### PR TITLE
Barking dogs

### PR DESCRIPTION
**Pull request by YakumoChen**
#### Summary:
```SUMMARY: Content "Dogs are noisy and bark a lot."```

#### Purpose of change
I thought it was weird that dogs didn't bark and wanted to see packs of dogs barking while chasing things.

#### Describe the solution
Dogs were given a Parrot special attack, like Mi-Gos. They bark at anything and everything now. Smaller dogs are yappier, big dogs make woofs.

#### Describe alternatives you've considered
Kevin mentioned off handedly that he wanted to implement a system where monsters could make noise when agitated. I'd rather have it where dogs only bark when aggressive (chasing things) but I'm also not a coder, so this was the best I could do.

#### Additional context
BARK BARK BARK BARK YAP YAP BARK BARK BARK WOOF
I'm not a coder, so please make sure everything looks square for me.
Also I'm not entirely sure how loud it should be, but 40 seemed to match a lot of louder Mi-Go phrases so I went with that.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
With your changes only one dog will be barking - the one you've added `PARROT` special attack to, `mon_dog`. I suggest adding this special attack to all kinds and types of dogs.

**Comment by Rivet-the-Zombie** [comment]
It should copy over since all the other breeds `copy-from` the `mon_dog`.

**Comment by Night-Pryanik** [comment]
Oh, never mind then.

**Comment by YakumoChen** [comment]
borf

**Comment by latogato** [comment]
Are attacking dogs bark? As i know they bark when agitated but never when they started to attack.
Source: every videos i saw about it and one personal experience with an attacking dog.

**Comment by MatthewGP** [comment]
A. Dogs will bark when threatened and they are unable to run away due to location or that they are defending a specific person or territory.
B. Most dogs will attempt to flee when possible.
C. Dog packs are also not known for being prolific barking sources unless they are cornering prey or situation A.
D. Solo dogs, if feral, will not normally bark if hunting.

This change should receive additional vetting before being merged if we are trying to be realistic.

**Comment by eilaattwood** [comment]
Hunting dogs ARE barking when tracking and fighting. It's intentional, because it helps human hunter to track where pray is and come to help. Of course, I don't know, how that instinct will trigger when dog is stray, without hunter companion nearby. But I think, it will still trigger somehow.

**Comment by MatthewGP** [comment]
@eilaattwood Please just literally google Why do dogs bark.  You can also google Training hunting dogs.  There is plenty of research explaining dog barking.

I didn't think it would be necessary, but:
E. Dogs trained for hunting or dogs from "hound breeds" such as beagles, coon hounds, etc are significantly more vociferous or trained to "alert" hunters to their whereabouts so that prey (see C. above) can be located.

Having all the dogs in the game barking all the time is completely unrealistic.

Just @ing @ZhilkinSerg also, it would be super if you could just double check that you think this should be merged in it's current state versus being a mod to have "all" dogs barking all the time.

**Comment by YakumoChen** [comment]
>Describe alternatives you've considered

>Kevin mentioned off handedly that he wanted to implement a system where monsters could make noise when agitated. I'd rather have it where dogs only bark when aggressive (chasing things) but I'm also not a coder, so this was the best I could do.

**Comment by latogato** [comment]
Please, don't let our comments bother you, it is nice addition and when they implement the "monsters could make noise when agitated" part in the code, it will be easy to adjust to it.

**Pull request merged**
