### PR TITLE
Aftershock Mi-go Turrets

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
SUMMARY: Mods "Mi-go Turrets"

#### Purpose of change
To give purpose to Mi-Go slaves.

#### Describe the solution
I added the the classic Mi-go brain powered turret.  

#### Describe alternatives you've considered
Not making abominations against man and god.  Arming it with the pain beam.

#### Testing
TBD in the morning.

#### Additional context
They ``Parrot``.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Argh,  I seem to have misunderstood how my branches worked and thought I could just add the commits that haven't already been accepted.  Do I need to create a new branch and then just bring those 3 files over that are actually new?  I'm not sure why it's showing all these files changed when they have already been added to the CleverRaven repo.

**Comment by Zireael07** [comment]
Nothing has been added to the CleverRaven repo because the PR is not yet merged. The only repo you're adding to is your own fork.

**Comment by Maleclypse** [comment]
> Nothing has been added to the CleverRaven repo because the PR is not yet merged. The only repo you're adding to is your own fork.
I completely understand why that would seem like the most common answer.  However, the first 44 commits from this branch were already merged in PR #35322 I had hoped that I could continue to use that branch without it listing the already merged files as changes.  Instead of it being 21 files and 850 lines it should be more like 3 files and 50 lines because all the rest are already in the CleverRaven fork.

**Comment by Zireael07** [comment]
Aaa, if your PR contains things that are already in CleverRaven, then you've messed up this PR.
If the other PR was yours, the error was that you continued to add stuff to the branch you've already PR'ed from. If the other PR was not yours, I don't even know.

In any case, you have to close this PR and re-do it on a new branch.

**Comment by Maleclypse** [comment]
> Aaa, if your PR contains things that are already in CleverRaven, then you've messed up this PR.
> If the other PR was yours, the error was that you continued to add stuff to the branch you've already PR'ed from. If the other PR was not yours, I don't even know.
> 
> In any case, you have to close this PR and re-do it on a new branch.

Yep, it's my branch, I had hoped that it would only count the new changes.  I'll create a new branch and recreate this PR. Thanks!

**Comment by Zireael07** [comment]
No problem ;) I've been a beginner git user once myself, so I know what it's like...

**Pull request closed without merging**
