### PR TITLE
[CR]Rescale vehicle collisions to get rid of megashrubs and insta-kills

### PR DESCRIPTION
**Pull request by Coolthulhu**
Fixed vehicle collisions healing monsters and slow vehicle collisions causing more damage to critters than moderate velocity ones (and causing a noticeable lag too).

Also, vehicle/terrain collision rebalance.
When bashing terrain and furniture, the old formula for approximating its mass and density was:

```
mass = 10 + max(0, bash_max - 30)
density = 10 + bash_max * 2.333
```

The new formula is:

```
mass = ( bash_min + bash_max ) / 2
density = bash_min
```

As a result, bashing stuff with cars mirrors bashing it with a pipe, rock or sledgehammer more closely instead of just correlating roughly with it.

When comparing densities: 15 is the density of creatures (all of them), mass is in kilograms (200 for a tank or a hulk, 81 for a human, 800 for a typical in-game car).
Density of car part depends on striking part: 30 for steel, 40 for hardsteel.

| Bashed stuff | Old mass | Old density | New mass | New density |
| --- | --- | --- | --- | --- |
| Shrub | 40 | 24 | 32 | 4 |
| Solid rock | 380 | 103 | 250 | 100 |
| Oak tree | 160 | 52 | 130 | 80 |
| Wall | 190 | 59 | 120 | 30 |

Meaning that collision with an adult tree is fatal (as in real life), while shrubs don't do much (may need adjustment, they do nearly nothing).

This makes walls quite weak, though. Suggestions welcome.

---

Also, vehicle-critter collisions. I wanted to get rid of the insta-kill on low speed collision (try driving over a hulk at 9 mph). Currently WiP.

This is a bit hard to adjust, because:
- Formulas for collisions with both objects moving in the same direction only make sense when the "chasing" object is faster than the "chased" one
- A creature can't be pushed away at speed lower than 10 mph
- If the creature isn't pushed away or killed, the vehicle must keep colliding until the sign of its velocity inverts or becomes 0

This gets problematic when we try to handle all the cases at once:
- A very heavy vehicle bumps into a small critter at low speed. It can't stop because it has huge momentum. The critter shouldn't die because the collision is at low speed. It must be pushed away.
- A very light vehicle bumps into a huge monster. The monster must not get pushed away and won't die, the vehicle should stop or go back.

### CODE REVIEW

**Comment by kevingranade** [comment]
I don't know if it should be an explicit flag, or just an adjustment to mass, but most of the resistance provided by walls, trees, and shrubs is going to be from the fact that they're attached to something with infinite mass (the ground) as opposed to their own mass.  Walls less so, trees to a large extent, and with shrubs it's the only reason they'd resist being moved at all.

One thing, why can't a creature be pushed away at a speed of 10MPH or lower?  If a large but slow-moving vehicle "hits" a person, moose, whatever, it's going to keep moving forward, and the obstacle is going to be pushed, the only question is whether the obstacle stays upright, and whether the obstacle and/or vehicle parts are crushed.  Now it certainly shouldn't be "flung", but pushing it one square back at a time makes sense.

**Comment by stk2008** [comment]
Wooot so no more shrubs wrecking cars if so I'm for this :)

**Comment by Zireael07** [comment]
on the topic of pushing <10 MPH

I believe normally it's pushed like that

X
---- dashes denote car (front, side, whichever slams)

maybe push them to the side instead?
----- X

so that they wouldn't keep colliding with the vehicle

**Comment by Rivet-the-Zombie** [comment]
Anything that fixes the **SHRUBS OF IRON** is good. We can sort out the walls later.

**Comment by Midaychi** [comment]
You could check the strength of the creature being hit I guess, and do damage based on how fast you were going at the collision vs that. Low strength creatures would be more flimsy, while high strength creatures would just be like 'u wot m8?'

Would be neat if high enough strength creatures could stop your car outright if their strength was large enough. I could see a hulk stopping a car going slower than 30 and then punching it into a skid.

**Comment by stk2008** [comment]
ha yeah them shrubs must have some kind of tough zombie genetics

I am not saying some big shrub wont do a little damage but it would mainly
only be cosmetic.

**Comment by Coolthulhu** [comment]
> One thing, why can't a creature be pushed away at a speed of 10MPH or lower?

Fling creature is quantized in 10 mph units.
If we allow pushing at speeds much lower than 10 mph, a bike will be able to push a hulk (with current algorithm, at least).

My current algorithm works like that:
* Calculate post-collision velocities based on masses, densities and velocities
* Deal damage based on energy differences between pre-collisions and post-collisions
* If post-collision velocity of the critter is >10.0, fling it `velocity/10.0` tiles and stop colliding
* If post-collision velocity of vehicle gets a different sign from pre-collision velocity, stop colliding
* Otherwise assign post-collision velocities and go back to start

With `velocity>10.0`, it's quite obvious that the creature has been pushed away.
Where should the "slow pushing" go?

> maybe push them to the side instead?

That would require finding a safe spot mid-collision. And collisions can be aborted (due to vehicle losing momentum later on), meaning said safe spot could become unsafe during the same collision.

**Comment by Coolthulhu** [comment]
Rebalanced collisions with critters:
* HUGE mons given mass of 1 (metric) ton. This makes them heavier than a car, but it still isn't enough to make sense. A hulk can still be pushed by a car that has no momentum
* If the car doesn't have enough momentum to push a critter, it stops rather than re-colliding multiple times. This prevents the insta-kill
* Sometimes (rarely) a critter gets pushed under the vehicle and then 3 tiles away. This is because of randomness involved in pushing a critter away. It's quite minor and the fix would have to be quite technical, so I'd let it be for now, unless someone has a simple way to fix it.

Changed [WiP] to [CR], because almost everything seems to be working, but I'd like someone to comment on shrubs posing only a tiny bit of resistance and drywalls being easily damaged by cars.

In a test, I was able to drive through a 9x9 horde of zombies with a regular car. I went in at 60 mph, got bogged down by the end of the horde, but then managed to wiggle out with the car only losing the windshield and some doors.
A sports car was able to drive through a drywall from a standstill, but then got smashed by the falling ceiling when inside.

**Comment by Midaychi** [comment]
I think that makes sense. It'd be nice to actually make an offroad vehicle that isn't made of tin foil.

**Comment by kevingranade** [comment]
When I test pushing through a horde, zombies end up in the vehicle every time I've tried it.

**Comment by Coolthulhu** [comment]
I'm not sure if it's possible to totally get rid of zombies "phasing" into vehicles with current collision logic, but a bulk of cases can be fixed by checking if the target was actually pushed away. In a horde, zombies get pushed into each other, which (in collision logic) is still treated as "pushed away" and thus passable.

The most "proper" way would be to keep checking collisions until none pop up (or the vehicle stops), but that would be expensive and could lead to infinite loops. I'll set it to repeat an arbitrary number of times - 3 sounds enough to eliminate most of the cases.

**Comment by kevingranade** [comment]
Aah, yes I think the majority of the cases are from flinging the monster into another monster then continuing forward.  A similar situation is if you hit a monster with a wall behind it.

I don't think monsters phasing into vehicles is unavoidable or acceptable, we should be able to prevent it entirely.

As long as a monster being flung consumes significant kinetic energy, it should be fine, although for a very massive but slow-moving vehicle the number of iterations might be large enough to be a problem.

One way to work around this in a natural way is to put flinging in a loop that increases the kenetic energy consumed with each iteration, so the first fling assumes open space behind the target, the second ramps it up a bit because it now knows there's an obstacle behind the target, the third increases it more because it's a *tough* obstacle behind the target, etc.  It should converge quickly on destroying the monster or the obstacle, or consuming all of the vehicle's kinetic energy.

Another option (probably overly-complex for this PR) is to have the collision code check the line behind the target, and treat everything in that line as a unit.  If there are a number of monsters, it would build up enough kinetic energy to either push the whole line to some open space behind them, crush one of them (and push the rest into the gap), or stop the vehicle.

**Comment by Coolthulhu** [comment]
Fixed most of the cases. When testing the fix, driving an APC through a horde only resulted in phasing when it turned and exposed the diagonals. With a regular car, the windshield and doors get wrecked quickly, so testing phasing doesn't work well.

**Comment by kevingranade** [comment]
I think my options would be nice to look into at some point, but I'm not seeing any phasing.
I AM seeing some "critter not found" type debug messages, though I suspect those aren't new.  I'll briefly take a look at those, but I'm considering merging it anyway.

**Comment by kevingranade** [comment]
I couldn't consistently reproduce the issue, and I'm pretty sure it's an unrelated issue about dealing with zombies jumping in a vehicle when it's moving, and the state after merging is incredibly better than it is without it.

**Pull request merged**
