### PR TITLE
Fix dazzling blinding you when already blind(folded)

### LINKED ISSUE #61097: Optical Dampers CBM does not block "blinding flare" effect from some enemies
### Describe the bug

Per the Optical Dampers description: "lenses surgically installed over your eyes can be tinted to block out incoming light", it seems like they should block 100% of incoming light, however I attempted to use them when killing a mil-spec searchlight since they blow up with a blinding flare on death, and noticed that I was still receiving the blinded message/effect even with the optical dampers enabled.

Even though it says "can be tinted", there's no qualification on what level of tint its referring to, and enabling them effectively blinds your character, so I assumed this is a bug.

### Steps to reproduce

1. Obtain Optical Dampers CBM
2. Enable optical dampers
3. Kill a searchlight or other enemy that emits the blinding flare
4. Examine log/status effects

### Expected behavior

With Optical Dampers enabled, killing a searchlight or other enemy that emits the blinding flare should result in that status effect being blocked

### Screenshots

N3NCeTn76Z

### Versions and configuration

-OS: Windows 10
-Game Version: experimental, 2022-09-17-0626, cdcb071 (tiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
None

#### Purpose of change

Fix #61097

#### Describe the solution

Add `BLIND` to `fd_dazzle`'s ~~worn~~ character immunity flags.
Handle blindfolds and similar optional worn field immunity flags by adding `immunity_flags_worn_any` to field type definitions - any one bodypart of the given types wearing their respective flag will grant immunity to the field in question.

#### Describe alternatives you've considered

None

#### Testing

Installed Glare Compensators before the change, walked into dazzling fields before and after activating it, got blinded both times.
After the changes only activated dampeners protect you.

After the optional flag changes both blindfolds and flash protection. will protect you from being blinded

#### Additional context

None?

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I'm working on fix for this issue as well. Please test your changes. Simple adding flag will make this CBM protect from dazzling even when it's non-activated.

**Comment by Venera3** [comment]
Looking at the code `"active_flags": [ "BLIND" ]` only confers the flag when activated, but fair's fair I suppose.

**Comment by Venera3** [comment]
Watch me forget bionics aren't considered worn like an idjit. Tested, works as inteded (worked on blindfolds until now, just not the bionic).
Thank you.

**Comment by Night-Pryanik** [comment]
My solution was to add check for active bionic with flag that grants immunity to `Character::is_immune_field`:
```
for( const bionic &bio : *my_bionics ) {
    if( bio.info().activated ) {
        if( has_active_bionic( bio.id ) && bio.info().has_active_flag( flag ) ) {
            return true;
        }
    }
}
```

**Comment by Venera3** [comment]
Active bionic flags are counted for `Character::has_flag` already, which routes this whole thing through my beloved charflags so that part was just sloppiness on my part. It did remind me that I ignored blindfolds, so I'll fiddle with it a bit to see if I can hook up a not-too-clunky solution.

**Pull request merged**
