### PR TITLE
Add additional military grade armored vests

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "Added heavier and lighter military armored vests and distributed them"

#### Purpose of change
This was moved to draft while some other changes happen to armor 

After some of the more recent changes to body armor it has opened up options for some more military grade armor that's cool, grounded in reality and gives players more true to reality options. 

#### Describe the solution

**THIS PR depends on #52826**

- I have modified the values for the current US Ballistic Vest to use the new proportional materials values.
- I have added 2 new armors with 4 total variations. Both armors work the same as the current ESAPI vest with ablative pockets.
- I have added spawn groups for the 2 new vests with possible plates
- I have done hopefully enough research on what the values for things should be

----------------------

**First off the math and numbers**
references:
IOTV Manual
https://www.benning.army.mil/Tenant/LRC/content/pdf/IOTV%20GEN%20III%20TM%2010-8470-210-10.pdf
Slick specs
https://lbtinc.com/products/6094slk

All of armors listed use Cordura (or something similar) nylon for exterior and aside from the light contain soft Kevlar inserts.

I **assume** all vests have 1.5 mm of thickness front and back of Nylon I couldn't find any info on exact thickness but it seemed a reasonable value for a thick outer material.

I needed to calculate the thickness of the Kevlar soft inserts.
I know that the groin protector is .92 pounds (417.3 grams)
I found measurements online for the whole vest as a costume https://image.dhgate.com/0x0s/f2-albu-g5-M00-64-B1-rBVaJFlYsCGAQrYyAAHVY9exJmM935.jpg/the-new-usa-iotv-interceptor-tactical-vest.jpg which estimates the groin cover at 22cm by 33cm 

I **assume** the groin guard is a rectangle to simplify my math 

I used this calculator https://www.aqua-calc.com/calculate/volume-to-weight/substance/nylon-blank-6 to get the weight of 3mm * 22cm * 33cm of nylon 6 at 246.24 grams

That leaves 171.06 grams for Kevlar. Using the values for estimating thickness in the JSON for Kevlar of 170 g/m2 = .25 mm of thickness, punching it all in gives 3.4 mm for Kevlar inserts. With all the simplification and using layered Kevlar I've rounded that down to 3 mm of layered Kevlar.

So the makeup of these vests and their pieces is 3mm of Layered Kevlar and 3mm of Nylon which is 9 bash armor, 12 cut armor, 24 bullet.

Most pieces have a soft insert of the same size as the container other than the larger vests on the torso. The soft armor doesn't completely cover under the arms so they will have a proportional material of .95

here is the updated values for the US Ballistic Vest based on these:
image

With that out of the way on to the implementation:

----------------------

A light weight plate carrier representing armor used by contractors and private citizens

Light weight is added to be a smaller less warm less encumbering option over the ESAPI vest for when you want some piece of mind but don't need full protection, or are in the middle of summer. 

>  [light ballistic vest](http://www.perrozdesigns.com/wp-content/uploads/2014/09/04_lpspc.jpg): The vest without armor plates in it. Based off the stats for the new Ballistic Vest. Can be found in military surplus stores

image

It also has a new item group military_ballistic_vest_light which is a vest + a 50% chance of an esapi plate twice: Can be found on lab security (maybe could be added to police but I didn't want to push it). It also could be added to bio-ops but I'm not sure.

----------------------
An implementation of the full American military [IOTV body armor](https://upload.wikimedia.org/wikipedia/commons/8/8e/MultiCam_IOTV.jpg)

IOTV body armor is added to be a heavier more flexible option over the ESAPI vest for when you want to make sure your protected giving arms and legs coverage on the shoulders, upper arms and hips. It's three variants are:

> [heavy ballistic vest](https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f5/IOTVFullImage.png/revision/latest/scale-to-width-down/713?cb=20190301090027) The complete heavy body armor kit with all the fixings. Can only be found on kevlar enemies making it quite rare and not available from day 1. Deconstructs/Constructs for a US ballistic vest, 2 ballistic deltoid protectors, 1 ballistic groin protector.

image

> [legless heavy ballistic vest](https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/95/IOTV_Assault.png/revision/latest/scale-to-width-down/795?cb=20190710085240) The IOTV without leg coverage. Can't be found normally you would need to deconstruct IOTV body armor (full) and craft this. Deconstructs/Constructs for an US ballistic vest, 2 ballistic deltoid protectors.

image

> [sleeveless heavy ballistic vest](https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/2f/IOTV_HMK.png/revision/latest/scale-to-width-down/591?cb=20190710085120) The IOTV without arm coverage. Can't be found normally you would need to deconstruct IOTV body armor (full) and craft this. Deconstructs/Constructs for an US ballistic vest, 1 ballistic groin protector.

image

It also has a new item group military_ballistic_vest_heavy which is a vest + a 50% chance of esapis and esbis: Can be found on Kevlar enemies.

Also added were the already mentioned spare parts: ballistic groin protector and ballistic shoulder protectors.

image

image

#### Describe alternatives you've considered

Adding more pieces for the IOTV to break into (neck guard, etc.) however it seemed overkill and you are already bottle necked on getting an IOTV before you can make another of any type. 

Changing and modifying numbers (which I'm still happy to do).

Not making this PR and wearing homemade kevlar stuff.

~~Waiting for the armor overhaul to be completely finished.~~

#### Testing

Loaded up the game, spawned all the items, killed some guards and kevlar soldiers, deconstructed some, crafted some.

#### Additional context

If these changes go through and people like them I may work on some additional crafts for versions of the three vests (slick, ESAPI, and IOTV) with added pockets and holsters (these would probably end up on bio operators and the like). As well a [riot duster](https://steamuserimages-a.akamaihd.net/ugc/693907274596083357/DA15FA86ACF40D67E2009076909E3F272A9871B8/) that uses a slick and IOTV shoulder plates.

### CODE REVIEW

**Comment by Amoebka** [comment]
Perhaps the groin and shoulder protectors should be thier own wearable items too? With the same 3 enc, 30% coverage stats they have when included with the suits.

**Comment by ISuckM8** [comment]
"Riot duster" Where the hell did you get that from, fallout?

Oh... he DID get it from fallout... 

I mean, how are you gonna explain it in the game's lore? It's not a real thing as far as I know (Well you can buy one on the internet but it doesn't protect you from bullets), maybe you can craft it with a high tailoring skill?

**Comment by Wishbringer** [comment]
If this gets merged after #52826 doesn't it cause the changes made in that to get reverted?
Because #52826 gets merged and then reverted in this branch that is?

**Comment by bombasticSlacks** [comment]
I'm no git wizard but my understanding is that after the first commit is squished and merged it has a seperate history so they won't interact in any way and this will squash on-top of it without trouble.

**Comment by kevingranade** [comment]
`As well a riot duster that uses a slick and IOTV shoulder plates.`
need a real-world example.

**Comment by Wishbringer** [comment]
Seems like changes made to ` data/json/recipes/armor/suit.json` by #52888 was lost when this was merged.

**Comment by bombasticSlacks** [comment]
you are correct it seems, a bunch of suit.json got modified by this PR...

**Comment by bombasticSlacks** [comment]
I'll go through tomorrow and fix it all

**Pull request merged**
