### PR TITLE
Generic_Guns: Ammo drop reduction

### PR DESCRIPTION
**Pull request by nikheizen**
Generic_Guns only has 6 different "calibers" and 6 different "barrel sizes".
This creates a problem which isn't the case in mainline: it's too easy to find more than enough ammunition for the guns you have. Without the problem of "10mm pistol, but 9mm ammo", you end up with too much. I think Generic_Guns is better without having this problem,  and in fact allows simulating it without being as absolute/all-or-nothing.

This patch reduces the amount of ammo you will find by ~50% for most ammo types by changing `count`. the rarer ammo (incendiary/AP rifle and heavy rifle), get a much smaller reduction since these are already rare enough and stacks of 5 ammo aren't good or fun when we don't have a gun which it makes sense to have such scant ammunition for.

There are also a few small tweaks here and there, as well as a typo fix which I found in the main itemgroups/ammo.json thanks to Night-Pryanik,

### CODE REVIEW

**Comment by mugling** [comment]
It would be helpful if you could somehow directly manipulate some `item_group` to yield less items. Would you mind putting this on hold temporarily whilst I look into how feasible that might be?

**Comment by nikheizen** [comment]
@mugling Of course. That would be a much more pleasant solution.
I would also be interested in reducing the number of guns which spawn (no
sense on having 8 pump action shotguns). I was thinking of perhaps
overriding the map files for some locations to do this, but I wasn't sure
if that would work.

**Comment by mugling** [comment]
> I was thinking of perhaps overriding the map files for some locations to do this, but I wasn't sure if that would work.

Would be fairly painful to do and would rapidly become outdated

**Comment by nikheizen** [comment]
Mmhm. Is there a better way?

**Comment by nikheizen** [comment]
Well, any news on that @mugling ?

**Comment by mugling** [comment]
Still short of a good solution

**Comment by mugling** [comment]
Struggling to rebase

**Pull request merged**
