### PR TITLE
Add roof to hunting lodge and cleanup unused features

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Add roof to hunting lodge"

#### Purpose of change

Add roof to hunting lodge and cleanup unused features.
Slight furniture tweaks around fireplace, such as chairs and adding fireplace to the second floor.
Fixes ground being rock instead of soil.

Done:
- [x] Add basic roof to second floor
- [x] Add roof level
- [x] Add roof terrain objects
- [x] Add misc. junk to roof
- [x] Figure out how to remove auto-created roof on top of standing tanks.
- [x] Consider adjusting downspout locations to make more sense
- [x] Basic Testing
- [x] Rotation Testing

Not happening in this PR:
- Figure out if there are options for mid-level downspouts that are better? Or remove them?
- Add more threats? For some reason the spawn zombie doesn't always happen. Might be a bug or need adjustment: `"place_monsters": [ { "monster": "GROUP_ZOMBIE", "x": 29, "y": 4 } ],`

#### Describe the solution

Update second floor and add a roof level

#### Describe alternatives you've considered

None

#### Testing

Spawned a bunch of lodges next to each other and checked everything looked correct. See additional context for final rotation test screenshots.

#### Additional context

I spawned two next to each other to test rotations, so some doors won't make sense between the two.
Floor 1:
image
image

Floor 2:
image
image

Roof:
image
image

### CODE REVIEW

**Comment by Maleclypse** [comment]
Thank you for doing this!

**Comment by Maleclypse** [comment]
Just noticed the diagonals in the middle of the second floor carpets both have two squares misplaced.

**Comment by haveric** [comment]
Oh, is it supposed to be a rotated rectangle? That makes so much more sense. I couldn't figure out whether it was intentionally done the way it was or if I was missing something. I'll tweak that when I am resolving conflicts.

**Comment by Maleclypse** [comment]
> Oh, is it supposed to be a rotated rectangle? That makes so much more sense. I couldn't figure out whether it was intentionally done the way it was or if I was missing something. I'll tweak that when I am resolving conflicts.

Yep. I’m a terrible interior decorator.

**Comment by haveric** [comment]
> Yep. I’m a terrible interior decorator.

Is that why there's bathtubs (hot tubs maybe?) in the open here? I'll be honest in that I didn't know the intention for some of the stuff, so I tried to keep the changes light that I did, especially since this was supposed to just be a roof fix, but I'm open to making more improvements if there were suggestions to be had. I was tempted to move the fireplace to a 3x1 placement along the wall as well, but remember a conversation from a while ago about wanting to have the giant 3x3 fireplace, so I just extended that upwards so it makes a little more sense.

**Comment by Maleclypse** [comment]
> > Yep. I’m a terrible interior decorator.
> 
> Is that why there's bathtubs (hot tubs maybe?) in the open here? I'll be honest in that I didn't know the intention for some of the stuff, so I tried to keep the changes light that I did, especially since this was supposed to just be a roof fix, but I'm open to making more improvements if there were suggestions to be had. I was tempted to move the fireplace to a 3x1 placement along the wall as well, but remember a conversation from a while ago about wanting to have the giant 3x3 fireplace, so I just extended that upwards so it makes a little more sense.

It is roughly based and a smaller scale on the main building of a 70’s hunting estate that a friend’s family bought in a bankruptcy auction. Those are in fact representing the random open room hot tub from when they first bought the place. So the three variants were designed to be “swinger pad”, drug distribution, and cannibals with the above floors looking pretty similar no matter what and the basement having the key.

**Comment by haveric** [comment]
Seems reasonable enough. I know I tried to find examples to compare it to and honestly struggled to find anything I wanted to reference.

Hot tub furniture might make sense just to avoid the confusion, but I suspect it would act the same, so it's not that big of a deal. I also considered adding some head/antler mounts as decoration, but didn't want to bloat the scope of this any more.

I should probably double check the basement carpet layout as well. I remember it being slightly odd, but I didn't change anything, so I assumed it was designed that way. Will update when I get a chance to look at this after work.

**Comment by Maleclypse** [comment]
> Seems reasonable enough. I know I tried to find examples to compare it to and honestly struggled to find anything I wanted to reference.
> 
> Hot tub furniture might make sense just to avoid the confusion, but I suspect it would act the same, so it's not that big of a deal. I also considered adding some head/antler mounts as decoration, but didn't want to bloat the scope of this any more.
> 
> I should probably double check the basement carpet layout as well. I remember it being slightly odd, but I didn't change anything, so I assumed it was designed that way. Will update when I get a chance to look at this after work.

Head and antler mount furniture or walls would be pretty cool.  I'm gonna ask about that in tileset channel.

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
Thank you for this!

**Pull request merged**
