### PR TITLE
Typos and Engrish

### LINKED ISSUE #65911: Hub 01 Bar punctuation issues and apricots
### Describe the bug

During the long trundle of translation, I spotted a number of punctuation inconsistencies in the hub 01 bar dialogue which I'll list here as well as the needed fix, it's mostly missing periods/extra punctuation marks:

- Just making sure people don't ask stupid questions -> Just making sure people don't ask stupid questions.
- Sorry I rather be left alone right now -> Sorry I rather be left alone right now.
- Take the anchor and leave the coin.  Its a deal?. -> Take the anchor and leave the coin.  Its a deal?
- Sure, let see what you offer -> Sure, let see what you offer.
- It'll get done -> It'll get done.
- Not interested after all -> Not interested after all.
- [5 HGC] Its a deal -> [5 HGC] Its a deal.
- Sure, just let me find the cash -> Sure, just let me find the cash.

I'm less sure of the following three since they seem to be written prompts of actions rather than dialogue, so not sure if they should have punctuation, but some similar descriptions of actions in this dialogue section do?

- Offer to buy the anchor for 1 HGC -> Offer to buy the anchor for 1 HGC.
- Attempt a friendly approach -> Attempt a friendly approach.
- Press on in search of a reaction -> Press on in search of a reaction.

Additionally, completely unrelated aside from the fact that I found these issues at roughly the same time, and this is the reason I added apricots in the title, the description and item name of "handful of irradiated apricots" is inconsistent as it is the following:

- An irradiated apricot.

The description should probably be changed to refer to multiple apricots just like the description of the regular handful of apricots.

### Attach save file

N/A

### Steps to reproduce

1. For the dialogue:
2. Talk to the people in the Ancilla bar
3. Look at the dialogue for the listed typos
4. For the apricots:
5. Irradiate apricots

### Expected behavior

Expected behavior for all of this is for there to be no typos

### Screenshots

_No response_

### Versions and configuration

Typos spotted on Transifex, so in game as of latest experimental

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Bugfixes "Minor typo, strange wording and grammar corrections"

#### Purpose of change

Fixes #65911

#### Describe the solution

Fixes identified typos and adds some additional changes in the same files.

#### Describe alternatives you've considered

"I don't need anything, just gotta go." is still fairly odd but I don't really know what they were going for and it's currently obsoleted anyway

### CODE REVIEW

**Comment by Ruminator24** [comment]
Not sure if intentional, but i think 
"Now if you please, I have a meal to ger rid off.\"
Should be 
"Now if you please, I have a meal to get rid of.\"

**Comment by Procyonae** [comment]
> Not sure if intentional, but i think "Now if you please, I have a meal to ger rid off." Should be "Now if you please, I have a meal to get rid of."

I took that as being a gruff sounding accent but without consulting whoever wrote it idk how to gauge it

**Comment by sadenar** [comment]
Before this goes, I found a few NPC complaints that need capitals at the start:

- my days are [swear] numbered -> My days are [swear] numbered
- didn't think it would end like this. -> Didn't think it would end like this.
- bury me somewhere nice, if I don't make it -> Bury me somewhere nice, if I don't make it
- so, this is how it ends, huh? -> So, this is how it ends, huh?

Then again I might be wrong and those might be used with other snippets, you might want to check that first.

**Comment by Procyonae** [comment]
> Before this goes, I found a few NPC complaints that need capitals at the start

Most of the time they're not meant to have capitals from where they can crop up, it's not perfectly consistent though as far as I can tell

**Pull request merged**
