### PR TITLE
Properly fix debug storage

### PR DESCRIPTION
**Pull request by BrettDong**
Thanks to @sired22 for pointing out my mistake! I broke the original meaning of the expression.

### CODE REVIEW

**Comment by Qrox** [comment]
This is causing overflow again... When debug storage is on, the expression is equivalent to
```c++
( INT_MAX - g->u.weight_carried() ) * 1000;
```
Which will most likely be negative due to overflow, and I cannot pick up single items in AIM with this change. 

The previous fix works fine for me. It does not break the meaning of the expression, since that "meaning"  inevitably leads to overflow. (I tried casting the part before multiplication to long but that did not work. It seems that int and long are equivalent on my compiler).

**Comment by BrettDong** [comment]
@Qrox @sired22 Would you like to contribute a proper fix? I'm pretty busy and tired on my daily work and life recently and apparently I can't make my mind concentrated and give a thorough fix.

**Comment by sired22** [comment]
like i said in the first post i don't know enough about c++ to code something like that and that i could be wrong.

From what i think i can see you are * 1000 to both when you only need to do it to the one that's not int_max.

if you sort that out and it still doesn't work with the debug carry then you need to check if something else is doing it.

make sure not to mix up max_weight and weightmax in your edits though, i see both declared in just that small 'files changed' blob.

**Comment by AMurkin** [comment]
Done in #21126

**Pull request merged**
