### PR TITLE
Corrected formula and rewrote description for contruction scaling

### LINKED ISSUE #20291: Construction scaling option doesn't work like its description
The description for the world option "Construction scaling" says: _**"Multiplies the speed of construction by the given percentage"**_

With that description, I would expect a setting of 50 to double the construction speed, (eg: Construction speed 1h x 50% => 30 minutes), but the opposite happens, it doubles the construction time instead.

A fix for this would either be to change the description, or swap the calculation in construction::time_scale() in construction.cpp, like this:

```
float construction::time_scale() const
{
    //incorporate construction time scaling
    if( get_world_option<int>( "CONSTRUCTION_SCALING" ) == 0 ) {
        return calendar::season_ratio();
    } else {
        return get_world_option<int>( "CONSTRUCTION_SCALING" ) / 100.0;
    }
}
```

Please note I didn't check what "calendar::season_ratio" returns, but I assume this is correct.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20291.

As @Moumix3 suggested.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Compatibility question: do we assume users trusted the wrong description or actually figured out what is happening (from earlier PR description, forum thread etc.) and ignored the invalid description?

**Comment by kolsurma** [comment]
Never assume anything, if possible. 
On first load of an old save it should prompt the user if the value has changed from the default. The option in the menu should probably also have an example of proper usage, 50% makes a 1 day construction project take 12 hours, 200% makes it take 2 days.

**Comment by kevingranade** [comment]
If they're keeping up with development on the forums or github, hopefully they'll keep doing so and notice the fix, otherwise I doubt they noticed.

I'd welcome some minimal infrastructure to savegame migration to add the option-changing prompt, but I don't want to hold up the obviously correct fix to wait on someone implementing it.  This change doesn't have permanent effects, it can be changed at any time, so I'm not too concerned about it ruining someone's game.

**Comment by Night-Pryanik** [comment]
Updated description as @kolsurma suggested. Used skill training speed as a reference.

**Pull request merged**
