### PR TITLE
Fixed amount of nails get from clearing the rubble

### LINKED ISSUE #26162: Excessive yield of nails from cabin rubble
**Describe the bug**  
A collapse porch and corner of a cabin in the woods yielded almost 9000 nails.

**To Reproduce**  
1. Find cabin innawoods
2. Look for rubble
3. clear rubble

**Expected behavior**  
I would expect there to be maybe a few hundred nails, in the rubble

**Screenshots**  
excessive_nails

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33196-g90d0a9b
 - Graphics version: Tiles
 - Mods loaded: Makeshift items, more survival tools, extended buildings

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Fixed amount of nails get from clearing the rubble."```

#### Purpose of change
Closes #26162.

#### Describe the solution
Replaced loop of spawning sets of 200-charges nails by `add_item_or_charges` with single `spawn_item`. Also made amount more randomized.

### CODE REVIEW

**Comment by kevingranade** [comment]
This spawns between 1-10 nails per tile? My really lowball estimate was putting it at ~35.
Or am I missing something?

**Comment by Night-Pryanik** [comment]
I can increase it, of course.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by adamkad1** [comment]
nails get!

**Pull request merged**
