### PR TITLE
Fixed "Craft consumes materials and won't start #33146"

### LINKED ISSUE #33146: Craft consumes materials and won't start
Game version:
0.D-6009-ged290b3a24-dirty

### Steps to reproduce the behavior

* load the game
* spawn 2 planks
* `eh&4Y`
* the planks are consumed but the craft is unchanged, requiring a new portion of planks again, spewing a backtrace:
```
20:29:17.569 ERROR : (error message will follow backtrace)
	./cataclysm(_Z21debug_write_backtraceRSo+0x43) [0x563d3f9c3fa5]
	./cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x1f2) [0x563d3f9c4c1c]
	./cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xba) [0x563d3f9c5740]
	./cataclysm(_Z12realDebugmsgIJEEvPKcS1_S1_S1_DpOT_+0x46) [0x563d3f8ae209]
	./cataclysm(_ZN6player21select_item_componentERKSt6vectorI9item_compSaIS1_EEiR9inventorybRKSt8functionIFbRK4itemEEb+0x71a) [0x563d3f9a375c]
	./cataclysm(_ZN6player18can_continue_craftER4item+0x343) [0x563d3f9a465d]
	./cataclysm(_ZN17activity_handlers13craft_do_turnEP15player_activityP6player+0x110) [0x563d3f89e916]
	./cataclysm(_ZNKSt8functionIFvP15player_activityP6playerEEclES1_S3_+0x24) [0x563d3f8c5f2c]
	./cataclysm(_ZN15player_activity7do_turnER6player+0xaf) [0x563d3feb2331]
	./cataclysm(_ZN4game16process_activityEv+0x79) [0x563d3fa4d1d5]
	./cataclysm(_ZN4game7do_turnEv+0x48d) [0x563d3fa6d263]
	./cataclysm(main+0x11b5) [0x563d3f8281da]
	/lib64/libc.so.6(__libc_start_main+0xeb) [0x7fb482c56ecb]
	./cataclysm(_start+0x2a) [0x563d3f88608a]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:621
	DebugLog(DebugLevel, DebugClass)
	.../src/debug.cpp:786
	realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	.../src/debug.cpp:108
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:657
	void realDebugmsg<>(char const*, char const*, char const*, char const*)
	.../src/debug.h:79
	player::select_item_component(std::vector<item_comp, std::allocator<item_comp> > const&, int, inventory&, bool, std::function<bool (item const&)> const&, bool)
	.../src/crafting.cpp:1442
	player::can_continue_craft(item&)
	.../src/crafting.cpp:1251 (discriminator 3)
	activity_handlers::craft_do_turn(player_activity*, player*)
	.../src/activity_handlers.cpp:3332
	std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:688
	player_activity::do_turn(player&)
	.../src/player_activity.cpp:80
	game::process_activity()
	.../src/game.cpp:1619
	game::process_activity()
	.../src/game.cpp:1607
	game::do_turn()
	.../src/game.cpp:1441
	main
	.../src/main.cpp:688
	__libc_start_main
	??:?
	_start
	??:?
Backtrace emission took 1 seconds.
```

### PR DESCRIPTION
**Pull request by ipcyborg**
## Summary
SUMMARY: Bugfixes "Craft consumes materials and won't start #33146"

#### Purpose of change
Fixes #33146

#### Describe the solution
It requires fabrication 2, but the player has 0 (see save file attached to issue description).
The game should report something like "You mess up and destroy the towel", etc. But failed to do so.

Fixed the issue by handling duplicate components requirements. 
Function `craft_command::create_in_progress_craft`  will now combine duplicate types of components required, so other algorithms (component consumption) will not fail.

Tested: player with fabrication 0 will waste a lot of components trying to craft `towel hanger`. The game reports about every failure.
Tested: player with fabrication 2 can craft the `towel hanger` without wasting components. 

#### Describe alternatives you've considered
Fix only the recipe by simplifying it (remove duplicate components). Considered bad solution.

#### Additional context
None

### CODE REVIEW

**Comment by ymber** [comment]
This changes the meaning of the recipe. It's supposed to require 2 2x4s AND (2 2x4s OR 2 sticks). This makes it require 2 2x4s OR 2 sticks. It's an oversight in the crafting code if it doesn't handle the original recipe.

**Comment by ipcyborg** [comment]
Yes, looks like I have to continue with the alternative solution. 
I will revert that change in the recipe.

**Comment by Rail-Runner** [comment]
Couldn't a towel hanger be nailed together from sticks, anyway? It's not something that needs to be terribly complex, precise or durable.

**Comment by ipcyborg** [comment]
> Couldn't a towel hanger be nailed together from sticks only, anyway? It's not something that needs to be terribly complex, precise or durable.

Yes, but changing the recipe looks like avoiding the issue with duplicate components. 
Which should be fixed sooner rather than later.

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Is it possible to re-do this check: `continuous-integration/travis-ci/pr`?

**Pull request merged**
