### PR TITLE
Headless zombie tweaks

### PR DESCRIPTION
**Pull request by TheMurderUnicorn**
#### Summary
```SUMMARY: Balance "Attempted to balance 'headless' zombies."```

#### Purpose of change

Brainless and Listener zombies were spawning too frequently and were largely useless.  This attempts to make them more viable as enemies as well as reduce their spawns.  Similarly, Skull Zombies were evolution only, but I've now added them to monstergroups.

#### Describe the solution
Reduced Brainless and Listener Zombie spawns across the board.
Added Skull Zombie to a couple of monstergroups, hopefully at sufficiently low frequencies.
Gave Brainless day vision, where they were previously completely blind.  From a flavor perspective, they're still blind, but I've given them vision so they can actually track the player a little better.
Increased vision of Listener Zombie for the same reason.

#### Describe alternatives you've considered
Leaving it alone.  But I'm pretty sure I'm supposed to clean up any stuff I add that isn't working right, so . . . I'm trying to do that.

#### Additional context
I'm ready to call these 'good enough' and never mess with them again, if I'm being honest.

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/brainless-and-listener-zombies/19232/27

**Comment by paulenka-aleh** [comment]
To me IR only vision would make more sense so that zombie would go to anything warm except zombies.

**Comment by Firestorm01X2** [comment]
It is better to merge this first:
https://github.com/CleverRaven/Cataclysm-DDA/pull/28797

People starting editing spawn lists freqently with small chunks. My PR edits a lot of them.

**Comment by TheMurderUnicorn** [comment]
Fair enough.  I'm a bit confused by some of the changes made in that PR.  It looks like a lot of stuff has changed with the monstergroups, so I think it's better for me to get this PR closed and then look at it again from scratch after #28797 resolves.

Could someone please delete this PR?  Or close it or whatever.  I don't know how or if I'm allowed to.

**Comment by Night-Pryanik** [comment]
> Could someone please delete this PR? Or close it or whatever. I don't know how or if I'm allowed to.

You can close your own PRs by yourself, no permission from anyone needed.

**Comment by TheMurderUnicorn** [comment]
x_x  Still bad at Github.  Thanks for teaching me something.

**Pull request closed without merging**
