### PR TITLE
Survivor armor uses better materials, small adjustment to thickness

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Survivor suits use better materials"

#### Purpose of change
Survivor suits are should be made of the best materials available to a common survivor. As they're the "best" a survivor can do on their own, there shouldn't be any compromises made with materials or techniques. Cotton and leather were holdovers from a long time ago when they were the only real option, but they have inferior sturdiness and breathability compared to modern fabrics. Leather is especially guilty of this being extremely stiff and warm while not notably protective compared to other materials.

#### Describe the solution
Kevlar jumpsuits now use Lycra as their inner layer. With excellent breathability and in game, better or equivalent defensive value than cotton or leather, and equal or superior flexibility, it's a clear improvement. Further, moisture wicking properties are incredibly useful, keeping you cool in summer and warm in winter. The 0.2mm inner layers of cotton and leather are now lycra, and the recipes require stretch fabric and appropriate materials to craft. 
Other changes:
- Adjusted thickness of the survivor suits. Kevlar is not a very restrictive material as a fabric, and while these suits were previously made of layered kevlar which might be stiffer, thickness was not adjusted when the material was changed. Encumbrance was unchanged.
- Light Kevlar jumpsuit's main kevlar layer goes from 1.0->1.3. The suit is 1.5mm at its thinnest and 2.5mm at its thickest. (90% of sections)
- Regular Kevlar jumpsuit went from 1.0->2.0. Bigger jump here as it lost the leather layer, so it can handle a bigger boost for equivalent encumbrance. 2.2mm at its thinnest. 4.2mm at its thickest (81% of sections). Warmth increased to 25 from 15.
- Heavy Kevlar jumpsuit went from 2.0->2.6. The biggest and sturdiest inner layer to support the heavy steel plating. Thus it is 2.8mm at its thinnest, with up to 1.2mm of steel in its thickest sections. Warmth increased to 25 from 15.
- Winter survivor suits are 0.2mm Lycra, 2mm fur as they were previously, plus the kevlar layer went from 1.0->1.3mm like the light kevlar suit. 3.5mm at its thinnest, 4.5 at its thickest, with the highest encumbrance as usual.
- Jumpsuits are now crafted with higher-quality tools. You need Sewing 2 and Fabric Cutting 2 when previously you only needed sewing 1. Since you're working with Kevlar, you need Kevlar shears, so the requirements are stiffer.
- Jumpsuits now require high quality thread. I introduced a new version of the "filament_durable" requirement which is *only* nomex and kevlar threads. No more making your endgame armor with wool strands and muscle fiber threading.
- Bugfix: Survivor suits are now made with regular kevlar sheets, instead of layered kevlar, which was *not* changed when their material became regular kevlar. Material cost increased appropriately.
- Bugfix: Survivor Firesuits are made with Nomex, instead of Neoprene 

#### Describe alternatives you've considered
Different thickness values.

#### Testing
Loaded up in game and viewed each survivor suit in the crafting menu and each one looked OK.

#### Additional context

Screenshot 2022-04-07 122456

Screenshot is out of date, it no longer needs the arc welder group. Will update when I can.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
It would be nice to see screen shots of the new stats. 

I haven't looked too hard at the balance stuff but all the recipe changes seem very good 👍

**Comment by anoobindisguise** [comment]
> It would be nice to see screen shots of the new stats.
> 
> I haven't looked too hard at the balance stuff but all the recipe changes seem very good 👍

Apologies! I'll grab some screens of the different armors that were changed when I get a chance later. I posted what I had in additional context.

**Comment by anothersimulacrum** [comment]
Here are comparisons.

<details>
<summary>Comparison</summary>

| Before                                                                                                          | After                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

</details>

**Comment by Termineitor244** [comment]
The only problem I could have with this is that both Kevlar and Nomex thread does not currently spawn in game, and must be obtained from disassembling things with them...

Could you at least add the Nomex thread to some spawns?

**Comment by anoobindisguise** [comment]
> The only problem I could have with this is that both Kevlar and Nomex thread does not currently spawn in game, and must be obtained from disassembling things with them...
> 
> Could you at least add the Nomex thread to some spawns?

I can try and find some spots for it. Tailor supplies, plus layered kevlar ought to be made from it so it can be disassembled there too.

**Comment by andrei8l** [comment]
While you're there, can you also update the steel-plated jumpsuit to cover both the normal and outer layers?

**Comment by bombasticSlacks** [comment]
The idea with the steel plated was its thin enough (with the split armor layers) to be on normal so you can wear a jacket with it. 

With the rigid changes you can't wear plate mail or anything with it anyways, basically all moving it to outer will do is make it conflict with jackets.

**Comment by anoobindisguise** [comment]
Aramid threads ARE available for purchase for hobbyists in lots of places so I don't think it's unreasonable that a tailor has the odd spool stocked here and there.

**Pull request merged**
