### PR TITLE
Implement viewing tiles on the floor below the current one when an open floor is shown for SDL tiles.

### LINKED ISSUE #15020: Climbing in tiles mode shows sea of blue sky and no walls
When you climb walls with z levels on in tiles mode, all you see is blue sky.

This is ASCII:

Image

And this is tiles:

Image

I was thinking it might be overlaying the blue sky over some tiles, but I made it transparent and was left with this:

Image

Which does show the walls, but one off. And no fair loading your map or inventory. And the weather plays the worlds quickest game of connect four.

### PR DESCRIPTION
**Pull request by DanmakuDan**
Fixes #15020.

This makes a similar attempt to ASCII mode's `draw_from_above`. Some details are lost since ASCII highlights aren't being used. The appearance of some squares is obscured depending on the graphics used for "t_open_air" (open air) and "tr_ledge" (ledge "trap" that allows falling down a level). The size of the squares is also dependent on the tileset's tile sizes. Larger squares indicate the walkable area, smaller squares aren't walkable (vehicle squares are walkable if they have a roof, but it's not exactly clear in ASCII mode either).

fromabove1
fromabove2
fromabove3
fromabove4
fromabove5
fromabove6

### CODE REVIEW

**Comment by Malkeus** [comment]
Oh my, this is amazing! I hope someday to be able to climb up on the roof of my car to have a final stand against the horde...

**Comment by Zireael07** [comment]
Great!

**Comment by Rivet-the-Zombie** [comment]
Wonderful!

**Comment by stk2008** [comment]
holy crap yesssssssssss ahhh merge merge all ready... :)

**Pull request merged**
