### PR TITLE
[Innawood] Rework most recipes, uses copy-from when possible, makes portable soldering iron craftable

### LINKED ISSUE #70179: Soldering iron roadblock in Innawood
### Describe the bug

There is a point in Innawood progression, where you create soldering iron and batteries. However, the current implementation of the Soldering iron can not be reloaded with a battery, it requires a connection to a network. 
Portable soldering iron can not be crafted at that stage, so the player is stuck. 
The only solution to debug create a portable soldering iron. 
A member of Discord said that the recipe hasn't been updated to have the portable soldering iron for innawoods.

### Attach save file

Not required I beleive

### Steps to reproduce

With Innawood and DinoMod on. 
1. Get to the progression stage where soldering Iron can be crafted, but portable can not. 
2. Get stuck 

### Expected behavior

Either being able to reload a soldering iron, or be able to craft a portable one at the same time when a normal one is researched. 

### Screenshots

SD1
SD2

### Versions and configuration

Experimental 
Build 2023-12-122-1858

Mods:
Innawood
DinoMod
Other default mods

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Bugfixes "[Innawood] Makes soldering iron craftable, updates some other recipes to match mainline"

#### Purpose of change
Blocked by #63931
- Make progression in the mod possible again.
- Make maintenance of the mod easier.
- Make the mod more readable.
- Make the mod smaller.

Fixes #70179

#### Describe the solution
- Make progression possible again by making the portable soldering iron craftable using the same recipe as the non-portable version
- Use copy-from when possible, thus preventing recipes in Innawood from unintentionally starting to differ from recipes in mainline.
- Made it more clear what parts of the recipe that the mod tries to alter
- Added comments to Innawood-specific recipes to remind me why there are there
- Removed some recipes that are now craftable in mainline without the help of the mod

#### Describe alternatives you've considered

- If I had understood copy-from better when I started on this mod, I would probably have used it from the start.
- Do something about ammonia not being craftable. I'm leaving this problem for now.
- Using copy-from with flintlock weapons caused problems with Generic Guns. Would have been nice to fix this in a more elegant way, but specifying the entire recipe in Innawood works well enough.

#### Testing

I've loaded in a world successfully and looked at some of the recipes. But it is quite possible that I made a minor mistake somewhere in the code.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Presumably closes #70179 on merge

**Comment by Light-Wave** [comment]
> Presumably closes #70179 on merge

Indeed, thank you. Added that to the summary.

**Comment by Karol1223** [comment]
You may wanna keep #63931 in mind when adding ``copy-from`` to recipes. It's a slippery slope.

**Comment by Light-Wave** [comment]
> You may wanna keep #63931 in mind when adding `copy-from` to recipes. It's a slippery slope.

Thanks for letting me know!
Do I understand correctly that any problems caused by this bug would cause errors, so if I have no errors then I'm currently okay?

**Comment by Karol1223** [comment]
> Thanks for letting me know! Do I understand correctly that any problems caused by this bug would cause errors, so if I have no errors then I'm currently okay?

One would hope so, but I won't vouch for it

**Comment by Light-Wave** [comment]
Okay the following code
  {
    "type": "recipe",
    "result": "soldering_iron_portable",
    "copy-from": "soldering_iron"
  }
Gives me this recipe: 
image

Yeah... I think copy-from is quite broken.

**Comment by Karol1223** [comment]
> Yeah... I think copy-from is quite broken. Real shame.

That's the case with most places where ``copy-from`` can be used, honestly. The only definitions I can vouch ``copy-from`` more or less functions as intended are items and monsters.

I know Procyonae has been working on making better support for it when it comes to terrain and furniture (last time I used it there, it just copied like two fields and nothing else). I think recipe support is in limbo.

**Comment by Light-Wave** [comment]
I see. Unfortunate but understandable. Thanks again for bringing this to my attention. I'll just close this for now and instead create another PR that just adds a recipe for the portable soldering iron the old way; without using copy-from.

**Pull request closed without merging**
