### PR TITLE
Fixes Transferred from #10837

### PR DESCRIPTION
**Pull request by JoeKlesczewski**
These fixes were in my old pull request, #10837, but unfortunately circumstances forced me to abandon it and by now it is far too late to integrate the changes cleanly and easily. Indeed, many of the things the pull request were intended to address appear to have been addressed in the meantime. This is where I will be putting the changes I am able to recover from that pull request.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Explosions need a different noise volume formula now that firearms make 150 noise.
Grenade creates an explosion with 12 power. With current formula, that's 120 noise (less than a pistol). With the formula in this PR, it would be 12 noise, which is comparable to bike horn.

**Comment by JoeKlesczewski** [comment]
Ah, I see. Fair enough, will reverse momentarily

**Comment by JoeKlesczewski** [comment]
Hm. I've traced the `explosion_distance_factor` value back through the code trying to figure out if it's already fractional (if it isn't then we may be having explosions whose power is going *up* exponentially with distance instead of down), but I've kind of dead-ended in iuse_actor.cpp.

It looks to me like it is loading the value for the field from a JSON, but none of the JSONs I've checked include such a field - am I missing something here?

**Comment by Coolthulhu** [comment]
Explosion force at a tile is roughly `power * factor ^ distance` (minus random factor).
Explosion expands from all the tiles for which the force calculated by the formula above is >= 1.
If something calls `do_blast` with factor >= 1, the game will debugmsg to avoid covering the entire map with an explosion.

**Comment by JoeKlesczewski** [comment]
Ah, I see it now. Thanks

**Comment by JoeKlesczewski** [comment]
Looking at the code, it does appear it was factor ^ distance instead of distance ^ factor - I went ahead and changed this to reflect reality.

**Comment by JoeKlesczewski** [comment]
And now that all the checks have passed, I think this pull request is finally done - most of the stuff in my old pull request has been rendered redundant by far better code from others.

**Comment by Coolthulhu** [comment]
> Er, wait - shouldn't that be distance ^ factor?

Nope, it's supposed to be more game logic than realism here. It's rather hard to get good explosives with inverse square, they become very weak except in epicenter.

**Comment by JoeKlesczewski** [comment]
I don't follow - wouldn't "good" explosions fall off with distance? Now that fragmentation is modeled, I would think that the actual "blast" damage would be reasonably minimal after a couple tiles for, say, a hand grenade. After three tiles that's still ~11% power, which isn't actually much different from the 12.5% power currently used.

**Comment by kevingranade** [comment]
There was disagreement about the explosion scaling change, so I merged the rest.  Feel free to resubmit that change, but I didn't want it holding up the obviously correct changes.

**Comment by JoeKlesczewski** [comment]
I'll do so right away, @kevingranade - but since I'm still unused to the GitHub interface, I do have a couple of questions:

1. How does one "resubmit" commits - should I create a new pull request with the same branch, or should I create a new branch and redo the commit in question?
2. What do you mean "merged the [correct changes]"? Is there another pull request somewhere that I should reference for that, or is this one somehow partially merged?

**Comment by kevingranade** [comment]
You should be able to make a new pull request with the same branch, I think
that will do what we want.
And you have it, this PR is partially merged, I grabbed all the commits
except the last one.

**Comment by JoeKlesczewski** [comment]
Good to know.

GitHub is quite the nifty service, I have to say. Very powerful.

**Pull request closed without merging**
