### PR TITLE
mercenary attire

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "mercenary attire"

#### Purpose of change
After discussion on the discord my original #53533 now seems a little silly. It attempts to maintain old static armor instead of bringing it into the modern overhaul framework properly.

#### Describe the solution
Obsoleted Scavenger Armor,
Obsoleted the recipe,

Split the Scavenger gear up to be a top and bottom so that you can wear it with a tail or whatever.

Remove all the additional strapped storage and make the new pieces not belted. This allows for more customization instead of being stuck with the exact layout they originally had.

Added molle attach to the top.

The bottoms are now normal and outer layer since they are a pair of pants. This may crush some survivor suit gamers, but the double pants were a real oddity before. 

Streamline the recipes.

While I was there I also updated the storage of cargo pants and army pants to be in line with other storage giving them a .6 multiplier, which is .3 when they are properly fitted. I also set their base encumbrance to that of reasonable pants. Reason I did this here is so that the mercenary version isn't magically better in every way for some reason. 

#### Testing
game loads armor appears

#### Additional context
Top
image

Bottoms 
image

### CODE REVIEW

**Comment by Marrim** [comment]
So the jacket is basically a variant on heavy ballistic vest?
How do the pants compare to survivor cargo pants?

**Comment by bombasticSlacks** [comment]
The stats are included above.

**Comment by bombasticSlacks** [comment]
You are right on the plastic good catch. 

The knee pads / elbow pads made the armor definition a mess. The UI had trouble describing it correctly. It also leaves the shoulder/hips uncovered with additional padding, the spread out / sometimes missing extra armor when consolidated to just 1 set of values for the whole arm was an unintelligible mess. Spreading out the panel padding on all bits has similar protection and coverage functionally. Plus now if you really want the extra protection you can wear knee/elbow pads separately, it'll cost a lil extra encumbrance but that's not the end of the world. 

I think something with the "scavenger" moniker could be made but padded military clothes don't really fit that description now that they aren't covered in bags.

**Comment by TheShadowFerret** [comment]
> The stats are included above.

> remove plastic from materials list

*Poke* 😛

image
image

**Comment by Marrim** [comment]
The scavenger suit had lost some of its "scavenging" utility once its huge storage space got transformed into lots of relatively small pockets. The original intent was something that is both protective (esp. against environment) and provides ample storage space for loot, but isn't as good as dedicated armors. Sort of Stalker-esque thing.

The niche it takes after the pockets change is more like customized combat gear for long missions where you can carry a lot of supplies if you take the time to organize the pockets. So "mercenary" indeed sounds better.

With this, however, we lose one of the few non-backpack articles that can fit an UPS.
Now I'm thinking of designing an UPS case to attach to load-bearing vests...

**Comment by bombasticSlacks** [comment]
Lil spoiler looking ahead but XEDRA are going to have LBVs with built-in UPSs to power more XEDRA themed goodies that are coming :)

**Pull request merged**
