### PR TITLE
Arm-Mounted Grappling Hook (WIP)

### PR DESCRIPTION
**Pull request by AlchemistExMachina**
Throwing a grappling hook is cool and all, but what if you could fire it to pull down enemies and pull yourself towards walls? The arm-mounted grappler does just that.

### CODE REVIEW

**Comment by kevingranade** [comment]
A grappling hook launcher is one thing, a winch that pulls things is another, which is this?
Also if you're talking about shooting a monster with something, that's a harpoon, not a grappling hook.
If we're talking about pulling the monster or the player around, I don't think it's usually going to do what you want.  If the monster is much smaller/weaker than the player, I could see having a pull attack fling the monster a square or two toward you, and if the monster ends up winning, flinging the player a square or two instead.  Whichever one gets flung would probably take a little damage, and either way the player is spending a lot of moves to do it.
If you're thinking zelda or bionic commando where things are flung large distances, I don't think that's a good fit for the game.

**Comment by AlchemistExMachina** [comment]
I was thinking that it'd be powered by a harpoon attached to your arm, it's not a winch that pulls things long distances. You'd shoot it, give it a tug, and move a monster a few squares towards you and down them, like in Assassin's Creed with the rope darts. Maybe it'd be better to just make rope darts?

**Comment by kevingranade** [comment]
In that case I don't see much reason for it to even be a CBM, why not just a harpoon gun?
What you're describing is a harpoon, a rope dart is something entirely different.

**Comment by AlchemistExMachina** [comment]
Well, we already have harpoon guns that fire underwater spears, so this would be redundant. Also, I never said it would be a CBM, but something you wear.

**Comment by KA101** [comment]
Underwater speargun != harpoon gun.   Speargun just launches a spear, harpoon launches a heavier one that's got a rope attached and can be expected to be useful for hauling the target back in.

**Comment by AlchemistExMachina** [comment]
I'll make a new request for that later then.

**Pull request closed without merging**
