### PR TITLE
[QOL] Add dynamic hint to inventory selector

### PR DESCRIPTION
**Pull request by Maykeye**
Now when you select an item in some menus,
item selector displays helpful info, such as volume,
nutrition and quench values for food,
bash/cut/pierce/range damaged for wielding menu so you don't have to check `I`tem parameter each time to see if picked up weapon will do more damage.

(I couldn't figure out useful info for wearing items, as it's always too specific - you often go for only ONE of warmth/storage/protection and there are too many parameters to display all)

Preview:
screenshot

### CODE REVIEW

**Comment by Vlad-dos** [comment]
Maybe also show how long till spoiling of food.

**Comment by Coolthulhu** [comment]
Won't it conflict with #21508?
The other PR has a priority due to being held up for long, being huge and being a follow up.

**Comment by Vlad-dos** [comment]
@Coolthulhu You linked this PR.

**Comment by Coolthulhu** [comment]
Oops, fixed

**Comment by Maykeye** [comment]
Yea,  they ovelap. Though #20676 addresses only consumption, it doesn't display wielding or other menus. This is more generic.

**Comment by Furbeh** [comment]
Just voicing my opinion, but this PR was reverted due to a crash and I would love it if it was re-implemented, after the crashing issue is fixed.

**Pull request merged**
