### PR TITLE
[CR] Basement laundry and flooded varient

### PR DESCRIPTION
**Pull request by RogueYun**
Before this gets merged, is there some kind of naming system that we need to use? Right now I've been naming my prototype basements as "basement_trait.json" ( ex. basement_laundry.json, basement_shooting_range.json, basement_nerd_dungeon.json, etc.)

I was going to make a few "generic" basements and name them "basement_generic_##.json" where the number would just increment for each one that I made.

The proposed basement addition is a generic basement used to do laundry and a less common flooded version which I believe will help add variety. There is a nice junk room that fills with random closed/open crates and some items will spawn inside them. The junk room will spawn a couple pawn shop items and a lot of average house items, enticing players to pry/smash them open to see what is inside. Some cleaning supplies, house items, and bathroom supplies are found in parts of the basement as well as a lot of clothes. The desk has some school oriented stuff. 

I might have been a little too complex with this design, but to me it feels like an average run of the mill basement. Let me know if I should change anything or could improve on something. Comments are welcome and I'll try to add some more basements in the near future.

### CODE REVIEW

**Comment by keyspace** [comment]
Note that `place_loot` is now mappable: #19793 

If you're not using external software to generate this, the approach above could be easier.

Then again, I've never done a mapgen object, so wouldn't know.

**Comment by Coolthulhu** [comment]
Needs lint

**Comment by keyspace** [comment]
There's now an example for mappable `place_loot` (i.e. `loot`) in a PR, see commit https://github.com/CleverRaven/Cataclysm-DDA/pull/20060/commits/1cbc4a6ee8fcff210ef3e5e034c1a157831d4588.

**Comment by Coolthulhu** [comment]
Closing as inactive.
The non-flooded variant would be pretty safe, the flooded one would be rather jarring since tiles with doors and stairs would still be dry. Just in case someone wants to clean this up and re-PR.

**Pull request closed without merging**
