### PR TITLE
Allow practicing ICs from e-ink tablet

### LINKED ISSUE #53042: 101 Important Integrated Circuits cannot be used as a tool for practicing integrated circuits when stored on e-ink tablet
### Describe the bug

When I store the book on a tablet and get rid of the physical book, I lose access to the tool to practice integrated circuits.

### Steps to reproduce

1. Make a character.
2. Use the debug menu to give them 3 electronics skill, 101 Important Integrated Circuits book, e-ink tablet, and a light battery to power it.
3. Read the book once to get access to the recipe.
4. Check 'Practice' in crafting menu to see that the tool requirement for the book is green.
5. Reload the tablet with the battery and store the book.
6. Drop the book out of crafting range.
7. Check the crafting menu again, the book tool requirement will be red.

### Expected behavior

I would expect to be able to use a digital version of the book in the same way as a physical copy.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 04d1bce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary
Bugfixes "Allow practicing integrated circuits by using a copy of 101 Important Integrated Circuits stored in a e-ink tablet."

#### Purpose of change

Fix #53042 - it was not possible to practice integrated circuits using a copy of 101 Important Integrated Circuits stored in a e-ink tablet because the recipe required the book as a tool in addition to `book_learn`

#### Describe the solution

Remove the tool requirement leaving only `book_learn`

#### Describe alternatives you've considered

1. "Containers: Many Bugs Ahead" - turn the e-ink tablet into a "container" containing a fake version of every book stored in it - a lot of C++ code to fix one recipe. BTW: keep up the good work. Your game as **good**.
2. "Enterprise" - decouple the way the game models knowledge from specific book items. Same as 1 plus turning every book into a container too.
3. "Magic" - write some C++ code to make a recipe with id "prac_elec_integrated_circuits" special.

#### Testing

1. Copy 101 Important Integrated Circuits into an e-ink tablet
2. Throw the book away
3. Practice the recipe

### CODE REVIEW

**Comment by GoLoT** [comment]
Just as a side-note: The e-ink tablet already works as described in your first alternative. Only it stores all books in a custom list that bypasses the container system, which is also the source a similar bugs: Proficiencies aren't mitigated by books stored in an ebook.

I think you chose the right approach though. Hardcoding the book as a required tool doesn't make sense, especially when it can be learned from multiple books and the recipe itself is gated already behind those books.

**Comment by wapcaplet** [comment]
When I created this recipe in #51539, I included the actual book as a component requirement because it is not something memorized or learned like a recipe is, but rather a collection of schematic diagrams and part specifications used for reference while practicing. That specific book (or its e-ink counterpart) should really be a requirement to have on-hand for this practice recipe.

**Comment by GoLoT** [comment]
I don't know if it's possible to block recipes from being learned while still being craftable from books, but it would make sense to make it a book-only recipe in that case. That way you can only craft it if you have a valid book/ebook (one that provides the practice recipe) at hand without having to add it as a requirement.

**Comment by hexagonrecursion** [comment]
> I don't know if it's possible to block recipes from being memorized while still being craftable from books

This should not be difficult to implement in C++. The biggest challenge is that this will be confusing to the player. C:DDA already has way too many hidden, unobvious and confusing mechanics. Must we add one more? If we do this, there **will** be bug reports from confused players that are surprised the recipe did not get memorized unlike any other recipe they ever crafted. Even saying this in the recipe description is not enough because "[users can’t read anything, and if they could, they wouldn’t want to](https://www.joelonsoftware.com/2000/04/26/designing-for-people-who-have-better-things-to-do-with-their-lives)".

**Comment by PatrikLundell** [comment]
The construction recipes used by faction base camps are marked not to be learned, so there is a flag for this, but I don't know if it could be used in this situation.
In fact, I think it would make sense for many practice recipes for skills with a significant theoretical component to require a written source to emphasize that you're using instructions you need to refer back to and progress with (you practice the first IC until you've got the hang of it, then the next one, and so on, while also reading the instructions to actually understand what they do and why they're constructed the way they are, with the later instructions telling you what to achieve, letting you figure out how to do that, implement it, and test it according to the instructions to verify that you've gotten something that works).

**Comment by GoLoT** [comment]
Requiring a book for the recipe is fine but hardcoded and ad-hoc solutions tend to cause issues down the road, which is one of the reasons there are so many PRs aimed at JSONizing stuff, un-hardcoding and refactoring old code. It also clutters the menus when you have a list of 10 specific tools/books/whatever listed as options because each of them had to be added individually to make it work.

If the recipe is somehow flagged as unmemorizable it will always require the book providing it (otherwise the recipe won't show up) without having a hardcoded ID that prevents the recipe from being added to any other sources (be it ebooks, SD cards with the schematics/recipe or any other new content).

**Pull request merged**
