### PR TITLE
Block monster and map extra from being generated repeatedly

### LINKED ISSUE #74697: Map extras spawning on previously visited tiles, and monster spawns higher than usual
### Describe the bug

I'm not sure if it's a bug as much as it is just a new feature, but I was asked to submit a report so I'm doing so. 

I'm getting map extras spawning on tiles that I have had pass through my reality bubble already, which I don't believe has happened before. In the save file I'm submitting, some web spinning spiders have spawned on a swamp tile a few spaces south of the evac shelter spawn at Level 0, -1'61, 1'43. I've also got a couple of ponds spawning in swamp tiles one tile Northwest and another pond spawning a tile north of that pond. -1'53 1'39 also spawned a mass grave in the Isherwood farms, in front of the outbuilding that Luke Isherwood resides in. 

Monster spawning also seems to be occurring more frequently than usual as well-I ran into a thing and a polyp southwest of the evac shelter spawn. 

### Attach save file

[Whately-trimmed.tar.gz](https://github.com/user-attachments/files/15920785/Whately-trimmed.tar.gz)

### Steps to reproduce

The map extra spawning should reproduce if the time ingame advances.

### Expected behavior

I expected for the game world not to spawn any extras after I visited them. 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3737 (22H2)
- Game Version: cdda-experimental-2024-06-19-1857 e4840ea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### LINKED ISSUE #74715: Mines occasionally spawn hordes of miner zs across several map tiles
### Describe the bug

Sometimes, mines will spawn with a very large number of zombie miners stretching across the map away from the mine as many as 15 tiles.

### Attach save file

[Ipava-trimmed.tar.gz](https://github.com/user-attachments/files/15935851/Ipava-trimmed.tar.gz)

### Steps to reproduce

1. Create a default setting world and load a character.
2. Debug reveal map and teleport to mines until you find one surrounded by a horde of zombie miners

### Expected behavior

Surface level mines spawn a reasonable amount of zombie miners within the fenceline.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-06-21-0140 d1fe2af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #74697, i.e. map extras and monsters spawning on already spawned terrain when revisited.
Fix #74715, i.e. monsters in tunnels spawning at the surface.

#### Describe the solution
- Add check to only perform mapgen and monster spawn if the map is actually generated.
- Change the check for spawning monster locations to restrict the valid set to the current Z level. When tinymaps were used this was done implicitly.

#### Describe alternatives you've considered
Introduce a version of the operation that gives you points within a range that only returns the points on a single Z level and use that one rather than generate points on all levels only to reject all hits on other levels. That should probably be done, but this change is faster and less complicated, so I'll leave this for a separate PR.

#### Testing
Loaded the bug report save and traveled around, looking out for new map extras spawning on previously visited terrain, without finding any new anomalies.
Then continued out into the unexplored territory to verify they do still spawn there when the terrain is generated.

Teleport on top of mine tunnels using the bug report save. Before the change miners were spawning in droves on the surface and only a few in the tunnels. Now they stay in the tunnels where they belong.

#### Additional context
I've been highly suspicious of the processing of this code because I did not see anything blocking its execution when terrains wasn't generated in the location where the code was moved from. Thus, the code was moved without introduction of any such guard. Apparently I must have missed something that did provide such protection.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Will this change prevent the EOCs that allow random encounters like the traveling free merchant trader from firing since those events only load on already created maps?

**Comment by PatrikLundell** [comment]
I don't know, but I don't expect that to be the case.

The code not called again is the map extra code and the monster generation code. I would expect the EOC code to not be part of that, but rather being triggered by you actually loading the tile into the reality bubble, whether from memory or file.

A further reason for why this would be the case is that if this code DID generate those then they'd only trigger on tiles you haven't visited within the current game session (because generate shouldn't be called when all Z levels of the tile is generated already while "uniform" tiles are regenerated only if they aren't in memory, and I think this only happens when loading from file, and I don't think there is anywhere the tiles are discarded (apart from not saved on saving, as they're regenerated on load instead).

However, it's something that would be good to test (and I'd need help with that, as I think I've only encountered these things once or twice in total, so the spawn rate would have to be increased massively to see if they do trigger).

**Comment by Maleclypse** [comment]
> I don't know, but I don't expect that to be the case.
> 
> The code not called again is the map extra code and the monster generation code. I would expect the EOC code to not be part of that, but rather being triggered by you actually loading the tile into the reality bubble, whether from memory or file.
> 
> A further reason for why this would be the case is that if this code DID generate those then they'd only trigger on tiles you haven't visited within the current game session (because generate shouldn't be called when all Z levels of the tile is generated already while "uniform" tiles are regenerated only if they aren't in memory, and I think this only happens when loading from file, and I don't think there is anywhere the tiles are discarded (apart from not saved on saving, as they're regenerated on load instead).
> 
> However, it's something that would be good to test (and I'd need help with that, as I think I've only encountered these things once or twice in total, so the spawn rate would have to be increased massively to see if they do trigger).

Ok if I have time tonight I’ll test that and see what happens. Thank you!

**Comment by Maleclypse** [comment]
Ok I don't think that impacted the eoc updates.

**Pull request merged**
