### PR TITLE
Add Default Bipod to RM298 & RM614

### PR DESCRIPTION
**Pull request by Plagueis-The-Wide**
#### Summary
Adds Bipods to Rivtech Machine Guns

#### Purpose of change
Adds Bipods to Rivtech Machine Guns

#### Describe the solution
Add a `"default_mods": [ "bipod" ], ` to the rm614 and rm298 guns. Both guns have also had their mod slots updated to current standards (ie. accessories, muzzles). 

#### Describe alternatives you've considered
Create a new proprietary Rivtech bipod mod made out of Superalloy for greater verisimilitude.

#### Testing
I uh. I did the above and spawned the guns to check they had bipods. It wasn't a very complicated feature.

#### Additional context
Did I do it right this time?

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Not that it really matters, but why are you still working in your 0.E branch? We're now on 0.F and steady moving towards 0.G.

**Comment by Plagueis-The-Wide** [comment]
Because I'm new and have no clue what I'm doing, that's why.

**Comment by Night-Pryanik** [comment]
> Has the 8x40mm gun file changed since 0.F?

No.

> If not can we just call this a 0.F pull? Or should I just reissue this one again.

No need.

**Review by Maleclypse — APPROVED** [review]

**Comment by Plagueis-The-Wide** [comment]
So uh.

What do I do now? Just wait?

**Comment by Night-Pryanik** [comment]
Yep. There are already almost 200 PRs waiting for review.

**Comment by Plagueis-The-Wide** [comment]
Right. That makes sense. 

So....

How's the weather?

**Comment by NetSysFire** [comment]
Portal storms and snow flurries, as usual. If you are eagerly awaiting the merge, maybe playtest other stuff a bit or try to find <s>giant aphids</s>bugs you can report?

**Comment by Plagueis-The-Wide** [comment]
Less eager and more nervous if I'm entirely honest...

**Comment by BrettDong** [comment]
There are merge conflicts in `data/json/items/gun/8x40mm.json`. Please create your pull request targeting `master` branch.

**Comment by ZhilkinSerg** [comment]
Conflicts need to be resolved.

**Pull request closed without merging**
