### PR TITLE
Strapped Plate Armor

### PR DESCRIPTION
**Pull request by mcdonohe**
#### Summary

```SUMMARY: Balance "Adjust layering of historical armor"```

#### Purpose of change

Historical armor (plate/mail/gambeson) is treated unrealistically. Most egregiously, gambeson is skintight! This makes no sense at all; gambesons were thick jackets.

#### Describe the solution

Gambeson is moved to the normal layer, chainmail is moved to the outer layer to make room for it, and plate armor (and all of its components) are moved to the strapped layer to make room for _that_.

#### Describe alternatives you've considered

I considered moving the gambeson itself to the outer layer, since tunics were worn under gambesons, but that would make it share a slot with chainmail, and gambesons were worn under chainmail.

### CODE REVIEW

**Comment by KorGgenT** [comment]
you are missing a summary line

**Comment by Vivit-R** [comment]
> you are missing a summary line

Fixed

**Comment by KorGgenT** [comment]
jenkins rebuild

**Comment by KorGgenT** [comment]
you need to run the file through the [web linting tool](http://dev.narc.ro/cataclysm/format.html)

**Comment by Rivet-the-Zombie** [comment]
Won't this make plate armor layer-clash with scabbards?

**Comment by Photoloss** [comment]
Missing [ornamental plate](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor.json#L567), samurai armor (debatable) and probably a few other pieces I'm forgetting, might cause issues with shoes. Gambeson would be "outer" layer when compared to *modern* garments and the "strapped" layer is somewhat illogical overall as different strapping layouts might not actually overlap (e.g. vambraces, elbow pads, a disability armband and pauldrons all technically "strap" to the arms in different places)

**Comment by Vivit-R** [comment]
> Won't this make plate armor layer-clash with scabbards?

Plate armor layer-clashing with back scabbards isn't that big of a deal given that back scabbards generally weren't used in actual combat -- the were just a way to transport large swords, not a way to _carry_ them for easy access. German Landsknechte didn't even use scabbards at all; they just carried their longswords over their shoulders. [I talk about this in greater detail in the forum thread.](https://discourse.cataclysmdda.org/t/layering-of-historical-armor/19112/7)

**Comment by Vivit-R** [comment]
> Missing [ornamental plate](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor.json#L567), samurai armor (debatable) and probably a few other pieces I'm forgetting

Changed the ones you mentioned. Samurai armor is strapped for the same reason that a Western cuirass is strapped: it hangs from the shoulders by straps (although made of tightly-braided fiber rather than leather).
> might cause issues with shoes.

None of armor covers the feet, so shoes shouldn't be a problem.
>Gambeson would be "outer" layer when compared to _modern_ garments

Yes, but putting it on the outer layer would make it clash with mail, and mail is A) clearly NOT strapped. and B) worn over a gambeson!
>and the "strapped" layer is somewhat illogical overall as different strapping layouts might not actually overlap (e.g. vambraces, elbow pads, a disability armband and pauldrons all technically "strap" to the arms in different places)

This applies to every layer actually: underwear clashes with stockings!

**Comment by Photoloss** [comment]
> it hangs from the shoulders by straps

Actually properly fitted armour rests on multiple points, especially the tailored waist in the case of the cuirass. Mass-produced designs such as [*lorica segmentata*](https://en.wikipedia.org/wiki/Lorica_segmentata) might differ especially since that particular armour had heavily reinforced shoulders.

> Yes, but putting it on the outer layer would make it clash with mail, and mail is A) clearly NOT strapped. and B) worn over a gambeson!

Perhaps it would be better to integrate a thinner gambeson into the mail armour item, or to make two versions representing the standalone fabric armour and the undergarment. Not only is this [historically accurate](https://en.wikipedia.org/wiki/Gambeson) but mail **without** fabric underneath is incredibly uncomfortable to wear due to chafing and pinching, far worse than plate or leather.

> This applies to every layer actually: underwear clashes with stockings!

Yes, but adding more instances doesn't exactly help. Unfortunately I have never seen any tests wearing modern-style belts or backpacks (let alone military bags) over plate so I have no idea how well it would actually work.

**Comment by I-am-Erk** [comment]
I think the best bet might be to make a gambeson part of the crafting recipe for chain armour, and move the gambeson to the outer layer with chain.

**Comment by SirPendrak** [comment]
Making plate strapped layer makes it incompatible with backpacks. We shall consider what adventages this change could give over negatives. Current system might not be perfect, but it allows you to use most armors and equipement without problems.

**Comment by ZhilkinSerg** [comment]
Marking as stalled. Please ping me to reopen when you are ready to pick up where you left.

**Pull request closed without merging**
