### PR TITLE
[WIP] Reduce micromanagement when taking off power armor

### PR DESCRIPTION
**Pull request by codemime**
...via the `'T'ake off` command. So that instead of a boring message in the log:

You would get the query:

Also, added a warning on `'d'rop`:

Uses the new function from #17539.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It doesn't work too well:
* Sometimes you'll be asked up to 3 times to take off power armor + hauling frame
* I managed it to drop a `none` by denying item drop once. Trying to reproduce right now. It didn't erase any items, but did print a debugmsg
* Seems dependent on item order in `worn` vector

**Comment by Coolthulhu** [comment]
The none production bug seems to reproduce reliably:
* Spawn basic power armor and hauling frame
* Wear both
* Make sure the armor is sorted above the hauling frame
* Try to take off the armor
* Answer yes and yes
* The bug happens
* Armor is unequipped, frame isn't

**Comment by codemime** [comment]
Could reproduce. Tackling right now.

**Comment by codemime** [comment]
All set.

**Comment by Coolthulhu** [comment]
* Wear (in this order): armor, frame, helmet
* Remove armor
* Same bug as earlier

**Comment by Mecares** [comment]
Perhaps it would be more elegant to treat Power Armor as one Item and handle the Hauling Rig and the Helmet similar to weapon mods.

**Comment by codemime** [comment]
> Perhaps it would be more elegant to treat Power Armor as one Item and handle the Hauling Rig and the Helmet similar to weapon mods.

I don't think so. The power armor is already a special case, but it shouldn't be. The mechanics should remain general and consisten with other armors / clothes, but with two additions:

1. Some worn items can depend on one another (partly implemented, but still hardcoded)
2. Some worn items can be worn only on bare skin or over those that have `SKINTIGHT` flag (will be implemented soon)

Combination of these conditions gives us a power armor, but they would be useful apart (especially the latter: boots, helmets, e.t.c.).

General solutions are generally better (not mentioning the fact that total reworking of the mechanics would be completely inexpedient).

**Comment by mugling** [comment]
Stalled?

**Comment by codemime** [comment]
No, I'm gonna pursue when I have time for it (in a couple of days).

**Comment by mugling** [comment]
Can this be kept as a local branch and reopened/resubmitted when ready? It is helpful to keep the PR queue as small as possible so we can see what needs active attention. Your decision either way.

**Comment by codemime** [comment]
No problem [closed for a short time].

**Comment by mugling** [comment]
Thanks

**Pull request closed without merging**
