### PR TITLE
Random casings all over the world

### LINKED ISSUE #31671: Random bullet casing drops on roads, maybe randomly in fields, and when you search bushes
**Is your feature request related to a problem? Please describe.**  
Not really, except you gotta ask what happened to all the bullets in New England.

**Describe the solution you'd like**  
We already have random engine drops and stuff on roads and rocks in plains, body bags in bushes, why not add bullet casings (maybe in stacks of like 1 - 5) into the list. I would love to grab some of those over another glass jar or body bag.

**Describe alternatives you've considered**  
I could mod it in myself (if I knew how to mod) but I thought maybe other people would think this should be in the game.

**Additional context**  
Very few bullets and casings in the world, if the military really did try to fight the zombie hoards, there should more than just random "body sites" which don't make a lot of sense in the first place (why did they not rise again?)

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Random casings all over the world."```

#### Purpose of change
Adding more signs of chaos during the Cataclysm and after it.
Closes #31671 - Random bullet casing drops on roads, maybe randomly in fields, and when you search bushes.

#### Describe the solution
- [X] Update `ammo_casings` item group with missing casings;
- [X] Add a high chance of single casing from this item group to spawn on a road;
- [X] Add several variants of shootouts through the map extras and made it spawn on the roads, fields, buildings and forests.
- [X] Make casings spawn in the bushes
- [x] Add more variants for map extra
- [x] Replace test rng with real rng in map extra

#### Additional context
 Pile of random casings in random place
изображение

Entire battlefield filled with casings

Person moved and fired in some direction
изображение

Two persons shot and created two piles of casings
изображение

### CODE REVIEW

**Comment by FulcrumA** [comment]
Would it be possible to decrease number of casings in the 'battlefield' screen or spread it over a bit bigger distance so they won't so clearly dropped in a square-ish area?

Also, likely out of scope of this PR but mixing in occasional filthy bandage, bloodied rag, some trash like cig butts and other such stuff in there, maybe even rare military-grade, spent magazine or severly damaged military helmet would be nice.

**Comment by Night-Pryanik** [comment]
> Would it be possible to decrease number of casings in the 'battlefield' screen

For now it's 10% chance to spawn on every tile of the submap, but yes, I could decrease it even further, I just need some numbers. 5% maybe, like in pic below?
изображение


> spread it over a bit bigger distance

At the moment it isn't possible for map extras to occupy several overmap tiles.

> Also, likely out of scope of this PR but mixing in occasional filthy bandage, bloodied rag, some trash like cig butts and other such stuff

I'll think about it.

**Comment by FulcrumA** [comment]
>5% maybe, like in pic below?

It certainly looks much better

**Comment by AMurkin** [comment]
> 5% maybe, like in pic below?

It could be range of the points in some random radius (points_in_radius) to not look square-ish.

**Comment by Night-Pryanik** [comment]
I've made a bit of improvements, so here's the updated pics:
1) "Simple pile of casings"
изображение

2) "Two-shooters casings"
изображение

3) "Battlefield casings"
изображение

4) "Move-and-fire casings"
изображение

**Comment by nexusmrsep** [comment]
Maybe add a rare chance for an empty magazine left behind in a hurry? I'm trying to think of what else might a wounded person drop and leave behind in such situation.

**Comment by Night-Pryanik** [comment]
> Maybe add a rare chance for an empty magazine left behind in a hurry?

I thought about that too, but because casings are taken randomly from the `ammo_casings` item group, that would require a lot of checks like "if casing is .223, then drop stanag magazine; else if casing is 9x19mm then drop _something else (what exactly? There is a lot of guns using 9mm caliber)_" etc.

>I'm trying to think of what else might a wounded person drop and leave behind in such situation.

Yeah, I'm still thinking on that too and can't think of something reasonable.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by FulcrumA** [comment]
>Yeah, I'm still thinking on that too and can't think of something reasonable.

Well, if you don't mind further ideas, aside from things already mentioned like mags, military helmets and barricades, filthy bandages, rags and cig butts, I can think of stuff like broken glass pieces and metal scrap and pools of gasoline/diesel on the ground suggesting that previously there was a vehicle in the area. Of course, it wouldn't fit every of those scenarios.

Also, I should point out that you may want to decrease somewhat changed of those bloodies rags. They seem to spawn a bit often. One in several such extras would probably do (and I also think that such events in general should be rather rare tp avoid whole swathes of land covered in casings).

**Comment by logros13** [comment]
Some bodies perhaps? if there are bunch bullets casings there you would expect corpses, either zombie human or both.

**Comment by Night-Pryanik** [comment]
> Also, I should point out that you may want to decrease somewhat chances of those bloodies rags. They seem to spawn a bit often.

If you're judging from the pics, it's just because I selected the ones with bloody rags on them, for representation. But I can decrease their chance to spawn, all right.

> I also think that such events in general should be rather rare to avoid whole swathes of land covered in piles of casings

Well, I tried my best to balance their chance of spawn, so it should be not too frequent and not too rare. For example, I set the chance to spawn to be slightly lower than that of a crashed helicopter. 
I think only real game experience could show if my predictions were right, and if they don't, balance could be adjusted in subsequent PRs.

**Comment by Night-Pryanik** [comment]
> Also, possibly some road obstacles, remnants of barricades?

These map extras will spawn everywhere, not only on the roads: in forests, in fields, even in the buildings.

**Comment by Amoebka** [comment]
Out of sheer curiosity, how do tens of casings spread over tens of tiles affect performance during 5min / 30min activities?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Out of sheer curiosity, how do tens of casings spread over tens of tiles affect performance during 5min / 30min activities?

Ammo casings are not active items. Nothing happens with them.

**Comment by FulcrumA** [comment]
@Night-Pryanik 
I was playing and trying it out over past few days and wanted to ask whether you're sure regarding spawn chances - something's off because places with random casings are not that rare, however almost all of them look like if they'd roll for a chance to appear _each_, often leading to locations with just one or two casings which I assume is not intentional.

**Comment by Night-Pryanik** [comment]
Could you please provide a screenshot of such locations?

> something's off because places with random casings are not that rare

Chance to spawn could be lowered, of course.

**Comment by FulcrumA** [comment]
So far it was random places in the world with just two, three casings lying around. Barely noticed most of the time, but if I will again and not forget, sure.

**Comment by Night-Pryanik** [comment]
Well, two or three casings lying in random places is absolutely normal and intended - imagine someone fired two or three times at someone else.

**Comment by FulcrumA** [comment]
sure, it's fine but when it's just this much casings every time at most, the 'scenarios' you've made will never really be shown.

**Comment by Night-Pryanik** [comment]
Well, all four scenarios have the same chance to spawn. Don't know why is there is some preference on one type of spawn.

Will make a test tomorrow if this is really happening.

**Pull request merged**
