### PR TITLE
Mark non-installed CBM with red color

### LINKED ISSUE #11432: CBM indicator (have it?)
A simple idea to help the player to know what CMB he already installed. Since most of the CBMs only can be installed once it would be quite helpful when the player looking for the new ones with a bunch of CMBs installed. And the solution is as simple as the idea, basically it's just a color change, like books have.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9078962-cbm-indicator-have-it?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Gabriel-SE**
Resolve #11432

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Will it work with power storage ones?

**Comment by Zireael07** [comment]
Great!

**Comment by Gabriel-SE** [comment]
>Will it work with power storage ones?

Power Storage CBM and Power Storage CBM Mk. II are still marked in red, even if player have installed them, because there's no limit on how much power player can have.

**Comment by KA101** [comment]
Hey, color-blindness is a thing.  At some point we need these color settings to be user-configurable.

**Comment by DavidKeaton** [comment]
color blind broski here, can attest to CB mode being rad.

**Comment by Gabriel-SE** [comment]
>Hey, color-blindness is a thing. At some point we need these color settings to be user-configurable.

I think we should put them in Options > Colors.

**Comment by KA101** [comment]
I'm not sold on this enough to merge w/o a color-picker and that's way beyond the scope.  If folks think it'll work, make that known; otherwise, I'll close with encouragement to reopen once we get a way to not interface-screw colorblind folks.

24 hours on the clock.

**Comment by Rivet-the-Zombie** [comment]
Couldn't we just mark ones that you've already got installed with a ````X```` next to the item name or something?

**Comment by DavidKeaton** [comment]
as long as the colors aren't mixed, and are primary or secondary colors, should be okay? (need fellow CB peeps to confirm).

**Comment by Rivet-the-Zombie** [comment]
I'm B/Y colorblind. If we're using color, I'm fine with anything with a good contrast. Nothing's worse than blue text on a black background, or yellow against white.

As it stands, we're pretty much in agreement that the normal text color is easy to read, so just adding a glyph to the name avoids the issue entirely.

**Comment by DavidKeaton** [comment]
Yeah blue next to red on black makes my eyes go crossed. A glyph would work, albeit I don't have any probs with all the colors the items get coloured in.

**Comment by KA101** [comment]
>blue next to red on black

Yikes. Zed bio-operators shouldn't be a player-side interface screw, my apologies.  Dunno if the green was any better though.  :-/

**Comment by sparr** [comment]
putting the name in parentheses could also convey the desired information?

**Comment by Rivet-the-Zombie** [comment]
>putting the name in parentheses could also convey the desired information?

I like this idea.

**Comment by KA101** [comment]
>putting the name in parentheses could also convey the desired information?

I'm thinking parens == installed?  if so, sure.

**Comment by Zireael07** [comment]
Nice idea with parentheses.

**Pull request closed without merging**
