### PR TITLE
Inhaler fix

### LINKED ISSUE #40781: Inhaler has unlimited charges.
Inhaler has unlimited charges and charges are not displayed. When asthma attack happens it says that inhaler still has 100 charges left, despite being manually activated 200+ times in a row.

image

I am using latest git pull on master branch at the time of writing this.

### PR DESCRIPTION
**Pull request by DillonSimeone**
#### Summary

SUMMARY: Bugfixes "Added pocket to the inhaler, and albuterol ammo+ammo_type"

Fixes #40781

#### Purpose of change

The inhaler was not using up its charge before this fix.

#### Describe the solution

Copied the style of oxygen_tank in json/items/tool/med.json for the inhaler, and the style of oxygen in json/item/ammo for the albuterol.

#### Describe alternatives you've considered

Letting someone else to do it instead.

#### Testing

Load up game, wish in an inhaler and take a few puffs then check if the charges on the inhaler is going down.

#### Additional context

My dude trying to get high off an inhaler.
image

### CODE REVIEW

**Comment by KorGgenT** [comment]
oh drat the iuse test for the inhaler needs an update for this

**Comment by waveyl** [comment]
fire drill also not display its charge, but i'm not sure whether it's unlimited.

**Comment by woutershep** [comment]
'Maximum <num> charges' in the left pane doesn't look right, and neither does the material 'plastic' for the ammo.

**Comment by wapcaplet** [comment]
> oh drat the iuse test for the inhaler needs an update for this

You should be able to fix the failing "inhaler" test case in `tests/iuse_test.cpp` by using `ammo_set` in the same way as the "oxygen tank" test does - since the new inhaler is loaded with albuterol ammo:

```cpp
TEST_CASE( "inhaler", "[iuse][inhaler]" )
{
    avatar dummy;
    item inhaler( "inhaler", 0, item::default_charges_tag{} );
    // Add these lines:
    itype_id albuterol( "albuterol" );
    inhaler.ammo_set( albuterol );
```

**Comment by kwl01skz** [comment]
We must add initial ammunition to it, otherwise the initial character will get an empty inhaler and die in despair.

**Comment by DillonSimeone** [comment]
There is already initial ammunition.

image

I'd guess that you just need to update to current unstable.

**Pull request merged**
