### PR TITLE
Audit: Farming Vehicles + Forklift

### PR DESCRIPTION
**Pull request by ShnitzelX2**
#### Purpose of change

While making some new tiles for vehicle parts, I noticed a couple things about some of the vehicles:
1) The **Plow Tractor** and **Reaper Tractor** had their plow and reaper parts mounted to the sides of a frame -- real-life tractors nearly always have them in front or in back of something.
2) All three of the farming vehicle parts (plow, reaper, seed drill) use frames differently: the plow has one frame required for mount and another for crafting, the reaper only requires a frame for crafting, and the seed drill requires neither. 
3) The **seed drill** and **plow** crafting recipes require electric components despite these machines having nonelectric real-life analogs. Further, none of them required electronics skill to craft and have advanced variants that could utilize electricity if needed.
4) The power usage of the farming vehicle parts should match horsepower needed to operate these vehicles in real life.
5) The **Forklift** was obviously intended to have two arms on separate tiles, but this conflicted with the forklift vehicle part's description as a "pair of arms". Additionally, two tiles wide seems like too much for a bog-standard forklift.

#### Describe the solution

Point by point:
1) CDDA doesn't really have a better way to make rows of crops aside from attaching three plows to a tractor, so I figured the plow/reaper could at least attach from the front/back of a frame like they would on a real-life tractor -- now they do. I left the seed drill alone since they could plausibly be placed side-by-side.
2) Every farming vehicle part -- plow, reaper, seed drill, and their advanced variants -- now uses location: "structure". It's simpler and less arbitrary.
3) All electronic components were removed from the farming vehicle parts. The plow is a [moldboard plow](https://bloximages.newyork1.vip.townnews.com/lancasterfarming.com/content/tncms/assets/v3/editorial/6/0d/60dada74-f316-11ec-9dcc-ffd2030d16e2/62b49cd6231f2.image.jpg?crop=800%2C420%2C0%2C56&resize=800%2C420&order=crop%2Cresize), the reaper is something approximating an [Adriance reaper](https://en.wikipedia.org/wiki/Reaper#/media/File:Adriance_reaper,_19th_century_illustration.jpg), and the seed drill is a box of sheet metal with some pipes and wheels attached.
4) The plow takes much more vehicle power to operate. It's digging 8" into the ground, after all, and farming shouldn't be free. The other parts' power costs are slightly increased. 
5) The newly-designed "Electric Forklift" is one tile wide with one forklift vehicle part (one pair of arms) and lacks heavy frames. The newly-named "Heavy-Duty Forklift" retains the original design.

Additionally, the Plow Tractor, Reaper Tractor, and Planter Tractor now spawn with items -- usually a basic tool and/or bottled beverage.

#### Describe alternatives you've considered

-I thought about making the reaper an electronic reaper, but in retrospect it would be too confusing to have only the reaper be electronic and then have an advanced variant on top of that.
-I thought about including a frame for the seed drill's crafting recipe, but it would be overkill. 
-I'm still unsure about the advanced seed drill consuming electric power. 

#### Testing

Spawned vehicles, checked power consumption, made sure game loaded, etc.

#### Additional context

First PR! Feel like this might be overdoing it for JSON edits, so feedback is appreciated.

Also, I need to redo the reaper sprite in my tileset PR. It's still an electric reaper.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I think you may have a compatibility problem, i.e. the issue that you change the mounting requirements for parts that may be in use in saves from before this change.
Old saves need to still work. That may be done by retaining old parts with their old specifications, obsoleting those, and then define new ones. It might be possible to add code to transform old designs to new ones, although that could be a bit tricky.

You have to follow the format for a PR (which is what the PR Validator test is complaining about). The PR summary section has to be present and follow the format the comment describes exactly since it's parsed by a script. The format is one of the listed code words followed by a descriptive comment, or the "None" code word without a comment.

**Comment by ShnitzelX2** [comment]
Sorry for the delay,

> I think you may have a compatibility problem, i.e. the issue that you change the mounting requirements for parts that may be in use in saves from before this change. Old saves need to still work. That may be done by retaining old parts with their old specifications, obsoleting those, and then define new ones. It might be possible to add code to transform old designs to new ones, although that could be a bit tricky.

I tested the vehicle changes in a new build with an old save file, and there didn't appear to be any related errors. For the Plow Tractor, the plow vp is mounted to the frame when it shouldn't be, but the old save still works fine; you can drive the tractor, plow terrain, and even remove the plow vp if needed. Is this acceptable or should I obsolete the plow and advanced reaper?

> You have to follow the format for a PR (which is what the PR Validator test is complaining about). The PR summary section has to be present and follow the format the comment describes exactly since it's parsed by a script. The format is one of the listed code words followed by a descriptive comment, or the "None" code word without a comment.

I fixed this (a silly error), and it also turned out that I forgot to run unit tests, so I updated the test data. Thanks!

**Comment by PatrikLundell** [comment]
If old save vehicles work as intended you probably don't have a problem.

**Review by ShnitzelX2 — COMMENTED** [review]
Author review

**Pull request merged**
