### PR TITLE
reimplement stairs placement logic

### LINKED ISSUE #24562: Shady Basement house lacks downstair
Game version: 0.C-29759

Operating system: Windows 10

Tiles or curses:Tiles

### Expected behavior
Upon exiting the shady basement starting location from the High Tech Low Life scenario, you appear at a set of down stairs inside the house.

### Actual behavior
Refer to screenshot: https://i.imgur.com/DoyOmXN.png

Leaving the basement puts you outside the house, on the pavement east of the front door. There is no downstair anywhere in the house, including under furniture. Adding a stair to the house with the debug menu connects to the basement as expected.

### Steps to reproduce the behavior
I've restarted several times with the same setup and have been unable to reproduce it, though at least one other person on discord has reported having the same issue. It might require a specific house and basement combination that is quite uncommon? I'm posting the issue regardless in the hopes that someone recognizes the house in question from the screenshot.

### PR DESCRIPTION
**Pull request by kkujala**
### How to use
Create a world with Align up and down stairs either false or true. Select scenario where the character starts underground such as High Tech & Low Life. Observe how the the stairs now align with the upstairs terrain in comparison to the existing logic. With the existing logic the stairs might not be there at all and the character would not be able to get back down again.

#### Summary
SUMMARY: Bugfixes "Reimplement stairs placement logic"

#### Purpose of change
Place stairs if at all possible to suitable places and honor the stairs location in comparison to each other.
This will partially fix #24562. When the Align stairs option is true then the stairs are always placed regardless what is on top.

When the option is false the stairs are not placed if no suitable places are found. Some houses are construction yards and for those there might not be any indoors tiles, and that prevents placing stairs normally.

#### Describe the solution
Find where the underground stairs up tiles match to suitable tiles aboveground with random fashion. Only use tiles which are indoors, flat and have not furniture. With the force stairs alignment option true, allow placing stairs to unsuitable locations if suitable location were not found.

#### Describe alternatives you've considered
The other option is to try to find suitable places around the underground stairs.

### CODE REVIEW

**Comment by AMurkin** [comment]
Valid summary would be ```SUMMARY: Balance "Try to place stairs to nearby tiles upstairs"```

**Comment by kkujala** [comment]
> Valid summary would be `SUMMARY: Balance "Try to place stairs to nearby tiles upstairs"`

Fixed.

**Comment by AMurkin** [comment]
Jenkins rebuild

**Comment by ZhilkinSerg** [comment]
image

image

**Comment by kkujala** [comment]
@ZhilkinSerg I reimplemented the placement logic that appears to lead more consistent stairs placement than what happened in your example.

**Pull request merged**
