### PR TITLE
Concrete Mixer audit

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Our tiny tabletop concrete mixer didn't really fit with realism that well

#### Describe the solution

<details>
<summary>CONCRETE MIXER ITEM CHANGES</summary>

- Weight increased from ~9kg to ~41kg
- Volume increased from 5l to 250l
- Added a manually defined longest side of 118cm
- Decreased pre-apo price from 500$ to 400$
- ``to-hit`` values now use modifiers
- Material now has 50% plastic (based on a concrete mixer with a plastic drum)
- Added an open pocket that can be used to store things
- Removed the ``HOTPLATE`` use action because why the fuck can we heat up lunch in a concrete mixer
- Made it an unfoldable vehicle and added a pseudotool - it now can only be used when unfolded into vehicle form

</details>

<details>
<summary>CONCRETE MIXER RECIPE CHANGES</summary>

- No longer takes raw steel, 2l metal tank, or heating elements
- Will now take 2 small wheels and a 30 gallon plastic barrel
- Tripled the number of pipes needed
- No longer has metalworking proficiency
- Will now take an extension cord instead of a bunch of loose cables
- Will take a small motor instead of a tiny motor
- Added some nuts and bolts as per the user manual of the one I'm basing this off
- Added some small metal sheets (for the blades to mix the concrete as well as to cover the motor)
- The weld length has been recalculated and increased over four times
- Now needs a metal sawing quality of 2 instead of 1, multitool won't cut it

</details>

<details>
<summary>30 GALLON PLASTIC BARREL CHANGES</summary>

- Volume increased from ~118l to ~165l
- Pocket volume increased slightly (by ~1l)
- Added a manually defined longest side of 72cm
- Increased pre-apo price from 50$ to 71$
- Renamed to clearly show it's made of plastic
- ``to-hit`` values now use modifiers
- Recipe fundamentally changed to be melding the plastic barrel instead of duct-taping plastic jerrycans together (?)
</details>

<details>
<summary>MISC CHANGES</summary>

- Concrete mixer can no longer be attached to the modular rigs (vehicle & appliance)

</details>

#### Testing
~~Although most of the things work as expected, the PR is blocked by #71108~~
No longer blocked

#### Additional context
The recipe isn't perfect and generates roughly 7kg of mass, but I cannot make it better without adding bullshit requirements.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
I wouldn't get rid of the battery or modular rig compatibility. It's good to keep options for usage open, that's why microwaves, hotplates, welders etc can run on battery backup.
Have you made sure it doesn't cause overflow iin the world due to 1000L space limits?

**Comment by Karol1223** [comment]
> I wouldn't get rid of the battery or modular rig compatibility. It's good to keep options for usage open, that's why microwaves, hotplates, welders etc can run on battery backup. Have you made sure it doesn't cause overflow iin the world due to 1000L space limits?

I've not made sure of anything yet, really. Hence the testing disclaimer. I'm not sure how to test it either but we'll burn that bridge when we get there.

As for the first part - I disagree. I am a firm believer in realism. And, frankly, if you're using a concrete mixer for anything the least you can do is have a power grid set up. Again, this warrants further testing and if it doesn't work as intended I'll give it the battery magazine back BUT if it does work as intended I do want to have it function only plugged in. It makes NO sense for a concrete mixer to take batteries.

**Comment by Karol1223** [comment]
Alright so to highlight what's actually going on with this one - I am stumped at how to handle the crafting recipe so that it doesn't generate mass. That's what's been blocking me from finishing this. As it stands, the crafting recipe generates roughly 30kg of mass if memory serves me right. But it uses accurate ingredients. So where's the issue? Good question! I'd like to know too...

**Comment by Kanexan** [comment]
There _are_ some cordless battery-powered concrete mixers, but they're going to be the kind that is an agitating rod on a handle [citation here](https://www.grainger.com/category/tools/power-tools/mud-mixers-concrete-vibrators/mud-mixers-paddles/cordless-mud-mixers?gucid=N:N:PS:Paid:MS:CSM-2296:LC5DTN:20500731&gclid=9c6d3b8b14dd10ce2bd95e8770c163a3&gclsrc=3p.ds&msclkid=9c6d3b8b14dd10ce2bd95e8770c163a3). These would work by putting your concrete components in a container such as a drum or bucket, and then mixing it within there; all of the stereotypical rotating-drum concrete mixers are going to be either powered by electric cord or by gasoline. We probably should also have gasoline-powered concrete mixers, but battery powered mixers of the type we have in game simply do not exist in any meaningful quantity.

**Comment by Karol1223** [comment]
> There _are_ some cordless battery-powered concrete mixers, but they're going to be the kind that is an agitating rod on a handle [citation here](https://www.grainger.com/category/tools/power-tools/mud-mixers-concrete-vibrators/mud-mixers-paddles/cordless-mud-mixers?gucid=N:N:PS:Paid:MS:CSM-2296:LC5DTN:20500731&gclid=9c6d3b8b14dd10ce2bd95e8770c163a3&gclsrc=3p.ds&msclkid=9c6d3b8b14dd10ce2bd95e8770c163a3). These would work by putting your concrete components in a container such as a drum or bucket, and then mixing it within there; all of the stereotypical rotating-drum concrete mixers are going to be either powered by electric cord or by gasoline. We probably should also have gasoline-powered concrete mixers, but battery powered mixers of the type we have in game simply do not exist in any meaningful quantity.

I'm gonna be making that an appliance so no gasoline powering for that.

**Comment by Karol1223** [comment]
Ah it's one of those happy little accidents I see

**Review by GuardianDll — APPROVED** [review]
tested it myself, works fine

**Pull request merged**
