### PR TITLE
Resume butchering

### LINKED ISSUE #42586: Suggestion: Be possible to continue butchering instead of starting over from the beginning
# Describe the bug

Sometimes when you are butchering or dissecting you need to stop midway to eat or deal with a random zed but when you do so it seems that you need to start over from the beginning.

It would be really nice if you could star from where you left just like with the recipes.

# Steps To Reproduce

1 - Start butchering or dissecting something
2 - Stop in the middle of the task
3 - Stark again and take note that you will need full time to finish the task at hand

# Expected behavior

When you are skinning, dissecting or butchering a corpse but you take a break in the middle, if you want to continue you usually will not need the same amount of time as if you were doing it from the start.

# Screenshots

Not needed.

# Versions and configuration

I am using using the CDDA 0.E-b10865 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

I think it would be nice if it was the same for most tasks that allow you to stop in the middle.

### PR DESCRIPTION
**Pull request by inogenous**
#### Summary
Features "Resume butchering"

#### Purpose of change

Allows resuming previously started butchering activities. Fixes #42586 .

#### Describe the solution

This is done by storing a var on the corpse item with the progress. For example, aborting a dissection after 90% has been completed will store var `DISSECT_progress`=`0.9` on the corpse.

Displays percent of previous progress in the butchery ui, if it has already started earlier.

resume-butcher

#### Describe alternatives you've considered

We should migrate the butcher activity from the old activity classes into "new" `activity_actor` classes - but that's for another PR.

#### Testing

* Dissected lots of zombies by selecting them individually. ✓
* Placed several zombies on the same tile and selected "Butcher everything". All zombies are correctly butchered. ✓

#### Additional context

The idea of storing a var on the corpse was already suggested before: https://github.com/CleverRaven/Cataclysm-DDA/issues/26113#issuecomment-442128477

### CODE REVIEW

**Comment by Nebnis** [comment]
Huge gamechanger, blob bless u

**Comment by Procyonae** [comment]
You probably shouldn't be able to 99% dismember a corpse and then start doing a full butchery on it etc but idk how to suggest changing it to accommodate for that

**Comment by Qrox** [comment]
> You probably shouldn't be able to 99% dismember a corpse and then start doing a full butchery on it etc but idk how to suggest changing it to accommodate for that

I think we can disallow finer butchering methods when a cruder method is already in progress. Alternatively, we can allow resuming butchering with a different method, and return butchering results based on the percentage of each method chosen once the methods' total progress reaches 100% or as soon as you pause butchering.

**Comment by inogenous** [comment]
Thank you all for good ideas.

> I think we can disallow finer butchering methods when a cruder method is already in progress.

Have added another commit here now that implements this. For example, starting "quick butchery" will make "dissect" unavailable. A butcher type is considered more crude than another type if it takes less time to complete.

Example when having started "quick butchery" :
resume-butcher-2

**Comment by I-am-Erk** [comment]
cool one

**Pull request merged**
