### PR TITLE
Add Arrested Scenario

### PR DESCRIPTION
**Pull request by Dozed12**
This is my first pull request so it will likely be wrong.

Adds a scenario where you can play as gangster or scoundrel and you begin in a police station.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Ehh seems odd that your character can spawn with their firearms/knives still in inventory, if they actually got arrested police should have confiscated those items.

**Comment by Dozed12** [comment]
Otherwise it would be like a normal survivor.

**Comment by KA101** [comment]
Yeah, this'll need some C++ support.  Your inventory should be in the evidence locker (the locked room down the hall from the front door, NOT the armory with the unlock-computer adjacent) if you've been arrested.

That and you'd need either an (improvised) lockpick or to start with the cell door somehow open for you.

Good ideas, Dozed12.  Just not quite ready for prime time.  :-/

**Comment by Dozed12** [comment]
Probably didn't thought about the whole thing enough, I will see what I can do.

**Comment by Dozed12** [comment]
I can't seem to find where I should add that scenario specific circumstances, is there an other scenario that needs to change player inventory and specific location that I can use as an example?

**Comment by kevingranade** [comment]
Afraid not, you're breaking new ground here.

**Comment by Lap** [comment]
Based on scenario.cpp 62 it looks like the ability to change starting items from a json is there, but I can't get it to work.

```C++
    JsonObject items_obj=jsobj.get_object("items");
    scen.add_items_from_jsonarray(items_obj.get_array("both"), "both");
    scen.add_items_from_jsonarray(items_obj.get_array("male"), "male");
    scen.add_items_from_jsonarray(items_obj.get_array("female"), "female");
```

**Comment by KA101** [comment]
Yeah, that'd need the handler to remove/reroute the stuff from inventory and place it on the map.  As is it gets the stuff specified in the JSON and adds 'em to the PC's inventory.

**Comment by chaosvolt** [comment]
Better idea: why not put the convict profession on this instead? Or add new professions with the "electronic cuffs" item?

Would be the simplest option.

**Comment by OzoneH3** [comment]
No progress for a long time, closing.

**Pull request closed without merging**
