### PR TITLE
Update, improve, and polish free merchant quest lines and dialogue

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Update, improve, and polish free merchant quest lines and dialogue"```

#### Purpose of change
The free merchant quest line is one of the first completed quest lines in the game, and will be most players' first contact with a quest/story thread.

It's kind of terrible. The dialogue is sparse, and several quests don't make sense. Also, many new features require that the code be updated.

Additionally, the shopkeeper's dialogue is very out of date; they basically describe a different sort of apocalypse and rely on a very short timeframe.

#### Describe the solution
- Change all shopkeeper missions to pay you in merch, update dialogue to explain this. As the quests progress they become more casual and less apologetic about merch, under the assumption that the currency is becoming more recognized.
- Change the ridiculous and now obsolete plutonium cell mission to be solar panels. As this is more achievable, move it back to its original place in the quest order.
- Change the now totally silly canned goods questline to be a quest for glass jars instead. This also activates the broker to have them start buying glass jars from you.
- Make the Tacoma Ranch mission dialogue less abrupt, have the merchant introduce the ranch. Add a starting and ending variable so that once you know about the ranch you'll be able to talk to other NPCs about it.
- Rewrite a lot of the shopkeeper's dialogue to better fit current cataclysm lore and to not sound ridiculous if you come back to the location a year later.
- Add a bunch more dialogue to match new additions to the center and to make NPCs less static - they respond a *little* to what's going on now.

In the process I have also massively expanded the merchant's inventory with things he has presumably obtained from scavengers: I just added a wide variety of item groups to his spawn list. It does work, but I am pretty sure not even close to his entire inventory is appearing in his trade list for some reason.  Still, it has gone a long way to making him into a potential trade partner.

As the shopkeeper will just drop everything on the floor, I've given them DEBUG_STORAGE as a mutation, until such time as either we have a better shopkeeper inventory system, or someone codes a SHOP_STORAGE mutation at least so that the NPC isn't flagged as a cheater.

#### Describe alternatives you've considered
- I am considering adding more quests.  Not sure what at the moment.
- I should probably further conditionalize the dialogue to update over time_since_cataclysm. Might do that this PR, might not.

#### Additional context
This old issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/22937 is going to cause a lot of problems with the ability to use currency like Merch.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> Change the totally silly canned goods questline to be a quest for glass jars instead.

That was rather rude to call @DavisBroda's hard work (three attempts) "silly".

**Comment by I-am-Erk** [comment]
Outdated and out of scale then? I'm being a little tongue in cheek here

**Comment by DavisBroda** [comment]
Canned food quest was never intended to last them through the winter. It was intended to provide a bit of a buffer if something were to keep them locked in for a few days. Something like a zombie horde passing by, where no one wants to step outside to hunt for fear of attracting attention.

Plus there was some attention to gameplay there. While a higher number would make more sense, it seemed like putting the number at a couple hundred would make it a really tedious fetch quest if the player wasn't already in endgame loot-collecting mode where they have hundreds of everything lying around.

**Comment by I-am-Erk** [comment]
It's all good, the quest I was really aiming at killing, and for which the PR is named, was the plutonium cells one. I've kept the spirit of the canned goods quest but made it somethng with more sustainable use to the center since jars are reusable.

**Comment by DavisBroda** [comment]
Bit disappointment you took out the item placement on quest completion. Always felt the refugee centre storage room was too empty, and made that quest partially as a plausible excuse to put some stuff in it.

**Comment by I-am-Erk** [comment]
Presently the storage room is actually much too overcrowded, I changed the spawns a few PRs ago. I did really like that feature, I'll probably put it back in once there are underground stores.

**Comment by DavisBroda** [comment]
Ah, if the spawns were changed that makes more sense. Will have to go check out how the new stuff looks at some point.

**Pull request merged**
