### PR TITLE
add semi-automatic mode to M2

### PR DESCRIPTION
**Pull request by ymber**
Replaces the M2 with an M2HB. Main difference is semi-automatic fire to prevent wasting .50 BMG rounds.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Does the SEMI mode work when fired against zombies?

**Comment by kevingranade** [comment]
Please revert the name change, this makes it less clear what it is instead of more clear.

**Comment by ymber** [comment]
Reverted name change.
@BorkBorkGoesTheCode I've been playing with this in my game for a few weeks and it's worked as expected in all cases except for the bug with vehicle turrets keeping their old fire mode for one shot after you switch mode.

**Comment by BorkBorkGoesTheCode** [comment]
This causes merge conflicts with #22756

**Pull request merged**
