### PR TITLE
DeadPeople Tileset update

### PR DESCRIPTION
**Pull request by SomeDeadGuy**
`SUMMARY: Content "Update to DeadPeople tileset and for mods for said tileset"`

### CODE REVIEW

**Comment by ifreund** [comment]
You'll need to add a valid SUMMARY line and lint your json to pass travis/gorgon

**Comment by SomeDeadGuy** [comment]
Like this?

**Comment by AMurkin** [comment]
`SUMMARY: Content "Update to DeadPeople tileset and for mods for said tileset"`

**Comment by ifreund** [comment]
Still need to run your json through the [web linter](http://dev.narc.ro/cataclysm/format.html)

**Comment by SomeDeadGuy** [comment]
Each json i need to run throught the linter, right?

**Comment by ifreund** [comment]
Looks good 👍

**Pull request merged**
