### PR TITLE
tools: improve dialogue validator

### LINKED ISSUE #31359: Sanity checking for dialogue
**Is your feature request related to a problem? Please describe.**  
Bugs have been observed due to inconsistencies in dialogue (#31075, #31107).

**Describe the solution you'd like**  
As discussed in the comments of #31077, we could have sanity checking to verify:
* All topics referred to exist.
* All topics can be reached.
* All topics can lead to an exit from the conversation.

@I-am-Erk FYI.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY Build "tools: improve dialogue validator"```

#### Purpose of change
Fixes #31359 
There was already a sanity checker for dialogue, but it didn't confirm that all chat paths reached all topics and eventually led to a TALK_DONE. Add that functionality and fix an exposed bug.

#### Describe the solution
Improve dialogue_validator.py by adding a dictionary of all topics and their responses, and then walking the dictionary repeatedly to determine that all topics have a response that leads to TALK_DONE.  Repeatedly walk the dictionary again to make sure that all topics are reachable from a start topic.

Fix a bug in the Free Merchant broker's dialogue.  Obvious typo.

#### Describe alternatives you've considered
I could probably write a better breadth first traversal than an O(n2) naive loop, but it takes less than 1/10th of a second to run even when it encounters errors, so I don't care.  Simplicity is easier to maintain.

### CODE REVIEW

**Comment by jbytheway** [comment]
Can we have this be run in Travis, please?  It can go in the `TEST_STAGE` part of `build-scripts/build.sh`, along with the json linting etc.

**Comment by jbytheway** [comment]
Also, based on your description, you're checking that topics are referenced in some response, but not that they are reachable at all.  There could be an isolated collection of topics which reference each other but cannot be reached.  Is that something that could be checked also?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Can we have this be run in Travis, please? It can go in the `TEST_STAGE` part of `build-scripts/build.sh`, along with the json linting etc.

I second that

**Comment by mlangsdorf** [comment]
I'll look into the Travis thing tomorrow

**Pull request merged**
