### PR TITLE
Minor Weapon Tweaks

### PR DESCRIPTION
**Pull request by chaosvolt**
These are a few ideas I'd pondered adding in a PR, for a few disparate
weapons.
1. Gave the briefcase armor data so it can be worn in the same way a
   briefcase can be worn. No storage though, so it's mostly a flavor
   detail.
2. Gave the blade bionic to knife use action. It already counts as
   having cut and butcher quality. I considered giving this to bionic claws
   as well, but decided against that for now.

I was also going to add a minimum of mod slots to the Sten because I
could've sworn I gave it no mod options when I first added it, but it
seems someone already did so. Derp. o3o

### CODE REVIEW

**Comment by chaosvolt** [comment]
Aw crap.

**Comment by kevingranade** [comment]
"No pickup" is there for a reason.  The assumption is natural-ish claws are a balance between combat and other purposes, whereas the bionic claws are totally focused on combat when on.

**Comment by chaosvolt** [comment]
Ack. Will remove it then. Any advice concerning the addition of the knife use_action?

**Comment by chaosvolt** [comment]
Also, I could've sworn there were a few other minor weapon-related tweaks I thought up, but I'm having trouble recalling them. I blame it being late here. @_@

**Comment by chaosvolt** [comment]
Well whatever it was, I can't find it on any of my recent posts in the "simple ideas" thread back on the forum, so oh well. o3o

**Comment by chaosvolt** [comment]
Ah, there is one thing I will possibly wish to tweak, as someone noted here: http://smf.cataclysmdda.com/index.php?topic=10624.0

**Comment by kevingranade** [comment]
Please get more than, "some guy says the recoil is too high" before adjusting the value.  There is a ton of values that are definitely off, but I'm not convinced this is one of them.

**Comment by chaosvolt** [comment]
Blargh. Alright, I'd only lowered the values by 10, but... >.>

**Comment by chaosvolt** [comment]
And now back to trying to recall if there was anything else I was going to tweak. :V

**Comment by chaosvolt** [comment]
Meh, can't think of anything else. Any stuff I need to re-tweak, or...?

**Comment by chaosvolt** [comment]
Ah, thank you for the merge. ^^

**Pull request merged**
