### PR TITLE
Show remembered vehicles across z levels

### LINKED ISSUE #48897: Remembered vehicle location is displayed at the ground level instead of the proper one
# Describe the bug

I have my remembered foldable cart accompanying me in my lab shopping spree, but it's shown on map on the ground level instead of however deep it is atm.

# Steps To Reproduce

Load the game and check the map.

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-10552-g227b45b9e3-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2021.05.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6489308/2021.05.10.zip)

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Show remembered vehicles across z levels"

#### Purpose of change

Fixes #48897

#### Describe the solution

Track the z-level for remembered vehicles and show the symbol for the closest z-level. Shows "^" if vehicle is above, "v" if vehicle is below, or "c" if on the current level.

#### Describe alternatives you've considered

None

#### Testing

Loaded a game. Spawned some vehicles on varying z-levels near a silo and bridge. Examined each and set "Remember vehicle position" on them. Saw symbols showing the direction of the vehicle when standing on other z-levels.

Spawned vehicles at the top and bottom of a silo. Saw the symbol change (in the minimap) from "c" at the top, "^" below that, "v" one level above the ground, and then back to "c" at the ground.

#### Additional context

<details>
<summary>Screenshots</summary>

Map:
image

Minimap:
image

Graphical Overmap:
image
image
</details>

### CODE REVIEW

**Review by dseguin — COMMENTED** [review]
Tested this locally and it works as advertised. Nice work!

I see that you added support for the overmap in the sidebar, but the "custom" sidebar uses a different function for drawing the overmap:

https://github.com/CleverRaven/Cataclysm-DDA/blob/931ad4f51dbd6aa4eca33a41b460bcf8c45afa49/src/display.cpp#L1098

Could you implement the same behaviour there? No problem if not, it's not a showstopper.

<hr>

Edit: Spoke too soon :P
Looks like it only works with graphical overmap disabled:

notiles

Enabling it uses the previous behaviour:

tiles

**Comment by haveric** [comment]
I'll take another look at those when I get a chance. Moving this to draft for now.

**Comment by haveric** [comment]
@dseguin I've updated it to support both. I'm not sure how to test the custom sidebar, but it should work the same way. I also decided to move the shared functionality to a function; it was getting to be in too many places and this should prevent accidental changes to one and not the others. Let me know if they belong outside of overmapbuffer though.

Also, is there anything I need to do to notify graphical overmaps of the new names?

**Review by dseguin — APPROVED** [review]
Tested:
- Overmap, non-graphical
- Overmap, graphical
- Overmap widget, default sidebar
- Overmap widget, custom sidebar

Looks like it's all good!

<hr>

For the future, you can swap the sidebar template to "custom" in the panel manager (`}` by default):

panel_adm

As for the new overmap tile ids, my understanding is that the tileset repo has scripts for discovering tile ids. If not, I would just post a comment in the graphics channel on Discord with the new ids just to be sure.

**Pull request merged**
