### PR TITLE
Fix formatting in gfx folder

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
Including the gfx folder in the JSON validation test #48101 will require them to be formatted before the new modified test is merged into master this will ensure the smooth introduction of said test.

#### Describe the solution
Lint gfx folder with this command, and discard changes to `gfx/tile_config_template.json`
```cmd
find gfx -name "*.json" -print | xargs -L 1 json_formatter
```

#### Describe alternatives you've considered
This is a relatively simple yet gigantic change, breaking it up a bit more would be good, the other way that comes to mind is making a PR per-file, not sure if I should do that.

#### Testing
I don't _think_ formatting would affect the behavior of the tilesets, then again I can be wrong about that.

#### Additional context
Using just one line for your config file is pretty cool.

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @int-ua?

**Comment by int-ua** [comment]
> I don't think formatting would affect the behavior of the tilesets

Me neither but I don't have time to test it right now.

**Comment by int-ua** [comment]
> +29,227 −81,181

I would expect it being the opposite, more lines being added than removed. I'll have some time to look into it later.

**Comment by Qrox** [comment]
I think that's because short objects spanning multiple lines are reformatted as single lines.

**Pull request merged**
