### PR TITLE
Survivor Hood and Cowl Changes + Cowls Can Use Filters

### LINKED ISSUE #74218: Scavengers cowl does not accept filters
### Describe the bug

The Scavengers cowl does not need filters when it clearly mentions respirator function. 

### Attach save file

N/A

### Steps to reproduce

Spawn scavengers cowl, doesn't has reload function for filter charges. 

### Expected behavior

Should have filter charges. 

### Screenshots

_No response_

### Versions and configuration

9568831 (tiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kantonine**
#### Summary
Balance "Survivor hood kevlar changes, and Cowl rebalancing"

#### Purpose of change
This is one follow-up to #74188, where I talked about some of the changes that should be done to armor. This specific Pr is to help rebalance both survivor hoods and cowls (mainly cowls) to help make them more useful for average gameplay. It was also annoying to see one major item that hadn't yet been updated for the modern system.

#### Describe the solution
I gave the Scavenger (now mercenary cowl) and Nomad cowls the same filtration effect that filtration masks use, requiring the use of filter cartridges to bolster the environmental protection, while also adding missing proficiencies to both recipes for the nomad cowl. Before, Cowls were in a weird spot not really useful for much. I also readjusted the crafting recipes for a majority of the survivor hoods, and the mercenary cowl to omit ballistic kevlar usage.

#### Describe alternatives you've considered
I did think about not adding the filtration effect, but if its only for smoke, then theres still plenty of things that can still bleed through the cowls.

#### Testing
Tested this many times to ensure that my json was up to scratch, big shoutout to ThatFanficGuy on the community Discord who helped me out with this!

#### Additional context
Untitled
Inspo for the scav/mercenary cowl, the OKZK cap

Fixes #74218

### CODE REVIEW

**Comment by marilynias** [comment]
Are you still on this?

**Comment by Kantonine** [comment]
> Are you still on this?

If I can, I'll try and get this done this weekend

**Comment by Maleclypse** [comment]
helmet_scavenger is used in a recipe test that times how long it takes to make the recipe.  Test will need updating

**Comment by Kantonine** [comment]
> helmet_scavenger is used in a recipe test that times how long it takes to make the recipe. Test will need updating

Hmmmm, I see, how does the test work? If it's okay to do so, i might just scrap the crafting changes atm, and just let someone else who's much more knowledgable change it (especially when looking at the crafting recipe costs, i didn't tweak them properly i feel, on second thought. I might also have to do that with the other changes i have for the suits and the other survivor pieces.)

**Comment by Kantonine** [comment]
Ok, UPDATE TIME!

For this PR, I'm gonna close this down for now, and hopefully be able to re-do this PR in a fraction of the time, and get this issue finally sorted, so i can focus on the other survivor garments.

**Pull request closed without merging**
