### PR TITLE
Obsolete Expanded Reactor Core

### LINKED ISSUE #36881: Reactor Core Expansion Device and the Minireactor
When you install a Reactor Core Expansion Device into the Minireactor, it no longer counts as a Minireactor for installing into a vehicle

# Steps To Reproduce

1. Spawn in a Minireactor and Reactor Core Expansion Device
2. Install Reactor Core Expansion Device
3. Attempt to install it in a vehicle

# Expected result:
The ability to install an expanded Minireactor into the vehicle with it's increased capacity for Plutonium. The reason it should be possible, is because you can install the Reactor Core Expansion Device into the Minireactor and it'll have the 20000 charges of Plutonium as the maximum.
# System info
 - OS: Windows 10
 - Game Version: 0.D-11046-gb0160b4 (tiles)
 - Graphics version: DeadPeople
 - Mods loaded: DDA, Disable NPC needs, Aftershock, Icecoons Arsenal, Medieval and Historic Classes and Shields, Mythological Replicas, More Locations, Fuji's More Buildings, No Rail Stations, Urban Development, No Acid Zombies, No Explosive Zombies, No Fungal Monsters, Simplified Nutrition

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #36881
Expanded Reactor Core has some odd interactions.
Expanded Reactor Core is raving pants-on-head crazy nonsense.

#### Describe the solution
Obsolete Expanded Reactor Core.

#### Describe alternatives you've considered
Keep nonsense Expanded Reactor Core

#### Testing
Load game with no more Expanded Reactor Core

#### Additional context
Expanded Reactor Core.

### CODE REVIEW

**Comment by kevingranade** [comment]
Expanded Reactor Core

**Comment by Night-Pryanik** [comment]
@kevingranade why did you merge this toolmod by yourself in 2015 (#12599) if it's so utterly nonsensical?

**Comment by Zireael07** [comment]
Five years ago, the game was much less focused on realism.

**Comment by Night-Pryanik** [comment]
I know our lore was changed, but using words like "raving pants-on-head crazy nonsense" feels offensively towards @Rivet-the-Zombie who worked on this content.

**Comment by kevingranade** [comment]
It would be offensive to Rivet if I were implying she actually thought that modifying an operating nuclear reactor was a good idea. I'm pretty sure that's not the case. As Zireael points out, it was something allowed by the setting at the time, but not any more.  Regardless of whether the setting allowed it or not though, it was and is nonsense.

**Pull request merged**
