### PR TITLE
Migrate to Astyle 3.0

### PR DESCRIPTION
**Pull request by kevingranade**
Just some misc astyling, with a const thrown in for the heck of it.
Also checking what the jenkins build thinks about it, since I used astyle 3.0.

### CODE REVIEW

**Comment by kevingranade** [comment]
Crap, as expected astyle 3 conflicts with astyle 2.05, so we'll need to do a coordinated version bump.  The good news is it doesn't disagree on that much, so it should be relatively painless to fixup the code base once we bump the astyle version to 3.

**Comment by narc0tiq** [comment]
Sounds like I'll have to build my own astyle. I think I've done that before, actually. Definitely will have to coordinate the upgrade, though.

**Comment by narc0tiq** [comment]
For testing purposes, the build machine (gorgon.narc.ro) now has an Artistic Style version 3.0 available as `/usr/local/bin/astyle3` (should be in PATH). This should make it easier to coordinate the version bump -- you can start referencing `astyle3` from the Makefile, then I can change out the plain `astyle` to the new version, and pull request a version that returns it to normal when ready.

**Comment by Leland** [comment]
If the intent is to migrate, will close https://github.com/CleverRaven/Cataclysm-DDA/issues/20225

**Comment by narc0tiq** [comment]
**Jenkins, rebuild** this please.

(boldface not required, actual regex is `.*jenkins,?\W+rebuild.*`, case-insensitive)

**Pull request closed without merging**
