### PR TITLE
Petrified mine finale message about deaf player hearing screeches fix

### LINKED ISSUE #28969: Deaf characters can hear events of petrified eye mine finale.
**Describe the bug**  
As title. Deaf characters canot hear screams of eye, but they can hear the cracking rock when wyrms spawn. (edit. In polish version it was saying about rock cracking, in english it apparently mentions sounds made by wyrms, wathever anyway) 

Mine eye pedestal event

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.D-572-gc62f18a (tiles)
 - Build 8621
 - Mods loaded:

Dark Days Ahead
Disable NPC Needs
Filthy Clothing
Mutant NPCs
Beta National Guard Camp
Sleep Deprivation
Z-levels enabled

**Additional context**  
Just a remindeer. This event is still kinda broken, because to trigger it you need to activate pedestal, and you can do it only after picking up eye. Most players will just grab the eye, and leave place without even knowing there are supossed to be enemies. Its a known isue for some years apparently. Maybe some other mechanic is needed, like plant gathering to get the eye from pedestal, instead of spawning item on furniture piece?

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: None```

#### Purpose of change
Closes #28969.

#### Describe the solution
Just added a check for deaf player.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Thanks for catching that.

Some side notes for the future:

There are a few other cases of "You hear ..." message where `is_deaf` is not checked. Can you please address them too? For example:

https://github.com/CleverRaven/Cataclysm-DDA/blob/d2d99e01686cefd0d8a146f4d29c0807c463cab0/src/trapfunc.cpp#L1095-L1099

Also it is possible that we should use `player::can_hear` instead of `player::is_deaf` (the former includes the latter).

**Comment by Night-Pryanik** [comment]
Ok, I'll check this out.

**Comment by Night-Pryanik** [comment]
> Also it is possible that we should use player::can_hear instead of player::is_deaf (the former includes the latter).

`can_hear` requires a specific volume though. Sometimes it is unknown what volume should there be - for example, what volume of `grinding of shifting rock` in your example?

**Comment by ZhilkinSerg** [comment]
That I don't know, but we can start with base volume value of 6 (noise of player character footsteps).

**Pull request merged**
