### PR TITLE
Power storage bionics using Bionic Slots

### PR DESCRIPTION
**Pull request by dunstad**
#### Summary

SUMMARY: Content "Adds power storage bionics that use bionic slots"

#### Purpose of change

With this PR I want to confirm whether this is a reasonable model to proceed with for power storage under the bionic slots system. 

#### Describe the solution

One new bionic is added that gives power, takes up slots in the torso, and is uninstallable. A flag for bionics that may be installed more than once is added, and the uninstall procedure for bionics is modified to support multiple bionics with the same ID. 

#### Describe alternatives you've considered

Instead of adding new bionics, the existing power storage bionics could be modified to use slots.

UI could also be added allowing the player to choose where to install bionics. This would allow one or two bionics to be installed in various slots in the body.

I chose the current approach because leaving the existing power storage bionics untouched seems best for backwards compatibility, and there currently is not any UI for choosing where to install bionics.

#### Additional context

I've made no attempt to balance the numbers for this bionic, and I don't think it should spawn anywhere right now. The current installation process and existing bionics appeared to be unaffected by these changes in my testing.

If this seems like a reasonable approach to power storage using bionic slots, in future PRs I would like to add a Mark II version, balance the numbers for their slots and power capacity, and possibly give them cooler names. Eventually we would want them to spawn in place of the current power storage bionics as well.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I appreciate your work, but honestly I don't like the approach. I would prefer alternative you mentioned:
>Instead of adding new bionics, the existing power storage bionics could be modified to use slots.

Power Storage CBMs are essentially batteries that should be rather easy installed in a new bionic, say, `Bionic Energy Station` with several slots for PS CBMs.

**Comment by Hymore246** [comment]
> 
> 
> I appreciate your work, but honestly I don't like the approach. I would prefer alternative you mentioned:
> 
> > Instead of adding new bionics, the existing power storage bionics could be modified to use slots.
> 
> Power Storage CBMs are essentially batteries that should be rather easy installed in a new bionic, say, `Bionic Energy Station` with several slots for PS CBMs.

This idea is pretty much what I was thinking too. Have say, a Torso slot CBM that comes with a base amount of bionic power and a few "slots" that you can install Power Storage CBMs into to increase your total bionic power. Think how a computer has RAM slots or PCI slots. There could be "bigger" versions of the CBM with more base power and/or more slots. You would still need an autodoc to swap storage sizes but you could argue that it would be very fast and require little to no anesthesia due to how the CBM is setup. This change could also be a justification to add Mark III or higher power storage CBMs too.

**Comment by dunstad** [comment]
Thank you for your comments. Perhaps I'm misunderstanding, but to me the Bionic Energy Station idea sounds very similar to the existing Battery System CBM, and would be a significant departure from the current power storage CBMs, which are installed surgically.

I'm not super attached to the system in this PR, but for making larger changes to the CBM power system, I feel that some larger consensus is needed.

**Comment by Hymore246** [comment]
The Battery System CBM lets you eat batteries to recover bionic energy. The Bionic Energy Station is something that would increase your max bionic power.

**Comment by kevingranade** [comment]
On further thought, I'm not clear on the rationale for putting power storage modules anywhere except the torso.
Torso CBMs are presumably installed in the body cavity, limb and head CBMs must replace functional tissue, as such if a CBM isn't *required* to be in the head or a limb, it shouldn't be.

**Comment by dunstad** [comment]
Fair enough, that does mean we don't have to worry about UI to choose an install location for these then. I'll take out the arm and leg batteries shortly.

**Comment by Fris0uman** [comment]
I don't get it, why not just give a bionic slot to existing power storage cbms ?

**Comment by dunstad** [comment]
Originally arm and leg slot bionics were included as well; as they no longer are, that might be a better way now.

**Comment by l29ah** [comment]
> limb and head CBMs must replace functional tissue

Why do you think so? You can heap up virtually unlimited amount of ~~fat~~implants under your skin (that will grow to accommodate even more), given you ensure they don't get in the way of your activities and, in case they're heavy, they better be attached to your skeleton or some other sort of carrying frame.

**Comment by dunstad** [comment]
I'd like to open another PR that updates the existing Power Storage CBMs to use slots in the chest, but I believe it will also be important to update the UI to display them as '2 Power Storage' rather than just repeating the name once for each copy installed. I haven't got that figured out yet, so closing this for now.

**Pull request closed without merging**
