### PR TITLE
Added a biotech seed/fruit (+fix #32590 )

### LINKED ISSUE #32590: "Invalid effect, ID: stim_overdose"
# Describe the bug

```
DEBUG    : Invalid effect, ID: stim_overdose

FUNCTION : virtual void Creature::add_effect(const efftype_id&, time_duration, body_part, bool, int, bool, bool)
FILE     : src/creature.cpp
LINE     : 907
```

# Steps To Reproduce

1. Create new character with profession "Crackhead".
2. Activate item "zipper bag with crack"
3. Get debug message.

# Versions and configuration

 - OS: Arch Linux 5.0.9-zen1
 - Game Version: 0.D-5703-g850f19cd9a
 - Graphics version: Tiles
 - Mods loaded: dda

### PR DESCRIPTION
**Pull request by free-coffee**
#### Summary

SUMMARY: Content "Adds new item/drug 'rejuvenator fruit'"
#### Purpose of change

Adding an high-technology-flair item in farms to make them feel more futuristic. This being a rejuvenator fruit with the gimmick, that it requires a battery to plant the seed to get it. Once the fruit is grown, the effect is nice for melee/movement oriented characters but should be more on the weaker side (since the technology isn't meant for fighting).
(Ran across #32590 so fixed it.)
#### Describe the solution

The inactive seed is a tool which requires a battery with 100 charges to activate. On activation it transforms into the comestible active seed, which can be planted and grow into the 'biogenic growth' which spawns the rejuvenator fruit. The rejuvenification effect is a buff to physical abilities (dex+speed+stamina regen.) and the fruit is addicting (to mutagens, since it is lightly connected & less effort). 
#### Describe alternatives you've considered

Mutating the 'pretty'-trait while 'rejuvenated' is active, but it would require infrastructure which isn't worth for this.
#### Additional context

Issue:
- The 'stamina regeneration' (specifically "stamina_min" and "stamina_max") modifier works, but it's effect isn't included in the 'stamina recorery' value of the debug mode frame-update.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> Adding an high-technology-flair item in farms to make them feel more futuristic

The game is not set in the future, it's set in the present with advanced technology in certain fields.
I could see this working as a rare thing in labs, but not as something that you would find outside of anywhere top-secret. 
If you'd like to adjust it to fit the game's lore better, you can consult the [design document](https://cataclysmdda.org/design-doc/), and the [technology document](https://cataclysmdda.org/technology.html).

**Comment by Moonsabrt** [comment]
'w') if the current CDDA doesent work as it may not work with the setting.
Maybe speak the aftershock+ or the mod devs maybe they will allow it into their mods =v=

**Comment by Rail-Runner** [comment]
This really looks like mod-only content.

**Comment by ZhilkinSerg** [comment]
Does not fit vanilla setting. Try moving it to Aftershock mod or create an external mod.

**Pull request closed without merging**
