### PR TITLE
Batteries are easier to remove

### LINKED ISSUE #18517: Car Batteries should require mechanical 0 or alternatively electronics
Exactly what part of unbolting (or in many case hand unwinding) the battery and putting a new on into the casing is mechanical or requires more than a passing familiarity with how batteries or current work?

With the lack of working vehicles, even a simple change such as this allows a desperate player to walk around with a (heavy) encumbering battery in the hopes of finding a suitable host for it.

### LINKED ISSUE #18532: Cloth roof installation time is negative
Vehicle construction menu lists install time for cloth roof as "-128849016 seconds". Attempting to install a cloth roof results in my survivor working on the vehicle until he dies of dehydration; even being interrupted by a 'You're tired' prompt doesn't stop the construction.

### PR DESCRIPTION
**Pull request by mugling**
- Fixes #18532
- Fixes #18517 
- 5 minutes to install, half that to  remove
- Needs only `WRENCH 1` and no skills

### CODE REVIEW

**Comment by mugling** [comment]
Going to come back to this later when we redo storage batteries but for now this provides a 90% solution

**Comment by pisskop** [comment]
Im not sure, but I think that this only decides the installation reqs?

**Comment by Zilenan91** [comment]
There's also the issue of installing frames taking 4 hours which is probably too long

**Comment by mugling** [comment]
> Im not sure, but I think that this only decides the installation reqs?

Note the new flag `REVERSIBLE`

> There's also the issue of installing frames taking 4 hours which is probably too long

Off-topic here and not likely to be changed - rolling fortresses are supported but not the focus for balance. The extra light frames could be lower however,.

**Comment by codemime** [comment]
> Fixes #18532 and #18517

I doubt the second issue will be auto closed.

**Comment by Coolthulhu** [comment]
Why does it require a wrench for removal?

**Comment by mugling** [comment]
> Why does it require a wrench for removal?

Technically requires pliers. Suggestion as to paucity of `WRENCH 1` recipes was valid. Also batteries do usually have clamps that need unfastening

**Comment by Coolthulhu** [comment]
It sounds like needless detail IMO.

**Comment by mugling** [comment]
> It sounds like needless detail IMO.

That argument could apply to almost all tool requirements! Having to find a pair of pliers isn't particularly arduous especially compared to the current situation.

**Comment by Coolthulhu** [comment]
> That argument could apply to almost all tool requirements!

No, only those that can be satisfied next to trivially, but take disproportionate amount of player time.
By the time you're grabbing batteries, you are very unlikely not to have seen a pair of pliers, but having a welder around is nowhere near guaranteed.

**Comment by mugling** [comment]
How is requiring it a problem though?

**Comment by Coolthulhu** [comment]
The part where you have it already, meaning it doesn't offer any interesting choices or even progression, but just don't have it on person and need to go and fetch it from one of the corpses.

Would be fine as an alternative component that speeds up the process, but adds more tedium than anything else as a required component.

**Comment by Xpyder** [comment]
@Coolthulhu I support the wrench requirement to install batteries that aren't swappable.

But I support it for flavor reasons rather than progression ones.  Usually you need a tool to remove a battery, and when installing one that isn't swappable you need to mount it to the frame somehow

**Comment by Coolthulhu** [comment]
Early on the requirement of a wrench means that you can't set up a crafting rig without having a wrench nearby.
That is, you can't just wiggle them out by force, cut them, unfasten the nut by hand or improvise a wrench from something nearby (bolt+nut), then you can't just place the clamp loose on the battery.
This is very selective realism that results in ten times as many "fuck, I forgot to grab tools from the car" as "OK, it kinda makes sense, I guess". In a game where you can hand-craft a (battery-powered) welder from scrap, hammer scrap into a workable screwdriver, weave seatbelts from strings acquired by dismantling rags and then repairing those seatbelts with bone glue, you can't improvise a wrench.

This would be all excusable if there was a gameplay reason for that.
But at the point where it matters, it only means you need to go fetch pliers/wrench, which are a common drop.
Meaning that the only result here is an extra bit of inconvenience.

**Comment by pisskop** [comment]
Slings are a patch of leather and 20 thread, which is a minor inconvenience to get.
Rubber hoses are easy to get, but a req to siphon gas.
Plastic bottles are easy to get, but are enough to limit early game use of gas.
A screwdriver, just as or more common than a wrench is used to pick a security system.

It is minor.  until you dont have any.  Requiring a pliers, which is ironically rarer than a wrench, makes cheating by using a bridge implausible.

**Comment by mugling** [comment]
One of the early game requirements is obtaining a reasonable set of tools. In particular finding a wrench and hacksaw are especially important. At some point I'd like to add optional tools (that accelerate tasks) but that will have to come in a separate PR.

For now I've fixed the JSON error so this is ready to merge unless anyone feels the `WRENCH` issue is critical?

**Comment by Coolthulhu** [comment]
Conflicts with generic tanks

**Comment by mugling** [comment]
Given this is trivial can it be merged so I can rebase generic tanks against it?

**Comment by Waladil** [comment]
It doesn't seem to be too heavily discussed here, but I'd like to weigh in that replacing (non-swappable) batteries should still require mechanics 1. IMO, mechanics 1 means you're at least capable of correctly identifying which bits are which and that which tools should be used to remove or install things. At mechanics 0, you're literally too unlearned to even recognize that the leads have to be attached to the batteries poles, and/or you don't know which lead goes to which pole. 
Swappable batteries are presumably designed such that it's literally impossible to install wrong (slide in hole) and therefore wouldn't need any mechanics.

**Comment by mugling** [comment]
Fixed merge conflict

**Pull request merged**
