### PR TITLE
Exclusive building additions

### PR DESCRIPTION
**Pull request by Pr0man**
#### Summary
SUMMARY: Content "Made many multitile-buildings exclusively spawn inside cities."

#### Purpose of change
Adresses #28265 partially
Spawning of overmap specials in town was not possible, as their overmap points had negative values and they were not declared `city_building`.
This PR adresses the spawning of overmap specials that should be **exclusive** to towns and thus no longer be found out in the wilderness.

#### Describe the solution
By moving entries from `overmap/special.json` into `overmap/multitile_city_building.json` and declaring them `city_building` many new structures are now allowed to spawn inside towns.
This came with its own set of changes as many buildings were not designed with this in mind and had their overmap field adjusted to allow actual spawning - which in turn meant adressing the direction they were spawned in with some multitile buildings requiring a 180° turn. (The mall and Apartment towers are especially guilty of this) Others needed to be revisited and altered to not be entirely butchered by the spawn behaviour. (Home improvement Superstore and Large Office tower.)
Additions:
25 Multitile buildings:

- Hotel
- Megastore
- Hospital
- Public Works
- Apartment_con
- Apartment_mod
- Office Tower
- Office Tower 2.0
- Large Office Tower
- Office Tower 2.0 Hidden Lab
- Cathedral
- School
- Mall
- Home Improvement Superstore
- Football Field
- Lumberyard
- Botanical Garden
- Landscaping Supply Co
- Storage Units Large
- Storage Units Medium
- Baseball Field
- Abandoned Shopping Plaza
- Zoo
- Stadium
- Movie Theater

#### Additional context
The result:
result
Note that there are still structures missing - namely many things one considers to be parks and suburb structures like ponds, cemeteries and trailer parks.
For the full effect this PR should be merged with PR #28563

### CODE REVIEW

**Comment by Shodan14** [comment]
Lumberyard though?

**Comment by Pr0man** [comment]
> 
> 
> Lumberyard though?

Makes total sense since a lumber yard is nothing but a building supply store that provides lumber. Maybe you were thinking about a sawmill or similar, turning raw wood into appropriate lumber for selling?

**Comment by Shodan14** [comment]
> 
> 
> > Lumberyard though?
> 
> Makes total sense since a lumber yard is nothing but a building supply store that provides lumber. Maybe you were thinking about a sawmill or similar, turning raw wood into appropriate lumber for selling?
Yeah, you're right. I was thinking of a sawmill, which would be out of place in a city. Carry on.

**Comment by ZhilkinSerg** [comment]
Things to follow-up:

- in city specials with size bigger than 1x1 can be partially rewritten by lower specials;

image

**Pull request merged**
