### PR TITLE
Adds blanket to makeshift sling recipe

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
SUMMARY: Content "Adds blanket to makeshift sling recipe"

#### Purpose of change
Diversifying the makeshift sling recipe by adding possible component: blanket

#### Describe the solution
Blankets made of cotton are thin enough to have a knot made on them, so it is feasible to have them as a recipe component.

#### Additional context
Googling "cotton blanket" results in blankets feasible to be used as a sling.

### CODE REVIEW

**Comment by ifreund** [comment]
Welcome to the project! 

You need to format your summary line like
SUMMARY: Content "Adds blanket to makeshift sling recipe."

**Comment by echomirage1** [comment]
> 
> 
> Welcome to the project!
> 
> You need to format your summary line like
> SUMMARY: Content "Adds blanket to makeshift sling recipe."

Thanks. Did I miss the quotation marks?

**Comment by ifreund** [comment]
looks like you were missing the `SUMMARY:` part and the quotation marks. Kevin fixed it up for you though.

**Comment by echomirage1** [comment]
Right. I missed both of those. I will keep an eye out for them next time.

**Pull request merged**
