### PR TITLE
Mutation selector mod

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Mods "Mutation selector mod"

#### Purpose of change
The mutation system leaves plenty of decisions to RNG.  I think some players would appreciate being offered mutation choices for story and roleplay purposes, or to better suit their playstyle.

#### Describe the solution
When the player character acquires a mutation, a selector menu appears which allows players to choose from a list of possible mutations.  Only mutations which the player is eligible for is shown on the list, and mutation category restrictions still apply.  It works with "true random" mutations which can result in a bigger list of mutations to choose from.  As in the base game, certain mutations, such as purifier mutations, may have to be mutated more than once to achieve the desired outcome as conflicting mutations are gradually removed.

Capture

This feature is a balance mod which has to be added into a world before it is enabled.  It is safe to add to an existing save.

#### Describe alternatives you've considered
Make an option instead of a mod.
Remove flavor text to make the menu much smaller.
Allow mutations to be selected for NPCs.

#### Testing
Builds successfully.
A fresh character was given mutagen and primer.
Waited in game until mutation happens.
Mutation selection menu appears correctly when mod is activated.
Mutations with missing prerequisites do not appear on list.
Mutations with threshold requirements only appear when threshold unlocked.
Mutations with bionic conflicts do not appear on list.
Purifier mutations only appear when applicable and correctly downgrades a conflicting mutation by one level.
Only mutations with the correct primer category is shown on list.
List does not show duplicate entries or existing mutations.
Mutations are applied correctly upon selection.

### CODE REVIEW

**Comment by alp7292** [comment]
is it compatible with othermods lile dinomod magicalysm

**Comment by Rewryte** [comment]
> is it compatible with othermods lile dinomod magicalysm aftershock xedra? awesome work btw

Good question.  This should work with pretty much everything.

**Comment by baldamundo** [comment]
Really excited to see this! Have been playing Caves of Qud recently and really enjoying the mutation system in that and was just thinking it would be cool for Cataclysm to have an option that works more similarly. In Qud, whenever you buy a new mutation, you get to pick one out of a random shortlist of three different mutations selected by RNG - which i wonder if it might be a fun option here as a halfway house between full RNG and totally free selection.

**Comment by Zireael07** [comment]
I like the compromise @baldamundo suggested <3

**Comment by Rewryte** [comment]
Believe it or not, I only found CDDA because I was looking for something like Qud.  But yeah, even in that game I never really used the random mutation system because RNG really isn't my thing.  I'll consider a pick-one system as a future option for this, but it probably won't be the default because the whole purpose of this mod is to remove the RNG element.

**Pull request merged**
