### PR TITLE
[WIP] Content - Toiletry Bag

### PR DESCRIPTION
**Pull request by LambdaSix**
#### Summary

SUMMARY: Content "Add a washing kit inline with Shaving & Haircut kit"

#### Purpose of change

Add a toiletry bag, that similar to the shaving kit and haircutting kit, lets you spend some time cleaning yourself up a bit for a mild morale boost and RP value.

#### Describe the solution

Adds 'washkit' and 'survivor_washkit' that when used invoke the iuse 'washkit' that starts the 'washself' activity and gives the player a mild morale boost for having cleaned themselves up.
Add the items to the appropriate loot drop lists where shavekit might be found.

#### Describe alternatives you've considered

Becoming one with the pigs and wallowing in the mud.

#### Testing

Started a new character, debug spawned in a Toiletry Bag and Makeshift Toiletry Bag, used the bag, licked my teeth and felt clean.

#### Additional context

image

### CODE REVIEW

**Comment by KorGgenT** [comment]
This kind of thing needs to be generalized more into a 'maintenance' activity, where you just hit a button and it does all applicable tasks, like cutting your hair, shaving, washing yourself, etc. In terms of user experience, adding a new item that has a morale boosting activity that you have to activate is somewhat poor, and we have been resisting these kinds of activities until such a point that you can do the maintenance activity and just choose the activities in the list.

**Comment by LambdaSix** [comment]
That's fair comment, I'll look into refactoring this to add a proper ACTION_HYGIENE that can be invoked via keybind (and redirect all the various kits to just invoke that action via a single iuse)

Would it be sufficient to search around the player via crafting_inv for appropriate item flags (HYGIENE_SHAVE, HYGIENE_HAIRCUT, HYGIENE_BRUSHTEETH, HYGIENE_WASHCLOTH?) then present a menu with the available options and time they'd take with an additional "all of the above" option and the normal Cancel being at index 0.

This does allow slightly more immersiveness/RP in that we can require Soap, Water and other Disposables from around the player rather than just soap loaded into the item itself. Can add the action to wash basins as well for a furniture activated invocation.

Presumably shaving should be a once a day activity; and for men only?. Women could shave our legs/etc but that's nothing something you'd really need to do every day, and especially in the cataclsym.

Haircutting would be something on a less regular basis I presume. Is there a simple way to track a timestamp on the character of "last_cut_hair" and "last_shaved" to make that work sensibly rather than allowing cutting of hair constantly?

I mostly added the washkit as (yet another) standalone hygiene item because I a) just wanted a quick RP item and B) didn't want to think through all of these questions in great depth :P

**Comment by Rivet-the-Zombie** [comment]
>Presumably shaving should be a once a day activity; and for men only?. Women could shave our legs/etc but that's nothing something you'd really need to do every day, and especially in the cataclsym.

I kept it intentionally vague so as to leave the specifics of *what* is being shaved up to the player's imagination. I see no reason why the game should be enforcing any particulars as they relate to sex or gender.

**Comment by ZhilkinSerg** [comment]
Feel free to resolve conflicts and reopen.

**Pull request closed without merging**
