### PR TITLE
Simulate hair growth

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Simulate hair growth over time."

#### Purpose of change
Simulate hair growth for NPCs and the player over long periods of time. Hair will slowly grow out until it becomes long, and can then be cut back.

~There's a few things that need to happen before this is ready to go:~
This is ready to go, all tasks have been completed.

- [x] Add an EOC to advance hair between the various stages of growth, based on average growth rates.
- [x] Add conditionals to properly carry over hair color between growth cycles, rather than hair color randomly changing.
- [x] Integrate #70017 properly with this system (might need to update my game or port relevant changes)
- [x] Add activated EOCs that can change hair styles in minor ways, like tying and untying a ponytail.
- [x] Add ultra-long hair growth traits that can be achieved via this system, down-to-the-waist type stuff.
- [x] Make sure cutting and cosmetic changes properly work with these traits.
- [x] Edit NPC starting traits to accommodate for trait changes.
- [x] Rinse and repeat with beards.
- [x] If no hair traits have been chosen, randomly assign some on game start.

#### Describe the solution
Add supporting EOCs and mutations to simulate hair growth, allowing players to grow out their hair over time. This currently is only cosmetic in nature.

#### Describe alternatives you've considered
Not doing this.

#### Testing
Repeatedly tested during development cycle, everything works as expected.

#### Additional context
I have some bigger ideas for this, that might be added after the basic infrastructure is up and running:

- Make hair growth based on the hidden health stat, rather than a flat 1 cm/month rate that it currently uses.
- Add a hair type, independent of style, such as wavy, curly, or straight. This should govern what style your hair grows in to, like becoming an afro instead of long hair, so on and so forth.
- Add a preferred hair type that NPCs and players can have, gives a very small (+3-5) morale bonus for "looking stylish" if their hair looks like that. Probably shouldn't give a morale penalty for not having this style, that might be too micro-managey.
- Add NPC logic for cutting hair if it gets too long. Could probably be automatic, or it might require a map item check for a stylists kit in a given radius.
- Add unkempt versions of hair and beards, might give a very slight penalty to social checks. Alternatively, instead of a penalty, being well-groomed gives a slight social bonus.

~This might also need #70086 to work properly. I don't know if there's a workaround for it, though.~

I have also wondered if I should have the beard growth EOCs track if the character is male or female, and work off of that for facial hair growth, but that might violate the game's development policy of selecting gender instead of sex.

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
> I am afraid of amount new traits this PR will generate unless some smart approach would be picked

I don't plan on adding any new traits to that extent, just attaching existing ones to the growth code. You likely shouldn't need to worry about mutation quantity for this PR.

**Comment by fairyarmadillo** [comment]
I'm working on something unrelated, but I thought I'd ask this here in case you know - I've noticed something strange with hairstyles. I don't seem to be able to get rid of them via any method other than directly removing specific ones. If I put the hair_style type on another mutation, it doesn't remove the old hairstyle if I gain it. If I try to add another hair_style via EOCs without removing the old one, I wind up with two hairstyles. This isn't how it works with a haircut kit or the debug menu, any idea what I'm missing?

**Comment by GuardianDll** [comment]
I suppose EoC bypassed the default mutation checks, while hardcoded functions do not - that is something that happened before with EoCs that modified spell levels/experience in any way
It was resolved when Lispcoc made this EoC spell adjustments run event bus, maybe this can be fixed in similar way, tho i believe some stuff would like to preserve bypassing mechanism

**Comment by MNG-cataclysm** [comment]
> I suppose EoC bypassed the default mutation checks, while hardcoded functions do not - that is something that happened before with EoCs that modified spell levels/experience in any way It was resolved when Lispcoc made this EoC spell adjustments run event bus, maybe this can be fixed in similar way, tho i believe some stuff would like to preserve bypassing mechanism

Yeah, the bypassing mechanism is incredibly useful for edge-case scenarios and flexibility. It should be left in for a few things.

**Comment by MNG-cataclysm** [comment]
> I'm working on something unrelated, but I thought I'd ask this here in case you know - I've noticed something strange with hairstyles. I don't seem to be able to get rid of them via any method other than directly removing specific ones. If I put the hair_style type on another mutation, it doesn't remove the old hairstyle if I gain it. If I try to add another hair_style via EOCs without removing the old one, I wind up with two hairstyles. This isn't how it works with a haircut kit or the debug menu, any idea what I'm missing?

Oh, I've figured it out. The hair style EOCs don't have any `"changes_to"` entries, so they won't use that part of the code to transform into something else. That's why getting one doesn't remove another. If those entries are added that give tiered transformations to hair styles, then getting one will remove the other.

**Comment by fairyarmadillo** [comment]
> Oh, I've figured it out. The hair style EOCs don't have any `"changes_to"` entries, so they won't use that part of the code to transform into something else. That's why getting one doesn't remove another. If those entries are added that give tiered transformations to hair styles, then getting one will remove the other.

Oh awesome, thank you. I'm doing some plant stuff and I noticed their leaves weren't getting rid of their hair like they're supposed to. I'm just gonna stick changes_to hair_bald on all the hairstyles in my PR.

**Comment by MNG-cataclysm** [comment]
> Oh awesome, thank you. I'm doing some plant stuff and I noticed their leaves weren't getting rid of their hair like they're supposed to.

If you need to use EOC's for that sort of thing, you can also make a `"processed_eocs": [ "YOUR_EOC_HERE" ]` entry that will remove all hair mutations. This goes in the code of a mutation, and fires when you gain that particular mutations. I believe it also works for variants, too.

**Comment by PatrikLundell** [comment]
Two complications I've though of:
- Baldness doesn't go away over time (to the dismay of many a baldy out there). Shaved obviously does (and I guess those people would rather that it didn't, at least until they've decided to change the style).
- Dyed hair doesn't grow out in the artificial color, but rather the natural one (regardless of how disliked it is, especially when gray and white starts to show up).

Neither of those apply to the current system where whatever you've selected is maintained automagically.

**Comment by fairyarmadillo** [comment]
Baldness is easily fixed by adding a mutation that cancels and prevents all hairstyles. 

Dye should come with an EOC that reverts you back to your old hair color after about 6 weeks. You'd have to pick a natural color and then dye in chargen.

**Comment by MNG-cataclysm** [comment]
> Two complications I've though of:
> 
> * Baldness doesn't go away over time (to the dismay of many a baldy out there). Shaved obviously does (and I guess those people would rather that it didn't, at least until they've decided to change the style).
> * Dyed hair doesn't grow out in the artificial color, but rather the natural one (regardless of how disliked it is, especially when gray and white starts to show up).
> 
> Neither of those apply to the current system where whatever you've selected is maintained automagically.

This is still very much a work-in-progress thing, so I’m going to add that here soon. I plan on using an EOC that fires on game start to select a natural hair color if you didn’t pick it in character creation.

**Comment by MNG-cataclysm** [comment]
I have recently discovered that trait variants do not support a `"processed_eocs"` entry.

**Comment by Maleclypse** [comment]
So I love this, but I worry it may be tedious. Is there a way to once you’ve got a shaving/haircut kit “freeze” at a preferred haircut and sort of hand wave keeping your hair a specific style becomes part of your daily hygiene?

**Comment by I-am-Erk** [comment]
I'd suggest that "slow growing hair" should be a no-cost trait available at character creation, stacked with the other cosmetic traits, that stops your hair from changing. You should be able to turn it on and off either (a) any time you would select a hair style or (b) through the npc hairdresser in the refugee center.

**Comment by fairyarmadillo** [comment]
> I'd suggest that "slow growing hair" should be a no-cost trait available at character creation, stacked with the other cosmetic traits, that stops your hair from changing. You should be able to turn it on and off either (a) any time you would select a hair style or (b) through the npc hairdresser in the refugee center. I slightly prefer B but it's cosmetic so it doesn't matter too much

We coumd just run a check for the player having a hair trimming item in reach when they (intentionally) go to sleep.

Or we could add a check for having an item to EOCs and simply prevent hair from growing if they have the trait, which probably shouldn't be chargen selectable.

**Comment by GuardianDll** [comment]
i'd prefer if activation of a hair trimming item simply give a popup like "do you want to take care of your hair in the future" or something like that, and if respond is "yes", hidden trait is added that stop hair from grow; "no" removes said trait, so player can always return to 'uncontrollable growth'

**Comment by I-am-Erk** [comment]
I would like various personal grooming elements to eventually be handled passively in a downtime activity, but that's getting way out of scope. Though it's a good point that it can possibly be done by an EOC check when you go to sleep now. However this is purely cosmetic, and it really adds nothing to the game if you don't want to deal with your look changing; I don't think we need to overthink it.

The mechanic here for mutations changing over time is hugely valuable, and the RP aspect of being *able* to have growing hair is really cool.

**Comment by MNG-cataclysm** [comment]
Implementing those sorts of grooming checks might have to wait for another PR, but the “no hair growth”, “slow hair growth”, and other such starting traits I can add with this PR. I was planning on JSONizing grooming functions at some point, but I’ll work on this some more and see what happens.

**Comment by I-am-Erk** [comment]
"fast hair growth" (natural), "very fast hair growth" (mutation only) and "unbelievable hair growth" (post-thresh mutation only) would be really fun too, but could be another PR. It'd be fun to have a mutant that has to cut their hair a few times a day.

**Comment by MNG-cataclysm** [comment]
So, I've added a trait that prevents hair growth, and this can be toggled with Vanessa Toby after you unlock her services. That also reminds me, we should probably add proper hair trimming kits into the game too.

**Comment by MNG-cataclysm** [comment]
I plan to add the auto-trim stuff to the game with a later PR when I do more work on this. For now, no-growth mutations should be an acceptable solution for preserving appearances in the face of apocalyptic scenarios. 
(This is why everyone in The Walking Dead is immaculately groomed, despite living in a zombie-infested USA.)

**Pull request merged**
