### PR TITLE
Aprons love

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Content "Adds new cotton and plastic aprons, as well as adjusting the spawns and certain stats for all the aprons"

#### Purpose of change
Well, this started because I found out aprons in game give an impressing 15 warmth! So I went to change this immediately, but I started to think "Why do we only have leather and kevlar aprons in game? There should be cotton ones too...".

#### Describe the solution
And... Here I am sometime later, revamping aprons spawns, adding new cotton and plastic aprons as well as some variants for the cotton one, I also updated the aprons to use the new encumbering modifier rather than min - max, I updated some professions accordingly, and finally... I severely reduced their warmth, this things can't really protect you from cold, even wearing them naked would barely do anything for you.

I changed the weight of the leather apron to something more in line with what real leather aprons weigh (based on amazon), and gave the old weight to the Kevlar one (Since I'm not sure about the real life variants of this item), I also made the Kevlar apron be a little ticker, so it can actually be a cut-resistant apron (It previously gave the same cut protection than the leather one).

#### Describe alternatives you've considered
To just change the warmth of the leather apron, like I originally planed to just do.

#### Testing
Done, it all seems to be working fine.

#### Additional context
The variants for the cotton apron are based around what I found on amazon when searching for aprons.
Aprons!:
imagen

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/57197/files#diff-29c855ed9319c55bc1a0337ae2b84b3ebf0db307695d2043e1c230357ac47b58R62 damn I was gonna make this joke but you just added it 😆

**Comment by Termineitor244** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/pull/57197/files#diff-29c855ed9319c55bc1a0337ae2b84b3ebf0db307695d2043e1c230357ac47b58R62 damn I was gonna make this joke but you just added it 😆

Haha as the one that added the short maid dress, I had to be the one to add the maid apron xD I found it while searching for aprons with weird designs so I said... "Why not?!" And here we are hahaha.

**Comment by Maleclypse** [comment]
Kevlar aprons are used for tire inspections to keep the QA staff from slicing themselves open along with the tire. I’m not sure if that’s what you were asking and they probably have lots of other uses I don’t know about.

**Comment by Termineitor244** [comment]
> Kevlar aprons are used for tire inspections to keep the QA staff from slicing themselves open along with the tire. I’m not sure if that’s what you were asking and they probably have lots of other uses I don’t know about.

That made it to find one with good weight (I only found some very light kevlar aprons before)! Thanks!

**Pull request merged**
