### PR TITLE
Fix Rubik's anesthetic quest

### LINKED ISSUE #56542: Asking Rubik to cyborgify the PC incorrectly complains about the lack of an anesthesia kit
### Describe the bug

The first reponse to "I've brought you those anaesthetic kits for you. Can you help me out?" is a popup saying
"You don't have a anesthesia kit". When the popup is dismissed, the following error report is generated:

 DEBUG    : Attempted a recipe with no available components!

 FUNCTION : select_item_component
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\crafting.cpp
 LINE     : 1798
 VERSION  : 53f9bd3

However, the dialog continues, the mission is completed, the bionic kit is installed, but the anesthesia kit isn't consumed.

### Steps to reproduce

1. Activate the bionic kit installation quest with Rubik.
2. Bring a single full anesthesia kit, which contains the required amount (6000 ml).
3. Enter the dialog above.

### Expected behavior

No complaint popup, no error report, and kit consumption (or, rather, the contents, leaving an empty kit).

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms as the mod PR for it was rejected.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Fix Rubik's anesthetic quest"

#### Purpose of change

- Fixes accidentally finishing Rubik's quest without consuming any anesthetic.
- Prevents errors from Rubik's quest. Fixes #56542
- Updated anaesthesia -> anesthesia
- Reduce requirement down to one liter per Erk's recommendation

#### Describe the solution

Switched anesthetic kits to just anesthetic. Made the quest completable only through dialogue.

#### Describe alternatives you've considered

None

#### Testing

Loaded up a game. Spawned in the overmap special for the exodii. Talked to Rubik until I could get the quest. Made sure that I wasn't autocompleting it just be having the kits on me and that talking to Rubik to finish the quest consumed only the anesthetic instead of the kits.

#### Additional context

Pinging @I-am-Erk for Rubik translation on my tweaked text.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
We can probably drop this to one liter of anaesthetic while you're in there

**Comment by haveric** [comment]
> We can probably drop this to one liter of anaesthetic while you're in there

Done. Let me know if there's any language you'd like to tweak.

**Comment by sonphantrung** [comment]
Quite dumb question, but are there any works on Rubik's CBM removal? Because I see that the PC spends 500$ for Rubik to remove their faulty bionics, only for him to break the character's limb

**Comment by I-am-Erk** [comment]
It's debatable if they'd say "liter" but I am okay with leaving it clear rather than trying to work out something dialectic.

**Comment by I-am-Erk** [comment]
> Quite dumb question, but are there any works on Rubik's CBM removal? Because I see that the PC spends 500$ for Rubik to remove their faulty bionics, only for him to break the character's limb

Is there an issue posted for that? if not there should be.

**Pull request merged**
