### PR TITLE
Move small quivers to leg waist slot

### PR DESCRIPTION
**Pull request by darktoes**
Shifts small quivers to leg slots so as to be more like scabbards (which they are very similar to IRL)

#### Summary
```SUMMARY: Balance "Move small quivers to leg waist slot"```

#### Purpose of change
Not aware of any issues related to this, only that I noticed it a while ago and found it strange enough to have a minor discussion about it, eventually leading to this PR.

Basically, smaller quivers are generally worn on the hip, hung from a belt, very similar to how some scabbards work. This meant that the player had to choose between a belt or belt-like item (e,g chest rig) or wearing a quiver, despite being able to wear any combination of belt-like items and scabbards, sheathes, and holsters. With this change, a player can wear one belt and a quiver or other belt-attached object on each side, which is more realistic.

Comparison images are below, they're clearly very similar in execution.

#### Describe the solution
Quivers (only normal/small quivers, not the larger back-worn ones) are moved from the TORSO, WAIST slot to the LEG, WAIST slot, which presumably represents something worn hanging from the belt rather than something that is or conflicts with a belt.

Quivers also received a few extra points of coverage and encumbrance, to be more in line with scabbards.

#### Describe alternatives you've considered
Make quivers a full belt-like item, including pouches and pockets for storage. This would also be perfectly reasonable, but I feel is more intrusive.

#### Additional context
Hip-quiver:

https://www.octobermountainproducts.com/wp-content/uploads/2016/03/60876.jpg

Scabbard:

https://i.pinimg.com/originals/7e/9e/55/7e9e554b8f306b41f52a9fb686296032.jpg

### CODE REVIEW

**Comment by SirPendrak** [comment]
Most scabbards are worn IRL around waist, and i believe they are represented in game with baldric. Sword scabbard in game can only store small swords, generally only slightly bigger than machette, and i believe its strapped firmly to your thigh. But you can't put longsword in it, for that you have mentioned baldric. 
As for change, maybe introduce 3rd type of quiver instead of changing this type?

**Comment by darktoes** [comment]
The baldric appears to be worn more on the back, or at least the strap is. That sounds more like the larger, belt worn quiver. The only time I could see it being reasonable for the quiver to take up the waist torso slot is if it were worn on the chest, and I'm not aware of any quivers that do that. Back and hip seem to be the only places quivers are commonly worn, so I'm not sure why a third would be necessary.

**Comment by jbytheway** [comment]
> Quivers (only normal/small quivers, not the larger back-worn ones) are moved from the TORSO, WAIST, STRAPPED slot to the LEG, WAIST, STRAPPED slot, which presumably represents something worn hanging from the belt rather than something that is or conflicts with a belt.

WAIST and STRAPPED are mutually exclusive -- they are both layers (I realise this is a little counter-intuitive).  I think you've actually moved them from TORSO WAIST to LEG WAIST.

**Comment by darktoes** [comment]
You're correct. I seem to have gotten large and small quivers confused a bit in the explanation. I'll edit the description of this PR, but there's no functional difference.

**Pull request merged**
