### PR TITLE
Sports car racing wheel fixes

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Bugfixes "Sports cars spawn with racing wheels"```

#### Purpose of change
#27723 by @mlangsdorf added new wheel types to racing cars, but currently the four racing cars have two steerable standard wheels in front and two steerable racing wheels in the back.

#### Describe the solution
Changing the tires on the Sports Car, Electric Sports Car, Electric Racing Car and Atomic Sports Car to have steerable racing slicks in front and non-steerable racing slicks in the back.

#### Describe alternatives you've considered
I haven't found any discussion or description on why the tire setups are like that. Could be that these are the intended setups. If I'm wrong about this I will close the PR.

### CODE REVIEW

**Comment by RarkGrames** [comment]
Closing this, changing the wheels mess up the travis tests.

**Comment by BevapDin** [comment]
> changing the wheels messes up the travis tests.

Well, it messes up the test suit because it affects vehicle efficiency and range. This is to be expected. It may still be a worthy addition to the game.

**Comment by RarkGrames** [comment]
Well, ok, I can restore it, if you think it can work. I didn't want to have stuff I can't fix myself.

**Comment by ZhilkinSerg** [comment]
You need to update tests data. Compile your branch and run "vehicle_make_efficiency_case" test case. It would output updated numbers:

```CPP
    test_vehicle( "beetle", 767373, 294400, 235600, 77390, 58340 );
    test_vehicle( "car", 1072322, 530700, 312700, 47890, 28180 );
    test_vehicle( "car_sports", 1105918, 444100, 317900, 39180, 23440 );
    test_vehicle( "electric_car", 1070791, 212500, 121700, 17430, 9118 );
    test_vehicle( "suv", 1271990, 998800, 492900, 71890, 34300 );
    test_vehicle( "motorcycle", 162785, 76870, 62950, 47530, 38890 );
    test_vehicle( "quad_bike", 264745, 75950, 75950, 35080, 35080 );
    test_vehicle( "scooter", 62287, 266900, 258300, 195200, 189700 );
    test_vehicle( "superbike", 241785, 72120, 46710, 34580, 21720 );
    test_vehicle( "ambulance", 1783889, 433100, 351300, 65530, 48600 );
    test_vehicle( "fire_engine", 2563241, 1171000, 970800, 248500, 219000 );
    test_vehicle( "fire_truck", 6259233, 308500, 200800, 19950, 4747 );
    test_vehicle( "truck_swat", 5939334, 505800, 349500, 30060, 7719 );
    test_vehicle( "tractor_plow", 703658, 528000, 528000, 121900, 121900 );
    test_vehicle( "apc", 5753619, 1100000, 942800, 132800, 91850 );
    test_vehicle( "humvee", 5475145, 607600, 342700, 25880, 9263 );
    test_vehicle( "road_roller", 8779702, 369800, 412000, 22990, 6996 );
    test_vehicle( "golf_cart", 446230, 52800, 104200, 26830, 13890 );
```

which you need to put into `/tests/vehicle_efficiency.cpp`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/457d06c8aed70841a9bbb341a04247dc32c7e65b/tests/vehicle_efficiency.cpp#L431-L451

See https://github.com/CleverRaven/Cataclysm-DDA/pull/26057#issuecomment-427164695 and https://github.com/CleverRaven/Cataclysm-DDA/commit/2ee660784ee6387459015b52352d04524b7205fe as an example.

**Comment by RarkGrames** [comment]
Thanks for the help. I will try to figure it out.

**Pull request merged**
