### PR TITLE
Set disinfectant freezing point to -19C

### LINKED ISSUE #58151: Antiseptic freeze point?
### Is your feature request related to a problem? Please describe.

I think that most antiseptic contain a fair amount of alcohol. Alcohol has a freeze point of -100°C so I am not sure if antispetic should freeze in winter.  Does anyone know the IRL freeze point of the various antiseptics in the game?

### Solution you would like.

Adjust the freeze points of antispetic drugs to IRL values.

### Describe alternatives you have considered.

_No response_

### Additional context

Non US here so I am not sure what the standard antispetic in the game is made of.

### PR DESCRIPTION
**Pull request by matt32106**
#### Summary
Bugfixes "Set disinfectant freezing point to -19C"

#### Purpose of change
Fixes #58151

#### Describe the solution
Set freezing_point value in the json

#### Testing
Material unfroze after waiting a few hours in -6C weather.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I can tell you now I am quite sure it will be culled from the changelog, but if you wish to keep the summary line, I would change the category to `Bugfixes`.

**Comment by Maleclypse** [comment]
https://rescuedisinfectants.com/wp-content/uploads/2019/01/Cleaning-and-Disinfection-Procedure_Cold-Weather_US_Nov2016.pdf

**Comment by matt32106** [comment]
@Maleclypse Thanks for this document, interesting. Note however this is about hydrogen peroxyde and I made the PR on the assumption that the "disinfectant" object was referring to isopropyl 70% (there is a different "hydrogen peroxyde" object too in cdda).

**Comment by Maleclypse** [comment]
> @Maleclypse Thanks for this document, interesting. Note however that it is about hydrogen peroxyde and I made the PR on the assumption that the "disinfectant" object was referring to isopropyl 70% (there is a different "hydrogen peroxyde" object too in cdda).

Please add a comment to the item saying that you are basing it off of that.  The recipe to create disinfectant does not currently create isopropyl alcohol if I'm reading it correctly.

**Comment by matt32106** [comment]
Description updated

**Comment by matt32106** [comment]
i'll be back

**Pull request closed without merging**
