### PR TITLE
Bones tweaks

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add human bone broth and recipe for it.
2. Add sealed jar of human bone broth and recipe for it.
3. Add tainted bone meal and recipe for it.
4. Add human broth as a possible component in sap soup recipe.
5. Add tainted bone meal as a possible component in glass shard.
6. Add human bone as a possible component for making bone meal and stone knife.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Tainted bone meal would probably not be too useful for fertilizing - it is supposed to be poisonous.

Sap soup could probably use both human and regular bone broth. It can use the regular, vegetable broth already.

**Comment by Darkyhard** [comment]
Well, actually plants won't mind if you use something rotten as a fertilizer, and blob itself doesn't appear to be poisonous for plants.

**Comment by Snaaty** [comment]
I'll have to agree with cool here that having fertilizer made out of zombie bones probably won't work on regular plants.

**Comment by Coolthulhu** [comment]
Human bone broth recipe had improper id (created sealed jar of regular bone broth).
Fixed on my side

**Pull request merged**
