### PR TITLE
Make no-vitamins mod default

### LINKED ISSUE #20513: Hide vitamins by default for 0.D
Currently the vitamin system does nothing mechanically.
Not a thing. Zero.
It only prints warnings which mislead the players who aren't yet aware that the game is lying to them.

False warnings like that are objectively wrong. They aren't just a flavor thing - they explicitly warn of effects that never come.
While implementing penalties would be a way to fix false warnings, I'd rather not experiment with it so close before 0.D.

After 0.D we can try doing something with the system. I recall @pisskop doing some experiment with vitamins in his mod, so his experience could be helpful with making vitamins matter in core.
But that's for post-0.D experimentals. Now the question is: do we want to disable it by making the no-vitamins mod default or hardcode the disable for 0.D and then remove the hardcode afterwards?

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #20513

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Why is this even a mod? If it doesn't do anything, shouldn't this change just be a part of the base game?

**Comment by Coolthulhu** [comment]
It probably should, but was originally inverted and I went with minimal fix for now.

**Comment by Lady-Luck** [comment]
Why even have a mod that introduces or removes a completely nonfunctional mechanic, though?

**Comment by Coolthulhu** [comment]
So that it can be made functional later.
It's safer to introduce giant changes as mods than to risk them being disruptive.

**Comment by kevingranade** [comment]
To unpack the reasoning a bit:
Large changes like this are dangerous to merge all at once.
The leading options for managing this are to develop in a separate branch
or develop in  the main codebase but deactivate the feature until it's
ready.
It takes significantly more dev time to develop features on a separate
branch and then merge them all at once.

That's it in a nutshell.

**Pull request merged**
