### PR TITLE
Obsolete defunct no joke monsters mod

### PR DESCRIPTION
**Pull request by mugling**
Given `core` currently blacklists all the same monsters by default this mod doesn't do anything so can be safely deprecated

### CODE REVIEW

**Comment by DangerNoodle** [comment]
I would assume it was only retained to prevent load errors.

**Comment by mugling** [comment]
Nope, we have a mechanism for that, it was just forgotten about. We ship loads of mods that barely work, have no maintainers or as in this case are entirely redundant. I'm going to work through and try and get to the stage where everything is both working and has an active maintainer.

**Comment by Zireael07** [comment]
@mugling: what do you mean by "core"? I've been using No Joke Monsters for months...

**Comment by mugling** [comment]
> @mugling: what do you mean by "core"?

`core` being the game without any mods.

> I've been using No Joke Monsters for months...

See `data/json/default_blacklist.json` - the contents of which are blacklisted even if you don't enable any mods.

**Comment by DangerNoodle** [comment]
> Nope, we have a mechanism for that, it was just forgotten about.

That seems like a sensible idea then.

**Comment by SeanMirrsen** [comment]
So wait, the game has a "default blacklist" of content that it has, but never uses.... is there a whitelist mod to override the default blacklist? I've been using the No Joke Monsters mod since forever, but just the sole concept of a "default blacklist" is confusing to me. Why not just remove the content if the game is designed to ignore it?

**Comment by mugling** [comment]
We have:

1. Content in the main game that is first loaded (eg. `jacqueshammer`)
2. Then unloaded via `default_blacklist.json`
3. Except when for a mod (`crazy_cataclysm`) where it is un-unloaded via an `ITEM_WHITELIST`

The item requires supporting definitions in core so it can be used as an alternative to regular tool (even though 99+% of players have it disabled). We even have C++ code support along with some translations and even open bugs for it. It's not even a funny joke!

Or even better:

1. We load `mon_zombie_jackson` in the core game
2. Then unloaded him via `default_blacklist.json`
3. Except when for a mod (`crazy_cataclysm`) where it is un-unloaded via an `MONSTER_WHITELIST`

Even better though `mon_zombie_jackson` has specific clothes than only he drops (eg. `jeans_red`) which someone forgot to blacklist in core even though they can never spawn without him.

So yes, the loading code has a double-negative and some extreme bloat. But I'd put money on an attempt remove `jeans_red` would result in complaints about 'lack of immersion' or such even though it's defacto guaranteed the poster hasn't been using that item (because it's impossible).

I'd like to carry on cleaning up some of this nonsense so we can finally get better mod support. Sometimes we need to stop defending content that actually doesn't work or is so marginal in it's utility that it just stands in the way of progress.

**Comment by mugling** [comment]
If the above is clear then a link back to the forum would be a good idea. If it's and someone feels up to condensing that argument down then that would also be appreciated. If it's not clear at all I'll try and expand upon it.

**Comment by SeanMirrsen** [comment]
So... okay. The game has a default blacklist that can be overridden. So far so good.

Why the loading/unloading? I mean, yes, I am far from an expert programmer, but it seems to me that actually building a list of things to be loaded or not loaded beforehand is sort of... more efficient?

1.) Scan default content and mod files for black/whitelists.
2.) Combine all blacklists and whitelists into a single filter list, in the order they are selected.
3.) Proceed with loading all available content, discarding everything the master filter list says should not be there.

This should theoretically work for all cases, with no extraneous or labyrinthine code.
The specific case of the jacqueshammer being a buggy tool by itself is indeed a possible cause for termination (or better, moving to a mod just in case someone is very attached to it), and the thing with the near-nonexistent theoretical `jeans_red` does not functionally hurt the game, plus leaves the item loaded for the wish menu.

**Comment by mugling** [comment]
> I am far from an expert programmer, but it seems to me that

I'm not stuck on how to go about fixing it - I'm just providing the background context you asked for.

> and the thing with the near-nonexistent theoretical jeans_red does not functionally hurt the game

There's a lot of similar examples and they hurt developers wading through dozens of obsolete items.

**Pull request merged**
