### PR TITLE
removed number of chapters from abstract book template

### PR DESCRIPTION
**Pull request by enaantd**
#### Summary

SUMMARY: Bugfixes "removed number of chapters from abstract book templates"

#### Purpose of change

Book templates had a fixed number of chapters, making it so that skill books had a limited number of uses, which is unwanted.

#### Describe the solution

I removed the number of chapters value from the abstract template.

#### Describe alternatives you've considered

None

#### Testing

I spawned a skill book in-game (Food Fashions for Young Moderns) and it had no number of uses, as opposed to previously.

#### Additional context

None

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
This will make fun books added by #37377 that use that abstract have infinite chapters.

**Comment by enaantd** [comment]
I don't know which fun books should have a limited number of chapters and which shouldn't. I'd say all or none?

**Comment by kevingranade** [comment]
All fun books should have a limited number of chapters.

**Comment by enaantd** [comment]
I *may* be able to do this, but I'm unsure of several things and I think I'd benefit from some insights before starting a long and repetitive process.

Currently, many book templates are divided between fiction and non-fiction. I don't quite understand the need for this, and this can cause some problems. For instance, a scifi novel should be a fiction book (though in the cataclysm scifi may be reality, but we're talking about books written before the cataclysm), but a war novel may or may not be fiction. Yet, it makes sense to have a scifi novel and a war novel share the same template since they're, well, novels.

Unless there's something I missed, I think it would be opportune to change the separation in the templates from fiction/non-fiction to skill book/fun book. This would solve the number of chapters problem without having to edit each book's data or add even more inheriting templates. It may be out of scope for this PR and maybe way harder than I'd imagined, but I'm willing to take a look at this if my suggestion is appropriate.

**Comment by Jerimee** [comment]
I think the problem stems from the fact that some skill books grant fun.  Presumably that fun should stop at some point, but the skill development (ie learning) shouldn't stop until max-learn level is achieved.

> Book templates had a fixed number of chapters, making it so that skill books had a limited number of uses, which is unwanted.

This is true.

> All fun books should have a limited number of chapters.

This is true.

> Currently, many book templates are divided between fiction and non-fiction. I don't quite understand the need for this, and this can cause some problems. For instance, a scifi novel should be a fiction book (though in the cataclysm scifi may be reality, but we're talking about books written before the cataclysm), but a war novel may or may not be fiction. Yet, it makes sense to have a scifi novel and a war novel share the same template since they're, well, novels.

This isn't false but...

Before I started messing with books, generally speaking all SKILL books were nonfiction and seemed hardbound.  All FUN books were fiction and seemed paperback.  So the convention I created and am trying to standardize is (fiction or nonfict), then form (typically paperback or hardbound, though there are 6 or 7 forms in total), then subject.

That order might be (might be, not is) less than ideal, but for the templates to "cascade" (in the CSS sense) or "nest" (in the Russian Dolls sense), an order is needed.  Since merely organizing the books in the present order is incredibly time intensive, I'm doubtful that changing the order is a good use of anyone's time.  

Look at itemgroups/SUS/library.json and items/book/abstract.json to see how I'm trying to organize them.  (You probably already have...)

My intent is this, with each abstract copying from the one above (until the actual book)

1. book_nonf__tpl 
2. book_nonf_hard_tpl
3. book_nonf_hard_cook_tpl
4. food_fashions (an actual book)

book_nonf_hard_tpl should have chapters, but skill books like those under book_nonf_hard_cook_tpl should not

There is chance that just setting **"chapters": 0** to book_nonf_hard_cook_tpl fixes the problem, but I'm just guessing.  If that doesn't fix it, a hack might be to give book_nonf_hard_cook_tpl such a large number of chapters that it isn't an issue with regard to learning - but that doesn't resolve the issue with fun needing to be capped.

Not having a good answer at the moment, I'm tempted to suggest these admittedly cruddy solves:

- leave it as is, even though the skill learn cap is unintentional
- make it so no skill books are fun

Feel free to DM me on discord.  Sorry for the long comment.

**Comment by kevingranade** [comment]
This is a symptom of the abstract being wrong, #37377 added a bunch of abstracts, redefined existing books in terms of those abstracts, and added new books.  It introduced chapters to some of these books inappropriately.  If you look at #37377 and restore the previous state of the pre-existing books, you're going to be 90% of the way there.

**Comment by Jerimee** [comment]
How is the abstract wrong?

It would be good to document the error so that it isnt repeated.

**Pull request closed without merging**
