### PR TITLE
More Survival Tools javelin rebalance

### LINKED ISSUE #30140: More Survival Tools removes thrown_damage from the javelin and iron javelin, making them useless without an atlatl
**Describe the bug**  
The majority of damage on throwing weapons comes from thrown_damage. More Survival Tool's versions of javelins do not have thrown_damage and deal demonstrably less damage than vanilla when thrown. 

**To Reproduce**  
1. Make a player with javelins from the More Survival Tools mod.
2. Spawn the debug monster. 
3. Throw javelins at the monster. Note that the damage is far below the listed melee/ammo damage. 

**Expected behavior**  
Javelins should be able to be thrown without an atlatl (in case one is unavailable or if the thrower wants to use the Railgun CBM with iron javelins) and deal the correct damage. 

Versions and configuration(please complete the following information):

- OS: Windows 10
- Game Version: 0.D-2460-gc0cef43
- Graphics version: tiles
- Mods loaded: dda, More Survival Tools

### PR DESCRIPTION
**Pull request by Highmongrel**
#### Summary

```SUMMARY: Balance "Rebalance Javelins while More Survival Tools is active"```

#### Purpose of change

While MST is active, javelins are by far the worst throwing weapon, with iron javelins having roughly the same damage as the nerfed throwing sticks, even at high throwing skill and strength. Throwing knives do roughly 50% more damage while stacking in hand.

This is largely due to the thrown damage not being brought over from the base game when it was changed to an ammo type.

Javelins also aren't generally designed to be as sturdy in melee. As such I've added the Fragile_Melee tag to them.

Additionally, the javelin bag was recently changed from holster to bandolier, which both interacts poorly with items that don't stack in hand and disables the ability to hold different kinds of javelins in the same bag. Holster only didn't work due to improperly configured min_size and a lack of the javelin tag on the changed javelins.

#### Describe the solution

Implement thrown damage from base game on wood and iron javelins as copy-from doesn't seem to grab it. Add thrown damage on copper and stone javelins following the existing pattern
This should close #30140

Add FRAGILE_MELEE to javelins

Change javelin bag back to holster
Add javelin tag to javelins
Configure bag size to properly fit javelins

#### Additional context

The recently implemented change to javelin bags also increased the amount of javelins it could hold to 10 . Kept it at 10 for now, but might nerf it back down to 5.

### CODE REVIEW

**Comment by darktoes** [comment]
1) STR_DRAW doesn't work properly at the moment and I strongly advise against using it.
2) My understanding is that thrown damage values won't work so long as the item is listed as ammunition. You'll have to test to make sure it's working correctly.

**Comment by Highmongrel** [comment]
Fair enough, I'll remove STR_DRAW for now.

As for thrown weapon damage interacting with being ammunition, most thrown weapons besides javelins are ammo of the "thrown" type and currently use it. 
Testing in game with throwing 8 str 8 with iron javelins against the debug monster had crits going from 14 without thrown damage to around 40 or so with thrown damage.

**Comment by Ilysen** [comment]
I always wondered why the thing that carried humans out of the Stone Age was so weak in-game. This is a fine note.

**Comment by kevingranade** [comment]
``have the atlatl at high(8) skill do roughly the same damage as a glock 17 with JHP rounds at low(3) skill while having longer range.``
I see no support for this in any sources I've been able to find.
Specifically, the total energy delivered by the javelin CAN be in the same ballpark as the 9mm round, but in practice it would be far lower.
I don't have any indication that 

The Glock side of the equation is fairly well understood, so we can just state some  numbers.
Effective range: 50m
Muzzle velocity: 375 m/s
Projectile weight: 7 - 8.3 g
Projectile energy: ~530J
This is all just wikipedia type info.

The javelin is a bit harder to get information for.
Effective range: 20m
Launch velocity: up to 35 m/s
Projectile weight: 800 g
Projectile energy: Up to 490J, but see below.

The problem with these numbers is it is for a peak condition olympic level javelin thrower, throwing a javelin solely for distance using a running start.
1. Player is not a peak condition olympic thrower.
2. Player is not throwing for distance, but accuracy.  Studies have shown that human musculature has a definite tradeoff between force applied and accuracy when throwing.
3. Player is not performing an olympic running throw. This technique is ridiculously demanding on the thrower's body and is terrible for accuracy.

I can't see this justifying anything upwards of ~200J (22-23 m/s throw velocity) for a throw from a non-olympian without a running start.  This puts total energy delivered, and therefor total damage output somewhere around half that of the 9mm round.

The accuracy issue is even more problematic, I'm seeing pretty consistent agreement that 20m is a solid limit for accurate javelin throws.

Source for javelin launch energy:
https://www.degruyter.com/downloadpdf/j/humo.2009.10.issue-1/v10038-009-0003-5/v10038-009-0003-5.pdf
Sources for Javelin effective range:
https://worldatlatl.org/wp-content/uploads/2018/12/ISAC-RULES-PACKAGE-10.6.18.pdf
https://natureecoevocommunity.nature.com/users/207960-annemieke-milks/posts/43943-early-neanderthal-spears-going-the-distance

**Comment by Highmongrel** [comment]
Hmm, I hadn't actually thought of the physics behind it. 

Javelins themselves have no change from base game outside of their volume. Changing their range and damage would involve changing the throwing code itself, which I'm not really comfortable doing.

As for the atlatl, I wanted it to be roughly twice the effective range of throwing by hand, with a slight increase in base damage. This put it in the same ballpark of a glock with longer range, so I used it for adjustment.

That the effective maximum range of a glock is currently around the same range as a skilled thrower with a wooden javelin in base game, is another problem altogether. This push is just to bring MST javelins in line with base game throwing weapons, and have the atlatl not be strictly worse then throwing by hand.

**Comment by Highmongrel** [comment]
Well, for now I'll remove edits to the atlatl itself, and just leave the changes to javelins and the javelin bag.

**Comment by kevingranade** [comment]
Your styling is hosed, probably tabs.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild

**Comment by Highmongrel** [comment]
Yeah looks like it was tabs. Will try to be extra careful of those going forward. Looks like Travis is stuck up on a vision test though.

**Pull request merged**
