### PR TITLE
Vehicle wheels now will be damaged on lava

### LINKED ISSUE #21543: Vehicles ignore lava tiles
Driving over lava, such as the ones in rifts, or those small lines of lava that sometimes pop up in the surface, does not affect the vehicles. No damage taken (probably even if the vehicle is made out of wood). 'course, player characters will get damaged by the intense heat, especially in a rift.

On the other hand, fires, such as ones from a molotov, will damage cars.
cata1

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes  #21543.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I added code to explode the tanks with flammable fuel, but I didn't manage to make them actually explode. I also tested with flamethrower firing at the gasoline tank and throwing incendiary grenades, but I still wasn't able to explode the tanks. Can anyone please confirm if exploding is actually happening and not bugged?

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by ituluwituluwzev** [comment]
In my experience, whichever grenade the tank drone fires makes the tank explode.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by codemime** [comment]
> I added code to explode the tanks with flammable fuel, but I didn't manage to make them actually explode.

There's no way they can explode since `vehicle::handle_trap()` operates only on wheels (`vehicle::wheelcache`). There's an additional check for presence of the `VPFLAG_WHEEL` flag in the function itself.

**Comment by Night-Pryanik** [comment]
Okay, I'll remove the code for the tanks.

**Pull request merged**
