### PR TITLE
[CR] Added Lumberyard variant of the Hardware Store

### PR DESCRIPTION
**Pull request by qbradq**
This PR adds a Lumber Yard variant of the Hardware Store. It is similar in concept to the new Home Improvement Megastore (see #11869) but is a normal mapgen structure.

**Specific comments requested**
- I could not get the "mapping" tag to work. Has this been fully implemented yet?
- Using the "items" tag, how can I specify to spawn, say, between 1 and 7 items from the group?
- How can I build a three-sided room with a roof?
- I would like some feedback on the item spawn rate.

**Features and Thoughts**
The store is designed as a storefront with general hardware goods and a large, semi-covered rear lot with bulk hardware and a selection of lawnmowers. There is a side alley providing truck access to the rear lot for picking up bulk purchases. This is based on smaller combination hardware and building supply stores located in small towns where I live in the southern US. I assume there are similar businesses in the New England area.

The spawn rates in the store have been tweaked such that cleaning supplies and paint are the most plentiful being non-survival goods. Hardware and household hardware are less available due to scavenging, and big tools are very limited just to keep the OP meter in check. Bulk hardware is rather plentiful, but only due to the volume of inventory space for it. The idea being that most of the huge inventory has already been looted.

An additional feature are two new shopping cart vehicles as suggested in the mentioned PR. There should be an average of one of these carts per store. The Oversize Shopping Cart provides 275 storage and is basically a larger version of the Shopping cart. The Trolley Cart is the kind of flat bed carts typically found in building supply stores and big-box electronics stores that sell enormous TVs.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> I could not get the "mapping" tag to work. Has this been fully implemented yet?

The way I understand it, mapping is assignment of terrain, furniture and possibly other elements to a character and using the characters to "draw" a map. Like what you're using for the layout.
It seems to be the only kind of mapping related to mapgen in the source.

> Using the "items" tag, how can I specify to spawn, say, between 1 and 7 items from the group?

`"repeat"` tag. For example, in data/json/mapgen/hardware1.json

> How can I build a three-sided room with a roof?

At the moment all floors have roofs. You can have a three-sided room by not adding the fourth wall.
It will stand just fine, but it will collapse easily if some of the walls are destroyed. It doesn't make the walls any more fragile, just makes them take more with them when they fall.

> I would like some feedback on the item spawn rate.

Didn't see it in action, but from the numbers it looks like a lot of empty shelves.
With stuff like construction materials, there is no risk of it becoming OP or getting looted. Non-tool hardware is similarly low-risk.



You could scrap the trolley bed part and just use steel frame. Steel frames are already used for car trunks and wheelbarrow boxes (650 and 275 volume respectively). Or you could just scrap the trolley entirely - a (rare) handjack would be a good thing to loot from a hardware store and it already has an entry in vehicles. Alternatively, the luggage cart uses a trunk part
Oversized basket is technically the same as wheelbarrow, except with different names for parts.

While new vehicles/parts can add flavor, having a new, totally disjoint part that doesn't reuse existing elements can easily make it fall into bloat territory. Especially if the parts can't be crafted or dismantled for materials and don't offer any advantages over existing ones.

**Comment by Zireael07** [comment]
Looks cool, and agreeing about more stuff and scrapping the trolley bed part.

**Comment by qbradq** [comment]
Not sure if I totally screwed up this PR with the master merge there... I'm a bit new to git.

Thank you all for the feedback, I am learning a lot!

I have increased the spawns on the hardware and bulk hardware back to what I initially had it set to before nerfing it thinking it was OP. Thanks for the advice :)

The repeat tag does not seem to work with the "items" tag.

Concrete floors are causing all kinds of jacked-up'ed-ness on my tiles build. Graphical glitches out the bohiney. So for now I've stuck with t_floor everywhere.

I have removed the new baskets. There is now an average 50% chance of a normal shopping cart to spawn in the store front and an average 10% chance for a handjack to spawn in the yard area.

**Comment by KiwiTrinsic** [comment]
Awesome, more hardware store types! I just put in a PR request for another one as well. Unfortunately with the exact same file name. I think the mergers should be able to handle that though and rename one of them.

**Comment by BevapDin** [comment]
> The repeat tag does not seem to work with the "items" tag.

Because it's only usesull when a coordinate range is given like this:
```JSON
{ "item": "office_mess", "repeat": 20, "chance": 100, "x": [ 15, 20], "y": [ 11, 19 ]}
```
This will roll 20 times for coordinates (in the range 15..20, 11..19) and spawn items from office_mess with a chance of 100. Therefor it will spawn at 20 places in the rectangle 15,11 to 20,19.

If you use the mapping, the coordinates are already decided through the mapping. If you want to spawn more, you could increase the chance. Chance (in this very specific situation, other mapgen stuff handles chance differently) is not actually change of one item, it's the chance of one *more* item (starting with 0 items). A chance of 20 means there is a 20% chance of at least one item, a 20%*20% chance of at least 2 items, a 20%*20%*20% chance of at least 3 items and so on.

Other mapgen stuff where it is not useful to place several things (like vehicles) usually interpret as the chance as a single X in 100 chance to either create the object or not.

Alternatively you can create your own group that uses another group to get items (it's basically what you want with the repeat option):
```JSON
{
    "type" : "item_group",
    "id": "...",
    "subtype": "collection",
    "entries":
    [
        { "group": "trash", "count": 10 }
    ]
}
```
This will use the group "trash" to generate items, it will ask that group 10 times and will spawn all items that are returned. (Note: some groups may sometimes not return any item, depending on their content.)

**Comment by qbradq** [comment]
Thanks! I will give this a try.

**Pull request merged**
