### PR TITLE
adding transparency to retrodays

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Interface "add transparency to retrodays"```

#### Purpose of change
retrodays tileset is my favourite but, all the tiles have a black background thus rendering all objects like a black square with the object drawn on that.
the problem is, when you have and object on top of a larger one, like a lighter on a table,
the lighter gfx and its black square background, prevent you to see the table underneath.
it make it look like the table is missing a whole chunk. to the point that if there is few objects (3 or 4) on the table you cannot distinguish there's a table at all.

so i removed the black squares, and left instead a black outline around the contours of the objects.
other tilesets have transparency, so i made it for retrodays too.

#### Describe the solution
i removed black squares around tiles, and left a black outline instead.

#### Testing
i have been playing with that for quite some time.

#### Additional context
in general look for objects on top of bigger objects, like the tables and sofas:
book_desc

another example, look at bed and table:
grab

before:
retrodays-before

after:
retrodays-after

tiles:
Untitled

### CODE REVIEW

**Comment by esotericist** [comment]
I was under the impression retrodays having a black background for things was an intentional stylistic element, given the general aesthetic and the name.

Given that, this possibly should be either a separate retrodays variant or a retrodays tileset mod, rather than an alteration to the original retrodays?

**Comment by captnblood** [comment]
@esotericist 
if that's the case, 
and that retrodays want to keep its black borders, then introducing a variant of it, is fine by me too.
i really like the aspect of retrodays, but i find it look even better without the black squares.

**Comment by ZhilkinSerg** [comment]
> 
> 
> @esotericist
> if that's the case,
> and that retrodays want to keep its black borders, then introducing a variant of it, is fine by me too.
> i really like the aspect of retrodays, but i find it look even better without the black squares.
> i'll let this PR sits for a while, see what people want to decide.

Make it a different tileset, we'll merge it and see players reaction.

**Comment by captnblood** [comment]
@ZhilkinSerg 
ok i close this PR and open a new, with a separate tileset made from retrodays

**Pull request closed without merging**
