### PR TITLE
[RDY] Updated `shelter` definition to make it spawn in worlds with CITY_SIZE=0

### LINKED ISSUE #22828: Game crashes after random character creation
Game version:
0.C 26014

Operating system:
Windows

Mods active:
Dark Days Ahead
More Locations
Urban Development
Beta National Guard Camp
Mining Mod (The current version found here: https://github.com/DangerNoodle/mining-mod)
Craftable Gun Pack

I cannot recreate the initial crash, but whenever a character is generated in the attached world, the game stalls. A message referencing Microsoft Visual C appeared in addition to an ordinary debug message (I don't remember either messages).
[Turner Corner.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1675365/Turner.Corner.zip)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- fixes #22828.

# Screenshots:

image

### CODE REVIEW

**Comment by kevingranade** [comment]
Doesn't setting the upper city distance number to -1 mean all shelters, even when they are spawned with default settings, are allowed to spawn at any distance from a city?
Allowing a shelter to spawn on the opposite corner of an overmap from a city is much worse bug than not allowing shelters to spawn in a city-less overmap.

How about this for a possible solution, we can hack city size 0 overmaps to instead spawn an invisible city with no contents, and then any shelters can spawn near that?

**Comment by ZhilkinSerg** [comment]
Yes, you are most certainly right about such distant shelters.

Very interesting proposition about some kind of virtual city in city-less overmap, though it can also raise some interesting mapgen bugs. I will try to look into it later today.

**Comment by BorkBorkGoesTheCode** [comment]
Would extending the possible start sites and scenarios open to the random character generator be too difficult pre-0.D?

**Comment by kevingranade** [comment]
Also, someone on discord pointed this out (@rawng), people wanting "no cities" probably want "no buildings".
It's a lot more consistent to adjust random character generation to only choose starting locations that appear with the current settings.

**Comment by ZhilkinSerg** [comment]
#22886 is merged, so I will close this for now.

**Pull request closed without merging**
