### PR TITLE
Fix the build for some 'clang' compilers

### PR DESCRIPTION
**Pull request by codemime**
The issue was [reported](https://github.com/CleverRaven/Cataclysm-DDA/issues/16870#issuecomment-221867610) in #16870.

### CODE REVIEW

**Comment by mugling** [comment]
Clang isn't behaving well there but it's a simple fix

**Comment by codemime** [comment]
Yeah, but only some older versions of `clang` stumble here. I tried to compile the project using `clang 3.6.0` on Linux (to see what happens) and it worked just fine. Jenkins uses `clang version 3.5.2` and doesn't complain either.

**Comment by kevingranade** [comment]
We can bump the minimum supported version,  (see COMPILER_SUPPORT.md) but
it's only necessary if the workarounds become excessive.

**Comment by codemime** [comment]
I wouldn't consider this a workaround only. IMHO It looks cleaner. At first an empty object is created (only once). If it can't be filled, it gets returned as is, otherwise it gets filled first.

**Pull request merged**
