### PR TITLE
MA: Shaping the country

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

Mods "MA: The Absolute State of DDA: Part 2"

#### Purpose of change

Overmap overhaul mod for Cataclysm: DDA that uses some features of Massachusetts state when generating overmaps.

#### Describe the solution

See commit messages.

#### Testing

1. Start game in new world with MA mod - during new game start you can use `C` to select city you want to spawn in (start location can have some restrictions attached - city size, city distance, allowed z-levels).
2. Hop between different cities and overmaps (using debug commands) and verify overmap terrain is generated using mod omap files.

#### Additional context

First step (https://github.com/CleverRaven/Cataclysm-DDA/pull/51771) needs to be merged first.

It is second step. We will definitely need to refine overmap terrain files later.

#### Screenshots

_A bit of Nantucket_

изображение

_Nearby Salem_

изображение

### CODE REVIEW

**Comment by NetSysFire** [comment]
Do I spot the isherwood farms being spawned in the north and SSE in the Salem picture?

**Comment by ZhilkinSerg** [comment]
> Do I spot the isherwood farms being spawned in the north and SSE in the Salem picture?

Yeah, most definitely.

**Comment by Inglonias** [comment]
I don't suppose there's a way you can avoid putting 1,400 files in this mod, is there?

**Comment by ZhilkinSerg** [comment]
> I don't suppose there's a way you can avoid putting 1,400 files in this mod, is there?

MA is 1337 omap files big.

**Pull request merged**
