### PR TITLE
More sports balls and items

### PR DESCRIPTION
**Pull request by The-Anjelo-Guy**
#### Summary
Content "Adds several new balls, their deflated forms and other items related to sports"

#### Purpose of change

Just for fluff purposes. Please have in mind I'm working on phone directly at GitHub, this is still a work in progress.

#### Describe the solution

Simply not doing it.

### CODE REVIEW

**Comment by Procyonae** [comment]
You've got pretty crazy lungs if you're blowing these up in 5 secs

**Comment by Procyonae** [comment]
At the very least make the deflated versions copy-from and the volumes proportional

**Comment by The-Anjelo-Guy** [comment]
> You've got pretty crazy lungs if you're blowing these up in 5 secs

I didn't found a better way to do it, to be honest. If I could potentially find a way to give a time to the "transform" thing I would surely do it properly.

**Comment by The-Anjelo-Guy** [comment]
> At the very least make the deflated versions copy-from and the volumes proportional

Come on, it is still a work in progress. You mean, make the deflated versions "copy-from" the inflated versions? Also, I though the inflated and deflated versions would probably have different volume values. Please correct me if I am wrong.

**Comment by Procyonae** [comment]
> Come on, it is still a work in progress.

Which is why I'm telling you asap so it's less work?

>You mean, make the deflated versions "copy-from" the inflated versions?

Or vice versa, doesn't really matter

>Also, I though the inflated and deflated versions would probably have different volume values.

Well ye that's why I said use proportional

**Comment by The-Anjelo-Guy** [comment]
Closing this to focus on other things for the foreseeable future.

**Comment by The-Anjelo-Guy** [comment]
Heh

**Pull request closed without merging**
