### PR TITLE
Propane

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Propane gas and tanks"

#### Purpose of change
I want to add a proper forge for metalworking but the only real option available was a LOT of charcoal. This adds propane as a fuel, which allows gas forges.

#### Describe the solution
Adds propane as a fuel.
Adds tanks in 2, 5, and 20 gallon sizes.

#### Describe alternatives you've considered
As above, lots of charcoal.

#### Testing
Spawned tanks, noted that they contained propane.

#### Additional context
This is obviously useful for things other than gas forges. Lamps, cookstoves, and heaters immediately come to mind. I tell you what.

### CODE REVIEW

**Comment by Shodan14** [comment]
What about makeshift propane explosives?

**Comment by ISuckM8** [comment]
Hey, wouldn't that technically make propane torches a possibility?

**Comment by Shodan14** [comment]
> Hey, wouldn't that technically make propane torches a possibility?

And good camping stoves.

**Comment by Drew4484** [comment]
> > Hey, wouldn't that technically make propane torches a possibility?
> 
> And good camping stoves (and hot air balloons).

There's a ton of uses, I just want to get it working in game before I add accessories.

**Comment by ISuckM8** [comment]
> There's a ton of uses, I just want to get it working in game before I add accessories.
>
> Kevingranade merged commit 7de9626 into CleverRaven:master 1 hour ago

You were saying?

**Comment by Nabo92** [comment]
Is propane flame hot enough for metalworking?

**Comment by Drew4484** [comment]
> Is propane flame hot enough for metalworking?

Yes, I'll be adding a gas forge. These are varied in size and number of burners but all but the smallest can raise temperatures to well over the melting point of steel. They serve the dual purpose of forge welding pieces together and heating larger pieces for shaping.

**Comment by chrispikula** [comment]
Isn't propane transported by weight of the amount that is stored in liquid form inside the tanks?  The 1lb camping mess kit ones, the 20lb BBQ ones, the 40/45lb ones for forklifts?  So why not name the tanks that way?

**Comment by Drew4484** [comment]
> Isn't propane transported by weight of the amount that is stored in liquid form inside the tanks? The 1lb camping mess kit ones, the 20lb BBQ ones, the 40/45lb ones for forklifts? So why not name the tanks that way?

Because in metric countries it's measured by the kilogram. I didn't want to use a title that would make things difficult for translation/non-US players.

**Comment by chrispikula** [comment]
Ah, fair, I was used to filling them up like that in Canada.  Imperial non-standardization strikes again!

**Pull request merged**
