### PR TITLE
Add flashlight attachment for hard hats and military helmets

### LINKED ISSUE #64672: [feature request] Army helmet should have flashlight attachments.
### Is your feature request related to a problem? Please describe.

army helmets should have flashlight attachments.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Features "Add flashlight attachment to hard hats and military helmets"

#### Purpose of change
Fixes #64672
They can have them IRL, so why not ingame

#### Describe the solution
add a flag for head attachment, and a pocket for each of the items

#### Testing
opened game, all of them have the pocket and accept the flashlight item in them

### CODE REVIEW

**Comment by Devengel** [comment]
Hell, Github is hell. i think i solved it now

**Comment by Devengel** [comment]
fixes #64932

**Comment by TheShadowFerret** [comment]
> fixes #64932

This needs to be in the OP to automatically close the issue on merge.

**Comment by Devengel** [comment]
#64672 , done, thanks

**Comment by Maleclypse** [comment]
I’m looking online and a cursory search I only found specially made flashlights that would attack to a helmet rail. Is this a helmet rail system or what exactly is it that unmodified flashlights all will go right into it?

**Comment by Devengel** [comment]
image
image
image
when i think of the flashlight attachment i think of a clamp that you can adjust to fit flashlights, kept it at only a flashlight as i think heavy-duty ones are way too big

**Pull request merged**
