### PR TITLE
A few small changes to exodii guns

### PR DESCRIPTION
**Pull request by AdamChirnside**
Adds PA md 68 and Rubik variant to vehicle turret mount. Makes 68 actually reliable, clean up formatting somewhat

#### Summary
Balance "Exodii guns"

#### Purpose of change
The PA md. 68 was getting jammed on every shot, and despite being something like a machine gun, it could not be mounted to a vehicle.

#### Describe the solution
Removed the min_cycle_recoil line, as this is for making a gun unreliable with certain types of ammo, and there is only one type of 12.3ln ammo. Added PA md. 68 to turrets json. Also gave the 68 a semi-auto mode, but left the 71 as it is. Removed blackpowder fouling since these rifles can't use any blackpowder ammo.

#### Describe alternatives you've considered
Nothing comes to mind.

#### Testing
Spawned in one of each gun, installed a 68 into a turret and it fired successfully.

#### Additional context
Tilesets may want to add the new turret, or perhaps use an existing turret as a stand-in?

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I'm not sure a the 68 should be mountable on an existing vehicle turret. It's meant to be an assault rifle, just a rather large and heavy one.  Could you mount something like an m-16? If so, this should be mountable, if not, I think it's probably best left out.

**Comment by AdamChirnside** [comment]
> I'm not sure a the 68 should be mountable on an existing vehicle turret. It's meant to be an assault rifle, just a rather large and heavy one. Could you mount something like an m-16? If so, this should be mountable, if not, I think it's probably best left out.

A large and heavy assault rifle is fairly close to the definition of a light machine gun. It even fires a full-power rifle cartridge like a typical machine gun "should". Although it seems to be significantly smaller in profile/volume, its weight is close to the M249 and M240.

Really though, the only thing needed for mounting to a turret is some form of trunnions or a mounting point for a bipod/tripod, or else a very adaptable turret. If none of that is meant to be present by default on the 68, perhaps a welding job to make a mounting point? It's made of steel and aluminum so something like that should be possible.

**Comment by I-am-Erk** [comment]
It definitely would not have a mounti point compatible with anything on cdda earth.

**Comment by andrei8l** [comment]
While you're there maybe you can give them more sensible names? 

`PA md. 68 Battle Rifle` expands to `Assault Rifle Model 68 Battle Rifle` and AFAICT this thing doesn't qualify as either in our universe. It looks like an LMG so maybe rename it `M md. 68` or better `Exodii machine gun` (and keep the fluff vendor name only in the description).

Similarly, rename `PA md. 71 zombie hunting rifle` to `Exodii zombie hunting rifle` and keep **PM** md. 71 only in the fluff text.

These are nitpicks, I know...

**Comment by gkarfakis19** [comment]
> While you're there maybe you can give them more sensible names?
> 
> `PA md. 68 Battle Rifle` expands to `Assault Rifle Model 68 Battle Rifle` and AFAICT this thing doesn't qualify as either in our universe. It looks like an LMG so maybe rename it `M md. 68` or better `Exodii machine gun` (and keep the fluff vendor name only in the description).
> 
> Similarly, rename `PA md. 71 zombie hunting rifle` to `Exodii zombie hunting rifle` and keep `PA md. 71` only in the fluff text.
> 
> These are nitpicks, I know...

I very much prefer "realistic-ish" names such as `PA md. 71 zombie hunting rifle`, as it makes it feel as if there's depth in the lore behind the Exodii, while a bland name like `Exodii zombie hunting rifle` doesn't inspire the same sense of discovery. Imagine if the M4A1 was renamed to 'zombie hunting assault rifle' - it just doesn't sound immersive.

**Comment by andrei8l** [comment]
> I very much prefer "realistic-ish" names such as `PA md. 71 zombie hunting rifle`, as it makes it feel as if there's depth in the lore behind the Exodii, while a bland name like `Exodii zombie hunting rifle` doesn't inspire the same sense of discovery. Imagine if the M4A1 was renamed to 'zombie hunting assault rifle' - it just doesn't sound immersive.

M4A1 doesn't seem to be an abbreviation unlike `PA md.`. For me at least, "what's an Exodii?!" is a better driver for discovery than "why is this thing misnamed?". I suppose that only makes a difference if you happen to know what "PA md." means, in our universe at least... We can keep both names though for the "Show gun brand names" option (ie. default name "Exodii hunting rifle" and brand name "PM md. 71").

**Comment by I-am-Erk** [comment]
What is the argument for changing fire modes on the 68?

**Comment by AdamChirnside** [comment]
I just added a semi-auto mode, because I can't see why it wouldn't be there. The only guns that lack any kind of single-shot functionality are machine guns or submachine guns and this isn't supposed to be either.

**Pull request merged**
