### PR TITLE
Nerf 9mm ferals

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "9mm ferals are less deadly"

#### Purpose of change
9mm ferals are probably too deadly. They get perfect accuracy by virtue of being a monster even with their very low skills, and they are still using the default Beretta M9 the player can loot which is no longer standard practice for such enemies. Further they get full damage out of these weapons but they usually drop heavily damaged firearms which are much weaker, leading to a logical disconnect as monsters don't need to worry about durability.

#### Describe the solution
Ferals get a new handgun with 10x the dispersion (copying the same multiplier from the ar-15 ferals) and -4 damage to its bullets to represent the gun being in terrible condition as the feral stopped maintaining it and probably treats it very poorly leading to further damage. This is equivalent to "| ." durability if I understand the system correctly, which is the average (they drop randomly "\ .", "| ." and "| \\" guns) 

In addition, monsters do not have to aim and can fire in melee flawlessly, so I gave these ferals a minimum range of 2 like their rock throwing buddies. You can safely engage them in melee range without them dunking on you with their perfect instant aiming skills.
 

#### Describe alternatives you've considered
Address the underlying problem that causes monsters to be nearly perfectly accurate and need no time whatsoever to aim their shots.

### CODE REVIEW

**Comment by Amoebka** [comment]
Sooner or later someone will have to fix the NPC aiming code to fix stats not penalizing accuracy and aim not being thrown off when hit. Then all these bandaid PRs for all gun-using monters will have to be reverted back.

**Comment by liminalRoar** [comment]
Do they have infinite ammo? Because a finite supply is one way to somewhat balance ranged enemies or at least make them more realistic. 

Having them spawn with anywhere from half a mag to possibly 2-3, maybe even more fully loaded magazines, dropping whatever is left when they are dead, incentivizing quick kills or stealth.

**Comment by PatrikLundell** [comment]
In my view the first priority should be to fix monsters so they don't have perfect snap shot accuracy. If that's too hard, the second line of defense should be to tweak the weapons they get to emulate the poor accuracy they should have, ideally with a "comment" (as the JSON nutjob creator removed comment support) identifying these places to be adjusted when number 1 is finally taken care of. The alternative to work-around nerfing ranged monsters would be to remove them completely until the aiming issue has been solved.
It can be noted that a reduced bullet count to anything above 1 isn't a solution, as it takes very few bullets to kill a player who isn't wearing kinetic protection when running into one of these. You can't "quick kill" something down a corridor as you don't can't aim at it before being shot, and you're ability to snap shot anything at that distance is close to zero, and would result in a glancing blow anyway, and "stealth" doesn't work in most places: the best you can hope for is to use a corner where you're lucky enough to have visibility cause the monster to turn the corner and end up directly in front of the PC. Most of the time they come in view two tile away, and half of that time your line of fire goes through the wall.

**Comment by liminalRoar** [comment]
I do agree in general. I wasn't proposing limiting ammo is the solution to this problem. Their accuracy should be nerfed however feasible. But i do think it would be a nice addition for them to have a limited supply and then use a melee weapon as backup.

**Review by LyleSY — APPROVED** [review]
Love it until we have a fix to how monster aiming works

**Comment by LyleSY** [comment]
And these don't have infinite ammo, they have five bullets, but yes, that's more than enough to one shot the player

**Comment by LyleSY** [comment]
anoobindisguise, you've tested this?

**Comment by anoobindisguise** [comment]
> anoobindisguise, you've tested this?

Yes, I did test this. They miss about 33% of their shots at about 10 tiles away from what I've seen. Accuracy improves a lot as they get closer and they miss a lot from far away. They also cannot fire their guns in melee.

**Pull request merged**
