### PR TITLE
Restore support for running unit tests [WIP]

### PR DESCRIPTION
**Pull request by mugling**
A `WIP` collaboration with @codemime. See also #18425. Additional help would be welcomed

### CODE REVIEW

**Comment by mugling** [comment]
In particular if anyone could pull this branch and post their platform details and results

```
FreeBSD 10.3-RELEASE-p4
FreeBSD clang version 3.4.1

test cases:      34 |      29 passed |  5 failed
assertions: 1303174 | 1303136 passed | 38 failed
```

**Comment by codemime** [comment]
Unit tests in their current form have two serious flaws:
- since they share one world, they mutually affect each other (for example, try `"use_manhack"` test suite - it passes when it's run alone, but fails in a sequence of suites)
- since the world is randomly generated each time and doesn't accept any kind of `seed`, we can't rely even on isolated tests - they may occasionally fail, occasionally pass.

We need some kind of small copyable test world (ideally - whole game state), generated using a passed `seed`.

**Comment by mugling** [comment]
The second doesn't sound too difficult to solve (and could probably double as a developer test world). The first needs careful design to ensure unit tests clean up after themselves or we need to reload the world each time.

**Comment by codemime** [comment]
> or we need to reload the world each time.

This would be preferable. Even better: load the world one time and then copy it for each test suite. This guarantees isolated tests no matter what they do (as they may have / already have quite unpredictable side effects). Though, I doubt it would be an easy thing to do with out current architecture.

**Comment by mugling** [comment]
Going to merge as it's a trivial fix and we now have dependent branches (#18471).

@codemime can you post your output of the whole test suite following this PR

**Comment by codemime** [comment]
```
cata_test is a Catch v1.3.5 host application.
Run with -? for options

-------------------------------------------------------------------------------
on_load-sane-values
  Awake for 2 days, gaining hunger/thirst/fatigue
-------------------------------------------------------------------------------
npc_test.cpp:41
...............................................................................

npc_test.cpp:69: FAILED:
  CHECK( test_npc.get_hunger() >= five_min_ticks - margin )
with expansion:
  141 >= 566 (0x236)

npc_test.cpp:70: FAILED:
  CHECK( test_npc.get_thirst() >= five_min_ticks - margin )
with expansion:
  143 >= 566 (0x236)

-------------------------------------------------------------------------------
on_load-sane-values
  Sleeping for 6 hours, gaining hunger/thirst (not testing fatigue due to lack
  of effects processing)
-------------------------------------------------------------------------------
npc_test.cpp:41
...............................................................................

npc_test.cpp:93: FAILED:
  CHECK( test_npc.get_hunger() >= expected_change - margin )
with expansion:
  8 >= 26

npc_test.cpp:94: FAILED:
  CHECK( test_npc.get_thirst() >= expected_change - margin )
with expansion:
  6 >= 26

-------------------------------------------------------------------------------
on_load-similar-to-per-turn
  Awake for 6 hours, gaining hunger/thirst/fatigue
-------------------------------------------------------------------------------
npc_test.cpp:99
...............................................................................

npc_test.cpp:135: FAILED:
  CHECK( on_load_npc.get_thirst() >= iterated_npc.get_thirst() - margin )
with expansion:
  18 >= 23

-------------------------------------------------------------------------------
monster_speed_square
-------------------------------------------------------------------------------
monster_test.cpp:364
...............................................................................

monster_test.cpp:311: FAILED:
  CHECK( (vert_move / 10000.0) == Approx(1.0) )
with expansion:
  10.0 == Approx( 1.0 )

monster_test.cpp:313: FAILED:
  CHECK( (horiz_move / 10000.0) == Approx(1.0) )
with expansion:
  10.0 == Approx( 1.0 )

monster_test.cpp:315: FAILED:
  CHECK( (diag_move / (10000.0 * diagonal_multiplier)) == Approx(1.0).epsilon(0.01) )
with expansion:
  10.0 == Approx( 1.0 )

monster_test.cpp:232: FAILED:
  CHECK( (move_stats.avg() / (10000.0 * diagonal_multiplier)) == Approx(1.0).epsilon(0.02) )
with expansion:
  10.0 == Approx( 1.0 )
with messages:
  mon_pig (100,0,0)
  slope := 0
  move_stats.avg() := 100000
  1

monster_test.cpp:232: FAILED:
  CHECK( (move_stats.avg() / (10000.0 * diagonal_multiplier)) == Approx(1.0).epsilon(0.02) )
with expansion:
  10.0 == Approx( 1.0 )
with messages:
  mon_pig (0,100,0)
  slope := 0
  move_stats.avg() := 100000
  1

monster_test.cpp:232: FAILED:
  CHECK( (move_stats.avg() / (10000.0 * diagonal_multiplier)) == Approx(1.0).epsilon(0.02) )
with expansion:
  10.0 == Approx( 1.0 )
with messages:
  mon_pig (100,100,0)
  slope := 1
  move_stats.avg() := 100000
  1

monster_test.cpp:279: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.1) )
with expansion:
  10000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Dist: 10 moves: 10000

monster_test.cpp:279: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.1) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Dist: 30 moves: 3333

monster_test.cpp:279: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.1) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Dist: 50 moves: 2000

monster_test.cpp:284: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.03) )
with expansion:
  2444.33325f == Approx( 100.0 )
with message:
  Monster:mon_pig Slope: 0 moves: 2444.33 types: 96

monster_test.cpp:284: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.03) )
with expansion:
  5333.25f == Approx( 100.0 )
with message:
  Monster:mon_pig Slope: 1 moves: 5333.25 types: 16

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -294 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -281 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -260 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  6333.25f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -235 moves: 6333.25 types: 4 samples: 10000, 10000,
  10000, 10000, 10000, 3333, 3333, 3333, 3333, 3333, 2000, 2000, 2000, 2000,
  2000, 10000, 10000, 10000, 10000, 10000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -211 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -189 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -176 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -137 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -124 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -103 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  6333.25f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -78 moves: 6333.25 types: 4 samples: 10000, 10000,
  10000, 10000, 10000, 3333, 3333, 3333, 3333, 3333, 2000, 2000, 2000, 2000,
  2000, 10000, 10000, 10000, 10000, 10000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -54 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -32 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: -19 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 19 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 32 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 54 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  4333.25f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 78 moves: 4333.25 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 3333, 3333, 3333, 3333, 3333, 10000, 10000, 10000, 10000, 10000,
  2000, 2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 103 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 124 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 137 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 176 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 189 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 211 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  4333.25f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 235 moves: 4333.25 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 3333, 3333, 3333, 3333, 3333, 10000, 10000, 10000, 10000, 10000,
  2000, 2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 260 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  3333.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 281 moves: 3333 types: 4 samples: 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333, 3333,
  3333, 3333, 3333, 3333, 

monster_test.cpp:294: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.05) )
with expansion:
  2000.0f == Approx( 100.0 )
with message:
  Monster:mon_pig Angle: 294 moves: 2000 types: 4 samples: 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
  2000, 2000, 2000, 2000, 

-------------------------------------------------------------------------------
use_manhack
-------------------------------------------------------------------------------
iuse_test.cpp:69
...............................................................................

iuse_test.cpp:84: FAILED:
  REQUIRE( test_item_pos == (-2147483647 -1) )
with expansion:
  0 == -2147483648

-------------------------------------------------------------------------------
Player body temperatures converge on expected values.
  Nude target temperatures.
-------------------------------------------------------------------------------
player_test.cpp:66
...............................................................................

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  600 (0x258) > 1156 (0x484)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  2100 (0x834) > 2656 (0xa60)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  3600 (0xe10) > 4044 (0xfcc)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  4900 (0x1324) < 4677 (0x1245)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  6400 (0x1900) < 5455 (0x154f)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  7900 (0x1edc) < 6122 (0x17ea)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  9400 (0x24b8) < 6733 (0x1a4d)

-------------------------------------------------------------------------------
Player body temperatures converge on expected values.
  Lightly clothed target temperatures
-------------------------------------------------------------------------------
player_test.cpp:66
...............................................................................

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  600 (0x258) > 1178 (0x49a)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  2100 (0x834) > 2674 (0xa72)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  3600 (0xe10) > 4035 (0xfc3)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  4900 (0x1324) < 4801 (0x12c1)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  6400 (0x1900) < 5595 (0x15db)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  7900 (0x1edc) < 6292 (0x1894)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  9400 (0x24b8) < 6836 (0x1ab4)

-------------------------------------------------------------------------------
Player body temperatures converge on expected values.
  Heavily clothed target temperatures
-------------------------------------------------------------------------------
player_test.cpp:66
...............................................................................

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  600 (0x258) > 1156 (0x484)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  2100 (0x834) > 2531 (0x9e3)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  3600 (0xe10) > 4100 (0x1004)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  5100 (0x13ec) > 5400 (0x1518)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  6400 (0x1900) < 5923 (0x1723)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  7900 (0x1edc) < 6605 (0x19cd)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  9400 (0x24b8) < 7228 (0x1c3c)

-------------------------------------------------------------------------------
Player body temperatures converge on expected values.
  Arctic gear target temperatures
-------------------------------------------------------------------------------
player_test.cpp:66
...............................................................................

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  600 (0x258) > 1134 (0x46e)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  2100 (0x834) > 2622 (0xa3e)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  3600 (0xe10) > 3975 (0xf87)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  5100 (0x13ec) > 5389 (0x150d)

player_test.cpp:44: FAILED:
  CHECK( high > p->temp_cur[0] )
with expansion:
  6600 (0x19c8) > 6850 (0x1ac2)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  7900 (0x1edc) < 7567 (0x1d8f)

player_test.cpp:43: FAILED:
  CHECK( low < p->temp_cur[0] )
with expansion:
  9400 (0x24b8) < 8416 (0x20e0)

===============================================================================
test cases:      34 |      29 passed |  5 failed
assertions: 1303300 | 1303227 passed | 73 failed

Test world "North Evans" left for inspection.
```

**Pull request merged**
