### PR TITLE
New Isometric tileset, new 16x16 tileset, lots of additions to 32 and 24 ChestHole tilesets.

### PR DESCRIPTION
**Pull request by Chezzo**
I am really excited to share with you all my new Isometric tileset. Sparr created the isometric mode, and recently fixed the controls, and I am having so much fun playing in this mode, there is so much depth and it feels like a whole different game.

As well as my new 16x16 tileset (for those who think 24x24 is too big) and lots of new stuff for my 32x32   and  24x24 tilesets.

I added boulders, ladders, the new farm equipment, the new copper stuff, game watches, the new cockroaches, biter zombies, screecher zombies, and lots lots more.

### CODE REVIEW

**Comment by sparr** [comment]
The display name of the tileset should be shorter, so it fits in the options dialog.

**Comment by sparr** [comment]
Also, can we get a couple of screenshots here?

**Comment by Chezzo** [comment]
You are right about the name, I can fix it. 

Here is a screenshot (Open it in a new tab to view it in it's naked isometric glory:

Iso screenshot

I also post about it on the forums, and about how much YOU @sparr contributed in a huge way to how awesome my tileset is and I will be forever grateful. 

http://smf.cataclysmdda.com/index.php?topic=9587.msg261657#msg261657

Thanks for everything, @sparr!

**Comment by Lain-** [comment]
Very nice!

**Comment by chaosvolt** [comment]
I am sorely tempted to suggest an 8x8 tileset solely as a joke.

**Comment by sparr** [comment]
@chaosvolt why a joke? there are plenty of 8x8 tilesets for other games. CalcRogue (for the TI-89) has a 5x5 2-bit-greyscale tileset.

**Comment by chaosvolt** [comment]
Fine. 4x4 enough of a joke? XP

**Comment by kevingranade** [comment]
I switched to a 1x2 font at one point, the map was surprisingly readable.
(The menus, not so much)

**Comment by chaosvolt** [comment]
Catalcysm: 2-bit Days Ahead. :V

**Pull request merged**
