### PR TITLE
Pipe audit

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
So we all like pipes, yes? Ours were weird. Double the expected weight, for the record.

The last changes to pipe numbers I am aware of are #47825. And there's a source, too. This is good because it allowed me to look for a specific set of pipes for numbers (60cm, 28mm diameter, 1.2mm wall thickness). Now, I didn't find anything matching the wall thickness so instead went for 1.5mm, which is close enough (?) but the issue at hand was... weight. Even with 1.5mm thickness, which is MORE than what the old PR assumed, the weight came out at 600g, while ours were 2x+ of that. So here we are.

Since @RenechCDDA is dying to prove me wrong and that our pipes indeed should weigh over 1kg:
- Calculating two cylinders: first with 60cm height and 28mm diameter (369.45ml), second with 60cm and 25mm diameter, to remove wall thickness that is 1.5mm x 2 (294.52ml)
- Substract the second cylinder volume from the first: 369.45ml - 294.52ml = 74.93ml
- Multiply volume by the density of steel we assume as a material (8g/ml): 74.93ml * 8g/ml = 599.44g

#### Describe the solution
- Changed the weight of pipes and all pipe-based items (sharpened pipe, pipe maces, pipe spear, pipe staff, bundle of pipes, makeshift crowbar; **NOT PIPE FITTINGS!**)
- Changed the pre-apo price for the pipe to match the reference, changed the pre-apo price for the bundle of pipes to be 10x that instead of just 1 dollar
- Changed the lengths of some pipe-based weaponry to be *number of pipes used x 60cm* because not all applied to that (this lowers it for any affected, for the record)
- Changed the volume and weight of the makeshift crowbar to... actually make sense. I mean, look - it for some reason lost over 2/3 of its volume because it got hammered on the sides? Nah. Same with the weight. Also got ``FRAGILE_MELEE``
- Edited the pipe disassembly recipe to bring it up to speed

**DPS CHANGES:**
| NAME | PRE-AUDIT | POST-AUDIT |
|--------|--------|--------|
| Pipe | **30.40** | **30.08** |
| Sharpened Pipe | **60.39** | **59.61** |
| Basic Pipe Spear | **60.08** | **61.49** |
| Pipe Spear | **70.13** | ~~**69.52**~~ idk anymore I lost this absurd testing character, higher now to please the tests |
| Pipe Staff | **32.98** | **33.15** |
| Pipe Mace | **41.20** | **40.22** |
| Great Pipe Mace | **41.38** | **41.86** |
| Makeshift Crowbar | **40.68** | **32.03** |

^ These values are bullshit, by the way. They're not the expected DPS of these weapons. I have no idea why my test character gets this sort of insane DPS. And you know what? I won't question it. I don't need exact same DPS values as the tests, I just need to know how much I'm changing them in comparison.

#### Describe alternatives you've considered
I briefly considered obsoleting the makeshift crowbar altogether but it was rightfully pointed out to me the issue isn't its existence. The issue (if any) is how useful it is. And I don't wanna touch that. Scary

#### Additional context
1. Makeshift crowbar and sharpened pipe, despite using a single pipe, have a slightly lower weight with the assumption that some material got chipped off in the process of creating it
2. Some weaponry that used pipe fittings had their weight lowered to not use 100% of the weight of the pipe fittings - our pipe fittings weigh 0.5kg for some reason and you're definitely not using 0.5kg of pipe fittings to hold 3 pipes together
3. Wanna hear a fun fact? I did this to help me handle the weight gap in the recipe on #67047... and I made it worse...

### CODE REVIEW

**Comment by GuardianDll** [comment]
for pipe weight actual person, that made it 1.25 kilo is Erk, in #32218. No reasoning was provided

**Comment by Karol1223** [comment]
> for pipe weight actual person, that made it 1.25 kilo is Erk, in #32218. No reasoning was provided

I don't believe that's right. The pipe already weighed 1.25kg in that PR, Erk just moved it to a different file. Or am I reading it wrong?

**Comment by Aerin-of-the-Toast** [comment]
What's the new attack speeds for the pipe and the pipe weaponry? I'm a bit worried this will make the already strong pipe weapons into DPS powerhouses

**Comment by Karol1223** [comment]
> What's the new attack speeds for the pipe and the pipe weaponry? I'm a bit worried this will make the already strong pipe weapons into DPS powerhouses

I'll be real I was hoping they were in the DPS test so I could adjust them accordingly but now I'm kinda fucked. I'll have to manually compare them.

**Comment by GuardianDll** [comment]
> I don't believe that's right. The pipe already weighed 1.25kg in that PR, Erk just moved it to a different file. Or am I reading it wrong?

oops, my bad, actual pipe weight goes back to #15744, when it was adjusted to sane frame weight

**Comment by Karol1223** [comment]
> oops, my bad, actual pipe weight goes back to https://github.com/CleverRaven/Cataclysm-DDA/pull/15744, when it was adjusted to sane frame weight

I really hate that we use regular pipes as vehicle parts. Really complicates things, given that they had to have a weight adjustment solely for this reason and even in this PR I had to fight against the automated vehicle tests...

**Pull request merged**
