### PR TITLE
Add HWP 8x40 caseless configuration

### PR DESCRIPTION
**Pull request by MrSamu99**
#### Summary
Content "Add HWP 8x40 caseless configuration"

#### Purpose of change

Hub 01 uses a lot of high tech devices and equipment. I think they can have not only high tech guns but high tech ammo too. Also Rivtech-related updates seems to be very rare and this will slightly change that.

#### Describe the solution

This PR adds a new Hub project to create a HWP barrel for caseless ammo. The barrel is nearly the same as the 5.56 barrel except waterproofing (all caseless guns are waterproof, so this new barrel also makes HWP immune to water).

#### Describe alternatives you've considered

None

#### Testing

All is tested. Hub project works, gun shoots.

#### Additional context

None

### CODE REVIEW

**Comment by anoobindisguise** [comment]
IDK about this. Rivtech stuff is generally super proprietary right? Unclear if Hub01'd have access to their design specs. Might be better to do 7.62x39, 5.7x28, 4.6x30 or even just .300 AAC rather than Rivtech's rounds, tbh. It's also probably not super easy to convert a gun to caseless compared to swapping a caliber, so you might even have better luck using Rivtech's 5mm flechettes.

**Comment by TheShadowFerret** [comment]
Converting a case-using gun to use caseless ammo with no upgrade to its heat dispersion? *Cook-offs intensify* No

**Comment by andrei8l** [comment]
> Converting a case-using gun to use caseless ammo with no upgrade to its heat dispersion? _Cook-offs intensify_ No

The movement of the bolt cools the ignition chamber. The G11 had heat problems specifically because it had no bolt.

**Comment by Maleclypse** [comment]
Neither the HWP designer nor the Hub Administrator appear to want this addition to the HWP based on the conversations in discord. I dislike closing a first contribution attempt but leaving it open would be giving you false hope of this merging and possibly delay you finding a different first contribution.

**Comment by MrSamu99** [comment]
Okay. I didn't thought that it would be merged after some conversations

**Comment by Maleclypse** [comment]
> Okay. I didn't thought that it would be merged after some conversations

I understand. I hope you find something else you’d like to contribute and that we see you again.

**Comment by bombasticSlacks** [comment]
> IDK about this. Rivtech stuff is generally super proprietary right? Unclear if Hub01'd have access to their design specs. Might be better to do 7.62x39, 5.7x28, 4.6x30 or even just .300 AAC rather than Rivtech's rounds, tbh. It's also probably not super easy to convert a gun to caseless compared to swapping a caliber, so you might even have better luck using Rivtech's 5mm flechettes.

For anyone reading this 5.7 and 4.6 already exist.

**Pull request closed without merging**
