### PR TITLE
Stacks of money

### LINKED ISSUE #23136: Combine cash cards into a stack that displays their total value and number of cards.
Game version:
944cc2b
Operating system:
ALL
Tiles or curses:
ALL
Mods active:
NA
### Expected behavior
Cash cards merge into a single stack that displays the total value.
### Actual behavior
Cash cards each have an inventory entry, obscuring the number and value of cards as well as cluttering the inventory.
### Steps to reproduce the behavior
Get a bunch of cash cards.
Marvel at the spam.

Should be fairly simple, just update
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L497
to make cash cards stack, and update
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2380
to traverse the stack and print the total value.

### PR DESCRIPTION
**Pull request by Veraghin**
Duplicate of closed #23145

Cash cards now stack.
Also, this interacts nicely with atm's for example.
Translator friendly string comments included.
In the inventory view, you'd have:
cash card ($3.50)
or:
2 cash cards ($0.00)
10 cash cards ($234.55)
Where 10 is the total number of non-empty cash cards on you, and the number is the sum of all the cash on them.
Also, when dropping stuff, and you select x out of total y cards to be dropped,
you can see it under the items to be dropped list as
x cash cards ($total dollar amount on to-be-dropped cards) of ($sum of all cards)

Closes #23136

### CODE REVIEW

**Comment by BrettDong** [comment]
Now #24207 has been merged, so I think it's better to utilize the added `format_money` function for money formatting.

**Comment by Veraghin** [comment]
This should be up to date now and ready for merging.

**Comment by ZhilkinSerg** [comment]
Something is wrong with displayed values now:

image

image

image

**Comment by NickGrease** [comment]
Just curious on the status of this.

**Comment by ZhilkinSerg** [comment]
> Just curious on the status of this.

When viewing dropped stack of cash cards their total value is not displayed and random card charges is displayed instead.

**Pull request merged**
