### PR TITLE
Added metal and sandbag backstop to s_gun0.json gun range, and earplugs

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
IRL gun ranges near urban areas have something to stop overpenetrating bullets before they endanger passersby. This PR replaces the back wall of the gun range with a metal wall and adds a sandbag wall in front of it. Also added a locker full of hearing protection items.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I like this, but I think metal wall don't fit well here - imagine the horrible sound of bullets banging the metal. Maybe concrete or brick wall?

**Comment by BorkBorkGoesTheCode** [comment]
I'm probably going to go with reinforced concrete as a replacement for the metal walls. Might future-proof the map by adding sand floors underneath the backstop.

**Comment by BorkBorkGoesTheCode** [comment]
Replaced metal wall with reinforced concrete.

**Comment by BorkBorkGoesTheCode** [comment]
I might not be available to update these PRs during the next few months, so if anybody wants to add these later in a different PR, feel free.

**Pull request merged**
