### PR TITLE
Clean up make_iso.py script for UltiCa conversion

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Infrastructure "Clean up make_iso.py script for UltiCa conversion"

#### Purpose of change

To make the make_iso.py script more robust and user-friendly, and use it as a test bed for an isometric UltiCa.

#### Describe the solution

Fix various mechanical problems with the script to make it run (mostly) without errors

#### Describe alternatives you've considered

Still very much in progress. Would like to refactor and modularize this script and make it work with all our standard tilesets.

#### Testing

```
utilities/make_iso.py -f gfx/BrownLikeBears
utilities/make_iso.py -f gfx/UltimateCataclysmDemo
```

#### Additional context

Draft for now, just wanted to get it out there

### CODE REVIEW

**Comment by wapcaplet** [comment]
First working attempt at converting UltimateCataclysmDemo tiles:

image

**Comment by kevingranade** [comment]
Is there anything preventing this from being mergesble as-is?

**Comment by wapcaplet** [comment]
> Is there anything preventing this from being mergesble as-is?

@kevingranade Not really. I sat on it too long and got some merge conflicts with @int-ua (now resolved), but it's certainly working better than it used to. I'll take it out of WIP status.

**Comment by int-ua** [comment]
Is it worth converting `os.system` calls to `subprocess.Popen` at least to get rid of invoking shell?

**Comment by wapcaplet** [comment]
> Is it worth converting `os.system` calls to `subprocess.Popen` at least to get rid of invoking shell?

@int-ua Maybe; what is the benefit of doing it that way? (other than to move away from deprecated stuff)

**Comment by int-ua** [comment]
Realistically, maybe none, it was more of a question than a suggestion :)

**Pull request merged**
