### PR TITLE
Alcohol mixing for storage

### PR DESCRIPTION
**Pull request by Coolthulhu**
Two recipes for mixing alcohols with no regards for taste. One for weak drinks, one for strong ones.

The mixed alcoholic "drinks" combine the worst traits of weak and strong alcoholic drinks respectively: worst nutrition, quench and addiction potential. Fun and price even lower than that.

Strong mixed alcohol is usable in all the recipes that allow all strong alcohols. That is, fuel, disinfection and distillation to ethanol.

Weak one has no recipes, but relatively OK stats (except fun), meaning it can be poor man's boozeberry or a combined quench+painkiller.

Both are useful for freeing bottles and cans and for quick liquor store raids with just a jerrycan in hands. Strong one is also useful for combining stacks not in multiples of 7 to get another craft/bigger batch size.

Weak one can be crafted from any drink that has stack size 1 and ALCOHOL_WEAK use action.

Strong one can be crafted from any alcoholic drink that has stack size 5, 6 or 7, except moonshine. Moonshine is craft-only, has even worse stats than cheap wine and is the only drink with ALCOHOL_STRONG.

Some drinks are not included in either recipe due to being outliers. Those are:
- Fruit wine and dandelion wine - ALCOHOL_WEAK with stack size 7
- Boozeberry - strongly negative fun, more addicting than bum wine, would drag the minimum down
- All the mixed ALCOHOL drinks with stack size 1 or 2
- Imperial stout (stack size 1 ALCOHOL). Regular stout is ALCOHOL_WEAK and thus fine in weak alcohols
- Cheap wine is ALCOHOL with stack size 7, but recipes that call for it generally request 4 times more of it than of other drinks, as if it was as weak as fruit wine
- "Named" wines are ALCOHOL with stack size 5. They aren't allowed in most recipes that call for alcohol
- Strawberry surprise is ALCOHOL with stack size 6 that is not allowed in recipes

Kinda hard to classify some of them, as "alcohol effect" is not standardized. Rum/tequila/gin/vodka are equal to cheap wine, which is 2 times as strong as fruit wine, which is 3.5 times as strong as imperial stout, which is 2 times as strong as weak alcohols. The spread is much too wide for "medium alcohol" to encompass them all.

### CODE REVIEW

**Comment by Mshock777** [comment]
So you decided to make mixed drinks not flammable?

**Comment by Coolthulhu** [comment]
Not make, they were like that before. I just didn't include medium strength alcohols in the strong alcohol recipe that only takes the flammable alcohols.

**Comment by Mshock777** [comment]
Oh you rewrote whole flammability code when I wan't looking, sorry.

**Comment by Coolthulhu** [comment]
That was quite long ago...

**Pull request merged**
