### PR TITLE
cbms for NPCs: add BIONICs tab to player info window

### PR DESCRIPTION
**Pull request by mlangsdorf**
Add a new tab to the player info window, below TRAITS, which displays
bionic power level and any installed bionics.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Please provide a screenshot of how the new @-menu look like.

**Comment by mlangsdorf** [comment]
bionicsplayerinfo
100x30 window. The TRAITS window has been squashed to provide space for BIONICS.

bionicsplayerinfolarge
150x45 window. The TRAITS window has fully expanded into the available space.

**Comment by Night-Pryanik** [comment]
And what about some heavily-mutated characters like picrelated?

There is no free space at all below the TRAITS window.

**Comment by Jownky** [comment]
It could be placed next to speed tab maybe?

**Comment by mlangsdorf** [comment]
@Night-Pryanik : is that from my code? because this code sequence:
```
    if( ( bionics_win_size_y + trait_win_size_y + infooffsetybottom ) > maxy ) {
        // maximum space for either window if they're both the same size
        unsigned max_shared_y = ( maxy - infooffsetybottom ) / 2;
        // both are larger than the shared size
        if( std::min( bionics_win_size_y, trait_win_size_y ) < max_shared_y ) {
            bionics_win_size_y = max_shared_y;
            // trait window is less than the shared size, so give space to bionics
        } else if( trait_win_size_y < max_shared_y ) {
            bionics_win_size_y = maxy - infooffsetybottom - trait_win_size_y;
        }
        // fall through if bionics is larger
        trait_win_size_y = maxy - infooffsetybottom - bionics_win_size_y;
    }
```
exists because I added code that is supposed to share that y space if the combined size of the windows is too large, and it seems to work in my test case in the images I posted. In the first one, Tonza has 10 traits and that's too many to fit in the available space, so the traits window is cropped. In the second one, Tonza still has 10 traits (because it's the exact same save game, just different window size options) but the traits window is full size.

but hey, maybe I screwed something up.

**Comment by Night-Pryanik** [comment]
No, that screenshot is not from your code. So you mean that long traits list from my screenshot will be condensed to provide space for bionics? Could you please make the person with MANY traits and MANY bionics and provide a screenshot of how it look like?

**Comment by mlangsdorf** [comment]
cybertonzalarge
Cyber-Tonza on the big screen, with 10 traits and 8 CBMs.
cybertonzasmall2
Cyber-Tonza on the small screen. 5 traits displayed, 4 CBMs, and I've scrolled through the list.
cybertonzasmall
Scrolling all the way to bottom.

I did screw something up - the scroll logic was awful. Fixed I hope.

**Comment by Night-Pryanik** [comment]
I understand that you're trying to give us a way to look on what bionics NPCs have. But that `BIONICS` window kinda duplicates the existing Bionics menu. We can:
1) Add a way to (de)activate bionics on this `BIONICS` window, update it with information about (de)activation costs and bionic power drain per turn, and it becomes a full duplicate. Bionics menu could be removed altogether in this case.
2) Make this `BIONICS` window show only when examining NPCs. While examining we don't need any extra information, just a list of installed bionics and their description will suffice.
3) Rework the existing Bionics menu to work on NPCs too.

**Comment by mlangsdorf** [comment]
We could also:
4. Accept that C:DDA often duplicates information in the player info window in other windows: the stat summary is in the sidebar and encumbrance and warmth are repeated in the clothing sort window.

I mean, I can make it NPC-only by littering the code with is_npc() calls, but is it really a bad thing to have another, slightly easier way for players to get information about their installed CBMs? This doesn't obsolete the bionics menu, but it does give players a place to see all their installed CBMs at a glance (or a scroll).

**Comment by DracoGriffin** [comment]
I agree with @mlangsdorf . The way I see it, having condensed scrollable windows on the character screen is a much better way of giving all the information "at-a-glance", while still retaining the usefulness of the View Bionics menu (hotkey `p`) and View Mutations menu (hotkey `[`).

>But that BIONICS window kinda duplicates the existing Bionics menu. We can:

With this rationale, why even have the mutations listed instead of just traits (or at all) since it duplicates the existing Mutations menu?

mutationsmenu

**Comment by mlangsdorf** [comment]
I appreciate the feedback. I want to have this PR merged (or reviewed with specific fixes requested), since it fills a need and makes bionics and mutations have the same style of interface.

**Comment by ZhilkinSerg** [comment]
Looks good for the start and intended goal. We can always update if necessary later.

**Pull request merged**
