### PR TITLE
typified item.h + cpp

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Changed untyped coordinates in operations to typed ones. Focusing on item.h/cpp this time.
A by-catch was the discovery of an untyped bubble coordinate sent into an untyped absolute coordinate operation (map_field.cpp operation field_processor_fd_fire, where the bubble coordinate was sent into get_local_windpower). The bug fix was to convert the bubble coordinate to an absolute coordinate using the appropriate conversion rather than a cast.

#### Describe the solution
Change operations from using untyped coordinates to using typed ones and adjusting users accordingly.

#### Testing
Apart from the bug, which I don't know how to test, no functionality was changed. Thus the test is a general one.
Loaded save, walked up ramp, jumped into car, drove through hay bales, ran over zombie corpse with inventory, ran over turkey, smashed into stationary vehicle. Nothing odd seen.

#### Additional context
The bug is to use bubble coordinate when getting weather, which expects absolute coordinates. This means the wrong wind info was used when processing fires. Since this hasn't been detected before it's probably not very important, and there shouldn't be any tests (failing to) test this. Basically, fire would be fanned by winds taken from a different location, and so spread in the wrong direction, possibly with the wrong speed, if that's a factor.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Hi Patrik, there seem to be a bunch of conflicts.

**Comment by PatrikLundell** [comment]
They weren't there when I checked this morning...
I'll get to it.

**Comment by PatrikLundell** [comment]
It's happened again, vehicle stuff tests serial failures in an unrelated PR (General build matrix / Basic Build and Test (Clang 10, Ubuntu, Curses) (pull_request)).
Is there a way to repeat the failures under a debugger so they can be tracked down by somehow making use of the randomness seed printed in the error report ("1733050048")?

**Comment by kevingranade** [comment]
> Is there a way to repeat the failures under a debugger so they can be tracked down by somehow making use of the randomness seed printed in the error report ("1733050048")?

Sometimes you can run the tests with the exact same arguments and get the same outcome, but it's the seed for the whole rng so it's not super stable, a single operation being different will cascade to everything afterwards being different.

**Comment by PatrikLundell** [comment]
Thanks. How do I try to repeat it? Would the RNG seed be some kind of a command line parameter?

**Comment by kevingranade** [comment]
Yes though I don't recall what it is offhand, it does support cata_test --help to dump the cli options.

**Comment by PatrikLundell** [comment]
Failed to repeat the errors locally, but it was still worth a try, even though the chances were slim.

**Pull request merged**
