### PR TITLE
Update electronics.json line 143 Augmentative tech review

### PR DESCRIPTION
**Pull request by DamienRoyan**
#### Summary
None

#### Purpose of change

The book "Augmentative Tech Review" from line 142, describes "bionic systems", that "improve" peoples bodies. The Design doc says CDDA Earth prosthetics pre-Cataclysm, are no better than ours.
Our current level of prosthetics are nowhere near being an "improvement" to our fleshy bits. And one might wrongly infer that bionics are commercially available, based on the description of the book, since "Annual" publication suggests they've been around for quite a long time

#### Describe the solution

Changed description to describe people with disabilities regaining their life through advanced prosthetics. This should match up with current lore as well as our world.
I didn't change the name "Augmentative Tech Review", because that just seems like something media would do to create hype. The books description should make sure players understand it isn't linked to actual bionics in game.

#### Testing

Made changes and opened up game. Description was changed as expected. No errors on startup or reading the description.

### CODE REVIEW

**Comment by DamienRoyan** [comment]
> Spell checker encountered unrecognized words in the in-game text added in this pull request. See below for details.
> Click to expand
> 
>     * This annual publication covers the various ways in which people use technology to regain their lives.  There are a few in-depth and thoroughly illustrated articles on how people suffering from **disabilties** are benefiting from advanced prosthetics, though they tend to use too much jargon when explaining the technology behind it.
> 
> 
> This alert is automatically generated. You can simply disregard if this is inaccurate, or (optionally) you can also add the new words to `tools/spell_checker/dictionary.txt` so they will not trigger an alert next time.

Change has been made

**Comment by Qrox** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/59198#issuecomment-1181614108

The book still teaches CBM recipes in Aftershock so the description should be kept as the previous version in Aftershock.

**Comment by DamienRoyan** [comment]
> [#59198 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/59198#issuecomment-1181614108)
> 
> The book still teaches CBM recipes in Aftershock so the description should be kept as the previous version in Aftershock.

Hmm. Well.. While my change is designed to make sure the book does not clash with current main lore, "advanced prosthetics" can technically mean CBM in the scope of a game session where the player is expecting a futuristic world such as in AfterShock.

The change is made keeping in mind the main game. The issue you have highlighted is for when the player loads up Aftershock. 

A new player would not get misled into thinking they can probably find CBM's in hospitals or electronic stores. And as for the AfterShock player, the extra bit I added in the end "when explaining the technology behind it" would allow an AfterShock player with that context of gameplay to infer that this is indeed about CBM's that have been called "Advanced prosthetics" instead and how they're made.

I hope this suffices. Otherwise I'm open to suggestions of some other description to be made, which don't clash with current lore, which is my main concern.

**Comment by DamienRoyan** [comment]
What went wrong here. Why were some required tests skipped?

**Comment by Maleclypse** [comment]
It doesn't look like any required tests were skipped but there was a random failure and that stops all tests past it in case it's not a random failure.  I've kicked all the remaining tests.

**Pull request closed without merging**
