### PR TITLE
Take down the Halloween decorations

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
```SUMMARY: Interface "Take down the Halloween decorations"```

#### Purpose of change
Halloween is over now. Lets take down the decorations.
#### Describe the solution
Flip the halloween mode off.

#### Describe alternatives you've considered
Leaving halloween decorations up after Halloween _like some kind of savage_
More seriously, we should maybe have the game check the computer's current date and change the theme appropriately (if it's October, I guess), with an option to turn it off entirely in JSON.

### CODE REVIEW

**Comment by jbytheway** [comment]
Alas.  I had assumed this was set automatically based on date...

**Comment by kevingranade** [comment]
Alternately, we should IMMEDIATELY put up X-mas decorations

**Comment by narc0tiq** [comment]
Maybe Thanksgiving first? A zombie turkey?

**Comment by Rivet-the-Zombie** [comment]
>we should maybe have the game check the computer's current date and change the theme appropriately (if it's October, I guess), with an option to turn it off entirely in JSON.

This.

**Pull request merged**
