### PR TITLE
Seriously.. WHERE IS EVERYONE!??!

### PR DESCRIPTION
**Pull request by TiberianErin**
#### Summary
Interface "Added an option for NPCs to be even rarer than the rarest option."

#### Purpose of change
``To make NPC spawns even RARER``

#### Describe the solution
``Added a new level of rarity in 'data/core/world_option_sliders.json', named "Seriously.. Where is everyone?" that has double spawn time as the current rarest spawn``

#### Describe alternatives you've considered
``An alternate approach is opening advanced settings and manually changing the NPC spawn time to something higher than 12.``

#### Testing
``I tested the slider, and it appears to work as intended. The new option does exist on the slider, does not override anything and does indeed set the npc option to 24. I tested this by creating a new world and cranking the slider all the way down.``

#### Additional context
oroof of functionality
Here is an image of the new slider option.

### CODE REVIEW

**Comment by Qrox** [comment]
That question might make less sense in CDDA because if you find no living human beings, then presumably everyone is now wandering on the streets, eyes oozing black goo.

**Comment by TiberianErin** [comment]
how do I fix "Validate PR" acting strange

**Comment by NetSysFire** [comment]
Because you did not use a proper summary. See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#all-prs-should-have-a-summary-section-with-one-line

**Comment by esotericist** [comment]
considering we already have players asking that on the *default* settings, due to how tricky it can be to actually locate the npcs once they've spawned (and the distinct lack of notification that they have spawned), i'm questioning the utility of adding this to the slider.

this is the kind of thing where if someone really wants this, they need to know what they're doing, and that's a good threshold for when someone should be doing something beyond the slider.

**Comment by kevingranade** [comment]
Expanding on what esoteristics is saying here. The sliders are intended to present a "norma"l range of behavior for the game where everything more or less works as intended. With the NPC rarity setting at some point you're going to get so close to 0 that it is practically 0 and that is very much not the intended play style of the game.

Does this PR cross that line? I don't know and the PR doesn't present any kind of argument for whether it crosses that line, so it's hard to evaluate.

**Comment by Fris0uman** [comment]
closing as stale

**Pull request closed without merging**
