### PR TITLE
Rework NPC shop restocking

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
None

#### Purpose of change
NPC traders restock their shop at their feet
NPC traders pile items forever
Traded items never disappear

Alternative, or supplemental, solution to EOC-based restocking such as https://github.com/CleverRaven/Cataclysm-DDA/pull/56677

Fixes: https://github.com/CleverRaven/Cataclysm-DDA/issues/54776

#### Describe the solution
Restock the shop and place traded items in defined loot zones owned by the NPC trader
Place a fallback unsorted zone if one is not defined at mapgen
Consume items from NPC's loot zones proportionally to time (in days) elapsed since last restock

<details>
<summary> TODO (finished)</summary>

- [x] fix mapgen zone rotation
- [x] better item consumption function that considers item contents
- [x] obsolete EOC-based restocking
- [x] obsolete Exodii's chunk-based restocking
</details>

#### Describe alternatives you've considered
1. Heuristic approach that places items in nearby furniture. Less robust and flexible; some traders might want to drop their items directly into a lava pit
2. Continue to use EOCs. IMO this spreads trader definitions across too many files and systems with different syntax.

#### Testing
<details>
<summary>use this zone manager patch to make things easier</summary>

```diff
diff --git a/src/game.cpp b/src/game.cpp
index 2c9cfd9cf5..986130ed71 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -6242,7 +6242,7 @@ void game::zones_manager()
             zones = mgr.get_zones();
         } else {
             const tripoint_abs_ms u_abs_pos = u.get_location();
-            for( zone_manager::ref_zone_data &ref : mgr.get_zones() ) {
+            for( zone_manager::ref_zone_data &ref : mgr.get_zones( faction_id( "exodii" ) ) ) {
                 const tripoint_abs_ms &zone_abs_pos = ref.get().get_center_point();
                 if( u_abs_pos.z() == zone_abs_pos.z() &&
                     rl_dist( u_abs_pos, zone_abs_pos ) <= 50 ) {
```

replace `exodii` with the faction you're testing
</details>

1. Spawn an `isolated_road` or an `evac_center` or an `exodii_base` overmap special in every possible orientation
2. Trade with the NPC trader and confirm that:
2.a. Trade list shows items from nearby furniture
2.b. Traded items get placed in nearby furniture in the appropriate zones
2.c. Traded items are evenly distributed in the destination zones (only relevant for `isolated_road`)
3. Advance time one year
4. Open the trade UI again and confirm that items were consumed from nearby furniture

Known issues:
~- Traders spawned before the patch are unable to sell their old items if they're farther than 1 tile away.~

#### Additional context
This approach has exposed a few bugs in the zone manager and the code part of this PR has grown larger than I would have liked. I think it should still be just about possible to review, but I can split it up if absolutely needed.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
The isolated artisans have seperate items on seperate shelves which is a feature I would like to not lose.

**Comment by andrei8l** [comment]
I've added preliminary mapgen support for custom loot zones so you can fine-tune sorting like this
```
"place_zones": [
  { "type": "LOOT_CUSTOM", "faction": "exodii", "x": [ 2, 2 ], "y": [ 1, 1 ], "filter": "candy" }
],
```

Exodii are pretty tricky and I probably won't change them in this PR. I think dseguin added all the necessary code bits back in https://github.com/CleverRaven/Cataclysm-DDA/pull/52617 though.

**Comment by andrei8l** [comment]
@bombasticSlacks I've added a new zone type, `LOOT_ITEM_GROUP`, which should address your sorting concern (https://github.com/CleverRaven/Cataclysm-DDA/pull/56720/commits/d6fde3fd0baa6c2bf99ba8187828c977352d56a0 for the json bits). Let me know if there are other issues.

**Comment by haveric** [comment]
The Tacoma PR mention is just a reminder for me to implement this for a couple NPCs once this is merged in.

**Comment by esotericist** [comment]
oh, this looks amazing. i'm so glad to see forward progress on this after so long, and i'm especially glad you're taking the zone approach; the oc trick slacks used was super clever, but i think this better fits our design patterns.

i wonder if it'll be feasible to mitigate the issue with pre-existing traders in a followup, somehow, so that players moving from 0.F to 0.G will get a smoother experience.

**Comment by esotericist** [comment]
thanks so very much for the prompt response! i'm not quite qualified to review the code, but i'll try to do some testing in the coming days to ease things for other members of the team.

**Comment by I-am-Erk** [comment]
The consensus from my team of smart Devs is "the code looks okay probably" and we all really want this so I'm going to put it in game and if something explodes, well glue it back together.

**Comment by andrei8l** [comment]
Thanks for merging!

**Pull request merged**
