### PR TITLE
Add fitover rollerblades everywhere

### PR DESCRIPTION
**Pull request by tornikeo**
#### Summary
Content "Add fit-over rollerblades"

#### Purpose of change

Add this to the game

image

#### Describe the solution

Adding ^ That to the game. Almost everything that has rollerblades also has fitover version there (but it's around 25% as common). 

Oh yeah, it can be worn over other rigid or non-rigid footwear (Say, rollerblades + RM13 armor, although foot encumb. Will likely be horrifyingly large)

#### Describe alternatives you've considered

Just doing meth and running really fast.

#### Testing

Wore this with RM13. Encumb is high, but that's the price for being **FANCY** as hell.

image

Also, idk, if we should disallow wearing this on bare feet. I think, given the image above, it should be possible to wear, but not very comfortable. @fairyarmadillo  what do ya think?

#### Additional context

Related issue #71563

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Are they really that common? I've never seen these in my life, 25% seems like a lot.

**Comment by Procyonae** [comment]
As an aside all the roller footwear should really be in it's own item group and that group be added to other groups to save them having individual weights everywhere

**Comment by tornikeo** [comment]
@fairyarmadillo fair enough. Will adjust proba weights accordingly. Will aim for 1 overfit rb per 20 regular rb.

@Procyonae That's reasonable. I'll see that's doable somehow. I don't think we have that group right now, do we?

**Comment by Procyonae** [comment]
> @Procyonae That's reasonable. I'll see that's doable somehow. I don't think we have that group right now, do we?

I doubt it if you didn't find it while searching where to add these

**Comment by fairyarmadillo** [comment]
A definite problem with this implementation is that you can wear them barefoot and they won't cause any discomfort. They'll even get rid of your barefoot penalty. That's shouldn't be possible. I think getting rid of the cotton on the soles will help a bit, but I think you'd be liable to hurt your toes trying to use these without proper shoes.

They're also using the ROLLER_INLINE flag, which means they're as fast as the fastest possible skates. That doesn't seem appropriate to me - reading reviews, I'm finding a lot from people who don't have good things to say about the product.

**Comment by Maleclypse** [comment]
> A definite problem with this implementation is that you can wear them barefoot and they won't cause any discomfort. They'll even get rid of your barefoot penalty. That shouldn't be possible. I think getting rid of the cotton on the soles will help a bit, but I think you'd be liable to hurt your toes trying to use these without proper shoes.
> 
> They're also using the ROLLER_INLINE flag, which means they're as fast as the fastest possible skates. That doesn't seem appropriate to me - reading reviews, I'm finding a lot from people who don't have good things to say about the product. They're obviously inline, and that's used for some balance code, so maybe cranking up the foot encumbrance to 40 or so would do the job by reducing the total speed to below that of a proper pair of rollerblades, but still higher than baseline. That would put a fitted pair a bit below rubber boots and would definitely be usable with shoes.

These changes make sense. Ping me once they’ve been put in.

**Pull request closed without merging**
