### PR TITLE
Adds a new drink to Crazy Cataclysm

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
```SUMMARY: Mods "You can now make the perfect drink to go with your birthday dinner to yourself in Crazy Cataclysm."```

#### Purpose of change
Crazy Cataclysm can always use more fun stuff to have.

#### Describe the solution
Adds a new drink to Crazy Cataclysm called bone apple tea, made from a bone, an apple, and some water. It's healthy, and rich in vitamin C and calcium.

#### Describe alternatives you've considered
Not adding bone apple tea to Crazy Cataclysm.

#### Additional context
https://knowyourmeme.com/memes/bone-apple-tea

### CODE REVIEW

**Comment by kevingranade** [comment]
I'll take the alternative thanks.

**Comment by Ilysen** [comment]
...why?

**Comment by AMurkin** [comment]
Probably you can use a calcium_tablet instead.

**Comment by Photoloss** [comment]
@Ilysen closure of this PR aside why would you add a positive "fun" value when even the meme page you linked states `often used sarcastically to caption photographs of unappetizing food`?

**Comment by Ilysen** [comment]
I feel like that would be a question to answer when the pull request *doesn't* get instantly closed.

**Pull request closed without merging**
