### PR TITLE
Prune obsolete entities from before 0.F

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
We have obsoleted entries still around from pre-0.F, no need to carry them around any more.

#### Describe the solution
Deleted the old entries based on some history analysis.
Ran tests and then worked around issues caused by the supposedly obsolete entries still being in use or re-added the entries.

#### Testing
Verified the game still loads and tests run.

#### Additional context
I was able to largely automate this with a horrific bash pipeline:
git blame data/json/recipes/recipe_obsolete.json | grep "\"id\":\|\"abstract\":\|\"result\":\|\"name\::" | grep -f <(comm -13 <(git log 0.F.. | grep "^commit " | cut -d ' ' -f 2 | cut -c -11 | sort -u) <(git blame data/json/recipes/recipe_obsolete.json | cut -c -11 | sort -u)) | cut -d ":" -f 4

This extracts the list of commits that have occurred since 0.F and the list of commits in the target file (blame) and diffs them to derive the list of commits that occurred *before* 0.F from the blame, then uses that list to filter the entries from the target file, rendering a list of entity ids that were committed before 0.F

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Mods-([slow] ~crafting_skill_gain)=> (continued from above) ERROR : src/iuse_actor.cpp:338 [virtual void iuse_transform::finalize(const itype_id &)] Invalid transform target: toolbox

**Comment by kevingranade** [comment]
> Delete old obsolete file to drop support for that version.

As occurred here, many entries were still in use or entangled with code somehow, simply deleting the file is unlikely to work. Also, people aren't necessarally going to know which version their changes are going to land in, so that scheme isn't as low overhead as you might think.

I'm not against somewhat better organization for these files, consolidating them all into one directory would probably be an improvement.

**Comment by actual-nh** [comment]
> There are also bunch of `"looks-like` that refer to obsolete items.

Copying symbols and symbol colors should not be problematic. Are tilesets including tiles for these? In some cases, the obsolete items may themselves have looks-like, although it's possible a tileset would have a tile for the obsolete item even if it had a looks-like. Transiting any such in @I-am-Erk's tilesets should not be difficult (@Fris0uman?), and other tileset maintainers should be notified via the dev and tileset discords at least.

**Comment by kevingranade** [comment]
> Invalid transform target: toolbox

Took a minute to figure out, this was a magiclysm item that as it turns out is also obsolete.

**Comment by kevingranade** [comment]
> Also you missed this test

Actually no, the mres were not obsoleted before 0.F so I didn't remove them though I can certainly remove the test since it's obsoleted.

**Comment by kevingranade** [comment]
> Though it appears you didn't delete tool_rdx_charge in this pull. Only its active variant. Coincidence from the used method?

This was a coincidence, I needed to re-add tool_rdx_charge because a workshop recipe was using it and I didn't ant to dig into that too much.

**Comment by kevingranade** [comment]
I was curious about the extent of the looks_like problem, so did a quick search:
find data -type f | xargs grep looks_like | grep -f <(git show | grep "    \"id\":" | cut -d '"' -f 4)
(git show is outputting the HEAD commit diff, i.e. this PR)
Looks like there are only 32 collisions, so I'll do something about those in this PR.

**Comment by kevingranade** [comment]
Eliminated looks_like references to removed entities, replaced with other references where I could find them, and just removed a few.

**Pull request merged**
