### PR TITLE
Improved armor sorting ui

### LINKED ISSUE #23425: Better display of 'extra' encumbrance
You can have additional encumbrance due to use of multiple items in the same 'layer' per part.

The game does a piss poor job of explaining _where exactly_ this extra encumbrance comes from.
There is the `[..]+123` part in the armor layering window per body part, but you're left to poke around on your own to find out _which items exactly_ cause the conflicts.

So... I think this can accommodate some improvement :grin:

Since not everybody is playing in 4K I think using additional screen space is questionable. I've put together a prototype of 85% of what I think could be a usefull solution.

Instead of a plain

image

it colorizes each armor pieces Storage or Encumbrance values to indicate which layer it belongs to. 

image

Multiple items with the same color per body part are a problem.

What I have no fricken clue how to do (and what would make this 100% functional in my mind) is how to calculate the additional encumbrance penalty by layer, so we could get something like

image
[Completely mocked those numbers in]

A quick glance at `character.cpp` and it's `encumbrance` related functions show no obvious way of getting those values (apart from duplicating some code in there, but I'm a firm believer in DRY so - not going to start here).

---

I've put up a prototype at https://github.com/DoctorVanGogh/Cataclysm-DDA/commit/dcf9c3a7326d4574343e2ed1721e779b8070024a

What's missing is the per layer calculated and colorized penalties to be inserted [here](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/armor_layers.cpp#L420).

Obviously the [colors picked](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/armor_layers.cpp#L80-L98) are completely arbitrary (though I think it'd be a good idea to **not** use colors from the 'health' spectrum). Also - maybe the whole coloring stick deserves to be moved as a member function to `item.h/.cpp` similar to [`item::damage_color()`](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/item.cpp#L3347-L3371).

Maybe coloring the **background** of the armor item lines would work better?

Also... My C++ is ... not up to par. I'm sure I've forgotten or added a `const`too much somewhere in there..

### PR DESCRIPTION
**Pull request by DoctorVanGogh**
This is my solution to #23425:

It turns 
image
into
image

Includes the following changes to the existing armor sorting ui:
- Uses _(colored) damage symbol + item type name_ instead of simply _colorized item type_ for each item. As someone else pointed out:
   > Note: don't rely on color to convey meaning. There's a lot of color blind folks in the world.
- Use same line highlighting scheme for selected armor piece as in other menus (white on blue)
- **Every armor piece also has the _layer_ it is worn on displayed (as a one character colored symbol, configurable via json - see PR #23670)**
- (Re)uses the default item details in the center pane. This removes duplication and potential non localized texts for the different displays.
  Even has scrolling support 😁 
- Tweaked the "Encumbrance & Warmth" display to use a highlighting color scheme in line with the item info display for body parts (Entries for "Covers: X, Y, Z" are _blue_.) [_Default display in character details is unchanged_]
- Colorizes categories (body parts) the same way as intentory/item location headers in _magenta/brown_.
- **Adds a detailed 'extra encumbrance' breakdown by layer to each body part (where applicable)**.
  This makes it easy to track down extra layer penalties.
- Several highlighting gimmicks:
  - Currently selected item is highlighted in each body part.
  - If currently selected item incurs a layering penalty on any body part then that penalty is highlighted.
  - If sorting only a particular body part, highlights that part in the armor by body part breakdown
- Nice truncation (...) of overlong item names

---

This builds on (and includes/merges PRs #23520 , #23669 & #23670). 

Closes #23425 once merged.

---

Potential additional features & changes not currently implemented:
- Highlight _conflicting_ armor pieces which are on the same layer on any body part as the current one.
- Maybe improve scrolling for the center pane. Currently the encumbrance & warmth block wastes several empty lines of space and doesn't support scrolling. Although this is only really an issue in minimal size displays.
- Shift layer symbol display per item around. Maybe to the _right_ side of each line, so the lines look a bit more balanced? One symbol on the left, one on the right? But then that'd impact the right alligned value column...
- (Re)use the item layer symbols in item info displays? Not just write `Layer: Foo` but do `Layer: [Symbol] Foo`

### CODE REVIEW

**Comment by Leland** [comment]
39678870-2ceab878-5195-11e8-947c-5fbb4b0254da

I didn't read any of your PR description. I'm looking at this for the first time. Here are my notes as a new user using this interface:

* I don't know what the W, B, U, etc. letters are to the left of the items, and I don't have a way to learn what they are.

    Additionally, no idea what the various colors are supposed to represent. Green and Red are used in the interface to traditionally mean "good" and "bad," but Teal and Blue don't have traditional meanings. I'm perplexed.
* Seems like a lot of duplicate info in the right and left columns. Is representing storage complex enough to warrant the first 1/3 of the screen? For that matter, do we need that info on the Sort Armor screen at all?
* Not sure what "W" and "B" mean in the right column. They clearly seem to correspond to the W and B values in the items below, but why aren't U, R, or O totals shown as well?
* The titles "Storage" and "Encumbrance" could stand to be more noticeable. They're the way users learn how to interpret values of the items underneath. Perhaps make them white?
* Why is the "Encumbrance and Warmth" header indented in the middle column? It doesn't appear to be a subset of the info above it.

**Comment by Leland** [comment]
> Well - hi @Leland: TL;DR: RTFM/PR description 😉

I most certainly did, after I made the comment. Your PR description is comprehensive and well laid out. I've been following your notes on other PRs as well. That being said, CDDA users won't have those notes. UI/UX reviews are perhaps most valuable when going in blind.

> The W, B, U are the (current) symbol for the layer the item is worn on. It's arbitrarily the first letter of the underlying code enum representing this: "UNDERWEAR", "REGULAR_LAYER", "WAIST_LAYER", "OUTER_LAYER", "BELTED_LAYER".

I guess the concern with this is that those enmus aren't printed in full in the UI. Instead they correspond to these "porcelain" strings:

https://github.com/CleverRaven/Cataclysm-DDA/blob/a438fee10466a4201625cb685a2755210539e229/src/item.cpp#L1315-L1324

It looks like the only mismatches are that B = "Strapped" and R = "Normal." I think otherwise users might be able to gather what the letters correspond to based on what's shown in the middle column.

> If you eliminate the 'all' display from the left and only show stuff per body part, how are you then allowing shifting a piece up/down if it also covers another body part than the one you've currently selected and you want to move it even further up or down because of other armor worn there.
>
> I think the whole armor/layer systems needs a refactor or two, but this PR doesn't aim to do this

That is indeed a hairy problem, and I can see what you're saying.

> Well, highlighting would be easy, but I'd keep it similar to the weight/volume headers in the advanced inventory. And I think those are non highlighted too.

> It's indented because that particular piece of code already did that and I didn't touch it 

Yup, fair enough. I'll see about working on those in a future PR.

**Comment by DoctorVanGogh** [comment]
You know what... You're right. _If_ those symbols get implemented they need to be more than a gimmick on a single screen.
So I'll 
- Change them to some locale agnostic symbols (Because even if you pick the fist letter of those porcelain strings, there is no guarantee things will still align in a localized version). How about:

  | Layer | Symbol | Label |
  | :- | :-: | -: |
  | `UNDERWEAR` | `\|` | Close to skin |
  | `REGULAR_LAYER` | `o` | Normal |
  | `OUTER_LAYER` | `^` | Outer |
  | `WAIST_LAYER` | `-` | Waist |
  | `BELTED_LAYER` | `+` | Strapped |

- I'll edit the fragment on the info display for each item to _include_ that symbol next to the porcelain string
  ```c++
  if( has_flag( "SKINTIGHT" ) ) { 
    temp1 << _( "<stat>Close to skin</stat>. " ) << " [" << clothing_layer::get(item->layer())->symbol() << "]"; 
   ```
  That should create the obvious association for the user if the symbol appears on it's own.

**Comment by Night-Pryanik** [comment]
There is always a probability that some abbreviations might be identical for different layers in some languages.

**Comment by DoctorVanGogh** [comment]
Well... I honestly can't say if this is better or worse than the letters:

image

The repetition and inclusion in the info dialog I like though...

---

As for similar latter in different languages: If I localize things I tend to not assume to only have to put out a Spanish and a Portuguese version. More likely Chinese, Russian & Arabic :grin:

**Comment by Night-Pryanik** [comment]
Maybe use numbers? 1 is for Close to skin, 2 is normal, and so on.

**Comment by DoctorVanGogh** [comment]
Completely different layout idea: Has anybody ever experimented with a layout like this?

```
+----------------------+-----+-------------------------------------------+
|                      |     |   |Torso       Mouth       L. Leg         |
|       Name           |Stor.|Enc|    Head        Arms        R.Leg      |
|                      |     |   |        Eyes        Hands       Feet   |
+------------------------------------+---+---+---+---+---+---+---+---+---+
| || Thingy of Foo   o |25,00| 12| x |   |   |   | x |   | x | x |   |   |
| || Bar Boots         | 0,00|  7|   |   |   |   |   |   |   |   | x |   |
| \. Raincoat        ^ | 0,00| 20| x | x |   |   | x |   | x | x |   |   |
| |\ Vest            o |10,00|  8| 8 |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
|                      |     |   |   |   |   |   |   |   |   |   |   |   |
+----------------------+-----+---+---+---+---+---+---+---+---+---+---+---+
| Encumbrance                      32  20          32      32  32   7    |
| Penalty                           8                                    |
+------------------------------------------------------------------------+
```

**Comment by Night-Pryanik** [comment]
I'd like to look at this layout as ingame.

**Comment by OzoneH3** [comment]
@DoctorVanGogh Thats pretty much what I did in safemode_ui. ```enum Columns``` ```std::map<int, int> column_pos``` and ```draw_column()```

**Comment by Rivet-the-Zombie** [comment]
Anything that makes information more accessible to us colorblind players is good.

**Comment by ZhilkinSerg** [comment]
Marking as `Stalled`, but feel free to resolve conflicts and reopen.

**Pull request closed without merging**
