### PR TITLE
Astyle campaign, the return.

### LINKED ISSUE #14565: Bindist archives contain unnecessary file
Archives available via http://dev.narc.ro/cataclysm/jenkins-latest/ contain file ```astyled_whitelist``` which is not targeted to the end-users, so it should be excluded from the further deliveries.

### PR DESCRIPTION
**Pull request by kevingranade**
nom nom nom
fixes #14565

### CODE REVIEW

**Comment by illi-kun** [comment]
I guess that file 'astyled_whitelist' will be presented in the repository on the permanent basis so it's better to move it to another location from 'data' folder (see #14565). Sorry for semi-related note, just want to bring your attention to that.

**Comment by kevingranade** [comment]
How about in the doc folder? It doesn't really make sense anywhere, but I don't want to make a new folder just for one file.

**Comment by illi-kun** [comment]
What do you think about these candidates: 'tests', 'tools' or even root directory?

**Comment by narc0tiq** [comment]
I could even consider it being sufficiently closely related to the source
to put it in the 'src' directory.

**Comment by kevingranade** [comment]
I don't like a random config file being mixed in with the source (either src/ or test/), it could go in the root I guess.
Mostly I just don't want to waste time worrying about it.

**Comment by kevingranade** [comment]
If people don't start merging these faster we're literally never going to have well styled code.

**Pull request closed without merging**
