### PR TITLE
Remove Mutagen Catalyst

### LINKED ISSUE #70398: Remove Mutagenic Catalyst
### Is your feature request related to a problem? Please describe.

I (sort of) understand why we split primer and catalyst as vitamins, but after watching people be constantly confused by our present system over on reddit and elsewhere, I have a question - why is catalyst its own item? All I can guess is that it's a legacy from back when mutagen used to work differently, but untyped mutagen was practically useless even back then. Now it's actively detrimental to the play experience and there is no reliable way for us to communicate this to the player that doesn't totally break immersion by feeding them information their character would have no way of knowing. Even worse, we've done exactly that, and it clearly isn't working.

So we're spending a lot to have catalyst, but unless I'm mistaken, we aren't really getting anything for it.

### Solution you would like.

Unless there's some reason I'm not understanding why it absolutely has to be this way, why don't we just rename primer to something like infusion (a common term for injectable drugs) and put a bunch of catalyst vitamins in it, then obsolete the catalyst itself, or perhaps make it some optional thing that could be crafted if there's still some edge case use for it? It would be pretty easy to implement and would lead to a lot less confusion for players.

There are a ton of other problems with the current implementation, but this stands out as a big one to me.

edit: Per the comments, it sounds like the way to go is to do away with catalyst as a vitamin and combine its function with primer. This will be slightly trickier than simply obsoleting the item, but doesn't sound terribly complicated.

### Describe alternatives you have considered.

I would just do this myself but I wanted to ask whether there was a good reason not to first.

### Additional context

image

This was just a cursory search, but I see questions like this popping up once a week, and the sense I get is that a lot of people don't even want to engage with the system because it's obscure and confusing in an out-of-character way. I don't consider this ideal.

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Balance "Remove Mutagen Catalyst"

#### Purpose of change

Fixes #70398 

As detailed in #70398 (please read this issue before commenting), there isn't really a reason for catalyst to exist as a distinct object or vitamin type. It creates massive amounts of confusion, needlessly complicates what is already an inaccessible mechanic, demands a lot of micromanagement, adds useless cruft to what should be high-value loot rewards, deters people from engaging with the system, and allows players to inject themselves with liquid blob for free stat bonuses that last for days and have no risks or downsides.

#### Describe the solution

THIS IS NOT A REVERSION
- The primary change in this PR is so that players only have to take one drug to mutate instead of two. It still takes the same amount of time, has the same risks and the same chances for things to go the way you want.

CATALYST IS GONE
- We are back to drinking mutagen or injecting serum (now called "infusion" to avoid confusion with I-am-Erk's idea for temporary stat-boosting serums). Mutagen is a low concentration form which is easier to craft. Infusion is more potent and less toxic. This incentivizes making primer, but prevents mutagen from being useless
- Untyped mutagen/infusion are back. They work as they once did, giving mutations from random categories instead of specific ones. Note that this is different from "mutagenic slurry" which was just giving you a small dose of every primer.
- Catalyst in existing saves will become untyped infusion, slurry will become untyped mutagen
- The existing catalyst vitamin is likewise changed to untyped mutagen

PRIMER IS GONE
- If you want to turn into a bird, you drink bird mutagen or inject bird infusion. No faffing around with other chemicals, no waiting for different vitamins to decay. All existing primer will become typed infusion. If you would like to stop mutating, you can take chelator as before
- On the technical side of things, what this change does is obsolete the Catalyst EOC and add suffer::from_mutagen(), which simply checks for the MUTAGEN_EFFECT flag. These flags have been added to the existing primer effects, which have been left in the game relatively unchanged

ITEMGROUP UPDATES
- I will be going over these to ensure that lab loot is reasonable. I don't think I'll actually need to change very much. Mutagen loot is currently very lame, and this will automatically bump it up to be decent,

HELP FILES
- I will go over the help files to make sure they explain how mutagen works.

SUMMARY
The net result is that you pick up bird infusion, inject yourself, then every couple of hours you have a chance to mutate, depending on all the same factors as are present now, except the system is only looking at one vitamin instead of two.

Now you will not be able to take primer without mutating, unless you have all the mutations of that category already, but in that case you don't get any buffs, so there's no more cheesing primer for sick gains. You still get the temporary stat buffs if you aren't post-thresh, but with them will come the risk of mutating. 

Because the process no longer relies on lucking out and finding catalyst, you will be more likely to find something you can use in a lab, and you will have to do less tedious crafting to get mutated. Craft times and requirements are still quite high, so you won't get everything you want without any work, either.

Other than the EOCs in changing_eocs.json, very little of the existing system needs to change. Mutating should take about as long as it did before, with similar chances of success.

#### Describe alternatives you've considered

I thought about using a new EOC instead of suffer::, but I can't think of a way to do that as neatly without making duplicate EOCs for every single mutation line, including those in all of our mods. As mutagen is a core concept to our game, I don't think the basic stuff needs to be EOC-ified. Contributors are still able to add or change mutagen types in json.

#### Testing

ongoing

#### Additional context

https://www.youtube.com/watch?v=jAzgaqC8xCs

### CODE REVIEW

**Comment by Venera3** [comment]
Mutations shouldn't be a straightforward process, at their core, and they should include running costs - both things the current system does very well. 

The communication problems can be solved by including a detailed runthrough in the help menu, or adding more direct instructions to the items/effects but reverting to birb mutagen->guaranteed birb traits is a huge step backwards.

On the implementation side, going through hardcode for something that is eminently EoC-able is also not a reasonable change - these days the entire mutation logic could move *out* of hardcode.

**Comment by fairyarmadillo** [comment]
> Mutations shouldn't be a straightforward process, at their core, and they should include running costs - both things the current system does very well.
> 
> The communication problems can be solved by including a detailed runthrough in the help menu, or adding more direct instructions to the items/effects but reverting to birb mutagen->guaranteed birb traits is a huge step backwards.
> 
> On the implementation side, going through hardcode for something that is eminently EoC-able is also not a reasonable change - these days the entire mutation logic could move _out_ of hardcode.

1) The current system does not do this well. Players wind up bottlenecked very quickly because of asymmetrical drains on the two necessary vitamins, with their only recourse being either weeks of waiting or multiple TCL dives.

2) The instructions are already as direct as they can possibly be. Players are told in no uncertain terms in the item descriptions and mutation failure messaging what they need to do, and as pointed out in the attached issue, it is not getting through to them. This is our fault, not theirs.

3) The existing mutation code is at least 1300 lines of C++ and is not EOCable. My change removes 99 lines of json and replaces them with like 12 lines of C++.

I don't think anybody is happy with the present system. The existence of catalyst is one of the biggest problems, but it's not the only one. We aren't getting anything out of having it, except that we are discouraging and preventing players from engaging with the system by needlessly obfuscating it. This stuff should be confusing to the character, not to the player. The way we represent that is skill requirements, multi-stage crafting, etc., not hidden variables that risk killing the character if they go too high.

The #1 piece of advice you get right now when asking how to mutate is either to cheat or not bother. That's not ideal!

**Comment by fairyarmadillo** [comment]
> reverting to birb mutagen->guaranteed birb traits is a huge step backwards.

Also not sure what you mean by this. Currently bird primer + catalyst = guaranteed bird traits. This is just removing the unnecessary OOC complication of catalyst.

**Comment by anoobindisguise** [comment]
I am personally not a fan of the "resting typed mutagen buff without any base mutagen to cause change" where you inject say 5 slime serums, 5 cephalopod serums etc and get a massive brain blast to learn everything extremely fast for example. Or dose up on trog and medical and become a melee monster with your hulked out strength. It's ok from a gameplay perspective but it's extremely weird from a flavor/lore/realism standpoint - all these chemicals sitting in your bloodstream that are giving you certain effects that are characteristic of what they would be mutating you into, yet not actually *changing* you. I think getting to experience buffs from your mutagen flavor should be a "reward" for fully committing to your mutagen tree. 
There's also the matter of even to this day there are people confused as hell about the new mutagen system and how it works. It's an extremely complicated system for the sole reason of getting passive stat buffs as mentioned above afaik that was literally the stated reason it would work that way when myliedaniels implemented the new system. It's an extremely unintuitive system and i'd be very happy to see it simplified.

**Comment by fairyarmadillo** [comment]
My vote would be to remove the passive stat buffs entirely. I-am-Erk proposed lootable super-soldier serums that boost various stats temporarily, and those could totally replace what Primers do on that front with fairly minimal effort.

**Comment by Venera3** [comment]
The mutagen effects confering bonuses is a system that needs limiting or long-term consequences - but it is far from being the only sense of the system.

 Turning the mutagen effects into flavor/signposting only (i.e. add instructions to mutate to the effect desc and some flavir snippets) would be a reasonable change, for what it's worth. So is increasing the amoubt of available mutagen loot to encourage experimentation (like that'll ever happen...), tweaking the mutation messages/dreams and so on. The system isn't where it wants to be, but it does a lot of things better than the alternatives - both the old one and this partial reversion.

**Comment by fairyarmadillo** [comment]
> The mutagen effects confering bonuses is a system that needs limiting or long-term consequences - but it is far from being the only sense of the system.
> 
> Turning the mutagen effects into flavor/signposting only (i.e. add instructions to mutate to the effect desc and some flavir snippets) would be a reasonable change, for what it's worth. So is increasing the amoubt of available mutagen loot to encourage experimentation (like that'll ever happen...), tweaking the mutation messages/dreams and so on. The system isn't where it wants to be, but it does a lot of things better than the alternatives - both the old one and this partial reversion.

This is not a reversion. Nothing changes playerside except that you take one drug instead of two. You still have to wait for the EOCs and everything.

**Comment by Venera3** [comment]
It removes the stochastic part of the system (category picking and mutation rolls).

**Comment by fairyarmadillo** [comment]
> It removes the stochastic part of the system (category picking and mutation rolls).

No, it doesn't? That's all in C++ and always has been.

**Comment by anoobindisguise** [comment]
> It removes the stochastic part of the system (category picking and mutation rolls).

what does this mean. you still take a mutagen type of your choice and get random mutations out of that tree just like before, except you don't need generic mutagen to do it. instead, generic mutagen gives you random mutations like it used to a long time ago instead of being a "helper" to the typed kind.

**Comment by Venera3** [comment]
Current system: mutagen causes you to roll to mutate, decays slowly and as it fails mutation rolls. On a successful mutation roll you choose a category from all your typed mutagen vitamins, weighted by their level. Typed mutagen decays slowly, and needs a high level to threshold break - one of the consequences of this setup is to make multi-category mutation sessions considerably more risky.

Your proposal is the old system with a time factor - completely deterministic beyond the final trait roll, which in effect usually boils down to a handful of traits.

**Comment by fairyarmadillo** [comment]
> Current system: mutagen causes you to roll to mutate, decays slowly and as it fails mutation rolls. On a successful mutation roll you choose a category from all your typed mutagen vitamins, weighted by their level. Typed mutagen decays slowly, and needs a high level to threshold break - one of the consequences of this setup is to make multi-category mutation sessions considerably more risky.
> 
> Your proposal is the old system with a time factor - completely deterministic beyond the final trait roll, which in effect usually boils down to a handful of traits.

That isn't true though. My system: typed mutagen causes you to roll to mutate, decays slowly, and as it fails mutation rolls. On a successful mutation roll you choose a category from all your typed mutagen vitamins, weighted by their level. Typed mutagen decays slowly and needs a high level threshold to break. The system works identically to the way it did before, the extraneous drug is simply removed.

**Comment by fairyarmadillo** [comment]
image
image

Ignoring the silliness of my placeholder messages, you can see the system still works like it used to here. I just didn't need to take any catalyst.

**Comment by anoobindisguise** [comment]
> Current system: mutagen causes you to roll to mutate, decays slowly and as it fails mutation rolls. On a successful mutation roll you choose a category from all your typed mutagen vitamins, weighted by their level. Typed mutagen decays slowly, and needs a high level to threshold break - one of the consequences of this setup is to make multi-category mutation sessions considerably more risky.
> 
> Your proposal is the old system with a time factor - completely deterministic beyond the final trait roll, which in effect usually boils down to a handful of traits.

That's not exactly true. Mutagen and typed mutagen decay on their own at different but similar rates. Regular mutagen deducts 100 mutagen every time it tries to pick a mutation from a category and then if it succeeds deducts 100 from that category too. If I understand the PR correctly what happens is that if you have say 1000 bird and 2000 slime you have a 66% chance of getting slime and a 33% chance of getting bird just like before. The only difference is that you're not paying the "entrance fee" of 100 generic mutagen to pick a category. You still have similar risks from having multiple categories = slower decay of all categories and longer time spent with their detrimental effects.

How is it any more deterministic than before? Unless you got your generic mutagen from slurry you weren't going to get out of category mutations anyways.

**Comment by kevingranade** [comment]
You've never actually outlined what the problem is other than people claiming it's confusing. If our criteria for removing features were "redditors claim it's too confusing" we wouldn't have any features.

I'm also not seeing any kind of outline of how it's supposed to work other than "It's simple now", which is not actually a goal for the system.

**Comment by fairyarmadillo** [comment]
> You've never actually outlined what the problem is other than people claiming it's confusing. If our criteria for removing features were "redditors claim it's too confusing" we wouldn't have any features.
> 
> I'm also not seeing any kind of outline of how it's supposed to work other than "It's simple now", which is not actually a goal for the system.

It works exactly the same as it did before, you just take the primer by itself instead of also having to take catalyst. It uses all the same code, same effects, everything. The only thing it changes is the single EOC that Catalyst was using, which didn't do anything other than randomly run mutate(), where all of the mutation logic lives.

If you open the attached issue, you'll see many problems with the system in the issue itself, and many more in the comments.

If you'd rather not do that:

1) Mutations currently spend catalyst every time the EOC procs, regardless of what mutate() then chooses to do. There is some random chance involved here, so you can inject two primers and two catalysts, then watch as mutate() tries and fails to get you a post-thresh mutation, which will burn up all your catalyst and none of your primer. Unless you have more catalyst or chelator, you can't continue mutating for days or even weeks, because your primer is still near overdose levels. It only decays very slowly over time, while catalyst decays fairly quickly for the reason I just mentioned.
2) If you inject primer without catalyst, nothing bad happens to you except a very manageable health malus. It is common practice for players to abuse this by injecting primers they don't intend to use for mutating with no mutagen to get substantial stat buffs at very low cost and zero risk.
3) I know the dev team isn't fond of reddit, but 90% of the people who post there have nothing to do with the harassment that developers have received, and are instead just logging in to look for an answer to a question in a game that no longer has an up-to-date wiki. While they can be hyperbolic, I don't think it's totally worth discounting an opinion just because someone voiced it there. People also voice the same issues in my discord and on both Somethingawful threads.
4) Crafting primer is pointless right now unless you're abusing the temporary buff issue, because it's straight up worse than typed mutagen. You will always run out of catalyst (I refer to the untyped "mutagen" vitamin here, not the item) before you run out of primer (again, referring to the vitamin, which is also called mutagen lol) because of how the system works. Primer in the lore is meant to be a breakthrough that propelled Dr. Maiar's career forward in XEDRA, but as-is, there's no reason you'd ever want to make it, and no reason they would either.
5) Catalyst being extremely important but relatively rare means that mutagen loot often just sucks. Your chances of getting something you can use at all are very low. Drop tables could be adjusted, sure, but it's still an issue that this would help solve.
6) I personally find it confusing and annoying to deal with, and I am pretty knowledgable about the game. There are multiple levels of obfuscation with hidden variables that make it much harder to keep track of what's happening, and not in a fun exploratory way, just a way that wastes time and resources.

I opened the issue two weeks ago in the hopes people would bring up these concerns at some point before I started doing any actual work. :/

**Comment by fairyarmadillo** [comment]
I'd also like to point out that we currently have:
Mutagen (item), gives you mutagenic slurry (vitamin) which then gives you mutagen (vitamin) and typed mutagens (vitamin)
Typed Mutagen (item) gives you mutagen (vitamin) and typed mutagen (vitamin)
Mutagenic Primer (item) gives you typed mutagen (vitamin)
Mutagenic Chelator (item) gets rid of mutagen (vitamin) and typed mutagen (vitamin)

Getting rid of catalyst and slurry as concepts and making primer just be a stronger version of the mutagen item, with the same vitamins as it has, would clear up a lot of this confusion.

Mutagen (item), gives you mutagen (vitamin)
Typed Mutagen (item) gives you typed mutagen (vitamin)
Mutagenic Primer (item) gives you typed mutagen (vitamin)
Mutagenic Chelator (item) gets rid of mutagen (vitamin) and typed mutagen (vitamin)

**Comment by I-am-Erk** [comment]
I'll try to explain the meta ground here, because I don't think it's clear. For all your assertions, this *is* a partial reversion. You're onsoleting a portion of the new mutagen code and taking some of it to c++ from JSON, making a part of the process more like it was. It's not a full reversion but it is, unquestionably, a reversion.

To revert part of a pretty new system that solved a lot of problems, generally we (the merge team) need a very clear and well articulated rationale. I get the feeling, especially from your last post, that you *have* one, but both this and the issue post are largely dependent on the assumption that we all agree with your opinions from the start and understand that what you're doing is necessary. We don't. Last time I played a mutant on the new system I felt it was excellent. I accept that I could be wrong, but your job is to convince me of that, *at the start*, because you're proposing what can easily be a major backslide on a feature we waited years for. Currently I see venera and Kevin both raising concerns and you seeming to get frustrated by it; they're just doing their due diligence on a proposal like this.

Does that help? Stop saying this isn't a reversion and instead work on taking a bit of your last long list comment and working that into a clear writeup justifying why we should backtrack on a significant chunk of the new mutation system instead of continuing to develop it. What you come up with should be edited into the PR description as well.

**Comment by Zireael07** [comment]
This is only a _partial_ revert. When I last tried to play a mutant, I was very confused by how it works now, so this simplification is a very good idea. The need to take two things which are really difficult to translate (what the eff is the difference between catalyst and primer???)...

**Comment by I-am-Erk** [comment]
> This is only a *partial* revert

Yes, that's what I said. In response to the large all caps repeated assertion that it's not a reversion. A partial reversion is a reversion and needs the associated rationale and explanation.

**Comment by fairyarmadillo** [comment]
@I-am-Erk 
292647177-56639d31-617b-442c-99d6-e042477d3a82

I feel like people just aren't reading the issue, the PR, or my replies. Venera's comments indicated he did not understand what my PR was doing, but he still moved immediately to block it, citing incorrect assumptions in doing so.

My reply to Kevin was very thorough, but you're telling me I haven't explained anything. Is there something wrong with the numbered list of reasons I laid out there?

And the all caps lines in the PR are headers to organize information in a dense piece of text, they're not yelling.

**Comment by anoobindisguise** [comment]
Obviously I'm not the author and some of this is certainly redundant to say, but:
In my opinion the primary advantage of the new system is that rather than instantly developing new mutations upon consumption, you instead buy yourself a ticket for a certain number of mutations which develop slowly (more quickly the more you have remaining) and you can't easily stop the process until it runs its course and also not without a penalty for doing so on top of needing a semi rare consumable.

Removing the current function of catalysts does not compromise the primary advantage. It simplifies the system, by changing generic mutagen from the "fuel" (all categories are now their own "fuel") into a "random" category. 

I think "random" should be the most common and readily available to encourage risky early mutation attempts. Mutagen slurry sort of works like this, but isn't ideal IMO. It is weighted against categories it chooses (you have say 175 in each category and your random mutation chooses Bird. Now you have 75 bird and 175 bird and can't get any more Bird, rather than it being true random every time. As is, it's easier to get a typed mutation than a random mutation, generally speaking.

The change simplifies the system and makes it more intuitive. The disadvantage is that you can no longer as easily use mutagens for stat buffs (which was the original primary reason the system Obviously I'm not the author and some of this is certainly redundant to say, but:
In my opinion the primary advantage of the new system is that rather than instantly developing new mutations upon consumption, you instead buy yourself a ticket for a certain number of mutations which develop slowly (more quickly the more you have remaining) and you can't easily stop the process until it runs its course and also not without a penalty for doing so on top of needing a semi rare consumable.

Removing the current function of catalysts does not compromise the primary advantage. It simplifies the system, by changing generic mutagen from the "fuel" (all categories are now their own "fuel") into a "random" category. 

I think "random" should be the most common and readily available to encourage risky early mutation attempts. Mutagen slurry sort of works like this, but isn't ideal IMO. It is weighted against categories it chooses (you have say 175 in each category and your random mutation chooses Bird. Now you have 75 bird and 175 nonbird and can't get any more Bird, rather than it being true random every time. As is, it's easier to get a typed mutation than a random mutation, generally speaking.

The change simplifies the system and makes it more intuitive. The disadvantage is that you can no longer as easily use mutagens for stat buffs (which was the original primary reason the system worked the way it did) but it's unclear if we actually want it to work that way and I've mainly seen dissenting opinions rather than devs liking using mutagen for stat buffs. You will still be able to do it, but you'll basically need to "complete" the tree first.worked the way it did) but it's unclear if we actually want it to work that way and I've mainly seen dissenting opinions rather than devs liking using mutagen for stat buffs. You will still be able to do it, but you'll basically need to "complete" the tree first.

**Comment by fairyarmadillo** [comment]
Screenshot_20240106_120932_Discord
Three supporting comments from my discord. Obviously these folks are biased to agree with me, but that doesn't mean their experiences ought to be discounted:

Screenshot_20240106_120820_Discord
Screenshot_20240106_120917_Discord

**Comment by fairyarmadillo** [comment]
Here's another one for good measure:

Screenshot_20240106_122751_Discord

**Comment by I-am-Erk** [comment]
I feel as though we're talking past each other a bit.

- I think you do raise some decent points in your reply to Kevin, I even said as much when I said it looks like you have a rationale behind this. I'm not yet certain if I *agree*, because:
- you're asking mergers and reviewers to collate information between an issue you wrote, your PR description, and your comments on both. If this were a minor push forward, that might be okay, but it's not, it's a relatively significant balance change. You need to make sure someone coming in can read your Purpose for Change and understand fully why you are doing this. At most, asking us to read the linked issue is fine, but not asking us to read several pages of discussion and come out with the same conclusion you did. Especially given that (and this is not meant to be a negative observation, just an observation, I do it too) your comment threads are *very verbose*. There is a ton of information presented, most is not relevant, and all of us are trying to review more than one PR today.
- as Kevin said, "Redditors are confused" just isn't going to get you far. It's got nothing to do with devs largely not reading Reddit, it wouldn't have gone far when we were active there either. The response I'd have for that would be to move forward on the system to clarify those common problems, not to revert it. Again, I can be convinced otherwise, but you're not really making a convincing case so far.

I'd suggest that your reason for change should briefly outline how it currently works, then explain how this is a problem. Your proposed solution should also explain why you don't feel we can solve this by, for example, making terminology clearer, adding more guides in the game, adjusting spawn balance of catalyst, etc.

You need to go through this because like I said, you're trying to explain it to people who largely haven't had these problems. That doesn't mean we're not receptive to your arguments but I don't think we're all that inclined to read through several threads to understand them, nor does it serve the purpose you want it to when we do. For me, it makes me slightly irritated, which isn't the mindset you want me in when I start trying to assess your changes I think.

Does that make sense?

**Comment by fairyarmadillo** [comment]
> Does that make sense?

1) Verbosity is a hard requirement when discussing a system that calls six different things "mutagen"
2) You all have the benefit of working with the code frequently. 'Some redditors', ie 99% of players, do not. The game is very different for them. Just because you understand it does not mean that it's well executed
3) The comment process exists so that reviewers can raise concerns and hear arguments. I have never seen a PR where the reviewers said 'we should not be expected to read replies to our posts'

I get the strong feeling that if I were to make another PR, it would not matter what I put in it. The dev team ignored the issue I put up for discussion two weeks ago and an internal consensus seems to have been reached out of hand. The only answer I've heard is "tldr" and all arguments have fallen on deaf ears.

**Comment by I-am-Erk** [comment]
I'm sorry that's how I've made you feel. I'm not sure how else I can make myself clear; I joined in here because I think your ideas have merit and I'd like to give them a fair chance, but I don't feel my words are landing that way. If your PR stood no chance of merging I wouldn't waste half an hour telling you how to adjust it, I'd just close it.

**Comment by fairyarmadillo** [comment]
> I'm sorry that's how I've made you feel. I'm not sure how else I can make myself clear; I joined in here because I think your ideas have merit and I'd like to give them a fair chance, but I don't feel my words are landing that way. If your PR stood no chance of merging I wouldn't waste half an hour telling you how to adjust it, I'd just close it.

I do not get the impression that either Venera or Kevin understood the content of my PR. Venera made several posts that appeared to be based on incorrect assumptions about my proposal, and Kevin came in claiming I'd done nothing to make my case when that's what I spent most of my evening doing last night, with evidence from 23 different players. All three of you seem to have ignored Anoobindisguise's comments.

What am I supposed to take from that? How will rewording work on people who admit they aren't reading?

**Comment by I-am-Erk** [comment]
> How will rewording work on people who admit they aren't reading?

This is an apt summary of how I presently feel. I just told you all the things you're asking, and I think I'll step out now because I don't sense anything but mutual frustration coming from this.

**Pull request closed without merging**
