### PR TITLE
Changed time and energy to create a washboard.

### PR DESCRIPTION
**Pull request by faefux**
#### Summary
Balance "Change time and energy to create a washboard."

#### Purpose of change

When I find decent dirty object that yields a lot of Kevlar for example; I run in to a house, smash a piece of furniture, run to bathroom and quickly build a washboard and clean the object before leaving the washboard behind and repeating the next time I find an object that makes it worth it.  All within a very short time-frame. This should change it so you're at least making a kind of effort.

#### Describe the solution

Changed the time taken to create 25 minutes. We had a small discussion on this at #49518 with @natsirt721 and @Night-Pryanik and landed on `perhaps to 10 or 20 minutes` so I cranked it up to `25 m` as long as simply taking more time out of the day you'll burn more calories and you'll be leaving your torch on for longer if hidden in that closet.

My own Objection:  I still think this is somewhat on the liberal side and would appreciate feedback here. Happy to put it up to `45 m` if nobody objects or to something else if anyone has different idea...

#### Describe alternatives you've considered

I would like to have different kinds that make cleaning faster or slower and add the traditional beating wet clothing method. But I would think this would need a lot more work and i'm not sure where even.

#### Testing

ran linter

#### Additional context

Changed to `'MODERATE_EXERCISE'` as this was always the plan in original PR. I just forgot.

### CODE REVIEW

**Comment by natsirt721** [comment]
45 is fine by me. I think theres an argument to be had for anything between 20 and an hour, based on the size of the end product and the skill of the crafter. An even 30 seems like it would strike a good balance but anything in that range should be plausible.

**Review by Night-Pryanik — COMMENTED** [review]
I don't like the change to `MODERATE_EXERCISE`. It isn't an energy-consuming task at all. You are just sitting with a piece of wood and a knife and more or less slowly cutting the "waves" on it. Nothing and no one is hurrying you, you could sit and cut the stuff literally all day and you won't be really tired.

**Comment by faefux** [comment]
> I don't like the change to `MODERATE_EXERCISE`. It isn't an energy-consuming task at all. You are just sitting with a piece of wood and a knife and more or less slowly cutting the "waves" on it. Nothing and no one is hurrying you, you could sit and cut the stuff literally all day and you won't be really tired.

I respectfully disagree. All you need is cutting 1 so it's carving at a solid plank of wood with a potentially very basic knife. Sure you could do it slowly but  I am sure if I picked up a knife and attempted to build one of these i'd be pretty worn out after having to apply pressure to plane or cut  out the ridges of a  solid piece of lumber.

**Comment by natsirt721** [comment]
Moderate Exercise is equivalent to walking. Hiking cross-country and carving simple notches in a plank should not have the same level of exertion, even if your tool is poor. Consider that most knives in the game have cutting 1, from stone knives to pre-apoc steel knives. If anything your concern is evidence that cutting levels need to be expanded.

How about changing the tool requirement to wood sawing?

**Comment by I-am-Erk** [comment]
I think moderate exercise is pretty decent. we could always have a second recipe requiring a saw.

**Comment by faefux** [comment]
> Moderate Exercise is equivalent to walking. Hiking cross-country and carving simple notches in a plank should not have the same level of exertion, even if your tool is poor. Consider that most knives in the game have cutting 1, from stone knives to pre-apoc steel knives. If anything your concern is evidence that cutting levels need to be expanded.
> 
> How about changing the tool requirement to wood sawing?

I agree with much of your points especially about knives but feel like your under rating how much effort is needed. Even sawing a plank of wood is more exerting than walking.  These are not simple  tasks, they're taxing manual labour.

**Pull request merged**
