### PR TITLE
Fix maps changing their location

### LINKED ISSUE #61214: Trail guides and maps change their name if you travel to a different city
### Describe the bug

The name (ie what you see in your inventory) of trail guides and other maps is dynamically generated based on your position and the nearest city. Thus, if you drive (or long-range teleport) to another city, your `Corinna trail guide` would now be called a `Lemington trail guide`.

### Steps to reproduce

1. Go to the middle of some city (say, Corinna).
2. Find/debug yourself a trail guide.
3. Enter your inventory with `i` to see that you have a `Corinna trail guide`.
4. Travel to the middle of another city (say, Lemington).
5. Enter your inventory with `i` to see that you have a `Lemington trail guide`.

### Expected behavior

Dynamically generating the map name is fine, but the city/area that's revealed should be stored in the item instead of being based on the player's position. This would also allow behavior such as spawning maps of various nearby cities at bus stations and airports.

### Screenshots

_No response_

### Versions and configuration

Linux, last commit is 25fd53ce63259b4c232782b1bcd15e86e7d7585c

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Bugfixes "Fixes maps changing their location via travel"

#### Purpose of change

Fixes #61214

#### Describe the solution

This solution was stolen from one @harrison-salzverg . While they did create a fix and pull request for this issue, they unfortunately did so in their own forked repo, and this fix never made its way upstream.

#### Describe alternatives you've considered
Letting this continue when the solution is RIGHT. THERE.

#### Testing

Testing in progress...

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Please put the author as a co-author in your commit(s).

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/61439

**Comment by Inglonias** [comment]
It looks like I added the co-author successfully.

I'm building the game to test this as we speak.

**Comment by Inglonias** [comment]
Hrm. It looks like the `get_action` function doesn't exist anymore. I'm going to need to work out what, if anything, replaced it.

**Comment by Inglonias** [comment]
Testing shows this doesn't work. Damnation.

**Comment by Inglonias** [comment]
It looks like this is not the cause of the bug - I'm going to need to do a lot more digging to see what's happening here if I want to solve this.

**Comment by Inglonias** [comment]
Upon further review, this is a necessary but not sufficient change to resolve this issue - This will fix the visitor's pass not counting as a map - nothing more. Why maps are wandering again, I still have yet to determine.

**Pull request closed without merging**
