### PR TITLE
Allow custom dolls with custom speech

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Mecares** [comment]
Cant wait to find my first talking Survivor Steve Action   figure that gives survival tips

**Comment by woutershep** [comment]
This looks wrong on its own, first get_speech("doll") would be called and now get_speech("talking_doll") will be called, i dont see any changes renaming the doll speech so it can now be found with talking_doll instead.

**Comment by Night-Pryanik** [comment]
> This looks wrong on its own, first get_speech("doll") would be called and now get_speech("talking_doll") will be called, i dont see any changes renaming the doll speech so it can now be found with talking_doll instead.

I'm afraid I don't understand what you meant. Now it will call `get_speech` for doll with any id for it found in json.

**Comment by Night-Pryanik** [comment]
Oh, I think I got it. Before this PR if doll is the `talking_doll`, then it will try to call `get_speech()` for non-existing `doll` item and will call `get_speech()` something else (first item with `DOLLCHAT` action?).

**Comment by woutershep** [comment]
I assumed get_speech takes its words from data/json/doll_speech.json, here there are two types of speech: "doll" and "creepy_doll", i think the "doll" in that json needs to be renamed to "talking_doll" so it can be found again because you removed the 'if (talking_doll) then use doll' logic wrt get_speech.

In other words: i don't think the normal doll makes sound anymore after this PR.

**Comment by Night-Pryanik** [comment]
Yeah, I missed that. Thank you.

**Pull request merged**
