### PR TITLE
move members of player:: to Character::

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Infrastructure "move a large number of members from player to character"```
#### Purpose of change

part of #34721
#### Describe the solution

list of members moved:

update_bodytemp()
temp_equalizer()
blood_loss()
in_climate_control()
get_wind_resistance()
get_armor_fire()
is_wielding()
use_amount()
use_charges_if_avail()
use_charges()
has_fire()
use_fire()
metabolic_rate()
warmth()
bonus_item_warmth()
can_use_floor_warmth()
floor_bedding_warmth()
floor_item_warmth()
bodytemp_modifier_traits_floor()
bodytemp_modifier_traits()
temp_corrected_by_climate_control()
in_sleep_state()
global_square_location()
global_omt_location()
std::array<int, num_bp> temp_cur, frostbite_timer, temp_conv, body_wetness, drench_capacity
time_point next_climate_control_check
bool last_climate_control_ret

### CODE REVIEW

**Comment by ifreund** [comment]
Fixed the merge conflicts, should be good to go.

**Comment by kevingranade** [comment]
g++ -DGIT_VERSION -DBACKTRACE -DLOCALIZE -ffast-math -Og -Werror -Wall -Wextra -Wmissing-declarations -Wold-style-cast -Woverloaded-virtual -Wpedantic  -g  -fsigned-char -std=c++14 -MMD -MP -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -I../src -Wno-unused-variable -Wno-sign-compare -Wno-unknown-pragmas -Wno-parentheses -MMD -MP -Wall -Wextra -c npc_talk_test.cpp -o obj/npc_talk_test.o
npc_talk_test.cpp: In lambda function:
npc_talk_test.cpp:564:37: error: no match for call to ‘(const item_category_id {aka const string_id<item_category>}) ()’
         return it.get_category().id() == "books" || it.get_category().id() == "food" ||
                                     ^
npc_talk_test.cpp:564:74: error: no match for call to ‘(const item_category_id {aka const string_id<item_category>}) ()’
         return it.get_category().id() == "books" || it.get_category().id() == "food" ||
                                                                          ^
npc_talk_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____42()’:
npc_talk_test.cpp:566:7: error: no matching function for call to ‘avatar::remove_items_with(____C_A_T_C_H____T_E_S_T____42()::<lambda(const item&)>)’
     } );
       ^
In file included from ../src/map_selector.h:8:0,
                 from ../src/item_location.h:8,
                 from ../src/item.h:24,
                 from ../src/inventory.h:18,
                 from ../src/character.h:24,
                 from ../src/player.h:21,
                 from ../src/avatar.h:12,
                 from npc_talk_test.cpp:6:
../src/visitable.h:110:25: note: candidate: std::__cxx11::list<item> visitable<T>::remove_items_with(const std::function<bool(const item&)>&, int) [with T = Character]
         std::list<item> remove_items_with( const std::function<bool( const item & )> &filter,
                         ^~~~~~~~~~~~~~~~~
../src/visitable.h:110:25: note:   no known conversion for argument 1 from ‘____C_A_T_C_H____T_E_S_T____42()::<lambda(const item&)>’ to ‘const std::function<bool(const item&)>&’
make[1]: *** [obj/npc_talk_test.o] Error 1
Makefile:49: recipe for target 'obj/npc_talk_test.o' failed
make: *** [tests] Error 2

**Comment by AMurkin** [comment]
> npc_talk_test.cpp:564:37: error: no match for call to ‘(const item_category_id {aka const string_id<item_category>}) ()’

I think that's from the #35147. Two branches together?

**Comment by ifreund** [comment]
Couldn't reproduce those build errors @kevingranade.  Just force-pushed again to resolve a minor conflict.

**Comment by ymber** [comment]
This introduced #35184.

**Pull request merged**
