### PR TITLE
Skip validation of obsolete mods

### PR DESCRIPTION
**Pull request by mugling**
We have 48 mods (and counting) all of which currently receive the attention of the core developers. This is rapidly becoming unworkable and results in frequent breakage of the mods that actually are popular. No amount of opining is going to change the fact that we have limited resources and should focus them on the core game and popular mods.

A significant problems is that `--check-mods` now takes ~10 minutes to run and this needs to be done for every PR. This PR aims to improve developer QOL by having `--check-mods` skip mods that are marked `obsolete` (see #19054).

The second problem is there sheer number of possible combinations and interactions between mods.

Four mods are marked obsoleted:
* Animatronics (minimal popularity, outdated)
* Dino mod (minimal popularity, outdated)
* Mundane zombies (list oudated and hard to maintain, nearly duplicated by only wildlife)
* No triffids (minimal popularity)

Please no offers to maintain (apart from core developers). The issue being that when a core developer alters the C++ code they have to update all 48 mods and that work can only reasonably be done by them. If your busy penning a 1000+ word ~~shitpost~~ argument consider instead creating a github repo and offering to maintain `contrib` mods there. Again no amount of opining will change the simple fact that we have too few developers to support all of those mods.

Note this PR does **not** break any savegames

### CODE REVIEW

**Comment by pisskop** [comment]
I would argue that no triffids should be kept even if it isn't as popular as other exclusion mods.

**Comment by mugling** [comment]
No, we need to reduce mod count and this isn't a thread for opining about it. There isn't enough developer time to support them all. 

Options are:
* Reduce number of mods
* Stop developer support for all mods

Note that the latter is almost certainly going to result in breakage of most of the mods over time.

Opining in this thread is about as useful as stating an issue *"I'd like Z-levels finished"* - you simply aren't going to be able to change the facts of the situation.

**Comment by Coolthulhu** [comment]
I recall there being talks about cata launcher having support for mods outside core, with automatic download. If this was implemented, we could drop many core mods and possibly offload them to a separate repo or something like that.

**Comment by mugling** [comment]
> If this was implemented, we could drop many core mods and possibly offload them to a separate repo or something like that.

Yes, this could work well for the popular mods that have a definitive maintainer. I'd like to combine this with @illi-kun's idea of publishing JSON API changes.

**Comment by hmstanley** [comment]
I've been surprised from the beginning of playing this game that dev's supported mods, it's just something you don't see in many games.. 

that said, it's unsustainable period. 

With the core code competing with the mod revision code, the problem becomes self sustaining, something will break something and I for one have seen numerous issues with mods, even though I know the devs are committed to fixing said mods, just not enough time or I would argue, insight into the individual mods under the "included" umbrella, I mean, someone else created these additions, not the core team.  

One approach, which I'll call "less builds more milestones", might force mod developers to manage and update their stuff with more mature and refined mod unit tests.  The tests, I think, can be something the devs would be responsible for (they are already) and it might allow more focus on the core set of features from the devs and shift focus back to mod devs on their mods.  Those modders who want their babies to survive, survive, those who don't, well, they die off.  Happens on many other games all the times.. This might result in more disjointed mods, but it also might result in some very good, managed, updated mods that swallow other under developed mods over time, incorporating those features who's modders have died off (seen this happen all the time on other games).

 Food for thought.

**Comment by mugling** [comment]
> I've been surprised from the beginning of playing this game that dev's supported mods, it's just something you don't see in many games..

Yes,
* anyone can write a mod and there's lots of complaint if we don't include it
* removal of any content is considered heresy
* developers have to support all mod content

> that said, it's unsustainable period.

I'm sure a few other developers will be familiar with the graph of [software death](https://tinyletter.com/programming-beyond-practices/letters/the-sad-graph-of-software-death):

soft

What we need:
* More developers
* Less mod content
* PR's closing issues or adding meaningful features

What's actually happening:
* Less developers
* More mod content
* `+3 foo, -2 quux` PR's (trivial and subjective JSON edits)

**Comment by hmstanley** [comment]
well..I'm sure you would then agree.. give the modders the tools to make their mods and update those tools as part of core?  I mean, it's a lot easier to maintain a set of generic unit tests that speak to core functionality with respect to a mod than to maintaining the actual mod?  Anyway, it sounds like you are trying to fix this.. no need to hear from the choir.

**Comment by Noctifer-de-Mortem** [comment]
I really see no reason to complain, developer time and resources are limited so reducing the workload is desirable. 

If you really want one of those mods for new worlds just delete the obsolete field in modinfo.json when you download a new experimental and if it has any load issues either fix it yourself or ask for help in the forum. Many mods are run on the forum and are broken all the time by new PRs but are swiftly fixed by their authors or those who use them.

**Comment by illi-kun** [comment]
@mugling this is good food for thought, thanks for publishing the graph.

**Comment by mugling** [comment]
@illi-kun your continued pruning of the issues database is most welcome.

It's obvious which part of the graph we are currently in and we need to promptly get back on track. Collectively we've closed ~500 issues but the number is still growing. Closing spurious issues helps but we also need to concentrate more on reducing the number of issues via bugfixes - especially for release milestone issues.

Pushing responsibility of mod maintenance to their creators is one significantly helpful step and given all of the positive feedback to date now is probably a good time to merge this PR. The next step is to co-ordinate with @remyroy for moving mods with defined maintainers to separate repos and also pursue your idea of publishing regular API updates.

**Pull request merged**
