### PR TITLE
Flail weapon balance (Part 2 of melee weapon balance project)

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary

```SUMMARY: Balance "Rebalances flail weapons"```

#### Purpose of change
Mlangsdorf has been doing some deep analysis of the melee weapons and both analysis of dps of weapons and evaluating their strength ingame, and started a large "melee weapon balance" project. His analysis and his proposed values can be found here:
https://docs.google.com/spreadsheets/d/14eQIe4AO_f6OxCt1XcB4NLAs6-5R1wQW-ydZG0orYdY/edit#gid=1655515751
He wanted someone to start implementing the new values ingame, so i started work.

#### Describe the solution
Rebalances flail weapons according to excel sheet.
#### Additional context
Credit to Mlangsdorf for the excellent analysis and for most of the proposed values.
Credit to vastin for review of the excel sheet.
Credit to hymore24/hirmuolio for the initial complaint.

### CODE REVIEW

**Comment by SirPendrak** [comment]
Maybe piercing damage for morningstars? 
And why do they get -1 to hit? 
If to hit is calculated: -2 base +2 grip +1 lenght +/-0 any surface +/-X **ballance** then **ballance** for them must be -3 which seems extreeme

**Comment by mlangsdorf** [comment]
Base: -2
Grip: Weapon +2
Length: Short +1
Striking Surface: Any +0
Balance: Clumsy -2
Total is -1.

If an axe or mace has a -1 balance, I'm okay with a flail having a -2 balance.  And morningstars have 6 points of pierce damage already, I guess that could reasonably be upped to 10.

I'm reasonably satisfied with damage values for the flails, but they do not have great DPS.  Maybe they should get more damage, or maybe they should get some kind of special bonus the way that polearms are going to get.  I can't think of anything appropriate, though.

**Comment by ampersand55** [comment]
I think the makeshift sap and especially the blackjack are significantly different from e.g. rock in a sock or a steel chain in terms of balance. They are somewhat stiff but springy weapons and should probably not suffer a clumsy balance penalty. 

A video showing the floppiness of blackjack :

* https://youtu.be/NAMaMne0ouE?t=185

The blackjack recipe should probably have included a spring.

**Comment by Brian-Otten** [comment]
Blackjack and makeshift sap

Base: -2
Grip: Weapon +2
Length: +0 No length bonus
Striking Surface: Any +0
Balance: Well balanced for swinging +1 (canonical example here is knives, and these are a similar small weapon that is well balanced for its intended use.
Total is +1.

Adjusting the blackjack and makeshift sap to +1 in the excel sheet and in the PR.

**Pull request merged**
