### PR TITLE
Forging now uses ```forging_standard``` and ```metal_standard```, part 1/2

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Infrastructure "Mainline items involving forging now use forging_standard and metal_standard"```
#### Purpose of change
1) The acetylene torch for forging has the wrong efficiency compared to forges per ```forging_standard``` (electric/coal forges use x5 more charges, currently) due to recipes using ```forge``` and ```oxy_torch``` instead.
2) Many metal requirements for forged items had lump:chunk:scrap ratios of 1:3:9, rather than the 1:4:20 specified in ```steel_standard``` and ```steel_tiny```.
3) Many forged items only allowed chunks or lumps, when forging would allow larger quantities of chunks/scrap to be melted together as well.

#### Describe the solution
Changed all recipes created with ```forge``` or ```oxy_torch``` previously to use ```forging_standard``` and ```steel_standard``` or ```steel_tiny```.

#### Describe alternatives you've considered
Changing the ```forging_standard``` ratios for the forges versus the torch(currently 1:1), the latter being suboptimal to a proper forging setup.

#### Additional context
Only mainline items were fixed, will make a second PR for mods once #30834 is merged so Moose isn't delayed for merge conflicts.

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
Closing until I get back from work, something in recipes_construction_om.json(Which I didn't even touch) is blocking my troubleshooting

**Comment by LaVeyanFiend** [comment]
Second recipes for items that allow ```"welding_standard"``` or ```"forging_standard"``` are necessary due to ``"using"`` not allowing the option of one or the other.

**Comment by I-am-Erk** [comment]
The oxy torch isn't measured in the same units as the other forging types, and from what I've read electric forges are dramatically inefficient. What's your bases for the efficiency changes?

**Comment by LaVeyanFiend** [comment]
Closed until efficiency numbers for forging_standard are solved.

**Pull request closed without merging**
