### PR TITLE
Added option for vehicle roof sprite visibility

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Features "Added option for vehicle rooftop tile visibility"

#### Purpose of change

We don't have the option to see the roof of a vehicle, even though we can see turrets, solar panels etc.  It breaks immersion if each vehicle looks like it's missing the roof.  Someone made the choice for all of us that we can't see vehicle roofs, so I want to give the choice back to us.

#### Describe the solution

The code that assigns vehicle parts visibility layers was moving roofs to -1 so we never saw them, I added an option in the graphics menu with the tile options to toggle rooftop visibility, and this code will now move rooftop tile visibility to the correct layer, above the rest of the vehicle and below on_roof.

#### Testing

vehicle roof option

Vehicle rooftops disappear when the player steps within, like turrets and lights etc do.  The indicators that signal when an item is in a vehicle tile show up as normal so the player can still know when there is an object inside a vehicle even with the roof on.  Changing the roof option does not refresh the layer visibility so a world reload seems to be necessary for each toggle.

#### Additional context

Most tilesets already have a roof tile assigned, and they are mostly incomplete - so I was not able to assign a new roof tile, and could not figure out how to overwrite existing tiles, so I could not get a good screenshot of it working.  Tile creators will eventually solve this problem on their own by updating their tile roof sprites.  Also, many vehicles have unusual roof placements, such as trucks having their roof extend out onto the side panels.  A future pr may need to be done to update vehicle roof placements so they are in more logical positions.

### CODE REVIEW

**Comment by Xaleth** [comment]
YES! THANK YOU SO MUCH

**Comment by stubkan** [comment]
@actual-nh I don't think Z levels are worked with here - the roof is on the same level as the car

**Comment by Xaleth** [comment]
Z-levels are a whole new rabbit hole. One of the issues that would come with that is that if the roof is on the level above, then that means the car's roof is on the same level as buildings with a second story, and that's pretty high up if you ask me

**Comment by stubkan** [comment]
image
image

image


Made new tileset.  Can confirm roofs are working as intended.

**Comment by esotericist** [comment]
while something of this sort is highly desirable, i don't think is the right way to address it.
a) conditionally tampering with the z-ordering in vehicle parts in this fashion is something i'm not comfortable with
b) include pollution of this sort is entirely unnecessary (`veh_type.cpp` has no sane business knowing about `options.h`)
c) you need to be able to look into the interior of vehicles without stepping into the vehicles (such as when using `x` look around) without having to change a setting and restart the game
d) this all belongs in graphics anyway, and probably can't be correctly addressed until after we're doing properly layered vehicle rendering

**Comment by Night-Pryanik** [comment]
@stubkan could you please resolve conflicts?

**Comment by I-am-Erk** [comment]
Closing as stale. Please feel free to reopen if you're active.

**Pull request closed without merging**
