### PR TITLE
Traps 3D and sinkhole rework

### PR DESCRIPTION
**Pull request by Coolthulhu**
Includes #12343

Traps changed to full 3D. astyled trapfunc.cpp since I had to change most of it anyway.

Reworked sinkholes (could possibly split it off into another PR if it is desired):
- Sinkhole will no longer move the player a z-level down and embed them into the rock leaving them to certainly starve to death
- When stepping on a sinkhole, the player is given a chance to throw a hook, rope or a bullwhip, as before
- If this fails (or the player has no such tool), a "sinking" effect is applied, with duration dependent on equipment load
- A popup is shown to inform player of the emergency (the queries were prompts anyway, so it isn't worse than in master)
- A weak character or one with no survival skill will need to wait out the sinking effect, which can last up to 2000 turns
- Struggling without skills can cause either instantly freeing self or sinking deeper
- Sinking too deep will put character's head under the mud and cause suffocation (won't kill if the player stops struggling, but will deal heavy torso damage in the end)
- The sinking effect itself decreases dexterity

The new sinkholes are dangerous if there are other creatures around, but isn't a delayed certain death effect like the one in master.

### CODE REVIEW

**Comment by jokermatt999** [comment]
Good job on the sinkhole rework. I'll close my lazy one.

**Comment by Rivet-the-Zombie** [comment]
Oh very cool!

**Comment by Zireael07** [comment]
Love love love the sinkhole changes!

**Comment by kevingranade** [comment]
Your 'sinkhole' is now 'quicksand', which is fine of itself, but it's not a
sinkhole.
A sinkhole is a formation where there is an underground void near the
surface that has collapsed, presumably because the player stepped on it.
If the sinkhole as it is is unworkable (which I disagree with, but I'm not
insistent about keeping them in their present state), I'd rather they get
removed from mapgen until they get fixed somehow.

**Comment by Coolthulhu** [comment]
> Your 'sinkhole' is now 'quicksand', which is fine of itself, but it's not a sinkhole.

I didn't know the definitions and confused them.
I'll change it to be more sinkhole-ish.

> If the sinkhole as it is is unworkable (which I disagree with, but I'm not insistent about keeping them in their present state)

It would be fine if they only spawned above some underground tunnels. Until mapgen can guarantee that, pulling the player down into solid rock is nearly certain death through starvation.

I changed the sinkhole back into a sinkhole. I changed the vertical movement to creating a pit and making the player fall into it.
Reimplementing the vertical movement would be easy - I cleaned up the ugly block of copypasted code that was there before and now instead of having to change 10 lines in 4 places in the code, it's only 2 lines in one place.

**Comment by Zireael07** [comment]
As for quicksand, keep the code for that somewhere. I'd love to see it used somewhere, maybe in swamps, maybe in deserts.

**Comment by narc0tiq** [comment]
Yeah, I like the quicksand, too, and it makes sense to have it along with
the sinkholes.

**Comment by Snaaty** [comment]
Are the swamps in cdda somewhat like a "moor"? Because if so, adding something quicksand like is definitely a good idea. Of course that is something different than quicksand, but I still remember the stories I read about people getting lost in the moor and at some point getting stuck in one of the stickier areas.

**Comment by kevingranade** [comment]
If the issue is dropping into solid rock, perhaps check whether there is a
cave underneath when the trap is triggered, if there is drop them, if not
treat it as a pit.

**Comment by qbradq** [comment]
I like this suggestion a lot! That would add variety and additional risk.

**Pull request merged**
