### PR TITLE
Support for grammatical gender in NPC dialogue translation

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: I18N "Allow NPC dialogue to be translated in a manner that depends on gender."

#### Purpose of change
In some languages it is difficult to translate NPC dialogue without knowing the gender of the speaker.

#### Describe the solution
This is an initial implementation of a system to support grammatical gender altering translations.

The goal is to allow languages that need it to offer it while not increasing the translation burden for languages that do not need it.

This consists of a number of components:
- Markup in the json to indicate which genders are relevant, and for which lines.
- Add code to `extract_json_strings.py` to add gender context to these dialogue lines.
- Add C++ code to convert genders to a context in a suitable format.
- Add a new translation function that accepts gender information as its context.

In the json you alter the `dynamic_line` like this:
```json
"dynamic_line": {
    "gendered_line": "I oversee the food stocks for the center.  There was significant looting during the panic when we first arrived so most of our food was carried away.  I manage what we have left and do everything I can to increase our supplies.  Rot and mold are more significant in the damp basement so I prioritize non-perishable food, such as cornmeal, jerky, and fruit wine.",
    "relevant_genders": [ "npc" ]
},
```

Valid entries in `relevant_genders` are `npc` and `u`.

An object like this can be nested in `dynamic_line` anywhere you would normally have a string, as you would expect.

That will cause multiple versions of the msg to appear in the translators' `.po` file, looking something like this (from a test example I put together where I've made it different for the three currently-supported genders):

```po
#: lang/json/talk_topic_from_json.py
msgctxt "npc:f"
msgid ""
"I oversee the food stocks for the center.  There was significant looting "
"during the panic when we first arrived so most of our food was carried "
"away.  I manage what we have left and do everything I can to increase our "
"supplies.  Rot and mold are more significant in the damp basement so I "
"prioritize non-perishable food, such as cornmeal, jerky, and fruit wine."
msgstr ""
"(Female version) I oversee the food stocks for the center.  There was significant looting "
"during the panic when we first arrived so most of our food was carried "
"away.  I manage what we have left and do everything I can to increase our "
"supplies.  Rot and mold are more significant in the damp basement so I "
"prioritize non-perishable food, such as cornmeal, jerky, and fruit wine."

#: lang/json/talk_topic_from_json.py
msgctxt "npc:m"
msgid ""
"I oversee the food stocks for the center.  There was significant looting "
"during the panic when we first arrived so most of our food was carried "
"away.  I manage what we have left and do everything I can to increase our "
"supplies.  Rot and mold are more significant in the damp basement so I "
"prioritize non-perishable food, such as cornmeal, jerky, and fruit wine."
msgstr ""
"(Male version) I oversee the food stocks for the center.  There was significant looting "
"during the panic when we first arrived so most of our food was carried "
"away.  I manage what we have left and do everything I can to increase our "
"supplies.  Rot and mold are more significant in the damp basement so I "
"prioritize non-perishable food, such as cornmeal, jerky, and fruit wine."

#: lang/json/talk_topic_from_json.py
msgctxt "npc:n"
msgid ""
"I oversee the food stocks for the center.  There was significant looting "
"during the panic when we first arrived so most of our food was carried "
"away.  I manage what we have left and do everything I can to increase our "
"supplies.  Rot and mold are more significant in the damp basement so I "
"prioritize non-perishable food, such as cornmeal, jerky, and fruit wine."
msgstr ""
```

Translators also get this new entry in their `.po` file:

```po
#. ~ Space-separated list of grammatical genders. Default should be first.
#. ~ Use short names and try to be consistent between languages as far as
#. ~ possible.  Current choices are m (male), f (female), n (neuter).
#. ~ As appropriate we might add e.g. a (animate) or c (common).
#. ~ New genders must be added to all_genders in lang/extract_json_strings.py
#. ~ The primary purpose of this is for NPC dialogue which might depend on
#. ~ gender.  Only add genders to the extent needed by such translations.
#. ~ They are likely only needed if they affect the first and second
#. ~ person.  For example, one gender suffices for English even though
#. ~ third person pronouns differ.
#: src/translations.cpp
msgctxt "grammatical gender list"
msgid "n"
msgstr "n m f"
```

As the comment indicates, this is where they can specify which genders are relevant for their language.  They only need to provide translations for the genders selected here.  Thus, I hope, we don't add too much burden to languages where this extra complexity is not needed.

Unfortunately, all different gender contexts will appear, even the ones that aren't needed for the language in question.  I'm not sure of a good way to avoid this.  We could have `merge_po.sh` delete them from the `.po` after merging in the `.pot` file, but I'm loathe to write my own `.po` file editor.  For now I propose we just ask the translators to mark these unnecessary translations as N/A (or their translated equivalent).

Finally, here's how it looks in game (using the above example):
cata-gendered-translation

To do:
- [x] Document in `TRANSLATING.md`.
- [x] Sanity checking of the json and the language's chosen gender list.
- [ ] (Maybe?) add similar support for player responses.

#### Describe alternatives you've considered
We already have `npc_male` and similar features to select lines according to gender, but those are not really logical or practical to use if the English version of the line would not vary by gender.

I saw a suggestion somewhere online to abuse the plural functionality of gettext for encoding gender.  That seems like a terrible idea.

#### Additional context
Things I'm deliberately treating as out-of-scope for this PR:
* Pronouns.  I think they need to be handled separately and differently.
* Genders of third parties (e.g. an NPC talking to you about another NPC).

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Is the (female version) in the example just there to show the version, or would it actually display in the game? Because it shouldn't display in the game.

**Comment by jbytheway** [comment]
> Is the (female version) in the example just there to show the version, or would it actually display in the game? Because it shouldn't display in the game.

Just an example.  You can see I wrote that in the `.po` file.

**Comment by jbytheway** [comment]
I think this has now reached the status of minimum viable feature.  I'd like to get some feedback from a translator before calling it ready to merge, though.

**Comment by jbytheway** [comment]
I got a cautiously optimistic response in discussions with A.Fulcrum on Discord yesterday, so I think this is worth a try as is.  Once it's merged we can see whether translators make any use of it.

**Pull request merged**
