### PR TITLE
Fix 13474

### PR DESCRIPTION
**Pull request by VlasovVitaly**
Fix bug #13474 
Added player actions destination coords save/loading.
Work with legacy savegames(affect only move items action).

Tested with saves from Issue and my own saves.
Someone should review code.

### CODE REVIEW

**Comment by BevapDin** [comment]
In line 435, `g->u.activity` is overridden with a new and therefor empty activity. The test for an empty `coords` vector *after* this will always be `true` and the function will always be left at that point. (This btw. breaks the "move all items" command in AIM).

The test should probably be before `g->u.activity` is override, even before the loop that extracts data into local variables.

**Comment by VlasovVitaly** [comment]
Not good. If test will be before overriding then this will be infinity loop on broken saves.
No resolve?

**Comment by BevapDin** [comment]
> Not good. If test will be before overriding then this will be infinity loop on broken saves.

The check for an empty `coords` vector should probably be done as first thing in the function because if it's empty, the whole function must be skipped anyway. Than you can override the activity inside the branch, right before the `return`.

> 'Move all items' is 'M' button in AIM?

I don't know, you can look that up in the key bindings setting there.

**Comment by VlasovVitaly** [comment]
Hmm... How about this?

**Comment by VlasovVitaly** [comment]
So if 'move items' activity don't have coords it will be dropped.
Tested with broked save from issue.

**Comment by VlasovVitaly** [comment]
About legacy save/load
Right now(in this fix) coords are saving/loaging for all actions. May be i need realize special method for that actions. 'bool _need_coodrs()' or something. This method should check all actions types for need destination coords. With this method will be easy control leagacy save/loading.

**Comment by BevapDin** [comment]
> About legacy save/load
 Right now(in this fix) coords are saving/loaging for all actions. May be i need to realize special method for that actions. 'bool _need_coords()' or something. This method should check all actions types for need of destination coords. With this method will easy control leagacy save/loading.

Just storing and loading it all the time is fine. For actions that doesn't use it, it will be empty and the overhead isn't much. At the same time, it's future proof (when someone uses the `coords` vector for a new activity).

Legacy loading isn't special here because old saves never had this vector at all.

**Pull request merged**
