### PR TITLE
Added 2 farms and balanced overmap

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content Added 2 farms and balance overmap```  

#### Purpose of change
There were not enough farms in New England to feed it's residents. I also changed stuff, that seemed weird to me in the overmap.

#### Describe the solution

- Added 2 farms, a farm with stills and an ordinary one modelled after 7d2d
- Rural houses now generate in a normal way (Like gas stations)
- Campground now far from town and in forests
- State parks are now in forests
- Motels are now next to roads, like gas stations
- Gas stations with garages are now more common and can also be found in the wilderness
- Railroad stations, zoos, stadiums are now less common
- Fixed a bug about public works,  mentioned in #20386

#### Describe alternatives you've considered
Not changing it. It's not an important update.

#### Additional context
Rural house
rural_house
State park
state_park
Gas station with garage opposite a farm
stillsandgarage_gas

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Now that's more readable. Thanks! Looking forward to reviewing.

**Comment by Amneiger** [comment]
This looks like rather more than just adding two alternative farm layouts.  Is there a chance that you could rename this to something that more accurately shows that there are several other changes in addition to farms?  (Also, I could have sworn that yesterday there were some other comments stating that the various changes here should be split up into multiple PRs - something like separating the new farms from the changes to overmap generation.)

**Comment by LovamKicsiGazsii** [comment]
I could edit that. I botched the last PR so I removed it.

**Comment by DracoGriffin** [comment]
This really should be two separate PRs:
One for the farm additions and the second for the overmap changes.

Both seem like welcome additions and changes, though.

**Comment by I-am-Erk** [comment]
I third that. I'm working on reviewing this but there is a lot to say, it would be much easier if I could just review your farm changes and just review your specials changes  since the two are not related and are both pretty significant.

**Comment by Night-Pryanik** [comment]
I can't see any house in your "Rural house" screenshot. Is this intentional?

**Comment by LovamKicsiGazsii** [comment]
> I can't see any house in your "Rural house" screenshot. Is this intentional?

That's intentional. I didn't change the house itself. "Dirt road" didn't sound that good.

> It would be much easier if I could just review your farm changes and just review your specials changes since the two are not related and are both pretty significant.

I didn't think this PR is that big. So you want me to split this PR into 2 smaller chunks. I could do that, if that's necessary.

**Comment by I-am-Erk** [comment]
It would be nice yes... The two changes are unrelated to each other, and the PR is over 700 lines long.

**Comment by LovamKicsiGazsii** [comment]
Okay, I created 2 PRs. I am closing this.

**Pull request closed without merging**
