### PR TITLE
Move soup out of recipe_food.json and add a new SOUP recipe subcategory

### PR DESCRIPTION
**Pull request by cainiaowu**
As title says.

### CODE REVIEW

**Comment by cainiaowu** [comment]
Build failed because range test failed, not caused by this PR.

**Comment by kevingranade** [comment]
There is not a remotely strong enough reason to shuffle all these entries around, please stop opening PRs that move around large volumes of json.

**Comment by cainiaowu** [comment]
@kevingranade 
So I guess someone need to clean up the wiki a little bit.

https://github.com/CleverRaven/Cataclysm-DDA/wiki/Want-to-help-with-development%3F-List-of-easy-jobs#moving-entries-from-broad-categories-to-specific-ones

**Comment by kevingranade** [comment]
Yep, done.

**Pull request closed without merging**
