### PR TITLE
Lab zombie evolution tweaks

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Balance "Adds evolutions for lab zombies"```

#### Purpose of change
Lab security and scientist zombies currently don't evolve, which causes problems for balance when players go to those sites later on.

#### Describe the solution
I added evolution groups to these zombies. Unfortunately the appearance of the evolved form won't show their flavourful roots. Security evolves using the soldier groups, and scientists using the normal groups.

#### Describe alternatives you've considered
I could add custom evolutions for the zombie types rather than soldier and plain zombie upgrades, but that's a lot of custom monsters for some pretty rare zombies. For now these suit their gear and origins.

#### Additional context
I may also drop spawn rates, we'll see.

### CODE REVIEW

**Comment by deadcutlass2** [comment]
doesn't upgrading the scientist cause them to no longer be dissectable for cbms? maybe upgrade shocker specifically instead?

**Comment by I-am-Erk** [comment]
Not every scientist has CBMs; I guess if they evolve into a different zombie, they must not have had CBMs to begin with.

Or if you prefer, the evolution process could be destroying the cybernetics.

It's not something I'm going to get too hung up on: retrieving useful CBMs from rotten corpses isn't something I think is going to continue to work as it currently does for very long.

**Comment by BenlyAZ** [comment]
You say they're pretty rare, but they're more or less ubiquitous in labs. I feel like this change makes labs less distinctive and the scientist at least deserves to not evolve into something generic.

**Comment by I-am-Erk** [comment]
I welcome you to make some unique scientist zombie evolutions then.

In the long run, I think we should be making all zombie evolutions inherit stats from their base type, so that rather than changing to a new type, scientist zombies would gain the "hulk" variant that altered their stats rather than replacing them. Since the major difference is whether or not it has a visible lab coat in the sprite and a bit of the descriptive text, I didn't really consider it an important priority before the balance fix of having evolved zombies in labs.

**Comment by BenlyAZ** [comment]
Other differences include the ability to spawn manhacks and create acid pools, or used to. If they've lost those abilities for some reason, that would seem like a logical direction for scientist evolutions. I have zero programming experience, so the "well you should do it yourself then" response is not terribly helpful.

**Comment by Lorith** [comment]
I have to go with I-am-Erk on the recommendation to make your own versions.  Editing JSON isn't programming, and is extremely easy, just tedious.  I'd much prefer fitting zombie types rather than scientists turning to already existing ones, but I'm too lazy to do it myself despite being able to, so I can't complain much.

The idea of having evolutions just modify the original is interesting, but probably very far out.

**Comment by I-am-Erk** [comment]
Zombie scientists haven't been able to throw manhacks or acid for almost six months, because those sort of abilities aren't really things zombies should be doing in the canon. The old zombie scientist is now the lab robot.

**Comment by Amoebka** [comment]
Zombie scentists are pretty much meant to be loot pinatas that pose no threat on their own. The lab difficulty doesn't and shouldn't come from them, so losing a ton of flavor evolving them into something barely more challenging is, in my opinion, just not worth it.

Also, if I'm not mistaken, undead lab security currently doesn't get shot by security bots. Evolving them to soldiers will probably remove this and cause them to get slaughtered by robots.

**Comment by I-am-Erk** [comment]
The faction point is a decent one, I forgot that I did that through the security guard and not through the turret faction. I'll have to find a simple fix for that.

The zombie scientists aren't meant to be loot pinatas, that argument doesn't hold any water at all, and I'm not sure why you'd think it would.

**Comment by kevingranade** [comment]
> Zombie scentists are pretty much meant to be loot pinatas that pose no threat on their own.

Yea, not in the slightest, in fact they really don't *need* those CBMs any more.

**Pull request merged**
