### PR TITLE
Don't clear terminal at exit when TILES=1

### PR DESCRIPTION
**Pull request by lucianposton**

### CODE REVIEW

**Comment by nanovad** [comment]
Won't this disable terminal clearing completely?

**Comment by lucianposton** [comment]
@nanovad Better completely than incompletely. :)

If you mean it would affect ncurses, this code doesn't actually clear the terminal while the terminal is in ncurses mode. It would have to call system("clear") after restoring tty with endwin() a few lines below.

**Comment by BevapDin** [comment]
Works fine on Linux with curses. In fact, I see no difference at all, the terminal is cleared as usual.

**Comment by lucianposton** [comment]
Yea, it shouldn't affect curses at all. I see no change in curses behavior. The fix only affects tiles, where it was unnecesarily calling system("clear"), which annoying removed info from the terminal.

**Pull request merged**
