### PR TITLE
Remove attractive stats and description from rabbit mutations.

### PR DESCRIPTION
**Pull request by Maddremor**
#### Summary
Balance "Made rabbit mutants less cute."

#### Purpose of change

Mutants are supposed to have a body horror theme, but skimming them had me notice that there were early rabbit mutations that had a negative ugliness score. 

#### Describe the solution

This fixes the discrepancy between current content and overall thematic intent by giving them a positive score and also remove parts of description that indicated them as such.
#### Describe alternatives you've considered

Doing further research instead of just flipping a -1 to a 1 in terms of balance. 

#### Testing

With as minute change as this I'm putting my hope in automatic testing.

### CODE REVIEW

**Comment by Maddremor** [comment]
```
D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\overmap_test.cpp(406): FAILED:
  CHECK( num_missing == 0 )
with expansion:
  2 == 0
with messages:
  num_missing := 2
  missing_oter_type_ids := "boat_rental_2 and boat_rental_2_roof"
  To resolve errors about missing terrains you can either give the terrain the
  SHOULD_NOT_SPAWN flag (intended for terrains that should never spawn, for
  example test terrains or work in progress), or tweak the constraints so that
  the terrain can spawn more reliably, or add them to the whitelist above in
  this function (inteded for terrains that sometimes spawn, but cannot be
  expected to spawn reliably enough for this test)
```
Did I fail the tests or did the tests fail me? I have my personal opinion, but this is what you get for just using the web interface.

**Comment by fairyarmadillo** [comment]
The intent behind rabbit was that it is the least frightening of all the animal mutations, as rabbits are pretty universally acknowledged to be a cute animal. Obviously they'd be less cute as four foot human hybrids, but I worry this PR runs counter to the original design, which is hinted at in some of the descriptions, like rabbit tail.

The original PR lays it all out here: https://github.com/CleverRaven/Cataclysm-DDA/pull/48548

**Comment by Fris0uman** [comment]
> We've also got other -ugly mutations throughout the system which are intended to convey that things such as gigantic butterfly wings are objectively beautiful even if they're coming out of a Brundlefly.

If other mutations are wrong they should get fixed ( could also happen in this PR), but they don't serve as a justification to have more wrong mutations. Maybe we should put down some notes in the design doc(?) to pin down what uglyness is supposed to be, and what is supposed to be ugly/beautiful in the context of mutations. Otherwise it's going to be a similar mess to FANCY

**Comment by Maddremor** [comment]
> could also happen in this PR
I did consider changing the other mutations, but there is a difference in that they are post-threshold and can be seen as clawing back some appearance. In contrast a rabbit mutant can theoretically get lucky and mutate ears and tails without anything else which has the same positive effect as having the Pretty trait in terms of appearance.

**Comment by Shibimon** [comment]
> > We've also got other -ugly mutations throughout the system which are intended to convey that things such as gigantic butterfly wings are objectively beautiful even if they're coming out of a Brundlefly.
> 
> If other mutations are wrong they should get fixed ( could also happen in this PR), but they don't serve as a justification to have more wrong mutations. Maybe we should put down some notes in the design doc(?) to pin down what uglyness is supposed to be, and what is supposed to be ugly/beautiful in the context of mutations. Otherwise it's going to be a similar mess to FANCY

Lots of mutations won't fit the "body-horror theme" and it's bold to think -ugly mutations are plain "wrong" im sure when they got added to the game people that implemented them knew what was doing.
I don't endorse them but feel this PR has a bit of anti-furry taste.

**Review by kevingranade — APPROVED** [review]
This is going in the right direction,  more inhuman implies more ugly.

**Pull request merged**
