### PR TITLE
Slight concrete mixer description change

### PR DESCRIPTION
**Pull request by Cyrano7**
Going with @Rivet-the-Zombie suggestion for concrete mixer description.
Edit: The PR https://github.com/CleverRaven/Cataclysm-DDA/pull/16067

### CODE REVIEW

**Comment by mugling** [comment]
Can you link to the previous discussion? Concrete mixers are not portable at all. If anything we should be moving towards forbidding the player carrying large object (especially tools like this, engines etc) in favor of having to build a transport sled or dragging them

**Comment by Cyrano7** [comment]
Both definitions work. Its a matter of preference really. Luggable is a very uncommon word. Even chrome is complaining that its a typo on my browser.
Portable: "being a lighter and smaller version than usual"
Luggable: "portable but only with difficulty"

**Comment by mugling** [comment]
"A bulky concrete mixer.  It is large and heavy, but can still be operated solo, and runs on batteries.  It also has a heater built in."

**Comment by Cyrano7** [comment]
@mugling Concrete mixers come in different sizes and I have seen some smaller ones. Even if its small it probably needs to be heavier. Its only 4.5x heavier then the coffeemaker at the moment. This was more for clarity.

**Comment by Cyrano7** [comment]
@mugling What do you think about "A bulky concrete mixer.  It is large and heavy but can still be operated solo. Runs on batteries and has a built in heater."

**Comment by mugling** [comment]
Sounds good. Bump the weight as well maybe?

**Comment by Cyrano7** [comment]
@mugling I might double back at some point and make some adjustments to the concrete mixer and some of the other big tools. It would be nice to have like an unpack-able flag for things that shouldn't fit on your person to.

**Pull request merged**
