### PR TITLE
Weapon Categories: Ninjutsu

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Balance "Add weapon categories for Ninjutsu"

#### Purpose of change

Partially implements #51867.
Ninjutsu: As with Krav Maga, a long list of weapons, a pretty good candidate for weapon categories.

#### Describe the solution

| Weapon Category  | Martial Art | Includes |
| ------------- | ------------- | ------------- |
| KNIVES | Ninjutsu, Krav Maga  | All kind of knives |
| MEDIUM_SWORDS  | Ninjutsu  | Swords of 81cm - 100cm length |
| LONG_SWORDS | Ninjutsu  | Swords of 101cm length or more |
| SHORT_SWORDS | Ninjutsu  | Swords of 80cm length or less |
| QUARTERSTAVES | Ninjutsu  | Quarterstaves and similar weapons |
| BLADED_FARMING | Ninjutsu  | Bladed farming tools and the machetes |
| CLAWS | Ninjutsu  | Bionic and Tiger claws |

The KNIVES category is already used by Krav Maga, the only additional knife added in this PR was the Kirpan (Already in use by the weapon list of Ninjutsu, but was lacking in the Krav Maga list).

6 new weapon categories:
- MEDIUM_SWORDS
Katana - And any normal sized sword such as a Broadsword
- LONG_SWORDS
Nodachi - And any larger that average sword such as a Longsword 
- SHORT_SWORDS 
Wakizashi - And any sort of short sword like the Xiphos
- QUARTERSTAVES
All variations of quarterstaves
- BLADED_FARMING
The sickle and other farming or similar tools (Machetes included in here)
- CLAWS
The tiger and bionic claws (Bionic claws were already in the style)

All the style weapons of Ninjutsu belong to one of these 7, as laid out (kinda) in the martial arts rebalance in #34135.

Edit: Shillelaghs changed to "BATONS" category as suggested in comments.
Edit 2: The Monomolecular Blade was removed from Ninjutsu as suggested in the comments.

#### Describe alternatives you've considered

Maybe unify the sword categories in one "SWORDS" category, but its too broad and I'm still going to look at the other styles.

#### Testing

New debug world, starting with Ninjutsu learned, debug spawn a Katana and its variations, the martial art works with it.
Proved with some of the other weapons too.

#### Additional context

<details>
<summary>Images</summary>

No more style weapons list:
imagen

Katana:
imagen

Some other weapons:
imagen
imagen
imagen

</details>

Eskrima is next, it should be way easier with KNIVES, CLAWS and BATONS already implemented.

**There needs to be a way to display the categories in the martial art info menu.**

### CODE REVIEW

**Comment by Rabidweasel** [comment]
I'm not hugely familiar with how such weapons are used in practice, but should the shillelah and loaded stick really be bundled in with quarterstaves? They're considerably shorter and I believe usually used 1-handed rather than 2-handed.

They could be in their own weapon category (short staves?) or bundled along with batons (I think most styles which use batons also use the shillelah already?)

**Comment by Termineitor244** [comment]
> 
> 
> I'm not hugely familiar with how such weapons are used in practice, but should the shillelah and loaded stick really be bundled in with quarterstaves? They're considerably shorter and I believe usually used 1-handed rather than 2-handed.
> 
> They could be in their own weapon category (short staves?) or bundled along with batons (I think most styles which use batons also use the shillelah already?)

Hmmmm now that you say it, the shillelagh (and all its variations) are indeed shorter than the quarterstaves, the styles that use batons are Silat, Eskrima and Krav Maga, only Krav Maga lacking these weapons in their (now defunct) list.

I will add this weapons to the "BATONS" category, Ninjutsu would not be able to use them anymore, but if they are batons then it would make sense.

Thanks for the suggestions!

Note: What is the difference between a baton and a quarterstaff? In the main game, the only martial arts in which this matters are Krav Maga (Only uses batons) and Ninjutsu (Only uses Quarterstaves), the rest use batons AND quarterstaves.

**Comment by Maleclypse** [comment]
I think due to the wrist blade's unique lack of wrist motions it should be limited to fictional arts such as the bionic combatives or kuntz-thingy.   Or any existing martial arts that focus on a blade/hook in place of a hand.  Otherwise this looked good to go.

**Comment by Termineitor244** [comment]
>  Or any existing martial arts that focus on a blade/hook in place of a hand

Yeah, I checked, I don't think we have any, it will have to remain as a bionic only weapon (Biojutsu and the Panzer martial arts).

It was originally added to Ninjutsu because of the theme of "Assassination weapon", I added its category after thinking much about it because I just couldn't think of how to justify its addition...

I will delete its category as "WRIST_BLADE" (Since it would be unused) and add a "BIONIC_WEAPONRY" category when I pass over Biojutsu in a later PR.

**Pull request merged**
