### PR TITLE
Fix UPS armors again

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary

`SUMMARY: Bugfixes "player: simplify UPS processing in process_items"`

#### Purpose of change
UPS-modded items don't function.
`player::process_items` hardcodes some functionality for `FB51 optical cloaks` and `power armor`
Only one each `FB51 optical cloak` and `power armor` can function at a time

Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/42349

#### Describe the solution

- [x] Fix UPS-modded items
- [x] Un-hardcode `FB51 optical cloak` from `player::process_items`
- [x] Un-hardcode power armors
- [x] Fix `Power Armor Interface` cbms
~~- [ ] Fix power draw from `Internal Unified Power System`~~ I had debug mutations on...
~~- [ ] Remove or deprecate `ups_based_armor`~~ slightly out of scope

#### Describe alternatives you've considered
Adding a battery well to UPS conversion mod and leaving the rest as it is: we can do better

#### Testing
for item in `headlamp (ups)` `FB51 optical cloak` `combat exoskeleton` `heavy combat exoskeleton` `field combat exoskeleton`; do
1. Check that $item turns on and draws power from UPS.
2. Check that $item can be turned off and stops drawing power from UPS
3. Check that $item turns off when UPS runs out of charges, or gets unloaded, or dropped
4. Repeat 1-3 but with an `Internal Unified Power System` instead of an UPS item
5. if $item is a power armor, verify that it works with a `BIONIC_ARMOR_INT` CBM as well

; done

#### Additional context
I had to change power armors to `TOOL_ARMOR` for `power_draw` to work. Changing/fixing that is out of scope for this PR

### CODE REVIEW

**Comment by andrei8l** [comment]
It turns out that both `Internal Unified Power System` and `Power Armor Interface` are currently broken and don't draw power from bionic banks. I'll look at fixing the internal UPS tomorrow and maybe leave the interface for another PR.

In the meantime, I'd still appreciate reviews and testing for the changes so far.

**Comment by andrei8l** [comment]
What is wrong with PR validator? Did it spam it with too many description changes?

**Comment by anothersimulacrum** [comment]
No clue, your summary is valid anyways.

**Comment by kevingranade** [comment]
It's a github actions issue, the old values never disappear.

**Pull request merged**
