### PR TITLE
Minor generic zombie balance edits

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Weirdness caught during the creation of #71170 that I was advised to PR separately for the ease of reviewing

#### Describe the solution
- Removed dodge from the resort dancer zombie, since just because they were dancers they would not be better at dodging
- Lowered the acidic zombie's speed and took away its dodge to match baseline zombies
- Removed the waif's armor and ``HARDTOSHOOT``. It's an emaciated kid, it's not particularly fast. It wouldn't be terribly hard to shoot, nor would it be armored
- Took away the guilt for killing shrieklings since they're "heavily mutated" according to the description
- Gave the Grue actual morale because it had 0
- Gave the Screecher ``SMELLS``, because it had scents defined and ``KEENNOSE``
- Removed the ability for the ocular zombie to prioritize targets and avoid danger. Our zombies don't waltz into traps because they don't seee them - they do because they don't have the mental capacity to care about getting hurt.
- Upped the malicious mane's HP to be the same as default zombie. No idea why it was weaker in that regard
- Upped miner's and technician's morale to 100 from 70 and removed their dodging skills

#### Describe alternatives you've considered
The only balance-affecting changes I didn't port from the copy-from PR are adding more attacks for kids and changing sizes for kids and fat zombies - the latter shouldn't have enough of a balance effect to matter and is only possible with ``copy-from``, whereas the former would be a pain to do manually.

#### Additional context
At the moment the copy-from PR has these changes as well - I'll take care of that when this one is merged

### CODE REVIEW

**Comment by RenechCDDA** [comment]
>Removed the ability for the ocular zombie to prioritize targets and avoid danger. Our zombies don't waltz into traps because they don't seee them - they do because they don't have the mental capacity to care about getting hurt.

I don't see anything (in the JSON or PR adding it) claiming its ability to pathfind and avoid traps is due to its eyesight. 

It is a rare, "fatally dangerous" (*diff 120*) zombie which only seems to appear by being upgraded by a zombie master. Other threats, with even less mental capacity (e.g. skittering amalgamation which is something as small as a reanimated cat) have PATH_AVOID_DANGER_2. Why not this zombie? It is an appropriate level of danger for it.

**Comment by Karol1223** [comment]
>It is a rare, "fatally dangerous" (diff 120) zombie which only seems to appear by being upgraded by a zombie master. Other threats, with even less mental capacity (e.g. skittering amalgamation which is something as small as a reanimated cat) have PATH_AVOID_DANGER_2. Why not this zombie? It is an appropriate level of danger for it.

It's all about the intelligence. Normal run of the mill zombies don't have the intelligence and self preservation to care about their wellbeing - amalgamations already do (whether they should is a different topic). On top of that, the difficulty is heavily skewed due to it's 7 melee skill which, again, it for some reason has due to... having more eyes? Yet it has only 90 health, which means it's easier to take down than a brute.

I don't see why a zombie that grows more eyes suddenly would get the mental capacity to care about it getting hurt, nor frankly why it'd suddenly get 7 melee skill but the latter is more than I'm willing to change.

**Comment by RenechCDDA** [comment]
> On top of that, the difficulty is heavily skewed due to it's 7 melee skill

Melee skill is not even the biggest contributor. When you say things like this and don't even bother to check or understand, it reflects poorly on you. Here's actually doing the math, by hand, no compiling or anything you don't have access to.
(step 1)
`( mon.melee_skill + 1 ) * mon.melee_dice * ( melee_dmg_total + mon.melee_sides ) * 0.04 + ( mon.sk_dodge + 1 ) * armor_diff * 0.04 + ( mon.difficulty_base + mon.special_attacks.size() + 8 * mon.emit_fields.size() );`
which reduces to...
`( 7 + 1 ) * 2 * ( 7 ) * 0.04 + ( 7 + 1 ) * 15.9 * 0.04 + ( 0 + 2 + 8 * 0 ) == 11.568`
(dropping melee skill to 1 at this point is only a loss of 3.36 difficulty, or about 29%)

(step 2)
`*= ( mon.hp + mon.speed - mon.attack_cost + ( mon.morale + mon.agro ) * 0.1 ) * 0.01 + ( mon.vision_day + 2 * mon.vision_night ) * 0.01`
which reduces to...
`*= ( 90 + 80 - 100 + ( 100 + 100 ) * 0.1 ) * 0.01 + ( 1000 + 2 * 1 ) * 0.01`
which *further* reduces to...
`*= 10.92`
`11.568 * 10.92 == 126.32256`
(evidently there is some truncation in there, but close enough)

**Comment by RenechCDDA** [comment]
> I don't see why a zombie that grows more eyes suddenly would get the mental capacity to care about it getting hurt, nor frankly why it'd suddenly get 7 melee skill but the latter is more than I'm willing to change.
> 
> It never is about threat level. It's about what makes sense.

What makes sense is that it is a more dangerous, evolved zombie, having been specifically evolved by a zombie master. Is is a greater threat, and as such it should be dangerous in more ways. You have *assumed* that the eyes are relevant to its ability to avoid traps. 

Here are some things that have PATH_AVOID_DANGER_1, which is lesser than the ocular, but greater than regular zombies:

-A literal chicken.

-A panicked person who is expressly hysterical (irrational).

-Armored centipede.

You have gone through the process backwards when dealing with this monster. First, you found out that you didn't like it, and then you went to change it. Only afterwards did you try to justify the change. That is not the right way to go about it.

**Comment by RenechCDDA** [comment]
Also cmon this is a conversation you participated in, re: zombie abilities.

image

Barring a Venera retcon or being overruled by a (more senior?) dev, ocular's got no reason to lose PATH_AVOID_DANGER_2.

**Comment by Karol1223** [comment]
> What makes sense is that it is a more dangerous, evolved zombie, having been specifically evolved by a zombie master. Is is a greater threat, and as such it should be dangerous in more ways. You have assumed that the eyes are relevant to its ability to avoid traps.
> You have gone through the process backwards when dealing with this monster. First, you found out that you didn't like it, and then you went to change it. Only afterwards did you try to justify the change. That is not the right way to go about it.

You say I assumed things, and then you assume what my thought process was. You're being hypocritical. No, I first intended to leave the ocular zombie as is and came back when I realised how stupid it was to have a zombie that only grew additional eyes to suddenly gain the mental capacity to discern what is or isn't dangerous to it. It doesn't even have a *mouth* anymore given the bite attack is gone, but more eyes for some reason mean that it's smart enough to prioritize targets and not walk into traps?

> Here are some things that have PATH_AVOID_DANGER_1, which is lesser than the ocular, but greater than regular zombies:
> -A literal chicken.
> -A panicked person who is expressly hysterical (irrational).
> -Armored centipede.

Are you... trying to say centipedes or chickens don't feel pain? Aren't alive? Don't care for their wellbeing? I don't see what point you're trying to make here. These are animals that feel pain and obviously are capable of predicting that jumping off a cliff or walking into fire would hurt them. Panicked person has ``PATH_AVOID_DANGER_1`` which means it won't run into fires but will still walk into traps - which seems appropriate for someone in deep constant panic that can't properly function *but still feels pain and is still human.*

> Also cmon this (https://discord.com/channels/598523535169945603/598535827169083403/1022871735705550931) is a conversation you participated in, re: zombie abilities.

And I stand by that. Smart zombies - those being necromancers and masters, which already violate most of our zombie rules - should avoid danger. I never claimed that I support adding *more* smart zombies, nor that a regular zombie which grew an excess of eyes should fall under that category.

**Comment by Nebnis** [comment]
There is a lot of subjectivity to this eye monster i feel. You could say the master is upgrading/leading its cognitive ability to see danger and avoid them like, you know, a master :P. Doesn't vigilant amalgamation makes other zombies smart enough to avoid danger too? Or maybe Venera wanted to add to it.

I'm going to take Renech side and agree it is fine for this monster since it isn't actually that tough or common to be a problem in the gameplay side. And i like the idea of coordinators zombies making the chaff feel different.

**Comment by Venera3** [comment]
I don't feel like zeds should avoid traps. Masters being weird and smart is the outlier, and personally I'm not a fan of that - weird passive blobby conduit feels more on-brand and makes you matter less.

Difficulty rating is notoriously wonk, so it's not really relevant.

**Comment by KeremBabaG** [comment]
> Removed dodge from the resort dancer zombie, since just because they were 

It's a nice gimmick, I think it should stay as it is

**Comment by Karol1223** [comment]
> It's a nice gimmick, I think it should stay as it is

It leads to things like technicians being able to pull metal because they worked with magnets, wrestlers remembering their wrestling moves etc etc, so no. Luckily we've removed those two already.

**Comment by KeremBabaG** [comment]
> > It's a nice gimmick, I think it should stay as it is
> 
> It leads to things like technicians being able to pull metal because they worked with magnets, wrestlers remembering their wrestling moves etc etc, so no. Luckily we've removed those two already.

Well those were nice gimmicks too, our zombies are fucking BORING now

**Comment by Zireael07** [comment]
> Removed dodge from the resort dancer zombie, since just because they were dancers they would not be better at dodging

Dodge was kind of the shtick of the various dancer zombies, of which the resort ones are a subtype

**Comment by carlarctg** [comment]
Hi, Ocular Zombie PRer here. That zombie isn't meant to be a master upgrade only variant, its meant to show up in normal evolution as well. Masters making super weird zombies is a cool idea but it's not what I'm going for here and it wouldn't really be very interesting to show that off with a normal-ass zombie with binoculars.

 I'm just silly and apparently forgot to add it somewhere it should be, presumably?

My idea for it was that it was a zombie with somewhat unnatural levels of perception, close to the realm of normalcy but just a tad too supernatural to be possible, like acid zombies, thorny shamblers, or hulks. That's why it can/could navigate around traps, despite being as dumb as a normal zombie, the unnatural perception steers them away. That said, my ideas for zombies seem to be more supernatural on average than what the dev team or contributors prefer, so just because that's my original intention doesn't mean it cannot be changed. I'm not particularly attached to it.

**Comment by Karol1223** [comment]
> Hi, Ocular Zombie PRer here. That zombie isn't meant to be a master upgrade only variant, its meant to show up in normal evolution as well. Masters making super weird zombies is a cool idea but it's not what I'm going for here and it wouldn't really be very interesting to show that off with a normal-ass zombie with binoculars.

> I'm just silly and apparently forgot to add it somewhere it should be, presumably?

Yeah this was really off for me that the only zombie I knew of that was exclusively a master-evolved form was mr. eye guy with basically default zombie health. I was assuming that this was a hiccup rather than intended choice, but I didn't check your PR to make sure so I opted not to change that in this PR. I could probably throw it in the default evolution group here real quick if you want me to?

> My idea for it was that it was a zombie with somewhat unnatural levels of perception, close to the realm of normalcy but just a tad too supernatural to be possible, like acid zombies, thorny shamblers, or hulks. That's why it can/could navigate around traps, despite being as dumb as a normal zombie, the unnatural perception steers them away. That said, my ideas for zombies seem to be more supernatural on average than what the dev team or contributors prefer, so just because that's my original intention doesn't mean it cannot be changed. I'm not particularly attached to it.

Thorny shamblers get the benefit of being ridden by a triffid vine while hulks... well, I don't really see how hulks are supernatural to be fair. They just grew bigger. As for acidics, I don't know the intricacies but I am pretty confident they can be explained biologically. The biggest supernatural comparison we have ingame right now, other than masters and necromancers, are shockers which are on the chopping block. All in all, supernatural zombies fit best into mods - but I will repeat what I said on discord - I do think that the body horror aspect of a zombie covered in eyes is a cool visual. Doubly so if you were to make them specifically eyes from different species (which we know zombies can achieve given batwings and snappers). In an ideal world it'd be fun to have EoCs or effects that tick back and forth where different "sets" of eyes are active and switch places. So sometimes you'd have eagle eyes that can see max vision range, sometimes you'd have cat eyes that have amazing night vision but average overall range, sometimes it'd just be default human range etc etc etc. But that's way beyond what I'm capable of.

**Comment by carlarctg** [comment]
> > Hi, Ocular Zombie PRer here. That zombie isn't meant to be a master upgrade only variant, its meant to show up in normal evolution as well. Masters making super weird zombies is a cool idea but it's not what I'm going for here and it wouldn't really be very interesting to show that off with a normal-ass zombie with binoculars.
> 
> > I'm just silly and apparently forgot to add it somewhere it should be, presumably?
> 
> Yeah this was really off for me that the only zombie I knew of that was exclusively a master-evolved form was mr. eye guy with basically default zombie health. I was assuming that this was a hiccup rather than intended choice, but I didn't check your PR to make sure so I opted not to change that in this PR. I could probably throw it in the default evolution group here real quick if you want me to?
> 
> > My idea for it was that it was a zombie with somewhat unnatural levels of perception, close to the realm of normalcy but just a tad too supernatural to be possible, like acid zombies, thorny shamblers, or hulks. That's why it can/could navigate around traps, despite being as dumb as a normal zombie, the unnatural perception steers them away. That said, my ideas for zombies seem to be more supernatural on average than what the dev team or contributors prefer, so just because that's my original intention doesn't mean it cannot be changed. I'm not particularly attached to it.
> 
> Thorny shamblers get the benefit of being ridden by a triffid vine while hulks... well, I don't really see how hulks are supernatural to be fair. They just grew bigger. As for acidics, I don't know the intricacies but I am pretty confident they can be explained biologically. The biggest supernatural comparison we have ingame right now, other than masters and necromancers, are shockers which are on the chopping block. All in all, supernatural zombies fit best into mods - but I will repeat what I said on discord - I do think that the body horror aspect of a zombie covered in eyes is a cool visual. Doubly so if you were to make them specifically eyes from different species (which we know zombies can achieve given batwings and snappers). In an ideal world it'd be fun to have EoCs or effects that tick back and forth where different "sets" of eyes are active and switch places. So sometimes you'd have eagle eyes that can see max vision range, sometimes you'd have cat eyes that have amazing night vision but average overall range, sometimes it'd just be default human range etc etc etc. But that's way beyond what I'm capable of.

Please do put it in the upgrade group! I would be very happy.

**Comment by Karol1223** [comment]
> Please do put it in the upgrade group! I would be very happy.

Nevermind. It already *is* in the default upgrade group, Renech was just wrong.

**Comment by fairyarmadillo** [comment]
@Karol1223 I have a plan for shockers that will make them mostly a portal storm/specific area thing, where they're explicitly caused by interaction with nether stuff.

**Comment by Karol1223** [comment]
> @Karol1223 I have a plan for shockers that will make them mostly a portal storm/specific area thing, where they're explicitly caused by interaction with nether stuff.

That sounds possibly way more interesting than their normalifying I heard proposed on discord, and since portals/nether don't have to abide by the real world physics you can get away with way more random bullshit in there. So yeah, I suppose we do have an avenue where supernatural zombies may fit in vanilla 🤔

**Comment by DragonWizard23** [comment]
> * Removed dodge from the resort dancer zombie, since just because they were dancers they would not be better at dodging

I just have a little comment to make about this. We can train dodge (up to level 2) from the Dance, Dance, Dance book. 
Link: [Dance Dance Dance!](https://cdda-guide.nornagon.net/item/mag_dodge)

By a similar virtue, I don't think it would be unreasonable for the dancer zombies to have level one or two dodge.

**Comment by fairyarmadillo** [comment]
Zombies do not dance. A typical zombie's fastest movement is 70% of an adult human's typical walking speed. They're clumsy and uncapable of even walking in a straight line. Being physically fit before death qualifies them to be tough zombies in the same way that being fat qualifies them to become fat zombies, but I don't think your typical exotic dancer has that kind of build (if only!).

Our zombie model is that almost everything the person had in life is lost and the blob starts with a nearly-blank canvas which it can then mutate. If you want a zombie with high evasion, it ought to be something that evolves that kind of ability after the fact, like a zombie predator.

**Comment by Karol1223** [comment]
> I just have a little comment to make about this. We can train dodge (up to level 1) from the Dance, Dance, Dance book.
Link: Dance Dance Dance!

> By a similar virtue, I don't think it would be unreasonable for the dancer zombies to have level 1 dodge.

No. Read my comments above why we don't do "zombies who were good at X in life are good at X when they're zombies".

**Pull request merged**
