### PR TITLE
[WIP] Add 2 new traits: Healthy and Unhealthy

### PR DESCRIPTION
**Pull request by fluffy-heretic**
```SUMMARY: Content "Added 2 new traits: Healthy and Unhealthy"```

Resubmitting the traits from #27381 as separate PRs.

#### Describe the solution
Healthy (1 point) multiplies all positive healthiness modifiers with 1.25 and all negative ones with 0.75.
Unhealthy (-1 point) does the same thing, but the other way around.

There are traits that give straight up boosts/maluses to all sorts of mechanics (Optimist/Bad Temper, Tough/Flimsy, Indefatigable/Languorous etc), but there's been no such thing for healthiness so far.

#### Describe alternatives you've considered
* Giving the traits to certain existing mutation lines (Plant and Chimera, respectively)?
* Changing the point costs
* Adding a flat, always-on modifier, like the one Optimist and Bad Temper have

### CODE REVIEW

**Comment by fluffy-heretic** [comment]
So it turns out this won't work very well because health and health_mod are integers.

Is there any reason not to change their type to float/double across the board? It would also make the current implementation of health decay `set_healthy_mod( round( get_healthy_mod() * 0.95f ) );` less weird.

**Comment by Vasyan2006** [comment]
> ``set_healthy_mod( round( get_healthy_mod() * 0.95f ) );``


You can use ``set_healthy_mod( roll_remainder( get_healthy_mod() * 0.95f ) );`` instead.

**Comment by kevingranade** [comment]
Your rationale doesn't hold up, just because other similar traits exist doesnt mean this one should also.

**Comment by Siersha** [comment]
I would figure that a proper rationale for the trait's existence would be somewhere along the lines of natural genetics and health. Some people are just generally healthier/unhealthier than others

**Comment by fluffy-heretic** [comment]
@Vasyan2006 Thanks for the suggestion, I changed the trait's implementation to use roll_remainder(). Might do the same for health decay but that'd be another, separate PR.

@kevingranade I might've worded that better. My reasoning wasn't "X exists so Y should exist too", it's that this is an as of yet untapped avenue of gameplay that deserves to be explored further.

Healthiness, the way it is now, is a rather abstracted, "gamey" simplification. It's a conflation of sleep quality, the strength of the immune system, nutrition, and a bunch of other innate and environmental factors. My impression was that it was *intended* to be this simplified, rather than being a placeholder for when someone gets around to fleshing it out (like how one can learn kung fu after reading for 10 minutes - that's a placeholder). I could reframe the traits as "Immunodeficiency" and "Strong Immune System", but that isn't really true to how the mechanics work.

Part of CDDA's appeal is that you can make niche builds with narrow applications and make them work for you. You can select traits that just make your character happy all the time. Or ones that let you carry lots of items. Or one that makes you glib and good at lying to people. Or eating people.

As of yet, there are no traits that really say "robust, hardy survivalist". There's Outdoorsman, but that only affects morale - you aren't *really* any better off standing in the rain all day. A better-than-average health score would have only minor benefits, it wouldn't make one better at fighting or learning, but it would make the character generally more robust in a subtle way. It has value both from a roleplaying and a gameplay perspective.

**Comment by kevingranade** [comment]
I'm going to give this a pass.
You can't rely on these traits to have any impact at all. AFAICT you still need to at least try to eat a bit healthy and avoid drugs to avoid tanking your health stat, neither of these traits changes that.

**Pull request closed without merging**
