### PR TITLE
Climate control in vehicle only if engine is on

### LINKED ISSUE #50297: Vehicles reset body temperature to 0, even without any sort of AC system
### Describe the bug

Inside vehicles your body temperature is always 0 (comfortable), no matter the clothing or the weather outside.

### Steps To Reproduce

1. Make a character of a profession that starts with a vehicle.
2. Enter the vehicle.
3. Walk around a bit, perhaps take control of it.
4. Press @ to check temperature.

### Expected behavior

For all vehicles (even custom-built carts) to not have a magical AC system that takes no power or anything.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: f40b533 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    No Fungal Monsters [No_Fungi]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary
Bugfixes "Climate control in vehicle even when engine is off "

#### Purpose of change
Fixes #50297

Climate control was enabled in vehicles even with the engine off. This just ensures that the engine is running before enabling climate control.

#### Describe the solution

Changed the test condition to check if a non muscle-powered engine is on instead of checking for available engine power. Also allows climate control if there is an alternator providing power, for example with muscle power.

#### Testing

Tested with car, solar  car, and stagecoach with horse. Climate control only works now when the engine is on.

### CODE REVIEW

**Comment by chrispikula** [comment]
This doesn't effect the mountable_heater and mountable_cooler, right?  Sometimes I _want_ those to run even though the engine is off.

**Comment by anothersimulacrum** [comment]
Those function separately, yes.

**Comment by Qrox** [comment]
AFAIK muscle power is also counted as "engine" so that might need to be excluded.

And maybe it should check there's electric power and (maybe in a later PR) a running air-conditioning part instead. (So you can create an air-conditioned vehicle where you generate electric power with foot pedals to power an air-conditioner.)

**Comment by RoyBerube** [comment]
@Qrox I'll change it to check that it is not muscle or animal power, and add a check for a working alternator as well.

**Pull request merged**
