### PR TITLE
LIXA 2: Son of LIXA

### PR DESCRIPTION
**Pull request by DPavonis**
#### Summary
Content "Adds the Laser Interferometer eXodimensional resonance Assay as a new minidungeon"

#### Purpose of change

#67429  seems to be dead in the water, but there was interest in getting it fixed up and in the game, so I've been working on that. 

#### Describe the solution

Stared at the JSON for several hours, made some changes here and there to make the thing actually work as intended (or at least as near as I can figure).

#### Describe alternatives you've considered

~~Let someone more competent handle it.~~

#### Testing

So far all my development has been in the form of a mod, this PR is the first attempt at integrating LIXA with mainline. So uh, I might actually want to test that.

#### Additional context

TODO:

~~- Find beta testers to get some new eyes on the combat encounter.~~
~~- Figure out what the congealed light terrain emitter problem actually is.~~
~~- Figure out an appropriate reward for the whole shebang. (RM13 or phase immersion suit?)~~
~~- Figure out a signposting method so players will be able to find the dungeon more easily. (Probably for a follow-on PR, something for Hub 01 and/or the Hub 01/Exodii rivalry?)~~
~~- Make sure to remove the roof on the personnel elevator.~~

<details> <summary>Let's go on a tour of the LIXA facility!</summary>

1_entrance

</details>

<details> <summary>... Typical fencepost security. </summary>

2_walk_up

</details>

<details> <summary>This entrance looks slightly more secure. </summary>

3_front_entrance

</details>

<details> <summary>We're in! Luckily the foot entrance was conveniently unlocked.</summary>

4_aboveground

</details>

<details> <summary>Say hi to LIXA's friendly and helpful support personnel.</summary>

5_helpful_LIXA_personnel

</details>

<details> <summary>Behold the closest thing we'll ever get to a Super Mario 64 painting in the cataclysm.  </summary>

6_super_mario_64_painting

</details>

<details> <summary>Ooooh, spooky endless corridor.</summary>

7_endless_corridor

</details>

<details> <summary>What has science dooooooone!?</summary>

8_angry_ghosts

</details>

<details> <summary>Let me assure you that what looks like boomer bile is actually congealed light, and should not be touched if you value your health.</summary>

9_congealed_light

</details>

<details> <summary>Nobody ever taught these people that spitting is rude.</summary>

10_spitting_is_rude

</details>

<details> <summary>Some of the eigenspecters have figured out a real-life dupe glitch.</summary>

11_dupe_glitch

</details>

<details> <summary>Look at this absolute unit.</summary>

12_absolute_unit
</details>

<details> <summary>Big boss time! Kill this thing to escape the endless corridor!</summary>

13_big_boss

</details>

<details> <summary>Freeeeeeeeeedom! </summary>

14_freedom

</details>

<details> <summary>Uwu, *[notices ID cards on the ground]* </summary>

15_uwu_wuts_dis

</details>

<details> <summary>Those ID cards unlock the prize depository!</summary>

16_phat_loot

</details>

<details> <summary>Sweet fresh air how I missed thee!</summary>

17_escape_tunnel

</details>

### CODE REVIEW

**Comment by DPavonis** [comment]
Going to just leave this comment here to put a few thoughts down:
Rather than an artifact, I'm leaning towards either an RM13 or phase immersion suit (both? RM13 for military, PIM for the nerd herd?) as I'm of the opinion an artifact would be a disappointing reward for what I'd like to think is a cool setpiece.

To get the PIM or RM13 I'm leaning towards one of the keycards at the end allowing access to a small equipment lockup, though this does have the "issue" that a reasonably well-equipped survivor could just brute-force their way into the lockup and just bypass the encounter altogether, but eh, such is life, such is Cataclysm.

**Comment by lapis413** [comment]
I remember reading the original and loving the idea, glad someone has revived it! I agree an artifact is a bad idea, they're too janky and inconsistent for a good reward. I'm not certain about the other ideas though; the PIM is already a guaranteed drop from a lab type, and RM13 doesn't make a whole lot of sense for the location (and who knows if it should even still be in the game).

I'm not sure if there's any other pre-existing item that makes sense, so I wonder if it deserves its own rewards. I'm unfortunately not entirely sure what they should be, but I like the idea of a military-type reward and a sciencey reward for doing all this.

**Comment by DPavonis** [comment]
> I remember reading the original and loving the idea, glad someone has revived it! I agree an artifact is a bad idea, they're too janky and inconsistent for a good reward. I'm not certain about the other ideas though; the PIM is already a guaranteed drop from a lab type, and RM13 doesn't make a whole lot of sense for the location (and who knows if it should even still be in the game).
> 
> I'm not sure if there's any other pre-existing item that makes sense, so I wonder if it deserves its own rewards. I'm unfortunately not entirely sure what they should be, but I like the idea of a military-type reward and a sciencey reward for doing all this.

Fair enough. I'm already aware of the guaranteed PIM drop from the ghost fight in the physics department, but unless you already have meta knowledge about it, I could very easily see players never finding the ghost fight and that guaranteed PIM drop. Hell, *I* didn't know about the ghost fight for the longest time despite having walked right by it who knows how many times. With a Hub and/or Exodii mission pointing the way to LIXA, this could be a guaranteed way for the player to pick them up. Ultimately I guess this is a long-winded way of saying a little bit of redundancy isn't necessarily a bad thing.

As for justifications I could easily see XEDRA issuing some for use at LIXA and the RM13 for use by any soldiers guarding the nerd herd during Happy Portal Fun Times™, just by the time the player gets there, there's only one of each left. Or something, idk.

**Comment by BlizzDA** [comment]
>Rather than an artifact, I'm leaning towards either an RM13 or phase immersion suit (both? RM13 for military, PIM for the nerd herd?) as I'm of the opinion an artifact would be a disappointing reward for what I'd like to think is a cool setpiece.
>---
>I'm leaning towards one of the keycards at the end allowing access to a small equipment lockup, though this does have the "issue" that a reasonably well-equipped survivor could just brute-force their way into the lockup and just bypass the encounter altogether, but eh, such is life, such is Cataclysm.
I concur that the two armors seem like fine rewards, since a player might not always get to reach the other spawns in their run. Brute-forcing is always going to be a possibility for most mapgens, so I wouldn't worry about that. TCL has it as well, and if anything happens to cardreaders you aren't locked out of the rest of the dungeon. 

As for treasure; Alternatively, those two gear pieces could randomly spawn as a 'mundane' loot option along with a dungeon-specific reward? Going through the PR, a thematic reward could be potable 'liquid/congealed Light' as it shows up throughout the dungeon a lot. Giving you a finite (or slowly replenishing) resource for utility lighting or very strange Molotovs? 

Could also serve as the future mission objective. Survivor brings a sample back to HUB01 and they're all 'we're gonna science this thing', while Rubik is delighted the Exodii now doesn't need to spend much power on interior lighting. Highlighting the differences between the factions.

**Comment by DPavonis** [comment]
> I concur that the two armors seem like fine rewards, since a player might not always get to reach the other spawns in their run. Brute-forcing is always going to be a possibility for most mapgens, so I wouldn't worry about that. TCL has it as well, and if anything happens to cardreaders you aren't locked out of the rest of the dungeon.

Yeah, I'm not overly worried about a player brute-forcing their way into the lockup, it was just a stray thought that occurred while working on it.

> As for treasure; Alternatively, those two gear pieces could randomly spawn as a 'mundane' loot option along with a dungeon-specific reward? Going through the PR, a thematic reward could be potable 'liquid/congealed Light' as it shows up throughout the dungeon a lot. Giving you a finite (or slowly replenishing) resource for utility lighting or very strange Molotovs?
> 
> Could also serve as the future mission objective. Survivor brings a sample back to HUB01 and they're all 'we're gonna science this thing', while Rubik is delighted the Exodii now doesn't need to spend much power on interior lighting. Highlighting the differences between the factions.

The idea of congealed light somehow being a thematic reward/macguffin for the Hub and/or Exodii is a really good one and I'm probably going to make use of it in some capacity.

That said I'm iffy on the Exodii using it as a light source. I suspect the amount of energy they're expending on lighting is pretty minimal compared to other things like charging the various worker and quadruped chassis, not to mention that it probably takes quite a bit of juice to operate whatever their dimension-hopping tech is. They *might* be open to using it as a weapon like you alluded to the player using. Maybe. I'd want a second opinion from someone higher up on the food chain before putting in the work.

Hub would totally want to science the shit out of it though.

**Comment by Maleclypse** [comment]
I'm going to compile and test this location tonight if I get a chance but can you add screenshots to the additional context section.  If you can make them hideable and unhideable that would be awesome.  Someone on discord can tell you how to do it.

**Comment by DPavonis** [comment]
> I'm going to compile and test this location tonight if I get a chance but can you add screenshots to the additional context section. If you can make them hideable and unhideable that would be awesome. Someone on discord can tell you how to do it.

Will do once I'm able

**Pull request merged**
