### PR TITLE
Remove morale penalty after washing if filthy item was worn whilst washing it

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Sorry for not testing thoroughfully.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That's still not the proper fix. This one will break FANCY items when they're also filthy.

The proper fix would be to call `on_takeoff` before washing and then `on_worn` after.

**Comment by Night-Pryanik** [comment]
`On_worn`?

**Comment by Coolthulhu** [comment]
on_wear

**Comment by Night-Pryanik** [comment]
Like this?
```
mod.on_takeoff(g->u);
mod.item_tags.erase( "FILTHY" );
mod.on_wear(g->u);
```

**Comment by Coolthulhu** [comment]
Yeah, could work.

It will scramble sideness, but `on_takeoff` alone (without `on_wear`) would mess it up even harder.

**Comment by Night-Pryanik** [comment]
I'm curious - does `on_item_takeoff` differs from `on_takeoff`?

**Comment by Coolthulhu** [comment]
> I'm curious - does on_item_takeoff differs from on_takeoff?

You want to call the item's method, so `on_takeoff`. It will then call the `on_item_takeoff` of the character wearing it.

**Comment by Coolthulhu** [comment]
Something is horribly wrong with filthy morale penalty, though it's unlikely to be caused by this PR:
* Remove all clothing
* Wear a filthy windbreaker (-32 morale)
* Wear filthy shorts (penalty drops to -22)
* Washing or removing the shorts increases the penalty back to -32

**Pull request merged**
