### PR TITLE
Add ability to cause some foods to incur nausea

### PR DESCRIPTION
**Pull request by Saelfen**
#### Summary
Content "Add ability to cause some foods to incur nausea"

#### Purpose of change
Follow up on #49758. Add ability to give barely edible foods the nausea debuff effect.

#### Describe the solution
Repurpose `BLECH`, the `use_action` involved in drinking bleach, to also handle the consumption of non-corrosive consumables. Chemicals that can deal severe internal damage when digested were given the `ACID` flag in order to fall under the current use case. This is acid not in chemical terms but in terms of physical corrosiveness. 

Additionally, Nausea effect was given a mini-rework. Before, Nausea had a base `vomit_chance` of 60, but with increasing intensity in multiples of 5 up to 3 times. This meant a chance to vomit of 1/12 (5/60) on intensity 1, 1/6 on intensity 2, and 1/4 on intesity 3. Per turn. This effectively guaranteed the player will vomit even on intensity 1 if they had any stomach contents.

New Nausea now has 5 intensities with names shown below along with their chance not to vomit within their 3-minute timeframe of intensity. It is important to note, higher intensity levels fall into their lower intensity once their 3-minute cap is over. The chance to vomit is intensity / 500 per turn.

Slightly Nauseous: ~70% not to vomit
Mildly Nauseous: ~49%
Nauseous: ~34%
Very Nauseous: ~24%
Extremely Nauseous: ~16% (Duration may be higher than 15 minutes, in which case chance not to vomit is even lower).

Currently, only drinking straight cooking oil would incur a nausea penalty of increasing intensity. Adding it to other food items only needs the addition of the BLECH use_action

#### Describe alternatives you've considered
Change `BLECH` and some other consumable `use_action` into flags

#### Testing
Become nauseous, debug to check expected probabilities and confirm they are as expected.

### CODE REVIEW

**Comment by Zeropol** [comment]
> Repurpose `BLECH`, the `use_action` involved in drinking bleach, to also handle the consumption of non-corrosive consumables. Chemicals that can deal severe internal damage when digested were given the `ACID` flag in order to fall under the current use case. This is acid not in chemical terms but in terms of physical corrosiveness.

Why don't name the flag `CORROSIVE` instead of `ACID` ? I know you said it is not in a chemical sense but it can bring confusion to have items such as bleach to be flagged acid. It is possible someone reuse the flag for a chemical purpose, and it will lead to weirdness.

Bleach bottles have the corrosive pictogram, so have the bottles of acids, so it wont confuse anyone.

Bottle of bleach
label bottle of bleach

Bottle of thioglycolic acid
label bottle acid

I don't want to be fussy, it's just that the contributors won't necessarily know you used acid in a non-chemical sense when they'll see the flag.

In all cases, it can be of use to put this new flag in `flags.json` so we know what it does without searching for this PR or ramming through the code.

**Comment by Venera3** [comment]
This doesn't actually scale as is, intensity on its own only influences the name and description of the effect in the @ menu. If you want the vomit chance to increase with intensity you need to include a `scaling_mod` array with whatever you want to increment vomit chance with per intensity, in your case 1.

**Comment by AccountAlias** [comment]
@Zeropol The `BLECH` method was simply repurposed to slightly more generic to apply also to nausea inducing foods. The `ACID` flag was there prior, and so I used it since bleach/ammonia fell into the `BLECH` category previously. Adding a new flag that does exactly the same purpose just for naming convention just doesn't make sense to me

@Venera3 yes it definitely does scale as shown below. Nausea in particular did not look to be using the scaling effects previously, and it's in large part due to its interaction with `vomit_multiplier` from certain traits such as `strong stomach`. The vomit chance on display, in this case, will be the denominator, so doing a `scaling_mod` wouldn't work as well since it would not be "scaling" properly (1/500, 2/500, 3/500 etc... vs 1/500, 1/450, 1/400). Also, `scaling_mod` would end up disregarding `vomit_multiplier`.

`Activated()` in `effect.cpp`
image

Where mod is defined by `vomit_mod()` by grabbing the current intensity of nausea
image

Call to vomit actually vomit in `process_one_effect()`:
image

**Comment by actual-nh** [comment]
I'm looking at some improvements in handling acid zombies; it would be vastly preferable if ACID were to mean just acid, not anything else.

**Comment by Venera3** [comment]
> 
> @Venera3 yes it definitely does scale as shown below. Nausea in particular did not look to be using the scaling effects 

Oh my, undocumented hardcoded interactions in the effect code, there's a surprise. Nice catch, would you mind updating the effect docs? This also explains why weakening poison's throwup effect seemed overtuned (it kinda scales to 100 intensity...).

**Comment by actual-nh** [comment]
Thanks for adding the CORROSIVE flag; much appreciated!

**Comment by AccountAlias** [comment]
Added `Corrosive` flag and use that instead of `Acid` for the previously aforementioned comestibles. consuming acids is mitigated by acid blood and acid immune just as prior, but consuming corrosive will be struck with penalties regardless of trait combination. Documentation has been updated to reflect the new flag as well as the previously undocumented hardcoded vomit interaction

**Comment by I-am-Erk** [comment]
This is such a cool addition it makes me wanna puke

**Pull request merged**
