### PR TITLE
Food morale changes

### PR DESCRIPTION
**Pull request by Coolthulhu**
Buffs:
- Doubled time for food morale (to 2 hours, 1 hour before decay starts)
- Doubled maximum bonus from hot food
- Made hot food morale bonus scale with nutrition, though currently low-capped at 5, meaning it may be redundant
- Hot food now also increases morale buff time by 50%

Nerfs:
- Decreased morale stacking - caps at `3*fun` now (was `*4`). This also fixes a minor issue where you could increase the bonus from cold vodka by chasing it down with a sip of warm vodka
- Decreased morale stacking from gourmand to 150% of base maximum

Note that the above effects also affect drugs.

Morale from food is fundamentally flawed in that you can eat 3 brands of potato chips and get 3 stacking bonuses, but I don't have a simple fix for that.

### CODE REVIEW

**Comment by Voskhod-1** [comment]
3 hours would probably be better than 2 hours for the time it takes to start decaying. Consider things in terms of "three square meals a day". If it takes 3 hours to begin decaying and 1-2 hours to fully decay, that would total about 4-5 hours of total morale bonus, multiplied by 3 meals a day equals 12-15 hours. Which is about the time spent every day not resting/sleeping.

**Comment by pisskop** [comment]
> Doubled time for food morale (to 2 hours, 1 hour before decay starts)

does this affect books or music or vibrators?

**Comment by Coolthulhu** [comment]
> does this affect books or music or vibrators?

No, just the things you can take with 'E'at command.

> 3 hours would probably be better than 2 hours for the time it takes to start decaying.

Could be. I went with 2 to start slow, but I don't see a good reason not to bump it higher.
Though it may be interesting to make it start decaying fast, but then decay slowly.

**Comment by Voskhod-1** [comment]
If it includes anything consumed by the Eat command does that include most drugs?

**Pull request merged**
