### PR TITLE
enable coveralls support.

### PR DESCRIPTION
**Pull request by kevingranade**
code coverage woo.

### CODE REVIEW

**Comment by Leland** [comment]
Dang, CDDA's getting all professional. Very cool.

**Comment by kevingranade** [comment]
cept its broken lol.

**Comment by kevingranade** [comment]
Wow 21%, wish that was accurate : D
It's not scaling it properly because it's not finding he source files.

**Comment by kevingranade** [comment]
Wow... actually it kind of looks like that's accurate, sweet.

**Comment by BrettDong** [comment]
What does the 22% mean? Is it  measured by running all unit tests? Or something else?

**Comment by kevingranade** [comment]
It's based on the currently enabled unit tests that always run.
The 22% is something like number of lines of code executed / total number
of executable statements.  FYI the actual numbers are around 22,000 /
100,000.

**Comment by Leland** [comment]
Wow, >1/5 of the code is covered by unit tests? That's fantastic

**Pull request merged**
