### PR TITLE
Rebalanced some item groups

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Added the LACP laser pistol as a rare improvised pistol spawn; moved briefcase smg to smg_milspec; and moved the automatic TEC-9 to smg_obscure.

The briefcase SMG could've been used by a spy or thief, the TEC-9 wasn't ever manufactured as an automatic-only weapon outside of Hollywood, and the LACP is way more interesting as a homemade weapon.

### CODE REVIEW

**Comment by mugling** [comment]
> The briefcase SMG could've been used by a spy or thief

It should just be dropped - it's an entirely useless item.

> the TEC-9 wasn't ever manufactured as an automatic-only weapon outside of Hollywood

That argument has been done before. It actually has a niche (fits in small holsters) so should stay in the existing group

> Added the LACP laser pistol as a rare improvised pistol spawn

Which is going to show up in some odd places now.

Sorry to say I think all of these are regressions

**Comment by BorkBorkGoesTheCode** [comment]
>It should just be dropped - it's an entirely useless item.

It can use improvised magazines, it can use many types of ammo through ammo conversion, and it has a 3-round burst.

**Comment by mugling** [comment]
> It should just be dropped - it's an entirely useless item.
> 
> It can use improvised magazines, it can use many types of ammo through ammo conversion, and it has a 3-round burst.

How does that differ from the sten though?

**Comment by BorkBorkGoesTheCode** [comment]
The sten can only shoot 3 rounds at a time, no more no less; the briefcase can shoot semiautomatic and 5-round bursts, allowing greater potential damage. 

The briefcase smg has greater durability than the sten, and it counts as FANCY clothing when worn, unless a bug prevents it.

**Comment by mugling** [comment]
None of those are a significant advantage especially considering that milspec are rare drops that usually involve considerable player risk to acquire. Player frustration would likely be high upon discovering the reward is the suitcase

**Comment by BorkBorkGoesTheCode** [comment]
You have a point.

**Pull request closed without merging**
