### PR TITLE
Mirror ( Hand Mirror ) Recipe change.

### PR DESCRIPTION
**Pull request by Dozed12**
Adds ability to use 2 chunks of steel instead of silver when making the mirror ( Hand Mirror ).

Its frequent for me to a point in the game in which have almost anything but few or no silver at all, I think it makes sense to be able to make a mirror with chunks of steel ( 2 may be too few ... )

### CODE REVIEW

**Comment by kevingranade** [comment]
Historically tin/mercury and silver were used, modern processes use
aluminum, steel AFAICT is right out.

**Comment by Dozed12** [comment]
What do you think of using an aluminium\tin can?

**Comment by kevingranade** [comment]
Make a recipe that properly represents evaporating the aluminum in a vacuum
chamber and feel free.

**Comment by Dozed12** [comment]
But I also have to add aluminium as an item, and said tools to obtain it from cans right?

Also I kinda like the idea of using an empty aluminium can straight forward as a "container" for the mirror.

**Comment by i2amroy** [comment]
FWIW you can polish stainless steel to a mirror finish fairly easily (Assuming you have a deburring/polishing machine), it's used in a lot of places where you want your mirror to get scratched if something hits it instead of shattering, such as hotels, schools, even things like [art](http://d2n4wb9orp1vta.cloudfront.net/resources/images/cdn/cms/PF_0113_MECH_Mirror_Stainless_2.gif) or [business signs](http://supersignletter.com/upload/pic/20111214170700889.jpg).

**Comment by Dozed12** [comment]
I like that, I think I'll try to make a polisher running on batteries, add it so it spawns on garages and what not and add a recipie to make a mirror using the polisher and some chunks or lumps of steel.

I took a look at it and it seems easy to make an item that uses batteries using json but I might need help with spawning as I never touched that.

Should I close PR and make a new one with all the stuff when I'm done?

**Comment by John-Candlebury** [comment]
At that point wouldn't it be easier to just loot mirrors though?

Although I'm sure that you could find more uses for polisher.

**Comment by Dozed12** [comment]
I want a solid crafting alternative to silver. And yes plenty of more future uses.

**Comment by KA101** [comment]
Yeah, closing this in favor of the polisher PR.

**Pull request closed without merging**
