### PR TITLE
Fixes and updates for laser sight gunmods.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Tweaks the their stats to make the underbarrel model competitive with
the rail one. No more volume with slightly faster speed/lower
weight/better accuracy than the rail version, since you're sacrificing a
versatile weapon mount point in order to use it.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
"aim_speed" is negative.
Should probably be named "aim_cost".

**Comment by Rivet-the-Zombie** [comment]
So they should list negative values in order to reduce time spent aiming?

As far as I could tell, the gun wants to take the lowest ````aim_speed```` variable it has available in most cases - whether from itself, or from an attached mod.

What am I missing here?

**Comment by Coolthulhu** [comment]
> So they should list negative values in order to reduce time spent aiming?

Negative would probably not work well. I was just under the impression you wanted to make them faster than they currently are (by increasing aim_speed). If not, then it's fine.

**Comment by Rivet-the-Zombie** [comment]
No, I changed the zeros to one and two because an ````aim_speed```` of zero doesn't seem to actually do anything.

**Pull request merged**
