### PR TITLE
fix furniture reloading with multiple ammo types

### LINKED ISSUE #68371: clay kiln and rock forge makes coal (not charcoal) disappear
### Describe the bug

I was playing a game where I happened to have come across a bunch of coal at a mine and also had charcoal available, all nearby. Reloading the Clay Kiln (constructed object) with Coal just made the coal disappear. Charcoal seems to work correctly, however.

### Attach save file

[Lemay - old-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12745268/Lemay.-.old-trimmed.tar.gz)

### Steps to reproduce

1. Build a Charcoal Forge or Clay Kiln.
2. Have Charcoal and Coal nearby.
3. Try to reload it with the coal.
4. Coal will disappear.

### Expected behavior

Just as with Charcoal, Coal should be loaded into the forge/kiln and tracked in its inventory. It should not just disappear, unless used of course.

### Screenshots

disappearingcoal

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ae14681 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I suspect this has not been caught yet because Coal is an extremely unlikely fuel to be used for these purposes given that it usually spawns in mines which are medium danger, low reward raiding targets. Furthermore, Charcoal is extremely easy to make to the point where it's often faster to just make it than to transport it back to base.

### PR DESCRIPTION
**Pull request by nornagon**
#### Summary
Bugfixes "Fixed reloading of furniture that allow multiple ammo types"

#### Purpose of change

The `reload_furniture` action was written assuming each furniture only allowed
a single ammo type, which is no longer true, resulting in strange bugs when
mixing ammo types.

Fixes #68371.

#### Describe the solution

Refactored `reload_furniture` to enforce the invariant that only a single type
of ammo is present in the furniture at a time.

I also changed some pseudo crafting items to have the PSEUDO flag, which stops
the reload screen from showing "(0/2000)" when choosing ammo (even when there
is ammo present). The denominator there is also wrong for the forge as it
allows a different amount of max charges for coal vs charcoal.

And I fixed the ammo selection screen giving 2000 as the maximum amount of coal
to load at a time by changing `item::reload_option::qty` to check the ammo
remaining for the specific ammo type being loaded.

#### Describe alternatives you've considered

Perhaps it should be allowable to mix ammo types? I didn't take that approach
because it seemed like it would be messy on the ammo usage side.

#### Testing

I manually tested:
- Loading an empty forge lets you choose either coal or charcoal
- Once a forge has something in it, you can only reload that same item type
- Loading coal lets you load up to 10000 at a time, vs charcoal with 2000

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Alternative to #72703 I guess?

**Comment by nornagon** [comment]
Yeah whoops, didn’t see Kate post that while I was working on this.


j

**Comment by katemonster33** [comment]
Looks like there's more here than what is in my branch, if @RenechCDDA wants to add their changes to this and merge this instead I'm fine with it

**Comment by nornagon** [comment]
We might want to blend them a bit? Idk if it’s better to restrict to one
ammo like this does or allow mixing like yours does


j

**Review by RenechCDDA — CHANGES_REQUESTED** [review]
This doesn't correctly consume charges for non default ammo. 

Put 5 coal into a forge, craft crude glass lens. Examine forge. Notice that despite having done the recipe consuming 5 charges, there is still 5 coal to take out.

**Comment by RenechCDDA** [comment]
The above behavior was rectified in katemonster33's PR via 5c9ed5f91a0761216704809cfe0fe9fad43eed6b

**Comment by nornagon** [comment]
Closing in favor of #72703

**Pull request closed without merging**
