### PR TITLE
Add more granularity to overmap vision

### PR DESCRIPTION
**Pull request by ehughsbaird**
#### Summary
Features "Add different levels of vision to the overmap"

#### Purpose of change
On the overmap, there is either no information about a tile, or full information. This is limited, makes scouting a fairly boring affair of going to high places with binoculars for full map information, and it gives a lot of meta information.

#### Describe the solution
Replace unseen/seen with five levels of vision granularity: unseen, vague, outlines, details, full.

Unseen and full (seen) work as before, but the three middle levels provide increasing amounts of information about an overmap tile as it becomes more visible. 

- vague is used to represent a quick (seconds at most) and distant scan of an area - trees look like forests, cleared land looks like fields, buildings in a city blend together, etc. 
- outlines provides a little more thorough look, and easily visible details become clear - farm fields versus unused land, type of forests/tree areas - as well as features that would previously blend in (roads, singular geographic features, etc).
- details serves as a good look (from afar) at an area - easily recognizable areas become fully visible, but buildings in particular are not revealed fully. For time/size reasons I did not implement building types becoming clear, but I think that this is the stage at which that should happen.

To avoid spending the next year adding all these details to every overmap terrain in the game, I added an `oter_vision` type that specifies the display information for vague/outlines/details, and overmap terrains reference which `oter_vision` describes them. In this, overmap terrains can specify that at certain vision levels, they blend in with the environment, in which case the overmap terrain displayed at that tile will be replaced with one of the surrounding overmap terrains. This is used to hide roads and other details at the "vague" vision level. 

Additionally, some map overlays (e.g. hordes) are hidden unless vision of a tile is details or better.

The adjustments to make the map reveal at different vision levels are pretty rough, and I think that whole thing needs to be rewritten, but I've already been working on this PR for too long. Right now it gives more and more detailed vision than I think it should (without spending a decent bit of time explicitly scouting, I think most of the map should be vague or outlines unless quite close to the player), but it can be generous until the work to improve it is done.

If you're reviewing, you may find it handy to review by commits.
The first commit does the boring work of replacing seen: true/false with an enum everywhere it's referenced. The second commit builds on that by providing the infrastructure to actually display these different vision levels differently.  The third commit uses that infrastructure to provide vision levels to all/most of the overmap tiles in the game. The fourth commit just lets you debug reveal the overmap at any vision level.

#### Describe alternatives you've considered
Continuing to work on this for weeks and never publishing it. There's a bunch of decisions I made here with how to specify this information, what vision levels go with certain overmap terrains, etc. that I could second-guess forever.

#### Testing
Run around, explore the map, climb things, grab binoculars, etc.

Here's some maps I've got:
image
Gray, the city I started in, where I know all about what's in town.

image
Up north is Monmouth, and I can't tell what the buildings are there.

image
Over to the east and after climbing a radio tower, I can see a large building, some rural buildings, and a map I read has revealed some of a town down south.
Some roads lead off to some features that I can't see yet, because they blend in with the landscape.

image
I go over to investigate them, finding trailheads and a shooting range, and revealing more of the town (there's some large buildings near the edge)

### CODE REVIEW

**Comment by RanikOrtega** [comment]
Quite an interesting and logical addition.

**Comment by ashGlaw** [comment]
Very exciting!

**Comment by kevingranade** [comment]
This looks AMAZING! Thank you so much for putting all this hard work in.

**Comment by Maleclypse** [comment]
It looks like clang is having some warnings from this. Unless I'm misreading it?

**Comment by ehughsbaird** [comment]
I believe the errors (flake8, clang-tidy, the enum thing) should be fixed now. Thanks for the fix to the enum issue, but I've changed it to act the same as the map display, and only count cities that have the center known at details or better. If just seen at any level is enough, I can change it back.

**Comment by vetall812** [comment]
As a tileset creator, how can I find out what is the current tile i can see? So i can draw an appropriate sprite for this?
Current sidebar cant show me this:
image

**Comment by jeffplata** [comment]
Very exciting indeed. But, can we at least make out the tallest buildings in the city? For sure, a six-storey building would stand out from the among the surrounding one, two storey houses.

**Pull request merged**
