### PR TITLE
Tamable Wildlife: Tamable spiders

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Mods "Makes spiderlings tamable"

#### Purpose of change

Tamable Wildlife allows survivors to tame many things, including ferocious wasps and mighty bears. Yet, for some reason, the spiders are excluded from that long list. This PR aims to fix that oversight.

#### Describe the solution

Makes baby nopes tameable! And large nopes pettable. The larger ones even mountable.

Thrown centipedes into the mix, because if we can tame the cockroaches and louses with dragonflies, then why not centipede larvae? Not to mention armored centipedes sound like a fun alternative to stag beetles.

#### Describe alternatives you've considered

Ignoring the spider mutants' need for friends. Renaming insect_spider.json file in Tamable Wildlife folder to insect.json.

#### Testing

None for now.

#### Additional context

None.

### CODE REVIEW

**Comment by randomtyper** [comment]
@Termineitor244, should it be merged or nay? AFAIK you are the mod's maintainer.

**Review by Termineitor244 — APPROVED** [review]
Looks good to me! I gave it a quick read, and it works in tandem with the rest of the mod, the young are generally non aggressive so I have no problem with the changes, go for it!

**Comment by Karol1223** [comment]
> Thrown centipedes into the mix, because if we can tame the cockroaches and louses with dragonflies, then why not centipede larvae? Not to mention armored centipedes sound like a fun alternative to stag beetles.

No, no, no. Centipede babies are aggressive. This won't work. Do it how I handled other aggressive larvae/nymphs.

**Comment by randomtyper** [comment]
> > Thrown centipedes into the mix, because if we can tame the cockroaches and louses with dragonflies, then why not centipede larvae? Not to mention armored centipedes sound like a fun alternative to stag beetles.
> 
> No, no, no. Centipede babies are aggressive. This won't work. Do it how I handled other aggressive larvae/nymphs.

A-and... Done.

**Comment by Karol1223** [comment]
> > > Thrown centipedes into the mix, because if we can tame the cockroaches and louses with dragonflies, then why not centipede larvae? Not to mention armored centipedes sound like a fun alternative to stag beetles.
> > 
> > No, no, no. Centipede babies are aggressive. This won't work. Do it how I handled other aggressive larvae/nymphs.
> 
> A-and... Done.

Not even remotely what I meant. Look at how Mantis do that.

**Comment by randomtyper** [comment]
Aight, now to wait until Windows build will find out I missed a comma.

**Comment by Termineitor244** [comment]
> > Thrown centipedes into the mix, because if we can tame the cockroaches and louses with dragonflies, then why not centipede larvae? Not to mention armored centipedes sound like a fun alternative to stag beetles.
> 
> No, no, no. Centipede babies are aggressive. This won't work. Do it how I handled other aggressive larvae/nymphs.

Huh, I missed that one, I was looking only at the spiders, good catch!

**Comment by Maleclypse** [comment]
So this is ready for merge?

**Comment by randomtyper** [comment]
> So this is ready for merge?

Should be. If something was wrong, I think Karol would arleady point that out.

**Review by Karol1223 — APPROVED** [review]

**Pull request merged**
