### PR TITLE
Populated Bone Skewers into recipes, made Skewers millable

### PR DESCRIPTION
**Pull request by chrispikula**
#### Summary
Content "Make Bone Skewers less of an end product"

#### Purpose of change

Bone Skewers were a dead-end product with much too many off.  No easily noticeable use case that would consume them, and excessive numbers caused lag and other issues.  I'm talking multiple cells with only 4096 bone skewers.

#### Describe the solution

Change to Bone Glue and Superglue recipes, change to two Liquid Fertilizer recipes.
Utilized skewer_bone as a 25:1 replacement for bone_tainted or bone_any, in recipes where chemical, rather than physical properties were required, with 200% tainted penalty.  
With the two fertilizer_liquid recipes, added meal_bone_tainted, with 200% penalty.

Change to Bone Skewers generic item.  Change to tainted bone carnivore item.
Made skewers 25:4 millable into meal_bone_tainted, to match up with normal bones.  No penalty.
Made bone_tainted 1:4 millable meal_bone_tainted, to match up with normal bones.  No penalty.

Change to kiln firing recipe.  (Not construction interaction!)
Added bone skewers to charcoal recipe utilizing kiln.  25:1 to bone.  No penalty.

Penalties discussed in additional context.

#### Describe alternatives you've considered

Possibly increase their ability to burn, given their increased surface area over normal bones.
Don't know how this would be possible without changing their material, and I don't want to do that.

#### Testing

I ran the game with my changes, didn't notice any particular issues.  Got rid of lag when the skewers were used in recipes.

#### Additional context

I was complaining about this at #47983 
This doesn't fix the issue of hauling them, but it fixes the issue of what to do with them currently.  Nor does this counter the issue of too many of them being made in the first place.

Also, the 200% penalty comes from the comment on line 906:
https://github.com/CleverRaven/Cataclysm-DDA/blob/703dd607ee7d6229fc7229a76da2aa2a93dd16d9/data/json/items/comestibles/carnivore.json#L891-L911

The Charcoal Kiln firing recipe doesn't require the penalty, but I threw it onto the glues due to their usage of bone_any.  The penalty is applied _after_ bone meal is made, as making tainted bone meal from tainted bones doesn't have this penalty in the Master branch.  

Fertilizer should be fine utilizing tainted bone meal, as it's going to go through several biological pathways before being reintroduced into consumables.  Unless the lore is that blob-parasites bioaccumulate across any species barrier?  Either way, the player wouldn't know, and thus it's a rational thing to attempt to do.

It's not like it's hard to get more bone skewers when you need them, and since they don't carry the tainted tag if they were created from a tainted bone, I just made the assumption that making them was effectively equalizing them as to be tainted.

### CODE REVIEW

**Comment by actual-nh** [comment]
Well, actually, you should only be getting 3-4 skewers per bone - see my calculations plus, well, your original issue report.

**Comment by chrispikula** [comment]
> 
> 
> Well, actually, you should only be getting 3-4 skewers per bone - see my calculations plus, well, your original issue report.

Yes, I saw that.  However to change that would push this back beyond 0.F, no?  We would need a new scrap bone item, which means translations and touching many other things.

**Comment by Qrox** [comment]
> they don't carry the tainted tag if they were created from a tainted bone, I just made the assumption that making them was effectively equalizing them as to be tainted.

According to the description of tainted bones, they are "rotten and brittle", so I doubt you can actually make usable bone skewers out of them rather than just shattering the bone. If we disallow making bone skewers from tainted bones, we can change bone skewers to be used like normal bones in crafting.

**Comment by actual-nh** [comment]
> > they don't carry the tainted tag if they were created from a tainted bone, I just made the assumption that making them was effectively equalizing them as to be tainted.
> 
> According to the description of tainted bones, they are "rotten and brittle", so I doubt you can actually make usable bone skewers out of them rather than just shattering the bone. If we disallow making bone skewers from tainted bones, we can change bone skewers to be used like normal bones in crafting.

The bone_skewer recipe uses bone_sturdy. The problem would be the material salvaged_into, which already likely produces bone skewers (usable ones) out of tainted bone.

**Comment by chrispikula** [comment]
> The bone_skewer recipe uses bone_sturdy. The problem would be the material's salvaged_into, which already AFAIK produces bone skewers (usable ones) out of tainted bone. Split bone as a material into regular and tainted? The name "Tainted bone" should not be a string freeze problem - it's already in use (see items/comestibles/carnivore.json).

Should I make a branch off this, and wait for this to get merged, or make a different branch off of Master?

**Comment by actual-nh** [comment]
> > The bone_skewer recipe uses bone_sturdy. The problem would be the material's salvaged_into, which already AFAIK produces bone skewers (usable ones) out of tainted bone. Split bone as a material into regular and tainted? The name "Tainted bone" should not be a string freeze problem - it's already in use (see items/comestibles/carnivore.json).
> 
> Should I make a branch off this, and wait for this to get merged, or make a different branch off of Master?

I think you would need to make a branch off of this, because bone skewers should then not get the 200% penalty in the various recipes.

However, another question remains: What should tainted bone have for salvaged_into? meal_bone_tainted, given that it's crumbly? Nothing? I'm thinking currently the latter, and eventually have it become meal_coarse_bone_tainted or whatever - coarse meaning that just a bit of effort would turn it into meal_bone_tainted, just as meal_coarse_bone would result from boiling & filtering non-tainted spongy bone.

**Comment by chrispikula** [comment]
Do not merge, getting an arithmetic error with stacks of meal_bone_tainted.  Looking for cause.

**Comment by chrispikula** [comment]
So it turns out that if your milling output is less than 1, bad things happen.

Basically, since each bone skewer is an individual item, they can't be used in milling recipes, as they each make .16 tainted bone meal, which means that you, somehow, get 4 for each skewer, but with the following sort of item on the map:

[{"typeid":"meal_bone_tainted","charges":20,"bday":12284615,"owner":"your_followers","active":true,"last_temp_check":12301605,"components":[{"typeid":"skewer_bone","bday":11459960,"owner":"your_followers","last_temp_check":12284615,"item_tags":["PROCESSING"],"specific_energy":54978124,"temperature":29148438}],"specific_energy":35923684,"temperature":28745456,"recipe_charges":0}]]

Notice that "recipe_charges":0 bit?  Yeah, that causes a crash.  I'm guessing that's cause each item that was milled doesn't make a full 'item'.  Still not sure where the extra 3.84 tainted bone meal come from, though.

**Comment by actual-nh** [comment]
Marked with Content Freeze to keep from going stale again; hoping someone can help with the milling problem.

**Pull request merged**
