### PR TITLE
Add Environmental protection to "turtleneck (rolled)" and "turtleneck shirt (rolled)"

### PR DESCRIPTION
**Pull request by Alm999**
#### Summary
Balance "Add environmental protection to rolled "turtleneck" and "turtleneck shirt" -- the same amount as their unrolled variants"

#### Purpose of change

I find it strange that rolling the neck part makes whole upper torso unprotected against environmental attacks (somehow).

#### Describe the solution

I simply copy-pasted the settings from the base unrolled items.

#### Describe alternatives you've considered

None.

#### Testing

Tested the change in-game. At least now the "Protection" entry shows in the item description window.

#### Additional context

None.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Sorry, misclicked.

**Comment by bombasticSlacks** [comment]
I think the turtle-necks that are unrolled should have mouth coverage is the idea... So I would say either the rolling should be removed or they should be further distinguished.

**Comment by Alm999** [comment]
> I think the turtle-necks that are unrolled should have mouth coverage is the idea... So I would say either the rolling should be removed or they should be further distinguished.

My understanding is that currently there is no way to individually set environmental protection for mouth and nothing else. A piece of clothing either has the protection, or don't. So, without reworking the system I found making "env" protection consistent between the modes is better than outright removing the protection.

**Comment by Alm999** [comment]
Changing to dedicated branch.

**Pull request closed without merging**
