### PR TITLE
fungal evolution

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "Fungaloid shambler evolution"

#### Purpose of change

Introduce "upgrades" function to fungal creatures to make them more dynamic and diverse

#### Describe the solution

Creates new fungaloid shamber that is bigger, has more HP, more armor, and is slower than regular fungaloids. It can also put out spores a little faster. It drops wreckage and forest trash that it's using as armor and can throw rocks. Adjusted flavor text

#### Describe alternatives you've considered

Flying evolution, evolution with giant horrible teeth, evolution that spits zombie spiders, evolution that's basically a giant fungal tree that doesn't move anymore, evolution that is basically a fungal tent or fungal house, evolution that grows wonderful berries and sings about a glorious future, evolution that wears cars and trucks as armor, basically a fungal hermit crab, evolution that causes hallucinations, evolution that causes sleepiness, evolution that puffs out fungal smoke to choke you, evolution with far reaching lashing tentacles that apply fungal injections.

#### Testing

Spawns no errors, looks right

image

#### Additional context

Inspired by Marion on Discord

### CODE REVIEW

**Comment by ToxiClay** [comment]
This is making "No Fungal Monsters" even more of a necessity.

**Comment by Venera3** [comment]
You seem to have written "Describe alternatives you've considered" where you surely meant TODO.

To set them a bit more apart, they could maybe get a spell to throw their wreckage armor? Beyond solely being an evolution it might also make sense to mix them into the monster group of fungal terrain, to give them some early presence.

**Comment by SariusSkelrets** [comment]
I like the idea of more fungal diversity but AFAIK the fungus hates anything it perceives as a contaminant. As a Mycus mutant you can’t even drink water so i don’t think it would contaminate itself like that.

However, hardened non-fireproof fungal matter would make sense and would provide a new material to harvest and use (maybe someday we could harvest the towers themselves)

**Comment by ktoma36** [comment]
> I like the idea of more fungal diversity but AFAIK the fungus hates anything it perceives as a contaminant. As a Mycus mutant you can’t even drink water so i don’t think it would contaminate itself like that.
> 
> However, hardened non-fireproof fungal matter would make sense and would provide a new material to harvest and use (maybe someday we could harvest the towers themselves)

I dont see it as hating anything in particular, it simply restructures things to better suit itself. For example it doesnt destroy most structures, simply coating them in fungus to facilitate the spread of itself. 

That its adapting to better deal with the local hostilities by utilizing materials in its environment makes sense to me, especially when later on mycus are fighting with some of the nastier blob mutations and government drones.

**Pull request merged**
