### PR TITLE
Balanced bio repair nanobots

### PR DESCRIPTION
**Pull request by RDru**
#### Summary
```SUMMARY: Balance "Balanced bio repair nanobots"```

#### Purpose of change
Nanobots were insane. Both with the healing and power use. They were healing 1 hp/s on all body parts. Several dozen seconds and you were all new. They also used 5 kJ per healed hp. That's 30 kJ if all parts were damaged and 2 kJ for each bleeding. And bleeding was all healed in 1s.

#### Describe the solution
- 4 J/s as standby power use
- 80 J for activation to simulate delay when nanobots have to go to body parts after activation or park in safe place/storage when turning off
- extra 40 J/s if you are damaged or bleeding
- healing 1 hp also takes 5 kcal
- healing rate is 1 hp per minute on random damaged body part
- after healing 1 hp, there is a chance roll to see if bleeding was also healed, based on % hp
- if healing was not removed there is 50% chance roll for not hp part or for not damaged part

#### Describe alternatives you've considered
I was considering other values for power and calories. Please leave your feedback.

#### Testing
Tested after getting damaged.

### CODE REVIEW

**Comment by irwiss** [comment]
Can i suggest removing or lowering the standby power? Super high drain (twice the amount of leukocytes) for no reason just turns the bionic into player's menu dance, rather than something in-game character would really experience - as to them flicking the switch when they feel ok should come naturally to them.

Alternatively automatically "flicking off" when finished healing all limbs similar to how gasoline generator does it.

Also kcal cost for repairs could be increased - if say base limb hp is 84 for str 8 character, regenerating half a limb at higher than normal speed could cost more than 420 kcalories, it could also provide extra value for high calorie foods as part of healing process with nanobots

**Comment by RDru** [comment]
Leukocytes are just some stimulators vs I assume large amount of nanobots in your body. Also system has to constantly check if you are damaged anywhere. 
I we want automatic turning off it should be with delay - nanobots need some time to park somewhere safe so they don't drift in places they should not be or leave the body.

**Comment by mrkybe** [comment]
@RDru I think what @irwiss means is that at the current power-drain, its very clearly optimal to toggle it on/off and basically all players will do that.  

According to [Wolfram-Alpha](https://www.wolframalpha.com/input/?i=10J%2Fs) 10J/s is equivalent to about 1/2 of the energy used by the brain.

So if there's half a brain worth of nano-bots who are about as efficient and active as the average brain-cell, then I guess that makes sense?  But that seems like a lot of energy to use just on stand-by to me.

**Comment by RDru** [comment]
Ok, 4 J/s and 80 J for activation to simulate delay.

**Pull request merged**
