### PR TITLE
Survivor Machete Update

### PR DESCRIPTION
**Pull request by glenmack**
#### Summary
```SUMMARY: Balance "Survivor Machete buff"```
Takes survivor machete from bash 6, cut 20, to bash 2, cut 26, and weight reduced to 495 as a survivor would probably want a lighter sharper weapon.

#### Purpose of change
Survivor Machete was currently worse than original machete from a base statistics point of view, being slower and with identical damage values. Being gated behind melee 5 makes it very hard to craft. Considering difficulty it should probably be even better than my slight buff.

#### Describe the solution
Reduced weight to lower than machete and at the same time reduced bash damage to reflect the description of being "re-balanced" into a lighter sharper weapon.

### CODE REVIEW

**Comment by RarkGrames** [comment]
It has the Quick Strike technique, which provides 30% extra dps. Normal machete is better only in one area, the higher butchering quality.

**Comment by l29ah** [comment]
The DPS is actually lowered for armored opponents this way, no?

**Comment by SirPendrak** [comment]
I believe it was possible to create surv. machette from makeshift machette, wchich is already a huge adventage. No need for forging equipement to get weapon similar in stats to standard macheete, and only materials needed are a blade from lawnmower and some ducktape.

**Comment by RarkGrames** [comment]
> 
> 
> The DPS is actually lowered for armored opponents this way, no?

Yes, if you do the math, it will be lower damage against armor. All I've found about it is in GAME_BALANCE.md:

"Rapid strike technique increases damage per turn by 0.66 / 0.5 = 132%"

I don't think that the lower damage against armor is such a big tradeoff, because bigger threats require high caliber firearms or axes anyway.

**Comment by glenmack** [comment]
> It has the Quick Strike technique, which provides 30% extra dps. Normal machete is better only in one area, the higher butchering quality.

I don't think rapid strike is meant to proc all the time, so it isn't/shouldn't be a flat 30% bonus. I think this is bugged right now, and will be fixed.

> The DPS is actually lowered for armored opponents this way, no?

Yes, but it makes it a more effective cut weapon, and by melee 5 you can probably afford to be specializing your weapons.



> I believe it was possible to create surv. machette from makeshift machette, wchich is already a huge adventage. No need for forging equipement to get weapon similar in stats to standard macheete, and only materials needed are a blade from lawnmower and some ducktape.

You'd still need melee 5 and survival 3 and that would be a huge point investment to start off and is probably only possible in mid-late stages of most average games.

**Comment by kevingranade** [comment]
Before a significant buff we need a better rationale for what is even happening here, what is being changed about the machete that significantly improves damage output? If we don't have a reason, it might be better to simply remove it.

**Comment by bombasticSlacks** [comment]
I think its bizarre that optimizing the machete for combat makes it heavier (and therefore slower if only by 1 unit) without increasing damage. Especially when the machetes fast attack speed is its best feature. I think the survivor version should at least have the same speed as the non survivor.

That said both versions are already very good being some of the fastest weapons with what I consider high dpm (around 28) and a good to hit bonus. Most times a weapon with under 100 M/A can be used to kite in melee which is a giant benefit on its own. Interestingly I made a spread sheet for this today.  Attached are all the "fast weapons" for comparison.

image

**Comment by glenmack** [comment]
@kevingranade For rationale, If I was going to improve a gardening machete, I'd Use a hacksaw, and maybe reduce it's size by 10-15% and sharpen it, (They are are often pretty blunt) maybe make some improvements to the handle, from the recipe I assumed that was what survivor version was supposed to be and why I proposed the change. Perhaps I should readjust the recipe to more clearly reflect this?

As @bombasticSlacks pointed out, the base machete is currently up there with Rivtech fighting knife in terms of damage output. Perhaps a slight re-balance to the original machete, bringing it in-line with the kukri, would make the change from bash + cut to a simple cutting weapon more of a reason to keep both. Machetes are not that uncommon and probably shouldn't be as potent as they are.

Especially now we don't have the ability to reinforce weapons, survivor, or weapon recipes are the only non-looting weapon "progression", we don't have much in the way of improving what we have, or what we find. Only books offer access to new weapons recipes and are again a loot find.

**Comment by kevingranade** [comment]
Reducing the size is going to make it hit less hard, you don't need high levels of skills to figure out you need to sharpen a blade, and 'improve the handle' doesn't tell me anything. Basically that rationale doesn't hold up.

Especially your ending ``we don't have much in the way of improving what we have, or what we find`` makes ne think you're just trying to inject some amount of improvement mechanics into the game. I'm sympathetic with that goal, but it needs to happen within the framework of real wespons.

**Comment by glenmack** [comment]
> Reducing the size is going to make it hit less hard, you don't need high levels of skills to figure out you need to sharpen a blade, and 'improve the handle' doesn't tell me anything. Basically that rationale doesn't hold up.
> 
> Especially your ending `we don't have much in the way of improving what we have, or what we find` makes ne think you're just trying to inject some amount of improvement mechanics into the game. I'm sympathetic with that goal, but it needs to happen within the framework of real wespons.

Yes reducing the size will make it hit less hard, that's why I reduced the bash damage, a machete is designed to have a larger head, and the larger weight at the end of the blade and uses that momentum to cut through plant fibers, with less strength and finesse. It's a gardeners tool.

It's currently a good mixed bash cut/damage, which is more utility. Mid/late game it's about specializing it into a better specific cutting weapon. That's the rationale. A poor man's katana, if you will.

Cutting a machetes rounded head down at an angle gives a sharper point with which to cut, and reduces weight, making it lighter, quicker, and less of a bashing weapon. The recipe calls for duct tape, and solder, I would be using this for improvements to the handle, by filling any gaps between the blade and often times wooden handle, to prevent blood and water seeping in to gaps and causing corrosion and wrapping the handle in duct tape. Giving it a better grip and less wobble, which gardening machetes also frequently have.

I could switch the recipe to cutting 5 but that makes it much easier to craft considering you can get to 4 with Spetnaz knife techniques.

**Comment by Rivet-the-Zombie** [comment]
> The recipe calls for duct tape, and solder, I would be using this for improvements to the handle, by filling any gaps between the blade and often times wooden handle, to prevent blood and water seeping in to gaps and causing corrosion and wrapping the handle in duct tape. Giving it a better grip and less wobble, which gardening machetes also frequently have.

Maybe also make the handle a bit larger/more comfortable in the process. Most machetes I've handled have handles that are way too small and hard on the hands after extended usage.

**Comment by kevingranade** [comment]
The rationale doesn't hold up.

**Pull request closed without merging**
