### PR TITLE
CRIT mutant friendly clothes recipes

### PR DESCRIPTION
**Pull request by Arokha**
#### Summary
Content "CRIT mutant friendly clothes recipes"

#### Purpose of change
Allows some basic clothes modifications to make things more mutant friendly. This would be cool as a tailoring kit option to any piece of clothing but that sounds complicated.

#### Describe the solution
Added a few recipes to basically cut holes for tails or the toes off boots for claws/talons in CRIT gear, at the cost of a small amount of coverage in the case of the tail mods and a large chunk of coverage in the case of toeless boots.

Honestly this was a fairly quick thing I just did for myself but I thought I'd put it here too. If desirable, I can make changes to make the mod requirements more accurate rather than a big copypaste.

#### Describe alternatives you've considered
Trying to do it in C++ or begging someone else to make it a feature of tailoring kits

#### Testing
Been playing with this for a bit myself.

#### Additional context
I made another PR to fix this, but currently toe talons don't check ALLOWS_TALONS so the boots need OVERSIZE to accommodate toe talons.

### CODE REVIEW

**Comment by Arokha** [comment]
Fixed. That's a handy bot.

**Comment by Arokha** [comment]
I'll fix pluralization tomorrow

**Review by Maleclypse — CHANGES_REQUESTED** [review]
So this takes all the existing problems with the CRIT Gear (overpowered, nonsensical, etc) and amplifies them by making them usable by all the mutant classes.  I don't think I'd approve this addition unless it was part of a serious rework of CRIT entirely.   This wouldn't fit the lore for the CRIT rework that I have notes written up for but I don't know when I'll get to it, so that's why I said that we are looking for a direction for CRIT.   And this is bothering me probably because it's the first thing I ran into but toeless boots can't be waterproof.

**Comment by Arokha** [comment]
> And this is bothering me probably because it's the first thing I ran into but toeless boots can't be waterproof.

Alrighty. Would it be worth fixing that (I didn't even think about it) and reducing armor/coverage of the items or is it unlikely to be merged even then?

If it's unlikely to be merged, howabout the infantry duster in particular getting ALLOWS_TAIL? I'm unsure how a duster would interfere with a tail since it's not worn against the body firmly so the tail would just go downwards. beneath the duster.

**Comment by Maleclypse** [comment]
> > And this is bothering me probably because it's the first thing I ran into but toeless boots can't be waterproof.
> 
> Alrighty. Would it be worth fixing that (I didn't even think about it) and reducing armor/coverage of the items or is it unlikely to be merged even then?
> 
> If it's unlikely to be merged, howabout the infantry duster in particular getting ALLOWS_TAIL? I'm unsure how a duster would interfere with a tail since it's not worn against the body firmly so the tail would just go downwards beneath the duster.

Yeah, duster should be fine :)

**Pull request closed without merging**
