### PR TITLE
Clear up misunderstandings about lever-action survivor guns.

### PR DESCRIPTION
**Pull request by kevingranade**
Evidently the descriptions led people to believe these are semi-auto.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Is my fault. o3o

Still, that aim-reset sounds decent.

**Comment by chaosvolt** [comment]
...and now I just noticed you've officially made the "this gun has a tube mag despite using the worst kind of bullet to load end-to-end" comment visible. Am I the only one that's enough of a gun nerd to be irked by this? ;_;

**Comment by karlnp** [comment]
I am also irked.

**Comment by chaosvolt** [comment]
Didn't even Rivet remark upon that the first time this lunacy was pointed out? :V

**Comment by Nerezza** [comment]
Look on the bright side. If the gun jams, you can throw it in the Hulk's face and it'll be like 98% likely to blow up.

**Comment by chaosvolt** [comment]
An even better makeshift grenade than the Sten would be.

**Pull request merged**
