### PR TITLE
Rename HOBBIES tab to BACKGROUND

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Interface "Rename HOBBIES tab to BACKGROUND"

#### Purpose of change

The reason for this is https://github.com/CleverRaven/Cataclysm-DDA/pull/51860#issuecomment-927170567, which is valid criticism, since e.g drug-addictions are not hobbies but your background. This would make it also more appropriate to insert other things into this tab, imho the stronger or more frequent portal storms, walled in or even nemesis challenge would fit perfectly into it. It would give your run even more adaptiveness.

Book Hating can not exactly be called a hobby, too. So in my point of view it makes perfect sense to rename this to the (quite literally) more appropriate "Background".

#### Describe the solution

n/a

#### Describe alternatives you've considered

There was quite some discussion about this in the IRC channel a few months ago and there have been multiple suggestions for a new name, like:
- Past(ime)
- Life
- Story
- ...

Background is still the best suggestion.

#### Testing

String change, does hopefully not need any testing.

#### Additional context

Ping @kevingranade as he was involved into that discussion.

This does not rename the `hobbies` variable because I am not a coder and do not know the implications of just regexp replacing this string.

### CODE REVIEW

**Comment by andrei8l** [comment]
Needs a translation hint

**Comment by NetSysFire** [comment]
@andrei8l I just looked into the docs and could not find anything about that, but existing hints just say "This basically means that, so consider...", but background seems pretty obvious here. What would you suggest as a hint? That it does not mean wallpaper or backdrop?

**Comment by ZhilkinSerg** [comment]
It needs a hint as it might be translated with scenery/backdrop in mind.

**Comment by Shodan14** [comment]
Your profession might just as well be "background". At least hobbies implies that you can have multiple.

**Comment by Zireael07** [comment]
@Shodan14: Actually, many tabletop RPGs have professions or occupations - one set of things - and then background(s) - a second set of things. That said, you have a point that often background is a single choice, not multiple choice.

**Comment by Stone94** [comment]
> Your profession might just as well be "background". At least hobbies implies that you can have multiple.
> 
> I'd suggest looking at what various tabletop RPG systems call things, might be some good inspiration there. Call of Cthulhu for example has occupations and personal interests.

Choosing various hobbies into a single background can also imply that is your background. A characters background can include many things such as their hobbies, education, profession etc.

**Pull request merged**
