### PR TITLE
Shocker zombies no longer drop CBMs(in vanilla)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Balance "Shocker zombies cannot be harvested for bionics in vanilla"

#### Purpose of change

[Kevin has spoken.](https://github.com/CleverRaven/Cataclysm-DDA/pull/35951#issuecomment-563069598) Shocker zombies are the result of space blob magic, not CBMs.

#### Describe the solution

Move skeletal shocker harvest to ``mr_bones``, the others to ``zombie``. Move the old harvest entries to Aftershock, with an added overwrite of the harvest per @John-Candlebury 's request.

#### Describe alternatives you've considered

None.

#### Testing

Dissect shockers with & without Aftershock on, be unable to get bionics or bionic scraps without AFS on.

#### Additional context
I did another world with every content mod active to make sure the moved itemgroups are only used in vanilla.
image
~#mod-development on Devcord

### CODE REVIEW

**Comment by SariusSkelrets** [comment]
Would it be possible to harvest the electrical organ? 

I would love to collect organic electrical generators and find a way to use them

**Comment by Fris0uman** [comment]
What SariusSkelrets said but maybe make it useless, but it would be cool to find weird organs related to their electrical property inside, instead of just regular zombie meat/bones.

**Comment by esotericist** [comment]
even after 0.F drops, this should probably wait until we've got our exodii transition at least partially underway, else we're just removing a substantial source of CBMs without providing an alternative.

i'm 100% for it once we're able to do that, though.

**Comment by I-am-Erk** [comment]
I am merging this now, as #49398 is pretty much ready and will solve some of these problems.

**Pull request merged**
