### PR TITLE
Remove fumarole specials and rifts

### LINKED ISSUE #29431: House spawned with lava seam in basement
**Describe the bug**  
Generic house spawned with lava seam in basement, instant death on descent with no warning.

**To Reproduce**  
Load game in the attached save file, descend stairs.
[Lumberton2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3061196/Lumberton2.zip)

**Expected behavior**  
There is not a lava seam in a basement, or if there is, there is at least a warning about it. 

**Screenshots**  
2019-04-09 23_03_35-Cataclysm_ Dark Days Ahead - 0 D-1522-gea190d3

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1522-gea190d3
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs (default)

**Additional context**  
Experimental Z-levels were not enabled. Possibly related to #29420 .

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fumaroles were brought to my attention recently in the context of, "what are these things anyway?", and I realized I don't have an answer for that. AFAICT these have never had a rationale at all other than, "lava is cool", so for the time being I'm just nuking the ones in mainline.
The same rationale applies to rifts and hellmouths, they're obviously incomplete, cause nothing but trouble, and don't occupy a position in the lore.
Fixes #29431

#### Describe the solution
Remove the spawn entries from regional_map_settings.json

#### Describe alternatives you've considered
I could see replacing this with something with a similar impact, like a portal that emits heat and spits out heat-themed enemies, but a random crack in the ground with lava in it doesn't add anything to the game.
The lore-friendly version of a rift is a portal opening with the extreme environment being on the other side.

#### Other context
I'm just removing the pieces that are safe to remove for the time being to prevent generation of new instances, it will take some more careful work to make sure we remove the rest of the pieces.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Maybe make these rifts spawn near some of the portals instead of random places?

**Comment by kevingranade** [comment]
Have you been in a rift? There's nothing there, it's a placeholder that was added 7 years ago and never finished.
If you want to add some interesting otherworldly content that would be great, but this is not that.

**Comment by ZhilkinSerg** [comment]
We probably want different types of portals: emitting various fields/radiation/temperature, spawning otherworld creatures/artifacts, etc.

**Comment by paulenka-aleh** [comment]
While not against these changes, actually add some variety to underground 'solid rock' which is much more 'nothing'. I'd be happy to see even more stuff like that there ones, e.g. caverns, aquifers, much more lealistic mines...

I admit I've been there only once and I had to dig through lab walls and rock to get there. Nothing more like a warm place to sleep and heat food still.

Well, if lava in its cureent form doesn't seem to have much justification from realism point of view than maybe some other day in another way...

**Comment by Night-Pryanik** [comment]
> Have you been in a rift?

Rift? I think I haven't. Most probably I confused it with lava fumaroles.

**Comment by kevingranade** [comment]
The fumarole is what whales called the random lines of lava that get scattered around with no apparent rationale.
A rift is a big empty underground room partially filled with lava that also has no apparent rationale.

**Comment by Throwaway-name** [comment]
Please add a new spawn location for sulfur.

**Comment by Zireael07** [comment]
Are there any sources on volcanism in New England area?

**Pull request merged**
