### PR TITLE
Make autowalk more like autodrive

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Make autowalk more like autodrive"

#### Purpose of change

In #50637 I noted that autowalk is a bit haywire due to making unnecessary forays into buildings only to back out the same way again, or getting out of water only to get back in again. I figured that changing the waypoints to be more like autodrive (i.e. target the midpoints of the edges between OMTs instead of the midpoints of the OMTs) would result in more natural-looking paths.

#### Describe the solution

Implement the waypoint selection change in `activity_handlers::travel_do_turn`. For the last OMT in the path, target the middle (as before), otherwise target the midpoint of the nearest edge. 
When following a diagonal overmap path, this actually **reduces the travel time significantly** due to traveling in a more-or-less straight diagonal line instead of zig-zagging in cardinal directions. See the 3rd pair of videos below.
I also added some more utility functions for dealing with coordinates.

#### Describe alternatives you've considered

Not adding utility functions. This is the 3rd PR in which I've needed to write code that finds the bounds of an OMT, so I decided to add that to the coordinates library. I need to go back and edit my earlier code to use it (if this change is approved).

#### Testing

Walking through a house, before this change, taking 134s:

https://user-images.githubusercontent.com/8000047/129103713-53fe3571-2efe-474a-a3ae-423e9ecaef3c.mp4

After, taking 116s:

https://user-images.githubusercontent.com/8000047/129103730-ca6fdf2e-b56a-49a2-85ac-fbd71cd9825c.mp4

Swimming across a river, before this change, takes 151s:

https://user-images.githubusercontent.com/8000047/129102511-6ebbcb4f-a3d2-4e65-8088-e01d341ce561.mp4

After, takes 125s:

https://user-images.githubusercontent.com/8000047/129102557-1476670e-2b88-470c-b98c-2d2074abc1ef.mp4

Walking a diagonal path, before this change, taking 97s:

https://user-images.githubusercontent.com/8000047/128978337-f9393bef-7d07-4c24-b720-0671587f4f7b.mp4

Walking the same path now takes 76s:

https://user-images.githubusercontent.com/8000047/128978352-3072f760-9450-45f6-80d2-47f3ea52ac5d.mp4

It's not quite sqrt(2) times faster, but it's close.

Otherwise, when autowalking in a straight line through roads, fields or forests I couldn't see a change.

### CODE REVIEW

**Comment by actual-nh** [comment]
The swim_after.mp4 video has a "jump" in the middle, BTW.

**Comment by eltank** [comment]
> The swim_after.mp4 video has a "jump" in the middle, BTW.

Happened so fast the video capture software missed it. But the beginning and end are the interesting bits anyway.
I suppose the videos would be better if I could turn off autowalk frame skipping, but I didn't see an easy way to do it.

**Comment by eltank** [comment]
> > The swim_after.mp4 video has a "jump" in the middle, BTW.
> 
> Happened so fast the video capture software missed it. But the beginning and end are the interesting bits anyway.
> I suppose the videos would be better if I could turn off autowalk frame skipping, but I didn't see an easy way to do it.

So 2 of the "before" videos were recycled from #50637, i.e. they were recorded using an older build of the game. I just tried re-doing them at HEAD without my change and the same frame-skipping happens. It's not just the video recorder, the game simply doesn't render any frames during the swim. This must have broken in the last few days.

**Comment by RenechCDDA** [comment]
May I recommend a testing environment? Stretches of subway track with their rails still intact, with 90 degree turns, while dragging a suitably heavy 1-tile-wide vehicle (e.g. shopping cart) behind you.

Pre-50637 autowalk can *sometimes* path it, but it seems to depend on your starting point. Other times it will cancel the autowalk seemingly at random, despite there being valid path(s). (It would also cancel autowalk in the middle of long straights sometimes...)

I am unsure if 50637 improved on this behavior but it's the one place where autowalk would semi-consistently fail to work without player intervention so it should be a good testing ground.

**Comment by actual-nh** [comment]
> > > The swim_after.mp4 video has a "jump" in the middle, BTW.
> > 
> > 
> > Happened so fast the video capture software missed it. But the beginning and end are the interesting bits anyway.
> > I suppose the videos would be better if I could turn off autowalk frame skipping, but I didn't see an easy way to do it.
> 
> So 2 of the "before" videos were recycled from #50637, i.e. they were recorded using an older build of the game. I just tried re-doing them at HEAD without my change and the same frame-skipping happens. It's not just the video recorder, the game simply doesn't render any frames during the swim. This must have broken in the last few days.

Could you create an issue for this? Thanks!

**Comment by eltank** [comment]
> > > > The swim_after.mp4 video has a "jump" in the middle, BTW.
> > > 
> > > 
> > > Happened so fast the video capture software missed it. But the beginning and end are the interesting bits anyway.
> > > I suppose the videos would be better if I could turn off autowalk frame skipping, but I didn't see an easy way to do it.
> > 
> > 
> > So 2 of the "before" videos were recycled from #50637, i.e. they were recorded using an older build of the game. I just tried re-doing them at HEAD without my change and the same frame-skipping happens. It's not just the video recorder, the game simply doesn't render any frames during the swim. This must have broken in the last few days.
> 
> Could you create an issue for this? Thanks!

I tried using older builds to determine when the frame-skip-while-swimming behavior started. Even a 2-week old build has it. So at this point it looks like that's "normal" and I'm confused about how I was ever able to capture a video in which swimming was not skipped.

**Comment by eltank** [comment]
I have re-recorded the "before" videos using a binary built from the master commit that this PR forked from (37171ba2386e99cb6d51bda4243282f1934520e1). I should have done this to begin with instead of recycling videos.

**Comment by eltank** [comment]
> May I recommend a testing environment? Stretches of subway track with their rails still intact, with 90 degree turns, while dragging a suitably heavy 1-tile-wide vehicle (e.g. shopping cart) behind you.
> 
> Pre-50637 autowalk can _sometimes_ path it, but it seems to depend on your starting point. Other times it will cancel the autowalk seemingly at random, despite there being valid path(s). (It would also cancel autowalk in the middle of long straights sometimes...)
> 
> I am unsure if 50637 improved on this behavior but it's the one place where autowalk would semi-consistently fail to work without player intervention so it should be a good testing ground.

Hmm, I suppose this PR does make autowalk while dragging a cart underground more likely to succeed when making 90 degree turns due to using waypoints that are between the tracks. Here's a video.

https://user-images.githubusercontent.com/8000047/129094963-72fdcf98-c4ed-46e2-b28f-496ae78fb02c.mp4

**Comment by eltank** [comment]
Re-did all the videos to show the time elapsed. The new waypoints always result in reduced travel time in all the scenarios I tested.

**Comment by eltank** [comment]
Adjusted the midpoint formula for inclusive rectangles and cuboids. It was potentially off by one.

**Comment by actual-nh** [comment]
Question: Over on the dev discord (which you are invited to, of course), we discovered that CDDA has been using euclidean distances when it should have been using octile distances for movement pathing. It is likely that rl_dist is going to have an option, eventually made always the case if CIRCLEDIST is set (the default), to use octile distance instead of euclidean distance. What effects would that have on your pathing work?

**Comment by eltank** [comment]
> Question: Over on the dev discord (which you are invited to, of course), we discovered that CDDA has been using euclidean distances when it should have been using octile distances for movement pathing. It is likely that rl_dist is going to have an option, eventually made always the case if CIRCLEDIST is set (the default), to use octile distance instead of euclidean distance. What effects would that have on your pathing work?

There are multiple kinds of movement pathing in CDDA (overmap, critter/autowalk and autodrive). If you mean overmap pathfinding, I already know it's broken (in more than one way) and I'm working on a fix. Autodrive should be correct (at least, it's in sync with how vehicle diagonal moves are timed today). The critter pathfinding (also used by autowalk) I know the least about,  but if it gets changed it won't impact any of my current work.

I'll have to look into joining the discord, sounds like I may be missing out.

**Comment by actual-nh** [comment]
> > Question: Over on the dev discord (which you are invited to, of course), we discovered that CDDA has been using euclidean distances when it should have been using octile distances for movement pathing. It is likely that rl_dist is going to have an option, eventually made always the case if CIRCLEDIST is set (the default), to use octile distance instead of euclidean distance. What effects would that have on your pathing work?
> 
> There are multiple kinds of movement pathing in CDDA (overmap, critter/autowalk and autodrive). If you mean overmap pathfinding, I already know it's broken (in more than one way) and I'm working on a fix. Autodrive should be correct (at least, it's in sync with how vehicle diagonal moves are timed today). The critter pathfinding (also used by autowalk) I know the least about, but if it gets changed it won't impact any of my current work.

OK, good.

> I'll have to look into joining the discord, sounds like I may be missing out.

Try <https://discord.gg/yKJCKfx>; if that doesn't work, let me know and I'll check with an admin.

**Comment by KorGgenT** [comment]
https://discord.gg/cdda should also work.

**Pull request merged**
