### PR TITLE
Change item list highlight color to white

### LINKED ISSUE #51443: Accessibility issue due to inconsistent UI in all-items panel
### Describe the bug

From Xvordan on the dev discord:
`Is there any chance the highlight color for items in the list all items around the player command could be changed to white (similar to the monster tab) instead of green? I'm a screen reader user playing CDDA, and I use a few scripts I wrote to help track CDDA's highlight. The problem with the item tab is that the items are highlighted in green, but so is the <tab> Items line at the top, as is the "v" at the bottom to indicate that you can scroll. This makes finding the highlight hard to keep a track of without some fairly complex scripting (which I'm not adept enough to work with yet).`

### Steps To Reproduce

Examine the list all items panel, and note that the highlight is in green, which it shares with other things on the same panel.

### Expected behavior

That the highlight be distinguishable from other parts of the page.

### Screenshots

_No response_

### Versions and configuration

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Interface "Change item list highlight color to white"

#### Purpose of change

Fixes #51443
Improve accessibility and UI consistency

#### Describe the solution

change a few lines in `game::list_items` for the color change
add a `wmove` call to position the cursor on the selected item for accessibility

#### Testing

Before:
image

After:
image

#### Additional context

I'm sure someone will complain because it's changing, but white-on-blue is what we use to highlight the "selected item" in the inventory UI and AIM, so this improves consistency.

### CODE REVIEW

**Comment by andrei8l** [comment]
Favorite items are also colored white

**Comment by dseguin** [comment]
It looks like other elements on the panel are also highlighted in white ("Items", total count, etc). Would it be possible to highlight the selected item in yellow instead?

**Comment by actual-nh** [comment]
> It looks like other elements on the panel are also highlighted in white ("Items", total count, etc). Would it be possible to highlight the selected item in yellow instead?
> 
> Edit: Just to clarify, because originally the user had issues distinguishing between different elements that used the same highlight.

Or other things such as those other elements + favorite items could be recolored (thus keeping things matching to the inventory and AIM UIs).

**Comment by andrei8l** [comment]
> Or other things such as those other elements + favorite items could be recolored (thus keeping things matching to the inventory and AIM UIs).

Favorite items are colored white in inventory and AIM as well. This accessibility problem is supposedly solved by `wmove()` (see https://github.com/CleverRaven/Cataclysm-DDA/issues/39638) but my experience with that hasn't been great.

**Comment by eltank** [comment]
After taking a closer look at the inventory UI, I noticed that the selected item is white-on-blue. I changed the item list UI to match.

**Comment by eltank** [comment]
I added a `wmove` call but I don't know if I'm doing it right. @Qrox, could you take a look?

**Comment by eltank** [comment]
Changed the `wmove` code with advice from @dseguin. Hopefully it works now.

**Comment by Qrox** [comment]
> I added a `wmove` call but I don't know if I'm doing it right. @Qrox, could you take a look?

It looks good to me, but you might want to ask someone who uses screen reader to test it.

**Comment by eltank** [comment]
I would test it myself, but I couldn't find any instructions on how to set up a screen reader for CDDA.
At this point the easiest way to verify might be to just get this merged and released into an experimental build, then ask for feedback from players using screen readers.

**Comment by anothersimulacrum** [comment]
To test `wmove`s, make a curses build, and change `curs_set( 0 )` to `curs_set( 2 )` https://linux.die.net/man/3/curs_set.

**Comment by eltank** [comment]
Hmm, so unfortunately the "info panel" display moves the cursor away from the item list.

image

**Comment by Qrox** [comment]
Maybe switch the refreshing order of `w_item` and `w_item_info`? If that does not work, call `wmove` after refreshing `w_item_info` and refreshing `w_item` again?

**Comment by eltank** [comment]
I could fix it in this instance, but this is a systemic issue. Now that I have a build that shows me the cursor, I can see that nearly *all* of the menus in CDDA put the cursor someplace non-sensical. Is it even helpful to position the cursor more appropriately?

Inventory - at the bottom
image

Advanced inventory - on the minimap
image

Main menu, Action menu - bottom option
image

The crafting and construction menus are the only ones that put the cursor on the selected item
image

And how do people read the message log? In the main game window the cursor is on the "@" symbol.

In order to improve accessibility I would need someone to tell me how to set up a screen reader for CDDA so that I could hear what they hear. I tried using Orca on linux with a curses build and the experience was absolutely horrible.

**Comment by andrei8l** [comment]
Those menus haven't been updated for screen reader support, at least according to the linked issue. For this case, you can just move the `wmove()`  and `wnoutrefresh()` calls to the end of the `on_redraw` callback (below `if (filter_type {...}`).

In my experience the screen reader didn't stop at window boundaries though so it wasn't very useful at all. That's possibly just a configuration issue though.

**Comment by eltank** [comment]
[We should probably be discussing this in an Issue like #26885 rather than in merged PR thread but oh well]

When I was playing with Orca I also noticed that it reads "past" the end of what it should have read, and can't handle wrapped text at all. 
Probably the best thing we can do for accessibility is to put TTS in the game engine. There seemed to be some willingness to add espeak-ng support from the core maintainers. I'm willing to write code that uses the library, but I don't have the necessary skills to actually add the library as a dependency. I do know a couple of contributors who do have those skills, so I'll try asking them when they're less busy.

**Pull request merged**
