### PR TITLE
Tinfoil hats!

### PR DESCRIPTION
**Pull request by i2amroy**
Adds aluminum foil and tinfoil hats. Allows aluminum foil to be used to make funnels and aluminum powder as well as the noted hats.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Oh derp. This is gonna foil my own mod's addition of foil and hats, I'm sure. o3o

**Comment by Rivet-the-Zombie** [comment]
These should totally provide a tiny bonus to saving throws versus mind control.

**Comment by chaosvolt** [comment]
Seems it does add protection against anything using the FEAR_PARALYZE move. If this gets merged, I'll presumably have to remove my take on it from More Survival Tools. o3o

**Comment by Rivet-the-Zombie** [comment]
Oh, so it does! Very nice!

**Comment by chaosvolt** [comment]
Also, I should point out that treating aluminum foil as a container with a cooking quality of 1 makes foil useful for something BESIDES making hats. >w>

**Comment by i2amroy** [comment]
>Also, I should point out that treating aluminum foil as a container with a cooking quality of 1 makes foil useful for something BESIDES making hats. >w>

Basic idea in the avoidance was that most recipes work just as fine without the foil as with it, and I didn't really see a good way to let us use it as a container in such a way that cooking in it uses up charges. (Though if somebody wants to come up with a follow up PR that adds some more uses to aluminum foil I certainly wouldn't be opposed).

**Comment by chaosvolt** [comment]
If this does get merged, I'll yoink the tinfoil hat from my PR. One problem though, how does one handle a container with a cooking quality versus this version that's ammunition?

Easiest way I'm guessing would be to make my version be an implied foil wrap and add a recipe to craft the cookable foil from a given amount of unused foil?

**Comment by chaosvolt** [comment]
Hmm. I see. And augh, derpy thing didn't update with your reply until I posted. >w<

**Comment by chaosvolt** [comment]
Additionally will likely have the foil tweaks be my last addition to that PR for now, if this goes through. o3o

**Pull request merged**
