### PR TITLE
adding drops for florentine weapons

### PR DESCRIPTION
**Pull request by VMSolidus**
this is to go with the PR for florentine weapons

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>this is to go with the PR for florentine weapons

Why isn't it a part of that PR?

**Comment by evilexecutive** [comment]
Probably because I don't know how to modify two files in one PR. I tried making a "More Shotgun ammo" mod that required multiple files, and lost about an hour's work to the aether, can't find that branch.

I'm a newb at github..

**Comment by BorkBorkGoesTheCode** [comment]
While I am not an expert either, I could walk you through the process. Send me a PM on the forums.

**Comment by mugling** [comment]
welcome @evilexecutive. This needs to be part of #17445 which you'll need to submit further commits to in any case as it currently has JSON errors.

**Pull request closed without merging**
