### PR TITLE
Martial Arts Rebalance for Muay Thai

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Muay Thai"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Muay Thai

#### Describe the solution

`Also referred to as the "Art of 8 Limbs," Muay Thai is a popular fighting technique from Thailand that uses powerful strikes.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 3||
Leg Block|Unarmed 4||
Forced Unarmed|Unarmed 0|Special Ability|Can use technique and buff while holding anything
Muay Thai|Unarmed 0|Static Buff|-5 Bash damage, Bash damaged increased 50% of Strength
elbow|Unarmed 2|Unarmed Crit Tech|50% move cost
kick|Unarmed 3|Unarmed Tech|Stun duration: 1
flying knee|Unarmed 4|Unarmed Crit Tech|Stun duration: 2

**Missing/Wrong information:** There is no "size damage bonus" against large monsters or NPCs. 

Muay Thai doesn't live up to it's name of being the most brutal martial art in the world. It has a few problems that need to be addressed.

_Problems and issues_
- **Static Buff reduces damage.** 
The player needs a massive amount of Strength to see bonus damage from Muay Thai's Static Buff. In fact, the -5 damage bonus requires at least 10 Strength to "break even" with the 50% of Strength damage bonus the Static Buff gives. Any less and you get a damage PENALTY!

- **Able to stunlock extremely easily.** 
It's usually a bad idea to have a normal technique that can stun. Considering flying knee also stuns, it's a recipe to allow Muay Thai to stunlock everything to death.

- **Style has the force_unarmed attribute.** 
I somehow completely missed this but Muay Thai had the same force_unarmed attribute that Taekwondo does. Not only is this not realistic but it also goes against the in-game Muay Thai description. It's hard to be the "Art of 8 Limbs" when you are holding a gun in your hands.

_Rebalance Goal_
Muay Thai should be strong martial art that focuses on Strength and doing heavy damage. Further, Muay Thai fighters are trained to block and take the massive hits from each other.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 3||
Leg Block|Unarmed 4||
Muay Thai Stance|Unarmed 0|Static Buff|Blocked damage reduced by 50% of Strength
Power Kick|Unarmed 0|Unarmed Tech|+30% Bash damage
Elbow Strike|Unarmed 1|Unarmed Crit Tech|50% move cost
Determination|Unarmed 3|OnGetHit Buff|Bash damage increased by 25% of Strength, blocked damage reduced by 50% of Strength. Lasts 5 turns.
Grab Break|Unarmed 3|Melee Tech|Grab Break
Flying Knee|Unarmed 5|Unarmed Crit Tech|+40% Bash damage, Stun duration: 1

_Important Changes_
- **Power Kick does +30% bash damage but no longer stuns.**
Muay Thai has the most damaging normal technique (with no requirements) in the game. However, it no longer stuns and is marked "crit_ok" which means it will it can act as a normal or a crit technique.

- **Flying Knee does +40% damage.**
Flying Knees hurt and this change makes it as damaging as Boxing's Uppercut. This technique is now the heavy hitter of Muay Thai.

- **Added Muay Thai Stance buff.**
Muay Thai is known for not only dealing powerful hit but also taking them as well. This extends only to blocking because not even a professional fighter can take a Power Kick to the head without damage. 

- **Added Determination buff**
Muay Thai practioners are trained for battles of attritions. They fight by dealing heavy damage that wears opponents down over time. So it makes sense that they train to not let the same happen to them. Determination triggers when the player takes damage OR blocks an attack. It will increase the player's damage and reduced blocked damage for a decent amount of time. This should help players in a pinch by ending the fight quicker and with less damage.

_Advantages_
- Muay Thai's techniques can do a large amount damage in a short amount of time.
- The style can get up to 100% of Strength in blocked damage reduction making you less likely to take damage

_Disadvantages_
- While the style does have some blocked damage reduction, it doesn't have any way to handle groups of enemies other than trying to kill them as fast as possible.
- Critical hits are where most of the damage comes from in Muay Thai. All three techniques will compete with each other to be the randomly choosen technique for a crit and you may not get the one you want when you need it the most.
- Aside from Flying Knee, the style doesn't have any sort of control options.

#### Describe alternatives you've considered

_If the style is too strong..._
- Reduce the damage of Flying Knee from +40% to +25%.
- Increase the duration of the Determination buff.
- Increase the move cost of Elbow Strike.

_If the style is too weak..._
- Add a Rapid technique.
- Add a damage bonus to Elbow Strike.

#### Additional context

_References:_
[Muay Thai wikipedia page](https://en.wikipedia.org/wiki/Muay_Thai)
[Top 10 Muay Thai Knockouts](https://www.youtube.com/watch?v=EaE66cI4Bz8)
[Muay Thai Fighter Vs Tree](https://www.youtube.com/watch?v=Jkcg_WzT0DU)

### CODE REVIEW

**Comment by Bulletfang** [comment]
As a practitioner of Muay Thai, I can say that this martial art I see here is Kickboxing, not Muay Thai.

Most martial arts in the western world that advertise themselves as Muay Thai are actually just Kickboxing, a neutered form of traditional Muay Thai, so I don't fault anyone for that. Firstly. Muay Thai has a big focus on clinches, if your teacher doesn't also teach the traditional form of Muay Thai, namely Muay Boran, then you're learning Kickboxing, cause your teacher doesn't know Muay Thai. One of the biggest differences to the rules between the two is that in Muay Thai, clinches are not interrupted after 3 seconds, you can clinch for as long as you want, meaning a large portion of Muay Thai is learning to deal with them in the form of techniques, both offensive and defensive, knee strikes from all angles, leaning on your opponent to tire him out and breaking out of clinches in various ways, so please at least add a grab breaking attack. Any decent Muay Thai teacher will teach you that you can fight in the Muay Thai style with weapons, the basic stance and form of blocking strikes and kicks are actually derived from Angkan Felices Kaliradman, Escrima, Arnis, etc., and can be used 1 to 1 with sticks, swords and knifes to effectively defend against those. Muay Thai was actually just a backup martial art for cases where a warrior lost his weapons. Realistically, the use of weapons with this style should be possible, at least partially. Fighters are also taught to be ruthless in the ring, this is more of a mindset teachers teach that is difficult to put into words, but it's really about relentlessness and aggression, sportsmanship comes into action when the fight is over. My teacher personally taught everyone that when your opponent does that stupid hand-touchy thing at the start of a fight, that instead of doing that with him, you're to surprise him with a fast foot to the face. In Thailand, they don't do that and they think it's very stupid when they see it. Western Kickboxing is generally looked down upon over there.

Then, another big pet peeve I have with this is the names of the techniques, there is no 'Power Kick', that sounds like something from an anime. 'Flying Knee', which one? Muay Thai has three flying knee techniques that I personally learned and at least another three that I haven't, all very different. Same with 'Elbow Strike', please, there are, without exaggeration, at least 5 dozen different elbow strike techniques and variations of them. The names of the attacks in Muay Thai are very important because they are not simply 'Horizontal Elbow Strike to the Jaw' if you translate them, they have cultural significance, i.e.: Hanuman Tawai Waen, a complicated uppercut strike with both fists simultaneously striking the jaw, translates to 'Hanuman bestows the ring', which refers to Thai folklore in which Hanuman, a monkey-god whose name pops up in a lot of Muay Thai techniques, gives a ring to another god. The techniques that don't have those direct cultural correspondences have names that describe a way that you can imagine the movements of the attack (only a minority of basic movements don't have them). As such, it pains me greatly to not see any proper names used at all. Please let me give examples of relatively common techniques that can be used in-game, I've personally learned all the following techniques (to varying success lol), take your pick:

Kicks:
Mon Yan Lak - Defensive kick that stops an advancing adversary, little damage but very fast and technically safe.
Teep Tong - The go-to for any Muay Thai practitioner when gauging your opponents ability, a fast hard frontal kick with the heel that has great stopping power and range and can even knock your opponent back. Strong fighters will stab you with their big toe, very dangerous when hitting soft parts like the stomach or throat.
Pashee Sabat Yang - A combination left right high kick to the jaw, very powerful but difficult to pull off effectively and can be easily interrupted.

Knee Strikes:
Kumpan Pung Hok - The quint-essential forward knee strike, can be used as a counter for any fist or elbow strikes or on its own.
Hanuman Thayarn - What is known is the western world of martial arts as 'Flying Knee', it is essentially a Kumpan Pung Hok that is executed during a forward leap. There is a variation of it where the knee is turned 90° to the side to circumvent certain blocks and one where you feint one knee mid-air only to strike with the other, all before landing (but I forgot their names and I can't find them rn).

Elbow Strikes:
Sok Fan Nah - Light fast elbow strike that is primarily used for counters, it is used has a frontal attack (pushing motion) so it has limited damage potential.
Pra Yaikae - Medium elbow that is a simple horizontal strike, prone to create cuts when hitting the head.
Khacha Tokman - A heavy, fairly difficult elbow strike, essentially the equivalent of a backhand strike, but from a more difficult angle.

Wai Kru - The Wai Kru is a short custom dance that Muay Thai fighters do before every fight and occasionally during training to honor their teacher. Although when learning Muay Thai from a book in the game the player doesn't technically have a trainer, it is absolutely necessary that a flavor text is displayed that the player performs the Wai Kru when choosing Muay Thai as his active martial art. This is one of the first steps every person learns when beginning training in Muay Thai, teachers value this greatly as it is a fundamental part of their tradition. Every teacher designs their own Wai Kru, they look ridiculous but you have to do them or your teacher gets annoyed with you.


If I sound impolite anywhere, I apologize, but it always gets me angry when I see western Kickboxing referring to itself as Muay Thai, and I see that influence in this game, and it gets be doubly angry so because it is a great game that gets so many things right. Muay Thai under Kickboxing rules is very similar to Kickboxing, and if you changed the title name of this martial art as it is now in this game from 'Muay Thai' to 'Kickboxing', no one would ever know the difference. By adding traditional names to the techniques and adding the weapons and grab break, it would distance itself from Kickboxing and add lore/flavor to the style that it is lacking.

Please and thank you for reading.

**Comment by Bulletfang** [comment]
As a practitioner of Muay Thai, I can say that this martial art I see here is Kickboxing, not Muay Thai.

Most martial arts in the western world that advertise themselves as Muay Thai are actually just Kickboxing, a neutered form of traditional Muay Thai, so I don't fault anyone for that. Firstly. Muay Thai has a big focus on clinches, if your teacher doesn't also teach the traditional form of Muay Thai, namely Muay Boran, then you're learning Kickboxing, cause your teacher doesn't know Muay Thai. One of the biggest differences to the rules between the two is that in Muay Thai, clinches are not interrupted after 3 seconds, you can clinch for as long as you want, meaning a large portion of Muay Thai is learning to deal with them in the form of techniques, both offensive and defensive, knee strikes from all angles, leaning on your opponent to tire him out and breaking out of clinches in various ways, so please at least add a grab breaking attack. Any decent Muay Thai teacher will teach you that you can fight in the Muay Thai style with weapons, the basic stance and form of blocking strikes and kicks are actually derived from Angkan Felices Kaliradman, Escrima, Arnis, etc., and can be used 1 to 1 with sticks, swords and knifes to effectively defend against those. Muay Thai was actually just a backup martial art for cases where a warrior lost his weapons. Realistically, the use of weapons with this style should be possible, at least partially. Fighters are also taught to be ruthless in the ring, this is more of a mindset teachers teach that is difficult to put into words, but it's really about relentlessness and aggression, sportsmanship comes into action when the fight is over. My teacher personally taught everyone that when your opponent does that stupid hand-touchy thing at the start of a fight, that instead of doing that with him, you're to surprise him with a fast foot to the face. In Thailand, they don't do that and they think it's very stupid when they see it. Western Kickboxing is generally looked down upon over there.

Then, another big pet peeve I have with this is the names of the techniques, there is no 'Power Kick', that sounds like something from an anime. 'Flying Knee', which one? Muay Thai has three flying knee techniques that I personally learned and at least another three that I haven't, all very different. Same with 'Elbow Strike', please, there are, without exaggeration, at least 5 dozen different elbow strike techniques and variations of them. The names of the attacks in Muay Thai are very important because they are not simply 'Horizontal Elbow Strike to the Jaw' if you translate them, they have cultural significance, i.e.: Hanuman Tawai Waen, a complicated uppercut strike with both fists simultaneously striking the jaw, translates to 'Hanuman bestows the ring', which refers to Thai folklore in which Hanuman, a monkey-god whose name pops up in a lot of Muay Thai techniques, gives a ring to another god. The techniques that don't have those direct cultural correspondences have names that describe a way that you can imagine the movements of the attack (only a minority of basic movements don't have them). As such, it pains me greatly to not see any proper names used at all. Please let me give examples of relatively common techniques that can be used in-game, I've personally learned all the following techniques (to varying success lol), take your pick:

Kicks:
Mon Yan Lak - Defensive kick that stops an advancing adversary, little damage but very fast and technically safe.
Teep Tong - The go-to for any Muay Thai practitioner when gauging your opponents ability, a fast hard frontal kick with the heel that has great stopping power and range and can even knock your opponent back. Strong fighters will stab you with their big toe, very dangerous when hitting soft parts like the stomach or throat.
Pashee Sabat Yang - A combination left right high kick to the jaw, very powerful but difficult to pull off effectively and can be easily interrupted.

Knee Strikes:
Kumpan Pung Hok - The quint-essential forward knee strike, can be used as a counter for any fist or elbow strikes or on its own.
Hanuman Thayarn - What is known is the western world of martial arts as 'Flying Knee', it is essentially a Kumpan Pung Hok that is executed during a forward leap. There is a variation of it where the knee is turned 90° to the side to circumvent certain blocks and one where you feint one knee mid-air only to strike with the other, all before landing (but I forgot their names and I can't find them rn).

Elbow Strikes:
Sok Fan Nah - Light fast elbow strike that is primarily used for counters, it is used has a frontal attack (pushing motion) so it has limited damage potential.
Pra Yaikae - Medium elbow that is a simple horizontal strike, prone to create cuts when hitting the head.
Khacha Tokman - A heavy, fairly difficult elbow strike, essentially the equivalent of a backhand strike, but from a more difficult angle.

Wai Kru - The Wai Kru is a short custom dance that Muay Thai fighters do before every fight and occasionally during training to honor their teacher. Although when learning Muay Thai from a book in the game the player doesn't technically have a trainer, it is absolutely necessary that a flavor text is displayed that the player performs the Wai Kru when choosing Muay Thai as his active martial art. This is one of the first steps every person learns when beginning training in Muay Thai, teachers value this greatly as it is a fundamental part of their tradition. Every teacher designs their own Wai Kru, they look ridiculous but you have to do them or your teacher gets annoyed with you.


If I sound impolite anywhere, I apologize, but it always gets me angry when I see western Kickboxing referring to itself as Muay Thai, and I see that influence in this game, and it gets be doubly angry so because it is a great game that gets so many things right. Muay Thai under Kickboxing rules is very similar to Kickboxing, and if you changed the title name of this martial art as it is now in this game from 'Muay Thai' to 'Kickboxing', no one would ever know the difference. By adding traditional names to the techniques and adding the weapons and grab break, it would distance itself from Kickboxing and add lore/flavor to the style that it is lacking.

Please and thank you for reading.

**Comment by Rivet-the-Zombie** [comment]
>the most brutal martial art in the world

I'm fairly certain there's a lot of folks out there practicing non-sporting combat arts that would disagree heavily with this assessment.

**Comment by Hymore246** [comment]
> Any decent Muay Thai teacher will teach you that you can fight in the Muay Thai style with weapons, the basic stance and form of blocking strikes and kicks are actually derived from Angkan Felices Kaliradman, Escrima, Arnis, etc., and can be used 1 to 1 with sticks, swords and knifes to effectively defend against those. Muay Thai was actually just a backup martial art for cases where a warrior lost his weapons. Realistically, the use of weapons with this style should be possible, at least partially.

Capable or taught? The former would be a case for Forced Unarmed but the latter means that Muay Thai actually teaches how to use weapons with the style. Forced Unarmed allows you to hold something but you can't use it in any way in melee combat. You can't even block with it. There are other complication such as how feasible it would be to use elbows and knees while holding, say, a rocket launcher.

>Then, another big pet peeve I have with this is the names of the techniques, there is no 'Power Kick', that sounds like something from an anime. 'Flying Knee', which one? Muay Thai has three flying knee techniques that I personally learned and at least another three that I haven't, all very different. Same with 'Elbow Strike', please, there are, without exaggeration, at least 5 dozen different elbow strike techniques and variations of them. 

Short Answer: Whichever one works best for the situation you are in.

Long Answer: Back when I was rebalancing Judo (#33448), I discussed why Judo only has a handful techniques in-game compared to the 67 different throwing techniques that real life Judo teaches. There were two important points: ambiguity and doing more with less.

**Ambiguity.** 
Ambiguity allows Judo's "Throw" technique to work in situations where a specific throw (like [Harai Tsurikomi Ashi](https://judoinfo.com/haraitsurikomiashi/)) wouldn't be allowed to work. In effect, "Throw" is any applicable throwing technique that could be usable at that given moment. Judo has a lot of throws which ultimately do the same thing, put the target on the ground. Muay Thai falls into a similar situation, it has a lot of techniques but are they really different enough to merit having their own technique in the style? Allowing an ambiguous technique like "Elbow Strike" effectively allows all of them to exist in the style. Otherwise, you start to get technique bloat, which I cover below.

**Doing more with less.** 
The more techniques a style has, the less likely you are to get a specific one in a given situation. While conditional attributes can modify the technique pool, CDDA chooses what technique is used in combat at random. This is a necessary evil in CDDA because stopping to pick a technique with EVERY attack will slow the game to a crawl and completely kills enjoyment. Technique bloat can become real issue when you cannot reliably get a specific technique to trigger. 
Conditional attributes can modify what techniques can be picked but this only helps so much and each change increases the complexity of the style, making it harder for players to understand. In order to make martial art styles as reliable as possible, I try to limit the amount of techniques each style has. So in my eyes, similar real life techniques need to be different enough to justify them being different techniques in-game. Otherwise, I let ambiguity do the heavy lifting by letting one technique cover all the possible situation for a "Throw" or "Elbow Strike" in the real life style.

**Technique names.**
Here is the problem: most people are not going to understand what "Hanuman Tawai Waen" means. Technique and buff names need to communicate what they do to the player. Yes, "Elbow Strike" is generic but it's gets the point across. For comparison take Medieval Swordsmanship. If you look at the techniques.json file, you can see that Sweeping Strike is an [unterhau](http://www.learn-sword-fighting.com/en/unterhau.html). Saying that the technique is an unterhau will just confuse players while Sweeping Strike gives at least a little bit of insight into what the attack will do. I get that the style loses some of it's identity with simple names but I would much rather that happen than people not understand what the style does. I think a properly made martial art can still convey the correct "feel" of the style. At least as far as CDDA is capable of.

>If I sound impolite anywhere, I apologize, but it always gets me angry when I see western Kickboxing referring to itself as Muay Thai, and I see that influence in this game, and it gets be doubly angry so because it is a great game that gets so many things right. Muay Thai under Kickboxing rules is very similar to Kickboxing, and if you changed the title name of this martial art as it is now in this game from 'Muay Thai' to 'Kickboxing', no one would ever know the difference. By adding traditional names to the techniques and adding the weapons and grab break, it would distance itself from Kickboxing and add lore/flavor to the style that it is lacking.

I understand you are passionate about your martial art but please remember that most people do not know as much about Muay Thai as you do. Using myself as an example, the most I knew about Muay Thai before doing the rebalance was from YouTube clips and Sagat from the Street Fighter fighting games. 
I can add Wai Kru as the initiation message and a Grab Break technique if that is taught as well. I designed Muay Thai as a brutal style that uses extremely strong strikes from different parts of the body and that has a focus on using the Strength stat. I am open to other suggestions as well but just remember that there are limits to what can be accomplished in CDDA.

>I'm fairly certain there's a lot of folks out there practicing non-sporting combat arts that would disagree heavily with this assessment.

I was quoting something I had heard about the style previously. That might have been incorrect. At very least, I'd say that it is a very brutal martial art.

**Comment by Hymore246** [comment]
I looked into it and clinching is an important part of Muay Thai along with breaking free so I added in a Grab Break. I've updated some of the messaging for the techniques and the initiate message as well.

I tried to find information about Muay Thai using weapon but I couldn't find anything that said it was part of the modern version of the style. [From what I found](https://www.martialartsplanet.com/threads/weapons-training-in-muay-thai.114082/), weapon use in might have been adopted from the older [Mauy Boran](http://warriors-journey.com/en/muay-thai-vs-muay-boran/) and [Krabong](https://en.wikipedia.org/wiki/Krabi%E2%80%93krabong) systems. There might be some overlap but I think this falls into the same problem as having Staves with Karate. Too much of the martial art's techniques change when using a weapon and that makes it too different from the original to be included.

**Pull request merged**
