### PR TITLE
Update character_body.cpp fix bodytemp_modifier_traits

### LINKED ISSUE #46999: The effect of bodytemp_modifiers does not match the doc description
我发现 bodytemp_modifiers 的效果和doc里的说明相反
如果我设置bodytemp_modifiers = [ -100000, 100000 ];
我的人物会过热
如果是 [ 100000, -100000 ]则不会
这是个bug么？
---Google Translate---
I found that the effect of bodytemp_modifiers is opposite to the description in the doc
If I set bodytemp_modifiers = [-100000, 100000 ];
My character will overheat
If it is [100000, -100000] then not
Is this a bug?

The version is cataclysmdda-0.E-Windows_x64-Tiles-b11399

### PR DESCRIPTION
**Pull request by zwa73**
#### Summary
Bugfixes "Using mutation_heat_low when overheating, rather than mutation_heat_high"

#### Purpose of change
fix https://github.com/CleverRaven/Cataclysm-DDA/issues/46999
"bodytemp_modifiers" : [100, 150], // Range of additional bodytemp units (these units are described in 'weather.h'. First value is used if the person is already overheated, second one if it's not
This is described in JSON_INFO.md

So in theory set to [- 100000, 100000] should be able to keep the temperature in the normal range

But if I set bodytemp_modifiers = [-100000, 100000 ];
My character will overheat
If it is [100000, -100000] then not, and keep the temperature in the normal range

#### Describe the solution

Swap the values of mutation_heat_low and mutation_heat_high in the code

#### Additional context

After fix
```
const int mutation_heat_low = bodytemp_modifier_traits( true );
const int mutation_heat_high = bodytemp_modifier_traits( false );
```

with character.cpp 8182
```
int Character::bodytemp_modifier_traits( bool overheated ) const
{
    int mod = 0;
    for( const trait_id &iter : get_mutations() ) {
        mod += overheated ? iter->bodytemp_min : iter->bodytemp_max;
    }
    return mod;
}
```
with mutation_data.cpp 299
```
if( jo.has_array( "bodytemp_modifiers" ) ) {
        JsonArray bodytemp_array = jo.get_array( "bodytemp_modifiers" );
        bodytemp_min = bodytemp_array.get_int( 0 );
        bodytemp_max = bodytemp_array.get_int( 1 );
}
```

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Some comments:
- The PR doesn't describe what it does, i.e. some code is pasted, but there is nothing explaining why the change was made or what the results are in game terms.
- The "Summary" section has to follow the format described in the comment as it is parsed by a script. The format is to replace "Category" with one of the listed keywords followed by an actual brief description in the quote section, or the keyword "None" (without the quotes) without any comment.
- As noted above, the "Purpose of change" section should contain something useful.
- Again, the "Describe the solution" section ought to describe what the change is, rather than a copy of the changed code.

**Comment by zwa73** [comment]
> Some comments:
> 
> * The PR doesn't describe what it does, i.e. some code is pasted, but there is nothing explaining why the change was made or what the results are in game terms.
> * The "Summary" section has to follow the format described in the comment as it is parsed by a script. The format is to replace "Category" with one of the listed keywords followed by an actual brief description in the quote section, or the keyword "None" (without the quotes) without any comment.
> * As noted above, the "Purpose of change" section should contain something useful.
> * Again, the "Describe the solution" section ought to describe what the change is, rather than a copy of the changed code.

Ok, I added some description
https://github.com/CleverRaven/Cataclysm-DDA/issues/46999

**Comment by PatrikLundell** [comment]
Sorry, but you still do it wrong.

- The "Summary" section should meet the criteria specified by the comment (which I tried to explain above) and contain nothing else.
- The fix reference should be in the Purpose of Change section.
- The "Using..." line belongs in the Describe the Solution section.
- Unless a change is trivial and self evident, there should be a description of how the change was tested to verify that it actually does what it's intended to do. In your case I would expect a successful test to be to describe a scenario where things do not give the expected result prior to the change, and then describe that it does give the expected result after the change (and explaining what the desired and actual effects are).

If you still have trouble getting the format right, try to look at some other PRs to see how they do it.

Note that my comments are restricted to getting the PR contents correct from a contents perspective: I can't comment on the actual PR functionality itself, leaving that for those competent at evaluating it.

#52940 references a bird mutation that provides some insulation against cold. This is not a strictly positive change, as it also means getting warmer, and thus overheat easier when it's warm. If the code change intends to make the mutation only protect against cold but do nothing when it's warm it does not match the intention of the mutation. A warm jacket protects against cold, but it is not useful when it's warm, and feather, fur, etc. generally provides insulation against cold as well as increased problems with overheating.

**Comment by zwa73** [comment]
> Sorry, but you still do it wrong.
> 
> * The "Summary" section should meet the criteria specified by the comment (which I tried to explain above) and contain nothing else.
> * The fix reference should be in the Purpose of Change section.
> * The "Using..." line belongs in the Describe the Solution section.
> * Unless a change is trivial and self evident, there should be a description of how the change was tested to verify that it actually does what it's intended to do. In your case I would expect a successful test to be to describe a scenario where things do not give the expected result prior to the change, and then describe that it does give the expected result after the change (and explaining what the desired and actual effects are).
> 
> If you still have trouble getting the format right, try to look at some other PRs to see how they do it.
> 
> Note that my comments are restricted to getting the PR contents correct from a contents perspective: I can't comment on the actual PR functionality itself, leaving that for those competent at evaluating it.
> 
> #52940 references a bird mutation that provides some insulation against cold. This is not a strictly positive change, as it also means getting warmer, and thus overheat easier when it's warm. If the code change intends to make the mutation only protect against cold but do nothing when it's warm it does not match the intention of the mutation. A warm jacket protects against cold, but it is not useful when it's warm, and feather, fur, etc. generally provides insulation against cold as well as increased problems with overheating.

"bodytemp_modifiers" : [100, 150], // Range of additional bodytemp units (these units are described in 'weather.h'. First value is used if the person is already overheated, second one if it's not
This is described in JSON_INFO.md
Maybe [100,150] is a mixed effect
But if the overheating now that will use the second high value
Clearly now the code is not correct

**Comment by Maleclypse** [comment]
I've fixed the PR summary.  It has a very specific set of requirements and it can take a coupe tries for it to make sense.  :)

**Pull request merged**
