### PR TITLE
Adds monster armors

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Content "Additional Monster Armors"

#### Purpose of change
Adds additional monster armors for cold, biological and pure.  

#### Describe the solution
Cargo cults from existing monster armor's to the additional damage types.

#### Describe alternatives you've considered
None

### CODE REVIEW

**Comment by Maleclypse** [comment]
@anothersimulacrum don't stress if you aren't able to make time to check this but I wanted someone to double check my cargo culting.

**Comment by dseguin** [comment]
This just needs a little bit of extra stuff to get working:

```diff
diff --git a/src/monstergenerator.cpp b/src/monstergenerator.cpp
index 4ce56b9e36..ff15bc0b86 100644
--- a/src/monstergenerator.cpp
+++ b/src/monstergenerator.cpp
@@ -436,6 +436,15 @@ void MonsterGenerator::finalize_mtypes()
         if( mon.armor_elec < 0 ) {
             mon.armor_elec = 0;
         }
+        if( mon.armor_cold < 0 ) {
+            mon.armor_cold = 0;
+        }
+        if( mon.armor_pure < 0 ) {
+            mon.armor_pure = 0;
+        }
+        if( mon.armor_biological < 0 ) {
+            mon.armor_biological = 0;
+        }
         if( mon.status_chance_multiplier < 0 ) {
             mon.status_chance_multiplier = 0;
         }
@@ -740,6 +749,9 @@ void mtype::load( const JsonObject &jo, const std::string &src )
     assign( jo, "armor_acid", armor_acid, strict, 0 );
     assign( jo, "armor_fire", armor_fire, strict, 0 );
     assign( jo, "armor_elec", armor_elec, strict, 0 );
+    assign( jo, "armor_cold", armor_cold, strict, 0 );
+    assign( jo, "armor_pure", armor_pure, strict, 0 );
+    assign( jo, "armor_biological", armor_biological, strict, 0 );
 
     if( !was_loaded || jo.has_array( "weakpoint_sets" ) || jo.has_array( "weakpoints" ) ) {
         weakpoints_deferred.clear();
diff --git a/src/mtype.h b/src/mtype.h
index 1c35c102e3..583f2b8e54 100644
--- a/src/mtype.h
+++ b/src/mtype.h
@@ -343,6 +343,9 @@ struct mtype {
         int armor_acid = -1;    /** innate armor vs. acid */
         int armor_fire = -1;    /** innate armor vs. fire */
         int armor_elec = -1;    /** innate armor vs. electricity */
+        int armor_cold = -1;    /** innate armor vs. cold **/
+        int armor_pure = -1;    /** innate armor vs. pure **/
+        int armor_biological = -1; /** innate armor vs. biological **/
         ::weakpoints weakpoints;
         weakpoint_families families;
```

**Comment by Maleclypse** [comment]
> This just needs a little bit of extra stuff to get working:
> 
> ```diff
> diff --git a/src/monstergenerator.cpp b/src/monstergenerator.cpp
> index 4ce56b9e36..ff15bc0b86 100644
> --- a/src/monstergenerator.cpp
> +++ b/src/monstergenerator.cpp
> @@ -436,6 +436,15 @@ void MonsterGenerator::finalize_mtypes()
>          if( mon.armor_elec < 0 ) {
>              mon.armor_elec = 0;
>          }
> +        if( mon.armor_cold < 0 ) {
> +            mon.armor_cold = 0;
> +        }
> +        if( mon.armor_pure < 0 ) {
> +            mon.armor_pure = 0;
> +        }
> +        if( mon.armor_biological < 0 ) {
> +            mon.armor_biological = 0;
> +        }
>          if( mon.status_chance_multiplier < 0 ) {
>              mon.status_chance_multiplier = 0;
>          }
> @@ -740,6 +749,9 @@ void mtype::load( const JsonObject &jo, const std::string &src )
>      assign( jo, "armor_acid", armor_acid, strict, 0 );
>      assign( jo, "armor_fire", armor_fire, strict, 0 );
>      assign( jo, "armor_elec", armor_elec, strict, 0 );
> +    assign( jo, "armor_cold", armor_cold, strict, 0 );
> +    assign( jo, "armor_pure", armor_pure, strict, 0 );
> +    assign( jo, "armor_biological", armor_biological, strict, 0 );
>  
>      if( !was_loaded || jo.has_array( "weakpoint_sets" ) || jo.has_array( "weakpoints" ) ) {
>          weakpoints_deferred.clear();
> diff --git a/src/mtype.h b/src/mtype.h
> index 1c35c102e3..583f2b8e54 100644
> --- a/src/mtype.h
> +++ b/src/mtype.h
> @@ -343,6 +343,9 @@ struct mtype {
>          int armor_acid = -1;    /** innate armor vs. acid */
>          int armor_fire = -1;    /** innate armor vs. fire */
>          int armor_elec = -1;    /** innate armor vs. electricity */
> +        int armor_cold = -1;    /** innate armor vs. cold **/
> +        int armor_pure = -1;    /** innate armor vs. pure **/
> +        int armor_biological = -1; /** innate armor vs. biological **/
>          ::weakpoints weakpoints;
>          weakpoint_families families;
> ```

Thanks!

**Comment by dseguin** [comment]
Might also be a good idea to update [the doc](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md) with the new fields:

| Property | Description
| --- | ---
| `armor_cold` | (integer) Monster's protection from cold damage
| `armor_pure` | (integer) Monster's protection from pure damage (very few things should resist pure damage)
| `armor_biological` | (integer) Monster's protection from biological damage

**Comment by Maleclypse** [comment]
Documentation police bribed. ;)

**Pull request merged**
