### PR TITLE
In pickup UI, show identical items as stacks

### LINKED ISSUE #18245: Change the way stacks of items are displayed
Similar items stack really nicely in the inventory:
arbitrary_alt_text

But not so cleanly when they're in a pile on the ground:
more_arbitrary_alt_text

I may be missing some reason why this should stay, but it'd be nice if it were easier to leaf through huge stockpiles without getting into the " `w " range.

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #18245.

Contains #18280, will rebase once that gets landed.

### CODE REVIEW

**Comment by kilozombie** [comment]
Just out of curiosity-- does this fix the apparent bug where you can't have a certain number of stacks of items on a single tile (so you could have 12,000,000 batteries in a cargo dimension but max out at a few thousand rags because rags don't stack)?

**Comment by nornagon** [comment]
Nope, this is a UI change only.

**Comment by kilozombie** [comment]
Right, thanks. Still really useful.

**Comment by Coolthulhu** [comment]
Needs a rebase

**Comment by nornagon** [comment]
Rebased.

**Comment by mugling** [comment]
Screenshot would be helpful

**Comment by Zireael07** [comment]
A screen was in #18245 

https://cloud.githubusercontent.com/assets/172800/18493099/ab1e530e-79c3-11e6-990b-4eb47264db2d.png

**Comment by nornagon** [comment]
Inlining for less click:

**Comment by mugling** [comment]
How do you pickup say 3 rags?

**Comment by nornagon** [comment]
Same way you would pick up less than a whole stack of batteries: just type
the number you want to pick up before hitting the invlet (or right arrow).

**Comment by mugling** [comment]
> Same way you would pick up less than a whole stack of batteries: just type the number you want to pick up before hitting the invlet (or right arrow).

This needs to be clearer. One option is having left and right keys change amount and showing that as the left column instead of `+` and `#`

**Comment by Rivet-the-Zombie** [comment]
>This needs to be clearer. One option is having left and right keys change amount and showing that as the left column instead of + and #

Improving how item selection works is a good idea, but it's not particularly related to this PR.

**Comment by Zireael07** [comment]
Can this get merged ASAP? It checks out with a green tick, and is a huge quality-of-life improvement.

**Comment by nornagon** [comment]
I have some ideas for improving the UI but I haven't hit on a clear
solution that works in all cases. Using left/right to add/sub one from the
# of items picked up works OK for `19 rags`, but not so well for `battery
(3000)`. It's not 100% clear what hitting the corresponding letter for an
item should do. Add one? Toggle between 0 and the max amount? Toggle
between 0 and the most you can carry? There should probably be a way to
select "as many as I can carry" using the right arrow key or nearby key
(shift+right?) too, if that's a feature available by pressing the item's
letter.

I'm happy to continue iterating on the UI until I find one that works, but
ideas and suggestions would be appreciated :)

Also happy for this to get merged as is & we can iterate, if that makes
sense.

**Comment by mugling** [comment]
> Improving how item selection works is a good idea, but it's not particularly related to this PR.

If you don't know how to pickup just one item it's a particularly harsh regression?

**Comment by Rivet-the-Zombie** [comment]
But that hasn't changed due to this PR; you still pick up partial stacks the exact same way you used to.

**Comment by nornagon** [comment]
Well, it's just that previously it was much less likely that you'd want to
pick up a partial stack, since that was only relevant for count-by-charges
items, which are generally lighter, smaller and rarer. Now the first time
you cut up a sheet you'll want to pick up a partial stack.

**Comment by mugling** [comment]
You could pick up individual rags before - now you need to know the`#` prefix which isn't exactly obvious nor well documented.

**Pull request merged**
