### PR TITLE
Allow filtering in amount_of and charges_of

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: Infrastructure "Allow filtering in amount_of and charges_of"```

#### Purpose of change
Allows fixing #28089.

#### Describe the solution
Add a filter function as an optional parameter in `visitable::amount_of` and `visitable::charges_of`.

#### Describe alternatives you've considered
This is not strictly necessary, but It will make similar fixes in the future simpler and does so cleanly.

#### Additional context
Astyle makes these function declarations look really ugly, not really sure what to do about that though.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Add ugly astyle files to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/astyle_blacklist.

**Comment by jbytheway** [comment]
I suggest a global function object called e.g. `return_true` which takes any arguments and returns `true` (put it somewhere like `cata_utility.h`).  Then use that rather than declaring a lambda each time.  That's less code duplication, and avoids the astyle issue.

**Comment by ifreund** [comment]
>I suggest a global function object called e.g. `return_true` which takes any arguments and returns `true` (put it somewhere like `cata_utility.h`). Then use that rather than declaring a lambda each time. That's less code duplication, and avoids the astyle issue.

Unless I'm missing something I don't think I can make something like that in C++11.  Variable templates are a C++14 addition according to my compiler.  Though, I can't say I'm all that experienced with functional C++.

I instead just defined `return_true` as taking a `const item &` in cata_utility to clean things up a bit. 

This also stopped my clang from crashing which is nice, should fix the CI clang builds as well.

**Comment by ifreund** [comment]
Ended up needing to go a bit farther than I had initially planned to properly handle component selection in crafting.  I've done a good bit of testing already and will be playing on this more tomorrow to make sure no bugs pop up.

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Pull request closed without merging**
