### PR TITLE
Spells: Adds optional bash_scaling fields to the SPELL type and unduplicate spells that used to require sub-spells to bash terrain

### PR DESCRIPTION
**Pull request by b3brodie**
#### Summary
Infrastructure "Adds bash_scaling fields to use with spells"

#### Purpose of change
If you wanted a spell to damage enemies and also damage the terrain, this necessitated using two separate spells with one that calls the other.  Implements the min_bash_scaling, max_bash_scaling, and bash_scaling_increment to dynamically determine bash damage instead of having to implement separate spells.

#### Describe the solution
Only functions for attack spell types currently since its the only one I see that has a good correlation with directly bashing terrain.

Adds optional min_bash_scaling, max_bash_scaling, and bash_scaling_increment values to the spell type.  If not defined these values default to 0.
The spells damage is multiplied by the calculated bash_scaling value, which starts at min_bash_scaling and moves towards max_bash_scaling depending on the bash_scaling_increment.  If the random damage flag is used then a random bash scaling is chosen between the min and max.

Largely duplicates the bash effects code for attack:  Cannot reuse the bash function because to pass the bash scaling value the parameters would have to be modified, and since its part of a map every spell effect type would have to be altered.  Cannot alter the bash effect to check if bash_scaling is <= 0 to determine if the attack should bash or not because that would effect that actual bash effect too.

Adds the bash scaling fields to all of the spells that utilize the duplicate spell definitions to bash terrain that I found in aftershock, magiclysm, mom, and xedra.

#### Describe alternatives you've considered
Adding a bash flag:  Doesn't allow for choosing between specific bash damage values.
Hooking bash scaling up to other spell effects.  None really seemed to fit, but if there's any suggestions it would be easy to do.

#### Testing
Created a character with each mod and tested all the spells.
Ex: MOM:
mind hammer still wrecks

### CODE REVIEW

**Comment by RedMisao** [comment]
Three questions: 
1. What's the difference or advantages in using this bash in the same spell instead of chaining a `bash` spell?
2. If `min_bash` and `max_bash` are not used, the spell deals 0 bash damage under its aoe, or no bash damage instance at all? In other words, are all `attack` spells dealing 0 bash damage or the function is not called unless `max_bash` >= 0 ?
3. What happens if you use negative bash values?

**Comment by b3brodie** [comment]
> Three questions:
> 
> 1. What's the difference or advantages in using this bash in the same spell instead of chaining a `bash` spell?
> 2. If `min_bash` and `max_bash` are not used, the spell deals 0 bash damage under its aoe, or no bash damage instance at all? In other words, are all `attack` spells dealing 0 bash damage or the function is not called unless `max_bash` >= 0 ?
> 3. What happens if you use negative bash values?

1. The primary advantage is that using bash_scaling is 1-3 lines of code to write, in comparison with the current setup where a user has to write 30 lines of essentially duplicate code.  In terms of functional effect there should be no difference, at least in all the spells I have seen in the current codebase.
2. This gets into the confusing terminology around an attack spell that deals bash damage and a bash spell.  Of these two spell types, the attack spell that deals bash damage will damage enemies (with bash damage) but not damage the terrain.  The bash spell effect will damage the terrain but not damage enemies.  Bash Scaling links the bash spell type to the attack spell type.  If bash scaling is not defined then the attack spell will do zero damage to the terrain, but will have no change to the amount of bash damage to enemies that it may have defined.  Codewise, the extra part to cause bash damage to the terrain is not called at all unless bash_scaling() > 0.
3. Mentioned prior, but unless bash_scaling() > 0 nothing happens.  This probably means you could have a min bash scaling of -1 and a max bash scaling of 1 and then it would only bash terrain based on how the spell is set up to move between those numbers, but generally negative numbers don't do anything.

**Comment by Psithief** [comment]
Is this related to `XAEA_line` at all? I can't figure out if that one is supposed to do terrain and creature damage, or just terrain damage.

**Comment by b3brodie** [comment]
> Is this related to `XAEA_line` at all? I can't figure out if that one is supposed to do terrain and creature damage, or just terrain damage.

I didn't touch the line spell because I'm not sure why it casts the bash spell about 6 additional times. Potentially the line could be converted over though if I knew why it did that.  For my testing though the line does do terrain and creature damage

**Comment by emixa-d** [comment]
On XAEA_line: I got the impression that it would attack multiple lines (could perhaps be tested by spawning multiple monsters in different places?), hence the repeating, but it's not something I've tested.

**Comment by Psithief** [comment]
I'm asking about XAEA_line because I can't get it to do anything myself and was hoping someone else might test it.
#76743

**Comment by Maleclypse** [comment]
> > Is this related to `XAEA_line` at all? I can't figure out if that one is supposed to do terrain and creature damage, or just terrain damage.
> 
> I didn't touch the line spell because I'm not sure why it casts the bash spell about 6 additional times. Potentially the line could be converted over though if I knew why it did that. For my testing though the line does do terrain and creature damage

To make sure it destroys everything it hits I think

**Comment by b3brodie** [comment]
> > > Is this related to `XAEA_line` at all? I can't figure out if that one is supposed to do terrain and creature damage, or just terrain damage.
> > 
> > 
> > I didn't touch the line spell because I'm not sure why it casts the bash spell about 6 additional times. Potentially the line could be converted over though if I knew why it did that. For my testing though the line does do terrain and creature damage
> 
> To make sure it destroys everything it hits I think

Oh I think I understand.  Its to get around the issue where, for example, dealing 10000 bash damage to a door will just leave a broken door because the bash doesn't roll over to destroy the next stage of the remaining?  Unfortunately this change won't do anything about that, so at most only one of the subspells could be removed in order to keep the current functionality.  I don't feel that's worth changing at the current time.

**Pull request merged**
