### PR TITLE
Makes loot in military locations more realistic and rewarding

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary
```SUMMARY: Balance "Increases military location loot"```

### Purpose of change
Military bunkers/ military outposts used to contain <100 rounds of ammo on average, while the turrets protecting it carries thousands of rounds. Players almost never took the effort to raid military installations other than boredom because they were not a good location to raid for ammo and gear, which is unlike both gameplay and real life expectations.

#### Describe the solution
Significantly upped the amount of ammo you can find in military bunkers, outposts, and the missile silo.
Raiding a military outpost, bunker,  or the silo will now be a major turning point in a run like raiding a lab is. 

Before this change military bunkers would mostly contain <100 bullets, while the turrets protecting it had 9600 rounds of .223. Raiding the bunker should now give you somewhere between 1-2k of ammo of various calibers, a good amount of grenades, but maybe more importantly, a reliable way to get ammo for heavy weapons. 

Amount was based on some ballpark estimates of what a real life depot of similar size would hold, and assuming somewhere between a 90-99% depletion rate during the cataclysm. It's a lot more than it was before.

#### Describe alternatives you've considered
Waiting for someone to completely rework the military locations.
Making the military locations a more challenging place to raid before increasing the loot. ( I would have loved to do this right away but it's not something i have experience with yet)
Leaving military outposts and bases as mostly obsolete content.

#### Testing
Loaded up the world with the changes and checked out multiple military bases and outposts to check if things are working correctly.

#### Additional context
Makes the military bunkers feel a lot more like this:
image
And less like an empty hole in the ground.

The first bunker in bunker.json uses a different loot spawning method than the others. i didn't feel comfortable trying to update it to the new standard so i adjusted the values of the old one to make it feel right. If someone would like to convert it it would be a good small project.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
This is a step in the right direction. But without looking up what one could expect to find in a military bunker/ Quonset hut equivalent, and/or doing some math based on the # of personnel in the area (I'm pretty sure mark's mentioned this somewhere) and the density of military installations in NE, duration of operations... etc, this is mostly just a game balancing thing.

Which is fine, but shouldn't be the final word here.

**Comment by Brian-Otten** [comment]
I did some estimates on that and some research, and all the numbers i came up with were essentially much larger than what is in this PR, to simulate a good 95-99% being gone already by the time your survivor gets to the bunker. Because what exact amount would get used during the cataclysm according to lore, and how much is looted before you get there, is so subjective, i think using real world as an upper limit and balance as a guideline is not a terrible approach.

However, if anyone wants to further tackle this, or suggest/make edits in this PR/ feel absolutely free. None of these numbers are set in stone, and the goal for me here was to get the drops closer to a good place.

**Comment by esotericist** [comment]
> did some estimates on that and some research

if you did research that's pertinent, you should include some of what you based your estimates off of.

Otherwise, as far as we can tell, you just made things up and put the "realistic" label on it.

**Comment by Brian-Otten** [comment]
https://alu.army.mil/alog/issues/sepoct10/spectrum_smallarms_ammo.html
Important excerpt.
image
I'm going to assume a conservative stockpile of 3 years worth of current usage, and say the US has 5.1 Billion rounds stockpiled. If we divide that by active US personnel That's about 3900 rounds stockpiled for every serving member in the US army.

If we assume the military outpost/military silo has about 20 peoples portion of that ammo, we get a starting estimate of about 78500 bullets.
If we assume the bunker carries about the portion of supplies for a 100 men, we get 390000 rounds of ammo.

If we say 95% is gone by the time the player gets there, this would still be almost 4k rounds for the outpost and 20k rounds for the military bunker.

**Comment by tenmillimaster** [comment]
>If we assume the military outpost/military silo has about 20 peoples portion of that ammo, we get a starting estimate of about 78500 bullets.

Can we instead use either a marine platoon (43 marines, 7 30 rounders each) or a section?

**Comment by Brian-Otten** [comment]
That would actually fit the amount of 5.56 we find really well, assuming somewhere between 85%/95% loot rate. The problem is that the game has a ton of variety in guns and ammo types, most of them assumed to be in use by the military. If you give the military outpost a total amount of ammo for the combat loadout of 43 marines, 9010 bullets, then assume a 95% looted rate and get 450 bullets. It ends up getting spread over 10-12 different calibers, and you only have 30-40 bullets for each separate gun. Meanwhile the turrets above a bunker just dropped 9600 rounds for the 5.56.

If you assume the loot rate is lower than 95%, you get back to the same kinds of ammo numbers as you'd find with this PR merged.

**Comment by esotericist** [comment]
> The problem is that the game has a ton of variety in guns and ammo types, most of them assumed to be in use by the military. If you give the military outpost a total amount of ammo for the combat loadout of 43 marines, 9010 bullets, then assume a 95% looted rate and get 450 bullets. It ends up getting spread over 10-12 different calibers, and you only have 30-40 bullets for each separate gun. Meanwhile the turrets above a bunker just dropped 9600 rounds for the 5.56.

There's absolutely no reason for us to attempt to represent all of our guns and ammo types in these locations. It should only reflect the weapons and munitions they would actually be issued, and in the appropriate proportions they would be issued.

**Comment by esotericist** [comment]
On a related note: the turrets long-term are going to be depleting much (possibly most or all) of their rounds dynamically before the player gets to them. You shouldn't be focusing on how much they give, when working out how much should be stored in the facility itself.

**Comment by Brian-Otten** [comment]
The people that wrote the ammo split of the military itemgroups already tried to make the distribution of the various military rounds make sense, but admittedly the ammo groups have swollen even more since that time and it would definitely not be amiss for someone to have a look at what ammo spawns where, and make sure it all spawns in sensible locations.

That would be a pretty big project though, crosschecking most/all item groups with ammo in the game and the locations and amounts they spawn in, and then making it so you adjust them without defacto deleting some guns from the gun by removing their ammo from the world.

As for what amount we want to be finding in these places, i'll go post a screenshot or two to benchmark what the settings are now, and we can see if we can find where we would like them to be. I'm okay with pretty much any suggestions/adjustments.

**Comment by esotericist** [comment]
if the existing item groups do not get you what your research says you should get for these locations, either a) the existing item groups are wrong and need to be fixed to get what your research says, b) new item groups need to be made that match your research, or c) the items need to be specified in the map definitions themselves.

in this case, i favor b) as an option, but I'm not one of the map people so don't take that as writ in stone.

**Comment by Brian-Otten** [comment]
image
image

Contents of the live in bunker



image
image

Contents of nuclear silo

image
image
Contents of military outpost

image
Military storage bunker

As always, item spawns are still semi randomized. it seems the military storage bunker had a low roll this run.
These should give some idea of where the spawns are at now with this PR.

**Comment by Brian-Otten** [comment]
I would like B of those options as well. but i would be hard pressed to say what ammo in the above examples should be removed. let alone where they would be moved to. I find it hard to judge what ammo the cataclysm military is stocking partially because of the addition of the rivtech weapons and all it's ammo variants.

**Comment by Brian-Otten** [comment]
For comparisons sake here is me documenting my finds in some standard mainline military locations.
image
Military storage bunker
image
Military outpost.

**Comment by Night-Pryanik** [comment]
I don't like 100% chance to spawn magazines and ammo. I think we should always let space for case of absence.

**Comment by 1n17** [comment]
You wont please both sides, you can either have realism or challenge here. And that would be even more pronounced if you tried to adhere to the story (ie. 'it all happened within the space of one day') and extrapolate state of military installation supplies from that.

**Comment by Brian-Otten** [comment]
I think absence might best be done by making a separate "looted" military location, like the evac shelter now. Some alternate ideas that were discussed was to make the military locations have a decent chance to not spawn with enemies, but filled with a small group of armed, hostile npc's. (soldiers still bunkered up from before the cataclysm gone crazy, or raiders.).


I understand some of the realism/balance concerns, in that this is probably still quite low to be "realistic" while still being a lot of loot.

And i think it won't be that much of a problem, because the military installations are already one of the harder locations to raid in the game. the military installation in particular is a rather fun little challenge, with turrets surrounding it and secubots, dispatch drones, and zombie bio operators inside.

If you can handle that, you are already solidly at cataclysm's endgame, so this would give characters that have reached that level an alternate activity to raiding labs for the lab barracks. and would hopefully somewhat expand the range of weapons available to use. having players use heavy weapons, grenades, and some of the other weapons wouldn't be much stronger than having players use a .556 rifle and a .50 sniper for everything, but would add to gameplay variety a decent bit.

**Comment by Ker-Nes** [comment]
> Can we instead use either a marine platoon (43 marines, 7 30 rounders each) or a section?

43 marines is fine. 210 rounds for each of them is not. That's what they (ideally) carry in a mission, as I understand, not what they have stockpiled in a base, bunker or even FOB.

**Comment by Amoebka** [comment]
Realistic ammo amounts seem crazy generous because zombie numbers are "unrealistically" low. And making them "realistic" (i.e. tens of thousands per town) isn't even an option because there just isn't enough tiles to place them all.
Ultimately this all runs into the problem of maps being scaled down too much.

**Comment by Brian-Otten** [comment]
If i were to formulate an amount based purely on balance, setting realism aside this is probably the approach i would take:
Currently the player mostly gets their ammo / weapons from turrets and the lab barracks, both found in the lab. setting aside the turrets, the lab is currently the one stop shop for almost all high end loot in the game, and one lab will contain a couple lab barracks. A military outpost or bunker would need to have a decent amount more military loot than the lab barracks for the player to find it worthwhile to raid. I would suggest 3x and 5x for the outpost and bunker respectively. I'll go ingame now and run some quick tests to see how much ammo is currently spawning in lab barracks and see what that might imply for the amount in military locations.

**Comment by Brian-Otten** [comment]
So, numbers we could end up adjusting to:
about 100 rounds  = current drops
about 600 rounds  = Just enough so people might risk raiding military locations
about 1500 rounds = low end of realistic
3000+ rounds = realistic, nearing the maximum we want to put in game without undue clutter.

This PR is calibrated for 1500 rounds right now, but if we decide on another number i can calibrate it to those settings.

**Comment by Amoebka** [comment]
In a perfect world labs wouldn't have barracks and military bunkers would be proper locations instead of 1 tile loot shops, but this is not a perfect world.

**Comment by thethunderhawk** [comment]
@amoebka According to the “background” page of the design doc, 12 years before the start of the game a DARPA lab doing portal research was completely destroyed by a creature from the netherum. I always figured that since then, portal research facilities would tend to have a garrison to protect the facility from threats like that.

**Comment by 8street** [comment]
A good idea. But a 100% spawn chance is too simple. I think it would be better if the chance were say 5-10% with 3000+ rounds in a mil location.

**Pull request merged**
