### PR TITLE
Add acetic acid dilution recipe

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Add acetic acid dilution recipe"```
#### Purpose of change

Adds a recipe to dilute acetic acid to make vinegar. Vinegar in its basic form is, for the most part, acetic acid diluted in water, so this should work. I've also made it possible to use unclean water to make vinegar (as concentrated acetic acid would probably kill any microorganisms in there, making it safe to use in cooking). Amount of vinegar used to make acetic acid also got increased, to preserve volume and not create acetic acid out of nowhere.
#### Describe the solution

JSON editing.
#### Describe alternatives you've considered

None.
#### Additional context

I have no idea about how concentrated the acetic acid item is in-game, but in case it's pure acetic acid, resulting vinegar would contain 10% of acetic acid by volume, and in case it's 40% acetic acid solution, it'd be 4% of acetic acid. Both seem kind of reasonable.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
I think it's safe to consider concentrated acetic acid 'glacial acetic acid', as that's what would be found in labs.

**Comment by I-am-Erk** [comment]
Yes, I only didn't call it glacial because I wasn't sure the average player would know the term.

**Comment by kevingranade** [comment]
You chemistry experts want to weigh in on whether this is reasonable?
In particular, IDK if the recipe chain of (possibly dirty) water -> vinegar -> acetic acid -> lab stuff is reasonable.

**Comment by I-am-Erk** [comment]
Wait, did I add concentrated acetic acid or was it already in game?

Anyway, the recipe suggested here is fine although maybe should be restricted to clean water. I haven't checked proportions.

The older recipe, making glacial acetic acid by boiling vinegar, doesn't really work.

**Comment by Rail-Runner** [comment]
> The older recipe, making glacial acetic acid by boiling vinegar, doesn't really work.

Should I simply remove it then, or there is some other way to concentrate acetic acid present in vinegar?

**Comment by I-am-Erk** [comment]
You were faster than my edit. The fine distillation quality would be all it really needs. I can find the tag for you

**Comment by Rail-Runner** [comment]
Done,

**Comment by tenmillimaster** [comment]
Quick math check for the proportions of the dilution recipe (glacial->white vinegar soln)

[Assuming vinegar implies a 5% v/v acetic acid:water solution](https://www.walmart.com/ip/Great-Value-Distilled-White-Vinegar-1-gal/10450998), and that we want to make a 5% solution from concentrated acetic acid:

Our givens: [Concentration of glacial acetic acid: 99.8g/1000g soln](https://www.sigmaaldrich.com/chemistry/stockroom-reagents/learning-center/technical-library/reagent-concentrations.html), [density of acetic acid: 1.049g/mL](https://en.wikipedia.org/wiki/Acetic_acid). 

The smallest unit of Glacial Acetic Acid(GAA) in game is 250mL, or 262.5 grams of GAA. At 99.8% purity w/w, that's 99.8 grams Acetic Acid(AA) per 100 grams solution, or 261.975g AA per 262.5g GAA. As a ratio, this is 261.975g AA : 0.525g H2O. 

A 5% v/v acetic acid soln(our average household white vinegar) is 5mL acetic acid per 100mL solution. As a ratio this is 5mL AA : 95mL H2O. Converting to w/w this is 5.245g AA : 95g H2O. Bringing the mass of AA to the lowest we can obtain from GAA the ratio is 261.975g AA : 4745.019 g H2O. 

Thus, to turn the smallest unit of GAA into 5% vinegar solution we need to add (4745.019g - .525g) = 4744.49g of water. Expressed in units of 250mL, this is 18.978 1/4L's. 

So with the smallest unit of GAA we can work with, we need to add 19 units of water to make white vinegar. This yields approximately 20 units (5L)  of vinegar.

This was probably a lot more mathy than it needed to be but there ya go.

**Pull request merged**
