### PR TITLE
Update swords_and_blades.json

### PR DESCRIPTION
**Pull request by TJKing293**
#### Summary
content "balancing karambit"

#### Purpose of change
rebalancing the karambit

#### Describe the solution
none

#### Describe alternatives you've considered
none

#### Testing
tested in game

### CODE REVIEW

**Comment by I-am-Erk** [comment]
image
At the very least attempt to justify yourself, but bear in mind that this is reaching a point where people with merge powers are getting really annoyed about the amount of bikeshedding going on over this very minor item.

**Comment by TJKing293** [comment]
I have been trying to justify it. I have linked videos and posted pictures and tried to explain it, the original damage was bashing 6 piercing 20. I was told to switch the damage type to cutting, and drop the damage to single digits. I did both. It's been pretty much decided it's a crappy wall hanger, about as dangerous as a pocketknife.

**Comment by I-am-Erk** [comment]
By "justify yourself" I am referring to the PR description. I have not been following your conversations on discord.

```
Purpose of change

rebalancing the karambit
Describe the solution

none
```
This is not a sufficient justification. We have those fields for a reason. When you've been specifically told that a damage change isn't going to be merged, and still decide to open a PR, you need an *iron clad* explanation here, not an empty field.

I understand you're passionate about this and that is totally fine, even praiseworthy, but you're also not listening to people telling you how to engage with the team and the project as a whole. That isn't going to work, we're not trying to make your life harder, we're trying to manage a very complex and active project and we don't want to have to keep repeating ourselves to someone not processing feedback.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/adding-a-karambit-sorry/27749/2

**Pull request closed without merging**
