### PR TITLE
Refactoring paths [FILENAMES]

### PR DESCRIPTION
**Pull request by Andres6936**
#### Summary

```SUMMARY: Infrastructure "Cleaning of code, from functional to object-oriented programming"```

#### Purpose of change

Reviewing the code base I have found parts where the code is read in an illegible and unclear way, due in part to the programming practices of the past and the lack of documentation, there are also parts where the code follows the line of functional programming and the use of unnecessary namespace, in addition to the use of the fearsome global variables.

#### Describe the solution

I have moved the sections from code written in functional programming to object-oriented programming, removed unnecessary name space, global variable and retired support for legacy files, added extensive and clear documentation to all methods of the new class.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm really not interested in arguing the point, but a singleton is not meaningfully different from a global variable, so making that change does not intrinsically justify a change, much less a large one.

In addition, you seem to have disabled several command line options we support surrounding adjusting the paths used by the program, and removed some legacy file handling.

Upon further review of the previous too-large PR, I'm at a loss to determine what your goals are here.  You are making a large number of changes revolving around practices not followed by this project.

**Comment by Andres6936** [comment]
@kevingranade, I don't want to generate discomfort with my changes, like the vast majority I only seek to help the project, the elimination of support for legacy files is a necessary change, has been there for more than 3 years, Singleton is a way to achieve a modernization of the code (which I seek to replace, because I am aware of its limitations), the removal of options by command line is temporary, not definitive, so this PR is marked as Draft, to resolve current conflicts.

I understand that my changes are annoying because they imply a big change, to add little or no functionality, but I do not try to add, only correct.

I lament that my goals here are questioned ....

_For a great solution, great changes._

**Comment by I-am-Erk** [comment]
> elimination of support for legacy files is a necessary change
I think you'd have to make much more of an argument than that for such a sweeping change.

**Comment by Andres6936** [comment]
@I-am-Erk, I don't consider it a "radical change", I consider it more like a refactoring, my code comes to fulfill the same functions as the previous one , it doesn't add new functionalities, it's an improvement, nothing more....

I've been studying the code for more than 3 months, and the areas that interest me are the refactoring, not the additions of functionality or modifications (mods), in fact there are already many collaborators in those areas that do an excellent job, my work there would not have great value.

**Pull request closed without merging**
