### PR TITLE
Fixed Coughing during a cold prevents sleeping even when Dead Tired

### LINKED ISSUE #33588: Coughing during a cold prevents sleeping even when Dead Tired
# Describe the bug

This is certainly not your usual cold :)

[2019.08.27.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547167/2019.08.27.zip)
0.D-7016-gf918a1454e-dirty

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fixed Coughing during a cold prevents sleeping even when Dead Tired"

#### Purpose of change
Fixes #33588
Fixes cough suppression not preventing stamina loss for prevented harmful coughs
Greatly reduced chances of waking up from coughing. Reduced fatigue recovery shortly after coughing.

#### Describe the solution
Moved cough suppression return code to top 
Removed chance to wake up from cough method.  There is still a chance to wake up based on the sound but its more realistically frequent.  Added effect coughing for 5 minutes after coughing that reduces fatigue recovery while sleeping

#### Describe alternatives you've considered
I attempted to build an option to auto retry sleeping after waking, but couldn't get it to feel/work right.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
This could lead to eternal sleep if one is coughing too frequently while sleeping?

**Comment by Ramza13** [comment]
> 
> 
> This could lead to eternal sleep if one is coughing too frequently while sleeping?

Hmmm,  I guess that's true it didn't happen with the flu but under the right circumstances it could. Shoot.

**Comment by I-am-Erk** [comment]
I think the fatigue effect is a really good idea... Could you store how much fatigue is being generated, and have it applied as an effect upon waking up?

**Comment by Ramza13** [comment]
To prevent infinite sleeping I changed it so that now for five minutes after coughing you only recover half as much fatigue from sleeping.

**Comment by I-am-Erk** [comment]
That's a very good fix

**Comment by l29ah** [comment]
Re-tested with the saved game from #33588, and i still wake up after 1-3 coughs.

**Comment by l29ah** [comment]
Oh, that was because i had enhanced hearing enabled.

**Pull request merged**
