### PR TITLE
ChestHole Tileset

### PR DESCRIPTION
**Pull request by Chezzo**

### CODE REVIEW

**Comment by KA101** [comment]
Careful with merging from your master branch (tough to break out changes if one thing is good but not another, basically a problem if we reject something or you want to PR more  than one thing at once).

Friendly reminder that DDA is CC-BY-SA so once this merges, it's in and people can remix.  If you've got a problem with that (some artists have in the past), now's the last chance to leave.

**Comment by Chezzo** [comment]
Oh, right. That makes sense. Do you want me to re-do it with the experimental? 

I haven't got a problem with that.

**Comment by KA101** [comment]
>Oh, right. That makes sense. Do you want me to re-do it with the experimental? 

Uh, no, that was a suggestion to make new branches for each update and PR those (then update your master branch once we merge 'em) rather than using your master branch to file PRs.

Is this to current spec (we've frozen content additions so you and the other artists can catch up), 0.B stable, or something else?

**Comment by Chezzo** [comment]
Okay, I think I've got it.

It is current to 2709, which I think is after the freeze. I just went over to Windows and downloaded the latest experimental, and the opening room and running around for a minute looks good.

**Comment by KA101** [comment]
Yeah, that was the test I ran.  Needs more helmets and such but it's good to have folks paperdolling; we can work out the rest as you get 'em in.

**Pull request merged**
