### PR TITLE
Crowbar now respects json ammo overrides

### LINKED ISSUE #53607: [Magiclysm] Technomancer mana-toolbar spending charges incorrectly
### Describe the bug

While using the technomancer mana-toolbar, charges are used in order to pry open windows and doors, even though they should presumably only be used by casting mirror image from it. When out of charges, the toolbar is unable to pry windows or doors.

### Steps to reproduce

1. Spawn a technomancer mana-toolbar, attempt to pry a window or door, see that it doesn't work.
2. Wait long enough for the toolbar to gain 1 charge
3. Pry the window or door again, see it successfully pry but lose 1 charge for doing so.

### Expected behavior

For prying objects open to not spend any charges of the spell in the item.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9bbe06e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### LINKED ISSUE #53813: Magiclysm: Technomancer Mana-Toolbar can't pry without charges
### Describe the bug

If you try to pry a crate/window with the technomancer mana-toolbar it will stop you if you don't have any charges and say:
"You attempt to pry open the window using your Technomancer mana-toolbar...
Your Technomancer mana-toolbar ran out of charges."
this seems like a bug to me as I doubt that you would be unable to pry with something crowbar shaped just because it ran out of charges.

### Steps to reproduce

1: Obtain a Technomancer mana-toolbar and a crate/window
2: Attempt to pry using the examine button
3: Get the message alerting you that you can't pry without charges

Alternatively
1: Obtain a Technomancer mana-toolbar and a crate/window
2: In the activate menu see that you can't activate any features of the crowbar when it is out of mana

### Expected behavior

As stated above I do believe that as the Technomancer toolbar is crowbar shaped it would make sense for it to be able to pry while it is out of charges. I believe that it is broken this way simply because of some standardization of the activation code that is prohibiting this.

### Screenshots

image

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-4631-ga342e1eae3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Note my game version is only dirty because of some slight json editing I have done in totally unrelated files (stuff like adding belt clip tags to bags of holding)

### LINKED ISSUE #54120: Functionality of #50319 is broken
### Describe the bug

#50319 was supposed to allow some `use_actions` to use different amounts of charge than others. Specifically the crowbar/hammer use actions for the gunsmith and firearm repair kits. Although the (%)item action menu says that some actions will take 0 charge, they will actually take the normal amount defined by `charges_per_use`

### Steps to reproduce

1. Get a fully charged gunsmith/firearm repair kit.
2. Find a crate. (or edit the kit to have prying 3 and find a window)
3. Use the "(a)pply or use item" or "(%)item action menu" to pry it open with the kit. (This shouldn't use up any charge.)
4. Look at the kit and see that current charge is now less than maximum charge.
5. Be sad.

### Expected behavior

Successfully using the prying action with the gunsmith repair kit shouldn't cost energy. 

### Screenshots

image
image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d532033 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

### Additional context

A similar issue is #53620, but it's not quite the same. Fixing this would also make it possible to fix some other issues such as #53813 and #53607, and possibly more. Additionally, actions without explicit `use_actions` also sometimes unintentionally use up charges sometimes. (writing on stuff with the Kelvinist Frostbind uses its mana (curiously using it as a weather tool does not???))

### LINKED ISSUE #55123: Gunsmith & Firearm Repair Kits need batteries to pry open crates
### Describe the bug

The Gunsmith and Firearm repair kits have, as part of their components, a Hammer, which has a prying ability of 1 - the same as a Makeshift Crowbar. 

However, if you try to open a sealed crate with them, the result will be the game telling the player they have no charge to work with. It also seems that the game prioritizes these kits for prying purposes, even if you have an actual loose hammer or crowbar in your inventory for this.

Seeing as they are "kits", one would assume that the hammer, as well as any other non-battery related tools, would not be converted to requiring batteries to operate - as in, someone would just be able to open the box/unfold the folder the items are in, retrieve what they need and use it.

However, if you reload them with batteries, to pry open a crate, the Firearm repair kit uses 100 charges, the gunsmith repair kit uses 25.

### Steps to reproduce

1. create a world in a scenario that gives you easy access to crates ("Safe Place" > "Light Industries"), give yourself 20 strength;
2. Debug yourself a Hammer, a makeshift Crowbar, a gunsmith repair kit and a firearm repair kit with no batteries.
3. Align the 5 crates in a way so that you can try and open 1 crate with each tool.
4. Notice that the 2 kits will not operate without batteries. 
5. Recharge them with a Light and Medium Disposable Batteries (Firearm and Gunsmith kit respectively)
6. Notice as crates can now be opened, but Battery charges will be used instead.

### Expected behavior

Using a non-powered tool from a tool bundle item should not require for charges to be used, as placing a hammer or a chisel inside a box / bag does not make them automatically electrical tools.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 7efd4f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Log order is reversed: 
Older messages below, newer messages above. 
Order of tool usage:
Makeshift Crowbar > Hammer > Firearm Kit > Gunsmith kit. and after reloading, "Firearm Kit > Gunsmith Kit".

### LINKED ISSUE #56741: Technomancer Mana Toolbar uses Charges on prying
### Describe the bug

Using the Technomancer Mana Toolbar as a Crowbar uses up the charges in the Toolbar. When no charges are left the Toolbar can not be used as a crowbar.

As long as it has charges it works from both (e)xamine and (a)ctivate.

### Steps to reproduce

Spawn in a Technomancer Mana Toolbar.

Use it on a closed crate. Repeat on crates until charge is spent.

Observe that after charges are spent the Toolbar will not pry open the crate.

### Expected behavior

After Cataclysm-DDA experimental build 2022-04-09-0507 I expected it to act as the crowbar where appropriate.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.593 (21H2)
- Game Version: 9f9b09d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ducanishah**
#### Summary
Bugfixes "firearm and gunsmith repair kits, innawoods blacksmith toolkits, and magiclysm toolbars do not use charges to crowbar"

#### Purpose of change
Prying with the mundane tool part of a kit should not consume charges. Hacksaw usage was given this upgrade, but crowbar usage was not. This fixes the crowbar-consuming-ammo bug of four different kits.
Fixes #56741
Fixes #55123
Fixes #53813
Fixes #53607
Fixes #54120

#### Describe the solution
Apply the same fix from the hacksaw activity_actor to the crowbar activity_actor- use a string to define the method, then use the overload of ammo_sufficient defined in #50319 to check if the item has a special power scaling for the crowbar use action.

#### Describe alternatives you've considered
Reworking every single instance of ammo usage to use the better ammo_sufficient and ammo_scale functions.

#### Testing
Spawn firearm repair kit, do not load, pry crate. Works fine. Load with battery, pry crate, no charge consumed. Did the same with blacksmith kit (inna), gunsmith repair kit (base) and technomancer mana toolbar (magic).

#### Additional context
This DOES NOT make this behavior of json overrides for use actions generic, and notably leaves open #55158, as I will need to go in and add override functionality and overrides for all tools in that kit. I would love to theoretically make the functionality of #50319 generic so that any usage can have a json override for charge scaling, but I figure I'll have to do it piecemeal as the code for consuming ammunition is not standardized across different kinds of actions.

Amusingly, while there were multiple open issues about the firearm kits and the toolbar, there were no open issues about the blacksmithing kit from innawoods.

### CODE REVIEW

**Comment by Sathra225** [comment]
For Innawoods, it probably never came up as the blacksmithing kit is so easily reversible and you rarely have to deal with actually using it for anything but repairing.

**Comment by ducanishah** [comment]
> For Innawoods, it probably never came up as the blacksmithing kit is so easily reversible and you rarely have to deal with actually using it for anything but repairing.

It has also occurred to me that there really isn't much to *pry* in innawoods, being, as it says, in the woods.

**Comment by catdach** [comment]
>This DOES NOT make this behavior of json overrides for use actions generic, and notably leaves open https://github.com/CleverRaven/Cataclysm-DDA/issues/55158, as I will need to go in and add override functionality and overrides for all tools in that kit. I would love to theoretically make the functionality of https://github.com/CleverRaven/Cataclysm-DDA/pull/50319 generic so that any usage can have a json override for charge scaling, but I figure I'll have to do it piecemeal as the code for consuming ammunition is not standardized across different kinds of actions.

When you get to this, #53620 will be another one that can be closed. (because their _clearly_ aren't enough things connected to this PR already 🤣)

**Comment by ducanishah** [comment]
> > This DOES NOT make this behavior of json overrides for use actions generic, and notably leaves open #55158, as I will need to go in and add override functionality and overrides for all tools in that kit. I would love to theoretically make the functionality of #50319 generic so that any usage can have a json override for charge scaling, but I figure I'll have to do it piecemeal as the code for consuming ammunition is not standardized across different kinds of actions.
> 
> When you get to this, #53620 will be another one that can be closed. (because their _clearly_ aren't enough things connected to this PR already 🤣)

This will NOT close #53620, sadly. This adds a json override for specifically the crowbar use action, to complement the existing overrides for transforms and hacksaw use action. This is not a generic solution, and I will have to go through the code for every iuse or activity_actor and update them to close #53620, as that wants it to be applicable to _any_ usage.

**Comment by catdach** [comment]
> > > This DOES NOT make this behavior of json overrides for use actions generic, and notably leaves open #55158, as I will need to go in and add override functionality and overrides for all tools in that kit. I would love to theoretically make the functionality of #50319 generic so that any usage can have a json override for charge scaling, but I figure I'll have to do it piecemeal as the code for consuming ammunition is not standardized across different kinds of actions.
> > 
> > 
> > When you get to this, #53620 will be another one that can be closed. (because their _clearly_ aren't enough things connected to this PR already 🤣)
> 
> This will NOT close #53620, sadly. This adds a json override for specifically the crowbar use action, to complement the existing overrides for transforms and hacksaw use action. This is not a generic solution, and I will have to go through the code for every iuse or activity_actor and update them to close #53620, as that wants it to be applicable to _any_ usage.

Sorry, I wasn't being clear. What I meant say was; ***WHEN*** (_in some PR in the future, **not this PR**_) #55158 _would_ be closed, #53620 could also be closed at _that_ point (as they are similar issues). just trying to add a note for the future so that it doesn't get forgotten about after it is (_at some point in the future_) fixed.

**Comment by ducanishah** [comment]
> > > > This DOES NOT make this behavior of json overrides for use actions generic, and notably leaves open #55158, as I will need to go in and add override functionality and overrides for all tools in that kit. I would love to theoretically make the functionality of #50319 generic so that any usage can have a json override for charge scaling, but I figure I'll have to do it piecemeal as the code for consuming ammunition is not standardized across different kinds of actions.
> > > 
> > > 
> > > When you get to this, #53620 will be another one that can be closed. (because their _clearly_ aren't enough things connected to this PR already 🤣)
> > 
> > 
> > This will NOT close #53620, sadly. This adds a json override for specifically the crowbar use action, to complement the existing overrides for transforms and hacksaw use action. This is not a generic solution, and I will have to go through the code for every iuse or activity_actor and update them to close #53620, as that wants it to be applicable to _any_ usage.
> 
> Sorry, I wasn't being clear. What I meant say was; _**WHEN**_ (_in some PR in the future, **not this PR**_) #55158 _would_ be closed, #53620 could also be closed at _that_ point (as they are similar issues). just trying to add a note for the future so that it doesn't get forgotten about after it is (_at some point in the future_) fixed.

Oop--
You were totally clear, I just blanked out looking over your quote. My bad mate, you're entirely correct :p

**Pull request merged**
