### PR TITLE
Disable hassle-causing egg spawns.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: None```

#### Purpose of change
Whatever there is to be said about the carrion system *aspirationally*, it isn't working as intended right now, leading to both crippled farming and "roach farming" due to errors in the balance that should prevent it.

#### Describe the solution
Just disable the problematic spawns for now, and if someone wants to champion the feature later they can resurrect it.
Specifically this means removing all instances of GROUP_ROTTING_PLANT and GROUP_CARRION as well as the roach-related egg spawns.

#### Describe alternatives you've considered
There is no shortage of ideas for tuning the system, but for the release I've been convinced by a large amount of feedback that this is a feature that should not be part of the default game experience in its current state.

On further review, using rot spawn for anything but eggs is just a bad idea.  If we want a system to "attract vermin", we need to do that instead of enabling it via spontaneous generation.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Fully agree. That said: Maybe just change the default Options setting to "0%"? Then those who like the system can add it back in without file edits. I think there's good stuff here to salvage, and having it in where players can see it might help encourage someone to fix it.

**Comment by Mecares** [comment]
Would it be much additional work to implement it as an option that is turned of by default or make an option that allows to scale the spawn chance?

**Comment by I-am-Erk** [comment]
> Would it be much additional work to implement it as an option that is turned of by default or make an option that allows to scale the spawn chance?

All it would take is making a mainlined mod that re-enables them. I think it would be a good idea to do just that, although knowing Kevin and his workload I doubt he'll do it himself.

**Comment by Photoloss** [comment]
> EDIT: Nvm, as discord points out this would kill chicken breeding.

Wait, chicken breeding is tied to rot spawns??? I can fully understand reusing the same code behind the scenes but who in their right mind would associate "carrion spawns" with that and a locust plague of Biblical proportions?

**Comment by mlangsdorf** [comment]
acidia was a strange fellow.
chickens lay eggs along with their manure.
eggs rot.
chicks sometimes spawn from rotten eggs.
there's a certain economy of code usage in this system.

**Comment by I-am-Erk** [comment]
> acidia was a strange fellow.
> chickens lay eggs along with their manure.
> eggs rot.
> chicks sometimes spawn from rotten eggs.
> there's a certain economy of code usage in this system.

What's odd is that the rotten eggs -> chicks mechanic isn't even that bad, it's just cosmetically very strange.

**Comment by kevingranade** [comment]
Yea, the chicken egg thing came first, and it's not really a problem, it only became a problem when non-egg things started transmuting into living creatures. Even then, the mechanism wasn't the problem as much as the lack of backpressure on populations numbers, or an effective conservation of mass kind of thing.

**Comment by kevingranade** [comment]
Short of me making some mistakes, this is ready to go.

**Pull request merged**
