### PR TITLE
7.62x25 cartridge migration

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Since the 7.62x25 gun migration is on hold until #16488 is merged, I've created a separate PR for migrating the 7.62x25mm cartridges. I have also renamed 762.json and 762R.json to 762x39.json and 762x54R.json, respectively. As @Cyrano7 has mentioned, Github seems to send emails out describing even the smallest posts made, so I'll adopt a verbose style when describing any fixes made to the code. If anyone bugchecks the code, please consolidate your comments and refer to line numbers when reporting bugs.

### CODE REVIEW

**Comment by mugling** [comment]
> have also renamed 762.json and 762R.json to 762x39.json and 762x54R.json, respectively

Please don't do this. The names match the `ammo` fields

> If anyone bugchecks the code, please consolidate your comments and refer to line numbers when reporting bugs.

It's best to comment on specific lines. Individual users can set their notification preferences and/or unsubscribe from certain threads.

> Since the 7.62x25 gun migration is on hold until #16488 is merged, I've created a separate PR for migrating the 7.62x25mm cartridges.

Please follow the existing pattern of migrating one ammo type at once. Multiple overlapping PR's isn't going to result in any faster progress. I'm hoping to look at #16488 over the weekend but that shouldn't change the general approach in any case

**Comment by BorkBorkGoesTheCode** [comment]
> Please don't do this. The names match the  ammo  fields
The names match both the real life names and the names that appear in the "name": field. The fact that multiple 7.62 bullets with very different sizes share very similar names may create confusion, even if they are smaller and faster to write.


> It's best to comment on specific lines. Individual users can set their notification preferences and/or unsubscribe from certain threads.
Okay. I wanted to reduce the number of email blasts from Github.

> Please follow the existing pattern of migrating one ammo type at once. Multiple overlapping PR's isn't going to result in any faster progress. I'm hoping to look at #16488 over the weekend but that shouldn't change the general approach in any case

The 7.62_m43 and 762_54R cartridges are untouched. I just renamed the files.

**Comment by BorkBorkGoesTheCode** [comment]
[Somehow, Github decided to eat my comment. the following is a rewrite]

The new names match the real life cartridge names and the names that appear in the "name": field.

The 762_m43 and 762_54R cartridges are untouched. I just renamed the files.

**Comment by Cyrano7** [comment]
@BorkBorkGoesTheCode Comments are fine, I just meant that commenting back on every line note isn't really necessary, even to say thank you. Your saying thank you for pointing something out by fixing it.

**Comment by BorkBorkGoesTheCode** [comment]
@Cyrano7 Thanks for the clarification.

**Comment by mugling** [comment]
The names of the files should match the `ammo_type` field

**Pull request closed without merging**
