### PR TITLE
Rebalanced all effects for 1 second turns

### LINKED ISSUE #31657: Winded, quickly dying of dehydration for no apparent reason
# Steps To Reproduce

1. Load the game.
2. Check the anomalous event log and stats.
3. Wait for an hour.
4. You die of dehydration on day 1 with ~50 worth of quench points drank.

# Screenshots

# Versions and configuration

 - Game Version: 0.D-4695-g888f3e381b-dirty
 - Mods loaded: alt map key

# Additional context

[2019.06.04.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310709/2019.06.04.zip)

### LINKED ISSUE #31691: Common cold causes fatigue and dehydration at extreme rate
# Describe the bug

I believe, It's caused by #30253 . When player character suffer common cold (other diseases may also be affected) his/her needs are increasing with the extreme rate causing game to be almost unplayable (player need to sleep, drink and eat almost all the time)

# Steps To Reproduce

1. Obtain common cold effect.
2. Try to play with it for a while.

# Expected behavior

Common cold being less extreme as it used to be before.

# Screenshots
N/A

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4796-g8fd4c4a
 - Graphics version: Tiles
 - Mods loaded: probably not needed

# Additional context

None

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
```SUMMARY: Bugfixes "Multiplied all effect tick values by six."```

#### Purpose of change
Fixes #31691 
Fixes #31657 

#### Describe the solution
All tick values in effects.json were multiplied by six.

#### Describe alternatives you've considered
Trying to figure out what such a change would actually do to the game. Not sure if this is actually going to cause more problems than it solves.

#### Additional context
Marked as a draft because I haven't been able to test this yet.

### CODE REVIEW

**Comment by Inglonias** [comment]
Alright. Looks like this isn't going to horrifically break the game, so that's good. Opening this for review.

Major change. I changed the bleeding decay tick back down, as it directly causes loss of health pretty much every tick. To keep the total amount of health lost from bleeding about the same as it was before, that has been adjusted back down. Let me know if this is acceptable or not.

**Comment by dkargin** [comment]
Since this problem has occurred several times a month, I would think about writing more unit tests. I can think of the cases:
1. Time to starve to death, against some expected time period.
2. The same as 1 but with additional effects, like diseases, deprivations and so on.
3. The same for thirst.
4. Test for bleeding rate.

**Comment by Inglonias** [comment]
Thats a great idea.

I have no idea how to write the unit tests, but thats a GREAT idea.

**Comment by ZhilkinSerg** [comment]
> Since this problem has occurred several times a month ...

That's because we didn't migrate EVERYTHING to use 1 second turns yet.

**Comment by Inglonias** [comment]
Whatever the reason, unit tests are never a bad idea

**Pull request merged**
