### PR TITLE
Further JSON validation

### PR DESCRIPTION
**Pull request by mugling**
Previously JSON errors are reported in the finalization stage which can make the source ambiguous when either inheritance or multiple mods are in use. This PR extends `assign` to report more errors at source.

The following fragments are rejected immediately with their JSON source location:

```
{
    "id": "milk",
    "type": "COMESTIBLE",
    "//": "Assignment out of bounds",
    "stack_size": 0
}
```

```
{
    "id": "string_6",
    "type": "GENERIC",
    "//": "Assignment out of bounds",
    "bashing": -4
}
```

```
[
    {
        "id": "9mm",
        "type": "AMMO",
        "price": 2400,
        ....
    },
    {
        "id": "cheap_9mm",
        "copy-from": "9mm",
        "type": "AMMO",
        "//": "Assignment out of bounds",
        "relative": { "price": -2500 }
    }
]
```

Additionally (re-)defining a value then trying to `extend` or `delete` in the same definition is ill-formed:

```
{
    "id": "reloaded_223",
    "copy-from": "223"
    "type": "AMMO",
    "effects": [ "FOO" ],
    "extend": { "effects": [ "RECYCLED" ] },
    "delete": { "effects": [ "NEVER_MISFIRES" ] }
}
```

Before `reloaded_223` would have `flags` set to `FOO` with `RECYCLED` being ignored. After this PR you get a JSON load error at the point of the ill-formed definition.

Finally `assign` for `nc_color` is dropped as it wasn't called. Suggestions as to how to resolve that in the future are welcomed (@BevapDin?) but are beyond the scope of this PR so it's removed as dead-code for now.

### CODE REVIEW

**Comment by mugling** [comment]
Have updated `core` and mods to pass validation. Ready for merge testing.

**Comment by Coolthulhu** [comment]
I had some weird merge errors with this one and now this one got conflicts. One of the PRs merged recently must have been at conflict with this one.

**Comment by mugling** [comment]
It's likely to be the one with uncrafting as I cherry-picked from this PR. You can probably merge via picking the remaining commits?

**Comment by Coolthulhu** [comment]
Can you rebase it on your side? Using the github's merge tools helps with tracking, which is especially important with "risky" PRs that Jenkins refuses to look at (ie. ones that modify json.h and I think generic_factory.h).

**Comment by mugling** [comment]
> Jenkins refuses to look at (ie. ones that modify json.h and I think generic_factory.h

I think this only applies to `json.h`

> Can you rebase it on your side?

Yes, but not immediately. If you're happy with the review then I can rebase and merge later?

**Comment by Coolthulhu** [comment]
It complains about PK mod during `--check-mods`.
I didn't detect any other problems.

If you run `--check-mods` with this PR after rebase and it doesn't complain, it's good to go.
Regardless of whether the problem is in the PK mod or here, you should at least hack around it. PK mod is full of hacks, so one minor hack more shouldn't be a problem.

**Comment by mugling** [comment]
> If you run --check-mods with this PR after rebase and it doesn't complain, it's good to go.

As above

**Pull request merged**
