### PR TITLE
[Xedra Evolved] Vampire Powers overhaul

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved] Vampire Powers overhaul"

#### Purpose of change

It is time that I turn my hand to yet another class of playable supernatural creature.

Also, I had a bunch of ideas for vampire powers.

#### Describe the solution

Overhaul the various vampire powers so that some of them maintain themselves as long as you have enough blood (these are activated from the mutations menu) and some of them are single-shot (these are activated from the supernatural powers menu). 

Also, make most powers scale based on how many vampire powers you have. Higher-tier powers provide more scaling benefit than lower-tier ones. 

Remove the `deactivate_condition`--the recurrence is long enough that it's not going to be a big deal, and a `deactivate_condition` based on an effect makes it likely to not run when you want it to, since recurring EoCs are only reactivated on gaining new bionics or traits, not effects. This means that a character who gains the vampire_virus effect later in the game would never progress until they gained some other trait or CBM (which would reactivate the deactivated EoC).

Add quite a few vampire powers:

TIER ONE

- Vigor Mortis: Vampiric strength. Small passive bonus, activate to increase the bonus by more.
- Sanguine Resilience: Vampiric toughness. Reduces damage taken by a bit, activate it to increase it by a more.
- Predator's Senses: Increases perception and hearing, scaling with vampiric power. Also provides a power that lets the vampire smell whether any humans are nearby. 
- Silent as Death: The vampire no longer makes any noise when they move.

TIER TWO

- Flow Like Blood: Increase dexterity slightly, and activate to increase the vampire's dodging ability greatly.  
- Predator's Mien: Cause supernatural fear in the target, making them run away (maybe--depends on the vampire's power). Only works on targets that can feel fear.
- Spider's Walk: Allows the vampire to climb walls without ladders and fall any distance without suffering damage.
- Claws of the Beast: Allows the vampire to warp their fingers into animalistic claws to savage their enemies. Equivalent to the Gnarled Claws mutation.
- Crimson Vision: The vampire can see the heat of blood flowing through the veins of their prey.

TIER THREE

- Cowing the Beast: Force a predatory animal (currently rats, wolves, coyotes, and bears) to obey the vampire.
- Earthen Slumber: Sink into the earth--on diggable soil, sink into the ground to slumber away from the sun. 

Since this is way more than previous number of traits, I edited the vampire tier ascension EoC so that you can ascend to the next tier after gaining four traits. These traits are random, so not all vampires will have the same traits. I have an idea for a research system allowing vampires to spend a bunch of time and blood to try to unlock new abilities that I'll include in a future PR, and presumably vampire NPCs could also teach some to you too (once they're implemented). 

The really iconic, powerful abilities like mind control, turning into mist or wolf or bat, controlling storms, etc., aren't in because they should probably be gated behind the currently unimplemented `VAMPIRE4` trait. 

#### Testing

Powers work. Vampire EoC processes when gaining Wan after fighting a strigoi. Powers stop at four, and then later evolution to the next tier occurs. 

Tested each power. No crashing, when you don't have enough blood the power successfully turns off, and when you run out of blood while maintaining them it also turns off.

image

### CODE REVIEW

**Comment by Standing-Storm** [comment]
Well, uh, I'm getting a silent crash with no crash log from using `u_deactivate_trait`, so that's odd.

**Comment by Krieger1999** [comment]
Hypnotic Gaze, Sanguine Restoration, Earthen Slumber do not work, because they are somehow passiv abilitys and not active. 

I wish i would know what Sanguine Resilience and claws of the beast exactly add. The claws seem to be way weaker then the fangs.

**Comment by Standing-Storm** [comment]
> Hypnotic Gaze, Sanguine Restoration, Earthen Slumber do not work, because they are somehow passiv abilitys and not active.

They are passive because they provide supernatural powers (from the supernatural powers menu). The mutations menu is for abilities that can be left on, and the supernatural powers are for abilities that you use once to get one-time effects. You should get a "You learn [X]" message when you gain the trait.

> I wish i would know how much armor Sanguine Resilience and damage claws of the beast exactly add. The claws seem to be way weaker then the fangs.

I need to move the fangs over to integrated armor but didn't want to do that in a PR that was already almost 1400 lines. And unfortunately, there's currently no UI infrastructure to display the effects of enchantments on the PC. Blood Lungs at least should provide an integrated armor item, visible in your equipment menu, and the stats should tell you how much blood it can contain / is currently containing.

**Comment by Krieger1999** [comment]
> > Hypnotic Gaze, Sanguine Restoration, Earthen Slumber do not work, because they are somehow passiv abilitys and not active.
> 
> They are passive because they provide supernatural powers (from the supernatural powers menu). The mutations menu is for abilities that can be left on, and the supernatural powers are for abilities that you use once to get one-time effects. You should get a "You learn [X]" message when you gain the trait.
> 
> > I wish i would know how much armor Sanguine Resilience and damage claws of the beast exactly add. The claws seem to be way weaker then the fangs.
> 
> I need to move the fangs over to integrated armor but didn't want to do that in a PR that was already almost 1400 lines. And unfortunately, there's currently no UI infrastructure to display the effects of enchantments on the PC that aren't speed-based. Blood Lungs at least should provide an integrated armor item, visible in your equipment menu, and the stats should tell you how much blood it can contain / is currently containing.

Ok i understand. Thanks for answering! :)

**Comment by Standing-Storm** [comment]
> I only noticed that Sanguine Resilience even with all Vampire powers and activated seems to protect only very littel even from normal zombies. That makes it kinda useless unfortunaly.

It should reduce bash damage by about a third when active (with maxed virus progression), but it's always a multiplier so a lot of the time it won't reduce damage to 0 the way armor will.

**Pull request merged**
