### PR TITLE
Fixes a few recipes i missed in tailoring audit

### LINKED ISSUE #58504: Few missing material recipes in tailoring overhaul
### Describe the bug

I done goofed and somehow the recipes for a few of the patchwork sheets got misplaced. Leather, fur, faux fur, synthetic fabric (for which the patchwork sheet is incorrectly named still, going to fix that as well), and i believe Lycra. 

Again, oops. When I have wifi tomorrow, I’ll write the PR. 

### Steps to reproduce

1. Try to make the above mentioned patchwork sheets. 
2. Notice that I somehow missed the recipes. 

### Expected behavior

I should be able to sew leather together into a patchwork sheet. That’s why I did all this damn work. 

### Screenshots

_No response_

### Versions and configuration

Not relevant, just any after #54256 was merged. 

### Additional context

Again I can fix it by submitting a new PR tomorrow or I can write it up in notes on my phone and send it to someone

### PR DESCRIPTION
**Pull request by a-chancey**
Oops

#### Summary
Bugfixes "Adds missing patchwork sheet recipes and a rename i missed"

#### Purpose of change
Fixes #58504 
adds recipes for patchwork leather sheet, patchwork fur sheet, patchwork faux fur sheet, patchwork lycra sheet, patchwork synthetic fabric sheet and patchwork felt sheets.
Also fixes patchwork synthetic fabric naming.

#### Describe the solution
I added the recipes

#### Describe alternatives you've considered
making someone else do it.

#### Testing
I opened the game and created each of the items successfully.

#### Additional context
Oops.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
If this was the "patchwork clothing parts -> rag" recipe, it needs to go too.

image

**Comment by a-chancey** [comment]
I don't have time to get to it tonight - I'll try to take care of that tomorrow while the wife drives - but you're absolutely right. 

I've got at least one other issue currently to clean up regarding the thread needed for weaving cotton cloth (it's way too low right now), so I'll make another issue addressing those tomorrow and hopefully get a PR put in by the evening. Those are both mostly just annoyance/balance issues at the moment. 

The patchwork sheet recipes, on the other hand, were entirely intended in the first pass, as it's the only way to acquire said patchwork sheets. I kept this PR exclusively to the work outlined in the issue I filed

**Comment by Sathra225** [comment]
Just to double-check, if I added an uncraft recipe for cotton sheets, they would uncraft into 8 patches? Largely an Innawoods thing as patches are currently somewhat annoying to get.

**Comment by a-chancey** [comment]
You should be able to cut them up or disassemble them already, I’ll look into that if they’re unable to be. 

Unless innawoods specifically has an override for the uncraft recipe, which is possible.

**Comment by Sathra225** [comment]
Started a new world and character and both spawned in and crafted a cotton sheet. Couldn't disassemble them and cutting them up only gives a chance at a single patch.

**Comment by a-chancey** [comment]
Thanks for testing it out. That’s odd, I’ll see what I can get to this weekend

**Pull request merged**
