### PR TITLE
Add recipe for fried chicken

### PR DESCRIPTION
**Pull request by Cyrano7**
Adds recipe for fried chicken.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Fried canned chicken? This is the grossest sounding recipe yet.

**Comment by chaosvolt** [comment]
That sounds hilarious.

**Comment by Cyrano7** [comment]
Dam I might need to start over. Any other way to get this merge-able? It doesn't like line 755 even though its the same as the master.

**Comment by chaosvolt** [comment]
Hmm. Snag the master branch's version, dump it into the branch, and re-implement the change? Assuming the git shell commands don't help.

**Pull request closed without merging**
