### PR TITLE
Add Wooden Wheel Mount

### PR DESCRIPTION
**Pull request by dannyisdude**
#### Summary

SUMMARY: Content "Add Wooden Wheel Mount"

#### Purpose of change

Until now, a power drill has been required to craft a steerable wheel. Steerable wheels are 19th century technology that shouldn't require power tools to make.

#### Describe the solution

Adds a wooden wheel mount.
Based on https://en.wikipedia.org/wiki/Dandy_horse.

#### Testing

Went in game, crafted wooden wheel mount, installed wooden wheel mount on vehicle, drove vehicle, and uninstalled wooden wheel mount from vehicle.

### CODE REVIEW

**Comment by dannyisdude** [comment]
> I'm seeing a bunch of blacksmithed parts in your references, including what seems to be critical parts.
> This has come up a number of times before, e.g. at #34378, and I've never seen evidence that a steerable all-wood wheel is feasible.

https://en.wikipedia.org/wiki/Wooden_bicycle
The top picture in this article shows a feasible all-wood design. Could the steerable mount be based on this?

**Comment by mlangsdorf** [comment]
<https://en.wikipedia.org/wiki/Dandy_horse>
Two inverted wood triangles connecting the wheel axis.  A short plank connects the triangles.  A vertical dowel runs through a wooden frame and is connected to the plank.  Another plank connects to the first plank at angle, ahead of the wooden frame, and is used as tiller to steer.

The dandy horse uses an iron spoked wheel, but you could do it with a slice of a tree trunk.  The only metal bits you really need are nails, and you could replace them with dowel pins and clever wood joinery if you were really, really insistent that you not have any metal work involved.

The dandy horse was developed in 1817.  I don't get the objection to wooden, steerable wheels.

**Comment by zeziba** [comment]
The skill is set to use 1 mechanics for both creation and installation. It should take a steady hand to make anything for this type of use as wood working is hard for practical uses so it should at min require as much fabrication skill to manufacture as mechanics if not 2-3.

**Comment by dannyisdude** [comment]
> The skill is set to use 1 mechanics for both creation and installation. It should take a steady hand to make anything for this type of use as wood working is hard for practical uses so it should at min require as much fabrication skill to manufacture as mechanics if not 2-3.

I completely agree. Changed.

**Comment by kevingranade** [comment]
> The top picture in this article shows a feasible all-wood design.
It shows a all-wood bicycle-shaped sculpture.  Between the lack of a metal rim to lack of metal hubs I'm enormously skeptical that it's a functioning bicycle.

> Two inverted wood triangles connecting the wheel axis.
The triangles are fine, the axis needs metal parts.

> A vertical dowel runs through a wooden frame and is connected to the plank.
I feel like we're looking at different images, that is quite plainly a threaded metal shaft with a square head on top, a washer below the handlebar, and a wing nut above the body of the dandy horse.  Even setting aside the obvious metal components, there is no way an apparently 1" or so wooden dowel is going to hold up to the torque that is obviously required to turn the wheel under the weight of the rider on what is essentially a wood-on-wood thrust bearing.

This is the image I'm referencing.
https://upload.wikimedia.org/wikipedia/commons/8/8d/Draisine_or_Laufmaschine%2C_around_1820._Archetype_of_the_Bicycle._Pic_01.jpg

> I don't get the objection to wooden, steerable wheels.

The objection is that wood is a *terrible* bearing material, so no matter what you make the rest of the thing from, you are not going to get away without metal bearings.  That includes the wheel axles as well as the pivot for the steering assembly.  The design of the dandy horse managed to turn the wheel pivot into a thrust bearing on an axle, and *maybe* you could substitute a beefed up wooden dowel for that, but there is no prior art for it, and you're still not getting away without metal axles, so what's the point?

**Comment by dannyisdude** [comment]
> I feel like we're looking at different images, that is quite plainly a threaded metal shaft with a square head on top, a washer below the handlebar, and a wing nut above the body of the dandy horse. Even setting aside the obvious metal components, there is no way an apparently 1" or so wooden dowel is going to hold up to the torque that is obviously required to turn the wheel under the weight of the rider on what is essentially a wood-on-wood thrust bearing.
> 
> This is the image I'm referencing.
> https://upload.wikimedia.org/wikipedia/commons/8/8d/Draisine_or_Laufmaschine%2C_around_1820._Archetype_of_the_Bicycle._Pic_01.jpg

That image isn't of the original dandy horse, it's of a knockoff. The Wikipedia page describes the original functional version as being all-wood.

**Comment by kevingranade** [comment]
> The Wikipedia page describes the original functional version as being all-wood.

Where?

**Comment by anothersimulacrum** [comment]
The wikipedia page for a wooden bicycle mentions that it's
> mostly, or entirely made from wood.

But both of the sources linked shown bicycles with metal wheel mounts.

**Comment by Rail-Runner** [comment]
Well, I think that even if such a steerable wheel needed metal and blacksmithing tools to make, it could still be useful sometimes. An all-wood version could maybe exist as non-steerable variant, if you don't mind your "car" not being able to turn? At least until someone can really prove that you could make it steerable.

**Comment by meladath** [comment]
Gotta love when someone argues history isnt real and that you "cant get away" with something we managed perfectly fine for hundreds of years without.,...

**Comment by mlangsdorf** [comment]
Wooden ball bearings apparently date back to 40 BC <https://en.wikipedia.org/wiki/Bearing_(mechanical)> though I'm not sure they were used for wheels.

I cannot find a readily understandable discussion of the friction load on a horizontal wheel axle versus the friction load on a vertical wheel axle intended to turn that horizontal axle.  My intuition is that (assuming collars of equal size on both axles) that the vertical friction is less and the torque required to rotate the vertical axle is also less.  I would be happy to be proven wrong - if someone has a copy of Halliday and Resnick handy and can look this up, that would be appreciated.  Assuming I'm right, if the survivor can make bearings that allow a wooden axle to turn a wooden wheel at all, he should be able to use those same bearings on the vertical axle.

I do think that a wooden steerable wheel should steer worse than one with metal bearings, but since steering is currently binary (you can either steer or you can't), I don't think it matters for now.

**Comment by mlangsdorf** [comment]
Okay, after further discussion with esotericst, it looks like wooden bearings do not work with wooden shafts for any significant level.  It might just barely be possible to build a rickety all-wood steerable wheel mount for a bicycle (but probably not) but you couldn't mount a couple of them to provide all wheel steering on your wooden land ship.

Proposed solutions:
* disallow wood steerable mounts (default)
* add wood + forged metal steerable wheel mount that can be installed without welding.  This PR should probably evolve into this.  Basically, the fasteners, the ball bearings, and the inner and outer races would need to be metal and the rest could be wood and the assembly could be nailed to a frame.
* add some mildly complicated vehicle code to count the number of axles and wheels in a vehicle, and allow all-wooden steerable wheel mounts to provide steering only on 2 wheel, 2 axle vehicles like bicycles but not on 4 wheel, 2 axle vehicles like cars.  I can add this to my to-do list but it'll be low priority or someone else could do it.
* generalize the previous solution and provide limits for all wheel mounts on how large a vehicle they can still steer.  I like this idea, but it's the most complicated and takes the most research and planning.

**Comment by kevingranade** [comment]
> add wood + forged metal steerable wheel mount that can be installed without welding.

This is fine. Minor correction all I was calling out as necessary were metal bearing bands, not ball bearings.

**Comment by dannyisdude** [comment]
> Proposed solutions:
> 
> * add wood + forged metal steerable wheel mount that can be installed without welding.  This PR should probably evolve into this.  Basically, the fasteners, the ball bearings, and the inner and outer races would need to be metal and the rest could be wood and the assembly could be nailed to a frame.

Alright, this seems the most reasonable. Changing it into this.

**Pull request merged**
