### PR TITLE
Adds a Clown Mask

### PR DESCRIPTION
**Pull request by fluffe9911**
Summary
SUMMARY: Content "Added a clown mask for the clown profession"

Purpose of change
The clown profession never had any makeup or mask or anything to make them look like a actual clown so now they got a neat mask to hide the true horrors underneath.

Describe the solution
Added a clown mask and gave it to the clown

Describe alternatives you've considered
Add some type of face paint item/character choice but a mask is easier and more neat plus a mask can contain fake hair/nose/face while the alt would be all those as separate items and a whole new character customization system for face paint

Testing
Loaded the game, spawned it in put it on, committed suicide.

Additional context
We live in a society

### CODE REVIEW

**Comment by fluffe9911** [comment]
also I imagine it looks something like this https://www.clipartwiki.com/clipimg/detail/259-2595039_clowns-clown-mask-masks-funny-circus-funny-clown.png

**Comment by Rivet-the-Zombie** [comment]
Don't clowns usually wear face paint instead of masks?

**Comment by fluffe9911** [comment]
Well generally yes but see the alternatives considered section. honk

**Comment by kevingranade** [comment]
Makeup would be fine, the whole mask thing seems like a meme thing, so no.

**Comment by fluffe9911** [comment]
@kevingranade is it ok if I just add a clown nose and wig then since I dont feel like adding a whole new thing for makeup?

**Comment by kevingranade** [comment]
Those are reasonable.

**Pull request closed without merging**
