### PR TITLE
[WIP][CR] Attempting to fix shotgun speedloaders: Speedloader adaptors

### LINKED ISSUE #52595: Shotgun speedloader chute not work
### Describe the bug

Weapon addon and shotgun speedloader chute not work. Gun don't see not 6, nor 8. They just keeping used shells, menu not open

### Steps To Reproduce

Select Shotgun who support this addon
Unload gun
install speedloader chute
load chute (any type of 12 ammo)
Try to reload with chute

### Expected behavior

I expected it to work the same way as with revolver speedloader, but gun doesn't see these speedloaders

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a37d197 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Hair and Skin Color Cosmetics, UDP and MXotto+ version p10 [mxoudpcosmetics],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Mythical Martial Arts [MMA],
    Rummaging [Rummaging],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Graphical Overmap [Graphical_Overmap],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Bugfixes "fix shotgun speedloaders"

#### Purpose of change
Fixes #52595

#### Describe the solution
A new optional Json field for gunmod items: `"speedloader_adaptor": [ "speedloader_item_id" ]`

as a quick refresher on how speedloaders usually work, guns with integrated magazines(guns that have a pocket of type "magazine" rather than "magazine well") have the following optional field within their pocket data: `"allowed_speedloaders": [ "speedloader_item_id" ]`. _In theory_ a mod with `"speedloader_adaptor"` will either _replace_, or _add onto the end of_, that data.

That's the idea anyway, I don't quite know how to implement this. Right now I'm basically throwing code at the wall to see what sticks. It seems like something that should be fairly simple for someone who knew what they were doing and/or were more familiar with the codebase than I am, so any help is appreciated. 

#### Describe alternatives you've considered
1. Trying to use `pocket mod` :  I tried adding a line to the shotgun-speedloader-chute like 
```    
"pocket_mods": [ 
 {
 "pocket_type": "MAGAZINE",
 "ammo_restriction": { "shot": 8 },
 "allowed_speedloaders": [ "shot_speedloader6", "shot_speedloader8" ] 
 } 
] 
``` 
which comes close to being what I need, but it has some problems (see #53542). The main problem is the need to redefine `"ammo_restriction"` even if it wasn't the thing being changed

   1a. asking for someone to change `"ammo_restriction"` to not need a count to be defined as it was already defined elsewhere in the item: (see #53375) essentially got shot down and had the opposite effect of the other places that it was defined being removed.

2. trying to make `"magazine_adaptor"` actually work for speedboaters: The magazine adaptor code is pretty confusing and I'm not even sure if it works properly anymore since guns don't have a "magazines" list like they used to. 

3. restricting the speedloader chute to only ever be used on 8 round shotguns so that I can just use freaking `"pocketmod"`: this seems like a quick and dirty non-solution, that feels more like I'm trying to hide the problem instead of fixing it.

#### Testing
It doesn't work yet (duh). Right now the game starts but crashes while loading into a world (not sure why, as no crash log is created).

### CODE REVIEW

**Comment by GuardianDll** [comment]
Want to point [the new 5.56 clips](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/magazine/223.json#L596) is somewhat related to this ussue, i believe, you can use it in your tests
#58359

**Comment by Maleclypse** [comment]
If this is ready for merge please resolve conflicts and bring out of draft.

**Comment by catdach** [comment]
Sorry, I haven't quite gotten this working properly yet, so it's still not ready for merge. When it is, I'll make sure to take it out of draft and resolve the conflicts.

**Comment by Maleclypse** [comment]
Closed by #63287

**Pull request closed without merging**
