### PR TITLE
[WIP] Proportional Ammo Piercing

### LINKED ISSUE #27085: Proportional Ammunition Pierce
**Is your feature request related to a problem? Please describe.**  
Part of my archery re-balancing/improvements requires that arrows have proportional damage and piercing values that multiply the existing damage value of the bow they are fired from, with the intent of making archery more practical and realistic.

As it stands, arrows and bows both have flat damage and pierce values. This is unrealistic and leads to inconsistent performance from different bows.
While Knightosmaster was nice enough to add a proportional damage value, I still need a proportional pierce value to make my changes.

**Describe the solution you'd like**  
Any and all "gun" items can have a pierce value applied to them in JSON. This represents the piercing value of a bow (or similar weapon) using a projectile with a terminal ballistic value of 1 (Or possibly 2, then non-bodkin arrows would reduce AP proportionally to bring them to appropriate levels. It depends on whether or not the base AP for the weakest bow is higher than 0).

A "prop_pierce" value would then be needed on the ammunition in use, which multiplies the base pierce value of the bow it's fired from to give a final pierce value based on the input energy from the bow, and the terminal ballistics of the arrow itself.

It's possible that I or others might make a mistake or simply not need to assign a pierce value to a weapon that might use proportional pierce ammo. If no pierce is assigned, the code would need to assume that the value is 0 and act appropriately.

In practice, the idea is that I can have a bow marked with a base pierce value of 8. Firing a normal arrow out of it would apply the base pierce value of 8. A bodkin arrow with a prop_pierce value of 2 would be fired with an applied pierce value of 16. A crude wooden arrow with a prop_pierce value of 0.75 would be fired with an applied pierce value of 6. (Values are examples and not actual values for anything)

**Describe alternatives you've considered**  
It's also possible that the appropriate pierce value could be drawn from the base damage of the weapon, then multiplied, but I feel that would make adding new content more difficult, requiring more math and messing about to get appropriate values.

I could also just ignore proportional pierce entirely, but that leads to the current issue with bows and arrows. Namely, that a weak bow with high-quality arrows does dis-proportionally high damage and pierce.

**Additional context**  
While I've mentioned primarily bows and arrows throughout this request, the same mechanic would obviously be applied to all similar weapons like crossbows, slingshots, and pneumatic weapons, which I also intend to take a stab at.

The recent proportional damage PR from Knightosmaster does something similar, so could be quite helpful for direction. https://github.com/CleverRaven/Cataclysm-DDA/pull/26705

The terminal ballistics and proportional damage values are drawn from Poragon's ranged weapon damage/pierce guideline which I've been working on applying to archery weapons. https://github.com/CleverRaven/Cataclysm-DDA/issues/26183

### PR DESCRIPTION
**Pull request by MetroidHunter**
#### Summary
SUMMARY: Features "Adding proportional ammo damage for ranged weapons"

#### Purpose of change
Fixes #27085 

#### Describe the solution

- [x] Add regression tests for current damage model
- [ ] Add regression tests for proportional damage model
- [ ] Add regression tests for current pierce model
- [ ] Add proportional piercing
- [ ] Add unit tests for proportional piercing
- [ ] Cleanup

#### Additional Context
This represents a good bit of discovery on my part digging into how the damage model is currently calculated in game and determining how pierce affects that model against armor. In addition to that, I also spent a long time learning about how items load from json into the game and attempted to make the tests idempotent without having to add additional json items. I ran into too much hurdles with the static nature of item_controller and its proliferation and gave up on that.

I wanted to put this PR up just to get the placeholder up and to make sure the tests run in the CD pipe

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Marking as stalled. Please ping me to reopen when you are ready to pick up where you left.

**Comment by MetroidHunter** [comment]
Stalled is an accurate description. I hopefully will pick this back up in may

**Comment by ZhilkinSerg** [comment]
> 
> 
> Stalled is an accurate description. I hopefully will pick this back up in may

That is great to hear!

**Comment by MetroidHunter** [comment]
Still on my radar. Once life calms down a bit, I still plan to return to this

**Pull request closed without merging**
