### PR TITLE
Renamed Vacutainer© to Blood draw kit. 

### PR DESCRIPTION
**Pull request by Treah**
Changed the name to be more descriptive of what this item actually does and is used for. Changed references to the item in the text along with changing its action from VACUTAINER to BLOOD_DRAW to clear up again what this action is.

The old name is a bit confusing and has problems with translations and the end user understanding its purpose. 

Also the name of the item is copyrighted by a company that requested it be changed when looking at the item database on chestholes site. Issue #21459

### CODE REVIEW

**Comment by Treah** [comment]
Forgot to add all the changes that I did with a misplaced git add command. Corrected and pushed.

**Comment by kevingranade** [comment]
If you change the item id you'll break savegames.
We have some migration code, but we could also just leave the id as it is.

**Comment by DangerNoodle** [comment]
Would also affect tile sets.

**Comment by Treah** [comment]
Well damn... The id was using the same name so there really wouldn't be a good way to remove the offending copyrighted word without doing that. Just renaming it only changes how its viewed in the game itself but not code and possibly not the item browser where the infringement was lobbied against.

**Comment by kevingranade** [comment]
Not copyright, trademark.  They REALLY have no usiness complaining about us using trademarked terms in game internals, that's not how trademark works.

**Comment by AlecWhite** [comment]
Then is this whole thing of adding the ® is still needed?

**Comment by kevingranade** [comment]
No, it never was, they were just making baseless demands.  We're not infringing on their trademark in the first place.

**Comment by Treah** [comment]
Ok ill run though this again tonight and change the Id's back to keep from breaking saves. Ill leave the action as is in the PR however as it is better and should not cause any issues.

**Comment by Treah** [comment]
Changed the item id's back and tested this out locally. Seams to be ok and only broke my game that I had tested  before with the old id. Please let me know if anyone gets any errors after applying this if its merged.

**Pull request merged**
