### PR TITLE
Allow [B]utcher with non-knife salvage tools [WIP]

### LINKED ISSUE #11734: No tool other than a knife has inscribe / cauterize / salvage use?
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_factory.cpp#L1350-L1366

It looks like there are three specific item "use" types that could be assigned to non-knife tools, but I can't find any items with those types. Looking at tools.json I wanted to make the toolbox usable for salvage, since it's got all the right stats, but it already has a use_action for repair. Is there some way to make a tool capable of salvage/incribe/cauterize in addition to the uses they already have?
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9863013-no-tool-other-than-a-knife-has-inscribe-cauterize-salvage-use?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sparr**
There are separate item use types for salvage, cauterize, inscribe, but nothing uses them. This patch adds the salvage type to a bunch of tools that are capable of taking things apart, so that the butcher menu won't refuse to open if you don't have a knife.

Resolves #11734

### CODE REVIEW

**Comment by Zireael07** [comment]
What tools are those? I can guess one of these is the toolbelt or toolbox, but other than that, dunno - git only shows the line you changed and two or three lines below...

**Comment by BevapDin** [comment]
You can expand the shown context by clicking on the part left of the field that contains the `@@ -252,7 +252,7 @@`, it's explained at https://github.com/blog/1705-expanding-context-in-diffs

**Comment by sparr** [comment]
Mostly sewing and soldering tools.

**Comment by Coolthulhu** [comment]
Items that consume charges shouldn't have the salvage ability in its current state. Separate usage costs aren't implemented yet, nor is properly choosing the best salvage tool.
With your PR, if you had a welder before any knife in your inventory, the welder would be picked and then invoked on every single item you try to cut up, eating up 50 charges for every item.

**Comment by sparr** [comment]
@Coolthulhu it had not occurred to me that there would be salvage tools that can do the same job at different costs. the complaint I was trying to address here is that if I want to disassemble items on the ground using a sewing kit (or soldering iron, or otherwise) then I need a superflous knife in my inventory.

**Comment by Coolthulhu** [comment]
I'm pretty sure you should be able to disassemble items without a knife. If you can't, but you can pick up the item and then disassemble it, that's a bug.

**Comment by sparr** [comment]
@Coolthulhu that's the bug this PR is meant to fix. The [B]utcher menu won't open if you don't have an item with the 'salvage' use, and only type:knife items have that use right now.

**Comment by Coolthulhu** [comment]
I just tested it and it did work as intended - without a knife in inventory, I stood over a pile of stuff, pressed `B` and it asked me which item I want to disassemble (listed the 2 tank tops, but no other items because those weren't disassemblable).
Then I disassembled one of them (it worked), then the other. It listed the rags from the tank tops properly too.

Do you mean disassemble as in "reverse recipe" ("uncraft") or as in "salvage" ("cut up with a knife")?

**Comment by sparr** [comment]
I mean reverse recipe / uncraft / the thing "(" does in your inventory.

**Comment by Coolthulhu** [comment]
A salvage tool should neither be required nor help with those in any way. The butcher menu should open just fine with no salvage tool in inventory and should list all the disassembleable items you could disassemble with "(".
If it doesn't, describe how did you get it to not-open, upload save, describe what it says etc.

**Comment by sparr** [comment]
Closing this for now. Will re-open if I can reproduce the bug. You're right that this isn't the correct fix. I was mistaken about all the side effects of the salvage use.

**Comment by sparr** [comment]
@Coolthulhu #11861

**Pull request closed without merging**
