### PR TITLE
Martial arts rebalance

### PR DESCRIPTION
**Pull request by Brian-Otten**
### How to use
Rebalance works on existing saves.
#### Summary
`SUMMARY: Balance "Martial arts rebalance"`
#### Purpose of change
Judo now gets an attack speed increase at the cost of damage, is now good for stunlocking zombies with throws for your friends or to use while running away

Capoeira now charge up powerful area of effect sweep kicks by moving.

Zui Quan now only gets 3 bonus dodges, and it's damage bonus no longer stacks twice (still as much damage bonus as all other damage bonus styles, instead of twice as much,)

All animal styles that buff damage from one of the other stats now reduce strength scaling slightly, good for low strength characters. Tiger style has -5 bash damage so it's damage is more in line with muay thai.

### CODE REVIEW

**Comment by MetroidHunter** [comment]
You have an invalid summary line. Must be in the format
 
Summary: Category "Description"

Must fix for gorgon to pass

**Comment by ifreund** [comment]
The rebalancing you've done looks great to me, and seems true to what the martial arts are in real life.  

I'd recommend disabling/moving the venom styles to a mod in a separate pr, as it's best to keep things a little more contained.

**Comment by Brian-Otten** [comment]
Yeah, there was a branch mixup, monstergroups.json is back. If people think they should stay in / be removed differently, i can change five deadly venom styles back to a starting trait, but i had some people suggest to solve it this way as well.

**Comment by ifreund** [comment]
>Yeah, there was a branch mixup, monstergroups.json is back. If people think they should stay in / be removed differently, i can change five deadly venom styles back to a starting trait, but i had some people suggest to solve it this way as well.

Oh I am all for moving them to a mod, was just suggesting to do that in a second pull request.

**Comment by Brian-Otten** [comment]
Changed it so five deadly venoms is still selectable at chargen. text edited to reflect this.

**Comment by ZhilkinSerg** [comment]
Conflicts should be resolved after #28874.

**Comment by ZhilkinSerg** [comment]
Marking as stalled. Please ping me to reopen when you are ready to pick up where you left.

**Pull request closed without merging**
