### PR TITLE
Add messy and untidy house mapgen palettes

### PR DESCRIPTION
**Pull request by tjole**
#### Summary
Content "Adds new mapgen palettes to add various levels of untidiness to houses"

#### Purpose of change
The aim of this PR is to add variety and realism to houses by altering item spawns to give a more natural look, in some cases.

Currently, items spawns are very similar between houses. Items generally spawn in the place they belong, eg dishes spawn on tables, clothes spawn in dressers. In real life, many houses have varying levels of clutter, where items are not where they belong or storage is overfilled. For example, dirty dishes may be found on coffee tables, jackets may be thrown over the back of a chair, a laundry basket with clothes may have been put down somewhere and forgotten about, or a bookshelf might be stuffed with books and trinkets. In-game, all houses are very tidy and neat which is not reflective of real life, and can give a sense of uniformity.

#### Describe the solution
I have introduced an untidy and a messy palette, to be used with the standard_domestic_palette. The untidy palette aims to represent a house that is a bit cluttered, with some floor-spawns and some items spawning in places they don't belong. The messy palette aims to further this, adding some dirty item spawns and increasing the amount of out-of-place and floor spawns.

I am tentatively planning for the untidy palette to be used ~15% of the time with the messy palette being used ~5% of the time. This may change during testing, or from feedback.

#### Describe alternatives you've considered
Creating variants for each house, with specific item-spawns. This would be a lot of work, and doesn't make use of the palette functionality.

The palettes I've added are designed to be loaded after the standard_domestic_palette but I am having trouble getting multiple palettes to load (see comment). I have considered fleshing out these new palettes to not require the s_d_p but be loaded instead of it. I'd like to avoid this, however, as I think it leads to unnecessary code duplication.

I am opening this in draft to see if anyone has any ideas for loading multiple palettes.

#### Testing
This is still a WIP, and item groups and palette item spawns will continue to be tweaked.

I have used the debug overmap editor to spawn large numbers of different houses to test these palettes, and have made tweaks to the palettes to get closer to the desired effect. As I add the palette to houses, I will spawn a 3x3 grid of the house to test each palette. Finally, once I'm happy with the palettes and that they work in the houses they've been added to, I'll create a map and teleport around cities to ensure spawn rates for untidy/messy houses are not excessive.

#### Additional context

This is still a WIP and I will continue to change items groups and spawn rates - these screenshots are more concept than final result.

House33 - default palette, for comparison
house33_default

House33 - using the untidy palette
house33_untidy

House33 - using the messy palette
house33_messy

### CODE REVIEW

**Comment by LurchingOtter** [comment]
I've been trying to get these palettes to spawn, but I can't work out how to use the a distribution with the palettes in mapgen. So:
[ "standard_domestic_palette", "standard_domestic_untidy_palette" ] 

Works fine and spawns the house with the untidy palette as expected, but:
[
  "standard_domestic_palette",
  { "distribution": [ [ "standard_domestic_untidy_palette", 3 ], [ standard_domestic_messy_palette", 1 ] ] }
]

leads to only standard_domestic_palette being loaded. I've tried a few variations on this, but haven't been able to get it to work. If anyone knows where I'm going wrong, it'd be a big help! If not, I have some other ideas on how to load these palettes, but I do think extending the standard_domestic_palette would be the best way to do this, if possible.

**Comment by MNG-cataclysm** [comment]
> I've been trying to get these palettes to spawn, but I can't work out how to use the a distribution with the palettes in mapgen. So: [ "standard_domestic_palette", "standard_domestic_untidy_palette" ]
> 
> Works fine and spawns the house with the untidy palette as expected, but: [ "standard_domestic_palette", { "distribution": [ [ "standard_domestic_untidy_palette", 3 ], [ standard_domestic_messy_palette", 1 ] ] } ]
> 
> leads to only standard_domestic_palette being loaded. I've tried a few variations on this, but haven't been able to get it to work. If anyone knows where I'm going wrong, it'd be a big help! If not, I have some other ideas on how to load these palettes, but I do think extending the standard_domestic_palette would be the best way to do this, if possible.

The mapgen palettes don't support a chance-based array. I'd create a new mapgen entry that shares the ID of the house you're working on, and apply the first palette array. Repeat this for the messy palette, replacing the untidy palette. When this is done, give the two new entries a lower mapgen weight based as a percent of the base model. For example, the untidy mapgen entry would have a value of 3% of the original weight value, while the messy entry would have 1%.

**Comment by LurchingOtter** [comment]
> The mapgen palettes don't support a chance-based array.

The docs suggest this is an option:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#palette-ids-as-mapgen-values
It looks like this was added under this pull request:
https://github.com/CleverRaven/Cataclysm-DDA/pull/51028
Several mapgen files do use distributions to select a palette, for example in line 35 of the cabin file:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/cabin.json

That being said, when I place that cabin in the map editor, I get an exception when I then approach it. It's the same for other files using a distribution in palettes. I'm thinking this is a bug, so I'll open an issue for it at least, to see what people think.

Using variants would definitely get this to work, but if possible I'd like to use a distribution in the palettes to avoid repeating lots of code. I think each variant would need to include the full map? Since I'm still tweaking spawnlists and such anyway, I think it'd be best to wait and see what happens with the palette distributions.



> Hopefully this helps.

It does - thanks for the reply :)

**Comment by LurchingOtter** [comment]
> The mapgen palettes don't support a chance-based array.

The doc for mapgen lists this as an option, and there are other mapgen files that use distributions in a similar manner. The cabin file for example uses it.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#palette-ids-as-mapgen-values

I've raised an issue for this as a bug, as I get the same exception approaching existing mapgen objects, such as the cabin map.



> Hopefully this helps.

Yeah, that's a big help :) If the distribution in the palettes doesn't work out, using variants like that would be a good way to get the palettes into the houses. It would make a lot of extra code, though

**Comment by MNG-cataclysm** [comment]
Are you using an up-to-date experimental build?

**Comment by LurchingOtter** [comment]
No, I was up-to-date with master when I created this branch so it shouldn't be more than a 7-10 days behind. I could merge master back in to make sure it's up-to-date, though

If I download the latest experimental release from https://cataclysmdda.org/releases/ then I get errors when spawning cabin_north which has a distribution in its palette - I've raised a bug for this but it's still unconfirmed so could just be me: https://github.com/CleverRaven/Cataclysm-DDA/issues/60395

________________________________

**Pull request closed without merging**
