### PR TITLE
[MoM] Allow portal storm scars to spawn on roads, in farm fields, and in subways

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Allow portal storm scars to spawn on roads, in farm fields, and in subways"

#### Purpose of change

Was changing something else and noticed that alien flora, pools of black water, etc can't spawn on roads or farms, which seems odds. Also, none of it was spawning in subways. 

#### Describe the solution

Allow all varieties of alien flora, crystal clusters, and black pools to spawn on farms or roads. Allow alien moss, crystal clusters, and black pools to spawn in subways.

#### Testing

Increased the spawn rate of specials for testing purposes and ran around for a while, map specials did appear.

#### Additional context

Chances are still low so the odds that you'll run into a grove of alien trees taking up the entire road are very small (but not zero)

### CODE REVIEW

**Comment by Nebnis** [comment]
Letting us drink that black water when?

**Comment by Standing-Storm** [comment]
> Letting us drink that black water when?

I need to do that so I can get a repeat of the person on the Discord who was like "I ate like 12 of those weird alien fruits and all I got was paralyzing muscle tremors."

**Comment by Nebnis** [comment]
I was actually thinking about adding some horrifying message/debuffs from doing it, passing out too. Maybeeee increasing/lowering nether attuned.

**Comment by Standing-Storm** [comment]
The only problem at the moment is that drawing water from a water-source is hardcoded and I can't fake it as an EoC  examine action that gives you the `black waters of infinity` because spawning liquids through EoC doesn't let you pick a container to put them in.

**Comment by NetSysFire** [comment]
I feel like some of this may be eligible for the main game, too.

**Comment by Standing-Storm** [comment]
We were talking about in the Discord at some point, and Kevin mentioned the reason that alien grass disappears is because there's no current way to track portal storms happening away from the player. This doesn't do that either (I've just been assuming all this was part of the initial week the sky broke during the Cataclysm), but I have thought about setting up an EoC that makes more of them over time.

**Pull request merged**
