### PR TITLE
Sanify stats of railroad tracks and crude anvil

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Was about to sanify power consumption for angle grinder, but it's pretty hard to do when the first recipe you see has super weird mass and volume conversion
#### Describe the solution
Tweak values of railroad tracks
Tweak values of crude anvil: rename it to "small anvil", give it anvil 3, combine the recipe that cut rail into crude anvil and recipe that transform crude anvil to anvil into one
remove recipe that transform crude anvil to anvil
#### Additional context
i am not sure the recipe should be 10 hours, but can't say anything else about the fact

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
Why would anyone get the regular anvil if the crude/small anvil gives the same quality & is *a component* of the regular anvil's crafting 🤔

**Comment by GuardianDll** [comment]
Regular anvil gives tool level 3 and can be only found, small anvil require tedious work and bunch of tools, and is, effectively, a regular anvil
it's just if it's made out of rail, it's kinda inappropriative to be five times bigger than the piece of rail

**Comment by x-qq** [comment]
Will this obsolete the crude anvil -> anvil crafting recipe?

**Comment by GuardianDll** [comment]
Yes

**Pull request merged**
