### PR TITLE
Additional samples for Mutagen recipes

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Balance "Additional ingredients for mutagen recipes"

#### Purpose of change
Add additional ingredients for mutagen recipes to match rabbit, snail, frog.

#### Describe the solution
Follows format already laid out.  Lays groundwork for additional recipe changes coming down the line.

#### Describe alternatives you've considered
none

#### Testing
TBD

### CODE REVIEW

**Comment by Shodan14** [comment]
Wouldn't it be better if they were actual things/bits rather than "samples"? It feels a it game-y compared to other stuff.

**Comment by Maleclypse** [comment]
> Wouldn't it be better if they were actual things/bits rather than "samples"? It feels a it game-y compared to other stuff.

People said the opposite when they were actual bits and things, so here we are. Once they are all in I'm fine for someone to go back and rename them.  String names and descriptions are easy to change.

**Comment by Venera3** [comment]
For the bugs I think you could use the eggs easily. They'll be intuitive as mutagen components and if we get a bit more nuanced mutagen system the ingredients could factor into the end result a bit more.

**Comment by Maleclypse** [comment]
I think the remaining samples will need to be made in specific PRs that also include sources for them and I'm going to need to work out what those would look like.

**Pull request merged**
