### PR TITLE
Rebalanced hacks' weight, volume and crafting recipes

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Inspired by #23251, but doesn't close it.
Hacks now require 25 minutes to craft (mininuke hack - 35 minutes). Also now they require `small electric motor`, `small storage battery` and `power converter`. ~~AND `plutonium cell` instead of `power converter` OR `plutonium cell`. I think that hacks are a military industrial-grade gizmos, so they shouldn't operate on common batteries, but on plutonium cells.~~

### CODE REVIEW

**Comment by voch93** [comment]
I feel that including a plutonium cell would make manhack craft not wort it at all, for it's a pretty rare drop and manhacks not that strong. A brief test shows that in 1v1 battle it is 15 regular zombies for 1 manhack, 1 zombie cop for 1 manhack and manhacks never being able to kill one zombie soldier.
For other hacks it's situational.

**Comment by Mecares** [comment]
Maybe a small storage battery would be a good alternative to a plutonium cell. They are not rare or useful like a plutonium cell but rarer than the common batteries.

**Comment by Night-Pryanik** [comment]
Hmm, 2.5 kilograms, 0.5 L volume, 500 points of energy capacity (= 500 batteries, right?). Sounds good enough.

**Comment by voch93** [comment]
Another side note, wouldn't it be strange that adding even move components will result in the same 0.25 L for all hacks? I guess we can use at least volume of the biggest component (so it results in 0.5 L for all hacks and 0.75 L for mininuke hack).

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Furthermore, all broken hacks have 3 volume = 0,75 L. I guess we could use this value for intact hacks, and 1 L for mininuke hack.

**Comment by Night-Pryanik** [comment]
Why is there different components gain from disassembling broken hacks? I guess broken hacks are just about the same as "alive" hacks with the same components, but just broken? Should I add missing components to broken hacks' disassembling recipes?

**Comment by kevingranade** [comment]
I'd be fine bumping volume up to 1L across the board, unless someone has a particular reason to keep them tiny. I assume this is in reference to inactive and broken hacks.
They're drifting from the original hand-sized flying threat toward a micro-drone that's a lot more realistic, I approve.

**Comment by voch93** [comment]
@Night-Pryanik if you about to add missing components. In the current implementation dropped "broken manhack" items, for example, are all undamaged. Does that mean that all components would be granted back to easily reassemble every fallen manhack?

And probably weapons themselves should not be added, I think their absence is intended. When you kill weapon hack `"The %s's interior compartment sizzles with destructive energy."` message appears.

**Comment by voch93** [comment]
@kevingranade it would be sane to keep mininuke broken and inactive hacks volume slightly higher than others, it requires twice as much component and weapon itself is bigger.

**Comment by Night-Pryanik** [comment]
> In the current implementation dropped "broken manhack" items, for example, are all undamaged. Does that mean that all components would be granted back to easily reassemble every fallen manhack?

There is always a chance that disassemble would be (partially) unsuccessful.

**Comment by kevingranade** [comment]
That is a good point though, the items that never drop represent items that
are destroyed when the hack is 'killed', ideally this would be dynamically
determined, but we don't have a system for that.

In short, the fact that some components never drop is intentional.

**Comment by voch93** [comment]
@Night-Pryanik hm, did you leave "inactive C-4 hack" and "inactive grenade hack" volume unchanged for purpose?

**Comment by Night-Pryanik** [comment]
Nope, just an oversight.

**Pull request merged**
