### PR TITLE
Add option to sheath Scalpel

### PR DESCRIPTION
**Pull request by ynemo**
Looks like we need scalpels for dissection? (not sure about it, but i usually take one scalpel with me)
And it would be logical to use ankle sheath or another sheath to store scalpel.

### CODE REVIEW

**Comment by Zireael07** [comment]
I believe X-acto won't sheath due to exact shape (it used to be sheathable, then there was discussion on GitHub which resulted in the current status quo). I'm on the fence regarding the scalpel.

**Comment by Barhandar** [comment]
Scalpels are flat and thinner than knives. Abstract sheaths should be able to store them, logically speaking.

**Comment by kevingranade** [comment]
The problem with both scalpels and x-acto type knives is they are very thin and very sharp.  If you try to sheath them in a typical knife sheath, they will fall to the bottom and dull the blade.

**Comment by ynemo** [comment]
Currently, it is more important to take scalpel or x-acto then butcher or hunting knife. If u want to make full butchering, then u need not only knife but also rope and etc. And generally dissection is more common and more frequent then butchering. So it is more game logically to have scalpel in some sort of worn equipment. 
Looks like we need special Sheath for them. Do we really need this micromanagement? Lets just imagine that we wrap up scalpel in rags before putting it to sheath.

**Comment by kevingranade** [comment]
Or just assume it's in a case or wrapped up in your general inventory, there's no need for sheathing them.

**Pull request closed without merging**
