### PR TITLE
Faster more reliable overmap_terrain_coverage test

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
None

#### Purpose of change
Previously the `overmap_terrain_coverage` test worked by generating a bunch of overmaps, and then verifying that every terrain was generated at least once.

However, to make the test reliable we had to over-generate more overmaps than would typically be needed to see every terrain, and whitelist a bunch of terrains which sometimes didn't spawn.

#### Describe the solution
A better approach is to keep track of what we've seen as we generate overmaps.  Then we can abort early if we see them all early, and run longer in the unlucky cases where it's necessary without whitelisting so many terrains.

Changed the test thus, and removed a few entries from the whitelist.

#### Describe alternatives you've considered
Removing the marina from the whitelist too.

#### Testing
The old implementation had a pretty fixed runtime of about 60s on my machine.

The new one can finish faster or slower.  In a few experiments I saw runtimes between 30s and 135s.  The worst case runtime if the test fails will be about 10 minutes.  But my hope is that, on average, it should be faster and more reliable than the old version.

#### Additional context

### CODE REVIEW

**Comment by BrettDong** [comment]
Re #55104: is it possible to release overmaps from the memory after they are generated?

**Comment by jbytheway** [comment]
Technically that is possible, yes.  But there's a catch.  Currently this test has two phases:
* Generate overmaps.
* Generate one OMT of each `oter_type_id`.
If we clear overmaps during phase 1 then the OMTs won't be there any more to use during phase 2.  The test could be rewritten to interleave the two phases, but it will become more complicated.  Alternatively, we could save the overmaps to disk instead of just throwing them away; then they could be reloaded for phase 2.  But disk space is also an issue on CI so I'd rather not do that.

We would also have to change the iteration order in phase 1.  Currently it just spirals out from the origin checking OMTs.  That would have to change into an outer loop over overmaps and an inner loop over OMTs within each overmap.

So, for now, I'm taking this issue as motivation to improve the memory consumption of overmaps instead.  Maybe that's foolish because overmap memory consumption isn't a real issue for end-users and so this is premature optimization.  So I might change my mind...

**Comment by Zireael07** [comment]
This should be revived for performance reasons

**Comment by jbytheway** [comment]
Yeah, it's still on my radar.  But last time I rebased it I was very confused by the merge conflicts and wasn't sure I did it right.  I might need to start over.

**Pull request closed without merging**
