### PR TITLE
fungal brute and hulk

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "fungal brute and hulk"

#### Purpose of change

Consistent content and mechanics, realism, bugfix

#### Describe the solution

Creates fungal brute and fungal hulk, similar to the skeletal variants with escalating stats and difficulty, partly based off of the existing fungal bulk but mainly coming from the zombie base

#### Describe alternatives you've considered

N/A

#### Testing

Game loads no errors, monsters transform and look right

Screenshot 2024-09-18 at 7 39 36 PM

Screenshot 2024-09-18 at 7 38 21 PM

#### Additional context

Inspired by https://www.reddit.com/r/cataclysmdda/comments/1fjwnc5/comment/lnre744/?context=3

### CODE REVIEW

**Comment by ADekema** [comment]
Discription says that their arms end in jagged points with fungal sprouds. That doesn't seem conducive with them still grabbing you. 

Maybe remove the grabbing ability and add some extra cut damage to their attacks and maybe a pierce attack.

**Comment by LyleSY** [comment]
Agreed, I've changed the descriptions to make it clear that they've fungalized from the zombie origins. These should be like zombies that are infected with fungus

**Comment by Night-Pryanik** [comment]
Nemesis converting into a fungal hulk means the end of nemesis' threat? I'm not saying this is a bad thing per se, but it feels like an inglorious end for such a special monster.

**Comment by LyleSY** [comment]
Agreed. Currently the Nemesis instantly shrinks down to a vanilla fungal zombie. This changes that to be an instant hulk to hulk transformation.  I'm not sure if that fires EOC_NEMESIS_DIED but I doubt it. My personal preference would be for a later PR to create a new fungal nemesis (ideally with intermediate steps) that also maintains mass but after a period of metamorphosis springs out and resumes its rampage. That seems a lot more fun to me.

**Pull request merged**
