### PR TITLE
fix fatigue restoration decrease

### LINKED ISSUE #72365: Fatigue regen while sleeping is bugged
### Describe the bug

After https://github.com/CleverRaven/Cataclysm-DDA/pull/72173 sleep fatigue regeneration was slowed down by 2 times

### Attach save file

[Old Mine-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14586878/Old.Mine-trimmed.tar.gz)
Save file with character already in bed with, pillow, quilt and fatigue set to 1000, with earplugs and blindfold

### Steps to reproduce

Normal fatigue recovery

1) Download [Cataclysm-DDA experimental build 2024-03-09-2216](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-09-2216) version
2) Find bed, pillow and quilt
3) Debug menu > Player > Edit player/nps > choose player > Set needs > make Fatigue to 1000
You can also make debug menu > quick setup > normalize body status before this
4) Sleep for 10 hours and see fatigue recovered by 240 points

Bugged fatigue recovery
1) Download [Cataclysm-DDA experimental build 2024-03-10-0100](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-10-0100)
2) repeat previous steps
3) See, that fatigue recovered only for 120 points

### Expected behavior

Normal sleep recovery

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0f9df4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #72365
Apparently there was `+ 1` in the code that i miss
#### Describe the solution
add `+ 1` to the calculations

### CODE REVIEW

**Comment by Venera3** [comment]
You might want to add some unit tests to the fields you enchantify to prevent this sort of oopsie - they also protect you from accidental regressions along the way.

**Comment by GuardianDll** [comment]
yeah, i'll try to do it, but i still don't know how to make a unit test from scratch - i can probably copy some existing stuff like overmap vision test i edited recently

**Comment by Inglonias** [comment]
I thought something was weird about this, but didn't realize it was actually a bug - I thought it was just my character having been sleep deprived.

**Comment by Venera3** [comment]
> yeah, i'll try to do it, but i still don't know how to make a unit test from scratch - i can probably copy some existing stuff like overmap vision test i edited recently

This is the way. `enchantment_tests.cpp` will probably be a good start for yoinkable references.

**Comment by GuardianDll** [comment]
"fixing" fatigue caused all tests that test fatigue to fail

**Pull request merged**
