### PR TITLE
Revised engines' weights and volume

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Based on [this discussion](https://discourse.cataclysmdda.org/t/jacking-vs-lifting/15094/10), and, in particular, [this table](http://www.gomog.com/allmorgan/engineweights2.html), I did some math and got average weights for i4, i6, v6 and v8 engines.

### CODE REVIEW

**Comment by illi-kun** [comment]
I guess the best way to fix the broken tests in your case is to slightly bump efficiency of affected engines.

**Comment by illi-kun** [comment]
Engines volume also should be revised due to [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/23231#issuecomment-373931993).

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by illi-kun** [comment]
Keeping this open with no progress for so long isn't a good thing.

**Comment by Night-Pryanik** [comment]
I just can't get the tests running on my machine. It seems that I will need help on tests' matter.

**Pull request merged**
