### PR TITLE
Added a luna park location

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Added a luna park location."```

#### Purpose of change
Add a new location.

#### Describe the solution
A rather small luna park with miniature railroad and a playground. Small maintenance shop and small ticket-selling building. Populated with zombie children. Nothing of high value here, minimal loot.
Also two miniature trains.

Also merged two json files into one for convenience.

#### Describe alternatives you've considered
None.

#### Testing
Debug-spawned the location several times. Then teleported around the map to find it "naturally".

#### Additional context
изображение

### CODE REVIEW

**Comment by mkikt4743** [comment]
I've seen this ingame already, is this a merge from a mod? I think it's cata++

**Comment by Night-Pryanik** [comment]
> I've seen this ingame already, is this a merge from a mod? I think it's cata++

No, it's not ingame (yet), and it's not from any mod. I designed this location from a scratch, based on design of park in my hometown.

Maybe you meant miniature railway from #35388?

**Comment by natovan** [comment]
I saw 1% of all structures but looking forward for it anyway

**Comment by mkikt4743** [comment]
aight, bet. I was confused cause the mini-rail came in about when I started playing with good mods

**Comment by Xenomorph-III** [comment]
Is there any difference between this and the miniature railway?

**Comment by Night-Pryanik** [comment]
> Is there any difference between this and the miniature railway?

Yes, there is.

**Comment by PaulBlay** [comment]
This is super cool. Is there any way the points by the storage shed at the bottom could be made functional? I found that if you drive your train up the branch there, you can't reverse out again because it crashes into the fence (possibly because collision detection is a bit wonky in CDDA).

**Comment by Night-Pryanik** [comment]
It's the problem with railways mechanics. It's possible to fix, we just need someone to do this.

**Pull request merged**
