### PR TITLE
Magiclysm - Dragon Mutation Add-On

### PR DESCRIPTION
**Pull request by animethecat**
#### Summary
```SUMMARY: Mods "Add a dragon mutation line to Magiclysm."```

#### Purpose of change
```Adds 4 new mutations lines for Black, Blue, Red, and White dragons each specializing in Acid, Electric, Heat, and Cold damage and resistance, respectively.```

#### Describe the solution
```The mutations system works by piggybacking off of mostly preexisting mutations, and adding on both pre and post threshold mutations specific and special to each of the 4 Dragon types.```

#### Describe alternatives you've considered
```To be honest, this started with me wanting to make martial arts modeled after Dragon Slayer magic from the anime Fairy Tail, but that just wasn't in the code, while mutations, by and large, were. I also considered making them as spells to add as new schools, but both can exist together without error, and more content is usually always welcome as far as I can tell, so I started here.```

#### Additional context
```I was able to test, within my own game on the latest experimental build #9639, if I was able to see the mutation lines present in the debug menu fore preexisting mutations, such as Fangs, Claws, Talons, Nose Slits, etc, and that was successful for each. Additionally I ensured that all books, mutagens, serums, and recipes were present and working properly, including intelligence restrictions. Applied serums, mutagens, and books read all functioned as expected and led to expected results.```

### CODE REVIEW

**Comment by KorGgenT** [comment]
So i'm going to try and investigate copy-from for mutations. We'll see how difficult that ends up being.

**Comment by animethecat** [comment]
With the dragon breath, I think it would still be a good mutation to have with an innate attack that also unlocks the spell to cast. The innate attack is aimed as a quick burst of energy while in melee combat and the spell is a more focused/concentrated blast. What do you think about that as a way to implement the mutation?
Also, are you following the D&D concept of acid/lightning lines, fire/ice cones?

**Comment by KorGgenT** [comment]
yes, so i'm following the dnd colors pretty closely. so red = cone, black, blue = line, etc. 
You can make spells cost Stamina, and in fact i might even suggest that the dragonbreath mutation do this. (and obviously be a little bit weaker than spells that cost mana in general, balanced with the fact you're locked to a mutation tree)

**Comment by animethecat** [comment]
I haven't forgotten about working on this at all, but life got busy this week. I plan on doing some hefty work on it this weekend, but I think the scope of this PR should be adjusted just to mutagens, the recipe books, and the recipes for the mutagens specifically for black dragons. That, I think, was Kevin's suggestion on Discord and I would like to make this a manageable change for everyone involved. If you would prefer me do this in a particular order KorgGenT I can no problem since this is largely your project.

**Comment by KorGgenT** [comment]
that's perfectly fine. you're not on a time limit, either.

**Comment by KorGgenT** [comment]
is this pr ready for review?

**Comment by KorGgenT** [comment]
image
this loop isn't really great

**Comment by KorGgenT** [comment]
image

**Comment by KorGgenT** [comment]
image
with these mutations, taking 20 in a row never mutates vomitous or wing stubs. Also, removing raptor talons from the categories will make it so that there is no longer the endless loop of mutations; when using mutagen the game will recognize prereqs even if it's not from the category.

**Comment by KorGgenT** [comment]
So I talked briefly with animethecat, and we will try to resume this PR in March or so. That being said, I will close it until the time comes, as the oddities i've seen aren't easy to reconcile without a clear idea of what the plan is for the mutation tree.

**Comment by EvilQU3S4D1LL4S** [comment]
for some reason it works just by ignoring it I combine the write and codes and copy to paste added the new things in catergory in Magiclysm just press I and the game is still playable with added things.

**Pull request closed without merging**
