### PR TITLE
Wield gun before attaching mods

### LINKED ISSUE #58078: I am allowed to attatch a suppressor to a USP .45 whilst it is in a holster that normally wouldn't fit a suppressed USP .45
### Describe the bug

if I attach a suppressor to a USP .45, it won't fit in the holster. however if I remove the suppressor and then place the USP .45 in the holster, I can reattach the suppressor and the gun stays in the holster. this causes an error to appear when loading a save;

" DEBUG    : error: item usp_45 cannot fit into pocket while loading: item is too long

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 384
 VERSION  : 0.F-2
"

### Steps to reproduce

see above

### Expected behavior

when loading the save, my suppressed usp will drop to the floor rather than stay in the holster.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

Bugfixes "Wield gun before attaching mods so there are no pocket conflicts"

#### Purpose of change

Fixes #58078

Guns could be modded while in a pocket that would make it too large for the pocket. This would cause problems after a save/load cycle.

#### Describe the solution

Wield the gun before modding it.

#### Describe alternatives you've considered

Do some checks that would disallow the mod if it would exceed pocket limits. Would not be as simple as this chosen solution.

Also considered doing the same treatment to detaching of gunmods. Decided against it as that seems to have no issues.

#### Testing

Attached gunmods with item wielded, in a holster, worn, and in inventory. In all cases the item was wielded with mod success.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Attaching gunmods should also be possible on a gun lying on a surface, like a workbench.

**Comment by Wyrdean** [comment]
Some pockets have a minimum volume/length as well.

**Comment by RoyBerube** [comment]
> Attaching gunmods should also be possible on a gun lying on a surface, like a workbench.

While it would be nice to use a nearby workbench, crafting uses a static function for that. Which means it is not accessible unless called from crafting file scope. It would take a bit of work to wrangle that over; perhaps using a namespace.

Translation: a lot of work for little gain.

**Comment by catdach** [comment]
Seems like a bit of a roundabout solution that might not be getting at the root of the problem. There are other reasons for a gun to change size while in a holster, such as loading it with a larger magazine or something. 

I guess for realism sake the character _would_ be wielding the gun before moding it, but the extra tedium of having to manually wield it, then mod it, then unwield it, is going to be quite a dip in quality of life. Especially in cases where the player might not realize that they can't use the mod because their skill level isn't high enough or whatever.

Also I ran into a similar bug that should be fixed by #58191, perhaps it will fix this too? 🤷

**Comment by mqrause** [comment]
> Also I ran into a similar bug that should be fixed by #58191, perhaps it will fix this too? 🤷

That's unlikely. Effectively all I did there was make sure the correct item_location is passed to the reload activity, so that's all that should be affected.

**Comment by catdach** [comment]
> > Also I ran into a similar bug that should be fixed by #58191, perhaps it will fix this too? 🤷
> 
> That's unlikely. Effectively all I did there was make sure the correct item_location is passed to the reload activity, so that's all that should be affected.

Yeah, I guess that was wishful thinking on my part.

**Comment by RoyBerube** [comment]
> I guess for realism sake the character _would_ be wielding the gun before moding it, but the extra tedium of having to manually wield it, then mod it, then unwield it, is going to be quite a dip in quality of life. Especially in cases where the player might not realize that they can't use the mod because their skill level isn't high enough or whatever.

The game does the wielding for you. I don't see the tedium. If instead of this solution, the mod were to be not allowed if it would expand in the pocket, how would that be better? Then you would have to wield it manually and would be the same state as this: wielding a weapon.

**Comment by catdach** [comment]
> The game does the wielding for you.
> 

Oh, in that case I just misunderstood what was happening. Please disregard my comments.

**Pull request merged**
