### PR TITLE
Fix throw zapback

### PR DESCRIPTION
**Pull request by kevingranade**
This was reported somewhere, but I can't find where, sorry.

The recent zapback fix in #23968 unfortunately triggered a more serious regression, throwing weapons started triggering zapping instead.

To reproduce:
Wield no weapon.
Spawn a shocker.
Throw a rock at the shocker (and hit).

Expected result:
Rock bounces off of shocker for a little damage.

Actual Result:
Rock bounces off of shocker and player gets zapped.

### CODE REVIEW

**Comment by Zireael07** [comment]
Reported in #24092?

**Comment by Mecares** [comment]
Does it also fix vehicle turret npcs getting killed when shooting shocker zombies? I read somewhere, on reddit i think, about turret corpses being dropped as a result of that bug.

**Comment by ZhilkinSerg** [comment]
> Does  it also fix vehicle turret npcs getting killed when shooting shocker  zombies? I read somewhere, on reddit i think, about turret corpses being  dropped as a result of that bug. /edit: https://www.reddit.com/r/cataclysmdda/comments/8tb3va/the_human_corpse_of_the_hypervelocity_driver/
--

and here #24109

**Comment by kevingranade** [comment]
I haven't checked, but based on how the fix it's likely.

**Comment by ZhilkinSerg** [comment]
Seems to fix both #24109 and #24092.

**Pull request merged**
