### PR TITLE
minor typo fixes and new content to hints

### PR DESCRIPTION
**Pull request by Jerimee**
#### Summary
```SUMMARY: None```

#### Describe the solution
```Copy edits and creation of a handful of new tips.```

#### Describe alternatives you've considered
```Submitting copy edits separately from original content.```

### CODE REVIEW

**Comment by Jerimee** [comment]
hmm... I actually did, or I thought I did. I'm sorry. Let me figure out what I smurfed up

**Comment by Jerimee** [comment]
I think the issue is that I cut and paste from windows into browser, and that is messing up the unicode-bom-special-character-witchery for the … character... (… is a single char, whereas this - ... - is three characters)

**Comment by anothersimulacrum** [comment]
The thing I noticed is that you have tabs instead of spaces.

**Comment by Jerimee** [comment]
On the off chance that this latest version passes all checks, please note that I've replaced all instances of _U+2026 : HORIZONTAL ELLIPSIS {three dot leader}_ with a simpler _..._ (three periods U+002E).

If this is undesirable, please do not merge.

**Comment by kevingranade** [comment]
Nope we want U+2026 : HORIZONTAL ELLIPSIS everywhere.

**Pull request merged**
