### PR TITLE
add house_w_6

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
```SUMMARY: Content "Adds new 2 story house.'"```

#### Purpose of change
continue nested house project.

#### Describe the solution
Added a house.

#### Testing
Spawned in world a lot to check nest placements and spawns.

#### Additional context
ground floor:
house_w_6_ground

2nd floor:
house_w_6_2ndfloor

roof:
house_w_6_roof

selection of nests: ground:
nests

selection of nests: 2nd floor:
nests 2

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Four bedrooms?

**Comment by curstwist** [comment]
Do we have a bedroom limit? Because I'm about to make more 4 bedroom ones. Which is a pretty standard layout. 3-4 is typical, especially for 2 story houses.

**Comment by Night-Pryanik** [comment]
If it's a standard IRL layout, then I have no more question. It just seems... too many to me.

**Comment by mlangsdorf** [comment]
both of the two story houses I've lived in had 4 bedrooms.  It's an extremely common number in America.

**Comment by curstwist** [comment]
Too many from a potential loot viewpoint or uncommon based on your personal experience?  I'm hoping more people will add nested_chunks for these houses, where they could replace some of the bedrooms with other possible rooms as well.  Usually it's 1 bedroom for parents, 2 standard for kids, and a guest bedroom/bonus room.

Once I start making more modern houses, they'll often have 3-4 bedrooms and 2 living rooms (family room & formal living room).  

If we end up adding more clothing sizes in the tailoring overhaul, I think the loot issue will equalize a lot, and we'll make more specifically children's bedrooms.

**Comment by Night-Pryanik** [comment]
> uncommon based on your personal experience?

This. I've never been in a house with 4 bedrooms.

**Pull request merged**
