### PR TITLE
vehicles: add support for amphibious vehicles

### LINKED ISSUE #20933: Enable playermade amphibious vehicles
Currently a vehicle is exclusivly landborne or waterborn, and amphibious crafts cannot be built or modded as "is boat" and "is not car" are hardcoded. I suggest that either restrictions on driving be removed and/or that `FLOATS` is divided up into `FLOATS` and (somethng like) `NOLAND`.

I think that @Coolthulhu was the last person working with the related code in #17687?

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "vehicles: add support for amphibious vehicles"```

#### Purpose of change
Fixes #20933
Remove the hardcoded limitations that require a vehicle either be a boat or a ground vehicle.  Allow people to put wheels on their boats, or boat boards on their cars, and seamlessly transition between land and water travel.

#### Describe the solution
First, change vehicle::gain_moves() so even stationary vehicles gain moves and have an opportunity to call act_on_map(), which is necessary because vehicles sink in act_on_map().  This solves a corner case where a stationary vehicle wouldn't sink - you could take your boat out to the middle of a lake, remove all the boat boards, and it would still float.

Second, stop pretending boat boards are some kind of weird wheel.  Boats float without taking on water when they have freeboard: their draft is less than the distance from the bottom of the hull to the top (aka the hull height).  Approximate hull height based on the percent of the vehicle's footprint that is covered by boat boards, calculate draft from the vehicle dimensions and mass, and set a boolean as to whether the vehicle can float or not.

Then instead of having two different calculations for whether a vehicle is in water - one in buoyancy and the other in k_traction - have a single function check_falling_or_floating that also checks as to whether the vehicle is falling or has 2/3rds or more of its tiles in water.  Continue to mercilessly destroy vehicles that are in water but can't float.

Generally simplify the logic for dealing with traction, which now deal exclusively with wheels.  Vehicles act as boats (with water movement, etc) when they are in water, and sink if they can't float.  Vehicles act as land vehicles if they aren't in water, and they don't move if they don't have enough wheels, whether or not they also have boat boards.

Please review and playtest carefully.  This isn't as as big as the vehicle speed rework but it's still changing some fundamental vehicle interactions - for the better but still.

#### Describe alternatives you've considered
~~The vehicle efficiency test is randomly failing.  I can't figure out why.   I considered deleting the randomly failing vehicles but that seemed like poor form.~~ Stale data was causing some tests to randomly start with the cruise velocity set to the water safe speed.  Fixed by initializing the relevant values and explicitly calling safe_ground_velocity().

There needs to be a better solution for dealing with sunken vehicles.

#### Additional context
Built on top of #27225.

itsa_hmmwvvitsa_dukw
My HMMWV is actually a DUKW.  It has boat boards, it has wheels, it drives on the ground, it floats on the water (barely).

itsa_hmmwvvitsa_dukw2
Driving on a bridge at 30mph.

itsa_hmmwvvitsa_dukw3
Moving across the lake, faster than my engine can handle.

itsa_hmmwvvitsa_dukw4
Back on dry land, no problem.

itsjustacanoe1
This canoe is just a canoe.  It has no wheels.

itsjustacanoe2
It doesn't go places on land because it has no wheels.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
I think I found the issue with the failing tests and should have fixed pushed shortly.  Stale data was causing some tests to run with water_safe_velocity as the cruise velocity.

**Comment by mlangsdorf** [comment]
Jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Can you include amphibious vehicle for testing purposes?

**Comment by mlangsdorf** [comment]
Sure!

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/amphibious-monsters-and-vehicles-perhaps/22361/2

**Pull request merged**
