### PR TITLE
[CR] Better pipe spear

### PR DESCRIPTION
**Pull request by TealcOneill**
#### Summary
None

#### Purpose of change
I felt the pipe spear was pretty weird with the odd dimensions and material generation so I took a look and realized that the recipe was way overkill for what should be a simple spear.

#### Describe the solution
I increased the length to 185cm(3 pipes + 2 roughly 1 inch long pipe fittings) to make it actually as long as the other reach weapons. I changed the recipe to use 3 pipes and 1 pipe fittings instead of magically extending a 60cm pipe to 150cm somehow using welding. Removed the welding and metalworking proficiencies since this should be a basic thrown together weapon. Removed the hacksaw tool and lowered the hammering quality required, so instead of finely cutting a tip you're just smashing it into a rough point. Oh, and I dropped the damage a little bit.

#### Describe alternatives you've considered
Not doing this, or simply adding a pointy pipe recipe and having this one take 3 pipes.

#### Testing
Loaded up a game and made sure the damage was about where I expected it and that the recipe worked fine.

#### Additional context
I don't really have a good grasp on the damage system yet so if anyone has any thoughts on the damage this should do that would be great. Any other thoughts or ideas are totally welcome.

### CODE REVIEW

**Comment by Shodan14** [comment]
Isn't the main point of the pipe spear that you can easily "sharpen" it by cutting the pipe diagonally? Smashing would get you something else.

**Comment by PatrikLundell** [comment]
I haven't found pipe fittings to be something you stumble upon frequently, so to make one would probably require an early character to be able to identify the set of items that may yield them when smashed (or picked apart using simple disassembly: I think "proper" disassembly would require tools the kind of character who'd need one might not have).

**Comment by Shodan14** [comment]
> I haven't found pipe fittings to be something you stumble upon frequently, so to make one would probably require an early character to be able to identify the set of items that may yield them when smashed (or picked apart using simple disassembly: I think "proper" disassembly would require tools the kind of character who'd need one might not have).

Don't you get a set for each sink you smash?

**Comment by PatrikLundell** [comment]
I suspect that might be the source of most of the ones I've found, but it's not easy to determine what the zombie smashed pile used to be.

**Comment by TealcOneill** [comment]
> Isn't the main point of the pipe spear that you can easily "sharpen" it by cutting the pipe diagonally? Smashing would get you something else.

That's a really good point that I actually hadn't realized, which in hindsight is pretty silly. I'll re add metal cutting to the recipe.

> I haven't found pipe fittings to be something you stumble upon frequently, so to make one would probably require an early character to be able to identify the set of items that may yield them when smashed (or picked apart using simple disassembly: I think "proper" disassembly would require tools the kind of character who'd need one might not have).

I mean, you can find pipe fittings from several household and generic furniture pieces where you would expect them. I think this should be a lot easier than finding a welder and welding goggles early on.

**Comment by Scorch-Mechanic** [comment]
I believe you can get pipe fittings from disassembling metal shelving. 

I like this new spear, but is it necessary to discard the existing very simple single-component pipe spear? Couldn't we just shorten the existing one and make it into a non-reach weapon like a sharpened rebar or a pointy stick?

**Comment by TealcOneill** [comment]
> I like this new spear, but is it necessary to discard the existing very simple single-component pipe spear? Couldn't we just shorten the existing one and make it into a non-reach weapon like a sharpened rebar or a pointy stick?

That was one alternative I considered so I could probably add that once I get the kinks with this one worked out.

**Comment by Shodan14** [comment]
> 
> 
> > I like this new spear, but is it necessary to discard the existing very simple single-component pipe spear? Couldn't we just shorten the existing one and make it into a non-reach weapon like a sharpened rebar or a pointy stick?
> 
> That was one alternative I considered so I could probably add that once I get the kinks with this one worked out.

Pipe shortspear.

**Review by I-am-Erk — CHANGES_REQUESTED** [review]
I don't object to what you want to do here, which appears to be making a more makeshift pipe spear, but I don't like removing the existing spear recipe to make room for it. The previous pipe spear was a durable weapon crafted carefully from a pipe using time and advanced tools to make sure it was suited to melee use. Your new spear is made in five minutes with finger-tightened pipe fittings and yet is more durable, more damaging, and overall better in almost every way. I disagree with this philosophy in a vacuum, you need to do some convincing for why this should be the case.

I think adding a "sharpened pipe" weapon that's inferior to the pipe spear but easier to make is a great idea. I am less convinced by your changes to the existing pipe spear and, unless you have a clear rationale for making them, I think they shouldn't be included.

**Comment by Shodan14** [comment]
> 
> 
> I don't object to what you want to do here, which appears to be making a more makeshift pipe spear, but I don't like removing the existing spear recipe to make room for it. The previous pipe spear was a durable weapon crafted carefully from a pipe using time and advanced tools to make sure it was suited to melee use. Your new spear is made in five minutes with finger-tightened pipe fittings and yet is more durable, more damaging, and overall better in almost every way. I disagree with this philosophy in a vacuum, you need to do some convincing for why this should be the case.
> 
> I think adding a "sharpened pipe" weapon that's inferior to the pipe spear but easier to make is a great idea. I am less convinced by your changes to the existing pipe spear and, unless you have a clear rationale for making them, I think they shouldn't be included.

If the current pipe spear is supposed to be crafted using "advanced tools" and all fancy it really should include a grip and not have a -1 to hit.

**Comment by Zireael07** [comment]
+1 to adding grip to the current spear

**Comment by TealcOneill** [comment]
> I don't object to what you want to do here, which appears to be making a more makeshift pipe spear, but I don't like removing the existing spear recipe to make room for it. The previous pipe spear was a durable weapon crafted carefully from a pipe using time and advanced tools to make sure it was suited to melee use. Your new spear is made in five minutes with finger-tightened pipe fittings and yet is more durable, more damaging, and overall better in almost every way. I disagree with this philosophy in a vacuum, you need to do some convincing for why this should be the case.
I think adding a "sharpened pipe" weapon that's inferior to the pipe spear but easier to make is a great idea. I am less convinced by your changes to the existing pipe spear and, unless you have a clear rationale for making them, I think they shouldn't be included.

I'm going to try and explain this simply, for my sake since I'm not great at communicating and I didn't do a good enough job before. 
1) Why I think the old recipe was bad.
Taking a single 60cm pipe and somehow welding it to be 150cm doesn't make any sense and still leaves it almost a foot shorter than the other reach weapons. With the thickness I imagine the pipe in-game being, this spear being made of a single piece of it and not being a durable_melee weapon just doesn't make sense.
2) Why I made the new recipe the way I did.
You could weld three pipes together and the pipe would be pretty strong, but with decent pipe fittings the spear will be just as strong and not require tons of skill. Something I forgot to mention above was why this recipe requires hammering. If you tighten the pipes and then give each joint a couple of good smacks it will not be able to loosen unless you cut the pipe fittings off. I did originally decrease the damage of the spear to reflect the lower fabrication requirements but I was recommended to leave the dps of the weapon alone. With the weight of the weapon tripling I had to increase the damage to make it match the previous dps.
3) Other things.
I don't really see how you could use the stuff the recipe had before to create a carefully suited weapon. There were none of the tools that would be needed to reforge it or add anything special to the pipe that this one doesn't have. Perhaps you could better balance the spear but again the recipe doesn't say anything about that and the to-hit bonus is the same as other spears. As for the time to make, it's just tightening three pipes together and smacking them a few times and then cutting an angle.

**Comment by I-am-Erk** [comment]
My assumption was that a welder was at least attaching a sturdy head to the pipe. I think if you're going with the idea listed here, your tools are strange: a hammer and hacksaw won't make a good, combat-ready spearhead, and aren't the ideal tools for fitting a pipe together. Looking at the recipe at a glance, I don't think I could guess what's going on in it. The welder isn't a sacred cow, but overall it should be clear how we're building this and what the end result is.

**Comment by TealcOneill** [comment]
> My assumption was that a welder was at least attaching a sturdy head to the pipe. I think if you're going with the idea listed here, your tools are strange: a hammer and hacksaw won't make a good, combat-ready spearhead, and aren't the ideal tools for fitting a pipe together. Looking at the recipe at a glance, I don't think I could guess what's going on in it. The welder isn't a sacred cow, but overall it should be clear how we're building this and what the end result is.

I see where you're coming from and that's reasonable, I didn't see anything in the old recipe that indicated putting a head on it. One comment above says that they think the sharp part of the spear is just cutting the head off at an angle which seems right to me. I could see lowering the damage on this a bit and adding another recipe that has this as the main ingredient, while using a scrap of steel and some tape or string or something to improve the grip. Does that sound reasonable to you?

**Comment by TealcOneill** [comment]
I'm having some issues with git so I'm going to close this and reclone my repo and then I'll open it anew.

**Comment by Shodan14** [comment]
Just for context, I think the spear bit is supposed to be something like you can [see here](https://www.youtube.com/watch?v=SJSIUgk6xpQ). Basically a huge syringe, that should be doable with a saw and some skill.

**Pull request closed without merging**
