### PR TITLE
Fixup source control regressions [CR]

### PR DESCRIPTION
**Pull request by mugling**
See #18563.

This should back out of the unreviewed changes whilst still addressing the buildbot failures resulting from #18548. It should unblock all the PR's that have become merge conflicts in the last 24 hours.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Anybody have anything to add to this? If not, I'll look into merging this as soon as I'm home this evening.

**Comment by Rivet-the-Zombie** [comment]
The buildbot isn't going to choke on a reversion to a non-whitelisted file because the autochecker hasn't run on it yet, is it?

Just typing that out makes me feel like it's a stupid question, but that danged bot has more allergies nowadays than a kid in a bubble, so I figure it can't hurt to ask.

**Comment by Coolthulhu** [comment]
Are you sure this will unblock everything?
I'm not all that good at git, but from what I know, reverting only applies a reverse diff, without actually causing the original commit to be unrolled. We could need a master branch rebase here.

Also, I don't see the conflict here and buildbot doesn't seem to be complaining. Is some part of it turned off?

**Comment by codemime** [comment]
I'm not quite sure this helps fixing the buildbot. According to [the log](http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Jently/lastBuild/), Jenkins has been in coma for about 4 days from now, and #18548 was merged less than a day ago. I assume that PR has nothing to do with the failure. The culprit is probably somewhere else. Could that be #18516 (the last checked PR), or a PR that was merged after?

**Comment by Coolthulhu** [comment]
> Jenkins has been in coma for about 4 days from now

I guess @narc0tiq is the only one who can fix it now.

**Comment by pisskop** [comment]
timestamps for git posts/commits have done the 'future commit' thing for maybe 3 months now?

**Comment by mugling** [comment]
> The buildbot isn't going to choke on a reversion to a non-whitelisted file because the autochecker hasn't run on it yet, is it?

No, I'm certain on that

> but that danged bot has more allergies nowadays than a kid in a bubble

I appreciate you are frustrated but you need to consider that and previous sentiments in context. The buildbot is a lot of work on someone elses part, that has ongoing running costs, and has been donated to the project. It is a helpful tool that has both allowed us to survive the long gap since `0.C` and helped us improve the quality of the codebase.

The buildbot hasn't caused the current issue - a small problem has been magnified into a large one by a decision to continue merging and then a bad 4.5k line unattributed commit followed by further merges.

> Jenkins has been in coma for about 4 days from now
> 
> I guess @narc0tiq is the only one who can fix it now.

When the buildbot is down the safe options are either not merging or the following manual checklist:

* `--check-mods` (ensures you don't have a JSON syntax error)
* `make astyle` (or confirm PR doesn't touch any files from `astyle_whitelist`)
* `make lint-check` (or confirm PR doesn't touch any files from `json_whitelist`)

> I'm not quite sure this helps fixing the buildbot.

It should allow us to build game binaries that contain critical fixes (#18565). The PR builder I'm not certain as to the cause of breakage but @narc0tiq will hopefully restore it in due course

> Are you sure this will unblock everything?
> I'm not all that good at git, but from what I know, reverting only applies a reverse diff, without actually causing the original commit to be unrolled. We could need a master branch rebase here.

Yes, but the git history for `game.cpp` would be a casualty here. I think a `rebase` would be better. I'm going to push #18565 so that if the buildbot gives up completely after a `rebase` then the last available copy will include the fix.

**Comment by narc0tiq** [comment]
Rebasing, especially on a published and popular branch, should not be
considered. Everyone who has a copy of that branch would have to force
update their copy, as the public history will have diverged from what they
have.

This also applies to amended commits - once you've pushed it, never change
it.

---

I've kicked the PR builder so it'll probably come up again soon, if it
hasn't already. I don't check up on it that often, so if nobody tells me
it's broken, I'll assume it isn't. A quick ping in an issue note or a poke
on IRC is enough, but absent those, you're relying on me going to the
Jenkins front-end, which I rarely need to do, and noticing a long time
since the last build.

**Comment by mugling** [comment]
> Rebasing, especially on a published and popular branch, should not be considered

Agreed it's not very nice. This PR avoids that but it does leave the history (line attribution) messed up.

**Comment by narc0tiq** [comment]
> it does leave the history (line attribution) messed up.

Can't be helped. What was published *can technically* be unpublished, but then you'll be dealing with "how I fix git?" for weeks thereafter from every contributor that runs up against the failure to pull due to "not a fast-forward". Or worse, they'll try and fix it themselves with a merge commit (as git 'helpfully' recommends) and I'm not sure if that won't just reintroduce the same commit you'd attempted to rebase out.

**Comment by mugling** [comment]
That's definitely the better argument - lost (hidden) history is better than a dozen contributors unable to pull `master`

**Comment by BorkBorkGoesTheCode** [comment]
Will author attribution be lost?

**Comment by mugling** [comment]
For `game.cpp`, yes (technically it will be hidden)

**Comment by narc0tiq** [comment]
Not at all, it's just that `git blame` will show a different commit (and thereby, a different person) as "last touched" those lines, because it will have been. The correct (for whatever value of "correct") source can be followed up in the Git history, if needed.

**Comment by mugling** [comment]
I wrote technically as `git blame` is the most common tool for checking and is fairly useful for determining 'how long has that code been there'

**Comment by narc0tiq** [comment]
Fair enough, consider it more a clarification, then.

**Comment by mugling** [comment]
I think our course of action is clear here - rebase is more evil than revert and obviously it would be good to get those 4.5k untested lines out of production as soon as reasonably practical (`astyle` probably has bugs especially as C++ isn't always strictly whitepsace insensitive and also because we are going to start accumulating merge conflicts against both variants)

**Comment by BorkBorkGoesTheCode** [comment]
The buildbot is working again.

**Comment by mugling** [comment]
> The buildbot is working again.

And it says it's happy with this PR. There is no ideal solution but this is the best so I'm going to merge it. This doesn't exclude a later `rebase` if we really want to but I think @narc0tiq's arguments are the most compelling

**Pull request merged**
