### PR TITLE
Translations update

### PR DESCRIPTION
**Pull request by VlasovVitaly**
Regular translations update:
Transifex updates:
- German
- Argentinian
- Italian
- Russian

Launchpad updates:
- French
- Japanese
- Korean
- Chinese

### CODE REVIEW

**Comment by KA101** [comment]
w00t!

**Comment by VlasovVitaly** [comment]
wOOt "wOOt"?

This PR isn't big enough? O_O

**Comment by KA101** [comment]
Uh, no, it's so big that Git doesn't list out the translations.  (I'm a bit of a jagoff and enjoy reading 'em.)

*KA101 is appreciative & favorably impressed*

**Comment by VlasovVitaly** [comment]
It's because 2 weeks without updates. :| Some language has 15k lines of changes...

**Pull request merged**
