### PR TITLE
Made minefields more dangerous and interesting

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Minefields are more dangerous and interesting."```

#### Purpose of change
"Square-shaped" minefields with signs marking exact boundaries always looked weird and boring to me. I believe minefields are meant to be disguised, and mines are meant to be hard to discover. Also, "rash" appearing when minefields are spawned on roads isn't unrealistic and pretty ugly to be honest.

#### Describe the solution
- Removed dirt terrain dotting the location altogether and removed dirt mounds revealing exact locations of mines;
изображение
- If terrain is diggable, then mines will be buried. Otherwise there will be ordinary mines;
изображение
- Randomized signs placements;
изображение

#### Describe alternatives you've considered
Forbid minefields to spawn on roads so we don't get this ugly picture
изображение

#### Additional context
~The only thing I'm not sure about this is invisible mines under placed under the asphalt is plausible.~

In overall minefields should be much more dangerous due to uncertainty of their boundaries and no external features revealing location of buried mines.

### CODE REVIEW

**Comment by Xenomorph-III** [comment]
We really need something like a metal detector/mine disarmimg kit and EOD suit if this will be the case. 

Otherwise people randomly blowing up won't make for a good user experience.

**Comment by Night-Pryanik** [comment]
> Otherwise people randomly blowing up won't make for a good user experience.

The signs are still here. The best strategy for this: "Spotted a sign? Get out of here as fast as you can". Besides, people sometimes randomly blown themselves up even on the old variant.

**Comment by paulenka-aleh** [comment]
Are there many minefields in New England? Based on lore, why minefields are there at all? If they're old they would be even sorrounded by fence even before the cataclysm. If they were deployed recently by military to stop zombies spreading their boundaries would surely be marked to warn civilians (except for rare cases when accidents happen during deployments when minefields were placed already but boundaties were not marked yet).

Mines below pavement seems to be odd. Who, when and how would put them there? And on the pevement they shouldn't be hard to spot unless you're driving 100mph at night with lights off... Btw, exactly such careless actions made my character blow up even on familiar roads even with the current ugly minefields

Not that I'm against, just looks like weirdness about minefields isn't gone with this PR

**Comment by Rail-Runner** [comment]
I think minefields on a road could happen, but they would have to be not buried.

**Comment by Mecares** [comment]
Well according to the lore the minefields where deployed against a human military invasion if i remember correctly and not only against zombies.

**Comment by Night-Pryanik** [comment]
изображение
If terrain is diggable, then mines will be buried. Otherwise there will be ordinary mines.

**Comment by esotericist** [comment]
whew. When I first saw this PR and the pictures in the opening post, I was Very Concerned.

I'm glad you walked back the invisible mine change for roads, because it would have made little sense, and it would have been too severe a "haha u died lol" issue for people while driving.

But even then, I'm a little bit unsold the extent of the change here. "more dangerous and interesting" should not readily translate to "I don't know why I died", and minefields are very suddenly dedz for many players already. Removing *either* the guaranteed sign placement *or* the mounds of dirt I can see...

But with how the game works, and the potential difficulty of spotting things *as a player* that the character should naturally spot (I have on MANY occasions been unable to notice the signs at first but noticed the churned dirt at the last moment, even though the signs should be "more obvious" to someone driving), I think doing both is entirely too severe.

**Comment by Night-Pryanik** [comment]
I can return the guaranteed four signs placements, though their location will still be randomized:
изображение
изображение

**Comment by esotericist** [comment]
That would be an improvement in my eyes. Now maybe I need to figure out how to have Safe Mode fire off of minefield signs... :D

**Comment by esotericist** [comment]
Just as a side note on the realism element:

The overwhelmingly vast majority of military-placed mines are not a "trap". They're a deterrent. They're a "Stay the hell out of this area, it has consequences" measure, and you're intended to ***damn well know*** they're there (even if you don't know exactly *where* they are). That's why there's signs in the first place; the expectation is for people to look at the sign and go "maybe I don't want to go that way".

**Comment by SomeDeadGuy** [comment]
Would be nice to have signs only dedicated to mine fields. So i can make different DANGER themed tiles for them.

**Comment by esotericist** [comment]
> Would be nice to have signs only dedicated to mine fields. So i can make different DANGER themed tiles for them.

That should be doable.

**Comment by Night-Pryanik** [comment]
As one last step I could return the placement of signs back in the corners if you think it will improve the visibility.

**Comment by esotericist** [comment]
> As one last step I could return the placement of signs back in the corners if you think it will improve the visibility.

I actually like a little bit of randomness to the placement; makes it feel more organic.

As long as all four edges are marked i think that covers due diligence on the part of whoever placed the mines. At this point the only two quibbles I might have are:

a) maybe restrict the range the signs can be in to the center 3/4ths or so of each edge if possible (to keep them *away* from the corners)
b) I really like the idea of adding something like a `f_sign_minefield` object so that we can have a separate sprite for distinctiveness

**Comment by Night-Pryanik** [comment]
Added a universal `warning sign` and made it spawn near the minefield instead of old plain `sign`.

**Comment by Night-Pryanik** [comment]
@esotericist done both a) and b) in your review.

**Comment by nexusmrsep** [comment]
Idea for the future: it would be nice if minefields on some cases spawn in multiple linked overmap tiles, lets say for example line of 5, or 2x2. Or even better if they could sometimes do actual big-scale area denial, for example cutting off bridge access, or circling a small town/outpost etc. where you would be actually forced to find a way to deal with the minefield itself in other way, then simply going around it.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Idea for the future: it would be nice if minefields on some cases spawn in multiple linked overmap tiles, lets say for example line of 5, or 2x2. Or even better if they could sometimes do actual big-scale area denial, for example cutting off bridge access, or circling a small town/outpost etc. where you would be actually forced to find a way to deal with the minefield itself in other way, then simply going around it.

We need to resurrect https://github.com/CleverRaven/Cataclysm-DDA/pull/25824

**Comment by dom4op** [comment]
I disable minefields completely in my games (btw there should be a mod for this), because they are unrational. A dozen mines buried in completely random place (a swamp or a huge open field) just doesn't make any sense. While this PR is certainly an improvement gameplay-wise, I still don't see rationale behind random mindfields lore-wise. Would very much prefer if minefields were spawned around very specific location where they would make actual sense (military bunkers, outposts, prisons, labs, etc)

**Comment by kevingranade** [comment]
So first a caveat, these minefields were added pre-dda so we do not know what the intent was for them, all we can do is see if there's something we can come up with that makes sense.  Alternatively, removing them IS an option.  Personally I think whales just coded up traps, included minefields, and scattered them around without putting much thought into the scenario.

The scenario that makes sense for me to explain the current minefields are that they were placed by the military as an anti-zombie measure under the presumption that it was the lesser evil. This is the rationale for the signs, to warn off ordinary citizens but be a threat to zombies.

The only thing that makes the randomly placed minefields at all sensical is to presume something like https://en.wikipedia.org/wiki/Family_of_Scatterable_Mines was extended to also drop pop-up signs to warn off the public, and they were literally fired off at random in infected areas.

While we can somewhat justify the existing minefields (so I'm not pushing for immediate removal), the better option IMO is to come up with scenarios where they would actually be used in the final fight against zombies and other threats.  They would be placed around bases as an outer perimeter and tactically in order to cover movement of troops, and potentially sprinkled into areas known to have large zombie populations.

Side note, the whole subplot about a ground invasion occurring concurrently with the Cataclysm has been abandoned. AFAIK it was only ever a weak justification for occasional spawns of Soviet Bloc firearms and other hardware.

**Comment by Sooose** [comment]
Personally I don't like this change, minefields are already an unfun and uninteresting way to die. I don't think shuffling the signs around and making them harder to notice due to removal of the churned Earth is really going to fix that. In the end this is just going to make me spend even longer staring at the map in front of me while driving which adds unnecessary tedium. Sure, I could remove minefields from my game but that would remove an excellent source of BBs and gunpowder for making my own ammo.

**Comment by Mecares** [comment]
> Side note, the whole subplot about a ground invasion occurring concurrently with the Cataclysm has been abandoned.

Thank you for that clarification.

**Comment by esotericist** [comment]
> The only thing that makes the randomly placed minefields at all sensical is to presume something like https://en.wikipedia.org/wiki/Family_of_Scatterable_Mines was extended to also drop pop-up signs to warn off the public, and they were literally fired off at random in infected areas.

If this is accepted as an explanation for the randomly place minefields, should these mines possibly not be hidden even in open fields?

**Comment by kevingranade** [comment]
Sort of, they would not be buried, but the antipersonnel mines used by these systems are only 82mmx54mm and deploy trigger wires in all directions up to 20ft away, so while they would be relatively easy to avoid on e.g. asphalt, any degree of ground cover renders them almost undetectable.

**Comment by thethunderhawk** [comment]
FASCAM bomblets have self destruct fuses IRL. IMO minefields make very little sense except in specific circumstances. I could see a proper minefield being set up around a location to be defended, or raiders setting up ambushes along obvious lines of travel, but random minefields seem like a waste of life and ordinance at best.

**Comment by KurzedMetal** [comment]
If the lore behind the minefields is destroying the Zombies (which make sense), I'd suggest converting them into anti-personnel ones and make Vehicles (at least heavy duty ones) almost immune to them.

I never understood lore-wise why the military would place anti-tank mines vs Zeds and fuck humanity for the sake of it. Or even why the CDDA mines seems effective vs everything: both personnel and tanks.

**Comment by faefux** [comment]
> EDIT: closest thing to a random minefield I can imagine is a small pillbox or sandbag fortification with a minefield in front of it, set up by engineers as a proper manned strongpoint or defensive position. It could include soldier corpses or soldier zeds, and it’d probably have a mine-free path in and out of the fortification for the defenders to use.

Are you going to work on this map? If not i'll happily get to it over the next few days. these would exist on roads or roadsides, right?

**Comment by Night-Pryanik** [comment]
No, I doubt anyone would be working on it. You are welcome to try to implement it.

**Comment by faefux** [comment]
Will do, Thanks!

**Pull request merged**
