### PR TITLE
Makeshift Steel Ballistic Plates

### PR DESCRIPTION
**Pull request by Novacat**
#### Summary
Content "Adds craftable makeshift ballistic plates"

#### Purpose of change
I was kind of bummed out about the lack of steel ESBI plate options. I added the ESAPI ones just for completion sake.

#### Describe the solution
Adds craftable ESAPI and ESBI plates.

#### Describe alternatives you've considered
I thought about just adding Steel ESBI plates, but I did not want to mess with loot tables.

#### Testing
I regularly play with these in my current game.

#### Additional context
These are supposed to be more professionally done than scrap plates, something you could achieve in a blacksmith's forge. The resources, expertise and time are somewhat patterned on plate armor.

This also adds a new nested category for these plates, which also includes scrap ESBI/ESAPI plates.

PS: I have been asked to write 'I am Nanaki'

### CODE REVIEW

**Comment by tenmillimaster** [comment]
The makeshift ballistic plate I'm fine with, the spall liner I still find weird. I still think it should be some sort of historically used ballistically resistant material (just a lot less of it than a ballistic vest). If leather worked as a spall liner, I think it would have been used for flak vests.

**Comment by Novacat** [comment]
It could be changed if requested. The main reason why I went with Leather is that it could be produced from scratch without needing to salvage materials. Mostly to help out those that might somehow want to use these for an Innawoods run.

**Comment by turco-ai** [comment]
I really like the makeshift plates idea but the liner really should be kevlar, I'm sure the innawoods people will figure something out.
It should also take less time to make them, at least the ones of a lower grade steel. Being able to craft tempered plates like the ones found in police/swat vests would also be cool.

**Comment by fairyarmadillo** [comment]
> The makeshift ballistic plate I'm fine with, the spall liner I still find weird. I still think it should be some sort of historically used ballistically resistant material (just a lot less of it than a ballistic vest), like nylon, fiberglass, kevlar. If leather worked as a spall liner, I think it would have been used for flak vests.

> It could be changed if requested. The main reason why I went with Leather is that it could be produced from scratch without needing to salvage materials. Mostly to help out those that might somehow want to use these for an Innawoods run.

Historically, cuir bouilli (and later buffcoats, made of very thick buffalo hide) was worn under a metal cuirass in fights where both sides were shooting guns at each other. I doubt they'd have done this if the coat wasn't at least expected to help with spalling.

I'm not sure "innawood" materials should be able to stand up to 5.56 though. A decent compromise might be to cap the ballistic protection well below what properly backed plates could provide.

**Comment by Novacat** [comment]
I am currently operating under the assumption that the mapgen issues showed in tests are not related to this PR, which does not touch mapgen at all.

**Pull request merged**
