### PR TITLE
Sewer monster rework and morale debuffs

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Content "The sewers now feature different monsters and cause morale debuffs, especially for characters with the squeamish trait, for prolonged stays"

#### Purpose of change

Somewhat related to #70221, having sewer snakes, gators and seweranhas are just peak cliché.
They are not realistic at all.

#### Describe the solution

Changes mongroup that spawns in the sewers:
- No more sewerranhas, gators and sewer snakes.
- No more frogmothers.
- Tadpoles and frogs can still spawn, but rarely. Same as cats.
- It is mostly flies, rats and raccoons down there now. And sewer slimes.
- New monster: Sewer slime. Copied from the ordinary slime and does biological damage on hit, very rare or even unique for a monster, and explodes in a gas of toxic gas on death. I find this very fitting for the sewers and utilizes an already existing faction.
- New monster: Dextrous raccoon. Preparations for when I eventually do the same to subways. They can open doors and will try to eat your food, but are not overly hostile. More a nuisance than anything else.
- Crawling zombies can be down there, too. Imagine one falling down an open manhole, mangling its legs and thus becoming a crawling zombie.

Thanks to an EOC we also got ambient sewer messages now, which are purely cosmetic.
Another EOC I introduced inflicts morale debuffs onto the character for being in the sewers, making them more hostile but not necessarily more dangerous.

Source I used: https://ukdnwaterflow.co.uk/animals-found-drains-sewers-around-world/
Plus common sense. There are storm drains with mostly "clean" rainwater and sewers with yucky sewage. But there are most definitely cats that fell into sewers (Cat rescue org rescuing some kittens out of a sewer: https://www.youtube.com/watch?v=UrKeOQVjvqA), raccoons. rats, flies.

#### Describe alternatives you've considered

- Adding larvae into sewers. That would make sense. Maybe later
- Adding random corpses. As in so many "rioters" died, they just threw them down a manhole. Would be story telling.
- Also targeting the sewage treatment plant. Maybe later. This is why I havent obsoleted those monsters yet.

#### Testing

Loads and runs as expected.

image

image

#### Additional context

Thanks GuardianDll for helping me fix the EOCS. I also fixed the issue where ambient lab subway sounds would not have triggered due to missing brackets.

### CODE REVIEW

**Comment by ashGlaw** [comment]
Now we need some sort of trait that makes spending time in the sewers feel good lol

**Comment by fairyarmadillo** [comment]
> Now we need some sort of trait that makes spending time in the sewers feel good lol

I was planning on making saprovores not mind gross stuff as much, since they eat rotten food.

**Comment by Nebnis** [comment]
Are those messages spammy? it would be nice if these debuffs didn't trigger if you were inside, lets say a tent or some shut in location. So it becomes a good place to live if you put some effort. +1 to the trait idea too lol

**Comment by fairyarmadillo** [comment]
When I do a second pass on the bile stuff I updated, I'm also going to make it so that standing in sewage can make your shoes and pants filthy unless they're totally waterproof, and lying in it will make you filthy all over. That'll go really well with this stuff.

**Comment by anoobindisguise** [comment]
Shouldn't wearing a gas mask reduce the penalty? You wouldn't really be able to smell much in a mask right?

**Comment by BlizzDA** [comment]
> I was planning on making saprovores not mind gross stuff as much, since they eat rotten food. I don't think anyone would really prefer huffing concentrated fart gas though. Rats and roaches live in sewers IRL but they're fastidiously clean animals and are probably distressed by the conditions down there.

Trog might be a good mutant-line for it. Sewers would also be a prime place for mutant tubifex worms that like it just fine, and Trog does get samples from worms. C.H.U.D. was also the sort of aesthetic/gameplay it goes for.

**Comment by NetSysFire** [comment]
>and roaches

oh right. I forgot about those

**Comment by fairyarmadillo** [comment]
I don't think a gas mask should do anything really. It's a sewer. There's pee and poo everywhere. That is gross.

**Comment by casswedson** [comment]
> Crawling zombies can be down there, too. Imagine one falling down an open manhole, mangling its legs and thus becoming a crawling zombie.

Is it possible to modify the manhole mapgen to occasionally generate instances without any cover

**Comment by NetSysFire** [comment]
>I don't think a gas mask should do anything really. It's a sewer. There's pee and poo everywhere. That is gross.

Indeed. *Maybe* but just maybe dampen the morale penalty with it on but I made the debuff snippets not just refer to smell.

**Comment by Procyonae** [comment]
> Is it possible to modify the manhole mapgen to occasionally generate instances without any cover

Should be, I need to relook at them because the ones on crossroads don't line up so I can do it then if it doesn't get added to this PR

**Comment by NetSysFire** [comment]
I won't add much more than bug fixes, if there are any bugs I added, in this PR.

>Are those messages spammy?

No. In my case I just waited without any monsters or actions inside. And given the fact they do not trigger any minute, it should not be spammy and barely noticable, but still a reminder that its unpleasant to be there.

**Comment by Rokharn** [comment]
> I don't think a gas mask should do anything really. It's a sewer. 

Even after years in cities where there are no living people left? If we look at the sewers of fallen civilizations, they are now clean. Not sure how long it took, but still. 

I think that the sewerage pumping stations  will not be cut down immediately with the onset of the cataclysm and will be able to operate autonomously for some time. Therefore, after a certain time, the sewer may not be such a bad place as it was during a living civilization.

**Comment by Alm999** [comment]
I hope I've read it right and new slime monster actually do not have the ability to FORMBLOB. Otherwise all the sewers will be filled with slime to the brim in no time.

(Slimes with their ability to multiply exponentially are driving me crazy!)

**Comment by fairyarmadillo** [comment]
> I hope I've read it right and new slime monsters actually do not have the ability to FORMBLOB. Otherwise all the sewers will be filled with slime to the brim in no time.
> 
> (Slimes with their ability to multiply exponentially are driving me crazy!)

I was trying to get regular slimes to do their exponential growth thing, but it wasn't happening. FORMBLOB as far as I can tell doesn't make new slimes, it just allows them to combine and split while keeping the number of total slimes constant.

Does something special have to happen to make it work?

**Comment by Alm999** [comment]
> I was trying to get regular slimes to do their exponential growth thing, but it wasn't happening. FORMBLOB as far as I can tell doesn't make new slimes, it just allows them to combine and split while keeping the number of total slimes constant.
> 
> Does something special have to happen to make it work?

I think, it has something to do with "critical mass". In my recent run I encountered a "College Kids" event at -1 level in a normal basement. There were (most probably one/two) amoebic molds and some zombies initially. By the time I got there and opened the door (the basement was locked behind twin doors) the whole room was filled with big slimes at each and every tile. Every! Tried to fight (they are too tough), using nailboard traps (slimes are surprisingly susceptible to nails, it seems) upstairs… Killed like, 30 of them. Used debug to see how are things downstairs: still full. They just keep spawning.

For this reason any Slime Pit id you stay long enough near it will turn into one giant blob of several thousand big slimes…

**Pull request merged**
