### PR TITLE
Update MSX++DeadPeopleEdition 2019-02-08

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Interface "MSX Dead People tileset update"`

### CODE REVIEW

**Comment by sneeze-attack** [comment]
@Pupsi-Mupsi any specific reason you are removing the changes introduced in #27962 ? That will make the current lab mapgen look pretty broken unless you also revert all of the lab mapgen changes also made in that PR.

**Comment by Pupsi-Mupsi** [comment]
Hmmm....

I though I was merely bringing the tileset to the latest version as it is offerd here:
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

**Comment by Pupsi-Mupsi** [comment]
@sneeze-attack

I'm closing this PR. Would you get in touch with @SomeDeadGuy to implement your changes in his original tileset?

**Comment by sneeze-attack** [comment]
@Pupsi-Mupsi can do!

**Comment by SomeDeadGuy** [comment]
Pupsi, continue. :)

**Comment by Pupsi-Mupsi** [comment]
I'll do. Just give me a few days. I'm currently handling a cold.

**Comment by SomeDeadGuy** [comment]
Ofhorse. get healthy
I added hair to my tileset, so when please take my latest version for update.

**Pull request closed without merging**
