### PR TITLE
Return the default font to Terminus and slightly improve fallback handling

### LINKED ISSUE #34492: ⍰ symbol in weapon names and on UI.
For some reason, I've noticed a ⍰ symbol appear in-game. I first noticed it when I found a S&W 610 on the ground. It read as "⍰S&W 610" - However, guns spawned in using debug mode appear normal. The ⍰ symbol isn't appearing in the name of _every_ gun, but I managed to find a few after I teleported to several gunstores. The ⍰ symbol also appears next to "Calm" on the UI. I reinstalled the game and ensured my graphics drivers were updated, but the problem persists.

If I'm the only one with this issue, I'll assume that it's on my end and reinstall my OS.

Screenshot (139)
Screenshot (140)
Screenshot (141)

OS: Windows 10 Professional
Game Version: 0.D-8222-g9213915
Graphics Version: Tiles
Mods loaded: No Flaming Weapons, No Survivor Armor, Disable NPC Needs

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
SUMMARY: Interface "Return the default font to Terminus and slightly improve fallback handling."

#### Purpose of change
Fixes #34492

Terminus is simply prettier than unifont and many were sad to see it go in #19965. Luckily @Qrox recently added fallback support for fonts and effectively negated the issues leading to the switch to unifont.

In addition to that, we currently don't have a square map and overmap font by default, perhaps because of how ugly unifont looks at 16x16.

#### Describe the solution
* Make Terminus the default font
* Prevent users from shooting themselves in the foot by *always* loading unifont as a fallback even if it is not specified
* Make the default (over)map font square

#### Testing
Loading fonts in various configurations and checking the description of the language option to see if fallback worked.

### CODE REVIEW

**Comment by Muffindrake** [comment]
The gentoo wiki denounces GNU Unifont as 'ugly as sin'. I can't believe that choice was made, it should only be dead last in a fallback list, but I'm not invested because I don't play Tiles.

Besides that, I'd have a recommendation in terms of default fonts. https://github.com/pcaro90/hermit

**Comment by esotericist** [comment]
> The gentoo wiki denounces GNU Unifont as 'ugly as sin'. I can't believe that choice was made, it should only be dead last in a fallback list, but I'm not invested because I don't play Tiles.
> 
> Besides that, I'd have a recommendation in terms of default fonts. https://github.com/pcaro90/hermit

find us a better single monospace font that covers all of our language support requirements, and we'll be happy to use it as default.

hermit fails that standard.

**Comment by esotericist** [comment]
Fixes #34492

**Comment by Muffindrake** [comment]
Every relevant font renderer has fallback mechanisms for missing fonts, unless I'm wrong on this one. Terminus certainly isn't high up on the list of 'next-gen exciting fonts', so I merely suggested one additional font as an alternative.

**Comment by ifreund** [comment]
@Muffindrake I believe there's been a bit of a misunderstanding.  If you check out #19965 you can see that we only used unifont by default because we lacked a font fallback mechanism, a lack which has just recently been corrected.  Terminus may not be "exciting" but it was the default font of tiles builds of CDDA when I first played and fits the role of a readable default quite well.

**Pull request merged**
