### PR TITLE
Variable Visual View When Aiming Down Sight

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Aiming Down Sight Causes Sight To Focus"

#### Purpose of change
Cataclysm is a non faced game so stuff like thermal and night vision scopes don't work. Also because it is all currently text based our "steadiness" system and picking a best sight by range aren't obvious to most players. I've made is so as you focus in on a target your 360 degree vision begins to fade simulating focusing on aiming at the target. This allows for specific "specialty" scopes in the future and helps with fidelity and clarity what is happening when you aim somewhere.

#### Describe the solution
The player now calculates based on their target tile and steadiness a range of degrees within which they can see around that target. This begins massive as you start to aim but as you focus on the scope and aim at your target this becomes much tighter.

The player always still gets a 15 tile radius which is to simulate other senses and situational awareness.

Best part this just hooks into the currently fairly robust calculations that already take place. No modifications necessary to underlying info (other than having some of it passed up to the avatar/character).

Video making it more obvious what I'm talking about in additional context.

TODO:

- [x] This all needs to be cached it is very expensive
- [x] ~Need to change the overall final focus based on the scope being used (and its FOV)~ gonna move this to a stretch. Currently would require too much messing with actual shooting code.
- [x] Need to add a hot key in shooting menu to drop all steadiness IE "Lower Your Gun" which would give you all your vision back but also mean you need to take the time to aim again.

#### Additional context

https://user-images.githubusercontent.com/4514073/166264533-8a02dcc1-56ea-4813-a8a3-de3657b8b07b.mp4

### CODE REVIEW

**Comment by Shodan14** [comment]
Now if only the view would also move with the aim cursor..

**Comment by bombasticSlacks** [comment]
> Now if only the view would also move with the aim cursor..

This is the easier implementation (and what I had prototype'd first) but it defeats the purpose since moving the aim cursor doesn't cost any time (nor should it).

So "steadying" or shooting is a necessary confirmation of "yes I do want to look this way"

**Comment by Shodan14** [comment]
> > Now if only the view would also move with the aim cursor..
> 
> This is the easier implementation (and what I had prototype'd first) but it defeats the purpose since moving the aim cursor doesn't cost any time (nor should it).
> 
> So "steadying" or shooting is a necessary confirmation of "yes I do want to look this way"

No no, I love this. I just wish there was also (a purely cosmetic) option to move the camera along with your aim reticle.

**Review by dseguin — APPROVED** [review]
Merged (locally) & tested. Works great, super cool stuff!

(The trig math is above me but the rest looks good)

**Comment by bombasticSlacks** [comment]
> (The trig math is above me but the rest looks good)

some time around hour 2 of just kinda feeling it out, I gave up and did all the math out on a piece of paper 😆

**Comment by catdach** [comment]
> > > Now if only the view would also move with the aim cursor..
> > 
> > 
> > This is the easier implementation (and what I had prototype'd first) but it defeats the purpose since moving the aim cursor doesn't cost any time (nor should it).
> > So "steadying" or shooting is a necessary confirmation of "yes I do want to look this way"
> 
> No no, I love this. I just wish there was also (a purely cosmetic) option to move the camera along with your aim reticle.
> 
> At the moment we can either move the aim reticle or the camera, but not both at the same time.

If I understand correctly, you should be able to do that by setting this option to true (under "interface"):
image

**Comment by Shodan14** [comment]
> 

Wow, it does, thanks! I honestly think that should be the default.

**Pull request merged**
