### PR TITLE
Removed unnecessary checks and text that will never be displayed. Less job for translators.

### PR DESCRIPTION
**Pull request by DeadLeaves**
Removed unnecessary checks and text that will never be displayed. Less job for translators.

### CODE REVIEW

**Comment by DeadLeaves** [comment]
No idea how I get rid of the "Merge pull request #2 from CleverRaven/master" I get on all my PRs due to me updating my local fork.

**Comment by narc0tiq** [comment]
Assuming your repository's name for the CleverRaven/Cataclysm-DDA remote is "upstream", You'll probably want to do something like `git checkout master`, `git fetch upstream`, `git reset --hard upstream/master`. This moves your local master to be exactly where the CleverRaven master is, and will discard the merge commit from accepting that pull request from yourself.

Normally, updating one's local repository is a matter of `git checkout master && git pull upstream master` -- no pull request necessary, as it's your own repo (so you naturally have push rights and don't need to ask yourself for it). Updating a branch based on an earlier version of that same master may involve some `git merge master` or `git rebase master` while the branch to update is checked out.

There's much better documentation around [github's help pages](https://help.github.com/) than I'm either willing or able to write in a comment here, but this should get you started.

**Comment by DeadLeaves** [comment]
Thanks, I figured it out thanks to your comment. Should I redo the PR or does it not matter?

**Comment by narc0tiq** [comment]
You can leave it as it is, or force-push to the same branch this PR is fed from; there's practically never a reason to redo a PR, as long as you can get your branch into the state you want it in.

That said, if you do update a PR, it is generally a good idea to make a comment about it, in case someone was about to merge/test it -- they will want the new version, and most of us get emailed on new comments.

**Pull request merged**
