### PR TITLE
Worlds without filthy mod won't show coloring and suffix on filthy items

### LINKED ISSUE #20454: Filthy clothing is colored and named even without filthy mod
When playing without filthy mod, it has no effects and the different color is misleading.
I'd keep the filthiness in the description, but remove the coloring and name when playing without the mod.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20454.

That check was somehow removed after #18233.

### CODE REVIEW

**Comment by kevingranade** [comment]
#20454 is invalid, this is working as intended.

**Comment by DangerNoodle** [comment]
What is your reasoning for this issue being considered invalid?

**Comment by kevingranade** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/20454#issuecomment-284208824

**Comment by DangerNoodle** [comment]
I do not see this as a valid reasoning. If the clothing does not have any gameplay effect without the mod enabled, there is minimal benefit gained in having them display as filthy when there is no consequence for wearing filthy clothing without the mod enabled.

In contrast, there is potential for player confusion caused by players assuming that the cosmetic effect indicates that filthiness behavior is occurring even without the mod enabled.

**Comment by Coolthulhu** [comment]
Seriously?
Misleading players with UI bullshit is a horrible practice.

I'm getting flashback to the time when someone thought that spamming the messagebox with "you are addicted to fungus" was anything but fucking idiotic.

**Comment by DangerNoodle** [comment]
> Misleading players with UI bullshit is a horrible practice.

I fully agree. There is no valid benefit from leaving the current user interface behavior.

**Comment by Zireael07** [comment]
Why was this closed? The UI shouldn't present information that is not pertinent (without the mod the player doesn't care about filthiness)

**Comment by kevingranade** [comment]
Ok I'm convinced I'm in the wrong here, sorry for being stubborn about it.

In particular, closing this with "bla is invalid" was rude, my intent was, "discussion should happen over there", but obviously my carelss and abrupt wording didn't get that across.

Thanks for everyone her, on the forums and on discord for setting me straight.

**Pull request closed without merging**
