### PR TITLE
remove novitamins from default mod

### PR DESCRIPTION
**Pull request by KorGgenT**
```SUMMARY: none```

So this has been a long time coming: I've been working for 4-5 months on various food projects, and I am quite happy with the state of vitamins as they are now. This means I am proposing removing simplified nutrition from the default mods recommended on world generation.

I also have no summary because i'm hoping that some of the people, who have the misconceptions of vitamins from the bugs from when they were first introduced, will not pay attention and play with it for some time before realizing it wasn't as bad as they thought.

### CODE REVIEW

**Comment by Mecares** [comment]
Are the deficiencies working properly?

**Comment by KorGgenT** [comment]
yes it takes the appropriate amount of time to become deficient

**Comment by KorGgenT** [comment]
jenkins rebuild

**Comment by nexusmrsep** [comment]
Protein/Fat/Carbs system when? *..winks..*

**Comment by KorGgenT** [comment]
jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Looks just right for experimental version.

**Pull request merged**
