### PR TITLE
Add missing monster blacklist options, update and de-obsolete Mundane Zombies mod [separate from original until cleared to merge]

### PR DESCRIPTION
**Pull request by KantoJolto**

### CODE REVIEW

**Comment by kevingranade** [comment]
What's the rationale for adding three new mods for this?
If there's a clear use case of "only mundane zombies", great, but we're not going to mainline an arbitrary list of different blacklist mods for players to pick and choose the exact mix of monsters, if nothing else it's a terrible ui to throw this many options at the player.

**Comment by KantoJolto** [comment]
The logic was that if there are specific blacklists for only acid, only explosive, or only fungal enemies, there should also be specific blacklists for only electric and only brute or hulk zombies. 

Community response indicates electric zombies are a greater point of contention for players than acid. In fact that was the most desired mod out of the three based on Reddit responses.

As for Mundane Zombies being revived, well, I could easily just forego the mod and tweak which zombies have "classic" flag to achieve the same effect. 

Having looked into it, the only non-Romero zombie included in the Classic Zombies option is the shady zombie which I can simply remove the flag of. 
This means Mundane Zombies is entirely redundant as its functionality is entirely covered by something that can simply be toggled on and off and applied to the world with a reset, rather than having to delete the world and remake it without a mod.

**Comment by kevingranade** [comment]
> The logic was that if there are specific blacklists for only acid, only explosive, or only fungal enemies, there should also be specific blacklists for only electric and only brute or hulk zombies.

That does not follow, no.  IMO those were bad ideas in the first place, so adding more is not an improvement.

> Community response indicates electric zombies are a greater point of contention for players than acid. In fact that was the most desired mod out of the three based on Reddit responses.

Ok, if that's your goal, remove the others (except mundane zombies) and add no electric instead.

> Having looked into it, the only non-Romero zombie included in the Classic Zombies option is the shady zombie which I can simply remove the flag of.

This is a historical accident, I added the classic zombies option before mods even existed, and it was recreated as a mod at some point without removing the option.  If anything, it's the option that should be removed instead of the mod, as the mod has lower impact on engine code.

**Comment by Coolthulhu** [comment]
For fungals, the primary reason was that they breed fast and ruin entire cities and CPUs. They aren't hard to remove, but can be very tedious.

There is a mod against explosives because they had a really bad start and were hated for that. Nowadays they are rather limited in spawns so they don't designate entire cities as "no go" zones. I don't think people would miss that blacklist.

**Comment by kevingranade** [comment]
Repeating:
>    Community response indicates electric zombies are a greater point of contention for players than acid. In fact that was the most desired mod out of the three based on Reddit responses.

Ok, if that's your goal, remove the others (except mundane zombies) and add no electric instead.

**Pull request closed without merging**
