### PR TITLE
Milk update

### LINKED ISSUE #33969: It isn't possible to make curdling milk from reconstituted milk.
Curdling milk, a necessary component for making cheese (which, in turn, is a necessary component for a host of other recipes) can't be made from reconstituted milk.

Drying milk leads to powdered milk, which can then be made drinkable 1:1 with clean water as "reconstituted milk". However, even though it is quite possible in reality, reconstituted milk can't be used to make curdling milk and eventually cheese.

This means that once milk has been dried for the sake of preservation, it is far less useful to the player.

1. Grant powdered milk and contained water to player.
2. Craft reconstituted milk.
3. Attempt to craft curdling milk, and note that reconstituted is not among the necessary ingredients.

# Expected behavior

Preserved milk should be just as applicable to cheese making as fresh milk.

True as of version 0.D-9601.

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19 Tara; Release: 19; Codename: tara; 
- Game Version: 0.D-7375-g1fbbe0a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Features "Milk_standard for dairy recipes, and limited raw milk subsitutiton"```

#### Purpose of change
Fixes #33969, re-do of #33991 to cover all milk-using recipes.

#### Describe the solution
Created ``milk_standard`` recipe requirement to include milk, shelf-stable, and reconstituted milk, and changed recipe requirements using milk to this method. Left out evaporated(partial dehydration), condensed milk(partial dehydration + sugar added) and milk powder(water removed).

In addition, added raw milk-compatible ``milk_standard_raw`` recipe requirement to recipes using both milk and a heat source to kill off potential _Coxiella burnetii_ and _Mycobacterium tuberculosis_(death of which is the defined objective of pasteurization), as fire is sufficient for this purpose.

Items with milk as an ingredient had their default calories recalculated, many of which were lower than the ingredients would result in.

#### Describe alternatives you've considered
Adding raw milk as option for curdled cheese. Left out as I am unable to find sources demonstrating _burnetti_(an acidophile) cell death by acidification via vinegar.
#### Additional context
USDA source on making cottage cheese from reconstituted milk: https://naldc.nal.usda.gov/download/CAT87212963/PDF
image
UN Code of Hygenic Practice for Milk and Milk Products:
http://www.fao.org/input/download/standards/10087/CXP_057e.pdf
image

Recommended pasteurization times:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2870484/
image

Credits to @anothersimulacrum for starting work on comprehensive fix.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Comestible tests are failing now and probably need to be updated.

**Comment by LaVeyanFiend** [comment]
> Comestible tests are failing now and probably need to be updated.

I don't get what you mean by this. I thought it was fine given the checkers gave me the 1/236 cases failed error. 😕

**Comment by ZhilkinSerg** [comment]
https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/584677629#L3917-L4005

**Comment by LaVeyanFiend** [comment]
I wonder if changing them from using  ``"LIST"`` in ``"components":`` method to ``"using":`` will make it work 🤔

**Comment by kevingranade** [comment]
Looks like the tests are still flaking out occasionally.

**Pull request merged**
