### PR TITLE
Sawing down of barrels [CR]

### PR DESCRIPTION
**Pull request by mugling**
As discussed in #14629 this PR implements `iuse::saw_barrel` which adds a `barrel_small` mod to an appropriate firearm with the `IRREMOVABLE` flag set.

Marked CR because I'd like sawn-off weapons to have reduced volume and there are a number of ways this could be implemented.

A trivial implementation could duplicate the logic used by `COLLAPSIBLE_STOCK` so that any reduction is proportional to the base volume.

A more complex version could add the `barrel_length` property to guns (possibly defaulting to the above algorithm if unspecified).

A very complex version could specify the `volume`, `recoil` and `dispersion` modifiers for each gun separately? If this route is the most favoured we could consider a generic implementation so that other permanent mods could be implemented, for example ported barrels via the cordless drill, and their modifiers specified for each gun?

In the absence of consensus or objection I'm considering proceeding with the `barrel_length` option.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
A barrel_length parameter would provide the most flexibility.

**Comment by chaosvolt** [comment]
Ah, interesting. This would additionally entail dummying-out some existing sawn-down items.

**Comment by mugling** [comment]
The outcome of sawing down a gun barrel should be reduced `volume` (and therefore easier storage and faster wielding), somewhat reduced `weight` and a marked increase in `dispersion`.

I've added a the `barrel_length` property to the remington 870 so the implementation can be tested.

As @chaosvolt has pointed out some existing items become obsolete (how?) and there is the issue of balancing the various barrel lengths, @Rivet-the-Zombie are you interested in helping with this?

**Comment by chaosvolt** [comment]
> (how?)

Ahem. Sawed-off double barrel, pipe and over shotties, POSSIBLY the sawn-down Saiga (I personally find it questionable that you could cut MUCH off a gas-operated AK-derivative without more extensive modifications), and other similar weapons would obviously become unnecessary if their reason for existence can be made obsolete with this idea.

**Comment by mugling** [comment]
I mean how to remove them from the game without breaking anyone's saves? Anything more sophisticated than removing them from `item_groups.json`?

**Comment by chaosvolt** [comment]
Ah right, sorry.

Removing the recipes for them, and any references to them in item groups, will dummy them out without causing load errors.

**Comment by kevingranade** [comment]
If we ever want to get rid of the old sawn-off items, we can have them blacklisted on load from saves and converted to the new version, then eventually (a year or so) we can remove that override and the old item definition.  As chaosvolt points out, the first step is making it so they don't spawn any more.

**Comment by chaosvolt** [comment]
Ah, didn't know we could blacklist items like that in addition to the normal first step. o.o

**Comment by Rivet-the-Zombie** [comment]
>@Rivet-the-Zombie are you interested in helping with that?

I can go through and add the missing parameter once you're done with this, yeah.

>I personally find it questionable that you could cut MUCH off a gas-operated AK-derivative without more extensive modifications

Make your cut in front of the gas piston intake and you're good. Cut behind it, and you've ruined the gun.

**Comment by kevingranade** [comment]
Two minor issues I'm looking at fixing while I merge:
"You saw down the barrel of your sawn-off Remington 870." You applied the mod before printing the message.
The hacksaw was being consumed in the process since you had the iuse return 1.

**Comment by chaosvolt** [comment]
> Make your cut in front of the gas piston intake and you're good. Cut behind it, and you've ruined the gun.

Hence why this led to me pondering how many inches you'd actually shave off in the process. XP

And wow, that was an impressively fast merge.

**Comment by mugling** [comment]
> And wow, that was an impressively fast merge.

Yes. The prior discussion in #14629 was helpful as we already had a suitable implementation in mind.

**Comment by chaosvolt** [comment]
As I suspected, yes. XP

**Comment by SeanMirrsen** [comment]
Is it possible to return the sawn-off versions to regular-size? Barrels are typically replaceable.

**Comment by chaosvolt** [comment]
I suspect not until/unless we implement replacement parts for custom gunsmithing. Moar barrels. o3o

And now I'm thinking of cartoon rabbits armed with carrots as a possible joke monster.

**Comment by Malkeus** [comment]
Swappable barrels? [Metalstorm weapons](https://www.youtube.com/watch?v=ZFjGbOyd2ek), anyone?

**Comment by chaosvolt** [comment]
That's only swappable in the sense that taking the bloody thing apart and slapping a fresh pre-loaded set on is faster than reloading them all normally. :V

**Comment by SeanMirrsen** [comment]
Metal Storm weapons could be like flintlocks of the modern age. Carry a few with you, unleash a goddamn hurricane of bullets when you need to, spend whole day reloading them all afterwards.

**Comment by chaosvolt** [comment]
Bah. Iz not enuff dakka if yah can't spend da 'ole day bein' shooty! o3o

**Pull request merged**
