### PR TITLE
str_tolower function to work with all locales  (using ICU library)

### PR DESCRIPTION
**Pull request by Xelat84**
Added Unicode support using ICU library (free, opensource).
To install ICU on Ubuntu 14.04 I use command: sudo apt-get install libicu52 libicu-dev
Now case insensitive search can properly work (for example in crafting gui) with any language.

### CODE REVIEW

**Comment by VlasovVitaly** [comment]
risovach ru

Need to be fixed: CMake Code::Block VisualStudio projects.

So, libICU is a great lib. libICU can fix many unicode(all of them) problems. Lot of our unicode code can be replaced or removed.

**Comment by Xelat84** [comment]
Sadly the problem is I'm not so much experienced in CMake and Jenkins, also I don't have VS2015 to fix VS project. So I want to ask people to help with that.

**Comment by VlasovVitaly** [comment]
I can do Cmake on Linux, guess
26 янв. 2016 г. 21:38 пользователь "Xelat84" <notifications@github.com>
написал:

**Comment by Xelat84** [comment]
I will be very appreciated!

**Comment by kevingranade** [comment]
Is std::locale insufficient for our needs?
If so, how much code would we need to write to work around places where std::locale falls short?
Is ICU (and more specifically a recent enough version to work correctly) going to be available on every platform we target? (Currently this is many flavors of linux, several flavors of BSD, several versions of windows, sometimes OSX, at least one version of iOS, and Android)

I'm asking all of this because every addition of a new dependency greatly increases the difficulty contributors have in building and contributing to the project, and almost invariably is going to make us *lose developers*.  If stdc++11 just doesn't support what we need with respect to internationalization, then we'll just have to bite the bullet and do it, but I want to make sure that's the case before committing to adding a dependency on another library.  If on the other hand we'd need to write a few hundred lines of code to get the functionality we need out of the std library, we should do that instead.

That aside, there's a build flag in the Makefile for enabling internationalization support, use it, there's no reason to make the program unbuildable without ICU, which is what the current PR does.

**Comment by Xelat84** [comment]
std::locale didn't work, at least I test it with russian language, and on windows it works, but on ubuntu - didn't. We can replace std::locale code step by step in the near future, no need to change everything simultaneously.
ICU supposed to be used on any platform, but probably we need to check it by our own. Honestly there can be issues with iPhone version, I saw some posts on StackOverflow about that.

I will be very appreciated if you people help me find out will this attempt of implementing unicode support successful or not. Because I have one more idea how to workaround issue with case-insensitive comparison in the game without using ICU.

> That aside, there's a build flag in the Makefile for enabling internationalization support, use it, there's no reason to make the program unbuildable without ICU, which is what the current PR does.

My fault, sorry! I will fix that.

P.S. Sorry my english.

**Comment by mugling** [comment]
stalled?

**Comment by mugling** [comment]
Similar to #15282 closed due to lack of consensus/progress. Could be further discussed in an issue if OP wants to resume work?

**Pull request closed without merging**
