### PR TITLE
[RDY] Add random body part damage to Heli-Crash scenario

### PR DESCRIPTION
**Pull request by macrosblackd**
This adds the ability to apply random damage to the player along with tweaking the helicopter crash scenario to take advantage of this.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
You should probably inline that `randomize_damage` where is it called rather than defining it separately. It isn't properly described, is "weird" (ignores damage parameter when `randomize_damage` is true, which it always is) and is only used in one place. It also lacks the proper checks a damage function used in-game needs.

It would be better to just roll random value (say, from maxhp/3 to maxhp) for each body part and set it. It would also prevent starting wounds killing the character (`randomize_damage` can do it). Pain should not depend on wounds here - random wounds is already a "scummy" condition, doesn't need to be even more so.

Alternatively, you could just break one of the legs at random. This would be predictable (and thus non-scummy) and offer an unique challenge.

**Comment by kevingranade** [comment]
I agree something deterministic would be better, roulette at game start leads heavily to startscumming.
The main options that sound good are either a broken limb or two, or setting HP on some number of body parts to a percentage of max, like 30% or so.
For an extra kick of immediacy you could add a bleeding effect, but not enough to kill the player.

**Comment by Coolthulhu** [comment]
Reminder that this PR still has unfixed errors.

Also, I don't think that heli crash should be a function of `player`. It is only used in one place and most likely won't ever be used anywhere else and the `player` class is quite big already.

It should be defined in game.cpp, but not as a function of game. You can use `apply_damage` if `on_hurt` is private - `apply_damage` calls `on_hurt`.

**Comment by macrosblackd** [comment]
It absolutely should NOT go in game.cpp. that file is even larger than
player.cpp.

**Comment by Coolthulhu** [comment]
Maybe we should have a separate file for start processing.
Regardless, it shouldn't be a player method.

**Comment by BevapDin** [comment]
> Maybe we should have a separate file for start processing.

What about start_location.cpp? It already contains similar code for adding fire.

**Comment by Coolthulhu** [comment]
I thought about start_location.cpp, but as far as I recall it doesn't have the access to player character.

**Comment by kevingranade** [comment]
If nothing else it has access to g->u, or a slightly more elaborate fix would have game invoke a start_location entry point and pass it u and m or something.

**Comment by macrosblackd** [comment]
I'll look at moving it to start_location.

**Pull request merged**
