### PR TITLE
Remove CBM spawns in inappropriate locations

### PR DESCRIPTION
**Pull request by BoatNectar**
#### Summary
Bugfixes "Remove CBMs from inappropriate item groups"

#### Purpose of change

With the source of CBMs being the Exodii, it doesn't make sense for people to be keeping them in the bank.

Steps to reproduce:
1. Go to bank
2. Start opening safes
3. Find alien technology stored amongst wads of cash and jewelry

#### Describe the solution

I removed the CBMs from the following itemgroups: sewage_plant, toxic_dump_equipment, vault, drugdealer, ant_food, spider, and rare.

There are additional spawns for CBMs still located in the following itemgroups and have been left unchanged: bionics, bionics_mil, those related to harvesting CBMs from Zomborgs, cyborg_harvest, and science

#### Describe alternatives you've considered

Come up with some other justification for CBMs to be stored in commercial banks.

#### Testing

Debug teleported to 3 banks and did not find any more CBMs in the safes. Debug spawning related itemgroups yielded no inappropriate spawns either.

### CODE REVIEW

**Comment by BoatNectar** [comment]
I've since tested with the spawn itemgroup debug command and CBMs do not appear.

**Comment by NetSysFire** [comment]
>Come up with some other justification for CBMs to be stored in commercial banks.

Only thing that comes to mind is some rich storing their "artifacts" there, including raided exodii stuff. But since they are all normal banks the normal citizens use, too it might be a bit of a stretch. Plus the exodii arriving might not have happened that early.

**Comment by anothersimulacrum** [comment]
> 

It did not happen that early.

**Comment by BoatNectar** [comment]
> There are also still bionics available at high-end electronics stores. Suggest those get removed next.

I've expanded the scope of this PR to catch more inappropriate spawn locations.

**Comment by anoobindisguise** [comment]
Part of the problem is that the exodii are still incomplete (I think) and the total removal of terrestial bionics was waiting on them being properly introduced as post-cataclysm devices, but if @I-am-Erk or another wants to chime in and clarify that would be great.

**Pull request merged**
