### PR TITLE
iuse actor heal for jsonized healing items

### PR DESCRIPTION
**Pull request by Coolthulhu**
As promised on forums.

Changed actions like bandages, disinfectants etc. from hardcoded `iuse`s to a single `iuse_actor`.
It looks like this:

```
"use_action" : {
    "type" : "heal",
    "limb_power" : 3,
    "head_power" : 1,
    "torso_power" : 4,
    "bleed" : 0.9,
    "move_cost" : 300,
    "effects" : [
        {
            "id": "pkill1",
            "duration": 120
        }
    ]
}
```

Should be pretty self-descriptive.

Allows defining a list of effects (in `consume_drug` effect syntax), a side product item (bloody rag) and making using some items a long action.
There is a test item - chloroform rag (because NPCs show that they are sleeping by having a blue background) that also creates a regular rag on use. Because of curent limitations of this iuse_actor, it needs to be used on a damaged body part.

Long actions are currently hardcoded to divide `move_cost` by (user's skill + 1), because that was happening to first aid kits. They don't work on NPCs yet - instead they will heal the NPC on first turn and then consume all the moves at once.

Diffs look quite huge, but most of that is just CTRL+X+V, because I moved the huge healing helper functions from iuse.cpp to iuse_actor.cpp.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Very nice!

**Comment by chaosvolt** [comment]
Ah, should be interesting to see.

**Comment by chaosvolt** [comment]
Small annoyance I discovered when trying to see what the full capabilities of this use_action, a lack of documentation on what all the effects are what they do. For example, no explanation for how limb_power and all these other numbers actually work. ;w;

**Comment by Coolthulhu** [comment]
Oops, looks like I forgot to include that.
Power is how much it heals given body part (at 0 skill I think), bleed/bite/infected is chance to heal that status.

**Comment by chaosvolt** [comment]
Ah, I see. I'm sorely tempted to change the arcana mod to use this instead of artifact-style healing. Either that, or remove the pain effect as it heals so little (for cost equivalent to 1 essence) that it isn't worth the pain accumulated.

**Pull request merged**
