### PR TITLE
Refactor place_npc_software

### PR DESCRIPTION
**Pull request by Gabriel-SE**
As suggested by @vache

### CODE REVIEW

**Comment by vache** [comment]
A subtle difference that I didn't notice at first was that each code starts stepping through the x,y coordinates at a different place, to make it more likely to stop at the back of the store in each rotation. We might want to prefer this behavior over the cleaner looking code.

**Comment by Gabriel-SE** [comment]
I'll add a function to walk in four directions : North, South, West and East.
If all of them end in wall and there's no furniture, then I'll place the computer there.
That place should be the back of the store.

**Comment by Gabriel-SE** [comment]
Moved the computer back from counter area to back storage area.
Let me know if there's anything wrong.

**Comment by kevingranade** [comment]
There has got to be a simpler way to do this.

**Pull request merged**
