### PR TITLE
additional LMOE bunker [CR]

### PR DESCRIPTION
**Pull request by sparr**
First commit moves the original lmoe_under to json. Upcoming commit will add a second LMOE bunker.

### CODE REVIEW

**Comment by Frost-wood** [comment]
looks good

**Comment by Rivet-the-Zombie** [comment]
Nice!

**Comment by sparr** [comment]
@Frost-wood @Rivet-the-Zombie thanks! I added a second bunker now. I spawned the bunker about a dozen times to make sure everything was spawning right. I'm a little concerned with how the random item groups are distributed, but that's another concern for a broader scope patch I think.

**Comment by KA101** [comment]
Looks nice.

One thing, doesn't have to happen here but would be good to keep in mind for the future: z-level folks are gonna need to align the stairways near or on top of each other, so it'd be good to put upstairs on z-1 near the x/y location of the downstair on z=0 if we know where they're both going to be (which is the case here).

**Comment by sparr** [comment]
@KA101 I was just talking about that with someone on IRC, actually. If we line them up, does that mean we need a new lmoe for each lmoe_under, and some way to match them to each other?

**Comment by KA101** [comment]
Or just move the stairs from the corner of the bunker more towards the middle?

**Comment by KA101** [comment]
To be clear: I'm willing to merge this as-is, so no need to push an update.

**Pull request merged**
