### PR TITLE
monsters with larger eyes see farther

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Balance "Monsters with larger eyes see farther than smaller variants"

#### Purpose of change

Based on feedback that mega mutants should be able to see farther given their size and existing game mechanics to offer a long view at high heights and review of publicly available scientific literature.

#### Describe the solution

Compare vision of standard (zombie or dog sized) monster and mega/hulk variant. Using skeleton hulks as a guide, increase vision_day by 66% for every 2.5x weight increase, capping the increase at 100% or 84, whichever is smaller

#### Describe alternatives you've considered

Larger vision bump

#### Testing

Small JSON edit, passed tests

#### Additional context

Thanks to @SomeDeadGuy for the idea

"I know you've deceived me, now here's a surprise
I know that you have 'cause there's magic in my eyes
I can see for miles and miles and miles and miles and miles" -The Who

### CODE REVIEW

**Comment by Fris0uman** [comment]
Double vision seems excessive. I don't think being tall should offer a bonus o vision range. It orks with the map stuff because seeing over obstacle lets you see more but here it's like climbing on a table suddenly gives you eagle eyes, that's a bit weird.

**Comment by LyleSY** [comment]
Good points, but these aren't just ten times taller, their eyes are also ten times bigger. Vision range doesn't scale 1 for 1 with eye depth, but 10 to 1 is really conservative 
image
https://www.karger.com/Article/FullText/357830

**Comment by LyleSY** [comment]
..except the hulks aren't growing by ten times. Thanks, I'll recalibrate

**Comment by Fris0uman** [comment]
Fair, but your source doesn't cover invertebrates, and since they're eyes works differently I'm not sure it's right for them.

**Comment by LyleSY** [comment]
I've bumped hulk down to match the boost that the skeletal hulk gets. I'm looking for a good source on insect eyes, but everything on the public web is pretty general so far

**Comment by LyleSY** [comment]
I see some references to this (unavailable) paper comparing jumping spiders eyes to cat eyes. As far as I can tell the optics in this example are the same, but I'm not finding anything comprehensive. 
https://www.wired.com/2014/04/spider-vision-made-clear/
https://www.researchgate.net/publication/238671399_'Eight-legged_cats'_and_how_they_see_-_A_review_of_recent_research_on_jumping_spiders_Araneae_Salticidae

**Comment by Fris0uman** [comment]
I guess big lenses might help see further. Can you change the title to show it's about having big eyes more than about being tall?

**Comment by Qrox** [comment]
> this (unavailable) paper

I got the relevant figure for you, and indeed it seems insects vision also scales with body size like that of vertebrates, but the principal eyes of _Portia_ seem to be an exception.

image

**Pull request merged**
