### PR TITLE
Fix shrapnel volume

### LINKED ISSUE #17727: Exploding 40 mm frag grenades spawn tons of "shrapnel" items
I assume it's a bug since each of those is useless, has 1 volume (total volume is much higher than that of the grenade) and there is way too many of them.
Probably some weirdness with chance to spawn, which should be 0 but is treated as `one_in( 0 )`.

### PR DESCRIPTION
**Pull request by mugling**
See also #17727

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Can't we have a proper fix instead of patching that ugly hack?

Something that doesn't create a ton of useless items just to show something that should be shown on the screen directly.

**Comment by mugling** [comment]
It's entirely plausible the player will want to collect nails from a used nail bomb so I don't consider it a hack at all.

**Comment by Coolthulhu** [comment]
Shrapnel from 40mm frag is pure trash.

**Comment by mugling** [comment]
> Shrapnel from 40mm frag is pure trash.

So are cosmetic fields by that token.

> total volume is much higher than that of the grenade

This PR provides a trivial and easy to verify fix to that issue.

**Comment by Coolthulhu** [comment]
> So are cosmetic fields by that token.

They aren't perfect and could use some display fixes. But it's not an excuse to have another mis-feature that only provides more clutter.
Fields have the decency to disappear after a while, don't pollute the menus, don't hide items and don't mark areas as "it has items here, check it out".

Changing the shrapnel items to cosmetic fields isn't such a bad idea, though. It still isn't The Proper Thing (actually displaying shrapnel during explosion), but 3 steps above itemized shrapnel.

**Comment by mugling** [comment]
> actually displaying shrapnel during explosion

I'd like to do this but it's not a simple process and there are worse parts of explosions that need addressing first (for example blast damage).

This fixes the shrapnel volume issue and is a definitive improvement.

**Comment by Coolthulhu** [comment]
> This fixes the shrapnel volume issue and is a definitive improvement.

Yes, but it is a bandaid. It doesn't fix the linked issue, only fixes shrapnel not stacking.

**Comment by mugling** [comment]
> Yes, but it is a bandaid. It doesn't fix the linked issue, only fixes shrapnel not stacking.

You're representing this as stacking fix vs UI rewrite. Given the latter isn't written and is an order of magnitude more complex that's not the decision which is stacking fix vs status quo.

By all means open an issue (or adjust your existing) to set out the design you'd like to implement but that's independent of whether or not this PR improves the situation. The only reason to merge is if you have a competing PR that would make this obsolete.

**Comment by Coolthulhu** [comment]
> The only reason to merge is if you have a competing PR that would make this obsolete.

I'm not saying I won't be merging this, just that it doesn't really close the linked issue.
It fixes shrapnel not stacking, not

> Exploding 40 mm frag grenades spawn tons of "shrapnel" items

**Comment by mugling** [comment]
> It fixes shrapnel not stacking, not

Updated preamble to avoid automatic closing of #17727 which could be extended to include an alternative design. Fields aren't a terrible idea and might actually be preferable to custom UI code (they persist).

**Comment by Coolthulhu** [comment]
Shrapnel is ammo, but doesn't have a corresponding ammo type. This produces a warning on load.

**Comment by mugling** [comment]
Fixed

**Pull request merged**
