### PR TITLE
[Done] Pain descriptions w/o SELFAWARE trait

### LINKED ISSUE #24700: Exact pain number should only be visible by character with "Self aware" trait
Game version:
master
Operating system:
any
Tiles or curses:
any
Mods active:
any
### Expected behavior
Exact pain number should only be visible by character with "Self aware" trait.
Player without this trait should only have a vague description about current pain status.
### Actual behavior
Any player can see his pain in exact number.
### Steps to reproduce the behavior
Start a new game, inflict some pain on yourself.

### PR DESCRIPTION
**Pull request by vircung**
Players without `SELFAWARE` trait won't see exact pain level number. Current considerations:
- pain thresholds are `/ 10.f` floating point operation
- `pain 0` is correctly detected as `No pain`
- ~~`get_perceived_pain` is not yet offset by 1, so 0-9 pain will be considered as `No Pain`~~
- pain description had to be moved a a bit to not to be overwritten 
- pain description are taken from issue [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/24700#issuecomment-411312464) 
- there is no "max pain" level so far, or at least I didn't found it

closes #24700

### CODE REVIEW

**Comment by woutershep** [comment]
I'm pretty sure you don't want the modulo operator but want the division operator.

**Comment by vircung** [comment]
Modulo operator will split `get_perceived_pain` into event 10 point range groups. Reminder is useless at this point and provides no value.

**Comment by vircung** [comment]
Sorry for trying to defend own brain fart. Of course You are right about type of operation. Mea culpa.

For naming scales implementation initially adopted naming convention from related Issue comment [pain scale](https://cdn.paindoctor.com/wp-content/uploads/2017/02/pain-scales.png).
Number of thresholds, value span and it's naming is open for discussion, ideally by more experienced players.

**Comment by vircung** [comment]
Examples of longest description of pain/hunger/thirst/mood area with double digit stats.

zrzut ekranu 2018-09-03 o 16 46 01
zrzut ekranu 2018-09-03 o 16 46 34

**Pull request merged**
