### PR TITLE
[MOD]PRing my LMOE Starting scenario

### PR DESCRIPTION
**Pull request by Hazerithious**
I didn't get the "Angry Pink Text"
The LMOE building seems to be limited to 3-6 city sizes though. Too high or small would cause the building to not be generated.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This does not need to be a mod. Just add it to the normal scenarios.

**Comment by Hazerithious** [comment]
I'm very new to Git, so I'm not sure how I would even be able to change that.

**Comment by Zireael07** [comment]
Push more commits to your branch and voila.

**Comment by Frost-wood** [comment]
(changes)
git commit . 
git push -u origin branch name

**Comment by Frost-wood** [comment]
Oh, I see you are using your master, don't do that in future PRs, because if this doesn't get merged, your master will be contaminated.  Do this instead:

git branch branch-name(in this case you would want it something like lmoe-scenario)
git checkout branch-name
when your are done with your PR update your master with

git pull upstream master
git push -u upstream master

**Comment by Hazerithious** [comment]
Yeah, I have no idea what you're saying. :(
I have a lot of trouble without a video or pictures. No idea why.

**Comment by Rivet-the-Zombie** [comment]
A quick and dirty method for this case only:

1. Take the contents of the file you created called ````scenario.json```` and insert them properly into ````DDAroot\data\json\scenarios\scenarios.json````.
2. Open your Git shell and type ````git commit . ```` and press Enter.
3. Type in ````git push -u upstream master```` and press Enter.

Normally don't want people to PR from their master branch, but in this case it's just easier to go with this. Just remember that next time you should make your changes in a separate branch.

**Pull request closed without merging**
