### PR TITLE
Adds several vehicles

### PR DESCRIPTION
**Pull request by John-Candlebury**
This adds the vehicles below, and changes the city spawns a bit (added the suvs, pickups, and hatchbacks) so that we have some more car variation.

Also added a glock 22 for the Fbi car and a item group for SWAT stuff.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Great work as usual, @John-Candlebury!

**Comment by DavidKeaton** [comment]
woo a van! and an SUV!

**Comment by Zireael07** [comment]
Great!

**Comment by Coolthulhu** [comment]
* No common upgraded solar panels please...
* Electric SUV has 2 gas tanks and a muffler, but no engine that would use either.
* Gas SUVs have powerful engines (V8), yet not much to transport (just 4 trunks). This makes them really fast.
* Superalloy on FBI is treasure on otherwise very unremarkable vehicle. It also doesn't cover the fragile areas like doors or the windshield. Windshield should probably be reinforced. A reinforced (or heavy-duty) door part would also be useful here. I'd drop the superalloy, though. It is very rare in game and making it not-rare should probably be discussed first.

**Comment by John-Candlebury** [comment]
Whoops forgot to remove the tanks from when the electric suv was actually hybrid...

Simply dropped the superalloy from the FBI, that said the car is rather uncommon, so I wouldn't have thought it was a big balance problem

**Comment by Coolthulhu** [comment]
Merged because it's rather minor, but electric SUVs need more batteries. They have a single storage battery and no way to remove it. Compare with electric cars that have 2 and both removable.

**Pull request merged**
