### PR TITLE
Changed weight and volume values of the ferromagnetic rail ammo to be more realistic.

### PR DESCRIPTION
**Pull request by Greevv**
#### Summary

SUMMARY: Balance "Changes the volume and weights of the ferromagnetic rails to be more realistic."

#### Purpose of change

The values for the volume and weights of the rail projectiles were unrealistically high. This is a fix for issue #30750.

#### Describe the solution

Simply tweaked the values in the JSON to better represent the actual volume and weights of a realistically sized projectile for a handheld railgun.

#### Describe alternatives you've considered

None.

#### Additional context

Source for the volume of the projectiles is here. I used dimensions of 6mm in diameter and 76.2mm (3 inches) in length.

cyl

Using a value of roughly 2 cm^3 or 2mL, I calculated the approximate weight of these projectiles using the density of steel given [here.](https://hypertextbook.com/facts/2004/KarenSutherland.shtml)

### CODE REVIEW

**Comment by Inglonias** [comment]
Nothing wrong with the PR itself, but the title was a little scary until I realized you were only adjusting one or two items. The title of the PR implies a much greater scope. Might be worth changing it.

**Comment by Greevv** [comment]
Oops! My bad, bit of an oversight.

**Comment by eilaattwood** [comment]
Wait, 'count' parameter is still there, right? So, specified volume is still for stack of 10? Should be multiplied by 10 then...

**Comment by Greevv** [comment]
I accounted for that in the final numbers. Thanks for the concern though.

**Pull request merged**
