### PR TITLE
more inclusive zombie naming

### PR DESCRIPTION
**Pull request by l29ah**
in lieu of the pending code of conduct

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Fat is fat, so just no.

**Comment by illi-kun** [comment]
First of all, you don't need to update translations that way.

Also, I don't think this is a good change (looks more like a trolling).

**Comment by Voker57** [comment]
I agree, "fat zombies" should be removed instead, since they imply non-standard bodied humans are functionally different.

**Comment by Soyweiser** [comment]
Stop trolling.

**Pull request closed without merging**
