### PR TITLE
Increase the martial arts manuals spawn

### PR DESCRIPTION
**Pull request by Uwuewsky**
#### Summary
Balance "Martial arts manuals spawn in libraries and houses"

#### Purpose of change
For some reason, martial arts manuals are almost impossible to find anywhere, which is odd, they should be present in libraries, bookstores and homes like archery books. Considering that there are quite a lot of fighting styles, it is almost impossible to get exactly the one that will be useful for your build.
In fact, at the moment, books spawn in houses with a probability of... well, consider that they do not spawn at all, 2% in a collection and about 1/1500 probability that this collection will be chosen for spawning. Grep also didn't find anywhere else where these books tried to spawn as a itemgroup.

#### Describe the solution
Create 2 itemgroups with manuals.
Unfortunately I didn't find any exact data, but I think accuracy is unnecessary here, on a small scale. It would be frustrating to find 100 manuals and have like 92 of them be boxing manuals.
`book_martial_common` The first group with common MA manuals. In this group there are manuals on popular martial arts. Which are most often unarmed and therefore ~~absolutely useless~~ very situational.
<details><summary>Boxing, karate, judo, kung fu (as a single style), krav maga, etc.</summary>
<p>

new_common

</p>
</details> 

`book_martial_rare` The second with rarer ones. This group contains either ancient martial arts or more useful weapon arts.
<details><summary>Fencing, ninjutsu, medieval styles, etc. For testing I also included the MMA mod, the vanilla list is smaller.</summary>
<p>

fencing, eskrima, silat, bojutsu, ninjutsu, niten, zui_quan, sojutsu, barbaran, medievalpole, swordsmanship
new_rare

</p>
</details> 

Also, old itemgroups have been replaced with new ones where they were. The homebooks itemgroup was sorted, although only one entry was changed there.

---
Increase the chance of spawning in houses. But you're unlikely to stumble upon it, they are still quite rare.
<details><summary>I ran the group test many times before I noticed the manual.</summary>
<p>

new_homebook

</p>
</details> 
<details><summary>But there is still a possibility, I was able to find one by teleporting around the city.</summary>
<p>

new_house1

</p>
</details> 

---
Dedicate one bookcase in libraries and bookstores to manuals.
<details><summary>Now you can find in a library 1-2 manuals on common arts, and probably one on rare ones.</summary>
<p>

Bookstore:
new_bookstore1
new_bookstore2

Library:
new_library1
new_library2

</p>
</details> 

Now it should be easier to find manuals.

#### Describe alternatives you've considered
Change the probabilities?
(Remove them from dojo and dumpsters so that no one will ever find them.)

#### Testing
Looks okay. I spawned all variations of libraries and bookstores and made sure that books spawn correctly.

#### Additional context
Perhaps it is worth changing the weight of the vandalized libraries, this is literally the only destroyed building in the city. I will also change the incorrect spawns that I found in a separate PR.

### CODE REVIEW

**Comment by Venera3** [comment]
> Considering that there are quite a lot of fighting styles, it is almost impossible to get exactly the one that will be useful for your build.

This is irrelevant. If you *want* a style you start with it, the whole gametime `I know kung-fu` MA learning thing is a bit of a relic that shouldn't inform the rarity of something real.

Gathering any hard data on it is obviously going to run into problems, but you could check something like the print run size of a manual-like book irl.

**Comment by andrewhr** [comment]
> Gathering any hard data on it is obviously going to run into problems, but you could check something like the print run size of a manual-like book irl.

Not sure if that's easier, but I would suggest data around martial art schools. Like, how many karate schools do exist in New England by population? Something like that.

Part of the reasoning is, today martial art manuals are sort of a proxy to learning, as AFAICT ideal state is learning from NPCs. For sure some MA will still be quite rare, soo... 🤷

**Comment by Maddremor** [comment]
> Part of the reasoning is, today martial art manuals are sort of a proxy to learning, as AFAICT ideal state is learning from NPCs. For sure some MA will still be quite rare, soo... 🤷

Then shouldn't we be removing the manuals and add those NPCs instead?

**Comment by DukePaulAtreid3s** [comment]
Is this still ongoing?

**Pull request merged**
