### PR TITLE
JSONize inheritance of flags via crafting

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Infrastructure "JSONize inheritance of flags via crafting"```

#### Purpose of change
Standardize and JSONize inheritance of flags by crafted items from their components.

#### Describe the solution
- Add `craft_inherit`, a bool field for JSON flags which, if true, makes crafted items inherit the flag from any of their components if present. Defaults to false.
- Add `NO_CRAFT_INHERIT`, a flag which, if present, means this item will not inherit flags from components when crafted, even if those flags have `craft_inherit: true`.
- Convert flags whose inheritance was hardcoded to use this new infrastructure, namely `HIDDEN_HALLU`, `HIDDEN_POISON`, and `FILTHY`. 

#### Describe alternatives you've considered
Continuing to hardcode flag inheritance.

#### Testing
Test 1 (tests if inheritance works for flags with `craft_inherit: true`)
1. Temporarily modify `POCKETS` in flags.json to have `craft_inherit: true`.
2. Load into game.
3. Spawn a long patchwork scarf.
4. Craft a blindfold from said scarf.
5. You now have a blindfold with pockets.

Test 2 (tests if `NO_CRAFT_INHERIT` blocks inheritance correctly)
1. Do step 1 from test 1 if you haven't already.
2. Temporarily modify blindfold in json/items/armor.json to have flag `NO_CRAFT_INHERIT`.
3. Do steps 2 through 4 from test 1.
4. Your blindfold has no pockets.

I also tested that items crafted from mushrooms with `HIDDEN_HALLU` or `HIDDEN_POISON` still inherit those flags correctly.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Consider also jsonizing the inheritance of `FIT` flag. It is behaving with the accordance with mechanics you described: `makes crafted items inherit the flag from any of their components if present`.

**Comment by DaviBones** [comment]
> 
> 
> Consider also jsonizing the inheritance of `FIT` flag. It is behaving with the accordance with mechanics you described: `makes crafted items inherit the flag from any of their components if present`.

I did consider that, in fact! As I understand it, the intended behavior of `FIT` is that if **all** components with `VARSIZE` are fitted, the result should also be fitted, **if** it has `VARSIZE` as well. If I made `FIT` inherit via my system and took out the hardcoded handling of it, there would be two problems: 
1. Crafting an item from **any** fitted item would result in a fitted item, **even if** a different component had "poor fit".
2. Crafting an item with a fitted item would always result in a fitted item, **even if** the crafted item didn't have the `VARSIZE` tag.

Number 2 could be accounted for by careful use of the `NO_CRAFT_INHERIT` flag, so if nobody is worried about number 1, I will be happy to do this.

**Comment by Night-Pryanik** [comment]
It's working as follows:
- If at least one component is fit, then the result will be fitted too.
- If at least one component is poor-fit, the result will be poor-fit too.
- If there are both fit and poor-fit components, the result will be poor-fit.

So we need to take `FIT`, `VARSIZE` and `POOR_FIT` flags into account to make the whole inheritance system work properly.

**Comment by DaviBones** [comment]
I suppose I could solve it by implementing 2 new fields for `json_flag` objects:
- `requires` which takes a flag, and cannot be applied unless that flag exists
- `overrides` which also takes a flag, and gives this flag priority over that flag during inheritance, overwriting it if necessary

Is it worth it for just a single use case?

**Comment by Night-Pryanik** [comment]
If it's too much of a hassle, I think it isn't worth it.

**Pull request merged**
