### PR TITLE
Remove down_blanket uncraft recipe

### LINKED ISSUE #34757: Disassembly of a blanket vs down-filled blanket is far too different
# Describe the bug

Time to disassemble blanket is 1 hour. Time to disassemble down-filled blanket is 2 minutes.

# Steps To Reproduce

Attempt to disassemble a blanket and down-filled blanket and observe the time required.

# Expected behavior

Disassembly time should probably be higher for down-filled blanket. Currently it is 30x quicker for a down-filled blanket to be disassembled vs a regular blanket.

# Screenshots

https://i.imgur.com/rFt1p9B.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Zombie Nightvision [Zombie_Nightvision]
]

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: Content "Remove down_blanket uncraft recipe"```

#### Purpose of change
Fixes #34757

#### Describe the solution
Remove down_blanket uncraft recipe

#### Describe alternatives you've considered
Change the uncraft time of the uncraft recipe

#### Testing
image

#### Additional context
N/A

### CODE REVIEW

**Comment by Rail-Runner** [comment]
> Change the uncraft time of the uncraft recipe

This seems like a better solution to me. At some point clothing will have to be disassembled rather than cut up anyway to recover things like fasteners, once they become a component for making clothing.

**Comment by anothersimulacrum** [comment]
The PR body doesn't mention it, but this recipe is redundant - the recipe for the down blanket is already reversible.

**Comment by Rail-Runner** [comment]
> The PR body doesn't mention it, but this recipe is redundant - the recipe for the down blanket is already reversible.

Sure, but cutting up a blanket for rags and whatever would still be much quicker than making one.

**Comment by snipercup** [comment]
I will adjust the deconstruct recipe instead and make one for the cotton blanket as well. The reason for this is the deconstruction time that cannot be set when using reversible:true.

**Pull request closed without merging**
