### PR TITLE
Magiclysm: Minor magic bugfix

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Mods "Magiclysm: summoned monsters don't drop items, and other small fixes"```

See commit messages

### CODE REVIEW

**Comment by KorGgenT** [comment]
well, for some reason the projectile checking PERMEABLE flag isn't actually working as i expected.

**Comment by ZhilkinSerg** [comment]
```
 DEBUG    : ERROR: summon_bear has higher min_range than max_range
 
 FUNCTION : static void spell_type::check_consistency()
 FILE     : src/magic.cpp
 LINE     : 230

 DEBUG    : ERROR: summon_bear has higher min_dot_time than max_dot_time
 
 FUNCTION : static void spell_type::check_consistency()
 FILE     : src/magic.cpp
 LINE     : 238

 DEBUG    : ERROR: seismic_stomp has higher min_damage than max_damage
 
 FUNCTION : static void spell_type::check_consistency()
 FILE     : src/magic.cpp
 LINE     : 226

```

**Comment by KorGgenT** [comment]
i'm going to mark this WIP until i figure out the permeable thing (and fix that debug stuff)

**Comment by KorGgenT** [comment]
i decided to revisit the permeable thing at a later date. this was meant to be a bunch of small fixes, not head scratchers.

**Pull request merged**
