### PR TITLE
Move hunger, regeneration etc. from game to player

### PR DESCRIPTION
**Pull request by Coolthulhu**
Player needs were handled in `game`, but were easy to move to `player`. This allows NPCs to also have needs and more importantly regenerate stamina an pain.

NPC needs are currently disabled because they can't properly handle them (won't eat even with food in inventory, won't do anything else when hungry either). The only need they take care of is sleep and only when following the player.

Fixed a bug with sleeping NPCs being pushable.

Changed the debug NPC menu: allowed selecting the body part to alter HP (not just torso) and added an option to teleport NPCs.

### CODE REVIEW

**Comment by kevingranade** [comment]
Neato, that's a good cleanup.

**Comment by i2amroy** [comment]
Instead of moving them to player.h can we get them at the Character.h level? It provides exactly the same cleanup, but gets us that much closer to being able to split out NPC's from the player class into their own.

**Comment by Coolthulhu** [comment]
`character` class is rather bare and those updates require some fields that it doesn't have (for example, stamina), but I could add a virtual method there. It wouldn't get invoked as anything but `player`, but it could make later changes easier.

**Comment by kevingranade** [comment]
I agree these should live in character eventually, but I don't see a reason to hold this one up based on that.

**Pull request merged**
