### PR TITLE
[Magiclysm] Adds new zombie animals

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
Mods "Magiclysm - Add new zombie animals"

#### Purpose of change
Magiclysm monsters like Owlbears, Trolls, Goblins and Dragons don't seem to get affected by the blob and revive like other animals do.

#### Describe the solution
Add new zombified forms of owlbears, trolls and the yule cat, some of these forms are a bit weaker than their living counterpart, but posses the same abilities.

I've also added a new type of meat, tainted mutated meat, which is a mix of both tainted and mutated meat.

#### Describe alternatives you've considered
Nerfing hard the Zombie Yule Cat upgrade.

#### Testing
Spawned in monsters, their stats and harvest seems to be correct.

#### Additional context

**I'm not good at balance :(**

**Because this PR adds tainted mutant meat directly to the repo, I don't think it can be merged during 0.F string freeze.**

> **Zowlbear**  
> Generally a bit weaker and smaller than a regular owlbear, after two in-game months upgrades into an envolved zombie owlbear.

> **Zowlbear Predator**  
> A much stronger Owlbear, faster, deadlier and heavier with a thick layer of skin and fat to protect against damage, but in the process loses their instinctics as animals ( avoiding traps ) and severely reduced intelligence.

*Stats are compared to an Owlbear*
|                   | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Melee Cut | Dodge  | Armor Bash | Armor Cut | Armor Bullet |Vision Night | Path Max Dist |
| :---:             | :---:     |:---:      | :---:       | :---:      | :---:            | :---:     | :---:  | :---:      | :---:     | :---:        | :---:       | :---:         |
| Owlbear           | 260       | 120       | 6           | 5          | 8                | 8         | 3      | 5          | 2         | 2            | 20          | 25            |
| Zowlbear          | 220 (-40) | 105 (-15) | 4 (-2)      | 4 (-1)     | 6 (-2)           | 6 (-2)    | 1 (-2) | 5          | 2         | 2            | 13 (-7)     | 12 (-13)      |
| Zowlbear Predator | 300 (+40) | 140 (+20) | 6           | 5          | 8                | 10 (+2)   | 4 (+1) | 8 (+3)     | 5 (+3)    | 4 (+2)       | 32 (+12)    | 0 (-25)       |

The Zowlbear Predator gets the smash ability for the price of losing all of its intelligence with pathing and trap avoidance.

> **Undying**
> An undead troll, the blob has greatly amplified its strength and regenerative property, at the cost of a lower speed and dexterity, though it can see slightly better at night, its day vision has been reduced.

|         | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Melee Cut | Dodge  | Armor Bash | Armor Cut | Armor Bullet | Vision Day | Vision Night | Regeneration |
| :---:   | :---:     | :---:     | :---:       | :---:      | :---:            | :---:     | :---:  | :---:      | :---:     | :---:        | :---:      | :---:        | :---:        |
| Troll   | 480       | 110       | 5           | 5          | 7                | 12        | 1      | 0          | 16        | 13           | 40         | 3            | 1            |
| Undying | 520 (+40) | 85 (-25)  | 3 (-2)      | 7 (+2)     | 6 (-1)           | 10 (-2)   | 1      | 2 (+2)     | 18 (+2)   | 14 (+1)      | 27 (-13)   | 6 (+3)       | 4 (+3)       |

> **Zombie Yule Cat**
> A freshly revived corpse of a zombie cat, still trying to adjust to its life after death, it's not much of a threat compared to the regular cat. They quickly upgrade in less than a week to the Death Cat

> **Tod Cat**
> Tod means death in german, at least that is what Google Translator said.  A streamlined hard hitting and fast version of the yule cat, much more used to an undead body, nearly blind during the day, but the apex hunter at night.

*Stats are compared to a Yule Cat*
|                 | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Melee Cut | Dodge  | Armor Bash | Armor Cut | Armor Bullet | Vision Day | Vision Night | Path Max Dist |
| :---:           | :---:     |:---:      | :---:       | :---:      | :---:            | :---:     | :---:  | :---:      | :---:     | :---:        | :---:      | :---:        | :---:         |
| Yule Cat        | 245       | 167       | 6           | 7          | 8                | 5         | 5      | 4          | 1         | 4            | ?          | 12           | 21            |
| Zombie Yule Cat | 215 (-30) | 124 (-43) | 3 (-3)      | 5 (-2)     | 7 (-1)           | 2 (-3)    | 3 (-2) | 4          | 1         | 4            | 30         | 10 (-2)      | 3             |
| Tod Cat         | 280 (+35) | 173 (+6)  | 8 (+2)      | 6 (-1)     | 8                | 14 (+9)   | 7      | 6 (+2)     | 2 (+1)    | 2 (-2)       | 8          | 30 (+18)     | 17 (-4)       |

The Death Cat also learned to leap short distances.

In a future PR I'd like to work on zombie Orcs ( more variety to it), zombie goblins and zombie Black Dragons.

**Let me know if I missed anything, I wrote this all while I was pretty tired**

---

|                 | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Dodge  | Armor Bash | Armor Cut | Armor Bullet | Vision Day | Vision Night |
| :---:           | :---:     |:---:      | :---:       | :---:      | :---:            | :---:  | :---:      | :---:     | :---:        | :---:      | :---:        |
| Goblin Warrior  | 40        | 105       | 4           | 2          | 4                | 5      | 0          | 0         | 0            | 30         | 8            |
| Zoblin Warrior  | 31 (-9)   | 91 (-14)  | 3 (-1)      | 2          | 3 (-1)           | 3 (-2) | 0          | 0         | 0            | 17 (-13)   | 4 (-4)       |

|                 | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Dodge  | Armor Bash | Armor Cut | Armor Bullet | Vision Day | Vision Night |
| :---:           | :---:     |:---:      | :---:       | :---:      | :---:            | :---:  | :---:      | :---:     | :---:        | :---:      | :---:        |
| Goblin Slinger  | 40        | 105       | 2           | 2          | 4                | 5      | 0          | 0         | 0            | 30         | 8            |
| Zoblin Warrior  | 31 (-9)   | 91 (-14)  | 1 (-1)      | 2          | 3 (-1)           | 3 (-2) | 0          | 0         | 0            | 17 (-13)   | 4 (-4)       |

Goblin slingers have less rocks, increased move cost and slighly reduced dexterity, perception and skills on their rock throw ability, but their range has been increased by 2 tiles.

|                   | HP        | Speed     | Melee Skill | Melee Dice | Melee Dice Sides | Melee Cut | Dodge  | Armor Bash | Armor Cut | Armor Bullet | Vision Day | Vision Night |
| :---:             | :---:     |:---:      | :---:       | :---:      | :---:            | :---:     | :---:  | :---:      | :---:     | :---:        | :---:      | :---:        |
| Goblin Chieftain  | 135       | 105       | 4           | 2          | 8                | 4         | 6      | 0          | 0         | 0            | 30         | 8            |
| Zoblin Chieftain  | 127 (-8)  | 95 (-10)  | 3 (-1)      | 2          | 6 (-2)           | 4         | 4 (-2) | 0          | 0         | 0            | 20 (-10)   | 5 (-3)       |

**All Goblins have no bash and cut armor, even though they drop scrap armor.**

### CODE REVIEW

**Comment by Fris0uman** [comment]
Not saying you should do it, but isn't the general rule to have zombieversions be even worse thant the living ones?

**Comment by actual-nh** [comment]
> Not saying you should do it, but isn't the general rule to have zombieversions be even worse thant the living ones?

True in some regards - although usually slower.

**Comment by Saicchi** [comment]
I tried to make them different, given that they are magical beasts. 
The owlbear gets weaker after death and after a long period mutates into a stronger version. 
The troll get to its physically stronger version right out of the gate, but its much slower. 
The body of the yule cat which was hit the hardest but got used to it faster quickly turns into a night hunter. Though I don't expect even a mid-game player to survive an encounter with a upgraded zombie yile cat at night, I'd like to give them some specialized butchering harvest drops that can be used in crafting potions or magical tools, to make killing them seem more worth it.

**Comment by connorpmartin** [comment]
the 32 night vision on the zowlbear predator seems mildly terrifying. Same with the tod cat. 
IDK if it's balanced, since you're presumably not running around lategame in the dark, but notably the only other creatures ik of with those numbers are shady zombies and nightstalkers with 40 each. And both of these creatures are substantially deadlier than a brute.

**Comment by connorpmartin** [comment]
on second thought migo scouts have 25 so maybe it's fine

**Comment by Saicchi** [comment]
I've addied zombified versions of the goblins. Surprisingly they have no armor despite dropping armor.

**Comment by Theawesomeboophis** [comment]
I like the idea of zombie yulecats and more variety for orcs is great, keep up the good work.

**Comment by Theawesomeboophis** [comment]
I like the idea of zombie goblins and yulecats, great job on this, looks great.

**Comment by Maleclypse** [comment]
> I've added zombified versions of the goblins. Surprisingly they have no armor despite dropping armor.
> I'll be working on zombified versions of the Black Dragon next.
> 
> **Again, if any of these values seem too strong or too weak, don't hesitate to make make a suggestion for the new values. You can do so directly from github web**

Are you saying living goblins have no armor but they drop scrap armor?

**Comment by Saicchi** [comment]
> Are you saying living goblins have no armor but they drop scrap armor?

Yes. Here is the entry for goblin warrior in `data/mods/Magiclysm/monsters/goblin.json`
```json
{
    "id": "mon_goblin_warrior",
    "type": "MONSTER",
    "name": { "str": "goblin warrior" },
    "description": "This short humanoid is covered in filth and shouts slurs at you as it brandishes a cudgel.",
    "default_faction": "goblin",
    "bodytype": "human",
    "species": [ "GOBLIN" ],
    "volume": "32 L",
    "weight": "42 kg",
    "hp": 40,
    "speed": 105,
    "material": [ "flesh" ],
    "symbol": "g",
    "color": "brown",
    "aggression": 100,
    "morale": 100,
    "melee_skill": 4,
    "melee_dice": 2,
    "melee_dice_sides": 4,
    "dodge": 5,
    "harvest": "demihuman",
    "vision_day": 30,
    "vision_night": 8,
    "path_settings": { "avoid_traps": true, "avoid_sharp": true },
    "death_drops": {
      "subtype": "collection",
      "items": [
        { "item": "helmet_scrap", "prob": 40 },
        { "item": "legguard_scrap", "prob": 40 },
        { "item": "boots_scrap", "prob": 40 },
        { "item": "armguard_scrap", "prob": 40 },
        { "item": "cuirass_scrap", "prob": 40 },
        { "item": "cudgel", "prob": 95 }
      ]
    },
    "death_function": [ "NORMAL" ],
    "flags": [ "SEES", "HEARS", "WARM", "BASHES", "FILTHY", "PATH_AVOID_DANGER_1" ]
  }
```

**Comment by actual-nh** [comment]
Some tweaks would seem to be needed on goblin armor...

**Comment by KorGgenT** [comment]
it looks like there's an accidental commit of some snippets in vanilla?

**Comment by Maleclypse** [comment]
Are you wanting this to stay in Draft?

**Comment by Saicchi** [comment]
No. I'm not working on it anymore. Anyone is free to salvage this if they want it.

**Pull request closed without merging**
