### PR TITLE
Sort items in wish menu by item name

### LINKED ISSUE #21245: Sorting rules in "wish for an item" debug menu are weird.
They look like a totally disorganized jumble. Why is the L39B-45 even at the top?

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #21245

### CODE REVIEW

**Comment by BrettDong** [comment]
How many items are there in game now? Is the time cost executing n*log(n) ngettext calls tolerable?

**Comment by BorkBorkGoesTheCode** [comment]
@BrettDong there are 3,635 items or more.

**Comment by BrettDong** [comment]
It turned out to be a real problem: there is a 3-second pause every time I open the wish menu. `ngettext` behind `itype::nname` is time consuming.
lag

**Comment by BrettDong** [comment]
I looked at the sorted list. Sorting on Chinese characters here is based on dictionary order of the UTF-8 byte sequence so the list is chaotic: it is neither in phonetic order nor key stroke count order. The order of the items in the list doesn't make any sense.

Using a language-independent component as the key might be better IMO. It avoids the time cost of `ngettext` calls and keeps a consistent item order regardless of the in-game language and even different versions of translations. The translated name for a certain item might change (even frequently) through translation revisions. It might be dizzy for players to search for an item in a newer version if he/she is accustomed to the old location of the item in question.

**Comment by Coolthulhu** [comment]
Performance of wish menu is already terrible.
Any hope of getting some sort of a cache in this PR? Could be per item type (some sort of "canonical name") or for the wish menu itself.

**Comment by BevapDin** [comment]
I changed it to sort by untranslated item name.

**Comment by kevingranade** [comment]
Please, no translation hostile features. If we can't fix this in a language-aware way then leave the status quo.  I'm not at all sure how productive it is to have the list sorted in the first place given its size.

Also, let's back up, what's the actual need here?  If the issue is, "items are hard to find", sorting the list in some particular way is way behind e.g. improved filtering.

**Comment by cainiaowu** [comment]
Is it possible to make the list sorted like crafting menu? And enable advance filter like Q for tool quality etc.

**Comment by kevingranade** [comment]
Not ok with sorting by something that will work in english and be nonsensical in other languages, we either need to cache the translated string and sort on that, or leave it as is.

**Pull request closed without merging**
