### PR TITLE
Adds a new basement type

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
```SUMMARY: Content "You can now find a new basement type."```

#### Purpose of change
I thought a D&D basement would be cool and the basements are currently lacking.

#### Describe the solution
Adds a D&D basement. It has a table with armchairs, and the table has snacks, character sheets, and a D&D handbook item. Some fridges nearby have some snacks in them.

I feel like it has a lot of open space at the moment, so if anyone has suggestions on how to fill that, pitch them my way.

#### Additional context
image

## Small spoiler warning for explorers

Each basement has a 10% chance to spawn an ancient red dragon by the table that glows slightly and has a very convincing description and large difficulty number. This dragon is, in fact, a prop made of paper, and has 1 HP. When you destroy it, it collapses into papers, heavy sticks, copper wires, and an amplifier or two (since it has lights built in!)

### CODE REVIEW

**Comment by Photoloss** [comment]
You seem to have quite a few (un?)linting changes unrelated to your actual content in there.

As for the empty space, maybe some bookshelves and a tv/computer for when the group is not in session?

**Comment by Ilysen** [comment]
I habitually run files through the json linter once I finish working with them; the linting itself is harmless but should still work fine.

Bookshelves or a TV is a nice idea.

**Comment by Ilysen** [comment]
Some experimenting showed me that log walls felt *much* more homely, and since it was implied that the person who made this also went through the trouble of paneling the floors, I also made the walls wooden, and put a desk by the door that can spawn some phones (representing a place where players would put their phones before playing, a practice several people I know do in their games.)

**Comment by Night-Pryanik** [comment]
> I feel like it has a lot of open space at the moment, so if anyone has suggestions on how to fill that, pitch them my way.

You could just shrink the whole basement to a much smaller room.

**Comment by Mecares** [comment]
You could add a chance for candles on the table, a laptop or tablet for the GM, cups or glasses to drink from, permanent markers, caffeine pills, a backpack next to one of the chairs 
>ior a showcase with a fake medieval weapon or armour piece.

**Comment by curstwist** [comment]
could swap a fridge for a sink and call it a wet bar.   I'm liking the wood walls, we do need proper wood paneling (and walls) at some point.  Still vote for a pillow fort unless this is a strictly adult D&D room (still even then, who doens't like a pillow fort :) )

**Comment by Ilysen** [comment]
I'm really liking all the ideas, thanks to yall for all the input. I'll look into some mapping changes sometime soon.

**Comment by Mecares** [comment]
You could also spawn a bunch of cardboard boxes, Soda cans and plastic bags in the trash can to represent pizza, soft drinks and chips that have already fallen to our valiant heroes.

**Comment by int-ua** [comment]
On open space: make the table bigger, 3x6 tiles looks like a comfortable size for D&D

**Comment by Amoebka** [comment]
What's up with that wooden door near the bar area that seemingly doesn't open to anywhere? Is it supposed to be a built in shelf or something?

**Comment by Mecares** [comment]
It is not visible on the screenshot, but there is a small bathroom behind that door, you can see it if you check out the actual changes under "files changed"

**Pull request merged**
