### PR TITLE
[CR] Forbid eating bad comestibles

### PR DESCRIPTION
**Pull request by Rail-Runner**
Transforms bleach, ammonia, concentrated acid, acid water, weak acid water, soy sauce, salt water, salt, cinnamon, black pepper, seasoned salt and Italian seasoning items to ammo items, as they don't do anything useful at all if eaten anyway.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
That was discussed earlier in #15448, and I personally agree with @Rivet-the-Zombie that we shouldn't forbid players to do something unhealthy or stupid.

**Comment by Malkeus** [comment]
I'd like to come in on the side of allowing foolish acts, it's a roguelike
tradition that i see no reason to remove.

**Comment by mugling** [comment]
> Transforms ... items to ammo item

No. They're not `ammo`. Ammo is reloaded into things. Special cases like this have the potential to greatly increase code complexity and in this case for arguably little tangible benefit.

> they don't do anything useful at all if eaten anyway

If this is a distinct property shared by those items consider implementing `INEDIBLE` flag

> we shouldn't forbid players to do something unhealthy or stupid.

A warning could be appropriate as the player selecting the wrong item does occasionally happen

**Comment by Malkeus** [comment]
A warning would be acceptable, that's also part of the tradition.
Seriously, bleach just got bad effects,  don't take away now.

**Comment by NickGrease** [comment]
~~I'd come in on the middle - things that actually have would have an actual affect (good or bad) should be consumable. Things like, as mentioned (soy sauce, salt water, salt, cinnamon, black pepper, seasoned salt and Italian seasoning) that wouldn't *really* have an affect and is more likely a miss select - just forbid.~~

> If this is a distinct property shared by those items consider implementing INEDIBLE flag
> A warning could be appropriate as the player selecting the wrong item does occasionally happen

I like this.

**Comment by mugling** [comment]
@NickGrease it's also trivial to code

**Comment by chaosvolt** [comment]
I'm torn between either simplifying this idea via an inedible flag, or simply adding a prompt before eating things you shouldn't.

Though to be honest? I'd rather there be a prompt like that for raw meat, chunks of fat, and unpurified water. Those are the ones I end up eating via mistype far more often than anything else. Lesson learned: don't keep that stuff in your inventory, a shopping cart is your friend.

Though chugging swamp water because you fumbled at the keyboard is a more annoying mistake than the roguelike staple of "Hey, what's this thing do?" in my opinion.

**Comment by Malkeus** [comment]
Why not both,  an inedible flag that triggers a prompt before eating? It
would be better if it could be marked in the json and not a special case in
the code.

**Comment by mugling** [comment]
> I'd rather there be a prompt like that for raw meat, chunks of fat, and unpurified water.

This is what I had in mind

**Comment by chaosvolt** [comment]
Not sure about both, but yeah. The prompt idea seems the sanest to me. It would still spoil the "herpderp I'm committing science" experience by hinting to players that that might be a bad idea, but it's not going to stop players who just HAVE to see what that does.

**Comment by Mecares** [comment]
How about a minimum intelligence for the warnings?

**Comment by chaosvolt** [comment]
> How about a minimum intelligence for the warnings?

Oh god that would be hilarious.

**Comment by Darkyhard** [comment]
Okay, closing this. I will make a warning show up when trying to eat those items later.

**Comment by Coolthulhu** [comment]
At least filtering them out from the eat menu would be helpful.

**Comment by chaosvolt** [comment]
That might help partially, yeah.

**Comment by mugling** [comment]
> At least filtering them out from the eat menu would be helpful.

Probably the cleanest solution overall

> A warning would be acceptable, that's also part of the tradition.

Indeed a tradition but arguably not a good one

**Comment by chaosvolt** [comment]
Though you can still mistype if they're filtered out of the menu. Whether it'll fix the mistaken devouring of inedible things depends on your normal method of selecting stuff.

Though fairly often I tend to scroll through with the arrow keys half the time, with is the method that would become safer if the filter was added.

**Pull request closed without merging**
