### PR TITLE
[DONE] Simple Camp Bugs

### PR DESCRIPTION
**Pull request by acidia**
Two very simple fixes:
#24424, Opened cans before distributing them around the litter area
#24426, Stopped companions from returning charge 0 seeds to the player after planting

### CODE REVIEW

**Comment by DracoGriffin** [comment]
Jenkins rebuild

**Comment by acidia** [comment]
Quick explanation, fixes #24425.  Item overflow was turned off because when I went through it originally I thought the items would spill out of their stacks as the sorting method was trying to stack them, causing an infinite loop.  Just turned overflow on and tested to verify, spilling out occurs later so we're safe with how it works.  If some logs are missing when you hit shift+V to get a count, look inside the hard building and crates.  With 1200 logs, I was able to account for all of them after sorting but they do spill into every empty tile around your sort point.

**Comment by acidia** [comment]
OK, no more changes.  Last one was just moving "Reset Sort Points" to be immediately available.  A couple of people forgot where they set their food distribution point at and where facing restarting the camp (not that they had gotten far).

**Comment by AMurkin** [comment]
Please write "Fixes #24424, Fixes #24426" to autoclose issues.

**Comment by cainiaowu** [comment]
@acidia, there are still a lot of lines not translated in the query_yn in src/npstalk.cpp and some mission definition in src/mission_companion.cpp . 

Will you fix that too?

**Pull request merged**
