### PR TITLE
Improve handling of hallucinations and pacification

### LINKED ISSUE #12931: Hallucinations can cause acid puddles.
reported on the forum by Dlightfull
"When hitting a hallucination acidic zombie (spiter, corrosive etc.) the acid (which should only be a hallucination too) actually spills and damages items on the ground."

http://smf.cataclysmdda.com/index.php?topic=10745.0

Not confirmed.

Another thing that hallucinations can do is grab you. Encountered this myself.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24288840-hallucinations-can-cause-acid-puddles?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
EDIT:
Closes #12931

EDIT:
Moved most hallucination handling to creature tracker. Effects that care about hallucinations will now need to explicitly request them (`game::critter_at( pos, true )`). This fixes a lot of weird cases like hallus stopping hulk smashed creatures. Will probably cause some bugs, but not as bad ones as it should fix.

Hallucinations can't be hit by ranged weapons for now. Let's just assume they use "dream logic" and the survivor doesn't understand "gun shoots stuff" well enough to make the connection.

Made `player::absorb_hit` ignore 0 damage hits. This has one effect: 0 damage bashing hits will no longer wreck clothing. Hits that became 0 damage due to armor will still keep wrecking clothing, it's just ones that were 0 before `absorb_hit` which no longer will. Such as hits from hallucinations.

Attacked hallucinations will no longer zapback or spew acid.

As for pacification: optimized the handling a tiny bit. Instead of checking `has_status("pacified")` 4 times, it is usually checked once, in `monster::move`. Shouldn't be significantly faster, but I'd say it makes pacification's effect more obvious in the code.

Noticed a possible bug: monsters recharge special attacks at own speed rather than just counting turns. Is it intended for monsters to scale special attack recharge time with own speed? Same for `wandf` variable.

### CODE REVIEW

**Comment by karlnp** [comment]
Very nice. I've been playing a schizophrenic lately & this will be much appreciated.

**Comment by Rivet-the-Zombie** [comment]
>Is it intended for monsters to scale special attack recharge time with own speed?

I don't think it was intentional.

**Comment by BevapDin** [comment]
> it may be better to just have  game::mon_at  not return hallucinations, because player is the only one who ever cares about them.

That's an interesting idea. It would probably require some special code at other places, but hallucinations should be the exception. If the code can handle a hallucination, it should make this explicit.

Places that would need this are: drawing code, examine (list monsters around, list contents of special tile), player attacking monsters, use of the camera item (has a nice special message for hallucinations), other item actions ("Strange, the your mother does not seem to be affected by the fire extinguisher").

**Comment by karlnp** [comment]
Have you noticed if hallucinations rip clothes when attacking?

**Comment by Coolthulhu** [comment]
OK, critter tracker is now responsible for most hallucination-related stuff. Monsters that try to move or spawn on hallucinations will be allowed to do so. This will kill the hallucinations.

**Comment by Rivet-the-Zombie** [comment]
>Monsters that try to move or spawn on hallucinations will be allowed to do so. This will kill the hallucinations.

Those poor hallucinations!

**Comment by i2amroy** [comment]
>Hallucinations can't be hit by ranged weapons for now. Let's just assume they use "dream logic" and the survivor doesn't understand "gun shoots stuff" well enough to make the connection.

Probably the best thing to do with hallucinations v. ranged attacks is just to make it so that the attack always "miss" the target (Maybe with better aimed shots printing a message about how the attack "passed through" the target instead of just the standard "missed" one?). I mean if you try to shoot a hallucination with a gun the bullet's just going to go right through the targeted spot since there's nothing there after all.

Not that that's necessarily a requirement for this, but it should probably be an eventual goal.

**Comment by karlnp** [comment]
There's already code for "passing through" skeletons, so we can adapt it to hallucinations if we introduce a hallucination type or tag or something. I'm not familiar with the modified code, so maybe that's what ->is_hallucination() does, but it should be a simple fix.

**Comment by Cat09** [comment]
it might be nice to have the code be usable for other entities too. hallucinating NPCs could be interesting, as long as they would actually be able to act accordingly, they could start shooting at nothing, drawing more zeds...

**Pull request merged**
