### PR TITLE
More accurate weights (and some volume adjustments) on mammals

### PR DESCRIPTION
**Pull request by alkemann**
#### Summary

```SUMMARY: Balance "Adjusted weights of mammals from the category defaults to averages of real values"```  

#### Purpose of change
When real weight and volumes were introduced they had placeholder values based on the size category, this change is about adjusting those placeholders to much more accurate to real life.

#### Describe the solution
 I have gone through and updated the weights based on looking up the animals online (and in some cases adjusted the volume were I thought it made sense). I couldn't find a good source of volume numbers, so the volumes are mostly set to match 1 ml to 1 g.

#### Describe alternatives you've considered
I considered not making the PR before I had better volumes, but I am not sure I will be able to and I think we are better off with this change that without.

### CODE REVIEW

**Comment by Mecares** [comment]
I would go for a volume based on a density of roughly 1 g/cm3 if you have no information about the volume.

**Comment by alkemann** [comment]
@Mecares volume is in "ml" not "cm3" though. Or is that the same thing?

**Comment by Zireael07** [comment]
1l = 1 m3 IIRC, so I guess they're the same thing?

**Comment by alkemann** [comment]
Updated all the relevant volumes to 1ml = 1g and edited the PR description to reflect this.

**Comment by alkemann** [comment]
Yes 1l to 1 dm3 gives 1ml to 1cm3

**Comment by alkemann** [comment]
@DracoGriffin hey. you should be able to find a link to my source on most of the commits for the different animals. my primary source listed one value so in those cases I used that. in the cases like pig I used wikipedia and they have ranges for both male and female, so I made a judgement call on how to average out those 2 ranges into one value.

For pigs I used https://en.wikipedia.org/wiki/Domestic_pig.

**Comment by DracoGriffin** [comment]
That doesn't quite answer the question, there are a number of pig breeds just as there are a number of dog breeds: https://en.wikipedia.org/wiki/Domestic_pig#Breeds and https://en.wikipedia.org/wiki/Dog#Breeds.

So which breed are you basing your statistics on? Keep in mind, it needs to be a common breed found in New England.

Also yes, I see the sources for weights/heights, but you haven't clarified how you're using the information. So you are averaging the ranges given, as well as with male : female ?

And just to clarify, I haven't asked about cat because that's quite difficult as that's best extrapolated into some various breeds rather than singular.

**Comment by alkemann** [comment]
Hey. Yes I took the two ranges of both male and female and found what I would consider a reasonable single number to represent and average of all. I didn't consider any breed other than the default pig and for dog I used Labrador. Feel free to give me a different value for these and I will update.

**Pull request merged**
