### PR TITLE
Update plating.json

### PR DESCRIPTION
**Pull request by ToxiClay**
#### Summary

SUMMARY: None

#### Purpose of change

This PR addresses several small grammatical changes.

#### Describe the solution

This solution proposes those changes.

#### Describe alternatives you've considered

No alternatives considered.

#### Testing

JSON linting performed; no errors.

#### Additional context

The change to `wired sheet metal` was proposed because, as written, "light" could be misinterpreted to refer to the weight of housing, rather than "light housing" being interpreted as "housing for lights."

### CODE REVIEW

**Comment by actual-nh** [comment]
For some reason, the Travis check is now failing with a doubled space (not after a period) in Aftershock/items/corpses.json.

**Comment by ToxiClay** [comment]
> For some reason, the Travis check is now failing with a doubled space (not after a period) in Aftershock/items/corpses.json.

As a result of _this_ PR? How thoroughly strange.

**Comment by actual-nh** [comment]
Hrm. Ah. I don't think it's this PR. Some others before it are showing the same. It hasn't been noticed, I suspect, because the Appveyor errors are causing people to ignore unsuccessful checks.

**Comment by ToxiClay** [comment]
> Hrm. Ah. I don't think it's this PR. Some others before are showing the same. It looks like ZhilkinSerg did a fix 2 days ago - try force-updating this branch.

Hmm. Can you walk me through how to do that?

**Comment by anothersimulacrum** [comment]
Don't do it, I've kicked Travis.

**Review by mlangsdorf — APPROVED** [review]

**Comment by actual-nh** [comment]
> Don't do it, I've kicked Travis.

Thanks! (How does one do that, BTW?)

**Comment by anothersimulacrum** [comment]
> > Don't do it, I've kicked Travis.
> 
> Thanks! (How does one do that, BTW?)

You need to be part of the CleverRaven organization, but there's a fairly obvious button in the Travis display once you are.

**Pull request merged**
