### PR TITLE
NPC ranged combat general update

### PR DESCRIPTION
**Pull request by Coolthulhu**
Does NOT fix the whole NPC+magazine deal yet, but allows NPCs to actually use weapons without internal magazines (before, they couldn't figure out that magazine charges imply gun charges).
- Let NPCs use reach attacks from spears and from bayonets. Quite strict with conditions, so you can be safe they won't try to stab through your car or through your back.
- Let NPCs aim before taking shots. Currently rather rough, but they can already understand that aiming isn't perfect.
- Added friendly NPC settings to force them to aim before shooting. Default setting is rather liberal, "spray" setting is only useful if the ammo is free, precise settings will make the NPC aim quite a lot, strictly precise will prevent an average NPC from ever using guns (can work with a shotgun)
- Changed the "attack nearby enemies" setting. Now it means "attack enemies near the player", though the NPC will stop to fight anything that manages to catch up with them. Makes it more useful, as now you can set it before a long action and the NPC will protect you rather than watching you get mauled from the other side.
- Added "attack if you don't need to move" setting. Not very useful, but sometimes you need that dude to stay put but not die in the process.

Fun fact: NPCs can throw items (other than molotovs), they just don't do it because it's hardcoded to only use 2 item ids.

### CODE REVIEW

**Comment by chaosvolt** [comment]
> Fun fact: NPCs can throw items (other than molotovs), they just don't do it because it's hardcoded to only use 2 item ids.

I had an NPC chuck a pipebomb at me once, a long time ago. The fact we were right next to each other was no deterrent to him.

I could've sworn there were flags allowing the AI to recognize stuff they can use as explosives. I was tempted to give that flag to the veinreaver in Arcana mod, but on the off chance an NPC obtains one, it might not work out well for them to toss what might be their dedicated melee weapon.

**Comment by Noctifer-de-Mortem** [comment]
One suggestion about npcs. Can you make it so that the player can mod the guns of npcs? I really wan to suppress their firearms to go stealthy.

**Comment by chaosvolt** [comment]
That could be integrated via the "I want you to use this" thing maybe, but then convincing them to give it back or remove it would be annoying.

**Comment by Coolthulhu** [comment]
Later on I want to make them listen to player more, so that you could take their weapons, mod them and give them back. There will probably be no "mod item in NPC's inventory" command, though.

**Comment by chaosvolt** [comment]
Oh god yes, that would be a glorious feature. Or maybe part of a "remember the stuff I'm giving you, and give it back on command if you still trust me" idea, as one of many overly ambitious AI ideas I've mentioned in the past.

**Comment by Coolthulhu** [comment]
That's a bit too much for now. I'd rather just have them refuse to travel with the player unless they want to be total minions.

**Comment by chaosvolt** [comment]
Ah right. I did say overly ambitious, after all. XP

**Comment by kevingranade** [comment]
> Changed the "attack nearby enemies" setting. Now it means "attack enemies near the player", though the NPC will stop to fight anything that manages to catch up with them. Makes it more useful, as now you can set it before a long action and the NPC will protect you rather than watching you get mauled from the other side.

It seems like this could be the union of enemies near the player and near the NPC.

**Comment by kevingranade** [comment]
Nevermind, I think I see the problem, you don't want them wandering away from the player when engaging nearby monsters?

**Comment by Coolthulhu** [comment]
Yeah, that's mostly it. The current (master) version makes them chase stuff (harmless animals), which is why I made it act like "attack without moving OR defend the player".

**Comment by kevingranade** [comment]
Weird, I had two NPCs beating on a debug monster, then they just gave up, now no matter what I do they're just standing there, they attack it like once a minute.  They'll follow me away from it if I move away, they'l walk back next to it if they get in engagement range, but hardly any attacking.

**Comment by Coolthulhu** [comment]
Debug monsters are very low priority, might be rounding errors or something like that. Is the debug monster hostile? What are their decisions in debug mode?

**Comment by kevingranade** [comment]
wow what? I attached a debugger, and good thing, I never would have guessed this.
in npc::choose_monster_target() a player::sees(monster&) is failing because player::pos() is returning { x = 70,  y = 0, z = 0}

**Comment by Coolthulhu** [comment]
Where did that `y = 0` come from?

**Comment by kevingranade** [comment]
ok I'm dumb, I think there were other NPCs lurking at the edge of the map.

**Comment by kevingranade** [comment]
Well it's reproducible at least, if I let them beat on a new debug monster for a little bit, they give up.

**Comment by kevingranade** [comment]
Looks fairly straightforward, they only attack it because it gets a boost from being hostile, once they hit it for a little while it stops being hostile and they lose interest.
I think it boils down to line 736 evaluating to 0
```float priority = mon.type->difficulty * (1.0f + hp_percent) - (scaled_distance - 1);```
mon.type->difficulty == 1
(1.0f + hp_percent) == 1
(scaled_distance - 1) == 1

**Comment by kevingranade** [comment]
What is the purpose of adding the -1 to scaled_distance?

**Comment by Coolthulhu** [comment]
`scaled_distance` is `std::max( 1, distance / speed )`. That -1 makes it go down to 0, so that it doesn't become negative.

**Comment by Coolthulhu** [comment]
Oh, I see it now: `monster_danger` is an `int`, meaning that for `diff == 1`, it goes down to 0 when hp percentage is below 1.0.

**Comment by Coolthulhu** [comment]
I was wondering why does debug monster get non-hostile and now I see it: it's because it's an insect and thus has a fear trigger "HURT".

> they only attack it because it gets a boost from being hostile, once they hit it for a little while it stops being hostile and they lose interest.

Is that a problem? I mean, I'd say it's fine for NPCs to ignore non-hostile targets with difficulty so low it gets rounded to 0. Having them keep their targets wouldn't really be easy, the alternative would be to have them attack everything (including vermin) or everything except a hardcoded selection of monsters.

**Comment by kevingranade** [comment]
Actually yes, it's totally fine now that I know what's happening.
I'm trying to get a NPC to throw some stuff to exercise that part of the
code.

**Comment by Coolthulhu** [comment]
Throwing currently requires them to be scared. Shoggoths seem to trigger that well.

Unfortunately the item selection for throwing is hardcoded right now (by item id).

**Pull request merged**
