### PR TITLE
ACOG addition

### PR DESCRIPTION
**Pull request by zippydaspinhead**
Adds ACOG scope to game, intended as a midrange tier scope between an holo sight and a rifle scope.

Aim stats are the middle of the road between the two existing items, however weight and volume are the same as a rifle scope to add realism and a tradeoff to using this tier of scope.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Consider adding the ACOG sight to the Steyr AUG in json/items/gun/223.json using "default_mods":

**Comment by zippydaspinhead** [comment]
Doesn't sound like a bad idea, is this based on the built in scope on the AUG's real life counterpart?

If so, I believe it also has integrated back-up iron sights, so it may be worth adding offset iron sights as a default mod as well.  This is if the wikipedia entry on the gun is accurate.

**Comment by BorkBorkGoesTheCode** [comment]
>Doesn't sound like a bad idea, is this based on the built in scope on the AUG's real life counterpart?

No. The AUG didn't start with an ACOG sight, but later variants had the ability to mount detachable picatinny-compatible sights. The version ingame most resembles the A2 version, which has a picatinny adaptor.

**Comment by BorkBorkGoesTheCode** [comment]
The first AUG had an integral 1.5x sight.

**Comment by zippydaspinhead** [comment]
Right, I guess what I'm saying is if we add acog and offset irons as default mods, it would change it in game to more closely resemble the original/military version of the rifle.  I guess I'm asking if this is something that we want to do or not?

**Pull request merged**
