### PR TITLE
Psychopath and Pacifist cancel each other

### PR DESCRIPTION
**Pull request by carpevenenum**
It's kinda tricky to experience guilt from killing if you don't experience guilt at all.
Pacifist also cancels predator mutations for the same reason.

### CODE REVIEW

**Comment by Reclusive-reptile** [comment]
The predator mutations should cancel pacifist, the survivor has mutated to the point where they no longer self identify as human and have been overcome by carnivorous instincts.

**Comment by shedya** [comment]
Can you actually mutate into a pacifist though? I thought that change would be redundant. But okay.

**Comment by Reclusive-reptile** [comment]
I don't think you can mutate pacifist, but you might be able to pick predator at char gen in some scenarios. I don't actually remember, haven't played with the lab challenge in a while.

**Comment by shedya** [comment]
Nope, you can't get predator from the chargen.

**Comment by Chezzo** [comment]
It doesn't entirely cancel it out though, does it? I think you still get the slow gain to skill experience, which is a big part of pacifist.

**Comment by shedya** [comment]
But it is implied that you gain the skill slowly because of the guilt, no? Because you can't even think of violence.

**Comment by Soyweiser** [comment]
Doesn't this make it too 'easy' to get rid of the starting trait penalty? I agree thematically.

**Comment by Coolthulhu** [comment]
Nah, sapiovore is otherwise an underpowered version of cannibal/psychopath that takes a crossed threshold in a beast type tree.

**Pull request merged**
