### PR TITLE
Provide default aim speed if unspecified

### PR DESCRIPTION
**Pull request by mugling**
Factored out of #15765 commit 857020a provides absolute (non-relative) defaults where `aim_speed` is unspecified. A few of the very small holdout pistols are reduced to `aim_speed 2` to differentiate them from the larger pistols.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Conflicts with #15880

Also, the skill type hardcode... I'd wait for it till the item variants. Then you could  implement it as variants - base item would be an abstract "pistol" or "rifle" which would set the base aim speed.

**Comment by mugling** [comment]
> Then you could implement it as variants - base item would be an abstract "pistol" or "rifle" which would set the base aim speed.

That could work. `pistol`, `holdout_pistol`, `rifle`, `carbine` etc

**Comment by BevapDin** [comment]
> Conflicts with #15880

I can always rebase that one. In fact, I'd really like to run `git rebase`. You don't need to resolve those conflicts.

**Comment by mugling** [comment]
> I'd wait for it till the item variants

^ this

**Pull request closed without merging**
