### PR TITLE
add 5gal bucket

### PR DESCRIPTION
**Pull request by nornagon**
#### Summary
Content "Added large plastic buckets (20 L)"

#### Purpose of change
[These things](https://www.homedepot.com/p/The-Home-Depot-5-Gallon-Orange-Homer-Bucket-05GLHD2/100087613) are ridiculously common. My specific reason to add them is because the [CDC Yellow Book](https://wwwnc.cdc.gov/travel/yellowbook/2024/preparing/water-disinfection) recommends them as a way to improvise a slow-sand water filter. But they seem generally useful, too.

### CODE REVIEW

**Comment by ashGlaw** [comment]
Good add. Should have been in years ago, but I'm glad you got it now 👍

**Comment by Maleclypse** [comment]
I've kicked the tests as the failure was showing to me as thousands of blank lines.  If it fails again there's likely an error.

**Comment by RanikOrtega** [comment]
I'm surprised 5 gallons were not already present. They are ubiquitous in real life.

**Comment by nornagon** [comment]
> showing to me as thousands of blank lines

weird! i was able to download the log archive and actually find the error, which was that the zoo keeper profession loadout can't hold a 5gal bucket in inventory. i'll put it back to a regular bucket.

**Pull request merged**
