### PR TITLE
Reimplement trading UI

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
Interface "reimplement trading UI"

#### Purpose of change

The trade UI is cumbersome and lacks many features compared to other item UIs
Fixes: https://github.com/CleverRaven/Cataclysm-DDA/issues/42363

#### Describe the solution
Reimplement the trading UI using two instances of `inventory_drop_selector` held together by a thin event queue.

Partially revert https://github.com/CleverRaven/Cataclysm-DDA/pull/51704 since the container issue is now handled differently and directly from the selection UI with the same behaviour as in the drop UI.

#### Describe alternatives you've considered
Using the AIM or parts of it: this approach was rejected twice

#### Testing
Trade with a neutral NPC. Trade with an NPC shopkeeper. Trade with an allied NPC while player items are on the floor. There should not be any surprises either when selecting items or after trading.

Trade for item stacks. Trade for items with charges. Trade for items from the floor and vehicles. Select a lot of items from the floor, then cancel the trade, then trade again for fewer items. This is to ensure that the changes to `npctrade` did not affect functionality.

Insert an unwanted item in a container (ex: `vac_oven_small_full`) and trade away the container. The balance and prices should not include the unwanted item. The unwanted item should spill before the container is traded.

#### Additional context
<details>
<summary>screenshot</summary>

std

</details>
<details>
<summary>screenshot smallest screen</summary>

small

</details>

<details>
<summary>If you're reviewing by commit</summary>

 please note that 
838b2814d0b9a61ff7e51229663d20eada7c6bda `trade_ui: reimplement trading ui`
duplicates some code that's later removed in
e5135ae645a073ff109e016e99701c8d42c0f21c `npctrade: nuke trading_window`
</details>

68fd32b9e47619eb44ebb1ea3293f534cb2a9839 `inventory_ui: add support for fixed window sizes` slightly changed the aspect of `inventory_examiner` (https://github.com/CleverRaven/Cataclysm-DDA/pull/51252), but the layout should be the same

### CODE REVIEW

**Comment by PatrikLundell** [comment]
If it's easy to do, I'd suggest placing worn items at the bottom of the list, since those items are the ones you're least likely to want to trade away.

**Comment by andrei8l** [comment]
That's a good idea, but the sort order is defined in json and I don't think I can do anything about it from this far down in the `inventory_ui` pile. I'll look into it though.

<details>
<summary>incidentally</summary>

sort order is trivial to alter in `advuilist`
</details>

**Comment by ZeroInternalReflection** [comment]
I have not looked at the trade ui side of this, but I did test out the impact on inventory_examiner.  Unfortunately, while your implementation of forcing the window size is a lot tidier than my (admittedly hackish setup) was, it results in things getting a bit cramped in the header and item list of inventory_examiner:
Examiner_Screen

I think the header does need to be full-width, and there needs to be something forcing the first column to use the available space.  I'd recommend changes along these lines:
[inventory_examiner.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/7532444/inventory_examiner.txt)
(If you'd like, I can add the changes line-by-line in a review instead of just the attached patch file, but this seemed simpler)

**Comment by andrei8l** [comment]
The column in `inventory_examiner` getting truncated is almost certainly a bug in `prepare_layout()`. Forcing the width to 1/3 of TERMX is just a hack that works well only on certain screen sizes. This small change seems to fix it but I'm not too interested in investigating atm:
<details>
<summary>patch</summary>

```diff
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index 3f2396b1fc..b945e60ebd 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -1694,7 +1694,7 @@ void inventory_selector::prepare_layout( size_t client_width, size_t client_heig
     // If we have a single column and it occupies more than a half of
     // the available with -> expand it
     auto visible_columns = get_visible_columns();
-    if( visible_columns.size() == 1 && are_columns_centered( client_width ) ) {
+    if( visible_columns.size() == 1 ) {
         visible_columns.front()->set_width( client_width, columns );
     }
 ```
</details>

For the `inventory_examiner` header: I'd rather just remove it since it's not pertinent to the examined container (it's just the default `inventory_selector` header). Neither of these are the focus of this PR so I most likely won't address them unless they become blockers. Sorry!

**Comment by andrei8l** [comment]
Thanks for merging!

**Comment by wapcaplet** [comment]
There are a number of open bugs related to the previous trading UI that may be resolved or obsoleted by this as well. A few I found are #41393, #43239, #45436, #46081, #46873, #46879, and there are surely others. I’ll try to retest a few tomorrow and close them if I can - I’m really looking forward to trying this feature out!

**Comment by ProfoundDarkness** [comment]
If anyone out there is like me and kept tab for 'toggle category selection mode' and thus get confused about how to switch over to sell (your inventory) instead of buy (their inventory, default)...

Check your keybindings ("?") for "Switch lists" and rebind that to something other than tab... or rebind category selection mode (which will probably change the key in other inventory screens).

I've opted to rebind "Switch lists" to numpad plus (nice big target not far from arrow keys).  Don't know if it will bite me in some way later.  I was going to bind it to left arrow but that conflicted with "switch columns" which is also an old hold over I kept.

Also thanks for the new interface!

**Pull request merged**
