### PR TITLE
Revert "Workaround for linking error w/ clang & glibc 2.31+"

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

#### Purpose of change
This removes the workaround to linking error when compiling with LLVM/Clang on a system with glibc version 2.31 or newer (#47099). The linking error only occurs when `-ffast-math` is used, but the flag was removed in 71c718a8e7f8eb60d6ce53555717ea2aa74ab646 in #50390, so this workaround is no longer needed.

#### Describe the solution
Revert #47099.

### CODE REVIEW

**Review by akrieger — APPROVED** [review]
I'm curious if we ever measured how much `-ffast-math` improved performance / removing it dropped performance. `-fno-builtin` probably has some nontrivial cost associated with it also, so maybe it balances out :)

**Comment by kevingranade** [comment]
It basically doesn't matter because we ran into --fast-math actually causing incorrect behavior, it seemed worth doing because it was "free", but I didn't anticipate the kind of failure modes it could trigger.
Hypothetically we could enable some of the sub-options that --fast-math bundles, but I don't anticipate it being meaningful, we mostly just eschew floating point operations.

**Comment by anothersimulacrum** [comment]
IIRC, @jbytheway talked about it causing a slowdown in lighting that https://github.com/CleverRaven/Cataclysm-DDA/pull/44558 would likely be the solution to.

**Comment by kevingranade** [comment]
Yea I need to get back on that, it was really promising.

**Pull request merged**
