### PR TITLE
Hide bandit_camp and bandit_cabin

### PR DESCRIPTION
**Pull request by Gabriel-SE**
Previously, you can search them with the help of /.

### CODE REVIEW

**Comment by KA101** [comment]
If you've seen them, then you probably should be able to find 'em again.  I'mma object to this one as having the character-obfuscation v. name specificity (green F on the map is "bandit cabin") seems the best current fit to letting players who know there's a bandit facility they saw somewhere look for it, without calling it out to players who may have walked by it.

**Comment by Gabriel-SE** [comment]
It's possible to reveal large area of the map with "Download surface area" from one of the lab's computer. Usually after I download the map, I use / and search for bandit cabin / bandit camp and if I find one, I create a custom note with red B so it's visible.

I think players should mark it themselves with their own note when they walk around the forest and see a suspicious house with NPC in it.

**Comment by KA101** [comment]
>they walk around the forest and see a suspicious house with NPC in it

Bias in favor of players with large monitors; that's an Interface Screw.

**Comment by kevingranade** [comment]
It's supposed to be hidden, the intended way to discover it is to get a
mission revealing it.
A good way to have it both ways is to have it display the fake name until
the player spots it, at which point the name and symbol change, but of
course we don't have infrastructure for that.

**Comment by KA101** [comment]
Well, we have the code to change an overmap tile w/o changing the underlying terrain (it's in debug mapgen, IIRC) so the tough part is figuring out when to call it.

**Comment by BevapDin** [comment]
> Well, we have the code to change an overmap tile w/o changing the underlying terrain

That would be visible to all player characters of the world (if there are several).

What about automatically adding a note, just like on vertical movement?

**Comment by kevingranade** [comment]
Good point, an auto-note when they're spotted is going to do what we want,
and there aren't enough of them to be bad map clutter.

**Pull request merged**
