### PR TITLE
Create new Magiclysm damage types

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
Content "Create new Magiclysm damage types"

#### Purpose of change
There's a few reasons:
1) Adding a few damage types for magic spells will make it a bit easier to balance additional monsters. It makes it more interesting to have some unique types.
2) No longer using "true" or "pure" damage for magic spells. Force damage spells now do "nether" damage.

#### Describe the solution
Create a number of new damage types in magiclysm:
 - Gravity
This damage type represents gravitational forces and pressure. It's a rare damage type and should be treated as such.
 - Light
This damage type replaces the "holy" concept of the pure damage spells. Generally high damage and resisted commonly.
 - Nether
 This damage type represents raw magic and chaotic forces. Resisted by high level zombies and by nether creatures.
 - Poison
This isn't really a new damage type per se, but it is split from the biological damage type from vanilla because bio damage also includes breathed in things and coughing damage. Technically this is "venom" damage, but in fantasy tropes it's known as poison, and i'm sticking to that because of that.
Robots are generally immune.
 - Psionic
 Not very common in magiclysm as the general theme of magic doesn't include a lot of psionics, but it could absolutely be a damage type that monsters do. Robots are generally immune.
 - Sonic
Sound. This is a rare damage type as it's not resisted by very many monsters.
 - Necrotic
 This is representative of the forces of decay in time. Generally monsters that have regeneration powers are *weak* to this damage type, and monsters that stand the test of time (robots, skeletons) generally resist it, but are not immune. There may be appropriate ageless beings that are immune to necrotic damage.

#### Testing
Checked out the new damage type colors (and workshopped them in discord)
image
image
image
image
image
image
image

#### Additional context
I have some additional melee changes that i decided to pull out of this pr and put into another branch.

### CODE REVIEW

**Comment by KorGgenT** [comment]
so now that i got extend to work - how do i properly suppress the unvisited members issue?

**Comment by Rokharn** [comment]
What's the difference between Gravity magic dmg and the raw force of a hulk smashing a player into a wall? Is that same kind of damage? Well, telekinetic dmg from Mind over Matter as well sounds similar.

**Comment by KorGgenT** [comment]
bashing damage is a physical object coming into contact with you, while gravity damage is not.

**Comment by KorGgenT** [comment]
> Damage from falling from a great height? Still physical object (ground) coming into contact with another object (people or items). But it's surely named as gravity by itself.
no, it's the concept of graivty just being more, suddenly in a way that injures you.
> For telekinetic, it's has it's own resistance at the armor. And there no any object, but a mind, which coming with another object (target).
what? this is for magiclysm, not any other mod

**Comment by Rokharn** [comment]
> what? this is for magiclysm, not any other mod

All other mods using magiclysm kind of damage as well. I do not think this is a good idea to create literally dublicates of dmg kinds, when players surely can play with many mods at same time. I think that it is better to merge similar things together rather than create duplicate entities.

**Comment by RedMisao** [comment]
Suggestion to rename necrotic to entropic, given it's decay and things like robots are susceptible to it too
Although the description for nether sounds similar too ...

**Comment by Standing-Storm** [comment]
Nice! I can already see some new spell ideas I can propose with this.

**Comment by KorGgenT** [comment]
since extend doesn't work out of the box with the resistances class, i decided to have it manually check for the extend object in json when it reads in the monster data. this became a problem however, because it sees me reading one object and throws the items visited error. the current state is that i either need to suppress that error (don't currently know how) or somehow fit resistances into extend (probably better, i probably have an idea but it's just a guess)

if anyone has an idea off the top of their head to expedite it would be quite helpful.

**Comment by KorGgenT** [comment]
i'll note here that spells may need to be rebalanced later, since a bunch of damage types have changed. i'd like to push these first and hear back.

**Pull request merged**
