### PR TITLE
Arrow/bolt overhaul

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Balance "Arrow overhaul"

#### Purpose of change

This audits arrows and is intended to add a few more varieties of them. WIP.

#### Describe the solution

This table is also WIP.

| Done? | Change | Explanation |
|---|---|---|
| :white_check_mark: | Renames `arrow_fire_hardened_fletched` | Highly misleading for a simple sharp twig (crude wooden arrow) |
| :white_large_square:  | Take a look at all the other arrows and bolts | So their properties are not misleading anymore (hooray merge conflicts) |
| :white_large_square: | New arrow: Fletched crude wooden<sup>1</sup> | Basically a crude wooden arrow but with fletching which means higher accuracy |
| :white_large_square: | New arrow: Fire-hardened crude wooden<sup>1</sup> | Basically a crude wooden arrow but a fire hardened tip for a bit more damage but less durability, which is faster to make |
| :white_large_square: | New arrow: Fire-hardened fletched crude wooden<sup>1</sup> | Like the two above, combined |
| :white_large_square: | New arrow: Bone variety<sup>1</sup> | Relatively low durability but better than ones with a wooden tip, fletched varieties included. May deprecate makeshift wooden ones. |
| :white_large_square: | New arrow: Bodkin bone<sup>1, 2</sup> | As above but perhaps with specifically carved arrowheads which also need more skills? |
| :white_large_square: | New arrow variety: Barbed arrowheads | Available to bone and metal arrowheads and need significant skill to create, designed to inflict massive bleeding<sup>3</sup> |

1. Bolts included.
2. Maybe.
3. There are no mechanics to pull projectiles out of wounds ingame, but they would inflict *massive* damage if pulled out.

In general, archery has a lot of potential. I know how to wield and shoot a (modern) bow (with modern arrows) irl so I am aware how powerful a bow can become, only against targets and not living creatures of course. According to my research, arrow wounds do not stop creatures near immediately like gun shots but are basically designed to inflict bleeding.
There are a lot of shapes arrowheads can take, depending on what purpose they serve:

<sup>Paul Hermans, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via [Wikimedia Commons](https://en.wikipedia.org/wiki/File:Cr%C3%A9cy-en-Ponthieu_24-09-2008_12-11-33.JPG)</sup>

I mainly want to add more varieties of arrows (e.g fletching or not, shape of the arrowhead, more materials (probably only bone)) to make it more diverse.
I *might* add bronze arrows, too. But I do not know if this even makes sense since why would you use bronze if iron is much more common and easier to make?

As always, I'd love to hear feedback. I am definitely not sure if I should have `sed`'ed that gfx stuff, too but this is trivial to revert.

#### Describe alternatives you've considered

There has been an arrow overhaul some years ago, but I think the arrows can definitely use some more love. Adding recipes for all the varieties seems tedious but there is, as far as I know and I'd like to be incorrect, no better alternative. There was https://github.com/CleverRaven/Cataclysm-DDA/pull/14324 but it may not be too relevant anymore.

#### Testing

WIP. Loaded an existing world, I got an error about the old item ID which I put in `migration.json` but it appears to went away successfully since it automagically replaced all the occurances.

#### Additional context

WIP

### CODE REVIEW

**Comment by Scorch-Mechanic** [comment]
There's no actual scientific evidence that "fire hardening" improves end result of the point. In fact, "fire hardened" tips are more brittle than the kind that are just carved. However, there is evidence that "fire hardening" to sharpen wood to a point is faster and easier than carving with crude tools, which could be desirable if you want to make something quickly or without good tools.
https://en.wikipedia.org/wiki/Fire_hardening

**Comment by NetSysFire** [comment]
Thanks for pointing that out and enlightening me. I did some research and indeed it causes brittleness but it can be used effectively if you e.g make a whole batch since it will be quicker.
The resulting tip will also be harder so it does cause a bit more damage but the brittleness will make it break faster. I adjusted the description.

**Comment by NetSysFire** [comment]
It appears the intended item string for archery-related projectiles is:

`(arrow|bolt)_material_suffix`

A few things were already using this but I attempt to make every projectile follow that for consistency.

**Comment by NetSysFire** [comment]
There is a bunch of merge conflicts and there will be even more in the future. There is a change I want to propose, the cutting quality overhaul, before the feature freeze which will cause more conflicts, so I will close this for now. But do not worry, I will eventually get to it and most of the work I have done so far was literally just renaming. I might do this step separately.

**Pull request closed without merging**
