### PR TITLE
 C96 Broomhandle Description, 1896 isnt "early" 19th century

### PR DESCRIPTION
**Pull request by ReynTheLord**
#### Summary
None

#### Purpose of change

Changes description from "An early 19th century" to "A late 19th century" because the C96 was made in 1896 which is definitely not early in the 19th century.

#### Describe the solution

Change the description

#### Describe alternatives you've considered

Not nitpick about a single inconsistancy in a description
#### Testing

Let's merge without testing what could go wrong.
#### Additional context

As a note I have no clue how github works so you may notice I changed, then undid the change, to the blunderbus description.

### CODE REVIEW

**Comment by mqrause** [comment]
You might want to change the `Nitpick` in your summary to `Bugfixes` (or replace the entire line with `None`. As in you have to, because this will make the PR Validator fail.

**Comment by ReynTheLord** [comment]
please be aware this is literally my first pr on github. Ever. so don't be surprised if I somehow managed to fuck up something this simple

> You might want to change the `Nitpick` in your summary to `Bugfixes` (or replace the entire line with `None`). As in you have to, because this will make the PR Validator fail.

Did that fix it?

**Comment by mqrause** [comment]
Yeah, that will work once a maintainer approves the tests. (Which only needs to be done because this is your first PR here.)

To offer a little bit of an explanation: the summary line is used to autogenerate changelogs and the first word is the category in which the PR falls. That's restricted to those listed in the PR template. `None` means the change won't show up in the changelog and is usually used for minor things.

**Review by bombasticSlacks — APPROVED** [review]

**Comment by bombasticSlacks** [comment]
Tests need to run as a formality, then I'll merge this, should be a few hours

**Comment by ReynTheLord** [comment]
So I may have had an adventure where I updated the blunderbus description, didnt realize I added it to this pr, and un-merged it. So that was an adventure.

**Pull request merged**
