### PR TITLE
Added Electroreceptors to Challenge-Lab scenario

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary
```SUMMARY: Content "Added Electroreceptors as a starting mutation to the Challenge-Lab scenario"```

#### Purpose of change
This change adds the fish mutation, Electroreceptors, to the pool of starting mutations available for the Challenge-Lab scenario.
#### Describe the solution
With Electroreceptors, the player can sense robots and creatures that have large amount of electricity in their bodies (i.e. Shocker Zombies) through walls but they will receive large amount pain if shocked.

This is extremely useful in the lab challenge due to the large amount robots but anything that can shock you will cause big problems. Overall, the benefit and drawback are balanced in the science lab setting.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
jenkins rebuild

**Comment by Mecares** [comment]
Useful no doubt, but do we allow balancewise to get post threshold mutations at the gamestart?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Useful no doubt, but do we allow balancewise to get post threshold mutations at the gamestart?

Seems reasonable for lab challenge scenario.

**Comment by Ilysen** [comment]
I hate to resurrect this, but I was browsing old PRs and wanted to say that Electroreceptors isn't a PT mutation, just a normal Fish one. So you don't need to worry!

**Pull request merged**
