### PR TITLE
Activate blankets to hike up and expose feet.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Features "Blankets and sheets can be activated to expose feet'"```

#### Purpose of change
Lifting a blanket up so it dosnt wrap around your feet should be possible, so you can run with a blanket wrapped around your other body parts whilst still wearing shoes.
Have turned blankets and sheets into tool_armour like scarves.

#### Describe the solution
Activate a blanket to raise it up, it will no longer cover your feet.
Activate it again to tuck your feet in.

#### Describe alternatives you've considered
Considered adding a -100 morale if you go to bed with your feet poking out the blanket, but decided against it.

#### Additional context
N/A

### CODE REVIEW

**Comment by davidpwbrown** [comment]
The way I imagine it, is if you are hiking up the blanket above your feet, you need to keep it covering your hands to lift it up.
If you want it to not cover your hands or your feet, then you probably need to cut holes in it or pin it somehow, then its not a blanket, its a poncho.

**Comment by KITbutler** [comment]
> The way I imagine it, is if you are hiking up the blanket above your feet, you need to keep it covering your hands to lift it up.

Making the two mutually exclusive might make sense, yes. Still it'd be another copy. Speaking of which, you might be able to use "copy-from" and "looks_like" to cut back on the amount of redundancy.

> If you want it to not cover your hands or your feet, then you probably need to cut holes in it or pin it somehow, then its not a blanket, its a poncho.

I was thinking of extending your hand past the straight edge and then folding the surrounding cloth around your arm, like you would see on a stock "[sheet ghost](https://image1.masterfile.com/getImage/NjQ5LTA2MTY1MjE5ZW4uMDAwMDAwMDA=AEhF4p/649-06165219en_Masterfile.jpg)" but using the same method to free your head.

**Comment by ZhilkinSerg** [comment]
Needs conflict resolution.

**Comment by davidpwbrown** [comment]
was a stupid little thing I did to pass the time anyway, not really worth adding.

**Pull request closed without merging**
