### PR TITLE
More complete fix for toolmod migration error

### PR DESCRIPTION
**Pull request by mugling**
A more complete fix for #18797 that should also repair any savegames that had the nested toolmod problem

### CODE REVIEW

**Comment by mutability** [comment]
Deleting all toolmods on a tool seems hazardous?
I have an alternative PR almost ready that is a bit more conservative here.

**Comment by mugling** [comment]
> Deleting all toolmods on a tool seems hazardous?

Well it only affects items without `TOOLMOD_MIGRATION` so should only occur once?

> I have an alternative PR almost ready that is a bit more conservative here.

Push what you have, it would be interesting to see the approach.

**Comment by mutability** [comment]
Pushed.

I am mostly worried about intermediate saves that have the new toolmod stuff (and so might have e.g. installed mods that are completely non-legacy) but do not have TOOLMOD_MIGRATION set yet.

**Comment by mutability** [comment]
Also note that legacy DOUBLE_REACTOR also sets DOUBLE_AMMO so you need to test for those in the right order.

**Comment by mugling** [comment]
Superseded by  #18807

**Pull request closed without merging**
