### PR TITLE
Update 338lapua.json

### PR DESCRIPTION
**Pull request by masema**
Changed weight from milligrams to grams to make it in line with the rest of the ammo.

NOTE: Please grant permission for repository maintainers to edit your PR.  It is EXTREMELY common for PRs to be held up due to trivial changes being requested and the author being unavailable to make them. -->

#### Summary
Infrastructure: Changed the weight of the .338 lapua ammo to be in grams rather than milligrams

#### Purpose of change

All other ammo has the weight in grams. 

#### Describe the solution

I removed 2 zeros from the end of the number and changed the unit.

#### Describe alternatives you've considered

None

#### Testing

I used debug to spawn in the ammo before and after making the change. Weight was consistent 

#### Additional context

None

### CODE REVIEW

**Comment by Karol1223** [comment]
You are increasing the weight 10x with this. It is not possible to achieve this exact weight in grams with our weight syntax.

**Comment by masema** [comment]
Impossible request. Don't know how it worked on my machine.

**Comment by Hyperseeker** [comment]
You can always go with `16 g 200 mg`. Or even `10 g 6 g 200 mg`, if you're feeling petty. (Don't actually do that, but you could.)

**Comment by Karol1223** [comment]
> You can always go with `16 g 200 mg`. Or even `10 g 6 g 200 mg`, if you're feeling petty. (Don't actually do that, but you could.)

Do you know this syntax actually works that you're saying this? Because I was under the impression this doesn't.

**Comment by masema** [comment]
Even if it did, it would still increase the weight by a factor of 100. The original is 16200mg, which comes out to 1.62 grams, not the 162 that I originally thought it did.

**Comment by Hyperseeker** [comment]
> Do you know this syntax actually works that you're saying this? Because I was under the impression this doesn't.

You were, I'm afraid, under a wrong impression. When I'd been compiling the schema for the game's JSON, I found out that dimensional properties (weight, volume, and length) accept any number of values and add them together. `100 g 200 g` makes the item weigh 300 grams, for example. This works between units (`1 kg 200 g`), in any order (`300 g 1 kg`), and with as many additons of a given unit as you see fit (`100 g 2 kg 200 g 500 mg 300 g`), with or without spaces between the value and the unit (`1kg 2g`).

In other words: yes, I know this for a fact. Here's proof:

In the latest experimental (as if this writing), I've adjusted the weight of a book:

```json
{
    "id": "book_anthology_moataatgb",
    "type": "BOOK",
    "name": {
      "str": "The Museum of All Things Awesome and That Go Boom",
      "str_pl": "copies of The Museum of All Things Awesome and That Go Boom"
    },
    "description": "The Museum of All Things Awesome and That Go Boom is an anthology of science fiction featuring blunt force trauma, explosions, adventure, derring-do, tigers, Martians, zombies, fanged monsters, dinosaurs (alien and domestic), ray guns, rocket ships, and anthropomorphized marshmallows.  Published by Upper Rubber Boot Books.",
    "weight": "300 g 1 kg 2 mg 2 kg 200 g",
    "volume": "408 ml",
    "longest_side": "20 cm",
    "material": [ "paper" ],
    "copy-from": "book_antho_tpl"
  }
```

Here's what it weighs in the game as a result:

2024-08-03 16_07_10-Cataclysm_ Dark Days Ahead - cdda-experimental-2024-08-03-0533 1c140ab

This is true for the latest experimental and the latest 0.H RC.

> Even if it did, it would still increase the weight by a factor of 100. The original is 16200mg, which comes out to 1.62 grams, not the 162 that I originally thought it did.

16200 mg = 16.2 g, [according to Wolfram|Alpha](https://www.wolframalpha.com/input/?i=16200+mg+in+g).

You can tell in your head because "milli-" comes from "mille", meaning "thousand", and is a prefix for "one thousandth". 16 thousand and 200 units with the prefix "milli-" should, then, yield 16 of the next metric unit.

Even if that weren't true, syntax could be easily adjusted to accomodate a new combination of units.

**Pull request closed without merging**
