### PR TITLE
(Fix for tests) Assign valid IDs to NPCs used during testing

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
None

#### Purpose of change
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8139343413/job/22242297663?pr=72106#step:17:78 looks like this was broken by the morale test I added in #72018

#### Describe the solution
Change error reporting so we can figure out what mission this is even supposed to be. The integer id is not useful

~~(After we figure it out) fix the actual cause~~ --> Assign all NPCs, even test NPCs, valid IDs. Then when the test NPC dies and its ID is checked for various things (like failing missions), no unintended interactions happen.

#### Testing
Wait to see if `GCC 9, Curses, LTO ` builds and tests pass on it

#### Additional context
While this resolves a bug with `standard_npc` which prevents the error from occurring, it does not actually address the root cause of the error. The actual error is `(~[slow] ~[.],starting_items)=> (continued from above) ERROR : src/avatar.cpp:369 [void avatar::on_mission_finished(mission&)] completed mission MISSION_CAMP_LEADERSHIP_CHANGE was not in the active_missions list`. But the mission should be in the active_missions list. Still, the primary purpose here is to make sure the tests pass, and if we can do that by fixing a bug with test data (standard_npc is used only for tests) then that shall suffice.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
image

image

So not only did the test I add cause this, it's a mission I added that's throwing the error. Just blame me!

**Comment by PatrikLundell** [comment]
A question/suggestion: Wouldn't draft ensure the PR doesn't get merged prematurely? Is there something about draft mode that causes some important tests not to be performed?

**Comment by GuardianDll** [comment]
iirc draft prs do not run all the tests

**Comment by RenechCDDA** [comment]
Specifically I don't know off-hand which tests the drafts do not run, so just to be sure it's not in draft.

Yes I suppose I could check, but slapping a big warning label on it is something I *know* works, so eh. Keep it simple.

**Comment by RenechCDDA** [comment]
Assuming the current commit ([Assign test NPCs valid IDs](https://github.com/CleverRaven/Cataclysm-DDA/pull/72167/commits/3fd4157bb9466673e87b14724c1aa51342c0668d)) makes it through GCC9 it should be good.

**Comment by Maleclypse** [comment]
Kicked failed tests in attempt to get to GC9 Ubuntu

**Comment by RenechCDDA** [comment]
Ahhhhh the accidental ambiguity, I meant `GCC 9, Curses, LTO `, not `GCC 9, Ubuntu, Tiles, Sound`.

**Comment by mqrause** [comment]
> Specifically I don't know off-hand which tests the drafts do not run, so just to be sure it's not in draft.

Draft skips all the build matrix except basic build, so it would have been the wrong choice here.

**Pull request merged**
