### PR TITLE
Improve consistency and readability of the nested items names

### PR DESCRIPTION
**Pull request by Aivean**
#### Summary

SUMMARY: Interface "Improve consistency and readability of the nested items names"

#### Purpose of change

Currently, when there is only a single item stack inside the parent container, the order of the names is inverted which usually leads to the very confusing names:
image

I see several issues here:
1. the innermost item name is displayed first, which leads user to believe that they are interacting with that innermost item, but in reality the `e`xamine menu corresponds to the outermost container
2. when such inverted items are displayed in the "Worn" list, they are not consistent with other (empty) clothes/armor. Is the character above wearing a fruit juice?
3. parentheses are used for both flags and item names. Is `(purse)` a flag or an item name?

#### Describe the solution

Use the consistent "{parent} with {child}" syntax, which is consistent with current multi-stack scenario. 

Before the change:
* several child stacks:   "parent with 2 items"
* single child stack:  "child (parent)"

After the change:
* several child stacks:   "parent with 2 items"
* single child stack:  "parent with child"

Some of the examples:
* hiking backpack with rock
* hiking backpack with rocks
* hiking backpack with purse with 2 items

Also, the displayed nested items hierarchy was not limited before, currently it's limited to three levels, full name is displayed for the first two levels (parent container and immediate child), and third nesting level is always displayed in the short form of "N items".

#### Describe alternatives you've considered

Use the inverted "child in parent" form for the item in their "default containers". See `"container"` for `"type": "COMESTIBLE",` in json. However, I decided against it, because I think such inversion is a bad idea in general and should be avoided. Specifically, it still violates "issue №1 above".

#### Testing

I added unit test to cover the affected cases.
Also I playtested multiple combinations of items in game (see screenshots):
* containers
* tools
* comestibles
* liquid

#### Additional context

Note: "before" and "after" here doesn't have exact one-to-one correspondence in terms of the inventory content, I just want to illustrate general picture of how inventory looks like.

### Before:
image
image
image

---

###  After:
image
image
image
image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Maybe use hyphen or colon instead of "with"? Like
`purse: medium tin can`
or
`purse - medium tin can`

**Comment by Aivean** [comment]
> Maybe use hyphen or colon instead of "with"? Like
> `purse: medium tin can`
> or
> `purse - medium tin can`

The idea to use a symbol instead of "with" has merit, but I'm not sure about the suggested variants.

I think something that can emphasized parent → child relation is a better choice. 

It try several variants:
* arrow: →
* backslash:  \
* angle bracket: 〉
* greater than: > 
* right angle/box drawing: └

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
image

**Comment by Aivean** [comment]
I'm leaning towards the `>` variant. Feels "right". Also I just realized that it's consistent with the symbol that is used to show parent/child relations when you highlight an item.

**Comment by Aivean** [comment]
Ok, I switched to using ">" symbol. Here are some screenshots of how it looks currently:
image
image
image
image

**Pull request merged**
