### PR TITLE
Change shark_suit[_faraday] Materials

### LINKED ISSUE #63604: Sharksuit and Faraday Sharksuit are fully rigid
### Describe the bug

The Sharksuit and it's Faraday version are both considered to be fully Rigid items on all locations. In comparison, all other chainmail armors are fully non-rigid, with the exception of the Faraday Chainmail Suit, which incorporates rubber boots and therefore has Rigid feet and lower legs.

### Attach save file

N/A

### Steps to reproduce

Check sharksuit item description, and compare with other similar chainmail armors.

### Expected behavior

The sharksuit should be nonrigid like other chainmail items, with the possible exception of the head and the feet, as the item description mentions it including a plastic helmet and booties.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1105 (22H2)
- Game Version: 200e84d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SJonesy**
#### Summary
Bugfixes "Changed shark_suit and shark_suit_faraday materials to plastic for the head/feet and lc_steel_chain in other slots. Also updated their weights to 18lbs."

#### Purpose of change
Fixes #63604

#### Testing
Viewed the new suits in the "Spawn Item" menu and verified that they are no longer fully rigid.

#### Additional context
Plastic encumbrance and thickness match "cleansuit". I verified the 18lb weight with a quick search for a modern, steel-chain anti-shark suit.

### CODE REVIEW

**Comment by SJonesy** [comment]
First PR, figuring out the work flow. Let me know if I should do things differently.

**Comment by anoobindisguise** [comment]
Should it not be HC steel or tempered steel? I can't imagine in modern times such armor would be made deluberately of shoddy steel.

**Comment by SJonesy** [comment]
> Should it not be HC steel or tempered steel? I can't imagine in modern times such armor would be made deluberately of shoddy steel.

I'm definitely not an expert here. I searched and saw this:
> To recap, steel is often categorized according to its carbon content. Low-carbon steel consists of less than 0.30% carbon. Medium-carbon steel consists of 0.30% to 0.60% carbon. And high-carbon steel contains more than 0.60% carbon. As the carbon content of steel increases, it becomes stronger and harder. At the same time, it also becomes less ductile.
And then I had to lookup ductile..
> ductile: (of a metal) able to be drawn out into a thin wire.
Which implied to me that fine mesh, light chain like in a scuba suit would be low-carbon. 

If someone knows more than me I'm happy to change it.

**Comment by Boonlike** [comment]
> > Should it not be HC steel or tempered steel? I can't imagine in modern times such armor would be made deluberately of shoddy steel.
> 
> I'm definitely not an expert here. I searched and saw this:
> 
> > To recap, steel is often categorized according to its carbon content. Low-carbon steel consists of less than 0.30% carbon. Medium-carbon steel consists of 0.30% to 0.60% carbon. And high-carbon steel contains more than 0.60% carbon. As the carbon content of steel increases, it becomes stronger and harder. At the same time, it also becomes less ductile.
> 
> And then I had to lookup ductile..
> 
> > ductile: (of a metal) able to be drawn out into a thin wire.
> 
> Which implied to me that fine mesh, light chain like in a scuba suit would be low-carbon. If someone knows more than me I'm happy to change it.

Modern chainmail is made from stainless steel which is a low carbon steel. It gets its strength and corrosion resistance qualities largely from chromium and sometimes other alloying materials. Makes sense as you wouldn't want your shark suit to rust. That being said, we don't have stainless steel in the game, we also don't have material oxidation so it's not really needed. In the interim, I'd suggest picking a high quality steel that we do have that gives the protective properties that seem appropriate.

**Pull request merged**
