### PR TITLE
Change default ImGui font to terminus to fix text position issues

### LINKED ISSUE #77297: Incorrect text position in menu [ImGUI]
### Describe the bug

I open item description and text trying to hide for me.
I try to make fully clean game without old saves and config files and have same situation.

### Attach save file

N/A

### Steps to reproduce

1) Start the game
2) Open inventory (i)
3) (e) Open item description 

### Expected behavior

Can read and text not trying to escape :)

### Screenshots

info 1
info 2
info 3
info 4

### Versions and configuration

Windows 10 24H2
cdda-experemental-2024-10-24-1253 2d90bfe 
English, Russian
Default mod configuration

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary
Bugfixes "Change default ImGui font to terminus to fix text position issues"

#### Purpose of change

Temporarily fix #77297 and #77402

#### Describe the solution

Change default imGui font to terminus, the default font for other UI. 

#### Testing

NOT TESTED

I can't seem to compile on this PC. 

I don't see how this one-line change could fail, but someone should probably test this just in case.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Another font shuffling? But why? I think we'd rather fix the issues themselves.

**Comment by ampersand55** [comment]
That would indeed be better. As mentioned this is temporary fix to a high-priority issue, not a replacement for a fix to the issue itself.

**Comment by NetSysFire** [comment]
I am in favor of reverting the font change to Helvetica as it indeed causes nasty issues. The new font actually looks quite good and readable but this is not worth the issues imo.

**Comment by ampersand55** [comment]
I assume you mean terminus?

I agree that Roboto looks better. We could use Roboto Mono, which is basically a monospaced version of Roboto Regular that's also free using the same Apache 2.0 licence. 

https://fonts.google.com/specimen/Roboto+Mono

**Comment by NetSysFire** [comment]
We changed from Terminus to Helvetica, the non-monospaced font that is causing issues right now, which you seek to revert so we are back at Terminus.

**Comment by ampersand55** [comment]
> We changed from Terminus to Helvetica, the non-monospaced font that is causing issues right now, which you seek to revert so we are back at Terminus.

What do you mean? The current default gui monospaced font is Roboto-Medium.

https://github.com/CleverRaven/Cataclysm-DDA/blob/0d9cbd17b6948bd7d7ba48873a24bf885e48de8e/data/fontdata.json#L8-L9

Here's a comparison between Roboto mono and Terminus using the ImGui menu:

Roboto mono:

image

Terminus:

image

**Comment by NetSysFire** [comment]
Nevermind then, I did apparantly mean Roboto. Someone of the team said something about Helvetica and I believed that without checking.

**Comment by db48x** [comment]
I would prefer to get #76513 committed.

**Comment by ampersand55** [comment]
> I would prefer to get #76513 committed.

Me too, this was only meant as a temporary fix. I'm closing this.

**Pull request closed without merging**
