### PR TITLE
Altered food recipe unit test to catch more recipes, and fixed them

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Bugfixes "Altered food recipe unit test to catch more recipes, and fixed them"```

#### Purpose of change
The comestible recipe permutation test is intended to make sure that the calories of recipes' results are at least somewhat in line with the total calories of their ingredients.

While working on another PR I noticed that this test was passing recipes no-questions-asked, **_if_** all possible ingredient combinations had identical total calories. In my case, adding a way of making the recipe with 748 calories when all the other ways totaled 750 made the test suddenly throw a fit that 750 >> 174. This was unintended behavior, so I fixed it.

While fixing it, I also discovered that byproducts charges were not being taken into account after the first, so I fixed that too.

After the above two fixes, naturally, a heap of recipes were suddenly failing. So I bashed my head against them until the test ran with no failures.

#### Describe the solution
The code changes were rather small and straightforward; if I made a mistake, it's likely in the JSON edits, so I'll list those here:
- Note that in practice, calories are inherited anyway so most of these changes will have no effect on kcal economy (there are exceptions, i.e. popcorn changes). Rather, most of these changes will result in player-crafted items matching their spawned version more closely, or not magically expanding/contracting by a factor of two upon crafting (i.e. dehydrated foods).
- Things I had absolutely no idea/basis for, so I just added `"NUTRIENT_OVERRIDE"` and moved on:
  - Hard cheese
  - Tainted meat
  - Mycus wine must
  - Sourdough bread
  - Kentucky coffee grounds
  - Chitin powder
  - Royal jelly
- Things I changed with little justification besides matching calories between recipe ingredients/results, so am less sure about:
  - Red sauce charges halved (mass doubled to maintain density)
  - Related to above, red sauce:tomato ratio is now more consistently 2:1
  - Tainted tallow calories changed from 52 to 18
  - S'mores changed to match ingredients
  - Maple syrup candies changed to match syrup used to make it
  - Frozen TV dinner changed to match cooked version
  - Lemonade drink mix changed to match new lemonade caloriess
  - Tomatoes' mass and calories increased a bit to more closely match canned tomatoes and red sauce (the awkward ratios were wreaking havoc with the test)
  - Tainted bone meal given 4 calories to match tainted bones
  - Sauerkraut and onions calories changed to match ingredients
  - Decreased flour needed to craft raw fast noodles
  - Hide bag (and tainted version) modified to use 6 hides, with stats to match
  - Candied honey -> forest honey recipe tweaked
  - Forest honey -> candied honey modified to match (though this "recipe" should really just be "keep it at 14°C for a couple days")
  - Cornmeal from corn reduced
  - Some liquor washes' (whiskey, gin, rum, moonshine) calories were increased; calorie values of player-crafted liquor will now match those of spawned liquor
  - Lutefisk calories increased to match fish it's made with
- These were researched and altered to match real world values/recipes, and as such I am rather confident about them:
  - Crafting french fries or potato chips now consumes cooking oil; using the oil as a tool was a interesting idea but isn't viable because something like 2/3 of the calories from fries are from the absorbed oil
  - Powdered milk calories now match milk, ratio of dry:reconstituted is 1:4
  - Red sauce calories per volume halved
  - All varieties of stomachs now have 5 calories per 6 grams, to match real-world tripe
  - Liver calories changed to 92 (from 73)
  - Popcorn kernels and popcorn completely redone
  - Gelato calories reduced a bit
  - Liver and onion recipe and calories were redone to match real recipes
  - Almond milk was given new item "almond pulp" so total calories are the same before and after crafting
  - Removed milk from frozen yogurt recipe
  - Caramel recipe tweaked
  - Honeycomb -> honey changed, wax byproduct removed (only ~2% of honeycomb mass is wax IRL)
- Changes I made that seemed more like bugfixes for oversights/mistakes than design decisions:
  - Maple sap calories were (exactly) 16x too small
  - `"cooks_like": "human_cooked"` added to human flesh, calories of cooked human meat changed to 402 so they more closely match normal meat
  - Large boiled stomach now copies-from small boiled stomach
  - Several mixed drinks' masses and calories were modified to match ingredients
  - Methacola given calories to match the cola it's made with
  - Canned tomatoes' mass and calorie values were half as big as they should've been (probably due to a failure to take into account `"stack_size": 2`)
  - Baked potatoes' calories reduced to match raw potatoes
  - Added `"charges": 1` to a **_lot_** of recipes (especially dehydrated foods) whose author probably missed that the recipe's result had default `charges` value of 2 or more
  - To maintain consistency with above change, all dry:rehydrated food ratios are now 1:1 across the board
  - Donut hole recipe altered to not be completely insane
  - Protein powder and soylent green powder recipes tweaked to be consistent

#### Testing
I have checked all the recipes and items I changed in-game, using the above list.

### CODE REVIEW

**Comment by FrozenSnowFox** [comment]
You might want to take a look at recipes that preserve food with cans/jars.  As mentioned in #32564 canned/jarred items do not inherit their calories/vitamins and instead spawn a preset item.

**Comment by DaviBones** [comment]
Hrm well that would be a code change that's only really tangentially related, so not really for this PR imo. Still, thank you for pointing it out, I may take a look at fixing it in a separate PR.

**Comment by DaviBones** [comment]
Test is failing apparently with -nanf value for some reason, can't reproduce on my machine... Any help/suggestions would be greatly appreciated.

**Comment by KorGgenT** [comment]
ok i have a single note about the bullet points you made in the description: baked potatoes _do_ have more digestible calories than raw. so perhaps nutrient override and cooks like is relevant here.
[quick google link, you can surely find some more](https://www.vitalhealthzone.com/nutrition/nutrition-questions/Anastacia-Sampson1/do-raw-potatoes-have-the-same-calories-and-nutrients-as-cooked-potatoes.html)

**Comment by KorGgenT** [comment]
[here's the spreadsheet i used](https://docs.google.com/spreadsheets/d/1XbImdtYjvlZH_UZBIk0ZmpfiQ48LDXb5Rb-fLOZaD_Y/edit) to keep track of my sources for the calorie and vitamin values for various foods during the rebalance i did

**Comment by DaviBones** [comment]
> 
> 
> ok i have a single note about the bullet points you made in the description: baked potatoes _do_ have more digestible calories than raw. so perhaps nutrient override and cooks like is relevant here.
> [quick google link, you can surely find some more](https://www.vitalhealthzone.com/nutrition/nutrition-questions/Anastacia-Sampson1/do-raw-potatoes-have-the-same-calories-and-nutrients-as-cooked-potatoes.html)

Alright I dived down this rabbit hole for a bit. Here is a summary of what I discovered ([this article](https://www.sciencemag.org/news/2013/02/have-we-been-miscounting-calories) has a more detailed explanation):
- Many cooked foods, not just potatoes, provide more calories.
- The way we measure calories sucks in a lot of ways, including detecting the difference between raw and cooked. This is because we use the Atwater system, which was developed more than a century ago and measures based on fat, protein, and carb totals, with no regard to the fact that some of these provide a lot more energy than others due to being more readily digested by humans. Cooking some foods converts "difficult" carbs to "easy" carbs, meaning more calories in practice, but not on the label.
- Despite the above, it is possible to find online sources list cooked potatoes as having more calories than an equal mass of raw ones. However, this is misleading, as food loses water mass during cooking.
- I was unable to find any studies or otherwise concrete information for the actual numerical difference. The best I could come up with is a guess unfortunately, though the guess was made by Richard Wrangham, who seems like the closest thing to an expert this field of study has:

>My best guess, based on studies of the increased digestibility of starch or eggs eaten cooked compared to raw, is that the increase in net calorie gain from cooking will prove to be in the region of 25­­–50%. That is only a guess, but I am confident it will be much higher than 10%.

(Source: http://blogs.discovermagazine.com/crux/2011/12/08/why-calorie-counts-are-wrong-cooked-food-provides-a-lot-more-energy/)

So, I went somewhere in the middle, implementing a 33% increase which has the added benefit of matching the existing increase from cooked->raw meat. I only changed potatoes for now but can certainly do more if it is deemed relevant. (Note that I subtracted 25% from raw potato, rather than adding 33% to cooked, since the issue is that the Atwood method _over_-counts available calories of raw, rather than that it _under_-counts cooked ones.)

**Comment by Kodiologist** [comment]
Yeah, I too would be skeptical of the rule that the energy of the product must equal the sum of the energies of the ingredients, except when the recipe is just moving stuff around without any cooking or other transformation, like building a sandwich. Cooking was an important innovation for prehistoric humans not just to kill bacteria, but also to make nutrients more bioavailable.

> The way we measure calories sucks in a lot of ways… This is because we use the Atwater system, which was developed more than a century ago and measures based on fat, protein, and carb totals

This is true of the "Calories" line on US Nutrition Facts labels, which uses a standard oversimplified formula, but I believe you can find empirically measured energy density of food, with e.g. a bomb calorimeter, in the Food and Nutrient Database for Dietary Studies (FNDDS).

**Comment by kevingranade** [comment]
I'm a million times in favor of having a "raw" flag for uncooked food items (under the assumption that there are fewer of them than there are cooked food items) that reduces calorie count by the commensurate amount that is removed by cooking, (and of course accounting for this in calorie inheritance and tests), but let's dig into that in a future PR.

**Pull request merged**
