### PR TITLE
limit stomach_contents::capacity to be no less than 250 ml

### LINKED ISSUE #76882: Tiny stomach trait with little/tiny mutation will make @ have negative stomach volume
### Describe the bug

The tiny stomach's -0.7 STOMACH_SIZE_MULTIPLIER combined little/tiny -0.5 STOMACH_SIZE_MULTIPLIER will create -1.2 STOMACH_SIZE_MULTIPLIER, giving negative stomach volume because the formula is ```value *= 1 + multiplier```, which is ```value *= -0.2``` in this case

### Attach save file

[Bell Ranch-trimmed.tar.gz](https://github.com/user-attachments/files/17276333/Bell.Ranch-trimmed.tar.gz)

### Steps to reproduce

Select tiny stomach and very short trait or add little/tiny mutation when building character

### Expected behavior

Stomach volume should never be negative

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: 0.G-12551-gce6526a2a1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #76882
#### Describe the solution
Limit stomach size to 250 ml, single unit of water; can't be smaller otherwise player gonna die from thirst, unable to drink water, vomiting it after each consumption
#### Describe alternatives you've considered
300 ml
#### Additional context
gastrectomy is no joke

### CODE REVIEW

**Comment by Fris0uman** [comment]
Isn't the problem that you always try to eat the whole in one go? This fix is was easier to implement than allowing partial consumption, but the fact that the player will always eat the whole item even if they literally have no room in their stomach seems like a bug.

**Comment by GuardianDll** [comment]
i honestly have no idea can we support partial eating and how hard it would be to implement

**Comment by Fris0uman** [comment]
There could at least be a thing where you consume up to your stomach volume and the rest is wasted. Or, because I think eating is an activity,each tick you could consume a percentage of volume and calorie and the food item could track that percentage I imagine. And your toon would stop when full

**Comment by NetSysFire** [comment]
Is there already an issue tracking partial consumption of comestibles? I do not find one right off the bat. Mainly because I'd have suggested looking at nethack because its a vaguely comparable game and supports partially eaten things.

**Comment by fairyarmadillo** [comment]
> Is there already an issue tracking partial consumption of comestibles? I do not find one right off the bat. Mainly because I'd have suggested looking at nethack because its a vaguely comparable game and supports partially eaten things.

Perhaps the charge system could be ported over to comestibles, and charges could represent portions of the food item /s

**Pull request merged**
