### PR TITLE
Modify monster melee targeting

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Features "Modify monster melee targeting logic"

#### Purpose of change

Fixes smaller limbs (mouth, feet, hands) never being targeted by most attacks. In addition, adds a non-explicit system for monster special attacks to restrict targeted bodyparts.

#### Describe the solution

~~Modified `select_body_part` and its upstream functions to ignore the size difference between the combatants (see additional context for the detailed reasoning), instead filtering bodyparts by two new monster/special attack fields - `hitsize_min` and `hitsize_max`.~~
- Added the fields `hitsize_min` and `hitsize_max` to monster special attacks, allowing the non-explicit bodypart selection to filter based on limb hitsize, and  `attack_upper` as a bool to allow hitting upper limbs
- Added `can_attack_high()`, a function to check if the combatant can attack limbs with the `UPPER_LIMB` flag 
  - for monsters small-sized mobs and below can't attack them unless they can fly or have the explicit `ATTACK_UPPER` flag
  - Otherwise-qualifying monsters can't attack upper limbs if they have the `ATTACK_LOWER` flag
  - characters can't attack upper limbs if they're prone, have broken legs or are downed
  - Added an additional bp flag ( LIMB_LOWER) to triple the limb's hitsize for attackers who can't attack the upper limbs
- Modified `select_body_part` to take the new fields instead of the size difference into account, it now also checks if the target character is on the ground and allows upper limb attacks for creatures normally incapable of that
- Adjusted vanilla monster's special attacks with `attack_upper: false` if they didn't qualify (cats can't scratch your eyes out if you don't lie down for them) and added `ATTACK_LOWER` to the crawling zombies

TODO
- [x] Move vanilla special attacks over to this system in preparation of mutant limbs
- [x] Remove `hitsize_relative` from bodyparts now that it's obsolete
- [x] Balance the limb hitsizes
- [x] Document changes
- [x] Remove the debug functions
- [x] Adjust the unit test to take the new system into account

#### Describe alternatives you've considered

Only change `hitsize_relative` of the small limbs, but that would have left special attacks either unable to filter their target bodypart or crashing the game when targeting a non-existent one.

Remove the size filtering completely.

Add a generic way of monsters filtering the target bodyparts by flags or bodypart category - it would certainly be nicer, but it also looks like pretty complicated stuff. Since for the moment the bodypart targeted is only relevant for monster->character and character->character violence I felt like I could get away with this barebones implementation.

Hook up a generic way to `mattack_actors` to inherit the base monsters' upper-limb-targeting rules but near as I can tell the loading function has no information on which monster it's loading the attack for, so I'll either filter by hand or just say "whatever"

#### Testing

Removed the bodypart array from a special attack and replaced it with hitsize restrictions, limbs got hit/filtered out as expected

Disabled attacking upper limbs on specials, those limbs got filtered out as well - if this leaves the list empty you get an error message and some imaginary damage to your appendix, but no crash (and shouldn't happen unexpectedly anyway)

Small critters can't attack upper limbs, unless they fly or have the special flag or their target is prone/downed.

Player characters lying down can't attack upper limbs.

#### Additional context

~~There were enough hardcoded monster attacks that could hit these limbs so that this flew under the radar for about four years, apparently.
I guess the reasoning behind the size-based targeting was that a Chihuahua couldn't attack your eyes, but that's ignoring a lot of edge cases where that *would* make sense (flying monsters, attacks from upper Z-levels, crouched/prone target, weird thin tentacle monsters that don't qualify as Medium sized because of their volume etc.).~~ Left in for posterity, but a reduced size-based filtering is kept.

<special attack hitsizes come here, Soon>

<details><summary>Test results before</summary>
Results read as "Number/percent of attacks with a given hit_roll hit this bodypart" out of 15,000 attempts

Smaller attacker:

| hit_roll | Torso |  Head |   Eyes |  Mouth |  Arms |   Hands |  Legs |   Feet |
|--------|------|--------|-------|---------|-------|---------|------|------|
|0 |      2947 |   0  |     0  |     0 |      4452 |   0  |     7601 |   0 |
%   |    19,6   | 0   |    0     |  0   |    29,7   | 0      | 50,7    |0|
1    |   2904  |  0   |    0    |   0   |    4676  |  0     |  7420 |   0|
%    |   19,4  |  0    |   0    |   0    |   31,1    |0       |49,5   | 0|
100 |    3409|    0  |     0  |     0  |     3989 |   0    |   7602   | 0|
%     |  22,7  |  0     |  0     |  0     |  26,6    |0      | 50,7  |  0|

Same-sized attacker:
| hit_roll | Torso |  Head |   Eyes |  Mouth |  Arms |   Hands |  Legs |   Feet |
|--------|------|--------|-------|---------|-------|---------|------|------|
0 |      4914   | 341 |    48    |  0 |      5985  |  0 |      3702 |   0|
% |      32,7    |2,3   |  0,3    | 0    |   39,9    |0     |  24,7   | 0|
1  |     4879   | 330  |   54   |   0   |    6181   | 0|       3556 |   0|
%  |     32,5   | 2,2   |  0,4    | 0      | 41,2   | 0  |     23,7 |   0|
100|     5090|    1758 |   91|    0 |      4771 |   0    |   3290|    0|
%    |   34,0|    11,7   | 0,6 |    0 |      31,4 |   0 |      21,9   | 0|

Larger attacker:
| hit_roll | Torso |  Head |   Eyes |  Mouth |  Arms |   Hands |  Legs |   Feet |
|--------|------|--------|-------|---------|-------|---------|------|------|
0  |     5397    |868|     86   |   0 |      6869 |   0 |      1780 |   0|
%  |     36,0    |5,8  |   0,6   |  0    |   45,8    |0     |  11,9   | 0|
1   |    5344   | 857 |    79 |     0   |    7023|    0  |     1697 |   0|
%   |    35,6   | 5,7   |  0,5 |    0      | 46,8   | 0    |   11,3 |   0|
100|     4896|    3801 |   150    | 0 |      4779  |  0 |      1374  |  0|
%    |   32,6 |   25,3   | 1|       0   |    31,86  | 0 |      9,2 |    0|
</details>

<details><summary>Test results after</summary>

Attacker can't target upper limbs:
| hit_roll | Torso |  Head |   Eyes |  Mouth |  Arms |   Hands |  Legs |   Feet |
|--------|------|--------|-------|---------|-------|---------|------|------|
  0  |   3367  |  0 |      0 |      0  |     2203  |  290   |  7437|    1693| 
  %  |   22,4   | 0       |0  |     0    |   14,7  |  1,9     |49,6   | 11,3 |
  1   |  3296   | 0      | 0  |     0   |    2385 |   289  |   7285|    1745| 
  %   |  22,0    |0      | 0   |    0   |    15,9   | 1,9    | 48,6   | 11,6 |
  100|   4693  |  0   |    0 |      0|       2410|    614 |    6356|    927|
  %    | 31,3 |   0     |  0    |   0  |     16,0   | 4,1 |    42,4    |6,2|

Attacker can target upper limbs:
| hit_roll | Torso |  Head |   Eyes |  Mouth |  Arms |   Hands |  Legs |   Feet |
|--------|------|--------|-------|---------|-------|---------|------|------|
  0  |   5319    |605 |    81    |  68 |     3510|    477 |    3988  |  952 | 
  %  |   35,5    |4,0   |  0,5    | 0,5   |  23,4   | 3,2     |26,6   | 6,3|
  1   |  5248   | 589  |   77    |  83  |    3750|    465 |    3864 |   924 | 
  %   |  35,0   | 3,9    | 0,5    | 0,5    | 25,0   | 3,1|     25,8  |  6,2 |
  100|   5933|    1674 |   183 |    170 |    3092|    778    | 3708|    392|
  %    | 39,5  |  11,2    |1,2 |    1,1    | 20,6 |   5,2     |24,7|    2,6|

</details>

### CODE REVIEW

**Comment by Zireael07** [comment]
Edge cases shouldn't overrule logic imho.

**Comment by Terrorforge** [comment]
> Edge cases shouldn't overrule logic imho.

I mean sure, but these "edge cases" aren't all the edgey. The standard wasp is a common flying monster that's smaller than a chihuahua, and there's no reason it shouldn't be able to reach your eyes.

What I'm thinking, however, is... how meaningful is body part size as a metric? I presume the idea is that e.g. a bio-operator could probably get its thumb into your eye, whereas a hulk couldn't hit your eyes without just smacking its entire fist into your head, so in that regard a minimum size makes sense. But does a maximum size? I can't think of a scenario where it would make sense for an enemy to be able to hit you in the hands, feet and eyestalks, but not the calves. No reason to remove that functionality, I guess, but probably the implementation should be that if no max hitsize is defined, maximum size is arbitrarily large.

**Comment by Zireael07** [comment]
> but probably the implementation should be that if no max hitsize is defined, maximum size is arbitrarily large.

Yep. But the chichuahua point still stands, and I think a ground-based walking monster should be the baseline, not a flying wasp/crow/whatever.

**Comment by Zireael07** [comment]
> Okay, but then the relevant factor isn't really the size of the body parts, it's their height, and that's kind of a separate issue. 

Yep, kinda.

Also I agree with you on that making it work even better is kinda out of scope.

**Comment by kevingranade** [comment]
Alternate idea, maybe we have a "height range targetable" property for the monster, i.e. min and max height, which is derived from size, movement modes, etc, and then that range is compared to player height (modified by stance) to determine what body parts are available for attack. It might be neat if flying enemies actually have trouble attacking close to the ground.

I know this is larger in scope than the current PR, but I don't think a basic version (just size plus flight ability) is that much larger, and it gets us to somewhere we can extend it pretty easily.

**Comment by Venera3** [comment]
I'll see if I can cobble something together. For the moment the only workable way I can see on the bodypart side is a flag, with a monster-side check to see if they can hit limbs with it - this bypasses the whole Character/creature override malarkey and leaves it all on the mob side. 

The hitsize stuff can live in the special attacks, that system is necessary to play nice with the custom BPs but for normal melee attacks it's less useful. The final `select_body_part` function will look a bit bloaty, but I think that's preferable to having two parallell functions.

**Comment by Terrorforge** [comment]
Might be worth considering how exposed body parts are as well. E.g. in fights people tend to get hit disproportionately in the hands and arms, not because they're a big target, but because they're sticking out and easy to reach. By the same token, a writhing chest tentacle is probably more likely to get nicked than a dragonfly naiad's labium folded in tight.

Idk if that deserves any system-level implementation or if it's just something to keep in mind while assign hit chances, but it's there.

**Comment by Venera3** [comment]
Small and tiny critters can't attack upper limbs. I also routed it through `is_on_ground` for characters to catch the times even a bulldog can chew your face.

**Comment by Venera3** [comment]
Slight rethink after fiddling with the hitsizes and the hitsize test: Added an additional bp flag ( `LIMB_LOWER`) to triple the limb's hitsize for attackers who can't attack the upper limbs. This preserves the original "smaller attackers go for legs most of the time" behavior, but includes a bit nicer filtering than the original size checks. I'll put up a table with the test results shortly.

Also redid hitsizes slightly, the end result should not be noticably different from the current state beyond hands/mouths/feet being targetable.

**Comment by Venera3** [comment]
An extra monster flag to cover "high-volume but should only hit lower limbs". This should be ready for review.

**Pull request merged**
