### PR TITLE
Pgettext'ing orange as color in item.cpp

### PR DESCRIPTION
**Pull request by Night-Pryanik**
To distinguish it from orange as fruit.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Silly Night, the color orange does not exist in Cataclysm. ;w;

**Comment by Night-Pryanik** [comment]
>Silly Night, the color orange does not exist in Cataclysm. ;w;

Uhhhm, what?

**Comment by chaosvolt** [comment]
I know. I was making fun of the fact that the actual color itself is not used by the game's palette. >.>

**Comment by Night-Pryanik** [comment]
Oh, it seems that my sense of humor deactivates after someone calling me "silly" for nothing.

**Comment by chaosvolt** [comment]
._.

**Comment by VlasovVitaly** [comment]
Can you replace "orange as color" -> "color". This makes more good sense, cuz contexts made for grouping.

**Comment by Night-Pryanik** [comment]
No probs.

**Comment by chaosvolt** [comment]
I'm now tempted to make orange exist in-game. <.<

**Comment by VlasovVitaly** [comment]
Ready for merge, guess.

**Pull request merged**
