### PR TITLE
Remove DURABLE_MELEE from some wooden weapons

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
None

#### Purpose of change

These weapons are made of only wood and some carving that could be from any source, including fresh, unseasoned wood with a high moisture content making them more pliable and weak. This doesn't scream durability. 

#### Describe the solution

Remove DURABLE_MELEE from cudgel, quarterstaff, and wooden tonfa.

#### Testing

Load ingame, game does not explode.

#### Additional context

This is barely a nerf, given how replaceable all of them are.

### CODE REVIEW

**Comment by actual-nh** [comment]
Ultimately, versions requiring skills/proficiencies for scavenging the right materials might have the DURABLE_MELEE flag.

**Comment by pehamm** [comment]
Isn't the Wooden Tonfa a recipe that cannot be autolearned, but has to be taken from "The Streetfighter's Sidekick"? That book teaches recipes that involve forging, I expect it to lose a few words about the wood selection.

But cudgel and quarterstaff can get taken a notch down, the latter helped me clear towns without splintering, which is a bit much for an entry-level weapon.

**Comment by LaVeyanFiend** [comment]
> That book teaches recipes that involve forging, I expect it to lose a few words about wood selection.

Even if true, this does not transmute green wood before reading it into good wood after.

**Comment by pehamm** [comment]
Fair enough. I believe I did not like changing the Tonfa because I never saw it as a do-it-yourself makeshift weapon like cudgels and quarterstaffs, but something I only ever stumbled upon in prison armories, which makes them feel more sturdy as pre-cataclysm "tech". If I carved one myself it should not be durable, but I personally never carved a tonfa and never found the book.

Semi-related, if this gets merged, should the wodden tonfas then taken out of the prison armory spawn groups? If those are not better than something a survivor can make themselves spontaneously with middling skill, it should not be good enough to be used by guards.

**Comment by kevingranade** [comment]
> Semi-related, if this gets merged, should the wodden tonfas then taken out of the prison armory spawn groups? If those are not better than something a survivor can make themselves spontaneously with middling skill, it should not be good enough to be used by guards.

This is a good point, and more generic than the prison armory issue.  Maybe the existing items should be unchanged, and we could add non-durable, easily-craftable variants?  This only applies if the items spawn as well as being craftable.

**Comment by Shodan14** [comment]
Has it ever been considered to use the weapon skill reduce the change of weapon damage when attacking/blocking?

**Comment by Aerotinge** [comment]
Do you consider also applying this on wooden pole weapon, like Naginata or Spear(everyone spear here and there)?

**Comment by LaVeyanFiend** [comment]
> Do you consider also applying this on wooden pole weapon, like Naginata or Spear(everyone spear here and there)?

I didn't consider the wooden spear/pike to have it removed since their points are fire-hardened

**Comment by pehamm** [comment]
> I didn't consider the wooden spear/pike to have it removed since their points are fire-hardened

The force is carried through the whole spear, at least between the tip and the back hand that supplies most of the thrust. And the wood in the back that carries the thrust from the muscles to the tip is still in it's natural state.

Although looking for research on how the force flows is applied throughout spears, I stumbled upon a paper by Ennos and Chan (2016) [(link)](https://royalsocietypublishing.org/doi/pdf/10.1098/rsbl.2016.0174), (doi: https://doi.org/10.1098/rsbl.2016.0174) that observed significantly (30%-60%) more breakage after fire-hardening spears, arguing that fire-hardening would be done more to sharpen the tips, accepting the increased fragility. So in a way not fire-hardened wood may even be less durable.

I would suggest making this uniform, hand-made wooden weapons should not be durable unless the player has skills and proficiencies to identify good wood and work with it, regardless of whether the weapons are used for bashing or stabbing. Unless we find further research, I am neither a carpenter nor an engineer.

**Comment by Broken27** [comment]
Quarterstaves should have Durable_Melee, the problems don't lie there.

Making Quarterstaves uncraftable (until there is some way to obtain seasoned wood), and adding a Makeshift Quarterstaff item makes more sense.

**Comment by Salty-Panda** [comment]
#49082: Already removed durable melee from quarterstaves, also contains a short discussion regarding seasoning wood etc.

**Pull request closed without merging**
