### PR TITLE
add screenshots game

### PR DESCRIPTION
**Pull request by ergolyam**
#### Summary
Content "Add game screenshots to data/screenshots"

#### Purpose of change

Adding new screenshots to the project to visually showcase different parts of the game, such as the main menu, gameplay, and credits.

#### Describe the solution

Three new screenshots were added to the `data/screenshots` directory:
1. `menu.png` - Displays the main menu of the game.
2. `game.png` - Shows a screenshot of the gameplay.
3. `credits.png` - Displays the credits screen.

#### Describe alternatives you've considered

No alternatives were considered as the addition of these specific screenshots serves the intended purpose.

#### Testing

Reviewed the screenshots to ensure they display the correct parts of the game as intended. Verified that they are correctly placed in the `data/screenshots` directory.

#### Additional context

Screenshots provide a visual understanding of the game for new users and can be used in documentation or promotional materials.

### CODE REVIEW

**Comment by grisha765** [comment]
hi, can you merge these changes into `0.H-branch`?

**Comment by grisha765** [comment]
@kevingranade 
hi, can you merge these changes into `0.H-branch`?

**Comment by Maleclypse** [comment]
> hi, can you merge these changes into `0.H-branch`?

0.H released yesterday so that wouldn't really be feasible.

**Comment by grisha765** [comment]
> > hi, can you merge these changes into `0.H-branch`?
> 
> 0.H released yesterday so that wouldn't really be feasible.

ok, then I think you can merge the changes from 0-H to master

**Pull request merged**
