### PR TITLE
Change how item groups are spawned

### PR DESCRIPTION
**Pull request by Trioct**
#### Summary

SUMMARY: Features "Change how item groups are spawned"

#### Purpose of change

In terms of item groups, item spawn rate currently only affect how many times an item group spawns. High spawn rates mean an item group might spawn on a tile 4 times, but with low spawn rates (especially like 10% low), the method for reducing spawns is reducing how often item groups spawn. When they do spawn though, they spawn in full 100% item spawn rate strength, so you either get nothing from a cupboard, or you get everything.

#### Describe the solution

This changes how item spawn rates < 100% work, where item groups have the normal chance to spawn, but items are less likely to spawn in the item groups. This allows frequent small loot piles instead of infrequent large loot piles at low spawn rates.

This also fixes a few things which I think are bugs.
Vehicle item spawns are now affected by item spawn rates.
Monster drops are now affected by item spawn rates > 100%.

#### Describe alternatives you've considered

Leaving it as is. It should be mathematically the same either way, minus the bugs.
Not making this pull request and embarrassing myself.

#### Testing

Test building, vehicle, and monster item spawns on low, normal, and high spawn rates.
Test non-mapgen related item group spawns, like bashing.

### CODE REVIEW

**Comment by Trioct** [comment]
This should only change spawns with a spawn rate < default, and it should act as the equivalent of multiplying the "chance" json variable by the ITEM_SPAWNRATE option with collections. Distributions are different, as in the end it may just not select an item. This is kind of like treating the whole distribution as an item, which will have its spawn chance lowered.

Maybe I could've explained better, but the way this should work is that when the spawn rates is < default, spawns work as if they're default. But once the code gets all the way down to spawning an item, where usually it'd be a 100% chance as it's gone past all the other checks, there's one more rng check against the spawn rate.

The huge item piles will still be pretty big assuming you're on a more reasonable lowered spawn rate like 50%. For example, going through three junk drawers each on 100% and 50% spawn rates, I found 49 items on 100% and 23 items on 50%. Below default spawn rates, the drawers have the same chance of spawning a loot pile, but on 50% the loot piles are half as big on average.

**Comment by Trioct** [comment]
Sorry, I should've bumped it, I'm still here. Thought I'd just wait until after 0.F, which is when I assumed it'd get merged.
I've been playing with it in my runs for a while, works how I want with low spawn rates.

**Comment by Night-Pryanik** [comment]
@Trioct could you please resolve conflicts?

**Comment by Trioct** [comment]
I wish I had my old dev environment to test this more thoroughly, but I've done a fresh os install since then. Compiled and seems to still work. Tell me if there's anything wrong.

**Pull request merged**
