### PR TITLE
Fix for issue #35067

### PR DESCRIPTION
**Pull request by naHrej**
An assert was being thrown while attempting to render information for non-gun weapons in the UI. This was caused by attempting to render ammunition information incorrectly for items that did not contain the ammunition structure. Adding a check for is_gun() before rendering is necessary to prevent the crash.

#### Summary
```SUMMARY: Bugfixes "Game Crash when scrolling over combat knife"```

#### Purpose of change
Fixes #35102
An assert was being thrown while attempting to render information for non-gun weapons in the UI. This was caused by attempting to render ammunition information incorrectly for items that did not contain the ammunition structure. Adding a check for is_gun() before rendering is necessary to prevent the crash.

#### Describe the solution
Added a check to the rendering code to prevent it trying read and render the missing data.

#### Testing
Ascertained the location of the error by recreating the bug with the original code, added the check and re-tested. Also checked to make sure that other item types were not incorrectly affected by the change

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
You need to [astyle](http://astyle.sourceforge.net/) your changes.

**Comment by esotericist** [comment]
In the future, please make a branch for your changes before submitting them.

Having them in `master` makes it more difficult for us to work with. (and makes it harder for you to have multiple things in progress at once)

**Comment by esotericist** [comment]
Fixes #30676

**Comment by Karthas077** [comment]
So this was treating the symptom but not the cause. Items with the `gunmod_data` JSON entry are not populating all the fields they used to ever since #34735 . `islot_mod` is responsible for the `ammo_modifier` field and is not being populated anymore for anything that isn't of type `GUNMOD`

**Comment by jbytheway** [comment]
@Karthas077 I just saw your comment regarding this breakage introduced by #34735.  I was a little puzzled at the time regarding the interaction between these islots.  Do you know whether this underlying issue has since been solved?

**Comment by Karthas077** [comment]
To my knowledge the current feature duplication between those fields is still present, but I went on vacation for almost all of November and am just getting back so I could have missed something.

**Pull request merged**
