### PR TITLE
Fix Anfo and RDX charge requirements.

### LINKED ISSUE #22226: ANFO charge recipe has insane components
1 ANFO charge recipe requires 700 units of ANFO and takes 2 hours to complete (and some other things that are not relevant for this issue).
However, the recipe for ANFO creates only 5 units at a time, requires 3 hours to complete and 500 gasoline and 90 ammonium nitrate (which requires on it's own 9 nitric acid and 9 ammonia and some minutes).
So to sum it up, creating all the ANFO units required to make a single ANFO charge would require:
70 000 gasoline 
1260 ammonia
1260 nitric acid 
420 hours of crafting (if you have all the ingredients ready)

Lets split it up:
----
> The ammonia is relatively easy - we find gallon jugs with 30 units of it all over the place and one can craft a lot with just a charcoal kiln, charcoal smoker, a swamp tile and some scrap metal. It does take 36 minutes to craft only 2 and this recipe time does not go down with batch either, so it will be worth your time to just run around and gather 42 gallon jugs of it instead.

> The gasoline seems excessive, but it is again doable if you are near a big town you can find few gasoline stations that could have more than 20 000 at a time. 

> The tricky part is the nitric acid. You can find bottles of 3 of it in labs (you'll need 420 of them) or craft it from sulfuric acid and to craft that one you require hydrogen peroxide (concentrated) which is not really craftable (one can craft the dilluted version from concentrated and vice versa, but neither is craftable by other means) and can again be found from labs in bottles of 3. So that would mean 420 bottles of either nitric acid or hydrogen peroxide and if it is the latter - add 25 minutes crafting time per unit you need to make into nitric acid.

> Raw crafting time, assuming you have ALL the ingredients ready is 420 hours. If we approximate that we will find the 1:1 nitric acid and hydrogen peroxide from labs, that will add some extra 262.5 hours of crafting time. 

I can throw some more numbers and calculations to why this might be making this recipe practically implausible to be made (unless you are insane person that wants to memorize all recipes without cheating like me), but I wonder if the simple explanation might be that the original ANFO recipe should be crafting maybe 50 instead of 5 units of ANFO for the amount of ingredients needed?

### LINKED ISSUE #22377: RDX charge recipe needs scaling down
Similar to the ANFO charge recipe (fixed after #22226 ), the RDX recipe will take forever to craft and cost literally two weeks of crafting time and hundreds of nitric acid which is not craftable otherwise but only found in labs. I suspect the problem is the same as in #22226, namely a previous fix ( #18337 ) had scaled the base ANFO & RDX recipes, but forgot to scale down the "charge" recipes.

### PR DESCRIPTION
**Pull request by Treah**
Fixed the charge for anfo and since it was such a small change going to add in a byproduct of sugar production from beets to include molasses. 
This fixes #22226
and Fixes #22377

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The problem with those molasses is that you can then craft them into second serving of sugar, making it over twice as effective as beet syrup provided you have lye to spare.

**Comment by Treah** [comment]
I'm not sure why Molasses is part of the sugar production recipe since its a byproduct and you cant really make sugar from it...  
I could remove it from the sugar recipe that uses lye.

**Comment by Treah** [comment]
Because of concerts over an increase in the production of sugar I updated the recipe to require one more sugar beet. This way its still better to use the harder to do recipe for sugar to get a dual output of sugar and molasses rather then the simpler sugar from sugar beet juice.

**Comment by atealein** [comment]
Could you please fix RDX charge as well? it suffers the exact same scaling issue as the ANFO one.

**Pull request merged**
