### PR TITLE
Sane-ify Integrated Toolset

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "bio_toolset is now welder and soldering only."

#### Purpose of change
Integrated Toolset has been on the hitlist for awhile now due to it being incredibly unrealistic even in the realm of sci-fi logic so I decided to take the shot. There's simply no way you could comfortably fit that many tools in your arms and there's also no way you could use those tools effectively. For example, there's no way you could get the leverage of a hammer with the toolkit unless you actually had the hammer in your hand.

#### Describe the solution
The welding bits have been kept since they could be kept reasonably compactly requiring no mechanical advantage unlike other tools. While it would be possible to fit a weak screwdriver or drill bit in your fingers I figure it's not ultimately worth doing.

#### Describe alternatives you've considered
Remove entirely.

### CODE REVIEW

**Comment by Photoloss** [comment]
Screwdriving and fine screw driving seem doable, the former can be achieved with a normal human fingernail if you don't need to tighten them too much. Both only level 1 if higher ones ever gain meaning, high speed or high torque are difficult without a full internal power tool. Drilling 1 might be doable as you say.

Cutting and (really bad) butchering are almost trivial by sneaking a pocket knife sized blade in somewhere. Level 1 prying should be possible with something like wolverine claws, higher levels definitely not. Low-level sawing _might_ be doable seeing as the multi-tool knives also have it (a small serrated section on one side of a wrist blade integrated into the forearm similar to Wolverine). The blade could also have level 1 fine cutting.

Other newer tool qualities which might fit into small subdermal implants: awl 1 ("sturdy needle"), smoothing 1 (some kind of flat surface, a foldable section on the forearm blade perhaps), hammering 1, fine and soft hammering 1 (various random hard bits), punch 1 (random hard bit 2-3cm wide), sewing 1, knitting 1 (needle dispenser), filing 1 (flat of the blade), lockpicking 1 (needle dispenser). Including **all** of these might be pushing it a bit depending on conflicts with other CBMs.

The ones which definitely need to go are the long levers: wrenches, hammers, large saws etc. Some of those could be squeezed in by giving you a "beer gut" storage compartment filled with regular hand tools but that would be highly inconvenient. Another weird solution would be a modular telescoping pole which you mount different heads on for the wrench/hammer/crowbar etc. made out of superalloy for the necessary sturdiness, this would cause a very long time to ready each tool and would not allow using multiple at once though (so no hammer *and* chisel). With the possible exception of the knapping punch all of the previous list should be able to fit into the hands or forearms without completely replacing them, in the master-of-none kinda-crappy quality expected of your typical multi-tool Swiss Army Knife. And don't forget the can opener!

**Comment by anoobindisguise** [comment]
> Screwdriving and fine screw driving seem doable, the former can be achieved with a normal human fingernail if you don't need to tighten them too much. Both only level 1 if higher ones ever gain meaning, high speed or high torque are difficult without a full internal power tool. Drilling 1 might be doable as you say.
> 
> Cutting and (really bad) butchering are almost trivial by sneaking a pocket knife sized blade in somewhere. Level 1 prying should be possible with something like wolverine claws, higher levels definitely not. Low-level sawing _might_ be doable seeing as the multi-tool knives also have it (a small serrated section on one side of a wrist blade integrated into the forearm similar to Wolverine). The blade could also have level 1 fine cutting.
> 
> Other newer tool qualities which might fit into small subdermal implants: awl 1 ("sturdy needle"), smoothing 1 (some kind of flat surface, a foldable section on the forearm blade perhaps), hammering 1, fine and soft hammering 1 (various random hard bits), punch 1 (random hard bit 2-3cm wide), sewing 1, knitting 1 (needle dispenser), filing 1 (flat of the blade), lockpicking 1 (needle dispenser). Including **all** of these might be pushing it a bit depending on conflicts with other CBMs.
> 
> The ones which definitely need to go are the long levers: wrenches, hammers, large saws etc. Some of those could be squeezed in by giving you a "beer gut" storage compartment filled with regular hand tools but that would be highly inconvenient. Another weird solution would be a modular telescoping pole which you mount different heads on for the wrench/hammer/crowbar etc. made out of superalloy for the necessary sturdiness, this would cause a very long time to ready each tool and would not allow using multiple at once though (so no hammer _and_ chisel). With the possible exception of the knapping punch all of the previous list should be able to fit into the hands or forearms without completely replacing them, in the master-of-none kinda-crappy quality expected of your typical multi-tool Swiss Army Knife. And don't forget the can opener!

All this sounds good, I'll try to "sane-ify" this a bit more rather than taking the scorched earth policy to the CBM.

**Comment by catdach** [comment]
> There's simply no way you could comfortably fit that many tools in your arms

Ok, maybe not the hammer and crowbar, but most of the other stuff is pretty common on most pocket knives which aren't much larger than a human finger. Heck, I carry a multitool in my wallet that's about the size of a credit card with a saw, a file, flat-head screw driver bit on the corner, a hole to fit lug nuts and be used as a small adjustable wrench, even a can opener and a bottle opener! Admittedly the saw blade is pretty short and it hurts to grip it in my hand, but it gets the job done. Point being that an intelligent use of space would make it pretty reasonable to have some version of these tools in your arms, if not in a single hand.

> Adding a powered tire iron would work as well

Perhaps something like an [impact wrench](https://en.wikipedia.org/wiki/Impact_wrench) is the IRL hand tool version of this. To my knowledge, it serves as basically a power drill equivalent for a wrench and/or tire iron.

> I worry the force would just twist and snap your finger

I really can't visualize how this would happen. I assume that it would basically be like replacing a fingertip with a spinning drill bit. Unless the finger was curled during use, your hand would break off before the finger; and if that amount of force was a problem for the human hand then powered hand drills wouldn't exist in the real world.

**Comment by anoobindisguise** [comment]
[ "WRENCH", 1 ],
[ "WRENCH_FINE", 1 ],
[ "WHEEL_FAST", 1 ],
[ "SCREW", 1 ],
[ "SCREW_FINE", 1 ],
[ "CUT", 1 ],
[ "DRILL", 3 ],
here's what it can do now in addition to welding duty. everything that's commonly used and practical to fit in your hands. You might be able to add reaming, rock drilling and punch, possibly others, but I don't think the Exodii would waste space on those when they're not commonly used enough to matter. I think this is a good balance between nearly no function and "there is no logical way it can have this much functionality".

**Comment by kevingranade** [comment]
If we're rationalizing this, wheel wrenching needs to go too.  Regular wrenching implies significant mechanical advantage, and impact wrenches that can handle it are much larger than would fit in a hand.  Likewise DRILL: 3 is excessive, that's large, high-torque bits.  Plus drill bits are consumables, so not fit for a permanent application like an implanted toolset.

**Comment by anoobindisguise** [comment]
> If we're rationalizing this, wheel wrenching needs to go too. Regular wrenching implies significant mechanical advantage, and impact wrenches that can handle it are much larger than would fit in a hand. Likewise DRILL: 3 is excessive, that's large, high-torque bits. Plus drill bits are consumables, so not fit for a permanent application like an implanted toolset.

Got it, I'll go back to just welder then.

**Comment by Photoloss** [comment]
> Got it, I'll go back to just welder then.

I do think the other feasible ones have value, maybe as a separate CBM though. The welder (+soldering, screwdriving, and maybe filing and low hammering) is something the Exodii would all carry as standard issue. Wood, stone, leather and cloth handling tools would still be useful for their new recruits/allies as general reliable survival tools i.e. an "Integrated Multi-tool CBM" for those who want to scavenge more efficiently and don't have a full cyborg conversion available yet.

From a gameplay perspective the multi-tool is a convenience feature so you don't have to fetch and carry random tools for odd jobs the same way no one really _needs_ a cranial flashlight or glare compensators but it's sometimes nice to have the option regardless.

**Comment by anoobindisguise** [comment]
This was failing due to the name change, tests/iteminfo_test.cpp didn't like that. Now C++ is involved, wonderful! Hopefully it won't fail that check anymore though.

**Comment by gkarfakis19** [comment]
I understand that the Integrated Toolset was extremely unrealistic and that some of its features had to be removed, as @Photoloss  mentioned, however, it's a very useful convenience tool to the point where I would make obtaining it my first bionic priority in every playthrough. Is it possible to re-add some of this functionality in other bionics?

**Comment by Photoloss** [comment]
Since the merged version is designated as a "welder" feel free to file a feature request using my comments. An "Integrated Multi-Tool CBM" or the like with all the small manual tools but no long levers let alone power tools. If you want a hacksaw implant that would probably require a separate module, and occupy almost an entire forearm all by itself if any kind of "bionics slots" system is considered.

**Comment by GoLoT** [comment]
Next step after this should be deprecating the ["toolset"](https://github.com/CleverRaven/Cataclysm-DDA/pull/52889/files#diff-dbd725072a2fbc9605773da6918227536a0d977dcb3a13b9349eb2530b2e88d1L28) fake item since it has no remaining qualities or uses. Actually it has a single use left, which is being able to start fires, but that's basically what the Finger Lighter CBM is for. Anyway, the firestarter flag should be added to the extended_toolset so it can only be used when the welder is extended. Then the fake_weapon "extended_toolset" can be added to the main CBM to replace the now useless toolset pseudoitem.

This allows deprecating the secondary CBM [("bio_tools_extend")](https://github.com/CleverRaven/Cataclysm-DDA/pull/52889/files#diff-3d0ef47ac4d216ce9c93d3d4b3b45a113385b5d02d858aa3c513b1a8a2662bd7L1540) by removing it from the included_bionics list of the main CBM so new installs don't add it.

This should be an easy cleanup if anyone wants to do it. I'll get to it when I'm done with my current PRs if no one picks it up.

**Comment by AcidAntOnAMinefield** [comment]
> Integrated Toolset has been on the hitlist for awhile now due to it being incredibly unrealistic even in the realm of sci-fi logic

To be honest, there's a lot of stuff in the game that fits the same bill, including the actual lore. Imo if we are going to remain on the realism path, at least having it applied properly would be the way to go, not just selective realism. Just like the Shock Absorber CBM, it would've been better if this was removed entirely.

**Comment by Photoloss** [comment]
> > Integrated Toolset has been on the hitlist for awhile now due to it being incredibly unrealistic even in the realm of sci-fi logic
> 
> To be honest, there's a lot of stuff in the game that fits the same bill, including the actual lore. Imo if we are going to remain on the realism path, at least having it applied properly would be the way to go, not just selective realism. Just like the Shock Absorber CBM, it would've been better if this was removed entirely.

And while we're at it let's remove those awfully unrealistic zombies and giant mutant animals!

(They're rewriting CBMs to be of extradimensional "parallel Earth" origin)

**Comment by AcidAntOnAMinefield** [comment]
> And while we're at it let's remove those awfully unrealistic zombies and giant mutant animals!
> 
> (They're rewriting CBMs to be of extradimensional "parallel Earth" origin)

"(...)in the realms of scifi logic(...)" being the reason for the change is the key aspect to my post as I pointed it out. And as I also said, I would be more in favour of removing tool-based CBMs entirely than to just nerf them. 
As to your point, Zombies and Giant Mutant animals are very well within the realms of scifi logic. Although one could argue that they shouldn't be at that stage even within the first year of the game - but I already know "blob magic" is the reasoning it.

**Comment by hostergaard** [comment]
I always tought it would be better would be to split the integrated toolset into several snazzy CBMs that you can find so you can slowly find and build an internal toolbox. Might even have several variants on certain tools that provides different levels of qualities, higher qualities being more rare. 

Side note, but it had me thinking that it could interesting if one could have an overall integrated toolset and you could slowly add various bionics to that toolset that would ultimately turn into the classical integrated toolset we know and love. 

As for realism and fitting it comfortable, my father is a carpenter and I have been around tools my whole life, it really would be easy enough if you simply think about it. Consider just how many tools you can fit in a Switch army knife or multitool. A hammer? It works because there is a hard surface with certain weight behind it, your arm providing the force by whipping it down. Simply having a hard surface on your hand would allow to work the same (with some consideration for shock absorption, and maybe make the cbm pool blood in the hand for weight) so you can basically hammer it down with your fist or slap it down depending on where the hard surface is. You gotta be a bit creative and consider what you can do with more advanced tech, as some say, it can be indistinguishable from magic. You don't need to fit a perfect tool  that looks identical to what we have today, you can use the way the body is already and make it wort. If you got titanium fingers, you could make them lock up and work as bolt turners. Or you could a pneumatic hammer in your arm. To claim you can't fit it is just silly and shows a lack of imagination. I could easily fit everything in the integrated toolset in one arm, or hand even. Crowbar? Lock up some joints, extend some nails from your fingers, you got a hand/arm crowbar.

**Comment by gkarfakis19** [comment]
> I always tought it would be better would be to split the integrated toolset into several snazzy CBMs that you can find so you can slowly find and build an internal toolbox. Might even have several variants on certain tools that provides different levels of qualities, higher qualities being more rare.
> 
> Side note, but it had me thinking that it could interesting if one could have an overall integrated toolset and you could slowly add various bionics to that toolset that would ultimately turn into the classical integrated toolset we know and love.
> 
> As for realism and fitting it comfortable, my father is a carpenter and I have been around tools my whole life, it really would be easy enough if you simply think about it. Consider just how many tools you can fit in a Switch army knife or multitool. A hammer? It works because there is a hard surface with certain weight behind it, your arm providing the force by whipping it down. Simply having a hard surface on your hand would allow to work the same (with some consideration for shock absorption, and maybe make the cbm pool blood in the hand for weight) so you can basically hammer it down with your fist or slap it down depending on where the hard surface is. You gotta be a bit creative and consider what you can do with more advanced tech, as some say, it can be indistinguishable from magic. You don't need to fit a perfect tool that looks identical to what we have today, you can use the way the body is already and make it wort. If you got titanium fingers, you could make them lock up and work as bolt turners. Or you could a pneumatic hammer in your arm. To claim you can't fit it is just silly and shows a lack of imagination. I could easily fit everything in the integrated toolset in one arm, or hand even. Crowbar? Lock up some joints, extend some nails from your fingers, you got a hand/arm crowbar.

These ideas sound amazing. Do you think you could make a feature request with this?

**Comment by adamkad1** [comment]
Maybe remove robots and manhacks while you are at this?

**Comment by kevingranade** [comment]
That's why the only things I asked to be removed were the large wrench and drill, but the author here just ignored that for some reason.

**Comment by Photoloss** [comment]
> That's why the only things I asked to be removed were the large wrench and drill, but the author here just ignored that for some reason.

Umm, if I may ask, seeing as **YOU** said this, why was this PR merged then? Shouldn't there be some kind of "hold for review" phase for changes like this where a reasonable alternative/extension exists but is not part of the PR?

**Comment by gkarfakis19** [comment]
> > That's why the only things I asked to be removed were the large wrench and drill, but the author here just ignored that for some reason.
> 
> Umm, if I may ask, seeing as **YOU** said this, why was this PR merged then? Shouldn't there be some kind of "hold for review" phase for changes like this where a reasonable alternative/extension exists but is not part of the PR?

Normally this wouldn't be an issue but this PR basically destroys most of the integrated toolset functionality and will really impact people playing in experimental.

**Comment by Photoloss** [comment]
> Normally this wouldn't be an issue but this PR basically destroys most of the integrated toolset functionality and will really impact people playing in experimental. It seems weird that this was merged when the most senior dev on here disagrees with the changes.

Eh, I'd argue it's *almost always* an issue albeit a subjective psychological one. It breeds discontent as players only see their shiny toys taken away, most of them unable to code a replacement. Then the fixes, which long-running devs might consider later parts of the same project, arrive under completely different conditions and those PRs garner praise while the older one continues to be a black stain on the game's history. A single "Split Integrated Toolset CBM into easy multi-tools and high value power tools" change will still be seen as a nerf by some, but many others will enjoy the greater availability, lower install difficulty and extended functionality of the other niche tools and happily keep their vehicle welding rig a little longer before unlocking the "nerfed" welder CBM.

Some changes such as fundamental reworks of nutrition, aiming, vehicles or the like genuinely require a "broken" intermediate phase as the core C++ mechanics get fleshed out before all object data can be brought up to speed. But for something like this I see no reason for the presently-merged state to exist over just keeping the status quo until a proper rework is finished.

**Comment by anoobindisguise** [comment]
I have absolutely no problem with #53153 re introducing those features. my original plan for this PR was to make the tool just the welder so I reverted to that goal.

**Comment by AdamChirnside** [comment]
FYI: the "Extended Welder" appears on the menu to remove bionics, and causes a crash when chosen

**Comment by anoobindisguise** [comment]
> FYI: the "Extended Welder" appears on the menu to remove bionics, and causes a crash when chosen

this happened before with extended toolset too.

**Pull request merged**
