### PR TITLE
Fix for overlapping farm zones NPC Shuffle

### LINKED ISSUE #35472: NPCs dance instead of farm if zones cross
# Describe the bug

When there are overlapping farm zones NPCs get confused as to what they're supposed to be doing and move back and forth across the zones instead of planting. It seems to occur regadless of seeds, whether the plot is set to no seed or whether the NPC has relevant seeds in their inventory.

# Steps To Reproduce

1. Set more than one farm zone overlapping with enough room to move around in.
2. Talk to NPC: 'l' (for lima) to farm.
3. Give them some seeds if they don't seem confused, I might be wrong about the seedless bit.

**Edit:**

Looks like the bug is triggered when an NPC exhausts the seeds in their inventory before completing all assigned tiles. If those tiles overlap another farm zone that they're due to work on they'll dance about, even if that zone is set to no seed.

# Expected behavior

Anything but dance. Complaining and quitting would be better than that. I'd suggest using a random seed, but using whatever plot is first to pick might be best. Having an 'any' seed farm plot would be ideal really, plus a stockpile for it.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9308-g1d6366e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix for overlapping farm zones NPC Shuffle"```

#### Purpose of change
Fixes #35472 

#### Describe the solution
1 ) NPC assesses the tile there , runs zones::get_zones() over the zones there, the first one the NPC has seeds for it considers a success and NPC goes " right I can do this, I have wheat seeds" and travels there,
2 ) then when the NPC is there it runs zones::get_zone_at() which iterates over the zones there ( in reverse order for some reason ) and then it decides it cant do the planting cos it looks at strawberry zone first and donst have strawberry seeds, and goes back to 1) repeat forever.

The fix is to ensure that he assessment and the doing of the planting are comparing the exact same zone every time, or at least iterating over them in the same order.

#### Describe alternatives you've considered
N/A

#### Testing
Loaded save in linked issue, after fix, they no longer shuffle back and forth but continue to plant what they can until activity is done.

#### Additional context
N/A

### CODE REVIEW

**Comment by kevingranade** [comment]
Unless we understand why things are being iterated in reverse, let's do everything forward instead of backwards.

**Comment by kevingranade** [comment]
In particular, looking at the history of zones::get_zone_at(), there's no indication whatsoever why it's iterating backwards.
If I had to hazard a guess, it might be because it was copied from zones::get_bottom_zone(), which specifically wants to get the last matching zone instead of the first one.

**Comment by davidpwbrown** [comment]
Made everything go forward instead of in reverse.

**Comment by Funguss** [comment]
> forward instead of backwards.

And always twirling, twiriling towards freedom! Seriously though, thank you so much for this fix. I found messing with piddly farm zones got really old really fast, I'm so happy to see this merged. :100:

**Pull request merged**
