### PR TITLE
Prune list of builds run on PRs

### PR DESCRIPTION
**Pull request by kevingranade**
The number of builds was getting out of control, only test the major configurations on PR builds.

SUMMARY: None

### CODE REVIEW

**Comment by jbytheway** [comment]
Your previous logic was to build the newest and oldest of each compiler version.  Have you decided that's no longer worth it?

In particular, you've turned off gcc 5.3 here, which was the oldest compiler we were testing.  I'm a little concerned about losing that.

**Comment by kevingranade** [comment]
Yea I need to revisit this more carefully, I also notice we have some cases where we have different builds invoking the same compiler, which is unecessary.

And yes the main configurations will be min and max version of clang and gcc.

**Comment by jbytheway** [comment]
> I'll open a new PR and let it sit for discussion a bit, this was kind of an emergency fix since build times were getting insane.

Hoping I've not stolen your thunder, but I have gone ahead and proposed something with #30761.

**Comment by kevingranade** [comment]
Thunder thoroughly stolen.

**Pull request merged**
