### PR TITLE
Place cursor at highlighted item name in construction and crafting menus as expected by screen readers

### LINKED ISSUE #39499: ui_adaptor: accessibility regression
# Describe the bug

when the interface migrates to ui_adapter, accessibility for the blind is impaired.
what is affected:
* crafting menu
* construction menu.

# Steps To Reproduce

1. use speakup on linux
2. press numpad star to enable tracking 
3. open construction or crafting menu
4. arrow between items.
5. item name isn't spoken

# Expected behavior

speakup announces item name. because it is Highlighted.

# Versions and configuration

* OS: archlinux
* Game Version: 217f4235ab
* Graphics version: terminal
* Ingame language: ru

# Additional context

i think if current item selection had been indicated not only by a color change, but also by the system cursor, this would remove this and many other problems.

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Place cursor at highlighted item name in construction and crafting menus as expected by screen readers"

#### Purpose of change
May fix #39499.

#### Describe the solution
Place the cursor at the beginning of the highlighted item/construction name.

#### Testing
@alex19EP please test if this resolves #39499.

### CODE REVIEW

**Comment by alex19EP** [comment]
construction menu: works like a charm. 
crafting menu: not working. i don't see the cursor on selected item.

**Comment by alex19EP** [comment]
weird. the cursor is always on the second item from the bottom in the visible part of the list.

**Comment by Qrox** [comment]
Perhaps crafting menu didn't work because the window was not refreshed. Please test the new patch and see if it works.

**Comment by alex19EP** [comment]
yay! now all is working. @Qrox great job.
thank you.

**Comment by Kenan2000** [comment]
Thanks a lot for tremendous work, @Qrox , screen reader and general accessibility, broadening this great game's audience by such means so that players from various communities can play it and enjoy it is very deeply appreciated by me, maybe i'll be able to work on this too someday, for now i'm just a JSON fixer :)

**Comment by Qrox** [comment]
@alex19EP @Kenan2000 glad to help! :)

**Comment by jbytheway** [comment]
@Qrox are you able to record what you learned in the docs somewhere for future reference?

**Comment by alex19EP** [comment]
> 
> 
> @Qrox are you able to record what you learned in the docs somewhere for future reference?

if you want i can create issue describing an interface that needs cursor treatment.
it really helps in accessibility.
post scriptum.
So I think I'm the only blind player at the moment. I'm just a little  embarrassed to ask for accessability fixes. 😳

**Comment by Qrox** [comment]
@jbytheway I've added documentation in #39609.

@alex19EP No worries, just open an issue and I believe people will be willing to help. Cursor fixes seem pretty straightforward so we can probably gradually add it to every UI.

**Comment by jbytheway** [comment]
@alex19EP if you really are the only blind player, then maybe accessibility fixes are exactly what we need to encourage more, so I also encourage you to open issues.

**Comment by alex19EP** [comment]
ok @jbytheway . I received a carte blanche. ☺ so get ready. 😀 I will deal with this soon.

**Comment by Leland** [comment]
@alex19EP thank you so much for providing feedback! there is no substitute for getting info from the folks who need a11y support the most :)

I've come across least one other blind CDDA user on GitHub, @BlindGuyNW from way back on  #15864. In my experience, that means there are many more lurkers out there! hope ya stick around 🚀

**Comment by BlindGuyNW** [comment]
You rang? :)

I haven't been poking at CDDA for a while, mostly because my Linux machine isn't a constant presence like my Windows and Macs. However, I'm always happy to see new accessibility fixes.

I'll keep an eye on this at the very least

**Pull request merged**
