### PR TITLE
Add detergent and allow it to be used in washboard

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Voker57** [comment]
What's the point of having another item fulfilling the exact same role? Why not merge them into one item like "washing solution"?

**Comment by Night-Pryanik** [comment]
> What's the point of having another item fulfilling the exact same role? Why not merge them into one item like "washing solution"?

Because soap is used as ammo also in shaving kits. It would be strange to use detergent with shaving kits, wouldn't it?

**Comment by Night-Pryanik** [comment]
I thought that adding some alternative (like sinews, fiber and yarn to thread) is better than just bumping up spawn of soap.

**Comment by Rivet-the-Zombie** [comment]
Detergent could have a more efficient volume to charges ratio than soap, since it's made specifically for washing clothing and a little goes a long way.

**Comment by Night-Pryanik** [comment]
You mean like changing it so 2 (or 3) charges of soap will be equal to 1 charge of detergent?

**Comment by Rivet-the-Zombie** [comment]
Like give it the same volume as soap, but with more charges.

**Comment by Night-Pryanik** [comment]
Is 200 charges too high?

**Comment by Rivet-the-Zombie** [comment]
Yeah, probably a bit high. Normal soap has ten, so maybe 2X as efficient, instead of 20X.

**Comment by kevingranade** [comment]
Please create the branch on your own repository, the fact that the permissions allow you to create it in the main repository is a shortcoming of the github permissions.

**Pull request merged**
