### PR TITLE
Remove skewers from smoked meats

### PR DESCRIPTION
**Pull request by Coolthulhu**
Skewers take no volume. At this point in game, they are free.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
At some point we should probably also do something to make dehydrated/salted/smoked meats a bit more different from each other as well.

**Comment by Coolthulhu** [comment]
Dehydrated meats are useful in many recipes, but bad on their own. They're quite different from salted and smoked, which are good "raw".
Once the optional component system is in (if ever), salted meats could count both as meat and salt, in recipes that use both. They have lower nutrition (than smoked) when consumed directly, so smoked would still have a role.

**Comment by bumpkindda** [comment]
What if salted had more nutrition per weight/volume (best for carrying around) and smoked had more nutrition per ingredients going into it.

**Comment by Soyweiser** [comment]
Do we even still use skewers? Can they just be removed?

**Comment by SeanMirrsen** [comment]
>Do we even still use skewers? Can they just be removed?

I'm continually upset at the direction the game in general is heading. As in, it becomes a **game** game - optimized for play, detached from the world it describes. I'd really like a version of CDDA that has it all returned, all the previously removed fiddly bits of fluff and tinker that serve no purpose and get in the way of *playing* the game, by giving the player some of those mundane annoyances that living by yourself in the cataclysm would provide. Vermin, lead plates for car batteries, skewers for cooking meat, etc - I don't follow most PRs here in detail, but I'm assuming this sort of thing is at least as pervasive as it looks.

**Comment by Coolthulhu** [comment]
> I'm continually upset at the direction the game in general is heading. As in, it becomes a game game - optimized for play, detached from the world it describes.

This is to balance the annoying natural tendency for it to go the opposite way - adding meaningless, annoying selectively-realistic trivialities that make the whole vision of the world incredibly unbalanced.
* Skewers required to craft smoked meat, but bread baked without an oven, just on a hotplate
* Vermin visible on the other side of the field of vision, tiny spiders blocking hulks and antimateriel rifle bullets
* Getting depressed from wearing a dirty backpack while not washing, changing underwear or even taking a shit (outside clothing at least) in the whole last year
* Separate step in crafting anything that does not add anything to the game and only requires extra keypresses - like lead plates for batteries or fletching for arrows

**Comment by SeanMirrsen** [comment]
>This is to balance the annoying natural tendency for it to go the opposite way

While I do understand the need to keep it in check, why not leave the option open to have those trivialties? I wouldn't mind finding an oven to bake proper loaves of bread (because there are other options for bread-like provisions), and I don't mind the extra step in the crafting. I'd have preferred a controlled expansion of the trivialties, to bring the vision of the world to the *detailed* side of balance, rather than culling them to bring it to the "*bland*" side.
(I mean yes, sure, it's more work in general, but surely relegating the old content to a mod is not that much harder than simply removing it?)

**Comment by Coolthulhu** [comment]
> While I do understand the need to keep it in check, why not leave the option open to have those trivialties?

Start a mod and, when possible, we'll be moving those things to the mod instead of removing them altogether.

> bring the vision of the world to the detailed side of balance, rather than culling them to bring it to the "bland" side.

Bland and needlessly detailed aren't opposites. Bland and distinct are.
When things share same details, like having extra steps that mean nothing and are only needless keypresses, they aren't any less bland than if they didn't have those details.

For example, having 3 named shotguns with nearly identical stats doesn't make them any less bland than if they all were just a single item named "shotgun".

Probably the worst offender of this pretend-detail is the set of chemistry-related items that aren't used anywhere. All this crap that spawns in labs, says "you could use it to explode a tank", but doesn't actually allow exploding anything with it, nor even cooking food with it.

And, in fact, needless detail stands in the way of actually making things distinct. Every moment spent updating skewer types, recipes involving chisels, gun stats for nearly identical guns and descriptions for items that don't matter is a moment not spend actually adding anything meaningful to the game wasted by a person willing to add something to the game.

**Comment by Soyweiser** [comment]
Skewers now provide no additional game benefit. They are basically wood (which is abundant and of low value), Using it to start an inferno is also nerfed iirc. So right now it is only a junk item. And in this case it isn't even something that is all that interesting. Skewers? Really not that vital. And like coolcthulhu said easy to mod in if you really want to add Yakitori to the game.

And indeed the various lab explosives have never been finished I think. Which is another problem CDDA has (mea culpa), starting stuff and never finishing it. Sadly a lot of that has been added into mainline in the past. If you really want to help sean, go over the various mods add look at what is missing. (For example, the survival tools mod is missing the block tags (and more) on weapons). Which is imho a lot worse for the game. At least some broken mods are being fixed right now. (I'll take a look at more survivor tools, if it hasn't been looked at).

**Pull request merged**
