### PR TITLE
Rigid armor, conflicts and raw skin

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Limiting rigid armor, testing for it and raw skin"

#### Purpose of change
Makes it so any hard armor conflicts with any other on BP and layer (maybe not sure on this),

Makes it so wearing hard armor with nothing under it will cause chaffing and soreness (gotta wear those socks)

Probably will unhardcode shoes. 

#### Describe the solution
What this PR does:

- Tracks what armors are more than 40% hard material on any sub bodypart and counts those as "rigid"
- Tracks what armors are more than 40% soft material on any sub bodypart and counts those as "comfortable"
- You can only wear one piece of "rigid" armor per sublimb
- With this shoes and helmets have been unhardcoded
- Some special rules to make most shoes "rigid" have been added, basically the same as the 
- I also removed the cap on head encumbrance since it does something now (original change not in this PR)
- Now all limbs and locations behave the same for armor, no weird rules
- Checks if you are wearing something comfortable under any piece of rigid armor (the rigid armor itself can be comfortable) if you aren't you get a small pain and speed penalty. Nothing crazy just something to help encourage layering armor sensibly.
- Added new flag PADDED for items that are rigid armor but are designed to be worn against bare skin. I've added it to helmets which normally have little pads to make them more comfortable.
- Added a flag for mutant limbs to make them able to ignore discomfort (more expansion will come to this later).
- Added UI to indicate comfortable and rigid body parts.

Nitty Gritty

- Lots of additions to the character wrapper to iterate through armor when changing sides and stuff to make sure it's a legal move. 

TODO:

- [x] add soreness effect if you aren't properly covered under hard armor
- [x] add rules for only wearing 1 of any hard armor piece per limb
- [x] unhardcode footwear
- [x] wait until the worn wrapper is merged so this doesn't get muddled with it

#### Additional context
NOT_FOOTWEAR and HELMET_COMPAT should be removed but I'm leaving them for mod compatibility.

### CODE REVIEW

**Comment by PlutusPleion** [comment]
I'm all for realism but feel like there should be a gameplay reason for it as well. First impression I just see this as: "you have to wear underclothes". Some "hard" clothing usually have padding underneath already. 

And where is the line for "hard"? Is super thick layered kevlar hard? Is it anything with iron/steel? How about chainmail? it has pretty good movement. Likely each armor would have to be hand-categorized.

The 1 hard armor piece per limb is more agreeable. This is pretty much an extension of what we already have with helmets and shoes.

**Comment by bombasticSlacks** [comment]
Currently it's by material and can be overridden with a flag for it being hard or a flag for it being soft.

It's a good point about comfortable things with a backing. I can make it so comfort is different from softness/hardness and put a threshold like "at least 90% needs to be covered in a soft material for it to not chafe".

**Comment by PlutusPleion** [comment]
Just throwing ideas out there, maybe just give additional encumbrance. Could be confusing for people.

**Comment by bombasticSlacks** [comment]
The plan was to have warnings in the layering menu, on the armor item UI itself, and it will create an effect similar to hot (bp) but instead it would be like chaffing (bp), which you can hover for a description and explanation why it's happening.

**Comment by Venera3** [comment]
For some skin types a trait-based global chafing modification would be nice, and the same goes for bodyparts on a per-limb basis - chitin shouldn't care about something hard being strapped on it(global skin trait), whereas a tentacle or a slime pseudopod would probably find it more uncomfortable. I want to say it could key off of cut armor, but I don't think *negative* armor is supported there.

**Comment by PatrikLundell** [comment]
Looks like it's covered with overrides, but I believe there's a power armor that requires direct skin contact, so it should be made sure this will still work without being penalized.

**Comment by Sutremaine** [comment]
'Dry plant' should probably be a soft material, going by which items are made from it.

Items which could use a "SOFT" flag: unfolded emergency blanket, unfolded emergency poncho, duct tape blindfold.

To find these ones I searched recipes for 'd: material: plastic' and looked through the resulting list, so there might be other candidates if I don't have the recipe for them or if they list another material first.

**Pull request merged**
