### PR TITLE
(WIP) Furniture Expansion 2: Lab and Hospital Furniture Expansion

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds a large amount of furniture for labs and hospitals, and other places"```

#### Purpose of change
There is a serious lack of lab and medical equipment in labs and hospitals. This stuff could eventually have specific purposes, but for now, it's decorative salvage.

Partially addresses https://github.com/CleverRaven/Cataclysm-DDA/issues/28187

#### Describe the solution
Adds the following furniture for use in labs and hospitals (updates *using* the furniture still pending)
- lab benches
- fume hoods
- incubator-shakers
- autoclaves
- sample freezers
- eyewash stations
- IV poles
- HPLC, mass spec, and NMR machines
- CT scanners and MRI machines, and special beds for going in them
- Electron microscopes
- Anesthetic machines
- Ventilator machines
- Paper shredders
- Water purifiers
- Air filters
- Server stacks
- Open and closed privacy curtains
- Dialysis machines
- Air compressors
- Dishwashers (good for labs, restaurants, and houses)

#### Describe alternatives you've considered
There is still a fair bit of stuff I haven't added, mostly vehicle type stuff like trolleys and toolbox carts.

#### Additional context
Depends on and builds on https://github.com/CleverRaven/Cataclysm-DDA/pull/28192

- [x] Add basic definitions, move modifiers, and required_str
- [x] Add descriptions
- [x] Create draft PR
- [x] Check ASCII text icons
- [ ] Add deconstruct and bash info
- [ ] Add unique items that may have been created for deconstruction
- [ ] Review flags and other details
- [ ] Test in-game

### CODE REVIEW

**Comment by curstwist** [comment]
thought I'd mention the ever ubiquitous water fountain, could be used in all public buildings.

**Comment by Night-Pryanik** [comment]
How should it be operated without electricity?

**Comment by I-am-Erk** [comment]
None of these work without electricity Night.

Water fountain is a pretty good call cursed twist. I'll see if I can work it in, it's basically a reskinned sink

**Comment by KorGgenT** [comment]
note: you'll want to rebase this. i took an extremely quick glimpse at the files changed and there were some oddities in there

**Comment by I-am-Erk** [comment]
Yeah, I'm just going to wait until part 1 is committed and then I'll redo this on a new branch

**Comment by I-am-Erk** [comment]
Closed in favour of https://github.com/CleverRaven/Cataclysm-DDA/pull/28662

**Pull request closed without merging**
