### PR TITLE
Spore add sundeath

### PR DESCRIPTION
**Pull request by MyculplantKatze**
#### Summary

SUMMARY: Balance "Added SUNDEATH flag to spores" 
#### Purpose of change

 Fix spore`s so that they dont duplicate during the day to slow down takeover and add some aggression to compensate
#### Describe the solution

Add SUNDEATH flag and turned aggression from -50 to 50, rather simple and effective way to control spore and mycus population
#### Describe alternatives you've considered

Adding more aggression to spores or force them to only grow using half life
#### Additional context

[Start of test](https://cdn.discordapp.com/attachments/365907426270117888/538594658222080025/unknown.png)
[After test](https://cdn.discordapp.com/attachments/365907426270117888/538594846991056897/unknown.png)
Ignore glow, solution was found during modding

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
It seems you have some unrelated changes in your PR. Please rebase on top of current master.

**Comment by Barhandar** [comment]
Aggressive spores makes no sense whatsoever, and fucks players over extra by spores now homing onto them (unless they already did that instead of floating aimlessly).

**Comment by l29ah** [comment]
Damn now spores are going to crash my vehicles' solar panels even faster.

**Comment by MyculplantKatze** [comment]
so if i remove the change to aggression all will be fine?

**Comment by kevingranade** [comment]
This is not a reasonable fix for fungal growth, the problem is that fungal spread only occurs when the player interacts with fungals, and it has a very high spread rate when that happens due to trying to make noticeable progress.

**Pull request closed without merging**
