### PR TITLE
Qualities tweaks

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add COOK 1 quality to awl pike and sharpened rebar.
2. Add BOIL 2 quality to empty canister, clay canister and clay bowl.
3. Add CONTAIN 1 quality to clay canister.

Other changes:
1. Remove knife action from awl pike.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
While we're at qualities, skewers should lose their cooking quality. They have 0 volume rendering all other cooking 1 tools useless for the purpose of cooking.

**Comment by John-Candlebury** [comment]
Skewers are a perfectly reasonable way of cooking small chunks of meat IRL though.

Which if I remember correctly is the only thing you can do with level 1 cooking.

**Comment by Coolthulhu** [comment]
Would skewers work with a campfire, though?

**Comment by Malkeus** [comment]
They'd work with with a hotplate and a small fire.

**Comment by Malkeus** [comment]
A fire for cooking and a fire for warmth are not the same. We could
abstract this away by saying the survivor moved a portion of the burning
fuel away from the main fire, in order to build a smaller cooking fire.

**Comment by Coolthulhu** [comment]
Hotplate could have that cooking 1 itself - it doesn't really need that skewer.

Though that kinda makes the whole cooking 1 free.
There is no real way to get meat without getting or passing up the opportunity to get a skewer.

**Comment by Malkeus** [comment]
Sure, you could cook the meat on the hotplate without the skewer, but
you'll probably burn your fingers trying to manipulate it and/or eat it.

**Comment by Malkeus** [comment]
Which isn't saying it should be a thing, but currently cooking is a
painless process

**Comment by Coolthulhu** [comment]
You could use any of that stuff in the inventory, for example that knife you used to create said meat.
The same knife could also be used as a skewer over a regular fire, with the exception of tiny (pocket knife) or flammable (glass shiv's rag handle) knives.

**Comment by Malkeus** [comment]
That assumes you still have all that available at the time of cooking. I'm
all for abstracting this all away and ignoring it as irrelevant...

**Comment by chaosvolt** [comment]
Hmm. I think it seems acceptable to allow skewers to have cooking of 1. We could make them eventually add up to some volume maybe. Then again, you're still liable to use a spear for the sake of it being a SPEAR, it having a cooking quality is just a nice bonus. XP

**Comment by Malkeus** [comment]
Just think how nasty that spear will be after killing a few zeds. There's
not enough soap and bleach on the planet...

**Comment by chaosvolt** [comment]
That's what the fire is for. X3

**Comment by Malkeus** [comment]
Not enough fire either... The spear head would melt and the shaft would
burn before I was satisfied that it was clean of zombie cooties. *shudders*

**Comment by chaosvolt** [comment]
So what, DF-style dragonfire instead? ;w;

**Pull request merged**
