### PR TITLE
Armored Car should have armor on doors

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by pisskop** [comment]
why?

If we armor doors for these, will we then armor humvee doors?

Doors are the weak points of a lot of these heavier vehicles

**Comment by l29ah** [comment]
On Fri, May 19, 2017 at 04:05:55PM -0700, pisskop wrote:
> why?

Because they're armored irl and don't have a reason not to be armored in the game afaik.

> If we armor doors for these, will we then armor humvee doors?

Yes, i didn't notice humvee lacking armor on doors as well.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by DangerNoodle** [comment]
The logical solution would be to armor humvee doors then.

**Comment by pisskop** [comment]
i maintain they are unarmored for gameplay reasons.  they give you a weak point and a reason to scavange for more plating

**Comment by DangerNoodle** [comment]
That would be a rather minor weakness though, as the doors have a reasonable amount of durability already. The windshields would potentially be a greater vulnerability, though this is mitigated by the windshields only being exposed when the vehicle is oriented diagonally, unlike the regular cars that have the windshield extend to the very edge of the vehicle

**Comment by DangerNoodle** [comment]
Actually scratch that, the armored cars actually use mundane doors which have 25 less durability than the reinforced windshields.

That said, an unarmored windshield would become more vulnerable than a reinforced windshield, which means that making armor car windshields extend full-width would add visual consistency while retaining some degree of vulnerability.

Note however than when I start to customize vehicles, I tend to take off the outermost windshields due to that extra exposure, in addition to armoring weak spots. I suspect other players that rely on up-armoring existing vehicles instead of making full combination vehicles would do this as well? This could serve the objective you are after of encouraging the player to invest in shoring up weak points, but both solutions might be tedium for players.

**Comment by pisskop** [comment]
zombie at your windshield cares not for your minor weakness.


he can reliably damage doors, not so much with armor padding

**Comment by DangerNoodle** [comment]
That does not address my suggestion.

**Comment by Zilenan91** [comment]
It's not even difficult to find two armored platings, just drive around for a while and rip it off a car with a toolbox, then just slap those suckers on. It's a whole different story for anything more than that, so armoring doors is fine.

**Comment by pisskop** [comment]
slap it on with batteries that you have to steal and a welder you have to make.

we made welding harder for a reason.  armored cars have (4) doors, and this is a major weakness of them.  the game follows the 'no armored doors' rule consistently.

why are we trying to further armor the _most_ _offensive_ vehicle in basegame, with its 2 turrets?

how many armored cars do you see in NE with guns mounted on them?  this pr isnt about realism

**Comment by kevingranade** [comment]
Had to do a rebase instead of merge, so it didn't auto-close.

**Pull request closed without merging**
