### PR TITLE
Cows/sheep give raw milk

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Cows & sheep no longer give pasteurized milk"```

#### Purpose of change
Fixes cows & sheep having pasteurized milk in their udders.

#### Describe the solution
Changed milk ammo_type in monexamine.cpp & sheep/cow starting_ammo to raw milk.

#### Describe alternatives you've considered
None.

#### Testing
image

#### Additional context
Original bug:
image

### CODE REVIEW

**Comment by tenmillimaster** [comment]
WDYM cows don't produce near boiling temperature milk?

**Comment by LaVeyanFiend** [comment]
The temperature they're set at is either 38C or 311C and someone forgot it wasn't in Kelvin?

**Comment by LaVeyanFiend** [comment]
image
That is the correct temperature.

**Comment by EldritchSigma** [comment]
So how does one turn raw milk into regular milk? Just curious.. assume theres a crafting recipe which involves heating.

**Comment by LaVeyanFiend** [comment]
Yes, you can boil milk at cooking 0.

**Pull request merged**
