### PR TITLE
Chemical recipes tweaks

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Change recipes to use heat source and CHEM quality instead of chemistry set: ammonium nitrate, acetic acid, aluminum sulfate, nitric acid, diesel, RDX, hydrogen peroxide (concentrated), dynamite.
2. Add lard and tallow to dynamite recipe.
3. Add diesel to ANFO recipe.
4. Add denatured alcohol to diesel recipe.
5. Add soylent green powder to medical mutagen recipe.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Add fire as a possible tool for making ethanol.

I'd say the fire omission was intentional. Distillation probably requires rather stable temperature.

**Comment by Darkyhard** [comment]
> I'd say the fire omission was intentional. Distillation probably requires rather stable temperature.

I think that using some kind of container already allows to get a stable temperature of something that is inside it.

**Comment by kevingranade** [comment]
It's not just a matter of isolating the heat source from the chemicals, you
just can't get the stable temperatures needed for distillation out of a
campfire.  This is going to be the case with a lot of chemical reactions.

**Comment by chaosvolt** [comment]
I would argue that a hotplate or chemistry set would work fine for that ethanol recipe. Just not fire.

Do we even HAVE any recipes that allow hotplates but not fire? While it might be sensible, it'd also be inconsistent if this recipe ends up being unique.

**Comment by Rivet-the-Zombie** [comment]
This might be a good time to add batch crafting time reduction to chemical stuff like lye - a lot of it never got batch crafting fully implemented.

**Comment by chaosvolt** [comment]
Ah, seems acceptable in that case.

**Pull request merged**
