### PR TITLE
add vehicle weapon mounts

### LINKED ISSUE #19206: Mounted Machine Guns Should Not Require Cutting Tools
Most machine gun mounts will utilize a quick release pin system of some sort. 

Please review the following. 

https://www.armyproperty.com/Resources/PS-Mag/2004-08/Vehicular%20Machine-Gun%20Mounting%20Systems.pdf

Search for M197 in the following document. 

http://www.liberatedmanuals.com/TM-9-1005-224-10.pdf

### PR DESCRIPTION
**Pull request by ymber**
closes #19206
fully implements weapon mounts and their ancillary code as started in #22747 

Tests are fixed, saves will be migrated, tankmod vehicles and items are updated. Guns can be removed from a weapon mount without tools. Installing or removing a mount requires standard fixed installation tools.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I find this kind of approach ungentlemanly. You take my work from a PR (not closed, not WIP!), add some of your work, and open your own PR. If you have something to say on matter of my PR, you can either say it in that PR, or wait for it to be merged or closed, and then open your PR with your developments.

**Comment by ymber** [comment]
#22747 is WiP with broken tests and no save migration as documented in that PR and it looked two months stalled. I redid it because I didn't expect results from telling other people to do work I could do.

**Comment by Night-Pryanik** [comment]
I repeat it once again: it is not WIP and it is not stalled. That PR is waiting for its review (there are PRs that are ready and waiting for review for almost a year).
I won't argue anymore, let the devs decide.

**Comment by Treah** [comment]
Ymber Night is right here. According to this https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md CR is code review. You should have reviewed the code saw problems and commented so that Night could comment back or make the changes. If you feel something is not moving you can always reach out to the person who own the PR. When you comment they usually get an email notification from github. 
I also agree with ymber that the last comment here is from Jan 16th and there was some comments on here but no movement, not even in the commits. One could argue its no longer being developed.  I know I am only a contributor here and I don't commit very much so in essence this is still only my opinion.

**Comment by illi-kun** [comment]
@ymber typically only first pr which solves the issue is going to be merged.

If some details of your implementation differs from #22747 then the most productive way to take them into account is to add some comments about that in the initial pr. I'm going to review #22747 within a few days (if no one will do this earlier), so it will be really helpful to start the discussion about proposed changes (if any are required per your point of view) before merge test. Thanks!

**Comment by kevingranade** [comment]
Please don't be territorial about changes.
Changes you make public can be adjusted and added to at any time and
resubmitted by anyone.
In practice this rarely happens, but we do occasionally have competing
implementations for fixes or features, and in general I'm going to merge
what I think is the better code with no concern for the "who" or "when" of
the submissions.

Do keep in mind you shouldn't squash commits from different authors.
IANAL, but I consider that authorship information to be protected by the
CC-BY-SA license.
One case where I will consider submission time or code proportions is when
a bountysource bounty is on the line, that complicates things.

**Comment by ymber** [comment]
@illi-kun Looks like my changes got copypasted into #22747 and improved since I wrote them. Only significant outstanding difference is the `break`s in vehicle.cpp.

**Comment by ZhilkinSerg** [comment]
Closed in favor of #22747.

**Pull request closed without merging**
