### PR TITLE
Prevent monsters from leaping to their death in water

### LINKED ISSUE #38038: Cougars leap into deep water and drown
As stated above. To reproduce just sit in a boat in deep water with a hostile cougar nearby, sail out if it gets too close. Should die within a few turns. This probably happens with other leaping wildlife, too. Cougar makes no attempt to get back to land.

# Screenshots

bravecat

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Bugfixes "Prevent monsters from leaping to their death in water"```

#### Purpose of change
Fixes #38038 by preventing monsters that could drown from leaping into drownable terrain.

#### Describe the solution
I refactored the die_if_drowning method to separate out a method (is_aquatic_danger) that defines terrain that would drown a drownable monster. In the leaping code, I consider a square unleapable if it would drown the leaper, and prevent leaping.

This refactor removed some redundant code checking for TFLAG_DEEP_WATER before doing the die_if_drowning checks and encapsulated it in hopefully a better way.

#### Describe alternatives you've considered
Should leaping animals always know that they would drown? I decided yes, because they won't willingly walk to their death, but the alternative of allowing some version of the existing behaviour was considered. It didn't seem appropriate, unless there is some case where monsters do this that I'm not aware of.

#### Testing
I couldn't figure out how to make cougars reliably hostile while on the shoreline! My testing was with evolved mutants, who also have the Leap attack and are hostile.

I tested before and after, and before, an entire group of evolved mutants leaped to their death when I was on a motorboat just off the shore.

Afterwards, I verified that they did not leap directly into the water. I tested that they would leap if their target was on my boat, which they did occasionally:

sc001344

(Note the dead monsters in deep water are almost exclusively from the "before" save.)

#### Additional context
When I did have a boarded mutant on my boat, the mutant behaviour was a bit strange but I am quite certain it was not related to this change -- I just think that boarded walkers on boats don't navigate as expected. The mutant was shaking the boat but wasn't charging me. It looks like there is a navigation issue with walkers on boats over deep water? I think there's a separate issue here if someone wants to improve the behaviour of walkers on boarded boats.

### CODE REVIEW

**Comment by Funguss** [comment]
Hell yeah, nice one! Regarding boat pathing it seems to be a symptom for all creatures in vehicles over deep water. I could leave my horse untied if I positioned the boat so the horse was surrounded by deep water tiles. Taking a horse for a boat ride is pretty weird anyway, but that's beside the point. I imagine dogs would behave the same, too.

**Comment by Sumguy62** [comment]
But cougars can swim really well...

**Comment by ZhilkinSerg** [comment]
You've changed filemode for some files:

image

**Comment by jkraybill** [comment]
@ZhilkinSerg sorry no idea how that happened, definitely wasn't intentional :( Reverted.

**Comment by jkraybill** [comment]
@Sumguy62 that's actually a good point, there is definitely room for improving aquatic behaviors but it's not the scope of this PR, I'd encourage opening an issue if you want to see more realistic cougar/other animal behavior!

**Pull request merged**
