### PR TITLE
Make `RUBIK_ANUS_FETICK` mission refer to units, not liters

### PR DESCRIPTION
**Pull request by DeeUnderscore**
#### Summary
None

#### Purpose of change

Currently, the mission where Rubik asks you to fetch some anesthetic asks for 1 liter of anesthetic. However, 1 liter of anesthetic is something like 778 charges, while [the actual requirement is 1000 charges](https://github.com/CleverRaven/Cataclysm-DDA/blob/e36ba857eea5250de4aa1da0c789e34909d09163/data/json/npcs/exodii/exodii_merchant_talk.json#L164). 

#### Describe the solution

Change dialog and mission description to have Rubik ask for 1000 units of anus feticks instead. 

#### Describe alternatives you've considered

I think "units" is a sufficiently medical-sounding term to use here. Rubik could perhaps have some more colorful description, but I think this one is good enough. 

#### Testing

Loaded the modified JSON in game and ran through the conversation.

#### Additional context

N/A

### CODE REVIEW

**Comment by ANickelN** [comment]
Why not change the actual requirement to 778 charges (1 Liter) instead of doing it the other way around?  

It seems changing the text to match the requirement makes less sense than fixing the requirement so it fits the text?

**Comment by DeeUnderscore** [comment]
The volume of a liquid you're carrying is more tricky to figure out than the amount of charges, since you need to descend into menus/descriptions to see it. It's also possible to set your game to display volume in units other than liters. I think things are generally clearer if the game asks for a number of charges and doesn't ask the player to do math.

**Comment by Maleclypse** [comment]
If 776 charges is one liter then 100 charges is roughly equal to a gill. https://en.wikipedia.org/wiki/Gill_(unit)

**Comment by AtomicFox556** [comment]
Seems like a good opportunity to show the complications of coming from different worlds: the measurement units won't ever completely match up, so I would expect medical knowledge of the player character to help figuring out how much is actually needed in terms of in-game units, otherwise Rubik could just say that they want more if you bring too little.

**Comment by pjf** [comment]
> Seems like a good opportunity to demonstrate the complications of coming from different worlds: the measurement units won't ever completely match up.

This is especially the case if there are different timelines involved. From Wikipedia:

> The original French [metric system](https://en.wikipedia.org/wiki/Metric_system) used the litre as a [base unit](https://en.wikipedia.org/wiki/SI_base_unit). The word litre is derived from an older French unit, the [litron](https://en.wikipedia.org/wiki/Units_of_measurement_in_France_before_the_French_Revolution#Volume_%E2%80%93_Dry_measures), whose name came from Byzantine [Greek](https://en.wikipedia.org/wiki/Greek_language)—where it was a unit of weight, not volume—via Late Medieval Latin, and which equalled approximately 0.831 litres.

However if the Exodii can provide blueprints the player can make sense of, then I'm ken they can provide a precise volume/quantity when giving a quest, even if that's just by supplying/pointing to a container of the appropriate size.

**Comment by PatrikLundell** [comment]
Whether the PC may or may not know how many of one units there are in another unit is not particularly relevant, as the PC doesn't have any ability to communicate with the player. Checks in dialogs can transfer some info, but only if that dialog has actually been written.
Also, the game's normal units are either 250ml or 1 ml for fluids. There's no indication to the player that this particular fluid uses some unit other than one of these, so you'd only find out if you fiddle around with the UI AND pay close attention to things you have no reason to pay special attention to.

**Comment by DeeUnderscore** [comment]
Yes, the main issue right now is that the conversation option for "here's the anesthetic" only becomes available if you have 1000 charges of it in your inventory. If the player brings less than that, there is no indication that it's not enough, no matter how many conversation trees they go through looking for that. If confusion about the amounts is to be relevant to the plot then ideally it should be clear that it is an in-universe thing, and not some bug that stops the mission from going through. 

And yes, we could have dialog in which determining the actual amount goes on, depending on the player's character skills, but there's also the mission description, and ideally that'd reflect whatever conclusion was reached through the conversation tree. I don't know if mission descriptions can be conditional like that, so we'd need multiple missions... But then we'd also need to handle what happens when the player character actually increases their skills in the meantime, and theoretically should now be able to figure out the exact amount.

That isn't to say that it's impossible to have a more complex handling of this situation, but it that *would* be more complex.

**Review by Maleclypse — APPROVED** [review]
I’m going to side with clarity of mission over thematic value since there is significant content potentially gated by this mission.

**Pull request merged**
