### PR TITLE
Adds weakpoints for the kevlar zombies

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Bugfixes "Adds weakpoints to the kevlar zombies"

#### Purpose of change
Kevlar zombies didn't have weakpoints, someone on discord made it arrive at my attention so I decided to add some.

#### Describe the solution
Adds weakpoints to the kevlar zombies based in the zombie soldiers weakpoints, with the understanding that their main armor is on the chest where the kevlar vest should have been, and that its hide is slowly covering everything with pieces of kevlar, but the limbs and head is not as well protected because of the distance from the chest and the softer (or none) armor those places had.

Edit: I changed the weakpoints and just used the ones @I-am-Erk is implementing in the PR mentioned in the comments, as well as adding a new effect that is used by the new weakpoints.

#### Describe alternatives you've considered
To not do it.

#### Testing
Spawned the monsters in game, attacked them several times, their weakpoints work.

#### Additional context
imagen

### CODE REVIEW

**Comment by casswedson** [comment]
Erk also added some weakpoints to these monsters and many others in #52084

```json
...
    "armor_cut": 25,
    "armor_bullet": 20,
    "bleed_rate": 50,
    "weakpoints": [
      {
        "name": "an unarmored part of the leg",
        "armor_mult": { "bullet": 0.5, "cut": 0.5, "stab": 0.25, "bash": 0.25 },
        "crit_mult": { "all": 0.75 },
        "difficulty": { "ranged": 2, "melee": 1 },
        "coverage_mult": { "point": 0.75 },
        "effects": [ { "effect": "downed", "chance": 25, "message": "The %s is knocked down!", "damage_required": [ 15, 100 ] } ],
        "coverage": 8
      },
      {
        "name": "the arm",
        "armor_mult": { "bullet": 0.5, "cut": 0.5, "stab": 0.25, "bash": 0.25 },
        "crit_mult": { "all": 0.75 },
        "difficulty": { "ranged": 2, "melee": 1 },
        "coverage_mult": { "point": 0.75 },
        "effects": [ { "effect": "staggered", "chance": 25, "message": "The %s is knocked off-balance!", "damage_required": [ 10, 100 ] } ],
        "coverage": 8
      },
      {
        "name": "the armpit",
        "armor_mult": { "bullet": 0.3, "cut": 0.3, "stab": 0.15, "bash": 0.15 },
        "difficulty": { "all": 3 },
        "coverage_mult": { "ranged": 0.1 },
        "coverage": 1
      },
      {
        "name": "the weak armor on the side",
        "armor_mult": { "bullet": 0.3, "cut": 0.3, "stab": 0.15, "bash": 0.15 },
        "coverage_mult": { "ranged": 0.65 },
        "coverage": 4
      },
      {
        "name": "a gap in the stomach armor",
        "armor_mult": { "bullet": 0.5, "cut": 0.5, "stab": 0.25, "bash": 0.25 },
        "coverage_mult": { "broad": 0.5 },
        "difficulty": { "ranged": 4, "melee": 1 },
        "coverage": 4
      },
      {
        "name": "the face",
        "armor_mult": { "physical": 0 },
        "crit_mult": { "all": 1.1 },
        "difficulty": { "melee": 1, "ranged": 3 },
        "coverage_mult": { "ranged": 0.75 },
        "coverage": 3,
        "effects": [
          {
            "effect": "stunned",
            "duration": [ 1, 2 ],
            "chance": 5,
            "message": "The %s is stunned!",
            "damage_required": [ 1, 10 ]
          },
          {
            "effect": "stunned",
            "duration": [ 1, 2 ],
            "chance": 25,
            "message": "The %s is stunned!",
            "damage_required": [ 11, 100 ]
          }
        ]
      },
      {
        "name": "the eye",
        "armor_mult": { "physical": 0 },
        "coverage": 1,
        "crit_mult": { "all": 1.25 },
        "coverage_mult": { "ranged": 0.5 },
        "difficulty": { "point": 4, "broad": 6 },
        "effects": [
          { "effect": "blind", "duration": [ 1, 2 ], "chance": 25, "message": "The %s is blinded!", "damage_required": [ 1, 25 ] },
          {
            "effect": "blind",
            "permanent": true,
            "chance": 30,
            "message": "The %s's eyes are obliterated!",
            "damage_required": [ 26, 100 ]
          }
        ]
      },
      {
        "name": "the neck",
        "armor_mult": { "physical": 0 },
        "difficulty": { "melee": 1, "ranged": 2 },
        "coverage": 1
      }
    ],
    "vision_day": 30,
    "vision_night": 35,
...
```

**Comment by Termineitor244** [comment]
> 
> 
> Erk also added some weakpoints to these monsters and many others in #52084

Oh, good! But then... Should I close this PR? I have been waiting for that PR to be merged but its still in a draft since some time ago.

**Comment by Termineitor244** [comment]
I unceremoniously copied and pasted the weakpoints that Erk made, I thought of closing the PR but I don't know how much time Erk will take to finish its PR, and the kevlar zombies are one of the most armored opponents in the game so they really need some weakpoints...

**Comment by I-am-Erk** [comment]
I've been incredibly busy, so doing this until I have a chance to catch up is fine. That PR has largely been stuck because I think we really do need some weakpoints modularity system.

**Pull request merged**
