### PR TITLE
Jsonify office tower

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary

SUMMARY: Content "Jsonify office tower."

#### Purpose of change
Continuation of hardcode-to-json project.

#### Describe the solution
- Converted hardcoded function into json variant with several adjustments here and there. It's essentially the same version as before, with the major tweaks being: replacing old `office`, `cleaning` and some other item groups with their modern `SUS_` counterparts; changed layout of the underground parking; converted old unusable elevator into usable ramp (just like in `Large Office Tower` location).
- I see no reason for this location to be spawned **only** during the `Find Corporate Accounts` mission. So I added this location to the list of normally-spawnable city buildings.
- Added migration stuff.
- Deleted hardcoded function for good. 

#### Describe alternatives you've considered
None.

#### Testing
Debug-spawned location to check if everything's okay.

#### Additional context
Ground floor
изображение

Underground floor
изображение

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Great work.

**Comment by curstwist** [comment]
Maybe make this variant all concrete walls?  I made the large ones all brick when I fixed the parking garage.  This way we'd get some variety and they'll stand up better to large zombie groups.

rock_wall or adobe_brick would also be pretty nice but concrete will be more modern.

**Comment by Night-Pryanik** [comment]
> Maybe make this variant all concrete walls?

I thought about this too. I just decided to make minimum-differences version. Though I'm not attached to the simple `wall` wall, so ok, I'll convert to concrete walls.

**Comment by curstwist** [comment]
> 
> 
> > Maybe make this variant all concrete walls?
> 
> I thought about this too. I just decided to make minimum-differences version. Though I'm not attached to the simple `wall` wall, so ok, I'll convert to concrete walls.

I've been on a side quest to remove all unpainted t_walls (unless we have a place under construction).  As a result, I've mostly assumed all t_wall_[color] types are closer to interior dry-wall.  It makes me want to revisit all the commercial buildings one day to deal with their exteriors.

**Pull request merged**
