### PR TITLE
[Magiclysm] Update goblin teeth and lizardfolk muzzle to techniques

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Update goblin teeth to techniques"

#### Purpose of change

Inspired by #72082, update goblin teeth to have an integrated item that provides a  "Goblin Bite"  technique, and give lizardfolk their own bite. 

#### Describe the solution

Remove the hardcoded attack and replace it with integrated `goblin teeth`, which provides the `FANGS_BITE_GOBLIN` technique. It has a higher weighting (-3 instead of -5) and better scaling  (about 10% better) but lower base damage than the FANGS mutation, because unlike a mutated human, goblin mouths are actually designed for biting. At higher Unarmed it will be better than fangs, but at lower levels it's worse (about a third worse).  

Also, swap out lizardfolk's use of `MUZZLE_LONG` for a custom one so they can have techniques with the same scaling as the goblin teeth.

#### Testing
image

Goblins' bite does not do a lot of damage, but they're fast and very small, so they can dodge around and bite people and nip them to death.

Lizardfolk are big and hulking and tear chunks out of their prey. They're a strong unarmed start, but they can't comfortably wear most human-made armors, can't wear gloves, can't wear helmets, etc, so their strong natural weapons are most of what they get. Also, apparently lizardfolk's giant webbed feet did not prevent them from wearing human shoes, so I added `"restricts_gear": ["foot_l", "foot_r" ]` as well (they already have the TOUGH_FEET flag and their trait even says "However, your feet are not designed for human footwear").

#### Additional context

Goblins sure are dodgy.

Currently lizardfolk get additional benefit from their tail attack, but tail is a prime candidate for "this will be a limb body part" so I'm not messing with it.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
It's a mod so do what you like, but if you refer to game_balance.md, it outlines how to adjust damage on mutation attacks. The current scaling is set up to match a stabbing weapon as closely as is possible in json, and it's intended that future attacks only adjust the base damage and/or base attack speed. Otherwise the attacks are going to be super inconsistent and will get worse over time as people copy/paste them.

**Comment by Standing-Storm** [comment]
I did read game_balance.json, but I do think it's worthwhile to have a distinction between attacks from mutant adaptions of human anatomy caused by mad science and attacks from beings with a different physiology than humans who are more adapted to that physiology than a mutant will ever be to theirs. A better solution then would be to change lizardfolk's muzzle (and any future similar attacks, like ravenfolk pecking etc) over to the slightly better scaling, make that better scaling consistent, and put a note in every non-human technique that this is a technique based on fantasy species anatomy and should not be adapted to humans.

People might still mindlessly copy it but at least then they'll mindlessly copy the note about how it's supposed to work.

**Comment by Kolrath** [comment]
Unsure if this is the correct place to report this or not, but I don't believe the Lizardfolk Talon / Muzzle mutations are working correctly. The tail mutation attacks are working as whether in unarmed or armed combat as long as directly adjacent to an opponent I regularly see log messages indicating that the enemy got "whapped" for ~3-8 damage from my tail. Never seen a single message regard either the talons or the muzzle. Dug around in the JSONs and it seems like there should be messages about biting / tearing into and clawing the enemy, but those never occur.

Aside from just regular gameplay I did some dedicated testing using the latest (as of 1/20/2025) experimental version "cdda-windows-with-graphics-and-sounds-x64-2025-01-20-1720". 
For testing I made a character with 20 in all attributes, maxed Dodge skill, and 4 Unarmed skill. Picked the "Lizardfolk" species / Scaled One background. Everything else was default starting options.
Used Debug menu and spawned in various enemy types (zombie, human, and animal) and fought them in unarmed combat and never noticed anything aside from punches, kicks, headbutts, and tail whaps in the combat log.

I know the mod "Martial Mastery" does some stuff with the way techniques work and allows you to custom build your own martial arts style with points as you gain XP and I figured that might in some way be interfering so I did testing (with the setup described above) using worlds with and without the "Martial Mastery" mod enabled. In all cases the results were the same. Only the tail attack from the Lizardfolk seems to occur. The muzzle and talon mutations don't seem to trigger.

The talons and muzzle do show up in the mutation listing and inventory. Their other functionality seems to be working as well in that you can butcher and cut up items with them. They also hinder / prevent equipment usage. It just seems to be the attacks themselves which aren't working which is a shame as that is the primary bonus of having them.

Hope that helps in some fashion. Aside from this I'm loving the lizardfolk. Gives an interesting way to play the game so far.

**Comment by Standing-Storm** [comment]
The problem seems to be that they're refusing to bite for some reason. The talon attacks do occur (it's just listed in the log as a punch--if you punch someone for 25+ damage as a lizardfolk, it's you clawing them, since normal punches do like 2-5 damage), but the bite doesn't seem to happen at all.

**Pull request merged**
