### PR TITLE
WIP: Change generic "shot" to 12 Gauge

### PR DESCRIPTION
**Pull request by carmakazi**
#### Summary

```SUMMARY: Content "Change generic "shot" to 12 gauge"```

#### Purpose of change

Earlier in development, referring to 12 gauge shells simply as shotgun shells/shot was likely sufficient.  Now that the game has many distinct ammo types, notably the .410, I believe it is time to call 12 gauge by its proper name.  It definitely is quite a pain to track down every reference to the old IDs for little gain, and I assume that is why it hasn't been done yet, but I'm happy to get it over with before the scope of work becomes even greater with time.

#### Describe the solution

Changes done so far:
-Change the ammo file name from "shot" to "12ga"
---All ammo IDs within to use "12ga" instead of "shot."  Ex. "12ga_00" instead of "shot_00"
---Item names to use "12 gauge"
---Some description revisions
-Migrate all ammo to new IDs
-Ammo_type from "shot" to "12ga"
-Gun file name from "shot" to "12ga"
---12 gauge pistol ammo type to "12ga"
---Magazine type of compatible shotguns to "12ga"
-magazine file from "shot" to "12ga"
---All mag ammo types to "12ga"
-Item_group entries to "12ga"
-Paper_shot reference to "12ga"
-CHANGE NEEDED: Recipe file name to "12ga"
---Recipes changed to new IDs
-Generic Guns reference and migration support
-Professions use new IDs
-Change to new IDs in mapgen
---Military base

Likely culprits for current errors:
-load-bearing gear such as the bandoliers
-other mapgen items

#### Describe alternatives you've considered

Not being anal about terminology.
or
Simply changing the names of the items while leaving the IDs and file names be.  I thought if I was going to go through the trouble, it would be better to be specific with the item IDs for clearer identification, and in case the base game or a mod wanted to add additional shotgun ammo types.

#### Testing

In progress, searching out the remaining references to the old IDs and other bugs, currently loading this PR will crash to main menu.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I'm happy to see someone working on this, seeing the generic shot always made me slightly sad before and this opens up having more shotgun gauges in the future with less confusion.

**Comment by tenmillimaster** [comment]
I do not feel that it is necessary to change the ID's, that just results in a bunch of migration entries.

**Comment by ZhilkinSerg** [comment]
Needs conflict resolution.

**Comment by ZhilkinSerg** [comment]
Closing to clean up PR queue. Feel free to resolve conflicts and reopen.

**Pull request closed without merging**
