### PR TITLE
Add the Chiappa Rhino

### PR DESCRIPTION
**Pull request by BalthazarArgall**
#### Summary
Content "Add the Chiappa Rhino"

#### Purpose of change
The Chiappa Rhino technically meets the standards for inclusion but isn't in the game despite being the most awesomest looking revolver after the Mateba Unica.

#### Describe the solution
The most common version of the Rhino is the 60DS in .357 so this is the version that will be added to the game. The technical specs for this version have been retrieved and implemented as faithfully as possible.

The spawn rates have been based off the ones for the Manurhin (`mr73`).

#### Testing
Spawned the gun, wielded it.

#### Additional context
Screen of the gunbroker search: (Apparently I'm supposed to include closed sales but I ~~don't know how~~ can't because I live in Europe)
Untitled
Image of the item for context:
ADP760

### CODE REVIEW

**Comment by Kantonine** [comment]
Hmmm, this might seem a stretch, but how common is the 9x19mm version, is it comparably common to the .357, or is it too nice to be able to pass the inclusion standard?

**Comment by Kantonine** [comment]
oh, and another point, would it be easily implementable to have a multi length barrel system for these? I.e. have a barrel mod that adds additional length onto the barrel, or would that mean having the basic gun have 0 barrel length, and the mod being bore based like the MDRX system?

**Comment by BalthazarArgall** [comment]
> Hmmm, this might seem a stretch, but how common is the 9x19mm version, is it comparably common to the .357, or is it too nice to be able to pass the inclusion standard?

The 9x19 version is rarer than the .38, I cannot make a "proper" gunbroker search but if you can find >100 hits for a 9x19 version I'd be happy to implement it.

> oh, and another point, would it be easily implementable to have a multi length barrel system for these? I.e. have a barrel mod that adds additional length onto the barrel, or would that mean having the basic gun have 0 barrel length, and the mod being bore based like the MDRX system?

Nope, Rhinos don't officially support changing the length of the barrel. There may be a way to do this as a gunsmith but I'd need proof before I make it possible.

**Comment by Kantonine** [comment]
That's perfectly understandable! Maybe just have a reg size and then a snubbie version? As for the Gunbroker search, me being the UK means doing that wouldn't be exactly advisable

**Comment by BalthazarArgall** [comment]
> That's perfectly understandable! Maybe just have a reg size and then a snubbie version? As for the Gunbroker search, me being the UK means doing that wouldn't be exactly advisable

Well, I'm implementing it like this for the time being, if you find a way to prove that there's a significant number of 9x19 Rhinos out there in New England **hit me up and I'll implement the version myself**, and I do mean it.

**Comment by BalthazarArgall** [comment]
Sorry for the back and forth, I was a bit confused with the generic naming and gun items architecture

**Pull request merged**
