### PR TITLE
Correct Ankle Hostler recipe

### LINKED ISSUE #31622: Holsters crafting component choice unbalanced
# Describe the bug

The various crafting recipes for holsters have a lopsided choice when it comes to string vs thread.  Ex: Quickdraw holster.  Choose between **20 thread** or **2 long strings** (2 long strings can be freely converted to 600 thread)

# Steps To Reproduce

View holster crafting requirements

# Expected behavior

The resource choice between thread or string should be closer than 1 to 30

# Screenshots

resources

# Versions and configuration

OS: Windows 10.0 1809
Version: 0.D-4578-gf477339 [64-bit]
Graphics: Tiles
Mods: Dark Days Ahead [dda], Disable NPC Needs [no_npc_food]

### PR DESCRIPTION
**Pull request by TechyBen**
As per report #31622

#### Summary

```SUMMARY: Balance "Correct Ankle Holster recipe"```

#### Purpose of change

Fixes #31622 - Now 600 thread instead of 20.

#### Describe the solution

Changed thread amount to match long string requirements.

#### Describe alternatives you've considered

Leaving as is, or using small strings instead.

### CODE REVIEW

**Comment by SirPendrak** [comment]
I think its not the right way of ballancing this item. 600 thread is a lot, over twice as much as some full body suits require. Crafting sometimes have optional choices that are less than optimal, but it does not mean that some time later base resources should be adjusted to theese not-optimal options. 
I think this long string version was for someone who has tons of strings, and dont want to waste time to dissasemble them.

**Comment by TechyBen** [comment]
Sounds reasonable. So it's anything of length. Long string being long enough, but overly strong compared to 20 thread. Question is, is 20 thread enough? Seems very low and fragile if going off most types of thread, I'd expect belt like strength for a holster. So rope/string at the least.

Let me know, as I'm browsing through the json for what other crafts might need a little more string/thread.

**Comment by faefux** [comment]
How much thread is 1 thread, exactly?
Sorry if dumb question, i just think it's important reference to have to consider both this question and writing recipe's and items in the future.

**Comment by TechyBen** [comment]
Thinking about it. The strength in this case is in the leather, not the binding material of the thread or short string. My bad. I was imagining it working as a belt, when it attaches to a belt (though for CDDA the game does not require one).

That's where my confusion was, thinking it was holster + belt. It's just the holster.

**Pull request closed without merging**
