### PR TITLE
Revert "Moved light and heavy snare kits to More Survival Tools mod"

### PR DESCRIPTION
**Pull request by Night-Pryanik**
This move wasn't so easy as I imagined. The game generate errors on start complaining that it couldn't find snares without MST mod.

### CODE REVIEW

**Comment by BevapDin** [comment]
Or you could just remove the references to the snare traps from the C++ code. As far as I can see, it's only used for the variables `tr_light_snare` and `tr_heavy_snare`. Remove the declaration, definition and initialization of them (6 lines in total) and it should be fine.

**Comment by Night-Pryanik** [comment]
But then the snares won't be working in MST?

**Comment by BevapDin** [comment]
> But then the snares won't be working in MST?

Those variables are not used at all, it doesn't matter whether they are there or not. The snares will work just like before.

**Comment by Night-Pryanik** [comment]
Okay, will make a new PR to address the issues later today.

**Comment by ZhilkinSerg** [comment]
#22644

**Pull request closed without merging**
