### PR TITLE
Innawood & TropiCataclysm made compatible

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Mods "Innawood & TropiCataclysm made compatible"

#### Purpose of change
Makes Innawood and TropiCataclysm compatible.
Makes both mods simpler and easier to maintain.
Makes it easier for other mods to be compatible with both mentioned mods.

#### Describe the solution

Change Innawood and TropiCataclysm to use region_overlay instead of region_settings.
Tagged all relevant map_extras with MAN_MADE, so that Innawood doesn't have to bother filtering out map_extras in the region_overlay.

Previously, mainline had the following code
`"t_grass": 12, "t_grass_dead": 2, "t_dirt": 1`
And Innawood had the following code, in order to add the occasional sand
`"t_grass": 12000, "t_grass_dead": 2000, "t_dirt": 1000, "t_sand": 1`
Now, instead, mainline has the following code
`"t_grass": 12000, "t_grass_dead": 2000, "t_dirt": 1000`
And Innawood has this code
`"t_sand": 1`
This is an ugly hack to make the mod interactions work seamlessly. TropiCataclysm can then alter the same field to read
`"t_grass": 20000, "t_grass_dead": 1000, "t_grass_long": 15000, "t_grass_tall": 10000, "t_dirt": 1000, "t_shrub": 1000, "t_underbrush": 1000` to alter the distribution of things to the way TropiCataclysm wants them to be, while still also allowing the occasional patch of sand when Innawood is also included in the world.

Similar solutions have been done for t_region_groundcover_swamp, f_region_weed, f_region_plain, f_region_forest, and f_region_forest_dense.

Added overmap_location "desert" as a placeholder terrain, and made roads pass over them as easily as they do plains. Removed the code from TropiCataclysm that does this. This allows Innawood to override road behaviour.

#### Describe alternatives you've considered
A bridge mod that deals with making the mods work together. The advantage is that code in mainline is not messed up for the sake of two mods working together. The disadvantages are more clutter in the mod menu, and players might forget to enabling it when creating a new world where it should be enabled, leading to confusion and frustration.
The suggestion from #48589 would let me make the mods play together without having to alter mainline. It would however require greater understanding of the C++ code to implement than I currently have.

#### Testing
Needs to be done. This should not have altered how the mods play on their own. But the changes are rather large, and it's possible that I messed up somewhere and broke something.

#### Additional context
I'd like to hear your opinion on if you think a bridge mod would be a better solution, or if you could come up with a better solution.

This is blocked by the problem that region_overlay can not deal with weather.
image

### CODE REVIEW

**Comment by NetSysFire** [comment]
CC @Xaritscin

**Comment by NetSysFire** [comment]
Also you missed the opportunity to name your branch/project innajungle

**Comment by Light-Wave** [comment]
I was gonna name it Innatropicalwood, but Innajungle is better.

**Comment by Xaritscin** [comment]
I dont see why not. the old Desert Region files are something i've been trying to get rid of because i dont know how to include desert terrain into the map to spice it up. so if it has to be deleted then no problem with that.

still on hiatus until 0.G so if someone wants to contribute go ahead, this mod isnt solely mine anymore its part of the repo after all.

**Comment by Light-Wave** [comment]
With #60401 finished, the mods are compatible as long as TropiCataclysm is loaded before Innawood. Good enough.

**Pull request closed without merging**
