### PR TITLE
medisoft practice recipes

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Content "practice health care with MediSoft and a computer"

#### Purpose of change
The only way to learn health care was by spamming about 6000 bandages. I wanted to change that.

#### Describe the solution
Now you use the MediSoft USB and a laptop, and can practice 3-10 this way. This may be too extreme, but it can be toned down later when health care stops being the "bandaging skill" and nothing else. "MediSoft" is vague as to what it is but I'm treating it as training software for med students which you'd use to teach yourself how to deal with complicated injuries.

#### Describe alternatives you've considered
You use your adhesive bandage (x132)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Practice up to level 10 using the same "training recipe" is definitely extreme. In most cases (where there even are practice recipes available) it seems you can get up to level 5 or so using practice recipes. Most practice recipes also consume resources.

**Comment by irwiss** [comment]
it already wastes most precious resource - time, if you have no actual wound that soaks bandages in body fluids there's no reason you can't roll up the bandage and reuse like in any irl first aid instructor does

perhaps make 4+ require more tools like tourniquets, splints, nearby npc or body doll and such but i don't see a reason to magically waste any of it just to make gamified resource scarcity

**Comment by Venera3** [comment]
The solution to "bandaging gets you up to 10 healthcare" isn't "add Medicine for Dummies", it's to add a low ceiling to bandaging's skill training. Learning medicine beyond the simple hands-on level isn't a reasonable goal in the postapocalypse.

**Comment by anoobindisguise** [comment]
advices noted. medisoft is now just training 3-6.

**Comment by Venera3** [comment]
You're not learning anything actionable from a program you couldn't from a book, that's just not how this works - just like you're not learning anything useful from dissecting a corpse or burning cough syrup, both of which came up as potential healthcare practice recipes. 

The wound care practice (and bandaging in general) training healthcare is not how it should work, but piling on more until it gets revamped is not the way to go.

**Comment by anoobindisguise** [comment]
> You're not learning anything actionable from a program you couldn't from a book, that's just not how this works - just like you're not learning anything useful from dissecting a corpse or burning cough syrup, both of which came up as potential healthcare practice recipes.
> 
> The wound care practice (and bandaging in general) training healthcare is not how it should work, but piling on more until it gets revamped is not the way to go.

How do you envision practicing medicine for the future?

**Pull request closed without merging**
