### PR TITLE
Fix NPC head explodey when they leave / reenter reality bubble with an activity

### LINKED ISSUE #35586: NPCs deconstructing vehicles explode from infinite loop
# Describe the bug

I told 2 NPCs to deconstruct vehicles in VDZ (armored car and flatbed truck). When I return from supply run, they get their brains exploded because they went into infinite loop.

# Steps To Reproduce

-load attached save;
-press "5" 7 or 8 times so you'll drive into  tile adjacent to shelter where VDZ is
-get error messages and exploding brains.

**Edit** - if you stop the vehicle and go there on feet they are fine and they just follow you around, not deconstructing. Maybe something with vehicle headlights lighting their work area?

# Expected behavior

NPCs not getting into loop and getting their brains out for the zombies to feast on.

# Versions and configuration

- OS: Windows 7 x64
- Game Version: 0.D-9483-ga3b0f0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Happened on 9901, updated to 9911, same thing.

[crash-debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3858819/crash-debug.zip)
Save file was too big for attaching so here's [the link](https://drive.google.com/file/d/1OWGrzboIAwmRGdABeeMPS8pru-J81PDM/view?usp=sharing)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix NPC head explodey when they leave / reenter reality bubble with an activity"```

#### Purpose of change
Fixes #35586 

#### Describe the solution
There are two bugs ive fixed.
1) from the attached issue - a discrepancy in the light level when NPC starts assessing tiles, and when they travel there, caused by the headlights of the car in the linked issue save - added some handling for differing light levels to stop NPCs constantly looping.
2) also fixed the long-standing bug where if you walk away so the NPC leaves the reality bubble while NPCs are doing an activity, then come back, sometimes the target of the activity will not be loaded, so the NPC tries to perform the activity on an out of bounds target, causing an infinite loop. to fix this ive stashed the activity when the target tile leaves bubble, and restore it when the target tile re-enters bubble.

#### Describe alternatives you've considered
N/A
#### Testing
I tested on a tree chopping activity, walked away ( in the specific direction that would cause the tree to unload before the NPC does ) then walked back, there was one turn where the NPC was loaded and the tree was not, for that turn they paused, the next turn, the tree was loaded, and they resumed the activity properly. 

I tested the attached issue savegame, and that is now fixed properly.

I did not test further on the leaving-bubble fix, for other activity types, or other permutations, as I need to sleep now, I will test further tomorrow, hence WIP for now, but code ready for review essentially.

#### Additional context
N/A

### CODE REVIEW

**Comment by Funguss** [comment]
Brilliant! This might have an impact on NPCs deciding that they've completed all construction they can due to light levels, too. I'll have a play when it gets merged and see.

**Comment by davidpwbrown** [comment]
confirm new dpwb account is me ( sorry for using this PR as the place for this, will delete in a moment )

**Comment by davidpwbrown** [comment]
Tested with other activities now - vehicle deconstruction/repair, butchering, constructing etc.
In all cases, walking away so the NPCs activity target unloads before it does, or walking back towards the NPC so they load before their activity target does - results in no more head exploding or infinite loops or errors.  Consider this ok now.

**Comment by Funguss** [comment]
Nice! Is it possible to have them "catch up" by simulating the time they've been unloaded? Or would that cause a bit too much lag?

**Comment by davidpwbrown** [comment]
> Nice! Is it possible to have them "catch up" by simulating the time they've been unloaded? Or would that cause a bit too much lag?

This should happen automatically - NPCs get moves given to them in one go when they are re-loaded, so they should have a backlog of moves to work through which would do more activity turns for them. 

Except in the case where they are re-loaded but the activity target isnt there, they would then use up all their extra moves in that one turn where they pause until the target is loaded too.

I'll think on a way to catch that up intelligently in another PR

**Comment by Funguss** [comment]
> 
> This should happen automatically - NPCs get moves given to them in one go when they are re-loaded, so they should have a backlog of moves to work through which would do more activity turns for them.
Ah... I don't think they get much of a chance to display this, really. Most of the tasks I set them they 'finish' when they're nearly out of the reality bubble, just before they're unloaded. Maybe reading and such are fine, but any interaction with the world generally ends as soon as they're some distance away, or if they're on a different Z level. I don't know enough about what's going on and how extensive it is to do a report about it yet. I have a feeling the way they see things is skewed, but I don't know for sure. I haven't come up with a good way of testing this yet.

**Pull request merged**
