### PR TITLE
Audit field scientist corpses map extra

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
We've had weirdly common corpses of scientists in full lab coats with random technology that'd not be even known to the public lying in fields for ages now. Time to not.

#### Describe the solution
~~Remove the entire map extra and connected itemgroups. By proximity it also means I removed scientist corpses from lying inside waste sarcophagi.~~

- Remove the scientist corpse inside the hazardous waste sarcophagus
- Remove ``science`` from the map extra
- Increase the odds of a lab card by 50% - if we're keeping them for that reason at least make it reliable
- Decrease the odds of leg prosthetics by 80% - why do exactly 10% of our field scientists have prosthetic legs?
- Lowered the chance of scientist corpse map extras aboveground nearly everywhere (except for fields, where they seem to be reasonably rare)
- Lowered the chance of college kids map extra in forests slightly

#### Describe alternatives you've considered
~~Expand the scope of this PR to also make drug deal/college kids map extras rarer because they're really weirdly common as well, but frankly I'm not sure how~~ None anymore

#### Additional context
And, before anyone starts crying about it in the comments - look, I need you to ask yourself if scientist corpses in their work clothing with confidential technology make any sense to simulate. Would something like this *never* happen? Of course it would - scientists would probably flee labs, they may bring some weird shit with them to better their survival odds. But the odds of this happening are so low that I firmly believe this is in the "so rare we should not simulate it" ballpark, alongside RPGs laying alongside roads which we got rid of ages ago.

### CODE REVIEW

**Comment by actually-a-cat** [comment]
Those are very useful for gameplay and discoverability because the maps and cards they carry are just about the only way to learn about and gain access to labs without already knowing exactly where to find them and how to bust in. It's dumb that they wear lab coats and carry random science equipment but "find dead lab employee, learn about labs from document found on them" is a good breadcrumb that should remain.

**Comment by Karol1223** [comment]
> Those are very useful for gameplay and discoverability because the maps and cards they carry are just about the only way to learn about and gain access to labs without already knowing exactly where to find them and how to bust in. It's dumb that they wear wait lab coats and carry random science equipment, I don't have any problem with removing that, but "find dead lab employee, learn about labs from document found on them" is a good breadcrumb that should remain.

That's actually not a bad argument. I'll think it through and try to edit the PR, I didn't think of how this would affect lab cards. They should still be really rare, though, not as common as they currently are.

**Comment by KittyTac** [comment]
> > Those are very useful for gameplay and discoverability because the maps and cards they carry are just about the only way to learn about and gain access to labs without already knowing exactly where to find them and how to bust in. It's dumb that they wear wait lab coats and carry random science equipment, I don't have any problem with removing that, but "find dead lab employee, learn about labs from document found on them" is a good breadcrumb that should remain.
> 
> That's actually not a bad argument. I'll think it through and try to edit the PR, I didn't think of how this would affect lab cards. They should still be really rare, though, not as common as they currently are.

I'm fine with making them rarer but they're one of if not the only vent lab breadcrumbs. Now is not the time probably.

**Comment by Karol1223** [comment]
> Now is not the time probably.

To be honest, there never will be a good time. They're certainly not the only source of vent lab breadcrumbs, just the easiest one. They should be rare.

**Comment by KeremBabaG** [comment]
sacrophagus is a good place for them to spawn imo, maybe try to leave that in?

**Comment by Procyonae** [comment]
They'd make sense in lab_subway (The z-4 subway) too

**Comment by Karol1223** [comment]
> sacrophagus is a good place for them to spawn imo, maybe try to leave that in?

...among the trash? No, it's not a good place.

**Comment by CoroNaut** [comment]
If I'm being honest, in my current play through, I have hundreds of the scientist, industrial, military and visitors passes cards in 250hrs, but have only used like 10 lab cards and a couple industrial and military ones. While they are fairly common, perhaps their occurrence could be reduced at least a little bit, perhaps 10-20% reduction. 

I'm not certain about removing field scientist spawns, perhaps they could be replaced with an alternative? Perhaps there could be a mission that goes like "There was a convoy full of scientists and gaurds, we haven't seen them in a while and think they went missing around here (XX, XX)". Another idea could be a scientist convoy working on radio towers or power substations to attempt to resupply their lab, but all died at those locations. A little lore here would go a long way.

image

**Comment by Karol1223** [comment]
> I'm not certain about removing field scientist spawns, perhaps they could be replaced with an alternative? Perhaps there could be a mission that goes like "There was a convoy full of scientists and gaurds, we haven't seen them in a while and think they went missing around here (XX, XX)". Another idea could be a scientist convoy working on radio towers or power substations to attempt to resupply their lab, but all died at those locations. A little lore here would go a long way.

I fully support whoever decides to do that. In the meantime, the existence of our overtuned field map extras has nothing to do with it, though.

**Comment by CoroNaut** [comment]
Instead increasing the amount of science cards? Too many cards everywhere would make it beyond trivial to enter labs. The decrease in prosthetics seems reasonable though.

**Comment by Karol1223** [comment]
> Instead increasing the amount of science cards? Too many cards everywhere would make it beyond trivial to enter labs

50% wallet spawn increase but more than 50% commonality reduction on the surface seems like a fair deal to me personally, but I do admit I am not good with arbitrary numbers

**Comment by CoroNaut** [comment]
Ah I missed the commonality reduction, my bad,

**Comment by fairyarmadillo** [comment]
> > sacrophagus is a good place for them to spawn imo, maybe try to leave that in?
> 
> ...among the trash? No, it's not a good place.

Weren't they hastily dumped in the sarcophagus after a containment breach, along with all the other crap in there?

**Comment by fairyarmadillo** [comment]
Thought so, here's the link: https://github.com/CleverRaven/Cataclysm-DDA/blob/0b5bf5d0b70ecb1bcf220f1197c42603ab56e9c6/data/json/snippets/hazardous_waste_sarcophagus.json

XEDRA was dumping XE037-contaminated waste, including corpses, into the sarcophagi. This predictably led to some of the corpses getting back up, and also may have contributed to the leak, though the teleporter accident had probably already caused it to breach containment.

There are lines in the lab snippets about how to dispose of scientists who improperly handle materials that suggest some of them may have wound up in the sarcophagi. Additionally, because staff at the sarcophagus were mutating (XE037 is excited by radiation, which is why it mutates you), it's plausible that a living science team would have been sent in at some point, and after being killed by zombies, retrieval might have been deemed impossible.

**Comment by Maleclypse** [comment]
> Thought so, here's the link: https://github.com/CleverRaven/Cataclysm-DDA/blob/0b5bf5d0b70ecb1bcf220f1197c42603ab56e9c6/data/json/snippets/hazardous_waste_sarcophagus.json
> 
> XEDRA was dumping XE037-contaminated waste, including corpses, into the sarcophagi. This predictably led to some of the corpses getting back up, and also may have contributed to the leak, though the teleporter accident had probably already caused it to breach containment.
> 
> There are lines in the lab snippets about how to dispose of scientists who improperly handle materials that suggest some of them may have wound up in the sarcophagi. Additionally, because staff at the sarcophagus were mutating (XE037 is excited by radiation, which is why it mutates you), it's plausible that a living science team would have been sent in at some point, and after being killed by zombies, retrieval might have been deemed impossible.
> 
> Outside of the existing lore justification, I think it's important to leave the dude in there because the sarcophagus is an obviously interesting place for players to explore, there's real challenge involved in doing so, and finding evidence of what may have caused the Cataclysm and potentially breadcrumbs to a lab is a great gameplay experience for someone who is first coming to the game.

I guess my question here is are the scientists a guaranteed spawn in the sarcophagus because I'm all here for a designed storytelling moment but I'm less here for a 1% chance of spawning that potentially might spawn in a way that adds storytelling, specifically in relation to a once a run exploration like the hazardous waste sarcophagus.

**Comment by fairyarmadillo** [comment]
HHG says there's a nearly 100% chance of finding a science ID card and lab coat there, suggesting it's a near-guaranteed spawn. It looks like they accomplished that by making every floor tile have a low random chance of spawning the special, unless I'm misreading that.

also lol at this note in the code:

```
      "monster": { " ": { "monster": "mon_zombie", "chance": 10 } },
      "//3": "The government would not put live humans into a highly irradiated cavern with lots of maneating zombies.  Right?  Right?!",
      "monsters": { "~": { "monster": "GROUP_VANILLA_NO_FERAL", "chance": 20, "density": 0.1 } },
```

**Comment by fairyarmadillo** [comment]
@Maleclypse Your comment made it sound like you were interested in keeping the (effectively) guaranteed scientist spawn?

**Comment by I-am-Erk** [comment]
It should have been said as a comment here, but using a map extra to place the scientists is a terrible solution and deserves to be destroyed. It can be added back in using a nested map as it should be

**Comment by Maleclypse** [comment]
> @Maleclypse Your comment made it sound like you were interested in keeping the (effectively) guaranteed scientist spawn in the sarcophagus? AFAIK it was basically the sole reason for the place to exist.
> 
> Asking in case we had a miscommunication or you'd go for a PR putting it (or a 100% reliable static spawn) back in.

I was looking for something that created storytelling in a unique way. Scientists spawning with notes/voice recordings about what’s happened here. A random scientist or two in a random square even with an almost guaranteed spawn felt more like just stuffing things in.   I’m not opposed to there being a story I just want it to be obvious and not an afterthought.

**Comment by Procyonae** [comment]
> It should have been said as a comment here, but using a map extra to place the scientists is a terrible solution and deserves to be destroyed. It can be added back in using a nested map as it should be

For clarity is this regarding the sarcophagus spawn or just in general?

**Pull request merged**
