### PR TITLE
Add Procyonae's nice highway interchange maps

### PR DESCRIPTION
**Pull request by ehughsbaird**
#### Summary
None

#### Purpose of change
Prevent bitrot and move towards getting https://github.com/CleverRaven/Cataclysm-DDA/pull/71822 in by pulling out the mapgen and getting it in the game sooner.

Taken from https://github.com/CleverRaven/Cataclysm-DDA/pull/71822 by @Procyonae 

#### Describe the solution
Pull all the JSON mapgen commits (and parts of commits) out of the above PR. Apply some fixes to ensure they work as standalone pieces.

Apologies for the huge PR. If desired I can split it up more, it's just quite hard to do that while preserving the commit history. Most of the lines are large, but not particularly detail-rich, mapgen and should be fairly easy to review.

#### Testing
Spawn the specials via the overmap editor.

I don't have a tiles build handy, so screenshots are in curses.

<details>
<summary>Small pieces of highway</summary>

Road crosses over highway
image image

Flat section
image

Highway crosses over land
image image

Highway crosses over water
image image

</details>

<details>
<summary>Fallback intersections</summary>

crossroad
image

tee
image

bend
image

</details>

<details>
<summary>Rest Stop</summary>

Rest stop (with slight fungal infection)
image image image

</details>

<details>
<summary>Bend</summary>

image

</details>

<details>
<summary>Trumpet Intersection</summary>

image image image image image image image

</details>

<details>
<summary>Cloverleaf Interchange</summary>

image image image image image image image image image image

</details>

<details>
<summary>Diamond Interchange</summary>

image image image image

</details>

#### Additional context
There's a lot of really awesome work here and it'd be a real shame to see it rot.

### CODE REVIEW

**Comment by Procyonae** [comment]
They probably need the SHOULD_NOT_SPAWN flag adding, or adding them to the whitelist

**Comment by ehughsbaird** [comment]
Ah, I didn't realize there was special handling for that.

**Comment by Procyonae** [comment]
The summary should probably be None too or at least something that makes it obvious this isn't working highways so peeps don't think they're actually going to show up in game

**Comment by ashGlaw** [comment]
These are beautiful. Very exciting

**Pull request merged**
