### PR TITLE
Remove battery slot from electric tools that should not be portable

### LINKED ISSUE #69963: Rotary Evaporator can only be loaded with empty (0 charge) batteries
### Describe the bug

Rotary Evaporator can only loaded with batteries with no charge. The description says it can use both cable and light/ultra-light batteries. By which I assume charged ones, and it doesn't mean it **charges** empty ones. 

Note: If you have no empty batteries in your inventory/nearby, but charged ones, it says there's no compatible magazine. 

### Attach save file

[Clearlake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13540162/Clearlake-trimmed.tar.gz)

### Steps to reproduce

1. Get Rotary Evaporator 
2. Get empty and charged light/ultra-light batteries. (any type)
3. Attempt to load charged battery into Rotary Evaporator
4. Rotary Evaporator only allows batteries with no charge

### Expected behavior

Rotary Evaporator can be loaded with charged batteries, and therefor be powered without a cable connection

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: d2e9257 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Features "No more batteries in microwave (and more)"
#### Purpose of change
Battery-powered coffee microwave? Battery-powered welder? Battery-powered coffee maker (except a single makita thingy)? no more attempts to put AAA battery into your hotplate!
Fix #69963
#### Describe the solution
Remove battery slot from this tools:
- atomic_coffeepot
- coffeemaker
- dehydrator
- food_processor
- hotplate
- hotplate_induction
- multi-cooker
- microwave
- forge
- vac_oven_small
- closed_loop_extractor_small
- closed_loop_extractor_large
- rotovap
- kiln
- soldering_iron (additionally soldering_iron_portable was made, that can use only batteries, and can't be connected to the grid)
- welder
- welder_crude
- welding_kit
- oil_press_electric
- fan
- hair_dryer
- chemistry_set
- melting_point
- analytical_set_basic
- oil_press_manual
- vac_mold

removed charges from the items in itemgroups that do not need one anymore
#### TODO
- [x] remove more slots (if someone has another example of thing, that has a slot, but shouldn't)
- [x] check descriptions and remove battery mentions in said items, because i'm sure i miss it somewhere
- [x] fix tests

### CODE REVIEW

**Comment by BlizzDA** [comment]
When this is merged - and if someone with permission is seeing this - could I get #69963 closed? It's a bug report for an issue with the Rotary Evaporator's ability to use batteries. With this PR removing the battery slot the issue pretty much resolved. Convenient!

**Comment by harakka** [comment]
> Arc welders use batteries IRL

Some exist but they're preeeetty rare. That would need to be a separate much less widely distributed tool.

**Comment by mkrutov** [comment]
why would atomic_coffeepot have a battery in the first place if its atomic and doesn't require one anyways huh

**Comment by GuardianDll** [comment]
@mkrutov #60765

**Comment by Kamayana** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/70029 was merged, so if you sync this PR you should hopefully be able to pass those tests.

**Pull request merged**
