### PR TITLE
[WIP] Update Tacoma ranch missions

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Update Tacoma ranch missions"

#### Purpose of change

At this point, this is just a progress tracker with the initial goals being mostly completed in other PRs.

General Fixes:
- [x] ~Allow ranch to be rotated~ (Moved to #57548)
- [x] ~Grammar cleanup~ (Moved to #56188)
  - [x] ~Update MISSION_RANCH_FOREMAN_13 mission that references North to general area description~
- [x] ~Convert broken window constructions to empty window frames~ Done through all the other PRs
- [x] ~Improve companion mission UI~ (https://github.com/CleverRaven/Cataclysm-DDA/pull/55746)
- [x] ~Woodcutter 1 was being spawned twice instead of spawning woodcutter 2 in the sawmill~ (Moved to #56196)
- [ ] Figure out a way to move all items from a location to a storage location instead of just leaving them there, such as the initial bed placement on top of items (Implement once @Ramza13 adds features)
- [ ] Make sure items can exist at any of the constructions and not get destroyed accidentally or cause errors
- [x] ~Update shop zones for Scavenger Boss and Bartender once merged:~ #56720 #57449
- [ ] Rebalance companion missions. 
  - [x] Convert to use merch
  - [ ] Decrease death, increase injuries.
  - [ ] Balance danger levels and merch/loot rewards.
- [x] ~Misc. Fixes~ (Moved to #57481)
  - [x] ~Fix western vehicle barricade spawns~
  - [x] ~Fix dirt appearing below makeshift beds in the barn~
  - [x] ~Assign ownership to all items/vehicles that are spawned in missions so the player can't just steal with no repercussions.~ (#56110)
  - [x] ~Replace sidewalk with concrete~

<details>
<summary>Missions: (COMPLETE!)</summary>

- [x] ~Barber~
  - [x] ~Fix listed prices~ (https://github.com/CleverRaven/Cataclysm-DDA/pull/55737)
- [x] ~Bartender~ - (Moved to #57338)
  - [x] ~Optimize nested chunks~
  - [x] ~Add a shot glass and have the shots be placed in them onto the counter instead of selling glass bottles for individual shots (I think this was intentionally implemented as a way to get glass bottles, but it makes very little sense)~
    - [x] ~Give the player a drink token that can be traded back with the shot glasses for a merch. (Slight Fallout reference. Feel free to hoard your worthless bottle caps!)~
    - [x] ~Add other spawn locations for shot glasses~
    - [x] ~Add other spawns for drink tokens (probably just on tables in the bar or nearby as these would be fairly new)~
  - [x] ~Add clutter (drinks behind the bar, empty drinks out on tables, something for the racks in the storage room)~
  - [x] ~Add farm plots for the sugar beet seeds?~
  - [x] ~Add end placement after final quest (More clutter items?)~
- [x] ~Crop Overseer~ (Moved to #56510)
  - [x] ~Jsonify Purchase and Upgrade~
  - [x] ~Create new, bigger field and allow conversion~
  - [x] ~Move plant seeds/harvest plants to the new dialogue and out of companion missions.~
  - [x] ~Handle new farm dialogue variables in code as well as traits~
- [x] ~Doctor~ - (Moved to #57387)
  - [x] ~Added 3 quests (so far) for office supplies, medical gloves, and anesthetic/medical equipment~
  - [x] ~Move regular aid here and gate it behind quests.~
  - [x] ~Gate bionics behind multi goal questline~
    - ~Acquire 3000 anesthetic~
    - ~Talk to scavengers to send a companion mission to raid a hospital to get parts for an anesthetic machine (and maybe more medical equipment)~
    - ~Talk to scrappers for metal parts (which will send you on a quest for an angle grinder and a hacksaw)~
  - [x] ~Prevent hospital raid from being able to run twice at the same time~
  - [x] ~Fix `u_has_item` and `u_sell_item` with anesthetic not being recognized in an anesthetic kit (https://github.com/CleverRaven/Cataclysm-DDA/issues/55918)~
  - [x] ~Figure out how to prevent the doctor from dropping the binders (Give them more storage capacity?)~
- [x] ~Nurse/Clinic~ (Moved to #56205)
  - [x] ~Jsonify nurse missions~
  - [x] ~Fix placement of clinic~
  - [x] ~Move aid to doctor. Possibly implement a lesser aid variant to the nurse~
  - [x] ~Fix/Rebalance lesser aid / aid times and currently busy times after.~
  - [x] ~Figure out how to spawn less aspirin after MISSION_RANCH_NURSE_1 (currently spawning 200 per bottle, should be 20)~
  - [x] ~Add end placement after final mission (probably add some medical items/furniture around the clinic)~
  - [x] ~Add the missing entrance from the house to the new buildings.~
- [x] ~Scavenger~ (Moved to #56403)
  - [x] ~Jsonify scavenger missions and fix fence placement in the wall~
  - [x] ~Molotov quest should not be repeatable~
  - [x] ~Re-add looted_building pseudo terrain~
  - [x] ~Replace 12 knife spears with simple knife spears~ (Moved to #56188) (Mentioned in #30579)
  - [x] ~Implement loot retrieval from companion raid missions. This was intended to work, but left as a TODO.~
  - [x] ~Increase spawns from "place_items"~
  - [x] ~Add end placement after Molotov quest (More scrap items?)~
- [x] ~Woodcutter 1~ (Mostly moved to #56192)
  - [x] ~Jsonify log placement (buy_10_logs and buy_100_logs)~
  - [x] ~Replace [NPC NAME] once #56066 is merged~
  - [x] ~Can purchase logs without paying by hitting escape in the trade window / Verify payment before placing logs~ (Fixed by: #56932)
</details>

Mission Tree Audit:
- [x] Barber, Bartender, Carpenter 1, Carpenter 2, Crop Overseer, Doctor, Farmer 1, Farmer 2, Foreman, Nurse, Scavenger, Scrapper, Sickly Laborer

Bonus:
- [ ] Woodcutter 2
  - [ ] Replace heavy machinery/old machinery with better/real machines
  - [ ] Investigate if the conveyor/sawmill can be made functional with EOCs
- [ ] Expand sickly laborer. (Possibly have the doctor look at them once they arrive? What do they even have? What is their purpose?)
- [ ] Expand scrapper.
- [ ] Add more scavenger quests (More weapons/armor?)
- [ ] Add barber quests (batteries for clippers? scissors? shaving cream? cleaning supplies?) (Gotta try to avoid doing the same thing as the refugee center hair kit)
- [ ] Crop overseer should probably have quests for growing crops (we have fields + greenhouse capacity)
- [ ] Guard is only used in companion missions. Should there be some generated around the commune as well?

#### Describe the solution

Allow the tacoma ranch to be rotatable and audit everything to make sure it works. Update what doesn't.

#### Describe alternatives you've considered

None

#### Testing

In Progress

#### Additional context

Creating this draft early to get my initial thoughts out and show that this is being worked on.

### CODE REVIEW

**Comment by Maleclypse** [comment]
`Figure out a way to move all items from a location to a storage location instead of just leaving them there, such as the initial bed placement on top of items`

I think Bombasticslacks added a way for EOCs to delete items from the game.

**Comment by Maleclypse** [comment]
I’m not sure how his method does it and whether it recognizes what the items are before it deletes them because it’s designed mimic sale of goods. Though if you only want to move things you could possibly use zone creation effects and then setup a fake NPC to complete the move.  If I were doing it it would be a specific NPC class that has debug invisibility, and somehow uses eoc commands to get it to sort the zones. But that’s probably pretty hacky.

**Comment by haveric** [comment]
I'd certainly prefer a less hacky implementation and can look into implementing it myself after I've fixed everything else, unless someone wants to volunteer to implement something before then.

**Comment by PatrikLundell** [comment]
The handling of dialog missions seems to be more primitive than the camp ones in that the camp missions highlight finished missions, which does not seem to be the case for dialog ones.

The caravan mission seems to be partially broken in that each companion caravan member is brought back individually, and each companion brought back seems to trigger the simulation of a new caravan when it comes to danger, but not when it comes to payment... I believe all remaining caravan members are involved in each fight up until they're recalled.

**Comment by haveric** [comment]
I haven't gotten to the dialog missions yet, so I'm not yet sure on the scope here. Is there any possibility of re-using the faction menu logic here or is this just going to need a complete rewrite?

My next focus is going to be jsonizing the scrapper missions if I can and auditing the other npc missions, so I probably won't get to this for a bit. If you or someone else has some free time between all the other work going on, I wouldn't turn down assistance looking at the menu logic.

**Comment by PatrikLundell** [comment]
Yes, you've gotten to the dialog missions... It's just that my description is poor. In my eyes there are two types of missions in the game, namely base camp missions, gotten via base camp bulletin board "dialog", and dialog missions, reached by talking to NPCs, and all of the Tacoma missions (such as the scavenger missions) fall into the latter group. Note that the division and naming is mine: I haven't seen anyone describe them in any terms.

Code wise the "top" of the mission logic resides in mission_companion.cpp, where the dialog missions are, and the base camp missions appear in faction_camp.cpp (with glorious C stupidity having the definitions in basecamp.h to confuse the unweary).

I can do the changes, at least for the UI only part, because they're fairly easy (just using a boolean or two to keep track of aggregated state when iterating over NPCs), while the caravan one requires more logic. However, I'm always weary of having multiple people modifying the same files at the same time, especially when the train wreck called git is used, as it will find "conflicts" everywhere, including a way do drop parts that happen to be the same when you actually want to merge things.

**Comment by haveric** [comment]
I'm focusing on converting the regular missions for now which are in mission_start.cpp. If you feel comfortable with the ui work, I'd vote for you to go ahead with it and leave any potential git conflicts to me. (I am comfortable enough with git that it shouldn't be an issue, but may end up splitting this PR into more sizeable chunks anyway for easier review, which would avoid the issue entirely)

**Comment by PatrikLundell** [comment]
Ah, OK, a quick look at mission_start.cpp gives me the impression it deals with "normal" missions where the PC is given a mission, not the missions where you send a companion off (base camp and what I call dialog missions, probably better called dialog companion missions).
I'll make a stab at the dialog companion missions (Scavenge raid/patrol, menial/carpentry labor, foraging, caravan) tomorrow, with a reservation for the caravan one.

**Comment by haveric** [comment]
Thanks for the improvements @PatrikLundell. I think the only major thing left will be figuring out how to jsonify the companion missions map updates, but I'll look into that once I've gotten a few other things updated.

**Comment by PatrikLundell** [comment]
None of the "actual" companion missions (i.e. those that involves sending off companions) include map updates. The buy/plant/harvest missions don't actually send off any companions anywhere, but it would certainly be good if they could be jsonified. I'd suggest considering (as in carefully weighing it as an option, not as a suggestion to immediately go ahead) moving these missions to the "normal" interaction level where you're currently improving things.
Doing that would require the ripping out of the corresponding enum values and code, but that ought to be it. Since no companions are sent off on these missions, there's no (de)serialization messiness to deal with.

**Comment by haveric** [comment]
That's all good to know. If there's no companion interaction, then they should be easy to move to normal interaction, which solves most of my concern over jsonifying them. I think they are the only blockers for allowing the map to be rotatable as I have done in this branch.  I'll take a closer look once your PR gets merged and see what makes the most sense. I can always reconfigure the menus to make it all make sense.

**Comment by PatrikLundell** [comment]
I would suggest splitting the crop overseer missions into two dialog entries rather than one, as me using them for labor isn't exactly the same as me providing them with labor. Thus, there would be one entry for investing in agriculture (or something along those lines) and one for providing labor (where a standardized phrase is useful to help players recognize what the topic is about).

**Comment by haveric** [comment]
Well I don't think that rebase went as cleanly as I expected. Apologies if this just pinged everybody...

**Comment by Maleclypse** [comment]
I think you might want to find a stopping point for this PR as you are currently 500 lines over what most people are willing to review in JSON.   I get that much of it is restating existing content but we are still reaching a point of increasing the difficulty of merging the PR.  Then create a new PR with the remaining to do items from this list? You can even show which ones you've already completed in any followup PRs.

**Comment by haveric** [comment]
> I think you might want to find a stopping point for this PR

I completely understand and I've always intended to split it up at places where it makes sense to, but there's plenty of things in incomplete states right now that I want to make sure are done before splitting out. There's also some areas I might need to go back and tweak before I am done and don't want to create several back and forth PRs as I figure things out.

**Comment by Maleclypse** [comment]
@haveric Is this still intended to be in Draft?

**Comment by haveric** [comment]
> Is this still intended to be in Draft?

Sorry, didn't think I'd be away from cdda development this long. All development has been done in other PRs for the existing work and this is purely a progress tracker for longer term goals at this point. I think I'm ok with this being closed at this point and I'll create a new issue/PR once I get to the next iteration of updates.

**Pull request closed without merging**
