### PR TITLE
Fixed errors on game start in No Hope mod

### LINKED ISSUE #53632: No Hope mod mapgen consistency errors
### Describe the bug

Starting or loading a game with the No Hope mod results in the following mapgen consistency errors:

```
16:37:33.021 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen farm_lot_wire_straight_h_open is not used by anything!
16:37:37.864 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen farm_lot_wire_turn_h_open is not used by anything!
16:37:38.655 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen farm_lot_wire_turn_uni is not used by anything!
16:37:39.339 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_+ is not used by anything!
16:37:40.578 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_+_dn is not used by anything!
16:37:41.027 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_+_up is not used by anything!
16:37:43.750 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_c is not used by anything!
16:37:46.444 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_c_dn is not used by anything!
16:37:46.445 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_c_up is not used by anything!
16:37:46.447 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_entry is not used by anything!
16:37:46.447 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_entry_dn is not used by anything!
16:37:46.448 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_entry_up is not used by anything!
16:37:46.451 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_t is not used by anything!
16:37:46.457 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_t_dn is not used by anything!
16:37:46.458 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_t_up is not used by anything!
16:37:46.458 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_wild is not used by anything!
16:37:46.458 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_wild_dn is not used by anything!
16:37:46.458 ERROR : src/mapgen.cpp:434 [void mapgen_factory::check_consistency()] Mapgen mansion_wild_up is not used by anything!
```

### Steps to reproduce

1. Create a new world with the No Hope mod
2. Start a character

### Expected behavior

No mapgen errors

### Screenshots

_No response_

### Versions and configuration

49c6f2d1ecbdf6b362c178720be7fdaef48060e2 (`cdda-experimental-2021-12-21-0353`) with #53302 applied.

### Additional context

These don't interfere with gameplay at all.

Attn @Night-Pryanik.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
None

#### Purpose of change
Closes #53632.

#### Describe the solution
Removed offending OMTs.

#### Describe alternatives you've considered
None.

#### Testing
Started game with the mod. Got no errors.

#### Additional context
None.

### CODE REVIEW

**Comment by pjf** [comment]
Thank you!

**Comment by kevingranade** [comment]
Removals triggered other failures, see tests for details.

**Comment by Night-Pryanik** [comment]
All errors refers to missing OMTs which I removed from the mod in this PR. I'm not sure what to do with such errors in this case.

**Comment by kevingranade** [comment]
Searching for the problem strings, it looks like it's because of Graphical Overmap, which we should be killing off anyway.

**Comment by ZhilkinSerg** [comment]
Can you rebase it on top of current master please? It should get rid of load errors.

**Comment by Night-Pryanik** [comment]
Ok, rebased, let's see about errors.

**Comment by Night-Pryanik** [comment]
Nope, errors still popping up.

**Comment by kevingranade** [comment]
It's still breaking because the Graphical Overmap mod isn't obsoleted.

**Comment by Night-Pryanik** [comment]
Closing in favor of #54391.

**Pull request closed without merging**
