### PR TITLE
Buff persistence hunter mutations

### PR DESCRIPTION
**Pull request by KittyTac**
#### Summary
Balance "Make persistence hunter mutations actually be relevant"

#### Purpose of change
(Extreme) Persistence Hunter had such a small effect that I thought it didn't work at all until it was pointed out. I decided to increase the regen enough for it to matter.

#### Describe the solution
I changed normal Persistence Hunter stamina regen from +10% to +35% and Extreme Persistence Hunter from +20% to +70%. With the latter, which is post-threshold lupine, you can regen from empty stamina to full in 4 minutes instead of 7 (before the effect was from 7 to 6) and regen stamina much quicker while walking, thus matching up more with the description.

#### Describe alternatives you've considered
Either change it to another stamina cap buff on top of Indefatigable or leave as-is.

#### Testing
Debugged stamina to 0, saw how long it took for it to regen, debugged extreme persistence hunter, did the same, then ran around to check if you can run forever (you can't, good).

#### Additional context
N/A

### CODE REVIEW

**Comment by Venera3** [comment]
It bears mentioning that this about doubles the effective stamina for everything including melee attacks as well (regen from 20 to 35 a turn, *before* cardio comes into play), which opens up the possibility of lupines getting to ignore stamina as a system provided high cardio, low arm encumbrance, and a low-cost weapon.

**Comment by Wishbringer** [comment]
Its human nature to over buff/nerf things.
More reasonable values would be something like 0.2 & 0.4 maybe?
This would be more likely to get accepted that way.

**Comment by KittyTac** [comment]
> It bears mentioning that this about doubles the effective stamina for everything including melee attacks as well (regen from 20 to 35 a turn, _before_ cardio comes into play), which opens up the possibility of lupines getting to ignore stamina as a system provided high cardio, low arm encumbrance, and a low-cost weapon.
I tested it, you still can't fight forever even when unarmed and with high cardio. A long time, yes. But you still can't swing a lucerne for very long for example. Plus it's a post thresh mutation for a line widely seen as not very good to go post thresh on.

> Its human nature to over buff/nerf things. More reasonable values would be something like 0.2 & 0.4 maybe? This is far more likely to get accepted that way.
From my tests, those values were not very noticeable at all. It was extremely weak before, and that was obviously not intended given the description and point values.

**Comment by Wishbringer** [comment]
Are you sure that wasn't because of #53603 ?

**Comment by Maleclypse** [comment]
Thanks I'm not sure exactly on the numbers but I definitely wanted Lupine's niche to be an incredible stamina when I was working on differentiating it.  One solution might be three mutations with one being pre-thresh and two post thresh.

**Comment by kevingranade** [comment]
Persistence hunter is the wrong description for this effect, persistence hunter is being able to run all day, which has nothing to do with what the game calls stamina.
You either need to lean into the fatigue effect more or overhaul the description of the mutation to reflect that it lets you sprint for longer, not keep up a moderate pace longer.

Also, these numbers are crazy, and your looking at the wrong things for balancing them. How long it takes you to recover from zero is irrelevant, the issue is how far and fast you can run or fight before getting winded.

**Comment by KittyTac** [comment]
> Persistence hunter is the wrong description for this effect, persistence hunter is being able to run all day, which has nothing to do with what the game calls stamina. You either need to lean into the fatigue effect more or overhaul the description of the mutation to reflect that it lets you sprint for longer, not keep up a moderate pace longer.

I initially considered reducing weariness gain but I think I'd need C++ code for that. I don't think fatigue would matter much in practice especially for the intended niche. I'll just change the description I suppose.

> Also, these numbers are crazy, and your looking at the wrong things for balancing them. How long it takes you to recover from zero is irrelevant, the issue is how far and fast you can run or fight before getting winded.

They may seem crazy, but consider three things:
1. Yes you can run for much longer and fight with low-cost weapons for much longer. But from my playtests (I am doing a run with this), it's not as big of an impact as you may think. And if you fight with something heavy you will still run out.
2. It has to compete with the other thresholds. You can't get e.g both 70% stamina from lupine and +7 Str from beast. This is what balances this.
3. Speaking of Insanely Strong, is that really weaker than this? Post-thresh mutations are meant to be quite strong, aren't they?

**Comment by kevingranade** [comment]
>    Yes you can run for much longer and fight with low-cost weapons for much longer. But from my playtests (I am doing a run with this), it's not as big of an impact as you may think. And if you fight with something heavy you will still run out very fast.

You haven't quantified it, so it's not part of the discussion.

>    It has to compete with the other thresholds.

This is not a thing, this is an argument for demoting it out of being post-threshold, not buffing it.

> You can't get e.g both 70% stamina from lupine and +7 Str from beast. This is what balances this. Lupine has little else post-thresh, thus making it undesirable to inject serums of (unless you want puppy eyes).

If you want to make a case for whole-tree balance you have to break the whole thing down and make that argument, not just sketch out a few parts of it. Then at the end of the day nerfing the alternatives is a possibility.

> Speaking of Insanely Strong, is that really weaker than this? Post-thresh mutations are meant to be quite strong, aren't they?

This looks much stronger than insanely strong is intended to be to me.

**Comment by KittyTac** [comment]
> > Yes you can run for much longer and fight with low-cost weapons for much longer. But from my playtests (I am doing a run with this), it's not as big of an impact as you may think. And if you fight with something heavy you will still run out very fast.
> 
> You haven't quantified it, so it's not part of the discussion.

That's going to vary with cardio, for balance it's difficult to quantify.

> > It has to compete with the other thresholds.
> 
> This is not a thing, this is an argument for demoting it out of being post-threshold, not buffing it.

Then the line itself will be just as weak. Changes little balance-wise.

> > You can't get e.g both 70% stamina from lupine and +7 Str from beast. This is what balances this. Lupine has little else post-thresh, thus making it undesirable to inject serums of (unless you want puppy eyes).
> 
> If you want to make a case for whole-tree balance you have to break the whole thing down and make that argument, not just sketch out a few parts of it. Then at the end of the day nerfing the alternatives is a possibility.

Well right now, lupine isn't much different from beast, besides beast having traits like combat adaptation, sapiovore, and insanely strong which are stronger than what lupine has. That's my point. And I don't feel mutations need nerfs.

> > Speaking of Insanely Strong, is that really weaker than this? Post-thresh mutations are meant to be quite strong, aren't they?
> 
> This looks much stronger than insanely strong is intended to be to me.

Not from my playtests. Insanely strong is at once a large HP boost, damage boost, and carrying capacity boost. With this... well you can run away more effectively and fight longer if with a light weapon I guess.

**Review by kevingranade — CHANGES_REQUESTED** [review]
You're sidestepping all the justification I'm asking for, if you want a drastic change like this it requires a strong argument, and you haven't presented one.
I don't even buy the weaker arguments you're making, running away more effectively is the single greatest enhancement you can make to your survivability, and you're arguing that it's pointless.
If the increased stamina is so much of a non-issue, why are you even making this change?

**Comment by kevingranade** [comment]
Actually nevermind, between the extreme thematic shift and the lack of justification, I don't see this happening.

**Comment by KittyTac** [comment]
I never said it was pointless, just that it wasn't gamebreaking. Right now those two traits are quite pointless though. That is my justification. I could reduce the buffs?

**Pull request closed without merging**
