### PR TITLE
More Survival Tools Series 16

### PR DESCRIPTION
**Pull request by chaosvolt**
Whee, yet another array of things I'd been pondering. @_@

Fixes:
- Fixed plural of lit hobo stove.

Item Additions:
- Bone skewers. In both normal and human varieties, intended for the few situations where wood isn't available yet bodies are. Added to a few recipes involving skewers and a couple requiring bone. Smoked meats only allow human bone skewers in the case of smoked sucker.
- Whistle multitool. Assorted functions, though the whistle isn't as loud as the proper whistle.
- Mortar and pestle. Not as bulky or complex to make as a quern, but recipes using it are more involved than grinding stuff with a quern. 50% more time to craft, and added survival skill requirement.

Terrain Additions:
- Door curtains. Easy to make and doesn't need a frame, but extremely fragile and can't be barricaded.
- Makeshift doors. Easy to make and doesn't need a frame, but fragile and can't be barricaded. Bit tougher than curtains, but uses higher skill and different materials.

Misc:
- Gave WEATHER_TOOL an item action due to the addition of an item with multiple uses, alongside the weather function.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>Door curtains ... Makeshift doors

I'd love to see these in the base game!

**Comment by chaosvolt** [comment]
Meep. Could shift the content to mainline then. All of it, some of it, or just door curtains? o.o

**Comment by Coolthulhu** [comment]
Those bone skewers (especially with a special human type) sound superfluous. I mean, bone is much rarer than wood in bulk, can be used for bone broth and the only type that would really be worth turning into skewers is tainted (which is useless for food).

Having extra recipes to maintain with those bone skewers isn't really worth it.

It's not really a mod thing, but smoked meat could lose that skewer component. Same for smoked sucker and fish.

Why does makeshift/curtain door have `t_null` as bash result? Shouldn't it go back to door frame?

As for mainlining: I think that you could work on mainlining basic copper stuff. Then you could add copper soldering to regular solder tools.

**Comment by chaosvolt** [comment]
Hmm. I've had situations where corpses are available but wood isn't, though. That cooking quality of 1 is the main use for it. I'll likely combine normal and human bone skewers though, for less recipe clutter.

As for setting the item to t_null, it's because the items are built directly without a door frame. Though I could tweak that and make makeshift doors require a frame, hanging a curtain is something that probably shouldn't need a door frame.

As for copper...hmm. Makes sense, yeah. Wasn't sure what to use for the repair item.

**Comment by Rivet-the-Zombie** [comment]
>Not sure whether to mainline any of this content or not then.

You really ought to mainline the constructions, at the very least.

**Comment by chaosvolt** [comment]
Meep. Sorry about that, and thank you for the merge. Will have to muck about with mainlining in a separate PR, alongside the aforementioned copper tweaks.

**Pull request merged**
