### PR TITLE
No skill required to make chemistry kits.

### PR DESCRIPTION
**Pull request by kevingranade**
Unless I'm missing something, these two recipes are literally putting glassware in a bag, why does it require skill?

### CODE REVIEW

**Comment by Malkeus** [comment]
Devil's advocate here: where's the bag?

**Comment by Rivet-the-Zombie** [comment]
Good point, @Malkeus. Looks like it's currently just jars, tubing, and safety glasses.

**Comment by Malkeus** [comment]
possible candidates: purse, messenger bag, sling pack, runner pack, rags/leather and thread w addition of sewing kit as a tool requirement

**Comment by Darkyhard** [comment]
> where's the bag?

It's weird that not having a bag (or ability to make it) prevents you from using a chemistry set for its' purpose, so I didn't add it to basic chemistry set when I PRed it.

**Comment by Malkeus** [comment]
Maybe just some rags/leather with no sewing requirement then? It sounds like a loose collection of fragile stuff, it would need to be wrapped up somehow to keep it from breaking irl. A cardboard box and some rags would work, those are REALLY easy to lay your hands on.

**Comment by Zireael07** [comment]
http://www.wikiwand.com/en/Chemistry_set

Cardboard and whatever bags are good ideas (I eyeballed the bag's volume vs. parts volume when considering which bags to allow for chemistry set). Rags and leather not really.

**Comment by Zireael07** [comment]
http://www.wikiwand.com/en/Chemistry_set

Cardboard and whatever bags are good ideas (I eyeballed the bag's volume vs. parts volume when considering which bags to allow for chemistry set). Rags and leather not really.

**Comment by Soadreqm** [comment]
>why does it require skill?
Well, you need basic familiarity with chemistry to know what equipment you need. That's cooking, though, not fabrication.
What's the lowest level crafting recipe that needs a chemistry set? Before you hit that, it's just one more piece of clutter in your crafting menu.

**Comment by Zireael07** [comment]
I picked fabrication so that you know how to wire that wire to avoid breaking the delicate glassware.

**Comment by Malkeus** [comment]
I've shifted my thinking from sewing a bag out of leather/rags, to an idea that seems to fit the theme of the new recipe. A cardboard box to hold everything with rags/leather to provide padding for the glassware. The difficulty would still be reduced to 0 since there's no wire included in the makeshift version, it's literally just glassware in a box with some old towels wrapped around it to keep it intact.

**Comment by kevingranade** [comment]
Good catch on the missing bag, that complicates things a bit.
If there's no bag or a box it's going to gave a bit of a volume premium, a
nice bag is going to be overall more compact.
The recipes aren't autolearn, so the difficulty is only how hard it is to
assemble, otherwise the recipe is simply a list of items to put in the kit.

**Pull request merged**
