### PR TITLE
~Ready~ Adds cattails to swamps.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Also known as _bulrushes_ by our Commonwealth players, these supremely handy plants are an excellent source of edible products and plant fiber all throughout the year. Just like in real life, their material output in DDA varies depending on the season in which they are harvested.

You can find them growing in swamps in little clumps.

New items: cattail stalk, cattail top, cattail shoot, cattail rhizome, starch, cooked cattail top, cooked cattail stalk

Includes new recipes to support new items and integrates new items into existing recipes wherever possible.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by graysage1** [comment]
Nice, that's one more good reason to brave the swamp holes.

**Comment by Coolthulhu** [comment]
Those nutrition values are rather big, especially the starch.
If nutrition was pure calories, it would make sense, but as far as I know it is supposed to be some generic calories+microelements+proteins something. Cooking oil doesn't grant much nutrition, neither does flour.
I like that -14 fun - DDA needs more meaningful food morale bonuses/penalties.

For example, in autumn with just a rock, stone knife and a can you can get average of 67 nutrition per plant by making starch.

I like the idea itself, but the number of different parts could be lowered (4 possible different parts from 1 plant, and that's before any cooking). I'm losing the track of which one does what even though I have the json in front of my eyes.

I don't see any re-growth data, so they're a finite resource. Are they supposed to ever regrow (say, when mapgen goes more dynamic) or is their growth too unreliable/slow to matter?

> Nice, that's one more good reason to brave the swamp holes.

Not too sure about this one. Swamp holes are essentially insta-kill. They should probably be removed from the game, or at least radically altered.

**Comment by graysage1** [comment]
@Coolthulhu 

>Swamp holes are essentially insta-kill.

It's been a long time since I fell into one, but is long rope or grappling hook supposed to be a defense against the swamp hole?  If yes, then it's only an insta-kill for the unprepared.  I try to get a long rope or a grappling hook soonish.  It's not a huge priority for me, but when I get a chance I usually do get one and carry it on me at all times.

>For example, in autumn with just a rock, stone knife and a can you can get average of 67 nutrition per plant by making starch.

This this from IRL bushcraft or something that happens in-game?  I am not aware of this technique you're referencing.

**Comment by Coolthulhu** [comment]
>  If yes, then it's only an insta-kill for the unprepared.

If you get bad rolls and don't have enough throwing and unarmed skill, it's still an insta-kill even with a hook.
While it is not a direct insta-kill (you don't die instantly, just starve to death), the only way to sensibly recover from it is using the debug menu. Unless you carry an electric jackhammer and means to power it for thousands of uses.

> This this from IRL bushcraft or something that happens in-game?

Not yet in game, but in this PR. You can craft a single unit of starch (50 nutrition) from a single rhizome or 4 stalks. Each cattail is a guaranteed rhizome and depending on the season possibly also stalks, shoots or spikes.

**Comment by graysage1** [comment]
@Coolthulhu Thank you for explaining.

>If you get bad rolls and don't have enough throwing and unarmed skill, it's still an insta-kill even with a hook.

I see.  Maybe the skill requirements can be relaxed then?  I don't understand why unarmed is checked at all.  It's not like you need to jiu-jutsu your way out of the hole.  It makes no sense to me.  Throwing I can understand.

Also it would be nice if the game allowed you to make throwing attempts from the bottom of the sinkhole, so that even if you don't have enough throwing skill yet, you can at least gradually earn it and succeed eventually.  That way you really do only need the rope or the grappling hook to be safe.  I think that's fairly reasonable without removing a hazard which I believe to be conceptually interesting, even if we can agree it's not implemented in the best way possible.

**Comment by Rivet-the-Zombie** [comment]
>Those nutrition values are rather big, especially the starch.

I'll knock it back down a bit.

>For example, in autumn with just a rock, stone knife and a can you can get average of 67 nutrition per plant by making starch.

They're pretty much full of nutrients.

>I like the idea itself, but the number of different parts could be lowered (4 possible different parts from 1 plant, and that's before any cooking). I'm losing the track of which one does what even though I have the json in front of my eyes.

I actually had to pick and choose which parts of the plant to include, since there's even more edible parts to a cattail than I have in this PR. That being said, I'll look into trimming some of the items back when I get home tonight.

>I don't see any re-growth data, so they're a finite resource. Are they supposed to ever regrow (say, when mapgen goes more dynamic) or is their growth too unreliable/slow to matter?

This is really just  case of me forgetting to include a regrowth system. I'll do so this evening.

**Comment by Frost-wood** [comment]
@Coolthulhu Cattails are some of the most nutritious plants, through the nutrition depends on what time of year you harvest them.  You can't use the roots as straight flour though, as cattail root doesn't have the thickening action that flour has. 

Peterson's field guide to edible plants suggests that you mix half flour, half-cattail flour if you are going to use it for baking.

**Comment by Rivet-the-Zombie** [comment]
Since you're taking the plant's very roots, I've decided to skip on having it regrow.

**Comment by Coolthulhu** [comment]
Had to add a little fix: cattail parts would spawn rotten due to unset birthday (0 by default).

Ideas for the future:
* Adding batch craft bonus to starch crafting (especially boiling)
* Cattail stalk glue (apparently it exists IRL)

**Pull request merged**
