### PR TITLE
Weapons Categories: Fencing

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Balance "Add weapon categories for Fencing"

#### Purpose of change
Partially implements #51867.
Fencing: A style with relatively few weapons, and with very little difference between them.

#### Describe the solution

| Weapon Category  | Martial Art | Includes |
| ------------- | ------------- | ------------- |
| FENCING_WEAPONRY  | Fencing  | The Foil, Épée, Sabre, and similar weapons like several batons  |

The hollow cane was added to batons and the sword cane to short swords.

1 new weapon category:

- FENCING_WEAPONRY 
A catch all for the weapons used in fencing, which are basically pointed, slender and of medium length weapons.

I also eliminated the monomolecular blade from fencing since I don't think it has the correct shape, but tell me in the comments if I should change it.

#### Describe alternatives you've considered
To divide the style along the lines of the 3 fencing weapons: The Foil, Épée and Sabre, but they seem the same to me.
Another alternative is to use the categories of batons and maybe create a smaller "FENCING_BLADES/POINTED_SWORDS" category for the remaining weapons, but it would add the tonfas to the style and some other weird weapons to use in fencing.

#### Testing
Spawned in game several fencing weapons, all working without problem.

#### Additional context
Style weapons before this PR:
imagen

Style weapons after this PR:
imagen
It should be the same except for the monomolecular blade.

Thanks to @dseguin for the work done in #52638 to display the weapons based by their category!

Fencing weapons:
https://en.wikipedia.org/wiki/Fencing#Weapons

### CODE REVIEW

**Comment by Scorch-Mechanic** [comment]
I have doubts about whether the loaded stick should be included as a fencing weapon. What I am observing is that fencing weapons are roughly sword length and relatively well balanced items. But the loaded stick is basically a walking-cane sized weighted club, it's specifically unbalanced (for better walloping). I don't know anything about fencing IRL though.

**Comment by Termineitor244** [comment]
> 
> 
> I have doubts about whether the loaded stick should be included as a fencing weapon. What I am observing is that fencing weapons are roughly sword length and relatively well balanced items. But the loaded stick is basically a walking-cane sized weighted club, it's specifically unbalanced (for better walloping). I don't know anything about fencing IRL though.

The loaded stick is basically a shillelagh but with a little more weight, if I remove it from the style then the shillelagh and its fake version should be removed too, they certainly are heavier than, for example, the saber, but they have the correct length and form.

**Comment by Terrorforge** [comment]
If "batons" isn't a close enough equivalent to "stick" that it can be used in a case like this, I feel like that's a problem with the "batons" category. Either we acknowledge that tonfa can be [gripped](https://i.pinimg.com/736x/d9/26/03/d92603c89362b17c4d4d85a710557f75.jpg) and [used](https://1.bp.blogspot.com/-4m9_hG8bQaI/W6BHwuyYNEI/AAAAAAAAIP4/VtEpmu_Z63IlpNXEuTrZS_m959vLNQPhwCLcBGAs/s1600/Arizona%2BHombu%2BDojo%2B-%2Btraditional%2Bkobudo%2B%2526%2Bkarate.JPG) as batons, in which case there's no reason to exclude them from Fencing, or we assume they're always used in the traditional side-handle configuration, in which case they shouldn't be in that category at all. The other main sticking point is the hammer, which we can just get rid of because it has no reason to be there in the first place, except to grandfather in Stuff That Krav Maga Used To Have For Some Reason.

Also it's worth noting that the saber is meaningfully different from the other fencing weapons, in both real-world and olympic fencing rules terms, because it is a cut-and-thrust weapon as opposed to a specialized thruster. And you know, I'm generally opposed to the idea of creating things like a "FENCING_BLADES" category, since a category that only really applies to one style is kind of counter to the whole idea of unified weapon categories, but I think it's warranted in this case. Because the alternative is acknowledging that creating a cut-and-thrust category and acknowledging that most swords are not _that_ different, and that's a line of thinking that ends with Niten Ichi-Ryu gaining access to the zweihander.

**Comment by Termineitor244** [comment]
@Terrorforge you know what? I'm convinced, I will give fencing a second pass and make it use batons and fencing blades as categories, removing the hammer of course (Kevin added it to this category, and it just stayed there haha).

There was already a bit of discussion in discord about Niten Ichi-Ryu and Medieval Swordmanship, and the conclusion was to make specialized categories for these styles rather than using other categories already implemented, I'm personally of the idea that all of these swords are very similar so one should be able to use them if their length is close enough, but I understand this would go against the essence of these styles.

**Comment by damien** [comment]
This is a really interesting discussion I'd love to contribute a bit to. I've done a small amount of fencing myself and can agree to the statements of _practical_ fencing weapons being long, pointed, and well balanced. Weight might also be an issue here, as going from epee to sabre definitely makes certain maneuvers more difficult.

Would it make more sense to think about qualities of a weapon that make them valid for a style rather than a binary yes/no per weapon? I'm thinking along the lines of defining a valid fencing weapons as something like `length: medium, weight: light, pointed: true` and including every weapon that fits those qualities.

This could also serve as a way to get around the need to manually manage weapon inclusion in martial art styles at the cost of ensuring any weapons we want to be used with martial arts define all the weapon qualities that are important to a martial art.

**Comment by Terrorforge** [comment]
> Would it make more sense to think about qualities of a weapon that make them valid for a style rather than a binary yes/no per weapon? I'm thinking along the lines of defining a valid fencing weapons as something like `length: medium, weight: light, pointed: true` and including every weapon that fits those qualities.

Doesn't that just mean you have to define all those properties instead? Sure, length, weight and damage type has to be there, but you'd also want to include properties like... is it double-edged or single-edged? Does it have a point suitable for thrusting? Is it curved or straight? Does it have a crossguard? Does it have a complex hilt?

It also sounds like the kind of system that would need a lot of babysitting to work the way you'd expect it to. You'd have to tune it a lot to make it so that e.g. fencing accepts the cavalry sabre, but not the scimitar or katana - or do the opposite thing and just accept a lot of overlap, which is confusing for different reasons. In either case, I don't think you're gaining a lot vs. just adding tags to the individual weapons.

Also fwiw I think the arbitrariness of manual tagging is and advantage. Sure, there's a noticeable weight difference between epee and sabre - but an actual historical cavalry saber weighs twice as much as _that_. The fact that we can just gloss over that and pretend that current sport fencing is exactly the same thing as 19th century military saber fighting is kind of necessary to avoid having a style where the best weapon is the sharpened foil.

**Comment by Termineitor244** [comment]
I have to say that I'm on the same side as @Terrorforge, such a system would need a lot of care for it to work properly, and those attributes are meant to have an use in other places, many other martial arts don't even conform to a defined standard in CDDA, Fior for example, you need to define its weapons because we do not track if a weapon has a head with an adequate form to make a "hook" in battle.

Weapon categories were created to make it more easy to keep track of them, to whenever possible keep lists that can be used in multiple martial arts and to enable cross mods compatibility for modded martial arts and mod weapons. They can also (now) be used to improve reading of weapon lists in game, and to have more granularity in techs and buffs of martial arts. A system like the one you mentioned would be more difficult (if possible) to make it work like this.

**Comment by Termineitor244** [comment]
Done: #52839

**Pull request merged**
