### PR TITLE
Add missing maintainers to DinoMod

### PR DESCRIPTION
**Pull request by damien**
#### Summary

```SUMMARY: Mods "Add missing maintainers to DinoMod"```

#### Purpose of change

Giving credit where credit is due. Also helping formalize who's doing what to keep this DinoMod going.

#### Describe the solution

Added missing Github handles to DinoMod's `modinfo.json`

#### Describe alternatives you've considered

Stealing all credit. Sadly, I'm not clever enough to keep that ruse up for long.

#### Testing

JSON is valid.

#### Additional context

None.

### CODE REVIEW

**Comment by damien** [comment]
Updated `Summary` in the PR, a type was causing PR validation to fail.

**Comment by KorGgenT** [comment]
Is https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CODEOWNERS
currently up to date as well?

**Comment by damien** [comment]
@KorGgenT It _was_, but I don't recognize `ethankaminski `. Current maintainers (that I'm aware of) include myself, @LyleSY, and @ephemeralstoryteller.

**Comment by damien** [comment]
@KorGgenT Patch to update CODEOWNERS in #39465

**Pull request merged**
