### PR TITLE
Rural Content: 4 New Farms

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content "Added 4 new farms"```

#### Purpose of change
The countryside was kind of empty.

#### Describe the solution
Added 4 new farms, all connected to existing road.
The farms share similar mapgens, like ```dirt_road_3way```, ```2silos``` and ```farm_lot_wire_straight_v```, so I didn't have to make as many. They could also be used to "mass-produce" more unique farms. ```coop_chicken``` and ```farm_lot_wire_turn_uni``` is currently unused, but I'll use it in a later PR. 

#### Describe alternatives you've considered
Creating a more ambitious project with generated dirt roads, but that would be impossible with my current knowledge. Also, scarecrows.

#### Additional context
farm_lot_2x4 farm_lot_empty_3x2 farm_lot_forest farm_lot_wired_2x3
farm
farm2

### CODE REVIEW

**Comment by I-am-Erk** [comment]
This is just lovely. Thank you.

**Comment by Chryseus** [comment]
More farms and such is always good.

**Comment by YukariMindGap** [comment]
I think you should add those rural isolated houses

**Comment by LovamKicsiGazsii** [comment]
> I think you should add those rural isolated houses

Yep. That's on my list.

**Pull request merged**
