### PR TITLE
Unobsolete and fix the Norse Evangelicals

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Unobsolete the Norse Evangelicals"

#### Purpose of change
Unobsolete the Norse Evangelicals, and fix various problems with their missions and dialouge.

#### Describe the solution
The Norse Evangelicals were obsoleted in #64417 on the basis of various complaints. This PR fixes these problems, and unobsoletes the faction.

Changes:

- Using new EOC code, the camp will spawn 7 days into the Cataclysm.
- Item ownership has been fixed for all materials in mapgen. This issue was mainly caused by a larger bug solved by #64822.
- Dialogue had been expanded to make the members sound like they are actual humans. Based on three new traits, the members now have a variable belief in Norse revivalism, and a variable backstory on how they joined. They way they speak has also been changed based upon their belief, with the non-revivalists speaking more contemporarily.
- Fixed the acetylene mission to take weld-ready oxyacetylene.

#### Describe alternatives you've considered
I have considered many alternatives:

- Having the camp spawn on day 1, and upgrade over time.
- Making all NPC's unique for custom backstories and beliefs, like those in the Refugee Center.
- Omitting the whole anti-Raiders side plot and replacing related missions with something else.
- Having the camp spawn quite a while longer in, possibly a few months.

#### Testing
I tested everything multiple times, it all works well.

#### Additional context
None at the moment, this section may change as discussion moves on.

Addendum 1:
Through further discussion, I’ve opted to switch some things around to make the camp a historical reenactment and living history center run by U Amherst, that the Valhallists have commandeered as a fortress.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
I only ever posted this in a place where you were not present but my suggestion for having this faction spawn at the early days  instead of having to delay it by months was to make it an anthropology/archeology experimental recreation managed by one of the Ivy League Universities or the Carnegie Institution. They are all nearby and could could have the means and interest to run it.

So less less trained survivalist and more a group of Researchers/Alumni trying to survive with the edge they knew they had. I think this is a pretty reasonable backstory and easily avoids most concerns that were originally raised about the faction.

Also probably avoid naming them "Evangelicals" we already have a faction named like that.

**Comment by MNG-cataclysm** [comment]
> I only ever posted this in a place where you were not present but my suggestion for having this faction spawn at the early days  instead of having to delay it by months was to make it an anthropology/archeology experimental recreation managed by one of the Ivy League Universities or the Carnegie Institution. They are all nearby and could could have the means and interest to run it.

The spawn has only been delayed by seven days, in place of a month.

**Comment by fairyarmadillo** [comment]
7 days is not going to be long enough for most players to notice that they weren't a day 1 spawn. You usually spend your first week or so getting your footing and don't really have the supplies for exploring much until later.

What's the intent behind not delaying them longer? I love seeing stuff actually change and grow in the world, rather than sitting static since world gen waiting for the main character to show up.

**Comment by Nebnis** [comment]
> The spawn has only been delayed by seven days, in place of a month. The Vikings didn't make any permanent settlements in the Western Hemisphere, either. There wouldn't be much to dig up or study pertaining to them.

I think what john meant was that they should be a group of general university students using their knowledge in general to survive, not necessarily be about norse or religion. It would change the whole scope of the theme but i would agree that kind of theme fits a whole lot better. Not that i have a problem with current one but it feels very "fallout" for the lack of better comparison. The alternatives you mentioned also all feel better.

**Comment by John-Candlebury** [comment]
> The spawn has only been delayed by seven days, in place of a month. The Vikings didn't make any permanent settlements in the Western Hemisphere, either. There wouldn't be much to dig up or study pertaining to them.

Yeah its not an actual Norse village nor an archeological site. But a "faithful simulation" used to discover possible building and farming methods through the recreation of known historical information about settlements.

You can find analogous experiments irl, often centered about building structures using only technology known at the time.

**Comment by MNG-cataclysm** [comment]
> 7 days is not going to be long enough for most players to notice that they weren't a day 1 spawn. You usually spend your first week or so getting your footing and don't really have the supplies for exploring much until later.
> 
> 
> 
> What's the intent behind not delaying them longer? I love seeing stuff actually change and grow in the world, rather than sitting static since world gen waiting for the main character to show up.

**Comment by Daved27hundred** [comment]
Do they still have that wooden fortress of a base? IMO that thing needs to be given the boot. I dunno how they managed to build that thing in the time since the apocalypse.

I think having them repurpose an already existing building is much more believable.

**Comment by pjf** [comment]
+1 for Experimental Archaeologists and Living History. They're very real thing. As references:

[**Butser Ancient Farm**](https://www.butserancientfarm.co.uk) is a well-established centre for Experimental Archaeology. It's been going for more than fifty years now, and so has extensive buildings and workshops.

[**Vlachernai**](http://vlachernai.com/) is my local Living History group that focuses specifically on Viking-age technologies. They've done temporary settlements as group activities, had their work exhibited in the Melbourne Museum, and have a truly amazing set of craftspeople.

**Comment by MNG-cataclysm** [comment]
Would the religious movement still be applicable for the living history reforms?

**Comment by pjf** [comment]
> Would the religious movement still be applicable for the living history reforms, or should that be changed with the possible switch to a new model?

All the viking age living history folks I know are *familiar* with Norse mythology, but almost none of them follow it as a religion. Most hold the same religious beliefs as the society in which they were raised. (In Australia that means watching the cricket the day after Christmas.)

**Comment by fairyarmadillo** [comment]
Living in the USA, I know some people who engage in pagan religious practices that include Viking-era deities, but I've never met a pagan who spoke like the Valhallists do. Many modern pagans treat the gods of the ancient world more as a focus for rituals or ideas, which is very different from how Christians often conceive of God. They don't talk about Valhalla and Odin with uncritical conviction.

If someone got really into Thor or whatever after the Cataclysm, I expect that unless they had kaluptic psychosis, would approach it in a much more grounded way, and they would be aware of the perceived absurdiry of it. The CDDA vikings are in an extraordinary situation, but still, these people had ordinary lives a couple of months ago and should act like it. 

A scholar theorizing that Ragnarok myths were actually some sort of warning about the Cataclysm and diving into Viking eschatology to try to better prepare their group for the days ahead could be really cool. Less awkward "skyrim belongs to the Nords!" and more "Hey I know this seems insane but I think these guys were onto something."

**Comment by harakka** [comment]
There are still a lot of challenges with the tone in the mission texts. Eg. the mission about attacking a mi-go scout tower and freeing prisoners reads like the person giving you the job has played CDDA the videogame, and knows that the mi-go location is called a scout tower and has prisoners inside, neither of which would be apparent to someone from an in-world perspective. There's an overall "purge the world from xenos" vibe in the texts that doesn't really work considering the extremely limited information that people in-world have about this brave new world and the threats in it, especially in the early days.

**Comment by MNG-cataclysm** [comment]
I've decided to go with the living history idea, and I've reoriented most of the dialogue to reflect that. Further changes and improvements will come soon

**Pull request closed without merging**
