### PR TITLE
Update German translation of MOTD/credits

### PR DESCRIPTION
**Pull request by Wuzzy2**
#### Summary
```SUMMARY: I18N "Update German translation of MOTD/credits"``` 

#### Purpose of change
To update the German translation of MOTD/credits for 0.D.

#### Describe the solution
By taking a text editor and start translating.

#### Describe alternatives you've considered
None.

#### Additional context
None.

### CODE REVIEW

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Comment by Wuzzy2** [comment]
@kevingranade: What is the commit ID?
I can't see my commit in master. :-(

**Comment by kevingranade** [comment]
Looks like I made a mistake somewhere, thanks for checking.

**Comment by kevingranade** [comment]
Really merged to 0.D and master this time.

**Pull request closed without merging**
