### PR TITLE
Fungal Zombies can see

### PR DESCRIPTION
**Pull request by pisskop**
Makes fungal Zombies "SEE", and reduces their 30 daysight to a flat 15 no matter what time.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Stuff that feels air movement and the like (insects) generally gets sight 5/5. 15 in the night is quite a lot and fungus doesn't really work well on eyes.

**Comment by pisskop** [comment]
Its a generally harmless unit.  The only real use it would have is to very occassionally puff fungus

**Comment by Coolthulhu** [comment]
The 15 sight will make it stay away from the fungals, being less effective at protecting them and taking (zombie) hits while they reload the "pouf"s.

Plus, it simply doesn't make sense for them to get better NV because of infection with fungus that doesn't have any perception-related powers.

**Comment by pisskop** [comment]
Is this acceptable?

**Pull request merged**
