### PR TITLE
Interface: Newcharacter - show proficiencies and other changes (UPDATED)

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Interface "Newcharacter - Show proficiencies"`

#### Purpose of change

Continuing with what was done in #44297 and #44465.

Changelog:

- PROFESSION TAB: **Re-added all empty values (+ previously missing like addictions)**
- DESCRIPTION TAB: Show character proficiencies
- DESCRIPTION TAB: Re-added pick nothing but a random name
- DESCRIPTION TAB: **Always show starting vehicle and starting addictions even if empty**
---

#### Screenshot(s)

PROFESSION TAB: 

grafik

DESCRIPTION TAB:

grafik

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I'm not sure if hiding empty item groups is a good idea. It's a loss of information IMO. Players could be confused: "why there's nothing said about wielded or worn items? That's because characters don't have wielded/worn items or is it a bug?"

**Comment by Pupsi-Mupsi** [comment]
Thanks. I see your point.

Do you feel the same way about '**profession skills**', '**traits**', '**pets**' and the like or is it just '**profession items**'?

**Comment by Night-Pryanik** [comment]
Honestly I personally don't consider all these "foo: none" as a clutter. As I said, information about nothing being wielded/worn or zero proficiencies is still information, and important too, so removing it I will consider as a regression. Can't say for others though.

**Comment by Pupsi-Mupsi** [comment]
I respect your opinion. I myself think that this specific information (none) is somewhat implicit and I would consider it more valuable for new players to just see what is given by a chosen profession. 
As a side effect, players have to scroll less often and can grasp the essential information more quickly. CDDA can quickly become overwhelming due to its richness.

By the way - all "NONE" information is still given on the "description tab". I know I still need to include items, pets, and spells, but I will eventually.

I was hoping to help with that, but I am willing to revert everything if there are enough votes for it.

**Comment by nexusmrsep** [comment]
I second @Night-Pryanik opinion. Character sheet boxes should be as constant as possible, much like a DnD sheets, where you have "boxes" that are either filled or not, depending of choices,  but the "box" is present in every case, so that the fact that there is an option that would "fill the box" is transparent in every case. So not only "what you see is what you get" but "... also what you don't get". Although for "wielded" it would not have impact, but with "proficiencies" for example it's quite important, and having information in plain sight that your character will not start with any is significant.

**Comment by Pupsi-Mupsi** [comment]
Would you like to see the NONE-info in the profession-tab or in the description-tab or in both? And should the previously to my PRs hidden information about addictions and spells also always output none if the player does not get any?

_"Although for "wielded" it would not have impact, but with "proficiencies" for example it's quite important, and having information in plain sight that your character will not start with any is significant."_

**Isn't it also obvious that you don't have or get something if it doesn't appear in the list?**


I personally agree with the character sheet concept. In game this is mostly represented in the @-menu. During the character generation I would prefer to see the NONE-info in the description-tab. where all other information is finally summarized I would keep the profession tab cleaner.

What about the rest of the changes (#44532, #44515, #44465, #44297 ), should they go away or can they stay?

**Pull request merged**
