### PR TITLE
workaround for "inaccurate" healing quality

### LINKED ISSUE #75736: Disinfection and bandaging not acting as it should
### Describe the bug

In the Consume screen, when I clicked on an alcohol wipe using my mouse, it just consumed it, cleaning a wound, I assume the most injured, and gave average disinfection.  If I used the keyboard, it would go to the correct screen and let me choose which wound to treat, offering poor disinfection, and then gave me average anyway.
The same happened with adhesive bandages, giving a poor bandaging, and when I go the the correct screen, it offers a very poor bandage.  I have not yet bandaged more than one slot, so I can't say what it will give if I use keyboard.

### Attach save file

[Eternal Pool-trimmed.tar.gz](https://github.com/user-attachments/files/16633608/Eternal.Pool-trimmed.tar.gz)

### Steps to reproduce

With an injured character, who has healthcare 3 and wound care proficiency, open the Consume screen, and click on an alcohol wipe, or click on an adhesive bandage.
Use the keyboard to go to the alcohol wipe or adhesive bandage, and check what it should have given.
Check the Character screen to see what it gave?

### Expected behavior

I expected clicking on the disinfectant/bandage to take me to the medical screen instead of just consuming it and using it on an injury without my input.  I also expected it to give me treatment in line with my skills and not dramatically more.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: c72f9ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sonphantrung**
#### Summary
None

#### Purpose of change
Fixes #75736 
Every time the survivor bandages, the effect's intensity is added by 1, leading to the issue above.

#### Describe the solution
Worked around the problem by making it print out the same as when the char bandages

#### Describe alternatives you've considered
I could try and prevent it from adding intensity by 1, but then I realize it's also the same in stims (e.g. black coffee's 12 stim in the JSON gives the player "Stimulants [13]" effect). Even more so, the "issue" appears way back in 0.G. The DDA src rabbit hole is so huge.

#### Testing
~~Will try and compile it later on, but just let the tests do its job first.~~
Char with 3 Health Care + Wound Care
image
image

#### Additional context
Yeah yeah I'll compile

### CODE REVIEW

**Comment by sonphantrung** [comment]
I think it can be merged now.

**Comment by akrieger** [comment]
I don't really like the idea of sprinkling random +1s around? Wouldn't it be better to take away the random +1 thats happening? Where is that?

**Comment by sonphantrung** [comment]
> I don't really like the idea of sprinkling random +1s around? Wouldn't it be better to take away the random +1 thats happening? Where is that?

Yay, a response! To answer your question, the code for adding +1 to the effect intensity resides right [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/348453333a599a0afbb829acfa145e9bc63a7ccc/src/creature.cpp#L1732).

**Comment by akrieger** [comment]
Yeah pretty sure if I were to implement that I'd have used `e.set_intensity( std::ceil(1, e.get_duration() / e.get_int_dur_factor() ) );`

**Comment by akrieger** [comment]
@sonphantrung can you try if the ceil call I wrote fixes this from the other direction, by not unnecessarily buffing healing (or other low intensity effects)?

**Comment by sonphantrung** [comment]
Yeah, I'm doing that one, but I think it should be std::max, as I don't think ceil function supports two arguments

**Comment by sonphantrung** [comment]
https://github.com/sonphantrung/Cataclysm-DDA/actions/runs/10759264269/job/29835730686 Compile error that I'm boggling my head.

**Comment by akrieger** [comment]
Aha. Try `e.set_intensity( std::max( 1, static_cast<int>( e.get_duration() / e.get_int_dur_factor() ) ) );`.

**Comment by Night-Pryanik** [comment]
@sonphantrung is this ready?

**Comment by sonphantrung** [comment]
Nah, should close this, as my goal now change from "sprinkling +1s" to "searching the problem that caused the +1 effect intensity".

**Pull request closed without merging**
