### PR TITLE
Disable some effects during sleep

### PR DESCRIPTION
**Pull request by Coolthulhu**
- Acid burn won't happen during sleep. Instead happens more often when awake (one in 1500 -> 1200). This prevents having to attempt sleep over and over, mended limbs un-mending themselves during the same sleep they mended in.
- Disintegration mutation gets same treatment: faster rot, but not during sleep.
- Painful electrical discharge and hallucination bionics stop acting during sleep. Their effects during sleep were mostly limited to message spam.
- Itchy bionic would randomly stop sleep, but have no real consequences. Also disabled during sleep.
- Bio spasm, which causes very minor pain and downing, doesn't make sense for sleeping characters (who are lying down already). Also prevented from acting up

### CODE REVIEW

**Comment by kevingranade** [comment]
I agree with the last three, if there is no effect other than bothering the
player they should just imact sleep quality directly if anything.

Simply shifting damaging effects from sleep time to waking time doesn't
make sense though, those effects can and should kill the player in their
sleep if they don't take measures to prevent it.  How about if the damage
application doesn't wake the player?  These are preexisting conditions, not
acquired during sleep, so there is no need to warn them it is happening.
If you want to be extra nice we could silence the messages unless the
player reaches a critical health threshold, then wake them.

**Comment by Coolthulhu** [comment]
>  those effects can and should kill the player in their sleep if they don't take measures to prevent it

Sleep healing overpowers them.
Average sleep healing is 1 per 20 minutes (200 turns). Half that with slow healing.
Acid was 1 per 1500 turns. Rot2 was 1 per 1500 turns. Rot3 was 1 per 600 turns.

So with rot3, slow healing and acid:
* Healing 1 hp per 400 turns = 30 hp per 12000 turns
* Rot3 1 hp per 600 turns = 20 hp per 12000 turns
* Acid 1 hp per 1500 turns = 8 hp per 12000 turns

So even rot3, slow healing and acid aren't enough to cause death in sleep, barring very bad luck coupled with very low hp when falling asleep. And anyone with rot3 will be very wary of not getting slow healing or acid discharge.
The character would still most likely rot to death, just not in sleep.

**Comment by kevingranade** [comment]
On Jul 29, 2016 8:46 PM, "Coolthulhu" <notifications@github.com> wrote:
>>
>> those effects can and should kill the player in their sleep if they
don't take measures to prevent it
>
> Sleep healing overpowers them.

In that case, this:
>> How about if the damage application
>> doesn't wake the player?

Solves the problem, and will do the right thing in cases where the damage
isn't overpowered by healing.

**Comment by mugling** [comment]
Could we reopen and just merge that last three? Message spam/interruption during sleep/crafting is a painful UI problem

**Pull request closed without merging**
