### PR TITLE
Fix active transformable mutations not contributing instability

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Bugfixes "Transformed active mutations (extended claws etc) properly cause instability"

#### Purpose of change
Someone asked how the new instability system interacts with mutations that transform, since their transformed variants have valid:false (you mutate only the inactive version of the trait). As a result when active they didn't cause instability.

#### Describe the solution
If the first check is failed, then also try checking to see if it has a transformed mutation target, and if it does, if that target is valid, and if it is, if either it or its transformed version has >-1 point cost. 

#### Describe alternatives you've considered
n/a

#### Testing
Tried on mainline; mutated long fingernails -> claws -> retracted claws, extended my claws, and then used Alpha mutagen. Instability was 0.
Compiled the branch with my changes locally. Mutated long fingernails -> claws -> retracted claws, extended my claws, and then used Alpha mutagen. Instability was 6 as expected.

### CODE REVIEW

**Comment by Venera3** [comment]
The major limb mutations use long-term transformations into otherwise-imvalid mutations so this will still miss them - they do have changes_to generally, so you could filter there as well. 

What's the reason for the validity check in the first place?

**Comment by anoobindisguise** [comment]
> What's the reason for the validity check in the first place?

So, I'm checking validity because I'm counting all traits the player has, but not all traits they have that aren't base traits are mutations. The alternative would be to for each trait check if its category entry isn't empty if it wasn't a base trait or a threshold or negative which would work since Extended Claws for example belongs to Feline but isn't valid. I was using valid as a shorthand for "it is mutable". If there are other technically-mutable but invalid mutations then this solution might not work perfectly.

**Comment by Venera3** [comment]
Since we don't do category-less actual mutations that would be my suggestion, yeah. As long as you document that invalid traits still need a category to count for instability it shouldn't lead to too much breakage.

**Comment by anoobindisguise** [comment]
> Since we don't do category-less actual mutations that would be my suggestion, yeah. As long as you document that invalid traits still need a category to count for instability it shouldn't lead to too much breakage.
> 
> (also, please document the new instability cal in mutations.md in some form)

OK, I did this and confirmed it looks like it's working.

**Pull request merged**
