### PR TITLE
More robust test for multi material portions

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
Should de-flake the recent test in #55405

#### Describe the solution
test now tests against the identical armor but if it were broken. So if they aren't basically identical the code is working.

Also to make this pass I fixed a potential divide by 0

#### Testing
If it passes it should be good.

### CODE REVIEW

**Comment by BrettDong** [comment]
Seems the UBSan test fails because of a division-by-zero error at
https://github.com/CleverRaven/Cataclysm-DDA/blob/7fa132e84494d52c63da0f9af985e70aca2d7cfc/src/item_factory.cpp#L786-L793

**Comment by bombasticSlacks** [comment]
> Seems the UBSan test fails because of a division-by-zero error at

Thanks for letting me know I'll PR a fix.

**Comment by BrettDong** [comment]
The test still fails
`   !(5.9342f == Approx( 5.9210000038 )) `

**Comment by bombasticSlacks** [comment]
Alright I think the issue was the armor values were small enough that since damage is bottomed/rounded to an int when applied to hp in a lot of cases the small differences between the two armors weren't enough to get to the next whole number. The increased thickness should effect it enough to make this reliable.

**Pull request merged**
