### PR TITLE
Fix night vision range bug

### PR DESCRIPTION
**Pull request by Coolthulhu**
Night vision range was effectively capped to day vision range, meaning that critters with good NV and bad DV were effectively blind all the time.

There is also this weird thing with monsters calculating their vision range based on light on the target position and not own, but it actually makes sense when you think about it so I didn't change that.

### CODE REVIEW

**Comment by Treah** [comment]
I think something else might be broken however..... I have Z's tracking me in the middle of the night like it was day. Like they are able to find me even when they are out of night vision range.

**Comment by Coolthulhu** [comment]
Most likely smell or sound

**Comment by Treah** [comment]
That's unlikely as I havent seen this type of behavior before the last pull. They find me even if im sitting still making no noise and im not carrying anything that smells
ill verify

**Comment by Coolthulhu** [comment]
> im not carrying anything that smells

Smell is from the character, not items.

**Comment by Treah** [comment]
Well I don't have that trait but it looks like it was just that Z or something else. :P

**Comment by pisskop** [comment]
Zs can hear pretty well.

they path to the sound of you walking from a short distance away, and Im not sure people understand how loud combat is now.  Melee is louder than walking, and law of osmosis means that eventually 1 zombie will wander into your scent trail.  It only takes one zombie to smack the side of a truck to pull the horde.

Vision is not quite as OP as it used to be, and scent and hearing can make up for it at night in the city.

**Comment by codemime** [comment]
> There is also this weird thing with monsters calculating their vision range based on light on the target position and not own, but it actually makes sense when you think about it so I didn't change that.

I'd say it would make sense to take both into account. When a monster is well-lit (outside by the sunlight), it should have difficulties in spotting an enemy hiding in darkness (e.g. deep inside of a house). The special case "if you see me, I see you" simply shouldn't work here.

**Pull request merged**
