### PR TITLE
This fixes #26544 | Adding Translation-Markup

### LINKED ISSUE #26544: Missing Translation Marking
**Describe the bug**  
Missing Translation Marking in src/iexamine.cpp on line 4112
Nothing to fancy. Unless i'm missing something it should be fixed fairly easy.

**Screenshots**  
before (left) -> after (right):
grafik

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
Forked the repo today and added the missing code to speed things up.

#### Purpose of change
Missing translation markup

#### Describe the solution
Adding in translation markup

SUMMARY: Bugfixes "Adding Translation-Markup"

### CODE REVIEW

**Comment by AMurkin** [comment]
Add this line to your post:
SUMMARY: Bugfixes "Adding Translation-Markup to iexamine.cpp"

**Comment by AMurkin** [comment]
Jenkins rebuild.

**Comment by AMurkin** [comment]
This is strange:
```
To run this automated build, certain files must be exactly as in master:
+++ Makefile
```
ping @narc0tiq

**Comment by narc0tiq** [comment]
Nothing strange about it, it's been that way for years. PRs that modify the Makefile or the source of `chkjson` aren't allowed to build automatically, for security reasons.

**Comment by narc0tiq** [comment]
Wait, I take that back, that's not a change from this PR, is it? I'll investigate.

**Comment by narc0tiq** [comment]
Looks like something @veid was trying to do -- he [offered to help fix the osx builds](https://github.com/CleverRaven/Cataclysm-DDA/issues/23171#issuecomment-435189078) some time ago and I just today created his user. I've reverted the change, so **Jenkins rebuild**.

**Comment by AMurkin** [comment]
Thank you.

**Pull request merged**
