### PR TITLE
Remove UPS Conversion Mod

### LINKED ISSUE #29961: UPS conversion mod don't work
**Describe the bug**  
UPS conversion mod don't work. 

- Can't install on pre-patch items;
- Can install but doesn't charge after-patch items

**To Reproduce**  
1. Spawn `Mechanized Infantry Carrier` vehicle
2. Turn on engine and UPS charge station
3. Wish for flashlight and UPS conversion mod
4. Attach mod to flashlight (Can't attach to pre-patch items.)
5. Drop flashlight to UPS recharge station
6. Wait long period of time (i've waited ~16 hours)
7. Item dont charges.

**Expected behavior**  
After patch item should charge, pre-patch item ideally too

**Versions and configuration:**
 - OS: Windows 7
 - Game Version: 0.D-2247-g97d7e5b
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
Pull request: #29651

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Content "Remove UPS Conversion Mod"

#### Purpose of change
With #29651 , most tools no longer have any inherent battery storage. Consequently, applying a UPS Conversion to a tool causes it to be unable to take any charge (due to no longer accepting a magazine). The item mod is also functionally obsolete, since its primary purpose was to make tools rechargable in a UPS-Compatible Recharging Station, and this is already the case (as all current battery cells are rechargable).

Fixes #29961 

#### Describe the solution
Removed UPS Conversion Mod, its recipe, and all mentions of it in any other files in the tree (including mainlined game mods).
Also added it to `migration.json`, transforming to a small storage battery (the most 'valuable' component used in crafting the mod).

#### Describe alternatives you've considered
It's possible to give the UPS conversion mod a degree of power storage, enabling it to serve *some* purpose in light of the current state of non-vehicle-charger UPS ignoring battery cells, but I'm not sure how the best way to do that is (or if it's even desirable).

### CODE REVIEW

**Comment by DracoGriffin** [comment]
Removing this doesn't seem like an appropriate fix, unless there is some plan to restore it somehow else?

**Comment by esotericist** [comment]
> Removing this doesn't seem like an appropriate fix, unless there is some plan to restore it somehow else?

Battery cells can already be recharged in a UPS-compatible recharger, which was the primary of the conversion mod.

**Comment by HKMist** [comment]
UPS Conversion Mod is just break by the battery update and not obsoleted.

One of the main usage of ups conversion is to make tools run on standard battery to able to directly power by UPS/ Bionic power with UPS upgrade, the new battery system just annoy this function of the mod.

Item install with ups conversion mod before the battery update now functioning in a strange way, it will drain its own battery first, when its own battery is out it will start draining UPS/Bionic power until it is off, And if the item is turn off, it won't turn on again until it is recharge even with a UPS.

Unload a battery to recharge is good but it can't/shouldn't replace the direct supply function. And outright remove everything relay to the mod seem too early, it is better trying to fix it or at least add something to replace the function of the mod first.

**Comment by esotericist** [comment]
> Unload a battery to recharge is good but it can't/shouldn't replace the direct supply function. And outright remove everything relay to the mod seem too early, it is better trying to fix it or at least add something to replace the function of the mod first.

Wouldn't it be preferable to make the UPS devices/CBM directly charge chargable cells? They've already been established as being UPS-compatible by the fact they can be charged in a UPS-compatible recharging station.

**Comment by esotericist** [comment]
Didn't expect the conversion mod to feature in tests. I'll look into that later.

**Comment by egorzaderiy** [comment]
Isn't the primary function of UPS mod is to allow directly charge tools withour battery reloading? At least this functionality needs to be restored, isn't it?

**Comment by HKMist** [comment]
Yes, let UPS charge battery directly is a solution but honestly I think it will involve some bigger problem later. 
First, You will not want to auto recharge everything in your bag, CBM can be off but UPS device can't, so if you have a electric jackhammer(not UPS modded) and a laser rifle, before the update you would have any trouble. But if UPS auto recharge everything run on battery, you will need to do some extra click on power management.
Second, I think there are some people don't like the idea of all battery being rechargeable and going to made a mod to separate battery to rechargeable and not rechargeable later.  :P

**Comment by esotericist** [comment]
> Second, I think there are some people don't like the idea of all battery being rechargeable and going to made a mod to separate battery to rechargeable and not rechargeable later. :P

For what it's worth, more batteries are almost certainly coming, including non-rechargables. The big chance recently was on getting the game to use batteries as magazines in the first place.

Your other points are pertinent, though.

**Comment by esotericist** [comment]
Closing, to approach this in a different way (as well as fix other broken things).

**Pull request closed without merging**
