### PR TITLE
[DONE] Monster consumption special attacks

### PR DESCRIPTION
**Pull request by acidia**
Two very simple special attacks to be used by some of the carrion spawns to make them more "interactive".

eat_crop is designed for locusts and simply allows the creatures to remove one crop in an adjacent square.  I'll probably add this special to cows, horses, deer, and moose so that the player is encouraged to fence crops off or hunt large mammals.

eat_food is designed for roaches (both types) and lets them remove one charge or item of food in an adjacent title.  Probably going to be added to pigs, bears, and ants.

Goal is to encourage the player to protect food stashes, although animals don't path to items (and I don't have an immediate desire to add it), carrion spawning can cause infestations if you don't monitor it.  For #23930.

### CODE REVIEW

**Comment by DracoGriffin** [comment]
Looks interesting!

**Comment by smolbird** [comment]
I can see this being hard for the player to control though...

**Comment by acidia** [comment]
To get a good test on these throw
`	"special_attacks": [ [ "EAT_FOOD", 25 ] ],`
On giant cockroaches and 
`    "special_attacks": [ { "type": "leap", "cooldown": 2, "max_range": 8 }, [ "EAT_CROP", 10] ],`
On giant locusts.  The special attacks trigger way too often with these values but you'll get to see them in action.

**Comment by kevingranade** [comment]
One issue I have with this is that it's a difference in the way the game world works based on whether the player is present or not.  The best way to protect your food is to keep it away from you, so you might want to make a food stash and only visit it occasionally to drop off or pick up food, because if it's on the map it'll attract vermin.

I think if we recognize that and make a note to fix it it's fine for now, because we don't have the infrastructure to do anything about it right now.

**Comment by ZhilkinSerg** [comment]
Needs conflict resolution.

**Comment by acidia** [comment]
Shouldn't interact with any of the new flags.

**Pull request merged**
