### PR TITLE
Rope, wire and barbed wire fences are now built and removed through the construction menu

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Added construction and deconstruction recipes for the fences, removed four `iexamine` functions.

### CODE REVIEW

**Comment by AMurkin** [comment]
Suggest switch usage:
```c++
    std::string result;
    
    switch( tid ) {
        case t_fence_rope:   result = "rope_6";      break;
        case t_fence_wire:   result = "wire";        break;
        case t_fence_barbed: result = "wire_barbed"; break;
        default: return;
    }
    
    add_msg( m_info, _( "You remove the %s." ), g->m.tername( examp ).c_str() );
```
And would be better to lookup items in json for corresponding id, and spawn them?

**Comment by Night-Pryanik** [comment]
I tried that. The compiler complains about `case t_fence_rope:` part.

**Comment by codemime** [comment]
Concerning fences: it would be nice to move them to the Construction menu, and get rid of all those `iexamine` actions.

**Comment by codemime** [comment]
> Now for deconstruction it needs standard deconstruction tools

The original behavior can be preserved via adding the `EASY_DECONSTRUCT` flag. Using a screwdriver as a tool for dismantling rope fences seems rather weird.

**Comment by codemime** [comment]
I just encountered a corresponding issue #22545. It appears that your PR now would close it.

**Comment by Night-Pryanik** [comment]
> I just encountered a corresponding issue #22545. It appears that your PR now would close it.

I saw this issue too, but @ShadowDragon8685 proposed to move deconstruction of chain link fence (named Wire Fence in construction menu) to construction menu from the use of hacksaw.
I decided that "deconstructing" metal terrain or furniture through the construction menu offered less opportunities than through iuse, so I left them as is in #22609.

**Pull request merged**
