### PR TITLE
Long pole changes.

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary

```SUMMARY: Balance "Rework long pole"```

#### Purpose of change
The long pole was craftable from logs which would probably be too small for a one piece 10 foot shaft.
The long pole behaved very differently from the pike / wooden pike, despite being the same item but pointless.
You could only learn the long pole recipe from the eastern smithing book, which felt odd due to it being an all time human classic and not that complicated for someone with enough fabrication skills.

#### Describe the solution
Make the long pole recipe use a wood beam rather than log.
Make the long pole recipe autolearn, but later than you could learn it from a book.
Give the long pole the same weapon flags as the wooden pike.
Lower the damage of the long pole so it isn't a better weapon than the wooden pike.

### CODE REVIEW

**Comment by Xenomorph-III** [comment]
How long is a heavy wooden beam in-game, compared to the plank?

**Comment by enaantd** [comment]
why does the long pole get the `DURABLE_MELEE` flag?
also, I'm hesitant about the `SHEATH_SPEAR` flag, isn't 3m (10 feet) too long to be sheathed?
otherwise I agree with the change

**Comment by kevingranade** [comment]
Durable melee doesn't really make sense, especially with as hard as you have it hitting.
Sheath spear definitely doesn't work, the only way you're going to move around with one of these is carrying it.

**Comment by Brian-Otten** [comment]
I thought sheath spear was iffy myself, but it was on the pike so i put it on this as well. i will go ahead and remove sheath spear from all the pike weapons.
Since the shaft is the same as used in pikes i thought it was only fitting for it to also have the durable melee flag, but there is something to be said that the fighting style involved with this involves more risk to the weapon, so i will remove the durable_melee flag.

**Pull request merged**
