### PR TITLE
[Ready] Enhanced Memory Banks rework: Now increases learning speed and map memory

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Balance "Enhanced Memory Banks now increases skill learning speed."``` 

#### Purpose of change
With skill rust disabled by default, heavily encouraged to stay that way and, I believe, on the chopping the block, Enhanced Memory Banks is currently a CBM with a very high difficulty (9) that serves no purpose at all. Many professions start with this bionic, but get no use out of it,

A new purpose for EMB gives it a reason for existing and to justifies the high difficulty of installing it. Now it isn't something that just clutters up the CBM spawnlists, but an actual useful bionic!

#### Describe the solution
Now, Enhanced Memory Banks:
* ...costs 10 power to activate, and consumes 1 power every 100 turns. All effects in the list following this one require EMB to be active.
* ...boosts effective focus by +10 when practicing skills (similar to Fast Learner, which offers +15.)
* ...increases experience gained from books (seems to be roughly +2% to +4% per chapter.)
* ...boosts map memory to 5000 overmap tiles, up from a default of 100.
* ...retains its old function, but displays a message when the power is consumed instead of being silent.

#### Describe alternatives you've considered
I considered making it much less difficult to install, but because skill rust is very all-or-nothing, this would likely make it very powerful while it's enabled, and wouldn't solve the issue of it not serving any use while rust is disabled.

I was originally only going to make it affect learning speed for practicing skills, but realistically speaking, perfect memory would make it easier to read, too; less rereading passages to make sure you understood something, and the speed of memory storage would increase comprehension in general.

### CODE REVIEW

**Comment by MT-Arnoldussen** [comment]
Just FYI, this CBM might get a second use already after #25551 gets merged. It's not in that PR but it would be an obvious candidate to be involved with map memory as someone else already mentioned there.

Apart from that, this does seem like a good, especially for such a difficult to install bionic.

**Comment by kevingranade** [comment]
> With skill rust disabled by default, heavily encouraged to stay that way and, I believe, on the chopping the block

Not at all on the chopping block, no one has cared to fix it, but the plan is still to have skill rust that applies a penalty, but doesn't impact effective skill level.

**Comment by Kelenius** [comment]
>Just FYI, this CBM might get a second use already after #25551 gets merged.

It would actually fit nicely with this PR, which makes the CBM toggleable.

**Comment by Xhuis** [comment]
How does it function right now? Not super up to date on the mechanics of map memory there.

**Comment by MT-Arnoldussen** [comment]
This makes the CBM toggleable? I thought it already was.

The PR does currently not do anything with this CBM. But since the PR introduces a new variant of memory, it would only make sense for it to help somewhat.

**Comment by Xhuis** [comment]
It was already toggled, indeed. It just had no idle power consumption; it only consumed power when preventing the skill drop. Now it consumes a little power automatically since it has other effects.

Since map memory appears to be persistent, I'm just not sure how I would make it interact with this CBM. Does it fade after a few days?

**Comment by Kelenius** [comment]
...sorry, I mean to say that it gives it a function that is active all the time when the CBM is turned on. Since it currently only drains power when it prevents skill rust.

**Comment by Xhuis** [comment]
It's no worry. I'm sure map memory could be intertwined with it somehow, but that's a story for another day.

**Comment by Xhuis** [comment]
I added on functionality for map memory; while active, it boosts memory to a massive 5000 overmap tiles. Despite this being a massive amount, for many people it won't come into play; nonetheless, I've increased the power consumption to 1 per 100 turns rather than 1 per 200 turns to compensate.

**Pull request merged**
