### PR TITLE
Adjust size of cows

### PR DESCRIPTION
**Pull request by NotFuji**
```SUMMARY: Balance "Adjust size of cows"```  

#### Purpose of change
Cows are smaller than they should be.

#### Describe the solution
Made cows bigger.

http://www.thecattlesite.com/breeds/dairy/22/holstein/

Volume is approximated as a 3.6ft x 6ft x 3ft prism extrapolated from 4.8ft shoulder height and Photoshop magic to cut off the legs.

### CODE REVIEW

**Comment by Ilysen** [comment]
This may not be the place to say this, but I also noticed that the zombear and antlered horror were very small (around the same size as the old cow before this pull request fixed it.) Maybe we should fix that relatively soon?

**Comment by KorGgenT** [comment]
volume doesn't need to match weight. in fact, it probably shouldn't.

**Comment by Night-Pryanik** [comment]
Wolf volume was changed too, is this intentional? If so, you might want to rename the PR to reflect the changes.

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Comment by kevingranade** [comment]
I merged before the wolf change, that will need a follow up if you still want to do it.

**Comment by NotFuji** [comment]
Not sure how that even got there, I changed the wolf, but to a different number that was slightly higher, not lower.  Then deleted it because it was too similar to make a difference.

Whatever, it's gone now anyway 🤷

**Pull request closed without merging**
