### PR TITLE
Update Bronse Fileset Recipe Reqs now that new tool added

### PR DESCRIPTION
**Pull request by Consoleable**
#### Summary
None

#### Purpose of change
Update Bronze fileset so it can be made with bronze chisel

#### Describe the solution
change required chiseling from 3 to 2 to match the bronze chisel

### CODE REVIEW

**Comment by Consoleable** [comment]
I dont understand why there are 12 commits instead of 1? I only changed one file in my branch after the previous PR where i made the other 11 commits mentioned here. It seems like they shouldnt be here, but im not sure what i did wrong :/ 
Just when i think i understand github I get confused.

**Comment by PatrikLundell** [comment]
Did you update your master copy from the official master after the previous PR was merged (assuming it has been merged: if it hasn't then this result is expected)? If you haven't, that's the answer: your copy presents the changes it has compared to what it had last updated from the official master.

Also, as the automatic message tells you, you're supposed to update your master from the official master, then create a branch, switch to that branch, make your changes, commit them, push that branch, and make a PR from that branch. When it's been merged you can then delete that branch.
This allows you to keep your master copy untainted by local changes and also somewhat juggle multiple PRs in parallel by having them in separate branches.

**Comment by Consoleable** [comment]
> Did you update your master copy from the official master after the previous PR was merged (assuming it has been merged: if it hasn't then this result is expected)? If you haven't, that's the answer: your copy presents the changes it has compared to what it had last updated from the official master.
> 
> Also, as the automatic message tells you, you're supposed to update your master from the official master, then create a branch, switch to that branch, make your changes, commit them, push that branch, and make a PR from that branch. When it's been merged you can then delete that branch. This allows you to keep your master copy untainted by local changes and also somewhat juggle multiple PRs in parallel by having them in separate branches.

1. Ye! I made sure to update my master after the last PR, so it wasnt behind. Even though i did this AND the previous PR was merged, it still says my master is commits ahead, but those commits were made to CDDA, which i assume is why they don't show up as changes here. 

2. I think your explanation of what I should be doing is thorough, but i can be pretty dense, and I'm still pretty lost about how to switch to branches and squash commits?/PRs? together? I really would like to be able to confidently make changes to multiple files and submit a cleanly defined PR, but I'm still a bit confused on using the web interface to make multi file PRs, ad some of the github terminology is still opaque to me. I appreciate you taking the time to try and explain. Hopefully I'll get a handle on it soon.

**Comment by PatrikLundell** [comment]
I dislike git a lot, and am able to perform only a very limited number of activities with it (and the documentation isn't useful because it drown you in an enormous number of commands, each with a huge number of parameters, so you can't find anything in that jungle, especially since there appears to be many different ways to set it up, with different commands applicable only to different setups)... I also don't use the web interface, and don't know how it works (with the exception being the generation of the PR from the uploaded branch).
You're probably not the only one who cannot use the web interface to commit multiple files at the same time: there's a lot of spam notifications of some people committing one file at a time...

Commands given locally from the command line:
- git branch whatever: creates a branch named whatever
- git switch whatever: switches to the whatever branch. Note that the command above doesn't do that.
- git branch whatever --delete: Get rid of the branch after your PR has been merged. Note that you have to be on a different branch to do that (typically by switching back to master).

I don't know how to squash things...

**Pull request merged**
