### PR TITLE
map memory: remember furniture, vehicles and traps

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Bugfixes "map memory: remember furniture, vehicles and traps"```  

#### Purpose of change
https://discourse.cataclysmdda.org/t/base-terrain-showing-through-objects/16739

#### Additional context
Prevent vehicle snakes at night by only remembering non moving vehicles.
auswahl_018

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Nice screenshot!

**Comment by OzoneH3** [comment]
Fixed that nice snake feature :P

**Comment by ZhilkinSerg** [comment]
I would leave it as a feature for hallucinating characters.

**Comment by Kelenius** [comment]
The character should memorize both the ground tile and the object on it, or some items would look strange.

**Comment by AMurkin** [comment]
Maybe not objects itself but some fuzzy entities. Non-passable entity, undefined items etc.

**Pull request merged**
