### PR TITLE
Recipes for screwdrivers( set)

### PR DESCRIPTION
**Pull request by kwl01skz**
#### Summary
SUMMARY: Balance "Let one screwdriver recipes produce screwdriver set."
 
#### Purpose of change
There are two recipes for screwdrivers, one is simple, and the other is complex (so useless).
At the same time, there is a lack of recipes for screwdriver sets.

#### Describe the solution
Modify one of the screwdriver recipes.

### CODE REVIEW

**Comment by Lamandus** [comment]
Are our tools even capable producing sxrew driver sets? I am not sure about that. Also just changing it to set without changing materials or anything else is a bit... Lazy

**Comment by Kelenius** [comment]
Aside from the survivor's ability to produce a screwdriver set by smithing, you would need to, at the very least, modify this recipe. Screwdriver set should require more materials.

IIRC this specific recipe was actually added for the innawoods characters.

**Comment by FulcrumA** [comment]
I recall discussion about this when I talked about creating a recipe for screwdriver set myself. The general consensus was that creating such a set would be possible for survivor of level high enough, with a set of other tools, even if the final product would be somewhat below quality of properly, precision-machined ones. Would be enough however for what we use screwdriver sets for in the game.

I've suggested, since screwdriver itself is rather generic, that creating such a set could require several screwdrivers as one of the ingredients before they'd be processed further (in which case there wouldn't need to be any forging involved as it'd be just gathering of various screwdrivers of different kinds into a complete set). I also agree that there should be more materials used than some piece of plastic. Personally I'd suggest something more along the lines of

`{
    "type": "recipe",
    "result": "screwdriver_set",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "skills_required": [ "tailor", 2 ],
    "difficulty": 3,
    "time": 7000,
    "autolearn": true,
    "using": [ [ "sewing_standard", 60 ] ],
    "qualities": [ { "id": "HAMMER_FINE", "level": 1 } ],
    "components": [ [ [ "screwdriver", 6 ] ], [ [ "leather", 8 ] ]
},`

...for a set made out of scavenged resources (tailoring used to make a container that'd keep the whole set together as one item along the lines of repair kit) and...

`{
    "type": "recipe",
    "result": "screwdriver_set",
    "id_suffix": "forged",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "skills_required": [ "tailor", 2 ],
    "difficulty": 6,
    "time": 180000,
    "autolearn": true,
    "using": [ [ "forging_standard", 10 ], [ "steel_tiny", 1 ], [ "sewing_standard", 60 ] ],
    "qualities": [ { "id": "ANVIL", "level": 3 }, { "id": "HAMMER_FINE", "level": 1 }, { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "swage", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ] ],
    "components": [ [ [ "plastic_chunk", 6 ], [ "duct_tape", 180  ] ],  [ [ "steel_chunk", 12 ], [ "scrap", 36 ] ], [ [ "leather", 8 ] ] ]
},`

...for one made from scratch (multiplying resources required for screwdrivers themselves, allowing plastic chunks as an alternative to duct tape handles and again, introducing leather container components).

**Comment by Treah** [comment]
@FulcrumA 
I think these would need to use something other then tailoring? That seams like an odd choice for something thats either mechanics or fabrication.

**Comment by Lamandus** [comment]
wait, so this PR got merged? Really? With no user being for the change? And making the whole screwdriverset with one plastic chunk?

Quality control anybody?

**Comment by Lamandus** [comment]
> 
> 
> > making the whole screwdriverset with one plastic chunk?
> 
> It's like, a pound of plastic, and this makes the smithing recipe actually useful.

it was usefull already in the "in the woods" scenario. Yes excessive a bit but still useful. Now it is just imbalanced. Sorry but I really think it needs tweaking.

**Pull request merged**
