### PR TITLE
Aftershock: Add "injection dialogue" to bio of Sadie.

### PR DESCRIPTION
**Pull request by KymasTuran**
#### Summary
Features "Add a way to receive another injection after recruit Sadie."

#### Purpose of change
Add a way to receive another injection after recruit Sadie because I cannot find the dialogue anymore after recruit her.

#### Describe the solution
Add dialogue to bio.

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
You need to move "Add a way to receive another injection after recruit Sadie" to the "Purpose of Change" section to fit with formatting standards.

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by Zireael07** [comment]
Why close?

**Comment by Maleclypse** [comment]
Are you able to add a limit to how often this injection can happen?  No more than once every seven days.  Let me know and if you can't, I'll work on adding the time limit.

**Review by Maleclypse — CHANGES_REQUESTED** [review]
I'll be able to approve this once it has some kind of limit to how frequently it can be requested.

**Comment by KymasTuran** [comment]
Sorry for the delay.
Something like this: { "topic": "TALK_DENY_PERSONAL", "effect": { "npc_add_effect": "asked_to_train", "duration": 36000 } }
Not sure how to.
I never ask her more than once a day, though the timer was already implemented by the Aftershock dev :p

**Comment by Maleclypse** [comment]
> Not sure how to. I never ask her more than once a day, though the timer was already implemented by the Aftershock dev :p

I'm not sure what you mean.  Candlebury and I are the Aftershock devs and neither of us have touched Sadie, she was made by friend of the mod Lyle and when I look through her existing dialogue there is no timer on her only how long the effect last's for.

**Comment by KymasTuran** [comment]
I keep receiving notifications from this but don't know what to do.
I don't know how to implement a limit to the amount of times one can request  heal. Perhaps some copy paste from the nurse in the ranch?
Feel free to do any change you like or close this.

**Comment by Maleclypse** [comment]
I'll try and suggest some changes this week.

**Pull request closed without merging**
