### PR TITLE
Small improvement of surgery UI

### LINKED ISSUE #28714: Bionic installation shows success/faulure messages before the operation
**Describe the bug**  
When you install a bionic the success/failure messages come before the operation starts.

**To Reproduce**  
Install a bionic on the autodoc.

**Expected behavior**  
You should get success/failure messages after the operation.

**Screenshots**  
Here I install a Power Storake Mk. II
operation

**Versions and configuration(please complete the following information):**
 - OS: W10
 - Game Version: 0.D-498-g5b6a055 (tiles)
 - Graphics version: Tiles
 - Mods loaded:   "dda",  "no_npc_food",  "filthy_morale",  "No_Anthills",  "No_Bees",  "No_Fungi",  "vertakoski",  "caliber_in_name",  "deoxymod",  "Urban_Development",  "alt_map_key"

**Additional context**

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Interface "Small improvement of surgery UI"```

#### Purpose of change

Improves UI of installing/uninstalling CBMs.
fixes #28714
#### Describe the solution

- [x] Can't select CBM in menu if you don't have enough anesthetic
- [x] Put messages in the right order
- [x] Bring the install menu to cbm uninstall

- ScreenShots:
   - Install with some anesthetic:
image
   - Uninstall with some anesthetic:
image
(I don't know why the CBMs display in grey)
   -Install/Uninstall with no anesthetic: 
image
 -Install/Uninstall with anesthetic kit:
image

#### Additional context

In order to display the menu for uninstallation the game adds CBMs corresponding to your bionics to your inventory and remove them after you've made your choice.

This also make Bionic require a CBM item to be defined (unless they are `included`) otherwise the game will throw an error at load and Bionic without corresponding CBM Item will unremovable.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
While you're here, could you please place a period at the end of the `You set up the operation step-by-step, configuring the Autodoc to manipulate a CBM` string in `introduce_into_anesthesia` function?

**Comment by Fris0uman** [comment]
@KorGgenT Should `has_enough_anest()` go in `avatar.cpp` instead of `player.cpp` ?

**Comment by KorGgenT** [comment]
do you expect an NPC to ever use this function? if so, put it in `Character`.
otherwise, put it in `avatar`. this goes for all new functions as well. If you don't know, i'll do a more thorough review later.

**Comment by Fris0uman** [comment]
Turns out that since it uses `crafting_inventory()`moving it to Character is not trivial. It should be ok to leave it as is since the definition is in `player.h` but the function is actually in `bionic.cpp`

**Comment by KorGgenT** [comment]
i see. i suppose that's one more thing to add to the "deprecate player class project"

**Pull request merged**
