### PR TITLE
[CR] Adaptive (windowed or fullscreen) inventory menus

### LINKED ISSUE #19059: Inventory view centering
@codemime how hard would this be to implement  this (probably toggled via `bool fullscreen`):

ready

I'm poking around in the code now but it might be obvious to the original author

### PR DESCRIPTION
**Pull request by codemime**
Follows #18996 ([this](https://github.com/CleverRaven/Cataclysm-DDA/pull/18514#issuecomment-256186197) in particular).
Closes #19059.

### Observable behavior

Any of the existing inventory menus can now be shown either windowed or fullscreen. That depends on their contents and the current screen resolution. The titles became white and have no colons (for consistency).

**Windowed, non-empty**
screenshot_2016-11-11_01-18-14

**Windowed, empty**
empty_invent

**Window size adjusts to the longest string (either columns, or header, or footer)**
footer1
footer21

**There's a threshold for snapping to the screen boundaries (4 glyphs for each side)**
partial_snap

**When the menu snaps to all the boundaries, it goes fullscreen (no border, as before)**
fullscreen

**Hight resolution**
fullscreen2

Also, screen updates were slightly adjusted.

### CODE REVIEW

**Comment by mugling** [comment]
@codemime much obliged, I'll take a look at this further

**Comment by mutability** [comment]
Subjectively, this seems to make moving through the inventory much slower (maybe 200ms to react to a keypress?)

**Comment by mutability** [comment]
For some reason, much more noticeable/slower on the multidrop ('d') screen than the regular inventory ('i') screen.

Linux, tiles, 220x60 window; both 'd' and 'i' appear windowed in this setup.

**Comment by mutability** [comment]
If I force inventory_selector::resize_window to always go fullscreen, the performance regression goes away.

**Comment by mutability** [comment]
Disabling drawing the frame in inventory_selector::refresh_window() also fixes the problem.

I suspect this is because erasing/drawing the frame forces that whole region to be drawn immediately (destroying the old inventory list), and then the inventory list is drawn again on top of it. So every keypress results in basically every character in the the entire frame+contents being drawn twice, rather than just the small changes (cursor highlight) being drawn.

**Comment by codemime** [comment]
@mutability Thanks for the notification. I didn't see even the slightest performance losses on my system, so I didn't make any speed optimizations for the UI. I'll add a benchmark and tackle the issue in a separate PR.
BTW Opening tickets and referencing PRs is preferable in such cases: it simplifies further tracking and lets others verify the issue.

**Comment by Coolthulhu** [comment]
> I didn't see even the slightest performance losses on my system

Which system?
We might need to create some artificial load for testing on (some?) *nix platforms, otherwise their faster drawing makes it hard to see the regressions on other systems.

For example, drawing on Windows "fake console" is noticeably slower than drawing on Linux console or even Cygwin console.

**Comment by codemime** [comment]
> Which system?

Linux x64 too. Tiles, windowed borderless 1920x1080.

> We might need to create some artificial load for testing on (some?) *nix platforms

That's a good idea.

**Comment by mutability** [comment]
FWIW I did a little instrumentation, here's how it looks with a windowed 'i' when moving the cursor around:

```
refresh_window(): erase w_inv: 55us
refresh_window(): draw w_inv: 15648us
refresh_window(): draw_frame w_border: 79us
refresh_window(): wrefresh w_border: 64397us
refresh_window(): wrefresh w_inv: 48558us
```

'd' screen is a little worse, I assume because the window is wider:

```
refresh_window(): erase w_inv: 48us
refresh_window(): draw w_inv: 14955us
refresh_window(): draw_frame w_border: 80us
refresh_window(): wrefresh w_border: 87119us
refresh_window(): wrefresh w_inv: 72769us
```

If I disable the border then it is way faster:

```
refresh_window(): erase w_inv: 54us
refresh_window(): draw w_inv: 12964us
refresh_window(): wrefresh w_inv: 2375us
```

```
refresh_window(): erase w_inv: 112us
refresh_window(): draw w_inv: 18389us
refresh_window(): wrefresh w_inv: 2362us
```

(all times measured via CLOCK_MONOTONIC so they are elapsed time not CPU time)

**Comment by mutability** [comment]
SDL_RenderCopy() (in CachedTTFFont::OutputChar) is taking 10us per character which seems, uh, slow.

**Pull request merged**
