### PR TITLE
Remove eyebulge prereq from nictitating membrane mutation

### PR DESCRIPTION
**Pull request by Stadler76**
#### Summary
Content "Remove eyebulge prereq from nictitating membrane mutation"

#### Purpose of change
While nictitating membranes are more common on lizards than bulging eyes, lizard and dragon mutations couldn't have the former without the latter. Hence the change.

#### Describe the solution
I've unlinked `MEMBRANE` and `EYEBULGE` first (See ecb6db712520040c815cc1f4020c010a21f5fecb) and then removed `EYEBULGE` from lizard and dragon mutations in step 2 and 3 (See 6b5becb77b9f978c506cd4a8f7208a198553b2bc and bbbb3d912612131b4da7e9ca9ae99ebbb11425b6).
This removes 100 mutagen cost, 8 visibility and 4 ugliness from both lizard and dragon mutation.
However, I don't believe, that this makes lizards mutation significantly stronger, only a bit in terms of NPC interaction and considering, that the field `"vitamin_cost"` is now a thing the mutagen cost (issue?) is something, that can easily be fixed later.
So what remains is the loss of visibility and ugliness. So if you really, really want that small gap to be filled I *could* for example:
- Add lizard legs to the mix as a 0 point mutation (would be similar to clawed feet from Magiclysm, but without the random attack and the restriction to wear any footwear) with, let's say 4 visibilty and 2 ugliness.
- Add 4 visibility and 2 ugliness to the reptilian muzzle aka `MUZZLE_LONG`-mutation.

However: I doubt, there's any need for filling up such a small gap with mutations, that are fairly pointless, for the sake of filling up an 8 point visibility and a 4 point ugliness loss (and 100 mutagen cost).

PS: Before anyone asks: Yes, geckos exist and they mostly have bulgy (and lidless!) eyes and while they are cute the lizards in CDDA are anything, but geckos.
PPS: You could say the same about webbed feet, but removing that would remove an outright bad mutation and thus making lizard mutation stronger and somewhat remove the purpose of the mutation system rework. Hence, why I didn't touch that. And I'm not planning on doing so.

And: It adds more fuel to the reptiloid conspiracy, since they can be human with nictitating membranes to hide their reptilian eyes. 😅 

##### Todo
- [x] Wait, until either #59569 is merged or #59362 is closed as fixed.
- [x] Undo pushing pre-thresh mutations of the batrachian mutation to post-thresh.

#### Describe alternatives you've considered
- Just unlink the mutations, but don't touch lizard or dragon mutation.
- Replace the loss of uglyness, visibility and mutagen cost with another 0 point mutation.

#### Testing
I've tested lizard, dragon, batrachian and fish mutation by using Edit player/NPC → mutate category from the debug menu and both batrachian and fish still get the `EYEBULGE`-mutation, while dragon and lizard get the `MEMBRANE` without `EYEBULGE`.

##### References:
- [Crocodile nictitating membrane with slow motion - YouTube](https://www.youtube.com/watch?v=ttsWKaIQgso)
- [Nictitating membrane - Wikipedia](https://en.wikipedia.org/wiki/Nictitating_membrane)
  For example the bald eagle has a nictitating membrane, but the eyes are anything, but bulgy.

##### Trivia
- Bulging eyes was added first in 07a1cb6 aka more than 10 years ago.
- It was most likely added because of the fish mutation.

### CODE REVIEW

**Review by Maleclypse — CHANGES_REQUESTED** [review]
This isn't going to work as is.  Not because of your additions but because pushing either of those post thresh makes zero sense.  I'm looking into the test to understand what's happening.

**Comment by Maleclypse** [comment]
Could you add Batrachian category to 

```
  {
    "type": "mutation",
    "id": "MUT_TOUGH",
    "name": { "str": "Resilient" },
    "points": 2,
    "description": "You can survive injuries that would incapacitate humans: you get a 20% bonus to all hit points.  Stacks with Tough, etc.",
    "social_modifiers": { "intimidate": 2 },
    "types": [ "DURABILITY" ],
    "prereqs": [ "LARGE_OK", "HUGE_OK", "STR_UP_3", "STR_UP_4" ],
    "threshreq": [
      "THRESH_URSINE",
      "THRESH_CATTLE",
      "THRESH_CHIMERA",
      "THRESH_MEDICAL",
      "THRESH_LIZARD",
      "THRESH_BEAST",
      "THRESH_BATRACHIAN"
    ],
    "changes_to": [ "MUT_TOUGH2" ],
    "category": [ "URSINE", "CATTLE", "CHIMERA", "BEAST", "LIZARD" ],
    "hp_modifier_secondary": 0.2
  },

```
While you are here and I'm looking for other solutions.

**Comment by Stadler76** [comment]
> Could you add Batrachian category to
> 
> [snipp]
> 
> While you are here and I'm looking for other solutions.

- [x] done

**Comment by Maleclypse** [comment]
I've looked and I'm positive the tests are incorrect given the expansion of category to every mutation in a path to a desired trait.

**Comment by RelMayers** [comment]
Why the hell push into main part of game changes that are required for something that's a case inside mod? Why change and balance core around something inside mod? Could you make changes for magicalysm in magicalysm?

**Comment by Maleclypse** [comment]
> Why the hell push into main part of game changes that are required for something that's a case inside mod? Why change and balance core around something inside mod? Could you make changes for magicalysm in magicalysm?

1. Please be polite to people.  

2. The changes are also impacting Lizard which is in the main game, and if they make those changes to Lizard then without the changes to Magiclysm, Magiclysm would break and we wouldn't allow the changes to the main game because the PR would be breaking Magiclysm.

**Comment by RelMayers** [comment]
I very dislike changes charted to make mod play better which will impact gameplay of core without a even person making such changes thinking about consequences.
I very much dislike change to core to have better mod. I disagree with logic behind motivation.

**Comment by Maleclypse** [comment]
> I very dislike changes charted to make mod play better which will impact gameplay of core without a even person making such changes thinking about consequences. I very much dislike change to core to have better mod. I disagree with logic behind motivation.
> 
> Balancing something when you have something additional added makes it unbalanced when you it's not there.

OK, so then you are misreading the PR.  The Magiclysm edits as I stated above appear to be a side effect of the change to make Lizard more accurate.  So all the things you are saying appear not to be accurate.

**Comment by Stadler76** [comment]
By all means, how does removing `EYEBULGE` from dragons create any imbalance?
And even if so: I've given an example on how to fill up the gap, albeit small.

**Comment by esotericist** [comment]
> I very dislike changes charted to make mod play better which will impact gameplay of core without a even person making such changes thinking about consequences. I very much dislike change to core to have better mod. I disagree with logic behind motivation.
> 
> Balancing something when you have something additional added makes it unbalanced when you it's not there.

i have to ask you to dial back the aggressiveness, and most especially stop being accusatory in this way. you've been doing this too much, and it's not welcome behavior.

**Comment by Stadler76** [comment]
I'm *considering* to add lizard legs to the mix here. It will be a 0 point mutation aka the `TOE_CLAWS` from Magiclysm but without the random attack and footwear breaking. I'll add it in a way, that it doesn't affect other mutations in any way. Name will be `TOE_CLAWS` to avoid BC breaks for fans of Magiclysm dragons.

Main reason is, that I think, that lizards are a bit on the low end of breach power aka I think, they need an extra push to jump over the threshold hurdle.

**Comment by Stadler76** [comment]
Just did some find in files and if I counted correctly, black dragon mutation currently has 73 mutations including `"id": "THRESH_DRAGON_BLACK"`, `EYEBULGE` and 19 post-thresh, so there are 53 pre-thresh mutations, if I did the math correctly.
And no, it's not criticism of black dragon mutation nor does it imply any intentions to change that fact.
It's just me brainstorming and a TL;DR for: Do we really need to fix the 'loss' of `EYEBULGE` for black dragons? And I conclude: No, absolutely not.

**Comment by Stadler76** [comment]
> I'm _considering_ to add lizard legs to the mix here. It will be a 0 point mutation aka the `TOE_CLAWS` from Magiclysm but without the random attack and footwear breaking. I'll add it in a way, that it doesn't affect other mutations in any way. Name will be `TOE_CLAWS` to avoid BC breaks for fans of Magiclysm dragons.
> 
> Main reason is, that I think, that lizards are a bit on the low end of breach power aka I think, they need an extra push to jump over the threshold hurdle.

I did a brief test on my local testing branch a couple days ago an IIRC with all pre-tresh-mutations lizards have 73 breach power, which is more than enough. So no need to add lizard legs to the mix to give them more breach power. At least not yet.

**Review by Maleclypse — APPROVED** [review]

**Comment by Stadler76** [comment]
FYI: Just renamed it to "Remove eyebulge prereq from nictitating membrane mutation". Makes more sense now and it was my original intention to leave `"leads_to": "MEMBRANE",` intact for `EYEBULGE`.
Later on I might try to implement #59428 myself unless someone is already working on that.

**Pull request merged**
