### PR TITLE
Clandestine autodoc basement

### PR DESCRIPTION
**Pull request by Night-Pryanik**
- Added two variants of new basement type;
- Both types have the same chance to spawn as most other basements;
- The new basement is loosely based on `basement_game` type and represent basement of a sports-lover;
- One variant have a concealed enter to clandestine room with autodoc. The room has a small chance to spawn common bionics in it. Also this variant can spawn broken cyborg in the main room - this is a characteristic of autodoc variant.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
>  Autodocs must be pretty uncommon

You know, people on reddit say exactly the opposite - like, autodocs should be available in almost every house, should be portable and/or vehicle-mounted, should be craftable and so on.

Initially I set `weight` of the autodoc basement to 125, while most others have 250, and in my testing it was TOO rare - say, one autodoc basement in ten or so cities. Then I increased its weight to 250, and in my opinion it was still rare - I'd say hospitals may be more frequent.

**Comment by ymber** [comment]
Changing hospital spawns could be an option. I think the important thing about autodoc spawn locations is that they should be most common in hospitals and other proper facilities and finding an improvised basement operating theater should be pretty rare. Maybe 1 per city for moderately large cities. If bionics were relatively common before the cataclysm a variant doctors office with an autodoc (think LIMB clinic) would be a good urban location for it. I think wherever they are they should be fairly well secured by automated or now zombified security to make getting access to one a good specific midgame target.

Making autodocs easily portable or craftable or anything else you can carry with you would undermine the purpose of implementing them in the first place.

**Comment by Xhuis** [comment]
What's this look like in-game?

Also, I agree on making Autodocs more common if we'd like to restrict bionics so much (which I still kind of disagree with, but I can't exactly stop changes getting in.) It sounds like bionics and CBMs were commonplace; in the world; a bit more than electrical cars in our own. Available mostly to the wealthy and upper middle class, but findable more rarely among others, too.

I had a shower thought last night that you could certainly do worse than putting an Autodoc in a doctor's office storage room, the variant with the metal door. Perhaps you could also make a new variant focused on being a bionic clinic, with some common bionics on display and perhaps semi-rare ones in storage, and an Autodoc in a safe place. No need to worry about that, though.

**Comment by Night-Pryanik** [comment]
>What's this look like in-game?

Spoilers ahead!

default

**Comment by Night-Pryanik** [comment]
Oops, just noticed, it isn't the last version of the layout. There are little changes here and there.

The autodoc basement has 4 rooms: the large room, the bathroom, the locker room, and the autodoc room. The "normal" version of this basement doesn't have the autodoc room.

The large room has exercise machines of all sorts and a punching bag, also it has bench and a mirrors for exercises; it has a sofa with a TV set, and a mini-library section with bookcases and another sofa; it has a bar section with snacks and drinks; it has a pinball machine.

Bathroom and locker rooms are self-descriptive, I think. Autodoc room has an autodoc with a couch, a sink and three counters with several medical gear and a chance to spawn one of the common bionics.

Door to the locker room is hidden behind the fridges in the large room, and door to the autodoc room is hidden behind the lockers in the locker room.

**Comment by John-Candlebury** [comment]
Cool stuff.

I think it would be nice the room had guaranteed spawns for a single round of bionic installation. That way if you found it early/mid game you could be willing to risk using it.

**Comment by Night-Pryanik** [comment]
> the room had guaranteed spawns for a single round of bionic installation.

Done.

**Comment by DracoGriffin** [comment]
Glad you reviewed some of the suggestions on your subreddit post. I think there are a few more good ideas on there as well (the money one).

This looks like another great step towards making CBMs a bit more realistic and also feasible without feature-locking them towards the end-game.

Nice job!

My only suggestion would be to hide the autodoc room a bit more -- I think there are some mansion variants with hidden rooms behind bookcases that you have to move or you'd never realize (whether intentional or not, it was still interesting to discover and think of the "backstory" of why they were there -- survival, nefarious or just kinky good times).

**Comment by Night-Pryanik** [comment]
Honestly, I don't think that complete hiding of the door to the autodoc room behind the movable furniture would be fun or interesting. The whole concept of autodoc basement is meant to be an early/mid-game thing, and novice players likely wouldn't even have an idea that there is a autodoc to install CBMs. The players wouldn't have a motive to search the basement for a hidden room.

So I just moved lockers closer to the wall. The door isn't visible at a first glance, it is needed to come up closer to discover it.

default

**Comment by ZhilkinSerg** [comment]
There is Cyberjunkie class with description mentioning `a shady world of back-alley bionic clinics and self-installed secondhand CBMs`, so these basements are great addition!

**Comment by ZhilkinSerg** [comment]
I guess that should be fairly simple to implement: a list of terrain ids for basements to select from instead of single `basement` value.

**Comment by thethunderhawk** [comment]
Love it! The whole autodoc system is one of those relatively simple things that IMO really enhance the game. 
Maybe there could be a significantly more rare “CBM workshop” variant with some tools, some burnt out bionics, and crucially some skill books with bionic recipes.

**Comment by Night-Pryanik** [comment]
Some people say extra communal buildings (bionic clinics or your CBM workshop or whatever) will be redundant as now communal building are already more frequent than houses in average city.

**Comment by thethunderhawk** [comment]
Oh I meant as a basement. I totally agree with you there.

**Comment by ZhilkinSerg** [comment]
#24036

**Pull request merged**
