### PR TITLE
added bare bones basecamp

### LINKED ISSUE #59439: Bare bones base camp
### Is your feature request related to a problem? Please describe.

The current set of base camps allows you to set up camp only in a few select places, where it mandates constructions and order of construction which may be undesirable for some players. At the same time, base camps provide some functionality that isn't available through other means (sending off companions on tasks and companion crafting in particular), and so might be wanted without the burden of a "proper" camp in an "approved" location.

### Solution you would like.

Introduce a bare bones base camp that just declares the tile as a base camp, but doesn't provide any construction, not even of a bulletin board, but which can be set up almost anywhere.

Once a player builds a bulletin board anywhere within the tile, the "full" set of camp functionality should become available (because the interface through which it's reached has been constructed), with the set being:
- The companion tasks base camps currently provide gated behind construction (remote logging, foraging, etc.)
- The ability to construct expansions in all surrounding tiles (the expansions would still have to satisfy the restrictions they have).
- The ability to order companions to do crafting of a (hopefully well selected) set of items. The crafting would still rely on resources being available within the base camp, but provided the resources have had the Basecamp: Storage zone painted over them they should work when constructed or placed by the player.

### Describe alternatives you have considered.

Changing the companion interaction dialog to include crafting and "base camp" mission orders (although I don't know how you'd handle abstracted calories in that case), somehow handling return to wherever the order was given and item delivery to the same location.

### Additional context

Not placing a bulletin board but requiring the player to make it allows this base camp to be set up anywhere, without issues with walls potentially being in the way, such as caves roof tops, or even down in mines.

It should be noted that this "base camp" wouldn't automatically be available anywhere, as you'd still have to manually list every type of terrain for which it should be legal. Thus, I'd expect only some roofs and building interiors would be included in the list.

I think this could be made to work in e.g. Innawoods if that mod overrode the bulletin board construction/deconstruction with something reasonably easily available (I think nails are hard to come by there, and planks require some progress along the technology ladder).

Companion crafting list bloat is a significant UI issue (look at the bloated workshop lists). In the longer term the UI ought to be changed to be very similar to the player crafting one (categories etc., but omitting fluid recipes that can't be crafted by companions until a solution to that has been found).
In the mean time a comparably "short" list of things ought to be provided, with a recommendation for players to (unfortunately) mod their lists to include the things they want their companions to be able to craft.
It would be better to allow the players to add/remove items to the crafting list, but that would require the construction of a UI for that, something I think the uilist currently used isn't up to. A bare bones UI would just list every known recipe that doesn't produce fluids and provide a search function to allow players to find the items they want in that very long list.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change

Fix #59439
Provide a bare bones base camp option that gives you access to the base camp features without requiring you to follow a construction unlocking path that can be placed anywhere.

#### Describe the solution
- Modified the code to (re)use the terrain "ANY" to indicate a base camp is compatible with any terrain.
- Added a new base camp using the "ANY" terrain indicator the constructs absolutely nothing, not even a bulletin board.
- The player has to manually construct a bulletin board in any base camp tile in order to use the base camp.
- Once the bulletin board is constructed, the player gets access to the "standard" set of actions, such as logging, plus a list of companion crafting options.
- The companion crafting list is based on the lists existing for field base camps, but trimmed of the clutter caused by an excessive number of armors.
- A number of recipes have been added to the list, namely tallow (better fat->preservative ratio than lard), plus each of the welding consumables.
- Included a "custom" recipe list that's empty. It's intended to be populated by slightly mod capable players.

#### Describe alternatives you've considered
- Change the set of crafting recipes further.
- Moving the custom recipe list to a separate file to allow easier save migration. That would require ensuring multiple recipe groups won't cause trouble, though.
- Wait for someone capable to update the base camp crafting interface to make it capable of displaying a decent number of recipes in an accessible manner.
- Wait for someone to add the capability for the player to add known recipes to the base camp set.
 

#### Testing
- Created the base camp on a field, a forest, a swamp, and a roof tile (happened to be an electronics store).
- Verified that the companion could be send off to forage (from the field base).
- Verified that the companion could be sent off to cut trees (from the roof)
- Sent off the companion to survey an expansion from the roof top. Obviously failed to uncover any compatible tiles, and so had to escape from the menu, but was able to retrieve the companion via the emergency recall.
- Built a fireplace, set a fire in it, spawned some meat, and ordered the companion to cook it (from the field base).

#### Additional context
The base on a roof top:
Screenshot (252)

The bulletin board menu:
Screenshot (253)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I'm not able to see what failed on General build matrix / GCC 9, Curses, LTO (pull_request), as no line claims to be a failure. However, the last line returns a suspicious value, but I don't think base camps are tested as mutable overmaps, so the error is likely to be something already in the master code.
:
([slow] ~starting_items)=> Filters: [slow] ~starting_items
([slow] ~starting_items)=> 42.106 s: starve_test
([slow] ~starting_items)=> 16.206 s: starve_test_hunger3
([slow] ~starting_items)=> 24.029 s: all_nutrition_starve_test
([slow] ~starting_items)=> 6.824 s: shot_features
([slow] ~starting_items)=> 6.463 s: shot_features_with_choke
([slow] ~starting_items)=> 2.214 s: default_overmap_generation_always_succeeds
([slow] ~starting_items)=> 9.891 s: mutable_overmap_placement
([slow] ~starting_items)=> 2.246 s: mutable_overmap_placement
([slow] ~starting_items)=> 16.696 s: mutable_overmap_placement
test exited with code 137
Error: Process completed with exit code 1.

**Comment by x-qq** [comment]
Tutorial dialog with NPCs that explains the basics of faction camps probably needs to be updated to reflect this change.

https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/json/npcs/TALK_FACTION_CAMP.json#L77

**Comment by PatrikLundell** [comment]
Good call.

It will take me some time, as this is out of date with regards to a lot of added locations.
@LovamKicsiGazsii promised to update the fire lookout tower base that was affected by the tower update in a comment on that PR.

**Comment by LovamKicsiGazsii** [comment]
> @LovamKicsiGazsii promised to update the fire lookout tower base that was affected by the tower update in a comment on that PR.

Yep, and I fixed it on the same PR.

**Comment by PatrikLundell** [comment]
Explains why I couldn't remember seeing any PR dedicated to fixing that...

**Comment by PatrikLundell** [comment]
I've updated the faction camp info dialog and tried to describe the various camp options. However, I've got a limited knowledge of many of them, and so have tried to deduce properties based on reading the JSON recipes for them. It would be useful of people with a better understanding of them reviewed the versions they're familiar with.

**Comment by PatrikLundell** [comment]
General build matrix / GCC 9, Curses, LTO (pull_request) failure is not possible for me to decipher:

(~[slow] ~[.],starting_items)=> All tests passed (29202720 assertions in 931 test cases)
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> 17:40:37.004 INFO : Ended test at Thu Jul 21 17:40:37 2022
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> 17:40:37.005 INFO : The test took 589.443 seconds
(~[slow] ~[.],starting_items)=> 17:40:37.005 INFO : Randomness seeded to: 1658424619test exited with code 139
Error: Process completed with exit code 1.

**Comment by PatrikLundell** [comment]
I believe it would be possible to extend the TALK_FACTION_CAMP.json content further with more detailed descriptions of selected base camps (i.e. the ones I know the details of, which is the field base camps and the bare bones one), as well as the generic expansions. If so, it would take the form of an addition entry in the TALK_CAMP_TUTORIAL_[camp version] in the form of "Give me more in-depth details about...".

This would make the dialog somewhat lopsided as only a few would have this extra info.

Similarly, the expansion part could be changed to have one entry per expansion, rather than trying to cram everything into one giant list.

Any opinions?

**Comment by x-qq** [comment]
Is there anything that's bloking this PR from being merged? The above failure seems unrelated.

**Pull request merged**
