### PR TITLE
Single-space fix

### PR DESCRIPTION
**Pull request by illi-kun**
- removal of excessive spaces in some json-files.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Rivet adds commits to add these spaces occasionally. I'm not sure what the space is for, but you may want to get with her.

**Comment by Rivet-the-Zombie** [comment]
We use double spaces after periods in all player-visible text in order to improve readability.

**Comment by kevingranade** [comment]
Specifically, since we're using a fixed-width font, the throwback style of adding two spaces after a period is beneficial in order to have a distinct break at the end of a sentence.

**Comment by DavidKeaton** [comment]
@kevingranade that's actually pretty smart. My compulsivity would have a field day though. lol.

**Pull request merged**
