### PR TITLE
Add winged zombie upgrade path

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Content "Adds flying zombie upgrades"

#### Purpose of change

Enemy diversity, reward different combat styles, make zombies feel unpredictable and dangerous

#### Describe the solution

Copy/paste a vanilla zombie and add FLIES flag and reduce HP and weight 20%, upgrades that into a copied zombie brute with a FLIES flag and same HP and weight malus. Adds brute to the brute upgrade group and winged zombie to zombie roof group on a timer,

BONUS: By request adds copy-from zombie crawler with less HP and weight and no claw ability that upgrades into the flyer. Has extra armor, sludge flag, and faster bite cooloff time to not be entirely terrible. Vanilla crawlers upgrade into pulsing crawlers.

#### Describe alternatives you've considered

Lots more flying zombie variants. Shadies, children, spitters. Probably not hulks or skeletons though. More intermediates, more advanced variants.

#### Testing

Both spawn with no errors and behave as expected
image

Pulsing crawler same:
image

#### Additional Context

Fly my pretties!

### CODE REVIEW

**Comment by aoae23** [comment]
Would brutes still be able to smash players with winged arms?

**Comment by LyleSY** [comment]
I was thinking about Manbat and gargoyles there. I think they could as part of a swoop or from a standing position but I doubt the code is clever enough to distinguish that

**Comment by aoae23** [comment]
In my opinion, the wings should sprout as large, fleshy protrusions from their shoulder blades instead. That would be a less silly mental image than zombies flapping their wing arms to fly.

**Comment by LyleSY** [comment]
That was my first thought too, but that feels too fantasy to me, I'd like to be more horrific with this

**Comment by anothersimulacrum** [comment]
I feel like flying zombies should be a unique line, not a variant of other zombies.

**Comment by NoahGoldFox** [comment]
But roofs are supposed to be a safe place. with zombies like this how are you supposed to escape to roofs to be safe?

**Comment by LyleSY** [comment]
Noah, I had the same thought. These don’t spawn at all on day one, and only on zombie roofs after the timer goes off. Bird flying mutations have been proposed before, it would just take a lot of work to do it properly and so far no one with the skills has signed up for that.

Simulacrum, are you talking about a second PR or this PR? If this PR, can you say more? I’m trying to make this as minimal as possible to start but I agree there’s lots of room to grow.

**Comment by Zireael07** [comment]
@LyleSY: Flesh protruding from shoulder blades AND back, with the skin of the back 'lengthening into a gruesome fleshy membrane'.... would probably feel as much NOT fantasy as your current description does, without the 'flapping arms' silly mental image.

**Comment by Amoebka** [comment]
Wings not being arms is fantasy from anatomical point of view. They don't magically move on their own, there must be bones, muscles and tendons supporting them.
Bird wings ARE indeed their "arms".

**Comment by harison86** [comment]
@LyleSY Let's make sure Kevin's concerns regarding flight in #25582 aren't forgotten, we wouldn't want to be unrealistic or inconsistent eh? That's what matters most after all, realism.

> Yes, a bird that size can fly, but birds are compromising on much more than just size and weight. They also sacrifice running ability and extremities suited for msnipulation. I was assuming a character would maintain their full faculties with respect to walking, running, and manipulation.
> 
> If you _really_ want a bird mutant to fly, it needs to go full bird. That means ditching the arms, so no crafting or most tool use, ditching the heavily muscled legs, so no running or long distance walking, along with the other things I outlined.
> 
> At that point, yes, real flight would be feasible, at the cost of pretty much every other player ability.


> I'm not haggling, what I outlined is the most I'll accept.
> 
> To recap:
> If the player keeps human-typical abilities like wearing clothes, crafting, running, then flight _requires_:
> 
> * the full spectrum of weight and size reducing mutations
> * Flight is an extreme hit on stamina, at least 4x the rate of running
> * Load on hunger and thirst is extreme as well
> * Flight is limited to an extended jump type action
> 
> If the player additionally sacrifices:
> 
> * Ability to wear most clothes (the only exception I can think off hand is something like a harness, but there are probably a few others)
> * Ability to craft.
>   Then that might justify continuous flight.

So if the winged zombie's "flight" is limited to an extended leap

- They need to be tiny and lightweight, with appropriately low HP and bashing damage
- The leap has a hefty cooldown due to the resource costs

If the winged zombies are expected to achieve sustained flight then they also

- Have terrible ground speed
- Their wings are their arms, lacking the ability to bash obstacles or grab the player, probably evolving claws/talons on their feet to compensate
- Are naked, making them worthless in terms of loot

So have fun with that, unless that fun is unrealistic in which case don't. These constraints are apparently non-negotiable.

**Comment by DrPariah** [comment]
Oooh, I actually like the idea of flying child zombies. Large-ish flock of low HP flying mobs, not too dangerous for an equipped survivor but still a threat. Add Shady variants to make night raiding !FUN!. Now that I think about it, a Nightstalker variant of the Winged Brute wouldn't be out of line either, and super simple to make. Winged variants of other specials outside of the Hunter/Biter models would be a bit much (Winged Spitter/Corrosive, no thanks!), but some variety wouldn't hurt.
Overmap special (are those still a thing?) for a "Nest", full of multiple flying zombie types, perhaps? Easiest way would be make a variant of the Regional Dump but swap out most of the trash with more 'natural' debris.

**Comment by anothersimulacrum** [comment]
@LyleSY As @harison86 hints at, flight is quite a specialized trait - it's shouldn't be 'normal zombies with wings', it should be an evolution chain that turns normal zombies into some sort of flying creature.

For example:
Zombies with wing stubs - worse than normal zombies, but getting smaller and starting the generate wings
Zombies with half wings - getting small with proper wings with some use, e.g. gliding. They're faster and perhaps starting to develop talon
Zombies with full wings - Smaller fast zombies with proper flight, proper talons. Perhaps they do the hit-and-run tactic that wolves do - dash in, claw you, fly away.

This isn't an exact blueprint for what to do, it's just an example.

**Comment by NoahGoldFox** [comment]
> Simulacrum, are you talking about a second PR or this PR? If this PR, can you say more? I’m trying to make this as minimal as possible to start but I agree there’s lots of room to grow.

I was talking about some separate PR in the future, not including it in this one.

**Comment by dissociativity** [comment]
I see these as zombies that are fast, make you bleed a bit more with every hit but don't do a whole lot of damage and are quite fragile

**Comment by Mister-Cultist** [comment]
zombie fliers should be lighter and more fragile than regular zombies, but maybe have nasty talons or powerful bites. Just copying regular stats into flyers seems like a bit of a missed opertunity but I'm keen to see how it goes. Experimental is experimental after all.

**Comment by moocowswag** [comment]
Probably late but has anyone considered that the cataclysm could have effected the atmosphere/polluted it with foreign gasses? Possibly reducing the requirements for flight.

**Comment by harison86** [comment]
If the atmosphere had been polluted by enough dense foreign gases to enable brutes to fly, every air-breathing creature on Earth would be dead, whether due to suffocation, poisoning, or crushed by atmospheric pressure.

**Comment by moocowswag** [comment]
I was refering to it being easy enough for regular zombies to fly with alittle less weight and keeping their arms (although possibly reduced to weak stabbing appendages)

**Pull request merged**
