### PR TITLE
Restore the damage values of the machete, combat machete, and qt combat machete after some unintended nerfs

### LINKED ISSUE #76152: `relative` json inheritance might be wonky for `survivor_machete_qt`
### Describe the bug

Unsure if this is a bug or intended behavior, but I noticed a discrepancy between the damage of the tempered steel combat machete in-game, versus its listing on the item browser. 26 cut in-game, versus 28 cut 1 bash in the browser.

This is being caused by the survivor_machete_qt setting its `relative` damage on `machete` (21 cut), not the `survivor_machete` (23 cut).

This might be unintended, since survivor_machete_qt `copy-from`'s the survivor_machete, which itself `copy-from`'s and `relative`'s the regular machete for its own damage.

Entries in JSON:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-09-02-1123/data/json/items/melee/swords_and_blades.json#L819-L883

### Attach save file

N/A

### Steps to reproduce

Look at item browser, look at code for survivor_machete_qt, look at tempered steel combat machete in game.

### Expected behavior

I would expect that tempering a machete would not cause it to lose bash damage compared to the non-tempered one.

I am not which values are 'correct' but the expected DPS of the qt combat machete is lower than inferior-steel alternatives in the expected dps file, as well as having worse expected DPS than bronze weapons like the khopesh and xiphos. I would expect a tempered steel short sword to perform better than a bronze short sword.

If this lower DPS is considered a bug, this issue might be the cause of it.

Expected DPS:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-09-02-1123/data/mods/TEST_DATA/expected_dps_data/shortswords_dps.json

### Screenshots

image

image

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 24.0.2; Codename: Wynsdey; 
- Game Version: cdda-experimental-2024-08-28-1527 0897544 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Regilith**
#### Summary
Balance "Restore the damage values of the machete, combat machete, and qt combat machete after some unintended nerfs"

#### Purpose of change

Fixes #76152

The machete, combat machete, and qt combat machete have all had their damages significantly reduced by some PRs, and these changes appear to have been unintended. The current DPS of the qt variant in particular is worse than the two bronze equivalent shortswords - the xiphos and the khopesh - despite them all being similar weights and lengths, and of the latter two being drastically worse material quality (bronze versus tempered steel), and significantly worse than all the other qt options in shortswords_dps.json

data/mods/TEST_DATA/expected_dps_data/shortswords_dps.json

`"machete": 16.9`
`"survivor_machete": 17.41`
`"survivor_machete_qt": 20.1`
`"sword_xiphos": 22.0`
`"khopesh": 24.26`
`"qt_cutlass": 26.3`
`"qt_scimitar": 27.0`
`"qt_wakizashi": 27.68`
`"qt_cavalry_sabre": 28.7`
`"qt_rapier": 30.5`

The two reasons I found for this were in these PRs:

#66956 changed the absolute damage values of the combat machetes to use `relative` instead, but instead of preserving the 28 cut damage of the qt variant, it unintendedly reduced it to 26 cut, and one less bash due to the flag not taking into the account the `relative` damage of the regular combat machete, which the qt `copy-from`'s. You can see this current cut damage in game (see #76152 for images, the item browser is wrong).

#68146 removed token bash damage from knives, but the machete, combat machete, and qt combat machete were also affected by this change despite them being short swords, not knives. This was probably due to the machete having "knife" in its description. Either this was intended, and the other short swords should have their bash damage removed since they have similar lengths and weights to the machetes (the xiphos is 10cm shorter, for example), or (more likely) this was accidental, as it left machetes as the _only_ `SHORT_SWORDS` without bash damage.

#### Describe the solution

Restore the damage values to what they were before the PRs, to be more in-line with the other short swords in the DPS list. The qt variant now has the same damage as a xiphos, but is faster to swing.

#### Testing

Just numbers changes.

image

#### Additional Context

After this PR, the new expected DPS is this (see 1cd5bc4 for where they place compared to other short swords):

`"machete": 19.34,`
`"survivor_machete": 20.64,`
`"survivor_machete_qt": 25.8,`

For some reason, `"replace_materials": { "steel": "qt_steel", "wood": "kevlar" },` isn't working correctly either for the qt machete, it shows as having wood instead of kevlar in-game. It seems some of these json inheritance flags don't correctly work when you chain `copy-from`'s together.

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
I'd say this is the thing to do: "the other short swords should have their bash damage removed".
Overall regardless of how it happened, I think it's totally fine for machetes to fall short of dedicated swords in combat capability. They're not made for fighting, they're made for chopping grass and shrubs and being cheap.

**Comment by Regilith** [comment]
> I think it's totally fine for machetes to fall short of dedicated swords in combat capability. They're not made for fighting, they're made for chopping grass and shrubs and being cheap.

This is true for generic machetes, and generic machetes should probably have reduced damage / less durability, but at least for our machete in-game it is described as being based off of the OKC 1-18, which is described as a "Military Machete."

The combat machete / qt combat machete are specifically described as being:

`"customized and rebalanced to improve its performance as a weapon"`
`"customized, rebalanced and tempered to dramatically improve its performance as a weapon."`

So these aren't generic machetes anymore, they're closer to 'zombie choppers' that some irl cutlery companies produce. If we want to actually have an end-game weapon in the `SHORT_SWORDS` category, we might want to reflavor the combat machetes to be totally different things, rather than modified gardening machetes.

Even with the adjusted damages, the qt combat machete still falls short of all the other qt swords in that DPS list, and the combat machete is around the same damage as a bayonet or sword cane, which seems reasonable.

My suggestions:

1. Change the current `machete` to be based on more of a more generic, grass-cutting, store-bought variety. Reduce its damage, remove the STURDY flag, change its physical numbers, update the description.

2. Change the acquisition of the combat machete to be either hand-forged from scratch, or as a rare drop in some locations (feral preppers and prepper houses come to mind), since the current recipe of super glue and grinding doesn't really make sense to make a machete more combat-capable. Base this machete off of the okc 1-18 or some equivalent 'zombie chopper'. Update the description to reflect how much different it is from a normal machete.

3. Keep the tempered steel combat machete as a high-fab crafting exclusive. Replace the description to distance it from the garden variety of machete.

4. Reduce overall bash since these are lighter than most swords, possibly compensate with higher cut.

**Comment by Regilith** [comment]
I'll rethink this and possibly re-approach it.

**Comment by kevingranade** [comment]
> based off of the OKC 1-18, which is described as a "Military Machete."

Just because it's military doesn't mean it's a good weapon???

> "customized and rebalanced to improve its performance as a weapon"

You're only getting so far by tempering bad steel and adjusting the profile of a machete, it's still a machete. It's a thin profiled broad blade made of a metal alloy that is optimized for not weapon usage.

> they're closer to 'zombie choppers' that some irl cutlery companies produce.

Which are themselves cosplaying as weapons.

> If we want to actually have an end-game weapon in the SHORT_SWORDS category

We don't,  a short sword is fundamentally not an end game weapon,  and machetes sit below the real short swords.

> to be either hand-forged from scratch, or as a rare drop in some locations

You're missing the point here,  if you extensively resesign a machete to be a capable short sword, it's no longer a machete. If it's still a machete, it's not a sword. If it's a sword... it's a sword, which we already have.

Please just drop it, machetes are a dead end. If you want a sword just use a sword.

**Pull request closed without merging**
