### PR TITLE
jmath: don't allow shadowing of built-in functions

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
None

#### Purpose of change
jmath functions can silently overwrite built-in functions and confound cargo culting, as seen in [this job run](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8121275392/job/22199474805?pr=72092#step:17:794) where a jmath function was cargo culted from Xedra without the corresponding shadowing function, `spell_exp()`.

#### Describe the solution
Don't allow shadowing
Replace shadowing function with a built-in one since its formula is hardcoded.
Also add the missing support for mod tracking to prevent silently overwriting jmath IDs within a mod.

#### Describe alternatives you've considered
N/A

#### Testing
<details>
<summary>Decent error message</summary>

Screenshot from 2024-03-02 13-02-02

</details>

`$ ./cata_test '[force_load_game]' --user-dir=all_modded --mods="magiclysm"` doesn't complain about bad scope for `spell_exp()` anymore.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Ok but I think Xedra and Magiclysm have different exp values so naming them both the same thing will make one overwrite the other? Or I’m confused?

**Comment by Maleclypse** [comment]
I’m thinking the difference is in a later part of the eoc chain now that I think on it further. But I’ll try and check they have different eoc names at that point too. Thanks!

**Comment by andrei8l** [comment]
> Ok but I think Xedra and Magiclysm have different exp values so naming them both the same thing will make one overwrite the other?

The formula for XP is hardcoded so it's the same for both mods - see [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/669a9fc29eda38d6fbd5bcb3ab44a00f83e73aec/src/magic.cpp#L1761-L1768) and [this](https://github.com/CleverRaven/Cataclysm-DDA/blame/669a9fc29eda38d6fbd5bcb3ab44a00f83e73aec/doc/MAGIC.md#L115-L117).

I've hardcoded the function. It can be moved back to JSON if the rest of the XP logic gets unhardcoded as well.

**Comment by Maleclypse** [comment]
I was meaning `EOC_XE_CASTED_A_SPELL` vs `EOC_MC_CASTED_A_SPELL`

I wasn't sure if MC stood for main character or Magiclysm and it was the same eoc in both Magiclysm and XE.  Sorry for the confusion :)

**Comment by Maleclypse** [comment]
Hey Andrei I kicked a test tonight and this popped up 
```
ERROR : src/math_parser.cpp:819 [void math_exp::math_exp_impl::error(std::string_view, std::string_view)] Expression parsing failed: Scope g is not valid for dialogue function spell_exp() (valid scopes: un)
```

Is that error from before this PR merged or after?

**Comment by andrei8l** [comment]
That's the issue I fixed in this PR. It's the same message and line number as the error I linked [in the OP](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8121275392/job/22199474805?pr=72092#step:17:794)

**Pull request merged**
