### PR TITLE
Remove salvaging from bone

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Our salvaging is really stupid to begin with, and while it can be handwaved for plastic or fabrics, there's no way you're cutting apart a log with a sharp rock. The same goes for skulls and all similar garbage. These are not materials you're just casually cutting apart like that.

#### Describe the solution
- delete the salvaging from bone
- remove ``NO_SALVAGE`` flag from all bone items that didn't have other materials that'd allow for salvaging
- remove ``NO_SALVAGE`` flag from migo bones. They already weren't salvagable on behalf of using a unique material so this is just misc cleanup

#### Testing
Can no longer cut up a chair or a log with a knife, even though neither has ``NO_SALVAGE``

#### Additional context
Thanks to @harakka for helping catch the items that were using ``NO_SALVAGE`` because if I had to do this manually I'd go insane

Part of #74364 and #73410

### CODE REVIEW

**Comment by RenechCDDA** [comment]
>there's no way you're cutting apart a log with a sharp rock. The same goes for skulls and all similar garbage. These are not materials you're just casually cutting apart like that.

So, give them different salvaging requirements?

**Comment by Karol1223** [comment]
> So, give them different salvaging requirements?

Are you adding support for defining what requirements material needs to be salvaged? Because at the moment that's not supported to my knowledge and it all defaults to cutting 1

**Comment by RenechCDDA** [comment]
No, I'm saying that if you want to improve the system that's the way to do it. You can turn a log into splintered wood. Removing it doesn't make much sense.

**Review by RenechCDDA — CHANGES_REQUESTED** [review]
It should be entirely possible to turn wooden items into splintered wood (and bone into... something, maybe not bone skewers). 

Removing this still isn't appropriate. If you want to continue on this, I recommend changing how salvaging works, not simply removing it.

**Comment by Nebnis** [comment]
Ye i agree with Renech here, it possible to just smash a tree with a sharp rock and eventually get splinters or bone shards from skull, it would just take a LONG TIME but it is entirely possible. The real fix would make it longer and maybe consume the shitty tool you are using after a set amount of time.

**Comment by Karol1223** [comment]
> It should be entirely possible to turn wooden items into splintered wood

It should be possible to salvage any material, in fact, not just wood or bone. Unfortunately it is not doable within the way the system currently works. The salvaging systems fits the bill for emergency salvaging fabrics, or some plastic junk, but it falls apart with materials tougher than this. I fully agree that wooden items should be able to be turned into splintered wood. I also fully disagree that this should be done via the salvaging system, as, like I said multiple times before - it is a massive mess that barely functions. Feel free to read #73410 if you want to see my entire line of thought about this.

**Comment by RenechCDDA** [comment]
It's about moving closer to a reasonable impression of reality. A wooden furniture can be broken apart with your bare hands. What do you get? Splintered wood (and maybe some other bits). Can we do that right now? Yes ([**actually no**](https://github.com/CleverRaven/Cataclysm-DDA/blob/1fb61c1d41cffd682a46fa6970f98c171762061a/data/json/items/furniture/seating.json#L9), but don't make me go change that)! Does making a wooden furniture unable to be broken up take us closer or further from reality?

Let me give you another system which doesn't work perfectly: Crafting. You put on a stew... and you have to stand there and watch it for 40 minutes while it boils.

Is that perfect? No. Is it very good? Ehh... no.

Should we remove all the cooking recipes so that food cannot be crafted? Absolutely not.

Do we want this system to be improved? [YES!](https://github.com/CleverRaven/Cataclysm-DDA/issues/62635).

A seeming lack of improvement doesn't mean it should be removed. The test you are modifying is coverage *specifically to make sure the system works*. Ask yourself why the test was added if salvaging is unwanted.

To iteratively improve on salvaging I would recommend tying a (optional, defaulting to current cutting 1) quality to each individual material, and then requiring that quality when selecting an item to be salvaged.

**Comment by Karol1223** [comment]
> specifically to make sure the system works

So I just tested in and it doesn't. Or rather that test only tests one specific aspect.

It currently takes a **SECOND** to take apart a 30kg wooden log with a bone shiv, which is just a sharpened piece of bone.

Interestingly the game claims it will take 50 seconds, which would also be bullshit, but it still only takes 1 second.

**Comment by RenechCDDA** [comment]
That is a great candidate for another follow-on PR, then.

**Comment by Karol1223** [comment]
I do not believe that our wood items should be salvagable, at least unless we can differentiate which quality is being used. A log should not be salvagable with anything less than wood sawing or axe qualities. But then you have something like a stick, which absolutely should be cuttable with a knife and some patience.

As for taking apart wooden furniture with bare hands, this can be done by smashing it in furniture form. I believe most wooden shit has low enough str requirements to have this be doable with bare hands, except maybe real big stuff like bed frames or wardrobes (I think I specifically made chairs have it low enough to be destroyable with bare hands just hard?)

To me this sounds like very much wishful thinking that someone is going to improve that, when nobody's showing any interest in doing so. Yet again, I very firmly disagree that a system which (in these circumstances) provides ***exclusively*** weird results, should not be kept in the current state. Fixing the time calculation would make it applicable in some very niche circumstances with wood, but never really with bone. Unless, again, someone restructures the thing from scratch. Problems outlined in #73410

**Comment by Karol1223** [comment]
> Are you personally not interested in improving it?

Not at all. Like I said in the comments of the issue - if it was up to me, I'd remove the system entirely. The problem with that is that this would, unfortunately, undoubtedly be a drastic change and a step backwards in most cases, at least regarding fabrics.

Improving it would require tremendous amounts of C++ which I don't have the knowledge for. But I'll be honest, even if I did I would likely not try.

**Comment by Maleclypse** [comment]
I understand your frustration with smashing something into splinters in a second with a rock.  Unfortunately I believe that this solution is going the wrong direction towards a fix.   I did look into the c++ on making the time quality dependent and it was beyond my ability.  If you had an idea of what a solution could look like to the end user and were willing to make an issue for it I would mark that as a confirmed issue and hopefully it would attract someone with c++ skills to complete it.

**Comment by Maleclypse** [comment]
Catching up on the discussion on discord of this it might be reasonable to reopen it?  I think we have two people looking into the mess that is salvage c++ and reopening while that is examined might make sense.

**Comment by kevingranade** [comment]
The status quo:
No matter what other uncraft recipes exist, you can take any item made of bone or wood and cut/smash it down to splinters of that material.  This is an ancient system that predates uncraft recipes and honestly I kind of expected/hoped for it to go away once uncrafting became an option, but it's sticking around so far.

The problem being called out is the "salvaging" action is extremely inflexible, it assumes you can take apart whatever with a knife (specifically a tool with the "salvage" actor attached, but that's knives), and it basically treats everything as being somewhere between cloth and wood with respect to how hard it is to take apart. It also ignores scale, it's a lot easier to shred a bunch of sticks than a whole log.
In addition, salvaging being triggered as "use tool on item" is problematic, what if you need multiple tools? What about salvaging actions where you don't need tools? i.e. smashing a chair against the ground.

This pr removes "salvages_into" from both bone and wood, in both case you get splinters as a result.  In retrospect, at least the bone part of this should have gone in, I don't think it's at all reasonable to take apart bones with a knife (or scissors), so that was a mistake from the outset.  Whittling down sticks is fine-ish, but yea logs should be exempted, possibly with application of more NO_SALVAGE flags.  If someone wants to subsequently extend salvaging to use smashing instead based on the tools available, there's your bone salvaging and it can easily be added back.

The other "more complete" fix is extending materials with "this is how you salvage me" and maybe "this is how hard I am to salvage", and extending the salvage iuse with "this tool can provide these salvaging qualities"  OR just ditching salvaging and replacing it with uncraft recipes, possibly that you can apply to different items instead of having to repeat them for every item you want to be able to use them on.

**Comment by zachary-kaelan** [comment]
Uncrafting is nice but it assumes a full and proper disassembly which can take a *really* long time. Sometimes you want a quick and dirty to get a few materials without care for efficiency. "Salvaging" hard items could potentially be moved into an extension of smashing. You pile items you want to destroy then every time you smash the tile it goes through the hard items, randomly damaging some of them and providing materials. Swinging a mace to hit a single bone on the ground being more difficult and less efficient than swinging a mace to hit a bunch of bones grouped together.

**Pull request merged**
