### PR TITLE
Reduce antifungal drug spawns

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
Balance "Reduce spawn chance of antifungal drugs in houses"

#### Purpose of change
A bathroom's chance of spawning antifungal drugs is among the highest in the game, considering how common they are the overall chance of finding antifungals in a set of houses is _very_ high.

#### Describe alternatives you've considered
Reducing it more?

#### Additional context
future fungal friends
Screenshot_2

### CODE REVIEW

**Comment by actual-nh** [comment]
In reality, antifungal _**topical**_ drugs (including into body cavities such as the vagina) are likely almost as common as nonprescription antibiotics. Oral/IV ones are much less so (partially because of the high side effect risk - fungi are the closest other group of organisms to animals, so what hurts them has a high chance of hurting us).

**Comment by NickGrease** [comment]
Can someone correct my math; is this going from roughly 2 in 100 spawns to 2 in 1000? Seems way overboard if correct.

**Comment by actual-nh** [comment]
> Can someone correct my math; is this going from roughly 2 in 100 spawns to 2 in 1000? Seems way overboard if correct.

What's the spawn rate for non-weak/narrow-spectrum antibiotics? Should be roughly the same, or actually less. (Perhaps increase in pharmacies, etc, to partially compensate?)

**Comment by NickGrease** [comment]
> What's the spawn rate for non-weak/narrow-spectrum antibiotics? Should be roughly the same, or actually less. (Perhaps increase in pharmacies, etc, to partially compensate?)

I *looks* like 1% chance for antibiotics - but I have no way of knowing if I'm reading the json right.
The way I'm reading it is `10% chance to spawn 10% of the time`

**Comment by Salty-Panda** [comment]
It looks like weighted distribution, which would mean that your change does nothing, because 60/60 == 5/5

**Comment by Salty-Panda** [comment]
There is 5% chance to spawn one of anti... items.
5/25 ( down form 60/80 ) that the spawned item will be antifungal
20/25 ( up from 20/80 ) for antiparasitic

**Comment by actual-nh** [comment]
> There is 5% chance to spawn one of anti... items.
> 5/25 ( down form 60/80 ) that the spawned item will be antifungal
> 20/25 ( up from 20/80 ) for antiparasitic
> 
> Overall there is 4% chance to spawn antiparasitic and 1% for antifungal now.

Hrm. I suggest putting back the 60/80 and 20/80 for antifungal/antiparasitic (neither should be particularly common), but decreasing the 5% chance for one or the other - 2%, or preferably 1% but increase spawn rates (for _both_) in pharmacies, etc enough to compensate. (Even that high for antifungal in bathrooms is assuming that it is not actually always in pill form, but instead that sometimes the character just needs something topical.)

**Comment by kevingranade** [comment]
> (Even that high for antifungal in bathrooms is assuming that it is not actually always in pill form, but instead that sometimes the character just needs something topical.)

What like Lotramin or other Athlete's Foot treatment? No that's absolutely not close enough, that's a separate item.

**Pull request merged**
