### PR TITLE
Mini Reactor Appliance

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "Mini Reactor Appliance"

#### Purpose of change
More appliances for the appliance gods.

#### Describe the solution
usual stuff, reactors seem to not work though, leaving this as draft until resolved (presumably here)

probably gonna add the microlab generators too as another reactor option.

#### Describe alternatives you've considered
I need some form of passive energy generation available for a new mod I'm working on, so this gotta happen at some point.

#### Testing
Seems to not work as is

### CODE REVIEW

**Comment by shacknetisp** [comment]
I tested this PR with my reactor charge fix in #58362 and it works.

**Comment by bombasticSlacks** [comment]
Awesome thanks for tackling that!

**Comment by anothersimulacrum** [comment]
FYI: the minireactor is functionally obsolete in vanilla.

**Comment by bombasticSlacks** [comment]
> FYI: the minireactor is functionally obsolete in vanilla.

I was working on this for mod content, I don't want to go through obsoleting it but if it is at some point obsoleted I can find a home for it 😆

**Pull request closed without merging**
