### PR TITLE
Add shillelagh, a traditional irish stick-fighting weapon.

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary

 ```SUMMARY: Content "Add shillelagh, a traditional irish stick-fighting weapon.```

#### Purpose of change

A new pre-smithing bashing weapon, for the sake of variety. Irish is the largest European ancestry in New England ([source](https://en.wikipedia.org/wiki/Demographics_of_New_England)) so it makes sense to have this traditional Irish stick-fighting weapon represented.

Also added a way to "upgrade" the weapon by allowing you to add weights. "weights" is a materials category and could be used to add weight to other weapons for more impact damage or as counter-weights for better handling.

#### Describe the solution

Crafting shillelagh:

> Shillelaghs were traditionally made from blackthorn (sloe) wood (Prunus spinosa) or oak. Wood from the root was prized as it was less prone to cracking during use. The bark was peeled and the wood was smeared with butter or lard, and then placed up a chimney to cure, giving the shillelagh its typical black shiny appearance. [1]

SKILLS: Fabrication(3) for crafting the shillelaghs and survival (2) for the process of curing it.

TOOL: Cutting 1, wood sawing 1 for extracting the root, A charcoal smoker and 6 hours crafting time should simulate the chimney curing process. 

INGREDIENTS: 1 log for the root, 400 grams of butter or lard. 

---

Crafting loaded stick:

> Some shillelaghs were hollowed at the knob end and filled with molten lead to increase the weight beyond the typical two pounds; this sort of shillelagh is known as a 'loaded stick'. [1]

SKILLS: Fabrication(5) for drilling a hole, smelting the metal and poring it in.

TOOL: drill, forge and crucible.

INGREDIENTS: 300g of "weights".

"weighting" is new material category consisting of malleable and ductile heavy metals (lead, gold, silver,platinum). One unit is 15 grams of weights.

---

Balance.

The shillelagh has a weight of 910g [1] (2 pounds) and a length of 3-4 foot [2]. The volume 1.5L is the same as an umbrella as it has a similar shape.

It has a damage of 24. A bit more damage than a baseball bat due to being a bit longer, having more of its mass concentrated at the point of impact, having a smaller area of contact (also why the "to hit" value is 1 less) and being a proper martial arts weapon designed to do damage.

Balance wise this makes it about as good as a barbed wire bat or an ironshod quarterstaff. 

The loaded stick has a weight of 1135g, matching the weight added in the recipe.

The damage of 31 is half-way between the shillelagh and the mace (37). 

---

Picture: shillelagh

A comparison of similar weapons:

shillelagh

Crafting:

image

image

references
* [1] http://oldeuropeanculture.blogspot.com/2015/05/knobstick.html
* [2] https://web.archive.org/web/20120302040109/http://www.freifechter.com/files/stick_edited.pdf
* https://shillelaghstudies.com/2018/11/01/what-is-a-shillelagh/
* https://en.wikipedia.org/wiki/Shillelagh_(club)

#### Describe alternatives you've considered

Making a "raw shillelagh" that can be left to cure on its own in a smoker.

### CODE REVIEW

**Comment by ampersand55** [comment]
TODO: add to item categories.

This is a WIP. Critique and suggestions welcome.

**Comment by kevingranade** [comment]
The damage output seems a bit high to me.
For a better comparison we need to look at damage vs attack speed as the
same things that make it do more damage also make it slower to swing. I.e.
if the DPS is similar to a bat that's ok.
The loaded version is definitely too high, even if the speed is relatively
low.

**Comment by ampersand55** [comment]
> 
> The damage output seems a bit high to me. For a better comparison we need to look at damage vs attack speed as the same things that make it do more damage also make it slower to swing. I.e. if the DPS is similar to a bat that's ok. The loaded version is definitely too high, even if the speed is relatively low.

I kind of felt that the damage was a bit high too, but I arrived at it by comparing with the other weapons and following the [GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md)

> Each point of to-hit is "worth" roughly a 10% increase/decrease in damage per turn or 2.5 points of damage per turn (whichever is higher).

> (...)

> 16-25 - Dangerous tools or crude dedicated weapons. Golf clubs, two-by-swords, wooden spears, knife spears, hatchets, switchblades, tonfas, quarterstaves.
> 
> 26-35 - Good dedicated weapons or the most dangerous of tools. Wood and fire axes, steel spears, electric carvers, kukris, bokken, machetes, barbed wire bats.

weapon | damage | moves/atk | dp100m | to hit | dp100m adjusted for +hit
--- | --- | ---| --- | --- | ---
shillelagh | 24 | 104 | 23 | +2 | 28
barbed wire bat | 20+6 | 121 | 21.5 | +3 | 29
baseball bat | 19 | 112 | 17 | +3 | 24.5
shillelagh (rebalanced) | 22| 104 | 21| +2 | 26

The shillelagh has an adjusted dp100m of 28 and is imho a "good dedicated weapon" (see [Bataireacht](https://en.wikipedia.org/wiki/Bataireacht)) and at least equal to a barbed wire baseball bat. That being said, I think the barbed wire bat is an outlier and a bit too good for an improvised weapon. 

The loaded stick damage was really just guesstimated and I agree it's too high. I was trying to justify it's requirements.

Adjusting shillelagh damage from 24>22 and loaded stick from 31>27. Let me know if it needs more adjusting.

**Comment by aoae23** [comment]
PR idea: rename New England to New Ireland as the new name is obviously more accurate

**Comment by ampersand55** [comment]
Someone should double-check if I added the fake version to mansion.json correctly.

**Comment by ampersand55** [comment]
@kevingranade might I bother you for a re-review? Sorry if pinging you out of the blue is the wrong way to go about it, but in my limited experience PRs going to the second page tends to be forgotten.

While I'm at it, I have a couple of questions.

1. What's the appropriate way to ask for a re-review, or ask general development questions to you or other core developers?
2. What kind of items do we want added to the game, specifically weapons? I'm thinking it has to fill the following criteria: 
   1. Plausible to exist or to be crafted by a post-apocalyptic New England survivor.
   2. Be realistic in its implementation.
   3. Be potentially useful.
   4. Be sufficiently different from other items.
   5. Not mess too much with the game balance.
3. I had planned to use the "weighs category" to also make a blackjack, and potentially a slapjack. Is that a good idea?

https://bestselfdefenseweapons.com/what-is-the-difference-between-a-slapjack-and-blackjack/

**Comment by Fris0uman** [comment]
Your PR is not forgotten but reviewing everything takes times, also PR marked CR or WIP are ignored I think so if you think it's ready you should remove CR from your title.

**Comment by ampersand55** [comment]
> 
> Your PR is not forgotten but reviewing everything takes time, also PR marked CR or WIP are ignored I think so if you think it's ready you should remove CR from your title.

Will do. Thanks for answering.

**Comment by kevingranade** [comment]
No problem at all, with that one issue addressed this is good to go, I just haven't had much review time recently.

**Pull request merged**
