### PR TITLE
[Xedra Evolved] More Ierde and Undine Paraclesian traits

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved] More Ierde and Undine Paraclesian traits"

#### Purpose of change

Trying to bring some of the other elements to par with how much Arvore has.

#### Describe the solution

Add more traits:

IERDE

- Avalanche Blow: After a brief wind-up, smash nearby terrain for extra damage (Strength multiplied between 2.5 and 3.5 times for the attack)
- Calling the Children of the Stones: Summon a minor earth fae to aid the Ierde.
- The Hills Overlook the Valleys: Like an observer on a mountaintop, the Ierde sees more than most. +3 Perception.
- The Soil Knows Those Who Tread Upon It: While on natural earth or stone or underground, the Ierde can sense the movements of nearby creatures through the earth. Losing contact with the living earth will deactivate this trait (_Requires Ierde Eyes and Ierde Ears_)
- The Stone Does Not Rot: The Ierde is immune to parasites and disease (_Requires Threshold and Vigor of the Mountain_)
- Mind Of Iron: The Ierde's mind is like an impenetrable fortress, rendering them immune to debilitating external influences.  They cannot hallucinate or be affected by psychic attack. (_Requires Threshold, The Hills Overlook the Valleys, and Inexhaustible Strength of the Earth_) ["Psychic attack" means flaming eyes--sadly no way to make them immune to MoM telepathy or the proposed psionic damage type in Magiclysm]

UNDINE

- Pounding Surf Strikes: Like the waves smashing on the shoreline, the Undine does 25% more melee damage. Consumes thirst while active. (_Requires Crashing Waves_)
- Crushing Pressure: Spell to do bash damage and slow a single target. (_Requires Water Sealed_)
- Whirlpool Catches the Shoal: Spell to drag a group of targets toward a central point and slow them. (_Requires Crushing Pressure_)
- Tidal Wave: Spell that does bash damage, bashes terrain, downs, and pushes enemies back in a line (_Requires Threshold and Whirlpool Catches the Shoal_)
- Like the Flowing Fountain: The Undine's mana regenerates 50% faster while standing in water or underwater. (_Requires Like a Fish in the River_). Upgrades to: 
- Like the Rushing Fountain: The Undine's mana regenerates 50% faster and they have 50% more mana while standing in water or underwater. (_Requires All Rivers Flow to the Sea_). Upgrades to:
- Like the Overflowing Fountain: The Undine's mana regenerates 50% faster, they have 50% more mana, and their Stamina regenerates 100% faster while standing in water or underwater. (_Requires Threshold_).
- The Pond's Depths Do Not Freeze: The Undine is completely immune to cold temperatures while underwater. (_Requires The Sea Sustains Me_)
- Befouled Water Rebuke: The Undine infuses their own body with their acidic mist, burning anyone who strikes them and making the Undine immune to acid. Consumes thirst while active. (_Requires Threshold, Fluid Body, and Acidic Mist_)
- The Sea Is Always With Me: The Undine can carry a bit of extra water in their liquid skin, fortifying them for journeys away from water sources (_Requires Threshold and Wave Skin_). [Implemented as an integrated pocket that can only contain water]

I have more Ierde ideas, but a thousand lines is more than a good place to stop, especially since I need to put in them shaping the earth like Arvore can grow plants, and that alone is likely to be a couple hundred lines. Sinking into the earth to sleep and heal, an ablative shield, sensing dirt and rock...these things will come.

#### Testing

Mutated category and tested all current traits to make sure they work. 
image

#### Additional context

Thank you Xedra Evolved for letting me use all the florid power names that would absolutely not fit into Mind Over Matter.

### CODE REVIEW

**Comment by Rokharn** [comment]
I hope fae ban for undine not become active before she will get The Pond's Depths Do Not Freeze. Because situation to needs some sleep and still having not this mutation at the winter or early spring/late autumn more, than possible. Maybe better to change this mutation to pre Threshold?

At same time Pounding Surf Strike very strong, it fits well as after Threshold power.

**Comment by Standing-Storm** [comment]
> At same time Pounding Surf Strike very strong, it fits well as post Threshold power.

It is very strong, but it also requires thirst to use (1 point per 30 seconds), meaning the ability to keep it up is limited, and competes with other powers that do/will also take thirst as well as the Undine's increased thirst requirement. It's part of my goal to make Undines the strongest near water sources but having to carefully manage their thirst when away from the water.

**Comment by Rokharn** [comment]
With all of this powers with thirst cost, I think, Undine needs some kind power similar to 'drop concentration' or auto dis-activation of this powers at some hydration level to prevent dehydration to death.

**Comment by Standing-Storm** [comment]
> With all of this powers with thirst cost, I think, Undine needs some kind power similar to 'drop concentration' or auto dis-activation of this powers at some hydration level to prevent dehydration to death.

Thirst-based traits will auto-deactivate if thirst is high enough, fortunately.

**Pull request merged**
