### PR TITLE
Butter is now just as unfun and nauseating to eat as cooking oil

### PR DESCRIPTION
**Pull request by moxian**
#### Summary
Balance "Butter is now just as unfun and nauseating to eat as cooking oil"

#### Purpose of change
Butter existence in residential fridges creates a degenerate gameplay.
It spawns plenty, has a high energy density, and used in a lot of recipes, which looks like a great food to grab and haul back to the main base when raiding. However, each individual recipe calls for only a little bit of it, and most of the butter is unused.
Butter also spawns with slightly random spoilage state, so it never goes bad all at the same time, but rather it does so gradually. So when I get hungry, and wonder what should I eat today, I go stand next to my perishable food tile press `E` and the answer is always "eat butter - it'll go bad soon, you can't be wasting food!".
20241221-232633-cataclysm-tiles

This is dumb, and I feel really bad that the game forces me to do the dumb thing. The in-game consequences for eating it is only just "-1" morale which is who cares, so that becomes the correct thing to do. Anecdotally, it seems to get presented as a "correct" gameplay on the discords.
IRL I think would not feel very well for a day or so if I had to eat a full butter stick.

So this PR aims to change this and align cata experience *somewhat* with IRL experience by ~~disincentivizing~~ no longer incentivizing gorging on butter [as much].

#### Describe the solution

Buter has now -25 fun and gives you nausea, exactly the same as animal/vegetable cooking oils.

#### Describe alternatives you've considered

- reduce it's "healthy" stat. This was the original implementation of the PR, but the feedback (below) didn't like it.
- make it completely unedible when raw - overkill for purpose, and a bit silly
- make it have much less calories when raw - kinda unrealistic, but also doesn't really do anything to fix the problem (I'd still be eating it)

#### Testing
20241222-140802-cataclysm-tiles

### CODE REVIEW

**Comment by RenechCDDA** [comment]
I would like to note that cooking oil also makes you nauseous when you consume it, which you don't seem to have mentioned. I think that's a bit overkill to apply to butter, but worth pointing it out as an option.

I think I agree that shoving butter down your gullet should be unhealthy.

**Comment by moxian** [comment]
I did mention cooking oils, in a late edit:

> - do the same to animal/vegetable cooking oil - not relevant. They do not spoil, so they do not run into the same problem of "needing to consume now" (they also have an insane unfun value, but I only realized this now - it was never really a consideration for me)

If someone wants to do the same to those - I won't mind, but they don't negatively affect my current gameplay, so I leave them be.

**Comment by moxian** [comment]
That's actually a great alternative!

Sadly, I don't have any preference between that and this PR, so I'll leave it like this so as to minimize effort spent. But if someone feels strongly about this, I'm happy to switch it up!

**Comment by RenechCDDA** [comment]
*I* think unhealthy butter is the way to go. So yes, please keep it up!

**Comment by Fris0uman** [comment]
Butter is not toxic, is not a drug and has no reason to tank your health. "Butter tank health because I think eating butter is dumb" is npt a correct justification for this change.

**Comment by PatrikLundell** [comment]
I think most people find the thought of eating just butter nauseating, but some seem to like it.

Making it unhealthy is bad, because that will make everything made with it unhealthy as well.

What you really want is some logic that makes eating something alone and in quantity make you nauseous, but doesn't affect its usage in moderation and for its normal purpose. The currently available logic that matches this best is the enjoyment factor. Sure, a utilitarian player won't care about the "feelings" of their character, but that player will still suffer SOME negative effects from it through the focus impact. Thus I would advocate for a significant bad enjoyment. Note, though, that this might make it ineligible for the faction camp calorie storage, which might be undesirable.

**Comment by Rimplestilt** [comment]
I do agree its an issue how you can force your character to eat things you think would make you nauseas and suffer no real penalty, but I do agree with others the -1 healthiness is not the way to go. I don't think we have a way for food effects to change with quantities, but that would be more ideal.

For example your enjoyment of certain things can dramatically change given quantity, as can health. For example, some ketchup or mayonnaise or mustard might be very enjoyable on a sandwhich, or some butter in various foods, but I guarantee if I eat 3 sticks of butter not only will I want to puke, my stomach will regret it  somehow. Of course taste is rather subjective.

I wonder if its possible to have limits to eating certain items where a message could pop up after a small quantity saying "The thought of eating any more of this right now is off-putting/awful/repulsive. Are you sure?" Where a stronger word could implied increased morale rebuff or chance of sickness/vomiting if you do eat.

**Comment by moxian** [comment]
> "Making it unhealthy is bad, because that will make everything made with it unhealthy as well"

This is not true. "healthy" is specific to the item type, and does not transfer to recipe results. You might be thinking of toxins. For example here are some fried eggs made from "unhealthy" butter:
20241222-140418-cataclysm-tiles

> Note, though, that this might make it ineligible for the faction camp calorie storage, which might be undesirable.

This would be desirable. For the same reasons.

Anyway, due to feedback, I've changed the item to what @RenechCDDA suggested. It now has the same fun and same nausea effect as cooking oils, that it is mostly interchangeable with.

**Comment by moxian** [comment]
> Butter is not toxic, is not a drug and has no reason to tank your health

While I agree that this is not a great rationalization, healthiness is a gamey stat anyway. We have lots of "junk food" that is neither toxic, nor a drug yet tanks the health (just from the crafting menu: "caramel", "french fries", "salted popcorn", "fast noodles", "onion rings", etc). They are only "unhealthy" for game reasons, not for IRL reasons. But I'm afraid that if I made a pr removing their unhealthiness (because they are neither toxic nor a drug), I'd meet the same kind of resistance advocating for status quo...

**Comment by qaziquza** [comment]
Personal testimonial here: big fan of raw butter. Not in excessive amounts, sure. But I'll gladly eat 100 grams of butter, any day.

**Comment by Astillia** [comment]
It seems unreasonable to push the nerf past an enjoyment malus, and even that is debatable. A solution outside of a nerf seems to be either A: Some sort of system to preserve butter so you can use it in later recipes (fridges already exist), or B: simply let the butter rot if you don't want to eat it. A block of fat seems like a realistic survival food for the apocalypse. 

You describe degenerate gameplay which confuses me. You can eat corpses as a gigantic dog mutant, so what does degenerate entail here? Lard, butter etc has a long history of being a last resort survival food, so it seems you are just realizing how amazing butter is as a calorie source and trying to balance it too hard. Realistically, there _would_ be butter in almost every house, its a base staple of cooking.

**Comment by Zireael07** [comment]
-25 is overkill imo. I'd go for -5 or -10

**Comment by Fris0uman** [comment]
> > Butter is not toxic, is not a drug and has no reason to tank your health
> 
> While I agree that this is not a great rationalization, healthiness is a gamey stat anyway. We have lots of "junk food" that is neither toxic, nor a drug yet tanks the health (just from the crafting menu: "caramel", "french fries", "salted popcorn", "fast noodles", "onion rings", etc). They are only "unhealthy" for game reasons, not for IRL reasons. But I'm afraid that if I made a pr removing their unhealthiness (because they are neither toxic nor a drug), I'd meet the same kind of resistance advocating for status quo...

Feel free to make them 0 health, caramel being - 1 is just as wrong as butter being - 1

**Comment by RenechCDDA** [comment]
> PatrikLundell said:
> Making it unhealthy is bad, because that will make everything made with it unhealthy as well.

I don't believe this is correct. The health effect is set on a per-comestible basis, and it is not inherited.

> -25 is overkill imo. I'd go for -5 or -10

Biased reply: I would prefer -7 at the highest, so that it can't be put directly into faction camp larders.

**Comment by moxian** [comment]
I disagree with most of the points brought up, but I don't have the energy to argue.

This is clearly not desired. Closing.

**Comment by Little-119** [comment]
Isn't there like, plans or at least a desire to replace the health system with something more realistic? That (still) a thing? And in the mean time health is too subjective of a stat to rebalance. Whether or not this is a reasonable change.

Personally I'm too roleplay-brained to make my survivor shove butter down their gullet anyway.

**Pull request closed without merging**
