### PR TITLE
Add AR glasses

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add AR glasses"

#### Purpose of change
More variety for electronic devices.

#### Describe the solution
Add two variants for AR glasses: the basic one (with just camera and a clock), and an advanced one which, in addition to that, allows reading electronic books, playing games and measuring ambient temperature.

#### Describe alternatives you've considered
None.

#### Testing
Launched the game, made sure that no errors happen and that all the functions of glasses work properly.

#### Additional context
Roughly based on #50327 , but I didn't add any C++ code.

### CODE REVIEW

**Comment by Drew4484** [comment]
There's a similar concept in Aftershock, might be worth combining with this.

**Comment by AtomicFox556** [comment]
> There's a similar concept in Aftershock, might be worth combining with this.

Do you mean adding all the same functions to similar devices in Aftershock?

**Comment by Drew4484** [comment]
> > There's a similar concept in Aftershock, might be worth combining with this.
> 
> Do you mean adding all the same functions to similar devices in Aftershock?

If that works for what you want to implement, then yeah no need to rewrite the same feature.

**Comment by I-am-Erk** [comment]
Basic build isn't passing

**Comment by AtomicFox556** [comment]
> Basic build isn't passing

Not related to my changes as far as I could figure out.

> (~[slow] ~[.],starting_items)=> 15:54:40.831 ERROR : src/map.cpp:376 [std::unique_ptr<vehicle> map::detach_vehicle(vehicle *)] detach_vehicle can't find it!  name=Cargo Van, submap:0,0,0

**Comment by Termineitor244** [comment]
> Not related to my changes as far as I could figure out.

@AtomicFox556 still, you need to pass this test for your PR to be merged, try rebasing your branch on master to see if that fixes it.

**Comment by AtomicFox556** [comment]
Build passed now; guess it was just a random failure.

**Comment by NOCH2004** [comment]
after reading [#50327](https://github.com/CleverRaven/Cataclysm-DDA/pull/50327) I think there could be another option. A Military based variant on par with the ballistic glasses with lower protection but higher weight/volume/encumbrance that uses UPS to provide a similar bonus to the Targeting System CBM rather than the infrared vision mentioned in [#50327](https://github.com/CleverRaven/Cataclysm-DDA/pull/50327) along with radio and the features you already listed. rare drop from zombie soldier, very rare drop from scientist, possible result of the nanoprinter and can be found rarely in labs in place of a CBM

**Pull request merged**
