### PR TITLE
[WiP][CR]Split seasons from monster evolution and food rot

### PR DESCRIPTION
**Pull request by Coolthulhu**
Currently turn 0 is always 0.00 of the 1st day of the spring. Here I tried to fix it by making the game time and "world time" separate, to allow late year starts without having to deal with day 0 predators or having to scale the entire evolution so that predators never appear.
- [x] Weather calculations
- [ ] Savegame compatibility
- [ ] Sunlight
- [ ] Moonlight

### CODE REVIEW

**Comment by kevingranade** [comment]
This is a perenial/seasonal (har) pain in the ass, but I've never seen a
decent way to do it, and the payoff is also pretty low.

**Comment by tyrael93** [comment]
if you can actually pull this off then I think I might start believing in a higher power.

**Comment by CIB** [comment]
I still find it questionable to have any events at all be in absolutes relative to "turn 0". Example: Presumably there's a specific time-stamp when refridgerators stopped working.. and a specific time stamp when monsters started appearing. The former affects food rot, the latter monster evolution. It'd be nice if a mod could actually untangle the two, rather than this being hardcoded into the C++ source code. But that's a different complaint, not really relevant to this PR. Just thought I'd mention it.

**Comment by Coolthulhu** [comment]
drbig already solved the worst issue (evolution scaling) and this PR is kinda old. If I restart it, I'll rewrite it from scratch.

**Pull request closed without merging**
