### PR TITLE
Added XL variants to sandals

### PR DESCRIPTION
**Pull request by Mer1ck**
#### Summary
Content "XL variants of sandals"

#### Purpose of change

It seemed odd that some of the most basic and versatile footwear was unable to be worn by mutants.

#### Describe the solution

Adding XL variants, like with numerous other footwear examples.

#### Describe alternatives you've considered

Leaving it alone and not adding anything

#### Testing

Changes were made and a fresh game was able to load without errors. I debugged in the recipe knowledge, and wore the added sandals. Everything appears to be in order.

### CODE REVIEW

**Comment by Karol1223** [comment]
image
Man that's really big sandals

**Comment by Maleclypse** [comment]
Anyway you can make your changes without creating so much change in the files?   Or is it only changing every line in the files touched until they are linted properly?

**Comment by Mer1ck** [comment]
> Anyway you can make your changes without creating so much change in the files? Or is it only changing every line in the files touched until they are linted properly?

Sorry, it's probably a bad habit. I usually upload the file with the changes rather than making them directly in github.

**Comment by Maleclypse** [comment]
> > Anyway you can make your changes without creating so much change in the files? Or is it only changing every line in the files touched until they are linted properly?
> 
> Sorry, it's probably a bad habit. I usually upload the file with the changes rather than making them directly in github.

In this particular case, it's making this unmergeable as I can't figure out what you've done to check it.  Like I can see your summary but I'm not checking ten k lines to make sure the only changes made are the ones you intended to make.  Not only am I not trying to check that many lines I would fail if I did try.

**Comment by Zireael07** [comment]
If you uploaded your file, it's highly likely your text editor did something weird (formatting, encoding etc.) that caused so much spurious changes.
Github online editor is usually a bad option but for a small change like this it might be worth giving it a try

**Comment by Mer1ck** [comment]
I've uploaded a second attempt, this time edited directly in Github. It should correctly highlight exactly what I added.

**Pull request closed without merging**
