### PR TITLE
[WIP] Add a music player

### LINKED ISSUE #44761: Playback of music from external media player when the player character can hear music
# Is your feature request related to a problem? Please describe.
The basic idea of this feature would be to either play or pause a running media player's music when your character starts/stops hearing music. Please note that I'm not suggesting that volume is even attempted to be controlled as that could lead to potentially bad results.

# Describe the solution you'd like
The first way I thought of doing this would be to fire off a keystroke (XF86AudioPlay on Linux) that a media player can pick up and use to play/pause music. It wouldn't keep it in sync, but ideally the player should have manually enabled the feature and would know to not have their music playing before loading up a character.  

Another potential solution would be to write the state of the music in game to a file/pipe and let a helper program handle it from there. I think the solution would be less complex codewise and open up a window for other status effects to be written to a similar/the same file (say for haptic feedback or an external display).

# Describe alternatives you've considered
I guess an alternative would be to press the keyboard key myself, but I think that this way would be far more immersive.

# Additional context
An example as to how the keypress might be done under Linux can be found [here](https://shanetully.com/2012/07/simulating-mediakey-presses-in-x11/) and for Windows, I figure that the [SendInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) function of the WinAPI would be used.  

If the file writing approach were to be used, I think that something similar to the save file system would work. It'd even be a good choice for the companion program because (afaict) there's already a json marsaller in place.

My C(++) is kind of rusty and I don't know what libraries are (already) in use, but I should be able to hack something together if desired. My only real sticking point is that this is a really large project and I'm not so sure where I should be looking to start.

### PR DESCRIPTION
**Pull request by 8street**
#### Summary

SUMMARY: Features "Add a music player"

#### Purpose of change

The player in game is listening a missing music via mp3 player, smartphone, etc. Time to fix it. 

I present to your attention "CataCurses Music Player". After player using the mp3 player or smartphone in game, music menu appears. After starting the music, if the player is not deaf, he will hear the music.

This should close #44761.

#### Describe the solution

Some features like rewind, show music duration, and slider will probably not work. I don't know how to implement them. But everything else is already working well.

To listen, you need to put your music files in a folder %CDDA_folder%/music/

Unfortunately I had to use an experimental library in C++14 - `<experimental/filesystem>` to get all music files in folder. This requires the necessary compiler flags to be set. I have set these flags for Windows compiler, but I need help to do this for all compilers used in the project. I hope for your help or ideas on how to abandon `<experimental/filesystem>` library.

#### Describe alternatives you've considered

Instead `<experimental/filesystem>` library use boost lib (which is the same) or a lot of `#ifdef` directives with its own implementation for each OS.

Also I first wanted to use .json files for music. But seriously? I want to listen to music, not fill a json file everytime.

#### Testing

Get mp3 player and activate it.
Tested on windows build.
Player adequate resizes and updates after game window resize.
Buttons stop, play, pause, next and previous track works correctly.
Music list and music scrollbar works.

#### Additional context

Outdated 
player

### CODE REVIEW

**Comment by Xaleth** [comment]
I'm thinking maybe you might want to have a more intuitive name than CataCurses because
1) Some people may have never heard of ncurses and having a curses word there is kinda weird.
2) The software of this (in-game) may have been developed before the Cataclysm and having the name there is ehhh

May I, a mere insignificant ball of flesh, offer you a suggestion? Just try to stay with the standard mp3 player title if it's from an mp3 player and the same for the other music players.

**Comment by Vzor-** [comment]
I personally like the name CataCurses. It makes about as much in game sense as a handheld gaming system having S N A K E.

**Comment by Xaleth** [comment]
[Aye](https://tenor.com/view/the-big-lebowski-jeff-bridges-the-dude-john-goodman-walter-sobchak-gif-5042638)

**Comment by 8street** [comment]
If you have any suggestions on how to name the player, I of course will rename it. If this name is better than the current "CataCurses".
The player looks like this now.
player2

Now game is built on most compilers. Sorry on android I had to disable this innovation. It remains to change the mingw-w64 and Xcode configuration. Yesterday I spent 4 hours with WSL (Windows Subsystem Linux), but I could not understand the reason why it won't compile. The same code compiles well from Windows with the same mingw-w64.

**Comment by 8street** [comment]
I decided to switch to the boost lib because MXE does not support experimental/filesystem in std c++ libs.

**Comment by kevingranade** [comment]
Nope, nope, nope nope nope nopenopenopenope.....
1. No music player in the project. You can crank out a prototype like this real quick, but this WILL invite piles and piles of feature requests and bugfixes, and I have no interest in managing a music player project inside a game project.
2. Absolutely. No. Boost. Ever. There are a number of strong reasons to keep the project dependencies minimal, and boost is antithetical to that goal. 

Opening a *control channel* to an external music player *might* be reasonable to add, and gets us off the hook for actually handling the music files or whatever themselves.  I honestly don't think this is practical either, as such control channels tend to be super idiosyncratic and often require weird dependencies.

**Pull request closed without merging**
