### PR TITLE
Remove the army improvized field repair manual and make the recipes have the auto learn flag

### PR DESCRIPTION
**Pull request by ISuckM8**
#### Summary

Balance "Removed army improvized field repair and made its recipes available by default at level 2 mechanics"

#### Purpose of change

The recipes the manual provides are extremely simple and realistically don't need a manual of any kind.

#### Describe the solution

Simply remove the army field repair manual and make the recipes available when you have 2 in mechanics.

#### Describe alternatives you've considered

Making the recipes require other manuals like Under the Hood.

#### Testing

It's working just fine.

#### Additional context

Nothing here.

### CODE REVIEW

**Comment by Karol1223** [comment]
You are removing an item without any sort of migration which will cause errors on existing saves. Don't do that. Migrate it.

**Comment by Maleclypse** [comment]
None of those are autolearn recipes for people that don't know about vehicles.

**Comment by ISuckM8** [comment]
> None of those are autolearn recipes for people that don't know about vehicles.

So would they be an Under the Hood recipe?

**Comment by ISuckM8** [comment]
> None of those are autolearn recipes for people that don't know about vehicles.

This is still only something that appears when you have two in mechanics, which is around the level of difficulty and knowledge to make a makeshift version of something from other skill trees. I don't think making a makeshift driver belt requires that much effort. This should at least require something else besides this extremely rare manual.

**Comment by NerosShadow** [comment]
The belts we get issued in the BDAR kit which is used in conjunction with the Battle Damage and Recovery Handbook (improvised field repairs manual) aren't really something that could be made. Until we implement a quality of parts, or parts that break down over time with usage, being able to recognize that the red thing is used for making temporary belt repairs is sort of niche.
BDAR Kit_old
Im not even sure that it should be craft-able without the adjustable belt, the only temporary belts that I have seen work are for v-belts, AFAIK there is no real world solution for serpentine belts other than replacing them.

**Pull request closed without merging**
