### PR TITLE
Natural mineral springs

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
```SUMMARY: Content "Forest basins may occasionally be mineral springs."```

#### Purpose of change
Mineral water springs exist in nature in real life, and I thought this would give an incentive for exploration.

#### Describe the solution
Forest ponds now occasionally contain springs of mineral water. Mineral water from these sources has a slight health boost, but might contain parasites (bugs like to live and lay eggs in natural still water sources). The flag to determine if a water source gives mineral water or normal water is `MINERAL_WATER`.

You can boil it to make it into clean water, or purify it to turn it into spring water, which doesn't have a health boost but does maintain the additional quench. Existing mineral water has been made into spring water.

Mutants with Freshwater Osmosis can also get a slight boost to their health by chilling in a spring for a while.

#### Describe alternatives you've considered
I actually had an idea of implementing some sort of post-Cataclysm water that had alien contaminants that influenced your body in different ways, but this felt unoriginal since I'm pretty sure that the blob is in the groundwater already.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Spring water and still water seem opposite of each other. Springs are natural ways of underground water to appear on the surface, thus the water flows constantly, often being filtered by sand before it emerges. I always believed that such water is pretty safe to drink as is. Also wiki says that there are some insects that like living near different types of springs, but they don't interact with humans. All in all I'm pretty surprised that you added the chance of parasites.

**Comment by Ilysen** [comment]
I might be incorrect, as most of my knowledge about mineral water comes from an outdoorsy good friend who brought me to a capped-off spring in Arkansas and explained that water flowed from underground and pooled into the area, and that it was capped off to prevent insects from laying eggs in it while still letting people access the water itself for drinking.

That's mostly what I based this off of, at any rate. The ponds themselves are springs of mineral water that pooled/pool naturally and still exist in that state. I could remove the parasites, if need be.

**Comment by Rail-Runner** [comment]
Do you think it could be useful for the same applications as "normal" water? Might be a good idea to add it to recipes then.

**Comment by Mecares** [comment]
Generally it would be preferable to make mineral water have more health and/or fun and/or vitamins and not more quench since quench in the game is the physical body requirement for water and a few minerals and a bit of solved carbon dioxide does not make it contain more water than pure water.

**Comment by Ilysen** [comment]
Taking a short break, but I'll do some adjustments shortly.

**Comment by thethunderhawk** [comment]
I agree, specifically I think water with the normal quench plus a slight health boost would be sufficiently rewarding to interest a survivor without getting too magical.

**Comment by Fris0uman** [comment]
Is the parasite the same you get from eating raw meat ? I'm not too sure that it is "realistic" but I can't check right now.
The quench thing could make sense as water with a bit of Na and/or sugar in it is better absorbed (see the electrolyte in gatorade) by the body.

**Comment by Ilysen** [comment]
The break is going indefinite for now. actually. If anyone would like to pick this up, you're welcome to.

**Pull request closed without merging**
