### PR TITLE
Pruning the old ``to-hit`` syntax - Part 9

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Continuation from #76281

#### Describe the solution
Worth to point out that I also removed damage values from a bunch of stuff that didn't have a defined ``to_hit`` anyway, as a bunch of apparel was doing damage where it should not have in any reasonable situation done so

Affected files:
- ``armor\cardboard.json``
- ``armor\exotic.json``
- ``armor\eyewear.json``
- ``armor\head_attachments.json``
- ``armor\helmets.json``
- ``armor\hoods.json``
- ``armor\integrated.json``
- ``armor\jewelry.json``
- ``armor\legs_armor.json``
- ``armor\masks.json``
- ``armor\pets_dog_armor.json``
- ``armor\storage.json``

#### Additional context
The next PR should finish off the ``armor`` folder

### CODE REVIEW

**Comment by akrieger** [comment]
Legit looking failures.
```
(~[slow] ~[.],starting_items)=>   CHECK( calc_expected_dps( weap.first ) == weap.second )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   Approx( 5.3147823341 ) == 8.42
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   integrated_chitin3_claws's dps changed, if it's intended replace the value in
(~[slow] ~[.],starting_items)=>   the respective file in data/mods/TEST_DATA/expected_dps_data.
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/effective_dps_test.cpp:294: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( calc_expected_dps( weap.first ) == weap.second )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   Approx( 7.4637222144 ) == 11.31
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   integrated_giant_pincer's dps changed, if it's intended replace the value in
(~[slow] ~[.],starting_items)=>   the respective file in data/mods/TEST_DATA/expected_dps_data.
```

**Comment by Karol1223** [comment]
> Legit looking failures.
> ```
> (~[slow] ~[.],starting_items)=>   CHECK( calc_expected_dps( weap.first ) == weap.second )
> (~[slow] ~[.],starting_items)=> with expansion:
> Error: (~[slow] ~[.],starting_items)=>   Approx( 5.3147823341 ) == 8.42
> (~[slow] ~[.],starting_items)=> with message:
> (~[slow] ~[.],starting_items)=>   integrated_chitin3_claws's dps changed, if it's intended replace the value in
> (~[slow] ~[.],starting_items)=>   the respective file in data/mods/TEST_DATA/expected_dps_data.
> (~[slow] ~[.],starting_items)=> 
> (~[slow] ~[.],starting_items)=> ../tests/effective_dps_test.cpp:294: FAILED:
> (~[slow] ~[.],starting_items)=>   CHECK( calc_expected_dps( weap.first ) == weap.second )
> (~[slow] ~[.],starting_items)=> with expansion:
> Error: (~[slow] ~[.],starting_items)=>   Approx( 7.4637222144 ) == 11.31
> (~[slow] ~[.],starting_items)=> with message:
> (~[slow] ~[.],starting_items)=>   integrated_giant_pincer's dps changed, if it's intended replace the value in
> (~[slow] ~[.],starting_items)=>   the respective file in data/mods/TEST_DATA/expected_dps_data.
> ```

They look legit, and they're the reason I'm not doing anything with this PR, but I don't know whether they actually are legit.

From my understanding, unarmed weapons do not use ``to-hit`` at all when worn. The ones here are integrated, so should only ever be worn. For the weapons the tests cry about, ``to-hit`` is the only aspect I changed.

What this means is either unarmed weapons *do* use ``to-hit``, or the DPS calculation (and by extent DPS display in item description) lies to the player because it calculates the DPS with ``to-hit`` in mind when in reality it doesn't use it.

**Comment by Maleclypse** [comment]
@anothersimulacrum  I think you might be the best person to answer the above question.

**Comment by anothersimulacrum** [comment]
To-hit is not applied when using worn weapons. I think this should be considered a bug.

**Pull request merged**
