### PR TITLE
Santa costumes!

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Content "Adds santa costumes to the game"

#### Purpose of change
It's almost December! We need to have some santas delivering gifts to all the zombies!

#### Describe the solution
Adds the clasic santa costume, as well as some other variants for more flavor.

#### Describe alternatives you've considered
To have a sad christmas in the middle of the cataclysm.

#### Testing
None yet.

#### Additional context
WIP until I add the spawns and variants... Tell me if you think zombies should drop this as a possible set like the current wedding dress and hat!

 
<details> 
<summary>Inspirations for the clothing (Images) </summary>

Santa traditional costume:
Santa suit long

Santa beard:
https://www.amazon.com/Costume-Christmas-Accessories-Adults-Disguise/dp/B07YWMSR2K/ref=sr_1_11?keywords=santa+beard&qid=1638173459&sr=8-11

Santa dress:
Santa dress normal

Santa luxury dress:
santa dress long luxury
Santa dress long luxury 2

Santa short dress:
Santa dress short

Santa short jacket:
Santa suit short

Santa short:
Santa shorts

</details>

### CODE REVIEW

**Comment by dseguin** [comment]
If you want, I could make it so that zombies can drop santa costumes during Christmas. Or better yet, maybe I could add a field to item groups which makes them spawn during special events? Something like:
```json
{
  "id": "clothing_christmas_set",
  "type": "item_group",
  "subtype": "collection",
  "items": [
    { "item": "santa_jacket", "prob": 50, "event": "xmas" },
    { "item": "santa_belt", "prob": 50, "event": "xmas" },
    { "item": "santa_gloves", "prob": 50, "event": "xmas" },
    { "item": "santa_hat", "prob": 50, "event": "xmas" },
    { "item": "santa_belt", "prob": 50, "event": "xmas" },
    { "item": "santa_pants", "prob": 50, "event": "xmas" }
  ]
}
```

**Comment by Termineitor244** [comment]
> If you want, I could make it so that zombies can drop santa costumes during Christmas. Or better yet, maybe I could add a field to item groups which makes them spawn during special events? Something like an `"event"` field:

It would be awesome! Please do it! I was thinking of implementing witch/wizard clothes after this, so it would be of use for halloween too!

**Comment by PatrikLundell** [comment]
Zombies ought to be outfitted with whatever they wore when the cataclysm occurred, not somehow change their clothing based on the current season. For that reason, I think this ought to be a mod that you actively selected rather than a part of the core.

**Comment by Termineitor244** [comment]
> Zombies ought to be outfitted with whatever they wore when the cataclysm occurred, not somehow change their clothing based on the current season. For that reason, I think this ought to be a mod that you actively selected rather than a part of the core.

The holiday itemgroups can easily be put on a mod if that is wanted, I don't have a strong opinion on it, and even then the clothes will still be able to be dropped by zombies very, very rarely (To represent cosplays and professional santas), or be found on stores/houses etc.

**Comment by dseguin** [comment]
> Zombies ought to be outfitted with whatever they wore when the cataclysm occurred, not somehow change their clothing based on the current season. For that reason, I think this ought to be a mod that you actively selected rather than a part of the core.

I could add a menu option to enable/disable these kinds of item spawns (disabled by default), so that it wouldn't affect normal gameplay unless the player intentionally enables it.

**Comment by PatrikLundell** [comment]
The items themselves make sense (I can easily imagine someone's storage having a Santa suit stored away for next Christmas).

How many professional Santas are there (i.e. year round professionals)? It's probably more likely to encounter that dress on a costume party.

However, extra spawning based on season (real world and/or in game) ought to be opt-in. @dseguin's suggestion is very reasonable if it's easy to implement.

**Comment by Termineitor244** [comment]
> 

I plan to add it as the minimal (1) possibility to spawn a set (full or not) of santa clothing for the regular zombies, it could be even lower given the huge amount of zombies in the game... Maybe I can make it even lower if that 1 is used for "costume clothing" in general, including the (soon to be implemented) witch/wizard clothing and others, but for now it would need to include only santa costumes.

And yes, @dseguin suggestion is a good one for seasonal drops.

**Comment by FoolsGold45** [comment]
I have some description nitpicks:

1) "in christmas" as listed in many of the item descriptions isn't proper grammar. "during Christmas" or "on Christmas" would be better. Christmas and Santa should also be capitalized in all uses (maybe not necessary in the item names).
2) "Mrs. Claus" is a more common name for what I think you're trying to represent with "Miss Santa"

**Comment by Termineitor244** [comment]
> I have some description nitpicks:
> 
>     1. "in christmas" as listed in many of the item descriptions isn't proper grammar. "during Christmas" or "on Christmas" would be better. Christmas and Santa should also be capitalized in all uses (maybe not necessary in the item names).
> 
>     2. "Mrs. Claus" is a more common name for what I think you're trying to represent with "Miss Santa"

Done! Tell me if you find anything more that needs to be changed.

And I used "Miss Santa" for the descriptions of some objects because that's how they were called on shops online (For the models I based the ones for the game), but I changed all mentions to "Mrs. Claus" for clarity.

**Comment by dseguin** [comment]
@Termineitor244 Now that #53100, you can try using it with the Christmas clothing if you want. Don't worry too much about the spawn probability because the `Special event spawns` menu option is disabled by default.

**Comment by Termineitor244** [comment]
> @Termineitor244 Now that #53100 is merged, you can try using it with the Christmas clothing if you want. Don't worry too much about the spawn probability because the `Special event spawns` menu option is disabled by default. So if the player enables the feature, it means they want to find the items you made. 👍

Thanks! I already implemented the special drops! The PR seems to have some problems so I will open another in a clean state...

**Pull request closed without merging**
