### PR TITLE
Inhaler helps with the smoke

### LINKED ISSUE #7583: Make Inhaler help with Smoke
As a [Bronchodilator](https://en.wikipedia.org/wiki/Bronchodilator), the inhaler should probably reduce or treat the smoke effect in addition to asthma attacks. [Smoke inhalation](https://en.wikipedia.org/wiki/Smoke_inhalation) is commonly treated with both Bronchodilators and oxygen apparently. Also, some other drugs common to the Cataclysm have been used as bronchodilators in the past before falling out of favor with those stick in the mud doctors. According to wikipedia,"Additionally some psychostimulant drugs that have an amphetamine like mode of action, such as amphetamine, methamphetamine, and cocaine, have bronchodilating effects and were used often for asthma due to the lack of effective β2-agonists for use as bronchodilator, but are now rarely, if ever, used medically for their bronchodilation effect." So perhaps those should help reduce the severity of smoke inhalation as well. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2059337-make-inhaler-help-with-smoke?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #7583.

### CODE REVIEW

**Comment by AMurkin** [comment]
`has_effect` is redundant

**Comment by pisskop** [comment]
this overshadows the oxygen tanks in usefulness.  Reducing the severity should perhaps imply a stat boost to the player if->smoke instead of removing the malus of smoke?

**Comment by DangerNoodle** [comment]
Smoke can be an asthma trigger factor though. Ideally it should simply be ineffective against medium and heavy smoke inhalation.

Can smoke provoke asthma attacks in the game already? If not, then maybe instead there should be a point where minor smoke has mimimal danger to a survivor without the trait, but can trigger asthma attacks.

**Comment by kevingranade** [comment]
Ideally both oxygen and inhaler would supress the "shortness of breath" symptoms of inhalation, but leave others in place.  Inhaler would probably supress the symptoms less than oxygen.

Short term though, which is worse, inhaler doing nothing, or inhaler doing a bit too much?
I don't think anyone is planning on looking at a longer-term fix, so those are the alternatives.

I don't have a strong opinion one way or the other.

**Comment by pisskop** [comment]
a quick solution is to add ab effect for inhaler that increases the chance of coughing by a bit, since chance in this situation is defined as 1/n

**Comment by Night-Pryanik** [comment]
> effect for inhaler that increases the chance of coughing by a bit

Inhaler suppress the smoke, but increases chance of coughing caused by the smoke?

**Comment by pisskop** [comment]
:|

since chance is defined as 1/n, where chance is 'n'

**Comment by kevingranade** [comment]
Had to do a rebase instead of merge, so it didn't auto-close.

**Pull request closed without merging**
