### PR TITLE
changed the weight and to-hit of awl pikes

### LINKED ISSUE #25209: Awl Pike weight
I am new here, so... Hi. And sorry by the english 

I  came across whitch an real comum problem, weapons weight in games. This time is the awl pike.

image

This is the wrong weight, is more then two time heavier then a real one. I propose a chance to 3-4,5 kg. 

Plus: Is extreme rare a weapon witch more than 4,5 kg 

Here some links to help me.

http://www.higgins-collection.org/artifacts/2870.1

http://myarmoury.com/talk/viewtopic.18651.html

https://en.wikipedia.org/wiki/Pike_(weapon)

Thank you for your attention and if a did some thing wrong, tell me

### PR DESCRIPTION
**Pull request by y2s82**
#### Summary

SUMMARY: Bugfixes "awl pikes now have realistic weight and appropriate to-hit value"
#### Purpose of change

This fixes #25209.
It aims to better reflect the awl pike object to the real-life counter part instead of relying on imbalancing other stat to produce the desired effect.
#### Describe the solution

I have decreased the weight of the weapon to reflect the actual weapon while also decreasing the to-hit value to keep the balance of the weapon.
#### Describe alternatives you've considered

I wanted to know if there was also a flag I could add, but I could not find the use of UNWIEDLY flag or how to use it.

### CODE REVIEW

**Comment by SirPendrak** [comment]
Are you sure -2 is realistic? Common sense would suggest that +1 or 0 would be fine. All the reach is huge adventage and could help. And you can allways adjust grip on pike if you need to strike something closer. Only gets in a way if fighting in a thight corriddor. 
For ballance, while attack speed rises from weight reduction, i would suggest decreasing damage per hit. Right now its strangely high. Why would its damage be soo different from spears anyway? You can accumulate similar ammount of energy, and the tip is of simmilar quality. Thrusting weapons are different from swung wep., for example heavier and longer swords build much moore momentum than shorter and lighter, but thats not a case in thrusts.

**Comment by y2s82** [comment]
The calculation was based on the suggestions made in the issue.
And logically, I do believe it will be quite different from a spear.  Spear is made shorter and easier to wield by one person.  Pike is often made for formation attack and not for adjusting and adapting to changing situation.  Holding it shorter is likely impossible; at some point, you will have a huge portion of the stick hanging behind you, which means you will no longer have the center of gravity within the two grip points.  If the center of the gravity is within the grip points, it will be too long.

That said, if someone more versed in practicing martial arts using sticks longer than 3 meters (I am not it), please correct me.

**Comment by cainiaowu** [comment]
balance should be -2, Awl pikes is way longer than "most polearms", it make it "very clumsy or lopsided".

**Comment by SirPendrak** [comment]
Awl pike will have its center of ballance somewhere in the middle. Of course, its longer than most polearms, but thse have Point of Ballance in 3/4 or 4/5 of lenght away from the user. How does that translate to the scale used for ballance? Someone has to decide. 
It just seems awkwad to see dedicated war weapon getting -2 hit rating.

**Comment by y2s82** [comment]
My thought on -2 was the following: 
- if this weapon-of-war was used for its intended purpose (i.e. group formation, making a stationary or slow-moving porcupine-like structure, in an open-field), this would be a highly effective weapon.
- If taken out of the intended purpose, however, we are looking at a 3-meter pole with a pointy end.  How effective is a single person surrounded by zombies, running down a street or struggling through densely wooded area, wielding a 3-meter stick, weapon-of-war or not?

But I guess this also has to do with game balance.  And I also have less understanding of how to-hit translates to real-life, too.

So I ask that someone better informed make a final call on this, and I will follow :)

**Comment by kevingranade** [comment]
I'm 100% behind the -2 to-hit, the distance more than justifies it.

**Comment by y2s82** [comment]
> While you can rely on others to support your stance, you are ultimately responsible for clarifying these details when you make the PR. There's nothing wrong with asking for assistance or guidance either if you're not sure, however there doesn't seem to be a lot of due diligence here.


Thank you for a thorough explanation and reply.  I did just want to point out, though, that I took the number from the discussion held in the related issue #25209 .  While it wasn't settled here either, it had a nice calculation done by @cainiaowu who took the numbers from the GAME_BALANCE.md.  I thought that was reliable enough, and since the PR is linked to the issue, I assumed everyone here would be aware of it.

Next time, I will not make such assumption and will be more thorough about the explanation.

Again, thank you for the comprehensive reply.

**Pull request merged**
