### PR TITLE
More items in vehicles

### PR DESCRIPTION
**Pull request by illi-kun**
The following items / groups of items were added to the vehicles:
- School bus: child (majorly) & school (minorly) groups;
- Sidecar motorcycle: motorcycle helmet;
- Golf cart: golf clubs & towel;
- Police car: cop gear & cop weapons groups;
- Cube van: misc hardware & tools plus a lot of 2x4s;
- Road roller: hard hat;
- Mobile Meth Lab: meth lab group;

Additionally, the golf cart was slightly redesigned and now it contains a couple of boxes right after the seats.

This PR is based on the request #5595 (but not resolving it yet).

_UPD:_
- Quad bike: motorcycle helmet;
- Low-end van: tools & big tools;
- Hippie van: sunglasses (including fancy version), acoustic guitar, joint roach;
- Atomic sports car: cocaine & female underwear;

### CODE REVIEW

**Comment by Zireael07** [comment]
Great!

**Comment by Rivet-the-Zombie** [comment]
Very cool!

**Comment by illi-kun** [comment]
Thanks for the comments!

Since this PR isn't merged yet, I'm going to put [WIP] on it and continue adding even more stuff.

**Comment by DavidKeaton** [comment]
cop cars having weapons = thumbs up

**Comment by stk2008** [comment]
I'm well up for cop cars having weapons......buttttt

How about having the shotgun etc locked in a compartment like they are in real life.

Well in real life there bolted down with some kind of lock in the car.
So maybe if possible make it so u need a lock pick or some thing ? :)

**Comment by DavidKeaton** [comment]
@stk2008 that may require having cargo or vehicle parts with the possibility of a lock component added.

**Comment by stk2008** [comment]
Tbh other than for the reason I said above I suppose is there no real reason to mod them in as there is no other human player that can steal your stuff and I don't think NPC's can take stuff from cars?.
But if they can it would be cool for that reason to add lockable car trunks and off course for the reason I mentioned in the first post :)

No idea how easy it would be to add lockable trunks to cars.

Suppose we could add a trunk with a lockable flag etc.no idea though as I'm not a programmer :(

**Comment by DavidKeaton** [comment]
@stk2008 you're on the money. :-) add a lockable flag, possibly a chance for it to be locked, and the code to implement the flag. Some other stuff, but that's the gist! :-)

**Comment by stk2008** [comment]
Awesome well unfortunately I have zero idea how to implement that :(.

As I've said befor on the irc if I could programme I would programme so much stuff for cdda it would not even be funny :p.

Any ways I'm off to bed nn all and thanks for all the hard work u devs'modders etc do for this incredible game :)

**Comment by DavidKeaton** [comment]
@stk2008 we all are thankful you give us such praise :-) sleep well bud!

**Pull request merged**
