### PR TITLE
[Sky Island] Allow difficulty selection for Warp Home spell

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Sky Island] Allow difficulty selection for Warp Home spell"

#### Purpose of change

If you play Sky Island with any powers mods, you might have gone in to use a power, perhaps the biokinetic power Physical Enhancement so you would have an easier time hauling 10 backpacks home, and instead hit the Warp Home power right next to it and shown up back at your island safely, bypassing the entire gameplay loop.  Sure, you were at full health and in good condition, and you probably would have made it to the exit.  But now you'll never know.

Not that that just happened to me or anything.

#### Describe the solution

Add a confirm dialogue box that says: 

> This will warp you home directly, bypassing the mission structure and need to find an exit point.  Do you want to warp home directly?

The default is false, so if you accidentally click Warp Home you will not be sent directly home.

Also, allow selection of the Warp Home spell in the Difficulty Options.  There are four options: 

1. Works the way it does now. You get the Warp Home spell and can warp home whenever you want, it's up to you not to abuse it.
2. You get the Warped Return spell, which only works if there are no enemies nearby (so no hiding in a closet) and costs one warp shard to use.
3. You get a recipe for a Warped Skyward Beacon for 5 shards that will send you home. It takes a minute to cast so you can't use it as an an emergency escape if two hulks bust through the wall (That's what the homeward mote is for). It's for if there's an impassible river between you and the exit, or the exit is next to a collapsed tower, or whatever.
4. You get nothing. 

Each difficulty option removes the other spells/recipes when picked.  It's theoretically possible to pick 3, make a bunch of Skyward Beacons, then pick 4, but you can use the Debug menu to do whatever you want so go wild.

#### Testing

Dialogue box appears.  Selecting No does nothing, selecting Yes sends you home. 

Using the Difficulty Selector gives you the appropriate ability to return home and removes the others.  Each ability works.

### CODE REVIEW

**Comment by GuardianDll** [comment]
`This only exists in case of bugs` in spell comment make me thing the intension is left it a debug option, not advancing it to "/tp home" that user may use in any second

**Comment by Standing-Storm** [comment]
> `This only exists in case of bugs` in spell comment make me thing the intension is left it a debug option, not advancing it to "/tp home" that user may use in any second

I'm sure that was the intention, but at the moment it's automatically granted to you when you start the mod and placed into your spellcasting screen, so I didn't change that behavior.

**Comment by GuardianDll** [comment]
i mean, in my opinion, it should be removed from the spells you get from the start
if it will cause some bugs, it would be better to fix the bugs, that give player an option to just bypass all mechanic of the mod

**Comment by Standing-Storm** [comment]
> i mean, in my opinion, it should be removed from the spells you get from the start if it will cause some bugs, it would be better to fix the bugs, that give player an option to just bypass all mechanic of the mod

At the moment I haven't had any instances where the exit points failed to generate, so I don't know how common it is or if the Warp Home power is necessary (or if it used to be more necessary but no longer is). 

I thought about making it a recipe that runs the EoC (since you're unlikely to be crafting while you're down on the surface)--would that put it further out of the way? I don't have enough experience with Sky Island to say whether just making it a debug-only option is a good idea or not.

**Comment by GuardianDll** [comment]
i don't have strong opinion, i just know it was something intended for debug

**Comment by TGWeaver** [comment]
I did initially just add the spell for debugging or in case anyone got stranded because a teleporter home failed to spawn. However, if people are using it, maybe it could be moved to an optional difficulty setting? Like if you choose easy difficulty you can have a way to warp home without reaching an exfil but it takes a minute or two to cast and thus must be done in a safe place?

**Comment by Standing-Storm** [comment]
It should be possible to swap it to a difficulty setting option and then use `{ "math": [ "u_monsters_nearby('radius': 10)", "<", "1" ] }` to make it so you have to be somewhere with no enemies nearby.

I should note that I'm not actually certain anyone is using it (except me, by accident...)

**Comment by Standing-Storm** [comment]
How about this: Add it to the Difficulty selector, you get four options:

1) Works the way it does now. You get the spell and can warp home whenever you want, it's up to you not to abuse it.
2) You get the spell, but it only works if there are no enemies nearby (so no hiding in a closet) and costs one warp shard to use.
3) You do not get the spell, but can make a `Warped Skyward Beacon` for 5 shards that will cast it for you and send you home. It still takes a minute to cast so you can't use it as an an emergency escape if two hulks bust through the wall (That's what the `homeward mote` is for
4) You get nothing. Good day, sir.

**Comment by GuardianDll** [comment]
If there would've been some "sky shop" where you can buy multiple upgrades for your island (including stuff like increasing the range to teleport goods around yourself and npc teleport etc), it could be some very very rare item to sell here

**Pull request merged**
