### PR TITLE
Added "MOUNTABLE", to small and medium boulders

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Interesting. Does the `UNSTABLE` flag have any effects on using a firearm?

**Comment by BorkBorkGoesTheCode** [comment]
The UNSTABLE flag affects player movement. If it does affect accuracy, the docs need updating.

**Comment by DangerNoodle** [comment]
Should cause no problems, in that case. I had assumed that trying to keep one's balance would have affected being attacked in melee, due to the message used when entering unstable terrain. That must be incorrect then.

**Comment by DangerNoodle** [comment]
It seems there is an effect, but not what I assumed.

````
    //Unstable ground chance of failure
    if( has_effect( effect_bouldering) && one_in(8) ) {
        add_msg_if_player(m_bad, _("The ground shifts beneath your feet!"));
        return 0;
    }
````

I assume this should not logically affect ranged attacks, so no further problems.

**Pull request merged**
