### PR TITLE
Drop more unused item groups

### PR DESCRIPTION
**Pull request by mugling**
`antique_guns` and `antique_ammo` aren't used anywhere. As a result `colt_navy` and `colt_army` don't spawn anywhere and this has been the case for some time now.

I've moved those items to `obsolete.json` as they need reworking before spawns could be added and might be better of in a mod. In particular the crafting recipes need percussion caps which themselves either need a recipe or frequent spawns - neither of which seems likely in post apocalyptic New England.

If anyone feels strongly about those items nothing precludes their later resurrection either as a well integrated part of `master` or more flexibly as part of a mod.

### CODE REVIEW

**Comment by pisskop** [comment]
not that its the point of this pr, but I think a preindustrial mod would work great in cdda.

**Comment by Rivet-the-Zombie** [comment]
Both of the antique revolvers are very nice guns, and I'm all for keeping them as a rare spawn in the appropriate context.

**Comment by mugling** [comment]
@Rivet-the-Zombie agreed, but this doesn't change the status quo. They can be held in `obsolete.json` until someone has the opportunity to do something with them.

**Comment by Rivet-the-Zombie** [comment]
Right on.

**Comment by mightyagrippa** [comment]
For what it's worth, all the antique_guns revolvers already show up in other item groups. The army and navy revolvers show up frequently in museum_guns and the Lemat shows up in guns_pistol_obscure. In my most recent game I got an easy pair of Lemats from lucky basement gun safes and had a dozen opportunities to pick up army and navy revolvers from museum looting.

**Comment by mugling** [comment]
> For what it's worth, all the antique_guns revolvers already show up in other item groups.

No they don't. Those groups are entirely unused so there are guaranteed to be no spawns.

> Right on.

I'm not averse to anyone fixing them but they can't live in `ranged.json` whilst they're broken so this PR is a good compromise - we drop the unused item groups and leave the JSONS in `obsolete.json` thereby breaking nobodies games until the point someone can successfully reintegrate them and/or move them to a mod.

**Comment by BorkBorkGoesTheCode** [comment]
Why are these specific guns being moved to obsolete.json?

**Comment by mugling** [comment]
> Why are these specific guns being moved to obsolete.json?

Please read the entirety of a thread before commenting as that is amply answered above

**Comment by mightyagrippa** [comment]
> No they don't. Those groups are entirely unused so there are guaranteed to be no spawns

museum_guns is used in museum.json. Just searched ten or so museums in a build from a few days back and came out with colt_navy, colt_army, and a pile of 36navy and 44army.

**Comment by mugling** [comment]
Ah I stand corrected - `antique_guns` is not used but `museum_guns` is. A different approach is needed

**Pull request closed without merging**
