### PR TITLE
Necropolis mapgen -> general mapgen. Part 3.

### PR DESCRIPTION
**Pull request by Mshock777**
Moved pump station and garage/gas station to separate mapgen.
Reworked 2 houses I added earlier.
Fixed some necropolis mistakes (gate control was placing gates in room next to it)

(Also I swear I don't know why my gitshell doesn't want to update normally and creates this first commit.)
Never mind, I figured it out, should I make new pr?

### CODE REVIEW

**Comment by Mshock777** [comment]
Also, from office_cubical.json:

>             "mapping": {
                "S": {
                    "items": { "item": "fridge", "chance": 50 },
                    "furniture": "f_sink"
                },
                "e": {
                    "items": { "item": "fridge", "chance": 50 },
                    "furniture": "f_fridge"
                }
            },

Should i fix it?

**Comment by Mshock777** [comment]
Also, I think I heard about this problem(picture bellow), but I can't find the post. Should I create new issue?

**Comment by Chezzo** [comment]
You can get rid of those black lines by toggling software rendering.

**Comment by Mshock777** [comment]
@Chezzo I'm on my backup PC that has GeForce 7300GS, so this is not an option.

**Comment by Mshock777** [comment]
@Coolthulhu 1 second, one last commit.

**Pull request merged**
