### PR TITLE
Adds a lighthouse

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
```SUMMARY: Content "Add lighthouse."```

#### Purpose of change
To add more lake locations.

#### Describe the solution
Add a small lighthouse

#### Describe alternatives you've considered
Adding an NPC spawn, which I will probably do next.

#### Additional context
I wasn't sure what to do with the top floor where the big light should be, so I went with defunct lighthouse.

lighthouse
lighthouse_z1
lighthouse_z2
lighthouse_z3
lighthouse_z4
lighthouse_z5

### CODE REVIEW

**Comment by Moonsabrt** [comment]
For the top I think you can either put like a lamp/electronic light  in the middle of it and have it surrounded by mirrors both inside and outside.  As I believe the mirrors essentially reflected and 'intensified' the light across a great distance. Although that would require essentially moving the stairs so that it wasn't on the center and instead on the side.
OH OH OH!
It could also have a mission with it! 
Maybe have a NPC suggest to the player that they

**Comment by Night-Pryanik** [comment]
Maybe add a chance to spawn some zombified lighthouse keeper?

**Comment by ZhilkinSerg** [comment]
Or an npc which dies and spawns zombie after conversation.

**Comment by curstwist** [comment]
> 
> 
> Maybe add a chance to spawn some zombified lighthouse keeper?

it already spawns zombies.  I don't know when/if I will get to NPC for this, but other people are welcome to add them if inspired. (I don't have anyone specific in mind).

**Pull request merged**
