### PR TITLE
Write door and window unit tests

### PR DESCRIPTION
**Pull request by matshou**
#### Summary
Infrastructure "Written door and window unit tests"

#### Purpose of change

Door and window behavior has no test coverage.

#### Describe the solution

I've written 4 unit tests that ensures the following:

- [x] Doors can be opened and closed.
- [x] Windows can be opened and closed.
- [x] Doors and windows make whoosh sound when opened and closed.
- [x] Character looses movement points when opening and closing doors and windows.

#### Describe alternatives you've considered

_No alternatives considered._

#### Testing

Tests have been run locally without failure.

#### Additional context

More information about tests can be found in `gates_tests.cpp`.

### CODE REVIEW

**Comment by wapcaplet** [comment]
Something to consider - as you may know, `REQUIRE` will abort the test at the first failure, while `CHECK` will allow execution to continue.

I see you're using these `assert_*` functions both as precondition assertions (which is more appropriate for `REQUIRE`) and in the verification `THEN` clauses (where a `CHECK` would be more appropriate).

For example here:

```cpp
THEN( "the door should be able to open and close" ) {
    assert_open_gate( t_door_o, pos, true );
    assert_close_gate( t_door_c, pos, true );
}
```

If for some reason both opening and closing are failing, with `REQUIRE` only the open failure would be caught (since the test would abort before running `assert_close_gate`).

It's okay; `REQUIRE` will do the job, but it may not catch failures that might be caught if execution were allowed to continue. On the other hand if you switch these to using `CHECK`, then they aren't so good at asserting preconditions (since we *do* want to abort if the preconditions are false).

**Comment by matshou** [comment]
> I see you're using these assert_* functions both as precondition assertions (which is more appropriate for REQUIRE) and in the verification THEN clauses (where a CHECK would be more appropriate).

I can say I am still confused as to when `REQUIRE` and when `CHECK` should be used. From what you are saying `REQUIRE` should be used in `GIVEN` and `WHEN` while `CHECK` should be used in `THEN` clauses. 

Is this something that should always be the case or just a general guideline? I normally use `CHECK` as a means to provide more information in case the test fails regardless of in which clause the code may be failing at.

**Comment by PatrikLundell** [comment]
I've only looked at the description, not the code, so the comment may miss the mark, but checking for a specific sound when opening/closing doors/windows seems off. I find it perfectly reasonably to have a bead curtain make a rattling sound and a squeaky door a squeaking one. And a well oiled door might actually be silent if opened carefully.

**Comment by matshou** [comment]
> I've only looked at the description, not the code, so the comment may miss the mark, but checking for a specific sound when opening/closing doors/windows seems off. I find it perfectly reasonably to have a bead curtain make a rattling sound and a squeaky door a squeaking one. And a well oiled door might actually be silent if opened carefully.

Currently doors and windows only make a single type of sound:
```c++
sounds::sound( p, volume, sounds::sound_t::movement, _( "swish" ), true, "open_door", ter.id.str() );
```
When that is changed we should update the tests to expect different types of sound in different situations. These tests are not set in stone and should be expected to expand as the door and window behavior changes in the future. For example I am working on implementing opening doors and windows silently when crouching. For each feature component (such as doors not making a sound when carefully opened) that I write I will update the test to account for that situation.

**Comment by matshou** [comment]
@wapcaplet I've made the changes to validation blocks to use `CHECK` instead of `REQUIRE` where appropriate.

**Comment by PatrikLundell** [comment]
The problem with testing for a specific sound value is exactly that it forces contributors to not only modify the JSON descriptions (which many contributors are capable of), but also go into the code to change an overly specific test to be less restrictive (which considerably fewer contributors are able and willing to do). I believe it would be better to make the sound test just look for the specification of a sound entry, rather than hard coding exactly what the string is permitted to be. The cost of a more general test seems to be that you fail to catch some cases of a misspelled string, which I find to be a very reasonable price.

**Comment by matshou** [comment]
The door and window sound string is already hardcoded (see [`map.ccp:3998`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L3998)), it is not defined in JSON. Perhaps you are talking about making the test compatible with future changes that _might_ make the sound string configurable in JSON but I am not sure that is going to happen any time soon. 

The reason I am checking for sound string is to confirm that a specific sound is being played instead of assuming that the sound being played is door related. Also if more door and window sounds get implemented in the future we would want to ensure the logic that makes them play is actually working through the use of unit tests that compare sound strings.

**Comment by PatrikLundell** [comment]
Thanks for the clarification. Yes, if the sound is hard coded (as you point out it is), it's less of a problem to hard code the check, although it's still something that gets in the way of improving the functionality, should someone want to do that at some point.

I find it to be a massive damper on enthusiasm to have to wade through and fix a lot of tests that might be of limited value in the first place (I'm still not convinced a check for that specific sound is that useful, but realize you disagree with that assessment). There tends to be a much greater enthusiasm in writing new tests than maintaining the old ones that get broken by changes as well (most PRs fail their tests due to broken tests of things completely unrelated to the changes most of the time).

**Comment by wapcaplet** [comment]
> I've made the changes to validation blocks to use `CHECK` instead of `REQUIRE` where appropriate.

@matshou Thanks. Though on second thought, I think the tests would be more readable if they embedded the `CHECK` and `REQUIRE` expressions directly in place, without the extra indirection of the `assert_*` functions.

> I can say I am still confused as to when REQUIRE and when CHECK should be used. From what you are saying REQUIRE should be used in GIVEN and WHEN while CHECK should be used in THEN clauses.
>
> Is this something that should always be the case or just a general guideline?

It's only a guideline, and mostly a personal guideline at that, but I find that it leads to more robust and informative tests. For example, any doubts about the door sound would normally be resolved with a `REQUIRE` as a precondition:

- GIVEN a door that swishes (use a REQUIRE to ensure the door is swishy before continuing)
- WHEN I open the door (do the door-opening action, and perhaps REQUIRE that it succeeded)
- THEN it makes a swish sound (use a CHECK for the expected swish sound)

If the "GIVEN" part of this test is not true (if we somehow had a squeaky door instead), then there's no point in even running the WHEN or THEN parts - the whole test would invalid. Any false output that came as a result of the squeaky door would just be noise (no pun intended), because our premise was false. Similarly, if the action of opening the door does not succeed, then there's again no point in checking what sound it made - so REQUIRE is suitable for WHEN as well.

But as you've pointed out, the "swish" is hard-coded, and not just in one place, but *four* - twice in `open_door`, and twice again in `close_door`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1bba9b703bd5972c29c2df892688f18ea22b45e4/src/map.cpp#L3998

https://github.com/CleverRaven/Cataclysm-DDA/blob/1bba9b703bd5972c29c2df892688f18ea22b45e4/src/map.cpp#L4016

https://github.com/CleverRaven/Cataclysm-DDA/blob/1bba9b703bd5972c29c2df892688f18ea22b45e4/src/map.cpp#L4114

https://github.com/CleverRaven/Cataclysm-DDA/blob/1bba9b703bd5972c29c2df892688f18ea22b45e4/src/map.cpp#L4121

So there is no way to make such a precondition assertion about these doors - we have hard-coded behavior, with hard-coded tests. I agree with @PatrikLundell that these tests are at risk of being an annoyance/hindrance to future contributors, since they may give the impression that hard-coded "swish" sounds for all doors are necessary and desirable, when they're really not. Un-hardcoding / JSONizing or otherwise parameterizing the door sounds is certainly something we'll want in the future, so I'd like to see some hint of this (maybe a TODO comment in the test case and/or near the hard-coded "swish" lines) in case a future contributor adds squeaky doors, and wonders why we have tests expecting all doors to go "swish".

**Comment by matshou** [comment]
> Though on second thought, I think the tests would be more readable if they embedded the CHECK and REQUIRE expressions directly in place, without the extra indirection of the assert_* functions.

The reason I generally use `assert_*` functions is to reduce the amount of code that needs to be duplicated and to increase code readability. If we look at the example of opening and closing door I would argue that it indeed does increase readability.

Asserting that a door can be opened and closed can be written like this:
```c++
CHECK( here.open_door( where, indoors, false ) );
CHECK( here.ter( where ).obj().id == expect->id );
```

Or it can be written in a single line with a clear expression like this:
```c++
assert_open_gate( what, where, true, false );
```

I understand the argument that the first example makes it more clear that we are preforming `CHECK` instead of `REQUIRE` while the second example hides that behind a `bool` function argument but I don't think that information is something that needs to be obvious at a glance. When dealing with hundreds of lines of code I think it's more important to efficiently communicate what the logical block is **supposed to do** rather then what **it is doing**. This is the whole purpose of documentation - quickly relaying information that is not obvious on first sight.

However if you are insisting that we not use `assert_*` functions I will remove them without further discussion.

> I agree with @PatrikLundell that these tests are at risk of being an annoyance/hindrance to future contributors, since they may give the impression that hard-coded "swish" sounds for all doors are necessary and desirable, when they're really not.

Couldn't you say this for any feature test though? Let's say that we have an object that has 3 possible states that are hardcoded and identified by strings. And let's also say that we have unit tests that are testing if these states behave properly. In order to test the behavior of each state we have to identify them by comparing strings. We finish writing our tests and commit the code. 

If I understand correctly what you are claiming is that later down the road a new developer might come and see that we have written tests that reference the object using strings and would thus deduce that **all child classes** of object are expected to have **3 states** and never more or less. I hold this to be an illogical assumption. A developer should understand that tests are written to test the behavior of objects as they are at the moment of writing and should not treat said tests as documentation on how objects should behave from now till the end of times. When the behavior of the object is changed in any way any associated tests need to be inspected and adjusted as appropriate.

> I'd like to see some hint of this (maybe a TODO comment in the test case and/or near the hard-coded "swish" lines) in case a future contributor adds squeaky doors, and wonders why we have tests expecting all doors to go "swish"

I agree, but I think perhaps this should be better left to another PR as this one only touches on unit testing.
However if you disagree let me know and I will include the needed comment lines above `swish` strings.

**Comment by wapcaplet** [comment]
> However if you are insisting that we not use assert_* functions I will remove them without further discussion.

It's fine to use helper functions, I just don't think these are helping that much; they serve two distinct purposes (masked behind a boolean argument) and only save a couple lines of code. Again, it's a guideline, not a rule.

> A developer should understand that tests are written to test the behavior of objects as they are at the moment of writing and should not treat said tests as documentation on how objects should behave from now till the end of times.

Right, I just want to make sure the test case itself has some caveat, or provides some context, in the form of a comment or TODO or some other hint, that "the window should make a swish sound" is contingent on this known-to-be-hardcoded behavior of `open_door` and `close_door`.

It is common for CDDA players (and contributors) to have doubt about what is the *intended* behavior of the game, versus what just *happens* to be the behavior because nobody did anything to fix it. It is not uncommon for players to be angry about broken game features because they believe it was designed or intended to be that way.

This hard-coded "swish" for all kinds of windows and doors is certainly not intended, so I think it's important for the test case to be clear that it's not an unqualified expectation, in the same way that "the door should be able to open and close" clearly is.

**Comment by matshou** [comment]
> This hard-coded "swish" for all kinds of windows and doors is certainly not intended, so I think it's important for the test case to be clear that it's not an unqualified expectation, in the same way that "the door should be able to open and close" is.

I was not aware of this. Are you saying that the sound being hardcoded is not intended or that the sound itself is not intended? Most probably you mean the former in which case I will write TODO notes just like you recommended explaining that the tests should be updated once the door and window sounds are defined in JSON files.

**Comment by wapcaplet** [comment]
> I was not aware of this. Are you saying that the sound being hardcoded is not intended or that the sound itself is not intended?

Neither; I mean the idea that "all doors and windows should go *swish*" is not intended.

**Comment by kevingranade** [comment]
> The reason I generally use assert_* functions is to reduce the amount of code that needs to be duplicated and to increase code readability.

They don't meet either of these goals, remove them.

**Comment by matshou** [comment]
> They don't meet either of these goals, remove them.

Okay I'll do that. Should I avoid those types of function in general when writing tests?

**Comment by kevingranade** [comment]
If they're following this pattern, yes.
Meaningful helpers are ones that centralize a significant amount of logic, not just a few lines.

**Pull request merged**
