### PR TITLE
Move shirts to skin layer and hoodies to normal layer

### PR DESCRIPTION
**Pull request by Jarewill**
#### Summary
Balance "Moved t-shirts and hoodies down a layer"

#### Purpose of change
As proposed in #52514 I moved various t-shirts to the skin layer, while hoodies were moved to the normal layer.
In the description of the hoodie it states that it's "A sweatshirt with a hood and a \"kangaroo pocket\" in the front for storage."
However unlike the sweatshirt, it had lower encumbrance and occupied the outer layer.
To make the description reflect on the item, I moved it to the normal layer and adjusted the encumbrance on the sweatshirt (and sweater, seeing the wool hoodie) to match the hoodie.
Also made t-shirts cover the shoulders and upper arms to differentiate them from tank tops.

#### Describe the solution
Moved any t-shirts with thickness 0.1 to the skintight layer. (With a few exceptions, such as buttoned shirts)
Moved hoodies to the normal layer to match sweatshirts.
Also made t-shirt-based items also cover the shoulders and upper arms and made the hoodie steel moddable to fit the sweatshirt.

#### Describe alternatives you've considered
Keeping as is.
Not making t-shirts cover arms in any way.

#### Testing
- Ensured the game loads and checked various items.

#### Additional context
I am unsure if my choices were correct here, so I am posting this as a draft for now.
I would highly appreciate any feedback on this.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
Thanks for doing this it looks good to me 👍 you can lint the file by copy pasting it in this site https://dev.narc.ro/cataclysm/format.html and then copy pasting the result back to the file.

>Making t-shirts also cover the upper arms. (Looking at images, they seem to also cover that part in like 50%?)

If you want to do this (don't feel obligated) thigh-high boots have an example of how to do it correctly.
```json
"armor": [
      { "encumbrance": 20, "coverage": 100, "covers": [ "foot_l", "foot_r" ] },
      {
        "covers": [ "leg_l", "leg_r" ],
        "specifically_covers": [ "leg_lower_l", "leg_lower_r", "leg_knee_l", "leg_knee_r" ],
        "coverage": 100,
        "encumbrance": 20
      },
      {
        "encumbrance": 0,
        "coverage": 50,
        "covers": [ "leg_r", "leg_l" ],
        "specifically_covers": [ "leg_upper_l", "leg_upper_r" ]
      }
    ]
```
So they have the entry for legs that has the encumbrance and 100 coverage for the shins and knees, then an additional entry for the thighs with 50% coverage. 

So you could do a similar thing (fill the X with whatever you want the encumbrance to be, seems for most these it's 0 so the entry could be removed entirely):
```json
"armor": [
      {
        "covers": [ "arm_l", "arm_r" ],
        "specifically_covers": [ "arm_shoulder_l", "arm_shoulder_r" ],
        "coverage": 100,
        "encumbrance": X
      },
      {
        "//": "encumbrance already handled in the above entry",
        "encumbrance": 0
        "covers": [ "arm_l", "arm_r" ],
        "specifically_covers": [ "arm_upper_l", "arm_upper_r" ],
        "coverage": 50,
      }
    ]
```

**Comment by Jarewill** [comment]
Alright, I linted the code and updated the coverages of shirts to also cover the upper arms.
Also I changes the material thickness of the flag_shirt to 0.1 to match the other t-shirts and threw the long-sleeved shirt back on the normal layer.
I was unsure about if the long-sleeved shirt should be skin or normal layer, so I will keep it in the normal layer for now.

**Review by bombasticSlacks — APPROVED** [review]

**Comment by PatrikLundell** [comment]
Doesn't this means female characters wearing a bra will be encumbrance penalized for wearing a t-shirt "on top" of it?

**Comment by Jarewill** [comment]
That it sadly does.
But the same thing also applied to wearing a tank top with a bra before.

What makes the tank top different from a t-shirt to warrant a different layer?
Both have the same materials and thickness and are described very similarly.
Tank top being a "sleeveless cotton shirt" while a t-shirt is a "short-sleeved cotton shirt".
Is lack of sleeves enough to warrant it being on the skin layer?

I also found out there's an item called the "undershirt" that is on the skin layer.
What should be done about that one?
Searching for images of it gave me either a tank top or a t-shirt, so I don't know if it should also cover the arms or not.

**Comment by PatrikLundell** [comment]
The layer system that's been decided upon introduces a number of limitations that do not make real world sense. Either you invent a new, better system (and convince the powers that be to adopt it), or try to reduce the bad interactions you get from the current system as much as possible.
In my view this means leaving the "skin" layer for "real" underwear almost exclusively. I've never worn longjohns without underwear under them, for instance. To me, this means tank tops would have to go on the normal layer. An undershirt would have to be on the skin layer with the current system, or it wouldn't be "under". As far as I understand, undershirts can be netted for use in warmer climates, or something ranging from a tank top to a t-shirt to a thin long sleeved affair for use in cold climates. Given that they're intended to be used under additional clothing they tend not to have anything elaborate printed on them (but can be colored).
It can be noted that underwear doesn't really do anything in the game, so you can replace them for warmer items that would, in the real world, be worn on top of them if you need to fight cold in the winter.

**Comment by bombasticSlacks** [comment]
> I also found out there's an item called the "undershirt" that is on the skin layer.
What should be done about that one?
Searching for images of it gave me either a tank top or a t-shirt, so I don't know if it should also cover the arms or not.

You could just leave it and someone in a seperate PR could remove the item migrating it to tank top or t-shirt. 
Otherwise it could be themed as more breathable/ less warm for sleeping in. 

As for bras, I don't think they are really the most important thing to worry about. Lots of tanktops / camisoles have a "boob shelf" as my partner calls it that functions well enough as a bra and I'm sure plenty of hard armor would give the back support more endowed people desire from a bra. Also lots of game starts already begin with something conflicting with their bra. 

Also the bra is a great example of the point of the layer system. Yes people wear bras with t-shirts. It does make the t-shirt more uncomfortable. Not a lot more uncomfortable, in this case 2 torso encumbrance worth.

**Comment by Jarewill** [comment]
> You could just leave it and someone in a seperate PR could remove the item migrating it to tank top or t-shirt. Otherwise it could be themed as more breathable/ less warm for sleeping in.

Alright, I will leave it for now.

> EDIT: If you really wanted to go overboard on handling issues you could introduce fitted / baggy versions of the clothing you've modified to skin layer (at least the generic ones like t-shirt and tanktop). Baggy versions stay on normal, fitted move to skin tight.

I think adding new versions of those items would be better off in a separate PR, if this one even gets merged.

Though I am still not fully sure on the long-sleeved shirt.
It's description and properties make it seem like it's just a t-shirt with longer sleeves and it can also be turned into a t-shirt.
I am not completely sure if I should also put it on the skin layer and lower it's thickness to match the t-shirt. (From 0.2 to 0.1)

**Comment by bombasticSlacks** [comment]
>Though I am still not fully sure on the long-sleeved shirt.
It's description and properties make it seem like it's just a t-shirt with longer sleeves and it can also be turned into a t-shirt.
I am not completely sure if I should also put it on the skin layer and lower it's thickness to match the t-shirt. (From 0.2 to 0.1)

long underwear top has the same thickness 
https://nornagon.github.io/cdda-guide/#/item/long_undertop

So theres no reason to reduce thickness if dropping it to skintight.

**Comment by Jarewill** [comment]
Oh, okay.
However the long-sleeved shirt that's 0.2 thick can still be turned into a t-shirt that's 0.1 thick.
They also have the same warmth values, which leads me to believe they should have the same thickness.

**Comment by Jarewill** [comment]
Seeing as the latest commit fails the encumbrance test, what should I do about it?
My intent with removing encumbrance from the long-sleeved shirt to make it fit more with the t-shirt. (Skin layer, 5 warmth, 0.1 thickness)
Should I revert that change?

**Comment by bombasticSlacks** [comment]
> Seeing as the latest commit fails the encumbrance test, what should I do about it? My intent with removing encumbrance from the long-sleeved shirt to make it fit more with the t-shirt. (Skin layer, 5 warmth, 0.1 thickness) Should I revert that change?

It's used in a bunch of tests and probably shouldn't. It would be hard to fix it here with change suggestions so I'll just PR a separate change for the failing tests and once that's in your stuff will pass.

**Comment by Shibimon** [comment]
What about giving "real" underwear a new flag that exempt one instance of it giving encumbrance penalty no matter what?
That will fix wearing lower underwear with skintight pants, and kinds of make sense as this kind of clothes tend to be very thin but still will give pentalty if you use 2 of it or make other combinations.

**Comment by Jarewill** [comment]
Adding flags and custom C++ logic (which I assume will be required for that) is currently beyond my ability.
While I could maybe figure out how to exactly do that, my attempts at compiling the code myself have not been fruitful and I don't feel comfortable updating code with no way to check if it works.
Also, I feel this will be too close to adding a new layer, which is something the devs want to avoid.
Someone more knowledgable could do this IF this PR even gets merged.

Though about that.
If it does end up not being merged because of the layer changes, I could edit those out.
I feel like adding sleeves to the t-shirts and some consistency fixes with t-shirt variants and hoodie/sweatshirt could be useful.

**Comment by bombasticSlacks** [comment]
Don't worry too much about it not getting merged, it seems valid to me. Just need to wait for #55457 so your stuff will pass. Then it will probably get merged in with the next big batch of PRs.

**Comment by bombasticSlacks** [comment]
alright so to get this to pass tests you are gonna need to do a git-rebase or merge the changes from master.

in whatever you are using for git you can do on the command line 

``` git pull --ff-only upstream master``` 

and then push.

Or do a rebase https://docs.github.com/en/get-started/using-git/about-git-rebase

**Comment by Jarewill** [comment]
Alright, I merged the changes and it looks to be okay.

**Pull request merged**
