### PR TITLE
Set ammo consumption rate for diffrent actions of the same item

### LINKED ISSUE #50157: Shotgun bug or  unintended behavior
### Describe the bug

Stockpiling loot i found that a fresh spawned from zombie a "5-round shotgun+1 (0/5 shot)" having a shoulder strap gave me the blue line in the image below while trying to remove the shoulder strap mod.
Loading the gun with ammo allowed me to remove the strap.

### Steps To Reproduce

1. Get a 5-round shotgun with strap from loot drops. (don't know if this happens on other similar weapons or a debug spawned item)
2. Make sure it has no ammo.
3. Trying to remove the strap by (a)ctivating it will prompt the gun having no charges.

### Expected behavior

Shoulder straps removing not dependant of gun charges.

### Screenshots

imagen

### Versions and configuration

Last version bb34304 (tiles) build 2021-07-23-0803 (4 hours ago) (laucher info)

### Additional context

_No response_

### LINKED ISSUE #50220: Guns and gun mods need to be loaded in order to be attached/detached
### Describe the bug

Attempting to attach mods to guns or detach mods from guns requires them to have ammo loaded. In short, whatever needs to be 'a'ctivated to attach or detach mods needs ammo loaded in it.

### Steps To Reproduce

1. Have guns and gun mods available.
2. Attempt to attach gun mod to gun by using the 'a'tivate menu.
2.1 Attempt to attach gun mod to gun by using the context menu from 'i'nventory -> selecting gun mod -> 'a'ctivate. The activate option will not be greyed out, but when activated you will be prompted that it needs at least one charge.

or

1. Have an unloaded gun with an attached gun mod.
2. Attempt to detach gun mod from gun by selecting it inside the 'a'ctivate menu.
3. Be prompted that gun needs at least one charge.

or

1. Have a gun mod that can hold ammo itself. Current example will use unloaded M203/M320.
2. Attempt to attach empty gun mod to compatible gun.
3. Be prompted that gun mod needs at least one charge.
4. Reload gun mod.
5. Successfully attach loaded gun mod to weapon.
6. This applies to attempting to detach gun mod as well.

or

1. Have a bow with compatible mods for it.
2. Attempt to attach mod to bow.
3. Be prompted that bow needs at least one charge.
4. This deviates a bit from the rest, because you're activating the gun mod but having the weapon be empty.
5. Be unable to attach or detach any mods from bows, because to my knowledge bows don't actually hold any ammo within themselves.

### Expected behavior

Be able to attach/detach gun mods to and from guns without being required to have ammo loaded in them. As far as I'm aware it should be the exact opposite.

### Screenshots

weeniescreenie

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ebb21f3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Safe Portable Autodoc [safe_portable_autodoc]
]

### Additional context

This started happening fairly recently, perhaps no more than 5 days ago. I update my game daily to the latest unstable version, so whatever update is causing this cannot be that far back. I could've reported this sooner but at first I assumed it was intended, until I ran into the inability to modify bows at all.
I did scroll through the issue tracker and didn't see any other reports about this, but I'll apologize in advance if this is just user error.
I assume none of the mods I use should affect weapons in any way, hence I didn't do any testing without them.

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary
Bugfixes "Ignore ammo check for actions not consuming ammo"

#### Purpose of change

Fixes #50220 
Fixes #50157

#### Describe the solution

~~Quick fix by modifiing several if-conditions so that attach/detach actions bypass the check.~~

~~Actually I don't like this solution myself, since it may be more non-ammo-consuming actions of tools/guns in the future. (For example firearm repair kit. The kit needs battery to be activated regardless of the actual action)~~

New approach below.

#### Describe alternatives you've considered

Add more informations to the corresponding class indicate whether an action needs to consume ammo.

#### Testing

The player is able to activate empty guns and gun mods.

#### Additional context

Unbenannt4

image

### CODE REVIEW

**Comment by Menschheit** [comment]
Reversed my original commit.

I defined a new set in the class itype, which corresponds action ids with ammo consumption rates.

It is now possible to define for each action a different ammo consumption rate in json ( only for items defined with actions, not yet implemented for quality levels).

For now this new attribute is only used for checking remaining ammos :  Added an alternative version of  `item::ammo_sufficient()`, which receives the String id of an action as parameter.

It is also possible to implement actual ammo consumption rate in the corresponding use functions.

Test: the player can activate empty firearm repair kit for cutting metal, saw down barrel etc from `a`ctivation menu,  but still needs battery to repair a gun

**Comment by actual-nh** [comment]
Ping: @Salty-Panda, any thoughts?

**Comment by Salty-Panda** [comment]
Sounds interesting, do you plan to support json-defined actions, like various `transform`? Because right now as far I can see you take the value from charges_per_use defined in item.

Could you test a case:
-Edit flaslhlight or any other item that defines use-action: transform and set 
charges_per_use in normal item to 0 and charges_per_use in _on item to 1
and check how would it work?

I have a hunch that it would result in enabling item costing a charge and disabling it being free.

**Comment by actual-nh** [comment]
Is #50372 related?

**Comment by Menschheit** [comment]
json-defined actions are already supported, added clean up codes for copy-from issues.

Just need to get the scale number in `iuse_transform::use` and replace `charges_to_use()` by `charges_to_use() * scale` to make it work.

Animation

**Comment by Menschheit** [comment]
> Is #50372 related?

No I don't think so.

**Comment by actual-nh** [comment]
Fixes #50521 can also be added.

**Comment by actual-nh** [comment]
Fixes #50956; please resolve conflicts.

**Comment by Menschheit** [comment]
I hope I didn't mess up. `git rebase` is driving me mad.
I think git is not amateur friendly :cry:

**Comment by kwl01skz** [comment]
This problem has not been completely solved.

Now using [Fire repair kit] still needs to consume batteries,

Although no consumption (- 0) is displayed before use, it actually consumes (- 100)

**Comment by kwl01skz** [comment]
Now, when ammunition exists in some tools, ammunition will be consumed preferentially. Even if the action of not consuming ammunition is performed.
or example, when cutting metal with a Fire repair kit, it displays (- 0). In fact (- 100). If it is less than 100, it will be exhausted, but 0 can continue to cut metal without consumption.

**Pull request merged**
