### PR TITLE
re-include (accidental) removal of 'game.h' fixes #12728

### LINKED ISSUE #12728: Tiles / SDL not building anymore.
Went from bc3d389 -> d53f969

Failed with:
```
src/sdltiles.cpp: In function ‘void curses_drawwindow(WINDOW*)’:
src/sdltiles.cpp:663:9: error: ‘g’ was not declared in this scope
     if (g && win == g->w_terrain && use_tiles) {
         ^
src/sdltiles.cpp:663:37: error: ‘use_tiles’ was not declared in this scope
     if (g && win == g->w_terrain && use_tiles) {
                                     ^
src/sdltiles.cpp: In member function ‘bool Font::draw_window(WINDOW*, int, int)’:
src/sdltiles.cpp:775:25: error: ‘g’ was not declared in this scope
             if ( win == g->w_terrain || win == g->w_minimap || win == g->w_HP || win == g->w_status ||
                         ^
src/sdltiles.cpp: In function ‘WINDOW* curses_init()’:
src/sdltiles.cpp:1448:9: error: ‘use_tiles’ was not declared in this scope
         use_tiles = false;
         ^
src/sdltiles.cpp: In function ‘void rescale_tileset(int)’:
src/sdltiles.cpp:1658:9: error: ‘g’ was not declared in this scope
         g->init_ui();
         ^
src/sdltiles.cpp: In member function ‘bool input_context::get_coordinates(WINDOW*, int&, int&)’:
src/sdltiles.cpp:1669:23: error: ‘g’ was not declared in this scope
         capture_win = g->w_terrain;
                       ^
src/sdltiles.cpp:1678:9: error: ‘use_tiles’ was not declared in this scope
     if (use_tiles && capture_win == g->w_terrain) {
         ^
src/sdltiles.cpp:1678:37: error: ‘g’ was not declared in this scope
     if (use_tiles && capture_win == g->w_terrain) {
                                     ^
src/sdltiles.cpp:1710:13: error: ‘g’ was not declared in this scope
         x = g->ter_view_x - ((capture_win->width / 2) - selected_column);
             ^
src/sdltiles.cpp:1718:13: error: ‘g’ was not declared in this scope
         x = g->ter_view_x - ((capture_win->width / 2) - selected_column);
             ^
src/sdltiles.cpp: In function ‘int map_font_width()’:
src/sdltiles.cpp:1908:9: error: ‘use_tiles’ was not declared in this scope
     if (use_tiles && tilecontext != NULL) {
         ^
src/sdltiles.cpp: In function ‘int map_font_height()’:
src/sdltiles.cpp:1917:9: error: ‘use_tiles’ was not declared in this scope
     if (use_tiles && tilecontext != NULL) {
         ^
src/sdltiles.cpp: In function ‘bool is_draw_tiles_mode()’:
src/sdltiles.cpp:1948:12: error: ‘use_tiles’ was not declared in this scope
     return use_tiles;
            ^
Makefile:454: recipe for target 'obj/tiles/sdltiles.o' failed
make: *** [obj/tiles/sdltiles.o] Error 1
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22629433-tiles-sdl-not-building-anymore?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alextes**
Probably best to look at my commit real quick. First time I'm contributing to a big repo.
fixes #12728

### CODE REVIEW

**Comment by slyscorpion** [comment]
Can confirm this works. I manually edited the cata_tiles.h file and added #include game,h and everything compiled :)

**Comment by BevapDin** [comment]
First, I apologize for that bug. Second, game.h should be included in sdltiles.cpp, because that's where it's needed. cata_tiles.h does not need it. All thee error messages in #12728 originate in sdltiles.cpp.

**Comment by AlexTes** [comment]
I see. Your cleanup was justified but sdltiles is missing the include. I simply checked the diff's and made things work again. Like I said, I'm not familiar with the source really. Want me to make a new PR or do you have this covered?

**Comment by BevapDin** [comment]
No problem in doing it here.

**Comment by drbig** [comment]
So I guess I don't need to PR a buildfix for this?

**Comment by AlexTes** [comment]
Aww, I didn't know you could add to an open PR. Already removed my local branch and only seem to be able to get it back in a detached state. Therefore unable to push. Opened a new PR. Hope thats okay. Sorry for the mess.

**Pull request closed without merging**
