### PR TITLE
Removes the swollen wretch to the obsolete file.

### PR DESCRIPTION
**Pull request by DoctorBoomstick**
#### Summary
None

#### Purpose of change
The Swollen wretch, an evolved child zombie added by me a few weeks back, was in retrospect one of the most irrelevantly useless and ridiculous enemies in the game. As the Murder Unicorn pointed out in his last experimental cataclysm video, it was a pretty terrible implementation, born out of a joke which should have just stayed as a joke. The concept of a flying zombie remains one that is potentially interesting to explore, with such an enemy possibly providing some different challenge for the player. Unfortunately, the wretch was a good concept added in one of the most ludicrous ways possible, and it more than likely made the game worse for it.

#### Describe the solution
the enemy, along with its fungal variant and the also added fungal raptor, has been retired to the obsolete file, with its spawn entries removed.

#### Describe alternatives you've considered
Simply wiping the zombie from the game entirely, or shifting it over to a mod like Crazy  Cataclysm. In the case of the former, I opted not to remove it completely as it may still be of use to another potential contributor with better ideas than me, whilst in the case of the latter, I simply don’t know enough over the purpose behind the mod to determine if such an enemy would fit well within it.

#### Testing
I simply moved some JSON around and nuked a single line. It shouldn’t have done anything significant.

#### Additional context
In the closing stages of his video, the Murder Unicorn briefly touched upon this enemy and whilst not strictly talking in depth about it, he did mention his opinion as stated in the sections above. I was already having reservations over this enemy, and this served as a nudge to take some action over the matter.
https://www.youtube.com/watch?v=P-HTXXq6e3A&ab_channel=TheMurderUnicorn

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
Why not just remove the flesh raptors and have it burst with gas? I think this enemy is a novel idea and it would be a fun monster to sprite as well. 

Normally we try to avoid walking things all the way back, but instead tweaking them until we get it right.

**Comment by DoctorBoomstick** [comment]
I went to look at the discord conversations that the Murder Unicorn had mentioned being rebuked on with regards to this matter, just to check out what they said about this, and I’ve got to agree with the points raised. It simply isn’t a matter that this enemy is impossible on a biological level, as, well, gasoline and headless zombies anybody, but they’re just not possible on a pure physics standpoint. Now, perhaps it would make more sense if I was to rework the enemy to a portal storm monster, but then it would just lose its justification for existing in the first place. Honestly, my main beef at this point is that there simply isn’t a definition for what Zs can or cannot be. They clearly don’t need to be grounded in reality, thanks to the existence of the types of enemies already mentioned, but unrealistic zombies get gunned down. I do suppose that this guy was probably pushing the envelope as to what creatures can exist, but we’re literally dealing with a being who can reformulate new monsters out of body parts, and literally play doe human meat suits into what ever it’s in the mood for. So, I don’t know. Part of me, the same part who created this dude in the first place, wants to be like, “ha ha, big balloon zombie go boom,” whilst the other half is taking a step back and considering this creature from a realism perspective. I will say that removing the Flesh raptors would probably be a fairly decent upgrade, but it still doesn’t answer the question over how the hell can this thing exist in the first place. Oh, and just as a side note, my rational for adding the raptors was working from the idea that most of the body mass inside of the zombie, bones and organs, got converted into the raptors, and that given that they naturally fly, they could sort of act as an internal mechanism providing directional force from within the zombie which lets it move at all.

**Comment by Zireael07** [comment]
why not change the justification then? I think it's a cool monster that would work as a portal storm thing!!!

**Comment by I-am-Erk** [comment]
Yes, I second/third that we're not going to approve a straight obsoletion. If you'd like to rework the balance that's fine, but the core concept of the monster isn't a problem and having received critique isn't a sufficient justification to delete it. If you'd like to turn this into a rebalance pr I'll reopen it.

**Comment by DoctorBoomstick** [comment]
Fair points everybody, and sorry for wasting your folk’s’ collective time on this. I’ll try in the future to avoid making these sort of poorly thought through decisions and actually tackle the issue in a productive manner. I think rebalancing it to a portal storm type monster and away from a zombie would be the way forwards with this creature, and I’ll probably throw this into draft until I get something working. My current school of thought would be either turning it into a floating chrysalis type organism, or perhaps a nether creature which would have infested a human host. Either way, this probably aint going to be staying as a zombie.

**Pull request closed without merging**
