### PR TITLE
Unbind Abandon character

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Interface "Remove abandon character default keybind, and set `q` to look at sky"

remove default keybind for abandon character and give `q` to look at sky, knowing the weather in more detail is useful imo.
Removed default keybind from abandon character due to it being unnecessary, leaving `Q` for perhaps something more useful later on?

#### Purpose of change
i don't think we need a dedicated button for abandonment (sorry old timers, i know, this is blasphemous)
look at sky is a useful feature not many know (from my knowledge at least) setting it to q allows it to be more easily discovered.

#### Describe the solution
simple json edit, assuming i did it correctly. rebind the keybinds in raw/keybinds.json

#### Testing
opened the game with the changes, and by default abandonment has no keybind, while look at sky is set at q.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I'd leave `Q` as a keybind for abandoning character.

**Comment by Devengel** [comment]
i think it is unnecessary for abandon character to have a default keybind. if someone really wants a hot key to quickly end their characters, they can assign one themselves. but i doubt it is something many people readily want it to be default.

**Comment by moxian** [comment]
On at least a couple of occasions i have found myself fat-fingering and *almost* accidentally abandoning the character. Luckily neither of those were fatal, but they were all scary nevertheless. I think removal of the easy to access suicide button is a good idea. It's not something you do often enough to need a dedicated keybind.
Without the keybind you can still go `Enter` -> actions -> abandon the character to achieve the same goal.

**Comment by Rimplestilt** [comment]
Suicide has no reason for a keybinding and instead should be an option accessible from the ESC menu, with a possible tucked away default key, like a function key.

There are more useful keybinds for "Q" imo, but as various ppl have various views on what is useful, i submit "q" and "Q" be left unbound by default for now. (for example: useful in spellcasting in magiclysm, or setting q and Q to cycle run speed up and down once, or bringing up character sheet, the list goes on)

Especially with the possibility that there is more drastic rework in both menu design and ui, and also keybindings, with possible entirely new keybinding sets (for example once more designed more modern keyboard usage with an emphasis on WASD or arrow key style gameplay)

**Comment by Golfavel** [comment]
This would close #59679.

**Comment by Devengel** [comment]
sky is already W on overmap it seems, Bound save and quit to Q, and quicksave to S. as per #59679 recommendations.

**Comment by Fris0uman** [comment]
Why also change S? just binding Q to `Q`uick save is a way more straight forward solution

**Comment by Fris0uman** [comment]
The PR is about unbiding the suicide key for safety, there is an unbound action that start with a Q which is Quick save, it doesn't make sense to alter another key that is just working fine.

**Comment by Devengel** [comment]
failure is unrelated

**Comment by kevingranade** [comment]
Do one thing at a time please.

**Comment by Devengel** [comment]
alright, i'll leave the quicksave unchanged then.

**Pull request merged**
