### PR TITLE
Add new Scenario - Anomalous Materials

### PR DESCRIPTION
**Pull request by HotCupOfJava**
#### Summary

SUMMARY: Mods "Aftershock: Create a new scenario, Anomalous Materials"

#### Purpose of change

To create a new scenario called Anomalous Materials which locks the Planar Frontiersman/woman in a lab finale in order to emulate the starting scenario from Half Life 1.

#### Describe the solution

It copies all other lab solutions while locking the player to the lab finale and to the planar frontiersman

#### Describe alternatives you've considered

Add the planar frontiersman to the Lab Staff start
#### Testing

I spawned into the game using the random location spawn several times to make sure that the frontiersman/woman will spawn in an ice/normal lab finale

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
You're making changes in your _master_ branch. You should create a separate branch for your changes.

**Comment by John-Candlebury** [comment]
You'll still have to format your json changes. Either using the [Web formatting tool](http://dev.narc.ro/cataclysm/format.html) (you have to paste the whole file to get the proper format) or ideally by running it through desktop using MSYS2.

Otherwise this seems good.

**Comment by esotericist** [comment]
@John-Candlebury just to double-check, this is ready to be merged in your eyes?

**Comment by John-Candlebury** [comment]
Yes it is!

**Pull request merged**
