### PR TITLE
Improve laser dot override for safemode and nerf tank drone speed.

### PR DESCRIPTION
**Pull request by kevingranade**
I think this is going to make tank drones pretty reasonable to deal with.  The mandatory safe mode message from the laser dots works as expected now, and I nerfed tank drone speed so that once you get the safe mode message, you should usually be able to get away.

### CODE REVIEW

**Comment by Lain-** [comment]
Speed from 100 to 75 is a pretty big nerf IMHO. May I suggest something like 80 ~ 85?

**Comment by Rivet-the-Zombie** [comment]
Looks like this is blocked by the string freeze.

**Comment by kevingranade** [comment]
Since the tank bot is pretty much going to kill you outright if it does shoot you, I think having it be a bit slow is pretty reasonable.  I think I can leave the strings as is and still have the behavior changes, and I'll make a separate change to fix the strings post-0.C

**Comment by kevingranade** [comment]
I adjusted the commit to only use pre-existing translatable strings, it's not as clear as it could be, but that's better than leaving in the old behavior.  Thanks for caching that.

**Comment by KA101** [comment]
Uh, this left me stuck in safemode move-lock.  Including after I'd debug-killed the tank drone.  :-(

**Comment by kevingranade** [comment]
Patched in a cancellation for the laser-lock when you toggle safe mode as well, thanks for catching that.

**Comment by KA101** [comment]
Frickin' time zones.  I'll recheck this later today/tomorrow if nobody beats me to it.

**Pull request merged**
