### PR TITLE
update mutations.json

### PR DESCRIPTION
**Pull request by wingbrother**
#### Summary
 ```SUMMARY: Bugfixes "change bad and good memory traits to match the new skill rust system"```

#### Describe the solution
In new skill rust system increasing skillrust rate increase time between skill rusting. Old good memory traits decrease time (accelerate skillrusting instead of slowing down) in new system. Inversing skill_rust_multiplier between FORGETFUL and GOODMEMORY traits.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
`GOODMEMORY` trait had multiplier of `0.66` and `FORGETFUL` trait had multiplier of `1.33` for `skill_rust_multiplier` both before and after it was jsonized in #32337. I don't remember anything changed regarding skill rust system recently that need to swap multiplier values between traits.

**Comment by wingbrother** [comment]
in 
bool SkillLevel::rust( bool charged_bio_mem, int character_rate )
{
    const time_duration delta = calendar::turn - _lastPracticed;
    const float char_rate = character_rate / 100.0;
    const time_duration skill_rate = rustRate( _level );
    if( to_turns<int>( skill_rate ) * char_rate <= 0 || delta <= 0_turns ||
        **delta % ( skill_rate * char_rate )** != 0_turns ) {
        return false;
    }

int Character::rust_rate() const
{
    if( get_option<std::string>( "SKILL_RUST" ) == "off" ) {
        return 0;
    }

    // Stat window shows stat effects on based on current stat
    int intel = get_int();
    /** @EFFECT_INT reduces skill rust by 10% per level above 8 */
    int ret = ( ( get_option<std::string>( "SKILL_RUST" ) == "vanilla" ||
                  get_option<std::string>( "SKILL_RUST" ) == "capped" ) ? 100 : 100 + 10 * ( intel - 8 ) );

    **ret *= mutation_value( "skill_rust_multiplier" );**

    if( ret < 0 ) {
        ret = 0;
    }

    return ret;
}

I highlighted those parts due to which skill ratе need swaping

**Comment by ZhilkinSerg** [comment]
That is not something new then - it was always `%` operator at least back to `0.A`.

```C++
bool SkillLevel::rust(const calendar& turn, bool charged_bio_mem)
{
    if (_level > 0 && turn > _lastPracticed &&
       (turn - _lastPracticed) % rustRate(_level) == 0)
```

**Comment by wingbrother** [comment]
earlier skill_rust_multiplier used to change the probability of a decrease in skills; now it affects the time between skill losses.

**Comment by Fris0uman** [comment]
Yep this https://github.com/CleverRaven/Cataclysm-DDA/pull/37281 changed what the rate means, sorry for not catching the mutation thing.

**Pull request merged**
