### PR TITLE
Meat recipe fixes

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Bugfixes "Fixed several things with meat dish recipes"```

#### Purpose of change
- Cooked scrap of meat doesn't inherit the Cooking 1 requirement from Cooked meat via copy-from.
- Several meat dishes can only be cooked using "chunk of meat" not the rest of the meat materials.

#### Describe the solution
- Adding the Cooking 1 requirement to the scrap of meat manually.
- Adding the "meat_red" (chunk of meat, rehydrated meat, canned meat, scrap of meat) cooking component group to meat dishes where it is missing and makes sense.
- Adding scrap of meat component where the above is not really applicable.

### CODE REVIEW

**Comment by kevingranade** [comment]
```RecipeID: cheeseburger, Lower Bound: 380.438141, Average: 1142.500000, Upper Bound: 1139.561890


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v2.9.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
recipe_permutations
-------------------------------------------------------------------------------
comestible_tests.cpp:109
...............................................................................

comestible_tests.cpp:140: FAILED:
  CHECK( mystats.calories.avg() < upper_bound )
with expansion:
  1142.5 < 1139.56189f
```
Changes pushed this test out of bounds, try fiddling with the cheeseburger recipe a bit.

**Comment by RarkGrames** [comment]
> Changes pushed this test out of bounds, try fiddling with the cheeseburger recipe a bit.

I checked it out, and my guess is that the rehydrated meat and canned meat push the burger over the limit. Both of them are copies of cooked meat, which gains calories during cooking (chunk of meat - 302 kcal, cooked meat - 402 kcal). The scrap of meat also has this (30 - 51 kcal).
I don't know if the kcal gain is intended, but matching the cooked meat values to the raw values would be one solution.

**Comment by RarkGrames** [comment]
After some testing it turns out that the crafted cheeseburger will be in the 900-1200 calories range instead of 380, regardless of components used. So adding the NUTRIENT_OVERRIDE to it solves both problems.

**Comment by kevingranade** [comment]
Nutrient override is a last resort that is not appropriate here. If the base nutrition ofvthe item is correct, match the ingredients to the item instead of forcing some of them to evaporate (which is what nutrient override does in this case).

**Comment by RarkGrames** [comment]
That makes sense.
In one variant of the recipe there was 200 g cheese spreads (one portion) going into the burger. I changed the cheese spread to match the two other kind of cheese, 30 g per portion. This way the end product will be in the 370-560 calories range.

**Pull request merged**
