### PR TITLE
Removed sickle/sythe requirement to cut grass.

### PR DESCRIPTION
**Pull request by JonahDes**
```SUMMARY: Balance "Removes the need for tools to remove simple grass objects."```
#### Summary

There are so many ways to remove long grass it was more effective to remove it entirely. Long grass is even able to be removed with one's hands in reality. Time was slightly increased in exchange for being accessible at any point.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Then it should be renamed from `Cut Grass` to something like `Remove Grass`.

**Comment by JonahDes** [comment]
> Then it should be renamed from `Cut Grass` to something like `Remove Grass`.

In this case it doesn't actually remove the grass entirely, I believe? Either way, it was prohibiting a user from removing some foilage that they would have otherwise had to use gimmicky things to remove it with (fire).

This just turns the grass into another grass type? I believe.

**Comment by SourSlime** [comment]
Perhaps call it Shorten Grass instead?

**Comment by kevingranade** [comment]
The rationale doesn't make any sense, the resulting construction doesn't make any sense.
You need a tool to cut grass, that's how it works.
If the balance of options is out of whack, bring something up about it instead of making random adjustments.

**Comment by JonahDes** [comment]
> The rationale doesn't make any sense, the resulting construction doesn't make any sense.
> You need a tool to cut grass, that's how it works.
> If the balance of options is out of whack, bring something up about it instead of making random adjustments.

Go to any field.
Hold grass with one hand.
Pull grass to make even 'cut'.

**Comment by ZhilkinSerg** [comment]
... and spend 10x time compared to using scythe or sickle
... and cut your bare hands

**Comment by Rail-Runner** [comment]
Well, personally I did use my bare hands to pull out a bunch of grass at some point, it's not as bad as it seems. It seems doable to do the same on a large scale (to clear a tile from grass) if you really want to, but I think it'd take a hour per tile or so. Should probably be an option, given that scythes and sickles aren't really that common.

**Comment by paulenka-aleh** [comment]
Removing grass with bare hands twice a year in a cemetery. It's not like weeds in the garden. It doesn't want to break, it can't be easily pulled out (if it can be at all), some plants strike back with thorns, cut hands and some plants cause blisters unless you're wearing gloves. Even a Garden pruner helps much. The tool does make a difference.

I also would like to have a way to remove grass without sophisticated tools unobtainable easily innawoods (and without fire) but surely a lawnmowers would be the fastest, scythes and sickles a best otherwise, I would use knives and scissors when desperate. And only then switch to bare hands expecting to invest a lot of time into this adventure.

**Comment by ifreund** [comment]
Typical lawnmowers don't really work for grass longer than about 10 inches or so, as the strain on the engine becomes too high (10 inches is probably a generous estimate).  To mow tall grass you really need something like a [field trimmer](https://www.amazon.com/s?k=field+trimmer) or [brush mower](https://www.drpower.com/power-equipment/field-brush-mowers/)

**Pull request closed without merging**
