### PR TITLE
Item info: visualize armour coverage

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
In addition to just looking at the % numbers for armour coverage, why not use a visualization to represent which parts and how much they are covered?

Also, body graphs are cool :)

#### Describe the solution
Add a body graph representing sub-limb locations to the item info screen:

duster

The graph was split to get the most out of the small draw space. Each sub-limb is colour-coded based on how much it is covered, from green (full coverage) to red (low coverage) to dark gray (no coverage). These graphs only appear on items that have armour definitions.

For the sleeveless duster above:
```
Torso (+all torso sub-locations): 100% coverage (light green)
                            Hips: 100% coverage (light green)
                           Knees: 100% coverage (light green)
                          Thighs: 100% coverage (light green)
                      Lower legs: 60% coverage (yellow)
                       shoulders: 40% coverage (yellow)
```

Also added an option to disable the coverage map, since it takes up quite a bit of space:

option
no_graph

#### Describe alternatives you've considered
It's hard to fit enough of the graph to be useful while avoiding clutter. I found that using a smaller full-body graph was just too small to represent sub-limb coverage, and that using both halves of the graph was redundant since sided armour can (almost) always cover either side. Splitting these up makes the most out of the 40x20 space.

#### Testing

<details>
<summary>More examples of coverage maps:</summary>

maid_cloth
belt
tshirt
sneakers
sandals
gauntlet
sleeves

</details>

#### Additional context
Hopefully this proves just how easy it is to add body graphs to different UI windows :)

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Not related to your work, but just an observation: duster doesn't cover waist layer. And, I'm afraid, many other types of clothes too. It seems like it wasn't added when we migrated WAIST flag to waist layer.

**Comment by dseguin** [comment]
I believe the waist sub-limb is not associated with any body part, and only specific items define the waist location (similar to hanging-front and hanging-back for backpacks). Not sure if that's intended, but it hasn't broken anything so far

C.C.: @bombasticSlacks - Should the waist sub-limb be left out of the graph?

**Comment by bombasticSlacks** [comment]
Waist is like the hanging front and back. 

It can *only* be used for strapped items (storage)

It should really only be used for belts. In my mind.

Might be worth renaming it to be more clearly for storage.

**Comment by bombasticSlacks** [comment]
To answer your direct question, it probably should!

**Comment by dseguin** [comment]
Turns out it was easy to just overlap the torso onto the waist, so why not just have the best of both worlds, haha.

duster belt

**Comment by Termineitor244** [comment]
Awesome as always!!! I love more and more these graphs!

As a side note: It would be cool to have the total clothing coverage/protection per coverage displayed like this in the bodygraph status window, the info is already there in numbers and what not, but seeing it helps a lot to understand your weakpoints and how covered you really are in certain locations.

Thanks for doing this!!

**Pull request merged**
