### PR TITLE
PRM:  Add 'harmless' wildlife/bugs

### PR DESCRIPTION
**Pull request by pisskop**
These help varietize the game, nullficate some wouldbe spawns, and seasonalize the forest and swamps and fields.

-maggots
-moths/butterflies
-pupae
-skunks
-goats
-large dogs

### CODE REVIEW

**Comment by Chezzo** [comment]
Is this gonna cause the same problems vermin had in the main branch? Like stopping LAW rockets and such?

**Comment by pisskop** [comment]
They arent vermin.  Theyre all at least the size of a fist and most are the size of a skunk.

**Comment by Zireael07** [comment]
A critter the size of a fist shouldn't stop a rocket, though. That's the same problem we had with vermin.

**Comment by pisskop** [comment]
dont know what to tell you.

a spore cloud will stop a rocket
a crow will stop a rocket
a digging underground giant worm will stop a rocket

**Comment by mugling** [comment]
Sorry, got to agree with @chezzo and @Zireael07 on that. After extensive discussion such features were removed because they were a huge problem. I don't think we want to reintroduce them even in a mod.

**Comment by pisskop** [comment]
there is no grounds to reject this.  these are no different than oppossum, lemming, or bullfrogs.

**Comment by mugling** [comment]
Pretty sure bullfrogs were supposed to have been removed in  #16215 - that looks like an omission

**Comment by pisskop** [comment]
that they were overlooked and recieved no complaints is more evidence as to the unfounded nature of rejecting this.

* they arent hard to see.
     they are not periods the color of grass.  they are 'w's and 'r's.

* they wont spam messages.
    they are not hostile, not invincible to melee or ranged attack, not immune to ramming, and dont spawn in tight knit waves.

* they are afraid of the player, and combat.
    They are not going to be around the vector of a rocket, ludicrous as this concern is. 

I cannot believe you think this rocket thing is a legit concern when a flag to make the rocket/bullets path through vermin would both find use and be easy to implement

**Comment by mugling** [comment]
It's not unfounded - I'm declining to merge precisely because after lengthy previous discussion two other developers decided to remove nearly identical content.

> I cannot believe you think this rocket thing is a legit concern when a flag to make the rocket/bullets path through vermin would both find use and be easy to implement

If you can fix the original issues highlighted then I can't see a problem with including this but that needs to occur prior to this PR and the implementation needs to be both robust and cover all the original points. If you want to start work on this it may be good to clarify in advance what the requirements would be.

**Comment by pisskop** [comment]
The list of 'shortcomings', as listed in #15863.

this pr faces none of these issues, and ive already covered a good deal of them in defense of this pr

**Comment by mugling** [comment]
The mechanics issues need working out in a separate PR before this could be merged. @Coolthulhu's list in #15863 is a good, but not exhaustive, list of the problems. If nobody wants to tackle that issue this PR could be split as not all of the content is problematic

**Comment by pisskop** [comment]
this shows me you didnt read the pr contents or description

**Pull request closed without merging**
