### PR TITLE
Remove some duplicated items.

### LINKED ISSUE #10795: Duplicated items
There are three duplicated items, in [the handloaded bullets file](../tree/master/data/json/items/handloaded_bullets.json):

* reloaded_300_winmag
* reloaded_32_acp
* reloaded_762_54R

They have slighty different values, I don't know which one should stay. But I'd say the ones between lines 296 and 370 are wrong, just because they have different indentation from the rest of the file.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7596256-duplicated-items?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Sheco**
Resolves #10795 

The lines I removed had "RECYCLED" effects, but the ones that remained don't have that effect.

Should it be added?

### CODE REVIEW

**Comment by BevapDin** [comment]
> The lines I removed had "RECYCLED" effects, but the ones that remained don't have that effect.
Should it be added?

Yes, that effect makes guns misfire sometimes when using that ammo. It should apply to all hand loaded ammo. Rivet-the-Zombie may have to say something about this, afaik this is their area of expertise.

**Comment by Sheco** [comment]
@Rivet-the-Zombie what do you think?

**Comment by KA101** [comment]
I'm not Rivet, but I can say that the RECYCLED tag is kinda important for handloaded ammo, so you should reinstate it.

**Comment by Sheco** [comment]
I agree, KA101, all other items in that file have that effect so I think it's reasonable to assume it has to be there.

**Comment by Sheco** [comment]
This PR has the RECYCLED effect added to the ammos.

**Comment by KA101** [comment]
Yes, I see that.  My comp's bugging me to reboot for an antivirus update, so the merge may be a while.

**Comment by Rivet-the-Zombie** [comment]
What KA101 said.

**Pull request merged**
