### PR TITLE
Jsonize cbm trigger costs

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Interface "Jsonize and display CBM trigger costs"

#### Purpose of change
When checking the code to find out why the Alarm System CBM was unexpectedly draining all my bionic power I realized that the activation costs displayed in the CBM menu aren't the values used for the triggered effects from some CBMs. That value is hidden for most of them (probability travel shows it in the description but other CBMs don't) and it's hardcoded. In some cases the value is hardcoded in multiple files making it hard to mantain and prone to human error.

As a plus, having the trigger cost as a JSON field also makes it very easy to show that cost in the CBM menu.

#### Describe the solution
Added a new "trigger_cost" field to bionics.json to hold the energy cost for triggered activations of the CBM, as in reactive effects like phasing (probability travel), oxigenation (respirator), shocking attackers (electroshock), etc.

Also displayed that value in the CBM menu to give more feedback to the player.

#### Describe alternatives you've considered
Spend the time playing the game instead.

#### Testing
Tried the easy-to-test CBMs and power consumption is consistent with tests before the changes. The trigger cost is also displayed for each CBM so it makes it easy to see the values are right:

image

### CODE REVIEW

**Comment by GoLoT** [comment]
Oh, crap. There are a few old empty commits from merging upstream. Any way to rebase those now?

**Comment by actual-nh** [comment]
Ping: @Ramza13 - may be of interest to you.

**Comment by anothersimulacrum** [comment]
> Oh, crap. There are a few old empty commits from merging upstream. Any way to rebase those now?

If you do an interactive rebase, you can drop those commits.

**Comment by GoLoT** [comment]
> > Oh, crap. There are a few old empty commits from merging upstream. Any way to rebase those now?
> 
> If you do an interactive rebase, you can drop those commits.

Yup, that did it. I was worried about rewriting the history but it should be fine as the changes were only on my branch. Thanks for the tip.

**Pull request merged**
