### PR TITLE
Port from BN: Add command to pet menu for removing individual items from storage

### PR DESCRIPTION
**Pull request by WhiteCloud0123**
#### Summary

None

#### Purpose of change
Thie  is [Add command to pet menu for removing individual items from storage](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2868) in BN.I think this can further enhance the practicality of pets. It is also great for players who like pets, and transplantation does not require much work.

#### Describe the solution
Add a new function `take_items_from (Monster& z)` and new enumeration item in monexamine.cpp, and apply them in fact.
And I adjusted the position of 'Remove bag from' slightly, placing it later may be better.

#### Testing

After：
show_02
CLB_8{6 ONR1X284BD(OPH7
show_01

I generated a cow and then give and take items multiple times normally.

### CODE REVIEW

**Comment by mqrause** [comment]
It'd be nice to use an inventory multiselector menu for this, but I guess we're missing a monster item_location to make that possible right now.

**Comment by WhiteCloud0123** [comment]
I fully understand that the project wants and should also accept higher quality PR, but that is not a "transplant", but a "inspiration from * * * *, I have made a better reset", and then it may not be "not requiring too much work". If it's just this PR, I don't want to do too much work anymore, so I've decided to close this PR.

**Comment by SurFlurer** [comment]
You needn't to close this PR. What mqrause said can be a good follow-up improvement. Adding a item_location is non-trivial, at least from my perspective.

**Comment by mqrause** [comment]
Yeah, what SurFlurer said. This was in no way meant to be a requirement from me. It's an improvement as it is already.

**Comment by WhiteCloud0123** [comment]
> Yeah, what SurFlurer said. This was in no way meant to be a requirement from me. It's an improvement as it is already.
I am actually very serious about the CDDA project, and I don't want to treat it like I treat my own toy project. Transplanting immature content is really my negligence, and your comments actually strengthen my determination to close.

**Comment by WhiteCloud0123** [comment]
> Yeah, what SurFlurer said. This was in no way meant to be a requirement from me. It's an improvement as it is already.

I am actually very serious about the CDDA project, and I don't want to treat it like I treat my own toy project. Transplanting immature content is really my negligence, and your comments actually strengthen my determination to close.

**Comment by Zireael07** [comment]
@WhiteCloud0123 There is nothing "immature" about this PR and it's a great QoL improvement

**Comment by WhiteCloud0123** [comment]
If given the opportunity, I will go back and make an improvement, at least supporting multiple choices in a certain way.

**Pull request closed without merging**
