### PR TITLE
PRM: Add wildlife

### PR DESCRIPTION
**Pull request by pisskop**
This is a reattempt to push  #18358

Since there were no specifics given wrt what creatures were offending @mugling, I can only guess, but the pr was closed inappropriately, since the removal of said creatures would negate the argument that was proffered.

This pr adds, specifically:

-large dog
-goat
-Giant moth
-Giant butterfly
-Skunk

To the safe and forest spawn pools.

The purpose of such critters is to provide a buffer against a moose hiding behind every tree, which is something of a problem for new survivors, and players looking to immerse themselves into more than combat.

### CODE REVIEW

**Comment by mugling** [comment]
How does this differ from #18358?

**Comment by pisskop** [comment]
It removes creatures.   The description of both list the creatures added.

**Comment by mugling** [comment]
moths, caterpillars and butterflies have the same problem as before. You also have a lot of other content mixed in with this (in particular terrain)

**Comment by pisskop** [comment]
That is so as to not break the merge since other changes have been applied since the last fork.

**Comment by pisskop** [comment]
> moths, caterpillars and butterflies

They do not.  They are not nonaggressive, tiny, cpu-wasting creatures.  They are akin to opossums, lemming, bullfrogs, crows, dermatik larvae, spore clouds, crows, raccoons, black rats, and fungal ants.

**Comment by mugling** [comment]
Merging content that's not included in the title or preamble is out of the question. Nobody else has pushed content to your mod. You should be working against a copy of master not expecting master to revolve around some local variant of yours that nobody can see.

The issue as to vermin critters was opened by @Coolthulhu, supported by @Rivet-the-Zombie and then authored by @kevingranade. Two other authors spotted the flaw before I even got to your PR.

You need to resubmit the content excluding anything unrelated or that is contrary to #15863

**Comment by pisskop** [comment]
These are not vermin, nor are they functionally useless.  The game is replete with examples of creatures that match their description and statlines, and they will be merged.

**Comment by pisskop** [comment]
They have been included in an unsactioned mod for long enough to have been tested and balanced.  To whom do I argue the case to that these are not like vermin?

Because you call them vermin despite them in all instances not following the patterns that caused vermin to be removed.

**Comment by mugling** [comment]
**Split the content**. This PR still include other unrelated changes that don't even have anything to do with creatures. Then PR everything that is uncontested.

Your PR is already difficult to review and maintain. In particular you ask for merges of large chunks of unrelated changes, often with misleading PR titles, or desceriptions. The formatting is so bad that it leads to frequent errors - when I cleaned up the JSON for your items some of them weren't even functional.

Review time is limited and should be distributed equally amongst contributors. If you want to burn through your share arguing about changes that everyone who has seen your PR objected to as well as all of the developers then be aware your other PR's will need to wait till that's resolved.

**Pull request closed without merging**
