### PR TITLE
Revert "[AFS] bionic difficulty tweaks" that forced bionic slots and easy autodoc

### PR DESCRIPTION
**Pull request by Gourmand-is-OP**
**Summary**

Reverts CleverRaven/Cataclysm-DDA#42202

**Purpose of change**

The changes made in this commit made CBM installations in Aftershock have a 100% success rate, require no anesthetic, and forced the bionic slots mod to be effective permanently, even in vanilla gameplay.

This is strongly undesirable, as forcing easy autodoc in Aftershock forcibly removes a strong challenge from the game, despite it's commitment to both customization and realism.
The bionics slot mod is also already optional, and forcing it on players has no benefit, especially when the feature is already contested and not universally enjoyed.

As a result, these changes should be reverted, until its edits  can be made without involuntary modifications to the present game.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Let me preface this by saying that by using  an Experimental build, you are currently playing a partly implemented version of the planned Aftershock bionic System. Which I expect to fine-tune in the following weeks.

That said, let me adress some of your points. 

>This is strongly undesirable, as forcing easy autodoc in Aftershock forcibly removes a strong challenge from the game, despite it's commitment to both customization and realism.

I agree to this, and will soon add different tiers of autodocs that resolve this difficulty issue. Its most likely that safe installations will only happen in the autodocs found as Finales, and on some other moderately difficult to raid places.

>The bionics slot mod is also already optional, and forcing it on players has no benefit, especially when the feature is already contested and not universally enjoyed.

Both aftershock maintainers (Maleclypse and me)  believe that the Bionic slot system helps encourage more meaningful choices on how you decide to specialize your bionic load out, encouraging players to seek and find synergies between their prefered gameplay strategy and their installed bionics. In particular, I specifically wanted the combined  slot system and reduced installation costs to encourage players to install early game bionics;  and to later allow them to alter their installed bionics as their characters and needs progress. All this as a part of a long form plan to make bionics more prevalent in the early and mid stages of gameplay.

Its likely that the current slot limits are too low, especially for the limbs and hands, or that the occupied slots for some bionics are to high and restrictive. I encourage you to make revisions to the slot system to improve its balance within Aftershock, but I'm not interested in a PR disabling the system.

**Comment by Gourmand-is-OP** [comment]
These are good points. If I am reading this right, 
you intend to reduce the slot limitations in the future,  but are currently making it simple to change bionics to help experimentation as you cross over to earlier bionics. 

However, I imagine it would be better to make the first/first few bionics easier to install, or reduce the costs and installation difficulty of common bionics, such as those found in electronic stores or doctor's offices, than the quick autodoc fix (I might actually try pushing that second idea).

Finally, my secret, furtive goal, was to preserve the option of becoming a robot monster by installing every bionic you can get your hands on. Obviously, this wouldn't be balanced,  but since that doesn't mean it wouldn't be fun, I would like to ask if there will no longer be the possibility in the future to do so. (Obviously, I can simply change the files, but I am worried about players that aren't as savvy.) I personally, would like an entry in the debug options to toggle bionic slots, or, as an alternative, to replace the mod that enabled slots with one that does the opposite. Is there any possibility of this in the future, and would you prevent me from making such pushes if I were to do so?

**Comment by KorGgenT** [comment]
honestly as a second mod a mod that simply disables bionic slots is a no-go. This is an example of an "option revert" mod which we obsoleted quite a number of, if not all of them, earlier this year. Thus, this type of mod is unlikely to be accepted to the repo in a general sense. A debug option is even more invasive. Noone is going to stop you from creating a 3rd party mod (we couldn't if we wanted to) though.

**Comment by Maleclypse** [comment]
> Finally, my secret, furtive goal, was to preserve the option of becoming a robot monster by installing every bionic you can get your hands on. Obviously, this wouldn't be balanced, but since that doesn't mean it wouldn't be fun, I would like to ask if there will no longer be the possibility in the future to do so. 

I would like to one day have a quest chain that essentially digitizes your consciousness and uploads you into a robot body with the ability to mount all the CBMs, however you would lose the ability to heal naturally (similar to My Sweet Cataclysm) and all mutations except the ones required to expand your slots and remove healing, etc etc.  But that's not on the roadmap yet so no idea when that would be possible.

**Pull request closed without merging**
