### PR TITLE
Dost thou even lift: Add makeshift rope and chain lifts

### LINKED ISSUE #13562: Constructions: pulley & rope system
You're at your dream ranch near the garage, your careless driving made you rip off the lever to open the garage doors... But no problem! You can rebuild it!...

`22:31:36 <        dRbiG> t_barndoor[207] vs t_palisade_pulley[208]`

Nope, it won't work, because you built the latter instead.

A sane 'quick' fix would be to ask what 'type' the player wants to build.

The long-term/better solution is an actual look over the constructions and then figuring out a sane way to handle it (e.g. 'What should this pulley & rope system be connected to?'). I'm quite positive there will be other cases like this one. 'Bob the builder stuff' is obviously one of the least play-tested things.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26712542-constructions-pulley-rope-system?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #23094: Do you even LIFT? We need makeshift lifts for vehicle maintenance.
Game version: 
Since #22980
Operating system:
All
Tiles or curses:
All
Mods active:
N/A
### Expected behavior
Minor alterations to vehicles can be made using readily available tools.
### Actual behavior
Installation or removal of anything but the lightest vehicle parts requires either extreme strength or a tool with LIFT 1, of which there are only two (small or medium crane, defined [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/4024bbe80466ed36beffbcd329c0b6773532ec93/data/json/vehicleparts/engineering.json), and they're quite rare.
### Steps to reproduce the behavior
Have vehicle with removable storage battery (e.g. autotractor).
Try to remove.

Simplest solution is a makeshift lift or winch, like https://www.harborfreight.com/1-ton-chain-hoist-996.html and a way to attach it to a raised object like the side of a building or a tree.
On the even more makeshift side of things, one should be able to throw together a winch by bolting a drum and handle to a vehicle, and then throwing a rope over a tree branch or something.

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
Content "Adds some common makeshift lifting tools"

#### Purpose of change
Closes #23094
Closes #13562

#### Describe the solution
image

Creates three new furnitures and a new 'block and tackle' item. Constructing the furniture is contingent on the terrain present in the tile.

1. Rope hoist: Hang a rope from a tree branch, or bang a couple 2x4s up to the ceiling and dangle it from there. This is a pretty efficient way to lift even fairly heavy things. 
2. Rope and tackle hoist: As above, but you've looped the rope through a tackle and have a lot more capacity to lift. Can be firmly attached to a tree branch, or to a ceiling. Fits on any ceiling because it's still not ultra strong.
3. Chain hoist: Must be attached to a ceiling and only allows concrete, reinforced concrete, or metal floor/ceilings. As strong as any crane. Requires some fabrication knowledge to mount safely.

The new block and tackle item is required for making existing rope and pulley systems and included in their deconstruction recipes.  While I was in there, I changed the terrain names to fix #13562. The block and tackle also spawns in common hardware groups and garages, and most of the time spawns with a piece of rope or chain attached. I did not add a crafting or uncrafting recipe for it, someone else could look into what that would entail. It could probably be done with sheet metal and small sturdy wheels.

Since I used nuts and bolts here, I made them spawn in more places as they were quite rare (or not spawning at all? Idk) and I've wanted to start requiring specific fasteners a bit more anyway

#### Describe alternatives you've considered

I am not currently extremely happy with the pre-terrain checks for ceilings. I don't know if you should be able to spike a rope and tackle into a dirt cave ceiling or a crumbling wooden barn and get enough stick. Chain hoists are a bit jank and overly specific. However to improve the pre-terrain check here would either require some new pre-tests for the durability of the underlying terrain, or a new terrain flag representing stronger types of supports. Both of these are things we could use in the future but I really don't wanna do them.

The lift numbers here are somewhat arbitrary. We could consider having more advanced lifting furniture/terrain that has higher lifting numbers.

#### Testing
image
Simple rope hoist on a tree

image
chain hoist in a concrete floor

image
Lifting quality is granted by the furniture

ed: dang, the game won't acknowledge the nearby lifting furniture for vehicles

#### Additional context
Just removing two of our oldest issues with an hour or so of work in my breaks. nbd.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Thanks to @mqrause and #59536 this should be good to go, functionality was tested in that pr

**Comment by Zireael07** [comment]
Closing 4,5 years old issue, congrats! I think it's gotta be some sort of a record?

**Comment by I-am-Erk** [comment]
Not a record but it is pretty good.

**Comment by Night-Pryanik** [comment]
#56143 closed 8,5 years issue.

**Comment by descan** [comment]
Normally wouldn't comment on a closed/merged commit like this, but I did have to go looking for this one to figure out *how* to place the constructions in-game, as it doesn't actually say what terrain/tiles are kosher except for a vague "horizontal beam" or something akin to that? Making the idea of a tree or the 2x4s you mentioned more explicit in-game might help other folks, and prevent bug-reports in the future of "I can't place this construction!"

**Pull request merged**
