### PR TITLE
Ultica: fix heavy duty quarterpanel corners

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary
None

#### Purpose of change

The rear right and rear left heavy duty quarterpanel corners looke wrong when the car is pointed east.

rear

#### Describe the solution

Swap the image numbers in tile_config.json 

#### Describe alternatives you've considered

Use an image editor to swap the sprites

#### Testing

* the game loads
* the tiles look right

### CODE REVIEW

**Comment by int-ua** [comment]
Thanks! Unfortunately, the Ultica version in the CDDA repo is overwritten on update, it has to be fixed upstream at https://github.com/I-am-Erk/CDDA-Tilesets/

Ask me if you need any help. We have Discord server if that would be appropriate for you.

**Comment by int-ua** [comment]
And if you are curious how it all works you can read https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TILESET.md

**Comment by int-ua** [comment]
@acepleiades should push the fix soon, he already has it in his branch

**Comment by ZhilkinSerg** [comment]
Closing this - changes should come from upstream tileset repo.

**Pull request closed without merging**
