### PR TITLE
Fix the infinite loop of trying to spawn a blacklisted monster

### LINKED ISSUE #75212: Game freeze near FEMA camp with Only Wildlife mod
### Describe the bug

I try to reach FEMA camp and CDDA freeze when Only Wildlife is enabled.
Teleporting  to the camp also cause freeze.

### Attach save file

[nomonster-trimmed.tar.gz](https://github.com/user-attachments/files/16362605/nomonster-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. go one step north

### Expected behavior

Player should be able to reach FEMA camp without freeze

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: cdda-experimental-2024-07-24-0510 a24a4db [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    削除 - モンスター [Only_Wildlife]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cknight828**
#### Summary
None

#### Purpose of change
Fix #75212

When trying to spawn monsters from a monster group, the quantity of monster to be spawn is not decreased when a sub group of top level monster group is selected, because it should be decreased in the sub group. But if some monsters are blacklisted and they are selected in the sub group, they are replaced with the default monster of the top level group but the quantity is not decreased.
For this, extra monsters may be spawn but it normally does not cause serious problems, because the valid monster in the sub group or the individual monster entry of the top level group is selected eventually in the loop. But at the worst case, the top level group contains only monster groups and all monsters in the group are blacklisted (like GROUP_VANILLA with Only Wildlife), the game will freeze.

#### Describe the solution
The quantity of monster is decreased when a sub group is selected but a blacklisted monster is seleceted in it.

#### Testing
Start game with Only Wildlife mod and reach FEMA camp.

### CODE REVIEW

**Review by RenechCDDA — DISMISSED** [review]
This actually changes spawn behavior quite significantly, take the following example:

```
GROUP, PICK ONE
---FULLY_BLACKLISTED_GROUP, weight 1
---NOT_BLACKLISTED_MONSTER, weight 1
```

Current behavior will be that the not blacklisted monster will always spawn, because the blacklisted group is excluded as a valid choice.

With your change, it's a 50% chance to spawn *nothing at all*.

A better approach would be loop detection, even a hacky solution of counting the number of times it's loop as some very high number (e.g. 100,000+) and then breaking if we hit that count.

**Comment by cknight828** [comment]
> ```
> GROUP, PICK ONE
> ---FULLY_BLACKLISTED_GROUP, weight 1
> ---NOT_BLACKLISTED_MONSTER, weight 1
> ```
> 
> Current behavior will be that the not blacklisted monster will always spawn, because the blacklisted group is excluded as a valid choice.
No. The blacklisted group is not excluded in MonsterGroupManager::FinalizeMonsterGroups.
If FULLY_BLACKLISTED_GROUP is selected, an empty vector is returned from recursive call of GetResultFromGroup and the default monster of GROUP is added to result. Currently, the quantity of monster is not decreased in this case, so the default monster continues to be spawned until NOT_BLACKLISTED_MONSTER is spawned. Is this behavior intended?

**Comment by cknight828** [comment]
I didn't notice the difference between place_monster and place_monsters. 
In place_monster, spawning works well now.
This pr fixes about place_monsters case.

**Comment by RenechCDDA** [comment]
> No. The blacklisted group is not excluded in MonsterGroupManager::FinalizeMonsterGroups and still exists when spawning. If FULLY_BLACKLISTED_GROUP is selected, an empty vector is returned from recursive call of GetResultFromGroup and the default monster of GROUP is added to result. Currently, the quantity of monster is not decreased in this case, so the default monster continues to be spawned until NOT_BLACKLISTED_MONSTER is spawned.
> 
> Is this behavior intended?

It looks like your assessment is completely correct(!?). That is really, REALLY not how I believed it worked and appears to be contrary to how blacklists work with item groups.

I'm going to go ahead and say that behavior is a bug, but also you don't have to deal with it in this PR.

**Comment by RenechCDDA** [comment]
I think this is still 'double counting' the quantity? If we find a monster inside the for-loop, quantity is decremented. But then we exit the loop and *decrease it again*, regardless of whether or not we found a monster. The check should *probably* be

```
    if( quantity && !monster_found && is_recursive ) {
        ( *quantity )--;
    }
```

I would love to verify the behavior, but I have been unable to get place_monsters to spawn any monsters, at all. So I literally cannot test this.

**Comment by cknight828** [comment]
> I think this is still 'double counting' the quantity? If we find a monster inside the for-loop, quantity is decremented. But then we exit the loop and _decrease it again_, regardless of whether or not we found a monster. The check should _probably_ be
> 
> ```
>     if( quantity && !monster_found && is_recursive ) {
>         ( *quantity )--;
>     }
> ```
> 

Quantity is not decremented when spawn_details is empty, so double counting does not occur. But monster_found is not set properly, it should be fixed and the check should be changed.
> I would love to verify the behavior, but I have been unable to get place_monsters to spawn any monsters, at all. So I literally cannot test this.

Spawning is guaranteed when density is set higher than 0.1

**Comment by cknight828** [comment]
@RenechCDDA Is there something wrong? I found the same issue in 0.H and want to backport this pr.

**Comment by RenechCDDA** [comment]
It's just waiting on merger review right now. I don't personally have merge permissions.

**Pull request merged**
