### PR TITLE
Fragile and Sturdy flags cannot be inherited

### LINKED ISSUE #75163: Aftershock light exosuit frame gets damaged in combat
### Describe the bug

When the light exosuit frame from aftershock is powered on it is considered fragile and will break in combat.

### Attach save file

N/A

### Steps to reproduce

1. Wear light exosuit frame.
2. Equip exosuit auxillary battery.
3. Examine light exosuit frame. (Now considered fragile AND sturdy)
4. Get attacked.
5. Light exosuit frame takes damage and eventually breaks.

### Expected behavior

Exosuit should not get damaged/break.

### Screenshots

_No response_

### Versions and configuration

OS: Windows 10
Game Version: 99ed329
Graphics Version: Tiles
Language: English

Mods loaded:   "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "magiclysm",
  "bombastic_perks",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "aftershock"

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
Bugfixes "Fragile and Sturdy flags cannot be inherited"

#### Purpose of change
Fixes: #75163

And overall it doesnt make sense for the base item to ever become fragile/sturdy when you attach items to it.

### CODE REVIEW

**Comment by RedMisao** [comment]
Wouldn't it be better to instead apply something like:
```json
"delete": { "flags": [ "FRAGILE" ] }
```
directly to the Aftershock item(s) ?

If there are any other items using `"copy-from"` that rely on copying such flags, they will break with this change.

**Comment by Karol1223** [comment]
I do not see why limiting the compatibility of the flags with ``copy-from`` is the way to go instead of solving the problem where it actually is a problem through the use of ``delete`` syntax.

**Comment by John-Candlebury** [comment]
Oh this affects only the behaviour of the "inherits_flags" pocket setting, as when you mount a NVG unit to an army helmet.  "copy-from" functionality wont be affected by this

**Comment by RedMisao** [comment]
Modded the `inherit` line to check if a item B being a `copy-from` item A with `FRAGILE` inherited the flag, and it does.
Most importantly, it is already documented to work for attachments/pockets, my bad.

**Pull request merged**
