### PR TITLE
Make target size affect ranged accuracy - take 2

### PR DESCRIPTION
**Pull request by Coolthulhu**
First attempt was #20119
Re-PRing because I clogged last one with needless `bool` switches passed everywhere.
Here it's much cleaner, although a bit hardcoded.

Once again, the changes are:
> Bigger targets get easier to hit than smaller ones, regardless of dodge values (dodge values still apply, just that they don't matter much for firearms). This is achieved by replacing the hardcoded `occupied_tile_fraction` by a function of target size.

Needs balance testing. I'll be trying to test it by playing a ranged character, but it would be useful if someone could help with actual gameplay tests.
Or we can merge earlier and do complaint-based balancing.

### CODE REVIEW

**Comment by Vidiveni** [comment]
Grenadiers could get scary.

**Comment by kevingranade** [comment]
On Feb 26, 2017 12:05 PM, "Vidiveni" <notifications@github.com> wrote:

Grenadiers could get scary.

If we have dodge scores elevated to emulate small size, we should reverse
that.

**Comment by Coolthulhu** [comment]
All grenade drones are tin + 6 dodge. Actual manhack is tiny + 0 dodge.

**Comment by Coolthulhu** [comment]
Nerfed bomb drone dodge (to 0) so that they stay dealable-with.
This makes them easier to deal with in melee, but it's not like they need that extra strength to be terrifying in battle.

**Pull request merged**
