### PR TITLE
Bugfixes for dairy farms.

### PR DESCRIPTION
**Pull request by Vasyan2006**
- A cow can be milked nearly infinite times per day now. This change will restore initial value from monsters.json,
- Dairy farm road connection point in on the north part of the and it can be imposible to drive from the road to the gate. This change will move this point to the south gate.

### CODE REVIEW

**Comment by Mecares** [comment]
Seems a bit arbitrary to set it to 4 units, which equals one litre per day while in reality cows can give up to 50 litres which would be 200 units per day.

**Comment by nexusmrsep** [comment]
While 50 litres would be too much for balance in my opinion, but 1 litre is much too few. A bucket worth of milk maybe? How much can bucket contain?

**Comment by smolbird** [comment]
20 units, or 5 liters. That sounds potentially reasonable.

**Comment by mlangsdorf** [comment]
While you're in the code, would you please make sheep milkable at about 1/3rd the production of cows? It's kind of sad to get to a dairy farm and not be able to make sheep's milk cheeses.

**Comment by Vasyan2006** [comment]
Amount of milk per day (4 units) is written in monsters.json. But there is a bug so a cow can be milked 2400 times per day instead of 4. This change will restore initial value. I dont want to change game balance  because this PR should be a tiny bugfix.

@mlangsdorf Sheeps should provide wool instead of milk. I would like to play a postapocalyptic happy farm but it will require more complex work, possibly including breeding as discused in another PR.

**Comment by mlangsdorf** [comment]
Sheep should provide milk, because sheep's milk is a real thing in the real world.

If you don't want to make the change, it's easy enough for me to PR it.

**Comment by DracoGriffin** [comment]
>Amount of milk per day (4 units) is written in monsters.json. But there is a bug so a cow can be milked 2400 times per day instead of 4. This change will restore initial value. I dont want to change game balance because this PR should be a tiny bugfix.

Just the starting "ammo" -- no reason milking couldn't be increased a bit to be closer to realistic values. Still falls under the bugfix.

>@mlangsdorf Sheeps should provide wool instead of milk. I would like to play a postapocalyptic happy farm but it will require more complex work, possibly including breeding as discused in another PR.

Although now that #23774 is merged, animal husbandry has a basic form. Also, I agree that should be a separate PR as sheep also require some way to be tameable (can simply add cattlefodder to work on sheep as well).

>If you don't want to make the change, it's easy enough for me to PR it.

Yes, please do.

**Comment by mlangsdorf** [comment]
Submitted #24016

**Pull request merged**
