### PR TITLE
Adds the exodii labyrinth monsters

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
None

#### Purpose of change

#73247 is a super huge PR so I'm parting it out into components, and updating the major deficits of those components as I go.

#### Describe the solution

Adds the monsters and monstergroups for the exodii labyrinth.
- Fleshborg: The default super basic monster, a slow and plodding enemy with a weak ranged attack.
- Advanced fleshborg: As above but, um, a bit more advanced? You get it.
- Stiltwalker: A fast melee enemy with giant stabby blades for limbs. Bad news.
- Labyrinth turret: a weak stationary enemy that basically throws rocks at you.
- One-shot turret: Most complicated enemy here for now, this thing has a 'dormant' and 'active' mode. When it spots an enemy, it charges up and switches to its active mode, then fires off a powerful attack. There is a gap between the two, giving you a chance to get to cover. Once it shoots, it destroys itself.

All of these except the one-shot have been tested in the original PR, I'm leaving this in draft until I have a chance to try out the one-shot as well.

#### Describe alternatives you've considered
I would love to have more enemies here. These ones need more playtesting, but they've been up a few weeks and I've had no takers, so as usual, we'll do it on the fly.

#### Testing
Fleshborg/advanced fleshborg/stiltwalker/labyrinth turret have all been tested in the original PR, one-shot turret just needs a little bit more, but I'm going out for dinner shortly and just wanna get the draft up before I go.

#### Additional context
The one-shot turret needs some attacks of its own before this is done. Open to suggestions for what it could do besides basic stuff, a few weird effects would be fun. Also I want to make it hostile to other netherum creatures so that you can lure enemies into its range to destroy it.

### CODE REVIEW

**Comment by Nebnis** [comment]
I know it is a draft but i will give some feedback. You should probably bump the hp and armor of some of the stronger bots to 150~200hp and add something that makes sense to them like a lot of cut or pierce armor. I would also be care with dumping nether creatures because a significant amount of them are extremely deadly like the nuckavelee,polyp and the star vampire. They are all threats that mostly only die to rifle bursts/nades or advanced melee

**Comment by I-am-Erk** [comment]
The star vampires got nerfed recently and actually I need to update that. In general, if they make it into the final groups at all, it'll be as rare bosses

**Comment by IdleSol** [comment]
How long does it take for a labyrinth to create a copy? Can the labyrinth create a copy of the player character? An evil copy? An evil not perfect copy?

An NPC with the player's enemy value, characteristics, skills, and equipment. A mini-boss if there is a room with a good reward.

Or maybe neutral? Go after your new “perfect” follower in the labyrinth.

**Comment by I-am-Erk** [comment]
I've presumed it takes a while, I don't want to have to explain why the player can't dupe items themselves

**Comment by IdleSol** [comment]
Add hallucination mechanics? Only one that disappears on death, not on taking damage.

Or repeating all of the user's actions. And then the result depends on luck.

**Comment by MNG-cataclysm** [comment]
[This PR](https://github.com/I-am-Erk/Cataclysm-DDA/pull/35) should probably be considered too, since it works with monsters involved here.

**Pull request closed without merging**
