### PR TITLE
Permanent underbrush

### PR DESCRIPTION
**Pull request by facepalm**
As described in issue #11813, it's odd that underbrush disappears when foraged through, and berry bushes, shrubs, and apparently triffid root walls all turn into underbrush when smashed, in order to provide more foraging if needed.  This hopefully changes that for the better.

Changes:
- Underbrush spawns a (dark green) harvested version of itself upon successful forage, similar to how berries work.
- Harvested underbrush regenerates each season.
- Shrubs, underbrush, etc are all destroyed (replaced with t_dirt) when smashed.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by Rivet-the-Zombie** [comment]
Oh, very nice!

**Comment by Coolthulhu** [comment]
Regenerating underbrush looks good.
How about some information about the harvested state in the name? Most of the time it will be obvious from color, but in some cases (blood, darkness, veggy guts, out of game visual problems etc.) the color alone is not enough.

Not so sure about the insta-wrecked shrubs. I liked the fact that zeds can't just smash the shrubs in one lucky hit (makes sense that bushes are hard to smash apart).

**Comment by KA101** [comment]
Interesting.

**Comment by facepalm** [comment]
>but in some cases (blood, darkness, veggy guts, out of game visual problems etc.) the color alone is not enough.

Oh, good thinking.

Everything else in the game that can be smashed does so instantly, though.  Small trees, for a very close by example.  If this makes bushes too easy for a zombie to smash through, it would be more consistent to compensate by just making them harder to smash.

**Comment by erzett** [comment]
Small nitpick: It would be nice if regenerated underbrush didn't have a chance to give trash.

**Comment by Tomcost** [comment]
I think that the trash could be carried by the wind to bushes, and that's why you could find more in the same spot. I wouldn't think of it as something important, though.

**Pull request merged**
