### PR TITLE
Material changes to medieval items

### LINKED ISSUE #52658: Various medieval items forged by player out of steel are made of iron
# Is your feature request related to a problem? Please describe.
There are a decent number of items players can craft that are made from steel but turn into iron upon completion. This is undesirable since iron is an inferior material and it makes little sense you'd deliberately smith something out of lower quality material, especially when you are using steel in the first place. Some examples:
Chainmail armor - this is made from Wires which are steel, but it uses the Iron material.
Conical Helm, Galea, Kabuto, Nasal Helm, Plated Leather, Pickelhaube, O-Yoroi - all these armors are forged from steel but turn into Iron after creation.
Baselard, Pike, Lajatang, Ironshod Quarterstaff, Mace, Scimitar, War Hammer - these weapons are forged from steel but become iron. 

# Describe the solution you'd like
These items should be made of steel to reflect the fact that they are made of steel. But it's not that simple, I assume this is deliberately done because they are weapons that predate steel. However many items, such as chain, pikes and maces, have steel versions too, historically speaking.
Should there be separate "quality" versions of these weapons hand-forged by survivors, while generic versions are made of iron? Or should they just be updated to be made of steel?
Further, I am operating under the assumption that Iron is an inferior material to steel. Armors made of iron are definitely worse than ones made of steel, due to the material properties defined in JSON. But does it actually affect weapons? I assume iron weapons are less durable, but I don't have any evidence to back this up.
I ask all this because I am interested in fixing this but I don't know what the best path to take with this is.

# Describe alternatives you've considered
(above)

# Additional context
On an unrelated note, I wanted to do some general cleanup of related issues. Namely I wanted to turn scrap armor into actual book-less blacksmithed armor instead of scrap metal strung together like Christmas lights, 
Second, I feel like armor values of medieval gear could use an audit? Full plate armor has a pathetic 16 slash defense, compare that to a broadsword which deals 27 slash damage. Plate armor should easily be able to negate pretty much any slashing weapon, I could easily see its defense being doubled or tripled in this regard. Just wanted to ask these questions while I'm on the subject.

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Medieval iron gear now steel"

#### Purpose of change

Fixes #52658
#### Describe the solution
Chainmail is now made of Steel instead of Iron, this pushes its defense to 14/14/8 up from 10/10/6. Morningstar, Ironshod Quarterstaff, Mace, Pike, Scimitar and some others are made of Steel. Player-crafted baselard now creates a steel version so that medieval peasants can still have their crappy period-appropriate iron version. 
Most other medieval weapons are steel, while it may be appropriate to include a few random iron ones too the spawnpools are already diluted by random garbage budget weapons. However everyday chainmail is made of iron, only player-made chain is actually steel. This retains its usual less impressive defense for world-found spawns. 
Also included XL Faraday Chainmail and kevlar gambesons-backed chainmail hauberks.

#### Describe alternatives you've considered
Create historical rusty iron versions of all these weapons. Given that they already have shoddy versions I don't think this is worth the overhead. 
Increase protection/thickness of steel plate armor - not doing that right now because other devs are considering making sweeping changes to those anyways. I am going to hold off giving these a ratio of steel to cotton or leather, even though it should now be possible, because these values are better left to whoever is more thoroughly redesigning armor. This is mostly just focusing on recipe/material gripes.

Kevlar-backed chainmail may be too beefy because its thickness (6) was not reduced from the cloth gambeson version. The resulting defense will be pretty high.

#### Testing
Everything seems to be working. Balance may be subject to change in future given kevlar gambesons are being nerfed.

### CODE REVIEW

**Comment by Zireael07** [comment]
Historical items should be iron, not steel - steel was simply not known in medieval times.

If you want to fix the issue where the player crafts from steel but it becomes iron, it needs to be some modern, reconstructor item.

**Comment by Inglonias** [comment]
> Historical items should be iron, not steel - steel was simply not known in medieval times.
> 
> If you want to fix the issue where the player crafts from steel but it becomes iron, it needs to be some modern, reconstructor item.

It seems that this is not correct.
https://en.wikipedia.org/wiki/Wootz_steel
https://en.wikipedia.org/wiki/Damascus_steel

**Comment by Photoloss** [comment]
Steel was known in the middle ages, and could be produced accidentally way before then as pretty much everyone fired their metalworking forges with carbon.

**However** steel was not always used even when available, and the historical production methods were far less consistent and reliable than modern ones. Maces were even made of _bronze_ because they maintain structural integrity through compactness and sheer bulk. And steel does not equal steel. Famously the katana uses a thick soft iron/mild steel spine with a very hard and brittle steel edge, both a far cry from tempered spring steel blades used in rapiers and sabres.

Mail is the main cause for concern as it is produced by bending and riveting the individual rings together. Even modern reproductions most likely won't attempt heat treatment after completion and the base material needs to be relatively soft. Earlier period helmets often weren't hardened either, and the Romans didn't really have the technology at all to my knowledge. These would all fall under "mild steel" though as it's pretty much impossible to produce or maintain pure iron in a charcoal forge. Ultimately this is a matter of technology however, the material properties match what the layman would call "iron" not "tool/weapon steel". In particular the defensive quality of mail, "viking" age and earlier gear should not increase as if they were made of modern steel. And they definitely did not have stainless steel to any significant degree, but that material could be repurposed as "mild steel" since it only exists to nerf medieval weapon spawns anyway.

The durability perk on the ironshod quarterstaff is also questionable but for a completely different reason: it is a bashing weapon and still has only the wooden pole for most of its length. At the very least the description needs some clarification, [langets](https://www.deviantart.com/sgainbrachta/art/War-hammer-langets-293844421) attached to the caps would definitely provide a significant durability increase while circumferential "bands" only add stress-focusing weak points (think of where tool axes break - right where the head meets the haft). However, and this should go in a separate PR, it is rather ridiculous that staves and greatswords cannot perform reach attacks and adding those would drastically shift their gameplay balance.

**Comment by anoobindisguise** [comment]
OK:
Generic chainmail items found in the world are still iron. Player crafted versions and all XL versions are steel. There are also variants with kevlar gambesons instead of cotton gambesons available. 
Steelshod quarterstaff lost sturdy again, for now. Maybe I should soup it up with oil like the Long Pole recipe to represent strengthening it.
Currently most weapons don't have steel AND iron versions, just steel versions. Even if iron versions would theoretically exist steel versions did too (there are certainly steelheaded pikes, steel maces historically) their spawnpools are already diluted with junk versions so it doesn't feel necessary to me.

**Comment by anoobindisguise** [comment]
The only question I have left is whether to make these use copy-from. The documentation warns against excessive copy-from inheritances. Is this such a case? Steel copies from Iron, then XL copies from Steel?

**Comment by anoobindisguise** [comment]
Looks like copy-from is broken. Going to close this again and fix it...

**Comment by anoobindisguise** [comment]
This issue isn't my fault. Reopening.

**Comment by anoobindisguise** [comment]
I see no reason why this should be failing. I made zero changes since last time and it was working then.

**Comment by anoobindisguise** [comment]
Kevlar-backed chainmail is now steel, kevlar, layered kevlar. This should dilute its defensive values somewhat. Encumbrance is 20% higher as well.

**Review by kevingranade — CHANGES_REQUESTED** [review]
This should not be a buff, if you're adding steel armor and weapons as the "proper" versions, those version should have the offensive or protective value of the previous iron version, and the previous iron version should now be worse.
Alternately just bump the materials to steel, drop thickness to compensate, and leave the item ids the same.  If functional steel armor is achievable by the survivor, there's no reasonable argument for pre-existing versions not also being steel, as the survivor has no special access to advanced metallurgy.

**Pull request closed without merging**
