### PR TITLE
Expanded Lab Sites

### PR DESCRIPTION
**Pull request by BrianLefler**
More labs:
- House and prison basements have a chance of hidden lab stairwells.
- 2x3 office towers have a chance of a hidden tower lab: five stories of labs with two finales on top, with full lighting, an altered monster set, and more monster density the higher up it goes.

Trains:
- A third of overmaps will have half their labs connected to the normal subway via new lab train depots.
- A possibility of a lab-only subway network on z level -4, connecting all labs in the overmap together, if and only if the central lab is placed on the overmap.
- Lab train stations have a terminal which can be hacked for a map of the subway.

Central Lab:
- A massive lab complex, only accessible via the lab-only subway network.
- Layout wise, the lab has a fixed cross-style layout on level -2, above a randomized layout (reusing the lab logic by placing four randomized labs of unusual size placed so they overlap with each other). 
 It is accessible by up to four subway entrances.
- Central labs have a tougher monster table with more spawns, full lighting, and around ~8 finales (each of the four wings has the usual finale at bottom and a chance of a finale on each level which should work out to ~1 additional per wing).
- The central lab has a place for grand finale - a fixed 3x3 area above the normal area.  Currently it isn't designed, and is instead just a space of collapsed hallways and an escape hatch to the surface.
- The central lab escape hatch goes out to a concealed forest manhole.

Potential future work that I think should not block initial submissions.
- Decide on a central lab grand finale and build that.
- More hidden lab areas, like under hospitals or tower labs over the hardcoded 2x2 office towers.
- Put an internal-facing set of science id-locked doors on lab entrances so people can exit labs they got to via train without having to fight a turret (this would affect lab escapes greatly).
- Allow a more reduced frequency for overmap specials than the current min 0, max 1 (like maybe a fractional max, so you could say no more than 1 in 3 overmaps), so that central labs (and maybe the necropolis) can be specifically made rare.

### CODE REVIEW

**Comment by BrianLefler** [comment]
Example central lab layout: The top level is a fixed layout, lower levels are dynamic.
screen shot 2018-07-21 at 1 59 36 pm
screen shot 2018-07-21 at 2 00 16 pm
screen shot 2018-07-21 at 2 00 34 pm
screen shot 2018-07-21 at 2 00 45 pm

**Comment by BrianLefler** [comment]
Train Depot:
screen shot 2018-07-21 at 1 57 11 pm

Basement lab stairs:
screen shot 2018-07-21 at 2 15 57 pm

Prison experiment wing / lab stairs:
screen shot 2018-07-21 at 2 13 45 pm

**Comment by ZhilkinSerg** [comment]
Lol, we have two subways now.

**Comment by DracoGriffin** [comment]
This looks amazing. I seriously don't know how people manage to make maps like these; I've made one location and took me forever.

Looking forward to it!

**Comment by Shodan14** [comment]
Has anyone updated the locked lab areas or is it still only armory and containment?

**Comment by BrianLefler** [comment]
Yes, there's a new bionics vault.  It doesn't happen on lab encaps like the armory/containment maps,   instead it can occur on regular cross-style json maps when they border rock (I think the odds are about a quarter of the time).

**Comment by Shodan14** [comment]
> Yes, there's a new bionics vault. It doesn't happen on lab encaps like the armory/containment maps, instead it can occur on regular cross-style json maps when they border rock (I think the odds are about a quarter of the time).
That's nice, but it would be cool if there was more variety in the locked rooms, both with different good stuff (equipment, mutagens, whatever) as well as bad stuff (leaky reactor, extra hard monsters,etc.)

**Comment by vache** [comment]
If you're looking for finale ideas, or more ideas to spice up labs in general, I have several that I wrote up a long time ago but don't have the time or drive to work on anymore.  A lot of them have some kind of quest/story/NPC based component to them, because I always envisioned the labs as where players would go to find all the lore and answers about how the cataclysm happened.

https://github.com/vache/Cataclysm-DDA/issues/12
https://github.com/vache/Cataclysm-DDA/issues/18

**Comment by BrianLefler** [comment]
Ok, I am removing the WIP flag because I think it is compelling enough to go in even without a grand finale, which I won't have time to implement for a while.

If there is specific content or tweaks people want to see before going live, though, I'd be happy for the feedback and could look into it.  And if someone *else* wants to implement the finale, let me know.

**Pull request merged**
