### PR TITLE
"RAW" flag which reduces calories of uncooked foods

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Balance "Raw food provides fewer calories compared to cooked"```

#### Purpose of change
Raw food takes more energy for the human digestive system to break down, and thus means less net energy. Research on the subject is still ongoing, but a 33% increase from to cooking seems a decent guess. See discussion in #34989 for more information.

#### Describe the solution
Implemented as 25% decrease to food with the "RAW" flag as compared with their JSON defined calories. When the food is cooked (used in any recipe with a heat source, or smoked on a smoking rack) this penalty is removed. Otherwise, it persists through crafting.

The "RAW" flag was added to raw meat, eggs, fruits, vegetables, nuts, and seeds.

#### Describe alternatives you've considered
None as of yet.

#### Testing
I spawned various raw items and confirmed their calories were reduced, and confirmed that they properly increased to normal levels when cooked.

One useful item to test is cattail rhizomes. They keep their RAW debuff throughout the crafting process of rhizome->starch->flour, but when baked into bread, the calories are increased by 33%.

### CODE REVIEW

**Comment by Rail-Runner** [comment]
Personally I've never heard that fruits and veggies like apples and tomatoes (that are edible and tasty raw) get more nutritious if cooked. Is it really true?

**Comment by DaviBones** [comment]
Yes, well probably. There haven't been a lot of studies to confirm or deny it (primarily due to a complete lack of interest on the topic from the scientific community, and because the only way to truly measure it is by studying the energy levels of the consumer), but [this article](https://www.pnas.org/content/108/48/19199) found that cooking food (in this case, meat and sweet potatoes) significantly increases the resultant energy levels of the mice that consumed it. There is also more theoretical discussion in a book called "Catching Fire: How Cooking Made Us Human" by Richard Wrangham. 

The upshot is that while cooking food does not directly impact the caloric content of food, it *does* make those calories more bio-available, easier for our digestive system to break down. Even fiber, which we subtract from carbohydrates before calculating calories since it's indigestible by humans, has been observed to break down into digestible carbohydrates when cooked.

Whether cooking increases the energy we get from foods like apples and tomatoes can only be speculated on, since we lack data on the subject. My thinking was that despite foods being quite different in many respects, the basic caloric compounds (fats, proteins, and carbohydrates) are the same. It stands to reason that even foods we think of as acceptable to eat raw, might become even more nutritious when cooked. This argument seemed more attractive to me than the vague argument of "it's tasty raw" (which was actually my first gut reaction), especially when every food I could think of is at least as good cooked as it is raw.

**Comment by SirPendrak** [comment]
Good, no more raw pasta eating

**Comment by Karthas077** [comment]
The only part of this I have issue with is the "Fruit" category. Putting aside the botanical definition of 'fruit', most colloquially defined fruits derive almost all of their calories from sugars, which is not made easier to digest by cooking. Certainly not to the extend that you are proposing.

Honestly, even the cooking of meat was originally done for parasite/disease reasons, and while it's almost certain our stomachs have evolved to extract nutrients more efficiently from cooked meat, a large portion of the calories come from the presence of fats/lipids which similarly are not made more or less bio-available by cooking.

You're also not making a clean distinction between the bio-availability of nutrients, and caloric value. Even if a large number of food items in the game should have their Vitamin levels adjusted by cooking, I question the validity of adjusting the calorie values.

**Comment by DaviBones** [comment]
@Karthas077 It's specifically related to the bio-availabilty of calories.  Vitamins are affected in all sorts of strange ways by cooking, and I'm not approaching that complex problem here at all. What I *am* approaching is the difference in energy levels between consumers of equal quantities of cooked and uncooked food. If you had read the study I linked, you would know that this difference has been confirmed, for, at the very least, both meat and sweet potatoes. This difference was documented for mice, who have had little to no evolutionary pressure towards digesting cooked meat.

**Comment by kevingranade** [comment]
> sugars, which is not made easier to digest by cooking

Source?

> even the cooking of meat was originally done for parasite/disease reasons, 

Source?

> large portion of the calories come from the presence of fats/lipids which similarly are not made more or less bio-available by cooking.

Source?

In short, we have a very serious study that indicates that cooking does in fact increase extractable calories in food, so that's the status quo.  In order for your assertions to be taken seriously, they need to also be appropriately sourced.

**Comment by Amoebka** [comment]
The quoted article only concern starch-reach foods and meat. Anyone extrapolating those results on all food in general without further research loses any ability to claim scientific accuracy anyway.

**Comment by DaviBones** [comment]
> 
> 
> The quoted article only concern starch-reach foods and meat. Anyone extrapolating those results on all food in general without further research loses any ability to claim scientific accuracy anyway.

I'm not claiming perfect scientific accuracy. As I discussed in my reply to Rail-Runner, I made the judgement call to make it the way it is, based on conjectural extrapolation. I also had in mind slightly easier maintainability -- it's easier to enforce "add 'RAW' flag to all raw food" than a complex set of heuristic-based rules that people will inevitably disagree on.

The PR's current state is now the "status quo," and more conjectural evidence isn't enough to supplant it; we would need an objectively *stronger* argument, not an *equivalent* one, to make any changes.

**Comment by Amoebka** [comment]
Ok, so basically YOU don't need scientific data to make an arbitrary change based on nothing but your assumptions ("extrapolation" is not an argument), but anyone trying to argue has to provide it? Seems real fair.

**Comment by DaviBones** [comment]
> 
> 
> Ok, so basically YOU don't need scientific data to make an arbitrary change based on nothing but your assumptions ("extrapolation" is not an argument), but anyone trying to argue has to provide it? Seems real fair.

I _**had**_ to make an assumption one way or the other, because I wrote the code. I went with the option that made the most sense to me. I'm not going to go back and change it unless someone offers a more compelling argument than "I don't like it this way," or I'm told I have to make changes by one of the mergers. If that seems unfair to you, I don't know what to tell you.

**Comment by Karthas077** [comment]
> > sugars, which is not made easier to digest by cooking
> 
> Source?

"Fructose exists naturally in many foods, such as fruits and vegetables. Small amounts of fructose can also be converted from sorbitol by aldose reductase. Sorbitol is also found in fruits and vegetables and as a sweetener in diet foods. However, the majority of dietary fructose comes from two sweeteners, sucrose and high fructose corn syrup (HFCS), which are commonly used in manufactured foods and beverages. Sucrose, commonly known as table sugar, is manufactured from sugar cane and sugar beet. As a disaccharide, sucrose releases equal amounts of glucose and fructose into the small intestine after being hydrolyzed by sucrase. "

https://ufdc.ufl.edu/UFE0041402/00001

The heating of sugars actually decreases their bioavailability.
"glucose and fructose react with amino acids when heated and thus participate in non-enzymatic Maillard browning reactions. These reactions generate components important for the taste, aroma, texture and appearance qualities of baked goods. The reactions also occur at the cost of losses of bioavailability of both reducing sugars and some amino acids."

https://www.longdom.org/open-access/sugar-loss-attributed-to-nonenzymatic-browning-corresponds-to-reduce-calories-recovered-in-lowmolecularweight-fraction-2155-9600-1000674.pdf

> > even the cooking of meat was originally done for parasite/disease reasons,
> 
> Source?

In retrospect I think I was actually incorrect about this one, and that trying to untangle the evolutionary pressure of fewer parasites/diseases vs easier digestion is an exercise in futility, so I'll just go ahead and accept that it's probably both.

> > large portion of the calories come from the presence of fats/lipids which similarly are not made more or less bio-available by cooking.
> 
> Source?
https://wa.kaiserpermanente.org/healthAndWellness/index.jhtml?item=%2Fcommon%2FhealthAndWellness%2Fconditions%2Fdiabetes%2FfoodBalancing.html

https://health.gov/dietaryguidelines/dga2005/document/html/chapter6.htm

and

https://www.sciencedirect.com/science/article/abs/pii/S0022286098009375

Given that meat doesn't have carbohydrates, even extremely lean meat is contributing way more calories from fat than it is from protein.

Most importantly, from the last one - "This variation in unsaturation grade and conformation provides evidence of the transformation of essential polyunsaturated fatty acids and subsequent decrease in the oils’ nutritional value."

Really it's starches and proteins that benefit from being cooked.

**Comment by DaviBones** [comment]
Thanks for the response, it is clearly well-researched! (Also, good job finding two relevant primary sources that I didn't catch.)

You make a lot of good points. I will remove the `RAW` flag from both fruits and fat shortly. It also seems evident that cooking sugars does in fact *reduce* available calories. However, implementing that would require additional C++ support, which I think makes more sense as a separate PR. That said, I may tackle it myself -- feel free to write an issue about it referencing this PR though, in case I don't get around to it.

I do have one criticism of your findings:

> Most importantly, from the last one - "This variation in unsaturation grade and conformation provides evidence of the transformation of essential polyunsaturated fatty acids and subsequent decrease in the oils’ nutritional value."

I think you might be conflating "nutritional value" with "bioavailable calories." "Nutritional value" has a very broad meaning, and I believe the way they are using it here references the fact that in their experiment, unsaturated fats are being converted to trans fats, which are strongly correlated with higher incidence of coronary artery disease. Nowhere in the article does it state or imply that bioavailable caloric energy is being lost.

Still, as I said earlier, I will remove the `RAW` flag from fat shortly, as I certainly don't see any mechanism for *increase* of bioavailable calories either.

I'm leaving the `RAW` flag on meat though, because:
- We have a primary source indicating that meat does provide more energy when cooked, and only extrapolation (however well thought-out that extrapolation may be) to the contrary.
- The status quo of not only this PR, but also master branch, is a 33% increase in calories upon cooking meat.

**Comment by anothersimulacrum** [comment]
Could you document these criteria somewhere?

**Comment by DaviBones** [comment]
Good idea, I put it in JSON_FLAGS.md, in the entry for the ```RAW``` flag. I also added a TODO to make a unit test for the criteria once fat/protein/carbs are added.

**Pull request merged**
