### PR TITLE
Integrated Toolset now has an auxiliary CBM that lets you perform item actions

### LINKED ISSUE #19489: Integrated Toolset bionic does not unlock item action menu choices
For example, the integrated toolset has a welder and solder function (based on its use in recipes), but can't be used to repair items unless you have a separate solder iron or welder to unlock the choices in the item action menu. Same for heating up food, it's not a choice unless you have a hotplate separate from your integrated toolset.

### PR DESCRIPTION
**Pull request by ghost**
I got a second monitor and I wanted to test the workflow, so I made this.

### Summary
```SUMMARY: Features "The Integrated Toolset now includes an auxiliary Extended Toolset bionic, which lets you use item actions such as sawing metal."```

### Purpose of change
Fixes #19489.

For a long time, the integrated toolset has provided full tool functionality, but hasn't let you actually use the tools except for their qualities for construction. Adding the ability to actually use them makes it more consistent and feels much better to use.

### Describe the solution
When you install an Integrated Toolset, you also gain the Extended Toolset included bionic. You can activate it to put an item into your hand (similar to how the monomolecular blade functions) that has the tool qualities of the toolset, and can be activated to do things like pry, cut, and saw metal bars.

Like other item bionics, the extended toolset can't be dropped and vanishes when you use the bionic again. Code-wise, it's considered a weapon bionic, and uses the same flags and code as the mono blade and the bionic claws.

The toolset item itself draws from your bionic power, and can be used as a soldering iron or welder to repair items. A new flag called `USES_BIONIC_POWER` lets this item (and any others someone mods in) draw from your bionic power reserves.

Includes backwards compatibility for saves that already have toolsets installed. When you deactivate a toolset, you get the extended bionic if you don't have it already.

### Describe alternatives you've considered
I was considering tying this effect to the toolset itself, but I think it would easily be an unneeded change to make the player need to hold an item in order to use the toolset. The most elegant solution seemed to be this one.

### Additional context
Bionic
Toolset item
Running on bionic power)
Item uses

### CODE REVIEW

**Comment by SirPendrak** [comment]
While this is definitelly an upgrade, i am sure you were able to do all theese things except "cauterise wound" before by using enter ->misc->item actions menu. I had my bionic preeper break into gun stores and survivor houses without any tools. And you were able to cauterise a wound if you had a steel blade that you then heated up using bionic power, but you were not able to cauterise using just your integrated soldering iron.  But what we really lack is ability to repair items using bionic power from integrated soldering iron or welder.

**Comment by Xhuis** [comment]
Those are fair points, I can take a look tomorrow.

**Comment by Xhuis** [comment]
Aw man, I thought it was a cool reference. I'll tweak it.

**Comment by Xhuis** [comment]
I changed the name to Extended Toolset.

I also managed to implement a soldering iron that runs off of bionic power. You can use the extended toolset item to repair things, and it'll draw from your energy reserves. I did this with a new flag, `USES_BIONIC_POWER`, meaning it can be put onto other items as well.

**Comment by Sirbab** [comment]
Wasn't soldering and even welding already a feature of the IT CBM?  I'm just not sure if that was known or not already given what you wrote.

**Comment by Xhuis** [comment]
They are indeed, but you can't directly use the soldering iron or welder to repair items in your inventory.

**Comment by Xhuis** [comment]
I'm about 90% sure that the security measure to apply the new bionic to old saves will work, but is there a way I can test that properly? I'm not sure how.

**Comment by Dehaku** [comment]
Does this allow heating up food and such directly as well?

**Pull request merged**
