### PR TITLE
Ammo changes

### PR DESCRIPTION
**Pull request by ghost**
Context: http://smf.cataclysmdda.com/index.php?topic=10693.0

Changes:
See commits.

### CODE REVIEW

**Comment by SpongeTheGlaive** [comment]
This is ready to merge now.

**Comment by Rivet-the-Zombie** [comment]
I guess this means I can't put off updating caseless stuff any longer.

**Comment by ejseto** [comment]
Nobody checked these numbers for consistency? .45 ACP weaker than 9mm? 10mm Auto same power as .40 S&W (short and weak)?

**Comment by SpongeTheGlaive** [comment]
@ejseto the numbers are derived from the factors listed in AMMO_STATS.txt. Other factors are not accounted for. Implement them if you see fit.

**Pull request merged**
