### PR TITLE
Added an external option to make zombies immune to bleeding

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Balance "Added an external option to make zombies immune to bleeding."

#### Purpose of change
Lore reason: zombies are explicitly stated in the lore as dead people reanimated by the Blob, and as such they are essentially dead beings. Their heart isn't working (and some zombies might even lack heart altogether due to various traumas) and isn't pumping blood as there is no need for it - the Blob is making corpses rise and walk due to its mumbo-jumbo magic, it doesn't need pity earthly mechanisms of supporting life.

Balance reason: applying direct damage to monsters due to bleeding is WAY too simplified. Creatures with such regenerative capabilities (not to mention their other paranormal abilities) such as zombies powered by the Blob shouldn't die from simple bleeding.

I understand that this PR is contradictory at best, but until we implement proper effects of monsters bleeding, I think it's better to have an option to disable the feature.

#### Describe the solution
Added an external option. Check for it in `monster::is_immune_effect` function. If `ZOMBIES_DONT_BLEED` external option is set to true (defaulted to false), and monster is zombie, make it immune to bleeding effect.

#### Describe alternatives you've considered
Replace direct damage with something less simplified, but it would be a much more work to do.

#### Testing
Turned option to false, make zombie step on a nailboard trap, make sure so they don't get bleeding effect.

#### Additional context
None.

### CODE REVIEW

**Comment by SirPendrak** [comment]
I could understand only zombies being affected by this but all monsters?

**Comment by Night-Pryanik** [comment]
Any monster that doesn't have immunity to bleeding will be affected, not only zombies.

**Comment by Zireael07** [comment]
I was thinking this would be for zombies only... maybe give 'em a flag? Because applying what is essentially movie zombie logic to all monsters is... weird...

**Comment by Night-Pryanik** [comment]
What do you mean by "movie zombie logic"? "Lose HP when you bleed"? If yes, then why do you think this logic should be restricted to zombies only?

Either all creatures (including player character and NPCs) receive direct damage when they bleed, or no one does. Our current situation is simply inconsistent. Monsters' simplicity is no excuse for them to get a completely different effect when they bleed.

**Comment by Zireael07** [comment]
I was thinking zombies don't bleed, therefore don't lose HP. So yes, "don't lose HP when bleeding" is movie zombie logic.

Monsters and NPCs have long been separate and there is no problem with monsters getting a different effect when they bleed.

**Comment by Night-Pryanik** [comment]
I don't think it's neither fun nor balanced when monsters could die by scratching themselves by the glass shard (especially when their blood doesn't flow at all - in case of zombies). It's ok that others don't agree with me on this matter, that's why I'm adding an option for it, rather than unconditionally pushing it right into the game.

**Comment by Night-Pryanik** [comment]
Warm-blooded monsters DO bleed. Zombies DO bleed too. Why only zombies shouldn't lose HP on bleeding? I just can't think of any justification on why this option should be restricted to zombies only.

**Comment by Zireael07** [comment]
Zombies DO bleed? I always thought they didn't, and that the bleeding effect applied to them was an oversight. If it's not the case, I stand corrected.

**Comment by Night-Pryanik** [comment]
Yes, zombies always had the BLEED flag, and it was always intended that they should bleed, and as @nexusmrsep said, they didn't actually bleed all this time simply because of technical limitations.

**Comment by Night-Pryanik** [comment]
Okay, reworked the option. It really feels too radical to disable HP loss due to bleeding to _all_ monsters. So I restricted the option only to zombies.
Also made the option more sensible: instead of allowing zombies to get bleeding effect and the literally do nothing, I made zombies immune to getting bleeding effect altogether with `ZOMBIES_DONT_BLEED` external option set to true (it's defaulted to false).

**Comment by kevingranade** [comment]
We need to address your points about lore and balance more directly.

1. Lorewise, vanilla zombies are nearly identical to humans, they should
bleed the same way. More evolved zombies can mitigate or lose this
vulnerability.

2. Very much in line with the lore issue, if we have monsters that are,
"too tough to be taken down by mere bleeding" then that should be reflected
in a flag that mitigates or eliminate either infliction or the impact of
blood loss.

For moddability, a set of monster flags to control blood loss is a much
more flexible system than a feature flag.

**Comment by Night-Pryanik** [comment]
I implemented this feature through the external option method simply because flag that allowed specific monster to bleed was obsoleted in #41219. If you say it's okay to return this flag and toggle bleeding through it, then I'll rework the feature through the flag.

**Comment by kevingranade** [comment]
Yes absolutely, possibly as a species flag and a per-monster flag as the
situation off the top of my head is:
Fungals should not bleed at all.
Plant monsters should leak intracellular fluid weakly.
Giant insects should leak hemolymph or possibly blood, and they have
varying degrees of clotting factor.
Mi-go...?
Robots definitely don't bleed, they might have lubricants or hydraulic
fluid, but that's very different from blood.
Weakly evolved zombies and ferals should bleed just like humans, more
evolved zombies should get better vlotting factor, bleed less, or stop
bleeding entirely.

**Pull request merged**
