### PR TITLE
Add more electric tools to mounted tool stations

### PR DESCRIPTION
**Pull request by Miner239**
#### Summary
Features "Add more electric tools to mounted tool stations"

#### Purpose of change

Now that the vehicle rigs have been split into modular tool attachments, I think it's good time to add the assorted electric tools the character can have to the allowed tools list as a quality of life improvement. Swapping batteries is pretty tiring to the player.

#### Describe the solution

Adds wire draw machine, concrete mixer, vacuum mold, angle grinder, electric shears, electric hairtrimmer, electric spinwheel, the four weed extract machines, firearm/gunsmith repair kit, circular saw, reciprocating saw, cordless impact wrench, electric polisher to the list of attachable tools for the two mounted benches.

#### Describe alternatives you've considered

Languish in the fact that I can't plug in my crafting appliances.

#### Testing

Attached hairtrimmer to mounted workshop and trimmed my hair using the tool through the mounted workshop menu. 
Attached makeshift welder to mounted workshop and repaired my car using the attached welder.
Attached electric spinwheel and successfully crafted cordage.
Attached wire draw machine and successfully crafted wire.

#### Additional context

Attempting to use makeshift welder to repair results in an error:

 DEBUG    : Empty main tool for repair

 FUNCTION : void repair_item_finish(player_activity*, Character*, bool)
 FILE     : src/activity_handlers.cpp
 LINE     : 2195
 VERSION  : 5c08c4c

Full stacktrace: [trace.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/11331278/trace.txt)

~~This error does not show up for regular arc welder. This is out of my depth to even troubleshoot, so I'll leave it to someone more capable to fix.~~ irwiss has provided a solution.

### CODE REVIEW

**Comment by GuardianDll** [comment]
#64334?

**Comment by Maddremor** [comment]
Concrete mixer and spinwheel are better off as appliances themselves than something you keep on a workbench IMO.

**Comment by Miner239** [comment]
The crafting recipes and stats for concrete mixer and electric spinwheel suggest to me that they are handheld, or at most desktop-sized, tools. 

Maybe they could be removed, replaced with an appliance counterpart, or have large versions that allows for more batch time savings? Either way, I don't think those solutions are within the scope of this PR.

**Comment by KHeket** [comment]
Can you pls also add gunsmith repair kit and firearm repair kit? Because, at least, firearm repair kit have too little charges and you need to swap batteries in it very often

**Comment by irwiss** [comment]
for makeshift welder the id needs to be hardcoded into this block to work https://github.com/CleverRaven/Cataclysm-DDA/blob/48ed876c6a1ae35d64951d99f672237580345f72/src/vehicle_use.cpp#L1702-L1708

Some tools that could also added: electric polisher, impact wrench and reciprocating saw

**Pull request merged**
