### PR TITLE
Change Lead Battery Recipie

### PR DESCRIPTION
**Pull request by Vzor-**
Lead acid batteries can be made with anything containing sulfates. Hommade battery video: https://youtu.be/C7gp3XjsH64?t=2m43s

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The numbers are all wrong: 4 acid is a whole liter of it, 4 liquid fertilizer is just a cup and 4 commercial fertilizer is 1/15 of a cup.

**Comment by Vzor-** [comment]
I just based it on the fertilizer_bomb.

**Comment by Coolthulhu** [comment]
Fertilizer bomb doesn't use them as acid, though. Considering the fertilizers in the bomb can also be used to make ANFO, it's most likely mostly nitrogen and not sulfur.

The car battery recipe is old and not really sensible (for example, it doesn't actually allow using sulfuric acid), but the new addition doesn't really improve it.

It would probably be better to have an autolearned fertilizer->sulfuric acid (or just "acid") recipe instead, then add sulfuric acid as a variant substitute for the "acid" to the battery recipe.

**Comment by Vzor-** [comment]
I don't think you could actually make fertilizer into sulfuric acid without electrolysis. It works as an electrolyte because it has a sulfate ion (epsom salt also works). I think generalizing it here is unnecessary. Just make it acid, sulfuric acid, fertilizer. Really acid is the only one that doesn't make sense. It seems strange to have specific acids like nitric and acetic along side a generic 'acid'.

**Comment by Coolthulhu** [comment]
The generic "acid" is old, before other acids were added. It could be removed, but then some other acid would need to take its place in all recipes.

**Comment by Vzor-** [comment]
Should I do another PR that includes sulfuric acid and more realistic fertilizer amounts?

**Comment by Coolthulhu** [comment]
Would be good. Preferably with the numbers being dependent on volume of substances in question.
The volume of a single charge is `1/charges` or `1/stack_size` (if stack size is specified). If charges aren't specific, it's 1.

There can be some multiplier on the charges used (say, if you assume that liquid fertilizer is mostly water and so less efficient here), but pure acid should probably be the best way to power a battery.

**Comment by Vzor-** [comment]
Ill issue a PR tomorrow when I am done with my actual work. I would like to eventually help as a minor contributor, I really enjoy this game.

**Comment by mugling** [comment]
I'm with @Coolthulhu that the numbers are incorrect. Not serious enough to warrant a revert but a little more review time would have been helpful here.

We should avoid trying to simulate chemistry perfectly:
1. Our current crafting implementation is inadequate for this (objective)
2. Would require rescaling most chemicals and resources in the game (objective)
3. Wouldn't necessarily add much to gameplay (subjective)

> pure acid should probably be the best way to power a battery

Batteries should indeed require strong acid, for which we should have three sources:

1. Scavenging (rare drop in hardware stores etc) or dismantling batteries
2. Harvested from acidic zombie corpses acid sacs (@Coolthulhus current PR)
3. From weak acid (via chemistry kit), probably with high energy requirements

Weak acids:
1. acetic acid (vinegar from fermentation) or citric acid (from farming)
2. Cleaning products found in homes
3. From water (chemistry kit with high energy requirement)

Realistically any electric vehicle is going to need a fair few batteries and allowing them to be crafted does ease this pain somewhat. In particular acid zombies would become a useful source in the early game

**Comment by Vzor-** [comment]
Well, we have to remember, these are not storage batteries. I consider a car battery to be a basic and common part and therefore should not be difficult to craft. As for realism, making fertilizer a possible ingredient is far from modeling chemistry realistically. It adds more choice and realism without adding complexity.

**Comment by mugling** [comment]
Come again? It's far from realistic but it adds more realism? It also definitely also adds complexity although that isn't necessarily a problem per-se.

**Comment by Vzor-** [comment]
It was a little contradictory. I meant adding a realistic option to a recipe isn't "modeling chemistry realistically" It's a minor change that adds depth without complexity. The recipe still takes plastic lead and an electrolyte.

**Comment by mugling** [comment]
I'm all for adding depth but that implies differing options. Fertilizer is just converting one item for another. The above changes I proposed add depth - you can scavenge, fight, farm or later on manufacture.

**Comment by Vzor-** [comment]
I do like the idea of getting acid from acidic zombies, but if generic acid is being phased out, what type of acid will it create? I don't image you are going to have nitric zombies and muriatic zombies (Now I want this).
If it is anything other than sulfuric it won't work in lead batteries. If you want to make them all work then I don't see why generic acid was replaced. I guess what I am getting at is, where is it written how realistic or unrealistic we want to go, or is it just generally understood.
I will say my favorite thing about this game is its extensive crafting system with all of its options and tools.

**Comment by mugling** [comment]
> where is it written how realistic or unrealistic we want to go, or is it just generally understood.

It's not generally understood and is indeed frequently debated on the forums.

> but if generic acid is being phased out, what type of acid will it create?

We probably just want strong acid and weak acid. The problem is uncrafting recipes which allow you to effectively perform type conversions by crafting with one component but disassembling to yield another.

> I will say my favorite thing about this game is its extensive crafting system with all of its options and tools.

We can still have depth and I agree crafting adds this. The problem is that any attempt at realistic chemistry is doomed to failure for all of the above reasons. What's important is that we have interesting mechanics.

**Pull request merged**
