### PR TITLE
[CR] Craftable aluminum ingots and aluminum tongs recipe update

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Copypasted tools requirement for ingot from lump of steel recipe, so values might need to be tweaked. Aluminum foil as component taken from aluminum powder recipe, aluminum cans as component taken from #15368.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by Darkyhard** [comment]
We would probably need steel tongs too, which could be crafted from steel, as it may be hard to collect enough aluminium to make tongs if you prefer to stay out of towns.

**Comment by Mecares** [comment]
Numbers do not make sense, an aluminium ingot has a weight of 2 kg while a aluminium can weighs only 0.01 kg and aluminium foil weighs 0.8 kg per 200 foil. This would make aluminium appear out of thin air.

**Comment by mugling** [comment]
Crafting items from aluminium: yes
Smelting aluminium: no

The reason being that smelting of bauxite ore is much more complicated than for iron ores and entirely impractical as in improvised operation. For example a major problem being that the power requirements are phenomenal.

In any case it might be interesting to have non-craftable ingots required for construction of light-weight frames. Could add a lot more depth to metallurgy. Making everything craftable adds no gameplay, merely crafting inventory spam.

**Comment by Night-Pryanik** [comment]
Well, the main reason for this PR is to ease acquiring materials needed for repairing aluminum items, not crafting them. I chose ingots for these materials in #13460. 
Maybe we should just change them to something scrap-like, like scrap metal for steel or copper scrap for copper? Maybe use aluminum cans as improvised "aluminum scrap"?

**Comment by Darkyhard** [comment]
> smelting of bauxite ore is much more complicated than for iron ores and entirely impractical as in improvised operation

Actually we don't even have possibility of smelting simple ores like iron ore now. That would probably be the first step in making it if we will ever have ore that can be smelted by player, though someone said that it's an unreasonable thing to do.

**Comment by mugling** [comment]
> Well, the main reason for this PR is to ease acquiring materials needed for repairing aluminum items

It might be worth making aluminum ingots rare spawns (warehouses, security vans, bank vaults, hardware stores etc?) and then having light-weight aluminum alternatives (with better stats) for some of the common items to offset the difficulty repairing them?

**Comment by Mecares** [comment]
I do not see a problem with aluminium items being repaired while using solder or scrap metal instead of massive ingots of aluminium.

**Comment by mugling** [comment]
> I do not see a problem with aluminium items being repaired while using solder or scrap metal instead of massive ingots of aluminium.

That's not how welding works IRL and in any case what's the point in differing metals if they don't have different mechanics?

**Comment by Mecares** [comment]
I still can imagine that this is how improvised  repairing items in a post-apocalyptic world works.

**Comment by Night-Pryanik** [comment]
> It might be worth making aluminum ingots rare spawns (warehouses, security vans, bank vaults, hardware stores etc?)

Earlier I've thought about making ingots spawn somewhere, but none of locations existing in game or any of locations suggested by you satisfy me. The only one sane location for storing ingots that comes to mind is some sort of metallurgical works - someone correct me if I'm wrong.

**Comment by mugling** [comment]
An engineering workshop or similar could be interesting? Lots of raw materials and some tools?

**Comment by Night-Pryanik** [comment]
Yeah, that's fine, but it would require to write a new mapgen template.

**Comment by kevingranade** [comment]
The primary problem with this as I understand it is the aluminum in a aluminum can is not the same as the aluminum used for structural support, so if you melt down aluminum cans and use it to solder a broken bike frame, that joint is just going to break again in short order, and you certainly couldn't cast a new frame section out of it.

Also after a quick look through the items, I don't see much of anything that:
1. incorporates aluminum
2. actually needs to be made of aluminum (a ton of things that list aluminum as a material could or should be steel, like flashlights)
3. has a need to be repairable (hotplates don't really need to be repaired)

The only exception I've run across is a combat chainsaw.  We could/should have light frames for vehicles that are made of Al and require it for repairs, but I don't think that's supported ATM.

So, what items are actually affected by this, and should they be?

**Comment by Night-Pryanik** [comment]
If only hip flask.

**Comment by Rivet-the-Zombie** [comment]
Aluminum baseball bats too.

**Comment by Night-Pryanik** [comment]
Looks like we need some sort of aluminum (or even all metals processing) overhaul.
For now I'm closing.

**Pull request closed without merging**
