### PR TITLE
Remove smartphone from urban samurai

### LINKED ISSUE #71943: Urban Samurai starts with more items than can be carried
### Describe the bug

The Urban Samurai profession outfit has no pockets, but does start with a smartphone and a bokken, which can't both be carried.

### Attach save file

N/A

### Steps to reproduce

1. Start a game as Urban Samurai
2. Wield bokken
3. You'll be prompted to drop your smartphone, because you have no pockets

### Expected behavior

Where was your bokken????

### Screenshots

_No response_

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: e5fd033 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Milopetilo**
#### Summary
None

#### Purpose of change
Closes #71943
The description does not make it feel like the person is someone who would be carrying around a smartphone.

#### Describe the solution
Remove the smartphone from the profession.

#### Testing
Game loads, profession starts without phone

### CODE REVIEW

**Comment by Zireael07** [comment]
It's pretty clearly a cyberpunk reference, so the smartphone makes sense

**Comment by Fris0uman** [comment]
We can either drop the smartphone or add a piece of equipment that could hold it. While you're there I think this sentence `Some claimed you were a visiting Shinto god.` could also go from the description, there's no way any one seeing someone dressed as a samurai in the street of New England is thinking that.

**Comment by Milopetilo** [comment]
> It's pretty clearly a cyberpunk reference, so the smartphone makes sense

I'm unsure, since the original PR that added the profession was about adding new Japanese stuff, and the PR that added the smartphone was a big audit of the character creation, so it might have been added in error.
I'm not opposed to keeping the smartphone, but I don't think there's a holder for it that would keep in theme with the traditional outfit.

**Comment by KeremBabaG** [comment]
> Some claimed you were a visiting Shinto god. could also go from the description, there's no way any one seeing someone dressed as a samurai in the street of New England is thinking that.

I think it's just a joke and not sonething literal

**Comment by Fris0uman** [comment]
Removing the profession entierly along with some other hyper-specific somewhat out of place one might happen in the future, in the mean time this seem like an acceptable fix

**Pull request merged**
