### PR TITLE
[CR] Test order randomization using a focused set of tests

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary

None

#### Purpose of change

This is a more-focused version of #46473. More specifically, it focuses on ordering of tests involved in weariness and nutrition, with more focus on the former. It includes modifications from #47653 and #47273.

#### Describe the solution

One noticeable set of tests that alter depending on ordering is those in weary_test.cpp. This PR does testing of only those, and of those plus some possibly-related nutrition tests. It rearranges what architectures/compilers some testing is run on, to allow for test failures and still get useful input, but also try to limit its occupation of PR-testing resources. It does runs both with and without rearrangement using the same seed.

#### Describe alternatives you've considered

My local computer unfortunately takes several minutes (during which its responsiveness to other commands is reduced) to even start up a world for weariness testing, making repeated test runs here painful - and, even then, uninformative on architecture/compiler differences.

#### Additional context

**_Not_** meant for merging.

### CODE REVIEW

**Comment by actual-nh** [comment]
@jbytheway: From the results of the Github matrix tests, it does not appear that the same seed is giving the same order across compilers (even 2 versions of the same compiler), even on (as far as I can tell) the same architecture. How difficult would it be to have Catch2 optionally go off of the order of tests in a file?

**Comment by jbytheway** [comment]
It is not easy to take the test order from a file. It's almost certainly easier to fix the ordering. If it's not the same for the same seeds, then that's a bug in Catch2.  There have been some changes to how the seed-based ordering works since I originally added it to Catch2, so maybe something has broken, or maybe it never worked properly...

**Comment by actual-nh** [comment]
> It is not easy to take the test order from a file. It's almost certainly easier to fix the ordering. If it's not the same for the same seeds, then that's a bug in Catch2. There have been some changes to how the seed-based ordering works since I originally added it to Catch2, so maybe something has broken, or maybe it never worked properly...

OK. (Upon looking at the Catch2 ordering code, I have confirmed that it is - unsurprisingly - beyond my (rather minimal) C++ skills to fix.) Just in case, what would the best way to check if Catch2's internal rng is generating the same sequence across compilers (and architectures)?

**Comment by jbytheway** [comment]
To debug this I'd suggest starting by getting the `TestHasher` constructor (in `catch.hpp`) to print out the value of `basis` after it's computed it.  If that value matches then the issue must be in the hashing or sorting.  If it doesn't then the issue is in the seeding or the RNG itself.  But I really can't see anything in the code that could possibly be compiler- or platform-dependent.

Are you sure you're not just seeing different interleavings of tests running in parallel and thinking that's a different order?

**Comment by actual-nh** [comment]
Gods-dammit, I'm an idiot. I'm sorry. I failed to realize that Github would be doing the matrix completely in parallel across multiple machines, INCLUDING finding out the date on different machines.

Do you happen to know whether `clara::detail::convertInto( seed, config.rngSeed );` would accept something like the sha1 commit hash, if I stuck a 0x on the front? If not, I'll check further into it.

**Comment by jbytheway** [comment]
I'd expect that it would expect a hex-formatted number.  But if it doesn't you can convert to decimal using bash
```
$ echo $((0x100))
256
```

**Comment by actual-nh** [comment]
> I'd expect that it would expect a hex-formatted number. But if it doesn't you can convert to decimal using bash
> 
> ```
> $ echo $((0x100))
> 256
> ```

It probably would accept a small hex-formatted number, but it never printed a seed when I tried one the length of a SHA hash. I wound up doing `$(( 0x3f1fabb706e42a609724c782298e0dfef85bb154 % 1000000000 ))` - one that length should work; the 1000000000 is derived from the `shuf` invocation used as a seed in another script.

**Comment by actual-nh** [comment]
Github docs was completely useless, although hopefully the documentation will be changed to reflect that GITHUB_SHA is the prior commit (making it rather useless for coordinating... sigh).

**Comment by actual-nh** [comment]
These are designed to get as much info as possible regarding the weary tests with the turn-by-turn activity measurement changes (so far rather few!) combined with #47653's weary changes.

**Comment by Night-Pryanik** [comment]
I suppose this PR is abandoned, since last commit was a year and a half ago? I'm not sure if it should stay in PR tracker, especially with this many unresolved conflicts.

**Comment by Night-Pryanik** [comment]
Closing as abandoned.

**Pull request closed without merging**
