### PR TITLE
Martial Arts Rebalance for Silat

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Silat"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Silat

#### Describe the solution

`Pentjak Silat, of Indonesian origin, is a fighting style that covers the use of short blades and bludgeons`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Silat Stance|Unarmed 0|Static Buff|+1 Dodges
Silat Counter|Unarmed 0|OnDodge Buff|Accuracy increased by 40% of Dexterity for 3 turns, stacks 4 times
Dirty Hit|Melee 1|Melee Crit Tech|Stun duration: 2
hamstring|Melee 2|Melee Crit Tech|Down duration: 3
Vicious Precision|Melee 4|Melee Crit Tech|+50% Bash, Cut, and Stab damage
Silat Brutality|Melee 3|Melee Crit Tech|Knockback distance: 1, Stun duration: 1

**Weapons:** PR-24 Baton, Bowling Pin, Combat Knife, Copper Knife, Copper Spear, Cudgel, Dive Knife, Forked Spear, Heavy Stick, Hockey Strick, Homemade Halfpike, Hunting Knife, Iron Javalin, Ironshod Quarterstaff, Glaive, Golf Club, Knife Spear, Kris*, L-strick*, Machete, Makeshift Glaive, Makeshift Knife, Makeshift Machete, Monomolecular Blade, Naginata*, No. 9*, Pipe, Pipe Spear, Pointy Stick, Pool Cue, Powered Quarterstaff, Quarterstaff, Rebar, RM42 Fighting Knife, Scimitar*, Scythe, Sharpened Rebar, Sickle, Simple Knife, Shishkebab*, Spike on a Stick, Steel Spear, Stone Knife, Survival Knife, Survivor Machete, Survivor Naginata, Switchblade, Tactical Tonfa*, Tanto*, Trench Knife, War Scythe, Wooden Javelin, Wooden Spear, Wooden Tonfa

Silat has some good points but needs a lot of work to be good. Because all the techs are critcals and you need extremely high skills in order to crit often enough to make use of the style.

_Problems and issues_
- **Every technique is a crit technique.**
This isn't a bad idea, but it needs to be executed better. You can't always crit and having multiple crit techniques can actually make it harder to get what you need when you do crit. 

- **Silat Counter gives too much Accuracy.**
Assuming the player has 10 Dexterirty, one stack of Silat Counter gives +4 Accuracy. As per [GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md),
`"Each point of to-hit is "worth" roughly a 10% increase/decrease in damage per turn or 2.5 points of damage per turn (whichever is higher)."`
Technically speaking, +4 Accuracy is a +40% damage boost. Not to mention that Silat Counter scales with Dexterirty and can stack 4 times. This means you could have +16 Accuracy at 10 Dexterity or even +32 Accuarcy  at 20 Dexterity. Clearly, this is too much.

- **Silat Stance and Silat Counter can be used without a weapon.**
While certian versions of Silat can be used unarmed, this version of Silat is weapon focused.

_Rebalance Goal_
Silat and Pentjak Silat are both umbrella terms used to describe hundreds of martial art styles that are from Brunei, Indonesia, Malaysia, Singapore, and portions of the Philippines. Narrowing down information about Silat is difficult but thankfully the style was developed using information from Wikipedia. So for my rebalance, I will focus on the aready established themes of the style:
1. Mobility is key in Silat. By added an extra Dodge attempt, this will make Silat the weapon style with the most Dodge attempts.
2. Every part of the body is subject to attack. Silat fights dirty and doesn't mind attacking below the belt. Crit techniques can be used to emphasize this idea as well.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Silat Stance|Melee 0|Static Buff|+1 Dodge atttemps
Silat Appraisal|Melee 0|OnDodge Buff|Accuracy increased by 15% of Dexterity.  Lasts 2 turns, Stacks 3 times
Hamstring|Melee 2|Melee Crit Tech|Down duration: 2
Vicious Precision|Melee 3|Melee Tech|Requires a "downed target", weighting: 2, +33% damage
Dirty Hit|Melee 4|Melee Crit Tech|Stun duration: 2
Silat Brutality|Melee 5|Melee Tech|Requires a "stunned target", weighting: 2, +33% damage

**Weapons:** PR-24 Baton, Bowling Pin, Combat Knife, Copper Knife, Copper Spear, Cudgel, Dive Knife, Forked Spear, Heavy Stick, Hockey Strick, Homemade Halfpike, Hunting Knife, Iron Javalin, Ironshod Quarterstaff, Glaive, Golf Club, Knife Spear, Kris*, L-strick*, Machete, Makeshift Glaive, Makeshift Knife, Makeshift Machete, Naginata*, No. 9*, Pipe, Pipe Spear, Pointy Stick, Pool Cue, Powered Quarterstaff, Quarterstaff, Rebar, RM42 Fighting Knife, Scimitar*, Scythe, Sharpened Rebar, Sickle, Simple Knife, Shishkebab*, Spike on a Stick, Steel Spear, Stone Knife, Survival Knife, Survivor Machete, Survivor Naginata, Switchblade, Tactical Tonfa*, Tanto*, Trench Knife, War Scythe, Wooden Javelin, Wooden Spear, Wooden Tonfa

_Important Changes_
- **Critical techniques lead to stronger techniques.**
Keeping with the theme of Silat's critical techniques being the focus of the style, the techniques now inflict status effects that trigger Silat's normal techniques. Furthermore, these conditional techniques are marked crit_ok, so they have a good chance to trigger when the conditions are met.

- **Silat Counter renamed Silat Appraisal and toned down a bit.**
As mentioned above in the issues section, this buff needed to be changed due to it granting way too much Accuracy. 15% of Dexterity as an Accuracy bonus is a fair amount for this stacking buff in my opinion.

- **Removed Monomolecular Blade as a style weapon.**
Salit is known for being able to use a very large variety of weapons but the style was never exposed to CBM weaponry and wouldn't know how to utilize it properly.

_Advantages_
- Silat can both stun and down opponents, allowing you to finish them off with high damaging techniques.
- The style has the more bonus dodge attemps that any weapon style.
- With enough Dexterirty, Silat Appraisal can generate a lot of bonus Accuracy.

_Disadvantages_
- Silat has a heavy reliance on critical hits. If you can't crit, Silat will not be very effective.
- You can't stack Silat Appraisal unless you are fighting more than one opponent.
- It takes a little while to learn all the important techniques.

#### Describe alternatives you've considered

_If the style is too strong..._
- Reduce the damage on Vicious Precision and Silat Brutality from 33% to 25%.
- Change Silat Appraisal's Accuracy bonus to +1.
- Reduce the duration of Hamstring and Dirty Hit from 2 turns to 1 turn.

_If the style is too weak..._
- Increase the damage on Vicious Precision and Silat Brutality from 33% to 50%.

#### Additional context

_References:_
[Silat wikipedia page](https://en.wikipedia.org/wiki/Silat)
[Pencak Silat wikipedia page](https://en.wikipedia.org/wiki/Pencak_Silat)

### CODE REVIEW

**Comment by SantosValourion** [comment]
I was reading this wiki page [](https://en.wikipedia.org/wiki/Weapons_of_silat),and noticed that some of the weapons they use are chains and whips. It is possible to add Steel Chain'ss and Bullwhip's to the weapon styles?

**Comment by Hymore246** [comment]
> 
> 
> I was reading this wiki page https://en.wikipedia.org/wiki/Weapons_of_silat ,and noticed that some of the weapons Silat use are chains and whips. It is possible to add Steel Chain and Bullwhip to the weapon list?
> 
> EDIT: Found some cool YouTube videos:
> Bullwhip: https://www.youtube.com/watch?v=co9_YVQpiTU
> Chain: https://www.youtube.com/watch?v=_I6gqTNp-rU (Yes the video says Kung Fu, but it would be pretty similar to Silat)

I don't think we have chains that function as weapons in-game right now. The bullwhip is a bit of a problem because the reach attack cannot trigger martial arts techniques. The player would have to melee attack with the bullwhip to use techniques and I'm not sure if it's worth adding to the style if it's limited like that.

**Comment by Noctifer-de-Mortem** [comment]
> Removed Monomolecular Blade as a style weapon.
Salit is known for being able to use a very large variety of weapons but the style was never exposed to CBM weaponry and wouldn't know how to utilize it properly

The Monomolecular Blade is still just a blade, it just happens to be built in. It's not likes it's a crazy new thing that's different, at the end of the day still just a short blade. If someone knows a martial art that uses a weapon but never personally used the weapon I wouldn't just forget how to use the style.

**Comment by LaVeyanFiend** [comment]
Wouldn't spears be removed from the weapon list since they're not "short blades and bludgeons"?

_Braces for spearmen salt at nerf_

**Comment by Hymore246** [comment]
> 
> 
> > Removed Monomolecular Blade as a style weapon.
> > Salit is known for being able to use a very large variety of weapons but the style was never exposed to CBM weaponry and wouldn't know how to utilize it properly
> 
> The Monomolecular Blade is still just a blade, it just happens to be built in. It's not likes it's a crazy new thing that's different, at the end of the day still just a short blade. If someone knows a martial art that uses a weapon but never personally used the weapon I wouldn't just forget how to use the style.

It's still different enough in function to not be included in my opinion. It's the same reason you don't see the CBM in Medieval Swordsmanship and Niten Ichi-Ryu.

> 
> 
> Wouldn't spears be removed from the weapon list since they're not "short blades and bludgeons"?
> 
> _Braces for spearmen salt at nerf_

Wikipedia mentions spears being Silat weapons. So I think they are ok keep.

**Comment by Lamandus** [comment]
To see Pencak silat in action, consider watching the Films Raid and Raid 2. Indonesian Movies with internation releases.

**Pull request merged**
