### PR TITLE
[Magiclysm] Attunements... again..

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Mods "Adding even more attunement effects"

#### Purpose of change

There is a lot of stuff that must be added to attunements. 

#### Describe the solution

Some of stuff still require work to dehardcode them, but bunch of stuff were doable using pure json

BOREAL_MAGE - got passive AoE field, that deal cold damage around, and permanent +9 cold damage in melee, and `CLIMATE_CONTROL` flag
GLACIER_MAGE - got passive small AoE field, that deal bash damage, and effect, that can knockback enemies in melee (it also must inflict `downed` status, but it doesnt work currently) (knockback itself is also buggy shit, my huge apologize to glacier players), and `CLIMATE_CONTROL` flag
VULCANIST - got a `CLIMATE_CONTROL` flag
MAGNETISM_MAGE - got some bullet damage resistance, and `SIGHT_RANGE_ELECTRIC`, which allow him to feel electric creatures (Thank you Irwiss!), and `ELECTRIC_IMMUNE` flag
TUNDRA_MAGE - got passive slowdown DoT field, and `CLIMATE_CONTROL` flag
ICE_ELEMENTAL - got +9 cold damage in melee 
CLEANSING_FLAME - got a `CLIMATE_CONTROL` flag
FIRE_ELEMENTAL - got a `CLIMATE_CONTROL` flag
STORMCALLER - got `ELECTRIC_IMMUNE` flag
STORM_ELEMENTAL - got `ELECTRIC_IMMUNE` flag
GAIAS_CHOSEN - got +30% to hp buff
EARTH_ELEMENTAL - got `ELECTRIC_IMMUNE` flag 
PERMAFROST_MAGE - got effect that substract moves from monster that try to attack user, and a `CLIMATE_CONTROL` flag
SOULFIRE - got +9 pure damage in melee 
SUN_MAGE - got `CLIMATE_CONTROL` flag
RADIATION_MAGE - got small AoE, that emit clairvoyance
ILLUSIONIST - got some social boosts
GOLEMANCER - got an ability to block minor damage monsters attack with 1/5 chance (kinda)
GRAVITY_MAGE - slightly edited his effects, added 2 new spells (accidentally, i planned to make it in separate PR, but shit happened) - gravity leap, which is a huge jump, and tactile telekinesis, which buff your melee
SHAMAN - got +40% to mana regen
WITHER_MAGE - got AoE DoT bioligical field, that damage monsters nearby, and spell, that gives small stat boosts when you fight in melee (also added +15 armor penetration using `ITEM_DAMAGE_AP`, but it doesnt work currently)
BLOOD_MAGE - got ability to heal himself for a bit when attack in melee

yeah, most temperature related attunements got `CLIMATE_CONTROL`, and all electric related got `ELECTRIC_IMMUNE`, because it feels odd to be a frozen mage and be vurnerable to cold temperatue

All AoE effects were moved to separate mutations (including existing one) to be able to turn them off (partially to prevent #55397, partially for perfomance wins when player make long term activities), and are given by using weird EoC

#### Testing

Seems good for me, but of course i can miss something

#### Additional context

Current status of attunements (imo) (aka what was left to do):

VULCANIST - 1 passive effect
ARTIFICER - 1 passive effect
TUNDRA_MAGE - 1 passive effect
CLEANSING_FLAME - 2 passive effects
STORMCALLER - 2 spells, 2 passive effects
STORM_ELEMENTAL - 1 spell, 1 passive effect
VOID_MAGE - 1 passive effect
PERMAFROST_MAGE - 1 spell, 1 passive effect
RADIATION_MAGE - 1 passive effect
FORCE_MAGE - 1 passive effect
ALCHEMIST - 2 passive effects
ILLUSIONIST - 1 spell, 1 passive effect

### CODE REVIEW

**Comment by Dan1ss1mo** [comment]
Doesnt Force mage already have 2  passive eddects: 20% speed bost and double melee damage?

**Comment by GuardianDll** [comment]
> Doesnt Force mage already have 2 passive eddects: 20% speed bost and double melee damage?

image

**Comment by Dan1ss1mo** [comment]
> > Doesnt Force mage already have 2 passive eddects: 20% speed bost and double melee damage?
> 
> image

seems like some one like forcemage a bit too much)) Graeat work btw)

**Comment by GuardianDll** [comment]
No, i just think having flat bonuses is boring. Id be glad to add some new passive stuffs for all attunements, but some of them would have been even more OP, and i want to see them in more or less equal level of coolness

**Comment by GuardianDll** [comment]
delete soul pressure and mind reading passive effect messages, because whats the reason if they require activations from now

**Comment by Light-Wave** [comment]
You might wanna check out #61139 if you haven't already

**Comment by GuardianDll** [comment]
yeah, ive seen that one, just didnt know it was merged already
but thanks for notify, ill fix the merge conflicts tomorrow

**Pull request merged**
