### PR TITLE
New Bird Mutations Attempt 2 - Mutated Emu

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Content "Adds new mutations to the Bird category and changes the category of some other bird-related mutations"```

#### Purpose of change
Bird category is a mutation category that is missing several mutations that birds have. Every animal is specialised in nature, so each animal category should have a specialised reason to go post threshold. In my opinion, birds have three main advantages in nature:

-flight
-speed, but only for flightless birds (ostriches can reach 70+ kph on the ground, and are similar heights to humans)
-beauty

#### Describe the solution
Kevin has made it clear that flight is not an option for bird mutants. So I decided to go the path of flightless bird, and give bird mutants some extra speed. I also focused on the third area they excel in, beauty.

List of Changes
-Light Eater no longer turns to gizzard. They're not mutually inclusive, and light eater has no reason to cancel gizzard
-Tough Feet added to bird category - birds have tough feet
-Glass Jaw removed from bird category, to make way for frail
-Frail added to bird category (since birds that can fly aren't very good at taking hits. If you’ve ever held a flying bird IRL you should understand what I mean.)
-Large Talons removed from bird category, because they get in the way of future additions (large talons sprout from the arms, not legs)
-Gizzard rework. Gizzards help digest food, and don't really decrease stomach size. As a result, nutrition with a gizzard is multiplied by 1.1. Gizzard is now a positive mutation and leads to Bird Crop.
-Bird Crop added. A new mutation that increases max stomach size by 120 points. Birds have crops in their neck that store ready-to-be-digested food
-Bird Wings name changed to Stiff Wings, and its benefit is the same as butterfly wings now (50% chance to negate fall damage). It also causes encumbrance and gives a little bash protection. It changes to Folding Wings post-threshold
-Folding Wings. A new post-thresh mutation that works like pre-changed Bird Wings. It negates fall damage, gives a little encumbrance when the wings are covered, and keeps STiff Wings' bash protection.
-Lilting Voice. A new pre-thresh voice mutation. It makes persuading NPCs easier, and intimidating them harder. It cancels the growling voice line, and changes to Birdsong. It's also a starting trait 
-Birdsong. Post-thresh variant of Lilting Voice, with better positives and negatives.
-Colorful Plumage. Pre-thresh mutation that makes the player prettier
-Stiff Talons. Pre-thresh mutation that restricts foot slots. It also gives a natural attack
-Flexible Talons. Post-thresh variant of Stiff Talons that no longer restricts foot slots. It also gives a natural attack if the talons are uncovered.
-Hummingbird/Pecking beak are now mixed effect mutations (they show up as purple in mutations), because they provide positive/negative effects.
-Feathered Arms. Added to Bird category, because Large Talons was removed.
-Subsonic-Sprinter. A post-threshold upgrade to Road-Runner that reduces move cost on flat ground by 40%

#### Describe alternatives you've considered
FLEET3 (Subsonic-Sprinter) is pretty OP. I wanted to make Road-Runner Bird post-thresh, but I wasn't sure how this would affect in-progress games

### CODE REVIEW

**Comment by LovamKicsiGazsii** [comment]
> Frail added to bird category since birds aren't very good at taking hits

Haven't you heard about the *Great Emu War*?

**Comment by Night-Pryanik** [comment]
> Haven't you heard about the Great Emu War?

Haven't you heard about emus _won_ the Great Emu War?

**Comment by paulenka-aleh** [comment]
While K

**Comment by paulenka-aleh** [comment]
While it make bird more attractive I wouldn't go for it without flight still. Kevin was opposed to sustainable flight and hummingbird-like flight but no againts "long jumps mostly in a straight line" or gliding down from apartment tower rooftops. Roof added and multi-store building make such jumps more and more attractive, up to point of safe travelling trough the cities with streets full of zombies.

I might be wrong but evrntually it deserves a try.

* Sorry for a bit of offtop

**Comment by EirenexTheDragon** [comment]
I welcome this! i always felt that the other mutations aint getting as much attention as the famous other ones. i am glad there are more people than just me making the other mutations more attractive aswell.

**Comment by SourSlime** [comment]
I’ve definitely heard of the great emu war now! :)

I was a little unclear in my original post, but I was referring to how frail birds that fly are. Flightless birds are pretty tough.

As for flight, Kevin did say it’s possible to do small leaps. He also said that in order to do so, bird mutants need aroubd “ encumbrance, very little carried, multiple -weight mutations and it would cost and enormous amount of food, water and stamina. Plus I’m not good enough to code that.

My goal isn’t to make Bird a fantastic category, and one worth going post-threshold in. Alpha and Medical are still way too OP for that. The point of this PR is to give Bird some missing features, and to make it not suck as much as it does.

**Comment by TechyBen** [comment]
Would stamina not balance any possibility of flight now? Though a flying human sized/weight option is rather hard (dinosaurs did it, but with massive wingspans). So we would be talking needing a tiny mutation + light bones + lots of other drawbacks to even get a few seconds of powered flight. (Haast's eagle says "hello").

**Comment by SourSlime** [comment]
Yeah, you’ve listed most of the requirements for flight to be added. Here’s a great link where Kevin outlined how it would need to work:
https://github.com/CleverRaven/Cataclysm-DDA/pull/25582#issuecomment-421539918

Adding flight would come with some huge drawbacks, and I think Kevin is right about the problems with sustained flight.

**Comment by I-am-Erk** [comment]
Are you still interested in finishing off the last bit of code cleanup and getting this merged?

**Comment by SourSlime** [comment]
Yes, but I wasn’t aware that anything still needed to be done.

**Comment by I-am-Erk** [comment]
Yep, it's got merge conflicts to be resolved in particular, and I think there were clean-up issues on top of that

**Comment by SourSlime** [comment]
Thanks, but I don't remember needing any cleanup (you might be confusing this PR with the jewelry additions). 

I think I fixed the merge conflict, but let me know if there are any more issues

**Comment by anothersimulacrum** [comment]
It looks like there are
issues

**Comment by SourSlime** [comment]
For the record, it took a little while to update so I didn't see that earlier. 

I'm closing this PR, but I'll copy the changes to a new branch.

**Pull request closed without merging**
