### PR TITLE
Tweak small/medium vehicle storage battery capacities/weights

### LINKED ISSUE #18045: Medium storage battery has a terrible storage:weight ratio
I know vehicle batteries are currently the subject of discussion and redesign, but at the moment the medium storage battery is fairly lame - twice the weight of car battery for less than a third the storage. 

Also perplexing that a full-size storage battery is the crafting equivalent of 4 medium storage batteries, but the medium size has 700 storage each to the full-size's 40k.

### PR DESCRIPTION
**Pull request by Eighth-of-Third**
The large storage battery has 40,000 capacity. It breaks down into 4 medium storage batteries, so they should each have 10,000 capacity. Medium storage batteries break down into 8 small storage batteries. If the medium storage battery has 10,000 capacity, the small storage batteries should each have 1,250 capacity. 40,000 = 4 \* 10,000 = 4 \* 8 \* 1,250

Fixes #18045

### CODE REVIEW

**Comment by pisskop** [comment]
why not just change down the storage battery?


The disparity between a standard car battery and storage batteries is real enough though

**Comment by Coolthulhu** [comment]
> It breaks down into 4 medium storage batteries, so they should each have 10,000 capacity.

Weight needs to match. The most important characteristic of batteries is storage/weight ratio.

With your change, small and medium storage batteries have much better storage to weight ratios than motorbike and car batteries. This is acceptable for the big storage battery because it weighs a ton, but the smaller ones should be in line with the big storage battery.

**Comment by Izicata** [comment]
>why not just change down the storage battery?
Because pretty much all electric vehicles use large storage batteries, and reducing its capacity would be a major nerf to electric vehicles. I'm not looking to make a huge balance change, just make the capacities consistent with what the batteries are made of.

**Comment by mugling** [comment]
> I'm not looking to make a huge balance change

But in changing storage:weight you are.

**Comment by Izicata** [comment]
>But in changing storage:weight you are.

Sure. By making medium storage batteries have 1/4 the charges and 1/4 the weight of a storage battery, instead of 1/57th the charges and 1/5th the weight, people might actually use them. Except they still won't because everyone builds 40 ton deathmobiles with 20 storage batteries. ¯\_(ツ)_/¯

**Comment by Coolthulhu** [comment]
What's the status on this? It's unmergeable, did someone fix the ratios in a different PR?

**Comment by Zireael07** [comment]
@Coolthulhu: medium storage battery had a typo in the weight (missing zero), I think, which someone else fixed.

**Comment by mugling** [comment]
> I think, which someone else fixed.

Relevant commit was 6d78b829 by @Soyweiser

**Pull request closed without merging**
