### PR TITLE
Fix some grammar

### PR DESCRIPTION
**Pull request by svenstaro**

### CODE REVIEW

**Comment by illi-kun** [comment]
I don't think you need to update *.po files manually, change only .cpp one.

**Comment by svenstaro** [comment]
Uhm but then the message id wouldn't match up.

**Comment by illi-kun** [comment]
@VlasovVitaly  periodically updates it using scripts.

**Comment by svenstaro** [comment]
Well does it hurt to just merge this as it is?

**Comment by illi-kun** [comment]
Okay, let's keep this decision to someone with merge rights.

**Comment by kevingranade** [comment]
I don't know what merging the translated files at this stage would be, so
unless we get some confirmation from one of the people working on the
transifex side of things that it would be ok, I want to only update the
.pot file.

**Comment by VlasovVitaly** [comment]
Ok. This fix can be accepted as temp workaround.
When i update pot-file id string will become normal.
When this PR will be accepted transifex and launchpad will update their
templates on next day and translators will be abble to update own
launguages.

But yes, template and translations shouldn't update by manual editing.
26 дек. 2015 г. 20:15 пользователь "Kevin Granade" <notifications@github.com>
написал:

**Pull request merged**
