### PR TITLE
Paper wrapper should have tinder flag

### PR DESCRIPTION
**Pull request by Montimorency**
#### Summary
None

#### Purpose of change
I always assumed it did - the description even indicates it - but it doesn't. 

Examples of comparable items with TINDER flag: file; paper; *lab reports, misc paper and documents*

### CODE REVIEW

**Comment by Montimorency** [comment]
Why are old, unrelated commits from another PR showing up?

**Comment by RedMisao** [comment]
Seems you're making the current PR starting from the branch you used for your previous PR, instead of a new one

**Comment by Montimorency** [comment]
But...?

**Comment by PatrikLundell** [comment]
When creating a new branch, I:
- Switch to master (if not already on it)
- Update the master branch to synchronize it to the current status
- Create the new branch
- Switch to the new branch
- (If the brain is working properly that day): Compile the code and start the game to know it worked before I started to change things
- Implement and test my changes

If you're on your previous branch when you're creating the new one you're probably going to get that branch as your starting point (which is what @RedMisao said).

**Comment by dseguin** [comment]
No worries about the commits, they'll be squashed on merge so that only the change you made gets in. Just remember to sync your master branch in the future when you create something new 👍

**Comment by Montimorency** [comment]
I think I figured out what the issue was. I had merged my branch commits into my main, so when I branched afresh from the main it inherited those commits. I see now there's an option to delete commits in the sync pulldown. 

@PatrikLundell

**Pull request merged**
