### PR TITLE
Ulysses remove cbms

### PR DESCRIPTION
**Pull request by faefux**
## Summary

SUMMARY: bugfixes "Removed CBM's from Ulysses_Rourke in anticipation for CBM's being removed as a pre-cataclysm resource."
#### Purpose of change

Ulysses Rourke has many CBM's, the exodii update will remove the idea of CBM's existing in the world pre-cataclysm.

#### Describe the solution

removed the 'bionics' list from npc.
.
#### Describe alternatives you've considered

leaving until after exodii are in.

#### Testing

removed these lines and tested on my machine was fine.

#### Additional context

It may be pertinent to delay this until exodii are in, but i could change it to [WIP] and at lest the pr's up and ready to go in that case.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Can you do a "copy-from" and "extend" to migrate this list to Aftershock? If you can't let myself or Candlebury know please so we can fix.

**Comment by Night-Pryanik** [comment]
> the exodii update will remove the idea of CBM's existing in the world pre-cataclysm.

What? Where did you get this idea?

**Comment by Broken27** [comment]
> > the exodii update will remove the idea of CBM's existing in the world pre-cataclysm.
> 
> What? Where did you get this idea?

I mean that's literally what the current design document says.

https://cataclysmdda.org/technology.html

>
Cybernetics were brought to earth after the cataclysm. A readily available CBM should not contain technology that can’t be explained by modern technology, except for the details of it being attached to the body without harm. We can handwave away neural interfacing with CBMs. Unique advanced CBMs may possess greater capabilities but access to these should be strictly gated through story advancement through one of several factions.

**Comment by Night-Pryanik** [comment]
Seems like this piece of lore was changed not so long ago, and I wasn't aware of that.

**Comment by I-am-Erk** [comment]
I would hold on on this stuff for now. There is no hurry to update things to match, and it robofac will have specific objectives related to getting CBM technology. Until we've decided how their plots will mesh, this is premature.

**Comment by John-Candlebury** [comment]
I agree with I-am-erk judgement over this. I would at the very least wait for the initial Exodii content to be fully in the game.

**Comment by faefux** [comment]
Yea that makes a lot of sense, Just thought i'd remove it when i was removing from personal npc's in anticipation of exodii.  Should i leave this up though so it's ready to go once exodii are implemented?

**Comment by ZhilkinSerg** [comment]
Let's not rush with removing CBMs. We can address this later.

**Pull request closed without merging**
