### PR TITLE
Blazemod update 2

### PR DESCRIPTION
**Pull request by chaosvolt**
Once again PR'ing it for Blaze, in case any fixes on the latest version on mediafire aren't in the github version. Additionally, made sure to retain the water tank mainlining, turret volume fixes, and mounted weapon overrides from last update.

And finally, removed the "needs a battery mount" from the mounted laser, as it would presumably break things. Also added the mounted laser rifle to overrides, which I didn't do last time because copying "NEEDS_BATTERY_MOUNT" from the other mounted laser hindered things.

### CODE REVIEW

**Comment by kevingranade** [comment]
Please double-check these for tabs, this workflow of you copying things
over means formatting errors like tab use keep getting reintroduced, at
some point blaze needs to sync from the main project, or this is going to
keep being a problem.

**Comment by DavidKeaton** [comment]
if need be a script could always be added to simple convert one `\t` into `x` spaces.

**Comment by Barhandar** [comment]
>at some point blaze needs to sync from the main project, or this is going to keep being a problem.

And set their text editor to use spaces instead of tabs so it doesn't repeat. Notepad++ can do that.

**Comment by DavidKeaton** [comment]
Most, if not all, programming editors can do that.

**Comment by chaosvolt** [comment]
Ack. Crap. Sorry, I kinda just copy-pasted Blaze's work and re-added the latest divergences.

Unfortunately that's kinda Blaze's error, if he's adding tab issues. ._.

**Comment by chaosvolt** [comment]
Okay, I'm working on fixing this myself...

**Comment by kevingranade** [comment]
> if need be a script could always be added to simple convert one \t into x
spaces.

How many spaces is x? In practice, it's either 8 or 4, unless it's
adaptive, in which case it's anything in between 1 and 8.
Basically if we could run astyle on the code in question it would sort it
out, but nothing less sophisticated than that is going to be able to fix it
without human intervention.

**Comment by chaosvolt** [comment]
It should be fixed now, plus some tabs I found that seem to have still been in the Github version.

**Comment by DavidKeaton** [comment]
where x is the number of spaces you want? I thought that was implied...

**Comment by chaosvolt** [comment]
Hmm. Somebody pester me if they find more tabs. @_@

**Comment by DavidKeaton** [comment]
an easy way to fix this is to use the search and replace function, simply change `\t` to `'    '` (4 spaces).

**Comment by chaosvolt** [comment]
Hmm, could work. Or just find in general so I ensure I give the right amount of spaces.

**Comment by DavidKeaton** [comment]
True this.

**Comment by chaosvolt** [comment]
Maybe. On it, in any case.

**Comment by chaosvolt** [comment]
I would hope that I've finally weeded out the tabs and space failures by now. <.<

**Comment by chaosvolt** [comment]
Why the hell is this giving a merge conflict NOW, and why did no one mention this?

**Comment by chaosvolt** [comment]
Augh. I've got other things to fix, we aren't really missing much if I close this.

**Pull request closed without merging**
