### PR TITLE
Give bone skewers calories

### PR DESCRIPTION
**Pull request by AudBobb**
#### Summary

Bugfixes "Give bone skewers calories"

#### Purpose of change

Noticed that bone skewers had no calories while helping unicorn work out the issues in #76999, which causes tainted bone meal crafted from them to have 0 calories. This made the game literally unplayable, so needed immediate resolution.

#### Describe the solution

I gave them 6 calories, resulting in tainted bone meal with 36 calories when crafted from them. This is one more than normal bone meal, but I don't think you can give an item fractional calories so this is the best I could do.

#### Describe alternatives you've considered

Leaving the game in an unplayable state, where tainted bone meal crafted from bone skewers had no calories. D:

#### Testing

image
resultant item from milling bone skewers

### CODE REVIEW

**Comment by AudBobb** [comment]
So the error this is running into is the recipe for making skewers from bones only gives one skewer, meaning it's losing 160ish calories. Should that be changed to give 28ish skewers (168 calories), should bone skewers get the nutrient override tag, or should this get pushed through despite that error.

Really feel like there should be a flag you can give a recipe that makes the recipe ignore ingredient calories and just give the resultant item it's default calories

**Comment by AudBobb** [comment]
Well I pushed that last commit to the wrong branch, but honestly it fits here, so if it's all good I'm gonna leave it. (I also just don't know how to revert it if I'm being honest)

This also might need to wait for #77004 to be resolved? I can't easily test the skulls calories until it's resolved, although I'm like 99% sure they are fine.

**Comment by kevingranade** [comment]
Skewers should not have calories, neither should bonemeal or other bones.  Larger bones can be assumed to have sone amount of marrow or digestible material attached to them that can be liberated by cooking or other processing, but that's not the case with skewers.

**Comment by AudBobb** [comment]
Ok, so throw this out and proceed with removing calories from bone meal and bones?

**Comment by TheMurderUnicorn** [comment]
That's what I had meant about how "adding calories to skulls shouldn't be the answer", or however I'd phrased it. I do think my issue is that the test doesn't make sense for bone meal because it shouldn't be a calorie item.  Adding calories to skulls/skewers doesn't make sense to me personally, and then trying to balance everything around how many calories of bone meal it would output also seems like the wrong answer.

**Comment by AudBobb** [comment]
Yeah, that's on me, I just blindly assumed that since someone had assigned bones and bone meal calories, they must have calories, and the obvious solution is to balance around that. Sorry for misunderstanding what you were getting at there.

**Comment by AudBobb** [comment]
Removing calories from bones looks like it would cause bone broth to need to be looked at, and with what Kevin said "or digestible material attached to them that can be liberated by cooking or other processing" I think it makes sense to leave them, so if it's agreeable, I'll just create a new PR removing the calories from bone meal, and that should resolve the issues with the milling recipes

**Comment by TheMurderUnicorn** [comment]
I was just going to wait for Karol to weigh in, my apathy has settled in after I hit the wall with the tests on what I had expected to be a dunk PR.  The only thing I saw that derives calories from bone meal was wastebread.  Bones themselves do give calories to characters with the lupine threshold (which is why they're assigned calories), I just don't know if that reasonably extends to skulls or not, or to bone meal, or etc.  Or maybe that WOULD be a reason to give bone skewers calories and I'm wrong, idk. I appreciate that you've been trying to help I just fell back to "I'm not really sure what I'm doing so I'll wait for feedback from someone who knows better than I do"

**Comment by Karol1223** [comment]
This is a horrible approach. Do not give calories to things that don't need to have calories. If the problem is in bone meal, change the bone meal - give it ``NUTRIENT_OVERRIDE``

**Pull request closed without merging**
