### PR TITLE
Alloy CBMs more protection, more mutation conflicts, added encumbrance. 

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Rebalance of Alloy Plating CBMs"

#### Purpose of change
I felt that it was odd that alloy plating CBMs didn't protect the hands and feet, and they have inconsistent effects on various mutations - you could grow a beak but not a snout, and the head plating didn't care about mutated animal ears. The level of protection they offered also felt fairly insubstantial for their difficulty of installation, rarity, and general high-techness. While they were previously a small, flat bonus at no cost whatsoever they should now be a somewhat more substantial addition with a small price to pay in permanent slight encumbrance.

#### Describe the solution
Make several changes to Alloy Plating CBMs. They now provide more protection, and provide protection to hands and feet. They also have more restrictions on mutations - all foot and hand mutations, as well as some other forgotten ones like beaks and mouth flaps for the head - and also the new Rabbit mutations. In addition, they cost slight encumbrance and cannot be removed because they have replaced your skin (updated descriptions to reflect that).

ARMS: 2 arm encumbrance, 6 arm protection, 3 hand protection, 0 hand encumbrance. Occupies 1 slot for L and R hands.
LEGS: 2 leg encumbrance, 6 leg protection, 3 foot protection, 0 foot encumbrance. Occupies 1 slot for L and R feet.
TORSO: 3 encumbrance, 7 protection.
HEAD: 2 head encumbrance, 6 mouth/head protection.
EYES: 1 encumbrance, 4 non-environmental protection (environmental protection unchanged)

#### Describe alternatives you've considered
Do nothing and wait until KorGgent's limb rework. Play with the encumbrance and protection values a little more. Make no protection/encumbrance changes and only make them conflict with the mutations.

#### Testing
Loaded up a character with all the CBMs and confirmed encumbrance and damage resistance. Unable to install these CBMs with new mutations present. Balance seems reasonable, basic zeds will often fail to pierce armor but will occasionally scratch your hands. Tough zeds can pierce your armor frequently but far less than before.

### CODE REVIEW

**Comment by Venera3** [comment]
Since trait armor has no coverage, this implicitly covers your entire hand and fingers in rigid plating, in that sense 0 hand encumberance feels too low. The same for mouth and eyes.

**Comment by anoobindisguise** [comment]
> Since trait armor has no coverage, this implicitly covers your entire hand and fingers in rigid plating, in that sense 0 hand encumberance feels too low. The same for mouth and eyes.

The idea was that previously 3-protection armor had zero encumbrance; your hands and feet get less armor specifically because their armor is more focused on flexibility.

**Comment by anoobindisguise** [comment]
I'd love to hear what else needs to be done with this PR. If it's good as is or if there are changes I still need to make to it for it to be OK to push.

**Comment by actual-nh** [comment]
For one thing, what's below the "Summary" needs to be one line saying either `None` or something like `Balance "Adjust alloy CBMs"` - this is used to create the automated changelog for releases. The rest of what's in that paragraph should be in "Purpose of change" or "Describe the solution".

**Comment by anoobindisguise** [comment]
> For one thing, what's below the "Summary" needs to be one line saying either `None` or something like `Balance "Adjust alloy CBMs"` - this is used to create the automated changelog for releases. The rest of what's in that paragraph should be in "Purpose of change" or "Describe the solution".

Got it, thanks!

**Comment by actual-nh** [comment]
For the JSON validation thing: Are you on Windows? If so, then you should be able to use the json_formatter.exe tool that comes along with CDDA; if not, you may be able to access it anyway. See doc/JSON_STYLE.md for some instructions.

**Comment by anoobindisguise** [comment]
> For the JSON validation thing: Are you on Windows? If so, then you should be able to use the json_formatter.exe tool that comes along with CDDA; if not, you may be able to access it anyway. See doc/JSON_STYLE.md for some instructions.

Yeah, I think it might be mad that I mistabbed some entries in a spot, I'll work to correct that.

**Comment by anoobindisguise** [comment]
So, thoughts on encumbrance/protection/non-removability?

**Comment by anoobindisguise** [comment]
Also, in the interest of flavor - what if the CBMs were reflavored into synthetic skin? Rather than being explicitly metal. This would solve numerous verisimilitude issues for being able to bleed and sweat through the armor plating for example. @KorGgenT intended to make these limbs truly "mechanical" with their limb rework but we're not there yet. Just a thought.

**Comment by Venera3** [comment]
Whole-body skin replacement feels more like something mutagen should handle (too many CBMs boil down to "Mutation X just better" already), from a practicability standpoint. Depending on the exact layer the plating occupies it would be possible that you'd get surface bleeds above it, so I don't think that's as big a flavor problem.

**Comment by TealcOneill** [comment]
This should probably close #45755 if it gets merged.

**Comment by Maleclypse** [comment]
Please make a copy in aftershock files that allows for removal.

**Comment by anoobindisguise** [comment]
OK, removable aftershock version is a go.

**Comment by anoobindisguise** [comment]
OK, what's left? Should encumbrance/protection values be changed? Is current encumbrance too little? What is a "realistic" amount of protection for turning your skin into metal, should basic zombies be able to pierce your skin at all? For example I could do 10 protection and 7-8 encumbrance? And lastly how do you feel about it being nonremovable - I personally like more CBMs with mixed benefits being permanent commitments but others may not share that sentiment for mainline cata.

**Comment by kevingranade** [comment]
The problem with all three of these PRs is the same, there's no real rationale here for why alloy plating (or subdermal armor mesh, or whatever it gets called) should exist in the first place, much less why it should be particularly effective.
This very much seems like something that should only be a viable option if you already discarded your skin due to going full cyborg, otherwise, just wear armor on the outside.

**Comment by anoobindisguise** [comment]
> The problem with all three of these PRs is the same, there's no real rationale here for why alloy plating (or subdermal armor mesh, or whatever it gets called) should exist in the first place, much less why it should be particularly effective.
> This very much seems like something that should only be a viable option if you already discarded your skin due to going full cyborg, otherwise, just wear armor on the outside.

Alright, so would you rather remove them outright? The plating can certainly be less effective if it isn't supposed to be particularly powerful due to logistical issues. It could be folded into subdermal carbon filament as a singular unified mutation - a full body armor sort of deal? I could work on that.
I do really like the idea of this armor totally clashing with numerous mutations though - more cbm and mutation exclusivity is a good thing.

**Comment by anoobindisguise** [comment]
Would it be better, then, for me to just leave prot at 3 and make the mutation changes only?

**Comment by anoobindisguise** [comment]
OK currently:
3 damage protection on all parts, 1 encumbrance on all parts, flavor set as "Intradermal Alloy", a mesh woven into your flesh. LMK if anything else needs done.

**Comment by anoobindisguise** [comment]
Candlebury OK'd the aftershock changes. Everything should be ready and in order now.

**Pull request merged**
