### PR TITLE
New transparent plastics, material adjustments

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Balance "Increase plastic variety, adjust plastics to be more realistic in terms of protection"

#### Purpose of change

Partially fixes issues mentioned in #66139 and comments to #66179.

#### Describe the solution

1. Split the generic plastic into household plastic with 0.5x bullet protection of current one, impact resistant transparent plastic (non-reinforced polycarb) 0.75x bullet protection of current one and plastic composite (polycarbonate composite) with 1x bullet protection of current one;
2. Buff bash resist of plastic padding. In its current state it does its job (bash protection) even worse than aramids in terms of bash protection per unit of weight/volume/mm;
3. Tone down thermoplastic resin bullet resistance. It is essentially better rigid Kevlar right now, while experimental evidence shows the opposite;
4. Nerf to ground silica glass (household glass) bullet resistance.

#### Describe alternatives you've considered

Have common household plastics be as resistant as polycarbonate safety glass. Have football helmets protect from bullets better than army helmets.

#### Testing
None for now.

#### Additional context

Why glass does not deserve 3 bullet protection:
https://www.youtube.com/watch?v=PD1vkhFO4Dg&t=420s

Pull out your napkins. The panes in question are mentioned to be 0.125 inches thick. 9 mm FMJ bullet (28 effective damage) destroyed 11. 11 panes is ~35 mm of glass, which in game translates to ~105 bullet armor (3 bullet armor per mm of glass). Meaning that in game bullet would stop at 4th pane at most. Cutting bullet res to 1 per mm produces MUCH more realistic results, making 35 mm of glass give 35 ballistic armor. If the panes were stacked back to back/there was a monolithic 35 mm thick pane in experiment, a 9mm bullet could realistically get stopped by that amount of glass. But not 4 panes of glass stopping a 9 mm round, like it is in game.

Why plastic does not deserve 2 bullet protection:
https://www.youtube.com/watch?v=OpDIoFHZfRs

Composite 3 inch glass from uparmored HMMWV (FRAG 5/6/7) stops an FMJ .50 bullet in video. When using in-game values, Barrett gives about 154 damage vs about 150 of generic plastic at 3 inch thickness. The results are close to real life, BUT: the plastic in game is supposed to be your usual everyday plastic, not composite ballistic polycarbonate specifically made to be in an armored windshield, and add in the fact the thickness itself gives some additional protective value through added rigidity (polycarb in a 20 mm thick visor wouldn't be as protective as a solid 3 inch brick of composite), and don't forget that if that 3 inch panel was worn, some energy of .50 BMG would still make it through and possibly deal some damage.

Why thermoplastic resin should not have 6 bullet resistance:
https://www.youtube.com/watch?v=TzRQgfXVdBA
https://www.youtube.com/watch?v=cVEdUl9AsR8

In both cases, a football helmet was pierced by a .22 LR rimfire cartridge (13 damage at best). At the same time, ingame football helmet provides ballistic protection that is unrealistically close to that of an army helmet on protected parts (army helmet has 31.5 bullet resistance on crown, football helmet provides 25, enough to reduce damage from 9 mm round to single digits, and fully stop anything smaller).

Non-reinforced polycarbonate should have 1.5 bullet resistance per mm per this:
https://totalshield.com/blog/polycarbonate-ballistic-performance-how-strong-is-polycarbonate/#:~:text=Ballistic%20Resistance%20Standards%3A%20The%20Bottom,357%20magnum.

1.25 inches is ~32 mm of polycarbonate, which should fully stop multiple impacts of .44 Magnum (~40 damage) per the article. So, 1-1.5 ballistic protection per mm (32 mm giving 32-48 ballistic protection) looks like a fitting value.

On the other note, 3.125 mm of tempered steel in game is ~24.3 armor, yet IRL it can withstand multiple .44 magnum shots per this resource... To fully stop a .44 Magnum shot plate of this thickness needs ~14 ballistic protection per mm.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
While we're on the subject how do you want to handle eyes encumbrance of stuff? There's a pretty big disparity between different kinds of eye protection gear in terms of encumbrance, with sunglasses, military flight helmet, light survivor mask and protective lenses being noticeably much better than ballistic glasses, safety glasses, riot helmets, motorcycle helmets, etc (which have 5 each) when all of these are pretty transparent plastic that wouldn't block FOV that much. unlike say a medieval visor, ski goggles, etc

**Comment by randomtyper** [comment]
> 

Wouldn't quite say the eye encumbrance is highly related to the issue of material protection. Imo it is a whole new issue that would entail total rebalancing of eyewear. What this PR is planning to change at most is assigning new materials where it is applicable. Like Impact Resistant Plastic to EOD visor and safety glasses.

**Comment by Maleclypse** [comment]
Is this ready for review? I noticed all its goals look to be complete? Unless I’ve misread.

**Comment by randomtyper** [comment]
> Is this ready for review? I noticed all its goals look to be complete? Unless I’ve misread.

Well, you can merge as it is, but the materials for armor will meed to be assigned in another PR then. Don't have much time for Cata right now, sadly,

**Comment by Maleclypse** [comment]
> > Is this ready for review? I noticed all its goals look to be complete? Unless I’ve misread.
> 
> Well, you can merge as it is, but the materials for armor will meed to be assigned in another PR then. Don't have much time for Cata right now, sadly,

Fair enough.  I hope life becomes easier soon :)

**Pull request merged**
