### PR TITLE
CRT Expansion Mod [WIP] [CR]

### PR DESCRIPTION
**Pull request by Soupster89**
#### Summary
```SUMMARY: Mods "A content mod pack, currently contains 2 new WIP mutation lines, 3 new martial arts, new techniques, new professions, some constructions, and new items.  "``` 
 
#### Purpose of change
This is a WIP mod pack, and some commentary would be appreciated.
CRT Expansion:
- New mutation lines: The Nightwalker, basically a Vampire of sorts. Includes some original mutations. Also the WIP Wendigo line.
- New armor sets, standard C.R.I.T equipment for and the extremely rare gas mask and transforming vest for Spec Ops division members, offers mildly OP effects in exchange for drinking UPS power/ overheating and extreme encumbrance when not powered (somewhat good for ice labs though)
-  New weapons and tools, a nightstick, hatchet, service knife, Berserk's Dragon Slayer, a different entrenching-tool and more
-  New gun mods: a new stock type, a WIP tactical flashlight (you can attach it, but can't activate it yet) and a wonky flare launcher along with a laser mod
-  New double barrel laser pistol, the damage potential is based on stacking incendiary effect rather than pure output
-  New professions to get diving in with the new content, they are OP compared to vanilla, but they all have high point costs. (6-12), also updated some scenarios to include these classes
-  New material: rubber, to really nail down a different type of material instead of just using plastic as a blanket term, I normally use it in the third material slot
- A withered plant recipe; make it from barks, pine boughs and more... really improves wilderness runs' QOL, withered plant bundle to make it compact
-  Gave grass clearing constructions a buff by making it so you can get 1 withered plant for uprooting grass, and bundle for tall grass
- New construction: A wall made of sticks and debris, not that strong and still flammable, can still put a roof over it
- New techniques to work towards giving the player more options during a fight "shoving away enemies"  Currently, vanilla tools and weapons do not have the new techniques
- The new techniques add extra depth to gameplay with new attacks, to help flush out more fighting styles than just choosing fencing to use a broadsword or Silat with quick weapons, etc.
- Techniques have stat scaling, with SS-Rank to E-Rank system for a vague gauge on their effects
- DS themed weapons and armor: the cutter, line gun, pulse rifle, a very much WIP ripper and the iconic armor

### CODE REVIEW

**Comment by KITbutler** [comment]
This looks like it should be split into several PRs with a minor followup for cross-compatibility if needed. The centipede rework is standalone except for adding in a new weapon or two. The SpecOps stuff might depend on your techniques but the reverse is definitely not true.

As for specific individual changes, why did you remove wide strike from the glaive and naginata? Actually striking *through* multiple targets is unrealistic with any weapon but others (survivor naginata) still got to keep it. The combination of leverage and a long blade is exactly what you need for wide cleaving cuts.

The "SMASH", "UNDERHAND" and especially "INERTIAL" techniques sound like quintessential mace attacks yet you added none of them to those weapons.

Even the battleaxe does not have the "CHOP" technique, what gives? Dito for the "THRUST" technique on spears and rapiers.

I would also reallocate "rapid strike" to weapons with multiple means of offense. Right now the Japanese swords tend to have it despite being curved and single-edged while double-edged cut&thrust swords *don't* even though they allow a wider range of attacks.

And I cannot be bothered to cross-check all the non-dedicated-weapon items listed in those files but I sincerely doubt you put in the effort to carefully adjust their combat stats given the above issues. Needless to say this makes the current layout incredibly cumbersome to update as your mod would overwrite future changes to any of these items.

Finally, and this goes beyond the capabilities of a JSON-only mod, instead of stuffing everything into techniques which are not displayed well in the UI I personally would prefer some fundamental adjustments to melee attacks in general first. Thrusting weapons like rapiers and spears should not be much slower due to volume while top-heavy ones like axes and maces should be significantly slower to swing than a sword of equal mass and volume. I wager that would obsolete your thrusting- and inertia-/smash-based techniques if done properly.

**Comment by Soupster89** [comment]
> This looks like it should be split into several PRs with a minor followup for cross-compatibility if needed. The centipede rework is standalone except for adding in a new weapon or two. The SpecOps stuff might depend on your techniques but the reverse is definitely not true.
> 

Ok, I'll split them into different PRs, I'm still new to gthub. The Centipede Rework is just its own standalone like you said. The core pack does use my techniques just a little bit but indeed the Extended Techniques do not really have much more interaction with the core content pack than that.

> As for specific individual changes, why did you remove wide strike from the glaive and naginata? Actually striking _through_ multiple targets is unrealistic with any weapon but others (survivor naginata) still got to keep it. The combination of leverage and a long blade is exactly what you need for wide cleaving cuts.
> 

I used an older version of Cata (Android Playstore) to write everything, which is probably why some weapons are missing their techniques, I'll pull the recent .json file next edit and put do it over.

> The "SMASH", "UNDERHAND" and especially "INERTIAL" techniques sound like quintessential mace attacks yet you added none of them to those weapons.
> 

I have not added techniques to every single weapon yet as this is still a first run to see what you guys think about the content.

> Even the battleaxe does not have the "CHOP" technique, what gives? Dito for the "THRUST" technique on spears and rapiers.
> 

I have not added techniques to every single weapon yet as this is still a first run to see what you guys think about the content.

> I would also reallocate "rapid strike" to weapons with multiple means of offense. Right now the Japanese swords tend to have it despite being curved and single-edged while double-edged cut&thrust swords _don't_ even though they allow a wider range of attacks.
> 

Sounds like a great idea, I have not given everything techniques yet or adjusted them, and Longswords do have much more techniques and attack angles than the infamous katana.

> And I cannot be bothered to cross-check all the non-dedicated-weapon items listed in those files but I sincerely doubt you put in the effort to carefully adjust their combat stats given the above issues. Needless to say this makes the current layout incredibly cumbersome to update as your mod would overwrite future changes to any of these items.
> 

I have not gone through every item yet and added techniques to the tools, but I see what you mean. I do not intend to give everything a technique as that would mess with a lot of actual weapons, but tools like the wood ax are what I would probably put a technique on. 

> Finally, and this goes beyond the capabilities of a JSON-only mod, instead of stuffing everything into techniques which are not displayed well in the UI I personally would prefer some fundamental adjustments to melee attacks in general first. Thrusting weapons like rapiers and spears should not be much slower due to volume while top-heavy ones like axes and maces should be significantly slower to swing than a sword of equal mass and volume. I wager that would obsolete your thrusting- and inertia-/smash-based techniques if done properly.

That would indeed make a lot of my stuff obolete, and I kinda wish we had a way to make it so "weapon classes" were more apparent than just adding the "SPEAR", "REACH_ATTACK", "STAB" or "UNARMED" flags to weapons to make them unique.

I honestly don't know much more about code than this because I only started messing with .json files a few months ago and most of my code is just a bunch of rehashing and pulling items with the "copy-from" function and dropping a bunch if stuff onto it to see if it works. But for a first run of this soggy mess it seems to be working, at least on my end.

I wanted to change the numbers on most weapons but that takes a bunch of time and my extended techniques are more of a rookie's blanket fix to at least add some game play that shows we are moving somewhere rather than just looking at weapons and tools that are not being updated every so often.

**Comment by KITbutler** [comment]
> I used an older version of Cata (Android Playstore) to write everything, which is probably why some weapons are missing their techniques, I'll pull the recent .json file next edit and put do it over.

If you submit something here you **ALWAYS** take the newest master branch (or maybe 0.D release branch right now for bugfixes), in fact you should update your local copy immediately before submitting a PR.

> this is still a first run to see what you guys think about the content.

In that case tag it with [WIP] so it will not get merged prematurely by accident, and also [CR] for "comments requested".

> I kinda wish we had a way to make it so "weapon classes" were more apparent than just adding the "SPEAR", "REACH_ATTACK", "STAB" or "UNARMED" flags to weapons to make them unique.

What *is* a "weapon class" though? A spear point, bayonet and the spike on a warhammer can all inflict the exact same mechanical damage to a target in the impact itself but function very differently in handling. Meanwhile a quarterstaff can be used for pretty much all techniques available with a bladed spear but is far less effective.

**Comment by Soupster89** [comment]
> In that case tag it with [WIP] so it will not get merged prematurely by accident, and also [CR] for "comments requested".
> 

How do I tag it?

> What _is_ a "weapon class" though? A spear point, bayonet and the spike on a warhammer can all inflict the exact same mechanical damage to a target in the impact itself but function very differently in handling. Meanwhile a quarterstaff can be used for pretty much all techniques available with a bladed spear but is far less effective.

In terms of "weapon class", I mean a really vague set of attacks, and of course some would overlap but still be a little different. For example, you said that the techniques of "SMASH", "UHAND" and "INERTIAL" seem like important mace techniques, and that is generally where I was going for them.

Just like how some swords have rapid attack, weapon block, vs the cudgel which is the training weapon but still has the same techniques, but offers different damage. In this case it overlaps, so I would probably tweak the cudgel in some way so it doesn't actually overshadow an actual sword.

Basic items such as a rock or a heavy stick (things in the spare parts or tool categories) generally should not have much more "power" than an actual weapon or they should at least not be really reliable in a fight, such as having a fragile melee flag or perhaps having awful accuracy or weapon use time. And we can't really put a "power level" on an item other than "early-game" or "end-game" because damage isn't really the way to go because of the item weight an all of that.

Like you said though, that would go over .json limits because weapon use time is related to the weight and changing the weight of an item breaks it in a different way.

I believe that adding new flags such as "TOP_HEAVY" (like you said for maces or axes) and "BALANCED" (such as a sword or a 2x4, as they have more uniform weight distribution) for a basic foundation on melee fixes would help do the trick as techniques and item weight changes would only go so far as you said before. Longer weapons could get some sort of different flag than just "SPEAR" or "TOP_HEAVY" so they have different movecosts.


I tried to work around this by making techniques have higher movecosts that could be toned down with the right stats (usually strength or dexterity), but then that runs into the issue of speed based traits such as "Quick" and more loosely "Deft" or even an artifact/bionic having an greater impact on fights, so the characters who already move like 10% have an even greater advantage vs those who don't have them.

Of course CDDA is about survival with a few fights to ensure you get a few supplies, but those traits make the scaling incredibly wonky because whenever I put together how movecost is calculated (or at least what I came up with) the movecost goes from "balanced" (damage to movecost ratio is close, but damage offsets movecost enough so that it still is a benefit)  to "overpowered" 

I think movecost is calculated through something like this, even though mine is probably much more primitive: (Ability Movecost - (Stat Ratio * Stat)) / Base Movespeed.

So when I do a technique which has a medium level stat ratio, a movecost of 120% and a base stat of 8 with a normal char it would be only around:
( 120 - ( 0.3 * 8 ) )  / 100  =  1.176 turns to do the technique

vs. a Quick char

( 120 - ( 0.3 * 8 ) )  / 110 = ~ 1.070 turns to do the same technique

**Comment by KITbutler** [comment]
> How do I tag it?

Just write it in the title, the actual coloured tags can only be applied by mods.

> In terms of "weapon class", I mean a really vague set of attacks, and of course some would overlap but still be a little different.

The existing system already is much better than trying to force things into rigid "classes" or categories. More tags and techniques are always nice to have of course.

> I tried to work around this by making techniques have higher movecosts that could be toned down

That falls flat with martial arts. You can't use multiple techniques simultaneously so everything you add in to un-nerf the weapon actually makes it *worse* in "skilled" hands.

**Comment by Soupster89** [comment]
> The existing system already is much better than trying to force things into rigid "classes" or categories. More tags and techniques are always nice to have of course.
> 

Alrighty, I didn't really mean that I was making everything have a rigid structure where weapons needed a "checklist" to become a certain weapon class, it was more of a way to kinda narrow down what goals we were going for in terms of improving melee fights, hence the new flags to help with that issue you were talking about.

> That falls flat with martial arts. You can't use multiple techniques simultaneously so everything you add in to un-nerf the weapon actually makes it _worse_ in "skilled" hands.

I'm confused on what you exactly mean? Also why does it fall flat with martial arts? I thought we were having the issue of martial arts being more interesting than just normal melee options. Is it because there would be too many techniques for the game to randomly select during an attack? 

I planned on making it so most weapons didn't have every technique related to that type of weapon (like every single spear having the "THRUST", "PROBE", etc) as that would clutter the weapon and the inventory UI and it would make it so different attacks wouldn't always be a technique as that would reduce the chances of a "normal" attack.

I also plan on abbreviating the stat names to just STR, DEX, PER, and INT so the UI won't be so crammed with info, not that it would polish it much, but it would just be enough to at least make it easier on the eyes.

**Comment by KITbutler** [comment]
> I'm confused on what you exactly mean? Also why does it fall flat with martial arts? I thought we were having the issue of martial arts being more interesting than just normal melee options. Is it because there would be too many techniques for the game to randomly select during an attack?

I mean *armed* martial arts. Every time a martial art technique triggers it prevents your weapon techniques reducing overall dpm. Fencing, Niten, Sojutsu and the ("official" mod) Medieval Swordsmanship *only* work with dedicated weapons or their training equivalents.

**Comment by Soupster89** [comment]
> I mean _armed_ martial arts. Every time a martial art technique triggers it prevents your weapon techniques reducing overall dpm. Fencing, Niten, Sojutsu and the ("official" mod) Medieval Swordsmanship _only_ work with dedicated weapons or their training equivalents.

Right, that makes a lot more sense.

How do I get started on making new flags and their effects?

**Comment by KITbutler** [comment]
> How do I get started on making new flags and their effects?

Those are usually coded into the main C++ functions handling whatever the flag is supposed to affect. Broader properties such as full body mutations can be spread over several files with no formal link between individual aspects.

The main ones you want to look for are "damage_melee" and "attack_time" (AKA base attack speed) in "/src/item.cpp" as well as "/src/melee.cpp" in general for fancier stuff. Not sure how elaborate it would be to add entirely new technique effects like, say, a punch that freezes the target or lights them on fire.

**Comment by Soupster89** [comment]
I opened up that file and uh... I have no idea what to do, so many lines of code and I'm already on shaky ground when it comes to C++.

**Comment by Soupster89** [comment]
I'm getting lost in the sauce here. How do I get everything in my branch to up to date with the new releases? Do I simply fork a new branch and move everything over or is there a feature that allows me to stay in touch with the master but not alter my existing files?

I keep getting an error with boots.json and I can't get through Travis because of that.

**Comment by neitsa** [comment]
I don't know if you are still working on it, but about your concern on how to update your branch with an up to date `master` it would go like this:

checkout (go to) your local `master` branch:

    $ git checkout master

Now fetch from the CDDA (origin) repository:

    $ git fetch -p origin

Rebase the changes from origin/master into your local master branch (you might `merge` instead of rebasing, but it is cleaner to rebase):

    $ git rebase origin/master

Check out the local branch you want to rebase/merge into:

    $ git checkout <your_branch>

Rebase (or merge) your now updated master branch into your local branch to update it:

    $ git rebase master

You'll probably have to resolve (a lot?) of conflicts, but it's expected and there's no way to avoid that...

**Comment by Soupster89** [comment]
> I don't know if you are still working on it, but about your concern on how to update your branch with an up to date `master` it would go like this:
> 
> checkout (go to) your local `master` branch:
> 
> ```
> $ git checkout master
> ```
> Now fetch from the CDDA (origin) repository:
> 
> ```
> $ git fetch -p origin
> ```
> Rebase the changes from origin/master into your local master branch (you might `merge` instead of rebasing, but it is cleaner to rebase):
> 
> ```
> $ git rebase origin/master
> ```
> Check out the local branch you want to rebase/merge into:
> 
> ```
> $ git checkout <your_branch>
> ```
> Rebase (or merge) your now updated master branch into your local branch to update it:
> 
> ```
> $ git rebase master
> ```
> You'll probably have to resolve (a lot?) of conflicts, but it's expected and there's no way to avoid that...

Thank you! I think I went through with merging and everything is working a lot better. Now it is mainly errors in my code that I need to sort out.

**Comment by Soupster89** [comment]
I keep getting this error in Travis called "recipe for target error" --> *my .json file" error 1.

I've looked up solutions, but I don't get most of the jargon being used. Is there some way to resolve this?
I have tried removing that file and now I am waiting for the build to finish.

It all works fine on my computer, even the most recent CDDA build operates just fine without bringing any pop-ups during mod load.

**Comment by neitsa** [comment]
In the builder log I can see this:

```
09:12:23 Validating Summary line from pull request.
09:12:23 Invalid Summary line, please provide a summary similar to the following:
09:12:23 SUMMARY: Features "Added ability to fly."
09:12:23 Makefile:1028: recipe for target 'validate-pr' failed
09:12:23 make: *** [validate-pr] Error 1
```

There's something in your summary line (first post of this PR) that prevents the build bot to validate your PR. It's probably a typographical mark that is not understood by the script in charge of validating the PR title. I don't know which one though.

I see a few possibilities:

* The summary is too long.
* Some typographical marks are not accepted.
    - maybe parenthesis (both `(` and `)` or one of them) or slash `/`.
    - comma? `,`

**Comment by Zireael07** [comment]
Commas are unlikely to be an issue. I think it's the parenthesis or the overall length.

**Comment by AMurkin** [comment]
Valid summary category is Mods.

**Comment by Soupster89** [comment]
It is now asking me to resolve a conflict from build-scripts/build.sh.

When I open it up, I don't really know what to do to fix it.

**Comment by Soupster89** [comment]
It is now asking me to resolve a conflict from build-scripts/build.sh.

When I open it up, I don't really know what to do to fix it.

**Comment by Soupster89** [comment]
I have no idea on how to fix the issue with build-scripts/build/.sh.

**Comment by Soupster89** [comment]
Do I start a new branch to make it so I don't have any master code affect my branch? I keep encountering errors from base

**Comment by Soupster89** [comment]
starting over

**Comment by neitsa** [comment]
Given the size of the PR and the modifications you're bringing in, I would advise to do an update of your repo with upstream at least once a week (if not more often) due to the rapid changes of the projects and all the PRs that are merged in.

Resolving the conflicts at least once a week would be easier than doing it once at the very end. 

Also, I think that rebasing instead of merging would give you a cleaner history, but that's just my POV.

**Pull request closed without merging**
