### PR TITLE
Giant Lithium Ion batteries aren't repairable.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
As title, dude with a soldering iron has approximately 0 chance of meaningfully repairing one of these.

#### Describe the solution
NO_REPAIR flag.

### CODE REVIEW

**Comment by esotericist** [comment]
Can we get a clarification on what exactly the intentions/expectations are here?

Why the `storage battery` object, and not medium or small versions of same? Particularly since the full size storage battery is described as an array of smaller cells, and can be crafted from the smaller variations?

Is the problem just that the items are accessible to the generalized repair code (since you mention soldering irons)? Or are we not meant to be able to repair our high density power storage at all?

**Comment by esotericist** [comment]
the copy-from bit got explained to me, that this change does affect all three. I'm still unclear on what implications this has for intention of maintainability of the resources.

**Comment by kevingranade** [comment]
> are we not meant to be able to repair our high density power storage at all?

This. To the best of my knowledge, repairing a lithium-ion battery is not at all feasible.  If you find sources that indicate otherwise please share them.

**Comment by esotericist** [comment]
> > are we not meant to be able to repair our high density power storage at all?
> 
> This. To the best of my knowledge, repairing a lithium-ion battery is not at all feasible. If you find sources that indicate otherwise please share them.

Repairing an individual cell? No. Repairing an *array* of cells? Yes, this absolutely can happen. Large size lithium-ion battery storage 'batteries' can be readily separated, and many of them use standardized cells that can be gotten all over the place. Replacing one cell with another *is* a task that can be done with a soldering iron and some expertise, and you can maintain an array quite a long time this way.

For instance, Tesla's stuff uses well-known and readily sourced cells (the 18650 is pretty easy to find right now even though it's not the 'current' cell used by their kit), although newer versions of their battery packs are more difficult to perform maintenance on (but this doesn't keep some some particularly stubborn and appropriately skilled people from doing it).

For one source, here's an example of documentation for making a battery pack using that 18650 cell. 
https://www.instructables.com/id/DIY-Professional-18650-Battery-Pack/

These can scale up pretty arbitrarily, mostly limited by your capacity to manufacture housing and manage thermal properties. At which point it just becomes 'make a few of them and separate them a bit'.

Even if the mass-produced full-sized storage batteries generated in-world aren't repairable in a direct sense (there are some things that are difficult to replicate with regards to construction without a factory), we should be able to tear them down, get some percentage of cells, and make a (less compact) equivalent with some number of working cells. Call them makeshift storage batteries, if need be, but it should still be possible.

From a gameplay standpoint: having our only high-density power storage option in-game be on a harsh entropy track while we still have issues with vehicle collisions being highly unpredictable in where damage occurs seems problematic to me.

**Comment by tenmillimaster** [comment]
Huge rechargeable battery arrays aren't typically made of giant cells, but rather smaller sub-cells. Teslas today are made with 18650 Cells, huge stacks and stacks of them. These are the cells that are commonly found in battery packs and laptop. 

Longevity and balancing issues aside, there's not too much of a reason someone couldn't : Isolate the number of cells that have failed due to damage/overdraw/overcharge, remove those from the pack, and add additional cells to bring the pack back up to nominal voltage. It's also possible to rebalance cells to match the characteristics of a pack.

https://attachments.priuschat.com/attachment-files/2017/07/129331_Prius_Cylindrical_Cell_Replacement___158.jpg
Some folks buy these prius cells on ebay to re-furbish their battery  packs.

https://i.ebayimg.com/images/g/OSkAAOSwh-1W5acD/s-l1600.jpg
Here's a tesla battery cell- it's one of the many that make up the sled the tesla is made of. 

So in practice: what I suggest- requiring small storage batteries to repair such storage batteries.

**Comment by ZhilkinSerg** [comment]
> From a gameplay standpoint: having our only high-density power storage option in-game be on a harsh entropy track while we still have issues with vehicle collisions being highly unpredictable in where damage occurs seems problematic to me.

That is a non issue: you shouldn't collide when driving your Tesla, use your road roller vehicle to crash zombies ;)

**Comment by tinukedaya** [comment]
Disassembling damaged batteries down to smaller ones will fail to recover all of them. If you want to build new big one you have to supply more form other sources... Does this not simulate perfectly the fact you need to replace the individual cells? 

The only problem here might be, that you can build the bigger batteries with damaged smaller cells.

**Comment by kevingranade** [comment]
Yes you can replace pieces of the array.  I don't think the repair action is up to doing it.

Maybe you can disassemble it to retrieve some number of cells, then reassemble the storage array with some extra cells added.  No I'm not interested in digging into this right, now, but I am interested in disabling the nonsense version of it we have right now.

**Comment by esotericist** [comment]
Understood.

**Pull request merged**
