### PR TITLE
Limit display to learned recipes only

### LINKED ISSUE #18562: Book knowledge auto-unlocked
I missed it when testing the crafting refactor.
Marking as priority since it's a pretty significant regression.

http://smf.cataclysmdda.com/index.php?topic=13354

### PR DESCRIPTION
**Pull request by mugling**
Fixes #18562

### CODE REVIEW

**Comment by codemime** [comment]
A have a suggestion concerning recipes. 

The current approach does this:
  - Constructs a [usually large] vector of data (`recipe_dict::search()` / `recipe_dict::in_category()`)
  - Filters it out using map lookup (over `player::learned_recipes`) which [in a common case] turn the vector into a small one.

This looks quite wasteful and can provoke performance losses (not a criticism of this PR since it's a quickfix, but performance is an issue for the crafting UI). 

So why don't we:

  - Apply `search()` and `in_category()` to the `learned_recipes` itself (simply iterating over the `map`)
  
There's a difficulty with `player::has_recipe_autolearned()`, but it can be overcome: 

  - Test all autolearnable recipes on each `player::set_skill_level()` (quite a rare event) and update the `learned_recipes` accordingly.

**Comment by mugling** [comment]
Yes, this is purely intended as a quick fix.

Crafting code urgently needs some attention and more eyes working on it would be beneficial - if you want to collaborate let me know the areas you want to work on so we don't end up duplicating each others work.

**Comment by codemime** [comment]
I think I'm gonna do the `has_recipe_autolearned()` part. Looks pretty easy and, along with the discrepancy, would fix an issue (is that an issue?): the player can "forget" an auto-learned recipe they once knew when they skills rust. Also, I can always review some code, but for now I don't have enough spare time to keep up your pace with big PRs.

**Comment by DangerNoodle** [comment]
What is the change here? Removing unlearned recipes from the "you could learn this" list in a book's description, or removing them from the recipe menu if they haven't been memorized?

The former would increase the need for players to metagame to figure out what books can teach them a recipe (as they can't check the books), while the latter flat-out disables book learning because that is the only way to learn recipes from books now.

**Comment by mugling** [comment]
See #18564:

> I'm going to push #18565 so that if the buildbot gives up completely after a rebase then the last available copy will include the fix.

**Comment by joeshipley** [comment]
I'm confused, if we can't ever craft a recipe from a book now, how do we ever learn those recipes? Even holding the book in hand as it is right now I can't craft anything from it. You can no longer learn a recipe by reading the book after all.

**Comment by codemime** [comment]
> I think I'm gonna do the has_recipe_autolearned() part

@mugling See #18633.

**Pull request merged**
