### PR TITLE
Updates swords to the new to-hit standard

### PR DESCRIPTION
**Pull request by Broken27**
#### Summary
Balance "Updates swords_and_blades.json to the new to-hit standard"

#### Purpose of change
Updating stuff to the new standards is good

#### Describe the solution

i changed the to-hit values of all items in swords_and_blades with the new Grip/lenght/surface/balance values

#### Describe alternatives you've considered

Not spending half an hour on this

#### Testing

Loads fine locally

#### Additional context

None

### CODE REVIEW

**Comment by I-am-Erk** [comment]
From #42961 for people like me that didn't know about the old code.

**Comment by SirPendrak** [comment]
Should knives that do stab damage have surface changed from line to point? That would be a big nerf to kombat knife tho.

**Comment by anothersimulacrum** [comment]
> Should knives that do stab damage have surface changed from line to point? That would be a big nerf to kombat knife tho.

This PR buffs the combat knife by doing exactly the opposite - it's currently to-hit value (-1) is only possible if it's balance is `point`, and this changes it to `line`.

**Comment by Broken27** [comment]
I already mentioned this in the discord, but i am strictly following the [balance](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md) document for the changes - It explicitly says knives are line weapons.

**Comment by I-am-Erk** [comment]
The expertise I gain from Google tells me that knives are primarily slashing weapons when used as a deterrent due to injury, and stabbing when used lethally. Since most of our combat is against things where pain and injury are not effective deterrents, I think we should assume knives are used as stabbing weapons primarily.

**Comment by Broken27** [comment]
> The expertise I gain from Google tells me that knives are primarily slashing weapons when used as a deterrent due to injury, and stabbing when used lethally. Since most of our combat is against things where pain and injury are not effective deterrents, I think we should assume knives are used as stabbing weapons primarily.

That seems fair enough, someone should change the balance document then

**Comment by anothersimulacrum** [comment]
@Broken27 Can you rebase this (if you don't know how, I can help)? The DPS tests need fixing, but they've changed pretty dramatically between when this PR was made and now.

**Comment by Night-Pryanik** [comment]
@Broken27 could you please resolve conflicts?

**Comment by I-am-Erk** [comment]
This is highly desired so I'm going to add this as a potential g-blocker, in the hopes someone will finish it off

**Comment by I-am-Erk** [comment]
I am moving this to a new list for abandoned PRs that are things we want, for now.

**Comment by catdach** [comment]
Seems like this was already done by #52076

**Comment by LyleSY** [comment]
Confirmed, good eye @catdach

**Pull request closed without merging**
