### PR TITLE
Clean one of the nastier hairballs out of the Makefile

### PR DESCRIPTION
**Pull request by oldlaptop**
Previously, ncursesw5-config was used for ncurses cflags/ldflags on the basis of OS detection (a nasty chain of ifeqs that boiled down to 'if not on Darwin, OSX, or BSD, use ncursesw5-config'. This diff changes it to simply use ncursesw5-config if it's present; it _needs to be tested_ on OSX and Cygwin as of this writing, but works on Linux, FreeBSD, and OpenBSD. [edit: NetBSD as well]

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm not sure if anyone is even deving on OSX :/
Let's give it some time and wait for verification of the Cygwin build, but I'd rather not hold it up if no one on OSX shows up.

**Comment by karlnp** [comment]
i was but i moved to cmake/clion as the more feasible option

**Comment by i2amroy** [comment]
Indeed, I have a Mac, but I've been waiting for CLion to give compiling on it another go since I'm much more used to developing on windows.

**Comment by Treah** [comment]
@kevingranade  I actually build on OSX just about every week to make sure the build still works and is stable. I have submitted patches in the past to assist in that. Not sure if that qualifies me as deving on OSX :P 

Ill try this build and see if it works oldlaptop

**Comment by i2amroy** [comment]
>Not sure if that qualifies me as deving on OSX :P

It certainly qualifies you to ensure that it still builds, which is what we needed here. :)

**Comment by kevingranade** [comment]
BTW, this broke on Jenkins' cross-compile for windows, so I reinstated the check for TARGETSYSTEM == LINUX, that check should probably be replaced with checking for cross-compilation somehow.
The problem was it was finding a ncurses5w-config, but it was for the build system, not the target system.
http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Windows/3416/console
http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Windows_x64/3416/console

**Comment by narc0tiq** [comment]
I think I have that resolved, running a test-compile now and will reference back if true.

**Pull request merged**
