### PR TITLE
Added message when pouring a liquid into container when parent is full.

### LINKED ISSUE #62872: Non-rigid containers in inventory don't fill up with liquids when asked to
### Describe the bug

Trying to fill up a non-rigid container in inventory transfers no liquids.

Workaround: Throw the container on the ground, fill it there, and pick it up when filled.

### Steps to reproduce

Have a huge container (`hiking backpack`) with a `gallon-sized zipper bag`
<details><summary>Get to a toilet, examine and decide to pour liquid into a container</summary>

image</details>

<details><summary>Choose yours `gallon-sized zipper bag`</summary>

image</details>

<details><summary>This message appears in the log, but no liquid is transferred!</summary>

image</details>

### Expected behavior

Firstly, the solution:
1. Calculate how much can a container be filled to still fit into ANY non-blacklisted (etc.) pocket. (If only the same pocket were checked, a `gallon-sized zipper bag` in my pans would decide to contain only 0.25 L instead of throwing it into my `hiking backpack` for full 4.5 L).
2. Fill it up.
3. Throw into a suitable pocket.

Secondly, be truthful:
If I don't fill it up, then don't tell me I did!
E. g. check for volume transferred > 0 L
And a debug warning for when this happens.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 99451f2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oosyrag**
#### Summary
None

#### Purpose of change
Resolves #62872

#### Describe the solution

Added a message "There is not enough room to add any more (liquid)." when amount to be transferred == 0. This will display upon attempting to fill the container when the parent container cannot contain any more.

I'm not familiar with C++ at all, please let me know if I did something wrong.

#### Describe alternatives you've considered

Do not have the not full, non-rigid container show up on the list of valid containers to pour into if the parent pocket of the container cannot fit any more of the liquid. Seems convoluted compared to the simple fix of just letting the player know what's going on. This alternative could also possibly cause confusion along the lines of "This container has space, why can't I choose it?"

#### Testing

Compiled and tested, looks ok. Although I'm not sure why the condom doesn't get "filled to the brim", while the gallon sized-zipper bag does.
image (1)

### CODE REVIEW

**Comment by Brambor** [comment]
Let's discuss! When condom is in small pocket, could there be msg like:
`There is not enough room to add any more %1$s. Pocket for condom is too small.`
I believe it would solve OP's concern
> This alternative could also possibly cause confusion along the lines of "This container has space, why can't I choose it?"

**Comment by oosyrag** [comment]
That's reasonable, but the current implementation doesn't actually confirm that it's because the parent pocket has no space, it just displays when nothing gets moved. I'm unfortunately a complete c++ novice so that's all I've got for now. I'll look into it though.

There's also the desire to keep the message log short and clean without too much verbosity. I'm thinking something along the lines of "(container) can't expand to add any more (liquid)" would be more precise, but sometimes a more generic statement can cover more cases. Again, I'll have to check to see what other situations might benefit from the message or if the parent container problem is the only one.

**Comment by Brambor** [comment]
Well, every container has a pocket, so if an item is in inventory it is in a pocket.
I don't know if there are cases when you cannot fill a container up because its volume is capped by **something**. And that case the **something** not being in a pocket.

It would be great to have a correct implementation with all edge cases, but if something slips, it is still better than before ;)

**Comment by Brambor** [comment]
Note the astyle error, maybe you are using different astyler?

**Comment by Brambor** [comment]
And, after astyle, you will want to squash all your commits into one. Hit me on Discord for help with that.
Or you can follow https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch

**Comment by Brambor** [comment]
@oosyrag Do you plan on finishing this up? Otherwise, I will try to pretty much copy this and make a new PR.

**Comment by oosyrag** [comment]
Oh yeah sure, I'll look into astyling properly. This was on the back burner because of string freeze right now, it won't get merged until G stable releases anyway.

**Comment by oosyrag** [comment]
Rerun tests

**Pull request merged**
