### PR TITLE
Reduce repetitive output color changes

### PR DESCRIPTION
**Pull request by sparr**
#### Summary
None

#### Purpose of change
Functions like mvwputch change the color then change it back, so calling them repeatedly, especially in a loop, results in a massive amount of duplication of effort.

#### Describe the solution
Use the non-color-changing versions of the function and specify the color explicitly before and after the loops and other calls.
I've also replaced many such loops with `mvwvline` and `mvwhline`, and added the new `mvwrectf` for 2d fill loops.

#### Testing
See comments for testing at various versions of the PR.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
@sparr care to resolve conflicts?

**Comment by sparr** [comment]
Sure, although I might abandon a few of them if the code has changed too much in the last year.

**Comment by sparr** [comment]
Working on the conflicts now. Glad to see some of the imgui stuff replacing old manually assembled UIs. Compiles are so much slower on my backup laptop :(

**Comment by NetSysFire** [comment]
You can make the github CI spit out builds for your PR, too. Simply change the branch in `.github/workflows/release.yml` in your fork and check the releases page after a while.

**Comment by Night-Pryanik** [comment]
Ok, thanks a lot! I'll see if I can find a time to test it soon.

**Pull request merged**
