### PR TITLE
Begin modeling limb loss in combat

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Begin modeling permanent loss of limbs in-game."

#### Purpose of change
I've heard this idea bounced around a few times, so I've been working up towards it with prosthetics and whatnot. This will begin modeling limb loss in-game as a result of great physical trauma and help give combat more depth and strategy, or so I hope. 

#### Describe the solution
Using an EOC, the game will check and see if one of your extremities (arms and legs) is at zero HP, and if you have not already lost it. When taking damage, you have a 5% chance for additional damage to remove that limb, where it sails off in an arc and applies profuse bleeding to your torso. If you receive sufficient medical attention within the immediate timespan, you can possibly survive this sort of thing happening, but will now have to work around (or with?) your missing limb. You do get the limb back, now modelled as an item, but there's no current way to reattach it.

#### Describe alternatives you've considered
Not doing this at all, or doubling the base HP of the player, applying the disabled status at 50% hp and then having the limb sever at 0.

#### Testing
I played around with this a good deal, it all works quite well from what I've seen.

#### Additional context
This relies on #69021 for all of the arm related things.

### CODE REVIEW

**Comment by Fris0uman** [comment]
I'm 90% sure that when we talked about limb loss in combat we decided that it's a death sentence and thus won't be in the game.

**Comment by MNG-cataclysm** [comment]
> I'm 90% sure that when we talked about limb loss in combat we decided that it's a death sentence and thus won't be in the game.

From what I remember, the idea had been tossed around before but not outright rejected, just that nobody had decided to work on it.

**Comment by kevingranade** [comment]
There are ways to accomplish it,  but "sails off in an arc" is not one of them.
It doesn't get any easier to server a limb just because the limb in question is disabled, so that part doesn't make sense either.

The absolute most common way to lose a limb due to combat (by an incredibly wide margin) would be for it to be injured and/or infected to a degree that it presents a risk of death to the character, and for the limb to be removed by a surgeon.

Game-wise amputation *in combat* wouldn't be a result of acumulation of damage,  but rather the result of a critical hit or a special attack.  Plus,  if that happens it would almost certainly be accomplished by fatal levels of blood loss,  so your chances of surviving it would be small,  and as Friz0uman points out,  most likely only occur if someone is standing by to provide first aid.

**Comment by MNG-cataclysm** [comment]
> There are ways to accomplish it,  but "sails off in an arc" is not one of them.
> 
> It doesn't get any easier to server a limb just because the limb in question is disabled, so that part doesn't make sense either.
> 
> 
> 
> The absolute most common way to lose a limb due to combat (by an incredibly wide margin) would be for it to be injured and/or infected to a degree that it presents a risk of death to the character, and for the limb to be removed by a surgeon.
> 
> 
> 
> Game-wise amputation *in combat* wouldn't be a result of acumulation of damage,  but rather the result of a critical hit or a special attack.  Plus,  if that happens it would almost certainly be accomplished by fatal levels of blood loss,  so your chances of surviving it would be small,  and as Friz0uman points out,  most likely only occur if someone is standing by to provide first aid. 

Should I redo the EOC to track damage to a limb; if a strike to it does x or greater amount of damage compared to the limb's resistance, roll a chance for it to come off?

**Comment by I-am-Erk** [comment]
To extend that, the way to start handling limb loss is probably first to work on how NPCs deliver first aid.

Alternatively, we could possible have a way to handle it by adding certain effect conditions that are treated identically to death, but actually leave a character disabled and bleeding out. Then, you'd switch to controlling a nearby NPC in your team who could then go stabilize your dying character. I've written a lot more about that [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/62349)

I don't think there's a lot of value in modeling severed limbs until we can model *surviving* severed limbs. Otherwise it's just a lot of code that basically just describes how things die in more detail.

**Comment by TheShadowFerret** [comment]
@I-am-Erk, does the lore of DDotD allow for "chop the limb to survive getting bit" or does the infection progress too fast for that to be possible?

**Comment by I-am-Erk** [comment]
> @I-am-Erk, does the lore of DDotD allow for "chop the limb to survive getting bit" or does the infection progress too fast for that to be possible?

It's not something I've really thought about at the moment since severing a limb is functionally a death sentence anyway. Maybe sometime

**Comment by Vaskritaya** [comment]
Looking at the eoc, am I correct in my understanding that this just checks that you were damaged while a limb is at 0? Assuming I'm not just extremely blind and this is already how it works, it should absolutely require some threshold of high cutting damage or very high bashing damage. Your limb just popping off because a zombie poked your for 1 would be very silly.

**Comment by MNG-cataclysm** [comment]
> To extend that, the way to start handling limb loss is probably first to work on how NPCs deliver first aid.
> 
> Alternatively, we could possible have a way to handle it by adding certain effect conditions that are treated identically to death, but actually leave a character disabled and bleeding out. Then, you'd switch to controlling a nearby NPC in your team who could then go stabilize your dying character. I've written a lot more about that [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/62349) (and edit to add that this is one of those not-too-inaccessible feature requests that I think would _massively_ improve many aspects of the game, not just this one)
> 
> I don't think there's a lot of value in modeling severed limbs until we can model _surviving_ severed limbs. Otherwise it's just a lot of code that basically just describes how things die in more detail.

Maybe we could just use this code here as a groundwork for those things, the same way #65505 allowed for most everything else regarding limbs?

**Comment by Nebnis** [comment]
Would be interesting to have this implemented due to infection much like what happens in wars. But our infections are too easy to cure unlike irl, so this feature would be pointless since you can just rub some shitty cattail jelly or alcohool dipped gazel and cure any infection. We would need to rework infection to be shallow or deep with the former being cured as it is now and the latter only with antibiotics. Failing to get an antibiotic pill in time the infected limb would become permanent thus guaranteeing death unless it is chopped off  with the help of an npc. Chances for deep and shallow could be scaled with damage from bites and such.

**Comment by keampe** [comment]
I see a lot of the argument against this pr being "death sentence if it happens" and of course that is correct - if you are human.

Ask yourself if your average mid to late game survivor really qualifies for that. Most often the answer to that is "not entirely".

From the mutation side of things: insect, spider, lizard, medical and slime, off the top of my head, may all have mutations that allow one to not only survive traumatic limb loss, but regrow the limb, especially post threshold.

From the CBM side the obvious one being Repair Nanos. These can stop bleeding or at least slow it down enough for the bleeding to be dealt with. Combine this with sensory dulling and you have someone who may remain combat capable after having an arm ripped off - as frightening as that possibility is. It is not hard to imagine other CBM's being developed for this reason. In addition, this code could also apply to bionic limbs - as in you lose them the same way from the program's point of view. This would certainly not be fatal.

Now, what happens when you combine mutation and CBM's.... It's only a flesh wound.....

Also, what is amputation? A person who traumatically loses their arm at the shoulder is likely dead without help, but what about just above the elbow? what about mid forearm? what about losing a hand at the wrist? how about losing fingers? As you go down the limb, things get easier to survive.

One other case that should be examined is that of MOD's: Aftershock, Arcana, Magiclysm and Mind over Matter all may have ways of dealing with such occurrences and it simply makes more sense to have the mechanisms for this in the base game rather than in the MOD's.

Just some thoughts - I think this is a necessary PR to be done especially for later down the road.
   - Shane

**Comment by I-am-Erk** [comment]
Shane: that's actually a good example of why we use real life as a yardstick. While it's fully possible an advanced survivor might have ways to survive limb removal, we need to first figure out what it'll do to a normal person, make that work, and *then* add ways around it. We can't first make it an arbitrarily mild injury and then nerf starting survivors as we add more details. It's bad design, frustrating for players, and leads to wild balance swings.

**Comment by MNG-cataclysm** [comment]
I'm also planning on adding bionic limbs down the road to compliment all this.

**Comment by esotericist** [comment]
this doesn't provide any gameplay opportunities that make sense, and doesn't meaningfully provide a substrate to build on that will enable any of the gameplay opportunities we're interested in.

i don't currently see a way forward where this design advances combat or health in an interesting way, and as erk noted, we wouldn't want to start here anyway.

**Comment by MNG-cataclysm** [comment]
Where would we even need to start for something like this? Could we please keep this draft open for design discussion on this issue?

**Comment by KorGgenT** [comment]
i feel like #64424 is an appropriate place to use as a jumpstart for something like this, though most amputation would be infection related and npc related

**Comment by esotericist** [comment]
@MNG-cataclysm i closed this because as kevin and erk indicated, mid combat amputation is the wrong starting place. pick an open (or even closed from stalebot, from a core team member) related design issue, start there.

**Pull request closed without merging**
