### PR TITLE
Allow long salvage with wielded and worn items

### PR DESCRIPTION
**Pull request by Coolthulhu**
As in title.

Also commented out re-setting the activity on long salvage finish. Didn't see any problems in the testing.
This results in player not being asked to confirm continuing salvaging every time a monster shows up or makes a sound, only the first time (still asks every time player is attacked/hurt).

I wanted to add long salvage with sheathed items, but it's far harder than it looks. For one, items in containers don't have inventory indices, which are required by activities.

### CODE REVIEW

**Comment by BevapDin** [comment]
> I wanted to add long salvage with sheathed items, but it's far harder than it looks. For one, items in containers don't have inventory indices, which are required by activities.

I'm wondering: do you *need* to store the tool that is used? Why not simply look it up in the inventory when it's needed (right before invoking its iuse function). It is automatically chosen anyway, whether this happens when the activity is started or when the activity is doing something shouldn't matter.

**Comment by Coolthulhu** [comment]
Could be a bit slow with large inventories. I'm getting slowdowns when building crafting inventory with 100+ items already.
While it would happen at a moment where slowdown is acceptable (player isn't queried for anything), I'd rather keep the index if it is possible.

**Comment by Coolthulhu** [comment]
OK, added support for sheathed (contained in general) knives.

A bit ugly (I'm casting away constness), but shouldn't cause much slowdown.

**Comment by Coolthulhu** [comment]
No one responded for a while, so I'll ask:
Is it OK that I cast away the constntess here or should I make an overload for `items_with` that returns non-const pointers?

**Comment by DavidKeaton** [comment]
where?

**Comment by BevapDin** [comment]
In my opinion it's fine, but go ahead and duplicate that function and add the const modifier to avoid this debate.

Actually no, don't do this. Instead use the value returned by `get_item_position` (which works fine with a const item!) and get a non-const reference to the very same item with `player::i_at`;
```C++
const item *x = ...
const int pos = u.get_item_position( x );
item &non_const = u.i_at( pos );
```

**Comment by Coolthulhu** [comment]
In #11569 I need to access items by pointers (items in containers have no inventory slots), so if I need to stop casting away constness, I need to go with the overload.

**Comment by Coolthulhu** [comment]
OK, no casting away the constness

**Comment by DavidKeaton** [comment]
still clacking away at nestable containers

**Pull request merged**
