### PR TITLE
Nerf fitting bonus at the low end.

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes a large jump in very low encumbrance as outlined in #11775

### CODE REVIEW

**Comment by DavidKeaton** [comment]
so this scales the penalty?

**Comment by kevingranade** [comment]
Yes, it only has an effect when encumbrance before fitting is under... 19, at which point it divides the value by two instead of subtracting 10.

**Comment by Coolthulhu** [comment]
A related problem:
Items that start at 0 encumbrance and are fitted get lower layering penalty. Before the nerf, there were many such items, now very few. It could be easily reclaimed by making low-encumbrance fitted items have lower layering penalty, but removing the (confusing) feature could be better.

**Comment by kevingranade** [comment]
Also the effect of the layering penalty can probably stand some scrutiny, if it scales with the items that cause it somehow, the "less layering on  fitted and 0 enc" thing can probably go away without even being missed.

**Comment by kevingranade** [comment]
Anything?  Is Coolthulu's "related problem" being taken as something this PR needs to fix?
I hope not, because I don't have a solution for that I'm happy with.

**Comment by Coolthulhu** [comment]
No, doesn't need to be here. I just wanted to bring it up.

**Comment by Rivet-the-Zombie** [comment]
We can also go over the current encumbrance values and tweak them in a separate PR.

**Comment by Coolthulhu** [comment]
The change doesn't display properly in the description: fitted hoodie has "0 (fits)", despite causing 5 encumbrance.

**Comment by Coolthulhu** [comment]
No bugs, but it needs that display change in item.cpp.
`get_encumber()` returns base encumbrance, then there's `std::max( 0, get_encumbrance() - 10 )`, which makes it display lower encumbrance for fitted items nerfed by this PR.

**Comment by kevingranade** [comment]
Yea, I'm pushing the change into item::get_encumber(), there's no reason for that adjustment to be externalized.  While I'm at it I think I'll just nuke "layers easily", while layering is worth keeping around, that isn't, at least in its current incarnation.

**Comment by DavidKeaton** [comment]
layering needs a nice overhaul, as a layering system is great, and gives reason to change the layering of items.

**Comment by kevingranade** [comment]
Should all be nice and consistent now, nothing but get_encumber() cares about adjustments to item encumbrance any more, as it should be.  Also I nuked "layers well" since it doesn't make sense right now, someone can re-add it if it makes sense later.

**Comment by Coolthulhu** [comment]
Now that the encumbrance is way higher than few months ago, it may be a good idea to consider getting rid of the whole encumbrance quantization - currently 10 torso encumbrance is far worse than 9 torso encumbrance, while 0 and 9 don't differ much.

**Pull request merged**
