### PR TITLE
More lab background tiles will match floor

### PR DESCRIPTION
**Pull request by sneeze-attack**
#### Summary
```SUMMARY: Bugfixes "More lab background tiles will match floor"```  

#### Purpose of change
Alleviates issue with lab terrain not matching surrounding floor tiles as described in #27139 

#### Describe the solution

1. Created new terrain tiles for lab which includes these IDs:
```
t_reinforced_door_glass_lab_c
t_reinforced_door_glass_lab_o
t_door_lab_c
t_door_lab_o
t_door_lab_frame
t_door_lab_b
t_mdoor_lab_frame
t_door_metal_lab_c
t_door_metal_lab_o
t_door_glass_lab_c
t_door_glass_lab_o
t_door_glass_frosted_lab_c
t_door_glass_frosted_lab_o
t_gates_mech_control_lab
t_gates_control_metal_lab
t_gates_concrete_control_lab
t_gates_concrete_brick_lab
```
2. Adjusted new terrains to have `t_thconc_floor` where possible (such as deconstructing or bashing)

3. Added new terrains to all tilesets. Used same graphic ID `t_thconc_floor` used or used `t_concrete` when `t_thconc_floor` did not have a separate graphic available.

4. Added `t_thconc_floor` and `t_strconc_floor` to any tilesets that did not already have them defined.

#### Describe alternatives you've considered
I am not aware of any alternatives to this issue

#### Additional context
Some tilesets such as Chesthole have the wooden door background filled in which prevents you from setting a background other than `t_floor`. To fix this, the png files must be edited.

Some of the mapgen in the labs appear to use `t_door_metal_c`. This appears to be hardcoded and not configurable via JSON files.

A lot of tilesets still have missing or incorrect backgrounds for items. Much of this likely needs to be fixed for the individual tileset.

### CODE REVIEW

**Comment by AMurkin** [comment]
I think you may squash some commits or even all of them to one.

**Comment by SomeDeadGuy** [comment]
Living quatters and armory in labs still have "street" concreete (the type you would see at electrical substation, for example) for the floor. And it mixed with lights tiles which is basicly lab concrete floor with the spotlight on it. Look in to it, if you can.
Otherwise - awesome additions to make labs look unique. Thank you.

**Comment by SomeDeadGuy** [comment]
nah
t_strconc_floor good for holding cells tho, and dog cages

here how it looks with my tileset

living1
living2
living3
living4
living5
living6

**Comment by sneeze-attack** [comment]
These screenshots help a lot. I'll take a second pass at the labs and reference your original issue again with the next PR. Thanks!

**Pull request merged**
