### PR TITLE
Prevent wielding items under certain conditions while driving

### PR DESCRIPTION
**Pull request by strategictraveler**
#### Summary
Balance "Wielded items behave the same as ranged weapons when driving"

#### Purpose of change

Certain ranged weapons (FIRE_TWOHAND) cannot be used when driving. This PR makes wielded two-handed items behave in the same way.

#### Describe the solution

Check if the PC is wielding a two-handed item when trying to control a vehicle. Also prevent them from picking it up when already in control.

#### Testing
Spawned a vehicle and tested it.

### CODE REVIEW

**Comment by SariusSkelrets** [comment]
IMO the player should be able to at least keep it in hand and not need to drop it. The player could have one hand holding the weapon while it is tucked between the seat and door while the other hand is holding the wheel

There can be a restriction about using the weapon, the same way two-handed guns can't be used while driving, but requiring the player to drop the weapon then pick it up every time sounds tedious, especially when most inventories can't hold long two-handed weapons

**Comment by KittyTac** [comment]
End of an era (the era of transporting fridges and cow corpses by holding them in your lap while driving).

On a serious note, I think there really needs to be a way added to transport these things by vehicle, as I understand this PR. They're larger than the largest cargo space.

**Comment by DSeyka** [comment]
> I think there really needs to be a way added to transport these things by vehicle

You can tie fridges to your vehicles if you have a long rope.

**Comment by strategictraveler** [comment]
> IMO the player should be able to at least keep it in hand and not need to drop it. The player could have one hand holding the weapon while it is tucked between the seat and door while the other hand is holding the wheel
> 
> There can be a restriction about using the weapon, the same way two-handed guns can't be used while driving, but **requiring the player to drop the weapon then pick it up every time sounds tedious, especially when most inventories can't hold long two-handed weapons**

They can still drop it on the seat. Blocking them from attacking with it could work, or I could up the moves per attack (by adding the pickup cost to every attack).

**Comment by strategictraveler** [comment]
Did some extra testing to be safe, it seems like everything works fine.

**Comment by x-qq** [comment]
This breaks an ability to transport objects with large volume, without providing any alternative, and should not be merged until such alternative exists.

**Comment by Maleclypse** [comment]
> This breaks an ability to transport objects with large volume, without providing any alternative, and should not be merged until such alternative exists.

That was never intended to work the way it currently does.  If I were trying to fix this I would look at how to model roof racks inside of our vehicle parts and pocket systems.

**Comment by x-qq** [comment]
I do not understand why you merged this without first merging such a fix.

**Comment by x-qq** [comment]
I speak of being able to transport an object >500L. Such ability was never intented to be present?

**Comment by Zireael07** [comment]
According to Maleclypse (who is one of the most active current devs) yes, not intended

**Comment by kevingranade** [comment]
Correct, dangling a huge item out the window of a car while driving was never intended to work.

**Comment by akrieger** [comment]
Or holding a 300L 200lb fridge my character could not reasonably lift much less drag while also biking a rusty commuter bike home.

**Pull request merged**
