### PR TITLE
Dragonfly naiad balance

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary

SUMMARY: None

#### Purpose of change

After some discussion I appear to have made the dragonfly naiads a bit too difficult, this PR adjusts them to be more an annoyance and less "welcome to the cattail fields, mothersurvivor".

#### Describe the solution

Decrease their health, speed, and morale, and remove the flag "swims" so they can't outrun a speedboat. Also reduce their spawn rate and pack size in both mongroups.

#### Describe alternatives you've considered

Fleshing them out a bit more with a dedicated aquatic upgrade path to have something that challenges the zhark in a lategame river. Decided to just do the quick balance PR for now, since they became a real menace.

#### Testing
Jumped around rivers and lakes, checking the spawn frequency and their hunting behavior. They can't really catch much anymore, unless their prey gets cornered and a single naiad can defeat a zombie, but not much else. 
Whacked them with a stick to check if it discourages them from trying to eat you ( it does).

#### Additional context
Thanks to curstwist for calling my attention to them and the people on reddit who gave some detailed feedback.

### CODE REVIEW

**Comment by Venera3** [comment]
I also seem to have  forgotten to give the fused dragonflies a base damge, so that's fixed now. Don't want to go too easy on you now..

**Comment by Fosheze** [comment]
I love these as a mob and the other swamp changes that you have been doing but something you may want to consider is limiting the spawning of dragonfly naiads to ponds/swamps(possibly lake shorelines too if possible)  and removing them from rivers/lakes. In reality dragonflies don't lay their eggs in quickly moving water and prefer to lay them in stagnant ponds rather than large lakes (of course these are also mutant apocalypse dragonflies so reality only applies when you feel like it). 

The main reason I say this is because as it is any lake start was impossible; seeing the ever expanding bloom of dying fish/birds and knowing your inevitable doom was near is definitely something I'll remember for a while. Even with these changes those starts will likely still be incredibly difficult considering the naiads spawn from day 1 and most survivors have to swim entirely naked until late game. Also even if the naiads aren't able to physically catch fish anymore, they will still be chasing them out of the reality bubble making massive dead zones where fishing is nearly impossible around wherever they spawned. Even if they are restricted to swamps/ponds they will still be a common threat without severely devastating the ecology. Considering the ponds spawn randomly as unmarked map extras that also gives players the opportunity to run into their scary evolved forms randomly later in the game when they are nowhere near a swamp and they think they are safe. If possible adding them to lake shorelines but not the deeper sections would also still impose their challenge upon lake start players without having the whole lake be "welcome to the cattail fields, mothersurvivor". As long as they are exclusively on shorelines then the fish populations in deeper sections of lakes will be unaffected and a lake start survivor will have a much shorter but still present death swim to reach shore (except for the man-eating beavers that is).

**Comment by Venera3** [comment]
The moving water point is obviously correct, but I felt that having them spawn in ponds/swamps doesn't really work from a game design perspective. 
In the swamps they'd only be able to poke you once and would stay confined in those 1x1 puddles (if they even get to spawn at all, since spawn coords are random and might not be in water). 
In puddles they'd just straight up murder fish that couldn't run away, and that wasn't my intention even if that's how it accidentally came out.
Rivers and lakes however offered a space for them to hunt, and those biomes are too peaceful as is unless you have an island prison nearby (then say hello to dozens of zharks on day1..).
The spawning in lakes is a bit weird, since they use the river mongroup but calculate population based on the connected lake tiles. With the new rates I needed to gen 8 lakes to have one with naiads in, so they feel much less guaranteed now. That also meant that they got considerably rarer in rivers, but that's just how it be I guess.
Them rampaging through the wildlife unabated was mostly down to their speed+swim tag, which meant that they had 150 moves a turn and moved a water tile in 50, outrunning almost everything. Thaose are now both gone, and they need a lot of luck to catch stuff.
Add to that the nerfed combat stats and I'm pretty confident they won't be any worse than say a surprise runner in the woods.

**Comment by Fosheze** [comment]
> Them rampaging through the wildlife unabated was mostly down to their speed+swim tag, which meant that they had 150 moves a turn and moved a water tile in 50, outrunning almost everything. Those are now both gone, and they need a lot of luck to catch stuff.

Ah. I had not noticed that you reduced their speed as well. That will definitely evens the playing field significantly. Also that is a good point on the ponds as well. It would make logical sense for them to spawn there but gameplay wise it would just wind up being a couple of naiads wallowing in a bunch of fresh fish corpses. I can't wait until this gets merged.

**Comment by Fosheze** [comment]
I've been playing with your proposed changes for a few days now on a lake start and everything looks good to me. The naiads do still occasionally manage to catch a fish or bird here and there but for the most part the ecological devastation has been reduced to a minimum. When I have encountered the naiads while swimming I did manage to scare them off rather easily however every time it happened I also ended up bleeding bad enough to wind up with moderate blood loss. So while they aren't lethal any more they are still scary opponents. They are also much more rare while still being just common enough to be a concern.

Over all this is a 10 out of 10 change.

**Comment by Venera3** [comment]
> I've been playing with...
Thanks so much for taking the time, earlygame balance is tricky to get right and fiddly to test.

**Pull request merged**
