### PR TITLE
Seasoned scrambled and fried eggs

### PR DESCRIPTION
**Pull request by DragonWizard23**
#### Summary
Content "Added seasoned fried and scrambled eggs"

#### Purpose of change
In real life, many people like to season their eggs. This PR adds recipes and items for fried and scrambled eggs that use seasoning. 

#### Describe the solution
I've copied the existing items recipes for fried eggs and scrambled eggs, but tweaked them to consume salt, pepper, or seasoning salt, in exchange for +3 fun compared to the base recipe. 

#### Testing
This is a JSON edit and I haven't tested it. If there are style or code errors (I promise I double-checked my code this time!), I have confidence that the automatic tests will catch them.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Testing such a change should be easy:
- Start the game (using any reasonable save)
- Debug spawn all the ingredients.
- Debug change skills if needed to gain the required cooking level.
- Debug spawn a book with the recipe if it isn't supposed to be auto learned by the cooking skill level.
- Make the dish (map editing in a suitable cooking furniture and fuel if needed).
- Verify that you didn't receive any errors and the description of the dish looks as expected by trying to eat it.

**Comment by DragonWizard23** [comment]
> Testing such a change should be easy:
> 
> * Start the game (using any reasonable save)
> * Debug spawn all the ingredients.
> * Debug change skills if needed to gain the required cooking level.
> * Debug spawn a book with the recipe if it isn't supposed to be auto learned by the cooking skill level.
> * Make the dish (map editing in a suitable cooking furniture and fuel if needed).
> * Verify that you didn't receive any errors and the description of the dish looks as expected by trying to eat it.

Thanks for the advice! I'm still painfully new to git and I don't know how to push my changes into my local cdda installation. I'm hesitant to directly edit the JSON files because I don't want to accidentally crash/corrupt my installation. 

What's the best way to accomplish this?

**Comment by PatrikLundell** [comment]
I'm afraid I'm not the best person to ask. I managed to find some instructions on how to install CDDA locally and have managed to find a small set of horrible git instructions to get it to work most of the time.
Most of the time screw ups can be recovered from by reverting the offending files before they're committed, However, I think I've had to nuke the installation twice due to some kind of git/MSVC corruption, but save files are usually not affected.

**Comment by Maleclypse** [comment]
> > Testing such a change should be easy:
> > 
> > * Start the game (using any reasonable save)
> > * Debug spawn all the ingredients.
> > * Debug change skills if needed to gain the required cooking level.
> > * Debug spawn a book with the recipe if it isn't supposed to be auto learned by the cooking skill level.
> > * Make the dish (map editing in a suitable cooking furniture and fuel if needed).
> > * Verify that you didn't receive any errors and the description of the dish looks as expected by trying to eat it.
> 
> Thanks for the advice! I'm still painfully new to git and I don't know how to push my changes into my local cdda installation. I'm hesitant to directly edit the JSON files because I don't want to accidentally crash/corrupt my installation.
> 
> What's the best way to accomplish this?

For a json only edit you can copy the two files edited directly from git and copy over the files in your installation. Or you can create a mod folder labeled changes with a modinfo file in addition to your changed files and then create a new world with that mod. Your changes should exist in the new world and you’ll be able to replace all the files in the future with different changes files as long as they are json only errors

**Pull request merged**
