### PR TITLE
The Great Vehicle Parts Adjustment

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Content "Adapts almost all vehicle definitions to use directional parts (most of the work by Curstwist)"

#### Purpose of change

#42803 made it easy to include the wide variety of vehicle parts now needed.

#### Describe the solution
@curstwist did nearly everything in this PR, I just finalized it to the vehicle parts we're currently using.
This changes all the defined vehicle parts to use left/right/front/rear designations, making vehicles all look good.
As well, mlangsdorf made a script to condense vehicle parts to fewer lines, hence the massive line count reduction.
I went through Wist's changes and have done a few small touch-ups.

#### Describe alternatives you've considered
This could be split into a dozen PRs but I'd rather we just get it done in one big ugly push.

#### Testing
I have been playing with these changes for a while, and they seem to be working OK.

https://user-images.githubusercontent.com/8007405/90534569-85129c00-e13f-11ea-8118-350db68a7566.png

Mlangsdorf and Curstwist have also playtested these pretty thoroughly.

#### Additional context
This will only work with the latest version of ultica, other tilesets won't look different.

Boats and a few other small parts have not been finished yet.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Helicopter and van-busses need linting it seems

**Comment by mlangsdorf** [comment]
```diff
diff --git a/data/json/vehicles/helicopters.json b/data/json/vehicles/helicopters.json
index 377e2b2ea9..cb1f8c108e 100644
--- a/data/json/vehicles/helicopters.json
+++ b/data/json/vehicles/helicopters.json
@@ -86,7 +86,7 @@
     "name": "Small helicopter",
     "parts": [
       { "x": 0, "y": 0, "parts": [ "frame_cross", "reclining_seat", "seatbelt", "controls" ] },
-      { "x": 0, "y": 0, "parts": [  "dashboard", "roof" ] },
+      { "x": 0, "y": 0, "parts": [ "dashboard", "roof" ] },
       { "x": 0, "y": -1, "parts": [ "frame_vertical_left", "door_nw" ] },
       { "x": 0, "y": 1, "parts": [ "frame_vertical_right", "windshield_vertical_right" ] },
       { "x": 1, "y": -1, "parts": [ "frame_vertical_T_left", "windshield_nw" ] },
diff --git a/data/json/vehicles/vans_busses.json b/data/json/vehicles/vans_busses.json
index 219a5d7778..c6a28a4f51 100644
--- a/data/json/vehicles/vans_busses.json
+++ b/data/json/vehicles/vans_busses.json
@@ -837,7 +837,7 @@
       { "x": 0, "y": 2, "parts": [ "frame_cross", "seat", "seatbelt", "roof" ] },
       { "x": 0, "y": 3, "parts": [ "frame_vertical_right", "door_front_right", "roof" ] },
       { "x": 1, "y": -1, "parts": [ "frame_vertical_T_left", "windshield_nw" ] },
-      { "x": 1,  "y": -2, "part": "wing_mirror_left" },
+      { "x": 1, "y": -2, "part": "wing_mirror_left" },
       { "x": 1, "y": 0, "parts": [ "frame_horizontal_2", "windshield_horizontal_front" ] },
       { "x": 1, "y": 1, "parts": [ "frame_horizontal_2", "windshield_horizontal_front" ] },
       { "x": 1, "y": 2, "parts": [ "frame_horizontal_2", "windshield_horizontal_front" ] },
```
two small whitespace errors, easy to fix.

**Comment by curstwist** [comment]
I've also done a lot (a lot) of in game testing on my changes, often stripping cars to the frames to check how they look (I recommend everyone strip down a semi truck cab sometime and look at those beautiful frames.  I've been playing a regular game with these changes for a few days and haven't encountered any issues (new game/new world).

**Comment by mlangsdorf** [comment]
BetterVehicles

Quick test on this morning's experimental and this JSON changes.  All the vehicles spawned without any issue, except the limo which I accidentally spawned on top of the food service truck.  That was an operator error.

**Comment by I-am-Erk** [comment]
Also I've got to go fix some mistakes in the tiles for open doors

**Pull request merged**
