### PR TITLE
Meat fixing

### LINKED ISSUE #29208: Advanced organ recipes need review
**Describe the bug**  
They take too long, consume too much heat, and lack batching
related to #28205
NEED: may need someone to run scans on the jsons to try and get a (mostly complete) list of recipes that may fall under this.  I'm guessing they're all likely to require 100 heat

**To Reproduce**  
give yourself max cooking
compare the following recipes (mentioned by @Crunchepillar in #28991 )
    cooked liver (benchmark)
    canned liver
    foie gras (consider removing or replacing with more believable variant)
    grilled sweetbread
    deviled kidney
    (and probably others)

**Expected behavior**  
food cooking should be relatively on par, with increases in time/heat/skill matching increases in stats

**Screenshots**  
ask if needed

**Versions and configuration(please complete the following information):**
 - OS: ask if needed
 - Game Version: ask if needed
 - Graphics version: ask if needed
 - Mods loaded: ask if needed

**Additional context**  
This may be a case of diversity creep.
It's fine (and even good) to have interesting variants for flavor, but they should be templated from base versions so they inherit updates and we don't have to hunt them down each time (see Cooked Liver <- Cooked Brains in offal_dishes.json for an example of this in action)

### PR DESCRIPTION
**Pull request by Xyzarach**
#### Summary

```SUMMARY: Bugfixes "fixes missing, outdated, and excessively costly meat recipes (mostly offal dishes)"```
#### Purpose of change

Fixes #29208 - adding batch craft values for advanced offal recipes and lowering surface_heat and time requirements where they seemed excessive.  
Additionally fixes a number of bugs, missing components, and obsolete recipes in a number of canned meat and offal recipes. 

#### Describe the solution

In addition to adding a batch time factor and lowering the surface_heat and time requirements for the advanced offal recipes, the branch contains the following fixes:

Fixed a bug in wasteland sausage where crafting them raw would only give one portion instead of the two given by smoking them at the same time.

Adds scrap of meat to the 4 canned and pickled meat recipes that it was missing from. Getting rid of hundreds of meat scraps at a time will be much simpler now that you can cram them all in a 3L jar with some vinegar.

Fixed a missing id suffix that was preventing a version of the canned liver recipe from showing up properly in the crafting menu.

Removed obsolete version of the cooked sweetbread recipe and the cooked offal recipe, as raw offal can no longer be harvested.

Opted not to remove the canned and pickled offal recipes, instead updated them to use some of the new offal type items. 
.
One new piece of content. While looking up real world recipes and cooking instructions for tripe as part of fixing issue 29208, I found that fried tripe actually had a longer raw ingredients to finished food prep and cooking time than the already excessive cook time in game. To fix this without making a recipe that would take two hours to cook and only have role play benefit for the cost, I split the recipe across three steps: parboiling (the already existing boiled stomach recipes), stewing (a new recipe that takes boiled stomachs and broth ingredients, but pays out extra broth as a byproduct), and deep frying (the original recipe, time cut to 15 minutes and with stewed tripe used instead of the raw stomach).

#### Describe alternatives you've considered

N/A
#### Additional context

The wikihow article I based the new tripe recipes off of: https://www.wikihow.com/Cook-Beef-Tripe

### CODE REVIEW

**Comment by KorGgenT** [comment]
you need to lint this http://dev.narc.ro/cataclysm/format.html

**Comment by ZhilkinSerg** [comment]
Comestible test is failing now:
```
comestible_tests.cpp:118
...............................................................................
comestible_tests.cpp:148: FAILED:
  CHECK( mystats.calories.avg() < upper_bound )
with expansion:
  1073.3 < 870.13989f
```

**Comment by KorGgenT** [comment]
> Comestible test is failing now:
> 
> ```
> comestible_tests.cpp:118
> ...............................................................................
> comestible_tests.cpp:148: FAILED:
>   CHECK( mystats.calories.avg() < upper_bound )
> with expansion:
>   1073.3 < 870.13989f
> ```

relevent recipe is the fried tripe recipe.
you need to reduce the kcal of the ingredients.

**Comment by Xyzarach** [comment]
Ah, sorry, didn't see your comment until I'd already pushed a different change. Going to wait and see if what I thought I'd messed up fixes it or not, then I'll commit your suggestion if it doesn't.

**Comment by KorGgenT** [comment]
it's definitely possible that changing the charges of the actual item will fix it. will wait for travis for further input.

**Comment by Rivet-the-Zombie** [comment]
Will this allow us to make meat scraps into stuff like jerky, dehydrated, and smoked meats?

**Comment by Xyzarach** [comment]
I didn't touch dehydrated or smoked meat because I remembered hearing something about issues with scraps and the smoking rack, and I didn't notice that jerky didn't take scraps or I probably would have already put that in. 

It having been brought up though, from the info in game on those items, and what little real world experience I've got with them, you definitely should be able to make any of those by hand through the crafting menu, so I'll put that in.

**Pull request merged**
