### PR TITLE
Add placeable Washing Machine item

### PR DESCRIPTION
**Pull request by definitelynotklip**
#### Summary
Content "Adds an item that allows you to easily carry and place existing washing machine furniture."

#### Purpose of change

This change introduces a way to haul an intact washing machine back to base in order to decorate your bathroom or basement. It can also be used to store items. Instead of (`*`) Deconstructing the item into materials, you now (`*`) Deconstruct it into a new item called "household washing machine" (**not to be confused with the craftable "washing machine" vehicle part**).

This item can then be (`a`)ctivated to be placed back down as the physical washing machine object. (`(`) Disassembling it instead yields the old deconstruction material results such as cables, pipes etc.

This change also switches the volume and weight attributes between the "household washing machine" and the "washing machine" vehicle part, as the latter is described being noticeably smaller and lighter yet it was 6 times as large and 3 times as heavy.

#### Testing

Fully tested on a local copy of version a27f801 (Experimental, July 18th). Spawned a washing machine, (`*`) Deconstructed it to the new item, then either (`a`)ctivated it to place it back or (`(`) Disassembled it for the old part list. Everything works as intended.

### CODE REVIEW

**Comment by eltank** [comment]
So with this change it's no longer possible to spend 20 minutes scavenging parts from washing machines; you'll need to spend 2 hours and 10 minutes instead? Sure, you'll get the maximum number of components that way, but speaking for myself I would not be happy with this trade-off.

**Comment by eltank** [comment]
Hmm, it looks like it would be fairly easy to add support for a `deconstruct_simple` attribute to the item's JSON definition (which would be used to specify what you get when you perform a Deconstruct Simple Furniture). It would also be useful for things like tables, workbenches and chairs.
I can write the code for that if it's an acceptable/desired solution.

**Comment by definitelynotklip** [comment]
> So with this change it's no longer possible to spend 20 minutes scavenging parts from washing machines; you'll need to spend 2 hours and 10 minutes instead? Sure, you'll get the maximum number of components that way, but speaking for myself I would not be happy with this trade-off.
> 
> Edit: this would be more reasonable if you could choose to perform either "Deconstruct Furniture" or "Deconstruct Simple Furniture" on the washing machine and get parts with the first option or a washing machine item with the second option.

I understand your concerns. My first iteration of the change was to keep the 20-minute "Deconstruct Furniture" recipe and simply require players to rebuild the machine from scratch under the (`*`) Construction menu with the minimum requirements of the functional "washing machine", since it is a household appliance after all.

However, @kevingranade did not see it feasible for the player to be able to craft a household washing machine from scratch, and I was instead instructed by @I-am-Erk to make the machine "portable" by adding another step to the deconstruction phase.

As for your proposed solution of splitting the functionality of regular deconstruction and "simple" deconstruction, it is not mentioned anywhere in the item or furniture description that the outcomes of this process will be different (e.g. one makes the object portable, the other destroys it), and I don't think it is common knowledge enough to warrant this change. If the devs are in support of this I don't mind you suggesting a rewrite and me accepting it (still new to GitHub and the whole contributor thing).

**Comment by eltank** [comment]
> As for your proposed solution of splitting the functionality of regular deconstruction and "simple" deconstruction, it is not mentioned anywhere in the item or furniture description that the outcomes of this process will be different (e.g. one makes the object portable, the other destroys it), and I don't think it is common knowledge enough to warrant this change. If the devs are in support of this I don't mind you suggesting a rewrite and me accepting it (still new to GitHub and the whole contributor thing).

Sorry for the confusion. I wasn't suggesting putting code into this PR. That was really a question for @I-am-Erk about whether it would be desirable for me to write a new PR adding support for 2 separate disassembly outcomes.

Players should already be used to "Deconstruct Furniture" actually destroying the furniture, since that's what it does most of the time.

> EDIT: Is it really possible to disassemble an entire washing machine in 20 minutes without destroying anything? This change gives you max material yields so it is assuming you are being careful and methodical. Genuinely curious.

Well, no. The 20 minute disassembly almost always destroys some parts in the process (you don't get the maximum yield).

**Comment by I-am-Erk** [comment]
> > As for your proposed solution of splitting the functionality of regular deconstruction and "simple" deconstruction, it is not mentioned anywhere in the item or furniture description that the outcomes of this process will be different (e.g. one makes the object portable, the other destroys it), and I don't think it is common knowledge enough to warrant this change. If the devs are in support of this I don't mind you suggesting a rewrite and me accepting it (still new to GitHub and the whole contributor thing).
> 
> Sorry for the confusion. I wasn't suggesting putting code into this PR. That was really a question for @I-am-Erk about whether it would be desirable for me to write a new PR adding support for 2 separate disassembly outcomes.
> 
> Players should already be used to "Deconstruct Furniture" actually destroying the furniture, since that's what it does most of the time.
> 
> > EDIT: Is it really possible to disassemble an entire washing machine in 20 minutes without destroying anything? This change gives you max material yields so it is assuming you are being careful and methodical. Genuinely curious.
> 
> Well, no. The 20 minute disassembly almost always destroys some parts in the process (you don't get the maximum yield).

I think that complicates matters much too far 

Scavenging a washing machine for parts can be done quickly, out of the scope of this PR, by the following steps:
- unplug it (quick disassembly of furniture)
- disassemble the washing machine into base components (cabinet, door, drum)
- give each of those base components a disassembly job.

If you want a secondary way to quickly get parts, a "bash" option to smash the whole thing and pull out a few bits is supported. However it takes ten minutes just to swap the door swing direction on a front loader you're not familiar with, it's not a desirable outcome to be able to scavenge all, or even the most valuable, parts of any given washing machine in twenty minutes.

**Comment by eltank** [comment]
> it's not a desirable outcome to be able to scavenge all, or even the most valuable, parts of any given washing machine in twenty minutes.

It is currently possible to deconstruct just about any furniture in the game in 20 minutes -- fridges, stoves, consoles, dryers, pinball machines, bookshelves etc. What's so special about washing machines that they should get special treatment? Is the plan to extend this multi-step disassembly process to other objects? Is there a proposal describing how to do it in a systematic, consistent way?

> it takes ten minutes just to swap the door swing direction on a front loader you're not familiar with

Deconstruction is faster because you don't care about damaging the object. You're just unscrewing all the screws you can see and pulling stuff apart by force. Getting some pieces of metal and a rubber hose in 20 minutes does not seem unreasonable.

**Comment by definitelynotklip** [comment]
> Is the plan to extend this multi-step disassembly process to other objects?

That is the plan, yes. Making a pilot of one item could bring about change that would be implemented by many other contributors, not just me alone. From my understanding it would also be better to introduce big changes like this in small chunks, so that they are less likely to break the game and are easier / faster to review.

I chose the washing machine specifically because I needed it at base. I intend to make one other such change for the water heater and that's about it. If someone else feels they need other portable furniture at base, the formula is right here - that's how the devs want something like this to be implemented.

I did something similar with the [Trash Can](https://github.com/CleverRaven/Cataclysm-DDA/pull/50004), although it was later introduced as its own item on @I-am-Erk's request.

**Comment by I-am-Erk** [comment]
> It is currently possible to deconstruct just about any furniture in the game in 20 minutes

That's definitely not a feature. It's the result of being unable to specify deconstruction time for furniture. Ideally, most complex furniture should deconstruct to a placeable item and then we can also specify deconstruction times that are more reasonable.

If you're just ripping stuff apart to get a rubber hose and some scrap, that's well represented by bash IMO. Deconstructing implies care to retrieve parts.

**Comment by definitelynotklip** [comment]
> It is currently possible to deconstruct just about any furniture in the game in 20 minutes -- fridges, stoves, consoles, dryers, pinball machines, bookshelves etc.

I would also like to point out that I found a very small fraction of furniture you can not either replicate at base or get to your base reliably, which is good. Building a 1-tile vehicle and placing a minifridge/minidfreezer on it, and another 1-tile vehicle with an RV kitchen unit/FOODCO buddy on it could replace your fridge or stove in a pinch.

Hell, they might even look the same using tilesets. I am not using tilesets, however, and it's bothering me that these vehicle parts don't have the same physical looks (in ASCII) as their household variants, thus not giving your house the same homey, pre-Cataclysm feeling. This is what this PR (and others like) it aim to change.

**Comment by scorpion451** [comment]
A bit late to the conversation but as a general thought from someone with some practical experience from summers at a salvage yard and a lot of garage tinkering, disassembly becomes _extremely_ fast when you know what you're doing. (Case for an associated proficiency?) 

In a certain sense a dissassembly approach like the one taken with butchery might be warranted- are taking your time undoing all the cinch clamps and snap-in connections properly and keeping track of all the screws, or are you just looking to get the important parts out of something that doesn't necessarily have to go back together like it was?

**Comment by I-am-Erk** [comment]
I would love to see some salvage proficiencies for speed. Go for it

**Pull request merged**
