### PR TITLE
Routine i18n updates on 23 Aug 2019

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
```SUMMARY: I18N "Routine i18n updates on 23 Aug 2019"```

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
FYI: @BrettDong There is a possible issue with `pt_BR` translation that is visible in Android builds (e.g. https://ci.narc.ro/job/Cataclysm-Android/9312/console):

```
22:25:40 > Task :app:makeLocalization
22:25:40 lang/compile_mo.sh all

22:25:55 lang/po/pt_BR.po:29192: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:29779: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:40111: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:45783: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:60276: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:60696: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:60942: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:69340: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:84731: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:85913: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:86009: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:86474: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101133: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101168: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101183: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101214: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101222: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:101254: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:175865: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:175877: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:175885: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:175909: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:178953: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:180857: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:180912: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:180937: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:180960: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:180982: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:181014: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:181216: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:182690: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:186239: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:186273: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:186307: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:191137: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:198940: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203177: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203215: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203268: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203312: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203347: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203382: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203418: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203444: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203481: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:203526: 'msgid' and 'msgstr' entries do not both begin with '\n'
22:25:55 lang/po/pt_BR.po:207116: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:214922: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:214930: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:214938: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 lang/po/pt_BR.po:216113: 'msgid' and 'msgstr' entries do not both end with '\n'
22:25:55 msgfmt: found 55 fatal errors
```

**Comment by BrettDong** [comment]
There are some `\n` mismatches in Brazilian Portuguese translation text. I'll patch them on next translation update.

**Comment by ZhilkinSerg** [comment]
Thanks a lot!

**Comment by samuelmattjohnston** [comment]
Just going to drop this in here quick fix:

```sed 's/"\nmsgstr/\\n"\nmsgstr/' /home/$USERNAME/Cataclysm-DDA/lang/po/pt_BR.po | sed 's/\\n\\n"\nmsgstr/\\n"\nmsgstr/' > /home/$USERNAME/Cataclysm-DDA/lang/po/pt_BR.po
```

**Comment by BrettDong** [comment]
Seems recent .po pulls from Transifex still contains error...

**Comment by ZhilkinSerg** [comment]
> 
> 
> Seems recent .po pulls from Transifex still contains error...

Could be some new strings incorrectly translated by same user?

**Pull request merged**
