### PR TITLE
Japanese stuff (New profession, items, and tweaks)

### PR DESCRIPTION
**Pull request by SeanWiig**
#### Summary
SUMMARY: Content "Adds Japanese-themed items and tweaks existing ones."

#### Purpose of change

1. Martial arts that apply to weapons with inferior and fake variants don't apply to them, with the sole exception of sojutsu which applies to halberd and halberd_fake. This means that you will never be able to utilize niten ichi-ryu unless you get very, very lucky.

2. I want inferior and fake versions of Japanese weapons to be slightly less garbage.

3. I want dojo clothes to be slightly less garbage. Martial arts wear is meant to withstand a lot of abuse and tumbling and are definitely less prone to tearing than jeans, which have 3(?) material thickness.

4. The naginata doesn't have inferior or fake versions.

5. Geta was the only shoe item in armor.json. All other shoe items are in boots.json

6. I have been playing too much Sekiro: Shadows Die Twice

#### Describe the solution

1. All martial arts which applied to weapons with fake and inferior variants now apply to all fake and inferior variants. This was already the case for the halberd and halberd_fake, now it’s consistent for all weapons. Also, the survivor naginata was added to sojutsu.

2. Fake and inferior variants of Japanese weapons are slightly less garbage. Fake variants remain worse than a makeshift crowbar.

3. Dojo clothes are slightly less garbage. keikogi, karate_gi, zubon_gi, hakama_gi now have 2 material thickness, instead of 1, and have the STURDY flag. judo_gi remains with 3 material_thickness, but is now also STURDY. keikogi and zubon_gi are now identical in terms of stats to the karate_gi, except that they’re for legs or upper body only. hakama_gi now has slightly more coverage and warmth than zubon_gi, at the expense of being slightly more cumbersome.

4. The naginata now has inferior and fake versions. It was accordingly added to mansion item tables.

5. geta was moved from armor.json to boots.json.

6.
- Added urban samurai. Two point cost is justified by very fancy clothing and the unique distinction of being the only profession to start with a weapon compatible with niten ichi-ryu.

- Yukata added. Yukata is similar to the kimono, but has less protection and less warmth and even less encumbrance. It is slightly more common than the kimono. Like the kimono, it has the flag FANCY.

- Haori added. It is a torso and arm outer garment with the SUPER_FANCY flag and low encumbrance. It is not very protective. It is a rare item. (for reference, with the stylish trait, wearing a kimono by itself gives a morale bonus of 8, and a haori by itself gives 8, but wearing them at the same time gives 10, because of how stylish bonuses stack.)

- Dress hakama added. This is an outer wear leg garment. It is not very protective. The idea is that you could comfortably wear it over a kimono or yukata (or anything else)

- tabi_gi and tabi_dress no longer have 10 encumbrance, which made them strictly worse than socks which have 0 encumbrance for no discernible reason. All other stats were and are identical to socks.

- added the new items to the itemgroups, with haori being treated as a rare item. The kimono is slightly less common than before, while yukata is more common. Also, geta was added to itemgroups. Dojos now have a slight chance of spawning haori and yukata and geta.

- Added a recipe book for Japanese clothing, and crafting recipes for kimono, yukata, hakama, haori, and geta.

#### Alternative Considered

I considered having the gi have the same material thickness as jeans or a sweatshirt at 3 thickness, but then judo_gi would have to have a value of 4 (because it's defined as being tougher than the other gi), which would push it into chainmail and survivor armor territory, which would be ridiculous. So I left the gi at 2 thickness. Which still leaves a karate gi as less protective than a sweatshirt or jeans, which sounds a bit wrong.

### CODE REVIEW

**Comment by aoae23** [comment]
Sort of piggybacking on this, but are stone spears not supposed to work with Sojutsu?

**Comment by SeanWiig** [comment]
It definitely should. I just looked into that. The stone spear resides in the "more survival tools" mod. Because of that, adding stone_spear causes an error on loading unless you have the mod loaded. Which is a shame. Maybe the item could be merged into the base game, but the recipe kept in the mod? But that's a job for another pull request.

Right now I'm just trying to figure out what about "item_groups.json" is causing the Travis CI build to fail.

**Comment by ifreund** [comment]
>Right now I'm just trying to figure out what about "item_groups.json" is causing the Travis CI build to fail.

It just needs to be linted.  You can use the web linter here: http://dev.narc.ro/cataclysm/format.html

**Comment by tenmillimaster** [comment]
I noticed a while back that naginatas can be crafted from a katana and a stick. considering that the two blades are of different lengths, maybe give the Naginata from existing blade recipe some love? also, maybe make it disassemble-able since that appears to be the case.

Here's an example of the opposite happening, a wakizashi made from a naginata, But I think they're both close enough. <http://new.uniquejapan.com/a-morokage-wakizashi/>

**Comment by SeanWiig** [comment]
The recipe for crafting a naginata from a katana and a stick creates a normal naginata, as far as I can tell. So it should be applicable to sojutsu. Unless I'm misunderstanding what you're trying to say?

Crafting a naginata from a katana seems to involve reforging the base of the blade to fit into the new handle, since it requires a full set of forging equipment and level 7 fabrication. Considering that, disassembling the naginata into a katana should also involve those same high requirements. Actually I'm not sure if it should count as disassembling, but maybe it should be its own crafting recipe. I could add that to this if it sound like a good idea.

**Comment by tenmillimaster** [comment]
I wasn't at all suggesting that the naginata be unapplicable to sojutsu.

- I'm suggesting that CDDA is using an additional item, the wakizashi to make the naginata. the lengths of blade listed here<http://ny-naginata.org/about/>, 6 inches to 2 feet, seem to indicate that a wakizashi is appropriate for this recipe.[ The lengths seem to be about 30cm to 60cm ](http://new.uniquejapan.com/7,-points-to-consider-when-choosing-your-japanese-sword/). 

I further provided an example of the reverse occuring, katanas and wakizashis being made from  naginatas.

**Comment by SeanWiig** [comment]
Oh, I misunderstood you and you misunderstood me. I thought you were saying that sojutsu currently doesn't apply to the crafted naginata, and I was saying it actually does. You didn't mention "wakizashi" in your post except offhandedly in the second paragraph so I had no idea what you were saying. I think what you're trying to say is that the naginata recipe should accept either a katana or a wakizashi, instead of only a katana. That sounds reasonable. I've committed the change.

**Comment by SeanWiig** [comment]
03:54:00 Formatted  src/game.cpp Formatted  src/activity_handlers.cpp
03:54:00 Makefile:993: recipe for target 'astyle-check' failed
03:54:00 make: *** [astyle-check] Error 1
03:54:00 Build step 'Conditional step (single)' marked build as failure

It sounds like something else broke the test? I haven't touched src/activity_handlers.cpp. Maybe I'm reading the console log wrong?

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by ZhilkinSerg** [comment]
> 
> 
> Jenkins rebuild

We've switched to 3xxxx PRs, so PRs with 2xxxx ids won't be build by Jenkins anymore (Travis can still check json formatting and astyle from any PRs).

**Comment by Night-Pryanik** [comment]
Okay, got it.

**Pull request merged**
