### PR TITLE
More spawns for voltmeter and multimeter

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Bugfixes "Adds more spawns for voltmeter and multimeter"

#### Purpose of change
The voltmeter and multimeter, 2 very common tools for anyone working with electricity, were somewhat lacking in possible spawn locations (including for example the zombie technician or the electronics store), and since they are now needed for the electronics practice recipes...

#### Describe the solution
Added the 2 items to a few itemgroups used in relevant places/death drops.

#### Describe alternatives you've considered
Creating some recipes for those 2 items and the breadboard...

### CODE REVIEW

**Comment by wapcaplet** [comment]
Yeah these were definitely too hard to find. A couple more locations for the breadboard would be nice too; I have not found one yet since I added them to the game!

**Comment by Termineitor244** [comment]
> 
> 
> Yeah these were definitely too hard to find. A couple more locations for the breadboard would be nice too; I have not found one yet since I added them to the game!

Haha me neither! I think maybe the school could have some, I will see if I can add it to some groups there.

**Comment by wapcaplet** [comment]
There is an electronics hobbyist basement room in the nested mapgen JSONs:

https://github.com/CleverRaven/Cataclysm-DDA/blob/47cbf6852d1debd0e5c5ba33b260e90e2e8815de/data/json/mapgen/nested/basement_nested.json#L2885-L2888

It already includes the electronics_diy itemgroup you've edited, but this location would be a suitable place for a near-certain chance of finding a breadboard and multimeter, maybe sitting on the workbench with "place_item".

**Comment by Termineitor244** [comment]
> It already includes the electronics_diy itemgroup you've edited, but this location would be a suitable place for a near-certain chance of finding a breadboard and multimeter, maybe sitting on the workbench with "place_item".

Done, thanks!

**Pull request merged**
