### PR TITLE
[WIP] Overmap zones

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Resurrection of #7892 (compiles, but was only basically tested and is not ready for merging).

# What was changed:

- see #7892.

# Screenshots:

__See all these blood puddles and broken furniture? They come from `Looted` zone:__

image.

### CODE REVIEW

**Comment by jamesmcm** [comment]
It might be interesting to add an OM zone for some sort of NPC settlements.

**Comment by Worthstream** [comment]
Will this support blacklist mods? As in "no fungal monsters" blacklisting fungalized zones.

**Comment by ZhilkinSerg** [comment]
> Will this support blacklist mods? As in "no fungal monsters" blacklisting fungalized zones.

Good point. We should add possibility to blacklist zone types.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/postbiomes-mod-concept-discussion/26632/4

**Pull request closed without merging**
