### PR TITLE
folding bicycle is dead. Long live Folding Bicycle

### LINKED ISSUE #28976: Foldable bike can't be folded after unloaded from bike racks
As title, after unloaded foldable bike from bike racks, it became a normal bike that can't be folded when 'e'xamine it.

**To Reproduce**  
1. Unfold the folded bike.
2. Load it on bike racks.
3. Unload it in bike racks.
4. Examine it to see whether there's an option to fold it.

**Expected behavior**  
It should be foldable after unload.

**Versions and configuration(please complete the following information):**
 - OS: 
image
 - Game Version: 0.D-947-g980ca05
 - Graphics version: Tiles
 - Mods loaded:
image
image
image

### LINKED ISSUE #39399: Folding bicycle magically repairs itself
# Describe the bug
The folding bicycle item that the cyclist starts with magically repairs itself upon folding and redeploying, fixing any and all damage. 

# Steps To Reproduce
1. unfold the fold-able bicycle item
2. smash it with a sledge hammer, breaking even entire sections off
3. fold it and redeploy it and see it's in perfect condition again.

# Expected behavior
For my damaged bike to retain it's damage.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-414-ge0bf561 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Another random note the folding bike itself isnt even made out of a foldable frame and you cant take apart or add anything to it. It appears to be something different than a normal player made fold-able vehicle.

### LINKED ISSUE #46752: Replace the foldable bicycle special item with a generic folding vehicle
# Is your feature request related to a problem? Please describe.
Folding vehicles are now possible to create in the standard vehicle interface, no need to have this separate item that has accumulated two major issues: #28976 and #39399

@BevapDin comment:

> The whole folding bicycle item should go away. It is either inconsistent or redundant:
> 
> It's inconsistent because it creates (when unfolded) a vehicle that could have been made via the vehicle interface (frames, saddle, wheels, etc.) However, making the item requires different tools / tool charges and different time than making the vehicle.
> 
> Fixing that inconsistency (which may get unfixed as soon as somebody changes the vehicle part installation settings), would make the item redundant. One can instead just make a vehicle and fold that. Why make an item, if it takes the same resources?
> 
> Therefor it should be removed.
> 
> Note that vehicles creates via the vehicle interface can be made with special properties (someone might want a bicycle with a horn, different cargo part, different wheels ...)

# Describe the solution you'd like
Folding bicycle replaced with similar vehicle, not special item.

# Describe alternatives you've considered

# Additional context

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary

SUMMARY: Bugfixes "Reimplement folding bicycle as a regular foldable vehicle that follows the same rules as the rest"

#### Purpose of change

Fixes #46752
Fixes #28976
Fixes #39399

Folding bicycle was a flodable vehicle before flodable vehicles were implemented. Now we have a more general foldable vehicle system, but we are still keeping folding bicycle as a special case which follows different rules. It is time to reimplement folding bicycle as a regular foldable vehicle.

#### Describe the solution

- [ ] reimplement or remove content that references "folding_bicycle"
- [ ] add migration code to replace the folding_bicycle **item** in save files with the new version
- [ ] add migration code to replace the folding bicycle **vehicle** in save files with the new version

#### Describe alternatives you've considered

* leave everything as is
* implement migration of saves by replacing unfolding code for the folding_bicycle item. This would not fix #28976 and item stats would have to be manually kept in sync

#### Testing

none yet

#### Additional context

none

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
As far as I know there is unfortunately no way to reference a folded version of a vehicle from inside an item group and implementing one would probably be more effort than it is worth.

**Comment by hexagonrecursion** [comment]
All that is left it on the C++ side:
- [ ] cleanup dead code
- [ ] implement save migration (since jsonized migration is probably not flexible enough)

**Comment by hexagonrecursion** [comment]
Yes. Definitely not flexible enough

https://github.com/CleverRaven/Cataclysm-DDA/blob/0d85973a3b0af8de0bb59e0f18f4d69b5461760b/src/item_factory.h#L43-L62

**Comment by int-ua** [comment]
I think I mislabeled the issue as a `Good first issue`. It's far from trivial.

**Comment by Rivet-the-Zombie** [comment]
>As far as I know there is unfortunately no way to reference a folded version of a vehicle from inside an item group and implementing one would probably be more effort than it is worth. So far I simply deleted the entry from item groups. Not sure what to replace this content with.

So this PR prevents folding bicycles from spawning outside of a single profession's starting inventory?

**Comment by hexagonrecursion** [comment]
> So this PR prevents folding bicycles from spawning outside of a single profession's starting inventory?

Good point. I should make the unfolded version spawn randomly somewhere.

**Comment by hexagonrecursion** [comment]
> I think I mislabeled the issue as a `Good first issue`. It's far from trivial.

The hardest part is meeting my archenemy - c++ compilers and not running away screaming like a little girl.

**Comment by hexagonrecursion** [comment]
> - [ ] add migration code to replace the folding_bicycle **item** in save files with the new version
> - [ ] add migration code to replace the folding bicycle **vehicle** in save files with the new version

I came up with a simpler solution:
* remove the ability to fold the folding bicycle **vehicle**
* make the folding_bicycle **item** disassemble into parts that you can build your own folding bicycle

This has the downside of breaking existing folding bicycles, but the upside is less code to maintain.

**Comment by ZhilkinSerg** [comment]
Let's move it post-0.F

**Comment by Night-Pryanik** [comment]
@hexagonrecursion is this still being worked on?

**Comment by hexagonrecursion** [comment]
No. Sorry. Anyone, fell free to pick this up.

**Pull request closed without merging**
