### PR TITLE
Show related craftable items for current recipe by hotkey

### PR DESCRIPTION
**Pull request by AMurkin**
#### Summary
```SUMMARY: Interface "Show related craftable items for current recipe by hotkey"```

#### Purpose of change
Provide better navigation between crafting recipes. 

#### Describe the solution
In the crafting menu press L (by default) to open a menu with recipes/items related to selected recipe: craftable components and recipes using selected item.
image

#### Describe alternatives you've considered
A new multi-panel window for continuous crafting could be a better solution.

#### Additional context
Interface could be better but not via menu i think.

### CODE REVIEW

**Comment by jniscior** [comment]
Perhaps there could be a static letter assigned to quitting the menu for consistency? Similar to how 'q' is used in "Use which component?" menu

**Comment by AMurkin** [comment]
Sure, done.

**Comment by AMurkin** [comment]
Here are some updates.
I don't know how I can make a nice interface, and don't want to make it from scratch using windows and all that addch-es. Suggestions?

**Comment by AMurkin** [comment]
I want to say this provides very good navigation between crafting recipes.

**Comment by AMurkin** [comment]
I need to sort results list. Didn't spot it.

**Comment by ZhilkinSerg** [comment]
That would be nice new addition to the game, but I have some questions.

1. Is it possible to add some kind of Back function in these menus? Not necessary to do right now, but it could be convenient to have that.

2. Please add `L` to keybindings label.

image

3. What do `L`, `+` and `-` symbols mean?

image

4. Why some of the menu entries aren't active (`chunk of steel` and `scrap metal`)? W

image

5. Why solar backpacks appear in the list for nail rifle magazine (and many other items)?

image

**Comment by AMurkin** [comment]
Menu shows recipes that give components and results of selected recipe.
Many items can be obtained with more than one recipe. They can be including by-products of some recipes.

1. This menu is one time recipe selector which sets filter string for crafting GUI. So history navigation should be implemented at its level. It's possible i think.
2. Will do. But for narrow screens/windows this line didn't fit completely.
3. Well, this is my attempt to use ASCII instead of border lines. I want to show a tree structure, but as I can see uilist not supports such chars. Maybe I'm wrong.
image
4. Non-active munu items are items that can be obtained via recipes listed after its row in nested level. If all recipe names are equal (3 different recipes named 'sugar') then menu will show only one active line (— sugar).
5. Scrap metal is a byproduct of solar backpacks :)
image

**Comment by ZhilkinSerg** [comment]
Following boxd-drawing chars work fine for me - I guess we can add them in subsequent PRs:

```
─
└
├
```

image

**Comment by AMurkin** [comment]
@ZhilkinSerg How can i use special chars in code? I think I cannot use them directly?

**Comment by ZhilkinSerg** [comment]
Why not? These are from ASCII character set and are supported just like other characters.

**Comment by AMurkin** [comment]
OK. Done in #25854. Thanks!

**Pull request merged**
