### PR TITLE
Add chainmail gloves, chausses, and faraday suit

### PR DESCRIPTION
**Pull request by harison86**
SUMMARY: Content "Add more chainmail items and crafting recipes"
#### Purpose of change
The player is unable to craft chainmail gloves or footwear, even though this is feasible and useful for them to do. If the player is able to craft a fullbody suit of chainmail similar to the shark suit, they should also be able to wire it to protect against electricity, similar to the faraday shark suit.
#### Describe the solution
Add chainmail gloves, chainmail chausses, faraday chainmail suit, and corresponding recipes.
Chainmail gloves and chausses spawn in expected locations where other chainmail items can be found.
Cut resistant gloves spawn in butcher shops now (instead of chainmail gloves as initially planned).
#### Describe alternatives you've considered
Not implementing any of the above features.
Making chausses occupy the skintight layer, allowing them to be worn with boots.
Making chausses also cover the legs.
Renaming chausses to socks or booties.
#### Testing
Made the changes in my own version of the game. Successfully spawned items through item spawn menu. Items appeared when testing the item groups they were added to. Items appear in crafting menu when and where expected, and can be crafted. Items behaved as expected when worn.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Summary: Content "Chainmail items" 

Should fix your PR Validator test.

**Comment by Maleclypse** [comment]
You can use http://dev.narc.ro/cataclysm/format.html to fix linting issues in JSON validation.   I generally select all text in the file I've changed and copy and paste it into the linter.  If you receive no error after hitting the lint button, copy the newly linted text and paste it over your original file.

**Comment by anothersimulacrum** [comment]
I'd suggest you have a more descriptive summary line, such as 
`SUMMARY: Content "Add more chainmail items and crafting recipes"`

**Comment by harison86** [comment]
I can remove the mention of butchering in the description for the chainmail gloves. Butcher's gloves are probably supposed to be represented by the [cut resistant gloves](http://cdda-trunk.chezzo.com/gloves_cut_resistant) already in the json files, which I hadn't known existed until recently since they do not appear to be obtainable in-game. If it's appropriate to include in this PR, I can have the cut resistant gloves spawn as butcher's tools in place of the gauntlets I am adding.

[This video](https://youtu.be/SSV1ocCEOdY?t=60) and [this video](https://youtu.be/WFl2yiw9nek?t=357) both showcase a flexible chainmail suit similar to what the player would be constructing, acting as a Faraday suit. [This website](http://www.teslamad.com/faraday/faraday.html) describes the process of constructing a Faraday suit by hand (it appears to be simple chainmail). I see very little difference between these suits and chainmail armor designed for physical protection.

[This video](https://www.youtube.com/watch?v=gNkCYR1aUls) shows what I initially imagined the chainmail gloves to be like. The gloves' stats were based on other chainmail items, and are similar to those of the [armored gauntlets](http://cdda-trunk.chezzo.com/gloves_plate), however I agree that the encumbrance should be higher.

Following this, I think I will
- Replace the chainmail gloves in butcher_tools with cut resistant gloves
- Change description of chainmail gloves, increase poor fit encumbrance to 30
- Remove chainmail_suit_full and corresponding recipes
- Alter the Faraday chainmail suit and recipe to better emulate an actual Faraday suit. The crafting recipe will take longer, take more materials, be irreversible, and can use either chainmail sheets or chainmail armor pieces – the player will be making significant, irreversible changes to the chainmail in order to repurpose it. The suit will have 30 poor fit encumbrance, lower defense than chainmail armor (due to a lack of gambeson/padding), and will be worn on the outer layer like a cloak.

Does this all sound like an appropriate course of action?

**Comment by Tevrian** [comment]
Really, faraday suits are way simpler than you might expect. Any sufficiently conductive suit that covers the whole body should protect against electricity about as well, on account of the fact that the whole point is just to provide any errant electicity a more convenient route to ground than your fragile flesh.
You could, in theory, make an adequate faraday suit by covering yourself in aluminium foil and duct tape, or by coiling yourself up in copper wires, or soldering up some chicken wire mesh into a suit, or by wearing a full suit of plate with some chainmail mittens tacked on.
It's kind of strange that the pre-existing faraday shark suit requires being "conductively interconnected" given all the shark suits of similar design that I've seen have already been conductively interconnected The only addition I could see that would improve a standard shark suit's electricity warding capabilities would be a wire mesh face mask, or a sort of chainmail veil, what with that being the only section of flesh not covered in conductive metal.

**Comment by kevingranade** [comment]
> I see very little difference between these suits and chainmail armor designed for physical protection.

I'm fairly certain that chainmail the armor focuses on vulnerable points rather than complete coverage, with some areas covered with more chain and some not having any coverage at all. A faraday suit on the other hand focuses on complete coverage to the exclusion of any other concerns.
Chainmail armor is going to trade off weight versus protection by increasing the gague of links or increasing their density, a faraday suit is going to use the smallest links that can handle the current, which is very small. Likewise the materials to use are different.
Finally a faraday suit is intended either for demonstration purposes or for working on electrical gear, whereas a chain armor is intended for fighting in.

That aside, your proposed changes sound good, a faraday suit is a thing that is craftable, I'm just not seeing any value in having it be a direct upgrade path from chain armor.

**Comment by Zireael07** [comment]
AFAIK chainmail armor covered one's whole body, and the only body part left uncovered was the face (chainmail hoods existed, but helmets had a face cover as an option, therefore were preferred for one's own safety in battle)
However, I agree that chainmail != faraday suit (but I suppose the survivor could reasonably make a faraday suit from the same materials and with the same tech s/he makes the chainmail with)

**Comment by crazykiddeath** [comment]
Cut resistant gloves, basically small ringed chainmail, are pretty common and get used in all sorts of industry. We used to use them in the tailoring industry when the cutting out large stacks of cloth using templates. They certainly weren't highly encumbering since you require a fair amount of dexterity to do precise cuts and they were good protection since they had to stand up to electric fabric cutters long enough to get you hand back without losing any fingers.

**Pull request merged**
