### PR TITLE
Remove commented out code

### PR DESCRIPTION
**Pull request by BevapDin**
Summary: None

### CODE REVIEW

**Comment by mlangsdorf** [comment]
NAK. That code gets removed and replaced with working code as part of #25802.

**Comment by BevapDin** [comment]
> That code gets removed and replaced with working code as part of #25802.

Why have you added it? It's dead code that has no meaning nor purpose.

**Comment by mlangsdorf** [comment]
I couldn't get labels to work while working on the bike rack code, so I commented out the references and forgot about them. The bike rack code got merged, I noticed the error, and then I fixed it as part of 25802 as I said.

**Comment by mlangsdorf** [comment]
Fixed in #25802. Closing.

**Pull request closed without merging**
