### PR TITLE
Use snippets instead of static responses in dialogs

### PR DESCRIPTION
**Pull request by Uwuewsky**
#### Summary
Infrastructure "Replace some player responses with snippets"

#### Purpose of change
We have a category of snippets for player responses that end a dialogue. But they were rarely used. It would be convenient to have all these typical responces in one place.

#### Describe the solution
[In this PR only the transfer of snippets to different files and several new categories was done.]
[The replacement of dialogues and responses was made in the following PRs.]

Replace static answers in `TALK_NONE` and `TALK_DONE` with snippets.

Snippets are now split into multiple files and several new categories.
`talk_tags.json` now contains only small snippets.
 - new `<wpunc>` - same as `<punc>`, but the snippets have weight instead of equal probability

`talk_tags_avatar.json` contains the player's responses.
- `<end_talking_bye>`, `<end_talking_later>`, `<end_talking_leave>`, `<end_talking_nevermind>`, `<end_talking_later_follower>` - the corresponding snippets and replaced text are sorted into these categories

`talk_tags_line.json` contains snippets with full sentences.
 - new `<lets_go>` snippet

#### Testing
I looked through all the changes in this PR, as for me all the replacements look correct. The game also did not give any errors when loading with data verification.
talk1
talk2
talk3
talk4
talk5
talk6
talk7
talk8
talk9

### CODE REVIEW

**Comment by Uwuewsky** [comment]
I know, my bad. But is there any point in breaking the PR into several parts if the work is already done? Isn't it better to break it here into smaller commits (~300 lines)?

If this is still needed, I will break it into several parts, just let me know

**Comment by GuardianDll** [comment]
it's not about making separate commits, it's about merger being able to read the PR in one go

**Comment by Uwuewsky** [comment]
Okay, I thought the merger would look at reviews from other participants.

Then I'll split it into ~4 PRs later. Although the first one will still be big due to copy-pasting pieces from a monolithic `talk_tags`, nothing can be done about it I think.

**Comment by Uwuewsky** [comment]
Done.

**Comment by GuardianDll** [comment]
this one also needed the test restarted
image

**Comment by Uwuewsky** [comment]
After the "big expansion" there were even more snippets, I moved some of them to another separate file `talk_tags_follower.json`. Also tested the latest changes.

Aaaand it might be worth clearing up this whole snippet mess as it has become even more confusing. But in this PR I made only minimal edits, other than moving from the monolithic file.

Some snippets have lost their original meaning or are used in the wrong places.
Some snippets should be removed altogether to avoid unnecessary confusion and complexity. `<ill_die>` is used in like 6 lines, but contains about 50 snippets, each of which sounds out of place after substitution. Where are `<sad>` and `<happy>` used at all?
Some categories should be merged into one.
Some new categories should be added.

**Pull request merged**
