### PR TITLE
Add a vibrator crafting recipe

### PR DESCRIPTION
**Pull request by wapcaplet**
There was an existing recipe for crafting an mp3 player, but
surprisingly none for a much simpler device, the vibrator.
This recipe uses similar ingredients to the existing deconstruction
recipe (with the addition of a tiny electric motor), and is auto-learned
at fabrication level 2.

#### Summary

SUMMARY: Content "Adds crafting recipe for vibrator" 

#### Describe the solution

I used the existing electronics crafting recipes as a template to add a vibrator recipe to the JSON data, using my best guess about difficulty and components.

#### Testing

Crafted a vibrator from the new recipe and loaded it with a light battery. Activated it and got the tension out.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I've found myself wanting to craft this before and been disappointed. Feels like a solid addition as a recipe.

**Comment by mkikt4743** [comment]
should be electronics 2 not fab 2 other than that all good

**Comment by kevingranade** [comment]
Plastic scrap is pretty severely not ok for this, and it needs casting tools as well, because you're not starting from a gigantic chunk of plastic that you carve into shape.

Silicone (not present in game)
Silicone casting tools (not present in game)
wires
on-off switch
tiny motor
scrap (for eccentric weight)

**Comment by wapcaplet** [comment]
I agree that a plastic mold should be required, and I see now that it's needed for several other electronics recipes. Some "cable" (copper wire) makes sense too. But do on/off switches even exist in the game? I don't want to make it too complicated - again, I can't help but compare it with the mp3 player, which is basically just some RAM and processors superglued together, which then magically become loaded with playback software and a limitless supply of tunes. A vibrator just needs to be smooth and insertable, with a motor and weight to make it wiggle a bit.

**Comment by Brian-Otten** [comment]
I imagine silicone would be a nice luxury, but a survivor could make do with plastic for his back massager. The shape cast properly in a plastic mold would probably be sufficient. Turning it on/off can be as simple as leaving the battery in the device but not socketed, then socketing it for use.
Earlier comment that it should be electronics 2 instead of fabrication seems correct, had not noticed that before.

**Comment by wapcaplet** [comment]
I chose fabrication as the skill requirement, since it seemed more of a component-assembly task (connect wires to motor and battery, glue it all together) than something requiring actual electronics knowledge, but it makes sense to require a bit of both.

The electric hair trimmer has
```
"skill_used": "fabrication",
"skills_required": [ "electronics", 1 ],
```
My recipe probably ought to require some solder too. I'll fix it up and try again.

**Comment by wapcaplet** [comment]
I've pushed another commit with several changes. I believe this recipe is well-balanced with others in `recipe_electronics.json` now.

**Comment by davidpwbrown** [comment]
I'd just like to take a moment to marvel at the fact that this is even a discussion in a game.

Beyond that, we actually need to work out what the vibrator is, and what level of "makeshift" would even be palatable for its purpose.

I cant believe im saying this on github, but here goes.

If its a penetrative sex toy, then silicone would obviously be the most hygenic and safe way to do it.
But other ways exist, as per here https://sextoycollective.com/blog/unsafe-sex-toys/

As you can see, many materials can work fine, with suitable treatment ( i.e wooden toys with sealant )

But because the vibrator item dosnt specify that its penetrative, and is infact quite euphemistic to its actual purpose, we can perhaps surmise that its just a variant of the ubiquitous Magic Wand, or even a small vibrating bullet-type vibrator, or any other external vibrating toy thats not designed for internal use.

Because of this, I wouldnt worry too much about the material its made from, as long as it vibrates, Cleopatra famously ( but probably apocryphal ) made do with a clay jar of angry bees.

**Comment by davidpwbrown** [comment]
By the way, you need to lint your JSON

**Comment by Fris0uman** [comment]
> don't want to make it too complicated - again, I can't help but compare it with the mp3 player

If the mp3 is too simple make it more complicated (but that can happen later), this is not an argument to make other recipe too simple to. 
Since you're currently working on the vibrator it would be nice to get a complete recipe for it. New materials and tool can always be used for other recipes.
You could maybe expend our selection of back massagers, with a makeshift one made from scrap platic and a finer one made from silicone.

**Comment by I-am-Erk** [comment]
I think to get more granular on this and many other things, we should get into making different types of plastic in game, not one material covering everything from silicone to PVC.

This is good for what we're talking about, which is a euphemism and could just as easily be a back massager. I have made a vibrating table for casting clay molds out of an old drill and some plastic scrap, it's pretty easy to do.

**Comment by ashGlaw** [comment]
I would recommend making the recipe require Electronics as a primary skill and Fabrication as a secondary. There are too few early electronics recipes and this would help progression without relying on a skill book.

**Pull request merged**
