### PR TITLE
NPC talker test fix

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Fix talker test failures

#### Describe the solution
Doing what dseguin said might work.

#### Describe alternatives you've considered
None

#### Testing
run tests

### CODE REVIEW

**Comment by dseguin** [comment]
I ran `git bisect` and found the cause: de406e4cc1dd3f582f3a9f50353d85aa4af124a1

Nothing wrong with the commit, but I think it exposed a flaw in the test :P

**Review by BrettDong — APPROVED** [review]

**Comment by haveric** [comment]
> I ran `git bisect` and found the cause: [de406e4](https://github.com/CleverRaven/Cataclysm-DDA/commit/de406e4cc1dd3f582f3a9f50353d85aa4af124a1)
> 
> Nothing wrong with the commit, but I think it exposed a flaw in the test

Thanks for this. That was one of those changes where I knew it fixed the issue, but I wasn't familiar enough with the surrounding code to understand the ramifications and am still hoping nothing breaks because of it. I also don't have a great grasp at some of the failing tests, so I was hesitant to "fix" the test that I didn't know if it was actually broken.

**Comment by Maleclypse** [comment]
64302863-D3D1-4D95-876A-BD58A5989562

is there more in this that needs to be fixed? Or is this coincidence?

**Comment by dseguin** [comment]
> is there more in this that needs to be fixed? Or is this coincidence?

It looks like that test run was from just before this PR was merged. I bet restarting the test will fix it.

**Pull request merged**
