### PR TITLE
Expand scrap metal furniture, especially with exodii stuff

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
SUMMARY: Content "Adds some new exodii furniture (not spawning) and general scrap metal furniture (constructable)"

#### Purpose of change
We need more apocalyptic furniture made of scrap.  Specifically I need some of this to decorate the exodii base, but some is useful for general purposes.

#### Describe the solution
Implements exodii furniture for decorating exodii base. This stuff is not constructable and does not yet spawn in game.

Also implements some furniture to be used by exodii, which is constructable.
- Scrap metal bridge
- Scrap metal table
- Scrap metal bench
- Ground cable (decorative only)

For the exodii specific furniture, I expanded "furniture_migo.json", previously just mi-go stuff, to be furniture_alien.

#### Describe alternatives you've considered
I'd welcome suggestions for more scrap furniture.

#### Testing
I have loaded these in game in my previous copy, but not tested in this version. Construction recipes still need testing.
Pics of ultica tiles for them upcoming.

Loaded in this version now, spawned all types of furniture, no errors.

#### Additional context
- Comment from my 4yo daughter that she would like added to this PR: "One one one. That means 'common sense'."

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
`exodii_portalizer ` item definition is nowhere to be found

**Comment by ZhilkinSerg** [comment]
`escrap` too

**Comment by I-am-Erk** [comment]
fixed and fully tested

**Comment by I-am-Erk** [comment]
Thanks my friend

**Pull request merged**
