### PR TITLE
New json flag "CAN_OPEN_DOORS"

### PR DESCRIPTION
**Pull request by ghost**
**Summary**
`SUMMARY: Features "Implementation of a new json flag 'CAN_OPEN_DOORS'"`

**Purpose of change**
Needed for #29206 

**Describe the solution**
Monsters with that flag will try to open a door if there's one blocking their path.
Always tries to open doors before bashing them.

**Describe alternatives you've considered**
**Additional context**

### CODE REVIEW

**Comment by mlangsdorf** [comment]
New flags should be added to doc/JSON_FLAGS.md and should be added to add least one monster in data/json/monsters/ or data/json/monsters.json to indicate the use.

**Comment by cafeoh** [comment]
`open_door`'s second parameter is a bool to determine if you're inside or outside the buildings.
If a door is locked it doesn't necessarily make sense for your monster (as intelligent as it is) to open it in a single turn. Instead of setting it to `true` you might want to check the outside_cache by using `!g->m.is_outside( pos() )`. Check action.cpp or npcmove.cpp to see how the function is usually called.

**Comment by mlangsdorf** [comment]
"Added a new JSON field" is not a valid field for PR type.  See doc/CHANGELOG_GUIDELINES.md for valid types.

**Comment by mlangsdorf** [comment]
jenkins rebuild

**Comment by paulenka-aleh** [comment]
Would love to see this flag in action. I suppose Zombie scientists, police bots and probably some nether monsters could be smart enough to attempt so.

**Comment by Throwaway-name** [comment]
"It was inevitable."

**Comment by ZhilkinSerg** [comment]
Can you please add this flag to some monster to begin with?

**Comment by Wokko1** [comment]
#29206 needs the flag.

Originally I wanted this flag to be used in my mod, but currently irl stuff prevents me from working on it (and contributing to the basegame too).

If you want, I can add the flag to zombie scientists or police bots maybe, just to justify the flag's addition. Though I don't know would that be fitting, and I think #29206 would still count as the flag usage.

**Comment by kevingranade** [comment]
I tried this out with the Prototype Cyborg, and it is not opening doors when chasing me around in a house.

**Comment by Wokko1** [comment]
That's strange, when I was opening the PR, I tried it with regular zombie, and they opened the doors. I'll try to test it again later.

**Pull request closed without merging**
