### PR TITLE
remove sand from fields

### PR DESCRIPTION
**Pull request by Snaaty**
Sand on regular fields is (imho):
a) visually not very appealing
b) not realistic
c) slightly irritating, as sand can't be used for much (yet)

So I hereby propose to change that.

### CODE REVIEW

**Comment by KA101** [comment]
Only reason this hasn't gone anywhere is that there's no replacement source for sand.  Needs to spawn sand elsewhere to remove it from fields.

**Comment by Aenye** [comment]
If possible, please also add sand to sandboxes, as vache suggested.

**Comment by mafagafogigante** [comment]
I have seen toy stores selling sand (both colored and "standard").

**Comment by KA101** [comment]
We can add more sand locations later; wanting to get this out of the hopper before it goes unmergeable.

**Comment by Snaaty** [comment]
Thanks, sorry for being so unproductive :(

**Comment by KA101** [comment]
's OK, you made sure sand's still findable and that was the only dealbreaker here.  Moving's not a joke and we realize that you need to look after your arrangements first.

**Pull request merged**
