### PR TITLE
Added recipes to extract seeds from some fruits and vegetables.

### PR DESCRIPTION
**Pull request by Kelenius**
Also put all seed recipes into a separate category in the crafting menu, because it was becoming cluttered.

This is based on #18262 and #18467 (it's pretty much just these two PRs combined).

Please tell me if you believe that something should be added or removed.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
For root plants like onion and sugar beet what do you need a knife (cutting tool) for, in those recipes? Same for grains like barley & oats?

**Comment by Kelenius** [comment]
To be honest, I have no idea how seeds are extracted from most plants IRL, and in some cases what these plants *are*. I've just added everything from the two PRs mentioned and removed parts that people objected to in the comments. What do you think should be changed?

**Comment by nexusmrsep** [comment]
> To be honest, I have no idea how seeds are extracted from most plants IRL, and in some cases what these plants are.

Ask Uncle Google :)

> I've just added everything from the two PRs mentioned and removed parts that people objected to in the comments. What do you think should be changed?

Onions and sugar beets are root vegetables, where root is the most usefull parts. However they grow seeds in the aboveground 'greens'. Those seeds can be planted to grow new vegetables (in contrary to potato, where you plant the potato itself and the root/bulb becomes 'mother' for new potatoes). 

So, there are two ways to approach this matter:
1. **simplified**: allow planting the vegetable itself (representing this cycle: plant the root, wait for it to grow seeds, plant seeds, multiply produce)
2. **simulationist**: separate seeds from the root (cannot plant the root itself as its considered a separate produce, plant seeds, they produce vegetables and more seeds as a byproduct for replanting).

You would need dev's opinion on this, in my opinion.

In both cases you cannot "extract" seeds from the produce, as it is not part of it anyway. It is rather a byproduct of the growth process. This i why i was surprised why they were included on the list, and why they need knife to extract seeds.

As for barley and oats, and all other grains and cereals: the usable parts of those type of plants are seeds themselves. If not processed, wheat (and other cereals including corn) can be planted directly and they grows into a plants that produce more wheat. There is no separate seed in this case. Solution is to either convert those items into their seed versions directly (no tool required) or, as someone mentioned in #18262, add seed info to the item itself (if the code can accept it from there).

**Comment by Kelenius** [comment]
Barley and oat doesn't require cutting to extract seeds.
Sugar beet and onion recipe removed.
Chilli pepper and wheat seed recipe added.

I might revisit sugar beets and onions in a different PR.

**Comment by nexusmrsep** [comment]
After some thought I'd personaly go for making seeds for onions and sugar beets, but instead giving them recipes to extract from the produce itself (which woud be unrealistic), add those seeds to seed spawn points and item groups, like in the gardening shop. And maybe with a slightly higher chance to spawn to compensate for that.

**Comment by ZhilkinSerg** [comment]
You probably won't need cutting for dandelion seeds:

image

**Comment by Kelenius** [comment]
>After some thought I'd personaly go for making seeds for onions and sugar beets, but instead giving them recipes to extract from the produce itself (which woud be unrealistic), add those seeds to seed spawn points and item groups, like in the gardening shop. And maybe with a slightly higher chance to spawn to compensate for that.

This is already a thing, actually, sans the higher spawn chance.

Dandelion seed recipe adjusted.

**Pull request merged**
