### PR TITLE
Machete proliferation

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Balance "Add the machete to relevant lootgroups."

#### Purpose of change
I was scrolling through the HHG, and realized that the common household machete, most often used for brush clearing and landscaping, was absurdly rare. This PR adds it to the relevant lootgroups. 

#### Describe the solution
Adds it to the gardening tools, hand tools, and household tools loot lists.

#### Describe alternatives you've considered
not doing that

#### Additional context
I don't know why it says there are 90 commits included, all I know is that this only changes 1 file.

### CODE REVIEW

**Comment by DukePaulAtreid3s** [comment]
What the hell?

**Comment by DukePaulAtreid3s** [comment]
Basic build test was being stupid.

**Comment by RedMisao** [comment]
Uhh, I'm guessing you PR'd this from the same branch you used to make the FBI profession? Regarding the 90 empty commits

**Comment by DukePaulAtreid3s** [comment]
This passed basic build

**Comment by DukePaulAtreid3s** [comment]
Why do you keep randomly failing the tests?

**Comment by akrieger** [comment]
I can honestly say I've never encountered a gardening machete in the US before, but that's fine.

**Comment by akrieger** [comment]
Is there any chance you can clean up the commit stack to remove all the extraneous ones?

**Comment by DukePaulAtreid3s** [comment]
> Is there any chance you can clean up the commit stack to remove all the extraneous ones?

I have no idea how, I tried purging my master file and it didn't work. I will avoid using master after this, but I don't have any recourse to fix it in the moment.

**Comment by akrieger** [comment]
With your permission I can try to fix it myself.

**Comment by DukePaulAtreid3s** [comment]
> With your permission I can try to fix it myself.

That would be lovely!

**Pull request merged**
