### PR TITLE
Give animals nightvision

### PR DESCRIPTION
**Pull request by Coolthulhu**
Animals get NV.

Most animals that have a degree of NV in real life get just 5. This includes deer, moose, dogs, wolves, foxes and coyotes.
This is more of an infighting thing, because at range 5 they can probably hear and smell the player already.

Cougars get NV range 10, because cats. Bears get NV 10, but only 30 day vision to represent the whole ursine vision thing.

Zombie animals get their living counterparts' nightvision, except zombears who keep 5 NV for now (zombears can actually kill people) and rott-weilers who get 10 NV and 30 day vision to make them stand out a bit from the far-more-common zombie dog.

Blind insects and spider gain 5 NV and 5 day vision so that infighting works for them. At 5 range, they'd sense the player anyway, so now they can sense all other stuff too.
Plus, the updated PLAYER_CLOSE triggers require seeing stuff for now.

Sewer animals get 1 day vision and night vision equal to their current day vision. A flashlight will blind them and force to rely on smell and sound.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Cervids really ought to have exceptional night vision, as their eyes are even better at seeing in the dark than a feline's.

**Comment by KA101** [comment]
Can add that in the merge if you'd like, as I'm holding on this for the cervid NV.

**Comment by Coolthulhu** [comment]
Tiny boost to moose (5->7) to be conservative with the changes for now, deer gets 5->12, because those never killed anybody.

**Comment by Zireael07** [comment]
LOL @ deer never killed anybody as opposed to moose.

**Comment by Rivet-the-Zombie** [comment]
>LOL @ deer never killed anybody as opposed to moose.

If we wanted to be particularly realistic/cruel we'd have them come hurtling through your windshield and mangle you when you hit one with your car, but that seems a bit punishing, even by DDA's standards.

**Pull request merged**
