### PR TITLE
[RDY][CR] Hugely speed up crafting GUI (improved inventory visiting + subset of recipes + unit tests)

### PR DESCRIPTION
**Pull request by codemime**
### Observable changes
- Crafting GUI works with huge amounts of stacked items much faster (see the numbers)
- Multi cooker menu works much-much faster (see the numbers)
- Players won't forget autolearned recipes they once knew, when their skills rust. If this change is undesirable, I'll revert it
- Actual recipe difficulty in the crafting info. Example:
  - Wish a copy of "Cooking on a Budget"
  - Set your fabrication and cooking skills to 2 (recipe requirements if you've learned it)
  - You cant craft a "charcoal smoker" (the book requires fabrication 3, it's harder there)
  - Increase your fabrication to 3
  - You can now see the recipe, but it deceptively shows "Difficulty: 2". Now it shows "Difficulty: 3" until either you or your companion learns it
- Books that your allies have in their inventories are also counted during crafting.
### Overview

Inventory `visitable` implementation is utterly inefficient in case of searching for sufficient qualities/amounts. It visits each and every indistinguishable item in the stack (see [the speed test](https://github.com/CleverRaven/Cataclysm-DDA/pull/18286#issuecomment-249492177)).

In this PR implemented visiting only the first item in the stack and multiplying by stack size.

As per the discussion in #18565:

When _crafting UI_, _item info_, or _multicooker menu_ get invoked, they perform these steps to acquire the actual list of available/known recipes:
- Construct (or get) a large vector of data (`recipe_dict::search()`, `recipe_dict::in_category()`, or even all recipes from the `recipe_dict`)
- Filter it out using map lookup (over `player::learned_recipes` or inventories in the `player::has_recipe()`) which, in a common case, turn the vector into a small one.

This looks quite wasteful and provokes performance losses. This PR changes the way available recipes are tracked. Since, in a common case, the player doesn't know all the recipes that exist, but a moderate amount of them, the new approach should be both faster and less memory consuming.

These changes speed up the multi-cooker and crafting UI, and, probably, some other places where the list of learned recipes, `inventory::amount_of()`, `inventory::charges_of()`, or `inventory::has_quality()` are used. Also, a couple of tweaks is applied to the crafting menu itself.
### Known limitations
- If skills were raised and then lowered without acquiring the list of known recipes, no new autolearn recipes will be learned this time.
### Implementation details
- Implemented `visitable<inventory>::amount_of()`, `visitable<inventory>::charges_of()` and `visitable<inventory>::has_quality()`. They work as described in the overview
- A new class `recipe_subset` is added. It contains a subset of recipes from the `recipe_dictionary` class
- `category` and `component` caches are moved from `recipe_dictionary` into the new class (that's where some memory is saved). These caches get updated each time a new recipe is added to the subset (the most usual case is when the player learns a new recipe), instead of adding all existing recipes from the dictionary on finalization (the finalization step should become faster)
- Accordingly, `search()` and `in_category()` are moved into the new class too (searching in a smaller set should be faster)
- Instead of `category` and `component`, `recipe_dictionary` caches `autolearn` recipes (there are not so many of them)
- Subset of learned recipes (including autolearned) now doesn't have any discrepancy with `player::knows_recipe()`. The latter simply calls the former
- The subset is private and it's cached. The cache gets invalidated each time player skills change (quite a rare event) so that some new `autolearn` recipes can be learned after that (via iterating over `recipe_dictionary::all_autolearn()`)
- The new `player::get_recipes_from_books()` and `player::get_available_recipes()` are executed one time per player/npc (instead of `player::has_recipe()` that gets executed for every recipe in the dictionary: lots of unnecessary work)
- `recipe_dictionary.h` became lightweight. It doesn't include `crafting.h` anymore
- Removed both overloaded instances of `recipe::can_make_with_inventory()`. They're pure middlemen that obscure expensive operations which are performed twice most of the time (first time before the invocation)
- `batch_recipes()` is inlined (it's also kinda misplaced middleman).
### Some numbers

| Phase | Before (ms) | After (ms) | Improvement |
| --- | --- | --- | --- |
| Multi cooker activation ' | 1158.8 | 11.1 | 104.4 |
| Building availability cache (FOOD tab) " | 2721.8 | 232.1 | 11.7 |
| Category search (FOOD tab) ' | 6.1 | 1.6 | 3.8 |
| Recipes finalization | 31.4 | 22.9 | 1.4 |

' Tested with cooking skill 0 and a companion with cooking skill 10
" Tested with 4000 rugs nearby and all recipes unlocked.

~~WIP because I'm still testing it and changes may follow. Also, I wanna make some performance measurements.~~

### CODE REVIEW

**Comment by Oskar636** [comment]
YAY! I do have a question though, does this repair the bug with the advanced crafting search?

**Comment by codemime** [comment]
No, the crafting search prefixes were removed in #18286, and I didn't recover them here. Can be added later (not in this PR though).

**Comment by Oskar636** [comment]
Ok, good to know.

**Comment by codemime** [comment]
Added unit tests. All set.

**Comment by mugling** [comment]
> It visits each and every indistinguishable item in the stack (see the speed test).

It did have an optimization to avoid that which we backed out of - I cannot remember the reasons though. You might want to check up on why that was.

**Comment by codemime** [comment]
> It did have an optimization to avoid that which we backed out of - I cannot remember the reasons though. You might want to check up on why that was. EDIT: Possibly #18175?

These changes have nothing to do with #18175. neither of `amount_of()`, `charges_of()`, `has_quality()` perform any manipulation with objects in the stack (unlike `remove_item()`). I haven't found a plausible way these optimisations can fail.

**Comment by Coolthulhu** [comment]
Doesn't seem to detect components.
I can get it to detect tools, but (some?) components fail to register.

For example, 10 (5 in inventory, 5 on map) pipes I spawned didn't register as components for makeshift crowbar. Toolbox registered just fine.

Then I cut up some clothes from a zed. Rags and leather patches did register.

A small plastic bottle that was on a vehicle did register.

It's not just item's location, though - moving pipes between inventory, map and vehicle doesn't help.

**Comment by codemime** [comment]
Can reproduce. I'm tackling it now.

**Comment by codemime** [comment]
Fixed. See  efee761.

**Pull request merged**
