### PR TITLE
Maintenance for recipes\weapons\ranged.json

### PR DESCRIPTION
**Pull request by Cyrano7**
Lint and reorder.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Main reason for the recipe difference was that it is supposed to be more makeshift than the forged, carefully made flintlocks. Same reason it has a lower level for crafting, and has an alternative recipe that involves cannibalizing two existing rifles.

Real-world multiple-barrel flintlock weapons tend to be rather rare and complex relative to single-shot versions, if I recall.

**Comment by DangerNoodle** [comment]
That said, if it is desirable from a balance perspective, either recipe system is fine by me. If any others have feedback on balance implications, such as @Coolthulhu?

**Comment by Cyrano7** [comment]
@DangerNoodle Ya I didn't see the description. IRL they used double barreleds for bird hunting. They weren't that rare honestly. But I'll leave it along for now.

**Comment by Coolthulhu** [comment]
I'd keep the flintlock recipes as simple as possible. They don't have much value at the point they're crafted.

**Comment by Cyrano7** [comment]
Since we are gonna leave these recipes alone for now this PR is not going to make any real changes. So i'm closing to bring the PR count down.

**Pull request closed without merging**
