### PR TITLE
Added motor to fridge deconstruction

### PR DESCRIPTION
**Pull request by Ker-Nes**
#### Summary

 `SUMMARY: Content "Added tiny motor to refrigerator"`

#### Purpose of change

The vast majority of fridges use a compressor to achieve cold. Compressors use an electric motor to compress things. Ergo, for realism, fridges should have motors. 

#### Describe the solution

Added a tiny motor to the deconstruction of the fridge and the glass door fridge. 

#### Describe alternatives you've considered

The motor in the compressor is not generally not a powerful motor, so used a tiny motor, although there are probably grounds to use a small motor instead as well.

### CODE REVIEW

**Comment by Pupsi-Mupsi** [comment]
Please add a "," at the end of the preceding lines.

{ "item": "cu_pipe", "count": [ 2, 5 ] },
{ "item": "motor_tiny", "count": 1 }

_and_

{ "item": "cu_pipe", "count": [ 3, 6 ] },
{ "item": "motor_tiny", "count": 1 }

**Comment by Pupsi-Mupsi** [comment]
jenkins rebuild

**Comment by Ker-Nes** [comment]
That should get the changes to the pull request I guess? I'm not yet quite familiar with how GitHub works.

And I thought about the minifreezer and minifridge, but they can't be currently disassembled, so I'd need to make the recipe from zero there. They probably should be, probably, but that's a subject for another time, as well as a recipe to craft them (or a makeshift low energy efficiency version perhaps), given that they aren't necessarily particularly high tech either.

**Comment by Pupsi-Mupsi** [comment]
jenkins rebuild

**Comment by Pupsi-Mupsi** [comment]
One more thing. Please add the following line or a similar one to your "#### Summary" section of your post.

`SUMMARY: Content "Added tiny motor to refrigerator"`

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> And I thought about the minifreezer and minifridge, but they can't be currently disassembled, so I'd need to make the recipe from zero there. They probably should be, probably, but that's a subject for another time, as well as a recipe to craft them (or a makeshift low energy efficiency version perhaps), given that they aren't necessarily particularly high tech either.

You are right. But maybe we could considere adding the tiny motor to **breaks_into**.
What do you think?

`https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_parts.json`

minifridge -> line 727 f.

```
    "breaks_into": [
      { "item": "steel_lump", "count": [ 8, 13 ] },
      { "item": "steel_chunk", "count": [ 8, 13 ] },
      { "item": "scrap", "count": [ 8, 13 ] },
      { "item": "hose", "prob": 50 },
      { "item": "motor_tiny", "prob": 50 },
]
```

and minifreezer

Line 751 f.

```
    "breaks_into": [
      { "item": "steel_lump", "count": [ 8, 13 ] },
      { "item": "steel_chunk", "count": [ 8, 13 ] },
      { "item": "scrap", "count": [ 8, 13 ] },
      { "item": "hose", "prob": 50 },
      { "item": "motor_tiny", "prob": 50 },
]
```

**Comment by Ker-Nes** [comment]
Like this for the summary? 

And on the break into, it's probably be a good idea, although I don't know quite how likely they'd be to be preserved if forcefully broken. Maybe at 25% chance instead?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Like this for the summary?

The form must be exat to pass one of the tests

SUMMARY: Content "Added tiny motor to refrigerator"

> 
> And on the break into, it's probably be a good idea, although I don't know quite how likely they'd be to be preserved if forcefully broken. Maybe at 25% chance instead?

Sure. 25% sounds good to me.

**Comment by Pupsi-Mupsi** [comment]
Good thinking: **{ "item": "motor_tiny", "prob": 25 }**

Now please change your summary to...

#### Summary

`SUMMARY: Content "Added tiny motor to refrigerator"`

**Comment by Ker-Nes** [comment]
> 
> 
> Good thinking: **{ "item": "motor_tiny", "prob": 25 }**
> 
> Now please change your summary to...
> #### Summary
> 
> `SUMMARY: Content "Added tiny motor to refrigerator"`

Like this? Or am I missing something obvious?

**Comment by Pupsi-Mupsi** [comment]
Add **SUMMARY:** in front of **Content "Added tiny motor to refrigerator"** and we#re good to go

**Comment by Pupsi-Mupsi** [comment]
jenkins rebuild

**Pull request merged**
