### PR TITLE
Give a makeshift funnel to the Naturalist

### PR DESCRIPTION
**Pull request by Mdnthrvst**
Should've had it much earlier. Now the naturalist is truly
self-sufficient. With the curing and tanning change, they wouldn't have
been able to get this from the jump.

### CODE REVIEW

**Comment by AllisonBW** [comment]
Idle curiosity: why makeshift?

**Comment by Mdnthrvst** [comment]
Because the Naturalist's shtick is that they don't use anything they can't make by hand out of natural materials. I was actually the one who lobbied for a makeshift funnel so that they could collect rainwater without resorting to plastic funnels, but I never added the funnel to their loadout until now.

**Comment by AllisonBW** [comment]
Makeshift funnel's actually made from a gallon jug, I think. What about the leather funnel? Would that be a better fit?

**Comment by Mdnthrvst** [comment]
...oh, wait. Leather funnel was what I meant. Stupid.

**Comment by KA101** [comment]
Should probably have more than one, since leather funnels aren't that efficient.

**Pull request closed without merging**
