### PR TITLE
NPCs will complain every 5 minutes if they're bleeding

### LINKED ISSUE #22893: NPCs won't complain about bleeding
There is `bleed_string` which is not utilized:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npcmove.cpp#L3077

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #22893.

### CODE REVIEW

**Comment by Mecares** [comment]
How long does bleeding last in game? I do not remember bleeding over a long period of time. Just checking to  make sure that the inverval is not bigger than a normal bleeding time.

**Comment by Night-Pryanik** [comment]
Tested a few times with my fellow NPC. He complained three or four times before bleeding auto-stopped.

**Comment by Night-Pryanik** [comment]
This is kinda doubling the current behavior - game already informs us about "NPC is losing blood".

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
> "My %s is bleeding!"

Damn we need more body parts...
http://www.lostprey.com/wp-content/uploads/2013/09/index2-210x170.jpg

**Pull request merged**
