### PR TITLE
Remove "ammo_bullet_762x25" material

### PR DESCRIPTION
**Pull request by Cyrano7**
It's overly complicated and the metal ratios are 1:1 anyways.

### CODE REVIEW

**Comment by mugling** [comment]
Idea is solid but I tested wrong branch - this has load errors

**Comment by Cyrano7** [comment]
@mugling My bad I for got to save the changes from that file.

**Comment by BorkBorkGoesTheCode** [comment]
Why are bullet recipes generic?

**Comment by mugling** [comment]
> Why are bullet recipes generic?

Different metal content is pure obfuscation

**Comment by BorkBorkGoesTheCode** [comment]
>Different metal content is pure obfuscation


I shouldn't have used the "using": method to create the recipe.

A explanation for future reference:

The lead requirements were based on the following comment from data/json/items/resources/metals.json:

`    "weight": 3, "//": "Density 11.34g/cm³ ~ 2.8kg/250ml @ stack 1000 = 3g/unit",`

**Comment by mugling** [comment]
Those values are for rough conservation of mass. We don't have precise enough units to represent different bullet weights and I don't see the need for that in any case.

**Pull request merged**
