### PR TITLE
Remove Shrubs from Dirt roads

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Bugfixes "Remove Shrubs from Dirt Road tile"

#### Purpose of change
Shrubs shouldn't grow in the middle of a dirt road.   Unless it's abandoned in which case it should be a different mapgen than normal dirt roads.

#### Describe the solution
Removes the shrub chance from mapgen for the "/" symbol used to create dirt roads.   I didn't remove groundcover because sometimes you can get some weeds but it's possible that groundcover also has things similar to shrubs that are hard on cars.  I leave that to other people to decide.

#### Describe alternatives you've considered
It's an easy and realistic change.  I've often complained about it myself but when I heard it on TheMurderUnicorn I was like why not look at how hard it is to fix.  Super easy it turns out. 

#### Testing
NA

### CODE REVIEW

**Comment by actual-nh** [comment]
Groundcover could be allowed for the edges of the roads, perhaps?

**Comment by Psiclops** [comment]
Isn't EVERY road abandoned in the cataclysm?

**Comment by anothersimulacrum** [comment]
Yes, it's been abandoned for a fairly brief period of time, it was actively maintained pre-cataclysm however.

**Comment by Maleclypse** [comment]
> Groundcover could be allowed for the edges of the roads, perhaps?

Are you suggesting I remove groundcover from the line where I removed shrubbery or editing the maps that dirt roads spawn on?

**Comment by actual-nh** [comment]
> > Groundcover could be allowed for the edges of the roads, perhaps?
> 
> Are you suggesting I remove groundcover from the line where I removed shrubbery or editing the maps that dirt roads spawn on?

The latter, but that can be left for later.

**Comment by faefux** [comment]
> Yes, it's been abandoned for a fairly brief period of time, it was actively maintained pre-cataclysm however.

They're dirt trails. And well.... local authorities... why are we assuming this to be true?

**Comment by Maleclypse** [comment]
> > Yes, it's been abandoned for a fairly brief period of time, it was actively maintained pre-cataclysm however.
> 
> They're dirt trails. And well.... local authorities... why are we assuming this to be true?

Because the houses have food in them that can rot per their itemspawns.

**Comment by faefux** [comment]
> > > Yes, it's been abandoned for a fairly brief period of time, it was actively maintained pre-cataclysm however.
> > 
> > 
> > They're dirt trails. And well.... local authorities... why are we assuming this to be true?
> 
> Because the houses have food in them that can rot per their itemsim

> > > Yes, it's been abandoned for a fairly brief period of time, it was actively maintained pre-cataclysm however.
> > 
> > 
> > They're dirt trails. And well.... local authorities... why are we assuming this to be true?
> 
> Because the houses have food in them that can rot per their itemspawns.

I'm sorry I do not see the connection.

**Comment by anothersimulacrum** [comment]
The people who live in the places that dirt roads leave to will maintain the dirt roads - and there were people there recently, as the food in those houses is rotting.

**Pull request merged**
