### PR TITLE
Conversion of nutrition to calories (kcal) - Part 1 of 3 - JSON parsing

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Infrastructure "Converted nutrition points to calories (kcal) - Part 1 of 3 - JSON parsing."```

#### Purpose of change
**This PR does not change or tweak any existing values, its just a conversion of units of the same value**

Three years ago, in PR #14613 @Coolthulhu provided infrastructure for converting `nutrition` points to actual `calories`. Since then it has not progressed, and i believe it was because no one had time to parse through JSON files and convert `nutrition` to `calories`. Until now.

Main calculation here was already in @Coolthulhu's infrastructure:

`/** 1 nutr ~= 8.7kcal (1 nutr/5min = 288 nutr/day at 2500kcal/day) */`

`static constexpr float kcal_per_nutr = 2500.0f / ( 12 * 24 );`

Actual value is more like 8.680555

And few of the comestibles were converted too, so I followed up with converting the rest.
**IMPORTANT**: The 'engine' is still converting calories in JSON to nutrition for hunger calculations, so this is just a part of a three-step job:
1. Convert nutrition to calories in JSON's to get rid of nutrition values, and clean the field for part 3.
2. Display CALORIES instead of NUTRITION to unlock the mindset and start thinking in calories instead of 
arbitrary nutrition points.
3. Switch the "engine" mechanics to do calculations of hunger in kcal and not in nutrition. Clean up the code from the nutrition to leave only calories behind. Tweak if needed.

#### Describe the solution
I'm lazy, and if i can do something with **wit** instead investing time, I do it that way.
So after some research it seems that in Vim you can use this expression:
image
to mass convert file content with included evaluation of a simple arithmetics.
This also guarantees that I haven't made any errors by calculating everything by hand entry after entry.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

**Comment by Inglonias** [comment]
Something to keep in mind: Dieting can be difficult (or it is for me) because all those really tasty junk foods like donuts and chips have a small volume (so they don't fill your stomach), are high in carbs (which are digested quickly), and are high in calories (which gets stored as fat).

I don't know what nutrition considerations a survivor would have to make, nor what their general calorie requirements are, but I don't want to have my survivor be sad because they ate delicious food that didn't actually fill them up.

Taking the starvation PR into consideration means that this could get very complicated very quickly if you're not careful.

**Comment by Zireael07** [comment]
@Inglonias: This part is just changing the units via automatic numerical conversion.

**Comment by Human-Shield** [comment]
Until we start simulating keto diets. :)

Calories are an important first step, then consider gameplay effects of getting all your calories from sugar or from animal protein and fat.

**Comment by Lamandus** [comment]
> 
> 
> Something to keep in mind: Dieting can be difficult (or it is for me) because all those really tasty junk foods like donuts and chips have a small volume (so they don't fill your stomach), are high in carbs (which are digested quickly, so you get hungry again), and are high in calories (which gets stored as fat).
> 
> I don't know what nutrition considerations a survivor would have to make, nor what their general calorie requirements are, but I don't want to have my survivor be sad because they ate delicious food that didn't actually fill them up.
> 
> Taking the starvation PR into consideration means that this could get very complicated very quickly if you're not careful.

it would be an idea to actually differentiate between calories and "filling". So you actually get hungry, you eat and the hungermeter is determined by "stomach filling". So you could either build up some fat, to lower the chance of malnutrition (but slows you down/lowers your stamina), or diet it down (filling but low on calories (anyone in for a salat?))

**Pull request merged**
