### PR TITLE
Balance sail recipe weight

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: Balance "Balance sail recipe weight"```

#### Purpose of change
The sail (945g) does not weigh the same as the sum of its components:

Components needed | Component weight in g | Component count | Total weight | Avg. weight
-- | -- | -- | -- | --
rag<BR>sheet | 80 g<BR>771 g | 40<BR>2 | 3200<BR>1542 | 2371
2x4<BR>stick<BR>stick_long | 1391 g<BR>1700 g<BR>3400 g | 10<BR>8<BR>4 | 13910<BR>13600<BR>13600 | 13703
nail | 4 g | 30 | 120 | 120
thread<BR>sinew<BR>plant_fibre<BR>yarn | 1 g<BR>1 g<BR>1 g<BR>1 g | 1x100x1<BR>1x100x1<BR>1x100x1<BR>1x100x1 | 100<BR>100<BR>100<BR>100 | 100
  |   |   | Total weight | 16294
  |   |   | Weight difference | -15349

#### Describe the solution
Increase the weight of the sail item and add byproducts to the recipe to compensate some of the loss that occurs when crafting. The game requires that reversible:true is removed when byproducts are used. Reversible:true does not make much sense for the sail in my opinion.

Now the weight is 14044g

Components needed | Component weight in g | Component count | Total weight | Avg. weight
-- | -- | -- | -- | --
rag<BR>sheet | 80 g<BR>771 g | 40<BR>2 | 3200<BR>1542 | 2371
2x4<BR>stick<BR>stick_long | 1391 g<BR>1700 g<BR>3400 g | 10<BR>8<BR>4 | 13910<BR>13600<BR>13600 | 13703
nail | 4 g | 30 | 120 | 120
thread<BR>sinew<BR>plant_fibre<BR>yarn | 1 g<BR>1 g<BR>1 g<BR>1 g | 1x100x1<BR>1x100x1<BR>1x100x1<BR>1x100x1 | 100<BR>100<BR>100<BR>100 | 100
  |   |   | Total weight | 16294
Byproducts: |   |   |   |  
splinter | 225 g | 10 | 2250 | -2250
  |   |   | Weight difference | 0

#### Describe alternatives you've considered
Not use byproducts and just make the sail item weigh as much as its components
or reduce the amount of components but I can't imagine crafting a sail with anything less then 4 long sticks

#### Testing
image

#### Additional context
N/A

### CODE REVIEW

**Comment by Zireael07** [comment]
Most modern sails are triangular in shape and all you need is two sticks (mast and boom).
Also sails are generally lightweight, 14 kg for a sail is unrealistic. 1-2 kg would be enough, at most 3-4 if we include the sticks.

**Comment by snipercup** [comment]
If I cut two long sticks, 4 sticks and 5 planks, the weight will be reduced by  about 6.84kg, and the sail will end up at about 7.45kg, still taking the 20 splinters byproduct into account. Without the splinters the sail would weigh nearly 10kg.

I'd need some help to bring it down to 3-4. Have any idea on how to cut down the weight without having materials disappearing?

**Comment by Zireael07** [comment]
Looks like I wasn't much off: https://forums.sailboatowners.com/threads/how-much-does-a-sail-weigh.145059/post-953776 (3.5 oz is around 0.1 kg apparently)

I forgot to mention most modern sails are made of synthetic materials (nylon, dacron).

Post number 4 here http://forum.woodenboat.com/showthread.php?8082-cotton-canvas-sails seems to make a comparison between premodern sails (canvas, cotton) and modern. 69 sq ft is 6 m2, so a fairly typical main sail. They say 10 oz for such a sail, so still very very light.

I have no idea how to find a weight for a wooden boom/mast combo since pretty much all modern boats have metal rigging, but without any doubt it'd be the main contributor to the total weight of our "sail" recipe (maybe split the current sail into "sail" and "rigging", it'd probably be easier to balance components that way?)

**Comment by snipercup** [comment]
Now I get where the initial 945g came from. it is indeed very light. I guess that would be for a metal sail. perhaps that should be a different item that uses a recipe with metal components instead of wood. This item is made of wood however and I can't see how I can make it anything less then the 7.45kg.

**Comment by Zireael07** [comment]
I must be missing something in the equations, though, as there's no way the stated 10 oz. is for a full **cotton** sail (it's probably the weight of some standard size of material, but I can't find what the standard size is). I asked my Mum, who was sailing in the 70s and 80s, before the advent of synthetic sail cloths, and she says 1 kg for the cotton sail itself, sans any rigging, "sounds about right".

So, for the sail part:
2 sheets = 1542 g or a roughly equivalent weight in rags (20 sounds about right if I haven't borked my maths)
For the rigging:
(assuming a triangular sail, we need only two sticks)
one long stick, 3400 g (we assume the survivor breaks it in half probably)
two sticks, 2x1700g
two planks, 2x1391g
For a premodern square sail, it's three sticks @ 3x1700g or three planks @ 3x1391g, but we'd have to exclude the long stick as it's impossible to make the weights sensible in that case
A square sail would be much easier to make for a survivor, but as I said, there's a problem with weights.
That's 1,5 kg for the sail (one sheet is too light and we can't really have "one and a half") and anywhere between 2,7 and 3,4 kg for the rigging (triangular sail), so some 4,2-4,9 kg total.

**Comment by snipercup** [comment]
Thanks for helping with the weight calculations. I appreciate it. The sail's description leaves it quite open for interpretation. If the components are reduced by much then I can't imagine anything other then a triangular sail the size of a person or smaller. 

It's supposed to support 2 sheets. is it possible to support 2 sheets with 2 sticks or 2 planks?

Also you mentioned separating the sail and the rigging. I figured I will remove the 'rags' component and just leave the sheets in the recipe. The survivor can craft a couple of sheets first before crafting the sail. This will help with the required time for crafting as well.

**Comment by Zireael07** [comment]
A 6m2 triangular sail is indeed roughly the size of a person. Good point concerning removing the rags.

If you have 2 separate sheets, then by definition you have multiple sails such as the pink ones in the picture: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Krusenstern_bowsprit_jibs.jpg/220px-Krusenstern_bowsprit_jibs.jpg (the white sails are the premodern square shapes I keep mentioning)
If you combine 2 sheets into a single sail, then 2 sticks is enough - see https://en.wikipedia.org/wiki/Sloop, a vast majority of modern non-seagoing yachts are sloops. A ketch, which has two masts, is bigger and I can't imagine a survivor wanting to use that much material on a DIY boat. And since we don't have the coast yet, I imagine any boat in CDDA is by definition non-seagoing)

**Comment by snipercup** [comment]
Getting a image of the sail really helps. Now I can see a possiblity of the sticks being enough. I'll adjust the PR based on our discussion so far and see how that looks.

**Comment by snipercup** [comment]
So now we got this:

Components needed | Component weight in g | Component count | Total weight | Avg. weight
-- | -- | -- | -- | --
sheet | 771 g | 2 | 1542 | 1542
2x4<BR>stick | 1391 g<BR>1700 g | 2<BR>2 | 2782<BR>3400 | 3091
nail | 4 g | 20 | 80 | 80
thread<BR>sinew<BR>plant_fibre<BR>yarn | 1 g<BR>1 g<BR>1 g<BR>1 g | 1x100x1<BR>1x100x1<BR>1x100x1<BR>1x100x1 | 100<BR>100<BR>100<BR>100 | 100
  |   |   | Total weight | 4813
  |   |   | Weight difference | 0

I think this is okay. I checked the vehicle part and its power is the same as hand paddles so we're not talking about a huge sail.

**Comment by mlangsdorf** [comment]
The default sail is supposed to be an improvised square sail with cotton sheets, as that's the kind of sail a completely inexperienced survivor would put together.  dpwb and I discussed this briefly when he was writing the initial sailing code.

There should also be an intermediate sail that is a proper bermuda rig.  That sail would be lighter and have better performance but also be more complicated to build.  Finally, there should be a pre-Cataclysm sailing rig which would be a proper metal and nylon bermuda rig and might not be craftable.

**Comment by snipercup** [comment]
Thanks for your input. So the sail i'm trying to balance is the basic square sail. Would you say the components listed in the PR are sufficient for that or should I put one or two long sticks and some planks/sticks back into the recipe? This will increase the weight of course.

**Comment by snipercup** [comment]
Added 2 planks and 2 sticks:

Components needed | Component weight in g | Component count | Total weight | Avg. weight
-- | -- | -- | -- | --
sheet | 771 g | 2 | 1542 | 1542
2x4<BR>stick | 1391 g<BR>1700 g | 4<BR>4 | 5564<BR>6800 | 6182
nail | 4 g | 20 | 80 | 80
thread<BR>sinew<BR>plant_fibre<BR>yarn | 1 g<BR>1 g<BR>1 g<BR>1 g | 1x100x1<BR>1x100x1<BR>1x100x1<BR>1x100x1 | 100<BR>100<BR>100<BR>100 | 100
  |   |   | Total weight | 7904
  |   |   | Weight difference | 0

now it's a square sail with one plank/stick on each side and 2 sheets to make the sail. Please review/merge.

**Comment by mlangsdorf** [comment]
looks good, thanks for making the changes.

**Pull request merged**
