### PR TITLE
[CR] No Survivor Zombies Mod

### PR DESCRIPTION
**Pull request by DeadLeaves**
Right now, this is what I use to get rid of the ridiculous items you can get from these zombies. They aren't very rare or difficult to kill. Yet they give among the best gear in the game. The survivor gear which IMO should be something to strive for to create instead of just finding while looting a basement.

I tried, and discussed other solutions in IRC, but we came up with nothing. What I most would want is to override the item drops for the survivor zombies, but all my different attempts did nothing. 

What I tried without success:
- Removing the survivor gear categories from the zombies.
- Changing all categories to have 0 probability. (And adding probability to those that did not have probability set)

Don't get me wrong, I love the survivor zombies and would love to have them in my game. They add much flavor and some challenge early game. But as it is now, they simply have way to good loot.

### CODE REVIEW

**Comment by Malkeus** [comment]
They could receive a massive buff like the soldier zombies did. If their
stats actually represented a fully armored and possibly well armed being
that was a challenge to kill, then the drops wouldn't be that extreme. You
are completely accurate about the current version being loot piñata's
though.

**Comment by Rivet-the-Zombie** [comment]
Survivor zeds haven't had their stats adjusted in quite a long time; more armor would be an immense improvement there.

**Comment by DeadLeaves** [comment]
While I agree totally with the fact that they need major buffs. The fact that they still drop a ton of amazing gear still need to be rectified. as it stands now they drop one "survivor item group" item for each major body part. If they drop ONE survivor item total it'd be fine. And what  survivor items they drop should be in even worse state than they currently are in.

**Comment by Malkeus** [comment]
That's why I specifically mentioned the soldiers, their drops were revised
along with the buff.

**Comment by Coolthulhu** [comment]
Boosting their armor is one thing, but they shouldn't drop survivor grade armor.

Survivors strong enough to craft this kind of stuff wouldn't be killed just like that - they'd be either overwhelmed by groups of hulks, assassinated by fellow survivors or grenaded by a grenadier zed.
Survivor zombies are just zombies of those people who were good enough to craft knife spears and leather armor rather than just panicking and dying within hours of the start of the cataclysm. That's level 3-5 of skills, not lvl 7 that survivor gear requires.

We could then have a "veteran survivor zombie" with stats better than hulks, that would drop survivor grade stuff.

**Comment by DeadLeaves** [comment]
I agree 100% @Coolthulhu survival grade armor is just way too strong to drop from survivor zeds.. Love the idea of veteran survivor zombies as well.

**Comment by Malkeus** [comment]
:+1:

**Comment by kevingranade** [comment]
I think coolthulu nailed it.

**Comment by DeadLeaves** [comment]
Ill close this, and start working on what coolthulhu suggested.

**Pull request closed without merging**
