### PR TITLE
refugee caravan

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "refugee caravan"

#### Purpose of change

Make world feel more alive, at least in early game

#### Describe the solution

Builds off #56629 with different dialogue, removes trading and adds a new mission to go to a FEMA camp and a recruitable NPC using the new SKILL_CHECK

#### Describe alternatives you've considered

More refugees, spawn them with monsters trying to murder them (map spawn will take care of that sometimes), more variations. Some kind of winter encounter, maybe a hungry hunting party? Place the correct corpses at the FEMA camp to be found, delete the originals when they are found if they haven't been deleted already. Create new custom classes instead of generic scavenger class. Create a new custom faction for them.

#### Testing

Runs no errors, can't seem to figure out a way to test. Plenty of rest stops spawning but I don't see my refugees anywhere. Increased spawn five times for testing again later

#### Additional context

Thanks for all the recent NPC work making this possible, I've been wanting this forever

### CODE REVIEW

**Comment by LyleSY** [comment]
@Ilysen can you look at what I have? I'm getting errors but I copied it straight from doc. It's yelling about no skill_required entry

**Comment by Ilysen** [comment]
Thaaat would be because I updated the docs with the wrong info. Whoops. Try replacing `skill_id` with `skill_required`, and if it works, I can correct the docs.

**Comment by Ilysen** [comment]
I've got a PR open to fix the docs - #57118 - so you don't need to fix it here. Thanks though ^^;

**Comment by I-am-Erk** [comment]
To test it, turn the chance to 100% with the rest stop out of your bubble for a bit, then head over. When you've confirmed you can get it to spawn at 100% chance, turn the value down and you should be good

**Comment by LyleSY** [comment]
I'm not having any luck with 1 in 1 chance. I tried a few variations on waiting, including just standing a long way away for two hours. Am I missing a step?

**Comment by LyleSY** [comment]
Still no luck, not sure what I'm doing wrong here

**Pull request closed without merging**
