### PR TITLE
Magiclysm golem tweaks

### LINKED ISSUE #47208: (Magiclysm) Golems bleed mechanical fluids
# Describe the bug

#46603 added a bleeding for robots. Apparently, golems are considered robots by the game

# Steps To Reproduce

1: spawn a golem
2: hurt the golem
3: slip on the fresh mechanical fluid it leaked

# Expected behavior

Golems are magical constructs and thus don’t need mechanical fluids

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-9280g9dde4db-dirty [32-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions, magiclysm

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
None
#### Purpose of change

With #47152 I set `factionless` monsters to have `by_mood` relation to each other, since it's more or less a fallback faction anyway. This accidentally made plastic golems very disappointed that they for some reason aren't part of the `robot` faction like their golem buddies and flew into a golemicidal rage. That makes looting wizard towers too easy, and we can't have that. (as yet unreported)
In addition, golems were lacking a custom species, making them susceptible to being hacked and bleeding mechanical fluid. (closes #47208 )
 
#### Describe the solution

Add plastic golems to the `robot` faction.
Create a custom species to prevent golems from bleeding, being influenced by a control laptop or the Hub01 dazzle gun. 

#### Describe alternatives you've considered

Screaming "not it" on Discord when I realized I slightly broke something *again*. I'll keep that option open for when I mess up properly.

#### Testing

Loaded an unmodified game, spawned a gun and teleported to a wizard's tower. Plastic golems were hitting each other inside, when shot bled mechanical fluid. Applied the changes, no golem-on-golem violence observed, they also didn't bleed when shot.

#### Additional context

The only hardcoded interactions that got activated by them not being robots are dissectors complaining about inorganic stuff, but those became/will become exposed wiring anyway and blob traps being able to slimify them. Since they spend little time in labs I don't think either of those are a real problem.

### CODE REVIEW

**Comment by actual-nh** [comment]
Do they wind up with `factionless` due to, well, not having a faction specified, or what?

**Comment by Venera3** [comment]
No, they were declared as factionless for some reason unlike the rest of the gang.

**Comment by actual-nh** [comment]
> No, they were declared as factionless for some reason unlike the rest of the gang.

One might consider this as revealing an earlier bug, not actually introducing one!

**Comment by actual-nh** [comment]
BTW - you might add "Fixes: #47208".

**Comment by Venera3** [comment]
That's gonna be the official story from this point on. Hopefully I'll one of these days learn to do a recursive search at least in \mods for stuff I change.

**Pull request merged**
