### PR TITLE
Update plate armor materials.

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Balance "Updates plate armor and ornamental plate armor."

#### Purpose of change
Both types of plate armor are currently 50% steel and 50% leather. This results in underperforming plate.

#### Describe the solution
Change material ratios to 9 steel : 1 leather.

#### Describe alternatives you've considered
None

#### Testing
Spawn item, note updated defensive values.

#### Additional context
Thanks to anoobindisguise for bringing this up.

### CODE REVIEW

**Comment by kevingranade** [comment]
"Noted defensive values", which are?

**Comment by anoobindisguise** [comment]
Based on 9/10 steel and 1/10 leather this would give 22 slash/bash defense and 11.2 ballistic defense. This probably makes ballistic and bash defense values too high. However considering that even a Nodachi (44 cut) or Zweihander (38 cut) would be completely unable to draw blood from a foe wearing plate armor the cut protection should be considerably higher. The best thing to do would IMO probably to boost the cut defense of steel/iron considerably (like, 10 per mm for steel armor) and lower bash (3 per mm) and ballistic (2 per mm). Swords cutting through plate armor makes no sense at all. Even a humble broadsword does 27 cut, which is more than enough to cut through plate's 16 cut defense.

**Comment by Drew4484** [comment]
> "Noted defensive values", which are?
Item: Bash/Cut/Ballistic
Coif: 10/10/6 
Vest: 10/10/6
Sleeves: 10/10/6
Leggings: 10/10/6
Chausses: 10/10/6
Gloves: 7/7/4
Gloves are slightly higher at thickness 2, at thickness 1 they're worse than before, 3.5/3.5/2.

**Comment by kevingranade** [comment]
Thickness numbers are off as I didn't revisit "real" armor when I overhauled thickness.
I haven't had any luck with digging up good direct sources, but tertiary "everyone knows" type sources put peak armor thickness at 0.7 - 4mm.
The light plate could probably drop to thickness 1 (not at the thinnest, but close) and the heavy plate we could truncate to 4mm.  In both cases that would still be quite a buff, and then we can follow up later with suit of armor tests (remember that includes plate and gambeston and probably some chain  etc) to fine tune the material contribution to defence.

> considering that even a Nodachi (44 cut) or Zweihander (38 cut) would be completely unable to draw blood from a foe wearing plate armor

Source?

**Comment by anoobindisguise** [comment]
I assume hundreds of randoms on every forum in existence all saying no weapon will cut through plate doesn't count as evidence. 
I could link you dozens of videos all saying the same thing but here are a couple standouts.

https://www.youtube.com/watch?v=qw62NV0bUTg - Skallagrim forges a chunk of plating out of mild steel and tests it.

https://www.youtube.com/watch?v=O9eCzG8AAoQ - unable to cut armor with a bigass claymore, blunt force trauma would kill though. that's bashing damage, and the zwei does a lot of bashing damage.

You can mess someone up with blunt trauma under their armor, but you cannot cut through it. You can stab through a weak point but not through the metal parts.

**Comment by Drew4484** [comment]
> Thickness numbers are off as I didn't revisit "real" armor when I overhauled thickness.
> I haven't had any luck with digging up good direct sources, but tertiary "everyone knows" type sources put peak armor thickness at 0.7 - 4mm.
> The light plate could probably drop to thickness 1 (not at the thinnest, but close) and the heavy plate we could truncate to 4mm.  In both cases that would still be quite a buff, and then we can follow up later with suit of armor tests (remember that includes plate and gambeston and probably some chain  etc) to fine tune the material contribution to defence.
> 
> > considering that even a Nodachi (44 cut) or Zweihander (38 cut) would be completely unable to draw blood from a foe wearing plate armor
> 
> Source?
 https://pdfs.semanticscholar.org/49fc/b3e3857824a0c0fb543ec226b6a6b8c06bd9.pdf
Breakdown of a 15th century German suit of field plate. Thickest measure of the chest plate is 1.6mm (page 11). The suit itself is parts from five different pieces but they're considered accurate. The co-author is Alan Williams who wrote The Knight and The Blast Furnace.

**Comment by Drew4484** [comment]
The Knight and the Blast Furnace lists examples of breastplates up to 8mm(!) after gunpowder became common. It also notes that those uncommon suits were upwards of 25kg. 4mm was common, and mentioned as the heaviest comfortable armor. 6mm was available.

May be a place for a third suit based on this, 2/4/6?

**Comment by Drew4484** [comment]
Projectile resistance of 2mm mild steel, comparable to SAE 1015 steel. Note the effectiveness of 4mm plate.
image
Approximate energy of melee and firearm attacks.
image

**Comment by kevingranade** [comment]
Yea sure, just needs an appropriate weight and encumbrance, and FYI that higher weight is going to have more impacts later. I.e. running around and fighting in equestrian plate isn't going to work out well.

**Comment by Drew4484** [comment]
> Yea sure, just needs an appropriate weight and encumbrance, and FYI that higher weight is going to have more impacts later. I.e. running around and fighting in equestrian plate isn't going to work out well.

Most of this is based on a limited number of sources and I'm sure there are counterexamples for my points. That being said: 

Suits for infantry (in this source) max out at around 4mm breastplate, but consistently thinner for limbs. Weight is noted as the biggest deterrent, with stamina being an issue at 3mm or more for the breastplate. It doesn't appear that range of motion was significantly impacted in production armors since the thickness for the arms and legs remained lower. These exclude the heavier tournament armors, which are more encumbering. 

Almost all of these examples are using heat-treated steel, not as good as modern techniques due to quality control issues. Less effective treatment could be done more consistently, so part of the increase in thickness comes from adding more decent steel rather than the higher cost of very good steel. Modern metallurgy can produce much better hardened steel, but a survivor's practical limit for creating new metal would probably match the level of 1600s historical armor.

In #53875 I'm currently splitting existing steel into low/med/high/ultra carbon steels, leaving hardened steel as-is. The low carbon steel is a good plate armor grade, a case-hardened suit would probably be the peak of a survivor's camp crafting. 

I would look at 1mm - 2mm for limbs for all suits, and then 2/4/6 for the torso for a light/medium/heavy plate. Weights would be around 15/20/25 kg respectively. Could also add a variety for hardened/non-hardened.

**Comment by kevingranade** [comment]
That all seems reasonable.

**Comment by Terrorforge** [comment]
> Based on 9/10 steel and 1/10 leather this would give 22 slash/bash defense and 11.2 ballistic defense. This probably makes ballistic and bash defense values too high. However considering that even a Nodachi (44 cut) or Zweihander (38 cut) would be completely unable to draw blood from a foe wearing plate armor the cut protection should be considerably higher. The best thing to do would IMO probably to boost the cut defense of steel/iron considerably (like, 10 per mm for steel armor) and lower bash (3-4 per mm of steel) and ballistic (2 per mm of steel). Swords cutting through plate armor makes no sense at all. Even a humble broadsword does 27 cut, which is more than enough to cut through plate's 16 cut defense.

I have to point out that this argument is... not necessarily wrong, but it gets weird because players/NPCs and monsters play by completely different melee damage rules. 27 damage is about the average of the Melded Task Force, one of if not the hardest-hitting monster in the game. The absolute maximum it's capable of is 45. If you balance any armor to resist the 40+ damage of high-tier weapons, that will translate to complete immunity to that damage type, coverage aside. And while I get that a broadsword shouldn't be able to cut through steel plate, I'm not sure the same thing applies to the claws of a one-tonne mutant mantis.

Of course, another wrinkle is that virtually no monster actually deals a whole lot of cutting damage. The highest I've found is the aforementioned Great Mantis at 15. So the existing plate armor already does make you virtually immune to cutting damage, NPCs with broadswords notwithstanding.

**Comment by Drew4484** [comment]
The toughest armor this adds is tempered 6 mm plate, offering 25.59 bash and cut protection. Strong but not invincible.

**Pull request merged**
