### PR TITLE
add road stop roofs

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
```SUMMARY: Content "Add road stops/rest stop roofs"```

#### Purpose of change
Continues roof project.  Basic roofs & terrain cleanup

#### Additional context
rest area:
rest area
rest area roof

rest stop
reststop
reststop roof

roadstop a
roadstop a
roadstop a roof

roadstop b
roadstop b
roadstop b roof

### CODE REVIEW

**Comment by aoae23** [comment]
Keep up the fine work!

**Comment by FulcrumA** [comment]
As always, thanks for working on it. A question though: why is rest area sporting a satellite dish? I don't recall it having any TVs, computer terminals etc.

**Comment by Night-Pryanik** [comment]
Rest stop - are there a tables enclosed by wooden walls in the center, with no place to sit near them?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Rest stop - are there a tables enclosed by wooden walls in the center, with no place to sit near them?

I imagine these are not tables to eat or sit at, but some kind of counters to keep local maps, guides and such.

**Comment by curstwist** [comment]
re: rest stop. yeah i didn't design them. I assume they were going for a covered overhand feel for a display as ZS suggested.

this sat dish is the small variant that is along the lines of a Dish satellite for TV/internet access. It doesn't require huge IT infrastructure to use and is most likely for a tv/wifi.  suppose someone already looted the tv/wifi here.

**Comment by curstwist** [comment]
jenkins rebuild

**Pull request merged**
