### PR TITLE
Remove zlaves

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: None

#### Purpose of change
Zlaves don't make a whole lot of sense. Somehow, with a little bit of first aid knowledge, you can completely disable all functions of a zombie.
A more sensible implementation of zlaves would have ones that can only physically attack trying to bump into you, and and any ones that can special attack still be able to do that.
Past all that, they would at least slowly regain lost function, much like they revive.
This makes them effectively useless, so let's skip that work, and just cut them out.

#### Describe the solution
Remove enzlave action, and edit notes referring to them. Remove zlave activity handler, iuse actor, and monster attitude. Remove remaining references to those things. Add activity migration code for the zlave activity.

#### Testing
Load [this save](https://github.com/CleverRaven/Cataclysm-DDA/files/4613256/Badger.zip), which contains a player doing `ACT_MAKE_ZLAVE`, an active zlave, and a corpse that has been turned into a zlave.

#### Additional context
Any zlaves currently existing will still count as player pets.

### CODE REVIEW

**Comment by Mecares** [comment]
I just want to say that i welcome the direction towards realism the game develops towards, because i anticipate an outcry from the upset and loud crowd that envisions another direction for the game. Maybe moving it a mod would lessen the inevitable moaning that is soon to happen, following this change.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
i generally agree with the direction the game is going, but this was just pretty un-c:dda for me. 
i more expected that you to add their skills and making them a bit harder to make.

**Comment by EvgenijM86** [comment]
Was it intentional that I can no longer push a cow, because you cannot make zlave anymore?

**Comment by anothersimulacrum** [comment]
Nope, sorry about that. I'll fix it.

**Pull request merged**
