### PR TITLE
Change Yule Cat harvest to mutant mammal

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
None

#### Purpose of change

The other magical creatures don't have normal meat, but the Yule Cat does. This seems to be an oversight.

#### Describe the solution

Change its harvest entry to ``mutant_mammal_fur``.

#### Describe alternatives you've considered

Not doing it.

#### Testing

Load game, butcher the kitty.

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @Theawesomeboophis?

**Comment by Theawesomeboophis** [comment]
The only problem I have with this is Yulecat's aren't mutated, they're magic big cats, mammal_fur imo seems suitable for now until a new harvest is introduced for magic animals.

**Comment by Theawesomeboophis** [comment]
I propose an alternative to change it to mammal_large_fur as they are not mutated ( I think there's a lore reason owlbears drop mutant meat), It may be worth it to introduce a new type of meat for magic animals, this new type of meat could also maybe slightly replenish mana or something.

**Comment by Theawesomeboophis** [comment]
This is suitable for now, I will be adding a new material later on, but it may take a while.

**Review by Theawesomeboophis — APPROVED** [review]

**Pull request merged**
