### PR TITLE
Adds personal hygiene kits.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Changes soap into an ammunition type rather than an icky comestible and tweaks its recipe.
Makes razor blades a bit more common.
Adds scissors recipe to forge.

New items:
**electric hair trimmer** - uses batteries, gives morale boost, craftable via book
**makeshift haircut kit** - requires no ammunition, but is larger and heavier than the electric trimmer version, craftable
**shaving kit** - uses soap, gives morale boost, noncraftable
**makeshift shaving kit** - uses soap, is larger and heavier than the pre-cataclysm version, craftable

Morale bonuses granted by using the various kits are inferior to the ones granted by visiting the NPC barber.
New item spawn locations are included in commits.

### CODE REVIEW

**Comment by kevingranade** [comment]
What's the meaning of this two-bit PR?
(I couldn't resist)

**Comment by Rivet-the-Zombie** [comment]
Two minutes before the first shave-and-a-haircut joke. I'm impressed!

**Comment by Coolthulhu** [comment]
This is one fast trimmer there: 36 seconds for a full trim.
Copypasting vibrator effects would probably fit better here and wouldn't be much more work.

**Comment by Rivet-the-Zombie** [comment]
It's really only intended to be a trim, but that's still a good point about the time. I'll boost it just a bit.

**Comment by Zireael07** [comment]
Cool!

How about a soap using item for females? I can't see a girl using a shaving kit :D

**Comment by Rivet-the-Zombie** [comment]
I'm female and I'd want some sort of shaving kit in this situation. I went with these two because the morale effects are already there (less work for me) and because they're readily unisex.

**Comment by tyrael93** [comment]
Could yo use this every two minutes to get a infinite free morale boost?

**Comment by Rivet-the-Zombie** [comment]
No. The morale boost is small, fairly long-lasting, and doesn't stack with itself.

**Comment by DavidKeaton** [comment]
@Zireael07 gotta keep them legs smooth! water and air resistance is a bitch! ;^)

**Pull request merged**
