### PR TITLE
Fix spear circular attack range

### LINKED ISSUE #24750: Autoattack outreaches aimed attacks in circular distance mode with range attack weapon
Game version: 0.C-30226

Operating system: Mac

Tiles or curses: Tiles

Mods active: default

### Expected behaviour

Autoattack (`tab`) can only hit the same enemies targetable with `f`

### Actual behaviour

While welding a range attack melee weapon (eg knife spear), an enemy two diagonal spaces away can be hit with Autoattack (`tab`) but can not targeted manually.

This behaves as expected in non-circular distance mode.

autoattack
aimed

Note that `REACH3` (awl pike) weapons seem to behave as expected.

### Steps to reproduce the behaviour

Enable circular distances mode, and while holding a knife spear, use an Autoattack (`tab`) when a monster is two diagonal spaces away, compared to targeting them with `f`. 

Credit for discovering to BradaZnanja

### PR DESCRIPTION
**Pull request by ssorpg**
Hello everyone! First PR here and looking to help bugfix. I've just recently begun coding and I'd love to start contributing to Cata. I'm not 100% sure this is the right way to fix this bug, so if there are any suggestions on a better method I'm all ears.

#### Summary
```SUMMARY: Bugfixes "Fixes the autoattack range for HAS_REACH weapons when the gameworld is circular."```

#### Purpose of change
Fixes #24750

#### Describe the solution
In get_hostile_creatures(), check whether the game is circularized and change the distance formula accordingly so autoattack range matches aimed attack range.

### CODE REVIEW

**Comment by kevingranade** [comment]
Good find, this looks like it will do the right thing, just need to test a few different things to make sure it doesnt change something unexpected.

It should work the same if you do std::round( rl_dist() ), since the distance returned when !trigdist is always an integer.

**Comment by ssorpg** [comment]
Okay, let me know if this is what you meant, thanks!

**Comment by kevingranade** [comment]
Actually I'm wrong and you're right, I forgot rl_dist() was returning an int, and therefore truncated the value before returning it.  The whole point of applying round() to both was to collapse it back to a single invocation of round( rl_dist() ), but that's not possible without changing the return value of rl_dist()  (which we should probably do, but not right now).

**Comment by ssorpg** [comment]
Ah okay, all good!

**Pull request merged**
