### PR TITLE
Allow zweihänder to fit in "back scabbard"

### LINKED ISSUE #45071: Zweihänder can't be put into a (back) scabbard
# Describe the bug
The discription of the Zweihänder states, that it can be put in a scabbard. But sadly it can't.

# Steps To Reproduce
1. Have a Zweihänder.
2. Try to put it into a back scabbard.
3. No Profit

# Expected behavior
Putting it in it, as the description says.

# Screenshots
grafik
grafik

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7143-g19c7921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    Fewer Farms [Fewer_Farms],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Dark Days of the Dead [classic_zombies]
]

# Solution
Either remove the description, OR let the back Scarbard have items up to 180 cm inside them. Or make the Zweihänder smaller (in the early middle ages they were just 110 cm long, later up to 2 meter, but we don't need to overdo that).

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

 `SUMMARY: None`

#### Purpose of change

Allow zweihänder to fit in "back scabbard"
This closes #45071.

A picture is worth a thousand words.

grafik

### CODE REVIEW

**Comment by wapcaplet** [comment]
Two of the three zweihanders (fake and inferior) are 200 cm in length (my bad, commit 88fb854ae93) and still won't fit. Those should probably be reduced to match the "real" zweihander length of 180 cm.

The "moves" value of 20 for the back scabbard is probably too little. I can sheath and unsheath the zweihander from a back scabbard 4 times in less than 1 second. This quick draw may be more appropriate for shorter swords, but I don't think there's a way to increase it based on sword length. Seems like it should take at least 1 full second to pull any sword from a back scabbard due to the awkward motion involved, but I have no experience in this area.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Two of the three zweihanders (fake and inferior) are 200 cm in length (my bad, commit [88fb854](https://github.com/CleverRaven/Cataclysm-DDA/commit/88fb854ae93d42b4c59de73fe1585bb4bd8745cf)) and still won't fit. Those should probably be reduced to match the "real" zweihander length of 180 cm.

-> Changed. Thanks!

> The "moves" value of 20 for the back scabbard is probably too little. I can sheath and unsheath the zweihander from a back scabbard 4 times in less than 1 second. This quick draw may be more appropriate for shorter swords, but I don't think there's a way to increase it based on sword length. Seems like it should take at least 1 full second to pull any sword from a back scabbard due to the awkward motion involved, but I have no experience in this area.

-> I agree. But I'm not an expert on things like that.  Tripled moves. Are you okay with that?

**Comment by Pupsi-Mupsi** [comment]
https://www.youtube.com/watch?v=xoMLrKInT8g
;-)

**Comment by Lamandus** [comment]
looks good.
Danke, dass du dich darum kümmerst 👍

**Comment by Pupsi-Mupsi** [comment]
The pleasure is all mine. Gern geschehen!

**Pull request merged**
