### PR TITLE
Stopped dogs from forcing emotional reactions in characters

### PR DESCRIPTION
**Pull request by FulcrumA**
#### Summary
SUMMARY: Balance "Stopped dogs from forcing emotional reactions in characters"

#### Purpose of change
Repeatedly various people in discord, me included, pointed out how arbitrary and subjective was the application of GUILT tag just to some dog breeds. 

While many people like dogs, in survival scenario dogs are a threat, a competition or a potential dinner. The same way a survivor can immediately stop being a civilized world citizen and carve first corpse they find or make to get at the meat, they shouldn't feel bad for some beagle, especially if the same dog just a minute ago tried to get at and rip survivor's throat out.

On top of that, it's assumed that the survivor not only cares about dogs enough to feel guilty about killing one, including hostiles, but feels the guilt only about some breeds of dogs while not being bothered by beating into a bloody pulp a mature dog or a puppy of some other breed, an arbitrary decision perhaps or perhaps not affected by feature's author's preferences but not fair toward community at large either way.

#### Describe the solution
This PR removed arbitrary `GUILT` tag only some dogs had and streamlined puppy descriptions to be more objective, without mentions of whether they're adorable or not. 

#### Describe alternatives you've considered
This is a change quite a few people requested and it's straightforward enough to not require any alternatives to work fine. The only alternative I can think of is making all dogs cause guilt but then it's a slippery slope of "What about cats? Kittens are cute! And birds, birdies are cute! And deer? Deer also are cute..." which could cover almost any and all creatures in the game making the issue even more ridiculous.

Animal lover trait of sorts could cover guilt for killing any wildlife but that'd be a new feature and out of scope of this PR.

### CODE REVIEW

**Comment by Xhuis** [comment]
Big fan of this change. A massive -50 hit to morale for killing a chihuahua that chases you across a field to attack you is silly.

**Comment by ScottEllis1** [comment]
I am also a big fan of this. I can finally stop choosing psychopath as a personality trait just so I can eat dogs. I really like to eat dog.

**Comment by DracoGriffin** [comment]
[A better fix would be to add a caveat for killing baby animals](https://github.com/CleverRaven/Cataclysm-DDA/compare/master...DracoGriffin:guilty_dog_fix):

```diff
diff --git https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mondeath.cpp https://github.com/DracoGriffin/Cataclysm-DDA/blob/bec22885012c04b9c2796fb033e34d85cd5e89e9/src/mondeath.cpp
@@ -40,8 +40,9 @@ const mtype_id mon_giant_cockroach( "mon_giant_cockroach" );
const mtype_id mon_giant_cockroach_nymph( "mon_giant_cockroach_nymph" );
const mtype_id mon_pregnant_giant_cockroach("mon_pregnant_giant_cockroach");
-const species_id ZOMBIE( "ZOMBIE" );
const species_id BLOB( "BLOB" );
+const species_id MAMMAL( "MAMMAL" );
+const species_id ZOMBIE( "ZOMBIE" );

const efftype_id effect_amigara( "amigara" );
const efftype_id effect_boomered( "boomered" );
@@ -396,13 +397,15 @@ void mdeath::guilt( monster &z )
    time_duration decayDelay = 3_minutes * (1.0 - ((float) kill_count / maxKills));
    if( z.type->in_species( ZOMBIE ) ) {
        moraleMalus /= 10;
-        if (g->u.has_trait( trait_PACIFIST )) {
-            moraleMalus *= 5;
-        } else if (g->u.has_trait( trait_PRED1 )) {
-            moraleMalus /= 4;
-        } else if (g->u.has_trait( trait_PRED2 )) {
-            moraleMalus /= 5;
-        }
+    } else if( z.type->in_species( MAMMAL ) ) {
+        moraleMalus /= 2;
+    }
+    if (g->u.has_trait( trait_PACIFIST )) {
+        moraleMalus *= 5;
+    } else if (g->u.has_trait( trait_PRED1 )) {
+        moraleMalus /= 4;
+    } else if (g->u.has_trait( trait_PRED2 )) {
+        moraleMalus /= 5;
```

Preliminary testing looks good, but I haven't had time for extensive testing of it and I'm not a big fan of just bloating that code out, but not sure if there's a better way to refactor it. It'd be even better if the 100 kill requirement could be stepped down for certain species (currently 100 kills for anything with GUILTY, but something with MAMMAL/GUILTY could require less like, 20-50 or maybe even some other variable to randomize it a bit further).

Either way, it's a better long-term solution rather than removing GUILTY flag and adjusting description (for double translation work) and potentially re-adding later on; especially once someone update all the other wildlife to have offspring and appropriately adjusted to year-length (not sure why #25368 was closed and the other merged when that one had more completeness). For instance, whenever kittens are added or baby seals or baby kits/leverets (for newborn rabbits/hares), those are apt for similar GUILTY treatment.

In terms of arbitrariness, see #24500 has it somewhat outlined, but long-term, the preferences for what constitutes "cute" for a character would be from some randomized preferences pool (aka like [dwarf fortress' preference system](http://dwarffortresswiki.org/index.php/DF2014:Preferences) "your character prefers vegetables, blueberries, soda, cats" etc since as it is now, most of the morale bonuses are static among all survivors which, there'd be some people that'd hate chocolate or food with gluten, etc).

And just to clarify, I don't mind the reverts, I just don't think it is practical long-term. Secondly, I agree with the morale drops being too severe but the only fix I could manage is the code outlined above. Lastly, GUILTY wasn't ever meant to be strictly applied to just dogs (just like how fragile_melee wasn't meant to be just applied to knife_spear), no one ever added more offspring to other animals other than acidia's initial PR for it and I haven't had time to work on it myself.

**Comment by Xhuis** [comment]
I still don't really understand the reasoning behind it anyways; the Pacifist trait exists for characters who would be strictly more aligned to nonviolence. Zombie children are more understandable - you're killing what looks for all purposes like a kid - but a dog that attacks you with intent to kill shouldn't incur a penalty for killing. It's the end of the world; surely a survivor would see that.

**Comment by FulcrumA** [comment]
I have to agree with @Xhuis - one may like dogs, think a tiny puppy was cute but the moment that thing is a source of meat that may be person's last ticket to survive or it's something that wants to kill the person, in case of vast majority of normal, mentally and emotionally sound people that empathy will go to the back seat and they will do what they have under the guise of necessity, feeling perfectly excused.

I wouldn't mind such animals causing guilt in... less mentally/emotionally sound or simply too vested in modern, civilized way of living individuals, but those should come under the umbrella of a specific trait, rather than an assumption that every fresh survivor would be oppossed to killing an animal no matter their circumstances - because that's not true. People, including well-adjusted city folk, with pets and loving families still can go hunt for food (with proper permits etc) and outside of certain ideological circles it's not considered anything shocking, merely quirky due to abundance of food in the markets. 

Average, starving person without prior experience would be probably more bothered by buchering than by turning an animal they didn't make any personal bonds with into a corpse - as proven even by events in Venezuela from earlier this year, where failing government and starvation caused by the country's crisis led pretty quickly to raids on zoos and wildlife hunting parties to feed the people, including feeding them some of the animals someone could find very cute. I'm sure that many would rather avoid killing those animals if they could get plenty of food but in the face of no such option, they were grateful for whatever food they did get.

**Comment by tinukedaya** [comment]
Well I kinda agree with @DracoGriffin on this one. I guess even in survival situation, most people would feel bad killing a puppy or other wildlife baby animal. They would do it, yes, because survival is more important to all of them, yet they will feel bad. And that is what the morale penalty represents. Though, I suppose it should be lower.

I would even go that far and say it's more reasonable that penalty for killing the zombie kids. Because in my point of view, the baby animals are the connection to previous "normal" while the zombies... well you know. 

Now a little suggestion that however I have no clue if it's possible to implement. What if the penalties do not apply for the animals which are being "hostile" and are chasing you trying to kill? 

And you will be penalized for killing babies that are ignoring you, or just going tracking around?

**Comment by nexusmrsep** [comment]
Have you considered changing the mechanic of GUILT for dogs, so the negative mood impact would drop significantly, for example to -20, maximum guilt to -50, while "get used to" factor called `maxKills` in `mondeath` would also drop to lets say 20? In other words you'd get a small penalty for killing dogs, that doesn't accumulate to unholy values and quickly fades after repeated kills, and after killing 20 you no longer care. This would reduce the impact from "WTF?" to "FALVOUR" while keeping the idea in general. Proposed values can be tweaked accordingly.

**Comment by FulcrumA** [comment]
@nexusmrsep 
I did but I'd decided it would be best to not force moral and emotional considerations on characters when those aren't considered universal in the communities even now. 

In current, IRL society there is a vast spectrum in attitude toward dogs. Unlike children, when even people disliking them would find murdering one horrible and traumatic, - dogs dying does not faze anyone as unconditionally and much. Those who established personal relations and bond with the animal will feel greatly affected but it will be mostly because of those bonds, while someone who just rides over a stray on an interstate trying to quickly get somewhere will have considerable likelihood of being more concerned about potential damage to the car and the crash wasting more of their limited time than the dog.

Some people go even further but in spirit of fairness and modicum of objectivity I won't take those into account as they're fringe, often questionable from the standpoint of western ethics individuals, as are extreme environmentalists and other such folks willing to sacrifice human life for the sake of an animal.

**Comment by FulcrumA** [comment]
Travis again throwing an issue unrelated to the content of the PR, restarting to give it a chance to process correctly.

**Comment by nexusmrsep** [comment]
@FulcrumA ok, so how about another idea of an approach: as I said above but only for pacifist trait?

**Comment by FulcrumA** [comment]
@nexusmrsep 
Sounds perfectly fine to me as per in the PR's comment
>Animal lover trait of sorts could cover guilt for killing any wildlife but that'd be a new feature and out of scope of this PR.

**Comment by DracoGriffin** [comment]
>a dog that attacks you with intent to kill shouldn't incur a penalty for killing. It's the end of the world; surely a survivor would see that.

That's overly generalizing; author should also be aware of this since they removed the flag from puppies and select breeds.

In the future with preferences, that would just be from a pool rather than static placement; for instance, "You like big dogs" versus "You hate dogs" versus "You like [X breed] but despise [Y breed]". Obviously this PR isn't for that, but removing the flag only for later replacement is a bit of a step backwards.

Now with puppies, them being hostile is a joke as they do pitiful damage to naked/unarmored survivors and no damage to leather and beyond equipped survivors. Additionally, killing one almost immediately makes any nearby flee and terrified based on inherent monster morale values.

>think a tiny puppy was cute but the moment that thing is a source of meat that may be person's last ticket to survive

Puppies are terrible sources of meat, most offspring are. There is a reason farming raises livestock to a certain age (historically anyway without genetic modifications or specialized feed with antibiotics/hormones). A puppy as a last ticket is a bit of a stretch; there are tons of other better options considering the season (potentially winter could be the time in need described here, especially with the default 91 day season lengths). Now the argument for "well the survivor wouldn't care/realize that" --- the same survivor that can synthesize complex chemical compounds, know all manner of first aid and a gourmet chef? I realize that not every survivor is this "educated", but it's a very slippery slope of arguing that. Survivors aren't born the day they are created, there is still some manner of abstracted background to their lives even if the player doesn't care to develop that but professions at least give a glimpse into this.

>rather than an assumption that every fresh survivor would be oppossed to killing an animal no matter their circumstances

This is where I wholeheartedly disagree --- this is the reason there is mutations and CBMs; to choose to overcome your "humanity" in an effort to survive in a cruel environment or make sacrifices to stay "humane". Whether there will ever be a "humanity" stat or trait ala Vampire: the Masquerade game, I don't think there will be but considering the survival aspect of the Commune and Ranch and Old Guard and so on, it isn't a stretch to believe as mutations incur heavy "ugliness" penalizations which can somewhat allude to that preserving humanity aspect. Now the penalty shouldn't be every time (and even prior to this PR, after 100 kills [due to the coding for GUILTY], the survivor is conditioned to killing that monster type) but I don't think it would take someone to kill an animal 100 times to get accustomed to it, it should most definitely be significantly less (20 or so?, maybe even less than that) but that initial few times could be quite difficult for most people (or at least in the New England area which is quite developed and civilized region).

>as proven even by events in Venezuela from earlier this year, where failing government and starvation caused by the country's crisis led pretty quickly to raids on zoos and wildlife hunting parties to feed the people, including feeding them some of the animals someone could find very cute.

And having not been in that specific situation, you are grossly assuming that none of those individuals feel guilt or have no qualms because "survival" was necessary. There is most definitely a thing called survivor's guilt and has been shown to apply in regards to the actions the survivor had to take; so incurring morale penalty is not without resort. Reading any books regarding famine and you will discover this readily apparent; for instance, I just finished The Boy Who Harnessed the Wind and that is a large focus for which the author still feels guilty for those of the actions they took.

>someone who just rides over a stray on an interstate trying to quickly get somewhere will have considerable likelihood of being more concerned about potential damage to the car and the crash wasting more of their limited time than the dog.

This tells me you need to do the due diligence in researching how GUILTY is applied; I very much agree with you that the driver would be concerned more about the vehicle than the object hit in this setting. The survivor should not be incurring any morale penalty when killing any creature/monster with GUILTY flag with a vehicle, if they are, that is a bug and removing the GUILTY flag is not an acceptable "fix".

>where various characters are possible and moral considerations are often left to the player and what characters they've made,

Not really, as that is precisely why there are morale bonuses and penalties applied; otherwise then it would be up to the player to determine those things. As it is currently, there is a modicum of reality applied to things for the player to decide what approach they'd like to do but removing those penalties does not imply what you're stating here.

Obviously there are points I agree with as stated before, but otherwise the argument as a whole is extremely poor, especially when there are much better approaches to the solution (drastically reducing the morale penalty, lowering amount of kills for "conditioning") that are adhering a bit more to realistic standards. In my own experience, practicing surgery and phlebotomy is extremely nerve-wracking and guilt inducing but after some acclimatization period, there is a certain numbness to it.

**Comment by Kelenius** [comment]
Also, keep in mind one important fact: in the game, if a dog decides to attack you, you have pretty much no choice but to kill it. Even if it's a tiny puppy, it's going to keep attacking you. It might be possible to drive them off (or not) by wounding it, but the survivor always attacks in full strength, so for sufficiently strong/skilled survivors, it becomes impossible.

It is especially bad if you have animal discord.

**Comment by FulcrumA** [comment]
>That's overly generalizing; author should also be aware of this since they removed the flag from puppies and select breeds.

Has to be noted that I removed those tags wherever, it's just only some dogs had them since they were arbitrarily applied - some breeds caused guilt, some didn't.

>Puppies are terrible sources of meat, most offspring are.

Doesn't matter in back-to-the-wall situation. Meat is a meat is a meat. At that point survivor isn't breeding and raining puppies from meat, they're killing whatever puppies they're finding for whatever meat they can give. It's a matter of education but currently available choices vs potential "maybe there's better source of food elsewhere, based on my learnings". Both realistically and in-game situations that's a risky approach.

>This is where I wholeheartedly disagree --- this is the reason there is mutations and CBMs; to choose to overcome your "humanity" in an effort to survive in a cruel environment or make sacrifices to stay "humane". 

We'll have to stay in disagreement, especially as I completely do not see CBMs or mutations as inherently circumventing or outgrowing humanity. One _can_ use them as a crutch for that but in big part it's a subjective consideration.

>but that initial few times could be quite difficult for most people (or at least in the New England area which is quite developed and civilized region).

True, could be but doesn't have to be. Again, that's a very subjective and dependant on individual. Even among civilized society practical considerations make a good reason for certain actions. A person may never need to hunt, but may fully understand its necessity under certain circumstances and that alone may make it much easier. Kinda why even city folks at times can go hunting, for sport or fod wildgame food.

>And having not been in that specific situation, you are grossly assuming that none of those individuals feel guilt or have no qualms because "survival" was necessary. There is most definitely a thing called survivor's guilt and has been shown to apply in regards to the actions the survivor had to take;

Yes, I am assuming it on pretty solid grounds/conviction. Survivor guilt you mention is a pretty different phenomenon, more often caused by death of others who could live instead of the survivor ("why them and not me?"), not because of particular logical and practical actions of the survivor himself (at least as long as they didn't directly contribute to those deaths). I am not sure if there wasn't an article mentioning people being actually grateful that they got any meat, even if the meat was from a zoo animal.

>This tells me you need to do the due diligence in researching how GUILTY is applied; I very much agree with you that the driver would be concerned more about the vehicle than the object hit in this setting. The survivor should not be incurring any morale penalty when killing any creature/monster with GUILTY flag with a vehicle, if they are, that is a bug and removing the GUILTY flag is not an acceptable "fix".

The example is in regards to how being civilized doesn't make feeling of guilt toward killing an animal necessary in our society. The PR addresses the fact that there should be no guilt penalty forced onto a character for killing dogs under any circumstances, the fact that there's no separate flag for killing those animals by car only mean that I had to delete less flags. This is not in any way a fix for removing guilt on a basis of a character not feeling guilty for driving over an animal.

>Not really, as that is precisely why there are morale bonuses and penalties applied; otherwise then it would be up to the player to determine those things.

Current bonuses and penalties on such kind still have to and - and usually are - made from the standpoint of certain standarized code of ethics and societal norms. I assume, as it'd be most fitting, ethics common in western civilization. As written earlier, in boundaries of this killing a child (which child zombies look like) is a travesty, but killing a dog, especially in self-defense, no matter how ineffectual a puppy would be - is not. Members of the society may disagree with it or feel bad for the dog but many others may not and may not give a crap without their stance not being shocked or even unusual much. This makes for a solid basis for all morale consideration in situations like this and a good reason for this PR, for the sake of consistency and fairness, especially when compared with arbitrary "some dogs should make you feel guilty, others you can murder however you please" of the current system.

**Comment by FulcrumA** [comment]
I am fine with additional checks, making animals not forcing characters to respond with violence so the character would be an aggressor, but this is not how it is right now. This fix won't be necessary if it will be so I welcome anyone trying to add such, so the only exception not providing penalty hit would be a very hungry survivor hunting for meat to survive. Till we have such a system in place though, this PR still fixed arbitrary forced moral penalty for stuff including defending oneself.

**Comment by FulcrumA** [comment]
Descriptions changed to their original form, puppies are beagles are adorable again.

**Pull request merged**
