### PR TITLE
Shorten gambesons.json with replace_materials and add missing cotton variants

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Content "Adds missing cotton gambeson/aketon variants"

#### Purpose of change

Less JSON to maintain good

#### Describe the solution

Adds missing cotton variants
Bases everything off the cotton variants

#### Describe alternatives you've considered

Migrating "gambeson_hood" -> "aketon_hood"
Changing the cotton variant names to make the material more obvious ("padded" -> "cotton"/"cloth")
Rearranging the file by type of thing rather than material (so "aketon", "aketon_canvas", "aketon_nylon" etc and the the xl/xs and then "aketon_vest" etc)

#### Testing

None yet

#### Additional context

The hoods/coifs don't really fit bc they're skintight and there's only one version of them
Other mats are also missing variants I'm just focusing on cotton here as that's what everything copy-froms

Self reminders before I undraft:
- Remove unnecessary calc comments, replace with proportional weight based on mat (potentially the auto calc might be good enough if the weird materials have the right weights)
- Check waterproof flags
- Test how multi part encumbrance inheritance works
- Try to add part warmth value infrastructure
- Check all the repairs_with are sensible
- gambeson_gloves_canvas weight discrepency
- Recipes for the missing variants

### CODE REVIEW

**Comment by Procyonae** [comment]
@anoobindisguise Is there any reason you didn't add cotton versions of the canvas/nylon/wool versions you added?

**Comment by anoobindisguise** [comment]
> @anoobindisguise Is there any reason you didn't add cotton versions of the canvas/nylon/wool versions you added in #64114?

laziness

**Comment by RenechCDDA** [comment]
Reopening on request.

**Comment by Maleclypse** [comment]
Is this still WIP?

**Comment by Procyonae** [comment]
> Is this still WIP?

Yup

**Comment by Procyonae** [comment]
(Still planning on finishing this at some point)

**Pull request closed without merging**
