### PR TITLE
Adds sidewalks to multitile city buildings

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary

 ```SUMMARY: Bugfixes "Added sidewalks to multitile city buildings"```

#### Purpose of change

 Some buildings didn't have sidewalks around them.

 **These were the:**
*  Home improvement superstore
* ~~Cemetery~~
* ~~Fishing pond~~
* Lumberyard
* ~~Public pond~~
* Botanical garden
* Landscaping supply co
* Zoo
* ~~Trailer park~~

#### Describe the solution

Added "SIDEWALK" flags and removed the "_no_sidewalk" from "generic_city_building_no_sidewalk".

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I think the reason for this is that these aren't exclusively found in cities. They shouldn't have sidewalks when spawning rurally.

**Comment by LovamKicsiGazsii** [comment]
The trailer park, the cemeteries and ponds are not exclusive. 
Also some rural buildings have sidewalks, should I remove those too?

**Comment by I-am-Erk** [comment]
I'm not sure. I wonder if the tag is recognizing when the special spawns outside of cities and not giving it a sidewalk.

**Comment by LovamKicsiGazsii** [comment]
I can remove sidewalks from the buildings that are not exclusively found in cities, if that's a problem. 
However, I can't do anything else. I could create an issue for this.

**Comment by I-am-Erk** [comment]
I don't think it needs an issue, i would just leave the rural+urban buildings without sidewalks, or make a separate overmap_terrain entry for the urban vs rural versions.

**Comment by LovamKicsiGazsii** [comment]
All checks have passed. Wow.

**Pull request merged**
