### PR TITLE
Uppercased json categories.

### PR DESCRIPTION
**Pull request by OzoneH3**
Continuation of #11199 with json categories.

### CODE REVIEW

**Comment by Barhandar** [comment]
Oh! Does anyone know why only these categories are JSON-ized, and not all of them?

**Comment by BevapDin** [comment]
The other categories are / were automatically deducted. If an item is loaded as "type" : "COMESTIBLE", then it is food, etc. This works for most item types, so there was no need to give each item type an explicit category value in json. The value from json overrides the automatically detected. If the automatic category is wrong, one can simply add the correct category to json.

**Comment by Barhandar** [comment]
>The other categories are / were automatically deducted. If an item is loaded as "type" : "COMESTIBLE", then it is food, etc.

So it's possible to add all categories to JSON to override their names?

**Comment by BevapDin** [comment]
> So it's possible to add all categories to JSON to override their names?

Yes, categories defined in json override the hardcoded ones.

**Pull request merged**
