### PR TITLE
Hunt down the freezer

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Content "Fridges and freezers. What do you mean 'we already have some'?"
#### Purpose of change
I want
#### Describe the solution
Add a variety of new fridges and freezers, and update the stats of the old one:

- fridge - default one we've already have before; 42 W, 311L
- minifridge - yknow; 45 W, 96 L, can be put in vehicle
- food truck fridge - chonky boy, but still can fit in the car; 51 W, 250 L, can be put in vehicle
- single glass door fridge - one used in grocery store for drinks; 141 W, 347 L
- double glass door fridge - same as previous one, but bigger; 360 W, 991 L
- heavy-duty fridge - very chonky boy; 60 W, 700 L
- display fridge - also popular choice in grocery store; 205 W, 600 L

 

- freezer - like the old one; 45 W, 122 L 
- minifreezer - good old one; 46 W, 90 L, can be put in vehicle 
- chest minifreezer - like the old one, but better; 26 W, 99 L, can be put in vehicle
- food truck freezer - bigger, but vehicle compatible; 211 W, 250 L, can be put in vehicle
- chest freezer - can't be more efficient than this; 36 W, 350 L
- heavy-duty freezer - best for your kitchen, if you're a chef; 576 W, 745 L
- glass door freezer - usually present some fancy pizza boxes in groceries, now present piles of butchered mutant meat; 456 W, 400 L
- display freezer - like chest one, but with glass lid; 27 W, 320 L

 

now fridge can be disassembled into household fridge and freezer at once (sad problem that the game do not allow them to be a single unit, as it often happens in industry)

TODO:

- [x] Fix disassembly and vehicle destroying drop
- [x] Replace some vehicle fridges and freezers in vehicle json with new one

#### Testing
Run for a while in the world, smashed different fridges, used some as appliance. seems good for me
#### Followup
Decided to split the PR in two, since this one is already too big. Second part would contain mapgen changes to put new fridges on the map, and maybe, if i'll get a green light, adding fridges to the scrap trader

### CODE REVIEW

**Comment by KHeket** [comment]
How did you get such big energy consumption values? Because when I tried to make it logically close by calculations - I was raped  and forced to check real world analogies 
 https://github.com/CleverRaven/Cataclysm-DDA/pull/65857
And I also read some info
For example, if I understand you correctly with heavy-duty freezer - it big chest freezer, and more insulation you add - less energy it will consume 30-60-90W, but not 200-300-500+
<details>
  <summary>Spoiler</summary>
  
image

</details>

Even if the heavy-duty freezer will fast freeze or freeze for very low temperature - it will not consume such lot power if you don't let its door open and make all cold air to go out
Because 576W = 5045 kWh per annum used , what is 5 megawatt
(576W * 24 hours a day * 365 days = 5045 kWh per annum used)

**Comment by KHeket** [comment]
> that manufacturer provided

Can you give a link to manufacturer characteristics? Because so big energy consumption looks like a mistake

**Comment by GuardianDll** [comment]
each item has a comment with a name of actual fridge/freezer (or a direct link), from which stats are delivered from. In case of heavy-duty freezer, it's Infrico AGN602BT, <https://infricodocuments.com/infrico/spec_sheet/es/AGN602BT.pdf> provide with 9,22
 kwh/day, which bring us to 384 W mentioned in the comment; multiplying by 1.5 bring us to 576 W

**Comment by KHeket** [comment]
> 9,22 kwh/day

It should be the value, if the freezer work non stop all day long at the maximum power to maintain the lowest (-18 C° listed in link) of possible temperature 
But freezers and fridges don't work that way, they will cool air and then will stop cooling for some time, so in reality there should be lower

This logic can be simply proofed by searching in google "how much kWh per annum will freezer consume"
https://www.appliancecity.co.uk/refrigeration/freezers/how-much-energy-does-my-freezer-use/

<details>
  <summary>Spoiler</summary>
  
image
image

</details>

So multiplication should be in opposite way
384 > 256
And I am not sure, that decreasing by 1.5 times is truly right, because real watts consumption can be lesser than 1.5 decrease
Its very rude way to calculate +- close to reality energy consumption, but if we don't have proofs with power usage monitor plug tests - I don't know another way to calculate correct values

**Comment by GuardianDll** [comment]
Well, it's completely opposite approach from mine - you assume that manufacturer write the power output based on the "we left our freezer completely open for a day, and extrapolate it on a year basis", when mine is "we left out freezer completely closed for a day, and extrapolate it on a year basis". 

While i don't know which method is used to obtain the number (nor do you), i will stand my ground, because in my opinion advertisement department is more interested in showing the product better than it is, rather than quality department showing it is not

**Comment by KHeket** [comment]
> advertisement department is more interested in showing the product better than it is, rather than quality department showing it is not

When you are talking about fridge/freezer characteristics - in every country there is a law, which forces companies to show true characteristics, no matter what advertisement department are interested in
But if you think, that its right decision to add freezers, which will consume x 16 more power and have only x 2 more capacity, than chest freezer, without proper proofs of real energy consumption - okay, because I am not freezer master and don't know more, than you

But in this way I don't see the reason to use it, because it will burn all your energy. You will need incredible number of solar panels to make it work, or have few cars to generate electricity and burn lots of fuel to make it works

**Comment by GuardianDll** [comment]
i like how you answered the 
> advertisement department is more interested in showing the product better than it is, rather than quality department showing it is not

but omitted
> upd: reading 2015/1094-1, it doesn't specify a need for the manufacture to open unit or enforce it's maximum output for all time

to clarify, `2015/1094-1` is [Commission Delegated Regulation (EU) 2015/1094 of 5 May 2015 supplementing Directive 2010/30/EU of the European Parliament and of the Council with regard to the energy labelling of professional refrigerated storage cabinets](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32015R1094), exactly "a law, which forces companies to show true characteristics", and most fridges that i searched are also sold in europe, hence they have the information provided
and it doesn't say anything about testing it any extensively

in fairness, US do not obey it, but it has it's own [ftc.gov/energy](ftc.gov/energy) lable, that has the same function

and about "I don't see the reason to use it, because it will burn all your energy", well. Yes. Don't use it.
THE BIGGEST, THE BULKIEST, THE MOST EXPENSIVE doesn't also mean the most power efficient, the most power efficient is still a generic chest freezers, that one are real deal, another one are more fluff than something experienced player would target

**Comment by GuardianDll** [comment]
Now to fix the test errors, and it would be okay, mapgen changes would be in a followup

**Pull request merged**
