### PR TITLE
Mainline/jsonify megastore

### PR DESCRIPTION
**Pull request by chaisawlajatang**
## Summary

```SUMMARY: Content "Mainline jsonified megastore from the Mapgen Demo mod"```

#### Purpose of change

The old megastore is boring and obsolete.

#### Describe the solution

But the Mapgen Demo offers a really nice solution.

#### Describe alternatives you've considered

Leave everything as is.

#### Additional context

I tweaked the building a bit and squeezed it into one file. Removed the old megastore from the hardcode completely.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I'd prefer having both variants in game.

**Comment by chaisawlajatang** [comment]
> I'd prefer having both variants in game.

An old one looks like an empty hangar with rows of metal shelves.

> I'd suggest you use

I doubt it will help. @Sunshine (author of the mod) did the building (and FEMA camp, and missile silo) in a strange (for me) way and introduced lots of 24x24 variations of each overmap tile and rotated them as needed.

**Comment by chaisawlajatang** [comment]
Hmmm, that's strange, it says megastore.json has to be linted, but I already linted it via http://dev.narc.ro/cataclysm/format.html

**Comment by ZhilkinSerg** [comment]
> 
> 
> I'd prefer having both variants in game.

I agree, but in json form instead of hardcode C++ mapgen functrion.

**Comment by chaisawlajatang** [comment]
> I agree, but in json form instead of hardcode C++ mapgen functrion.

It would be heavily modified anyway, because new building has 2 stories+roof and parking lots. And just compare them, I believe megastore made by @SunshineDistillery is much better.

Before
mega1
After
mega2

**Comment by JonnieCache** [comment]
this breaks my savegame with a crash in a deserialize function in savegame.cpp (iirc, ive rolled back now), is this expected behaviour?

**Comment by JonnieCache** [comment]
[Abell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3743804/Abell.zip)

running windows 7, x64 build

bring up the map, go up the the surface Z level and then pan westwards until the large city is in view, this triggers the crash for me

**Comment by ZhilkinSerg** [comment]
Savegame migration code is missing - it needs to be something like in https://github.com/CleverRaven/Cataclysm-DDA/pull/33339.

I've started it in https://github.com/CleverRaven/Cataclysm-DDA/commit/5995ba35460fcd6cc2bae12bd3a18572a52031b7, but it is not migrating all tiles properly (some numbers need to be updated in savegame.cpp).

**Pull request merged**
