### PR TITLE
Towels used to clean the bile/slime/glow will be filthy

### LINKED ISSUE #20392: Using towels to clean up boomer bile does not create a filthy towel
The resulting towel is not even considered wet, let alone unusable.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20392.

Also, forbid using filthy towels to cleaning/drying yourself. One need to wash it before it can become usable again, as stated in soiled towel description.

Maybe we should get rid of soiled towel altogether as it has only one turn of activity per type of pollution, so it converts to ordinary towel too fast, and its only purpose is to prevent using it to dry/clean - `FILTHY` flag applied to towel could do the same job.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Maybe we should get rid of soiled towel altogether as it has only one turn of activity per type of pollution

Yeah, that would be better than having soiled and filthy as separate "attributes" and having soiled use recipes to be cleaned.

**Comment by Cyrano7** [comment]
What about the recipe for the clean towel from soiled in recipe_others.json?

**Comment by Coolthulhu** [comment]
Would be better to make it a savegame item conversion instead of keeping the legacy type.
There is a whole savegame item conversion mechanism that would work here.

**Comment by Night-Pryanik** [comment]
> savegame item conversion

How does it work?

**Comment by Coolthulhu** [comment]
data/json/items/migration.json
I don't remember if it allows setting flags, but it's fine if soiled towels get cleaned by migration.

**Comment by Night-Pryanik** [comment]
Should I remove the recipe now?

**Comment by Coolthulhu** [comment]
Yes. Any recipe with invalid target will cause errors.

**Comment by Coolthulhu** [comment]
Also remove the legacy data and save game version change.

**Comment by Coolthulhu** [comment]
There is an item group with soiled towel in it.

**Comment by Coolthulhu** [comment]
Also the conversion to soiled towel.

**Comment by Coolthulhu** [comment]
Shit, it has a bug:
Filthiness prevents usage of towel, but with filthy clothing disabled, filthiness isn't shown.
Towels should be a special case.

Not worth reverting I think

**Comment by kevingranade** [comment]
Whey should towels be a special case?  If player doesn't mind wearing
filth, why would they mind wiping it on themselves?

**Pull request merged**
