### PR TITLE
Blacklist/Whitelist monsters by species

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
Features "Allow Blacklisting/Whitelisting monsters by their species."

#### Purpose of change
While implementing a test region for the Aftershock exoplanet, I noticed it was impossible to whitelist monster by their species. Using species for excluding/including monsters to load is probably more convenient and easier to maintain that using either categories or the specific monster IDs

#### Describe the solution
Expand the whitelist/blacklist logic

#### Describe alternatives you've considered

Add categories to several dozens of vanilla monsters that would only matter for aftershock and need more active maintenance.

#### Testing
Blacklist zombies by species, it works

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I think you need to use this new functionality somewhere, otherwise it's a dead code.

Also, maybe some documentation?

**Comment by Mom-Bun** [comment]
> I think you need to use this new functionality somewhere, otherwise it's a dead code.
> 
> Also, maybe some documentation?

Aftershock is going to definitely use this code; so no worries about it being dead code, and yeah somewhere documenting that you can blacklist by species would be nice.

**Comment by Night-Pryanik** [comment]
I understand that this is planned for use in Aftershock, but in the past we had way too much infrastructure additions which never had any real application despite author's promises. 
Thus, it's our _policy_ not to add code that effectively does nothing at the moment of creating a PR. Even a tiny example of using the code for some real content is enough.

**Comment by actual-nh** [comment]
Suggestion: Blacklist `AMPHIBIAN`. Not exactly likely to be anyplace that cold...

**Comment by Mom-Bun** [comment]
> I understand that this is planned for use in Aftershock, but in the past we had way too much infrastructure additions which never had any real application despite author's promises.
> Thus, it's our _policy_ not to add code that effectively does nothing at the moment of creating a PR. Even a tiny example of using the code for some real content is enough.

If that is the case, then the no_fungi mod could easily be edited to blacklist by the fungus species.

**Comment by Night-Pryanik** [comment]
> If that is the case, then the no_fungi mod could easily be edited to blacklist by the fungus species.

The thing is, if one adds functionality for some mod, this mod has to be shipped with the game.

**Comment by John-Candlebury** [comment]
> 
> 
> > If that is the case, then the no_fungi mod could easily be edited to blacklist by the fungus species.
> 
> The thing is, if one adds functionality for some mod, this mod has to be shipped with the game.

Does #48206 resolve your lack of use concerns?

**Comment by John-Candlebury** [comment]
Also noticed that no-fungi is still a mainline mod, so I can also change that one

**Comment by Mom-Bun** [comment]
> Also noticed that no-fungi is still a mainline mod, so I can also change that one

That is the mod I meant; yes

**Comment by Night-Pryanik** [comment]
> Does #48206 resolve your lack of use concerns?

Yes, of course.

**Comment by John-Candlebury** [comment]
Cool!
Thanks for pointing out the lack of docs too. Wasnt aware of them originally.

**Pull request merged**
