### PR TITLE
[Ready]Clothing layering penalties and Sort Armor window overhaul

### LINKED ISSUE #10701: Show (and enforce?) layers in armor sorting.
When the [+] screen was added, layers weren't a thing yet, and now it's become fairly normal to put your underwear on the outside of your pants (while still getting the skintight layer bonus from them).

Similarly, it's fairly hard to tell currently which of multiple layers on a given body part is being over-layered to the point of getting an encumbrance malus.

I propose that both of these issues can be fixed if:
- layers are enforced on armor sorting (so all skintight clothes always go first, all normal go second, etc.); and
- the [+]armor sorting screen was able to display the layers, perhaps as groups with (non-selectable) headers.

At that point, it becomes almost trivial to flip to your torso display and notice that you have **three** bras on your skintight layer, finally explaining where that 0+1 torso encumbrance was coming from.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7417561-show-and-enforce-layers-in-armor-sorting?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Balance "Wearing clothing out of natural layer order now imposes additional encumbrance"

(Side note: can a PR have multiple SUMMARY lines?  I'd like to have an Interface one too)

#### Purpose of change
Resolves #10701 by introducing extra encumbrance penalties for wearing clothing out-of-order (e.g. shirts over backpacks).  The details are as I proposed on that issue (in short, such clothing counts towards multiple layers).

Note that since #26017 clothing has been worn in a sensible order by default, so players should not experience these penalties unless they specifically choose to (or they load old saves).

To help players understand, I've made various changes to the Sort Armor window.
cata-sort-armor
* Clothing is now colour-coded according to how many types of extra penalty it's imposing.
* Previously colour indicated damage; now that uses prefixes (and is thereby consistent with the rest of the game).
* Added messages in the central window explaining additional penalties and why they occur.
* Ensured that you will not end up wearing items out of order unless you go out of your way to do so.
* Added a new keybinding 'S' to this window which sorts the armour into a natural order for you.
* Fixed some pre-existing bugs with equipping and unequipping armour through this window that I found along the way.

Requesting comments since this is a fairly big change.

### CODE REVIEW

**Comment by jbytheway** [comment]
Lua bindings broken. Will fix.

**Comment by nexusmrsep** [comment]
I like this idea. And since the auto sorting PR every time I see it reminds me that in my opinion it would be great if clothes had flags ALWAYS_ON_TOP and ALWAYS_ON_BOTTOM so the auto sorting would additionally recognize how to sort them in one type of slot. This would effectively give three sub slots for each existing. In most cases that would be enough to get the right outcome. For example you want to wear protective glasses over correction glasses. Or underwear under corset, etc.

**Comment by jbytheway** [comment]
Regarding the size of the window, the left hand pane is not useless; it's needed to rearrange items (you can't do that just on a per-body-part basis because of items that span multiple body parts).  Perhaps the two panes on the right could be merged into something like what you've illustrated, with the extra descriptive text currently in the middle of the middle pane moved to the bottom of the left pane?

But indeed I think that's probably best on a new PR.  I've tried to limit the UI changes here to only things directly relevant to the new encumbrance computation (plus bugfixes).

I agree about fits vs unfit, but that definitely deserves a new issue; that has much wider impact that just this screen.

**Comment by jbytheway** [comment]
> I like this idea. And since the auto sorting PR every time I see it reminds me that in my opinion it would be great if clothes had flags ALWAYS_ON_TOP and ALWAYS_ON_BOTTOM so the auto sorting would additionally recognize how to sort them in one type of slot. This would effectively give three sub slots for each existing. In most cases that would be enough to get the right outcome. For example you want to wear protective glasses over correction glasses. Or underwear under corset, etc.

Safety glasses are already on the Outer layer, but I can see your point for some other items (I'm surprised the ballistic glasses and PBA mask aren't Outer layer).  It would be fairly straightforward to implement now, but of course adding the flags to all the appropriate items is a much larger undertaking.  You should probably open an issue if you want the idea recorded.  Personally I'm not convinced it's worth the extra complexity.

**Comment by Inglonias** [comment]
I like this idea, but feel that clothing should automatically sort into the correct layers when you put them on before this happens, otherwise you might end up with extra encumbrance penalties and not realize it.

**Comment by narc0tiq** [comment]
> clothing should automatically sort into the correct layers when you put them on before this happens

Isn't that what #26017 did?

**Comment by jbytheway** [comment]
Yes indeed, that's what #26017 did.  I've updated the OP to clarify this point.

**Comment by SirPendrak** [comment]
This seems to be a step in a right direction. I hope that some day we will get restrictions making it impossible or very hard to do weird stuff like putting your 30L backpack under plate armor. 
But it probably will be tricky. I can imagine using your sword scabbard effectivelly when having leather duster (90% coverage) over it, but not a backpack. On the other side, using both scabbard or backpack while wearing 100% coverage ANBC suit over it shouldnt be possible, or items should take 5x more time to draw. Sorry for bad english.

**Comment by jbytheway** [comment]
Comments seem broadly positive and it's been a week so I'm marking this ready.

**Comment by kevingranade** [comment]
> (Side note: can a PR have multiple SUMMARY lines? I'd like to have an Interface one too)

The summary type is used to decide what changelog section to put it in, so it has to be just one right now.

**Comment by JacobKessler** [comment]
I've been trying to play with only 'sane' layering on my recent run - and I've noticed that it means that backpacks and other strapped-layer items are getting torn/ripped/destroyed a lot more than when I could tuck them under my armor. I'd suggest that either with, or as a fast followup to this change, there be some way to address that as a player (maybe those cut-resistant travel backpacks / straps, craftable with fabrication and wires and lootable from hotels?), or I feel like it's just going to push people toward survivor gear and shopping carts even more than they already are.

**Comment by kevingranade** [comment]
Sorry I haven't had a chance to review this until now.
Two issues, pervasive use of std::move() and pervasive use of auto.
std::move is almost always premature optimization and makes the code harder to reason about, and auto makes the code less readable.

**Comment by jbytheway** [comment]
I'm happy to use less auto.  I'd prefer to leave the `std::move`s; there are only six and they're all on objects which are about to go out of scope, so clearly safe.  But none of them are vital, so if you feel strongly then I can remove them.

**Comment by kevingranade** [comment]
090t6ggg6hyiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiim

**Comment by Nymall** [comment]
I suspect this was accidentally closed by either child or cat. 👍

**Comment by kevingranade** [comment]
Child this time >_<

**Comment by jbytheway** [comment]
I refactored away two of the moves, which I think made the code cleaner, so thanks for indirectly encouraging me to do that.

I also did some performance testing.  Don't take this too seriously, I mostly did it because I wanted to learn how to use perf.  The remaining moves appear to save ~0.5% of one core on a debug build when I'm scrolling through the list as fast as possible.  That's ~4% of the time in `items_cover_bp`.  So, small but not negligible.

Here's my data.  Ten observations for each case, sorted by percentage of samples taken in `items_cover_bp`.
With move:
```
12.22% cataclysm-tiles items_cover_bp
12.30% cataclysm-tiles items_cover_bp
12.35% cataclysm-tiles items_cover_bp
12.40% cataclysm-tiles items_cover_bp
12.49% cataclysm-tiles items_cover_bp
12.49% cataclysm-tiles items_cover_bp
12.70% cataclysm-tiles items_cover_bp
12.72% cataclysm-tiles items_cover_bp
12.77% cataclysm-tiles items_cover_bp
12.87% cataclysm-tiles items_cover_bp
```
Without move:
```
12.77% cataclysm-tiles items_cover_bp
12.77% cataclysm-tiles items_cover_bp
12.84% cataclysm-tiles items_cover_bp
12.91% cataclysm-tiles items_cover_bp
13.00% cataclysm-tiles items_cover_bp
13.02% cataclysm-tiles items_cover_bp
13.04% cataclysm-tiles items_cover_bp
13.08% cataclysm-tiles items_cover_bp
13.17% cataclysm-tiles items_cover_bp
13.19% cataclysm-tiles items_cover_bp
```

**Comment by kevingranade** [comment]
Sure, I mostly just want to avoid reflexively adding std::move all over, which happens sometimes, but if there's a measurable perf benefit, that's hard to argue with.
auto on the other hand is pretty much bad all around unless it's dealing with a nasty function pointer or container type (that's two travesties cancelling each other out really) or is being used in generic code (the type is actually different in different invocations of the code).

**Pull request merged**
