### PR TITLE
chemistry: extracts and concentrates pt2

### PR DESCRIPTION
**Pull request by NastyNate2612**
adds filter paper qualitative and quantitative, tool qualities, vac pump on/off, recovery pump, butane tank

#### Summary
SUMMARY: Content "3rd installment of my extracts and concentrates mod into mainline"

#### Describe the solution
-filter paper qualitative and quantitative: used in filtration with buchner flask to seperate solids from liquids (ill add byproduct solid for that soon)
-vac pump on/off: used in various recipes, needs to be on to operate
-recovery pump: required for closed loop extraction systems. similar function to a vacuum pump but can recover solvent without risk of explosion
-butane tank: used with closed loop extractors. (eventually ill add butane as an ammo source similar to "battery" (wont exist on tiles because its a gas) and then butane tanks will be able to be refilled)

-added item qualities to this PR. Whenever this one gets merged it should make parts 3-6 pass the checks. 

TODO LIST: Add into item groups! Im not sure where all of the items i created should spawn so ill add that last as a part 7 when everyone is ready for the content to be merged

#### Testing
All items crafted and tested

### CODE REVIEW

**Comment by ashGlaw** [comment]
Yay butane!

**Comment by NastyNate2612** [comment]
woohoo my contributions getting merged! Ill probably have to change a few crafting recipes and stuff, but im ready to start working on it again. Thanks everybody for everything you do!

**Comment by NastyNate2612** [comment]
hey so I noticed that there were a bunch of changes made to this PR that doesn't have to do with the content in here. Do i need to close out this PR and start a new one? If it wasnt for all the other changes done this PR should pass all checks at this point i believe.

**Comment by kevingranade** [comment]
Rebased and pushed as 2876ece5e9

**Pull request closed without merging**
