### PR TITLE
More Survival Tools Series 12

### PR DESCRIPTION
**Pull request by chaosvolt**
Minor update so far due to lack of any ideas for additions.
1. Gave copper and stone spears the "REACH_ATTACK" flag, quite belatedly
   on my part.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
How about mainlining your mod's spears and javelins some time?

**Comment by chaosvolt** [comment]
I'd be fine with that, actually.

**Comment by Rivet-the-Zombie** [comment]
I can merge this as-is; do it in a separate PR.

**Comment by chaosvolt** [comment]
Ah, okay. ^^"

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
