### PR TITLE
Nerf the fastest new zombie animals so attacks take a whole turn

### LINKED ISSUE #45803: Some of the new zombie animals attack too fast
# Is your feature request related to a problem? Please describe.
The zombie horse, woodland wight (zombie deer), barghest (zombie dog brute), hulking horror (zombie dog hulk), spearcat hunter (zombie cougar hunter), and antlered hammer (zombie moose brute) have speeds of over 150. This affects both their movement and attack speed, which makes them unbalanced.

# Describe the solution you'd like

Give them an `attack_cost` that limits their attack speed to around once per turn, as was suggested in the quotes below.

# Describe alternatives you've considered

Expanding this issue to live animals (the infamous moose attacks twice a turn too), or to other zombies that have a speed of up to 150, or even further.

Suggesting that all monsters should attack once per turn unless specified otherwise—in other words, that movement speed should be separated from attack speed.

Describing this issue as "Someone added an 'attack_cost' feature to the game, but no monster actually uses it."

Never going into a forest again, for fear of antlered hammers.

# Additional context

The speeds of the new zombie animals and upgrades are clearly based on the speeds of the live animals, and the difference between live humans and zombie humans and their upgrades. However, GAME_BALANCE.md says:

> ... under no circumstances should a zed be more than 50% faster than base character speed. Currently, this means "capped at 150".

I asked about this on Discord, and:

>[4:29 PM] kevingranade: that's pretty much out of date
[4:29 PM] kevingranade: part of the reason was that when that was written, there was no distinct "move speed" vs "attack speed"
[4:29 PM] kevingranade: and I belive there is now
[4:30 PM] kevingranade: so if there's IDK a zombie deer that can move like 10 tiles a round, but only attack once a round, that's fine
[4:30 PM] kevingranade: (especially if it can't do both in the same round)
...
[4:32 PM] anothersimulacrum: Ah, `attack_cost`
[4:34 PM] kevingranade: I think it's not super obvious, but you can give them a super high move speed and then a super high attack cost as well, and that'll effectively give them a crazy move speed and normal attack speed
...
[5:07 PM] mlangsdorf: so zombie animals that are super fast should probably have their "attack_cost" increased so they're not attacking multiple times per turn
[5:11 PM] anothersimulacrum: Probably resolves #42706 at least mostly, because that seems to be in large part about speed

No monster currently uses `attack_cost` except the Lifting Mech.

The zombie dancer, scissorlimbs, and tadpole constrictor also break the rule of "no zombies >150 speed". The dancer appears to be a blacklisted joke monster, the scissorlimbs is part of a special location and its description supports it attacking very quickly, and the tadpole constrictor is summoned by a monster with only 60 speed.

### PR DESCRIPTION
**Pull request by Cimanyd0**
#### Summary

SUMMARY: Balance "Very-fast-moving zombie animals only attack once per turn"

#### Purpose of change

Resolves #45803

#### Describe the solution

Give the zombie horse, woodland wight, and antlered hammer an `attack_cost` equal to their `speed`. A regular attack now takes a whole turn.

Do the same for the spearcat hunter, and also give its claw and bite special attacks (but not its leap) a `move_cost` equal to its speed.

Give the barghest and hulking horror a `proportional` increase in their `attack_cost` equal to the increase in their `speed`, and add a `move_cost` on their bite that approximates the same thing. An attack or bite now takes slightly less than a turn, since they're copying from a rot-weiler's 105 speed.

#### Describe alternatives you've considered

Making the same change to the antlered horror as I did to the antlered hammer, so a zombie moose doesn't attack more slowly after evolving into a zombie moose brute. Even without doing that, the brute (hammer) does hit much harder and it gains the smash and grab special attacks.

Making the same change to the normal moose, for similar reasons. The extremely dangerous moose is such an icon of Cataclysm at this point that any changes to it should be done with someone who knows more about game balance than I do, instead of just a straight nerf.

#### Testing

Used debug mode to confirm each of those monsters still move very fast, but only attack once per turn now, including biting and clawing.

### CODE REVIEW

**Comment by Cimanyd0** [comment]
This all seems very arbitrary. This only includes zombies over 150 speed, so an acidic zombear (135) and the good old zombie hulk (130) keep their faster attacks because they still don't have `attack_cost`. Nothing else does.

The barghest, hulking horror, and spearcat hunter all have special attacks with cooldowns so short they still often attack more than once per turn, so this may not even resolve the issue. Also, how is the zombie moose brute grabbing me? With its arms? Its mouth?

**Comment by Venera3** [comment]
Special attack cooldowns use 1s turns, so the cooldowns are not affected by mob speed. The reason they can still attack twice a turn is because the specials don't have a move_cost defined, if you add that they'll be golden.

**Comment by Cimanyd0** [comment]
Added move_cost to upgraded-dog bites and spearcat claws.

**Comment by Venera3** [comment]
Maybe it bites and its antler snap shut like a venus fly trap? Not gonna lie, grab is a bit of a stretch for them, and since they have a speed of 210 they could catch you even without it, making it pretty much a waste of a turn. Maybe a higher-damage scratch would make more sense for them (with the hooves and all), or give them a bite as well so they can infect at least.

**Pull request merged**
