### PR TITLE
Remove new lines and trailing white space from retro days 20 

### PR DESCRIPTION
**Pull request by Cyrano7**
756 -> 740 KB
https://github.com/CleverRaven/Cataclysm-DDA/pull/17865/files?w=1 To see removed new lines.

### CODE REVIEW

**Comment by mugling** [comment]
16KB space savings to justify an 18KLoc PR?

I'm not strictly averse to large scale cleanup of the JSON but changes of this magnitude require both justification as to necessity and must be carried out by an automated tool that can be externally verified.

**Comment by Cyrano7** [comment]
@mugling  I use a specific regex to get ride of the spaces. The same one I've been using on all the other json files for trailing white spaces and newlines. I never seem to be around whenever tilesets get added or updated so I always miss the opportunity to have them be done right the first time. I can understand if there is not enough justification for the change though.

On a separate note. The RetroDaysTileset10_spritetest tileset doesn't seem to be different then the normal RetroDaysTileset10. Is there a reason why its there?

**Comment by mugling** [comment]
> I can understand if there is not enough justification for the change though.

Pretty much this. The work you've done on JSON cleanup is appreciated but I'm not sure you'll find cleaning up `gfx` so rewarding. Note we now have an automated lint tool if you wanted to carry on with your earlier series of PR's

**Comment by Cyrano7** [comment]
I mostly do the json clean up because its the lowest hanging fruit and only takes a few minutes per PR. I guess i'll close the retrodays PRs because they are to big. But we should keep a better eye on spaces and things like "multitile": false in tileset updates in the future. Not that I want to discourage people from merging tileset but they seem to get added even if they are really dirty with unnecessary things.

**Pull request closed without merging**
