### PR TITLE
Extend support for nested containers

### PR DESCRIPTION
**Pull request by mugling**
This PR follows #14600, has no anticipated behavioral changes, and extends support for nested containers to the following methods:
- `Character::get_item_position`
- `inventory::position_by_item`
- `Character::has_item_with`
- `inventory::items_with`
- `Character::items_with`

It also provides the following new methods:
- `inventory::has_item_with`
- `item::contains`

~~Finally the `*::visit_items` and renamed for consistency with `item::visit`.~~ (see 68c4307)

Further work (separate PR) includes extending support for nested containers to `*::remove_items_with` with the eventual goal of making `std::vector<item> worn` and similar private or protected members.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
`visit_items` is more descriptive. `visit` alone would suggest that we care about the object (`player`, `inventory` etc.) at hand, not just contained items.

**Comment by Coolthulhu** [comment]
This will require performance testing:
Inventory class is used for building `inv_from_map`, meaning that any slowdown here will translate into slowdown when opening craft menu in a large area.
Preferably separate testing with gcc and clang - one of those may be less competent at inlining `std::func`s.

**Comment by mugling** [comment]
> visit_items is more descriptive

I want to avoid similar but subtly different names (`item::visit` vs `inventory::visit_items`). They all use the same pattern but differ only in their staring point in the hierarchy. Later we may add `map::visit` and `vehicle::visit`?

Again for consistency we should consider renaming `inventory::position_by_item` to `inventory::get_item_position`?

> This will require performance testing:

Yes, I recall the discussion in #14600. Clang generates identical code for templates vs `std::function` but I'm uncertain as to gcc so I'll look in to this.

**Comment by Coolthulhu** [comment]
> I want to avoid similar but subtly different names (item::visit vs inventory::visit_items). They all use the same pattern but differ only in their staring point in the hierarchy. Later we may add map::visit and vehicle::visit?

But you still visit items and not say, network of connected vehicles. Since jumper cable networks also use the visitor pattern, `vehicle::visit` would be ambiguous.
`item::visit_items` still does make sense - after all you visit not only the item, but also the contents.

**Comment by mugling** [comment]
On my far from modern laptop `inv_from_map` slows proportionally to the number of nearby items with the delay becoming noticeable around 10⁵ items.

When this PR is tested on FreeBSD with both clang 3.4 and gcc 4.9 using `RELEASE=1` there is no noticeable difference in speed between this implementation and master.

Given these are dated compiler versions running on a relatively obscure platform tested on older hardware I would be surprised if performance was significantly worse for anyone else. There is of course of the option of switching to templates or providing specialised implementations in the future if the need arises but at present given the lack of evidence I'd consider this to be premature optimisation.

**Comment by stk2008** [comment]
Is this going to allow backpacks that we can drop with items in it and then
pick it back up after fighting etc?

If so wow this is awesome

**Comment by mugling** [comment]
@stk2008 This is only one very small piece of the puzzle. I'm only working on the container logic as I require it for magazines and holsters. The UI for such a system as you describe remains an open unsolved problem.

**Comment by stk2008** [comment]
I see thanks for explaining also thank you for every thing your doing :)

**Comment by Malkeus** [comment]
@mugling Where is the UI for the system being discussed? I had a vision of a possible solution and I want to see if it's been discussed already.

It's basically an adaptation of the sort system, where the inventory would be divided by containers. Say you were wearing a backpack, cargo pants and a trenchcoat, your inventory would look like:
Backpack                  2/30volume
  plastic bottle of water   2volume
Cargo Pants             1/12?volume
  wrench                        1volume
Trenchcoat              5/14volume
  plastic bottle of water 2volume
 rock 3                          3volume
 
It would handle items only fitting in containers with sufficient volume, so no spreading a sledgehammer across the pockets of several pieces of clothing, it uses the current inventory screen to show everything you are carrying. And yes, it's essentially dwarf fortresses inventory system with a better ability to view everything. But world of warcraft does pretty much the same thing by letting you open multiple containers on screen. It's a good system that works. I'm really curious to see the past discussion.

**Comment by mugling** [comment]
@Malkeus how do you intend to handle nested containers?

**Comment by Cat09** [comment]
for nested containers, I'd suggest use of a '+' next to the container when 'closed' and a '-' and an indented list when open. It's pretty standard and works quite well. simple right and left arrows open and close the list is intuitive.
The trick I think would be handling screen space with heavily nested containers, you can do word wrapping, screen scrolling (follow your current position to some extent, like it does vertically) or a combination of both.

**Comment by Malkeus** [comment]
Cat09's idea is pretty much what I was going to suggest. I would use a
dedicated key for expanding\contracting a container, rather than left right
arrows which are already being used on both the standard inventory and AIM
screens.

An alternative to indenting would be using a symbol to denote a nested
container, the top level would have no symbol, '*' for the first layer, and
'*1', '*2', etc for each descending layer. The symbol could be placed above
or below the containers name to maintain the current alignment.
Containers could all be displayed in bold print\alternate font to make them
stand out on the screen.

Am I correct in assuming that ultimately each nested item would still have
to fit in the space available in the parent (minus the actual volume of the
nested container)? That would seem to place a limit on how crazy people
could get with nested containers.

**Comment by Cat09** [comment]
are "+" or "-" used in the inventory menu? those could be bound to the expand/collapse functions.
you would have a potential issue with deep nests, but like Malkeus said, volume would tamp down on that some. expandable containers grow to the volume of their contents + base volume right?
the biggest use for nesting in that case would be for easy organization and quick drop, I doubt people would really end up going too far.

for viewing I'd suggest the pane have the column of characters 1 to the left of the first character of your currently selected item viewable if the item name is too long to fit on the view pane otherwise.
(not very clear, sorry >.>)

**Pull request merged**
