### PR TITLE
Obsolete Dire Wolves

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
They were completely unused anywhere in the repo save for one shotgun test and one filler Backrooms mongroup. Not to mention they no longer really make sense to keep in vanilla, as wolves are restricted to small populations in zoos and in #74554 I outlined why allowing large vertebrates to mutate is problematic

#### Describe the solution
Destroy

#### Additional context
Huge shout out to Megafauna for both including additional spawns for this monster and then blacklisting it so it can't spawn

### CODE REVIEW

**Comment by SirPendrak** [comment]
Game ballance doc has one line mentioning direwolves: 
Monster melee dice size scaling:
Maximum dice size for balance purposes: 12 (hardest possible hitter; dire wolf )

**Comment by LyranRenegade** [comment]
hmm I use one in my mod which hasn't been released yet. 
Don't know why you would remove things that aren't in the way of anything..

**Comment by Karol1223** [comment]
> hmm I use one in my mod which hasn't been released yet. 
> Don't know why you would remove things that aren't in the way of anything..
> 

If it doesn't have a reason to exist, it has a reason not to. Unused content is still maintenance burden - has to be translated, ends up being accounted for in things like modded blacklists or XE vampire spells, or ends up used as useless (because they don't occur ingame anyway) examples in documentation.

If you use it in your mod, feel free to add it back to your mod, but it's not any reason to keep it in vanilla.

**Comment by LyranRenegade** [comment]
ok yeah I get that..

**Pull request merged**
