### PR TITLE
[Bombastic Perks] Add Stormwrought line of playstyle perks

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Bombastic Perks] Add Stormwrought line of playstyle perks"

#### Purpose of change

Always wanted to put something into the game that referenced [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/32850991c495930ed18c3a10f05494697eea905b/data/json/effects_on_condition/nether_eocs/portal_storm_effect_on_condition.json#L1216) (aka the Catgirl gene), and finally figured out to a way to do it that's not silly.

#### Describe the solution

Add a set of playstyle perks, called Stormwrought [X], where [X] is one of Bird, Feline, Insect, Lupine, Plant, or Spider.  These trigger EoCs that, when you're out unprotected in a portal storm, run every 5-30 minutes and have a 1/3 chance when they trigger to mutate you in the appropriate category. ~~Post-instability rework, this just uses `u_mutate_category`, since there's no necessity to use vitamins to track instability anymore~~. Edit: `u_mutate_category` seems to automatically bring up the mutation selector which doesn't fit with portal storm randomness, so it's back to mutagen.  To work around the issues with `u_mutate_category`, the EoC adds primer and mutagen, forces a mutation with `u_mutate`, then removes primer and mutagen to return to baseline, causing one mutation per EoC trigger. 

You can only have one Stormwrought perk. 

There's no reason to limit it to those mutation lines, I just had to start somewhere. 

#### Testing

Traits exist and are selectable, show up in their own menu (so they don't overwhelm the other Playstyle perks if more are added), and hanging out in a portal storm causes mutation. Mutagen properly removed after mutating. Wearing a 5-point anchor prevents mutation. 

#### Additional context

It'd be nice if `u_mutate_category` had a kwarg that turned on or off the selector. I double-checked and `SHOW_MUTATION_SELECTOR` is set as false (the test world just had default mods + Bombastic Perks)

### CODE REVIEW

**Comment by Standing-Storm** [comment]
Drafting to account for threshold breaking with the add mutagen / mutate/ subtract mutagen method. Will implement tomorrow

**Comment by Standing-Storm** [comment]
Alright, this approach works and doesn't cause negative primer levels or anything.

**Comment by Standing-Storm** [comment]
n

**Comment by Maleclypse** [comment]
OOH I just realized it would be very thematic for Dinomod to have this for their Dino trees.

**Pull request merged**
