### PR TITLE
Facility items 003 chemicals (reprise)

### PR DESCRIPTION
**Pull request by Aenye**
Using the discussion from https://github.com/CleverRaven/Cataclysm-DDA/pull/9215 I've put up a tiered system for chemicals and populated it with the first batch of chemicals and a nice bomb to keep things interesting.

In total, I am planning some 30 chemicals (15 out of the way already, 10 more shortly) and some 20 devices (among them: Thermite, RDX, HMTD, TCAP, Powder charge, Hexamine, Smoke curtain, Rocket Candy, Home-made rocket).

Please comment on what do You think of these ideas and tell me if there is something obvious, that I should add to the list.

### CODE REVIEW

**Comment by Aenye** [comment]
PS: Happy New Year guys !

**Comment by KA101** [comment]
Hence why I'd like to get the fireworks merged in time.  ;-)

**Comment by KA101** [comment]
RDX charge either needs downtuned or the mininuke uptuned, as the keg-o-boom has a much nastier blast.  But I'm inclined to leave it for another PR.

**Comment by Aenye** [comment]
Will boost the mininuke a bit, then - only a bit is needed, as the huge weight of the RDX charge (and the ingredient cost) are balancing factors in this.

**Comment by KA101** [comment]
I'm fixing this on my end, please don't file a commit: letters are kinda reserved for critters, rather than items.  Most of these should be = for dry ingredients, ~ for liquids, * for the thrown charges, and I used ( for the keg.

Just need to get that sorted, check up the books, and this'll be ready to go.

**Comment by Aenye** [comment]
Ok, not pushing any commits unless You say so.

**Comment by KA101** [comment]
Added a couple to the chem textbook and cleaned up the JSON.

And now, time to bring the noise.  :-D

**Comment by Aenye** [comment]
Hoorray ! Thanks for all Your help ! :D

**Comment by KA101** [comment]
Thank you for all yours.  :-)

**Pull request merged**
