### PR TITLE
Vending machine fixes

### PR DESCRIPTION
**Pull request by bkentel**
I'm not 100% satisfied with this yet, but it's at a place where some feedback would be welcome.
- New: Items are grouped together by name and listed with a count (0...9, or \* if more); no more endless jumbled pages of items.
- Fixed: item names overflowing the bounds of the windows.
- Fixed: item selection now shows only cash cards (and equipment).
- Use `mvwhline` instead of a hand-rolled loop.
- Adjusted alignment to allow slightly longer item names.
- Use `WINDOW_PTR` aka `unique_ptr` instead of naked new and delete.
- Tried to clarify some of the inline constants.

### CODE REVIEW

**Comment by bkentel** [comment]
I still might play with the implementation a bit, but functionality wise, what do you guys think?

**Comment by KA101** [comment]
Not my line of work, I'm afraid.

**Comment by bkentel** [comment]
I mean, how do you feel about grouping like items together with a count in the vending machine interface?

**Comment by Rivet-the-Zombie** [comment]
>I mean, how do you feel about grouping like items together with a count in the vending machine interface?

**DO WANT**

**Comment by DavidKeaton** [comment]
Agreed, would be marvelous.

**Comment by KA101** [comment]
Quibble: buying stuff doesn't decrement your cash card as displayed in the vending-machine window.  Can be fixed in another PR if you don't see this in time (if you do, reply, so I don't miss any commits!)

**Comment by bkentel** [comment]
@KA101 just saw your comment now (paradoxically, weekends are a busy time for me) -- I'll take care of your quibble and maybe one or two other small points that came to mind in another PR.

**Comment by KA101** [comment]
np, it's Cheap Candy Eve so you might be busy.

**Pull request merged**
