### PR TITLE
Allow taming ducks with birdseed

### PR DESCRIPTION
**Pull request by Proxiehunter**
Category "Features"
 
#### Purpose of change

Ducks seem to be untameable currently. Since real life farmers have been known to keep ducks for duck meat, duck eggs, and feathers it seems that they _should_ be tameable in game the same way chickens are. Birdseed seems the most logical way to do that.

Consider also applying to geese which are also sometimes kept by real life farmers and to crows which are relatively easily tamed in real life.

This would increase players access to eggs for both cooking and mutagen creation.

#### Describe the solution

Replace the current entry for ducks under the bird.json with this one (Updated with code from the correct fork this time I hope):

"id": "mon_duck",
    "type": "MONSTER",
    "name": { "str": "duck" },
    "description": "A mallard duck, often seen around rivers and other bodies of water.  It feeds primarily on insects, seeds, roots, and, pre-Cataclysm, bread scraps.",
    "default_faction": "small_animal",
    "bodytype": "bird",
    "categories": [ "WILDLIFE" ],
    "species": [ "BIRD" ],
    "volume": "1500 ml",
    "weight": "1500 g",
    "hp": 4,
    "speed": 140,
    "material": [ "flesh" ],
    "symbol": "v",
    "color": "brown",
    "aggression": -99,
    "morale": -8,
    "melee_dice": 1,
    "melee_dice_sides": 1,
    "melee_cut": 0,
    "dodge": 4,
    "harvest": "bird_small",
    "fear_triggers": [ "SOUND", "PLAYER_CLOSE", "FRIEND_ATTACKED", "FRIEND_DIED", "FIRE", "HURT" ],
    "death_function": [ "NORMAL" ],
    "reproduction": { "baby_egg": "egg_duck", "baby_count": 3, "baby_timer": 5 },
    "baby_flags": [ "SPRING" ],
    "biosignature": { "biosig_item": "feces_bird", "biosig_timer": 5 },
    "flags": [ "SEES", "HEARS", "SMELLS", "ANIMAL", "PATH_AVOID_DANGER_1", "WARM", "FLIES", "SWARMS", "BIRDFOOD" ]

The bold indicating the only change to the entry. As I understand it this would allow ducks to be tamed with bird seed.

#### Describe alternatives you've considered

Alternative solutions are to either use something else to tame them (not sure how that works, could BREAD be added or is just limited to the typical ones like bird food, cat food, dog food, and cattle fodder?) or continue to _not_ allow players to tame ducks. 

#### Testing

I have not tested but this is a solution I've seen offered when a player wants to tame a creature that was not initially designed to be tamed and this simple edit should not cause errors. I can test it in the next few days if need be.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I think you may have PR'd the wrong branch.

**Comment by Proxiehunter** [comment]
> 
> 
> I think you may have PR'd the wrong branch.

Technically yes I did mean for this to go to BN but to my knowledge you can't do it in mainline either (I first noticed that you couldn't tame ducks when watching Rycon's Dusk series in mainline cata) and there's no reason it shouldn't apply to both. Is something different about the duck entry in mainline and bright nights I wasn't aware of? I need to head out the door but I can replace the duck file with the one from mainline when I get back in a couple hours.

**Comment by Maleclypse** [comment]
> > I think you may have PR'd the wrong branch.
> 
> Technically yes I did mean for this to go to BN but to my knowledge you can't do it in mainline either (I first noticed that you couldn't tame ducks when watching Rycon's Dusk series in mainline cata) and there's no reason it shouldn't apply to both. Is something different about the duck entry in mainline and bright nights I wasn't aware of? I need to head out the door but I can replace the duck file with the one from mainline when I get back in a couple hours.

Yes.  However, at the moment this PR cannot possibly be merged because it is trying to add tameable ducks and change DDA into the same code in every way as BN.  If you look at all the conflicts or even the number of changed lines you can see you'd need to open a new PR that's based on a DDA fork.

**Comment by anothersimulacrum** [comment]
Not even a dda fork, just a branch based on DDA, instead of BN's master branch.

**Comment by Proxiehunter** [comment]
> Yes. However, at the moment this PR cannot possibly be merged because it is trying to add tameable ducks and change DDA into the same code in every way as BN. If you look at all the conflicts or even the number of changed lines you can see you'd need to open a new PR that's based on a DDA fork.

Which is why I said I was going to change the code to use the correct code from this branch as soon as I was able. It's going to be a moment, updating to the newest available release.

**Comment by PatrikLundell** [comment]
Wild ducks aren't of the same race as domesticated ones, so I think it's appropriate to allow the taming of adult birds to be restricted to chicken, while other species should be tameable only when young. However, being able to tell which species a chick belongs to would help you to select the chicks you want to tame with a higher precision.

**Comment by actual-nh** [comment]
> Wild ducks aren't of the same race as domesticated ones, so I think it's appropriate to allow the taming of adult birds to be restricted to chicken, while other species should be tameable only when young. However, being able to tell which species a chick belongs to would help you to select the chicks you want to tame with a higher precision.

Unfortunately, the bug/current limitation described in #47145 makes "tamable only when young" not really work. (I am also dubious about the degree to which wild and tame ducks differ except in raising, particularly with the spread of mallard genetics.)

**Comment by anothersimulacrum** [comment]
> > Wild ducks aren't of the same race as domesticated ones, so I think it's appropriate to allow the taming of adult birds to be restricted to chicken, while other species should be tameable only when young. However, being able to tell which species a chick belongs to would help you to select the chicks you want to tame with a higher precision.
> 
> Unfortunately, the bug/current limitation described in #47145 makes "tamable only when young" not usable. (I am also dubious about the degree to which wild and tame ducks differ except in raising, particularly with the spread of mallard genetics. Source(s)?)
 
I have recently hatched some eggs, tamed some chicks, and had them successfully grow up to adults (ducks included).

**Comment by actual-nh** [comment]
> > > Wild ducks aren't of the same race as domesticated ones, so I think it's appropriate to allow the taming of adult birds to be restricted to chicken, while other species should be tameable only when young. However, being able to tell which species a chick belongs to would help you to select the chicks you want to tame with a higher precision.
> > 
> > 
> > Unfortunately, the bug/current limitation described in #47145 makes "tamable only when young" not usable. (I am also dubious about the degree to which wild and tame ducks differ except in raising, particularly with the spread of mallard genetics. Source(s)?)
> 
> I have recently hatched some eggs, tamed some chicks, and had them successfully grow up to adults (ducks included).

Tame adults? Has the CDDA bug gotten fixed (or is this IRL)?

**Comment by anothersimulacrum** [comment]
This is in game :)

**Comment by PatrikLundell** [comment]
I've tamed various kinds of chicks in 0.E2 stable without seeing any indication of problems. The grown birds remain friendly and lay eggs that can then hatch into chicks that can be tamed. However, someone might have broken that since then.

**Comment by Xaleth** [comment]
This seems useful and an IRL way to do it: https://www.tyrantfarms.com/how-to-get-your-ducks-to-like-you-three-tips/

**Comment by anothersimulacrum** [comment]
@Proxiehunter Can you please either close this PR or fix it up?

**Comment by ZhilkinSerg** [comment]
It looks like you have opened this pull request accidentally.

**Pull request closed without merging**
