### PR TITLE
Mainline .45 pipe rifle from Craftable Gunpowder mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Mainline .45 pipe rifle from Craftable Gunpowder mod"```
#### Purpose of change

Adding more variety in makeshift ranged weapons. Since it's an one-shot pipe rifle, not a full-auto SMG, it could be in mainline. Also prevents mod content from becoming bugged or broken due to mainline changes. Stats and recipe got altered to be the same as 9mm pipe rifle, but ammunition used is different.
#### Describe the solution

JSON changes.
#### Describe alternatives you've considered

None.
#### Additional context

None.

### CODE REVIEW

**Comment by Zireael07** [comment]
IIRC the game leans away (as of recently) from crazy homebrewed stuff, so both pipe rifles belong in a mod?

**Comment by Rail-Runner** [comment]
Why? It's very much possible to build primitive homemade firearms like one-shot rifle.

**Comment by Photoloss** [comment]
Well
> Also prevents mod content from becoming bugged or broken due to mainline changes.

is pretty much spot-on as far as that goes. Longer crafting times and more involved metalworking tools (e.g. a lathe) should definitely be applied to this variant if the others are updated.

Based on the description and the recipe I don't think it should be called a "rifle" though when there is nothing to actually apply rifling *with*. The damage stats and viability of firing .45 cartridges without rifling should be double-checked by someone who actually knows their way around guns.

**Comment by Rail-Runner** [comment]
Well, it is a rifle, except it has a smoothbore barrel. No idea how to correctly name such a thing, but if it does get renamed, other "pipe rifles" should be renamed as well.

**Comment by chaisawlajatang** [comment]
You're planning to mainline gunmod and mediecal mods entirely one recipe by one, don't you?

**Comment by Photoloss** [comment]
> Well, it is a rifle, except it has a smoothbore barrel. No idea how to correctly name such a thing, but if it does get renamed, other "pipe rifles" should be renamed as well.

[Smoothbore](https://en.wikipedia.org/wiki/Smoothbore) could be used as a noun and should tip off anyone who knows their stuff that this is a very primitive and thus unreliable weapon. Other historical terms include [Arquebus](https://en.wikipedia.org/wiki/Arquebus) or [Musket](https://en.wikipedia.org/wiki/Musket) but those of course never used modern cartridges. For larger calibres or if you want to get *really* primitive there's also the [Gonne](https://en.wikipedia.org/wiki/Hand_cannon) which is another term for "hand cannon". All of those were muzzle-loaded so at least that part fits.

If all else fails simply calling it "pipe gun" would still be more accurate unless there is a significant culture of knowingly calling smoothbores "rifles" in New England (ignorance doesn't count)

**Comment by Rail-Runner** [comment]
> You're planning to mainline gunmod and medieval mods entirely one recipe by one, don't you?

Yes. Do you think it's a better idea to do otherwise?

**Comment by Throwaway-name** [comment]
Could someone replace the full-size sheet metal requirement in the STEN recipe with the new small sheet metal items?

**Comment by kevingranade** [comment]
Check your dispersion, this needs to be the least accurate .45, not the most accurate one.

**Comment by Rail-Runner** [comment]
It has just as much dispersion as 9x19mm pipe rifle does. It might be like that because there are no factory-made .45 rifles currently, and 9x19mm pipe rifle is similarly more accurate than 9x19mm pistols and SMGs (it is as accurate as existing 9x19mm carbine Cx4 Storm, but the carbine has a much shorter barrel than the rifle)

**Comment by kevingranade** [comment]
> No idea if it's supposed to be like that, but if it isn't inteded, then all pipe rifles need to have their dispersion increased.

Yep, they should collectively be the least accurate guns in the game by a wide margin as they aren't even rifled.

**Comment by Rail-Runner** [comment]
Done. Raised dispersions of all smoothbore guns, assuming 520 for rifle-sized guns, 590 for SMGs, 620 for pistol-sized guns, 855 for makeshift shotguns, and 900 for makeshift shotgun pistol.

**Pull request merged**
