### PR TITLE
[MOM] Add Chronokinetic Path (DRAFT)

### PR DESCRIPTION
**Pull request by b3brodie**
#### Summary
MOM "Add Chronokinetic Path"

#### Purpose of change
Add a new path that allows a lot of unique types of power interactions.  Note, this description and everything within is incredibly TODO.

#### Describe the solution
Adds chronokinetic path and related infrastructure for a new path

Current Powers:
- Time Freeze: Target cannot move, act, etc in any way, but they are also incapable of taking damage.  Useable on any target.
- Time Bubble: AOE version of time freeze but it also freezes the air and everything else within.  Nothing(tm) can enter the bubble (vehicles included) while it exists nor can anything within be damaged.
- Stabilize Timeline(C): Prevents being affected by time freeze or time bubble (any future powers).  Also allows moving within Time Bubbles.
- Chronal Acceleration(C): Speeds up the psion by quickening the progression of their own timestream compared to everything else.

Current TODOS:
- Power to prematurely end time freezes / bubbles in a neutral manner
- Power to prematurely end time freezes / bubbles in a negative manner
- Power to momentarily massively increase the timeflow on a target.  For most targets, this will express itself via evolving them into their next monster type.
- Power to reverse the last instance of damage taken
- Meditation power to alter the characters age
- ?Infrasture to allow editing a characters age? - haven't looked if it exists
- Mediation power to massively slow the users timeflow, effectively fastforwarding the date into the future
- Some manner of power that acts similar to "mark and recall" where the mark is maintained via a concentration power
- Other powers as I think of them
- Some manner of activity type or similar to make time frozen players automatically progress their time freeze instead of having to manually skip turns while waiting for it to end.
- Potentially make time freeze also pause effects, vitamins, nutrition, etc.
- Actually balance the numbers on the powers
- Add learning methods for the powers
- Add all the other little things that aren't there yet
- A lot more testing
- Documentation
- Do another pass through all the c++ code to make sure everything looks good
- Feral Chronokinetics here? Probably better in another PR

#### Describe alternatives you've considered
Some form of breaking up this PR since a lot of the powers will require c++ additions for them.  I'm currently looking to keep it all in one place though.

#### Testing
time bubble beats car

#### Additional context
This is also a Worm reference

### CODE REVIEW

**Comment by Standing-Storm** [comment]
Control of time itself is way too magical for the feel I want in MoM.

**Comment by SariusSkelrets** [comment]
There's also balance to take in consideration. The path's passive might not seem much with only +1 speed per 10 levels, but it's permanent speed that isn't disabled by anything that interferes with psionincs. That speed boost is then stacked with Chronal Acceleration for even more speed and any eventual slowing power for more relative speed compared to the opponent. 

When I think about it, I should make that other paths have their passives disabled while close to psi-nulls as these passives are psionic abilities.

Some feedback for the powers themselves:

- Time Freeze: massive panic button. If it is used, you didn't planned to kill the foe anyway. Could work with a reasonable cast time and duration.
- Time Bubble: even more massive panic button that allows to freeze a horde. Useless without the below buff, game-breaking with it. Dividing its duration by the amount of targets could make it closer to balanced but the issue of it being not worth using without another power remains.
- Stabilize Timeline: allows to freeze a horde and walk through it without spending more than some stamina. The combos are incredibly potent with it. It needs a restriction, cost or anything to not synergize too hard with the bubble or else you have the strongest panic button ever.
- Chronal Acceleration: speed boosts are very powerful, no matter how small. I can see people taking the path only for the speed it gives. Capping the max boost would help to keep it reasonable.
- Power to prematurely end time freezes / bubbles in a neutral manner: unless there's an ongoing cost to maintaining a freeze, I only see this help while kiting. Very niche at best.
- Power to prematurely end time freezes / bubbles in a negative manner: freeze - damage - freeze - damage etc until enemy is dead. Making the cast cost too high to stunlock enemies that way is mandatory as a sufficiently long stun will allow to regain enough stamina to stun the enemy again. It isn't that effective against groups, but since your balance intentions are that time-frozen foes cannot be damaged, I decided to mention it.
- Power to momentarily massively increase the timeflow on a target: I fail to see the benefit of this, as things that evolve are most often enemies. Unless NPCs suffer from dehydratation from days spent standing still or some other painful thing like that. And wouldn't that give the target the equivalent of a massive time dilatation, allowing them to crush you in the blink of an eye?
- Power to reverse the last instance of damage taken: the simple way is going the mageshield way with a concentration spell (described as preparing to undo the next damage you take the instant you take it at a stamina cost). It's way simpler than tracking all hits so they can be reverted individually.
- Meditation power to alter the characters age: age isn't doing much currently and deciding what it should do is a can of worms.
- Mediation power to massively slow the users timeflow, effectively fastforwarding the date into the future: I do not see the use of it. Food rots, zombies evolve, other things happen and you gain nothing of doing that.
- Some manner of power that acts similar to "mark and recall" where the mark is maintained via a concentration power: check the magus mark and the Construct a Winch spells for examples as they work exactly like that minus the concentration.

And by the way, time powers always end up as magic or "so advanced those unaware of the inner workings will call it magic" as the amount of important details that are ignored for the powers to work without bringing a ton of questions are immense. For example, how do rewinding time doesn't cause a paradox? Your goal is to alter things in a way you won't have to rewind, thus preventing you to rewind it at all because the thing that allowed the change never happened, so the change never happened.

I second that XE would be a better place for time powers. After all, years being seconds and minutes being decades is something expected while in the realms of the Fae.

**Comment by Maleclypse** [comment]
If you'd be interested in adding this to XE what would you imagine this as being it's zone of operation?  Would this be limited to a new species or a new magickal class outside of the existing, an attunement of some sort?

**Comment by b3brodie** [comment]
> Some feedback for the powers themselves:
> 
> I second that XE would be a better place for time powers. After all, years being seconds and minutes being decades is something expected while in the realms of the Fae.

So I will be moving this to XE which is going to change a lot of things up, but I'll address my thoughts on some of the points here since they'll also apply in XE.

Time Freeze Mechanics: Time freeze does serve as a good panic button since it prevents monsters from damaging players.  However, it also prevents the players from harming the monsters as well, which in my opinion prevents one of the main goals of encountering hostile monsters: killing them.  Time frozen monsters drop no loot, no skill training, and will of course be eventually unfrozen and thus making the area dangerous again.  Unlike the vast amounts of methods of permanently fixing the problem in a more beneficial way, time freezing is a temporary fix.

Time Bubble:  I'd disagree on it being useless without the stabilization power: in addition to freezing enemies themselves it can also block off passageways or even just add some extra time to reach the player while they are still capable of casting spells through it.  As for the synergy with stabilization, this is definitely intended for players to be able to walk through their own bubbles, but balanced in them still not being able to do much in them anyways.

Stabilization: Mostly gone over above, but freezing a horde is ultimately less useful than killing them.  It won't be a direct translation, but MOM has several anti-horde powers such as wrecking ball that give far more output than just being able to temporarily pass through a horde.

Chronal Acceleration: Numbers were a big TODO since the PR was still in draft

Ending a Freeze: I'd consider this more than just niche since it gives the psion the ability to choose their battles much more effectively.  IE freezing multiple enemies and then unfreezing one, or freezing an enemy at low stamina and then unfreezing them at high stamina.

This is admittedly one of the more magicy powers, but it was intended as more of an aging power than a speed boost power.  This is more niche, but there are definitely circumstances where buffing zombies can help, such as multi-faction combat or just a high end player wanting better skill training.  This is not to mention all the non-evolving creatures that the power would be much more negative to.

For the other things that seem less relevant, they'd be put in place with plans on expansions of other things to the world, such as enemies that can age a player.

**Comment by b3brodie** [comment]
Reimaging in #78111 for XE with prep for scenario time class

**Pull request closed without merging**
