### PR TITLE
Improve mod comparability regarding addition of rare flora

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
None

#### Purpose of change
Several mods (including Innawood, Magiclysm, and TropiCataclysm) adds rare flowers. The way this is done can cause issues if more than one of these mods are loaded at a time. This change would help mitigate some of those issues.
The main reason for this PR is to make Magiclysm, Innawood and TropiCataclysm rare plants work better together.

#### Describe the solution

- In data/json/regional_map_settings.json, multiply all weights in t_region_groundcover_swamp, f_region_flower, f_region_weed, f_region_plain, f_region_forest, and f_region_forest_dense by 100
- Magiclysm had previously copypasted and multiplied by 30 the default 'f_region_flower' and 'f_region_weed' plants weight to help make magic plants rarer. In this PR, I removed the data that was copied from data/json/regional_map_settings, and multiplied the weights of the magical flowers by 3.333. The net result of this should be no functional change if you are only playing Magiclysm. (See Testing for an issue with this)
- Furthermore, it seems like Magiclysm forgot to add the magical plants to f_region_plain, f_region_forest, and f_region_forest_dense, resulting in the plants probably almost never spawning. I fixed that by adding the magical plants to these relatively new categories. 
- Updated TropiCataclysm with the latest version of json/regional_map_settings.json while maintaining all the unique changes the mod does. Again, this should have no noticeable mechanical effect. I'd welcome a sanity check on these changes to make sure I didn't acidentally delete something from TropiCataclysm.
- Changed \aftershock_exoplanet\region_settings.json so that the total weight in f_region_weed matches the new weight in the base game. This should have no effect if you play with this mod alone, but should make it so that if you play with both aftershock_exoplanet and Magiclysm, the magical flowers spawn in rougly the same frequency as they do with only Magiclysm installed. Whether or not it is desirable for these plants to spawn at all here is a different question not dealt with here. (Also see Testing for an issue with this)
- Updated No_Hope, classic_zombies, desert_region, and rural_biome to use the new weights
- Altered Innawood from using region_settings to instead use a much more compact region_overlay, and also updated weights. This should have no effect if the mod is played alone, but should make it more compatible with other mods, perhaps most notable Magiclysm and Dinomod. This should also make it so that Innawood doesn't prevent newly added plants from spawning, reduce maintenance, and increase readability.
- man made map extras has been tagged with MAN_MADE. The fact that MAN_MADE is blacklisted is now used to filter these out in Innawood, instead of redefining the lists of allowed map extras. This should mean that newly added natural map extras no longer gets blocked by Innawood by default, and should reduce maintenance and increase readability.
- multiply t_region_groundcover weights by 1000. This should make it so that Innawood is compatible with TropiCataclysm if (and only if) Innawood is loaded after TropiCataclysm.

#### Describe alternatives you've considered
Multiply all, or at least more of the weights by 100
Changes done in PR #58727
Let it be and let the weights be wrong

#### Testing
Turns out that if you load a mod with a region_overlay, and then load a mod with a region_settings, the region_overlay seems to get completely discarded. see issue #60394
That means that if you load say Dinomod and Magiclysm, and then load a mod such as TropiCataclysm, the dino nests from DinoMod and the magical flowers from Magiclysm does not show up.

Other than that, from what I can tell, everything seems to still be working.

### CODE REVIEW

**Comment by Light-Wave** [comment]
Poking @Xaritscin to sanity check my TropiCataclysm alteration.
Poking @GuardianDll to check that you really want the plants to spawn in the wilderness, and the distribution between plains, forest, and deep forest looks reasonable.

**Comment by GuardianDll** [comment]
Looks great for me. Thank you for your work!

**Comment by Xaritscin** [comment]
Looking at the commits it appears you only changed the ground cover stuff so unless you literally copypasted the whole regional settings into the TropiCata file i dont see much issues. save for the modded fruit trees past line 145, you may have gutted them when you pasted the new forest cover.

otherwise i dont see any other part of the file being erased.

**Comment by Light-Wave** [comment]
> the modded fruit trees past line 145, you may have gutted them when you pasted the new forest cover.

It seems like I indeed accidentally removed some fruit trees. I've put them back now.

**Pull request merged**
