### PR TITLE
[MoM] More nether attunement effects

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] More nether attunement effects"

#### Purpose of change

The high end of Nether Attunement is a bit bare of really dangerous stuff that can happen to you. Time to add a few.

#### Describe the solution

Add a few more Nether Attunement effects:

- Nether Conduit: (req Nether Attunement 3) Prevents your Nether Attunement from going down while in effect, and occasionally raises it. Can last quite a while (maximum possible duration is 4 days if you already have max Nether Attunement when you get it). 
- Feedback:  (req Nether Attunement 5) Has a chance of causing pain when you use your powers while the effect lasts. The chance of pain is relative to your Nether Attunement. This also can occur when you concentrate on your powers.
- Nether Attenuation:  (req Nether Attunement 6) Multiplies casting time by 5 as you have to strain to pull the energies from the Nether. If you have Nether Conduit, you are immune to this effect, and vice versa.
- Nether Lightning (req Nether Attunement 9) Unleashes a blast of unearthly energy around the psion, damaging them and anyone else.
- Mutation: (req Nether Attunement 12) the surge of Nether energy causes a permanent change. This draws from a small list of thematic mutations (currently Jittery, Kaluptic Psychosis, Bad Temper, Mood Swings, Chemical Imbalance, Animal Discord, and Insomnia), you're not suddenly going to turn into a catgirl from using pyrokinesis. 
- Rift: (req Nether Attunement 12 and the Observed or the Nether Conduit effects): Opens a Tear in Reality on top of you. 

More to come.

#### Testing

Tested each EoC, they all work.

### CODE REVIEW

**Comment by Nebnis** [comment]
is the rift permanent? That seems...pretty egregious to say the least if you end up popping on your base by accident since it will make the place pretty much unlivable

**Comment by SariusSkelrets** [comment]
Yeah, a rift is an extremely harsh punishment for attunement, much more than all others

If it's something incredibly rare that you almost need to force for it to happen, then it might work

If not, you get the same problem than tear-causing artifacts: using them is not worth it at all as a tear is a huge, permanent problem that almost nothing is strong enough to justify making a tear

If I calculated well, a level 5 spell would reach a 27% percent chance to make a tear every time the event fires so using a power above attunement 12 would be a risk of getting a permanent problem. The player is also likely to have the raising effect that is both long-time and comes from attunement, leaving them the choice of not using powers or to risk tearing existence multiple new ones should they get it

As Nebnis suggested, spawning a monster is much less harsh and also lines much more with what psionics can cause (uncontrolled version of breach) than permanently ripping the barrier between worlds

**Comment by Standing-Storm** [comment]
> If it's something incredibly rare that you almost need to force for it to happen, then it might work

Well, it requires a pre-requisite effect and that you have max Nether Attunement before it even has a chance to trigger, and it's competing against all the other possible Nether Attunement effects, so "every time the event fires" is only 1.4% of the, and then only 27% of the time after that.

To put things in perspective, there already is a Nether Attunement even that summons a Nether creature--it can trigger a group of Hounds of Tindalos on top of you, under basically the same conditions. It's been in the game for months, and I have never once seen a story of it happening to people.

**Comment by Nebnis** [comment]
Even if is a really low chance, i wager making an entire reality bubble dangerous/usless where this rift pops isn't going to sit well with most people when it happens. Imagine it spawning somewhere important like the hub, the shelter, etc. You basically just bricked your save.

The hounds are easy to escape/slow/can be killed whenever they pop up, a rift is irreversible and uncounterable permanent damage, unless you digged into the code to know about this.

**Comment by Standing-Storm** [comment]
> I found myself spamming my powers at home to train it, and getting to 12 is very easy when you doing mass training of the powers to level them up, so i assume sooner or later, i would spawn one of those in.

One of my goals is to discourage this by having more long-term possible consequences at higher levels of Nether Attunement.  High levels should be a big deal and not something you want to spend much time on unless you really need the power, or unless you're in a bad situation and have to do it to survive. It should feel like you're tempting fate, not just, "Oh, I'll just facetank the consequences, they won't matter tomorrow anyway"

> Maybe we could add a power that close rifts at very least? Something from one of the schools.

There won't be a power to do this (it'll probably be a crafting recipe) but I do plan to include a way to deal with rifts.

**Comment by MNG-cataclysm** [comment]
What if we included Eaters in the monster spawning events, with a chance a few might appear on top of you?

**Comment by Standing-Storm** [comment]
> What if we included Eaters in the monster spawning events, with a chance a few might appear on top of you?

This would also be a good high-Attunement event, since my conceit for Eaters is that <details>
  <summary>Spoiler warning</summary>
  They aren't actually independent creatures, they're the feeding organs of some multidimensional _thing_ extended into Earth
</details>

**Pull request merged**
