### PR TITLE
Removed Bore mod location from guns that don't use it, standar-ished mechanism slots to 2.

### PR DESCRIPTION
**Pull request by carlarctg**
#### Summary
Content "Removed Magazine & Bore gunmod location from guns that don't use it"

#### Purpose of change

Seeing the "bore" location on every gun is an eyesore, especially when you're being a nerd and overly customizing your gun. But it applies outside of that as well. It's also just entirely unnecessary and too confusing for new players.

Mechanism slots were all over the place. 4 looked ungainly in the examine screen and was complete overkill, some guns had 2, others had 1, most had 4.. setting it to 2 is enough for firearm waterproofing and match trigger, which are the only unintegrated mechanism mods you're actually going to see ingame, and you probably shouldn't fit too many things inside the firing mechanism of a gun. I kept the pipe rifles and similar at 1 mechanism slot because that seems reasonable to me.

Removed magazine gunmod slot as it was unused

#### Describe the solution

Removing the bore location entirely from all guns that don't have a conversion kit, including base types.

Setting mechanism slots to 2, except for some handmade guns which have 1.

#### Describe alternatives you've considered

None!

#### Testing

Spawned in, found a soldier with a gun, saw that the bore slot was still there with a conv. kit. Spawned a gun & kit and made sure it fit.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Aftershock has bore mod `"id": "afs_shotgun_gauss"` that can be applied to any shotgun. Can you please move that to the barrel slot and ensure that all aftershock shotguns can take barrels mod while at it.

**Comment by carlarctg** [comment]
> Aftershock has bore mod `"id": "afs_shotgun_gauss"` that can be applied to any shotgun. Can you please move that to the barrel slot and ensure that all aftershock shotguns can take barrels mod while at it.

Any reason it can't be made a mechanism mod instead?

**Comment by John-Candlebury** [comment]
> Any reason it can't be made a mechanism mod instead?

Yes, guns only have 1 barrel slot, just as they used to have a single bore slot. Please move it there.

**Comment by carlarctg** [comment]
Wait magazine is also a totally unused gunmod location. BRUH

**Pull request merged**
