### PR TITLE
Adds ability to add effects from a mutation, and a mutation using it to incubate Dermatiks

### PR DESCRIPTION
**Pull request by MylieDaniels**
#### Summary
Features "Mutation activation can now add effects, also a Dermatik Incubation mutation to use this feature"

#### Purpose of change
This adds the ability for activating or reflex activating an ability to add any effect of any duration to any player bodypart.  Needing an example for this, I also added an insect post-threshold mutation that allows for infecting yourself with dermatik larva as an activation, roughly comparable to the Slimespring mutation.  But way scarier.

#### Describe the solution
Mutations can now have "effects" specified, a list of lists of values that specify the effect id, effect duration, affected bodypart, and whether the effect is permanent.
The example of this is the DERMATIK_INC mutation, which applies dermatik infestation to your torso at the cost of calories and water.
DERMATIK_INC mutation also increases the chance to spawn tame dermatik larva from 33% to 100%

#### Describe alternatives you've considered
Not adding a horrifying mutation that allows parthenogenesis of parasites in your skin.

#### Testing
Ran through a few test mutations, then settled on this one and accidentally died of torso damage after 3 successful Dermatik incubations.

#### Additional context
Draft until I write the documentation and stylize

### CODE REVIEW

**Comment by Ramza13** [comment]
So this is a good idea but too limited.  Instead of just adding a hardcoded effect mutation activation you should probably get it to run effect_on_conditions's so that we can enable the full range of json power here.  It would also be less code.  And if you are feeling adventurous doing the same thing for bionics would also be nice. 

Also for stuff like this you should update the documentation to reflect the changes.
I know this can be a lot to take in, so if you need any help doing so or want me to just do it for you let me know.

**Comment by Fris0uman** [comment]
The dermatik thing seems pretty nonsensical to me. I already find very weird that the larvae that were laid into you to use you as food suddenly follow you like if they were duklings but now you can sudenly grow some out of your own body?

**Comment by Mikenyes** [comment]
Ramza13
> So this is a good idea but too limited. Instead of just adding a hardcoded effect mutation activation you should probably get it to run effect_on_conditions's so that we can enable the full range of json power here. It would also be less code. And if you are feeling adventurous doing the same thing for bionics would also be nice.
I can definitely do both!  I assume the desired implementation would be to trigger a check of an EOC by activating a mutation/bionic?

Ramza13
> Also for stuff like this you should update the documentation to reflect the changes.(edit just saw you mentioned that so ignore me) I know this can be a lot to take in, so if you need any help doing so or want me to just do it for you let me know.
I was waiting for this kind of feedback before updating the docs, I usually keep that as my last step... totally not just because I don't like writing docs.


Fris0uman
> The dermatik thing seems pretty nonsensical to me. I already find very weird that the larvae that were laid into you to use you as food suddenly follow you like if they were duklings but now you can sudenly grow some out of your own body?
I agree that the grubs following you after normal infestation is strange (and if this was added perhaps it would be a good idea to make "normal" dermatik infestation always produce hostile grubs), but I feel that it makes sense for a mutant that has developed insect limbs, wings, chitin, and etc to be able to produce eggs/grubs- skin parthenogenesis just seemed more palatable than "you lay an egg".  I got the inspiration from the insect butcheries that show developmental chambers on the backs or sides of mutant arthropods, but again, this is not a necessary part of the feature and can definitely be removed or retooled!

**Comment by SariusSkelrets** [comment]
> The dermatik thing seems pretty nonsensical to me. I already find very weird that the larvae that were laid into you to use you as food suddenly follow you like if they were duklings

For me, it made sense in a way: if the offspring are friendly to the host, they might get additional food and protection from the host after growing out of it

Seeing the posts on reddit, it looks like it works quite well while bringing its own nightmare fuel in the form of a potential willing host

**Comment by Mikenyes** [comment]
@Ramza13 I've completed the EOC based redo, would love if you took a look at it!

**Pull request closed without merging**
