### PR TITLE
Fixed segfault from pressing enter on an empty bionics tab.

### PR DESCRIPTION
**Pull request by DanmakuDan**
Missed a size = 0 check for #11641.

### CODE REVIEW

**Comment by DanmakuDan** [comment]
(Didn't see this was already being worked on.)

**Comment by sparr** [comment]
meh, yours might be better than mine, I'll let KA101 decide.

**Comment by KA101** [comment]
This one looks simpler, so if it works I'd prefer it.

**Comment by KA101** [comment]
This made my cyberjunkie testchar unable to switch to the passive tab , so far as I can tell.  But it's 5:20 AM here.  In any event, not comfortable merging this right now, sorry.

**Comment by DanmakuDan** [comment]
Is it possible to recheck this? I can't replicate the issue you're having, unless your keybindings didn't pick up the change from the menu interface somehow.

**Comment by sparr** [comment]
I'm with Dan on this one. I cannot fathom how his patch would produce the behavior you're seeing.

**Comment by KA101** [comment]
>But it's 5:20 AM here.

No need to dogpile, thank you very much.

**Pull request merged**
