### PR TITLE
Rework nailguns

### PR DESCRIPTION
**Pull request by mugling**
Many of the improvised weapons are currently bugged due to changes in the reloading code adding a heavy time penalty. Few reports of this have been received (#16788) which shows how underused some of those items are.

This PR reworks the nailgun/nail rifle. The former remains a terrible weapon whilst the latter is marginally improved by adding the ability to use crafted magazines. It is silent and has no recoil but very poor range and is unreliable. Tiny steel bolts become more effective to offset the fact they require significant metalworking supplies to produce.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Can VENOM be applied via nailgun? That would increase its usefulness.

**Comment by Rivet-the-Zombie** [comment]
>Can VENOM be applied via nailgun?

What would keep it from coming off the nail when it was fired?

**Comment by BorkBorkGoesTheCode** [comment]
https://en.wikipedia.org/wiki/Georgi_Markov#Assassination

**Comment by BorkBorkGoesTheCode** [comment]
Poison nails could be an extremely rare drop.

**Comment by Rivet-the-Zombie** [comment]
The Markov assassination doesn't apply here. A tiny ricin filled capsule was used in that case, not poison smeared on the surface of a nail.

**Comment by BorkBorkGoesTheCode** [comment]
To clarify, the venom would be placed in small holes drilled either in the side or the tip of the nail, with the sugar seal applied over the hole(s).

**Comment by illi-kun** [comment]
For me, it's too complex/specific explanation and also weird components/tools are required in case of crafting.

**Pull request merged**
