### PR TITLE
Body part jsonization: part 2

### PR DESCRIPTION
**Pull request by Coolthulhu**
There is one very minor gameplay change:
* Removed the modification to hit chances for being prone. They were minor, incredibly rare and posed a problem here. They should be reimplemented properly, by allowing all effects to change part sizes, not hard-hacked like they were.

Two big purely technical changes here:
* Body parts get their `generic_factory`
* Body part "sets" are contained in an `anatomy` class, which takes care of "pick random body part out of set"

Currently anatomies are immutable (they have ids and so are unique). Not sure if this is the right approach - once everyone starts mutating, mutable anatomies will be required.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Need help with that clang error message. Clang doesn't want to hash enums?

**Comment by codemime** [comment]
You could replace `unordered_map` with `map` as a workaround. I suppose it won't hurt the performance (actually, maybe even improve it because of the tiny number of items), and would save an (also tiny) bit of memory.

**Comment by BrettDong** [comment]
Maybe you need to explicitly define a hash generator function for `enum body_part` yourself like this:
```C++
struct body_part_hasher
{
    std::size_t operator() ( const body_part &bp ) const
    {
        return static_cast<std::size_t>( bp );
    }
};

static const std::unordered_map<body_part, bodypart_ids, body_part_hasher> body_parts;
```

**Comment by Coolthulhu** [comment]
Changed `unordered_map` to `vector`, since all keys are integers from one contiguous range.

**Comment by codemime** [comment]
Does the `long-term` label mean the PR isn't yet meant to be merged?

**Comment by Coolthulhu** [comment]
It was supposed to mean that back then when we were rushing for stable.
But it looks like the rush died down as 3 of the remaining 19 issues are actually feature requests, plus some of the PRs merged after applying the label were significantly more destabilizing (and I don't mean crashes) than any and all of those non-WiP with the label.

**Comment by Coolthulhu** [comment]
Honestly it doesn't really make sense to let this sit and bitrot.
It doesn't affect the game functionality in any way, just sets it up for further changes.
It doesn't change the interface used by legacy functions either.

**Comment by Coolthulhu** [comment]
Had to decrease precision in one of the tests, from `1%` to `1.5%`, because tiny changes (using standard `weighted_float_list` instead of custom implementation of it) combined with RNG caused one test case to get slightly out of line on Windows (and Windows only).

**Pull request merged**
