### PR TITLE
Document power_draw

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Document the newer tool parameter that specifies power draw.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Would it be relevant here to mention that tool that uses `power_draw` have some randomness in they power consumption?

**Comment by kevingranade** [comment]
I don't think so, that's an implementation detail, and the kind of detail we really prefer to hide.

**Comment by kevingranade** [comment]
For example, I'm looking at this and thinking we might want to stash a number that says how many turns to wait until the next discharge event instead of rolling it randomly every turn.

**Comment by jbytheway** [comment]
Would be nice if this allowed use of a string with proper units, rather than a number in unclear units, but I appreciate you were only trying to document it here.

**Pull request merged**
