### PR TITLE
Test case: NPCs prefer to use guns

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Infrastructure "Test case: NPCs prefer to use guns"

#### Purpose of change
* #38609

Maybe closes, maybe not

#### Describe the solution
Make the test, make sure they actually try to use the guns

#### Describe alternatives you've considered
I have tried nothing else, and I am all out of ideas

#### Testing
image

### CODE REVIEW

**Comment by wwkk222208** [comment]
I believe I have solved this issue in #72222

**Comment by wwkk222208** [comment]
Before that，NPC do not use ranged weapons because the value rating of melee weapons is very high. Balancing and correcting the rating formula seems to be a tricky problem. I temporarily adopted a rough approach, allowing the NPCs to give priority to using ranged weapons.
Currently in the game, NPCs sometimes do not use ranged weapons either, because when the enemy approaches, the NPC's process of reloading bullets may be interrupted. Having no bullets will result in the value rating of the gun becoming 0. And if the NPC misses the time point when the magazine is just emptied, they will wait until it is in a relatively safe position to reload. This might be improved, but there are no major issues for now.

**Comment by RenechCDDA** [comment]
> I believe I have solved this issue in #72222

It looks like you improved the calculation, but these tests are to make sure that the behavior *stays* improved. If future changes accidentally reintroduce the issue, the tests should properly warn (by failing).

In addition, I made a change to the visitable check which allows all of their inventory to be checked as weapons, instead of only some. This is in itself a pretty important change, IMO.

**Comment by Maleclypse** [comment]
Tests to keep things fixed always make me happy!

**Pull request merged**
