### PR TITLE
Hit from the zombie can make your clothing filthy

### PR DESCRIPTION
**Pull request by Night-Pryanik**
It's 10 percent now, but could be more or less if needed.

### CODE REVIEW

**Comment by kevingranade** [comment]
I could maybe see some specific special attack doing this, but what's the
rationale for a simple hit from a zombie totally soaking an article of
clothing?

**Comment by Coolthulhu** [comment]
Regular hits shouldn't turn the whole clothing dirty. It's just a punch, not a hug from a slime-covered slug.

Bile applications would make more sense.
Also, 10% for all items regardless of stats? Same chance for underwear, hazmat gear (which is very good at keeping filth on the outside separated from one on the inside), wrist watch etc.

Then finally, are you sure that incredibly common re-application of filthiness that the player can't defend against is not too much even for people who want some clothing cleaning?

Technical:
* You shouldn't check zombie type per item, but outside the loop.
* Fungals also produce filthy items. You should make it a flag instead of checking type every time.
* The message should mention which article of clothing got filthy.

**Comment by DangerNoodle** [comment]
Please no.

**Comment by Night-Pryanik** [comment]
Ok, then maybe apply it when you are grabbed by the zed?

**Comment by Night-Pryanik** [comment]
> Please no.

And I say "Please yes". 
What's in particular you don't like? In any case, you can always disable filthy clothing mod.

**Comment by Night-Pryanik** [comment]
> the player can't defend against

Training dodge for melee, using ranged weapon, no?

**Comment by Zireael07** [comment]
Simple hit is a bad idea.

Specials, on the other hand...
Some candidates:
* boomer bile
* shocker acid
* bites (as opposed to normal hits? I believe they are somehow special?)

**Comment by mutt3x** [comment]
Maybe a new Z monster that specificly does this more often.

>Ok, then maybe apply it when you are grabbed by the zed?

Im okey with this suggestion.

**Comment by pisskop** [comment]
ten percent is outrageous, considering the frequency with which you can expect mid-late game raid combat to occur.

1% is a better start point for tediums sake, and fractional percentiles are probably better.

**Comment by tinukedaya** [comment]
I would agree with the grab having a little chance of making your clothes filthy as well as some of the special attacks as already mentioned... Normal attacks on the other hand nope!
Maybe if your clothes are getting ripped, then there might be a chance of them getting filthy as well?

**Comment by DangerNoodle** [comment]
> And I say "Please yes".
> What's in particular you don't like? In any case, you can always disable filthy clothing mod.

I am unsure if the feature will actually be disabled correctly if the Filthy Clothing mod is disabled.

We already have clothing showing up as filthy even without the mod enabled, even if allegedly the actual effects of dirty clothing are disabled in that case.

**Comment by kevingranade** [comment]
You have to remember, becoming filthy means the article of clothing is
completely covered AND embedded* in the material.

Strikes wouldn't cause this at all, grabs are a bit questionable IMO.
Bites also make little sense.  I'd only expect bile explosion or puke
attacks to achieve it at close range.
What I'd actually like to see is a grab followed up by a vomit attack that
only causes filthiness.  This gives players one more reason to avoid grabs,
and avoid monsters that do that attack.

*This reminds me, some materials should be filth proof or filth resistant.
Metal and some plastics are the most likely candidates, though if it's
metal/cloth it's going to not matter.

**Comment by Nioca** [comment]
Echoing what's been said above, this only really makes sense if it's part of an attack that could reasonably bestow a sufficient level of filth. In my own opinion, the only thing that could really accomplish that is a boomer's bile-spewing attack, or a special zombie with its own filth-causing attack (perhaps a decayed or boomer upgrade).  However, I also want to bring up that this could cause a rather problematic interaction with Squeamish. That trait prevents you from wearing clothing that's filthy, and if it's now going to be possible for clothes to get filthy _while_ worn, it'll need to be addressed; it won't make sense for clothing already worn to be acceptable by the trait's standards, but at the same time, "filthy" attacks shouldn't strip a Squeamish player of clothing automatically. First thought in my head to answer would be to increase the morale penalty and maybe add a secondary status effect which emphasizes the duress being clad in such clothing is putting the character under.

(Although, stray thought here: this might be a niche for, say, a Sewer Zombie or Sewer Monster. Traveling through sewage or toxic waste might get clothing filthy, and a monster based in such an area might also be able to bestow such an ailment)

**Comment by kolsurma** [comment]
>This reminds me, some materials should be filth proof or filth resistant.
Metal and some plastics are the most likely candidates, though if it's
metal/cloth it's going to not matter

Hm, I don't think anything should be completely filth proof, even the most resistant of clothing will still get dirty on the outside. Regardless of the material if it gets forced into the body it should still cause infection. 

I imagine filthiness as more of a sliding scale than a yes/no, this would also allow an 'armor value' against dirty attacks reducing the amount of grime/gore that sticks to the clothing.

**Comment by pisskop** [comment]
filth is a cumulative effect.

thinking in terms of single attacks is like thinking a ripped shirt means it is destroyed.

an item should become filthy in degrees as gore, vomit, poison, dirt, and other gibbies splatter across it

**Pull request closed without merging**
