### PR TITLE
obsolete bio_furnace

### LINKED ISSUE #23262: Drinking clean water consumes container when internal furnace is active
Game version:
0.C-26851-g935cea8

Operating system:
Ubuntu 16.04.3 via Linux Subsystem for Windows

Tiles or curses:
curses

Mods active:
DDA
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Vehicle Additions Pack

### Expected behavior
When a player consumes the last charge of a drink/food item in their inventory, the container is not consumed by internal furnace if internal furnace is on.

### Actual behavior
Containers are consumed by internal furnace upon consuming the last charge of their contents and no message is displayed to indicate it was consumed or any power units were gained.

### Steps to reproduce the behavior
1. Install internal furnace CBM or start with player that has it
2. Spawn a bottle of clean water from debug menu
3. Make sure internal furnace CBM is active
4. Drink both charges of the water
5. Plastic bottle is now gone with no indication that it was actually consumed by furnace or any power was gained
6. Repeat with internal furnace off to see that the bottle is not consumed when not active

Also this is unrelated, but does anyone else think the internal furnace message is odd? It says that you "digest" the item, but really you should be "burning" it or something - unless you are actually eating it, but that would be really inefficient, unsatisfying, and in the case of eating filthy items, gross.

I think I'm gonna make small mod that adds calculators to the game to consume by the furnace - it will have the description "It's a calculator. You can eat it to gain its power." And you will be able to eat it without the furnace on, but you will get the message "Uh oh, the calculator is lodged in your colon!" and take torso damage. Maybe I will also change the internal furnace so that when you eat the calculator, it says "Sweet quadratics of fiery mathematics! You recharge X energy!"

### LINKED ISSUE #29522: Internal Furnace CBM bug with consuming tools that have batteries.
**Describe the bug**  
The Internal Furnace CBM consumes only a variable amount of battery charges (3 in cordless drill, 30 in cellphone, 6 in handheld game system etc) and does not consume the tool, but gives bionic power as if the whole tool is consumed and extra for some reason (up to 60% more I think). For example: "Cordless drill 300/300 consumed by Internal Furnace CBM, player recieves 300+ bionic power, item changes to Cordless Drill 297/300. Player can proceed to consume the drill a hundred times for roughly 30000 bionic power."

**To Reproduce**  
1. Make a player with Internal Furnace CBM, give them a cordless drill item with full charge (300/300).
2. Try to consume the cordless drill item.
3. Player gains bionic power as if consumed whole drill (300+), drill loses only 3 points of batteries and remains intact (297/300). Player can continue to consume the drill a hundred times.

**Expected behavior**  
The drill (or any consumable with charges) should be consumed and the batteries should be destroyed/unloaded after the first time, as the batteries themselves ARE NOT consumable by Internal Furnace.

**Screenshots**  
1. I consume phone with 120 charges
2. Phone doesn't disappear, gives a lot of power (comparatively)
3. Lastly I unload the phone and consume it without batteries (notice the low power gain):
4. Phone disappears.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1706-g7023fc4
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, filthy clothing, aftershock, craftable gun pack, safe autodoc, bright nights, bens gf recipes, deadleaves' fictional guns, extended realistic guns, garden pots, icecoon's arsenal, makeshift items mod, medieval and historic content, modular turret, salvaged robots, dinomod, more survival tools, alternative map key, mutant npcs, more locations, fuji's more buildings, urban development, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, arcana and magic items, artyom's gun emporium - reloaded, classes and scenarios mod, classig roguelike classes, prevent zombie revivification, sleep deprivation, statsthroughskills, extended_buildings, mythical martial arts, pks rebalancing, beta national guard camp, mapgen demo, no survivor armor no acid zombies, manual bionic installation.

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
```SUMMARY: Content "Obsolete internal furnace CBM"```

#### Purpose of change
The internal furnace is comically impractical and the bionics system is moving away from such per #28273.
Closes #23262
Closes #29522 

#### Describe the solution
Remove internal furnace from drop lists and professions. Currently existing furnaces will continue to function but no new ones can be acquired. All furnace functionality and references to it should be removed at the next compatibility break.

#### Describe alternatives you've considered
bio_furnace could be moved to crazy cataclysm.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Oh, what a great shitstorm, caused by this change, awaits us.

**Comment by HKMist** [comment]
It is really necessary to obsolete Internal Furnace?

Aside from the rebalance discussion on #28273, which don't have solid plan on how to implement the change, the removal of the system itself is not very clear. Comically impractical don't seem much a explanation here. 

If the two bug of #23262 and #29522 is the main reason of this removal, and these bug can't be easily fix. Is some dirty fix like "adding filter to block anything have charge/magazine loaded to be consumable by internal furnace" possible to patch the hole?

**Comment by chaisawlajatang** [comment]
>I guess this fantastic bionic will fit nicely there.

Then almost every bionic is fantastic. Microprocessor, somehow connected with the neurons and helping the brain to... think? somehow? "Industrial-grade intestines and processors". Artificial night generator with very wibbley-wobbley work principle. Metabolic exchange, somehow (how?) transferring energy from the body to the battery (ATP transporter? NADP-related thing? there's no "energy" in the free form in the body). Integrated instruments, not interferring with fine finger and hand movements. And so on.

I'm not a fan of the internal furnace (I actually dislike it), but is this

> is comically impractical

the decent reason to remove it? Seriously.

**Comment by Zireael07** [comment]
Microprocessors and mechanical intestines are plausible extrapolations of current tech. We already have cochlear implants, which are essentially microprocessors connected to your cochlea, and other artificial organs. Internal furnace has no such IRL equivalent.

**Comment by chaisawlajatang** [comment]
Cochlear implant (and the developing technology of 'artificial eyes') sends electrical impulses from the receptor into the brain. It's an infinitely simple device in comparison with a 'thinking processor'.
About artificial organs - artificial heart is just developing tech with a few successful cases of use. There are artificial 'lungs' and 'kidneys', yeah - big hefty stationary machines, so Cataclysm bionic implants are based on VERY extrapolated current tech.

**Comment by nexusmrsep** [comment]
Although I'm not against obsoleting internal furnace, it's one less method to gain power for other CBM systems. This reduces the variety, and thus some thoughts should be given towards potential replacement/ replacements. Some expansion towards battery system perhaps? A CBM with removable accumulators? Or something entirely different. External power storage device, like a solar backpack, but with a rechargable battery pack pluggable to your cable power system. 

Another thought: remaining power generation/ supply CBMs should now be more common to make up for the decreases variety.

**Comment by Zireael07** [comment]
I like your new bionics ideas, @nexusmrsep

**Comment by Night-Pryanik** [comment]
I think Cable Charger bionic should be the "default" power source that advertising agents of bionic companies should be recommending to their customers. All other types (microreactor, metabolic interchange, ethanol burner, and joint torsion rackets) are too invasive, too expensive (in pre-cataclysm prices) and require a lot of complex surgery. Cable Charger on the other way is just a cable with a plug that connects to the power storage - fast and easy to install.

**Comment by Night-Pryanik** [comment]
> Then almost every bionic is fantastic.

If it's purely fantastic (not "entirely physically possible or plausible, just in the future"), then we should rework the offending bionic or remove it altogether if it's not reworkable. We removed unrealistic bionics in the past, I don't see why can't we do it again.

**Comment by HKMist** [comment]
I don't think internal furnace is a well balance thing too but I don't want to discuss about realism/balance since i don't want to get warning of off topic again. 

My doubt on this PR is the PR don't provide enough information on why ymber choose to obsolete internal furnace at this timing. Use #28273 as a reason is too weak since the whole discussion is around how to redesign the cbm system as a whole and don't touch much on individual cbm. And base on #23262 and #29522 is also weak since both are not game breaking(well,#29522 is balance breaking though) and seem somehow fixable, it seem a waste to choose remove instead of fixing/improve the whole infrastructure of internal furnace's code at this state.

And if the decision is base on realism/balance, it is too early to move into this step. Remove something may only need a day but making replacement can take months. It is always better to open discuss on how to balancing it or replace it with something first on removing content.

And I think if it really need to move, Aftershock seem more suitable. Crazy cataclysm is just too crazy for internal furnace.

**Comment by Rail-Runner** [comment]
Maybe pull it out into a mod, at least?

**Comment by kevingranade** [comment]
Feel free to add to a mod that doesn't care how ridiculous it is.

**Comment by Ilysen** [comment]
Was made aware of this through Discourse. I don't care enough to do it myself, but if someone wanted to put this into Aftershock, a whole lot of people would appreciate whoever did it.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/tips-tricks-and-newb-questions-reborn/16870/736

**Pull request merged**
