### PR TITLE
Obsolete guns that didn't exist enough or made sense enough 

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove some guns"

#### Purpose of change
Some pipe rifles (32, 380, 45 ACP, 9x19/18, 40 S&W) have no or little to no rim to work in a pipe rifle. Big Horn Model 89 and Lemat revolver don't exist in enough numbers, and the homemade lever action shotgun seems a bit too complex for a homemade job. 

#### Describe the solution
Obsoletes the items and removes them from the game. Also fixed a BFG-50 item group. 

#### Describe alternatives you've considered

Change the homemade lever action shotgun to a Winchester 1901 but the issue is those are also very rare. 

#### Testing
Tested locally, works fine. Nested BFG group works now too.

### CODE REVIEW

**Review by TheShadowFerret — APPROVED** [review]
I would have turned the .45 ACP pipe rifle into .45 Colt, but the obsoletions make sense.

**Comment by Holli-Git** [comment]
> I would have turned the .45 ACP pipe rifle into .45 Colt, but the obsoletions make sense.

I probably should've done that, I'll add it in on another gun-related PR

**Comment by Kantonine** [comment]
While i can understand the possibility of some of the pipe rifles being obsoleted due to concerns regarding their cartridges being unable to be chambered, I don't think its a reasonable assumption to obsolete the homemade lever action shotgun. we can already make handmade revolvers, and i dont think its a massive jump to assume one couldnt make a (working, albeit poorly designed) lever action shotgun when its possible to make a revolver guns chambered in .40, .45, and 12 gauge. I would rather suggest that they get reworked into other designs, and in the case of the pipe rifles, other gun types take their place

**Comment by Maddremor** [comment]
> While i can understand the possibility of some of the pipe rifles being obsoleted due to concerns regarding their cartridges being unable to be chambered, I don't think its a reasonable assumption to obsolete the homemade lever action shotgun. we can already make handmade revolvers, and i dont think its a massive jump to assume one couldnt make a (working, albeit poorly designed) lever action shotgun when its possible to make a revolver guns chambered in .40, .45, and 12 gauge. I would rather suggest that they get reworked into other designs, and in the case of the pipe rifles, other gun types take their place

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#player-can-craft-a-x-so-they-should-also-be-able-to-craft-a-y

**Comment by Kantonine** [comment]
> > While i can understand the possibility of some of the pipe rifles being obsoleted due to concerns regarding their cartridges being unable to be chambered, I don't think its a reasonable assumption to obsolete the homemade lever action shotgun. we can already make handmade revolvers, and i dont think its a massive jump to assume one couldnt make a (working, albeit poorly designed) lever action shotgun when its possible to make a revolver guns chambered in .40, .45, and 12 gauge. I would rather suggest that they get reworked into other designs, and in the case of the pipe rifles, other gun types take their place
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#player-can-craft-a-x-so-they-should-also-be-able-to-craft-a-y

Fair play to bring that up, but i think there is a _big_ difference between what im suggesting, and something even remotely resembling factory made firearms and other items in general, if we take that premise into account:
No crafting of _any_ electrical appliances outside of lights
No makeshift steam engine
No Luty at all
No handmade revolvers or revolver shotguns
No crafting recipe for suppressors and automatic sears outside of the drop in sear and lightning links
No Coilgun, Electrified Fencing Swords, Quarterstaff, and Removal of the crafting recipe for the taser tonfa (granted, i already have my own issues with it)
No Combat chainsaws
No Electric Carver crafting recipe
Everything in the Survivor line is out of the question, especially boots and masks as you cant ensure actual protection
The craftable flintlock rifles would have to be made to be _much_ worse than normal flintlock guns as, lets be honest here, we arent using precision tools

**Comment by Kantonine** [comment]
Meanwhile, i can find examples of designs that imho, wouldnt be farfetched at all

**Comment by Holli-Git** [comment]
> Fair play to bring that up, but i think there is a _big_ difference between what im suggesting, and something even remotely resembling factory made firearms and other items in general, if we take that premise into account: No crafting of _any_ electrical appliances outside of lights No makeshift steam engine No Luty at all No handmade revolvers or revolver shotguns No crafting recipe for suppressors and automatic sears outside of the drop in sear and lightning links No Coilgun, Electrified Fencing Swords, Quarterstaff, and Removal of the crafting recipe for the taser tonfa (granted, i already have my own issues with it) No Combat chainsaws No Electric Carver crafting recipe Everything in the Survivor line is out of the question, especially boots and masks as you cant ensure actual protection The craftable flintlock rifles would have to be made to be _much_ worse than normal flintlock guns as, lets be honest here, we arent using precision tools

The handmade lever action shotgun doesn't even have a crafting recipe to begin with, it's just some random gunsmithing project. And for your other argument, that's a huge leap of logic. The existence of recipes for some items doesn't somehow negate any and all issues with a completely different item. Also, the .40 and .45 revolvers are going to get obsoleted too, as being rimless without a moonclip (which you arent machining) they'd just get pushed down the barrel once the hammer strikes them.

**Comment by Kantonine** [comment]
> Also, the .40 and .45 revolvers are going to get obsoleted too, as being rimless without a moonclip (which you arent machining) they'd just get pushed down the barrel once the hammer strikes them.

Yeah, i can understand that, but why not change it so that theyre revolver friendly, like .38? Fully up for obsoleting stuff that cant make sense, like the pipe rifles you mentioned, but id rather change stuff rather than full obsoletion

**Comment by Holli-Git** [comment]
> Yeah, i can understand that, but why not change it so that theyre revolver friendly, like .38? Fully up for obsoleting stuff that cant make sense, like the pipe rifles you mentioned, but id rather change stuff rather than full obsoletion

Does anyone actually use the 2-shot special? Why would someone bother spending even more time and more skills making a .38 revolver?

**Comment by kevingranade** [comment]
> Meanwhile, i can find examples of gun designs that imho, wouldnt be farfetched at all, and still remain balanced

Find and present actual evidence if you have it, so far you haven't said anything convincing. 

*You* might have a bias against obsoletion, but the project doesn't. It's on you to find alternatives instead of just insisting they happen.

**Comment by Kantonine** [comment]
> > Meanwhile, i can find examples of gun designs that imho, wouldnt be farfetched at all, and still remain balanced
> 
> Find and present actual evidence if you have it, so far you haven't said anything convincing.
> 
> _You_ might have a bias against obsoletion, but the project doesn't. It's on you to find alternatives instead of just insisting they happen.

Yeah, hold on, letme grab my sources, sorry

**Comment by Kantonine** [comment]
https://www.youtube.com/watch?v=opLOeQCQQjg
https://www.youtube.com/watch?v=2W_Q4x9Vv94
https://www.youtube.com/watch?v=6vTMmUBtgp4
https://www.youtube.com/watch?v=KTZWW3Q21NU&t=297s
https://www.youtube.com/watch?v=RPPxp4KNZ3o
https://www.youtube.com/shorts/z-MnrLmk1ks
https://www.youtube.com/shorts/Lx9BEESG-V4
https://www.youtube.com/watch?v=gtLYnqZQHCY
https://www.youtube.com/watch?v=DAkDjM1TgPw
https://www.youtube.com/watch?v=6skP61TXU14

**Comment by Holli-Git** [comment]
> https://www.youtube.com/watch?v=opLOeQCQQjg https://www.youtube.com/watch?v=2W_Q4x9Vv94 https://www.youtube.com/watch?v=6vTMmUBtgp4 https://www.youtube.com/watch?v=KTZWW3Q21NU&t=297s https://www.youtube.com/watch?v=RPPxp4KNZ3o https://www.youtube.com/shorts/z-MnrLmk1ks https://www.youtube.com/shorts/Lx9BEESG-V4 https://www.youtube.com/watch?v=gtLYnqZQHCY https://www.youtube.com/watch?v=DAkDjM1TgPw https://www.youtube.com/watch?v=6skP61TXU14

None of those are lever actions, or revolvers with rimless cartridges.

**Comment by Kantonine** [comment]
> > https://www.youtube.com/watch?v=opLOeQCQQjg https://www.youtube.com/watch?v=2W_Q4x9Vv94 https://www.youtube.com/watch?v=6vTMmUBtgp4 https://www.youtube.com/watch?v=KTZWW3Q21NU&t=297s https://www.youtube.com/watch?v=RPPxp4KNZ3o https://www.youtube.com/shorts/z-MnrLmk1ks https://www.youtube.com/shorts/Lx9BEESG-V4 https://www.youtube.com/watch?v=gtLYnqZQHCY https://www.youtube.com/watch?v=DAkDjM1TgPw https://www.youtube.com/watch?v=6skP61TXU14
> 
> None of those are lever actions, or revolvers with rimless cartridges.

Sure, and after looking at it, i _have_ conceded on that, and more so my point was to atleast change them to be reasonable

**Comment by Holli-Git** [comment]
> Sure, and after looking at it, i _have_ conceded on that, and more so my point was to atleast change them to be reasonable

Change what to be better? The pipeguns? Because that 9mm rifle had very much not homemade parts

**Comment by Maddremor** [comment]
> > > https://www.youtube.com/watch?v=opLOeQCQQjg https://www.youtube.com/watch?v=2W_Q4x9Vv94 https://www.youtube.com/watch?v=6vTMmUBtgp4 https://www.youtube.com/watch?v=KTZWW3Q21NU&t=297s https://www.youtube.com/watch?v=RPPxp4KNZ3o https://www.youtube.com/shorts/z-MnrLmk1ks https://www.youtube.com/shorts/Lx9BEESG-V4 https://www.youtube.com/watch?v=gtLYnqZQHCY https://www.youtube.com/watch?v=DAkDjM1TgPw https://www.youtube.com/watch?v=6skP61TXU14
> > 
> > 
> > None of those are lever actions, or revolvers with rimless cartridges.
> 
> Sure, and after looking at it, i _have_ conceded on that, and more so my point was to atleast change them to be reasonable

If you have new firearms you feel suitable for inclusion you are welcome to open up a PR for those, but there is no rule that you have to add something in to offset an item being obsoleted. Furthermore, posting no-context YouTube links is not very digestible.

**Comment by Kantonine** [comment]
> > > > https://www.youtube.com/watch?v=opLOeQCQQjg https://www.youtube.com/watch?v=2W_Q4x9Vv94 https://www.youtube.com/watch?v=6vTMmUBtgp4 https://www.youtube.com/watch?v=KTZWW3Q21NU&t=297s https://www.youtube.com/watch?v=RPPxp4KNZ3o https://www.youtube.com/shorts/z-MnrLmk1ks https://www.youtube.com/shorts/Lx9BEESG-V4 https://www.youtube.com/watch?v=gtLYnqZQHCY https://www.youtube.com/watch?v=DAkDjM1TgPw https://www.youtube.com/watch?v=6skP61TXU14
> > > 
> > > 
> > > None of those are lever actions, or revolvers with rimless cartridges.
> > 
> > 
> > Sure, and after looking at it, i _have_ conceded on that, and more so my point was to atleast change them to be reasonable
> 
> If you have new firearms you feel suitable for inclusion you are welcome to open up a PR for those, but there is no rule that you have to add something in to offset an item being obsoleted. Furthermore, posting no-context YouTube links is not very digestible.

I'll keep that in mind for future reference, and i will let this PR be, was only stating my case, thank you all for the insight anyways

**Comment by John-Candlebury** [comment]
Can I suggest adding the lemat to the Void Weaver Minor Loot pool?

Mostly due to the fact that while I dont think they are common enought to have them spawn normally they are one of a handfull of actually mechanically interesting pistols the game has.

**Comment by Holli-Git** [comment]
> Can I suggest adding the lemat to the Void Weaver Minor Loot pool?
> 
> Mostly due to the fact that while I dont think they are common enought to have them spawn normally they are one of a handfull of actually mechanically interesting pistols the game has.

I don't want to have the void weaver loot pool as "Anything that doesn't fit in the game", it'd feel weird and I'd imagine it would become an argument pretty soon for anything removed at all.

**Comment by John-Candlebury** [comment]
Theres not an excess of minor loot variants that spawn there yet(repeats can still happen atm), theres plenty of time-displaced objects in the limited lootpool and the Lemat isnt just random stuff but a gun with actual unique gameplay mechanics. 

I wouldnt be advocating for people to shove the Weaver full of lame reject stuff.

**Comment by kevingranade** [comment]
The Lamat isn't just time displaced,  there were never large numbers of them. The quick estimate I found said less than 3,000 were ever made.

**Comment by Kantonine** [comment]
Maybe add it as a custom order from the Artisans? We already have the Pressin in-game, which is already rare too, and its available from them, They should be reasonably able to make a reproduction, maybe have a quest for it?

**Comment by KnifeFightBears** [comment]
Why obsolete the Model 89? It's a commercially produced rifle made by a company that is in business today. You can order one online from the manufacturer directly.

edit: I was curious so I went searching and you can _literally buy these at Bass Pro_, if I can walk into a gun store and buy it over the counter it seems like a fair inclusion in the game

**Comment by kevingranade** [comment]
If you mean this listing https://www.basspro.com/shop/en/101554176 is not over the counter,  it's a used gun brokering service,  so all of bass pro shops has one (1) of them for sale.

Here's the guidelines for gun inclusion https://github.com/CleverRaven/Cataclysm-DDA/blob/313810083d7ef27d02f44aee8d9a70d032193ae5/doc/GUN_NAMING_AND_INCLUSION.md?plain=1#L82

I just checked again and this gun is practically nonexistent.

**Review by kevingranade — APPROVED** [review]
I had to stop and think about the removal of shot paper rounds,  but clearly there's no interest in utilizing it since they've been in for quite a long time without any more additions that use them.
Resolved a tiny conflict,  should be good to go after a rebuild.

**Pull request merged**
