### PR TITLE
Chest hole 2, Electric Boogaloo

### PR DESCRIPTION
**Pull request by Chezzo**
This is a pull request for an update to the ChestHole tileset. It also makes ChestHole tileset the default tileset for new installations.

### CODE REVIEW

**Comment by Chezzo** [comment]
This is current! It's got sharp rocks (Thanks to whoever did those, I was asking for more rocks and that is perfect.) and reclining seats. 

Noticed music shops, which is good because I already made an electric guitar and drums. But not totally done.

**Comment by Chezzo** [comment]
Wait, didn't push the reclining seats. Gimme a minute.

**Comment by Chezzo** [comment]
Okay, is good now. Ready to be pulled.

**Comment by KA101** [comment]
> It also makes ChestHole tileset the default tileset for new installations.

Little greedy there, though I shan't fault you.  Hoder hasn't been updating.

**Pull request merged**
