### PR TITLE
Limit shot targets to the reality bubble

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary
Bugfixes "Limit shot targets to the reality bubble"

#### Purpose of change
fixes an out of boubds map dereference

#### Describe the solution
Clamps the randomized target miss coordinates to fit the reality bubble.

#### Describe alternatives you've considered
Disabling strict memory checks for cataclysm and enjoying silent game state corruptions like 99.9% of players do.

#### Testing
Used the repro at the bug report.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Are you really solving the same problem the the bug reports (and which doesn't specify any reproduction that you can reference in your testing section...)?

You may be solving YOUR problem mentioned in the comments of that bug report, but de-referencing a null pointer for some kind of effect seems like a different issue from targeting an out of bounds location.

I'm not saying this doesn't need fixing, and I haven't looked into your correction (which sounds reasonable from the description), only that I don't think it's actually fixing that bug report's stated problem.

**Comment by l29ah** [comment]
> de-referencing a null pointer for some kind of effect
What? The report doesn't mention any null pointers.

I'm 95% sure it's the same bug.

**Comment by PatrikLundell** [comment]
"dmg_by_type is empty for chemical thrower, and de-referencing max_element causes out-of-bound read." after the code that iterates over an empty container trying to get ->first from the empty results sounds like a null pointer to me.

There's also "Error: attempt to dereference a past-the-end iterator." from the game's report as well (which doesn't mention null explicitly).

I'm following the link of the bug report posted, so it's possible the link refers to the wrong bug report.

**Comment by kevingranade** [comment]
It's definitely a different crash, but it's also definitely a crash, so thanks for that.

**Pull request merged**
