### PR TITLE
Electrical insulation for gear

### LINKED ISSUE #53772: New electricity damage is excessive
### Describe the bug

#53135 made some interesting changes to electricity, and therefore Shockers and their ilk, but the result is a bit too much. One shock often deals 30-40 damage and a load of Pain, and seems to follow you as you try to run away. Worse, if there's a husk or a trigger-happy shocker inside a room you can't see into, it'll charge up the walls, and when you get close, you'll take one of those massive bursts and be instantly crippled.

This is particularly egregious in the TCL after one or two months, because the high number of technicians that spawn means that after a few half-lives, the place is absolutely crawling with shockers.

### Steps to reproduce

1. Approach a room containing a shocker
2. Get zapped to hell and back

### Expected behavior

Would prefer if the game didn't punish you by taking off half your health and putting you in crippling pain just for walking up to a door.

### Screenshots

image
Before getting shocked.

image
After having had the audacity to walk up to a wall.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 579f907 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

They seem a lot less dangerous in open spaces, where their blasts mostly just dissipate, but it's difficult to engineer that kind o scenario, especially if you don't already know there's a shocker behind that door.

### LINKED ISSUE #53819: Cannot use tailor's kit to modify clothes with leather, fur, or wool when more than 1 item required
### Describe the bug

You cannot modify clothing using the tailor's kit with leather, fur, or wool if it requires more than 1 leather patch, fur pelt, or felt patch respectively. It appears that the materials for these modifications are not properly discovered as available when multiple are required. The tailor's kit UI will display the options for these modifications as unselectable with a message like `Can't pad with leather (need x leather patches)` regardless of available resources. However, it is possible to modify clothing pieces which require only 1 of those resource. The steel plate and layered kevlar sheet modifications are available as expected when the resources are available. 

### Steps to reproduce

1. Create a character with a gambeson, pair of ankle socks, tailor's kit, 5 leather patches, 5 steel plates, 5 layered kevlar sheets, 5 fur pelts, and 5 felt patches.
2. Raise the character's skills to 10 (I don't know if this is necessary)
3. Apply the tailor's kit, select the modify clothing option, select the gambeson. This will display the leather, fur, and wool options as unavailable due to lacking resources. The steel plate and kevlar modifications will be available.
4. Apply the tailor's kit, select the modify clothing option, select the ankle socks. This will display the leather, kevlar, fur, and wool modifications as available. The steel plate modification is unavailable due to it being a restricted modification

### Expected behavior

When modifying a piece of clothing using the tailor's kit with leather, fur, or wool and the required amount of materials are available, then the modification should be able to be performed.

### Screenshots

**Inventory with appropriate materials**
image

**Modification UI for gambeson**
image

**Modification UI for ankle socks**
image

### Versions and configuration
Experimental build

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

### Additional context

**Relevant code**: 
Clothing modification definitions: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/clothing_mods.json
Tailoring resource definitions: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/resources/tailoring.json
Tailoring actor code: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L4545

**Stable release testing**
I could not reproduce this bug on the  0.F-2 release. All modification types are available as expected when following the steps outlined above.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Features "Implement electrical insulation for gear"

#### Purpose of change
Follow-up from #53135
Closes #53772
Closes #53819

#### Describe the solution
This PR adds infrastructure for electrical insulation on gear and damage negation/reduction based on electrical insulation.

A quick overview of the new feature:
* Electric damage from fields is now applied to specific bodyparts. Low intensity fields only target feet and legs, while high intensity fields reach more bodyparts. The bodypart selection is weighted to favor feet and legs. Being on the ground (prone, no legs, downed...) makes fields target any bodypart independent of intensity. Full damage will be applied to the bodypart hit while other bodyparts will only take 50%.
* Armor now has an "Electrical insulation" value based on materials/thickness. This value doesn't reduce incoming damage, it only acts as insulation. This means electrical damage works in a binary way. If enough layers are stacked to overcome the attack intensity (damage) the damage is fully prevented. If the bodypart isn't completely insulated the electricity will flow doing full damage (-20% of cumulative insulation value).
* If an attack has multiple damage types, electric insulation from layers penetrated by physical damage is ignored. This means that if a piercing attack goes through armor and has added electric damage, the electric damage will be applied in full.
* Gear pieces can now be padded/lined with rubber chunks to add insulation. The added insulation is always be 0.5 while encumbrance is increased by `3 + 5*coverage`, which means encumbrance on a 100% coverage piece will increase by 8, while a piece with 50% coverage will end up with 5 extra encumbrance.

To get this working I had to change the `absorb_hit()` function a bit. Previously it looped through all damage types for that attack instance and for each of those it went through all layers of armor applying damage reductions. It made more sense to do it the other way: loop through armor layers and for each layer hit apply reductions to each damage type. This also makes it a lot easier to implement damages that bypass layers of armor (i.e. in this case electric damage only starts being reduced when the physical portion is completely reduced, if present) since all you need is a to test it there is any damage instance with physical damage at each layer and set a flag to control if the physical damage is > 0.

Although I didn't make substantial changes to the previous logic, other than inverting the two nested for loops, there are small changes that might impact tests and damage calculations in very specific cases. There aren't many attacks that apply multiple damage types at the same time but for the few that do, previously when a piece of armor was destroyed it was removed instantly, before reducing other damage types using that armor.

This made damage calculations dependent on the order of evaluation of damage types. If you had an attack with cutting, fire and electrical damage, if the physical damage is calculated first and it breaks a piece of armor, the other 2 elemental damages won't be reduced by that layer. If you calculate the elemental damages first and the physical (that breaks the armor) last, then all 3 will be reduced. So it only made sense to make it consistent by applying reductions to all damage types first and then removing the broken piece of armor.

The other minor change that might have an effect on calculations is that previously there was a single coverage roll for all layers of armor, which if I understood the code right, it means that two 20% coverage pieces will cover the same 20% of the bodypart, making it so that 20% of the attacks will hit both layers and 80% of the attacks won't hit any. It's easy to revert back to the previous behavior though.

EDIT: Decided to make rubber padding a whitelist-only mod since it doesn't make sense for most gear (panties, socks, etc). I haven't added it to the valid_mods list of any items yet. I suggest allowing it for outer-layer gear and some boots but I'll leave that out of this PR for now.

Some observations after doing some in-game testing:
- Rubber boots (3 insulation) can save your life if you are caught by a Husk. It won't really help when he gets on top of you and you start getting shocked by intensity 5-10 fields (that can zap bodyparts not covered by boots) or its 6 electric damage hits, but it will be enough to prevent damage from the less intense fields and let you run away to safety without being chain-zapped.
- Rubber padding can be useful for unavoidable fights with shockers/husks. When stacking gear the encumbrance will add up quickly (~12 encumbrance per point of insulation) but it's an affordable way to stack early electric damage resistance.

#### Tasks
- [x] Only count gear after the last layer penetrated by physical damage (if combined damage).
- [x] Implement insulation / percentage reduction based on total insulation from applicable layers.
- [x] Implement rubber padding/lining for additional electrical insulation.
- [x] ~~Implement a simplified version for monsters.~~ In #53736
- [x] ~~Make attacks with conductive weapons / unarmed apply damage to the limbs.~~ Not as straightforward as I hoped, it will be a follow-up PR.
- [x] Tweak material values.
- [x] Test in-game.
- [x] Implement tests.

#### Describe alternatives you've considered
What do you mean? Are you saying I had a choice?

#### Testing
Manually tested a few basic scenarios involving shockers and husks. Basic gear (rubber/turnout boots or layered socks + regular footgear) now easily prevents most/all damage from low intensity fields which helps with #53772. Wearing proper boots makes running away from husks and shockers easy (if you can outrun them) but full body insulation is needed to melee them reliably.

I'll implement some automated tests now and it will be ready for review.

#### Additional context
Rubber padding:
image

### CODE REVIEW

**Comment by Shodan14** [comment]
Maybe rubber should add some acid protection as well?

**Comment by GoLoT** [comment]
Good point. I thought about warmth but didn't add it yet, I'll see if I can come up with sensible values for both.

**Comment by GoLoT** [comment]
I think this is ready for review now. What's left now is a lot of tweaking and balancing work but that requires further playtesting and reports.

**Comment by kevingranade** [comment]
Sorry I didn't get a review in before you put all this work in, but this isn't how electricity works, the lack of mitigation is intentional as you're either going to ground incoming electricity before it reaches your body, or it's going to pass through your body unmitigated. There's no real in-between state where you reduce the intensity.
Padding clothing with insulation in particular is especially pointless as no readily available insulation has higher electrical resistance than air, so if the electricity arced through any meaningful anount of air before reaching you, your padding will be irrelevant.

**Comment by vegarbg** [comment]
By that logic, shocker zombies and electrical clouds shouldn't exist.

**Comment by GoLoT** [comment]
> There's no real in-between state where you reduce the intensity.

There is no reduction in intensity though, other than a 20% reduuction (of the "insulated damage") that I added for balance purposes and can be easily removed by changing a line. If the damage hits a very thick insulating material (all combined layers of armor where it hit) it either goes through (doing full damage) or it doesn't. 

https://github.com/CleverRaven/Cataclysm-DDA/pull/53604/files#diff-35237e419d9c2be993e71dc5f010878c8c6cc3963d28151ef8f2d76979ef9940R521-R525
Simply changing that line to `elem.amount = initial_electric_damage;` should achieve what you said unless I misunderstood.

**Comment by GoLoT** [comment]
@kevingranade I opened a new PR (#54049) to rebalance field damage. The changes to electricity fields from this PR can be reverted while keeping the armor insulation changes strictly for electric damage that comes from physical attacks (monsters with added damage, tasers, plasma that makes contact with the character and so on). Let me know if that works and I'll commit the changes so it can be reopened.

**Pull request closed without merging**
