### PR TITLE
Scent Tracking Zeds

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Balance "What Zombies should track by scent?"

#### Purpose of change
Currently all Zombies are bloodhounds as far as finding people.  So are almost all monsters.  As part of #62681 I'm focusing on one species at a time.  Zombies to start with.

#### Describe the solution
Removed the species wide ability for Zombies to sniff out prey and specifically added it back on zombies that seemed reasonable to have it. 

#### Describe alternatives you've considered
Attracting attention to the issue about this and making it more clear I'm looking for help on this project.  

#### Testing
Night raiding became much safer until I got overconfident and a zombie dog caught my scent.

### CODE REVIEW

**Comment by Venera3** [comment]
I think the shady, screecher and the predator lines definitely need it (+- `KEENNOSE` for some better tracking) either from a functional or a flavor perspective, and I'd add the base level to the evolved brawlers as well mostly for want of a flavor on them. 

Headless/acid/bone/shocky zeds not smelling you is fair enough, and slightly restricting smell should keep single zeds from peeling off and saying Hello 1v1 randomly.

**Comment by Night-Pryanik** [comment]
> specifically added it back on zombies that

That what?

**Comment by SabrinaMori** [comment]
I am playing on stable, but i never had zombies sniff me out, during the night especially i can walk almost past them, do you have strong scent perk or maybe you just encountered `KEENNOSE` special zombies?

**Comment by Maleclypse** [comment]
> I am playing on stable, but i never had zombies sniff me out, during the night especially i can walk almost past them, do you have strong scent perk or maybe you just encountered `KEENNOSE` special zombies?

This is more of a review prompted by comments from Kevin about baseline humans not being able to track by smell.  So my assumption is that non-mutated risen human dead, ferals, and probably most robots shouldn't track by smell.

**Comment by Kribylet** [comment]
Is the accuracy of scent tracking the same across all scent tracking zeds? Could we consider baseline zombies being able to track some extremely high threshold of scent? For example, survivor hiding in a room, next to the door with a baseline zombie on the other side? That could make negatives that affect scent intensity matter some more, maybe.

**Comment by SabrinaMori** [comment]
> This is more of a review prompted by comments from Kevin about baseline humans not being able to track by smell. So my assumption is that non-mutated risen human dead, ferals, and probably most robots shouldn't track by smell.

Oh yeah in that context it does make more sense that zombies just like normal humans shouldn't be able to track their prey using directional smells. I'm not an expert on the game mechanics but i remember smell is based on how long you stayed in the area, so the longer you stay in one spot, the more smell you leave there, and that high amount of smell should be detectable even by normal people.

**Comment by Maleclypse** [comment]
> Is the accuracy of scent tracking the same across all scent tracking zeds? Could we consider baseline zombies being able to track some extremely high threshold of scent? For example, survivor hiding in a room, next to the door with a baseline zombie on the other side? That could make bonuses/maluses that affect scent intensity matter some more, maybe.

There are currently two levels of smell, normal and keen nose.

**Comment by AcidAntOnAMinefield** [comment]
Zombies shouldn't be able to track scent in any way - assuming they made of rotting flesh (as some of them have it in their descriptions), that scent would overpower pretty much everything else. And this is assuming their smelling senses even work to begin with. Plus they also have rotting clothes, or their own "smells" (gas, smoke, murky water, etc) over their "pleasant rotting flesh" aroma.

But if we want to stretch it a bit, I'd probably suggest that the only zombie creatures that should reasonably be allowed to follow scent would be zombie animals and predators. 

Also Headless/Brainless Zombies are still a strange concept given that most of the sensory receptors require a working brain - how can a headless creature even stand to begin with, how can it move with no central coordination to itself (ie "brain") or how can they even track sound? This is a legitimate question, given that the "brainless zombie" (and the "Listener Zombie", which evolves from it) have no brain, *yet* their hearing ability still exists? :thinking:

**Pull request merged**
