### PR TITLE
brought base blueprint recipe names inside their name spaces

### LINKED ISSUE #53065: Canteen faction camp expansion (version 1) does not display most furnishing mission options
### Describe the bug

So, I have a faction camp with a canteen expansion, and despite the fact that it's lacking many of its furnishing options, it seems to be about as done as it's going to get until this problem is fixed. The missions to build furnishings for the pantry and dining hall, as well as the butchery area and the planters, are completely absent from the menu for sending NPCs on missions.

### Steps to reproduce

1. Make a faction camp with a canteen (version 1) expansion
2. Build the expansion up enough that the furnishing options mentioned above should appear
3. Notice that they do not appear

### Expected behavior

I expect to be able to send my NPC followers on missions to furnish the canteen until it is complete, and all recipes are available.

### Screenshots

Furnishing options missing from canteen

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro]
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers],
    Chris K's Knives [ChrisKsKnives],
    Custom Spells [Custom_Spells],
    Reproduction mod [perverts],
    Custom Bionics [custom_bionics],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
    Deconstruction Plus [Deconstruction_plus],
    Core Data Changes [core_data_changes],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Dripbots [dripbots],
    Hard Steel Armor [hardsteel_armor]
]

### Additional context

I looked through my canteen basecamp recipes (which I have not edited) for any sign of anything that would cause this problem, and have found nothing. I already searched through all of the mods I use for anything that might change how the canteen mission recipes work, and the only mod that even mentions basecamps at all in its data is Aftershock, which does not modify the canteen. Also, I have another faction camp set up with the version 2 canteen expansion, and that one doesn't seem to have the same problem.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Fixes #53065

#### Describe the solution

A number of canteen version 2 recipe blueprints retained their original names, causing them to sometimes dominate the original versions and sometime (I presume) the reverse, explaining why there were failure to replicate the issue.

This prompted an investigation of the recipe blueprint names for version 2 expansions, and a number were found not to fall within the "namespace" they ought to use, although I don't think any of those actually clashed.

#### Describe alternatives you've considered

Travel back in time and not screw up in the first place. However, I haven't found any time traveling machine.

#### Testing

A very quick testing consisting of loading the save I made after encountering the issue myself (allowing me to actually eventually figure out what had happened) and verifying that all the constructions that had been AWOL were available.
This isn't a definite proof, as the random recipe loading "logic" could have loaded the recipes in the working order anyway.

#### Additional context

None of the improperly named recipes or their dependents rely on the implicit declaration of the recipe name being available, but instead rely on explicitly allocated tokens that usually were identical to the recipe names, so the actual name technically doesn't matter, as long as it doesn't get superseded by another recipe of the same name. The changed names now match those tokens (and fall within the "namespace" of the expansion).

This bug would not have been present in the original PR submission if the game flagged duplicated recipe names as problematic, rather than silently tossing one of them away (probably overwriting the earlier ones with later ones).

Screenshot (129)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Ironically, removing potentially mismatching requirement specifications from the canteen was what caused me to encounter this bug...

**Comment by hexagonrecursion** [comment]
It looks like you forgot to mention dd046a9ea1708dff6942b1a2208f5d0d8eb781e1 in the PR description.

**Comment by PatrikLundell** [comment]
The reason for the late change is that the automatic processing rejected the PR unless that part was changed, which is what my comment refers to. It's not part of this PR as such, just one of all these things the compilation and checking throws at you because someone merged something else that didn't pass that check (or wasn't subjected to it, as is frequently the case with the RNG based testing). Thus, it's something someone else let into the master.
The complaint was that the stated requirements didn't match the auto generated ones (that could be fixed either through the change made, or by the [in this and most cases] inappropriate change to override the auto generated resource requirements). The irony is that this is exactly what I was trying to address so this situation shouldn't happen (in a PR that hasn't been tested or submitted yet, where the affected file is processed fully, not just the entry the checks found offensive this time).
There are two different reasons for not making a separate PR for the check rejection fix:
1. It cannot be tested, because the issue this PR fixes blocks the ability to test it (for me: the randomness of the problem may make it possible to test for someone else, or for me some other day): I don't know how the JSON data conflict handling (fails to) work.
2. I wanted to get this PR done quickly so those affected by the bug it fixes can actually proceed with their expansion construction, rather than wait for the full cleaning.

**Comment by AmarinReyny** [comment]
Thank you for this. I'm still waiting until I get the spoons needed to commit to updating to the latest experimental and making all the adjustments I'll need to make on my end to get it sort of working, but I was able to copy the changes you made into my own files, and upon testing, it works wonderfully!

**Pull request merged**
