### PR TITLE
Zombie animals don't fear fire

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
Bugfixes "Zombie animals don't fear fire"

#### Purpose of change
It was brought up in the development discord that antlered horrors actually fear fire. Looking into this, it appeared to be true but a huge chunk of zanimals did as well, so there's the fix.

#### Describe the solution
Removed the fear triggers from all zombie animals that had them. This should affect all zombies from the families of moose, cougar, beaver, wolf, bear, pig, bull and tiger.

#### Testing
It's just fear trigger removal, shouldn't cause errors.

### CODE REVIEW

**Comment by NetSysFire** [comment]
Because zombies literally do not have the brains to process fire as a danger anymore. This is also why blackberry bushes are effective fortifications now.

**Comment by GuardianDll** [comment]
Okay. Why zanimals still have brains, when zeds don't?

**Review by ashGlaw — APPROVED** [review]

**Comment by Nebnis** [comment]
I think you misunderstood Netsysfire. zanimals are like zeds, they don't have the cognitive ability to avoid danger anymore. Unless they are some very specific evolved one.

**Comment by GuardianDll** [comment]
Oh I'm dumb, my bad

**Review by LyleSY — APPROVED** [review]

**Pull request merged**
