### PR TITLE
Strapped/waist items rebalance.

### PR DESCRIPTION
**Pull request by BrianLefler**
Here's the proposed formula which I'm trying to plug everything into.  If gear roughly adheres to this, then wearing right-sized item will always be a better choice than layering, layering small items will be close behind (maybe worth it for the flexibility), and people should have a valid range of options for both belts & packs.
- Make typical gear to have a storage value of ~ 6 + 4*encumbrance (but with lots of variation within).
- Make top-end gear have a storage value of ~ 8 + 5*encumbrance.
- Consider vests & harnesses to be heavy belts rather than backpacks to give more options for the waist slot.
- Retouch names & descriptions where useful (remove light & heavy from names if there's no other version).
- Made the survivor belt storage 12 and encumbrance 1 to contrast with the survivor harness (storage 15+holster, encumbrance 2).

### CODE REVIEW

**Comment by BrianLefler** [comment]
Removing [WIP].  That was actually pretty quick, most items were close to these values already.

**Comment by Coolthulhu** [comment]
> We may be calculating layered differently though, isn't it normally just half the unlayered value?

I calculated layered as `storage * 2 / (encumbrance + 1.5 * max( encumbrance, 2 ) )`, because the highest encumbrance item doesn't cause the penalty and layering more than two items should be a bad thing to do.

**Comment by BrianLefler** [comment]
I thought a layered item added its value +100%, not +50%?  So the encumbrance of two identical items stacked will be `storage * 2 / (encumbrance + 2 * max( encumbrance, 2 ) )`.

Either way, I really had trouble thinking about it that way, but the idea of a formula is a lot easier for me to follow.  For top-end gear which meets the formula, this is what I get.
Encumbrance | Storage | S/E (layered)
------------------ | ----------- | ----
0 (2 layered) | 8 | 4
1 (3 layered) | 13 | 4.33
2 (4 layered) | 18 | 4.5
3 (6 layered) | 23 | 3.88

Since wearing a bigger piece of gear should give 5 storage per encumbrance, it should always be better to do that instead if a piece of gear exists w/ the amount of storage you're seeking.

**Comment by Rivet-the-Zombie** [comment]
>Consider vests & harnesses to be heavy belts rather than backpacks to give more options for the waist slot.

Why not move them to the OUTER layer, so that you can still wear a vest with a backpack without extra layering penalties?

**Comment by BrianLefler** [comment]
I guess it's all a judgement call.  We describe them as vests or harnesses, but I googled chest rigs and they really do look basically like belts, where they have straps for support but are mostly a real heavy band around the waist.  Right now there aren't really heavy belts and it seemed nice to to have an option.  With this, the waist progression is: tactical dump pouches (8s for 0e) + survivor belts (12s+sheath for 1e) + survival harness (15s+holster for 2e).

**Comment by Coolthulhu** [comment]
> I thought a layered item added its value +100%, not +50%?

Oops, my fault. I tried to add the `encumbrance*2` and layering and multiply by 150% at the same time, but should only do one of those.

Formula should be:
`(2*storage)/(2*enc + max(2, enc))`, because encumbrance is applied twice, then layering penalty is low-capped at 2 and added.

**Comment by BrianLefler** [comment]
Tho I like OUTER too.  Lots of pics of people wearing chest rigs and *not* jackets, and then it would fit in as a lighter alternative to the survivor duster.  Either OUTER or WAIST makes more sense to me than vests conflicting with backpacks.

**Comment by Rivet-the-Zombie** [comment]
I'm leaning towards the OUTER flag for them, since you really ought to be able to wear a vest, belt, and backpack without having them interfere with each other too badly.

**Comment by md000** [comment]
But shouldn't you be able to wear a chest rig over a jacket without any problems as well?

**Comment by Rivet-the-Zombie** [comment]
Since they're both worn over your chest, I would imagine that a jacket would interfere with a chest rig more than a belt worn on the waist would.

**Pull request merged**
