### PR TITLE
Some initial work on multi-story houses

### LINKED ISSUE #15914: Multilevel houses (and shops/parks)
I wanted to add custom basement for one of the houses but realized that it can only be done using `overmap_specials`, and they are designed for unique structures (that are mostly outside towns).
It would be nice to have a tool to create multilevel houses/shops and add them to `regional_map_settings` (or just straight up assign `om_terrain` to them).

Also I looked and didn't find any documentation on `overmap_specials`.

p.s. Maybe this way we can also add `house_base` to json houses and resolve #10612.

### PR DESCRIPTION
**Pull request by Coolthulhu**
My take on #20399

Basically:
* Each house/shop/park gets converted to a special with some extra constraints
* One of these constraints is 1x1 footprint (otherwise it would require a lot of extra overmapgen code)
* Those specials are placed using the regular `place_special`, because it handles vertical placement just fine
* Multi-z-level buildings will need to be specials for now. They do need to have data about multiple different overmap tiles - a 3 z-level house can't have any of its z-levels share an ID - ground level needs doors, middle level needs both up and down stairs, highest level needs down stairs but no up stairs
* Houses can now be specified in regional settings, like shops and parks are

Ported and modified a two story house out of More Locations mod. It accounts for ~200 lines out of the PR.

EDIT: Closes #15914

### CODE REVIEW

**Comment by Coolthulhu** [comment]
All right, I got it to actually work. It doesn't need that complex optimization at the moment.

**Comment by DangerNoodle** [comment]
Will this have any negative effect on the mandated overmap specials count, especially with mods that add more? Listing of `0, 0` in your added specials implies behavior different from what most are familiar with.

**Comment by Coolthulhu** [comment]
No. They have 0 appearances and thus don't use the sectored special spawning code.
While they are on the list of specials, it's only a formality.

If edited to have non-zero appearances and at least one allowed terrain, they could also be spawned as specials, but that doesn't affect their role as city spawns.

**Comment by DangerNoodle** [comment]
Very well then, thank you.

**Comment by Coolthulhu** [comment]
I don't understand what is this coverage test thing even trying to say.
All the decreases in coverage are in files untouched here - most of them not changed even indirectly.

I'll just push updates from master and hope it covers the complaints.

**Comment by kevingranade** [comment]
That's an advisory failure more than anything, it doesn't block pushes.
For the time being I've loosened the threshold since it is quite jittery now, especially after adding the overmap specials test, I'm assuming that exercises wildly different code areas at random depending on how special placement goes.  It'll calm down in we add unit tests for more of mapgen so it's covered regardless of what the overmap specials test does.

**Comment by Leland** [comment]
Will close #15914

**Comment by Coolthulhu** [comment]
Updated

I set the chance for the 2story house very low for now (1/1334), meaning the best way to test it is to first bump it or force-generate it with debug.
I set it low because there is only one entry for two story house at the moment.

**Comment by Coolthulhu** [comment]
I just realized this system could be used to automatically create roofs for houses without having to invoke an extra post-load sanitization.
I didn't add it here, but it will be a nice bonus.

**Comment by Coolthulhu** [comment]
Anything wrong with it?
It arguably fixes a 0.D blocker, and even if it doesn't, it includes most of the work to fix it.

**Comment by kevingranade** [comment]
I've taken three runs at reviewing this, and every time I come away having no idea how it's supposed to work.  This in particular threw me:
> Each house/shop/park gets converted to a special with some extra constraints
> Those specials are placed using the regular place_special, because it handles vertical placement just fine

And I only just now recovered from this misunderstanding.  I understood this to mean you were running some kind of transformation on the house definitions and then placing them along with the rest of the specials, when in reality what you mean is you've adjusted the overmap's idea of what a house is to use your variant of a special, and then using just the terminal place_special method to add it to the overmap.

My remaining concern is if you aren't using the special spawning code, why are the objects going on the special lists? You can arrange to share the deserialization code and object types, but give them a new json type and load them into a new structure internally.

**Comment by Coolthulhu** [comment]
> My remaining concern is if you aren't using the special spawning code, why are the objects going on the special lists?

They do use the special spawning, just not the rules for finding a spot for them.
The spot is found using rules for city buildings, but then the function for spawning an actual special is invoked.

> You can arrange to share the deserialization code and object types, but give them a new json type and load them into a new structure internally.

Is it just the `"type" : "overmap_special"` part that needs changing or does it need to be some more significant refactoring?
Is it fine for it to be an alias that doesn't need certain fields (occurrence etc.)?

**Comment by kevingranade** [comment]
> They do use the special spawning, just not the rules for finding a spot for them.
The spot is found using rules for city buildings, but then the function for spawning an actual special is invoked.

This is pretty much perfect now that I understand how it works.

> Is it just the "type" : "overmap_special" part that needs changing or does it need to be some more significant refactoring?

Mostly that, just make it "city_special" or something.

> Is it fine for it to be an alias that doesn't need certain fields (occurrence etc.)?

Totally.

**Pull request merged**
