### PR TITLE
rewrite the loading screen to use ImGui

### PR DESCRIPTION
**Pull request by db48x**
#### Summary
Interface "rewrite the loading screen to use ImGui"

#### Purpose of change

We ought to put _something_ on the screen while we load things, lest the users think it crashed.

#### Describe the solution

Did the simplest possible thing.

#### Describe alternatives you've considered

I considered starting a thread and having it run a loop at 60fps so that the game always responds to events during the loading, even when one step takes a long time. But that’s a lot of work for a Tuesday.

I thought about animations.

I considered writing an homage to Homestuck by making it look like the sburb loading screen.

#### Testing

Ran the game. It looked ok.

### CODE REVIEW

**Comment by db48x** [comment]
Seriously? A comment on a namespace that is two whole lines long? That’s why it failed?

**Comment by zakhad** [comment]
image

Hey i just updated and i get this error i presume it's related to this, and i instantly crash to desktop afterwards.

**Comment by db48x** [comment]
Oh, that’s fun. I didn't consider that we might have inconsistent support for image formats across platforms. What version of SDL_Image did you build with?

**Comment by alef** [comment]
> Hey i just updated and i get this error i presume it's related to this, and i instantly crash to desktop afterwards.

Same here. Built with CMake `windows-tiles-sounds-x64-msvc` profile.

**Comment by gitelitko** [comment]
cataclysm-tiles_Mh3p350FD9

windows-tiles-x64

**Comment by Burnrate** [comment]
I get this as well on windows 10

 DEBUG    : Error: Could not load image "gfx\cdda.avif": Unsupported image format

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 1062
 VERSION  : cdda-experimental-2024-09-05-1725 858f8bc

**Comment by HadeanLake** [comment]
> What version of SDL_Image did you build with?

2.30.7 linux

**Comment by akrieger** [comment]
`avif` support is not in sdl2-image in vcpkg https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-image/vcpkg.json

**Comment by ZhilkinSerg** [comment]
Let's use PNG

**Comment by db48x** [comment]
Yea, sorry about that folks. I did convert it to a PNG in the end, since AVIF support is so spotty. It doubled the size of the image though.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/76226

**Pull request merged**
