### PR TITLE
Remove flag constants that are not actually used.

### PR DESCRIPTION
**Pull request by BevapDin**
Remove some unused flag constants.

They are not used at all. Therefor unused.

For some reason the PR #58617 added a constant to the C++ code. Without actually using it. It literally added the declaration and the definition of the constant, no other code was changed.

#### Summary
None

### CODE REVIEW

**Comment by Maleclypse** [comment]
@Drew4484

**Comment by Drew4484** [comment]
> @Drew4484 

Looks like a rebase went wrong and included a bunch of changes it shouldn't have. #58617 can be reverted and I'll resubmit, as it should have only impacted one file.

**Comment by Drew4484** [comment]
This can be changed, #58617 had some changes that are part of #58685, now that both are merged the flags are in use.

**Comment by BevapDin** [comment]
I don't get it. These flags are still unused in the C++ code. Yes, they are referenced in the JSON files. I have not removed them there.

This PR does not change or remove a feature, it removes code that has **no effect** at all.

This is not specific to the EXO flags. This PR removes not just some EXO flag constants, but several other (also unused) ones.

And one has to ask: why do I have to rebuild the game after applying changes to the JSON files? Isn't the point of loading all the data from JSON that one can change the game data **without** rebuilding it?

**Comment by Drew4484** [comment]
The exosuits flags are used to limit the contents of pockets. They don't _do_ anything on their own but are essential for the exosuits all the same. Likewise for the ABLATIVE_MEDIUM and ABLATIVE_LARGE, and presumably several others you've included. Please look at where the flags are actually used and check with the authors before removing any flags.

**Comment by BevapDin** [comment]
This PR does not remove any flags from any JSON file. The behaviour of the game is not changed by this PR. It removes C++ constants that do nothing anyway.

**Comment by anothersimulacrum** [comment]
This isn't removing the flags, it's removing unnecessary C++ constants that have no effect.

**Comment by Drew4484** [comment]
> This PR does not remove any flags from any JSON file. The behaviour of the game is not changed by this PR. It removes C++ constants that do nothing anyway.

Sorry, I misunderstood the goal!

**Pull request closed without merging**
