### PR TITLE
(Typo) Correct verb form of "costs" on scenario selection screen

### PR DESCRIPTION
**Pull request by perryprog**
#### Summary

SUMMARY: None

#### Purpose of change
"Cost" would only be correct if there are multiple scenarios ("these scenarios cost two points"), which doesn't apply here.

### CODE REVIEW

**Comment by perryprog** [comment]
Just realized there's an `ngettext`, so this might be incorrect. Checking and will also test just in case.

**Comment by perryprog** [comment]
This _may_ be OK now, but because I hadn't realize this was a localized message before making the PR I wasn't prepared to update the corresponding gettext files (and don't have experience with them). I'm currently recompiling with localization to triple check it's good now.

**Comment by Qrox** [comment]
The `.po` files shouldn't be hand-edited, they are updated via Transifex.

**Comment by perryprog** [comment]
@Qrox figures, sorry—should I drop the second commit then?

**Comment by Qrox** [comment]
Yep. You can update the localized messages on Transifex after this is merged.

**Comment by perryprog** [comment]
Done, and going to sleep—I'll make sure to be much less impetuous when reading the documentation for Transifix tomorrow. 😉
Hasty commits while drowsy is totally always a good idea.

**Review by BrettDong — APPROVED** [review]
Editing source code is sufficient. Translation data on Transifex will automatically be updated once this is merged.

**Pull request merged**
