### PR TITLE
[CR] Color Manager

### PR DESCRIPTION
**Pull request by OzoneH3**
GUI to change all available colors. Access through help menu ?4.

NoBright is used for inverted colors when NO_BRIGHT_BACKGROUNDS option is set.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woo! A treat for colorblind folks 

Pinging @Rivet-the-Zombie, @DavidKeaton

**Comment by DavidKeaton** [comment]
NICE!

**Comment by sparr** [comment]
This is amazing. Sets the stage for allowing per-usage color customization.

**Comment by kevingranade** [comment]
Super awesome!  Hmm, pallette shifting?  Is that a thing we can do?

**Comment by DavidKeaton** [comment]
If SDL runs in 8 bit, otherwise we'd have to emulate it.

**Comment by Rivet-the-Zombie** [comment]
I really like the sound of this! Now I won't have to go blind trying to read freaky color combinations.

**Comment by KA101** [comment]
Much appreciated, OzoneH3.  Thanks, and I'm sorry I was tied up with the IRL today.

**Comment by OzoneH3** [comment]
Two things I'm not sure about:

1) Is NoBright really used at all? It would save some space to remove it. I could display the actual custom color name instead of just custom.
I thought about adding some predefined templates for people to load. Various colorblind ones hopefully someone will provide. I could move the NoBright ones (since those are only 6 or so) to a template as well.

2) Lets say I set the custom color of c_gray to c_red. Then I set the custom of c_white to c_gray.
At the moment c_white would become c_gray or should it become the custom of c_gray -> c_red?

**Comment by KA101** [comment]
I'm ready to merge this as-is, and we can tweak it later.  Agreed that presets would be (or at least seem) useful.

I'd discourage daisy-chaining as described in 2: to me, that seems likely to cause confusion.  Not sure if I'm being overcautious there.

**Comment by kevingranade** [comment]
I agree on both counts, presets sound awesome, but can be added later.
Also daisy-chaining sounds confusing, if I set c_red to be c_ltred, I don't
want it to affect my c_blue to c_red mapping.

**Comment by DavidKeaton** [comment]
@kevingranade load order alias hell ;-)

**Pull request merged**
