### PR TITLE
The Red Dragon Teashop

### PR DESCRIPTION
**Pull request by jokermatt999**
In honor of Aavak restarting his Let's Play series, I asked him if there were any ideas he'd like implemented. He said he didn't have anything specific other than "comical amounts of teashops". One isn't that funny, but it'll do for now.

I was also going to include chamomile tea in this pull request, but my compiler is being a bit screwy, so this is just the json for now.

### CODE REVIEW

**Comment by chaosvolt** [comment]
What's this about dragons? And tea? interesting. owo

**Comment by jokermatt999** [comment]
Sorry, this red dragon: https://en.wikipedia.org/wiki/Welsh_Dragon

**Comment by chaosvolt** [comment]
Ah, right. X3

**Comment by vache** [comment]
I get the feeling the red dragon tea shop is going to be a very popular chain in cataclysm era New England.

**Comment by jokermatt999** [comment]
You had me worried I forgot to update the weighting there. :)

**Comment by vache** [comment]
Nah, more like every tea shop is going to have that sign out front that says it's the red dragon tea shop.  It won't be a big deal once there are more tea shop mapgens.

Also IMO the tea shop oter weight seems a little high.  I would put it in the same category as coffee shops and tweak the weighting a little bit so that maybe every 5 coffee shops is a tea room?  If you keep it distinct, maybe drop the weight down to 2?

**Comment by jokermatt999** [comment]
If I put it on with coffee shops, won't the overmap tile show "coffee shop"?

**Comment by vache** [comment]
Hmmm that's a good point.  I hadn't considered that.  Maybe we can up the weightings for shops in cities and use that to tweak shop chances with better granularity.

**Comment by chaosvolt** [comment]
I'd suggest making the overmap say tea shop, but find some way to make the sign display a random name. Unsure how to do so, short of the clunky method of using duplicate mapgen files.

**Comment by vache** [comment]
That is actually something I've been wanting to do for a little while now.  I might take a look at how to implement a system to allow semi-random signs, probably using the snippet system.  The big thing for that is to make sure that it can generate a sign randomly at mapgen and then save and load the generated sign as necessary.  I'd actually like to get a lot more random generation options, like being able to do something like "\<lastname\> and sons" or "\<lastname\>, \<lastname\>, and \<lastname\> law firm" and have the game automatically fill those in with random names.

**Comment by jokermatt999** [comment]
That'd be awesome! If you implement it, I'll definitely make use of that.

**Comment by chaosvolt** [comment]
Oh hell yes, that would be useful.

**Comment by vache** [comment]
It wouldn't really be all that hard now that I'm thinking about it.  Maybe I'll give it a look and see if I can knock it out in one quick night before fallout 4 fully absorbs me again.

**Comment by Zireael07** [comment]
@vache, that'd be amazing!

**Comment by BevapDin** [comment]
> to make sure that it can generate a sign randomly at mapgen and then save and load the generated sign as necessary.

Signs are already saved and loaded just fine. Signs (and their text) from mapgen is stored the same way as the stuff your character writes with a spray can.

**Comment by chaosvolt** [comment]
> Signs are already saved and loaded just fine. Signs (and their text) from mapgen is stored the same way as the stuff your character writes with a spray can.

I suspected as much, yeah. So altering the sign-creating code to allow citing a snippet entry would likely be the key part. Though retaining its current ability as an optional way to build signs, just in case, might be a good idea.

**Comment by vache** [comment]
Yeah.  It only needs to know the random stuff up until mapgen, then that will get overwritten with the generated message so it saves and loads fine.

So I'm thinking add an alternate json tag for signs, so it can either have "signage":"hey this is a sign!" or "snippet":"snippet_sign_category", and then allow signage and entries in snippets to have tags like \<lastname\>, \<firstname\>, and maybe \<city\> that can fetch a random last name, random first name, or the name of the nearest city.  All random substitution happens at mapgen when it gets stored at the submap level so any saving/loading saves the generated text.

**Comment by chaosvolt** [comment]
Maybe. Allowing snippets to cite city names would add to the complexity though, we'd need to ensure that similar results are consistent across a given town.

That making it so that the sign text is only relevant in the context of the store itself means less work involved.

**Comment by vache** [comment]
Unless two towns somehow happens to generate right next to each other to the point that it looks like one big town (which does happen), they should have the same names as other buildings in the town.  The city names are already being generated and stored, they just need to be accessed.

**Comment by chaosvolt** [comment]
Ah, I see. Towns do in fact have names? Odd, I can't recall seeing that very often. o.O

Also, here's a thought for a stupid workaround. Does the add_signs function allow for chance or probably, like other stuff-placing mapgen functions typically do? If so, one could start with a default signage with a 100% chance of placement, followed by a selection of alternatives with a less than 100% chance of appearing.

Assuming that rolling for multiple signs overwrites the initial result instead of throwing up an error (or worse, succeeding in compacting multiple successful sign generations in one space), this would allow some randomness, though trying to calculate that actual odds of any given sign appearing would be a lot screwier than just using a weighted group like sane people would.

And that's still assuming place_signs allows for probability, which I doubt.

**Comment by vache** [comment]
They do have names, but they never get referenced anywhere.  One of my longer term goals is to make more use of this city flavor and give them a little more lifelike feel.  

No need for a workaround implementation.  The actual implementation of the right way to do it should be straightforward enough, it's just a matter of taking the time to do it, which will probably be the weekend if I had to guess.

**Comment by chaosvolt** [comment]
True. It was more curiosity on my part, as I don't know whether the workaround would even work. XP

**Comment by BevapDin** [comment]
> So I'm thinking add an alternate json tag for signs, so it can either have "signage":"hey this is a sign!" or "snippet":"snippet_sign_category", and then allow signage and entries in snippets to have tags like <lastname>, <firstname>, and maybe <city> that can fetch a random last name, random first name, or the name of the nearest city. All random substitution happens at mapgen when it gets stored at the submap level so any saving/loading saves the generated text.

Would probably best to add this to `jmapgen_sign` (mapgen.cpp), not as part of the `f_sign` definition. The class there already contains a string for the sign. It could be extended to replace a keyword in the sign text with location data. For example it could replace "\<town-name\>" with the name of the town. Or "\<surname\>" with a random surname.

> Ah, I see. Towns do in fact have names? Odd, I can't recall seeing that very often. o.O

When your character dies in or nearby a town, the memorial log (text file with the `.log` extension in the save / graveyard folder) gets an entry like "Died in \<city-name\>."

**Comment by vache** [comment]
PR filed at #14032

**Comment by chaosvolt** [comment]
And that's been merged it seems, so now...snippets, whee.

Also still have the sprite for the chamomile plant in the tileset itself, and an item sprite for chamomile stowed away elsewhere. I'll make use of that in the event that picking chamomile becomes a thing, since I wouldn't know for sure what the item ID will be. o3o

**Pull request merged**
