### PR TITLE
Fix compound Eyes

### LINKED ISSUE #43378: Compound eyes perception bonus does not match up to its description
# Describe the bug

The compound eyes mutation's description says that it will give 2 bonus perception, but the actual stat boost is only 1.

# Steps To Reproduce

1. Acquire the mutation
2. Check the bonus

# Expected behavior

Either change the description to the real value, or change the value to match the description. I have no idea which of the two was the intended bonus, so I'll leave that to the experts.

# Screenshots

image

You can see that the bonus is giving only 1 perception, and I have no gear that covers the eyes

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-5518-g9dbd68a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    Crazy Cataclysm [crazy_cataclysm]
]

### PR DESCRIPTION
**Pull request by Theundyingcode**
#### Summary
SUMMARY: Bugfixes "Fix compound eyes."

#### Purpose of change
fixes #43378

#### Describe the solution
Give compound eyes stated +2 perception bonus.

EDIT: Originally completely overlooked the whole "while not wearing eyewear" thing.  Converted to draft as I try to add encumbrance based mutation triggers as less hard coded stuff is better and, I can see potential other uses for it too (ex: trait for nudist runs).

#### Describe alternatives you've considered

Change description.

### CODE REVIEW

**Comment by Theundyingcode** [comment]
Just realised I didn't handle the "while not wearing eyewear" bit

**Comment by ZhilkinSerg** [comment]
Don't forget to remove existing hardcode:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9b7cd49702233609d53573cb26bb0ca1183e8b57/src/avatar.cpp#L1174-L1176

**Comment by Theundyingcode** [comment]
>

> Don't forget to remove existing hardcode:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/9b7cd49702233609d53573cb26bb0ca1183e8b57/src/avatar.cpp#L1174-L1176

@ZhilkinSerg  Thanks for pointing that out.  I didn't even think to check there when I was looking for hard/existing code...  I'm not familiar with avatar at all... It looks to me like a external interface to player for the character builder, bionics and, a few other random things.  Not sure what the benefit of leveraging that would be since the player already owns the mutation.

**Comment by Theundyingcode** [comment]
Can't seem to get the triggers to work right no matter what tweaks I make to the JSON.  Not sure if i'm doing something horribly wrong with the JSON or there is an issue with the trigger code.

**Comment by Theundyingcode** [comment]
Closing PR as I have begun re-working the triggers and thus fundamentally changing the PRs nature.  Will open up new one once I am finished.

**Pull request closed without merging**
