### PR TITLE
[Magiclysm] Leprechaun adjustments

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Mods "Magiclysm Leprechaun Edits"

#### Purpose of change
Adds a prank spell to the leprechaun and makes it less of a backroad serial killer.  I'd love it if there was a way to do something like hit and run but instead it cast a spell and then bolted.     

#### Describe the solution
Adds the spell as "prank",  drops damage from the leprechaun so it doesn't close with you and hit you three times for a third of a limb each hit.   Requires #48740 to merge first.

#### Testing
TBD

### CODE REVIEW

**Comment by actual-nh** [comment]
Some possibilities:
- How about using the zombie technician attack? It steals metal, and seeing that it isn't gold, drops it.
- #48740 behavior? Set it to keep at maximum distance for the zombie technician attack and/or the attack spell.
- Randomized effects on the attack spell if used (including as well as the above) - downed+winded instead of vomit, for instance.
- Drop morale to, say, 5 and put in HURT as a fear trigger.
- To be really nice, PLAYER_WEAK as a pacify trigger, although this will require some C++ alterations to make it functional IIRC. (There really should be a load-time warning for using non-functional anger/fear//pacification triggers, e.g., MEAT as a pacify trigger...)

**Comment by Maleclypse** [comment]
> Some possibilities:
> 
> * How about using the zombie technician attack? It steals metal, and seeing that it isn't gold, drops it.
> * #48740 behavior? Set it to keep at maximum distance for the zombie technician attack and/or the attack spell.
> * Randomized effects on the attack spell if used (including as well as the above) - downed+winded instead of vomit, for instance.
> * Drop morale to, say, 5 and put in HURT as a fear trigger.
> * To be really nice, PLAYER_WEAK as a pacify trigger, although this will require some C++ alterations to make it functional IIRC. (There really should be a load-time warning for using non-functional anger/fear//pacification triggers, e.g., MEAT as a pacify trigger...)

I think the technician attack would also need C++ since the technician holds onto the weapon until killed?

**Comment by actual-nh** [comment]
> > Some possibilities:
> > 
> > * How about using the zombie technician attack? It steals metal, and seeing that it isn't gold, drops it.
> > * #48740 behavior? Set it to keep at maximum distance for the zombie technician attack and/or the attack spell.
> > * Randomized effects on the attack spell if used (including as well as the above) - downed+winded instead of vomit, for instance.
> > * Drop morale to, say, 5 and put in HURT as a fear trigger.
> > * To be really nice, PLAYER_WEAK as a pacify trigger, although this will require some C++ alterations to make it functional IIRC. (There really should be a load-time warning for using non-functional anger/fear/pacification triggers, e.g., MEAT as a pacify trigger...)
> 
> I think the technician attack would also need C++ since the technician holds onto the weapon until killed?

Oh? Having never gotten that far, I didn't know that - although the attack itself doesn't put it into their hands anymore, but on the ground at their feet.

**Comment by Maleclypse** [comment]
> Oh? Having never gotten that far, I didn't know that - although the attack itself doesn't put it into their hands anymore, but on the ground at their feet.

You are correct and that is a great effect possibility.  I swear at one point at least I had to kill technicians to get my gear back but thanks for correcting my mistake :).

**Comment by actual-nh** [comment]
> > Oh? Having never gotten that far, I didn't know that - although the attack itself doesn't put it into their hands anymore, but on the ground at their feet.
> 
> You are correct and that is a great effect possibility. I swear at one point at least I had to kill technicians to get my gear back but thanks for correcting my mistake :).

Quite welcome - from my recollection of the change in question, you indeed probably did at one point.

**Comment by Maleclypse** [comment]
OK to do the "Randomized effects on the attack spell if used (including as well as the above) - downed+winded instead of vomit, for instance."
I can use the Wonder effect but I'd need to create separate spells for each effect and while vomit won't be hard, I'll look into whether the weapon grab can be converted into a spell format. I'll have to find a spell that has a downed effect too.

**Comment by Maleclypse** [comment]
@KorGgenT  This PR is ready.

**Comment by KorGgenT** [comment]
gag humor.

**Comment by Theawesomeboophis** [comment]
Awesome work on this btw, I really like the idea of leprechauns just being magic prankster and it is very interesting part of their folkloric/mythological origins.

**Pull request merged**
