### PR TITLE
Allow a player activity to refer to monsters

### PR DESCRIPTION
**Pull request by prutschman**
#### Summary
SUMMARY: Infrastructure "Allow a player_activity to refer to specific monster(s)"

#### Purpose of change
Adds a list of monsters to player_activity, allowing activities to refer to monsters, at least as long as they continue to exist. 

#### Describe the solution
`player_activity` gains a member `monsters`, stored as a `vector<weak_ptr<monster>>`.
Because `monster`s don't have unique IDs, serialization/deserialization is added for `weak_ptr<monster>` using the critter tracker's temporary ID mechanism. To allow for a future possible transition to a different reference mechanism, the temporary ID is serialized as a json object `{"temp_id": <integer> }` instead of just the raw integer.

#### Describe alternatives you've considered
`player` does have a unique ID. This could in principle be hoisted into the `Creature` superclass. If that happens, the serialization can be changed to emit `{ "unique_id": <integer> }` instead.

#### Additional context
This was inspired by #27816 (Create activity for control laptop), which created an activity for the control laptop, but in so doing had to change the target selection to happen at activity completion.

### CODE REVIEW

**Comment by kevingranade** [comment]
This needs at least an example use case to justify it, otherwise it's just dead code.
Did you have something in mind that would use this, or is it entirely hypothetical?

**Comment by prutschman** [comment]
Hacking was recently changed to be interruptible. As a consequence, the target must now be picked at the end of the hack cycle, rather than at the beginning. Certainly not a huge deal, but I wondered if it could be made interruptible while still otherwise retaining the old behavior. I have a modification in progress to restore the original mechanism of picking a target before the hack, but still allowing interruption. To do this, the hack activity needs to "remember" the target.

I had split up the infrastructure and the implementation into separate pull requests, and was waiting on this one before making the other. If you prefer, I can retract this pull request, and post a new one that includes both this change to player_activity as well as the new code in the hack activity that makes use of it.

**Comment by kevingranade** [comment]
It needs to have both the infrastructure along with some use of it, so please add the changes for hacking in addition to the infrastructure.

Regarding the mechanism itself, I like the overall approach, but instead of using temporary_id, please use the location of the monster.  It's a more concrete piece of data to store and is equally unambiguous.  We would like to remove temporary_id in the future as it exposes some internal state of creature tracker that it shouldn't.

**Comment by prutschman** [comment]
Ok. Thanks for the feedback; I'll incorporate it. It'll probably be a few days before I can get to this.

**Comment by prutschman** [comment]
Closing in favor of #28465

**Pull request closed without merging**
