### PR TITLE
Adds craftable crude & fancy monocles

### PR DESCRIPTION
**Pull request by carlarctg**
#### Summary
Content "Adds craftable crude & fancy monocles"

#### Purpose of change

Adds a way to create monocles, and a way to create lens for x-sighted traits. Adds an use for crude lens.

The biggest reason for this PR is to give Innawoods characters the ability to mend their sight problems. However, there's no reason this can't apply to the basegame as well, as it contains some unique content that doesn't have true alternatives.

#### Describe the solution

There's two types of monocles this PR adds.
- Crude monocles, which are large, uncomfortable, very bulky. They help you read things, or be on the lookout for targets, but when doing anything important you'll probably want to be rid of them ASAP.
- Handcrafted monocles, which are similar to the above, but much more comfortable and less encumbering. They even have a chain so you can easily take them on and off! Of course that also means they're harder to get.

Crude monocles require level four fabrication at least, what I see as 'journeyman' glassblowing skill. (If there's a way to unlock recipes with proficiencies let me know!). They take six hours to make, and a lot more if you count the crude lens' crafting time as well. I think that means something like 10 hours total but I'm typing this in gitlens and don't want to change git tabs in case that wipes my description (it has happened before)
Handcrafted monocles are medieval or early industrial aristocrat tier, the kind of work a master glassblower could make. Thus, they're locked behind level 7, take 34 hours (10 with the crude lens craft time) to make. They're immaculately fine, with a beautiful 'fanciful metal' rim, and a string or wire to hook onto clothing when not in use.

#### Describe alternatives you've considered

Making this an Innawoods only recipe. Decided not to because this is interesting as a base-game thing as well. Especially if you consider the possiblity of the handcrafted monocle being displayed on museums, pawn shops, etc. as a historical artefact.

Just making the base monocle craftable. Decided not to because, while it's very much possible to make a basic lens by hand, you're not going to make a modern monocle by hand, not one that's so convenient to wear.

Only having one craftable monocle. Decided not to because I like the idea of a rudimentary survival lens on one hand and a finely crafted 'best we're gonna get' monocle.

Bifocal monocles. Decided not to because that's 1. overcomplicating it (stylish bifocal transition monocles, anyone?), 2. damages the concept of these being lesser imitations of modern spectacles.

The monocles both come in concave and convex, AKA reading and, uh, normal (how do you refer to optical aids for the nearsighted generally??), AKA nearsighted and farsighted.

#### Testing

Spawned myself in, spawned the monocles in. Ensured the recipes had proper requirements. Ensured the monocles worked properly. Ensured the handcrafted chains had no bugs when transforming the item. Ensured the sprite properly copied from monocles for tilesets (Thanks Guardian and Renech!)

#### Additional context

https://en.wikipedia.org/wiki/Glasses#History

> Robert Grosseteste's treatise De iride (On the Rainbow), written between 1220 and 1235, mentions using optics to "read the smallest letters at incredible distances".[23] A few years later in 1262, Roger Bacon is also known to have written on the magnifying properties of lenses.[24][25] The development of the first eyeglasses took place in northern Italy in the second half of the 13th century.[26]

Believe it or not, spectacles have been around in some way or another since the 13th century, at least. They're not impossible to make, as evidenced by two people creating them independently at around the same time. The quality will not be great, but that is already simulated here with the encumbrance.

I wanted to make the crude monocle uncomfortable, but the code prevents this by the HARD flag not doing anything, the c++ function limiting small and light items from being uncomfy, so I just decided not to bother.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
>If there's a way to unlock recipes with proficiencies let me know

You can lock recipes behind already knowing a proficiency

```{
    "id": "prac_health_care_int",
    "type": "practice",
    "activity_level": "NO_EXERCISE",
    "category": "CC_PRACTICE",
    "subcategory": "CSC_PRACTICE_HEALTH",
    "name": "bandaging (advanced)",
    "description": "Practice bandaging different limbs and less accessible parts of your body using both hands and each of your hands alone.",
    "skill_used": "firstaid",
    "time": "1 h",
    "practice_data": { "min_difficulty": 1, "max_difficulty": 2, "skill_limit": 3 },
    "proficiencies": [
      { "proficiency": "prof_wound_care", "required": true },
      { "proficiency": "prof_wound_care_expert", "time_multiplier": 1, "skill_penalty": 0 }
    ],
    "autolearn": [ [ "firstaid", 1 ] ],
    "flags": [ "BLIND_HARD" ],
    "book_learn": [ [ "booklet_firstaid", 0 ], [ "mag_firstaid", 0 ], [ "pocket_firstaid", 0 ], [ "manual_first_aid", 0 ] ],
    "tools": [
      [
        [ "bandages", -1 ],
        [ "bandages_makeshift", -1 ],
        [ "bandages_makeshift_bleached", -1 ],
        [ "bandages_makeshift_boiled", -1 ]
      ]
    ]
  }```

**Comment by harakka** [comment]
Your recipes completely miss the actual time consuming part of lens making, grinding. The recipes also should not be auto learned.
If you want to add Innawood content add it to the mod, but this approach won't fly in vanilla.

**Comment by Maddremor** [comment]
I would call any sort of optic where we care about more than the general shape of the lens crude if you have to make it by hand. Given that you can just pull lenses from eyeglasses until you get what you need I don't see what the point would be for anyone.

**Comment by PatrikLundell** [comment]
@TheShadowFerret: As far as I can determine from the practice recipe you provided, it prevents you from using the recipe until you have a required proficiency, but it doesn't do the reverse, i.e. provide you with one or more new recipes when mastering a given proficiency, which is what I think was the functionality asked about.

Basically, the functionality would be something like '"autolearn_proficiency" : [ "prof_wound_care" ]' to state that the practice recipe would automatically be learned when "prof_wound_care" was mastered. In the OP context, you might learn a "crude_concave_lense" and a "crude_convex_lense" recipe when mastering a hypothetical "basic_glassmaking_optics" proficiency (which might be learned using a research recipe (a.k.a. practice recipe) called e.g. "glassmaking_optics_research" unlocked by more basic glassmaking proficiencies unlocked via fabrication).

**Comment by carlarctg** [comment]
> Your recipes completely miss the actual time consuming part of lens making, grinding. The recipes also should not be just auto learned. Optics is kinda involved.
> If you want to add Innawood content add it to the mod, but this approach won't fly in vanilla.

That's kind of what the crude lens excess is for? Like I said in the op. If you think that's insufficient somehow, explain why. 

I can add a lengthy recipe for filing away at a crude lens to polish it, there's nothing unreasonable about that. Anyone with a basic knowledge of how lenses bend light can trial & error until they get the hang of it and make preindustrial optical lenses. A research recipe for a proficiency like the last commenter suggested would be enough to get over this hurdle.

**Comment by carlarctg** [comment]
https://youtu.be/2SJY0foypAo?si=CU5IstJuH4zT2T3-

Checked this video out. Low-level knowledge of glassblowing is all you need to understand the basics of how to make crude glass lenses with magnification. We already allow glassblowing recipes to be autolearned, don't we?

**Comment by Maddremor** [comment]
Can you give an example of a situation when someone would do this? I still don't see the use case.

**Comment by carlarctg** [comment]
> Can you give an example of a situation when someone would do this? I still don't see the use case.

A stylish survivor wants to craft a fancy monocle to look good.

**Comment by Maddremor** [comment]
As stylish survivor would get some nice looking eyeglasses, not make something probably pretty bad looking by hand.

**Comment by Zireael07** [comment]
I agree that imho fancy monocles are beyond the means of a survivor to make. They'll always be crude given the tools at their disposal

**Comment by carlarctg** [comment]
> I agree that imho fancy monocles are beyond the means of a survivor to make. They'll always be crude given the tools at their disposal

My dude. If a dude in the 13th century can make fancy monocles, then so can a survivor who puts enough work into it. Especially one who's proficient in metalworking, glassblowing, and has 'level 7' in fabrication.

**Comment by I-am-Erk** [comment]
Monocles are an 18th century invention.... Do you think crusaders wore monocles?

**Comment by Zireael07** [comment]
@carlarctg 1) I'm not a *dude*
2) Monocles postdate crusaders by quite a lot

**Comment by Maddremor** [comment]
Given that monocles aren't really fashionable anymore, would this PR still have a use case if they lacked that flag?

**Comment by Maddremor** [comment]
As of #70716 monocles are no longer fancy, so that flag has to be removed.

**Comment by kevingranade** [comment]
Crafting a monacle around a lens would be fine,  it's the lens that's the problem and that's not happening.

**Pull request closed without merging**
