### PR TITLE
Creation of 5 new overmap special campsites

### PR DESCRIPTION
**Pull request by Nymall**
Creates 5 new campsites, with similar spawning rules to the forest
cabin:
-Forest Campsite(5 tents, brazier)
-Incomplete Cabin(1 tent, half built cabin, various food drops)
-Biker Campsite(5 tents, brazier, chance to spawn up to 3 bikes)
-Destroyed Biker Campsite(bits of tent, brazier, low chance to spawn up
to 3 bikes, bodies)
-Campground(five tents, outhouse, well, braziers)

### CODE REVIEW

**Comment by mugling** [comment]
More overmap variety is always good. Issue possibly relates to #15197 although I'm not as yet sure how.

**Comment by Rivet-the-Zombie** [comment]
Neat!

**Comment by kevingranade** [comment]
Probably it's the same issue as what mugling pointed out, try ```corpse.name
= "";```

**Comment by Nymall** [comment]
Updated the JSONs and tried the newest experimental, and the issues with corpses are gone.

**Comment by Coolthulhu** [comment]
There are some issue with item spawn placement:
* Non-destroyed biker campsite has all food near one tent. Most of it not even inside
* Campsite A has logs in front of the toilet rather than in the crate (they're supposed to go into the crate, right?)
* Campsite A has food lying near the well. I assume it was supposed to go to the tent on the other side of thecamp (mirrored coordinates)

**Pull request merged**
