### PR TITLE
JSON monster cleanup (zombies)

### PR DESCRIPTION
**Pull request by mugling**
- Moves all monsters from faction `zombie` into subdir
- Normalizes fields
- Sorts fields
- Sorts monsters alphabetically by `id`

### CODE REVIEW

**Comment by mugling** [comment]
This is mostly done using `jq` followed by automated formatting than finally a small amount of hand cleanup of the formatting. There are no behavioral changes or other alterations

**Comment by Coolthulhu** [comment]
Seems to be working - all zeds load fine. But it is absolutely huge...

I'll wait for someone else to comment on it, as we don't usually merge PRs this huge. It's JSON only and no actual changes, but still.

**Comment by mugling** [comment]
I could break it up into smaller arbitrary chunks but reviewing multiple smaller PR's separately wouldn't necessarily reduce the workload?

I entirely appreciate that you don't typically want PR's of this scale but there isn't a smaller logical unit without splitting the PR at an arbitrary size and leaving the definitions split between files might actually be more confusing than anything?

The `zombie` faction is of course by far the largest...

**Comment by dbackeus** [comment]
Just some input from a code spelunker...

These sort of style consistency commits have to be huge. If only smaller chunks are done at a time then the payoff isn't really there since other contributors might still not realize which style to use for their own commits.

I remember looking at this project two years ago and one of the reasons I lost inspiration to contribute was the JSON files looking like a complete mess. I expect there are a lot of people out there who are not hardcore C programmers but would be interested in contributing / fixing / balancing content who would benefit a lot from clean and consistent JSON.

**Comment by narc0tiq** [comment]
The best I can suggest is to perform automated verification of some kind, since the major problem with merging something this large is needing to be sure everything that was valid before remains valid after.

If it were just me, I'd be willing to take it on faith that the change was done correctly -- even if one or two small issues may have been introduced, they're probably easily fixable once detected.

**Comment by mugling** [comment]
> The best I can suggest is to perform automated verification of some kind

Indeed. One trivial option would be to run a `jq` script to compare that an equivalent number of monster `id` exist after this merge.

> If it were just me, I'd be willing to take it on faith that the change was done correctly -- even if one or two small issues may have been introduced, they're probably easily fixable once detected.

Sounds reasonable. There are a lot of benefits from cleaner JSON. Less place for bugs to hide and hopefully encourage more contributions.

**Comment by kevingranade** [comment]
For future reference, this might have been possible to review if you had done each of your bullet points as a separate commit.

**Comment by mugling** [comment]
With the exception of normalization any of the above changes are going to result in a huge diff which I agree is a big obstacle to review.

One option here might be if i publish the `jq` script I used which can be run against `master` to check it produces equivalent output to the contents of this PR?

**Pull request closed without merging**
