### PR TITLE
Adds full belt spawns to military base armory.

### PR DESCRIPTION
**Pull request by aMegaSloth**
#### Summary
bugfixes "Create full belt item, have it spawn for the armory"

#### Purpose of change

It doesn't really make sense that the armory would store the default belts that wold start with 100 out of 500 bullets in the belt.

#### Describe the solution
Create a new item group to specifically spawn where the old place_item for belts are. verified they spawn as fully loaded ammo belts.
Add them to the place_item for the military base.

#### Testing
Started new game, jumped around until I found a base. checked armory, and it had full ammo belts.

### CODE REVIEW

**Comment by aMegaSloth** [comment]
> Similar note: broken ceramic plates stored everywhere clean plate carriers are

I was thinking of doing a different PR for this. It sounds like @GuardianDll is going to take care of it though.

**Comment by casswedson** [comment]
I'd not create new items to solve this specific problem; if you add items you also gotta add uses to them, guns would need to accept them as magazines, they need to spawn in more places etc

I would use itemgroups to solve this, see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ITEM_SPAWN.md

**Comment by aMegaSloth** [comment]
As much as that makes more sense @casswedson, there seems to be a bug in getting ammo belts spawning with more than 101 of ammo. I spent the last 2 hours trying to work though it but doesn't seem possible.

**Comment by aMegaSloth** [comment]
So it seems like I was able to get it.

I thought I tried this but for some reason I guess I didn't do it correctly the first time.
Anywho, I also slightly bumped up the chance of getting more belts, but it shouldn't matter too much.

Before it was a flat 75% chance of getting either 556 belts or 762. Now it rolls a few times at 75% chance so spawn isnt as static.

**Comment by aMegaSloth** [comment]
I am closing this to fold in other military base updates coming very shortly.

**Pull request closed without merging**
