### PR TITLE
[CR]Vehicle part weight/efficiency adjustments

### PR DESCRIPTION
**Pull request by Coolthulhu**
Changes to batteries, engines and frames.

Batteries got a giant nerf - their capacities got cut by an order of magnitude, their weights got increased with no compensation to their stats at all.

| Battery | Capacity | Weight in kg | Capacity-per-kg |
| --- | --- | --- | --- |
| Motorbike | 2k | 6kg | 333 |
| Car | 4.5k | 18kg | 250 |
| Truck | 8k | 30kg | 267 |
| Small storage | 0.5k | 2.5kg | 200 |
| Medium storage | 7k | 31kg | 226 |
| Big storage | 40k | 150kg | 267 |

Storage batteries also got their volumes increased, but that isn't too relevant for vehicles which ignore volumes anyway.

Electric engines got buffed to compensate:

| Engine | Power | E-power | E-power per power |
| --- | --- | --- | --- |
| Small | 20 | 5000 | 250 |
| Medium | 100 | 20000 | 200 |
| Big | 400 | 120000 | 300 |
| Enhanced | 500 | 200000 | 400 |

Frames got rebalanced (mostly nerfed).

| Frame | Durability | Weight in kg | Durability per kg |
| --- | --- | --- | --- |
| Handle | 30 | 1.25 | 24 |
| XLight | 150 | 5 | 30 |
| Frame | 400 | 20 | 20 |
| HDuty | 1200 | 60 | 20 |
| Foldable XL | 50 | 5 | 10 |
| Wooden | 150 | 8 | 18.8 |
| Light wooden | 100 | 4 | 25 |
| Foldable wooden | 15 | 4 | 3.75 |

Light frames lost a small bit of HP, regular frames got a big increase in weight, heavy duty frames almost doubled in weight.

Resulting vehicles have weights more comparable to the IRL ones.

Other adjustments:
- Solar panels lose ~60% of their efficiency. Except quantum ones, those lose ~46% instead
- Removed AISLE from cargo holder. It can't have both AISLE and volume 1000 of stuff on it
- Increased cargo holder weight with heavy frame. Now it weights 80 kg and is not as much of a no-brainer.
- Made bone and chitin armor kits cheaper, easier to craft, lighter and generally better to make them more sensible to craft to armor very light vehicles
- Made water purifier take "anywhere" instead of "center"
- Decreased reactor install difficulty to 6 (from 8). Now that batteries aren't amazing, it might see some use.
- Increased floodlight energy consumption 10fold - was 187, is 2000
- Increased stereo system energy consumption 2x. It uses some weird system for draining power, unlike all other parts, so it can't be directly compared, but it is roughly 700 epower

### CODE REVIEW

**Comment by dbackeus** [comment]
Enjoyed seeing the very detailed breakdown of what changed technically in this PR. Would have also enjoyed to see description for how the game ends up being more balanced after it. Maybe with a before and after scenario: *here's what didn't make sense in the game before, here's how it makes sense now* kind of thing.

**Comment by Coolthulhu** [comment]
What got more realistic:
* Car weights. An average American car weighs almost 2 metric tons, DDA cars weighed ~0.7 metric tons, now they're around 1.1 metric ton
* Truck/military vehicle weights. Commercial truck can easily weigh 10 metric tons, now the in-game ones can get closer to those values
* Battery weights. IRL car battery weighs ~20 kg and electric car battery ~0.3 metric tons

How do the two above improve gameplay:
* The choice of a light vs. regular frame has more of an impact on vehicle's velocity and fuel usage
* Non-light vehicles will need more wheel area. Still not enough, as removing wheels from fully loaded truck will still improve its velocity, but it's an improvement anyway
* Stacking infinite batteries on a vehicle just because you can is no longer such a good idea.

Other improvements to gameplay:
* Solar panels will no longer instantly satisfy all electric needs forever, unless you are conservative with electric energy
* Using a minireactor to make a light electric vehicle is now closer to making sense. It would still be expensive to maintain, but could actually be useful.
* The choice of using a lighter electric engine (for more efficiency) is now closer to being sane

The biggest change is the battery one. It shouldn't be a good idea to connect all batteries to the vehicle. IRL one of the biggest problems with electric vehicles is that electric car batteries are prohibitively heavy.

**Comment by mugling** [comment]
Good, this restores some much needed balance.

@Coolthulhu how would you feel about applying the same order-of-magnitude adjustment to fuel consumption as per #15362.

There's also an argument for reducing the cargo capacity of various items - a vehicle laden with scrap frames remains too small.

**Comment by Coolthulhu** [comment]
I didn't change fuel consumption that much with this PR. Weight increases do affect it, but not much since the formula is very forgiving.

I'm not sure how would I change combustion engines' efficiency. Multiplying consumption by a factor of 2 or so probably wouldn't hurt, but I'd rather see it depend on engine size instead. Medium size combustion engines don't see much use, everyone goes for the V12s as soon as possible.

The only reason to nerf the small ones would be the alternators. If we do change engine efficiency to depend on vehicle size, it should not make small engines significantly better at powering alternators - fuel drain from alternator should be more or less constant.

**Comment by mugling** [comment]
Could we not have a fuel efficiency property for each engine as a crude but reasonable starting point? Where in the code is fuel usage calculated?

**Comment by Coolthulhu** [comment]
Hardcoded per fuel type near the top of vehicle.cpp

**Comment by Zireael07** [comment]
I like most of the changes except the electric batteries - don't you think the technology would have progressed so far by 204x that they are no longer

> prohibitely heavy

?

**Comment by kevingranade** [comment]
No, we've gone over this many times, technology is assumed to be
contemporary unless it's specifically super-science.

**Comment by dbackeus** [comment]
Great stuff. Interesting to see how real life ends up being a very good starting point for achieving balance :+1: 

As for the next step of vehicle balancing (as outlined in the "Too much fuel" issue) increasing fuel usage based on engine type + increase the penalty of weight seems to me the most interesting direction to take right now.

**Comment by Rasip** [comment]
> Car weights. An average American car weighs almost 2 metric tons, DDA cars weighed ~0.7 metric tons, now they're around 1.1 metric ton

What? the heaviest of the 5 American cars i have owned was just over 1 metric ton fully fueled with me sitting in it. 

[https://www3.epa.gov/otaq/fetrends.htm](url) 
4060 pounds (1.8 metric tons) is the average of all cars and light trucks.

**Pull request merged**
