### PR TITLE
Reduce usage cost of Insect Wings

### PR DESCRIPTION
**Pull request by KittyTac**
#### Summary
Balance "Reduce usage cost of Insect Wings"

#### Purpose of change
The Insect Wings mutation consumed 17.4 kcal and thirst units per second, which seemed excessive to me from my tests. Using them for a minute left you dehydrated and very hungry which doesn't seem right, and also not reasonable verisimilitude-wise.

#### Describe the solution
I reduced the costs to ~~2~~ 3 kcal and thirst units per second. You will still feel the effects if you overuse it, but at least the mutation is usable now.

#### Describe alternatives you've considered
Leaving as is, or having a slightly higher/lower usage.

#### Testing
Tested, the mutation consumes resources at a lower pace now.

#### Additional context
It gives you the debuffs all at once when you stop using it, rather than giving them gradually. Seems unintended, but I don't know how to fix that bug (heh).

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
That's a rather serious change - more than eight times lower. I'm not against it, but it feels... severe.

**Comment by KittyTac** [comment]
> That's a rather serious change - more than eight times lower. I'm not against it, but it feels... severe.

It was severe in the other direction before. As I said, I'm open for reducing the buff somewhat if desired.

**Comment by Night-Pryanik** [comment]
I can't say for others, but I'm fine with more moderate approach.

**Comment by KittyTac** [comment]
Changed it to 3 resource units/second.

**Comment by Amoebka** [comment]
For reference, the old value translates to a cool 72 kW power drain. This stupid thing is powered by an 11 kW engine:
lossy-page1-462px-Bio-inspired_Big_Dog_quadruped_robot_is_being_developed_as_a_mule_that_can_traverse_difficult_terrain tiff

**Pull request merged**
