### PR TITLE
Fix mapgen crash triggered by toxic dump and hazardous waste sarcophagus

### LINKED ISSUE #31972: Map Spawn Error: Hazardous Waste Sarcophagus
# Describe the bug

The overmap area 'Hazardous Waste Sarcophagus' produces an error when approaching it. After wading through the error spam, the area where the hazardous waste buildings should be is replaced by empty fields.

# Steps To Reproduce

1. Load up the included save.
2. Walk South down the road a bit until you reach the Hazardous Waste Sarcophagus. (It's visible on my map if you somehow get lost).
3. Enter the area it's supposed to be.

# Expected behavior

The hazardous waste sarcophagus to show up.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (latest Win 7 update)
- Game Version: 0.D-5086-g93da2fd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    EXTENDED_BUILDINGS [ext],
    Urban Development [Urban_Development]
]

# Additional context

 DEBUG    : map::saven grid (0,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : failed to generate a submap at 223,276,0
 
 FUNCTION : void map::loadn(int, int, int, bool)
 FILE     : src/map.cpp
 LINE     : 6788

#Save file
[CDDA HazWasSarc Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342189/CDDA.HazWasSarc.Save.zip)

### LINKED ISSUE #32007: Toxic waste dumps fail to generate when you get close and crash when you save there
# Describe the bug

When the overmap calls for a toxic waste dump, I get a bunch of debugmsgs and no toxic waste dump.

# Steps To Reproduce

1. Find a toxic waste dump on the overmap.
2. Get close enough so that it is in your reality bubble.
3. Observe the message spam

BONUS BUG:
4. Attempt to save and quit when on the relevant overmap tile.
5. Observe the crashing!

# Expected behavior
Toxic waste dumps generate, and also I can save my game without it crashing.

# Screenshots
This is supposedly a toxic waste dump in the forest.
Jessica Jammerson __15-53-35_Eastern Standard Time

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5119-g9265810 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3343057/crash.log) from my crash when I tried to save my game.

```
 DEBUG    : map::saven grid (0,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (0,1,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (1,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (1,1,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : failed to generate a submap at 294,150,0
 
 FUNCTION : void map::loadn(int, int, int, bool)
 FILE     : src/map.cpp
 LINE     : 6788

 DEBUG    : map::saven grid (0,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (0,1,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (1,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : map::saven grid (1,1,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : failed to generate a submap at 294,151,0
 
 FUNCTION : void map::loadn(int, int, int, bool)
 FILE     : src/map.cpp
 LINE     : 6788

 DEBUG    : map::saven grid (0,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

```
and those debug messages continue for a while. They seem to be repeating.

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: Bugfixes "Fix mapgen crash triggered by toxic dump and hazardous waste sarcophagus"

#### Purpose of change

Fixes #32007 
Fixes #31972

#### Describe the solution

#31831 updated many overmap terrains and specials to allow rotation, which worked great for the JSON-based locations, but some of the old C++ mapgen locations were doing checks on the overmap terrain id to determine what to render. Unfortunately, rotated terrains and non-rotated terrains end up with different ids, and so these locations would effectively render nothing into the location, which then caused issues when visiting the locations in game and saving/loading the locations.

#### Describe alternatives you've considered

These hardcoded locations should probably be converted to JSON, but this fixes the issue in the near term.

### CODE REVIEW

**Comment by Alicecomma** [comment]
Thanks so much! :)

**Comment by Berkyjay** [comment]
This just started happening to me.  Not sure if it's related but it seems like it.  This happened once when I drove past this specific hazardous waste sarcophagus.  But then it was OK once I reloaded.  Then when I made my way back passed it my game started crashing and now I can't get close to it without the game crashing on me.

Win10
Game build 9794
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3758847/crash.log)

**Comment by ZhilkinSerg** [comment]
Do you have a savegame with reproducible crash?

**Comment by Berkyjay** [comment]
Here ya go.  When you load up the location is to the left of the screen.  I didn't have to walk far before it crashed.

https://drive.google.com/open?id=1W-4RKaAqDJX8iDJWn-tOwa5JKK-7d4z5

Let me know if you need more info.  I was trying to figure out how to print out my mod list.  If you could tell me how to do that I'll get it for you.

**Pull request merged**
