### PR TITLE
Honey, I shrunk the Makarov [RDY]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The Makarov has similar dimensions to the P230. Unless it's supposed to be bigger due to the rail, it is a pocket pistol.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Is it supposed to have almost twice the density of a glock 19?

**Comment by BorkBorkGoesTheCode** [comment]
How does density work? I assumed there were few interactions between volume and weight.

**Comment by Coolthulhu** [comment]
There aren't. You have to specify them explicitly and then check a loaded gun.
Loaded makarov is 0.7kg, loaded glock 19 is 0.8kg.

**Comment by BorkBorkGoesTheCode** [comment]
It's actually lighter than normal according to a quick search.

**Pull request merged**
