### PR TITLE
Make the basic laboratory analysis set recipe accepting large boxes

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Content "Make the basic laboratory analysis set recipe accepting large boxes"```

#### Purpose of change
Since the proper size of a box is hard to find.

#### Describe alternatives you've considered
Adding a box recipe.
Dropping the box requirement altogether.

### CODE REVIEW

**Comment by sharkfinsouperman** [comment]
> Since the proper size of a box is hard to find.

Medium boxes have the same spawn rate in residential homes as large boxes, and medium boxes of toilet paper are very common in washrooms, so I don't understand why this change is necessary or justified.

**Comment by l29ah** [comment]
Just checked 13 washrooms in underground labs and found zero medium boxes. Do i have to get back in a city just to pick a proper box for all the research lab equipment i harvested in the lab?

**Comment by sharkfinsouperman** [comment]
Okay, according to the item locator, they don't spawn in underground labs at all.

This may be nothing more than an oversight when the objects were added. So rather than changing the recipe due to the lack of spawns in underground labs, perhaps it would make more sense to correct the oversight and set toilet paper to spawn inside the labs instead?

**Comment by l29ah** [comment]
I consider requiring a toilet paper box in the recipe for the item that is necessary for mutagen production an oversight (as well).

**Comment by sharkfinsouperman** [comment]
I understand your frustration, but IMO changing the recipe affects the game globally, while adding toilet paper spawns to the lab solves your local issue without having any global effect.

**Comment by I-am-Erk** [comment]
A large cardboard box is big enough to his inside, it's not a reasonable way to carry around an analytical set. Some reasonable solutions:

- add a recipe to make a medium box out of cardboard scraps so you can chop up a large box and build a medium one
- improve spawning of items in an underground lab since they should be overflowing with medium cardboard boxes

This is not a good solution as presented.

**Pull request closed without merging**
