### PR TITLE
Randomized NPC age and height

### LINKED ISSUE #61788: All NPCs are 175cm and 25yrs old
### Is your feature request related to a problem? Please describe.

Currently basically every (randomly generated) NPC is the exact same age and height. This is obviously just an unfinished feature.

### Solution you would like.

NPCs should be varyingly old and tall.

### Describe alternatives you have considered.

Probably using a standard distribution of some sort to determine what is the "normal" age of cataclysm survivors (probably the younger and healthier) and "normal" height per population distributions.

### Additional context

Too lazy to do this myself but it bears mentioning.

### PR DESCRIPTION
**Pull request by Rorkh**
NPC height and age now randomly generates as for character

#### Summary
Features "NPC now have randomized height and age values"

#### Purpose of change
Fixes #61788

#### Describe the solution
Instead of setting fixed value in npc::load_npc_template it's do it in npc::randomize what's called from it and sets the values randomly as for character

#### Testing

1. Enter debug menu
2. Spawning -> Spawn NPC
3. Re-enter debug menu
4. Player -> Edit player/NPC
5. Select spawned NPC
6. Edit description/...
7. Confirm it's works pretty well

#### Additional context
Proof that it's works
proof 1
proof 2

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Stasya is a really tall lass.

**Comment by NetSysFire** [comment]
Cool! I would bump the minimum age to 18 though, juuust to be safe.

For the future, doesnt impact your PR and I do not expect you to implement this, I would love to see survivor demographics done by one of our lore guys. So say 70% of the survivors are 20-30 years old, 25% are 30-50 and the remaining 5% would be 50+ seniors. Could be a nice detail.

**Comment by Rorkh** [comment]
> Cool! I would bump the minimum age to 18 though, juuust to be safe.
> 
> For the future, doesnt impact your PR and I do not expect you to implement this, I would love to see survivor demographics done by one of our lore guys. So say 70% of the survivors are 20-30 years old, 25% are 30-50 and the remaining 5% would be 50+ seniors. Could be a nice detail.

Yeah, will bump soon but don't think this age distribution is possible as world is infinite so NPCs count too.

**Comment by NetSysFire** [comment]
>but don't think this age distribution is possible as world is infinite so NPCs count too.

I meant that there is a higher probability that NPCs are young, since most older people may not be able to escape from a horde due to health and age. So basically in pseudo code:

```
random = randint(1, 100)
if random < 60:
  npc.age = randint(18, 30)
elif random > 60 && random < 95:
  npc.age = randint(31, 45)
else:
  npc.age = randint(46, 60)
```

**Comment by Rorkh** [comment]
> > but don't think this age distribution is possible as world is infinite so NPCs count too.
> 
> I meant that there is a higher probability that NPCs are young, since most older people may not be able to escape from a horde due to health and age. So basically in pseudo code:
> 
> ```
> random = randint(1, 100)
> if random < 60:
>   npc.age = randint(18, 30)
> elif random > 60 && random < 95:
>   npc.age = randint(31, 45)
> else:
>   npc.age = randint(46, 60)
> ```

Oh. Misunderstood. Kinda sounds good and can do it soon.

**Comment by I-am-Erk** [comment]
This is a good change, but I think it should be held off for stable; there's a micro chance of bugs, but the chance remains, and also it's going to need some refining with demographics and things that should really be ongoing as part of an experimental cycle. 

Luckily that's a short wait.

**Pull request merged**
