### PR TITLE
Audit throwing practice tools

### PR DESCRIPTION
**Pull request by bloodbowel**
#### Summary
Features "Adds throwing practice tools"

#### Purpose of change
I noticed a while ago that throwing practice does not include flaking rocks.

#### Describe the solution
I decided to add them, and a couple of other common items that could be used. The full list is:
1.flaking rock
2.pebble
3.brick
4.wood block
5.barb wired baseball (since you have a baseball)
6.lawn dart
7.weighted dart (since I added the lawn dart)

#### Describe alternatives you've considered
If you think anything should be added or removed, comment. Also I was wondering about adding irregularly shaped common objects like chunks of steel. You might smash something and grab a piece if you're holed up somewhere surrounded by zombies. Pretty common thing in my early games.

#### Testing
Tested in debug mode on my computer.

#### Additional context
throwing

### CODE REVIEW

**Comment by RenechCDDA** [comment]
The pebble's too small to properly practice with, it's really not intended for throwing.

**Comment by bloodbowel** [comment]
> The pebble's too small to properly practice with, it's really not intended for throwing.

I thought that too, but it already lets you use a marble and dice which are about the same size, so I included it. They never seemed right to me. What do you think of removing the other two?

**Comment by RenechCDDA** [comment]
Marble and dice are right out IMO

Ball bearings can be of any size, and ours seems to be really small so you can nix that too.

**Comment by bloodbowel** [comment]
I removed them. Should I actually remove them in a separate pull request for clarity? Or is it fine to do here?

**Comment by RenechCDDA** [comment]
I think it's fine to do it all here. You're touching the same recipe, so all this changes are highly related. If you want, you could change the title to something like "Audit throwing practice tools" so it's that tiny tiny bit more accurate. Not a big deal though.

**Pull request merged**
