### PR TITLE
Implements .410 and .45 Long Colt

### PR DESCRIPTION
**Pull request by DangerNoodle**
Implements .410 bore and .45 Long Colt ammunition, and allows the Taurus Raging Judge to use both in addition to .454 Casull.

Additionally implements a few firearms to use them. Single-barrel youth shotgun as a basic .410 shotgun, a Bond Arms derringer as a compact weapon allowing shotshells and pistol rounds, the classic Single Action Army, a reproduction Colt Lightning (providing a pistol-caliber rifle role), and the M6 Aircrew Survival Weapon as a combination weapon (.22 LR/.410 bore).

Future plans include a .410 conversion kit and _possibly_ a Cowboy Action Shooting profession, but for now these are already more than enough additions for a single pull request.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
There is a redundant "makes makes" in the .410 description.

**Comment by DangerNoodle** [comment]
Ah, apologies for that.

**Comment by BorkBorkGoesTheCode** [comment]
>Ah, apologies for that.

I wasn't offended, it looked like a typo, so I noted it.

**Comment by DangerNoodle** [comment]
Will fix the typo along with double-checking all files and lintfixing.

**Comment by DangerNoodle** [comment]
Also observed, I do not recall removing the Mossberg 500 and replacing it with the SKS, in the survival weapons item group.

**Comment by BorkBorkGoesTheCode** [comment]
Check your branch, you may have unknowingly moved between branches due to how GitHub handles some things.

**Comment by DangerNoodle** [comment]
Strange, but both pull requests I am working on were based off the same master branch, and the other pull request contains no item group changes.

**Comment by BorkBorkGoesTheCode** [comment]
Did you change that itemgroup in any other branch? It might be a good idea to check for recent account activity.

**Comment by DangerNoodle** [comment]
This is the first instance of my doing so. I am assuming I did so by mistake and failed to notice. In the meantime, will also fix incorrect name for the .410 pipe shotgun, add itemgroup entry, and recipe. I briefly forgot that I added that, it seems.

**Comment by DangerNoodle** [comment]
I will futhermore want to balance .410 slugs to be consistent with https://github.com/CleverRaven/Cataclysm-DDA/pull/18981, but this will depend on @Coolthulhu's feedback regarding balancing.

**Comment by BorkBorkGoesTheCode** [comment]
I would love it if the internal magazine system could be expanded to include stripper clips and moon clips: https://en.wikipedia.org/wiki/Stripper_clip

**Comment by DangerNoodle** [comment]
It would be possible to implement moon clips as a magazine, but stripper clips and speed loaders would require a separate system. They would have to be optional, bypass the 'RELOAD_ONE' effect when used, and transfer their ammunition without being loaded whole into the weapon.

**Comment by BorkBorkGoesTheCode** [comment]
Are you ready?

**Comment by BorkBorkGoesTheCode** [comment]
The only problem I can see at the moment is the possible typo in the Single Action Army ID: "colt_~~ssa~~"

**Comment by DangerNoodle** [comment]
Ah, that should be the only remaining anomaly, will fix that now.

**Comment by DangerNoodle** [comment]
Attempting to at least, Github client is working slowly due to connection issues.

**Comment by DangerNoodle** [comment]
And that should be it. While it will be nice to have feedback on this, I have also been waiting for https://github.com/CleverRaven/Cataclysm-DDA/pull/18646.

**Comment by mugling** [comment]
Very against this. This just adds unnecessary complexity for no improvement in gameplay. The purpose of alternate ammo types was to provide novel items, not simulate the minutiae.

**Comment by mugling** [comment]
Not strictly the same problem as #18972 but you might want to check there and also #18571.

Closing as you now have thumbs down from multiple developers. This would however be reasonable mod content and you might wish to collaborate with @BorkBorkGoesTheCode on this. If you wanted to consolidate a number of extra item mods into a 'more guns' pack this would also be a welcome change

**Comment by pisskop** [comment]
id love to see this as a mod package

**Comment by mugling** [comment]
> id love to see this as a mod package

Yes, an extended gun mod would be welcome and contributors have much more scope for changes there

**Comment by DangerNoodle** [comment]
I understand your reasoning, and might be up to implement this as mod content if @BorkBorkGoesTheCode wishes to do so.

Though stating you are closing it due to receiving a thumbs down from Illi-kun (when Rivet also gave it a thumbs up) does not seem like sound reasoning. I had assumed you were closing it due to quite understandable objections about this becoming mainline content.

**Comment by mugling** [comment]
I closed it because it was contrary to #18571 but could easily be a mod. It's fair to point out that another developer holds that viewpoint.

**Comment by DangerNoodle** [comment]
Understandable, yes.

For the meantime, I would rather wait until feedback from BorkBorkGoesTheCode to see what to do with this content. I have also still been waiting for feedback on https://github.com/CleverRaven/Cataclysm-DDA/pull/18646, as I prefer to avoid handling multiple pull requests simultaneously.

**Comment by mugling** [comment]
Did you know you can submit PR's against another developers branch. This is one route by which you could collaborate?

**Comment by DangerNoodle** [comment]
I was unaware of this, actually.

**Comment by BorkBorkGoesTheCode** [comment]
>For the meantime, I would rather wait until feedback from BorkBorkGoesTheCode to see what to do with this content. I have also still been waiting for feedback on #18646, as I prefer to avoid handling multiple pull requests simultaneously.

The .40 PR is useless as mod content due to a bug in copy-from.

I would like to add some version of these to the game.

**Comment by mugling** [comment]
> The .40 PR is useless as mod content due to a bug in copy-from.

What is the bug?

**Comment by DangerNoodle** [comment]
What would be the bug in question? It could be possible to alter items using 'edit-mode' instead, if that is the problem. Or the use of overriding content if worst comes to worst, as that is likely the oldest modding method available in CDDA, and should still work if no alternative will function.

**Comment by DangerNoodle** [comment]
For now though, will not be on until later. Will have to see what to do when I get a chance.

**Comment by BorkBorkGoesTheCode** [comment]
There were two bugs:

1. I couldn't redefine the 10mm as a member of the 10mm_auto ammo_type within a mod. I kept getting a wrong ammo message. The ammo types were set up properly, and the ammo was set up properly:
DEBUG:               void Item_factory::check_definitions() const
FILE:                    src/Item_factory.cpp
LINE:                   828

2. When I made a .22 mod to test the BB rebalance, the .22 CB dispersion was overwriting the .22 rat-shot dispersion.

The issue might have been caused by a corrupted file, since I cannot replicate the bug in a new experimental using new files.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle I am willing to collaborate.

**Comment by DangerNoodle** [comment]
That is peculiar. I am unsure how to resolve either of those. What method was used to edit the 10mm ammunition? Copy-from, edit-mode, or direct override? For this pull request at least it should be easier to implement in a mod, as the Raging Judge and .454 Casull ammunition does not need to be altered to add these.

It would be interesting to collaborate on this, though unsure how to submit against another contributor's branch.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle , do you have a Cataclysm-DDA forum account?

Have you tried creating a PR targeting my repository?

**Comment by DangerNoodle** [comment]
I do not have a forum account, no. And I am still uncertain how to target your repository like that.

**Comment by BorkBorkGoesTheCode** [comment]
I am having trouble targeting your repository.

Could you sign up for a forum account?

**Comment by DangerNoodle** [comment]
I do not know if I have much use for a forum account, but if you need to do so over private message, then so be it.

It might be easier for one of us to manually overview the other's content and integrate it in a pull request, if targeting a repository is difficult. If I recall, the only thing your earlier pull request did initially was add a new ammo type and change the ammo types used by 10mm ammo and one weapon, correct?

**Comment by BorkBorkGoesTheCode** [comment]
It also changed the 10mm cartridge into one of the heavier versions.

**Comment by DangerNoodle** [comment]
Ah, peculiar, but can still be incorporated into a pull request I hope. Uncertain what was causing errors if you attempted to move it to a mod.

Is 10mm Auto the default ammunition type for .40 Switch and Wesson? If so, that is likely it.

**Comment by BorkBorkGoesTheCode** [comment]
>Is 10mm Auto the default ammunition type for .40 Switch and Wesson? If so, that is likely it.

No, the .40 is default.

**Comment by DangerNoodle** [comment]
That averts one of the usual expected causes. I will need to look at the content of that pull request.

**Comment by DangerNoodle** [comment]
Tested a mod shift of the content of your pull request so far, though I forgot to implement the conversion kits. So far it loaded in Build 5780 without issue. In fact the only problem I am having is how to format multiple author credits in the modinfo file.

**Comment by BorkBorkGoesTheCode** [comment]
>Tested a mod shift of the content of your pull request so far, though I forgot to implement the conversion kits. So far it loaded in Build 5780 without issue. In fact the only problem I am having is how to format multiple author credits in the modinfo file.


That confirms it was a corrupted file on my end.

You could use this:  `"authors": [ "foo", "bar" ], `where foo and bar are the author's names. illi-kun taught me this.

**Comment by DangerNoodle** [comment]
Ah, I might have retained singular author instead of authors when changing it.

The only issue I have now encountered is that the 10mm Auto ammunition is retaining the ammunition type added to .40 Smith and Wesson. I am attempting to see if using 'edit_mode' will work.

**Comment by DangerNoodle** [comment]
Ahah, it would seem that recursive copy-from bypasses this. It requires 10mm Auto to copy from itself and tell it to remove the .40 ammo type inherited from its parent ammunition. It seems that the handloaded version additionally requires to recursively copy itself.

**Comment by illi-kun** [comment]
Re: thumb down
I didn't put a comment about it since mugling expressed my idea already: it's a great additional for gun nuts but it's extra complexity with no obvious benefit for a common player. So mod is the best place for it.

**Comment by DangerNoodle** [comment]
Understandable. Regarding that idea, I have also managed to streamline the changes to .40 S&W and 10mm ammunition via the use of recursive copy-from. I will need to see whether the change to the .40 revolver can be handled in the same way.

If I have time later on, I can present a pull request if @BorkBorkGoesTheCode is okay with it.

**Comment by BorkBorkGoesTheCode** [comment]
Go ahead and send in a PR.

**Comment by DangerNoodle** [comment]
Very well then, presently load-testing and checking that everything is as intended, then will pull it.

**Comment by BorkBorkGoesTheCode** [comment]
If you are interested, I also have a .357 magnum and .38 super modification.

**Comment by DangerNoodle** [comment]
Would be interesting. Though I have already encountered an issue. It seems at some point a load error was caused by my streamlining of the changes to .40 S&W and 10mm, when before it allowed it without issue. It is either my having since altered reloaded ammunition, or the result of updating build.

**Comment by DangerNoodle** [comment]
It is citing a circular dependency error, but not informing me of what file it is in.

**Pull request closed without merging**
