### PR TITLE
Storage cells and car recharger changes

### PR DESCRIPTION
**Pull request by Core0verload**
Storage cells are now modular for purposes of assembly and disassembly. Big storage cells are made out of 4 medium cells. Medium cells are made out of 6 small cells. That's how power cells in modern e-cars are made IRL. 

Rechargeable power cell tool mod is removed in favor of UPS power mod. It's replaced by UPS mod in spawn and removed from crafting. Existing rechargeable mods will install UPS mod. Existing modded tools will charge in car recharger, but not in UPS. Car-mounted recharger is upgraded to the charging speed of UPS power port (it was ten times slower), and renamed to "UPS-compatible recharging station".

Internal UPS CBM is now craftable - it requies an UPS-compatible recharging station, 2 power converters and 1 burnt out bionics. Recipe is found in "Lab journal - Herrera" and "2XI design binder-CLASSIFIED".

Other changes:
- Small storage cells are no longer craftable. DIY lead-acid batteries are possible, but storage cells are something closer to modern Li-Po I think. Anyway, there is no point in crafting them when you can get 24 small cells out of one big storage cell.
- You can't cut up storage cells.
- Storage cells size, weight and capacity are a bit more in line. Small and medium cells have more capacity and less volume, big cell has more volume.
- Lead cells weight less. 12kg was way too much for a motorbike power cell.
- Cordless drill now uses regular batteries, just like every other tool. I changed it because it's desc stated that it was reachargeable but it actually wasn't. It can be unloaded, and it has a crafting recipe.
- Small cells are used in UPS and laptop crafting/dissassembly.

### CODE REVIEW

**Comment by kevingranade** [comment]
Re: power armor, I'm thinking of making them rely on plutonium cells, I
don't think their power usage has the intended effect of making their use a
precious resource as intended now that you can harvest so much charge from
vehicles.

**Comment by Core0verload** [comment]
For me main limiter was how power armor is insanely hard to get. And even if you have your armor, your storage space sucks unless you have a hauling frame too because it blocks your storage items.

I checked - no, Internal UPS isn't powering power armor. And my update doesn't add any way to harvest car power. You can't mod UPS to be UPS-powered, and you can't charge your bionics from car.

**Comment by tyrael93** [comment]
Love it! Great job.

**Comment by Coolthulhu** [comment]
Those "modular" power cells sound really futuristic. Is this how it works IRL?

Small storage battery can store 2500 charges of battery now. That's 25x as volume-efficient as handheld batteries.

The idea itself isn't bad, but the direction of vehicle battery storage should be "NERF HARD" rather than buff, especially when it comes to weight. IRL electric cars need batteries with weight measured in hundreds of kilograms, not tens.

**Comment by Core0verload** [comment]
@Coolthulhu, yes. Real life Tesla car uses a ton of connected NCR18650A cells - they are a bit bigger than AA cells. Older EVs use packs lead-acid or gel cells. [Sizes of power cell modules of various EVs.](https://chargedevs.com/wp-content/uploads/2015/01/Teslas-Batteries-Cell-Comparison.jpg) 

I always thought that "100 power cells" are actually one AA-sized 3V cell at 100% of charge. 1 volume is too much for an AA cell, it must be 0.5 or 0.25. For comparsion, a crowbar is only 4 volume, and it's obviously bigger than 4 AAs. With "100 batteries  = 0.25 volume" small storage battery only 6x as volume-efficient as handheld batteries. I think we can just say "they are advanced nano Li-Pol cells of the future" at this point. Hey, we have a plutonium reactor-powered coffee machine, why can't we have a bit of future in our power cells?

**Comment by Coolthulhu** [comment]
> And the main reason why storage cells have that insane capacity is that any electrical engine in the game is insanely power hungry. Even car controls consume 25 cells per tick. 1 car charge unit != 1 power cell.

Car controls only consume power when producing light.
And even when they do, they take 15 turns to consume a single charge of the cell (because of `power_to_epower` conversion).
If they are supposed to have insane capacity, they should also have insane weight. Currently (I mean in master, before the buff) power storage only "costs" grinding batteries. There is pretty much no downside to installing extra 20 batteries in all possible slots. Here you make the problem even worse by making the batteries lighter.

**Comment by Core0verload** [comment]
Have the extra weight ever stopped anyone from installing 5x10 storage cells on their solar RVs?

**Comment by kevingranade** [comment]
>Hey, we have a plutonium reactor-powered coffee machine, why can't we have
a bit of future in our power cells?

Because we try to keep the futuristic things like atomic whatevers separate
from the mundane things like car batteries.

> Have the extra weight ever stopped anyone from installing 5x10 storage
cells on their solar RVs?

I don't follow, if you think the extra weight isn't a problem, then keep it
as coolthulu (and myself) are asking.

**Comment by Core0verload** [comment]
Weight isn't a problem, consistency is. Storage cell can't weight two times more than it's components.

**Comment by kevingranade** [comment]
IIUC the storage batteries are based on real electric car battery packs, so if they are inconsistent with their components, it means they are not including enough components, not that they are too heavy.
A quick search indicates that the weights in current electric cars are much, much higher than what we are depicting in game.  Nissan leaf 600lbs, Tesla model S 1,200 lbs, Chevrolet Volt 435lbs.  The storage battery should be about 10x heavier than it is, not lighter.
These are simple facts, start there and work backward if you want the chain of items to be consistent, though in general these things shouldn't be craftable at all, just used as is.

**Comment by Skidborg** [comment]
If we can get a decision on how much these things should weigh I'm looking forward to the rest of the proposed changes going in.

**Comment by kevingranade** [comment]
We already said, 10x the current weight.

**Comment by Soadreqm** [comment]
@kevingranade 
>we try to keep the futuristic things like atomic whatevers separate from the mundane things like car batteries.
I thought the car batteries were supposed to be at least a little bit futuristic. Not "NUCLEAR COFFEE" futuristic, but "viable solar cars" futuristic. Like, real-world electric cars aren't very common at the moment, and battery limitations are a major reason for this. It'd be somewhat incongruous if they didn't have better batteries in the future.

(What the fuck is even up with that coffeemaker, though? How does a nuclear reactor help you make stronger coffee?)

Anyway, I'm not sure if the thing with people filling their cars up with dozens of batteries is even solvable. In a post-apocalyptic world, a car's maximum power capacity is just more important. No matter how much they weight, it'll always be beneficial to carry more of them. Even their cost is no longer relevant, since the economy has collapsed. To make battery weight in any way meaningful, you'll also have to seriously tone down the power of electric motors, and at that point people are just going to stop using electric cars since being able to carry several tons of junk is the main benefit of having a car at all.

**Comment by kevingranade** [comment]
On Jan 1, 2016 7:25 PM, "Soadreqm" <notifications@github.com> wrote:
> ... at that point people are just going to stop using electric cars since
being able to carry several tons of junk is the main benefit of having a
car at all.

You say that like it's a bad thing...
Seriously, if realistic battery weight/capacity  plus realistic motor
efficiency means pure electric megamobiles are impractical, that's fine. We
actively want different engine types to have different niches.

**Comment by Skidborg** [comment]
It's not even that big of a drawback since you can install a diesel engine for cruising and and also an electric for sneaking if you need to.

**Comment by Core0verload** [comment]
I increased large storage cell's weight to old values. #fuckthisshit

Can it now be merged without causing any balance drama?

**Comment by Coolthulhu** [comment]
> Can it be merged without causing any balance drama?

There are merge conflicts now, you have to resolve those before it's mergeable.

Also, you left the buffed values for two other batteries - motorcycle and car. Those are quite bad for balance already because you can stack them all on the same tile. Their lower storage/weight ratio was helping with that a tiny bit, with your current stats they are only ~20% less efficient.

**Comment by Core0verload** [comment]
Merge conflicts were from #14765, they are resolved now. Please, merge this before #14778 will add more conflicts.

I returned car cell weight to old value, but motorbike battery's weight remains reduced /2. Who uses 13kg batteries on motorbikes? If it would cause any ISSUES with motherfucking BALANCE...

**Comment by Soadreqm** [comment]
How about reducing the power capacity? The bikes will start just fine with smaller batteries, and that'd make them less attractive for piling on your car by the dozen.

**Pull request merged**
