### PR TITLE
Give G80 necessary range

### LINKED ISSUE #19083: H&K G80 Railgun has zero range
Neither the gun nor the ammo it uses specify a range, so it ends up having zero range.

### PR DESCRIPTION
**Pull request by Mecares**
0 is a bit low for combined range of gun and ammo.
Fixes #19083

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Since the range cap is only intended to be temporary, could you increase range to 60?

**Comment by mugling** [comment]
Something is wrong - you aren't supposed to need to specify `range` at all - it should depend on `dispersion`?

**Comment by BorkBorkGoesTheCode** [comment]
The ammo lacks range, due to the fact that the railgun provides the propulsive force.

**Comment by mugling** [comment]
Yes, but that still shouldn't make a difference - something is wrong with the implementation

**Comment by Mecares** [comment]
Could it be caused by the removal of the powder flag?

**Comment by mugling** [comment]
Not a bad suggestion but I don't think so

**Comment by mutability** [comment]
`Creature::gun_current_range()` (both the version before the dispersion changes, and the new version) caps the returned range to `item::gun_range()` which uses the item/ammo/gunmod range data.

For all current guns this is what limits `Creature::gun_engagement_range(.. engagement::maximum ..)`, the dispersion-based calculation is always greater than the item-based maximum range.

**Pull request merged**
