### PR TITLE
Ignore most paths for MSVC workflows

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
None

#### Purpose of change

The msvc (Cataclysm and object creator) workflows are going off for changes in a number of subdirectories that were not needed.

#### Describe the solution

Add these to the ignore lists in the workflow .yml files.

#### Testing

CI.

#### Additional context

Ping: @akrieger?

### CODE REVIEW

**Comment by akrieger** [comment]
Seems reasonable.

**Comment by akrieger** [comment]
I can't seem to figure out how to put suggestions on the code (or it just won't let me do it outside the immediate context area) except to suggest to keep the ignore list alpha sorted.

**Comment by actual-nh** [comment]
> I can't seem to figure out how to put suggestions on the code (or it just won't let me do it outside the immediate context area) except to suggest to keep the ignore list alpha sorted.

I had put data at the bottom to remind us that it may need to be removed. I suppose it wouldn't be for the object creator, so I'll change that part; yes, Github is annoying about that.

**Comment by BrettDong** [comment]
`lang` directory can also be ignored.

**Comment by jbytheway** [comment]
The object creator build does depend on all the source, so I don't think we should skip builds for that.  Maybe we could only rebuild it when a header changes; that should catch most things.

**Pull request merged**
