### PR TITLE
removing leftovers of bionics from doctor's office

### PR DESCRIPTION
**Pull request by OmegaCenti**
#### Summary
Bugfixes "removing leftovers of bionics from doctor's office from base game ~~and No Hope mod~~ reverted No Hope Changes"

#### Purpose of change
I was instructed by moderators and collaborators that these changes were needed to office_doctor, ~~as well as in No Hope mod~~ reverted changes to No Hope Mod

#### Testing
I was able to play the game without error

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by Venera3** [comment]
You don't need to remove the anesthetic, this variant could comfortably turn into a small day surgery setup - operating table in place of the autodoc, an autoclave with surgery equipment in the storage along with some drugs+anesthetic.

**Comment by Adamas12** [comment]
As far as I know there isn't any consistent way of finding anaesthetic outside of Dr's offices, and seeing as it's integral to an entire faction as well as the fact that should be in a drs office is a bit odd... you've left people with the option of finding up to 20 zoos or lab hunting for one the first quests they can get.

**Comment by Night-Pryanik** [comment]
What's the rationale for removing bionics, anesthetics and autodoc from the mod?

**Review by Maleclypse — CHANGES_REQUESTED** [review]
After Night's comment I went to look and see if the readme in No Hope said anything about CBMs and  it says the following `Returned CBM loot in most places it was removed from (electronic stores, toxic dumps, sewage treatment plants etc).` so it's not appropriate to remove from No Hope.

**Comment by OmegaCenti** [comment]
> After Night's comment I went to look and see if the readme in No Hope said anything about CBMs and it says the following `Returned CBM loot in most places it was removed from (electronic stores, toxic dumps, sewage treatment plants etc).` so it's not appropriate to remove from No Hope.

alright, should I remove that change and push again?

**Comment by OmegaCenti** [comment]
> What's the rationale for removing bionics, anesthetics and autodoc from the mod?

I was instructed to by Guardian! XD I will repush without those changes

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
