### PR TITLE
Remove the Chop Tree Trunk Into Planks construction

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Interface "Remove the Chop Tree Trunk Into Planks construction option"```

#### Purpose of change
as it's inconsistent and can be done via axes' action menu
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/26729

### CODE REVIEW

**Comment by EddiTheBambi** [comment]
Worth taking a loot at the stone adze, I believe it doesn't have the action menu option.

**Comment by macrosblackd** [comment]
The construction menu action is used to chop a tree trunk directly into planks - this action is basically 2 steps in one.

**Comment by I-am-Erk** [comment]
Have you addressed the issue that no skills are required by the iuse action and that it has an incorrect timeframe?

**Comment by l29ah** [comment]
I don't see zero skill requirement as a problem (see https://www.youtube.com/watch?v=-JcWY0rjePU), and the iuse action time requirement is inherited by the construction job anyway.

**Comment by macrosblackd** [comment]
So - what's happening is it's taking 60 minutes to chop the tree trunk into logs. It THEN calls chop into planks for EACH log. This construction option isn't entirely redundant, it actually saves players a few key presses to go from a tree trunk to planks.

**Comment by I-am-Erk** [comment]
I wouldn't describe riving a log by hand as something that takes no skill.
http://www.hurstwic.org/history/articles/manufacturing/text/viking_woodworking_riving.htm

It is not something that I would assume someone with no knowledge of wood and woodworking would even know where to start.

**Comment by l29ah** [comment]
Well, we already have stone axe, stone hand axe and stone metal axe that are cheap to make and require zero skill to make planks.

**Comment by I-am-Erk** [comment]
That is the issue I am talking about, which I also referenced in your issue report. While the iuse action may be the preferred way to make planks from trunks, this should be a skill based action. If you're going to merge the two ways of doing it, you should probably be solving that discrepancy as well.

**Comment by I-am-Erk** [comment]
Hm, someone else has pointed out to me that the recipe also can be used to direct NPC actions to do this for you. I really don't think it ought to be obsoleted; the requirements and yields of the two actions should be made the same, though.

**Comment by kevingranade** [comment]
What needs to happen is make them consistent, which is apply the skill requirement to both, base the speed on the construction, etc, not eliminate one.

**Comment by nexusmrsep** [comment]
As I've said previously I'd see it rather as a long action invoked from the items. All the initial requirements can be then placed into iuse template lumber() that can use variants for different tools and materials and it would setup an action resolved later by action_do_turn and action_finish governed by action_handlers.cpp. In my opinion only then would removing construction option be valid. Why? This PR does not address the problem with 'p.moves -= 20_minutes', and that's the main part of the problem.
Unfortunately I have no time lately to help with solving the problem directly, but I hope you will find my advice helpful.

**Pull request closed without merging**
