### PR TITLE
0.e merge

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Backport a selection of bugfixes to the 0.E branch for a point release.

#### Additional context
Probably best to rebase.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Could I suggest adding #39152 to this list?

**Comment by kevingranade** [comment]
Suggestions for backports are welcome, I did a scan over the commits but I could easily miss ones that don't have commit messages that look like bugfixes.

**Comment by Qrox** [comment]
#39238 also fixes a crash on 0.E.

**Comment by ZhilkinSerg** [comment]
@kevingranade:

I've added some parameters to job https://ci.narc.ro/job/Cataclysm-Android/, so we can manually build any branch with necessary parameters and it will do everything we do in automatic scripts (upload artifacts to Github Releases page and Playstore).

image

Do you want me to update job https://ci.narc.ro/job/Cataclysm-Matrix/ as well, so we could build updated 0.E artifacts (and other branches in the future) on-demand?

**Comment by Qrox** [comment]
#39335 #39342 #39386 #39389 #39408 I think these can also be backported to 0.E

**Comment by anothersimulacrum** [comment]
Weren't those issues caused by #38026, which was merged after 0.E?

**Comment by Qrox** [comment]
Yep you're right, I saw the commit time was 2 months ago so I thought it was merged before 0.E while it wasn't.

**Comment by kevingranade** [comment]
@ZhilkinSerg yes please, I'm going to want to do at least one 0.E point release, and that will be much easier than trying to use a different build system.

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ZhilkinSerg yes please, I'm going to want to do at least one 0.E point release, and that will be much easier than trying to use a different build system.

I've did it, so we can try building `refs/heads/0.E-branch` and see if it works when Jenkins is done with current builds.

image

**Pull request merged**
