### PR TITLE
Update power_leech.json

### PR DESCRIPTION
**Pull request by Perset**
#### Summary
Content "Remove leech plants' lightning arc attacks"

#### Purpose of change
Same reasoning as the removal from skeletal creatures. Their status as extradimensional creatures did not create exception, apparently.

#### Describe the solution
I removed the "gun" special attacks from their json files.

#### Describe alternatives you've considered
Leaving it in or changing it to be more palatable, but I'm not sure what will satisfy palette in this case.

#### Testing
I removed the attacks in my own game, then started Cranberry's leech mission: went as expected, no lightning balls and no error messages.

#### Additional context
Feel absolutely free to comment and criticize.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Can you please provide a link to where this was discussed? I dont believe removing this ranged attack to be a good idea.

**Comment by Perset** [comment]
> Can you please provide a link to where this was discussed? I dont believe removing this ranged attack to be a good idea.

It was "discussed" in discord. I asked whether the leeches were magical enough to still get lightning spam, and Kevin said "They're keeping it so far". This was followed by a coded encouragement to contribute by another regular, and here we are. I'm not sure I want to take the seconds to astyle those lines correctly if this is gonna encounter resistance, though. 

Do you think leech plants are magical enough to spam lightning like crazy while they generate infinite numbers of similarly lightning-spamming, ambulatory plants? Now that I think on it, they break physics in like six ways, why the fuck'd they need to "leech" power from anything?

**Comment by Venera3** [comment]
Their numbers and behavior otherwise is not relevant to the discussion at hand.

They are weird nether critters with a short-range shock and not really much otherwise, "me no likey" is not really a good enough argument to remove it without replacement.

**Comment by John-Candlebury** [comment]
> Do you think leech plants are magical enough to spam lightning like crazy while they generate infinite numbers of similarly lightning-spamming, ambulatory plants? Now that I think on it, they break physics in like six ways, why the fuck'd they need to "leech" power from anything?

Making things expand off-screen at a reasonable pace is an unsolved problem in the codebase. They spawn rapidly to mitigate this and allow some expansion like fungaloids do.

Yes I do think they are magical enough to keep  given they are strange plants made of "meat" that take energy from the EM spectrum rather than light. I dont if the idea behind removing electric attacks is that nothing should be able to arc electricy through the air to a specific target, then the ability can be removed from the plants but otherwise I think they should keep it.

Most of the enemies here use the electric gun to EMP the player at melee ranges (0,2 counting spears). This shouldnt be removed enven if the arcing electricity is.

**Comment by Perset** [comment]
> Yes I do think they are magical enough to keep given they are strange plants made of "meat" that take energy from the EM spectrum rather than light. I dont if the idea behind removing electric attacks is that nothing should be able to arc electricy through the air to a specific target, then the ability can be removed from the plants but otherwise I think they should keep it.
> 
> Most of the enemies here use the electric gun to EMP the player at melee ranges (0,2 counting spears). This shouldnt be removed enven if the arcing electricity is.

All of them have at least 2 tiles of range, and the stationary plants far longer. 

Plz describe what exactly what "the EM spectrum rather than light" is, I clearly am way out of touch on these terms.

**Comment by I-am-Erk** [comment]
These are weird nether creatures, they're basically not constrained by most bounds of realism. They should instead be balanced purely to gameplay, and as far as I know, their gameplay is in the right place.

**Pull request closed without merging**
