### PR TITLE
Adding dead college kids to map specials [CR]

### PR DESCRIPTION
**Pull request by KiwiTrinsic**
This adds another map special much along the lines of the groups of dead scientists or soldiers. However, in this case it is the horror flick classic group of dead college students who ran into a psychopathic killer or supernatural danger... or in Cataclysm's case, netherworld creatures. There are three item groups they can be spawned with, depending if they were heading to a cabin in the woods, to a lake, or to a sporting event. I've set the probabilities of them showing up to be slightly higher than the chance of finding dead scientists.

Does that probability sound correct? And are there any obvious items that should be added to their spawned items?

### CODE REVIEW

**Comment by kevingranade** [comment]
Cute idea, love it.

**Comment by Rivet-the-Zombie** [comment]
Good stuff, @KiwiTrinsic!

**Comment by KiwiTrinsic** [comment]
Thanks! I figured it would add a bit more flavor and also dilute some of the rare items drops that can be found with the scientists and soldiers.

**Comment by Zireael07** [comment]
Great idea!

**Comment by DavidKeaton** [comment]
was gonna add a special myself :-) nicely done

**Comment by KiwiTrinsic** [comment]
@DavidKeaton Great! Are you still planning to add one? I've been thinking about doing some improvements to the specials handling code to move it closer to jsonizing. I can hold off on that until after you've added any you were thinking about though to prevent merging problems.

**Comment by DavidKeaton** [comment]
by all means do your additions first! I still want to add, but I can wait bud! :-)

**Comment by Coolthulhu** [comment]
I can't get it to generate. Is there any good way to test mapgen specials other than trying to regenerate a tile that has good chances over and over?

**Comment by DavidKeaton** [comment]
perhaps a debug routine is in order.

**Comment by KiwiTrinsic** [comment]
When I was testing it, I had added an extra zero to the end of the chances for them in overmap.cpp. I agree that there should be a better way to do that though, especially for testing things that only happen in very rare probabilities.

**Pull request merged**
