### PR TITLE
Obsolete flaming weapons

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Content "Obsolete flaming weapons"

#### Purpose of change
These items weren't feasible and aren't suitable for core.

#### Describe the solution
Obsolete flaming weapons and recipes for them. After 0.E. the code in the engine for these should be removed.

#### Testing
Game loads without errors.

### CODE REVIEW

**Comment by Mecares** [comment]
I agree they do not fit well into the core game, but wouldn't be crazy cataclysm a reasonable place for them?

**Comment by sayke** [comment]
Wouldn't they fit into Aftershock too?

**Comment by anothersimulacrum** [comment]
No? They aren't sci-fi, they're just wacky.

**Comment by I-am-Erk** [comment]
I'd support these going to Crazy Cataclysm. They're crazy, and many are quite humorous. I really don't want to see the Flammenschwert go.

**Comment by Mister-Cultist** [comment]
take them out of core if you must but put em in crazy

**Pull request merged**
