### PR TITLE
Container adjustments - plastic tub volume increase, soda spawns in 0.5 L and 2 L bottles, and styrofoam cups -> paper cups

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Content "Soda may uncommonly spawn in two-liter bottles, and more commonly in half-liter bottles."```  

#### Describe the solution
* Plastic tub volume and capacity increased from 4 L -> 4.25 L
* Styrofoam cups are now paper cups
* Soda now spawns in varied containers
  * Vending machines stock plastic bottles instead of cans
  * Most sources of soda uncommonly drop two-liter bottles of the soda instead of the can
  * Soda weighting has been adjusted to be more or less the same spawn rate of soda, just sometimes in other containers
  * Mansion food hoards have glass bottles (mansion people, what can you do)

#### Purpose of change
* The plastic tubs at my local supermarket appear to contain 4.25 L of ice cream instead of 4 L like I thought, so I adjusted the volume accordingly since those tubs are mass-produced and found all across the country (at least, in the states I've been in.)
* Styrofoam gives off toxic fumes when burned. This would be an interesting interaction, but for the meantime, renaming them to paper cups helps keep reality consistent.
* Soda only ever spawning in cans felt weird to me. I felt that it was okay to spawn it in greater quantities since it offers little quench and is more believable to do so. Additionally, I haven't seen any vending machines in the US that stock cans over plastic bottles, nor any grocery stores that sell by the can. Glass bottles of soda in mansions are referencing old-timey soda bottles, which are uncommon, but not enough that a neurotic food-hoarding mansion owner couldn't stockpile them.

### CODE REVIEW

**Comment by woutershep** [comment]
Github text incorrectly states plastic cups.

**Comment by alanbrady** [comment]
When/if styrofoam cups get added back someone could give them insulation as well, which seems mildly useful.

**Comment by kevingranade** [comment]
Leave the styrofoam cups, we're not going to have item id styrofoam_cup named "paper cup" just because one particular property isn't modeled yet.  If you want paper cups represented they need to be added as a new item, and I could certainly see swapping some styrofoam cup spawns out for paper cups.

**Comment by kevingranade** [comment]
Squashed and merged after removing the paper cup changes.

**Pull request closed without merging**
