### PR TITLE
fix: nerf adhesive bandages' gravitational effects

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
Today I was very surprised when I noticed that a bunch of adhesive bandages ~50 ranked among the heaviest items in my inventory.

Adhesive bandages are heavier than many types of bullets, a bit over 4 times more heavy than 9mm rounds

a whooping 40 grams per item

I happen to have a couple of these <https://i5.walmartimages.com/asr/0a49f4b5-6caf-41f7-85a6-06409b7ef2fa_1.2eecc6d7236030d334084ff052efc799.jpeg> adhesive bandages on my wallet and took them out for some very serious "scientific testing" and I determined their weight and volume to be around ~2 grams and ml. Why not

#### Describe the solution
Since charges are a problem (see comments) I just remove the charges from the item definition and changed all spawning instances to use count, recipe was changes as well, they are cheaper to make since you only get one item per recipe, a bit of cotton and tape

#### Describe alternatives you've considered
Title: prevent adhesive bandage fueled gravitational singularities

#### Additional context
I am having a lot of fun

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]
I noticed above that medical grade amphetamines have a volume of 250 which is probably a relic of when 250 ml was the smallest volume.

**Comment by GuardianDll** [comment]
real volume = `volume/charges`
in your case the bandage has weight 2 g and 0.2 ml
for example https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/ammo/223.json#L8

**Comment by casswedson** [comment]
Here is what I see on master
Screenshot from 2022-05-27 17-05-02
one unit of adhesive bandage weighs 0.04 kilograms -> 40 grams
Here is defined as 40 grams, so it can't be doing real volume = volume/charges
<https://github.com/CleverRaven/Cataclysm-DDA/blob/9ab7cf1a8fb585078519ce130c42a1042db9382a/data/json/items/comestibles/med.json#L52>

**Comment by GuardianDll** [comment]
Hmm
why in that case 223 has `"weight": "12 g",` and `"volume": "194 ml",`, when in game it has 0.01 and 0.01?
image
same with food - cereals has `"weight": "40 g",` and `"volume": "250 ml",` while real stats is 0.04 and 0.04?
image
🤔

**Comment by PatrikLundell** [comment]
I think you missed ""charges": 10," in the item definition.
However, something is definitely odd, as the save I happen to have has the PC carrying 10 charges for a volume of 0,15 L and 0,40 kg, i.e. the expected volume for a set of 10, but 10 times the weight. Dropping half of them halves both the weight and the volume...
Material is "cotton", with a density of 1.6.

Regular bandages are defined as 70 g, 250 ml, charges 3, stack size 9.
10 charges has a volume of 0,28 L and a weight of 0.70 kg.
This looks like volume is divided by "stack size" and "charges" is ignored for regular bandages, while volume is divide by "charges" for adhesive bandages, while weight seems to ignore both modifiers, and thus is applied per charge.

cereal: 38 g, volume 250 ml, charges 4. container: box_small, material junk.
"junk" has density 1.1, so the true volume of cereal would be 0,04 L (to the precision displayed) in a 250 ml box.

It seems that weight doesn't take the number of charges/stack size into account, while volume does.

**Pull request merged**
