### PR TITLE
Royal jelly from giant bees mutates you

### PR DESCRIPTION
**Pull request by SariusSkelrets**
#### Purpose of change

Currently there's no reason for the player to visit beehives since the royal jelly lost its cure-all properties as chitin can be easily aquired in anthills along with ant eggs, there's much more anthills on the map and ants can't fly or outrun you
#### Describe the solution

Give royal jelly insect mutagen properties to:
     Give a (rather small but still one) reason to clear beehives
     Expand the amount of non-lab mutation sources
     Explain how the Apis NPC got her mutations

#### Describe alternatives you've considered

None

#### Testing

Eat royal jelly. Obtain insect mutation

#### Additional context

It's possible to increase the amount of royal jelly in beehives or reduce the royal jelly mutagenic potency if needed

If this PR is merged, I'll search other rare consumables contained in uninteresting places in term of loot like the razorclaw roe from the shipwrecks and give them mutagenic properties to make them at least a little bit more interesting while expanding non-lab mutation sources

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
It is perfectly normal that hard-to-obtain items are useless.

**Comment by Cactoideae** [comment]
Usefullness of loot aside, this is a very flavourful change with a lot of storytelling potential.

I'm not quite convinced it should be _strong_ mutagen, though. As far as I understand, that makes threshold crossing possible.

**Comment by SariusSkelrets** [comment]
I tested it and get the «felling something wanting to break free» message so it means that royal jelly can’t pass the threshold

**Comment by Fris0uman** [comment]
This doesn't work as royal jelly also spawns in homes.

If you want behives to be interesting work on the map, add stuff to see, different type of monsters, larvae, a queen, several zlevel etc...

Adding an easy to get insect mutagen to it is not really interesting.

**Comment by SariusSkelrets** [comment]
It could be separated in two royal jellies: the one made by regular bees and the one made by giant blob-infected mutant bees that have a wierd texture and appearance 

I could try to expand the hive but IIRC the hive is still hardcoded and I can’t compile the game to test the changes i would do (also it’s incredibly rare: while testing the mutagen effect I searched hives and only found 2 after searching in 7 
Maybe i could add some smaller hives but for now i focus on the royal jelly

The mutagen is quite difficult to obtain as you must kill 40 or so bees to get 2-5 royal jellies (numbers based on my aforementioned searching)

In the NPC hints file there’s a line about a man that «came home with this wierd, magic honey stuff». I know it’s a reference to the panacea but it makes sense with mutagen wierd honey too

**Comment by Fris0uman** [comment]
> Two royal jellies

Yeah sure, that's a good start.
What would be really cool would be a map rework, having beehives in mantions and office tower instead of just laying on the ground would be nice.
And as far as rewards go I feel like mutated honey would make more sense, personnaly if I'm exploring a giant beehive it's because I expect to steal shit ton of honey, not to maybe get a little bit of royal jelly if I come at the right season.

**Comment by SariusSkelrets** [comment]
> What would be really cool would be a map rework, having beehives in mantions and office tower instead of just laying on the ground would be nice.
> And as far as rewards go I feel like mutated honey would make more sense, personnaly if I'm exploring a giant beehive it's because I expect to steal shit ton of honey, not to maybe get a little bit of royal jelly if I come at the right season.

They’re two great ideas. I’ll increase the spawn of honey(combs) and create a foul-smelling wierd mutagen royal jelly

**Comment by Fosheze** [comment]
> > What would be really cool would be a map rework, having beehives in mantions and office tower instead of just laying on the ground would be nice.
> > And as far as rewards go I feel like mutated honey would make more sense, personnaly if I'm exploring a giant beehive it's because I expect to steal shit ton of honey, not to maybe get a little bit of royal jelly if I come at the right season.
> 
> They’re two great ideas. I’ll increase the spawn of honey(combs) and create a foul-smelling wierd mutagen royal jelly
> 
> Do you have an idea for the differences between regular and mutated honey?

The mutant honey could just have a toxin value like other mutant foodstuffs. 

However I personally don't see a reason that the honey has to be "mutant" honey. Why not just leave it as normal honey. It would just be nice to have a good way to have a decent but dangerous source of a handy cooking ingredient. Having a 60l tank of just honey when you're at a high enough power level to clear a beehive isn't going to significantly unbalance the game. Eating nothing but honey would still tank your vitamin and health stats. I also don't see why honey produced by giant bees would be that much different from normal honey; it is essentially just a sugar syrup after all and it isn't actually a part of the mutant creature it's self.

**Comment by Fris0uman** [comment]
> Why not just leave it as normal honey.

How does a giant bee makes normal honey? There's no giant flowers. Best case scenario it's made from meat, see vulture bees irl.

**Comment by SariusSkelrets** [comment]
> best case scenario it’s made from meat, see vulture bees irl

It’s a good idea but the only problem i found with some internet searches is since the vulture bees produce only the honey they need the taste and more important the potential toxicity and health effects are unknown (but we can just add a toxin value so it’s ok if you don’t abuse this honey)

Or maybe they make honey from the fungal flowers

**Comment by dissociativity** [comment]
> 
> 
> > Why not just leave it as normal honey.
> 
> How does a giant bee makes normal honey? There's no giant flowers. Best case scenario it's made from meat, see vulture bees irl.

pehaps it could be some odd fungal synergy?
That certainly gets large enough, and it would be an adaptation for the changing world.

**Comment by Fosheze** [comment]
> Or maybe they make honey from the fungal flowers

Off topic but I beelieve you just came up with the fungal bee type. The Fungal Pollinator. It would spawn near fungal flowers. A flying fungal monster would definitely make the fungal flowers a bit more intimidating.

Also I guess I see the point on where would they be getting the pollen from. I haven't played around with foods with a toxin value much currently. As it is I just don't eat anything with any toxin value so if the honey has a significant toxin value then there is still no reason to go collect it. Alternatively, if some method was added to "detoxify" food then that would resolve the problem entirely. The player would still have a source of honey with the added labor required to detoxify it. The detoxification method definitely shouldn't be easy though. Perhaps something along the lines of the irradiation plant. It really depends on what specific toxins we're looking at.

As far as vulture bees go I did find [this](https://www.quora.com/How-do-vulture-bees-make-pollen-from-rotten-meat-and-is-the-honey-poisonous-to-humans). Of course it's from Quora so take it with a grain of salt. Quoted below.

`They don’t need to process the meat into pollen. There are nutrients that the decay organisms digest and others they make for the the decay organisms themselves. The meat is already partially digested and supplemented for the bees. Bees evolved the ability to live on just pollen and nectar from carnivorous ancestors that only ate pollen and nectar as supplements to a mostly carnivorous diet. It is actually easier to go from hard to digest plant matter to richer in savory nutrients meat. Many herbivores are noted for eating meat if the opportunity presents its self, including vulture bee ancestors. The bees have evolved resistance to food poisoning caused by eating decayed meat. Even honeybee honey is toxic to human infants because it can contain small amounts of botulism. As far as eating the honey made from a mixture of condensed nectar and rotten meat, that is not an experiment I would want to try. Not only would it possibly be toxic, It would be very expensive to purchase. Their honey is stored in individual honey cells, rather than in convenient honey combs. Humans can eat decayed meat, as our ancestors ate decaying meat before they worked up to killing larger, stronger animals for fresh meat. The people indigenous to the area might be able to enjoy it and treat it as a delicacy. Most fermented meat delicacies are an acquired taste and most of them tend to make to an outsider gag. It will have marketing issues. Sometimes, humans will even eat things not good for them for the interesting side effects, such as Japanese fugu and numerous illegal drugs. If it does sell well, it could create a demand that could cause the extinction of some very unusual organisms and the world would be lessened at the loss of their intrinsic value.`

Key points are:
1. All bee ancestors originally ate meat so it would make sense if the new mutant ones went back to that when pollen is scarce.
2. Vulture bees still require nectar, the meat is only a pollen replacement.
3. It sounds like vulture bees don't just eat any rotting meat, they specifically grab the decay byproducts.
4. Vulture bee honey would possibly be edible, if it is it would just be best described as a "delicacy" like lutfisk or hakarl.

**Comment by Cactoideae** [comment]
Giant bees get pollen from giant triffid flowers. It's not fully implemented yet.

**Comment by ZhilkinSerg** [comment]
> Giant bees get pollen from giant triffid flowers. It's not fully implemented yet.

Why would triffid have any pollen? They are not even plants.

**Comment by Cactoideae** [comment]
> 
> Why would triffid have any pollen? They are not even plants.

They are alien plants. And it's Kevin's idea, not mine: https://github.com/CleverRaven/Cataclysm-DDA/projects/36

**Comment by SariusSkelrets** [comment]
> Giant bees get pollen from giant triffid flowers. It's not fully implemented yet.

After reading this, i think i’ll leave the honey as normal honey and just changing the royal jelly and increasing the honey spawns since just one honeycomb each 3-4 beehives seems too small for giant honey-producing bees

**Comment by SariusSkelrets** [comment]
I’m still working on it. I’m currently very busy IRL and get an unknown error with the code so it gonna take some time

**Comment by int-ua** [comment]
Please switch the PR to draft if you are still working on it.

**Comment by kevingranade** [comment]
We're moving away from readily accessible mutagen, this needs at least an intervening crafting recipe.

**Pull request closed without merging**
