### PR TITLE
Add wakizashi to silat

### PR DESCRIPTION
**Pull request by TJKing293**
#### Summary
SUMMARY: Content "adds the wakizashi items to silat weapons list"

#### Purpose of change

Applies the silat effects to the wakizashi and it's variants
#### Describe the solution
Add wakizashi and it's variants

#### Describe alternatives you've considered

Considered Adding katana, But came to the conclusion that it was not suitable Due to its length.
#### Testing
In-game testing

### CODE REVIEW

**Comment by Maleclypse** [comment]
Can you edit the title to more accurately reflect the summary?

**Comment by AMurkin** [comment]
File in this PR is located in the root directory, not in data/json/.

**Comment by TJKing293** [comment]
I don't follow

> File in this PR is located in the root directory, not in data/json/.

**Comment by TJKing293** [comment]
I think I fixed it

**Pull request merged**
