### PR TITLE
Fixed another instance of illiterate characters are being able to read text on signs

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Hm, strange, I used AStyle, and gorgon is still complaining about astyle regressions...

**Comment by ZhilkinSerg** [comment]
> Hm, strange, I used AStyle, and gorgon is still complaining about astyle regressions...

Try more whitespaces in line 98 (24 instead of 16).

Try
````C++
                        _( "\nSign: %s" ), signage.c_str() );
````

instead of

````C++
                _( "\nSign: %s" ), signage.c_str() );
````

**Comment by Night-Pryanik** [comment]
It worked, thanks.

**Pull request merged**
