### PR TITLE
[Magiclysm] Add NO_FAIL to the various "Improved" spells

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Add NO_FAIL to the various "Improved" spells"

#### Purpose of change

The Improved spells are nice and satisfying--you're so good at a certain spell that you've come up with an even better version--but in practice they run into a big problem with the spellcasting formula in Magiclysm. Improved spells are learned by raising the base spell to max level, but that means the Improved spell starts over at level 1. And since level is the biggest component of easier casting, and since Improved spells usually have higher Difficulty than the base spells, and since Improved spells have no scrolls to study, you can easily end up with a situation where your max-level base spell and your Improved spell have the same effect except you have a 100% chance to succeed at the base spell and a 60% (or lower) chance to succeed at the Improved spell until you cast the Improved spell a few hundred or thousand times to raise its level. Not ideal. The whole concept here is that you understand the spell so well you can personalize it, so why would your personalized version fizzle so often? 

#### Describe the solution

Add the "NO_FAIL" flag to Improved [whatever] spell variants learned by mastering lower-level spells, making it always more worthwhile to cast the Improved version. By that point, the base version almost certainly has a 0% chance to fail anyway. 

#### Additional context

There are fewer Improved spells than I thought.

### CODE REVIEW

**Comment by GuardianDll** [comment]
i feel this idea was a fail, the better approach would be to remove this spells at all, return the basic versions of a spell 25 max level it was before, and apply "experience for casting" EoC that was introduced in XE in magiclysm - in this case players could actually train this spells bedyond lvl 15 (because after this it is just impossible to train spell beyond without spending weeks for one level), resolve unobtainable high levels for attunements and overall will be healthy for a mod

**Comment by Standing-Storm** [comment]
I'll defer to you about adding those EoCs to Magiclysm, since you originally designed them and understand them better than I do. 

(I'm also not the person to do it because I play with 50% skill gain rate on, so a week for one level of a high-level spell doesn't bother me)

**Comment by Rokharn** [comment]
There is not every improved spells. You missed many ones. For example, you missed 
magus: Dimension Door, Enhanced Impact Sling
animist: Soulrend
biomanser: Evolved Vicious Tentacle, Evolved Conjure Bonespear, Evolved Vicious Tentacle
druid: Enhanced Feral Form
kelvinist: Enhanced Glide on Ice
stormshaper: Shipwrecker, Enhanced Call Stormhammer, Enhanced Repelling Arc, Enhanced Stormfist, Vacuum Decompression, Shocking Teleport
technomancer: Enhanced Mage Blade, Enhanced Mage Armor, Hypervelocity Knifeshot

Easy to find, using "learn_spells"

**Comment by GuardianDll** [comment]
Vacuum Decompression is not the version you invent for yourself, you can learn it from the book separately

**Comment by Rokharn** [comment]
<details>
<summary>Idk, Vacuum Decompression surely can be learned as improved spell if you looking at the original spell</summary>
```
"id": "explosive_decompression",
    "type": "SPELL",
    "name": "Explosive Decompression",
    "description": "Create a high-pressure zone originating from the selected point.  Shortly after, a massive pressure wave will crush everything inside, inflicting barotrarumatic injuries on everyone affected.",
    "effect": "attack",
    "shape": "blast",
    "valid_targets": [ "self", "ally", "hostile", "ground" ],
    "flags": [ "SOMATIC", "VERBAL", "NO_LEGS" ],
    "max_level": 15,
    "min_damage": 24,
    "max_damage": 84,
    "damage_increment": 4,
    "min_aoe": 0,
    "max_aoe": 6,
    "aoe_increment": 0.4,
    "min_range": 6,
    "max_range": 21,
    "range_increment": 1,
    "spell_class": "STORMSHAPER",
    "base_casting_time": 250,
    "final_casting_time": 50,
    "casting_time_increment": -14,
    "base_energy_cost": 400,
    "final_energy_cost": 125,
    "energy_increment": -20,
    "energy_source": "MANA",
    "difficulty": 4,
    "damage_type": "bash",
    "learn_spells": { "vacuum_decompression": 15 }

```

</details>

   
in short ->  **"id": "explosive_decompression", <...> "learn_spells": { "vacuum_decompression": 15 }**
I hunt scrolls and books for the long time and did not saw vacuum one at last versions at all.


Oh, I forgot about _classless_ improved spells: Improved Obfuscated Body, Improved Aura of Protection, Greater Acid Resistance, Thought Suit.

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdc30581dc882eacf5a9bfd887bbaa0fa61a8b72/data/mods/Magiclysm/items/spell_scrolls.json#L862

**Comment by Rokharn** [comment]
Sure, but I did not saw it at loot and on traders at all for the few ingame years. And still as this spell can be learned via maxed another spell, it's surely count as improved one. Very strange if it's still somehow can be obtained as scroll after this change.

**Comment by GuardianDll** [comment]
it is a separate spell, it has it's own unique effect, it should not be removed from obtaining, full stop.

**Comment by Rokharn** [comment]
Purely for clarification. 

"Improved" spells is the ones, which can be obtained, when player upgrade spell to max level. Right?
If spell 'improved' it's will not have scrolls or books of any kind, right?

If it is a separate spell, not improved one, why it can be learned after max level of explosive decompression?

If spell both can be learned via maxing one spell and at the same time vis 'book', what kind of this spell? How any spell can be on both sides?

**Comment by Standing-Storm** [comment]
That should be all the appropriate spells.

I did not include any spells that had different effects from the original, even if they're learned from the original (so no Shocking Teleport even though it's learned from Shocking Dash because they don't do the same thing, for example)

**Pull request merged**
