### PR TITLE
No more cigarette flashlights

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
Bugfixes "Lit cigarettes no longer function as light sources"

#### Purpose of change
It was brought up on discord how some people use cigarettes to dissect in the dark. Need I say more?

#### Describe the solution
Change ``LIGHT_4`` flag to ``LIGHT_2`` on cigars, cigarettes, and joints. This means cigarettes will, when dropped on the ground, illuminate that tile but not enough to allow for stuff such as dissection or performing most crafts. It appears, however, that when 'worn' they produce no light whatsoever.

### CODE REVIEW

**Comment by GuardianDll** [comment]
How does such small values work in game? I though the idea was to make it not bright enough to do anything useful, but enought to disable stealth with cigarette in the mouth

**Comment by Karol1223** [comment]
> How does such small values work in game? I though the idea was to make it not bright enough to do anything useful, but enought to disable stealth with cigarette in the mouth

I am not sure. At ``LIGHT_4`` it was enough to light up the tile of the person the same way a lighstrip did aka allow to do anything on that one tile. It is possible that lowering it further may give stealth penalties without allowing for light-requiring activities but I honestly am not sure a cigarette is enough to compromise stealth when the enemy is a zombie - they're not attracted to the light, they're attracted to you in the light, and a cigarette isn't enough for them to see you in said light.

**Comment by Night-Pryanik** [comment]
This is intentional - see #63087.

**Comment by Zireael07** [comment]
@Night-Pryanik That issue is about stealth while IIUC this issue is about being able to do stuff requiring light

**Comment by GrandpuhTy** [comment]
Should cigarettes have an affect on night vision if they're extremely dim? I'm not really sure they're bright enough and in the right color spectrum to have a significant impact on your night vision.

**Comment by Karol1223** [comment]
> This is intentional - see #63087.

Right - this does still go back to the drawing board though. A cigarette should not allow you to be able to perform actions as if you were illuminated. If I had to choose between being stealthier and being able to perform an autopsy under cigarette light I'd rather choose the former. Do you have a suggestion as to how fix both the issues together?

**Comment by Night-Pryanik** [comment]
I'd add check for very low light conditions, such as lit cigarettes, and forbid conducting most activities requiring proper light.

**Comment by Karol1223** [comment]
> I'd add check for very low light conditions, such as lit cigarettes, and forbid conducting most activities requiring proper light.

This does seem like a good solution. Would you say then that the ``LIGHT`` flag should be given back to them? If so, should it still be at 4? I don't feel like a lightstrip and a cigarette give off the same amount of light...

**Comment by Night-Pryanik** [comment]
Light level produced by lit cigarette could be lowered to 2 or 3 then.

**Comment by Karol1223** [comment]
> Light level produced by lit cigarette could be lowered to 2 or 3 then.

2 looks to be a good middle ground. When carried in the mouth it does basically nothing, when dropped on the ground it gives enough light to illuminate but not enough to dissect or craft (most crafts, anyway, it allows for some still, not sure why).

**Pull request merged**
