### PR TITLE
Fix for vehicle menu bug

### LINKED ISSUE #17960: Unable to control vehicle lights
On commit e111a0b.
Trying to toggle vehicle lights does nothing.
Lights don't come on.
Menu doesn't indicate they're on either as when you go into the menu again you still see the option to enable them.
Asked about it in forum and Coolthulu said someone mentioned it in a commit comment, but there was no issue about it, so here is one :)
Easily reproducible by creating new world, no mods, spawn vehicle, try to enable lights.

### PR DESCRIPTION
**Pull request by mugling**
Fixes #17960

### CODE REVIEW

**Comment by MedievalNerd** [comment]
Works fine now! Thank you guys! :+1:

**Comment by mugling** [comment]
No worries and thanks to @petermorck for setting up a test case

**Comment by MedievalNerd** [comment]
I was following that ticket very closely. So @petermorck is a bit my hero. :)   I need to get more familiar with how to setup the debug version of the game. Does it work with the "new" visual Studio community, or only with 2015?

**Comment by petermorck** [comment]
Thanks :) Though I think it's better to discuss setting up VS2015 on the forum instead.
I made this thread before I got it to work. Let's continue there.
http://smf.cataclysmdda.com/index.php?topic=13063.0

**Comment by mugling** [comment]
More players compiling for win32 would be helpful

**Pull request merged**
