### PR TITLE
Fix missing rain gutters on the mansion roof

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
None

#### Purpose of change

image

There are some missing rain gutters on the mansion roof.

#### Describe the solution

n/a

#### Describe alternatives you've considered

n/a

#### Testing

I added `t_gutter_south` to it manually via the map editor and it looks good.

#### Additional context

n/a

### CODE REVIEW

**Comment by curstwist** [comment]
This looks fine.  You can probably use the north gutter (2 is the symbol) from what I'm seeing on the mapgen but it really doesn't make a difference.

**Comment by NetSysFire** [comment]
I actually checked the docs but it is unclear on rain gutters. Should it be e.g north when the ledge/open air is north?

**Comment by curstwist** [comment]
> I actually checked the docs but it is unclear on rain gutters. Should it be e.g north when the ledge/open air is north?

yes, it refers to the direction the ledge/open air is located.  However, our sprites no longer require individual rotations per side, so it isn't really impactful for their purposes.

**Comment by NetSysFire** [comment]
Seeing that even in Ultica rain gutters just look like an ordinary metal floor, it might make sense to replace all the aligned rain gutters with a single type of rain gutter, but this is something very out of scope for here.

**Pull request merged**
