### PR TITLE
Remove recipe for leather out of tainted hide, human hide

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove tainted/human leather recipe"

#### Purpose of change

Tainted hides/pelts would be very decayed, rotted, and damaged, and wouldn't be of much use to make leather. Was also questionable if it should've been possible in the first place, as comments on #14262 says it shouldn't've been able to be made.
Human skin, as far as I can tell, can't be used to make a leather equivalent to something like a cow leather. If there's a source that says they can, I'd love to hear it but so far, from my research it seems to be just theory and speculation.
Demihuman skin is something? It seems to come a lot from nether creatures, and it seems like an awfully nice coincidence you can turn it into leather.

#### Describe the solution

Removes the recipe to make leather/fur from tainted hide/pelt, along with leather from human and demihuman skin. I kept in the ability to use human pelt, because it's weird, mutated, and I'm unsure how much it would resemble animal hide. Also gave them a bit better of a description to describe why those can't be used. 

#### Describe alternatives you've considered

Not allowing human pelt to be used either. 

#### Testing
The new description:
image
Recipes:
image
image

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I think human skin should stay just because you can currently make leather out of any animal. Deer, rabbit, dog, pig etc. skin is not all that different from ours. If tough/durable things like cowhide are ever broken away from thinner leathers, it would be appropriate to move human skin over to the weaker type. See: https://www.livescience.com/archaeology/ancient-scythians-used-human-skin-for-leather-confirming-herodotus-grisly-claim or https://www.huffpost.com/entry/weight-loss-excess-skin-human-leather_n_64889fa8e4b04ee51a978464/

Agree on tainted hide though.

**Comment by Holli-Git** [comment]
> I think human skin should stay just because you can currently make leather out of any animal, and special casing human skin seems weird

I don't think something else not making sense should allow something else to also not make sense. I know little about leatherworking, but removing human skin seemed to be the most plausible so that's why I did it.

**Comment by fairyarmadillo** [comment]
> I don't think something else not making sense should allow something else to also not make sense. I know little about leatherworking, but removing human skin seemed to be the most plausible so that's why I did it.

But it does make sense. I posted evidence of people making leathercrafts like the ones the player makes in the game. Human skin would work for 99% of the leather and for the stuff where it wouldn't be ideal (some but not all of the armor) you could still use it, you'd just need more layers.

This is no different from the majority of animal skins in the game. The current method is that all skins are equal, making one arbitrarily unequal doesn't track.

**Comment by Holli-Git** [comment]
> This is no different from the majority of animal skins in the game. The current method is that all skins are equal, making one arbitrarily unequal doesn't track.

Ah whoops, I misread your statement. I'm still honestly "ehhh" on it. The two sources listed don't really rely on leather being a leather, it's just a general fabric. Now, granted, as you said a lot of our recipes it doesn't really matter the strength of the leather, but the recipe to make leather from humans is the tanned hide item, which is mostly used in armors and such.

**Comment by fairyarmadillo** [comment]
> but the recipe to make leather from humans is the tanned hide item, which is mostly used in armors and such.

This is incorrect, tanned hides are used to make all leather goods craftable in the entire game. They're simply the largest leather fabric item, with sheets and patches being smaller. Hides are used to make quivers, belts, clothing, bags, etc. Armor happens to be included in that, but it's in the minority, and there's nothing differentiating any one type of leather from another.

It may be appropriate in the future to break out cowhide from other types and implement different results from different types of tanning (chrome-tanned leather is very different from vegetable-tanned, etc), but that would be a project akin to differentiating steel qualities, which would take ages and a ton of research.

**Comment by kevingranade** [comment]
The sources do not establish that "leather made from human skin is useful", just that ancient people could be edgelords sometimes.
Mechanically, there's no real use for this OTHER than to be edgy, so it's not something I want to encourage.

**Comment by fairyarmadillo** [comment]
> Mechanically, there's no real use for this OTHER than to be edgy, so it's not something I want to encourage.

That I can get behind.

**Comment by JeveGreen** [comment]
You mean I can't cosplay Ed Gain anymore? Aw man...

**Pull request merged**
