### PR TITLE
Experiment with Windows build on GitHub actions

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Infrastructure "Add GitHub workflow to build object_creator"

#### Purpose of change
The object_creator has been part of the repo for a while, but has no CI coverage.  We should try building it on CI with Visual Studio.

#### Describe the solution
Try adding a new GitHub workflow using Windows.

#### Describe alternatives you've considered
Building on Linux instead.
Also tried #49117, but ran into Appveyor build timeout issues.

#### Testing
Needs to be tested here.

#### Additional context
as with the other PR, I'm unfamiliar with Windows builds on GitHub, so this is mostly for experimentation.

### CODE REVIEW

**Comment by jbytheway** [comment]
After quite a lot of messing about I've got this to the point where it mostly works, but the object creator build can't find the Qt headers.

This was very mysterious until @ZhilkinSerg reported that he was observing the same error building locally.

So, this work is on hold until such time as someone figures out how to fix the build on their local Windows machine (something I'm not really in a position to try).

**Comment by ZhilkinSerg** [comment]
qt5 includes were moved to qt5 subfolder - see https://github.com/microsoft/vcpkg/pull/17158

**Comment by jbytheway** [comment]
This now works, so I've marked ready for review.  Unfortunately, there is one remaining annoyance: the caching doesn't work because it runs out of disk space while `tar`ing up the files for the cache.  So this version would end up recompiling all the dependencies on every build, which isn't ideal.  I don't have any great ideas for how to fix that.  One possibility is that switching to Qt6 might help, because the Qt6 vcpkg port has more fine-grained feature options, meaning we could turn some off and not have to build so many Qt dependencies, saving disk space (and time).  Alternatively, there might be some things we could delete to save disk space before the caching step, but I'm not sure what.

**Comment by jbytheway** [comment]
...also, we're using a rather ugly workaround for the qt includes of hard-coding the path to the qt5 headers.  That doesn't seem like it's the Right Thing, but it does work.

**Comment by jbytheway** [comment]
I had left this alone for a while.  Now after rebasing it no longer works and I can't figure out why.  It builds the dependencies fine in the "Install more vcpkg packages" step, but then when it comes to the "Build" step it tries to build them all again instead of using the previously built versions.  I can't figure out why this would be.  Ideas welcome.

**Comment by jbytheway** [comment]
Superceded by #51616

**Pull request closed without merging**
