### PR TITLE
ERROR: Signal lost in multiple units.  WARNING: Sensitive materiel may require retrieval.

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
Content "Adds CBM harvests to the Zomborg, remove from earthly zombies"

#### Purpose of change
The zomborg, a partially converted cyborg that has died and been reanimated, should have extensive CBM harvests. I have not yet added those.

#### Describe the solution
Adds what is basically an SUS itemgroup for zomborgs, sorting their potential CBMs into logical subgroupings so you have a reasonable chance of finding many subtypes of CBMs. 

This also removes harvestable CBMs from earthly zombies and cleans out most of those obsolete itemgroups.

There are certain CBMs that should never be available from zombie harvests. These include, but are not limited to:

##### CBMs that must be researched first for compatibility with our world
bio_batteries,Battery System
bio_power_armor_interface,Power Armor Interface
bio_power_armor_interface_mkII,Power Armor Interface Mk. II
bio_remote,Remote Controller
bio_ups,Internal Unified Power System

##### CBMs that should be associated with a quest line
bio_night,Artificial Night Generator
bio_probability_travel,Probability Travel
bio_time_freeze,Time Dilation
bio_leukocyte,Leukocyte Breeder System
bio_teleport,Teleportation Unit - will probably need a buff
bio_cloak,Cloaking System
bio_chain_lightning,Chain Lightning
bio_uncanny_dodge,Uncanny Dodge
bio_resonator,Sonic Resonator
bio_faraday,Dielectric Capacitance System
bio_nanobots,Repair Nanobots
bio_blood_filter,Blood Filter
bio_ads,Active Defense Sytem - will probably need a buff
bio_ods,Offensive Defense System
bio_synaptic_regen,Synaptic Regeneration System

##### High tier CBMs that could be possible to harvest, but should be very rare - not all of these should appear at all.
bio_adrenaline,Adrenaline Pump
bio_emp,Directional EMP
bio_emp_armgun,EMP Projector
bio_heat_absorb,Heat Drain
bio_painkiller,Sensory Dulling
bio_railgun,Railgun
bio_recycler,Recycler Unit
bio_shock,Electroshock Unit
bio_shockwave,Shockwave Generator
bio_speed,Synaptic Accelerator
bio_surgical_razor,Autonomous Surgical Scalpels
bio_targeting,Targeting System
bio_tools_extend,Extended Toolset

#### Describe alternatives you've considered
Different CBM spawn lists

#### Testing
Result of 100 itemgroup spawns: the real ones would not be sterile
image
image
(there are two separate groups, one for utility/structure CBMs and one for power/power production CBMs)
I am very happy with this balance, you almost always get some decent trade good CBMs from a zomborg, and if you do 5-10 you should get a few useful CBMs, plus there's a chance for some pretty advanced ones later on.

Some zomborg harvests, using a scalpel with healthcare and electronics skills set to 5:
image
image
image
image
image

#### Additional context
I don't like the amount of automatic production of burnt out bionics currently, which makes it hard to predict outcomes. These lists are still more punitive than I want. However, the Exodii will buy burnt-out bionics at a pretty good rate, so they're a decent trade item soon. I would like to add a "cbm harvesting" proficiency you can get from them to improve your yields, since they'd very much like scavengers to go retrieve that stuff for them.

I left a few places where bionics spawn in maps for a future PR, because it will require some more testing for those to be removed, and can wait for a bit more exodii content to be in place.

I am still refining the lists and frequencies here. If there is a CBM you feel belongs in the "super rare" or "quest only" tier and is not included, it's a good time to make your case. In the near future I will be rewriting all our existing CBM itemgroups into tier lists and killing off the old ones.

### CODE REVIEW

**Comment by pehamm** [comment]
Surgical scalpels feel like a mission CBM, similar to the mind slicer kit for the hub retrieval quest.

**Comment by I-am-Erk** [comment]
> Surgical scalpels feel like a mission CBM, similar to the mind slicer kit for the hub retrieval quest.

I waffled on including them. Mission or not I am fine with them not being lootable.

**Comment by I-am-Erk** [comment]
This needs some testing but is done otherwise.

**Comment by actual-nh** [comment]
> bio_uncanny_dodge,Uncanny Dodge

If on this list, should be noted as needing a buff (applying to more things, for instance).

> bio_recycler,Recycler Unit

What's the logic for this one as high-tier?

**Comment by I-am-Erk** [comment]
> Perhaps another category of "very common" - I'd think Blood Analysis for self-monitoring, for instance?
> 
> > bio_uncanny_dodge,Uncanny Dodge
> 
> If on the high-tier list, should be noted as needing a buff (applying to more things, for instance).
> 
> > bio_recycler,Recycler Unit
> 
> What's the logic for this one as high-tier?

The harvest tiers are more about complexity than "goodness". Recyclers, for example, are presumably big and complicated and hard to retrieve intact.

From a gameplay perspective I just don't want to have all the cbms available easily by looting.

**Comment by I-am-Erk** [comment]
I think this is ready. Test failure doesn't seem to be related, though I am not 100% sure exactly what is failing

**Comment by anothersimulacrum** [comment]
There is no test failure I can see.

**Comment by I-am-Erk** [comment]
> There is no test failure I can see.

The general build matrix hates me.

**Comment by EvgenijM86** [comment]
If CBM are supposed to be this secret alien tech that average Joe know nothing about then how does a player even know how to harvest it in the first place? At the very least if humans developed CBM and the basics of it were taught in schools (advanced stuff - in specialized manuals) - it would make much more sense why you as a player know how to harvest them.

**Comment by I-am-Erk** [comment]
They're not a secret alien tech, they're parallel human tech. They weren't developed in this world, but they aren't particularly alien. All you need to do is cut them out, it's not rocket science... This isn't any different a problem from before this PR, when cbms were top secret military tech. 

At some point the exodii will teach you tips and tricks that will greatly improve your CBM recovery rate, though, that will be cool.

**Comment by EvgenijM86** [comment]
> This isn't any different a problem from before this PR, when cbms were top secret military tech.

CBMs could not have been just a top secret military tech, because:
1) Average civilian engineer zombie is equipped with magnetic CBM that could snatch metal items from you.
2) Many shock zombie in purely civilians locations with shock CBM.
3) Journals like Augmentative Tech Review implies that civilians also have access to CBM.
4) Civilian hospitals equipped with CBM installation stations.
5) Many scenarios where you start out with CBMs while being just a civilian with no relationship to some secret military.

**Comment by I-am-Erk** [comment]
CBMs were secret military tech. The game is pretty explicit about it, the places you could dissect them were just not get tightly moderated. Regardless, you've got your answer. You don't need special knowledge to carefully dissect a thing from a corpse, and I have no plans to remove the basic process of CBM retrieval.

**Pull request merged**
