### PR TITLE
Highlight useful information in item info text.

### LINKED ISSUE #13941: Improving item screen readability
Take a fully modded reflex recurve bow.
It is a ranged weapon, so it has about two dozens parameters related to that.
It's also a clothing item, so it has another dozen stats about that.
Then five lines of item description.
Then half a screen of text about mods.
All of this barely formatted with no easy hooks for the eye to navigate.

I'd like to suggest something like this.
1. Basic color-coding. Stat names should be of different color than the values. That alone would make it much easier to look over stats of any given item.
2. Advanced color-coding. Maybe stat names should have different colors depending on their type. For example, grey for generic ones (price, material), reddish for combat ones, greenish for armor ones, blueish for comestibles ones, etc.
3. Bullet points. Something like a colored [*] to indicate that this line is about some new property and not a continuation of previous text. Maybe a word for a category, like [mod:] before text regarding installed mod, [container:] for container description text, [item:] for item description, etc.
4. Better structure. Stats -> container description text -> damage when used as a weapon -> item description text doesn't look like a good structure.

Any thoughts?

### PR DESCRIPTION
**Pull request by OzoneH3**
Closes #13941

The goal is to make it easier to find important information about an item.

How it looks atm:

Tiles version both Windows and Linux: (look exactly the same)

### CODE REVIEW

**Comment by Treah** [comment]
Thats actually a very good idea espcialy with the perishable flag being highlighted. 

I think the could craft with it does not need to be highlighted tho. I do like the colors you chose too as they are not so bright or dim as to blend in or be overpowering.  Anyone else have any comments?

**Comment by vache** [comment]
Instead of "could craft with it", highlight "dozens of things".  Also maybe try to compress descriptions to remove new lines?  Screen real estate for descriptions is limited, especially without the ability to scroll them in some situations.  So, it could be like: This container is rigid, resealable, watertight, and holds 0.5 liters of liquid."

**Comment by BevapDin** [comment]
Highlighting "perishable" *and* "will rot" seems redundant. Is there any situation when only one of them will be present?

**Comment by Coolthulhu** [comment]
Canned perishables will not rot.

**Comment by OzoneH3** [comment]
Updated images in first post.

Please don't fixate on the images alone, can't upload a picture of everything. There are probably more of those lines @Vache pointed out with the containers that can be trimmed down.

As for the limited space, you should be able to scroll everywhere the item info is shown since #13805, if not please tell me where and I'll add it.

**Comment by BevapDin** [comment]
> I'd really love some input about what colors to use

I think the color manager can handle custom color names, you could just set up a custom color "color_stat" that has a default mapping to wherever actual color, but can be changed by the user.

**Comment by Night-Pryanik** [comment]
"This Container" -> "This container".
Also I don't fully understand the point of bolding Volume and not Weight, bolding Nutrition and not Quench etc.

**Comment by OzoneH3** [comment]
By only bolding the first important stat in a section I find it easier to jump between sections to where I actually want to look. Bolding every stat name would again make it harder to find information.

@Night-Pryanik
Would you want to have all stat names in bold, or just both if they are on the same line?

**Comment by Night-Pryanik** [comment]
@OzoneH3 I don't know if it's really needed to bold any of these stat names, because division into sections is already helping to distinguish info types one from another IMHO.

**Comment by OzoneH3** [comment]
@Night-Pryanik
It does but this makes it extra catchy, especially with something as long a text as the recurve gets.

**Comment by Nandorianen** [comment]
Thanks for working on this. Here's a few thoughts.

1. About colors. Not making it all look like a drug-induced dream is a good idea, but there are also caveats. Try zooming out. The blue colors seen in your screenshots (ones used for material, layer) look good zoomed in, but the smaller you make the font, the (disproportionally) harder it is to make out the letters. Same goes for this bleak purple ("GUNS"). Maybe a little bit brighter variants would be better? This probably works better in-game, where backgrounds are pure black (in default ASCII, at least), unlike your screens, where background is not black.

2. Bold words as a group separator seems to work. Is it possible to use a real separator? Like a line? If it is, it may work even better, but it's hard to tell without some examples.

3. There is still nothing to easily distinguish between stat name and stat value. Can you try using a subtle shading of one or another? If one is light gray, then another could be dark gray or normal gray.

4. Can you try using bullet points, for, say, list of flags? Something like this:
* This is fancy.
* This has pockets.
That would allow grouping stuff tighter without losing distinguishability. "*" could also be of a somewhat different shade of gray to stand out, but not too much.

5. Structure can still be improved.

For example, coverage and protection belong together, they shouldn't be separated by encumbrance/storage duo. These are the most important most of the time, so they should go to the end of the clothing stats.

Material belongs to the basic stats like category and volume.

Mod locations belong to weapon stats and should be separated from "covers" and all that follows.

**Comment by Zireael07** [comment]
@Nandorianen: I don't think the rearranging belongs here. I agree that the purple is really dark.

**Comment by narc0tiq** [comment]
Colors will vary by your terminal settings, and there are either 8 or 16 foreground and either 8 or 16 background colors, depending on terminal capabilities. Most every modern terminal emulator will understand the full set of 16x16 colors.

The base colors are black, red, green, yellow, blue, magenta, cyan, white. The eight "bright" colors are attained by setting the "bold" bit or the "blink" bit for bright foregrounds or backgrounds, respectively. Some terminals will let you choose whether the bold bit means bold, bright colours, or both; almost all current terminals will interpret "blink" as a bright background.

A quick Googling gave me [a fairly comprehensive list of terminals and their color support](http://misc.flogisoft.com/bash/tip_colors_and_formatting). YMMV.

On platforms where Cataclysm is not running in a terminal, it emulates one (though with some odd default choices for what the various colors mean -- normally, non-bold yellow is not supposed to be brown).

Pretty much every terminal I know of, [including Cataclysm's emulation](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/raw/colors.json), allow you to change what colors mean what. I don't know what color scheme @OzoneH3 is showing in his pictures, but they are purely representative of his terminal settings.

**Comment by Night-Pryanik** [comment]
Separation lines and bullets are cool!

**Comment by narc0tiq** [comment]
Color comparison with the game watch on my terminal:
colors, they do something

**Comment by Zireael07** [comment]
Separators look brilliant!

**Comment by OzoneH3** [comment]
Ok thanks, I think the colors are fine, narcs are even crisper than in my terminal.

Updated the first post with new images.

Added the separator line as dkgray so its not too dominant.

**Comment by Nandorianen** [comment]
Looks great. Couple more thoughts (looking at the last OP picture).
1. Value coloring is needed to easily distinguish values from stat names. I think leaving some values uncolored (I can see bash, cut damage, armor-pierce, damage calculation for ammo) defeats the purpose.
2. Would be nice to color ammo type used.
3. Would coloring mod slot numbers (0/1) be overkill?

**Comment by OzoneH3** [comment]
The last image is from the item comparison screen. If the values are identical or can't be compared they stay unhighlighted.

Here is how highlighting all vallues could look like (there is no easy way to only highlight certain values).


The item comparison gets a little funky with this though:

**Comment by Night-Pryanik** [comment]
Is it possible to also color resulting value, something like Damage: 7 (red) + 66 (brown) = 73 (red, not brown)?

**Comment by OzoneH3** [comment]
@Night-Pryanik Thats more of an item comparison "issue". It is in fact intended to work like it does. As for example in the picture above, why would I want to highlight the loaded weapon damage of the remington with the not loaded reflex bow. It dosen't give you any hints about how good a weapon is since there are so many different weapon+ammo combinations. 99% of the time you will compare empty weapons anyway.

**Comment by remyroy** [comment]
I just noticed this in the latest experimental. Well done. It' a great improvement.

**Comment by chaosvolt** [comment]
Ah, I missed this it seems. Dare I ask how the colors are selected? I get the feeling it needs to be up to the player, or possibly give the option to disable it.

It's already causing some derps. https://github.com/CleverRaven/Cataclysm-DDA/issues/14143

**Pull request merged**
