### PR TITLE
A few additions on the using of petfood

### PR DESCRIPTION
**Pull request by BrettDong**
* Feeding a nether dog (`mon_dog_thing`) the dog food will not comfort it, instead it will bite your fingers. This indicates that unlike normal dogs, in fact they are fond of human flesh.
* (__Edit:__) Feeding a hostile NPC the dog food may probably make them angry (10%).
* (__Edit:__) Do not spill the pet food if no animal is in there.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
A hungry survivor of cataclysm wouldn't mind being fed dog food. Especially considering that in-game dog food is just meat+veggies prepared in some relatively skillful (harder to make than jerky) way.

As for spilling: it would be OK to just cancel it saying that there is no animal be fed here.

**Comment by BrettDong** [comment]
I wanted to make this a way to shoo NPCs away. But yeah you're right,
desperate hungry survivors won't mind it.

**Comment by Coolthulhu** [comment]
If you want to shoo NPCs, it would be better to just implement a "shooing" function in dialogue that doesn't skip things.
For example, by allowing intimidate options in quest dialogue.

**Comment by Coolthulhu** [comment]
There is no good reason for a NPC to flee when presented with dog food. Especially hostile NPC.
It should be more like "NPC knocks it out from your hand" + `make_angry` or just ignore.

**Comment by BrettDong** [comment]
The NPC may think the player psychopathy for putting a piece of dog food into his mouth, or at least the player is some bit abnormal. And he/she then wants to stay away from the player as far as possible.

**Comment by Coolthulhu** [comment]
NPCs currently don't mind talking to nudist mutants with saber teeth and tentacles for feet.
Hostile NPCs who are trying to kill the player right now turning around to flee just because the player wants to feed them doesn't sound right.

Plus, some NPCs are mute and can't respond.

Why would smearing dog food on someone be more effective than pointing a loaded shotgun at them?

**Pull request merged**
