### PR TITLE
Removed money-related perks and millionaire profession

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Content "Removed money-related perks and millionaire profession"```

#### Purpose of change
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/32258

### CODE REVIEW

**Comment by SourSlime** [comment]
I think some stuff has to be moved to the obselete files (not sure how that works though) so that existing characters with the mutations/profession work properly.

**Comment by l29ah** [comment]
I think they just vanish with a warning. The profession resets to `Evacuee` AFAIR.

**Comment by Night-Pryanik** [comment]
@l29ah please do test this thoroughly so we could be sure we don't get new crashes related to this.

**Comment by Rail-Runner** [comment]
By the way, listed issue only mentions that the traits have to be removed. I think the profession could stay, but the associated trait would have to be removed from it; having lots of expensive but mostly useless starting items still gets the idea across.

**Comment by nexusmrsep** [comment]
Any chance of moving them to Crazy Cataclysm Mod?

**Comment by Zireael07** [comment]
I don't think they fit the crazy cata, but maybe their own mod?

**Comment by ZhilkinSerg** [comment]
Traits are obsoleted in #34239.

**Pull request merged**
