### PR TITLE
Fish fry & tadpole minor audit

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
These guys both were lacking in some departments

#### Describe the solution
**Fish fry**
- got a defined harvestlist of ``exempt`` - honestly not sure if this causes anything, but I am foolproofing this in case someone someday gets their corpse on their hands somehow
- got basic biology and physiology proficiencies - both normal fry and mutant fry (which should matter for the mutant)
- shrunk volume from 10ml to 3ml
- lowered mutant fry dodge from 10 to 8

**Tadpoles**
- increased dodge from 5 to 10
- no longer drop corpses - seriously, those guys are too small for this
- shrunk even more
- removed fire fear trigger - not for an aquatic critter

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
The fry should probably have 0 dodge, like other fish. Its tinyness will already make it very hard to hit, and at 8 dodge, the definitive meta for training melee will be to find one of these harmless creatures and spam attacks at it forever.

**Comment by Karol1223** [comment]
> The fry should probably have 0 dodge, like other fish. Its tinyness will already make it very hard to hit, and at 8 dodge, the definitive meta for training melee will be to find one of these harmless creatures and spam attacks at it forever.

Doesn't melee training depend on monster difficulty/melee skill level? These have the minimal amount of both, so this shouldn't matter.

**Comment by fairyarmadillo** [comment]
I was under the impression it was dodge skill. If I'm mistaken then nevermind.

**Comment by Karol1223** [comment]
After some research (asking people smarter than me if I was wrong or not):
- Dodge doesn't affect training melee skills
- Melee skill level of monster does, and this skill can't go below 1 to my knowledge => you can learn up to skill level 3 on fish fry
- This is fixable by manually defining a field with maximum level the monster can teach you up to. I'll do that in the evening for fish and frogs

**Pull request merged**
