### PR TITLE
Update UltiCa, and assume total control of the Senate.

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Content "Update UltiCa and make it default"

#### Purpose of change
UltiCa is the only tileset that currently supports all the vehicle changes in place. Also it is more generally user-accessible than other tilesets in repo, despite retrodays being really nice.

#### Describe the solution
I am assuming direct control. UltiCa is now the ultimate power in the universe.

In addition to making ultica default, this adds a huge amount of art for wearable and wieldable items, some more monster sprites, and a bit more vehicle art.

The Demo tag has now been fully removed. Obviously the tileset is not done, but there are very few areas remaining where it's hard to play with it. Hopefully this will encourage bug reports on the things that are most noticeable.

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/ultica-tileset-update-thread/19033/122

**Comment by I-am-Erk** [comment]
Nothing can stop me now

**Comment by Tairesh** [comment]
Retrodays' fans have left the chat

**Comment by Mister-Cultist** [comment]
UNLIMITED POWER~!!

**Comment by buildfailedforallplatforms** [comment]
Dead People is better

**Comment by ave-** [comment]
> 
> 
> Dead People is better

Give it time, it will get better. Variety is good, so if someday SomeDeadGuy stops working on his tileset, we will already have a good tileset to play with. Also, I like the vehicle style of UltiCa, so I will give it a try for sure.

**Pull request merged**
