### PR TITLE
[WiP]Optimize drawing-related functions, cache ASCII mode drawing

### PR DESCRIPTION
**Pull request by Coolthulhu**
Drawing in text mode on Windows is SLOOOW. I'm getting 5-7 fps in the benchmark on regular Windows, but 70+ on MSYS (which is Cygwin).

In the profiling I did in #19304 just "rendering" alone took as much time as shadowcasting.
That isn't all of the drawing and actual displaying the "rendered" letters on the screen takes much longer than figuring out what to draw and in which colors, but it is still a large chunk of CPU time.

Here I optimize the "rendering" itself by caching the symbols and colors and only regenerating them when structures under them change.
Old approach checked every single visible tile for furniture, terrain, traps, fields, items, vehicles and graffiti (graffiti took a surprisingly big chunk of time), every single turn.
New one does it once, then once again when any of the above is added, removed or changed, when map is shifted or when player goes underwater or comes back from underwater.

This isn't perfect yet so it is hidden behind an option. By default turned off. When turned off, the old behavior (regenerating everything every time) is used.
There is one case of imperfect behavior I can't easily fix here without reworking a lot of code or dirtying the whole cache every time: changing items on the map. For example, flare burning out. This is because the converting item doesn't know where is it located.
I won't fix it in this PR. For now it will either leave "ghosting" or clear all cache (not sure which is better).

___

Another update I bundled here is optimization of one of the rendering bottlenecks: `map::apparent_light_at`.
It does call `rl_dist` a lot. In fact, it may easily be the single biggest source of `rl_dist` calls.
For square distance it is tolerable, but circular has that expensive `sqrt` there.
Since the function only compares the distance to two preset values, it is fine to use a square of distance.
I added a `rl_dist_squared` which is `trig_dist` without the `sqrt` at the end or `square_dist^2`.

___

[WiP] because I need to profile it and check if it didn't break any existing functionality. Some performance regression should be acceptable

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Shit, the benchmark isn't any faster.

Any gains in time are dwarfed by the huge penalty for drawing on Windows.
I spent few hours only to realize that I've been trying to optimize the wrong part of drawing.

I failed to notice that the cost of `map::draw_maptile` was completely dominated by `UTF8_getch`, which is a part of `mvwputch`/`mvwprintz`. More than 90% of `draw_maptile` is just executing `UTF8_getch` for every single character.

**Comment by BrettDong** [comment]
Profiling result on your branch FYI:
profile2
profile1

GPU: Intel HD Graphics 6000
OS: Windows 10 x64
Compiler: MSVC x64

Benchmark FPS isn't any faster either.

**Comment by Coolthulhu** [comment]
Did you test it in tiles build? In my console build the UTF8_getch hogs way more CPU time - over 25% of `curses_drawwindow`.

**Comment by BrettDong** [comment]
> Did you test it in tiles build? In my console build the UTF8_getch
> hogs way more CPU time - over 25% of |curses_drawwindow|.
>
SDL Tiles

**Comment by Coolthulhu** [comment]
That would explain totally different results.
I'm mostly concerned about wincurses, because the code for it is abysmal and gives me 6 fps average.
What are the average FPS in tiles builds?

**Comment by BrettDong** [comment]
> That would explain totally different results.
> I'm mostly concerned about wincurses, because the code for it is
> abysmal and gives me 6 fps average.
> What are the average FPS in tiles builds?
>
>
For me on this poor Intel HD Graphics 6000, it's 27 fps on optimized build.

**Comment by Coolthulhu** [comment]
I'll try to finish what I'm working on here (UTF16 string caching - should solve console bottleneck) and maybe that will get the console build performance somewhere closer to that 27 fps.

Was that 27 fps with caching option (in graphics) on or off? Did turning it on/off make any difference?
If it isn't the bottleneck, I will probably scrap the whole map caching and just cache individual symbols of terrain, items etc.

**Comment by BrettDong** [comment]
> I'll try to finish what I'm working on here (UTF16 string caching -
> should solve console bottleneck) and maybe that will get the console
> build performance somewhere closer to that 27 fps.
>
> Was that 27 fps with caching option (in graphics) on or off? Did
> turning it on/off make any difference?
> If it isn't the bottleneck, I will probably scrap the whole map
> caching and just cache individual symbols of terrain, items etc.
>
There is no obvious difference on benchmark results whether caching
option is on or off.

**Comment by Coolthulhu** [comment]
This isn't really going anywhere, I started from the wrong side.
The problem is abysmal handling of Unicode. Until that is solved, any console drawing optimizations are pointless.

**Comment by BrettDong** [comment]
What does the profiling look like on your side?

**Comment by Coolthulhu** [comment]
```
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
  6.81      2.75     2.75     6391     0.43     0.57  curses_drawwindow(WINDOW*)
  6.38      5.33     2.58                             pthread_spin_lock
  5.49      7.55     2.22                             pthread_setspecific
  5.10      9.61     2.06                             pthread_spin_unlock
  4.90     11.59     1.98                             __pthread_self_lite
  3.93     13.18     1.59                             pthread_getspecific
  2.38     14.14     0.96                             _Unwind_SjLj_Register
  2.13     15.00     0.86                             std::string::assign(std::string const&)
  1.86     15.75     0.75                             GetCurrentThreadId@0
  1.83     16.49     0.74 20377771     0.00     0.00  UTF8_getch(char const**, int*)
  1.83     17.23     0.74  4000604     0.00     0.00  map::draw_maptile(WINDOW*, player&, tripoint const&, maptile const&, bool, bool, tripoint const&, int, bool) const
  1.73     17.93     0.70                             std::istream::sentry::sentry(std::istream&, bool)
  1.71     18.62     0.69                             _Unwind_SjLj_Unregister
  1.66     19.29     0.67  6799524     0.00     0.00  waddch(WINDOW*, int)
  1.66     19.96     0.67     1698     0.39     0.51  map::generate_lightmap(int)
```

```
[7]      9.0    2.75    0.88    6391         curses_drawwindow(WINDOW*) [7]
                0.38    0.00 10277930/10277932     widen(std::string const&) [68]
                0.37    0.00 10326253/20377771     UTF8_getch(char const**, int*) [34]
                0.13    0.00 10277930/20288656     mk_wcwidth(unsigned int) [93]
```

That % time is not correct. It's skips a lot for some reason.
It is actually much worse than it looks from the numbers. Could be input delay or something.
The end effect is that moving by pressing keys as fast as possible is literally 5 times faster in Cygwin builds than in proper Windows builds.

**Pull request closed without merging**
