### PR TITLE
Split some traits from professions

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

SUMMARY: Balance "Split some traits from professions"
#### Purpose of change

Allow player to start with Helicopter Pilot and Skater traits, so that they're not locked to certain professions if they want them. I suppose "former pilot" and "hobby skater" could be valid things. Trait descriptions were edited to be a bit more generic while clarifying actual trait effects.

Also made Wayfarer and Helicopter Pilot traits mutually exclusive, since having Wayfarer won't let player control a helicopter even if they have Helicopter Pilot trait.
#### Describe the solution

JSON editing of trait entries.
#### Describe alternatives you've considered

Doing the same for some other profession traits, but most of them seem to assume that it's not just skills, but also being in certain databases, which wouldn't make sense for anyone but an active worker to have; also they're simply way too niche.
#### Testing

Made sure that both traits are available at character creation.
Made sure that Helicopter Pilot profession correctly starts with the trait.
Made sure that both of Helicopter Pilot profession and Helicopter Pilot trait allow controlling a helicopter.
#### Additional context

None.

### CODE REVIEW

**Comment by kevingranade** [comment]
So your character is whatever else it's configured to be and just randomly also a helicopter pilot? That stretches credulity way too far which is why this was not available as a trait other than with a profession in the first place.

**Comment by Night-Pryanik** [comment]
Well, some combinations like "senior citizen" profession and "former helicopter pilot" trait are viable.

**Comment by Rail-Runner** [comment]
> So your character is whatever else it's configured to be and just randomly also a helicopter pilot?

I was thinking they're most likely either a former pilot, with enough knowledge remaining so that they can figure out how to operate one now (likely with their license being revoked due to some violations, but who cares about that now), or someone who was about to become a pilot and just finished their traning.

**Comment by kevingranade** [comment]
Feel free to add, "former pilot" or "student pilot" professions then, but those use cases don't justify throwing it open to combining the pilot trait with arbitrary professions.

> I can remove it and leave only changes related to Skater trait if it's still a problem, though.

Please do.

**Comment by Rail-Runner** [comment]
Done.

I decided to keep the description change (since it gets outdated in case player manages to actually fly a helicopter) and Wayfarer-related change (so that pilots can't take Wayfarer trait since it kinda ruins the point)

**Pull request merged**
