### PR TITLE
Boomers Leave Gibs

### PR DESCRIPTION
**Pull request by TheSaddestGoomba**
#### Summary
Content "Boomers now leave fleshy gibs on detonation"

#### Purpose of change
Boomers have always just left a pile of clothing in the middle of their scattered payload. This adds body fragments to the drops when boomer-type enemies explode.

#### Describe the solution
I tested this in #71475 with the bloated zoad and warted monstrosity.
This is essentially the same implementation. An item group called through monster death_drops that leaves a smattering of body scraps in addition to the usual zombie drops.
4 new items are created:
1. tainted innards - which functions as a catch-all for mutated and rotted zombie guts/entrails.
2. tainted limb (arm) - represents the fragmented limbs that may remain after a boomer bursts, not part of butchery.
3. tainted limb (leg) - ditto to above, just variable description and weight/volume.
4. tainted human skull - tainted bone version of the normal human skull, grim reminder of what they were and place for more flavor text.

Exploding fungals were set to leave a full corpse, but now leave body parts and alien fungus chunks.
Necro-boomers have unique death drop of corpse ash and very little bone.

The changes currently affect the following monsters:
1. Boomer
5. Huge Boomer
6. Boomer Glutton
7. Bloated Zombie
8. Bombardier Boomer
9. Gasoline Zombie
10. Swollen Tearjerker
11. Sleepwalker Zombie
12. Zombie Necro-boomer
13. Fungal Boomer
14. Bloated Fungal Zombie
15. Pollinator Zombie
16. Gangrenous Flesh
17. Gangrenous Impaler
18. Gangrenous Crawler
19. Scissorlimbs
20. Hanging Innards
21. Trapped Tendril
22. Trench Pig

I'll add any other monsters that fit, but I think that's everything.

#### Describe alternatives you've considered
- Make the parts scatter out to adjacent tiles. I would love to do this but don't have an idea as to how yet, and I want to get the basic function done first.
- Somehow use mass_ratio for the the drops. It appears to be tied specifically to butchery of corpses and not useable in item groups however.
- Applying this to pupating zombies, but they leave corpses and are able to be revived by necro effects.
- Creating tainted versions of individual organs. I believe this is more granular than is needed for any use they may have, and also that the original organ is likely unidentifiable at this point in the creatures' transformations.
- Adding the new items to recipes. I'll work this into a follow-up PR to polish up the items themselves.

#### Testing
- Loaded up the game, spawned a variety of boomers, blew them up; all edited monsters drop the appropriate items on death, including the default drops they had before. Same tests done for collapsed tower mobs.
- Currently my only hang up is that the dropped clothing items are not FILTHY despite the creatures having the flag. Something about circumventing the corpse generation may be causing the flag to not apply?
- Tested harvest additions by debugging in, killing, and butchering various enemies; all had the appropriate tainted innards or alien fungus chunks.

#### Additional context
I'm taking this out of draft. I will look into the clothing issue and relevant recipes in a follow-up PR.

### CODE REVIEW

**Comment by TheSaddestGoomba** [comment]
@Karol1223 
Is there any risk of conflict I should worry about with your PR draft for #71170 ?

**Comment by fairyarmadillo** [comment]
I'm not sure if necro-boomers are exploding into goo, as they don't leave any field behind or anything. I sort of thought they were just exploding into shadows or something. Doesn't matter too much, but it might look weird if there's just like a mysterious bit of intestine left on the ground after the thing dies.

**Comment by Karol1223** [comment]
> @Karol1223 Is there any risk of conflict I should worry about with your PR draft for #71170 ?

I am pretty confident that the only boomer I touched was the necroboomer, so even if we do end up causing each other conflicts it'd be in one place only. Any other boomers I'd aim to audit in the part 2 of that PR because the current one already got a tad too big for my liking - don't worry about it, odds are my stuff won't be ready to merge before yours is.

**Comment by Spicyshadow** [comment]
You could make exploding fungals more disctinct by having them also drop alien fungus chunk. I wouldn´t make them drop fungal fluid sacks as those are edible which is to be avoided for zombies. The only use I would see for tainted offal is to make fertilizer/compost and maybe to make mutagen, besides being food for mutants that can eat zombies. 

Tainted offal could be given to all zombies and given various descriptions similar to mutant organs. It would add a new oppertunity for more discusting body horror and fix the wierdness of zombies having no organs.

**Comment by TheSaddestGoomba** [comment]
> You could make exploding fungals more disctinct by having them also drop alien fungus chunk. I wouldn´t make them drop fungal fluid sacks as those are edible which is to be avoided for zombies. The only use I would see for tainted offal is to make fertilizer/compost and maybe to make mutagen, besides being food for mutants that can eat zombies.
> 
> Tainted offal could be given to all zombies and given various descriptions similar to mutant organs. It would add a new oppertunity for more discusting body horror and fix the wierdness of zombies having no organs.

You bring up a lot of good points.
Alien fungus chunks are a good, easy addition for the fungals, (even moreso because they're already hooked up to recipes :)
I'll add the tainted offal to the zombie butchery lists in this PR.
Oh, I had forgotten about multiple/variable item descriptions through snippets. I do love me some body horror. I'll add a few at least and leave some room for others to expand it. I may rename the item to tainted innards to further genericize it and open up the descriptive possibilities.
I'll take a look at fertilizers and mutagens, if they seem too daunting I may leave them for a another PR. Same for making them edible to mutants, with or without recipes.

>Re: Necro-boomers

I do like the idea of something more unique for the necro-boomers. Currently they just sorta disappear and leave their clean clothes, like they were raptured. Maybe corpse ash is appropriate? It uses ALL of its energy and just disintegrates

Sounds good on the copy-from PR. I don't think this will touch anything beyond death_drops for the necro-boomer.

**Comment by fairyarmadillo** [comment]
Corpse ash is a great idea.

**Comment by TheSaddestGoomba** [comment]
This is essentially complete.

There are errors tripping for two reasons that I see:
1. Unrelated map gen
2. Density testing - It's tripping on the new items, "arm_zed" and "leg_zed" which copy their weight and volume values from existing "arm" and "leg".

**Comment by Karol1223** [comment]
@TheSaddestGoomba Is it intended fungal zombies don't drop innards, or is it an oversight? I'm working on #76865 and chaining together harvestlists, noticed the fungal ones don't have innards. I can see this going both ways, so I figured I'd better ask.

**Comment by TheSaddestGoomba** [comment]
@Karol1223 

IIRC, at the time I just left them out in favor of the alien fungus chunks.
In retrospect, I think it's more fitting that they should have both. Possibly less innards in proportion, since some of it has been converted into the fungal tissue.

**Pull request merged**
