### PR TITLE
Pickaxe_list and rope_natural relevant Fix

### LINKED ISSUE #71381: Unable To Construct "Dig Downstair"
### Describe the bug

Despite having all that is needed for the recipe and being on ground that can be dug up I can't dig downstair

### Attach save file

[Pedro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14107811/Pedro.zip)

Should work on a fresh save file

### Steps to reproduce

1. make a player with 5 fabrication and 3 survival.  2. spawn in a hammer, wood saw, pickaxe, shovel, 90 nail, 18 planks, and 2 heavy wooden beams. (materials for the recipe) 3. Find dirt and attempt to dig downstair. 

### Expected behavior

I expected to be able to dig downstair

### Screenshots

_No response_

### Versions and configuration

- OS: Windows 11  -Game Version: Experimental Build 2024-01-31-0419  -Graphics Version: Tiles  -Ingame Language: English  
- Mods loaded: dda, bionic slots, disable npc needs, slowdown fungal growth.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by osuphobia**
#### Summary

Bugfixes "Pickaxe_list, and rope_natural relevant bug 'Unable To Construct Dig Downstair'"

#### Purpose of change
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/71381 https://github.com/CleverRaven/Cataclysm-DDA/issues/72141, in addition to a minor bug that tools needed not displayed corretly.

#### Describe the solution

Pickaxe_list is not working properly, fixed it both in vanilla, Magiclysm and innawood. Now we can uncraft large rock with tools in pickaxe_list.
In addtion, I corrected the minor mistakes in pickaxe_list, so tools needed in relevant construction recipes can be shown correctly now.

Requirements in constr_dig_downstair, constr_mine_downstair, and constr_mine_upstair are not well-defined.
Because that rope_natural is not defined as a tool, but a component in material.json, simply adding it to tool-requirement result in nothing.
Added tool_rope_long consisiting with long ropes, grappling hook, steel chain and heavy-duty tow cable in toolsets.json, and replaced rope_natural with tool_rope_long in the recipes relevant.

#### Describe alternatives you've considered

The in-game description still suggests that ropes are considered as components in these recipes after https://github.com/CleverRaven/Cataclysm-DDA/pull/69822, and the words has not been changed since 0.G as far as I know.
To set ropes as tools instead of components required, we can also add `[ { "id": "ROPE", "level": 2 } ]` to qualities required.
Another way is to simply add the "tools" line to rope_natural in material.json, then change `[ "rope_natural", 1, "LIST" ]` to `[ "rope_natural", -1, "LIST" ]` in the recipes. But that's kind of wired IMO.
Please give me some advice on which one should be used.

#### Testing

Manual testing to verify fix, nothing wrong when uncrafting large rock with pickaxe.
And items listed in tool_rope_long now count as tools required in in constr_dig_downstair, constr_mine_downstair, and constr_mine_upstair.

#### Additional context

None

### CODE REVIEW

**Comment by osuphobia** [comment]
I did it the wrong way in creating a pull request with the master branch as the head branch in https://github.com/CleverRaven/Cataclysm-DDA/pull/72156, and I can't find a way to change the head branch to a sub branch.
Sorry for any inconvenience caused.

**Comment by osuphobia** [comment]
Tracked the change log, in https://github.com/CleverRaven/Cataclysm-DDA/pull/69822 `[ "rope_30", "vine_30", "rope_makeshift_30" ]` is moved from components to tools required in dig_downstair, mine_downstair and mine_upstair. 
Then https://github.com/CleverRaven/Cataclysm-DDA/pull/71087 replaced `[ "rope_30", "vine_30", "rope_makeshift_30" ]` with rope_natural. This not only caused the bug above, but also expanded the range of items usable for the task, and I don't think it's reasonable.
Considering all these things above, the best plan should be to add `[ { "id": "ROPE", "level": 2 } ]` to qualities required. Those 30-foot grappling hooks are surely applicable for tasks that 30-foot long ropes can be used.

**Comment by osuphobia** [comment]
@PatrikLundell Could you please give me some advice on which solution is preferred?

1. Remove the `[ "rope_natural", 1, "LIST" ] ` requirement and add `[ { "id": "ROPE", "level": 2 } ]` to qualities required.
2. Simply add the "tools" line to rope_natural in material.json, then change `[ "rope_natural", 1, "LIST" ]` to `[ "rope_natural", -1, "LIST" ]` in the recipes.
3. Add
```
  {
    "id": "rope_tool_long",
    "type": "requirement",
    "//": "Long rope used as a tool, in constuction process and so on",
    "tools": [ [ [ "rope_30", -1 ], [ "rope_makeshift_30", -1 ], [ "vine_30", -1 ], [ "grapnel", -1 ] ] ]
  }
```
to toolsets.json and replace `[ "rope_natural", 1, "LIST" ]` with `[ [ "rope_tool_long", 1, "LIST" ] ]`.

**Comment by PatrikLundell** [comment]
No, I'm afraid not. It's a judgement call. I personally would be fine with any of them (although I thought grapnel was just the hook without the rope that makes it into a grappling hook: a grappling hook would be usable as it's a rope with an extra bit). However, I'm not the one who approves things.

**Pull request merged**
