### PR TITLE
Add wearable scalpel

### PR DESCRIPTION
**Pull request by glenmack**
#### Summary
Adds recipe for and item of wearable scalpel. Just clip to your survivor gear and dissect at will.

```SUMMARY: Content "Wearable scalpel"```

#### Purpose of change
Mostly ease of use, addresses #36782 

#### Describe the solution
Adds a wearable scalpel

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I use a scalpel on pretty much a daily basis, and have never encountered nor heard of a wearable scalpel, nor do I understand why anyone would design one.

**Comment by kevingranade** [comment]
Seems to have no basis in reality, please post one if you can find it and we can reconsider.

**Comment by glenmack** [comment]
Of course it has no basis in "reality" people who use a scalpel every day in real life don't use it to dissect CBMs out of corpses when they're walking across a desolate landscape. They use it in their workshop.

It's to serve a gameplay purpose for the thing that is a game for systems within the game that only exist within the context of that game.

**Comment by glenmack** [comment]
https://www.amazon.co.uk/AKORD-7-15-Pen-Pencil-Clips/dp/B00AFT9I7M/ref=asc_df_B00AFT9I7M/?tag=googshopuk-21&linkCode=df0&hvadid=232020729251&hvpos=1o2&hvnetw=g&hvrand=15969279719079068855&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1006739&hvtargid=pla-420702627039&psc=1 Essentially the same thing, but I would use it to hold my scalpel.

**Comment by I-am-Erk** [comment]
But why? Even in game what purpose does it serve? The player can do exactly what I do, pull a scalpel from their pocket if they need it quickly. Butchering and dissecting only requires you to have it in your inventory, it doesn't need some kind of quick draw tool mod.

**Comment by glenmack** [comment]
You clearly didn't read the code or understand the issue. It isn't drawable, or sheatheable. It's just clipped to the outer layer so it doesn't have to be in your inventory, because inventory management is still a quagmire of unnecessary keystrokes.

**Comment by I-am-Erk** [comment]
That's possibly the least compelling reason I can think of for such a niche item to exist, and is definitely not clear in either your code nor your issue. If it were I'd have closed this sooner.

**Pull request closed without merging**
