### PR TITLE
Export some mapgens to JSON

### PR DESCRIPTION
**Pull request by BevapDin**
The JSON is a simple copy of the C++ code, not actual changes there, I hope somebody with creativity will enhance them.

Sometimes the relatively new "mapping" entry is used to allow mapping of several mapgen things to a letter in the map blueprint (the "rows" array) in one step. This way several things can be placed together (e.g. map "f" to setting furniture fridge _and_ spawning items from group "fridge").

What is the plan with all the empty functions in mapgen_functions.cpp?

### CODE REVIEW

**Comment by Zireael07** [comment]
So how does the JSON work now?

**Comment by vache** [comment]
I think the idea was to pull all the individual functions out of mapgen and into mapgen_functions to make it easier to find what individual omt you were looking for, but it never got finished.

**Comment by kevingranade** [comment]
Yes, a half finished cleanup, they can be removed.

**Comment by BevapDin** [comment]
@Zireael07 Same as before, no real changes here. What do you mean exactly?

The mapping I was  referring to is this (code not necessarily correct):
```JSON
{
    "mapping": {
        "A": {
            "terrain": "f_grass",
            "furniture": "f_chair",
            "trap": "tr_blade",
            "items": { "item": "drugs" },
            "fields": { "field": "fd_blood" }
        }
```
This defines all the mappings to a single letter in one place instead of putting them in separate entries:
```JSON
{
    "terrain": {
        "A": "f_grass"
    },
    "furniture": {
        "A": "f_chair"
    },
    "trap": {
        "A": "tr_blade"
    },
    "items": {
        "A": { "item": "drugs" }
    },
    "fields": {
        "A": { "field": "fd_blood" }
    }
```

**Comment by DavidKeaton** [comment]
Much better then.

**Pull request merged**
