### PR TITLE
[WIP] Power Armor Holster, Sheath, and Scabbard

### PR DESCRIPTION
**Pull request by Maddremor**
This PR adds a holster, sheath, and scabbard for exclusive use with a power armor. Spawning and/or crafting remains unimplemented as I wish get some second opinions on balancing.

Currently, the holsters dosen't have a covered bodypart assigned as the tag, "power_armor": true, applies to both power armors and power armor accessories (currently the hauling frame). An item cannot encumber a body part without registering as a power armor and thus conflicting with the actual power armor. If this cannot be circumvented, the holsters probably needs to be rare loot as they lack any penaleties from wearing.

### CODE REVIEW

**Comment by Zireael07** [comment]
@Maddremor what's that zoom swap commit doing at the top of the commit list?

**Comment by Maddremor** [comment]
The zoom thing is due to me being a git newbie.

**Comment by Zireael07** [comment]
Well, you'll need to fix it before this PR can get merged...

Are you using a Git GUI client? I'm afraid I'm no good at commandline git...

**Comment by Maddremor** [comment]
I know, working on it.

**Comment by Night-Pryanik** [comment]
You may want to read some information about wearing any gear with power armor in #14764.

**Comment by Maddremor** [comment]
New cleaner PR at #21092

**Pull request closed without merging**
