### PR TITLE
Rename world creation "Spawn Time Options" to "World Time Options"

### LINKED ISSUE #73501: Rename world option "Spawn Time Options"
### Describe the bug

Since the setting for spawn time has moved to the character creation, I think the name for this section should be changed.

### Attach save file

N/A

### Steps to reproduce

1. Open World creation
2. Press 's' for advanced options
3. There it is!

### Expected behavior

I would suggest calling it "World Time Options" instead, since the contained options are centered around how time flows in the world (season length, construction scaling, eternal seasons, and day/night cycle).

### Screenshots

image

### Versions and configuration

Experimental, currently in 2024-05-04-0725, but it's been like that for a while.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by theFeu**
#### Summary
Interface "Change world setting 'Spawn Time Options' to 'World Time Options'"

#### Purpose of change
Since the setting for spawn time has moved to the character creation, I think the name for this section should be changed, resolves #73501

#### Describe the solution

I would suggest calling it "World Time Options" instead, since the contained options are centered around how time flows in the world (season length, construction scaling, eternal seasons, and day/night cycle).

#### Describe alternatives you've considered

N/A

#### Testing

I am still trying to figure out how to compile, so not yet tested.
Then again, it is just a string that was changed :)

#### Additional context

I am not sure if the po files need to be updated (and how). If there is more I should do, let me know!

### CODE REVIEW

**Comment by Qrox** [comment]
> I am not sure if the po files need to be updated

The po files will be automatically updated, you do not need to (and should not) update them manually.

**Comment by hexagonrecursion** [comment]
> #### Summary
> 
> Interface "Change world setting 'Spawn Time Options' to '**Spawn Time Options**'"

You made a copy paste error. The second "Spawn Time Options" should be "World Time Options" instead.

**Comment by I-am-Erk** [comment]
ah, I didn't notice the interface thing hadn't been fixed. Oh well

**Comment by theFeu** [comment]
@I-am-Erk 
Would it make sense to include this in 0.H?

**Pull request merged**
