### PR TITLE
More mutations conflict with Alloy CBMs

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "More mutations conflict with Alloy CBMs"

#### Purpose of change

Alloy Plating CBMs could not be installed if the character had many mutant parts, but the list of prohibited anatomy was incomplete. It was possible for example to install the plating over a beak but not over a snout and the Leg and Arm plating had no bearing on foot and hand mutations, even though they give those spots armor and take up slots. 

#### Describe the solution

More mutations will prevent installation of CBMs (and vice versa, having alloy plating will also prevent the development of more mutations). The Head Alloy Plating will now conflict with mouth flaps, mouth tentacles, and beaks, Arm Alloy Plating now conflicts with claws, talons, nails, webbed hands and paws, and Leg Alloy Plating will now conflict with hooves, padded feet and toe talons.

#### Describe alternatives you've considered

Alternate, difficult to implement rework of the interaction between CBMs and Mutations that is beyond my skill level. Alternatively, make no changes and allow beaks but not snouts on your cyborg skin.

#### Testing

Testing process: Debug in mutations from this list. Attempt to install an Alloy Plating CBM. Get message saying it is not compatible with patient's body.
Disclaimer: I still need to test this at home, doing this on some slow hours at work. But hopefully these couple JSON changes won't break anything, and if need be I do testing in 8 hours from now or so.

#### Additional context

(First time doing a PR, tell me if I'm getting some stuff wrong. TY)
UPDATE: Added protection from alloy plating to hands and feet. Previously your feet and hands were bare, I didn't know that! Hopefully this is acceptable as well.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
OK, I'm very silly. Alloy actually *doesn't* protect the hands and feet! OK, so the question is: should it? Or should it not?

**Comment by anoobindisguise** [comment]
The current slot usage of the arm alloy plating may cause it to push prototype cyborg over its limit if bionic slots is installed as well. Will need to address that, maybe by making one of the faulty cbms use fewer hand slots.

**Comment by Maleclypse** [comment]
> The current slot usage of the arm alloy plating may cause it to push prototype cyborg over its limit if bionic slots is installed as well. Will need to address that, maybe by making one of the faulty cbms use fewer hand slots. Candidates include Fingertip Razors (2 - not faulty), Itchy Metal Thing (1) and Self Locking Thumbs (1) - I favor IMT since it has the least strong connection to "hands". Or Fingertip Razors can be buffed.

Só currently if you start over the slot count the only issue it causes is you can’t add more until you eliminate some. I’m hoping Ramza’s transhuman rework goes in soon as it has a different method of handling slots.

**Comment by anoobindisguise** [comment]
Closing this for now, I'll resubmit it more completely.

**Pull request closed without merging**
