### PR TITLE
Added coverage to underbrush

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: None```

#### Purpose of change
Driving over underbrush breaks vehicle headlights etc.

#### Describe the solution
Adding the `nocollide `flag to all 5 variants of underbrush.

#### Testing
Drove over some underbrush with a vehicle without damaging it.

Edit: Per feedback and requested changes, I've changed the nocollide flag to 40% coverage to match the rest of the shrubs.

### CODE REVIEW

**Comment by RarkGrames** [comment]
The description talks about "small plants and shrubs", this implies that the shrubs are small enough to bend when driven over and won't do damage to the car, except scratching the finish. Not something that would damage and break parts on the vehicle.

What changes are you suggesting?

**Comment by I-am-Erk** [comment]
I think that's meant to be "smaller than trees". I picture something like this:
https://www.lawnsite.com/attachments/hibernia-rd-004-jpg.218357/

I believe what Kevin is saying is that we need to work out vehicle clearance probably from wheel size before we say they can all clear the underbrush whether they're on 24" tires or 4" casters

**Comment by RarkGrames** [comment]
After looking through the whole file, I noticed underbrush has no coverage (as opposed to the rest of the shrubs with 40 coverage), so I would think that this is not higher than knee level. If it is intended to be more massive foliage, then it would be a good idea to add coverage here too, and modify the description.

That being said I'm not hell-bent on this whole subject, I'm even fine with leaving as it is and closing the PR.

**Comment by I-am-Erk** [comment]
It would be reasonable to give it some coverage I think.

**Comment by RarkGrames** [comment]
What about changing the description?

**Comment by I-am-Erk** [comment]
I don't think there's anything really wrong with the description, but I have no strong opinions on it one way or the other

**Pull request merged**
