### PR TITLE
added mechanical winch and metal gate to construction menu

### PR DESCRIPTION
**Pull request by OromisElf**
#### Summary
Content "added mechanical winch and metal gate to construction menu"

#### Purpose of change

give the player a different gate type door to build other than the palisade gate

#### Describe the solution

Once the player has enough experience with mechanics and fabrication, they can construct a mechanical winch next to a reinforced concrete wall. They can then construct a metal gate next to that same reinforced concrete wall to open it. The materials from the mechanical winch are free styled and may not be at all what is desired; the metal gate pretty much needs about 2.5x the materials of a normal metal door.

#### Describe alternatives you've considered

not making this addition; having floor requirements (like concrete), doing different materials

#### Testing

I built a winch, a reinforced concrete wall and a metal gate with hammerspace and confirmed the gate could be opened and closed. For my change that removed the concrete floor requirement I only started the game to see if it'd throw errors.

#### Additional context

the gate doesn't actually need walls on both sides to be opened/closed, but I kept the description since it would be ineffective if there wasn't a wall to the right

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I'd definitely like to see an extension to the set of materials the wall and the floor can be constructed from (although any kind of winch + metal door is a big improvement over nothing).

I'd also consider removing the floor requirement for the winch(es), because that would allow some flexibility in their usage (such as placing one inside a non concrete building that doesn't have an odd concrete floor/roof tile, and one outside on the ground, again without the requirement to place it on concrete, like the ones that are present for private home garages generated by the game).

**Comment by OromisElf** [comment]
the floor requirement for winches and metal gates is in place because both have a concrete tile as "background" (for the metal gate it's only seeable when it's open); would you be fine with "merging" the _concrete floor_ cost into the winch? after all a good winch needs a good foundation :D

**Comment by PatrikLundell** [comment]
The "graphics" being "hard coded" to a specific background is a problem that's probably a rather large issue to tackle (and probably well out of scope for this PR).

My personal preference would be to allow construction on any surface and hand wave the looks away in order to get access to the functionality, but I can definitely see that being offensive to the sensibilities of some people.

A problem with baking the floor into the cost of the winch is that people who've already "paid for" a concrete floor would be charged for it again.

I would expect that a winch wouldn't need an enormously strong and/or heavy foundation, but that mostly any kind of "real" floor would do. Metal would certainly work, I'd expect a wooden one would as well. Resin would work only if you could actually make holes in it so you can fasten the winch, while dirt or wood chips obviously wouldn't provide any support. I'd expect both normal and reinforced concrete to be usable.
However, it should be technically possible to mount the winch on the wall rather than on the ground, even though that wouldn't be reflected in the graphic representation, and in that case you'd need a wall material that's strong enough, which would be most of them (I'm doubtful about the sod one).

**Comment by OromisElf** [comment]
sounds like a valid and fair standpoint; will change it

**Pull request merged**
