### PR TITLE
Visual aid for broken limbs

### PR DESCRIPTION
**Pull request by OzoneH3**
* Limb is broken

* Limb is mending with a splint (Progress bar with # every 20%)

* Percentage display with self aware

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Suggestion:
Have it fill with `#` when mending and display exact mend percentage for self-aware.
You can get mending percentage with:
```
static const efftype_id effect_mending( "mending" );
const auto &eff = u.get_effect( effect_mending, part );
float mend_perc = eff.is_null() ? 0.0f : ( static_cast<float>( eff.get_duration() ) / eff.get_max_duration() );
```

**Comment by Treah** [comment]
@Coolthulhu 
OOOOOooooo that would be awesome instead of having a vague guess on the @ screen.

**Comment by Leland** [comment]
This looks really, really good

**Comment by OzoneH3** [comment]
> Have it fill with # when mending and display exact mend percentage for self-aware.

Done.

**Comment by Broken-Admin** [comment]
This'll be great keep it up @OzoneH3!

**Comment by angoddu** [comment]
I love it

**Pull request merged**
