### PR TITLE
Fix vitamin inheritance not overwriting vitamin when needed

### LINKED ISSUE #75421: Animal Cooking Oil registers as a vegetable
### Describe the bug

Animal cooking oil counts as a vegetable for allergy purposes.

This appears to be because animal oil (cooking_oil2) is mostly a copy-from of vegetable cooking oil (cooking_oil), and as such inherits the veggy_allergen vitamin. They're both in drink_other.json

### Attach save file

trivially reproducible

### Steps to reproduce

1. Take "Hates vegetables"
2. Look at animal cooking oil

### Expected behavior

animal products are not vegetables

### Screenshots

image
Will cause allergic reaction

image
Character is not meat intolerant, but does hate vegetables

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 09410b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    My personal mod [terror_mod]
]

### Additional context

And yes, this does matter for cooked foods. As of changing over to the vitamin system, meat fried in vegetable oil counts as a vegetable and vice versa. Which makes sense for actual allergies, but reads a bit strange for the "allergy" traits that are flavored as preferences.

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #75421
#### Describe the solution
Apply code, suggested by Ehug
#### Testing
image
#### Additional context
Wtf is animal cooking oil? animal cooking oil is named tallow

### CODE REVIEW

**Comment by Terrorforge** [comment]
> Wtf is animal cooking oil? animal cooking oil is named tallow

Tallow and lard are (more or less) solid at room temperature and exist as solid items in the game, but they have to be rendered into "animal cooking oil" before being used in oil-type recipes. I _guess_ this represents having to melt them before using, but that seems like an unnecessary step to add in 99% of cases.

**Comment by GuardianDll** [comment]
It is an unnecessary step indeed, your pan do not work at room temperature
I say this as a person who uses tallow in cooking, using it is like using a butter

**Comment by Maleclypse** [comment]
So the assumption is that you can buy animal fat cooking oil which I’m not sure you can.

**Comment by GuardianDll** [comment]
Nevertheless i think we should get rid of it

**Comment by dynst** [comment]
> Wtf is animal cooking oil? animal cooking oil is named tallow

There's even been a comment pointing out that `cooking_oil2` does not exist since #62180.

https://github.com/CleverRaven/Cataclysm-DDA/pull/62180/commits/3a0f157563a12338f61d2100fdf3538bec0774fb

https://github.com/CleverRaven/Cataclysm-DDA/blob/4508944ecc70d5ca3570029cad071a83e0d88403/data/json/recipes/recipe_food.json#L706

**Comment by GuardianDll** [comment]
yeah, ideally someone would step in and just decrease the weight and volume of lard and tallow; i would've made it by myself, but i stuck at step where i replace cooking_oil2 with tallow and lard, just because i am not very familiar should i use it in all places cooking_oil2 is used or not (like baking)

**Pull request merged**
