### PR TITLE
Capitalize all mod titles

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by mugling** [comment]
Merge conflict with #18366

**Comment by Cyrano7** [comment]
@mugling Fixed

**Comment by mugling** [comment]
What was the motivation here? If it was consistency (I haven't checked) these mods were actually correctly capitalized.

**Comment by Cyrano7** [comment]
All the mod titles have every word capitalized except for "and". Its for consistency. When creating a new world it looks odd that a few are different.

**Comment by mugling** [comment]
Consistency is important. It might be better to do the inverse and convert all the bad titles to more correct casing?

**Comment by Cyrano7** [comment]
I think it looks good how it is. But we can see what other people think.

**Comment by mugling** [comment]
Fair enough. It's not a critical issue either way

**Comment by Rivet-the-Zombie** [comment]
I rather like the capitalized version.

**Comment by mugling** [comment]
No point in otherwise holding this up then. Good to see you back around @Cyrano7

**Comment by Karlieb** [comment]
It looks like proper English grammar now (not something I complain about but something that always makes me happy when fixed). Thank you!

**Pull request merged**
