### PR TITLE
Liquid bandage spray

### PR DESCRIPTION
**Pull request by cake-pie**
#### Summary
Content "Liquid bandage spray"

#### Purpose of change
:warning: Requires #63434, which was split off from this PR.

Demonstrate/leverage new feature added in #63434.

#### Describe the solution
Adds a new item, liquid bandage spray, a healing tool that uses charges.

- [x] todo: add to itemgroups, spawn the item where appropriate

#### Testing
Debug damage self, debug spawn liquid bandage spray, use liquid bandage spray.

### CODE REVIEW

**Comment by Shodan14** [comment]
Would be cool to have some ad hoc wound wound supergluing as well down the line.

**Comment by cake-pie** [comment]
> Would be cool to have some ad hoc wound wound supergluing as well down the line.

Only if `superglue` is actually cyanoacrylate. The item description "a tube of strong glue" kind of suggests it might be, but there is also a recipe to make it which definitely rules it out.

**Comment by Shodan14** [comment]
> > Would be cool to have some ad hoc wound wound supergluing as well down the line.
> 
> Only if `superglue` is actually cyanoacrylate. The item description "a tube of strong glue" kind of suggests it might be, but there is also a recipe to make it which definitely rules it out.

Yeah, I guess there's a bunch of backend work for that. It really should be a liquid with each use using some amount rather than just "a superglue". Then you could also make it in reasonable amounts.

**Comment by cake-pie** [comment]
No, I meant that the `superglue` that currently exists in game has a recipe that allows it to be made from bones or hide or pine pitch etc, therefore it is definitely not cyanoacrylate.

**Comment by cake-pie** [comment]
I know, I looked at it and decided it was easier to just make a new distinct item for this rather than deal with the problems associated with making superglue into proper cyanoacrylate and giving it the heal action.

**Comment by bombasticSlacks** [comment]
Conflicts with your other PRs where the spray is tucked in the middle of lists. Afterwards, this is g2g.

**Comment by cake-pie** [comment]
Conflicts were expected and have been resolved.

**Pull request merged**
