### PR TITLE
 Additional color variations (blue, pink, etc.) for vanilla hairstyles that didn't have them

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Content "Additional color variations (blue, pink, etc.) for vanilla hairstyles that didn't have them"

#### Purpose of change

Reopens #62657 

#### Describe the solution

- Reopen PR
- Add new trait to trait group

#### Testing

Load without error

image

image

Those colours are set to be pretty rare so I didn't manage to see tham appear in NPCs

#### Additional context

We should probably migrate the old trait to this new variant structure

### CODE REVIEW

**Comment by KilroyWasHere451** [comment]
Hi, I appreciate you opening this up again in a new PR, and it's far more professional looking, that's for sure.   But since this is my first contribution, and I was just having trouble with the linting, I was wondering if you'd still be willing to let my PR have a crack at being added.

**Comment by Fris0uman** [comment]
You still get credit for doing the work, I've just added a few commits on top of you work. When this gets merged into the game your name will appear has author of this addition

**Comment by KilroyWasHere451** [comment]
> You still get credit for doing the work, I've just added a few commits on top of you work. When this gets merged into the game your name will appear has author of this addition

Ah, very nice!  In that case, I appreciate you reopening this, as well as the additions you made.  I didn't even think to add the spawn chance for these mutations.
Do you think it would be a good idea to close my original PR (again lol), or leave it open?

**Comment by Fris0uman** [comment]
I've just closed it. You can work a new thing now if you want :+1:

**Comment by KilroyWasHere451** [comment]
Cool, thank you very much.  Glad that someone more experienced was able to help me get my first contribution out there!

**Pull request merged**
