### PR TITLE
Fixed issue making game literally unplayable

### PR DESCRIPTION
**Pull request by Saint-of-Grey**
#### Summary
SUMMARY: Bugfixes "Fixed glaring typo in NPC dialogue"
#### Purpose of change
This change is to bring the game to a playable state once more.
#### Describe the solution
I replaced "you're" with "your" in the line "Because I'm you're friend".
Didn't touch any of the translated text, hopefully those are reflective of the grammatically correct sentence.
#### Describe alternatives you've considered
There are no alternatives, the game cannot be played in it's current state.
#### Additional context
Sharing is nice, and when I found out a good amount of people in a discord server I'm in play CDDA, I brought up the fact I'm a contributor. One of them then said the game has been unplayable for months and brought this issue to my attention. 

I had to take action.

### CODE REVIEW

**Comment by DemAvalon** [comment]
not all heroes wear capes.

**Comment by kevingranade** [comment]
Please revert the changes to the .po files

**Comment by Mecares** [comment]
>"Because you're my friend".

You forget the "I am" that  makes the sentence literally unplayable in your description.

**Comment by Saint-of-Grey** [comment]
> > "Because you're my friend".
> 
> You forget the "I am" that makes the sentence literally unplayable in your description.

You saw nothing, it was like that all along.

**Comment by AMurkin** [comment]
> it was like that all along.

@Saint-of-Grey 
image

**Pull request merged**
