### PR TITLE
Sidebar info2: minor cosmetic changes

### PR DESCRIPTION
**Pull request by nsklaus**
#### Summary
```SUMMARY: Interface "cosmetic changes for the sidebar"```  

#### Purpose of change
I am proposing some minor cosmetic changes for the sidebar. 
some swapping and alignment, to make it look better.

#### Describe the solution
 here's what i've done:
- swapping position of stamina and power
- put the Empty / Full gaz gauge on same line as other driving related strings 
- put the mood smiley into a better place
- put the "SAFE" string into a better place
- disabled the displaying of power while we are showing vehicle controls

maybe some other minor changes like that here and there.
please see attached screenshots

#### Additional context
normal mode: (note power and stamina position swap, also SAFE and smiley position)
screenshot_20190116_153500

wide mode:  (also showing stamina and power in their new position)
screenshot_20190116_153444

showing vehicle controls: (note Empty / Full gauge on same line as other vehicle related things)
screenshot_20190116_153912

### CODE REVIEW

**Comment by KorGgenT** [comment]
But how will you know how much stamina you have while riding a bicycle?

**Comment by nsklaus** [comment]
> But how will you know how much stamina you have while riding a bicycle?

good question, i didn't think of that. 
i probably shouldn't hide stamina while displaying vehicle control then.

**Comment by nsklaus** [comment]
@Night-Pryanik @ZhilkinSerg @mlangsdorf @kevingranade
Any of you guys know what's going on with Travis, failing in timeout ?
it was the same yesterday for a bug correction i did, i've changed one word, a bool from false to true and i got that timeout error too. Can i do something about it, or is it fine to ignore that ?

**Comment by Night-Pryanik** [comment]
Don't pay much attention to it, it often declares false errors.

**Comment by nsklaus** [comment]
> Don't pay much attention to it, it often declares false errors.

ok, thanks for telling.

**Comment by jbytheway** [comment]
It looks like bionic power will now run off the screen once it exceeds 3 digits.  And changing the format string to `%-4d` would only improve that to 4 digits; I've seen people reach >5000 power, so I suspect some players exceed 10000 (maybe there's some hardcoded limit; I'm not sure).  With the old positioning it could overflow to the right a bit, but now that won't work.

**Comment by nsklaus** [comment]
> It looks like bionic power will now run off the screen once it exceeds 3 digits. And changing the format string to `%-4d` would only improve that to 4 digits; I've seen people reach >5000 power, so I suspect some players exceed 10000 (maybe there's some hardcoded limit; I'm not sure). With the old positioning it could overflow to the right a bit, but now that won't work.

ah yes this is correct, i didn't know power value could exceed 3 digits.
hum, if power value could go up to 5 digits then this makes it impossible to have power located where i've put it. i have to re-think this through again.

**Comment by jbytheway** [comment]
> ah yes this is correct, i didn't know power value could exceed 3 digits.
> hum, if power value could go up to 5 digits then this makes it impossible to have power located where i've put it. i have to re-think this through again.

You should double-check if there is some kind of maximum; as I said I'm not sure.

**Comment by nsklaus** [comment]
> > ah yes this is correct, i didn't know power value could exceed 3 digits.
> > hum, if power value could go up to 5 digits then this makes it impossible to have power located where i've put it. i have to re-think this through again.
> 
> You should double-check if there is some kind of maximum; as I said I'm not sure.

yes but, now that i think about it,
displaying 10000 it would have not worked correctly in wider view either, i mean even with the old position. it would have been truncated with displaying the map. maybe there's something to do about displaying a too high number ?

**Comment by nsklaus** [comment]
> > ah yes this is correct, i didn't know power value could exceed 3 digits.
> > hum, if power value could go up to 5 digits then this makes it impossible to have power located where i've put it. i have to re-think this through again.
> 
> You should double-check if there is some kind of maximum; as I said I'm not sure.

after a quick check, i did not find a limit in the amount of max_power_level
as an idea: before displaying the number, i could check how many digit the number has, and just divide it to have a 3 digit number to display without changing the actual value ?
what would you think about this ?

**Comment by nsklaus** [comment]
how can i raise my power level to 1000 or more to test the new code ?

**Comment by jbytheway** [comment]
* Bind a key to the debug menu.
* Use the debug mutate option to give yourself the "Debug Bionic Installation" trait.
* Use the debug wish option to wish for a bunch of power storage CBMs and some CBM to generate power.
* Activate them all to install.
* Generate power somehow (I suspect the Battery System CBM would be the fastest option; just have to wish for lots of batteries).

**Comment by nsklaus** [comment]
>     * Bind a key to the debug menu.
> 
>     * Use the debug mutate option to give yourself the "Debug Bionic Installation" trait.
> 
>     * Use the debug wish option to wish for a bunch of power storage CBMs and some CBM to generate power.
> 
>     * Activate them all to install.
> 
>     * Generate power somehow (I suspect the Battery System CBM would be the fastest option; just have to wish for lots of batteries).

thanks, i also tested with mutating -> debug bionic power, it adds more power by increment 100.
but, all this is done with the debug menu (cheating) is there a normal way for player to install cbm or anything and have all this making their bionic power to exceed 999, without using debug menu, the normal way, playing by the rules ?

**Comment by AMurkin** [comment]
Print thousands when power > 999, maybe?
1k, 15k, 62k.

**Comment by nsklaus** [comment]
> Print thousands when power > 999, maybe?
> 1k, 15k, 62k.

Thanks for coming in and sharing your thoughts on this.
what you propose is a good idea, 
but i also have to ask: is it necessary to let the player power level to reach such high values ? if yes then capping to 999 is a mistake. if not, then 999 cap should be ok.
i don't know the game enough yet to understand if it is intended or not to let them have such a large storage of power. In any case, having a max value somewhere should probably be a good thing.
the question is if 999 is enough or not.

**Comment by AMurkin** [comment]
You need 1k power to jump through four 1-tile width walls with probability travel. Plus you may use additional CBMs at this time.
Aero-evaporator CBM uses 200 units.
I think it should display values larger than 999.

**Comment by nsklaus** [comment]
> You need 1k power to jump through four 1-tile width walls with probability travel. Plus you may use additional CBMs at this time.
> Aero-evaporator CBM uses 200 units.
> I think it should display values larger than 999.

ok, thanks for telling. i'll go and try to implement the idea you suggested earlier.
about the cap though, should i remove it completely or just raise it to say for example 5k or 10k or more ?

**Comment by Night-Pryanik** [comment]
> should i remove it completely or just raise it to say for example 5k or 10k or more ? 

Capping bionic power is a good question, but it isn't related to the theme of this PR and should be thoroughly discussed elsewhere prior to implementation. I'd say remove it completely for now.

In any case, there should be at least some message indicating why bionic power isn't increasing further some threshold. Ideally it should be prohibited at the moment of installation, otherwise players will simply lose CBM, anesthesia and their time on nothing.

**Comment by nsklaus** [comment]
> > ```
> > * disabled the displaying of power while we are showing vehicle controls
> > ```
> 
> **WHY?!** This one actually has gameplay relevance, both in terms of activating CBMs knowingly (health-related stuff like Blood Filter/Radiation Scrubber) and in getting valuable reminders on anything you might have forgotten to turn off such as Dielectric Capacitance or Thermal Dissipation after fleeing from the related hazard in your vehicle.
> 
> Based on your screenshot the vehicle layout has space to the right of the body temperature text ("chilly"). What were you trying to accomplish in the first place, hiding information like bionic power and stamina even though they continue to change while driving?

i planned to solve a lot of problems with _this_ particular feature, if you must know. 
it's a very complex calculation i made, it's based on inverted and extrapolated butterfly effect: one variable hidden from the sidebar, one angry gamer and the world hunger problem gets solved. you must suffer for the good of others, congratulation. you're welcome.
no but more seriously don't fear, i was not the main point of this PR, but just a side thing i did in passing. i just thought those were unnecessary in that context. but if this not the case we can bring it back if this is desirable. the point of the PR was to continue the tidy up work that got started on the sidebar.  so more updates like this one will happen, and sometimes along that update process little mistakes can be made. if they are indeed mistakes, they will get noticed and corrected.

**Comment by Poragon** [comment]
Bionic power in vehicle control tab is an important bit of information, at least for myself personally and I imagine all those who also use cable charger CBM as their primary method of charging a bank of bionic power. Always good to know if you're rearin' and ready to hop off the wheel and decimate the nearby horde with lightning or if you need to do another lap around the city 'till you're good to go.

**Comment by nsklaus** [comment]
> Bionic power in vehicle control tab is an important bit of information, at least for myself personally and I imagine all those who also use cable charger CBM as their primary method of charging a bank of bionic power. Always good to know if you're rearin' and ready to hop off the wheel and decimate the nearby horde with lightning or if you need to do another lap around the city 'till you're good to go.

it's coming back thanks for the heads up.

**Comment by Treah** [comment]
Is there not another Contributor that is rewriting the UI interface as well? I would hate you put work into something just for it to be trashed by another PR.

**Comment by EldritchHorror** [comment]
Very pointless change that did nothing but confuse players and appeal to the contributor's own sense of aesthetics.

Not as bad as their whole redesign of the sidebar but getting there. Here's hoping this gets reverted.

**Comment by nsklaus** [comment]
> Is there not another Contributor that is rewriting the UI interface as well? I would hate you put work into something just for it to be trashed by another PR.

@Treah 
thanks for that comment,
but, it's fine with me .. i propose ideas and bits of code, if it gets accepted fine if it doesn't, well that's how it works.
i understand that not everything produced will get included. and i'm building a little cpp experience out of this, so it's all good. by the way, i didn't know that someone else was working on UI update. it's good to hear, i wonder what will it look like. is there any info, preview or mockup about it that i could look at ?

**Comment by EldritchHorror** [comment]
Seeing as this pull probably isn't going away, given Kevin's douchy responses - can you at least bring back the mood icon inside of vehicles? It's important to know and I don't know why you keep hiding all this stuff.

**Comment by KITbutler** [comment]
> Seeing as this pull probably isn't going away, given Kevin's douchy responses - can you at least bring back the mood icon inside of vehicles? It's important to know and I don't know why you keep hiding all this stuff.

What the hell, mood too? Okay, simple step-by step:

- Driving is a dedicated character skill
- Skills are leveled by performing related activities, this drains Focus
- Other than this drain the current rate of change for said Focus is determined by Morale/Mood

How can such a core, simple game mechanic be ignored? How can we **trust** someone who displays such a careless attitude towards core gameplay mechanics to properly handle the core UI of the game?!

**Comment by EldritchHorror** [comment]
Great. But can we also have the stamina bar back where it used to be?

Just for those with already formed eye coordination habits?

**Comment by azaelous** [comment]
Yknow, I just really don't see the point of this. Everything is already fine where it was before.

**Comment by Bidiguilo** [comment]
Hey, can I make a suggestion? I think the Stamina bar and the Bionic Power bar would be better if they were not swapped. It is hard to locate the Stamina because when you're all green, you can confuse the stamina for your R leg and accidentally waste some bandages. Also, the PER and PWR really close to each other are kinda hard to separate and locate from just a glance. Just some quality of life things! I don't know anything about modding but that would be a nice addition.

**Pull request merged**
