### PR TITLE
add recipes for fruit and veggy seeds

### PR DESCRIPTION
**Pull request by Reclusive-reptile**
plus pumpkin seeds as byproduct of mashed pumpkin. I tried to keep this as uncontroversial as possible, thus no seeds from grains (aside from corn), or veggy propagated via root cuttings or are not present with intact seeds at market. After #18262 was closed due to inactivity I wanted to jump on this as it seems logical and needed.

### CODE REVIEW

**Comment by mugling** [comment]
Will merge conflict with #18286

**Comment by Reclusive-reptile** [comment]
So can no crafting recipes be merged until that goes through? I'm not code savvy enough to understand what your refactor actually does.

**Comment by mugling** [comment]
Avoid any recipes that specify `byproducts`

**Comment by Reclusive-reptile** [comment]
Okay, how would I revert the addition of a byproduct to avoid conflicts. I am new to git hub.

**Comment by mugling** [comment]
Looking at your PR you'd be best doing it again after #18286 as the same PR lets you write template recipes (I'll give you an example once #18286 is merged)

**Comment by Reclusive-reptile** [comment]
closing pending #18286

**Comment by WizardOfOoo** [comment]
#18286 is merged.  Are we ok to work on this now?  Maybe we need a new PR?  This one is cluttered.

**Pull request closed without merging**
