### PR TITLE
Fix compile error finding gunmods that suppress sound

### PR DESCRIPTION
**Pull request by FlaKougar**
Fix broken tiles builds on build 4497
Fixes Issue #15633

### CODE REVIEW

**Comment by mugling** [comment]
Thanks for reporting. Have you tried including `itype.h`?

**Comment by NickGrease** [comment]
> Have you tried including itype.h?

That almost solves the problem. @mugling on your commit, you're missing a ')' on line 578 of sounds.ccp 
With that fixed it compiles fine. ty.

**Comment by mugling** [comment]
@NickGrease yes. I'm surprised that both clang and the buildbot accepted #15617 as-is

**Comment by narc0tiq** [comment]
The buildbot can't do all seven builds in reasonable time, so it only does a lincurse build (which is clang). If I were to switch it over to do tiles builds, we'd get incomplete coverage on curses, so there's not much to be gained there.

And, of course, if something is preprocessor'd out, no compiler will complain about it because it never got to see it in the first place.

**Comment by mugling** [comment]
@narc0tiq that's useful to know. TBH the performance of the buildbot is very respectable considering.

**Comment by mugling** [comment]
> This is my first time! New to pr's/git/github/c++/gcc and everything in between

@NIckGrease I'd like to encourage you to keep trying. Concise reporting is very helpful and trivial fixes like this are ideal for becoming familiar with submitting PR's.

**Comment by NickGrease** [comment]
@mugling Thanks for the encouragement. It's been a learning experience, that's for sure. Still working out a few kinks in the process, but I hope to be a regular contributor in the future. Thanks again.

**Comment by FlaKougar** [comment]
#15635 is a cleaner fix. Closing.

**Pull request closed without merging**
