### PR TITLE
Fix categorisation of water

### LINKED ISSUE #16321: Hip flasks filled with water are classified as ammo
Water is ammo (for water cannon), but its primary function is being a comestible. Comestible type should have higher priority than ammo.

### PR DESCRIPTION
**Pull request by mugling**
Fixes #16321

### CODE REVIEW

**Comment by Cyrano7** [comment]
In jsons should the standard style be spaces around colons of just spaces to the right of them?

**Comment by mugling** [comment]
All of the migrations I've done (which is now a tens of thousands of lines) have used this format. The same issue applies to indentation (2 vs 4 spaces). Consistency within a file is the most important factor followed by actually making progress cleaning up the JSON.

In the absence of an automated formatting tool (not worth the considerable effort) try to make the JSON both compact and easy to read.

**Comment by kevingranade** [comment]
I'd also lean toward standardizing on what mugling has done. I don't much
care about the formatting details as long as they're sensible.

**Comment by Cyrano7** [comment]
@kevingranade Ya I realized yesterday that he has being been putting spaces on the right of colons and not the left and I've been putting spaces on both sides. I'll let you be the tie-breaker, moving forward whats the standard?

**Comment by mugling** [comment]
We do need to consider standardising on the ordering of fields as that does make some difference to the readability

**Comment by kevingranade** [comment]
I'd personally lean toward padding both sides, but for practicality sake
would prefer whichever is used by the largest body of styled json, which I
believe is the gun/magazine/ammo json that has been converted.
I'm against enforcing a particular field ordering.  I'm not convinced
there's a consistent ordering that will be beneficial in all cases, and
it's a hell of a lot of churn to get all the json there in the first place.

**Comment by mugling** [comment]
> it's a hell of a lot of churn to get all the json there in the first place.

it would only be worth it when implementing new files or migrating old ones

**Comment by kevingranade** [comment]
It's not worth it at all if we aren't even trying to migrate everything
there eventually.
If you want to pick an ordering for json you write or convert, no problem,
I just don't want to mandate an ordering for everyone, potentially blocking
merges, if we aren't driving a campaign to get all if it there eventually,
and supporting it with tooling.

**Comment by mugling** [comment]
I've got as a far as `jq` dropping redundant fields, sorting the entries by `id` and then ordering the fields. It can't do formatting and there's no simple way to extend it to do so

**Comment by Cyrano7** [comment]
@mugling You have a tool now?

**Pull request merged**
