### PR TITLE
add tele_sight to itemgroups

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: Content "add telescopic sight to itemgroups"```

#### Purpose of change
tele_sight can only be obtained trough crafting. This PR fixes that.

#### Describe the solution
Add tele_sight to the same itemgroups as improve_sights:

gunmod_common -> improve_sights(60)
military -> improve_sights(10)
drugdealer -> improve_sights(10)
map_extra_drugdeal -> drugdealer(75) -> improve_sights(10)
npc_misc -> improve_sights(1)
NC_JUNK_SHOPKEEP_misc -> improve_sights(20)
NC_EVAC_SHOPKEEP_misc -> improve_sights(20)

#### Describe alternatives you've considered
Leaving it as-is

#### Testing
image

#### Additional context
The NC_EVAC_SHOPKEEP_misc is a little weird I think because the result seems disproportionate and I think it is cause by allowing it to spawn items and itemgroups, which will give items such as the tele_sight a bigger spawn chance then items from itemgroups in that same itemgroup. Maybe something for another PR.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
So much no. The handmade telescope is a simple refractor/gallilean or similar telescope made of ~2 elements. It isn't even close to the same quality as a cheap tasco or chineseium scope.

If it spawns, it should only be alongside handmade survivor equipment.

Usable scopes like this could even be magnifying, but also inverting, in design, and they're far from ideal. 


An alternative would be to add this style of **telescope**  to the game, and have the handmade scope use it as a simpler recipe.

**Comment by snipercup** [comment]
Nowhere in the item's description does it imply it is hand-made even though you can make it by hand.

**Comment by tenmillimaster** [comment]
Reference #23526, when they were introduced.  Making pre-cata scopes was discussed; the sights that were able to be made are not those.

**Comment by ZhilkinSerg** [comment]
I've reverted this pull request, so we can be discussed further.

**Comment by snipercup** [comment]
I can agree on items crafted by a survivor not being allowed to spawn in the same group as pre cataclysm items. I will cancel this pr. Would you agree that the description of the tele sight should be changed to reflect the fact it is no more then a crafted telescope with a crossheir?

**Comment by tenmillimaster** [comment]
Yeah, that sounds reasonable. The items showing up in post cata shops is a good addition imo.

**Pull request merged**
