### PR TITLE
Suppress debug message when dragging furniture off the ledge

### LINKED ISSUE #78828: Pushing furniture off the ledge results in a debugmsg error
### Describe the bug

- Have a furniture (such as a table) above ground, on a roof
- Grab it
- Move it to the edge so it falls down
- Get error
```
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1830 [furn_set] Setting furniture f_table at (67,67,1) where terrain is t_open_air (which is_open_air)
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture
```
- The furniture does fall down tho

### Attach save file

[debug-world-remote-trimmed.tar.gz](https://github.com/user-attachments/files/18268387/debug-world-remote-trimmed.tar.gz)

### Steps to reproduce

see above

### Expected behavior

no error

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5247 (22H2)
- Game Version: 163ee18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
None

#### Purpose of change
* Closes #78828.

#### Describe the solution
Added a new parameter for `furn_set` function which allows suppressing showing of debug message, default to false. Applied this new parameter for cases of dragging furniture off the ledge and deploying furniture on open air. Removed now-unneeded `ALLOW_ON_OPEN_AIR` flag from stepladders (as furniture).

#### Describe alternatives you've considered
None.

#### Testing
- Dragged chair off the ledge. No debug message.
- Deployed stepladder on the open air. No debug message.

#### Additional context
None.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Do the tests really cover everything that should be covered? It seems the negative tests are missing.
What happens if you try to deploy something that should fall (i.e. non step ladder furniture)? Will it refuse to be deployed, and, if not, will it fall as it should?

Also, I assume the chair, which probably was pushed off the ledge (unless the PC was flying) was confirmed to fall as it should (no reason to assume it wouldn't still fall when a message is removed, but still).
Similarly, I assume the step ladder didn't fall.

**Comment by Night-Pryanik** [comment]
I'm afraid you're misunderstanding the gist of this PR. This PR is NOT about furniture falling down or not. Non-deployable furniture not falling down was addressed years ago in #47751. Deployable furniture not falling down was addressed in #77083. So, in short, furniture is falling down as it should, both deployable and non-deployable.
This PR is trying to address an issue of debug message showing up when dragging furniture off the ledge.

**Comment by PatrikLundell** [comment]
I did understand what the PR addresses, but I still think it's reasonable to test that there aren't any unexpected side effects, i.e. that the previous behavior remains unchanged.

**Comment by Night-Pryanik** [comment]
My tests showed that furniture is falling as it was previously. I didn't notice any unexpected side effects or changes in furniture falling behavior. The only thing that changed is debug message no longer showing up when furniture is dragged off the ledge.

**Pull request merged**
