### PR TITLE
Offroad autodrive

### LINKED ISSUE #49449: Feature Request: Autodriving Off-Road
Currently, Autodriving is only available when on roads, it would be great to autodrive on trails or in the woods, as exploring the forest is one of my favorite activities in-game.

### LINKED ISSUE #50378: Overmap pathfinding for amphibious vehicles goes over land and does not avoid forests
### Describe the bug

When attempting to autodrive with an amphibious vehicle, it does not limit routes only to roads, and creates routes through the middle of forests.

### Steps To Reproduce

1. Spawn in a DUKW
2. Attempt to drive to somewhere far away from your current location on the overmap, or separated from you by a large forest
3. Watch as autodrive refuses to route you through a forest.

### Expected behavior

1. Autodrive does not attempt routes which will never be pathable.
2. The rules for whether or not you can drive off road are the same for amphibious and non-amphibious vehicles (except water is allowed for amphibious ones)

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Arch, kernel 5.13.5
- Game Version: 0.F-1200-g61be774194 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

bug

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Features "Offroad autodrive"

#### Purpose of change

This is the second PR in the Fast Travel project (#49455)
This allows planning overmap paths for vehicles that aren't restricted to just roads. It also fixes some other issues with overmap pathfinding (see commit list).
Fixes #49449
Fixes #50378

#### Describe the solution

The main change is `overmapbuffer::get_travel_path`, which is an improved version of `get_npc_path` that takes a much more flexible configuration object (`overmap_path_params`) with weights for various terrain types set based on the properties of the vehicle being used (while also handling travel on foot).

Helicopters: only air
Boats: lakes, rivers and shore
Cars: roads, fields, farm road, ~shore~
Amphibious cars: can go where cars and boats can go
Bicycles: like cars but can also do forest trails
Walking: pretty much anywhere but water, unless already swimming or destination is a water tile; also prefer to avoid swamps and forests if possible

In addition, the car's "offroad coefficient" (seen in the vehicle information panel) will be used to assign appropriate weights for off-road vs on-road travel. A car with 100% offroad coefficient will treat field tiles as if they were roads. A car with <5% offroad coefficient will stick to roads.

Other changes:
- the starting OMT is always considered drivable regardless of what it is
- when generating the overmap path start with the tile that the vehicle is on (in some rare cases it's not the same as the tile the player is on)
- I included the various bridge road tiles in the match list for "road" but the current pathfinding algorithm can't go up a z-level so bridge navigation is not resolved in this PR. But if you manually drive up a bridge ramp you can then autodrive to the other end of the bridge if you want (then manually drive down the ramp).

#### Describe alternatives you've considered

I still need to rewrite `pf::find_path` to overcome its limitations (doesn't keep track of cost incurred so far and doesn't handle z-levels) and to fix performance/code clarity issues, but I decided to leave that for another PR.

I disallowed vehicles pathing through shorelines ("river" and "lake_shore" tiles) because for narrow rivers the shorelines of the 2 sides of the river are adjacent and it would seem that you can drive from one to the other, when in actuality you can't.

#### Testing

Car driving on field, road and farm road

https://user-images.githubusercontent.com/8000047/128775162-1cae9ba2-d7e1-4cfc-8e41-a1d76e995347.mp4

Biking on a forest trail

https://user-images.githubusercontent.com/8000047/128787883-3e005fa4-144c-47ee-a1d8-90e90fb3e41d.mp4

Amphibious vehicle on lake, field and river

https://user-images.githubusercontent.com/8000047/128790236-952f130d-1fb5-4739-8c44-77d77650e341.mp4

Inflatable boat on river

https://user-images.githubusercontent.com/8000047/128790808-6be1ca89-6b8c-4828-a6a9-b5a11fe5296f.mp4

Walking through a building

https://user-images.githubusercontent.com/8000047/128791644-719c5ea3-b259-4a9b-8b04-767108e2c0ee.mp4

Walking through the forest

https://user-images.githubusercontent.com/8000047/128791787-b1c39de5-57e8-444d-89bf-aa2a064d32b8.mp4

Going for a swim

https://user-images.githubusercontent.com/8000047/128792340-aebf1ed0-7e48-4196-bacd-a9389ba18eb1.mp4

Ill-fated flight

https://user-images.githubusercontent.com/8000047/128793516-e829e22b-3626-4598-b81c-dacbba3a866e.mp4

#### Additional context

Note the wacky into-the-building-and-out-the-same-way-again in the 5th video or the drunken swimming in the 7th video. Autowalk could use some work. I should probably change it to use the same algorithm as autodrive, at least for the waypoints, but my focus is on vehicles at the moment.

I also need to change the pathfinding algorithm to prefer diagonal paths (like up-left-up-left-...), which are faster, but I can't do that with the current `pf::find` since it only gives me 1 previous node and I need 2 for that. But as mentioned above I'll replace `pf::find` with something better in a later PR.

For anyone wondering about the crash: the helicopter rotor blades extend out a fair bit, even though you can't see them. Autodrive collision detection kicked in but I decided to keep going to see what happens. Normally you'd want to stay well away from flying creatures that are attracted to sound when flying a helicopter. Changing altitude helps too.

### CODE REVIEW

**Comment by actual-nh** [comment]
If you put `Fixes #49449` in the body of the PR, it _should_ close that issue when this is merged, BTW.

**Comment by eltank** [comment]
So I fixed the bug (std::vector(n) doesn't do what I thought it does), but I'm still testing.
I expect to be able to ride a bicycle on forest trails, but that's not working right now.

**Comment by anothersimulacrum** [comment]
I imagine https://github.com/CleverRaven/Cataclysm-DDA/issues/50378 is fixed too?

**Comment by eltank** [comment]
> I imagine #50378 is fixed too?

Yes, forests are not valid terrain for amphibious vehicles anymore.

image

**Comment by eltank** [comment]
Everything seems to be working as expected, so this is ready for review now.

**Pull request merged**
