### PR TITLE
Add earplugs to combat professions

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The US army currently issues earplugs to footsoldiers. Why should they stop doing so in the future?

### CODE REVIEW

**Comment by codemime** [comment]
All wearable items that players possess are worn at the very beginning of the game. Adding earplugs means that all of the fighters will start the game being deaf. That seems confusing.

**Comment by BorkBorkGoesTheCode** [comment]
Sorry, my damn internet connection malfunctioned.

I have created an issue to discuss that problem: #16624

**Comment by ifreund** [comment]
Broken Cyborg starts the game deaf, is this really a problem?

**Comment by Shoes01** [comment]
I think it's a problem only because it goes against expectations. A new player might not study in detail the loadout and miss that they are wearing earplugs. Not a big problem, but it should be fixed.

**Comment by Cyrano7** [comment]
@BorkBorkGoesTheCode If it's a issue your waiting for to be fixed to allow this PR to be merged you should close this and reopen it once your issue is fixed.

**Pull request closed without merging**
