### PR TITLE
MShock24 Tileset Modded Series 4

### PR DESCRIPTION
**Pull request by chaosvolt**
Well, I borked a handful of things, easily fixed. There is also a 32
version of this that's very WIP, slowly but surely working on respriting
things. For now, have an update.
1. Vehicle part sprite for mirrors and a few other such things should
   rotate now.
2. Flipped the mininuke and C4 haaaax. Everyone faces right on this
   tileset.

I have also seem anomalous shadows for some sprites that don't seem to be showing on GIMP, unsure of cause.

### CODE REVIEW

**Comment by stk2008** [comment]
This is fantastic news mate thank you

Been hoping for a 32 version of this :)

Thanks again

**Comment by chaosvolt** [comment]
I shall also blame SilverDragonLord over on youtube. Taking me a while to go sprite by sprite and remember how the hell I made each one.

**Comment by stk2008** [comment]
Well we all appreciate the hard workmate :)

**Comment by chaosvolt** [comment]
Not so much work as me mucking about with colorizing and pixel editing while asking myself "Wait, how the hell did I get this to not look awful the FIRST time?" constantly.

**Comment by chaosvolt** [comment]
Also noticed a handful of monsters in need of sprites, so will work on those when I'm not out and about on the laptop.

How do we have a zombie shark, but no regular shark? :v

**Comment by Rivet-the-Zombie** [comment]
>How do we have a zombie shark, but no regular shark?

Maybe all the regular,non-zombie sharks got eaten already? If anyone were to provide us with a normal bull shark PR, I would merge it.

**Comment by chaosvolt** [comment]
Though as I've never SEEN a jawed terror legit so far, and we lack worldgen for beaches, it could be sensible to assume most of the sharks aren't venturing upriver voluntarily.

**Comment by Rivet-the-Zombie** [comment]
Bull sharks go up rivers all the time. It's kinda their thing.

**Comment by chaosvolt** [comment]
Ah, that explains the existence of zharks in the first place. Doh. o3o

**Comment by chaosvolt** [comment]
On the one hand, I did not expect that it would take me this fucking long to finally get home.

On the other hand I was planning moar spriting, but...meh, I can do it another time. Thank you for the merge.

**Comment by pouar** [comment]
Awesome. The lack of a 32 version was why I haven't started using it yet

**Comment by chaosvolt** [comment]
Working on it bit by bit. Eventually I will PR it, though I might in turn PR it alongside a planned addition of a couple more sprites to the 24 version. Then again they might want me to keep them in separate PRs. >w<

**Pull request merged**
