### PR TITLE
Multicooker liquid fix

### LINKED ISSUE #30923: Multicooker spills liquid product into player's inventory.
# Describe the bug

If the final product cooked by multicooker is liquid it will be spawned in the player's inventory without any container or liquid transfer prompt.

# Steps To Reproduce

1. Obtain multicooker.
2. Set the recipe that yields liquid product.
3. Wait to craft completion and extract dish.

# Expected behavior

A standard dialog about what to do with liquid should appear, like the one during the usual craft.

# Screenshots

N/A

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-3534-gac86716
 - Graphics version: Tiles
 - Mods loaded: N/A

# Additional context

N/A

### PR DESCRIPTION
**Pull request by eilaattwood**
#### Summary
```SUMMARY: Bugfix "Multicooker liquid result behavior"```
#### Purpose of change
Fixes #30923 - Multicooker spills liquid product into player's inventory.
#### Describe the solution
Added check for liquid resulting product, set product temperature, call liquid handling dialog.
#### Describe alternatives you've considered
Bugs should be fixed. Not sure about treating temperature...
#### Additional context
N/A

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
You need to astyle your changes.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by eilaattwood** [comment]
I've just thought that resulting dish temperature shouldn't be defined by EATEN_HOT flag. Actually it should be defined by the fact of using a heat source in the recipe. I'll try to fix this later.

**Comment by eilaattwood** [comment]
Haven't tested last two commits, but everything should be fine...

**Comment by eilaattwood** [comment]
I've finished, PR is ready for review and merge.

**Pull request merged**
