### PR TITLE
Protein Ration Condom

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Content 

#### Purpose of change
We were talking about it in the discord and we thought it was hilarious, so I whipped this baby up.

#### Describe the solution
Adds a new variant of Condom

#### Additional context

https://discord.com/channels/598523535169945603/598523535169945607/1173685102719541288

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Too meta-commentary. Yes it's hilarious. It's not believable a fledgling brand would also launch a niche condom flavor or promotional partnership.

**Comment by fairyarmadillo** [comment]
Would go great in Crazy Cataclysm.

**Comment by Maddremor** [comment]
What tenmillimaster said, and there is also unrelated changes to `zed_soldiers.json`

**Comment by Fris0uman** [comment]
Not really credible and in poor taste, I think we'll pass.

**Pull request closed without merging**
