### PR TITLE
WIP Address 4 tile motorcycles single saddles

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary

SUMMARY: Content "Address motorcycle seat length"

#### Purpose of change

Address the changes suggested by MLangsdorf and Acepleaidies https://discord.com/channels/598523535169945603/598614717799596055/800743112556544011

#### Describe the solution
Adds additional saddles.

#### Describe alternatives you've considered
Not my issue

#### Testing
None needed

### CODE REVIEW

**Comment by Maleclypse** [comment]
Realized why I don't work in vehicles often as now all the tests are broken.

**Comment by actual-nh** [comment]
> Realized why I don't work in vehicles often as now all the tests are broken.

Given that there are statistical functions available, I am not sure why average_from_stat is just taking the midpoint (halfway between min and max), thus also enabling tests with confidence intervals. (Or were the statistical functions not available at the time these tests were created? Or would the statistical functions demand too many iterations for the slowness of the tests?)

**Comment by Maleclypse** [comment]
> > Realized why I don't work in vehicles often as now all the tests are broken.
> 
> Given that there are statistical functions available, I am not sure why average_from_stat is just taking the midpoint (halfway between min and max), thus also enabling tests with confidence intervals. (Or were the statistical functions not available at the time these tests were created? Or would the statistical functions demand too many iterations for the slowness of the tests?)

Probably best a question for Github Discussions or the discord?  I don't know the answer though.

**Comment by acepleiades** [comment]
The problem is that motorcycles have a box in that tile and it can't be on the same tile as the saddle.
I think it would be reasonable to allow a box and a saddle to exist in the same tile.

**Comment by Maleclypse** [comment]
> The problem is that motorcycles have a box in that tile and it can't be on the same tile as the saddle.
> I think it would be reasonable to allow a box and a saddle to exist in the same tile.

I'm currently leaning towards killing this PR and creating a vehicle part, motorcycle rear seat with saddlebags.  Would that solve issues?

**Comment by Nerezza** [comment]
I think "saddlebags" should be an acceptable new part that could be attached to a saddle.
In fact, I think we should keep the box motorcycles as-is and create a new two-saddle motorcycle with saddlebags.
While we're at it, perhaps a touring motorcycle with a "box and saddlebags" vehicle part for a little extra storage compared to the box ones?

**Comment by acepleiades** [comment]
> I'm currently leaning towards killing this PR and creating a vehicle part, motorcycle rear seat with saddlebags. Would that solve issues?

I think so, but I think a better name would be "rear motorcycle seat with box". It would be extra good if this vehicle part didn't allow vehicle controls on the same tile, but I don't know how these rules are set in game.

**Pull request closed without merging**
