### PR TITLE
Rework CROWS II turrets ammo drop

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
Balance "Rework CROWS ammo drop"

#### Purpose of change

`CROWS II` turrets drop a lot of ammo. While a `TALON UGV` robot drops up to 30 5.56mm ammo, a 5.56mm CROWS II turret drops `1600` 5.56mm ammo, a 7.62mm CROWS II turret drops `1000` 7.62mm ammo and a .50 BMG CROWS II turret drops `400` .50 BMG ammo.  
This much ammo trivializes the usage of guns, as the avatar does not need to worry about noise ( they have ammo to spare on the zombies that get attacted by the noise ), and the sheer amount of ammo makes trading very easy, buying expensive items with bullets to spare. Just a .50 BMG turret drops $1000 worth of ammo.

The amount of ammo **is not the problem**, the problem is that it drops in ammo belts, which the player can unload in just a few minutes.

#### Describe the solution

Give each of the `CROWS II` turrets a special casing for their ammo. This casing makes so the bullets don't fit regular weapons but is still easy for the player to unload the gunpowder within and melt the casing to make more bullets.

This changes incentivezes the player to deconstruct the bullets for materials and craft their own reloaded ammo.

My intention with this change is for the player ammo quantity to be capped by the amount of casings they find, as disassembling the crows ammo will give all but the casing as materials needed to craft a regular 5.56 ammo. The casings are not craftable, so the player must find them on the world.

The new bullet type has a lower manufacturing price, to rationalize it being picked over regular ammo, but it sells for much less in a post apocaliptic world because not everyone can disassemble and hand-reload bullets.

Taking a `M249 autonomous CROWS II` for example:
It has a new gun `crows_m249` which is a copy of `m249`, and its `starting_ammo` was changed to `crows_556`, which is also exactly the same as `556` except that it can't be used on `556` weapons.

To accomodate these changes the recipe for making and disassembling the CROWS turrets was changed. As there would be no point if disassembling them gave their weapons, they were removed from the components list.

#### Describe alternatives you've considered

Reducing ammo on `CROWS II` turrets. This is undesirable as #33436 increased their ammo quantity to real world values.

Give the turrets a flag so most of the ammo explodes on death.

Make `CROWS II` turrets drop another type of ammo belt instead, this ammo belt **can not be unloaded**, carries up to **90 bullets** and takes 3 minutes per bullet to disassemble ( 4.5 hours on a full belt ). The downside to this is that the player may fail to disassemble all the bullets, but I think that can be avoided by using `n` bullets with 1 charge instead of 1 bullet with `n` charges to it, though I don't even know if that is possible.

#### Testing

> 5.56mm CROWS II (M249)
- [x] Turret can fire
- [x] Turret drops CROWS 5.56mm ammo belt
- [x] Turret has 1600 CROWS 5.56mm bullets
- [x] Deconstructing CROWS 5.56mm bullets give materials
> 7.62mm CROWS II (M240)
- [x] Turret can fire
- [x] Turret drops CROWS 7.62mm ammo belt
- [x] Turret has 1000 CROWS 7.62mm bullets
- [x] Deconstructing CROWS 7.62mm bullets give materials
> .50 BMG CROWS II (M2HB)
- [x] Turret can fire
- [x] Turret drops CROWS .50 BMG ammo belt
- [x] Turret has 400 CROWS .50 BMG bullets
- [x] Deconstructing CROWS .50 BMG bullets give materials

#### Additional context

Some help with the ammo would be appreciated, as I know nearly nothing about guns and ammo.

I might have been a bit overboard when lowering the post apocalypse price of the bullets.

### CODE REVIEW

**Comment by Maddremor** [comment]
Why wouldn't they be using standard NATO calibers, but an obscure caliber with exactly the same characteristics?

**Comment by Saicchi** [comment]
> The new bullet type has a lower manufacturing price, to rationalize it being picked over regular ammo, but it sells for much less in a post apocaliptic world because not everyone can disassemble and hand-reload bullets.

**Comment by Maddremor** [comment]
This seem like a far more invasive thing than simply reducing the standard loadout for turrets. Do these calibers, or something similar for other militaries, exist?

**Comment by Salty-Panda** [comment]
What about vehicle turrets?
Maybe make the special gun recoverable but impossible to fire by hands? As in lacking any stock, grip, sights etc, 
We have a similar cases, M203 rocket launcher or rail crossbow.
They could still be mounted as vehicle weapons or maybe also crafted into really bad and heavy guns usable by humans?

**Comment by Saicchi** [comment]
Sorry, I don't know much about guns but.
They are supposed to be the exact same caliber but with a slightly different casing, making it not fit on regular weapons but fit on the crows turret.

**Comment by Salty-Panda** [comment]
I see it as very gamey solution to the problem. How about FLAG that makes them explode on over-death-damage the way corpses might become pulped on death?

**Comment by Maddremor** [comment]
> 
> 
> Sorry, I don't know much about guns but.
> They are supposed to be the exact same caliber but with a slightly different casing, making it not fit on regular weapons but fit on the crows turret.

That sounds super expensive. You would have to create new manufacturing equipment and new guns, and logistics would get worse as you now have to different calibers that look almost identical, but don't work with each other. Just the hassle of having to make sure no crate of ammo is mislabeled or that a soldier would accidentally load the wrong ammo would probably dwarf any kind of savings you got.

**Comment by Shodan14** [comment]
Maybe just put the ammo inside the turret and require some time and effort/skills to disassemble it successfully?

**Comment by themaster567** [comment]
To put it another way, by the time you can take on such a deadly turret that has an ammo reserve of potentially thousands of bullets, you would already be powerful enough that the extra ammo isn't going to unbalance things much further from that point. I just don't see this as a change that would benefit anything.

**Comment by SariusSkelrets** [comment]
My problem with this is that the soldiers deployed with the turrets wouldn’t be able to use the turret’s ammo if they run out/the turret is non-functionnal. In an emergency, this ammunition could save their lives

My suggestion is that the turrets’ munitions should be randomized so they get less ammo. They aren’t maintained anymore but are still shooting so the munitions are used and were probably not at their maximum ammo capacity before the soldiers stopped reloading them

The randomization would give smaller numbers over time as the turrets shoot at anything that gets close of them including birds and reanimating zombies

A NPC that gets a turret’s worth of ammo before the player could be a great twist

**Comment by Salty-Panda** [comment]
> To put it another way, by the time you can take on such a deadly turret that has an ammo reserve of potentially thousands of bullets, you would already be powerful enough...

Peek from a corner and throw stones? That's not uncommon thing

**Comment by Salty-Panda** [comment]
> The randomization would give smaller numbers over time as the turrets shoot at anything that gets close to them including birds and reanimating zombies

I see two similarities
First, vending machines miraculously looted after a week or two in-game, even inside the sealed library in a secret lab.
Secondly, we have a flag IRREPLACEABLE CONSUMABLE that's TODO now but is supposed to function "this item will get more expensive with time". We could make it so that the later you find a turret the less ammo it will have.
It would be a pain though since many turrets wouldn't be in place allowing them to shoot at anything (labs finales etc) so the spawn function would have to handle many edge cases. It could work though for various z-0 spawns.

**Comment by actual-nh** [comment]
BTW, the CI test failure is because Generic_Guns requires having a way to migrate this new calibre to a generic replacement, which is not really possible with the original different-ammo idea as far as I can tell.

**Comment by themaster567** [comment]
> > To put it another way, by the time you can take on such a deadly turret that has an ammo reserve of potentially thousands of bullets, you would already be powerful enough...
> 
> Peek from a corner and throw stones? That's not uncommon thing

Fair point, but there is a cheese for everything if you're clever enough. I still do not believe that this PR is the correct solution. I like a lot of the suggestions in the comments here though.

**Comment by faefux** [comment]
> > The new bullet type has a lower manufacturing price, to rationalize it being picked over regular ammo, but it sells for much less in a post apocaliptic world because not everyone can disassemble and hand-reload bullets.

What was your comment on this logic, exactly, 

> > Sorry, I don't know much about guns but.
> > They are supposed to be the exact same caliber but with a slightly different casing, making it not fit on regular weapons but fit on the crows turret.
> 
> That sounds super expensive. 
Unless I am miss-understanding CROWS they are supposed to be a new technology, right? 
New 'Defense Industry' technologies are often super expensive. My two sense here is that we should not take as a truth that such things are built with cost and resource efficiency in mind. There is for example a very prominent example of this all over the media recently.

**Comment by actual-nh** [comment]
> Unless I am miss-understanding CROWS they are supposed to be a new technology, right?
> New 'Defense Industry' technologies are often super expensive. My two sense here is that we should not take as a truth that such things are built with cost and resource efficiency in mind. There is for example a very prominent example of this all over the media recently.

The only new tech aspect is the improved autonomous functioning - see #33436.

**Comment by SenpaiSlime** [comment]
I agree with the idea of having to be careful of how you kill them if you want the ammo, and having to deconstruct some sort of internal compartment to retrieve the ammo, having them just drop it is a little too simple for my taste

**Comment by actual-nh** [comment]
> I agree with the idea of having to be careful of how you kill them if you want the ammo, and having to deconstruct some sort of internal compartment to retrieve the ammo, having them just drop it is a little too simple for my taste

I'd go for a combination of the first and a randomized amount of ammo (some already expended); I don't know whether the innards of these IRL would justify an internal compartment like that.

**Comment by Shodan14** [comment]
> I'd go for a combination of the first and a randomized amount of ammo (some already expended); I don't know whether the innards of these IRL would justify an internal compartment like that.

This is like not 100% realistic, but I could see autonomous turrets left to guard an area for some time being inside a tamper-resistant housing to discourage scavengers and just clever people thinking they can sneak up and press a button to turn it off.

**Comment by SariusSkelrets** [comment]
Turrets were made to keep military areas or points of interest. They were also deployed with soldiers that could turn them off when needed. Leaving a turret active and loaded in some corner is asking for casualties

In newspapers, there’s a mention of how turrets shoot anybody that lacks the autorisation. Pretty sure that ‘’clever’’ would die fast from gunfire

For me, the tamper-proof compartment is simply more trouble for the soldiers that have to reload the turret and a slight inconvenience for anyone that really wants that ammo

For their desactivation, I think that it would be a system with physical connection: you can only turn off the turret if it authorizes your presence. Semi-autonomous weaponry vulnerable to wireless hacking wouldn’t be trusted. However, it will need a computer nearby to control them.

**Comment by kevingranade** [comment]
Big nope to this, the plan is to make turrets rarer, and when they do appear deploy them tactically to avoid trivializing them.

**Pull request closed without merging**
