### PR TITLE
[RDY] Farm mapgen JSONify

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Conversion of `farm` mapgen from `map::draw_map` to JSON.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Thank you. That was something I had mentioned doing due to an earlier version of Tanks and Other Vehicles mod having a partial override for this, which caused a load error issue for mods overriding hardcoded mapgen entries.

Proposed solution to restore a feature that has since been removed was to convert farms to JSON format, and have the vanilla version spawn tractors via the farm_vehicles vehicle group, allowing the mod to spawn its additional tractor styles without any override.

This however I can implement after this pull request is merged.

**Comment by codemime** [comment]
You're doing a good job. Please don't forget to update the list of hardcoded overmap specials (like you've [done](https://github.com/CleverRaven/Cataclysm-DDA/pull/20276/files#diff-90df0fb487770203c1f3f21de7b1b6bdL648) in your previous PRs).

**Comment by DangerNoodle** [comment]
Edit testing branch to have a higher than 0 minimum occurrences to confirm whether they spawn at all?

**Comment by codemime** [comment]
Damn. Looks like I've somehow missed the save game conversion.

**Pull request merged**
