### PR TITLE
Format NPCs doc

### PR DESCRIPTION
**Pull request by AMurkin**
#### Summary
```SUMMARY: None```

#### Purpose of change
More compact and solid view of response effects list.
And conditions list.

#### Describe the solution
Formatted as a table. `<br/>`s was used.
Not sure if `morale_chat` should have a lower level of nesting. It was ###.

#### Describe alternatives you've considered
Did not come to mind.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
I'm a producer of the documentation, not the consumer, so I don't have an opinion if this is any better.

I do think that if you're going to put the effects in a table, you should put the conditions in a table.

**Comment by AMurkin** [comment]
Done.

**Comment by AMurkin** [comment]
I can also split out the type in a separate column in the conditions.
Should I?

**Comment by I-am-Erk** [comment]
As a user of the documentation I do think this is better.

You might consider sorting these tables somehow. I'd suggest by category of effect/condition, just loosely, with a header. Alphabetical would also be a possibility. Something along the lines of (not complete):

- missions
- behaviour/AI
- trade
- opinions
- mutations and effects
- deprecated functions

this would just break up the list a bit and make it easier to scan through and find an entry. It's not strictly necessary as we probably all do ctrl+f most of the time.

**Comment by AMurkin** [comment]
I hope this is acceptable now.

**Comment by I-am-Erk** [comment]
Acceptable? It is beautiful!

**Pull request merged**
