### PR TITLE
Fix compile issues with g++4.2

### PR DESCRIPTION
**Pull request by hovatterz**
These are minor changes I had to make to get things compiling on OS X. I'm not sure if this will affect other platforms.

### CODE REVIEW

**Comment by pouar** [comment]
g++ 4.2? Time to upgrade

**Comment by narc0tiq** [comment]
@pouar That's probably why this was merged and closed in January 2013.

**Comment by pouar** [comment]
I could've sworn this popped up in my notifications more recently. I guess I misread.

**Comment by pouar** [comment]
Apparently it did pop up since it showed up here
fcbaf1ac40d3a79b36a24a9bd49772af73745d8c

**Comment by narc0tiq** [comment]
Right, except that reference should go to
https://github.com/acidia/Cataclysm-DDA/pull/4 -- it's a pull request from
CleverRaven/Cataclysm-DDA to acidia/Cataclysm-DDA. A dirty way to update
one's branches, but it does work.

Similarly, you will get references to the low-numbered issues from
un-preformatted stacktraces from gdb.

**Pull request merged**
