### PR TITLE
[Innawood] Food made from blood

### LINKED ISSUE #56013: Allowing Hardtack to be cooked without it being a learned recipe.
### Is your feature request related to a problem? Please describe.

While I know everything can't be justified by saying "It's not balanced for Innawoods" I do believe hardtack shouldn't be gatekept by a recipe in a book when there are other recipes I believe an average person wouldn't think of. I have been doing research irl for a better understanding of hardtack because of its viability in survival, I am a history major and I was intrigued by Hardtack after watching _Tasting History with Max Miller_. So I did do a bit of research and I believe it is a very easy recipe that I personally would try to make in a survival situation before something a bit more eccentric like "Wastebread" and its interesting recipe.

I believe the implementation of Hardtack as a default recipe given to the player would help those not only trying to survive in a more wilderness setting but could also help those who have dried out potential food sources in their area and refuse or do not wish to venture out. Hardtack can also be a lifesaver for a winter you did not prepare for.

https://www.youtube.com/watch?v=KTVPV-15GL0&ab_channel=TastingHistorywithMaxMiller (Includes Hardtack history) 
https://www.youtube.com/watch?v=FyjcJUGuFVg&ab_channel=Townsends (Townsends and more Hardtack history)
https://www.youtube.com/watch?v=oPTdSMOQRnY&ab_channel=TastingHistorywithMaxMiller (Hardtack history includes early 18th & 19th century implementations)

### Solution you would like.

I do want Hardtack to be implemented without it being learned as a recipe from a book, and while I understand it may seem a tad overpowered I believe with its not so great "enjoyability" and "vitamin source" balances it quite alright, and those who attempt to survive solely off of Hardtack would find it difficult... which is fine, you aren't supposed to survive months with just Hardtack.

I like the idea of it still being food handling 3, maybe 2 if someone has other concerns or has a better general outlook of the food situation in the game.

### Describe alternatives you have considered.

I could just add it to my own game with a little bit of JSON editing, but I feel like others would enjoy another durable food source in their games when the going gets rough.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Mods "[Innawood] Food made from blood"

#### Purpose of change
Makes blood useable as a food source in Innawood

#### Describe the solution
Adds wheat-free blood soup and blodplättar to mainline
Makes blood soup, blodplättar, and blutwurst autolearn in Innawood. Both wheaty and wheat-free versions.
Also makes hardtacks autolearn in Innawood. Fixes #56013

#### Describe alternatives you've considered
Put wheat-free blodplättar somewhere else. It's in 'other' now.

#### Testing
None done yet.

### CODE REVIEW

**Comment by Sathra225** [comment]
Are sausage casings autolearn in innawood? Otherwise blutwurst isn't possible to make.

**Comment by Light-Wave** [comment]
> Are sausage casings autolearn in innawood? Otherwise blutwurst isn't possible to make.

Good catch! Added that.

**Comment by Light-Wave** [comment]
This should be ready to merge now. The failing tests shouldn't be related to these changes.
>Setting furniture f_null at (49,96,2) where terrain is t_open_air (which is_open_air)
>If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

**Comment by DIBAOS** [comment]
I think those recipes are a litlle complex. My families always boil pig blood to eat like that [](https://www.youtube.com/watch?v=xhHR_0VcBnU).

**Pull request merged**
