### PR TITLE
Fix fictional martial arts being learnable without mods

### LINKED ISSUE #59991: NPC Taught me a martial art from a disabled mod
### Describe the bug

I completed the bandit assassination quest from Alonzo, and as payment he taught me Lizard kung fu, which is from mythical martial arts, a mod I don't have enabled.

### Steps to reproduce

1. Complete Alonzo's mission in a world without MMA
2. Ask to be taught a skill
3. Be taught Lizard kung fu?

I don't know if this is reproducible but I will upload my save at the bottom of this form.

### Expected behavior

That I wouldn't be taught a skill from a mod that I don't have enabled.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: bb34fdb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The save, unfortunately the game autosaved after he taught it to me.
[Peaceful Prairie.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9276295/Peaceful.Prairie.zip)

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Bugfixes "Fix fictional martial arts being learnable without mods"

#### Purpose of change
Fix #59991.

#### Describe the solution
Remove Venom Mob Protege from a list of possible starting traits for NPCs, remove Deadly Venoms martial arts from the list of martial arts accessible via Close Quarters Battle CBM.

#### Describe alternatives you've considered
Leaving the Deadly Venoms martial arts accessible via the CBM, as it's plausible for the Exodii to know and make use of martial arts that don't exist in real world, but I think the ones that they would use wouldn't reference any martial arts films from the real world, and the moves provided by those martial arts don't make much sense from a realism standpoint either. Bionic Combatives would make sense for them to know and use however, so I've left it in.

#### Testing
Launched the game, made sure that no errors happen and that the removed martial arts don't appear as possible choice on activating Close Quarters Battle CBM. No idea how to make sure that those martial arts won't appear on random NPCs anymore that in turn would be willing to teach them to the player character, but that shouldn't happen now.

#### Additional context
None.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Please add a todo note in the martial arts book file and the fictional martial arts that they should be moved to MMA post 0.G?

**Comment by AtomicFox556** [comment]
> Please add a todo note in the martial arts book file and the fictional martial arts that they should be moved to MMA post 0.G?

This seems likely to break old saves. Most likely nothing serious, just a debug message complaining about unknown martial art that the player character has, but probably a good idea to avoid it whenever possible.

**Comment by Maleclypse** [comment]
> > Please add a todo note in the martial arts book file and the fictional martial arts that they should be moved to MMA post 0.G?
> 
> This seems likely to break old saves. Most likely nothing serious, just a debug message complaining about unknown martial art that the player character has, but probably a good idea to avoid it whenever possible.

That’s why it’s a todo for post 0.G. So it breaks less saves. If you don’t put it in someone will come along and go “these don’t spawn anywhere in vanilla I need to remove them” and no one will remember to wait until the next experimental cycle because no one commented a timeline of when it was safe to do so.

**Review by Maleclypse — CHANGES_REQUESTED** [review]
Add the todo comment.

**Comment by AtomicFox556** [comment]
Notes added.

**Review by Maleclypse — APPROVED** [review]
I appreciate you making the note while you are here because otherwise these things get lost.  Thank you!

**Pull request merged**
