### PR TITLE
Rework naming of PK mod

### PR DESCRIPTION
**Pull request by mugling**
Current consensus being mod name is misleading although the appropriate name/description remains undecided. This PR provides the last suggestion from #16738 as a starting point for discussion. Marked `CR` so as everyone has fair chance to make their case.

### CODE REVIEW

**Comment by pisskop** [comment]
. . if i can suggest names, something such as:

  - prime revision
  - post requiem
  - pks reimagining
  -

**Comment by pisskop** [comment]
As far as descriptions Id likely try to update whatever one we had for a more in-depth one once the mod is actually integrated.

**Comment by Zireael07** [comment]
Reimagining/Revision/Requiem are all better ideas than Rebalancing :+1: 

Project Redacted, however, sounds too vague.

**Comment by pisskop** [comment]
Im fond of PRM as an acrynom

**Comment by mugling** [comment]
> As far as descriptions Id likely try to update whatever one we had for a more in-depth one once the mod is actually integrated.

The mod is already merged as part of mainline content so the description should be updated now. Nothing precludes further updates to the description as your work proceeds.

> Im fond of PRM as an acrynom

But this cannot be at the expense of clarity. @Coolthulhu's suggestion for *extension* is much more explanatory than any of those suggestions

**Comment by ifreund** [comment]
Plus, PEM stands for lots of [cool things](https://en.wikipedia.org/wiki/PEM)

**Comment by pisskop** [comment]
I was under the impression the mod needed to be renamed because too many people saw potential for a misunderstanding about what 'rebalancing' meant, not that the name needed to be cut-and-dry explanatory.

Not that I think 'extension mod' explains anything.

**Comment by ifreund** [comment]
"Rebalancing" suggests simply changing stats/recipes within the default game.
"Extension" suggests new content, which is much more accurate with the mod you created.

Perhaps "extension" does not explain much about the content of the mod, but it is not misleading.  In fact, the name does not need to explain details since the explanation can occur mostly in the description.  All that is really needed for a name is that it accurately describes the mod, which i think "PKs Extensions" does quite well.

**Comment by pisskop** [comment]
I think we're sidetracking.

All we really need is a mod name that _doesn't_ mislead, not one that sounds like a half complete sentence.

**Comment by mugling** [comment]
> I think we're sidetracking.

No, the central issue is a good name and description.

**Comment by pisskop** [comment]
There is a concensus that 'rebalancing' is misleading.   Which is fine, though regretable.

If you wanted something that was more in-line with the rest of the mod-names in the core game, than there's no reason  'pks reimagining' or something to that effect doesnt correctly describe my attempts to expand the lore of the game.

**Comment by pisskop** [comment]
I'm not sure if this description would prove more accurate or not, but my suggestion for it is

>    "ident": "PK_REVISONS",
>   "name": "PKs Revisions",
>    "description": "Adds new faction, monsters, locations, and items in an attempt to expand the lore and increase combat difficulty.",

**Comment by mugling** [comment]
I'm not sure how checking the `ident`

**Comment by pisskop** [comment]
Having used it for the life of the mod, and using it as an acrynom for the wizard who makes the future-tech/demony things for the doom submod.

**Comment by mugling** [comment]
> Having used it for the life of the mod, and using it as an acrynom for the wizard who makes the future-tech/demony things for the doom submod.
> 
> PEM isnt really a corporation.

I'm completely lost by that. I don't think any new players have much chance of understanding it either?

**Comment by pisskop** [comment]
Its a piece of lore from the mod itself, which wouldnt be readily available from a glance.

Reenvisioning or Reimagining both imply new content, and in fact 'reimagining' implies a whole new flavor.

Reimagining covers how Ive added new triffid groves surfaces, how Im adding new fungal hotspots, how Ive added blobs to lategame spawn lists, how I make a point to not differentiate select monsters in color, encouaging immersion into the game itself.

Reimagining covers a new faction that could outcompete the rest of them if it have the numerical superiority (which is a strong point of all three base invaders).  It covers how I intend to include small mutations and touches, and how I have made monsters weak to 1 or 2 weapon types but quite armored against other types.

Reimagining covers how I give the player less safe spaces to hide in, granting night vision to robots like tankdrones, and increasing the range of most lairs, like ant hives or how Ive added monsters to make the fungus slightly more aggressive or added uncommon bashing ants to force the player to keep moving.

**Comment by mugling** [comment]
Following e887142 I'm going to leave this open for further review and/or another dev to merge

**Pull request merged**
