### PR TITLE
Apply mag_jam_mult to helical and drum magazines

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
#74696 added field, that supposed to make drum and helical mags handle damage worse than default. This pr applies it
#### Describe the solution
Apply field, document how field should be used
#### Additional context
Chances are following:
image
image

### CODE REVIEW

**Comment by Hyperseeker** [comment]
For future reference: assuming we ever get quad-stack magazines and the like (or, say, someone eventually adds one of those as a mod), what should the multiplier be for those? Are they supposed to be as unreliable as drum magazines?

**Comment by GuardianDll** [comment]
i dunno, even this numbers are pretty asspull imo, both because there is little to no data, and because our damaging system is not very detailed (damage can be only one of five state duh)

**Comment by Holli-Git** [comment]
> For future reference: assuming we ever get quad-stack magazines and the like (or, say, someone eventually adds one of those as a mod), what should the multiplier be for those? Are they supposed to be as unreliable as drum magazines?

We do have quadstacks, and I think some tri stacks

**Comment by Hyperseeker** [comment]
If we do have those, then maybe it's worth considering what multiplier they ought to have, as well. Maybe in a follow-up PR?

**Comment by GuardianDll** [comment]
can be here also, but i am really far from knowing how they should behave, so i'd rely on you
(also how to find said mags? searching by `quadstacks` did not yield anything)

**Comment by Hyperseeker** [comment]
I don't actually have a good source for magazine reliability aside from those in the other PR; the issue of reliability has not come up until now. Conventional wisdom (which often gets repeated by third parties) suggests that anything more-complicated than a double-stack (which is what your conventional 30-round STANAG magazine is) is not reliable enough for the benefits of higher capacity. I am, however, yet to see actual studies that third parties keep referring to. (Not that I've searched very hard so far.)

I'll see if I can come up with anything. I suspect there won't be a lot, or at least not a lot available online. Ideally, I'd want something like the reliability study by the Army that I'd linked to in the previous PR.

> (also how to find said mags? searching by `quadstacks` did not yield anything)

You have to know how a given magazine works. For example, the [60- and 100-round STANAG box magazines](https://everydaynodaysoff.com/wp-content/uploads/2010/12/Surefire-60-100-Round-Box-Magazine.jpg) that we have are both quad-stack, which you can tell visually by the fact that [they're much wider than your 30-rounder](https://i.redd.it/gnk9m9wh6kia1.png). (These are not the same magazines, by the way, but you can get the idea from the comparison.)

It's called a quad-stack because they [stack the rounds inside into four columns](https://i.redd.it/34vgnpae9kia1.png), at least eventually, hence the width requirements. (They narrow down to single-stack at the feeding lips.)

For what it's worth, while [Magpul was unable to produce a reliable quad-stack](https://www.thefirearmblog.com/blog/2017/04/04/magpul-finally-explains-killed-polymer-coffin-magazine/) – at least reliable to their own high standard – the German manufacturer Schmeisser [sells a polymer 60-rounder](https://schmeisser-germany.com/en/ar15-m4/), which is [apparently](https://www.guns.com/news/reviews/review-schmeisser-s60w-ar-mag) reliable enough:

> When it came to reliability, we fired a mix of 500 rounds through the two mags [Gen I and Gen II of the same model — H.] with just a couple of warning flags to raise. First off, when using brass-cased ammo, we had no problems. The warning lights just went off with imported lacquered 5.56 (looking at you, Wolf), which sometimes delivered a failure to feed towards the end of the mag.

Granted, 500 rounds is barely scientific, but it's something.

**Comment by SirPendrak** [comment]
> > For future reference: assuming we ever get quad-stack magazines and the like (or, say, someone eventually adds one of those as a mod), what should the multiplier be for those? Are they supposed to be as unreliable as drum magazines?
> 
> We do have quadstacks, and I think some tri stacks

Exodi 60mag is 4-row, same for HUB-01 EXOTIC HWP 60 mag

**Comment by Holli-Git** [comment]
> Exodi 60mag is 4-row, same for HUB-01 EXOTIC HWP 60 mag
Only the HWP is a quad stack, Exodii's 60 rounder's a pan

**Comment by Holli-Git** [comment]
> It's called a quad-stack because they [stack the rounds inside into four columns](https://i.redd.it/34vgnpae9kia1.png), at least eventually, hence the width requirements. (They narrow down to single-stack at the feeding lips.)

I'm being pedantic here. Magazines being single feed or double feed is dependent on the firearm. Quadstacks could narrow into single or double feed. I think quadstacks have a harder time becoming single feed just because of the friction but I don't think it's impossible

**Comment by Hyperseeker** [comment]
As a follow-up to this, now that it's merged: is it possible to assign a decimal to the multiplier value? That would solve whatever conundra I might have for complex magazines I add myself (even though it will be a while before that happens).

**Comment by GuardianDll** [comment]
yes, it's a double under the hood, can do entire `1.23456789`

**Pull request merged**
