### PR TITLE
[Magiclysm] More (and more thematic) trolls

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] More (and more thematic) trolls"

#### Purpose of change

I remember the first time I fought a troll in Magiclysm was very memorable, but I was very surprised at their relative lack of regeneration. Ever since D&D borrowed from _Three Hearts and Three Lions_, powerful regeneration has been a troll staple. And with the benefit of negative armor leading to vulnerabilities in the Magiclysm damage types PR, it can better be represented.

#### Describe the solution

Change troll regeneration from 1 to 12, but add fire and acid weaknesses of 15(+15 damage when hit by fire or acid). In addition, disable their regeneration when set on fire (there doesn't seem to be a "covered in acid" effect that applies to targets being hit by acid, or at least, `corroding` never showed up on any monsters I was attacking). Greatly reduce troll bump attack damage (1/3rd of what it was), and rebalance that damage onto the special attacks, which can be avoided by disabling the troll's arm via weakpoints. Of course, trolls can regenerate...

In addition, add two other types of troll.
-  Rock trolls have stony skin, giving them much better armor, but they also turn to stone in sunlight (or would if monsters that didn't leave a corpse could cast death effects. Right now they just vanish). I'm planning to put in a special cave variant that has rock trolls and a bunch of trash and bones and maybe, if you're lucky, some loot that's actually interesting.
- Sea trolls live in water, and are slightly weaker and slower on land than normal trolls, but can swim. 

#### Testing

Trolls are very dangerous in melee--even the experienced survivor in the combat test suite had trouble with them, mostly with being grabbed by a giant monster and thus being unable to wield a nodachi.  However, firearms can outpace their regeneration--with the provided AR-15, I was able to kill one before it reached me.

Using magic, trolls are much less of a threat. Made a mid-rank survivor and gave them some kelvinist spells and the troll died easily as I set it on fire, disabling its regeneration. As in D&D, bring fire or acid to fight trolls.

Rock troll caves are a significant threat--on testing I found one with 5 rock trolls in it--but the player has the advantage that if they can run back out into the sunlight, they're safe.

### CODE REVIEW

**Comment by Rokharn** [comment]
I think with their armor level and high hp, this 24 regeneration is too much. This makes this monster at the tier of dragons.

**Comment by Zireael07** [comment]
10-12 would be ok imho

**Comment by Standing-Storm** [comment]
I based it on one half of the HP-to-regen ratio that trolls have in D&D. D&D trolls are infamous for the rule that they're basically unkillable unless you use fire or acid to  fight them, which is what I'm trying to emulate here.

**Comment by Rokharn** [comment]
> I based it on one half of the HP-to-regen ratio that trolls have in D&D. 

DnD troll have up to 84 hp. Our one have 480. Plus armor difference, enemy dmg, plus huge differences of damage potential of the players, armor difference. This is not same enemies if looking at their abilities at all. 

Extra 10 dmg for whole enemy turn is not so huge for dnd characters, when this enemies start to appear. Plus you can kill dnd troll only if regen is stopped. It's will not die even at the zero hp. For cataclysm with zombification it's seems will not work.

And 'once per enemy turn' surely not the same as our regen per second. At least not at time, when player needs more turns to deal damage for the most of weapons. Plus DnD is party game. Sure, we have npc, but they are not ready for such feats, in my humble opinion.

At the same time, if we consider folklore trolls, they completely turn into motionless stone during the day. At the same time they are only strong at night.

**Comment by Standing-Storm** [comment]
> DnD troll have up to 84 hp. Our one have 480. Plus armor difference, enemy dmg, plus huge differences of damage potential of the players, armor difference. This is not same enemies if looking at their abilities at all.

Correct, but a starting human in CDDA also has 84 HP, which is a high-level character in D&D. It's about the ratio, not the exact amount.

> And 'once per enemy turn' surely not the same as our regen per second (literally this is regen per dnd movement of 1 square, which far from whole turn). DnD turn = 6 second, you know. 480/84*10/6 = 9 regen. And this is if we will not count players turns at all.

This is a good point and I was coming here to mention it when I saw you already had.  Under that rule, 10-12 like Zireael07 mentioned would be more reasonable--still high enough that you want to use fire or acid, but less overwhelming.

It would be technically possible for me to make them return to life (just give them the REVIVES flag and set them to revive into trolls again) but it wouldn't be anything like actual D&D troll reviving (it would take hours and smashing them would stop it, just like zombies)

> At the same time, if we consider folklore trolls, they completely turn into motionless stone during the day. At the same time they are only strong at night.

This is what stone trolls (as listed above) are intended to emulate.

**Comment by Rokharn** [comment]
> but a starting human in CDDA also has 84 HP, which is a high-level character in D&D

Average human of level 1 start DnD with ~8 hp. So...

**Comment by Standing-Storm** [comment]
It's HP is derived from its size--it the same volume as a zombie hulk, and whoever made them gave them the same HP as a zombie hulk. (though it actually weighs 4x as much as a zombie hulk and so should probably have even more HP than it does)

**Comment by Rokharn** [comment]
I think 12 regen much more reasonable. 

But zombified version surely needs more, than 5 regen. Originally on Magiclysm it's become more dangerous with 3 regen vs 1 of living version. DnD troll zombie having the same regen as alive one, but less armor (and can be killed without acid or fire).

**Comment by RedMisao** [comment]
Do negative armor values work? I tested it last week or so and monsters weren't receiving bonus damage

Also, for the rock troll death I _think_ you can add a `death_function` that spawns a "troll statue" furniture via ter_furn_transform

**Comment by Standing-Storm** [comment]
> Do negative armor values work? I tested it last week or so and monsters weren't receiving bonus damage

They don't yet, but that functionality is being added in the Magiclysm damage types PR

**Comment by Standing-Storm** [comment]
Happened to look at Magiclysm ogres and they're one eighth as big as Magiclysm trolls (???), so with troll regeneration being buffed maybe their HP and size should go down slightly, and then I can increase the HP and size of ogres and put some ogre lairs in swamps. 

(D&D has them of similar size with ogres slightly larger)

**Pull request merged**
