### PR TITLE
Target by Monster species

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Target by monster species

#### Describe the solution
Mirrors targeting by monster id.  What goes wrong? Can I fix it?

#### Describe alternatives you've considered
nyet

#### Testing
Works great

#### Additional context
banish works

### CODE REVIEW

**Comment by GuardianDll** [comment]
Maybe add some info for MAGIC.md is good idea?

**Comment by Maleclypse** [comment]
> Maybe add some info for MAGIC.md is good idea?

Only if I get it working.  :) It's really frustrating to write out documentation and then remove it because you only got things to work partially or one of the enhancements out of several.

**Comment by KorGgenT** [comment]
i need to try to find time to look at it by this weekend, but one of my credos about spell_type is to add as few new members to it as possible, while reusing other members of it as long as they sort of made sense. 
that being said, it's been a while since i've looked at them; but i'm pretty sure there was a targeted creature member? which if you add a flag to convert creature to species, would actually prevent adding another member.
if i haven't looked at it by july 17th prod me again please

**Comment by Maleclypse** [comment]
> i need to try to find time to look at it by this weekend, but one of my credos about spell_type is to add as few new members to it as possible, while reusing other members of it as long as they sort of made sense. that being said, it's been a while since i've looked at them; but i'm pretty sure there was a targeted creature member? which if you add a flag to convert creature to species, would actually prevent adding another member. if i haven't looked at it by july 17th prod me again please

Hey Korg, 
I'm not sure how to add a flag to convert creature to species.   Would you be able to take a look and see if it's something you can whip up in a short bit?

**Pull request merged**
