### PR TITLE
JSON format script [RDY]

### PR DESCRIPTION
**Pull request by mugling**
#### Summary
- A formatting tool for our JSON data akin to `astyle`
- ~~Less than 80~~ 89 lines of fairly idiomatic `perl`
- No external dependencies beyond the p5-JSON module
- Configurable via plain text without having to know perl
- Could be very helpful in the cleanup of  #17417
#### Implementation
- Parses in a single pass and aborts on any JSON syntax errors
- Traverses nodes recursively building a `context` string as it travels
- Object keys are sorted according to `priority.conf` aborting for unmatched keys
- Fields which should avoid wrapping can be specified in ~~`wrap.conf`~~ `nowrap.conf`
#### Configuration
- Comments begin with one or more `#` and all blank lines are ignored
- `context` specifications are regular expressions (PCRE)
- Ordering is significant with first match applied
- Specifier for object fields is `:` (eg. `recipe:qualities:id`)
- Specifier for anonymous array elements is `@` (eg. `recipe:components:@`)
#### Scope
- This tool is for formatting only and should be kept simple (no conditionals/branching)
- Although there is the option for special casing a `context` via perl code this should be avoided
- Redundant fields should be identified by `jq` and not this tool
- Misspelled fields are however detected as this adds no cost to the implementation
- Validation remains the responsibility of the `cataclysm` binary
- Provides `-c` switch to check file is canonical format (for use in `Makefile`)

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Could also remove redundant fields, though then it would need to be updated once in a while.
How about a parameter that lets it do that and then have it print all the removed fields?

**Comment by mugling** [comment]
Warn on unmatched fields would catch a lot of bugs, for example it should be able to catch `baszing: 6` as being a typo of `bashing: 6`. That extremely simple to implement.

**Comment by mugling** [comment]
Ok so it now catches mispelled fields (those that don't appear in `priority.conf`)

**Comment by mugling** [comment]
Can convert this:
```
},{
        "type" : "recipe",
  "result": "aripper",
  "category": "CC_OTHER",
  "subcategory": "CSC_OTHER_PARTS",
  "skill_used": "mechanics",
  "skills_required": [ "fabrication", 5 ],
  "difficulty": 5,
  "time": 30000,
  "reversible": false,
  "autolearn": true,
  "qualities":[
    {"id":"HAMMER","level":2,"amount":1},
    {"id":"SAW_M","level":1,"amount":1}
  ], "tools": [
    [
	  [ "soldering_iron", 30],
	  [ "toolset", 30]
    ]
  ],
  "components": [
	[
		["scrap", 12],
		["steel_chunk", 4]
    ],
	[
		[ "turret_engine_L", 1 ]
	],
	[
		[ "fcs", 1 ]
	],
	[
		[ "ripper", 1 ]
	]
 ]
}
```

into this

```
  {
    "result": "aripper",
    "type": "recipe",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_PARTS",
    "skill_used": "mechanics",
    "difficulty": 5,
    "skills_required": [ "fabrication", 5 ],
    "time": 30000,
    "reversible": false,
    "autolearn": true,
    "qualities": [
      { "id": "HAMMER", "amount": 1, "level": 2 },
      { "id": "SAW_M", "amount": 1, "level": 1 }
    ],
    "tools": [ [ [ "soldering_iron", 30 ], [ "toolset", 30 ] ] ],
    "components": [
      [ [ "scrap", 12 ], [ "steel_chunk", 4 ] ],
      [ [ "turret_engine_L", 1 ] ],
      [ [ "fcs", 1 ] ],
      [ [ "ripper", 1 ] ]
    ]
  }
```

**Comment by mugling** [comment]
* Updated preamble to include initial documentation
* Needs testing - in particular can anyone demonstrate particularly ugly output
* Would welcome PR's to this branch that extend support for additional `contexts`

**Comment by mugling** [comment]
Done for now. As this PR affects neither the game binary nor the build script if anyone is lurking I'd appreciate a merge as I want to start a refactor of #17417 using it.

Documentation as to writing rules for the parser will follow in the wiki.

**Comment by mugling** [comment]
Latest commits provide example output, a unit test framework to ensure non-regression as the ruleset is updated and also initial documentation.

I've written rules for about 80% of the JSON data and am almost ready to start parsing blazemod

**Comment by mugling** [comment]
One obvious extension is being able to output a ruleset for a JSON file but that can wait for part 2.

Ready for testing

**Comment by Coolthulhu** [comment]
Perl is usually in `/usr/bin/perl/`, without that `local`.

**Comment by Coolthulhu** [comment]
Breaks when fed `tools.json`:
```
ERROR: Unmatched rule 'TOOL'
```

**Comment by Coolthulhu** [comment]
From what I can tell, it is supposed to handle tools.json, yet doesn't.

**Comment by mugling** [comment]
> Perl is usually in /usr/bin/perl/, without that local.

Not on FreeBSD but I agree that's exceptional. How about `/usr/bin/env perl`?

> From what I can tell, it is supposed to handle tools.json, yet doesn't.

Almost. You can consider an type supported once it has a unit test in `examples`

**Pull request merged**
