### PR TITLE
Add more simple tools and containers

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add more simple tools and containers"

#### Purpose of change
Implement more methods of producing useful things from various materials.

#### Describe the solution
Add foil wrapper usable for cooking food, foil cup usable for boiling water, wooden bowl, skull bowl, and a recipe for the tobacco pipe.

#### Describe alternatives you've considered
None.

#### Testing
Launched the game with those changes, made sure that no errors happen, looked at recipe to make sure they're sensible.

#### Additional context
None.

### CODE REVIEW

**Comment by Shodan14** [comment]
Should probably add some spawns as well?

**Comment by AtomicFox556** [comment]
> Should probably add some spawns as well?

All of this is mostly improvised or handcrafted stuff; I'm not really sure where it could spawn.

**Comment by Shodan14** [comment]
> > Should probably add some spawns as well?
> 
> All of this is mostly improvised or handcrafted stuff; I'm not really sure where it could spawn.

Even then, presumably other survivors have also done this before. At least the foil stuff should be in some of the trash groups. Maybe the wooden stuff at camps or other nature sites. Not up on the latest outdoor item groups.

On another note, is there enough foil currently in available in urban areas to make this practical?

**Review by NetSysFire — COMMENTED** [review]
>I'm not really sure where it could spawn.

The skull cup in the area where you would get the etched skull thingy for the quest with the human sacrifice monster. Perhaps also add it to some itemgroups like the `creepy` (or however its called) itemgroup for the mansion basement. You get the idea.

The wooden bowl could potentially be in the swamp shack or pottery hut.

The foil wrapper could be spawned around homeless camps and trailer parks perhaps. To me it looks improvised and cheap enough that it might have been used by people who do not have another choice since foil is cheap and an actual bowl might not be.

The only complaint I have is about the foil cup. I think actually making one yourself will be rather difficult and they are limited use, but this might not be possible to realize due to current limitations.
As far as I can see you only get a rather flimsy cup out of aluminum foil and forming said cup requires one in the first place. Putting it into a fire to boil water may not work since it can not hold the water and would fall over I think.

**Comment by AtomicFox556** [comment]
Item group entries added.
> The only complaint I have is about the foil cup. I think actually making one yourself will be rather difficult and they are limited use, but this might not be possible to realize due to current limitations.
As far as I can see you only get a rather flimsy cup out of aluminum foil and forming said cup requires one in the first place. Putting it into a fire to boil water may not work since it can not hold the water and would fall over I think.

YouTube has plenty of videos showing people boiling water in aluminum foil cups with various design. Some people do use an existing cup to form the foil cup, others don't. Some people mention that the cup would degrade if used many times; if needed, I could limit the cup to just containing the liquid, rather than boiling it.
https://www.youtube.com/watch?v=rrrl6HHq9SY
https://www.youtube.com/watch?v=-Ra5byOxFec
https://www.youtube.com/watch?v=Yv8eqfbO8eo

**Comment by NetSysFire** [comment]
>Some people do use an existing cup to form the foil cup, others don't.

Hmm. Maybe add a recipe with a lower skill requirement requiring a cup and make it autolearn. Then change the existing recipe which does not need a cup and increase the skill requirements a bit (still autolearn) but also add it to some survival books.

The goal of this is that as a beginner/survival noob you can only make such a foil cup using a different cup to shape it but if you know how (by reading it in a book) or just get better at fabrication or survival, you can achieve the same without a cup to give shape to the foil cup.

If you add this, please add a comment to the recipes so others understand the idea, too. It might be a little hard to understand without a comment.

>I could limit the cup to just containing the liquid, rather than boiling it.

Since you stated your sources I am now convinced this works for boiling water but my concern is still the flimsy nature of the cup which would make it degrade after some time.
I think a good workaround would be potentially removing the BOIL quality, so it forces you to boil water one at a time by dropping it on a fireplace and waiting until has finished boiling, since as far as I know physics boiling does not require the BOIL quality, only recipes require those, which enable batch crafting. Please test that though, I am reasonably sure it would work but not 100%.

This should discourage overusing the foil cup so the player seeks alternatives. It works in an emergency but it is tedious. This is just an idea though, so do not be afraid to tell me what you think about this.

**Comment by AtomicFox556** [comment]
> Hmm. Maybe add a recipe with a lower skill requirement requiring a cup and make it autolearn. Then change the existing recipe which does not need a cup and increase the skill requirements a bit (still autolearn) but also add it to some survival books.

I've decided to just increase the recipe difficulty to 1 to take into account the fact that it's not made using an existing cup. It's quick enough to learn, and I doubt there'd be any use for making an improvised cup from foil for boiling water if you already have some kind of container you could (almost certainly) boil water in.

> Since you stated your sources I am now convinced this works for boiling water but my concern is still the flimsy nature of the cup which would make it degrade after some time. I think a good workaround would be potentially removing the BOIL quality, so it forces you to boil water one at a time by dropping it on a fireplace and waiting until has finished boiling, since as far as I know physics boiling does not require the BOIL quality, only recipes require those, which enable batch crafting. Please test that though, I am reasonably sure it would work but not 100%.

> This should discourage overusing the foil cup so the player seeks alternatives. It works in an emergency but it is tedious. This is just an idea though, so do not be afraid to tell me what you think about this.

I think deliberately making something tedious for the player is just bad game design, especially when such an addition would serve no other purpose. If it is tedious for the character, it doesn't have to be the same for the player.

**Pull request merged**
