### PR TITLE
5-Point Anchor and MDA Need to Charge

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Balance "Give the 5-Point Anchor and Modular Defense Anchor Internal Batteries."

#### Purpose of change
When the battery audit hit, the original power source of the subjects, the medium plutonium battery, was migrated to the standard medium battery. This (unintentionally) drastically reduced the operational lifespan of these devices from ~5 days to about an hour. This PR aims to partially restore the lost battery.

#### Describe the solution
Instead of running off disposable batteries, the 5-Point Anchor and Modular Defense Anchor now possess an internal storage of 450KJ (or 12.5 hours on a full charge).  

#### Describe alternatives you've considered
-Adding back the medium plutonium battery but adjusted for the post-audit meta.
-Decreasing the power draw.
-Making the base Anchor be non-rechargeable, but Hub-01's modifications allow it to be charged.

#### Testing
TBD
Screenshot 2024-10-03 192925

#### Additional context
This is really @John-Candlebury's Domain, so I am doing my best to tread carefully and respectfully. And thank you to @Maddremor for suggestions on implementation

### CODE REVIEW

**Comment by Holli-Git** [comment]
That's roughly 1-2 kgs of batteries, I don't think that's a reasonable amount to lug around. Also, you've greatly increased the power to the point it can last for over a day. I think that's unreasonable, this is some really strange device capable of grounding you to this earth during storms that are tearing apart the fabric of reality. I don't think lasting over a day on a single charge is reasonable. IMO, an hour of use sounds better, it gives people something to think about, and plan accordingly. 

Also didn't we veto the UPS power stuff? I feel like having it draw from UPS just because HUB touched it feels like a flimsy excuse to add what you wanted.

**Comment by DukePaulAtreid3s** [comment]
> Also didn't we veto the UPS power stuff? I feel like having it draw from UPS just because HUB touched it feels like a flimsy excuse to add what you wanted.
It looks like they can't recharge at all without the UPS flag, I've learned this while I've been testing this PR (hence why it is still a draft), but have not updated the description. I've already tried cords, but they do not make any sense with the current descriptions.

**Comment by Holli-Git** [comment]
I'd still say increase the power consumption so it lasts an hour. If you have an argument for why it should be 12.5 you should say, but you haven't

**Comment by DukePaulAtreid3s** [comment]
> I'd still say increase the power consumption so it lasts an hour. If you have an argument for why it should be 12.5 you should say, but you haven't

Original operational time was about 5 days, which was reduced down to 1 hour by the removal of medium plutonium batteries. If we reduced the medium plutonium battery's charges by the same 48% as the heavy version, without changing the power draw, you get 66 hours, or about 2.75 days. My PR, by including an internal battery, reduces that time further to just over 12 hours. It is still a very, very substantial nerf to the overall efficiency of the device compared to what it was originally intended to be. That is why I first asked how long the expeditions were in which it was supposed to be worn. Alternatively, I could allow them to use heavy plutonium batteries, which in terms of power stored are roughly equal to where it originally was. In fact, I am just now realizing that is what I should have done in the beginning.

**Comment by John-Candlebury** [comment]
I honestly do think this should las 12 hours or so on a full charge. Enough to walk someone dangerous and have ample safety margin to return.

**Comment by DukePaulAtreid3s** [comment]
I am currently remaking this from the ground up, in a new branch. Closed

**Pull request closed without merging**
