### PR TITLE
Forest glass

### PR DESCRIPTION
**Pull request by Sathra225**
#### Summary
Mods "Forest Glass and Acetone"

#### Purpose of change
The ammonia changes made glass and rubber cement impossible in Innawoods, so these changes make them possible.

#### Describe the solution
Adds 'forest glass' made from sand, ash for flux and lime as stabiliser. It requires more heat and fuel than soda glass. Then added autolearn to acetone (all the other ingredients are already possible).

#### Describe alternatives you've considered
Changing the problematic recipes to using Innawoods craftable ammonia, but not sure if there are other changes coming on that front so went with alternative recipes.

#### Testing
Made changes, recipes were available and made.

#### Additional context
Viability of ash/forest glass is from https://etheses.whiterose.ac.uk/3464/1/287681.pdf.

### CODE REVIEW

**Comment by Sathra225** [comment]
The commit history is a mess after having to fix my repository.

**Review by Light-Wave — APPROVED** [review]

**Comment by Light-Wave** [comment]
Lovely, thank you.

**Comment by evankimori** [comment]
Hi, question from a discussion on #59671 - is it possible perhaps to incorporate Corpse Ash into the recipes here? Or is this already a WIP? 

Apologies if I'm asking a question already answered.

**Comment by Light-Wave** [comment]
> Hi, question from a discussion on #59671 - is it possible perhaps to incorporate Corpse Ash into the recipes here? Or is this already a WIP?

Not currently worked on, to my knowledge.
If you can show research showing that this works in real life, and perhaps numbers of how much corpse ash you need compared to how much wood ash you need, then I would be fine with including it in Innawood.
As far as I can tell, the composition in corpse ash and wood ash are different. However, the important part seems to be potash, which exists in roughly equal amounts in wood ash and cremated remains. So it is possible it would work. But I'd like a slightly more definitive source than that. If you find that, you can make an issue and ping me in it (with @), or you can reply here.

**Comment by evankimori** [comment]
> It'd probably make more sense to use corpse ash as fertilizer honestly.

Hrm. That's a very good thought. Will discuss. Thank you for your input and clarification, much appreciated!

**Pull request merged**
