### PR TITLE
Restore item pickup to examine menu

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Features "Restore item pickup to examine menu"

#### Purpose of change

Allow the `e`xamine command to pick up items (like it has always done), but do it using the new container-aware item pick-up pop-up.

The removal of this keybinding behavior has been a frequent player question or complaint on the development discord lately. The muscle memory of using `e` for as many commands as possible is hard to break; some players were not even aware that `g` to pick up items existed, because `e` performed that role so seamlessly. In fact the default behavior for `e` was to automatically pick up items unless something prevented it, so I agree that its removal led to a regression in quality of life for some players.

#### Describe the solution

Revert (partially) these two commits:

ac80392cb5c339eeaf93f85f3fb653aa7f858e18
22699c010445828458948e934f28c24373e8b5f8

Ensure that calls to the old (left sidebar style) `Pickup::pick_up` menu are now using the new (container-aware central popup style) `game::pickup` menu.

When a vehicle storage tile and the ground beneath it both have items, the `g` popup displays both, so I removed the separate menu entry "Get items on the ground".

Add a new (default unbound) keybinding, "Examine nearby terrain, furniture, or items", which gives the *old* behavior for `e` (including items to pick up).

#### Describe alternatives you've considered

The word "examine" has become decreasingly applicable to the `e` menu, which (with or without pickup) is now more like "everything except examine". However, the word "examine" is entrenched firmly in the codebase and UI for this feature. Changing it to a more descriptive and accurate word like "interact" feels inevitable, but also feels outside the scope of this PR.

#### Testing

The new container-aware Pickup screen should be displayed in all these cases:

- Use `e` on a floor or ground tile that has items - pick up items by default
- Use `e` on a table or counter tile with items, then select `g` to pickup items
- Use `e` on a vehicle storage tile with items, then select `g` to pickup items
- Deploy a roll mat, brazier, tarp, or other furniture, then place items on it; use `e` to "Get items" along with other appropriate options

#### Additional context

Using `e` to examine my surroundings:

image

At the cupboard:

image

At the leather tarp:

image

At the bicycle basket:

image

Or just at a floor tile, where no further entry is needed - in all cases, the new pick-up pop-up should be displayed, with containers and their contents:

image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Please check if bug mentioned in this (https://discourse.cataclysmdda.org/t/autodoc-bug-when-an-item-is-on-the-machines-tile/25940) post doesn't reappear with your changes.

**Comment by wapcaplet** [comment]
> Please check if bug mentioned in this (https://discourse.cataclysmdda.org/t/autodoc-bug-when-an-item-is-on-the-machines-tile/25940) post doesn't reappear with your changes.

I restored all of the changes from #47612 in this PR, and confirmed that `e`xamining an autodoc with items either gives this "No patient found located on the connected couches" message:

image

Or, if I am on the couch, shows the operation menu, without including `g` Pick up items, as expected:

image

**Comment by Terrorforge** [comment]
Any chance this change could be made optional? Like maybe a separate hotkey for "examine without pickup"? I'm the apparently only person who was glad to see the old implementation go, because I hate trying to 'e'xamine the only examinable furniture in range and getting prompted to select one of six tiles because there were some random items laying about.

**Comment by wapcaplet** [comment]
> Any chance this change could be made optional? Like maybe a separate hotkey for "examine without pickup"? I'm the apparently only person who was glad to see the old implementation go, because I hate trying to 'e'xamine the only examinable furniture in range and getting prompted to select one of six tiles because there were some random items laying about.

This is a reasonable request. It complicates the code somewhat, but turned out not to be too difficult. Now there are two keybindings. The original `e` is now named "Examine nearby terrain and items", and the new keybinding is called "Examine nearby terrain only". By default it is unbound:

image

The prompt for each is now slightly different too - originally it simply said "Examine where?", but now the default `e` says "Examine terrain, furniture, or items where?" and highlights eligible nearby tiles, including those that only have items in them:

image

With the new keybinding command, the prompt is "Examine terrain or furniture where?", and highlights only tiles that can be examined, *not* counting item-only tiles:

image

Likewise, if you have "Autoselect if exactly one valid target" enabled, and only one counter or door or whatever is nearby, it will automatically examine there, again not counting tiles that only contain items.

**Comment by mqrause** [comment]
In my opinion making the default behavior the old one is a bad choice. Instead of aiming to improve the controls or UI, this is explicitly catering to players who don't want to adjust their habits.

**Comment by wapcaplet** [comment]
> In my opinion making the default behavior the old one is a bad choice. Instead of aiming to improve the controls or UI, this is explicitly catering to players who don't want to adjust their habits.

I don't agree that the forced removal of "pick up items" from the "examine" menu is an improvement in any way whatsoever. Using "examine" to pick up items is not just a habit, but a legitimately useful UI function that was removed for no coherent reason I'm aware of.

I believe other players should be free to choose the new no-pickup behavior for themselves, with a way to "opt in" to the new no-pickup mechanism if it's something they want, instead of changing the default behavior for everyone and forcing them to "opt out" if they don't like it.

**Comment by mqrause** [comment]
> I don't agree that the forced removal of "pick up items" from the "examine" menu is an improvement in any way whatsoever. Using "examine" to pick up items is not just a habit, but a legitimately useful UI function that was removed for no coherent reason I'm aware of.

I originally removed it because I saw and still see omnidirectional pickup as the way to go in the future, going in the direction of #50015. And obviously with no directional pickup it also had to go from `e`xamine. There wasn't more of a reason to it.
However that was also exactly what made it easy for me to adjust my own muscle memory because interacting with furniture became much more streamlined, like what Terrorforge said. And I do think that that would be an improvement for new players. That doesn't mean there is no room for a "one button for everything" control style, I just don't think it should be the default.

> I believe other players should be free to choose the new no-pickup behavior for themselves, with a way to "opt in" to the new no-pickup mechanism if it's something they want, instead of changing the default behavior for everyone and forcing them to "opt out" if they don't like it.

Unless I'm mistaken, if you keep the `config/keybindings.json` when updating and leave the "examine with pickup" id the same as examine was before, nothing will change. So there is no forcing to opt out for everyone. Unless they use a completely fresh install regularly, but I would assume that means going through all the settings anyway.

**Comment by catdach** [comment]
here's a discussion that seems very relevant to the implementation of this pull request in regards to key bindings #52890

**Comment by mqrause** [comment]
> Here's a discussion that seems very relevant to the implementation of this pull request in regards to key bindings #52890

Yeah, if something like that was coming soonish, it wouldn't really matter which way around it was done in this PR.

> Personally I feel that omnidirectional pickup is a good feature to have, but I don't think it fills the same role as a monodirectional pickup and one isn't an outright replacement for the other. In a similar way that the advanced inventory management screen is _better_ than item pickup, but it's also more difficult to use and does not warrant the removal of item pickup. (I really don't want to discus this to much more here as it could become too irrelevant to this PR specifically, though it may be worth more discussion elsewhere. the linked issue post above may also be relevant to this.)

Directional pickup is just a really crude filter to have fewer items show up in the menu. So pretty much any good improvement to filtering would completely obsolete it. But yeah, that's a discussion for another time.

> I'm in no position to be deciding what the default settings of the game should be for something so ubiquitous as putting an item into one's inventory, but in my opinion the default control settings should prioritize what is most simple and intuitive for a new player. Pressing 'e' to pickup items is very common in video games, almost as common as pressing 'i' to open the inventory and 'wasd' to move. It may not be best to have a "one button for everything" control style in the long run, it is at the very least simple and intuitive.

I'm in no position to decide anything either. I'm just here to offer feedback because that's something my original PR was sorely lacking. Roguelikes like this one are hard to compare to your more normal games, though. Interacting with `e` is most generally used for single things in front of you, not for potentially something like nine stacks of loot, three pieces of furniture and a vehicle.

**Comment by ProfoundDarkness** [comment]
I'm mostly ambivalent, *leaning* against, this PR... I switched to 'g' pickup and 'e' interact a LONG while back when I expected 'e' was going to loose item pickup...

Possibly more relevant to discuss... The old item pickup (through 'e' or 'g') had a pane below the items list which displayed details about the highlighted item.  Quite a few people who were upset about the loss of item pickup from 'e' were actually upset believing that getting information about items had been removed.  Many were more or less fine with switching to 'g' for pickup once they knew about 'e' (or 'E') while highlighting an item in the various inventory related screens.  Some still preferred the idea of dropping the new item pickup interface to get that always present information pane back.  All such folks were initially indistinguishable from the muscle memory folks in their complaints about 'e' loosing item pickup.  From the details available it would appear only the muscle memory folks will be assuaged by this change.

**Comment by wapcaplet** [comment]
After consulting with Kevin and the other devs, I've made the new examine (no pickup) the default `e` keybinding, and this legacy examine (with pickup) the unbound one. In other words, players will need to manually change their `e` keybinding to get the old behavior back.

The reasons that convinced me were (a) picking up items is of major importance, deserving its own dedicated key, that being `g`, and mingling of item pickup code with the everything-else code is undesired complication; and consequently (b) we would like to steer players away from relying on `e` for picking up items, but not necessarily force them to adapt right away.

**Comment by Vzor-** [comment]
In order to look in many objects, both esc and pickup need to be used. With esc and (e) that is easy, requiring no movement of the left hand. (g) and (/) however, both require either stretching or moving the hand back and forth.

**Comment by wapcaplet** [comment]
A couple of tests are failing in the Basic Build CI, but both are unrelated. One is a known-to-be-volatile fire-spreading field test, 
and the other is a melee damage / coverage test that also fails in master with `--rng-seed 1637381899`.

**Pull request merged**
