### PR TITLE
fixes #28020 - some wood soups recipes not allowing organs

### LINKED ISSUE #28020: Some woods soup recipes can use organs, while some can't
**Describe the bug**  
The normal and jarring recipes for woods soup can utilize organs like kidneys, livers, and lungs in their recipes as part of the first ingredient, while the canning and 3L jarring recipes can't.

**To Reproduce**  
1. Try to craft woods soup.
2. See that canning and 3L recipes can't use organs.

**Expected behavior**  
Because the other two recipes can use organs fine, I'd assume that they're also usable in regular crafting. Seeing as portion size between the normal soup and canned soup is the exact same, I know it's not that smaller portions can't use it.

**Screenshots**  
### Canned soup, lacking organs

**Versions and configuration:**
 - OS: Windows 10
 - Game Version: 0.C-37210-ge6e1890
 - Graphics version: Tiles
 - Mods loaded: Reproducable with no mods loaded except Dark Days Ahead

**Additional context**  
I'm not really sure why this issue exists, as the json seems identical between the variants.

### PR DESCRIPTION
**Pull request by mount2010**
#### Summary

SUMMARY: Bugfixes "Fix woods soup being unable to use organs in 3L jarring or canning."
#### Purpose of change

Fixes #28020 
#### Describe the solution

Add meat_nofish to the acceptable items. meat_nofish contains the organs allowed in the other recipes.
#### Describe alternatives you've considered

N/A
#### Additional context

N/A

### CODE REVIEW

**Comment by KorGgenT** [comment]
meat_nofish covers a lot of the things that are already in there, you need to delete the duplicates. you can find the list of them in cooking_components.json

**Comment by mount2010** [comment]
Should I be copy and pasting the other components, adapting the counts

**Comment by KorGgenT** [comment]
> Should I be copy and pasting the other components, adapting the counts

no just delete the lines in the recipe you're editing that appear in the requirement

**Comment by ZhilkinSerg** [comment]
Merged to `0.D` (and `master` with with #28097).

**Comment by mount2010** [comment]
Uh oh, @ZhilikinSerg. I commited too late to fix KorGenT's note. Shall I make another PR or is this one okay?

**Comment by ZhilkinSerg** [comment]
Another PR please.

**Pull request closed without merging**
