### PR TITLE
Add sewer crocs

### PR DESCRIPTION
**Pull request by pisskop**
Adds a sewer gator monster.

Poor day vision, nasty temper, ambushes the unwary by not attacking until they get close, and has a bad bite.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
OK, that bite actually is pretty nasty.
But I'd say it's core animals which suck rather than the croc being too strong.

Still, I'd bump the difficulty stat a bit - 20 or so. It has no mechanical effects, but makes the game color the critter's name red to show that it is dangerous.

**Comment by kevingranade** [comment]
IRL a crock bite is very nerly certain death since it's going to keep whatever it just bit.  You might stay attay attached, you might not, but it's keeping that arm, leg, or whatever.
I other words, sounds great to me :D

**Comment by Coolthulhu** [comment]
About holding:
The `melee` attack has an `effects` field (currently not used by anything) with the same syntax as regular monster attack effects (seen in fungal fighter), which in turn are described in `docs/EFFECTS_JSON.md`.

I'm not sure if it's worth adding here to make crocs also auto-grab with their bites, because the "grabbed" effect is currently a hack and we will need to rework it, but it's just something to consider.

**Comment by Coolthulhu** [comment]
Fuck, linter wants the whole bite on one line. It's better to adjust linter than to deal with 1-line Molochs in the jsons. I'll look into it.

**Comment by Coolthulhu** [comment]
Oh, it looks like it only doesn't like that first newline:
It wants
```
{ "type": "melee"...
```
Instead of
```
{
  "type": "melee..."
```

**Comment by Coolthulhu** [comment]
The gator keeps trying to execute the grab-drag as the first attack and can waste a lot of turns doing so.
Due to low melee dice (grab chance is determined by bashing damage dice), they have a low chance to actually succeed at a grab against any character with sensible physical stats.

It should either lose the drag or at least get it re-arranged after bite.
Later on we could extract a "wrestling skill" stat out of monsters (make an feature request if that would be useful), but until 0.D, the grab attacks will stay wonky.

**Pull request merged**
