### PR TITLE
Change Hobo Stove to deployable furniture

### PR DESCRIPTION
**Pull request by Xpyder**
#### Summary
Balance "Change Hobo Stove to deployable furniture."

#### Purpose of change
Why change: currently hobo stove was either WAY too efficient, or completely useless.

#### Describe the solution
How is it useful but balanced: It deploys like brazier which means it scales to "nearby fire" efficiency now.  Has a max capacity of 500ml to restrict possible burnable fuels (even plank / stout branch is way too large to fit).  all burnable fuels that fit should burn quickly which will require pre-chopping the wood and setting up a "firewood source" tile most likely, meaning it's better for small / one off / emergencies rather than constant usage

Why not just use brazier: Brazier is big and heavy.  This is much smaller and lighter than a full brazier making it good for a day pack or emergency pouch, but much more fussy about fuels and requires more work to keep it going (so Brazier still has a place in field camps)

Notes:
I've swapped out in place so it'll still spawn all the old places
I've changed the can to Medium as that's more reasonable (and didn't exist when the recipe was first added)
I've changed the necessary tool qualities (metal sawing 1, drilling 1) to match the IRL recipe below
I've slightly increased the difficulty to make it
It's not auto learned, only available in book (but can still be found in world as before)
It now also functions as a container (like it's can) but can't hold water and has a minimum size (should be able to hold tinder if I did my math right)

#### Describe alternatives you've considered
Alternatives: Just drop it entirely but I think there's a place for it when you don't want to carry around something as big as a brazier and you're willing to fiddle with fuel a lot in exchange.

#### Testing
Still needs to be tested

I think I got all the places the old version was used but if you find any feel free to let me know or adjust as needed

also I'm not quite sure if the stats are right (like what you get when you destroy it, and the pocket stats) so if anything looks weird feel free to note it for adjustment

#### Additional context
Based new version on this real world recipe: https://www.motherearthnews.com/diy/how-to-make-hobo-stove-zmaz84zloeck

### CODE REVIEW

**Comment by Xpyder** [comment]
Can someone remind me where the style guide is so I can fix the formatting and lint it?

**Comment by anothersimulacrum** [comment]
https://dev.narc.ro/cataclysm/format.html

**Comment by Xpyder** [comment]
It keeps saying the following but I've already done what I think it's asking (add Balance after summary) ?

Error: Please fix your PR SUMMARY line to match (\n|^)#### Summary\s+`{0,3}(SUMMARY:\s+)?(None|((Features|Content|Interface|Mods|Balance|Bugfixes|Performance|Infrastructure|Build|I18N) +".*"))`{0,3}\s*(\n|$)

**Comment by anothersimulacrum** [comment]
`Balance "Change Hobo Stove to deployable furniture."

**Comment by Xpyder** [comment]
Ty, updated summary

**Comment by Xpyder** [comment]
Also to make it could probably be (metal sawing 1 + (drill 1 or awl 2)) but I'll leave that for another time

**Comment by Xpyder** [comment]
the pocket is still bugged (intent is to let it hold items of tinder size  or larger even when inside a pack [open to adjusting to splintered wood+ if people prefer])

but currently it indicates it spills if put in a pack.  That said it's in a good state right now so I'll leave that fix for another time as it's relatively minor

**Comment by I-am-Erk** [comment]
The post says this needs testing. Have you tested it? I'm happy to merge if this is working.

**Comment by Xpyder** [comment]
I tested it before 0.F went live and it worked

**Comment by Xpyder** [comment]
Unless something happened that would have broken Braziers (which these are almost identical to just with different values) then it should be safe to merge

**Pull request merged**
