### PR TITLE
Duffel bag & backpack material / recipe fix

### PR DESCRIPTION
**Pull request by tvm1**
As mentioned by Chezzo, it was possible to craft duffel bag with rags only and disassemble it for rags and plastic chunks. Also alternative materials for crafting recipe didn't made much sense (fur/leather/etc.), duffel bags are made of cotton and yield rags on disassembly.

Same problem applies to backpack.

### CODE REVIEW

**Comment by chaosvolt** [comment]
> Crafting a duffel bag using nothing but rags, having to cut it apart due to current character having the Huge trait...getting 10 rags and 10 plastic chunks.

Chezzo wasn't the only one to comment on this. :V

**Comment by tvm1** [comment]
Oh well.

/me gives cookie to chaosvolt.

**Comment by chaosvolt** [comment]
Huehuehue. o3o

I'm sure there are other items with similar issues as well, but would need to mess around with finding them. I do recall that I'm fairly certain that steel-toed boots have the "no salvage" token to prevent turning them into scrap metal.

**Comment by tvm1** [comment]
Today, I've had some beers and the enlightenment, I'm writing some kind of sanity checker for that stuff.

**Comment by chaosvolt** [comment]
Should be entertaining to see. owo

**Comment by kevingranade** [comment]
The general fix for this was supposed to be the fact that survivor-crafted items have the actual items used to craft them stored with the item, and you get them back if you disassemble them, is this broken now?

**Comment by Rivet-the-Zombie** [comment]
>is this broken now?

Last I knew it was still working, but I haven't tested it in a while.

**Comment by kevingranade** [comment]
Aah, you mean it can be "cut up" for plastic chunks.  If you have a way of having that operation make sense and return the right items, please do so, but we're not removing a bunch of crafting options to make it happen.
We could probably check if it's a crafted item and select items from the list to return instead of using the normal cut up code.

**Comment by chaosvolt** [comment]
Material tweaks would be the logical fix for cutting, or applying the NO_SALVAGE token.

Cutting stuff up can cause a lot of silly results at times.

**Comment by tvm1** [comment]
Fair enough then. I've reverted the recipe commit, so only the plastic removal remains.

I've found some other items which yield materials that are not used in the crafting recipe and will address theme in separate PR.

**Pull request merged**
