### PR TITLE
[Aftershock] Move non scifi vehicle parts to Blaze Industries

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Mods "Vehicle parts from AFS to Blaze"

#### Purpose of change
I have had this move of non sci fi vehicle parts to Blaze on my to do list for most of a year.  

#### Describe the solution
Moves json from AFS to Blaze and creates obsoletes in AFS for people that don't use Blaze.

#### Describe alternatives you've considered
Solely obsoleting them.

#### Testing
TBD

### CODE REVIEW

**Review by Mom-Bun — CHANGES_REQUESTED** [review]
Thank you, this was needed!

Just to note: Please obsolete trailer vehicles with this; if you can? It doesn't fit aftershock, and should indirectly solve #45701

You can move it to Blazemod; but considering the current bugged implementation, might not be a good idea until C++ support gets added for trailers; and trailers should be vanilla anyhow. 

Also thoughts on adding the bubble car to this? Afaik the only sci-fi thing about it is the nuclear reactor; and that is it, its just a regular weird looking car.

**Comment by John-Candlebury** [comment]
I have no problem with bubble car and the other atomic vehicles staying in.

**Comment by Mom-Bun** [comment]
> I have no problem with bubble car and the other atomic vehicles staying in.

No No; I'm fine with the other atomic cars as those are sci-fi, its just the bubble car is just a bit... random? Like Its a weird curvy car that exists and randomly has atomic reactor for... no reason?

It is apparently modeled after a real car from the 1990s; and it had no nuclear reactor in it.

**Comment by Maleclypse** [comment]
> Thank you, this was needed!
> 
> Just to note: Please obsolete trailer vehicles with this; if you can? It doesn't fit aftershock, and should indirectly solve #45701
> 
> You can move it to Blazemod; but considering the current bugged implementation, might not be a good idea until C++ support gets added for trailers; and trailers should be vanilla anyhow.
> 
> Also thoughts on adding the bubble car to this? Afaik the only sci-fi thing about it is the nuclear reactor; and that is it, its just a regular weird looking car.

The trailers were in the vehicle override file so I'm wondering if the trailers exist in vanilla but I'm not interested in checking :). I've deleted them entirely.

**Review by Mom-Bun — APPROVED** [review]

**Pull request merged**
