### PR TITLE
Crabapples and Rosehip Nerf

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Balance "Add crabapples, reduce rose hip yield, reduce cultivated wild fruit tree frequency"

#### Purpose of change

There are huge amounts of fruit in the woods, and roses produce way too much fruit, giving up to 10 cups of rose hips for a single patch - IRL rose hips yield far less than normal fruit crops, and the fruits themselves contain much less edible matter, being mostly seeds and inedible hairlike spines. 

#### Describe the solution

- Adds crabapples. Most wild-growing apples in New England are feral varieties which have accidentally been dispersed into the area. Due to how apple biology works, planting an apple seed even from a good tree almost never yields a fruit which is as large or sweet as the domestic cultivars.
- Adds crabapples to recipes. Enjoy your crabapple pie.
- Reduces calorie, and vitamin values on rose hips by half. Their nutritional values were technically correct, but were for the prepared form of the fruit. The unprepared fruits are ~half as nutritious by volume due to the presence of inedible seeds.
- Rose hips must now be disassembled before use unless you are a bear or a rabbit. Unlike other berry-type foods, the seeds are not edible and removing them is a very minor chore.
- Fixed a bug that allowed entire watermelons to be smoked whole.
- Adjust spawns of wild fruit trees. Peaches, plums, and pears are half as common as they were. Most apple trees have been replaced with crabapples. This does not affect orchards, trees growing in people's yards, or the forest tiles that are full of fruit trees - these appear to be remains of old orchards, and should have plentiful fruit still growing.

#### Describe alternatives you've considered

I'd prefer to work off of a survey of wild tree species in New England, but I can't find one (edit: I found one. We're mostly looking good, though our forests are notably missing ash trees), and there really isn't any data on what percentage of trees would be crabapples. From personal IRL observation I can say that just about any apple tree you find, even ones in people's yards, produces crabapples more often than not.

I'd also like to differentiate wild and domestic roses and grapes, and have the domestic varieties produce less of the same fruit, but that's pending a seed rewrite.

There may be too many nuts still. I'm not sure. I'll find someone who works at a university over there and email them about it, then get that (and any further fruit corrections) in another PR.

Roses should maybe not even be plantable. I've left them in for now, but it actually takes a couple of years to grow a fruiting rose bush from a seedling. I'll address this when I'm able to further rework crops.

#### Testing

Spawned in, picked apples, picked rose hips, picked crabapples, observed different forest tiles to see no strange behavior. Saw that calorie values on the fruits were as expected. Checked recipes, smoked fruit.

#### Additional context

image
Summertime forest tile. There's still plenty of fruit to be had, but it's a bit more reasonable.

A video on rose hips, showing how little yield you get compared to proper berries: https://www.youtube.com/watch?v=gU4UhqhjMgA - some varieties have more or bigger berries, but some roses produce none at all. They're great for supplements and treats, but not a good food crop.

### CODE REVIEW

**Comment by Karol1223** [comment]
> Reduces volume, calorie, and vitamin values on rose hips by half. They're still great sources of vitamin C, but are no longer superior to most other kinds of fruit.

I disagree with this because this creates confusion among the "handfuls" of small fruit. If possible could you instead adjust how much rose hip units are harvested per bush? You'd get the same results without adding to the confusion.

**Comment by fairyarmadillo** [comment]
> > Reduces volume, calorie, and vitamin values on rose hips by half. They're still great sources of vitamin C, but are no longer superior to most other kinds of fruit.
> 
> I disagree with this because this creates confusion among the "handfuls" of small fruit. If possible could you instead adjust how much rose hip units are harvested per bush? You'd get the same results without adding to the confusion.
> 
> Also for the record rose hips have accurate values per gram, but the issue is that they are harvested in the already edible form - I am pretty sure that's not the case irl and they need some preparations before they're edible? If you want to nerf them that'd be a step in the right direction.

Changing rose hip harvests won't work because the player-planted crop grown from the same seed will give a different amount of fruit. What I could instead do is return the volume of the item to 250ml and leave the calorie/vitamin values as they are, with the calorieless volume representing the inedible bits. That way the player doesn't have to micromanage deconstructing every piece of fruit they want to eat, but can still choose to do so (and still eat the cut remainder of the fruit) if they'd like to keep the seeds.

**Comment by fairyarmadillo** [comment]
https://youtu.be/eNJ0_hkEBfU

This lady explains how to eat 'em without preparing them at around 1:30

**Comment by Karol1223** [comment]
> Changing rose hip harvests won't work because the player-planted crop grown from the same seed will give a different amount of fruit

Elaborate on that? Most rose hips are obtained from specific furniture/terrain/whatever bushes spawned by mapgen which I was sure were separate from the crop harvests? Sure, there are planted crop versions of them - but imo the issue there is that we have them spawn as crops, because they almost certainly weren't planted with food in mind. I do believe the issue should be handled at the harvesting step, but you're more experienced with C++ than me so I'm assuming you know this won't work and I just don't understand what you mean fully.

> If you think they should need to be uncrafted before being edible at all I can make it work that way, but this isn't like cutting up a canteloupe or something where there's some real effort involved. Could work either way imo

No, I think the unprepared versions being edible is fine but they should probably lower fun and have "raw" or "unprepared" in the item name because otherwise everyone updating is going to be hella confused. Could probably use a description edit to indicate you need to prepare them, too. People were confused when I didn't give that edit for melons.

At the end of the day my main concern is that saying "the numbers are different than what is found online" doesn't indicate you have any resources for your numbers. I am not a fan of switching values backed by online sources for values which for all intents look to be arbitrarily chosen. Unless you forgot to remove that comment on the cut rose hip versions, in which case that's a different thing.

Also you should apply the changes to the fruit requirement where they're used in recipes if you want to go this route, because as it stands only the unprepared fruit are usable in recipes, and they're still used in the amount that assumes they're prepared.

**Comment by fairyarmadillo** [comment]
> Elaborate on that? 

Wild plants, that is, t_shrub_rose, have a bespoke harvest json entry in harvest.json. Roses which the player plants, or those spawned by the game using the generic f_plant_harvestable furniture (used extensively in malls and many other maps) don't pull from this, they have a hardcoded value in iexamine.cpp shared by all plants, a random number between 1 and 12 (iirc) modified heavily by the harvester's survival skill.

I have plans to redo how crops work so that this isn't always the case, but for now we're stuck with most of the rose bushes that aren't growing in the woods giving preposterous amounts of fruit, unless I modify the rose hips item itself somehow.

> Unless you forgot to remove that comment on the cut rose hip versions,

I did forget. The only change I made to the relative calories was to half those in the unprocessed hips, because it seems that about half their volume is accounted for by inedible bits.

> Also you should apply the changes to the fruit requirement where they're used in recipes if you want to go this route, because as it stands only the unprepared fruit are usable in recipes, and they're still used in the amount that assumes they're prepared.

Argh I forgot.

**Comment by fairyarmadillo** [comment]
I went ahead and made the rose hips inedible until disassembled, unless you're a rabbit or a cattle mutant. While it's technically possible to pinch the pulp out of them as shown in the video below, they're now using the same logic we use for melons. The pinched pulp method wouldn't work well for larger varieties of rose hips, the pinched pulp versions wouldn't be suitable for many of our recipes, and you'd be leaving lots of calories behind.

https://homesteadandchill.com/rose-hips-harvest-dry-use/ This blog post goes into detail about how preparing them for use is kind of a pain in the butt. One of my motivating factors for starting this PR was that I'd noticed that rose hips were _the_ fruit meta, which isn't true IRL. IRL they're certainly nutritious, but they're not a good source of foragable calories compared to other autumn fruits and vegetables due to low yields and the annoying labor involved. That should be reflected in our simulation.

I also noticed that it was possible to put a whole uncut watermelon in the charcoal smoker and get a single piece of 1000 calorie dried fruit, so I nixed that.

**Comment by Karol1223** [comment]
> Roses which the player plants, or those spawned by the game using the generic f_plant_harvestable furniture (used extensively in malls and many other maps) don't pull from this, they have a hardcoded value in iexamine.cpp shared by all plants, a random number between 1 and 12 (iirc) modified heavily by the harvester's survival skill.

To be fair, I feel like we should swap the "crop" mapgen-spawned rosehips for the furniture version since they weren't cultivated for food, but it's a separate problem altogether.

And the hardcoded amount of harvest per crop is... quite a big deal, unfortunately. I accidentally created a watermelon crop meta this way. Fixing it would be preferable, but it's C++ bullshit and I can't exactly ask you to fix my mess 😅

**Comment by fairyarmadillo** [comment]
> To be fair, I feel like we should swap the "crop" mapgen-spawned rosehips for the furniture version since they weren't cultivated for food, but it's a separate problem altogether.
> 
> And the hardcoded amount of harvest per crop is... quite a big deal, unfortunately. I accidentally created a watermelon crop meta this way. Fixing it would be preferable, but it's C++ bullshit and I can't exactly ask you to fix my mess 😅

Agreed on both counts.

I do fully intend to fix the hardcoded crop yield problem, but it's a doozy. The way we are currently doing crops in general is unsustainable if we want to add more planter types, hydroponics, etc. - my intent is to get away from hardcoded results and the generic "plant" furniture, and instead have as much as possible (including yields) jsonized in seed_data. From there I can have seeds grow into the same kinds of plants they are in nature, so if you plant a rose seed in t_dirtmound it will eventually grow into t_shrub_rose, or something which is functionally identical to it, after a couple of years.

I'm still in the early stages of trying to organize a solution. It's not a huge challenge codewise, it's just a matter of organizing all the logic in the simplest way possible.

**Comment by Karol1223** [comment]
> Going through and pulling all the crop-style roses could happen in another PR unless you consider that a blocker here.

No, I think it's fine to be done later. The crops are mostly a side issue that I just remembered about, not related to this. Everything looks good to me here.

**Comment by fairyarmadillo** [comment]
> EDIT: If we have flags for that, perhaps make bird mutants able to eat unprepared rosehips? Birds tend to do that.

We do! Done.

**Pull request merged**
