### PR TITLE
Make bicycles more likely to exist

### LINKED ISSUE #37451: Pedal-driven bicycles are unrealistically rare
**Is your feature request related to a problem? Please describe.**  
Bicycles are very difficult to find despite most households owning at least one in real life.

**Describe the solution you'd like**  
Spawn rates of bicycles should be increased, and should also spawn inside houses and garages.

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

```SUMMARY: Balance "Increase bicycle, dirt bike, and electric bicycle spawn rates"```

#### Purpose of change

Fixes #37451

#### Describe the solution

Prior to this change, bicycles had (by rough count) only a 3% chance among the vehicle pool on city streets (less than half that of armored vehicles). This seemed way too low, so I wanted to give bikes a fairer chance.

This commit changes three vehicle groups, including:

city_vehicles:
- Bicycle equally likely as the standard car, or twice as likely as a Hippie Van.
- Dirt bike as likely as a Hatchback or Hippie Van
- Electric bicycle as likely as a Beetle or RV

suburban_home:
- Bicycle as likely as standard car
- Dirt bike as likely as SUV
- Electric bicycle possible, as likely as scooter or sports car

parkinglot:
- Bicycle as likely as car or flatbed truck
- Dirt bike possible, as likely as hatchback or motorcycle

#### Describe alternatives you've considered

Part of the imbalance is that there are so many different car, truck RV and armored vehicle types that they outweigh the puny 3 kinds of bicycles. Having more bicycle types would help this problem too but that seems like another issue.

I considered (and tried) setting the dirt bike spawn rate to 100000000, but that was definitely too many bicycles.

#### Testing

Tested by creating new worlds and using debug to teleport around city streets. Bicycle density is definitely increased, but not too much so.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I love the idea of making bikes more common, but I don't think they're *this* common. There's no way, for example, that dirt bikes should be as common as hatchbacks in parking lots. I don't know if I've ever seen a dirt bike in a parking lot.

For the street versions, you could try looking up a statistic for how many cyclists there are in a state like Massachusetts compared to drivers, and go from there. Remember that by default we're talking about April.

The major solution here is to add more bicycles to houses. You could take a look at the new nested mapgen for gardens and yards and add a bicycle shed as an optional spawn, for example.

**Comment by jkraybill** [comment]
I'm still pretty bad at this game, but I find bicycles to already feel pretty OP in the very early game. While I agree that bicycles would be more common IRL, I'm not sure that making them massively more common is the right answer right now. If anything, I'd suggest revisiting to make it more necessary to scavenge for bike parts or chain oil or something.

**Comment by 8street** [comment]
> I love the idea of making bikes more common, but I don't think they're _this_ common.

I also think that twice more will be enough.

**Comment by Eliijahh** [comment]
It seems fairly difficult to find stats on bycicle use in New England, at least at a glance. Only data point I was able to find was this ([website](https://www.bikeattorney.com/massachusetts-bicycle-accidents.html)) for Massachussets:

- There seems to be 762,000 who ride bikes at least once in the summertime, but does not specify whether by rental or ownership
- Out of a total population of around 7mln, this is slightly more than 7%

It is really easy to find stats about accidents, but very difficult for bicycle ownership, which could make sense as I do not believe there is any requirement to register a bike. 
Agree with @I-am-Erk, probably would make sense to increase the numbers of bycicles within houses, potentially locked with a padlock or in a sort of outside storage container.

**Comment by TechyBen** [comment]
Locked bikes would make bolt cutters/picks a nice content lock... that and the reliability of bikes could be adjusted? More spawning with minour/larger damage to them?

**Comment by wapcaplet** [comment]
Mountain bikes don’t belong in parking lots, I agree, though store fronts IRL may have bike racks or other dedicated bicycle spots. It’d be great to have bike racks with bikes (or pieces of bikes) locked onto them, requiring bolt cutters, hacksaw or lock pick to remove. I’m not even sure how the mechanics of that would work - can a vehicle be “anchored” to another vehicle or piece of furniture in this way now? That would be a cool new feature but I think beyond the scope of this PR.

I’m happy to reduce the rates I used, though I still think bikes should be at least as common as armored cars. In current experimental you’ll see two SWAT trucks, Humvees or similar vehicles for every bicycle in the street. I know that’s more of an argument for reducing armored cars than adding bikes, but either way it’s a weird imbalance. Anyway, I’ll knock it down a bit.

I will also look into spawning bikes more frequently next to sheds or in the back yard of houses, or such out of the way spots, so you’ll have to look around a little for them. Maybe I will even hide a (folded) folding bicycle in a closet here and there.

Thanks everyone for the feedback. Updates will follow :-)

**Comment by wapcaplet** [comment]
Alright, I've pushed some revisions to my bicycle spawn rates, bringing them down to just about 2x what they were before I muddled with them. See commit message https://github.com/CleverRaven/Cataclysm-DDA/pull/37457/commits/d895b7c9b8512734ab49d4ca9f8c14979e6a66e0 for all the gory details.

Here's the cool part, though - I made a bike shed! Again, I'll spare you the full details, which can all be found in the commit https://github.com/CleverRaven/Cataclysm-DDA/pull/37457/commits/a7fe71c6abafa87ee974987485825699c4634ef0 

But here are some nice screenshots. Note, the screenshot was taken with tool spawn rate at 90% just for testing and demo; actual spawn rate is only 10% for the tools. But If you find one of these sheds, and manage to pick the lock, you have a 50% chance of finding a bicycle (or some other bike shop vehicle) inside! Just be careful maneuvering it out the door:

"house_patio"
image

"house08"
image

With that, I am ready to call this issue completed, unless there are any further concerns.

**Comment by wapcaplet** [comment]
Oh dang, failed linting... lemme fix

**Comment by wapcaplet** [comment]
Alright, as far as I can tell my JSON is fine. My last commit was pasted directly from the output of http://dev.narc.ro/cataclysm/format.html but it still failed linting. Is there a command-line tool or vim plugin or something to make this easier?

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md says the formatter can be "invoked directly via the Makefile" but neglects to explain how. The only way I know of is to do a full build, then wait until the end when it reads all the JSONs, but I know there has to be a quicker way.

**Comment by davidpwbrown** [comment]
Looks good to me.

**Comment by Brian-Otten** [comment]
The new version with the edits looks good to me, would love to see it merged.

**Comment by JonathanLochridge** [comment]
Did you still add the spawn chance for bicycles in parking lots? I don't think they should spawn there at all. Just in houses, on the roads, or in front of shops.

**Pull request merged**
