### PR TITLE
Move Zombie Bio Operators to No Hope

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Move Zombio Bio Operators to No Hope"

#### Purpose of change

Zombie bio-ops were from when common-place bionics existed and were not Exodii bound. CBMs are exodii-bound now, and as such zombie bio ops can be removed. They also didn't give bionics anyways.

#### Describe the solution
Moves them over to No Hope

#### Describe alternatives you've considered
Not migrating them to no hope and just removing them outright.

#### Testing
Vanilla:
image
image
No hope: (spawning naturally)
image
No hope: dissecting for bionics
image

### CODE REVIEW

**Comment by EirenexTheDragon** [comment]
You talk about how the Bio Operator were still related to Old lore , which isnt the case anymore. The lore has  been changed on Bio Operator already, they are the zapper variant of Zombie Soldiers since then and their description makes it clear aswell. wouldnt it be easier to remove the Bio take down attack instead?

**Comment by Holli-Git** [comment]
Has it? They don't evolve from anything, and the name still gives hints that it's bionic-related. To me it still very much feels like the old bio-ops, just with the bionic dissections removed

**Comment by EirenexTheDragon** [comment]
This is the current description
>"description": "This armored soldier zombie appears to have been some sort of special forces agent.  Its malfunctioning equipment sends out occasional showers of sparks.",


I cant find the old description, but i am certain it talked about how  the Zombie Bio operator retained their combat knowledge thanks to bionics. 

Youre right, they still act like the old bio operators, because they still retained the Bio Takedown. it woldnt make sense for them to retain it as Zombies shouldnt know such techniques. so just removing the line of bio takedown seems like the most simple approach while retaining their danger in being shocking and armored instead

**Comment by Holli-Git** [comment]
I'm thinking of adding a spec ops feral to replace them (Shoutout Anid for the idea), and I think it'd still be better to move these to No hope, so that there can be spec ops ferals and bio ops in No Hope

**Comment by Maleclypse** [comment]
> I'm thinking of adding a spec ops feral to replace them (Shoutout Anid for the idea), and I think it'd still be better to move these to No hope, so that there can be spec ops ferals and bio ops in No Hope

This makes sense. Thanks!

**Pull request merged**
