### PR TITLE
Fix #41329: Plutonium fuel cell duplication

### LINKED ISSUE #41329: Plutonoum fuel cell duplication when reloading a hologram cloak or RM13
# Describe the bug

1. Reloading a hologram cloak or RM13 produces 500 charges per fuel cell, but unloading produces 1 fuel cell per charge leading to duplication.
1. They also have an absurdly high volume and weight when fully loaded with plutonium similar to #40860.
2. The "encumbrance when full" stat on the item info display is also way too high, but real encumbrance does not actually increase based on how mush plutonium they are loaded with.

# Steps To Reproduce

1. Wish for a hologram cloak.
2. Unload it.
3. You now have a 1000 plutonium fuel cells
4. Puck 2 of them up
5. Teleport far away
6. Reload your cloak
7. See that your cloak is now fully loaded

# Expected behavior

1. Weight and volume should be sane
2. Reloading should not cause duplication

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3208-gbd9759e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

#40860 has similar symptoms except that unloading UPS does not work at all instead of duplication plutonium cells.

### PR DESCRIPTION
**Pull request by cfraenken**
#### Summary

SUMMARY: Bugfixes "Fix plutonium duplication and it's weight/volume inside tools"

#### Purpose of change

Fix #41329

#### Describe the solution

Add a check when unloading a magazine that takes plutonium and override the amount of fuel cells it should drop.
Add a check when calculating the weight/volume of an item using plutonium and adjust the values.

#### Describe alternatives you've considered

make plutonium fuel cells magazines that take plutonium charges instead of hacking plutonium  it in like this.

#### Testing

Tested on various items using plutonium based ammo. Weight/volume seems to be correct now, unloading yields sane amount of fuel cells. checked edgecase of not having enough plutonium charges to drop a fuel cell, doesnt drop any fuel cells and give message "can't unload partially used plutonium fuel cells".

#### Additional context
advanced UPS still broken (related to #40860) , but has correct weight/volume values now.

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
> make plutonium fuel cells magazines that take plutonium charges instead of hacking plutonium it in like this.

Wouldn't this require adding c++ support for items with multiple magazines? You can put 10 plutonium fuel cells into RM13. A simpler solution is to switch plutonium fuel cell powered items to use plutonium fuel batteries. They are not rechargeable just like the cells and there already are recipes to craft the batteries from the cells.

**Comment by cfraenken** [comment]
> Wouldn't this require adding c++ support for items with multiple magazines? You can put 10 plutonium fuel cells into RM13. A simpler solution is to switch plutonium fuel cell powered items to use plutonium fuel batteries. They are not rechargeable just like the cells and there already are recipes to craft the batteries from the cells.

What i meant is that the plutonium fuel rods should behave like the plutonium batteries we already have (not reloadable .etc) and that tools using those would only be able to take one fuel cell, like with batteries. But you are right switching to plutonium fuel batteries is a lot simpler, probably possible by just changing stuff in json.

**Comment by cfraenken** [comment]
I tested giving plutonium based items a magazine_well pocket that only accepts plutonium fuel batteries and use battery charges instead. That works and it even fixed the advanced ups  (see #40860) (it still applies the efficiency bonus from using plutonium though. maybe change?).

**Comment by cass-wedson** [comment]
Maybe add the rigid flag to the new pocket data, such that they don't show the possible encumbrance value, specially if the hologram cloak is using a 35 ml battery.

**Pull request merged**
