### PR TITLE
Partial fix for plutonium reload

### PR DESCRIPTION
**Pull request by Coolthulhu**
A hack, but better than nothing.
In `item::reload`, `qty` refers to minimum of capacity left and ammo usable. It was divided by `PLUTONIUM_CHARGES`, which doesn't make sense for plutonium cells.

The whole plutonium reload multiplier will most likely be going away, so there is no need for a proper fix - a hack should suffice.

Doesn't completely fix the issue from user's point of view, since it turns plutonium items into something effectively equivalent to RELOAD_ONE, but restores the ability to actually reload plutonium items.

### CODE REVIEW

**Comment by mugling** [comment]
We should fix `plutonium` to be something useful (see #17086) rather than an annoyance requiring special cases. Having just reworked the reloading code to remove all the special cases I've no desire to add hacks to it for the sake of convenience.

One possible option is that plutonium cells become non-reloadable magazines in a similar manner to vehicle batteries and acetylene tanks.

**Comment by Coolthulhu** [comment]
> Having just reworked the reloading code to remove all the special cases I've no desire to add hacks to it for the sake of convenience.

You didn't remove all the special cases. You left in the plutonium special case with its hacks.
I simply add a hacky solution to render those hacks actually operable.

The plutonium bugs stayed there for a while. Nobody bothered to fix them, despite them being known for 2 months.

> We should fix plutonium to be something useful (see #17086) rather than an annoyance requiring special cases.

Sure.
But until it happens, "hacky but working" is better than "a tiny bit less hacky but not working".
Fix, rewrite, upgrade or get rid of it - anything but keep it in in its broken form.

**Comment by mugling** [comment]
> You didn't remove all the special cases. You left in the plutonium special case

There's truth in that - `plutonium` lacks a good solution. The vehicle code has a similar problem. If we're going to work on it further it seems wrong not to attempt a proper fix especially given there's a very recent issue (#17086) open discussing how best to proceed.

**Comment by Coolthulhu** [comment]
> If we're going to work on it further it seems wrong not to attempt a proper fix especially given there's a very recent issue (#17086) open discussing how best to proceed.

I removed the "Fixes #issue", now there is no reason to oppose this partial fix.
It doesn't make it any harder to properly fix the issue, there is no obvious solution that does it better and it fixes an old problem.

There is no consensus regarding how plutonium should be working except for the part that it should be working. This PR brings us significantly closer to that without making a proper fix harder to write.

**Comment by mugling** [comment]
`obj->charges += std::min( cells * PLUTONIUM_CHARGES, qty * PLUTONIUM_CHARGES )`

could become:

`obj->charges += std::min( cells, qty ) * PLUTONIUM_CHARGES`

**Comment by mugling** [comment]
Part of the objection is in context that there are a number of other PR's that attempt to hack around more architectural problems. They may all have their individual merits but collectively it's the wrong approach

**Comment by Coolthulhu** [comment]
> They may all have their individual merits but collectively it's the wrong approach

Worse Is Better

It's better to have a working (but ugly) fix that can be thrown away on a whim and replaced with a proper solution than to wait for the proper solution that never arrives/arrives far too late.
Doubly so when users are involved and the project isn't just for the developers.

**Comment by mugling** [comment]
It's subjective:

Excellent hack: #17179
Bad hack or good solution: #16797 vs #16799 or  #17060 vs #17063

This PR isn't especially problematic as you're correct we already have a (broken) special case for plutonium. Equally though it doesn't have the same urgency as for example #17179.

The same cannot be said for #17272 where a special case is being added.

**Comment by Coolthulhu** [comment]
> Bad hack or good solution: #16797 vs #16799 or #17060 vs #17063

In all those cases the hack is bad because it alters a code that will stay with us for a while.

This one alters a bit of code that is about to be thrown away "sometime soon", without integrating it into the hack-less sections.

> Speed of resolution is important, but not at the expense of correctness.

That depends on the case.
A horrible hack now is better than perfect solution never.
A single ugly hack to make blazemod not produce errors on load is better than correcting all the horrible hacks in the mod.
A bandaid with "this is broken, fix it when someone figures out how to" comment and a special case that makes it usable is better than leaving a case broken wide open because a proper fix is hard.

> The same cannot be said for #17272 where a special case is being added.

A special case that restores functionality to a significant portion of the game by bringing back RELOAD_AND_SHOOT is better than generic solution that fails to address that.

As long as the hacks aren't integrated into the game (for example, lack of `const`ness cascading down, making it impossible to actually `const` anything) and are easy to remove, they're just the lesser evil.

**Comment by mugling** [comment]
> This one alters a bit of code that is about to be thrown away "sometime soon", without integrating it into the hack-less sections.

Agreed as above

> (#17272) A special case that restores functionality to a significant portion of the game by bringing back RELOAD_AND_SHOOT is better than generic solution that fails to address that.

If anything it should be special cased in `item::reload_option` but that wouldn't help with the actual major cause which is likely to be #17274. This is the danger in hacks - you often end up layering them.

**Comment by Coolthulhu** [comment]
> This is the danger in hacks - you often end up layering them.

**Comment by mugling** [comment]
Just tested this, it's still broken in that you can repeatedly reload the advanced UPS adding 500 units per attempt. You can't use the arrow keys via the **p**art reload option either.

**Comment by Coolthulhu** [comment]
Yeah, it is a partial fix.

It's an improvement over "broken hard".

**Pull request merged**
