### PR TITLE
Gives repeating crossbow skill consistent with properties

### PR DESCRIPTION
**Pull request by DangerNoodle**
This pull request changes the repeating crossbow skill back to archery. Reasoning is it no longer has the burst fire function that warranted the skill change, and a cho-ko-nu is not operated like a firearm.

### CODE REVIEW

**Comment by Chezzo** [comment]
Aww, you mean it's not one of these? 

https://www.youtube.com/watch?v=tbKGjRoSofA

**Comment by kevingranade** [comment]
Burst fire wasn't the reason it was switched to smg, take a look at a video of a cho-ku-no firing.

**Comment by DangerNoodle** [comment]
How in the hell do you think "manually depress a lever up and down on a weapon that often lacks sights" and think that a weapon skill requiring sight alignment, recoil control, and proper use of burst fire is even remotely relevant?

https://www.youtube.com/watch?v=BFKg7Z-CuZ8

This does not resemble the operation of a fully automatic firearm. Mistaking the two methods of operation is indicative of having never fired crossbows or firearms..

**Comment by kevingranade** [comment]
And it resembles using a bow and arrow how?
There's not a particularly good match for any of the weapon skills, smg is the least bad match.

> Mistaking the two methods of operation is indicative of having never fired crossbows or firearms.

This kind of fallacious argumentation is unacceptable, reign it in or leave.

**Comment by DangerNoodle** [comment]
It is closer in operation to a crossbow than a firearm, at a bare minimum. Archery still covers bows and crossbows, sub machineguns are a much more specialized method of handling. Just because they can be fired from the hip, does not mean you should. Unlike repeating crossbows where firing from the hip is the more practical method of operation.

And my apologies for that outburst, but I feel I should highlight something here.

image

I have, as far as I recall, never before resorted to profanity in my posts before, mild as this was. Again, my apologies for that and for my remark at the end, but this closure reason has no grounding in reality.

**Comment by DangerNoodle** [comment]
See discussion as raised here: https://github.com/DangerNoodle/Cataclysm-DDA/issues/2

**Comment by AlecWhite** [comment]
https://www.youtube.com/watch?v=PnOuHLAtDoc

Here is a crossbow tutorial for more information regarding functionality and management.

I would like to point out that it is compared with a rifle in the video.

**Comment by kevingranade** [comment]
> Archery still covers bows and crossbows,

This is also incorrect, archery should only cover bows and slingshots, which are similar to each other but not remotely similar to a crossbow in operation.

> Instead you presented a single-line reason that was already fallacious in nature,

I disagree, what seemed to be your primary rationale for the change, equating the use of the smg skill to the burst fire capability the cho-ku-no used to have, was incorrect, if you look at the commit in question, it simultaneously removed burst fire and changed the skill to smg.  I know this because I wrote said commit, and I assert I understand my intentions better than you.

If you had bothered to search either the forums or github or check the file history, you would have seen previous discussion on this exact subject.  If you can't be bothered to do a bare minimum of research before opening a pr, why should i spend a lot of time refuting it?

**Comment by DangerNoodle** [comment]
The second reason, that the weapon should use the most appropriate skill, is the higher priority statement. I apologize for having assumed that not changing the skill was an oversight, but I had assumed it was accidental.

Put simply, the point I am making here is twofold, and the second part you still have blatantly ignored:
1. Even if crossbows should not use the archery skill, they do last I checked.
2. The repeating crossbow is operated in a manner closer to that of a crossbow than to that of a firearm, and should use the same skill as other crossbows, **whatever that skill may be.**

**Pull request closed without merging**
