### PR TITLE
.223 Caliber Firearm Ranged Damage Rebalance Based on Muzzle Velocity

### PR DESCRIPTION
**Pull request by rtizzy**
Balanced all 223 weapons to more reasonable values based off muzzle length/muzzle velocity. 

The 223 pistols use 0 damage. 223 survivor carbines use 1 damage since it's more crude. 223 carbines use 2 damage. 223 standard length rifles use 3 damage. 

Some 223 weapons were high as 6 and as low as -6 regardless of barrel length which didn't make a lot of sense.

### CODE REVIEW

**Comment by kevingranade** [comment]
Can you document somewhere, such as in doc/AMMO_STATS.md what your values for barrel length and such are?  If we're moving to data-based balance, we need the data available.

**Comment by elricsfate** [comment]
@kevingranade 

The logic used was simple enough. A firearm is classified as one of the three:

Pistol: A weapon that has a pistol length barrel. These have 0 damage modifier 
Rifle Carbine: A rifle with a shorter than usual barrel. These use 2 damage. 
Rifle Standard Length: A rifle with a standard length barrel. These use 3 damage.

Weapons that are considered "crude" do 1 less damage than the barrel length they are based on. 

The barrel length was determined by the description of the weapon currently in the code. 

Let me know if you would still like this documented at the mentioned. Would the top of the ranged file perhaps be a better place to go over the barrel lengths? Keep the comments with the code.

**Comment by Rivet-the-Zombie** [comment]
This robs a lot of uniqueness from various firearms.

**Comment by Coolthulhu** [comment]
Change of ~5 damage isn't much when the cartridge itself has 40.
I'd go with gameplay over realism here.
Though if it was about realism, all the guns should get adjusted dispersion/recoil values too.

Some weapons do have quite wild values of damage bonus, though. Like M27 with its +8 to damage, tiny dispersion, very manageable recoil and 15 burst size.

**Comment by kevingranade** [comment]
The rationale should go in the doc/ directory, possibly in ammo_stats.md or
possibly elsewhere, it's very unlikely that people adding guns are going to
find comments in ranged.cpp.
A range of 0 - 3 seems very small to go from a pistol to a rifle, that is a
very miniscule amount of damage in our system.

**Comment by kevingranade** [comment]
Shrinking the range of damage between pistols and rifles is very problematic, and this isn't landing without a rationale going with it.  Anyone that feels like addressing those can re-open this or a new PR.

**Pull request closed without merging**
