### PR TITLE
Finalize item definitions for artifacts

### LINKED ISSUE #22104: Artifacts do not have a category
Game version: 0.C-23389-gd993d6c

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "StatsThroughSkills",
  "blazemod",
  "Tanks",
  "boats",
  "realguns",
  "ew_pack"

### Actual behavior
extra item entry in v
An invisible entry appears on the player tile without any reason and the description of the previous item carries onto the invisible entry. There is nothing below the ground player is on.
### Steps to reproduce the behavior
- Load [the save](https://drive.google.com/file/d/0B9NNp9wUrjFgNHhIeFgxaXBBWEU/view?usp=sharing)
- Press [V] to list all items around the player and move up to find the invisible entry

Unfortunately, I haven't been able to replicate this bug so I can't provide more useful information. Maybe this is related to the vehicle parts on the vehicle?

### PR DESCRIPTION
**Pull request by Coolthulhu**
A step in direction of better support for runtime types.
Fixes a tiny bug: all artifacts were shown to be unrepairable despite some of them being repairable.

EDIT: Fixes #22104

### CODE REVIEW

**Comment by angoddu** [comment]
Will they now show up in a catagory?

**Comment by Coolthulhu** [comment]
I think they will, because finalization calls `calc_category`.

**Comment by Leland** [comment]
Nice – if they do have a category in inventory now, this fixes #22104. Haven't tested yet.

**Comment by OzoneH3** [comment]
Artifacts do get a category assigned but it's always TOOLS:

**Comment by BevapDin** [comment]
> but it's always TOOLS:

Because they *are* tools (they have the tool slot set). `calc_category` should probably check for an entry in the artifact slot and return a new category identifier.

**Comment by cainiaowu** [comment]
debug menu cant spawn some special artifact, you need to teleport to temple finale to see them.

**Comment by Leland** [comment]
Clairvoyance is an artifact

**Comment by cainiaowu** [comment]
ehh, what I mean is that there are armor/weapon artifact exist, and you cant get them via debug menu.

**Comment by Coolthulhu** [comment]
OK, added a new category for artifacts. It's second last in sort order, so that you can access it by going up in inventory menu if you have no armors.

**Pull request merged**
