### PR TITLE
Adjust ranges of SMGs and pistol caliber carbines

### LINKED ISSUE #66947: Submachine guns need a range bonus review.
### Is your feature request related to a problem? Please describe.

In game, all MP5 series guns have a bonus range of 14. The MP5A2 (225 mm barrel), MP5K-PDW (140 mm barrel length, some pistols have longer ones) and MP5SD (a proprietary silencer that slows bullet to subsonic speed), despite all of them have differing barrel lengths and constructions, all of those increase range of a 9x19 mm FMJ bullet by factor of 2 from 14 to 28. This translates to ~330 m effective range if going by tiles*12 formula, despite IRL the effective range of MP5A2 is stated to be about 150-200 m. The effective range for MP5K is even lower at 100 m.

Sources:
https://weaponsystems.net/system/227-Heckler+&+Koch+MP5
https://weaponsystems.net/system/229-Heckler%20&%20Koch%20MP5-K
https://www.militarytoday.com/firearms/hk_mp5.htm

At the same time, P90, which has the same stated effective range of 200 m (with caveats: it defeats Level 3 body armor at 200 m while having "maximum effective range" of 400 m, at which bullet delivers 85 J of energy to target) as full-sized MP5A2 (200 m).
Despite that, the ingame P90, which has a barrel 264 mm long has the same bonus range (0 tiles) as a FN 5-7 with barrel length of 122 mm.

Quoting https://www.remtek.com/arms/fn/p90/data/concept.htm:
"Three rounds are available for the P90 at this time. The standard ball round, called the SS190, features an overall length of 1.6 inches (40.5 mm), a projectile weight of 31.0 grains (2.02 grams) and a muzzle velocity of 2,345 fps (715 mps). The SS190 projectile features steel core in front of an aluminum core toward the base. The bullet penetrates about 10 inches (26 cm) of 10 percent ballistic gelatin, according to testing conducted at the Royal Canadian Mounted Police Academy in September 1997. The SS190 round will also penetrate 48 layers of Kevlar, the typical "Flak jacket" (including CRISAT protection, which is a combination of titanium and Kevlar) worn by infantry to protect them from shrapnel produced by exploding devices, or a standard PASGT (U.S. Kevlar) helmet at 150 meters (164 yards), which is the effective range of the P90 Personal Defense Weapon. The weapon will still defeat Level 3 body armor at 200 meters (219 yards). The "maximum effective range" using the NATO definition (the maximum range where a weapon's projectile will still deliver 85 joules on target) is 400 meters (437 yards). Thus, according to NATO standards, the P90 is theoretically able to deliver a lethal wound on a protected target at 200m and an unprotected target at 400m if the round hits a vital area. Personally, I would not be enthusiastic about engaging targets beyond 150m with the standard SS190 round."

Yes, 5.7x28 is not a long-ranged round, but I think a barrel that is over 2x as long should have at least some effect.

The situation is even less logical when looking at PS90, which has a 16 inch (407 mm) barrel... And has no bonus range. At all.

### Solution you would like.

Easy fix: axing the range bonus from MP5s, as it looks suspiciously like someone just copied bullet ranges to guns and they added together.

Hard fix: giving bonus ranges from +1 up to +5-7 tiles depending on barrel length. No +14 range tho.

### Describe alternatives you have considered.

Nerfing bonus range of MP5K and MP5SD to ~7 tiles. Still more than IRL at 21x12=252 m, but much more consistent in terms of logic (shorter barrel -> worse ballistics -> lower range).

Buffing P90 bonus range to about 13-14, putting it about on par with MP5A2 in terms of range. Giving PS90 bonus range of ~18, putting its range at 32... Wait... Wait.

Kel-Tec P50 has a pretty long barrel, too, it may use ~6 tile range bonus.

Having no semblance of consistency in submachine gun stats. Having machine pistols be as good at long ranges as full-size SMGs. Having SMGs with 2/3-8/9 of assault rifle range.

### Additional context
None

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Balance "Adjusts ranges of SMGs and pistol caliber carbines"

#### Purpose of change

Closes #66947. Fixes a factual inaccuracy in description. Continues what was started in #66999.

#### Describe the solution

Adjusts ranges of pistol caliber carbines and SMGs according to this small arbitrary chart (hard to determine actual range of gun when every system to determine it gives different result, #66947 has an example of that, but at the same time, SMGs should not be that close to ARs in terms of range, and I am much more content with them being closer to pistols than ARs). Resulting bonus ranges are much smaller in most cases than ones given initially.
image

Pistols may be given another pass for guns like Broomhandles, which are renowned for their range and accuracy for pistols. I recommend having all other pistols having +0 ranges, as Browning action is not renowned for its accuracy (tilting barrel and stuff).

#### Describe alternatives you've considered

Have some guns with bonus ranges, some without.

#### Testing

None for now.

#### Additional context

None for now.

### CODE REVIEW

**Comment by randomtyper** [comment]
On the other note, Calico deserves better than 6 durability (as bad as a pipe rifle, despite being a factory made gun!) and 280 dispersion (worse than MP5s that have much shorter barrels and same roller-delayed action). Will make a PR about that, likely.

**Comment by randomtyper** [comment]
Will update the range bonus of Pennsylvania long rifle, while at it. Much shorter Baker rifle was capable of reliable hits at 200 m range, while muskets were extremely unreliable at half that range.

**Comment by randomtyper** [comment]
Hi-Point 3895 range was pretty damn nutty, 30 total range on .380 ACP round, which is, in game terms, same range as on a 7.62x39 round... 

The only "pistol" rounds that seem to deserve seriously increased range are .44 and .500 Magnum fired out of long rifles (Big Horn), but those did not have increased ranges AT ALL.

**Comment by randomtyper** [comment]
20 bonus range on H&K USC for total range of 36 tiles, matching .223 rounds fired from full-sized AR-15 platform guns... I am not even surprised.

**Comment by TheShadowFerret** [comment]
Can range bonuses be scaled with barrel length automatically, like how bullet damage is(for calibers that have been updated, that is) 👀

**Comment by randomtyper** [comment]
> Can range bonuses be scaled with barrel length automatically, like how bullet damage is(for calibers that have been updated, that is), so shortening barrels is factored in? 👀

I will look into that...

**Comment by randomtyper** [comment]
> Can range bonuses be scaled with barrel length automatically, like how bullet damage is(for calibers that have been updated, that is), so shortening barrels is factored in? 👀

From first look, the answer seems to be "nay".

**Comment by Maleclypse** [comment]
So is this ready to merge or needs more discussion?

**Comment by randomtyper** [comment]
> So is this ready to merge or needs more discussion?

Ready to merge as I envision the rebalance, it is still better than it was IMO. But there is still a room for improvement, as reworked rounds (5.56, for example) only seem to change the damage with barrel length, while IRL barrel length affects dispersion and length, too. Of course, these changes could be applied through receivers/upper assembles of the guns, but it would be nice if those differences were centralised around the barrel length and upper assembles would only adjust base stats for their length.

**Pull request merged**
