### PR TITLE
Tank Mod Series 2

### PR DESCRIPTION
**Pull request by chaosvolt**
This is of course the next part of the mod, divided due to PR bloat.

This adds basically everything except the mapgen hax.

Differences from the original pre-split version:
1. 105mm cannon has been removed entirely, replaced with 120mm cannon.
2. Remote Weapon System has been upgraded from 105mm to 120mm.
3. Diesel turbine engine and supercharged electric engine have been
removed, replaced by an equivalent amount of mundane, pre-existing
engines. Series 1 already did this for the tank trio.
4. Interior of armored fighting vehicles have been de-armored to be
consistent with vanilla APCs. Series 1 already did this for the tank
trio.

Vehicle (Re)Additions:
1. The Self-Propelled Howitzer. Still vaguely M109-ish, still 155mm. Has
gained the interior armor nerf that the other tanks got, though. And it
seems to run at acceptable speeds with only a mere V8 engine.
2. Mobile Gun System. Unlike the Stryker variant it vaguely resembles
(er, if you're drunk enough maybe), it now gets a 120mm RWS instead of
the 105mm it initially had. Also got the interior armor nerf.
3. Technical truck. No changes, but will be solely dependent on road
spawns, as without the mapgen changes it won't appear in bandit
strongholds.
4. Bandit Bulldozer. Again, no changes but will be rarer due to lack of
mapgen changes.
5. Plain civilian tractors. Very rare at present due to being an
uncommon road/highway spawn (few would be redneck enough to bug out on a
tractor, after all).

Additions that will only be relevant in Series 3:
1. Bandit vehicle group. Cheeki breeki? Nyet, get out of here Stalker.
Won't be used without mapgen changes.
2. Forklift. Does not show up on roads, and thus hinges on mapgen tweaks
to exist.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Thank you for the merge. ^^

**Comment by DavidKeaton** [comment]
niccceee, gonna add this to default mod list,

**Comment by chaosvolt** [comment]
Ah, have fun. Mapgen hax will eventually be in Series 3.

**Comment by DavidKeaton** [comment]
I've been really enjoying your stuff, keep up the good work!

**Comment by chaosvolt** [comment]
And thank you. ^^

**Pull request merged**
