### PR TITLE
Fix mac tests running as raw binary.

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
None

#### Purpose of change
Mac builds have been having a bad time. App builds were fixed but the raw cli builds would fail to run because of missing rpath entries to the framework'd sdl libraries.

#### Describe the solution
Add the rpath entries per https://stackoverflow.com/questions/77829286/no-lc-rpaths-found

#### Testing
Mac tests on this PR should completely pass, not just build. Hopefully github runners won't have the same inane security popups that my laptop had.

### CODE REVIEW

**Comment by akrieger** [comment]
More reading at https://stackoverflow.com/questions/66268814/dyld-library-not-loaded-how-to-correctly-tell-gcc-compiler-where-to-find/66284977#66284977 I guess.

**Comment by akrieger** [comment]
I need to make sure this doesn't break the mac app build in some way, so please don't merge this until I say so. I have to keep it as not-draft so the mac ci runs.

**Comment by akrieger** [comment]
Downloaded the tiles build from https://github.com/akrieger/Cataclysm-DDA/releases/tag/cdda-experimental-2024-11-30-2132, it ran whether I had the sdl frameworks installed in the same path or not. Seems okay.

**Comment by kevingranade** [comment]
Needs a rebase, but maybe do so after #78272 so it can avoid a whole-project clang-tidy.

**Comment by akrieger** [comment]
```
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```

welp.

**Pull request merged**
