### PR TITLE
max stamina modifiers from mutations now  affect stamina regen

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
```SUMMARY: Bugfixes "Max stamina modifiers from mutations now affect stamina regen"```

#### Purpose of change
To normalize the time needed to recover stamina to 500 turns regardless of maximum stamina, and make certain traits make more sense in terms of time to recover stamina. Previously, languorous only needed 375 turns to recover all max stamina, and indefatigable required 625. Realistically, it makes no sense for an "unfit" person to recover faster than a "fit" person.

This also affects walking stamina regeneration, where indefatigable would gain 10 stamina instead of 5, and languorous would be at 0 net stamina from walking. The numbers for walking emulate fit/unfit stamina more realistically this way. Sprinting and crouching are barely affected.

#### Describe the solution
Apply max_stamina_modifier to stamina_multiplier for regen purposes. Movement costs remain untouched.

Stamina regen are as follows:
no mutation: 20 (net 5 stamina gain when walking)
Languorous: 15 (net 0 stamina loss when walking)
indefatigable: 25 (net 10 stamina gain when walking)

#### Testing
Enable debug mode to see stamina consumption
Check stamina regen and consumption across no mutations, languorous, and indefatigable.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I like this, since having no available ways for players to be able to make a "fit" character in chargen with higher stamina regen has been in peoples wishlist for a while and this is a sensible way to do it.

If this change happens i'd seriously consider making these two four point traits, because they will have notably more effect. languorous in particular becomes really nasty with its net stamina drain while walking, even if carrying a light load with no mouth encumbrance, and indefatigable probably becoming the single best trait for melee characters.

**Comment by anothersimulacrum** [comment]
I think this is the wrong solution. To fix the problem stated in purpose of change, the time spent should be multiplied by the modifier, not the stamina regen.

**Comment by CodeBandit** [comment]
> If this change happens i'd seriously consider making these two four point traits, because they will have notably more effect. languorous in particular becomes really nasty with its net stamina drain while walking, even if carrying a light load with no mouth encumbrance, and indefatigable probably becoming the single best trait for melee characters.

I agree langourous would be especially annoying in very long on-foot travel, but taking even half an hour of game time in manual steps game turns would be a long endeavor. Indefatigable becoming the single best trait for melee characters because of a slight enhancement to stamina regen is a bit of an exaggeration imo. Melee costs will far overtake the extra stamina regen that, by the time you run out of stamina, you may have only recovered enough stamina for about 5 more attacks. For movement, fleet-foot is far superior as a 2 pointer

> I think this is the wrong solution. To fix the problem stated in purpose of change, the time spent should be multiplied by the modifier, not the stamina regen.

I'm curious as to how you would even multiply time spent when each turn is 1s (the smallest unit of time in CDDA)? Stamina regen is on a per-turn basis.

**Comment by anothersimulacrum** [comment]
Oh, sorry, I misread the post. I thought you were saying it took 500 turns always, even when you may have only needed 375 or may have needed 625.

**Comment by Brian-Otten** [comment]
I went ingame to double check and you were right, i somehow thought stamina costs for melee weapons were lower, but my 8/8/8/8 0 skill survivor needed 140 stamina for his 100 movecost hockey stick, so the indefatigable trait would have gained him 1 "free" hit every 28 hits.

Calculated as amount of hits till 0 stamina, it's 71 hits versus 93, which is a 30% increase.

I think that might be enough to go from 2 points to 3 points but it's a bit of an edge case.

**Comment by CodeBandit** [comment]
> I went ingame to double check and you were right, i somehow thought stamina costs for melee weapons were lower, but my 8/8/8/8 0 skill survivor needed 140 stamina for his 100 movecost hockey stick, so the indefatigable trait would have gained him 1 "free" hit every 28 hits.
> 
> Calculated as amount of hits till 0 stamina, it's 71 hits versus 93, which is a 30% increase.
> 
> I think that might be enough to go from 2 points to 3 points but it's a bit of an edge case.

If the stamina cost was 140, it would be 135 with indefatigable (applying the +5 stamina to it). That would make 10k/140 = 71 hits for without the trait and 10k/135 = 74 hits for with the trait. With your "1free" hit every 28 hits, it's about the same outcome 71 + 71/28 = 73.53.

**Comment by kevingranade** [comment]
Negative net stamina regain when walking doesn't really work, walking is roughly defined as, "an indefinitely maintainable pace", and the system is tuned to make that happen.
Other than that I like this change and am inclined to apply it once we can sort out the walk thing.

**Comment by CodeBandit** [comment]
@kevingranade 
> Negative net stamina regain when walking doesn't really work, walking is roughly defined as, "an indefinitely maintainable pace", and the system is tuned to make that happen.
> Other than that I like this change and am inclined to apply it once we can sort out the walk thing.

Maintaining an indefinitely maintainable pace for walking (without mouth encumbrance) and also keeping the 500 steps is technically already true as the game is already coded. PLAYER_BASE_STAMINA_BURN_RATE. The numbers shown above were what I got through testing with starting survivor gear (which includes a slight mouth encumbrance). The real numbers without mouth encumbrance/max stamina are:
Langurous: +0 net
normal: +5 net
Indefatigable: +10 net

**Comment by Siersha** [comment]
I'm definitely looking forward to this. It would make Indefatigable slightly more impactful while strolling away from those zombies in style. Another thing to take into consideration math-wise is that 2 steps of Regen with indefatigable would now be equivalent to waiting in spot for 1 turn. (10 stamina gained vs 20 stamina).

This would additionally give a leeway of 25 mouth encumbrance (-5 stamina Regen). It's not like the survivor should have a mask on at all times though. With this, having one on wouldn't be pretty comfortable.

**Comment by CodeBandit** [comment]
Will Re-PR due to rebase (Is there a less verbose way to do this?)

**Comment by anothersimulacrum** [comment]
Yeah, it looks like you rebased incorrectly somehow. I've been continually rebasing #38912 (roughly every force-push is that), and the commit history is still intact.

**Comment by CodeBandit** [comment]
Likely because I'm just pushing the changes from the rebase of upstream/master, not force-pushing. I will keep that in mind for the future, thanks!

**Pull request closed without merging**
