### PR TITLE
Remove Feral Archaelogist

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
None

#### Purpose of change

Feral archaeologists were originally added as part of an archaeological dig for a mine, and was also added in as a reference to indiana jones. I do plan on removing the dig sites for them, but I am saving that for another PR as I want to make this PR focus entirely on the feral, as there has been controversy around it before. 

A. Archaeologists are not that common. From the Bureau of Labour Statistics, the number is placed at 7 720. https://www.bls.gov/oes/current/oes193091.htm. This would make archaeologists astronomically rare to find in CDDA, to the point of them being essentially non-existent. 

B. The job of archaeologist wouldn't make a feral any different from a regular one. They're not like feral mechanics where they have a set specific type of clothes and tools to use as weapons, and so they'd more or less be equivalent to a regular feral. In fact, the only difference is that they wield a shovel and have somewhat different drops. To me this feels like way too specific of a feral, akin to having a "civil engineer" feral, or an "office worker" feral. 

C. The mine finale of a digsite doesn't make much sense, and was the main justification for having these specific ferals. It's a dig site buried below many meters of rock, uses dynamite (very bad in a digsite where you try to preserve artifacts), and presumes to have regular mining operations despite the fact it's clearly a very very old and therefore an extraordinarily important digsite. They also don't appear to spawn there anymore, instead chilling at the top of mines. 

EDIT: It was suggested I include the original PR suggesting removal of them. #67707. The main argument for removal was that a feral could not sustain itself at the bottom of a mine, that it was very obscure, and that it was an indiana jones reference. The current solution was to have it spawn in the office of the mine, and to reduce the chance of spawning with a bullwhip. I don't think this is a sufficient reason, as it doesn't solve the problem of archaeologists being an extremely rare profession, or why it could not be a regular feral. There is a fair amount to read and parse in that PR, so apologies if something was misconstrued, misunderstood, or missed. 
 

#### Describe the solution

Removes them.

#### Describe alternatives you've considered

N/A

EDIT: Turning the above ground feral archaeologist into a regular feral.  

#### Testing
Spawned a bunch in, loaded in after the change, working as intended
image

### CODE REVIEW

**Comment by RenechCDDA** [comment]
This was previously suggested for removal in #67707 and the consensus was apparently to keep it

**Comment by Holli-Git** [comment]
> This was previously suggested for removal in #67707 and the consensus was apparently to keep it

Exactly why I made this PR. I think the justifications for the consensus are incorrect, and that they should've been removed in the first place.

**Comment by Night-Pryanik** [comment]
Move it to No Hope instead of removing.

**Comment by RenechCDDA** [comment]
> > This was previously suggested for removal in #67707 and the consensus was apparently to keep it
> 
> Exactly why I made this PR. I think the justifications for the consensus are incorrect, and that they should've been removed in the first place.

If the justifications for removing it have already been shot down once, it **really** behooves you to mention that before starting on another justification. Cause you're justifying against the previous argument, right? Not just sweeping it under the rug and hoping nobody raises a winning objection this time?

You understand why it would be unfair not to mention it, I hope.

**Comment by Holli-Git** [comment]
> You understand why it would be unfair not to mention it, I hope.

That is true, Admittedly, I was unsure how exactly to phrase it, but I'll add it into my PR in a moment.

**Comment by kevingranade** [comment]
What does it add to have a labeled archaologist? Nothing,  they're no different from any other feral, so they have no reason to exist.

If you want them in no hope you can add them there.

**Pull request merged**
