### PR TITLE
Deleted contents of testing.json

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
They weren't being used, and they took up space.

The file itself has been retained as a storage area for future test items.

### CODE REVIEW

**Comment by mugling** [comment]
There isn't much value in retaining an entirely empty file

**Comment by BorkBorkGoesTheCode** [comment]
From Coolthulhu #18729:

>we'd need to make another when adding new features that need a test item.

So I kept the file for future use.

**Comment by mugling** [comment]
Why do we need to version control an empty file?

**Comment by BorkBorkGoesTheCode** [comment]
#18741

**Pull request closed without merging**
