### PR TITLE
Add a book-specific recipe name and optionally hide the recipe in book descriptions

### PR DESCRIPTION
**Pull request by BevapDin**
The entry in the recipes can now contain a name for the recipe that appears in the book description instead of the of the resulting item.

This came up before and now again in https://github.com/CleverRaven/Cataclysm-DDA/pull/11620#issuecomment-82751284. And I agree, books like a cookbook clearly state what the resulting item is supposed to be. But books like college book that explain the basics of how a motor works do not contain the actual recipe, they only allows the reader to figure it out based on the information in it. And books like the lab journals might not even state what the result is, they just contain a list of instructions that result in "something".

Example:

``` JSON
"book_learn": [
    [ "textbook_chem", 4 ],
    [ "textbook_anarch", 7, "Stuff THE MAN doesn't want you to know" ],
    [ "textbook_gaswarfare", 8, "" ]
],
```
- The recipe will appear as usual in textbook_chem (with the name of the resulting item). This is the default and used for all existing recipes.
- It will appear as "Stuff THE MAN doesn't want you to know" in the textbook_anarch (not mentioning the resulting item).
- It will not appear in the textbook_gaswarfare, but an additional message "It might help you figuring out some more recipes." will appear to indicate reading it might still be useful.

This is a cosmetic change only, the behave is not affected at all.

---

The examples added in `data/json/recipes/recipe_ammo.json` are completely arbitrary and can be adjusted / removed as you seem fit. They only serve as examples. Without changes to the json, nothing will change in the game.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by Snaaty** [comment]
So whenever there is a book with a hidden recipe it shows the sentence "I might help you figuring out some recipes."?
Does that message disappear once I have learned all hidden recipes from one book?
Real neat changes.

**Comment by BevapDin** [comment]
> So whenever there is a book with a hidden recipe it shows the sentence "I might help you figuring out some recipes."?
> Does that message disappear once I have learned all hidden recipes from one book?

I changed it: if the recipe is known, it is assumed the player recognizes it in the book and handled as non-hidden. So if you known the recipe, it will show up. The message about further recipes will not show up when there are no unknown hidden recipes.

> EDIT, slightly OT: Perhaps how we could also make e.g. mechanic books not show any recipes and reduce the rate at which you're learning recipes and instead introduce single "blueprints" that you can use for doing specific stuff. Those could also be used as quest rewards and/or trading and in safes.

Sure, but that is a json only change and it affects the content, so I won't touch it. But I like the idea of blueprints: small books each containing one recipe, randomly found in garages or hardware stores and more often in labs.

**Comment by KA101** [comment]
OK, if you want me to manually fix each and every one, that's gonna need time I don't have at the moment.

**Comment by Rivet-the-Zombie** [comment]
>But I like the idea of blueprints: small books each containing one recipe, randomly found in garages or hardware stores and more often in labs.

I really like this idea.

**Comment by kevingranade** [comment]
For now we can add the feature (which sounds good to me, and assuming it
works of course), and open issues for updating books to use it and for the
blueprints idea.

**Comment by Snaaty** [comment]
Yeah, I think we shouldn't badger BevapDin into doing this in this PR.

**Comment by KA101** [comment]
Hadn't intended to badger BevapDin.  Statement of my schedule and time available.

**Pull request merged**
