### PR TITLE
JSON linting for RELEASE builds

### LINKED ISSUE #17902: JSON linted whitelist
@narc0tiq do you have (or could it be provided) a copy of the perl5 JSON module for the buildbot? I'd like to start linting some JSON files and prevent regressions via a similar system to the current astyle whitelist. The lint tools sole dependency is p5-JSON module.

### PR DESCRIPTION
**Pull request by mugling**
Closes #17902
- Enables linting of files contained in `json_whitelist` for `RELEASE` builds
- If `perl` or the `p5-JSON` module are unavailable the build continues without linting
- Reasonably performant and caches the success of `json-lint` target as `obj/lint.cache`

The `AMMO` definitions are converted via `cleanup.sh` which uses the linter which is itself backed by the previously committed unit tests. Linting consumes only a few seconds at the start of a build.

@narc0tiq `json_format_check.sh` is now defunct but the replacement `lint.sh` along with the linter itself (`format.pl`) need similar protections (not building PR's which change them)

### CODE REVIEW

**Comment by mugling** [comment]
Shell globs are supported in `json_whitelist`. 581b888 uses this to ensure that all new files added to the `ammo` subdir pass the lint check.

**Comment by Coolthulhu** [comment]
`whereis -qb` doesn't work here. `whereis --help` doesn't list a `-q` option.

**Comment by mugling** [comment]
That might be a FreeBSD idiom. Let me take a look

**Comment by mugling** [comment]
Replaced with call to `which`

**Pull request merged**
