### PR TITLE
Migrate the butchery menu to use uilist

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
```SUMMARY: Interface "Migrate the butchery menu to use uilist"```

#### Purpose of change
Migrates the butchery menu to use uilist. Also generates the menu entries using format strings instead of `stringstream`.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Slightly off topic, but still around it: do you also plan on migrating limb choice menu (this one with limb health bars when using bandages)?

**Comment by Qrox** [comment]
That one does not seem to be using uimenu. Do you want me to refactor it to use uilist or do you mean something else?

**Comment by nexusmrsep** [comment]
Yes, I was asking if you had any plans on refactoring it to uilist? By looking at it I think it would benefit from refactoring as uilist is much more elastic. If you don't plan of doing it, I might try eventually.

**Comment by Qrox** [comment]
Not before you mentioned it, but since you asked I'll have a look.

**Pull request merged**
