### PR TITLE
Make format.pl process many files at once.

### PR DESCRIPTION
**Pull request by mutability**
This is much faster than spinning up a new perl for each file.

### CODE REVIEW

**Comment by mugling** [comment]
> This is much faster

How much faster? Should be easy to benchmark?

**Comment by mugling** [comment]
the classical complexity vs performance argument

**Comment by mutability** [comment]
I didn't benchmark it, but I no longer sit around for a minute waiting for the json lint to finish as the final step in a -j8 build, put it that way.

There's minimal complexity change really, most of the diff is indentation changes where I pulled the guts of the processing into a sub.

**Comment by mugling** [comment]
I'll take a look. It should only take a minute on the first build though due to `lint.cache`?

Tangent: If you want to hack on `Makefile`, linting or other tooling (for which you appear to have the required skillset) such work would be most welcomed

**Comment by mutability** [comment]
I tend to switch branches a lot, so lots of clean builds.

**Comment by mugling** [comment]
You no doubt get the same problem then that `make lint` and `make lint-check` differ (the latter doesn't enforce sort order)

**Comment by mutability** [comment]
old:
```
$ time make lint-check
mkdir -p obj
Linting data/json/bionics.json
[...]
Linting data/mods/PKs_Rebalance/monsters/fungus.json

real	1m27.542s
user	1m24.892s
sys	0m1.496s
```

(Aggravated by it being a single target, so make can't parallelize it)

new:
```
$ time make lint-check
mkdir -p obj
Linting 455 json files

real	0m11.128s
user	0m11.044s
sys	0m0.028s
```

**Comment by mugling** [comment]
`perl` is very slow to start. @narc0tiq any objection to doing a `mod_perl` variant of the web linter?

**Comment by mugling** [comment]
Much faster but some problematic regressions. In particular `make lint-check` no-longer tells you which file an error is found in (for example for unmatched contexts)

**Pull request closed without merging**
