### PR TITLE
Reduced price of emergency blankets.

### PR DESCRIPTION
**Pull request by Petethegoat**
For some reason they were worth $425.
Reduced this to a more reasonable $4.25.

### CODE REVIEW

**Comment by karlnp** [comment]
Man, I can't even get a disposable rain poncho for $4.25. Why not move it one place instead of two and we have $42.50? they are foldable, after all. pretty convenient

**Comment by Petethegoat** [comment]
I figure they've been handed out widely by the government when evacuation started.
Obviously the price can be whatever, but in the context of spawning in a shelter with an NPC, getting 40 bucks for it still seems like a lot to me.

**Comment by karlnp** [comment]
According To The Lore they were only ever sparsely stocked and meant to be a distraction. Disaster preparedness theatre. But the lore page on the wiki is hilariously incomplete, so who knows.

**Comment by karlnp** [comment]
$4.25 it is.

**Pull request merged**
