### PR TITLE
Ledges provide sight coverage

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Features "Ledges provide sight coverage"

#### Purpose of change
Creatures ignore walls on their z-level when spotting characters on the z-level above.  A zombie staring at a wall should not be able to see a character on the roof at the opposite end.

#### Describe the solution
ledge
Introduce overly complex calculations to simulate how much of a character is obscured by a ledge when viewed by a creature below.  It takes into account the height of the ledge, distances of both creatures from the ledge, creature sizes of both viewer and target, and any furniture they are standing on.  The angle of the viewer's eye height to the ledge is extrapolated to the distance of the target to determine how much height the ledge covers at that point.

Part of the existing coverage system has been refactored to allow both ledge coverage and crouch/furniture coverage to interact nicely with each other.  Crouching and lying prone allows a character to remain hidden when ledge coverage is insufficient to cover their full body height.  Ledge and furniture coverage do not stack and only the highest of both is used.

#### Testing
Builds successfully.
New character created in the "Surrounded" scenario.
Teleported character to a rooftop.
Creatures on z-level below that are too close to the wall are unable to see the character, while those further away can.
Moving closer to the ledge make the character visible to more creatures.
Crouching and lying prone makes the character visible to less creatures.
No detectable increase in draw times.

### CODE REVIEW

**Comment by Nebnis** [comment]
Next level update, thank you Rewryte for all the amazing QOL you been putting out for the game.

**Comment by ashGlaw** [comment]
Gree! This is clutch. Way to go!

**Comment by andrei8l** [comment]
Since our cover system is all-or-nothing wrt vision, this needs to be reciprocal. Meaning that I should not be able to see this zombie if it can't see me.
Screenshot from 2023-08-04 20-05-40
This should properly be solved from shadow casting code, but no one has been able to improve that in years and this solution works so whatevs 🤷.

**Comment by Rewryte** [comment]
> Since our cover system is all-or-nothing wrt vision, this needs to be reciprocal. Meaning that I should not be able to see this zombie if it can't see me.

Fair enough.  I always had a mind to update the light / shadow system to work better with 3D vision, but ended up deferring the task.  Just making ends of the code is an undertaking on its own.  I'm working on something else at the moment but I'll have another go then I'm done.

**Comment by kevingranade** [comment]
The shadowcasting test needs to be updated to mesh with this.
Thanks a ton for this,  the way this works has really bugged me for a long time but I haven't been able to get around to it.

**Comment by Rewryte** [comment]
> The shadowcasting test needs to be updated to mesh with this.

Sure, will get to this soon.  Currently looking into #66040 which is hampering the new lightmap changes.

**Comment by Rewryte** [comment]
This is fully functioning now.  However, there is a noticeable performance impact on elevated areas such as open rooftops as ledge coverage is calculated for each grid in the area below.  Looking into ways in which performance can be improved.

**Comment by Rewryte** [comment]
Seems to be some discrepancy in visibility between creatures looking up a ledge, and the player lightmap when looking down at the same creature.  Looking into this.

**Comment by Rewryte** [comment]
Should be good to go.  Shadowcasting might sporadically stop working for tiles 2 or more z-levels below the player but such is the behavior prior to this PR.  Have yet to ascertain the cause.  The same area also seems to have its own ledge shadowcasting unrelated to mine.  This behavior will be effectively obscured by the seen_cache post-processing introduced in this PR.

**Pull request merged**
