### PR TITLE
Adjusted battery charge desc & reload time. Adjusted med cell plural text.

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Bugfixes "Adjusted battery charge desc & reload time. Adjusted med cell plural text."

#### Purpose of change
The legacy 'batteries' item description was insufficient in explaining to players how it is to be utilized in the new battery magazine world. Reload time was also the default 100 moves per charge, making reloading cells take excessively long.

Medium Battery Cells had an incorrect plural name, causing them to masquerade as light battery cells.

#### Describe the solution
Adjusted description, reload time, and plural name as appropriate.

Battery charge reload time is now 1 move per cell. So 1 turn per 100 charge.

#### Additional context
I've been bereft of screenshots lately. I must do something.
image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Plural name is excessive here, as `s` is automatically added to the end of `name` if no `plural_name` is set.

**Comment by esotericist** [comment]
> Plural name is excessive here, as `s` is automatically added to the end of `name` if no `plural_name` is set.

Good point. I suspect the plural name is an artifact of the fact `battery` needed it for its affix. Do you want me to strip them?

**Comment by Night-Pryanik** [comment]
> Do you want me to strip them?

Yeah, we stripped redundant fields from jsons earlier.

**Comment by esotericist** [comment]
> > Do you want me to strip them?
> 
> Yeah, we stripped redundant fields from jsons earlier.

Done. Some of them were still meaningful (due to the ordering of terms), so I left those

**Comment by jbytheway** [comment]
Perhaps the item type loading code should check for redundant plurals and log an error?

**Pull request merged**
