### PR TITLE
Extracts and Concentrates pt 6 (recipes)

### PR DESCRIPTION
**Pull request by NastyNate2612**
all the crafting recipes and deconstruction recipe for the vac oven

#### Summary
SUMMARY: Content "6th installment of my extracts and concentrates mod into mainline. All the crafting recipes and deconstruction recipe for vac oven"

#### Testing
Tested all crafting recipes

### CODE REVIEW

**Comment by NastyNate2612** [comment]
im gonna make a Low quality distllate comestible to utilize the different DISTILL and FINE_DISTILL qualities as well

**Comment by kevingranade** [comment]
Looks like you changed the extraction textbook ID, but didn't update it in these recipes, also "reversible": false is an invalid flag in a recipe.

**Comment by NastyNate2612** [comment]
ahhh you're right i missed a couple on the texbook id change, my bad. Ill fix em.

**Comment by NastyNate2612** [comment]
Thanks again Kevin. Ill get all the items put into item groups tomorrow during lunch and make another PR for it

**Pull request merged**
