### PR TITLE
I Dream Of Macedonia

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "Addition of the Hub-02 Faction"

#### Purpose of change
Heavily WIP addition of a new faction from the faction sheet.

This is getting shelved for this cycle so it's mostly here to remind me it exists in 4+ months.

I'm not trying to sneak this under the freeze or something dumb

#### Describe the solution
This initial pass will at least implement

- A new Faction with an NPC you can interact with and trade with
- The Factions home base
- A non Refugee Center breadcrumb to start the quests
- At least one new mission
- A new Robot companion/deploy-able
- A (probably) non-accessible end game dungeon for later quests

#### Describe alternatives you've considered
Letting someone else do this

Waiting until someone else get the framework in place

#### Testing
HEAVY WIP

#### Additional context
I'll add more details as it gets closer to release.

Currently I have some notes that are WIP and based on stuff from the devcord that probably doesn't need to be plastered here yet

### CODE REVIEW

**Comment by Maleclypse** [comment]
This all content driven really, right? Maybe a little bit of c++ here and there but not super feature heavy right? If so it doesn’t have to be shelved until we hit content freeze.

**Comment by I-am-Erk** [comment]
Just trying to get me to test out the new project freeze label, eh?

**Comment by bombasticSlacks** [comment]
I'm planning to write some stuff that will require some C++ but it would be quite sequestered... alright well this isn't off the table then. I'll see where it can get to and if I can get it in for content freeze!

**Comment by I-am-Erk** [comment]
This is on project freeze and shouldn't have been closed, but I don't know how to make stalebot ignore project freeze labels

**Comment by bombasticSlacks** [comment]
I mean I can keep it from closing but at this point I'm working on other stuff and if someone else had ideas and wanted to work on it I wouldn't want to discourage them. I will otherwise try to pick this up for .H

**Comment by I-am-Erk** [comment]
That was the plan anyway, I am just talking to stalebot there. It never listens to me though

**Comment by bombasticSlacks** [comment]
Not realistically going to be completed

**Pull request closed without merging**
