### PR TITLE
UGV's → UGVs, UPS's → UPSes

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
None

#### Purpose of change
Fix a possible grammar error and keep style unified.

#### Describe the solution
Change UGV's (possessive) to UGVs (plural), same with one instance of UPS's and UPSes (it was changed elsewhere).

#### Describe alternatives you've considered
Keep them as is, but it seems it was changed to a form without it elsewhere.

#### Testing
Simple text changes, can be seen e.g. in debug.

#### Additional context
Fixes 1 Transifex issue.

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by I-am-Erk** [comment]
This is incorrect. Apostrophes are used to pluralize acronyms.

**Comment by Faalagorn** [comment]
> This is incorrect. Apostrophes are used to pluralize acronyms.
> 
> Edit: apparently it depends on which style guide you're going with, but until we've chosen one specifically I don't think it's something that changes should be PR'd for

I used this as a guide: https://www.thepunctuationguide.com/apostrophe.html, and while indeed it mention the rare case you mention, I'm not sure it's the case for UVG here?

**Comment by Faalagorn** [comment]
@I-am-Erk just realized that even the PR template uses the s without apostrophe form for the plural, it actually uses them both, first referencing to the PR in question (PR's) in https://github.com/CleverRaven/Cataclysm-DDA/blob/e802591efca741a4f910ea8585a42327b18b3021/.github/pull_request_template.md?plain=1#L5 then few lines lower, the plural PRs: https://github.com/CleverRaven/Cataclysm-DDA/blob/e802591efca741a4f910ea8585a42327b18b3021/.github/pull_request_template.md?plain=1#L8

CBMs and UPSes mostly use that form too :thinking: Either way, it'd be best for something to be agreed on and put in the manual of style for consistency I guess?

**Comment by Faalagorn** [comment]
Following the discussion with @I-am-Erk in Discord assuming it's worth picking one style and keeping it as such, I changed remaining instance of "UPS's" (obsolete, but still).

**Pull request merged**
