### PR TITLE
Add more world options to modify enemies

### PR DESCRIPTION
**Pull request by Salty-Panda**
#### Summary
Features "Add more world options to modify enemies"

#### Purpose of change

Closes: #48677

#### Describe the solution

Added more options:

- Vision affects day and night vision.
- Attack affects melee bash attack dice sides, added cut damage (not directly), values in melee_damage array.
- Armor affects all values accessible from that part of code: bash, cut, bullet, acid, fire, stab. ( Are monsters defenseless against lighting and biological? )
- Special attack chance I failed to get to work properly,

image
I couldn't find any `const` in its code, but it's somehow declared read-only, not sure how to edit it during loading from json.

#### Testing

New world, 1% attack, 1000% armor, 10% vision.
Skeletal juggernaut saw me from ~5 tiles, was unable to "pierce armor" of fresh char in normal clothes.
Char with all skills 10 was unable to damage skelly with neither battleaxe nor .50 gun.

### CODE REVIEW

**Comment by actual-nh** [comment]
Can you modify special attack cooldowns instead?

**Comment by Salty-Panda** [comment]
Not sure what you mean?
As I wrote, it doesn't seem to be modifiable

**Comment by actual-nh** [comment]
> Not sure what you mean?
> As I wrote, it doesn't seem to be modifiable

Are you talking about trying to modify the percentage chance that a special attack succeeds? I'm wondering about the potential of adjusting how often monsters can do various special attacks (cooldowns).

**Comment by kevingranade** [comment]
Please move these to an external option, you can exercise these with a micro-mod, but I don't want more tuneables on the option screen. If anything I'd prefer to move some of the existing ones.

**Comment by Salty-Panda** [comment]
@kevingranade 
Would it be alright to make an external option EDIT_ENEMIES true/false, set it to false in the mainline and add mod that sets it to true.
Then in world options check for EDIT_ENEMIES == true before displaying those parameters?
So can you only edit them if you added that mod?

**Comment by Salty-Panda** [comment]
I tried that and it didn't work.
External options are loaded on game start and I can't overwrite them on the fly during world creation.

The only solution I can think of is to leave those options as is, so the player can edit them both from main menu and during world creation, but they only take effect if the mod is added. I would put note about the requirement in the options description.

**Comment by kevingranade** [comment]
Like I said, I don't want more turntables in the options menu, so having them present but not functional doesn't help at all.

**Comment by Salty-Panda** [comment]
By Kevin too:
> Really I want to prune all the monster adjustment options down to a single "make monsters weaker/stronger" knob that we actually curate instead of just exposing a bunch of individual settings

**Comment by actual-nh** [comment]
> Really I want to prune all the monster adjustment options down to a single "make monsters weaker/stronger" knob that
> we actually curate instead of just exposing a bunch of individual settings

Said individual settings being available can be useful in figuring out how to best get the desired results from that knob. There is also the question of to what degree do you have to use a particular playing style, overall strategy, or whatever to succeed - see <http://nethack4.org/blog/strategy-headroom.html> for a good discussion of this; different players will have different preferences in strategy headroom, and it's nice if adjustments allow for making a game better fit the player's preference.

**Comment by Salty-Panda** [comment]
Yup.
Armor scaling is worthless against mage characters since magic ignores conventional armor values
Speed and vision is strong against players who prefer to fight at the distance
Attack scaling is more punishing to melee players

**Comment by I-am-Erk** [comment]
Closing this as stale for now, but feel free to reopen if you are active again.

**Pull request closed without merging**
