### PR TITLE
Standard House Palette Tweaks

### PR DESCRIPTION
**Pull request by LilShiningMan**
#### Summary
```SUMMARY: Content "minor tweaks including item spawns for glass cabinet, fireplace terrain'"```

#### Purpose of change

Refining standard house palette. 

#### Describe the solution
6 different additions or tweaks: 
1 - added another symbol to list of unused palette symbols
2 - changed terrain that spawns under fireplace to concrete, as it currently spawns with whatever main terrain it is (typically wood or carpet)
3 - added my home_display_case item group to glass cabinet, though I see it's also been added to a couple other parts of the palette
4 - I find there are quite a few locked doors spawning in houses. I tweaked the numbers so it's a bit less frequent.
5 - In the basement palette, a few of the unique furniture spawns default to grass terrain for some strange reason. I've changed the default terrain spawn to concrete which makes a lot more sense.
6 -**EDIT** - pantry shelves retain their 25 chance to spawn SUS group, but I've also added a small chance for a few food items to spawn in addition. This won't drastically change the overall amount of food in the game, but it does simulate a situation where people's food stashes are running low. ( pantry shelves frequently spawn empty. I changed the chance for the SUS list from 25 to 40,) 

#### Testing
created a new test house and spawned the above problematic furniture pieces and everything works as planned.

### CODE REVIEW

**Comment by curstwist** [comment]
I'm ok with these changes.  I'm 50/50 on the pantry buff.  That delivers a lot of food when it does spawn, I'm not sure if increasing the chance is a good idea.  Many houses will have a few pantry spawns so this could result in a lot of shelf stable food.

**Comment by LilShiningMan** [comment]
I appreciate the comment and see what you mean from a game-play perspective, but from a lore-perspective there's a 2 week window from the general public thinking there's something going on, to riots in the streets, to the government sending in the military and finally the portals opening and presumably the majority of people becoming undead. That's a quick escalation from hoarding food and riots in the streets to an alien invasion.  

My other thoughts on how to handle the "where is the food?" question are to increase makeshift survivor bases in house spawns with 15-20 non perishable items or to have map extras in cities of failed survivor/looter food raids. 

These are just my thoughts. I can eliminate the pantry bump from this PR and think about adding the above in the future.

**Comment by curstwist** [comment]
Eventually I hope we either get support for weighted magpen palette selection (so you could have a palette that is well stocked and another looted one, etc).  Or, until mapgen "evolves" over time support is added.  Then we can do all sorts of stuff with environmental story telling.

**Comment by LilShiningMan** [comment]
Yeah, I am definitely all for the environmental storytelling. As it is, a lot of my upcoming houses have multiple variants, some of which just spawn versions of the house with more or less loot.

You have a point about the different palettes and "looted" and "regular" item spawns. My first couple house submission will have "tags" for adding linoleum terrain under bathroom or kitchen furniture that overlay the standard house palette in the same way the basement overlay currently does. It wouldn't be such a stretch to just have a palette with only the furniture and terrain defined and the item spawns defined in an overlaid "tag" palette, though without the benefit of having the weighted choice you're speaking of, it's less useful and still necessitates having multiple entries for the same house. 

And, of course, that would mean revamping what you've come up with already, and from experience, I know it's a pain to constantly be retrofitting work. I have a backlog of 30+ houses I'm slowly converting to the new palette.

**Comment by curstwist** [comment]
Are those houses in a mod?  I'm doing the same with Urban Development.  Check the open PR for the symbols I'm using if you want to synchronize them all.

**Comment by LilShiningMan** [comment]
I started making a mod and changed gears midway. Now I've repurposed all of my work and have been converting everything to standard palette. Most everything is salvageable and still useful (with some polish). I'm keep myself interested by mixing up the conversion houses with some new houses. I have about 8 houses ready to go for submission. 

I'm not sure what you mean by synchronizing my symbols with the UD houses, but if I can help let me know.

**Pull request merged**
