### PR TITLE
[CR] Test monster attack+sees with/without fov_3d

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
Infrastructure "Tests monster attack+sees with/without fov_3d"

#### Purpose of change

This is a followup on @wapcaplet's #48051, which it incorporates. It is meant as the basis for testing a version of @Jamuro-g's #47993, with the exceptions for stairs, ramps, etc removed.

#### Describe the solution

This adds:
- Checking both with and without fov_3d;
- Having potentially differing expected values for the attack and sees checks.

#### Testing

That is what it is doing. It is expected that the attack tests for without fov_3d will fail when not using #47993 (without exceptions for stairs, etc). Currently, unexpected failures are happening in the flat ground sees tests - the monster & player don't seem to be able to see each other from a very short distance away.

### CODE REVIEW

**Comment by actual-nh** [comment]
That is... weird. In the general build matrix GCC 7 with Tiles compile, the "sees" checks for the "flat ground" case are NOT failing, unlike what happened locally:
```
monster_attack
  attacking on open ground
-------------------------------------------------------------------------------
../tests/monster_attack_test.cpp:66
...............................................................................

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (67,67,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (67,66,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (67,65,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (67,64,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (67,63,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (66,67,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (66,63,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (65,67,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (65,63,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (64,67,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (64,63,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (63,67,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (63,66,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (63,65,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (63,64,0)
  fov_3d := false

../tests/monster_attack_test.cpp:35: FAILED:
  CHECK( you.sees( target_monster ) == expect_vision )
with expansion:
  false == true
with messages:
  attacker_location := (65,65,0)
  target_location := (63,63,0)
  fov_3d := false

Log messages during failed test:
12:00:00AM: You dodge the zombie.
12:00:00AM: You hit the zombie for 2 damage.
12:00:00AM: You dodge the zombie.
12:00:00AM: Your torso encumbrance throws you off-balance.
12:00:00AM: You miss.
12:00:00AM: The zombie misses you.
12:00:00AM: You hit the zombie for 4 damage.
12:00:00AM: The zombie hits your torso.
12:00:00AM: You hit the zombie for 4 damage.
12:00:00AM: The zombie hits your left leg.
12:00:00AM: You hit the zombie for 6 damage.
12:00:00AM: The zombie hits your left arm.
12:00:00AM: You hit the zombie for 6 damage.
12:00:00AM: Your <color_c_light_green>|| </color>army jacket is ripped!
12:00:00AM: The zombie hits your torso.
12:00:00AM: You miss.
12:00:00AM: The zombie hits your torso.
12:00:00AM: You hit the zombie for 5 damage.
0.037 s: attacking on open ground
0.268 s: monster_attack
```
Tiles vs Curses? (I really hope it isn't a test ordering effect...)

**Comment by actual-nh** [comment]
The travis build, with curses, also didn't have the flat ground failures. I am... rather puzzled by this one.

**Comment by actual-nh** [comment]
@jbytheway, @wapcaplet, @Jamuro-g: It's a test ordering effect. When one runs all the tests, only the expected two fail. When one runs just that test, unexpectedly the player can't see the monster... on level ground. Any ideas?

**Comment by jbytheway** [comment]
Maybe it's affected by time of day / weather?

To be clear, you're saying that running the `monster_attack` test in isolation is consistently exhibiting unexpected failures? Is that true on master, or just this PR branch?

**Comment by actual-nh** [comment]
> Maybe it's affected by time of day / weather?

Do tests run, unless specified otherwise, at the in-game time of day identical to the realtime one (what time zone?) or something? That would be... inconvenient.

> To be clear, you're saying that running the `monster_attack` test in isolation is consistently exhibiting unexpected failures? Is that true on master, or just this PR branch?

This PR branch. It is an extended version of the `monster_attack` test, with checking for whether the two opponents can actually see each other (the `sees` part being originally coded by wapcaplet - see #48051). In the part of the test in question, it is checking to see if the two opponents can see each other on flat ground, at a maximum of something like 4 tiles away. The monster can see the avatar... but whether the avatar can see the monster is variable (89749b9 vs the most recent results).

There are also 2 failures that are expected, given the issue (#42845).

**Comment by jbytheway** [comment]
> > Maybe it's affected by time of day / weather?
> 
> Do tests run, unless specified otherwise, at the in-game time of day identical to the realtime one (what time zone?) or something? That would be... inconvenient.

No, I mean the in-game time.  By default the time is midnight on day 1, but some tests change it and don't generally restore it.

**Comment by actual-nh** [comment]
> No, I mean the in-game time. By default the time is midnight on day 1, but some tests change it and don't generally restore it.

What's the recommended way to reset it after setting it? From your (_**very much appreciated**_) PR #48217, I am guessing that `restore_on_out_of_scope` would not work. (I am thinking of specifying noon, to make sure light levels are not the difficulty.)

**Comment by jbytheway** [comment]
> What's the recommended way to reset it after setting it? From your (_**very much appreciated**_) PR #48217, I am guessing that `restore_on_out_of_scope` would not work. (I am thinking of specifying noon, to make sure light levels are not the difficulty.)

`restore_on_out_of_scope` should work fine; it's not covered by that PR for unrelated technical reasons.

**Comment by actual-nh** [comment]
> > What's the recommended way to reset it after setting it? From your (_**very much appreciated**_) PR #48217, I am guessing that `restore_on_out_of_scope` would not work. (I am thinking of specifying noon, to make sure light levels are not the difficulty.)
> 
> `restore_on_out_of_scope` should work fine; it's not covered by that PR for unrelated technical reasons.

Excellent! (Technical reasons being with clang-tidy picking it up properly?)

**Comment by jbytheway** [comment]
> Excellent! (Technical reasons being with clang-tidy picking it up properly?)

Indeed.

**Comment by actual-nh** [comment]
It doesn't seem to be time of day; checking weather + resetting sight limits.

**Comment by actual-nh** [comment]
Nope. Trying resetting visibility, map caches.

**Comment by actual-nh** [comment]
Well, so far, all of them are "failing properly" - no "can't see your opponent on level ground" silliness. Given that previously all of them were doing that, looks like it was a combination of needing to reset the time and/or weather with then resetting caches for what's visible, etc.

**Comment by jbytheway** [comment]
Sorry, I don't know much about the weather override code.  Not sure how you'd undo that.

**Comment by actual-nh** [comment]
> Sorry, I don't know much about the weather override code. Not sure how you'd undo that.

I'll take a look - I suspect one sets it to WEATHER_NULL. If so, I'll do that with the weather and vehicle solar panel tests if they aren't directly setting the weather override anyway to start.

**Comment by jbytheway** [comment]
I'll write an RAII helper to make scoped weather overrides easier.

**Comment by actual-nh** [comment]
> I'll write an RAII helper to make scoped weather overrides easier.

Excellent! Once that's merged, the weather_override setting (to WEATHER_CLEAR then WEATHER_NULL) can be changed to just the scoped_weather_override with WEATHER_CLEAR.

**Comment by actual-nh** [comment]
Everything needed from this should be in #48245.

**Pull request closed without merging**
