### PR TITLE
Nerf tonfa/baton damage, make tonfas autolearned.

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
Balance "Nerf baton and tonfa damage"

#### Purpose of change

Batons, while being self-defense tools, are also still weapons capable of killing someone or breaking bones. However, they are not anti-armor breakers that should be out-DPSing a large amount of other dedicated bashing weapons like the trench mace, which I think serves as a good baseline for bashing weapons. The speed, accuracy, easy of use, and harrying potential of batons (and tonfas) should come with a downside rather than doing as much damage as something with a weighted metal head that is noticeably clumsier. While capable of killing, they are not battlefield weapons.

#### Describe the solution

Chunked the damage of all the batons and tonfas to be a bit closer to the cudgel, which makes a good comparison point. Tonfas (including the PR-24) had their damages reduced to 14 instead of 20-22, and the collapsible baton had its damage reduced to 12. I've also made the tonfa and wooden tonfa autolearned instead of requiring a rare book, because most people know what a tonfa (or at least a police truncheon) is and looks like, and they're not extraordinarily complex objects to craft either.

#### Describe alternatives you've considered

Buffing the damage of other bashing weapons (such as the trench mace/pipe mace) to be suitably stronger than a baton or tonfa, but those weapons already seem to perform fine for their tier as is.

#### Testing

Game works and stuff, recipes showed up in the recipe tab.

#### Additional context

This incidentally serves as a sort of soft nerf to lab starts since the PR-24 or expandable batons were easy and strong weapons you could just find on security guard zombies, I suppose.

### CODE REVIEW

**Comment by snipercup** [comment]
I don't think we should balance weapons around the implementation of other weapons, but rather look at sources that tell you what IRL batons can do in bash damage and translate that into the in-game weapon.

You compare it to the trench mace which was added in #50097 but that PR has no explaination of how the bashing damage came to be. That PR has no reference to real life equivelents. Why do you think that the trench mace serves as a good baseline for other bashing weapons?

**Comment by TheShadowFerret** [comment]
As the wooden tonfa is also made out of untreated wood like the cudgel, it should no longer be DURABLE_MELEE

**Comment by Aerin-of-the-Toast** [comment]
> I don't think we should balance weapons around the implementation of other weapons, but rather look at sources that tell you what IRL batons can do in bash damage and translate that into the in-game weapon.
> 
> You compare it to the trench mace which was added in #50097 but that PR has no explaination of how the bashing damage came to be. That PR has no reference to real life equivelents. Why do you think that the trench mace serves as a good baseline for other bashing weapons?

Fair enough. I don't have a super concrete reason for saying the trench mace is perfect as-is beyond vague allusions to game balance and "it just feels right," but even disregarding them I think 12-14 damage for the batons is more accurate since that puts it at a low enough damage it can only *barely* dent soldier zombie armor. As mentioned, batons aren't meant for breaking armor (or, furniture) so only barely being able to damage a zoldier through its kevlar makes sense to me.



> As the wooden tonfa is also made out of untreated wood like the cudgel, it should no longer be DURABLE_MELEE (IDK about the plastic one's DURABLE_MELEE nor why the wooden one is fab 4 for a t-shaped piece of wood 😛 )

I didn't really look into the recipes themselves; I think they mostly escaped notice until now because no one even knew tonfas were craftable because the Streetfighter's Sidekick is so extraordinarily rare lol.

**Comment by Aerin-of-the-Toast** [comment]
Recipe for the wooden tonfa has been made a bit easier (4 to 3 fabrication since it's probably still a bit more complicated than a cudgel) and faster (2 hours to 1 hour, again still slower than a cudgel by 15 minutes), and removed DURABLE_MELEE from the wooden tonfa. Didn't touch the plastic one though, I don't know how hardened plastic compares personally.

**Comment by Sinistrem** [comment]
I feel like this change will make security starts in labs / and especially TCL **_much_** harder, since you have to deal with a ton of moderately armored enemies early on (other security guards, occasional military zombie) and avoiding combat to "just run away" is not an option. 

I'm not debating whether or not those weapons deserve a nerf, just pointing out that there are other issues it causes which are not obvious when just comparing damage to other blunt weapons. Maybe replace guard starting weapon with something more in line with old batons? 

Tweaking point bonus of those starts and security guard point cost might also be an option, but I doubt extra points will compensate for the loss in early killing power.

**Comment by Aerin-of-the-Toast** [comment]
> I feel like this change will make security starts in labs / and especially TCL **_much_** harder...

Knock-on balance effects aren't really a concern, honestly. You can always just break apart some lockers for a pipe then sinks for pipe fittings and make a pipe mace if you need the bashing power. Also I'm not sure why guards should start with something better, they just batons irl after all, guards aren't running around with maces. (Maybe the spray kind of mace :p). And character creation points are a lie anyway tbh

**Pull request merged**
