### PR TITLE
Reworkeditemgroups

### PR DESCRIPTION
**Pull request by SunshineDistillery**
This is my project to rework the item groups into something more useful and legible. 

A lot of cool functionality has been added to the game, but which hasn't been applied to old item groups. Stuff like varying containers, charges, or damage to items; different types of groups like collections; and especially having an item group which draws from other item groups. That last one is the coolest, because it means that there could be generic-ish item groups in a main file that other groups, for locations or death drops, could draw from. So, for example, instead of having really large groups for a grocery store, an organic grocery store, and a farmer's market--lists which are almost identical--there could be an item group for fruits and another one for vegetables which the locations draw from in varying ratios. And then to make them unique they can have a few extra items tacked on. 

PROS 

+Because looting is the soul of Cataclysm, the item groups have a pretty large affect on gameplay.  Sometimes, like in a lab challenge or after you've been spoored by fungus, your life hinges on what items you can find. Often an item will be really really hard to find, not because it makes sense for it to be rare, but because it was neglected to be added to the proper groups. Conversely, rare expensive items show up with surprisingly regularity. So, better loot lists will mean a better game. I'm not saying I fixed the item balance--at all--but the groups should now be easier for others to read and adjust.

+The lists are generally shorter and more legible. It's very hard to read a super long list of items without having your eyes glaze over, and even harder to figure out the weights and probabilities. Short lists with focused types of items make more sense to humans. 

+When someone makes a new item for the game, they can add it to just the main groups without having to worry about the dozens of others groups in vehicle or mapgen or monsterdrop files. So, if someone makes a new type of teleporter and adds it to the Advanced Electronics group, it will then automatically appear in labs, on scientist zombies, in safes, etc. Anywhere that draws from that main group will have it.

+Like wise, if someone makes a new building, map extra, or vehicle with an item group that draws from the main groups, they won't have to worry about updating it later. If you make baseball park concession stand, and someone later adds Circus Peanuts to the candy group, the new item will automatically show up in your old building. 

+If you have ever used the debug menu to test item groups, you've seen that there are a ton of them. Many of them are fairly similar and redundant. So, with decent generic groups that are easy to find and read, hopefully people won't feel the need to make a new item group for every type of new building. This one isn't really a big deal because it doesn't affect gameplay, but it's nice for things to be compact. 

+The range of values were expanded so there's more room for fine tuning relative weights. I used a regular-ish set of numbers for probability. Of course it's always better to carefully examine a group before adding an item, but I'm assuming people won't actually do that. This way, if someone makes a common item and carelessly plops it into multiple lists with a value of 50 each time, the results will be mediocre instead of awful.

CONS

-I'm not actually trying to balance the loot lists; I'm trying to make them legible and a little smarter. I assigned pretty rough and arbitrary values along the way because it was beyond me to reorder everything AND balance things at the same time. So some things will be out of whack. (And if you see something that looks unbalanced, I consider that a success, because it means you can actually read the lists.) 

-It's freakin huge. The commits are huge and there are like a million of them. That's sort of the nature of the project since I'm erasing gigantic lists from one file and adding them to another. Despite being big and clunky, the changes are fairly simple, so I hope it's readable for people. 

-I just mess with the jsons, not the game. Probably changing the name of variable here and there is not a big deal, but I'd rather not get out of my depth or risk breaking things I don't understand. (Also I don't want to recompile the game every time I stop to check for errors.) A real programmer could have certainly done a much better job, but I'm the one who did it.

### CODE REVIEW

**Comment by illi-kun** [comment]
OMFG. Only one question: why did you do it in a single PR? It's pain check all of these changes at one time.

**Comment by SunshineDistillery** [comment]
Because I don't really know how to use git. I've been reading tutorials while working on this.

**Comment by Zireael07** [comment]
Jeez.

Love the dedication shown, but this needs to be split up.

PR 1: shuffling stuff.
PR 2: new functionality.

..or the other way round.

**Comment by Lain-** [comment]
This is something that should be done sooner or later IMHO. The huge PR will make it hard to check everything though.

I take a quick look through the change and the groups look resonable enough, don't know about the frequency though.

**Comment by RadaRadaRada** [comment]
Perhaps, guns looted from dead and corpses should spawn loaded with random number and type of ammo appropriate to gun in question?

**Comment by Coolthulhu** [comment]
The idea is good, but with the PR of this size it's nearly impossible to review.
There are two ways to handle this:
* Break it up into sensible-sized PRs, each only covering one kind of item group
* Merge it as is, hope nothing breaks, then spend few weeks fixing the things that will inevitably break (hopefully not enough to make the game unplayable)

I'd rather go with the former.

**Comment by kevingranade** [comment]
Since you made a large number of separate commits, it might be mergeable in
pieces, though there is an incredibly high chance that the changes will
become invalidated before it is all merged.
Can you identify which commits leave the code in a worrying state?

It is very likely that this simply will not work, changes like this *must*
be broken into manageable chunks.

**Comment by kevingranade** [comment]
Also there needs to be a high level summary of what you are doing,  what
was wrong with the old situation and how does this fix that problem?

**Comment by SunshineDistillery** [comment]
Darn. I thought breaking it up into commits was all that was needed. Sorry, guys.

Now, that I have final form it might be fairly easy to redo. Most of the work was making the new item groups rather than shuffling them to new files. That's why I committed so much so fast.

**Pull request closed without merging**
