### PR TITLE
Dig a channel to divert a river.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Features "Dig channels to divert shallow river flowing water."```

#### Purpose of change
This relies on PR #28014 
Use a digging tool on terrain that is diggable, adjacent ( not diagonal ) to a shallow river tile, this will take an hour or two ( depending on tool quality ) , and create a new shallow moving water tile.

#### Describe the solution
This will be useful for base moats, water wheels, future implementations of features - irrigation, farming sprinklers, sanitation, who knows.

#### Describe alternatives you've considered
There is one thing I'm concerned about, in the current implementation of water "flow" ... well there is no flow, it's just a flag that says it's moving, therefore you can create a channel of moving water, even though the channel is not really diverting a current, or even needs to be joined back up to the River.
The options here may be to require it to join back up to a river, which creates tonnes of more problems of how that works.
Or allow a dead-end channel to be "flowing" which creates problems of realism.
I am not entirely sure which is best, a stagnant water channel is of less practical use.

### CODE REVIEW

**Comment by KITbutler** [comment]
> Or allow a dead-end channel to be "flowing" which creates problems of realism.

Since the rivers never really go anywhere either can't we just assume the water slowly seeps into the surrounding ground or splits into tiny creeks not worth distinguishing from wet dirt?

**Comment by davidpwbrown** [comment]
> > Or allow a dead-end channel to be "flowing" which creates problems of realism.
> 
> Since the rivers never really go anywhere either can't we just assume the water slowly seeps into the surrounding ground or splits into tiny creeks not worth distinguishing from wet dirt?

This is what i was imagining.

**Comment by Night-Pryanik** [comment]
I assume removing lab terrains is an error?

**Comment by davidpwbrown** [comment]
how the hell did I do that, I saw that in the merge conflict resolving, but I thought I specifically told it NOT to do that !

**Comment by davidpwbrown** [comment]
closing in favour of a cherry picked commit to a new PR as ive done something very very wrong with the merge conflict fixing here.

**Pull request closed without merging**
