### PR TITLE
Add a crafting recipe for propane lanterns

### PR DESCRIPTION
**Pull request by descende**
#### Summary

Content "added propane lantern recipe"

#### Purpose of change

consistency with existing lantern recipes

#### Describe the solution

made a recipe

#### Describe alternatives you've considered

making them more common

#### Testing

added the recipe to my install and crafted one

### CODE REVIEW

**Comment by descende** [comment]
reopened because i pulled from master instead of branching

**Comment by TealcOneill** [comment]
Hmm, the issue here is that propane is a highly pressurized gas and not a liquid. 
With the gasoline lantern the cordage/cotton patch wicks the liquid up past the metal cap when then turns into a vapor that burns.
The metal scrap I believe represents a cap that prevents the flame from traveling back down into the bottle container and igniting any vapor that the fuel in there gives off.
Meanwhile propane won't be mediated or absorbed by a wick and it would be almost impossible to regulate the valve of the tank to provide continuous steady amounts. Modern heaters/lanterns have precise outlets that use the pressure from the tank to keep the flame at consistent size.
There is a ton of danger in trying to make or adjust these kinds of fittings by yourself.
I think this could possibly be done but it would require a dedicated recipe, not autolearn. Use of appropriate materials, i.e. fittings and pipping as well as metal scraps. It would also probably be a fairly high fabrication level. 

I know it's a bit intimidating to see this as a new contributor but we do want to keep the game fairly realistic and believable.
I think that if you spend some time researching and thinking on this you could come up with a better recipe and make a great addition to the game! 👍 
Feel free to ask anything you want and I'll try and get back to you asap. You can also talk about this in the developers discord channel. Everyone is super willing to help out and discuss these things.

**Comment by TealcOneill** [comment]
The new recipe looks much better, good stuff!

**Comment by I-am-Erk** [comment]
Make sure to keep the original PR template... We can't merge PRs when the changelog info is in a different format. In this case you deleted some line breaks, I've added them back

**Comment by I-am-Erk** [comment]
That was a hard one but you apparently had a ” instead of a ". I changed it, should pass the test now. Thank goodness for casswhedon's sharp eyes

**Pull request merged**
