### PR TITLE
Limbs, gloves, and boots cleanup

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Cleans JSON for gauntlets and sabatons."

#### Purpose of change
Removes ONLY_ONE which was unnecessary. Uses copy-from for variant pieces to simplify.

#### Describe the solution
Update boots.json and gloves.json.

#### Describe alternatives you've considered
None.

#### Testing
Verified items spawn correctly.

#### Additional context
Footwear is still limited to one set until #55566 is completed. This means that individual sabatons cannot be worn together currently.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
The PR that covers fixing your issue is #55566 not the sublimb all the limbs

**Comment by Drew4484** [comment]
> The PR that covers fixing your issue is #55566 not the sublimb all the limbs

Oops yeah copied the wrong PR.

**Comment by PlutusPleion** [comment]
Correct me if I'm wrong but I don't see "sided":  true for heavy arm guard for example, neither does the base item from "copy-from".

This means you can wear 2 arm guards but you're getting double coverage.

**Comment by Drew4484** [comment]
> Correct me if I'm wrong but I don't see "sided": true for heavy arm guard for example, neither does the base item from "copy-from".
> 
> This means you can wear 2 arm guards but you're getting double coverage.

Just pushed the commit to fix those, it was on the light version but didn't get carried over to the medium and heavy. Same for legs. Once #55566 is complete, we'll limit hard armor to one per limb, so the ONLY_ONE flag won't be needed, which is good because that doesn't play well with sided.

**Pull request merged**
