### PR TITLE
Artifact passives occur on HELD and not WIELD

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Artifacts apply passives in inventory instead of when wielded"

#### Purpose of change
Artifacts as they were were largely pointless. Although there are currently lots of new, exciting and dangerous ways to obtain them there's still no _incentive_ to do so. Because the artifacts only apply their passive effects when you actually hold them in hand essentially only their activated effects mattered, except in some extremely dumb and niche edge cases - if you hold a +strength artifact in your hands, you can lift a heavier engine into your car. If you hold a +speed artifact in your hands, you can craft faster. These are obviously really illogical since you're using the artifact in your hands to assist you with something that needs free hands. 

#### Describe the solution
Procgen artifact passives now occur on HELD instead of WIELD. Since artifacts are hardcoded to ask "is this armor? if so make it happen on WORN, if not make it happen on WIELD" instead it makes the artifact passives occur on HELD (present in your inventory)

#### Describe alternatives you've considered
This has potential balance implications of a character carrying around a bag of artifacts to get boosts, but as the game currently is this still poses some potential side effects - only stat effects are really immediately visible and unless you look in your game files, it could have side effects like increased thirst or slower weapon swings that you may not know about and are impacting you. It also makes artifacts more interesting to handle since you cannot "contain" their effects. Maybe there's an artifact that spawns friendly bees that you want but it has big passive penalties on it, so now you need to bring it home with those added debuffs. 
One alternate solution is to make these artifacts use the "ablative armor" system and have the WORN condition to specifically slot into an artifact receptacle to apply their passives. But right now this is the simplest change to make a big difference.

#### Testing
Spawned at the bottom of a mine, picked up a malleable blob, noticed it was giving me -1 strength while in my pockets. Dropped it and strength went back to normal.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
You can still bring an artifact with you by hauling it along the ground, as well as placing it into a vehicle (such as a shopping cart).
Carrying the artifact in the inventory rather than wielding it makes a lot of sense, though. If there's some reason you'd want to restrict the number of artifacts currently providing their passive effects I guess specific artifact pockets could be used, but then you'd have to somehow tell the player that such pockets are needed, how to make them (or find out how to make them), and restrict the number of pockets/slots in that thing, in addition to balance it such that it doesn't block usage of some equipment (by taking up and blocking a particular layer on a particular body part).

**Comment by Maleclypse** [comment]
> You can still bring an artifact with you by hauling it along the ground, as well as placing it into a vehicle (such as a shopping cart). Carrying the artifact in the inventory rather than wielding it makes a lot of sense, though. If there's some reason you'd want to restrict the number of artifacts currently providing their passive effects I guess specific artifact pockets could be used, but then you'd have to somehow tell the player that such pockets are needed, how to make them (or find out how to make them), and restrict the number of pockets/slots in that thing, in addition to balance it such that it doesn't block usage of some equipment (by taking up and blocking a particular layer on a particular body part).

Or create an effect that occurs once you pass a certain number of artifacts on your person.

**Comment by anoobindisguise** [comment]
> Or create an effect that occurs once you pass a certain number of artifacts on your person.

That sounds good, although it's probably out of scope. But more nether fuckery, teleportitis, etc as you hoard too many nether shinies would be a fun mechanic.

**Comment by PatrikLundell** [comment]
I wouldn't find it either fun or interesting to suddenly get screwed over for no known reason. If you were to introduce artifact interactions/interference you ought to provide some way for the player to detect it or otherwise get to know about the danger or you'd create an in-game death trap that can only be avoided by meta game knowledge. Also, setting up an artifact stockpile would be a recipe for disaster...

**Comment by Inglonias** [comment]
your PR has three zeros on the end of it.

**Comment by Maleclypse** [comment]
> I wouldn't find it either fun or interesting to suddenly get screwed over for no known reason. If you were to introduce artifact interactions/interference you ought to provide some way for the player to detect it or otherwise get to know about the danger or you'd create an in-game death trap that can only be avoided by meta game knowledge. Also, setting up an artifact stockpile would be a recipe for disaster...

If we were to do something like artifact resonance we’d need escalating warnings as you were holding more artifacts. But this is out of scope for the PR and probably deserves its own issue.

**Comment by anoobindisguise** [comment]
Tested and compiled, confirmed functional.

**Review by Maleclypse — APPROVED** [review]
I think this is a reasonable change.

**Pull request merged**
