### PR TITLE
Magiclysm brown dragon

### PR DESCRIPTION
**Pull request by ZhamelSeh**
#### Summary
SUMMARY: Content "Adding brown (nature) dragons to Magiclysm"

#### Purpose of change
First of the dragon types. Brown, nature/forest dragon. No special breath weapon for this dragon, it functions similar to fungal queen and the soldier, creates trees around it combined with paralyzing sting. Hopefully it's a challenge (still learning monster balancing).

All of the items (equipment, recipes, books, etc) have been completed. Gear stats are similar to black dragon, except the brown provides more environmental protection instead of acid protection. This goes along with the nature theme. Zero fire protection due to nature being very susceptible to it. A little acid protection.

Everything has been created so far except for a lair, still looking into how those are created.

#### Describe the solution
No solution, adding content.

#### Describe alternatives you've considered
Other dragon types to be added in the future.

#### Testing
Loaded test world and spawned in equipment. Crafting should not be an issue due to copy/paste nature of recipes.

#### Additional context
Need tileset art next. Also fixed a mention of kevlar in black_dragon_items (new PR for this?).

### CODE REVIEW

**Comment by ZhamelSeh** [comment]
Already fixed the PR summary and JSON issue.

If someone could give me some pointers on balance for the dragons and items, that would be the most helpful. Unless there is a document somewhere for guidelines?

**Comment by KorGgenT** [comment]
why choose the color brown over green? green dragons are the canonical forest dwellers in dnd, breathing toxic gas.

**Comment by ZhamelSeh** [comment]
Yes, green are the traditional forest dragons. This is just an idea, easy to change all of it. Have both the green and brown in the forests, since forests are so plentiful in the world generation. Green will be the poison dragon with a poison special breath attack, brown would actually make the forests grow and attack the PC.

I was hesitant to have one dragon do both a poison gas attack and have it grow the vegetation/trees to attack the PCs as I was not sure that would be balanced enough and too much on one monster. This is using the black dragon you made as a base template. If you think that it would be fine then I can redo this one easy enough as I already have red/blue/white/green, with radiation (color?) in the planning stage, created on my test game, so no problem to combine the two.

**Comment by KorGgenT** [comment]
please let me know if you want to continue working on this, but the last real activity on it was 4 months ago so i'm closing it as stale. this does not mean i do not want the change, i am just reducing the number of PRs we see in the tracker.

**Pull request closed without merging**
