### PR TITLE
Add Vermin trait, update squeamish, add a mood-enhancing bionic

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Content "Moves bile resistance to its own trait, updates squeamish, adds a bionic to cope with bad moods"

#### Purpose of change

#71964 made filth more of a factor for characters, but I rather clumsily made saprovore, saprophage, and eater of the dead grant immunity to some of bile's effects. This was a bit inconsistent, and I decided it would be better to put all the bile-resisting effects in one mutation, which also resists morale penalties for filthy clothing and being in the sewer, the latter being an EOC added in #71476 

I also added a bionic which doesn't resist the morale penalties, but can grant a bonus to offset them. These two minor changes provide players with a reasonable avenue to avoid or offset the effects of filth becoming more common.

Squeamish was not designed to account for items becoming filthy while worn. It now multiplies morale penalties from this by 1.5.

#### Describe the solution

- Vermin: Adds the Vermin mutation to Troglobite, Insect, Chimera, and Gastropod. This mutation has Vomitous, Eater of the Dead, or Saprovore as a prerequisite. Vermin are immune to the lifestyle and nausea effects of bile, and receive no morale penalty for wearing filthy clothing or being in a sewer. This does not protect them from things like the infection chance from being wounded while wearing filthy clothing. Cancels Squeamish.
- Adds Saprovore to Insect. Bugs famously eat rotten stuff.
- Removes bile resistance from all traits except Vermin.
- Squeamish still prevents putting on filthy clothes, and now multiplies the morale penalty from filth by 1.5.
- Adds the Mood Enhancer CBM. This is not something Rubik sells, it can only be harvested from zomborgs. The exodii will still install it if you bring them one, but what they won't tell you is that it is actually used for keeping the more autonomous workers from freaking out or rebelling. While inactive, it has no effect. While active, it adds +10 morale, -2 dexterity, and -10% Reaction. When turned off, there's a hangover effect where you get -5 morale for 30 minutes, and -1 dex and -5% reaction for 15 minutes. It's meant to be akin to the joywire in rimworld, great for downtime, not so great during an emergency.

#### Describe alternatives you've considered

The mood enhancer could alternatively be a +20 mood buff that you can just never turn off, but I think that would lead to nobody using it, and I imagine it's a more effective social engineering tool if it can be remotely turned on and off as needed.

Conversely, I think maybe the mood enhancer could have a higher power draw and inflict a penalty when it's offline.

#### Testing

- Got a shirt filthy with no traits, saw the usual -16 morale penalty.
- Gained the Vermin trait, the penalty disappeared.
- Lost the Vermin trait and gained the Squeamish trait, saw that the penalty went to -24.
- Installed a mood enhancer CBM. Saw it granted the appropriate bonuses and penalties, and that these were permanent as long as it was on.
- Turned it off, saw that the bonuses and penalties were replaced by the temporary hangover effect.
- Turned it back on, lost the hangover.
- Saw that power draw was as expected.
- Saw that the CBM was not uninstallable, with the appropriate message for why.
- Dissected many zomborgs until I found a mood enhancer CBM

#### Additional context

Rats and mice do not get this trait, as they are actually extremely fastidious animals who constantly groom themselves. If you want to be a sewer rat, I recommend taking a dip in the troglobite line.

### CODE REVIEW

**Comment by carlarctg** [comment]
The name 'Slob' feels wrong. Slob is used to represent greasy and trashy modern people, and while that fits here somewhat, in this case we're talking about the mutant adaptations caused by becoming more beastly or eldritch. It's not that they're normal people who choose to live disgustingly, but just that their mutations into a more animal form cause them to lose that ingrained disgust response. That doesn't feel like a Slob thing to me. 

Additionally, because it's a 'modern' term that refers to 'modern' filthy people, it made me think upon viewing this PR's title that you would be adding a new character trait, not a beastly mutation, which I think will cause some confusion.
Admittedly it's quite hard to find a good term for it. How about 'Filth Indifferent/Tolerant'?

**Comment by fairyarmadillo** [comment]
> The name 'Slob' feels wrong.

I think Saprophile might be the move here. I was struggling to find a word that made sense. I completely agree that slob sounds like a slovenly person and not, for example, a maggot that lives in rotting flesh.

**Comment by fairyarmadillo** [comment]
@Standing-Storm  since you're doing racial stuff in Magiclysm, it may interest you to know that ignoring or getting 1.5 times the penalty for filthy items are tied to json flags and not the traits themselves. Being unable to put on filthy clothes in the first place is still attached to the Squeamish trait though. Might be good for elves and goblins(?)

**Review by Fris0uman — CHANGES_REQUESTED** [review]
Please cut the PR in discret part, mix bags PR like that are very difficult to review

**Comment by fairyarmadillo** [comment]
> This PR seems kinda all over the place. What is the commonality with hygiene, insectile dietary preference, and cybernetic antidepressants?

Ways to deal with the bile changes, but sure.

**Pull request closed without merging**
