### PR TITLE
Deploy OS X App bundles with Travis CI

### PR DESCRIPTION
**Pull request by ghost**
**Dont't merge this directly into the master branch!**

Just want to notice you that I've automated the build&release process with [Travis CI](https://travis-ci.org/auto-load/Cataclysm-DDA/builds/123472043).
Anyone can use this `.travis.yml` to build his/her own CataclysmDDA.app (Graphics or Terminal).

For example, all tagged commits got released here:
https://github.com/auto-load/Cataclysm-DDA/releases
Note: to deploy the app, you must create a tag for the project

Have fun! :cake:

### CODE REVIEW

**Comment by illi-kun** [comment]
@jakwings If it shouldn't be merged it shouldn't be here. Why you didn't put it on the forum?

**Comment by jakwings** [comment]
@illi-kun I said this shouldn't be merged **directly** into the master branch. I need some feedback, and just be waiting now.

There are far less active osx *developers* on the forum. This GitHub repository is a better place for developers to find useful information about the compiling and deployment of osx build.

**Comment by illi-kun** [comment]
Typically, we're adding '[CR]' (comments required) tag to the PR's title for this case.

**Comment by mugling** [comment]
If you don't want this merging would be better as an issue

**Comment by jakwings** [comment]
Ok, I can see that the official jenkins build is enough for testing the compilation on os x.

**Pull request closed without merging**
