### PR TITLE
Further improve lab escape start - add a brute who smashed the glass.

### PR DESCRIPTION
**Pull request by BrianLefler**
#### Summary
SUMMARY: Content "Improve lab escape more."

#### Purpose of change
Changes cells: Adds north-facing doors with a locked hallway, makes south windows reinforced, adds a bashed in window - this is the cell the player spawns in.

To the area below, creates 3 variants, all of which have a zombie brute (who smashed the glass in story terms) between the player and the door.  Players are able to run past and put a metal door between them and the zombie, but may take a hit along the way.

Fixes the spawn bounds more precisely to be the cell - the old logic was slightly off, which showed since the valid spawn area here is so small now.

#### Additional context
screen shot 2018-09-14 at 7 34 41 pm
screen shot 2018-09-14 at 7 33 15 pm
screen shot 2018-09-14 at 7 31 18 pm

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> a zombie brute (who smashed the glass in story terms)

It's hard to relate a broken glass and a brute that for whatever reasons is standing too far away from it. Looking at the screenshots, I'd say it's much more likely that a player himself smashed the window (leaving the question though - but with what tools?).

**Comment by Robik81** [comment]
> It's hard to relate a broken glass and a brute that for whatever reasons is standing too far away from it.

Hmm, is it possible to add_msg at the start of the game? Or some kind of welcome screen? Dependent on the starting scenario?

That would be pretty cool.

Message could be something like _Passing zombie brute smashed the glass in his rage. I should be careful, the monster can be still nearby..._

**Comment by BrianLefler** [comment]
Changed, removed a reference to being set free in 'unwilling mutant'.

Also added a pair of lockers to the map which had only one door leading to a room, so in case of very bad luck and that room having a turret, the player can drag LOS blocking furniture in front to escape (if they can deal with the brute, at least).

**Comment by ZhilkinSerg** [comment]
> It's hard to relate a broken glass and a brute that for whatever reasons is standing too far away from it. Looking at the screenshots, I'd say it's much more likely that a player himself smashed the window (leaving the question though - but with what tools?).

Maybe we should display window with some flavor scenario text in the beginning of the game?

**Pull request merged**
