### PR TITLE
More misc item fixes & AID obsoletion

### LINKED ISSUE #63535: Error when trying to re``f``ill a vehicle tank
### Describe the bug

An error screen pops up when pressing f to refill a tank in a vehicle. Sometimes happens just when examining the vehicle. The weird part is it only happens on that one specific vehicle (that I built).

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10713077/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

1. Examine the vehicle (the one the character is standing in)
2. If no error screen yet - press ``f`` to refill tanks
3. Behold the error screen

### Expected behavior

Man I'd really rather not see error screens that'd be grand

### Screenshots

obraz

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 2ee4928 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
I like it when things work good
ALSO fixes #63535

#### Describe the solution

<details>
<summary>WEIGHT CHANGES</summary>

- Chalice: 1.5kg -> 200g
- Waffle iron: 2628g -> 520g
- Adjustable wrench: 907g -> 417g
- Bundle of pipes: 1251g -> 12500g
- Bundle of copper tubing: 1251g -> 3400g
- Cow bell: 566g -> 330g
- Narrow-spectrum antibiotics: 15g -> 611mg
- Antibiotics: 1g -> 611mg
- Broad-spectrum antibiotics: 1g -> 611mg
</details>

<details>
<summary>VOLUME CHANGES</summary>

- Chalice: 250ml -> 330ml
- Waffle iron: 5l -> 0.87l
- Adjustable wrench: 120ml -> 75ml
- Cow bell: 1l -> 300ml
- The entire chitin skin mutation line integrated armor set has had its volume increased to fix the density tests (no gameplay impact)
</details>

<details>
<summary>LENGTH CHANGES</summary>

- Chalice: ``none`` -> 12cm
- Waffle iron: ``none`` -> 30cm
- Adjustable wrench: 20cm -> 25cm
- Bundle of pipes: 23cm -> 60cm
- Bundle of copper tubing: 23cm -> 60cm
- Cow bell: ``none`` -> 20cm
</details>

<details>
<summary>MATERIAL CHANGES</summary>

- Waffle iron: ``iron`` -> ``aluminum``
- Cow bell: instead of being 50/50 ``brass`` and ``wood`` it is now 95:5 ``steel`` and ``rubber``
- Match: ``none`` -> ``wood``
- Manhole cover: ``steel`` -> ``iron`` (they're made of cast iron irl, I done goofed previously)
</details>

<details>
<summary>PRICE CHANGES</summary>

- Chalice: ``pre-apo`` 100$ -> 19$
- Waffe iron: ``pre-apo`` 20$ -> 16$
- Adjustable wrench: ``pre-apo`` 12$ -> 18$
- Multivitamins: ``pre-apo`` 0.9$ -> 18$, ``post-apo`` 1$ -> 10$ (I misunderstood price code in the last item fix)
- Cow bell: ``pre-apo`` 7$ -> 10$
- Toolbox: ``pre-apo`` 130$ -> 17$, ``post-apo`` 30$ -> 1$
- Abstract dodge skillbook: ``post-apo`` 50$ -> 2$
- Hot Rod Chassis & Suspension Handbook: ``post-apo`` 240$ -> 7.5$
- Rocuronium: ``post-apo`` 200$ -> 2$
</details>

<details>
<summary>DISASSEMBLY CHANGES</summary>

- Chalice: initial disassembly implementation
- Waffle iron: initial disassembly implementation
- Adjustable wrench: initial disassembly implementation
- Cow bell: initial disassembly implementation
- Purse: time taken 1h -> 20min
- Handheld game system: time taken 1h -> 20 min
- Electronic blanket: now gives cotton sheets instead of patchwork cotton sheets
- Back scabbard: initial disassembly implementation
- Shorts: initial disassembly implementation
- Leather pants: FULL disassembly rework, check JSON
- Jumpsuit: initial disassembly implementation
- Tank top: now handled via a reversible recipe
- Undershirt: now handled via a reversible recipe
- Tunic: initial disassembly implementation
- Canvas sack: time taken 10m -> 2m
- Pillowcase: initial disassembly implementation
- Blanket: initial disassembly implementation
- Runner pack: initial disassembly implementation
- Hoodie: now handled via a reversible recipe
- Sweatshirt: now handled via a reversible recipe
- Crack pipe: initial disassembly implementation
- Glass pipe: initial disassembly implementation
- Water faucet: initial disassembly implementation
- Scrap knuckles: initial disassembly implementation
- Down-filled blanket: now gives 33 cotton sheets instead of 35 cotton patches
- Manhole covers: steel chunks given 130 -> 109
</details>

<details>
<summary>RECIPE CHANGES</summary>

- Waffle iron: now needs aluminum to craft and uses less charges
- Adjustable wrench: now needs significantly less steel to craft and uses less charges
- Leather pants now use 5 ``tailoring_leather_patchwork`` instead of 4
- Shorts now use 4 ``tailoring_cotton_patchwork`` instead of 7 and give one less patch as a byproduct
- Jumpsuit: no longer uses ``sewing_standard`` on top of ``tailoring_cotton_patchwork``
- Down-filled blanket: no longer uses ``cotton_patchwork`` for whatever reason when it already uses ``tailoring_cotton_patchwork_simple``
</details>

<details>
<summary>CATEGORY CHANGES</summary>

- Plastic shopping bag: ``clothing`` -> ``containers``
- Butchery refuse: ``comestible`` -> ``other``
- Match: ``ammo`` -> ``tools``
- Matchbox: ``tools`` -> ``containers``
- Matchbook: ``tools`` -> ``containers``
</details>

<details>
<summary>FLAG CHANGES</summary>

- All propane tanks: added ``NO_SALVAGE``
- Socket wrench set: added ``NO_SALVAGE``
- Combat knife: added ``NO_SALVAGE``
- Wood axe: added ``NO_SALVAGE``
- Hoe: added ``NO_SALVAGE``
- Pair of bolt cutters: added ``NO_SALVAGE``
- Shovel: added ``NO_SALVAGE``
- Headlight: added ``NO_SALVAGE``
- An ungodly amount of fake tools/appliances: Made flags work via ``extend`` to have their density tests not break
</details>

<details>
<summary>MISC CHANGES</summary>

- Waffle irons have been removed from the iron group at recycling center, moved to aluminum group
- Antennas have been removed from the aluminum group at recycling center, moved to copper group
- Cement name changed to cement powder
- Chalice name changed to gold chalice
- Made waffle iron use ``to-hit`` modifiers and lowered its damage to account for size changes
- Made adjustable wrench use ``to-hit`` modifiers and lowered its damage to account for size changes
- Added liquid ammonia to the temperature removal blacklist
- A LOT of disassemblies got attached skills removed. Taking sand out of sandbags, cutting up rubber strips or bashing a skull with a rock should not train your fabrication
- Liquid soap got changed from type ``AMMO`` to type ``COMESTIBLE`` to avoid errors
- Added new item! Leather sheets - they are basically pre-cata sheets of leather used in tailoring. Added to two tailoring itemgroups but most commonly should be obtained from disassembling clothing. Added primarily so that purses and the such didn't disassemble into tanned hides (handling of reversible recipes)
- Pillowcases and body pillows now have ``repairs_like: tshirt`` so they should be feasibly repairable
- Removed several items from the ``known_bad_density_list`` without applying any changes
- All the AIDs have been moved to both Aftershock and Xedra Evolved at @Maleclypse's request. These files also have copies of the affected bionics that they should override then with. I also used this opportunity to fix up the weight of AIDs from 150g to 35g and give them plastic as material so they should no longer fail the density checks
</details>

### CODE REVIEW

**Comment by Karol1223** [comment]
@Maleclypse I moved the AIDs to Aftershock and Xedra like you asked. I'd appreciate if you were to take a look and tell me if this is sufficient or if you want it done differently

**Comment by anothersimulacrum** [comment]
You need to be making more, smaller PRs, this does too much. Your PRs also should have a descriptive title.
> WEIGHT CHANGES
> 
>     * Chalice: 1.5kg -> 200g
> 
>     * Waffle iron: 2628g -> 520g
> 
>     * Adjustable wrench: 907g -> 417g
> 
>     * Bundle of pipes: 1251g -> 12500g
> 
>     * Bundle of copper tubing: 1251g -> 3400g
> 
>     * Cow bell: 566g -> 330g
> 
>     * Narrow-spectrum antibiotics: 15g -> 611mg
> 
>     * Antibiotics: 1g -> 611mg
> 
>     * Broad-spectrum antibiotics: 1g -> 611mg
> 
> 
> VOLUME CHANGES
> 
>     * Chalice: 250ml -> 330ml
> 
>     * Waffle iron: 5l -> 0.87l
> 
>     * Adjustable wrench: 120ml -> 75ml
> 
>     * Cow bell: 1l -> 300ml
> 
>     * The entire chitin skin mutation line integrated armor set has had its volume increased to fix the density tests (no gameplay impact)
> 
> 
> LENGTH CHANGES
> 
>     * Chalice: `none` -> 12cm
> 
>     * Waffle iron: `none` -> 30cm
> 
>     * Adjustable wrench: 20cm -> 25cm
> 
>     * Bundle of pipes: 23cm -> 60cm
> 
>     * Bundle of copper tubing: 23cm -> 60cm
> 
>     * Cow bell: `none` -> 20cm
> 
> 
> MATERIAL CHANGES
> 
>     * Waffle iron: `iron` -> `aluminum`
> 
>     * Cow bell: instead of being 50/50 `brass` and `wood` it is now 95:5 `steel` and `rubber`
> 
>     * Match: `none` -> `wood`
> 
>     * Manhole cover: `steel` -> `iron` (they're made of cast iron irl, I done goofed previously)
> 
> 

These changes all fit into one PR.

> PRICE CHANGES
> 
>     * Chalice: `pre-apo` 100$ -> 19$
> 
>     * Waffe iron: `pre-apo` 20$ -> 16$
> 
>     * Adjustable wrench: `pre-apo` 12$ -> 18$
> 
>     * Multivitamins: `pre-apo` 0.9$ -> 18$, `post-apo` 1$ -> 10$ (I misunderstood price code in the last item fix)
> 
>     * Cow bell: `pre-apo` 7$ -> 10$
> 
>     * Toolbox: `pre-apo` 130$ -> 17$, `post-apo` 30$ -> 1$
> 
>     * Abstract dodge skillbook: `post-apo` 50$ -> 2$
> 
>     * Hot Rod Chassis & Suspension Handbook: `post-apo` 240$ -> 7.5$
> 
>     * Rocuronium: `post-apo` 200$ -> 2$
> 

These would be better in a separate PR, especially the post apocalypse price changes (pre-apoc don't really matter, so could go with volume/weight).

> DISASSEMBLY CHANGES
> 
>     * Chalice: initial disassembly implementation
> 
>     * Waffle iron: initial disassembly implementation
> 
>     * Adjustable wrench: initial disassembly implementation
> 
>     * Cow bell: initial disassembly implementation
> 
>     * Purse: time taken 1h -> 20min
> 
>     * Handheld game system: time taken 1h -> 20 min
> 
>     * Electronic blanket: now gives cotton sheets instead of patchwork cotton sheets
> 
>     * Back scabbard: initial disassembly implementation
> 
>     * Shorts: initial disassembly implementation
> 
>     * Leather pants: FULL disassembly rework, check JSON
> 
>     * Jumpsuit: initial disassembly implementation
> 
>     * Tank top: now handled via a reversible recipe
> 
>     * Undershirt: now handled via a reversible recipe
> 
>     * Tunic: initial disassembly implementation
> 
>     * Canvas sack: time taken 10m -> 2m
> 
>     * Pillowcase: initial disassembly implementation
> 
>     * Blanket: initial disassembly implementation
> 
>     * Runner pack: initial disassembly implementation
> 
>     * Hoodie: now handled via a reversible recipe
> 
>     * Sweatshirt: now handled via a reversible recipe
> 
>     * Crack pipe: initial disassembly implementation
> 
>     * Glass pipe: initial disassembly implementation
> 
>     * Water faucet: initial disassembly implementation
> 
>     * Scrap knuckles: initial disassembly implementation
> 
>     * Down-filled blanket: now gives 33 cotton sheets instead of 35 cotton patches
> 
>     * Manhole covers: steel chunks given 130 -> 109

These are another PR, but probably belong with the weight/volume/material changes.
 
> RECIPE CHANGES
> 
>     * Waffle iron: now needs aluminum to craft and uses less charges
> 
>     * Adjustable wrench: now needs significantly less steel to craft and uses less charges
> 
>     * Leather pants now use 5 `tailoring_leather_patchwork` instead of 4
> 
>     * Shorts now use 4 `tailoring_cotton_patchwork` instead of 7 and give one less patch as a byproduct
> 
>     * Jumpsuit: no longer uses `sewing_standard` on top of `tailoring_cotton_patchwork`
> 
>     * Down-filled blanket: no longer uses `cotton_patchwork` for whatever reason when it already uses `tailoring_cotton_patchwork_simple`

These go with the density/volume/material changes  

> CATEGORY CHANGES
> 
>     * Plastic shopping bag: `clothing` -> `containers`
> 
>     * Butchery refuse: `comestible` -> `other`
> 
>     * Match: `ammo` -> `tools`
> 
>     * Matchbox: `tools` -> `containers`
> 
>     * Matchbook: `tools` -> `containers`

Another PR.
 
> FLAG CHANGES
> 
>     * All propane tanks: added `NO_SALVAGE`
> 
>     * Socket wrench set: added `NO_SALVAGE`
> 
>     * Combat knife: added `NO_SALVAGE`
> 
>     * Wood axe: added `NO_SALVAGE`
> 
>     * Hoe: added `NO_SALVAGE`
> 
>     * Pair of bolt cutters: added `NO_SALVAGE`
> 
>     * Shovel: added `NO_SALVAGE`
> 
>     * Headlight: added `NO_SALVAGE`
> 
>     * An ungodly amount of fake tools/appliances: Made flags work via `extend` to have their density tests not break

Another PR.
 
> MISC CHANGES
> 
>     * Waffle irons have been removed from the iron group at recycling center, moved to aluminum group
> 
>     * Antennas have been removed from the aluminum group at recycling center, moved to copper group
> 
>     * Cement name changed to cement powder
> 
>     * Chalice name changed to gold chalice
> 
>     * Made waffle iron use `to-hit` modifiers and lowered its damage to account for size changes
> 
>     * Made adjustable wrench use `to-hit` modifiers and lowered its damage to account for size changes

These can go with material/volume/weight changes.
 
>     * Added liquid ammonia to the temperature removal blacklist

Another PR.

>     * A LOT of disassemblies got attached skills removed. Taking sand out of sandbags, cutting up rubber strips or bashing a skull with a rock should not train your fabrication

Another PR.

>     * Liquid soap got changed from type `AMMO` to type `GENERIC` with `stackable: true` to avoid errors

Why? Another PR anyways.

>     * Added new item! Leather sheets - they are basically pre-cata sheets of leather used in tailoring. Added to two tailoring itemgroups but most commonly should be obtained from disassembling clothing. Added primarily so that purses and the such didn't disassemble into tanned hides (handling of reversible recipes)

In a PR with disassembly recipes for items that use them.
 
>     * All the AIDs have been moved to both Aftershock and Xedra Evolved at @Maleclypse's request. These files also have copies of the affected bionics that they should override then with. I also used this opportunity to fix up the weight of AIDs from 150g to 35g and give them plastic as material so they should no longer fail the density checks

Absolutely in another PR.

Making smaller PRs makes them easier to review and much faster to merge. If you're doing stuff like material/volume/weight changes like this that have a bunch of far reaching stuff, do it in small batches at a time, don't just do a bunch and shove it into one PR that's hard to review because it's doing 40 different things.

**Comment by Karol1223** [comment]
> You need to be making more, smaller PRs. This PR does (way) too much.

I both agree and disagree with you on this.
This PR looks too big because one file is a duplicate between two mods folders (adding ~450 new lines) and the additions to the obsolete are also directly copied from that file (adding around ~150 duplicate lines) but in reality it is nowhere near as big as some of my previous item fixes.

Typically, my PRs of this type stick around 350-500 new line mark - this one got bloated due to the AID obsoletion - which I do agree in hindsight should probably be in a separate PR. The rest, however, are so simple and small changes that I do not believe they warrant PR splitting. Especially not stuff like adding ammonia to the list for temperature tracking removal or changing the type of liquid soap - those are 1 or 2 line changes.

> Your PRs also should have a descriptive title.

Honestly, I do agree fully and I have nothing in my defense. I got too cocky here, I'll change the title in a bit

> Why?

Fixes #63535

> Try to keep PRs under 2000 lines of changes at most, and under 1000 preferably.

I typically try to stick around the 500 new line mark for that reason so that reviewing it doesn't take forever. This one is an anomaly in how it got out of hand and I apologize for that.

**Review by Maleclypse — COMMENTED** [review]
It looks like the Software items are missing for both Aftershock and Xedra Evolved.

**Comment by Karol1223** [comment]
> It looks like the Software items are missing for both Aftershock and Xedra Evolved.

What do you mean by software? The AIDs? They're at the bottom of the file.

**Comment by bombasticSlacks** [comment]
The BIO power armour was obsoleted, you will need to remove the sheets for that.

**Comment by Karol1223** [comment]
> The BIO power armour was obsoleted, you will need to remove the sheets for that.

Alright yeah that's done I forgot to edit that for Xedra

**Pull request merged**
