### PR TITLE
Spliting vehicles.json into multiple json files [CR]

### PR DESCRIPTION
**Pull request by KiwiTrinsic**
The vehicles.json file is rather long. What does everyone else think of splitting it up into separate json files to make it a bit more manageable?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Looks good.
I'm not sure if I'm reading it right, but did you blank the vehicles.json? You should `git rm` it too.

**Comment by KiwiTrinsic** [comment]
vehicles.json still contains the custom vehicle framework. Probably a good place for that and any other special vehicle types of that nature.

**Comment by illi-kun** [comment]
I tried to apply similar changes of one of json file, and my PR was declined for some reasons, and here is the list of these reasons (incomplete, probably):
- it's hard to track the correctness of all performed changes (was everything moved correctly?)
- it's hard to apply further massive changes to the bunch of files (comparing with processing of one file).
- it's hard to find some specific record thru the entire directory instead of one file.

For me, this PR is a step to right direction, such number of new files it's overkill (and why armored car is a member of ```vans_buses``` category instead of ```military```?)

**Comment by kevingranade** [comment]
The killer for me is validating it, I'm not even sure where I'd start to check that nothing was lost, or that nothing gets lost in a merge going forward.

**Comment by BevapDin** [comment]
> The killer for me is validating it, I'm not even sure where I'd start to check that nothing was lost, or that nothing gets lost in a merge going forward.

Well, I just put back the original vehicles.json file from the separate files in d87403575819164484929d252b01f31af413a9c7 (just moved the text back, keeping the preexisting order) and that file matches the vehicles.json file from d1da6700da137e48a6f198a36680006bc7ce57bc exactly, so the new files have (in sum) the very same content as the original file.

Starting the game works as well, the debug menu lists the same amount of vehicles in either case, albeit in a different order (the vehicle prototype map is unordered).

**Comment by KiwiTrinsic** [comment]
If it causes too much trouble or people prefer it the old way, the PR can always be closed. The only reason I didn't open an issue ticket to discuss it first was because it only took a few minutes to put together anyways. :)

**Pull request merged**
