### PR TITLE
Expands vehicle water purification, ad-hoc with funnels

### LINKED ISSUE #18815: Generic tanks, purification and funnels: UI hassle
http://smf.cataclysmdda.com/index.php?topic=13464

Purifier now keeps water stored in the same tank. This tank is most likely the one under the funnel.
This means that you have to manually transfer the clean water to a separate tank if you want to keep funnel working.

Part of it could be fixed by allowing purifiers to be activated and making them clean the water before depositing, without intermediate stage of storing dirty water. This would allow funnels over clean water tanks to work.

### PR DESCRIPTION
**Pull request by Toothspit**
Fixes #18815
Implements the suggestion in #19448, probably not a total fix. Also suggested by BrainDamage in IRC, to thunderous applause.

**Wot this does:**
- Adds a default hotkey in the vehicle control menu, `p` to toggle purifiers on/off.
- Water purifiers can be set to run continuously. They will auto-purify water in the tanks they're sitting on and collected rainwater will be cleaned. This includes the FOODCO, because apparently it does everything not related to cooking food.
- Funnel + water purifier + tank = clean rainwater source in exchange for vehicle battery.
- Rainwater funneled to clean water tanks contaminates it to regular water if battery power is insufficient and/or there is no purifier on the tile (this does affect existing deathmobiles).

**Wot this does not:**
- Adjust the absurdly-low power usage of purifiers.
- 'Lock' a tank to a specific liquid, nor allow liquid relocation, as in the rest of #19448.
- Get rid of the water purifier part's existing functionality.

### CODE REVIEW

**Comment by pisskop** [comment]
does dirty water still require a vehicle container dedicated to it if its on auto-run?

**Comment by Toothspit** [comment]
Dirty water will stay dirty unless there's a purifier on the tile. Dirty water will be cleaned if there's a purifier on the tile, if there's enough power and the tank is under a funnel. If there isn't enough power and the tank is under a funnel, rain will make the clean water dirty.

**Comment by Night-Pryanik** [comment]
> Rainwater funneled to clean water tanks contaminates it to regular water if battery power is insufficient and/or there is no purifier on the tile (this does affect existing deathmobiles).

Now we need some sort of deactivable funnel to prevent this sort of contamination without removing the funnel.

**Comment by Xpyder** [comment]
also related to #7075

**Pull request merged**
