### PR TITLE
Updates to C.R.I.T Expansion

### PR DESCRIPTION
**Pull request by Soupster89**
#### Summary
SUMMARY: Mods "Balances and description changes"```

#### Purpose of change
Decluttering of item descriptions and balance of items.

#### Describe the solution
Take out redundant text and descriptions. Nerf multi stat ratios and base costs on techniques,

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Will you resolve conflicts?

**Comment by Zireael07** [comment]
'Pen' is probably penalty, but no idea what AR is?

**Comment by AMurkin** [comment]
> so what is the 'arpen' in
> ` +1 armor. STR provides accuracy and minor bash damage and arpen.`
> ~ Description of buff 'C.R.I.T Guard' for martial art 'C.R.I.T Enforcement'

Armor penetration?

**Comment by kwl01skz** [comment]
> Armor penetration?

Cool! Thank you

**Comment by ZhilkinSerg** [comment]
It has MAJOR conflicts. Will you resolve them?

**Comment by Soupster89** [comment]
I am horribly sorry, this wasn't supposed to be kept open.

**Pull request closed without merging**
