### PR TITLE
Vanilla NPCs do not rely on your bank account anymore

### LINKED ISSUE #75433: Hub01 Doc cannot install bionics if you have bank debt
### Describe the bug

I tried to install bionics at the Hub01 Bar doctor and none of the useful dialogue popped up, have both anesthesia kit and bionics in my inventory.
it starts working once you put money in your bank account and get rid of your debt

### Attach save file

[Valley Forge-trimmed.tar.gz](https://github.com/user-attachments/files/16484363/Valley.Forge-trimmed.tar.gz)

### Steps to reproduce

!. talk to the Doc
2. choose "Could you help me with some bionics?"
3. no install dialogue pops up
4. put all your money in a conveniently placed ATM
5. it works

### Expected behavior

I expected to be able to install my bionics

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-07-28-0227 bfeb1ff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #75433
#### Describe the solution
Repalce all instances of manipulation with cash (aka your bank account) and `npc_service` with `u_has_items` and `u_consume_item`
~~After some lore discussion, remove tacoma ability to install/uninstall bionic, and make custom bionic dialogue to reflect that they have no idea about bionic at all~~ moved to #75463
#### Testing
image
#### Additional context
augustmoon is intentionally left unchanged because aftershock uses bank account; just fixed them not using $, but HGC in message

### CODE REVIEW

**Review by RenechCDDA — DISMISSED** [review]
>After some lore discussion, remove tacoma ability to install/uninstall bionic, and make custom bionic dialogue to reflect that they have no idea about bionic at all

You absolutely should separate this out from the $$$ changes.

**Comment by RenechCDDA** [comment]
Yeah so the service checks are good to get rid of, but I'm not happy with how the dialogue options are hidden when not meeting the condition. I think it would be better to move the condition into a [dynamic line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#dynamic-lines). I realize this is a bunch more work than the simple bugfix, but if you're up for it.

**Comment by GuardianDll** [comment]
But `dynamic_line` is what NPC says to you, not what you can say to them

**Comment by RenechCDDA** [comment]
> But `dynamic_line` is what NPC says to you, not what you can say to them UPD: you probably mean to replace `text` with `dynamic_line`, but i am still a bit confused how it would work? Do you mean some greyed out option so it is visible you do not have the money? i miss how simple `text` -> `dynamic_line` would solve it
> 
> The only potential way i see to solve it is to duplicate the responses with opposite check, that show something like `<color_red>[4 HGC]<\color> Sorry, have no money.`, but that sound a tad different from what you are talking

Sorry I thought it was possible to branch the actual dialogue **and effect** depending on the condition, using dynamic lines. If this isn't correct then just ignore what I said

**Pull request merged**
