### PR TITLE
Jsonify police station and add a new variant

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Moved police station mapgen to json and added another variant."```  

#### Purpose of change
To allow changeable police station mapgen.

#### Describe the solution
Added a police station mapgen in json with a handful of tweaks here and there. Removed `mapgen_police` function from `mapgen_functions.cpp`.
Also added a new variant with brick walls and a chance to spawn police car.

#### Additional context
Default variant
default

New variant with brick walls and a police car
default

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Nice!

**Comment by Night-Pryanik** [comment]
Working on a second variant right now.

**Comment by Mecares** [comment]
In  my experience the loot in the locked area is disappointing, maybe a slight increase in item spawn there would be a good idea.

**Comment by Night-Pryanik** [comment]
> locked area

Supply room or evidence locker?

**Comment by Mecares** [comment]
The evidence room, it creates an expection of at least some useful loot due to its increased security measures.

**Comment by Night-Pryanik** [comment]
@Mecares it's `cop_evidence` item group. It contains mostly not so useful stuff. Increasing spawn of items from this group won't help much IMO.

**Comment by Inglonias** [comment]
This hadn't been done yet? Wow.

**Comment by I-am-Erk** [comment]
Can the new version have an upstairs to expand z-level usage?

**Comment by Night-Pryanik** [comment]
Well, why not. But that will also require adding second floor?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Well, why not. But that will also require adding second floor?

That is what he has meant: "upstairs" not as a ladder, but as an additional floor.

**Comment by Night-Pryanik** [comment]
I never worked with z-level floor before, I need to look on how are they implemented. Though I'd prefer to make this in other PR in order not to overweight this one with features. It began only as a jsonify, you know.

**Comment by ZhilkinSerg** [comment]
Sure, that's a fair point - I am also prefer this PR in its current state and expand this and other citty buildings to several z-levels later.

Example of multistory building is `house_2story_base`. Basically you need to create `overmap_terrain` and `mapgen` for each floor , then combine several overmap terrains in `city_building`, which is like `overmap_special`, but has some limitations (e.g. x/y dimensions should be 1x1) and also doesn't contribute to overmap specials limit total.

Use following files as a guide:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/multitile_buildings_terrain.json

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/multitile_city_buildings.json

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/house/house_2story.json

**Comment by ZhilkinSerg** [comment]
Maybe add some benches here:

default

**Comment by Night-Pryanik** [comment]
> Maybe add some benches here:

Will do.

**Comment by ZhilkinSerg** [comment]
Merged to `0.D`.

**Pull request closed without merging**
