### PR TITLE
Revert "Simplify generic factory"

### PR DESCRIPTION
**Pull request by Coolthulhu**
Reverts CleverRaven/Cataclysm-DDA#19108

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I'm going to sleep in a moment. If no one tells me to wait, I'm merging it to fix #19135

**Comment by mugling** [comment]
Correct decision. Cursory look doesn't suggest any obvious fixes so will look into it further after the weekend.

**Comment by DangerNoodle** [comment]
@chaosvolt had already verified that martial art overrides do in fact function.

**Comment by mugling** [comment]
Two problems:

* Deferred loading of `copy-from` isn't yet supported for that type having been reverted out in this PR. This leads to a particular nasty bug where the validity of your JSON would depend on load order - for example if you renamed a file your JSON may suddenly stops working. A nasty bug for a future maintainer to waste hours tracking down.

* Other inheritance syntax such as `extend`, `delete`, `proportional` etc aren't yet functional for that type. They'll pass linting though and not result in JSON load errors meaning you can specify invalid JSON that appears correct but actually does nothing. Again this information wouldn't be available to a future maintainer.

> @chaosvolt had already verified that martial art overrides do in fact function.

You remain responsible for testing your own PR's and whilst there are no written rules I'd discourage you from submitting them on behalf of others because there's always a risk of being drawn into others disputes

**Comment by DangerNoodle** [comment]
I did test it myself as well. The martial art overrides as expected, and the weapons being added by 'extend' show up on the weapon list.

In fact it was my initial proposal to use that method of making the martial art override less clunky, tested it, then Chaosvolt adopted it and verified it works via their own testing.

````
[
  {
    "id": "style_silat",
    "copy-from": "style_silat",
    "type": "martial_art",
    "name": "Silat",
    "extend": { "weapons": ["bloodscourge", "scourge_staff", "spear_pestilence"] }
  },
  {
    "id": "style_fencing",
    "copy-from": "style_fencing",
    "type": "martial_art",
    "name": "Fencing",
    "extend": { "weapons": ["sun_sword", "sun_sword_on"] }
  },
  {
    "id": "style_niten",
    "copy-from": "style_niten",
    "type": "martial_art",
    "name": "Niten Ichi-Ryu",
    "extend": { "weapons": ["bloodscourge", "scourge_staff"] }
  }
]
````

Did you actually test these?

**Comment by mugling** [comment]
Some of the fields will support that syntax and some will not. The type needs migrating to use `assign` and appropriate finalization adding before such constructs can be used. Such changes are otherwise brittle and result in hard to debug problems when you move a JSON definition between files and the inheritance suddenly breaks

**Comment by DangerNoodle** [comment]
Peculiar. That said, it still works as intended at present.

**Comment by mugling** [comment]
That's called undefined behavior. It's a special form of evil. Things happen to work but break spectacularly without warning when you make seemingly unrelated changes.

**Comment by DangerNoodle** [comment]
I see. I am saddened that the mod has been obsoleted, but so be it. Your doing so after Coolthulhu voiced a dissenting opinion does seem a bit off-putting though.

**Comment by mugling** [comment]
This isn't Q&A. The mod that obsoletes the PR sets out the reasons and you can continue the discussion in the forum post linked to it.

**Comment by DangerNoodle** [comment]
I do not have any desire to post on the forums, given my experiences lurking on it.

**Pull request merged**
