### PR TITLE
Fixed lucern hammer spelling

### PR DESCRIPTION
**Pull request by DanteTorn**
#### Summary

SUMMARY: Bugfixes "Fixed lucerne hammer spelling"

#### Purpose of change

Lucerne hammer is spelled with an E, and even the third Google result will show the CDDA entry when searching "lucern hammer." The ingame name should probably reflect the real-life counterpart is takes after.

#### Describe the solution

I've renamed the item name, but not the item ID.

#### Describe alternatives you've considered

I was originally going to change the item ID as well to the proper spelling, but it might mess with peoples' saves or have some unforseen consequences I don't know about, so I left that part be.

#### Additional context
image
- - - -
image

### CODE REVIEW

**Comment by KorGgenT** [comment]
your summaryline is incorrect: ```SUMMARY: Bugfixes "Fixed lucerne hammer spelling"``` would be a correct summaryline.

**Comment by DanteTorn** [comment]
> 
> 
> your summaryline is incorrect: `SUMMARY: Bugfixes "Fixed lucerne hammer spelling"` would be a correct summaryline.

Thanks, fixed it.

**Comment by I-am-Erk** [comment]
Unfortunately the item ID will probably be stuck like this forever. You could change it and make a second item called 'lucern_hammer' that just copies from 'lucerne_hammer', but there's a high risk for unexpected and annoying little complications. I don't think items support multiple ID aliases.

**Comment by DanteTorn** [comment]
> 
> 
> Unfortunately the item ID will probably be stuck like this forever. You could change it and make a second item called 'lucern_hammer' that just copies from 'lucerne_hammer', but there's a high risk for unexpected and annoying little complications. I don't think items support multiple ID aliases.

In my opinion, this isn't too big of a deal. There's plenty of strange IDs for stuff like quarterstaffs having the ID of "q-staff" of all things.

**Pull request merged**
