### PR TITLE
Add myself to CODEOWNERS for clang-tidy stuff

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
None

#### Purpose of change
I'd like to be notified for changes related to `clang-tidy` (and some other stuff in `tools`).

#### Describe the solution
Add myself to `CODEOWNERS` for those.

### CODE REVIEW

**Comment by BrettDong** [comment]
I believe your account has to be a member of the organisation for CODEOWNERS to work.

**Comment by anothersimulacrum** [comment]
I think you specifically need write access to branches (e.g. more than just triage).

**Comment by ZhilkinSerg** [comment]
@kevingranade should they be added to maintainers team in organization then?

**Comment by NetSysFire** [comment]
#56802

**Pull request merged**
