### PR TITLE
Propane parts

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Propane vehicle parts"

#### Purpose of change
Now that propane is in, we should be able to use it for things like barbeques, grills, and RV kitchens.

#### Describe the solution
Adds XL tank for furniture or vehicle use.
Adds gas cooker vehicle part.
Adds flag "GAS_TANK".
Updates propane tools to use flag instead of item list.

#### Describe alternatives you've considered
None.

#### Testing
Made simple vehicle, installed kitchen unit and propane tank, made popcorn. Removed kitchen unit, installed gas cooker, made more popcorn.

### CODE REVIEW

**Comment by Drew4484** [comment]
> You still can't move propane around between containers right?

I've adjusted the containers to allow that now.

**Comment by Shodan14** [comment]
> > You still can't move propane around between containers right?
> 
> I've adjusted the containers to allow that now.

So there's equipment that allows this that would still feasible work post-apocalypse? My understanding is that for the storage to be worth anything the propane needs to be highly compressed.

**Comment by Drew4484** [comment]
> > > You still can't move propane around between containers right?
> > 
> > 
> > I've adjusted the containers to allow that now.
> 
> So there's equipment that allows this that would still feasible work post-apocalypse? My understanding is that for the storage to be worth anything the propane needs to be highly compressed.

All it would need is a compressor pump and a power source, it could work like the siphon action, but that's a very complicated change. That would be more realistic but also needs new systems added.

**Comment by Shodan14** [comment]
> > > > You still can't move propane around between containers right?
> > > 
> > > 
> > > I've adjusted the containers to allow that now.
> > 
> > 
> > So there's equipment that allows this that would still feasible work post-apocalypse? My understanding is that for the storage to be worth anything the propane needs to be highly compressed.
> 
> All it would need is a compressor pump and a power source, it could work like the siphon action, but that's a very complicated change. That would be more realistic but also needs new systems added.

Ok, but that pump is presumably not man-portable? You shouldn't be able to run around and siphon a bunch of propane to your jerrypack.

**Comment by Drew4484** [comment]
> > > > > You still can't move propane around between containers right?
> > > > 
> > > > 
> > > > I've adjusted the containers to allow that now.
> > > 
> > > 
> > > So there's equipment that allows this that would still feasible work post-apocalypse? My understanding is that for the storage to be worth anything the propane needs to be highly compressed.
> > 
> > 
> > All it would need is a compressor pump and a power source, it could work like the siphon action, but that's a very complicated change. That would be more realistic but also needs new systems added.
> 
> Ok, but that pump is presumably not man-portable? You shouldn't be able to run around and siphon a bunch of propane to your jerrypack.

Properly, we would need to define which tanks store gas vs. the ones that store LPG, and then the target pressure for each tank based on what it contains. The appropriate pumps for these would not be small, but could still be portable. Pumps of that nature, especially for liquids, might be nice to add for reloading large vehicle tanks with water rather than just using a hose. I'm not intending to add that level of infrastructure, this PR will simply make the tanks exist for my purpose of having a gas forge for working steel.

**Comment by Shodan14** [comment]
Sounds good. I'm just lobbying to not be able to move propane around when the required infrastructure is not implemented. This just means you'll have to pick it up in whatever containers it comes in and makes it a bit more of a logistic challenge.

**Comment by ISuckM8** [comment]
Propane torch?!?!

**Comment by Drew4484** [comment]
> Propane torch?!?!

Just for you! https://github.com/CleverRaven/Cataclysm-DDA/pull/54557/commits/fd14d39950531bdd54b766320cb3ebfa1ffcedcd

**Pull request merged**
