### PR TITLE
1911 mag size fix

### PR DESCRIPTION
**Pull request by nopenoperson**
#### Summary
fixed 1911 magazines so they they fit where they should and dont take up too much or too little space

### CODE REVIEW

**Comment by ANickelN** [comment]
1911 magazines are not that large.  The 7 round magazine value is correct from a brief look, and the 10 round magazine needs to be adjusted to a bit more than the 7 rounder.  I'm currently working on this at https://github.com/CleverRaven/Cataclysm-DDA/pull/60038
if you have real life values you'd like to contribute.

**Comment by nopenoperson** [comment]
> 1911 magazines are not that large. The 7 round magazine value is correct from a brief look, and the 10 round magazine needs to be adjusted to a bit more than the 7 rounder. I'm currently working on this at #60038 if you have real life values you'd like to contribute. I've been taping magazines shut and using water displacement to determine their volume, or in cases of magazines I don't own, using measurements available from patents or other information online.

my fix is fairly consistant with the rest of the game. changing everything to real life values will break a lot of stuff it seems.  7rd magazines being 61mm lets fit them in many  places where they shouldnt.

**Comment by ANickelN** [comment]
> > 1911 magazines are not that large. The 7 round magazine value is correct from a brief look, and the 10 round magazine needs to be adjusted to a bit more than the 7 rounder. I'm currently working on this at #60038 if you have real life values you'd like to contribute. I've been taping magazines shut and using water displacement to determine their volume, or in cases of magazines I don't own, using measurements available from patents or other information online.
> 
> my fix is fairly consistant with the rest of the game. changing everything to real life values will break a lot of stuff it seems. 7rd magazines being 61mm lets fit them in many places where they shouldnt.
Then you fix the things that are broken, not keep it messed up so that everything is consistently messed up.

**Comment by nopenoperson** [comment]
More experienced contriubutors than me  should do the changes that break stuff. This is just a small change to these items to bring them a bit closer to reality while letting them play better with the rest of the game

**Comment by ANickelN** [comment]
Changing the volume of a 1911 mag to 250ml for some reason is not bringing the game closer to reality.  Your longest_side value looks about right, which is great, but I have no idea why you're changing the volume from what it actually is.

**Comment by nopenoperson** [comment]
i did some napkin math and its closer to 150ml right?

**Comment by ANickelN** [comment]
No, the listed value of 61ml seems to be correct based on my work with other magazines thus far.  If you want to discuss this further without the back and forth on Github feel free to reach out to me on the Discord, my username is similar there.

**Pull request closed without merging**
