### PR TITLE
Migrate more guns to item drops

### PR DESCRIPTION
**Pull request by mugling**
Adds no new magazines and is mostly straight normalization and migration with three exceptions:
- Survivor special 700 is moved to `obsolete.json`. It wasn't craftable, has a single extremely rare (almost never) spawn and we already have the alternative 3006 pipe rifle
- Lever shotgun is moved to `obsolete.json`. It was a near duplicate of revolver shotgun and that was a more interesting item. In the case of the latter a future PR could extend the crafting code to allow recipes that specify item `groups` so that the requirements could include a revolver.
- Survivor carbine now uses the craftable 223 magazines (and will come loaded with one) and has more limited `modifications`. Previously it was too good for the early game but by the time you reached the crafting requirements it was effectively useless.

### CODE REVIEW

**Comment by vache** [comment]
I think survivor special is a guaranteed? spawn in the abandoned farm.

**Comment by mugling** [comment]
@vache fair enough, I'll update that

**Comment by kevingranade** [comment]
> Lever shotgun is moved to obsolete.json. It was a near duplicate of revolver shotgun and that was a more interesting item.

The problem with this is that IRL lever-action shotguns, while rare, are not extraordinarily so, but revolver shotguns are almost unheard-of.

In general, I don't consider "too similar to another item stat-wise" to be a good reason to remove an item.

**Comment by Rivet-the-Zombie** [comment]
Agreed, we should keep the lever-action shotgun.

**Comment by mugling** [comment]
See d0294d7 which adds item drops for the lever shotgun

**Pull request merged**
