### PR TITLE
Hear No Evil, Speak No Evil

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Content "Adds the AudioVox CBM as well as the WearMan CBM, the first transforming CBM."

#### Purpose of change
In #76177, Kevin removed the music action from the Integrated AR System CBM, which never should have had it in the first place. That did, however, open up a niche for a CBM that could actually play music. Originally, I was going to add radio cat ears, but then I looked to Cyberpunk for inspiration, and came across the CBMs that are being implemented here. 

#### Describe the solution
The AudioVox is essentially a vocal synthesizer. It makes your voice louder; very, very much louder.   The WearMan functions as a combination MP3 Player and Radio, allowing you to effectively listen to broadcasts without lugging one around. It transforms like the HUB Scout Headgear to facilitate this.

#### Describe alternatives you've considered
Cat Ear CBM

#### Testing
Screenshot 2024-09-04 153134
Screenshot 2024-09-04 153017
Screenshot 2024-09-04 153000

#### Additional context
Thank you GuardianDLL for letting me bounce ideas off of you, as well as your contributions to the community! This should also help with #73889

### CODE REVIEW

**Comment by GuardianDll** [comment]
few things: i think it would be better to use `upgraded_bionic`, `included_bionics` and `available_upgrades` with infolink, so infolink (gives radio) would be given automatically with this mp3 thingy
also speaking in vocoded should not give you any major advantage (nor disadvantage) in talks. `social_modifiers` should be removed

**Comment by DukePaulAtreid3s** [comment]
> also speaking in vocoded should not give you any major advantage (nor disadvantage) in talks. `social_modifiers` should be removed

The Vocoded part is merely a part of it, the social effect comes from the ability completely and effortlessly change the natural sound of your voice, being able to imitate the effects of CROAKY VOICE and GROWLING VOICE

**Comment by fairyarmadillo** [comment]
I agree with GuardianDLL about the vocoder. CBM tech is scary and ugly and not good for finessing terrified survivors.

**Comment by DukePaulAtreid3s** [comment]
> I agree with GuardianDLL about the vocoder. CBM tech is scary and ugly and not good for finessing terrified survivors. There's also already a CBM that gives you a robot voice, so it's redundant anyway.
So to be clear, social buffs are outside of CBMs intended spheres?

**Comment by DukePaulAtreid3s** [comment]
> few things: i think it would be better to use `upgraded_bionic`, `included_bionics` and `available_upgrades` with infolink, so infolink (gives radio) would be given automatically with this mp3 thingy also speaking in vocoded should not give you any major advantage (nor disadvantage) in talks. `social_modifiers` should be removed

Done!

**Comment by DukePaulAtreid3s** [comment]
Basic build “passed” but the test crapped itself, redo

**Comment by GuardianDll** [comment]
`(continued from above) ERROR : src/bionics.cpp:539 [static void bionic_data::check_bionic_consistency()] Bionic bio_radio (included by bio_mp3) consumes slots, those should be part of the containing bionic instead.`

**Comment by ashGlaw** [comment]
Is the music played by this CBM audible by others, or is it silent?

**Comment by Maleclypse** [comment]
I think this makes sense.  It's obviously a commercial item that Exodii have scavenged and never bothered to change the user manual on.  Fantastic :)

**Pull request merged**
