### PR TITLE
Scorched zombie child name/color change

### PR DESCRIPTION
**Pull request by pisskop**
Kind-ling
and kinder-ling

and then changes color to match the grownup scorched zombie

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I really like 'kinderling', but 'zombie kindling' sounds more like some sort of object than a creature. Also, I've never heard of a plural that works like that.

I'd like to suggest using 'zombie kinderling/kinderlings'.

**Comment by Coolthulhu** [comment]
> Also, I've never heard of a plural that works like that.

German has plural like that.
Child -> Kind
Children -> Kinder

**Comment by pisskop** [comment]
Im okay with kinderling(s), its just more of a pun if singular is kindling.

**Comment by Rivet-the-Zombie** [comment]
>German has plurals like that.

Not in the middle of the word like that; it goes on the end.

**Comment by pisskop** [comment]
Its germlish, so no suprises.

**Comment by Zireael07** [comment]
Kinderling > kindling, definitely.

The -(l)ing suffix for kids is an OE (Old English) thing. Hatchling, definitely. Aetheling. Yngling.

**Pull request merged**
