### PR TITLE
Fixed bionic sniper having no generator

### LINKED ISSUE #23612: Bionic Sniper should have a way to recharge
Game version: 0C-7349

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Default (none)

### Expected behavior
Bionic Sniper profession used solar panels CBM to recharge bionic power. After solar panels CBM was removed in #23317 Bionic Sniper profession has lost the ability to recharge. Solar panels CBM has been removed in 224d624e928f2a80d7421ee760d97cf7050d68ff but not replaced with a different recharge method.

### Actual behavior
Bionic Sniper can not recharge

### Steps to reproduce the behavior
Start a new game as a Bionic Sniper. Exhaust all bionic power. Wait for sunny or clear weather.

### PR DESCRIPTION
**Pull request by NotFuji**
closes #23612

Gave him an internal furnace so he can eat sticks and such while sniping out in the wilderness.

### CODE REVIEW

**Comment by Cyrano7** [comment]
Maybe adding Joint Torsion Ratchet is a better fix? As suggested by @ZhilkinSerg in that issue. Internal furnace can generate a LOT of power.

**Comment by Mecares** [comment]
Torsion Ratchet does not seem that well fitting considering how much time snipers spend waiting motionless.

**Comment by ZhilkinSerg** [comment]
> Torsion Ratchet does not seem that well fitting considering how much time snipers spend waiting motionless.

Neither smoke from the furnace or glare from solar panels

**Comment by NotFuji** [comment]
Metabolic maybe?  Really, none of them make sense.  He'd do better as a plant mutant, but that probably doesn't go well with the rest of the _normal_ professions.

But I feel like a profession shouldn't get scrapped just because one of their items got removed.

**Comment by BorkBorkGoesTheCode** [comment]
Battery System bionic maybe?

**Comment by BorkBorkGoesTheCode** [comment]
Jenkins, rebuild please.

**Comment by kevingranade** [comment]
Merged, but a rebase confused github.

**Pull request closed without merging**
