### PR TITLE
Use strings for rotatable symbols, land use code and overmap terrains symbols

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Infrastructure "Use string instead of long for rotatable symbols, land use code and overmap terrains symbols"```

#### Purpose of change

Allow using string instead of long for rotatable symbols, land use code and overmap terrains symbols.

#### Additional context

Include changes from #29205.

Symbols are stored as `uint32_t` internally and can be returned as string via `get_symbol` function.

No visible changes for player right now, but I plan to use more Unicode characters for overmap terrains in follow-up pull requests to make map look like this:

image

It is still possible to use number instead if string in `sym` node for overmap terrain definitions (for third-party mod compatibility), but these overmap terrains will be reported in `debug.log` as following:

```
14:11:13.659 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: mall_a_10_roof (open air)
14:11:13.659 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: mall_a_19_roof (open air)
```

Also non-abstract terrains without `sym` defined will be reported in the `debug.log`:

```
14:28:43.523 ERROR MAP_GEN : sym is not defined for overmap_terrain: house_prepper (house)
14:28:43.523 ERROR MAP_GEN : sym is not defined for overmap_terrain: duplex (duplex)
14:28:43.523 ERROR MAP_GEN : sym is not defined for overmap_terrain: s_gas (gas station)
14:28:43.523 ERROR MAP_GEN : sym is not defined for overmap_terrain: s_pharm (pharmacy)
14:28:43.523 ERROR MAP_GEN : sym is not defined for overmap_terrain: office_doctor (doctor's office)
14:28:43.524 ERROR MAP_GEN : sym is not defined for overmap_terrain: office_cubical (office)
14:28:43.524 ERROR MAP_GEN : sym is not defined for overmap_terrain: s_grocery (grocery store)
14:28:43.524 ERROR MAP_GEN : sym is not defined for overmap_terrain: s_grocery_roof (grocery store roof)
14:28:43.524 ERROR MAP_GEN : sym is not defined for overmap_terrain: s_grocery_1 (grocery store)
````

Overmap terrains with `LINEAR` flag and no`sym` defined wont' be reported as their drawing symbol is define by different means. Abstract overmap terrains without `sym` defined wont' be reported either.

### CODE REVIEW

**Comment by Photoloss** [comment]
As with previous map changes can you *please* preserve the orientation telegraph? This is a very useful feature for the tiles that do support it and removing it from houses would be a major annoyance.

**Comment by ZhilkinSerg** [comment]
> 
> 
> As with previous map changes can you _please_ preserve the orientation telegraph? This is a very useful feature for the tiles that do support it and removing it from houses would be a major annoyance.

Rotatable symbols aren't getting removed and still can be used when necessary.

**Comment by Photoloss** [comment]
> Rotatable symbols aren't getting removed and still can be used when necessary.

The houses in your preview all face upwards and you don't seem to have Land Use Codes or other relevant overlays enabled hence the concern.

**Comment by ZhilkinSerg** [comment]
That is nothing, but an example of possible outcome and doesn't represent the final form.

**Comment by codemime** [comment]
`std::string` is an overkill for this purpose. It's fine for serializing/deserializing, but what you really want for storing a Unicode character, if you don't like it to be `long`, is either `std::wstring::value_type` (which is `w_char`) or `uint32_t`.

Cons of using `std::string`:
-The requirement for it to represent exactly one character is not enforced (the string can be anything really);
-Waste of memory/performance for no reason.

**Comment by ZhilkinSerg** [comment]
> 
> 
> `std::string` is an overkill for this purpose. It's fine for serializing/deserializing, but what you really want for storing a Unicode character, if you don't like it to be `long`, is either `std::wstring::value_type` (which is `w_char`) or `uint32_t`.
> 
> Cons of using `std::string`:
> -The requirement for it to represent exactly one character is not enforced (the string can be anything really);
> -Waste of memory/performance for no reason.

I totally agree we should use something else than string internally and I just didn't made there yet.

**Comment by kevingranade** [comment]
AFAIK using ``uint32_t`` is the least likely to cause problems.
long is not guaranteed to be long enough on all platforms.
w_char has weird baggage based on the string implementation.

**Comment by ZhilkinSerg** [comment]
> 
> 
> AFAIK using `uint32_t` is the least likely to cause problems.
> long is not guaranteed to be long enough on all platforms.
> w_char has weird baggage based on the string implementation.

Yes, we already using `uint32_t` to store Unicode codepoints in `catacharset.cpp`, so I will stick to it.

**Comment by ZhilkinSerg** [comment]
`uint32_t` migration for `land_use_code` and `oter_type_t` should be done now, but there are more things left to be improved in the future (e.g. `std::string rotate_symbol( const std::string &sym, type dir );` could be changed to use `uint32_t` too).

**Comment by kevingranade** [comment]
Is there any possible way to convert from legacy numeric values to strings? I really want to merge this, especially since it's going to bitrot extraordinarily fast, but I also don't want to break every mod that is currently doing the right thing.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Is there any possible way to convert from legacy numeric values to strings? I really want to merge this, especially since it's going to bitrot extraordinarily fast, but I also don't want to break every mod that is currently doing the right thing.

Yes, there are should be some ways - I will look into this.

**Comment by jbytheway** [comment]
> Yes, we already using `uint32_t` to store Unicode codepoints in `catacharset.cpp`, so I will stick to it.

Just want to point out that there is also `char32_t` which is intended for this sort of thing.  https://en.cppreference.com/w/cpp/keyword/char32_t

**Pull request merged**
