### PR TITLE
Various tweaks

### LINKED ISSUE #17119: Missing WRENCH level 2
Braethias recently said the belt fed mod requires WRENCH level 2, but none of the tools have this tool quality.

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add hammering 3, fine hammering 1 and chisel 3 qualities to basic repair kit, also make its' recipe reversible.
2. Add 1 screw driving, 1 bolt turning, 1 metal sawing, 3 hammering qualities to firearm repair kit, and allow using it instead of soldering iron for crafting. Not sure if gunsmith repair kit should have these qualities too, as it may contain more specialized tools which are unsuitable for generic tasks.
3. Change belt feed adapter recipe to use bolt turning quality of 1, as there are no items with bolt turning 2 quality. (Fixes #17119)
4. Add pot qualities to pot helmet.
5. Add "TRADER_AVOID" flag to all obsolete items.
6. Combine exploding arrowhead and exploding arrow recipes. This makes exploding arrowhead obsolete. Also make it possible to craft just one exploding arrow instead of 5 at a time.
7. Add FIRE_TWOHAND flag to slingshot, brace slingshot and spraycan flamethrower.
8. Remove duct tape from spraycan flamethrower recipe. You don't really have to connect lighter and spray can together, you can just hold them separately as needed.
9. Remove gunmod slots from spraycan flamethrower.
10. Add steel to RPG-7 materials, so that it can't be cut up for skewers.
11. Add COOKOFF effect to exploding arrow, hydrogen (putting a canister of super-compressed flammable gas in a fire is not a good idea), .50 BMG API, signal flare, modified mininuke, 20x66mm flare, 20x66mm incendiary.
12. Remove COOKOFF effect from 12mm projectiles and remove powder from its' elements. It's just a metallic projectile, fire is not supposed to affect it.
13. Add ALWAYS_TWOHAND flag to bionic claws.
14. Remove ALWAYS_TWOHAND flag to camera pro. Even if it can only be used with two hands, it shouldn't prevent someone from simply carrying it with one hand.

### CODE REVIEW

**Comment by illi-kun** [comment]
I guess you heard that many times before but I need to say it again: (almost) every change from your list should be done in separate PR.

**Comment by Darkyhard** [comment]
Actually, no. It happened only when I attempted to add something new and not related to other things or something very large .

**Comment by illi-kun** [comment]
The issue with this PR is changes are not related with each other, so merge condition is "all or nothing", which is not good.

**Comment by Darkyhard** [comment]
I can easily revert any of these changes if someone will prove that they are not needed.

**Comment by Rivet-the-Zombie** [comment]
>Add ALWAYS_TWOHAND flag to bionic claws.

So if the player were to have a crippled arm, wouldn't this prevent them from using the bionic claws on the other side as well?

**Comment by Darkyhard** [comment]
> So if the player were to have a crippled arm, wouldn't this prevent them from using the bionic claws on the other side as well?

Not sure if it really would do so, but it should, I think. Attempting to extend such claws if your arm's bones are not where they are supposed to be may lead to further damage to the arm.

**Comment by BorkBorkGoesTheCode** [comment]
The basic repair kit may be affected by the same problems mentioned in #16237

**Comment by BorkBorkGoesTheCode** [comment]
Some comments on Darkyhard's PR:

> Add 1 screw driving, 1 bolt turning, 1 metal sawing, 3 hammering qualities to firearm repair kit, and allow using it instead of soldering iron for crafting. Not sure if gunsmith repair kit should have these qualities too, as it may contain more specialized tools which are unsuitable for generic tasks.

^

> Change belt feed adapter recipe to use bolt turning quality of 1, as there are no items with bolt turning 2 quality.

Why not WRENCH_FINE?

> Add pot qualities to pot helmet.

I like this idea.



> Add FIRE_TWOHAND flag to slingshot, brace slingshot 

I like two-thirds of this idea.

> Remove gunmod slots from spraycan flamethrower.

> Add steel to RPG-7 materials, so that it can't be cut up for skewers.

I also like these ideas.

**Comment by Coolthulhu** [comment]
> The basic repair kit may be affected by the same problems mentioned in #16237

There may be future conflicts if #17058 is expanded to cover hammering or chiseling. But at the moment adding extra qualities to things won't make them gain iuses.

> Add COOKOFF effect to exploding arrow, hydrogen (putting a canister of super-compressed flammable gas in a fire is not a good idea), .50 BMG API, signal flare, modified mininuke, 20x66mm flare, 20x66mm incendiary.

> modified mininuke

Shouldn't cookoff in fire, melting (it's plastic) would be better than having it weakly "pop" and send shrapnel.

> Add ALWAYS_TWOHAND flag to bionic claws.

This will not work and even if it did, it wouldn't make too much sense.

**Comment by BorkBorkGoesTheCode** [comment]
@Darkyhard  Could you re-PR the RPG fix? Wooden RPGs are weird.

**Pull request closed without merging**
