### PR TITLE
Add recipe for tabi socks in Traditional Japanese Kimono

### PR DESCRIPTION
**Pull request by molkero**
#### Summary
```SUMMARY: Content "Add recipe for tabi socks in Traditional Japanese Kimono"```

#### Purpose of change
Add recipe for already existing item tabi socks in the book Traditional Japanese Kimono.

#### Describe the solution
Added recipe in ```data/json/recipes/armor/feet.json```

#### Describe alternatives you've considered
Let all the cyborg samurais continue their search for socks matching their outfit.

#### Testing
Spawned Traditional Japanese Kimono, tailoring to 2, crafted tabi socks.

#### Additional context
Tabi socks weigh a bit more than normal socks, added a bit of materials to cover that. Skill requirements are also higher because they are "better" socks.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
These and other specific cultural/religious garments are so niche that their recipes should probably be booklocked, even if they arent hard to make.

**Comment by molkero** [comment]
Something other than ```"book_learn"```?

**Comment by John-Candlebury** [comment]
Oh, never mind me. I must be going blind or something.

**Comment by molkero** [comment]
Would be nice if there was something to block learning them at character creation though.

**Comment by anothersimulacrum** [comment]
There is, add `"flags": [ "SECRET" ]`.

**Pull request merged**
