### PR TITLE
String stacking, volume consistency

### PR DESCRIPTION
**Pull request by chaosvolt**
Minor tweak for strings concerning their volume (or lack thereof, in the case of small strings).
1. Changed small strings and long strings into ammunition, allowing them
   to have volume and stacking to match up with that of short ropes. Using
   count of 1 should ensure that recipes and other things don't break.
   Value additionally altered to account for price being based off
   stack_size, not count.
2. Moved from melee.json to ammo.json.

### CODE REVIEW

**Comment by kevingranade** [comment]
The change itself is simple, but I have an intuition that it has a high
chance of breakage.  I'm trying to think of what needs to be tested with it.

**Comment by chaosvolt** [comment]
Hmm. I'm not sure what all might break. Using count of 1 should ensure that crafting it won't be changed, and it shouldn't affect appearance in item groups or reserved recipes...will double-check to make absolutely sure.

Additionally, it should even retain the same value per string, since I double-checked whether the price entry applies it based off count or stack size (turns out it was stack size).

If there's any other situations I should test, definitely suggest it. ^^"

**Comment by chaosvolt** [comment]
Correction, I'll double-check things after restarting and remembering to tell Avast not to Derpscreen my freshly-picked build of Cataclysm. >.<

**Comment by kevingranade** [comment]
Appreciate the extra checking.

**Comment by chaosvolt** [comment]
Ah, thank you. Still unsure if its original value is intended.

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
