### PR TITLE
Archery acuracy overhaul.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: BALANCE: "Bring Archery effective ranges in line with the rest of the weapons."

#### Purpose of change
Archery (bow, crossbow) effective range has been persistently ignored while firearm range has been adjusted to use a unified continuum of effective ranges.

#### Describe the solution
Add a set of effective range tests that place various archer loadouts on the same continuum as firearms, and tweak bow stats until they pass the tests.

#### Describe alternatives you've considered
IDK, this is the mechanism we use for this, I'm not aware of another reasonable approach.

#### Testing
Tests pass, also need to do some manual testing to insure that the in-game performance isn't misrepresented by the tests.

#### Additional Context
I'm leaning on a number of sources that all point to bow effective range of all kinds being around 100 meters, placing it in a similar range as most pistols and shotguns.
https://outdoortroop.com/how-far-can-a-compound-bow-shoot/

There are of course caveats, bowhunting has a particular emphasis on one-shot kills, and because of this (and the related practicality of losing your quarry entirely with a non-lethal hit), that effective range is depressed a bit more than similar figures for guns, who count a wounding hit as nearly as good as a kill rather than as a negative.
But in the other direction, you have the relative lack of velocity in an arrow or quarrel, a particularly fast firing bow or crossbow will launch an arrow at approximately 300 feet per second, not even counting slowdown during flight, that means that an arrow launched at a target 100m away is going to take a full second to arrive. If your target happens to be stationary, that's not too problematic, but if it's moving, possibly erratically, that renders that shot nearly impossible.  We can look into modeling this sort of thing explicitly in the future, but until then it makes sense to factor this effect into the effective range of these weapons in an ad-hoc way.

#### TODO
Not quite done here, I need to
- [x] Add crossbows to the tests.
- [x] At least consider factoring in arrow types in the test.
- [ ] Do some in-game sanity checks of various scenarios.
- [ ] Review the bow mods and see if anything is going to invalidate the tests.

### CODE REVIEW

**Comment by kevingranade** [comment]
Lolwhoops, an errant git push and this is on master.
Let me know if there's a problem...

**Comment by Ker-Nes** [comment]
It may have been gone a bit too far, as even with pretty high skill and good bows, accuracy stay a bit too low. At archery 6, a heavily modded high end bow only almost manage the same accuracy as a a pistol with skill level of 3, and absolutely _no_ mods. 

In addition, the bow mods also need some re-balancing as with the massive new bow dispersion, their changes to it barely make any difference.

**Comment by kevingranade** [comment]
Bow performance relative to pistols or other elements of the game is irrelevant, the question is does it represent how bows work.
I'm not inclined to do much with bow mods myself, give me an outline of what your expectations are with respect to how much they impact accuracy and some sources, and I can look into baking them into the tests.  Keep in mind it's zero-sum, the upper end of accuracy is what it is, and making bow mods better also means making them mandatory to reach the tested for effective ranges.

**Comment by Saint-of-Grey** [comment]
I feel like I should note this came up from me attempting and failing to make tests for my PR (#35971), and my discovery that a compound bow functioned like a high-end rifle. Any prospective balance that aren't dispersion related adjustments are included in that PR.

**Comment by Ker-Nes** [comment]
On the matter of related to pistols and the like, I don't mean in the sense of game balance, but in the sense of "weapons that should have similar accuracy". Assuming someone at skill level of 6 is a _highly_ skilled practitioner, if still not world class, it should have good well aimed accuracy, even without sight and mods, at ranges of up to 90m or so (target archery has an upper range of around that, and the bullseye of the target is even smaller than a human head, as far as great hits in game terms are concerned). As such, I'm taking other weapons that would have around that effective range, which would be thing like handguns and shotguns (firing slugs). I would say smoothbore muskets, but as I mentioned in #37203 , they probably need a change in how they are handled, too little dispersion, too little max range.

On the subject of ranges:
https://en.wikipedia.org/wiki/Target_archery
https://en.wikipedia.org/wiki/NRA_Precision_Pistol

And on the topic of bow mods: I don't know how much of a difference exactly they should make or how "obligatory" they should be at a high level, but as they are right now they became mostly irrelevant: A mod that reduces -20 dispersion for a weapon of over 1000 dispersion might is rather irrelevant. Since we know that they are used and archers feel those make _some_ difference at least, it's to be assumed that thus that their presence should make a noticeable difference, even if still relatively small.

**Comment by SeanMirrsen** [comment]
I'd argue against the comparison of equal skill levels for bows and pistols. The whole thing about why crossbows - and later firearms - ended up superseding bows in warfare, is because it takes a much higher level of skill to effectively shoot a bow, whereas it takes very little training to fire a crossbow, or a gun. Thus, even a relatively incompetent shooter would be able to score a hit against a target with a pistol - the pistol and the bullet's flat trajectory and near-instant hit time do most of the work for him. But it would take a much more competent bowman to match that accuracy.

**Comment by Ker-Nes** [comment]
I'm not comparing equal bow and pistol skill. I'm comparing lower pistol skill with considerably higher archery skill. That said, yes, they should have different skill to accuracy curves, with bow starting much lower but actually eventually topping out at a higher level (as noted above, target competition range for archery tops out at around 90m, while pistol target shooting seems to top out at some 45m (50 yards) or so).

**Pull request merged**
