### PR TITLE
Add more food recipes

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add recipes for sausage gravy, Mannwurst gravy, red sauce and canned human soup.

Also change description and materials of sausage gravy and Mannwurst gravy.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The gravy wursts are really hard to craft with milk being heavily limited right now.

**Comment by Darkyhard** [comment]
Well, some food items are just supposed to be heavily limited after the cataclysm, including milk. But you still could find some by scavenging powdered milk or canned condensed milk.

**Comment by Coolthulhu** [comment]
Why not go with the original description and make it a mushroom gravy instead?
That would make the recipe much more useful by not limiting it to rare drops.

**Comment by Coolthulhu** [comment]
The material still has "dairy"

**Pull request merged**
