### PR TITLE
Use sed to conditionally add tag strings to parallel execution

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
None

#### Purpose of change
With `--tagstring` added, the `github-action` error format no longer starts with `::error`, so github cannot extract the error messages.

#### Describe the solution
Use `sed` to insert tag strings to the start of the actual message.

#### Testing
image

14b277b: All builds correctly reported the json error.
0c4006e: Builds correctly marked as failed.

### CODE REVIEW

**Comment by actual-nh** [comment]
Would it be easier to put in the tagstring as previously, then move the `::(error|others)` to the beginning of the line?

**Comment by Qrox** [comment]
It might, but I've already sorted out how to do it (I think) so the only difference now is the length of the regex expressions.

**Comment by actual-nh** [comment]
> It might, but I've already sorted out how to do it (I think) so the only difference now is the length of the regexs.

I'm thinking it might work better on macOS - less quoting involved.

**Comment by Qrox** [comment]
It seems `sed` on macOS does not support back reference. I'm current trying `-E` to enable extended regex, and if that does not work I'll try using gnu sed.

**Comment by actual-nh** [comment]
> Seems to be working but not sure why some builds are not marked as failed.

Possibly it's picking up that the sed didn't return a nonzero status? Not sure why that wouldn't always happen, however.

**Comment by Qrox** [comment]
I suspect the problem is that `pipefail` is not set when `parallel` starts a separate bash process, so piping to `sed` masked the exit code of the unit test.

**Comment by Qrox** [comment]
Travis is using bash 4.3 which does not support the `@Q` variable expansion format. Is there a way to make travis use bash 4.4 instead?

**Pull request merged**
