### PR TITLE
Pack of firecrackers can be disassembled

### LINKED ISSUE #21370: Pack of firecrackers can't be disassembled
### Expected Behavior

Picking up a 'pack of firecrackers (25)' and (D)isassembling it should produce 25 firecrackers, 5 paper, 1 small string as per recipe. See: https://github.com/CleverRaven/Cataclysm-DDA/issues/56

### Actual behavior

"You can't unload a pack of firecrackers! You cannot disassemble this." They can however be assembled. As one of the few resources of gunpowder besides ammo itself, it'd make sense for a survivor to want to disassemble these and use the powder for handloading.

### Steps to reproduce the behavior

Put a pack of firecrackers on the table and karate-chop them as hard as you can. Repeat.

### PR DESCRIPTION
**Pull request by ituluwituluwzev**
Closes #21370

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Problem, however. You can cause firecrackers to have less than the full 25 charges via the use_action allowing you to not light off the entire pack.

**Comment by ituluwituluwzev** [comment]
I try to remove charge from pack of firecrackers, and make it use like single firecracker with louder explosion. What is the problem now? Any comment or advice is appreciated.

**Comment by DangerNoodle** [comment]
That would be the wrong approach. I will have to look into altering the hard-coded pack of firecrackers behavior so that the option to set off only a specific number of charges is removed, as this has been the limitation preventing this desired feature, and realistically packs of firecrackers are fused to go off in a constant series of pops.

**Comment by DangerNoodle** [comment]
I am presently compiling a pull request that changes the behavior of packs of firecrackers, which will make this a non-issue.

**Comment by DangerNoodle** [comment]
Tested, pull request is up. If you have any feedback, it would be desirable.

**Comment by ituluwituluwzev** [comment]
That's great!

**Pull request closed without merging**
