### PR TITLE
Export mapgen of playground/park and the two cabins to JSON

### PR DESCRIPTION
**Pull request by BevapDin**
One cabin used `map::make_rubble`, but inconsistent: a 2x2 area would be set to `f_rubble` directly, another 2 places adjacent would be set to rubble via the `make_rubble` function. I changed this to set all 6 squares to rubble via `make_rubble`. This means:
- terrain is destroyed (previously the 2x2 area would keep its terrain, leading to rubble embedded in a log wall)
- items (from destroyed terrain) on each of the 6 squares
- it may lead to addition rubble squares because some adjacent floor may collapse

I also used the monster group GROUP_ZOMBIE, which does contain non-standard zombies, previously only a few standard zombies had been spawned.

---

New mapgen features:
- rotation (used by the park): one can rotate the generated map, either randomly or by a fixed value. This should be useful for stuff that does not align with the surrounding (it could be added to the cabins), or for things like curved roads (only need one .
- allow calling `map::make_rubble` from JSON.

### CODE REVIEW

**Comment by vache** [comment]
What is the difference between the rotation mapgen.json member and the overmap_terrain.json rotate member?

**Comment by BevapDin** [comment]
> What is the difference between the rotation mapgen.json member and the overmap_terrain.json rotate member?

Overmap rotation generates 4 different overmap terrain from one json entry (which can have different symbols). The houses are implemented that way:
```JSON
{
        "type" : "overmap_terrain",
        "id" : "house",
        "rotate" : true,
        "sym" : [94, 62, 118, 60], <-- different symbols for each rotation.
}
```
The game makes that single JSON entry into 4 different overmap terrain types: house_north, house_west, house_south and house_east. They get generated like normal (they have the same mapgen code), but are rotated according to the suffix in their name. This rotation is not done for overmap terrain that had `"rotate": false`.

The mapgen rotation allows another rotation. This is used for the park, its overmap terrain has `"rotate": false`.

**Comment by vache** [comment]
Is there any functional difference than just changing the park's "rotate" member to true?  It should still place rotated parks, but they will be internally "park_north", "park_east", etc., but with the same symbol.  How is the mapgen rotate different from the overmap_terrain rotate in a way that it would support something that overmap_terrain doesn't already support?

**Comment by BevapDin** [comment]
> Is there any functional difference than just changing the park's "rotate" member to true? It should still place rotated parks, but they will be internally "park_north", "park_east", etc., but with the same symbol.

First of all, that would destroy save compatibility. Old saves still contain the id "park".

> How is the mapgen rotate different from the overmap_terrain rotate in a way that it would support something that overmap_terrain doesn't already support?

Rotation in the overmap relates to road connection (houses are rotated so they face the road).

Counter question: why should the park be rotated at all? Currently the random rotation is nothing more than to make the resulting map more random. If, for example, the park contains a sun dial, it should not randomly rotate at all.

**Comment by vache** [comment]
I understand now, but I can still see how it might be confusing, especially if you had what appear to be conflicting values, like "rotate":false in omt, and "rotation":[0,3] in the mapgen.  Maybe it would be worth it to include an explanation of the difference in the mapgen doc?

**Comment by DavidKeaton** [comment]
is there anything keeping omap specials in the code? or is it because they would be a pain in the ass?

**Comment by BevapDin** [comment]
Well, the overmap setting is a simple bool (whether it should be rotated in some unspecific way), the setting in mapgen is an actual rotation in 90° steps (it actually rotates the map).

The current documentation says
> "rotates": true - The terrain will be rotated after generation (to face roads etc)

> "rotation": Rotates the generated map after all the other mapgen stuff has been done. The value can be a single integer or a range (out of which a value will be randomly chosen).

I don't know how to word this any more obvious.

----

> is there anything keeping omap specials in the code?

You haven't done it yet (-:

> or is it because they would be a pain in the ass?

But seriously: the overmap specials are already in JSON: data/json/overmap_specials.json, the mapgen stuff (dead scientists, portals etc.) is porbably a bit more complicated

**Comment by vache** [comment]
> "rotates": true - The terrain will be rotated after generation (to face roads etc)

> "rotation": Rotates the generated map after all the other mapgen stuff has been done. The value can be a single integer or a range (out of which a value will be randomly chosen).

That leads me to believe that "rotates":false, and "rotation":[0,3] will do nothing, when that's not what will happen.

Also, what is the point of having rotation be a random number on a range?  I would think if someone wanted their building to rotate, they would either want it to rotate north-south, east-west, or any direction.

**Comment by BevapDin** [comment]
> That leads me to believe that "rotates":false, and "rotation":[0,3] will do nothing, when that's not what will happen.

"rotates" controls what happens in the overmap, it makes the terrain appear differently on the overmap, does not affect mapgen (nearly). (The generated map is rotated afterward because they share the same mapgen code and the code can simply assume the north side always faces the street.)

> Also, what is the point of having rotation be a random number on a range? I would think if someone wanted their building to rotate, they would either want it to rotate north-south, east-west, or any direction.

It adds ... randomness to an otherwise quite specific (non-random) map. There is no (in-game) reason why a park, a cabin, a mine entry etc. should have the same orientation all the time.

If you have a better wording for the description of those settings, I'll gladly apply them, or you can make a PR on your own.

**Pull request merged**
