### PR TITLE
Buff explosions

### PR DESCRIPTION
**Pull request by Coolthulhu**
Buff to numbers alone. Didn't change any mechanics.

Explosives will be rather weak against turrets (which have armor), but should be acceptable against unarmored stuff.

Numbers are eyeballed, I don't know exactly how high should they be. Any pointers?
Examples like
- Grenade exploding in inventory should take at least 50% hp from 8 str survivor
- Dynamite exploding 3 tiles away should deal at least 20 dmg
  etc.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Yay. Now my modded-in tank shall be able to do horrible things to zombies again.

**Comment by John-Candlebury** [comment]
-Im of the opinion that dynamite  and C4 should still deal lethal damage up to a 6 tile radius. And  be strong enough to at least demolish half of an ingame house. 

Also I dont know if its related, but molotovs blow up in a hella weird way right now,

**Comment by chaosvolt** [comment]
Hmm. Thing is, is the C4 meant to represent a demolition charge, or a breaching charge?

**Comment by kevingranade** [comment]
A forumite linked to a page with tons of this kind of info, ideally what
I'd like to do is write some unit tests based on those numbers (most seems
to be centered around 50% 'lethality' at a given distance), and then tweak
the numbers to match, then future changes to the system would also get
checked.
I'm not saying this PR shouldn't land, just some future direction.

**Comment by Coolthulhu** [comment]
Buffed explosions heavily against the player. Since monsters have as much total HP as player would have on torso, didn't buff it against monsters. For example, moose has 120 hp, which is as much as "moose-like" player would have on torso alone.

Changed flamethrowers to add fields rather than using the new explosions. The new explosions were too... "explosive". Napalm rockets use a mixture of new and old - they cause flame explosion and then cover it with some extra fire fields.

**Comment by chaosvolt** [comment]
Ooh, very nice.

Also pondering what would be best for tank shells. A direct hit obviously works wonders, but what are the expected effects on robots if it eats a near-miss, like landing in a adjacent tile?

**Comment by Coolthulhu** [comment]
Tank shells have an ultra-powerful direct hit damage, but barely any explosive damage. A 1 tile miss is like having a grenade explode nearby.

**Comment by chaosvolt** [comment]
Ah, I figured it was all about the direct hit, just unsure how much oomph a comparable near-miss has in reality, compared to said near miss in-game. ^^"

**Comment by kevingranade** [comment]
AFAIK it matches reality, any undirected explosive force in an anti-tank
round is wasted, therefore it's quite small (although 'same as a grenade'
should still have 50% lethality at up to 4 squares distant IIRC)

**Comment by chaosvolt** [comment]
Ah, good.

Hmm. That does remind me though, what about fragmentation? Seems like fragments were only going maybe 2-3 spaces last time I played with fragmenting explosive ammo, and it was far smaller a radius than the explosion itself.

**Comment by kevingranade** [comment]
Shrapnel needs a total overhaul, the "shoot pieces in random directions for a while" thing doesn't do what it should with respect to lethality, and wastes a bunch of time animating.

**Comment by chaosvolt** [comment]
Agreed. At the very least, making it all animate at once would be nice, depending on how laggy that'd be.

**Pull request merged**
