### PR TITLE
Advanced chemistry expansion

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Advanced chemistry expansion"

#### Purpose of change
Expand variety of available chemicals, adjust existing recipes to bring them more in order with reality, or remove them if it's not possible.

#### Describe the solution
Add new chemicals: benzene, toluene, antimony trichloride, ferric chloride, nickel powder, slaked lime.

Split potassium hydroxide and sodium hydroxide into different chemicals. They're made to be often, but not always, interchangeable in recipes.

Make sulfur usable directly as a fungicide.

Adjust recipes of salt (the chemical one), potassium iodine, diazepam, insecticide, plastic chunk (from milk) to be closer to real-life processes used to make those.

Recipes for disinfectant (assuming it's isopropyl alcohol), antiseptic powder (assumings it's bismuth formic iodide powder), Thorazine, antiparasitic drug, and black powder (from oxidizer powder, lye powder and ammonia) were obsoleted, as I could not figure out a workable way to produce those, and the current components are definitely not the ones that could be used to produce those things.

#### Describe alternatives you've considered
There are some other interesting chemical projects that are potentially possible for a survivor to take on, such as producing Kevlar, bakelite, sodium metal and trinitrotoluene, but I've decided to add those in a separate PR to keep amount of changes made at once manageable.
  
 I've figured out a way to produce Nylon, but apparently there's no easy way to form it into usable thread. Nylon plastic seems possible to make if some method of precision temperature control is used, so I may add this later.

Thought about not adding an extremely complex recipe for diazepam and just obsoleting the existing recipe, but decided it's a good excuse to just add more chemicals that are also actually useful in some way.

#### Testing
Launched the game, made sure that no errors happen.

#### Additional context
The process for making diazepam I've come up with, with the help of a comment below:

>Benzoyl chloride is reacted with para-chloroaniline in the presence of Lewis acid used as a catalyst, in this case ferric chloride. The resulting 2-amino-5-chlorobenzophenone is converted to the oxime with hydroxylamine and then cyclized to the chloromethylquinazoline-3- oxide by treatment with chloroacetyl chloride. When this is treated with alkali, ring enlargement occurs, giving 7-chloro-1,3-dihydro-5-phenyl-2H-1,4- benzodiazepin-2-one-4-oxide. Raney nickel reduction of the oxide followed by methylation with dimethyl sulfate gives diazepam.
>
>Benzoyl chloride is made via free radical chlorination of toluene. The resulting benzotrichloride is then reacted with water, producing benzoyl chloride.
>
>Para-chloroaniline is prepared by reduction of 4-nitrochlorobenzene with sodium hydrosulfide. 4-Nitrochlorobenzene is prepared by nitration of chlorobenzene using nitric acid. Chlorobenzene is produced by chlorination of benzene in the presence of a catalytic amount of Lewis acid; ferric chloride is used as such. Sodium hydrosulfide is prepared by reacting sodium with hydrogen sulfide. Hydrogen sulfide is prepared by treating ferrous sulfide with hydrochloric acid. Ferrous sulfide is prepared by heating sulfur and iron together.
>
>Hydroxylamine is produced by electrolysis of nitric acid in 50% sulfuric acid.
>
>Chloroacetyl chloride is prepared by the addition of chlorine to ketene. Ketene is produced from acetone using a ketene lamp.
>
>Raney nickel is prepared by dissolving nickel in molten aluminum, which is then cooled, ground into a powder, and treated with a concentrated water solution of sodium hydroxide.
>
>Dimethyl sulfate is prepared by the esterification of sulfuric acid with methanol.
>
>Chlorine for all intermediate steps is produced via brine electrolysis.

The process for making insecticide I've come up with, assuming it's actually DDT:

>DDT is made by condensing chloral hydrate with chlorobenzene in presence of sulfuric acid. Chloral hydrate is produced by the chlorination of acetaldehyde in the presence of hydrochloric acid, and using antimony trichloride as catalyst. Acetaldehyde is produced by the partial oxidation of ethanol at 500-650 C using silver as catalyst. Chlorobenzene is produced by chlorination  of benzene in the presence of a catalytic amount of Lewis acid; ferric chloride is used as such.

### CODE REVIEW

**Comment by MrWhiteCDDA** [comment]
It's nice to see some more advanced chemistry added.
I want to comment on the hydroxylamine synthesis. It is a good simplification for use in game but I prepared it myself and want to add how it is done on a production scale:

It is not done in gas phase as can be inferred from the description. The gas phase reaction has only a 1-2% yield.  You blow the gases into a suspension of the catalyst in sulfuric acid or hydrochloric acid. The gas has a 1:2 NO:H2 stochiometric ratio to prevent side reactions with free NO.  That way you get around 90% yield of a hydroxylamine salt. You convert that to hydroxylamine with a base, preferably ammonia solution at low temperatures.
The sulfuric acid/hydrochloric acid  is part of the catalyst but it is used up by the ammonia and yields ammonium sulphate or chloride.

An alternative way to synthesize hydroxylamine with stuff that's already in game is electrolysis of nitric acid in 50% sulfuric acid.

**Comment by AtomicFox556** [comment]
> An alternative way to synthesize hydroxylamine with stuff that's already in game is electrolysis of nitric acid in 50% sulfuric acid.

Actually this seems like a more accessible way; I'll update the recipe soon.

**Comment by MrWhiteCDDA** [comment]
Glad I could help. One more thing, since you updated the description of caustic soda. It is never really sold as powder but rather as pellets. Its very hygroscopic, powder would clump up really fast and get stuck in the bottle.

**Comment by AtomicFox556** [comment]
> One more thing, since you updated the description of caustic soda. It is never really sold as powder but rather as pellets. Its very hygroscopic, powder would clump up really fast and get stuck in the bottle.

Done, updated the description.

**Comment by AtomicFox556** [comment]
Made a minor update regarding use of sodium hydroxide and potassium hydroxide in recipes.

**Comment by AtomicFox556** [comment]
Added oxycodone recipe as well. The process involves oxidation of codeine to 14-hydroxycodeinone, which is then hydrogenated in the presence of platinum catalyst to obtain oxycodone; hydrogen and oxygen are both produced via electrolysis.

**Pull request merged**
