### PR TITLE
Make rope wearable

### PR DESCRIPTION
**Pull request by ifreund**
As Charlesilv4 pointed out on IRC, you should be able to wear rope coiled around your torso.  This makes the 30 ft rope and vine wearable, with what I think are reasonable encumbrance, coverage, and thickness values.

### CODE REVIEW

**Comment by illi-kun** [comment]
That's a quite weird PR, imho.

It's possible to wear a bucket on your head IRL, so should we make it wearable in game also? No, I guess (but maybe it's just me)...

**Comment by karols146** [comment]
Bucket on head win everything :D 
Btw wearing rope like that is normal, you can see a lot  guys wearing ropes like that in real. Only thing is about line length, 30 ft is too long in my opinion.

**Comment by Rivet-the-Zombie** [comment]
They should probably go on the STRAPPED layer.

**Comment by illi-kun** [comment]
I guess you mean ```BELTED```.

**Comment by Rivet-the-Zombie** [comment]
Yeah, I had that backwards.

**Comment by codemime** [comment]
> It's possible to wear a bucket on your head IRL, so should we make it wearable in game also?

It could be a funny [Easter egg](https://www.google.com/search?q=skyrim+bucket&biw=1920&bih=928&source=lnms&tbm=isch&sa=X).

**Comment by ifreund** [comment]
> It could be a funny Easter egg.

Bucket as a helmet could be a cool easter egg, but it would make much more sense to have it "wearable" on a hand just like a briefcase or shopping bag.

>Only thing is about line length, 30 ft is too long in my opinion.

I estimate that 30 feet would be wrapped 6 times around, 5 feet per loop.  Then this would be draped over one shoulder and diagonally across the torso.  In my head this works out pretty well, though I can't say I've tried this irl.

>They should probably go on the STRAPPED layer.

On it, I forgot about that.

**Comment by 321nick** [comment]
tbh a bucket on head sounds like a really great idea, it can be used as armor or something, at the cost of blindness, b/c it would cover eyes,  although it could be a crafting recipe too poke out eyeholes with a screwdriver or similiar, with a byproduct of giving u some scrap metal and a bucket with eyeholes, oh and sorry for sort of going off-topic.

**Comment by Charlesilv4** [comment]
Hey thats cool!
Thanks ifreund

**Comment by BorkBorkGoesTheCode** [comment]
Hooray!

**Comment by ifreund** [comment]
No problem @Charlesilv4 thanks for idea!

**Pull request merged**
