### PR TITLE
Mildly modify mansion monsters & majorly minimize mansion mapgen 

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: balance "Expands the mansion zombie list and slightly increases zombie spawn rates in mansions; makes mansions much more rare in the overmap"```

#### Purpose of change
Mansions are presently one of the most idyllic sources of early-game loot for a few reasons:
- They have very few zombies, and no special zombies, in the spawn list
- They are outside town, away from hordes
- They contain a little bit of nearly everything including foodstuffs, clothing, water, cooking tools, etc.
- They contain a wide range of extremely helpful books (addressed here: https://github.com/CleverRaven/Cataclysm-DDA/pull/28035)
- They are guaranteed to contain medieval arms and armour, often high end stuff
- They are flippin' everywhere

#### Describe the solution
Mansions should still be great places to loot, but they shouldn't be so great that they totally invalidate other sources of loot.

This PR aims to solve the first issue listed above, by adding a wide range of low-tier special zombies to the spawn list of mansions and increasing spawn rates by about 20% - this should be offset by each new specialized Z counting as a few normal ones. Mansions should still be accessible to new characters, but no longer the be-all end-all loot pinata of the early game.

I have added runners, tough zombies, and skeletons/shrieker/acid/smoker/shady/shocker/grabber/bloated zombies to the list, as well as cops and necromancers. This should make things tougher, but these zombies will still be much less frequent than plain Z.

EDIT:
I have also gone into overmap generation stuff and made mansions quite a lot less common. Instead of a guaranteed mansion and up to 4 per overmap tile (of each type!) it is now not guaranteed at all, and one of each type is the max. The isolated rural estates are considered unique buildings. Mansions closer to cities aren't unique.

This should help reduce the problem of mansions giving out too much loot and armour simply by making mansions quite rare!

#### Describe alternatives you've considered
If there was a way to do it, I'd love to give the panic room spawns 3 choices: spawn zombies, spawn a turret, or spawn an NPC. 

I've considered limiting what spawns in the mansion, but I don't see why these zombies wouldn't evolve the same way town zombies do.

I considered having a small chance to spawn a turret or secubot in the foyer but decided it was cruel. Instead i just put more zombies there.

#### Additional context
- [x] Update spawn lists to expand zombies
- [x] Increase spawn rates to make up for cost of adding special zombies
- [x] Test to make sure it's still survivable

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I recently spent quite a bit of time in the monstergroups.json file, these look like very reasonable and well balanced changes IMO.
The one thing i would be careful for is checking the mansion isn't overcrowded now, since i noticed the cost_multiplier is pretty low overall in the spawn group. I'm not 100% on how those work but that might cause more spawns than expected. if that is the case, you can fix by turning the multiplier up on some of the nastier zombies, but give it a playtest first and see how it feels.

**Comment by I-am-Erk** [comment]
Yes, I'll be loading it up soon to test. I don't think it'll be more crowded though; I didn't increase the spawn rate much, and the new monsters all cost 3-5 points.

**Comment by I-am-Erk** [comment]
So it turns out that each overmap region was set to contain a minimum of 2, and as many as 12 mansions. The level of mansions was too damn high! I have nerfed that to oblivion, making these a cool rare find. As a result I can leave some things I was originally going to nerf - like armour availability - intact, because now a mansion is a special thing.

Someone suggested a way for me to make the panic room contain a few different types of spawn, including possibly a holed-up NPC, so I am gonna take a look at that. Finding a living NPC would be another cool treasure in a mansion.

**Comment by I-am-Erk** [comment]
Tested: The new monster types do spawn, but are quite rare. I'd say they do a little bit to make mansions less plain, but I don't know if they really bump the difficulty up appreciably. I'll leave it where it is for now, the decreased spawn rate should help the rest of the balance equation.

**Comment by SunshineDistillery** [comment]
If you don't mind taking a suggestion:  You could remove all those monsterspawns at the mapgen level and add spawns to the om_terrain.  It makes it easier to set exact population numbers and easier to edit in the future.  Look at the lab terrains as an example.

**Comment by I-am-Erk** [comment]
I confess, I have no idea where to find that in the lab code. I'm not likely to make any big changes to mansions at this point as I'm pretty happy where they are... however, I do want to look at lab spawning, so if you want to help me find that stuff, I would be happy to check it out.

**Comment by Photoloss** [comment]
Could you rename the PR and remove the "mildly" considering the mapgen changes? Mainly to preempt the forum outrage when someone out of the know reads of a 75+% spawn nerf as a "mild" change. 

I'll also note skeletons, smokers, bloated and probably others *already* spawned as evolution upgrades so your first "purpose" bullet is *technically* wrong but I have no issue with the actual proposed changes.

**Comment by I-am-Erk** [comment]
I hope you're happy, it took me a while to think of good alliterative word's

**Comment by I-am-Erk** [comment]
I've playtested a few worlds now, but if someone wants to load up the overmap changes and see how rare mansions are in their worlds now I'd really appreciate it. Higher number values are good. I would like it to be a special event to spawn near-ish to a mansion.

**Comment by Wayticus** [comment]
How will this change effect the mansion holdout start scenario?
Would you ad an option to start in the panic room?  If so would you have more profession options besides butler/maid, as other types of people could have been living there and hid out.
Would it no longer cost a point but give points at start since it will be much more challenging with harder monsters in it?

If the panic room has an NPC will they be getting a special back story, not as traumatizing as hiding in a morgue body locker, but that would of been a little nerve racking:  Someone is breaking into the house, hide in there press the panic button wait for police to arrive, but they never did, then seeing what was actually breaking into the house on the security cameras, and hearing over their radio the chaos happening, they know why no one showed, eventually the power systems were destroyed everything went dark, but the noises persisted, and they were left alone with the flashlight batteries getting weak, as the days passed, supplies run out, hunger and thirst driving them to want to venture out, but the monsters could still be heard, type of thing.

**Comment by I-am-Erk** [comment]
I don't plan on adding a possible NPC to the panic room this PR, I have other things I'd like to work on. If I eventually do (I'd like to!) they'd definitely have a unique backstory.

Is mansion holdout a mainline scenario? I thought it was from a mod... Whatever the case, I have no plans to change it and it should be possible but a bit more difficult. Not as tough as mall I suspect

**Comment by Wayticus** [comment]
It isn't mainlined but it is a mod that comes packaged with the game, part of the more classes scenarios mod, a bit back they made it cost a point instead of none, I figured because of the potential loot you have access too, and the ease of the starting mobs, although I do recall some starts I did with hulks, shockers or and skeletal juggernauts, but they may have wandered in from the city that was right outside the mansion.

**Comment by kevingranade** [comment]
Feel free to open an issue about the shift in difficulty of the mansion start scenario.

**Comment by SunshineDistillery** [comment]
lab mapgen is pretty complex, which is why it's good that most of the spawning isn't handled there.  You don't have to dig through all those files.  

Look in the overmap_terrain.json and scroll down to where the labs are.  Or look at the fields/forests entries at the start. It's a lot more straight forward, because you can set the range for spawn populations, the chance for it to appear, and optionally the radius it spreads out from that point, like ants around an anthill.  I find it a lot less baffling than mapgens that set the X,Y coordinates and then use various mondensity/repeat/place functions. 

Monster spawning and monstergroups have almost no documentation, so I'm not really sure how it all works.

**Comment by ZhilkinSerg** [comment]
Merged to `0.D` (and `master` with #28234).

**Comment by Throwaway-name** [comment]
Uhh something may have been double committed from this: https://github.com/CleverRaven/Cataclysm-DDA/pull/28384/commits/35c81edcca4f11e5504fc2241b2b417217b3e385

**Pull request closed without merging**
