### PR TITLE
[Magiclysm] Add technomantic augmentation clinic

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Add technomantic augmentation clinic"

#### Purpose of change

Unlike our Earth, Magiclysm's Earth had CBMs before the Exodii showed up because they were invented by technomancers. However, there's no real evidence of this in the game at the moment, and there should be. 

#### Describe the solution

Add an augmentation clinic, where technomancers or rich people who didn't care about their mana levels had CBMs installed. They're pretty rare and only appear in major cities (Magiclysm Earth had CBMs but they weren't exactly common).

First floor: 
Floor1

Waiting room, consultation rooms, the Ritual Room™, and a recovery room with resting area. The autodoc is custom furniture to represent the different path Magiclysm Earth took (for example, if you disassemble it, you get some mana crystals back). 

Second floor:
Floor1

Offices for technomancers and bionic storage on the second floor.  The bionic storage _may_ have magical defenses...

#### Testing

Map spawns in and looks pretty good.

We'll see if it complains about carpet parameters. 

#### Additional context

You should be able to find zombies with CBMs in them that were former technomancers (or rich people), now that I think about it. #78796 should make blithely cutting into them feel pretty bad.

### CODE REVIEW

**Comment by Standing-Storm** [comment]
@Milopetilo Sorry for ping, but the tests are complaining about `mapgen 'palette magiclysm_augmentation_clinic' uses undefined parameter 'carpet_color_type'` but as far as I can tell I did everything correctly (and it all works in game, as the pictures show). You have more experience with this than me--is there something obviously wrong with my palette?

**Comment by QuillInkwell** [comment]
I took a look and it seems like you're the only one using the carpet palette nested inside of another palette. I think that's the issue, the test. I'm guessing it doesn't check nested palettes for the parameters they provide. I'm betting it only looks at palettes directly referenced on the mapgen itself.

**Comment by Standing-Storm** [comment]
Extra annoying that everything works in-game, then, but at least it's already a tracked error. Thank you!

**Comment by Milopetilo** [comment]
@Standing-Storm Sorry for the late response. As Quill said, there's an issue open for this exact thing, but from what I can remember the error showed up when loading into the game so the fact that there's no error for you is pretty weird. 
The mapgen still loading in and having carpet is due to the fact that it should be using the fallback, but in your screenshots there's green carpet and in the mapgen file the fallback was red, I'll take a closer look at this once my exams are over :)

**Pull request merged**
