### PR TITLE
Fix invalid beta pointer with console

### LINKED ISSUE #65437: Shelter B-19 Computer errors out when examined
### Describe the bug

When interacting with the computer in the B-19 shelter, this error occurs:
```
DEBUG    : Tried to use an invalid beta talker.

 FUNCTION : actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 1803
 VERSION  : ffc75ab
```

### Attach save file

[Damascus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11375765/Damascus-trimmed.tar.gz)

### Steps to reproduce

1. Load my save
2. Interact with computer to the north with (e)xamine
3. Error out!

### Expected behavior

Computer screen appear with lore about the shelter.

First time interacting with a B-19 shelter computer, so I'm not sure what else should be there. 

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: ffc75ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

This seems related to https://github.com/CleverRaven/Cataclysm-DDA/issues/65313

### LINKED ISSUE #65443: Invalid beta talker issue still persist
### Describe the bug

When I tried to talk to the console with another character, this error message appeared:

 DEBUG    : Tried to use an invalid beta talker.
 FUNCTION : talker* dialogue::actor(bool) const
 FILE     : src/npctalk.cpp
 LINE     : 1803
 VERSION  : ffc75ab

### Attach save file

[Wasted.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11377478/Wasted.zip)

### Steps to reproduce

1. Load the character Cathy
2. Talking to the console
3. Error

### Expected behavior

No error.

### Screenshots

_No response_

### Versions and configuration

latest experimental.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fix #65443
Fix #65437

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
ahhh yeah this one was my fault thanks

**Comment by andrei8l** [comment]
You also need to special case for `avatar`, `monster`, `npc`, and so on. I think a better solution is to use to use a cloning member function, something like https://github.com/andrei8l/Cataclysm-DDA/commit/cf456dba738530c408d1ed2c230a596e83f3723f (or without templates: https://github.com/andrei8l/Cataclysm-DDA/commit/443328f40144ab58d9b76e9da884edf403a1b6b4).

**Comment by bombasticSlacks** [comment]
This does look like a great long-term solution, so something like this doesn't happen again.

**Comment by Ramza13** [comment]
> You also need to special case for `avatar`, `monster`, `npc`, and so on. I think a better solution is to use to use a cloning member function, something like [andrei8l@cf456db](https://github.com/andrei8l/Cataclysm-DDA/commit/cf456dba738530c408d1ed2c230a596e83f3723f) (or without templates: [andrei8l@443328f](https://github.com/andrei8l/Cataclysm-DDA/commit/443328f40144ab58d9b76e9da884edf403a1b6b4)).

That looks like a nice solution, are you making a PR with it and I should close this one or should I update this one?

**Comment by andrei8l** [comment]
> That looks like a nice solution, are you making a PR with it and I should close this one or should I update this one?

I've opened my own PR with my alternative because I wanted a test unit too: #65469

**Pull request closed without merging**
