### PR TITLE
Fix headlamp to accept medium batteries akin to a flashlight

### PR DESCRIPTION
**Pull request by Br1ght0ne**
#### Summary
Bugfixes "Fix headlamp to accept medium batteries akin to a flashlight"

#### Purpose of change

I noticed that the flashlight now uses medium batteries (56 max charge), and the headlamp still uses light/ultralight (16 max charge).

#### Describe the solution

I changed the headlamp to accept medium batteries, so, for instance, the battery from the flashlight used to craft the headlamp can be used.

#### Describe alternatives you've considered

Making flashlight run on light batteries again (defeats the battery overhaul I guess)

#### Testing

Crafted a headlamp from a flashlight which had a battery inside. Proceeded to reinsert the battery in the headlamp.

### CODE REVIEW

**Comment by Br1ght0ne** [comment]
Just noticed [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/76029#issuecomment-2318414571) on #76029 - I guess this fix will be handled together with other `tool_armor`s.

**Comment by Night-Pryanik** [comment]
Your change broke some tests. Care to fix them?

**Comment by GuardianDll** [comment]
I didn't know how to fix wearable_light properly, because the irl wearable flashlights i was able to find consumed 10 times more energy than flashlight, and wearable_light can be crafted using flashlight

**Comment by ampersand55** [comment]
> I didn't know how to fix wearable_light properly, because the irl wearable flashlights i was able to find consumed 10 times more energy than flashlight, and wearable_light can be crafted using flashlight

My findings were different, see #77394. 

As for this PR, we should remove pocket for ultra-light batteries (2/2) as they fizzle out instantly.

**Pull request merged**
