### PR TITLE
[WIP] Update Defense Mode's Caravan Shop

### PR DESCRIPTION
**Pull request by Rod995**
#### Summary
```SUMMARY: Content "Updates Defense Mode item list."```

#### Purpose of change
Defense Mode's item groups were outdated, so I'm updating the lists, as well as implementing increasingly advanced weapons to be sold from the caravan.

#### Describe the solution
Adds newer items to item groups.

#### Describe alternatives you've considered
Putting all melee items in, mod or otherwise, and sorting them into tiers by their damage per move.

#### Additional context
Yes.
Still a work in progress, don't merge.
Renewal of #28331, and #31118 since my commits don't show up there anymore, and that other one borked when I rebased.

### Sorting Melee by DPM

> The item list at cdda-trunk.chezzo.com calculates what a melee item is using `damage + cutting damage + to-hit bonus >= 7`

This is a chart representing the Caravan's tech progression, increased by the number of shop encounters that occur.

*Not Final!*

Tech Level | # of Caravan Visits | DPM Min | DPM Max
--------- | ----- | ----- | -------
Level I | 1 | 0 | 8 |
Level II | 5 | 8 | 10 |
Level III | 8 | 10 | 12 |
Level IV | 11 | 12 | 14 |
Level V | 14 | 14 | 16 |
Level VI | 17 | 16 | 20 |
Level VII | 19 | 20 | 24 |
Level VIII | 20 | 24 | 28 |
Level IX | 22 | 28 | 32 |
Level X | 23 | 32 | 36 |
Max | 30 | 36+ | ∞ |

#### Notes

- While the list is currently unsorted, I plan to sort the weapons using their damage per turn.
- Instruments are included in the melee item list, due to their propensity to become weapons. :p
- Fake items are also included, since some of them make decent early-game weapons, in my experience.

#### Bugs

- The tech check in the switch for `CARAVAN_MELEE` isn't being properly updated with the right tech level, ie `caravan_tech_level`. 
image

- `wave_difficulty` also isn't being updated, which is a problem.
- Random crashes (Not confirmed as of commit e59fe8c).

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Are we even still supporting Defense Mode?

**Comment by Rod995** [comment]
I suppose?
It still gets touched sometimes, just no new features or new content.

*Until now!*

**Comment by Inglonias** [comment]
If Rod wants to support defense mode, even a little bit, there's no harm in letting them do that.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Are we even still supporting Defense Mode?

Occasionally. It should really be moved to a special type of mod ad made more configurable (with PRs likes this). Well maybe a little (huge) touch on UI too.

**Comment by Zireael07** [comment]
Can draft PRs be excluded from the bot?

**Comment by kevingranade** [comment]
Maybe, but do we really want drafts sitting around for 2+ months with no
activity?

**Comment by Rod995** [comment]
Probably not.

**Pull request closed without merging**
