### PR TITLE
Fix z-level melee attack difference problems (with testing code)

### LINKED ISSUE #42845: Monsters attacking from different Z-levels are hard to percieve. (3D FoV)
# Describe the bug

Zombies and feral humans gather in groups where they just seem to stand around while knocking eachother down, doing damage. Feral humans throw rocks but that is the only message that is being shown besides zombies getting back up. They seem to focus on a select few zombies.

_Edit: Real issue being not that they attack eachother but that you can't tell when monsters at different Z-levels are attacking. Check comments._

# Steps To Reproduce

1. Start in town where there are feral humans and zombies.
2. Watch enemies group up around eachother continously getting knocked down and getting up while taking damage.
3. Walk by the groups in broad daylight without any of them paying attention to you.

# Expected behavior

The zombies and feral humans should be on the same team and not be attacking eachother. Enemies should recognize the player as priority threat.

_Edit: There should be indicators that enemies are attacking/being attacked from another Z level._

# Screenshots

[Zombies gathered at a corner ignoring the player](https://i.gyazo.com/2fae3735303dda93e580f7c39508f97f.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4951-g9af1a35 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Redacted Roleplaying [redacted],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Mythical Martial Arts [MMA]
]

# Additional context

Started in town and went outside to find most zombies gathered in different large groups ignoring me. On a restart I could not replicate the bug but found it again on later starts. I have 3d vision enabled if that's somehow related. They also seem to be grouping around buildings even if there's nothing inside the building.

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
Bugfixes "Prevent cross-z-level melee attacks when attacker or target is not actually visible, and test for problem being solved"

#### Purpose of change

Fixes #42845.

There is a problem in which (without fov_3d) monsters are doing melee attacks when the player isn't able to see them (and the monster isn't actually able to see the player). This needs fixing.

#### Describe the solution

This PR:

- Removes the exceptions for ramps from the (committed PR) #47993;
- Adds the testing code from #48202, which expands monster_attack_test.cpp to check visibility (thanks to #48051) then checks with and without fov_3d being turned on;
- Fixes that, if run as a single test, the avatar and monster don't seem to be able to see each other on open ground - due to time of day and/or weather causing insufficient light;
- Requires that the avatar's melee attacks not go between z-levels unless fov_3d is on, to be parallel with the limits on monsters.

#### Describe alternatives you've considered

Default fov_3d to true; not acceptable right before a release, and it still has some bugs.

#### Testing

The test code indicates that it is indeed solving the problem of monsters being able to attack things across z-levels when they can't see the target.

~~Unfortunately, the test code is also indicating the other way around is not true - avatars are capable of attacking monsters that they can't actually see. Further work is needed. Once this part is fixed, in-game testing will be required.~~

It is now also solving that problem, and has passed in-game testing (thank you, wapcaplet!).

#### Additional context

The fixes for the monster_attack test wound up requiring making sure there was sufficient light, including clear weather. ~~As it turns out, the weather generation test didn't remove any weather_override remaining from a prior test. In case this is holding up this PR's inclusion, I intend to extract this from this PR sometime today/tonight.~~ Done; see #48290.

Ping: @wapcaplet, @Jamuro-g, @kevingranade.

### CODE REVIEW

**Comment by actual-nh** [comment]
I need to work on taxes... sigh. I can try to figure out where in the character (vs monster)'s melee_attack a sees check needs to be added (probably limited to across z-levels when fov_3d is false).

**Comment by actual-nh** [comment]
Well, so far so good - and I haven't seen any cross-platform/compiler differences on this, so...

Two things need checking:

- Playtesting (including whether the avatar can hit the monster and vice-versa) for the original bug
- Reach attacks

**Comment by actual-nh** [comment]
@BrettDong: Applicable labels would be Bugfixes, Z-levels, Info/User Interface, C++, and possibly Code: Tests. Thanks!

**Comment by wapcaplet** [comment]
I did some playtesting in your branch, using scenarios from the original issue report, as well as those I used [testing Jamuro-g's earlier fix attempt](https://github.com/CleverRaven/Cataclysm-DDA/pull/47993#issuecomment-798938911). I tested with giant wasps and normal zombies, using stairs, ladders, and jumping off ledges. I included switching 3D FoV on and off a couple times to get monsters' attention.

Everything is looking good now, and I cannot reproduce the symptoms of the original issue in your branch. I was not attacked by any monsters on other z-levels, nor could I attack them in return; there were no "unseen source" messages; and a friendly NPC was not attacked across z-levels. Both zombies and wasps were occasionally able to find their way across z-levels, and could follow me up or down stairs once they spotted me.

Additional confirmation from other users would be great, but I feel fairly confident that you have fixed the issue now. Nice work!

**Comment by actual-nh** [comment]
> Additional confirmation from other users would be great, but I feel fairly confident that you have fixed the issue now. Nice work!

Excellent! Thank you (for both the compliment and your part in this)!

**Comment by jbytheway** [comment]
Do you think this also fixes #47980?

**Comment by actual-nh** [comment]
> Do you think this also fixes #47980?

Good question. `stretch_attack` (and `stretch_bite`, for that matter) already actually are checking vs `sees` (and for `impassable` along whatever spaces `find_clear_path` decides to use), so I wouldn't think so. I agree with the poster of the issue, GGgatherer, that a limit on how long find_clear_path's path can be would be helpful.

**Comment by actual-nh** [comment]
I may have found (at least part of) the problem causing #47980- the `sees` in [map.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/map.cpp#L6198) doesn't exactly exclude seeing different z-levels without fov_3d on. Instead, it treats different z-levels as being on the same z-level:
```cpp
    if( !fov_3d || F.z == T.z ) {
```
Anyone know if there's a reason this version of `sees` _should_ work for different z-levels without fov_3d being on, or is this a definite bug? @kevingranade?

**Comment by actual-nh** [comment]
#47980: I keep trying to figure out how in the world it was getting past the `sees` check. I wondered if the `sees` in map.cpp, which does NOT block seeing to another z-level if fov_3d is off (is this a bug?) might be confusing things, but I'm pretty sure it isn't the one getting used, even internal to the appropriate `sees` - at least, not until _after_ the fov_3d check. If someone with a functional debugger can take a look at what's getting called when, it would be appreciated - as in, what exactly is happening internal to stretch_attack and its `sees` call.

**Comment by actual-nh** [comment]
Due to the commit of #47993, I'll need to do a bit of conflict-fixing - probably tonight or tomorrow.

**Comment by actual-nh** [comment]
Done. (It appears possible that #47993 or something else committed recently has solved #47980; not sure how...)

**Comment by Night-Pryanik** [comment]
@actual-nh did this fix #34005?

**Comment by Night-Pryanik** [comment]
@actual-nh did this fix #34005?

**Pull request merged**
