### PR TITLE
Fixing reload_furniture to allow reloading with ammo other than the default

### LINKED ISSUE #68371: clay kiln and rock forge makes coal (not charcoal) disappear
### Describe the bug

I was playing a game where I happened to have come across a bunch of coal at a mine and also had charcoal available, all nearby. Reloading the Clay Kiln (constructed object) with Coal just made the coal disappear. Charcoal seems to work correctly, however.

### Attach save file

[Lemay - old-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12745268/Lemay.-.old-trimmed.tar.gz)

### Steps to reproduce

1. Build a Charcoal Forge or Clay Kiln.
2. Have Charcoal and Coal nearby.
3. Try to reload it with the coal.
4. Coal will disappear.

### Expected behavior

Just as with Charcoal, Coal should be loaded into the forge/kiln and tracked in its inventory. It should not just disappear, unless used of course.

### Screenshots

disappearingcoal

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ae14681 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I suspect this has not been caught yet because Coal is an extremely unlikely fuel to be used for these purposes given that it usually spawns in mines which are medium danger, low reward raiding targets. Furthermore, Charcoal is extremely easy to make to the point where it's often faster to just make it than to transport it back to base.

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Bugfixes "Fixes issue where loading a forge with coal does not work"

#### Purpose of change
Fixes: #68371

#### Describe the solution
reload_furniture in iexamine.cpp was modified to look at multiple ammo types for a single object. this involves taking into account situations where, in the case of the forge, it could be 40% full of charcoal, and the user wants to put coal in, we need to calculate how much coal they can load it with.

#### Testing
loaded save linked in issue, deposited coal into forge, see that the game prompts me on subsequent calls to reload_furniture to unload said coal

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Still looking for this to restrict loading to a single ammotype at a time, don't know if you can easily merge Nornagon's commits from #72743

**Comment by katemonster33** [comment]
> Still looking for this to restrict loading to a single ammotype at a time, don't know if you can easily merge Nornagon's commits from #72743

working on it, there's a lot of moving parts with nornagon's PR and I'm trying to figure out what parts of mine can be kept

**Comment by katemonster33** [comment]
also i rebased with nornagon's change. since the code changes seemed very different i just took the JSON change. hope that's ok @nornagon

**Comment by katemonster33** [comment]
sorry, triple-post... furniture should only take single ammo type now

**Review by RenechCDDA — APPROVED** [review]
Looks good now, thanks for the hard work!

**Pull request merged**
