### PR TITLE
Add monster electric resistances

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Features "Add monster electric resistance"

#### Purpose of change
Follow-up from #53135
Initially part of #53604, I decided to split that PR into monster resistances and character insulation as they are two independent code paths.

#### Describe the solution
This PR adds support to define electric resistance for monsters through JSON. It also adds initial values for most monsters that should be tweaked after more thorough testing.

The amount of electric resistance was decided as follows:
* All blob-based monsters (i.e. zombies, slimes. mutations) get a small amount of electric resistance.
* Bigger monsters (100L, 300L, 600L+ monsters) get a boost to electric resistance based on size.
* Intermediate evolutions get a small boost to resistances while late game evolutions (Hulks, Juggernauts) get a huge boost.
* Plant based enemies get a small amount of electric resistance.
* Zombies with appropriate gear get boosts to resistance. Soldiers/Firefighters get a base resistance similar to a character wearing turnout boots. Hazmat zombies get a medium boost. Power-armor wearing enemies get a huge boost. 

Also fixed a nasty bug where calling erase on a reference to a std::vector wasn't removing the element from the original vector (it should never make a copy in the first place). I don't know why this happens but I wasn't able to reproduce it anywhere else. Changing the `std::vector&` to `std::vector*` fixed it. This bug was causing fields to spread towards creatures ignoring the spread cap which made electricity very deadly in some cases, mostly noticed when Husks melted anything that came into contact with them. Now the fields act as I initially intended.

Now Husks will create more condensed fields but they will be deadly (intensity 7) if you are close, going up to 10 if supercharged. The intensity falls off quickly to a maximum of 3 at a distance of 2+ tiles. With the previous bug fixed this still kills most monsters that hug the Husk (it even damages Hulks and Juggernauts sometimes) without instantly melting anything that gets close.

@Venera3 brought out a good point about the zapped effect being too binary in that monsters either were immune to it or completely vulnerable to it. I implemented a logarithmic function to control the chances of being zapped which should make it easier to balance the zapped effect on monsters and added a global multiplier that can be defined for each monster type (defaults to a multiplier of 1). Also made its duration last 1/10 of the damage instead of equal to the damage while keeping the minimum duration of 2 turns. It's a severe nerf to the effect so maybe this will have to be tweaked in the future.

The multiplier can be used for other status effects or renamed/refactored if needed. I haven't added it to any monster definitions yet so there is still time to change/extend it after this PR.

#### Describe alternatives you've considered
None.

#### Testing
Made sure that fields spread properly now without going over the intensity cap. Resistances seem to be working well too but I don't think they can be balanced without proper playtesting. Initial values should be good enough for now.

#### Additional context
Husk field after the changes:
HuskFields

Zapped effect chance for 0.2, 0.5 and 1.0 (default) multipliers:
image

### CODE REVIEW

**Comment by Venera3** [comment]
Is the `zapped` effect also mitigated by this? Those move debuffs can effectively shut down large single monsters for no investment other than batteries and time spent doing it.

**Comment by GoLoT** [comment]
> Is the `zapped` effect also mitigated by this? Those move debuffs can effectively shut down large single monsters for no investment other than batteries and time spent doing it.

It's based on damage now (as of #53135) with a 20% base chance of zapping at 2- damage and 100% chance at 5+ damage. It can be tweaked if needed. This is damage after mitigations so hulks with 5 resistance will completely ignore fields of intensity 5 or less, and attacks of 5 damage or less, and they will only be stunned reliably with 10+ damage hits (mitigated to 5+).

But the zapped chance can be made into a curve (it is linear now) with a logarithmic growth.

**Comment by Venera3** [comment]
Cheers, I'm happy as long as there's a dial I can fiddle with - until now the flavors of zapproofness were "electric attacks and immune" and "zaps back and immune", which is pretty limiting.

**Comment by GoLoT** [comment]
This is ready for review now. It should give more room to play with electric damage since monsters won't be completely crippled by it.

**Pull request merged**
