### PR TITLE
[Xedra Evolved] Maintaining

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Maintaining
#### Describe the solution
See the commit names

### CODE REVIEW

**Comment by b3brodie** [comment]
Another issue, xedra adds lines of dialogue to rubric referencing fae and vampires.  However, the response from asking about methods to fight vampires is a copy paste from asking about fae.  I'm presuming this was supposed to be a source of the vampire cure method?

**Review by Maleclypse — APPROVED** [review]
Thank you for these

**Comment by Maleclypse** [comment]
> Another issue, xedra adds lines of dialogue to rubric referencing fae and vampires. However, the response from asking about methods to fight vampires is a copy paste from asking about fae. I'm presuming this was supposed to be a source of the vampire cure method?

I’ll fix that. Thanks for letting me know.

**Comment by Maleclypse** [comment]
Does this need to be rebased to deal with the bio op takedown error?

**Pull request merged**
