### PR TITLE
Option to disable item info highlighting. Color changes for readability.

### LINKED ISSUE #14143: Hard to read brown text in the crafting menu
Mostly dig the new crafting interface changes, but the brown text is very hard to read. 
To get all "interface optimization and advanced color theory" on ya'll, brown/black has a low perceptive contrast ratio. Which is good for camouflage or subtle color transitions, but very bad for legibility.
I'd suggest  yellow- same color family as the current brown, but much higher contrast.
Alternately, use a brown highlight/background with black text. (Because [math] (https://en.wikipedia.org/wiki/Color_difference) and [eyes] (https://en.wikipedia.org/wiki/Color_constancy))

### PR DESCRIPTION
**Pull request by OzoneH3**
Closes #14143

Changed c_brown to c_yellow and c_blue to c_ltblue for readability

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, excellent.

**Comment by Zireael07** [comment]
Great!

**Comment by kevingranade** [comment]
Unless there's a remaining readability issue after the color change (and one that we can't work around), there's no need to add an option to disable the highlighting, we have more options than I'd like already.

**Comment by chaosvolt** [comment]
Because EVERYONE loves having their inventory screen become rainbow vomit.

**Comment by pouar** [comment]
https://33.media.tumblr.com/tumblr_mcdhszWhji1qf1mhe.gif

**Comment by chaosvolt** [comment]
Hmm. Almost had a minor "oh what the hell" moment because I forgot this PR hadn't been merged yet and assumed the color changes failed to work.

Also of note, the item-comparison screen is made rather less useful by the delightfully distracting array of colors added. >.>

**Comment by chaosvolt** [comment]
And if I seriously have to start quoting the various people on the forum that have expressed a dislike for the item info highlighting...

**Pull request merged**
