### PR TITLE
Item names now include the number of additional pockets attached to them

### PR DESCRIPTION
**Pull request by Dan1ss1mo**
#### Summary
Interface "Item names now include the number of pockets attached to them"

#### Purpose of change
MOLLE pockets are currently buried pretty deep in the interface; to see if an item has any attached pockets at all, you have to go into the item description and then scroll down to the storage section. There's no way to easily see at a glance how many pockets an item has attached

#### Testing
Works as intended

#### Additional context
#62664

### CODE REVIEW

**Comment by andrei8l** [comment]
A test unit would be nice here.

Also you should try to preserve commit authorship - you can either cherry pick or use `git commit --author=...`, or at the very least add Ilysen as co-author by appending `Co-authored-by: ... <email>` to the commit message.

**Comment by Dan1ss1mo** [comment]
> A test unit would be nice here.
> 
> Also you should try to preserve commit authorship - you can either cherry pick or use `git commit --author=...`, or at the very least add Ilysen as co-author by appending `Co-authored-by: ... <email>` to the commit message.

do i need gitbash for that? I'm still isn't that famailiar with github

**Comment by Dan1ss1mo** [comment]
> A test unit would be nice here.
> 
> Also you should try to preserve commit authorship - you can either cherry pick or use `git commit --author=...`, or at the very least add Ilysen as co-author by appending `Co-authored-by: Ava <...stripped...@gmail.com>` to the commit message.

As mentioned it discord, don't think i have qualification to write a test(

**Comment by KorGgenT** [comment]
that  summary isn't acceptable, it really needs to be an actual summary

**Comment by bombasticSlacks** [comment]
If you are okay with it, I'd reopen a version of this with the correctly cherry-picked commits and add a unit test.

**Comment by bombasticSlacks** [comment]
ahhh actually I can't resurrect it since the branch is deleted. I'll add a unit test still though.

**Comment by anothersimulacrum** [comment]
@bombasticSlacks I can get the branch with
`git fetch <remote pointing to cleverraven> pull/62664/head:<branch name>`

**Comment by bombasticSlacks** [comment]
Closing for #64582

**Pull request closed without merging**
