### PR TITLE
Partially linted json/item_groups.json

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Since the linter doesn't know what to do with the "note": and "repeat" contexts, I had to feed this file chunk by chunk. The "repeat": was in the razorclaw spawn.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Also, this file is huge.

**Comment by Cyrano7** [comment]
If you had to manually do any part of this process it could taint the result. Which means manual review. This PR is to big. Better to wait for the linter to be updated to do this.

**Comment by BorkBorkGoesTheCode** [comment]
>If you had to manually do any part of this process it could taint the result. Which means manual review. This PR is to big. Better to wait for the linter to be updated to do this.

This PR only changes a single (big) file, so conflicts with other PRs are unlikely.

**Comment by Cyrano7** [comment]
Also there is a unrelated commit in this PR. You have been at this for awhile now. Trying to commit strait from you own master is sloppy.

**Comment by BorkBorkGoesTheCode** [comment]
@Cyrano7 Thank you for telling me. I'm going to review the Git documentation. Could you mention these types f things in future? I don't know if my activity is pissing people off.

**Comment by Rivet-the-Zombie** [comment]
It's better for everyone involved if you don't PR from your master; use a specialized branch instead.

**Pull request closed without merging**
