### PR TITLE
Remove "return fire" from turrets

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "turrets don't get to return fire if they can't see you"

#### Purpose of change
So turrets have a special secret mode that lets them automatically shoot if they can't see you. This is dumb for several reasons.
- This happens instantly, faster than the turret can actually aim to shoot you in the first place.
- The turret somehow knows where you are despite not being able to see you.
- Turrets have a weakpoint in their camera, where you can shoot that spot and break it rendering them blind. Turns out this actually makes them way more dangerous because now it's impossible to attack them without them perfectly identifying your location and blasting you immediately. It actually also lets them fire *immediately* after hitting the weakpoint, because it's now blind and valid for "return fire".

#### Describe the solution
Remove this flag from all turrets.

#### Describe alternatives you've considered
Remove the underlying c++ code entirely. Maybe there's some hyperintelligent Yrax robot or something in AFS that still wants this so I decided to also do less work and not do it.
This may make turrets too weak against being in the dark and using that against them. The turrets could have limited infrared or something? Or a flashlight like the milspec searchlights? Cameras should be night-blind, but a turret may just be looking for a blob of heat to shoot at.
IRL turrets definitely have thermals and rangefinders but monsters can't distinguish between "visible in light" and "visible in infrared only" right now iirc.

#### Additional context
image
Here's an example. I was playing chicken with the turret (I'd poke around the corner, fire off a quick pistol shot, and then get back behind cover, which was "safe", until I accidentally hit the camera weakpoint and it got to shoot me for free.)

### CODE REVIEW

**Comment by Maleclypse** [comment]
So here is the original PR.  #35784 then #35985 kevin adjusted it to be more deadly.  Can you check current distances and percentage of hits against what Kevin intended them to be?  If we are outside of those numbers it's probably in need of adjustment.

**Comment by anoobindisguise** [comment]
> So here is the original PR.

one possible solution would be to give the turret a small delay on returning fire when it is blind? if it takes however long to aim at the player and shoot them, then if it's doing this then there's that same delay? the issue is that the way turns work this isn't easy to accomplish in code.

**Comment by Maleclypse** [comment]
> > So here is the original PR.
> 
> one possible solution would be to give the turret a small delay on returning fire when it is blind? if it takes however long to aim at the player and shoot them, then if it's doing this then there's that same delay? the issue is that the way turns work this isn't easy to accomplish in code.

You could have it fire off an eoc that then fires the gun 1 second later?

**Comment by kevingranade** [comment]
The recoil number I added is up for debate,  and adding a delay is totally reasonable,  yes it does need to traverse to fire.
As for it having a better chance to hit you using this feature,  well it should pretty much have a perfect hit rate of it can target you visually so...

**Comment by ADekema** [comment]
Adding infra-red and nightsight to military turrets would be the most realistic solution. Maybe there should be a base chance that a turret misses if you hit it and it can´t see you. The reason would be that it can only guess where the bullet came from and might target a completely wrong area.

**Comment by kevingranade** [comment]
Yes it can't center-of-mass you since all it knows is where the gun is. Weirdly that doesn't really fall off with range

**Comment by Zireael07** [comment]
@kevingranade Problem is currently it effectively magically knows center of mass

**Comment by fairyarmadillo** [comment]
Lorewise, how does it even know it's being shot at? What sense or metric is it using to determine that? These things would be deployed alongside friendly soldiers, right? Wouldn't nearby unseen friendlies firing guns be a thing that happened all the time? How is it telling those kinds of shots apart from ones aimed at it by hostiles?

**Comment by SkuliAdams** [comment]
> Lorewise, how does it even know it's being shot at?

As per the original PR, the turret has a built-in accelerometer to detect being hit by a projectile. Once hit by a projectile, it then fires at the nearby gunshot sound, assuming it was picked up by the gunshot detector.

**Comment by fairyarmadillo** [comment]
> > Lorewise, how does it even know it's being shot at?
> 
> As per the original PR, the turret has a built-in accelerometer to detect being hit by a projectile. Once hit by a projectile, it then fires at the nearby gunshot sound, assuming it was picked up by the gunshot detector. Though this suggests that there could still be friendly fire issues if there's an active gunfight and both sides are firing at once.

Strange that they return fire on bows, but that's a separate issue I guess.

**Comment by Profugo-Barbatus** [comment]
What exactly is the basis for this being any sort of accurate? Gunfire detection technology does exist, and its bearing and distance is good - but with full distributed grids of dedicated equipment having margins of error in the [tens of meters](https://arxiv.org/abs/2108.07377), and single-point systems presumably having worse spatial accuracy - it'll have a good bearing still, but considering everything I can find indicates that spatial precision is done in clusters, evidence is that a single location unit isn't able to provide great distance data.

**Comment by kevingranade** [comment]
Clustered systems struggle because they're operating across a huge area with very sparse coverage and lots of obstacles, if the sensors have direct line of sight to the sound source it's a much, much simpler problem.
Heck, all of this is ignoring the fact that guns have muzzle flash.

Again, the only meaningful limitation here is they know where the gun is but not the shooter's body, so that limits their accuracy.

**Comment by Profugo-Barbatus** [comment]
I don't really think that's what I'm asking for, I'm asking if there is an example of an existing functional system that works as you are describing, providing precise targeting-useful information from that direct gunshot. All the systems I'm aware of provide a direction and a range estimate, not a pinpoint "right there", even with flash detection. Simply saying "Its an easy problem to solve" doesn't actually show anyone who's solved it, while having an actual existing system that does so lets us figure out how well this should work from how well it itself works.

If the goal here is to make turrets less easily cheesed at night, wouldn't it make more sense to just actually have muzzle flashes act as illumination, so the turrets normal sight can act on the player? Then rather than gun turrets automagically acting in an unpredictable manner that doesn't reflect anything in real life, we instead have players realizing something night fighters have fought with for over a hundred years, that muzzle flash gives away positions.

**Comment by kevingranade** [comment]
Your source is repeating what I said, "this is hard if you don't have direct line of sight to the sound source, it's easy if you do", then it explores solutions to address the difficult case.  Since in our scenario the source necessarily has direct line of sight to the sensors because it needs that path to fire, it's a much simpler proposition.

This source is a more similar scenario and claims cm-scale localization of sound sources https://www.mdpi.com/2079-9292/11/16/2509 the turret system can function with well over an order of magnitude less precision than that.

> All the systems I'm aware of provide a direction and a range estimate

That's... precisely what you need? A bearing and a range *is* a firing solution.

> If the goal here is to make turrets less easily cheesed at night, wouldn't it make more sense to just actually have muzzle flashes act as illumination, so the turrets normal sight can act on the player?
 
It's a black box, we're discussing implementation details here, but none of this is or should be exposed to the player, so nothing about explicitly basing it on muzzle flash detection is going to make any difference. All the player is going to know either way is, "if I shoot one of these things it returns fire".

Just FYI, the alternative here isn't "ok turrets are just helpless at night", it's "ok turrets have IR vision and are never blind".
To the extent that this is a departure from reality, it's a departure from reality to specifically make turrets less capable of shooting the player in all conditions.

**Comment by Profugo-Barbatus** [comment]
>This source is a more similar scenario and claims cm-scale localization of sound sources
Are we looking at the same paper? It achieves that level of accuracy, with a spread of ten microphones over a 500m area, depicted [here](https://www.mdpi.com/2079-9292/11/16/2509#:~:text=Figure%202.%20The%20constellation%20of%20the%20microphone%20array%20and%20one%20impulse%20acoustic%20source.). I still haven't seen a source for the accuracy and margins of error for a single central microphone array - IE, contained single unit.

> That's... precisely what you need? A bearing and a range is a firing solution.
For artillery pieces, sure, but one degree of error at just a hundred meters distance is already missing the origin point by two meters, so unless turrets are chucking explosive ordinance, its going to be extremely ineffective. 

> All the player is going to know either way is, "if I shoot one of these things it returns fire".
I think this part is being misunderstood - I'm not saying a different special case for muzzle flashes should be done - I mean that a muzzle flash should in the most literal of gameplay senses illuminate your tile - and then if you're in vision range of anything, including a turret, it can now see you, like any other entity, and shoot at you. No special case of "well turrets can shoot back but not other things", no arguments over microphone array efficacy in automated immediate response fire control systems for autonomous weapon platforms that don't exist IRL, just "I see it, I shoot it".

**Comment by kevingranade** [comment]
> one degree of error at just a hundred meters distance

One degree is a huge error.

> a muzzle flash should in the most literal of gameplay senses illuminate your tile

It should generally only provide a flash of light, not enough for most things to discern what's there.  Illuminating the tile for long enough for an enemy to discern what's there would be a huge overreach.  A turret using it to better discern the location of a gunshot if what it's expecting to see is a gunshot is a totally different thing.

**Comment by Profugo-Barbatus** [comment]
> One degree is a huge error.

And we have no numbers on how much error and accuracy a single unit sensor has - See my point? Considering shot-tracking technology has existed since at least the early 2000's judging from the vehicle mounted units, but with no real information or indication available of its isolated use to that level of accuracy (I didn't even find details on whether the vehicle units operate independently or as a convoy/spread of vehicles to get that distributed advantage) its just as much of an asspull to say its useless as it is to say its single man sized precise at an arbitrary distance off a single signature - if it was regularly used in an isolated configuration, you'd think you or I would be able to find more information about it. The reason I bring up the age is that if we're extrapolating the few extra years of tech advancement that the CDDA world has on us, there's no evidence of near-deployment prototypes for this kind of advancement in the tech. Which is why I'm asking for sources that back it up is all.

> It should generally only provide a flash of light, not enough for most things to discern what's there. Illuminating the tile for long enough for an enemy to discern what's there would be a huge overreach.

Agreed, but that's more of a simulation granularity issue - Perfect information or no information, CDDA doesn't really provide a middle ground of "Something unknown just lit up in the night". If it did, I'd imagine our extremely trigger happy and irresponsibly deployed at times autonomous weapons platforms would shoot it as a matter of principle, some programming equivalent of "probable cause for hostilities". But that leaves the whole thing in a bit of a difficult place where we have invisible gunfire to mask perfect perception.

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
