### PR TITLE
JSON Readability pass

### PR DESCRIPTION
**Pull request by dopeghoti**
Make this JSON more readable and maintainable by doing two things:
- Using a columnar format that vertically aligns the numerical data
- Alphabetically sorts the individual item members of each item_group

The first of what will hopefully be many quality-of-life patches.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It would probably be much more informative if they were sorted by weight rather than id.

**Comment by dopeghoti** [comment]
I can see that, perhaps, but sorting by weight has maintainability concerns.  If I want to add, say, `hammer`s to `mischw`, it's a lot easier to tell at a glance if the sorting is by name than by weight.  Using find on a 12,000-line long file might scroll you right out of the `item_group` you're looking at without you noticing - some of the groups have a _lot_ of members.

**Comment by BevapDin** [comment]
> some of the groups have a lot of members.

It might be good to move those very large groups into their own file.

**Comment by karlnp** [comment]
>It might be good to move those very large groups into their own file.

YES PLEASE.

**Comment by dopeghoti** [comment]
Certainly something to consider, perhaps.  But then a conversation would need to take place about how to divvy things up.  I could certainly tackle this once I've finished making the JSON readable, which is my first step; this file being the first, and worst, victim.

**Comment by kevingranade** [comment]
Large-scale changes like this are very problematic, especially ordering
changes, because they confuse the hell out of git's merge functions.
I also do not expect to maintain alphabetical ordering for these files
indefinitely, or keep handling churn in the files because someone wants a
particular ordering.  Given the size of these files, searching and
filtering are the only practical way to interact with them, so ordering is
irrelevant.

I'm extremely against columnar formatting, it leads to huge amount of
whitespace churn for the sole purpose of keeping the formatting around.
Also we already have a problem with json reading dominating game startup
time, judging from the vehicle groups PR, you will be nearly doubling file
sizes in some cases, which will have a noticeable impact on startup times.

**Comment by dopeghoti** [comment]
Thanks for the input.  Would you, like @karlnp, be amenable to splitting the file up into more manageable pieces?  My main goal here is to make working with the JSON more consistent, with an eye toward eventually standardizing along something resembling a naming convention; making the JSON more _readable_ was just my first instinct in making it more _workable_.

**Comment by kevingranade** [comment]
I don't really think breaking large data files into smaller pieces *helps*, but it also doesn't have major drawbacks.  It's natural to maintain the broken-down files once it's done, and it doesn't impose additional load on the system.

**Comment by dopeghoti** [comment]
Based on this discussion, closing this PR and starting work on breaking up `item_groups.json` into smaller files by putting related groups (e. g. `museum_*`) into smaller files.  Also closing PR #13025

**Pull request closed without merging**
