### PR TITLE
.308 BBTI, description fluffs, recipes adjustments

### PR DESCRIPTION
**Pull request by tenmillimaster**
#### Summary
Content "Adds alternate .308 recipes, .308 ballistics data, and adjusts .308 guns"

#### Purpose of change

.308's ballistics data needed some adjustments. (M80, 22" barrel, does  3470J. The data I provided earlier was not doing that.)
7.62x51 cases and .308 cases were being used for the same reloading recipes.
There were no semiauto FAL's, or G3's. 

#### Describe the solution

Adds .308 Ballistics data to the ammo files. Switched the copy froms to have m80 be the 'base' ammo. Adjusted dispersion.

Added ammo requirements for .308 and 7.62x51 cases.
Adds recipe variants for each .308/7.62x61 cartridge from the alternate casing, and annotated the recipes with the loading used  for the data.
Turns the FAL and G3 into semiauto variants.
Fluffs and adjusts the M14 description, and the FAL and G3 while I was at it.

#### Describe alternatives you've considered

Adding semiauto variants instead.

#### Testing
Loaded game. Checked out new stats, recipes.

#### Additional context
None.

### CODE REVIEW

**Comment by carmakazi** [comment]
1. With the G3, is there value and/or precedent in creating variants of one gun that are identical in all but name?
2. If yes, then why not add the SA-58 for the FAL?
3. This is most likely outside of the scope of this PR, but would it be reasonable for a player character to be able to harvest the full-auto trigger/sear group from an MP5 submachine gun and fit it to a G3 clone, like what people do with registered H&K sears?

**Comment by tenmillimaster** [comment]
> 1. With the G3, is there value and/or precedent in creating variants of one gun that are identical in all but name?
> 2. If yes, then why not add the SA-58 for the FAL?
> 3. This is most likely outside of the scope of this PR, but would it be reasonable for a player character to be able to harvest the full-auto trigger/sear group from an MP5 submachine gun and fit it to a G3 clone, like what people do with registered H&K sears?

1) It's cool and harmless, IMO.
2). That's not a bad idea. Do you have any recommendations for major variations? I was luming anything DSA made into the same 'FAL', but that basically is the SA-58 pattern clone. I think there's merit to other very-different models. Century R1A1,maybe an IMBEL FAL import?
3) I think so? I know that's possible but haven't looked specifically in what needs to be present on the gun.

**Comment by tenmillimaster** [comment]
> * I mostly ask because it could set precedent to do the same with other guns.  WASR-10/PSAK-47/VSKA, for example.  I can live with it and perhaps get a little roleplay fun out of it, non gun enthusiasts may think different.  Though I guess the answer for those people is "Turn gun names off."

1) I did it for the G3 because the CETME, and the PTR 91 are very different guns that are also, in essence, the same. (I can see the argument about the HK91 not being that different). Ak's, well... I think the only real differences the variants should reflect are major ones like stamped vs milled, or RPK receiver bulge, maybe other major stuff that's not quite coming to mind this second. I don't want to get into the weeds and do PSA AK, Arsenal AK, WASR AK, Saiga AK, AMD, WBP, zastava, etc..

**Comment by tenmillimaster** [comment]
> Could the different manufacturers be done by the Variant system? Same stats just fluff. This would work for guns that of course are the same model, not just same stats. Also out of scope for this PR

Yes, but I don't think going down that route is really what we want for CDDA..

**Pull request merged**
