### PR TITLE
[very WIP]Mesoamerican armor

### PR DESCRIPTION
**Pull request by KeremBabaG**
#### Summary
Content "Add Ichcahuipilli, an aztec gambeson"

#### Purpose of change
Add some mesoamerican armor because why not

#### Describe the solution
Adds the Ichcahuipilli, a gambeson like Aztec armor that is made from quilted cotton soaked into brine to crystallize and thus make it more protective

Here are some other stuff I'm considering to add:
-Tlahuiztli: The Aztec full body suit made of animal hides and decorated with jaguar patterns, feathers, etc.
-That one hardwood helmet I can't remember the name of

#### Describe alternatives you've considered
not adding these

#### Testing
In progress

#### Additional context
MY EXAMS ARE OVER WOOOOOOO
biology majors when

cheers to dgl on discord for the idea

### CODE REVIEW

**Comment by ANickelN** [comment]
Adding spawns for these to museums might not be a bad idea.

**Comment by KeremBabaG** [comment]
> Adding spawns for these to museums might not be a bad idea.

I have a plan for a series of future prs to branch the current museum into multiple different ones with different themes. I'll add them to one of those.

**Comment by KeremBabaG** [comment]
Hey @anoobindisguise I need some advice for this since you are the last guy who reworked gambeson. The average Ichcahuipilli was 1 inch thick and was quilted. But I don't exactly know what quilted fabric means in this game. Does it encompass the filling inside the fabric or is it just the outer layer? Currently it is 2.5 cm of pure quilted fabric, should it go like quilted-cotton quilted?

**Comment by anoobindisguise** [comment]
> Hey @anoobindisguise I need some advice for this since you are the last guy who reworked gambeson. The average Ichcahuipilli was 1 inch thick and was quilted, filled with cotton. But I don't exactly know what quilted fabric means in this game. Does it encompass the filling inside the fabric or is it just the outer layer? Currently it is 2.5 cm of pure quilted fabric, should it go like quilted-cotton-quilted? Thanks in advance

sorry for the late response.
Quilted is a bit of a hack to represent the fact that the really tightly layered fabric was substantially more protective in practice than just 4mm ish of plain cotton would suggest. For example it's easier to cut a gash into a tree stump with a sword than it is to slice through a gambeson.
As far as the actual protectiveness of these go, my cursory reading suggests they're pretty badass, being basically altogether superior to a European gambesons. That said 25mm is a LOT of fabric, if we scale up an aketon vest it looks like it could easily be 27kg. How much does an actual historical item weigh? I would compare that to the existing canvas gambesons and base "effective thickness" off that.
Historical evidence suggested it compared favorably to a steel cuirass on basically every level (ease of wear, protectiveness, maintenance). From the looks of things Aztecs were "optimizing" their cloth armor earlier than Europeans were; images I've looked at suggest that it's more like a modern ballistic vest than a full body suit that focuses on protecting the vitals and not the extremities.
https://www.mexicolore.co.uk/images-11/1125_00_2.jpg

Like for example if it's many quilted layers each stuffed with a lot of cotton material I'd do like 5mm of quilted cotton at 100% coverage, and 20mm of regular cotton at 95% coverage. Maybe it deserves to cover the shoulders too. Obviously feel free to fudge the numbers but I'd try to avoid giving too big of a 100% coverage layer just for general game balance purposes and it shouldn't stand out substantially from other armors. Obviously it being like 4x as thick as a gambeson is gonna make it a powerhouse, but it should have limits, somewhere along the lines of "musket shot gets nearly nullified" in terms of ballistic defense. And of course if it's really over 25 kilograms worn on your chest you're looking at a lot of encumbrance, though it's pretty well distributed

**Comment by KeremBabaG** [comment]
Will come back to this very soon i promise

**Pull request closed without merging**
