### PR TITLE
Facility items 004 gunpowders & stuff [WIP][CR]

### PR DESCRIPTION
**Pull request by Aenye**
Adding the black gunpowder guns and charges and bombs, as well as a few other propellants / explosives for homebrew guns / explosives, based on the discussion of such firearms in http://smf.cataclysmdda.com/index.php?topic=9067.0

Asking for a bit of discussion on the stuff I will be adding here - was doing research on black gunpowder and guncotton firearms and came up with a lot.

Also, a balancing thing (to discuss before adding) - should the PC be able to craft military-grade gunpowder (at least this is what I understand the current recipe for gunpowder to be) ? I would go for not-necessarily-safe disassembly of bullets (or scavenging - gun stores, sports goods ?) to get the stuff, while less powerful propellants would be craftable with a bit of resources. If doing this, I would consider slightly upping the stats of existing milspec ammo, to counter the limited supply of high-quality ammo.

Another thing: the ranged combat system could possibly use a few tweaks, but this is well beyond my skills - if anyone is interested, I've got the physical model worked out.

### CODE REVIEW

**Comment by Aenye** [comment]
With the above, there are the following propellants (ordered by proposed strength*):
black gunpowder < guncotton < cordite < RDX gunpowder < milspec gunpowder (exists as "id": "gunpowder")
*strength - combination of deflagration speed, unit volume of gasses produced upon combustion and adiabatic compression coefficients. "Weaker" means that more of the propellant is necessary to produce the same muzzle energy (or muzzle velocity for the same projectile, fired from the same firearm).

Also: black gunpowder = a lot of smoke and a lot of soot; guncotton = little smoke, some soot, cordite = some smoke, no soot; rdx powder & milspec powder = no smoke, no soot.

**Comment by kevingranade** [comment]
So it sounds like RDX and milspec will both be usable to craft modern ammo,
but some special ammo might require milspec only.
Meanwhile the others are suitable for blackpowder guns and other guns
designed to accept them, and ecplosives.

**Comment by Aenye** [comment]
Pretty much the case - would be nice to add a "soot accumulated inside barrel" variable for guns using black gunpowder / guncotton / cordite and a "gun brush" item to help with that.

BTW: What do You think of adding a more detailed ranged targetting / combat system ? Now that weather is in and different propellants can be used, we could use speed/momentum/energy of the projectile for range/damage/armour-piercing calculations. Guns would behave a bit more realistically (effects of wind strength/direction, stopping power and different behaviour upon getting hit with a projectile, also, difference in long-range sooting with low-/high-velocity ammo) without complicating anything for the players (and giving them something to ponder before going into combat).

**Comment by kevingranade** [comment]
I disagree about the accumulating soot and similar issues, I'd rather just
disallow items that would cause excessive amounts of it rather than either
ignoring it or forcing the player to do busywork to maintain their weapons.

I'm not opposed to making the ballistics and damage model a bit more
involved in principle, but I am concerned about making the definitions of
gun and ammunition items overly complicated.  I suspect that we can get
most of the effects you're looking for by simply declaring properties on
ammunition rather than building a physics simulation into the game, and it
would be much easier for modders to manipulate them.

**Comment by kevingranade** [comment]
The problem with adding an unpreventable increase in jamming/breaking is
that we'd then get (justified) complaints that you can prevent this with
proper cleaning, which we do not want to add.  It's a big can of worms I'd
prefer to just not mess with.

**Comment by KA101** [comment]
Uh, OK, I'd envisioned using the repair kit as cleaning the machine, but I'm not significantly invested in the idea.  's all good.

**Comment by Aenye** [comment]
Ok, dropping the soot buildup / cleaning issue then.

As for the advanced ballistics model, no need for a full simulaiton - wanted to use mass of the projectile vs. muzzle velocity for damage calculations and to add an energy dispersion (progressively decreasing damage) with distance traelled by the projectile. This would essentially need two more lines of code and one more parameter for kinetic ammo.

**Comment by kevingranade** [comment]
The question is, what does that buy us compared to the existing system,
where damage can already fall off with distance, and is it worth adding
another parameter to ammo (and why only ammo? The gun used has a large
effect on muzzle velocity), and more importantly making assigning a damage
to an ammo type more complicated?

**Comment by Aenye** [comment]
If considering a gun, the length of the barrel does affect muzzle velocity, however, if we do not have to go into details, we could just pull the gun type (pistol/smg/rifle) and use those in place of an individual barrel length.
As for the gains - it would be nice polishes, to have the strategy of minding the direction of the wind (and weather in general) when shooting (sure, you can hit the zombie anyway, but that slight accuracy/range boost can be critical), to actually be able to choose the right ammo for the right job, to have a wider array of effects when a projectile hits its target (armour-piercing (slightly more detailed and range-dependent), frangible bullets (not sure about the translation), HV ammo), etc.

**Comment by Zaweri** [comment]
I would also appreciate a mod where it removes all this blasphemy and just makes it a single powder. because this hurts my brain :(

**Comment by KA101** [comment]
I'm kinda hoping this one finishes up and becomes mergeable, personally.  Aenye's work is generally popular and well-received, for all the right reasons.

**Comment by DavidKeaton** [comment]
Seconded

**Comment by Aenye** [comment]
Still working on that - having some major internet problems ATM. Should get over those in some days.

**Comment by KA101** [comment]
Fair enough.  Hoping they resolve themselves w/o much (more) stress on your part.

**Comment by Coolthulhu** [comment]
This PR will probably not become mergeable. Closing.

**Pull request closed without merging**
