### PR TITLE
Fixing Android window showing tiny in the top left corner

### LINKED ISSUE #72381: Font width and font height are messing with the terminal window (and terminal window is small)
### Describe the bug

Game opens with terminal window small, 
Touching in configs i learned that the font settings [width, height] are messing with the screen. (Did not check if other also changed something)
(And of course that the terminal window is now small, and in older versions that didnt happen)

### Attach save file

N/A

### Steps to reproduce

1.Fresh install cdda on mobile
2. NO force full-screen, NO native android UI menus, YES back button, NO software option
3. Open game, terminal window bugged.
4. Go into font settings and mess with them

### Expected behavior

That the font settings didnt mess with the window
(And that the window wasnt that small, every older version i played this didnt happen, the game opened on a playable resolution and i just had to do some minor adjustments in the terminal settings, not font settings)

### Screenshots

Screenshot_20240314-012704
Screenshot_20240314-012534

### Versions and configuration

Android
pt-br
version 9666753
Tiles

### Additional context

_No response_

### LINKED ISSUE #72399: Full-screen android issue
### Is your feature request related to a problem? Please describe.

Screenshot_20240314-225717~2
The android buttons are necessary for opening the keyboard.

### Solution you would like.

A simple deadzone where the game does not register your touch
Screenshot_20240315-003824~2

### Describe alternatives you have considered.

Workaround i found currently inside the game. Using one finger on screen by quickly tapping and holding, and another finger scrolls the android buttons
Screenshot_20240315-003824~3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Bugfixes "Fixes an issue with Android where window shows small and in the top-left corner"

#### Purpose of change
Fixes: #72399
Fixes: #72381
also partially addresses #72420 

#### Describe the solution
remove SDL_WINDOW_RESIZABLE from SDL window flags, add SDL_WINDOW_MAXIMIZED.

#### Testing
tested on my pixel 7

### CODE REVIEW

**Comment by oosyrag** [comment]
Thank you for figuring this one out!

**Comment by katemonster33** [comment]
https://github.com/katemonster33/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-19-1831 please test this

**Comment by oosyrag** [comment]
Confirmed scaling issue without force full screen has been resolved on OnePlus 7t running Android 12

**Comment by AnotherSeawhite** [comment]
A bit late to the party, can confirm it's working well

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/39efc892-8d08-4aff-ac12-83f9a9e39207

**Comment by ZhilkinSerg** [comment]
Need to be backported to 0.H

**Pull request merged**
