### PR TITLE
NPC Reading Rainbow!

### PR DESCRIPTION
**Pull request by acidia**
So, a lot of other people seemed to like the idea of NPCs having the ability to read books to you if you are illiterate... here it is.  I went ahead and added far sighted/no glasses check to it as well.

-NPCs must have one less than the minimum intelligence you need to read the book, for them to be able to read it aloud to you.  You still have to pass all the other reading checks.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woo!

**Comment by Coolthulhu** [comment]
Kinda cool and makes illiteracy less of a crippling challenge trait and more like a possible choice of bad trait.
Could also check for blindness (even though there's no way to get blind permanently yet) and also (even more minor) NPC blindness/illiteracy etc.

Why does the NPC need minimal intelligence? Smart words can be hard to pronounce, but it is the player's survivor who has to understand those.

**Comment by KA101** [comment]
Because the reader has to actually read the bloody thing too.  If you can't handle the book when reading silently, you're gonna have a worse time reading it aloud, and that's gonna throw off your reading cadence, speed, etc.

**Comment by Coolthulhu** [comment]
Maybe a penalty instead of strict "no"? Player character can read the SICP with just 4 intelligence, it would just take a day per chapter.

**Comment by KA101** [comment]
Feels like the sort of thing people would complain about in anti-grinding terms.  :-/

**Comment by KA101** [comment]
OK.  Doesn't affect MA manuals (probably because those are handled as one-shot matrix-chair carts rather than books) but apart from that seems to work.  Stand by for merge, please.

**Pull request merged**
