### PR TITLE
add vehicles

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
Content "Adds a few new vehicles for future lab content."

#### Purpose of change

Add some lab content.

#### Describe the solution

This includes a new mini railroad locomotive with steerable wheels and a selection of specialized carts

#### Testing

Play tested in a recent build.

#### Additional context

These will spawn in future maps.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
They should spawn somewhere?

**Comment by Venera3** [comment]
I think it would make more sense for the locomotives/draisines in the subways to use electric motors (there's now an electric locomotive with a suitably powerful one) but spawn without batteries - combustion engines are a bad idea underground, and having to decide between bolting a few batteries on or remaking them as gas-powered is a fun mini+objective for the player.

**Comment by curstwist** [comment]
> They should spawn somewhere?

They will spawn in maps I've already created.  I'm pushing the easier content additions first.  I was going to PR the palette set and begin PRing the nested map chunks but I need to wait for #49594 to be merged first.  My palette sets depend a lot on how the palettes were loading and working and I need to ensure they still work right with jbytheway's recent palette enhancements.

**Comment by curstwist** [comment]
> 
> 
> I think it would make more sense for the locomotives/draisines in the subways to use electric motors (there's now an electric locomotive with a suitably powerful one) but spawn without batteries - combustion engines are a bad idea underground, and having to decide between bolting a few batteries on or remaking them as gas-powered is a fun mini-objective for the player.

Makes sense to me.  I think an electric locomotive engine was added in the recent 0.F dev merge rush.  I only made the steerable mini railroad, but if Night-Pryanik agrees then I can just update the other subway vehicles too.

**Pull request merged**
