### PR TITLE
More repairs like flags

### LINKED ISSUE #36761: Repairing uncraftable armor/clothes is currently too hard
# Describe the bug
Repairing of uncraftable armor/clothes is not reasonably possible for most/all players, even with endgame skills.

# Steps To Reproduce
Spawn army pants/sheriff shirt/ rollerblades/ other uncraftable armors.
Set tailoring to 8.
Try to refit/repair clothes with tailor kit
See that the success chance is for repair/refit is 0% or far lower than than the damage chance.

# Expected behavior
Uncraftable clothing repair chance is based on the material it is made from. This would keep repairs in line with what your character could craft. Alternatively reduce the difficulty slightly so endgame characters can repair their sentimental value sheriff shirt.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11048-g8ad1db2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary
 ```SUMMARY: Bugfixes "Adds repairs like flag to uncraftable armors"```

#### Purpose of change
Fixes #36761
With recent changes it became impossible for uncraftable armor with no repairs_like flag to be repaired.

#### Describe the solution
Add repairs_like flag with a suitable item to every armor that needed it i could find. By my count 179 items.

#### Describe alternatives you've considered
Having someone else add repairs_like flags and ids for 5 hours.

#### Additional context
I tried to use a close match for the repairs_like flag, but i didn't get a "perfect" match on many items. Someone should be easily able to add even better fitting repairs_like flags after this has merged.

### CODE REVIEW

**Comment by Zireael07** [comment]
The first commit was funny - miner hat, really? You probably could roll those two commits into one (google git squash) so that we don't have such a funny commit in the repo history once it (hopefully) gets merged.

**Comment by Brian-Otten** [comment]
Heh, copy pasting one line in everywhere so i only had to swap the ids in later after i had found all the needed armors was the fastest way to get it done at the time.
I'll see about git squash, but am going to get some sleep first, and perhaps i can find some time to figure it out tomorrow. If i don't get to it in time one weird commit shouldn't hurt much.

**Comment by anothersimulacrum** [comment]
If you add `Fixes #36761` to your first post, when this PR is merged, that issue will be automatically closed.

**Comment by Brian-Otten** [comment]
I wasn't 100% sure i got everything in one go, but it's probably good enough. Will edit it in.

**Comment by RarkGrames** [comment]
I think you need to recheck this whole thing. The miner_hat entry is still on a lot of clothes as of build 10243. Like for example on wedding veil or utility vest. An other thing I noticed that you used entries that look similar, rather than entries that use the same materials or the same tailoring technique. I.e. repairing a nylon fencing jacket is not the same as repairing a boiled leather armor.

**Pull request merged**
