### PR TITLE
Martial Arts Improvements, Disarming ++

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Content "Adds some MA techniques, improves disarming and transform certain techniques from stuns to downing techs"

#### Purpose of change
It came to my attention a post on [reddit](https://www.reddit.com/r/cataclysmdda/comments/17kz3ga/does_pankration_only_work_against_humans/) where it was mentioned some problems with Pankration, so I went to check and discovered that the meat of the style depended on stunning the enemy, which since the changes in #66034 is much more difficult... But that didn't make much sense, because the style was focused on grabbing your opponent to the ground...

After I fixed that problem I noticed some others, like the current inability to disarm monster opponents (mainly ferals), and the stun reliance of some styles that would be better accommodated by down techniques or a separate stun technique, allowing the use of their main techniques in more enemies just because of a stun that didn't even make that much of a sense in the techniques.

#### Describe the solution

- Transformed the Pankration style to one that downs its opponent with its kick (As it should) and then proceeds to maul it to death in the ground, you can also throw them around and then maul them to death too! Removed/changed the stuns because they made the style too restrictive and the techniques too difficult to use.

While I was there I noticed the disarming tech of Pankration, went to look at the Bone Breaker of Krav Maga and obtained enlightenment... So I went into a little frenzy...

- Ferals/Human monsters will no longer be able to use their weapons (for melee or ranged attacks) when disarmed by the player/npc! This can be achieved by either a standard disarming technique (From Martial Arts or from certain weapons) or by the already present effect of "Broken Arm" given by the final technique of Krav Maga, a normal disarment lasts only for the duration of your fight (5-8 Minutes? Something like that), but breaking your enemy's arm is permanent (permanent non-working right now, changed to long duration) and disables many other special attacks that requires correct usage of their arms, like scratches, slashes, pulls/drags among others, part of the functionality for this was already in place for broken arms in the mentioned PR! You can now also break the arms of ferals, which was impossible previously.

- Given the nature of Krav Maga, and the difficulty in breaking your enemies arms, a new technique was given to the style, its just a simple quick disarment technique, but it can help a lot when fighting human enemies, the rest of the good techniques of the style were given a little bonus to proc so you don't end up trying to disarm your enemy more than you need to.

- Ninjutsu was in a precarious position in which its 2 main techniques, the only ones that give bonus damage and the meat of the style, were very difficult to actually use since both included stuns (with all the limitations that carries), so I modified the Ninjutsu Takedown and Assassinate techniques to remove the stuns, in part to compensate the takedown can now be done even while armed (Only with knives and claws), and its learned a little earlier.

- Ninjutsu recieved 2 new limited techniques to make it a little more interesting and compensate for the removed stuns, these are "Bite the Dust" a purely staff technique that is basically just the swipe technique that all staffs already have, which downs the enemy, and, more importantly, the "Dirty Kill" technique, a new stun technique for those ninjas that already dropped their enemies to the ground but failed to kill them, stunning them and facilitating your kill. This means that after your initial surprise attack, you can now choose to retreat to try again later or stay there and try to finish your job by whatever means possible.

- Taekwondo had its Spinning Back Kick technique changed to down the opponent rather than stun it, it makes more sense this way (You are kicking your opponent in their center of gravity, with even a knockback! they should be dropping to the ground for sure!) and it makes the technique easier to trigger against more enemies, like a kick should. 

- Removed any remnant mention of the medieval and constructed swords categories, since they were both removed in #68582

- As a benefit from these changes, added support for dialog conditionals to the special_attacks of "gun" type, in the same way as melee special attacks can.

#### Describe alternatives you've considered
A different set of techniques maybe, or not doing this kind of changes when I should be sleeping already...

Several other martial arts have stun techniques that limit a complete use of the martial art, but those techniques have more reasoning and justification behind their stuns, so I was unable to remove them and change them by something else, the styles should probably receive a visit some other time to make them a little more useful even without being able to use their stuns techs, but that is a story for another time.

#### Testing
It works! The disarm techniques now trigger even while fighting a monster, as long they have a new flag that indicates that they carry weapons, when affected by these techs the monster will become unable to use attacks related to the weapon, so no use of axes/pipes/maces to hit you when you already disarmed your enemy! And with some c++ it was also made possible to limit gun attacks in the same way, so you can disarm that feral security guard in a fight, and if you see more enemies around the corner you can run away without being afraid of being shoot on the back by the guard! If you have already disarm them you will have to wait for them to search and wield their weapon before you can disarm then again.

#### Additional context
I have a few images from my testing:

Weapon Disarm
I disarmed a pistol wielding monster and then holed up behind reinforced glass, it took the monster several minutes before they were able to wield and shoot again against me.

Weapon disarm 2
Here you can see that its possible to disarm your enemies again after they have wielded their weapons one more time.

Weapon Disarm 3
And here you can see the effects of disarment on a melee enemy, they were able to hurt me with their axe before I disarmed them, but after that they were unable to cause me any damage with just their punches and me blocking their attacks.

### CODE REVIEW

**Comment by scanevaro** [comment]
I'm the creator of the reddit post. Much appreciated for your efforts!

**Comment by Termineitor244** [comment]
> I'm the creator of the reddit post. Much appreciated for your efforts!

You're welcome!!

**Comment by TheShadowFerret** [comment]
I think now would be the time to make Krav Maga's skills unlocked by melee levels instead of unarmed ones(or split it into melee/unarmed version like Bionic Combative's Measured Strike) 🤔

**Comment by Termineitor244** [comment]
> I think now would be the time to make Krav Maga's skills unlocked by melee levels instead of unarmed ones(or split it into melee/unarmed version like Bionic Combative's Measured Strike), other than maybe the grab break

Done! I decided to leave the style unlocked 50/50, so you now gain at least one buff/technique per level of either unarmed or melee until level 5, the techniques more closely related to hand movements, like the takedown and quick disarm, were left in unarmed, but the grab break, jab, stun and the crit buff were moved to melee, I'm not so sure about dividing the techniques into 2, unarmed and melee versions, since the techniques of this style are more focused towards versatility, the most I could think would be to pass all techniques to melee, but a little of unarmed training should be part of this style to unlock all it has to offer.

**Pull request merged**
