### PR TITLE
vehicles: use fake parts to fill gaps in turning vehicles

### LINKED ISSUE #5684: Angled vehicles develop holes [$15]
While all this vehicle renaissance is going on, does it seem feasable to tackle that problem where cars at a 45-degree angle can be entered diagonally between otherwise solid parts? I think you know what I mean, how if two boards are adjacent vertically, at an angle you'll cross between them somehow. Ideally it would check the vehicle structure and make the space beyond functionally impassable/opaque from only that side. It'd probably be a tough fix, but it ought to happen at some point.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1548800-angled-vehicles-develop-holes?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "vehicles: use fake parts to fill gaps in turning vehicles"```

#### Purpose of change
Fixes #5684

As vehicles turn, they skew and open gaps in previously aligned lines of obstacles.  This creates a weird situation where a vehicle that is driving in a cardinal direction fully protects its occupants, but a vehicle driving at any other angle can get hitchhikers.

#### Describe the solution
This is a cleaned up and simplified version of #41277 by mft-dev and he should get co-contributor credit.

Create a bunch of functions to return vpart_ranges with and without fake parts and active and inactive fake parts.

During `vehicle::refresh()`, find all the OBSTACLE parts on the left/right edges of the vehicle, and add another part 1 map tile to the left or right of that part.  The new part is a fake part and is not counted for vehicle weight, the vehicle map cache, etc.  Fake parts have an index value of the real part that they are mimicking (their parent), and the parent part has an index value of the fake part.

When the vehicle turns, a function finds all the fake parts that are no longer in line with their parents and changes them from inactive fakes to active fakes (and changes unneeded active fakes in inactive fakes).  Active fakes are displayed and added to the map cache, so they block like of sight and movement.  In all cases, damage to a fake part is applied to the fake part instead.

#### Describe alternatives you've considered
`bool is_fake` is probably redundant to having a `parent_index > 0` but it's easy to reason with.

Various other solutions to the angle gap problem have been proposed, but this solution is the only solution that can be confined mostly the vehicle code instead of polluting every part of the game.

#### Testing
Several new unit tests were added.  One drives the vehicle in a circle and checks that the number of active fake parts changes correctly.  Another makes sure that a collision on an active fake part does not damage the fake part but does damage the parent part.

#### Additional context
[Short gif of a vehicle turning through 360 degrees](https://www.prismnet.com/~mlangsdo/CDDA-AngledGapsFinal.gif)

##### TODO
- [x] Fix the issue where fake parts disappear after examining the vehicle
- [x] `refresh()` now updates the vehicle cache
- [x] Fix the issue where fake doors don't open/close with the parent part
- [x] Minor changes to `open_or_close()` that take advantage of the double links between fake and real parts
- [x] Handle PROTRUSIONs on the left/right sides
- [x] add fake protrusion parts after other fake parts and link the fake protrusions to the fake obstacles so they are enabled or disabled together
- [x] filter fake parts of out vehicle interaction display
- [x] make sure that examining a fake part causes the right thing to happen and not a crash
- [x] Rewrite the test cases that I inexplicably dropped during the refactor submission

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Travis failure has nothing to do with this PR.

**Comment by SirPendrak** [comment]
While gaps in vehicles are indeed a big problem, and i had a situation wen i lost a lategame character due to being pulled out of deathmobile running 120 km/h by zombie grabber, still i dont like this solution and rlly hope there is a better way. 

1. Problem. This looks rlly ugly. And might cause a lot of confusion. 
2. Problem. It has some logic flaws. Lets imagine some sort of strange deathmobile that is 5 tiles wide and is quite long. 
Inside it there are 2 long corridors that are not connected. So its composition is like: 
Outside wall, left corridor, inside wall, right corridor, Outside wall. 
You cant get from one corridor to another. And now, if you park this thing diagonal, then you can magically cross the wall inside vehicle, but you cant move through outside walls. 
What law of physic or logic makes the inner wall different than the others? 
Honestly, i would just preffer if diagonal movement, shight etc. was forbidden if there are 2 walls, vehicle parts, impassable furniture there where youre trying to squeeze in.

**Comment by mlangsdorf** [comment]
I'd really prefer to prevent movement, vision, and line of fire through diagonal obstacles.  However, that involves making highly intrusive changes to hundreds of bits of code scattered across the entire repository, including but not limited to the vision code, pathfinding, npcmove, and monmove.

I'm not saying that solution isn't happening.  I am saying that I am not writing that solution but someone else is welcome to give it a shot.

Further discussion of forbidding diagonal movement between obstacles should be conducted in the PR implementing it, and not brought up in this PR again.

**Comment by kevingranade** [comment]
Super minor nit in testing, when a door is doubled, stepping on or off of the fake door prints a message like, "moving off of this pavement is slow".
When driving around I periodically get this
```
00:27:56.917 ERROR : (error message will follow backtrace)
    ./cataclysm(_Z21debug_write_backtraceRSo+0x25) [0xa79fdb]
    ./cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x1bd) [0xa7ac6c]
    ./cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x95) [0xa7b915]
    ./cataclysm(_Z12realDebugmsgIJRKimEEvPKcS3_S3_S3_DpOT_+0xd5) [0x1131b5e]
    ./cataclysm(_ZN7vehicle11remove_partEiR17RemovePartHandler+0x72) [0x111ebb2]
    ./cataclysm(_ZN7vehicle5smashER3mapfff5pointf+0x44f) [0x111f675]
    ./cataclysm(_ZN3map18add_vehicle_to_mapESt10unique_ptrI7vehicleSt14default_deleteIS1_EEb+0x62e) [0xd875f0]
    ./cataclysm(_ZN3map11add_vehicleERK9string_idI17vehicle_prototypeERK8tripointiiib+0x327) [0xd9d0f1]
    ./cataclysm(_ZN3map11add_vehicleERK9string_idI17vehicle_prototypeERK5pointiiib+0x2a) [0xd9d322]
    ./cataclysm(_ZNK20VehicleFunction_json5applyER3mapRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1fd) [0x113a151]
    ./cataclysm(_Z11mapgen_roadR10mapgendata+0xe6e) [0xdc3f20]
    ./cataclysm(_ZNK14mapgen_factory8generateER10mapgendataRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x95) [0xda77d3]
    ./cataclysm(_ZN3map8draw_mapER10mapgendata+0x36) [0xda08fe]
    ./cataclysm(_ZN3map8generateERK8tripointRK10time_point+0x38b) [0xda1019]
    ./cataclysm(_ZN3map5loadnERK8tripointbb+0x35c) [0xd43f2e]
    ./cataclysm(_ZN3map5shiftERK5point+0x644) [0xd44898]
    ./cataclysm(_ZN4game10update_mapERiS0_+0x18f) [0xb4bfcb]
    ./cataclysm(_ZN4game10update_mapER9Character+0x40) [0xb4ecaa]
    ./cataclysm(_ZN3map16displace_vehicleER7vehicleRK8tripointbRKSt3setIiSt4lessIiESaIiEE+0xc1c) [0xd4bb16]
    ./cataclysm(_ZN3map12move_vehicleER7vehicleRK8tripointRK7tileray+0x831) [0xd4c597]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:778
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:943
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:116
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/include/c++/7/bits/basic_string.h:647
    void realDebugmsg<int const&, unsigned long>(char const*, char const*, char const*, char const*, int const&, unsigned long&&)
    …/src/debug.h:79
    vehicle::remove_part(int, RemovePartHandler&)
    …/src/vehicle.cpp:1907
    vehicle::smash(map&, float, float, float, point, float)
    …/src/vehicle.cpp:1077
    std::__uniq_ptr_impl<vehicle, std::default_delete<vehicle> >::_M_ptr() const
    /usr/include/c++/7/bits/unique_ptr.h:147
    std::unique_ptr<vehicle, std::default_delete<vehicle> >::get() const
    /usr/include/c++/7/bits/unique_ptr.h:337
    std::unique_ptr<vehicle, std::default_delete<vehicle> >::release()
    /usr/include/c++/7/bits/unique_ptr.h:359
    std::unique_ptr<vehicle, std::default_delete<vehicle> >::unique_ptr(std::unique_ptr<vehicle, std::default_delete<vehicle> >&&)
    /usr/include/c++/7/bits/unique_ptr.h:239
    map::add_vehicle_to_map(std::unique_ptr<vehicle, std::default_delete<vehicle> >, bool)
    …/src/mapgen.cpp:5970
    map::add_vehicle(string_id<vehicle_prototype> const&, tripoint const&, int, int, int, bool)
    …/src/mapgen.cpp:5859
    map::add_vehicle(string_id<vehicle_prototype> const&, point const&, int, int, int, bool)
    …/src/mapgen.cpp:5831
    VehicleFunction_json::apply(map&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    …/src/vehicle_group.cpp:144
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/include/c++/7/bits/basic_string.h:647
    mapgen_road(mapgendata&)
    …/src/mapgen_functions.cpp:867
    mapgen_basic_container::generate(mapgendata&, int) const
    …/src/mapgen.cpp:255
    mapgen_factory::generate(mapgendata&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const
    …/src/mapgen.cpp:347
    map::draw_map(mapgendata&)
    …/src/mapgen.cpp:2839
    int_id<oter_t>::operator->() const
    …/src/int_id.h:108
    map::generate(tripoint const&, time_point const&)
    …/src/mapgen.cpp:150
    map::loadn(tripoint const&, bool, bool)
    …/src/map.cpp:6951
    map::shift(point const&)
    …/src/map.cpp:6780 (discriminator 2)
    point::operator-=(point const&)
    …/src/point.h:60
    game::update_map(int&, int&)
    …/src/game.cpp:11212
    game::update_map(Character&)
    …/src/game.cpp:11171
    map::displace_vehicle(vehicle&, tripoint const&, bool, std::set<int, std::less<int>, std::allocator<int> > const&)
    …/src/map.cpp:1217
    std::set<int, std::less<int>, std::allocator<int> >::~set()
    /usr/include/c++/7/bits/stl_set.h:271
    map::move_vehicle(vehicle&, tripoint const&, tileray const&)
    …/src/map.cpp:637
Backtrace emission took 1 seconds.
src/vehicle.cpp:1906 [bool vehicle::remove_part(int, RemovePartHandler&)] Tried to remove part 1157 but only 151 parts!
```
More seriously I rammed a road roller and this happened:
```
#0  0x00007f0f50372ae0 in raise () from /lib64/libc.so.6
#1  0x00007f0f50373f88 in abort () from /lib64/libc.so.6
#2  0x0000000000a69d8c in crash_terminate_handler () at src/crash.cpp:146
#3  0x00007f0f50ccfe86 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f0f50ccfed1 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f0f50cd0104 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007f0f50cf86a7 in std::__throw_out_of_range_fmt(char const*, ...) () from /lib64/libstdc++.so.6
#7  0x000000000112c9b6 in std::vector<vehicle_part, std::allocator<vehicle_part> >::_M_range_check (this=this@entry=0x165fbcc8, __n=__n@entry=18446744073709551615) at /usr/include/c++/7/bits/stl_vector.h:825
#8  0x000000000112c9e9 in std::vector<vehicle_part, std::allocator<vehicle_part> >::at (this=this@entry=0x165fbcc8, __n=__n@entry=18446744073709551615) at /usr/include/c++/7/bits/stl_vector.h:846
#9  0x0000000001112296 in vehicle::get_non_fake_part (this=this@entry=0x165fbbf0, part_num=part_num@entry=-1) at src/vehicle.cpp:7233
#10 0x0000000001127c73 in vehicle::damage (this=this@entry=0x165fbbf0, p=p@entry=-1, dmg=dmg@entry=27, type=type@entry=DT_BASH, aimed=aimed@entry=true) at src/vehicle.cpp:6468
#11 0x0000000000d46896 in map::vehicle_vehicle_collision (this=this@entry=0x35b0fb0, veh=..., veh2=..., collisions=std::vector of length 3, capacity 4 = {...}) at src/map.cpp:846
#12 0x0000000000d4c15b in map::move_vehicle (this=this@entry=0x35b0fb0, veh=..., dp=..., facing=...) at src/map.cpp:548
#13 0x000000000113f692 in vehicle::act_on_map (this=0x165fbbf0) at src/vehicle_move.cpp:1879
#14 0x0000000000d34879 in map::vehproceed (this=this@entry=0x35b0fb0, vehicle_list=std::vector of length 22, capacity 32 = {...}) at src/map.cpp:443
#15 0x0000000000d34b09 in map::vehmove (this=0x35b0fb0) at src/map.cpp:389
#16 0x0000000000b4b6b5 in game::do_turn (this=0x35b0a30) at src/game.cpp:1542
#17 0x000000000081537e in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:704
```

**Comment by mlangsdorf** [comment]
I'll look into that next week after I get done playing in cata_tiles.

**Comment by mft-dev** [comment]
Glad to see this was picked up after I lost steam on it 👍

**Comment by pjf** [comment]
Have applied this to my local testing/play branch, and if I get a chance to play I'll report back on how it feels. Thank you!

**Comment by pjf** [comment]
I've played a little bit with these changes applied, and honestly the experience is *glorious*.

I thought maybe the vehicles would look weird with the fake parts appearing and disappearing during rotation, but they look *much better* than before, and I no longer have weird anxieties about driving in non-cardinal directions.

I've impacted zombies, clipped a mailbox by accident, ran over items, and done all the stuff one usually does during the apocalypse, and I've not had any surprises whatsoever.

Admittedly I've only driven my converted RV doom-mobile, but the experience with that has been better in every way with this branch applied. Thank you! ♥

**Comment by pjf** [comment]
Aaaand I've found my first bug! :beetle: 

I have a 1x1 folding trolley (folding frame, folding basket, folding castors) that now refuses to unfold with the error "There's no room to unfold the folded trolley". :shopping_cart: 

Reverting the changes on this branch allows it to unfold as usual.

**Comment by pjf** [comment]
As of #50138 this no longer applies cleanly, but up until that point it's been working great (except for the folding vehicle bug).

Five stars. Would apply patch again.

**Comment by pjf** [comment]
Created 8e02d9c2b10be87fa6614791e3ae6d375cc5dc82 to fixup old calls to `item::contents`.

**Comment by I-am-Erk** [comment]
@mlangsdorf you haven't been active for a bit, but this looks almost ready to go. Should we put out the call for someone to finish it off?

**Comment by robob27** [comment]
I made a copy of this branch in my fork, rebased and compiled. I tried to replicate the road roller crash error but haven't been able to so far (any more details on how that happened? going back a while now). Looking in to the "moving on to this pavement is slow" and folding stuff. I have no idea how well the rebase was done yet or much progress I'll be able to make, but the branch is here in case anyone else wants to poke around https://github.com/robob27/Cataclysm-DDA/tree/veh_gap_fill_v2

image

Hope I'm not stepping on any toes here, I don't want any credit or anything like that I just would love to see this merged!

**Comment by Night-Pryanik** [comment]
Closing after #56143.

**Pull request closed without merging**
