### PR TITLE
[CR] Add consistency checking to overmap terrains

### LINKED ISSUE #19325: Weirdness with 3-story house: debug error thrown when approaching/loading game, no items at all inside, and no stairs down on third floor
90% sure this is either a problem with either the "More Locations" or "Tall Buildings" mod, my best guess being the latter. Anyway, when I was out scavenging, I started to approach a particular house (none of the other buildings in the area were houses, either), and about the point where it loaded into the reality bubble,  a debug message was thrown.
untitled
The message also shows up when I load the game with the house inside the reality bubble. I was able to continue the game without a crash, though when I actually got to the house, there were absolutely no items inside. All of the furniture was there, but no items (except for the water in the toilets, funnily enough) had spawned. When I got to the third floor, I found that it had no stairs downward, so I had to debug in a downward staircase to be able to get out without jumping off the roof.

The save itself isn't very old, I started it just a handful of experimentals ago, though I keep it updated to the latest version with the launcher.

### PR DESCRIPTION
**Pull request by codemime**
Follows #19223.
Fixes #19325, and eliminates some other inconsistencies.

These three checks are failed for now:
```
Checking mod PKs Reimagining [PK_REBALANCE]

src/overmap.cpp:618 [void overmap_terrain::check_consistency()] Mapgen terrain "prison_5" exists in both JSON and a hardcoded function. Consider removing the latter.
src/overmap.cpp:618 [void overmap_terrain::check_consistency()] Mapgen terrain "spider_pit_under" exists in both JSON and a hardcoded function. Consider removing the latter.

Checking mod Tanks and Other Vehicles [Tanks]
src/overmap.cpp:618 [void overmap_terrain::check_consistency()] Mapgen terrain "farm" exists in both JSON and a hardcoded function. Consider removing the latter.
```

What shall we do (I mean here, in this PR)?

- move jsonized objects from mods to the core game.
- suppress the checks for the time being.
- let them fail (as a reminder of pending tasks).

### CODE REVIEW

**Comment by mugling** [comment]
> let them fail (as a reminder of pending tasks).

I've no problem with `--check-mods` being noisy if there are actual problems with a mod

> move jsonized objects from mods to the core game.

This could come in a separate PR

Note also your comment about that horrible if/else construct. If you want to rework that we could talk about relaxing some of the review requirements (before you start) as it's so ugly I think everyone would be glad to see the back of it.

**Comment by codemime** [comment]
> I've no problem with --check-mods being noisy if there are actual problems with a mod

Let them fail then.

> If you want to rework that we could talk about relaxing some of the review requirements (before you start) as it's so ugly I think everyone would be glad to see the back of it.

I was thinking about an automated way: it's too tiresome and time consuming to do that manually. We could either: parse the function (may be quite tricky), or let it generate terrains and then jsonize the result (may be too dumb). In any case, that would require manual adjustments. Do you have any ideas?

**Comment by mugling** [comment]
> Do you have any ideas?

No, I looked at it recently and gave up in despair. Even a 90% solution would be preferable to the current mess

**Comment by pisskop** [comment]
i can clean it up so as not to produce errors but the neartern goal is its removal in favor of a repository only DL.  so via cdda launcher utility or direct

**Comment by mugling** [comment]
@pisskop yes you are correct the goal is to obsolete the mod in the main repo and for your repo to contain the actively developed version. That said if your JSON farm definitions are better we could use those in `core`. What did you change (if anything)?

**Comment by codemime** [comment]
@pisskop The mod part is perfectly fine, it's the core that needs de-hardcoding. Moving the basic jsonized versions of those terrains to the core, and customizing them in your mod would help alot.

@mugling I believe the farm has been made by @chaosvolt.

**Comment by pisskop** [comment]
I removed the plants, made the barn red, and modified the house a little.

**Comment by DangerNoodle** [comment]
Mods overriding mapgen entries should not cause error messages. If no code alternative is viable, perhaps the changes demanding it should be shifted to mainline. Foremost example would be adding setting the farm to spawn a tractor vehicle group in mainline, and thus allow that mod to add the tracked tractors to it.

I could work on a method for this when I get home, if desired?

**Comment by codemime** [comment]
> Mods overriding mapgen entries should not cause error messages.

Mods can override mapgen entries, and they will be able to do so in the future. Now warning is shown. The only situation when it appears is when something (no matter if core json files or a mod) overrides a hard-coded entry. The warning simply informs that a better alternative (this very json) exists and can be used instead.

**Comment by DangerNoodle** [comment]
I see. I should have suspected that the farm override was the only problem.

That said, there is potential for desync between the original JSON and the overrides, and it is therefore good futureproofing if overrides of JSON mapgens exist only to add something that could reasonably be moved to core.

**Comment by codemime** [comment]
> That said, there is potential for desync between the original JSON and the overrides, and it is therefore good futureproofing if overrides of JSON mapgens exist only to add something that could reasonably be moved to core.

I'm working on a PR that applies `generic_factory` to overmap terrains. That enables inheritance (`"copy-from"` semantics) when mods can modify only what they really need in `overmap_terrain`.

**Comment by DangerNoodle** [comment]
That might be interesting and useful, but that does not resolve the objective of https://github.com/CleverRaven/Cataclysm-DDA/pull/19390.

What is being modified here is the mapgen entry itself, not the overmap terrain. Indeed, implementing overrides for mapgen entries would be unfeasible at present, as they outright work by having variants chosen by their sharing the same mapgen ID.

**Comment by vache** [comment]
I don't think we should discount any hardcoded mapgen.  There are some things you can do in the back end code (mainly things revolving around random layouts) that simply is not possible with JSON right now.  It should be possible to have hardcoded and JSON mapgens for those cases where both should be capable of generating.

**Comment by chaosvolt** [comment]
Huh, don't see the namedrop that summoned me. But yeah, I always suspected the farm override I added would cause trouble at some point. :V

I'd say that any debug message is a sign of a problem. I'm not sure what the intended point of making an override of a hardcoded entry generate errors IS, unless it actually fails to override the mapgen correctly. I recall all I really did with these overrides is spawn vehicles, so https://github.com/CleverRaven/Cataclysm-DDA/pull/19390 is a smart idea. Even when I WAS a contributor, keeping the overrides consistent with mainline was always a pain in the ass.

Regarding farms though? Back then I didn't know how to sanely place a vehicle in hardcoded farms, and actually I still dunno. If neither placing tractors in it via hardcode OR JSONizing famrs aren't feasible, then feel free to axe farm-spawned tractors for the time being.

**Comment by codemime** [comment]
@vache I would have agreed with you in general, but have you seen the code we're talking about?  It's a complete mess, a heavy burden that discourages any attempt to make progress in that area. 
The sooner we jsonize most of it the better.

@chaosvolt Thanks for the reply.

**Comment by DangerNoodle** [comment]
If I was certain how to covert farms to a JSON format, I might. It would be tedious I suspect. Will farms rotate properly if converted to a JSON format, though?

**Comment by codemime** [comment]
> If I was certain how to covert farms to a JSON format, I might. It would be tedious I suspect.

Any efforts in this direction are very welcome. You could start with the existing JSONized farm from "Tanks and Other Vehicles".

> Will farms rotate properly if converted to a JSON format, though?

Yes, like all other overmap specials do.

**Comment by vache** [comment]
Sure, the old hardcoded mapgens probably all suck and should be converted to new JSONs.  But, as a general rule, it is not correct to say "a hardcoded mapgen and a JSON mapgen both exist for x, the hardcoded mapgen should be deprecated and removed".  One thing that absolutely cannot be done in JSON right now is the computer system.

**Comment by DangerNoodle** [comment]
Understood. The farm building implemented in Tanks and Other Vehicles eliminates a lot of the tedium, so I could make the attempt later on.

**Comment by Coolthulhu** [comment]
I'm not sure if I understand. Why is it a problem? Is there anything a mod can do to silence the warning? Does it trigger when same overmap special has both hardcoded and json entries?

**Comment by codemime** [comment]
> I'm not sure if I understand. Why is it a problem? 

Technically, it's not a problem. It's a reminder about hardcoded mapgens that could have been replaced with their jsonized versions.

> Does it trigger when same overmap special has both hardcoded and json entries?

Yes, except that it works for mapgens. Overmap specials can be overridden nicely. 

> Is there anything a mod can do to silence the warning? 

No, nothing for now. The check can't yet distinguish between mainline and modded mapgens.
What would you suggest?

**Comment by Coolthulhu** [comment]
This is a relatively "soft" warning. Is there a way to make it not happen all the time when a given mod needs to use both hardcoded and json entries? For example, it could be tied to `test_mode`, to only display on `--check-mods`, which would make it fail `--check-mods`, but not bother players.

We really need some other mechanism of displaying load problems - debugmsg or nothing is way too binary.

**Comment by codemime** [comment]
> For example, it could be tied to test_mode, to only display on --check-mods, which would make it fail --check-mods, but not bother players.

Good suggestion. Done.

**Pull request merged**
