### PR TITLE
Zombie nightvision

### PR DESCRIPTION
**Pull request by kevingranade**
Pulled the zombie nightvision changes out of #11369, leaving it just bugfixes.
I also applied the feedback from that, in summary:
all the regular zombies have nightvision range of 3
shriekers, brutes, hulks and zombie dogs have 4
feral hunters, necros and masters have 5
shia still has 10.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>shia still has 10.

*Now it's dark and you seem to have lost him,
But you're hopelessly lost yourself.
Stranded with a murderer,
You creep silently through the underbrush.*

**Comment by KA101** [comment]
That a vote for or against?

**Comment by Rivet-the-Zombie** [comment]
Shia is super rare and not particularly tough or anything, so I'm fine with it.

**Comment by KA101** [comment]
I've had a close call or two, but wev.  Since I appear to be the only one opposed, so be it.

**Comment by Dozed12** [comment]
I never saw a Shia

**Comment by KA101** [comment]
They're extremely rare--about the same odds as a Thriller, but in the woods rather than cities, IIRC.

**Comment by DavidKeaton** [comment]
Never seen either. :-0

**Comment by Dozed12** [comment]
I just googled what a Shia represents in cata, it's worth the search.

**Comment by DavidKeaton** [comment]
Oh who it is is awesome. Lol.

**Pull request merged**
