### PR TITLE
makes steel_lump disassembly work again

### LINKED ISSUE #54782: [Innawoods] Nails are uncraftable
### Describe the bug

Nails require chunks of steel or scrap metal to be made, however when you craft lumps of steel it disassembles into iron ore, rendering scrap metal and chunks of steel unobtainable. 

### Steps to reproduce

1. Make lumps of steel
2. Get a hacksaw
3. Disassemble the lumps to get iron ore

### Expected behavior

I expect to get chunks of steel from disassembly of lumps of steel.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6a794f1 [64-bit]
- Graphics Version: Tiles
- Game Language: Nederlands [nl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    No Fungal Monsters [No_Fungi]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Bugfixes "makes steel_lump disassembly work again"

#### Purpose of change

#54606 introduced a bug that made steel_lump no longer possible to disassemble. This fixes that issue.
Fixes #54782

#### Describe the solution

Adds an id_suffix to the recipe we don't want to use when calculating how to disassemble a steel_lump

#### Testing
Tested trying to disassemble a steel_lump with and without the fix. It didn't work without, but it worked with.
I made sure the altered recipe still works.

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by PatrikLundell** [comment]
I assume you've checked that the recipe whose name was changed still work as intended and you've checked to verify that was the only reference to it.

**Comment by Light-Wave** [comment]
> I assume you've checked that the recipe whose name was changed still work as intended

Good call. I checked that and it still works.

>  and you've checked to verify that was the only reference to it.

Not sure what you mean here.

**Comment by PatrikLundell** [comment]
You had to change the name of the recipe as it was (inadvertently) referenced for the disassembly. It's not impossible that it might be referenced elsewhere, in which case those references now would refer to the new recipe. I would do a text search of the whole JSON directory to see if the original ID shows up anywhere else, and determine whether those references should be changed to refer to the renamed recipe or be left unchanged to refer to the new one. Most likely there are no other references to it, but it's best to check.

**Comment by Light-Wave** [comment]
> You had to change the name of the recipe as it was (inadvertently) referenced for the disassembly. It's not impossible that it might be referenced elsewhere, in which case those references now would refer to the new recipe. I would do a text search of the whole JSON directory to see if the original ID shows up anywhere else, and determine whether those references should be changed to refer to the renamed recipe or be left unchanged to refer to the new one. Most likely there are no other references to it, but it's best to check.

What would be the name / ID of the old recipe? To my knowledge, recipes doesn't have names or IDs.

**Comment by PatrikLundell** [comment]
I'd search for the string you changed (before the change, of course). The "name" would be the string value of the "result" entry, as creating another recipe with an identical string causes a "random" one to be the one used (probably based on a non deterministic load order).

**Comment by Light-Wave** [comment]
> I'd search for the string you changed (before the change, of course). The "name" would be the string value of the "result" entry, as creating another recipe with an identical string causes a "random" one to be the one used (probably based on a non deterministic load order).

The only other recipes that seems to create steel_lump is one previous in the file, and two in a mod. I tested to make sure this change makes disassembly work correctly both in vanilla and when using said mod. The id_suffix I added does not show up anywhere else.

Not sure if that answers your question.

**Comment by PatrikLundell** [comment]
I'm not quite sure either, but let's call it a day.

**Comment by Light-Wave** [comment]
Error message seems to be unrelated to this change.
> In update mapgen mx_mass_grave on field, setting terrain to t_pit_corpsed (from t_grass) at (9,16) when item 9mm_casing existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

**Comment by PatrikLundell** [comment]
Yes, the error message is the result of a recently introduced check. What it means is that someone needs to update the mapgen to pass the check, and I believe ERASE_ALL... is the correct change, but someone with a higher level of confidence should tackle it.
I disagree with the introduction of new checks that keep failing unrelated PRs just because someone hasn't done a sufficient cleaning up of almost all of what would fail before unleashing the PR on the general public, at least as an error state. Warnings, notifying people who agreed to take care of the issues found would be a superior solution.
Note that the check itself is a good thing, it's just that it has been released too early.

**Pull request merged**
