### PR TITLE
Direct hits roll for sub coverage

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Armor absorption now rolls for and tries to use sub_location"

#### Purpose of change
re implementation of #52789 without causing any issues and fixing almost all edge cases.

#### Describe the solution

*Update* after suggestions bellow for convenience going forward the PR had to do a pile of mundane JSON churn to get fix values now that coverage is described based on the local things it covers as opposed to the whole limb. EX: a backpack that covers all of your back now has coverage 100 instead of coverage 50. So most of the changes are just taking the original value and dividing by the max coverage of all covered sublocations for each item. The other big change is you don't have to specify redundant locations for an entry now so a lot of additional data was removed from dusters and some torso armor. 

*Second Update* I fixed an issue with a debug item test_utility_belt which had json fails with this new stuff. It was using "TORSO" instead of "torso" for its coverage

This PR does the following:

1. Adds max coverage values to each sub location. These are used in logic and also for testing and validation.
2. Adds a number of tests for sub locations to keep json sane
3. Updated the Long_duffel to have coverage values that make it not fail tests. 
4. Attempt to roll a sub location on the targeted limb then check against the roll when applying damage absorption from armor. If no sub data exists for the limb or the armor has no sub location data default back to just using the single roll for damage.
5. Allows an armor item to specify multiple armor_data definitions for a single limb as long as they have different sub locations defined. These entries are combined for general purposes but are also kept separate internally for use with sub location queries. In implementation terms `armor_data` is now loaded in as a vector called `sub_data` and from that during `finalize` the currently used `data` vector of `armor_data` is generated. So new sub location specific stuff can use sub_data while (hopefully) keeping everything else working identical. 

The reason for 5 is that an item might not cover the same subparts of the body equally. imagine a pair of thigh high boots which only go halfway up the thigh. If they cover all of the lower leg and knees but only 50% of the upper leg that means their total coverage of the leg is 60% (35 for lower, 5% for knees, 20% for thighs). without the above code changes the code treats it like each sublocation is 75% covered (60% of the 80% max of the locations is covered). This is wrong as it should actually be represented as I said above with the lower leg and knee being 100% covered and the thigh being 50% covered. You can now do this as follows:

```json
"id": "thigh_high_boots",
    "repairs_like": "boots_larmor",
    "type": "ARMOR",
    "name": { "str": "pair of thigh-high boots", "str_pl": "pairs of thigh-high boots" },
    "description": "Very long leather boots that reach past the knees, these are difficult to wear.",
    "weight": "1540 g",
    "volume": "4250 ml",
    "price": 8000,
    "price_postapoc": 500,
    "to_hit": -1,
    "bashing": 1,
    "material": [ "leather" ],
    "symbol": "[",
    "looks_like": "boots_larmor",
    "color": "dark_gray",
    "warmth": 20,
    "material_thickness": 2,
    "environmental_protection": 2,
    "flags": [ "VARSIZE", "WATERPROOF" ],
    "armor": [
      { "encumbrance": 12, "coverage": 100, "covers": [ "foot_l", "foot_r" ] },
      {
        "encumbrance": 25,
        "coverage": 40,
        "covers": [ "leg_r", "leg_l" ],
        "specifically_covers": [ "leg_lower_l", "leg_lower_r", "leg_knee_l", "leg_knee_r" ]
      },
      {
        "encumbrance": 0,
        "coverage": 20,
        "covers": [ "leg_r", "leg_l" ],
        "specifically_covers": [ "leg_upper_l", "leg_upper_r" ]
      }
    ]
```

This PR does not change how resistance is actually calculated. It is still averaged (though that should probably be tackled in a separate PR) 

This PR also removes a function that doesn't work that I left in by mistake in #52468 which is item::get_encumber but overloaded for sub body parts. It's never been used, doesn't really make sense AND doesn't work (a real triple threat)

#### Describe alternatives you've considered
A number of things have been discussed but all had pit falls or missed edge cases. 

#### Testing
Added some debug messages to test the thigh high boots, JSON for which is above. Character is also wearing jeans (95% coverage).

As the attack starts a roll is made and a sub location determined, that roll and sub location is used throughout

"converted roll" in the bellow debug logs is the modified roll for the sub location and armor scaled to be out of 100. So for the boots it should be: 0% on hips (since it doesn't cover), 50% on thighs (since it covers half), 100% on knees and lower legs (since it fully covers them). 

image

image

image

#### Additional context

The max values for each sublocation are as follows:

Torso (rolled twice once for the hanging items and once for torso proper)

name | value
-- | --
torso_upper | 60
torso_lower | 40
torso_neck | 10
torso_hanging_front | 40
torso_hanging_back | 50

name | value
-- | --
arm_shoulder | 20
arm_upper | 40
arm_elbow | 5
arm_lower | 35

name | value
-- | --
leg_hip | 20
leg_upper | 40
leg_knee | 5
leg_lower | 35

### CODE REVIEW

**Comment by Terrorforge** [comment]
I think there's a dev-side usability problem with the coverage syntax. It seems really cumbersome to have to go "okay, so this part completely covers the lower leg and the knee, so that means uuuuh [digs up this PR to find the max coverage values] 35 + 5 = 40, I guess? Shit, is it the same if it's both legs or just the one?" That's just asking for user error.

It would be better if the syntax was the same as it currently is for body parts, i.e. you just put in "coverage: 100" and specify that it's the lower leg and knee, and that means it has full coverage on those sublocations, with the odds of that part getting hit handled by the code.

**Comment by bombasticSlacks** [comment]
The current implementation is very much to maintain the status quo. If people think that would be easier it makes the code and logic simpler as well.

**Comment by Termineitor244** [comment]
> The current implementation is very much to maintain the status quo. If people think that would be easier it makes the code and logic simpler as well.

Since I just used the code for some of my PRs I think I can say some words about it, and it definitely confuses you at first, you need to keep at hand the exact percentages of each sub location, one can get used to it, but it would be easier to just define the percentage covered of the sub location (1% to 100%) and just letting the code handle the possibility of hitting it.

Another thing that could help: That if you don't define the percentage covered for a sub location (s), the code just assumes that it covers it 100%, it would reduce clutter on the code.

**Comment by bombasticSlacks** [comment]
I think you both make good points and it would be best for it to be changed. I'm away for the next few days so any non trivial code changes I need to compile I can't do until late tomorrow. I'll set this to draft until then and add:

- [ ] No coverage is 100% coverage
- [ ] Coverage describes relative coverage instead of overall coverage for the limb
- [ ] No subcoverage defined for an armor entry counts as all the sub locations. 

If your stuff gets merged before then Termineitor I'll update all the values for the new info.

**Comment by Termineitor244** [comment]
Thanks!

**Comment by bombasticSlacks** [comment]
okay so I believe all the code work is done for this. @Termineitor244 I can't make it so not specifying coverage is 100 because it's already a default for 0. I was working on making it so it is 100 sometimes but its too many edge cases and too confusing to document so it has to stay at 0.

I still need to modify 204 items that have the new updated specifically covers values.

**Comment by Termineitor244** [comment]
> okay so I believe all the code work is done for this. @Termineitor244 I can't make it so not specifying coverage is 100 because it's already a default for 0. I was working on making it so it is 100 sometimes but its too many edge cases and too confusing to document so it has to stay at 0.

Don't worry, it would be a nice addition if it was easy to do, but if it becomes a problem then is better to leave it as it is, thanks!

> I still need to modify 204 items that have the new updated specifically covers values.

I can imagine haha, some of them were because of me, sorry.

**Comment by bombasticSlacks** [comment]
It's okay its all easy changes. It's impressive how many items you got done!

**Comment by Termineitor244** [comment]
> It's okay its all easy changes. It's impressive how many items you got done!

I started with just two items, then those 2 made me revise some more, then the whole file, then 2, 3 and 4 files... I was possessed hahaha, I hadn't planned to do as many as I ended up doing, but I'm happy to have done the changes, it allows more clothing combinations and that allows even more roleplay in the game. A nice addition overall.

**Comment by Termineitor244** [comment]
I could not resist... #52971 Sorry... At least I resisted the impulse of auditing the files for hats and gloves, but there will now be 2 more items to the list to change (If my PR is merged first).

**Pull request merged**
