### PR TITLE
Clothing Can Be On Multiple Layers

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Clothing can now be on multiple layers at once"

#### Purpose of change
first chunk of #53455 

#### Describe the solution
Added functionality everywhere it was needed for an item to have multiple layer flags. To put it simply I changed the layer entry to be a vector and fixed all the errors. This means an item can conflict with multiple layers at once. 

So now an item can exist on the outer layer and the strapped if it's something with massive pockets/bags.

#### Describe alternatives you've considered
This needs to be done if things like Molle attached directly to outer layer armor is ever going to happen.

#### Testing
The Scavenger Armor has been put on the outer and strapped for testing:
image

If you load up the PR you can test scavenger armor correctly conflicts with things.

I noticed #53459 while working on this but it seems that this isn't what broke that as it's also in current. 

#### Additional context
Currently I'm working around the fact that Normal layer is the absence of a flag. At some point if someone wanted something that was normal + something else they would need to make normal a separate flag and add it to **everything**. This PR doesn't do that but it wouldn't need much extending to support this.

### CODE REVIEW

**Comment by Terrorforge** [comment]
You're really something. I keep idly thinking things like "hmm, it would make sense if Normal-layer items with big pockets conflicted with Outer layer armor" and then glance at the PR tap to find you've already designed, coded and uploaded that exact thing.

**Comment by bombasticSlacks** [comment]
Clang is talking smack and I'm not sure exactly why. I'm guessing it's to do with the linters double indent, so I'm gonna try to add a public to the start of the struct.

**Comment by bombasticSlacks** [comment]
That wasn't it I'm at a pretty big loss on how to fix this clang warning

**Comment by ferociousdork** [comment]
If you click through to the logs of the run you can see what the optimal field order is: https://github.com/CleverRaven/Cataclysm-DDA/runs/4529556874?check_suite_focus=true

**Pull request merged**
