### PR TITLE
Gun prices and post apocalyptic prices

### PR DESCRIPTION
**Pull request by zantanzuken**
#### Summary

SUMMARY: Balance "Fixes gun prices for merchants, adds realistic prices for a couple guns (just cause.)"

#### Purpose of change

add some post apocalyptic values to weapons so that their actual values aren't used as a replacement, allows guns to be sold/bought for normal average prices instead of ridiculously inflated pre-cata prices.

#### Describe the solution

Changed a few values in the JSON files, everything else in the coding should take it from there.

#### Describe alternatives you've considered

N/A

#### Testing

 Changed the JSON for a gun, then loaded up the game to make sure there were no errors in the JSON, then checked the gun to see its value/traded with npc to make sure it worked.

#### Additional context

first pull request! feel free to look over it to see if I accidentally broke something or put a value where it shouldn't be... i only slightly know what I'm doing.

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/beretta-px4-storm-9x19mm-has-no-barter-value/25533/10

**Comment by Night-Pryanik** [comment]
> allows guns to be sold/bought for normal average prices instead of ridiculously inflated pre-cata prices.

I don't approve this rationale. Guns should literally be _the_ weapon of survival in post-apocalypse world, and as such they should be in very high demand, and as such they should cost very highly. They shouldn't cost $25000, as pre-Cataclysm, of course, but dropping their cost to mere $25 is very unrealistic.

**Comment by actual-nh** [comment]
> > allows guns to be sold/bought for normal average prices instead of ridiculously inflated pre-cata prices.
> 
> I don't approve this rationale. Guns should literally be _the_ weapon of survival in post-apocalypse world, and as such they should be in very high demand, and as such they should cost very highly. They shouldn't cost $25000, as pre-Cataclysm, of course, but dropping their cost to mere $25 is very unrealistic.

Would dropping by a factor of 20 be about right? (See #46214.)

**Comment by Night-Pryanik** [comment]
Personally I think there should be no relation to pre-Cataclysm price at all. Pre-Cataclysm price consists of cost of production, logistics, salaries and many other things that are irrelevant to post-apocalypse survivors. Gun's price shouldn't suddenly drop by a factor of X simply because, you know, Cataclysm happened. Post-apoc price should be set based on its usefulness and rarity. Sometimes this could lead to situation when some handgun with its pre-Cataclysm price of, say, 100 bucks could cost 200 after the Cataclysm due to its coolness, and that's normal.

**Comment by anothersimulacrum** [comment]
> > allows guns to be sold/bought for normal average prices instead of ridiculously inflated pre-cata prices.
> 
> I don't approve this rationale. Guns should literally be _the_ weapon of survival in post-apocalypse world, and as such they should be in very high demand, and as such they should cost very highly. They shouldn't cost $25000, as pre-Cataclysm, of course, but dropping their cost to mere $25 is very unrealistic.

Rationale aside, this change appears to be just to bring them in line with other gun prices (though it seems to be a little bit lower for the very limited sample I saw).

**Review by mlangsdorf — APPROVED** [review]

**Comment by zantanzuken** [comment]
the idea behind the change was specifically that weapons without the 'postapoc' values would use the incredibly overinflated pre-war pricing. i dont think the pre war price actually factors in to the game anywhere except for flavor text.

**Pull request merged**
