### PR TITLE
Throwing baseballs with baseball bat

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Graywolfe813** [comment]
Does this have any negative effect on the use of a baseball bat as a melee weapon?

**Comment by BorkBorkGoesTheCode** [comment]
It shouldn't, since bashing damage is the same for guns as melee weapons.

**Comment by BorkBorkGoesTheCode** [comment]
Baseball bat is listed as a gun now, and the aluminum bat is missing. I doubt this will be added to mainline.

**Comment by Night-Pryanik** [comment]
>Baseball bat is listed as a gun now

That's the way to make baseball way "fire" baseballs.

> the aluminum bat is missing

It's still there, I didn't touched it at all.

**Comment by BorkBorkGoesTheCode** [comment]
@Night-Pryanik Sorry for the confusion; this is what I mean't:

>EDIT for clarity: the aluminum bat wasn't converted with the wood baseball bat.

**Comment by Chezzo** [comment]
Is there any way you can make this not train marksmanship and a gun skill?

**Comment by BorkBorkGoesTheCode** [comment]
@Chezzo the bat uses throwing skill as the ranged attack skill. I don't know if marksmanship can be avoided.

**Comment by Night-Pryanik** [comment]
>Is there any way you can make this not train marksmanship and a gun skill?

If I'm not mistaken, it trains throwing, not gun.

**Comment by AlecWhite** [comment]
This basically treats a baseball and a bat the same as a bow and arrow with a sling skill. I don't like it.

14 dispersion is the same as the short bow, for a thing that only sends the ball in a general direction is incredibly accurate. 

Also you can still "take precise _aim_ and shoot" after you throw the ball in the air and swing your bat, which in my opinion, without the wired reflex CBM or something like that, would require superhuman reflex and body control to do.

Also there's no chance to miss the ball right?

**Comment by Night-Pryanik** [comment]
Added aluminum bat.

**Comment by Night-Pryanik** [comment]
> 14 dispersion is the same as the short bow, for a thing that only sends the ball in a general direction is incredibly accurate.

14 is a dispersion of baseball (= dispersion of pebble). Bats have dispersion of 150.

**Comment by AlecWhite** [comment]
>14 is a dispersion of baseball (= dispersion of pebble). Bats have dispersion of 150.

My bad, but is still way too low dispersion to compare a bat with a sling.

**Comment by Night-Pryanik** [comment]
What dispersion do you find appropriate for bats?

**Comment by AlecWhite** [comment]
Something like 450 dispersion. It needs to show that there's a reason why hitting objects with a stick didn't turned out as a popular viable weapon in ancient times.

**Comment by Coolthulhu** [comment]
It's pushing it when it comes to technical details (bat counting as gun, aiming the bat), game design (redundant, as it doesn't really offer any advantages over throwing), and realism (combat baseball? seriously?).

I don't really see it being salvageable for anything.

**Comment by BorkBorkGoesTheCode** [comment]
@Night-Pryanik @Coolthulhu I'm going to check if the "category": field can be used to fix gun category.

**Comment by Chezzo** [comment]
If anyone wants to play around with it, it is in a mod (from Japan, also has flaming balls) here:

http://chezzo.com/cdda/Homerun.zip

**Comment by kevingranade** [comment]
It would likely be a better approach to treat it like the railgun CBM and jyst have it luck in when wielding a bat and throwing an eligible projectile. 
Having said that, its a pretty nonsensical thing to do.

**Comment by Night-Pryanik** [comment]
Well, the reason for implementing this was mostly for fun. I don't expect anyone to use bat as a serious ranged weapon. If it's really offending someone's feelings, I'll close this PR.

**Comment by Zilenan91** [comment]
Kevin's suggestion is actually pretty neat, if an item with a volume under some specific value is thrown there would be a chance it gets lobbed with the baseball and does more damage

**Comment by BorkBorkGoesTheCode** [comment]
>Well, the reason for implementing this was mostly for fun. I don't expect anyone to use bat as a serious ranged weapon. If it's really offending someone's feelings, I'll close this PR.

It isn't offensive.

**Comment by DangerNoodle** [comment]
Amusing idea, terrible implementation.

**Comment by AlecWhite** [comment]
>If it's really offending someone's feelings, 

Is not that it is offensive is that:

>terrible implementation.

I mean equalling baseball and bat to a viable ranged weapon is more or less in the same range as gun-kata and dual wielding. Nice if it's a gimmick, not so much if it serious. But as always, that's my opinion.

**Comment by Mecares** [comment]
Maybe this is content better suited for the crazy cataclysm mod than for the base game?

**Comment by DragonLaggin** [comment]
Neat idea, but like @Mecares said, this may be better suited for the crazy cata mod instead. I would love to see this redone as Kevin suggested, also.

**Comment by kevingranade** [comment]
Put in Crazy Cataclysm + rework to make it "enhanced throwing" instead of "bat that acts like a bow" and it's good to go.

**Pull request closed without merging**
