### PR TITLE
Alternative ammonia recipe

### PR DESCRIPTION
**Pull request by Ali-Anomma**
#### Summary
Add recipes of ammonia that using sewage and manures

#### Purpose of change

After of removal of ammonia recipe that using coal(the recipe had nothing to do with the real production),one of the most essential crafting ingredient becomes finite.The real problem is ammonia depends on urine;and devs said they never add body waste system.
#### Describe the solution
I add two recipe that produce ammonia from sewer water and manure.It work arounds urine problem and also makes it renewable source like IRL.

#### Testing
I changed files on my computers CDDA data and it crafts perfectly.

#### Additional context
Ekran Alıntısı2

Ekran Alıntısı

### CODE REVIEW

**Comment by faefux** [comment]
Needs to be run through the styler it seems.

**Comment by Zeropol** [comment]
I question the recipes, but I've got not chemistry skills so feel free to disprove me.

Manure recipe : 
May need a filtration device and some diluted acid ( https://www.ars.usda.gov/ARSUserFiles/60820000/FY11/ASABE.pdf ). If I understood correctly it is also a lengthy process, so it may be better suited to use something like the "brew" we already have, who take time to transform. May give up auto-learn as a result.

Sewage recipe : 
I have the feeling if I go through the sewage and boil water, and won't end up with ammonia, so extra steps may be needed. What do you think ?

**Comment by actual-nh** [comment]
I doubt the sewage will have nearly as much urea/ammonia in it after a few days as it would on a pre-Cataclysm basis.

**Comment by actual-nh** [comment]
According to mlangsdorf on discord (<https://discord.com/channels/598523535169945603/598523535169945607/860198990926446642>), it is unlikely that alternative ammonia recipes will be used (at least until there's been enough time for IRREPLACEABLE_CONSUMABLE flags to start really applying).

**Comment by I-am-Erk** [comment]
The sewer one doesn't work because after a while that's just slightly unsanitary water. Nobody poops anymore.

The manure one could work, but not like this. I would suggest looking up how nightsoil is made into ammonia. If you want to do the whole process you can but it's not trivial. We do have all the code and components for it.

**Review by I-am-Erk — CHANGES_REQUESTED** [review]
The sewer one doesn't work because after a while that's just slightly unsanitary water. Nobody poops anymore.

The manure one could work, but not like this. I would suggest looking up how nightsoil is made into ammonia. If you want to do the whole process you can but it's not trivial. We do have all the code and components for it.

**Pull request closed without merging**
