### PR TITLE
Fix for SegFault on game load

### PR DESCRIPTION
**Pull request by DavidKeaton**
Latest master [092158a499e2c5...] segfaults when loading, and shows a debug message if it is fixed. This fixes both issues with minor additions.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
u fast gurl

**Comment by Rivet-the-Zombie** [comment]
We aim ~~for the head~~ to please.

**Comment by DavidKeaton** [comment]
<3

**Comment by KA101** [comment]
Dammit; worked fine on mine.  Thanks.

**Comment by DavidKeaton** [comment]
It's what teamwork is all about :-)

**Pull request merged**
