### PR TITLE
Allow mods to modify scenarios

### PR DESCRIPTION
**Pull request by BevapDin**
Example from More Survival Tools:

``` JSON
{
    "type": "scenario",
    "ident": "wilderness",
    "edit-mode": "modify",
    "add:professions" : ["wanderer", "caveman"],
    "add:allowed_locs" : ["swamp"]
}
```

This just adds the new professions and start location to the existing scenario. Mods may also change name, description points, flags and all the other properties of scenarios.

### CODE REVIEW

**Comment by MisterFelixFox** [comment]
I was right about to ask if it worked between two mods but your own example was the one I was wanting to modify. Thanks again

**Comment by Zireael07** [comment]
yaaay!

**Comment by BevapDin** [comment]
> if it worked between two mods

Yes, it does. Once a mod is loaded, it's data is basically merged into the already loaded core data. When the next mod gets loaded, it won't see any difference and can't even tell whether the existing data has been loaded from core files or from a mod.

**Comment by Malkeus** [comment]
Would it be possible to put in some documentation for this and other modification formats? Unless I've overlooked it, the only place to see what's possible is by dissecting the PR's that add the ability to mod an entry.

**Comment by BevapDin** [comment]
Yes, documentation is scheduled and will be added.

**Pull request merged**
