### PR TITLE
[Mythos] Add infrastructure for monsters

### PR DESCRIPTION
**Pull request by mythosmod**
#### Summary
Mods "Add mythos monsters to Mythos mod"

#### Purpose of change

Add in various mythos monsters to compliment the already existing ones

#### Describe the solution

- Add MYTHOS species to differentiate from the existing NETHER monsters
- For each of the following monsters, add faction to monster_factions (if required)
- Add deep ones (based on stats from extant monsters in Aftershock mod)
- Add ghouls
- Add ghasts
- Add elder things
- Add Dark Young of Shub-Niggurath
- Add nightgaunts
- Add shantaks
- Add rat-things
- A servitors of the outer gods

#### Describe alternatives you've considered

Keeping the species as NETHER, however if the existing Lovecraftian monsters ever need changing in the future the MYTHOS species will enable differentiation

#### Testing

Loaded into base game, given temporary looks_like sprites - need properly balancing but other creatures to add, factions working.

#### Additional context

Mythos Setup 1

Mythos Setup 2

Mythos 3

Mythos Setup 4

Mythos Setup 5

### CODE REVIEW

**Comment by actual-nh** [comment]
You will probably need to modify (in your mod) some base factions - there's a test that should tell you if you do. If so, take a look at Aftershock and/or DinoMod for how to do that.

**Comment by actual-nh** [comment]
> You will probably need to modify (in your mod) some base factions - there's a test that should tell you if you do. If so, take a look at Aftershock and/or DinoMod for how to do that.

Urk. I forgot that test doesn't currently run on mods - sorry, lack of sleep; we're moving as of tomorrow from North Carolina to Vermont. Do you have the program compiled at home, including the cata_test part?

**Comment by mythosmod** [comment]
> > You will probably need to modify (in your mod) some base factions - there's a test that should tell you if you do. If so, take a look at Aftershock and/or DinoMod for how to do that.
> 
> Urk. I forgot that test doesn't currently run on mods - sorry, lack of sleep; we're moving as of tomorrow from North Carolina to Vermont. Do you have the program compiled at home, including the cata_test part?

@actual-nh No problem, thank you for your help, I don't have a compiled build but I am sorting one out now - the test I assume is the 'generate_monfactions_attitude_matrix' one mentioned in the monster_factions file? Good luck with your move tomorrow!

**Comment by actual-nh** [comment]
> > > You will probably need to modify (in your mod) some base factions - there's a test that should tell you if you do. If so, take a look at Aftershock and/or DinoMod for how to do that.
> > 
> > 
> > Urk. I forgot that test doesn't currently run on mods - sorry, lack of sleep; we're moving as of tomorrow from North Carolina to Vermont. Do you have the program compiled at home, including the cata_test part?
> 
> @actual-nh No problem, thank you for your help, I don't have a compiled build but I am sorting one out now - the test I assume is the 'generate_monfactions_attitude_matrix' one mentioned in the monster_factions file? 

That (search for lines containing your new factions' IDs) and another one - 'monfactions_reciprocate'. For either of these to work with a mod, you'll need to run `tests/cata_test --mods=Mythos monfactions_reciprocate` and `tests/cata_test --mods=Mythos generate_monfactions_attitude_matrix`. 'monfactions_reciprocate' is checking for times when faction A may/will attack faction B, but faction B can't attack faction A.

> Good luck with your move tomorrow!

Thanks! Packing up computer tonight, so wanted to let you know before then.

**Pull request merged**
