### PR TITLE
Added Butter Dogs

### PR DESCRIPTION
**Pull request by Catalyst2114**
#### Summary
 ```SUMMARY: Content "Adds butterdogs"```

#### Purpose of change
Not enough recipes use butter and there's a lot of butter.

#### Describe the solution
I made butter dogs like hotdogs but no hot, just butter.

#### Describe alternatives you've considered
Could have made a butter sandwich, but that's icky. 

#### Testing
It runs, and nothing crashes.

#### Additional context
I made the butter dog take the tileset for peanut butter sandwiches cause there are no hot dog buns and the color of the butter matches mostly.

### CODE REVIEW

**Comment by kevingranade** [comment]
I thought this was something for Sweet Cataclysm.
@Fris0uman

**Comment by Someoneman** [comment]
Nice idea. There needs to be more ways to use condiments so we can get their calories without the morale penalties for eating/drinking them directly.

If we're adding bread with an obscene amount of butter on it, there should also be bread with a sane amount of butter on it if you want less calories but more morale. It would require 1 bread, 1 butter, and fire or a hotplate and a tool with cooking 2 (since it would be hard to spread cold butter on cold, soft bread).

**Comment by Rail-Runner** [comment]
> it would be hard to spread cold butter on cold, soft bread

Easily done if you use a knife to cut the butter (which is arguably more accessible than a heat source)

**Comment by pjf** [comment]
In terms of other butter usage that would fit, and not too hard to implement:

- Clarifying butter into ghee, which can then be used anywhere we want to use an oil.
- A 'buttered bread' item, which can be used anywhere regular bread can be used. This makes butter useful in any sandwich.
- Having a pie-crust recipe, or going directly into pies ( #38449 made an attempt at this)
- Croissants. The most glorious use of butter there can be.
- [Deep fried butter](https://en.wikipedia.org/wiki/Deep-fried_butter), because America. :)

**Comment by Little-119** [comment]
* [Butterbars! Made with one stick of butter and one paper wrapper](https://www.youtube.com/watch?v=03Hcy9e5hnM)

**Comment by Catalyst2114** [comment]
Nah, I'm talking about these. 
image

**Comment by Positronic-Girl** [comment]
If this is just a log of butter in between bread then I don't feel like... it really requires a whole recipe? 
Like you could probably just get the same experience by eating 1 butter, and then 1 bread in game. 

Like I feel like @pjf comment highlights it better, there are so many better things to do for uses of butter that isn't something as simple as this that can easily be disassemble and just... takes 0 effort?

Like everything they listed is... way better of an idea in my opinion than this? Buttered bread, or even butter + toast + jam? or in pastries or pies, or even deep fried butter which is a real thing in real life! There is stuff like Hollandaise sauce?

Here is a huge list of dishes that use butter from wikipedia that could probably be easily implemented i think:
https://en.wikipedia.org/wiki/List_of_butter_dishes
Like heck, puff pastry is basically just bread that is has huge chunks of butter rolled into it! that would be a great use.

**Comment by kevingranade** [comment]
I'm gonna pass on the joke food thanks.

**Pull request closed without merging**
