### PR TITLE
Sword weapon balance (Part 5 of melee weapon balance project)

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary

```SUMMARY: Balance "Rebalances sword weapons"```

#### Purpose of change
Mlangsdorf has been doing some deep analysis of the melee weapons and both analysis of dps of weapons and evaluating their strength ingame, and started a large "melee weapon balance" project. His analysis and his proposed values can be found here:
https://docs.google.com/spreadsheets/d/14eQIe4AO_f6OxCt1XcB4NLAs6-5R1wQW-ydZG0orYdY/edit#gid=1655515751
He wanted someone to start implementing the new values ingame, so i started work.

#### Describe the solution
Rebalances sword weapons according to excel sheet.
#### Additional context
Credit to Mlangsdorf for the excellent analysis and for most of the proposed values.
Credit to vastin for review of the excel sheet.
Credit to hymore24/hirmuolio for the initial complaint.

### CODE REVIEW

**Comment by SirPendrak** [comment]
As an owner of a zweihander, i would say give them block 2 instead of block 1 and nerf some other stats if needed for ballance. They usually come with parienhaken as second crossguard and siderings attached to giant main crossguard, yet they still get the same blocking quality as nodachi that has almost nonexistent crossguard.

**Comment by mlangsdorf** [comment]
I'm really happy with the nodachi versus zweihander balance point: nodachi is a touch faster and does a lot more cutting damage, the zweihander does a lot more bash damage, and their average DPS values are within 1% of each other.  But broadswords have WBLOCK2 so if Brian wants to up zweihanders to WBLOCK2, that's fine by me.

**Comment by Brian-Otten** [comment]
Zweihander and nodachi could conceivably both have W_block 2 because the blade of both weapons can be used for parrying, but the current high dps and sweeping strikes implies to me a more offensive style is being used, something like montante, where you let offense be your defense and keep the sword in constant motion, always on the attack.


What we could consider is giving either zweihander and nodachi a slight buff or estoc and longsword a slight nerf so that the larger, less defensive weapons eke out a bit more of a lead in raw  dps.

**Comment by mlangsdorf** [comment]
zweihander and nodachi have 26 DPS, broadsword and estoc have 24 DPS.

**Pull request merged**
