### PR TITLE
[CR] Being grabbed drastically reduce your dodging ability

### LINKED ISSUE #32064: Being grabbed doesn't affect player's dodge at all
In contrary with ingame description - "You have been grabbed by an attack. You are being held in place and **cannot dodge**, and blocking is very difficult." - game itself doesn't check for player being grabbed whatsoever. Being grabbed slightly reduce your actual dodge value due to `grabbed` effect reducing your speed, but it should reduce dodge value down to zero... right? Or it shouldn't?

Should we add a check for being grabbed and zero the dodge value in this case, or should we change the description instead and remove mention of "cannot dodge"?

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Balance "Being grabbed drastically reduce your dodging ability."```

#### Purpose of change
Closes #32064 - Being grabbed doesn't affect player's dodge at all.

#### Describe the solution
Added a check for being grabbed in `player::get_dodge` function. If you're being grabbed, then divide your actual dodge level by `(number of adjacent monsters with grab ability + 1)`. Thus one zombie that grabbed you will halve your dodge level; if there are two zombies, one of which grabbed you, your dodge level will be only one-third from the normal; and so on.

Also replaced check for hardcoded id of rollerblades with check for `ROLLER_FOO` flags. All items with one of these flags have the same penalty to dodge level.

#### Describe alternatives you've considered
Nullify dodge on being grabbed. But I think that would be an overkill and simply uninteresting.

#### Additional context
In general, being grabbed is much more dangerous now. One probably can allow oneself to being grabbed only if they are fighting one-on-one. Every adjacent monster will reduce one's dodge level further and further to the point they wouldn't be able to dodge at all if completely surrounded.

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
Zui Quan users: _triggered_

**Comment by Fris0uman** [comment]
Shouldn't the intensity of the `grabbed` effect play a role here?

**Comment by Night-Pryanik** [comment]
Well, it could decrease dodge level even more.

**Comment by l29ah** [comment]
The problem with grabs is that once a zombie grabbed you, you have to kill every zombie around you with grabbing ability to get ungrabbed, and even if you do, if a zombie with a grabbing ability comes near you next turn, you will magically remain grabbed.

**Pull request merged**
