### PR TITLE
Debug menu doc for contribution

### PR DESCRIPTION
**Pull request by remyroy**
It seems [many new contributors](https://github.com/CleverRaven/Cataclysm-DDA/pull/13957#issuecomment-155468824) are unaware of the debug menu and do not know how to create a good in-game test environment for their changes. I had that problem too.

This PR will add a section in CONTRIBUTING.md about this.

### CODE REVIEW

**Comment by illi-kun** [comment]
I'm not sure it's acceptable to put some links to external resource (http://i.imgur.com/)

**Comment by remyroy** [comment]
Would it be preferable to remove the image entirely or put it under /doc?

**Comment by narc0tiq** [comment]
I'd say we should support this being usable as offline documentation, in which case having the image present in the repo would be good. That said, you could also plug in a text dump like this:
```
┌────────────────────────────────────────────┐
│ Debug Functions - Using these is CHEATING! │
├────────────────────────────────────────────┤
│ 1 Wish for an item                         │
│ 2 Teleport - Short Range                   │
│ 3 Teleport - Long Range                    │
│ 4 Reveal map                               │
│ 5 Spawn NPC                                │
│ 6 Spawn Monster                            │
│ 7 Check game state...                      │
│ 8 Kill NPCs                                │
│ 9 Mutate                                   │
│ 0 Spawn a vehicle                          │
│ a Change all skills                        │
│ b Learn all melee styles                   │
│ c Unlock all recipes                       │
│ d Edit player/NPC                          │
│ e Spawn Artifact                           │
│ f Spawn Clairvoyance Artifact              │
│ g Map editor                               │
│ h Change weather                           │
│ i Remove all monsters                      │
│ j Display hordes                           │
│ k Test Item Group                          │
│ l Damage Self                              │
│ m Show Sound Clustering                    │
│ n Lua Command                              │
│ o Display weather                          │
│ p Change time                              │
│ q Set automove route                       │
│ r Show mutation category levels            │
│ s Cancel                                   │
└────────────────────────────────────────────┘
```

...which would remain representative without requiring any special resource at all.

**Comment by remyroy** [comment]
@narc0tiq Brilliant idea. It's in.

**Comment by narc0tiq** [comment]
Heh. A nice benefit of having the ncurses backend is having the ability to copy/paste anything Cataclysm displays -- though retaining colours tends to be non-trivial, so I'm glad we didn't have to do that.

**Comment by illi-kun** [comment]
I really like narc's solution.

**Comment by Night-Pryanik** [comment]
Sometimes I miss the :+1: button here on github for some cool posts like narc's.

**Pull request merged**
