### PR TITLE
[CR] Bionic multimeter

### PR DESCRIPTION
**Pull request by natsirt721**
#### Summary
Features "Add bionic multimeter and bench electronics kit"

#### Purpose of change
#73889 calls for low and medium power bionics: I deliver two.

The first is a simple 'integrated multimeter'. Electrical leads in the fingertips attached to a readout on the back of your hand or wrist or something. Touch two points to read current/voltage/resistance. I can imagine the character doing a 👌 to read the current inline :)

The second is an upgrade of the first, which adds a soldering iron and a screwdriver. The idea is that a professional electronics repairman would have all the things he needs at his fingertips (ha ha). I would prefer to just add fine screwdriving, but most of the electronics crafting recipes require the regular screwdriving quality, so this bionic provides both. There's a case to be made for adding fine cutting or fine bolt turning (and probably others) - but frankly I don't have much electronics repair experience so I don't know how useful those things would be.

I figure since the system is designed to conduct electricity without interfering with the user's nervous system that you'd also get a bit of protection from electrical damage for your hands and arms. I have no sense of scale but 3 seemed like a nice number to start with.

Practically, I feel these are simpler and less useful than the integrated multitool, so their prices and difficulty are based on that bionic.

#### Describe the solution
Added new bionics, CBM items, and pseudoitems. Updated soldering itemgroup with soldering iron, and ad-hoc soldering iron recipes where appropriate. Updated bionics item groups and exodii trading groups with new CBM items.

#### Describe alternatives you've considered
I chose not to make these conflict with the integrated toolset bionic, but they are doing similar things in a similar place, and I won't die on that hill.

#### Testing
Debug-installed bionics and checked recipes to ensure everything is working as intended.

#### Additional context
none

### CODE REVIEW

**Comment by RenechCDDA** [comment]
> Not sure why the hazmat test is failing. Somehow 'the beak' is getting into the list of bodyparts the hazmat suit covers. Which - sure, but I'm not touching any of that.

The (other) iteminfo test is checking the description of the hazmat suit, including what can repair it. You added a new item which can repair it, but the test does not know that. You will need to update the test's expected description to include your added "integrated soldering iron".

**Comment by natsirt721** [comment]
> The (other) iteminfo test is checking the description of the hazmat suit, including what can repair it.

Hmm, I updated the test but I put it in the wrong place. Its putting the integrated soldering iron at the front of the list with the welders instead of with the other soldering irons. Doesn't seem great but it doesn't look like I can specify the order anywhere?

**Comment by natsirt721** [comment]
The one I don't understand is this one:
image

**Comment by Maleclypse** [comment]
That's a test that we know fails because of something someone did with colors that they haven't been able to come back and fix.  It doesn't actually break the game so we've left it in for them to fix at some point.

**Pull request merged**
