### PR TITLE
Renamed generic 'bird egg' variants to have '<species> egg' names

### LINKED ISSUE #25141: Bird eggs incompatible and indiscernible
Bird eggs show up in game simply as "bird egg", regardless of species. Which means there are nine different types of items that appear perfectly identical based on item descriptions, even though they have distinct item IDs.

However, cooking recipes require all eggs to be of the same type (or perhaps do not support the new egg types at all? I can't even tell because all nine bird egg types appear identical in-game). It's extremely difficult to figure out if you have the proper type of eggs, or how many you're lacking, when all bird eggs appear identical.

Bird eggs either need to be clearly marked by species so players can tell them apart. and all recipes (should) be expanded to use all egg types.

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: I18N "Renamed generic 'bird egg' variants to have '<species> egg' names"```

#### Purpose of change
Fixes #25141

### CODE REVIEW

**Comment by FulcrumA** [comment]
Won't that make everything too easy to identify even when the egg was just foraged from some bush? Is there a point now to making chicks be just described as brown, yellow without stating their name etc if we can even identify eggs themselves?

**Comment by cake-pie** [comment]
@FulcrumA I think it's best to treat this as a hotfix for now.

The problem in #25141 is: you can substitute any ONE of the [`eggs_bird`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cc20c28ca16636013574fac6c31c0f3772edacf9/data/json/requirements/cooking_components.json#L22-L38) items when crafting, but then all of the N eggs required by the recipe must be of the same type (species) -- there is no way to use a mix of different eggs to meet the required count. In the crafting screen you're likely to see all red ```bird egg OR bird egg OR bird egg (etc)``` which is not helpful; the problem is worsened if you want to batch craft.

That is frustrating to deal with, so this fix slightly ameliorates the problem for now: with automagical egg identifying powers, you can look at what eggs you have and be able to tell what you can cook with them.

To go back to indistinguishable eggs (and chicks) would need modification to the crafting requirements system to provide a way for `eggs_bird` to specify that the items are fully interchangeable -- mix and match to meet required count of N, rather than requiring N × any one of the items.

**Comment by FulcrumA** [comment]
True, it'd be good if there'd be code handling for mixing variants of the same item. I am just unsure (but hopeful) that the intent between the eggs and chicks was to make them initially hard to distinguish, not something meant to be changed by itself.

**Comment by cake-pie** [comment]
> make them initially hard to distinguish

That's what I think the intent was as well, perhaps something like mushrooms where you need certain level of survival skill to be able to identify poison/halluc mushrooms. But getting it to work that way is going to need quite a bit of additional machinery that we don't yet have.

**Comment by OzoneH3** [comment]
Does it really matter that you know which bird the egg is from since they are 100% the same anyway?
I could change the names to "big white egg" and "small brown egg with white dots" just to make them distinguishable which the player most certainly would be able to. In the end the player would meta know anyway which egg is from which bird.

**Comment by FulcrumA** [comment]
>Does it really matter that you know which bird the egg is from since they are 100% the same anyway?

Kinda. It's not a big one but a nifty feature to make them indistinguishable by name so the player finding some eggs in the wild, at least without decent survival won't know which is which. Because they are 100% same only for cooking, but now many bird eggs are used to grow actual birds, be it for creating an egg farm or general poultry raising.

**Pull request merged**
