### PR TITLE
Move the list of initial available martial art styles to json.

### PR DESCRIPTION
**Pull request by BevapDin**
The styles are (as before) linked to the traits, now they are stored as part of the mutation data.
If the player selects several traits that provide initial styles, they are all available and the player can freely choose from any of them. If only one style is available, the game will automatically choose it.

This allows for example to create a trait that has contains only one initial martial art style and the game will choose it automatically without bothering the player.

### CODE REVIEW

**Comment by KA101** [comment]
OK, should I expect the other traits to receive similar consideration?

**Comment by BevapDin** [comment]
> OK, should I expect the other traits to receive similar consideration?

What exactly shall I do? This PR moves logic from C++ to json, it wasn't intended to change the behavior of the game, it *allows* people to add martial initial art styles to traits.

You can add initial martial art styles to any trait you want, but I'm not going to do so because I do not know the first thing about martial art, I prefer guns (-:

**Comment by KA101** [comment]
Uh, the generic MA traits?  I'm only seeing the profession ones here.  ;-)

**Comment by BevapDin** [comment]
My fault, they are several screens above the other other so I missed them, will be done shortly.

**Comment by KA101** [comment]
np, when I installed the profession ones I had to put 'em there so the profession traits got assigned.  Generi-MA happen before the profession applies.  Sorry for the confusion.

**Comment by BevapDin** [comment]
Fixed and added documentation.

**Comment by KA101** [comment]
Stanging bug I must've missed when writing 'em.  Sorry about that.  >_<

**Comment by KA101** [comment]
Oops, this only lets you pick one style.  I took MA training, Self-Defense, Melee Weapons, and Blackbelt, was given the relevant list, and after picking Eskrima, sent into the game.  (Was entitled to three more picks.)

Not ready for prime time.

**Comment by BevapDin** [comment]
Fixed.

**Pull request merged**
