### PR TITLE
[WiP] Removed faulty auto-fire mods.

### PR DESCRIPTION
**Pull request by OzoneH3**
Fixes: #20980

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
If I'm not mistaken, this mod need to be obsoleted.

**Comment by Cyrano7** [comment]
@OzoneH3 You should make it so it doesn't spawn either. Its still in item groups.

**Comment by kevingranade** [comment]
it does need proper obsoletion yes.
Since it's broken in current games, just having it silently disappear is fine, but I think if we just remove the item definitions it will cause load failures.  Removal from item groups is also needed.

Do both mods have the same error?  If not that could be a clue to what is breaking.
The EW_pack mod at least seems to be based on something that actually would work as opposed to the mainline item, so it'd be nice for it to keep working, but removing it is still better then it staying broken.

**Comment by OzoneH3** [comment]
The autofire mod from EW_pack has the same problem yes.

What is the best way to obsolete items? Is there a file or something where
I can add the items that are obsolete?

**Comment by AMurkin** [comment]
See #17914 for example.

**Comment by OzoneH3** [comment]
Will have to look into this some more.

**Pull request closed without merging**
