### PR TITLE
Do not auto swap advanced inventory panels

### LINKED ISSUE #45900: Don't switch advanced inventory panels when you re-select them
# Is your feature request related to a problem? Please describe.
Assume I want to open adv. inventory with [4] on the left panel and [6] on the right panel. So I open the adv. inventory, left tab is highlighted, I press [4], then right, then [6], done. However, if when I opened the inventory, [4] was already on the left pane, when hit [4], it instead switches panes, and now my left pane is whatever used to be there on the right one instead of [4], and from this point it screws things up because I have to look intently which pane it actually selected vs what I was planning to select, filters get swapped as well, etc etc.

Another scenario: assume I wanted to open adv. inventory with "all" on the left. I open the inventory, hit "a", but turns out, "all" was already on my right pane, so I end up swapping panes. In general this does not sound terrible, but my right pane had a filter like "CBM, chain, oxy, auto" from previous time I was managing it, and now I have to notice that the filter has moved to the left pane, either purge it or swap panes again, lots of extra actions that should not have been there.

This behavior prevents muscle memory from working because when selecting panes, you need to actively pay attention to which panes there currently are and make sure to not accidentally try to switch to a pane that's already selected.

I understand that having the same left and right pane makes no sense and so instead of dealing with this problem when player tries to select them like that, they're switched instead. Boom, easy implementation, problem solved. However, this behavior requires visual feedback from actions where it should not be needed.

Another example of a similar menu is Total Commander, Norton Commander and other such file managers and all of them allow opening left and right panes to the same directory even though it does not make much sense from file management perspective.

# Describe the solution you'd like
Actually allow opening both panes targetted to the same tile. Just ignore item moving commands because moving item from tile to the same tile indeed makes no sense.

# Describe alternatives you've considered
I also tried using default layout to make sure that adv inventory is opened to some panes that I rarely use (like 5, 5[vehicle]), but problem still exists if I want to change panes later. I have also tried the option that resets adv inventory layout after every operation, but it has proved extremely annoying to move multiple items with that option on because AIM resets its state after every single item moved. This seems like an unrelated bug outside of the scope of this issue.

# Additional context
Depending on others' perception of this swapping feature, maybe we don't even make it an option, but just change the behaviour instead. Maybe some people use it, I don't know, but surely not me.

### PR DESCRIPTION
**Pull request by satheon49**
#### Summary

SUMMARY: Interface "Prevent advanced inventory from swapping panels"

#### Purpose of change

Fixes  #45900

As described in the issue, swapping advanced inventory tabs when selecting the square shown in the other tab is confusing.

#### Describe the solution

Changing squares in the active tab does not affect the inactive one whatsoever. While this allows having the exact same square open in both tabs there was already logic in place that prevents swapping items in this case.

Furthermore you can now freely toggle between vehicle and non vehicle mode by reselecting the square with the vehicle.

Swapping panels has been delegated to a hotkey (Default: 'x' for exchange, s/S were sadly already taken by sorting)

#### Describe alternatives you've considered

Not really an alternatives but I considered always having the left tab in focus when opening the advanced inventory. This would allow for muscle memory and predictable behavior when moving items (basically you can close your eyes and know that / + 4 + TAB+ 6 will have WEST selected in the left tab and EAST selected in the right).

#### Testing

Filled a few squares around me with items and a vehicle and moved stuff around with the advanced inventory.

### CODE REVIEW

**Comment by Raikiri** [comment]
I definitely like the idea of having left pane always selected first when you open the inventory.

**Comment by andrei8l** [comment]
> I did change the advanced inventory to always open with the left tab focused.

IMO it's better if you integrate an extra keypress in your muscle memory ( left arrow to trigger `LEFT` action) than to force this behaviour on everyone. I want my AIM to maintain its exact state when I re-open it.

**Comment by Raikiri** [comment]
> > I did change the advanced inventory to always open with the left tab focused.
> 
> IMO it's better if you integrate an extra keypress in your muscle memory ( left arrow to trigger `LEFT` action) than to force this behaviour on everyone. I want my AIM to maintain its exact state when I re-open it.

Problem is, I don't use arrow keys for anything in game. Everything that I've encountered so far can be controlled by numpad or other buttons. Panes can be controlled by "tab", but it toggles them instead of changing the active one. So using arrow keys for just one action in the game? Maybe it's a solution, I certainly can live with it even though I'd personally prefer it to work otherwise. I'll let you guys decide which behavior should be the default one.

**Comment by satheon49** [comment]
I would argue that it would bring AIM in line with every other tabbed window in the game. No other window with tabs remembers its focus. The closest is probably the construction window that remembers the selected category (but that one doesn't have tabs).

@andrei8l Can you describe the scenario you have in mind where it is useful for AIM to remember its focus?

**Comment by andrei8l** [comment]
> @andrei8l Can you describe the scenario you have in mind where it is useful for AIM to remember its focus?

Presumably any scenario and I think more interfaces should maintain their state. As a concrete example, perhaps I'm browsing my stash to figure out where to put some items. I *could* swap my panes around but maybe some people prefer the right pane in the same way you prefer the left.

**Comment by satheon49** [comment]
it is just that UIs should be in a consistent state when you open them. If you are repeating an action like using AIM instead of hauling to move items in a straight line keeping the focus is fine it is helpful to keep the focus but in general you won't remember which tab you left AIM in the last time.

Anyway, I am reverting the forced focus for now since it seems to be somewhat controversial.

**Comment by Davi-DeGanne** [comment]
#45900 is not a bug, it was implemented as an intentional behavior. See my comment in that thread for details.

**Comment by satheon49** [comment]
The update contains the following change:
You can now toggle the auto swap behavior within AIM itself (similar to the category selection mode). By default AIM acts like before and will swap tabs when you select the same square as the destination. If you toggle that behavior off (default hotkey "g" because AIM already uses almost every key) you can toggle that behavior off. Settings are saved as most AIM settings per character.

**Comment by satheon49** [comment]
I moved "toggle swap on reselect" to a global option. Aside from bugs I consider this PR finished. Whether or not it should be merged is not for me to decide.

The basic gist of the discussion in #45900 is:
- swap on reselect is useful because it allows you to double tap target location followed by source
- not swapping on reselect is intuitive for new users (you want to swap stuff from a to b so you select a, TAB, b, TAB back)

**Comment by esotericist** [comment]
for anyone possibly watching who wasn't participating in the conversation, the conclusion from discussion in #45900 is that we aren't going with this solution at this time.

**Pull request closed without merging**
