### PR TITLE
[ Aftershock ] Migrating Artifact to Relic data

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary

SUMMARY: Mods "Aftershock : Migrate Artifact data to relic data"

#### Purpose of change

Help Korg deprecate existing artifact_data in json and learn how the new relic code works at the same time.

#### Describe the solution

Replace all instances of artifact data with passive and active relic data.

#### Describe alternatives you've considered

none

#### Testing

Currently I'm missing a mandatory id in the active use json lines.  I'll figure that out tomorrow.

### CODE REVIEW

**Comment by KorGgenT** [comment]
a couple of these items may need the last PR i'll be doing, which will be "regenerating ammo". have you tested out if the hologram cloak works properly? i'm betting it won't use relic charges for the use action.

**Comment by Maleclypse** [comment]
> a couple of these items may need the last PR i'll be doing, which will be "regenerating ammo". have you tested out if the hologram cloak works properly? i'm betting it won't use relic charges for the use action.

None of the use actions work properly anymore except one that seems to have infinite charges.  So I'll keep an eye on the artifact charge PR's.  Thanks!

**Comment by KorGgenT** [comment]
i will make sure to @ you when i make the PR as i'll update magiclysm with it as decent examples.

**Comment by KorGgenT** [comment]
ok, updated and tested the json. works just fine.

**Pull request merged**
