### PR TITLE
[CR]Fix the geese

### PR DESCRIPTION
**Pull request by DevianProdigy**
#### Summary
None

#### Purpose of change
geese have the fears overwritten but are still using the SOUND fear trigger inherited from ducks

#### Describe the solution
Removing inheritance and adding the previously inherited properties

#### Testing
Loading the game and yelling at a goose

#### Additional context
image

### CODE REVIEW

**Comment by actual-nh** [comment]
SOUND is unfortunately also inherited from the species - see species.json.

**Comment by actual-nh** [comment]
Ping: @Venera3?

**Comment by Venera3** [comment]
`SOUND` is a weird trigger, since it *isn't* one really - it just flat-out makes monsters path towards/away from you. Also, triggers inherited from species is a bother, and the reason I had to juggle a lot of triggers around for bugs.

**Comment by DevianProdigy** [comment]
> 
> 
> `SOUND` is a weird trigger, since it _isn't_ one really - it just flat-out makes monsters path towards/away from you. Also, triggers inherited from species is a bother, and the reason I had to juggle a lot of triggers around for bugs.

Can you confirm if geese are intended to have the `SOUND` fear trigger? if not I might be able to trial and error the triggers out of species.json to make them not flee when yelling

**Comment by Venera3** [comment]
I have no experience in shouting at geese (and Canadian geese are pretty rare round where I live), so I can't comment on the intention. It's entirely possible that species overwriting the fear triggers wasn't a thing back when they got added, or whoever made the triggers didn't  know about it - it would explain the redundancy. I don't think it will break anybody's grand vision of waterfowl behavior, so adjust away.

**Comment by I-am-Erk** [comment]
Closing as stale for now. Feel free to reopen if you are active.

**Pull request closed without merging**
