### PR TITLE
CBM Spawn Cleanup

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Removes CBMs inappropriate locations."

#### Purpose of change
Removes some remaining Earth CBM spawn locations.

#### Describe the solution
Removes non-Exodii CBM spawns and drops from several locations and loot lists.

#### Describe alternatives you've considered
None.

#### Additional context
Left the broken cyborg as-is. Left lab specials.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I'm VERY MUCH against this.

Screw retcon in general and screw Exodii in particular. I want Earth-made bionics, not some goddamn weirdo mumbo-jumbo aliens.

Removing `autodoc_installation_programs` from two loot lists means they won't spawn anywhere at all.

**Comment by NetSysFire** [comment]
I think they are just trying to make it work with the current lore chosen. I would discuss that with @I-am-Erk. I don't like the Exodii either but luckily there is the Dark Days of the Dead mod.

**Comment by Broken27** [comment]
Shouldn't this wait until the Exoddi are actually complete.

**Comment by SariusSkelrets** [comment]
Yeah IIRC the plan is to wait for the Exodii are fully done before getting rid of earth-cbm. That's why labs still have them

­>I want Earth-made bionics

DDA-earth have power armor, which in a pre-apocalypse scenario is almost better on all fronts than bionics. 

Earth-bionics would've been conceived before the end, where you want to have replacements if someone can't do what you're asking them and where not being able to doff your equipment is a _very big drawback_

Since bionics, unlike power armors, need invasive surgeries before use, are a pain to repair, can't be transfered or removed without harming the owner and thus are unsuitable for mass use it's very unlikely they would've be anything else than power armor extensions or a select few bionics sold as harmless gadgets to civillans

Humans from another universe that didn't cared about the drawbacks and impracticality of bionics (the Exodii) allow to simply skip that problem while adding CBMs in the core progression, getting rid of failure chance that forced to grind skills before installation and removing the CBM lab loot RNG

**Comment by Xaritscin** [comment]
Question. should this also apply to Anthills? the CBM you get there is rare i think but its not really gamebreaking.

**Comment by Theawesomeboophis** [comment]
I love the exodii and the lore behind them, but isn't this too soon? As far as I know, the exodii are still a WIP faction and I don't think exodii cbm spawns have been set yet, I may be wrong tho.

**Comment by esotericist** [comment]
guys, this is a draft. that means it's not intended to go in yet.

**Comment by a-chancey** [comment]
> I'm VERY MUCH against this.
> 
> Screw retcon in general and screw Exodii in particular. I want Earth-made bionics, not some goddamn weirdo mumbo-jumbo aliens.
> 
> Removing `autodoc_installation_programs` from two loot lists means they won't spawn anywhere at all.

Autodoc self installation is planned to be going away, IIRC. I believe the plan was that you’d need an operator (doctor NPC at Tacoma or Hub01) after a quest to bring them an autodoc, so the installation programs will be useless

**Comment by a-chancey** [comment]
> Question. should this also apply to Anthills? the CBM you get there is rare to spawn i think but its not really gamebreaking.

I believe #55999 already took care of anthill CBM spawns, among others

**Comment by kevingranade** [comment]
The bionics_common group continues to spawn in labs after this, "bionics" spawns in labs and microlabs, bionics_mil spawns nowhere, which might be a bit of a problem if there are any items unique to it.

Overall I'll sit on this for a bit, but given the above I'm not seeing a problem, we've had a ton of availability creep over time with bionics appearing in some truly silly places (storage units?), and ratcheting that back is reasonable to do independent of making them more available via Exodii or elsewhere.

As for rejecting overall development direction, that's a non-starter, CBMs are moving primarily to Exodii, end of story.

**Comment by a-chancey** [comment]
> The bionics_common group continues to spawn in labs after this, "bionics" spawns in labs and microlabs, bionics_mil spawns nowhere, which might be a bit of a problem if there are any items unique to it.
> 
> Overall I'll sit on this for a bit, but given the above I'm not seeing a problem, we've had a ton of availability creep over time with bionics appearing in some truly silly places (storage units?), and ratcheting that back is reasonable to do independent of making them more available via Exodii or elsewhere.
> 
> As for rejecting overall development direction, that's a non-starter, CBMs are moving primarily to Exodii, end of story.

I missed this until I just got the merge notification. 

CQB is now unattainable, but all of the other mil_bionics seem to be in the bionics group now.

I can create an issue later.

**Pull request merged**
