### PR TITLE
Implemented drawing of CJK characters with ImGui screens

### LINKED ISSUE #72162: Imgui y/n query popup fails to display translated string on Windows
### Describe the bug

Imgui y/n query popup fails to display translated string on Windows.

### Attach save file

N/A

### Steps to reproduce

1. Change language setting to Chinese.
2. Restart the game.
3. Press 'q' to try to quit the game.
4. The y/n popup appears with an unrecognizable string.

### Expected behavior

I expect that translated string appears on the screen, instead of "????????"

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-7807-g2ba772a1dd-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝)<color_dark_gray>（92.9%）</color> [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Bugfixes "Implemented drawing of non-English characters in ImGui screens"

#### Purpose of change
Fixes: #72162

#### Describe the solution
Implemented a font "fallback" system in ImGui to allow CDDA to interrupt ImGui's drawing flow to draw glyphs using CDDA's Font::OutputChar method.

#### Describe alternatives you've considered
There are open PRs in the ImGui repo that implement dynamic font atlases which could potentially solve this problem, but they seem far from being viable enough to be a better solution than this.

#### Testing
Changed the language to Chinese, opened up the keybindings screen, and verified that the screen displays properly

#### Additional context
The 'x' and 'y' position that ImGui tries to draw at doesn't quite work for Cataclysm. I needed to modify those by magic numbers to make the font align properly. I'm still not sure why it's needed.

### CODE REVIEW

**Comment by katemonster33** [comment]
Just noticed something... On text entered into an input field, the cursor position doesn't match the space between glyphs

**Comment by katemonster33** [comment]
> Just noticed something... On text entered into an input field, the cursor position doesn't match the space between glyphs
> 
> Edit: with CJK characters I mean

this should be good now

**Comment by ZeroInternalReflection** [comment]
I distinctly recall this PR having a note requesting Curses testing, but I'm apparently confusing that with a different PR.  Regardless, I'd call the impact on the Curses build "unfixed, but a step in the right direction".  
In the current state of things, ImGui windows will print out a bunch of garbage instead of the appropriate characters (Simplified Chinese pictured):
Curses--Before

After this PR, any unhandled glyphs instead print out as blank space:
Curses--After

Notably, the blank space appears to be the appropriate size for the unprinted text, so it looks like the character width calculations are working.  Contrast the Chinese above with Russian below:
Curses--After--Russian

**Comment by katemonster33** [comment]
> I distinctly recall this PR having a note requesting Curses testing, but I'm apparently confusing that with a different PR. Regardless, I'd call the impact on the Curses build "unfixed, but a step in the right direction". In the current state of things, ImGui windows will print out a bunch of garbage instead of the appropriate characters [...]
This is a good catch. The fault for the original issue likely lies in the ImTui backend. I definitely wouldn't expect this PR to fix it unfortunately, since this has everything to do with graphical textures that curses builds know nothing about. 

I would go ahead and make a separate issue for that, we will need to track that as a blocker for moving the UI completely to ImGui.

**Pull request merged**
