### PR TITLE
New location: Regional airport

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content "Adds regional airports"```

#### Purpose of change
There are never enough stuff to explore in the overmap.
+Added a place, where you can find small airplanes, which will be a thing soon, *right*? 

#### Describe the solution
Added a regional airport, with a:
* Small hangar
* Large parking lot
* Waiting area
re_airport_1
* control tower
* fuel station
re_airport_2
re_airport_3

#### Describe alternatives you've considered
Adding an international airport. I *may* add that later.

#### Additional context
I wanted to add an "apocalyptic variant" with a lot more zeds, that were trying to evacuate, but failed.
I didn't know what items to add in the crates.
Fuji's More Buildings already has an airport, but I didn't really realize it until now.
Also, I found this:
missed

### CODE REVIEW

**Comment by curstwist** [comment]
Crates: car parts, metal stuff like springs, etc.

**Comment by mlangsdorf** [comment]
I'm not aware of any plans to add airplanes in the near future.  I've offered to help other people add them, but no one has taken me up on the offer and I have other things I want to do first.

**Comment by nexusmrsep** [comment]
I love the idea. The runway looks *awfully* short though. And I bet no flight authority would allow to build anything directly at the end of any end of the runway. Perhaps if you'd make it longer, like 2 overmap tiles extra, you'd also get free space for hangar or two at the side.

**Comment by LovamKicsiGazsii** [comment]
There are 5 runway om tiles.
I agree, I could make a longer runway. I am not sure if I can fix the other issue you mentioned. That would require a lot of changes.

**Comment by kevingranade** [comment]
Please extend the runway to 10 tiles, that's the shortest runway I can find a reference for.
Ideally I agree the hanger must be off to the side, but if you aren't up to it we can fix that later.

**Comment by LovamKicsiGazsii** [comment]
Current one:
og

Concept:
new

**Comment by I-am-Erk** [comment]
As well as making the runway so long, I'd suggest having an empty field tile after the runway as part of the special just to make sure nothing spawns in that space.

**Comment by kevingranade** [comment]
Tack an empty field on each end and that concept is perfect.

**Comment by LovamKicsiGazsii** [comment]
New airport:
airport

**Comment by I-am-Erk** [comment]
This is beautiful, good work

**Pull request merged**
