### PR TITLE
Island prison and prisoners tweaks

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Tweaked island prison and prisoners."```

#### Purpose of change
Thanks to @TheMurderUnicorn's [videos](https://www.youtube.com/playlist?list=PLaY-Sp2A8N-BA2drMeOWRkQQNtf3LGNg0) in which he playtested the location and the challenge itself I noticed several issues with the prison and its inhabitants.

#### Describe the solution
- Added spawn of some clothing to the coat racks in the admin buildings;
- Added a locked bar door behind the normal door in the armory;
- Reduced number of drugs spawning in the kennels;
- Reduced number and chance to spawn of misc stuff in filling cabinets;
- Added spawn of soft and hard drugs in the infirmary glass fridges;
- Added spawn of cleaning stuff to the laundry;
- Added socks and sneakers to the starting gear of both convicts professions.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Rail-Runner** [comment]
Is it intended that prisoners don't get socks?

**Comment by Night-Pryanik** [comment]
> Is it intended that prisoners don't get socks?

Will add them too.

**Comment by Night-Pryanik** [comment]
Done.

**Pull request merged**
