### PR TITLE
[Magiclysm] Remove elf spawn in forge

### LINKED ISSUE #47735: Hostile Forgeborn
# Describe the bug

I was playing Magiclysm and approached a Forge of Wonders. A Forge Born immediately went hostile on me despite the fact that I hadn't attacked anything in the area. It approached me and attacked my accompanying NPC (the one that is at the Wizard's Vacation start by default)

# Steps To Reproduce

1. Make a Magiclysm character
2. Visit a Forge of Wonders
3. Get wrecked by super powerful magic enemies that apparently aren't meant to be hostile.

# Expected behavior

I am told these enemies are supposed to be neutral.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9804-gbc7931f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I was also attacked by the cyber mastiffs at the PrepNet Orchard in Aftershock, this may not be a mod issue.

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Bugfixes "Worker Elf Spawn turns Forge Hostile"

#### Purpose of change
I started investigating a bunch of recent reports of the forge always being hostile by the time players arrive.  Found this as the cause.  Several issues reported, I'm not sure if any of them are open still. Fixes #47735 partially.

#### Describe the solution
Removed the worker elf that aggroed against Forgeborn on sight.

#### Describe alternatives you've considered
None

#### Testing
I am able to get to Forge's without finding them hostile more often now.

#### Additional context
I wish hostile would fade upon a monster killing a target that had damaged it or was part of a hate group but that is beyond my ability.

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
I shall make a new location specific to workshop elves.

**Comment by Theawesomeboophis** [comment]
DEBUG    : Error: Json error: data/mods/Magiclysm/monstergroups.json:EOF: couldn't find end of string, reached EOF.

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 952
Getting this error while testing, how do I fix this?

**Comment by anothersimulacrum** [comment]
You are probably missing a `"` somewhere.

**Comment by Theawesomeboophis** [comment]
I do not see any missing "s, my guess is that it is a spacing problem.

**Pull request merged**
