### PR TITLE
[Backport?] Fix feral wizard species from #71275

### PR DESCRIPTION
**Pull request by Psithief**
#### Summary
Bugfixes "Fixes species of feral wizards and feral butchering"
#### Purpose of change

This marks feral wizards as the feral species to fix continuity. This also surfaced the issues with feral butchering for backporting.
This was already fixed in experimental in #71275 but that added extra content that may not work.

#### Describe the solution

The species of the monsters is changed from "HUMAN" to "FERAL"  Adds the bugfix to ensure feral species is correctly marked similar to human.

#### Describe alternatives you've considered

Asking someone else to raise a pull request.

#### Testing

Try butchering a feral thaumaturgical researcher. There will no longer be an extra prompt.

#### Additional context

N/A

### CODE REVIEW

**Comment by Maleclypse** [comment]
When you say butchering are you using the butchering prompt or the dissection prompt?

**Comment by Psithief** [comment]
> When you say butchering are you using the butchering prompt or the dissection prompt?
It prompts either way.
Butchering gives the message `Would you dare desecrate the mortal remains of a fellow human being?` and dissection the message `Really dissect the remains of a fellow human being?`

**Comment by Maleclypse** [comment]
> > When you say butchering are you using the butchering prompt or the dissection prompt?
> 
> It prompts either way. Butchering gives the message `Would you dare desecrate the mortal remains of a fellow human being?` and dissection the message `Really dissect the remains of a fellow human being?`

Yes normally it does that. I compiled your changes cause I don’t have a current 0.H candidate downloaded and neither prompted. Which if nothing went wrong in my compile means ferals don’t prompt at all in 0.H and this PR won’t do anything. In current experimental butchery still prompts the player to feel bad but once you’ve dissected enough humans it stops prompting for dissection while still prompting for butchering. So I wanted to double check that you’ve tested before and after on the 0.H candidate. If you have I’ll recompile sometime this week and see if I can replicate the behavior you are experiencing.

**Comment by Psithief** [comment]
Yes, I have tested that the prompt is absent if the species is set to `FERAL`. This is also a basic consistency issue, where all monsters with a name starting with 'feral' except these two were marked as species `FERAL`.
@Standing-Storm Is there anything more I can add?

**Comment by Maleclypse** [comment]
So I'm going to need you to goto https://github.com/CleverRaven/Cataclysm-DDA/blob/0.H-branch/src/activity_handlers.cpp and search for the word `FERAL`  the fact that you won't find it means that this fix is not complete compared to experimental.  Give me to next weekend and I'll PR the rest of the fix against your branch.  I'm on vacation and am not sure how much time I have to do real dev work.

**Comment by Maleclypse** [comment]
Haahaha quick and easier than I worried.

**Comment by Psithief** [comment]
I can see that we're not on the same page about this.
I saw inconsistent behaviour between [0.H RC] mod content and base content and raised this pull request to address it.

I've realised that you're telling me that, in experimental, the prompt appears for both humans **and** ferals. That's not the case in the [0.H RC] branch and thought the [0.H] behaviour was intended.
I was completely unaware that the behaviour had been changed in experimental and wasn't looking to backport new behaviour.

If the new behaviour is be backported into [0.H], then I can see that this pull request is not very useful at all; my commit would only give the researcher a cold or flu effect 1% of the time.

**Comment by Standing-Storm** [comment]
> @Standing-Storm Is there anything more I can add?

No, they were missed when HUMAN was changed to FERAL (since they're in mods) and this is the proper correction.

> If the new behaviour is be backported into [0.H], then I can see that this pull request is not very useful at all; my commit would only give the researcher a cold or flu effect 1% of the time. (looking at the C++ code, there may be more in the JSON)

There are some effects that key off species FERAL in experimental and they may exist in 0.H. It's worth it for consistency in any case, and the chance of cold/flu does matter too.

**Comment by Maleclypse** [comment]
This is a good catch psithief. Appreciate it!

**Pull request merged**
