### PR TITLE
Fungal rebalance 2: Dramatically slow sporeling maturation

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Balance "Dramatically slow fungal sporeling maturation rate"```

#### Purpose of change
As one of the main factions of interdimensional horror, the fungus - while extremely compelling - remain so poorly balanced that many people just turn them off.

In a final push before 0.E, I would like to rebalance fungus, and improve their existing content to be more interesting.

One of several aspects to the problem is the rapid growth of fungaloids. Presently a sporeling evolves to a fully grown fungaloid in a few turns.

#### Describe the solution
I tested several different growth rates, and settled on making it ten times as long. Now sporelings evolve to fungaloids in around 1-4 hours. This is still very quick, but much less egregious. Since sporelings don't release spores, this slows fungaloid crush syndrome by a lot.

#### Describe alternatives you've considered
Reducing sporeling spawn rate and not making maturation so slow

#### Testing
Tested as above.

#### Additional context
[part 1 here](https://github.com/CleverRaven/Cataclysm-DDA/pull/35435)

### CODE REVIEW

**Comment by SirPendrak** [comment]
I think i saw some time ago an idea to make fungi reproduce only in dark. Its appealing, because most WTF moments are when a survivor goes to sleep, and then he wakes up in an alien world. And most people sellep at night when its dark.

**Comment by I-am-Erk** [comment]
I'd like to leave it a bit fast for now and assess the overall impact on fungal spread, because between this and reducing spread rate of fungal terrain, it's going to be pretty dramatic. I think pushing it further is going to nerf fungus too much actually

**Comment by I-am-Erk** [comment]
I'd like to leave it a bit fast for now and assess the overall impact on fungal spread, because between this and reducing spread rate of fungal terrain, it's going to be pretty dramatic. I think pushing it further is going to nerf fungus too much actually

**Comment by Shibimon** [comment]
Props on efforts for fixing fungaloids, till now they are a "keep out of reality bubble or turn off" problem and while the speed affecting multiplication and growing will definitely will be useful, there is an issue probably outside the scope of this PR about them.
Irl different fungi have varied preference on what to eat and grow into, and while a fantasy superfungi could grow everywhere there is a very real threat to most of them that would be nice the fungaloids respect and is access to water or humidity.
What nutrients fungaloids can find in concrete to make them grow in ther, instead of using that effort into 10+ nice and cozy earth tiles?
Im learning to homegrow mushrooms and it would be really nice to see some nature logic shaped into them, or go further and even get homegrowing edibles, vitamin supplements, psychedelics and other medicinals (or revamp how to get marloss and other things arround that) since we already have pressure cookers, glass jars, plastic bags, filters, syringes and other basic instruments, instead of the bland and weird "bury spores on farmland" thing we have now.

**Comment by I-am-Erk** [comment]
Mycus will have its own limitations, but don't make the mistake of assuming they work like real fungus. They resemble fungus but they're not the same.

**Comment by Shibimon** [comment]
Im not saying they need to be like real fungi, just using a bit of real organism logic behind how it works, so players could interact with it somehow, biologic reasoning instead "it just grows".
Being prone to infest forests and creatures, organic materials, even more arround swamps, being super agressive on getting "sugary" materials, or slimes and blobs, decaying and drying on consumed zones, tendrils of nutrient sharing connecting focal points, transformation of materials instead "now is fungus and losed forever" are all neat ideas that could be worked arround it and make sense to be there, of course they could have some more special fantasy interactions with things like zombies and mutated creatures.
the only thing "they resemble fungus" right now is just growing and a few similar names.

**Comment by I-am-Erk** [comment]
Mycus is similar to the blob, in that it doesn't seem to be here to eat. Its limitations are largely going to be related to whether or not it can connect to its extradimensional form.

It would be neat to have them have Nutritional requirements and such, but it's a pretty tall order for code.

**Comment by dissociativity** [comment]
I definitely think the spread is far too quickly, the issue is that it's only within the reality bubble and cannot be seen from afar on the overmap like zombie hordes so the player can view and control it.

I think it should honestly take at least a week to cover a single overmap tile, I don't really have the coding knowledge to do the overmap stuff, but I can imagine it working similar to how hordes work, only it doesn't move, and instead spreads.

**Comment by Amoebka** [comment]
In general, why does fungus spawn so many independent bodies, shouldn't spreading the mycelia take priority?
I think it would be cool if actual walking fungaloids were more like an immune response - spawned specifically to counter some threat (zombies, animals, players), and then reprocessed (i.e. despawned) after they are no longer needed.
This would also solve the main issue of overpopulating. Reducing the rate helps some, but in the end it's still exponential growth, which is fundamentally wrong.

**Comment by Nerezza** [comment]
Since someone mentioned the "wtf moment" where people wake up and see the alien world of fungi that have overrun the town (and since I'm not sure of a better place to post this) I wanted to note that it's always kind of neat seeing the "ecosystem" of a town change when the fungal monsters move in, but at the same time experienced players know that it's time to get out of dodge because fungal infection is **no joke**.

It would be great if there were easier ways to avoid fungal infection from "lesser" fungal monsters encountered in that expanding zone, so that the player isn't discouraged from exploring it and interacting with the fungal monsters so long as they wear proper protection.

**Comment by TechyBen** [comment]
> Irl different fungi have varied preference on what to eat and grow into, and while a fantasy superfungi could grow everywhere there is a very real threat to most of them that would be nice the fungaloids respect and is access to water or humidity.
Yeah. In the forums I also suggested the possibility of the growing nodes/roots similar to real fungus, as both a story element and a spread type/speed limiting balance. (Ring worm and many other fungus make ring like growths as food is eaten/runs out, others are web/sponge like, and not all are completely engulfing like the Fungal threat in game).

**Comment by MrOlaf** [comment]
It is a change in a good direction. Fungus tends to consume the map too fast.

**Pull request merged**
