### PR TITLE
Aftershock Exoplanet: Glacial tunnels

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
Mods "Aftershock Exoplanet: Glacial tunnels, a new low-risk area."

#### Purpose of change
These tunnel systems are intended to be low to mid-danger areas that you can explore and forage for food, not completely unlike vanilla forests. Later on they should also function as a refuge from hazardous weather conditions and as entry points for more dangerous and deeper dungeons

Note that this PR only adds the bulk of the  tunnel mapgen, and the tunnels currently have no monsters, harvestable plants or rewards of any sort. These would need to come in successive and hopefully much smaller PRs

#### Describe the solution
I  designed these to be relatively easy to expand in the future.  Different tunnel "biomes" can be easily added through the creation of new mapgen palletes, and all the map pieces are assembled piece-by-piece using chunks, with different chunks providing the base floor, then walls, and then special pieces like rivers, or large decorative elements. So adding future tunnel types would mostly be a matter of creating a few more chunks and altering the spawning order/frequency of these chunks.

Anyhow I did two biomes to test the concept,
Heres a Volcanic version of the tunnels, full of geothermal vents and jagged rocks.
image

And heres the Forested version of the tunnels, which are much more lush and full of plants:
image

And also made underground river maps to test the chunk layering idea:
image

#### Testing
This is a wip mostly becuase I still need to fix a few errors in the mutable overmap definition.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Oh also @jbytheway was interested in checking whether the palette inheritance/sharing exhibited by this overmap special is an intended feature an accident or a bug.

**Comment by jbytheway** [comment]
I think it is a bug that this palette sharing is working.  I think the way that you should implement it is to make a palette whose only purpose is to refer to the other palettes.  So it would be something like
```json
  {
    "type": "palette",
    "id": "afs_tunnel_any",
    "palettes": [ "afs_tunnel", { "distribution": [ [ "afs_tunnel_volcanic", 1 ], [ "afs_tunnel_forested", 1 ] ] } ]
  }
```
and then you'd have all the other mapgen that currently defines a distribution instead use `afs_tunnel_any`.

My plan is to introduce some sort of namespacing of parameters at some point, and the default namespace will be the context in which it's defined.  Parameters will only be considered the same if their name and namespace match.  So to merge parameters from different contexts you would have to explicitly set their namespaces to be the same.

In the mean time, you can avoid future breakage by consolidating the palette choice as above.  And I think it's better that way anyway, because then the distribution is only defined in one place, which makes it much easier to add new palettes in the future.

(Of course, I don't think I've ever tested this combination of palette nesting and parameterised palettes, so you might encounter a bug).

**Comment by John-Candlebury** [comment]
Thanks for the review!
And yeah that does look much more convenient.

**Comment by Night-Pryanik** [comment]
@John-Candlebury these tunnels will spawn in `Aftershock` mod, yet title tells us that they are for `Aftershock Exoplanet` mod. Some sort of oversight?

**Comment by John-Candlebury** [comment]
No what is happening is that the the data of the mod is all in Aftershock, but the actual placement for the mutable special requires a specific overmap tile `"ravine_edge"` that isnt generated outside Aftershock Exoplanet, so they dont ever get placed unless both mods are active.

Works like that because Aftershock exoplanet is intended to have minimal content on its own, to make the future mod merge easier.

**Pull request merged**
