### PR TITLE
[CR] Seasonal color/symbols for furniture and terrain 

### PR DESCRIPTION
**Pull request by BevapDin**
With all the new trees, it's difficult to know what tree is meant. Some color/symbol combination are already used for different things: blackjack oak (unharvested) looks like a dead hickory tree (brown 7), the former is usable, the later isn't. It's annoying when you try to harvest every available tree around and you go back to that unharvested oak tree, only to find it's actually a dead hickory tree.

This PR allows terrain and furniture to have different symbols and colors, based on the current season. Btw. this is already possible within tilesets.

I propose this color scheme of trees (already implemented in the last commit):
- Normal, unusable trees are green.
- Usable trees that are only _currently_ not usable (they have no fruits in the current season, or they have already been harvested) are light green. This allows players to spot potentially interesting trees, but does not "clutter" the  map with many different colors/symbols.
- Usable trees that are currently usable (fruits) have specific colors, like it was before.
- In winter, all trees are brown (or should they be gray?).

This allows to use more colors for the fruit trees as they only need to be unique among the trees that have fruits at the same time.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> In winter, all trees are brown (or should they be gray?).

It would be cool if fruit trees had something to tell them apart from the rest. For example, gray background, inverted colors (brown bg, black fg) or different fg color from the rest.

> blackjack oak (unharvested) looks like a dead hickory tree (brown 7)

I don't see a change here. Am I missing something?
It would also be cool if oak got a new color to tell it apart from other trees.

Maybe something like:
* Green background means harvestable now and will regrow
* Brown background means harvestable in other season (including because it was harvested now)
* Gray background means harvestable once
* Default black background means no 'e'xamine interaction with the tree

**Comment by John-Candlebury** [comment]
I like Bevap din proposition most, as I think it would be better to reserve the colored backgrounds to denote that the object is question is bigger/thicker/stronger than a normal tree or structure.  

Just in case we eventually add things like "reinforced concrete walls" in bunkers and "triffid trees".

**Comment by BevapDin** [comment]
>> In winter, all trees are brown (or should they be gray?).

> It would be cool if fruit trees had something to tell them apart from the rest. For example, gray background, inverted colors (brown bg, black fg) or different fg color from the rest.

That's only for flavor and can be changed easily, I'm not fixed on that.

>> blackjack oak (unharvested) looks like a dead hickory tree (brown 7)

> I don't see a change here. Am I missing something?
> It would also be cool if oak got a new color to tell it apart from other trees.

Yeah, I might have missed something there. I'll make the dead hickory tree green. It may not really match its real color, but it is consistent with the color scheme: the dead hickory tree is unusable, just like any generic tree.

> Maybe something like:
> Green background means harvestable now and will regrow
> Brown background means harvestable in other season (including because it was harvested now)
> Gray background means harvestable once
> Default black background means no 'e'xamine interaction with the tree

I wouldn't make a different in color for harvestable once and harvestable often. How would you apply that to a hickory tree, which is harvestable often for the nuts, but only once for the roots?

But I like the usage of background color. Indeed having a background for currently harvestable seems good, it indicates "there are items there".

So I refine my scheme to:

- Always unusable trees (including dead ones) are green, default background (can be chopped down).
- Currently unusable trees are light green, default background. One usually doesn't care *why* it's not usable right now. If one is going to prepare for the future (e.g. marking the apple trees to collect from them later), one has to check out the individual tree anyway as they all may have a different harvest season.
- Currently usable trees have a background color (gray or brown or white or blue?) and a specific foreground based on the tree type. This is a tree you want to walk up to and examine it.

----

> I like Bevap din proposition most, as I think it would be better to reserve the colored backgrounds to denote that the object is question is bigger/thicker/stronger than a normal tree or structure. 

> Just in case we eventually add things like "reinforced concrete walls" in bunkers and "triffid trees".

I like those ideas, too. But what about a blue background, like you get when there are items on the tile inside the terrain/furniture? This seems to be kind of consistent: there never can be actual items there because the trees have the NOITEM flag, but the fruits are (kind of) there.

**Comment by chaosvolt** [comment]
Ah good, I was afraid this would add seasonal variants in a way that would add delicious transparency errors to tilesets. The way this is being implemented seems sound, just a matter of working out the details.

**Pull request merged**
