### PR TITLE
now copper wire recipe is more balanced

### PR DESCRIPTION
**Pull request by Ali-Anomma**
#### Summary
copper wire recipe is unblanced and make it uncraftable. i made some balances
#### Purpose of change
the recipe is so long,that makes uncraftable
#### Describe the solution
applying my changes.
#### Describe alternatives you've considered
leaving same recipe,but set craft time as few seconds

#### Testing
i changed same files on my computer and works with no problems

### CODE REVIEW

**Comment by wapcaplet** [comment]
Your "Summary" section needs to be properly formatted, for example `Content "Make copper wire recipe more balanced"`

This seems like an extreme change - instead of crafting 1 unit of wire in 3 minutes, your new recipe allows crafting 200 units in only 10 minutes. That is a 60x speed-up. And 200 units of wire is a lot; what if I only want 5 or 10 units?

Instead, maybe change the existing recipe to give a batch savings with `"batch_time_factors": [ 80, 5 ]` or something in that range. That would give an 80% time savings when crafting 5 or more units.

**Comment by anothersimulacrum** [comment]
It would be best if you found a source on this sort of thing (drawing copper wire from copper), and based time on that.

**Comment by actual-nh** [comment]
This should really be two recipes: One to get copper wire from copper, and the other to (with duct tape or whatever) convert copper wire into (crude) cabling.

**Comment by kevingranade** [comment]
Obsoleted by #48127

**Pull request closed without merging**
