### PR TITLE
Further strict JSON parsing

### PR DESCRIPTION
**Pull request by mugling**
- Enable strict parsing for `MAGAZINE` and `GUN`.
- Update all `core` and `mod` content.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
`--check-mods` breaks hard.

**Comment by Coolthulhu** [comment]
Actually, it's not just mod content, the `aim_speed` restriction is broken, since `"aim_speed": -1` is correct.

**Comment by mugling** [comment]
> Actually, it's not just mod content, the aim_speed restriction is broken, since "aim_speed": -1 is correct.

In what context is it correct?

**Comment by Coolthulhu** [comment]
Gunmods use it, but with this PR, it's "outside allowed range".

**Comment by mugling** [comment]
I don't get any errors for `--check-mods`. What is the `debugmsg`?

**Comment by Coolthulhu** [comment]
* Durability out of range for some mods (fictional weapons has durability 11, pk has 666)
* Aim dispersion out of range (core)
* Aim speed out of range (core)

**Comment by mugling** [comment]
Found it - I didn't push the last commit that fixed those. Sorry for that.

**Comment by mugling** [comment]
Also rebased against master

**Pull request merged**
