### PR TITLE
bird weakpoints

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "bird weakpoints"

#### Purpose of change

consistent feature implementation

#### Describe the solution

Basic bird weakpoint proficiency and other relevant proficiencies applied to bird monsters, new weakpoint group based on the pterosaur weakpoint group in DInoMod

#### Describe alternatives you've considered

Keep waiting for someone else to do it, a more advanced proficiency for murdering mutants, don't bother with a special bird proficiency and just use the flying proficiency for things that don't fly

#### Testing

Game loads no errors, proficiencies appear and work as expected, new weakpoints appear to work correctly

Screen Shot 2022-09-21 at 6 14 21 PM

Screen Shot 2022-09-21 at 6 15 58 PM

#### Additional context

N/A

### CODE REVIEW

**Comment by anoobindisguise** [comment]
Why not just use "creatures of flight"?

**Comment by LyleSY** [comment]
I thought about that but birds have somewhat different bodies than other flying things and not all birds fly, bloated corvid the most important example

**Comment by Ragecrabbo** [comment]
Albino penguins should probably be included in the profession and recieve the weakpoint damage aswell, despite being a much less mundane type of bird

**Comment by LyleSY** [comment]
Done, good call

**Comment by TheShadowFerret** [comment]
>Albino penguins should probably be included in the profession

At first I thought this meant Lyle had added a Bird Watcher profession with the proficiency, and now I want one :(

**Pull request merged**
