### PR TITLE
[RDY]Extract fungal effects into a new class

### PR DESCRIPTION
**Pull request by Coolthulhu**
How I imagine #20220 being implemented.

### CODE REVIEW

**Comment by CoroNaut** [comment]
I notice you have a fairly large amount of if/else statements within fungal_effects.cpp. Just note that this has caused performance issues in the past.

**Comment by bdgackle** [comment]
@CoroNaut, The 'if else' code appears to be straight out of player.c.  There is rather a lot of that in there.

As it stands, it's a 12k line file with no clear overarching purpose, so this sort of refactoring at least gets the code organized by functionality.  By keeping the changes limited to breaking out into a file, we can avoid introducing bugs while doing the large refactor.

@Coolthulhu, I wonder whether it makes sense to even have a class here.  The references to the two global state objects that you are injecting are still basically global state.  What if we added those as parameters and converted these four functions into simple free functions?  It doesn't seem like they NEED to have any associated member data.

This (and a whole lot of other stuff in player.c) probably make more sense as a collection of free helper functions than as members of some class.

**Comment by kevingranade** [comment]
I need to be careful, I replied to this via email but I don't see it here.

Seems reasonable, eventually we could implement my ramblings about interface segregation and only pass a subset of the game and map interfaces into this kind of thing, then we'd have a solid shot at mocking those interfaces and making this code unit testable.

This improves things more than I thought it would at first, sweet.

Free functions in a namespace vs class members in a tiny class, there's not much difference there, so I'd prefer to just leave it up to implementor's taste.

**Comment by Coolthulhu** [comment]
@bdgackle
> The references to the two global state objects that you are injecting are still basically global state. What if we added those as parameters and converted these four functions into simple free functions?

@kevingranade 
> Free functions in a namespace vs class members in a tiny class, there's not much difference there, so I'd prefer to just leave it up to implementor's taste.

I went with class because:
* If needed, there could be a global object of the class, with default game and map. Or a field of one of the classes
* Less arguments per function - many of our functions have 5+ arguments, which can be hard to read
* Less problems with default arguments: if we want to make game/map arguments default to global ones, it can be changed in one function rather than 4

I'm not too terribly attached to that idea, but I still think it's slightly better.

**Comment by kevingranade** [comment]
Another pro for a class is that if we consistently encapsulate code in
classes, it's easier to add caching or lazy evaluation later.

Side issue, since this grabs references to game and map, it would be nice
to disable its' move and copy constructors to keep people from stashing it
somewhere.

**Comment by bdgackle** [comment]
I can't think of any real pros for the free-function approach other than avoiding unnecessary boiler plate in cases where the class is a glorified namespace (and even that is debatable due to parameter counts, as was pointed out).

Since there are some real upsides to including the containing class, I'd agree that it's the right approach!  Suggestion withdrawn.  :-)

**Comment by Coolthulhu** [comment]
Anything to be done here?
Is this approach proper?

**Comment by kevingranade** [comment]
> Seems reasonable, ...

> This improves things more than I thought it would at first, sweet.

> Side issue, since this grabs references to game and map, it would be nice
to disable its' move and copy constructors to keep people from stashing it
somewhere.

**Comment by kolsurma** [comment]
This is only slightly related but what is the overall feeling toward large if-elseif blocks? The blocks like
```c++
bool fungal_effects::spread_fungus( const tripoint &p )

...

    } else if( m.has_flag( "SHRUB", p ) ) {
        if( x_in_y( growth * 10, 200 ) ) {
            m.ter_set( p, t_shrub_fungal );
            converted = true;
        } else if( x_in_y( growth, 1000 ) ) {
            m.ter_set( p, t_marloss );
            converted = true;
        }
    } else if( m.has_flag( "THIN_OBSTACLE", p ) ) {
        <very similar to above>
    } else if( m.has_flag( "YOUNG", p ) ) {
        <very similar to above>
    } else if( m.has_flag( "WALL", p ) ) {
        <very similar to above>
    }
```
seem to be poorly designed to me, though I'm no code-golfer who could one-line it (and even if I were one-liners tend to be hard to read).

**Comment by Coolthulhu** [comment]
> This is only slightly related but what is the overall feeling toward large if-elseif blocks?

Should be avoided. This one only looks like this because I didn't change it to a proper set.
The typical alternative I use is creating a structure for the block, one entity of the structure per `else if`, then change the blocks into a `std::map`.

**Pull request merged**
