### PR TITLE
[RDY] Cathedral mapgen JSONify

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Conversion of `cathedral` mapgen from `map::draw_map` to JSON.

### CODE REVIEW

**Comment by sick-trigger** [comment]
basement is missing the blank bodies near the relic. to help keep the loneliness at bay.

**Comment by ZhilkinSerg** [comment]
Thanks for the tip.

**Comment by Coolthulhu** [comment]
Conflicts with one of the other PRs I'm testing, the conflict may be trivial but I currently don't have the time to fix it.

**Comment by ZhilkinSerg** [comment]
Superseded by #20393

**Pull request closed without merging**
