### PR TITLE
Clean up PK's mod

### PR DESCRIPTION
**Pull request by Cyrano7**
After https://github.com/CleverRaven/Cataclysm-DDA/pull/16726 I thought I'd take a look.

### CODE REVIEW

**Comment by pisskop** [comment]
I do appreciate the help with things.  Im not always attentative.

Why would you delete the lines between the brackets and the datum?

And of course every time these get updated I have to close PRs because merge incompatibility.

**Comment by Rivet-the-Zombie** [comment]
>And of course every time these get updated I have to close PRs because merge incompatibility.

Or [rebase them](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/).

**Comment by Cyrano7** [comment]
@pisskop Extra empty lines that don't increase readability should be removed because its extra unnecessary data in the file. Same with the white spaces at the end of lines and the already defined values. It doesn't seem like much but when added together with the hundreds of other files it starts to compound.
As for your other PRs. I think it's better to make sure the content you have merged so far is good to go before trying to add more on top of it. Quality before quantity.

**Comment by pisskop** [comment]
wat

thank you for reading through the errorfree code in order to change completely aesthetic aspects of the legible code that im not even sure how many people actually use.

**Comment by cainiaowu** [comment]
https://www.smashingmagazine.com/2012/10/why-coding-style-matters/
http://stackoverflow.com/questions/127916/is-programming-style-important-how-important

**Comment by Cyrano7** [comment]
@pisskop Error free? I wasn't going for aesthetics believe me. Typos are bugs, the capitalization falls under grammar, double spaces is for display, defaults and extra spaces falls under performance. I wasn't sitting here staring at lines of code my text editor can make these changes on its own. Also you need to turn on your spell check. If the editor your using doesn't have one you need to use one that does.

**Comment by Xpyder** [comment]
@pisskop 

If you aren't sold on the importance of readability in your code, or you need general guidelines I suggest checking out PEP 8 [https://www.python.org/dev/peps/pep-0008/](https://www.python.org/dev/peps/pep-0008/)

It's specifically geared towards python but a lot of the concepts are applicable to any language.  The key insight being that code is read much more often than it is written.

**Comment by pisskop** [comment]
Okay.

Since other people have to sort through it and the extra or improperly labeled lines are only slowing down the game and creating bloat.

Ive probably been looking at it wrong; all ive been interested in in something that ran without complaining to me.

**Comment by mugling** [comment]
> Ive probably been looking at it wrong; all ive been interested in in something that ran without complaining to me.

The issue here is that other authors will have to help maintain your contribution. For example each time I refactor the JSON loading code I often have to update mods to be compatible.

**Comment by pisskop** [comment]
jaa

**Pull request merged**
