### PR TITLE
Fal to scar mags

### PR DESCRIPTION
**Pull request by DifferentLevelDan**
https://www.youtube.com/watch?v=t9QXqIE6pdI

### CODE REVIEW

**Comment by DangerNoodle** [comment]
I suspect that for balance purposes, it might be better restricted to booklearn, as how to correct the fitting might not be common knowledge.

Needing calipers to measure it, as the video states, suggests that a firearm repair kit or gunsmith kit might be sensible to include in the recipe, as that could be reasonably implied to include measuring tools.

**Comment by illi-kun** [comment]
I'd prefer to see this recipe in 'realguns' mod.

**Comment by DangerNoodle** [comment]
That might be interesting to see. What other real-world firearm recipes would be viable in the mod? Any actual firearms perhaps? I am vaguely aware that generic pipe SMGs exist in the CGP mod, and used to be part of the main game in the past.

**Comment by mugling** [comment]
> I'd prefer to see this recipe in 'realguns' mod.

Probably technically correct but of limited appeal. Crafting bloat is causing such sufficient problems with latency that we are having to rewrite much of the implementation to deal with it.

As a result this should definitely be mod content.

**Pull request closed without merging**
