### PR TITLE
Adds LivePeople tileset

### PR DESCRIPTION
**Pull request by rainbowjose**
#### Summary
SUMMARY:  Content "Adds LivePeople Tileset."

#### Describe the solution
Just enable tileset as usual, also  you can enable custom indicators through mods. I recommend "hybrid".

#### Purpose of change
For the better game experience.

#### Additional context
Based on this discussion:
#26676

Original author's repo:
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

### CODE REVIEW

**Comment by rainbowjose** [comment]
Something "wrong" with json, but it not.

**Comment by cainiaowu** [comment]
You need to check the build output log: 
http://gorgon.narc.ro:8080/job/Cataclysm-PR-Builder/10372/console
```
12:53:52 Invalid Summary line, please provide a summary similar to the following:
12:53:52 SUMMARY: Features "Added ability to fly."
12:53:52 Makefile:1081: recipe for target 'validate-pr' failed
```

your summary line should be quoted by three "```" both at top and bottom to pass this validate step.

**Comment by rainbowjose** [comment]
Oh no, this shit again. As I can see my PR have proper summary. I giving up.

**Comment by cainiaowu** [comment]
In CI build, the build failed with following error:
```
Formatted data/mods/LivePeople_Chesthole/mod_tileset.json
make: *** [data/mods/LivePeople_Chesthole/mod_tileset.json] Error 1
make: INTERNAL: Exiting with 4 jobserver tokens available; should be 3!
The command "make -j3 RELEASE=1 BACKTRACE=1 DEBUG_SYMBOLS=1 CROSS="$CROSS_COMPILATION"" exited with 2.
```
which means that your "data/mods/LivePeople_Chesthole/mod_tileset.json" doesnt match the requried code style. You need to lint those file with json formatter first.

**Comment by rainbowjose** [comment]
> In CI build, the build failed with following error:
> 
> ```
> Formatted data/mods/LivePeople_Chesthole/mod_tileset.json
> make: *** [data/mods/LivePeople_Chesthole/mod_tileset.json] Error 1
> make: INTERNAL: Exiting with 4 jobserver tokens available; should be 3!
> The command "make -j3 RELEASE=1 BACKTRACE=1 DEBUG_SYMBOLS=1 CROSS="$CROSS_COMPILATION"" exited with 2.
> ```
> which means that your "data/mods/LivePeople_Chesthole/mod_tileset.json" doesnt match the requried code style. You need to lint those file with json formatter first.

You can check that json. I can't see problem in file.

**Comment by cainiaowu** [comment]
Check my PR #26620 as an example, your summary line is clearly different with mine.
My summary line has a nice grey background and different font setting because I quote them with proper [Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by AMurkin** [comment]
> You can check that json. I can't see problem in file.

Add new line at the end of file.

**Comment by cainiaowu** [comment]
Also may related with CRLF setting, you might need a proper text editor to edit those files. (Not quite sure though, but it has caused some similar issues before.)

**Comment by AMurkin** [comment]
I guess your summary line have (or had) two spaces after `SUMMARY:`.
But it rendered to one space in html view.

Log fragment:
image

I will PR a change to summary validator to fix this issues.

**Comment by rainbowjose** [comment]
Not working:
Image of Yaktocat

Working:
image

**Comment by rainbowjose** [comment]
Hoooray

**Comment by rainbowjose** [comment]
Jenkins rebuild

**Comment by rainbowjose** [comment]
Travis rebuild

**Pull request merged**
