### PR TITLE
Warehouse shelf

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Content "Added warehouse shelf furniture"```

#### Purpose of change
Breaking down #37024 to smaller portions for easier review.

#### Describe the solution
- Adding the furniture
- Replacing `f_rack` in s_hunting
- Replacing `f_rack` in abandoned_warehouse
- Replacing `f_rack` in s_hardware

#### Testing
Spawned in the locations to check the furniture changes.

### CODE REVIEW

**Comment by RarkGrames** [comment]
Added construction recipe

**Comment by KorGgenT** [comment]
are these the shelves you can put pallets onto? the really high ones?

**Comment by RarkGrames** [comment]
> 
> 
> are these the shelves you can put pallets onto? the really high ones?

Something like [this](http://www.besonshelf.com/Uploads/image/20170629/20170629091951_97142.png).
Not the ones that you need a forklift to take things from, but something that can hold a lot of stuff.

**Comment by I-am-Erk** [comment]
I'm not sure this is practically different from f_utility_shelf, is it? That was what I had in mind when I added utility shelving.

**Comment by RarkGrames** [comment]
> 
> 
> I'm not sure this is practically different from f_utility_shelf, is it? That was what I had in mind when I added utility shelving.

It can hold 2500L. The game will need huge shelves at one point when the warehouses get full of bulk goods or similar things. A utility shelf for example can only hold two 200L oil barrels.

**Comment by I-am-Erk** [comment]
That's probably an error from the redone storage volumes. Utility shelves are meant to cover large shelves you'd use in shops, warehouses, and storage areas. Smaller shelving is covered by f_rack.

I'd suggest you make this a tall palette shelf, the sort that you need a forklift for, since we don't have those and they're a type of warehouse shelf, and in this PR you can bump up the storage space of utility shelves.

**Comment by RarkGrames** [comment]
> I'd suggest you make this a tall palette shelf, the sort that you need a forklift for, since we don't have those and they're a type of warehouse shelf, and in this PR you can bump up the storage space of utility shelves.

Ok, I can do that. What changes do you need on the warehouse shelf furniture itself? Also, what was the original intended storage space for the utility shelves?

**Comment by I-am-Erk** [comment]
I didn't have a strong opinion on storage space when I set them up. You could base it on what you need the shelf to be able to do

**Comment by RarkGrames** [comment]
I increased the utility shelf storage capacity to 1500L.

**Pull request merged**
