### PR TITLE
Adds armored leather jacket and vest.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
These are armored clothes crafted in a similar fashion to the extant
armored fingerless gloves.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ooh, this concept I like. What would be the logical leg equivalent, if any? Chaps might be interesting, but this as-is seems neat.

**Comment by Rivet-the-Zombie** [comment]
I didn't really consider leg armor much, as I was inspired by Max's jacket in the Mad Max films. Cutting an armored jacket down into an armored vest would be doable, I just haven't added a recipe for that method.

**Comment by Coolthulhu** [comment]
10 on arms+torso isn't very cumbersome. Unarmored jacket is `17/2=8` - just 2 encumbrance for the iron plates made of scrap?

That 95 coverage - chance of attack passing through halved from the unarmored version. Unless the plates cover the places without leather (in which case the encumbrance needs another boost), it shouldn't be more than 90.

And the crafting recipes - just 2 tailoring (easier than a hoodie?) to hammer out viable metal plates out of scrap and attach it to a leather jacket without making it noticeably more encumbering.

Armor values seem somewhere in the range to make all common zeds unable to get through it.

**Comment by chaosvolt** [comment]
Hmm. And yeah, armored chaps aren't very Mad Max-ish OR Fallout-ish.

Additionally, I'm pondering if byproducts can be made to return more than one item, so it could output both leather and a scrap or two.

I would be in favor of suggesting the coverage stay the same as the standard leather jacket, and have the encumbrance be at least 5 more than the unarmored version, rather than 3 more. Or possibly as much as 10 more, unsure.

**Comment by Zireael07** [comment]
5 more seems good before further testing.

**Comment by chaosvolt** [comment]
Probably. Ease it up a bit, mess with it, then add moar if needed. X3

**Comment by Rivet-the-Zombie** [comment]
The tailoring requirement is low because all you've got to do is attach the plates; forming them from scrap is where the fabrication skill comes into play. I've raised the fabrication requirement by a point, and increased the encumbrance by another two points, and dropped the jacket's coverage back to 90. Keep in mind that none of these have the STURDY tag, so they still wear out fairly quickly without constant maintenance.

**Comment by Coolthulhu** [comment]
> The tailoring requirement is low because all you've got to do is attach the plates

I'm not a tailor, but I'd expect attaching metal stuff to leather without use of nails, wires etc. would be a bit harder.

> forming them from scrap is where the fabrication skill comes into play

2 fabrication is pretty much free. Is hammering viable, barely encumbering armor plates, using no real tools (only a hammer-shaped lump of metal at a stick) really that easy?

> none of these have the STURDY tag, so they still wear out fairly quickly without constant maintenance.

Armor damage from attacks happens in two cases:
* When the raw (unscaled by piercing) damage is twice or more the armor value
* (If not sturdy) Once per 200 hits otherwise

The first point won't happen often.
Maintenance of leather items is easy, meaning that having to maintain it probably won't be enough of a problem to make it a balancing factor.


I'd bump tailoring to 3 (1 below creating most leather items) and fabrication to 3.

On paper it looks like it's still a bit too good.
18/18 (when reinforced, which is easy) at 90% for 11 encumbrance. With underwear below it, it means any zombie weaker than a brute has 90% chance to deal 0 damage with the regular melee attack.
Compare:
* Leather body armor: 15/15 at 85% for 13 encumbrance (clearly worse than modded jacket here)
* Plate armor: 30/30 at 90% for 20 encumbrance (much more encumbering, but doesn't protect more, except from brutes and up)
* Nomad gear: 14/14 at 100% for 10 (clearly better, but then nomad gear requires high skill)
* Chainmail armor: 23/23 at 95% for 10 (rare, so excusable) (Also, holy fuck why is it so much better than plate?)
* Scrap suit: 36/36 at 90% for 35 (horrible, unusable)

It shouldn't be better than the professional leather body armor, which AFAIR is also book-locked and only appears at tailoring 4 or later.

**Comment by kevingranade** [comment]
I feel like if you want to stick with the 'just sew plates into the jacket'
approach, the most obvious way to reign in the balance is to reduce
coverage even more, it's only going to provide that peak armor value if an
attack hits a plate, and they're going to need to be widely spaced to avoid
encumbrance if it's not carefully designed.

**Comment by chaosvolt** [comment]
Though if I recall, reducing thickness to tweak its armor value is also an option.

**Comment by vache** [comment]
My thoughts: zombies should have a better chance to damage through armor or to damage armor itself.  Zombie attacks are mostly claws, bites, and grabs, which should have a pretty high chance to damage anything made of cloth, and grabs should have a decent chance to damage leather.

**Comment by chaosvolt** [comment]
If I recall, there was a fragile tag or something like that added, but I doubt it would be appropriate for this.

The ability to have the whole "hitting weak points in the armor" be a mechanic would mitigate things, but that's an unrelated, complex addition.

**Comment by Rivet-the-Zombie** [comment]
I'll take care of this as soon as I've got Internet connectivity again.

**Pull request merged**
