### PR TITLE
More Duplexes

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
- Adds 10 new various duplexes.

- Fixes mailboxes (missing flags)

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Honestly the whole furniture.json could use a linting but I didn't want to do the whole file in case anything was purposefully formatted a certain way.

**Comment by cosmiccoincidence** [comment]
Ok, I looked at furniture.json and didn't see anything that looked purposefully formatted so I ended up linting the whole file with the linting tool anyway.

**Comment by ZhilkinSerg** [comment]
There are straw whitespaces:

image

**Comment by cosmiccoincidence** [comment]
Just linted the whole Duplex.json but didn't commit it as that seems to have been the only spacing mistake.

**Comment by cosmiccoincidence** [comment]
- Combined the old duplex with my new duplexes and moved to the default mapgen folder.

- I have intentions on renaming (my) other additional locations (removing the capital letters) and moving them to the default mapgen folder, as well as combining other locations. (In a different PR)

**Pull request merged**
