### PR TITLE
PR template: remove `don't delete HTML comments`; add Summary examples; grammar

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
None

#### Purpose of change
I thought the tests on a PR would fail if the HTML comments were deleted.

from Discord @GuardianDll 
> it says this so first time contributors won't remove it without reading

I don't believe this will start happening now.

#### Describe the solution
Remove the sentence that led me to believe that.
Also, fix some grammar reported by Gramarly, so that the template isn't red for me.

#### Describe alternatives you've considered
N/A

#### Testing
I see that I am writing this PR with the new template!

I am assuming the PR tester will not throw any errors as I have removed HTML comments in this PR.

#### Additional context
N/A

### CODE REVIEW

**Comment by Maleclypse** [comment]
"I don't believe this will start happening now." That would be incredible since it already happens now and I have to fix new contributors PR Summaries on the regular.

**Comment by Brambor** [comment]
> "I don't believe this will start happening now." That would be incredible since it already happens now and I have to fix new contributors PR Summaries on the regular.

I mean it will not affect the situation. It will not happen more nor less.

Do you do think the sentence helps? I don't feel **strongly** about removing it. I **would like** the next contributors to not be as confused as I was. Managing the PR is easier when you remove the HTML comments.

If you prefer it, I will leave it in and reduce this to grammar fixes.

**Comment by Brambor** [comment]
I decided to add some summary examples too. They are taken from the existing changelog. A real example might get across better than a generic template.

**Comment by Maleclypse** [comment]
> I decided to add some summary examples too. They are taken from the existing changelog. A real example might get across better than a generic template.

I like those examples. We’ll try it this way and see if it improves. Let me know when ready to merge.

**Pull request merged**
