### PR TITLE
Pot update

### PR DESCRIPTION
**Pull request by BrettDong**

### CODE REVIEW

**Comment by Regularitee** [comment]
Hey Brett, is there any chance you could start putting a little more info in these updates? While I'm sure we all appreciate the work, it'd be nice to know what's actually going on. Every "pot update" contains zero info on what was changed, added, or removed.

**Comment by keyspace** [comment]
Took a look at the [Transifex page](https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/), one must have an account to access [the relevant resource](https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/master-cataclysm-dda/).

Most of us only need to check that `lang/po/cataclysm-dda.pot`, was changed in the "Files" tab.

**Comment by BrettDong** [comment]
@Regularitee How about "translate template update from Jan 6 to Jan 13"? Is this fine to you?

**Comment by Regularitee** [comment]
@BrettDong 
I only bring it up because before I joined the github here, I'd always see "pot update" displayed in the launcher's changelog, would click the link to find no description, and would wonder "what the heck is this? Is he changing the drug system? or the container pot for the cooking system?" 

Yeah, something simple like what you suggested would be more than adequate.

By the way, why is it called "pot update" rather than "translation template update"? It's pot an acronym?

**Comment by BrettDong** [comment]
> It's pot an acronym?

Yes, `.pot, a template file extension used by the GNU gettext program`

**Pull request merged**
