### PR TITLE
backport #72334

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Backport #72334
#### Additional context
Dear Santa, i will never, ever make an omnibus PR, at least one bigger than 50 lines

### CODE REVIEW

**Comment by harakka** [comment]
The codebase had diverged from 0.H for 2.5 months by this point, how confident are you that this big of a backport into 0.H doesn't break more stuff? Content that works unideally is preferable to instability for 0.H imo, especially this late into the cycle.

**Comment by RenechCDDA** [comment]
If it was good to merge back then (and I haven't *seen* any issues arising from it, though of course there could be) then it should be good to merge now. The main thing I would be worried about is any possible merge conflicts which had to be manually resolved.

**Comment by Maleclypse** [comment]
Ugh this backport works but I want the transparent code for Snups work on bags that flashlights can shine through and also for vampire suffering in daylight.  Is there a better way we want transparent or is it just getting pulled because it's dead code right now without the photosynthesis stuff?

**Comment by GuardianDll** [comment]
Snup code about transparent pockets were not approved yet, for there is no way to attach flashlight to a gun, as it would be the most common way to light the entire area. Until it would be made, it is effectively a dead code.

Besides, this is a backport

**Pull request merged**
