### PR TITLE
Move items along when riding the elevator

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Features "Move items along when riding the elevator"

#### Purpose of change
To be able to move items along when riding the elevator.

#### Describe the solution
Ported over https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1531 (which wasn't yet merged at the time of writing).

Check for items in 10-tile radius area (which should be terrain with the newly added `ELEVATOR` flag) around the player. Then move these items up or down.

#### Describe alternatives you've considered
None.

#### Testing
Put an item on the floor of the elevator, activated the elevator, checked item moved too.

#### Additional context
None.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Would it make sense to give a flag to elevator terrain to have this behaviour instead of hardcoding it to this particular terrain?

**Comment by Fris0uman** [comment]
Also as a side note you can add a co-author to the PR manually if you can't cherry pck the commits by adding two empty lines followed by `Co-authored-by: name <username@users.noreply.github.com>` to your commit description
```
[describe commit]


Co-authored-by: name <username@users.noreply.github.com>
```
Documentation there https://docs.github.com/en/enterprise-server@3.5/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by Fris0uman** [comment]
Also as a side note you can add a co-author to the PR manually if you can't cherry pck the commits by adding two empty lines followed by `Co-authored-by: name <username@users.noreply.github.com>` to your commit description
```
[describe commit]


Co-authored-by: name <username@users.noreply.github.com>
```
Documentation there https://docs.github.com/en/enterprise-server@3.5/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by anothersimulacrum** [comment]
Note for whoever merges this: for the attribution reasons outlined above, this should probably be squashed, because as of now the co-author appears only in the last commit.

**Pull request merged**
