### PR TITLE
[Xedra Evolved] Add new time related powers for each default dream class

### PR DESCRIPTION
**Pull request by b3brodie**
#### Summary
Mods "[Xedra Evolved] Add new time related powers for each default dream class"

#### Purpose of change
New Powers are cool
This PR includes infrastructure for a future class/scenario that will be entirely time based

#### Describe the solution
Adds 2 Powers / Items per class

Dreamer:
- Time Bubble: Create a bubble of impenetrable time(tm) that freezes everything within, making it unable to change in any way
- Generate Accelerated Time: Constantly generate an expansive field of accelerated time around you, making everything within much quicker.

Eater:
- Stabilize in Reality: Become immune to portal and time related maladies for the duration of the spell.
- Erosion: Buff the eaters attacks to make them slowly erode the target, doing damage over time.

Inventor:
- Time Piercing Device: Breaks frozen time fields, allowing physical access and freeing anything trapped within
- Injury Reset Device: Reverse the last injury the character suffered. (IE, only works once until taking another injury).

Dreamsmith:
- Time Trap: Reusable Trap that freezes anything that steps within for several hours.
- Shattered Time Pocketwatch: Stops time for 10 seconds once per day.

Infrastructure:

Flags:
 - CANNOT_ATTACK: creatures with this flag cannot attack via movement or special attacks.  Players with this flag cannot attack via movement, auto attack, use ranged weapons, or cast spells.
 - CANNOT_MOVE: players and creatures with this flag cannot move themselves or be moved.  Doesn't cover things like teleporting.
 - CANNOT_TAKE_DAMAGE: players and creatures with this flag cannot take damage
 - CANNOT_CHANGE_TEMPERATURE: players with this flag cannot change their internal temperature
 - FREEZE_EFFECTS: players and creatures with this flag will not have their effect duration tick down.  An effect with this flag is ignored and will still tick down.  This can only be applied with an effect unlike the other flags for players.
 - The above flags can be applied via effects for monsters and players.  Players may also have the flags applied via mutations, bionics, custom bodyparts, or martial arts buffs.

EOC additions:
- character_take_damage: also reports the bodypart that takes damage and the pain that is caused by the damage
- cancel_activity: new effect that will cancel the current activity that an npc is performing

Field Additions:
- linear_half_life bool: rather than using a randomized half life, decay time is set at calendar::turn - age + half_life.
- Impassable fields can be moved through if the character / monster is immune to them.
- Items cannot be picked up within impassable fields
- Terrain cannot be modified or interacted with within impassable fields (such as opening or closing doors)
- Vehicles will crash into impassable fields
- Players / monsters will not teleport from within impassable fields if they get stuck in them

Item Use Additions:
- effect_on_condition action: now takes the need_worn and need_wielding fields to determine if the EOC can be cast.

Spell Additions:
- spawn_ethereal_item: can now be cast by things other than the player (such as trap spell casts) and if targeted at a non-npc, will drop the item on the ground.

#### Describe alternatives you've considered
MOM path
Splitting these powers into individual prs.  Roughly 4-5 of them depend on the same c changes though so they'd have to stay.

#### Testing
Time Frozen Creatures:
- not damageable
- not moveable (with what I tested)
- do not give skill experience
- are not moved or damaged in vehicle collisions
Time Bubbles:
- not damageable
- not traversable unless an immune flag is had
- items cannot be picked up from within
- terrain cannot be changed from within
- items cannot be aim'd out of bubble
- hauling cannot start in the bubble

Time Bubble:
- places bubble that scales with level correctly

Generate Accelerated Time:
- speeds nearby enemies in addition to players

Erosion:
- applies dot correctly

Injury Reset Device:
- resets last injury

Time Piercing Device:
- properly deletes time bubble segments and unfreezes creatures

Time Cage:
- freezes creatures or self correctly and spawns itself when activated (to allow reuse)

Time Freeze Watch:
- freezes corectly, recharges, etc.

#### Additional context
Partial reimagining of #78081

### CODE REVIEW

**Comment by RedMisao** [comment]
About the flags: 
1. How is the `CANNOT_ATTACK` + `CANNOT_MOVE` combination different from using a spell with negative `mod_moves` ?
2. What happens if the player gets the effect with those combinations ? Are their turns skipped (as when getting zapped and trying to move "skips" your actions until the movement value isn't negative anymore), or they can act but nothing happens, except for the messages ?

About the time stop artifact: Keep in mind #48019, so the recharge time should be 48 h for it to recharge every 24 h

**Comment by b3brodie** [comment]
> About the flags:
> 
> 1. How is the `CANNOT_ATTACK` + `CANNOT_MOVE` combination different from using a spell with negative `mod_moves` ?
> 2. What happens if the player gets the effect with those combinations ? Are their turns skipped (as when getting zapped and trying to move "skips" your actions until the movement value isn't negative anymore), or they can act but nothing happens, except for the messages ?
> 
> About the time stop artifact: Keep in mind #48019, so the recharge time should be 48 h for it to recharge every 24 h

1. I haven't fully checked this yet, but my understanding is that mod_moves is 1) affected by the creature speed and move cost stat.  IE, if two creatures are mod_moved by -1000 and one has 100 speed and 100 movecost, while the other has 200 speed and 50 movecost, the quicker creature will be 'frozen' for 4x less duration.  For 2), I'm not sure there's any way to prematurely stop the mod_moves once its happened.  Basically, my goal with the time stop effect is to have it last for a predetermined amount of time (maybe in the far future forever is also an option) but also be endable by certain things. I'd be happy to hear otherwise, but I don't believe either of those are supported by mod_moves.
2. This is still a TODO because right now nothing is skipped automatically for the player.  They won't be able to move or act and they will have to manually wait out the time by holding down the wait button or using the wait time feature.  This is very much not the intended gameplay, so I'm looking into having an activity that will automatically pass the time or something similar.

And thanks for the info on the recharge time bug.  Fixed the pocket watch to account for that

**Comment by Maleclypse** [comment]
Is there a pop up window that tells the PC they have to manually wait so the player doesn’t think the game has frozen?

**Comment by b3brodie** [comment]
> Is there a pop up window that tells the PC they have to manually wait so the player doesn’t think the game has frozen?

I use an eoc to automatically start and end a time frozen activity.  The player shouldn't have to do anything if they get frozen

**Pull request merged**
