### PR TITLE
Fix some formatting in the document

### LINKED ISSUE #73995: document: incorrect title mapgen_id hierarchy in Terrain/Furniture Examination Actions
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/970efaabd3ea0a9b18111238467a4d0f875e4989/doc/EXAMINE.md?plain=1#L95-L105

'### `mapgen_id`' hierarchy does not match, should be 4 '#' as with other optional

### Attach save file

unnecessary

### Steps to reproduce

Visit the URL:
<https://docs.cataclysmdda.org/TESTING_YOUR_CHANGES.html>

### Expected behavior

Should be changed to ####, I think here as not present as a type field, keeping the #### hierarchy will confuse users

### Screenshots

_No response_

### Versions and configuration

website

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cosing**
#### Summary
None

#### Purpose of change
1. [table](https://docs.cataclysmdda.org/EFFECT_ON_CONDITION.html#reusable-eocs) isn't rendering well
2. fix #73995 

#### Describe the solution
1. ~~Not sure why tables with missing vertical lines work on GitHub, but I usually encounter tables with vertical lines, and I'm hoping this will solve the rendering issue~~
The real reason it is not recognized as a table is the lack of extra blank lines above and below the table.
2. just add character '#'

#### Describe alternatives you've considered
None

#### Testing
None

#### Additional context
None

### CODE REVIEW

**Comment by NetSysFire** [comment]
What kind of rendering issue do you see? I compared both your changed file and the original in their rendered version and they look identical.

**Comment by cosing** [comment]
Same in markdown, but I think this may have caused the render to html error
image
Here should be a table @NetSysFire 
in URL <https://docs.cataclysmdda.org/EFFECT_ON_CONDITION.html#reusable-eocs>

**Comment by NetSysFire** [comment]
Ooooh there. Interesting. Very interesting. Looks like whatever docs.cataclysmdda.org runs behaves differently from the github web UI in terms of parsing.

**Comment by cosing** [comment]
Please wait a moment, I'm not sure if it's actually caused by the missing vertical lines.

It's just a guess because I've never seen a format with missing vertical lines that would cause a rendering error.

I just found a similar error just now, but the vertical lines are present in the source markdown file.

https://docs.cataclysmdda.org/EFFECT_ON_CONDITION.html#valid-talkers-35

https://github.com/CleverRaven/Cataclysm-DDA/blob/5b4b49b71e8a5fdc6b655bfec81be6cca39af9f9/doc/EFFECT_ON_CONDITION.md?plain=1#L964-L969

Observing that there are no blank lines in this table and the header below, and that this is a common feature of the two rendering failures (the other tables that were rendered successfully maintained blank lines) , I'm guessing that blank lines may be the cause here.

As a further note, I think this may be caused by the difference between soft and hard line breaks? Just a guess.

**Comment by cosing** [comment]
I built my own web to verify this.
<https://cosing.github.io/Aspirant/Handling-Equipment.html#looting>


```markdown
```

**Comment by NetSysFire** [comment]
In either case, this is likely an upstream jekyll(?) bug. It is fine to keep your changes here in the meantime, thats prettier syntax anyways, as a fix from jekyll might take a while if there will be one.

Coincidentally this revealed some weirdness in the automated workflows to keep docs.cataclysmdda.org updated. This is unrelated to this PR and I will make that a separate issue.

**Review by NetSysFire — APPROVED** [review]

**Pull request merged**
