### PR TITLE
-canceled-

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
**New trait:** `Spiritual` positive, 1 point
**New item:** `holy symbol` with randomized description, one for each faith already represented in-game
**New iuse action:** `meditate` +5 morale, +10 max, requires `Spiritual` to perform
**New item flag:** `INSPIRATIONAL` added to some existing books

Adds a new starting-only one point positive trait, `Spiritual`, which interacts with various ways the character's morale can be manipulated.

Characters possessing the `Spiritual` trait gain a small amount of bonus morale when reading holy books (of any sort) or other books with the `INSPIRATIONAL` flag.

Characters possessing the `Spiritual` trait gain bonus morale when  consuming certain natural entheogens (`mushroom_magic`).

Adds a new item, `holy symbol`, id `holy_symbol`, which uses the new `meditate` iuse function, allowing characters with the `Spiritual` trait to spend 2000 moves (~2 minutes) to gain five points of temporary morale, capped at ten (two uses). This function can be used an infinite number of times, and requires no charges. The extant `relic` item has been given the `meditate` function as well, and as such can now be used for the same purpose. Characters without the `Spiritual` trait cannot use these items to gain their bonus.

Adds some interactions within the cannibalism code, dealing with the philosophical and spiritual implications of eating people. This generally means different messages and slightly different morale bonuses.

**New item,** `holy_symbol` **spawns:**

museum_misc
church
bedroom
dresser
antique
jewelry_front
spider

**_All effects apply to all faiths and philosophies equally. Every possible effort has been taken to ensure that all faiths have been treated respectfully and that no religion or philosophy is advocated or advanced by the messages and effects within this PR.**_

---

_I've kept it all quite vague/equally applied so that the player is free to decide what their character's spirituality actually means, and no path is objectively 'better' than another._

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I'm not sure why it won't auto-build; it compiles and works fine.

**Comment by narc0tiq** [comment]
"Unmergeable pull request" seems pretty clear to me.

**Comment by Rivet-the-Zombie** [comment]
It would be nice if it would elaborate a bit beyond 'unmergeable' because I'd like to know if the problem is something I did, or something to do with Git.

**Comment by Rivet-the-Zombie** [comment]
Derp. And here I thought I'd done all that in such a way as to avoid conflicts.

**Pull request closed without merging**
