### PR TITLE
Drop remaining ues of tools and bigtools

### PR DESCRIPTION
**Pull request by mugling**
Use the more specific `tools_*` groups as alternatives to `tools` and `bigtools`

### CODE REVIEW

**Comment by Coolthulhu** [comment]
There are mapgen errors when running `./cataclysm --check-mods` with this PR

**Comment by Coolthulhu** [comment]
Should I wait for fixes?

**Comment by mugling** [comment]
@Coolthulhu fixed in 111d82e

**Comment by Mshock777** [comment]
While you are messing around with tools, maybe add `tools_electronics` to `tools_home` at about 20% chance.

**Comment by mugling** [comment]
> While you are messing around with tools, maybe add tools_electronics to tools_home at about 20% chance.

I'm trying to move away from the everything-spawns-everywhere-and-all-the-time setup we have at present. When we add oscilloscopes and multimeters to `tools_electronics` the category those spawns would then be inappropriate.

There should be an incentive to venture deep in to a city to raid a specific shop rather than just rely on the rng producing it for you in a home

**Comment by Mshock777** [comment]
Who doesn't have multimeter/solder iron/magnifying glass in there home?
But maybe it's just me, never mind.

**Comment by mugling** [comment]
> Who doesn't have multimeter/solder iron/magnifying glass in there home?

Whilst there's likely some truth in that the danger is boredom - if different sites don't have different monsters and loot it becomes dull very quickly.

**Comment by Mshock777** [comment]
True, that's why I use spawn scale below 0.5 (I also think amount of loot at 0.5 should be considered standart)

**Comment by mugling** [comment]
> (I also think amount of loot at 0.5 should be considered standart

Yes, there is far too much loot

**Pull request merged**
