### PR TITLE
[Xedra Evolved/Innawood] Remove modern items from XE spawns Innawood, allow starting with XE-specific scenarios

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved/Innawood] Remove modern items from XE spawns Innawood, allow starting with XE-specific scenarios"

#### Purpose of change

If you've checked out my Github, you've seen I have a mod that's dedicated to doing just this. But now that we have mod compatibility, I can just PR those changes.

#### Describe the solution

Edit renfield and changeling deathdrops to remove all modern items. Allow changelings or renfields to spawn very rarely in the forest, and add a renfield-themed cave and a goblin spider themed cave. Allowing choosing Lilin, werewolves, vampires, and Paraclesians and add a Naked and Afraid start to all of those.

...well, the werewolf one is called "Naked and Unafraid" for obvious reasons.

This does increase the availability of some gear, but if you want an absolutely pure Innawood experience, you probably shouldn't combine it with Xedra Evolved. 

#### Testing

Scenarios are selectable, renfields and changelings do not drop modern gear.

### CODE REVIEW

**Comment by Cddasurvivor** [comment]
Just a heads up that Child-like Fetches still drop modern items in the mod.

**Comment by Maleclypse** [comment]
If flint knives exist already childlike fetches can be armed with those. If not let me know and I'll try to make them.

**Comment by Cddasurvivor** [comment]
> If flint knives exist already childlike fetches can be armed with those. If not let me know and I'll try to make them.

The thing is they have backpacks, leather belts, synthetic clothing, video games, ect.

**Comment by Maleclypse** [comment]
> > If flint knives exist already childlike fetches can be armed with those. If not let me know and I'll try to make them.
> 
> 
> 
> The thing is they have backpacks, leather belts, synthetic clothing, video games, ect.  Not sure if he fixed that but it was still an issue in the mod.

No clue. I'm volunteering to help if they need a replacement for the scissors as weapons I'd set them up with in base XE.

**Comment by Standing-Storm** [comment]
> Just a heads up that Child-like Fetches still drop modern items in the mod.

I'm not sure I ever knew those existed--I'll fix that too. 

> If flint knives exist already childlike fetches can be armed with those. If not let me know and I'll try to make them.

They do not IIRC (I've seen it multiple times as one of those "why isn't this in Innawood?" things)

**Pull request merged**
