### PR TITLE
Mshock Modded Tileset Series 17

### PR DESCRIPTION
**Pull request by chaosvolt**
Fixes:
- Gave the 32x32 version of winter foliage the correct background.

Sprite Additions:
- Gave the brick kiln its own sprite.
- Stegosaurus
- Ankylosaurus
- Allosaurus
- Velociraptor
- Deinonychus
- Utahraptor
- Dilophosaurus
- Parasaurolophus
- Dimorphodon (ohgodwhat, that derpy sprite ;_;)
- Blank scroll
- Magic scrolls
- The Six Pillars
- Mask of insight
- Plain golden ring
- Diamond ring
- Ring of the fallen angel
- Cursed sword
- Forked spear
- Pitchfork
- Fencing foil, epee, and saber

Sprite Assignments:
- Eoraptor
- Aluminum ignot
- Bag of mortar
- Clay quern

### CODE REVIEW

**Comment by Mshock777** [comment]
I was too lazy to fix it myself, so: winter version of harvested underbrush should have background 543.

**Comment by chaosvolt** [comment]
Ah, I see it. I could've sworn that harvested underbrush originally lacked a sprite to begin with. o.o

**Comment by Mshock777** [comment]
Hahaha, I was just looking at tile_config for 24 version and thinking: am I going mad, I swear it was 513 before :-)

**Comment by chaosvolt** [comment]
Huehuehue. Yeah, that was a mistake on my end last time I was updating foliage, I assume. XP

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
