### PR TITLE
Ammo can be multiple types

### LINKED ISSUE #9709: Bug: gasoline-using tools can be refueled with napalm.
All gasoline-using tools can be loaded with napalm and then used.

When unloaded, they transform napalm that was loaded into gasoline.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5548338-bug-gasoline-using-tools-can-be-refueled-with-napalm?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mugling**
- Allows ammo to be multiple types
- Simple implementation due to the existing encapsulation via `ammo_*` accessors
- Demonstration items are provided in a2e3f45 and 34a391d
- Fixes #9709

### CODE REVIEW

**Comment by mugling** [comment]
How handle `ammo_required()` when different ammo types have differing charge ratios?

**Comment by Zireael07** [comment]
Specify charge ratio per type and add a type parameter to ammo_required? Just a thought...

**Comment by mugling** [comment]
> Specify charge ratio per type and add a type parameter to ammo_required? Just a thought...

Won't work for empty items though

**Comment by mugling** [comment]
Change of plan - I'm going to differential scaling of ammo in a separate PR to avoid bloating this one.

Ready

**Comment by DangerNoodle** [comment]
I can see this having potential.

**Comment by mugling** [comment]
> I can see this having potential.

Yes, we are starting to reach the critical mass where the code supports enough features to implement some novel items and game mechanics (as opposed to more item bloat)

**Comment by Coolthulhu** [comment]
Very minor regression, possibly caused here: flamethrower using napalm says "bang" when firing.

**Pull request merged**
