### PR TITLE
Rollback added pockets and fix tailors kit.

### LINKED ISSUE #11345: Tailor's kit issues.
1. You can modify an item with a tailor's kit even if this item can't be worn. Well, adding kevlar plates on a canvas bag is possible, but doesn't make any sense since you're not going to wear it anyway, so why would you want to do that?
2. If you choose to repair an item with a tailor's kit, you are asked about which item to repair for the second time.
3. Tailor's kit description says that it contains a heating element and you need a lighter to craft it, yet it doesn't require the lighter to contain any fuel. I would suggest to use appopriate tools from inventory if you are working with plastic instead of making it included in the kit itself.

Also, I would suggest to prevent modifying an item if it won't benefit from this (if storage/warmth/protection won't increase at all after modification) and to add some way to remove modifications.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8771911-tailor-s-kit-issues?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kevingranade**
We were getting a ton of complaints about pocket application not making sense, and looking at the code it doesn't. It can be applied to all kinds of things where it makes no sense, and has no effect in places it should, and the formula for the amount of storage added is nonsensical.  We can take another look at this post 0.C, but for now I'd like to prioritize stability over having the feature.

This rolls back adding pockets and fixes #11345 by preventing modification of non-armor items, allowing repairs of modified items and passing the command through to a helper function instead of calling iuse::sew() directly.
I didn't address the heating element issue.

### CODE REVIEW

**Comment by KA101** [comment]
OK, good to know.

**Comment by Rivet-the-Zombie** [comment]
And this won't break saved games?

**Comment by KA101** [comment]
Looks like it stops reading any existing pocket flags, so they *should* sit there doing nothing.

**Comment by kevingranade** [comment]
KA101 is correct, items will still be tagged with "pocketed", but it won't have any effect.
(hooray item tags doing what they were meant to do)

**Pull request merged**
