### PR TITLE
Marking Important gear in inventory

### PR DESCRIPTION
**Pull request by jimidobson**
Adds ability to mark inventory items as "Important". Adds a flag to items that causes special highlighting in inventory screens in the form of a white background for that item name.

Special and conditional text colours are preserved. A piece of rotten food will still have brown text, but on a white background. A book you can learn recipes from but not gain a level from will have yellow text on white background or pink if you can't learn from it just yet.

You can toggle this flag on items by going to the item's details and hitting 'M'.

Note: this includes #18165 by adding in various fixes for VS2015 code standard issues.

### CODE REVIEW

**Comment by woutershep** [comment]
Your coding style seems wrong. At the very least your tabs and spaces around parenthesis. You should doublecheck the style requirements.

**Comment by jimidobson** [comment]
I will run it through astyle and commit

**Comment by mugling** [comment]
Welcome @jimidobson. You should only astyle the relevant lines (those which you have changed)

**Comment by jimidobson** [comment]
thanks @mugling ! I'm not very familiar with astyle - I used it on the files I changed and it seems to have modified a ton of lines of code. Could you tell me how to target the specific code I've changed with astyle?

**Comment by mugling** [comment]
To be honest I'd probably be easier to make a small number of changes by hand. It might also be best to split the MSVC changes as a separate PR as whilst those are welcome they usually have a longer review cycle than the other interface enhancements you are proposing.

**Comment by jimidobson** [comment]
Fair enough. I'll go through the MSVC fixes and clean them up so its just the relevant lines rather than a bulk astyle sweep. I'll then make a new pull request for those changes.

I'll then do the same with these changes as the MSVC fixes from before have been folded into this one.

**Comment by Mecares** [comment]
Can we also make it impossible to burn important gear in my internal furnace, i would really like that.

**Comment by jimidobson** [comment]
@Mecares I'd be happy to, I'll make that as a new feature if/when this one gets merged (but I need to complete the MSVC stuff first and I need to tidy this feature up too).

**Comment by mugling** [comment]
Stalled. Could be rebased and reopened

**Pull request closed without merging**
