### PR TITLE
Makes AIM able to transfer between two containers

### PR DESCRIPTION
**Pull request by GoodDays13**
#### Summary
Features "Made it so you can open containers in AIM and move stuff between them"

#### Purpose of change
I felt like some things would be easier if you could transfer between two containers, and it felt like the AIM container menu was acting a bit weird. Containers would only show one item and you couldn't open them in your inventory

#### Describe the solution
made it so there are two different areas that hold info on the left and right containers. I duplicated variables that only held one side's info. 

#### Testing
opened AIM and opened jeans and messenger bag of default character and also put one on the ground and other combinations like inventory. also tried spawning another messenger bag and transferring between them in case the same item messed things up. Also opened an item in an item in an item

#### Additional context
image

### CODE REVIEW

**Comment by GoodDays13** [comment]
> you can't seem to open containers in your inventory or in other containers yet

I tested merging a pr I found, #55997, and it seemed to work a little with it, being able to open it in the inventory, but there are bugs with it becoming "invalid container" like I had when I was writing this one. also, still can't open in containers. I may look into this later, but maybe it's small

**Comment by GoodDays13** [comment]
notes to self
!
- [ ] "move all" functionality 
?
- [ ] open containers in inventory 
- [ ] open containers in containers

**Comment by Night-Pryanik** [comment]
@GuardianDll could you please resolve conflicts?

**Comment by GuardianDll** [comment]
Wrong ping? 🤨

**Comment by Night-Pryanik** [comment]
Sorry.
@GoodDays13 could you please resolve conflicts?

**Comment by Fris0uman** [comment]
Could you fix the Clang errors?

**Comment by GoodDays13** [comment]
It seems that half of what this does is already in the game because of how long it took me to come back to this, so I'm gonna close it.

**Pull request closed without merging**
