### PR TITLE
[WIP] (help's needed!) Allow sourdough to be started in clay canisters

### PR DESCRIPTION
**Pull request by DanielVartanov**
#### Summary
Content "Allow sourdough to be contained in a clay canister"

#### Purpose of change

Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/51964

#### Describe the solution

This PR intends to allow a player to use clay canisters to contain sourdough and sourdough starters.

#### Describe alternatives you've considered

An alternative would be to have a much more complex change of allowing _any_ container to contain sourdough. I think current solution covers two major cases: when looting is available (player uses glass jars) and when looting is [temporarily] not available (player uses clay canisters).

#### Testing

I tested it manually, here is my test plan:

<details>
<summary>Test plan</summary>

  - Test setup:
    * Spawn lots of plastic bottles of clean water
    * Spawn lots of flour

  - Test making clay and glass young
    * Spawn empty clay and glass
    * Make clay young and glass young
    * Check you got clay starter, young starter and no empty vessels

  - Test how young gets into starter
    * Spawn clay young and glass young
    * Wait for a week
    * Check you got clay starter and young starter

  - Test how glass starter splits into two
    * Spawn 2 glass starters
    * Spawn empty glass and empty clay

    * Make split with empty glass
    * Check you got 1 clay starter, 1 empty clay and 2 glass splits

    * Make split with empty clay
    * Check you got 3 glass splits and 1 clay split

  - Test how clay starter splits into two
    * Spawn 2 clay starters
    * Spawn empty glass and clay

    * Make split with empty glass
    * Check you got empty clay, 1 glass split, 1 clay split and 1 clay starter

    * Make split with empty clay
    * Check you got 1 glass split and 3 clay splits

  - Test how starter gets into bread
    * Spawn clay starter and glass starter

    * Bake bread from clay starter
    * Check you got bread, clay split and glass starter

    * Bake bread from glass starter
    * Check you got bread, clay split and glass split

  - Test how split gets into starter
    * Spawn clay split and glass split
    * Wait for a day
    * Check you got clay starter and glass starter

  - Test young, split and starter gets disassembled correctly
    * Spawn 2x(young, split and starter)

    * Disassemble clay young, split, and starter
    * Check you got 3 clay canisters and nothing else

    * Disassemble glass young, split and starter
    * Check you got 3 clays, 3 jars and nothing else
</details>

Please note, since this PR is WIP, some test cases do not pass.

##### Help is needed!

In order to allow `sourdough_bread` to be crafted with two different sets of components, producing two different by-products, I create duplicate recipes, like that:

```
  {
    "type": "recipe",
    "result": "sourdough_bread",
    "byproducts": [ [ "sourdough_split_in_glass_jar", 1 ] ],
     ...
    "components": [
      [ [ "flour", 10 ] ],
      [ [ "sourdough_starter_in_glass_jar", 1 ] ],
      [ [ "water", 2 ], [ "water_clean", 2 ] ],
      [ [ "water_clean", 1 ] ]
    ]
  },
  {
    "type": "recipe",
    "result": "sourdough_bread",
    "byproducts": [ [ "sourdough_split_in_clay_canister", 1 ] ],
    ...
    "components": [
      [ [ "flour", 10 ] ],
      [ [ "sourdough_starter_in_clay_canister", 1 ] ],
      [ [ "water", 2 ], [ "water_clean", 2 ] ],
      [ [ "water_clean", 1 ] ]
    ]
  },
```

This trick turned out not to be working (only the first one gets picked up by the game). But in https://github.com/CleverRaven/Cataclysm-DDA/issues/51964 and https://github.com/CleverRaven/Cataclysm-DDA/issues/51174 people suggested doing a JSON-only change would be the best course of action, I wonder how do I make it work?  Do I have to duplicate an item (`sourdough_bread_made_with_sourdough_from_glass_jar` and `sourdough_bread_made_with_sourdough_from_clay_canister`) even though all its properties would be the same?

Another question is on items migration, I might deduct how they work, but is there any doc on that? I couldn't find any.

Thanks in advance!

### CODE REVIEW

**Comment by kwl01skz** [comment]
Let me briefly describe how it is implemented in the game.

Item B1: glass bottle 1
Item B2: glass bottle 2
Item: yeast
Item Y1: yeast waiting for fermentation in glass bottle 1
Item Z1: Fermented yeast in glass bottle 1
Recipe: glass bottle 1 / glass bottle 2 + raw material = yeast in glass bottle waiting for fermentation

Over time, Y1 becomes Z1.
Finally, open Z1 to obtain glass bottle 1 and yeast.

Maybe you noticed,
We used different glass bottles, but in the end we could only harvest glass bottles 1.

If you want to implement your idea by modifying JSON, you should write:

Item B3: another container
Item Y3: yeast waiting to ferment in another container
item Z3：…………

**Comment by wapcaplet** [comment]
Would it make things easier if there were simply no container?

Sourdough starter can be a solid lump of dough. You can leave it sitting on the counter or in the fridge, preferably enclosed or covered, but there is no reason it has to live in a jar, clay pot, tupperware, or any other water-tight vessel unless you are maintaining a more hydrated, liquid starter.

What if the recipe were simply for the dough or starter itself, and omitted all reference to containers? Then you could keep it in whatever container you want.

**Comment by DanielVartanov** [comment]
@wapcaplet, strange, nearly all recipes on the internet imply some form of lid ([example](https://upload.wikimedia.org/wikipedia/commons/9/99/Sourdough-process.svg)), does sourdough by chance need a lack of oxygen at some stage?

**Comment by wapcaplet** [comment]
> @wapcaplet, strange, nearly all recipes on the internet imply some form of lid ([example](https://upload.wikimedia.org/wikipedia/commons/9/99/Sourdough-process.svg)), does sourdough by chance need a lack of oxygen at some stage?

It makes practical sense to put a lid on, to help retain moisture and keep dust and critters out, but oxygen or lack thereof has no significant effect I'm aware of; in fact the lid should be somewhat loose to allow CO2 to escape.

The graphic you linked above looks kind of like the recipe workflow I had in mind, minus the bowl, since we don't yet simulate mixing bowls or spoons in recipes. I was thinking the in-game recipe could simply be the "mix flour and water, form into a ball" part, and the recipe would produce the dough-ball which you may then place in any container you like.

**Comment by DanielVartanov** [comment]
@wapcaplet thank you for the idea and for the explanation, I will try if I can do it myself when I get back to this PR!

**Comment by DanielVartanov** [comment]
> Feel free to request that it be re-opened if you are going to actively work on it

Okay, will do, mr. bot.

**Pull request closed without merging**
