### PR TITLE
Prevent loaded batteries from being heavier

### PR DESCRIPTION
**Pull request by Coolthulhu**
`"NO_DROP"` flag means that the item is fake and so should not have any weight.

EDIT: Includes #21380 (has to, otherwise the vehicle tests would rely on the bug it fixes)

### CODE REVIEW

**Comment by Leland** [comment]
This fix #12764?

**Comment by Coolthulhu** [comment]
Something may be very wrong with vehicle momentum:
It seems that this test is failing because electric vehicles became less, not more, efficient as their weight decreases.

The problems are with the "full stop" tests, meaning that it is NOT caused by less efficient braking causing the vehicle to just coast for longer. In full stop tests, the vehicle is started at full velocity, then allowed to coast.

I think I located it - in map.cpp::422 there is:
```
const float k_slowdown = (0.1 + veh.k_dynamics()) / ((0.1) + veh.k_mass());
```

Why should the vehicle slow down MORE as it gets more aerodynamic?

**Comment by codemime** [comment]
This requires updating of a unit test.

**Comment by Coolthulhu** [comment]
I'm not sure if it's better to update the unit test or first fix the thing that causes this problem in unit tests. #21380 will change the results, but will also fix the problem.

**Pull request merged**
