### PR TITLE
[WIP] Allow AR-15 and other rifles to easily swap between .223 and .300blk

### PR DESCRIPTION
**Pull request by DPavonis**
#### Summary
Features "Allow AR-15 and other rifles to easily swap between .223 and .300blk"

#### Purpose of change

Seeing as the Hub01 HWP can easily swap between various different ammunition types, I had a big think moment: what if, just like in the real world, we could easily swap AR-15 family rifles, and maybe the other .300blk rifles between .223, .300blk and heck, why not .50 Beowulf while we're at it?

#### Describe the solution

Create a .223 AR-15 kit, set all AR-15 derivatives to NULL ammotype, remove .300blk kit's `IRREMOVABLE` flag

#### Describe alternatives you've considered

~~Not do this~~

#### Testing

Make sure the rifles can use their respective caliber conversion kits

#### Additional context

TODO: figure out how to properly migrate existing rifles to this new NULL ammotype/relevant gunmod regime
TODO: .50 Beowulf for added hilarity?

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
No shortie kit for AR pistol & OA-93?

**Comment by DPavonis** [comment]
> No shortie kit for AR pistol & OA-93?

It's a balance between realism and clutter imo. I'm already adding quite a few new kits as it is, and adding even more kits just to account for barrel length seems a bit much to me.

**Comment by DPavonis** [comment]
Not exactly happy with the idea of creating these copy-from's all over the place to do this. Gonna look for a saner way to do it.

**Comment by anoobindisguise** [comment]
How strong would .500 Beowulf be? 47 base damage? So slightly better than .300 AAC.

**Comment by DPavonis** [comment]
> How strong would .500 Beowulf be? 47 base damage? So slightly better than .300 AAC?

Something along those lines probably, but I haven't sat down and actually mathed it out yet. I want to hammer out the other components of the PR first.

**Comment by nopenoperson** [comment]
i tried to make a 38 revolver that could cylinder swap to load 9mm with moon clips but having the conversion change the pocket from "MAGAZINE" to "MAGAZINE_WELL" just gave me a bunch of game crashes. this is much saner

**Comment by DPavonis** [comment]
> i tried to make a 38 revolver that could cylinder swap to load 9mm with moon clips but having the conversion change the pocket from "MAGAZINE" to "MAGAZINE_WELL" just gave me a bunch of game crashes. this is much saner

Glad this inspired you, but I can't really take credit tbh, I just pinched this from the hybrid weapons platform.

Side note: still haven't really solved the issue of properly migrating the weapons. :\

**Pull request closed without merging**
