### PR TITLE
islot_tool::load

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Infrastructure "Migrate Item_factory::load_slot( islot_tool ) to islot_tool::load()"```

#### Purpose of change
part of #36851

#### Describe the solution
changes load_slot from item_factory to a load() function using the generic_factory way of things in islot_tool.

#### Testing
loaded the game to make sure i don't get any funny debug messages.

### CODE REVIEW

**Comment by kevingranade** [comment]
This seems to be causing an item processing test I added recently to fail, and I don't know why.
The symptom is that I'm activating a firecracker and stashing it in various locations, then triggering an active item processing tick.  The "fuze" on the firecracker (item::charges) is not ticking down.

**Comment by KorGgenT** [comment]
that's this PR causing it? very strange, that doesn't sound like the kind of thing this would be anywhere near. The charges count down just fine without it thought? i will see what i can do to investigate.

**Comment by KorGgenT** [comment]
Yup, confirmed that it doesn't happen in master but does happen in this PR. Investigating why that is.

**Comment by KorGgenT** [comment]
I still have no idea what's going on. I didn't do anything special with the load functions, they load with the same default values as previous.

**Comment by KorGgenT** [comment]
i'm just going to close this for now. i've got plenty of other things on my plate and these item factory refactorings were just meant to be an easy little brainless thing. maybe we can figure this out at some other time.

**Pull request closed without merging**
