### PR TITLE
Explicitly add triffid fungicide sacks and relevant recipes.

### PR DESCRIPTION
**Pull request by Tamiore**
#### Summary
Content "Explicitly add triffid fungicide sacks and relevant recipes"

#### Purpose of change
~~`Fungal fighter sting` was at some point removed from fungal fighter harvest table. It was moved to on-death drops, but I don't see why a (presumably internal) stinger should detach itself on death. Looks more like a bizarre workaround, so I'm giving it back as harvest result.~~
Currently, triffid fungal fighter does not really have much in the "fungal fighting" department. He drops a sting on death (sometimes) that can be used in a secret recipe for fungicide. But nothing anti-fungal comes from butchering it, plus the recipe for turning the stinger into fungicide does not make much sense (why would a camping handbook have a secret recipe for turning alien plant stinger into commercial fungicide..?).
Abandon stinger, just add triffid fungicide sacks explicitly.

#### Describe the solution
~~Replace paralytic venom with `fungal fighter sting` in harvest table.~~
Explicitly add triffid fungicide sacks and relevant recipes

#### Describe alternatives you've considered
~~Adding it as dissection item, not "normal" butchering.~~
~~Keeping the paralytic venom sacs available, just adding the stinger as an extra. (Personally, I don't like this much, because thematically that should be a fungicidal/paralytic venom, not just normal paralytic venom.)~~

#### Testing
.json changes, works fine locally.

#### Additional context
I really don't think natural weapons (that are parts of the creatures body) should be on-death drops. 
For two reasons:
1) It just does make much sense thematically. It's not like a triffid is holding a "triffid gun" of some kind. The stinger is part of the body.
2) Making a natural weapon an on-death drop has all kinds of strange interactions with "item spawn chance" world settings.

### CODE REVIEW

**Comment by Venera3** [comment]
Removing the paralytic sacs is quite unintuitive, to be honest. Their description, attack effects and ranged attack all paralyze the player, so either remove those as well or consider the (not actually implemented, by the way) fungicidal venom an extra adaptation "on top" of the usual paralytic of triffids.

**Comment by Tamiore** [comment]
>Removing the paralytic sacs is quite unintuitive, to be honest. Their description, attack effects and ranged attack all paralyze the player, so either remove those as well or consider the (not actually implemented, by the way) fungicidal venom an extra adaptation "on top" of the usual paralytic of triffids.

I agree it's not the most intuitive decision. (Giving the paralytic venom sacks back is a one line edit, too, so extremely easy.)

The reason I'm not 100% on board with this is:
if the fungal fighter explicitly drops the paralytic venom sacks (when harvested), where it the fungicide coming from? Is it part of *that* venom? Shouldn't be just "normal" paralytic venom in that case. 
Or fungal fighter has two kinds of venom sacks — one for paralytic venom, one for fungicide? 
Not hard to implement per se, but does bring up the question of what exactly is inside the fungicide sacks. Ready to used "triffid fungicide"?

**Comment by Tamiore** [comment]
Ok, whatever.

Full-blown commit with new item: triffid fungicide sacks.

Can be used for anti-fungal weapons "as is", can be turned into standard fungicide with applied science (7), survival(6) and health care (6).

**Comment by Venera3** [comment]
Cheers, that's the solution I would have gone with as well.  Sourcing two kinds of useful chems from them makes them even more of a punching bag, but the whole bunch could use a hefty buff anyway.

**Comment by Tamiore** [comment]
On the second though, I don't really see why high health care would be relevant to turning triffid fungicide into more conventional fungicide. So health care lowered to (2).

**Comment by Fosheze** [comment]
> On the second thought, I don't really see why high health care would be relevant to turning triffid fungicide into more conventional fungicide. So health care lowered to (2).

The only reason I could see healthcare being required is to know how to remove the venom from the organ. Considering that this is an alien organ though, I don't imagine healthcare knowledge would be useful for anything more than determining that "this is definitely an organ and it looks like it has fluid in it." To that end survival might be a better fit because it is what is used for butchering. Being able to gut an animal without piercing an organ and ruining the meat would be a much more useful skill in this situation than knowing human biology.

**Comment by Tamiore** [comment]
>The only reason I could see healthcare being required is to know how to remove the venom from the organ. Considering that this is an alien organ though, I don't imagine healthcare knowledge would be useful for anything more than determining that "this is definitely an organ and it looks like it has fluid in it." To that end survival might be a better fit because it is what is used for butchering. Being able to gut an animal without piercing an organ and ruining the meat would be a much more useful skill in this situation than knowing human biology.

Survival (6) is already there. As is applied science (7)

Health care (2) represents more of a very general "make sure the end product is not completely incompatible with human metabolism".

**Comment by actual-nh** [comment]
> Health care (2) represents more of a very general "make sure the end product is not completely incompatible with human metabolism".

Or "how to handle things while wearing gloves to protect yourself".

**Pull request merged**
