### PR TITLE
[RDY] Rollback recent spawn function changes in hardcoded mapgen

### LINKED ISSUE #22895: Huge spike in monster spawns in recent builds.
Game version: 7109

Operating system: Windows

Tiles or curses: Tiles

Mods active:

### Expected behavior 
Monsters spawn at a reasonable rate.

### Actual behavior 
Drug deals gone wrong and presumably other set pieces spawn with multiple migos and enough amoebic molds and blobs to cover the screen causing lag from the blobs/amoebic molds. Other players have reported roadblocks with dozens of turrets. 

### Steps to reproduce the behavior 
Encounter drug deals gone wrong, dead scientists, road blocks, or likely other set pieces that spawn monsters in a recent build.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Fixes #22895.

# What was changed

- rollback changes from #22847;
- rollback most changes from #22852 (`start_location.h` left intact);
- rollback changes from #22854.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I believe it would be better to properly fix #3951 while moving hard-coded mapgen to json.

**Comment by ZhilkinSerg** [comment]
Btw, is it properly to name defs like this:

````C++
#def SUBMAP_WIDTH (SEEX * 2)
#def SUBMAP_MAX_X (SUBMAP_WIDTH - 1)

#def SUBMAP_HEIGHT (SEEY * 2)
#def SUBMAP_MAX_Y (SUBMAP_HEIGHT - 1)
````

**Comment by BevapDin** [comment]
> How do we call square with SEEX * 2 and SEEY * 2 dimensions? Is it submap?

A submap contains lots of `foo_type foo[SEEX][SEEY];`, so a submap is `SEEX` times `SEEY` map squares large.

`SEEX * 2` is the size of the overmap terrain, expressed as number of map squares. It's also the number of map squares of the map used for mapgen (`tinymap`), maybe that can give it the name (which should probably be local to the mapgen files).

**Comment by ZhilkinSerg** [comment]
Thanks, @BevapDin! So it is like this:

`
SM = SUBMAP = SEEX * SEEY
OMT = OVERMAP_TERRAIN = SM * 2 * 2 = SEEX * 2 * SEEY * 2
`

And I can probably go with this names:

````C++
#def OMT_WIDTH (SEEX * 2)
#def OMT_MAX_X (OMT_WIDTH - 1)

#def OMT_WHEIGHT (SEEY * 2)
#def OMT_MAX_Y (OMT_HEIGHT - 1)
````

**Comment by boydkr** [comment]
Can we get a merge on this?  The bug is pretty game-breaking

**Comment by anubiann00b** [comment]
There's a linked build here, for any players seeing this and wanting a quick fix: https://github.com/CleverRaven/Cataclysm-DDA/issues/22895#issuecomment-364729975

**Pull request merged**
