### PR TITLE
Survivor Machete: Removes rapid attack, damage fix

### PR DESCRIPTION
**Pull request by chaosvolt**
Since Jkoudys' PR https://github.com/CleverRaven/Cataclysm-DDA/pull/13795 has stalled a bit, decided to add the more relevant rebalancing myself.
1. Removes rapid attack from the survivor machete. This is the big
   obvious cause of its effective damage per turn being so obscenely high.
2. Alters damage values. Its total damage is now the same as the
   standard machete, gaining 1 cut damage in exchange for 1 bash damage.
   Damage can be messed with further, but removing rapid strike is the more
   important part. This is just to deal with the survivor machete's current
   damage being set with rapid strike in mind.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Could also lose the brutal attack. It doesn't really fit the theme and it's not actually a good thing on the survivor machete. Brutal attack is stun+knockback.

Though with the modified stats, it's not really worth crafting. Machete has dpt 35.1 vs. survivor machete's 35.5
Drop the weight too, maybe?

I'm not sure how could a machete be "rebalanced for combat", so it's hard to tell what should it be.
It's one of the problems with all "survivor" items.

**Comment by chaosvolt** [comment]
Ah, right. Let's see, how much weight reduction would I need to increase the DPT to about a point or 2 more than the normal version?

Alternatively, does replacing "chop" with "slice" for flags do anything? From a flavor perspective, I'm assuming whoever would craft this is basically trying to make an ersatz katana or other light cutting weapon. So while brutal technique doesn't fit, slice flag would be viable

**Comment by chaosvolt** [comment]
Though this'll have to wait, as will be out and about for a bit. >.<

**Comment by vache** [comment]
> I'm not sure how could a machete be "rebalanced for combat", so it's hard to tell what should it be.
It's one of the problems with all "survivor" items.

That is my whole argument.  Survivor machete makes no sense, a machete is already about as streamlined as it's going to get.  I don't really see how you can change it with a soldering iron, hacksaw, hammer, and duct tape that is going to make it into a better weapon than it already is.

**Comment by Coolthulhu** [comment]
We have a bit of a problem with letting go around here.
Additions are easy, removals require consensus.

I'd be fine with the recipe removed. Then, when going stable the item could be removed too.

If not, here we can discuss how to salvage this weird item into one that makes sense.

**Comment by Zireael07** [comment]
https://en.wikipedia.org/wiki/Machete

Saw-machete combo, anyone? More for tool use than a weapon, though. IMHO the machete can't be made any better as a weapon...

**Comment by chaosvolt** [comment]
Right. I'll leave the decision to dummy it out to others. Until then, I can rebalance the item as others wish.

**Comment by Rivet-the-Zombie** [comment]
> Survivor machete makes no sense, a machete is already about as streamlined as it's going to get. I don't really see how you can change it with a soldering iron, hacksaw, hammer, and duct tape that is going to make it into a better weapon than it already is.

My line of thinking when I added it was that you were going from a standard garden tool like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Machette_kos.pg.jpg/800px-Machette_kos.pg.jpg) with a rather crappy handle and a flimsy blade with a rather dull, flat ground edge to something more like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Gerber_Machete.jpg/1024px-Gerber_Machete.jpg) which has a much better/larger handle and a reinforced, sharpened blade.

**Comment by vache** [comment]
At the very least, I don't think the recipe reflects that.  The main changes it sounds like are adding something making the handle easier to grip, which can be the duct tape, and sharpening the blade, which we should probably have a sharpening stone or a whetstone for.  Reinforcing the blade sounds like it's probably unnecessary, or at least would require some metal as a part of the recipe, which should add weight.  From that description, it sounds like converting a regular machete to a survivor machete would add weight, and increase cutting damage, and possibly increase durability and reduce chance to get stuck.  We don't really model the second two that well, outside of some basic flags.  Also, I think if we add a whetstone and make that a component in the recipe then it should probably be a part of most weapon recipes.  

Honestly, I don't think your standard machete, even like the one you linked, is going to be crappy.  It is made for clearing brush which is a pretty heavy duty task.  Why wouldn't the player be finding the second one when they find a machete?  It makes more sense to me for the player to find the second one, than to find the first one and turn it into the second one.

**Comment by chaosvolt** [comment]
Machetes do vary wildly in quality IRL though. I have two excellent. One is a 6-dollar piece of shit that can't hold an edge to any significant degree. It actually kinda clubs weeds to death more than it does any cutting.

The other, despite being half that price (I think it might've been a dollar less originally, but was on clearance), has an excellent edge and a more comfortable handle, but has pointless serrations on the back that leave me storing it unsheathed because it tore the original sheath to pieces. >.>

And back to being on topic, it good be interesting as an oversized knife if lightened to change the point of balance. Sharpness, probably not. In my case my current damage changes were only really to make the total damage on par with the standard machete, shifting bash/cut around was a spur-of-the-moment idea.

**Comment by Rivet-the-Zombie** [comment]
I like this set of changes.

**Comment by chaosvolt** [comment]
Ah. I will admit I'm still leery of having bumped cutting damage up (now at 2 more than normal machete, but only 1 more total damage), for the reasons @vache pointed out. But I had trouble getting the weapon's DPT at the desired 1 point more than the standard machete, without lowering weight even more than it's at now.

**Comment by Rivet-the-Zombie** [comment]
I'd be happy with reducing the damage by that single point and otherwise using this as-is.

**Comment by Coolthulhu** [comment]
At like 5 or so fabrication it can afford to gain some value over the regular machete.

Though it would be the best if it was "equal but different" instead of being just a bunch of shuffled points.
Say, less damage, with only marginal bashing, but shorter (lower volume) and lighter and possibly with stick prevention (or slicing type). Explained as clipping/shaving down the blade to move the center of weight towards the handle to make it easier to handle (at the cost of striking energy and momentum).

**Comment by chaosvolt** [comment]
Hmm. Could work. Will start by shaving off (pun intended) the extra point of cut I gave it. Did giving it the SLICE flag mean it gained stick prevention, then?

I'm assuming that the slice flag would likely only have lower odds of getting stuck than if it had chopping, and require the actual fag for not getting stuck to remove the chance entirely.

**Pull request merged**
