### PR TITLE
Add Surgical Cart Vehicle

### PR DESCRIPTION
**Pull request by VictoriaActual**
#### Summary
Content "Adds a medical cart to medical facilities (doctors offices, hospital, veterinarian, nursing homes) and new metal tray vehicle part"

#### Purpose of change

There are no wheeled carts to hold surgical implements and medical supplies for use in operations! This PR adds a new Medical Cart that works like a small capacity shopping cart.

#### Describe the solution

I created a metal tray vehicle part that holds 15 liters (for now) and is installed/removed with a few nuts and bolts and something to tighten them down with (WRENCH 1). The new Medical Cart is basically a shopping cart with a smaller cargo size that uses the metal tray part.

#### Testing

I've tested adding and removing the metal tray after spawning the parts needed (sheet metal and bolts), and made sure it can hold a bundle of surgical implements (scalpels, bandages, hemostatic powder, antiseptic) and be wheeled around. I added the FLAT_SURF flag to it to represent that its basically a table on wheels, but I'm open to changing that (eating lunch on a surgical cart does sound like a med student thing to do though).
Once I start adding the cart to maps I'll be sure to edit this section with my mapgen tests to make sure it spawns in correctly.
EDIT: I added the cart to the nursing home (both Shady Hills (although I didn't mess with the lab beneath) and the normal one), veterinarian's office, all the doctor offices, and to the hospital. I spawned them all in with the overmap editor and verified that the carts were there and functioned like usual. I have all of the carts rolling up the same loot in each place (which is just `gear_medical` for now) except for increasing the chances and amounts in hospital carts. 

#### Additional context

Apparently @I-am-Erk has been asking for a little cart like this for years now, so I opted to add it in when I was watching them stream cdda development. I added in a new requirement in \json\requirements\vehicle.json called 'vehicle_bolt_install_simple` that the cart uses, but it's only used there at the moment. If desired I can just go back to using the original vehicle_bolt_install for the part.
I haven't started on adding it into some of the medical maps yet as I'm still a bit unfamiliar with location editing. If there are particular locations you think I should add this to, please let me know either here or on the devcord. 👍
EDIT: I added the cart to the locations suggested, but I don't feel brave enough to spoil the TCL or some of the labs for myself and have decided against adding the carts there until I go and visit some more of those locations in my playthroughs.
There are still a few locations that could possibly use the cart like the bionics basement if it's still a thing (I saw it in the files looking for autodocs, but I haven't encountered one in a game in a long time) and several of the lab locations.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
- The obvious place for such a thing would be the hospital.
- You could argue for nursing homes (but do they really have surgical staff there)?
- Advanced doctor's offices (again, do they perform surgery there)?
- In conjunction with autodocs (but won't the tray be integrated into the equipment)?
- It should probably be present in the TLC mutant research section.

**Comment by fairyarmadillo** [comment]
Doctor's offices would have these, as would veterinary offices. There aren't dental offices, but they'd have them too.

15 liters seems really big. They're pretty compact.

These are used for more than just surgery. You could rename it to like "medical cart" and have it be in nursing homes as well.

**Comment by I-am-Erk** [comment]
15 litres is about right, we often put several 2l liquid bottles on them with room to spare.

They are indeed used in almost every medical setting. My office has three.

**Comment by BarndoBoi** [comment]
> Doctor's offices would have these, as would veterinary offices. There aren't dental offices, but they'd have them too.
> 
> 15 liters seems really big. They're pretty compact.
> 
> These are used for more than just surgery. You could rename it to like "medical cart" and have it be in nursing homes as well.

I was just thinking this yesterday while I was trying to figure out what they're actually called. It does seem like they're some variant of medical cart, and some of them come with extra drawers and cabinets inside of them for extra storage space. I'm going to rename them this evening and start looking around in the medical maps I have open in VS Code.
I gave them the 'medical_gear' loot group so far, but would it make more sense to take the group off the vehicle and instead define them in the map locations instead? I would think that a medical cart at a nursing home would have different items than a cart in a procedure room, but I need to do a little more research as well.

**Comment by fairyarmadillo** [comment]
I would avoid tying an itemgroup to the vehicle itself. A creepy lab is going to have different stuff on their carts than an animal hospital or a nursing home or a FEMA camp, as you say.

**Comment by BarndoBoi** [comment]
Alright, I updated all of the locations I felt I could tackle and tested them. I went ahead and updated the PR's body to reflect some of my updates, and I think that this one should be good to go provided the tests pass again. There are a few locations that could use the cart but that I decided against editing myself just yet, and it looks like a few modded locations like DinoMod could make use of it as well. Perhaps I'll come back in a second PR to update labs and the TCL once I've delved around inside them some more, and I'd like to go back into the hospital at some point to add roof access and perhaps a second variant if I'm feeling ambitious. UwU

**Pull request merged**
