### PR TITLE
Additional Exterior Pocket Tweaks

### LINKED ISSUE #53301: Let devs name pockets
### Is your feature request related to a problem? Please describe.

The new backpack pockets are great, but even as someone who keeps up with development and knows why they're there, I find myself looking at them and getting confused about what they're supposed to represent. This was already a problem when items had many pockets, but it's really obvious now that most backpacks have lots of them.

### Solution you would like.

Let is name pockets in the json, and display the names in the UI. For example, a survivor belt instead of having like 9 "pockets" with dimensions such and such would have one sheath, one belt loop, one holster and 6 pouches. Backpacks would have "tucked between the straps" and "clipped on" etc.

For extra credit, create a standardized library of pockets so you can just add a pre-defined KNIFE_SHEATH_LARGE instead of having to manually match existing dimensions and terminology

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Popups on item loss, more ways to lose items, UI improvements"

#### Purpose of change
This is the "Stuff @I-am-Erk wanted" PR
A collection of the low hanging fixes for external pockets after discussion on the devcord

Partially resolves #53301 

#### Describe the solution
This PR:

- Increases the chance of losing a ripoff pocket item when grabbed (using a similar algorithm to grab breakout itself with rippoff instead of strength)
- Adds a large chance of losing a ripoff pocket item when slammed (compares ripoff to melee dice * melee sides) The item ends up somewhere along your knock back vector.
- ~Adds a very minuscule chance of losing a ripoff pocket item when attacked (5 - ripoff % chance, minimum 1)~
- Adds a popup when you lose an item so you are made very aware
- Adds an optional description field for pockets to help describe them
- Compresses min and max length to one entry in the UI
- Adds descriptions to all the new exterior pockets and to ablative pockets

#### Testing

Pocket Descriptions and compressed length info:
image

Popup:
grab
image

smash
image

~attacked~
image

### CODE REVIEW

**Review by I-am-Erk — APPROVED** [review]
Looks good as best I can tell!

A small detail, may want to change the phrasing:
`Items have a chance of falling out when you are grabbed` is no longer strictly accurate
I would change it to
`Items may fall out if grabbed or hit`

**Comment by kevingranade** [comment]
I'm not clear on the rationale for ripoff from a simple attack, I think this should maybe be a special property of some attacks.
For example, there's a water bottle strapped to your backpack with a velcro loop.  It totally makes sense that someone grappling with you might grab it and rip it , off, and it makes sense that if you're thrown (either judo style or hulk smash style) it can jostle loose, but are any of the basic attacks going to have *any* chance of knocking it loose?
Punch, kick, knife stab, shot with bullet or arrow, spear thrust, axe chop, bite, headbutt, shoulder check (that does not cause a knockdown), etc...

I can see some special attacks that might be grab-adjacent like a claw swipe having a tiny chance, but I don't think it fits for blanket applying it to all attacks.

Additionally, balance and frustration wise, you simply take too many hits for this to be reasonable, 1% or worse of *every* attack adds up really, really fast and will end up as a constant annoyance.

**Comment by bombasticSlacks** [comment]
I don't have a horse in this race either way, I was on the fence about it. However as a middle ground I can reduce it from 5 - ripoff chance to 2 - ripoff chance. That means currently the only things which will fall out from melee attacks are items hanging under the handles of a duffel bag which I think is **reasonable**. I would also need to add two versions of the warning to the UI.

**Comment by kevingranade** [comment]
I'm still not buying "somebody punches you and your shovel falls out".  If an item is held that tenuously, I'd rather just call it not a viable way to carry items around.
Alternately, add a requirement for a "dislodge" flag on the attack that gets propagated into absorb()

**Comment by I-am-Erk** [comment]
> I'm still not buying "somebody punches you and your shovel falls out". If an item is held that tenuously, I'd rather just call it not a viable way to carry items around. Alternately, add a requirement for a "dislodge" flag on the attack that gets propagated into absorb()

The suggestion I had (from the description it sounds like this isn't how it's done here) is that only attacks that hit the container should have a 1% ripoff chance, so not 1% of all comers, but 1% of hits against your backpack. Since ripoff pockets here are things like your external water bottle, your pot tied loosely onto a webbing loop, or your shovel stuffed between your back and your pack, it seemed reasonable to me. I'm okay with taking it off this PR and instead requiring some kind of trait for the incoming attack that enables dislodging.

**Comment by bombasticSlacks** [comment]
okay I definitely misunderstood. We don't simulate down to the pocket level for hits so I just used the most finite option we have. I'll pull it all out right now

**Comment by I-am-Erk** [comment]
> okay I definitely misunderstood. We don't simulate down to the pocket level for hits so I just used the most granular option we have. I'll pull it all out right now.
> 
> wait on second read it seems you did mean at the pack level.
> 
> Either way it can be turned into a monster attack json flag at some point in the future for now its outta there.

I mean at the clothing level, so any hit that gets your backpack might rip something off your backpack, but a hit on your breastplate will not.

**Pull request merged**
