### PR TITLE
[CR] Enhance Driving Experience

### LINKED ISSUE #12200: Driving skill accumulates experience needlessly slowly
I have 'Fast learner' and 'Stylish' traits.  I'm wearing lots of stylish gear so my focus is routinely over 100.  Given all these favorable conditions, and given that I've been driving my motorized wheelbarrow for close to 30 in-game days, it seems silly that my driving skill hasn't hit 2 yet.  This to me seems absurd.

It's crazy that you can learn driving faster by reading a book than by actual driving.  It makes little sense to me.

### PR DESCRIPTION
**Pull request by illi-kun**
**UPDATED:**
Let's try this formula instead of simple "+1":
~~`exp = (1 + (mass / 500) ^ 1.8 + (velocity / 25) ^ 2.3)`~~
`exp = (1 + mass / 400 + velocity / 32)`, where velocity is measured in mph, and mass in kilos.

Plus, chance of applying such experience was replaced from 1-in-10 to 1-in-8.
(Formally, this PR closes #12200).

As illustration of this formula, I've tested a few cases:

| name | mass [kg] | velocity [mph] | experience |
| --- | --- | --- | --- |
| bicycle | 22 | 20 | 1 |
| beetle | 536 | 37 | ~~4~~ 3 |
| car | 735 | 52 | ~~8~~ 4 |
| car | 735 | 95 | ~~24~~ 5 |
| fire truck | 2010 | 37 | ~~15~~ 7 |
| fire truck | 2010 | 52 | ~~18~~ 7 |
| fire truck | 2010 | 95 | ~~34~~ 8 |
| sport car | 727 | 300 | ~~303~~ 12 |

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good idea, but I don't like the exponential scaling. Exponential scaling means that tanks and cargo trucks loaded with logs would give unholy amounts of xp for rolling at lowest speed possible and that going at "organ donor" speeds for just a few ticks would make you a master driver.

Take a typical sports car: 300 safe speed, which means ~300 exp per exp tick. Remove most of the car and make it a motorcycle and it becomes even faster (while being way easier to stop safely). One charge through a section of road and you're a master driver.

You need to cast both the mass and the velocity to doubles before the division (dividing it by doubles will cast it automatically), otherwise it gets all truncated.
Store the exp to be gained in a temporary double variable and only cast it down to an int at the very end. After casting, you should also randomly increase the result if the fractional part (the one dropped by casting) is non-zero. Like this:

```
double exp_temp = 1 + mass / 500.0 + velocity / 25.0;
exp = static_cast<int>( floorf( exp_temp ) );
if( exp_temp - exp > 0 && x_in_y( exp_temp - exp, 1.0 ) ) {
    exp++;
}
```

That way exp won't be lost in the division.

**Comment by DavidKeaton** [comment]
actually, you can achieve proper rounding by just adding 0.5 before the final cast to int, as any proper rounded up number won't be truncated unless it wouldn't round up anyway.

**Comment by Coolthulhu** [comment]
Just adding 0.5 will still alter the xp gain.
Say, you're driving a vehicle that gives 2.3 xp. My solution would give you 2 xp 70% of the time and 3 xp 30% of the time. Your solution would give 2 xp 100% of the time.

**Comment by DavidKeaton** [comment]
I see. Is this type of behaviour standard for skills?

**Comment by Coolthulhu** [comment]
Most skills have rather strictly defined values (no fractions), but inside the `practice` function, focus is treated this way. ie. skill gain is multiplied by focus and if it results in rounding, it is randomly increased with a chance depending on how much was lost to truncation.

**Comment by illi-kun** [comment]
Thanks for comments. I don't worry about the loss due to truncation too much, but your implementation is fine for me, I'll incorporate it.

Vehicles at high speed make huge leaps on each turn, so it's really hard to control them properly, and a lot of exp is the gain for unpredictable behavior of your transport, but, yeah, 300 xp per tick is too much.

**Pull request merged**
