### PR TITLE
Construction tweaks

### PR DESCRIPTION
**Pull request by facepalm**
Construction is another current skill that is, at the moment, nearly impossible to train without a book, which makes things like charcoal kilns and smoking racks much harder to reach than desirable.  

This PR implements a large number of small changes intended to help this situation:
- Construction projects give the same XP as crafting jobs, complete with difficulty and time scaling.
- Most construction projects now take considerably longer, from 30-90 minutes. This improves XP return, and adds a bit more realism - you're not going to build most furniture pieces in under ten minutes, or even wooden walls in less than half an hour.
- Tweaks difficulties a bit, to reflect the current situation that higher levels are exponentially more skilled than low ones.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Shallow digging and tilling jobs should probably keep that 10 minute time. Tilling without a hoe is time-costly as it is and digging can be used to create a makeshift fortification.
30 minutes to fill a deep pit is too much. 10 was fine.

"Upgraded" pits requiring 1 construction doesn't make much sense. They're just pits with stuff in them.
Same for boarded-up windows.

Did you test the exp leveling? Looking at the formula, it seems like it should be higher at the higher levels to keep up with the quadratic (not actually exponential) exp formula. Old (pre leveling nerf) behavior had exp gained/exp needed ratio mostly constant with difficulty, here it looks like this:
http://www.wolframalpha.com/input/?i=%2810%2Bn*15%29%2Fn^2
Old ratio was too low already - nobody really trained construction except sometimes first 3 levels.

Rest looks good.

As for the skill requirement lowering: construction is an underbalanced skill (nearly useless past lvl 3), so lowering the requirements would be fine even if the exp ratio was constant.

**Comment by facepalm** [comment]
I'm assuming a "shallow pit" is two to three feet deep.  I couldn't do that in 10 minutes.  Not even with a shovel, much less a digging stick.  Tilling might be a little too high, I'll grant you, but it is similar - tilling earth is [i]hard work,[/i] and slow work, even when you have an ox doing most of the heavy pulling for you.  You aren't hoeing an already-prepared garden here, you're plowing up a very small field.

As for upping some difficulties to 1, I reasoned that the difference between construction 0 and 1 was that at 1, you know which end of the nail to hit.  So at 0 you can dig a shallow pit, and dig a deep pit, but it takes Const 1 to figure out how to anchor spikes such that someone falling on them will be properly impaled, and not just knock the sticks over.  That also had the effect of spreading out tasks a bit, and giving players an option to grind past 1 without requiring a fortune in nails to build bookshelves.

Similarly, at 0 you can tape over a window, at 1 you know how to board the window up to strengthen it, and then at 3 you know how to do it __right.__  The previous difficulties for these, btw, were 0, 0, 5.

I tested skill gain at low levels, and progress felt much more reachable.  Based on experience with crafting skill gains, the increased time and desired number of later projects (namely, building walls and roofs) should help experience scale commensurately.  It wouldn't surprise me, though, if there were gaps in the progression that made certain levels impractical to reach without more options being added.  Aside from even fancier furniture, what should high Construction projects even look like?

**Comment by BevapDin** [comment]
> I couldn't do that in 10 minutes.

Have you considered that default season length (and construction time does *not* scale with it) is only 14 days?

**Comment by facepalm** [comment]
>Have you considered that default season length (and construction time does not scale with it) is only 14 days?

If that's a consideration, it should be implemented as a scaling factor for all player activity timers, not pushed out to hardcoded json values.

**Comment by BevapDin** [comment]
> If that's a consideration, it should be implemented as a scaling factor at the level of player activity timers, not pushed out to hardcoded json values.

Maybe. But for now, it doesn't scale, and any discussion should probably refer to the current behavior and the default values of that option.

Even *if* it would scale, how can you discuss this with other when everyone has their own scale? One says it should take 100 minutes (90 days season), somebody else says it should take 50 minutes (and assumes 45 day seasons), another one says 10 minutes (and assumes 9 days season). How do you compare those values?

> Have you considered that some people don't play with 14 day seasons?

Yes, but your statement "I couldn't do that in 10 minutes." is incorrect for (most of) those as well.

----

Btw. making *everything* scale with season length would make the season length option pointless.

**Comment by facepalm** [comment]
>Btw. making everything scale with season length would make the season length option pointless.

You wouldn't make everything scale with season length.  Day duration and sleep time and such wouldn't scale, but crafting would.  I don't particularly care about making sure it scales, but you seem to, so there you go.  When you start the timer, just multiply the given time by DAYS( calendar::season_length() )/91.0 to get the proportional time for the craft.  

That way the json can hold irl time values, it all can scale automatically based on whatever the player picks for their season, and we don't have to have fruitless arguments about convoluted time scaling like the first part of your reply describes.

**Comment by KA101** [comment]
Construction time should scale with season length.  Fixed-length projects take far longer of a 14-day season than a 91-day season.

**Comment by facepalm** [comment]
Maybe, but except for digging wells and mining staircases (neither of which are altered at all in this PR), the times are all still pretty short.  I can't imagine a scenario where I'm desperately trying to dig a hole because Winter Is Coming, and if the time were just a third as long, I'd make it.

Even for basic projects like farming, the total build time is currently heavily dominated by gathering the materials needed for them, not the actual construction.  While one can imagine having just too many seeds to till soil for them all in the present growing season, I can't say it's ever happened to me.

**Comment by KA101** [comment]
Noted.  I'd accept the NPC and XP changes without the JSON if you'd prefer that.

**Comment by facepalm** [comment]
This discussion has actually got me curious to see how difficult it would be to implement the kind of scaling I described to bevapdin, as I'm (so far) fairly ignorant of the intricacies of the timing system.  Let me take a crack at that, and if that's too troublesome, then sure - it's the XP change that'll help more than anything (players currently get a whopping 1.25*difficulty).   It's just silly to me to be knocking out furniture faster than Bob Vila on PCP.

**Comment by DavidKeaton** [comment]
I see no issue with just changing the value for time spent in the activity to be scaled against the season length.

**Comment by KA101** [comment]
Nor do I, but then I'm seriously not in the mood for mergetesting (still have that headache after an hour of reading RP rules, dammit) so I won't be much help.

**Comment by DavidKeaton** [comment]
Sorry bud. :-(

**Comment by facepalm** [comment]
>I see no issue with just changing the value for time spent in the activity to be scaled against the season length.

Hey, yeah, that would work well, actually.  But it'd be construction-specific, and have to be redone for each activity we want to scale, and I'm already waist-deep into player_activity.cpp.  Looks like all the tasks "based on speed, not time" are the ones which ought to be scaled to match seasons.  Just needs to be tested to make sure some tasks - melee, say - aren't suddenly 8x faster.

**Comment by KA101** [comment]
Sad part is that reading the rules is generally effective at reducing my headaches.  Much clearer, easier to work with, and not specifically targeting me.

*KA101 was reading Shadowrun anyway*

**Comment by facepalm** [comment]
Okay, so given that craft time scaling doesn't seem to be very desirable, even conceptually, are there any other outstanding points of contention I ought to address?

**Comment by KA101** [comment]
I'm still looking for such scaling, thanks much.

Expanding the calendar such that a DDA day is equivalent to a calendar day should also expand the amount of time major projects take, rather than leaving them compressed for the 1:6 DDA:calendar ratio.

Kevin can overrule me (feel free, just make it clear so we all know what the official word is) and until he does so or I receive a similarly good argument, I'm afraid times are gonna need to scale if you touch them.  (So remove the changes, and I'll queue this.)

**Comment by facepalm** [comment]
What's the official thought on adding more user options?  The consensus in the scaling thread seemed to favor that.  Something like "scale crafting time to match season length? True/[False]"

**Comment by KA101** [comment]
We try to minimize option-menu options, and I'd default it to true.

**Comment by facepalm** [comment]
I imagine Kevin'd want it to default it to false, judging by his take on the idea in the first place.  Either way, the other PR's the better place to discuss it, so I'll take it over there when I get a chance to hack.  I'm thinking it should just apply to construction tasks for now, since I don't want to have to go over all of the other crafting times to keep them from being scaled into nothingness.

**Comment by kevingranade** [comment]
I have no problem with a construction-time-scaling option, as long as it isn't specifically the season length option.  You could if you want have a scaling option that allows values ranging from some tiny number to some large number, plus a "based on season length" option.  I'm against having an option just to toggle this behavior, because it's adding clutter to the options menu for what to me is a bad idea in the first place, but having it be one value in the general scaling option would be fine.

**Comment by facepalm** [comment]
So something like "Construction multiplier.  Multiplies the speed of construction by the given percentage.  '0' automatically scales construction to match the world's season length. #Default 100 - Min: 0, Max: 1000"?

**Comment by kevingranade** [comment]
Yes, something just like that.

**Comment by KA101** [comment]
Fine by me.

**Comment by facepalm** [comment]
Just FYI, this'll need another commit after the time scaling PR goes in, to correct XP per item for varying scaling settings.

**Comment by KA101** [comment]
If you know what you need and can get it in now, feel free.  I'm on IRC if you need to get hold of me.

**Comment by KA101** [comment]
OK, hearing nothing, this'll happen tomorrow.

**Comment by facepalm** [comment]
Actually, it's fine as-is, sorry for the false alarm.  It's grabbing build.time for the XP calculation, which doesn't change with time scaling, and not build.adjusted_time(), which does.

**Comment by facepalm** [comment]
THAT was it, I knew I needed to do something before this went in.  I noticed I'd accidentally removed the skill cap from the practice calls, but didn't have time right then to fix it.

**Pull request merged**
