### PR TITLE
Extended Buildings mod

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Added Extended Buildings mod from http://smf.cataclysmdda.com/index.php?topic=8579.0.

Thanks to Whaley (http://smf.cataclysmdda.com/index.php?action=profile;u=3470).

### CODE REVIEW

**Comment by Coolthulhu** [comment]
There is already one "more locations" mod. Unless there is a good reason for why should this be separate, it shouldn't be a separate mod.

**Comment by ZhilkinSerg** [comment]
> There is already one "more locations" mod. Unless there is a good reason for why should this be separate, it shouldn't be a separate mod.

More locations mod contain large multitile Z-level structures. Locations in current mod are much smaller.

**Comment by vache** [comment]
Locations shouldn't be in a mod anyway unless they are in some way inappropriate for mainline inclusion (like missing item/monster spawns, specific to theme of mod that does not match game theme, etc).

**Comment by kevingranade** [comment]
While I agree what we really want is to mainline this content, there's also
no good reason to exclude it.  I would ask that it have a distinctive name
to prevent confusion.

**Comment by ZhilkinSerg** [comment]
> Locations shouldn't be in a mod anyway unless they are in some way inappropriate for mainline inclusion (like missing item/monster spawns, specific to theme of mod that does not match game theme, etc).

I would like to move these new locations to core eventually, but they are probably not ready for it yet.

> While I agree what we really want is to mainline this content, there's also no good reason to exclude it. I would ask that it have a distinctive name to prevent confusion.
 
Do you mean I need to change mod `ident` and/or `name`?

**Comment by kevingranade** [comment]
Yes both of those.

**Comment by ZhilkinSerg** [comment]
I name it `more_buildings`!

**Comment by secretfire42** [comment]
Just a comment (hopefully not inhelpful or unwelcome; if so I apologize) - from the 'casual forumgoer who looks at the github' - you guys have a LOT of mods in the game with names like 'more buildings', and the last time I played with them, half of them were uh, really good, and half of them were uh...errorprone. Its getting to the point where I stopped using them because I couldn't tell what was horribly broken and what was usable. So uh, I'm just going to second that you maineline, when possible, working content.

**Pull request merged**
