### PR TITLE
Increase Vehiclular Noises

### PR DESCRIPTION
**Pull request by pisskop**
Increases the volume of various vehicle noises.  A 30 volume horn is useless when the minimal volume for hordes is 60 and a zombie can see you before it could hear you if it was on the local map.

Alarms and stereos are both made loud enough to attract hordes.  Volume levels for horns have likely been untouched since sound levels were increased

### CODE REVIEW

**Comment by mutability** [comment]
Why is a stereo louder than a car horn?

**Comment by pisskop** [comment]
Why was a car alarm quieter than a stereo?

**Comment by mutability** [comment]
Not asking about the old values, asking about the new values that you want to apply.

nb: car horns are typically 100-110dB. _typical_ stereo is not going to be that loud (110dB sustained is hearing loss territory)

It seems fine to have some sound levels that only attract attention immediately nearby, not at the horde level.

**Comment by pisskop** [comment]
Nahj

**Comment by mutability** [comment]
A sound-quality ("how interesting is this sound to hordes?") value to go with the sound-intensity value? Then you could have a sensible ordering of intensity and not have deafening stereos but still have them attract hordes.

**Comment by pisskop** [comment]
concerns for realism aside, we look forward to that addition from you when it comes and this solution provides the intended functionality.

**Comment by mutability** [comment]
Until that exists can you put the sound levels in a reasonable relative
order? That was my point here which you seen to have missed.

**Comment by pisskop** [comment]
sure. if a 9mm is 166 im sure i can compare horns and stereis to it and increase tgem accordingly.  that was my point you seem to have missed

**Comment by mutability** [comment]
I don't think you understand what I am suggesting. I am suggesting you make horn_car intensity, say, 75, so that the relative ordering is sensible Not that you overhaul your changes and everything else in the name of realism.

**Comment by mutability** [comment]
This probably also needs changes to vehicle::honk_horn().

**Comment by pisskop** [comment]
9mm 159.8 dB

So it seems that the sound is in fact purely a decibel representation.
105 for a car horn
~120 for a truck
A conversation is about 65 db
And though I didnt look apparently train horns are 165

So 85 for music, 125 for a truck

**Comment by mutability** [comment]
That makes it a bit easier if we can do that. (+/- fuzz factors for balance, but at least there we can document it as "this should be 50dB, but it's set to 60 for balance reasons")

(Then again, the sound code just has a linear scale for audible distance, which seems wrong if the levels are in dB)

**Comment by Zireael07** [comment]
> (Then again, the sound code just has a linear scale for audible distance, which seems wrong if the levels are in dB)

Sound code has nothing to do with decibels atm. I think moving the numbers to decibels has been suggested a couple of times.

**Comment by pisskop** [comment]
It should be, or at least some standard applied.

**Pull request merged**
