### PR TITLE
Use xvfb on Travis

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
```SUMMARY: None```

### CODE REVIEW

**Comment by jbytheway** [comment]
Hit timeout, so this suggests there is indeed a dialog box open and it's waiting for us to say something.  If only we could see it.

My only vague idea to debug right now is to set something up to kill the process during that 10-minute period (e.g. by sending it SIGSEGV) and hope that we get a useful backtrace?

**Comment by andrei8l** [comment]
You can take a screenshot of xvfb in the usual ways, for example (assuming it's running on `:99`)
`xwd -display :99 -root -silent | convert xwd:- png:tmp.png`

**Comment by ZhilkinSerg** [comment]
Possible cause (caught on MSYS, but it is highly likely to be working the same way on wine):

image

**Comment by ZhilkinSerg** [comment]
It looks like `initial_scores` is not being cleared somehow while it should (because prior tests added some data?):

```
initial_scores.size()=26

0:score_skill_levels_gained
1:score_broken_left_arm
2:score_broken_right_arm
3:score_damage_healed
4:score_distance_crouched
5:score_distance_swam_underwater
6:score_buried_corpses
7:score_min_move_z
8:score_headshots
9:score_crosses_mutation_threshold
10:score_damage_taken
11:score_installs_faulty_cbm
12:score_moves
13:score_max_move_z
14:score_distance_mounted
15:score_distance_ran
16:score_cut_trees
17:score_distance_walked
18:score_exhumed_graves
19:score_broken_bones
20:score_kills
21:score_broken_right_leg
22:score_installs_cbm
23:score_distance_swam
24:score_gains_mutation
25:score_broken_left_leg
```

**Comment by jbytheway** [comment]
Good find.  I'll see if I can turn off that dialog for assertions.  Looks like there are some ideas [here](https://stackoverflow.com/questions/2148591/windows-preventing-assert-failures-from-opening-the-debug-popup).

**Comment by ZhilkinSerg** [comment]
Closing this.

Output to a virtual display is actually a bad idea in our case (when tests crash under wine):

- when there is no display - we see that tests crashed immediately (as it tries to output to non-existing display and fails to do so);
- when there is a virtual display - error is output to virtual display (that we cannot easily see) and we need to wait until we catch a timeout and hung tests app terminates.

We better need to find a way to redirect crashes to console or at least shush display output.

**Pull request closed without merging**
