### PR TITLE
Fix astyle regression (2018-01-04)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
@narc0tiq can we stop downstream (Android and Doxygen) projects from building if upstream build was a failure?

image

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
Self-merging to fix astyle regression introduced in #27413 (CI there was clean green there, but didn't include Jenkins build).

**Comment by narc0tiq** [comment]
In fact, I seem to have just fixed the build numbers (by introducing another layer of indirection): now there is [a Multijob project](http://ci.narc.ro/job/Cataclysm-Multijob/) that starts the Matrix, Android, and Doxygen -- and provides a single official build number for all of them.

So now the build number of the downstream projects (all three, at this point) doesn't matter, because the top-level project's build number is the real one. And, as a bonus, the downstream projects will only run when the primary is successful.

**Comment by ZhilkinSerg** [comment]
Thanks a lot! I believe everything would be great!

**Comment by ZhilkinSerg** [comment]
@narc0tiq There is an issue with Android builds, though I am not sure if timeout comes from Jenkins. Can you please check from Jenkins side? I will try to check if Android builds successfully locally.

**Comment by narc0tiq** [comment]
> Project 0. Cataclysm:DDA master build build #8406: ABORTED in 2 hr 0 min

Ouch, yep. I'll go ahead and increase the timeout for that. 3 hours should work better.

**Pull request merged**
