### PR TITLE
Add axe quality to stone adze

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Content "Add axe quality to stone adze"```

#### Purpose of change
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/28071

#### Describe the solution
see https://www.youtube.com/watch?v=-JcWY0rjePU

### CODE REVIEW

**Comment by l29ah** [comment]
AFAIU stone adze is not much different in its ability to produce planks compared to stone axe, stone hand axe and metal hand axe that already have the quality-action (that should be removed?).

**Comment by kevingranade** [comment]
Stone

**Comment by EddiTheBambi** [comment]
> All of the stone tools should lose plank making, the metal hand axe should not.

https://www.youtube.com/watch?v=b3mA0v-smtY
You could make a plank with stone tools, albeit very slowly and with most of the material from the log being wasted. Logically you should be able to get a single plank per log using the method in the video. It might not be tremendously useful or efficient but it's certainly possible and could be useful in wilderness runs where access to planks is otherwise difficult.

**Comment by Rail-Runner** [comment]
> All of the stone tools should lose plank making, the metal hand axe should not.

Well, how would people start making planks in wilderness-only plays then? I mean, there has to be some way to do it since humanity did it somehow during technological progression.

**Comment by EddiTheBambi** [comment]
> Well, how would people start making planks in wilderness-only plays then? I mean, there has to be some way to do it since humanity did it somehow during technological progression.

Planks mainly became a thing with the introduction of the saw. That requires metal processing which currently is a bit iffy in wilderness-only. Maybe that's an are that needs looking at? I don't know the plausibility of a single survivor setting up metal processing in the wilderness all by themselves but i assume, given enough time and knowledge it could work.

**Comment by kevingranade** [comment]
> You could make a plank with stone tools,

If you feel like adding the ability to harvest a single plank or beam from a log with a stone adze, feel free.
If you want to add log riving followed by using an adze to finish the resulting planks, also feel free.
If you want to build a process for chopping flats into a log with a stone adze and then assembling your logs into a log cabin, that would also be great.

> humanity did it somehow during technological progression.

You don't plane hundreds of planks with stone tools and build a modern house, you chop down trees and finish them *just enough* to be used as building materials. Heck, even with a steel axe or adze you're not necessarily going to want to go all the way to planks, just to logs with flats on them or maybe squared off beams.  What you're looking for here is log cabins or similar.

> I don't know the plausibility of a single survivor setting up metal processing in the wilderness all by themselves but i assume, given enough time and knowledge it could work.

There's a really stupidly long tech tree to get there which I'm not opposed to having in the game, but it's really just a trap, because you're not going to see significant returns on your time investment pretty much ever.  That's a bit different if you had a whole community.

**Comment by kevingranade** [comment]
As outlined above, this overreaches quite a bit, if you are interested in implementing one of the suggestions listed above, feel free.

**Pull request closed without merging**
