### PR TITLE
Add a rare spooky popup during portal storms that urges the player to go outside

### PR DESCRIPTION
**Pull request by gkarfakis19**
#### Summary
Interface "Adds a rare popup during severe portal storms encouraging players to go outside"

#### Purpose of change

Inspired by I-am-erk's suggestions on discord on how the interface can mess with the player during portal storms, this is a simple idea, introducing a popup that urges the player to leave the safety of the indoors during a portal storm. This popup should be quite rare, as it can be annoying if overused.

#### Describe the solution

Adds a new interface function that's used to specifically display this popup.
Instead of using light_red, it randomly selects from a range of colors to spice things up.
I have expanded the "u_message" EOC effect to handle interruption queries. It takes 2 additional parameters,
bool "popup_w_interrupt_query", which indicates if a popup with query should be initiated, and
string "interrupt_type" which determines what type of interrupt should be called.
My code only supports "interrupt_type" == "portal_storm_popup", but any interrupt type could be implemented in other PRs.
The message is handled through json files, much like the existing infrastructure available for "popup" : true.

TODO:
- [x] Create the new popup interface
- [x] Make the new popup occur ONLY during severe portal storms
- [x] Ensure the new popup is very rare, happening at most once per storm
- [x] Add functionality for varied, different messages in the popup (maybe through json?).

To ensure rarity, I've simply made this event 1/5th as likely as a normal portal indoor voice EOC. Is this rare enough?

In order to properly catch players unaware, I've made some of the popup messages mimic existing interrupt messages, such as      "Monsters spotted! You need to leave, fast!".  However this doesn't really work that well if these popups are also colored randomly, so perhaps I should revert to "light_red" for all of them.

#### Describe alternatives you've considered

Not adding this

#### Testing
Seems to function as intended.
(this is how the lite 'zalgo' GET OUT message renders):
image

#### Additional context
N/A.

### CODE REVIEW

**Comment by kevingranade** [comment]
We should have a xmas themed version of this based on the lyrics of "baby it's cold outside".

**Comment by Ramza13** [comment]
So this should really involve u_message.  Ideally it would be an upgrade of the current popup but I know that might be a real pain in the ass.  The easier way is to just make a new u_message option similar to popup which uses your code instead.   For reading in a string array you would just use jo.get_string_array at the top of the set_message and pass the array into the function similar to what happens with message.

After that its all json.  For making it happen once per portal storm on tough storms what you would do is add an effect to the EOC that causes a portal storm.  The effect would queue an EOC between some time frames in the future.  This EOC would check the portal strength and if high enough would use your new u_message functionality.  

If you've got any questions feel free to ask.

**Comment by PatrikLundell** [comment]
Is once per portal storm really rare? I'd expect that to lead to a "oh, here comes THAT message" reaction after the two first surprising ones. Once per 5 or 10 storms would be really rare and make them that more surprising to players who've encountered storms before, but never this.

**Comment by gkarfakis19** [comment]
> So this should really involve set_message(in npctalk.cpp). Ideally it would be an upgrade of the current popup but I know that might be a real pain in the ass. The easier way is to just make a new u_message option similar to popup which uses your code instead. For reading in a string array you would just use jo.get_string_array at the top of the set_message and pass the array into the function similar to what happens with message.
> 
> After that its all json. For making it happen once per portal storm on tough storms what you would do is add an effect to the EOC that causes a portal storm. The effect would queue an EOC between some time frames in the future. This EOC would check the portal strength and if high enough would use your new u_message functionality.
> 
> If you've got any questions feel free to ask.

Thanks for the amazing advice. I implemented most of your recommendations and everything seems to be working perfectly.

**Comment by fungamer2-2** [comment]
It would only make sense to show this message if the player is not already outside.
To do that, you should add this condition: `{ "not": "u_is_outside" }`

**Comment by gkarfakis19** [comment]
> It would only make sense to show this message if the player is not already outside. To do that, you should add this condition: `{ "not": "u_is_outside" }`

as far as I understand this only has the possibility of being called when indoors, since it's appearance is managed by the above EOC which also calls the INDOOR VOICES EOC in the same way, which does not include the indoors condition.

**Comment by gkarfakis19** [comment]
> > It would only make sense to show this message if the player is not already outside. To do that, you should add this condition: `{ "not": "u_is_outside" }`
> 
> as far as I understand this only has the possibility of being called when indoors, since it's appearance is managed by the above EOC which also calls the INDOOR VOICES EOC in the same way, which does not include the indoors condition.

Further testing has confirmed that this is the case - the popup does not trigger when outdoors.

**Comment by gkarfakis19** [comment]
I don't know why these tests are failing - this is ready for review.

**Comment by gkarfakis19** [comment]
Uhhh, the basic build test is stuck at "expected" and doesn't seem to be finishing..

**Comment by NetSysFire** [comment]
This is unfortunately normal. lgtm times out for whatever reason everywhere.

**Comment by gkarfakis19** [comment]
> This is unfortunately normal. lgtm times out for whatever reason everywhere.

I'm aware of the LGTM issue, but Basic Build is also failing to run, and it's a required merge, despite it passing for past commits.
image

**Comment by NetSysFire** [comment]
For whatever reason theres a bunch of cancelled checks in there. It might be related to those.

**Comment by gkarfakis19** [comment]
> For whatever reason theres a bunch of cancelled checks in there. It might be related to those.

I have a suspicion it was the  "GE̴T O̸UT  GE̶T OU̶T.  GE̷T OUT" string was confusing the JSON parser on github! I'll remove it for now.

**Comment by Terrorforge** [comment]
This might be a little too common, at least for alter, longer storms. I'm six months in so my storms are pretty vicious, and I got like three of these during one storm.

**Comment by gkarfakis19** [comment]
Thats too frequent, I agree. I will tone their appearance rates down to 1/2
or 1/3 of the current frequency.

**Pull request merged**
