### PR TITLE
Refactor charge consumption on item activation

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary
Infrastructure "Refactor charge consumption on item activation"

#### Purpose of change

Item activation consuming charges was different for different kinds of items. The number of charges needed was defined in different places and the not so nice `consume_charges()` were used.

Work towards units::energy based batteries.

#### Describe the solution

* Unified all item use actions to `ammo_consume()` and `ammo_remaining()` for ammo consumption.
* `charges_to_use()` should not be used directly as in future items can use both electricity and ammo on activation.
* `consume_charges()` are pretty messy and there is no reason to use it when we have the used item right there to be directly accessed.
* `ammo_scale` is now integer since the places where it is used are integers now. All items that use it have it at zero.

Removed the nonsensical feature where tools that consumed zero charges on activation instead deleted themselves (YAY!).
If you want item to delete itself after activation add `"SINGLE_USE"` flag to it. Added that to deployable manhacks and traps.

Bionics (the ones you install), and deployable furnitures still delete themselves without the above flag.

`charges_per_use` item property is not very nice and maybe should be massaged a bit. It defaults to 0 and onlty tools can set its value.
But `charges_to_use()` returns `charges_per_use` for tools,1 for comestibles and 0 for everything else.
`ammo_required()` then uses weapon stuff for and `charges_to_use()` for everything else.

#### Describe alternatives you've considered

Maybe Bionics and deployable furnitures should also use `"SINGLE_USE"` for self deletion?'
Maybe "place_monster" action should delete the item without needing `"SINGLE_USE"` flag? But I guess someone may want to make monster spawning item that is not single use some day.

Maybe single usedness should be defined in the use action instead of item. That way one item could have multiple actions where only some of them cause item to be deleted. But that seems more difficult to do.

Having `"SINGLE_USE"` on item adds text to it that tells that it is removed after use. It should be obvious from context that this would happen so maybe that text is unnecessary?

#### Testing

Tests pass.
Light testing ingame (relative to number of items that need testing).

This touches literally every single item use action so it is very possible that some of them are now not behaving properly. Too big task to test them all.
Most likely bugs to occur are incorrect charge counts and incorrect charge consumptions.

### CODE REVIEW

**Comment by mqrause** [comment]
Does this fix #59552?

**Comment by Hirmuolio** [comment]
Thje `"SINGLE_USE"` flag would probably work for single use magic item.

**Comment by GuardianDll** [comment]
What if i want to use action, and then not delete the item, but transform it to some another one? Does this PR provide some solution for this, or i need to make a separate issue about it?
Anyway good job

**Comment by Hirmuolio** [comment]
No this does not change what items do or add new behavior.

**Review by dseguin — APPROVED** [review]
LGTM, though someone else may want to give it another look

**Pull request merged**
