### PR TITLE
Unobsolete and fix the Norse Evangelicals: Round 2

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Unobsolete the Norse Evangelicals."

#### Purpose of change
Unobsolete the Norse Evangelicals, and fix various problems with their missions and dialogue.

#### Describe the solution
The Norse Evangelicals were obsoleted in https://github.com/CleverRaven/Cataclysm-DDA/pull/64417 on the basis of various complaints. This PR fixes these problems, and unobsoletes the faction.
Changes:

Using new EOC code, the camp will spawn 30 days into the Cataclysm.
Item ownership has been fixed for all materials in mapgen. This issue was mainly caused by a larger bug solved by https://github.com/CleverRaven/Cataclysm-DDA/pull/64822.

Dialogue had been expanded to make the members sound like they are actual humans. Based on three new traits, the members now have a variable belief in Norse revivalism, and a variable backstory on how they joined. They way they speak has also been changed based upon their belief, with the non-revivalists speaking more contemporarily.

Fixed the acetylene mission to take weld-ready oxyacetylene, and changed the joining mission to slaying a giant wolf, rather than a naked mole rat.

A breadcrumb quest leading to the location from the Free Merchant Teamster, 30 days following game start, has been added to allow for an easier time of finding the faction.

I have also lowered the pantry food spawns as a result of realism concerns. Additionally, all NPCs that exist as part of this faction are simulated on-map.

#### Describe alternatives you've considered
I have considered many alternatives:

Having the camp spawn on day 1, and upgrade over time.

Making all NPC's unique for custom backstories and beliefs, like those in the Refugee Center. That would be a lot of work, though.

Omitting the whole anti-Raiders side plot and replacing related missions with something else.

Having the camp spawn quite a while longer in, possibly a few months.

#### Testing
I tested everything multiple times, it all works well.

#### Additional context
Addendum 1:
Through further discussion, I’ve opted to switch some things around to make the camp a historical reenactment and living history center run by U Amherst, that the Valhallists have commandeered as a fortress.

Addendum 2:
Due to problems with force pushing and conflicts, I have reopened this under a new PR.

Addendum 3:
Due to problems with obsoletion folders causing conflicts, I have opted to copy the up-to-date obsoletion folders into the branch and use those.

### CODE REVIEW

**Comment by LordBarkBread** [comment]
If I may say on the first/last time the Norse Evangelicals were around they had an over abundance of NPC's over every inch of their base location along with a oversaturation of food/drink in stockpile that towered over what any other faction held in place.
Has that been tweaked around at all?

**Comment by MNG-cataclysm** [comment]
> If I may say on the first/last time the Norse Evangelicals were around they had an over abundance of NPC's over every inch of their base location along with a oversaturation of food/drink in stockpile that towered over what any other faction held in place. Has that been tweaked around at all?

No, I haven't changed any of the item or NPC spawn rates.

**Comment by LordBarkBread** [comment]
> > If I may say on the first/last time the Norse Evangelicals were around they had an over abundance of NPC's over every inch of their base location along with a oversaturation of food/drink in stockpile that towered over what any other faction held in place. Has that been tweaked around at all?
> 
> No, I haven't changed any of the item or NPC spawn rates.

Would it be a wise to do just that perhaps? It was rather absurd last time with the abundance of the whole location. Even the Refugee Center doesnt have that many NPC's or food items set there, could trim it down, say the NPC's are "off map" but still there, how like in the Refugee Center we don't see all the Refugees their food stockpiles that are "Down in the basement".

Makes it a little bit more in-tune for the game so a player doesn't just drive a truck through the location, steal the stockpile of food laid out and be set for just about a whole in-game year.

**Comment by MNG-cataclysm** [comment]
> Would it be a wise to do just that perhaps? It was rather absurd last time with the abundance of the whole location. Even the Refugee Center doesnt have that many NPC's or food items set there, could trim it down, say some of the NPC's are "off map" but still there, how like in the Refugee Center we don't see all the Refugees or their food stockpiles that are "Down in the basement".
> 
> 
> 
> Makes it a little bit more in-tune for the game so a player doesn't just drive a truck through the location or hell just sneakily steal the stockpile of food laid out and be set for just about a whole in-game year.

The problem they had with the inability to respond to theft has been fixed, so they will become very angry if you drive a truck through the wall and try to rob them.

I mainly wanted to have the player feel like the base was substantial with on-map NPC's, to give it that air of habitability in place of a skeleton crew that talks about grand, inobvious designs. Another thing is that, being based off of ancient Medieval wooden structures, the living history camp wouldn't have any substantial or convenient areas in which to place off-map NPC's or store food, save for a small amount of cellars. 

As for the general abundance, the Valhallists were just particularly lucky at the beginning of the Cataclysm, and their prosperity now wouldn't be a constant for later. I plan on having the faction encounter problems like that later on, as they have to either fight harder for resources or find a source of knowledge on more domestic pursuits, which could tie in to the Great Library faction down the road.

**Comment by Drew4484** [comment]
A though I had which might help explain the large group of believers: refugee evac bus breaks down, everyone is stranded and scared in the middle of the woods. After a day, a zombie finds the bus, starts banging on it. Then more show up, a few refugees get pulled out, things are generally going bad. Vahallist leader shows up, turns zombies into dog food, rescues the survivors and says they can come with him, he'll teach them how to survive. You might have some hard converts or skeptics but after a month of seeing the post-cataclysm world, people are either onboard with the vahallist way or have left the camp (maybe even picked up by the raiders or made their way to the refugee center).

**Comment by MNG-cataclysm** [comment]
> A though I had which might help explain the large group of believers: refugee evac bus breaks down, everyone is stranded and scared in the middle of the woods. After a day, a zombie finds the bus, starts banging on it. Then more show up, a few refugees get pulled out, things are generally going bad. Vahallist leader shows up, turns zombies into dog food, rescues the survivors and says they can come with him, he'll teach them how to survive. You might have some hard converts or skeptics but after a month of seeing the post-cataclysm world, people are either onboard with the vahallist way or have left the camp (maybe even picked up by the raiders or made their way to the refugee center). 

That's essentially the backstory I have for the large part of the warriors right now, but that is a very good idea for an alternate backstory for some members, or for the more transient ones which you might find out in the world. 
Thank you, that's very good.

**Comment by TheMurderUnicorn** [comment]
Does this actually resolve the issues for which it was removed?  You have made the supplies owned by the faction, and you've made the characters sound less like cult psychopaths, but the rest of the issues remain?  you chose not to reduce their being heavily supplied and populated stating they were just 'particularly lucky' which isn't much of a justification.  You chose not to build them up over time/delay their appearance (looks like 7 days in and they've recruited a bunch of folks to their weird religion), they still have the same vibes (albeit less so) of a cult.  Very little of the dialogue has actually changed beyond tweaks to explaining who they are, it seems like their belief system is the same?  You also say you did not address the mission.

I understand that you want your faction in the game, and you've done a lot here, but I don't think it resolves the issues.  Even at spawning a week into the cataclysm they're saying things like "It was a hell of a journey to get here." and "people have come and gone" implying it's been a long time.  Saying they were lucky is a cop out, in my opinion.  It makes sense for something like the refugee center to have density and items because it would be a default place many would aim for in the apocalypse, it was designed for people to congregate there.  The hub has obviously got sci fi elements that have been in the works probably for many years before the game starts.  But this random group of nerds head into the woods and form a well-supplied, well-populated cult in the span of a week.

I do not feel you've addressed many of the issues with the faction.

**Comment by MNG-cataclysm** [comment]
> Does this actually resolve the issues for which it was removed?  You have made the supplies owned by the faction, and you've made the characters sound less like cult psychopaths, but the rest of the issues remain?  you chose not to reduce their being heavily supplied and populated stating they were just 'particularly lucky' which isn't much of a justification.  You chose not to build them up over time/delay their appearance (looks like 7 days in and they've recruited a bunch of folks to their weird religion), they still have the same vibes (albeit less so) of a cult.  Very little of the dialogue has actually changed beyond tweaks to explaining who they are, it seems like their belief system is the same?  You also say you did not address the mission.
> 
> 
> 
> I understand that you want your faction in the game, and you've done a lot here, but I don't think it resolves the issues.  Even at spawning a week into the cataclysm they're saying things like "It was a hell of a journey to get here." and "people have come and gone" implying it's been a long time.  Saying they were lucky is a cop out, in my opinion.  It makes sense for something like the refugee center to have density and items because it would be a default place many would aim for in the apocalypse, it was designed for people to congregate there.  The hub has obviously got sci fi elements that have been in the works probably for many years before the game starts.  But this random group of nerds head into the woods and form a well-supplied, well-populated cult in the span of a week.
> 
> 
> 
> I do not feel you've addressed many of the issues with the faction.


I have addressed all of the listed issues with the faction, and I can have them spawn a month in if that's preferred. As for the "mission", I fixed the issue with them not accepting oxyacetylene, and changed the animal you have to kill in the introductory mission.

There might be some issue someone has with it that they haven't told me, but I have addressed all of the problems voiced within GitHub and the development channels regarding this faction.

**Comment by Drew4484** [comment]
Changing the appearance date to a month sounds good to me.

**Comment by Zireael07** [comment]
@TheMurderUnicorn I don't recall anyone complaining about their "belief system" nor "cult vibes"?

**Comment by Karol1223** [comment]
> @TheMurderUnicorn I don't recall anyone complaining about their "belief system" nor "cult vibes"?

It's been a problem brought up many many many times around the development discord.

**Comment by MNG-cataclysm** [comment]
> It's been a problem brought up many many many times around the development discord.

I intended for them to feel like a cult, because they are somewhat of a cult.

**Comment by Karol1223** [comment]
> I intended for them to feel like a cult, because they are somewhat of a cult.

Which is where the problem stems from. Cults take a while to form and yours formed in a week (from game start, which makes it 3 weeks from C-day)

**Comment by Zireael07** [comment]
@Karol1223 This is a fair point but easily fixable with some background snippets saying they were around BEFORE c-day

**Comment by MNG-cataclysm** [comment]
@Karol1223 The group in question now reaches it state a month after game start, and I have created background information that explains how they came to existence, and how their location existed before the Cataclysm.

**Comment by stubkan** [comment]
Can I ask how exactly are they being spawned in?  Because a month later, most players worlds will have pregenerated quite a few overmaps - so if you are making them spawn in ungenerated overmap tiles only - they will most likely generate something like 500+ overmap tiles away, often further - depending on how many missions the player has generated in those 30 days

So, the second issue arising from that - is - are there 'breadcrumb' quests to point you to the location?  For example, lapin the rabbit guy will give you a breadcrumb quest to the isherwoods farm.  If there are no breadcrumb quests, then it is very unlikely the player will discover a camp thats generated 500+ overmap tiles away

**Comment by MNG-cataclysm** [comment]
> Can I ask how exactly are they being spawned in?  Because a month later, most players worlds will have pregenerated quite a few overmaps - so if you are making them spawn in ungenerated overmap tiles only - they will most likely generate something like 500+ overmap tiles away, often further - depending on how many missions the player has generated in those 30 days
> 
> 
> 
> So, the second issue arising from that - is - are there 'breadcrumb' quests to point you to the location?  For example, lapin the rabbit guy will give you a breadcrumb quest to the isherwoods farm.  If there are no breadcrumb quests, then it is very unlikely the player will discover a camp thats generated 500+ overmap tiles away


The camp will spawn in the wilderness at least 5 overmap tiles away from a city, with a 50-70% chance to do so. It's unlikely to spawn 500+ tiles away from the player with the current setup, though I suppose I could increase the spawn chance to 100% when the conditions are met.

There are no breadcrumbs leading to the location yet, and I don't have any current ideas on how to implement those. I suppose the Teamster could say something about it, or have some sort of scouting party which would point the player in the direction of the fort.

**Comment by stubkan** [comment]
> The camp will spawn in the wilderness at least 5 overmap tiles away from a city, with a 50-70% chance to do so. It's unlikely to spawn 500+ tiles away from the player with the current setup, though I suppose I could increase the spawn chance to 100% when the conditions are met.

Is there not a 30 day offset? from commit [f537d23](https://github.com/CleverRaven/Cataclysm-DDA/pull/65594/commits/f537d239e258ce6ac9b3daa4e7a2f0f86cf5286e)?  If you are using the default special overmap generation and not a mission or eoc to spawn it, then it will only be able to spawn on fresh overmaps.  So I think, yes there will be a high chance that your special will spawn 500+ tiles away from the player.  You should prepare for that.

This is because every time a mission looks for a specific building (for example, a hospital) then if it cannot find one in the current overmap, it will generate (this is when specials such as your norse special get generated) more overmap maps until it finds one that contains a hospital.  This process is done for every mission that requires a specific special for it.  After 30 days, this process will have run quite a lot of times, often generating several dozen overmaps.  By the time 30 days rolls around, your special cannot be generated on any of these overmaps, so it can only generate on fresh ones, outside it.  This is why the norse special will likely generate quite far away.

> There are no breadcrumbs leading to the location yet, and I don't have any current ideas on how to implement those. I suppose the Teamster could say something about it, or have some sort of scouting party which would point the player in the direction of the fort.

Because of the aforementioned far spawn, I highly recommend you get one or two breadcrumb pathways to point the player toward your norse special, or otherwise there will be a low chance for a player to find it.

**Comment by Zireael07** [comment]
> You can also use this breadcrumb method as a way to spawn the norse special instead of relying on the default overmap generation. By giving a chat mission to travel to and behind the scenes find/generate one - for example - this will allow for closer spawns, by declaring it can be placed within X-X distance, but only on an unexplored area.

This is a good idea.

**Comment by MNG-cataclysm** [comment]
Got a breadcrumb quest in for it.

**Comment by kevingranade** [comment]
On review the whole idea of norse evangelicals is too flawed to resurrect. Any fixes to how exactly it's implemented misses the underlying problem that a settlement built around a norse religion in New England makes no sense.

**Comment by hacartwright** [comment]
Hi,
I can't find MNG-cataclysm's email so I have to ask this here.  Would you mind if I try to import this factions and quests into CTLG either as a mod or if accepted part of the main repository?

**Comment by Drew4484** [comment]
> Hi,
> I can't find MNG-cataclysm's email so I have to ask this here.  Would you mind if I try to import this factions and quests into CTLG either as a mod or if accepted part of the main repository?  

No.

**Comment by hacartwright** [comment]
Thanks!  I'll be sure to credit you!

**Pull request closed without merging**
