### PR TITLE
M14 EBR has plastic stock

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by mugling** [comment]
`m1a` should probably be `[ "steel", "wood" ]`

**Comment by BorkBorkGoesTheCode** [comment]
That is not within the scope of this PR.

**Comment by mugling** [comment]
Yes it is, `m14ebr` inherits from `m1a`. The purpose of your PR is to exchange the wooden stock for a plastic one in which case the same PR should fix the `m1a` at the same time to use `steels` as opposed to `iron`.

**Comment by mugling** [comment]
Was factored out of #17309

**Pull request merged**
