### PR TITLE
Change condensed milk spoil time from 1 day to 180

### PR DESCRIPTION
**Pull request by kholat**
#### Summary

Changes condensed milk spoil time from 1 day to 180.

#### Purpose of change

Condensed milk has only 1 day spoil time but the description and the real world suggest it should have way more.

#### Describe the solution

Changed condensed milk spoil time from 1 day to 180.

#### Describe alternatives you've considered

Leaving is as is or making it 1 year, since thats what google says. So I went with an arithmetic average ish 180 days :)

#### Testing

Trivial

#### Additional context

N/A

### CODE REVIEW

**Comment by chrispikula** [comment]
IIRC, the spoilage time that you see in game factors in the quality of the (sealed) method.  
The spoilage time you changed would be more akin to the time it takes condensed milk to spoil in open, non-temperature controled air, in, say, a bowl.  I'd check the quality of the sealing rate in the pocket that condensed milk is sealed into, (usually it's .9), and work backwards from there.

So if it's supposed to last for 180 days, but the sealing method gives it a .9 or 90% reduction in spoilage rate, that'd work out to something closer to 18 days?  Still feels a bit long to me, but it's much more reasonable.

Also, if you want to pass the validation check on the PR request, change the summary line to:

Bugfix or
Balance "Changes condensed milk spoil time from 1 day to 180."
or, since this is a small change,
None

**Comment by actual-nh** [comment]
`can_medium` (in data/json/items/containers.json) has a spoil modifier of 0.0 - which IIRC means no spoiling as long as it's sealed.

**Comment by chrispikula** [comment]
Ahh, I was wrong with how that modifier works.  I thought it was 1.0 (no spoilage) to 0, (full spoilage).  It does make more sense that it'd be the other way around, given that that way it's just a multiplication, rather than a multiplication and subtraction.

Just to be clear, it is 0.0 (No Spoilage) to 1.0 (Regular) to Higher (Fermenter/Composter?), yeah?

**Comment by actual-nh** [comment]
I double-checked in the source code, plus see [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/46329#discussion_r549001430). (And oops, it's `spoil_multiplier`, although the code does internally use `spoil_modifier`...)

**Comment by kholat** [comment]
> IIRC, the spoilage time that you see in game factors in the quality of the (sealed) method.
> The spoilage time you changed would be more akin to the time it takes condensed milk to spoil in open, non-temperature controlled air, in, say, a bowl. I'd check the quality of the sealing rate in the pocket that condensed milk is sealed into, (usually it's .9), and work backwards from there.
> 
> So if it's supposed to last for 180 days, but the sealing method gives it a .9 or 90% reduction in spoilage rate, that'd work out to something closer to 18 days? Still feels a bit long to me, but it's much more reasonable.
> 
> Also, if you want to pass the validation check on the PR request, change the summary line to:
> 
> Bugfix or
> Balance "Changes condensed milk spoil time from 1 day to 180."
> or, since this is a small change,
> None

Ok I see the issue. You should not be able to make condensed milk on its own I think; that recipe should be removed and only the ones in cans/jars/etc should be a thing, and spoil time should be what, a week or so after opened? Deffo not just 1 day though.

I knew I made the PR too fast without thinking.

**Comment by actual-nh** [comment]
> Change spoil time for the actual base "Condensed Milk" item to something, not sure exactly what (this is the opened container, so idk 1 week? 2 weeks?)

Even in a refrigerator, the spoil time is no more than a month, from a quick check - usually 1-2 weeks. It should be longer than non-sweetened milk at room temperature, but not a full week.

> Also REMOVE the recipe that creates Condensed Milk on its own, not inside a sealed container (since that just makes no sense, right now if you make this item it has 1 day spoil time)

The recipe doesn't involve canning/jarring it? Ah. I see. There look to be a total of 4 recipes; 3 of them (recipes/food/canning.json) _**do**_ involve canning/jarring; one (recipes/recipe_food.json) does not.

**Comment by anothersimulacrum** [comment]
Step one: Provide sources that unrefrigerated condensed milk will last longer than 1 day in a non-sealed container.
https://github.com/CleverRaven/Cataclysm-DDA/pull/26763#pullrequestreview-176129144

**Comment by actual-nh** [comment]
> Step one: Provide sources that unrefrigerated condensed milk will last longer than 1 day in a non-sealed container.
> [#26763 (review)](https://github.com/CleverRaven/Cataclysm-DDA/pull/26763#pullrequestreview-176129144)

Evaporated milk is down as spoiling in 1 day, as is regular milk. Condensed milk is about half sugar; this will help preserve it, sources - <https://web.archive.org/web/20080611090413/http://www.foodsci.uoguelph.ca/dairyedu/concprod.html> and Ph.D., Microbiology and Molecular Genetics; therefore, it should be more than 1 day. How much longer? That will take a bit more research.

**Comment by actual-nh** [comment]
> Evaporated milk is down as spoiling in 1 day, as is regular milk. Condensed milk is about 45% sugar; this will help preserve it, sources - https://web.archive.org/web/20080611090413/http://www.foodsci.uoguelph.ca/dairyedu/concprod.html and Ph.D., Microbiology and Molecular Genetics - I did a graduate seminar on extremophiles, for which I presented on xerophiles/osmophiles; therefore, it should be more than 1 day. How much longer? That will take a bit more research.

From what I can find, it's pretty variable. If a can already has something capable of growing in those conditions (there certainly are some - not surprising), it may well start the can bulging in 7-8 days unopened. However, that would likely be before the milk even got to the grocery store. We're talking about opened (but hopefully re-covered!) cans at room temperature. I'd go with 2 days. Note that it tends to spoil in terms of "I don't know if I should drink this" rather before it is actually undrinkable.

**Comment by kholat** [comment]
https://www.doesitgobad.com/does-condensed-milk-go-bad/#:~:text=That%20means%20it%20should%20retain,mentioned%203%20to%204%20days

Here its about 3-4 days. We have to keep in mind though that manufacturers always add safety nets for laws and lawsuits.

A case where 1 person at some point in time dies and they blame some milk company because he drank their milk 1 day before the due date so they push it to never deal with this again. That sort of stuff.

Idk 4 days seems fine to me?

**Comment by actual-nh** [comment]
> https://www.doesitgobad.com/does-condensed-milk-go-bad/#:~:text=That%20means%20it%20should%20retain,mentioned%203%20to%204%20days
> 
> Here its about 3-4 days. We have to keep in mind though that manufacturers always add safety nets for laws and lawsuits.

While it's a bit unclear, I think the site refers to in the fridge. They also add a margin to make sure people don't blame the manufacturer for a decline in quality.

**Pull request closed without merging**
