### PR TITLE
Base camp expansion

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

SUMMARY: Content "Expanded base camp framework and added new field camp version plus expansion versions"

#### Purpose of change

- Provide a framework within which new versions of base camps and expansions can be introduced in addition to the existing ones.
- New version of the modular field base camp hub.
- New versions of the existing expansions (but no new ones), except for the Saltworks.

#### Describe the solution

Dependencies between the base and the expansions have been severed when possible to make bases and expansions orthogonal to each other.
The files have been structured such that the author hopes it will make sense for others that want to add new base camps and/or expansions in a manner that does not create unnecessary coupling between different bases/expansions.

From a player perspective, the new base camp means a list of two alternatives is presented, using existing functionality. The user selects one, and the corresponding set of recipes/blueprints is used.

Expansions work in a similar, but somewhat more convoluted, way. The current selection of the TYPE of expansion is essentially the same (there's additional text in the entries). Thereafter, however, the player has to select a zero time recipe to select which set of recipes/blueprints to use.

#### Describe alternatives you've considered

Expansion selection could have been pushed up to the top level (i.e. get an expansion list containing all variants at the same time). This option was not selected for a single reason: the code that presents entries in these UI lists seem to order the entries randomly, which means getting an overview of what they contain is difficult, and it will get even more so as additional expansions and/or expansion versions are added. If the lists had been ordered alphabetically this would have been the preferred solution, but code changes are out of the scope for this already bloated PR.

Orientation selection for the version 2 expansion recipes/blueprints could have been pushed down a level to yet another zero time recipe selection. The preferred solution would be for the code to be changed such that the expansions contained a provided identifier allowing the orientation to be detected automatically. If that doesn't happen, the top level isn't sorted, and too many new expansions are added, in particular if even one of those uses orientation dependent layouts, the orientation selection essentially have to be pushed down one level.

#### Testing

Every item variant in every blueprint has been built at least once (different orientations are different blueprints) and verified visually to be as intended. Every building material has been used at least once for the new base camp as well as all the new expansion variants, relying on the fact that new material recipes/blueprints were produced using copes of a base set subjected to string replacements to generate the "same" template for a new material. The process used an experimental version currently about a month old with a new world where the PC was buffed to 20 in all stats, 10 in all skills, recruited the shelter start companion (100% chance with the skill), set out to a suitable location for a base, buffed the companion to 10 in all skills using the debug menu (to allow the companion to perform construction), used debug spawning of everything required and had the companion build the base/expansion, using the debug menu to update the time to recover the companion for the next step.

All the new expansions have been built together with both the new and the existing base camp, and all the existing expansions have been built together with the existing base camp, with sample tests together with the new base camp.

No compatibility testing with constructions in existing saves has been done, as the author does not have access to any such saves. However, pains have been taken to change identifiers only for the first step of the process (necessary to allow for any branching at all). While the recipe groups for the existing expansions and base camps have been changed to sever inter connection, the original ones remain as "legacy", which ought to work with existing games.

#### Additional context

The thread used until the changes were ready for a PR can be found here [https://discourse.cataclysmdda.org/t/field-base-camp-adjustments/24924/33](url). If desired, the various layouts can be copied to this PR (assuming github supports fixed size fonts and I can find out how to enable it).

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
This PR is waaaay too large to be reviewable. Could you perhaps go through camp by camp in separate PRs?

**Comment by Maleclypse** [comment]
Also there are several filenames changed with no changes inside the file.  That adds significant churn with usually little value.  Is it possible to not change the names of existing files when you aren't changing the contents?

**Comment by PatrikLundell** [comment]
Splitting it up would result in a string of PRs that won't work unless they're introduced in dependency order. Past experience with github hasn't been good on that point. All dependent PRs will fail because they depend on changes that haven't been approved and introduced.
In addition to that, I foresee criticism for choices made from people who would review the framework changes in isolation, because they haven't looked at the additions that resulted in the decision.

Files have been reorganized and named in order to try to get a consistent structure to how camps and expansions are handled. I have no idea of how to track which files may have had different names in different locations.

I'll try to make another PR that consist only of the reorganization of the current structure. Reviewing that would be the same as reviewing this PR but ignoring all version_2 entries (apart from the lack of that context). If that PR is approved, it's possible to produce separate PRs for the base variant and each expansion.

**Comment by Zireael07** [comment]
@PatrikLundell: I remember many dependent PRs being made here and reviewed here without issue. The biggest of them, IIRC, was 20-ish parts.

**Comment by PatrikLundell** [comment]
I don't even understand how I would be able to create a dependent PR that does not include the contents it depends on. My previous bad experience was from the dependency being on a different repository that wasn't updated because the PR depended upon wasn't approved for several months, so my local copy had the not yet approved version of the repo depended upon, but in this case I can't see how I can make a dependent set of JSON files that contain the files replaced by the PR depended upon and still somehow be convinced it's correct, as there is no possibility to test it. I can certainly see a string of PRs where the subsequent ones contain the changes relied on in addition to the new ones, but in that case they're not really dependent: each one would actually be fully independent from the smaller PRs supposed to be handled before them, as they'd contain those changes as well.

**Comment by andrei8l** [comment]
It looks like you're manually rotating and/or mirroring the maps and the rest is boilerplate to support all the variations. Can't this be done better in code? We already have `map::rotate()`

**Comment by PatrikLundell** [comment]
It could have been done better if there was code/JSON support for it. As far as I can tell, however, the current rotation support just allows mapgen placement to rotate as required, but there is no support to allow JSON to specify that a rotation by a specific amount should be used (in the same vein, the needless blueprint duplication for each building material could be removed if there was support for applying the appropriate palette to blueprint either as an override or as a mandatory addition if the blueprint lacked a specified palette).

**Comment by Night-Pryanik** [comment]
Please fill in the PR template.

**Comment by PatrikLundell** [comment]
@Night-Pryanik : As far as I can tell I have. Can you tell me what I've missed? For some reason the site compresses the contents to a single line, but I can expand it to edit it. However, I'm not aware of having done anything that should cause it to be compressed.

**Comment by Night-Pryanik** [comment]
Are there any player-visible differences between old version and your version? If yes, you can add some screenshots for better understanding of what you are trying to achieve.

**Comment by PatrikLundell** [comment]
Assuming players elect to build the new base camp hub and/or expansion versions, yes. The layouts are different from the current ones, as described in the thread referenced (where all the layouts are presented using character "graphics"). I don't know how to get github to display those correctly (i.e. using a fixed size font). I'm horrible at making screenshots and always struggle with it when I'm forced to do it every few years.

**Review by kevingranade — CHANGES_REQUESTED** [review]
To put the size of this PR in context, it increases the amount of json the game loads by approximately 20%, that's a really staggeringly huge amount of new data.

If there's any redundancy, such as the rotation thing, that must be addressed, additionally we should very much look into reducing the raw amount of data embodied by these changes as this represents a significant maintenance burden.

**Comment by PatrikLundell** [comment]
So, if I understand @kevingranade correctly, the comment basically rejects the PR on the grounds that the code doesn't have the support required for handling rotation, mirroring, and palette selection (the last @mlangsdorf didn't see any use for). Once someone provides that support the number of blueprints could be reduced drastically (8 rotations times the number of construction materials). The number of recipes would remain the same, however, unless some way to create template recipes was introduced, where you'd specify that a wildcard should be able to take any of a set of provided values. That would reduce the number of recipes maintained, while the recipes handled by the code would be the expanded set with the wildcard replaced.

**Comment by andrei8l** [comment]
You're trying to rotate the camp expansions so they face the camp hub, right? That can be achieved easily in code without json changes. Here's a quick and very dirty patch:
<details>
<summary>patch</summary>

```diff
diff --git a/src/faction_camp.cpp b/src/faction_camp.cpp
index 914814c6c8..2a541eb080 100644
--- a/src/faction_camp.cpp
+++ b/src/faction_camp.cpp
@@ -151,6 +151,20 @@ struct mass_volume {
     int count = 0;
 };
 
+namespace
+{
+    int _rotcamp( tripoint_abs_omt const &cpos, tripoint_abs_omt const &epos ) 
+    {
+        if( cpos == epos ) {
+            return 0;
+        }
+        tripoint_abs_omt const diff( cpos.x() - epos.x(), cpos.y() - epos.y(), 0);
+        double const angle = std::atan2( diff.y(), diff.x() );
+        int const rot = 1 - static_cast<int>( angle / 1.57 );
+        return rot >= 0 ? rot : rot + 4;
+    }
+} // namespace
+
 namespace base_camps
 {
 // eventually this will include the start and return functions
@@ -2600,7 +2614,7 @@ bool basecamp::upgrade_return( const point &dir, const std::string &miss,
     if( comp == nullptr ) {
         return false;
     }
-    if( !run_mapgen_update_func( making.get_blueprint(), upos ) ) {
+    if( !run_mapgen_update_func( making.get_blueprint(), upos, nullptr, true, _rotcamp( omt_pos, upos ) ) ) {
         popup( _( "%s failed to build the %s upgrade, perhaps there is a vehicle in the way." ),
                comp->disp_name(),
                making.get_blueprint() );
@@ -2941,7 +2955,7 @@ bool basecamp::survey_return()
     const recipe_id expansion_type = base_camps::select_camp_option( pos_expansions,
                                      _( "Select an expansion:" ) );
 
-    if( !run_mapgen_update_func( expansion_type.str(), where ) ) {
+    if( !run_mapgen_update_func( expansion_type.str(), where, nullptr, true, _rotcamp( omt_pos, where ) ) ) {
         popup( _( "%s failed to add the %s expansion, perhaps there is a vehicle in the way." ),
                comp->disp_name(),
                expansion_type->blueprint_name() );
diff --git a/src/mapgen.cpp b/src/mapgen.cpp
index 558f5c9747..ac73029f4f 100644
--- a/src/mapgen.cpp
+++ b/src/mapgen.cpp
@@ -7097,7 +7097,7 @@ bool update_mapgen_function_json::setup_internal( const JsonObject &/*jo*/ )
 }
 
 bool update_mapgen_function_json::update_map( const tripoint_abs_omt &omt_pos, const point &offset,
-        mission *miss, bool verify ) const
+        mission *miss, bool verify, int rot ) const
 {
     if( omt_pos == overmap::invalid_tripoint ) {
         debugmsg( "Mapgen update function called with overmap::invalid_tripoint" );
@@ -7106,10 +7106,13 @@ bool update_mapgen_function_json::update_map( const tripoint_abs_omt &omt_pos, c
     tinymap update_tmap;
     const tripoint_abs_sm sm_pos = project_to<coords::sm>( omt_pos );
     update_tmap.load( sm_pos, true );
+    update_tmap.rotate( rot );
 
     mapgendata md( omt_pos, update_tmap, 0.0f, calendar::start_of_cataclysm, miss );
 
-    return update_map( md, offset, verify );
+    bool const u = update_map( md, offset, verify );
+    update_tmap.rotate( 4 - rot );
+    return u;
 }
 
 bool update_mapgen_function_json::update_map( const mapgendata &md, const point &offset,
@@ -7184,14 +7187,14 @@ mapgen_update_func add_mapgen_update_func( const JsonObject &jo, bool &defer )
 }
 
 bool run_mapgen_update_func( const std::string &update_mapgen_id, const tripoint_abs_omt &omt_pos,
-                             mission *miss, bool cancel_on_collision )
+                             mission *miss, bool cancel_on_collision, int rot )
 {
     const auto update_function = update_mapgen.find( update_mapgen_id );
 
     if( update_function == update_mapgen.end() || update_function->second.empty() ) {
         return false;
     }
-    return update_function->second[0]->update_map( omt_pos, point_zero, miss, cancel_on_collision );
+    return update_function->second[0]->update_map( omt_pos, point_zero, miss, cancel_on_collision, rot );
 }
 
 bool run_mapgen_update_func( const std::string &update_mapgen_id, mapgendata &dat,
diff --git a/src/mapgen.h b/src/mapgen.h
index a04898055f..0ee18bb0d4 100644
--- a/src/mapgen.h
+++ b/src/mapgen.h
@@ -378,7 +378,7 @@ class update_mapgen_function_json : public mapgen_function_json_base
         bool setup_update( const JsonObject &jo );
         void check() const;
         bool update_map( const tripoint_abs_omt &omt_pos, const point &offset,
-                         mission *miss, bool verify = false ) const;
+                         mission *miss, bool verify = false, int rot = 0 ) const;
         bool update_map( const mapgendata &md, const point &offset = point_zero,
                          bool verify = false ) const;
 
diff --git a/src/mapgen_functions.h b/src/mapgen_functions.h
index fe7355ea8f..792fa26ddc 100644
--- a/src/mapgen_functions.h
+++ b/src/mapgen_functions.h
@@ -83,7 +83,8 @@ void madd_field( map *m, const point &, field_type_id type, int intensity );
 
 mapgen_update_func add_mapgen_update_func( const JsonObject &jo, bool &defer );
 bool run_mapgen_update_func( const std::string &update_mapgen_id, const tripoint_abs_omt &omt_pos,
-                             mission *miss = nullptr, bool cancel_on_collision = true );
+                             mission *miss = nullptr, bool cancel_on_collision = true,
+                             int rot = 0 );
 bool run_mapgen_update_func( const std::string &update_mapgen_id, mapgendata &dat,
                              bool cancel_on_collision = true );
 bool run_mapgen_func( const std::string &mapgen_id, mapgendata &dat );
```
</details>
(don't use this patch as it is; it's just here as a demo and to help you get started)

<details>
<summary>screenshot</summary>

scr
</details>
Mirroring should not be too difficult either.

If you're tying to do something else, then at least upload a screenshot so we can try to figure something out to help you (without parsing 100k lines of json).

**Comment by PatrikLundell** [comment]
Well, the purpose of the PR was to provide one that did not involve changes to the code. Trying to understand that and deal with backwards compatibility was intended to be a later exercise that might turn out to be too difficult, while dealing with JSON at least seemed like a possible starting point.

The problem with your approach is that it rotates everything (I haven't looked at the actual code yet), and I only want to rotate/mirror layouts that are intended to be rotated/mirrored without affecting existing layouts (and I think trying to rotate anything while in the process of being constructed will result in an expansion that's half original and half mirrored).

**Comment by andrei8l** [comment]
> The problem with your approach is that it rotates everything (I haven't looked at the actual code yet), and I only want to rotate/mirror layouts that are intended to be rotated/mirrored without affecting existing layouts

You can add a json flag if only some expansions should be rotated.

> (and I think trying to rotate anything while in the process of being constructed will result in an expansion that's half original and half mirrored).

if you mean migration-wise, then that's also just a json flag (or save format version) check AFAICT! Otherwise you can see some not-broken upgrades already in the screenshot.

**Comment by PatrikLundell** [comment]
If JSON flag additions can be used to specify that the blueprints referenced by recipes should be mirrored vertically and/or horizontally and/or rotated by 90/180/270 degrees then those additions should be sufficient to achieve the objective of giving the directions. Now, if you can also add flags to indicate that blueprints should be mirrored/rotated based on the location of the expansion (which I think the code should have access to), a whole lot of blueprints and recipes could be folded into a much smaller set.
I know very little about the JSON stuff, including flag handling. If I added a flag in the JSON file, would it automatically propagate so it could be examined by code without the addition of additional parsing so that I'd only have to add the flag to the JSON file and code to extract it from the recipe in the code applying that recipe, but nothing to the JSON -> internal data translation step?

**Comment by Night-Pryanik** [comment]
@PatrikLundell do you still work on this?

**Comment by PatrikLundell** [comment]
Yes and no...

I've made two other PRs that will pave the way for the actual contents to be submitted as PRs. However, those PRs are floating in limbo since last year (only indication of any attention is that the assassin bot was called off for one of them, while the other stalled the assassin bot by having to resolve conflicts against PRs accepted since), but once those PRs have been accepted I intend to produce one PR for each of the expansions plus the core.

There is no point in resolving the conflicts introduced by other PRs in this PR, as that has been done in the base reorganization one, and there's little point in updating the expansions/core here if the PR that cuts down on the number of files needed isn't approved.

Once those additional PRs have been submitted, I intend to close this one as it has served its purpose, but until that time I intend to leave this PR as a reference, as it's the only place where the target is shown (the base reorganization one is kind of pointless on its own).

**Comment by I-am-Erk** [comment]
I am closing this PR as it doesn't seem to be under construction anymore. however I do think there is a ton of useful stuff in here that should be salvaged.

**Comment by PatrikLundell** [comment]
It's correct the PR itself isn't under construction. @kevingranade requested it to be split up, and so that's being done. This PR remains as a reference (which in itself references the thread that preceded it), so my intention was to close it when all its parts had been submitted as PRs. The two initial PRs were kept hanging in limbo essentially since last year, but since the second one of those has just been approved I know in which direction to proceed. The base camp hub PR was submitted today (as you noted), and I expect to submit one for each remaining expansion at an approximate rate of one per day (it takes  some time to regression test the implementation against the changes that have happened since, and there may be a need to adjust the recipes against changes as well).

**Pull request closed without merging**
