### PR TITLE
Make double-barreled flintlock carbine recipe similar to single-barreled version

### PR DESCRIPTION
**Pull request by nornagon**
Not sure if this is the right modification to make, but it seemed weird that the double-barreled flintlock carbine was easier to make than the single-barreled version.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
There is a reason for that. It is explicitly described and statted out as a more makeshift item than the normal flintlock weapons.

See original pull request: https://github.com/CleverRaven/Cataclysm-DDA/pull/18485

**Comment by nornagon** [comment]
Ahh, I see. Perhaps it could be named to match? The description is fairly subtle.

I'm closing this for now, though.

**Comment by DangerNoodle** [comment]
The addition of "survivor's" or "makeshift" to the name might be desirable then.

**Comment by Graywolfe813** [comment]
> statted out as a more makeshift item

Except it's not. Slightly higher dispersion, lower recoil, otherwise equivalent to a standard flintlock carbine, from what I'm seeing.

**Comment by DangerNoodle** [comment]
Hmm. I had thought that I based several of the statistics of a mix of the rifle and carbine, generally taking the worse of the two properties when sensible.

Note that it is meant to be in between the pipe guns and the other flintlocks in quality, so it being inferior to the flintlocks in most regards (except capacity of course) while a step up from other makeshift firearms is intended. If it warrants a nerf relative to the flintlock carbine then that can be done.

**Comment by Graywolfe813** [comment]
I'm seeing a recipe here to make one using 2 flintlock carbines/rifles, also... That leads to a conflict, since I would think taking two well made barrels and firing mechanisms, and placing them on a single stock wouldn't hurt their effectiveness much.

Bit of a pickle, there?

**Comment by DangerNoodle** [comment]
True. I am unsure how best to change the weapon in that case, other than a rename.

**Comment by nornagon** [comment]
We could:

- buff the weapon such that it's more similar to the single-barrel version, just with two barrels (increased dispersion and recoil to pay for the extra shot seems reasonable).
- remove the recipe to craft it from the single-barrel version, and rename it to 'makeshift double-barrel flintlock carbine'

**Comment by DangerNoodle** [comment]
That might work. Currently it is already mostly comparable to the carbine except for 20% more dispersion, so more recoil might be acceptable. Other possible inclusions might be -1 to range, or -2 to damage (relative to the carbine).

That said, it might be reasonable to expect that taking apart a pair of professionally made firearms and putting them together with only basic tools might have some impact on fit and finish, though I am unsure how much impact it would be.

**Comment by DangerNoodle** [comment]
Though strangely, I cannot find any recoil listed on any of the flintlock firearms. Even the pistol, which should be harder recoiling than a rifle firing the same ammunition (though same reasoning means that more recoil relative to single-barrel might be illogical unless fit and finish played into that).

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle are the flintlock firearms loaded when you examine them?

**Comment by DangerNoodle** [comment]
What do you mean? I was referring solely to the base stats of the weapons in question, not the weapons plus ammunition.

**Comment by BorkBorkGoesTheCode** [comment]
Recoil is tied to gun weight now.

**Comment by DangerNoodle** [comment]
Oh, I see. That would explain it.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle This is the PR which changed recoil: https://github.com/CleverRaven/Cataclysm-DDA/pull/18362
It describes some of the

You might be able to adjust the "handling" field on a gun, but be aware that I haven't been able to do so without odd results.

**Comment by DangerNoodle** [comment]
For now I have not yet tried to alter recoil, instead changing other properties.

**Pull request closed without merging**
