### PR TITLE
Raise spawn chance for cardboard boxes.

### LINKED ISSUE #35795: "Normal" cardboard boxes are absurdly rare
**Is your feature request related to a problem? Please describe.**  
Small and large cardboard boxes are seemingly everywhere, yet medium ones are nowhere to be found.

This makes Dino Dave's quest ludicrously hard to complete.

**Describe the solution you'd like**  
Replace some small/large box spawn points with medium ones.

**Describe alternatives you've considered**  
Make cardboard boxes craftable.

**Additional context**  
I don't think a lunatic hobo's fetch quest should be more difficult to complete than hub 01 recovery missions ¯\\\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by arijust**
#### Summary

```SUMMARY: Balance "Raise spawn chance for cardboard boxes."```
#### Purpose of change

Close #35795
#### Describe the solution

Tweak probability to get boxes in several item groups.
#### Describe alternatives you've considered

Raise spawn chances a bit more and make some items spawn in medium boxes.

### CODE REVIEW

**Comment by SpellingSword** [comment]
Thanks :)

**Comment by I-am-Erk** [comment]
@zhilkinserg I was kinda in the midst of suggesting changes there...

**Comment by I-am-Erk** [comment]
So @arijust I can go do it in a separate pr, but if you'd like to learn to adjust this stuff let me know either here or on the discord. It's not incredibly difficult.

Basically the code looks like this
```{
        "collection": [
          { "item": "plastic_spoon", "count": [ 0, 6 ] },
          { "item": "plastic_knife", "count": [ 0, 6 ] },
          { "item": "plastic_fork", "count": [ 0, 6 ] }
        ],
        "prob": 30
      },
      { "item": "plastic_spoon_kids", "prob": 35, "count": [ 1, 6 ] },
      [ "corkscrew", 75 ],
```
Everything inside the added collection has a chance of spawning together, so if you made that eg. a medium cardboard box and some packs of nails, it would spawn all those things together, implying a cardboard box full of packs of nails. It's not quite a container because our code isn't there yet, but it's a decent functional representation of one.

**Comment by arijust** [comment]
I will note that for my future PRs, but it would take me some time before I get used to it.

**Comment by I-am-Erk** [comment]
Yep no worries. I will probably make a second PR adjusting the changes in this one so you can see what I mean, and then if you want to further add cardboard boxes to spawn along with things that might spawn with boxes you'll be able to see how. TOGETHER, WE COULD FILL THE EARTH WITH CARDBOARD.

**Comment by arijust** [comment]
Alright, thanks.

**Pull request merged**
