### PR TITLE
Stops roadblocks from spawning live zeds

### LINKED ISSUE #11131: Active zeds probably shouldn't spawn at roadblocks/outposts
I'm noticing some incongruities. For example, military turrets are shooting zombie soldiers and bio operators. Same for turrets at roadblocks and the cops. I bet lab turrets shoot scientists too.  Fungal zombies are fighting regulars and vice versa, when probably they wouldn't realize any difference. And everybody goes after spore clouds, when they seem like they should be ignored.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8296871-active-zeds-probably-shouldn-t-spawn-at-roadblocks-outposts?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Toothspit**
Fixes #11131

### CODE REVIEW

**Comment by pisskop** [comment]
why?

zeds at roadblocks makes sense and is part flavor.

additionally, any argument about them being dead or murdered by robots fails to take into account the zeds reviving periodically.

the gunshots additionally serve to _warn_ the player

**Comment by kevingranade** [comment]
Does the item spawn that is the alternative to the zombie include a corpse?
If it does that seems reasonable to me from a thematic POV, eventually the
turret could do enough damage to finish off the zombies.

**Comment by Toothspit** [comment]
> why?

Because it's been an open issue with the 'Bug' label for two years and nobody closed it nor disagreed with KA101, and is low-hanging fruit. I don't disagree with you.

> Does the item spawn that is the alternative to the zombie include a corpse?

Yes.

**Comment by Leland** [comment]
> the gunshots additionally serve to warn the player

this is an *excellent* counterpoint to this PR

**Comment by Toothspit** [comment]
> this is a good counterpoint to the PR

Sure. But it hasn't come up in [2 years](https://github.com/CleverRaven/Cataclysm-DDA/issues/11131). Will close when the issue closes, that's where discussions like these should be, and 2 years of non-controversy is a pretty good measure of consensus, IMO.

Open to be proven wrong, of course, I'm not personally attached to roadblocks.

**Comment by Toybasher** [comment]
Came across this. 

I noticed, looking at the code, it seems [I might be wrong] that the turrets only have a chance to spawn in mapgen.cpp in police roadblocks? Can the live zombies spawn...alive in those cases as there's no turret to kill them?

**Pull request merged**
