### PR TITLE
Recipe tweaks

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Remove wrench from welding goggles recipe and change recipe to consume a charge of spray can instead of whole can.
2. Make mop recipe reversible and remove the mop from recipes.
3. Add ethanol to first aid kit recipe.
4. Add recipe to disassemble cigarette pack into paper.
5. Remove recipe for 10 plastic bags bundle item. This item is just useless.
6. Add empty canisters to tinned food recipes, so that you could store food in containers that you made, not just scavenge or reuse existing ones.
7. Add 6 aluminium cans to aluminium powder recipe.
8. Add skill_used to 0-level recipes.
9. Change candle recipe to use CONTAIN quality instead of tin can or empty canister as a component.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
If you're obsoleting the 10 plastic bag, move the item to obsolete.json file too.

**Comment by Night-Pryanik** [comment]
What's the point behind removing the mop from recipes?

**Comment by Core0verload** [comment]
>What's the point behind removing the mop from recipes?

There is no reason to keep mop in recipes as analogue to wood stick if you can just disassemble a mop to get that stick.

**Comment by Mecares** [comment]
And what am i supposed to use to remove Zombie blood from my kitchen floor if i can not craft a mop anymore if i cant find it?

**Comment by Darkyhard** [comment]
> And what am i supposed to use to remove Zombie blood from my kitchen floor if i can not craft a mop anymore if i cant find it?

Actually you can now both craft and disassemble it. It was possible only to craft it before this change

**Comment by Mecares** [comment]
Okay, then i must have misinterpreted the initial post. Great job.

**Pull request merged**
