### PR TITLE
Help to json

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Interface "Moved help menu and texts to .json"```

#### Additional info
Key actions can be inserted via ```<press_open>``` which uses the action translation from ```action_ident( action_id id )```

Special cases for note colors: ```<DRAW_NOTE_COLORS>```
and movement directions: ```<HELP_DRAW_DIRECTIONS>```

~~PS: I feel like I'd have to add those new .json text fields somewhere for translations to work but I don't know where that'd be?!~~ Done.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
End quotation mark is missing in summary line.

**Comment by OzoneH3** [comment]
Jenkins rebuild.

**Comment by BevapDin** [comment]
Do we really need this? It contains some special logic in order to show the very same information as the current version (e.g. color names, direction keys matrix). What useful possibilities does this add? How is this going to be used?

**Comment by OzoneH3** [comment]
It's a first step in updating the whole help system. I didn't want to make any major interface changes in this already big PR. The special logic can be put to json as well at some point.

**Comment by cainiaowu** [comment]
the Python script that handle string extraction is what you need.

**Comment by OzoneH3** [comment]
I'll rebase again once this gets a green light.

**Comment by kevingranade** [comment]
Rebased and merged :+1:

**Comment by ZhilkinSerg** [comment]
There is no check in `get_dir_grid` function whether direction keys are bind.

**Pull request closed without merging**
