### PR TITLE
Audit pine nuts and remove the recipe

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Balance "Audit Pine Nuts"

#### Purpose of change
Audit pine nuts to realistic caloric density etc. and remove the pine nut recipe.

#### Describe the solution
Change JSON values to half of what they were since the calories listed would be approximately double of what it would be per pinecone.

Pinecones have 2 nuts per scale with approximately 50 scales per average pinecone.
That's about 100 nuts, which would weigh about 15 grams.
Additionally, 10 nuts are about 11 calories, thus leading to 110. But, not all the nuts are going to be good so 101 (exactly half of current values) is a reliable estimate.

Additionally, the type of pine nuts used for consumption in the game are not true to new england since they are not harvestable in new england.

#### Describe alternatives you've considered
Continue to let the pine king rule.

#### Testing
Spawn pine nuts.
image

### CODE REVIEW

**Comment by kevingranade** [comment]
Just FYI, the pine nuts this is based on aren't even present in New England, they should be replaced with foods it's reasonable to forage for in New England.

**Comment by CodeBandit** [comment]
Should pine nuts be removed from the game since they aren't technically harvestable in new england?

**Comment by mrkybe** [comment]
> 
> 
> Should pine nuts be removed from the game since they aren't technically harvestable in new england?

I believe there might be stores that sell a variety of foods not typically harvestable in New England.  ;)

**Comment by dissociativity** [comment]
I'd make them take significantly longer to harvest from pinecones given they'd be smaller nuts, time for pine nuts with this merged is still the remaining issue, it's too quick and efficient still to harvest, perhaps make the recipe require two pinecones for one charge?

**Comment by CodeBandit** [comment]
For now, I have opted to obsolete the pine nut recipe from pinecones and increase their spawn probabilities in item groups already containing pine nuts.

**Comment by BenlyAZ** [comment]
New England pine trees do have edible seeds, they're just smaller than the pine nuts from European stone pines. They are, however, seasonal as the seeds drop out of the cone eventually. For an overview of wild-harvesting pine nuts for American survivalists, primalsurvivor.net/harvest-pine-nuts-wild/ seems like a good start.

**Comment by CodeBandit** [comment]
Well okay, I didn't mean to dive this deep into it, but to really shut this down, here it is:
https://www.maine.gov/dacf/mfs/publications/handbooks_guides/forest_trees/pdf/Pines.pdf

There is no distinction between the species of pine trees in CDDA. From the link above there are species of pine trees in the pine tree state (maine) which comprise about 50% of new england. 
image

Of those 5 trees, 3 of them are prevalent in all of new england, their partial distribution maps are as follows:
Pinus Rigida
image

Pinus Strobus
image

Pinus Resinosa
image

This is also directly backed up by the game's description of pine trees:
image

Only one of these seeds (in particular the Pinus Strobus) was used for consumption historically, however not mainly for the nut itself.

[Source](http://eattheplanet.org/eastern-white-pine-an-effective-remedy-for-the-common-cold-2/)
```[Eastern White pine has very small nuts, they can be eaten, but usually are too much effort to collect.]```

With that, I personally believe pine nuts shouldn't be craftable from pinecones.

With the removal of the pine nut recipe, however, I may look into foraging in a different PR.

**Comment by EvgenijM86** [comment]
More on the topic of overpowered food sources: I was doing a winter start game, found diary farm, brought cows inside a house and tied them with a rope, and then simply lived there for over a month. 2 cows generate enough milk to always to max out your quench needs even with High Thirst trait. And it seems that you can sustain yourself that way without needing to collect any other food source ever again, as long as cows are safe.

image

**Pull request merged**
