### PR TITLE
Adds deconstruct recipe for copper pot.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
A good source of scrap copper.

### CODE REVIEW

**Comment by Zireael07** [comment]
Thought it'd be melting it, seems the survivor just saws it into pieces?

**Comment by Mecares** [comment]
Nice, already wondered why it can not be dissembled. While you are at it it seem like Hot-pants are also missing their deconstruction recipe.

**Comment by karols146** [comment]
> Thought it'd be melting it, seems the survivor just saws it into pieces?
Yea i think about melting, cutting pot in pieces sounds little weird.

**Comment by Mecares** [comment]
Well it should be an option if you do not have the necessary tools to melt it and depending on what you want to do with the copper it might even be better to use the flat pieces you cut it into instead of a massive solid ingot.

**Pull request merged**
