### PR TITLE
Fix telescope eyes not preventing eye mutations

### LINKED ISSUE #15211: Ursine Vision not affected by Telescopic Eyes CBM
Right now Ursine Vision sight limitation can be neglected with glasses or contact lenses. However, Telescopic Eyes is also supposed to be like "any vision problems you might have had are now gone", but it doesn`t affect Ursine Eyes in any way.

Maybe it should be treated as "integrated glasses" and remove Ursine Vision range handicap totally?

### LINKED ISSUE #21407: Telescopic Eyes don't affect nearsightness if installed prior to that mutation
Also may be related to #15211.

Currently, as Telescopic Eyes fix vision problems upon installation, it's possible to be near/far-sighted and have Telescopic eyes at the same time, if you first install Telescopic Eyes and then manage to roll Nearsighted mutation.

I think it's inconsistent with the lore, as Telescopic Eyes are supposed to replace your eyes completely. Additionally, they are impossible to remove, so you can't just reinstall them to fix the problem.

Build: 
image 
but I think it affects all versions.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix telescope eyes allowing eye mutations to be gained"

#### Purpose of change
Fixes #21407
Fixes #15211
Prevents gaining eye mutations with telescoping eyes installed

#### Describe the solution
Added a check to is_mutation_ok to prevent gaining eye mutations while having telescope eyes installed.  Also expanded the number of eye mutations removed to correspond with the prevented ones.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
My only concern is hardcoded list of affected bionics. Maybe replace it with some new flag on bionics?

**Comment by Fris0uman** [comment]
Yes please don't hardcode it, there is already a thing for CBM to remove mutations if you could expend it to also forbid getting those mutations that would be great.

**Comment by Ramza13** [comment]
Thanks for the feedback!  I have changed it to now work for anything using the canceled mutations tag and added the correct tags to bionics.json.

**Comment by Amoebka** [comment]
This behaviour isn't really correct in the general case either. Just because a CBM removes certain mutations on installation doesn't mean it should also **always** prevent them from reappearing. A CBM that replaces your eyes obviously removes eye mutations, but it doesn't prevent you from growing another pair of eyes elsewhere after the fact.
Ultimately, this is something that should be set case by case, so a **new** flag is needed.

**Comment by Ramza13** [comment]
At the moment this is the only time this tag is being used so I guess I could rename it to be more accurate but I'm not sure if that's a good idea.

**Pull request merged**
