### PR TITLE
added message when items are destroyed rather than damaged

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Interface "Added 'destroys' message when items are destroyed (rather than just damaged)"```

#### Purpose of change
The message "the weight of the vehicle damages the diesel!" as reported in #38080 was also confusing to me as a new player. It made me think that diesel has hit points, and in general it felt weird to be told something was being damaged when it was actually destroyed.

The purpose of this change is to clarify this message to "destroys" instead of "damages" when the item in question was in fact destroyed.

#### Describe the solution
I added a new check in map.cpp which has 4 outcomes when items are damaged, listed below in priority order (top happens first if triggered):

More than one item destroyed: "The X destroys several items!"
Exactly one item damaged and destroyed: "The X destroys the Y!"
More than one item damaged: "The X damages several items." (changed previous "!" to ".")
Exactly one item damaged: "The X damages the Y." (changed previous "!" to ".")

#### Describe alternatives you've considered
There is probably a more in-depth question of as to scenarios the player doesn't need to see the message at all. Also not doing anything.

I felt as a new player that "The weight of the car damages the diesel!" was a bit confusing, but I feel that "The weight of the car destroys the diesel!" will hopefully be slightly less confusing.

#### Testing
Tested a bunch of scenarios with single and multiple item piles, driving over them. Verified the messages match what I documented above.

Below is an example of a multi-item stack having items destroyed/damaged:

sc001339

sc001340

I am not an expert in this part of the code, so if there are edge cases I'm not aware of (like item removal not actually representing destruction, or items that can respawn themselves and wouldn't be considered destroyed, or situations where "destroyed" is not accurate), I'd appreciate some thoughts.

Also this is my first time adding or modifying strings in C++, which I imagine causes some headaches for the translators of the world -- so if I'm missing a step in being translation-friendly let me know.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I wonder if removing the "destroyed" message for liquid items would be a good idea.

**Comment by jkraybill** [comment]
@Night-Pryanik I tend to agree but I'm sure there are exceptions like high-value liquids like serums etc? For now this at least seems like a straight improvement but welcome any feedback.

**Comment by Night-Pryanik** [comment]
I mean there is no way to gather these spilled liquids anyway, why bother player about them?

**Comment by TechyBen** [comment]
> I mean there is no way to gather these spilled liquids anyway, why bother player about them?

Seperate from this update, but would a "tank leaks out X" message instead be prefered. While a player does not need to know about non recoverables being damaged (though they are interactable via setting light to fuel), knowing a tank is leaking is an important bit of information (assuming visible to the players character). This message currently does form a partial notification to the player that items/fuel is leaking.

**Pull request merged**
