### PR TITLE
Make compared have a copy of the inventory_entry rather than a pointer to fix segfault when using multiple filters.

### LINKED ISSUE #34046: Crash when comparing daypack and military rucksack
Game version: 0.D-7603-g1b96ad13c5-dirty

(but I didn't change anything related to encumbrance in my local build)

Operating system: macOS 10.13.6

Tiles or curses: Tiles

Mods active: 

### Expected behavior

Don't crash when comparing items

### Actual behavior

SIGSEGV with 
```
0   libsystem_kernel.dylib        	0x00007fff55715b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff558e0080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff556711ae abort + 127
3   cataclysm-tiles               	0x000000010fb88643 signal_handler(int) + 83
4   libsystem_platform.dylib      	0x00007fff558d3f5a _sigtramp + 26
5   ???                           	0x0000000111636e00 0 + 4586696192
6   cataclysm-tiles               	0x000000010fe7a533 item::is_null() const + 99
7   cataclysm-tiles               	0x000000010fe7b55c item::volume(bool) const + 28
8   cataclysm-tiles               	0x000000010feba53b item::get_encumber(Character const&) const + 75
9   cataclysm-tiles               	0x000000010fe7dfde item::info(std::__1::vector<iteminfo, std::__1::allocator<iteminfo> >&, iteminfo_query const*, int) const + 782
10  cataclysm-tiles               	0x000000010fe7dc81 item::info(bool, std::__1::vector<iteminfo, std::__1::allocator<iteminfo> >&) const + 49
11  cataclysm-tiles               	0x000000010fd95477 game_menus::inv::compare(player&, cata::optional<tripoint> const&) + 1991
12  cataclysm-tiles               	0x000000010fdb8cc4 game::handle_action() + 7908
13  cataclysm-tiles               	0x000000010fcedbcf game::do_turn() + 2399
[...]
```

### Steps to reproduce the behavior
In a new world, spawn a military rucksack and a daypack. Wear the military rucksack. Then press <kbd>I</kbd> to compare items, and use the search function <kbd>/</kbd> to search for "mil", press enter to confirm the search, and press right arrow to select the rucksack you're wearing. Then press <kbd>/</kbd> again, search for "day", press enter to confirm the search, then press right arrow to select the daypack. The game will crash before it shows the comparison screen.

This is 100% reproducible for me.

### PR DESCRIPTION
**Pull request by ishtatann**
```SUMMARY: Bugfixes "Make compared have a copy of the inventory_entry rather than a pointer to fix segfault when using multiple filters"```

#### Purpose of change
Fixes #34046

#### Describe the solution
Converted the compared vector to be a copy of the inventory_entry instead of a pointer.

#### Describe alternatives you've considered
I considered turning compared into an item* but that turned into something very invasive.

#### Testing
Verified that comparison works with and without filters after the change.

### CODE REVIEW

**Comment by AMurkin** [comment]
I'm getting a segfault.
Stack trace: https://gist.github.com/AMurkin/157efbdc9cb8656f3fac650f31119d7b
It's on Linux Tiles.

Steps:
* with several items in inventory press
* `I<arrow right>/<some filtering text>Enter<choose any item>`

**Comment by ishtatann** [comment]
I haven't been able to replicate this problem on MS VS19.

The stack trace points to the item disappearing on linux for some reason.
But my read through inventory_entry down to the item says that shouldn't be happening.

I did try a completely different approach of making the entries_unfiltered the master list and entries pointers to the inventory_entry's in that list.  Ended up changing a ton of things and completely broke inventory as well as compare.

I know KorGgenT is doing heavy work in this area at the moment so am going to pause doing any more work on this PR to see how those changes shake out.

**Comment by KorGgenT** [comment]
@ishtatann you got it backwards, the stuff i'm working on is low priority compared to this being a release blocker.

**Comment by ishtatann** [comment]
Save a copy of the first selection before set_filter is called.  Restore the first selection after set_filter finishes.

I'm hoping this will fix the crash people were seeing on the linux side.
Works fine in my testing of x64 Windows VS19.

**Comment by ymber** [comment]
I can still reproduce the crash with these changes.
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-10657-g710bf90bcb
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x39) [0x557711f7a7d9]
    ./cataclysm-tiles(+0x180df6a) [0x557711f58f6a]
    ./cataclysm-tiles(+0x180dd08) [0x557711f58d08]
    /usr/lib/libc.so.6(+0x3bfb0) [0x7f21ef906fb0]
    ./cataclysm-tiles(_ZNKSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE16_M_get_use_countEv+0) [0x557711c3d740]
    ./cataclysm-tiles(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE23_M_add_ref_lock_nothrowEv+0x9) [0x557711c3d719]
    ./cataclysm-tiles(_ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC2ERKSt12__weak_countILS1_2EESt9nothrow_t+0x14) [0x557711c3d6e4]
    ./cataclysm-tiles(_ZNSt12__shared_ptrI4itemLN9__gnu_cxx12_Lock_policyE2EEC2ERKSt10__weak_ptrIS0_LS2_2EESt9nothrow_t+0x1b) [0x557711c3d6ab]
    ./cataclysm-tiles(_ZNKSt8weak_ptrI4itemE4lockEv+0x9) [0x557711c3d649]
    ./cataclysm-tiles(_ZNK14safe_referenceI4itemE3getEv+0x23) [0x557711c3d603]
    ./cataclysm-tiles(_ZNK13item_locationeqERKS_+0x27) [0x5577122e3c77]
    ./cataclysm-tiles(_ZNSt7__equalILb0EE5equalIPK13item_locationS4_EEbT_S5_T0_+0x2b) [0x5577122077cb]
    ./cataclysm-tiles(_ZN9__gnu_cxx5__ops16_Iter_equals_valIK15inventory_entryEclINS_17__normal_iteratorIPS2_St6vectorIS2_SaIS2_EEEEEEbT_+0x2d) [0x55771220a3dd]
    ./cataclysm-tiles(_ZSt9__find_ifIN9__gnu_cxx17__normal_iteratorIP15inventory_entrySt6vectorIS2_SaIS2_EEEENS0_5__ops16_Iter_equals_valIKS2_EEET_SC_SC_T0_St26random_access_iterator_tag+0x145) [0x55771220a325]
    ./cataclysm-tiles(_ZSt9__find_ifIN9__gnu_cxx17__normal_iteratorIP15inventory_entrySt6vectorIS2_SaIS2_EEEENS0_5__ops16_Iter_equals_valIKS2_EEET_SC_SC_T0_+0x3a) [0x55771220a1ba]
    ./cataclysm-tiles(_ZN16selection_column9on_changeERK15inventory_entry+0x63) [0x5577121f5a93]
    ./cataclysm-tiles(_ZN18inventory_selector9on_changeERK15inventory_entry+0x74) [0x5577121faa94]
    ./cataclysm-tiles(_ZN26inventory_compare_selector12toggle_entryEP15inventory_entry+0xa7) [0x5577121fb8c7]
    ./cataclysm-tiles(_ZN26inventory_compare_selector7executeEv+0x2d1) [0x5577121fb731]
    ./cataclysm-tiles(_ZN10game_menus3inv7compareER6playerRKN4cata8optionalI8tripointEE+0x46d) [0x55771213ef2d]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:620
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    …/src/crash.cpp:284
    ??
    ??:0
    std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_get_use_count() const
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/shared_ptr_base.h:203
    std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_lock_nothrow()
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/shared_ptr_base.h:287
    __shared_count
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/shared_ptr_base.h:911
    __shared_ptr
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/shared_ptr_base.h:1357
    std::weak_ptr<item>::lock() const
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/shared_ptr.h:595
    safe_reference<item>::get() const
    …/src/safe_reference.h:30
    item_location::operator==(item_location const&) const
    …/src/item_location.cpp:497
    bool std::__equal<false>::equal<item_location const*, item_location const*>(item_location const*, item_location const*, item_location const*)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/stl_algobase.h:820
    bool __gnu_cxx::__ops::_Iter_equals_val<inventory_entry const>::operator()<__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > > >(__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/predefined_ops.h:241
    __gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > > std::__find_if<__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__ops::_Iter_equals_val<inventory_entry const> >(__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__ops::_Iter_equals_val<inventory_entry const>, std::random_access_iterator_tag)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/stl_algo.h:148
    __gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > > std::__find_if<__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__ops::_Iter_equals_val<inventory_entry const> >(__gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__normal_iterator<inventory_entry*, std::vector<inventory_entry, std::allocator<inventory_entry> > >, __gnu_cxx::__ops::_Iter_equals_val<inventory_entry const>)
    ??:?
    selection_column::on_change(inventory_entry const&)
    …/src/inventory_ui.cpp:994
    inventory_selector::on_change(inventory_entry const&)
    …/src/inventory_ui.cpp:1692
    inventory_compare_selector::toggle_entry(inventory_entry*)
    …/src/inventory_ui.cpp:1928
    inventory_compare_selector::execute()
    ??:?
    game_menus::inv::compare(player&, cata::optional<tripoint> const&)
    …/src/game_inventory.cpp:1383
```
Built with `make -j6 CLANG=1 CCACHE=1 RUNTESTS=0 TILES=1 SOUND=0 LOCALIZE=0`. I'm on Arch Linux.

**Comment by jbytheway** [comment]
I've posted an alternate attempted fix at #36606.  Testing by others welcome.

**Comment by ZhilkinSerg** [comment]
Obsoleted by #36606

**Pull request closed without merging**
