### PR TITLE
Support Mac arm64

### PR DESCRIPTION
**Pull request by CzBiX**
#### Summary
Build "Support Mac arm64 build"

#### Purpose of change

Get native arm64 build for mac.

#### Describe the solution

Use framework for mac to avoid cross compile.

#### Additional context

reopen #63702 to fix typo

### CODE REVIEW

**Comment by Maleclypse** [comment]
Is this fix covered by or in addition to #63821?

**Comment by CzBiX** [comment]
@Maleclypse seems the same, but with clean commit messages.

**Comment by LyleSY** [comment]
Isn't this missing the script and all of the other good things in the original that were reverted?

**Comment by kevingranade** [comment]
You need to cherry pick the original commits or revert the revert.

**Pull request closed without merging**
