### PR TITLE
Correcting dispersion  of Rivtech 8x40mm caseless ammo and guns

### PR DESCRIPTION
**Pull request by Firestorm01X2**
#### Summary

SUMMARY: Content "Setting adequate dispersion for Rivtech 8x40mm caseless ammo"

#### Purpose of change

There is few reasons to change.
1) For some reason Rivtech guns using reverse scheme of relationship between base gun dispersion and ammo dispersion

Other guns in the game have most dispersion (>80%) on gun itself and much less on ammo (<20%). Rivtech 8x40mm guns uses reverse scheme: 60-80% disperson on ammo and 20-40% on gun.  It hurts consistency and potentially make Rivtech rifles harder to balance.

Example:
Assault rifle:
Steyr AUG: 140 (base disp.)+30(.223 disp.)=170
RM51 assault rifle: 90(base disp.)+ 75 (8x40mm caseless disp) = 165

Battle rifle:
FN SCAR-H: 150(base disp.)+15(.308 Winchester disp.)=165
RM88 battle rifle: 50 (base) + 75 (8x40mm caseless disp)=125

LMG:
M249: 200(base disp.) 30 (.223 disp)= 230
RM614 LMG: 140 (base) + 75 (8x40mm caseless disp)= 215

HMG:
M240: 200 (base disp) +15(.308 Winchester disp.)= 215
RM298 HMG: 180(base disp.) + 75 (8x40mm caseless disp)= 255

Sniper rifle
M24: 85 (base disp.) +15(.308 Winchester disp.) = 100
RM11B scout rifle: 10(base disp.) + 75 (8x40mm caseless disp) =85

2) It is unrealistic and unlogical.
Rivtech is futuristic gun manufacturer.
Rivtech based its wepons on unique caseless ammunition. It is expected that Rivtech rifle ammo has superior or at least comparable accuracy stats to modern rifle ammuniton.

For example:
5.56 NATO M855A1 has disperion of 20.
.223 Remington has disperion of 30
7.62x39mm 57-N-231 has disperion of 35
9x19mm JHP has dispersion of 60
8x40mm caseless has dispersion of 75

But in fact 8x40mm ammo has worse dispersion than pistom 9x19. That is questinable at best.

3) There is change that this dsipersion is long forgotten leagcy oversight. 

#### Describe alternatives you've considered

# Plan:
- [x] Determine ingame and IRL analog of 8x40mm caseless ammo. It is likely between .203 and .308
- [x] Set adequate dispersion stats to 8x40mm ammo. **Lets set to 20.**
- [x] Decide what to do with removed dispersion: **move it to guns**/partially move it to guns/ do not move it to guns
- [x] Make individual gun dispersion correction if needed.

#### Additional context

So firtst. What is 8x40mm caseless. Caseless ammo exists IRL:
https://en.wikipedia.org/wiki/List_of_caseless_firearms
https://en.wikipedia.org/wiki/Caseless_ammunition

Caseless ammo has advantages:
* increases gun reliability
* Reduced ammo weight
* Increases gun firerate

Caseless ammo has  also disadvatages:
*  Casesless ammo heat sensisive
* Ammo itself are quite fragile
* Sealing problem

We can pretend that Rivtech somehow solve caseles ammo issues in their guns.
Overall there is no strsight indication that caseless ammo has worse or superior accuracy in comparsion to normal ammo. So we can compare it with usual ammo.

But what about 8x40mm dispersion? To get it we must at least get IRL analog of 8x40mm ammo.
First let's try to determine caliber. It not quite possible because despite of marking 8x40mm ammo likely has cartridge around bullet. That 8mm may be cartridnge diameter but not bullet itself:
https://www.hkpro.com/index.php?option=com_content&view=article&id=23:the-g11-caseless-military-rifle

https://en.wikipedia.org/wiki/Heckler_%26_Koch_G11
https://en.wikipedia.org/wiki/5.56%C3%9745mm_NATO
https://en.wikipedia.org/wiki/9%C3%9719mm_Parabellum

Likely  8x40mm size is between 5.56 (.223) and 7.62 (.308). Someone also noted that it has quite short length in comparsion to rifle ammo sot it has less room for poweder. Probably it uses some kind of very special powder to get a punch:
https://2ch.hk/vg/res/28140975.html#28199492.

So I assume that 8x40mm ammo dispersion should be around 23 (between .223 and .308 dispersion). Lets round it to 20 because it is semi futuristic and for convinience.

Also  IRL 8x40mm has Nylon Wall Plugs:
https://www.clasohlson.com/uk/8x40-mm-Nylon-Wall-Plugs/Pr409214003
:)

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
So overall I recommend to use dispersion 20 to 8x40mm instead of 75.

**Comment by Vasyan2006** [comment]
Ballistic performances of caseless 4.73x33 HK G11 is presented here:
https://www.remtek.com/arms/hk/mil/g11/caseless.htm
Compare to 5.56x45 rifles it has slightly better performanse on short range below 300m (benefits of smaller caliber) and same results on longer.
Main reason to use caseless ammo is to increase rate of fire and magazine capacity. It will increase hit probability in situations where proper aiming is not possible.
Also I suggest to rename 8x40mm to 5x40mm, because 8x40 is a common caliber for heavy and slow subsonic bullets, like 7.62x35 or 9x39.

**Comment by Firestorm01X2** [comment]
There is 5x50 ammo already https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/ammo/5x50.json

It may confuse players. Actualy name of RIvtech ammo confusing already. It make if worse.

**Comment by Firestorm01X2** [comment]
I've wandered around over json once more. I am almost sure that simply reducing 8x40 dispersion is bad idea. I definetely should more it to guns. There are another Rivtech guns and not all of that extremely accurate.
But I should definetely increse Rivtech HMG accuracy. It is lower than conventional HMG accuracy for some reason,

**Comment by Firestorm01X2** [comment]
After correction:
Assault rifle:
Steyr AUG: 140 (base disp.)+30(.223 disp.)=170
RM51 assault rifle: 120 (was 145) (base disp.)+ 20 (8x40mm caseless disp) = 140

Battle rifle:
FN SCAR-H: 150(base disp.)+15(.308 Winchester disp.)=165
RM88 battle rifle: 100 (was 105) (base) + 20 (8x40mm caseless disp)=120

LMG:
M249: 200(base disp.) 30 (.223 disp)= 230
RM614 LMG:  180 (was 195) (base) + 20 (8x40mm caseless disp)= 215

HMG:
M240: 200 (base disp) +15(.308 Winchester disp.)= 215
RM298 HMG: 165 (was 235) (base disp.) + 20 (8x40mm caseless disp)= 185

Sniper rifle
M24: 85 (base disp.) +15(.308 Winchester disp.) = 100
RM11B scout rifle: 65 (ok as it is) (base disp.) + 20 (8x40mm caseless disp) =85

**Comment by Firestorm01X2** [comment]
I think that it is done.

**Comment by kevingranade** [comment]
As I said in the previous issue, whether there's more dispersion on the ammo or the gun is irrelevant, youre just shuffling numbers around with no change.

**Comment by Firestorm01X2** [comment]
But here is was change to gun dispersion
 You did not notice it?

**Comment by Firestorm01X2** [comment]
Also can we get some cracking kind of discussion before closing my PRs?

**Pull request closed without merging**
