### PR TITLE
Rewrites #22756 (Firearms Overhaul) as json-only mod

### PR DESCRIPTION
**Pull request by fungusakafungus**
using a script from
https://gist.github.com/fungusakafungus/eb2bdf39da73c03dcb2325b3350ff24b#file-gen-mod-from-diff-sh

like this:

```
git checkout kasanryukin/master
git reset c0e3b6f # fork point

./gen-mod-from-diff.sh PR22756
```

Not endorsing the actual content of #22756, I have no idea about firearms balancing. Just providing it in a more palatable (easier to use? I hope) form. There's also a zip file here: https://github.com/fungusakafungus/Cataclysm-DDA/releases/tag/PR22756-v1.0

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
As far as I see this: https://github.com/CleverRaven/Cataclysm-DDA/pull/22756 just changes maximmum ranges of guns. It may be usefull but if it is used alone - it just limit current firerarms even more bacus of distance limitations.

**Comment by Firestorm01X2** [comment]
I mean it will not help with current situation with guns at all.

**Comment by fungusakafungus** [comment]
My idea was that if anyone wants to use that Firearms PR they can just install and turn on the mod and see for themselves if that's their cup of tea or not. There's probably a better place for a mod, feel free to close.

**Comment by kevingranade** [comment]
I appreciate your effort, but the PR doesn't actually fix what it sets out to, which is one if the reasons it hasn't been merged.
https://github.com/CleverRaven/Cataclysm-DDA/issues/22753 discusses what the balance *should* be, but additionally setting the range on guns doesn't set effective range, just a range cap.

**Comment by pipehat** [comment]
For what it's worth, lost a game the other day because I couldn't drop a shocker with 8 point-blank shots with a remington. I don't care much about realistic dispersion. I do care about it being satisfying to shotty a zombie in a zombie apocalypse game. I recommend ratcheting down the 'realism' concerns and make guns fun and useful - even if imperfect.

**Pull request closed without merging**
