### PR TITLE
Aftershock Exoplanet: Update weather definitions

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
 None

#### Purpose of change

0.F-dev branch required different weather definitions than the master branch, which caused issues after the original Exoplanet region was merged.

This fixes the conflicts within 0.F dev.

#### Describe the solution

Update the weather definition in the mod

#### Testing

Game loads

### CODE REVIEW

**Comment by actual-nh** [comment]
Are you meaning to target this at 0.F-dev, not master?

**Comment by John-Candlebury** [comment]
> 
> 
> Are you meaning to target this at 0.F-dev, not master?

Whoops forgot to change the targeted branch at PR creation. That said I'm pretty sure devs with merge rights can change that without problems. If not tell me and I'll redo it.

**Comment by jbytheway** [comment]
You don't need to re-do the PR, you can edit this one.

**Comment by actual-nh** [comment]
> You don't need to re-do the PR, you can edit this one to target `0.F-dev`.

Good point. It would make it easier to see what's happening and what any remaining problems are (see the issue report I just opened).

**Comment by Maleclypse** [comment]
I flipped it to 0.F -dev to see if it would automatically redo tests and it doesn’t look like it is from this window.

**Comment by actual-nh** [comment]
Well, it looks like it needs a force-push or similar anyway, from various things it's still doing to files in data/json.

**Comment by John-Candlebury** [comment]
Think its done now

**Pull request merged**
