### PR TITLE
Enable ClangBuildAnalyzer on PRs to 0.F-dev

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

#### Purpose of change
I want to observe if there is any impact on compile time in pull requests such as #48571. But Clang Build Analyzer workflow only triggers on pull requests to `master` branch.

#### Describe the solution
Add `0.F-dev` to `CBA.yml`.

### CODE REVIEW

**Comment by jbytheway** [comment]
Thanks.  I was wondering why CBA wasn't running on such PRs.

**Comment by jbytheway** [comment]
You probably want to add `0.F-dev` to the pull request branches list in the same file?

**Comment by actual-nh** [comment]
> Thanks. I was wondering why CBA wasn't running on such PRs.

Because I hadn't included it in my earlier PRs to get CI running on 0.F-dev (IIRC, at the time there were some problems with everything being very slow).

**Comment by jbytheway** [comment]
> Hmm... still doesn't seem to be running?

Perhaps because you didn't edit anything matching the patterns under `paths:`?

**Comment by BrettDong** [comment]
There has to be some C++ source code changes to trigger Clang Build Analyzer.

**Comment by actual-nh** [comment]
> There has to be some C++ source code changes to trigger Clang Build Analyzer.

Are you planning on doing a test one to check if this PR is functioning?

**Pull request merged**
