### PR TITLE
Allow custom message from roll_remainder

### LINKED ISSUE #64025: Show custom messages when using u_roll_remainder
### Is your feature request related to a problem? Please describe.

I have a list of mutations that I'd like the player to receive as one randomly chosen from said list.
I've tried using u_roll_remainder but it doesn't display any feedback on what you get.

### Solution you would like.

Add a "message" field to u_roll_remainder that allows displaying a custom message with the mutation name.
Something like `"message":"you get <name>"`

### Describe alternatives you have considered.

So far I've been using "weighted_list_eocs" to choose a random eoc that gives a mutation.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #64025
Allow better messaging.

#### Testing
Used this json
```
{
    "type": "effect_on_condition",
    "id": "TEST",
    "effect": [ 
      { "u_roll_remainder": [ "FASTREADER", "TOUGH_FEET" ], "type": "mutation", "message":"You gain mutation %s" },
      { "u_roll_remainder": [ "bio_armor_arms", "bio_armor_eyes" ], "type": "bionic", "message":"You gain bionic %s" },
      { "u_roll_remainder": [ "AEA_BLOOD", "AEA_HEAL" ], "type": "spell", "message":"You gain spell %s" },
      { "u_roll_remainder": [ "40x46mm_hornets_nest_22lr", "reloaded_45_super" ], "type": "recipe", "message":"You gain recipe %s" }
   ]
  },
```

### CODE REVIEW

**Comment by Maleclypse** [comment]
Can you allow it to set a null message once all roll_remainder's have been selected?

**Comment by Ramza13** [comment]
> Can you allow it to set a null message once all roll_remainder's have been selected?

Yup that was already possible using false_eocs.

**Comment by Maleclypse** [comment]
> > Can you allow it to set a null message once all roll_remainder's have been selected?
> 
> Yup that was already possible using false_eocs.



> > Can you allow it to set a null message once all roll_remainder's have been selected?
> 
> Yup that was already possible using false_eocs.

```
{
    "type": "effect_on_condition",
    "id": "EOC_vampire_virus_escalation",
    "recurrence": [ "48 hours", "72 hours 15 minutes" ],
    "condition": { "and": [ { "u_has_effect": "vampire_virus" }, { "not": { "u_has_effect": "blood_treatment" } } ] },
    "deactivate_condition": { "not": { "u_has_effect": "vampire_virus" } },
    "effect": {
      "run_eocs": [
        {
          "id": "EOC_VAMPVIRUS",
          "condition": {
            "and": [
              { "u_has_effect": "vampire_virus", "intensity": 1 },
              { "compare_int": [ { "u_val": "effect_intensity", "effect": "vampire_virus" }, "=", { "const": 1 } ] }
            ]
          },
          "effect": {
            "run_eocs": {
              "id": "eoc_vampvirus_1_trait",
              "condition": { "u_has_trait": "VAMPIRE" },
              "effect": [
                { "u_roll_remainder": [ "EYEGLEAM", "STAMINAFORBLOOD" ], "type": "mutation", "true_eocs": [ "EOC_VAMPVIRUS1" ] },
                { "u_message": "Suddenly you feel your heart pounding and you realize a new ability." }
              ],
              "false_effect": [
                { "u_add_trait": "VAMPIRE" },
                {
                  "u_message": "You suddenly understand that drinking someones blood will make you feel better than you've ever felt before in your life."
                }
              ]
            }
          }
        },
```
Ok so I'm having the false effect add the trait that enables the roll_remainder situation.  What would I do differently here, keeping in mind this is part of a larger EOC chain and I'd be repeating that pattern several more stages?

**Comment by Ramza13** [comment]
> > > Can you allow it to set a null message once all roll_remainder's have been selected?
> > 
> > 
> > Yup that was already possible using false_eocs.
> 
> > > Can you allow it to set a null message once all roll_remainder's have been selected?
> > 
> > 
> > Yup that was already possible using false_eocs.
> 
> ```
> {
>     "type": "effect_on_condition",
>     "id": "EOC_vampire_virus_escalation",
>     "recurrence": [ "48 hours", "72 hours 15 minutes" ],
>     "condition": { "and": [ { "u_has_effect": "vampire_virus" }, { "not": { "u_has_effect": "blood_treatment" } } ] },
>     "deactivate_condition": { "not": { "u_has_effect": "vampire_virus" } },
>     "effect": {
>       "run_eocs": [
>         {
>           "id": "EOC_VAMPVIRUS",
>           "condition": {
>             "and": [
>               { "u_has_effect": "vampire_virus", "intensity": 1 },
>               { "compare_int": [ { "u_val": "effect_intensity", "effect": "vampire_virus" }, "=", { "const": 1 } ] }
>             ]
>           },
>           "effect": {
>             "run_eocs": {
>               "id": "eoc_vampvirus_1_trait",
>               "condition": { "u_has_trait": "VAMPIRE" },
>               "effect": [
>                 { "u_roll_remainder": [ "EYEGLEAM", "STAMINAFORBLOOD" ], "type": "mutation", "true_eocs": [ "EOC_VAMPVIRUS1" ] },
>                 { "u_message": "Suddenly you feel your heart pounding and you realize a new ability." }
>               ],
>               "false_effect": [
>                 { "u_add_trait": "VAMPIRE" },
>                 {
>                   "u_message": "You suddenly understand that drinking someones blood will make you feel better than you've ever felt before in your life."
>                 }
>               ]
>             }
>           }
>         },
> ```
> 
> Ok so I'm having the false effect add the trait that enables the roll_remainder situation. What would I do differently here, keeping in mind this is part of a larger EOC chain and I'd be repeating that pattern several more stages?

False effect is not the same as false_eocs.  What you would do is set the false_eocs with an inline eoc that just sets a message.

**Pull request merged**
