### PR TITLE
Add shields

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Adds various types of shields to the game, including round, tower, kite, and heater shields; made of leather, metal, and wood. A riot shield is also added.

#### Purpose of change
The use of shields in melee combat is as old as time, and they are advantageous to survivors looking to protect themselves from undead. Logically, those lacking ranged weapons may create shields along with other forms of armor to protect themselves in combat, and the player could do the same with the correct skills. Additionally, the inclusion of shields can provide some realism; historic varieties being found in museums and mansions. Police officers also lack riot shields at the moment, which they likely employed during initial, pre-cataclysm riot control.

#### Describe the solution
Currently, five varieties of shields exist; with varying coverage depending upon their design (all cover the hands and arms).
Tower shields are cumbersome and heavy, but highly protective for 90% of the body. 
Unnamed "run-of-the-mill" varieties have nothing special.
Kite shields cover a portion of the legs.
Round shields are less protective, but maneuverable and light.
Heater shields cover a portion of the torso.
Additionally, all types come in three materials; wood, leather, and metal. Each has it's material-dependent advantages and drawbacks.
The riot shield is a unique case, as it is lightweight with the coverage of the tower shield, but made of plastic. 

#### Describe alternatives you've considered
If unbalanced, the encumbrance values may be increased, or protection decreased as needed.

#### Testing

I loaded a new game, spawned in shields, and used them in combat. No errors or problems were detected, and they function as intended. I spawned in a mansion, and shields were present inside.

#### Additional context
I plan upon adding new varieties of shields; such as the Mycenean "figure-eight" design, or the targe. I also plan upon adding a greater variety of materials shields could be crafted from.

### CODE REVIEW

**Comment by Venera3** [comment]
It's established that shields will have to wait until multiwield (as in, tracking what item is held in which hand / tentacle / noodly appendage) becomes a thing - that's not a million miles off, but it has no ETA. Until then the drawbacks don't really represent what you'd deal with from strapping a shield to your arm, and you have a huge gap of functionality between wearing and wielding them.

**Comment by Zireael07** [comment]
Wouldn't they fit better in the Medieval mod?

**Comment by kurtisvetter** [comment]
To add to what @Venera3 has said, it might make sense to differentiate between shields that are wielded in one's hand, like a [buckler](https://en.wikipedia.org/wiki/Buckler) or the tower, kite, and heater shields in this PR vs shields that are strapped to one's arm, and which mostly only protect the arm to which it is strapped at the cost of relatively high encumbrance. Until multiwield is implemented, perhaps this PR could be limited in scope to shields that are strapped, not wielded?

By the way, @MNG-cataclysm you're going to want to run the JSON style validator after making edits to JSON files (see [JSON_STYLE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md)).

**Comment by MNG-cataclysm** [comment]
@kurtisvetter 
Would it make sense for the shields in this PR to strap to the arm?

**Comment by kurtisvetter** [comment]
> Would it make sense for the shields in this PR to strap to the arm? The shields now strap to the arm, by the way.

I think it would make more sense for the shields to be 'strapped' (as in "BELTED"); right now they are in the normal layer. And I think it makes less sense for the larger shields to protect the torso and legs, since they aren't actually attached to those limbs. The 'shield' ("WBLOCK_3") ability will indirectly reduce damage to those body parts anyways. But then one would be incentivized to always use the smallest/least encumbering shield, since they all give the 'shield' ability, so I'm not entirely sure about what should be done.

**Comment by Maddremor** [comment]
I'm no authority here, but I can confidently say that the "shields as clothing/armor" thing is not going to work.

**Comment by kevingranade** [comment]
Even just limiting shields to strapped varieties doesn't work, because the fundamental limitation that we can not currently represent is that your arm is not just encumbered but not available for ordinary use at all.  It's a pretty big deal that using a shield restricts you to wielding a weapon in just one hand.

The solution I *want* is to handle dominant and off-dominant hands explicitly and have nuanced handling of the impact of having one or two hands available for wielding a weapon be reflected.

What would be acceptable for a shorter term fix would be a flag that says when "Wearing" a shield it occupies one of your arms, and we can work that into the various pieces of code handling how good you are at handling a weapon, whether wielding a particular weapon is valid, etc.

**Comment by MNG-cataclysm** [comment]
> What would be acceptable for a shorter term fix would be a flag that says when "Wearing" a shield it occupies one of your arms, and we can work that into the various pieces of code handling how good you are at handling a weapon, whether wielding a particular weapon is valid, etc.

What if I used extremely high encumbrance values to mimic this? 80-100 might work.

**Comment by MNG-cataclysm** [comment]
> And I think it makes less sense for the larger shields to protect the torso and legs, since they aren't actually attached to those limbs. The 'shield' ("WBLOCK_3") ability will indirectly reduce damage to those body parts anyways. But then one would be incentivized to always use the smallest/least encumbering shield, since they all give the 'shield' ability, so I'm not entirely sure about what should be done.

I added additional protection values to these shields to differentiate them from one another, and help reflect upon the properties of their design.

**Pull request closed without merging**
