### PR TITLE
Weakpoint Sets

### LINKED ISSUE #52894: Make it possible to define weakpoints in an external json object
# Is your feature request related to a problem? Please describe.

My PR #52084 is currently delayed mostly by me being very low on time and brainpower, but also by my discovery that the beautiful weakpoints system @Joshua-Chin and I designed needs some way to be more modular, or it represents probably tens of thousands of lines of exhausting JSON churn, most of which is repetitive copy-and-pasting. I initially started to address this in #52279, but resolving it with existing copy-from has its own flaws, not the least of which is that it is *also* a lot of JSON churn, and makes zombie entries harder to read and process.

# Describe the solution you'd like

During implementation we discussed the option of allowing weakpoints to be specified in a separate JSON object and I thought it wouldn't be necessary. I WAS WRONG.

I would like the `"weakpoints"` attribute to accept the same things it currently does, allowing inline specification of weakpoints. However I would also like to be able to call one or more separate `weakpoints_set` JSON objects that can be defined externally.

I'm not sure the best way to do this but I'd suggest maybe doing it through a separate JSON attribute in the monster entry. So, `weakpoints` as currently implemented would not change. Add a new optional attribute `weakpoint_sets`. This accepts a list. Items in the list are loaded in the order they are written, so:

`"weakpoint_sets": [ "wps_humanoid", "wps_zombie_headshot", "wps_cop_armour" ]`
- first load a set of weakpoints standard to all humanoids.  Then load weakpoints standard to zombies that can get hit with an unarmoured headshot.  Then load weakpoints related to cop armour specifically.
- If any weakpoints listed in `wps_zombie_headshot` are also listed in `wps_cop_armour`, override the zombie ones with the cop_armour ones because it is listed later.
- Weakpoints specified inline in the monster entry should override any with the same name/id in the inherited sets.

`weakpoint_set` objects should be a JSON object that uses the same syntax as the current `weakpoints` entry in every way.

A weakpoint set would look like this:
```json
{
  "type": "weakpoint_set",
  "id": "wps_zombie_headshot",
  "weakpoints": [
    {
      "name": "the head",
      "coverage": 5,
      "crit_mult": { "all": 1.1 },
      "armor_mult": { "physical": 0.75 },
      "difficulty": { "melee": 1, "ranged": 3 },
      "effects": [
        {
          "effect": "stunned",
          "duration": [ 1, 2 ],
          "chance": 5,
          "message": "The %s is stunned!",
          "damage_required": [ 1, 10 ]
        },
        {
          "effect": "stunned",
          "duration": [ 1, 2 ],
          "chance": 25,
          "message": "The %s is stunned!",
          "damage_required": [ 11, 100 ]
        }
      ]
    }
  ]
}
```

# Describe alternatives you've considered
I've tried two other ways, as linked above, and stalled out due to the massive churn required.

I initially thought we should integrate some copy-from functions, like `delete`, `proportional`, and `relative`, to the way these sets interact with each other. However, I have since realized that a better way to do it is just to keep each weakpoint set to a specific body part or other related collection of bits to hit, and then just combine the parts as needed. That removes pretty much all need for complex inheritance, at the cost of very slightly more complicated but easier-to-read monster entries.

# Additional context
I have marked this as p2 because full weakpoint implementation is pretty important for 0.G at this point, and I don't think I can complete it without this issue. This also makes it possible to add even more complex effects and things to individual weakpoints, something that was becoming prohibitive on zombies with a dozen weakpoints running at 100 lines each.

This structure also makes it much simpler to change weakpoints in mods. Rather than having to re-create every monster entry, you need only change the weakpoints entry itself and all the monsters will fall in line. I definitely need that for Dark Days of the Dead, otherwise I'll need to encode a way to change just the weakpoints in every zombie.

As a side note, I think overall we should be moving to a more modular set of monster entries like this, such as we already have for special attacks. Other monster data fields should be similarly exported to separate json objects, allowing mods to edit those objects with a cascading downstream effect on monsters, and later on, allowing monster mutations and evolution to work by adding or adjusting existing modules.

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

*Alternative summary: Infrastructure "Weakpoint sets - define groups of weakpoints outside of monster definitions"*

#### Purpose of change
Fixes #52894.
Allows weakpoint sets to be defined as a sequential list, with later sets overwriting matching weakpoints from earlier sets. This allows us to define common weakpoint sets that can be reused instead of lumping everything into the monster definition.

#### Describe the solution
Using Erk's example from the linked issue:
```json
{
  "type": "weakpoint_set",
  "id": "wps_zombie_headshot",
  "weakpoints": [
    {
      "name": "the head",
      "coverage": 5,
      "crit_mult": { "all": 1.1 },
      "armor_mult": { "physical": 0.75 },
      "difficulty": { "melee": 1, "ranged": 3 },
      "effects": [
        {
          "effect": "stunned",
          "duration": [ 1, 2 ],
          "chance": 5,
          "message": "The %s is stunned!",
          "damage_required": [ 1, 10 ]
        },
        {
          "effect": "stunned",
          "duration": [ 1, 2 ],
          "chance": 25,
          "message": "The %s is stunned!",
          "damage_required": [ 11, 100 ]
        }
      ]
    }
  ]
}
```

##### How it works
A `"weakpoint_set"` is a thin container for an array of weakpoints. The only unique fields for weakpoint sets are `"type"` and `"id"`. Weakpoint sets are used in monster type definitions using the `"weakpoint_sets"` field:
```json
{
  "id": "mon_zombie_cop",
  "type": "MONSTER",
  "name": { "str": "zombie cop" },
  "description": "A human body covered by a weather-beaten and badly damaged set of riot gear.",
  "bodytype": "human",
  ...
  "weakpoint_sets": [ "humanoid", "zombie_headshot", "riot_gear" ],
  "weakpoints": [
    {
      "id": "humanoid_leg",
      "name": "an unarmored part of the leg",
      "armor_mult": { "bullet": 0.5, "cut": 0.5, "stab": 0.25, "bash": 0.25 },
      "coverage": 8
    },
    ...
  ],
  ...
}
```

In this case, the weakpoint sets are applied in the following order:
1. The `"humanoid"` weakpoint set is used as the base.
2. The `"zombie_headshot"` weakpoint set overwrites any weakpoints from `"humanoid"` that **match the same id**.
3. The `"riot_gear"` weakpoint set overwrites matching weakpoints from the previous sets.
4. The inline `"weakpoints"` definition overwrites any matching weakpoints from `"weakpoint_sets"`.

Note that 2 weakpoints that have the same id are considered to match, so it's important to define this value if you want that weakpoint to overwrite any previously defined weakpoint with the same id.

<hr>

Because of the unusual way this works, the implementation is a little different than standard inheritance (In fact, it's much simpler). I've also made an effort to preserve `"extend"` and `"delete"` functionality, but that should still be tested.

What has changed:
- New JSON type `"weakpoint_set"`.
- New field `"weakpoint_sets"` in `MONSTER` type, which is an array of strings referring to the id of a weakpoint_set.
- The `weakpoints` struct has been converted into a type container using a generic factory.

What has NOT changed:
- A monster's weakpoints are stored in the `mtype::weakpoints.weakpoint_list` vector.
- Weakpoints can still be defined inline in the monster type in the `"weakpoints"` array.

<hr>

#### Describe alternatives you've considered
I considered converting individual weakpoints to JSON types as well, but I feel that it would create some unnecessary churn. I think that having sets of weakpoints should be enough to accomplish most weakpoint definitions.

#### Testing
Added unit tests to verify the order that sets are applied, as well as checking that hits and damage match the applied weakpoints.

#### Additional context
TODO:
- [x] Convert `weakpoints` struct to type container
- [x] Rewrite weakpoint loading in `mtype`
- [x] Documentation
- [x] Unit testing

### CODE REVIEW

**Comment by dseguin** [comment]
@I-am-Erk Let me know if anything about this is wrong.

**Comment by I-am-Erk** [comment]
This looks exactly like what I want, thank you.

**Comment by nexusmrsep** [comment]
The category for this for the summary should in fact be 'infrastructure', as it is significant enough to be included imho.

**Comment by dseguin** [comment]
> The category for this for the summary should in fact be 'infrastructure', as it is significant enough to be included imho.

Done :+1:

**Pull request merged**
