### PR TITLE
fix: don't run styling workflows always

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
Another go at fixing the problem presented here #56536 <- this would work if the workflows were skipped, but they are almost never skipped, they run always, just don't run them always ez

TL;DR from the pr mentioned above:
The styling workflows are currently running on any change, we do not
need that, also this causes every pull request to be labeled as astyled
and json-styled, very noisy

Solution:
It's because of the removal of the high level "run workflow on these
path changes", I restored that functionality, not sure if that was
intended but with these changes, the "styled" labeling seems more
pleasing

#### Testing
https://github.com/casswedson/Cataclysm-DDA/pull/16 Here, the workflow files are modified with this patch, the other changes are, so I can run the style labeler on my repo and changing json and cpp files

The good part:
Notice the last commit and consecutive bot action, the commit modifies some cpp file and the bot labels it as cpp, astyle validation says it's good and it gets an astyled label

#### Additional context
~~How come it's so hard to have a pr to this repo as a working demo~~ never mind I told the check to also run on modifications to the workflow file itself ofc this triggers the workflow

### CODE REVIEW

**Comment by PatrikLundell** [comment]
While it's noisy to add Json-styled/astyled every time, if I was to look for things to approve, I wouldn't bother with any entries that haven't passed those steps. You can't really use negative labels like json-style-failed, as that wouldn't be applied until the test has already been performed, and so would not mark anything as dirty while it's still untested.

Now, if testing actually worked, and didn't fail due to broken tests and broken test procedures 90% of the time a single "all tests passed" label should be the thing to work. Until then, the cluttering json/astyle crutches will probably have to remain.

**Comment by kevingranade** [comment]
IIRC this breaks the "these must pass to allow the PR to be merged" check.
Now that I look again, I'm not clear why this is a problem in the first place?

**Comment by casswedson** [comment]
I still see the "Required" besides the checks in this pr

What I consider the problem here is that pull request trigger style checks, these may not concert them, like they didn't change any c++ files why bother running astyle on them or json style or whatever else, you end up checking the state of master and using that to label them, to me that does not feel very pleasing or very much intended, it's a bit of an overkill to have this running so often, if we can save some _precious_ seconds on the runners we should

**Comment by PatrikLundell** [comment]
If logic to check that no JSON is changed is fast, that could be used to attach the json-styled flag without actually running the test. The same can be done for astyle, under the same assumption. That assumes violating PRs haven't been accepted into Master, but even if they have, the perpetrators ought to fix the errors, no PR authors who didn't have anything to with it.

However, if you REALLY wanted to cool down those scorching hot testing computers you should concentrate on making the tests actually work and only fail when there's something that's actually wrong. That would also relieve PR authors from the constant need to retrigger testing in the hope of rolling a natural 20 in the test RNG casino.

**Comment by kevingranade** [comment]
> I still see the "Required" besides the checks in this pr

Of course you did, the test ran because you edited the .yml file.  If theyvwon't trigger, the test will be "required" but not run and rherefore not pass.

> What I consider the problem here is that pull request trigger style checks, these may not concert them, like they didn't change any c++ files why bother running astyle on them or json style or whatever else,

As above, it's a mechanical limitation of the github actions workflows.

**Pull request closed without merging**
