### PR TITLE
Reeneable mapgen test

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
None

#### Purpose of change
Restoring the mapgen test that was disabled in #53506.

As evidence of the usefulness of this test, it allowed me to find many issues, such as those fixed in #53189, #53698, #53840, #53842, #53843, #53877, #53878, #53879, and #53880.

#### Describe the solution
Re-enable the test, and also add a new sanity check whereby furniture placed on open air flags a `debugmsg`.  This helps catch a lot of strange mapgen issues.

#### Describe alternatives you've considered
This test will almost certainly have a long tail of issues it finds that need resolving.  I'm opening as a draft while I stress-test it some more locally to flush out anything common.

~One problem is that when you get the message about misplaced furniture it's usually impossible to track down the cause without the aid of a debugger.  So that's unhelpful for errors in CI.  I'd like to improve this, but I'm not sure how.  I considered two options:~
* ~Pass a context string to the `furn_set` function which allows it to report that context in its error message.  This is probably a bad idea because it's a performance cost paid by every caller that's only useful in an error case.~
* ~Have `furn_set` return an indication of success.  I'm leaning towards this option, but it requires updating all the call sites (or at least, the most commonly-error-related ones) to check that return value, which is annoying.~

~I'd welcome any other ideas.~

Better error reporting now implemented.  See comment below.

#### Testing
It is itself the test!

#### Additional context

### CODE REVIEW

**Comment by jbytheway** [comment]
I went ahead and implemented better error reporting.  Now an example error would look something like this:
```
ERROR : src/map.cpp:1406 [bool map::furn_set(const tripoint&, const furn_id&, bool)] Setting furniture f_vent_pipe at (2,21,2) where terrain is t_open_air (which is_open_air)
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture
ERROR : src/mapgen.cpp:2456 [virtual void jmapgen_furniture::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const] Problem setting furniture in nested mapgen roof_2x2_infrastructure in mapgen megastore_0_2_roof
```

Which should be sufficient for people without a debugger to figure out what happened.

I think this is enough to make this mergable.  There are certainly still lots of low-probability error cases.  But I'm only seeing one maybe every tenth time I run the tests, so hopefully it's not too bad.  And now with the better error reporting hopefully other folks can help clean up more after the merge.  So, I'm marking this ready for review.

I'll keep running the tests and fixing stuff they find until I get bored or it takes too long to find new problems.

**Comment by jbytheway** [comment]
One more thing...  I thought about adding a load-time check for nests that go out of bounds.  Unfortunately we can't really do that so long as we force nests to be square.  Support for non-square nests is something I've been wanting, though, so maybe I'll look into that.

**Comment by jbytheway** [comment]
Pushed a few more fixes and a new sanity check to mirror the one already present: this looks for removing terrain out from under furniture.

**Comment by jbytheway** [comment]
I did find a way to write an automated check for (most) out-of-bounds nest placements.  That found a whole bunch of issues which I've now added fixes for to this PR (including one which was the cause of the [last CI check failure](https://github.com/CleverRaven/Cataclysm-DDA/runs/4683133140?check_suite_focus=true), as at 81a61c3.

I won't add the check itself to this PR, because there's one problem it found I don't yet know how to fix, and it will also find problems in the mods, which I have yet to tackle (but are not relevant for the exhaustive mapgen test which is the primary subject of this PR).

**Comment by kevingranade** [comment]
Good "test" of the placement errors, I was able to track down the apparent source of the error in the goblin camp very quickly.

**Comment by jbytheway** [comment]
Thanks for fixing that; I hadn't got around to testing Magiclysm locally.

**Pull request merged**
