### PR TITLE
[Sky Island] Add Warped Pond craft

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Sky Island] Add Warped Pond craft"

#### Purpose of change

Been meaning to do this for months, and more ways to decorate your island are good.

#### Describe the solution

Create a crafting recipe that creates a pond on your island. It takes 30 warp shards and requires that you have a water tile nearby (so you can only create a pond when you've already secured a source of infinite water). The craft requires that you select a water tile and, when doing so, you can place the pond to the NW, NE, SW, or SE (so it's not on top of any part of the bunker). The pond's appearance is slightly random.

#### Testing

Recipe works. If you cannot select a water tile, the warp shard cost is refunded. The menu to pick a location pops up and all locations are correct. The pond appears.

### CODE REVIEW

**Comment by Naadn** [comment]
Could the water well/water pump be count as a source of infinite water for EoC? I would like have pond on island but don't want 1 single ugly water tile to ruined the scenery.

**Comment by Standing-Storm** [comment]
Ugly? :(

it should be possible to check for either a water pump or a water tile.  I’m away from home now but can get to it in a couple days.

**Comment by Naadn** [comment]
> Ugly? :(

I mean a single, square water tile away from the rest, cause it need to be near the statue

**Comment by Standing-Storm** [comment]
It's not the statue, it's the warp obelisk, and you can drag that wherever you want IIRC. 

It's still a good idea to include wells and pumps since they're also infinite water sources though

**Pull request merged**
