### PR TITLE
gave peanut butter some much needed love

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary

SUMMARY: Content "added peanut butter as an ingredient to more recipes"

#### Purpose of change

Peanut butter (and by extension, imitation peanut butter) has laughably little use ingame; you can only make 4 variations of a peanut butter sandwich with it.

#### Describe the solution

added peanut butter/imitation peanut butter as an ingredient to several appropriate recipes including milkshakes, icecream and cookies.

#### Describe alternatives you've considered

add peanut butter to more recipes or create new recipes that use it

#### Testing

cleaned of syntax errors and linted json files

#### Additional context

I plan to make more recipes that utilize peanut butter in the future.

### CODE REVIEW

**Comment by topherclay** [comment]
> I plan to make more recipes that utilize peanut butter in the future.

[George Washington Carver's book](https://archive.org/details/CAT31355406/mode/2up) is free to browse online. It might be fun if you added it for discovering some recipes!

**Comment by Mom-Bun** [comment]
Might be worth it to add peanut soup to this too

**Comment by ZhilkinSerg** [comment]
Some tests are failing.

**Comment by BrettDong** [comment]
Need to update `tests/iteminfo_test.cpp` at around line 1680:
```c++
    SECTION( "nutrient ranges for recipe exemplars", "[iteminfo]" ) {
        ice_cream.set_var( "recipe_exemplar", "icecream" );

        CHECK( item_info_str( ice_cream, { iteminfo_parts::FOOD_NUTRITION, iteminfo_parts::FOOD_QUENCH } )
               ==
               "--\n"
               "Nutrition will <color_cyan>vary with chosen ingredients</color>.\n"
               "<color_c_white>Calories (kcal)</color>:"
               " <color_c_yellow>126</color>-<color_c_yellow>467</color>"
               "  Quench: <color_c_yellow>0</color>\n" );

        CHECK( item_info_str( ice_cream, { iteminfo_parts::FOOD_VITAMINS } ) ==
               "--\n"
               "Nutrition will <color_cyan>vary with chosen ingredients</color>.\n"
               "Vitamins (RDA): Calcium (7-28%), Iron (0-83%), "
               "Vitamin A (3-11%), Vitamin B12 (2-6%), and Vitamin C (1-85%)\n" );
    }
```

**Pull request merged**
