### PR TITLE
Let some missing text be translated

### PR DESCRIPTION
**Pull request by kwl01skz**
This problem seems to last for a while.
The  _() doesn't work when Assigning the initial value to string title_XXX 
So we have to do _() again each time they are referenced.
Now it works.

Update: Find some missing content
 
#### Summary
  ```SUMMARY: I18N "Let some missing text be translated"```

#### Purpose of change
 
 
before

after

### CODE REVIEW

**Comment by AMurkin** [comment]
Probably this variables should be declared with `translate_marker()` instead of `_()`.

**Comment by kwl01skz** [comment]
> Probably this variables should be declared with `translate_marker()` instead of `_()`.
no, it is not work.
I will try to read the documentation of gettext again.

**Comment by Qrox** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/1bfd9e97dc5b74ce1675ff2e5af7990ec440e0d5/src/player_display.cpp#L29-L35

You probably need to change `_()` here to `translate_marker()` to avoid double-translation, and to allow the translation to update after switching language in game.

**Comment by kwl01skz** [comment]
> I guess the strings were not translated because as static variables they were initialized before gettext was properly set up. So you probably need to change `_()` here to `translate_marker()` to mark the string for later, proper translation.

Thanks, I understand that we can mark them with translate_marker() instead of gettext()
In other words, I still have to use _() to wrap them each time I reference these title_XXX

**Comment by kwl01skz** [comment]
I think there are no problems now that can be merged.

**Pull request merged**
