### PR TITLE
Fix description of Mannwurst

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Wrong.

[Do a modicum of research before you kill off the joke, folks.](http://grammarist.com/archaic/long-pig/)

**Comment by ZhilkinSerg** [comment]
> I'm tempted to revert this PR outright for being a buzzkill.

Sorry. :)

**Comment by Cyrano7** [comment]
@Rivet-the-Zombie What research would someone have done? I had never heard of it until today and even the linked article says "The term is rarely used now, except in historic context." The wording is tricky as long is placed where it could describe the sausage or the pork.

Maybe it's best to leave a note. I can appreciate the reference now, but it's only a matter of time before someone else tries to 'fix' this again.

**Comment by ZhilkinSerg** [comment]
We can add `//` node with comment near the description.

**Pull request merged**
