### PR TITLE
Lava rework

### LINKED ISSUE #24459: Lava on the roof
I just came across this weird thing

image

Lava stripe on the top of Apartment Tower. 

I see no logic in it? Should only be on the ground level?

### LINKED ISSUE #28407: Make lava more THICC
In my tileset lava supports connected textures. However all the time lava line spawns on the ground it placed in such a way what my connected tiles are not connected. Lava should be slighttly more thick, so it will connect propper.
Here an exapmle.
not thick, original, not connected in most parts
lavawrongtiles
THICC, connected
lavarighttiles

### PR DESCRIPTION
**Pull request by ianestrachan**
#### Summary
```SUMMARY: Bugfixes "Improvements to fumarole lava spawning"```

#### Purpose of change
Fixes #24459 and fixes #28407.

#### Describe the solution
Prevents fumaroles spawning on all z-levels above 0. This prevents it from showing up in the middle of tall buildings, floating in the air, etc.

Adjusts the fumarole creation to draw two adjacent (possibly partially overlapping) lines, guaranteeing an unbroken line of lava squares. This makes tiles look nicer, and also prevents monsters slipping through on diagonals.

Finally, when a fumarole is generated, it sets everything adjacent to it on fire. If it spawns in a road or open field the fire will burn out quickly; if it spawns in a building or forest, the fire will spread.

#### Describe alternatives you've considered
I'm not sure if there's a better way to select all the points adjacent to each tile, but I did add them to an `std::set` so that there wouldn't be duplicates.

I'm also not sure if a 15-intensity 10-turn fire is the best choice but it seems to work fine in testing for causing buildings to go up in flames. In almost all cases the fire will spread or burn out before the player sees it.

The fire only spawns on creation of the fumarole and not on an interval. Repeated spawns seems unnecessary given that anything flammable would be incinerated the first time, and it also seems an unnecessary way to spend CPU cycles to repeatedly spawn fires on burnt-out tiles.

#### Additional context
Example of the new lava after being spawned from the debug menu:
NewLava

### CODE REVIEW

**Comment by hyper2snyper** [comment]
some astyle problem

**Comment by Inglonias** [comment]
I don't know how to feel about fumaroles setting things on fire. It makes sense, but it can also cause alarming fires before you're ready for them if you're not careful.

**Comment by I-am-Erk** [comment]
> I don't know how to feel about fumaroles setting things on fire. It makes sense, but it can also cause alarming fires before you're ready for them if you're not careful. It causes odd gameplay implications, I suppose.

I think more things being on fire is generally the kind of look we're going for in the early cataclysm

**Comment by Inglonias** [comment]
> > I don't know how to feel about fumaroles setting things on fire. It makes sense, but it can also cause alarming fires before you're ready for them if you're not careful. It causes odd gameplay implications, I suppose.
> 
> I think more things being on fire is generally the kind of look we're going for in the early cataclysm

That's the thing though. Things will catch fire, yes, but not only in the "early cataclysm". They catch fire whenever the fumarole enters your reality bubble.

**Comment by ianestrachan** [comment]
I tried it before, and again just now, and having these in forests isn't too bad. The fires burn quickly and (thankfully) Cataclysm has no modelling for embers carrying through the air, so the fire only goes in connected lines, and only between trees and shrubs (which can spread it occasionally); long and tall grasses don't spread fire.

What seems to happen is the fire will burn off in only one or two directions and quickly burn itself out when it hits any kind of gap. The fire might head off and cut a swathe through the forest leaving piles of ash behind, but A) it's not a huge danger to the player because it spreads so slowly, B) it will leave a cleared path behind it within one in-game hour, C) if it's raining or snowing the fires go out faster, often before they can spread at all, and D) it's actually kind of interesting to find a spot where this has happened. You can follow the trail of destruction back to the fumarole at no real personal danger.

**Comment by nexusmrsep** [comment]
The other option could be going for 'what was able to burn burned away a while ago' and actively translating nearby flammable terrain to ash and rubble piles during mapgen fumarole placement.

**Comment by Mecares** [comment]
I like the fires caused by the lava, it gives the feeling of a world which changes by itself and not only by player activity and of the cataclysm being all around me and still going on not something that happened somewhere in the past.

**Comment by Inglonias** [comment]
It sounds like the "map encompassing inferno" hazard is relatively low, which was my main concern. I just didn't want an entire forest to turn to ash if a fumarole happened to be anywhere in my reality bubble. A building turning to ash is disappointing, but makes sense (ignoring the fact that it only happens when you show up, which is not a problem unique to this feature).

**Comment by ianestrachan** [comment]
My concern about directly mapping terrain types is that you'll probably end up with a fumarole-shaped hole in an otherwise perfectly intact house. Setting the whole thing on fire is going to look more natural.

And yes, "Map-Encompassing Inferno" is an impossibility. In the city, roads will break it if gaps between buildings don't. In a forest, it creates more of a slowly expanding ring of fire that gets patchier and patchier as it grows.

**Pull request merged**
