### PR TITLE
Standardized chemical powders for 1 unit = 1/100 mol (part 1)

### PR DESCRIPTION
**Pull request by RDru**
#### Summary
```SUMMARY: Balance "Standardized chemical powders for 1 unit = 1/100 mol"```

#### Purpose of change
It's hard to do new or balance existing recipes if you don't know how much an unit is.

#### Describe the solution
1 unit of chemical powder is 1/100 mol
Density taken from wikipedia. Added it as a comment.
Molar mass taken from https://www.convertunits.com/molarmass/
A "chunk" is 250ml volume item. Same as "metal chunk". Balanced crafting powders from chunks accordingly. Much bigger chunks felt too OP - like you find 1 and you are kinda set up for the rest of the game.
Most powders are in small bottles now - most solid state chemicals are sold like that.

This PR touches below chemicals. Number is how much LESS they weight now. Those numbers were also used to quickly change current recipes with those chemicals (previous numbers were just multiplied by them).
sulfur: 15.6
zinc powder: 12.9
zinc oxide: 15.7
manganese dioxide: 14.5
potassium chloride: 6.7
potassium hydroxide: 6.8
chromium oxide: 8.6
calcium carbide: 8.6

#### Describe alternatives you've considered
0. I actually started with 1 unit = 1 gram #34805
1. Changing recipes to allow units of volume or weight in them. But that will lead to some problems, like what to do with left overs. It's also much bigger work.
2. We could have base "items". Like "1 gram of copper" and then we inherit that to make a copper wire, etc.

#### Testing
Checked weight, volume and crafting in game. Weight for items below 1g is rounded to 0g. Will try to find it or I will make an issue about it.

#### Additional context
There is still work needed on more powders and then balancing units in various chemical recipes.

"X mg" in json for weight doesn't really work for values below 1000 mg. It rounds it somewhere so less than 1g becomes 0.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Shouldn't we keep the actual quantities of stuff the same, or close to it?

1kg of old stuff, 1kg, in some quantity of mols, new stuff?

**Comment by RDru** [comment]
You mean what we find? Yes. But I want to set it in item groups and leave quantity 100 in items.

**Comment by tenmillimaster** [comment]
So we'll find something like 100 10g baggies of the material instead of a kg Jug?

**Comment by RDru** [comment]
No, you can set up how much amount of content you find. Something like that:
      [ "protein_powder", 15 ],
      {
        "item": "protein_powder",
        "prob": 12,
        "container-item": "bottle_plastic_small",
        "charges-min": 1,
        "charges-max": 9
      }

**Pull request merged**
