### PR TITLE
[Ready] Make vehicles and parts resistant to damage, rather than having higher HP

### PR DESCRIPTION
**Pull request by EkarusRyndren**
#### Summary
```SUMMARY: Balance "Makes vehicles and parts resistant to damage"```

#### Purpose of change
As it stands, vehicles currently have no "natural armor" which seems out of place considering if you took a butter knife to your average sedan you aren't really going to do much. 

#### Describe the solution
As such, most parts (specifically anything that would have a sort of natural armor) have received a "damage_reduction" value.

Parts meant to take hits (Rams for example) have received more armor than other parts of similar materials as it's implied their construction would take it better than something that just happens to be made of hard material while parts made of something hard with inner framework (stow boards for example) have higher armor as well.

#### Additional context
After some work with kind volunteers in the discord, the parts have been balanced. Civilian vehicles won't stand up to much punishment beyond a lone zombie or smaller critters (provided they don't go for weak points, EG windows) while military vehicles will take just about everything non-military (or really big critters) and not flinch. Stuff in-between will take damage on an appropriate level, a regular hulk for example can still tunnel through a vehicle in most cases but not military grade stuff (by itself.)
While most parts still use an "All" armor quality this is mainly due to most having a general resistance to attack, parts that are weaker/stronger to certain kinds of attacks (EG tires have a bash resistance but no cutting resistance outside the armored tire) have received matching resistances.

### CODE REVIEW

**Comment by NickGrease** [comment]
While I'm not opposed to the idea, I think `damage_reduction: all` is going to have a lot of unintended consequences (acid damage comes to mind). I think flat damage reduction *in general* is bad, usually leading to invulnerable parts, monsters getting stuck beating the same part ad infinitum, etc.

This could also negatively impact the player, bashing car parts for chunks is fairly common, and I'm not sure how this change would interact in terms of damaging the tool the player was using (crowbar, bat, etc).  Seems like an idea with good intentions...

A %damage reduction makes a little more sense to me, but it's not my call, and probably a lot more work.

**Comment by Night-Pryanik** [comment]
> usually leading to invulnerable parts

I don't see nothing bad in some types of armor (military composite, for example) being invulnerable to most (if not all) types of damage with value lower than some threshold.

> This could also negatively impact the player, bashing car parts for chunks is fairly common

Again, players should not be able to damage highly-resistant types of armor. They could get chunks from bashing the ordinary civilian sedan, but they shouldn't get anything from trying to bash a tank.

> how this change would interact in terms of damaging the tool the player was using (crowbar, bat, etc)

I believe nothing will change in this matter. It will only affect parts' ability to withstand the damage.

**Comment by TechyBen** [comment]
> While I'm not opposed to the idea, I think `damage_reduction: all` is going to have a lot of unintended consequences (acid damage comes to mind). I think flat damage reduction _in general_ is bad, usually leading to invulnerable parts, monsters getting stuck beating the same part ad infinitum, etc.

_Some_ parts being immune to small attacks/denting seems reasonable. Not all, panels etc could easily be dented and torn if thin, but large structures would take big sledge hammers or grinders to destroy.

**Comment by crazykiddeath** [comment]
> 
> 
> > While I'm not opposed to the idea, I think `damage_reduction: all` is going to have a lot of unintended consequences (acid damage comes to mind). I think flat damage reduction _in general_ is bad, usually leading to invulnerable parts, monsters getting stuck beating the same part ad infinitum, etc.
> 
> _Some_ parts being immune to small attacks/denting seems reasonable. Not all, panels etc could easily be dented and torn if thin, but large structures would take big sledge hammers or grinders to destroy.

I think you'd be surprised by how much punishment steel sheets and steel plates can take, the place I used to work had a hydraulic metal shear that had (iirc) some 9tons of pressure per sq inch and that would struggle with particularly long pieces of sheet metal. Even steel sheets that are only a few mm thick will take you a good long while to get through with a sledgehammer/pickaxe/similar tool if you can manage it at all.

Anything thicker then that, you can hammer on all day long and all you are going to end up doing is mess up your hands.

**Comment by EkarusRyndren** [comment]
> While I'm not opposed to the idea, I think damage_reduction: all is going to have a lot of unintended consequences (acid damage comes to mind). I think flat damage reduction in general is bad, usually leading to invulnerable parts, monsters getting stuck beating the same part ad infinitum, etc.

The damage reduction values used aren't incredibly high, if you were to take a sledge to a car you're still going to damage the parts on a civilian car (military with high enough strength.) As far as the over-use of the "all" is concerned, I'm not entirely certain the line checks for environmental damage types but that's a simple enough fix if it does.

As far as monsters not being able to break through a car is concerned that's kind of the point, a lone zombie _shouldn't_ be able to get through a car unless it goes for a weak point (eg a window.)

**Comment by KorGgenT** [comment]
jenkins rebuild

**Comment by Night-Pryanik** [comment]
> What is the damage output of the player with a sledge hammer, an electric jack etc?

Depends on player's strength, target armor and many other factors.

**Comment by TechyBen** [comment]
> I think you'd be surprised by how much punishment steel sheets and steel plates can take, the place I used to work had a hydraulic metal shear that had (iirc) some 9tons of pressure per sq inch and that would struggle with particularly long pieces of sheet metal. Even steel sheets that are only a few mm thick will take you a good long while to get through with a sledgehammer/pickaxe/similar tool if you can manage it at all.
> 
> Anything thicker then that, you can hammer on all day long and all you are going to end up doing is mess up your hands.

Yeah, I agree. Just with cars the materials vary massively (bumpers being plastic, panels not often sheet metal for some brands, while older cars are like _tanks_... lol). So just noting that the "must reduce damage only" mentality kinda missed the point. :P

Similar with weapons, some people like the follow "game" design philosophy, which is in no where like real life... and somehow they also let those ideas affect their real life interpretations (imagining a Tank has HP, and they could hit it with a rock until it exploded). ;)

**Comment by crazykiddeath** [comment]
> 
> Yeah, I agree. Just with cars the materials vary massively (bumpers being plastic, panels not often sheet metal for some brands, while older cars are like _tanks_... lol). So just noting that the "must reduce damage only" mentality kinda missed the point. :P
> 
> Similar with weapons, some people like the follow "game" design philosophy, which is in no where like real life... and somehow they also let those ideas affect their real life interpretations (imagining a Tank has HP, and they could hit it with a rock until it exploded). ;)

I see your point, I wonder if it would be possible to base it, at least partially, off of what (if any) armour you have added to your vehicle, with the armour being the first layer of defence that needs to be bypassed. Even a relatively flimsy car could be made into something much more sturdy if you cover it in steel plating/steel sheets/composite armour, piercing/deforming the flimsier panels would IRL require getting through said layers of plating first.

Way beyond the range of the outlined PR but maybe something to consider for the future.

**Comment by Rail-Runner** [comment]
> This could also negatively impact the player, bashing car parts for chunks is fairly common

This really doesn't seem realistic to me unless player finds a sledgehammer or something like that to do this.

> A %damage reduction makes a little more sense to me, but it's not my call, and probably a lot more work.

Not really. I think one would rather break their own hands than significantly damage a car or heavier vehicle with bare hands or feet, if they tried to do that. The same applies to normal zombies.

> Even a relatively flimsy car could be made into something much more sturdy if you cover it in steel plating/steel sheets/composite armour, piercing/deforming the flimsier panels would IRL require getting through said layers of plating first.

I don't think it'd work like that. If one attached composite plating to a light wooden frame, then any strong hit would break the frame, though the plating may still be intact.

**Comment by crazykiddeath** [comment]
> 
> 
> > This could also negatively impact the player, bashing car parts for chunks is fairly common
> 
> This really doesn't seem realistic to me unless player finds a sledgehammer or something like that to do this.
> 
> > A %damage reduction makes a little more sense to me, but it's not my call, and probably a lot more work.
> 
> Not really. I think one would rather break their own hands than significantly damage a car or heavier vehicle with bare hands or feet, if they tried to do that. The same applies to normal zombies.
> 
> > Even a relatively flimsy car could be made into something much more sturdy if you cover it in steel plating/steel sheets/composite armour, piercing/deforming the flimsier panels would IRL require getting through said layers of plating first.
> 
> I don't think it'd work like that. If one attached composite plating to a light wooden frame, then any strong hit would break the frame, though the plating may still be intact.

I didn't consider wooden vehicles if I'm honest, I was thinking more of the standard budget car/box van, you are somewhat mistaken though. It depends on how sturdy the wood frames actually are, see converted wooden ships used during the american civil war for examples of wooden vehicles with metal armour plating.

**Comment by EkarusRyndren** [comment]
Some experimenting has shown that acid doesn't seem to damage vehicles at all, regardless of the "damage_reduction" value. Fire does seem to be affected by this value but unless someone can tell me otherwise I see no reason to make parts less resistant as the few that are "strong enough" to be ignoring significant amounts of fire damage are the hardened parts to begin with (Wood being an example of something that'd be "weak" to fire, but it isn't' strong enough for it to be noticeably affected by the "all" damage resistance)

Figured anyone paying attention might want an update.

**Comment by EkarusRyndren** [comment]
Made a minor discovery, seems to be a known issue but mentioning it for those asking about fire/acid damage to vehicles. It seems fields don't deal direct damage to vehicles, fire damage seems to be related to a separate thing I am unaware of but seems linked to the "bash" damage type. As attempting to balance for fire functioning as bash would mess up a handful of things as well as lead to problems down the road when the fields problem is fixed I won't account for it in this.

**Comment by EkarusRyndren** [comment]
I haven't heard any more complaints and resolved the ones that have been had so far. I believe this is ready to go.

**Pull request merged**
