### PR TITLE
Fire Extinguisher as make-shift fog machine.

### PR DESCRIPTION
**Pull request by pipehat**
- let the fire extinguisher shoot a cloud of obscuring fog (for fun and emergency escape)
- adds 'fog' field effect type

### CODE REVIEW

**Comment by Coolthulhu** [comment]
And what is this fog supposed to do? It needs to do something other than just animating.
You added loudness, but I am not sure if it will ever trigger. Isn't it like, a gun-only field?

**Comment by pipehat** [comment]
Other than look interesting I wanted it to offer the player a couple turns of obscuring smoke screen as an escape mechanism.

**Comment by Coolthulhu** [comment]
Well, it isn't obscuring anything at the moment. Except item display.

**Comment by Metallumere** [comment]
This makes me happy, even if it is purely visual.

**Comment by pipehat** [comment]
Hmm, is the switch block in lightmap.cpp what I'm missing for that (obscuring line of sight)? I left it out because when I initially added fog there it rarely ever blocked LOS at all. I think because lightmap.cpp may be ignoring the transparency hints from field.cpp and just assumes that density below 3 is partially transparent. And the fog dissipates from density 3>2 almost instantly.

**Comment by BevapDin** [comment]
> Well, it isn't obscuring anything at the moment.

The switch in lightmap.cpp considers everything with `transparency == false` to be completely opaque (via the default case), regardless of the density. That works fine for the fog.

The fog of one spraying dissipates after around 10-14 turns.

**Comment by pipehat** [comment]
Added in usage in lightmap.cpp and a few other spots. Unfortunately it doesn't seem like this does anything to break line of sight with zombies which was an effect I was hoping for.

**Comment by i2amroy** [comment]
Honestly I'd love to see the fire extinguisher create small clouds that severely hamper fires in their tiles (or extinguish them if they are thick enough/the fire is small enough). It'd be a lot more useful than the current "extinguish 1 tile right next to you" usage and would be more realistic.

**Comment by mugling** [comment]
Closed due to age. Would need rebasing against master if reopened

**Pull request closed without merging**
