### PR TITLE
Faux fur

### PR DESCRIPTION
**Pull request by Maskrow**
#### Summary

SUMMARY: Content "Added a few faux fur items"
#### Purpose of change

My wife asked me why the anime cat ears are made with real fur in the game, so I just had to make some faux fur variant. Also added a faux fur coat as a clothing item and also to serve as a source for faux fur patches for those cat ears.
#### Describe the solution

Simple JSON editing.
#### Describe alternatives you've considered

Telling my wife "It's just a game, why do you care?", but I love her too much.
#### Additional context

I hope that it will be less problematic than SCBA gear revamp.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Political correctness in all it's glory. No offense.

**Comment by Kelenius** [comment]
Is it possible to use `copy-from` here?

>Political correctness in all it's glory.

Huh?

**Comment by Maskrow** [comment]
@nexusmrsep
Eh, I’m not much for PETA propaganda and such myself. I know that it got some of those PC vibes, but if you think about it, faux fur instead of a real deal makes a bit more sense for anime paraphernalia.
@Kelenius
If you tell me how to do that (can do that in discord btw) and if it’s a better way to do so, will gladly do it.

**Comment by dissociativity** [comment]
Giving people more options is hardly political correctness, much like a restaurant offering vegetarian options is not.

The options are there in real life and have been throughout history, in a simulationist game I have no doubt we have reason to include them.

I am for this PR.

**Comment by nexusmrsep** [comment]
> Giving people more options is hardly political correctness, much like a restaurant offering vegetarian options is not.

That was a joke, I'm not against this PR either. Synthetics are economically cheeper then fur, so all other things aside, they would have high representation in pre-Cataclysm clothing industry.

**Pull request merged**
