### PR TITLE
[RDY]Display actual nutrition acquired, rework rotten food penalties

### PR DESCRIPTION
**Pull request by Coolthulhu**
Food display now displays actual nutrition and fun from eating food.
For example, when eating pizza as gourmand, it will display 30 fun, not 10. Carnivores will see halved nutrition for things that aren't made nearly completely of meat/eggs.
This is seen both in item descriptions and the new consumption menu.

___

Rotten food penalties reworked.
Instead of having a hard threshold when food becomes ~50% (random from 0 to 1) less edible and strongly poisonous (more so than meth or low quality alcohol), the penalties gradually build up. Nutrition from food drops from 90% (just got rotten) to 0 (about to despawn). Health penalty starts at `10%*base_nutrition` and grows up to `100%*base_nutrition`.
Also, since rotten food is supposed to be disgusting, it now gets two fun penalties: flat (from -2 to -20) and then scaling (90% to 0 for positive fun, 110% to 200% for negative). Applied before Gourmand.

This should make rotten food both more meaningful (it's better than starvation, meaning it's a nutrition vs health and fun tradeoff) and more realistic (gradual, not more dangerous than meth, scaled roughly with actual amount of "poison").

Sample numbers:

Food | Nutrition | Fun | Health
--- | --- | --- | ---
Fresh Cooked meat | 28 | 0 | 0
Just-rotten Cooked meat | 25 | -3 | -3
Totally rotten Cooked meat | 0 | -20 | -28
Fresh Meat pizza | 50 | 30 | 0
Fresh Meat pizza for Carnivore | 25 | 30 | 0
Totally rotten Meat Pizza | 0 | -20 | -50

___

[CR] because I don't know how to best handle:
* Display of nutrition for inedible stuff. Display base (as if it was edible) or 0 nutrition?
* Should there be some sort of display for base nutrition or fun? If so, where?

### CODE REVIEW

**Comment by kevingranade** [comment]
Nutrition and fun should hit 0 far before despawn.  Despawn is literally
"rotted away", if the scale is continuous instead of only having one step,
the food is inedible long before it disappears.

**Comment by Coolthulhu** [comment]
I was treating "despawn" not as "rotten away into dust" but rather "rotten beyond any use", as saprovores can still absorb it somehow.
Also, food takes as long to rot away as it takes to rot, further reinforcing that idea. Food takes more time to disintegrate than it takes to get all slimy, disgusting and potentially unsafe.

Changed the breakpoint to halfway between start of "rotten" and "rotten away".

**Comment by kevingranade** [comment]
Halfway is fine for now, that's roughly what it was before.

I agree time to item disappearance should probably be skewed much further, possibly via some intermediate state like having regular food decay into a "rotten food" item that's totally inedible, and having "rotten food" assigned a much coarser decay timer (if it's off by even as much as a day, no big deal).  This would also make it clearer what's actually happening

**Comment by Night-Pryanik** [comment]
> Health penalty starts at 10%*base_nutrition and grows up to 100%*base_nutrition.

I think base nutrition doesn't fit well here as a multiplier for health penalties. This way it will be like half-rotten cooked buckwheat will harm health roughly for the same amount as a totally rotten cooked meat.

**Comment by Coolthulhu** [comment]
> I think base nutrition doesn't fit well here as a multiplier for health penalties.

I couldn't think of anything better.
I picked nutrition because rotten juices are less harmful than rotten oatmeal, so the approximation is roughly within order of magnitude.
Could be later refined into something better by taking flags into account, but for now it's still an improvement.

**Pull request merged**
