### PR TITLE
Warm corpses

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary
```SUMMARY: Bugfixes "Corpses and butchery results have temperatures"```

#### Purpose of change
When you butcher  a corpse the items you get do not have defined temperature. So they are set to the enviroment temperature.

This can cause your freshly killed animal to drop frozen meat. It isn't good that the meat freezes instantly like that.

#### Describe the solution
Corpses now have temperature. On death the corpse is set to 37 C if the monster has "WARM" tag on it. Otherwise they are set to enviroment temperature.
The corpse item gets its temperature processed like foods. So the warm body will cool down and can even freeze.
Butchery items get their temperature from the corpse.

Item processing code has been adjusted so that non-food items can be temperature tracked.

If `has_temperature()` is true for the item then the item will be set active when it is created with `add_item()` (I hope no other way of creating items exists).

In future if any other items need to be temperature tracked simply update the following functions:
`has_temperature()`, `get_specific_heat_liquid()`, `get_specific_heat_solid()`, `get_latent_heat()` and `get_freeze_point()`. And boom the new item(s) have their temperatures processed.

Also since the corpse takes its thermal properties from its material and corpses can be made of any material I have added thermal properties to all materials in materials.json. Some of the values are rough guesses or baseless values (for example wool). Flesh corpses are the only interesting ones at the moment but I think it is nice to have something for rest of the materials too just in case.

#### Additional context
There were many places where corpses were set inactive for various reasons. If you find a corpse that stops changing its temperature then I missed one of these.

### CODE REVIEW

**Comment by Hirmuolio** [comment]
Two problems remain:
* Only zombie corpses are procesed by the `item::process`.
* If you leave zombei corpse off map, stay away for a long time and come back. The zombie revives and temperature calc throws error. Oddly no error if you are on map when the zombie revives.

**Comment by Mecares** [comment]
Are Zombies warm or do they no longer produce body heat because they are walking but still dead?

**Comment by Hirmuolio** [comment]
I would just set all creature corpses to 37C. The other option would be to define body temperature on per monster/per monster class basis. I don't think having different death temperatures would add anything important.

The error is now fixed. I still can't find how thee game decides what items to process. I would need to add non-zombie corpses to that place.

**Comment by Hirmuolio** [comment]
I think it should be ready.

While making all corpses active I had to also change zombie reviving code in few spots. Hopefully that changed nothing. Reviving still seems to work and pulping stops reviving.

**Comment by Little-119** [comment]
There's already a `WARM` tag present on every warm-blooded creature (i.e. not a skeleton, reptile, plant, fungus, etc), so defining body temperature for each creature wouldn't be necessary to make this only apply to warm-blooded creatures.

**Comment by Hirmuolio** [comment]
If the creature has "WARM" flag the corpse will be at 37 C. Otherwise the corpse will be at enviroment temperature.

Corpse now uses its material freezing point. Currently no material has defined freezing point so everything uses the default 0 C. But now a no-freeze mod can be made to remove corpse freezing.

**Comment by Night-Pryanik** [comment]
Please do test that zombies actually don't revive when they shouldn't (like smashing them with a very hard hit by a vehicle).

**Comment by Hirmuolio** [comment]
Zombies that are damaged enough to be pulped don't revive. I moved the `damage() >= max_damage()` to before the reviving code. That is what set the corpse to inactive during pulping before.

**Comment by Night-Pryanik** [comment]
Ok, thanks.

**Pull request merged**
