### PR TITLE
Armored creatures won't take damage from stepping on a sharp or rough terrain types

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Balance "Armored creatures won't take damage from stepping on a sharp or rough terrain types."```

#### Purpose of change
Prevent highly armored monsters from dying after stepping on a pile of woodchips.

#### Describe the solution
Creatures with `cut_armor` value more than 12 (I took cut protection value of a zombie hulk as a reference point) will ignore the damaging effect of stepping on a sharp or rough terrain.

#### Describe alternatives you've considered
None.

#### Additional context
Obviously monsters don't have separate body parts ATM, so for now we check for cut protection value of monsters torso. But in the future this check should be changed to monsters legs.

### CODE REVIEW

**Comment by AMurkin** [comment]
Can we have it as a constant with a comment?

**Comment by Night-Pryanik** [comment]
> Can we have it as a constant with a comment?

Done.

**Comment by ymber** [comment]
Why threshold it at 12 instead of checking if the damage that would be done is greater than the actual armor value?

**Comment by Night-Pryanik** [comment]
> Why threshold it at 12 instead of checking if the damage that would be done is greater than the actual armor value?

Well, no exact reason. 
Will make a PR with your suggestion shortly.

**Pull request merged**
