### PR TITLE
Add TropiCataclysm to the Mod Repository

### PR DESCRIPTION
**Pull request by Xaritscin**
#### Summary
Mods "Add TropiCataclysm to repo"

#### Purpose of change
TropiCataclysm has reached a somehow decent amount of development so i decided to see if it can be submitted to the master branch so it can be kept worked on by me or other contributors.

#### Describe the solution
Adds TropiCataclysm v0.50 to the mods folder as a starting point for ease of access and manipulation

#### Describe alternatives you've considered
Keeping the mod separate much like Chaosvolt's mods and spam on Reddit everytime an update comes out

#### Testing
Made a fork of the Master branch and submitted my files after finishing bugfixing and testing the latest update on my machine

#### Additional context
First time contributing to CleverRaven so i guess errors are to be expected, files seemed to be fine tho.

### CODE REVIEW

**Comment by Broken27** [comment]
@Xaritscin This is failing the Json style check - You need to lint it so it follows the proper standard.

Pass the text by this linting tool:

https://dev.narc.ro/cataclysm/format.html

**Comment by Xaritscin** [comment]
Seems the Linting error was based out of the mod Blacklist file. tried using the Linting tool provided to update the code. waiting for results

**Comment by Xaritscin** [comment]
Linting didnt do anything, perhaps the whole Blacklist file was just useless to the structure so i decided to remove it for the time being. i will come up with a different blacklisting file in the future (hopefully).

**Comment by BrettDong** [comment]
Every JSON file needs to be linted.

**Comment by Xaritscin** [comment]
Checked all the files on mod with the Linting tool. i thought it was only one file but yeah, lots of fixes so i added blacklist.json again to see if it pans now

**Comment by Xaritscin** [comment]
general build matrix fixes were done. waiting for system validations

**Comment by Xaritscin** [comment]
monster and monster generation fixes and balances.

**Comment by Xaritscin** [comment]
updated fork and linting changes to new files.

**Pull request closed without merging**
