### PR TITLE
No more multiple wedding rings per zombie

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
After #76852 there was a tiny (~0.024%) chance for a zombie to spawn with two wedding rings. This is too high.

#### Describe the solution
Remove wedding rings from ``accesories_personal_unisex``, they should spawn independently from other accessories anyway

### CODE REVIEW

**Comment by Maleclypse** [comment]
Shut it down.  https://19thnews.org/2023/04/somerville-massachusetts-legal-protections-polyamorous-families/

**Comment by Karol1223** [comment]
> Shut it down.  https://19thnews.org/2023/04/somerville-massachusetts-legal-protections-polyamorous-families/

This is a single city in a single state of the region the game takes place in, I am not convinced this makes it anywhere near common enough to have in the game.

**Comment by Consoleable** [comment]
Isn't the actual reason for having two wedding rings not necessarily polyamorous, but someone who was intending to propose? That seems like implicit ambient storytelling, which is common in post-apocalyptic games(eg. finding skeletons clutching each other in a destroyed house)

**Comment by Karol1223** [comment]
> Isn't the actual reason for having two wedding rings not necessarily polyamorous, but someone who was intending to propose? That seems like implicit ambient storytelling, which is common in post-apocalyptic games(eg. finding skeletons clutching each other in a destroyed house)

Well, the actual reason is Storm forgot to remove it.

But if you wanna get into the details I believe it's the engagement ring you're thinking of, which is also a separate item altogether.

**Comment by Consoleable** [comment]
> > Isn't the actual reason for having two wedding rings not necessarily polyamorous, but someone who was intending to propose? That seems like implicit ambient storytelling, which is common in post-apocalyptic games(eg. finding skeletons clutching each other in a destroyed house)
> 
> Well, the actual reason is Storm forgot to remove it from the second itemgroup.
> 
> But if you wanna get into the details I believe it's the engagement ring you're thinking of, which is also a separate item altogether.

could also be someone carrying around the wedding ring of a deceased spouse.

**Comment by Karol1223** [comment]
> could also be someone carrying around the wedding ring of a deceased spouse.

It very well could be, but this is also reaching insanely unlikely levels of being witnessed in the scope of the game. I am not sure how common the behavior is in the first place, and keep in mind that you'd have to luck out into finding a zombie that still hasn't lost the ring in the whole process of... you know, dying, and then shambling around in tattered clothes.

This was discussed all the way back in #63311, and is why I keep an eye out for this sort of things happening in the game itemgroups.

I am not saying this is something that can never happen - I am saying that this would not be happening often enough to warrant simulating in the game. At least I believe so, and given the conversations in the comments of the linked PR I'd say I'm not alone in this.

**Comment by Consoleable** [comment]
> > could also be someone carrying around the wedding ring of a deceased spouse.
> 
> It very well could be, but this is also reaching insanely unlikely levels of being witnessed in the scope of the game. I am not sure how common the behavior is in the first place, and keep in mind that you'd have to luck out into finding a zombie that still hasn't lost the ring in the whole process of... you know, dying, and then shambling around in tattered clothes.
> 
> This was discussed all the way back in #63311, and is why I keep an eye out for this sort of things happening in the game itemgroups.
> 
> I am not saying this is something that can never happen - I am saying that this would not be happening often enough to warrant simulating in the game. At least I believe so, and given the conversations in the comments of the linked PR I'd say I'm not alone in this.
> 
> In an _ideal_ world I think we could ditch the wedding ring item altogether, and instead spawn different types of rings all around the place, letting the players decide what they think the stories behind them were, but that's out of scope for this PR.

thanks for humoring my line of inquiry

**Comment by Maleclypse** [comment]
I understand that I only shared the one article but more cities in Massachusetts have done so since then including one of the cities that make up Greater Boston. With the already tiny odds in game I’m personally fine with the odds as is. I guarantee there are a larger number of right hand wedding bands than you suspect in any US state. Recognized or not.

**Comment by esotericist** [comment]
btw, to prevent misunderstandings: me merging this is merging a bugfix for what looks like a data entry error. it is not in any way a statement that multiple wedding rings are inappropriate, i just think if it happens it needs to be on purpose, with both a rationale and list structured to handle it in a way that can be understood and reasoned about.

**Comment by Night-Pryanik** [comment]
Just an anecdote: I've seen many times when my not-so-experienced, or simply foolish, co-workers (who was wearing rings), accidentally hooked their rings to protruding parts of machinery, and traumatized their fingers. I've heard that some unlucky fellows even lost their fingers that way (haven't seen this with my eyes though).
That's why I took my wedding ring off and gave it to my wife, and she's wearing two wedding rings on a finger.

**Pull request merged**
