### PR TITLE
Fix for item bars being hidden

### LINKED ISSUE #27631: Item health not shown
Item health bars/damaged status text not shown.

 - OS: Manjaro Linux 4.19.13-1-MANJARO
 - Game Version: 0.C-36489-g3cec9b8c91
 - Graphics version: Tiles

### PR DESCRIPTION
**Pull request by nsklaus**
#### Summary
```SUMMARY: Bugfixes "item bars were not showing anymore"```  

#### Purpose of change
Fixes #27631 item bars were not showing anymore due to error from my part
correcting bug introduced with the [cleanup of sidebar UI](https://github.com/CleverRaven/Cataclysm-DDA/pull/27352) pull request.

#### Describe the solution
i made a change in the sources while testing things around, that prevented item health bars from showing up. This correct that mistake.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
jenkins rebuild

**Comment by nsklaus** [comment]
> jenkins rebuild

@mlangsdorf thanks for the review and labels.
do i need to do anything more or i just wait for jenkins to finish validating the PR ?

**Comment by AMurkin** [comment]
Fixes #27631
Edit PR description.

**Comment by Kodiologist** [comment]
@nsklaus It looks like one of the Travis builds failed due to a timeout.

**Comment by nsklaus** [comment]
> @nsklaus It looks like one of the Travis builds failed due to a timeout.

yes but i have no idea what to do about it.
i have no access to the servers config i think. not to mention no particular knowledge of jenkins.
this pull request is just 1 word change. why it fails with timeout is beyond me.

**Pull request merged**
