### PR TITLE
(Infrastructure, not yet effective) NPCs consider allergies, cannibalism, and other things when eating from camp stores

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Balance "NPCs consider allergies, cannibalism, other issues before eating from camp larder"

#### Purpose of change
With #72224 it will be possible to track whether food put into camp storage contained human parts. Naturally, NPCs are mostly upstanding people that are unwilling to eat others. So they need to be able to think for themselves.

#### Describe the solution
When feeding workers, instantiate fake food item. Override that item's default nutrition with the food nutrients struct they previously had put right into their stomach.

Check character::will_eat to see if there's anything wrong with the food (player can force themself to eat anyway, NPCs will always decline)

If won't eat, re-add food to larder (add message for player so they know what's going on). Except if you try to feed human flesh to non-cannibals. Then they just plain revolt.

#### Describe alternatives you've considered
It would have been even neater if you could take the food back out of storage as an actual 'prepared meal' item that stayed preserved *and did rot over time*. But there's no reasonable way to do that, since overriding the default nutrition only lasts until the game closes. 

(Still I did consider making components of 1_kcal and 1_vitamin and inserting them into the food's components. But that is a TERRIBLE idea!)

#### Testing

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/4d26ee8d-d8eb-43f1-81e1-7d02dbe3e21e

#### Additional context
Will have no practical effect until #72224 is merged, and then only for cannibalism.

Note that **as food is placed back in the larder on failure to eat** this has the potential for massive balance swings to how camps are made. A not hungry/allergic NPC will put the food back, meaning calories spent on upgrades are refunded (or at least that NPC's share).

But I personally am not opposed to the idea of that. 

If actual food costs don't match the labor costs of camp construction, then let the numbers fall where they may.

### CODE REVIEW

**Comment by Nebnis** [comment]
>If won't eat, re-add food to larder (add message for player so they know what's going on). Except if you try to feed human flesh to non-cannibals. Then they just plain revolt.

How would they know you are feeding them human flesh? Unless they see you cooking.

**Comment by RenechCDDA** [comment]
The same way the player knows the exact nutritional content of food.

**Comment by Qrox** [comment]
So if I blow up a bandit with a cannon and a piece of their flesh happens to land at the camp food zone and I distribute food without knowing, my follower will then blow me up when they have their next meal? Perhaps a warning should be added when adding allergenic food or human flesh to the camp larder.

**Comment by RenechCDDA** [comment]
> So if I blow up a bandit with a cannon and a piece of their flesh happens to land at the camp food zone and I distribute food without knowing, my follower will then blow me up when they have their next meal? Perhaps a warning should be added when adding allergenic food or human flesh to the camp larder.

I consider the chances for accidentally putting cannibalism-derived food in the larder extremely miniscule. Among other reasons being that the scenario you've posited simply isn't possible. Not just because bandits aren't going to wander into your faction camp, but because even if they did and you gibbed them into pieces, the resulting pieces have too low enjoyability to be placed into the larder without specifically processing them into food. (Similarly, raw meat, scraps, and offals of all other kinds cannot be put into the larder.)

There is an incongruence where with this PR, NPCs will only react to player cannibalism in the context of being fed from the camp... but the solution to that is to make sure non-cannibal NPCs (at best) ostracize the player *elsewhere* when the player engages in cannibalism. Not to further make it more difficult for the player to be held accountable by their companions.

**Comment by Qrox** [comment]
You're right raw flesh cannot be put into the larder, but I still think accidentally putting *allergenic* food into a larder is a real concern.

**Comment by RenechCDDA** [comment]
Right now it's simply not possible to put allergenic food in the larder, it's all flag-based. If my plans go ahead to make them all into vitamins then we'll need another solution, yes, but definitely not by always warning on input. Remember, wheat is an allergy. Meat is an allergy. Vegetables are an allergy. Everything is a bloody allergy!

But that's neither here nor there, it is a problem that will be tackled before or during transitioning allergies to vitamins.

**Comment by RenechCDDA** [comment]
> Right now it's simply not possible to put allergenic food in the larder, it's all flag-based. If my plans go ahead to make them all into vitamins then we'll need another solution, yes, but definitely not by always warning on input. Remember, wheat is an allergy. Meat is an allergy. Vegetables are an allergy. Everything is a bloody allergy!
> 
> But that's neither here nor there, it is a problem that will be tackled before or during transitioning allergies to vitamins.

One thing I've thought about is making all the allergen-type vitamins to a new vit_type, `"vit_type": "allergen"` or whatever. Then concocting a list in the bulletin board designating whether or not each specific vitamin should warn, with only certain allergens (basically just cannibalism) set to *always warn* by default. The player could interact with the list and swap between "Always warn", "Warn only if player is allergic to this", and "Never warn".

**Comment by Qrox** [comment]
Maybe ultimately we should change the larder to a real on-map zone that stores individual items, which should solve most of the problems of only storing an aggregated nutrient value.

**Comment by Montimorency** [comment]
> Maybe ultimately we should change the larder to a real on-map zone that stores individual items, which should solve most of the problems of only storing an aggregated nutrient value, such as contaminating all food with allergen with a single egg.

An alternative would be to match calorie input to vitamin input of any larder submission, with allergens being one such vitamin. So, for example, if there are 1000 calories in the larder, and 100 of them were submitted with an egg allergen item*, then only 100 calories in the larder are 'contaminated', and an allergic NPC will not withdraw those calories by default unless or until _the rest_ have been exhausted. Having the same system for PC withdrawals would also be nice.

This would avoid a 'bathwater effect.'


*assuming here allergens are treated as a binary effect rather than a spectrum

**Pull request merged**
