### PR TITLE
Aftershock: cam-spy rovers to spy on zombies.

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary

SUMMARY: Mods "Aftershock: Cam-spy drones let you survey buildings from safety"

#### Purpose of change

Adds one more neat high-tech tool to aftershock. Not vanilla since it works in a slightly hack-y way.

#### Describe the solution

Cam-spy rovers work almost exactly like the already existing RC cars, with the only difference that they continuously emit clairvoyance fields to simulate having a mounted camera.

#### Describe alternatives you've considered

Actually adding support for proper cameras, but that's a lot of work I dont want to do just to add a single item.

Items Spawns only as part of the initial gear of the corporate infiltrator. Deserves a recipe/spawns later on.

#### Testing

Load the Corporate infiltrator profession, drive the rover around.

### CODE REVIEW

**Comment by jbytheway** [comment]
We already have camera support as a vehicle part.  I would have hoped it wouldn't be too hard to adapt that to an item.

**Comment by anothersimulacrum** [comment]
#37200 had that working

**Comment by John-Candlebury** [comment]
After giving it a look, I think fixing and building over that is more complex that I feel confident doing.

**Comment by Entity-y** [comment]
This sounds cool, are the drones capable of changing between Z-levels and have you thought about making a C-4 strapped variant?

**Pull request merged**
