### PR TITLE
[Ready] Add test target to all make target so tests get compiled by default.

### PR DESCRIPTION
**Pull request by kevingranade**
Teensy change, build those tests by default so they don't get out of sync with the rest of the code.
They're not ready to auto-run yet, the player test in particular takes too long.

### CODE REVIEW

**Comment by kevingranade** [comment]
dRbiG pointed out that this might not build properly with RELEASE=1, so please try that before pulling, setting to WIP because I probably don't have time to wait for a release build to finish tonight, I have to sleep some time.

**Comment by narc0tiq** [comment]
I'll look into it, and if I find only easily-fixable issues, I'll resolve those in the merge.

**Comment by narc0tiq** [comment]
For the Windows cross-builds, I don't have `librt.so` available. I'd try to remove `-lrt` from the compile orders, but I'm not sure what that would break.

I'll PR the changes I needed to make for the Linux and Lin64 builds to this branch of yours.

**Comment by drbig** [comment]
Regarding `RELEASE=1`:

At least in my corner of platform-space it looks to work fine, i.e:
```
$ make -j4 CLANG=1 CCACHE=1 NATIVE=linux64 LOCALIZE=0 LUA=1 RELEASE=1 TILES=1 tests
$ ./tests/cata_test -d yes
```

Results in [this](http://ix.io/k0I). I build my for-play CDDA with the same options as `tests` here.

**Comment by kevingranade** [comment]
Hopefully this will sort things out for windows builds.
As a bonus it's a bit simpler.

**Pull request merged**
