### PR TITLE
Improve aiming UI

### LINKED ISSUE #17295: Setting turret mode (burst/semi) requires control access
Before, it could be done from the turret's position, which makes more sense for "primitive" turrets.

### PR DESCRIPTION
**Pull request by mugling**
- Factored out of #17751 as can be tested separately
- Fixes #17295
- Targeting display now includes detail about amount and type of ammo
- Can switch turret mode (semi, burst, auto etc) via targeting UI

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I didn't get the keybind for the mode switch anywhere. Pressing 'q' just drops the aiming menu.

**Comment by mugling** [comment]
I'll take a look now

**Comment by mugling** [comment]
Can reproduce, will see what I missed out when extracted from #17751

**Comment by mugling** [comment]
Found it - many turrets only have a single mode so the behavior is correct. Try with `flamethrower` or `watercannon`

**Comment by Coolthulhu** [comment]
Does it only work with turrets? I though it works with any weapon that has modes.

**Comment by Coolthulhu** [comment]
OK, it works with turrets.

**Comment by mugling** [comment]
No. I'd like it to work with other weapons but that actually requires more significant refactoring

**Comment by Coolthulhu** [comment]
I tested it by just commenting out the `if`. Looks like you're right, it still needs some extra code to start working for held weapons.

**Comment by Coolthulhu** [comment]
While you're updating the aiming UI, it could be a good idea to make it not auto-target friends, ever.

**Comment by mugling** [comment]
Sounds reasonable - can you open an issue so that doesn't get forgotten

**Pull request merged**
