### PR TITLE
Fix gravel terrain.

### LINKED ISSUE #35543: Smashed Gravel Producing Roofs
# Describe the bug
Smashing gravel tiles (above ground) at a Lumberyard, Farm, or other generated structure that has gravel, produces a rock floor, which generates a roof upon reload. 

# Steps To Reproduce

1. Find Lumberyard, or other gravel-supporting world generation
2. Smash gravel tiles, leaving a rock floor
3. Check above z-level
4. Save/Load
5. Check above z-level again to find spontaneous roofing

# Expected behavior
As amusing as free-floating roofing is, gravel probably shouldn't produce them.

# Screenshot
roofingescapades

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9374-g73f6a9a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
# Additional Info
This isn't an issue underground, where Gravel used to be only used for subways, but now that it's creeping up onto the surface, it's causing (mild) issues.

### PR DESCRIPTION
**Pull request by arijust**
#### Summary

 ```SUMMARY: Bugfixes "Fix gravel terrain."```
#### Purpose of change

Close #35543
#### Describe the solution

Add correct terrain for deconstruction and terrain smash for gravel.
Changed min_str to 30 for successful bash.

### CODE REVIEW

**Comment by Funguss** [comment]
Hang about, this isn't the way to do it. It should be changed to "t_null", as that will take the base terrain for that Z level (I believe that's how it works, anyway).

While you're at it it might also be a good idea to get rid of the whole smashing thing, too. I don't even know why that's there, or exactly how one would bash away gravel. Sure, you can explain it as sweeping it away, but for that it's best to add something to the broom because right now zombies will occasionally pause to smash gravel, which is plain ridiculous.

**Comment by arijust** [comment]
>It should be changed to "t_null", as that will take the base terrain for that Z level

It's way more likely to create 1-Z hole instead.

>I don't even know why that's there, or exactly how one would bash away gravel.

If I remember it right, every furniture/terrain has "bash" as main requirement. 
Making str_min higher would give it more sense, but I want to see opinion of other people before doing so.

**Comment by Funguss** [comment]
> It's way more likely to create 1-Z hole instead.

Why would that be the case? Plenty of terrain transforms to t_null and without issue. Have you tested this already?


> If I remember it right, every furniture/terrain has "bash" as main requirement.

Huh, maybe I misread the jsons somewhere, I was pretty sure I've seen ones that don't. Scratch that then, sorry for throwing a spanner in the works! In terms of your suggestion I don't see why anybody would have an issue with raising the str requirements to the level of dirt, it seems like an oversight in the first place. I was just throwing it out there as you were making changes to gravel as seeing zombies smashing up gravel breaks immersion a bit. One of those bugs I've been seeing for so long I've just grown accustomed to it.

**Comment by arijust** [comment]
>Why would that be the case?

Recently, it seemed to be buggy and created random holes in ground after some walls collapsed. I am not sure if that was fixed or not, though.

>Have you tested this already?

Not yet.

>I don't see why anybody would have an issue with raising the str requirements to the level of dirt

It seems to be little too much. I would rise it to 30-something at most.

**Comment by arijust** [comment]
I just checked and t_null works fine.
Now only to tweak str_min and it will be all.

**Comment by Funguss** [comment]
Nice! I got the impression that the reason for the ludicrously high strength requirement was that it generated the "there's nothing there to smash!" message. Thinking about it now there are clearly walls etc. with higher strength, so I'm guessing there's a flag or something, but it's not immediately obvious. Maybe it's hardcoded?

**Pull request merged**
