### PR TITLE
Shot balance and choke

### PR DESCRIPTION
**Pull request by wwkk222208**
#### Summary
None

#### Purpose of change
This PR is seperated from Aim overhaul and guns/gunmods balance #53106.
In the master version shotguns still behave like short-range rifles. In fact, the shot spread in the real world is more prominent than in the game.
shot_strings_choke_effect
Shot spread in the real world can reach 90 MOA even with full choke, which is more significant than weapon dispersion.  In the game, the dispersion of rifles is about 20 MOA. So shot spread should be much larger than this value.

So in this PR, the shot spread has been significantly increased. 

At the same time, because the current game mechanism can reflect the characteristics of the shotgun damage decay rapidly with the increase in distance, the previous distance limit seems a bit out of date, so the range of the shot has been increased.

Add choke as gunmod which can effectively reduce the shot spread, so that shotguns can perform better when dealing with distant targets.

#### Describe the solution
00_shot:  shot_dispersion:10->300 range:12->18 
shot_bird: shot_dispersion:10->300 range:15->18
choke: reduce 30% shot spread     **can't fire slugs**
Add choke into "gunmod_common".
Add recipe of choke.

#### Describe alternatives you've considered
The specific value of shot spread may need to be adjusted. The range of 00_shot in the master version is 12, so I hope that the damage caused by 00_shot is much lower than that at close range when the distance exceeds 12. After many trials, 300 was finally chosen.

#### Testing
A npc (all stats = 10 all skills=5) shoot different monsters at different range with shotgun_s without recoil 1000 times. Caculate average damge.

shot_balance

More test results can be obtained from the ranged_balance_test.cpp.

Tested item groups ,recipe and crafting.

#### Additional context
All the results of tests at point blank are abonormal, which is an inherent problem.

### CODE REVIEW

**Comment by wwkk222208** [comment]
This PR is temporarily closed. Because I need to solve the problem

**Comment by kevingranade** [comment]
> In order to balance the game, the damage of a single projectile has been slightly increased.

There is not a target balance point for these, I calculated the KE of the pellets and derived the damage from those, the tests are there to detect unexpected changes to the resulting damage, so the previous damage values are preferred.

> At the same time, because the current game mechanism can reflect the characteristics of the shotgun damage decay rapidly with the increase in distance

The range increase is just fine, especially as the increased dispersion should have the effect we want of making progressively less of the shot hit at target with increasing range, but just FYI there is an additional damage falloff with range that shot is subject to, especially birdshot, since the ballistic characteristics of shot are so much worse than rifled bullets, and the shot decelerates so quickly.

Wonderful changes, love it.

**Comment by wwkk222208** [comment]
> I calculated the KE of the pellets and derived the damage from those.
That is really cool. I love it.

**Comment by wwkk222208** [comment]
>the tests are there to detect unexpected changes to the resulting damage

After changing the shot spread, the variance of the damage distribution became particularly large. At that time, I thought it seemed meaningless to test the damage of a single shot. So I changed the test to calculate the average.
However, there seems to be a small probability that the generation of organisms will fail. This problem is especially prominent when the number of test repetitions increases. In the submitted commit, the number of tests has been reduced from 1000 to 100. Maybe I should continue to reduce the number of tests, or change back to testing a single shot?

**Comment by wwkk222208** [comment]
I am still working on aim overhaul. I think the reason that shotgun aiming is better than rifle shooting is that they can fire cloud-shaped projectiles and can hit the target without precise aiming. Now that the shotgun can fire cloud-shaped projectiles, I removed the buff of the aim speed of the shotgun.
After making these changes, what I actually experienced in the game is that shotgun is not easy to use, compared to smg. Without choke, it only has a good performance in a very close range (range <5).
I'm not sure if I missed something. Or is it what the shotgun is supposed to be?

**Comment by Shodan14** [comment]
Really cool to see shot mechanics getting fleshed out. Just wondering if the slug range is still fine with these increases?

**Comment by wwkk222208** [comment]
> Really cool to see shot mechanics getting fleshed out. Just wondering if the slug range is still fine with these increases?

No change to the slug. But shotgun with choke cannot fire slug.

**Comment by kevingranade** [comment]
> Without choke, it only has a good performance in a very close range (range <5) Even at this distance, shotguns have no advantage over smg or even rifles.

That's pretty much expected yes, though I expect better ability to "snap fire" at the end of the day, i.e. we can take a look at reaction times and ranges for skeet shooting.

**Comment by wwkk222208** [comment]
I did further tests and found out why shotguns did not have ideal performance.
The damage of shots to unarmored targets is overflowing, so whether most projectiles hit the target is not so important. However, creatures in the game seem to be tougher than those in the real world, which causes  even an ordinary zombie to be killed in one shot only when most of the projectiles hit it. If we lower the resilience of monsters in the world settings, the shotgun performance in close combat can be very ideal, even surpassing SMGs and rifles.
I think this result is acceptable, because the existing shotguns are not designed for mutant creatures and zombies.
**Shotguns are still most powerful civilian weapons for close combat **, although they can't match with automatic weapons.

**Pull request merged**
