### PR TITLE
Urban Development Part 2

### PR DESCRIPTION
**Pull request by acidia**
This is the second step to implementing the urban development concept #21488.  Contains buildings 11-20.

This batch contains 5 traditional or ranch houses, 2 victorians, 1 duplex, and the first two “dense urban” tiles.  Using “dense urban” on the overmap simply because the tiles contain a mix of residential and commercial fronts occupying the same tile and wouldn’t necessarily be distinguishable from a distance.     

Forum thread: http://smf.cataclysmdda.com/index.php?topic=14812.0

### CODE REVIEW

**Comment by Maykeye** [comment]
Line endings are CR LF. This will cause git issues on Linux/mingw systems.
(https://github.com/CleverRaven/Cataclysm-DDA/issues/21719)

**Comment by acidia** [comment]
Mighty strange, after part 1 I used the script instead of the browser version... Guess it didn't make a difference.

**Comment by BorkBorkGoesTheCode** [comment]
Have you tried using Notepad++ to replace the CRLF with LF?

**Comment by acidia** [comment]
Github isn't detecting any changes when I updated the line endings, could you verify that the updated files are good?

**Comment by AlecWhite** [comment]
On windows using MINGW64 I get the previous problem.

**Comment by acidia** [comment]
Did EOL Conversion II work?

**Pull request merged**
