### PR TITLE
Make underbarrel flamethrower use "flammable" ammo types

### PR DESCRIPTION
**Pull request by Cyrano7**
Closes https://github.com/CleverRaven/Cataclysm-DDA/issues/22503

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Should close #22503.

**Comment by Cyrano7** [comment]
@Night-Pryanik It already is?

**Comment by Night-Pryanik** [comment]
@Cyrano7 Yeah.

**Comment by Cyrano7** [comment]
@Night-Pryanik Yep.

**Pull request merged**
