### PR TITLE
MShock Modded Tileset Series 14

### PR DESCRIPTION
**Pull request by chaosvolt**
Got a tad interrupted by discovering a sprite assignment error from the last PR.

Fixes:
- Scrap copper shouldn't use the mortar and pestle's sprite. Doh.

Changes:
- Gave root walls a proper sprite instead of a placeholder.
- Gave rock walls and half-built rock walls their own sprites as well.

Sprite assignments:
- Low stairs (the new ramps)

Sprite Additions:
- Pet carrier
- Bane staff
- Moruboru

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Would it be possible to fix birch bark using incorrect sprite (some white clothing)?

**Comment by chaosvolt** [comment]
Uh-oh. o.O

**Comment by Night-Pryanik** [comment]
Oh, sorry, I mean willow bark.

**Comment by chaosvolt** [comment]
Ack. Okay, let me look...

**Comment by chaosvolt** [comment]
There we go. o3o

**Comment by Night-Pryanik** [comment]
Thx for fix!

**Comment by chaosvolt** [comment]
Sorry I didn't notice that mistake sooner, Night-Pryanik. And thank you to Rivet for The Mergening.

**Pull request merged**
