### PR TITLE
Migrated the combination gun [WIP]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The loudness field on the 30-06 was removed. From #18766

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
No clue.

**Comment by mugling** [comment]
No idea. You need to practice git offline (or against your own repo) ~50% of your PR's are never merged due to closure by yourself

**Comment by BorkBorkGoesTheCode** [comment]
Understood.

**Comment by mugling** [comment]
You're still issuing notifications as this is repeatedly updated. Please work it out a local branch and then push it

**Comment by BorkBorkGoesTheCode** [comment]
I just did

**Comment by mugling** [comment]
It's still broken

**Pull request closed without merging**
