### PR TITLE
Add new MGOAL_CONDITION mission goal

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: Features "Add new MGOAL_CONDITION mission goal"

#### Purpose of change

Add a new mission goal which allows specifying conditions for mission completion in the JSON definition for the mission, utilizing the same infrastructure and conditions as the dialogue conditions.

#### Describe the solution

* cac89ee - update the conditions code to support a templated context for evaluating conditions
* 4d98d88 - extract that code to it's own set of files
* de92bb3 - add a new mission goal, JSON attribute, and associated code to missions to allow evaluating a JSON-specified condition 
* e261ff7 - add a new mission using the functionality

#### Additional context

There are two conditions that are evaluated in the context of a dialogue that will evaluate to false right now regardless of context when evaluated for a mission:
* `has_reason` - in a dialogue this would be set by another effect, but I don't see a way this would make sense in the context of a mission goal condition right now, and so `reason` is not set to anything
* `is_by_radio` - mission completion doesn't currently have any context for how the player is interacting with the NPC, it just passes along the NPC ID to evaluate. For now, this will always return false.

I added a new mission `MISSION_PROVE_YOU_ARE_A_SURVIVOR` which uses the `days_since_cataclysm` condition to assert that the player has survived some amount of time  (10 days) after the cataclysm. However, that condition doesn't really work correctly--it's comparing the days to the `calendar::turn`, which means that with our updated 30 day start, the mission is immediately completable. I think fixing that condition is better left to another set of changes, however.

Overall, this change opens up a big set of conditions for missions so that we can hopefully leverage all the work we've done there for more complicated mission goals without having to write a specific MGOAL type for each of them.

If you haven't seen the conditions, they can be perused in the NPC documentation, but for convenience here's the list again:

#### Dialogue conditions
Conditions can be a simple string with no other values, a key and an int, a key and a string, a key and an array, or a key and an object. Arrays and objects can nest with each other and can contain any other condition.

#### Boolean logic

Condition | Type | Description
--- | --- | ---
`"and"` | array | `true` if every condition in the array is true. Can be used to create complex condition tests, like `"[INTELLIGENCE 10+][PERCEPTION 12+] Your jacket is torn. Did you leave that scrap of fabric behind?"`
`"or"` | array | `true` if any condition in the array is true. Can be used to create complex condition tests, like `"[STRENGTH 9+] or [DEXTERITY 9+] I'm sure I can handle one zombie."`
`"not"` | object | `true` if the condition in the object or string is false. Can be used to create complex conditions test by negating other conditions, for text such as<br/>`"[INTELLIGENCE 7-] Hitting the reactor with a hammer should shut it off safely, right?"`

#### Player or NPC conditions
These conditions can be tested for the player using the `"u_"` form, and for the NPC using the `"npc_"` form.

Condition | Type | Description
--- | --- | ---
`"u_male"`<br/>`"npc_male"` | simple string | `true` if the player character or NPC is male.
`"u_female"`<br/>`"npc_female"` | simple string | `true` if the player character or NPC is female.
`"u_at_om_location"`<br/>`"npc_at_om_location"` | string | `true` if the player character or NPC is standing on an overmap tile with `u_at_om_location`'s id.  The special string `"FACTION_CAMP_ANY"` changes it to return true of the player or NPC is standing on a faction camp overmap tile.
`"u_has_trait"`<br/>`"npc_has_trait"` | string | `true` if the player character or NPC has a specific trait.  Simpler versions of `u_has_any_trait` and `npc_has_any_trait` that only checks for one trait.
`"u_has_trait_flag"`<br/>`"npc_has_trait_flag"` | string | `true` if the player character or NPC has any traits with the specific trait flag.  More robust versions of `u_has_any_trait` and `npc_has_any_trait`.  The special trait flag `"MUTATION_THRESHOLD"` checks to see if the player or NPC has crossed a mutation threshold.
`"u_has_any_trait"`<br/>`"npc_has_any_trait"` | array | `true` if the player character or NPC has any trait or mutation in the array. Used to check multiple specific traits.
`"u_has_var"`, `"npc_has_var"` | string | `"type": type_str`, `"context": context_str`, and `"value": value_str` are required fields in the same dictionary as `"u_has_var"` or `"npc_has_var"`.<br/>`true` is the player character or NPC has a variable set by `"u_add_var"` or `"npc_add_var"` with the string, `type_str`, `context_str`, and `value_str`.
`"u_has_strength"`<br/>`"npc_has_strength"` | int | `true` if the player character's or NPC's strength is at least the value of `u_has_strength` or `npc_has_strength`.
`"u_has_dexterity"`<br/>`"npc_has_dexterity"` | int | `true` if the player character's or NPC's dexterity is at least the value of `u_has_dexterity` or `npc_has_dexterity`.
`"u_has_intelligence"`<br/>`"npc_has_intelligence"` | int | `true` if the player character's or NPC's intelligence is at least the value of `u_has_intelligence` or `npc_has_intelligence`.
`"u_has_perception"`<br/>`"npc_has_perception"` | int | `true` if the player character's or NPC's perception is at least the value of `u_has_perception` or `npc_has_perception`.
`"u_has_item"`<br/>`"npc_has_item"` | string | `true` if the player character or NPC has something with `u_has_item`'s or `npc_has_item`'s `item_id` in their inventory.
`"u_has_items"`<br/>`"npc_has_item"` | dictionary | `u_has_items` or `npc_has_items` must be a dictionary with an `item` string and a `count` int.<br/>`true` if the player character or NPC has at least `count` charges or counts of `item` in their inventory.
`"u_has_item_category"`<br/>`"npc_has_item_category"` | string | `"count": item_count` is an optional field that must be in the same dictionary and defaults to 1 if not specified.  `true` if the player or NPC has `item_count` items with the same category as `u_has_item_category` or `npc_has_item_category`.
`"u_has_bionics"`<br/>`"npc_has_bionics"` | string | `true` if the player or NPC has an installed bionic with an `bionic_id` matching `"u_has_bionics"` or `"npc_has_bionics"`.  The special string "ANY" returns true if the player or NPC has any installed bionics.
`"u_has_effect"`<br/>`"npc_has_effect"` | string | `true` if the player character or NPC is under the effect with `u_has_effect` or `npc_has_effect`'s `effect_id`.
`"u_can_stow_weapon"`<br/>`"npc_can_stow_weapon"` | simple string | `true` if the player character or NPC is wielding a weapon and has enough space to put it away.
`"u_has_weapon"`<br/>`"npc_has_weapon"` | simple string | `true` if the player character or NPC is wielding a weapon.
`"u_driving"`<br/>`"npc_driving"` | simple string | `true` if the player character or NPC is operating a vehicle.  <b>Note</b> NPCs cannot currently operate vehicles.

#### Player Only conditions

Condition | Type | Description
--- | --- | ---
`"u_has_mission"` | string | `true` if the mission is assigned to the player character.
`"u_has_cash"` | int | `true` if the player character has at least `u_has_cash` cash available.  *Deprecated*  Previously used to check if the player could buy something, but NPCs shouldn't use e-cash for trades anymore.
`"u_are_owed"` | int | `true` if the NPC's op_of_u.owed is at least `u_are_owed`.  Can be used to check if the player can buy something from the NPC without needing to barter anything.
`"u_has_camp"` | simple string | `true` is the player has one or more active base camps.

#### Player and NPC interaction conditions

Condition | Type | Description
--- | --- | ---
`"at_safe_space"` | simple string | `true` if the NPC's current overmap location passes the `is_safe()` test.
`"has_assigned_mission"` | simple string | `true` if the player character has exactly one mission from the NPC. Can be used for texts like "About that job...".
`"has_many_assigned_missions"` | simple string | `true` if the player character has several mission from the NPC (more than one). Can be used for texts like "About one of those jobs..." and to switch to the `"TALK_MISSION_LIST_ASSIGNED"` topic.
`"has_no_available_mission"` | simple string | `true` if the NPC has no jobs available for the player character.
`"has_available_mission"` | simple string | `true` if the NPC has one job available for the player character.
`"has_many_available_missions"` | simple string | `true` if the NPC has several jobs available for the player character.
`"mission_goal"` | string | `true` if the NPC's current mission has the same goal as `mission_goal`.
`"mission_complete"` | simple string | `true` if the player has completed the NPC's current mission.
`"mission_incomplete"` | simple string | `true` if the player hasn't completed the NPC's current mission.
`"npc_service"` | int | `true` if the NPC does not have the `"currently_busy"` effect and the player character has at least `npc_service` cash available.  Useful to check if the player character can hire an NPC to perform a task that would take time to complete.  Functionally, this is identical to `"and": [ { "not": { "npc_has_effect": "currently_busy" } }, { "u_has_cash": service_cost } ]`
`"npc_allies"` | int | `true` if the player character has at least `npc_allies` number of NPC allies.
`"npc_following"` | simple string | `true` if the NPC is following the player character.
`"is_by_radio"` | simple string | `true` if the player is talking to the NPC over a radio.

#### NPC only conditions

Condition | Type | Description
--- | --- | ---
`"npc_available"` | simple string | `true` if the NPC does not have effect `"currently_busy"`.
`"npc_following"` | simple string | `true` if the NPC is following the player character.
`"npc_friend"` | simple string | `true` if the NPC is friendly to the player character.
`"npc_hostile"` | simple string | `true` if the NPC is an enemy of the player character.
`"npc_train_skills"` | simple string | `true` if the NPC has one or more skills with more levels than the player.
`"npc_train_styles"` | simple string | `true` if the NPC knows one or more martial arts styles that the player does not know.
`"npc_has_class"` | array | `true` if the NPC is a member of an NPC class.
`"npc_role_nearby"` | string | `true` if there is an NPC with the same companion mission role as `npc_role_nearby` within 100 tiles.
`"has_reason"` | simple string | `true` if a previous effect set a reason for why an effect could not be completed.

#### NPC Follower AI rules
Condition | Type | Description
--- | --- | ---
`"npc_aim_rule"` | string | `true` if the NPC follower AI rule for aiming matches the string.
`"npc_engagement_rule"` | string | `true` if the NPC follower AI rule for engagement matches the string.
`"npc_rule"` | string | `true` if the NPC follower AI rule for that matches string is set.

#### Environment

Condition | Type | Description
--- | --- | ---
`"days_since_cataclysm"` | int | `true` if at least `days_since_cataclysm` days have passed since the Cataclysm.
`"is_season"` | string | `true` if the current season matches `is_season`, which must be one of "`spring"`, `"summer"`, `"autumn"`, or `"winter"`.
`"is_day"` | simple string | `true` if it is currently daytime.
`"is_outside"` | simple string | `true` if the NPC is on a tile without a roof.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
That's a really helpful documentation you've written here.

**Comment by ralreegorganon** [comment]
> That's a really helpful documentation you've written here.

Can’t take credit, others wrote all that—I just reposted it from the docs to provide some more easily available context for what sorts of things this change will enable usage of.

**Comment by AMurkin** [comment]
> I'm not quite sure how you failed to survive AND are talking to me.

Nice.

**Comment by Petethegoat** [comment]
Wow, amazing work.

**Pull request merged**
