### PR TITLE
Clang-tidy check to combine locals into points

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Infrastructure "Enforce use of points as local variables"

#### Purpose of change
For better type safety and code clarity.

Working towards #32017.

#### Describe the solution
Add a new clang-tidy check that looks for pairs (or triples) of local variables that should be merged into `point`s (or `tripoint`s), and automate that conversion.

On average, I think these changes are a substantial improvement; lots of cases where points were being unnecessarily decomposed and recomposed are now performed as point arithmetic directly.

#### Describe alternatives you've considered
Doing some subset of the changes by hand.

#### Testing
Most of the changes are automated, so should be low-risk.

Ran the unit tests.

#### Additional context
I'm expecting some compiler errors from the old clang we support (3.8), so don't merge until that looks good (it's the first Travis CI job).

### CODE REVIEW

**Comment by jbytheway** [comment]
OK, looks like the clang-3.8 issues are now resolved.

**Comment by FeepingCreature** [comment]
Is the `src/mapbuffer.cpp` change and changes like it valid? I thought the evaluation order of side effects in function calls was arbitrary.

I think you need to write it like `tripoint loc{ jsin.get_int(), jsin.get_int(), jsin.get_int() };` to get left-to-right evaluation?

**Comment by jbytheway** [comment]
Thanks for catching that.  Indeed it was a bad change.  Did you see other similar changes?

**Comment by FeepingCreature** [comment]
Didn't notice any on a cursory grepping. I'll keep my eyes open for further crashes. :)

**Pull request merged**
