### PR TITLE
Coffees plural fix

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by illi-kun** [comment]
Nice!

**Comment by Cyrano7** [comment]
@illi-kun I was browsing old PRs earlier and found a comment of yours on https://github.com/CleverRaven/Cataclysm-DDA/pull/13075 and started laughing hysterically cause I know hows serious you are with your tabs and spaces on my PRs. Random but made my night.

**Comment by illi-kun** [comment]
I'm glad you liked it and please don't treat my nitpicking (and probably annoying) comments as acts of attack to you personally (because it's attack to _DAMNED TAAABS!!_ ).

**Comment by Cyrano7** [comment]
I don't mind at all. I can take constructive criticism. Project style is important. We don't want to look like a shoddy operation.

**Pull request merged**
