### PR TITLE
Refactor aiming UI

### PR DESCRIPTION
**Pull request by mugling**
- Refactors in preparation for allowing changing of firing mode from targeting UI
- Only behavioral change is fix for #17764
- Deprecates fake `vehicle_pointer` item

### CODE REVIEW

**Comment by mugling** [comment]
Ready

**Comment by mugling** [comment]
Ready for testing

**Comment by Coolthulhu** [comment]
* Spawn flaming electric car
* Get on the controls
* Empty hands
* Press fire
* Segfault

**Comment by mugling** [comment]
Let me take a look

**Comment by mugling** [comment]
Fixed

**Comment by Coolthulhu** [comment]
Targeting from controls is totally broken - does nothing at all.

**Comment by mugling** [comment]
That's unlikely to be a regression in this PR and probably pre-existing

**Pull request merged**
