### PR TITLE
V-menu style filters for advanced inventory menu.

### PR DESCRIPTION
**Pull request by OzoneH3**
Requested from:  #11215

Just not sure where to put the info text how to use the filter options.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>Just not sure where to put the info text how to use the filter options.

How about the Advanced Inventory help screen?

**Comment by OzoneH3** [comment]
Yeah, don't know. That screen is more about keybindings and it's quite a bit of text.

**Comment by Ishindri** [comment]
Thank you, Ozone!

In the V-menu, when you go into the filter field, the description of whatever item you were looking at is temporarily replaced by the filter instructions.  Could something like that be done with the log field at the top of the advanced inventory menu?

**Comment by KA101** [comment]
Clarify: -pipe,chunk,steel excludes all three?

**Comment by OzoneH3** [comment]
Hmm, it used to but must have been changed. Updated the text.

**Comment by KA101** [comment]
Uh, I didn't know and wasn't sure from the text, so asked--better to get the instructions right on the first try.

**Comment by narc0tiq** [comment]
AFAIK, every comma-separated part is separate from every other part, so
"-pipe,chunk,steel" should mean something like "show me only things that
match 'chunk' or 'steel', but not 'pipe'". I'm not 100% sure if it's an
"or" or an "and".

**Pull request merged**
