### PR TITLE
[WIP] ~ Some "contained": true recipe tweaks.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
This flag could be utilized a lot better than it currently is.

### CODE REVIEW

**Comment by BevapDin** [comment]
The resulting item also spawns in a plastic bag (it should at least, because of the `"contained": true` entry). Without the plastic bag as component, it would give the player a free plastic bag from nothing.

This recipe was used to demonstrated that feature (crafting results can spawn within their default container), or it was implemented for that very purpose, something like this. See #11068.

**Comment by Rivet-the-Zombie** [comment]
Ah, so I see. It still strikes me as odd that it requires a plastic bag to grind up the coffee powder at all.

Perhaps we should remove the contained entry and implement it on other recipes where it would make more sense.

Thoughts?

**Comment by BevapDin** [comment]
> Perhaps we should remove the contained entry and implement it on other recipes where it would make more sense.

Fine with me. It's only used for this one recipes anyway, and coffee powder outside of any container should not be a problem either.

**Comment by kevingranade** [comment]
The idea is that the recipe consumes a container so there's somewhere to
put the resulting item, the alternative is to do something like with
liquids and have the player specify an eligible container to put it in,
loose coffee grounds in one's inventory aren't particularly reasonable.

**Comment by Rivet-the-Zombie** [comment]
>loose coffee grounds in one's inventory aren't particularly reasonable.

Then it's already a problem, because nothing is preventing this right now.

**Comment by kevingranade** [comment]
There is, and it needs fixing.

**Comment by BevapDin** [comment]
Does that mean all powder things (like flour) should behave that way? If so, all of their recipes should require that container as component as well. (Which btw. creates a heavy dependency, what if the default container is changed?)

Some powder stuff does not spawn with a container at all (e.g. poppy painkiller, cocaine, crack, heroin, poppy sleep, morphine, cement, quicklime, RDX, chitin powder, sand, bone meal, low-grade methamphetamine, incendiary, antifungal drug), how would that work?

In the end, wouldn't it require a `handle_powder` function, similar to the `handle_liquid` function? At that point the two things should be combined into a generic `handle_contained` (or similar) function.

(Note for the implementation: many ammunition items include powder in their material list (aside other materials), it might be better to add a special "POWDER" phase and check that instead of the material type.)

**Comment by Rivet-the-Zombie** [comment]
>Does that mean all powder things (like flour) should behave that way? If so, all of their recipes should require that container as component as well. (Which btw. creates a heavy dependency, what if the default container is changed?)

I'm thinking it would be better implemented the way containers for liquids are currently handled; craft the thing and then get prompted for a container to keep it in.

>In the end, wouldn't it require a handle_powder function, similar to the handle_liquid function? At that point the two things should be combined into a generic handle_contained (or similar) function.

>(Note for the implementation: many ammunition items include powder in their material list (aside other materials), it might be better to add a special "POWDER" phase and check that instead of the material type.)

Yeah, something along these lines.

**Comment by Cat09** [comment]
seems like container choice should be made first (bad planners aside).

**Pull request closed without merging**
