### PR TITLE
Process of adding Whaley's Locations (3 of 9)

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
**[1 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/25070)** - Combines/Renames/Moves/Lints mapgen files most notably in /mapgen/cosmics_additions.

**[2 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/25072)** - Combines/Renames/Moves/Lints mapgen files most notably in /mapgen/parks_recreation & /mapgen/small_town_buildings.

---

**Part 3** - Adds Whaley's official (in-game) mod, "More Buildings" (including: baseball field, daycare, pet store, rest stop, shopping plaza, storage units, thrift store and a veterans of foreign wars store) to the vanilla game.

- Combines Medium Storage Units, Large Storage Units, Baseball Field, Rest Stop, and Shopping Plaza into single files.
- Linted location files.
- Moves locations to \mapgen folder.
- Adds overmap_specials, overmap_terrain, and regional_map_settings info to main files.
- Deletes "More_Buildings" mod.

**This PR is NOT dependent on any other step.**

Discussion for the addition of Whaley's Mods can be found **[here](https://github.com/CleverRaven/Cataclysm-DDA/issues/24932)**.

---

**[4 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/24989)** - Adds Whaley's Zoo (from his "Big Buildings" mod).

**[5 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/24990)** - Adds Whaley's Stadium (from his "Big Buildings mod).

**[6 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/24992)** - Adds the remainder of Whaley's "Big Buildings" mod.

**[7 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/24998)** - Adds Whaley's "City Entertainment" mod.

**[8 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/25000)** - Adds Whaley's "Seedy Spots" mod.

**[9 of 9](https://github.com/CleverRaven/Cataclysm-DDA/pull/25002)** - Adds Whaley's "River Buildings" mod.

### CODE REVIEW

**Comment by cainiaowu** [comment]
It should be marked as obsolete instead of outright delete the whole thing.
Think about those saves you will break.

**Comment by cosmiccoincidence** [comment]
How does one mark it as obsolete?

**Comment by cainiaowu** [comment]
one line in mod info, I am sure they are documented somewhere, search this repo for related PR.

**Comment by cosmiccoincidence** [comment]
Got it, thanks.

**Comment by cosmiccoincidence** [comment]
Just kidding, post office merge was in part 2.

**Comment by cosmiccoincidence** [comment]
Not sure if I should remove "More_Buildings" mod files from json_blacklist or not... Obviously I moved and linted the files from that mod but I didn't remove the mod, only made it obsolete.

**Comment by ZhilkinSerg** [comment]
> Not sure if I should remove "More_Buildings" mod files from json_blacklist or not... Obviously I moved and linted the files from that mod but I didn't remove the mod, only made it obsolete.

You can leave it as as - we will remove this mod later (maybe right before or after `0.D`).

**Pull request merged**
