### PR TITLE
Use %zu for printf-style formatting of size_t values.

### PR DESCRIPTION
**Pull request by mutability**
This is a semi-automated replacement of %d/%i formats with %zu
when the parameter is of type size_t. It was driven by parsing the
warnings generated by PRINTF_CHECKS.

Also fixes one case where a size_t was passed as a width specifier
(this has to be an int)

%zu is specified in C++11 (via C99) so hopefully we are OK with
compatibility there. The alternatives are very ugly (macros embedded
in format strings, or casts everywhere)

### CODE REVIEW

**Comment by illi-kun** [comment]
According to [stackoverflow thread](http://stackoverflow.com/questions/2524611/how-can-one-print-a-size-t-variable-portably-using-the-printf-family), VS2013 doesn't support ```%zu```. I'm sure this is an issue but I think it's better to state it here.

**Comment by mutability** [comment]
VS2013 also doesn't support C++11, does it? My research seemed to indicate that the more recent visual studio versions that supported C++11, also supported %zu.

**Comment by mutability** [comment]
http://stackoverflow.com/questions/15610053/correct-printf-format-specifier-for-size-t-zu-or-iu suggests that VS2015 does support %zu, VS2013 may or may not it's unclear.

What are we targeting?

(VS2013 apparently doesn't support constexpr either..)

**Comment by illi-kun** [comment]
Okay, I've checked ```compiling.md``` and it seems that we targeted on support of VS2015:
> Visual Studio 2015 is required to build Cataclysm.

So you PR is acceptable.

**Comment by Totentag** [comment]
Unintended bugs coming from this. 

image

**Comment by macrosblackd** [comment]
This breaks the Windows release by causing a crash when opening the new inventory UI.

**Comment by mutability** [comment]
What is the Windows release built with?

**Comment by DanmakuDan** [comment]
MXE cross compiles with MinGW, most likely 4.8.2 from #13652.

**Comment by mutability** [comment]
Looks like we might need __USE_MINGW_ANSI_STDIO to tell it to use the standards-conforming *printf not the Microsoft one.

https://stackoverflow.com/questions/25670522/c-program-shows-zu-after-conversion-to-windows

**Comment by DanmakuDan** [comment]
Maybe @narc0tiq can check if the flag is applicable to the build. This issue isn't present on MSYS2/mingw gcc 5.2.0.

**Comment by illi-kun** [comment]
Yeah, I tested these charges with Code::Blocks default compiler in Windows and it woorks fine.

**Comment by illi-kun** [comment]
It seems that this PR needs to be reverted, sorry for this. Is it ok to just push the 'revert' button or we have some more gentle and safe way to do that?

**Comment by codemime** [comment]
Shouldn't we revert the PR until the solution is found? BTW the link that @mutability gave suggests a [quick]fix:

> all you need to do to get all of this standard behavior is either #define __USE_MINGW_ANSI_STDIO 1 before any includes if you use any of the printf functions or ...

**Comment by codemime** [comment]
@illi-kun At the same time.

**Comment by codemime** [comment]
> sorry for this.

That's all right. The side effect wasn't easily predictable.

>  Is it ok to just push the 'revert' button or we have some more gentle and safe way to do that?

Pushing it creates a reverting pull request. I believe that's perfectly safe.

**Comment by mutability** [comment]
So what's the plan for actually fixing the build issue? I can't test the change I suggested, is there an active developer with the same build environment who can test it?

**Comment by narc0tiq** [comment]
I can theoretically run builds of specific commits right in Jenkins itself, but that'd show up as a new build and would probably get grabbed up by the auto-updater, so let's avoid that.

At the same time, I can also just manually run the same commands in its shell and capture the output. If we're suggesting just that extra `#define` (as a CXXFLAGS addon), I'll have some binaries for you in a short while.

**Comment by narc0tiq** [comment]
Okay, here's the wincurses [build log](http://dev.narc.ro/cataclysm/cataclysmdda-0.C-pr19339-build.log) and [binary](http://dev.narc.ro/cataclysm/cataclysmdda-0.C-pr19339.zip) taken by checking out this PR (specifically, commit 7dcb672) and adding `CXXFLAGS='-D__USE_MINGW_ANSI_STDIO=1'` to the build invocation[1].

In my very brief testing, the build is quite unstable; simple things like monsters fighting each other, or eating often (but not always) lead to crashing. This is likely to be the same issue as reported in #19372.

---

[1] Specifically, the invocation was `CXXFLAGS='-D__USE_MINGW_ANSI_STDIO=1' BUILD_NUMBER=pr19339 Platform=Windows Graphics=Curses /www/virt/dev.narc.ro/htdocs/cataclysm/mainline-build.zsh > /www/virt/dev.narc.ro/htdocs/cataclysm/cataclysmdda-pr19339-build.log 2>&1`, which should be identical with a Jenkins invocation except for the additional compiler flag.

**Comment by mutability** [comment]
OK, so if that didn't work, then options are (in rough order of my preference):

1) someone with an environment equivalent to the CI environment (so far that seems to mean @narc0tiq only) does some experimentation and works out how to make it compile with a C++11 compatible printf
2) update the CI environment to a version that supports C++11 properly (e.g. one of the other Windows build methods above which appears to work OK)
3) embed our own printf implementation, e.g. https://github.com/fmtlib/fmt, either everywhere or just on Windows builds. NB: this would also fix the existing positional-args problem too I think.
4) use a macro: `("hey I counted %" PRZU " things", things.size())`
5) forbid use of size_t when formatting: `("hey I counted %d things", (int)things.size())`

Doing nothing here is just delaying the inevitable as there are surely platforms where passing a size_t to %d is a crash bug.

**Comment by codemime** [comment]
The first one appears to be the only viable option.

**Comment by mutability** [comment]
Here's a minimalish test; if you can get that compiling in the CI environment such that it says "vector has 1 elements" when run, then it's probably working.

```
#include <cstdio>
#include <vector>

int main(int argc, char *argv[])
{
    std::vector<int> v;
    v.push_back(1234);
    printf("vector has %zu elements\n", v.size());
    return 0;
}       
```

**Comment by narc0tiq** [comment]
Okay. It just worked. [Here's the binary](http://dev.narc.ro/cataclysm/test.exe).

My command was `ccache /home/narc/mxe/usr/bin/i686-w64-mingw32.static-g++ -ffast-math -Os -Wall -Wextra -fsigned-char -std=c++11 -MMD -c test.cpp -o test.obj && ccache /home/narc/mxe/usr/bin/i686-w64-mingw32.static-g++ -o test.exe test.obj -static` (basically, a stripped-down version of the compile commands for the cata binary).

**Comment by mutability** [comment]
Hm, weird, why is it failing on the full build then..

**Comment by mutability** [comment]
Ok, so it looks like everything goes through vstring_format in output.cpp which has some _MSC_VER-specific magic that invokes _vscprintf_p and _vsprintf_p. I guess that is bypassing the mingw implementation.

The other non-microsoft path uses vsnprintf directly. I wonder if it is simple as dropping the #ifdef _MSC_VER path, can you try turning that ifdef off and using the vsnprintf version?

**Comment by mutability** [comment]
notably:

https://msdn.microsoft.com/en-us/library/1kt27hek.aspx

"Beginning with the UCRT in Visual Studio 2015 and Windows 10, vsnprintf is no longer identical to _vsnprintf. The vsnprintf function complies with the C99 standard; _vnsprintf is retained for backward compatibility with older Visual Studio code."

(presumably also applies to the other _vs*printfs too)

**Comment by narc0tiq** [comment]
That's weird, I wouldn't have thought mingw32/64 would have `_MSC_VER` set. On account of it not being Visual Studio.

Nonetheless, I'll try it out.

**Comment by mutability** [comment]
You may be right, I am not familiar with any of the windows build environments at all..

**Comment by narc0tiq** [comment]
No worries, I've got barely any clue about C++ anyway. Let's just see what happens -- here's [the binary](http://dev.narc.ro/cataclysm/cataclysmdda-0.C-pr19339-b2.zip) and [build log](http://dev.narc.ro/cataclysm/cataclysmdda-0.C-pr19339-b2-build.log).

**Comment by mutability** [comment]
I'm building MXE now and I resurrected my win7 VM so hopefully I can actually test this myself soon

**Comment by mutability** [comment]
Built MXE from current github master (1ba4e8f75d0c5df94bef2fc9e896d37d076c2bf9)
Built CDDA from the point where this PR was merged:

```
$ git checkout 779a385089946bbf576582837c16bc4e0151bf53
$ make -j8 CROSS="~/git/mxe/usr/bin/i686-w64-mingw32.static-" LUA=1 RELEASE=1 LOCALIZE=1 bindist
```

Resulting build _works correctly_

screenshot from 2016-11-21 20-26-13

So I am slightly at a loss here. Can we update the CI environment to the current MXE? Or can you tell me how to build a MXE that matches what the CI environment has?

**Comment by narc0tiq** [comment]
> Can we update the CI environment to the current MXE?

I've tried before, but I kept having interesting problems compiling `isl` (a dependency for something or other). I retried it now to get the error; it reads: `/usr/bin/ld: i386:x86-64 architecture of input file '/home/narc/src/mxe/usr/x86_64-unknown-linux-gnu/lib/libgmp.a(hgcd_step.o)' is incompatible with i386 output` (and the same for basically every other object file it touches). I have no idea wtf is going on with that.

Maybe [this mention in the mxe dependencies](https://github.com/mxe/mxe/blob/master/docs/index.html#L661) to `apt-get install g++-multilib libc6-dev-i386` is relevant, but trying to actually do that leads to [a problem](https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/1365375), as `libc6-dev-i386` is mutually exclusive with `libc6-dev-amd64`, but both are trying to install (with `g++-multilib` bringing in the other one). Thus, the bug as detailed on launchpad. To be fair, the distro isn't Debian, but Ubuntu, and so the dependencies might not be relevant.

Just for laughs, I'm trying it out on another machine, which is basically a completely clean Ubuntu 16.04; we'll see what comes of it.


> Or can you tell me how to build a MXE that matches what the CI environment has?

It's just old -- a `git show HEAD` tells me it's 9582b46246c115137e3a75e670ba195550929f5b. I may or may not have edited `src/lua.mk` to make it grab a Lua 5.2 instead of 5.1, but I believe that's the only change from that commit.

**Comment by mutability** [comment]
My MXE build was on a 16.04 install (upgraded many times) and it "just worked", I didn't have to do anything other than what the COMPILING.md instructions said.

I'll try MXE from the commit you gave, thanks.

**Comment by narc0tiq** [comment]
This machine is screwy because it used to be all 32-bit and at one point had to switch to a 64-bit kernel -- so it's kind of an unholy mix of (mostly) 32-bit userland on a 64-bit kernel. The other one should work better.

Maybe doing a dist-upgrade on the Jenkins machine would be good, too (it's on 14.04, yuck), but those always seem to come with issues, so I'd want to have time to deal with them (not in-between work, as now). I'll probably do it soonish, as I also have a RAM upgrade (2 GB -> 4 GB) coming from Linode. No more 438 days of uptime :)

**Comment by mutability** [comment]
I had to update the libpng download URL as the version referenced had moved, that worked OK.

However ncurses doesn't want to build:

```
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_18189.c:835:15: error: expected ‘)’ before ‘int’
../include/curses.h:1594:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:790: recipe for target '../objects/lib_gen.o' failed
```

Did you do anything to the ncurses build on the CI machine to get it working?

**Comment by mutability** [comment]
Ok! I have a build that shows the problem at last.

**Comment by mutability** [comment]
Results so far:

* Old MXE, vsnprintf: fails
* Old MXE, vsnprintf, -D__USE_MINGW_ANSI_STDIO=1: *works*
* Old MXE, std::vsnprintf: works
* New MXE, all combinations: works

**Comment by mutability** [comment]
Ok, WTF. My test case with -D__USE_MINGW_ANSI_STDIO=1 works, but building CDDA with that still produces a broken binary.

gcc -E says:

```
std::string vstring_format( char const *format, va_list args )
[...]
        int const result = libintl_vsnprintf( &buffer[0], buffer_size, format, args_copy );
```

gcc -dM says:

```
#define vsnprintf libintl_vsnprintf
```

So I think it's actually libintl that is borking things here.

**Comment by mutability** [comment]
I don't see a way to fix this without either a MXE upgrade or dropping localization support in the windows builds.

Old-MXE has a libintl that understands positional parameters but not C99 format specifiers,  and a `__mingw_vsnprintf` that understands C99 but not positional parameters. The only option with the old MXE is to use `__mingw_vnsprintf` and disable localization; this produces a working binary for me (but no localization, obviously)

**Comment by narc0tiq** [comment]
Right, I'm not surprised it's `libintl` poking in; we could try updating just that part of the working mxe, but I'm loath to mess with it because it's so easy to break it.

Maybe I can grab the binaries I'm making on my spare machine and use those; that would give me a working modern mxe with minimal difficulty. They'd be finished already, but I didn't put it in a `tmux` or `nohup` the build process and the ssh connection got lost -- I'll keep a closer eye on it today.

**Comment by narc0tiq** [comment]
Okay, I think copying over the working mxe (built on the other machine) has worked -- I'm running a test build now, and if it works, I'll replace the current (very old) mxe with the new one. I'm surprised there's no `glibc` compatibility issue, but I guess (or, I hope) mxe is meant to be self-contained. If that assumption holds, I'll make it the live build (and keep the old as a backup for at least a week) and we can try putting this back in.

**Comment by narc0tiq** [comment]
Not so successful, then, I've got this from the build process:

```
[...]
ccache /home/narc/src/mxe/usr/bin/i686-w64-mingw32.static-g++ -Wl,-stack,12000000,-subsystem,windows -o cata_test -DRELEASE -DCROSS_LINUX -DGIT_VERSION -DLOCALIZE objwin/crafting_test.o objwin/creature_test.o objwin/erfinv.o objwin/fake_messages.o objwin/gun_aiming.o objwin/iuse_test.o objwin/line_test.o objwin/map_iterator_test.o objwin/melee_test.o objwin/mod_test.o objwin/monster_test.o objwin/morale_test.o objwin/npc_test.o objwin/overmap_test.o objwin/player_test.o objwin/reloading_test.o objwin/reload_magazine.o objwin/rewrite_vsnprintf_test.o objwin/savegame_test.o objwin/shadowcasting_test.o objwin/test_main.o objwin/vehicle_turrets.o objwin/visitable_remove.o ../cataclysm.a -ffast-math -Os  -Wall -Wextra   -fsigned-char -Werror -std=c++11 -MMD  -DLUA -I../src -Wno-unused-variable -Wno-sign-compare -Wno-unknown-pragmas -Wno-parentheses  -static -lintl -liconv -llua -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -L.
../cataclysm.a(npc.o): duplicate section `.rdata$_ZTV12standard_npc[__ZTV12standard_npc]' has different size
../cataclysm.a(mattack_actors.o): duplicate section `.rdata$_ZTV12standard_npc[__ZTV12standard_npc]' has different size
objwin/crafting_test.o:crafting_test.cpp:(.rdata$_ZTV12standard_npc[__ZTV12standard_npc]+0x360): undefined reference to `non-virtual thunk to npc::serialize(JsonOut&) const'
objwin/crafting_test.o:crafting_test.cpp:(.rdata$_ZTV12standard_npc[__ZTV12standard_npc]+0x374): undefined reference to `non-virtual thunk to npc::deserialize(JsonIn&)'
collect2: error: ld returned 1 exit status
make[1]: *** [cata_test] Error 1
make[1]: Leaving directory `/home/narc/src/Cataclysm-DDA/tests'
make: *** [tests] Error 2
```

I didn't get this when I ran the build from the machine mxe was built from, so it's something particular about the Jenkins machine. This is the exact same source tree I'm building at the exact same commit, using the same compilers with the same arguments, so something else in the environment is causing it.

Unfortunately, this is pretty obscure for me, and I'm honestly not even convinced the error is being truthful. In particular, I'm thinking that `cataclysm.exe` built successfully using the exact same object files, so why would `cata_test` have a problem?

If you have any thoughts of what I should investigate, I'm game, but otherwise I'm thinking moving the Jenkins (at least temporarily) to the new host would be a really good idea.

**Comment by mutability** [comment]
I saw the same test build failure here iirc. Let me investigate

**Comment by mutability** [comment]
I got the same test link failure (and a complaint about missing -lpthread) with the "old" MXE but not with the "new" MXE.

Oddly, re-running make didn't show the same failure (just -lpthread), so I wonder if this is a timing/parallelism thing. I ran the first build with -j8

**Comment by mutability** [comment]
nb: the main binary, notably, does _not_ depend on the library, it just links the objects directly

**Comment by narc0tiq** [comment]
Curious. I'm running with -j2, but I'm not getting any complaints about `libpthread` (and a peek at the mxe shows that the library is present). Nonetheless, as I said, I keep not seeing the error on the alternate machine, so maybe what's happening is some build step is dipping into the wrong mxe. I'll check a little deeper.

**Comment by mutability** [comment]
I think the pthread thing may just be that I'm compiling with SOUND=1 for the first time and my environment isn't set up quite right.

**Comment by mutability** [comment]
I have no real idea about this, the old MXE produces strange results and the new MXE works fine here.

**Comment by narc0tiq** [comment]
So I'm working on a new Jenkins and this is funny (but not promising): <http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/Graphics=Curses,Platform=Windows_x64/1/console>

```
In file included from /home/narc/src/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/map:61:0,
                 from src/json.h:10,
                 from src/enums.h:8,
                 from src/visitable.h:9,
                 from src/character.h:4,
                 from src/player.h:4,
                 from src/bionics.cpp:1:
/home/narc/src/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/bits/stl_map.h: In member function 'bool player::activate_bionic(int, bool)':
/home/narc/src/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/bits/stl_map.h:212:56: internal compiler error: in expand_expr_addr_expr_1, at expr.c:7672
       { _M_t._M_insert_unique(__l.begin(), __l.end()); }
                                                        ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:650: recipe for target 'objwin/bionics.o' failed
make: *** [objwin/bionics.o] Error 1
make: *** Waiting for unfinished jobs....
Build step 'Execute shell' marked build as failure
Recording fingerprints
Finished: FAILURE
```

Hooray for `internal compiler error`s.

**Comment by mutability** [comment]
Been a long time now since I saw an ICE..

I did only try a 32-bit build. Let me try a 64-bit build.

**Comment by mutability** [comment]
I get the same ICE with a 64-bit build. Doesn't happen with a 32-bit (i686) build.

**Comment by mutability** [comment]
Actually now that I look at the error, it is a _different_ ICE. Joy.

```
In file included from /home/oliver/git/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/set:61:0,
                 from src/json.h:11,
                 from src/enums.h:8,
                 from src/sounds.h:4,
                 from src/sounds.cpp:1:
/home/oliver/git/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/bits/stl_set.h: In function 'void sfx::do_footstep()':
/home/oliver/git/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/4.9.4/include/c++/bits/stl_set.h:225:56: internal compiler error: in expand_expr_addr_expr_1, at expr.c:7672
       { _M_t._M_insert_unique(__l.begin(), __l.end()); }
                                                        ^
```

**Comment by mutability** [comment]
Getting all sorts of ICEs at different locations depending on the exact compile options (but always in expand_expr_addr_expr_1, at expr.c:7672). 

I do notice this in the Makefile:

```
    # MXE ICE Workaround
    ifeq (${CXXVERSION}, 4.9.3)
      OPTLEVEL = -O3
    else
      OPTLEVEL = -Os
    endif
```

perhaps that problem persists in 4.9.4

**Comment by narc0tiq** [comment]
Ah, hey, that could be exactly it! I'll experiment and report back.

**Comment by mutability** [comment]
Yeah, it seems to work OK here if I set -O3. Beware that the current makefile detection stuff is broken (it looks at the output of "gcc" not "$(CROSS)-gcc)"). I'll put together a patch for that.

**Comment by narc0tiq** [comment]
I'm getting an odd issue where the `x86_64-w64-mingw32.static-g++` is apparently making `i386` object files, leading to `/home/narc/src/mxe/usr/bin/x86_64-w64-mingw32.static-ld: i386 architecture of input file 'objwin/mod_test.o' is incompatible with i386:x86-64 output`. This is really special indeed. Maybe my ccache is ccaching the wrong thing.

**Comment by narc0tiq** [comment]
No, it's not ccache (it shouldn't have been, so I'm not surprised, but bleh). I need to get back to work; I'll come back to this later.

**Comment by patternoia** [comment]
As a bit of offtopic: @narc0tiq since you are deploying a new build server (or upgrading existing), could you please install clang/llvm **v3.8.1**. This will help with linux to mac cross compilation later.

You could very simply install it by cloning [osxcross](https://github.com/tpoechtrager/osxcross) and running `CLANG_VERSION=3.8.1 INSTALLPREFIX=/any/path/here ./build_clang.sh`. By specifying the `INSTALLPREFIX` you then ensure you will not damage the current clang installation.
Let me know what you think about this.

**Comment by narc0tiq** [comment]
Hell, I can do that to the existing build server right now - I have
packages available, only need to install them. Indeed, on the new machine,
I went straight to clang-3.8 because why not?

**Comment by narc0tiq** [comment]
So, I found out that `make clean` doesn't actually clean the `tests/objwin`. Maybe should fix that sometime.

**Comment by narc0tiq** [comment]
@patternoia I seem to have v3.8.0 on the new machine (but I haven't plugged in the clang PPA, which may resolve it by way of package (much preferable)). Is the .1 critical?

**Comment by patternoia** [comment]
Should not be

**Comment by kevingranade** [comment]
Just a project management note, leaving this reverted and trying again
later would be preferable to an invasive workaround, this is a fairly
obscure warning that has very little chance of causing actual problems, and
presumably the underlying projects will have fixes applied in time.

**Comment by mutability** [comment]
What invasive workaround do you mean?

Fixing this particular warning is a necessary step towards fixing _all_ the printf warnings, at which point we can turn on enforcement of those warnings in release builds (or as a separate check step) and avoid future bugs involving a mismatch between format strings and arguments.

**Comment by narc0tiq** [comment]
> invasive workaround

I'm not sure it's that invasive, as it's just trading one set of optimizations for another (and it's fairly narrowly targeted at mingw64's x86_64 build target only). We can always narrow it further if someone needs it, but it's more likely mingw64 will update their gcc first... in a couple more years.

**Comment by mutability** [comment]
The -O3 thing is just keeping an existing workaround intact with the new
version of gcc, isn't it?

**Comment by narc0tiq** [comment]
Yeah, but with #19440 it's targeted on mingw64 entirely -- which it probably needs, at least for now. Eventually, it'll be unnecessary and we can remove it altogether, I hope.

**Comment by mutability** [comment]
Are we building with anything other than gcc 4.9.3 / 4.9.4 for x86_64-w64-mingw32.static? I thought the answer to that was "no"

**Comment by mutability** [comment]
It would be useful if Kevin can clarify what he means too because I don't understand what the issue is - the ICE has nothing to do with this PR and you need it anyway?

**Comment by kevingranade** [comment]
I was referring to these options:

   1. embed our own printf implementation, e.g.
   https://github.com/fmtlib/fmt, either everywhere or just on Windows
   builds. NB: this would also fix the existing positional-args problem too I
   think.
   2. use a macro: ("hey I counted %" PRZU " things", things.size())
   3. forbid use of size_t when formatting: ("hey I counted %d things",
   (int)things.size())

If it's a targeted fix in the build system my only concern is it being a
time sink,  but that's up to the people involved to decide.

**Comment by mutability** [comment]
Yeah, agreed that none of those solutions are particularly good; fixing the CI environment is the way forward.

**Pull request merged**
