### PR TITLE
[Xedra Evolved] Add more fae bans for post-threshold Paraclesians

### LINKED ISSUE #70993: Paraclesian broke fae ban throws an error due to double definitions / Xedra Evolved
### Describe the bug

Game throws an error since last update on experimental with Xedra Evolved active about a double definition.

It seems to be defined in:
1. "paraclesian_eocs.json"
2. "paraclesian_fae_bans.json"

### Attach save file

Happens even with only DDA and XE active, so not needed?

### Steps to reproduce

Activate XE and try to load/create a character.

### Expected behavior

Game loads.

### Screenshots

image

### Versions and configuration

Cannot generate one for that specific problem, as I don't get in game without meddling. 

### Additional context

Game starts if one of the two definitions are removed.

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved] Add more fae bans for post-threshold Paraclesians"

#### Purpose of change

Stories about the Fair Folk are full of them being weird and doing bizarre things because they're following odd rules that constrain their behavior. The ability to mod that is limited, but if you're playing actual fae you should have some sort of limitations as you get less and less human.

Also fixes #70993

#### Describe the solution

Add some more bans for the fae, following Arvore not being able to chop down trees. Breaking them causes pain (sometimes), causes a big morale hit, reduces maximum mana and mana regeneration, and causes stat penalties. The duration is several days. 

Arvore: Cannot sleep within the bounds of a city or in a populated area (faction camps excluded).
Ierde: Must sleep underground on natural earth or stone. Cannot use tools to dig or mine the earth (this will be gated behind their earth-moving magic once I write that).
Homullus: Must not slay a human (including ferals--use your fae magick to deal with ferals).
Salamander: Cannot get wet (their heat endurance traits should prevent them from sweating and triggering it that way).
Sylph: Cannot sleep indoors. Cannot spend more than an hour at a time underground (I'll gate this second one behind their ability to fly once I let them fly). 
Undine: Must sleep underwater. 

Will add more as I think of them.

#### Testing

Each condition works.

#### Additional context

Salamanders currently get one stack of Broken Ban _per wet bodypart_. The means I used to try to limit that (give them an effect that prevented them from getting more than one stack) prevented them from getting it at all. I'm not sure if there's a good rate limiter for EoCs.

### CODE REVIEW

**Comment by Maleclypse** [comment]
I wonder if sylph can be banned from sleeping on any tile flagged INSIDE?

**Comment by Standing-Storm** [comment]
> I wonder if sylph can be banned from sleeping on any tile flagged INSIDE?

There's a `u_is_on_terrain_with_flag` condition so I can easily add that!

**Comment by Standing-Storm** [comment]
What's your opinion on Homullus killing ferals? Should it fall under their ban so they have to use their magic to get around liking them (I’m leaning this direction)?

**Comment by Maleclypse** [comment]
> What's your opinion on Homullus killing ferals? Should it fall under their ban so they have to use their magic to get around killing them (I’m leaning this direction)?

I agree with you 100%.   And at a higher end ban, kill nothing that in the shape of a thinking mind.  So demihumans and mi-go would be off list to.  I'm not sure how higher level bans will work but I figure they'll be pre-reqs for the highest/most powerful abilities.

**Comment by Standing-Storm** [comment]
> I'm not sure how higher level bans will work but I figure they'll be pre-reqs for the highest/most powerful abilities.

Yeah, I should be able to key them off the Threshold and other abilities too. That's currently how the Undine ban works (they only have to sleep underwater once it's possible for them to sleep underwater)

**Comment by Standing-Storm** [comment]
image

**Comment by Rokharn** [comment]
> cut_tree event so that post-Threshold Arvore cannot cut a tree down without suffering pain, a morale hit, and a stacking debuff 

How about to add some a slightly less terrible taboo for Arvore as well for killing peaceful forest animals like rabbits, hares, squirrels and so on, maybe non mutated birds too?

For Salamander it can be actions of 'killing fire' like: extinguish fire (campfire, candle, ets), use fire extinguisher. 

For Undine it can be for killing peaceful water animals like waterstrider, frogs (non mutated ones), maybe some waterfowl birds include pesky goose.


> Undine: Must sleep underwater.

Nearly impossible at the winter.  Maybe just a 'nearly water' at least, like the one for spell exp?

**Comment by Standing-Storm** [comment]
> For Salamander it can be actions of 'killing fire' like: extinguish fire (campfire, candle, ets), use fire extinguisher.

I can do use fire extinguisher, but it doesn't look like "extinguish a fire" is a checkable activity.

> > Undine: Must sleep underwater.
> 
> Nearly impossible at the winter. Maybe just a 'nearly water' at least, like the one for spell exp?

Huh? I just checked and rivers and ponds etc. don't freeze in winter. There shouldn't be a problem if Undines are near a water source.

**Comment by Standing-Storm** [comment]
Undine aren't currently immune to cold while underwater, but they will be. And they already have a trait that makes it easier for them to fall asleep when they're underwater, so once they have all that, they should be fine. 

The "your wounds are closing!" message is hardcoded IIRC and there's no way to remove it or suppress it, unfortunately.

**Comment by Standing-Storm** [comment]
Redrafting as I try to remove an error message that pops up when Ierde mine or dig into the Earth (the actual ban is appropriately applied, but there's an error message)

**Pull request merged**
