### PR TITLE
Added new allergen flags and updated carnivore blacklist 

### PR DESCRIPTION
**Pull request by fyhannes**
#### Summary
Features "Added allergen flags for cheese, dried vegetables, and bread"

#### Purpose of change
#66649 Currently, carnivores can eat anything that has egg or milk since they've been whitelisted in `set_allergy_flags`. Also, materials such as "dried_vegetable", "cheese", and "bread" do not have allergy flags defined, nor are they accounted for in the carnivore and vegan blacklist. This means that food made out of bread could be consumed by carnivores and food made out of cheese can be consumed by vegans.

#### Describe the solution
Added the respective flags and updated the blacklists to account for these new allergens. Removed { material_egg , flag_CARNIVORE_OK }, and { material_milk, flag_CARNIVORE_OK } since the inclusion of such flags can inadvertently allow any carnivore to eat any item as long as its material is composed of egg or milk.

#### Describe alternatives you've considered
None

#### Testing
Steps: Debug Carnivore and try to eat Caviar and Egg. 
Expected Result: Player should be unable to consume Caviar and Egg.

### CODE REVIEW

**Comment by Maleclypse** [comment]
So egg is in fact a major food for many carnivore species, such as snakes.   Snakes are obligate carnivores.  Milk sure remove that from obligate carnivores though not all obligate carnivores are lactose intolerant.

**Comment by fyhannes** [comment]
```
{ material_milk, flag_CARNIVORE_OK },
{ material_egg, flag_CARNIVORE_OK },
```

I assume you're referring to the removal of these two flags above. The reason I removed it was because any food such as [Caviar and Egg t](https://github.com/CleverRaven/Cataclysm-DDA/blob/7920ed62f2b05e29248a943faeb94f7f8f54ba46/data/json/items/comestibles/egg.json#L979) that is made out of "bread" and "egg" should not be edible by carnivores, but the flag `{ material_egg, flag_CARNIVORE_OK },` will allow the Caviar and Egg to be eaten. To generalize it, as long as any food contains `milk` or `egg`, it doesn't matter what other materials it's made out of because the carnivore can eat it. You can test it by trying to eat [buttered_toast](https://github.com/CleverRaven/Cataclysm-DDA/blob/7920ed62f2b05e29248a943faeb94f7f8f54ba46/data/json/items/comestibles/bread.json#L261) or [buttered_toast_wheat_free](https://github.com/CleverRaven/Cataclysm-DDA/blob/7920ed62f2b05e29248a943faeb94f7f8f54ba46/data/json/items/comestibles/bread.json#L271) as a carnivore (without my changes). The alternative could be to just edit the json entries for each of these food types but I don't think it's future-proof.

Unless I'm mistaken, isn't the point of `set_allergy_flags` to assign allergens to specific food types? If that's the case, then removing `{ material_milk, flag_CARNIVORE_OK },` and `{ material_egg, flag_CARNIVORE_OK },` shouldn't be an issue because they aren't in the [carnivore_blacklist]({ material_milk, flag_CARNIVORE_OK },
{ material_egg, flag_CARNIVORE_OK },) and the carnivore_blacklist is what really controls the carnivore's diet.

**Comment by dseguin** [comment]
Doesn't look like the new allergens are being added to any food items, which I'm pretty sure means that eating bread with a bread allergy does nothing. Are you planning to add those in a follow up PR?

**Comment by fyhannes** [comment]
Is that not what `set_allergy_flags` is for?

**Comment by dseguin** [comment]
You're absolutely right, sorry for doubting :+1:

**Comment by fyhannes** [comment]
No worries! I'm happy to have other eyes on this.

**Pull request merged**
