### PR TITLE
Wood panels - a new major construction component

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
 ```SUMMARY: Content "Adds wood panels for construction, a component for many existing recipes."```

#### Purpose of change
Currently 2x4s stand in for all types of wood construction. This is a bit silly as many constructions require other shapes of wood. Too much granularity isn't great, but we should have something to represent long flat panels of wood as opposed to narrow thick planks

#### Describe the solution
Adds `wood_panel`, an item that represents assorted smaller pieces of flat wood, and `wood_sheet`, a full sized sheet of plywood

Wood panels can be obtained in most of the same places as 2x4s: through furniture or terrain deconstruction, raiding lumberyards, etc. They are harder to pack around than 2x4s. Wood sheets are even harder to pack around, can be cut down into wood panels, and are only really found at job sites and lumberyards. For now they're basically just a way to get wood panels, although they can be used in wood wall construction. Eventually wood sheets will probably get some unique uses. Also, now that you're not building wooden walls out of 2x4s, it's faster to build wood walls.

- [x] Create wood panels, move 2x4 and other wood types to a new item definition file
- [x] Add wood panels to many appropriate construction recipes
- [x] Add wood panels to many appropriate terrain bash/deconstruct results
- [x] Add wood panels to appropriate furniture bash/deconstruct results
- [x] Add wood panels to appropriate item groups

I do not think I've gotten even close to all the things that should spawn wood sheets/panels nor use them. I will try to add a few more this PR but if not I (and I'm sure others) will continue adding them to places now that they exist.

#### Additional context
This is preparation for adding flat-pack furniture kits, which will depend on wood panels. However these are big enough of a change to merit their own PR and really should have been in some time ago.

### CODE REVIEW

**Comment by curstwist** [comment]
quick review of construction.json

Not sure how you reasonably get a panel from chopping down a tree.

walls/pony walls: 1 panel, seems like it should be 2 (1 per side)
coffin/closed: 2 panels. I'd suggest at least 3 so one can be used for sides (or also require 2x4s)
bookcase: 1 panel, but also need 2x4s for shelves? or more panels...
cupboard: see book case

**Comment by I-am-Erk** [comment]
For some of those  it's really a saw that's needed rather than more panels. I'll add one or the other

**Comment by faefux** [comment]
One little thing: I have serious doubts that a sheet of ply is going to survive a bashing. It'd likely leave splintered wood, etc.  Happy to be proved wrong though.

**Comment by I-am-Erk** [comment]
A wood panel can be any of a wide range of sizes, so something useful as a panel could indeed survive bashing. You'll notice the chance of getting one is pretty much always 50% or lower. Plus, don't forget bashing may not represent tearing something to shreds. Kicking a door in is also bashing, so is tearing it off its hinges, or breaking the legs of a table.

**Comment by TechyBen** [comment]
Some desks would too, right?
PS, I really should get on modding in foldable chair/table to pipes sheet disassembly for my survival characters. XD

**Comment by I-am-Erk** [comment]
Jenkins Rebuild

**Comment by BenlyAZ** [comment]
With this change an integrated toolset is no longer sufficient to build a table. If wood sawing 2 is going to be mandatory for construction involving wood panels the integrated toolset should probably be upgraded to match (it is described as including a wood saw, after all.)

**Pull request merged**
