### PR TITLE
Update recipe_weapon.json

### PR DESCRIPTION
**Pull request by LiGIAOTPA**
<<makeshift_knife,copper_knife , switchblade,rapier,estoc,knife_steak,naginata>>these weapon now belong to cutting subcategory in recipe :)
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/21369

### CODE REVIEW

**Comment by BrettDong** [comment]
```
19:15:52 +/tmp/CommandInterpreterCondition4065236141232869869.sh:6> diff --unified /var/lib/jenkins/cataclysm-reference-repo/Makefile Makefile
19:15:52 diff: /var/lib/jenkins/cataclysm-reference-repo/Makefile: No such file or directory
19:15:52 +/tmp/CommandInterpreterCondition4065236141232869869.sh:8> exit 0
19:15:52 Run condition [Execute Shell] enabling perform for step [Set the build result]
19:15:52 Setting result to [Aborted]
19:15:52 Build step 'Conditional step (single)' changed build result to ABORTED
19:15:52 Build step 'Conditional step (single)' marked build as failure
```
@narc0tiq What's the problem in the CI?

**Comment by narc0tiq** [comment]
> What's the problem in the CI?

The reference Makefile went missing, which happened when the main build failed to fetch from Github: http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/6563/console and http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/6564/console .

I might be able to make the pull request builder stop when the mainline build fails, but then it's not going to care why the main build failed; maybe the mainline build shouldn't clear out the workspace... I'll figure something out.

**Comment by narc0tiq** [comment]
I've got it cleaning only the sub-jobs' workspaces for now; that should ensure the Makefile doesn't go walkabout anymore, but might cause other issues (I'm not sure what; I just remember possibly running into some problems with this setup before). We'll try it out for a while -- if it breaks, someone ping me.

**Comment by narc0tiq** [comment]
Oh, and: **Jenkins, rebuild** this please.

(boldface not required, actual regex is `.*jenkins,?\W+rebuild.*`, case-insensitive)

**Pull request closed without merging**
