### PR TITLE
Arcana: fixes/rebalancing from archived repository

### PR DESCRIPTION
**Pull request by DangerNoodle**
This implements no new content, presently only balancing and other alterations from the repository being maintained by @Chaosvolt.

The main change appears to be changing the martial art overrides to avoid any future changes to the affect arts causing issues, by implementing use of `copy-from`.

Additionally, several mapgen entries retained the defunct use of 'place_items' instead of the current use of 'place_loot'. That has now been corrected.

There was also one apparent typo fix along with a few alterations to professions, recipes, and tools.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Good. I'll look at what you ported over and explain my reasons for why I added the

* Martial art fix: You've already explained this one, and you wrote it up to begin with. Futureproofing.
* Typo fix: Scrolls of darkness were originally called scrolls of mysticism, and one instance of the old name was retained. Derp. :V
* Profession changes: Balancing. Mask of insight makes hammer useful for its actual effect, scribe and summoner are ill-fitted for a dangerous scenario, while Dark Priest was intended to start with a symbol of judgement.
* Recipe changes: Lore. The Six Pillars and History of Alchemy are present in the Cleansing Flame's book list, so letting them make the relevant items with dull essence is logical.

**Comment by DangerNoodle** [comment]
Understood. As I am not implementing your addition of basement mapgen entries, I will hope that these additions are deemed acceptable.

**Comment by chaosvolt** [comment]
In the meantime, I'm mucking about with a map item to add to my repo eventually. Planning to have it map out the arcane structures, strange temples, and strange cabins.

Dunno where to make it spawn, but probably high odds in arcane structures so players that conquer one structure have an edge on finding others.

**Comment by DangerNoodle** [comment]
Discovery, arcane ranged weapons are only reloading 1 at a time.

**Comment by DangerNoodle** [comment]
Oh. It would appear that reloading of non-magazine weapons is broken.

**Comment by chaosvolt** [comment]
...eh. How bad is it, a mL per essence? Mess with it if you want, but shouldn't really hurt anything.

Weapons being broken in general is a more pressing concern. I fear that it, like the stair issue, will go unfixed for a good while.

**Comment by chaosvolt** [comment]
Also to fix: curious structure uses old "place_items" instead of place_loot.

**Comment by chaosvolt** [comment]
Updating my repo now. If you do copy these fixes for this, double-check and remove references to 'arcanemap' since that is a new item, and this is for fixed stuff only. :V

**Comment by DangerNoodle** [comment]
Thank you. I will have to add this when I am able to in the morning.

**Comment by DangerNoodle** [comment]
Apologies for the delays. Implementing fixed mapgen entries now. Note that you have an excess separator in 'mapgen_sanguine.json', the 'place_loot' entry where you added 'arcanemap'. Since I had to remove this loot spawn, the separator error is thus fixed on my end.

**Comment by chaosvolt** [comment]
Doh. Got it, fixed on my end now.

**Comment by mugling** [comment]
`copy-from` support for many of these JSON types was lost when the PR implementing them was later reverted. Any further changes to this mod are best made in the relevant third-party repo.

**Comment by DangerNoodle** [comment]
Then what method is used instead of copy-from?

Closing this does not provide anything productive, I still would want to fix up the main version of the mod.

**Comment by chaosvolt** [comment]
@mugling, what is your problem?

**Comment by DangerNoodle** [comment]
Tell me what fixes are broken, and I can replace them with functional fixes and re-open, allowing Chaosvolt to fix it in their repository as well.

Closing the pull request because of feature breakage is not the ideal solution.

**Comment by chaosvolt** [comment]
Requesting @Rivet-the-Zombie to confirm whether Mugling's claimed reason for closing this is valid.

**Comment by chaosvolt** [comment]
I just tested my repo of Arcana with the latest available build, 5946. No load errors, and martial arts replacements still work as expected, and monsters are still edited to drop essence/items. As those are the only uses of copy-from in the mod, Mugling is either lying or acting in ignorance. Either way, he is not justified in closing this PR.

@DangerNoodle, re-open this.

@mugling, don't start closing stuff unless you have a valid reason.

**Comment by DangerNoodle** [comment]
@chaosvolt I am unable to re-open.

**Comment by Coolthulhu** [comment]
For as long as we support a mod, we should allow fixes like that.

We don't have the full mod support up yet (ie. stable isn't out), so we should keep it up at least until that stable. We can do giant cleaning after the stable is out. Or as one of the last PRs before stable.

Keeping a broken mod in repo is the worst option possible.

**Comment by chaosvolt** [comment]
Thank you.

**Comment by mugling** [comment]
> The main change appears to be changing the martial art overrides to avoid any future changes to the affect arts causing issues, by implementing use of copy-from.

This doesn't actually do anything as `copy-from` isn't yet supported for martial arts. Support was reverted out in #19137.

> For as long as we support a mod, we should allow fixes like that.

This mod is horrible to support. The previous maintenance PR ended with a rebuke from a different developer. I'm going to mark this mod as `obsolete` which means the mod will still load but new games will need to be started using the version distributed from the third-party repo. Significant bugs can be PR'd to the core repo until it is deprecated but any extension needs to take place in the third-party repo.

**Pull request closed without merging**
