### PR TITLE
More feedback about food's relative age and spoil progress.

### PR DESCRIPTION
**Pull request by nexusmrsep**
**What does it do?**

This PR introduces **new feedback information for the player, who wants to know how old is his/her food**.

**Racionale:**

Discussion under PR #23986 led to new ideas, one of which is need for more options to preserve food.
However, even with existing options (fridges, ice labs, winter), you don't know how old is your food, as it can spend weeks frozen without aging too much, so present information about how long it will last in **room temperature** (which is **default**) quickly gets irrelevant.

Drop your food in the fridge, or survive winter with a bunch of perishable comestibles, and you end up with no true knowledge of what to expect of your food's further life expectancy.

Although it shows as _food (old)_ in last stages of its life, but that is not enough when managing your food supplies in the long run.
In this manner, I belive there is strong need to give the player a way to evaluate food's state - is it fresh? Is it past its best days, but still long before rotting? Etc.

This extra info (combined with default spoil time) will be much more important if PR #23986 gets merged. For long lasting, but perishable food it is crucial to discern food's effective age, on a relative scale from fresh to rotten.

**For example:** you should be able to distinguish between week old pasta, fresh as new, and a half-year old pasta, somewhat aging, but still in its prime.

**Implementation:**
- information is relayed by examining food, under existing information about its default life-expectancy
- player has to be a decent cook or more then decent survivalist to properly evaluate food's age, if not -he is given standard info (default life expectancy in room temperature, (old) suffix, as is now)
- feedback is divided in five tiers by percentage 10|20|20|20|20|10 (sum=100 %), each with a different description given to the player; _side note: functions for lower and higher 10% were already coded for rudimental `relative_rot` queries._
- there is no extra feedback if food is already `rotten`, as this information is diplayed sufficiently to the player.

### CODE REVIEW

**Comment by Granitecosmos** [comment]
I really like this idea. Not perfect information with remaining days or hours which could be unrealistic, instead a more basic system that's still good enough to help a lot.

**Comment by NickGrease** [comment]
Will other places, like inventory/adv inventory display the 'tiers' in some way (color/words), or will you always have to examine the individual food items to get the 'better' information?

**Comment by nexusmrsep** [comment]
> Will other places, like inventory/adv inventory display the 'tiers' in some way (color/words), or will you always have to examine the individual food items to get the 'better' information?

Not in this PR, but i will write it down in my "todo/think about" list.

**Comment by mlangsdorf** [comment]
advanced inventory already has an option to sort by spoilage, and I would hope that this PR wouldn't impair that functionality.

Ideally, a sufficiently skilled survivor should be able to open up the advanced inventory on his minifridge, sort by spoilage, and distinguish between the fresh milk he milked that morning (nominal spoilage time 24 hours, effective spoilage time sometime next week) and the sugar beets he put in there at the start of the game (nominal spoilage time 1 season, effective spoilage time tomorrow).

**Comment by Night-Pryanik** [comment]
A screenshot would be helpful.

**Comment by nexusmrsep** [comment]
@mlangsdorf Yes it does, and: [1] its sorting method is accurate and based on true age not default spoil time, [2] it's not colliding in any way with this PR, [3] so in the end I believe its working exactly as you said in your example.
The only difference is that it only sorts, but doesn't give more precise info outright. But with this PR you can [e]xamine food from the adv. inventory to get to those details.

@NickGrease since this feature, as mentioned by @mlangsdorf, already exists, and in my opinion it works fine code-wise, i think I won't alter it in any way. Since you can [e]xamine items from within sorted pile you will have all needed info at hand's reach, without introducing too much clutter.

@Night-Pryanik screenshot of what?

**Comment by Night-Pryanik** [comment]
Screenshot of how does it look like ingame.

**Comment by NickGrease** [comment]
@nexusmrsep Yes. after thinking about it, adding 6 more colors or words to food would be overkill (UI wise).

**Comment by nexusmrsep** [comment]
### **First three are from "examine item" - with different age = different feedback:**

image

image

image

### **Last one is from adv. inventory, with sorting by spoilage, and examining within this mode.**
**This one is equal as the last one, but I also thrown in some fresh pizza to show sorting.**
**Right column displays [e]xamine results for older pizza within adv. inventory.**

image

**Pull request merged**
