### PR TITLE
Astyle 3.1 fix on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by OzoneH3**
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```
```
apt-cache show astyle
Package: astyle                                                                                                                                                                                                                               
Architecture: amd64
Version: 3.1-1ubuntu2
Priority: optional
Section: universe/devel
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matteo Cypriani <mcy@lm7.fr>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 756
Depends: libc6 (>= 2.14), libstdc++6 (>= 5.2)
Suggests: xdg-utils
Filename: pool/universe/a/astyle/astyle_3.1-1ubuntu2_amd64.deb
Size: 198728
MD5sum: 453e993671d9970e2dbe79a1002ec0ce
SHA1: 7f9a86360c9a33dc0fb57865f691eac5827f9547
SHA256: 3d193d61aa3d7b274451888007459e2445e56a5ecfc50d5e07d4739fc4549ef6
Homepage: http://astyle.sourceforge.net/
Description-de: Quelltextformatierer für C, C++, Objective-C, C# und Java
 Artistic Style »verschönert« Quelltexte in den Programmiersprachen C, C++,
 C++/CLI, Objective-C, C# and Java durch Einrücken und Neuformatierung.
 .
 Dieses Paket enthält das Befehlszeilenwerkzeug.
Description-md5: 8df5aba4629c6ca17e967f878cb634ad
```

Lets see what Jenkins has to say to this.

### CODE REVIEW

**Comment by OzoneH3** [comment]
Nope, seems like Jenkins does not agree...

```
13:24:25 astyle regressions found.
13:24:25 Formatted  src/iuse.cpp
13:24:25 Makefile:970: recipe for target 'astyle-check' failed
```

**Comment by OzoneH3** [comment]
Changed && to & so everybody should be happy.

**Comment by ZhilkinSerg** [comment]
It totally makes no sense to use && here and I would even suggest changing it to `const auto & pt`.

C++11 allows to modify rvalue defined with `&&`, but `pt` is not modified and only passed as first argument to `add_field` function which takes `const tripoint &`.

image

**Comment by ZhilkinSerg** [comment]
I guess that was a typo in #13121, maybe @Coolthulhu remembers more.

**Comment by ZhilkinSerg** [comment]
On the other hand there are several places through the code with similar constructions:

https://github.com/CleverRaven/Cataclysm-DDA/blob/a593644c490aceeb21da58361d73ad4ecc6d8132/src/game.cpp#L9334

https://github.com/CleverRaven/Cataclysm-DDA/blob/a593644c490aceeb21da58361d73ad4ecc6d8132/src/character.cpp#L452

Maybe it makes some sense after all?

**Comment by Coolthulhu** [comment]
That `&&` was my error, I don't think anything will break if you change it to regular `const &`.

**Pull request merged**
