### PR TITLE
Add recipe for deck of cards

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add recipe for deck of cards"

#### Purpose of change
Provide an easily craftable source of entertainment that also doesn't need electricity to work.

#### Describe the solution
Add recipe for the deck of cards, as it seems like the simplest "game" item of all the others.

#### Describe alternatives you've considered
Coming up with something even simpler that could qualify as a game, though at some point you could just not use any equipment for it at all.
Adding paper as a possible alternative to cardboard, but that may make too flimsy cards.

#### Testing
Launched the game, made sure that no errors happen.

#### Additional context
None.

### CODE REVIEW

**Comment by Fris0uman** [comment]
could you make that a makeshift deck of card? It's weird that drawing on carboard produce a pristine factory-made deck of card.

**Comment by AtomicFox556** [comment]
> could you make that a makeshift deck of card? It's weird that drawing on carboard produce a pristine factory-made deck of card.

Done.

**Review by Maleclypse — APPROVED** [review]

**Comment by Termineitor244** [comment]
@Maleclypse from what I'm seeing, the test errors of this PR are not related to the changes made (test_tool_belt_pocket_mix is causing failures, but I think this was an old error that was affecting all PRs before). Could you restart the tests or maybe rebase the PR on master so the PR can be merged?

**Comment by AtomicFox556** [comment]
Build passed now. Apparently it indeed was random.

**Pull request merged**
