### PR TITLE
[WIP] UI code and appearance update

### PR DESCRIPTION
**Pull request by Kelenius**
#### Summary
```SUMMARY: Interface "Changed UI layout"```

#### Purpose of change
I'm going to make a stab at the current UI issues floating around. This PR is an alternate to #27809.

I didn't actually get around to the redesign yet - currently, there are only back-end changes that break down code into separate functions. This makes moving items around much easier and, I think, is a first step to JSONing the UI if it ever comes to that.

The next step would be to change how UI looks, you can see a mock-up below.

#### Describe the solution
This is the layout that was generated from brainstorming in Discord:
```
MMMMMMM HEAD  |||||  Distressing Pain  Str 11
MMMMMMM LIMB1 |||||  Really hungry     Dex  9
MMMMMMM LIMB2 |||||  Super thirsty     Dex  9
MMMMMMM LIMB3 |||||  Very tired        Dex  9
MMMMMMM LIMB4 |||||  Focus: 999   ^W^    SAFE
MMMMMMM LIMB5 |||||  Scorching Hot (Rising!!)
MMMMMMM Pwr 1111111  Spd 120 120 W  Stm |||||
[Location]                         [   *   ]
[Season], day 22, 23:59:59             ( | )
Rainy Thunderstorm                     -23 C
[Lighting]                        Sound: 234
[Wielded]                             [Style]
```
However, I'm still trying to figure out the best way to put vehicle info into it. I will probably not touch the wide sidebar, because I've never used it and I'm not sure what would be better.

### CODE REVIEW

**Comment by Treah** [comment]
Remember to retain both the types of mood indicator here instead of preferring one over the other some users like the :) rather then the ._. versions. I don't think you intend to only keep one but it was what was in your mock up so.

**Comment by I-am-Erk** [comment]
I have to admit I kinda like the ||||| bars being together in principle, except for stamina being hard to distinguish. I wonder if it could be put there but made blue instead of green.


Really this should probably be jsonized somehow.

**Comment by curstwist** [comment]
Will it keep that tiny upper left corner mini-map?  Love that thing for night raiding.

Like to add encouragement for the emoji/mood indicator to be more prominent.  It is the bit of information that helps a player feel more connected to their character.  All the new designs tend to make it feel like an afterthought while I consider it to be more like the soul of my character.

On I-am-Erk's comment, a color change would be good if it returns back to nsklaus' position under the legs.  I was thinking of a pixel wide bar separating it from the legs too, but that requires more space so....

**Comment by KITbutler** [comment]
- Weather and lighting need some consideration as both have a display value of "cloudy". Labels are an option, or the terminology could be changed to eliminate ambiguity.

- Especially if we are grouping things into movable panels or JSON sub-blocks I would group weather, lighting, temperature, sun and moon into one block if geometrically possible.

- For large screens the best place for vehicle info would be an overlay panel obscuring the oldest messages in the log. For smaller screens however something will have to give. Could we hold a reasonably public poll on which UI elements would be best to toggle between?

- Is there any way we can use the dead space in the centre of the lower block? If the time display were elsewhere that might be enough to fit the most important vehicle stats.

- Can we make any kind of compact but glaringly obvious marker to properly distinguish moves and movement cost? Two O(100) numbers right next to each other is pretty hard to read.

- Personally I consider the jarring layout distinction to the stamina bar a feature. It *functions* differently and is closely associated with the directly adjacent moves/movement values, yet it still represents a vital biological function which is good (green) when plentiful and bad (red) when depleted.

Can anyone suggest a simple and effective freeform auto-scaling nested box code we could rip off for JSON panel handling? [Ren'Py](https://www.renpy.org/doc/html/screens.html#grid) is built to be extremely easy-to-use and as a python framework has very readable source code (end-user inputs look almost the same as JSON...) but I doubt many people are familiar with it. Are there any C++ equivalents with open source code?

**Comment by I-am-Erk** [comment]
If we decide to break stuff into sub blocks, don't forget that things that are too big can probably be abbreviated or rephrased to *make* it geometrically possible.

Dpwb has requested wind speed and direction be included with weather and I think that's a good idea.

**Comment by davidpwbrown** [comment]
At some point I am planning on having weather_data return not just "cloudy/sunny" but also wind direction and a text description of the wind strength
Not a huge difference but bear in mind in future the weather string may be a tad longer
"Cloudy Gale from NW" or " Cloudy with NW gale winds" or whatever fits best.

**Comment by KITbutler** [comment]
Wind should be a separate field not directly attached to weather but placed in the same "environmental" block. And it should definitely render in vehicles if the game actually performs the proper vector sum in determining wind chill. Will there be a man-portable wind speed meter to get numerically precise values?

**Comment by davidpwbrown** [comment]
The weather reader CBM and weather reader item produce exact figures.

**Comment by EldritchHorror** [comment]
STAMINA IN THE RIGHT SPOT. WOOO.

@kevingranade please look at this.

**Comment by Amneiger** [comment]
I'm very glad to hear that you have eyes on the idea of making parts of the sidebar easier to move around and creating more settings for the sidebar.  It would be great if we could let players rearrange the sidebar components to something that they find more aesthetically pleasing and/or more efficient, or at least if we had a number of possible sidebar setups to choose from.  (We might add the older style of sidebar with a name like classic, for example.)

**Comment by Lamandus** [comment]
Perfect idea. Like I said in the Panelinfo 3 part. I don't mind his new UI, I I can choose another 😂

**Comment by Achie72** [comment]
As someone who just blindly follows the ui update, i would prefer this way over the other. In that things are scattered, i get the weather info faster, before my `pain`, `hunger` and `thirst`. My only suggestions are:
Move ` Spd 120 120 W  Stm |||||` under/over the Power bar  
Move the mood, and the safemood in place of it. 
Now the mood part looks to cramped, and the stamina would look better with the other imo (i'm aware the technical difference between those, but still, it helps please the eye.) If it's not a well recieved idea, you can try to incorporate this (as i would like it as well):

 > * Can we make any kind of compact but glaringly obvious marker to properly distinguish moves and movement cost? Two O(100) numbers right next to each other is pretty hard to read.

Break it into two new lines, and add the mood, and safemood next to that.

**Comment by ifreund** [comment]
Inactive and superseded by #28152

**Pull request closed without merging**
