### PR TITLE
Mutagen and mutation cleanup

### PR DESCRIPTION
**Pull request by Kelenius**
#23519 

Removed defaults from `threshold_mut`, `mutagen_message`, `iv_message`. Mutation categories MUST set them.

Proper spacing around ellipses in mutagen messages and dreams.

Changed IV yelling messages to make more sense.

Changed how mutagen category is retrieved from the mutagen - now it uses `properties`. Because of that, the abstracts were changed - the game currently can't using copy-from on something that has properties/qualities set, then setting it in the child too. There's no property for ANY, because that's the default state now.

Cleaned up categories. Previously:
id: "mutation_plant"
category: "PLANT"
category_full: "MUTCAT_PLANT"
mutagen_flag: "MUTAGEN_PLANT"

Now:
id: "PLANT"

That's it. The rest is redundant.

Cleaned up mutagen iuse.

Removed MUTAGEN_STRONG flag from mutagen serum. It has no effect; the amount of mutations gained from serums is adjustable in the category JSON.

### CODE REVIEW

**Comment by Kelenius** [comment]
Should be ready.

**Comment by Kelenius** [comment]
Any problems here?

**Comment by ZhilkinSerg** [comment]
> Any problems here?

Nope, just need more spare time to merge test this.

**Comment by ZhilkinSerg** [comment]
I guess it is safe to remove following lines now:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8badff72e358bc7d9f889dc635e922880fcf0cf2/doc/JSON_FLAGS.md#L807-L829

**Comment by ZhilkinSerg** [comment]
Looks good in fresh world with new character.

**Pull request merged**
