### PR TITLE
[Concept] Experiment: Using roads on map edges to generate a "highway," scaling map specials to city spacing setting.

### PR DESCRIPTION
**Pull request by DanmakuDan**
I used this http://devmag.org.za/2011/04/05/bzier-curves-a-tutorial/ to create a set of discrete bezier points between the roads placed on a map edge. The road itself is used as city points to connect nearby special terrain (labs, farms, etc). It doesn't affect the normal map spacing, but it helps wider spaced generation to handle the placement sometimes. I also added a scaling RNG check to reduce the amount of special terrain generating in more spread out mapgen.

The highway road gives the impression of a continuous road, as it will generate another end-to-end road from the available edges when mapgen creates a new overmap.

For reference:
Default city size 4, city spacing 4:
reg443
reg442
reg441

City size 4, city spacing 6:
reg463
reg462
reg461

City size 4, city spacing 8:
reg483
reg482
reg481

With modified generation and the edge-to-edge highway:
City size 4, city spacing 4:
new443
new442
new441

City size 4, city spacing 6:
new463
new462
new461

City size 4, city spacing 8:
new483
new482
new481

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Neat!

**Comment by Zireael07** [comment]
Cool!

**Comment by chaosvolt** [comment]
Ah, interesting. I do wonder if this can bring back the actual highway mapgen that hasn't been seen in forever. Otherwise it's still going be a series of country roads in practice. XP

**Comment by DanmakuDan** [comment]
I updated the code to try for at most two map-crossing roads, along with a pruning routine to get rid of leftover dead ends from pathing weirdness.

Note: I think high city spacing causes more pathing failures where roads should be built to certain special features, but this is observable even on regular settings, like mansions without a road.

**Comment by mugling** [comment]
Closed as appearing stalled. If work resumes would need rebase against `master`

**Pull request closed without merging**
