### PR TITLE
Floorwiring

### PR DESCRIPTION
**Pull request by deafmole**
#### Summary
Features "Adding Floorwiring Appliance"

#### Purpose of change

It is mainly to allow players more flexibility in selfbuilt bases, without the need of using pseudo-vehicles or connecting everything with jumpercables or extensioncords, which can be quite a mess.

#### Describe the solution

Well, I added them, using blank copper wire for now - just like the decorative ground cables before. 

#### Describe alternatives you've considered

thought about pipeconnections in the electricity system aswell. But so far: pseudo-vehicles, only use walls with wiring, jumpercables.  

#### Testing

No errors. Tested the connection over 4 tiles ingame with a standing lamp at night. Waited multiple hours, ran a few overworld tiles away and returned.

For now it acts like a electricity conducting dummy-appliance. You can traverse the tile, but with a movementpenalty and cant drag items over it. 

#### Additional context
I'm always open for suggestions and have a few other additions planned already. 

ToDo: 
- Remove/Reduce Movementpenalty
- Don't hinder dragging items
- Ideally tiles next to each other will connect like decorative ground cables.

### CODE REVIEW

**Comment by deafmole** [comment]
Also: if someone knows how I get rid of the movement penalty, I'll change it asap.

**Comment by deafmole** [comment]
Due to linting it's 945 lines instead of 30 lines changed.

**Comment by PatrikLundell** [comment]
A test of adding the "AISLE" flag to a floor lamp and placing it seems to allow it being moved through without a slowdown. However, trying to pull a welding cart through the tile still results in a collision.

**Comment by deafmole** [comment]
Weird, I am pretty sure I have tried that already and it still showed 400% movespeed.

**Comment by PatrikLundell** [comment]
My only check was to see that the message that it took a long time to move through the lamp didn't show up, so I didn't check actual movement costs.

**Comment by Fris0uman** [comment]
I'm pretty sure this is not the right solution as the floor wiring will collide with appliances and vehicles

**Pull request closed without merging**
