### PR TITLE
Escapable menus, part 2

### PR DESCRIPTION
**Pull request by illi-kun**
The following menus are affected:
- `Debug menu > Change time`
- `Debug menu > Edit player/NPC > Edit Stats`
- `Debug menu > Edit player/NPC > Set hitpoints`
- `Debug menu > Edit player/NPC > Set needs`
- `Debug menu > Edit player/NPC > Set health`
- `Debug menu > Edit player/NPC > Add mission`
- `Zlave menu`

\+ minor unrelated typo fix.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Good stuff!

**Comment by illi-kun** [comment]
/please do not merge this in next 10 minutes since I'm working on astyling of debug() function.

**Comment by illi-kun** [comment]
/Applied astyle to ```debug()``` function. It's ready for merge now.

**Comment by illi-kun** [comment]
#14564 shows that I need to make more testing of this PR.

**Comment by illi-kun** [comment]
It's good that @DanmakuDan pointed out the potential issue due to these changes.
```Debug menu > Edit player/NPC > Add mission``` was unsafe without the latest commit: keypressing of unassigned keys (like `@`) in this menu caused crash :-(
Fortunately, I've fixed it.

**Pull request merged**
