### PR TITLE
Replace the codeowner file with auto-request-review action

### LINKED ISSUE #56802: Code owner file does not work correctly
### Describe the bug

No reviews are requested automatically for some people. I noticed this in https://github.com/CleverRaven/Cataclysm-DDA/pull/56796

### Steps to reproduce

Open https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CODEOWNERS, see errors

### Expected behavior

Reviews should somehow be able to be requested for people not in the organization.

### Screenshots

_No response_

### Versions and configuration

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
None

#### Purpose of change
The codeowner file requires owners to have write permissions to be requested for review which does not suit what we actually want to do with it. Fixes #56802.

#### Describe the solution
Use [auto-request-review](https://github.com/marketplace/actions/auto-request-review) action instead.

It should be able to request review from people without write permissions, because I don't find any information stating otherwise.

Also added myself to be alerted of changes to `ui_manager.h/cpp` to test it.

#### Describe alternatives you've considered
Add more alerts for myself, but my contributions are scattered around the repo so perhaps I'll keep to the old check-prs-that-interest-me route.

#### Testing
Tested in Qrox/Cataclysm-DDA#12. It requested review from me.

It would still be nice if someone can help me test requesting review from people without write permissions. @jbytheway you recently added yourself to the code owners file so perhaps you'll be interested? If you agree I'll create a PR in my repo modifying some files to request review from you.

### CODE REVIEW

**Comment by GuardianDll** [comment]
You can add me into the request list for xedra and magiclysm mods, i don't have any writing permissions and fairly interest to got notes about mod PRs

**Comment by jbytheway** [comment]
If you still need another guinea pig I'm also happy to help. Feel free to go ahead and make a PR that should notify me.

**Comment by Qrox** [comment]
Well, turns out auto-request-review can only request review from collaborators too...

**Comment by jbytheway** [comment]
I found [this discussion](https://github.com/orgs/community/discussions/4586) where requesting reviews of non-Collaborators is requested.  Just mentioning it here so folks can go up-vote it.  It's already several years old, though, so I'm not holding my breath.

**Pull request closed without merging**
