### PR TITLE
Remove pork from description of mannwurst

### PR DESCRIPTION
**Pull request by bug-sniper**
Calling it pork would imply that it is not made from human flesh, which it is.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
It's long pork.

**Comment by bug-sniper** [comment]
Ok, thanks. Didn't understand what was meant. I guess I'll close this pull request.

**Comment by BorkBorkGoesTheCode** [comment]
@bug-sniper Actually, you could add the long part to the description.

**Comment by bug-sniper** [comment]
It's already in the description.

**Pull request closed without merging**
