### PR TITLE
[CP] Fix recipes and contents jars

### PR DESCRIPTION
**Pull request by Xpyder**
Consistency fixes for Sealed Jar recipes.  Based weights off the contents + jar weight, adjusted each object and recipe with the assumption of creating 2 volume of items (consistent with all other containers).

There are a lot of changes here, which means a lot of places for me to have made a mistake.  I'd appreciate a couple people reviewing them to make sure it's clean and ready to go.

I did each recipe as it's own subbranch in case there are issues or controversies about a particular recipe, not sure how to leverage that (this is my second time using GitHub) but I hope that was the right approach

### CODE REVIEW

**Comment by mugling** [comment]
Needs rebasing. 48 commits is excessive

**Comment by Xpyder** [comment]
A note on some of the remaining inconsistencies in broth weight and changes to canned fruit/tomato:  I based all changes on the existing items in comestibles.

The broth weights look wrong which implies an issue with either weight, volume, or charges for broth in comestibles but that's outside the scope of this correction and needs to be resolved separately

Canned Fruit and Tomato charges set to 2 because of the volume of their existing items in comestibles, with an eye toward weight to make sure it's consistent with other items.  Because the weight and volume match other similar items I made the assumption that the recipe charges were incorrect.  I'm open to changing this if we need, but because that implies larger changes to these items in comestibles, that discussion would probably be better handled with it's own change request after these consistency changes are in place.

**Comment by Xpyder** [comment]
> Needs rebasing. 48 commits is excessive

I don't know what this means, please explain?

**Comment by Xpyder** [comment]
@mugling 
I followed instructions here and got the following, but I don't know how to get the squashed commits to squish here.  Or do I need to submit a second merge request, or am I missing something?

rebase instructions used: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Results:
[detached HEAD 89d30f8] fixed recipe jar v8
 Date: Mon May 16 11:35:31 2016 -0700
 3 files changed, 343 insertions(+), 335 deletions(-)
Successfully rebased and updated refs/heads/fix-recipes-jar-contents-xpyder.

**Comment by Xpyder** [comment]
for easy access, here's my branch: https://github.com/Xpyder/Cataclysm-DDA/tree/fix-recipes-jar-contents-xpyder

**Comment by Xpyder** [comment]
It looks squashed in my GitHub Desktop, is there something I need to do to push that up here?

**Comment by karols146** [comment]
I think that mugling mean that it's too many commits for one PR. For example you can fix all recipes in other PR, and all fixes just take in one commit.

**Comment by Xpyder** [comment]
@mugling
I couldn't figure out how to get the squashed commits to show up here so I created a new pull request.
#16731

**Pull request closed without merging**
