### PR TITLE
[RDY] Autofire rebalance

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Previously, most guns with autofire lacked any coherent standard for their fire rates, creating oddities like the 3-round burst ARX-160 and the 30-round MAC-10. Now most coreguns with automatic fire rates (except the 223s, which will be fixed after the L523 PR is closed or merged) have been rebalanced around 1 second of cyclic fire. 1 second was chosen as a standard for two reasons: 1. Kevin Granade mentioned that he was interested in redefining a single turn around 1 second and 2. higher rates would cause most guns to empty their magazines after a single bad shot. If anybody's interested. dedicated machine guns like the M60 could have their fire rate based on 2 or 3 second burst. ~~Also, the BAR now has two automatic fire rates based on the A2 variant.~~

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
I arrived at the automatic numbers by finding the cyclic rpm of each gun, then dividing by 60 and rounding the result.

**Comment by kasanryukin** [comment]
I think #22756 and this one could work together since you're overhauling automatic fire, and I'm working on firearm range data.

**Comment by BorkBorkGoesTheCode** [comment]
I've added an explanatory stub to GAME_BALANCE.

**Comment by BorkBorkGoesTheCode** [comment]
I'm gonna revert the M1918A2 changes until after kasanryukin's PR. If I'm not around and anybody wants to add them, here's the code:


```
  {
    "id": "m1918",
    "type": "GUN",
    "name": "Browning Automatic Rifle",
	"//": "Based on the M1918A2.",
    "description": "Designed near the end of World War I, the BAR provided fire support for the US Army from World War II all the way to the Vietnam War.  Too much firepower to serve as a battle rifle, but not enough to be an ideal light machine gun, it still found a niche on the battlefield.",
    "weight": 8800,
    "volume": 10,
    "price": 350000,
    "to_hit": -1,
    "bashing": 12,
    "material": [ "steel", "wood" ],
    "symbol": "(",
    "color": "dark_gray",
    "ammo": "3006",
    "skill": "rifle",
    "dispersion": 180,
    "durability": 8,
    "modes": [
      [ "DEFAULT", "low auto", 5 ],
      [ "AUTO", "high auto", 8 ]
    ],
    "barrel_length": 4,
    "valid_mod_locations": [ [ "accessories", 4 ], [ "barrel", 1 ], [ "bore", 1 ], [ "grip", 1 ], [ "mechanism", 4 ], [ "muzzle", 1 ], [ "rail", 1 ], [ "sights", 1 ], [ "stock", 1 ], [ "underbarrel", 1 ] ],
    "magazines": [
      [ "3006", [ "m1918mag", "m1918bigmag" ] ],
      [ "223", [ "stanag30", "stanag10", "stanag50", "survivor223mag" ] ]
    ]
  },

```

The weight was increased to 8800 grams, and the Browning Automatic Rifle got two automatic fire rates.

**Comment by BorkBorkGoesTheCode** [comment]
Now there shouldn't be any conflicts between kasanryukin's PR and this one.

**Comment by BorkBorkGoesTheCode** [comment]
Jenkins, rebuild please.

**Comment by kevingranade** [comment]
Just FYI, my plan for auto fire in the future (I need to add this to the projects page...).
Default burst fire becomes "controlled burst", effectively the shortest burst the player can manage.  This would be mediated by the appropriate firearm handling skill, at low skills they waste some rounds due to inexperience, but at higher levels they're putting a tiny controlled burst on target.

Adjusting these numbers to be 1-second bursts really helps with this, because then I can just assert that various skill/dex levels lead to different fractions of a second of fire.

**Pull request merged**
