### PR TITLE
vehicles: added force replace button

### PR DESCRIPTION
**Pull request by sonphantrung**
#### Summary
Content "vehicles: added force replace button"

#### Purpose of change
Less keypresses for replacing battered up veh parts ;)

#### Describe the solution
added the force replace button:
- In the `do_repair` function, when a vehicle part is broken, instead of doing the repair, the function will instead do the vehicle installation process. In this PR, I've added `force_replace` boolean (`replace` button calls `do_repair( true )`)

~~(I'm getting errors from my clangd LSP, plus currently unable to compile, that's why I'm setting it to WIP)~~
Not yet compiled

#### Describe alternatives you've considered
Not doing this and having to do 9999 more buttons to remove then install vehicle parts (NOOOOOOOO!!!)

#### Testing
Not yet compiled

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
How does this "force replace" button work? Does it work for every vehicle part, or only for batteries?

**Comment by sonphantrung** [comment]
Yes, theoretically, it works for every single vehicles (when a vehicle part is broken, it'll call installation requirements instead of reparation requirements)

**Comment by irwiss** [comment]
Fwiw this is essentially a cheat

Assume damaged frame; instead of removing all parts on a tile, replacing the frame and re-welding/installing parts back you can "replace" it and end up paying time/charges/rods/etc just for the frame installation

**Comment by Night-Pryanik** [comment]
If you're actively working on this PR, consider making it a draft.

**Comment by sonphantrung** [comment]
I have a question which makes me feel quite wondering: Can Installation and Removal requirements be concatenated into a variable?

**Pull request closed without merging**
