### PR TITLE
electronics control unit fixes

### LINKED ISSUE #24609: Cruise control is on  without any incar electronics.
Game version: 7643

Operating system: Win 10 x64

Tiles or curses: tiles

Mods active: none

### Expected behavior
Cruise control on vehicles can be active only if the vehicle has working dashboard or other drive-assistant electronics. 

### Actual behavior
Cruise control is active by default on new vehicles and can not be switched off without control board.

### Steps to reproduce the behavior
Drive quad bike or hippie van.

It was introdused by #24594

### PR DESCRIPTION
**Pull request by mlangsdorf**
move reactor toggle out of the general vehicle control menu and into the electronics control menu.
move cruise control out of the electronics control menu and into the general vehicle control menu - it's a QoL control issue for players.
add dashboards or electronic control units to all the vehicles that should have them.

Fixes a bug introduced in #24594 
Fixes #24609

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Rockwheel operation control is missing now - was in intended?

**Comment by mlangsdorf** [comment]
Definitely an oversight. Will fix.

**Comment by ZhilkinSerg** [comment]
If you update vehicle weights (adding some parts to them) you would need to run vehicle efficiency tests and update test data and put it into `tests/vehicle_efficiency.cpp` (see comments in https://github.com/CleverRaven/Cataclysm-DDA/pull/24065).

The PR is good to go to be merged after test data is updated, bu unfortunately I cannot run tests by myself right now.

**Comment by mlangsdorf** [comment]
Yeah, I realized after looking at the Travis build that I needed to do that. Will fix this morning.

**Comment by mlangsdorf** [comment]
efficiency tests updated.

**Comment by ZhilkinSerg** [comment]
Thanks.

**Pull request merged**
