### PR TITLE
Forest mapgen via region_settings

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary
SUMMARY: Infrastructure "Add forest composition attributes to region_settings and use in mapgen."

#### Purpose of change
Forests are currently a completely hardcoded mapgen, making it difficult to introduce new terrains and furnitures or adjust the overall parameters.

This change creates a new forest section in the region_settings which allows modification of these forest settings via json, either via `region_settings` or `region_overlay` entries, which means mods can also trivially add to or adjust the forest composition. These settings are then used in a new forest mapgen function.

#### Describe the solution

* See [the new documentation](https://github.com/ralreegorganon/Cataclysm-DDA/blob/forest-mapgen-region-settings/doc/REGION_SETTINGS.md#forest-map-generation-settings) for a description of the forest mapgen settings.

* See [the new section](https://github.com/ralreegorganon/Cataclysm-DDA/blob/forest-mapgen-region-settings/data/json/regional_map_settings.json#L43) in the regional map settings for the new json.

* See [the additional map extras](https://github.com/ralreegorganon/Cataclysm-DDA/blob/forest-mapgen-region-settings/doc/JSON_FLAGS.md#map-specials) for a description of the map extras added.

#### Additional context

The new forests should be roughly equivalent to the old ones, though some of the additional tree and shrub species that were previously underrepresented (or not present at all) should be a bit more common, and I've added some additional ground clutter (e.g. dirt, tree trunks, boulders) to liven up the forests a bit. 

The primary reason why I've initially flagged this PR as [WIP] is that I'd like to get some testing and feedback to ensure that I've not accidentally totally ruined access to some critical forest-based resource. I do have ideas for further changes to the forest compositions, both for balance and verisimilitude, but I'd prefer to keep that for follow-ups.

If you're on Windows and want to run applications downloaded from strangers on the internet, I've compiled a version of this for testing purposes, which you can [download here](https://www.dropbox.com/s/p49ffespc9vzj5i/cataclysmdda-0.C-forest-region-settings-mapgen-20180909-1.zip?dl=1).

It's important to note that the previous and new forest mapgen functions handle both forests and swamps (and actually differentiates between `forest` which are at the boundaries of forests and `forest_thick` which are the inner forests). 

**The forest in spring...**
forest_spring

**...and a swamp**
swamps

It's fairly straightforward to adjust the composition, keeping in mind that with the way regional settings are currently applied, there is effectively only one region for the entire map. So, you could turn the swamp above into a **berry bog**...

bogs

...but EVERY swamp will now use that definition. Being able to have multiple regions is certainly an area of future work, as one could imagine differentiating between coastal swamps (e.g. a [salt marsh](https://en.wikipedia.org/wiki/Salt_marsh)) and interior swamps or other similar changes based on region.

Using `region_overlay` entries, it's quite trivial for a mod to significantly change the nature of a forest--for example, **Whaley** has been working with an early version of these changes to introduce new fauna (plants native to New England), groundcover (leafy forest floor), muddy water, and adjust the density of the forest and spawn rates to create something like this:

catawoods6

Part of un-hardcoding the previous forest mapgen was moving some of its special events out to map extras--the spiderwebs, jabberwock, and [Shia](https://www.youtube.com/watch?v=o0u4M6vppCI) that were hardcoded in the forest are now map extras that are referenced by the forest map extras via the normal json configuration, though nothing precludes them now being referenced anywhere a map extra can be used.

I also added three new map extras to give a bit more life to the forest:

**mx_grove**

>From wikipedia - The main meaning of "grove" is a group of trees that grow close together, generally without many bushes or other plants underneath.

This map extra finds the first tree in the area, and then converts all trees, young trees, and shrubs in the area into that type of tree. Here we see a grove of fruit trees:

groves

**mx_shrubbery**

Similar to a grove but for shrubs, this map extra finds the first shrub in the area, and then converts all trees, young trees, and shrubs in the area into that type of shrub.

shrubbery

**mx_clearcut**

>From wikipedia - Clearcutting, clearfelling or clearcut logging is a forestry/logging practice in which most or all trees in an area are uniformly cut down.

This map extra converts all trees and young trees in the area to stumps.

clearcut

Finally, some more closing images through the seasons, to follow the **spring** from above:

**summer**
forest_summer

**fall**
forest_fall

**winter**
forest_winter

### CODE REVIEW

**Comment by kevingranade** [comment]
Bug against githubbinterface: only allows one :+1:

**Comment by nexusmrsep** [comment]
This is big! Love it. Can see potential to going north (ice field regions), south (deserts), up (hills - replace trees with big boulders), or anywhere actually...

**Comment by FulcrumA** [comment]
I like the overall idea, but I'd like certain adjustments. Clearcut map extra should happen only at the edge of such a forest, people don't go deep into it to make those unless there's some innawoods settlement/house - in which case, assuring that there's a relatively rare, small wooden cabin map extra, with basic house loot would be nice (I believe such a cabin already exists, it's just being spawned pretty randomly).

**Comment by ralreegorganon** [comment]
I'm taking the [WIP] off this.

One thing to note is that any mod which includes a `default` regional settings will need to include the new sections. The Bright Nights mod included with the game does this, and I've updated it accordingly [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/25425/commits/12b17a13aca70972a497840597b6b5ff2fd25a59#diff-4d0ec680c7a45db7c16e8103a097d744R34).

**Pull request merged**
