### PR TITLE
Sci-Fi sidebar

### PR DESCRIPTION
**Pull request by mlange-42**
#### Summary
Interface "Sidebar 'sci-fi'"

#### Purpose of change

Add another sidebar with a different concept than the usual.

#### Describe the solution

Build a new sidebar.

C++ changes:

* Fix pain color transition to match text change thresholds
* Implement flipped horizontal graphs

#### Describe alternatives you've considered

None

#### Testing

Using the sidebar in-game.

#### Additional context

Screenshot(s) current status.

**Health/body status** widget:

grafik

Indicators left to right are:
* Warmth + wetness as background (cyan=damp, blue=wet/soaked)
* Encumbrance
* HP
* Status, as bodygraph
* HP
* ...

Above bodygraph, left to right:

* Thirst
* Body weight (here: very obese)
* Hunger

**Weather and place** widget:

grafik

Part 1 of **weather**/place widget (all 15 weather types, same order as in the debug menu)

weather_icons

Required widgets:

* [x] Place and environment
  * weather, time, date, moon, light, wind, sound, place
* [x] Health and body
  * [x] BP HP bars and status
  * [x] BP warmth, wetness, encumbrance
  * [x] Hunger and thirst
  * [x] Avatar bodyweight
* [x] Stamina
* [x] Pain
* [ ] Fatigue/tiredness
* [x] Weariness etc.
  * [x] Weariness and transition
  * [x] Activity and weary malus
* [ ] Stats
* [ ] Speed
* [ ] Vehicle speed
* [ ] Focus
* [ ] Mood
* [ ] Safe mode
* [ ] Weight carried (%)
* [ ] Temperature (with thermometer)
* [ ] Bionic power
* [ ] Mana?
* [ ] Compass
* [ ] Overmap
* [ ] Wielded weapon
* [ ] Martial arts
* [ ] Martial arts buffs?

### CODE REVIEW

**Comment by liminalRoar** [comment]
i kind of have mixed feelings about the whole front perspective. With the left side being on the right and vice versa. I guess it makes sense, but it might be more intuitive switched.. Depends what other people think tho.

**Comment by mlange-42** [comment]
> i kind of have mixed feelings about the whole front perspective. With the left side being on the right and vice versa. I guess it makes sense, but it might be more intuitive switched.. Depends what other people think tho. Otherwise i love this set up. looks great!

Since I work with bodygraphs, I always simply followed what was already there for the full-body widget. Added a few alternative graphs that are in front-view since then.

It is probably a bit of a "philosophical" question, and should be discussed for the "built-in" body graphs (sidebar developers can still write flipped versions).

So if we think of the player *being* the character, the view should be as viewed in a morror (i.e. left is to the right). If, however, the player *controls* the character, it should be in front view as it currently is.

**Comment by mlange-42** [comment]
Finished the weather widget. See srceenshots in original PR comment.

**Comment by mlange-42** [comment]
Added widgets for thirst, body weight and hunger over the head of the bodygraph:

grafik

**Comment by bombasticSlacks** [comment]
Should this still be in draft?

**Comment by mlange-42** [comment]
> Should this still be in draft?

Yes, this is not ready at all. Basically everything but place and bodyparts still missing. Still working on it, although slowly. (E.g. waited for merge of vertical sidebars in #60604)

**Comment by Maleclypse** [comment]
@mlange-42 The feature freeze is over so this can be worked on again.

**Comment by Zireael07** [comment]
Should probably be tagged as salvageable?

**Pull request closed without merging**
