### PR TITLE
Larger world creation menu UI and options menu UI

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Interface "Larger world creation menu UI and options UI"```

#### Purpose of change
Make use of modern display resolution for world creation menu UI and options menu UI.

Information in world creation menu UI is very densely condensed, to the point of long mods name or long mods descriptions doesn't fit in the interface. This is because of hopelessly outdated 80x24 terminal size it was created for. So I decided to use all available free space. 
Also I had to make options menu UI larger too as World Options tab is shown in the world creation menu.

#### Describe the solution
- Replaced all instances of `FULL_SCREEN_HEIGHT ` and `FULL_SCREEN_WIDTH` to `TERMY` and `TERMX` respectively for world creation menu UI and options menu UI;
- Added a `handle_redraw` function to get rid of graphical artifacts on main menu screen after exiting from world creation menu or options menu.

#### Describe alternatives you've considered
None.

#### Testing
Started game, opened options menu directly, opened world creation menu, checked for world options, returned to main menu, checked if all is ok.

#### Additional context
World creation menu before:

Options menu before: long names don't fit

World creation menu after: World Mods tab
изображение

World creation menu after: World Options tab
изображение

World creation menu after: Finalize World tab
изображение

Options menu after:
изображение

### CODE REVIEW

**Comment by AMurkin** [comment]
```
src/options.cpp: In member function ‘std::__cxx11::string options_manager::show(bool, bool)’:
src/options.cpp:2588:13: error: ‘handle_redraw’ was not declared in this scope
             handle_redraw();
             ^~~~~~~~~~~~~
src/options.cpp:2676:13: error: ‘handle_redraw’ was not declared in this scope
             handle_redraw();
             ^~~~~~~~~~~~~
```

**Comment by Night-Pryanik** [comment]
Yeah, I noticed the error too. How am I to resolve it?

**Comment by OzoneH3** [comment]
I'd suggest a width cap like other menus do, because having everything crammed to the left looks very ugly, especially on resolutions > 1080p.

**Comment by Night-Pryanik** [comment]
> width cap like other menus
What other menus are you talking about?

**Comment by OzoneH3** [comment]
I think the crafting menu does some %  width thing, would have to double check later.

**Comment by reed501** [comment]
> > width cap like other menus
> 
> What other menus are you talking about?

Many of the in-game menus:
inventory, use, reload, advanced inventory, etc.

**Comment by Night-Pryanik** [comment]
You mean something like this?
изображение

**Comment by Night-Pryanik** [comment]
Ok, it seems I managed to make world creation menu and options menu larger and centered.

Now it's the "undeclared use" of `handle_redraw` function. Can anyone help me with this? I declared it in `cursesport.h` and defined in `sdltiles.cpp`.

**Comment by OzoneH3** [comment]
The prototype is inside a ifdef ```#if defined(TILES) || defined(_WIN32)``` which isn't accessible from curses builds inside options and wordfactory. You would have to ifdef the calls there as well.

**Comment by Night-Pryanik** [comment]
Well, this redrawing should be available for curses builds too.

**Comment by OzoneH3** [comment]
It needs a minimum size as well, TERMX / 2 isn't very good for that (80x24):

**Comment by Night-Pryanik** [comment]
Well, I can set a minimum horizontal size, but I'd prefer discard supporting that small resolution. Even the background theme on your pic with this resolution is distorted.

**Comment by OzoneH3** [comment]
So, the minimum would have to be 160. Until that's the case this PR is on ice I guess.

PS: Didn't the Issue with the discussion on minimum screen resolution got stale closed?!

**Comment by Night-Pryanik** [comment]
> PS: Didn't the Issue with the discussion on minimum screen resolution got stale closed?!

Yes, it was.

**Comment by Night-Pryanik** [comment]
Done. Now windows are displayed correctly on both small and large resolutions.

Below are pics of 80 width
изображение
изображение

**Pull request merged**
