### PR TITLE
Add Eye colors cosmetic traits

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Content "Add Eye colors comsetic traits"

#### Purpose of change

We have hair, facial hair and skin color but eye color is missing

#### Describe the solution

Add the 6 main eye color (accordng to wikipedia https://en.wikipedia.org/wiki/Eye_color)
Put those traits into trait groups for NPC 
Add tiny edit to chargen to also pick random eye color when randomizing

#### Testing

Spawn a random Character
Spawn a bunch of NPC
*Look them in the eyes*
image

Confirm that there is a vairety of color instead of blue for everyone

#### Additional context

Sprites ready in https://github.com/I-am-Erk/CDDA-Tilesets/pull/605

### CODE REVIEW

**Comment by actual-nh** [comment]
I'm guessing Content Freeze, but feel free to remove if inappropriate. (Will have to check randomization at some point to see about making it match actual distribution, if it isn't already.)

**Comment by Fris0uman** [comment]
I put hazel with the rest of the brown like colors. I think in term of repesentation in the population it's more common in the area where people hav "dark eyes" that's why it's in the dark group. BUt that's a very rough modelisaion. Feel free  to find the proper number and make the correct groups.

**Comment by actual-nh** [comment]
> I put hazel with the rest of the brown like colors. I think in term of repesentation in the population it's more common in the area where people hav "dark eyes" that's why it's in the dark group. BUt that's a very rough modelisaion. Feel free to find the proper number and make the correct groups.

Understand; will check into it when I have a moment. (What color did you use for hazel in the tilesets?)

**Comment by Fris0uman** [comment]
light brown/yellow https://github.com/I-am-Erk/CDDA-Tilesets/pull/605/files?short_path=ac2ea18#diff-ac2ea18df3499e99b83d5530ca6ae453a65d19e54560d05337a6c87e96550421

**Comment by actual-nh** [comment]
> light brown/yellow https://github.com/I-am-Erk/CDDA-Tilesets/pull/605/files?short_path=ac2ea18#diff-ac2ea18df3499e99b83d5530ca6ae453a65d19e54560d05337a6c87e96550421

That variety of hazel definitely qualifies under dark, I think. Hazel seems to range - in terms of averaging over the whole iris - from mostly brown with a hint of green to green with a hint of brown.

**Pull request merged**
