### PR TITLE
fix pupating nuclear detonation

### LINKED ISSUE #73520: Pupating zombie is deafening load when transforming into flesh raptors
### Describe the bug

The noise created when a pupating zombie transforms into flesh raptors is very loud. In fact, it is so loud that my character with good hearing gets deafened when it happens, nearby or at 40 tiles away. I think this was updated in #73338, and I did update my version before making this report (I've observed this behavior twice). 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15211573/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

1. Spawn some pupating zombies. 
2. Wait for them to transform into flesh raptors. 
3. See if they deafen the player character. (I'm not sure if good hearing is requirement for this or not.)

### Expected behavior

I did not expect the flesh raptors bursting out of the pupating zombie to be so loud. Shooting my rifle chambered in 5.56 is not as loud. Boomers being very loud would be ok, but I don't think of the pupating zombie as explosively loud. 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fa7e258 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause the game to crash.

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
fix: #73520
no more mininuke loudness levels from exploding pupating zeds also increase aoe cause they were failing to spawn even if the pupating zed was by itself with nothing around it, tweak a few things also add a description sound

#### Testing
Screenshot_2024-05-05_12-45-20

### CODE REVIEW

**Comment by Karol1223** [comment]
Possibly relevant to look at #73338?

**Comment by casswedson** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/73338/files#diff-58877d704d44db681360b71a38c84cfd4f628685c73acffe393db6efb9271e3fR236-R238

added lots of damage plus the LOUD flag, it resulted in a very loud explosion

**Comment by GuardianDll** [comment]
wait why there is `LOUD`? it should be `silent`, and the sound is delivered by `soft_squelch`, did i just typed a wrong thing?

**Comment by I-am-Erk** [comment]
oh good, i was worried I'd just misread something but that's actually a tough error to catch

**Comment by GuardianDll** [comment]
since #73338 is backport candidate, this one should go in 0.H also

**Pull request merged**
