### PR TITLE
Missing header for cygwin

### LINKED ISSUE #10912: Cygwin x86 build error in filesystem.cpp
Version: 0.B-2646-gc9c38cb ~~(dirty, technically, due to my fix; see below)~~ (disregard, I'm a dumb; wasn't dirty when the error occurred.)

`git pull`, `make clean`, `make -j` resulted in the following:

```
src/filesystem.cpp: In function ‘void {anonymous}::for_each_dir_entry(const string&, Function)’:
src/filesystem.cpp:129:37: error: ‘errno’ was not declared in this scope
         auto const e_str = strerror(errno);
                                     ^
src/filesystem.cpp: In function ‘bool {anonymous}::is_directory_stat(const string&)’:
src/filesystem.cpp:144:37: error: ‘errno’ was not declared in this scope
         auto const e_str = strerror(errno);
                                     ^
g++ -DLOCALIZE -Wall -Wextra -g  --std=c++11 -MMD  -c src/mission_start.cpp -o obj/mission_start.o
Makefile:403: recipe for target 'obj/filesystem.o' failed
make: *** [obj/filesystem.o] Error 1
```

Fixed by inserting `#include <cerrno>` after `#include <cstring>` in `src/filesystem.cpp`.

### PR DESCRIPTION
**Pull request by bkentel**
This resolves #10912 .

### CODE REVIEW

**Comment by KA101** [comment]
@i2amroy, this is all yours.

**Comment by Shoes01** [comment]
I gave this a shot, here is the error I get on Cygwin : http://pastebin.com/dih5vqeM

**Comment by bkentel** [comment]
Looks like cygwin hs the same issue as mingw32 -- I can't look into it right now, but I'll have a look after work if you don't work it out yourself.

**Comment by bkentel** [comment]
What symbols are defined for you if you do a ` gcc -dM -E - < /dev/null`?

**Comment by Shoes01** [comment]
Here's the list of em : http://pastebin.com/wJCVDSJD

**Comment by bkentel** [comment]
Thanks.

You've got a pretty new version of GCC, and presumably libstdc++, odd that std::to_string is disabled. Any chance you could grep the libstdc++ source and see how it has been disabled in your distribution? I can just add a check for cygwin to fix your specific issue, but if the root cause is the same as on mingw32 perhaps the check can be unified into something simpler.

**Comment by Shoes01** [comment]
Are you on IRC? If you help me with some instruction I have time to do it, but I only pretend to be good at this programming stuff ;p

**Comment by Shoes01** [comment]
In my error reported above, if I remove the "std::" the game continues to compile until I hit the "errno" issue. By #including <cerrno>, the game then compiles.

**Comment by bkentel** [comment]
Doh! False alarm then -- for this workaround that we have, to_string has to be called unqualified.
I should add a not to one of the .md files in the root.

**Comment by kevingranade** [comment]
I'm going to call Griffinheart and you the two build verifiers for this and pull it.

**Comment by Griffinhart** [comment]
I'd verify this fix, but most recent build isn't building for me due to `std::to_string` in compatibility.h giving Cygwin a fit. Might just be an outdated version of Cygwin, though.

**Comment by bkentel** [comment]
Use just `to_string(...)` not `std::to_string(...)` and see what that does for you.

**Comment by bkentel** [comment]
@Griffinhart actually, where was it that the error was occurring? Is that old log you linked to still valid?

**Comment by Griffinhart** [comment]
```
In file included from src/advanced_inv.cpp:11:0:
src/compatibility.h: In function ‘std::string to_string(T)’:
src/compatibility.h:61:12: error: ‘to_string’ is not a member of ‘std’
     return std::to_string(n);
            ^
src/compatibility.h:61:12: note: suggested alternative:
src/compatibility.h:59:13: note:   ‘to_string’
 std::string to_string(T const n)
             ^
src/compatibility.h: In function ‘std::string to_string(T) [with T = double; typename std::enable_if<(((((std::is_arithmetic<_Tp>::value && (! std::is_same<T, bool>::value)) && (! std::is_same<T, wchar_t>::value)) && (! std::is_same<T, char>::value)) && (! std::is_same<T, char16_t>::value)) && (! std::is_same<T, char32_t>::value))>::type* <anonymous> = 0u; std::string = std::basic_string<char>]’:
src/compatibility.h:62:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/compatibility.h: In function ‘std::string to_string(T) [with T = int; typename std::enable_if<(((((std::is_arithmetic<_Tp>::value && (! std::is_same<T, bool>::value)) && (! std::is_same<T, wchar_t>::value)) && (! std::is_same<T, char>::value)) && (! std::is_same<T, char16_t>::value)) && (! std::is_same<T, char32_t>::value))>::type* <anonymous> = 0u; std::string = std::basic_string<char>]’:
src/compatibility.h:62:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/compatibility.h: In function ‘std::string to_string(T) [with T = long int; typename std::enable_if<(((((std::is_arithmetic<_Tp>::value && (! std::is_same<T, bool>::value)) && (! std::is_same<T, wchar_t>::value)) && (! std::is_same<T, char>::value)) && (! std::is_same<T, char16_t>::value)) && (! std::is_same<T, char32_t>::value))>::type* <anonymous> = 0u; std::string = std::basic_string<char>]’:
src/compatibility.h:62:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:403: recipe for target 'obj/advanced_inv.o' failed
make: *** [obj/advanced_inv.o] Error 1
```

**Comment by bkentel** [comment]
Is that built off a fresh pull from the upstream master?

**Comment by Griffinhart** [comment]
Version 0.B-2858-g18380c5 builds fine under Cygwin x86.

**Pull request merged**
