### PR TITLE
[CR] Use proper tin can weight

### PR DESCRIPTION
**Pull request by jzambo**

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
"copy-from": should copy the weight of unopened can.

**Comment by jzambo** [comment]
Copying weight would make this change a no-op. With this change opened can weighs less than unopened one. 

It's a minor thing, but tin cans may be only way to get clean water for early survival characters and it's a bit silly to carry 2kg of empty tin cans for that purpose.

**Comment by Coolthulhu** [comment]
Why would a proper weight for a tin can be lower than the weight of the tin can itself, with no contents?
It's not like the lid weighs 60% of the can.

**Comment by jzambo** [comment]
I assumed that 'tin can' weight is one with contents and I have changed weight on an 'opened tin can'. This was confirmed during gameplay as far I could tell. Is there something else goin on with "container mechanics" that I need to be aware of?

**Comment by Coolthulhu** [comment]
Tin can should weigh as much as itself+contents. If it doesn't happen and it doesn't include weight of the contents, that's a bug.

**Comment by BorkBorkGoesTheCode** [comment]
@jzambo canned items created during world generation receive the weight of their contents until eaten, after which they revert to an opened can. Spawning foodstuffs directly using debug menu won't spawn a corresponding container. Have tested with condensed milk spawned by worldgen.

**Comment by kevingranade** [comment]
Sounds like this is a non-issue, feel free to reopen if i'm missing something.

**Pull request closed without merging**
