### PR TITLE
Obsolete generic NPC common classes; use the avatar character generator instead

### PR DESCRIPTION
**Pull request by ShnitzelX2**
#### Summary
Features "obsolete generic NPC common classes; use the avatar character generator instead"

#### Purpose of change

Right now, randomly generated NPCs pick from `npc_class` objects where `"common" = true`, which include the following:

NC_NONE, NC_ARMY, NC_OPS, NC_HACKER, NC_DOCTOR, NC_VETERINARIAN, NC_TRADER, NC_NINJA, NC_COWBOY, NC_FARMER, NC_SCIENTIST, NC_BOUNTY_HUNTER, NC_MOTORHEAD, NC_THUG, NC_SCAVENGER, NC_SCAVENGER_PREPPER, NC_SCAVENGER_MOONSHINER, NC_SOLDIER

In my opinion, these 18 common classes aren't sufficient. When spawned, these random NPCs don't have a cohesive set of skills, nor a profession; their backstory might as well be random given that you can't tell what class they were spawned from. 

We have 198 professions (many of which cover the above classes), and a very nice character generator for the player character. Why not use them?

#### Describe the solution

What this PR does do:
- Generalizes character generation from `avatar::randomize` to `Character::randomize`, has `npc::randomize` use `Character::randomize` only if no valid class is defined, extracts relevant methods to do so where necessary. This functionally means that **NPCs are generating mostly like the avatar is.**
- Add `npc_background` key to professions taking a trait_group id for backstory
- Adds more `trait_group` for NPC backgrounds

What this PR does not do:
- Remove obsoleted `npc_class` and related JSON
- Account for equipment NPCs may have (or not have) aside from their profession's starting equipment. This is a big one, since a lot of the common classes have equipment definitions, which often include weapons that most professions don't start with. If this PR gets merged, I'd follow up by adding a function that modifies a spawned NPC's equipment depending on days passed.
- Add more `profession_group`s, also for a follow-up.
- Allow unique (`common = false`) NPCs to have a profession, also for a follow-up.

#### Describe alternatives you've considered

I deliberately did not put `npc_background` in a `profession_group` because ideally most professions would have unique stories.

#### Testing

Passed all tests locally except for "npc-movement", which I assume is an unrelated/outdated failure?

#### Additional context

Some NPCs generated with the debug menu:
npc1
npc2
npc3

### CODE REVIEW

**Comment by Maleclypse** [comment]
```
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> npc-movement
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/npc_test.cpp:432
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/npc_test.cpp:475: FAILED:
(~[slow] ~[.],starting_items)=>   {Unknown expression after the reported line}
(~[slow] ~[.],starting_items)=> due to a fatal error condition:
```
I couldn't find the exact error other than an NPC test failed so I restarted in case it's not related to your changes though that seems likely.

**Comment by Standing-Storm** [comment]
Is there a way to mark professions as exempt from being chosen for random NPCs?

**Comment by Maleclypse** [comment]
> Is there a way to mark professions as exempt from being chosen for random NPCs?

"common": false

**Comment by Standing-Storm** [comment]
`"common": false` doesn't work for professions, it seems. Is there another way to block particular professions from being chosen for NPCs? @ShnitzelX2 

Untitled2

**Pull request merged**
