### PR TITLE
Updated Riot Armor to modern armor standards

### PR DESCRIPTION
**Pull request by bean-b**
#### Summary
Content "Updated Riot Armor to modern armor standards."

#### Purpose of change
The old riot armor made little sense, 55%/60% coverage all around, 1000g of weight, and as such was not up to modern armor standards and made little sense. Therefore, I updated the armor values to make more sense.

#### Describe the solution

The materials are now  plastic padding and thermoplastic resin for protection. The suit has varying protection values across it, as i tried to base the material thicknesses off of current riot armors. It also has a small amount of molle webbing(on the thighs) as i saw that that was common across many riot suits.

#### Describe alternatives you've considered

The riot arm/shin guards are very similar to the hard leg/arm guards and thus may be a bit confusing. Also any of the values could be changed of course. Currently it isnt repairable which im not sure is ideal, but that is because thermoplastic resin and plastic padding are not repairable, which seems out of the scope of this pr.

#### Testing

Spawned the item in game, saw defensive values, tested attaching and detaching molle. 

#### Additional context

Designed after this suit vaguely after:
https://www.securityprousa.com/collections/riot-gear/products/damascus-gear-modular-hard-shell-crowd-control-suit

### CODE REVIEW

**Comment by Jarewill** [comment]
Since the armor now incorporates a jumpsuit, maybe it should also be on the normal layer alongside the outer layer as well as be padded/comfortable?

**Comment by bean-b** [comment]
I'm pretty sure its already padded/comfortable given the materials within. But I could totatly make it normal + outer if that makes more sense given its components and that it sorta has a normal layer built in. Another option would be to model it after a version without the nylon jumpsuit underneath, i.e. https://www.securityprousa.com/collections/riot-gear/products/secpro-riot-suit-1
I saw about half and half of both styles of designs when I was researching, and so I think this could go either way.

**Comment by bean-b** [comment]
I guess my main question with making it have both layers is what the difference between this vs say the track touring suit is. The track touring suit has an entire 1.3mm leather jumpsuit that holds all of the plastic padding etc, but only occupies the outer layer.

**Comment by nopenoperson** [comment]
break up all the hard plastic into multiple pieces in a way that makes sense.  like shin guards (could have foot guards, knee pads that could be modular), groin protector ( with hip protection?)  chest protector (with protection for shoulders and upper arm? protective foam vest could be separate piece worn on normal layer), forearm protectors (with built in elbow pads or might be separate?) etc. 

having it be a single article of clothing makes no sense.

**Comment by bean-b** [comment]
Yea i can do that

**Comment by bean-b** [comment]
I'm pretty happy with how the armor turned out, but one other option I considered would be to make the unique chest + shoulder + hip guard, and have it combined with the existing hard arm + leg guards in order to form the riot suit.

**Comment by anoobindisguise** [comment]
Only thing I could think to change is to bump up the plastic padding thickness a little. Other uses of plastic padding have 12-14mm.

**Comment by bean-b** [comment]
Is there anything particularly wrong with less thick plastic padding layers? I know many of the motorcycle armors have a lottt of plastic padding, but I don't see any reason against having less on another piece of armor. I chose the plastic padding material because most riot suit advertise shock absorbing foam _tm_ or something along those lines, although the thicknesses didint seem insane as it was all underneath the thermoplastic resin. Would there be a sort of halway point of like 6-8mm? Because 12+mm would more then double armor values and probably increase encumbrance values as well.

**Comment by anoobindisguise** [comment]
> Is there anything particularly wrong with less thick plastic padding layers? I know many of the motorcycle armors have a lottt of plastic padding, but I don't see any reason against having less on another piece of armor. I chose the plastic padding material because most riot suit advertise shock absorbing foam _tm_ or something along those lines, although the thicknesses didint seem insane as it was all underneath the thermoplastic resin. Would there be a sort of halway point of like 6-8mm? Because 12+mm would more then double armor values and probably increase encumbrance values as well.

There's absolutely a right number there that likely isn't 2mm or 12mm. Just depends on the design specs of RL armors.

**Comment by bean-b** [comment]
@TheShadowFerret Could you review this when you get the chance? Thanks so much. Also if there is a better way to request reviews please let me know.

**Comment by bean-b** [comment]
or @MNG-cataclysm if you could review that would be great!

**Review by MNG-cataclysm — APPROVED** [review]

**Pull request merged**
