### PR TITLE
Tuning of jars

### LINKED ISSUE #12249: Sealed vs Open Jar volumes and weights wrong
get 2 Sealed Jar of Woods Soup
open one of them
compare them

With nothing done other than opening it doubles in volume and more than doubles in weight.

Either Glass Jars need to be dropped to 1 volume and lower weight or all the recipes for sealed jars of food need to be doubled.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12612376-sealed-vs-open-jar-volumes-and-weights-wrong?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by illi-kun**
Volume of jars is set to 2 (since they're 0.5L containers).
Cutting props of glass jars were nerfed from 1 to 0 (glass bottle is reference for me), bashing props are reduced also to match open/sealed conditions (from 8 to 4), and to-hit bonus was also removed.

Let's merge this PR as is (I don't want to keep it open for a long time, it already improves jars consistency).

The part of issue #12249 related to weight isn't solved here and still require attention (I will fix it separately).

### CODE REVIEW

**Comment by Treah** [comment]
"sealed jar of V8"

V8 technically comes in bottles and cans not jars :P

**Comment by kevingranade** [comment]
I'm not clear on the status of this, it looks like a totally reasonable thing to do, is it just waiting on you having time to finish it?

**Comment by illi-kun** [comment]
Yeah, I need to finish it, sorry for delay. I want to spend more time than expected for checking of possible hidden issue here. Will change the status of this PR shorty (either close & break it into smaller chunks or finalize it).

**Comment by illi-kun** [comment]
@Treah V8 in jars looks like a home-brewed option, I suppose (I didn't introduce new receipts here, just tweaked existing items).

**Comment by Coolthulhu** [comment]
Multi-charge jars (for example, meat soup) seem to have weight calculated for 1 charge.

**Comment by illi-kun** [comment]
Well, my initial message clearly state that weight isn't fixed yet.

**Comment by Coolthulhu** [comment]
Skipped reading it after I saw the name change.
OK then, merging in current state

**Comment by illi-kun** [comment]
Thanks, will tweak it more later.

**Pull request merged**
