### PR TITLE
make turrets controlled by ID readers/consoles deactivate instead of despawn

### LINKED ISSUE #71332: turrets should drop its inactive state and ammo when deactivated via a console or ID card reader
### Is your feature request related to a problem? Please describe.

It's kinda weird that the turrets just vanish out of existence instead of just, well, being deactivated. It would make sense if they were mounted to a wall or ceiling but nothing in their description indicates this, they are just on (what I assume to be) tripods.

### Solution you would like.

Instead of despawning they should drop their inactive state and drop their ammo if they have any.

### Describe alternatives you have considered.

Adjust their descriptions (this will also require some sprite work for tileset maintainers) to indicate that they are retractable towards walls/ceilings/ground instead.

### Additional context

I already wrote the code for deactivation instead of despawn. If this makes sense I'll make the pr for it.

### PR DESCRIPTION
**Pull request by KeremBabaG**
#### Summary
Balance "make turrets controlled by ID readers/consoles deactivate instead of despawn"

#### Purpose of change
Turrets with the flag ID_CARD_DESPAWN or CONSOLE_DESPAWN despawn when you do their actions. This aims to make them deactivate instead of despawn.

closes #71332

#### Describe the solution
When you swap an id card or hack a console the game looks for a furniture of the same name (e.g. f_turret for mon_turret) and places the furniture in its place. If no such furniture is found it despawns the turret and places its to_item entry instead.

Also changed the flag's name to better reflect the nature of this solution.

#### Describe alternatives you've considered
Turn them friendly instead.
Make a new "inactive turret" enemy instead of a furniture.
Go through with the initial method of dropping its inactive state as an item.
Or just let the turrets quantum tunnel themselves out of our reality as always.

#### Testing
Visited a TCL, swapped the visitors pass. The turrets indeed turned into furnitures.

#### Additional context
none for now

### CODE REVIEW

**Comment by KeremBabaG** [comment]
Implemented it this way because didn't want to bloat monster json with an additional field for furniture. So in case the durniture is not valid, it drops its item in its stead. Added a container flag because in future I want them to drop their ammo as well.

**Comment by Fris0uman** [comment]
Why a furniture when every other robot turn into an item and we already have the infrastructure for it?

**Comment by KeremBabaG** [comment]
> Why a furniture when every other robot turn into an item and we already have the infrastructure for it?

Well I did that originally but in the issue I linked it was said that turning them into furnitures was much better. And the idea grew onto me because it feels like they are part of the enviroment this way.

**Comment by Fris0uman** [comment]
But why add a step that doesn't represent anything?

**Comment by KeremBabaG** [comment]
> But why add a step that doesn't represent anything?

Well dropping it as an item doesn't give the same feeling of "this thing would've gladly murdered you and now it's inactive" as well as the furniture does imo. Although I can go through with just the item, if it's that much of a bloat. I thought it was nice

**Comment by Qrox** [comment]
> But why add a step that doesn't represent anything?

A furniture step can better represent the turret retracting into the ceiling instead of simply disappearing or magically popping out of the ceiling for the player to pick up, so it does represent *something*.

> put some flavour text in the log saying that the turrets retracts in the wall/floor

Even if retracted the turret should still be there, so from a realism persepective a furniture can better represent it.

**Comment by TealcOneill** [comment]
Is this ready for merge? This sounds like a great feature!

**Comment by KeremBabaG** [comment]
> Is this ready for merge? This sounds like a great feature!

oh yeah it is, idk why this one was not merged.

**Comment by TealcOneill** [comment]
If you could update the branch to check if there's any merge issues that would be awesome.

**Comment by KeremBabaG** [comment]
> If you could update the branch to check if there's any merge issues that would be awesome.

This pr is appearemtly 5 months old so I don't think so. I will try it nonetheless and open another one if it breaks stuff.

**Comment by kevingranade** [comment]
Sorry for not giving feedback on this for so long. 
This is a bit of a tricky legacy issue. The reason the turrets disappear is to essentially not hand out a huge reward when the challenge is bypassed. Is this a huge cop out? Yes it is.

The question is what to do about it now? Ideally I think turrets are just the wrong fit here,  especially a bunch of them, but that's a pretty involved change so it's not great for the short term. 

I think just spawning a turret item is swinging too far in the other direction though,  a nice middle ground would be a turret fixture that had a high chance of reactivating when you try to mess with it to revive some of the risk.

**Comment by KeremBabaG** [comment]
Thanks for the feedback. I too thought that getting a high-end turret is too much of a free reward, especially just for swiping a card or hacking a terminal(computers is easy to level up). But it's also silly having them vanish so I made this. Your solution is much better, and we could add a warning in its description/action to make players think twice. As you progress in computers/electronics said fixture might have a less chance to just boot up in your face(although never zero).

Having said that I'm closing this one as it is too old, but I will come back to it with a better solution like I mentioned.

**Pull request closed without merging**
