### PR TITLE
New challenge scenario - Fungal Infected

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Content "New scenario: Fungal Infected"

#### Purpose of change
Add new challenge scenario. Fungal infected has a lot of interesting effects and flavor which would make for an interesting starting scenario.

#### Describe the solution
Add new scenario

#### Testing
Create new character with new scenario and let the time fly by as the mycus converts their innards to nutrition.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Please add a documentation for your new flag in `JSON_FLAGS.md`.

**Comment by enaantd** [comment]
That's a cool idea for a new scenario, especially for experienced players that know how to avoid fungal infection.
Have you considered making this start next to a fungal tower (or something related)?

**Comment by CodeBandit** [comment]
I have updated JSON_FLAGS.md

> Have you considered making this start next to a fungal tower (or something related)?

I have, but it looked like I needed to create a new fungal tower/fungal bloom map since they didn't look to allow player spawning directly on top of them. Not only that, their distance from cities also makes it far more difficult to cure the fungal infection since the time limit is strict and maluses are severe.

**Comment by enaantd** [comment]
> I have, but it looked like I needed to create a new fungal tower/fungal bloom map since they didn't look to allow player spawning directly on top of them.

Maybe spawn a few tiles away from the tower, if that's possible?

> Not only that, their distance from cities also makes it far more difficult to cure the fungal infection since the time limit is strict and maluses are severe.

Sounds like a challenge!

**Comment by CodeBandit** [comment]
I may try to do that in the future as part of a different PR :)

**Comment by waveyl** [comment]
Born in fungal tower, you have no way to stop fungal expansion, you have to get away from it, and find someplace to do some preparation for entering city. It's a running game requires luck,not special and not interesting.

**Comment by CodeBandit** [comment]
But, you're not born in the fungal tower, you can select anywhere you like, you don't need all that much preparation to enter the city (if you know what you're doing), and it makes you deal with situations you'd typically not encounter. Running away from zombie dogs -> "You taste mushrooms".
It's through and through a challenge scenario

**Comment by ZhilkinSerg** [comment]
We should jsonize starting scenario effects someday and drop all these flags.

**Pull request merged**
