### PR TITLE
Allow fake weapons to be sharpened into inferior ones

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Features "Allow the player to sharpen fake weapons into edged, inferior versions."

#### Purpose of change
Inspired by this discussion on the CDDA Discourse: [Sharpening dull replicas](https://discourse.cataclysmdda.org/t/sharpening-dull-replicas/27620)
This PR aims to allow the player to sharpen the blade edges of cheap replica blades into something more usable, but markedly inferior to quality craftsmanship. This only extends to weapons that are meant to deal cutting damage, excluding blunt weapons like maces, but including morningstars.

#### Describe the solution
Using something to grind an edge on the metal, the player takes a 'fake' replica and grinds an edge down, making it 'inferior'.

#### Describe alternatives you've considered
None

#### Testing
Spawned in a grindstone and a fake broadsword. Executed the recipe, and the fake broadsword became an inferior broadsword.

#### Additional context
None

### CODE REVIEW

**Review by anothersimulacrum — CHANGES_REQUESTED** [review]
These are items representing different things. You should not be able to transmute them.

**Comment by MNG-cataclysm** [comment]
> These are items representing different things. You should not be able to transmute them.

I suppose I could add a sharp version of the fake weapons to solve this. Could it share the sharpness multiplier of the inferior version, or would it be somewhere in between the fake and inferior varieties?

**Comment by anoobindisguise** [comment]
Inferior ones are budget steel, so you obviously can't turn an aluminum one into that, but also the aluminum ones are just completely fake and poorly constructed, they're replicas to display in a home or museum - so sharpening it is going to get you basically nowhere as it will become dull after slicing a zombie like, twice, if you're lucky.

**Comment by liminalRoar** [comment]
So, is this replica seen as being equivalent to a movie prop or something completely fake? Or is it rather an unsharpened blade? Because you can buy plenty of practice/fake swords that are actually decent steel and would make an okay weapon if sharpened.

**Comment by Zireael07** [comment]
CDDA fake weapons are aluminum, so that should probably tell you enough about their sharpness. I don't think you can sharpen it to any sort of edge useful in a post-apoc situatiion

**Comment by PatrikLundell** [comment]
If I understand it correctly, "real" practice weapons are made out of proper materials but made blunt to be reasonably safe for sparring (with protective gear), and so could be sharpened. Some practice weapons (in particularly heavy ones that would be dangerous even when blunt) are made out of safer materials and thus couldn't be sharpened.
Some sports weapons are probably almost completely useless even if sharpened (Olympic fencing, for instance) as they're far removed from the weapons they were once derived from. Something that flexes at the slightest resistance would be hard to use to damage zombies with any kind of protection at all.

**Comment by liminalRoar** [comment]
Ah, yeah that wouldn't last long lol.

We could add a dull practice sword that could be sharpened with a recipe. Idk if that is totally needed, but id personally be okay with it.

Not sure where all the current replicas spawn but probably reasonable that some of those could spawn a steel alternative occasionally.

**Comment by Zireael07** [comment]
Sport fencing weapons are basically a piece of electroconductive wire. Pretty thick, like your thumb twice, but not meant to be sharp at all and trying to sharpen it will just destroy it. Will happily bend and flex against any resistance (opponent's torso, board, wall)

Source: mate's brother is a paralympic wheelchair fencer who has showcased the sport a couple times and I have been able to hold/"fence" with said weapon

**Comment by liminalRoar** [comment]
I would think the steel practice sword would mostly be a trinket some people would have at home in a closet or basement or somewhere. I personally have an unsharpened high carbon sword and know a couple of other people who do as well. They aren't too hard to find irl.

**Comment by anothersimulacrum** [comment]
I don't think we should have any sharpening until we have an explicit sharpening mechanic. These specifically are just poorly constructed replicas, I think practice items would also be separate items, and those might be reasonable to convert into more proper weapons (I don't know).

**Comment by liminalRoar** [comment]
I do agree with that. Sharpening would probably be part of item qualities/grades/etc. Which i believe we will first be implementing slowly with cooking.

Someday we can have a menu for sharpening weapons similarly to the current repair + tailoring menus. By activating a sharpening stone or grinding wheel. Weapon sharpness could become separate from actual item damage. Tons more thoughts on that, but i would be looking forward to developing more complex item creation and management.

Do items in game have unique IDs currently? If there are two Katanas sitting on a table, does anything make them distinct? They must at least store the current condition, like how damaged they are?

**Comment by PatrikLundell** [comment]
As far as I understand items are not inherently unique. However, they can have fields that would make them unique (I think you can name items?), and damage is a property that some (all?)  items have. Note that much of the code just tosses around the id of an item, in which case it's up to the using code to find something that matches within some implicit context, while the newer item_location contains a reference to an actual item (as well as the ability to specify a sub stack of it, such as 3 out of the 35 identical items in a stack).

**Comment by liminalRoar** [comment]
Gotcha.  i was just thinking that would inevitably need to be part of future item qualities if it happens. Not sure how all the coding works, but i figure items having unique parameters and stats could be taxing depending on how much is stored and used in memory at a time.

I'd imagine you would just have the unique IDs for items and maybe only call up their specific stats when wielded by the character or other creature as well as when it is examined.

**Comment by PatrikLundell** [comment]
I'm not sure if items are always stored individually and stacks are meta structures, or if stacks are actually a stored unit (charges are stored within the item, but that's different from a stack). There are functions within the code that collects like items into stacks for e.g. display purposes.
I don't think sharpness would be much of an issue if the resolution is limited. A float value would make displaying your collection of combat knifes rather unpleasant, though, with one line for each of your 352 knives... If course, the stack collection functions could limit the resolution and stack knives within some brackets together into a smaller number of displayed stacks.

**Pull request closed without merging**
