### PR TITLE
Fix plural names in Arcana mod

### PR DESCRIPTION
**Pull request by Cyrano7**
Pretty much a copy of https://github.com/CleverRaven/Cataclysm-DDA/pull/21569 but for mods.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Any fix for the official repo, or will I have to do so for them?

**Comment by DangerNoodle** [comment]
Also, note that this is replicating default behavior for when plural is not specified, and is redundant.

**Comment by ZhilkinSerg** [comment]
> Also, note that this is replicating default behavior for when plural is not specified, and is redundant.

So, that is why I have 102 batterys...

**Comment by DangerNoodle** [comment]
Yes, amusingly. I also looked up the Arcana and Magic Items repository, it appears this was already fixed by them, possibly during a linting commit.

**Pull request merged**
