### PR TITLE
Mythical weapon replicas

### PR DESCRIPTION
**Pull request by Zaweri**
I think this mod is ready, be sure to tell me if I missed something. These are replicas of Norse weapons, but I plan upon expanding to it, hence the name "Mythical Weapon Replicas". ATM you learn them from a very rare book.

### CODE REVIEW

**Comment by kevingranade** [comment]
Still broken.

**Comment by Rivet-the-Zombie** [comment]
For some reason I'm not surprised.

@Zaweri, your idea here is neat. I'd really like to merge it, but you have to **actually test it** before you PR it.

**Comment by Zaweri** [comment]
Yeah, I was having problems with my computer. Sorry guys for the inconvenience, I am testing it after I come back from eating.

**Comment by Zaweri** [comment]
IT LIVES!!!! *EVIL LAUGHING*
A quick playtest shows everything's fine!

/me dances excitedly

**Pull request merged**
