### PR TITLE
Detached Rural Special Maximum Distances from Requiring a City

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Bugfixes "Detached Rural Specials from Requiring a City"

#### Purpose of change

If you get an overmap without a city, there will be very few specials placed, making the countryside noticeably barren.  Especially pronounced when the spacing and size sliders are adjusted.  This simply unhooks the rural type specials from requiring a city, while keeping their minimum distance from a city the same.  The result of this fix is that you have the same generation on normal spacing/sizing, but the empty long countryside roads on extreme spacing are filled in with specials now.

#35212
Partially fixes this bug.

#### Describe the solution

Going over the list of specials and finding the rural type ones (Farms, etc) or those with high maximum city distance settings, such as ;
    "city_distance": [ 8, 40 ],
And unhooking them from requiring a city to be present by changing the last number to -1 ;
    "city_distance": [ 8, -1 ],

Which essentially leaves worldgen as normal, on normal spacing, and improved on large spacing/sizing maps - since it appears by giving these specials an upper-limit distance and requiring a city, a consideration was not given to the possibility of having no city on an overmap tile.  This change should improve worldgen on large spacing, with no drawbacks I can see on other spacing.

The following specials were adjusted ;

Motels (not the built up 2 floor motel though)
Farms
Mine Entrance
Rest Stop
Roadstop
Gas station with Garage
Apple Orchard
Dairy Farm
Hunting Blind
Tree Farm
Desolate Barn
Rest Area
Rural Houses
Fire Lookout Tower
Lumbermill
Steel Mill
Private Resort

#### Describe alternatives you've considered

Introducing a function to dynamically adjust placements of specials on the fly according to the sizing/scaling slider setting, which would require c++ edits.  This json edit solution is much simpler, and does not have any requirement of c++ edits.

#### Testing

Tested a couple of maps with normal, small and large spacing and size variations.  Normal maps were the same, unchanged.  Larger sizes and larger spacing maps were significantly improved with fresh sprinkles of rural specials along formerly empty country highways.

I am still keen to fine tune this, and would like feedback, as well as any other problems that may need to be faced.

The following specials were not changed, but I think they may be considered?

FEMA Camps
Prisons
Freshwater Research Station
Mansion Wildernesses -> They generate without road connections for some reason??

#### Additional context

This is what a country road looks like before this fix (only rural gas stations, 1 rest stop type and food cart, nothing else);

old country roads

After the special unhooking from cities is applied,  these empty country roads now get populated thus ;

unhooked rurals 1

unhooked rurals 2

### CODE REVIEW

**Comment by Venera3** [comment]
As discussed on Discord and over at the context section of #46701, there's a *reason* behind the city size restrictions. Without it you don't have any stratification of specials around cities, making the countryside much the same as the suburbs.

You could add it to the Rural Mapgen mod, or implement a scaling factor for the special spawn conditions on the code side, but otherwise I see it as a step back from where worldgen is right now.

**Comment by Zireael07** [comment]
@Venera3: Point. Can we somehow get a special case, "no city on overmap" - use this set of parameters, "city" - that set of parameters?

**Comment by actual-nh** [comment]
If the maximum city distance is such that it could stretch to another overmap, and there is no city on this overmap, then there should be some chance of treating the maximum distance as "-1", preferably dependent on how far the original maximum distance is.

**Comment by stubkan** [comment]
> As discussed on Discord and over at the context section of #46701, there's a _reason_ behind the city size restrictions. Without it you don't have any stratification of specials around cities, making the countryside much the same as the suburbs.

This pr does not alter city strata, I believe.

I would like you to try this configuration and you will see normal worldgen sizes in spacing of these specials appears the same.  Because all of the ones I unhooked have high maximum distances (40-50 tiles etc) and all the cities are so densely packed that they often are less than 40 tiles away from each other.  Since an overmap is 150 tiles across, and there are usually multiple cities, the maximum radius overlaps more often than not.  So this unhooking has no discernable effect until spacing is increased.

These issues that I am concerned with fixing here are specified in the discussion that you linked to me, ie "some quirks of the worldgen and content additions through the years have led to most generated overmaps feeling pretty samey."  This is what this json fix is aimed toward solving.  As any overmap tile without a city is quite samey, as there are very few specials that can generate right now.  I think it is a severe limitation that a city must be required for most specials to be placed.

Special minimum distance from cities is untouched, so the strata around cities is the same.  And things that generate only further away from a city continue to do so.  Things that generate close to a city continue to do so.  I have not touched any specials that should remain close to a city, and only added the possibility of rural type specials to be generated further from a city, to fill in cityless overmap tiles.

Please test it and see for yourself.  I am willing to discuss further and make changes if required, as this simple change addresses in my opinion a severe limitation, but does not alter city strata.

Of course we could make new functions and entirely new special json files, or c++ that scales the placement according to spacing settings, but that is a lot more work, and someone else will have to volunteer to do that...

**Comment by actual-nh** [comment]
I don't know whether this should be under Feature Freeze or not; I will let others decide.

**Comment by Maleclypse** [comment]
I've labeled this Feature Freeze as I would rather we see how this affects things in an experimental branch rather than in a stable release.  If it merged in now we would have very little feedback before it became part of the 0.F stable and overmap generation is critical.

**Comment by Venera3** [comment]
I don't need to test it, for the most part this is literally what worldgen looked like until about two months ago. You also unintentionally mentuoned the reason why limiting specials by stricter spawn conditions makes overmaps less samey: *usually* cities spawn within the broades band (the range of city-connected specials, if I may use my categories) of each other leading to a relatively homogenous "civilized" region. However, every overmap will have at least a few areas where -either by sheer chance, a happy river/lake placement or whatever- there are a number of special sectors outside of all city-dependent spawns, causing that part of the overmap to have noticeably different locations and in general a more "wilderness" feel.

Again, the fact that this penalizes off-default world settings is unfortunate, but after plinking away at specials for about two months I can say with 90% confidence that the low-hanging JSON fixes are all present and accounted for. There's certainly a discussion to be had about which world settings should be default and/or should be relevant to special spawns, but until there's a system in place to scale the limits to world settings any such decision will be inherently arbitrary.

**Comment by actual-nh** [comment]
@Venera3: Question, to make sure I'm understanding things correctly - can the city distance limits "stretch" across overmap borders? Or is an overmap without cities never going to have any of these, even if there's a city right on the border? (An additional factor being that, IIRC, the position defined as the city is simply where it initially started, not where it is centered now; moreover, the city distances are from that position, not from the "city limits".)

**Comment by stubkan** [comment]
Worldgen did not look like this two months ago.  I have made two other fixes to c++ which has improved road generation by accomodating spacing and cityless overmaps better.  It introduced specials being linked to roads, and ensured continous road systems, whereas they did not before.

But sure, ignore everything here and keep the bugged system, without trying new things or talking about improving it.

**Comment by stubkan** [comment]
> @Venera3: Question, to make sure I'm understanding things correctly - can the city distance limits "stretch" across overmap borders? Or is an overmap without cities never going to have any of these, even if there's a city right on the border? (An additional factor being that, IIRC, the position defined as the city is simply where it initially started, not where it is centered now; moreover, the city distances are from that position, not from the "city limits".)

Most of the overmap worldgen is generated as if it was the only overmap in existence, so there no current way for gen to know where a city is outside an overmap with the present system.  This is why some of the worldgen breaks when for some reason an overmap does not have a city, as a lot of the generation work is only done with a city present.

The only code (that I know of so far) that steps across overmaps is when a mission or spawn tries to find a specific building to assign it as the mission objective or starting location, it can search I think up to 3 overmaps away to get one.

Your idea that you mentioned gave me an idea though, routines could be written in the worldgen to check for a city, and to do a different generation if no city is found.

**Comment by actual-nh** [comment]
> Worldgen did not look like this two months ago. I have made two other fixes to c++ which has improved road generation by accomodating spacing and cityless overmaps better. It introduced specials being linked to roads, and ensured continous road systems, whereas they did not before.

This does bring to mind the idea of some specials being determined by maximum distance from the nearest road, as opposed to maximum distance from the nearest city.

> But sure, ignore everything here and keep the bugged system, without trying new things or talking about improving it.

It certainly needs improving, and I think we're talking about improving it right now. Your C++ fixes are/will be already improving on it.

**Comment by actual-nh** [comment]
> Your idea that you mentioned gave me an idea though, routines could be written in the worldgen to check for a city, and to do a different generation if no city is found.

Perhaps a flag, to allow the generation of particular specials on overmap tiles without a city even if they have a city distance maximum limit? E.g., farms?

**Comment by stubkan** [comment]
> This does bring to mind the idea of some specials being determined by maximum distance from the nearest road, as opposed to maximum distance from the nearest city.

That could be a method for sure, an added line in the other pr to check it is linked to a road, and if not, then to remove the special and try again or move on.  Although, without this pr, nothing much will generate in that case anyway, as only gas stations or rest stops can generate away from a city right now.

**Comment by stubkan** [comment]
> EDIT: I agree with Venera3, BTW, that having the countryside look too much like the suburbs is problematic, and any fixes for non-default city frequency should not cause this.

I'm not sure why though, as it does not change the city strata layouts, and the rural buildings are what would generate out in the country.   What is the specific issue here?

The specials should not be the same ones?  They should be different, country-only specials?  

Or is it the fear that the strata is being changed?  But that can be checked by test runs, to see if your observations confirm mine or not?

**Comment by actual-nh** [comment]
> > This does bring to mind the idea of some specials being determined by maximum distance from the nearest road, as opposed to maximum distance from the nearest city.
> 
> That could be a method for sure, an added line in the other pr to check it is linked to a road, and if not, then to remove the special and try again or move on. Although, without this pr, nothing much will generate in that case anyway, as only gas stations or rest stops can generate away from a city right now.

I was more thinking of an optional specification for each special of maximum distance from an existing road, which would be a separate PR. If that was specified for a given special, with a relatively close figure, I think there would be less objection to making them capable of spawning further from/without cities - you could still have the completely-empty areas that @Venera3 wants (as do I) provided they were also not close to a road.

**Comment by actual-nh** [comment]
> The specials should not be the same ones? They should be different, country-only specials?

There is a preference for some areas not having any but a very few specials - the equivalent of parks (although I'd think that Fire Lookout Towers should still be generated in those).

> Or is it the fear that the strata is being changed? But that can be checked by test runs, to see if your observations confirm mine or not?

You might want to check the specials' git "blame" for what distance specifications they had (that were problematic).

**Comment by stubkan** [comment]
> I was more thinking of an optional specification for each special of maximum distance from an existing road, which would be a separate PR. If that was specified for a given special, with a relatively close figure, I think there would be less objection to making them capable of spawning further from/without cities - you could still have the completely-empty areas that @Venera3 wants (as do I) provided they were also not close to a road.

I see, so it is empty countryside that is wanted?

I could change the other pr to search a closer radius for a road .. perhaps 30 tiles, and remove specials that do not find a road, so it will be filled with farms and rural things but ONLY near the country roads, so there will be plenty of empty countryside.

I assumed that away from cities, farms would be wanted, since the country side is usually filled with things like that irl, not just gas stations

**Comment by actual-nh** [comment]
> > I was more thinking of an optional specification for each special of maximum distance from an existing road, which would be a separate PR. If that was specified for a given special, with a relatively close figure, I think there would be less objection to making them capable of spawning further from/without cities - you could still have the completely-empty areas that @Venera3 wants (as do I) provided they were also not close to a road.
> 
> I see, so it is empty countryside that is wanted?

In some areas - variety.

> I could change the other pr to search a closer radius for a road .. perhaps 30 tiles, and remove specials that do not find a road, so it will be filled with farms and rural things but ONLY near the country roads, so there will be plenty of empty countryside. I think it would be possible to force only things that have a road connection to be close to a road, the rest such as mi go towers and fire lookout towers would still be off in the fields etc.

I'd do it as a separate PR, built onto that one - I am suspecting that the existing version will likely go in without too much problems as a bugfix, but going further would be considered more of an added feature and make people nervous about side effects if put into a release.

> I assumed that away from cities, farms would be wanted, since the country side is usually filled with things like that irl, not just gas stations

Contiguous areas of overmap terrain specifying "park" would be nice. Such an area could have most things not appearing there (except gas stations and rest areas along a few roads). As it is, if you expand where farms can be, that will eliminate the parklike areas - moreover, you can't have parklike areas next to a city.

**Comment by stubkan** [comment]
> > I see, so it is empty countryside that is wanted?
> 
> In some areas - variety.

I think, by forcing city-less countryside overmaps to only generate specials by the roads, like gas stations do, they will be their own variation, separate from the countryside...  so a 'column' of built up stuff following the road, then the countryside with only natural stuff and trails, etc..  That'd be a variety to start with and a distinct separation of the natural countryside... good? 

> Contiguous areas of overmap terrain specifying "park" would be nice. Such an area could have most things not appearing there (except gas stations and rest areas along a few roads). As it is, if you expand where farms can be, that will eliminate the parklike areas - moreover, you can't have parklike areas next to a city.

I could do the built up column of farms and rural cabins along the roads I think, but this park biome would be something else.  

But aren't forests kind of already like that?  They have a high weight for pathing through, so stuff tries to avoid it, and the only things that go in them are campgrounds and trails...

**Comment by actual-nh** [comment]
> > > I see, so it is empty countryside that is wanted?
> > 
> > In some areas - variety.
> 
> I think, by forcing city-less countryside overmaps to only generate specials by the roads, like gas stations do, they will be their own variation, separate from the countryside... so a 'column' of built up stuff following the road, then the countryside with only natural stuff and trails, etc.. That'd be a variety to start with and a distinct separation of the natural countryside... good?

Does one see such overmaps when the city frequency is at the default level? They'd only qualify as variety if they showed up with a reasonable frequency. (What may really be needed is something to fluctuate the frequency over several overmaps' worth of terrain - to have some areas with closer together, as with the current default, and some areas with further apart, as with enough to have overmaps without cities.)

> > Contiguous areas of overmap terrain specifying "park" would be nice. Such an area could have most things not appearing there (except gas stations and rest areas along a few roads). As it is, if you expand where farms can be, that will eliminate the parklike areas - moreover, you can't have parklike areas next to a city.
> 
> I could do the built up column of farms and rural cabins along the roads I think, but this park biome would be something else.

Understand.

> But aren't forests kind of already like that? They have a high weight for pathing through, so stuff tries to avoid it, and the only things that go in them are campgrounds and trails...

Parks should not be just dense forest, however - lots of parks have waterways passing through them, and a mixture of areas including heavy forest, light forest, and fields.

**Comment by Venera3** [comment]
Apologies if I was unclear: I don't intend to disparage your other contributions, but you *are* partly reverting a change that had quite a bit of thought put into it. My point is pretty much unchanged: without doing something with the underlying code - either adding scaling, or making farms prettier, or differentiating specials into "special specials" and "rural buildings", or any of the dozen other possibilities - there will always be big compromises to make. The compromise I made in the old, old days of January was to err on the side of optimizing the special spawns for the default world settings to provide higher intra-overmap variance, knowing that it might start coming apart at the seams if the world settings are drastically changed. Your changes would lead to some very jarring edge cases and because of the underlying system of limited special slots would lead to wilderness locations being essentially outcompeted by farms or other high-occurrence specials - the very situation I addressed in the linked PR.

This is not me " ignoring everything here and keep the bugged system, without trying new things or talking about improving it", but me explaining in a hopefully constructive manner why the things you seek to change got the way they are, and what unintended consequences your changes would have.

**Comment by stubkan** [comment]
> Does one see such overmaps when the city frequency is at the default level? They'd only qualify as variety if they showed up with a reasonable frequency. (What may really be needed is something to fluctuate the frequency over several overmaps' worth of terrain - to have some areas with closer together, as with the current default, and some areas with further apart, as with enough to have overmaps without cities.)

Default spacing has something like 4-5 cities per overmap, so it would never be a thing then.  On that setting you don't get empty countryside.  It gradually spaces out depending on both the city size and spacing - both adjust it, since small cities have smaller spacing, so bigger cities, bigger spacing is maxed.  That gives you something like 4-5 empty overmap tiles between cities.  Actually, I don't know, I've only ever found one city on my long roadtrips, but it can get pretty far. So it would only be a thing for people who adjust the spacing and like to have roadtrips, and have stuff spread out. 

But all overmap tiles without a city look the same.  Regardless of spacing - they will always have 3 roads meeting somewhere at an intersection.  And about 2-4 gas stations. a few rest stops, maybe a food cart.  Thats it for the road stuff.  There is quite a lot of empty countryside, with mi go towers, fungal, etc.

**Comment by stubkan** [comment]
>Apologies if I was unclear: I don't intend to disparage your other contributions, but you are partly reverting a change that had quite a bit of thought put into it. 

I get that you are attached to your hard work, and I get that it's been carefully thought out..  I just feel like all the code is aimed toward a specific playstyle and setting, ie play with these settings and everything works fine, but move the chair to the left a little and then the house falls apart.

As someone who only really enjoys the game on high spacing, I got sick of all the broken stuff... so I am trying to make everything work on all the settings that are available to the user.  I'm here to find a way to figure this out, not to undo other peoples work. 

Please offer these ideas about either adding scaling, or making farms prettier, or differentiating specials into "special specials" and "rural buildings", or any of the dozen other possibilities as I would love to hear them and turn them over in my head...  

Like, ideas are good. I'm thinking , based on what you guys have said so far, maybe a set of special jsons that the game would choose from for each overmap, according to certain criteria... ie, if no city found, then choose one of these rural special lists, then it'd fill the map with the specials in that file.  Could be used for city variance as well, an industrial city.  A city with too many shopping malls.  It'd incentivize further exploration.

**Comment by Venera3** [comment]
The potential solutions that came to mind back then, in ascending order of complexity:
- A simple check after the city-building step to the effect of "Is there a city on this overmap at all? If not, proceed to ignore all city restrictions for specials with the `RURAL` flag."
- Using a two-level special placement, with a higher slot allotment for "common" specials like farms and an independent, lower-slot placement pass to add the properly unique things (potentially differentiating on pre/post-Cataclysm-ness instead of rarity)
- Adding a new "farmland" biome, probably with an overmap-randomized occurrence that partly replaces fields and places fencing and farm houses without relying on the special slot system
- Doing something properly fancy with designated zoning for industrial/agricultural/residential areas outside of cities that would restrict certain types of specials to themselves but would boost their spawn chances

None of them are anything resembling trivial, but I'm very much not a coder so I might not gauge that correctly.

**Comment by actual-nh** [comment]
> > Does one see such overmaps when the city frequency is at the default level? They'd only qualify as variety if they showed up with a reasonable frequency. (What may really be needed is something to fluctuate the frequency over several overmaps' worth of terrain - to have some areas with closer together, as with the current default, and some areas with further apart, as with enough to have overmaps without cities.)
> 
> Default spacing has something like 4-5 cities per overmap, so it would never be a thing then.

That's what I was thinking.

> On that setting you don't get empty countryside. It gradually spaces out depending on both the city size and spacing - both adjust it, since small cities have smaller spacing, so bigger cities, bigger spacing is maxed. That gives you something like 4-5 empty overmap tiles between cities. Actually, I don't know, I've only ever found one city on my long roadtrips, but it can get pretty far. So it would only be a thing for people who adjust the spacing and like to have roadtrips, and have stuff spread out.

It would be nice to be able to specify a maximum, average, and minimum for how much area was covered by city (on each overmap). This could at least partially replace the city spacing and sizing controls.

> But all overmap tiles without a city look the same. Regardless of spacing - they will always have 3 roads meeting somewhere at an intersection. And about 2-4 gas stations. a few rest stops, maybe a food cart. Thats it for the road stuff. There is quite a lot of empty countryside, with mi go towers, fungal, etc.

Point.

> I really think bigger spacing should be CDDA default mode... Because... Vehicles are a big part of the game, so.. roadtrips! But it seems people like other parts of CDDA better, since road generation had been broken for a long time

People who go for "innawoods" (in-the-woods settings) seem to be wanting not rural so much as wilderness.

**Comment by actual-nh** [comment]
> The potential solutions that came to mind back then, in ascending order of complexity:
> * A simple check after the city-building step to the effect of "Is there a city on this overmap at all? If not, proceed to ignore all city restrictions for specials with the `RURAL` flag."

For this one, testing (including tweaks to various settings, what had the flag, etc) would probably take longer than the C++ coding.

**Comment by stubkan** [comment]
In regards to the city distance parameters...  Is this distance measured from the center of the city, ie the manhole.. or the edge of the city?  Because I doubt there is something keeping track of the city radius...  And if so, then with the increased city size, these strata city distance parameters are going right out the window when the slider starts moving?  In that case, this pr wouldn't be working properly anyway.

Then perhaps for the city distance thing to work in all cases, it'd need a self referential gauge built in that adjusts it per spacing, I don't know how else it can keep working as intended...

**Comment by actual-nh** [comment]
> In regards to the city distance parameters... Is this distance measured from the center of the city, ie the manhole.. or the edge of the city?

IIRC, the "center" of the city.

> Then perhaps for the city distance thing to work in all cases, it'd need a self referential gauge built in that adjusts it per spacing, I don't know how else it can keep working as intended...

Something to handle adjusted distances being larger than an overmap, or even over half it (75), would probably be needed for this. And/or just making it a separate option, defaulting to 1, that adjusts the effective city distances used.

**Comment by stubkan** [comment]
> > * A simple check after the city-building step to the effect of "Is there a city on this overmap at all? If not, proceed to ignore all city restrictions for specials with the `RURAL` flag."
> 
> For this one, testing (including tweaks to various settings, what had the flag, etc) would probably take longer than the C++ coding.

I was thinking this was the easiest option.

OK,  I will pull the plug on this and go try to work something out

**Comment by stubkan** [comment]
Can this be frozen or something so all the text is kept for me to reference?

**Comment by Venera3** [comment]
Distances are counted from the origin manhole, which is why you can even at the best of times find some specials on the very edge of larger cities (in the map view "to the north of X", instead of "on the northern outskirts of X"). You can only really game it with going *very* strict in your spawn conditions, taking care to add your wanted minimal distance on top of the max city size for the actual minimum distance, and doing the inverse for the max distance and hoping they don't intersect..... That's about where I discarded that line of finetuning and started hoping somebody gets suckered into messing with the code beneath.

**Comment by actual-nh** [comment]
> Can this be marked dont merge / ignore or something so all the text is kept for me to reference? Or should I save it locally

If you close it, it doesn't disappear. It just doesn't show up on the standard screens and is marked as closed.

**Comment by stubkan** [comment]
Thanks for the feedback guys, time to drink more coffee

**Comment by LyleSY** [comment]
Any chance this is worth reviving now?

**Pull request closed without merging**
