### PR TITLE
Distribute beauty mutations to elfa/alpha

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Prettier alpha/elfa mutants"

#### Purpose of change
Per the description of the Transcendant Mutant:
> An experimental subject wearing a surprisingly clean orange jumpsuit. They look unchanged at a distance, but as you approach their head spins towards you with unnatural speed. Their face is disconcertingly beautiful, but their eyes shine with an intelligence far beyond human - and a deep disgust directed at you.

This implies that Alpha mutants are so beautiful that it's almost uncomfortable as if it shouldn't be possible. They currently just get Pretty which is a fair level of attractiveness for a human but nothing abnormal.

Additionally, it looks like ELFA lost "Glorious" and other beauty mutations as they no longer have those in their category.

#### Describe the solution
~~Alpha now gets "Very Beautiful".~~
~~Elf-a again gets "Glorious" which has been made a post threshold mutation as per its description it supposedly has almost mind-control levels of influence over people, and while that is not the case with ugliness currently it could be changed in the future.~~

ELFA caps out at Pretty. Extreme beauty is no longer in ELFA's wheelhouse but as an ALPHA offshoot they should still get a bit of hotness.
Alpha gets Beautiful and Beautiful2. Beautiful2 is locked behind their threshold. Alpha is now the "hot" mutant, which fits them being human+ as they become highly attractive to humans.

#### Describe alternatives you've considered
~~Alpha just gets Beautiful and not Very Beautiful so that it doesn't step on Elfa's toes too much.
Glorious is a pre-threshold mutation instead of being put as a post thresholder.~~
~~Change the way categories are defined for these mutations. I have no idea how this will affect threshold passing and whether or not elfa should get "pretty, beautiful, very beautiful, glorious" or just "very beautiful, glorious". Input is appreciated.~~

Add Glorious to Alpha.
Make Alpha's high level of beauty make people uncomfortable. I think this would be pretty neat but it might be out of scope.

#### Testing
No errors and does not appear to affect thresholding negatively from what I've tried.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
OK, looks like
> mutation_category_id &)] Failed to mutate towards BEAUTIFUL2 because a prerequisite is needed but none are available in category ELFA

So that answers my question.

**Comment by KittyTac** [comment]
This is working as intended, in 0.H experimentals, Elf-A's gimmick will be mind-controlling NPCs rather than simply charming them.

**Comment by anoobindisguise** [comment]
> This is working as intended, in 0.H experimentals, Elf-A's gimmick will be mind-controlling NPCs rather than simply charming them.

Hey, I was looking over this again and realized this comment was ambiguous. Did you mean that Elfas intentionally are no longer pretty because they will just mind control people? Or did you mean it's intentional that Glorious becomes post-threshold because it will have mind control aspects? Beauty was definitely central to Elfa's design, I was curious if that's no longer the case.

**Comment by anoobindisguise** [comment]
KittyTac has said on Discord DM that Alpha is intentionally no longer beautiful. I'll make some adjustments.

**Pull request merged**
