### PR TITLE
Expanded talk_tags.json

### PR DESCRIPTION
**Pull request by PandaBlyat**
#### Summary
Content "Expanded NPC dialogue"

#### Purpose of change
wanted to expand npc dialogue

#### Describe the solution
uhh writing more dialogue!

### CODE REVIEW

**Comment by harakka** [comment]
You need to remove the first line to match the PR template, which is a requirement for the PR to move forward.

**Comment by GuardianDll** [comment]
nah, that's fine, 
what you should do is to lint your changes

**Comment by GuardianDll** [comment]
And yes, you should test your changes before making a request, this one has handful of syntax errors

**Comment by PandaBlyat** [comment]
> nah, that's fine, ~what you should do is to lint your changes~ linted it for ya
> 
> And yes, you should test your changes before making a request, this one has handful of syntax errors
> 
> and for the future, we try to limit PRs to be 500 strings at max, makes it much easier to review for reviewers, 2.5k strings is really lot of text

got it, my apologies. First time contributing :)

**Comment by GuardianDll** [comment]
are you sure you linted it properly? you should put the entire file into <https://dev.narc.ro/cataclysm/format.html> and then paste the output back

**Comment by GuardianDll** [comment]
Why closed?

**Pull request closed without merging**
