### PR TITLE
Metabolism: hunger rate and body temperature

### PR DESCRIPTION
**Pull request by Coolthulhu**
Changes to hunger/thirst:
- Removed the bonus nutrition from hunger. Not only were the numbers absolutely huge (10 times when starving), it doesn't really make sense to gain more nutrition when hungry.
- Lowered hunger rate when hungry. When dying of starvation, the hunger rate will be roughly 50% of the one when fully fed. Scales multiplicatively with mutations, so Extreme Metabolism will become more manageable once you get all skeletal
- Lowered speed penalty from thirst and hunger. Changed them from linear to piecewise linear. It will no longer drop your speed to 25 when you still have a week of starving to do
- Added stat penalties from hunger and thirst. Hunger debuffs strength moderately, int and dex weakly. Thirst debuffs all 4 stats moderately.
- Greatly (factor of 15) reduced the amount of spam when starving/dehydrated/tired. Once per 30 minutes is plenty.

Changes to body temperature:
- Hunger-related temperature penalty now depends on metabolism rate. Light eater will cool you down, fast metabolism will heat you up.
- Having above average metabolic rate will provide bonus heat (ie. heat that doesn't need to be used)
- Reduced message spam from wind - it won't spam when you aren't actually in danger of getting cold
- Doubled morale bonus from getting comfy (it is still tiny, 10 points)

Purely code quality:
- Renamed `player::bonus_warmth` to `player::bonus_item_warmth`, because bodytemp calculations have a variable named `bonus_warmth`
- Added a linear interpolation function `multi_lerp` to cata_utility.h. Takes a sorted vector of x/y pairs (points) and x argument, finds 2 points between which input x is located, then linearly interpolates their y values. Useful for piecewise linear calculations.
- Moderately big refactor of body temperature calculations. Moved most of the stuff that doesn't depend on body parts to the top of the function, out of the loop. Split floor warmth functions up to make it easier to add stuff like automatically getting under blanket when reading or NPCs understanding floor warmth.

### CODE REVIEW

**Comment by ayancey** [comment]
Can I say that this is pretty awesome, and a good idea? Or is that clutter...

**Comment by Zireael07** [comment]
Great!

**Comment by Rivet-the-Zombie** [comment]
It's awesome, not clutter.

**Comment by kevingranade** [comment]
> Having above average metabolic rate will provide bonus heat (ie. heat
that doesn't need to be used)

Unless I'm missing something, heat from metabolism isn't something you can
get rid of at will.

**Comment by Coolthulhu** [comment]
The problem is that our heating system is quite punishing for those with high baseline.

Summers have very hot shade and even hot underground. And even if underground was fine, having to hide there every day with a burning metabolism would be tough for any non-endgame survivor.

I extrapolated the heat loss from hunger in the other way and the result was that in the summer, in a basement, the survivor was taking damage from excess heat while naked.

Having it be bonus heat makes the already really bad metabolism mutations a bit more bearable.

**Comment by kevingranade** [comment]
This doesn't happen IRL, so the question is what are we missing? Is the
effective temperature too high? Is the modeling of homeostasis too weak?
Also I've poked at making some integration tests for this in the past, if
we can sort that out it would be a lot easier to make assertions about the
system.

**Comment by Coolthulhu** [comment]
> Is the effective temperature too high? Is the modeling of homeostasis too weak?

Mostly the fact that most heat bonuses are just flat bonuses rather than something that goes through clothing/fur. Clothing is just a scaled bonus too, it does nothing to capture heat from mutations or metabolism.

In #14605 there are some ideas on how to solve it.

**Pull request merged**
