### PR TITLE
Rebalance CBM drops rates

### PR DESCRIPTION
**Pull request by DziugasPraninskas**
#### Summary

```SUMMARY: Balance "Rebalances CBM drops rates"```
#### Purpose of change

Current implemantation of CBM spawns has a few problems:
1. Bionic vaults in labs use bionics_common item group, which leads to very disappointing CBM finds.
2. Bio-operative has a massively inflated drop table, which leads to getting duplicate bionics very often.
3. There is no almost no difference between looting a military bunker and dissecting a bio-operative.
4. Zombie scientists have some wierd CBM drops (why would a scientist need infrared vision or scent vision?).
#### Describe the solution

In harvest.json, I added a power storage drop to the zombie scientist and upgraded the skeletal shocker and incandescent husk power storages to mk2.
### Bionics_common:
* Removed metabolic, gasoline and ethanol fuel CBMs, seeing as civilians would most likely use Cable (plugging into a wall) or Battery System for fuel.
* Removed Electromagnetic Unit, seeing as that would not be very useful to a civilian.
* Added intelligence, soporific, blood analysis, ups, remote CBMs, seeing as these would be more useful to a upper-class civilian.
### Bionics_sci:
* Removed CBMs that would not be useful to a scientist, such as Infrared Vision, Night Vision, Scent Vision etc.
Bionics_mil:
* In an effort to make military bunker loot feel distinct from bio-op dissection, removed more stealth focused bionics in favor strictly offensive bionics, such as Railgun and Shotgun.
### Bionics_op:
* Removed offensive bionics which the bio-operative does not use, such as railgun, laser, shotgun.
* Removed Teleportation, Probability Travel and Time Dilation CBMs, seeing as these would not be found in use by a regular soldier.
### Bionics_tech:
* Technicians lose enhanced memory and soporific inducer in favor of electromagnet and remote controller.
### Bionics_subs:
* Lost the dex enhancer in favor of EMP projector and Hydraulic Muscles, Skeletal Bracing.
### Bionics_vault:
* Lab vaults contain rare, powerful and useful CBMs.

In monsters.json, changed shocker brute to use bionics_common and skeletal shocker to use bionics_subs.

#### Describe alternatives you've considered

Different CBM drops are definitely possible. I am welcome to suggestions for which zombie should have which CBM.
#### Testing

Loaded up the game, ran item group tests.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> There is no almost no difference between looting a military bunker and dissecting a bio-operative.There is no almost no difference between looting a military bunker and dissecting a bio-operative.

Could you explain further why this is problematic? I don't see any reason why military bunkers would have different CBMs than they would be installing in bionic soldiers.

> upgraded the skeletal shocker and incandescent husk power storages to mk2.

Why would more evolved zombies have these when their less evolved counterparts don't? I think that either all of the normal zombies that drop CBMs should drop them (have a chance to), or none should.

> Removed offensive bionics which the bio-operative does not use, such as railgun, laser, shotgun

Just because they don't use them doesn't mean they wouldn't have them. I'm not sure that these should be removed from them.

**Comment by LaVeyanFiend** [comment]
I'd apply what Kevin planned on(https://github.com/CleverRaven/Cataclysm-DDA/pull/35951#issuecomment-563069598):
image
No more CBMs from shockers 🙁

**Comment by Fris0uman** [comment]
There's a lot of seemingly arbitrary change here, why do the military loses cqb, blade, flashbang, emp and digestion stuff that seem all pretty usefull to a soldire? Why does the commando lose the hack/lockpicking tools, the stealth and face mask CBMs? Why do techinicians lose weight carrying and the farraday CBM that seems pretty usefull if you work with electrical stuff and or carry heavy loads for your work.

**Comment by Amoebka** [comment]
> Infrared Vision, Night Vision, Scent Vision
All of these could be useful to scientists, I see no reason to remove them.

Shockers apparently shouldn't have CBMs at all.

Bioops don't use high-end combat CBMs because they are brainless space zombies, not because they don't have them. Their "intelligence" comes from CQB module, which isn't programmed to use ranged weaponry or fancy experimental stuff.

Bionic vaults in labs should logically have the same CBMs scientists *carry* on them (not have installed).

**Comment by Dziugaske** [comment]
> Could you explain further why this is problematic? I don't see any reason why military bunkers would have different CBMs than they would be installing in bionic soldiers.

Considering how many CBMs CDDA currently has (many I would considering redundant or obsolete), I see a need for a more reliable way of getting them. Right now a vast majority of CBMs are shared between bionics_mil and bionics_op. This means that players won't see a lot of CBMs simply due to the randomness of getting them from military bunkers or zombie bio-operators. By changing the distribution of CBMs, it allows the player to make a choice to go for certain bionics first. For example, if the player wished to acquire CQB bionic for Bionic Combatives, he should focus his efforts on raiding labs and killing bio-operatives. If the player wished to use power armor effectively, he should seek out military bunkers to get Power Armor Interface. Right now we have a limited amount of zombies that use bionics, but other could be added that use more offensive techniques and carry those CBMs. Since the bio-operative fights using a malfunctioning CQB bionic, I interpret that to mean that he belongs to special forces of some kind, where stealth would be paramount.

> Bionic vaults in labs should logically have the same CBMs scientists carry on them (not have installed).

Currently zombie scientist drop from "bionics" item group, which contains almost every single CBM in  the game.

**Comment by Dziugaske** [comment]
I appreciate the discussion and while I clearly have a lot of cleaning up to do, I do want to make it clear that my goal here is to give the player more choice on where to acquire certain bionics from. You could make any number of arguments why a bio-operator might have a certain bionic and not use it, but all it does is dilute the bio-operator's drop table. I believe that players expect certain bionics when venturing into a bunker or dissect a bio-operator and I want to ensure that these bionics show up from time to time.

**Pull request closed without merging**
