### PR TITLE
Adds alternative recipe for fruit juice

### PR DESCRIPTION
**Pull request by chaosvolt**
You should be able to squeeze enough juice from most fruits to get
drinkable results without adding water. Rather than a complete recipe
overhaul I added an alternative recipe. This requires twice the amount
of fruit and can only use fresh ingredients, in exchange for not
requiring water and returning twice the pulp.

Mainly purpose is for the rare situations like that discussed here ( http://smf.cataclysmdda.com/index.php?topic=11006.0 ) where you have access to fruit but not clean water. Spending drink to procure a less efficient drink is an annoyance.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That would require rebalancing the numbers a bit. Look at the current juice stats vs. fruit stats:

What | Nutrition | Quench
---|---|---
1 juice + 2 pulps | 24 | 37
4 blueberries | 65 | 8
8 grapes | 144 | 40
4 cherries | 56 | 8

While some of those are obviously just the result of fruit juice recipe being wrong (8 grapes one), the berry ones shouldn't produce water just like that.
You could bump the amount of pulp produced and/or lower pulp quench (to slightly negative, assuming it's really sweet), while increasing the number of berries required.

Would be good if you actually checked the numbers for all the common (bush/tree) fruit, preferably with a table like I posted. If you don't know how to table, google+"github table" (there's a tutorial and it's a very low amount of work to table results).

**Comment by chaosvolt** [comment]
Hnng. Yeah, this was kind of just a raw, dumb doubling of input.

I guess the main thing is to look at the results and adjust the recipe accordingly. Hmm...

**Comment by chaosvolt** [comment]
Hey wait a bloody minute. I multiplied the amount of juice returned by the waterless recipe by 2 already, so this should be 1 juice plus 4 pulps. >.<

**Comment by chaosvolt** [comment]
New ratios.

What | Nutrition | Quench
---- | --------- | ------
1 juice + 4 pulps | 44 | 39
4 apples | 64 | 12
4 apricots | 64 | 12
4 blackberries | 60 | 12
4 blueberries | 65 | 8
6 cherries | 84 | 12
12 cranberries | 60 | 24
2 grapefruits | 70 | 36
4 grapes | 72 | 20
6 kiwis | 66 | 18
4 mangos | 60 | 12
6 melons | 54 | 24
3 papayas | 63 | 24
5 peaches | 70 | 20
4 pears | 52 | 28
3 pineapples | 66 | 27
4 plums | 76 | 16
2 pomegranates | 54 | 24
4 raspberries | 60 | 12
4 strawberries | 72 | 12
2 watermelons | 30 | 56

These are still very screwy, but not to the same degree as before. Not even sure where to begin with fixing the watered-down juice recipe.

**Comment by Coolthulhu** [comment]
Almost all fruits have way more nutrition than juice+pulp. Bumping pulp nutrition and lowering quench would help.

**Comment by chaosvolt** [comment]
Slow starspawn is slow. Changed pulp from 10 nutrition and 1 quench to 15 nutrition and -4 quench.

Unless pushing it further would be desirable?

**Comment by Coolthulhu** [comment]
Obviously, slowdragon.

Unless your table uses old stats. I think it does, because 4*15 is certainly more than 44 and 4*-4+35 is certainly less than 39.

**Comment by chaosvolt** [comment]
Um...huh. I might've failed to adjust the table right, or do the math. x.x

**Comment by Coolthulhu** [comment]
Average nutrition/quench of all the fruit types in the recipe is: nutrition 63 quench 20
So `4*15+3` looks perfect for nutrition, while `4*-4+35` is only 1 off from the average.

However after deleting "rare" fruits (ones that don't drop from trees/bushes), the averages change to 65 for nutrition, but just 15 for quench, which would be better represented by dropping either pulp quench by another point or juice quench by 4 points.
Since -4 is already really low, nerfing juice here would look better than nerfing pulp more.

**Comment by chaosvolt** [comment]
Hmm. So I see, I guess I could reduce juice quench by a bit, that isn't too loco.

Not sure how the cost of fruit plus clean water will affect the required amounts for the watery version of the recipe, but that can be sorted out once the waterless version is squared away.

**Comment by Coolthulhu** [comment]
Or maybe... change the fruit juice to be 2 charges per stack, have 20 quench and buff back pulp.
That way the watery version could produce 2 juices (for 40 quench) and this one juice and 4 pulps (for 16 quench total). Nutrition per portion could stay.

Though I'm not sure if mapgen would like it.

**Comment by chaosvolt** [comment]
Hmm. Mapgen shouldn't be puking up any errors from stack tweaking, I hope.

Though wait, 2 juices from the water version? I'd need to instead keep the charges at 1 and give the watery version a result multiplier, I think.

**Comment by Coolthulhu** [comment]
There is a separate option to change stack sizes independently from default charges, though I'm not sure if it works for liquids.
And if mapgen wouldn't start spawning half-filled bottles of juice.

**Comment by chaosvolt** [comment]
Hmm. Not sure how the math will work out.

Fairly certain that mapgen should figure out how to fill it based on volume of container, I think. Hopefully. Then again I think liquids exclusively use the charges property without setting stack size.

**Comment by Coolthulhu** [comment]
Minor: juice is 2x as heavy as it should be (1L of juice is 2kg).

**Comment by chaosvolt** [comment]
Doh. Aw well, thank you for the merge. ^^"

**Pull request merged**
