### PR TITLE
Revert #71460 Altered Mindstates partially resist Flaming Eyes

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
Drunkenness as a protective measure is a pernicious and dangerous concept and I will not be party to it.

Mental illness as a protective measure is also extremely problematic, and encouraging people to not take their medication is beyond the pale.

#### Describe the solution
Revert it.

### CODE REVIEW

**Comment by LucioMagno** [comment]
maybe just have kaluptic psycosis only protect you from flaming eyes if you are not hallucinating? that would further incentivise people to take their meds, and would keep this interesting addition.

**Comment by Zireael07** [comment]
Why was something with so many confused/negative reactions merged?

**Comment by MacroLP** [comment]
Pffffftttttttpppppttttt. 👎 its a fucking video game dude.

**Comment by RenechCDDA** [comment]
> Why was something with so many confused/negative reactions merged?

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#project-management

**Pull request merged**
