### PR TITLE
[CR] Update Modular Turrets and Salvaged Robots to match Mainline style and recipes Fixes #35689

### LINKED ISSUE #35689: Modular Turrets needs to update to new robotic parts system
# Describe the bug

With Modular Turrets mod enabled, the Turret Control unit cannot be crafted as all Modular Turrets turrets (which replace CROWS and other other variants) are using outdated uncraft recipes that give RAM and processors still. Modular Turrets and Salvaged Robots needs to be updated to include the newly added module components otherwise the Turret Control Unit is nearly-impossible to craft.

# Steps To Reproduce

Attempt to craft Turret Control Unit with Modular Turrets mod. Realize that Firing Operating system and Targeting module cannot be retrieved from inactive or broken Modular Turrets. Check the repo to notice that Modular Turrets overrides most turret uncraft recipes which would contain the needed parts otherwise.

# Expected behavior

Able to get robotic module parts from salvaged modular turrets to build vehicle turret controls as you would from CROWS or other robotic drones.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9619-g1681742 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]
]

# Additional context

You can still get the parts from killing a chicken walker and maybe a few others, but I'm not even sure if salvage robots changes that as well.

### PR DESCRIPTION
**Pull request by CSHague**
#### Summary
SUMMARY: Mods "Update Modular Turrets and Salvaged Robots to match mainline style and recipes"
#### Purpose of change
Originally intended to fix an issue #35689 - Modular Turrets and Salvaged Robots uncraft recipes contain outdated uncraft recipes that prevent the player from accessing newer items that are components for newer recipes. Eventually turned into an update to get Modular Turrets and Salvaged Robots to match Mainline turret style in terms of uncrafting recipes and ammo drops. 
#### Describe the solution.

- Specifically tried to keep the power sources the same, except for with manhacks which were converted to  use small storage batteries. Plutonium batteries not merged from many entries as microreactors can be uncrafted into plutonium cells.

 -  Modified the uncraft recipes of broken turrets and robots so they will disassemble into newer components to allow the player to access the Turret Control Unit and other future items :
Any turret or robot that can fire a ranged weapon was given targeting and gun control modules; AI cores and other robotic modules were added to the recipes trying to match the tiers shown in main: Simple core for manhacks, regular for turrets and guard bots, and advanced cores for medical robots;  many loose electronics were removed from the disassembly recipes as the new modules can be uncrafted for the same electronic components and turrets and robots were given new chassis components (spider legs, reverse-jointed legs, android arms, et al) As a result scrap metal and electronics removed as these components clearly represent the body. The body parts I couldn't find a rough analogue for I kept as scrap components.

- Military Turrets and robots have had their starting_ammunition increased to approximate with the mainline turrets, 1000 for 308, 1600 for 556. Liquid turrets have been given 10L of ammunition equivalent to a plastic jerrycan. Small pillbox turrets were kept with low capacities as they appear to be "civilian models." Grenade launchers were kept at their default capacities. 

- Added DROPS_AMMO to many turrets allowing them to drop the same amount of ammo as turrets in mainline. This would at least give the player access to a wider variety of ammunition over the military and civilian-use spectrum. Tried to match ammunition volume wise with the mainline turrets.

- Lights were removed from turrets and robots to match mainline turrets. This would be a good spot for another branch to add a craftable spotlight turret.

#### Describe alternatives you've considered

With the breadth of changes made it's hard to speak for alternatives. Removing the override on the corpses would allow the player to salvage regular turrets but they would lose the functionality of the modular turrets. I guess leaving the Modular Turrets deprecated would be considered a reprieve from what some would consider newer "unfair" turrets.

#### Testing
Put this branch through its paces.  Turrets properly drop their ammo when killed except for liquid turrets which is the source of a duping bug and was subsequently disabled. Craftbuddy uses Batteries as ammo, rendering it impossible to load though it doesn't appear to need the ammo to do anything. Updating the craftbuddy is out of the scope of this branch.

#### Additional context
Came across this issue a few days ago while watching a streamer and wanted to take a crack at handling it. This is my first fork and since this is just a JSON edit (while large) it seemed doable. Could use some input on the broken cyborg. 

I eschewed many of the robotic modules in the broken cyborg recipes, as one would expect the human brain component is responsible for most of that, but I added robotic controls to, as some subsystem must be responsible for forcing the cyborg to do things. If I should add an AI core to it as well, that is fine.

Weights and volumes of monsters to the new components need to be adjusted but I can get that with another branch. The volumes for a lot of things in both mods are way off before even comparing them to mainline turrets.

### CODE REVIEW

**Comment by fluffe9911** [comment]
any chance this fixes the issue of the lab entrance turret not going down even if you slide the science card?

**Comment by CSHague** [comment]
Not that I've tested for it, but I doubt it. This is only a JSON edit. That sounds like something that would need to modify the script that runs the consoles. Probably not checking for the right ids or monstergroups

**Comment by Maleclypse** [comment]
Thank you for doing this!

**Comment by CSHague** [comment]
Description says the autoarmor was intended to just walk your armor for you since its AI makes a poor combatant so the frame was probably just assumed to be used by every player.

**Comment by Maleclypse** [comment]
@CSHague can you resolve the conflicts in this PR or do you need some help with it?

**Comment by Maleclypse** [comment]
@LaVeyanFiend Travis is failing a Magiclysm test?

**Pull request merged**
