### PR TITLE
Vehicle funnels

### PR DESCRIPTION
**Pull request by Coolthulhu**
Added a vehicle funnel part. Fills (dirty) water tanks. Unlike solars, it only works in the reality bubble, but unlike solars, it is calculated retroactively.

Acid component of rain is ignored at the moment. Later on it could damage the water tanks or something like that, but now it is just dropped.

Fixed a bug in regular funnels that would cause their water production to scale quadratically with time spent in rain outside reality bubble.
The water produced formula was roughly: `turns_in_rain / ( funnel_parameters / total_rainfall )`. Changed to something along the lines of `1.0 / ( funnel_parameters / total_rainfall )`, which grows linearly with time in the rain.

Added a helper function to rng.h: `divide_roll_remainder( double x, double y )`. Couldn't think of a better name.
It divides x by y, then increases the return value by 1 if `x_in_y( remainder, 1.0 )`.
This kind of operation is repeated in multiple places, like fuel consumption. I didn't replace the existing code, though.

Refactored funnel-related functions in `weather.cpp` a bit. Split off `funnel_charges_per_turn` from `trap::funnel_turns_per_charge` (needed it for the non-trap funnels) into and split off `get_rainfall` from `retroactively_fill_from_funnel` (for same reason). Removed unused function: `rain_or_acid_level`.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woo!

**Comment by chaosvolt** [comment]
Ah, this shall be a very useful addition.

**Comment by illi-kun** [comment]
This PR fixes #11725.

**Comment by kevingranade** [comment]
Actually this is exactly the same as regular funnels, they're retroactively fille when they're loaded onto the map.

**Pull request merged**
