### PR TITLE
Balance fixes/recipes/adjustments and QOL

### PR DESCRIPTION
**Pull request by misterprimus**
#### Summary

```SUMMARY: Balance "various adjustments"```
#### Purpose of change

To fix some things in the game that don't make sense from a realism/balance perspective.
#### Describe the solution

1. Allow crafting of stethoscopes. These are a pain to find, but you can't ever craft them, even though online tutorials show even a child can do it:
https://www.thoughtco.com/make-your-own-stethoscope-2086570
While not exactly something a doctor would ever show to a patient, it seems as though it should work for simple listening as in safe cracking.
2. Secubots and turrets had ammo amounts that were very unbalanced and didn't make much sense. For example the mobile secubot carried only 30 rounds even though this thing was expected to move around autonomously. On the other hand some of the turrets had bricks and bricks of ammo even though they were stationary and that qty of ammo might even overheat/cookoff ammo in the gun if fired continuously (non-continuous firings would easily be remedied by staff reloads). Small amounts were adjusted up, large amounts adjusted down. Now the ammo is between 200-400 rounds. No more 1,500 rounds from defeating a single turret, but the (IMO more difficult) secubots now are actually worth looting, as they should be. This also required changing the secubot to use an M249 instead of an M4 to avoid having it drop STANAG mags which definitely makes no sense compared to a belt-ammo gun.
3. Tank bots were marked "broken" for death purposes, but drops_ammo was not checked. Doesn't really seem consistent with turrets. These should either break and drop ammo or explode and drop no ammo. Not sure if chickenbot should remain EXPLODES or change to BROKEN and flag DROPS_AMMO. Suggestions? I suppose it would depend on whether these are full-on warfare items or more for guarding an American base. Since they are in America walking around, I think making these things explode when destroyed makes less sense since there would be risk of collateral damage to locals. On the other hand, since it happens in the USA, hardly a good reason to make it explode to keep from falling into enemy hands, so changed to broken.
4. Player should get warning before setting alarm and going to sleep if he is deaf (like from wearing ear plugs). Kind of like is presently done for having night vision on.
5. Player should be allowed to wear armor that covers "nothing" even with power armor (like ear plugs).
6. Player should get a warning for trying to drink regular water (unclean). In all my time playing this game, I have only ever drank unclean water a few times, and the vast majority of those were unintentional since often times water tanks and clean water tanks are kept together.
#### Describe alternatives you've considered

Also thought about changing disassembly recipe for secubots and other ammo droppers to not drop usable M4s or M249s since cost-savings features at the factory level would likely dictate that putting in a real "M4" would be a waste since the robot would have no use for the furniture or ergonomic features of the gun, which would only add to weight/volume. However, it looks like assembly of the robots does require those guns (as opposed to "M4 without furniture"), I wouldn't want to create a discrepancy between assembly and disassembly, and I suppose it's possible a real M4 would be used if the robot factory and the gun factory were not collaborating and a decision was made to use surplus items that would be thrown out anyway.
#### Testing

Tested every fix to see if behavior resulted in expected behavior and corrected unexpected behavior accordingly.
#### Additional context

N/A

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Several of these deserve their own PRs.
In my opinion, arbitrarily changing the ammo counts from real numbers is unacceptable.
I know the TALON is based on a real bot, is the m249 version you added based on that and does it have appropriate ammo?

**Comment by anothersimulacrum** [comment]
Also,
> IMO more difficult) secubots now are actually worth looting,

Is an invalid rationale, difficulty should not correlate with value of loot.

**Comment by misterprimus** [comment]
> Also,
> 
> > IMO more difficult) secubots now are actually worth looting,
> 
> Is an invalid rationale, difficulty should not correlate with value of loot.

Can we make it 600?
https://www.brookings.edu/articles/military-robots-and-the-laws-of-war/
"Fully loaded, it costs $400,000 and carries a machine gun with six hundred rounds of ammunition"

Not sure if there is other literature available for drone ammo capacity.

**Comment by misterprimus** [comment]
> Several of these deserve their own PRs.
> In my opinion, arbitrarily changing the ammo counts from real numbers is unacceptable.
> I know the TALON is based on a real bot, is the m249 version you added based on that and does it have appropriate ammo?

Didn't realize there were such drones in operation with publicly released specs (thought they were military secrets or something). Do you have any info besides what I found?

**Comment by esotericist** [comment]
Several unrelated changes in the same PR is not appropriate.

If you're doing multiple changes, they either need to be related to a single purpose, or actually rely on one another for function. This is necessary for both tracking and review purposes. No grab bags of randomly changes.

Further, as anothersimilacrum states, "difficulty" is not valid a reason to make arbitrary changes, especially changes to aspects that have been researched.

the ammo counts that dropped have a basis. whether you agree with that basis or not, you need specific evidence in the PR to suggest your change to ammo drops is more correct from a factual standpoint, not a vague "it seems better" standpoint. keep that in mind if you attempt to open that aspect in another PR.

**Comment by misterprimus** [comment]
> Several unrelated changes in the same PR is not appropriate.
> 
> If you're doing multiple changes, they either need to be related to a single purpose, or actually rely on one another for function. This is necessary for both tracking and review purposes. No grab bags of randomly selected changes.
> 
> Further, as anothersimilacrum states, "difficulty" is not valid a reason to make arbitrary changes, especially changes to aspects that have been researched.
> 
> the ammo counts that dropped have a basis. whether you agree with that basis or not, you need specific evidence in the PR to suggest your change to ammo drops is more correct from a factual standpoint, not a vague "it seems better" standpoint. keep that in mind if you attempt to open that aspect in another PR.

OK, didn't realize it was a requirement to post these separately. Will repost separately with support. Thanks!

**Comment by esotericist** [comment]
> OK, didn't realize it was a requirement to post these separately. Will repost separately with support. Thanks!

Yeah, if *some* of your changes were acceptable as is, *some* would need changes to be acceptable, and *some* were unacceptable, we wouldn't be able to merge the ones that are until the other things got fixed or removed.

Everyone's life (including the contributor) is cleaner when things are properly separated.

**Comment by esotericist** [comment]
Also, important note: the way you assembled strings in your c++ changes are not correct for localization. You *cannot* concatenate strings in that fashion, it's not translatable.

**Pull request closed without merging**
