### PR TITLE
Changes some grammar in the LED Tattoo and tweaks its balance

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
 ```SUMMARY: None```

#### Purpose of change
Yessss, new CBMs. One step closer to becoming the bionic queen. It's neat, but had some formatting and wording craziness that I thought could use some fixing up, and it's slightly too weak for its power consumption right now.

#### Describe the solution
I rewrote the descriptions for the LED Tattoo and fixed the formatting issues it had. I also changed its power cost:
* Reduced the power consumption to 1/50 turns instead of 1/25 turns; the Cranial Flashlight is running at full power and costs 25 turns, so I think it's too much for a dim light.

@Fris0uman has the final say on these changes, so Fris, if you don't like parts of it, let me know and I can close this if you want.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Thanks for pinging me ^^.
So the idea of this was directly stolen from Shadowrun from the Chrome Flesh 5E book [pic related](https://imgur.com/ynd2kxC) .

And it was kind of useless on purpose, I mean it's just a tattoo that glows in the dark. I'm not sure it's reasonnable to expect to be able to read normally in the dark with it. I might try to make `fancy` cbms a thing as a follow up to this but that seems non trivial.

The decrease on power consumption seems to make sense.

Regarding the new description it would be cool to keep the idea that the pattern of the tattoo can be whatever we want ( even if it's meaningless in term of gameplay) and I think it would be better to not say where the tattoo is, because it could be anywhere so we can leave that to the player imagination.

If you want to keep it as a possible reading light maybe put something in the description on how now you could crank up the intensity of the light to use it to read and craft. Like if it was an especially swanky tattoo that can glow brighter than the usual model or something.

**Comment by Ilysen** [comment]
Sure, I can make those changes. I'll change the description to fit that.

I wanted to keep a reading light possible since that seemed to be a good use for it, mechanically speaking. If it's an LED, its brightness could theoretically be changed quite a bit, and I thought it gave an interesting use to it.

**Comment by Ilysen** [comment]
I had an idea while sleeping earlier of a replacement CBM for reading lights that could theoretically work as a replacement, thematically. Would you like me to keep the tattoo as shady, and have those reading lights as their own thing?

**Comment by Fris0uman** [comment]
You mean adding a reading light CBM ?
Personally I'm happy with the changes you made so you can keep it as it is or split in two CBMs a usefull reading light and a dim semi-useless tattoo. 
Or do both, I don't know if redundant CBMs are a bad thing or not.

**Comment by Night-Pryanik** [comment]
IMO making this CBM allow to read and craft at dark is OP. This way it removes the need for all lightning sources altogether for reading and crafting.

**Comment by Fris0uman** [comment]
You still need to find it, install it, and power it. Sure it's the easiest CBM to install in the game but it will still consume power.
Atomic Night light is probably still better, even if it's more cumbersome.

**Comment by Ilysen** [comment]
Reading lights already kind of do that, since they take up basically no space and a UPS mod can be attached to make them run off of bionic power. Candles are also craftable at a very modest skill to serve the same purpose. Personally speaking, I feel that needing to worry about light for reading and crafting is only relevant early-game, and by the time you have the power and materials to install this bionic under the default system of the Autodoc, it'll already no longer matter and will serve mostly as QoL.

**Comment by Maddremor** [comment]
While I have no issue with a reading light CBM, it should probably be a bionic made for actual illumination. A bionic tattoo feels more like a cosmetic/fluff thing. A low power cranial light, or a tight beam ocular lamp seems like a better approach to a functional tool.

**Comment by Ilysen** [comment]
That's a good enough point that I'll tweak the values back to their old ones! It also gives me a better idea, regardless, so I'll look to implement something else in the future.

**Pull request merged**
