### PR TITLE
Modernized School

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
```SUMMARY: Content "Modernized school"```

#### Purpose of change
The school itself wasn't really updated since it was first added.

#### Describe the solution
* Added 2 new floors and a roof
* Added lots of new terrain and furniture
* Added a working school bell system
* Classrooms can fit 30 students instead of 12
* 2 new classrooms
* New rooms such as
   * school nursing room
   * various gym related rooms
   * file room
   * 2 smaller meeting rooms
   * IT classroom
   * storage room
   * mechanical room

Also, schools will spawn way less zombies now.

#### Describe alternatives you've considered
Scrap the old school *(heh)* and make a new one from scratch.

#### Additional context
It kinda resembles the original school.
1floor
2floor
3floor
4floor

### CODE REVIEW

**Comment by curstwist** [comment]
Impressive.

**Comment by Night-Pryanik** [comment]
> make a new one from scratch.

Another variant will always be welcome.

**Comment by curstwist** [comment]
My first thought was why not a variant too. But if we keep both, the old one will probably be preferred for its easy library access. I like that this makes it a much bigger risk so I'm in favor of replacing it.

**Comment by Night-Pryanik** [comment]
> the old one will probably be preferred for its easy library access.

I'm pretty sure people will prefer school that is located nearby, not the one that has some advantages.

**Comment by paulenka-aleh** [comment]
Wow, that looks more like a school than before.
No underground shelter here? No showers near stadium / changing rooms? Is it a boiler room on the top floor, maybe it would fit better underground?

> I'm pretty sure people will prefer school that is located nearby, not the one that has some advantages.

No all. My parents choose a school 30 minutes away due to English classes available there instead of 3 other schools closer. I changed that school after 6 years and was taking 30 minutes subway across the city to reach another school. Sister didn't go to closest school either. There are always some people who make a different choice.

**Comment by Night-Pryanik** [comment]
> No all. My parents choose a school 30 minutes away due to English classes available there instead of 3 other schools closer. I changed that school after 6 years and was taking 30 minutes subway across the city to reach another school. Sister didn't go to closest school either. There are always some people who make a different choice.

I meant post-Cataclysm people.

**Comment by JennyBundrick** [comment]
> I meant post-Cataclysm people.
What are we, a bunch of animals?! Just because the apocalypse came and went doesnt mean we get to choose our schools all willy nilly! We use the one in our given zip codes like TRUE AMERICANS.

**Pull request merged**
