### PR TITLE
clarify repeater mod installation and add another quest for them

### LINKED ISSUE #70170: Radio repeater mod does nothing when interracting with a radio station computer
### Describe the bug

Radio repeater mod is obtainable from the "plans for a radio repeater mod" by crafting. If crafted and going to a radio station, the "Install Repeater Mod" selection does nothing. If you don't have it in your inventory, it displays a message saying you don't have a repeater mod.

I've also noticed that it does use in-game time when you select the option to install the repeater mod. So maybe the functionality is broken and doesn't throw any errors?

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Go to a radio station with capability to install repeater mod
2. Give yourself a radio repeater mod
3. Try to install radio repeater mod
4. Nothing happens

### Expected behavior

I expect the repeater mod to actually do something.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KeremBabaG**
#### Summary
Bugfixes "clarify repeater mod installation and add a vanilla quest for them"

#### Purpose of change
Closes #70170. Appearently the repeater mod installation in radio stations are only for two necropolis(rip) quests that are moved into no hope. This adds a reason why you couldn't just install it.

#### Describe the solution
Clarify why you couldn't install it otherwise. I'l also add a repeating quest for old guard representative.

#### Describe alternatives you've considered
Don't do this and give repeaters an actual use instead of being a mission objective.
or fucjking restore necropolis to main game idk

#### Testing

resim_2023-12-13_120416556

Ekran görüntüsü 2023-12-14 214704

Quest works as well.

#### Additional context
~~Please give some ideas in the comments about who would want to install a repeater. Maybe the old guard again in the refugee center?~~
Old guard representative will have repeating quest.

### CODE REVIEW

**Comment by Vaskritaya** [comment]
Couldn't the manual and recipe just be moved to the mod as well?

**Comment by KeremBabaG** [comment]
>Couldn't the manual and recipe just be moved to the mod as well?

No_hope uses it. Gotta ask night praynik first. Also adding a quest for it is a better solution imo

**Comment by KHeket** [comment]
> Please give some ideas in the comments about who would want to install a repeater. Maybe the old guard again in the refugee center?

May Rubik would ask you to install a repeater or something like that to communicate with his cyborg workers to make them teamwork against the blob? Or at least to teamwork cyborg workers to slowing blob spreading down to have more time before another teleportation of Rubik to the next world?

**Comment by Vaskritaya** [comment]
> > Please give some ideas in the comments about who would want to install a repeater. Maybe the old guard again in the refugee center?
> 
> May be Rubik would ask you to install a repeater or something like that to communicate with his cyborg workers to make them teamwork against the blob? Or at least to teamwork cyborg workers to slowing blob spreading down to have more time before another teleportation of Rubik to the next world?

Playing off this idea, maybe the repeater could be used as a method to get directions to the exodii warehouse during that mission? iirc, it's intended that you can get directions there, but no methods have been implemented yet so you just kinda have to find one while driving around currently. Main reason its not a global unique yet.

**Comment by PatrikLundell** [comment]
Given that the Exodii have their own transmitters on their warehouses, I don't find it that credible that they'd want to use terrestial infrastructure or have the knowledge of how to interface to it (each technological world would probably have a slightly different implementation, and they'd probably not know what the current one is unless they've sent a mission off to find out).
I don't think the (somewhat annoying) warehouse finding mission should be able to give you directions. If I recall correctly, they can't give you directions because they don't know where it ended up: if they'd known where it ended up they wouldn't need your help. A repeater won't be useful in locating it if the transmitter on the warehouse isn't working (but it would if a booster stage wasn't working, so the signal was too weak to be detected), but in that case they ought to need several repeaters to provide range extensions for several directions (as they don't know where it ended up).

**Comment by Vaskritaya** [comment]
> I don't think the (somewhat annoying) warehouse finding mission should be able to give you directions. If I recall correctly, they can't give you directions because they don't know where it ended up: if they'd known where it ended up they wouldn't need your help.

Yeah, I'm pretty sure it was intended that you would be able to get directions from free merchant traders who have happened to see it on their travels, or something to that effect. I was just spitballing a broad idea of relating the repeater to the mission somehow as well.

**Comment by KeremBabaG** [comment]
alright then I'm going through with the old guard idea

**Comment by KeremBabaG** [comment]
added a new function called has_mission_id because I couldn't figure out reading the entire iterator before doing the else. Hey maybe it'll be useful to someone someday. Otherwise can someone that actually knows c++ lend me a hand here

**Pull request merged**
