### PR TITLE
Adjusts height display in character creation menu to respect imperial/metric settings & removes instances of 'pair of' in names of singular items to increase readability

### LINKED ISSUE #60443: Character height doesn't always respect metric/imperial setting
### Describe the bug

On the final screen of the character creation wizard, it's hardcoded to show your height in centimeters.

### Steps to reproduce

1) Configure `Settings->Interface->Distance units' to imperial.
2) Create a new character
3) On the final character creation screen, note that the character's height is 175 (or whatever) cm.
4) After the game starts, press `@' and see that the height is displayed as 5'9".

### Expected behavior

If the distance units are imperial, the height should be displayed as 66 inches or 5'9"

### Screenshots

_No response_

### Versions and configuration

Linux, last commit is 60820c9a4a82778b481ab277020e9d12fd0ea501. Version 0.F-10847-g60820c9a4a.

### Additional context

In-game, the character information screen ('@' menu) shows the character's height correctly- 5'9" or 175cm depending on the metric/imperial setting. But in `newcharacter.cpp:draw_height()', it's hardcoded to say it in centimeters. I would consider fixing this by centralizing the code in something along the lines of Character::height_to_str().

### LINKED ISSUE #61220: Remove "Pair of" for singular pair items
### Is your feature request related to a problem? Please describe.

I think that having a lot of apparel using "pair of..." in their name when it's only a singular pair clutters the hud of many menus, like inventory or pick-up, unnecessarily. I think that it's already clear to the player when most apparel items are a pair, and the description menu clearly states if an item covers both pair of limbs.

### Solution you would like.

Simply remove "pair of..." from an item name when it's a singular pair, keep it for plural pairs.
Example:
"Pair of socks" -> "Socks"
"Pair of pants" -> "Pants"
When there's multiple pairs, keep it
"2 pairs of socks"

### Describe alternatives you have considered.

Nothing, leave it as it is. But i think that changing this greatly improves the readability of most menus.

### Additional context

I didn't check the git if this has been previously brought up, i apologize in case.

### PR DESCRIPTION
**Pull request by ruben-hernandez-jr**
#### Summary
Content "Adjusts height display in character creation menu to respect imperial/metric settings & removes instances of 'pair of' in names of singular items to increase readability"

#### Purpose of change

Fixes #61220 
Fixes #60443

#### Describe the solution

For the first issue, this change removes all instances of the phrase 'pair of' in the singular case of item names.
For the second issue, these changes change the displayed height in the character creation menu to appear in feet and inches when the measurement settings are set to imperial. Furthermore, the popup menu for editing height by keyboard has been adjusted to accept input in inches, rather than only centimeters.

#### Describe alternatives you've considered

We can change the pop-up menu for height input to accept input for both feet and inches when the measurement settings are in imperial. 

#### Testing

I ran the code in all possible measurement settings to check how the height was displayed. I also interacted with NPCs to view the items they had, in order to check for instances of the phrase 'pair of'.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Tô help with reviewing it’s generally preferred for disparate fixes to be separate PRs. Would that be alright? Basically your c++ changes have nothing to do with your json “pair of” changes.

**Comment by ashGlaw** [comment]
Fixing the character creation height in centimeters is a good idea. Thank you for doing that

**Comment by Maleclypse** [comment]
If you need any help with any of these suggestions we are happy to help.

**Comment by ruben-hernandez-jr** [comment]
> Tô help with reviewing it’s generally preferred for disparate fixes to be separate PRs. Would that be alright? Basically your c++ changes have nothing to do with your json “pair of” changes.
I understand, I'll redo my changes to submit them as separate pull requests.

**Comment by ruben-hernandez-jr** [comment]
> In general you should avoid creating commits directly on your master branch. Instead you are recommended to create new branches where you make your changes, and submit pull requests from the branches you created. Otherwise after the pull request is merged, you'll have conflicting master branches between the main repository and your fork.

Thanks for the advice! I'll be sure to do that in my new version of the pull request.

**Pull request closed without merging**
