### PR TITLE
Translations template update + fixes

### LINKED ISSUE #15544: "DANGER! MINEFIELD!" is not translatable
On the master, here are no references to "DANGER! MINEFIELD!" in the `pot` file.

### LINKED ISSUE #15626: Wrong invalide JSON escape in data/json/mapgen/roadstop_a.json
Line 53.
`"i": "This was once a infromation map for the \<city\> area, but it has long since been eroded beyond usefullness. There are small holders for tourist maps attached."`

So this `\<city\>` is invalid JSON escape sequence. I can't update translations template due Python JSON parser will raise exception. I can ignore this file but this is wrong.

Where this part of mapgen JSON is used? May be we can do `\<city\>` => `<city>`

### PR DESCRIPTION
**Pull request by VlasovVitaly**
Translations template update.
And...
fixed #15544
fixed #15626
both issues can be closed.
Python extractor was fixed too.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Maybe also make translatable `place_signs` in hardware1.json, house_duplex.json, park.json and teashop.json?

**Comment by VlasovVitaly** [comment]
ok. Let's try. WIP now.

**Comment by VlasovVitaly** [comment]
Done. But unfortunately without of any usefull comments for translators. Can't get something usefull from mapgen object.

**Comment by Night-Pryanik** [comment]
Thanks a lot!

**Pull request merged**
