### PR TITLE
Gold description correction

### PR DESCRIPTION
**Pull request by 91247686**
Corrected "hard shiny metal" to "soft shiny metal"

### CODE REVIEW

**Comment by 91247686** [comment]
Need to figure out how to remove those unnecessary commits.

**Comment by Cyrano7** [comment]
@91247686  Maybe this can help get you started.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#example-workflow

**Comment by 91247686** [comment]
Those commits are still there, but they don't actually change anything, so I think it's fine. 
I'll certainly be more careful about keeping my master branch clean in the future.

**Comment by BorkBorkGoesTheCode** [comment]
@91247686  git rebase -i 11c9b93dc1e5ac4ddf02fe463ffe3a97da2172d9~ in the git console, delete every commit before "merge pull request 1" from the resulting text file, then save the text file using save (not save as).

**Comment by BorkBorkGoesTheCode** [comment]
@91247686 You'll need to git push --force to update this pull request, but only do so after creating a backup branch of your PR.

**Comment by BorkBorkGoesTheCode** [comment]
Oh shit.

**Comment by 91247686** [comment]
Yep, I done goofed.

**Pull request closed without merging**
