### PR TITLE
Ability to remove tires without a jack if character have enough strength.

### PR DESCRIPTION
**Pull request by DZiral**
At this moment installing tires don't require jack at all. I unsure if this need to be changed (to use jack or strength) or must be keep as is.

### CODE REVIEW

**Comment by kevingranade** [comment]
Sanity check.  What's the strength required for changing a tire on an
ordinary sedan?
How about a big truck?

**Comment by DZiral** [comment]
Ordinary car about 18-21 str, trucks 50 or more. See table:
Motorcycle (motorcycle_sidecart) - 8 str
Hatchback (car_mini) - 13 str
Car (car) - 18 str
Electric car (electric_car) - 20 str
Police car (policecar) - 20 str
Suv (suv) - 21 str
RV (rv) -34 str
Semi truck (semi_truck) - 57

**Comment by kevingranade** [comment]
That seems a bit low then.  This is the strength required to lift the
vehicle with one hand and install the tire with the other, not just the
strength required to lift the vehicle.

**Comment by DZiral** [comment]
I think average people (str 8) can change motorcycle tire without jack. And someone really strong (or with powerful bionics +20 str) can do this with ordinary car. Not whole car must be lifted, only one side a little. Also we can assume what something (stone, bricks, anything found in wilderness) put under car to keep it lifted during tire change process. Maybe something used as a lever in process. This is why I decide use 40 as strength coefficient.
What values you purpose?

**Comment by kevingranade** [comment]
Don't assume something to prop the vehicle up with exists, we track little
stuff like that.  If you want to make the strength check based on whether
the player can lift the vehicle and put a support under it, add a
requirement to have the support.  If you want to assume the use of a lever,
add a requirement to use a lever and a fulcrum.
Otherwise the scenario is lifting the vehicle with one hand, and the
strength checks should be something like 6 higher.

**Comment by jaked122** [comment]
We should be able to prop up cars with stones though. I really like that idea.

**Comment by DZiral** [comment]
May be use 30 as coefficient? Without assumption for levers and other stuffs. Strength values will be something like this:
Motorcycle (motorcycle_sidecart) - 6 str (look like I put have wrong value in previous table, valid is 4, not 8)
Hatchback (car_mini) - 18 str
Car (car) - 24 str
Electric car (electric_car) - 26 str
Police car (policecar) - 26 str
Suv (suv) - 21 str
RV (rv) -45 str
Semi truck (semi_truck) - 76

And what about installing a tire? This can be done without jack, current requirements same as install any other part. Do this need to be changed, or this is normal?

**Comment by kevingranade** [comment]
Yea that sounds like a reasonable ballpark.
And yes, the jack missing from wheel installation is a bug.

**Comment by DZiral** [comment]
Adjusted strength needed to work with tires and add checks for jack/strength when installing tire.

**Pull request merged**
