### PR TITLE
Change death [explosion]

### PR DESCRIPTION
**Pull request by pisskop**
The current radii are ridiculous.  And deadly to melee players.  And awful.

This changes to something a little more reasonable, with huge tanklike robots exploding for 12 radii, and tiny ones for 1 radius.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It's not radius. The power at a point at distance `n` is `power * (0.8^n)` by default. Explosion stops propagating below power 1.
So 26 power is radius ~15, with power dropping to just 4 at range 8.

I'll need examples of this explosion being too strong and information how this does fix the issue.
Because if it is mostly about melee, it may be better to just drop the explosive death.
It would be very simple to adjust the explosion factor, which could be used to control how much it spreads.

Alternatively, it would be simple to add a `death_explosion` field to all monster types and make it customizable, using same syntax as item explosions (grenades etc.), including allowing them to send shrapnel on death. I can lead you through that if you're interested.

**Comment by pisskop** [comment]
Well, I knew it wasnt radius when I started playing actual characters with it.

Power 12 is a grenade.  Well, power 12 and 2 shrapnel is a grenade.

Id much rather not have each mon exploding, unless this allowed us to customize death field emissions like you can with explosions.

I could merely change it back, lowering the numbers by 3-6 each.  Tankbots would be 20.  Still dangerous, but not taking off 30 health points just for being strong enough to kill it in melee.

**Comment by Coolthulhu** [comment]
Number tweaks need some sort of goal, not just "up" or "down". How much damage should it deal at what range?
Doesn't need to be exact numbers, but going by gut sense is the wrong way to go.

**Comment by pisskop** [comment]
Now we come to problems.  Something shot by armor piercing bullets and something stabbed in the face-radar are not going to explode the same way - if at all.

And furthermore, even things with the ability to purposely 'self-destruct' would not be built for this purpose, unless it was their primary purpose.  tankbots are definitely not.  Secubots even less so.

**Comment by Reclusive-reptile** [comment]
And spot lights don't make sense exploding at all.

**Comment by pisskop** [comment]
Im happy enough with these current settings.  The explosions of secubots tankbots and modded creatures were all equally ridiculous, and we could even add in an explosive death for hacks now

**Comment by Coolthulhu** [comment]
I still need some data on this.

What do you want to achieve here? What are the expected damage numbers at what distance?
What armor do you assume the player is wearing?

Number tweaks like "down because IDK it's too strong" will break if this section is rebalanced again for any reason. We need at least some data points to balance around.

Something like:
* Character wearing hoodie+underwear+jeans should not take more than 30 damage to torso or head when in melee range of a secubot explosion
* Tankbot death explosion should never deal 80 damage to any body part to any unmutated character

Or something like that.

If it doesn't have a use case but just "kinda less", it will break whenever something changes to the explosion system, since it doesn't even have a set of items to be balanced around (unlike say, bomb hacks).

**Comment by pisskop** [comment]
I want to come back to this, but am unwilling to produce definite numbers at this moment.

**Pull request closed without merging**
