### PR TITLE
Add gendered_line to dialogues

### PR DESCRIPTION
**Pull request by Uwuewsky**
#### Summary
I18N "Adds a gendered_line to some dialogues."

#### Purpose of change
[gendered_line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md#grammatical-gender) 
> For NPC dialogue some languages may wish to have alternate translations depending on the gender of the conversation participants.

#### Describe the solution
After this PR, separate entries should appear in the translation files for different genders of participants.

#### Testing
The changed files have been linted, extraction from them works, the .po file has been created with the additional entries, game loads .mo correctly.

#### Additional context
At the same time I changed a couple of lines in the files: Mangalpreet/Vanessa Toby/Jack Isherwood. There were either some cryptic concatenations or non-working hacks for gendered_line.

### CODE REVIEW

**Comment by GuardianDll** [comment]
What is the point of gender line, related to npc gender, used in NPCs that has their gender defined?  Since gender is always the same, there would be no option where it would be different

**Comment by Uwuewsky** [comment]
Which NPCs?

NPCs with a predetermined gender have modified dialogues that only refer to the player's gender (`"related_genders" = [ "u" ]`)
As far as I understand (due to the absence of a "gender" field in "npc" json), even some NPCs with unique names have a random gender, like Glooscap. Am I wrong? Can this be defined somewhere else?

Gender line, related to npc gender only used for random npcs unless I made a mistake (I checked the patch several times tho)

**Comment by Maleclypse** [comment]
Can you add some documentation that this won't require gendered translation for languages that lack certain genders?  That way we don't have languages that only gender one way having multiple copies of the same line?

```
The problem is that almost all of its documentation is in code and there's no fallback so you have to copy the translation for every gender even if it doesn't make a difference in that particular case. For the one sentence that used that feature, some translators have copied the line even though it's not needed at all for their language and it has actually introduced some discrepancy in one case (korean).

So it'd be nice if translators were made aware that they don't need to translate genders that aren't in their language, before that PR makes its way to transifex
```

**Comment by Uwuewsky** [comment]
@Maleclypse 
This feature is already documented. If we need to convey this information to translators, then I might suggest adding a link in the comment for each gender line (comments are visible to translators), like this:
```
#. ~ NPC dialogue line
#. ~ You don't need to translate genders that aren't in your language, check: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md#grammatical-gender
#: data/json/npcs/TALK_NC_FARMER.json
msgctxt "npc:n u:m"
msgid ""
"Hey, you're alive!  Me too.  Been a long while since I've had a "
"conversation.  Uh, with someone else.  Um."
msgstr ""
```
I have already implemented this, this is a real example. If this is what is needed, I can push this commit directly into this PR. Tell me if the hint text needs to be changed.

**Pull request merged**
