### PR TITLE
yowshi

### PR DESCRIPTION
**Pull request by yowshi**
#### Summary
SUMMARY: Added soap flakes recipe which could be used in a washing machine.

#### Purpose of change
It's a bit ridiculous that we can't use basic soap in washing machines, people used to use normal soap to wash clothes long before detergents were a thing.

#### Describe the solution
Some C++ work would be needed to allow washing machined to use them but i did add soap flakes and a recipe to make them to the JSON files.

#### Testing
The soap flakes item is in there but i can't test them in a washing machine yet.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I will do the C++ work to make this function.

**Comment by Fris0uman** [comment]
Could you change the title of the PR so that it actually give some info about the content?
Also it seems you have changed the whole files instead of just adding new recipe, passing it through the linter might fix it.

**Comment by yowshi** [comment]
i did pass the code through the linter. when i was reading the guidelines about how you're supposed to format the JSON files i got worried so i did a copy and paste of the files into the linter and checked em.

**Comment by AMurkin** [comment]
PR was made from a not clean old branch. It may be easier to redo in the new branch after updating the master branch.

**Comment by yowshi** [comment]
can someone close this pull request then while i figure out how to do that?

**Pull request closed without merging**
