### PR TITLE
Save and prune mapbuffer

### PR DESCRIPTION
**Pull request by kevingranade**
Obsoletes #19966 
This was always the intended behavior, but I somehow forgot to add it.  On each map shift, it saves all the submaps if necesary and prunes ones not near the loaded map.
Also drops the now-unecessary popup dialog since there will never be  significant backlog of submaps to write out.

### CODE REVIEW

**Comment by Zireael07** [comment]
> I somehow forgot to add it

This explains why saving would sometimes take 10+ minutes on a shitty windows computer I played on during the holidays...

**Comment by kevingranade** [comment]
Yes, the current behavior is submaps are not pruned unless you save or
quicksave, so if you move around a ton between saves it starts adding up.

**Comment by Coolthulhu** [comment]
On Windows, with z-levels on, this causes a very noticeable stutter when driving a car, worse than one that comes from mapgen.
It happens all the time, even on empty fields.

Tests on GNU/Linux won't show the stutter all that well since it's just Windows that fails at HD access. Or maybe just synchronous HD access.

Could it be an option instead? Having few seconds of inactivity every x minutes of play is much less straining on sanity than having parts of it forced every few keypresses.

**Comment by kevingranade** [comment]
OK, if there are performance problems sometimes there are some
optimizations I can add, an option would just mean people can opt out of
poor performance in one place around arednddd it elsewhere.
Worst case is write out in pauses between player inputs, but I doubt
that'll be necessary.
I'll see if I can repro poor performance on my windows netbook.

**Comment by Coolthulhu** [comment]
> an option would just mean people can opt out of poor performance in one place around arednddd it elsewhere

Breaks and load times are much less painful in bulk.

Would it be possible to have all those writes happen on a separate thread instead?

**Comment by kevingranade** [comment]
> Breaks and load times are much less painful in bulk.

Perhaps, but my point is its fixable, the version you tested was writing out ~256 submap quads at a time, the current version writes out 60, and since then I realized I can drop that to 11.  The version that writes 60 has no noticeable lag on my very underpowered windows netbook (the 256 version did), so I'm confident that my last idea (just writing out the trailing edge(s) on shift) will completely eliminate any issue.

> Would it be possible to have all those writes happen on a separate thread instead?

Possible yes, advisable no.  If we need to move this outside the main render loop, it's much simpler and safer to just do some writeout when waiting on user input.

**Comment by Coolthulhu** [comment]
> Perhaps, but my point is its fixable, the version you tested was writing out ~256 submap quads at a time, the current version writes out 60, and since then I realized I can drop that to 11.

What about Z-levels?

**Comment by kevingranade** [comment]
On Jan 24, 2017 11:29 AM, "Coolthulhu" <notifications@github.com> wrote:

Perhaps, but my point is its fixable, the version you tested was writing
out ~256 submap quads at a time, the current version writes out 60, and
since then I realized I can drop that to 11.

What about Z-levels?

That bumps it back up to ~250 quads, but the majority of those are going to
have the uniform flag set.  Apples to apples the code you tested was saving
~5,250 quads with z levels enabled, so expect a ~20x speedup (current code
in the pr will save ~1,260 quads per shift, maybe not so good).  I'll be
sure to test my new code with z levels as well, and if it's laggy I'll look
at deferring writeout until we're waiting on user input.

**Comment by AMurkin** [comment]
So in case of game process stop (crash or exit) there will be dupes of items or missing items if player moved from one (saved) map tile to another?

**Comment by Coolthulhu** [comment]
At 20x speedup it should be tolerable, though there may be extreme cases that will still be slow.
One such case would be player leaving an overstocked base.
Another one is people having saves on very slow media, like USB drives. Do we support those?

**Comment by Zireael07** [comment]
> Another one is people having saves on very slow media, like USB drives. Do we support those?

That's a good question (I take a spare copy of CDDA on a USB stick with me to the resort since there is nothing to do in the afternoons)

**Comment by kevingranade** [comment]
> So in case of game process stop (crash or exit) there will be dupes of items or missing items if player moved from one (saved) map tile to another (not saved)?

This is currently going to happen to an extreme degree, impacting every submap touched since the most recent save, after this change the impact will be minimized to submaps still in the immediate vicinity of the player.

Re: performance, I implemented "trailing edge writeout", but it's still unacceptably slow on my netbook with z-levels on, I'm going to investigate to make sure I don't just have a bug, but it's starting to look like lazy writeout while waiting for input is going to be the answer.

**Comment by mutability** [comment]
> This is currently going to happen to an extreme degree, impacting every submap touched since the most recent save, after this change the impact will be minimized to submaps still in the immediate vicinity of the player.

I think you have this backwards. The status quo is that a crash between saves does not result in item duplication or destruction. Changing to incremental saving introduces duplication/destruction behaviour.

**Comment by mutability** [comment]
> an option would just mean people can opt out of poor performance in one place around and add it elsewhere.

Save times on my Linux install are already fine here (couple of seconds). On this install, I'd rather have saves that take a couple of seconds and not lose consistency of an atomic(-ish) save. So an option would be most useful.

**Comment by Coolthulhu** [comment]
Can it be introduced as an option, at least at first?

I can easily see this causing a lot of trouble in common cases. It doesn't look hard to make it optional and just making it the default option would provide enough feedback.
Later on, when existence of the option became a maintenance problem, it could be made mandatory.

**Comment by mutability** [comment]
Perhaps you could get most of the best of both worlds if the incremental saving wrote to separate filenames and the "real save" renamed them all to their final resting place (assuming that renames are fast enough, anyway; I don't know how that behaves on Windows)

**Comment by kevingranade** [comment]
> Changing to incremental saving introduces duplication/destruction behaviour.

My bad, I was thinking the current semantics expose more data to loss, but that's not a lack of consistency.

To be clear, I agree that the loss of consistency is a critical issue.  Insuring that consistency as well as fixing the performance problem should be doable though.  Your idea of writing a map cache and renaming on atomic save sounds like a good one.  I believe the w32 RenameFile call does the right thing, as for performance, we'll just have to test and find out.  Even if it doesn't, we could do some kind of generational thing explicitly.

Just to outline this scheme, incremental saves would write to a "map cache" directory adjacent to the current submap save directory.
Incremental loads would check this cache first for submap data and fall back to the current directory.
Non-incremental saves would save the active map directly, and rename files in the map cache over map save files.
Non-incremental loads (game start) would delete the map cache directory before proceeding with loading to clean up after crashes.

**Comment by kevingranade** [comment]
Tiny adjustment, there's no need to change incremental loading behavior, we can just leave submaps cached, and mark them as synced to disk until they're loaded into the map again. No need to actually prune them unless we get reports of memory exhaustion. 

My experiment with shifting-based writeout is a failure, this approach isn't going to work on windows, WTH windows.  I'll build a idle-writeout feature as outlined previously, but that's going to take a while.

**Comment by DanmakuDan** [comment]
Regarding Windows performance with small files, Minecraft used to store maps in 16x16 block chunks that took around 5 KB each. They moved to a region format of 32x32 chunks (512x512 blocks) to fix the hard drive issues Windows was having. Hard drive speed is still fast for writing the larger file, since the overhead is with how Windows handles of a large number of small files.

**Comment by Coolthulhu** [comment]
Large blocks could be a problem for the json system, though. Consider just adding something to a block, without having to rewrite entirety of it.
Unless save blocks were all fully filled up to that block. But that would be a large problem to sync with small block sizes used in submaps. I got into the "guts" of save system when I implemented the uniform submap saving - its performance pretty much relies on the facts that you dump the contents on mass save (and thus save all 4 submaps of the block) and the fact that block size is small and thus small changes can be easily saved.

This PR+large block size would erase both factors that make current saving system perform relatively well.

It could be made manageable if the saving system wasn't required to dump the save as soon as the submap is outside reality bubble but only after the entire block is outside bubble.

**Comment by kevingranade** [comment]
On Feb 6, 2017 12:09 PM, "Coolthulhu" <notifications@github.com> wrote:

It could be made manageable if the saving system wasn't required to dump
the save as soon as the submap is outside reality bubble but only after the
entire block is outside bubble.


I was already doing this, but it seemed to be taking too long still, I'm
getting some better test cases set up to verify if trailing edge writeout
works.  If that doesn't work I have the implementation for writeout-on-idle
written, it just needs some cleanup.

**Comment by angoddu** [comment]
Is this PR still active? Or should it get closed?

**Comment by kevingranade** [comment]
Needs to be resurrected at some point, but doesn't need an open PR until then.

**Pull request closed without merging**
