### PR TITLE
Make flu shot expire

### PR DESCRIPTION
**Pull request by eJ0opb**
#### Summary

SUMMARY: Bugfixes "Make flu shot expire"

#### Purpose of change

Prevent the player from stocking on flu shots and taking one every six months.  That's not how it works.  Nobody is developing vaccines anymore, so there is no vaccine after the last flu season before the cataclysm.

#### Describe the solution

Check if the current turn is more than 24_weeks after the start of the cataclysm.

#### Describe alternatives you've considered

* Leaving it the way it is
* Figuring out when the last flu season started and using that instead of the start of the cataclysm.  That is probably better but I figure this is good enough for now.

#### Testing

1. Change the expiration time (in code) to 8_hours + 5_minutes after the start of the cataclysm
2. Start new game, spawn 2 flu shots
3. Take flu shot, get vaccinated message, @ screen shows vaccinated
4. Wait 5 minutes, @ screen no longer shows vaccinated
5. Take another flu shot, get expired message, @ screen does not show vaccinated

Tacoma ranch:
1. Start game before changes
2. Spawn tacoma ranch clinic
3. Complete missions up to advanced emergency care
4. Change mission content
5. Continue missions, you still get the flu shot mission
6. Start a new game
7. Spawn tacoma ranch clinic
8. Complete missions as asked, syringes is after advanced emergency care

#### Additional context

Logical continuation of #40287

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Consider changing the flu shot Tacoma ranch mission to match these changes - if it's not useful after 6 months, perhaps they should be looking for something else.

**Comment by Xenomorph-III** [comment]
What can the Tacoma Ranch make, then? I'm thinking aspirin or other basic medicine.

**Comment by Night-Pryanik** [comment]
Maybe add some message mentioning that it won't work after it's expiration date? Maybe for characters with a few of first aid skill levels or MD profession? Otherwise people might be confused on why they get the flu even after applying the vaccine.

**Comment by Wishbringer** [comment]
How does the flu even spread? There are hardly any people left?

**Comment by anothersimulacrum** [comment]
@Xenomorph-III They aren't making it, they want it for a quest.

**Comment by kevingranade** [comment]
Zombies are viable hosts, I want to adjust flu acquisition to be based on exposure to infected zombies instead of pure environmental exposure.

**Comment by eJ0opb** [comment]
> Maybe add some message mentioning that it won't work after it's expiration date? Maybe for characters with a few of first aid skill levels or MD profession? Otherwise people might be confused on why they get the flu even after applying the vaccine.

That's easy enough, but that implies you knew the vaccine didn't work, in which case why would you take the shot in the first place?  If anything, I think it's weird that you can positively know that the vaccine worked on you.

**Comment by eJ0opb** [comment]
> Consider changing the flu shot Tacoma ranch mission to match these changes - if it's not useful after 6 months, perhaps they should be looking for something else.

How about just making the mission inaccessible for now?  Content addition can go in a separate PR.  Players who already have the mission will probably be confused as to how the request for flu shots at some point turned into a request for medical gloves or chicken eggs or whatever they got replaced with.

**Comment by Night-Pryanik** [comment]
> why would you take the shot in the first place?

You could then prevent taking a shot of over-expired vaccine for people with high medical skills.

**Comment by wapcaplet** [comment]
> That's easy enough, but that implies you knew the vaccine didn't work, in which case why would you take the shot in the first place? If anything, I think it's weird that you can positively know that the vaccine worked on you.

I agree, the "You no longer need to fear the flu" message (and even more so, the visible "vaccinated" status in the `@` menu) may be giving too much away, but at least is true and consistent messaging.

The flu shot item description mentions that it's still in the packaging, which suggests it may have a manufacture or expiration date printed on it. Perhaps that could be the basis of an alternate message, after `You inject the vaccine`, say `You notice the date on the packaging is pretty old, so it may no longer be effective`.

**Comment by Marrim** [comment]
Shouldn't it still have some reduced effect?
Real-life vaccines are tailored to a particular strain that is expected to be common in next flu season, but the vaccine itself doesn't go bad, it might still help if the strain you caught happens to match.

Or does it actually go bad?

**Comment by Profugo-Barbatus** [comment]
Even against the strains vaccines do protect against, their potency wanes with time. Nothing lasts forever.

**Pull request merged**
