### PR TITLE
Reword PR summary instructions in template

### PR DESCRIPTION
**Pull request by xuvatilavv**
#### Summary
None

#### Purpose of change
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/52591
Addresses part of https://github.com/CleverRaven/Cataclysm-DDA/issues/50208
The instructions for the summary in the PR template are somewhat unclear.

#### Describe the solution
Clarify.

#### Describe alternatives you've considered
None

#### Testing
N/A

#### Additional context
This PR could close the second linked issue but it was also suggested to edit the error message with an example and to direct the user to read the PR template more closely. As stated in the issue discussion, that change would go here: https://github.com/CleverRaven/pr-validator/blob/160a007b08976855c37b38d78e6156b8fab4d2b0/src/main.ts#L13

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Also fixes #52591.

**Comment by xuvatilavv** [comment]
> Also fixes #52591.

Nice catch! Added it to the post.

**Comment by PatrikLundell** [comment]
Well, I wrote that suggestion, so it wasn't that hard... Happy to see a new attempt to improve the template.

**Comment by xuvatilavv** [comment]
> Well, I wrote that suggestion, so it wasn't that hard...

Yeah, didn't think to check that til after commenting 😄 thanks, anyhow.

**Pull request merged**
