### PR TITLE
Display distance to mission objective as a real distance

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Interface "Show actual real-world distance to mission objective"

#### Purpose of change
image

#### Describe the solution
Just do that

#### Testing
image
image
image
image

#### Additional context
~~due to how `length_units` converts we always get a meters/yards value unless it is **perfectly** divisible into kilometers. I wasn't going to risk touching that when the meters-->kilometers conversion is perfectly easy to do in your head just by looking at it.
(Yes, this IS much more difficult with imperial! Too bad, use a real measurement system! -Signed, American who uses metric)~~

IMPERIAL WINS AGAIN! GOD BLESS AMERICA!
-Signed, **American** (who uses metric 😢 )

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I'd prefer to get both real world distances AND game distances. This is especially relevant as game distances are rather loose with their real world connections (good luck trying to shoot at a 200m target at a shooting range).

**Comment by RenechCDDA** [comment]
I updated the example images to be more clear. I did already force push it to displaying both.

**Comment by RenechCDDA** [comment]
image

....Okay I guess this *is* my problem

**Comment by Consoleable** [comment]
> image
> 
> ....Okay I guess this _is_ my problem

As a citizen of the internet, how many bananas is that?

**Comment by PatrikLundell** [comment]
It depends on the kind of banana...
However, it's about 38057 minimum length bananas of the Gros Michel or Cavendish sub-groups.

[https://unece.org/fileadmin/DAM/trade/agr/meetings/ge.01/document/Codex%20bananas%20E.pdf](url)

**Pull request merged**
