### PR TITLE
Unhardcode speed modifiers/fix speed enchantment

### LINKED ISSUE #47450: Passive enchantments with SPEED modifier do not affect player speed
# Describe the bug
Passive enchantments that affect speed (`enchant_vals::SPEED`) do not actually affect avatar's speed, only speed display.

# Steps To Reproduce
1. Obtain an artifact with passive enchantment that severely reduces speed (win debug spawn lottery or just edit a save)
2. Activate the passive enchantment (e.g. wield the item if needed)
3. Notice that 'speed' indicator in the sidebar dropped as expected
4. Walk around. Notice that the movement takes ~1 turn/tile, both with and without the artifact

# Expected behavior
Character needs a few turns to move across a tile, like when in pain or overburdened.

# Versions and configuration
Build 11459 (aka cbcfab179d4e7e7f715e21d44816d1bee1132868)

# Additional context
I'm pretty sure `Creature::speed_bonus` gets reset at the beginning of each turn, and new moves are assigned based on this new value instead of whatever was calculated by the `Character::enchantment_cache`.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #47450
Unhardcode bionics speed effect, fix speed enchantment

#### Describe the solution
Moved bio_speed over to using enchantments.  Removed mutation speed mod and moved it to using enchantments.  Fix speed enchantment actually working by moving the call to the correct place.  Remove hardcoded speed mod display for quick/bio speed and add a generic display for speed enchantments.

#### Describe alternatives you've considered
Right now the speed display shows the total from enchantments with a heading of Bio/Mut/Effects as those all can have enchantments.  I would love to break it out into individual pieces but thats a lot of work/goes against the spirit of the enchantment system.  Also if anyone has a better title please suggest it.  Calling it enchantments would be out of place in standard CDDA and I considered MISC but figured this is a little better.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I do not see any value in unhardcoding `speed_modifier` field which is already unhardcoded.

**Comment by Ramza13** [comment]
> 
> 
> I do not see any value in unhardcoding `speed_modifier` field which is already unhardcoded.

To me the value is consolidating it into one place:enchantments.  Otherwise we have speed_modifier for mutations and an enchantment doing the same thing which can be used by mutations. Better to maintain one way to do it than 2.

**Comment by ZhilkinSerg** [comment]
I agree it could (and should) be simplified code-wise, so mutations/bionics/enchantments/whatever would use the same code to apply all these modifiers. Still, you have just bloated things up data-wise, e.g.: we had just one line `"speed_modifier": 1.15` in `CRAFTY` mutation and you replace it with a reference to a new object `"enchantments": [ "ENCH_TRAIT_CRAFTY" ]` plus definition of this object (probably not reusable for anything else). That adds a level of indirection to lookup what mutation does and now you need to keep not only cheap `cata::optional<float>` field, but also a heavier enchantment object and reference to it in mutation.

P.S.: I also do not like "enchantment" used in context of mutations/bionics, but that's just a nitpick.

**Comment by Ramza13** [comment]
> I agree it could (and should) be simplified code-wise, so mutations/bionics/enchantments/whatever would use the same code to apply all these modifiers. Still, you have just bloated things up data-wise, e.g.: we had just one line `"speed_modifier": 1.15` in `CRAFTY` mutation and you replace it with a reference to a new object `"enchantments": [ "ENCH_TRAIT_CRAFTY" ]` plus definition of this object (probably not reusable for anything else). That adds a level of indirection to lookup what mutation does and now you need to keep not only cheap `cata::optional<float>` field, but also a heavier enchantment object and reference to it in mutation.
> 
> P.S.: I also do not like "enchantment" used in context of mutations/bionics, but that's just a nitpick.

I see what you are saying and agree its less than ideal.  That said it is my understanding that enchantments are the way of the future in terms of bringing mutations/bionics/effects together under one roof of shared content.  I am not sure whether or not performance is noticeably impaired by this change and either way think performance improvements on enchantments in general can be there own issue.  I see at the moment two solutions to the organization issues you have raised.

1. Move the enchantment out of the enchantments.json file and right next to the mutations that correspond to them.  This is an easy change that helps someone reading the json see what is going on.  But it's still a little more complicated than needed.

2. Allow enchantments to be defined in the mutation/bionic directly.  So the enchantment syntax would be the same but it would be an object right in the main json.  

To my thinking 2 is the best solution but I'm not sure how easy or hard it is.  I will look into it especially because I think it will help #48042 to use something similar when I start using that in places like monster and items, the same issue of json being spread between too many fields.  If you see other solutions please let me know.

**Comment by ZhilkinSerg** [comment]
Yes, having inline enchantment (with syntax unified with regular enchantments) should work:

So, in addition to having separate:

```
  {
    "type": "enchantment",
    "id": "ENCH_TRAIT_FORCE_MAGE",
    "condition": "ALWAYS",
    "values": [ { "value": "SPEED", "multiply": 0.2 } ]
  }
```

and referencing it in mutation definition:

```
"enchantments": [ "ENCH_TRAIT_FORCE_MAGE" ]
```

we also allow using inline enchantment in mutation definition (referencing enchantment by id should also be possible):

```
  "enchantments": [
    { "condition": "ALWAYS", "values": [ { "value": "SPEED", "multiply": 0.2 } ] },
    { "condition": "ALWAYS", "values": [ { "value": "SLEEPY", "add": -12 } ] },
    "ENCH_SHADOW_CLOUD",
    "ENCH_INVISIBILITY"
  ]
```

***

Thinking of it further, we utilize these enchantment modifiers not only to magical enchantments, but also for bionics, traits/mutations, artifacts/relics/items, so we should probably generalize these modifiers and go with a different name (`effect` is already taken, so let's call it `consequence` for example).

Enchantment would be be its own thing (that could exist on item types or be attached to items in magical mods) and other object types would use `consequences` node with syntax taken from current `enchantment` object type:

```
[
  {
    "type": "enchantment",
    "id": "ENCH_TRAIT_FORCE_MAGE",
    "consequences": [ { "condition": "ALWAYS", "values": [ { "value": "SPEED", "multiply": 0.2 } ] } ]
  },
  {
    "id": "bio_cloak",
    "type": "bionic",
    "name": { "str": "Cloaking System" }, 
    "enchantments": [ "ENCH_TRAIT_FORCE_MAGE" ],
    "consequences": [ { "condition": "ACTIVE", "ench_effects": [ { "effect": "invisibility", "intensity": 1 } ] } ]
  }
]
```

**Comment by Ramza13** [comment]
Just added new PR  #48151 to allow inline enchantment definitions.  When either that or this is merged I will update the other to use it.

**Comment by actual-nh** [comment]
Since this one is now targeted at 0.F-dev, could the "Fix speed enchantment actually working by moving the call to the correct place" bugfix be moved to a master-targeted PR?

**Comment by Ramza13** [comment]
> Since this one is now targeted at 0.F-dev, could the "Fix speed enchantment actually working by moving the call to the correct place" bugfix be moved to a master-targeted PR?

So there is no reason it couldn't and I have no problem with someone taking it and doing that but having gone through a lot of rebasing and git stuff lately I'm not feeling too enthusiastic about it.  I'll add it to my list but I'm not making any promises or even super considering it at the moment.

**Pull request merged**
