### PR TITLE
Add more activatable bots

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add inactive versions of eyebot, skitterbot, security bot, police bot and antimateriel turret. Also add recipes to craft them and make these bots drop their inactive verstions if deactivated without being destroyed.
2. Move existing bot recipes to electronics_other category.
3. Replace "9mm" with "9x19mm" in turret description.
4. Modify bots item group to include new bot items.

I didn't add other inactive bots because they are either very buggy when attacking monsters or would be too heavy to be held in inventory to activate.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The jsons are badly formed. A bunch of errors at load.

**Comment by Darkyhard** [comment]
Fixed it.

**Comment by tyrael93** [comment]
The real problem with activable tazer-mobs is that they're unstoppable. There's a mod in the forum called jury-rigged robots that explains plainly that skitterbots are overpowered as hell against zombies
http://smf.cataclysmdda.com/index.php?PHPSESSID=34wpQeKkpMgL2nsXqp2jA0&topic=10667.0

>The pre-existing monsters are made to be good enemies for a player character; they're not designed as pets. Some are just way too strong to be converted directly to allies. The main offender isn't the tankbot—like you might expect—it's the common skitter bot. It turns out that a sidekick with an unlimited tazer is really OP. (A pair of skitterbots can take down a hulk in a few rounds. A group of about five skitterbots can practically clear a city by themselves.)

now, I'll admit my ignorance with "deactivated" bots, but as logic goes you wouldn't activate a robot and have it unfriendly, which must mean that whenever you activate it, it's going to be friendly. And a friendly skitterbot is overpowered.

I am against this and the police bot (which also tazes).

**Comment by Darkyhard** [comment]
All the bots can be hacked using control laptop. It doesn't make it more unbalanced because you will already be able to craft a control laptop (and use it effectively) when you can craft these bots. But the fact that a few skitterbots can clear the city is still overpowered.

**Comment by kevingranade** [comment]
A couple of balance points, the broken bots should need some repair before you can use them again normally.
The recipes to make them from scratch need a lot more in the way of components, a lot of them don't even have any moving parts, at a minimum they need a motor of some kind, and most of them should have several.  They also all need power sources and control circuitry, in the case of the larger bots they need a lot, to the point of several being unreasonable for a survivor to make such as the secubot and copbot.

Future extensions (not necessary for this PR):
You should either find or write software for them, or perhaps they should be remote controlled.  Autonomous minions is a big stretch.
They should have charge and run down, that would go a long way toward balancing them I think.

**Comment by Darkyhard** [comment]
I've changed bots' recipes. Is it okay now?

**Comment by kevingranade** [comment]
"the broken bots should need some repair before you can use them again normally"
The eyebot is FLYING, that's not a reasonable thing to cobble together from some spare parts and scrap.
"in the case of the larger bots they need a lot, to the point of several being unreasonable for a survivor to make such as the secubot and copbot", but you left the secubot and copbot in as craftable.

**Comment by Coolthulhu** [comment]
I'd say it needs a nerf to skitterbots first. Not sure if in this PR.

**Comment by Coolthulhu** [comment]
Before the mergetest, I mean.

Or maybe just drop the skitterbots and make eyebots uncraftable (and non-reversible).

**Comment by kevingranade** [comment]
Closing because the overboard bots aren't getting removed,l someone can feel free to strip those out and re-PR.

**Pull request closed without merging**
