### PR TITLE
Add dialog effects for taking control of npcs and conversations with monsters/items

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
Infrastructure "Add dialog effects for taking control of npcs and conversations with monsters/items"

#### Purpose of change
Add dialog functions to allow taking control of followers and allow talking to monsters/items
There has been excitement around possibly taking over a follow on death, this won't allow that but can let a talk response or item enable the same thing.  

#### Describe the solution
Add chat topics fields to items and monsters which define what they say in a dialogue.
Add effect to open dialogue.
Move taking control of followers menu out of debug and into avatar.  Add dialog functions to allow using it.

#### Testing
Some json I used:
```
{
    "id": "debug_mon",
    "type": "MONSTER",
    "name": { "str": "debug monster" },
    "description": "This monster exists only for testing purposes.",
    "default_faction": "",
    "species": [ "ZOMBIE" ],
    "volume": "62500 ml",
    "weight": "81500 g",
    "hp": 10000,
    "speed": 100,
    "material": [ "flesh" ],
    "symbol": "X",
    "color": "white",
    "aggression": 100,
    "morale": 100,
    "melee_cut": 0,
    "vision_day": 1,
    "armor_bullet": 100,
    "weakpoints": [
      { "name": "the knee", "armor_mult": { "bullet": 0.5 }, "armor_penalty": { "bullet": 25 }, "coverage": 25 },
      { "name": "the bugs", "armor_mult": { "bullet": 0.0 }, "armor_penalty": { "bullet": 0 }, "coverage": 25 }
    ],
    "harvest": "exempt",
    "chat_topics":["TALK_CITY_COP_NEWS","TALK_CITY_COP"],
    "special_attacks": [
      {
        "type": "spell",
        "spell_data": { "id": "impossible_shape_attack", "min_level": 1 },
        "cooldown": 5,
        "monster_message": "You get a very clear view of the impossible shape."
      }
    ],
    "death_function": { "corpse_type": "NO_CORPSE", "message": "The %s melts away." },
    "regenerates": 50,
    "regeneration_modifiers": [ [ "onfire", -5 ], [ "corroding", 5 ] ],
    "flags": [ "IMMOBILE", "NOT_HALLUCINATION", "FILTHY" ]
  },
  {
    "type": "SPELL",
    "id": "impossible_shape_attack",
    "name": { "str": "Impossible Shape Attack" },
    "description": "Hurts you mentally.",
    "valid_targets": [ "hostile", "ground" ],
    "max_level": 1,
    "flags": [ "SILENT", "NO_HANDS", "NO_LEGS" ],
    "base_casting_time": 75,
    "min_range": 6,
    "max_range": 6,
    "shape": "blast",
    "effect": "effect_on_condition",
    "effect_str": "EOC_impossible_shape_attack"
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_impossible_shape_attack",
    "condition": "u_can_see",
    "effect": [
  "open_dialogue"
    ]
  },
{
    "id": "migo_bio_tech",
    "type": "TOOL",
    "name": { "str_sp": "Mi-go Biotech" },
    "description": "A piece of mi-go biotechnology.",
    "weight": "1 g",
    "volume": "250 ml",
    "price": 3000,
    "price_postapoc": 10000,
    "symbol": "!",
    "chat_topics":["TALK_CITY_COP","TALK_CITY_COP"],
    "color": "light_red",
    "use_action": {
      "type": "effect_on_conditions",
      "description": "Touch the opening.",
      "effect_on_conditions": [
        {
          "id": "EOC_MIGO_BIO_TECH_TALK",
          "effect": [
            { "u_message": "You have a slight feeling of being watched." },
            
            "open_dialogue"
          ]
        }
      ]
    }
  }

 "type": "talk_topic",
    "dynamic_line": "What about faction camps?",
    "responses": [
      {
        "text": "Control",
        "topic": "TALK_DONE",
        "effect": "take_control"
      },
      { "text": "Tell me how faction camps work.", "topic": "TALK_CAMP_TUTORIAL_INTRO" },
      { "text": "Tell me how faction camps have changed.", "topic": "TALK_CAMP_TUTORIAL_CHANGES" },
      {
```

### CODE REVIEW

**Comment by hm001121606** [comment]
Item usage 'chat_ Topics' if it is on the ground, an error will be reported

**Comment by Ramza13** [comment]
Hmm I'll have to take a look at that, thanks for reporting it.

**Comment by Ramza13** [comment]
> Item usage 'chat_ Topics' if it is on the ground, an error will be reported

Ok I've just tested this and it seems to work fine.  I created an item with chat topics and an open dialogue eoc. Dropped it on the ground and activated it. Result dialog opens fine.

Were there any other steps you did to get an error?

**Comment by hm001121606** [comment]
> 工

Sorry for wasting your time.

**Comment by Ramza13** [comment]
Ha no worries, its totally possible something changed in experimental since you reported it and fixed it.  Reports are always appreciated.

**Pull request merged**
