### PR TITLE
Disable multi processor compilation with MSVC [RDY]

### PR DESCRIPTION
**Pull request by ghost**
> A piece of code that unable to be compiled with msvc was merged into master after my last PR. I fixed it. I think we need to remind every developer to use same type of parameters in `std::min` and `std::max` function, either both `float` or both `double`. Otherwise, it will not pass the build with msvc.
> 
> By the way, I disabled multi processor compilation in Visual Studio project properties. It is even slower than the single thread compilation. Not helpful to shorten the build time at all.

This PR was originally for fixing the float type issue. But it has already been fixed in another PR. So I changed the title to "Disable multi processor compilation with MSVC".

### CODE REVIEW

**Comment by codemime** [comment]
This PR is the fifth of a kind (#16961, #16971, #16978, #16987) (except the disabled multiprocessor compilation).

**Comment by DLaboratory** [comment]
oh sorry I didn't check for duplicate

**Comment by DLaboratory** [comment]
Do I need to close this PR, or leave it open?

**Comment by codemime** [comment]
I suppose you could revert your first commit and leave the second one (please change the title accordingly). BTW your PR doesn't solve the issue with types, but swaps them (via replacing `std::min( float, double)` with `std::min( double, float )`). According to the Jenkins the embedded version of `floor()` returns `double` and that's why the issue wasn't spotted in the first place).

**Comment by DLaboratory** [comment]
Thanks. I reverted the commit.

 

My code was

> std::min( floor( corpseDamage ) - 1, 1 + max_hp / 5.0f )

The first parameter, `floor( corpseDamage ) – 1` is a float type value, as `floor` is defined as a float type function in `cmath` in MSVC:

```C++

_Check_return_ inline float floor(_In_ float _Xx) _NOEXCEPT

       {

       return (_CSTD floorf(_Xx));

       }

```

And the second parameter is also a float value.

**Comment by codemime** [comment]
> Thanks. I reverted the commit.

Not at all. Please don't forget to change the title and the description too.

> as `floor` is defined as a float type function in `cmath` in MSVC:

We don't make build for MSVC only. There are [several](http://en.cppreference.com/w/cpp/numeric/math/floor) overloaded versions of `std::floor()`.  Compilers choose one of them depending on the argument type.

> The first parameter, `floor( corpseDamage ) – 1` is a float type value, 

Nope. If you don't explicitly specify the namespace, it will return `double` in `gcc` and `clang` (probably some other compilers). I guess they use some kind of embedded function if you omit `std::`.

```
floor( float ) -> double
std::floor( float ) -> float
```

The Jenkins marked your build as a failure for this very reason: `min( double, float )`.

**Pull request merged**
