### PR TITLE
mad militia guard base

### LINKED ISSUE #53707: Mad Militia are very accurate from afar
### Describe the bug

During my game I was spotted by a Mad Militia. 
Broad daylight, so the 50 daytime vision obviously helped. Once they were at around 30 or so tiles from me, they started unloading bullets. ALL of them hit me. 6 were enough to kill me. I "watched my last moments" and they were still shooting at me *while coming towards my dead body*. That I could count for at least 20 bullet cases on the floor. All his hits did over 28 damage as seen on "Screenshots" (picture) 
Also noticeable that it never even once missed a shot. 
Should also point out I was wearing a Modified Faraday Chainmail Suit with Kevlar plates, which gives me a 16 ballistic protection, 100% coverage. 

I save scummed to see what was going on. I killed it and noticed it had an AR handgun, empty, with a grand total of 24 .223 bullet cases on the floor. 

Keeping in mind that this gun only does 28 damage, it should do much less damage after applying the Armour benefits right? 
I figured "well, maybe I need to update, something may have changed in the past 2 days", so I fully updated it, created a test world and recorded it. (See: "Screenshots", video)

- This time I spawned a creature using debug mode and tracked it. The amount of bullets it has was reduced, but this time it had an M27, which justifiedly does more damage. It still doesn't explain how or why they have 10+ .223 ammo **and** what essentially is 100% accuracy from a long distance, and seem to be very keen on hitting the torso. 

### Steps to reproduce

1. Create a test world;
2. Spawn Mad Militia
3. Watch as it takes great joy in hitting you every time it pulls the trigger, turning your chest into a makeshift brass catcher.

### Expected behavior

Considering they are supposed to be "mad", they shouldn't be in full control of their "abilities", the miss chances should be higher the further away they are. This also highlights that armour protection is, effectively pointless unless I am misunderstanding the calculations there, which, if so, please enlighten me. 

### Screenshots

https://cdn.discordapp.com/attachments/367645652328644618/923593869109645363/unknown.png

https://www.youtube.com/watch?v=gJoG7RAl1-Q

### Versions and configuration

- OS: Windows 7
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Balance "mad militia guard base"

#### Purpose of change

Close #53707 , specifically keep it at its special location, not wandering around

#### Describe the solution

Gives mad militia a difficulty value to let the player know how dangerous they are, gives the mapgen spawn info a "patrol" entry so they don't go wandering far. Changes LMOE and cabin to use place_monster instead of place_monsters to allow this

#### Describe alternatives you've considered

Deprecate them, reduce their stats, cut spawn rate in half in GROUP_PREPPER_HOUSE, spawn more, spawn fewer

#### Testing

Game loads no errors. Spawned prepper cabin and teleported inside to confirm monsters in there. Waited outside, shouted, walked around, waited until weather changed. Monsters stayed inside.

#### Additional context

Currently a release blocker

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I don't like this as this is not a proper fix. More accurately, this doesn't fix that issue. Making them have less HP, less speed, less vision, and less ammo doesn't make them less accurate at all. These changes just make them another boring enemies that will cease to pose a threat to anyone post early-game.

**Comment by LyleSY** [comment]
Good call, I've changed the purpose section to be more clear, responding to Erk's comment: 
"I remain of the opinion that hostile monsters with guns should never spawn at random, and should only be something you have to go to find, and have a lot of warning about.

inaccuracy is not a fix. You cannot plan for or fight inaccuracy, tactics don't help you. It just means that sometimes the monster kills you, and you can't do anything about it. We do not have a system that models taking cover from bullets and darting across the battlefield, so a feral that can pop a lucky cap in your head before you realize they popped up in the reality bubble is just not fun."

Based on my testing this doesn't fully achieve that, but it's better than current state, offering a warning before the bullets come, at least in clearings. In the city or heavy woods you're still dead before you see it.

**Comment by LyleSY** [comment]
Just looked at the monstergroup entry and this doesn't spawn day one, it spawns day 20, working on a better fix

**Comment by LyleSY** [comment]
Errors don't look related

**Pull request merged**
