### PR TITLE
Make clairvoyance's range 20% range of super-clairvoyance

### PR DESCRIPTION
**Pull request by Noctifer-de-Mortem**
Me and a few others have been using a clairvoyance artifact and have noticed it's range to be rather short. In both combat and reconnaissance, monsters can just escape the artifacts range if they are in the open or in a large enough building, leaving it's effects useless.

   After code diving, we noticed the sharp contrast between `VISION_CLAIRVOYANCE` and `VISION_CLAIRVOYANCE_SUPER`. With this PR, the normal clairvoyance should become usable while still being only 1/5 of it's counterpart; still a sharp contrast between the too but also just an upgrade rather than the former on steroids.

### CODE REVIEW

**Comment by somot** [comment]
On a side note: What is the range of debug-menu spawned clairvoyance artefact?

**Comment by Noctifer-de-Mortem** [comment]
It's forty as it spawns an artifacts with `VISION_CLAIRVOYANCE_SUPER`.

**Comment by kevingranade** [comment]
I don't follow your rationale, it just boils down to, "I want this to be better".
The effect having major limitations is intended, all of the artifacts have unique but very limited uses.  Clairvoyance lets you see what's on the other side of walls, and that's it.

Comparing to SUPER_CLAIRVOYANCE doesn't make sense, it's a debug-only property, no randomly-generated artifacts will be assigned it.

**Comment by Noctifer-de-Mortem** [comment]
I’ll will be more clear and transparent about the issue; I should have done so from the start so my mistake. We were not only playing with an `AEP_CLAIRVOYANCE` vanilla artifact, but also items from mods with both the `AEP_CLAIRVOYANCE` and `AEP_SUPER_CLAIRVOYANCE` tags. The arguments that the range is tool small for these artifacts to be too niche, as well that they have drawbacks that make them not worth it, still stands (You however, indicated that this is intended; I am also trying to refute that that should not be the case). The second point is that this PR would also balance artifacts in mods that use both flags in them. Making ones with just `AEP_CLAIRVOYANCE` a viable alternative with proper drawbacks and `AEP_SUPER_CLAIRVOYANCE` still a clear upgrade but the former still usable.

	I am not very good at explaining myself so sorry if this comes off the wrong way.

**Comment by kevingranade** [comment]
In that case, what you need to do is add a new clairvoyance effect with a
range of 8, and use that effect in the mod.

**Pull request closed without merging**
