### PR TITLE
[RDY] Allow deconstruction of `t_door_frame`

### LINKED ISSUE #21752: Cannot deconstruct door frame
We should be able to deconstruct door frames. it seems odd that you can construct one but not deconstruct one.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Deconstruction result item quantities are equal to maximum of what you can get from bashing this terrain.

Fixes #21752.

### CODE REVIEW

**Comment by angoddu** [comment]
The point of being able to deconstruct is to get all/most of the construction components back. If I wanted to get the smash result then I wouldn't waste 20 mins to deconstruct it. I would take a few seconds and smash it

**Comment by ZhilkinSerg** [comment]
> The point of being able to deconstruct is to get all/most of the construction components back. If I wanted to get the smash result then I wouldn't waste 20 mins to deconstruct it. I would take a few seconds and smash it. Please set the 2x4 value to 12 and the nail charges to 12-24

I see an issue in smashing numbers - it is simply not possible to smash door frame in a few seconds.

**Comment by Coolthulhu** [comment]
Deconstruction is supposed to return all ingredients, though.

**Comment by ZhilkinSerg** [comment]
I can edit deconstruction numbers to one and a half of what you can max get from smashing or 75% of construction recipe ingredients.

**Comment by Coolthulhu** [comment]
Looking at existing entries, the formula is roughly:
* Wood is returned 100%
* 80%-100% of nails are returned
* 100% of other components is returned

**Comment by ZhilkinSerg** [comment]
Small chance to loose ingredients:

- 1 out of 12 planks;
- 4 out of 24 nails.

How about that?

**Comment by Coolthulhu** [comment]
Would be better to follow the (currently unwritten) rule. Random exceptions only make things weirder.

**Comment by ZhilkinSerg** [comment]
> Would be better to follow the (currently unwritten) rule. Random exceptions only make things weirder.

Okay. Done.

**Pull request merged**
