### PR TITLE
Automatic extraction of data to generate Lua bindings.  

### PR DESCRIPTION
**Pull request by BevapDin**
The PR adds a python2 script that extracts the definitions that are exported to Lua. The generated output fits the syntax as required by `src/lua/generate_bindings.lua`. The script uses clang to parse the header files and therefor requires a clang installation along with the python bindings (you need `clang/cindex.py` in `/usr/lib/python2.7/site-packages/` or similar).

The script is not supposed to be run on each build. It is a helper that automatically exports all functions that *can* be exported to Lua. The generated definitions can be extended and modified by hand. It's intended to be run when much code has changed, or when a new class should be exported to Lua. Or maybe right before a release when there is a stable interface.

----

Changes in detail:

- The Lua wrapper definition use actual C++ type identifiers (`std::string`, `std::list<item>::iterator` etc.).

- The content of `class_definitions.lua` is split: the content generated by the python script is in `generated_class_definitions.lua` (overwritten each time the python script is run), `class_definitions.lua` can be used to extend that generated content (not automatically overwritten).

- `lua/parser.py` is the core component containing the parser and the export logic.

- `lua/export-c++-definitions-to-lua.py` is the script that needs to be run. It contains the configuration (what to export, what not).

----

There is an extended branch https://github.com/BevapDin/Cataclysm-DDA/tree/automatic-extraction-for-lua that continues this work (with more exported classes and some example usage).

----

Testing: I recommend putting Lua code into a file (e.g. "/tmp/x.lua") and running it from the Lua console by including the file: `game.dofile("/tmp/x.lua")`

----

Note that the huge line count comes from moving the existing definitions from `lua/class_definitions.lua` to `lua/generated_class_definitions.lua` (about 2000 lines).

Btw. I opt for keeping Lua. It's a great debugging tool. Especially with more exported bindings.

### CODE REVIEW

**Comment by narc0tiq** [comment]
Don't mind me, I'm just testing if I can have the new **Jenkins rebuild** this by including the keyphrase (see #20876 for details).

**Comment by ZhilkinSerg** [comment]
Does this makes sense if LUA will be dropped eventually?

**Comment by narc0tiq** [comment]
Let me try that again; Jenkins, rebuild, please.

**Comment by kevingranade** [comment]
> Does this makes sense if LUA will be dropped eventually?

It does not, I'm still planning on removing LUA integration immediately after the 0.D release.  I've seen two requests to keep it, one of which is for general debugging, and the other for unspecified molding that the author didn't give any details about.  Neither use case is compelling enough to keep around a huge LUA infrastructure.

**Comment by ZhilkinSerg** [comment]
I have accidentally just stumbled upon this PR and i'm sorry it was probably me who caused this to be closed.

I'm interested in keeping Lua in dda alive (even in separate repository) and will explore extended branch (https://github.com/BevapDin/Cataclysm-DDA/tree/automatic-extraction-for-lua), so please do not delete it. :)

**Pull request closed without merging**
