### PR TITLE
Make welding masks actually change when raised and lowered.

### PR DESCRIPTION
**Pull request by TheRafters**
#### Summary
```SUMMARY: Bugfixes "Make welding masks actually change when raised and lowered."```

#### Purpose of change
The current versions of welding mask and crude welding mask do not change coverage or function when activated (raised). This PR makes them work as intended. 

#### Describe the solution
I removed the copy-from lines and expanded each entry for the masks into independent entries. According to JSON_INHERITENCE.md type ARMOR is not supported and the results of trying to use them here, speak for themselves.
I also changed the weight of the plastic version(2.2lbs) to further differentiate it from the steel version(8.8lbs). I sourced [google](https://www.google.com/search?q=how+much+does+a+welding+mask+weigh&rlz=1C1CHBF_enUS856US857&oq=how+much+does+a+welding+mask+weigh&aqs=chrome..69i57j0.6718j0j4&sourceid=chrome&ie=UTF-8) for average weights of welding helmets and rounded to 1000 because we seem to love round numbers.
~And a little formatting to make things consistent and more readable.~

#### Describe alternatives you've considered
Extending Inheritance to support ARMOR. HAHA!

#### Additional context
Hah, I got the little tick marks in the summary this time!

Crude Welding Mask
https://i.imgur.com/aISrF2i.png
Crude Welding Mask(Raised)
https://i.imgur.com/NUzrqQ1.png
*crosses fingers and hits create pull request*

### CODE REVIEW

**Comment by Malkeus** [comment]
I'm not sure what the error message means, I don't know how to fix it.

**Comment by anothersimulacrum** [comment]
It means you need to lint.

**Comment by Malkeus** [comment]
I think I found the culprits, hopefully...

**Comment by Malkeus** [comment]
Well...Ok, to hell with consistency, for some reason that use_action has to be all on one line, but the other 3 are just fine spread out. Logic-x Reason-x Chaos-X

**Pull request merged**
