### PR TITLE
Updated maintainer for Growable/Garden Pots Mod

### PR DESCRIPTION
**Pull request by NastyNate2612**
Added myself as a maintainer for the "growable pots" mod.

#### Summary
Summary: Mods "changed maintainer for Garden Pots mod"

#### Purpose of change
Gotta have a caretaker for the garden...  Hey everybody! This is my first Mod im attempting to maintain, so please bear with me if i end up asking stupid questions. All I did this time was add myself as a maintainer. Next step will be to go through the list of seeds and add the ones that are not currently in the mod, adjust grow times to accurately reflect real growth times, and lower yields based on garden pot size. eventually add more sizes of garden pots. Im a farmer irl so indoor and outdoor gardening is something i practice on a regular basis and have a passion for. I didnt change the obsolete line because its missing 75% of the available seeds to plant, give me a couple days and ill have it up to par for now at least. I hope everybody likes the idea of still having movable garden pots and indoor gardening. My previous coding experience is practically non existent, but i will do my best. Starting with an easy mod thats already been written and reverse engineering it seems the best way for me to start.  

#### Describe the solution
Ill Do it!!

#### Describe alternatives you've considered
not having indoor gardening sounds super lame, especially when theres soooo many zombies outside!

#### Testing
Changed obsolete line to false. Create new world, selected Garden Pots, notice addition of Nate's name to maintainer list

#### Additional context
image

### CODE REVIEW

**Comment by NastyNate2612** [comment]
Sorry for the long description. Im super excited to be helping work on this amazing game, my knowledge is limited now but i learn pretty quickly when its something im interested in.

**Comment by ymber** [comment]
The real problems with this and the hydroponics mod are deeper than the mod JSON. They'd be in core if their implementation wasn't such a hack. For them to be technically acceptable the plant growth code needs a fairly significant rework so data for content like this doesn't have to abuse item transformations.

**Comment by NastyNate2612** [comment]
yeah i noticed it was using "transform" to grow, im assuming thats a placeholder until the code for plants needing to be in a lit tile is required.

**Comment by I-am-Erk** [comment]
yeah, unfortunately I don't think this one is going to meet the basic requirements for inclusion as a mainline mod - we are steering away from mods that could be core features, because they tend to stop people from working on adding the features to core in a working way. I don't think anyone would have a problem with adding raised garden beds to mainline, though.

You could consider:
- taking this over as a third party mod, hosted on your own github and linked to something like the launcher
- working on a project to add indoor gardening to mainline with necessary code updates (oh god please choose this one and fix outdoor gardening while you're at it)
- for the vehicle components alone, you could think about getting them moved over to blazemod, the vehicle parts pack.

Growable pots *as a mod* isn't something we're keen on, but growable pots as a feature would be amazing.

**Comment by I-am-Erk** [comment]
I should add that if you decide to help with farming/gardening features in mainline, I'm pretty sure there are some coders that would love to help you get the C++ portion done, there are several of our more experienced code people that would be really excited to have farming work better.

**Comment by NastyNate2612** [comment]
Ouch! Well I dont have any knowledge on c++, editing json files is pretty much my extent as of now. Also I'm new to this community and I don't know anybody or know how to contact someone with the knowledge to do coding for this project. I appreciate the positive response but sadly I lack the ability to do any of those things. I'll just run the mod on my own local disk and add all the missing seeds and stuff for now. I'll keep an eye out on the changelog and if someone fixes the coding for farming I'll bring this topic back up. Thank u!

**Comment by I-am-Erk** [comment]
Are you on the discord by any chance? https://discord.gg/4dKtbC we could discuss there, if you like.

A good starting point would be to create an Issue outlining what kind of changes would be needed to make farming more reasonable, if we don't have something like that already. It's a bit tricky doing a good large-scale issue for the first time, but I could help walk you through it. Then step 2 is to get people excited about it :)

**Pull request closed without merging**
