### PR TITLE
Fix some item id naming inconsistency

### PR DESCRIPTION
**Pull request by sulyi**
#### Summary

~~None~~

~~Probably~~ won't merge.

#### Purpose of change

Keep a legacy of reverted work done on #56062

#### Additional context

Measured discussion never hurt anybody, IHO.
This is a place to do so, about item ids.

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
This would break saves, so it's a big no.
There's a migration facility you can use to prevent that, but IMO this is still a pretty low payoff.

**Comment by sulyi** [comment]
I'll at look migration later, I'm not planning to take this up any time soon. Neither giving up on it. At least it seems a bit more strait forward to do then #46692, @anothersimulacrum suggested to me to study.

**Comment by kevingranade** [comment]
If you're not picking up, no need to have a PR open.

**Comment by sulyi** [comment]
Grief caused by this seems to have effected my work, but got me thinking:
A data structure as big as this stored in json is bound to problems like this.

I haven't got the chance to look at migration, where I should start, but I'm still wondering whether expanding it could allow using some database as middle ware, that probably could speed up game loading as well.

I realise this is ambitions and first I'd like to finish what I started, but I don't like how it progresses at the moment and I hope taking the time to compose this would help.

**Comment by kevingranade** [comment]
There is zero chance of merging a database dependency.

**Comment by sulyi** [comment]
Just forsake of clarity that's a mention of a mention. But it actually makes senescence. Since that's related to separating the task of querying and storage.

And I was infract wondering about binary serialization of json data at build time.

**Pull request closed without merging**
