### PR TITLE
Add option for aim window position

### LINKED ISSUE #36327: Option to change position of "look around" and "aim" windows
**Is your feature request related to a problem? Please describe.**  
I like my sidebar position on the left. The UI windows for looking around and aiming a weapon are always on the right. This causes an undesired amount of stuff on screen when being used.
In the interface options, Pickup window position can be changed between left, right, and overlapping; however, there are no similar options for Look Around nor Aim.

**Describe the solution you'd like**  
An option for the position of the Look Around window and the Aim window to be displayed on the left side.

**Additional context**  
Looking around while sidebar is on the left.
before

Mockup of desired window location.
after

Aiming a weapon at a certain enemy can be inconvenient at times.
before2

Mockup of desired window location.
after2

### PR DESCRIPTION
**Pull request by Kilvoctu**
#### Summary
```SUMMARY: Interface "Add option for aim window position"```

#### Purpose of change
Second part of #36804. Closes #36327.

#### Describe the solution
Adds "Aim window position" in the interface options, where the options are left and right (right is default).

#### Describe alternatives you've considered
Any different way to manage all these left/right panel options, but I'm not able to think of any.

#### Testing
Compile and run game, then set each configuration of panel position for sidebar and aim window. Tested on fullscreen and windowed (smallest terminal size).

#### Additional context
See original issue for screenshots of how it looks now.

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
We are definitely not adding a separate option for every window, the one for look around was iffy, and I'm not doing any more without a better way to manage them.

**Comment by Kilvoctu** [comment]
Yeah I'm aware of your dislike of options bloat, and I feel the same way. I'll continue to ruminate about any solutions to all these 4 or 5 similar options, and leave the PR up for anyone else to chime in with ideas.

**Comment by Kilvoctu** [comment]
There are a couple approach I can think of.

One, the more straightforward and easy solution, is to combine the options into one: look, pickup and aim. Sidebar is a near ever-present UI element so I feel that it can be separated. This does come with the downside of hurting UI flexibility.


The other approach, more difficult but I think is better, is to allow the look/pickup/aim windows to instead be swapped sides during gameplay via a hotkey. Should eliminate the need to have those options displayed altogether.
I imagine it could work out as such:
-Each panel defaults to right. When the hotkey is pressed to swap side, that setting is stored in a hidden option so user doesn't need to swap all the time.
-Swap side should apply as soon as the hotkey is pressed. I think this means the window has to be redrawn if I understand how windows work.
-The swap hotkey is contextual to the respective windows and can be rebind. Default key could be `S`, as that doesn't seem to be used in any of the three windows.

Again, due to the near ever-present sidebar panel, that could stay as a visible option. Also, the pickup position has three states (left, right and overlapping). I'm inclined to keep it as is.
Any thoughts or ideas? I'll move forward with one of the proposals if acceptable or hold off if not.

**Comment by kevingranade** [comment]
A hotkey from inside the menu that persistently toggles the position is totally fine.
My main objection is menu bloat, not simply having options when they're non-invasive like this.

**Comment by Kilvoctu** [comment]
Running into some hurdles that I expected to encounter. Gonna close this PR *for now* as I can't find the time currently to work through it, and I will resubmit the revised proposal as a new PR when able.
The linked issue can stay closed.

**Pull request closed without merging**
