### PR TITLE
Adds dynamite bomb and recipe

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary
```SUMMARY: Content "Adds dynamite bomb and recipe"```

#### Purpose of change
The player has dynamite as one of the few craftable high explosives available to him, but did not yet have a way to turn this powerful explosive into a bomb with fragmentation.
#### Describe the solution

New autolearn recipe: Dynamite bomb.
The survivor takes a stick of dynamite and a 2L metal tank, saws it open and packs the dynamite in with a bunch of shrapnel, then welds it shut with the fuse sticking out.

#### Testing
Launched the game, crafted the new bomb, and lit it, and tossed it at some zombies.
#### Additional context
image

### CODE REVIEW

**Comment by Maddremor** [comment]
I greatly appreciate this. Would it be too much to ask for you to add a grenade size version? Dynamite is a nice explosive to craft, and should be available in those use cases it can actually handle (IMO).

**Comment by Brian-Otten** [comment]
I can have a look and see if it would be possible to have one "bundle of dynamite" be used in a craft recipe that makes multiple smaller grenades.

**Comment by 1n17** [comment]
> Dynamite is a nice explosive to craft

For now. I'm (slowly) working on updating explosive recipes and introducing few new ones (TNT, DNP), so classic stabilized nitroglycerin dynamite should no longer be the explosive material of choice for crafting explosives in the future - but it will be easy to update the recipes to new agents so its a non issue.

**Comment by mkikt4743** [comment]
very cool

**Pull request merged**
