### PR TITLE
Adds Buildable Monorail track

### PR DESCRIPTION
**Pull request by TJKing293**
#### Summary

```SUMMARY: Content "Adds Buildable Monorail track"```
#### Purpose of change

allows easy transfer of large amounts of items from location to location
#### Describe the solution

this allows specialization of camps. For example one camp can be built to specialize in food production and another in building materials. These can then be shipped without the need to risk caravans, and reduce time it takes to transfer materials and goods.
#### Describe alternatives you've considered

two tracks were considered, but disregarded due to the inability to accommodate different sizes of vehicles. Using two wheels instead of four, reduces materials needed.
#### Testing

testing included: vehicles, deconstruction and construction

### CODE REVIEW

**Comment by I-am-Erk** [comment]
This is very cool but why a monorail? Wouldn't a small rail track for a normal two wheeled rail make much, much more sense?

**Comment by TJKing293** [comment]
> 
> 
> This is very cool but why a monorail? Wouldn't a small rail track for a normal two wheeled rail make much, much more sense?

less materials

**Comment by I-am-Erk** [comment]
Less materials? In what sense? Building a monorail car is not a trivial endeavour. If I was a survivor trying to build a railway between my bases I most definitely wouldn't start with a monorail

**Comment by TJKing293** [comment]
> 
> 
> Less materials? In what sense? Building a monorail car is not a trivial endeavour. If I was a survivor trying to build a railway between my bases I most definitely wouldn't start with a monorail

the car no but the double track would require double the mats

**Comment by TJKing293** [comment]
also limits welder use

**Comment by kevingranade** [comment]
You need a two rail track, I can't even begin to imagine how a motorcycle type vehicle is supposed to balance on a fixed track.

This also needs to be limited to smaller carts and such as I outlined in the issue you opened, it should not place the existing railroad terrain pieces.

**Comment by TJKing293** [comment]
I see. to be honest the only reason it's a monorail is because I can't quite figure out how to do anything more elaborate

**Comment by TJKing293** [comment]
do you think instead of a typical rail track it could be a guide rail?

**Comment by kevingranade** [comment]
Obsoleted by #34955 and friends

**Pull request closed without merging**
