### PR TITLE
ChestHole Tilesets Update: Every monster, Every vehicle part, Every mod.

### PR DESCRIPTION
**Pull request by Chezzo**
This is my attempt to have a tile for all the vanilla, PK and Arcana monsters, vehicle parts and traps.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
@Chezzo what are Marloboros?

**Comment by ZenZen2** [comment]
@Chezzo i found somthing interessting that is not worth an issue, because i dont think any player will notice it, this is just fyi:
You use ```"bg": 632``` over 5000 times, it is a tile with a shadow in the middle of it. Many or most id's with ```overlay_wielded``` use this as background.
Now look very close at your survivors face while your hands are free, now take for example a katana and see how his face gets darker due to the shadow of the background tile.

**Comment by Chezzo** [comment]
@ZenZen2: There are an awful lot of those, huh? I don't know what I should do about them. Maybe someone can write a script or someone else can do the dogsbody work.

**Comment by Chezzo** [comment]
An IRC user asked if I could get t_pavement_y to connect and I couldn't make it happen for the life of me. They just would NOT rotate no matter what I did.

**Comment by SomeDeadGuy** [comment]
I am making tileset too. There are A LOT to do, dude. I went and spawned all items, and put them all on the streets on pavement. There are ton of stuff to make tiles for. Feel free to use tiles from my tileset, if you want.

**Comment by Chezzo** [comment]
Cool @SomeDeadGuy always good to see new sets. Is it posted somewhere for me to borrow from?

**Comment by SomeDeadGuy** [comment]
On my github, dude! :) https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

**Comment by BorkBorkGoesTheCode** [comment]
Jenkins rebuild please.

**Comment by BorkBorkGoesTheCode** [comment]
Hey @Chezzo , how are you feeling? What's the prognosis?

**Comment by Chezzo** [comment]
Feeling fine, no deficit. Coumadin is a terrible blood thinner and unless it kills me, I'll live for another 30 years. Thanks for asking, @BorkBorkGoesTheCode.

**Pull request merged**
