### PR TITLE
vehicle interaction: overview pane scroll support

### PR DESCRIPTION
**Pull request by mlangsdorf**
SUMMARY: Interface "Add for scrolling the overview pane in the vehicle interaction window"

#### Purpose of change
Currently, if a vehicle has more engines, fuel tanks, storage batteries, turrets, or seats than will fit in the overview pane, the extra are just lost.  Wetwings reported the issue here https://discourse.cataclysmdda.org/t/how-to-scroll-in-the-vehicle-parts-list/16329/12

This PR adds basic support for scrolling the overview pane.

#### Describe the solution
This is an adaptation of the existing scrolling code used for vehicle descriptions. A scroll offset value and scroll limit value are both set to 0. When a new line is added to the overview pane's image buffer, the current value of y is checked: if it's under the size of the buffer, the scroll limit is set to the scroll offset. Otherwise, the scroll limit is set to the loop control variable for the part being printed, a message indicating how to scroll down is added to the buffer, and the loop that is adding new lines is broken.

When the user hits the scroll down key, the scroll offset is incremented and the next redraw of the overview pane starts printing parts at that offset (instead of 0). Scroll offset can't be incremented past scroll limit, and scroll limit never goes above the loop control variable necessary to get the last N items in the part list to display inside the overview pane.

Hotkey support was also altered. Instead of naively incrementing from 'a' to whatever, it jumps from 'z' to 'A'. That way no hotkey will be assigned to '{' or '}', the overview scroll keys. It also means that vehicles with more than 31 tanks will get hotkeys for valid keyboard characters, instead of random ASCII symbols.

#### Describe alternatives you've considered
The UI really needs a scrolling window that can take a buffer of text, determine if it fits within the window pane, and provide scrolling, instead of making everyone write their own. However, that kind of UI overhaul is long and hard, while rolling my own again fixes Wetwings' issue this year.

#### Additional context
cameloverviewscrolling
Luxury RV with a tank on every available tile showing what the scroll looks like.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
An alternative could be like making the vehicle layout window, list of tanks, seats etc window, and description window gain "focus" like it is happening now in @-menu. By default vehicle layout has focus. You can use arrow keys and any other usual switches, but they are anchored only to this window. Then you can press Tab or `>` and `<` and switch focus to the other window, where you can use arrow keys to scroll the list.

**Comment by mlangsdorf** [comment]
We've already taught people that arrow keys handle scrolling through the vehicle display and that you can use [ and ] to scroll through the vehicle descriptions at the same time. I'd rather not change that interface right now.

**Comment by ZhilkinSerg** [comment]
Minor issue in keybindings menu (probably not strictly related to changes introduced in current PR):

image

**Comment by mlangsdorf** [comment]
No, that's definitely an error introduced by me.

Fixed with a shorter keybind description.

**Pull request merged**
