### PR TITLE
Made reinforced garbage bags watertight

### PR DESCRIPTION
**Pull request by DragonWizard23**
#### Summary
Balance "Reinforced garbage bags are now watertight"

#### Purpose of change
I was trying to come up with a way to haul water from a toilet and thought that a garbage bag might work, based on its "waterproof" description. It didn't, so I tried a reinforced garbage bag, which didn't work either. 

#### Describe the solution
I made the reinforced garbage bag's pocket watertight and edited the description for the standard garbage bag. Garbage bags are usually pretty close to being watertight IRL, but they often have small leaks, especially if the bag gets damaged. Therefore, I only made the reinforced garbage bag watertight. 

#### Describe alternatives you've considered
I briefly thought about how vehicle gas tanks can leak over time, but decided that was overly complex for garbage bags. 

#### Testing
This is a two-line JSON edit, so I simply checked that the formatting and spelling are correct.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Since your goal is to get a bag you can carry water in, I'd verify that you actually can do that as part of the testing. It's no good to have something that's syntactically correct but doesn't do what you intended it to do anyway because of something else being absent or the wrong syntactically correct token being used (unlikely in this case, but better check it anyway).

**Comment by DragonWizard23** [comment]
@PatrikLundell Yeah, you're right. I should remain through with my testing, even on small changes. I've now checked that the reinforced back can hold water, and it does!

**Comment by I-am-Erk** [comment]
updating to master should fix your failing tests.

**Comment by DragonWizard23** [comment]
I'm still not familiar with git, but I think I updated both my master branch and then merged those updates into this branch? It says it "merged cleanly".

**Comment by I-am-Erk** [comment]
Yep you did it right, I'll merge once the last few tests pass

**Pull request merged**
