### PR TITLE
[CR] Addition of Bone Armor

### PR DESCRIPTION
**Pull request by Pr0man**
#### Summary:
SUMMARY: Content: "Revision and addition of bone armor"

#### Purpose of change: 
Redesigning bone armor after the removal of the old variant.

#### Describe the solution:
In order to make bone armor not as wonky as it used to be which was basically pieces of bone strung together, it went through a complete redesign,

Not only did it get "streamlined" stat values across the board for said armor in order to not have any dead pieces - like gauntlets or arm guards - it also received redesigned recipes to use not just leather and bone plating pieces, (similar to lamellar armor, meaning it is basically a sheet of material worn over a padded garment, in this case a thin leather piece), but also lots of filament material to reflect this. Those plating pieces have to be sawn out of special bones dropped from skeletons, which are used for the "standard" armor, or Skeletal Juggernauts for an Armor which is a somewhat comparable mix between the "chitinous armor" set and the "heavy survivor armor" set, with both "bone armor" sets lacking in bash but offering superb cutting and chipping qualities for their encumbrance values.
Quick Info: 
Standard armor values: 6/12 Bash/Cut, 1/1 Acid/Env (less bash than Leather) but at 10 encumbrance
Reinforced armor values:  12/25 Bash/Cut, 2/3 Acid/Env (Same bash as Chitin, less cut than heavy survivor) at 22 Encumbrance (a mix between both armors)
The recipe now involves not only more leather overall - at least for the "Standard" bone armor (but less leather than a full "armor" made out of it, justified by having it be a single layer) - but also a more demanding craft in terms of creating several bone plating pieces, with the hardened bones aquired from skeletons being faster and easier to work on (reflected in the tool and time requirements) than the reinforced boneplates. The Reinforced boneplate armor in turn does require just as much leather as the standard "leather armor" pieces in order to reflect it being just upgraded leather armor utilizing pieces of boneplating that retained some of its attributes after extraction.

#### Describe alternatives you've considered: -Streamlining many armor pieces to resemble what one would consider to be a "set" 

having to mix gear in order to achieve relatively even armor values (for certain encounters), or relatively even encumbrance values (for general gameplay) for something that is considered to be the sophisticated work of a person surviving, training and/or reading in tailoring books by designers, is more frustrating than anybody would believe, especially when considering that survivor would be trying anything to find the balance between protection and utility.

#### Additional context:
There have been many reports on armor that was fashioned in a lamellar style using bone pieces, so the idea is not entirely unheard of. While it is true that most of the armor only saw ceremonial use, it differs only little from a chainmail or metal lamellar armor in that many interlaced pieces - that are individually weak - provide enough protection that is strong enough to withstand blows, or more likely, arrows and spear tips. I presume most of these armors rarely saw combat due to the amount of work that has to be put into creating such an armor, which would make it more of a valued trophy. Yet it is unlikely that clothing outfitted with an extra layer of interlaced bone plating pieces will vastly underperform to any normal armor known.

Side Note:
Many of the actual deletions/additions are actually due to me running every altered file through the provided linting tool, overall, the armor addition isn't all too big, adding some recipes, items and the appropriate harvest entries.

### CODE REVIEW

**Comment by Mecares** [comment]
I think Kevin has been pretty clear about his decision that there is no place for bone armour in the mainline, so maybe it is a better idea to add it to a mod. More survival tools comes to mind or maybe even Crazy Cataclysm.

**Comment by I-am-Erk** [comment]
Oh fun another post about this so we can all go complain about how mean the devs are for not wanting to have the same discussion about why an exceptionally rare armour that has no real niche in the game world and barely existed in real life needs to exist! Good times.

Why not make a suit of armour out of scrap metal sewn onto a leather jacket?

**Comment by kevingranade** [comment]
AFAICT none of my concerns here were addressed:
https://github.com/CleverRaven/Cataclysm-DDA/pull/28083#issuecomment-460861900
Also please split linting from content changes.

**Comment by Photoloss** [comment]
> AFAICT none of my concerns here were addressed:
> [#28083 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/28083#issuecomment-460861900)

Unfortunately *those* concerns were poorly worded at best. I *did* reply asking for clarification but you never engaged.

However the important point is [this one](https://github.com/CleverRaven/Cataclysm-DDA/pull/28064#issuecomment-461250806), any structural enhancement in infected does not have the same stability/ontological inertia as real-life materials but rather relies on constant maintenance from the Blob. This prevents the effective use of skeleton-enemy bone unless you can figure out a way of keeping them "alive" and regenerating (i.e. strapping bisected skeletons to your vehicle *might* work depending on the specifics of the revival process but would likely carry a risk of them reviving fully and jumping off to attack you)

**Pull request closed without merging**
