### PR TITLE
Fix Windows path encoding

### LINKED ISSUE #51204: Crash when the character template name include a 2-byte code.
### Describe the bug

If the language used is set to Japanese or other 2-byte codes, an error occurs when trying to save the Last Character.template during character creation. This is because the template file name is automatically named to "前回のキャラクター設定.template" when language used is set to Japanese.

The character template will fail to save and the file name "前回のキャラクター設定.template.1016.temp" will remain in templates folder.

If you have a previously created character template that contains 2-byte codes, the game will crash immediately upon startup.

### Steps To Reproduce

1. Set 2byte-code language in Interface option such as Japanese.
2. Make new character
3. Failed to save Last Characters template file. 

### Expected behavior

The template should be able to saved correctly even if 2-byte codes in the template name.

### Screenshots

error

### Versions and configuration

OS: Windows10
Game version:2470543 (This occurs in versions after 2021-08-27-2258 or so.)
Ingame language:Japanese

### Additional context

_No response_

### LINKED ISSUE #51239: Creating world using Chinese character failed
### Describe the bug

When I try to create a world named by chinese, it show a error message "Failed to write world data to .save/(garbled characters)/worldoptions.json": opfile failed
And the previous save using chinese will be turn into garbled characters too.
Also saving a template character using Chinese will throw errors.

### Steps To Reproduce

just create a world using a Chinese name

### Expected behavior

Can use Chinese normally

### Screenshots

_No response_

### Versions and configuration

-----------------------------------------
22:12:52.506 : Starting log.
22:12:52.506 INFO : Cataclysm DDA version 5aff6c2
22:12:52.522 INFO : [main] C locale set to C
22:12:52.523 INFO : [main] C++ locale set to C
22:12:52.523 INFO : SDL version used during compile is 2.0.14
22:12:52.523 INFO : SDL version used during linking and in runtime is 2.0.14
22:12:52.620 WARNING : opendir [./sound/] failed with "No such process".
22:12:52.629 INFO : Number of render drivers on your system: 5
22:12:52.629 INFO : Render driver: 0/direct3d
22:12:52.629 INFO : Render driver: 1/direct3d11
22:12:52.629 INFO : Render driver: 2/opengl
22:12:52.629 INFO : Render driver: 3/opengles2
22:12:52.629 INFO : Render driver: 4/software
22:12:52.764 INFO : [options] C locale set to C
22:12:52.764 INFO : [options] C++ locale set to C
22:12:52.764 INFO : Setting language to: 'zh_CN'
22:12:52.765 INFO : Language is set to: 'zh_CN'
22:12:52.765 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:12:52.765 INFO : [translations] C++ locale set to C
22:12:52.936 INFO : Active renderer: 1/direct3d11
22:12:53.812 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
22:12:53.826 INFO : Setting language to: 'zh_CN'
22:12:53.826 INFO : Language is set to: 'zh_CN'
22:12:53.826 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:12:53.826 INFO : [translations] C++ locale set to C
22:13:25.708 INFO : [options] C locale set to C
22:13:25.708 INFO : [options] C++ locale set to C
22:13:25.708 INFO : Setting language to: 'en'
22:13:25.708 INFO : Language is set to: 'en'
22:13:25.708 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:13:25.708 INFO : [translations] C++ locale set to C
22:13:51.516 WARNING : opendir [./save/000/mods] failed with "No such process".
22:20:10.473 WARNING : opendir [./save/111/mods] failed with "No such process".

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
Bugfixes "Fix Windows path encoding"

#### Purpose of change
Based on and closes #51242. Fixes #51239 and fixes #51204.

The errors seem to happen because the GHC filesystem functions assume the paths are always utf-8 encoded, so checks like `file_exist` fail with native encoded paths on Windows. Meanwhile `std::fstream` assumes the path is always in native encoding, so #51242 does not work.

#### Describe the solution
One solution is to assume all paths are utf-8 and use `fstream` wrappers to handle utf-8 paths, another is to change `file_exist` and friends to use the native encoding. I decided to go with the former solution.

However, despite that `std::fstream` expects the path to be in native encoding, the GHC `fs::fstream` wrappers simply pass the utf-8 path to `std:fstream` when compiled with glibcxx on Windows, so file operations still fail if the path contains unicode characters.

Therefore, this PR uses `fs::u8path` and creates `cata::fstream` wrappers based on `fs::fstream` to handle path encoding on Windows properly. In the GHC implementation, `fs::path` simply passes the string as utf-8 without any conversion, but the standard implementation may consider `fs::path` to be in native encoding so `fs::u8path` is used for future-compatibility.

I may later add a clang-tidy check to ensure that we always use `cata::fstream` and `fs::u8path`.

#### Testing
Tested with creation, loading, and deletion of worlds and templates, and no error was raised. Other files were also correctly loaded and saved.

### CODE REVIEW

**Comment by Qrox** [comment]
I did some testing and it works fine now.

**Comment by akrieger** [comment]
Thanks for debugging and fixing this!

**Comment by akrieger** [comment]
Which specific build were the issues happening in? Compiling from msys/mingw?

**Comment by Qrox** [comment]
I think it's builds with glibcxx on Windows (see my explanation in the OP), so msys/mingw do have this issue.

**Comment by akrieger** [comment]
I think in general handling non-ascii characters in paths is messed up. After reverting this change I repro'd an issue with a regular msvc build if I put unicode in the world name, and that's not using glibcxx either. Possibly the issue isn't with what ghc filesystem is doing but just how we are passing and constructing paths in the first place. 

I'll revisit this sometime after I've landed my json to binary stack because I feel like we can get a cleaner fix than using wrappers. This gives me pointers on what to try when I do.

**Comment by Qrox** [comment]
Ah, yes, I was mistakenly thinking about the issue of why using `fs::fstream` did not work.

The original issues were because ghs filesystem expects utf-8 encoded paths but functions like `file_exist` were called with natively encoded paths when the path encoding option is on. When the path encoding option is off, utf-8 paths were passed to `std::fstream`, which expects natively encoded paths. Therefore the whole option was broken on Windows regardless of the compiler.

Removing the path encoding option only fixed the first half of the issues. I then assumed that ghs fstreams would convert utf-8 paths to the native codepage, but turned out it simply passes the utf-8 path to `std::fstream` on Windows if glibcxx is used, so I had to create our own `fstream` wrappers to fix the second half of the issues.

**Pull request merged**
