### PR TITLE
Expand the Hells Raiders: Round 2

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Expand the Hells' Raiders"

#### Purpose of change
Despite the desire to join them not being considered good in #63300, I still think that the Hell's Raiders could use some expanding.

#### Describe the solution
Adds two new bandit-related locations, the slave farm and a drug lab, which contain a variety of loot and NPCs. Existing bandit locations have also been updated with some new mapgen and additional NPCs, to make them feel more alive and working. The larger locations also contain a local gang boss who runs the operations in that area and can be fought. None of these NPCs will talk to you however, as their dialogue has been cut from the last PR. These NPCs, including a gunrunner and quartermaster, bring with them new loot to these highly dangerous structures, providing a high risk-reward tradeoff for approaching them.

The ability to join the Hells Raiders has also been cut from the PR, though non-hostile interactions with the group may come back in the future.

#### Describe alternatives you've considered
This is the alternative.

#### Testing
I tested and loaded everything; it all works like a charm.

#### Additional context
This is some work on #63362, aiming to provide new content to the Raiders.

### CODE REVIEW

**Comment by Procyonae** [comment]
All these locations should probably be globally unique, making the regular bandit maps you're changing a non globally unique version would be good too

**Comment by MNG-cataclysm** [comment]
> Seeing how you mentioned all these NPC's are hostile, what about the slaves they are/were being held by the Hells Raiders? Can we 'the player' talk to them and free them sort of in the same way we can free prisoners from the Mi-Go's?

Yes, the player can talk to and free the slaves they encounter.

**Comment by MNG-cataclysm** [comment]
> All these locations should probably be globally unique, making the regular bandit maps you're changing a non globally unique version would be good too

They're supposed to be regular bandit locations, I don't see why they would need to be globally unique.

**Comment by Procyonae** [comment]
> They're supposed to be regular bandit locations, I don't see why they would need to be globally unique.

Nvm I must have been tripping earlier I thought the higher ups were unique NPCs

**Comment by Daved27hundred** [comment]
I might be in the minority but I feel like the hell's raiders owning slave farms and slaves in general is kind of...dumb, is the best word I can use? Ignoring the touchiness of the subject it doesn't even feel like something they should be able to do.

They're not a kingdom like Ancient Egypt or Greece with the power and wealth behind them to support an operation like this, they're a group of thugs. I don't know how organized they are intended to be but something like that would be a lot of effort to maintain without the slaves either revolting or the leadership falling apart, especially considering there's ten slaves on that farm you have and only six men overseeing it.

I guess this is less a criticism of your PR and more one of the hell's raiders in general.

**Comment by Procyonae** [comment]
> I might be in the minority but I feel like the hell's raiders owning slave farms and slaves in general is kind of...dumb, is the best word I can use? Ignoring the touchiness of the subject it doesn't even feel like something they should be able to do.
> 
> They're not a kingdom like Ancient Egypt or Greece with the power and wealth behind them to support an operation like this, they're a group of thugs. I don't know how organized they are intended to be but something like that would be a lot of effort to maintain without the slaves either revolting or the leadership falling apart, especially considering there's ten slaves on that farm you have and only six men overseeing it.
> 
> I guess this is less a criticism of your PR and more one of the hell's raiders in general.

I feel like it could be written better personally, like rather than them being captured slaves they could be peeps that don't want to risk life and limb so they bought the bandits protection in exchange for stuff they had and now do hard labour in exchange for continued protection?

**Comment by I-am-Erk** [comment]
The narrative around hell's raiders and slaves is supposed to be a pretty complex one, and I pretty strongly feel that it's a very bad place to start with the faction. it sends the message that this is what they are, and at the very least, runs the strong risk of just turning them into a budget bin Caesar's Legion from New Vegas.

I'm not opposed to adding HR content. This just isn't a good place to begin it. Generally, if we were to add a HR base of some sort in the current game, we should probably start with a fortified encampment not to far off the other faction bases. They'd be hostile by default, but once in, we'd add a few quests that would allow you to get in and parlay with them.

Just like every faction, the Raiders should have elements that keep them from being universally 'the baddies'. There are things they're right about and in some ways they've got good points. Opening them up as "these are the guys who attack you and keep slaves" will prevent much development in that direction.

**Review by I-am-Erk — CHANGES_REQUESTED** [review]
See comment above: I think the content here needs to be done a little more cautiously. In general, I think you have a tendency to choose some very complex factions to write about, and I strongly recommend you try to organize your thoughts in a planning issue before you do all the writing and stuff.

**Comment by MNG-cataclysm** [comment]
So, for the time being, I've scrapped the slaves at the farm, and turned the crops into something more reasonable for the Raiders to grow.
@I-am-Erk #63362 outlines much of what I was planning, I just intend for this PR to add some locations instead of meaty NPC content or lore.

**Pull request merged**
