### PR TITLE
Move arming sword from Medieval Stuff mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
Keep moving it.

Move arming sword and its' fake version from Medieval Stuff mod into the main game.

Changes:
1. Reduce weight of arming sword by half.
2. Add inferior arming sword to some item groups.
3. Reduce spawn rate of arming sword in some item groups.
4. Add arming sword and its' fake version to No Medieval Items mod's blacklist.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Neat!

**Comment by chaosvolt** [comment]
Ah, nice.

**Comment by Coolthulhu** [comment]
When moving "good" items to master, include their damage per 100 moves value, for balancing purposes.
For swords, the adjusted damage per 100 moves should not be over 45.
[Check the formulas for "Damage"](doc/GAME_BALANCE.md)

**Comment by Darkyhard** [comment]
> When moving "good" items to master, include their damage per 100 moves value

How do I calculate it?

**Comment by Coolthulhu** [comment]
Easiest way would be to spawn a character, debug-set the strength to 0, spawn the item and note its bashing, cutting and time per attack. Then add bashing and cutting together, multiply by 100 and divide by time per attack.

**Comment by chaosvolt** [comment]
And, if I recall, to-hit is also mention in the documentation for game balance.

**Pull request merged**
