### PR TITLE
Left/right sprite flipping in iso mode. Run and crouch overlay. Minor extras.

### PR DESCRIPTION
**Pull request by kristleifur**
* add isometric branches to facing-left/facing-right calculations for monsters and player (including actions and ranged). The calculations are reasonably simple and fast.
* enable sprite flipping in isometric mode when appropriate
* clarify to-flip-or-not-to-flip code for right/left-facing stuff
* flip all entity and overlay sprites in hitbutton_iso so they are facing right like in all the other tilesets :)

* add run and crouch tile overlay support
* add run and crouch overlay tiles to hitbutton_iso tileset

* add parameter comments to some function calls that have many parameters

* sneak brainless zombie sprite into hitbutton_iso tileset

* bonus: unshadow a couple of variables in a big tile-drawing function (x, y, col)

#### Summary
```SUMMARY: Interface "Left/right sprite flipping in iso mode, run and crouch overlay"```

#### Purpose of change
Until now it has only been in non-isometric mode that sprites have been flipped right/left to match orientation. Here's an attempt at addressing that. Run and crouch sprite overlay support is also added, as well as tiles to support it in hitbutton_iso.

#### Describe the solution
Added simple and fast logic to get the left/right movement in isometric space. Added iso logic to sprite-orientation draw calls to allow horizontal flipping. (Still no rotation or vertical flipping in iso mode.) Clarified some code a little bit too.

Also flipped all entity sprites in hitbutton_iso to be RIGHT-facing instead of left-facing. All the other tilesets have right-facing sprites out of the box.

We also add a RUN and CROUCH overlay tile support.

Plus some comments and cleanup, and a brainless zombie sprite.

Sending this in as one big pull request. My apologies. Thanks for your patience. The thing is that because of the sprite flipping that was required for hitbutton_iso, untangling this into separate PRs was a noticeable amount of hassle. The work came about in a long hacking session. Maybe this is all decent enough to be accepted as-is? If it's hard to work with this PR as is I'll rework it. Thanks.

I see these as only small changes that bring out the expressivity that's already in the engine. L/R facing sprites, sees-player alerts, and run/crouch overlays add A LOT to the gameplay in isometric mode.

#### Additional context
Screenshots:

Little computer person running to the left with lots of zombies approaching from both sides. Most of the zombies see the player, except some brainless zombies.
Screenshot 2019-06-13 at 23 04 10

Little computer person crouches behind a road roller. Most of the zombies don't see us anymore.
Screenshot 2019-06-13 at 23 09 30

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/tileset-editing-with-imagemagick-jq-fish-clion-and-pixelmator-pro/20228/13

**Comment by kevingranade** [comment]
Nice, minor thing, needs astyling.

**Comment by SomeDeadGuy** [comment]
Yes, thank you! This is something i wanted for a long time!

**Comment by AnthonBerg** [comment]
Thanks for the kind words! – I am undeserving as I keep forgetting to astyle! :) I am full of ambition to improve my citizenship. I'll fix!

**Comment by AnthonBerg** [comment]
There we go!

I also notice that my Summary line could be improved – thanks Night-Pryanik! :)

**Comment by Night-Pryanik** [comment]
You are welcome!

**Comment by ZhilkinSerg** [comment]
@AnthonBerg Yeah, `not` is a standard C++ operator synonym, but <https://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators>.

**Pull request merged**
