### PR TITLE
Fix fertilizer use

### LINKED ISSUE #12049: plants fertilized status is not saved
Fertilize plant, save, load -> you can fertilize plant again

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11394685-plants-fertilized-status-is-not-saved?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by i2amroy**
Fixes #12049.

To be honest I'm not sure what this line of code was supposed to do in the first place; all it seems to do is make it so that the fertilized token disappears whenever you reload a submap.

### CODE REVIEW

**Comment by BevapDin** [comment]
> To be honest I'm not sure what this line of code was supposed to do in the first place;

If I remember correctly, the token used to be removed when the plant state changed, thus allowing to fertilize the plant 3 times, once during each plant state.

**Comment by Coolthulhu** [comment]
Right now it seems that 1 fertilization is enough to boost the plant into fully growing in 1 season.

**Comment by Coolthulhu** [comment]
Can't re-fertilize the plant after it changes a growth stage.
How about re-add that fertilizer removal, but in that `if` at the bottom of the function?

**Comment by i2amroy** [comment]
Sure thing, easily enough done. Give me a moment.

**Comment by i2amroy** [comment]
There we go, now you can fertilize it once in each stage (excepting the fully grown one) for a total of 3 times.

**Pull request merged**
