### PR TITLE
Add tests for health distribution

### PR DESCRIPTION
**Pull request by Coolthulhu**
To avoid operating on pure RNG, I brute force the distribution and operate on that.
This might be a tiny bit rough on the edges due to rounding errors, but gives sane enough results for most of the range. Almost certainly more stable than Monte-Carlo-ing the distribution.

Tests are designed to pass with current health mechanics.
The following tests are implemented:
* Comparison of brute forced distribution with RNG-ed actual one
* 2 seasons of constant 10 `healthy_mod`
* 2 seasons of blackberry breakfasts and fasting afterwards (totally implausible)
* Entire year of pear diet with no night snacking, ie. 3 meals a day (unfeasible, but doable if the player tries very hard)
* Entire year of typical healthy diet: 3 meals, each of 2 oatmeals

The upper and lower bounds on health show that currently the effect of food is very underwhelming:
* Half a year of almost impossibly healthy diet isn't enough to get 70 health, which isn't even half the maximum
* Entire year of "health nut" diet isn't enough to feasibly get 50 health
* Normal-healthy diet isn't enough to guarantee non-negative health

Still, not fixed here. This is just a preparation for fixing, to have some method of testing the changes.

### CODE REVIEW

**Comment by kevingranade** [comment]
> To avoid operating on pure RNG, I brute force the distribution and operate on that.

I don't see a compelling reason to have RNG involved in the first place, so rooting it out is an option.
If it's really so chaotic that a simple monte carlo approach is wildly unstable, I'd much prefer that we do so, because it means it's wildly unstable in practice.

Whether that happens or not, what are the acceptance criteria you're aiming for?  That needs to drive test development, not vice versa.

**Comment by Coolthulhu** [comment]
> I don't see a compelling reason to have RNG involved in the first place, so rooting it out is an option.

Sounds good - I'll change it to deterministic then

> Whether that happens or not, what are the acceptance criteria you're aiming for? That needs to drive test development, not vice versa.

* Highest health score should be feasibly achievable naturally, meaning no gorging on food, just eating very healthy
* Health at least halfway towards lowest possible value should be feasibly achievable naturally, without faulty bionics, drugs, poison or gorging, just by eating only junk food
* Health changes should not take more than an in-game year to go from neutral to one extreme (health changes down could happen faster, possibly due to asymmetry in health range up and down)

**Comment by kevingranade** [comment]
Awesome, glad you're on top of it, just wanted to get a handle on it.

I'd moderate the second to making "significant ill effects", is eating junk food really enough to get you half way to the health level of a homeless junkie?

Since years are mutable, might want to specify the timespan as a number of days.

**Comment by Coolthulhu** [comment]
Reworked in #21512

**Pull request closed without merging**
