### PR TITLE
Reintroduce H&K UCP pistol into FictionalWeapons mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Mods "Reintroduce H&K UCP pistol into FictionalWeapons mod"```
#### Purpose of change

UCP was removed in #30426 , this PR preserves it in a mod.
#### Describe the solution

JSON editing.
#### Describe alternatives you've considered

None.
#### Additional context

None.

### CODE REVIEW

**Comment by kevingranade** [comment]
Why?

**Comment by Rail-Runner** [comment]
> Why?

Well, in most cases I think it's better to move content to some kind of mod than to just completely remove it (at least if content does function as intended) if it turns out to be unfitting in mainline for whatever reason. Someone could want to keep playing with it after all. I went with the existing mod to avoid making yet another mod (there's already quite a lot of them); FictionalWeapons was chosen because it apparently doesn't care much about how rare the guns in question may actually be.

**Comment by kevingranade** [comment]
Ok, so you don't have a reason the UCP should exist, just a knee-jerk reaction to deleting things.

That's not a sufficient reason.

**Comment by ejseto** [comment]
Wait, since when do things in mods need a reason to exist other than "I like it" or "I think it's a cool item"? The UCP is certainly more real than Leadworks or Rivtech, and in an alternate timeline or future time could certainly have been revived and put into production, yet it's not even allowed to exist in a mod called **Fictional Weapons**?

>Someone could want to keep playing with it after all.

This sounds like a reason.

**Comment by kevingranade** [comment]
Since people started thinking it's ok to shoehorn things into unmaintained mods with nonsense rationales like, "you shouldn't delete content".

If someone is actively maintaining a mod, I have no problem letting them put whatever content they want into it, or oking other people putting content into it.

If a mod is unmaintained, it falls to me to decide if an addition fits or not. IMO the UCP doesn't fit in fictional weapons or any other mod in mainline.

**Pull request closed without merging**
