### PR TITLE
Backport #75364

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Backport #75364

### CODE REVIEW

**Comment by RenechCDDA** [comment]
I don't think this needs backporting.

**Comment by GuardianDll** [comment]
i'd like to have it for out of repo modders

**Comment by RenechCDDA** [comment]
It's not fixing a bug. Better modder support is cool and all, but not something that we've previously considered appropriate for backporting.

**Comment by kevingranade** [comment]
It's not at all risky,  which is the main thing I'm worried about.
If we get a *flood* of tiny QoL backport requests that would be different.

**Comment by RenechCDDA** [comment]
OK, sounds reasonable. 👍

**Pull request merged**
