### PR TITLE
Ladders and climbing improvements

### PR DESCRIPTION
**Pull request by Coolthulhu**
Includes #13522 
To sum up the above: Allows seeing stuff on the z-level below in z-level mode. Just the terrain, furniture and vehicles. As in, draws stuff dots with cyan background for stuff. Only curses mode for now.

Adds (step)ladders. Ladder is a deployable piece of furniture that makes climbing easy. That's it. Currently only wishable.

Climbing and falling changes:
- Vehicles help more with climbing
- `map::valid_move` now checks vehicles
- Using `map::valid_move` instead of just checking `TFLAG_NO_FLOOR`. Should prevent falling inside vehicles.
- Allows climbing down by examining ledges. Gives a short summary of how will the fall look like ("3 stories" meaning 3 z-levels, "you won't be able to climb back" etc.) and asks for confirmation. Can hurt less than falling.

### CODE REVIEW

**Comment by stk2008** [comment]
Wow got well excited about this till I read curses only as I play with
tiles...but still awesome work man :)

Thanks

**Comment by Night-Pryanik** [comment]
> Vehicles help more with climbing
Oh my, that means I can climb on the car standing near the high wall, and then climb over this wall?

**Comment by Coolthulhu** [comment]
> Oh my, that means I can climb on the car standing near the high wall, and then climb over this wall?

Not exactly that, but close enough. There is no z-level representing "on the car but below roof". All roofed vehicles are essentially 1 z-level (~4 meters) tall.

There isn't much above (houses don't even have roofs yet), but that will be solved later (in mapgen update).

**Comment by stk2008** [comment]
This is so cool.

So I assume z level vehicles will be a thing one day lime double decker
buses?

**Comment by kevingranade** [comment]
Most likely, but that isn't part of the kickstarter-backed bounties, so it's a bit lower priority.

**Pull request merged**
