### PR TITLE
[WIP] Allow quivers to contain arrows and bolts again

### LINKED ISSUE #40521: Quiver item info display shows no storage and does not show that it can store arrows
# Describe the bug

Quivers have one pocket with 0.00 storage max size and weight.
They also cannot be activated to store arrows.
When looking at arrows it says "can be stored in: bow sling, back holster, hiking backpack, and golf bag" with no mention of quivers.

# Steps To Reproduce
Craft a quiver and try to store arrows.

# Expected behavior

You will be unable to store the arrows.

# Screenshots
quiver
arrow

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2125-g7d04bfa
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
 -->Dark Days Ahead
-Disable NPCs Needs
-SpeedyDex
-Stats Through Skills
-sees-player icon, retrodays
-Fuji's Military Proffesion Pack
-MSX Indicator: REMIX
-Zetsukaze's Hair - O.E EDIT

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Bugfixes "Allow quivers to contain arrows and bolts again"

#### Purpose of change

Fix #40521 

Four of the quiver items (`quiver`, `quiver_large`, `quiver_birchbark`, `quiver_large_birchbark`) had their capacity defined in terms of `ammo_restriction`, but that only works when the pocket has type `MAGAZINE`, so it was impossible to store any arrows or bolts in any of the quivers.

#### Describe the solution

Add `MAGAZINE` type to the quiver pockets, so they can hold ammo. Also make them rigid, so their encumbrance rating does not vary.

Finally, update the quiver descriptions to indicate (a) they can contain bolts as well as arrows, and (b) they can be unloaded or reloaded, rather than "activated".

#### Describe alternatives you've considered

The `ammo_pouch` item in this file needs a similar update, but holds many more kinds of ammo and could not be solved as neatly. Saving that for a future PR seemed wise.

#### Testing

Spawned quivers, bolts, and arrows in game. Stored bolts and arrows in quivers, wore quivers, checked encumbrances.

#### Additional context

**WIP** - When firing a bow, I am getting a message like "You don't have any arrows to reload your `||` self bow", despite having quivers full of arrows. With a backpack full of arrows, however, I am able to fire them.

### CODE REVIEW

**Comment by KorGgenT** [comment]
> but that only works when the pocket has type MAGAZINE, so it was impossible to store any arrows or bolts in any of the quivers.

This should be false, why is this happening? quivers should not be a MAGAZINE  they should be a container

**Comment by wapcaplet** [comment]
> basically, ammo_restriction should work for any pocket type. if it doesn't, that's a pretty big problem.

It does, but only partially. When the pocket is not a MAGAZINE, the total capacity and pocket capacity is displayed as 0:

image

There appears to be no way to direcly reload more arrows into the quiver - the "reload" action is disabled, "activate" says I can't do anything interesting, and "insert" does not list any of the arrows or bolts in my inventory. When I pick up arrows or bolts, they go into the quiver - but I cannot put them there myself.

**Comment by wapcaplet** [comment]
This bug is far more multi-faceted than I realized. First, functionally, the existing quivers *can* in fact contain arrows and bolts. There is no bug with that part.

However there are at least two display-related problems with having "ammo_restriction" defined for an item with a non-MAGAZINE pocket, both related to the item info display being misleading:

- Those ammo restrictions are *not displayed* unless the item is also a MAGAZINE (being in `item::magazine_info`, which quits immediately if the item is not a magazine). This could be solved by refactoring the item info functions so they can display "ammo_restrictions" even when the pocket is not a MAGAZINE.
- Volume and Weight capacity are displayed as 0.0 for non-MAGAZINE pockets (all pockets with "ammo_restriction" have their volume set to 0, because their capacity is limited only by what kind of ammo is put into it). This can be solved by completely omitting volume/weight capacity from the item info display for "ammo_restriction" pockets, regardless of whether the pocket is a MAGAZINE or not.

Related to putting items in the quivers, another misleading-display issue concerns the "Insert" menu. When using the "insert" popup menu for a quiver or ammo pouch, it may show "Your inventory is empty", when it really means any of several things, including:

- "This pocket is already full"
- "This pocket is partly full, but you have no more of the same item"
- "You don't have any compatible items that can be inserted"

How to distinguish and simplify these cases is another issue; they are already fairly cleanly handled for the "reload" action with MAGAZINE types, but extending them to work with "inserting" with non-MAGAZINEs may need to be a separate PR.

**Comment by wapcaplet** [comment]
I have a better solution on the way with #41532 - closing this PR.

**Pull request closed without merging**
