### PR TITLE
Vehicle json tidy-up

### PR DESCRIPTION
**Pull request by TheGoatGod**
#### Summary

Infrastructure "tidy up vehicle json"

#### Purpose of change

tidy up vehicle json

#### Describe the solution

use the vehicle script to tidy up .json

#### Describe alternatives you've considered

leave as is, works both ways

#### Testing

tested the script on GMC all the mods work fine (well with the code changes)

### CODE REVIEW

**Comment by BrettDong** [comment]
Looks like some numbers or qualities were unintentionally modified because unit tests are failing.

**Comment by TheGoatGod** [comment]
> Looks like some numbers or qualities were unintentionally modified because unit tests are failing.

nothing I've done

**Comment by TheGoatGod** [comment]
for some reason it makes your stuff fail? is `[  ]` working for vehicle json properly? because the script just organized the parts into a single object, there one to one so I don't understand how the ``
General build matrix / varied_builds (g++-7, 1, 1) (pull_request) Failing after 5m — varied_builds (g++-7, 1, 1)
`` failed

**Comment by TheGoatGod** [comment]
don't believe this will get pr'ed as is failing and must be the cause in

**Comment by actual-nh** [comment]
> don't believe this will get pr'ed as is failing

Take a look at the vehicle tests that are failing - should be possible to figure out what's going wrong.

**Comment by Maleclypse** [comment]
I keep seeing errors saying the part etc can't be installed on space x,y.  I'm wondering if you have to have a frame part separate from the other parts? I don't know enough about vehicles to really have a better guess.

**Comment by TheGoatGod** [comment]
> I keep seeing errors saying the part etc can't be installed on space x,y. I'm wondering if you have to have a frame part separate from the other parts? I don't know enough about vehicles to really have a better guess.

if this is the cause ill need to go over everything one to one 1:1 ah possible as it merged multiple lines

**Comment by TheGoatGod** [comment]
this defo needs additions/support to src, I have to ask why does half the code work and the other half doesn't this way? it must not be fully supported somehow, after checking the json im 100% sure that its fine, something is wrong on the other end.

**Comment by TheGoatGod** [comment]
i think this is unfixable

**Comment by TheGoatGod** [comment]
BORKED

**Comment by mlangsdorf** [comment]
There's a perfectly function vehicle reformatter script in `tools/vehicle_reformatter.py` which produces sensible output that won't break the game.  It's also substantially different that the output of whatever script you used to reformat the vehicles.  I'm not that great a Python programmer and this is an open source project, so I don't object at all if people rewrite my scripts or write a superior version.  However, I'm not sure about the point of writing a new version of one of my scripts that produces incorrect output.

**Comment by TheGoatGod** [comment]
> There's a perfectly function vehicle reformatter script in `tools/vehicle_reformatter.py` which produces sensible output that won't break the game. It's also substantially different that the output of whatever script you used to reformat the vehicles. I'm not that great a Python programmer and this is an open source project, so I don't object at all if people rewrite my scripts or write a superior version. However, I'm not sure about the point of writing a new version of one of my scripts that produces incorrect output.

if only it was easy to use this py, `usage: vehicle_reformatter.py [-h] vehicle_sources [vehicle_sources ...]
vehicle_reformatter.py: error: the following arguments are required: vehicle_sources`

**Comment by mlangsdorf** [comment]
`python tools/vehicle_reformatter.py data/json/vehicles/cars.json` reformats cars.json.

**Comment by UmbralReaper** [comment]
> There's a perfectly function vehicle reformatter script in `tools/vehicle_reformatter.py` which produces sensible output that won't break the game. It's also substantially different that the output of whatever script you used to reformat the vehicles. I'm not that great a Python programmer and this is an open source project, so I don't object at all if people rewrite my scripts or write a superior version. However, I'm not sure about the point of writing a new version of one of my scripts that produces incorrect output.

uh... I don't know how I missed that. The script I wrote was a hacky implementation I wrote because there was nothing else and I always intended to improve but never got around to. Yours is superior, 100%.

**Pull request closed without merging**
