### PR TITLE
Bionics can use integrated armor system

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Features "Bionic Integrated Armors"

#### Purpose of change
Mutations got new cool integrated armors, but bionics were still using the same old derpy 100% flat coverage, flat defense system and I wanted to fix that. Further, the system allows for some new bionics which weren't possible beforehand without attached armor pieces. If the Internal Storage CBM shows up in the Nether at some point it could use this new system for its pockets as an example.

#### Describe the solution
Integrated bionic armor uses the passive_pseudo_item system. If the item type of a pseudo item is an armor with the integrated flag, it will be visible in your inventory and will be equipped to your character.

~~The bionic armor in the game has been revamped from the previous bionic system to proper complicated new armor. It occupies the skintight and normal layers except for the head, eyes and face which occupy the inner layer only. The armor bionics should be "layerable" utilizing the upgrade system eventually, so you start with the basic armor and then start upgrading with variety OUTER layers to differentiate your cyborg.~~

~~This armor specifically is made of Superalloy, representing a magnesium alloy such as AZ80A. At roughly 60-65% the strength of good quality steel but only 25% of the weight according to my research it seemed like the ideal candidate for an armor set that is worn 24/7. Underneath this is a material represented with Plastic, as a sort of flexible polymer used by the Exodii as artificial skin. Lastly there are points with thin reinforcement of qt_steel such as elbow and knee pads, knuckles, toecaps and the forehead.~~

~~Rather than be an actual wearable and removable armor, this is a CBM since its integration both allows for minor breathability - it interfaces with your sweat glands to expunge some heat from your body and as such has AVERAGE breathability in many spots and POOR in some others. It will also serve as a barrier against infection when skin-breaching bionics gain the appropriate functionality (likely these will treat injuries as if the limb was wearing filthy clothing and also cannot be accessed if covered by non-integrated armor). Although it is not conventionally removeable, these can be uninstalled again with all the usual risks since they do not replace your epidermis, just envelop it and sink their techy bits into it. Later on you could remove your skin from inside these bionics to make more room with the risk that these being breached potentially means your death.~~

~~At present it is unbreakable, though I expect that to change when a more robust system of CBM maintenance in place. There is also currently not any logic to remove a specific bionic when its component integrated armor is destroyed. However when the time comes we could use this system and create a "inside_skin" layer to represent bionics suffering damage occasionally.~~

~~Kevin has requested this be changed because its functions are too much sci-fi handwavium. Now it is layers of thin internal plates and latticed carbon reinforcement. Some exterior coverage remains but less than half the body has external plating. Occupies the SKINTIGHT layer only now. Fewer mutations are affected since it does not completely replace your epidermis.~~

Changes to alloy plating have been undone, they are exactly the same as they were before. Subdermal Carbon Filament and Protective Lenses do have integrated armors to demonstrate the new system.

#### Describe alternatives you've considered
~~Now that these bionics explicitly encase the skin as a suit of armor glued to the body these perhaps shouldn't interfere with as many mutations anymore. If you suddenly mutated fur under your bionic armor you would get appropriate, disastrous encumbrance penalties to represent your bionics and body clashing horribly.~~
The passive_pseudo_item structure being reused for integrated armor is a bit of a hack but it seemed like the most convenient and simple solution to me.

#### Testing
New character spawns with all the bionic armor pieces on creation. (Razorgirl/Razorboy)
Character who installs bionics gets the integrated armor pieces.
Character who removes the bionics at an autodoc has the armor deleted from inventory.

#### Additional context
protective lenses
subdermal carbon filament

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Looks great, but the cyborg changes may be better separated.

**Comment by anoobindisguise** [comment]
> Looks great, but the cyborg changes may be better separated.

I forgot to mention those. I intended to upgrade their armor to reflect the improved alloy CBMs since they are harvested from them. But you are right, I'll go ahead and undo that.

**Comment by OtpalTS** [comment]
This looks amazing. To me it looks like this will prevent wearing underwear? Also incompatible with the Exodii bodyglove, which could be explained by it being made for members who haven't made such radical changes to their bodies.

**Comment by anoobindisguise** [comment]
> This looks amazing. To me it looks like this will prevent wearing underwear? Also incompatible with the Exodii bodyglove, which could be explained by it being made for members who haven't made such radical changes to their bodies.

That's correct, if you attempt to wear close to skin gear you will get extremely large penalties due to mislayering, and normal layer gear will also incur stacked up penalties but you can cram yourself in a jumpsuit if you really want. Warm coats should still be enough for winter, but if it ever isn't, there's a CBM for that!

**Comment by AtomicFox556** [comment]
You may want to convert Subdermal Carbon Filament CBM to use this system as well. Probably a good candidate for skintight/inner layer armor.

**Comment by anoobindisguise** [comment]
> Speaking of additional "cyborg" armor on outer layer: I think it'd make the most sense for such armor to just be shaped plates of metal (or some other kind of material; possibly some of it could even be craftable) that can attach to purpose-made attachment points on integrated CBM armor, sort of like ballistic plates currently function. That is mostly because I don't see any reason to require special machinery to attach more layers to one's body if it's already covered in integral artificial armor (the same works for said armor removal as well).

Ideally once you convert your body to a proper cyborg frame you'll be able to do something like that, although you'll likely need the Exodii to do it so that they can properly wire up all your bionics and integrate it with your armor. If you have a monomolecular blade you'll need to have your armor specialized to accommodate it so it's not as practical to just snap the armor on. And that's just one example of many.

**Comment by anoobindisguise** [comment]
> In that case you'd first want to implement worn items in general preventing some bionics from functioning properly (such as said monomolecular blade, or Cloaking System CBM that is described as being a "set of cameras and LEDs", but somehow is still able to function even while wearing clothing that covers the whole body). In fact it's probably a more common case than some bionics conflicting specifically with bionic armor plating and nothing else.

Yes that's next on the list, I'd like to distinguish bionics which breach the skin and bionics which are contained within your body, and which body parts need to be uncovered for certain bionics to function, and ideally what threshold of coverage is too high + what part of the sublimb is covered (so monomolecular blade covers forearm but not elbow and upper arm). Then prevent you from activating or refueling those bionics if the limb is inaccessible and making the limb more prone to infection if it doesn't have a bionic armor covering it. That'll be a complex process though.

**Comment by anoobindisguise** [comment]
I went ahead and added some "//": JSON comments to explain my thought process in a way that is more preservative than what I said in this PR. Confirmed those don't cause any errors.

**Comment by kevingranade** [comment]
I haven't had a chance to review the implementation, but based on your description you're trying to have the best of both worlds, which is a non-starter. "Interfacing with sweat glands" is incoherent, if you seal the skin behind a metal shell, you're in a metal shell, and sweating isn't going to work. Plus, "this doesn't replace the skin" and "your skin is permanently sealed inside a metal shell" is a massive contradiction, your skin *must* have access to open air, for sweating, shedding skin, infection management, etc.
This is the whole reason the previous concepts were either skin replacing or subdermal, you can't just seal your skin away and not like, die.

**Comment by anoobindisguise** [comment]
> I haven't had a chance to review the implementation, but based on your description you're trying to have the best of both worlds, which is a non-starter. "Interfacing with sweat glands" is incoherent, if you seal the skin behind a metal shell, you're in a metal shell, and sweating isn't going to work. Plus, "this doesn't replace the skin" and "your skin is permanently sealed inside a metal shell" is a massive contradiction, your skin _must_ have access to open air, for sweating, shedding skin, infection management, etc. This is the whole reason the previous concepts were either skin replacing or subdermal, you can't just seal your skin away and not like, die.

This could instead replace your skin and be unremovable. We just currently don't have a system in place to prevent sweating entirely, so even if it is totally unbreathable you'll still accumulate moisture.

**Comment by Terrorforge** [comment]
I don't like the 50% + 50% + 50% + ... implementation. That makes it really hard for the player to understand how good this armor actually is. In fact, it's so confusing that even the armor UI doesn't understand it - it seems to think that the average protection value for almost all of these is just the Carbon lattice. If you want to simulate varying degrees of protection, better to do it with sublocations and maybe two or three armor layers, like you started out with.

Also fwiw the Epicuticle mutation uses the PERSONAL ("Personal aura") layer to represent armor that replaces the skin. I don't think that's what PERSONAL is supposed to be for, but IMO there probably _should_ be a layer that represents stuff that replaces or goes under the skin for CBMs and mutations to use.

**Comment by anoobindisguise** [comment]
> I don't like the 50% + 50% + 50% + ... implementation. That makes it really hard for the player to understand how good this armor actually is. In fact, it's so confusing that even the armor UI doesn't understand it - it seems to think that the average protection value for almost all of these is just the Carbon lattice. If you want to simulate varying degrees of protection, better to do it with sublocations and maybe two or three armor layers, like you started out with.
> 
> Also fwiw the Epicuticle mutation uses the PERSONAL ("Personal aura") layer to represent armor that replaces the skin. I don't think that's what PERSONAL is supposed to be for, but IMO there probably _should_ be a layer that represents stuff that replaces or goes under the skin for CBMs and mutations to use.

Right, this is due for a change anyways. There's been a bit of ruckus in the dev discord trying to finagle this into something that is workable due to the various issues inherent in synthetic 24/7 armor that is surgically affixed to your body. It's entirely possible this PR will be stripped down to just the infrastructure. And yeah, I've considered using PERSONAL but these had some external armor too that made it just bulky enough to be considered "SKINTIGHT" (1mm or so)

**Comment by anoobindisguise** [comment]
Alloy plating changes are no longer applied whatsoever, they are exactly the same as before, but can be removed now because they are very likely going to be obsoleted and characters should have a chance to get rid of their obsolete bionics when it happens.

**Comment by bombasticSlacks** [comment]
Why the aftershock removals?

Also this now has a conflict

**Comment by anoobindisguise** [comment]
> Why the aftershock removals?
> 
> Also this now has a conflict

Taking a look at the conflict. 
When the alloy plating bionics were made non removable, the Aftershock devs requested that they specifically be removable in aftershock. Since they're no longer non removable there's no reason to maintain that distinction.

**Pull request merged**
