### PR TITLE
Process of adding Whaley's Location Mods (1 of 9)

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
**THIS PR WAS REMADE [HERE](https://github.com/CleverRaven/Cataclysm-DDA/pull/25070)**

This process intends to add Whaley's Location Mods to the game (those that haven't already been added). Before getting to adding said locations I thought it would be a good idea to combine some mapgen files and organize the mapgen folder a bit.

This **first** step does just that, combines many mapgen files (ex. combines pool.json & pool1.json into just pool.json). It also moves and renames several files to organize the mapgen folder. But, because this PR was getting fairly lengthy I'm splitting this organizational stage into 2 steps. The steps that will proceed this one are as follows.

**2 of 9** - Finish combining/renaming/moving mapgen files (specifically Whaley's early additions in the "parks_recreation" and "small_town_buildings" folders).

**3 of 9** - Move Whaley's official (in-game) mod, "More Buildings" (including: baseball field, daycare, pet store, rest stop, shopping plaza, storage units, thrift store and a hunting supply store) to the vanilla game and removing it as an official mod.

**4 of 9** - Add Whaley's Zoo (from his "Big Buildings" mod).

**5 of 9** - Add Whaley's Stadium (from his "Big Buildings mod).

**6 of 9** - Add the remainder of Whaley's "Big Buildings" mod (including: derelict properties, dispensaries, head shop, natural spring, pet store,  and another gun store variation).

**7 of 9** - Add Whaley's "City Entertainment" mod (including: gambling hall, movie theater, music venue, paintball field, smoke lounge, and another military surplus variation).

**8 of 9** - Add Whaley's "Seedy Spots" mod (including: crack houses, detached houses, homeless camps, scrapyards, strip clubs, trailer park, another coffee shop variation, and another park variation).

**9 of 9** - Add Whaley's "River Buildings" mod (including: boat rental, moonshine camp, river houses, and rural houses).

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Could you please revert the gas station jsons combining until my PR with jsonifying gas station will be merged?

**Comment by ZhilkinSerg** [comment]
Please update records in `\json_blacklist` when renaming files. For example:

There are following records in this file:

```
data/json/mapgen/clothing0.json
data/json/mapgen/clothing1.json
data/json/mapgen/clothing5.json
```

You moved all data from `clothing_x.json` to single file `data/json/mapgen/s_clothing.json`, but didn't lint files, so you should add `data/json/mapgen/s_clothing.json` to `\json_blacklist` to satisfy json checker.

**Comment by ZhilkinSerg** [comment]
`data/json/mapgen/s_gun.json` should probably go to blacklist too.

**Comment by Night-Pryanik** [comment]
While you are here, I think it's safe to delete `ags_station.json` as it is a full duplicate of `gas_station.json`. Also, rural gas stations from `s_gas_rural.json` now could be added to `gas_station.json`.

**Comment by cosmiccoincidence** [comment]
I notice the checks say "Conflicting files - data/json/mapgen/gas_station.json"
Should I have not renamed it to s_gas.json and left it as is?

**Comment by ZhilkinSerg** [comment]
You would need to change `add` to `place_item` in some of the files (as shown in https://github.com/CleverRaven/Cataclysm-DDA/pull/24530).

**Comment by Night-Pryanik** [comment]
> I notice the checks say "Conflicting files - data/json/mapgen/gas_station.json"
Should I have not renamed it to s_gas.json and left it as is?

I think you should combine all versions of gas stations into one `gas_station.json`.

**Comment by cosmiccoincidence** [comment]
> I think you should combine all versions of gas stations into one gas_station.json. All other files (ags_station.json, s_gas.json, s_gas_rural.json should be deleted after combining.

This was done 2 commits ago after you mentioned it before.
The final gas station file I named s_gas.json rather than gas_station.json, and I was wondering if that's why I was getting the conflicted file. 
And now I have many conflicting files. I imagine because many of the conflicts are files I deleted or renamed.

**Comment by Night-Pryanik** [comment]
I keep repeating this because I don't my variant of gas station anywhere. It was in `gas_station.json`, but you deleted the file.

**Comment by cosmiccoincidence** [comment]
Sorry about that buddy, I think the point you were making was just going over my head. And apparently I messed up by not getting the new version of the file after your PR was merged. But it is added now.

**Comment by BrianLefler** [comment]
Also for add->place_item, make sure your chances are in percentiles NOT one-in-X, like you would for place_items.  In my experience some were and some weren't (depending on whether the dev knew the old add behavior was different than place_items)

**Comment by cosmiccoincidence** [comment]
Fixed conflicting files by merging cleverraven master to my master again and updating this branch with the changes.

**Pull request closed without merging**
