### PR TITLE
Chitin plating now requires rope to install instead of a welder

### LINKED ISSUE #28608: Chitin plating should install via glue/tape not welding
**Describe the bug**  
Chitin armor kit -> Chitin plating
installs via welder despite having no metal components

**To Reproduce**  
find a vehicle
give yourself fabrication 10
compare the recipe for the kit, vs it's install requirements

**Expected behavior**  
Should require tape or glue to install, similar to how wooden armor kit installs via nails

**Screenshots**  
ask if needed

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version: 0.D-155-gede79d4
 - Graphics version: tiles
 - Mods loaded: lots, ask if needed

**Additional context**  
ask if need save or anything else

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Chitin plating now requires rope to install instead of a welder."```

#### Purpose of change
Closes #28608.

#### Describe the solution
Added explicit requirements to install and repair chitin platings. 
Though I thought that using glue or tape to install a part that takes most of the damage when vehicle is hit makes little sense, so I made it require a rope to install and adhesives to repair.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Closing in favor of #28610

**Comment by EvgenijM86** [comment]
The problem with this solution is when you remove the plating you don't get the ropes back. So, if you want to redo the vehicle shape or replace the frames you would have to spend a couple of days/weeks searching for rags and recrafting ropes.

**Comment by EvgenijM86** [comment]
Another solution would be to use welder + scrap metal, so that you make a metallic placeholder where platings are inserted. It would make much more sense to do this instead of using ropes, because if you use ropes in reality then your plating would only be as strong as your ropes - once the rope rips apart your plating would just drop on the ground. Assuming that realism is the priority here.

**Comment by Night-Pryanik** [comment]
> The problem with this solution is that when you remove the plating you don't get the ropes back.

That's not the problem of this solution itself, but with our vehicles construction system instead. There is similar issue with it - #22938.

**Pull request closed without merging**
