### PR TITLE
[RDY] Swapped uncommon smgs for more common and added missing magazine spawn

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
~~Swapped the automatic TEC-9 with the RM360 rotary carbine.~~ The automatic TEC-9 isn't really that common IRL, and people have been asking for more modern and future weapons. Also added spawns for the RMRB200 .22 magazine, which had been missing. I might swap the American-180 with the UZI 9mm in future.

What do you think @Rivet-the-Zombie ?

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
The Mini-UZI could be added as a functionality replacement for the TEC-9, since it could also fit in small holsters. https://en.wikipedia.org/wiki/Uzi#Military_variants

**Comment by Rivet-the-Zombie** [comment]
None of the Rivtech guns are supposed to be super common.

**Comment by BorkBorkGoesTheCode** [comment]
Ok @Rivet-the-Zombie . I was going to swap the American-180 with the UZI in a later commit to complete the replacement of super rare SMGs in smg_common with more modern guns, but I could revert the RM360 change and use the UZI 9mm instead.

**Comment by kevingranade** [comment]
Hah, Tommyguns and tec9s aren't exactly common either, at some point we really need to look into a baseline of rarity for a lot of these crazy rare guns.
This is an improvement though so I'm not asking you to close it.

**Pull request merged**
