### PR TITLE
The UCP was never a thing.

### PR DESCRIPTION
**Pull request by tenmillimaster**
#### Summary
SUMMARY: Bugfixes "Replaces UCP with MP7's, corrects MP7 stats"
#### Purpose of change
[The very limited amount of information](<http://pistol-training.com/archives/1740>) about the H&K P46 'UCP' pistol, companion to the MP7, indicates that it never left prototype stage due to inadequate ballistic performance.  This seems credible given that no one seems to have adopted it, unlike the FiveseveN, and the information hasn't been disputed.

#### Describe the solution
Delete the UCP from item groups and  replace all UCP's with MP7's. As a consolation prize, I've also updated the MP7 with its real world stats (same method as I used for backup pistols, treating the SMG as a box).  <https://en.wikipedia.org/wiki/Heckler_%26_Koch_MP7>

415mm * 51mm * 169.5mm * 0.001 = 3587mL.
#### Describe alternatives you've considered
Leaving well enough alone, which isn't an option.

### CODE REVIEW

**Comment by Ilysen** [comment]
***Guns aren't real and you've never seen one. This is not a joke.***

**Comment by AMurkin** [comment]
> Balance, Bugfixes

Choose one. Multiple aren't supported.

`SUMMARY: Bugfixes "Replaces UCP with MP7's, corrects MP7 stats"`

**Comment by Shodan14** [comment]
Hmm, I always thought it was the [H&K USP](https://en.wikipedia.org/wiki/Heckler_%26_Koch_USP) tbh.

**Comment by kevingranade** [comment]
If you do a migration, you don't actually need the obsolete entry.

**Pull request merged**
