### PR TITLE
Update 762x25.json (from #18988)

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Since #18988 was rendered unmergable by another PR, I decided to send in the rebalance with tweaks.

### CODE REVIEW

**Comment by mugling** [comment]
Consider merging this with the expanded ammo PR?

**Comment by BorkBorkGoesTheCode** [comment]
No

**Comment by mugling** [comment]
762x25 is so rare it's de facto useless. Moving that to the new mod would help bulk it out.

**Comment by BorkBorkGoesTheCode** [comment]
Why is it desirable to have the current recoil value?

**Comment by mugling** [comment]
I mean #18988 - doesn't that add a new item?

**Comment by BorkBorkGoesTheCode** [comment]
>I mean #18988 - doesn't that add a new item?

It did. This doesn't include it. Why do you ask?

**Comment by mugling** [comment]
I assumed you were going to include it here

**Comment by BorkBorkGoesTheCode** [comment]
Can't. I fully expect this PR to become unmergable if I did.

**Comment by Coolthulhu** [comment]
Mergeability depends on order of commits and parent branch. If you manually copy changes to a branch that is based on current master, it will not have conflicts with current master.
Same if you merge a branch onto a branch that is based on current master.

**Comment by BorkBorkGoesTheCode** [comment]
I tried manual merge but it didn't work.

**Comment by mugling** [comment]
Please don't move dispersion between ammo and guns. It makes it hard to compare differing items.

**Comment by mugling** [comment]
[wrong button]

**Comment by mugling** [comment]
Adjustments to one ammo type at once aren't very useful and probably consume too much review time proportionate to their usefulness.

In particular this PR moves `dispersion` and `recoil` from `ammo` to `gun` which in doing so breaks comparison of different ammo and guns.

When I did the aiming rework I calculated all the values on a spreadsheet to ensure there was at least a semblance of balance. Altering items one at a time could at best yield a marginal improvement in a few months or so but is far more likely to break the balance and consume a lot of time whilst doing so.

**Comment by BorkBorkGoesTheCode** [comment]
Please look at the contents of my PRs before giving stock answers.

**Comment by mugling** [comment]
That's hardly a stock answer is it

**Pull request closed without merging**
