### PR TITLE
[WIP] Remove strawberry and blueberry jams - take two

### LINKED ISSUE #20396: Remove strawberry and blueberry jam items, use generic fruit jam (take 2)
This is a copy of issue #20344, which has been auto-closed by PR #20385 and can't be reopened.

PR #20385 has performed the obsoletion incorrectly - see reverting PR #20395.

-----

`data/json/recipes/recipe_food.json` has `jam_(straw|blue)berries` listed as ingredients for "jam sandwitch", but there is no crafting recipe for them.

`grep -Er "jam_(straw|blue)berries" data` shows these specific items are still present in mapgen, item groups, etc..

Generic jam was added in commit 505ebf4708c1a55eb115ec48e442cd75ba9b3dea (part of PR #3521). The PR is huge (+1,039 −54).

Specific jam recipes were removed in bde1d9fa6885819c399b1219bcb6c755fb87a13f (part of PR  #11507). The items themselves were not removed then since that would have "broken" save games (see discussion in PR).

Obsoletion was not imlemented AFAIK at the time of that PR. It is now, so it should be possible to stop spawning specific jams for new savegames.

"Splitting" recipes might require a different approach - don't remember ATM.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20396.

To obsolete properly, should I create `legacy/7`right now or wait for merging of #20368?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Wait.
The legacy support system is horrible at handling any conflicts. It also requires hardcoding version changes.

**Comment by Night-Pryanik** [comment]
Ok.

**Comment by keyspace** [comment]
Could probably add:

> Closes #20396, see that for rationale.

to the preamble/OP.

**Comment by keyspace** [comment]
Perhaps a [WIP] to title, too, since waiting for #20368 resolution.

**Pull request closed without merging**
