### PR TITLE
Adds a "Projectile skip" option to the graphics menu.

### PR DESCRIPTION
**Pull request by vulkans22**
Intended to alleviate the issue where long range, long bursts take an excessive amount of time to animate for people playing graphical on small tilesets and wide viewports. It does so by skipping animation frames by the amount specified in the option screen, thereby speeding up the animation.

### CODE REVIEW

**Comment by Sirbab** [comment]
Oh thank god, i hated going to military bases because of this. (90% of the time i was there was waiting for the bullets.)

**Comment by kevingranade** [comment]
This shouldn't be manual, how about we just do it based on range?

**Comment by Coolthulhu** [comment]
How about an option to make all bullets "tracers" and just draw them as lines? Those could be drawn in a single pass. It's not like the survivor sees the bullet anyway.

**Comment by vulkans22** [comment]
@kevingranade During personal play, shooting at around 40 tiles I've found skipping 4 frames is sufficiently fast on my PC. Would a 10/1 20/2 30/3 40+/4 range set be acceptable? And if hardcoding these values, do you think PC specs might factor into any potential problems? (eg: animating too fast for some and too slow for others)

@Coolthulhu This is what I originally did but I ran into a snag: One of my side projects is filling out sound events for the game. When I got to gunshot sounds I found that doing a burst in a single pass was resulting in an eardrum destroying 10+ sound files being played all at once on top of each other. If such an option were added, it wouldn't be a problem now with the current lack of sound assets, but it would need to be addressed in the future.

**Comment by Coolthulhu** [comment]
> And if hardcoding these values, do you think PC specs might factor into any potential problems? (eg: animating too fast for some and too slow for others)

You could ask for a multiplier instead. "Draw x% of the frames".
At multiplier 0.1, range 100 attack would have frame skip 10, range 35 attack only 3 etc.
That way all attacks would last approximately the same time.

> When I got to gunshot sounds I found that doing a burst in a single pass was resulting in an eardrum destroying 10+ sound files being played all at once on top of each other.

Not a single pass: you'd draw a single line, wait the animation time, draw another line etc.
Or even just hardcode it to only play the sound on the first shot.

**Comment by kevingranade** [comment]
There's already an option for animation delay, that should adjust for different system speeds.
The goal would be for the same number of animation steps being present independent of the range. Obviously there's a floor of the number of squares from you to the target, but that should be fine.
The question then becomes what is the minimum number of draw events necessary to make it clear to the player what is happening.
Also, automatic fire should have its own tradeoff, it should be ok to have fewer animation steps per shot and still make it clear to the player the path that the projectiles are taking.
Another tweak you can make is have the animation step showing where the projectile stops have a longer delay, since that piece of information is more important than the intervening squares the projectile travels through.

**Comment by vulkans22** [comment]
Based on both suggestions, I've elected on a calculation to get skipped frames based on range and a hardcoded multiplier, eliminating the need to set it manually. Testing, it looks like a .1 multiplier equates roughly to a 250ms wait regardless of range.

**Comment by Coolthulhu** [comment]
Minor: bursts have visible "stride" now. Adding an offset to the `projectile_skip_calculation` different for each bullet would help.

**Pull request merged**
