### PR TITLE
[CR] More requirements

### PR DESCRIPTION
**Pull request by Maddremor**
I plan on converting armor crafting recipes to using requirements, making this PR first for the new prerequisite reqs I plan on using.

I could add more reqs while I'm at it if anyone has suggestions.

### CODE REVIEW

**Comment by cainiaowu** [comment]
It would be better if we can change filament requirement from used as component to used as charge.

Currently only filament that are not loaded in the tool could be used to craft clothing which is a bit counter intuitive, and there are lots complain about it.

**Comment by Maddremor** [comment]
Frankly, the idea of loading a sewing tool with thread seems strange for me. I'd rather move in the other direction of having the repair action use thread from the inventory and remove the ability for sewing tools to be loaded at all. However, this is outside the scope of this PR.

**Comment by ZhilkinSerg** [comment]
> Frankly, the idea of loading a sewing tool with thread seems strange for me. I'd rather move in the other direction of having the repair action use thread from the inventory and remove the ability for sewing tools to be loaded at all. However, this is outside the scope of this PR.

That will be addressed in #20569. Sorry for that PR being stalled, but I'm not dropping it and it will ve eventually merged.

**Comment by Coolthulhu** [comment]
Requirements alone are not testable, this will need at least one example per requirement.

I don't like the large leather/fur requirements. They aren't granular and seem to only exist to make tanned leather pieces useful. This is rather backwards, unless you want to remove the smaller scraps someday and just have all leather be handled as those big tanned sheets.
A more correct way would be to simply have the tanned leathers be cut up into scraps as a part of the tanning process.

**Comment by cainiaowu** [comment]
Various meat / veggy / eggs could use requirement system.

**Comment by Coolthulhu** [comment]
This still needs to be updated.

**Comment by ZhilkinSerg** [comment]
Marking as Stalled. Feel free to reopen it.

**Pull request closed without merging**
