### PR TITLE
Fix various encumbrance updates

### LINKED ISSUE #32459: RM13 Combat Armor doesn't update player encumbrance when activated
# Describe the bug

When wearing RM13 Combat Armor, player encumbrance doesn't update a turn after activating, only updating after the player wears/takes-off something else. This goes both ways, allowing the player to have low encumbrance when off, or high encumbrance when on.

Probably caused by the performance update that reduced updates to player/npc encumbrance. This may extend to other activated clothing such as  the riot helmet with facemask, or containers that change encumbrance when holding things like waterskins or magazine straps.

# Steps To Reproduce

1. Wear RM13 Combat Armor, note encumbrance.
2. Activate armor, wait a turn, note encumbrance hasn't updated.
3. Wear/take-off some other item, note encumbrance has updated.
4. Activate armor, wait a turn, note encumbrance hasn't updated.

# Expected behavior

When the armor is activated, encumbrance updates immediately or one turn later.

In previous versions, it would update one turn later either because encumbrance was updated at the end/beginning of every turn, or to stop the player abusing the armor by activating it for less than one turn, gaining its benefits without using fuel cells.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5683-gcd6579b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Survivor Armor [no_survivor_armor],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]
]

### LINKED ISSUE #32529: Encumbrance doesn't get updated when cutting up worn clothes
# Steps To Reproduce

1. Note your encumbrance.
2. Cut up a piece of encumbering clothing you're wearing using `%c`.
3. The encumbrance haven't changed even though the clothes are gone.

0.D-5749-ga24f3b03bf-dirty

### PR DESCRIPTION
**Pull request by Petethegoat**
#### Summary
```SUMMARY: Bugfixes "Fixes many encumbrance updates."```

#### Purpose of change
Make sure player encumbrance is (almost) always updated and correct.

#### Describe the solution
Manually call `reset_encumbrance()` in several places where appropriate.

Add the "ENCUMBRANCE_UPDATE" flag to items that are going to affect character encumbrance, and have characters check for these items every frame to update only if necessary.

#### Additional context
Fixes #32529
Fixes #32459

This doesn't fix encumbrance in all cases, but the remaining issues appear to be caused by unrelated issues in other areas, which I will document and look into separately- ~~refilling a vehicle from a waterskin for example will still not update encumbrance correctly~~, and siphoning into a waterskin will update but be a turn behind the actual encumbrance.

Refilling is now fixed by this PR. :confetti_ball:

### CODE REVIEW

**Comment by daydreamer0000** [comment]
Consider looking at worn containers that change encumbrance when full/empty (waterskins, xl holster, etc...) that I mentioned didn't update in [#32459](https://github.com/CleverRaven/Cataclysm-DDA/issues/32459). # #

**Comment by Petethegoat** [comment]
Have a tentative fix for waterskins etc. May not cover all edge cases, but it does handle siphoning and unloading at least.
Looking into holsters now.

**Comment by Petethegoat** [comment]
Holsters are fixed @daydreamer0000. Let me know if you notice anything else, please!

**Comment by daydreamer0000** [comment]
I have noticed that on the current build encumbrance doesn't update when you select to [w]ield a worn gun with shoulder strap.

**Comment by Petethegoat** [comment]
Fixed, thanks again.

Right now I'm trying to figure out how hard it is to get rid of the nasty `on_contents_changed( &g->u )` calls I've added.
For the item.cpp ones it seems like a pretty deep rabbit hole to go down. The potential downside of leaving it is that the player could get extra encumbrance updates when NPCs perform actions, which doesn't seem too catastrophic.

**Comment by Petethegoat** [comment]
Removing WIP tag, as I think this is acceptable to merge, although I'd still like a second pair of eyes on the item.cpp calls.

**Comment by kevingranade** [comment]
Everything looks good except how item::use_amount(), item::fill_with() and item::use_charges() unconditionally invokes (eventually) reset encumbrance on the player.  This is not just a perf problem, it's incorrect, because when a NPC inventory triggers it, the NPC encumbrance isn't updated.

What I *think* will be an acceptable solution here is to have those instead set a flag on themselves saying "I've been modified", and then have all characters check their inventory for items with that flag once a tick and conditionally call reset_encumbrance() if a modified item is found.

**Comment by Petethegoat** [comment]
Do you think that's preferable to passing a `Character` all the way down the call chain? I'm sure it'd be more work, but I suspect this might not be the first thing that would like to know what character is operating an item.

**Comment by kevingranade** [comment]
Where I'm coming from with that is that it is appropriate for an item to flag itself as being modified and it is appropriate for the player to check for the presence of that flag but it's a pretty bad layering violation to pass the character all the way down into these functions in order for the item to turn around and tell the player to do something.

**Comment by Petethegoat** [comment]
Makes sense. I'll try the flag thing soon.

**Comment by jbytheway** [comment]
It would be great to have tests for these sorts of corner cases.  They are the sort of thing that is likely to trip us up again in the future.

**Comment by Petethegoat** [comment]
Cool new version. Did what Kevin suggested.

Right now if you try to siphon from a vehicle to fill up a worn waterskin, you'll notice that checking encumbrance immediately afterwards will be slightly wrong until you move or wait a turn- the flags are being set too late or we're checking them too early or something.

Still needs work, but nearly there.

**Comment by Petethegoat** [comment]
This can be merged. There are remaining problems with encumbrance updates, but they aren't caused by this PR, just not yet fixed.

I'm pretty sure they'll need a deep dive into code I'm unfamiliar with, so I'll try to document and address them separately.

**Pull request merged**
