### PR TITLE
fix clang tidy error in condition.cpp

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix clang tidy, and make the field work as it should work
#### Describe the solution
If not terrain, then search furniture

### CODE REVIEW

**Comment by GuardianDll** [comment]
Ok clang do not like this solution, i'll check what's going on later, unless someone knows what's the problem

**Comment by PatrikLundell** [comment]
I'd expect you'd need to change the right side to a furn_id if you change the left side to one.

**Comment by GuardianDll** [comment]
i copied the code from `conditional_t::func f_map_ter_furn_with_flag`, and it has it like this also
https://github.com/CleverRaven/Cataclysm-DDA/blob/7e6bc3f569e7802682876efd9a183cf47edc7e5a/src/condition.cpp#L1584-L1588

**Comment by PatrikLundell** [comment]
Well, in the source you copied both ter and furn happen to have flag operations returning the same type. The code you tried to correct, however, has a left and a right side of the ter_id type, and you changed only the left one.
I'd expect the string mess on the right side to be either a terrain string or a furniture string, with the first branch trying to convert it to a ter_id, while the second one ought to have tried to convert it to furn_id.
This compiles locally for me:
`return get_map().furn( loc ) == furn_id( furn_type.evaluate( d ) );`

**Comment by GuardianDll** [comment]
compiled, tested, seems to work

**Pull request merged**
