### PR TITLE
[WiP][CR]City blocks

### PR DESCRIPTION
**Pull request by Coolthulhu**
Implements (a necessary part of) #21488 

Currently lacks a proper building selector system, but builds city blocks and fills them out with buildings of proper sizes. Understands only square sizes for now, but doesn't leave empty spaces in blocks (does leave some between them).

I moved some of the city building code from `overmap.cpp` to new files `overmap_gen.h/cpp`, which define a new class that does some of the building. At the moment it is a `friend` of `overmap`, but I think I'll be able to unfriend it. No need to have city building code see all the guts, it could do just fine with a bunch of publics.

Currently includes #21527 which is also WiP. This one currently doesn't depend on that PR, but the building selector (probably a separate PR after this one, this is fat enough) will use a common system with the multi-story building one.

I need comments on how to best clean this up. The code quality should be tolerable, but I'll need to:
* Hide the new behavior until it is ready. This means I need to disable the new functionality here, except for those who flip some switch. Option? Mod?
* Comment this mess. After working on it for few hours I don't even know what needs commenting the most, so it would be helpful if someone could point out what is the most confusing. `city_building_line` is sanity damage tier eldritch, so I'm not sure if comments will be enough.

Here's a screenshot.
The 'A's are 2x2 buildings (apartments). 'M's are 3x3 buildings (mansions). The small houses nested in those are to show where is the origin (point `(0,0,0)`) of the building and in which direction is it pointing.
nu-city spammy

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Is it intended that shops are placed in tiles already occupied by apartment blocks?

**Comment by ZhilkinSerg** [comment]
Also I'm getting only straight 4x4 block cities. Should I change some world settings?

default

default

default

default

**Comment by Coolthulhu** [comment]
> Is it intended that shops are placed in tiles already occupied by apartment blocks?

No, it's one of the bugs to fix.
For some reason the existing overmapgen code allows overwriting.

**Comment by Coolthulhu** [comment]
> Also I'm getting only straight 4x4 block cities. Should I change some world settings?

Currently it's not very well tweaked. Block size is `city_size^2 - distance_to_center^2`, meaning that for any city size smaller than 8 or so, it is likely not to create a lot.

**Comment by Coolthulhu** [comment]
> Considering how large and blocky these are, we might want to consider creating a "city" overmap type that features a single large city with this kind of layout at the core, and leave the existing overmaps as they are.

I was thinking about making those only happen above certain city size threshold, then guaranteeing more even city size spread on the overmap.
Overmap "biomes" could be a thing - they're half-implemented - but there is quite a bit of work to get it to actually create sane "over-overmaps" with guaranteed biome distribution (ie. at least one city per 3x3 overmap block or so).

**Comment by kevingranade** [comment]
You don't need rigidly "sane" overmap type distribution, you only need to be able to find one when you need it.  Until we have code that finds cities for missions, or points you to the nearest city, we don't even need that.

In the interim before we have an overovermap, we can simply roll dice when an overmap is generated to characterize it as a town or city or wildernesd.

My concern is the status quo works pretty well, and I'd like to avoid disrupting it for the sake of adding large cities.
At the same time, I don't want to constrain city layouts to fit in the existing system, they can easily take up an entire overmap, and in the case of very large cities, just the central business district or downtown area could fill an overmap.

**Comment by Coolthulhu** [comment]
> My concern is the status quo works pretty well, and I'd like to avoid disrupting it for the sake of adding large cities.

I'm writing it in such a way that it can be turned off by a switch.
Status quo works well for small cities, blocky cities would work better above certain threshold. The blocky algorithm also supports falling back to "worming" roads at the edges, meaning a big city can have suburbs that look similar to current version.

I'm trying to get it to workable first, even if it means turning it off and keeping it a debug option. Or a mod.

**Comment by kevingranade** [comment]
> I'm writing it in such a way that it can be turned off by a switch.

The issue isn't it being turned on and off, the issue is generating worlds that have both types of settlements.

**Comment by Night-Pryanik** [comment]
I hope this is closed only because of @Coolthulhu's absence?

**Comment by kevingranade** [comment]
Yep, if he's not here to push it forward, there's no reason to keep it open.  Anyone can feel free to pick up where he left off and complete the feature, including him if he reappears.

**Pull request closed without merging**
