### PR TITLE
Fix shotgun speedloader

### LINKED ISSUE #52595: Shotgun speedloader chute not work
### Describe the bug

Weapon addon and shotgun speedloader chute not work. Gun don't see not 6, nor 8. They just keeping used shells, menu not open

### Steps To Reproduce

Select Shotgun who support this addon
Unload gun
install speedloader chute
load chute (any type of 12 ammo)
Try to reload with chute

### Expected behavior

I expected it to work the same way as with revolver speedloader, but gun doesn't see these speedloaders

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a37d197 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Hair and Skin Color Cosmetics, UDP and MXotto+ version p10 [mxoudpcosmetics],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Mythical Martial Arts [MMA],
    Rummaging [Rummaging],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Graphical Overmap [Graphical_Overmap],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]

### Additional context

_No response_

### LINKED ISSUE #73018: Shotgun speedloader doesn't work
### Describe the bug

The current shotgun speedloader doesn't work, the purpose of a speedloader is supposed to be to be able to quickly load a weapon at once, but as it currently stands, the speedloader itself can be loaded at once, but the weapon can't be loaded at once using the speedloader.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Allows shotgun to be loaded at once by using a speedloader.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-04-04-0825 15b95a2 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by osuphobia**
#### Summary
Bugfixes "Fix shotgun speedloader and speedloader chute"
#### Purpose of change

Use pocket_mods instead of magazine_adaptor.
Modified relevant functions to prevent bugs from jumping out.
Close https://github.com/CleverRaven/Cataclysm-DDA/issues/52595
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/73018

#### Describe the solution

Gun/magazine needs to have allowed_speedloaders defined in pocket_data to use speedloader/speedloader_clip.
For shotguns, they don't have it defined, and are expected to get the ability by installing speedloader chute gunmod.
However, speedloader chute has magazine_adaptor defined, but it doesn't change anything for guns with pocket_type MAGAZINE.
Instead, we need to use pocket_mods to alters the original pockets of the weapon.
~~Since that pocket_data is overwritten, to prevent changing the amount of ammo a shotgun can contain, chute needs to be manually adjusted before attaching now.~~
Certain shotgun needs specific chute, and the old ordinary chute needs to be obsoleted afterwards. For now, the old chute needs to be manually adjusted before attaching.

Also fixed functions checking if we can attach or remove certain gunmod.
Now we can get rid of `Oops!  deleted some items when updating pockets that were added via toolmods` debug message.
Instead, you are suggested to unload your magazine in these situations.

#### Describe alternatives you've considered

Not to use speedloader chute, but directly add allowed_speedloaders to pocket_data of shotguns.

#### Testing

Compiled and tested locally.

#### Additional context

Checks also work for conversion kit now, so https://github.com/CleverRaven/Cataclysm-DDA/issues/71754 may also be solved. @AnotherSeawhite Could you please test it?

### CODE REVIEW

**Comment by Hyperseeker** [comment]
For what it's worth, the chute in question (specifically, [this model by Arredondo](https://www.arredondoaccessories.com/product/speed-loader-assist/), hence the item ID) does not come for all the models listed. Each of these chutes should be a separate item, because each chute mounts to a specific location on the frame of the shotgun (see link above for the photos of chutes as applied to different models of shotguns). They can't be "tuned", and I imagine it would take a decent idea about shotgun construction and welding to re-fashion a chute from one model to another.

Also, I'm not positive on this, but you might wanna research how speedloaders fit with different tube sizes. I *think* it might be okay to reload e.g. a 4-shell tube with a 6-shell speedloader? But I'm not sure.

I do like the change for which slots require unloading the gun before modding. That's a positive change in itself.

**Comment by osuphobia** [comment]
> For what it's worth, the chute in question (specifically, [this model by Arredondo](https://www.arredondoaccessories.com/product/speed-loader-assist/), hence the item ID) does not come for all the models listed. Each of these chutes should be a separate item, because each chute mounts to a specific location on the frame of the shotgun (see link above for the photos of chutes as applied to different models of shotguns). They can't be "tuned", and I imagine it would take a decent idea about shotgun construction and welding to re-fashion a chute from one model to another.
> 
> Also, I'm not positive on this, but you might wanna research how speedloaders fit with different tube sizes. I _think_ it might be okay to reload e.g. a 4-shell tube with a 6-shell speedloader? But I'm not sure.
> 
> I do like the change for which slots require unloading the gun before modding. That's a positive change in itself.

@Hyperseeker 
Thank you for your link and advise.
Currently, there are only 4 models in dda that have loading port location, the Benelli SBE 3 shotgun(4 rounds), the Remington 870 MCS shotgun(4 rounds), the Mossberg 930 SPX shotgun(8 rounds), and the Mossberg 590A1 shotgun(9 rounds). I just added 3 types of chute simply to prevent ammo_restriction being changed, but according to infomation above, I should add four different chute for these four shotguns.
The old ordinary chute needs to be obsoleted then, but I'm not sure how to do it, so just leave it to other people.

The two shotgun speedloaders in dda are SPEEDLOADER_CLIP.
`This item can quickly reload rounds into gun or magazine that don't have enough space.`
As the FLAG info listed, the target gun or magazine don't have to be emptied, SPEEDLOADER_CLIP will reload as many rounds as the gun/magazine can hold, and unfilled ammo still remains in the speedloader. I didn't change the way it works.

**Comment by Hyperseeker** [comment]
> The old ordinary chute needs to be obsoleted then, but I'm not sure how to do it, so just leave it to other people.

You could simply re-implement the existing one into one of the specific ones: e.g. into one for the 9-shell shotguns, or one for 8-shell ones etc.. On existing saves, this may or may not retain the reworked chute even if it doesn't fit the model of the shotgun. (One of the specops professions used to spawn with an MP5 which had a holo sight attached to it, despite not having the `sights` slot or the sight mount. The game would simply spawn the SMG with the holo sight attached regardless. I suspect something similar may happen here.)

Alternatively, of course, you could make a new item and [migrate it](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/OBSOLETION_AND_MIGRATION.md) like you would any other item.

> The two shotgun speedloaders in dda are SPEEDLOADER_CLIP.

I was referencing the real-life possibility of reloading when I mentioned those. I'm not sure how shotgun speedloaders even work, much less handle shorter-than-self tubes to reload into.

**Comment by osuphobia** [comment]
@Hyperseeker 
So I can only migrate one item to another? Fine, consider doing it later, not in this PR.

> I was referencing the real-life possibility of reloading when I mentioned those. I'm not sure how shotgun speedloaders even work, much less handle shorter-than-self tubes to reload into.

https://www.youtube.com/watch?v=M3Hs4do69ms
I'm not a pro, but the way it works in dda seems not that much unrealistic.

**Comment by AnotherSeawhite** [comment]
Oml, GitHub didn't even notify me for the mention. I'll test it soon.

**Pull request merged**
