### PR TITLE
Z-levels items update

### PR DESCRIPTION
**Pull request by Coolthulhu**
EDIT: Tested on my side, ready for official testing.

A lot of functions updated for 3d - currently mostly just overloads that do the same stuff, but take tripoints.
Item stacks, item processing (including active), item spawning, artifacts, functions invoked on actualization (funnels, fruits, rotten item removal), minor map functions (`hit_with_acid/fire`, spawn artifact), crafting (item access, building of inventory).

Almost entire `map.h` has 3D variants now.

Is removal of 2D overloads a part of #6818 or can it be done when it would actually be useful?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Tests I performed (listing for easier verification):
- [x] Active items on the ground
- [x] Active item saving and restoring (with z-level movement, saving/loading the game)
- [x] Active items in vehicles
- [x] Crafting, crafting with fire and crafting with furniture
- [x] Fields interacting with items (items exploding in fire, containers dropping contents)
- [x] Plants growing
- [ ] Funnels filling retroactively
- [ ] Hit with fire/acid
- [ ] Mop up guts
- [ ] Find an artifact created by mapgen
- [ ] Restock fruit

**Comment by KA101** [comment]
For my part (I am not Kevin), successfully removing the 2D-compatibility overloads is the final proof that the conversion works and is implemented throughout the game.  It may not be *necessary* to demonstrably add 3D support, but I think it would certainly be *sufficient*.

**Comment by Coolthulhu** [comment]
Yeah, but removing the overloads would be quite a bit of work, while being almost completely menial. At the same time it would add no visible results, possibly cause a lot of conflicts (depending on the speed of merging), require quite a bit of redundant work (many parts will have to be rewritten in later parts of z-level update anyway) and greatly shift the amount of work towards the part 1.

I've already done more work on the part 1 than I expect to do on the sum of any 3 other parts. At least unless part 2 necessitates writing something like k-d tree range search.

If necessary I'll do it, but I'd rather avoid it.

**Comment by KA101** [comment]
Hence why I didn't think it *mandatory*, but was willing to accept the removal as sufficient proof that the bounty had been fulfilled.  Other proofs may be possible.  And I'm not the final decision on that, anyway.

**Comment by Coolthulhu** [comment]
OK, tested this one on my side. Fixed the bugs I discovered. Should be ready to be queued for official testing.

While testing this PR, I noticed the following bugs/oddities:
* Funnels don't work retroactively in master (fixed here). Inverted operator in weather.cpp
* `int(0.0/0.0)` operation in weather.cpp. Technically correct, but casting NaN created by zero division to int sounds like the epitome of ugliness. Added an `if > 0`.
* `accessible_items` (in crafting) function actually returns if the items are not accessible. Not a bug, but I inverted it (also where used, so that it still works correctly) for readability.
* `sees` function seems to always return false when the target tile is not transparent. As a result no message is printed when spitter's spit hits a wall.

**Pull request merged**
