### PR TITLE
make searchlights passive entities

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Balance "make searchlights passive entities"

#### Purpose of change
It doesn't make a lot of sense to me that zombies attack searchlights but not other machines and lights. Also I think in general turrets and lights are paired to defend places since zombies will just aggro the light and either destroy it or stack making locations with lights and zombies, very easy.

#### Describe the solution
Make a new faction called passive_machine this is for things coded as monsters but which aren't at all dangerous and wouldn't draw the ire of most creatures. 

Added the spotlight to that.

I've for now left bugs as aggro-able on spotlights since it makes a bit of sense for bugs to swarm them. 

#### Describe alternatives you've considered
Move most searchlights out of the reach of enemies (up on towers for example)

#### Testing
spawn a mil light and some brutes, they wont attack it

#### Additional context
image

### CODE REVIEW

**Comment by BrettDong** [comment]
Monster faction test also needs to be updated.

**Comment by Night-Pryanik** [comment]
Hey, just wanted to make the same thing today! Good job!

**Comment by Ilurker** [comment]
This is a very good change. On top of the other highlighted oddness, I often found that approaching helipads and checkpoints at night would be unusually easy because all the zeds would be bunched up trying to push past barbed wire fencing instead of paying attention to me plinking away at them from the middle of the spotlight. This should make searchlights a serious obstacle since getting revealed will mean you actually receive aggro.

**Comment by bombasticSlacks** [comment]
Yeah this makes FEMA camps an absolute nightmare to clear now

**Comment by Inglonias** [comment]
This is cool and good.

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
