### PR TITLE
Make ground mounted solar panels more efficient

### LINKED ISSUE #68526: Solar Panel energy production is much worse then real-world production
### Describe the bug

The normal solar panels in-game produce 50W: https://cdda-guide.nornagon.net/vehicle_part/solar_panel

This is absolutely pathetic compared to a normal 1m2 consumer panel that many of us use today. It's quite common these days for people to have 5kW solar setups, or even larger. To get 5kw in-game would require 100 of these panels, and covering the entire roof (after looting an entire city worth of panels).  

A more realistic value for this size of panel should be a value from 250W-500W. 

Advanced panels should be adjusted in similar fashion. 

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Solar panels in game should produce similar output to average real photovoltaic panel of similar size.

### Screenshots

_No response_

### Versions and configuration

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ehughsbaird**
#### Summary
Balance "Improve efficiency of non-vehicle solar panels"

#### Purpose of change
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/68526

It seems that vehicle tiles are smaller than the ~1mx1m size that tiles otherwise are
https://github.com/CleverRaven/Cataclysm-DDA/blob/11a2c1e60597c4cd396b13b9c53eaf2c553089a7/src/vehicle.cpp#L4014-L4023
Because solar panel production values are oriented around vehicles, this makes appliance solar panels less efficient than they should be.

#### Describe the solution
Add larger solar panels for use as appliances, constituted of 4 of the smaller vehicle-mounted solar panels.

#### Describe alternatives you've considered
Also add the reinforced versions, but I don't really see much point in reinforcing static solar panels.

#### Testing
Spawn in

- 5x Solar Panel
- 1x Solar Panel Array
- 40x Copper Wire
- 5x Advanced Solar Panel
- 1x Advanced Solar Panel Array

Solar panels and small solar panels can be mounted
image
Solar panel arrays can be disassembled into smaller solar panels
image
And crafted from smaller panels
image
Generation of smaller versions
image image
Is 1/4 that of larger versions
image image

#### Additional context
There seems to have been a lot of discussion on this. This change seems in line with the discussion on the linked issue.

### CODE REVIEW

**Comment by Nebnis** [comment]
I assume the solar farms would have the bigger versions too?

**Comment by ehughsbaird** [comment]
This PR modifies `f_solar_unit`, yes.
https://github.com/CleverRaven/Cataclysm-DDA/blob/11a2c1e60597c4cd396b13b9c53eaf2c553089a7/data/json/mapgen/solar_farm.json#L46

**Comment by Alm999** [comment]
Nice! (Kevin will probably furious)

But there seem to be a naming mismatch:
solar panel (item) -> "small solar panel" (appliance)
solar panel array (item) -> "solar panel" (appliance)

Oh, and foldable solar panels were not changed, so they are still garbage (x0.68 output for no reason).

**Comment by ehughsbaird** [comment]
I don't love the naming, but didn't want to shake things up by changing a bunch of names. Maybe I should have.

I don't really know anything about folding solar panels - I don't see a reason to give them the treatment received here, because folding doesn't make sense for an appliance.

**Comment by Alm999** [comment]
No, folding solar panels obviously are not intended to be used as appliances.
But with things in their current state they are pretty useless because:
1) they can not be used as-is and must be installed into a foldable frame (why use them when you can just place basic panel as appliance?):
2) they have even more weight than an ordinary panel, are made from ordinary solar panels (that can be reclaimed upon disassembly) and have the same area, but! for some reason produce only 2/3 of an ordinary solar panel's power.

Overall, foldable solar panels are garbage without their applications. Slightly less so now, that the weight was adlusted to reasonable values (meager 36W maximum at noon in summer with "sunny" weather for 14.5kg was just ridiculous).

**Comment by ehughsbaird** [comment]
Oh, they can be crafted? I thought they were an entirely different type of panel, not just a normal modified to fold. I might give a look at them.

**Comment by Alm999** [comment]
Fun fact: they can *only* be crafted. I doubt they spawn naturally anywhere. Yet, when I tried to fix them in https://github.com/CleverRaven/Cataclysm-DDA/pull/66478, I was given an explanation for the state of things as "Quick google shows collapsible panels average efficiency of 7%-15%. Non foldable 15-22%."

Apparently, [Maleclypse](https://github.com/Maleclypse) compared large industrial rooftop solar panels to some pocket-sized foldable "smartphone-charger" gadgets (and even then, my google-fu could not fetch me anything with performance below 20%), which is clearly not the way foldable solar panels are made in-game.

**Comment by Maleclypse** [comment]
> Fun fact: they can _only_ be crafted. I doubt they spawn naturally anywhere. Yet, when I tried to fix them in #66478, I was given an explanation for the state of things as "Quick google shows collapsible panels average efficiency of 7%-15%. Non foldable 15-22%."
> 
> Apparently, [Maleclypse](https://github.com/Maleclypse) compared large industrial rooftop solar panels to some pocket-sized foldable "smartphone-charger" gadgets (and even then, my google-fu could not fetch me anything with performance below 20%), which is clearly not the way foldable solar panels are made in-game.

Are you pinging me because you want me to google for you since again my google search for "efficiency of foldable solar panels" still pulled multiple references to below 20% on the first page or are you wanting me to comment that foldable solar panels probably shouldn't be craftable and should be salvage only?

**Comment by Alm999** [comment]
@Maleclypse
I've pulled you because:
1) our previous conversation is not over, as I indeed requested sources you've used but you never replied (I have provided mine);
2) I feel present conversation is relevant and since you've participated in the our previous re-balance attempt, I thought you would be interested;
3) I don't want to  make an impression that I'm blackmailing you and trying to push my vision behind your back.

So yes, I'm still interested in your sources and explanation why exactly the same solar panel, after being installed into a foldable frame (and **gaining** weight in the process) can lose one third of its power output.

I shall remind that in-game "foldable" solar panels are not pocket-sized gadgets from AliExpress, but ordinary solar panels disassembled by (player's) hand and put into frame, so one can not justify sudden loss of efficiency by "inferior cells" and power loss in additional wiring can not be that high.

**Comment by ehughsbaird** [comment]
I think this discussion would probably go better in a different place.

**Comment by Alm999** [comment]
Done https://github.com/CleverRaven/Cataclysm-DDA/issues/68642

**Pull request merged**
