### PR TITLE
Updates to More Survival Tools

### PR DESCRIPTION
**Pull request by DangerNoodle**
Maintenance of More Survival Tools, as originally implemented in https://github.com/CleverRaven/Cataclysm-DDA/pull/19328.

Wooden and iron javelins now use 'copy-from' to change their base items into ammuniton, instead of a full override.

Copper javelins are also made non-conductive. Perhaps I should additionally alter them to copy from related items?

Obsolete comments in the curdling milk items have been removed.

Other ideas might be to update the flint and steel to require forging, and add wanderer to other scenarios that permit the naturalist profession (which it seems to be derived from). I had also wondered about whether implementing a Skåne-style lockbow might suit the profession better, being makeshift. Thoughts on those idea would be appreciated.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Apologies for that, it seems I slipped up when removing the comments.

**Comment by mugling** [comment]
> Wooden and iron javelins now use 'copy-from' to change their base items into ammuniton, instead of a full override.

This should have an inline comment explaining you are changing the item `type`. Whilst this support is intentionally included it has been the source of previous bugs so you should make your intentions clear here

**Comment by DangerNoodle** [comment]
Very well then. Should I also look into setting stone and copper javelins to copy from wood and iron javelins, respectively? This would reduce repeats of anomalies such as copper javelins needing to be set as non-conductive.

**Comment by DangerNoodle** [comment]
One thing I discovered. If copper javelins are left in their original placement (before the definition for iron javelins), they copy from the mainline iron javelins instead of the version in the mod. This causes load errors as they will have ammunition properties but no ammo type, or out-of-range values from their (nonexistent) ranged damage and pierce being reduced.

There are two solutions. Adding the required ammo-specific information ensures they act as ammo and have the required properties no matter what they copy from. Additionally, placing them after the iron javelin makes them derive properties from the version modified by the mod. I used both methods as I do not trust the latter option as foolproof.

**Pull request merged**
