### PR TITLE
Forest trails

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary
SUMMARY: Content "Add forest trails."

#### Purpose of change

This introduces a new overmap connection type, `forest_trail`, and updates overmap and map generation to create these new forest trails as routes through forests. When city size is greater than 0, there is also a chance of trailheads being created at the ends of some trails.

There is a now a corresponding `forest_trail_settings` section in the region_settings which drives the forest trail generation, allowing modification of these settings in json via `region_settings` or `region_overlay` entries. Consequently, mods can trivially adjust these values.

#### Describe the solution

* See [the new documentation](https://github.com/ralreegorganon/Cataclysm-DDA/blob/forest-trails/doc/REGION_SETTINGS.md#forest-trail-settings) for a description of the forest trail settings.

* See [the new section](https://github.com/ralreegorganon/Cataclysm-DDA/blob/forest-trails/data/json/regional_map_settings.json#L421) in the regional map settings for the new json.

At a high level, during overmap generation the forests are flood-filled to find the contiguous forests, and then each forest that qualifies for a trail has a subset of points picked as trail points. These points are then connected using overmap connections with the new `forest_trail` connection. Finally, trailheads are added to some trail endpoints.

#### Additional context

**a trail with trailheads on the overmap**

The trails are denoted by the green lines, and the trailheads are brown Ts.

trails-trailhead-highlight

**on a trail**

The composition and variance in shape of the trail is driven through json. By default, you have dirt trails in the forest which are somewhat ragged, while maintaining a thin path through.

trails-dirt-2

But it's entirely possible in a `region_overlay` to turn them into straighter wider gravel paths for your bike.

trails-alt-config-gravel

**trailhead variations**

There are several variations of trailhead, and new ones can be added into the mix by simply defining new mapgen entries for the `trailhead` overmap terrain and ensuring the entrance to the trail is on the south end of the map when defined in json. They have weights defined to adjust the rarity, as some are more useful than others. 

trailhead-2

trailhead-1

trailhead-3

**in motion**

Trails are a little hard to convey with static images, so I tossed a quick animated gif of running along a trail onto imgur, which you can [view here](https://imgur.com/a/1AtdRme). 

**trail frequency in the overmap**

The likelihood of trails occurring is driven by the combination of the forest trail settings, the forest settings, and city size / spacing. Because the trails have a minimum forest size before the forest is even considered, and the roll is made for each contiguous forest, you can have scenarios where a huge metro with city size 16 / spacing 0 leaves nothing but small forests that don't qualify, while on the other hand it's possible with city size 0 to have a huge contiguous forest that either fails the roll and has no trails at all, or succeeds the roll and has a big trail system. I think the variety here is pretty interesting and configurable via the json settings in mods or changes to the base game, but I've focused on tuning it primarily for the default settings. Here's an example of the result.

trails-overview-2

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Looks really great in game. My only concern it is possible that too many terrains with line-drawing symbols can be displayed at once now (especially after I finally add railroads). We should probably add more map display modes later, so display of forest trails could be switched off and changed to green F (used for forests).

image

**Comment by Achie72** [comment]
I agree with ZhilkinSerg, with another tile using the line system the map look busy and confusing. Can't wait to try this though, looks really cool, forest were way to "plain" before imo.  
Is it possible to make this trails connect to camps if they are nearby?

**Comment by ralreegorganon** [comment]
> We should probably add more map display modes later, so display of forest trails could be switched off and changed to green F (used for forests).

Seems like a reasonable follow up.

**Comment by ralreegorganon** [comment]
> Is it possible to make this trails connect to camps if they are nearby?

Depends on what you mean. You can specify forest trails as a type of connection for overmap specials, and the game will attempt to make that connection (there are some oddities around assumptions the game makes with respect to connections that need follow up work though). The forest trails are also just considered forest terrain for the purposes of placing most overmap specials, so the game will gladly stamp the specials over or next to trails, which can give a convincing illusion of deliberate connectivity (e.g. I've run into a desolate barn or a campsite placed on the trail and it flows pretty well).

**Pull request merged**
