### PR TITLE
Add survival kit

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary

 ```SUMMARY: Content "Add survival kit```

#### Purpose of change

Variety. The survival kit works similar to a first aid kit.

#### Describe the solution

Weight 1612 mg, the weight of the items.
Volume: 1 L, a bit less than the items contained as survival kits are usually packed to minimize volume.
Contents:
* folding knife
* flint and steel
* whistle multitool
* foldable plastic bottle
* glowstick
* 15 water purification tablets
* ~~flare gun + 8 signal flares~~ 4 hand flares
* ~~survivor's map~~
* pocket survival guide (new!)
* survival kit box (1 L)

Added to item groups:
* camping 
* traveler 
* mil_surplus 
* shelter 
* mil_accessories 
* helicopter 
* car_kit 
* survivorzed_extra 
* college_camping 
* dollar_tools

---

EDIT: Survivor zombie now also has a small chance of dropping a damaged survivor kit.
EDIT2: Implemented suggestions by @Maddremor.
EDIT3: Implemented suggestion by @Petethegoat.
EDIT4: Implemented suggestion by @ZhilkinSerg.

#### Describe alternatives you've considered

I've debated which items it should contain a lot, but I wanted to make it as light as possible. 

#### Additional context

image

### CODE REVIEW

**Comment by Maddremor** [comment]
Is it supposed to be a homemade kit or an of the shelf thing? The survivor's map is hand annotated, which is less fitting for a commercial product.

**Comment by ampersand55** [comment]
I kind of imagined that it could be either or, but I suppose it wouldn't make sense to have something with an annotated map found in a military surplus store.

> What kind of packaging does it come in? Anything usable for storing liquids, or even as tinder?

I suppose a container with boiling quality would make sense.

I'll incorporate these changes tomorrow and I'll mark this as a WIP/CR for now.

**Comment by Firestorm01X2** [comment]
Can I have small suggestion. I mean I am not hardcore survivalist or survavalist at all. But I know for sure that using mathces are much easier than:
>flint and steel

Maybe it is better to add some matches?

**Comment by Petethegoat** [comment]
I would consider replacing the flaregun. I think one or two of those wire survival saws would be perfect, along with maybe a few other small goodies instead.

**Comment by ampersand55** [comment]
I'm not sure about the flare gun myself, I went off and on with the handflare and the flare gun several times.

I really like the flare gun, but considering its price it might be a mismatch with the other items.

**Comment by ZhilkinSerg** [comment]
Shouldn't it have some booklet inside too?

**Comment by ampersand55** [comment]
> 
> 
> Shouldn't it have some booklet inside too?

Good idea, added a "Pocket Survival Guide". 

Or should I create a custom booklet like with first aid kit?

**Pull request merged**
