### PR TITLE
JSON: store distance value into a specified variable

### PR DESCRIPTION
**Pull request by rtxyd**
#### Summary
Features "JSON: store distance value into a specified variable"

#### Purpose of change

Store distance of two points into a specified variable which is declared in JSON file.

When I write JSON file, and refer to EFFECT_ON_CONDITION.md
I need to calculate the distance of two points and store it into a variable declared in JSON. And then use the variable to invoke "math" key.
But it seems there is no such function that I can store the distance to a variable, 
so I look into how JSON works and then figure it out with this solution.

#### Describe the solution

what I test to write in JSON is 
```json
...
...
"effect":[
      {"get_distance_value": [{"u_val": "point01"}, {"u_val": "point02"}, {"global_val": "distance_01"}]}
]
...
...
```
So what I need is read the array, get index 0, index 1, and then index 2.
I use two functions that in previouse commit, get_tripoint_from_string, get_string_from_input, and get_varinfo_from_string (this is a variant from get_tripoint_from_string).
get_string_from_input: it can read object with index in the array return a string value,
get_tripoint_from_string: it can turn string-fied tripoint value into tripoint_abs_ms type
get_varinfo_from_string: it returns a var_info type data and stores a correct name.
read string info of the array, then get first value, second value, third value
transform first and second value to tripoint_abs_ms type, third value to var_info type,
then invoke rl_dist, give point01,  point02, get the distance, and
then invoke write_var_value to store the distance value into the third variable.

#### Describe alternatives you've considered

maybe we can use different method to implement it, and write this feature into another cpp file.

#### Testing
waite a minute

#### Additional context
I am noob, and just starting learning. So this may be full of loopholes. 
If I did something wrong, I'd like your guidance.

### CODE REVIEW

**Comment by andrei8l** [comment]
```JSON
      {"get_distance_value": [{"u_val": "point01"}, {"u_val": "point02"}, {"global_val": "distance_01"}]}
```

This is the same as

```JSON
 { "math": [ "distance_01", "=", "distance( u_point01, u_point02 )" ] }
```

**Comment by rtxyd** [comment]
> ```json
>       {"get_distance_value": [{"u_val": "point01"}, {"u_val": "point02"}, {"global_val": "distance_01"}]}
> ```
> 
> This is the same as
> 
> ```json
>  { "math": [ "distance_01", "=", "distance( u_point01, u_point02 )" ] }
> ```
em, well, I didn't find that. That's my fault

**Comment by rtxyd** [comment]
but this use-case isn't in EFFECT_ON_CONDITION.md. 😐 Though I need to close this since.

**Comment by andrei8l** [comment]
`math` documentation is kinda hidden away in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#dialogue-functions and the functions don't even have TOC links. I am going to move it and try to reorganize it a bit once all traces of arithmetic are gone.

**Comment by rtxyd** [comment]
@andrei8l 
```json
  {
    "type": "effect_on_condition",
    "id": "EOC_set_spawnpoint",
    "eoc_type": "EVENT",
    "required_event": "game_begin"
    "effect": [
      {
        "u_message": "Spawnpoint set!"
      },
      { "u_location_variable": { "u_val": "spawnpoint", "type": "eoc_basic_loc", "context": "eoc_key" }}
      { "run_eocs": ["EOC_set_point_01"]}
    ]
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_set_point_01",
    "recurrence": "1 minute",
    "effect": [
      {"u_location_variable": { "u_val": "i_am_here", "type": "eoc_basic_loc", "context": "eoc_key" }},
      {"math": ["distance_01", "=", "distance(u_i_am_here ,u_spawnpoint)" ]},
      {
        "u_message": "<global_val:distance_02> show!"
      }
    ]
  }
```
test with this, shows
DEBUG    : Could not convert string '' to tripoint

 FUNCTION : from_string
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\point.cpp
 LINE     : 73
 VERSION  : 6a37479

I'd like to try to figure this out.

**Comment by andrei8l** [comment]
type and context factor into the variable name. That should be
```JSON
  {
    "type": "effect_on_condition",
    "id": "EOC_set_spawnpoint",
    "eoc_type": "EVENT",
    "required_event": "game_begin",
    "effect": [
      { "u_message": "Spawnpoint set!" },
      { "u_location_variable": { "u_val": "spawnpoint", "type": "eoc_basic_loc", "context": "eoc_key" } },
      { "run_eocs": [ "EOC_set_point_01" ] }
    ]
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_set_point_01",
    "recurrence": "1 minute",
    "effect": [
      { "u_location_variable": { "u_val": "i_am_here", "type": "eoc_basic_loc", "context": "eoc_key" } },
      {
        "math": [ "distance_01", "=", "distance(u_eoc_basic_loc_eoc_key_spawnpoint, u_eoc_basic_loc_eoc_key_i_am_here)" ]
      },
      { "u_message": "<global_val:distance_01> show!" }
    ]
  },
```
but you're better off not using "type" and "context". Let's move dev support to discord though.

**Pull request closed without merging**
