### PR TITLE
Additional samples and harvests

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Content "more samples and harvests for mutagen recipes"

#### Purpose of change
Continue working on mutagen manufacture overhaul.

#### Describe the solution
Adds additional samples and harvests and spawn points.

#### Describe alternatives you've considered
none

#### Testing
TBD

### CODE REVIEW

**Comment by Maleclypse** [comment]
I need additional ideas for the beast sample harvests.  Moose? Or should moose be Bovine?   I'm kinda looking at beast as a sort of Trolloc analog from Wheel of Time.  Should chimera require samples from multiple of the existing types?
@Venera3 your thoughts are always appreciated.

**Comment by Zireael07** [comment]
Moose giving Bovine samples sounds fine to me (a quick google tells me male moose are attracted to cows and hybrids did happen)

**Comment by Photoloss** [comment]
> Chimera expecting two (three?) samples

Three, for the mythological reference. Feline, cattle and lizard being the closest approximation.

**Comment by Terrorforge** [comment]
Does there actually need to be a specific "beast sample"? That sounds a bit weird to me. Wouldn't it make more sense if you could craft it using any of the predatory mammal samples? Or else do it the way you've discussed doing chimera, e.g. lupine + feline + ursine sample = four doses of Beast mutagen, or something along those lines.

**Comment by Maleclypse** [comment]
> Does there actually need to be a specific "beast sample"? That sounds a bit weird to me. Wouldn't it make more sense if you could craft it using any of the predatory mammal samples? Or else do it the way you've discussed doing chimera, e.g. lupine + feline + ursine sample = four doses of Beast mutagen, or something along those lines.

Huh, I've been basing beast as generic omnivore line because it has animal empath and other herbivore traits in it.  In fact Beast has doesn't start having carnivore traits until it goes post thresh.  But based on the mutations it currently has I definitely won't be giving it predator stuff. It probably needs new post thresh mutations for it. But that's outside the scope of this PR.

**Comment by Terrorforge** [comment]
See the thing about that is, because of the way prerequisite mutations work, having Culler etc. as post-thresh mutations means Beast can (and will) get Carnivore as pre-threshold mutation. In fact, if I understand the mechanics correctly, it means east is about five times more likely to develop Carnivore than most of the pre-threshold mutations that are actually in the category. Which is an inconsistency you see between lines; some have prerequisites like that explicitly included, some don't.

This mechanic also causes some pretty serious bugs as I've detailed in #52942. E.g. it causes Ursine to pretty much always develop Carnivore as well, and that's very explicitly supposed to be omnivorous, to the point it has a special exception for the Culler line.

Personally I always assumed Beast was the generic predator line, but it is a bit of a mess. It doesn't have any meaningful natural weapons, for one thing. Also it has both Animal Empathy _and_ Animal Discord.

**Comment by AdamChirnside** [comment]
Shouldn't human samples appear alongside the other mutagen samples in Labs/TCL etc.?

**Comment by Maleclypse** [comment]
> See the thing about that is, because of the way prerequisite mutations work, having Culler etc. as post-thresh mutations means Beast can (and will) get Carnivore as a pre-threshold mutation. In fact, if I understand the mechanics correctly, it means Beast is about five times more likely to develop Carnivore than most of the pre-threshold mutations that are actually in the category. Which is an inconsistency you see between lines; some have prerequisites like that explicitly included, some don't.
> 
> This mechanic also causes some pretty serious bugs as I've detailed in #52942. E.g. it causes Ursine to pretty much always develop Carnivore as well, and that's very explicitly supposed to be omnivorous, to the point it has a special exception for the Culler line.
> 
> Personally I always assumed Beast was the generic predator line, but it is a bit of a mess. It doesn't have any meaningful natural weapons, for one thing. Also it has both Animal Empathy _and_ Animal Discord.

Someone could go in and do what I did with the mi-go line in Aftershock and make special post thresh mutations for Ursine that prevent it from being in the carnivorous pathway.

**Comment by Maleclypse** [comment]
> 

Good catch!

**Comment by Terrorforge** [comment]
> Someone could go in and do what I did with the mi-go line in Aftershock and make special post thresh mutations for Ursine that prevent it from being in the carnivorous pathway.

Might do that, but it's a recurring problem. In testing, I've actually become Freakishly Huge from taking Medical Serum because it has Resilient as a post-threshold mutation. I might spend some time cleaning that sort of thing up, but I have no idea how to fix the fundamental problem

Anyway that was more of an aside, my main point was that as it stands, Beast _does_ get Carnivore.

**Pull request merged**
