### PR TITLE
MSX Dead People tileset update and make it default.

### LINKED ISSUE #27111: Change default graphics from ChestHole to DeadPeople
**Is your feature request related to a problem? Please describe.**  
ChestHole is updated less frequently than DeadPeople and contains a number of missing tiles.

**Describe the solution you'd like**  
DeadPeople is a popular tileset that is frequently updated. It would be a good choice for default.

**Describe alternatives you've considered**  
Not changing the default, and getting someone to update ChestHole.

**Additional context**  
At some point soon it might be worthwhile to go through our included graphics sets and remove some of the less well maintained ones from the mainline.

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Interface "MSX Dead People tileset update and make it default."```

#### Purpose of change
Fixes #27111

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
>options tileset name fix

Yes. That is very important.

**Comment by OzoneH3** [comment]
Jenkins rebuild.

**Comment by SomeDeadGuy** [comment]
Wait, why are you changing options tileset name?
It is indication for you not using latest version of it!
LIVE_PEOPLE - old version packeged with main game
DEAD_PEOPLE - newest version from my github

Please change it back.

**Comment by SomeDeadGuy** [comment]
Oh, got it. Then it is fine!

**Pull request merged**
