### PR TITLE
Make boats deployable in deep water.

### PR DESCRIPTION
**Pull request by DanmakuDan**
By changing mapgen.cpp add_vehicle_to_map to check for a vehicle with floating parts, an inflatable boat can be activated/deployed over deep water. I'm not sure if there's any performance issues with changing it here. In most cases, a boat would be deployed partially in the shallow/deep water area. For  #13147.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, brilliant. o.o

**Comment by kevingranade** [comment]
gah, don't revert things in your branch, if we merge this along with #13189, this one will undo the other one.

**Comment by chaosvolt** [comment]
Ah, even when being fixed these bugs are causing shenanigans to ensue.

**Comment by kevingranade** [comment]
Cherry-picked the fix and avoided the duplicate commit and revert.

**Comment by chaosvolt** [comment]
Ah, and thank you.

**Comment by DanmakuDan** [comment]
Sorry about the revert, I wasn't sure what was going on, since I usually don't submit pull requests that close to each other.

**Pull request closed without merging**
