### PR TITLE
fix mics repair kit

### LINKED ISSUE #71090: Unable to reload Misc repair kit
### Describe the bug

When I attempt to reload the misc repair kit with a cardboard roll of duct tape the game says I have no items to reload.

### Attach save file

Any save should work but just in case use this one.     
[Duchesne.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13994496/Duchesne.zip)

### Steps to reproduce

1. Make a character with a misc repair kit and find a cardboard roll containing duct tape.  2. attempt to reload the repair kit using the duct tape in the cardboard roll

### Expected behavior

I expected I would be able to reload the misc repair kit using the duct tape in the cardboard roll

### Screenshots

_No response_

### Versions and configuration

- OS: Windows 11.  -Game Version: Experimental Build 2024-1-19-1608.  -Graphics Version: Tiles, Ultica, Larwick Overmap.  -Ingame Language: English.  -Mods Loaded: dda, slowdown fungal growth, disable npc needs, portal storms ignore npcs.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Bugfixes "mics repair kit works again"
#### Purpose of change
Fix #71090
Closes #72554
#### Describe the solution
Apply Renech solution, fix itemgroups problems that was caused by it
#### Testing
Compiled, found roll with duct tape, reloaded mics repair kit, repaired a broom
image

image

### CODE REVIEW

**Comment by mqrause** [comment]
Please make sure all the non-repair kit uses of duct tape (and other things coming in cardboard rolls) still work as expected.

**Comment by GuardianDll** [comment]
They do not
image
image
*fuck*

**Comment by KHeket** [comment]
Maybe remove the reloading mechanic from sewkits, mics repair kits and others and just make them use nearby resources like it makes when you craft
Because its unrealistic, that you can "reload" needle or mics repair kit. You can insert duct tape roll in the kit, and you cant insert thread into needs, and threads are also for now counted by pieces
The best way for me to implement it is:
1) Activate mics reapair kit/sewing kit/needle
2) Choose, which material you want to use. Duct tape/thread/sinew/heavy duty thread etc
3) You are repairing items with this kind of resource

This way will be also much more easier for the future items

**Comment by GuardianDll** [comment]
it is something desired, except we don't want the need of any kits or tools to open the menu, re:#64528
but it's tad bigger than eeh three lines of code

**Comment by GuardianDll** [comment]
@RenechCDDA do you happen to know a solution for this one, or i should close it?

**Comment by KHeket** [comment]
Check pls this two good ideas to make kits and needles work more player and contributor friendly, more realistic, and this ideas is much more easy to realize, than to fix this bug
#72899
#72774

**Comment by GuardianDll** [comment]
\> making brand new UI that hold and handle all repair stuff
\> easier than two lines of code and bunch of json copypaste
is it a better approach? sure. is it easier? hell no

**Comment by AnotherSeawhite** [comment]
I'm honestly not sure if there's an 'easy' fix for this bug.

**Comment by RenechCDDA** [comment]
> @RenechCDDA do you happen to know a solution for this one, or i should close it? Unless if having `container` field stripped from duct tape is desired, then i'll just remove code changes and rephrase a PR body

I don't have any recommendations for you right now

**Comment by GuardianDll** [comment]
closed in favor of #72751, unless removing container field from duct tape item definition is desired, then i'll reopen and scrap off the tool changes and left only itemgroup stuff

**Pull request closed without merging**
