### PR TITLE
Speed up drawing (currently only console)

### PR DESCRIPTION
**Pull request by Coolthulhu**
In master, map drawing does quite a bit of extra checks and no caching.

Here I add a wrapper for a [submap, point] pair that implements methods from submap using arguments from the point. This allows getting multiple features from tile (furniture, terrain type, trap etc.) with just one bounds check and submap lookup, without having to allow classes outside `map` to use submaps directly.

I use that wrapper to cut the number of extra checks per drawn map tile by a factor of about 6.

Currently only the console drawing is sped up. Tiles drawing would probably get even more of an advantage from caching, as many features in tiles drawing check 4 neighbors per every single tile.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woot!

**Comment by BevapDin** [comment]
There are quite a lot duplicated (from submap) functions in that new class `maptile`. Some are so specific, they are only used in `map::drawsq`. In short, this seems like a lot of pointless repetition. Why can't the map class access those submap functions directly using the `maptile` data? E.g. instead of `curr_maptile.get_item_count()`, `mt.sm->itm[lx][ly].size()` /(rename `curr_maptile` to `mt`, extract x and y into local variables lx, ly).

At least `submap::get_maptile` seems completely pointless, why shouldn't the map create an instance of `maptile`? It is already a friend. Deferring this to the submap seems simply unnecessary.

Have you measured the speed up?

None of the above is a deal breaker, so I'll give it a try anyway. It can always be changed later.

Btw. it might be worth to get rid of passing `g->u` to `drawsq` every time. It's always `g->u`, so why no let the function get that reference on its own.

**Comment by Coolthulhu** [comment]
> There are quite a lot duplicated (from submap) functions in that new class maptile. Some are so specific, they are only used in map::drawsq.

Yes, they are supposed to be.
Currently only `drawsq` uses them, but I intend to use them in few more places. The maptile approach has the advantage that submaps don't need to be exposed to the more "high-level" code, while still allowing partial optimization.
For example tile drawing (as in, SDL drawing) - it has no access to submaps and it re-reads the same tile multiple times.

Situations like that could be solved by allowing submaps there or by adding a safe wrapper that does the submap stuff without direct submap accesses. I went with the latter here.

I didn't measure the speed up. I approximated it by looking at it. "Noticeably faster", but not sure how much. Depends a lot on viewport size.

Suggestions regarding `submap::get_maptile` and `drawsq` with `g->u` sound good. I am currently fixing other stuff so I won't add them right now, but if I remember I'll include them in next related PR.

**Comment by BevapDin** [comment]
Ok, it seems much time inside of `map::drawsq` is used by `map::get_submap_at` (roughly 50%, but I think my sample size is too big), so this change is actually useful.

However, seen from `map::draw`, only a small amount of time is spend in `get_submap_at` inside of `map::drawsq`, much is spent getting the colors (which requires string instantiating, and function calls to the color mapper) and updating the cache at the beginning.

I'll merge it as it does not break anything and it speeds up `map::drawsq` considerably. But you'll probably get a far bigger speed up by reducing the overhead for getting the colors. For example: each call to `apply_vision_effects` (for invisible terrain, nearly everything at night) will look up the colors used to display the '#' everywhere. Similar each out-of-bounds terrain (each `wputch( w, c_dkgray, '#' )`) requires the color look up based on a freshly created string. It might also be useful to add a overload to the color look up function that accepts a `const char*` to prevent creating a strings every time.

**Pull request merged**
