### PR TITLE
Assassin convict and fix prison scenario description

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Content "Adds a new assassin convict profession"

#### Purpose of change
I wanted to play as an assassin infiltrated in a prison to kill someone in there...

#### Describe the solution
Adds a new convict profession with a hidden knife and a photo of the assassination target! It even has a little mission to go and kill the target, which will not be easy since the mark used to stay surrounded by friends before the cataclysm...

This PR also fixes the description for the prison scenario, there has been a long time since robots stopped spawning in there.

#### Describe alternatives you've considered
To have a more complex mission maybe.

#### Testing
Started a new game with this profession and tried to complete its mission in all types of prison! It works!

#### Additional context
Thanks to @Maleclypse for the idea of the mission.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Don't feel obligated to doing this but you could have the character start with a mission that creates a target zombie inside the prison.

**Comment by Termineitor244** [comment]
> Don't feel obligated to doing this but you could have the character start with a mission that creates a target zombie inside the prison.

I would like to! But I can't assign missions to a profession... Maybe with an EOC that fires with a trait given to the profession... I will see if I can do it, it would be better to just assign a mission from the profession entry but well, one can only wish.

**Comment by Maleclypse** [comment]
@dseguin I don’t know enough to be able to say whether missions could be easily made to assign by profession in addition to how they can by scenario currently?

**Comment by dseguin** [comment]
> [...] missions could be easily made to assign by profession in addition to how they can by scenario currently?

Using EOCs as a workaround is fine for now, but it shouldn't be too hard to add a `missions` field to professions the same way it works for scenarios. I'll see if I can get that working.

**Comment by Termineitor244** [comment]
> > [...] missions could be easily made to assign by profession in addition to how they can by scenario currently?
> 
> Using EOCs as a workaround is fine for now, but it shouldn't be too hard to add a `missions` field to professions the same way it works for scenarios. I'll see if I can get that working.

Thanks! Even then I will have to keep the EOCs for these missions because there is a need to differentiate between the different prisons, but for a normal hitman/assassin profession (outside of prison) it would work perfectly without relying on EOCs. So it would be much appreciated.

**Pull request merged**
