### PR TITLE
Make array the outer element of every file under data/json

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary

SUMMARY: None

#### Purpose of change

Almost every file under data/json has an array as its outer element. This array contains objects with a "type" field. But there is a special case: a single object with a "type" filed can be the the top level element too. There are currently 5 files under data/json that use this shorthand.

More uniform file layout would make using jq and writing tooling easier.
For example: to collect every unique top level key one currently has to write:
```
shopt -s starglob
jq 'objects, (arrays | .[]) | keys | .[]' data/json/**/*.json | jq --slurp unique
```
With this change this can be reduced to:
```
shopt -s starglob
jq '.[] | keys | .[]' data/json/**/*.json | jq --slurp unique
```

#### Describe the solution

This PR changes all 5 file to use an array as the top level element. Note: it does not remove the ability to parse the old format from the game or from existing tooling.

#### Describe alternatives you've considered

Document the shorthand - it appears it is not currently documented.

#### Testing

1. The game starts
2. Can create new character

#### Additional context

none

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
Odd. I piped everything through http://dev.narc.ro/cataclysm/format.html as recommended by https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md why would it fail the stype check?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Odd. I piped everything through http://dev.narc.ro/cataclysm/format.html as recommended by https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md why would it fail the stype check?

Invalid line endings probably?

**Comment by hexagonrecursion** [comment]
On my end the line endings appear to be LF (unix) both before and after the change. Also: json is listed as text in .gitattributes. Wasn't this supposed to take care of line endings?

https://github.com/CleverRaven/Cataclysm-DDA/blob/a79975db9ae2c44b55051947521f89e8d54bfe0b/.gitattributes#L11

**Comment by anothersimulacrum** [comment]
You have one too many new lines at the end of the file. Also, I think you should enforce this in the JSON reader, or else this could just happen again.

**Comment by hexagonrecursion** [comment]
anothersimulacrum, thanks. Now it passes validation.

**Pull request merged**
