### PR TITLE
Healing provides minor first aid experience

### PR DESCRIPTION
**Pull request by facepalm**
As it stands, first aid is a skill that can only be effectively raised with a book.  This PR aims to change that, by adding a little practice whenever you heal (generally via sleeping).  It's not a lot of experience, unless you're getting the crap kicked out of you all day every day, but it should get you a few levels.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
You already gain first aid XP by using first aid items (bandages, first aid kits, disinfectant, etc.) to heal yourself, like you should.

This just doesn't make sense; I see absolutely no reason why a character should become better at applying first aid because they've slept off a lot of bruises.

I'm opposed to this in its current form.

**Comment by facepalm** [comment]
Natural healing as it is is an abstraction for dressing wounds, changing bandages, keeping them clean, etc.  None of that would be fun in-game, so it just isn't there, and you heal in your sleep instead.  This is the experience equivalent of that.

**Comment by aierce** [comment]
I don't have problems raising first aid skill without books.

You should try disassembling pillows, which yield 4 cotton balls. Pillows are rather common. Also bandages are easy to make as well with alcohol , rag and duct tape.

**Comment by Rivet-the-Zombie** [comment]
>Natural healing is an abstraction for dressing wounds, changing bandages, keeping them clean, etc. 

No, it's a representation of 'sleeping it off'. If you want to dress your wounds/change bandages/disinfect them/etc., you need to actually use first aid kits/bandages/disinfectant.

**Comment by facepalm** [comment]
>No, it's a representation of 'sleeping it off'.

Then you shouldn't be able to "sleep off" more than a few hitpoints - one |, say.  Maybe a "healing factor" mutation would work to emulate current gameplay, but people aren't punching bags of hitpoints who can reinflate so long as there's one left.  If you've taken anything like an actual wound irl, you need to dress it and tend to it if you want it to heal, and first aid items aren't nearly easy enough to create to keep up with that demand.

**Comment by sparr** [comment]
I'm with facepalm, at least on the conceptual sleeping bit. Sleep healing is an abstraction for a lot of things, not just rest.

**Comment by DavidKeaton** [comment]
I would disagree, sleeping is you _sleeping_. Your bodies natural healing properties don't constitute an increase to first aid. I can sleep off a black eye, but that doesn't teach me to put ice on it.

**Comment by sparr** [comment]
You can sleep off a black eye. You can't sleep off a one-cut-away-from-death every-body-part.

**Comment by facepalm** [comment]
When you stumble off to bed with one red | left to your name, that's not just a black eye.  You aren't sleeping off a minor ding, you're sleeping off a grievous head injury that would have killed you outright if it had been just a bit more serious.

**Comment by DavidKeaton** [comment]
@facepalm then I would state that constitutes discussion into decreasing how much healing you receive when you sleep.

**Comment by sparr** [comment]
Elevating a swolen limb is one example of how someone might practice first aid while sleeping, without consuming any items.

**Comment by DavidKeaton** [comment]
That requires having knowledge of how and why to do that while you are _awake_.

**Comment by facepalm** [comment]
Fiddling with the rate of sleep healing is not the answer, it's a categorically different beast from "sleeping it off" no matter how fast or slow it is.  

Either sleep-healing is meant to be "sleeping it off," in which case I agree it shouldn't provide experience, but it also shouldn't heal anything more than the final bar's worth of damage, and (now that I think about it) first aid kits and bandages shouldn't be instantaneous healing, OR it's an abstraction of taking care of wounds "in the background" and you should get the experience for that, even through you're not grinding through stacks of bandages.

**Comment by kevingranade** [comment]
All the points about severity are irrelevant, you're not going to learn a
thing about first aid from passively healing, full stop.

**Comment by DavidKeaton** [comment]
@kevingranade I shall cease my discussions, my apologies.

**Comment by sparr** [comment]
@kevingranade do you mean "passively" as in the player not doing anything, or passively as in the character not doing anything? facepalm's whole point here is that the player must already be doing something, so whatever we're talking about already isn't passive.

**Comment by facepalm** [comment]
The argument is that it **isn't** passive, just automatic, following the logic of not forcing players to perform rote actions (like dressing wounds).

Either way, I've spent more time talking about this PR than it took to code it, so there;s that as well.

**Comment by DavidKeaton** [comment]
I wasn't trying to argue. However, if it came across that way to you or anyone, my apologies. I get a bit stern at times when debating my point of view.

**Comment by facepalm** [comment]
@DavidKeaton
I don't see arguing as a dirty word.  It's the only way to work out differences of opinion.  I much prefer it over "debate," which implies a sense of conversational structure that is generally missing.

**Comment by DavidKeaton** [comment]
Okay, I can totally give you that. +1

**Comment by kevingranade** [comment]
I mean the character not doing anything, sleeping doesn't teach you about
how to perform first aid, otherwise we'd all be doctors by 12.
If there's a need for low level first aid practice actions, feel free to
add some kind of improvised wound dressing or similar, but gaining skills
for sleeping is simply nonsensical.
The goal for healing is to eliminate the hp abstraction entirely and
instead accumulate wounds that will heal over time, requiring varying
degrees of medical intervention for it to proceed properly.  This will
eliminate part of the 'sleep heals all wounds' problem.

**Comment by SparrowGryphon** [comment]
The core problem is the health system, you should not be able to fix a concussion with a pocket full of bandages and some ibuprofen. if we flesh out the system and add some more steps it will be a lot easier to level it up.

Diagnose, Clean, Suture, Disinfect, Dress. There now you get 5x the experience fixing the cut on you upper arm. :)

**Comment by DavidKeaton** [comment]
I think that's what Kev is saying.

**Comment by facepalm** [comment]
>The goal for healing is to eliminate the hp abstraction entirely and instead accumulate wounds that will heal over time, requiring varying degrees of medical intervention for it to proceed properly. 

Oh, is it?  That's a better implementation anyway.  

Although, I imagine many players would find it too fiddly, unless the treatment is so effective that it doesn't actually mean much.  See: the evolution of DF's hospital system.

**Comment by kevingranade** [comment]
My intent for the medical interface is that if you have ample supplies you
just hit 'treat wounds' a number of times, and it treats the most severe
wounds first, when it's interesting is when you have limited resources and
have to pick which wounds to treat.  That's separate from the fact that
it's simply more interesting to have some number of bruises, scratches,
bites, etc instead of merely missing a bunch of HP.  Also you get to
balance patching yourself up a bit and maybe taking some painkillers vs
taking a long rest and healing up more fully, even treated wounds are going
to leave you more vulnerable to additional damage.

**Comment by SparrowGryphon** [comment]
Please do this ^ :+1:

**Comment by kevingranade** [comment]
Thanks for the support, it's on my list of things to do, but it's after a
lighting and field of view overhaul, and fixing hordes.

**Comment by facepalm** [comment]
Okay, since First Aid is more or less a wonky placeholder skill until Kevin gets around to refactoring player HP, I'm not going to worry much about polishing it up to usability.  We can revisit this when the new system lands, which will be some time from now.

**Pull request closed without merging**
