### PR TITLE
Deployable grappling hooks.

### PR DESCRIPTION
**Pull request by Broken27**
#### Summary 

SUMMARY: Features "Grappling hooks can be deployed for climbing, just like ladders."

#### Purpose of change

Grappling hooks should be able to be used for climbing in general, not just in the specific case of broken stairs.

#### Describe the solution

Added a deploy_furn action to grappling hooks. Made a new furniture item "f_rope_up".

Also fixed their volume (They were smaller than a long rope) and made them harder to craft (They require proper grip hooks now, not just scrap).

#### Describe alternatives you've considered

None

#### Testing

Started a new game, wished for a grappling hook. Confirmed it can't be deployed. Confirmed f_rope_up allows climbing. Confirmed that smashing it produces grappling hook parts. Confirmed it can be deployed from a roof to climb down.

#### Additional context

The grappling hook doesn't need a wall to be deployed, but in that case it's non-functional - It just looks weird.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I'm not sure I like the solution of making it possible to toss a grappling hook in the air and just have it stay there as a climbable rope, even if it doesn't let you actually climb it without somewhere to climb to. I'd want a second opinion here; you have a reasonable solution in general but it's a bit janky. It seems like we should be able to apply something like a construction check to a deployed furniture to see if there's somewhere above to toss it, but that will require a bit of coding.

**Comment by Broken27** [comment]
It is a bit janky indeed, but this is as far as i can get with json.

If someone is insterested in helped with coding go ahead.

**Comment by Maleclypse** [comment]
Can you please make a link to the discord comment where Kevin said that this was an acceptable temporary measure while the code part to make the grappling hook not hang in the air get's worked on?  At least I think I saw that conversation a few days back.

**Comment by Broken27** [comment]
@Maleclypse sure

https://discord.com/channels/598523535169945603/598529538015887372/731187092092354600

**Comment by I-am-Erk** [comment]
I can accept that as a counter argument. Perhaps the goofy cosmetic thing will encourage a fix.

**Pull request merged**
