### PR TITLE
[WIP] [CR] Derived armor weight and volume

### PR DESCRIPTION
**Pull request by SimonPurdie**
This PR derives armor weight and volume from its attributes rather than using hardcoded JSON values.

This is intended to standardise and automatically balance armor, and to provide groundwork for allowing greater degrees of armor/clothing customisation.

Weight and volume are less balance critical relatively than encumbrance / warmth, which are next on my list of attributes to standardise.

---

New formula for armor weight:
(base_weight_multiplier (0.035) \* body_part_multiplier \* density \* coverage \* thickness) + (storage_weight_multiplier (2) \* density \* storage)

body_part_multiplier is a representation of relative sizes of bodyparts.
Torso: 16, Legs: 8, Feet: 8, Hands: 4, Head: 4, Eyes: 1, Mouth: 2

Capacity of liquid containers and holsters is treated as equivalent to storage (this also applies to volume).

---

New formula for armor volume:
(base_volume_multiplier (0.005) \* body_part_multiplier \* coverage \* thickness) + (storage_volume_multiplier (1) \* storage)

If the armor entirely made of flexible materials then the volume is divided by 4.

---

Here is a google sheet showing how those changes shake out:
https://docs.google.com/spreadsheets/d/1_gihw9Bax8870WBCRa0zlqVmF4QhWqwcri91dXFlS9U/edit?usp=sharing

Due to the requirement to differentiate flexible/nonflexible materials, this PR also diversifies plastic into 2 materials - one for flexible low-density plastics (e.g LDPE / PVC / Nylon) and one for high-density hard plastics (e.g. HDPE / Polycarbonate). Other than the flexibility and density, the materials act identically. They both give "plastic_chunk" when salvaged, diversification of hard chunks and flexible scraps is material for a further PR.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I don't care for this. Having those values specific to each individual item makes stuff actually different from each other. A standardized formula for weight and volume would make everything bland and too similar.

**Comment by hitbutton** [comment]
It's certainly not intended to homogenise armors. Armor resistances are already dealt with via material and thickness, and there's still a lot of variance. Are there any particular changes in the linked spreadsheet that you think make armor that are currently distinct too similar?

I completely agree that encumbrance and warmth will be trickier to standardise, though I do have some ideas about how to go about that. That's outside the scope of this particular PR though.

**Comment by kevingranade** [comment]
I agree with Rivet, weight might be reasonable to calculate based on just counting up materials, but volume isn't determined directly from the stats, that's an ideal that different clothing is going to approximate to differing degrees, and if you're going to have a stat to capture that you might as well just have a volume stat instead.  The other stats are going to differ to even greater degrees, where it's perfectly reasonable for two articles of clothing to have the exact same primary stats except for one (for example enumbrance), but this kind of system doesn't allow for that.
The main problem I have with this kind of system is that it requires someone making an item to be intimately familiar with said formulas in order to make the item act the way they want it to instead of just setting the stats here they want it to be.

**Comment by Rivet-the-Zombie** [comment]
Material thickness doesn't always make sense in terms of how heavy an object should be. This is particularly obvious when you look at something like the RM13 armor, which gains thickness value when activated, but shouldn't be gaining volume or weight, or the armored leather jacket which has a reduced thickness to account for the fact that it incorporates the iron material (not reducing the thickness would have resulted in super-armor due to the iron). Some armor's thickness is lower than you might think from looking at other, similar armor due to inclusion of really protective materials like steel.

There's also stuff like the scavenger gear which is intended to have high weight as a drawback.

**Comment by Coolthulhu** [comment]
> Material thickness doesn't always make sense in terms of how heavy an object should be.

Material thickness doesn't make much sense in general.
Boiled leather doesn't get thicker, dual material items don't have uniform thickness, sci-fi armor doesn't get thicker when powered etc.

There is an advantage of using the formulas: new items are automatically balanced. Currently we have multiple cases where someone added a new item without comparing it to existing ones, which resulted in wild stats. For example, the wedding dress which occupies over half the space plate armor does, despite being made of thin material that folds easily.
There should be an option to override formulas, but they do make good defaults. And good defaults make moding and testing easier.

That override thing would be mandatory, though. We can't have go bags occupy less than 10 volume, jerrypacks carry 5 times their volume in liquids and two full ANBCs fitting nearly in a backpack.

**Comment by hitbutton** [comment]
A flag that allows weight / volume to be set explicitly definitely sounds a good idea, and should address kevingranade's concerns about making custom items difficult.

> jerrypacks carry 5 times their volume in liquid

Actually that's an error in the spreadsheet, not the PR. Volume is increased by liquid capacity (on a 1 to 1 basis) so the derived volume of jerrypack is 46.

RM13 armor seems like it would be better simulated by changing to a different material rather than becoming thicker.

I assumed ANBCs were something like this: https://www.google.co.uk/search?q=nbc+suit&tbm=isch
which would fold down enough to fit a couple in a (fairly large) backpack. If the CDDA ones are meant to be more rigid, then I could just change them back to hard plastic to make then non-foldable.

**Comment by Coolthulhu** [comment]
> Flags to allow weight / volume to be set explicitly definitely sounds a good idea

I'm thinking something lower level than flag.
Formulas could be used at item load, since their results don't change.

In fact, recalculating the base item volume and weight every time those values are needed sounds like a bad idea - many functions enumerate over all items in square/vehicle part. For example, vehicle collision enumerates ALL items contained in the vehicle to get their weight.

Doing it all at item load might take a while, but otherwise it will be recalculated every single turn for every item in player's inventory.
Doing it at item load would also make an override flag redundant - items with volume/weight specified would be overridden, ones without it would use the formulas for the missing values.

**Comment by hitbutton** [comment]
So move the weight/volume calculations to itemfactory.cpp where they are set for the type, rather than the individual item?

**Comment by Coolthulhu** [comment]
Yeah.

Unless there are important per-item elements of the calculation that can't be expressed by multiplying the final value. In such a case it should be cached per type and then once again per-item, with an option to force recalculation.

**Comment by hitbutton** [comment]
Gotcha. I don't think there's any armor specifically that currently requires variable weight/volume, except for non-rigid containers (e.g. waterskins). Those are already special-cased in MASTER, and the values aren't cached. Caching them could be a good a idea, but I think that isn't material for this PR.

**Comment by chaosvolt** [comment]
Hmm. I can see this to be even more of a pain in the ass to balance in a desirable manner than the existing system.

**Comment by hitbutton** [comment]
> Hmm. I can see this to be even more of a pain in the ass to balance in a desirable manner than the existing system.

How so?

**Comment by chaosvolt** [comment]
So long as sane values can be calculated, yes. Either way, future additions will require contributors to be familiar with how these default values are determined, and know when and when not to use them. Then again, since new additions already have just as much issue with potentially not being balance-checked, that only really results in giving screwups like me two different options for said screwing up. XP

**Comment by Rivet-the-Zombie** [comment]
I'm seeing more reasons to *not* merge this than to merge it. We wouldn't want this for probably 3/4 of the existing armor, so that would mean the majority of items would be 'exceptions' and it would further require contributors to learn a special formula to simply figure out what a pair of pants should come out weighing - and that would likely have little relation to what that item actually weighs in real life, which is already how we determine what they weigh in the game. And if they manage to manipulate the values enough that the article of clothing weighs roughly the right amount, then there's a fair chance that its armor values will be totally off because they'd be tied together when *there's absolutely no reason to take that control away from the designer*.

What's the actual benefit here? All I see is drawback upon drawback.

**Comment by hitbutton** [comment]
> We wouldn't want this for probably 3/4 of the existing armor, so that would mean the majority of items would be 'exceptions'

I don't think this is the case though. Could you possibly provide more illustration? The vast majority of values in the spreadsheet are close to the original values, and I think most of the ones that are significantly different are actually indicative of poorly ascribed values in the first place. In general clothing that covers the same amount of the same body part, is made of the same stuff, and is the same thickness, will be similar in size and weight.

> there's absolutely no reason to take that control away from the designer.

No control is taken away from the designer. Since I implemented Coolthulhu's suggestion that would simply require adding the desired volume / weight values to the JSON.

> What's the actual benefit here?

There are the benefits for balancing that have already been discussed here. Contrary to your view I think this will make designing items simpler, as sane values for the armor properties are provided for you rather than requiring you to research how much a vest made of X material should weigh.

This also provides groundwork toward a more open-ended and extensive clothing customisation / crafting system. Currently this area of the game is pretty limited compared to the open-endedness of, say, vehicles. Without methods to judge how balance-critical aspects of armor should interact with each other (e.g. how thickness, warmth and coverage should affect encumbrance, weight and volume ) such a system would be near impossible to balance. My thinking in this area was kicked off by this post by kevingranade on the forums: http://smf.cataclysmdda.com/index.php?topic=11366.msg251003#msg251003

**Comment by Rivet-the-Zombie** [comment]
>I don't think this is the case though. Could you possibly provide more illustration? 

Most clothing's weight is already fine, as they're based off what those items of clothing actually weigh, not off a formula that mashes numbers together, because I weighed a whole lot of different pieces of clothing on my kitchen scale in order to get those values right.

Blue jeans - this formula would leave them weighing 172 grams, and that's about a quarter of what they should weigh.

Sneakers - should be somewhere between two and three pounds, depending on size. Proposed weight is less than half a pound.

Wrist watch - the revised weight is only **seven** grams. That's about as much as a pair of button-cell batteries *alone*. Should be between 50-150 grams. To be fair, the current weight is really low, but it's still not seven grams.

Dress shoes - the current weight is spot-on, at 870 grams. The revised weight is listed at 202, which is about a quarter of what it should be.

Heels - previous weight was also spot-on, 640 grams. Revised weight is a whole 50 grams, which leads me to believe that this version may actually be composed of papier-mâché.

Mind you that these are far from unique; the real-world clothing in DDA is already pretty danged accurate as far as weight goes.

**Comment by chaosvolt** [comment]
Damn. I should've been paying that sort of attention to detail when I was adding stuff. >.<

**Comment by hitbutton** [comment]
That does look like I'm consistently underestimating for a number of items then. I'll take more of a look at the formula to see if I can improve it. Thanks for pointing them out, and it's especially useful to know those items currently have very accurate weights.

The watch is a separate matter. The method isn't suitable for items that don't cover body parts or have storage, and should require them to have weight and volume in the JSON.

**Pull request closed without merging**
