### PR TITLE
lsurvivor gear

### PR DESCRIPTION
**Pull request by ghost**
Top and bottom of a light survivor suit in separate pieces for easier encumbrance management. Extremely similar to a light survivor suit when you're wearing both at once.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
When compared to items other than survivor suits, this is far too good. And survivor suits aren't balanced, so they aren't a good thing to compare to.

100 coverage, 11/19 protection (when reinforced), 3 environmental for just 7 encumbrance is too much.
The pants section is clearly better than survivor cargo pants, whose stats are:
90 coverage, 7/11 protection, 3 environmental, 7 encumbrance, 14 storage, craftable at 6 tailoring (the new ones at 5 tailoring).

The pants section would need to get nerfs that would make it not-stronger than survivor cargo pants. But to make sense to keep it, it would need to stay different from them.
I see the following options:
* Dropping the material thickness to just 1, keeping other stats
* Dropping the coverage to 80, material thickness to 2, keeping other stats
* Bumping the encumbrance to 20 (10 when fit), dropping thickness to 2 and environmental protection to 1 or 0

**Comment by Marrim** [comment]
I'm a little skeptical about the whole idea. You can't hope to make a two-piece suit that would be identical to a full jumpsuit with the same encumbrance.

I'd say not being able to fine manage it is partly a balancing factor of why survivor suits are even allowed this much storage and coverage.

**Comment by mauledbybears** [comment]
Halved the storage, cut all the environmental protection and reduced material thickness to 3. Having half the storage of a MOLLE and protecting you from radiation was ridiculous. Now it's pretty effective armor but without the utility of pants_survivor. Maybe the cut damage protection deserves a nerf too.

**Comment by chaosvolt** [comment]
Hmm. I'm still suspect that the suit will be best as a, well...suit. There's a precedent for actual decent armor being suits. Leather armor and its variants, bone and chitin armor, plate armor...

It would be difficult to make split-up versions of the light survivor suit actually have a valid gameplay purpose if it had to be compared to the survivor trenchcoat and survivor pants. If you want light S.T.A.L.K.E.R.'d gear that you can mix and match, there are already items for that.

In contract, the light survivor suit has its own niche compared to the regular/heavy suits, compared to dedicated medieval suits, and compared to the Monster Hunter-style suits made from whatever you can hunt in abundance.

**Comment by Coolthulhu** [comment]
Still compares too well against everything that isn't a survivor suit (or a fencing jacket).

The biggest problem is that 3 thickness (giving it 9 bashing protection) makes it the best 100 coverage item in its encumbrance range (except for feet and eyes - goggles and boots have better ratios than rest of the equipment).

The next best item of this type is motorcycle pants: 9 armor for 10 encumbrance.

For torso and arms, there is fencing jacket (totally broken at 7 protection, 100% coverage for just 1 encumbrance), but other than that there is no 100% coverage item for torso that isn't either huge armor suit or underwear with no protection.

**Comment by chaosvolt** [comment]
Hmm. So would it be best to balance a split-up light survivor suit, or would be be better to not split it up and balance it from that point?

**Comment by Coolthulhu** [comment]
It would be better to first nerf all the broken items (survivor suits) and only then add split versions of them balanced against now-nerfed suits.

**Comment by chaosvolt** [comment]
Ah, I see. How do the survivorized clothes compare to normal alternatives?

If the survivorized clothes are at least balanced, that gives an end point for how far to nerf the suits, I guess.

**Comment by mauledbybears** [comment]
@Coolthulhu The body armor doesn't cover arms. To cover them with any kind of useful armor you'd have to wear something else as well. At 3 thickness it would balance pretty well against the kevlar vest and dragon skin.

The pants need to be at least slightly superior to pants_army. Right now they have an advantage of 1 material thickness, waterproofing and 5% coverage. They have a disadvantage of 5 warmth. Maybe they should lose that material thickness point.

@chaosvolt It varies. The boots, masks, gloves, bags and some other stuff are mostly fine but the suits and trenchcoats need changes. There's probably more.

**Comment by chaosvolt** [comment]
Right. Even with the survivor suit you would have to augment it with the mask, helmet, gloves, and boots. ^^"

**Comment by vache** [comment]
Perhaps the issue is that armor values are very effective against the majority of enemies at low levels, thus making it hard to really get different levels of protection.

**Comment by Coolthulhu** [comment]
> The body armor doesn't cover arms.

I missed that. Yes, that makes it more balanced, as there are no good dedicated arm guards.
This is also an opportunity to drop the ugly "survivor x" name for those items, as this new vest is a vest and thus is different from the suit.

> Right now they have an advantage of 1 material thickness

And material advantage - kevlar gives it noticeably more cut protection.

> The pants need to be at least slightly superior to pants_army.

It would be better if instead of being superior, they were different but roughly comparable.
For example, less protective but with less encumbrance. Or less protective, but with more coverage.
Or more protective but with less storage and more encumbrance. Or comparable in protection, but with more coverage and (noticeably) more encumbrance (13 or so after fitting).

Warmth isn't really a binary better/worse thing. Waterproofing is nearly meaningless. Environmental protection protects from acid, so it is worth some points.

**Comment by MehMuffin** [comment]
This does address one thing that I've been wondering about: despite the presence of trenchcoats, kevlar vests, chaps, arm guards, etc, survivor suits are still the only piece of survivor-y torso equipment in the normal layer, which to me seems a little awkward--it's possible to get full survivor gear with individual parts on each body bit, except for just the torso+arms.

**Comment by Rivet-the-Zombie** [comment]
>It would be better if instead of being superior, they were different but roughly comparable.

They're supposed to be slightly superior; they started off as army pants/cargo pants, but they've been improved upon specifically for the purpose of surviving in a zombie apocalypse, and their crafting requirements aren't low.

**Comment by chaosvolt** [comment]
Some extra degree of encumbrance could be plausible, though only as much as needed to balanced against the gained protection and storage. Not sure if they're okay as-is or not.

**Comment by Coolthulhu** [comment]
> they've been improved upon specifically for the purpose of surviving in a zombie apocalypse

Pre-cataclysm gear can't really be improved much, more like specialized. That is, if we're trying to retain realism. And specialization comes at a cost - higher encumbrance, protection vs coverage, storage etc.
And even if we aren't trying to retain realism, pretty much all survivor gear with 100 coverage is crazy good, to the point where it is impossible to balance items against survivor gear with 100 coverage and most other items.

Even just dropping the coverage to 95 would do wonders for balancing.

**Comment by chaosvolt** [comment]
Hmm. I do like the idea of the survivor gear being specialized, yeah. At a minimum, less coverage and more encumbrance sounds logical.

**Comment by Rivet-the-Zombie** [comment]
It is specialized/improved; taking those army pants for our example, they were originally designed to provide camouflage, protect the wearer from environmental hazards like thorns and dirt, and carry a bit of stuff in their pockets. When adapted to a post-cataclysm form like a survivor suit, they have to protect the wearer from things that are trying to bite/claw them by adding kevlar and extra reinforcement, and carry lots more stuff in a comfortable manner. In the simplest terms, the folks who designed those BDUs didn't have to build them survivor-tough because they were never intended to go up against that level of abuse and constant wear. A survivor has that extra information, and understands that their clothing is going to need to handle a lot more abuse than a soldier's basic fatigues were ever made for.

That being said, we could drop the coverage by 5 and it would allow a few hits to get through every now and again, while still keeping the basic concept intact.

**Comment by kevingranade** [comment]
I think the coverage is the best thing to go after, only clothing that's
specifically fully enclosing (power armor, cleansuits) should have 100%
coverage, as long as there is a way to slip an attack between adjacent
articles of clothes, it should fall short of full coverage (even if it's
just by 1%).

**Comment by chaosvolt** [comment]
Hmm. Seems like the best starting point, yeah.

**Comment by mauledbybears** [comment]
I'm with rivet. Survivor gear should be better than what you can find on day 2 or there's no reason to craft it.

I'd never heard the power armor and cleansuits rule. I'll knock coverage down to 95.

**Pull request merged**
