### PR TITLE
Added map memory

### PR DESCRIPTION
**Pull request by Kelenius**
#### Summary
```SUMMARY: Features "Added map memory."```

#### Purpose of change
I'm actually adding this because I want to add a BLIND trait, and to have any ability to navigate the world as a blind person, you'd need to have an ability to remember the map around you. But it's also neat for exploring labs, buildings, or navigating at night.
Relevant issues: #21928, #19053, #11808.

#### Describe the solution
The survivor will now remember the tiles they can see. If they're in the range of a memorized tile and can't see it (because it's dark, obstructed, or out of range), it will be shown as dimly lit. Only terrain is remembered, not furniture, items, or monsters.

A survivor can remember a specific amount of 12x12 tile squares (submaps), 400 by default, 200/800 with forgetful/good memory traits (so 50/100/200 overmap tiles). Oldest submap is erased when you go over the limit.

#### Describe alternatives you've considered
I don't particularly like putting the memorization into terrain drawing, but I can't think of a better place to put it.

I think that grouping the memorized tiles by overmap tiles would be preferable to using submaps, but I haven't found a way to translate from one to another.

It would be good if a survivor could pick which overmap tiles to always remember and which ones to never remember, but that, first, runs into the above issue, second, goes outside of the scope of this PR.

The number of tiles you can memorize is completely arbitrary and should be adjusted after playtesting and player feedback.

#### Additional context
- [x] Make this work in tile mode
- [x] Make this work in ASCII mode
- [x] Make this save

### CODE REVIEW

**Comment by Mecares** [comment]
Could you make the amount scale with intelligence as well? I think int could use some more benefits to give.

**Comment by Kelenius** [comment]
I could, but the numbers would need adjusting anyway.

**Comment by AMurkin** [comment]
Visual difference would be hard for ASCII, I suppose.

**Comment by Kelenius** [comment]
Actually, a different color is possible. Even transparency, by the looks of it. I'll poke at it and see if I can make it look good.

And I'll probably add a key to toggle them too. That's easy.

**Comment by Inglonias** [comment]
My two biggest concerns are this:
1. Is this persistent if you close and reopen the save file?
2. How does this affect performance of the game in terms of save/load, as well as in everyday interactions like walking around?

**Comment by Kelenius** [comment]
1. It will be persistent, wouldn't be any point making it otherwise.
2. Not much and not much.

**Comment by jniscior** [comment]
This does look good but something very similar is already used for dim lighting. Wouldn't two of those clash with each other? And is it obvious to the player what part of the visible area is a memory map and which part is dimly lit?

Perhaps the memory map should be blended with a different color other than black? To distinguish between something you remember but cannot see and something that you see but has low light.

Just a thought/concern.

**Comment by cainiaowu** [comment]
Related Issues #11808 #21928.

**Comment by paulenka-aleh** [comment]
If remembered terrain changes, I suppose player won't know until he sees?.. E.g. of a worm turns up soil right behind the tree, hulk destroys a wall in the room next to yours or you mininuke goes off destroying house full of Zs a few overmap tiles away

Btw, keeping tiles in memory for which overmap notes exist would be a nice feature.

**Comment by AMurkin** [comment]
It made me think - not store tiles, that not changed after last seen. Actually allocate memory when something alters a tile state.

**Comment by Kelenius** [comment]
I currently have two ideas how to make it look:
Dimmer but in color:
image
Or grayscale:
image

**Comment by paulenka-aleh** [comment]
Would it be feasible to increase memory a bit for those who installed enhanced memory banks?

Although, seems out of scope for this PR, but camera could make ladscape photos to quickly refresh the memory or even have a look while away

**Comment by MT-Arnoldussen** [comment]
Memory banks actively fight forgetting (due to skill rust) and drain your batteries doing so. Making it help with map memory the same way would mean it would become a permanent battery drain once you are over your memory cap. 

Of course, if intelligence increasing memory size gets implemented, it would be trivial to have memory banks count as some number of extra intelligence for that calculation. That seems to be outside of the scope of the current PR though.

**Comment by kevingranade** [comment]
I'm not merging non-cosmetic tiles-only features.

Theres definitely a way to do this in curses, well just need to wait until we have that sorted out.

**Comment by cainiaowu** [comment]
Gray on Brown (or the reverse) may be a good choice, like the one in GBA pokemon, give you some kind of "old map" feeling.

**Comment by jniscior** [comment]
Making a gameplay feature gated by using tiles is a slap in the face for everyone using curses and I agree with Kevin that it should not be merged.

Also if you could please provide screenshots of your solution working with night time/low light circumstances. Best way to test, I think, if there would be no clash between lightning and memory map is to have a character stand in an open field when the sun is almost down. So some areas would be in dim light, some in very dim and the rest (which would normaly be dark) would be the memory map showing.

**Comment by Kelenius** [comment]
Fine. Works in ASCII now.

**Comment by OzoneH3** [comment]
Very nice. Not too sure about using c_brown though (Sadly there is no light gray..). Can be hard to tell on the edges to the ground.

**Comment by Kelenius** [comment]
Brown is quite striking visually. Light grey meshes with low-light areas.

**Pull request merged**
