### PR TITLE
Magiclysm - Crusader spells

### PR DESCRIPTION
**Pull request by Nijiru**
#### Summary
Mods "Adding Crusader spells"

#### Purpose of change
I noticed that the spells for the Crusader attunement were not done, and decided to take a crack at them as my first attempt into adding stuff to JSON files.

#### Describe the solution
I stated Holy Shield using some of the measurements for shields from the old Medieval Weapons mod, and tried to make it the next set in the line of Lesser Bracer of Defense -> Greater Bracer of Defense statwise, except it also ties up one arm like a suitcase or bindle.  The arm it is on should be switchable.
~~As for the Sword of Judgement, I stated out what would be a Longsword +4, simply continuing the already set upgrade modifiers.
Both weapons are unbreakable, unsellable, and only one of each can be equipped at a time.
I also added the new weapon to the two martial arts I know of that use Longsword: Medieval Swordsmanship and Ninjitsu.~~

#### Describe alternatives you've considered
~~Adding different techniques to the Sword of Judgement besides the WBLOCK_2 from the Longsword base.~~
Converting Holy Shield to an aura that doesn't take up an equipment slot.
~~Using a different weapon as the base for the Sword of Judgement.  Either one or two handed.
Making Sword of Judgement an offensive spell.  I have no idea on what would work as good parameters for such a spell.~~
Leaving this alone and letting someone else work on it.

#### Testing
I have started two new games, mutated into Crusader, cast the spells and gone on a rampage through the nearest town, both times with all Stats at 20, all Skills at 10, and the Swordsmanship martial art.  One time was at starting evolution and the other world was one with a 9999 day advanced evolution.

#### Additional context
EDIT: removed Sword of Judgement as there are already plans for that spell.

### CODE REVIEW

**Comment by Xpyder** [comment]
It sounds like this is one of your first PRs so I just wanted to say ty for taking a crack at it and I'm excited to see how they work out in game.

We're coming up on pushing out a new stable release (#42658) so there will be a delay to these being brought in to the main branch.

In the mean time I wanted to make sure you know you can test these yourself (and take advantage of the content) by copying the appropriate files over the actual game itself (if you're on windows I recommend using the [C:DDA Launcher ](https://github.com/remyroy/CDDA-Game-Launcher/releases) as it makes it easy to restore the original files if your change ends up breaking anything)

Also I wanted to call your attention to the Debug menu in the game, super useful for testing to grant yourself the appropriate spells and targets and stuff

**Comment by Nijiru** [comment]
I actually just made a full second copy of my game, so that the file I'm playing is not being affected by this testing.
I did use Debug to give myself the spells and make sure they work without giving errors, made sure the shield can swap arms, and then used them to rampage through a town for a bit.  My main character is not far enough into Magiclysm yet to do attunements, so I currently have no immediate need for any of these changes on my main file.

**Comment by Nijiru** [comment]
KorGgenT has informed me that he has plans for Sword of Judgement already, so I have removed that spell from the PR.

**Comment by KorGgenT** [comment]
i'm going to make some slight edits for the balance but the concept seems fine.

**Pull request merged**
