### PR TITLE
[RDY] Changing welding googles recipe skill requirements

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Welding googles recepie for some reason requires tailoring 4. I recommend to change it to require mechanics 3 (just like for crude welder) for multiple reasons:
- Welding googles is used for welding, that is related to mechanics. Is not related to tailoring directly
- Player need to invest heavily in tailoring to craft welding goggles  but at the same time in mechanincs to craft crude welder. But both of this items actually related to the same things - welding and mechanins
- goggles_nv at the same time require real profile skill: "electronics" that is logical
- Welding googles recepie looks like hand made improvisation (ductaping any google and covering it with spray) but not like something that require tailoring
- Car repair with ductape  is heavily nerfed now. So if player have no access to "true" welder then the only option to proper repair - is crude welder.  But it is unusable without welding googles.

### CODE REVIEW

**Comment by SeanMirrsen** [comment]
What, not even a discussion?

In what way does it make sense to use mechanics to craft welding goggles? If you're going to change it to something, change it to fabrication.

**Comment by Oskar636** [comment]
How about you make it use fabrication (3-4?) but require mechanics (2-3?)? Makes more sense to me but not sure that's how it works.

**Comment by Firestorm01X2** [comment]
Well. My opinionis google_nv (night vision googles)
It requires has electronics 7 and tailoring 1. So maybe recepie for welding googles should changed as:
mechanics 2 and fabrication 1

**Comment by Firestorm01X2** [comment]
Let's discuss future changes (if needed) there:
https://github.com/CleverRaven/Cataclysm-DDA/issues/18641

**Comment by mugling** [comment]
> What, not even a discussion?

OP's arguments were reasonable and another developer also tagged it as in agreement. Prior to this PR there wasn't any discussion so a change from `tailoring` (which everyone agrees is bad) to `mechanics` is better than no change at all.

**Pull request merged**
