### PR TITLE
[WIP] Blazemod refactor

### PR DESCRIPTION
**Pull request by ave-**
#### Summary

SUMMARY: Mods "Refactor and restructure blazemod"

#### Purpose of change

Update blazemod structure to mirror dda structure, make it easier to support, obsolete some items

#### Describe the solution

Blazemod is updated on an infrequent basis and is out of sync with internal dda structure changes (directories, naming conventions, etc). Also there are places where 'copy-from' can be used much more extensively.

- [x] Move (and rename) files to their respective directories to (mostly) match dda structure.

- [x] Restructure blob items and vehicle parts (split to several smaller files to match vehicle parts structure of dda - ie frames, wheels, boards, engines, turrets, etc).

- [x] Remove redundant "blaze_" prefix from all files.

- [x] Refactor and split blaze_test.json and move recipes to recipes, items to items, vehicle parts to vehicle parts, etc.

- [x] Dispose of automated turrets (turret automation is another item from vanilla now, not a turret flag), migrate automated turrets id's to manual ones.

- [ ] Testing all the stuff changed

#### Describe alternatives you've considered

Keep it as it is now?

#### Testing

Generate the game with all blazemod content.
Update mod.
Load the game, check items, vehicles, ensure that everything is migrated properly.

### CODE REVIEW

**Comment by BevapDin** [comment]
> is out of sync with internal dda structure changes (directories, naming conventions, etc). 

We have naming conventions? Where are those defined? And for directories as well?

**Comment by ave-** [comment]
> 
> 
> > is out of sync with internal dda structure changes (directories, naming conventions, etc).
> 
> We have naming conventions? Where are those defined? And for directories as well?

First there is `File descriptions` chapter in doc/JSON_INFO.md, then there was several PR's that were splitting various json files and moving them to directories. It is mostly unspoken but respected (for example, see vehicle parts, it was split from one huge file to the smaller categorized jsons).

**Comment by BevapDin** [comment]
At least remove the redundant "blaze_" prefix from *all* files.

**Comment by ave-** [comment]
> 
> 
> At least remove the redundant "blaze_" prefix from _all_ files.
Will do.

**Comment by ave-** [comment]
Almost ready! Will be testing tomorrow, dunno how long it will take due to IMMENSE amount of automated turrets removal and the need to spawn all the blazemod stuff to test renaming and separation to smaller files.

**Comment by Maleclypse** [comment]
How is this coming along?

**Comment by ave-** [comment]
I'm sorry for going dark, but currently there are some real life issues and changes in my work schedule that leave me almost no free time, so I was unable to do any tests.

In a new-year holidays I was only able to rebase my refactor forward to resolve most of the conflicts (actually I rebased the file rename commits and redid everything else again).

I hope that in a few weeks I will be able to devote more time to actually do the tests, but at least in a January chances are slim.

**Comment by ZhilkinSerg** [comment]
I will mark it as a long term, so it won't be closed by `stale` bot.

**Comment by ZhilkinSerg** [comment]
Closing in favor of #37497. Feel free to collaborate with @Soup-de-Loop to update blazemod, make changes in current PR to resolve conflicts and ping me to reopen (or open new PR).

**Pull request closed without merging**
