### PR TITLE
Add disassembly recipes for Exodii material blocks

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add disassembly recipes for Exodii material blocks"

#### Purpose of change
Make those huge blocks of material actually useful.

#### Describe the solution
Each large block is disassembled into 100 smaller blocks with 1/100th the weight of the large one each, and those smaller blocks are then disassembled into actual usable material by weight. Angle grinder is needed to disassemble metal blocks, and circular saw or reciprocating saw are needed to disassemble plastic block.
Increased weight limit for "crafting spot" workbench, so that items that are as heavy as those blocks could be disassembled.

#### Describe alternatives you've considered
Disassembling material blocks into usable material straight away, but it'd take too much time to do so and would cause a delay after disassembly is done, as all the newly-created items are being spawned.

#### Testing
Disassembled material blocks in-game to make sure that disassembly still works fine with huge weights and huge amounts of stackable items produced.

#### Additional context
None.

### CODE REVIEW

**Comment by Drew4484** [comment]
I've got 5/10L chunks written up in #56598, it has some materials that aren't found in the giant ingots but would still be nice to consolidate.

**Comment by AtomicFox556** [comment]
> I've got 5/10L chunks written up in #56598, it has some materials that aren't found in the giant ingots but would still be nice to consolidate.

I'll update this PR to make use of those if and once that one gets merged, then.

**Comment by AtomicFox556** [comment]
... Alright, I fucked this up. Will re-do later.

**Comment by Drew4484** [comment]
> ... Alright, I fucked this up. Will re-do later.

I've done the same thing, you can fix it in github CLI pretty quick. Drop into dev-help when you have a chance.

**Pull request closed without merging**
