### PR TITLE
Mainline and update ATGM launcher from Tanks mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Mainline and update ATGM launcher from Tanks mod"```
#### Purpose of change

Add more powerful and reasonably possible guns to core game.
#### Describe the solution

Add new JSON entries related to ATGM launcher in mainline, replacing mod ones. New data about the gun and ammo weight is taken from Wikipedia, weight of empty casing and volume of all things is approximated (though they do look very bulky). Direct hit damage got increased as well (before it was identical to man-portable launchers). Added an empty tube item which remains after firing a missile.
#### Describe alternatives you've considered

None.
#### Additional context

None.

### CODE REVIEW

**Comment by faefux** [comment]
Would it be beyond the scope of this PR to ask for a disassembly recipee for the amunition?  Always noticed the missiles couldn't be taken apart for gunpowder and huge primers and possibly electronics.

**Comment by Rail-Runner** [comment]
> Would it be beyond the scope of this PR to ask for a disassembly recipee for the amunition? Always noticed the missiles couldn't be taken apart for gunpowder and huge primers and possibly electronics.

Could do that, but not really sure what one could get from disassembling such a missile. They almost certainly don't use conventional primers, and don't use gunpowder as either fuel or explosive material.

**Comment by Regularitee** [comment]
Based on the setting as a whole, an ATGM would likely be from the '70s and '80s era inventory, especially since these second-echelon militia units (and the front-line units are overseas, unless that was retconned away along with the 2040 starting date in lore). So it'd resemble something like the BGM-71.

In which case you'd be looking at a 20-25 kg missile. The shaped charge would be 5-7 kg of explosive filler, plus another 5 kg of copper. The rest would be flight components, and a solid rocket motor. The rocket motor itself I'm not sure could really be salvaged; or at least, it's so highly specialized it can't easily be re-purposed for much else, unlike explosives.

**Comment by eilaattwood** [comment]
> I'm not sure could really be salvaged, or at least, it's so highly specialized it can't easily be re-purposed for much else; it burns too slow to be an explosive, too quickly to be a fuel, and is probably pre-mixed with oxidiers which could make processing it into something else rather tricky.

I assume it can be used to create another rocket. BTW, there is already rocket fuel (including makeshift one) in the game, isn't it?

**Comment by Rail-Runner** [comment]
Added a disassembly recipe for the unspent missile and for hull (so that the latter isn't completely useless and can at least be disassembled into metal).

**Pull request merged**
