### PR TITLE
XEDRA Armored Trucks

### PR DESCRIPTION
**Pull request by Reuvin**
#### Summary
Features "Adds armored XEDRA trucks meant to provide a relatively early game character a source of extremely limited mutagen." 

#### Purpose of change
There is currently a gap between the two routes of transhumanism. Bionics have been changed to be accessible throughout the entire game with the addition of the Exodii, however mutagen is a purely our-Earth based creation so there will be no extradimensional entities coming in to sell a survivor some. Adding these rare XEDRA armored trucks to the world allows an early game player access to mutagen, putting both transhumanism routes as something that can be accessed throughout the entire playthrough.

#### Describe the solution
This feature just adds a new map extra, the "TCL Armored Truck". The truck is similar to the SWAT and security vans, but additionally contains a minifridge in the back that was meant to be storing mutagen and mutagenic samples. There are a few zombie security guards around the location and a zombie scientist meant to resemble the former crew of the truck, as well as an experimental mutant that was meant to be sedated for the trip before waking up halfway. Functionally the mutant is the main threat to deter completely fresh survivors from the van, but not threatening enough to keep someone with passable equipment away. 

#### Describe alternatives you've considered
Simply not adding this and coming up with another method of making mutagen accessible in the early stages of the game.

#### Testing
Successfully drove around the world until finding the extra naturally. The monsters and items spawn as expected with no errors. 

#### Additional context
Screenshot (21)
The entire view of the map extra. 

On another note the autonote function wasn't working on my game, but as far as I can tell there's no problems with the code for the notes. Not sure if it's a me issue or if I genuinely scuffed the code somehow.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
You've got the summary backwards. It has to follow the format described in the comment as it's parsed by a script and added to a change log. This format is one of the listed code words without quotes, followed by a descriptive line within quotes. Thus, move the quotes and add an 's' to 'Feature'.
This is what the PR Validator / Validate PR (pull_request) rejection tries to say...

**Comment by Reuvin** [comment]
The summary line should be fixed now. I'm not certain how to fix the styling error though. During my learning process I started by just simply fiddling with other codes to see how they worked, and then copying them pretty accurately to suit the needs of this PR as far as I know. If anyone could point out how to fix that error that would be helpful.

**Comment by PatrikLundell** [comment]
Close, but no cigar. You need quotes around the comment part of the line, i.e.

Features "Adds armored XEDRA trucks meant to provide a relatively early game character a source of extremely limited mutagen."

This project demands that everything is formatted exactly as their style checker demands.

"astyle --options=.astylerc --recursive src/*.cpp,*.h tests/*.cpp,*.h" works for Windows, but you'd have to figure out how to install astyle (I've found it somewhere, but I don't remember how to do it).

JSON is similarly rigid with a json_formatter.exe tool compiled into the tools/format folder. This can be integrated into Visual Studio somehow (again, I don't remember how). There's also some web page somewhere where you can post the contents of the file, get it uglified, and then paste the modified text back.

Don't bother trying to figure out how the formatting is supposed to be done. The "documentation" consists of a few examples that shows how a few cases are supposed to look like, without telling you anything about what the rules actually are.

**Comment by Reuvin** [comment]
Okay, the summary line should finally be actually correct. In terms of the styling, are you saying to just ignore the errors so long as the code is functional?

**Comment by PatrikLundell** [comment]
No. The opposite. It will not be accepted until the style demands have been met.

What I've tried to say is that it's futile to try to deal with style demands manually: you'll have to use the tools or you'll spend forever guessing at what it demands that you do to satisfy it.

**Comment by Reuvin** [comment]
Well, I went through and messed with obvious spacing inconsistencies. Doesn't seem like it'll say if it's properly organized now though until someone can manually start the rest of the checks so I can figure out if it wants more fixes or not.

**Comment by PatrikLundell** [comment]
Tests are restarted when you do a new commit.

**Comment by kevingranade** [comment]
As was outlined when you brought this up in discord, the lore doesn't match and the goal of having mutagen drops scattered around like this isn't great either.

**Pull request closed without merging**
