### PR TITLE
Add a machine-readable memorial file

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Infrastructure "Create a machine-readable memorial file at game over"

#### Purpose of change
To support a "top scores" feature and tracking past achievements, we need a machine-readable record of past games.

Currently there only exists the memorial file, which is human-readable.

#### Describe the solution
For the avoidance of doubt, this does *not* remove the existing text memorial file; that still exists for human consumption.  It's less fragile to game changes than the json version, so I have no specific plans to remove it.

Convert the 'intermediate' memorial file (that exists in the `save` directory while the game is ongoing) from plain text to json.

Add a json file, stored in the same place as the existing memorial file (but `.json` rather than `.txt`).
It contains:
* A format version number for future compatibility.
* A json version of the log lines from the existing memorial file.
* A serialized version of the stats tracker.
* A serialized version of the achievements tracker.
* All the valid scores and their values as at game end.

<details>
  <summary>Here's an example (pretty-printed and hand-edited to be less absurdly long; the file on disk is more like minified json)</summary>

```json
{
    "memorial_version": 0,
    "log": [
        {
            "time": 28800,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Shalon 'Chef' Vera began their journey into the Cataclysm."
        },
        {
            "time": 28800,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Used the debug menu (WISH)."
        },
        {
            "time": 28802,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Used the debug menu (ENABLE_ACHIEVEMENTS)."
        },
        {
            "time": 28814,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Gained the achievement Rude awakening."
        },
        {
            "time": 28814,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Lost the conduct Pacifist."
        },
        {
            "time": 28814,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Gained the achievement One down, billions to go\u2026."
        },
        {
            "time": 28815,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Shalon 'Chef' Vera committed suicide."
        },
        {
            "time": 28815,
            "oter_id": "mall_a_30",
            "oter_name": "mall",
            "message": "Last words: Memorial testing 3.1"
        }
    ],
    "achievements": {
        "enabled": true,
        "initial_achievements": [
            "achievement_kill_10_monsters",
            "achievement_lvl_7_bashing",
            "achievement_lvl_10_driving",
            "achievement_lvl_7_driving",
            "achievement_lvl_10_traps",
            "achievement_reach_lab_finale",
            "achievement_lvl_7_mechanics",
            "achievement_bury_100_corpses",
            "achievement_lvl_7_survival",
            "achievement_lvl_7_firstaid",
            "achievement_lvl_10_speech",
            "achievement_lvl_10_swimming",
            "achievement_break_major_limbs",
            "achievement_install_10_cbms",
            "achievement_lvl_7_speech",
            "achievement_lvl_7_gun",
            "achievement_bury_10_corpses",
            "achievement_lvl_10_rifle",
            "achievement_bury_1_corpse",
            "conduct_zero_character_kills",
            "achievement_survive_91_days",
            "achievement_survive_7_days",
            "achievement_wield_crowbar",
            "achievement_lvl_10_mechanics",
            "achievement_reach_min_z_level",
            "achievement_exhume_10_graves",
            "achievement_kill_in_first_minute",
            "achievement_lvl_10_barter",
            "conduct_no_skill_levels_gained",
            "conduct_no_cbm",
            "achievement_lvl_10_fabrication",
            "achievement_lvl_7_barter",
            "achievement_return_to_first_omt",
            "achievement_lvl_7_swimming",
            "achievement_lvl_10_computer",
            "achievement_survive_one_day",
            "achievement_lvl_7_stabbing",
            "achievement_survive_365_days",
            "achievement_lvl_7_computer",
            "achievement_swim_merit_badge",
            "conduct_zero_cut_trees",
            "achievement_lvl_10_firstaid",
            "achievement_crosses_mutation_threshold",
            "achievement_wear_power_armor",
            "achievement_cut_100_trees",
            "achievement_kill_100_monsters",
            "achievement_cut_1_tree",
            "conduct_no_books_read",
            "achievement_lvl_7_launcher",
            "achievement_lvl_10_dodge",
            "achievement_lvl_10_unarmed",
            "achievement_lvl_7_traps",
            "achievement_cut_1000_trees",
            "achievement_lvl_7_fabrication",
            "achievement_survive_28_days",
            "achievement_lvl_10_throw",
            "achievement_reach_max_z_level",
            "achievement_lvl_7_cooking",
            "achievement_lvl_10_cooking",
            "achievement_lvl_7_lockpick",
            "achievement_lvl_10_tailor",
            "achievement_reach_refugee_center",
            "achievement_lvl_7_archery",
            "achievement_lvl_10_cutting",
            "achievement_lvl_7_tailor",
            "achievement_lvl_10_survival",
            "achievement_walk_1000_miles",
            "achievement_lvl_7_electronics",
            "achievement_lvl_7_shotgun",
            "achievement_lvl_10_electronics",
            "achievement_install_1_cbm",
            "achievement_lvl_10_lockpick",
            "achievement_lvl_10_archery",
            "achievement_lvl_10_gun",
            "achievement_lvl_7_unarmed",
            "achievement_lvl_10_launcher",
            "achievement_lvl_7_pistol",
            "achievement_lvl_10_stabbing",
            "achievement_lvl_10_pistol",
            "achievement_lvl_7_rifle",
            "conduct_pure_human",
            "achievement_lvl_10_shotgun",
            "achievement_lvl_7_smg",
            "achievement_lvl_10_smg",
            "achievement_kill_zombie",
            "conduct_zero_kills",
            "achievement_traverse_sharp_terrain",
            "achievement_lvl_7_throw",
            "achievement_lvl_7_melee",
            "achievement_lvl_10_melee",
            "achievement_exhume_1_grave",
            "achievement_lvl_10_bashing",
            "achievement_lvl_7_chemistry",
            "achievement_lvl_7_cutting",
            "achievement_lvl_7_dodge",
            "achievement_lvl_10_chemistry",
            "conduct_no_mutations",
            "achievement_marathon",
            "conduct_no_broken_bones"
        ],
        "achievements_status": {
            "achievement_kill_zombie": {
                "completion": "completed",
                "last_state_change": 28814,
                "final_values": [
                    [
                        "int",
                        "1"
                    ]
                ]
            },
            "achievement_kill_in_first_minute": {
                "completion": "completed",
                "last_state_change": 28814,
                "final_values": [
                    [
                        "int",
                        "1"
                    ]
                ]
            },
            "conduct_zero_kills": {
                "completion": "failed",
                "last_state_change": 28814,
                "final_values": [
                    [
                        "int",
                        "1"
                    ],
                    [
                        "int",
                        "0"
                    ]
                ]
            }
        }
    },
    "stats": {
        "data": {
            "character_takes_damage": {
                "event_counts": []
            },
            "character_loses_effect": {
                "event_counts": [
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "effect": [
                                "efftype_id",
                                "grabbed"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28814,
                            "last": 28814
                        }
                    ]
                ]
            },
            "game_over": {
                "event_counts": [
                    [
                        {
                            "is_suicide": [
                                "bool",
                                "1"
                            ],
                            "last_words": [
                                "string",
                                "Memorial testing 3.1"
                            ],
                            "total_time_played": [
                                "chrono_seconds",
                                "124"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28815,
                            "last": 28815
                        }
                    ]
                ]
            },
            "avatar_enters_omt": {
                "event_counts": [
                    [
                        {
                            "oter_id": [
                                "oter_id",
                                "mall_a_30_north"
                            ],
                            "pos": [
                                "tripoint",
                                "(268,222,0)"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "character_wields_item": {
                "event_counts": [
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "itype": [
                                "itype_id",
                                "knife_combat"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "exhumes_grave": {
                "event_counts": []
            },
            "game_start": {
                "event_counts": [
                    [
                        {
                            "avatar_custom_profession": [
                                "string",
                                ""
                            ],
                            "avatar_id": [
                                "character_id",
                                "9"
                            ],
                            "avatar_is_male": [
                                "bool",
                                "0"
                            ],
                            "avatar_name": [
                                "string",
                                "Shalon 'Chef' Vera"
                            ],
                            "avatar_profession": [
                                "profession_id",
                                "musician"
                            ],
                            "game_version": [
                                "string",
                                "0.E-3920-g6c09236041-dirty"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "character_wears_item": {
                "event_counts": [
                    [
                        {
                            "character": [
                                "character_id",
                                "-1"
                            ],
                            "itype": [
                                "itype_id",
                                "sneakers"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 0,
                            "last": 0
                        }
                    ],
                    ...
                ]
            },
            "avatar_moves": {
                "event_counts": [
                    [
                        {
                            "mount": [
                                "mtype_id",
                                ""
                            ],
                            "movement_mode": [
                                "character_movemode",
                                "walk"
                            ],
                            "terrain": [
                                "ter_id",
                                "t_thconc_floor"
                            ],
                            "underwater": [
                                "bool",
                                "0"
                            ],
                            "z": [
                                "int",
                                "0"
                            ]
                        },
                        {
                            "count": 5,
                            "first": 28802,
                            "last": 28807
                        }
                    ]
                ]
            },
            "uses_debug_menu": {
                "event_counts": [
                    [
                        {
                            "debug_menu_option": [
                                "debug_menu_index",
                                "ENABLE_ACHIEVEMENTS"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28802,
                            "last": 28802
                        }
                    ],
                    [
                        {
                            "debug_menu_option": [
                                "debug_menu_index",
                                "WISH"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "character_kills_monster": {
                "event_counts": [
                    [
                        {
                            "killer": [
                                "character_id",
                                "9"
                            ],
                            "victim_type": [
                                "mtype_id",
                                "mon_zombie"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28814,
                            "last": 28814
                        }
                    ]
                ]
            },
            "reads_book": {
                "event_counts": []
            },
            "character_gains_effect": {
                "event_counts": [
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "effect": [
                                "efftype_id",
                                "hunger_blank"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ],
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "effect": [
                                "efftype_id",
                                "grabbed"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28812,
                            "last": 28812
                        }
                    ],
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "effect": [
                                "efftype_id",
                                "mabuff:buff_eskrima_static"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "player_gets_achievement": {
                "event_counts": [
                    [
                        {
                            "achievement": [
                                "achievement_id",
                                "achievement_kill_zombie"
                            ],
                            "achievements_enabled": [
                                "bool",
                                "1"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28814,
                            "last": 28814
                        }
                    ],
                    [
                        {
                            "achievement": [
                                "achievement_id",
                                "achievement_kill_in_first_minute"
                            ],
                            "achievements_enabled": [
                                "bool",
                                "1"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28814,
                            "last": 28814
                        }
                    ]
                ]
            },
            "character_heals_damage": {
                "event_counts": [
                    [
                        {
                            "character": [
                                "character_id",
                                "9"
                            ],
                            "damage": [
                                "int",
                                "0"
                            ]
                        },
                        {
                            "count": 6,
                            "first": 28800,
                            "last": 28800
                        }
                    ]
                ]
            },
            "character_gets_headshot": {
                "event_counts": []
            },
            "player_fails_conduct": {
                "event_counts": [
                    [
                        {
                            "achievements_enabled": [
                                "bool",
                                "1"
                            ],
                            "conduct": [
                                "achievement_id",
                                "conduct_zero_kills"
                            ]
                        },
                        {
                            "count": 1,
                            "first": 28814,
                            "last": 28814
                        }
                    ]
                ]
            }
        },
        "initial_scores": [
            "score_skill_levels_gained",
            "score_broken_left_arm",
            "score_broken_right_arm",
            "score_damage_healed",
            "score_distance_crouched",
            "score_distance_swam_underwater",
            "score_buried_corpses",
            "score_min_move_z",
            "score_headshots",
            "score_crosses_mutation_threshold",
            "score_damage_taken",
            "score_installs_faulty_cbm",
            "score_moves",
            "score_max_move_z",
            "score_distance_mounted",
            "score_distance_ran",
            "score_cut_trees",
            "score_distance_walked",
            "score_exhumed_graves",
            "score_broken_bones",
            "score_kills",
            "score_broken_right_leg",
            "score_installs_cbm",
            "score_distance_swam",
            "score_gains_mutation",
            "score_broken_left_leg"
        ]
    },
    "scores": {
        "score_broken_bones": [
            "int",
            "0"
        ],
        "score_broken_left_arm": [
            "int",
            "0"
        ],
        "score_broken_left_leg": [
            "int",
            "0"
        ],
        "score_broken_right_arm": [
            "int",
            "0"
        ],
        "score_broken_right_leg": [
            "int",
            "0"
        ],
        "score_buried_corpses": [
            "int",
            "0"
        ],
        "score_crosses_mutation_threshold": [
            "int",
            "0"
        ],
        "score_cut_trees": [
            "int",
            "0"
        ],
        "score_damage_healed": [
            "int",
            "0"
        ],
        "score_damage_taken": [
            "int",
            "0"
        ],
        "score_distance_crouched": [
            "int",
            "0"
        ],
        "score_distance_mounted": [
            "int",
            "0"
        ],
        "score_distance_ran": [
            "int",
            "0"
        ],
        "score_distance_swam": [
            "int",
            "0"
        ],
        "score_distance_swam_underwater": [
            "int",
            "0"
        ],
        "score_distance_walked": [
            "int",
            "5"
        ],
        "score_exhumed_graves": [
            "int",
            "0"
        ],
        "score_gains_mutation": [
            "int",
            "0"
        ],
        "score_headshots": [
            "int",
            "0"
        ],
        "score_installs_cbm": [
            "int",
            "0"
        ],
        "score_installs_faulty_cbm": [
            "int",
            "0"
        ],
        "score_kills": [
            "int",
            "1"
        ],
        "score_max_move_z": [
            "int",
            "0"
        ],
        "score_min_move_z": [
            "int",
            "0"
        ],
        "score_moves": [
            "int",
            "5"
        ],
        "score_skill_levels_gained": [
            "int",
            "0"
        ]
    }
}
```

</details>

(Also fixed an unrelated typo)

#### Describe alternatives you've considered
In the presence of the other game data, this is sufficient to compute most things we might want to be able to compute.  The catch is that if you don't have the same game data (e.g. if different mods are loaded or lots of game development has occurred) then it will be difficult or impossible to interpret.  It still suffices for knowing what achievements were gained and when, but other things that we might want to present regarding older games may not be interpretable.

I'm trying to decide what else, if anything, should be included to that end.  Things I'm considering are:
* The human-readable names and descriptions of the scores and/or achievements (this would be nice for presentation, but it's fragile; e.g it locks in translation to whatever language was set at the time).
* A text dump of the other stuff that goes into the human-readable memorial log.

Opinions welcome.

#### Testing
Started and ended some games, and looked at resulting json.

#### Additional context
Working towards #4173.

### CODE REVIEW

**Comment by jbytheway** [comment]
I've implemented some of the things that were previously just proposals:
* The final values of all scores are now saved in the json (since the way those scores are computed might change, this seems important to preserve).
* The versions of the memorial log lines in the json are now more json-y rather than just strings.

The example output included in the OP has been updated.

**Comment by jbytheway** [comment]
I think I'm now content with this as an initial version.  I'm sure it will evolve over time, but that's why I put a version number in there.

I'd still welcome opinions, but I wouldn't suggest waiting on them before merging.

**Comment by ZhilkinSerg** [comment]
Maybe we should store player/overmap terrain coordinates for each entry?

**Comment by jbytheway** [comment]
> Maybe we should store player/overmap terrain coordinates for each entry?

Do you have a specific use case in mind?  I'm trying not to add things just for the sake of adding them.

**Comment by ZhilkinSerg** [comment]
Someone could use these coordinates to create post-game adventure maps.

**Pull request merged**
