### PR TITLE
Use a byte instead of an int for lum

### PR DESCRIPTION
**Pull request by bkentel**
This is the suggested revision using 8 bits instead of 32; a quick glance over the helper functions for correctness would be appreciated.

### CODE REVIEW

**Comment by narc0tiq** [comment]
Looks good to me.

**Comment by KA101** [comment]
Weirdness: vehicle headights no longer illuminate the immediate area in front o the bumper: rather, they start about a tile or two ahead of the veh.  Start a game, go underground (Mine, preferably), and debug yourself a Hatchback or Car, then turn on the headlights.  (Or wait for nighttime.)

**Comment by bkentel** [comment]
Could be related to the other small change around line 80 of `lightmap.cpp` -- I'll see if I can figure out how / if it's related to these changes.

**Comment by bkentel** [comment]
It doesn't appear to be related to this change -- even removing the code, the light from the car is odd. I even checked on a quite old build 3f652b9, and the light is the same.

**Comment by bkentel** [comment]
Old build:
old_light
New build:
new_light

**Pull request merged**
