### PR TITLE
Map Item Audit

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Content "Adds new map items and reviews existing ones"

#### Purpose of change

Fixes various existing map items revealing OMs unintentionally as well as adding new map items for flavour

#### Describe the solution

Removes hiway from all map items
Fixes "road" revealing several other structures
Removes misleading "access codes" part of handwritten note description
Adds TCL station to handwritten note
Fixes mil op map revealing survivor bunkers and homeless shelters
Expands range of mil op and mall advertising brochure because the OMs are few and spawn more sparsely
Adds gas stations and town halls to road maps
Removes evac shelters from road maps
Fixes subwaymap revealing z-4 subway and various lab stations
Adds trail_intersection to trail map
Adds zoo to tourist map
Allows restaurant map and restaurant advertising brochure to show bar variants in addition to "bar"
Adds diners to restaurant map 
Removes several unintended OMs from satellite map
Removes homeless camp from urban explorers map
Adds forts to the history advertising brochure

Adds sewer map, seems unlikely there'd only be digital copies
Adds buy local, nightlife, get active, gun nut and pet pamphlets for flavour
Adds a new flag PAPER_SHAPED for the leather_journal pocket

Adds a metal map board that acts like a display case for maps
Adds a flyer rack item with PAPER_SHAPED pockets

#### Describe alternatives you've considered

leather_journal and book_binder feel like they could maybe be combined?
Not adding more maps
I don't know much about guns or gun lore in game so if there's a better pick for the gun nut pamphlet than Remington happily comment (also if you can think of better names than gun nut pamphlet and pet pamphlet)
Removing one of restaurant map and restaurant advertising brochure
I had a go at trying to rez the PR in #61214 but didn't get anywhere

#### Additional context

Several entrance tiles to z-4 labs use "subway" instead of "lab_subway" meaning the maps reveal/don't reveal these correctly #66220

### CODE REVIEW

**Comment by Zireael07** [comment]
"Removes hiway from all maps"

Can you explain? I'd think highways are important enough to be shown on maps... unless they got deprecated/removed?

**Comment by Procyonae** [comment]
> Can you explain? I'd think highways are important enough to be shown on maps... unless they got deprecated/removed?
Afaik they're completely unused currently, they were meant to be larger roads idk if anyone's doing anything with them but referencing non existent stuff doesn't make much sense, all the inter city roads just fall under road which all the maps you'd expect to reveal road directions do

**Comment by ashGlaw** [comment]
Love the idea of having paper maps that reveal the sewers. I was asking on Discord a day or two ago about that very thing! Thanks for adding these. 

Where do you think the sewer maps will spawn?

**Comment by Procyonae** [comment]
> Love the idea of having paper maps that reveal the sewers. I was asking on Discord a day or two ago about that very thing!

I said they'd be coming soon 😉 

> Where do you think the sewer maps will spawn?

I've not fully thought spawns out yet, off the top of my head any sewer facility that doesn't have computerised versions should have a chance to spawn with a bulletin board with a map on it and the town hall and public works should have a chance to have them in a filing cabinet or something

**Comment by randomtyper** [comment]
> > Where do you think the sewer maps will spawn?
> 
> I've not fully thought spawns out yet, off the top of my head any sewer facility that doesn't have computerised versions should have a chance to spawn with a bulletin board with a map on it and the town hall and public works should have a chance to have them in a filing cabinet or something

There are also small storage rooms in the sewers with stuff like hard hats and work clothing, imo they are pretty similar to the maintenance rooms in subway stations (the subway maps spawn there) and should have at least a chance to spawn sewer maps, too.

**Comment by Maleclypse** [comment]
Is this ready for review?

**Comment by Procyonae** [comment]
> Is this ready for review?

No I haven't done the things listed in additional context yet

**Pull request merged**
