### PR TITLE
Fix ultra-dangerous shrubs

### PR DESCRIPTION
**Pull request by Coolthulhu**
An improper bash check in vehicle collision resulted in vehicle trying to bash the dirt that the bashed shrub left behind. Since dirt is rather hard to break (impossible in 2D mode), the vehicle used up all its force on bashing the dirt, stopping instantly on the collision.

### CODE REVIEW

**Comment by kevingranade** [comment]
Wha? No wonder I could never find it, that makes no sense at all >_<

**Comment by Coolthulhu** [comment]
This was mostly the result of vehicle collision kinda "inlining" the bash checks rather than re-checking whether the tile is now passable.

Pretty sure that any terrain rammed by a vehicle has to become unbashable rather than just passable for the vehicle to stop the collision loop.

**Comment by jokermatt999** [comment]
Oh my god, so glad to see this fixed.

**Comment by Zireael07** [comment]
Omg what a bug, bashing dirt lol

**Comment by drbig** [comment]
"lol"

And that **hopefully** solves the tank-stopping shrubbery annoyances!

**Pull request merged**
