### PR TITLE
MShock Tileset Modded fix and additions

### PR DESCRIPTION
**Pull request by chaosvolt**
Major fix: I screwed up some sprite assignment, causing things like tubas pretending to be trees, spiral stones pretending to be random chunks of explosion, etc. Also didn't assign military seats properly in the 32x32 version.
## 

Vanilla Spritework:

Sprite changes:
- Made the makeshift macuahuitl use the stone version's sprites

Sprite Assignments:
- Light plate armor
- Armored gauntlets
- Armored boots

Sprite additions:
- Barbute (whaaat, I'm amazed MShock missed that one)
- Kabuto
- Lobster helmet
- Chainmail (vest, coif, sleeves, leggings, armor)
- Sharksuit and faradary shark suit
- New trees (birch, maple, and willow)
- Suitcases
- Harmonica
- Acoustic guitar
- Bagpipes (massive pain in the ass to sprite that)
- Tuba
- Hickory trees (normal, harvested, and dead)
- Harvested birch and willow trees
- Birchbark and willowbark
## 

Mod-related stuff:

Sprite changes:
- Made Kadian's debug-only gift consistent with the new longsword sprites.

Sprite assignments:
- Halberd (real and fake)
- Glaive
- Naginata
- Lamellar armor
- Arms and Armor of Imperial China

Sprite additions:
- Arming sword (real and fake)
- Longsword (real and fake)
- Estoc (real and fake)
- Xiphos
- Khopesh
- Jian
- Dao
- Ji (real and fake)
- Dory
- Qiang
- Fire lance, and ammo
- Bronze
- Corinthian helm
- Galea
- Nasal helm
- Conical helm
- Tunic, rag tunic, sleeveless tunic
- Gambeson
- Chainmail hauberk
- Bronze greaves
- Bell cuirass
- Lorica segmentata
## 

Spritework for content currently only available on Dropbox:

Sprite Assignments:
- The Medieval Warrior
- The Modern Pankratiast
## 

Sprite assignments that will be important later:
- 30mm autocannon (vehicle part)
- Mounted ATGM launcher (vehicle part)
- ATGM turret (vehicle part)

### CODE REVIEW

**Comment by kevingranade** [comment]
Explosion item, nice :)

**Comment by chaosvolt** [comment]
Epic fail on my part. :V

**Comment by chaosvolt** [comment]
Also fail, looks like I've got explosions disguised as cigarette packs too. Lemme fix that real quick. ._.

**Comment by chaosvolt** [comment]
There we go, done mucking about. I was GOING to finish adding Medieval Mod content and spriting instruments, but discovering sprite assignment bugs interrupted that.

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Comment by vipches** [comment]
Eh.. I want to remind you about the diamond weapon... can you make those weapon have diamond upgrade too?

**Comment by chaosvolt** [comment]
Also on my to-do list for sprites. Weird, MShock already sprited flaming weapons, so I'm guessing diamond weapons were added later.

**Pull request merged**
