### PR TITLE
Remove explicitly default virtual constructors from iuse_actor.h

### LINKED ISSUE #11530: Master branch fails to compile
||=== Build: Debug in Cataclysm (compiler: GNU GCC Compiler) ===|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\artifact.h|61|error: looser throw specifier for 'virtual it_artifact_tool::~it_artifact_tool()'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\itype.h|570|error:   overriding 'virtual it_tool::~it_tool() noexcept (true)'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\artifact.h|91|error: looser throw specifier for 'virtual it_artifact_armor::~it_artifact_armor()'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\itype.h|522|error:   overriding 'virtual itype::~itype() noexcept (true)'|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 5 second(s)) ===|

Sorry, folks, guess I'm not mergetesting anything tonight.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9419245-master-branch-fails-to-compile?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
As in title.

Might fix #11530

### CODE REVIEW

**Comment by narc0tiq** [comment]
Those aren't mentioned in #11530, but they would've been a problem if @KA101's compiler had gotten to them (it bailed earlier, in `artifact.h`)..

**Comment by kevingranade** [comment]
Same treatment for it_tool, it_comest, it_artifact_tool and it_artifact_armor?
I can't test it so I don't want to blindly push stuff, but that at least doesn't seem to hurt.

**Comment by narc0tiq** [comment]
> Same treatment for it_tool, it_comest, it_artifact_tool and it_artifact_armor?

I think that should work. I'm disappointed the gcc 4.7 I'm using for the Linux_x64 builds doesn't have the bug -- that was the whole point of using an old gcc for it.

**Comment by KA101** [comment]
mingw-w64 isn't having the problem, so this is testable on my end.

**Comment by KA101** [comment]
Didn't cure the problem, I'm afraid: my testing tonight was mingw-w64.  *grr*

**Comment by Coolthulhu** [comment]
Updated: removed explicitly default destructors from itype and Character. Checked for all lines that start with `virtual` and end with `= default` and found no other matches.

**Comment by KA101** [comment]
Was not made aware of that change, have not retested with mingw32 and since builds are now taking half an hour for clean, not inclined to retest tonight.

**Comment by PropaneSoup** [comment]
I just tried to compile from a clean master on my mingw32, I was getting the same compiling issue that KA101 was. It's still failing, but it's giving me a different error than before:

||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
obj\Release\src\mtypedef.o||duplicate section `.data$_ZZN16MonsterGenerator9generatorEvE9generator[__ZZN16MonsterGenerator9generatorEvE9generator]' has different size|
obj\Release\src\path_info.o:path_info.cpp|| undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'|
obj\Release\src\translations.o:translations.cpp|| undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'|
||=== Build failed: 2 error(s), 1 warning(s) (0 minute(s), 15 second(s)) ===|

**Pull request merged**
