### PR TITLE
Unifies window names

### PR DESCRIPTION
**Pull request by DoctorBoomstick**
#### Summary
None

 #### Purpose of change
As I was casually running around in game, I noticed that many of our windows lacked defining descriptors in their names like, “open,” and “closed curtains.” Given that these descriptors are useful to convey information, this particular fact irked me.

#### Describe the solution
I’ve gone through and added such descriptors to the names of our windows.

#### Describe alternatives you've considered
Not doing a single thing.

#### Testing
They’re simple text edits.

### CODE REVIEW

**Comment by NetSysFire** [comment]
Looks like the test failures are unrelated and you can safely ignore them

**Comment by casswedson** [comment]
we still need to at least reset the basic build and test until it's green, branch protection has that test as a **must pass**

**Comment by NetSysFire** [comment]
I just hit re-run and hope its a transient error

**Review by Maleclypse — APPROVED** [review]
Good fix!

**Pull request merged**
