### PR TITLE
Add a new widget to display weight with the format "##.#/##.#[unit]"

### PR DESCRIPTION
**Pull request by AudBobb**
#### Summary

Features "Add a new widget to display weight as "##.#/##.#[unit]""

#### Purpose of change

I felt like this was a glaring hole in the information you could display in the sidebar, considering all the random stuff you can display over there, so I fixed it.

#### Describe the solution

Added a new functions in display,cpp to pull current units and concat current weight with max weight, and calculate what percent of the max they are to color them appropriately, then added the requisite code to widget.cpp to call on this information. 

I then added a new widgets to legacy labels sidebar to display this new information, because that's the sidebar I use. If anyone wants it added to another sidebar, speak up.

#### Describe alternatives you've considered

Not doing the imperial version because pounds make no sense

#### Testing

image
image

#### Additional context

I'd like to thank my gf for being patient with me while I ignored the show we were watching all day today, and I'd like to thank chatGPT for holding my hand and helping me setup the compiler in visual code, and helping me with c++ syntax because my coding experience is limited to java from 15 years ago, and lua from writing software in the minecraft computercraft mod

My head hurts

I'd also like to thank @Zenefess for giving me some guidance on how widgets work when I first thought about doing this a month or two ago

Should probably rename the existing carry_weight_text variables to denote that they handle the carry weight as a percent, because it's somewhat ambiguous

### CODE REVIEW

**Comment by AudBobb** [comment]
I could probably check that in the display function, I'll look into it when I get home tonight

I honestly threw the imperial one in as a complete after thought

**Comment by AudBobb** [comment]
made necessary changes to remove the code dedicated to the imperial version, and modified the metric function so it detects the users mass unit and adjusts accordingly. Also renamed all variable names to be non unit specific

**Comment by IdleSol** [comment]
```
        unit = "lb";
```
lbs?

**Comment by AudBobb** [comment]
image
image
Updated

**Comment by IdleSol** [comment]
Okay, I'm not good with the imperial system of measurement. Wiki says it's `lb`. But in the options, it's `lbs`. It's better to check with people who use it.

And it's definitely not correct to use `kgs` for metric.

**Comment by AudBobb** [comment]
xD Iooks like lbs is correct for imperial. You'd think as an american I'd know this, but shit makes no gd sense
image

**Comment by AudBobb** [comment]
The build test seems to be failing here due to map generation for the isherwood farm? Not something I touched, so not really sure if I need to be concerned about that or not.

**Comment by Procyonae** [comment]
Presume you missed https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/units_utility.cpp#L91 and https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/units_utility.cpp#L143? (or weight_to_string but I agree that it's nicer for the unit to appear only once) Also you probably want to remove the `(kg)` from ll_weight_carried_value

**Comment by AudBobb** [comment]
Yeah, I sure did miss those, updated to implement them, as well as remove the stray (kg) you found.

**Pull request merged**
