### PR TITLE
Port innawood stream mutable

### LINKED ISSUE #69503: Port Innawoods stream mutable to the main game
### Is your feature request related to a problem? Please describe.

#67065 is pretty amazing and we should have this in the main game, too.

### Solution you would like.

Port it. It may have minor balance implications because it makes infinite water more common again but it also adds realism.

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Content "Previously Innawoods-only stream mutables are now in the main game"

#### Purpose of change

Fixes #69503.
CC @Light-Wave and @SandwichPie. I am unsure if these changes will need to be addressed in Innawood.

#### Describe the solution

Most of this is copied verbatim from Innawoods. I adjusted the mongroups a bit.
Beavers are abundant in Massachusetts (see https://www.mass.gov/info-details/learn-about-beavers), so I found it appropriate to keep the beaver dams as is.

#### Describe alternatives you've considered

n/a

#### Testing

Loads and looks fine! They will cut through forest trails sometimes, which is okay.
Roads will just avoid them altogether, which can look quite silly but this is the worst case I found. Roads can be quite silly in general, so not really the fault of this mutable.

image

### CODE REVIEW

**Comment by Procyonae** [comment]
It's possible to add lil bridges and stepping stones to the trail intersections and small z0 road bridges if you let road spawn over them but I can add those afterwards.
They'll want yeeting from innawoods now tho (outside of making sure they're still whitelisted), no point in the two coexisting

Later on I'd like to turn them into connections so they can path to rivers which is the reason I didn't push for these to be made vanilla originally, but that's not on the horizon still

**Comment by NetSysFire** [comment]
I just removed them from Innawoods. The terrain itself still has the `WILDERNESS` flag, so it should be just fine there.

>It's possible to add lil bridges and stepping stones to the trail intersections and small z0 road bridges if you let road spawn over them but I can add those afterwards.

Yes please. I am not too familiar with mutables yet and have no idea how I would even do that.

**Review by Light-Wave — APPROVED** [review]

**Comment by MNG-cataclysm** [comment]
> > It's possible to add lil bridges and stepping stones to the trail intersections and small z0 road bridges if you let road spawn over them but I can add those afterwards.
> 
> Yes please. I am not too familiar with mutables yet and have no idea how I would even do that.

I was experimenting with the idea some time ago for a PR similar to this one, and I couldn't find a way to make streams reliably cross roads. When two fields were beside a straight road tile, the method I was using (fake overmap ID with blank mapgen, so it didn't affect the road surface but kept the river going) worked fine, but it ran into issues at road corners, intersections, long stretches of road leading to cities, and roads directly beside river tiles.

**Comment by Procyonae** [comment]
> I was experimenting with the idea some time ago for a PR similar to this one, and I couldn't find a way to make streams reliably cross roads. When two fields were beside a straight road tile, the method I was using (fake overmap ID with blank mapgen, so it didn't affect the road surface but kept the river going) worked fine, but it ran into issues at road corners, intersections, long stretches of road leading to cities, and roads directly beside river tiles.

I doubt what I come up with will be perfect but I think occurrences of that kind of thing should be rare with how it works in my head. We need a generalised connection solution to this anyway though for railroad etc which is another reason why turning it into a connection eventually will make more sense.

**Pull request merged**
