### PR TITLE
The ambient sounds

### PR DESCRIPTION
**Pull request by BevapDin**
This includes the commits from #13081, merging this PR should automatically close that PR.

I used the sounds from https://github.com/vulkans22/CataSounds/ for testing.

The game already has a sound effect system. Why should a second one be added? I merged the two systems. For this, I moved several sfx functions into sdltiles.cpp (including the definition of the `sound_effect` struct).

Now playlists and sound effects are loaded via the `DynamicDataLoader`. They are loaded from from `FILENAMES["datadir"] + "sound/"` and only once at program start.

The `DynamicDataLoader` will still load "sound_effect" and "playlist" entries (if there are any) from the data folder because it knows about _all_ load-functions. This may cause problems in the long run - sdltiles.cpp should ideally create its own instance of the `DynamicDataLoader`, which only loads the sound effects and playlists and the main instance of `DynamicDataLoader` should not known about those (needs changes in the `DynamicDataLoader`).

Currently, the game loads sound effects and playlists from "data/sound/soundset.json" and "data/sound/musicset.json" (hardcoded files). With the changes here, they will be loaded from all .json files in the "data/sound" directory. This allows to add "soundsets" by simply dropping them (as new folder) into "data/sound", they only need to contain a JSON file with the sound effect definitions and sound files (similar to the mod or tileset structure). The path of the sound files still need to be relative to the "data/sound" folder (not relative to the JSON file). If different soundsets provide the same sound effects, they will be merged (as if they had been defined together).

It includes the file "data/sound/vulkans-soundset.json" (which was "data/json/soundset.json" in the original PR). One can, for example, put that file and all the linked sound files (see https://github.com/vulkans22/CataSounds/) into one archive that can be extract into "data/sound". Doing so does not interfere with other soundsets (assuming they all go into their own sub folder) and it does not need to be in the repository. Something like this script https://gist.github.com/BevapDin/6e5eb960e28ccb950b35 may do.

---

Threading is done via std::thread. The `sound_thread` struct has a constructor (which is run in the main thread and sets up all the data) and has a `operator()`, which is called in the new thread. This separation makes sure that the new thread does not access any global data, which would not be synchronize and therefor dangerous.

I was able to cross-compile (but not link) after following the advice at http://blog.worldofcoding.com/2014/05/cross-compiling-c11-without-going-madder.html#c11-support and enabling posix threads in the mingw version of gcc. This probably requires to recompile all mxe packages.

Linking worked after I added `-lharfbuzz -luuid -ldxguid -lwebp -lwebpdecoder -lwebpdemux -lglib-2.0 -lgio-2.0 -liconv -lintl -lgthread-2.0 -lgobject-2.0 -lgmodule-2.0 -lgio-2.0 -lws2_32 -lole32`. Not all of them may be needed, but linking takes several minutes and I'm to lazy to test a smaller subset. (Read: this worked for me.)

I did not test that build as it is terrible slow with wine.

---

The old sound effect system and the new sound effect system had different interfaces. The old one uses additional parameters to `sounds::sound`, the new system has its own functions that must be called explicitly. The merged system can use both:

``` C++
// old system: plays sound effect "environment", variant "alarm"
sounds::sound(pos, 40, _("an alarm go off!"), false, "environment", "alarm");
// Basically the same with the new system:
sfx::play_variant_sound( "environment", "alarm", sfx::get_heard_volume( pos ) );
```

Calling only `sfx::play_variant_sound` plays the sound, but does not have any in-game effects (no monsters alerted). `sounds::sound` automatically calls `sfx::play_variant_sound` (and may alert monsters), so using it has in-game effects as well as playing the sound file.

---

And btw. @vulkans22 and everyone else that makes soundsets: Please make sure the file names in your repository match the names in the JSON file. Currently I get errors like "Failed to load audio file data//sound/player/laugh_m/laugh_3.wav" because the file is named "laugh_3.WAV" (uppercase "WAV"). Some file systems know that there is a difference between "wav" and "WAV".

---

Needs some testing, especially in non-Linux environment. Also some testing for whether it still plays the correct sounds, merging this with the current master was a bit complicated.

### CODE REVIEW

**Comment by drbig** [comment]
> Calling only sfx::play_variant_sound plays the sound, but does not have any in-game effects (no monsters alerted). sounds::sound automatically calls sfx::play_variant_sound (and may alert monsters), so using it has in-game effects as well as playing the sound file.

Unify by adding `bool alert` to `sfx::play_variant_sound`? I have a feeling this distinction might get confusing fast. And moving this whole thing into main should give us the way to make it 'right'(-er).

...And that's all I can 'argue' about for now. Good work @BevapDin. I'll actually try to merge-test it here.

**Comment by narc0tiq** [comment]
Via the Jenkins machine, trying to make a wintiles build:
```
ccache /home/narc/mxe/usr/bin/i686-w64-mingw32.static-g++  -DRELEASE -DCROSS_LINUX -DSDLTILES -DTILES -DLOCALIZE -ffast-math -Os -Wall -Wextra -Werror --std=c
++11 -MMD -I/home/narc/mxe/usr/i686-w64-mingw32.static/include/SDL2 -DSDL_SOUND -DLUA -I/home/narc/mxe/usr/i686-w64-mingw32.static/include/SDL2 -c src/start_l
ocation.cpp -o objwin/tiles/start_location.o
src/sounds.cpp: In function 'void sfx::generate_melee_sound(tripoint, tripoint, bool, bool, std::string)':
src/sounds.cpp:607:5: error: 'thread' is not a member of 'std'
     std::thread the_thread( sound_thread( source, target, hit, targ_mon, material ) );
     ^
```

Probably just a missing include?

---

I'm really concerned about 

> I was able to cross-compile (but not link) [...]. This probably requires to recompile all mxe packages.

That's a non-trivial time investment, and a risky one, as well -- last time I tried to update mxe, none of the Windows builds were willing to build anymore.

**Comment by drbig** [comment]
Portability of this thing will be non-trivial, no doubt about it. No reason not to try either.

**Comment by BevapDin** [comment]
>> Calling only sfx::play_variant_sound plays the sound, but does not have any in-game effects (no monsters alerted). sounds::sound automatically calls sfx::play_variant_sound (and may alert monsters), so using it has in-game effects as well as playing the sound file.

> Unify by adding  bool alert  to  sfx::play_variant_sound ? I have a feeling this distinction might get confusing fast. And moving this whole thing into main should give us the way to make it 'right'(-er).

Adding that makes it basically the same as `sounds::sound`, only without a message. This seems to be a bit unfear to user of non-sound builds: they get no indication of what sound (or whether at all) has just affected the monsters.

Also, that parameter would always be compile-time constant anyway, so why not keep two separate functions?

And regarding the distinction causing confusion: how easy is it to mix up just one parameter as compared to a whole different function call? As a similar example: instead of having `to_string(X, 10)` and `to_string(X, 8)`, I would prefer having `to_decimal_string(X)` and `to_octal_string(X)` (they may both call `to_string`).

(The functions may be named better, any suggestions?)

----

>> error: 'thread' is not a member of 'std'

> Probably just a missing include?

Nope, not directly. That mingw version simply doesn't have thread support via C++11. I've run into exactly the same problem and solved as described above, through I'm not sure have feasible that is for the build bot.

> That's a non-trivial time investment, and a risky one, as well -- last time I tried to update mxe, none of the Windows builds were willing to build anymore.

So ... not feasible. Well, looks like I have to write a wrapper using posix threads, I might have done this before.

**Comment by drbig** [comment]
@BevapDin My line of thinking was "you may want to play some sound for the player that does not alert monster" where "Calling only sfx::play_variant_sound plays the sound, but does not have any in-game effects (no monsters alerted)." I understood as equivalent. But I think I see your point so I rest the case here.

My testing shows it works as intended but:
 - `SOUND=1` - yeah, obvious but I've missed it
 - The JSONs between this and https://github.com/vulkans22/CataSounds/ seem broken; the only thing that actually worked for me (i.e. action sounds + bg music) was @Chezzo's zip from http://chezzo.com/cdda/catasounds.zip

So: code-wise it works and compiles fine at least here. Portability, soundsets (:D) etc. - to be done.

**Comment by BevapDin** [comment]
> The JSONs between this and https://github.com/vulkans22/CataSounds/ seem broken; the only thing that actually worked for me (i.e. action sounds + bg music) was Chezzo's zip from http://chezzo.com/cdda/catasounds.zip

The thing with sound effects is a bit confusing: the current master already has sound effects, loaded from "data/sound/soundset.json" (and only this path, and in a format that is incompatible to the `DynamicDataLoader`).

The original PR added *another* soundset.json file (located in "data/json", compatible to the `DynamicDataLoader`). Both were loaded into different variables and were accessible through different functions.

This PR combines both and loads them from any json file in "data/sound". Having them in "data/json" would mean they will only be loaded when the world data is loaded (not when the program starts) and reloaded upon each new game/loading of a game. Or they could be loaded upon program start, but they would be loaded again when the game data is loaded, it would be a bit of a mess. The `DynamicDataLoader` isn't that flexible.

That archive is a bit strange. It contains a
- data/sound/soundset.old (seems to be ... old? Outdated?)
- data/sound/music/danger_theme/danger_extreme.pkf (no idea what that is)
- three soundset files (data/sound/soundset.json and data/sound/soundset.old are the same, but they differ from data/json/soundset.json)
- a playlist

To make it work, you have to:
- unpack into separate folder (not the cataclysm folder)
- remove data/sound/soundset.json and data/sound/soundset.old and data/sound/musicset.json (incompatible, old format),
- move data/json/soundset.json (usable format) to data/sound/vulkans-soundset.json (override the existing file, its format is fine, but its entries are old),
- move data/sound into data/sound of the cataclysm folder (overriding the existing sound folder=).

----

I removed "data/sound/vulkans-soundset.json" from the PR. It is of no use without the sound files and should be distributed together with the sound files.

Ideally, soundset archives should only contain the data/sound folder and they should not contain a "data/sound/soundsets.json" or "data/sound/musicset.json" file, because they would override files from the repository (other json files are fine).

**Comment by BevapDin** [comment]
> error: 'thread' is not a member of 'std'

The simple solution is the wrapper from https://github.com/meganz/mingw-std-threads/, which works fine, but may still need additional linker options. There is no LICENSE file or anything similar in the repository, so I'm not sure whether to use it. It seems to have been intended in the original PR (it included "mingw.thread.h", but did not contain that file).

Using it: download https://github.com/meganz/mingw-std-threads/blob/master/mingw.thread.h into the src folder and apply this patch to use it:
```diff
diff --git a/src/sounds.cpp b/src/sounds.cpp
index 013b442..76d43b5 100755
--- a/src/sounds.cpp
+++ b/src/sounds.cpp
@@ -21,6 +21,9 @@
 #ifdef SDL_SOUND
 #include "SDL2/SDL_mixer.h"
 #include <thread>
+#if (defined _WIN32 || defined WINDOWS)
+#   include "mingw.thread.h"
+#endif
 #endif
 
 #define dbg(x) DebugLog((DebugLevel)(x),D_SDL) << __FILE__ << ":" << __LINE__ << ": "
```

Alternatively, the file could probably go into the mingw include folder.

**Comment by Chezzo** [comment]
Thank you so much!  You are the BEST!

**Comment by kevingranade** [comment]
How hard would it to be to stub out the stuff that has hard dependencies on linking/building craziness?
dRbig pointed out this is really likely to bitrot if we don't get in in relatively soon, and I think he's right

**Comment by BevapDin** [comment]
> How hard would it to be to stub out the stuff that has hard dependencies on linking/building craziness?

Well, the header from https://github.com/meganz/mingw-std-threads/ makes it compile.

I have to add the libraries `-lwebpdecoder -lharfbuzz -lglib-2.0 -lws2_32 -lintl` behind `-lfreetype` (required by SDL2_ttf) to make it work, but that looks like a problem in my mxe setup and unrelated to threads. I can't really test that setup.

**Comment by kevingranade** [comment]
Hey @narc0tiq 
Can you run this through Jenkins after the header update?  I'm hoping it's going to be peaches and sunshine, but we'll see.

**Comment by narc0tiq** [comment]
Sure, I'll give it a try as soon as I have a moment.

**Comment by narc0tiq** [comment]
Looks good now; I'll just go ahead and make sure all the builds are fine with it and then merge it.

**Comment by kevingranade** [comment]
Sounds good, looks good to me, and builds fine here.

**Comment by narc0tiq** [comment]
> Sounds good

No pun intended, of course.

**Pull request merged**
