### PR TITLE
Fix build on mac

### LINKED ISSUE #16377: Error compiling on mac with gcc 5.3.0
seems that this issue comes from [this](https://github.com/CleverRaven/Cataclysm-DDA/commit/e27570398d2acab9e0ac3945b530460c6481da9f) commit
error is:
```
src/iuse.cpp:8141:67: error: moving a temporary object prevents copy elision
      [-Werror,-Wpessimizing-move]
            vehicle_part source_part( vpid, vcoords.x, vcoords.y, std::m...
                                                                  ^
src/iuse.cpp:8141:67: note: remove std::move call here
  ...source_part( vpid, vcoords.x, vcoords.y, std::move( item( *it ) ) );
                                              ^~~~~~~~~~~            ~~
src/iuse.cpp:8147:67: error: moving a temporary object prevents copy elision
      [-Werror,-Wpessimizing-move]
            vehicle_part target_part( vpid, vcoords.x, vcoords.y, std::m...
                                                                  ^
src/iuse.cpp:8147:67: note: remove std::move call here
  ...target_part( vpid, vcoords.x, vcoords.y, std::move( item( *it ) ) );
                                              ^~~~~~~~~~~            ~~
```
i compiled using 
```
make clean
make -j8 RELEASE=1 NATIVE=osx OSX_MIN=10.11 TILES=1 LOCALIZE=0
```
Full log:
[error.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/233532/error.txt)

Thanks!

### PR DESCRIPTION
**Pull request by mugling**
Fixes #16377

### CODE REVIEW

**Comment by mugling** [comment]
Can @ifreund or anyone else verify effective?

**Comment by ifreund** [comment]
I believe Jenkins failed as well

**Comment by ifreund** [comment]
Want to talk on [IRC](http://webchat.freenode.net/?channels=#CataclysmDDA)?

**Comment by mugling** [comment]
I'm not sure if it's for that reason though

**Comment by ifreund** [comment]
ncurses: [it was](http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/4746/Graphics=Curses,Platform=OSX/console)
tiles: [it was](http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/4746/Graphics=Tiles,Platform=OSX/console)
verified now?

**Comment by lucianposton** [comment]
Looks correct, but don't have gcc 5.3 to verify though. You might check with clang

**Comment by ifreund** [comment]
it failed with clang as well.  I'm testing gcc 4.9.3 right now.

**Comment by mugling** [comment]
I'm going to merge this to fix the buildbot. It's a trivial PR to revert if that turns out to be the wrong decision

**Comment by ifreund** [comment]
that gave me a different error:
```
src/veh_interact.cpp:2336:55: error: moving a temporary object prevents copy
      elision [-Werror,-Wpessimizing-move]
        partnum = veh->install_part( dx, dy, part_id, std::move( consume...
                                                      ^
src/veh_interact.cpp:2336:55: note: remove std::move call here
  ...dx, dy, part_id, std::move( consume_vpart_item( part_id ) ) );
                      ^~~~~~~~~~~                              ~~
src/veh_interact.cpp:2391:49: error: moving a temporary object prevents copy
      elision [-Werror,-Wpessimizing-move]
            veh->install_part( dx, dy, part_id, std::move( consume_vpart...
                                                ^
src/veh_interact.cpp:2391:49: note: remove std::move call here
  ...dx, dy, part_id, std::move( consume_vpart_item( part_id ) ) );
                      ^~~~~~~~~~~                              ~~
src/veh_interact.cpp:2491:59: error: moving a temporary object prevents copy
      elision [-Werror,-Wpessimizing-move]
            partnum = veh->install_part( dx, dy, part_id, std::move( con...
                                                          ^
src/veh_interact.cpp:2491:59: note: remove std::move call here
  ...dx, dy, part_id, std::move( consume_vpart_item( part_id ) ) );
                      ^~~~~~~~~~~                              ~~
```

**Comment by ifreund** [comment]
hey that built! 👍
Thanks

**Pull request merged**
