### PR TITLE
9x19mm +P and + prices

### PR DESCRIPTION
**Pull request by faefux**
#### Summary
Bugfixes "9x19mm +P versus + prices"
#### Purpose of change

I did some cursory research and found that 9x19mm +P+ ammo is twice as expensive as 9x19mm +P ammo.

#### Describe the solution

Changed it to reflect this without messing with the previous price range.

#### Describe alternatives you've considered

Making a request for someone else to look at it because I do not really understand gun stuff.

#### Additional context

This did not feel like a bugfix but I didn't really know what category to choose. Feedback on what one to change it to would be nice.

### CODE REVIEW

**Comment by actual-nh** [comment]
Try `Bugfixes "9x19mm +P versus + prices"`. And looks like some rebasing or something is needed?

**Comment by faefux** [comment]
> Bugfixes "9x19mm +P versus + prices"

Thanks. :)

>And looks like some rebasing or something is needed?

Yes. I accidentalied did a pull from my master branch and have been trying to work around that. Very irritating. I'm going to deal with that for good before any other PR's. Apologies.

**Comment by esotericist** [comment]
this shouldn't have gone into master during content/string freeze, so it's going to need to be re-applied towards dev branch

**Comment by faefux** [comment]
> ugh. mistakenly reverted this one instead of the PR i actually intended to, and i'm not sure how i managed to fail on that.

No worries at all, @esotericist.  Do you want me to (more cleanly) re-submit the PR?

**Pull request merged**
