### PR TITLE
Martial Arts Rebalance for Krav Maga

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Krav Maga"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Krav Maga

#### Describe the solution

`Originating in Israel, Krav Maga is based on taking down an enemy quickly and effectively.  It focuses on applicable attacks rather than showy or complex moves.  Popular among police and armed forces everywhere.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 2||
Leg Block|Unarmed 4||
Krav Maga Hand-to-Hand|Unarmed 0|Static Buff|Bash damage increased by 20% of Strength
Krav Maga Edged|Unarmed 0|Static Buff|+20% Stab damage
quick punch|Unarmed 2|Unarmed Tech|Rapid
feint at|Unarmed 2|Unarmed Tech|Feint
percise strike|Unarmed 3|Unarmed Tech|Stun duration: 2
disarm|Unarmed 3|Unarmed Tech|Disarm
grab|Unarmed 4|Unarmed Tech|Down duration: 1
grab break|Unarmed 4|Unarmed & Melee Tech|Grab Break

**Weapons:** PR-24 baton (extended), shock tonfa*, tactical tonfa*, wooden tonfa
*Includes all variations

Krav Maga is style that can do just about everything. It has the most techs of any normal style in the game but doesn't do anything especially well.

_Problems and issues_
- **Lots of techniques but no focus.** 
I'm fine with the style being diverse in it's move set but just because a style has a lot of moves doesn't make it good. In fact, due to the random nature in which the game selects attack techniques, the style can become unreliable if it has too many techniques to pick from.

- **Krav Maga Edged makes no sense.** 
This buff increases Stab damage by 20% and is meant to be used by knives. No style weapon in Krav Maga is a stabbing weapon. So in order to make use of this buff, you must use a knife and doing so will prevent ALL Krav Maga techniques from triggering. This is not a good thing to have in a style.

_Rebalance Goal_
I should start off by saying that Krav Maga as it is now in-game is not over performing. Yes, it can do a lot and could use some tweaks but it isn't overpowered like some people believe. In reality, the majority of the combat styles in the game were not worth using prior to the rebalance. So when a style comes along and can do a little bit of everything, other styles end up looking even worse because they had nothing else to noteworthy to offer. The rebalance of each style will help address this issue.

Krav Maga in real life is used mainly to disable targets by attacking the most vulnerable spots on the human body such as the neck, eyes, joints and the groin (_especially_ the groin). It's versatility and takes the best parts of Aikido, Boxing, Judo, Karate, and Wrestling and combines them into a single combat style. It even includes some weapon training. With this in mind, Krav Maga will become a "jack of all trades" style that takes inspiration from the aforementioned styles. It's weapon list will be expanded and will feature slightly different ways of fighting depending on if a weapon is used. Unarmed will focus on disabling targets and is meant to be very useful against NPCs while using weapons will focus on damage at the cost of losing to a powerful technique.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 2||
Leg Block|Unarmed 4||
Krav Maga Stance|Unarmed 0|Static Buff|+1 Accuracy, +1 Block attempts
Jab|Unarmed 2|Melee & Unarmed Tech|Rapid
Cheapshot|Unarmed 2|Melee & Unarmed Crit Tech|Stun duration: 1
Grab Break|Unarmed 3|Melee & Unarmed Tech|Grab Break
Takedown|Unarmed 3|Melee & Unarmed Tech|Down duration: 1
Counter|Unarmed 4|Melee & Unarmed Block Counter|
Bone Breaker|Unarmed 5|Unarmed Tech|Requires a "downed and stunned target", Disarms, +200% Bash damage, gain Bash armor penetration equal to 100% of Strength, Stun duration: 3

**Weapons:** combat knife, copper knife, cudgel, dive knife, honey scraper, hunting knife, makeshift knife, PR-24 baton (extended), RM42 fighting knife, switchblade, survival knife, tactical tonfa*, trench knife, wooden tonfa
*Includes all variations

**Pistols:** FN Five-Seven, FN 1910 .380, Glock 17, Glock 18C, Glock 19, Glock 22, Glock 31, L2032 Lookout, L39B, L39, M17, M1911, M1911A1, RM232 IDW, S&W 22A, SIG P226, SIG P320, SIG Pro .40, SIG Sauer Mosquito, SIG Sauer P230, Tokarev TT-33, USP .45, USP 9mm, Walther PPK 

**Rifles:** AR-10, AR-15, AK-74M, AN-94, FN FAL, FN SCAR-L, H&K G3, H&K G36, L523-CAR carbine, L523-DSR rifle, L523-LMG, L523-MBR rifle, M14 EBR-RI, M24, M27 IAR, RM51 assault rifle, RM88 battle rifle, SIG 552, SKS, Steyr AUG 

_Important Changes_
- **Krav Maga Hand-to-Hand changed to Krav Maga Stance.**
20% of Strength is worth about +2 Bash damage to the average character and even Strength focused characters are not going to get a lot from it. While bonus damage is always nice, Krav Maga is a style that has weapons AND a bigger damage buff for using weapons. As a result, the bonus unarmed damage is wasted. I changed the static buff to give an Accuracy bonus and a bonus Block attempt. This static buff is used by both unarmed and armed players.

- **Removed Krav Maga Edged.**
This never made sense for a style that didn't used knives. But, even with new weapons, it still isn't balanced enough to keep in the style. I've decided to move the style in a different direction that isn't about pure, static damage.

- **Added Bone Breaker.**
Derived from Aikido's and Judo's joint manipulation, Bone Breaker is the strongest unarmed technique in the game. It deals more damage than any other unarmed attack, bypass some armor, and stuns the opponent for several turns. This is offset by the fact that it requires more setup than any other technique in the game to trigger. To trigger Bone Breaker the following conditions must be met:
You must be unarmed.
Your opponent must be armed. 
Your opponent must have the Downed status.
Your opponent must have the Stunned status.
The technique will trigger 75% of the time in this situation and can be a normal or critical hit. Situations where this technique triggers will be rare but it will be amazing when it happens. This technique can occur only once per opponent due to the fact that it disarms an opponent. Once Bone Breaker triggers, the player should switch to a Krav Maga weapon for more damage and to kill the opponent while they are still stunned.

- **Additional style weapons.**
-- **Knives** - Knives are a common weapon used by soldiers world while and training for knife use is part of Krav Maga.
-- **Cudgel, PR-24 Baton, and Expandable Baton** - Batons are a common law enforcement weapon and Krav Maga can make use of them. A cudgel is roughly the same size as a baton, making it usable as well.
-- **Pistols** - Krav Maga can use pistols. I used semi-automatic pistols as a baseline and excluded compact and revolver handguns since I didn't see either used with Krav Maga.
-- **Rifles** - Krav Maga can use rifles. I used automatic rifles as a baseline and excluded call other types. I'm not sure if other rifles would work so I just stuck with the baseline.

_Advantages_
- Krav Maga is a "jack of trades" style. It gains access to stuns, a knockdown, a Grab Break, a disarm, a counter and can be used unarmed and armed.
- You can use certain firearms with Krav Maga to cover both ranged and close combat.
- Bone Breaker is the strongest unarmed technique in the game and will ruin your opponent's day.

_Disadvantages_
- Nearly all of Krav Maga's offensive techniques are restricted in some way. Takedown requires a stunned target. Bone Breaker has three separate requirements and can only be used unarmed.
- Guns are not meant to do good close range damage. Krav Maga might be able to finish off a weaken opponent but using a gun in melee is usually worse than using a melee weapon.
- While the style leans toward use against NPCs, NPCs can vary greatly in combat skill and can be armed with guns. Krav Maga may not be enough to kill an NPC if you do not have high skills to fight them effectively.

#### Describe alternatives you've considered

The CDDA version of Krav Maga doesn't live up to the real life version. This is partly due to game limitations and partly due to game balance. If I added everything Krav Maga could do to the game it would become both the most powerful and unreliable martial art. As such, I picked a "jack of all trades" approach for the style and left it at that so it wouldn't overshadow every other style.
As for the guns is in the style, I did my best but I'm not a gun person and finding out EXACTLY what guns are used as part of offensive Krav Maga training is difficult. If someone with more knowledge wants to edit the weapon whitelist, by all means do so.

_If the style is too strong..._
- Reduce the damage or stun duration on Bone Breaker.
- Make Cheapshot and/or Takedown only useable while unarmed.
- Remove Bash armor penetration from Bone Breaker.

_If the style is too weak..._
- Add more guns.
- Add a damage bonus to Takedown.

#### Additional context

_References:_
[Krav Maga wikipedia page](https://en.wikipedia.org/wiki/Krav_Maga)
[Krav Maga in real life situations](https://www.youtube.com/watch?v=2uc44atkviU)
[Krav Maga knife training](https://www.youtube.com/watch?v=0gfE_y6vPGw&vl=en)
[Krav Maga weapons](http://www.your-krav-maga-expert.com/krav-maga-weapons.html)

### CODE REVIEW

**Comment by Hymore246** [comment]
> 
> 
> > It's the only way to insure your opponent actually has an arm to be honest
> 
> All humanoid monsters have Species: Human set, as far as I'm aware, so it should be possible to add a check for that. At that point you're writing new melee code, though, so it's out of scope here.

This goes into the idea of adding body parts and checks to monsters which is something the devs don't want to do because tracking those the body part health, conditions, etc is a big headache and will slow the game down by a large amount.

**Comment by jeremyshannon** [comment]
>This goes into the idea of adding body parts and checks to monsters

No, it doesn't. Nothing new would have to be tracked -- anything that has species:human set should be a reasonable target for a joint-lock from what I can see.
  You'd have to add a tag for melee techs that only work against humanoids, and then some code for it to look for the species: human tag when that tech is triggered. That would be better than the present hack (though it's good enough for now) and ought to catch most of the creatures this should work on. (I don't think Krav Maga includes training on how to do this "Bone Breaker" maneuver to a moose. It might be technically possible, but adding the ability to do so would involve adding new tags like "has_bones" or something, which really would be a big undertaking.)

**Comment by Hymore246** [comment]
> 
> 
> > This goes into the idea of adding body parts and checks to monsters
> 
> No, it doesn't. Nothing new would have to be tracked -- anything that has species:human set should be a reasonable target for a joint-lock from what I can see.
> You'd have to add a tag for melee techs that only work against humanoids, and then some code for it to look for the species: human tag when that tech is triggered. That would be better than the present hack (though it's good enough for now) and ought to catch most of the creatures this should work on. (I don't think Krav Maga includes training on how to do this "Bone Breaker" maneuver to a moose. It might be technically possible, but adding the ability to do so would involve adding new tags like "has_bones" or something, which really would be a big undertaking.)

Exactly. That's why I'm not going to do that for this PR. It's outside the scope and required a lot of work just to joint lock an NPC. As far I can tell from the code, there is no way to target a specific body part, so additional functionality would need to be added for that. There would also have to be checks to make sure you can't "break" the same limb more than once if it is already broken.

If clarification is really needed for the technique, I can just change the name to something like Brutal Disarm and remove the joint lock reference. The technique is meant to be a very damaging disarming attack that can only be used when the user is unarmed.

**Comment by jeremyshannon** [comment]
I was not suggesting that be part of this PR, I'm just clarifying that what I was talking about would not require targeting specific body parts or tracking whether it had been done before or anything extensive like that.
 Just that "species: human" would be a better indicator of whether something is humanoid than checking to see if it has a weapon, and it that could be tested for pretty easily to improve the new "bone breaker" maneuver's hacky way of determining suitable targets, at some future date. Hell, I might write it myself if I have the time.

**Comment by Hymore246** [comment]
@Rivet-the-Zombie PR should be good to go. Unless someone needs to do more testing with it.

**Pull request merged**
