### PR TITLE
Adds pet FOOD flag for monsters and taming

### PR DESCRIPTION
**Pull request by DracoGriffin**
Creatures with CATFOOD / DOGFOOD flag can be tamed when fed with cat / dog food, respectively.

Simple PR to allow for upcoming expanded dog breeds and more.

- [x] Address @ZhilkinSerg 's [comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/23779#issuecomment-390469009) - completed

### CODE REVIEW

**Comment by cainiaowu** [comment]
Need document added for modder

**Comment by DracoGriffin** [comment]
>Need document added for modder

I don't understand what you're asking.

**Comment by John-Candlebury** [comment]
>I don't understand what you're asking.

I think they mean you should add a brief explanation of what the flag does in /doc/JSON_FLAGS.md

**Comment by smolbird** [comment]
> Yeah, not sure why when there's plenty of stuff not documented... milkable isn't even there.

Gee, I wonder how that became problem in the first place...

**Comment by ZhilkinSerg** [comment]
There are three pet food types. Can you expand this further for all three types?

**Comment by kevingranade** [comment]
@smolbird chill it with the snide comments, if you dont have anything productive to say, you dont have anything to say.

**Comment by DracoGriffin** [comment]
>There are three pet food types. Can you expand this further for all three types?

You mean dog food, cat food, and cattle fodder? The only one missing is cat food. I suppose I can replace that as well. Please specify so I can address this sooner. Thank you.

>Gee, I wonder how that became problem in the first place...
>chill it with the snide comments, if you dont have anything productive to say, you dont have anything to say.

This is my fault. I wasn't being reasonable, because I thought I had explained what it did in mtype.h, but I realize I should be documenting in the DOC files as well, to hopefully assist others like myself, trying to help create with little to no knowledge of coding changes.

**Comment by ZhilkinSerg** [comment]
> You mean dog food, cat food, and cattle fodder? The only one missing is cat food. I suppose I can replace that as well. Please specify so I can address this sooner. Thank you.

Yes, cat food. You can do it in another PR if you want to.

**Comment by DracoGriffin** [comment]
Jenkins rebuild

**Pull request merged**
