### PR TITLE
Migrate 40mm launchers

### PR DESCRIPTION
**Pull request by mugling**
Adds 40mm launchers and ammo spawns and reworks some of the ammo:
- Frag ammo  produce `shrapnel` as opposed to a single large explosion. As a result they are significantly more effective in enclosed spaces.
- Smoke ammo is now much more effective and has situational usages including providing temporary cover for retreat
- Flare ammo now provides about 30 minutes illumination as opposed to merely being a weak incendiary round. Many tactical usages during night, scouting, distraction etc
- Toxic and acid are gone as they were entirely useless. They are migrated to teargas which I would like to further overhaul in a further PR
- Shot and fletchette are craftable using shotgun primers

Marked CR as 40mm ammo needs deconstruction recipes. For `40mm_shot` and `40mm_fletchette` these are logically the inverse of crafting.

It's unreasonable to allow the construction of `40mm` ammo but it might be permissible for example to allow conversion between types:

`40mm_flare` deconstructs to `40mm_primary` + `flare` and can then be used to produce `40mm_smoke` via `40mm_primary` + `smokebomb`.

Suggestions?

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
While I think the removal of the underbarrel hardpoint from the MOUNTED launchers is a good idea, the handheld launchers could plausibly mount a bayonet.

**Comment by mugling** [comment]
The main priority at the moment is getting the launchers working again. `40mm` is entirely useless and nobody has missed the lack of spawns as a result

**Comment by TempestMaiden** [comment]
You nerfed Flare to range 40 from 90. That intended?

**Comment by mugling** [comment]
> You nerfed Flare to range 40 from 90. That intended?

Yes, it uses the same propellant

**Comment by mugling** [comment]
See updated preamble

**Comment by mugling** [comment]
Ready. We can do deconstruction recipes in part 2

**Pull request merged**
