### PR TITLE
Polish up COMPILING-VS-VCPKG.md

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
None

#### Purpose of change
There are some hang ups and pitfalls with the current instructions that we could call out and ease people into the tooling better.

#### Describe the solution
Clarify the situations.
- Explicitly delineate cmd.exe and git bash command differences.
- Add explanation for 'retarget projects' when using VS2022.
- Specify choosing Release configuration at first launch.
- Enumerate steps to set working directory for debugging.

### CODE REVIEW

**Comment by haveric** [comment]
While we're modifying this, can we add some more detail to: 
```Ensure that the Cataclysm project (`Cataclysm-vcpkg-static`) is the selected startup project, configure the working directory in the project settings to `$(ProjectDir)..` (under Debugging section), and then press the debug button (or use the appropriate shortcut, e.g. F5).```

As someone new to Visual Studio, this took me way too long to figure out how to do. Probably something as simple as simple as "From the Solution Explorer, right click on the..." or something similar.

**Comment by akrieger** [comment]
At a certain point our documentation has to draw the line somewhere between 'teaching you how to do X things for cataclysm' vs 'teaching you how to navigate a developer tool'. I'm happy to add that but I'm wary of things crossing the line into general developer tooling instruction guides because there's plenty of that on the internet.

**Comment by akrieger** [comment]
@haveric let me know how that reads to you.

**Comment by haveric** [comment]
> @haveric let me know how that reads to you.

Looks even better than I was suggesting and reads pretty good to me. I appreciate the updates and I hope they help future devs.

**Pull request merged**
