### PR TITLE
Modularify heavy ballistic vest

### PR DESCRIPTION
**Pull request by epebe**
#### Summary
Content "Allows attaching ballistic shoulder and groin protectors to esapi vests, replace heavy ballistic vests"

#### Purpose of change

The heavy ballistic vest is just the ESAPI vest with arm and leg protection. It feels really convoluted to have three heavy ballistic vest entries for what is essentially the ESAPI vest with add-ons.

#### Describe the solution

Add ablative pockets to the ESAPI vest that only fit the shoulder and groin protectors, similar to the helmet attachments. 
Remove the heavy ballistic vest since it's an ESAPI with the protectors.

#### Describe alternatives you've considered

Leave vests as they are

#### Testing

Spawned kevlar zombies and killed them; they drop US ballistic vests with shoulder and groin protectors. 

Wore ESAPI vest with shoulder and groin protectors, checked the armor screen and saw encumbrance on shoulder and legs. 
I didn't see leg or arm armor values in the body status screen, but I didn't see them on the eye either for a face shield attached to an army helmet. I assume the helmet attachment system works and that the body status is faulty here.

#### Additional context

Shoulder and groin protectors drop clean even if the vest is filthy.
I would like to add thigh protectors like in #62981 if this pull request works out.

### CODE REVIEW

**Comment by Hyperseeker** [comment]
When I tried doing that for [Armory](https://github.com/FrontierMods/Armory), what I found out was that pocket-based pieces of armor don't render (in `tiles`) because the engine has no support for it. (Or so it has been explained to me.) Has that been resolved since 0.G? If not, the pieces won't render, making the armor look somewhat-deceptive.

This may or may not be important-enough to pass this PR. I figured I'd bring it up anyway because a lot of players use tilesets in their games, and some of those like to style their characters. I imagine to them the visuals would be important.

**Comment by Kantonine** [comment]
Another suggestion may i add, is maybe also allow deltoid protectors to be paired with the light plate carriers, with possible hard armor variants for both the hip protection, as well as the arms?

**Comment by Montimorency** [comment]
The light ballistic vest only cuts down to synthetic fabric despite being nominally composed of Kevlar.

Maybe the inconsistency below has something to do with it. 

vest

**Comment by Kantonine** [comment]
> The light ballistic vest only cuts down to synthetic fabric despite being nominally composed of Kevlar.
> 
> Maybe the inconsistency below has something to do with it.
> 
> vest

Thanks for pointing that out!

**Pull request merged**
