### PR TITLE
Infrastructure for using vitamin system for toxins

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Infrastructure "Add infrastructure to support using vitamin system for toxins"```

#### Purpose of change
The vitamin system would be perfectly set up for representing food-borne toxin buildup in the body with only a few small modifications.

Required for #34878 

#### Describe the solution
- [x] Allow vitamins with side-effects from excess, even if they don't have deficiency symptoms.
- [x] Implement distinct severity levels for vitamin excesses.
- [x] Fixed a bug that capped vitamins at 0 regardless of their listed `max`.
- [x] Fixed a bug that caused infinite vitamin buildup even if the player only consumed a small amount a single time.
- [x] Fixed a test that broke because it relied on the above bug to work.

### CODE REVIEW

**Comment by Lunaimon** [comment]
Would this be able to be used for intolerances like gluten and lactose?

**Comment by DaviBones** [comment]
> 
> 
> Would this be able to be used for intolerances like gluten and lactose?

Yes, definitely.

**Comment by DaviBones** [comment]
Making this a WIP until I can test it more, keep running into bugs in the vitamin code.

**Comment by DaviBones** [comment]
Removing the [WIP] tag, I have tested this pretty thoroughly using #34878 and it is working as intended.

**Pull request merged**
