### PR TITLE
Add profession labtech to challenge-labstart

### PR DESCRIPTION
**Pull request by ghost**
It only makes sense that a few lab technicians might not have been lucky enough to evacuate in time

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Could you rename your PR to account for the new changes?

**Comment by Coolthulhu** [comment]
Lab technician is significantly better than volunteer mutant, which has the same point cost.

**Comment by Voskhod-DDA** [comment]
Change labtech from 2 points to 3 then? Maybe 4?

**Comment by Coolthulhu** [comment]
Volunteer mutant to 1 would be better.

**Comment by Voskhod-DDA** [comment]
Volunteer mutant is already 1 though?

**Comment by Voskhod-DDA** [comment]
Changed the profession description to something more generic

**Pull request merged**
