### PR TITLE
Allow MSVC to compile

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Build "Change variable type to allow MSVC to compile"

#### Purpose of change

PR #46456 will not allow compile on MSVC.

#### Describe the solution

Change variable to the same as the auto variable.

#### Testing

Compiles.

### CODE REVIEW

**Comment by BrettDong** [comment]
That's why I'm inclined to use `auto` here instead, but unfortunately `clang-tidy` policy here doesn't allow to do so.

**Comment by RoyBerube** [comment]
Appeasing clang sometimes feels like throwing perfectly good virgins into a volcano.

**Comment by andrei8l** [comment]
The policy allows for `auto` to be used for iterators, but I guess the plugin barfs in this case. IMO this particualr case could be improved greatly by adding `using xp_cutoff_t = std::array<int, 20>` somewhere.

**Comment by BrettDong** [comment]
Is there any attribute or marker or something alike that can make `clang-tidy` plugin silent here?

**Comment by andrei8l** [comment]
This should work: `// NOLINT(cata-almost-never-auto): reason here`

**Pull request merged**
