### PR TITLE
[CR] Vary horde speed based on monsters in horde

### PR DESCRIPTION
**Pull request by nornagon**
Not sure if this is the best approach. Some notable (though not IMHO particularly bad) downsides:

- Hordes will change speed when they get spawned, since they'll switch from being the "idealised" horde to a specific list of monsters.
- The maximum movement speed of any horde is 1 map space every 2.5 minutes. No horde can ever move faster than this.
- This doubles the number of processing steps for hordes, as previously the max speed was 1 space per 5 minutes.

I think a better system would:
1. Always spawn hordes as a specific list of monsters, rather than delaying instantiation until the player moves into range.
2. Queue horde movement on a timer, rather than a fixed tick, so each horde would only be checked exactly as often as needed.

Happy to make changes as needed! Looking forward to your comments :)

### CODE REVIEW

**Comment by DracoGriffin** [comment]
This sounds interesting, but could you expand on why this should be changed? What is the scenario or example you're trying to fix or change ?

I'm assuming you've set it up so that larger hordes move more slowly (bumping into each, "in-fighting" [like hulks], distractions), and smaller hordes move more quickly (less distracted by noises/smells, less stumbling into another, etc), correct ?

**Comment by nornagon** [comment]
Nope, it’s based on the type of monsters in each horde. Hordes with faster
monsters in them will move faster on the overmap.

**Comment by nexusmrsep** [comment]
Why would a horde of zombies and zombie dogs move at z-dog's pace? Zombies would not get any faster just becouse there are dogs among them. Faster Zeds would react faster to opportunity of lunch and either split the horde by moving on their own pace,  or make the horde elongated (stream of zeds) or move as a while at slowest zombies speed. Last option would need a reason, perhaps distraction from other zombies keeps them together, even if certain members could go faster.

**Comment by thethunderhawk** [comment]
What problem does this intend to solve? 
It’s not any more realistic, it doesn’t seem to be adding anything to gameplay, and as you said it doubles the number of processing steps for hordes. I think some clarity as to what you’re envisioning here could be helpful.

**Comment by nornagon** [comment]
I was mostly just fixing the @todo tbh :D

The thing I think this actually changes most is hordes that have spawned
and then returned to being hordes, with mostly fast monsters (eg feral
runners). They should arrive at sounds first, before the fat zombies get
there. And they should arrive faster than they currently do.

**Comment by thethunderhawk** [comment]
If that’s how it works out in practice I’m definitely all for it, long as it doesn’t result in regular zeds traversing the overmap extra quickly. 
I haven’t tested it yet though so I shouldn’t throw stones.

**Comment by Firestorm01X2** [comment]
>If that’s how it works out in practice I’m definitely all for it, long as it doesn’t result in regular zeds traversing the overmap extra quickly.

If you don't start exploding everything it should not be the case already. Hordes reaction on sound changed  long time ago:
https://github.com/CleverRaven/Cataclysm-DDA/pull/19222
https://github.com/CleverRaven/Cataclysm-DDA/pull/20183

It is more or less smooth now.

**Comment by FantasticFwoosh** [comment]
``Zombies would not get any faster just becouse there are dogs among them``

Methodically this is true, but the composition will affect its shape and how quickly it engages threats with dogs & runners at the front as the front end scouting & engaging for the horde making noise and the slower ones at the back. Big circular masses of hordes is a trope when in the context of CDDA it may be more of a narrower 'train' of zeds.

**Pull request merged**
