### PR TITLE
Fix NPCs hitting allies with reach attacks

### LINKED ISSUE #59056: NPCs with reach melee weapons can hit allies in the way
### Describe the bug

Had an NPC riding in a motorcycle sidecar nearly take my arm off with a zweihander when it tried to attack a zombie on the other side of me. I had the NPCs settings to 'avoid shooting if allies are in the line of fire' but it looks like this setting either a) does not work for reach weapons or b) does not work when in a vehicle.

### Steps to reproduce

The motorcycle sidecar example works well because it prevents the NPC from moving closer to the target.
1) Have friendly NPC wield a reach weapon
2) Tell them not to shoot if allies are in the line of fire
3) Board motorcycle w/ sidecar, have NPC also board it.
4) Spawn hostile so that you are between the hostile and NPC
5) Observe as NPC attacks the hostile with their reach weapon, occasionally hitting you in the process

### Expected behavior

NPCs with reach weapons should either abort reach attacks if there is a friendly in the way, or decide whether or not to go through with the attack according to the 'avoid shooting if allies are in the line of fire' command.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 0dbe8ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by natsirt721**
#### Summary
Bugfixes "Fix NPCs hitting allies with reach attacks"

#### Purpose of change
Fixes #59056 

#### Describe the solution
Before making a reach attack, have the NPC check for any `FRIENDLY` creatures in the way. If there are and the NPC is allowed to move, use the `avoid_friendly_fire` method to attempt to maneuver around the ally. If there are but the NPC is not allowed to move, have them complain.

#### Describe alternatives you've considered
Considered allowing `NEUTRAL` creatures to trigger the non-attack logic.  
Considered tying the check to the 'avoid shooting allies' rule.

Can do either or both of the above easily. Figured I'd start simple and respond to feedback.

#### Testing
Used various combinations of a friendly NPC with a spear/long pole and debug monster/player/npc geometry. Also tested with NPC riding shotgun in a vehicle to make sure they behave properly and don't move unexpectedly. Tested with a few combinations of combat rules, but my no means did that exhaustively.

### CODE REVIEW

**Comment by natsirt721** [comment]
I noticed that `avoid_friendly_fire` doesn't work very well if the centroid of allies positions is on the line from the shooter to the target. I can also look into improving the behavior in that case as part of this, or do it separately, or not at all.

**Comment by Maleclypse** [comment]
> I noticed that `avoid_friendly_fire` doesn't work very well if the centroid of allies positions is on the line from the shooter to the target. I can also look into improving the behavior in that case as part of this, or do it separately, or not at all.

If it’s possible that it would be confusing what change is trying to make what behavior fix it might be best to make them separate PRs.

**Comment by natsirt721** [comment]
Not sure why one build is failing, looks like unrelated density test failures.

**Comment by anothersimulacrum** [comment]
That doesn't cause the tests to fail. This is a failure due to the rock throwing sanity test (not your fault, should be fixed with a kick of the tests).

**Pull request merged**
