### PR TITLE
Remove leather material from tourniquet

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Change Tourniquet Materials"

#### Purpose of change

Realized to my horror that vegan characters can't use tourniquets cause it's made of leather. Even though majority of the ingredients are cotton, and that most IRL are nylon or similar, in game they're made with leather and wood. 

#### Describe the solution
Removes the leather material, replaces it with cotton.

#### Describe alternatives you've considered
Make a version that's not handmade that is standard plastic and nylon and the handmade one with wood and cotton. Or just not do that and have it as wood and nylon.

#### Testing
Tested. Works fine

### CODE REVIEW

**Comment by Drew4484** [comment]
Rather than replace, why not make a separate version?

**Comment by Zireael07** [comment]
Why would veganism prevent using leather TOOLS (as opposed to foods)?

**Comment by Karol1223** [comment]
> Why would veganism prevent using leather TOOLS (as opposed to foods)?

I believe the intention is that the trait doesn't allow you to wear animal-product-clothing (leather definitely, I think chitin and wool may fall under this as well?) and the tourniquet is used by... wearing it. So this kinda fell apart.

**Comment by Maleclypse** [comment]
This also breaks the density tests for the tourniquets.

**Comment by Paprika-H** [comment]
> Why would veganism prevent using leather TOOLS (as opposed to foods)?

Because it's a dead animal. Vegans are against any sort of animal products. Also that's just how I coded it, can't exactly change that

**Comment by Paprika-H** [comment]
> Rather than replace, why not make a separate version?

One that's made with a leather belt and one thats not?

**Comment by Karol1223** [comment]
> This also breaks the density tests for the tourniquets.

Correction - this FIXES the density tests for the tourniquets. Just remove them from the known bad density list and it should be good to go, looks like

**Comment by I-am-Erk** [comment]
I'd love to merge this as soon as that test thing is fixed :)

**Pull request merged**
