### PR TITLE
rebalance ketchup

### PR DESCRIPTION
**Pull request by Snaaty**
Just a small thing that came to my mind when raiding a mansion, and all I could find were ketchup bottles. It's a little more nourishing now, but doesn't reduce thirst (due to large amounts of sugar in it, and only being semi-liquid). I also reduced the fun value to -1, so that downing a whole bottle of ketchup is slightly detrimental to your morale.

### CODE REVIEW

**Comment by Midaychi** [comment]
But what if you're pikachu?

**Comment by DavidKeaton** [comment]
most valid question of the year awarh

**Comment by KA101** [comment]
No Electric Rat mutation, so question is invalid.

*KA101 is unfamiliar with pokemon and his sole familiarity with pikachu is from Smash Bros.*

**Comment by DavidKeaton** [comment]
Pokemon is 2dope, great RPG with tons of under-the-hood-and-never-explained-mechanics.

**Pull request merged**
