### PR TITLE
Explosion code refactor

### PR DESCRIPTION
**Pull request by Coolthulhu**
Changed the PR to be more general:
- Moved the explosion code to new files: explosion.h and explosion.cpp
- Explosion actor and explosion in fire now use the same structure, which can be loaded from a json with a single function
- Added the ability of ammo to use its explosion data on ranged hit
- Explosion structure contains the shrapnel data
- Added `game::explosion( tripoint, explosion_data )` - much cleaner than all those arguments. Changed the old explosion function to a be an overload of the 2 argument one.

### CODE REVIEW

**Comment by mugling** [comment]
Nice. I was considering looking into the 40mm ammo and this PR should presumably make that much easier?

**Comment by Mshock777** [comment]
So here's a little story. Back in the days when I was just starting to mess with Cata I made a PR #8727 where I rebalanced some explosives due to the fact that we don't have vehicle armour. If you are going to overhaul explosions you probably should look at how stats where before that PR.

**Comment by BevapDin** [comment]
Maybe it's time to move the explosion code into a separate place (namespace? or make it a member of `explosion_data`).

With the additional parameters and return type from @mugling's shrapnel PR, the `explosion` function should accept a single parameter that contains all the explosion data (for example `explosion_data`). That would make adding more data to it much easier.

**Comment by Coolthulhu** [comment]
> the explosion function should accept a single parameter that contains all the explosion data (for example explosion_data).

Went this route.

`explosion` is still a `game` method, but now it can be invoked with just 2 arguments.

**Comment by mugling** [comment]
@Coolthulhu needs a rebase against master? The diff is >10'000 lines...

**Pull request merged**
