### PR TITLE
Add Vehicles: Full-size, Mini, Cargo, and Camper Vans

### PR DESCRIPTION
**Pull request by DeadArsenal**
#### Summary
Content "Add Vehicles: Full-size, Mini, Cargo, and Camper Vans"

#### Purpose of change
It seemed odd to me that only hippies like vans, so I made new ones.

#### Describe the solution
Using the Hippy Van as a template I created a series of vans that are very similar to the kind you might find on American streets:

**Full-size Van**: _Six seats, a six cylinder engine, and cargo space in the back. Hybrid variant has an electric motor and truck alternator._

**Minivan**: _Six seats, four cylinder engine, and trunk space in the back. Hybrid variant has an electric motor and truck alternator._

**Cargo Van**: _Two seats, six cylinder engine, and a whole lot of cargo space. Opaque rear doors and a single opaque side door._

**Camper Van**: _Similar to the Cargo Van, but has several cargo spaces replaced with amenities relating to mobile living. Comes with a kitchen unit, minifridge, bed, curtains with motors._

**Mini RV**: _A variant of the Camper Van with a clean water tank and a quartet of solar panels._

Changes have been made to some vehiclegroups so that the vehicles can spawn in the game world. Hopefully the values are acceptable.

#### Describe alternatives you've considered
I could have embraced the van-going stoner way of life, but that was too easy.

#### Testing
Modified the files locally, forgot some commas but corrected it afterward.

#### Additional context
Vans

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
CC @acepleiades

**Comment by DeadArsenal** [comment]
My apologies for the Linting issue. Have never used github before.

**Comment by acepleiades** [comment]
Hello, I have changed a few things in how vehicle prototypes are done in order to accomodate some neat details in the sprites https://github.com/CleverRaven/Cataclysm-DDA/pull/50632
I will suggest changes to your PR as soon as I figure out how to do that

**Comment by acepleiades** [comment]
I didn't figure out how to suggest changes directly but here is a json file that only covers the new lines you added
[new 1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6975015/new.1.zip)
I noticed that some vans had 5 wheels and others had 6. I edited them all to have 4. I also edited the doors into the proper nw/ne/sw/se variants, those are important. Please be careful
Before the vehicle parts in #50632 are present in the game, the IDs that I used in that file will not really exist yet. So I don't think the edits should be applied yet. I did test the entries in my compiled game with the new parts though, as you can see in this screenshot:
new vans
Every van is working as it should, and I hope you like the new look.

**Comment by DeadArsenal** [comment]
@acepleiades Those look fantastic! Great catch with the wheels too. I appreciate your help and consideration very much.  Should I wait until your commits are merged to continue? I'm still figuring out how all this works.

**Comment by acepleiades** [comment]
Yes because until that PR is merged, the new parts don't actually exist in the game yet. I hope we get to see the vans in the game soon

**Comment by Maleclypse** [comment]
Can you make one more van.  
`Camper Van: Similar to the Cargo Van, but has several cargo spaces replaced with amenities relating to mobile living. Comes with a kitchen unit, minifridge, bed, curtains with motors, and a quartet of solar panels.`   I've owned one of these in real life and they look exactly like this except they don't have the solar panels.  I'd make the camper van no have solar panels and then make one that called `van_life` that adds the solar panels and a 60 Liter water tank.

**Comment by DeadArsenal** [comment]
@Maleclypse That's a good idea. I'll see if I can strip the solar panels off the Camper Van as you suggest and make an "upgraded" version called a Mini RV that's rare to find.

**Review by Maleclypse — APPROVED** [review]
Thanks for doing this! These are great!

**Comment by Fris0uman** [comment]
So does this need one more PR to integrate Acepleiades changes into the vans?

**Comment by acepleiades** [comment]
Changes were already applied, just see the comments

**Pull request merged**
