### PR TITLE
The less items is worn on torso, the more power Solar Panels CBM will generate

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This sounds incredibly tedious, with the only gain being that solar panels stop being usable in combat.

Plus, it's not really realistic that wearing a belt completely stops your energy regeneration. If you want realism here, you'll need to scale it with product of all "un-coverage".
That is, multiply `100%-coverage` for all items worn on torso.
This would allow regenerating most of the energy when wearing a belt, some of it when wearing a tank top or an apron, but almost nothing when wearing a trenchcoat or hoodie.

Additionally, doing the scaling would make the whole thing significantly less tedious: you could still regenerate energy without the painful undress-regen-dressup routine, just much slower.

**Comment by Noctifer-de-Mortem** [comment]
While having to undress to charge using solar panels is realistic, solar cbm is already a poor way to generate power. You have to wait for the weather to be sunny, or at least clear, to get any real benefit and have to find a spot where there is no obstructions to successfully charge.

**Comment by Coolthulhu** [comment]
Coverage is multiplicative, not additive. Wearing a hoodie and a belt doesn't give 100% coverage.

**Comment by Coolthulhu** [comment]
Again, the formula for non-coverage is a product of `100% - coverage` of all items.
That is:
```
float noncov = 1.0f;
for( auto &it : worn ) { if( it.covers(bp) ) noncov *= (100-it.coverage)/100.0f; }
```

**Comment by Night-Pryanik** [comment]
```
float noncov = 1.0f;
for( auto &it : worn ) {
    if( it.covers( bp_torso ) ) {
        noncov *= ( 100 - it.get_coverage() ) / 100.0f;
    }
}
```
`noncov` shows some insane value like 1610612736.

**Comment by AMurkin** [comment]
Небольшое замечание: незачем рассчитывать покрытие, если нет солнечных панелей.
Minor: no need of counting coverage when no solar panels.

**Comment by Coolthulhu** [comment]
> noncov shows some insane value like 1610612736.

Are you printing it as an `int`?

**Comment by Night-Pryanik** [comment]
>Are you printing it as an int?

Oops, my bad, forgot to change to show it in float from my previous additive integer realization. 
But now 95% hoodie plus 90% shirt `noncov` shows 0,005000.

**Comment by Coolthulhu** [comment]
> But now 95% hoodie plus 90% shirt noncov shows 0,005000.

`10% * 5% = 0.1 * 0.05 = 0.005` - math checks out.
Alternative is using some different formula.
Or handwaving it away as a detail - I don't really see much benefit from nerfing that already situational CBM. We don't have a slot system that would make it shine in any case and at the moment it is generally worse than the alternatives. If it is to be nerfed hard, it may as well be removed instead - if we're going for realism, installing solar panels on human skin is counterproductive and thus inherently unrealistic.

**Comment by Night-Pryanik** [comment]
Ok, closing.

**Comment by kevingranade** [comment]
Scaling via coverage is an option, but I'd prefer to just ditch the solar
panel CBM, it's utter nonsense.

**Pull request closed without merging**
