### PR TITLE
Fixing up the condition of the fishing

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Balance "Various changes to fishing"```

#### Purpose of change
Fishing had some problems.
1) ALL fish were the same weight and volume, 40 kg to be precise. This is ridiculous, even the supposedly tiny fish species ( like pickerel ) were 40kg, this meant that butchery yields were crazy.
2) Fishing checked if there were any fish monsters present in a radius, else it just wouldnt allow you to fish, this is silly, a lake or a river would be full of hundreds of fish, not the handful actually present as game monsters, this meant that you could deplete an entire lake of fishing possibilities after catching 2 or 3 fish.
3) The activity ran for a few hours, then was either succesfull or not at the end of it.
This aims to fix that.

#### Describe the solution
1) I've added a load more fish varieties, based on a template of tiny/small/medium/large/huge fish types, which corresponding weights and thus harvest yields, and added these to spawns.

2) I've made a fish monster have a marker for "fish_population" this is an abstract of the monster on the map representing the underlying fish population present in that body of water, when fishing is a success, this reduces the fish population of that monster by 1, and spawns a corpse of that type, instead of killing it, when the fish population of that monster goes to 0, then that fish dies.
Fishing is still possible in a lake or a river or a flowing water tile, when no fish monsters are present, but at a much reduced chance of success ( to represent the hidden population of fish ), but having fish monsters present is a signifier of a good fish population.

3) Made the activity have a do_turn function that gives a little bit of practice every hour it goes on for, and every turn it checks for a success in catching a fish, based on the population present,  ( and whether you are using a basic rod or pro rod, and your survival skill - which was previously a factor anyway )
So in a 5 hour stint of fishing, with survival skill 10 and a pro fishing rod, you could catch 5+ fish( usually more )
wheras with survival skill 0 and a basic fishing rod, youd be lucky to catch 1 fish in 5 hours.
( I've done similar checks for the fish trap )

This overall means that most fish are gonna yield less meat ( unless you get lucky and catch a salmon )
But depending on where you fish and your skill/tool, you could get multiple fish per session, and you wont deplete the body of water of its entire fish population in doing so.
So I think this makes it balanced and more realistic.

#### Describe alternatives you've considered
I had ideas of making the fishing more realistic by looking at the bait used, and a chance for the line to snap depending on the size of the fish and your strength and so on, but that could be done in a different PR

#### Additional context
I invite comments on balance and numbers used, I've done some testing and it dosnt seem crazy results, but would welcome any input on that.

source

### CODE REVIEW

**Comment by tinukedaya** [comment]
Sometimes you are able to corner a fish in some dead end part of a pond or river and bash it. If that fish now represents whole "population" what is going to happen if you hit it?

**Comment by davidpwbrown** [comment]
> Sometimes you are able to corner a fish in some dead end part of a pond or river and bash it. If that fish now represents whole "population" what is going to happen if you hit it?

If that fish dies, the population associated with that fish type dies with it. Unfortunately that is a bit of a limitation.

**Comment by tinukedaya** [comment]
Can't you detach it? You said, that even without the monsters present, the water is still fishable to represent hidden population. What if the populations are hidden everywhere and from certain population size it will start spawning single monsters. So if you see a fish it would still be a sign of numerous population, but shooting the monster with a bow, gun whatever won't kill the whole population.

If it's not possible, then nevermind, it's still awesome addition to the current system!

**Comment by davidpwbrown** [comment]
> Can't you detach it? You said, that even without the monsters present, the water is still fishable to represent hidden population. What if the populations are hidden everywhere and from certain population size it will start spawning single monsters. So if you see a fish it would still be a sign of numerous population, but shooting the monster with a bow, gun whatever won't kill the whole population.
> 
> If it's not possible, then nevermind, it's still awesome addition to the current system!

Detaching the population from the monster and attaching it to the terrain itself is much trickier to code.
The terrain cant carry data like that currently, I tried with that abandoned snowfall PR I did.
It may be possible to do something like when a fish dies from a source other than fishing it spreads its "population" to other present fish but that could get very complicated very quickly.

**Comment by tinukedaya** [comment]
I see.. So.. what if: You have it the way you have it. But when the population is big enough, it will spawn normal "single entity" fish around it. a few of them maybe. That way you can increase the ability of the whole population to survive unorthodox (dynamite) fishing methods.

**Comment by davidpwbrown** [comment]
> I see.. So.. what if: You have it the way you have it. But when the population is big enough, it will spawn normal "single entity" fish around it. a few of them maybe. That way you can increase the ability of the whole population to survive unorthodox (dynamite) fishing methods.

When they die you mean? so killing a fish with a high population factor, spawns entities that have the divided up remaining population of the dead one?

**Comment by tinukedaya** [comment]
What I mean is that you have this one fish that carries the population. 

When that population is strong enough it will spawn another fish (a little chance of that happening every now and then) that will be just a monster as they are now.

So you will have a pond where you can see 5 fish "monsters". You are really hungry, but you do not have a fishing rod. You can hunt and kill that fish with a rock or whatever. And you still have only 1/5 chance of you killing the "mother" fish. If you are lucky you can return here later with the rod and do some proper fishing.

**Comment by tinukedaya** [comment]
> When they die you mean? so killing a fish with a high population factor, spawns entities that have the divided up remaining population of the dead one?

But this sounds quite ok as well.

**Comment by davidpwbrown** [comment]
> What I mean is that you have this one fish that carries the population.
> 
> When that population is strong enough it will spawn another fish (a little chance of that happening every now and then) that will be just a monster as they are now.
> 
> So you will have a pond where you can see 5 fish "monsters". You are really hungry, but you do not have a fishing rod. You can hunt and kill that fish with a rock or whatever. And you still have only 1/5 chance of you killing the "mother" fish. If you are lucky you can return here later with the rod and do some proper fishing.

Yeah the game already spawns new fish in bodies of water naturally, I dont wanna mess with that, cos it could go down a rabbit hole of balancing to make sure you arent creating population explosions.

In the future ideally yes, the population of a body of water would be done via the terrain or overmap data, but the code isnt ready for that, and I don't think I'm good enough to make it ready.
And trying to hack a facsimile of that by distributing the population attached to the monster to spawning new ones would create complexity that outweighs the amount of effort I want to put into fishing code by a large margin lol.

Your not wrong in what you envisage, it's just too much of an "ideal world" situation.

**Comment by tinukedaya** [comment]
:D Alright no worries! As I said, it's still awesome addition. If only for the fish variation!

**Comment by jeremyshannon** [comment]
I think a simpler (hackier) way to do it then would be to have the hidden population represented by a single "mother fish" that has debug_invulnerability and debug_invisibility. Maybe removing those mutations if the population is depleted.

**Pull request merged**
