### PR TITLE
fixed wings & mandible loop in insect

### PR DESCRIPTION
**Pull request by connorpmartin**
#### Summary
Bugfixes "Fixed wing and mouth mutation loop in insect"

#### Purpose of change

If you inject a bunch of insect mutagen, you'll constantly switch between insect and butterfly wings, and between mandibles and proboscis.
 
#### Describe the solution

Made the pre-threshold mutations (insect wings, proboscis) lead to the post-threshold ones.

#### Describe alternatives you've considered

Making all of these mutations non-purifiable and sticking them post-thresh, kinda like how Bird works with Hummingbird / Woodpecker beak.

#### Testing

Spawned in, injected insect mutagen, no more of these loops.

#### Additional context

There's still an ongoing issue with the toggle mutations (photopore, jekyll/hyde, hypermetabolism) which causes them to constantly switch between themselves and their "on" states as mutagen is injected. Photopore is particularly odd because you can actually develop multiple stages of photopores at once... I think the fix would require creating some tag to make the (on) mutations completely inaccessible by mutagen, which we don't currently have.

### CODE REVIEW

**Comment by Cactoideae** [comment]
Some lines have mutations that are supposed to alternate. Feline/Lupine has both pretty and ugly, for example. In this case, you are either an ant (insect wings + mandibles) or a butterfly (butterfly wings + proboscis). These are not supposed to be progressive.

The real bug is with photophores, extendable claws and other such things you've mentioned.

**Comment by connorpmartin** [comment]
That’s a fair point about the expected swaps when injecting mutagen.

The problem with making some of those mutations pre-thresh and some post-thresh is that some characters will transition between useless pre-reqs and real mutations. In this case, a mutant with another threshold will constantly swap between mandibles and not having mandibles on injecting insect mutagen. I think we’d rather have mandibles stay constant if a non-viable threshold mutation is the alternative.

Maybe it would be better to make proboscis and butterfly wings pre-thresh instead of these changes. We’d still get a loop, but it would work properly regardless of threshold status.

**Comment by Cactoideae** [comment]
It would be better to make post-thresh mutations ineligible if you don't actually have the threshold. The reason you keep gaining and losing mandibles when you aren't post-insect is the game trying to give you proboscis and removing mandibles to prepare for it, without realising that you will never get probosicis in the end.

Making butterfly wings and proboscis pre-thresh is wrong too. Insect already barely has any post-threshold mutations.

In either case, calling this a bugfix is misleading. Mutations rotating is the **inteded** behaviour, and whether or not it should change is up to debate.

**Comment by connorpmartin** [comment]
I’d say that there’s still a bug, namely that insect mutagen without threshold leads to these mandible-mouth flap loops. One option might be to remove the wing stub / mouth flap requirements from the post-thresh mutations, but that seems a bit hacky.

**Comment by Cactoideae** [comment]
There's no quick and dirty JSON solution here. The only proper fix is to fix the underlying C++ code so that it can't pick post-threshold mutations as targets unless the character has the threshold. If it can't pick butterfly wings as target, it won't remove insect wings in favor of wing stubs, because wing stubs "changes into" insect wings instead of just being a requirement.

**Comment by Salty-Panda** [comment]
Shouldn't the mutation doubling be fixed by #46507, at least fot photophore?

**Comment by connorpmartin** [comment]
That would solve the problem of getting both weak and strong photophores, but it doesn’t fix the problem of mutating photophores into their (on) counterparts. I’m betting that the change will also lead to photophore(on) changing to weak photophore(off) on injecting mutagen, since the changes_to isn’t defined there.

Either way, since these bugs don’t seem solvable with .json I’m going to close this PR.

**Comment by Salty-Panda** [comment]
The solution I can see is to rewrite active mutations to be handled in similar way to bionics.
So there is only one mutation, with specified active effects.
It could be done after planning out the future mutation rework as to ensure there won't be redundant work.

**Comment by connorpmartin** [comment]
> The solution I can see is to rewrite active mutations to be handled in similar way to bionics.
> So there is only one mutation, with specified active effects.
> It could be done after planning out the future mutation rework as to ensure there won't be redundant work.

yeah, the current mutation activation system is a bit hacky and I think it only lets you do instantaneous effects (like applying an effect or mutating something or w/e)

**Pull request closed without merging**
