### PR TITLE
Rename/Remove Some Gum

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove Some Gum Variants"

#### Purpose of change

The amount of gums we have is overwhelming to the point of causing UI issues. Please list what flavours I should readd, or should remove in the comments. 

#### Describe the solution

Reduce the amount of variants, and rename some of the existing ones.

#### Describe alternatives you've considered

Not doing this.

#### Testing

It is a draft.

### CODE REVIEW

**Comment by zachary-kaelan** [comment]
Are you going to be adding new gum flavors back to compensate for all the fun you're removing?

In all seriousness, I've only ever had bubblegum and spearmint, and didn't even know other flavors existed, maybe that's why some people's gum tastes like crap.

**Comment by DragonWizard23** [comment]
My personal favorite flavors are mint and cinnamon. Occasionally bubble gum or something fruity.

**Comment by DSeyka** [comment]
This issue has been raised before and I believe the solution is NOT to remove item variants, but to fix this on UI level.
https://github.com/CleverRaven/Cataclysm-DDA/issues/71066

**Comment by Theawesomeboophis** [comment]
I agree with the above, collapsible variants would solve the issue without making people upset. Maybe display it as Gum>number of variants and only show variants when uncollapsed manually by the player, like we do with other items after the charge removal.

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
