### PR TITLE
Adds priority flags for special placement

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change

Not having priorities is limiting

#### Describe the solution

Adds 2 new special flags PRIORITY_HIGH and PRIORITY_LOW which result in attempting to place the special before/after other specials
Isn't really ideal because it still checks all mandatory special occurrences first which I think means UNIQUE and GLOBALLY_UNIQUE only try after all of the mandatory occurrences
Applies the flags to some maps that probably benefit from it including most `"existing": true` road connections (which should hopefully help with clumping when they get shuffled to the front when there aren't many roads), removes the ability for isherwood farm to spawn over roads in exchange for giving it high priority

#### Describe alternatives you've considered

Making priority a numerical field

#### Testing

Idk how to test this if someone could suggest a proper test or a way to test locally that'd be great

### CODE REVIEW

**Comment by Maleclypse** [comment]
Hás conflicts to resolve.

**Comment by lispcoc** [comment]
I think this is an important feature to prevent refugee centers from being generated too far away, but are there any plans to resume development?
If there is no one else to start, I am thinking of taking over this.

**Comment by Maleclypse** [comment]
> I think this is an important feature to prevent refugee centers from being generated too far away, but are there any plans to resume development? If there is no one else to start, I am thinking of taking over this.

I believe the person who was working on this has experienced a life event such as a move and it is unknown when they will return.   I think if they don't respond today you can probably work on it.

**Comment by lispcoc** [comment]
I got it. If I don't get a response today, I'll try to reimplement it.

**Comment by Procyonae** [comment]
lispcoc is implementing this in #68389 instead

**Pull request closed without merging**
