### PR TITLE
Revert "Fixes infinite sleeping pill/chamomile tea bug" #78684

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Reverts #78684

#### Describe the solution
Reverts this fix as it broke things across the repo.  Broke more things than it fixed.

#### Describe alternatives you've considered
None

### CODE REVIEW

**Comment by moxian** [comment]
What things are broken, exactly?

**Comment by Maleclypse** [comment]
> What things are broken, exactly? And did you check that reverting the commit fixes those things? (Testing section is empty)

It broke every single comestible using EOCs in the repo.  Given that the item I was testing on a build from December 22nd worked until I updated my build an hour ago and now it can't be tested at all, I'm pretty certain this will at least improve the situation.


> p.s.: does this really require a full revert? Perhaps we can have a more small and targeted fix?

Probably can be more targeted but that would need to be someone else and since I can't work on anything I was working on the last few days until this is reverted at least in part I'm putting this up as an option.

**Comment by moxian** [comment]
Makes sense. In that case may I suggest removing the debugmsg and early return, while leaving the json changes and the comments in place?

**Comment by moxian** [comment]
P.s.: the comment https://github.com/CleverRaven/Cataclysm-DDA/pull/78684#issuecomment-2557977028 implies that there are no other consumables using EoC in repository. Is that incorrect? Can you give an example of such (outside of the one you're working on)?

**Comment by SariusSkelrets** [comment]
The blood of saints from XEDRA Evolved is one of them. It calls a EOC to check some things and act according to that.

https://github.com/CleverRaven/Cataclysm-DDA/blob/8bd4c5d584e6fd06a4de00414d4214ed72f81487/data/mods/Xedra_Evolved/items/comestibles/med.json#L70

**Comment by Maleclypse** [comment]
> P.s.: the comment [#78684 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/78684#issuecomment-2557977028) implies that there are no other consumables using EoC in repository. Is that incorrect? Can you give some examples of such (outside of the one you're working on)?

A plethora of items in MoM, Magiclysm and Xedra Evolved.  I just tested one of them from each mod and they all trigger this error message.

**Comment by Maleclypse** [comment]
> Makes sense. In that case may I suggest removing the debugmsg and early return, while leaving the json changes and the comments in place? (I know you said it gotta be someone else, but just putting it up as an option)

If you would like to suggest those changes in this PR I will happily commit them.  Internet is frustratingly spotty on my laptop right now but I can accept a change on the phone easily.

**Comment by moxian** [comment]
#78786

**Comment by Maleclypse** [comment]
Closing in favor of https://github.com/CleverRaven/Cataclysm-DDA/pull/78786

**Pull request closed without merging**
