### PR TITLE
Add a survival achievement

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Features "Add an achievement for surviving one day"

#### Purpose of change
Make it easier to implement achievements with a lower time bound, where you might expect to complete them at a certain time, rather than at an event.

For now, we work around the limitation by allowing unconstrained requirements that exist purely as triggers to reconsider the achievement.

#### Describe the solution
Add example "survive one day" achievement and the infrastructure required to support it.  Also, document this workaround better.

#### Describe alternatives you've considered
We could hook into a timer system to trigger achievements at the specific time, but for this "survival"-type achievement I actually prefer this solution for gameplay reasons (more satisfying to get the achievement as you wake up) and so I'll avoid the code complexity of timers for now.

#### Testing
Verified that the new achievement works in a unit test and in-game.

### CODE REVIEW

**Comment by CountAlex** [comment]
A good and obviously necessary infrastructure for achievments.
A bit weird to me it's bound to waking up but I guess it's limitation of registring events. A player might go 2-3 days without sleep at the start the game which would show up a bit strange.
And maybe you can add other surviving achievments like week, month, year, while you are at it?

**Comment by jbytheway** [comment]
I plan to add more survival achievements, but first I want to implement "hiding" of achievements, so the longer timeframe ones don't appear until you've completed the shorter ones (so that the achievements list doesn't get too cluttered).

**Comment by CountAlex** [comment]
> 
> 
> I plan to add more survival achievements, but first I want to implement "hiding" of achievements, so the longer timeframe ones don't appear until you've completed the shorter ones (so that the achievements list doesn't get too cluttered).

Do you mean it like a series of same theme achievments where at start you'd see 1 day badge you can get, on second day you'd see you can get 1 week badge etc.?

**Comment by jbytheway** [comment]
Yes, exactly.

**Pull request merged**
