### PR TITLE
Police stations: change wooden doors

### PR DESCRIPTION
**Pull request by aMegaSloth**
#### Summary
Bugfixes "Replace wooden doors with bar doors to cells"

#### Purpose of change
It doesn't make much sense that cell doors would be wooden doors surrounded by steel bars. This changes wooden cell doors to bar door style.

#### Describe the solution
Make a quick json edit to replace doors with a new type.

#### Testing
Load json in to fresh world. 
Seems to work fine.

### CODE REVIEW

**Comment by descan** [comment]
Modern police station holding cell doors tend to be metal or polymer solid doors, rather than the stereotypical bar doors.

**Comment by aMegaSloth** [comment]
> Modern police station holding cell doors tend to be metal or polymer solid doors, rather than the stereotypical bar doors.

Alright, I can swap it to a solid metal door, but doesn't that mean we should change the bar walls to something solid as well?

**Comment by descan** [comment]
Based on this photo, from this website, I'd say concrete - they're cinderblock construction, which isn't quite what "brick wall" means in-game. 
image
https://amentaemma.com/portfolio/town-of-east-hampton-town-hall-and-police-station/

It's from an architecture firm touting their work in a Connecticut town hall and police station. Other examples I could find of modern police stations are similar - solid metal doors with concrete, reinforced brick, or cinderblock walls. (usually with reinforced glass or polymer windows on the door, although I don't think there are doors like that in game - the closest would be a peephole metal door, which don't let you see in without interacting with them)

**Comment by aMegaSloth** [comment]
Now I could be wrong on this but I am looking at the metal door options and I dont think the metal door with peephole can be locked. Seems like a trade off we'll have to go with.

**Comment by NetSysFire** [comment]
Having a metal door with a peephole, just like some wooden doors do, could suffice here.

**Comment by aMegaSloth** [comment]
Alright, I changed the bars out to a simple concrete wall. I was debating on changing all the cell walls to be all concrete but brick is decent enough I think.

**Review by NetSysFire — APPROVED** [review]
Looks fine so far. I am a bit puzzled why you chose alpha instead of just plain a but this does not matter too much.
A thing for another PR is looking into the prison and also replacing doors where appropriate.

**Pull request merged**
