### PR TITLE
Added another Blacksmithing tool

### PR DESCRIPTION
**Pull request by Atsumari**
#### Summary

Content "Added blacksmithing item"

#### Purpose of change

Makes hammer's and axes realistically craftable.

#### Describe the solution

Changes recipes require a drift(spike like object to make holes in axe and hammer heads)

#### Describe alternatives you've considered

None

#### Testing

Made sure all recipes worked and game didnt crash

#### Additional context

image

### CODE REVIEW

**Comment by actual-nh** [comment]
Is this essentially an awl usable at high temperatures, or what?

**Comment by Atsumari** [comment]
> Is this essentially an awl usable at high temperatures, or what?

If the awl was 20 times its normal size. yeah.

**Comment by I-am-Erk** [comment]
Giant awl for hammering through hot metal. Love it.

**Comment by pehamm** [comment]
Does the drift recipe actually need toolsmithing proficiency? I assumed that one was reserved for more complex objects, while to my utterly uneducated eye this looks like a straightforward craft for a character that has the basics to be a blacksmith down.

Just a question, you know much more about your craft than I do. If you need to be careful about which metal you pick for the tool, that could absolutely justify needing toolsmithing to craft this.

**Comment by Atsumari** [comment]
> Does the drift recipe actually need toolsmithing proficiency? I assumed that one was reserved for more complex objects, while to my utterly uneducated eye this looks like a straightforward craft for a character that has the basics to be a blacksmith down.
> 
> Just a question, you know much more about your craft than I do. If you need to be careful about which metal you pick for the tool, that could absolutely justify needing toolsmithing to craft this.

You hit it on the head.

The drift requires a "tool steel" which is a significantly harder steel than normal and needs to be heat treated and annealed properly or it won't function correctly and might actually shatter in the most extreme cases.

**Comment by kevingranade** [comment]
Ideally before we get too much further into blacksmithing we can start differentiating steel types.  If nothing else tool steel and "the rest", but up to a handful of different types would be reasonable.

**Comment by Atsumari** [comment]
Yeah not a problem.

**Comment by kevingranade** [comment]
To clarify, I'm not asking for this PR, just something to start thinking about.

**Comment by I-am-Erk** [comment]
@kevingranade we're still getting the hissy fit before mergeable here, over astyle this time. Do you know how to fix?

**Pull request merged**
