### PR TITLE
More mutant traits, TCL scenarios, resubmitted

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Features "TCL Labs have mutant starts, mutant starts have more trait options"

#### Purpose of change
I wanted the mutated starts to have more options to choose from, there are a lot of cool mutations that can change up how you play. I also wanted to give TCL more options, mutant starts like the traditional labs. Since oldstyle labs are being phased out anyways a new lab mutant start will be needed.

#### Describe the solution
TCL is split into two types: TCL Staff, which allows Security, Medical Resident and Lab Technician like the old labs, and TCL Mutant, which allows Unwilling/Volunteer Mutants which get to pick mutations as traits. Both are now worth 8 points instead of 6, because TCL is significantly more challenging to escape than the traditional labs which were themselves worth 8 points.
Mutants get to pick a wider variety of traits as well.

#### Describe alternatives you've considered
This does run into an issue that trait-mutations cannot be purified and don't count towards thresholds. This was an issue before but adding more traits exacerbates the issue. It's probably not a big deal, and it could be explained away by some blob-magic/pseudoscience of it being "baked into your dna now such that even purifier won't help" and a "baseline" mutated trait is still an interesting limitation, so that you can't just take negative point mutations and purify them for ez points.
I renamed "essential" to "nonessential" in the TCL Staff starting scenario to match the flavortext of the old lab start, and it makes sense to me - if you were "essential", like one of the big name XEDRA scientists innovating mutagen, they'd want you to evacuate with them, but if you're just some security guard or hired help in the lab they don't need you that badly. But it's not necessary to the PR, I can revert it if needed.

#### Testing
I loaded this up in game, things are working fine and traits seem to be blocking each other fine. I made sure my c++ change worked too. 

#### Additional context
Resubmitted edition of #52668 due to it breaking for no good reason after I made a trivial change.

### CODE REVIEW

**Comment by KittyTac** [comment]
There is already the Extra Mutated Scenarios mod which I plan to update with some missing stuff but other than that, good idea.

**Comment by PatrikLundell** [comment]
Essential/non essential:
The interpretation is based on the context:
- Essential to the XEDRA project: evacuate
- Essential to the operation of the facility: keep at the location
- Not important to either: non essential, and evacuate if you're going down to a skeleton crew, and abandon if you're just saving the "important" (politicians, etc.) ones and throw the rest to the wolves.

The second interpretation is used e.g. when governments evacuate non essential staff from embassies in risky countries when the situation worsen, and I think that's the one originally intended. I'm not bothered by a change in meaning, though.

**Comment by anoobindisguise** [comment]
Hmm, I can't figure out this last error, previously it was talking about being unable to build a base commit but now it is bugging me about a general build matrix / GCC 7 and it's not totally clear what's going wrong.

**Comment by Saicchi** [comment]
> There is already the Extra Mutated Scenarios mod which I plan to update with some missing stuff but other than that, good PR.

Answer given in previous PR
>This approach is a bit different than extra mutated scenarios. EMS gives you the option of picking every trait - with no regard for the aforementioned statpoint bug, and also offers post thresh mycus mutations, this list is a little bit more curated. Also no options for post thresh, I think it's meaningfully different and just an expansion of what we already have in main.

**Comment by kevingranade** [comment]
The fact that this massively expands mutation selection at game start has somehow completely eluded me, that's a huge non-starter, we don't want people picking extensive lists of mutations at game start, it simply skips a huge chunk of game content and is a bad ui for it to boot.

**Comment by anoobindisguise** [comment]
> The fact that this massively expands mutation selection at game start has somehow completely eluded me, that's a huge non-starter, we don't want people picking extensive lists of mutations at game start, it simply skips a huge chunk of game content and is a bad ui for it to boot.

OK. I tried my best to exclude mutations that were just "upgrades" of existing mutations/traits such as better night vision, better chitin, etc but I would be happy to trim down the list more. What would you like me to remove?

**Comment by kevingranade** [comment]
Unless there's a compelling reason otherwise, everything.

**Comment by anoobindisguise** [comment]
I have cut down the list to the following.
"LIGHTFUR" - there are a ton of mammal lines that include fur, it's very likely an experiment would get this mutation when exposed to mutagens. A mammal equivalent to the existing Chitin option.
"HORNS" - likewise, there are a lot of horn mutations that this mutation is an intermediary.
"SMALL2" - Shows up in fewer trees but I believe it would be very fun to play a character who is tiny from the get-go, with all the limitations that would impose. It's a dramatic flashy mutation that would more fun to have from char creation.
"ROT1" - can take or leave this. I like the idea of starting with a mutation that is slowly killing you giving you an immediate goal (find a way to cancel it)
"PAWS" - common mammalian hand limitation, alternative to arm tentacles.
"HUGE" - for the same reason as SMALL2 being cool, freakishly huge would have a radical effect on how you play, majority of clothing and vehicles are no longer available to you making you have to work around those limitations, it would be a fun and novel character and is worth including imo.

**Comment by Maleclypse** [comment]
I think this is viewed very similarly to the Road Warrior and hardened survivor professions.  Anything that starts significantly down the progression path is going to be viewed with a jaded eye outside of mods.   So if I'm doing a mutant run but I can start with the equivalent of five mutagens worth of mutations, that's going to significantly reduce the gameplay before the end of the game.  If something was to put you significantly closer to going post thresh where now you only need a couple of serums instead of 5 or more serums, that's also drastically reducing gameplay.

**Pull request closed without merging**
