### PR TITLE
Update 22.json

### PR DESCRIPTION
**Pull request by BjoHart**
#### Summary

Balance "Increased the range of the .22LR ammo to make it actually useful in the game"

#### Purpose of change

The range of the caliber was much too small.
Even some bows can shoot further.
This does not correspond to reality, there shoots a .22LR caliber over 1000m.

#### Describe the solution

Raised the range of the caliber from 13 to 24.

#### Describe alternatives you've considered

No alternatives, .22LR rifles are complety useless with the low range.

#### Testing

No testing, just a raise in range.

#### Additional context

none

### CODE REVIEW

**Comment by anoobindisguise** [comment]
22lr has less range than 9mm, and 9mm has a range of 14. Therefore unless you want to rework range for every gun and completely rebalance tbe game on your own I'd recommend you only give a range bonus to the 22 rifles, the ruger 10/22 and marlin 39a. There is precedent for rifles giving more range to pistol bullets, see the cx4 storm for example.

**Comment by fairyarmadillo** [comment]
Don't most 22s have a longer effective range than 9mm irl? There's more powder in a nine but it's way bigger and falls off faster.

**Comment by BjoHart** [comment]
Dosen't the LR in .22LR stands for long range?
Anyway, i will try to give the rifles a range bonus. Thanks for the idea!

**Comment by Paprika-H** [comment]
> Dosen't the LR in .22LR stands for long range? Anyway, i will try to give the rifles a range bonus. Thanks for the idea!

LR stands for Long Rifle, not long range. And I think you're confusing maximum range with effective range. Yes, a .22 can remain lethal for over 1000m, but has a much shorter actual effective range.

**Comment by BjoHart** [comment]
I tried in the game to hunt small animals with a rifle caliber .22 LR.
Unfortunately I had zero success because the range of the rifle is only 13.
All the animals run away immediately before I even get close to range…

Does anyone else here use this caliber for anything?

I have a friend who is a hunter. He says that the range of the .22LR rifles is already very far. The energy of the shot just decreases …

**Comment by Paprika-H** [comment]
> I tried in the game to hunt small animals with a rifle caliber .22 LR. Unfortunately I had zero success because the range of the rifle is only 13. All the animals run away immediately before I even get close to range…
> 
> Does anyone else here use this caliber for anything?
> 
> I have a friend who is a hunter. He says that the range of the .22LR rifles is already very far. The energy of the shot just decreases …

In game I use it for stealth a lot, as a suppressor will make any .22 LR gun completely silent.

**Comment by BjoHart** [comment]
I close this request

**Comment by BjoHart** [comment]
> 22lr has less range than 9mm, and 9mm has a range of 14. Therefore unless you want to rework range for every gun and completely rebalance tbe game on your own I'd recommend you only give a range bonus to the 22 rifles, the ruger 10/22 and marlin 39a. There is precedent for rifles giving more range to pistol bullets, see the cx4 storm for example.

Do you know how to give the range bonus to the rifles?
Im new to modding the game...

**Pull request closed without merging**
