### PR TITLE
Container pocket weight limits fix

### LINKED ISSUE #41303: Canning pot can hold 25L, but only 1 kg.
# Describe the bug

Canning pot can hold 25L, but only 1 kg, which means it can only hold 1 liter of water.

# Expected behavior

It should be able to hold at least 25 kg.

# Screenshots

изображение

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3202-g401143b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Purpose of change
Fixes #41303
Seven cooking tool containers had pocket weight limit set too low at 1 kg which would not allow them to be filled.

#### Describe the solution
Changed pocket weight limits for a few items in dining_kitchen.json to 1 kg per liter.
Searched other json data files as well for the same issue and did not notice the same issue. 

#### Testing
Spawned canning pot and filled with water.

### CODE REVIEW

**Comment by FuelType-Memes** [comment]
1kg to 1L might be too low. Soup has higher density than plain water, I don't think that 25L of soup should cause a pot to break

Maybe 1L to 1.25kg for some overhead to include higher density liquids?

**Comment by RoyBerube** [comment]
You do have a point. I was trying to be consistent with other cooking containers which are mostly set to 1 kg per liter.

I'm thinking that is a balance issue that encompasses more than this fix addresses. The weight and volume balance of pockets is wildly inconsistent in the data files. To be consistent it would have to adjust much more than this fix. At least this gets the containers usable again.

**Comment by CodeBandit** [comment]
Density of water is 997kg/m^3. Density of sea water deep in the ocean under high pressures is 1050kg/m^3. The density of water-based liquid food items should then be inconsequential.

**Comment by meladath** [comment]
> 
> 
> Density of water is 997kg/m^3. Density of sea water deep in the ocean under high pressures is 1050kg/m^3. The density of water-based liquid food items should then be inconsequential.

Food generally contains solids, which are far more dense than even water at the very bottom of the ocean.

**Comment by CodeBandit** [comment]
Considering how containers don't only hold their weight in water, working it off of densities doesn't make much sense. This is analogous to a steel pan, holding only 1L, is only capable of holding 1kg (which is untrue).

**Comment by wapcaplet** [comment]
> Do we even model density and weight correctly for a lot of these items though? Has someone added in the density of every/most food stuff in the game?

The `data/json/materials.json` file includes a "density" field, but it's a simple numeric value and appears to bear no relationship to actual material density. For example "water" has a density of 1 while "wood" has a density of 4, and "wool" a density of 9. Furthermore, although the density value is read from the materials JSON, I don't think it is used anywhere - nothing in the source appears to call `material_type::density()`. The `src/item.cpp` file has had a `TODO: MATERIALS add a density field to materials.json` since 2013, so it's anyone's guess what the plan with that was.

But since every item has a "volume" and "weight", density can be calculated from that relationship. I would not be at all surprised if these were all over the place; when I made some recent changes to branches and logs, I found that the former "long stick" was more than twice as dense as most wood (1.4 kg/L).

I think 1kg / 1L is a good starting point for these containers, until items can be audited to know more about their actual densities. I may try to take this on with some Python scripting.

**Comment by Kelenius** [comment]
It shouldn't be 25 kg. Putting the limit on 25 kg means that you can't fill it with salt water, which is slightly heavier than regular water. Is it possible to just remove the limit? I don't know how much weight a 25L pot can hold exactly, and it's not really something that people measure, no to mention it massively varies depending on the shape, material, etc, but I believe that it's somewhere in hundreds of kilograms, and for practical purposes limitless.

**Comment by Kelenius** [comment]
Putting it this way, if you took a pot, and filled it with iron (much more dense than water), it wouldn't break under the weight, right?

**Comment by kevingranade** [comment]
I pretty agree, the weight limit should probably be optional and default to some very high weight.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Putting it this way, if you took a pot, and filled it with iron (much more dense than water), it wouldn't break under the weight, right?

It depends on material of the pot, its structure and how forces are applied: if you fill a pot with some rocks or sand while it stays on the ground - nothing bad will happen, but if you try to lift that filled pot using handles - it is totally possible that pot handles would fall off.

**Comment by mrkybe** [comment]
The only realistic case for max-weight applying is I think with plastic bags.  A shopping bag would rip if filled with mercury (~13g/cm^3).  A pot, if filled with mercury (don't do this) would be a pain to actually lift, but you wouldn't necessarily have to lift it by the handles.  You could carry it like you would a crate.

For reference, the densest material that exists at standard atmospheric temperatures/pressures is ~~redditors~~ [osmium](https://www.newscientist.com/article/mg20928026-900-eight-extremes-the-densest-thing-in-the-universe/) which comes in at 22g/cm^3.

**Comment by kevingranade** [comment]
Ehh, there are any number of containers that might be conspicuously fragile, keep in mind containers includes all kinds of things that CAN be used as containers but DEFINITELY would not be fit for purpose, and this provides a mechanism to make them appropriately suboptimal.
Plastic bags of all sizes.
t-shirt bindle
Paper bags
Condoms
Dress pants pockets
Cardboard boxes (think more macaroni box rather than shipping box)

**Comment by Kelenius** [comment]
Yes, weight limits make sense for cloth, cardboard, and plastic containers, but much less so for metal ones.

**Pull request merged**
