### PR TITLE
[CR] File linting and file rearrange

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Moved various definitions out of files in `mapgen` folder to dedicated files and linted some files.

* Item groups from files in `mapgen` folder moved to `/data/json/itemgroups/itemgroup_mapgen.json`;
* Monster groups from files in `mapgen` folder  moved to `/data/json/monsters/monstergroup_mapgen.json`;
* Vehicle groups from files in `mapgen` folder  moved to `/data/json/vehicles/vehiclegroup_mapgen.json`;
* Furniture from files in `mapgen` folder moved to to `/data/json/furniture.json`;
* Linted `/data/json/furniture.json`.

### CODE REVIEW

**Comment by kevingranade** [comment]
What's your goal here?  There's significant cost to moving data around in this kind of volume, and it doesn't seem to make any significant improvements in organization.

**Comment by Coolthulhu** [comment]
If it is to be considered for merging, it must be broken up heavily.
For example, the giant lint of furniture.json alone is too big to be a single PR.

> There's significant cost to moving data around in this kind of volume, and it doesn't seem to make any significant improvements in organization.

Centralized item/monster groups could be helpful with modding. It can be hard to find them all otherwise (requires greping the whole data directory for types).

**Comment by ZhilkinSerg** [comment]
> What's your goal here? There's significant cost to moving data around in this kind of volume, and it doesn't seem to make any significant improvements in organization.

I want to make data structure more clear for help with future modifications.

> Centralized item/monster groups could be helpful with modding. It can be hard to find them all otherwise (requires greping the whole data directory for types).

Yes, that is the point.

>If it is to be considered for merging, it must be broken up heavily.

I'd be happy to make changes smaller and easier for review, but it was just about moving the data and I  thought that it won't be an issue. How much of json data is okay to change in single PR? X files, Y rows?

> For example, the giant lint of furniture.json alone is too big to be a single PR.

It is not possible to lint part of the file (also doesn't make much sense), isn't it? All of the furniture is defined in one big file. Maybe I should split it to multiple linted files in several PRs?

**Comment by ZhilkinSerg** [comment]
Also I have an idea of replacing all of terrain/furniture definitions in mapgen files to mapgen_palettes. That should save up some disk space, but such changes will be rather big in terms of changed rows/files.

Should I consider several PRs, changing only several mapgen files per PR?

**Comment by kevingranade** [comment]
A vague, "maybe this will make things easier to find" is insufficient, unless you have a clear hierarchy where it's extremely obvious to modders where a particular entity will be, the file churn is unwarranted.

Additionally, this makes working on a specific mapgen strictly more difficult because now the data for a particular region are spread across many files instead of being concentrated in one.

**Comment by kevingranade** [comment]
Yes, ideally only one mapgen file per PR.

The requirement driving this is changes must be manually reviewed, anything
over a few hundred lines becomes difficult to review.

**Comment by ZhilkinSerg** [comment]
> A vague, "maybe this will make things easier to find" is insufficient, unless you have a clear hierarchy where it's extremely obvious to modders where a particular entity will be, the file churn is unwarranted.

`dda` does not have clear hierarchy right now - you can already put json objects to any file and in most cases the game will take it with no errors.

> Additionally, this makes working on a specific mapgen strictly more difficult because now the data for a particular region are spread across many files instead of being concentrated in one.

Maybe we should move all the definitions to mapgen files then and prevent using definitions from the outside?

**Comment by ZhilkinSerg** [comment]
>Yes, ideally only one mapgen file per PR.

Search ""mapgen"" (752 hits in 151 files)

That makes me very sad. Will someone review this number of PRs, say I create them?

**Comment by Coolthulhu** [comment]
You don't need to move all mapgen entries, though. At the moment just the monster and item group definitions.

Though it would be bad to consolidate them all in one file. A branching directory structure may be a bit harder to navigate, but much easier to modify without having to affect the whole file.
If it is all to be merged into one file per category, it would only be trading one problem for another.

**Comment by kevingranade** [comment]
> dda does not have clear hierarchy right now - you can already put json objects to any file and in most cases the game will take it with no errors.

This isnt about loading json, the game doesnt care where things are defined, this is strictly about contributors finding things.  As such you need to provide an organization that contributors can use to find things, if you dont have that, just leave things where they are now.

> Maybe we should move all the definitions to mapgen files then and prevent using definitions from the outside?

Some definitions are shared and some are unique to a particular mapgen file, the unique ones should stay in the file where they are used, and the shared ones can be in shared files.

>  Will someone review this number of PRs, say I create them?

We havent even established if this is worth doing.  It will be a huge amount of work to do it properly, and there needs to be a huge benefit to doing it.

**Comment by ZhilkinSerg** [comment]
> This isnt about loading json, the game doesnt care where things are defined, this is strictly about contributors finding things. As such you need to provide an organization that contributors can use to find things, if you dont have that, just leave things where they are now.

Yes, I understand that. Personally I would prefer to keep different types of json objects in separate files, so two types of organization comes into mind:

1. **Sort all json data by object type**. Rearrange all distinct json object types to separate folders/files, so there won't be different json object types in single file (i.e. move all item groups to separate folder).

* `/data/json/mapgen/house.json` - contains `house` mapgen;
* `/data/json/monstergroup/house.json` - contains `house` monster groups;
* `/data/json/itemgroup/house.json` - contains `house` item groups.

2. **Sort json data by usage area**. Rearrange json object by its usage (i.e. keep item groups related to mapgen in mapgen file itself).

* `/data/json/mapgen/house/house_mapgen.json` - contains `house` mapgen;
* `/data/json/mapgen/house/house_monstergroup.json` - contains monster groups for `house` mapgen;
* `/data/json/mapgen/house/house_itemgroup.json` - contains item groups for `house` mapgen.

**Comment by kevingranade** [comment]
> Personally I would prefer to keep different types of json objects in separate files

This is a preference, not a rationale for why it should be that way.  Both of the schemes you propose are frankly terrible because of your arbitrary preference for segregating json entities  by type.  With both schemes, the modder needs to either know both the type of entity and where it is located in order to find it, or they have to just search for it.

I strongly suspect that any scheme that tries to arrange json entities uniformly is going to be overall bad.  The natural relationship of *some* of these entities is that they are only used in one place, so that is the obvious way to arrange them.  The natural relationship of some other entities is that they are members of a general pool of entities that are used by many other entities, so it makes sense to group them together by kind.

I'm not seeing a plan here that would justify shifting all this data around.  I strongly suspect this is a matter of, "If it's organized it'll be better", but even if there's a slight improvement it's not worth the cost that would come with it, it needs to be an extrordinarally compelling reason, and I don't see one here.

**Comment by ZhilkinSerg** [comment]
@kevingranade, could you please explain what is the cost that would come with data shift? I really don't get it. Did you mean that it will be harder for contributors to find things or what?

**Comment by kevingranade** [comment]
The most immediate cost is that someone (most likely me) needs to review the change.
After that you have overhead from any pending PRs that edit the affected json developing conflicts that need to be manually resolved.
Additionally you have forks that aren't even PRs that may need to be manually fixed.

Also, I think all of the proposed changes will make things harder for contributors to find rather than easier, so IMO this is an expensive (in time) thing to do, and it has no payoff.

**Comment by ZhilkinSerg** [comment]
Thanks, I see now.

**Pull request closed without merging**
