### PR TITLE
Adjust MRE caloric value to reflect real MREs

### PR DESCRIPTION
**Pull request by DziugasPraninskas**
#### Summary

```SUMMARY: Balance "Adjust MRE caloric value to reflect real MREs"```
#### Purpose of change

Current MREs have 3211 calories worth of food in them. Real MREs have anywhere between 900 to 1400 calories worth of food, since soldiers are issued 3 MREs per day. Considering the MREs found in the game are regular MREs, they should also caloric value in that range.
#### Describe the solution

Remove excess food in MREs.
#### Describe alternatives you've considered

Not changing MREs.
#### Testing

1. Loaded up a game.
2. Disassembled a MRE.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I approve of this change even if it will make my characters sad.

**Comment by I-am-Erk** [comment]
We might consider bumping up mre spawns

**Comment by Mister-Cultist** [comment]
makes sense but consider making them more common if they're smaller

**Comment by FeedingWolves** [comment]
24 hour MRE's contain over 3000 calories typically. Judging by the amount of purification tabs and drink powders i always thought each MRE was supposed to be based on 24h packs.

**Comment by Rogal-Dorn** [comment]
> 
> 
> 24 hour MRE's contain over 3000 calories typically. Judging by the amount of purification tabs and drink powders i always thought each MRE was supposed to be based on 24h packs.

The United States doesn't have a 24 hour ration and the MREs ingame have names following the standard 1000-1250 calorie MRE menus. US rations also typically don't contain water purification tablets, but the ingame ones only have enough for 1.5 liters each which doesn't seem excessive at all. The US army recommends a soldier in combat drink over 4 liters per day.

**Comment by AlbertNewton** [comment]
Maybe we can replace most current MREs with MRE Packs, which would contain 3 MREs, with MREs and MRE packs combined still having about the same amount of calories found on average per place where they're found as before.
Current MREs would still of course spawn, but they'd mostly only spawn on zombies.

**Pull request merged**
