### PR TITLE
ZenFS' thick sidebar added

### PR DESCRIPTION
**Pull request by Zenefess**
#### Summary
Interface "Wide sidebar with detailed status displays"

#### Purpose of change
To add detailed sidebar options that take advantage of the current UI system.

#### Describe the solution
It's an extra sidebar layout option.

#### Describe alternatives you've considered
The current assortment of sidebars serve their purpose, but they are fairly basic. I wanted to see what could be done with the new UI system. None of the other default sidebars provide the player with as much information as this one.

#### Testing
I spent about a week developing, testing, sharing, and addressing feedback.

#### Additional context
Main panels:
Gozer _2024-01-20T15-52-00 panel1
Slim panel (v1.3.3):
image

### CODE REVIEW

**Comment by andrei8l** [comment]
Please use `math` instead of `compare_num`. The other widgets were recently updated so you have some examples and you can ping me if anything is not clear.

`compare_num` is a PR or two away from removal.

**Comment by Zenefess** [comment]
@andrei8l 
> Please use `math` instead of `compare_num`. The other widgets were recently updated so you have some examples and you can ping me if anything is not clear.
> 
> `compare_num` is a PR or two away from removal.

Hey, mate, I'm having trouble accessing the moon phase via math. The old way (eg. [ "moon", "==", { "const": 2 } ] ), no problem obviously, but directly using "moon" in a "math" entry always claims it's value is 0. encapsulating it as "u_val('moon')" throws an unrecognized number source error.
How do I access that variable inside a "math" entry?

**Comment by andrei8l** [comment]
> Hey, mate, I'm having trouble accessing the moon phase via math. The old way (eg. [ "moon", "==", { "const": 2 } ] ), no problem obviously, but directly using "moon" in a "math" entry always claims it's value is 0. encapsulating it as "u_val('moon')" throws an unrecognized number source error. How do I access that variable inside a "math" entry?

`moon` and other time stuff isn't ready yet, see #70996. You can leave those as compare_num for now. Thanks for porting the rest!

**Comment by Zenefess** [comment]
@andrei8l Hey, mate, maybe you can tell me what it's complaining about. First batch I uploaded had tabs but I've since replaced them all with appropriate spacing, and virtaully all of the changes recommended by the review bot looked identical to what I uploaded, but I confirmed it's alleged changes anyway.

What am I doing wrong? I was away from coding for 14 years, so maybe I'm just old & out-of-touch these days.

**Comment by andrei8l** [comment]
You have CRLF instead of LF line endings. Github has [a guide for that](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).

You can also use `json_formatter.exe` which is included in every release. On windows you can just drag & drop the files on top of the formatter exe AFAIK.

**Comment by ashGlaw** [comment]
Thanks for making this! I've been using it all day on my ultra wide monitor and it's lovely. The only things I'm missing are the Moves and a numerical temperature, other than that it's a treat

**Comment by Zenefess** [comment]
@ashGlaw
Thanks, mate. The most recent version has movement information in the status panel (under stats) and numerical temperature (as long as your character has an item with a temperature readout) in all environment panels. My github page will always have the latest build, so feel free to use that version until it's merged.

**Pull request merged**
