### PR TITLE
Fix CI failures, blazemod errors, fix speedloaders

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: None

#### Purpose of change
Fix CI failures.
Fix some issues from #34638

#### Describe the solution
Install time is commented out for all other gunmods, it doesn't appear to work.
One description was missing a space.
Add a default uncomfortable grip gunmod onto the remington 870 MCS. It is irremovable.

#### Testing
Ran `tests/cata_test`, noticed that it did not give me the errors it gave before I made these changes.

#### Additional Context
I want @tenmillimaster to give feedback before it is merged, so it's WIP. 
image

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Looks good.
Can't believe I missed a linting error.

**Comment by FuelType-Memes** [comment]
Can you also fix the description for "shot_speedloader8"? It says 6-shot instead of 8

**Comment by LaVeyanFiend** [comment]
> Add a default uncomfortable grip gunmod onto the remington 870 MCS. It is irremovable.
**irremovable**

Why? 😢

**Comment by anothersimulacrum** [comment]
Okay, all the tests pass, this is no longer WIP.

Not super happy with how I fixed the ranged balance tests, just felt like it was fudging with numbers. Not sure if there's a better way.

> Can you also fix the description for "shot_speedloader8"? It says 6-shot instead of 8. It's a really small copy-paste mistake, sad to create an individual PR for it

I'm not super happy doing a lot of stuff in one PR, I'm only doing the speed-loader fix in this because 10millimaster asked me to. I will do that in a separate PR.

> > Add a default uncomfortable grip gunmod onto the remington 870 MCS. It is irremovable.
> > **irremovable**
>
> Why? :cry:

The intent originally appeared to be including a permanent -6 handling modifier on the gun, this has the same effect.

**Comment by ThomasLinkin** [comment]
"Uncomfortable Grip"? dude, why does that exists in the first place? and if it actually "enhance" the recoil, why would anyone use it ?

**Pull request merged**
