### PR TITLE
Clarify world option city sizes

### PR DESCRIPTION
**Pull request by sparr**
#### Summary
Bugfixes "Rephrase city size options more accurately"

#### Purpose of change
Existing verbiage describes two sizes effectively equivalently ("twice as small" and "50% smaller") when they have different effects. Rephrasing makes them less ambiguous and more accurate.

#### Describe the solution
Replace "twice as small" with "half as large" for consistency, and "50% smaller" with "25% smaller" for accuracy.

#### Describe alternatives you've considered
I wrote a few other versions, and tried rephrasing other options to be more consistent with these, but none read as cleanly to me.

#### Testing
Loaded the game and viewed the options sliders during world creation.

### CODE REVIEW

**Comment by sparr** [comment]
While updating the translations for 50%->25%, I think I found a bunch with inaccurate info for the other half of that description (some say half as far apart, instead of 50% farther apart, or something equivalent). I also think some of the translations for the other string, "twice as small" vs "half as large" should be clarified like the original change here but I'm not confident enough in those languages, and a few of them also seem to contain mistakes.

I'm unsure of the best way to proceed on the localization front.

**Comment by GuardianDll** [comment]
I don't think you need to edit a translation files, they would be changed automatically
And translation.md point they must left untouched

**Comment by dseguin** [comment]
That's strange, this PR should have triggered a warning comment from #55922. In any case, you shouldn't need to modify the `.po` files since they're automatically updated from Transifex every week.

**Comment by sparr** [comment]
Do changes here also get pushed to Transifex? I'm not just changing the English strings; I'm also changing some of the translated strings.

**Comment by dseguin** [comment]
Yeah, sometime ago the translation infrastructure was overhauled (more than once). For every master branch build, [this workflow](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/push-translation-template.yml) updates Transifex with the new json strings, then translators will update the string for their locale, and on Fridays [this workflow](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/pull-translations.yml) creates a PR to overwrite the `.po` and `.pot` files with the updated translations.

Even though your changes here may be fairly obvious, they would be overwritten anyway the next Friday. Some of this is described in the comment in the failed test: https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3123878613/jobs/5066817951#step:2:99

**Comment by BrettDong** [comment]
Please don’t edit any translations in the Git repository. Translation updates flow from Transifex to GitHub one-way.

**Comment by sparr** [comment]
I've removed the translation commits.

**Pull request merged**
