### PR TITLE
Backport #76153

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Backport #76153

### CODE REVIEW

**Comment by Maleclypse** [comment]
@akrieger would this be a risky Backport?

**Comment by GuardianDll** [comment]
huh, what's with this error in basic build test?
image

**Comment by akrieger** [comment]
Well I wouldn't recommend it until I fix the tests on the original. Which tbh I don't understand why they are failing but there's a nonzero chance I just delete them because I am dubious about the assertion being useful.

**Comment by GuardianDll** [comment]
original PR suddenly transformed to the point i don't feel myself good enough to backport it on my own

**Pull request closed without merging**
