### PR TITLE
City size rng scaling balance

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Bugfixes "Changes rng city scaling to be consistent per scaling"

#### Purpose of change

Fix the rng per city size randomization to take into consideration the map's city size setting, instead of makig the smallest cities straight up size 1.

#### Describe the solution

33% of cities were being set to size of 1, regardless of city scaling setting.  The algorithm was originally intended to set them to 1/3 of size, not to 1.  so the algorithm was changed to match the rest of it.  (1/3, 2/3, 3/2, 4/2)

So when you have size 10 cities, you don't get size 1 cities with them, but size 3-4 small ones, so it scales properly.

#### Describe alternatives you've considered

Retaining size 1 cities, as a special.

#### Testing

Ran some maps, and noticed the smallest cities were scaling properly now.

#### Additional context

fixed number

### CODE REVIEW

**Comment by actual-nh** [comment]
> The algorithm was originally intended to set them to 1/3 of size

Might I ask where this info is from? Pull requests, or what? I'd like to take a look, particularly to figure out why it isn't doing any city sizes equal to the setting (+/- 1).

**Comment by stubkan** [comment]
> > The algorithm was originally intended to set them to 1/3 of size
> 
> Might I ask where this info is from? Pull requests, or what? I'd like to take a look, particularly to figure out why it isn't doing any city sizes equal to the setting (+/- 1).

There was a discussion on discord in dev help with kevingranade and he mentioned that was the intention.

**Comment by actual-nh** [comment]
> > > The algorithm was originally intended to set them to 1/3 of size
> > 
> > 
> > Might I ask where this info is from? Pull requests, or what? I'd like to take a look, particularly to figure out why it isn't doing any city sizes equal to the setting (+/- 1).
> 
> There was a discussion on discord in dev help with kevingranade and he mentioned that was the intention.

Got it. (I will get on the discord at some point - lack of time at the moment...) Any idea why it isn't doing any sizes actually equal to the setting (+/- 1)?

**Comment by stubkan** [comment]
> > > > The algorithm was originally intended to set them to 1/3 of size
> > > 
> > > 
> > > Might I ask where this info is from? Pull requests, or what? I'd like to take a look, particularly to figure out why it isn't doing any city sizes equal to the setting (+/- 1).
> > 
> > 
> > There was a discussion on discord in dev help with kevingranade and he mentioned that was the intention.
> 
> Got it. (I will get on the discord at some point - lack of time at the moment...) Any idea why it isn't doing any sizes actually equal to the setting (+/- 1)?

I guess by making it a fraction instead of changin the number by 1, you get more obvious differences in sizes, which leads to better aesthetic variety of sizes.   A city of size 8 looks very similar to a city of size 9.

**Comment by actual-nh** [comment]
I've put a Feature Freeze on this (anyone with triage+ access is, of course, free to remove it) because, in my experience, it tends to be especially hard to see things being off with a random number distribution being involved.

**Comment by stubkan** [comment]
> I've put a Feature Freeze on this (anyone with triage+ access is, of course, free to remove it) because, in my experience, it tends to be especially hard to see things being off with a random number distribution being involved.

What it did before went something like this

Place city
int size = rng( op_city_size - 1, op_city_size + 1 ); (picks a starting size which is a rng chosen -1 to +1 from specified size)
for 1 in 3 chance, make city size = 1
else 1 in 2 chance, make city size 2/3
else 1 in 2 chance, make city size 3/2
else, make city size times 2
std check size is 1 or more (so we don't get size 0.8 cities)

This change just makes the first line do make city size 1/3 instead of setting it to 1, other aspects are left alone.

**Comment by actual-nh** [comment]
> > I've put a Feature Freeze on this (anyone with triage+ access is, of course, free to remove it) because, in my experience, it tends to be especially hard to see things being off with a random number distribution being involved.
> 
> What it did before went something like this
> 
> Place city
> int size = rng( op_city_size - 1, op_city_size + 1 ); (picks a starting size which is a rng chosen -1 to +1 from specified size)
> for 1 in 3 chance, make city size = 1
> else 1 in 2 chance, make city size 2/3
> else 1 in 2 chance, make city size 3/2
> else, make city size times 2
> std check size is 1 or more (so we don't get size 0.8 cities)
> 
> This change just makes the make city size = 1 do make city size 1/3 instead, other aspects are left alone.

I can see your argument, but it still makes me a bit nervous, and it seems @Maleclypse agrees - @kevingranade, your thoughts?

**Comment by actual-nh** [comment]
A couple other thoughts:
- Shouldn't mongroups be proportional to city size (as in ~radius) squared - as in area - not directly to city size as per the comment and place_mongroups()?
- The distribution of city radius squared should actually be, for most cities, log-normal (see <https://www.hindawi.com/journals/isrn/2014/498125/> and <https://onlinelibrary.wiley.com/doi/pdf/10.3982/QE42>; from the latter, the proportion between before-exp mean and before-exp sigma should be something like sigma = mean/10).

**Comment by stubkan** [comment]
> Three other thoughts (which would _definitely_ need to be tested out in 0.F-dev...):
> 
> * Shouldn't mongroups be proportional to city size (as in ~radius) squared - as in area - not directly to city size as per the comment and place_mongroups()?
> * The distribution of city radius squared should actually be, for most cities, log-normal (see https://www.hindawi.com/journals/isrn/2014/498125/ and https://onlinelibrary.wiley.com/doi/pdf/10.3982/QE42; from the latter, the proportion between before-exp mean and before-exp sigma should be something like sigma = mean/10).
> * There also appears to be a bit of a problem with the distribution of numbers of cities per overmap - it's rather too similar, varying at most by +/- 1.

What do you mean?  Monster groups are placed in a circle that is slightly bigger than each citys size - what other way should it be?

I saw your other message about the improve gen project, and I'd love to be part of it but that one says its mainly about transferring gen to jsons, I want to fix the bugs and add features that make the gen not crap.

**Comment by actual-nh** [comment]
> What do you mean? Monster groups are placed in a circle that is slightly bigger than each citys size - what other way should it be?

Placement is not the problem. Zombie populations for cities are currently determined by elem.size * 80.
 
> I saw your other message about the improve gen project, and I'd love to be part of it but that one says its mainly about transferring gen to jsons, I want to fix the bugs and add features that make the gen not crap.

Understand. It seems to be potentially broader than that - see the "To do".

**Comment by stubkan** [comment]
> Placement is not the problem. Zombie populations for cities are currently determined by city size * 80. It should be city size squared (for area) times something (13-14, maybe?).

Oh, population.  I looked again, and I see what you mean now.  Nice spot.

**Pull request merged**
