### PR TITLE
Corrosive zed tweaks.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
As discussed in https://github.com/CleverRaven/Cataclysm-DDA/issues/14726.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Could it also get the barf attack to have something dangerous in melee?

**Comment by Rivet-the-Zombie** [comment]
Yeah, I can do something along those lines.

**Comment by Rivet-the-Zombie** [comment]
Gave them the extant ACID_BARF power and also removed their luminance value because none of our other acid related stuff glows in the dark.

**Comment by Coolthulhu** [comment]
That luminance thing was quite useful for marking areas with corrosives as "no go zones". Though the nerfs may make them safer now.

I remembered another problem with corrosives: they have huge melee values. I assume this was supposed to represent them melting walls, but our acid no longer melts non-fleshy stuff. This could be lowered too.

**Comment by Coolthulhu** [comment]
It has really low accuracy at range, might need a buff there later on.

**Pull request merged**
