### PR TITLE
Operation: Update TropiCata

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
TropiCata has been rotting for a long while. Which is a shame because the idea behind it is cool. Recently due to some of my other PRs I looked at its code and... it's barely held together. So here I am, trying to make it a mod people play more than once in 6 months.

#### Describe the solution
- Move the coordinates for sunrise to Central Brazil, also update the mod description to reflect that - literally all of the content here is based off South America. There's no point lying that it's some non-determined tropical region
- Edit the regional groundcover so it's not riddled with underbrush every two steps
- Remove the nonexistant mutant cactus ID from the regional settings so the game doesn't throw errors when generating a world
- Update the regional blacklist to include mutant moose, some non-native birds and amphibians, most vanilla fish (with the exception of the goldfish, european carp, rainbow trout, and american eel, which have small but technically present populations in Brazil)
- Cut out the wolves from the blacklist since they only spawn in zoos anyway
- Remove duplicate goldfish definition since I added one in vanilla ages ago
- Give the mod's monster factions some bases to work with so they function more dynamically in the world

**TODO**:
- [ ] Figure out why the hell there's no forests anywhere - **postponed until after #73602**
- [x] Annoy @Procyonae to know if there's a more sustainable way to list which overmap extras can spawn and which ones can't. Defining it manually isn't gonna go far if vanilla gets new ones...

### CODE REVIEW

**Comment by Karol1223** [comment]
@Xaritscin I'm gonna need to know if you're still active in the repo or not, because you've been MIA for like a year now

**Comment by Procyonae** [comment]
The only reason I stuck the coords in Central America was bc there was some interest at the time of actually mainlining the region a realistic distance to the south (with start scenarios) when we get the ability to have multiple regions but idk how realistic that happening is

**Comment by Karol1223** [comment]
> The only reason I stuck the coords in Central America was bc there was some interest at the time of actually mainlining the region a realistic distance to the south (with start scenarios) when we get the ability to have multiple regions but idk how realistic that happening is

I am still against sacrificing 50% of the mod content to move the setting elsewhere, personally. Let it stay a mod. There's no reason for it to be vanilla unless we want to simulate all of the US, Mexico, and all the way down to Nicaragua.

**Comment by Procyonae** [comment]
> I am still against sacrificing 50% of the mod content to move the setting elsewhere, personally. Let it stay a mod. There's no reason for it to be vanilla unless we want to simulate all of the US, Mexico, and all the way down to Nicaragua.

Well that would be the hypothetical idea ye c;
If the mod has alot of Brazil specific wildlife etc though that's cool, nothing made it particularly obvious if it was intended to be anywhere specific

**Comment by Karol1223** [comment]
> If the mod has alot of Brazil specific wildlife etc though that's cool, nothing made it particularly obvious if it was intended to be anywhere specific

It also has some wildlife from outside Brazil, admittedly (one species of crab), but it was the only region I could find that had most of the current mod content fit it.

Anywho, the question about blacklisting/whitelisting overmap extras stands.

**Comment by Procyonae** [comment]
> Anywho, the question about blacklisting/whitelisting overmap extras stands.

What differences do you want there to be between vanilla and TropiCata extras?

**Comment by Karol1223** [comment]
> > Anywho, the question about blacklisting/whitelisting overmap extras stands.
> 
> What differences do you want there to be between vanilla and TropiCata extras?

The point is - I don't think there need to be any? There might be some extras that wouldn't make sense in TropiCata, but most would. But if I'm reading the files correctly, currently in the regional settings there's a manually curated list of which map extras can spawn with the mod?

**Comment by Procyonae** [comment]
I'm using #73602 as a good excuse to go through and make most of the remaining region settings overlays instead so they don't need to maintain their own lists of city buildings and extras etc

**Comment by Karol1223** [comment]
> I'm using #73602 as a good excuse to go through and make most of the remaining region settings overlays instead so they don't need to maintain their own lists of city buildings and extras etc

Gotcha. I'll ignore that part for now then and let you take care of that in this case.

**Comment by Karol1223** [comment]
Since #73602 seems to be in limbo I'm gonna bite the bullet and get this merged in the current state. Doesn't fix all the issues I was hoping to tackle, but it at least makes the mod able to be loaded onto a world without an error screen so that's progress.

**Pull request merged**
