### PR TITLE
Fix: ellipsis width

### PR DESCRIPTION
**Pull request by bkentel**
The ellipsis was incorrectly getting a width of 1, not 2, causing it to be cut off a bit.

### CODE REVIEW

**Comment by KA101** [comment]
Translation people/Kevin, this a problem for the string freeze?

*KA101 thinks it shouldn't be, but then he's been wrong about stuff like that in the past*

**Comment by kevingranade** [comment]
In principle no, but this is also so minor it can just wait.

**Comment by BevapDin** [comment]
Since when is the ellipse 2 cells width, is there a standard reference for that? In my console (font DejaVu Sans Mono) it's exactly one cell width: 
screenschot-2015-02-25-06-01-26

**Comment by bkentel** [comment]
It's two cells on the windows SDL build (or at least it can't be rendered properly in one cell); it probably depends on one's font as well. If it works properly as one cell on a plain ncurses build, it could be conditionally two cells for non-ncurses builds.

**Comment by bkentel** [comment]
Or, some extra logic to force the last character of a truncated line to act as if it were a wide character?

**Comment by BevapDin** [comment]
> conditionally two cells for non-ncurses builds.

That could do. I can't reproduce the problem here, none of the three included fonts seem to even support that character. But what about adding code to the glyph cache that makes the character display correctly. Introducing logical differences between sdl and curses builds just asks for trouble.

**Comment by DavidKeaton** [comment]
DejaVu Mono represent son.

**Comment by DavidKeaton** [comment]
Could one not change the default render font to include ellipsis?

**Comment by KA101** [comment]
Any thoughts on #11501?

**Comment by bkentel** [comment]
@KA101 Not sure, but it could have to do with source file encoding during compilation? Maybe changing the inline "…" to its escaped utf-8 counterpart ("\xE2\x80\xA6") would help?

**Comment by DavidKeaton** [comment]
the end result is the same though, yes?

**Comment by bkentel** [comment]
It ought to be -- unless the compiler is treating the source as being encoded as anything other than utf-8 in the inline case.

**Comment by KA101** [comment]
OK, just wanted to check whether this would affect that.  (Browser problem: reading Git and pulling now happen on separate machines.  Gooo Mozilla.)

**Comment by bkentel** [comment]
Also, FWIW, this PR is still in limbo -- not sure how this should be handled. I think it's specifically a CJK font issue though.

**Comment by bkentel** [comment]
A screencap of the issue since I realized I never posted one:
ellipsis

**Comment by BevapDin** [comment]
Could it be that the ellipsis is two console cells width in that font? Because in my console and font it's only once cell width and the code that determines this (src/wcwidth.h) seems to agree.

The game also assumes that it's 1 cell width. If it's larger, the string must be shortened more.

**Comment by bkentel** [comment]
Right, which is what this PR attempted to do by increasing the ellipsis's width to two. Not sure what the best fix is though -- increase the width or increase how much strings are truncated (or conditionally do one of those based on locale?).

**Comment by BevapDin** [comment]
As this issue seems to be an SDL only thing (or am I wrong?), just make a global constant depending on whether it's SDL or curses that defines the width of the ellipsis and use this width to additionally truncate the string.

Or if it's possible to get this information from the font, get it from there, but that seems to be more trouble than it's worth.

Would work fine for curses as well and has only minor impact on the whole code.

**Comment by bkentel** [comment]
Probably an SDL issue, but I don't have a way to test a native curses build with a CJK font. Anyone able to test, say, the Japanese version on a linux curses build?

**Comment by DavidKeaton** [comment]
I could, but at DnD game. :-P

**Comment by bkentel** [comment]
@DavidKeaton Enjoy :+1: 5E?

**Comment by DavidKeaton** [comment]
well I say DnD, but I use it generally for tabletop fantasy. It's actually Pathfinder, based on 3.5. Played D&D 4.0, did not enjoy it, personally. :-)

**Comment by bkentel** [comment]
4E was pretty controversial, but from what I've heard 5E is a nice improvement (no personal experience though). Enjoy, and if you have time later the testing would be much appreciated.

**Comment by DavidKeaton** [comment]
I heard 5E was a nice improvement as well, and I can try to check the branch in Japanese today. :-) Simply need a check to see if your branch prevents that glyph error?
(Linux curses user here)

**Comment by bkentel** [comment]
@DavidKeaton Not so much that this PR prevents it, but rather that the problem exists on linux builds with a CJK font too.

**Comment by KA101** [comment]
Tried this and didn't have any ellipses to verify, so whether it eliminates 'em or I don't have any, can't pass it.  *shrug*

**Comment by jakwings** [comment]
This may be a problem for both console and SDL versons. I'm using iTerm2, and it provide an option to [treat ambiguous-width character as double width](https://github.com/gnachman/iTerm2/blob/35bfdc1d2e2e2aed05a6add20a9edb528a7748bf/sources/NSCharacterSet%2BiTerm.m). So it is better to provide such a option ingame too.

Here comes the screenshots:

When “Treat ambiguous-width character as double width” is off:
OFF

When “Treat ambiguous-width character as double width” is on:
ON

**Comment by jakwings** [comment]
I've added some notes on how it overlaps with another character.

You can modify the po file or pot file to get a long string and test in the tutorial mode.

**Comment by jakwings** [comment]
This is really a big problem for CJK translations. (Yeah, I have finally found out the reason of why my screen is not clear properly and leave lots of rubbish there.) :imp: 

As you can see from the screenshots above, the top and bottom borders of the frames are so smooth, right? But what I copy from the terminal is this:

```
┌───────────────┐
│ a使用         │
│ R読む         │
│ E食べる       │
│ W着る         │
│ w装備         │
│ t投げる       │
│ T脱ぐ         │
│ d置く         │
│ U取り外す     │
│ r再装填       │
│ D分解         │
│ =キー割り当て │
│ +自動取得     │
│               │
│               │
│               │
│               │
└───────────────┘
```
In case you don't have the proper fonts to show the glitches, see my screenshot:

2015-05-27_08_00_54-hd
“Treat ambiguous-width character as double width” is ON. (AND IT SHOULD BE, FOR CJK USERS!)

**Comment by kevingranade** [comment]
Seems reasonable, how do we do it in our code?  Is there a list of
ambiguous width characters or a call to check it for a character?

**Comment by jakwings** [comment]
@kevingranade I've found the list, but the real problem is harder than I thought before. A hard-coded list is not enough at all due to different font glyph design and how the game/terminal display different characters. So I have to put this problem away for now and put more energy into translating the game. :wink:

**Comment by kevingranade** [comment]
Looks like #12474 is what needs to happen for this issue, closing this one in favor of that issue.

**Pull request closed without merging**
