### PR TITLE
Add smaller plastic sheets and use them instead of plastic bags in most recipes

### PR DESCRIPTION
**Pull request by actually-a-cat**
#### Summary
Balance "Add smaller plastic sheets and use them instead of plastic bags in most recipes"

#### Purpose of change
Continuation of #57766 (I broke the PR by force-pushing to it while it was closed, oops)

There are many recipes that use substantial quantities of plastic bags for waterproofing. This is both nonsense (why are you using the flimsiest plastic available for your tent or armored clothing?) and annoying (plastic bags need to be collected one by one, often by dumping out their contents).

#### Describe the solution

Renamed existing plastic sheets to "large plastic sheets" and adjusted their weight and volume. Introduced new "plastic sheets" which are the same size as cotton sheets and serve a similar role in crafting, replacing plastic bags on a 1:1 basis. They have the same weight as plastic bags, but are thicker and smaller.

Large sheets remain ingredients for some larger items like constructions and tents, and plastic bags remain in food-related recipes. Sheets can be crafted into large sheets by taping them together with duct tape or by heat-pressing. Heat-pressing can also be used to fuse plastic bags into sheets.

#### Describe alternatives you've considered
The previous approach was to use existing plastic sheets, but they are just too big for most crafting projects, and it would have meant a lot of wasted and disappeared material.

I thought about also adding smaller plastic patches to mirror fabrics, but I can't actually find any use for them. 

#### Testing

Ran tests, loaded it in, looked at it in game. Simple JSON changes only so it's probably okay.

#### Additional context

Big thanks to fairyarmadillo and Zireael07 for contributions and helping me arrive at a workable approach.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
May as well add the heat-pressing here as it would be a tiny PR on its own. Just drop this in recipe_others?

The process [here](https://www.youtube.com/watch?v=787VpNLjpmY) shows a couple bags being used to make a sheet. The plastic sheeting he winds up with is sturdy enough to be used as a work surface or to make gear that won't rip, so I think a 4-ply (2 bags to 1 sheet) solution is a better idea than 2-ply.

`  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "small_plastic_sheet",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_MATERIALS",
    "skill_used": "fabrication",
    "difficulty": 1,
    "time": "5 m",
    "autolearn": true,
    "qualities": [ { "id": "CUT", "level": 1 }, { "id": "COOK", "level": 2 } ],
    "tools": [ [ [ "surface_heat", 5, "LIST" ] ] ],
    "components": [ [ [ "bag_plastic", 2 ] ] ]
  },
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "plastic_sheet",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_MATERIALS",
    "skill_used": "fabrication",
    "difficulty": 1,
    "time": "5 m",
    "autolearn": true,
    "qualities": [ { "id": "CUT", "level": 1 }, { "id": "COOK", "level": 2 } ],
    "tools": [ [ [ "surface_heat", 5, "LIST" ] ] ],
    "components": [ [ [ "sheet_plastic", 8 ] ] ]
  },`

**Comment by actually-a-cat** [comment]
>  The plastic sheeting he winds up with is sturdy enough to be used as a work surface or to make gear that won't rip, so I think a 4-ply (2 bags to 1 sheet) solution is a better idea than 2-ply. That also leaves room for some bag_plastic items being smaller than actual grocery bags.

Making it 4-ply is problematic because the weights and sizes are calculated around the assumption that garbage bags/sheets are twice the thickness of plastic bags. 

It would be plausible to make sheets thicker, but then they'd no longer be equivalent to regular garbage bags (at Hefty's, you need to go for "CONTRACTOR EXTRA THICK" to get bags that thick), and being able to use garbage bags is kind of the point of this whole business. 

Making plastic bags thinner is more of an option, but everything I find on google tells me the current value is about right. (Unfortunately I don't have a scale sensitive enough, or enough plastic bags, to see for myself)

**Comment by fairyarmadillo** [comment]
Makes sense. Just adjust the bag count down if you want to use the recipe in this PR then.

**Comment by fairyarmadillo** [comment]
We could leave it for another PR, but I just realized there's a distinct plastic_shopping_bag item. I thought it was supposed to be one of those reusable bags but I think it's just one of the disposable HDPE ones. We should probably have it be usable in the heat-pressing process, it's roughly the right size as described, though its dimensions might need adjusting in the code. Ziplock bags would also work as they're LDPE which mixes with HDPE just fine, though they're smaller so maybe it should be a 2:1 or 4:1 ratio. Could even just go in the same recipe as an alternative to the generic plastic bag.

**Comment by fairyarmadillo** [comment]
We could leave it for another PR, but I just realized there's a distinct plastic_shopping_bag item. I thought it was supposed to be one of those reusable bags but I think it's just one of the disposable HDPE ones. We should probably have it be usable in the heat-pressing process, it's roughly the right size as described, though its dimensions might need adjusting in the code. Ziplock bags would also work as they're LDPE which mixes with HDPE just fine, though they're smaller so maybe it should be a 2:1 or 4:1 ratio. Could even just go in the same recipe as an alternative to the generic plastic bag.

**Comment by Zireael07** [comment]
@fairyarmadillo just so you know, the game doesn't differentiate between types of plastic (cf my contribution of plastic molds for making small plastic items such as bottles/bags)

**Pull request merged**
