### PR TITLE
Give messenger bag to Vengeful Preacher

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: None

#### Purpose of change
This profession lacked sufficient storage for their items.  This was causing CI failures in the Magiclysm tests.

#### Describe the solution
Provide a messenger bag to resolve that.

#### Describe alternatives you've considered
A different bag.  But messenger bag was suggested (mostly for pun reasons, I suspect).

#### Testing
Relevant unit tests now pass locally.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
#41912 ZS beat you to it.

**Comment by anothersimulacrum** [comment]
#41912 ZS beat you to it.

**Comment by jbytheway** [comment]
Oh well.

**Comment by jbytheway** [comment]
Superseded by #41912.

**Pull request closed without merging**
