### PR TITLE
Add support for OSX cross-compilation from Linux

### PR DESCRIPTION
**Pull request by patternoia**
A first step to bring all the builds under the same roof. @narc0tiq we could implement these cross-builds on Jenkins, if this will get merged.

Though I thoroughly tested this PR on my machines, I can not guarantee that it will not break Linux and Windows builds. Lets cross fingers.

This PR also adds appdist target which packages the `.tar.gz` archive of Cataclysm.app instead of `.dmg` image. This is due to lack of `hdiutil` program on linux distributions.
The compilation documentation as well received an update.

### CODE REVIEW

**Comment by BrettDong** [comment]
OSX is renamed to macOS by Apple, so maybe we should change it either in the document?

**Comment by patternoia** [comment]
Speaking of this, we still are not supporting macOS 10.12, since all the builds target current OS X 10.11.6 EL Capitan at most. Thus support for macOS is unofficial.

**Comment by BrettDong** [comment]
I mean, Apple changed the name of this operating system series to macOS, so
it's better to follow this change.

**Comment by remyroy** [comment]
It might be possible to [create DMG on linux](https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform). That should be the preferable distribution format.

**Comment by patternoia** [comment]
Dropped `appdist` target and supported the `dmgdist` target for cross-compilation.
To create compressed dmgs on linux `genisoimage` and `dmg` from [libdmg](https://github.com/planetbeing/libdmg-hfsplus) are chosen.

**Comment by remyroy** [comment]
Well done! I'll see if I can do a quick review of this one soon.

**Comment by patternoia** [comment]
God damn, did I screw rebase?

**Comment by remyroy** [comment]
I guess you did screw this branch. Can you try to clean it up so I can test and review the changes?

**Comment by patternoia** [comment]
This PR is moved to #19559

**Pull request closed without merging**
