### PR TITLE
Require grenades and other explosives to be wielded before activation

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Interface "Require grenades and other explosives to be wielded before activation"

#### Purpose of change

When grenades or other explosive devices are `a`ctivated, their countdown timer begins immediately, even if they are inside a pocket or backpack. This becomes a problem when `d`ropping or `t`hrowing them, since it requires precious seconds to take them out of the pocket first - *while* the countdown is in effect. With a timer of only 3-5 seconds, this can cause unintentional self-destruction, especially if the explosive is nested inside a couple containers.

The correct thing to do is first `w`ield the explosive, then `a`ctivate it. This incurs no further movement cost for dropping or throwing it. However, this fact is not obvious to new players (and even experienced players may forget from time to time).

#### Describe the solution

Add `"need_wielding": true` to the `use_action` for grenades, pipe bombs, dynamite and other explosives, so they cannot be activated unless they are currently wielded.

Also document the `need_wielding` field in `JSON_INFO.md`.

These explosives now require wielding before activation:

- can bomb
- dynamite
- dynamite bomb
- EMP bomb
- primitive demolition charge
- improvised demolition charge
- flashbang
- fungicidal gas grenade
- makeshift fungicidal gas grenade
- makeshift gas canister
- grenade
- EMP grenade
- incendiary grenade
- canister grenade
- tear gas grenade
- insecticidal gas grenade
- makeshift insecticidal gas grenade
- bootleg grenade
- improvised grenade
- primitive grenade
- molotov cocktail
- bootleg pipe bomb
- improvised pipe bomb
- primitive pipe bomb
- scrambler grenade
- smoke bomb
- small bootleg frag device
- small improvised frag device
- small primitive frag device
- rocket candy

For these three, due to their large size (50-100L),  instead of `need_wielding`, I gave them the `ALLOWS_REMOTE_USE` flag, so they can be activated on the ground:

- ANFO charge
- improvised barrel bomb
- bootleg barrel bomb

These explosives have dedicated `use_action` iuse flags, and do not require wielding before activation (left as-is):

- acid bomb
- c4
- firecracker
- pack of firecrackers
- packed M72 LAW
- mininuke

#### Describe alternatives you've considered

Instead of making the user wield the item, it would be nice to have a prompt, such that when an item with `need_wielding` is activated, the player is prompted to first wield it. This would complicate things a bit, since there may then be another prompt for what to do with whatever you are already wielding, but would probably be a better long-term solution requiring fewer keypresses.

#### Testing

Debug-spawn various explosives, and try to `a`ctivate them when they are not wielded - you should see a message like `You need to wield the grenade before activating it.`

Then, `w`ield the explosive, and `a`ctivate it again. You should get `You pull the pin on the grenade` or whatever the appropriate message is for that explosive. 

#### Additional context

There is a discrepancy in movement cost with `need_wielding`, depending on whether the item is activated directly from the inventory, or separately from the `a`ctivate menu.

If you go to `i`nventory first, then select the grenade (in a pocket) and press `a` to activate, it does not work - you will get the "You need to wield the grenade" message, and no time passes.

However, if you press `a` to bring up the activation menu, the grenade is selectable (even though it won't work). When selecting the grenade in this case, the "You need to wield the grenade" message is correctly shown, but 8 seconds of time pass anyway.

Furthermore, if the item is wielded, then `a`ctivating it (lighting the fuse or pulling the pin) takes 0 time.

### CODE REVIEW

**Comment by Alex-Folts** [comment]
Is this really nessesery? Game is turn based, player have much time to think what he is doing, no rush. Also game sort of roguelike so we learning by dying, so next time wont do something stupid.

Just my personal thoughts.

**Comment by cainiaowu** [comment]
Game is turn based, but unavoidable death due to single wrong keypress is not good game mechanics.

**Comment by Alex-Folts** [comment]
If there was difficulty level, such auto safety features supposed to be on easy difficulty.

**Comment by cainiaowu** [comment]
Accidental death does not add difficulty, only tedium.

**Comment by IIverner** [comment]
I think we should use a security model to check for risky behavior

**Comment by Mecares** [comment]
I won't be able to light a stick of dynamite in a bag full of dynamite and throw the entire bag?

**Comment by Alex-Folts** [comment]
> Accidental death does not add difficulty, only tedium.

It is not accidental, just count actions you need to do to perform it, it is not 1 key press fail. Accidental is when you crafting explosive and fail and it all explode, also this is realistic.
Also, you still can instead of throwing activated explosive, use drop action by mistake and you drop it right under your feet, will fix this too?

It is not about this particular fix nor this PR, its about setting a vector where such changes lead, what next, respawn feature, because someone spend 40 hours on character and then did mistake and died in one of thousands possible ways...

Did anyone advocating this fix even died like this?

**Comment by Fosheze** [comment]
I get @Alex-Folts reservations on this and to @Mecares point, this is removing a possibility from the player which I personally am never a fan of. What if instead of making it impossible to activate the grenade in the pack, simply give the player a prompt to wield the grenade at the start of the action? This would also have the added benefit of making it require slightly fewer key-presses to use grenades. 

A person most likely is never going to pull a grenade out of their pack, pull the pin, then shove it back into the pack but they could so the option should still be available. Remember at one point there was an issue posted where activated explosives in NPC or animal inventories didn't go off. Sometimes players just want to do weird things so we should never entirely remove those options.

**Comment by RecycledSail** [comment]
I can get what @Fosheze try to say, but there should be two yes/no prompt because you need to determine to wield grenade and determine to activate grenade inside inventory (we should add this because the safety is the main goal of this PR) and that is, pretty sure, nullify the benefits you are saying.

If you really want to add safety only then you can have a prompt like "Really activate grenade?".
However I like that little quality of life that you have fewer keys needed to be pressed, so I think @wapcaplet idea is fine.

**Comment by wapcaplet** [comment]
> It is not accidental, just count actions you need to do to perform it, it is not 1 key press fail.

@Alex-Folts You can very easily make a 1-keypress fatal accident with the current grenade-activation system, if the total time needed to wield the grenade is longer than the grenade's countdown timer. The player is not always informed of how much time is required for wielding, unless they are specifically using the `w`ield menu. When activating a grenade from the "Use item" menu, or from the "Inventory" screen, the number of moves is *not displayed*.

So, if you have a grenade in a cardboard box in a backpack, and go to the `w`ield menu, you can see it will take 642 moves (over 6 seconds) to wield it:

image

But if you simply go to the `a`ctivation (Use item) menu, you will have no idea:

image

Pressing enter here, the grenade will explode immediately. And if you activate it from the `i`nventory screen, at first you may think you're OK, but you will no longer have time to drop or throw the grenade before it explodes.

> Sometimes players just want to do weird things so we should never entirely remove those options.

@Fosheze This PR does not prevent you from blowing yourself up if you want to. Just wield the explosive, activate, and wait. All this change does is prevent accidental detonation.

Pulling the pin from a grenade that is tucked away inside your backpack (at the same time you're wielding some other item in your hands) is not just weird, it is impractical and unrealistic. You need your hands free to pull the pin or light the fuse.

> I won't be able to light a stick of dynamite in a bag full of dynamite and throw the entire bag?

@Mecares You can still do this, as long as you're willing to spend the moves to put the lit dynamite back in the bag before throwing it (and you have enough strength to throw a bag full of dynamite far enough away to avoid getting blown up).

**Comment by Alex-Folts** [comment]
> image
> 
> Pressing enter here, the grenade will explode immediately. 

This sounds broken. There is no timer for grenade in inventory, so instead of being frozen in time it just explode immediately? Or it assume that you get grenade from inventory, pull pin, and put it back?

>And if you activate it from the `i`nventory screen, at first you may think you're OK, but you will no longer have time to drop or throw the grenade before it explodes.

This is not as bad as previous case, at least you have some time.  In this case you left with activated grenade in your hand, or in inventory?

I think procedure should be like this: you press activate when grenade in inventory(intentionally or by mistake), game check if one of hands empty, game put grenade in your hand and pull pin, and at the end of action you left with activated grenade in your hand, grenade have full time before explode, so you have time to throw it.

**Comment by wapcaplet** [comment]
> This sounds broken.

I agree, in fact the `a`ctivation moves take effect even if you *cancel* the activation (which is noted in #42893). But this problem with activation moves is a separate problem than what I'm trying to solve here, which is to simply prevent accidents.

> I think procedure should be like this: you press activate when grenade in inventory(intentionally or by mistake), game check if one of hands empty, game put grenade in your hand and pull pin, and at the end of action you left with activated grenade in your hand, grenade have full time before explode, so you have time to throw it.

That would definitely be a more player-friendly way to do it. As mentioned in the alternatives I considered, this would involve adding a Yes/No prompt for what to do with anything you may currently be wielding. Such behavior could be a follow-up to this PR, changing the way the `need_wielding` field works so that wielding would be automatic upon activation. There are dozens of other items using `need_wielding` however, so I want to be sure it doesn't adversele affect those before doing such a radical change.

**Comment by Kenshkrix** [comment]
> This sounds broken. There is no timer for grenade in inventory, so instead of being frozen in time it just explode immediately? Or it assume that you get grenade from inventory, pull pin, and put it back?

What happens is you immediately pull the pin on the grenade (with telekinesis) and then reach in and take it out of the bag and wield it.
In some cases the time it takes to remove it from the bag and wield it is longer than the fuse so it explodes before the player can do anything else.

**Comment by Alex-Folts** [comment]
Now it finally make sense
> What happens is you immediately pull the pin on the grenade (with telekinesis) and then reach in and take it out of the bag and wield it.

This is bug/broken behavior, and this PR is kind of hack to prevent executing broken behavior. Well at some point need to fix the bug itself.

**Pull request merged**
