### PR TITLE
[DISCUSS] Disable recipe memorization from books

### PR DESCRIPTION
**Pull request by kevingranade**
This is built on #7814 and adds removing support for learning recipes just from reading since the rest of the PR is uncontroversial and this is.

### CODE REVIEW

**Comment by KA101** [comment]
Hmm, looks like this wasn't hugely controversial.  I'd thought I approved of the idea.

**Comment by kevingranade** [comment]
I'll rebase it tonight, likely to have grown monster conflicts.

**Comment by OzoneH3** [comment]
Is there still a way to make this work, or can ot be closed?

**Comment by kevingranade** [comment]
It's basically a todo, it needs to be open or replaced with an issue.

**Comment by kevingranade** [comment]
Obsoleted by #16564

**Pull request closed without merging**
