### PR TITLE
Fix build error on cygwin.

### PR DESCRIPTION
**Pull request by karols146**
Make cygwin to work on gcc 5.3.0.

### CODE REVIEW

**Comment by karols146** [comment]
have no idea why got check failed. All working for me. 
Fixes #17138

**Comment by BevapDin** [comment]
> have no idea why got check failed

All changes to the Makefile trigger a build error on the build bot for security reasons. Nothing you can (or need to) do about it.

**Comment by karols146** [comment]
Thanks for info @BevapDin

**Comment by kevingranade** [comment]
What's the build error? Generally we are going to want to stick with std=c++11 on all platforms.

**Comment by karols146** [comment]
[here](http://image.prntscr.com/image/28016ae99de74d1884f13ec40ac2382f.png)

**Comment by kevingranade** [comment]
Ok wow, that's not a mess I want to dig into, so I'm going to merge this.  It's nicely limited to Cygwin builds, thanks for that.

**Pull request merged**
