### PR TITLE
Added Bō to weapons

### PR DESCRIPTION
**Pull request by VarrenKrytor**
#### Summary
Balance "Adds the Bō and nerfs Quarterstaff and it's related weapons"

#### Purpose of change
With all Quarterstaff weapons becoming non-durable and being seen as more of a stick that you carved, I wanted to introduce a proper weapon in this category: the bō.  It's much harder to make and takes more time, but it retains the stats from the original Quarterstaff.  I also nerf the Quarterstaff and it's related weapons by putting their 'balance' to neutral since they are not crafted with skill and would not be well balanced.

#### Describe the solution
Create a recipe that gives the players the ability to make a well crafted and traditionally used quarterstaff, the bō.  Nerfs quarterstaffs further to be more in line with a stick hastily carved into a staff.  The end result is a bō that functions exactly like the old quarterstaff, with much harsher crafting requirements.  From my reading on the matter (and personal usage of a bō) this should be realistic.

Also updated descriptions of all quarterstaffs and the ability to use the bō for training purposes.

#### Describe alternatives you've considered
Leaving things as they are.  But with the quarterstaff nerfs my updated descriptions should probably be kept at the very least, and maybe even my nerf to their to_hit since they would no longer be well-balanced.

#### Testing

Tested and working

#### Additional context
This is my first weapon addition, critique it harshly.  Currently failing tests that don't seem to be related.  Probably needs to be re-run.

### CODE REVIEW

**Comment by Dandy-boy** [comment]
For the Bō's description, you should add a period to the end and change that "finally" to "finely" (i assume this was just a typo).

**Comment by VarrenKrytor** [comment]
Tested and working.

**Comment by CosmicHitman** [comment]
The quarterstaff has the rapid strikes technique but the bo staff does not. Is this intended? (this is not a critique, just a double check)

**Comment by VarrenKrytor** [comment]
> 

This is intended.  As someone who has used the Bo, it doesn't really swing quicker like a dagger might.  You could argue that a poking attack was faster, but you still need to pull back a decent amount to do any damage.  It's also heavier than it might look.

**Pull request merged**
