### PR TITLE
[CR]DinoModv2 "Dinos inna woods!"

### PR DESCRIPTION
**Pull request by LyleSY**
Adds compies, gallimimus, titanis, spinosaurus, ankylosaurus, and eoraptor to spawn in forests. Includes domestic group as prep to add dinos there (not yet implemented). Restores vanilla snippets to game in addition to DinoMod content. Adds new dino content to lab notes. Overall, you see more dinos and more written content.
From playtesting, the extra spinosaurus can add some difficulty, but it isn't game breaking, comparable to moose.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Looks like you copied the entire snippets.json, increasing the size of the PR by 1500 lines.
Snippets are added, not overwritten.

**Comment by LyleSY** [comment]
@Coolthulhu Yes, in my testing all vanilla snippets disappeared when DinoModv1 was enabled, similar to how monsters works. Applying the same principle, I just pasted the contents of the vanilla snippets file at the end and it worked as intended in testing. Nothing against the new mod content, but it gets very repetitive. I applied this same approach with lab notes.

**Comment by LyleSY** [comment]
Thinking more about the snippets.json issue, would it be possible to create a snippets_mod group that would drop in modded content in if mods are enabled, instead of overwriting the file? It may be that I'm trying to solve a larger problem with how mods are handled by the game. If so, could I just do that within the json, or would that group need to be created in the source?
I also have an idea to potentially cut some bloat from this clumsy approach (remove snippets classes that DinoMod isn't calling, if there are any). I'll look at that.

**Comment by LyleSY** [comment]
I've updated snippets and lab notes to follow standard mod guidance.

**Comment by LyleSY** [comment]
My next idea is to start including zombie dinos. I may introduce fungal dinos also if that goes well. Just waiting on this to merge.

**Comment by ZhilkinSerg** [comment]
Marking as Stalled. Feel free to reopen it.

**Pull request closed without merging**
