### PR TITLE
Adds the first fungal house!

### PR DESCRIPTION
**Pull request by zdlpoppa**
#### Summary
Content "adds a new fungus infested mapgen"

#### Purpose of change
Fungal building are lacking; heavily. It's been 5 years since the fungal towers had been updated, and that was more so changes then it was content. While this is a relatively small, and exceedingly small change (due to my lack of knowledge on mapgen), this is yet another first step for a future for more fungal updates.

#### Describe the solution
Add the first fungal-infested house, to better introduce the mycus as a threat inside cities, but also introduce marloss evangelists as well, since they can potentially spawn inside fungal buildings. This also introduces the more unique fungal zombies inside buildings, since before now besides fungalize_into, they had no way of spawning. Hopefully in the future, there can be improved, larger, and more interesting variants of fungal buildings.

#### Describe alternatives you've considered
Potentially adding more houses in one PR, but I didn't want to scope creep, and this PR is closer to a 'base' of what a fungalized house should look like.

#### Testing
I've done some pretty thorough testing, and haven't gotten errors on load, and could spawn the correct om_terrain without any errors as well.

#### Additional context
The rooms are barren, but you can see that the random generation of the fungus actually does pretty decently.
image

### CODE REVIEW

**Comment by IdleSol** [comment]
Is this house going to appear next to the mushroom tower? It's not going to randomly appear in any town, is it?

Because he's a potential source of mushroom spread throughout the city.

**Comment by zdlpoppa** [comment]
> Is this house going to appear next to the mushroom tower? It's not going to randomly appear in any town, is it?
> 
> Because he's a potential source of mushroom spread throughout the city.
It is intended to randomly appear in towns, however it is considerably rare. also, through a bit of testing, you won't really need to worry about a huge fungal outbreak.

**Comment by IdleSol** [comment]
Question: is it possible to create a function or eoc that will instantly infect omt with a normal <s>home</s> tiles? In my opinion, it would reduce the amount of work significantly.

And if it is tied to a mushroom tower, then great in general.

**Comment by zdlpoppa** [comment]
> Question: is it possible to create a function or eoc that will instantly infect omt with a normal home tiles? In my opinion, it would reduce the amount of work significantly.
> 
> And if it is tied to a mushroom tower, then great in general.

Possibly? But that would take a lot more then I personally know how to do. I don't really want to entertain the thought for this type of PR, though.

**Pull request merged**
