### PR TITLE
A zombie in every house

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Balance "Increase the likelihood of zombies spawning inside houses"

#### Purpose of change
I come here to fulfil my campaign promises.  A zombie in every house and a feral in every kitchen.  Well there isn't a zombie in every single house and only a small percentage of houses will contain a feral but both have had been added to houses overmap terrains. I believe there are probably some issues lying around that this would impact as far as improving zombie density in houses.  Specifically, this change addresses the fact that apparently no one died at home during the cataclysm.   Previously the vast majority of zombies spawn in the streets, in special locations and in basements.   By addressing this at the overmap tile it randomizes where zombies appear which often results in zombies in yards instead of in houses, but because this is a big change I went a little hyperbolic in the title block.  

#### Describe the solution
Adds a high percentage to spawn a small number of zombies in every housing overmap terrain. When taken in combination with the recent spawn deductions in overmap specials this should be considered more of a redistribution of those removed spawns.   

#### Describe alternatives you've considered
Creating individual spawn chances in each room of house mapgen with low percentages.

#### Testing
I've played this for several hours and it definitely makes each house a more complicated decision to approach in daylight.   At nighttime the PC still has the advantages of darkness, even if they are more likely to enter houses that contain zombies.  In my testing closer to 3/5th's houses contained zombies than the 4/5th's you would assume from the 80% spawn chance.

### CODE REVIEW

**Comment by Maleclypse** [comment]
This is probably one of the largest changes possible done via a single line of json.   There is realistically no amount of testing that I can do to determine the ultimate impact of this change.  I've done my testing and it makes the early game harder but not insurmountable, other players mileage may vary.    I imagine this will need refining after merging.

**Comment by NoahGoldFox** [comment]
This does not seem like a balanced or good idea for the game. It would totally destroy being able to stealthily night raid the outskirts of town and is just anti-fun.

**Comment by JosephJomama** [comment]
Can you elaborate a little more on the "purpose of change" section? Why is this a good addition to the game?

**Comment by Maleclypse** [comment]
In my testing I remained able to stealthily raid houses on the outskirts in daytime as long as long as I kept it short and sweet and didn't expect to be able to go through the entire house in one go, then frollick along to the next house down the street.   Nighttime raiding remained much easier than the daytime raiding.   But both were still feasible.

**Comment by bombasticSlacks** [comment]
this is really spicy 🔥

**Comment by AcidAntOnAMinefield** [comment]
Wasn't the lore changed from "everyone died because nukes and china" to "everyone became infected by "the magic blob", then crazy, and some people died"? If so, then why would there still be people in the houses, when (again, according to the lore) everyone went crazy, riots started and they just went down on everyone else? 

Don't misunderstand me, I am not against the houses having some population - on the contrary, this is a welcomed change - but it should be a really, really tiny chance of that happening. That or, if you really want to be "fair", instead of adding Zombie spawns to the houses, just add random human corpses on the floor with a "faster" revivification rate, from 1 to 4 corpses, maybe more if that can be done based on number of beds for example). That way the player will have some "challenge" to their looting, but it won't be in the form of a fully healed dead creature that overtime as evolution happens may become an impossible thing to deal with.

**Pull request merged**
