### PR TITLE
Small Typo Fixes

### PR DESCRIPTION
**Pull request by chaosvolt**
Apologies for this, as most of these typos are likely my doing. Even then, the Saiga typos might have occurred via copying and editing the AK-74M mag. Mentioned in https://github.com/CleverRaven/Cataclysm-DDA/issues/15244
- AKM Magazine: Description mentions AK-74M instead of AKM. I'm assuming this one was a fail on my part.
- Saiga-12 Box Magazine: No period at end of description.
- Saiga-12 Drum Magazine: Same as with the box mag.
- STEN Magazine: "based of the magazines" Based off, based on, or based off of would sound better. My bad.
- AK-74M Magazine: No period at end of description, this one's likely my fault.

### CODE REVIEW

**Comment by kevingranade** [comment]
I wasn't kidding, go away.

**Comment by Darkyhard** [comment]
What's wrong with him?

**Comment by karols146** [comment]
What's wrong with that pull  ?

**Comment by Night-Pryanik** [comment]
@kevingranade how about looking at the PR itself, not the people who opened it? Especially if there's no whining or awful attitude in text or comments?

**Comment by kevingranade** [comment]
He's been banned from the project, end of discussion.

**Pull request closed without merging**
