### PR TITLE
Zombie drops balancing

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Balance "Balance default zombie drops."```

#### Purpose of change
Addresses #28072.

#### Describe the solution
Lowered chance to spawn multitool from 20% to 5% and knives from 10% to 5%.
Lowered chance to spawn any item from 75% to 50%.
Lowered chance to spawn `default_zombie_items_pockets` items inside `default_zombie_items_bags` group from guaranteed 100% to 50%.
Both cellphones and smartphones now have an even chances to spawn: (90% of fully discharged and/or 10% of 0..15 charge). This way most of the phones will spawn empty, and only a handful will have a small charge in them.
Added a 10% chance to spawn permanent marker.

### CODE REVIEW

**Comment by Mcrone617** [comment]
Yeah this seems solid, and hopefully should cut back on how quickly you get loot, while still making the system more realistic than before when you could get televisions dropping from zombies.

**Comment by I-am-Erk** [comment]
Love the changes. 

I'd suggest that phones should spawn several times more frequently, and the chance of them being charged should be significantly lower. So mostly they'll be just a junk item, but a common one.

If I got zombified I'd probably still be carrying my phone through my entire undeath, out of muscle memory alone.

**Comment by Squishums** [comment]
Great changes. I love the more sensible drops, but swimming in multitools really shortened the early game.

Maybe not the place to ask, but I'd love if Permanent Markers could be added to the drop table. It's a possible pocket item, and I feel as if the item labeling and note mechanic in the game could be more accessible. Knives only work on certain materials.

**Comment by I-am-Erk** [comment]
Permanent markers! I keep forgetting those when I'm trying to think of pocket contents for NPCs

**Comment by Night-Pryanik** [comment]
> Permanent Markers could be added to the drop table.

Done.

**Comment by ZhilkinSerg** [comment]
Merged to `0.D` (and `master` with with #28097).

**Pull request closed without merging**
