### PR TITLE
Reduce Wasps Nest spawns in forests

### PR DESCRIPTION
**Pull request by JonathanLochridge**
#### Summary
Balance "Reduced Wasp Nest spawns in forest."

#### Purpose of change
Complaints about too many wasps after wasp towers added and the difficulty of spotting them at a safe distance.
At least partially fixes issue #52773  
Of note is the original implementer of Wasps mentioning their spawn frequency should be reduced in regards to forests.

#### Describe the solution
It reduces the rate at which wasp nests are spawned in forests.
Forest tiles at the edge of a forest were cut less since they should be easier to spot.
So, this should result in them serving more as an obstacle to avoid. Than something you stumble into and die as soon as you discover it. 
Swamps rates were unaffected since they are expected to be more dangerous areas.
And plains make up a small percentage of total wasp nests already.
This should result in less wasp nests.

#### Describe alternatives you've considered

Complete removal of nests from deep forest segments. To still preserve their effect of blocking forest paths.

A smaller reduction of the chances of every spawn location for wasp nests.
However, this might result in less frequent spawn locations almost never spawning reducing variety more than total occurrences. 

#### Testing
I ran the JSON through the cataclysm linter and found no change when checked against the code. 
I ran a fresh catalcysm game and drove around with the debug clairvoyance mutation to give perfect spot rates so I could spot wasp nests more reliably and explored an area to get their occurrences. 

I found 1 dermatik and 1 normal wasp right next to each other in the woods across a larger stretch between 2 cities(encountered at 10 out of 30 minutes driving)
I also found 1 field wasp but I didn't touch their spawn rates.
Overall I covered about as much ground as I generally would in 2 days of scouting early game assuming I got a bike sometime in there.

I didn't find any wasps on roads that cut through woods or in the section when I went in the woods. Not sure of an effective way to survey large a amount of wood tiles. Maybe a debug spawned roller or deathmobile that can force it's way though a whole forest?

I got the following error after about 20 minutes of searching when I went by a crater:
I get similar duplicates for other locations. But the same terrain codes.

"
 DEBUG    : Setting terrain t_open_air at (131,40,0) where furniture is f_rubble_rock.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint&, const ter_id&)
 FILE     : src/map.cpp
 LINE     : 1756
 VERSION  : f1997bf
"

#### Additional context
I am unsure of the amount it is reduced by is the amount that others working with bugs want this to be reduced by. 
Are we aiming to have 1 wasp nest average for large forest? Or more like 1 in 2 or 1 in 3. I would estimate that with the new code they should be in like 1 in 3-4 forests based on the number I was able to survey. Which would put them as being roughly in 1 in 2 forests or more originally. I also noticed some clumping in my test of the vanilla.
Which also occurred. Usually when there is a forest wasp nest there is at least 1 other within a couple tiles. (I only know of 4 examples from recent builds. But I think that is enough to concerned over but not confirm anything.)  I still need to match the times involved for vanilla testing to get a more accurate experiential comparison.
I am thinking of maybe scaling it back to be halfway inbetween old and new values on another day when I have time to test it.

### CODE REVIEW

**Comment by NetSysFire** [comment]
>DEBUG : Setting terrain t_open_air at (131,40,0) where furniture is f_rubble_rock. Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

Thanks for playtesting thoroughly! Fortunately this is not caused by your work.
See #54092

You are also missing the quotes in your PR summary.

**Comment by Maleclypse** [comment]
@Venera3

**Comment by Maleclypse** [comment]
I'm wondering if we can change the mapgen for these to only generate after like day seven or something like that?

**Review by Venera3 — APPROVED** [review]

**Comment by Venera3** [comment]
It would probaby be doable to hook up the map extra to spawn a queen, and the queen to build different configurations of the nest depending on passed time with effect_on_conditions' map updates, but I haven't had the time to look into them properly.

I think you could reduce the wasp "house" (`mx_house_wasp`) spawn as well in there, they probably shouldn't thrive around zombos. I'm half a mind to restrict that to rural houses, honestly.

**Comment by Zireael07** [comment]
> It would probaby be doable to hook up the map extra to spawn a queen, and the queen to build different configurations of the nest depending on passed time with effect_on_conditions' map updates

Out of scope for this PR, however ;)

**Comment by Venera3** [comment]
Oh, obviously, just thinking out loud. 

You don't have to worry about clumping and such, that's just how map extras are - we generally don't have a framework for tiles to know *anything* about other tiles, so it's unavoidable for now. Half as common in light forests and quarter as common in thick ones looks reasonable.

**Comment by JonathanLochridge** [comment]
I noticed that dermatiks only spawn at the water tiles in the forest according to the code? Is this intentional? 
I made an a adjustment there and think that the amount is about right.
But, another approach might be to let them spawn more places with lower frequency?
@Venera3

**Comment by JonathanLochridge** [comment]
This is High Tyrol From the discord for purposes of getting discord colors from this PR.

**Comment by LyleSY** [comment]
Yes, water forest means swamp tiles, I was confused too

**Pull request merged**
