### PR TITLE
Adds 2 farms

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content "Adds 2 new farms```

#### Purpose of change
There were not enough farms in New England to feed it's residents. I also changed stuff, that seemed weird to me in the overmap. 

#### Describe the solution
 -Added 2 farms, a farm with stills and an ordinary one modelled after 7d2d
 -Rural houses now generate in a normal way. (Like gas stations)
 -Campground now far from town and in forests
-State parks are now in forests
-Motels are now next to roads, like gas stations
-Gas stations with garages are now more common and can also be found in the wilderness
-Railroad stations are now less common

#### Describe alternatives you've considered
Not changing it. It's not an important update.

#### Additional context
No screenshots this time. I let you explore the farms and the other ones are already in the game.
I may have ruined the ```specials.json``` because I linted it. Idk my computers skill is just 2

### CODE REVIEW

**Comment by ifreund** [comment]
I'd recommend reverting all the changes in `specials.json` and opening a separate PR for those without linting (it's on the `json_blacklist` and shouldn't be linted).  It's best to keep PRs as self contained as possible.

**Comment by paulenka-aleh** [comment]
Could you also make railroads unavailable with city size = 0? They do look bizzare when neither roads nor railroads are present. Seems to be in line with your changes.

**Comment by I-am-Erk** [comment]
Love the additions based on a scan. I'd really recommend including a screenshot or two, you could always put them behind a link for spoilers but it would be nice for file review.

**Comment by Night-Pryanik** [comment]
And I recommend splitting your BIG PR into smaller chunks, based on their content. PRs with line count more than 1000 are really hard to review.
It seems that you're changing things not directly related to the farms in this PR. Narrow the changes to the farms, and open new PRs with changes to rural houses, gas stations and others.

**Comment by I-am-Erk** [comment]
I think it would all be manageable as a single PR if specials.json wasn't listed. Unfortunately you really have to unlint it, we can't see what changes you made because the whole file registers as changed from the linting.

**Comment by LovamKicsiGazsii** [comment]
My bad. Creating another branch.

**Pull request closed without merging**
