### PR TITLE
Add sharp rock recipes

### PR DESCRIPTION
**Pull request by Rail-Runner**
Allow making some stone items using sharp rock just like a regular rock.

### CODE REVIEW

**Comment by KA101** [comment]
Not totally sold on the fire drill, maybe the shovel, but apart from that, this looks OK.  Any other opinions?

**Comment by Rivet-the-Zombie** [comment]
I'd say no to the fire drill. The rock used in it is for a socket that you hold in your hand while steadying the drill. A sharp rock would hurt your hand.

**Comment by Lain-** [comment]
Agree with what Rivet said, other than that I like this PR!

**Comment by Coolthulhu** [comment]
Will it make ceramic shards totally useless? (I count making arrows of them as uselessness - tainted bones are free)

**Comment by Darkyhard** [comment]
Done.

And no, it won't make ceramic shards useless. I made this to add some kind of use to sharp rocks if you already have a better butchering tool and don't want them lying around.

**Comment by KA101** [comment]
Ceramic can be produced, sharp rocks not so much.  I think this can make it.

**Pull request merged**
