### PR TITLE
Get rid of uses of chemistry set as tool instead of quality+hotplate

### PR DESCRIPTION
**Pull request by Coolthulhu**
Converted some remaining recipes to use chemset+hotplate tools rather than direct usage of chemset. This was done for most recipes with the addition of basic chemset, but some recipes were skipped during that update. I don't see a good reason to keep them that way and I see a good reason to allow them to use other hotplates: convenience of not having to use a separate tool with separate charges.

Also, vehicle mounted chemistry set could be removed and just replaced with the RV version + basic chemset spawn on it. It doesn't really offer anything above RV+chemset since CHEM quality split.

### CODE REVIEW

**Comment by Darkyhard** [comment]
I think that these recipes involve electrolysis, and that's why they were using chemistry set charges and not hotplate charges. Heating up water and obtaining acid as a result is weird.

**Comment by Coolthulhu** [comment]
But chemset is literally just a bunch of flasks, rubber hoses and a hotplate.

**Comment by baraba3** [comment]
...and some copper wires which are i presume for electrolisis.

**Comment by Rivet-the-Zombie** [comment]
>I think that these recipes involve electrolysis

This is exactly why.

**Comment by Coolthulhu** [comment]
Which ones of those involve electrolysis?
Ammonia has scrap, so it probably does involve it.
Bleach is most likely the chloralkali process, so electrolysis.
I'll revert those two.

But sulphuric acid and acid water?
Acid water just makes acid from water. Is this a thing IRL or is it pure video game logic? Or does it involve leaching something from dirt or something like that?
I can't find anything about the sulphuric acid+hydrogen peroxide, except that they are used together to clean organic contaminants.

**Comment by Rivet-the-Zombie** [comment]
>Acid water just makes acid from water.

Hydrogen electrolysis from water: water around the anode is H positive, or acidic, while the water around the cathode is H negative. Kept apart with a conductive separator, they don't mix and neutralize themselves.

**Comment by Coolthulhu** [comment]
> Hydrogen electrolysis from water: water around the anode is H positive, or acidic, while the water around the cathode is H negative.

What kind of acid does it produce?

**Comment by Rivet-the-Zombie** [comment]
Given the list of ingredients, oxalic acid via electrosynthesis CO2 reduction seems the most likely candidate.

**Comment by Rod-Serling** [comment]
I thought we were basically concentrating the acid already present in the water from the portal pollution that happened during the cataclysm?

**Comment by Zireael07** [comment]
@baraba3: Copper wires are there to hold the flasks together with the hoses. Search for chemistry set on Wikipedia :)

**Comment by kevingranade** [comment]
Can we do "CHEM" : 3 and give that to the chemistry set instead?  It seems like the adjusted recipes are intended to use the chemistry set specifically, and having a higher quality would document that better.

**Pull request closed without merging**
