### PR TITLE
add raisins as a new food item

### PR DESCRIPTION
**Pull request by juur**
#### Summary
Content "Add raisins"

#### Purpose of change

Add raisins (dried grapes) into the game, hopefully to allow delicious fruit cake and scones to be created to distract the zombie horde.

#### Describe the solution

I added them to be used alongside dry_fruit and grapes, as I thought appropriate.

#### Describe alternatives you've considered

Not having raisins, which made me cry.

#### Testing

Booted and spawned.

### CODE REVIEW

**Comment by LordBarkBread** [comment]
Raisins I hadn't thought about them tasty treats!
Any plans to add a recipe(s) to make raisins using a dehydrator or smoking rack, or any thoughts to add raisins as recipe components for a few existing meals/foods? Or is this just right now to get them into the game with more thoughts later down the road?

**Comment by juur** [comment]
> Any thoughts on making a recipe to actually make raisins, be it dehydrator or smoking rack, separate from just getting "dehydrated fruit"

Sure. I like small incremental changes as it's something I can do in an evening or whatever, plus once it's in, others can (more easily) build on it.

**Comment by PatrikLundell** [comment]
There is JSON support for assigning specific names for specific versions of a base product. That kind of logic has been used to call various mixtures of booze different things. I suspect that logic might be possible to apply here.

**Comment by juur** [comment]
> There is JSON support for assigning specific names for specific versions of a base product. That kind of logic has been used to call various mixtures of booze different things. I suspect that logic might be possible to apply here.

That would be useful for sultanas and currants (and green Vs black grapes) but not sure for the base raisin?

**Comment by Rokharn** [comment]
What, exactly, is the difference between dried grapes and raisins? Maybe better to correct correct ingame dried grapes and not create new item?

**Comment by juur** [comment]
> What, exactly, is the difference between dried grapes and raisins? Maybe better to correct correct ingame dried grapes and not create new item?

There aren't any explicit dried grapes (raisins) in the game. Or I've wasted my time and missed them :)

I'm unsure of the difference between American Vs British use never mind other counties so have been using the terms interchangeably a bit...

**Comment by PatrikLundell** [comment]
I am not aware of raisins being anything other than dried grapes either in English or my native language (there's something called corinths which are smaller dried grapes used for some cooking purposes).

Regardless, dried grapes do exist in the game in the form of dry_fruit (grapes). They're found by looking up "id": "grapes" in raw_fruit.json and then find the "smoking_result": "dry_fruit", line. There are also manual smoking recipes that take grapes (as one of many options) and produce dry_fruit. Note that dry_fruit retains info about where it came from when smoked or produced by a recipe (I think the generated ones are generic without a source, though).

**Comment by juur** [comment]
> I am not aware of raisins being anything other than dried grapes either in English or my native language (there's something called corinths which are smaller dried grapes used for some cooking purposes).
> 
> Regardless, dried grapes do exist in the game in the form of dry_fruit (grapes). They're found by looking up "id": "grapes" in raw_fruit.json and then find the "smoking_result": "dry_fruit", line. There are also manual smoking recipes that take grapes (as one of many options) and produce dry_fruit. Note that dry_fruit retains info about where it came from when smoked or produced by a recipe (I think the generated ones are generic without a source, though).

In British English raisin is specifically for dark dried grapes, vs sultanas vs. currants.

Dehydrated fruit (which is what I think dry_fruit (grapes) is - made via smoking rack) are not the same as dried fruit which is not (always) the same as raisins: https://en.wikipedia.org/wiki/Raisin explains the process, which is not in anyway the same as the process with a f_smoking_rack. For example, the same page on Wikipedia confirms that there is still some residue water in raisins, which doesn't tally with the negative quench for dry_fruit (grapes).

I think based on this raisins are unique and not just dry_fruit. That said, I am not that bothered if people don't think it worth introducing them (and thus any more complex recipes or items that use them)

**Comment by PatrikLundell** [comment]
Raisins contain some moisture, that's true, but not enough to compensate for the sugar (and other stuff) in it (salt water contains a lot of water, but it doesn't quench the thirst anyway).

I believe the dried fruit you get from smoking racks to be dried fruit with a bit of moisture left in them, corresponding to dried meat. The second pass on meat makes it dehydrated, and I would expect a second pass on fruit to result in fruit flakes, had it been implemented.

**Comment by juur** [comment]
I don't agree that smoked grapes are raisins. Firstly, the process outlined per Wikipedia is quite complicated involving additional chemicals. As a second data point https://countrywoodsmoke.com/smoked-grape-waldorf-salad/ shows smoked grapes. These are nothing like raisins.
But I've already put more effort into explaining my PR than writing it so I'll leave it now.

**Comment by Qrox** [comment]
> the process outlined per Wikipedia is quite complicated involving additional chemicals

The mentioned process sounds like it should apply equally to other fruits though. The pre-treatment tries to improve the dehydration rate because grape skin have wax and is adapted to prevent water loss, but other fruits (such as apple) also have wax layers, so I think dehydration of any fruit should also have this step.

The drying process is simply removing water, so whether it's heat drying or freeze drying or mechanical drying shouldn't have much difference that is worth modeling in the game. If we can track how a particular batch of dried fruit is made, we can add a conditional name to call grapes dried using a specific set of steps "raisin" but we should probably stop there to avoid introducing too much verbosity to the game.

The post-drying process is simply cleaning and grading, which need to be done for any dried fruit anyway (our survivor might just skip the grading step though).

**Comment by Montimorency** [comment]
Why FREEZERBURN?

**Pull request closed without merging**
