### PR TITLE
Make the fourth tier of vampirism possible to obtain + add related NPC

### PR DESCRIPTION
**Pull request by SariusSkelrets**
#### Summary
Mods "(XE) Allow vampires to reach the fourth tier and add vampiric mentors"

#### Purpose of change

I am adding the requested content for the fourth tier of vampirism, including the mission by which you reach that point

#### Describe the solution

Add a way to become a tier 4 vampire, following the guidance @Maleclypse gave me on what was wanted for that

- [x] Added the mentor + dialogue
- [x] Got the mentor to spawn in some vampire-filled churches
- [x] Talked to the mentor + test of all choices
- [x] Reached tier 4 through murder of cherishing NPC
- [x] Made mentor not attacked by vampires, made player almost not attacked by vampires
- [x] Edited tier 4 description
- [x] Added tier 4 achievement 
- [x] Edited vampire guide file
#### Describe alternatives you've considered

none

#### Testing
Got vampire tier 3, the mission and a cherishing NPC. Asked them, killed them, became tier 4
Visited vampire cathedral, found the mentor and talked with them. The choices work, can get the mission and the vampire bite from it

#### Additional context

The ability to reach tier 5 will be added in another PR

### CODE REVIEW

**Comment by Maleclypse** [comment]
To make the anger relations work I'd suggest 
```
"anger_relations": [ [ "VAMPIRE", -50 ], [ "RENFIELD", -50 ] ],
```
Or whatever number makes it so that you can cause them to attack you but they won't do it normally if you are around for a short length of time.

It's ok if they gradually decide to atack you because of being too close for too long because vampires natural state should be solitary predators that dislike each other's company. But that may be too hard to code currently :)  But anyway that with what I sent to this PR should make it all work.

**Comment by Maleclypse** [comment]
Thank you so very much for doing this! Great stuff!  I'll merge this after the tests pass.  I added a couple dialogue options for people with

**Comment by Krieger1999** [comment]
I do not know how to find the cherishing npc.
I get the mission from the vampire mentor but no coordinates for the target.

**Comment by SariusSkelrets** [comment]
The discord is a much better place to ask that than closed github issues

For your question, that NPC is any follower with their value and trust stats over 10. The mission isn't about finding a precise person, it's about getting a very close friend before murdering them so a location isn't needed

**Pull request merged**
