### PR TITLE
[RDY] Disable C4146 error in MSVC

### PR DESCRIPTION
**Pull request by ghost**
In `inventory_ui.cpp` line 418:

``` C++
} else if( action == "PREV_TAB" ) {
        move_selection( std::min( std::max<int>( -entries_per_page, -selected_index + 1 ), -1 ) );
    } else if( action == "HOME" ) {
```

`entries_per_page` is an unsigned type integer, and `-entries_per_page` results in `C4146` compile ``error'' in MSVC. Just now I discovered that it is in fact a warning but notices me like an error, and I could disable it in the configuration of the VC project.

BTW, I changed source file list in `.vcxproj` to wildcards.
Before:

```
<ClCompile Include="..\src\action.cpp" />
<ClCompile Include="..\src\active_item_cache.cpp" />
...
```

After:

```
<ClCompile Include="..\src\*.cpp" />
```

Some new source files were created in recent days (eg. `npc_class.cpp`), and I don't want to post a PR to add these files to MSVC everytime.

---

I submitted so many MSVC PRs in recent days. It's a little bit annoying to you, I'm sorry.

### CODE REVIEW

**Comment by kevingranade** [comment]
I prefer your previous solution of handling it using correct typing, MSVC is being more picky here, but it is definitely a problematic thing to do, and I'd rather not silence warnings if at all possible, they usually indicate a real problem.

The number of MSVC PRs is definitely not a problem, we're happy to support developers who want to use it.

**Comment by DLaboratory** [comment]
Okay, I converted them to `int` when calculating their negative number.

**Comment by DLaboratory** [comment]
Rebased this with the latest `master` branch, ready to get merged.

**Comment by mugling** [comment]
Doesn't this still suppress the `C4146` error despite you providing a mitigation for the original problem?

**Comment by DLaboratory** [comment]
For convenience purpose. Those code that triggers `C4146` error are added into the source tree often, I don't want to post a pull request every time and wait the request to be merged for weeks.

**Pull request merged**
