### PR TITLE
Caffeine pills for Computer Hacker

### PR DESCRIPTION
**Pull request by Metallumere**
Noticed a lack of caffeine in the hacker's diet.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I approve of this.

**Comment by DavidKeaton** [comment]
I would argue any good hacker has Adderall and/or weed. ;-)

**Comment by Rivet-the-Zombie** [comment]
Or all of the above, but this will do.

**Comment by DavidKeaton** [comment]
Fair enough m'lady.

**Comment by Metallumere** [comment]
\o/

**Pull request merged**
