### PR TITLE
Invisible spells

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Infrastructure "Added ability to cast spells without explosion visual effect."

#### Purpose of change
Sometimes explosion visual effect when spell is cast is undesirable. The new spell flag allows for casting spells without any visual effects.

#### Describe the solution
Added a new `INVISIBLE` spell flag. Explosion visual effect will only be drawn if spell doesn't have this flag. For now no spells in vanilla have this flag, but mods (e.g. Secronom, in which many features are made through the extensive use of spells) may benefit from having invisible spells.
Added documentation for the flag.

#### Describe alternatives you've considered
None.

#### Testing
Added this new flag to almost every spell in Secronom mod. Generated a world with the mod. Debug-spawned flesh forest and went for a stroll there. No more annoying explosion visual effect on my character literally every second.

#### Additional context
None.

### CODE REVIEW

**Comment by KorGgenT** [comment]
i talked to @esotericist about this PR, and there's a couple issues with this PR as-is.
1) and the most important one, this isn't making any changes to anything in-repo. when we set up the in-repo mod documentation, we basically decided then that if you want C++ for your mod, you need it in repo, otherwise you need to work around what exists. things that are currently dead code will eventually be deprecated.
2) if you're needing to disable it for every single spell, then there's a different issue here. I've been wanting to, for a long time, add the ability to have tiles defined for spells but that's a whole big mess of refactoring of the tile code required. it's a given that this isn't a lot of lines of code, but this is definitely something that'll have to be taken out later in order to fix the actual issue, and hiding the issue is worse than having this issue in the first place

**Comment by Night-Pryanik** [comment]
Ok, how about I go the opposite way - I'll add a VISIBLE spell flag to every single spell in in-repo mods, and spells that don't need visual effect could simply don't have this flag?

**Comment by KorGgenT** [comment]
why do you think that would be ok? that's just attempting to jump through a hoop for #1, by implementing something that doesn't make sense in-repo in a vacuum. you're also eliding entirely over my second point.

**Comment by Night-Pryanik** [comment]
> why do you think that would be ok?

I dunno, because it works?

You made a completely subjective decision to add an explosion visual effect for _every_ spell. And despite the documentation states that spells are not necessarily magic, there is no way to disable the visual effect nor to assign a different sprite to it. And when I propose a quick and working solution to disable the undesirable effect, you discard it saying that my mod had to be an in-repo mod to accept my changes to the code. As far as I recall, @kevingranade permitted adding code for _any_ mod, without the proviso about in-repo mods.

Regarding your second point: I need not the custom visual effects for some spells, but no effects at all. Even if we add an ability to define custom tiles for casting spells, assigning a transparent sprite to achieve the "no visual effect casting" effect would be an ugly and hacky solution.

**Comment by Night-Pryanik** [comment]
Anyway, I'd like to hear project leader's opinion on this PR.

**Comment by Night-Pryanik** [comment]
Why am I ignored? @kevingranade please do tell me if @KorGgenT's reasons for closing the PR, and my arguments about supporting the code for non in-repo mods are valid.

**Comment by kevingranade** [comment]
@KorGgenT is in charge of magiclysm related changes.

**Comment by Night-Pryanik** [comment]
But spells are not designed only for magic and Magiclysm, right? In any case spells effects are jsonified and therefore could be used by any mods, including those without any magic whatsoever.

**Comment by ZhilkinSerg** [comment]
Maybe this change could help to implement psionic-like abilities - something wreaking havoc without visible effects?

**Comment by Night-Pryanik** [comment]
This change could provide a lot of options for mods that don't need no visual effects whatsoever for effects granted by spells.

**Pull request closed without merging**
