### PR TITLE
Hunting supply store

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Content "Added hunting supply store location"```

#### Purpose of change
Adding a new kind of store to loot hunting weapons, survival gear and warm clothes.

#### Describe the solution

s_hunting

### CODE REVIEW

**Comment by curstwist** [comment]
Looks good.  Pretty high spawn rates, but that's the direction loots spawn is going in.  Roof looks great, thanks!

**Comment by Beneficial-Insurance** [comment]
perhaps add holo-cloaks as a very, very rare spawn?

**Comment by RarkGrames** [comment]
> 
> 
> perhaps add holo-cloaks as a very, very rare spawn?

The high-tech gadgets are military or government experimental stuff according to the project design document, so no chance of finding them in civilian stores. If the game would have everyday camo gear, like camo ponchos or similar, I would add them here though.

**Comment by Moonsabrt** [comment]
Now we just need a mega version of this and it can become a nightmare 'w')
Ever seen like the big big hunting stores in america like bass pro shops. That should be a thing one day

**Pull request merged**
