### PR TITLE
Smartphones

### PR DESCRIPTION
**Pull request by FulcrumA**
#### Summary
SUMMARY: Content "Adds smartphones and their spawn" 

#### Purpose of change
There were mentions in the past of how weird it is that the future does not accomodate smartphones, using merely cellphones. This PR adds the item.

#### Describe the solution
Smartphone item added, adjusted the loot tables so it can be found more often than how cellphone was till now (slightly decreasing spawn rates of those). Functionality of smartphone is slightly different - it uses UPS and doesn't allow direct input of batteries, it possess functionality of the cellphone + camera functionality. Cellphone light was made slightly weaker, to make cellphones generic as they were - rather than LEDs, cellphones use their screens as that's how most people used them to light various areas with old models of cellphones.

Some connected features were slightly adjusted - some descriptions slightly changed, some prices slightly differentiated.

#### Describe alternatives you've considered
I've considered not changing cellphones at all, but as I've introduced smartphones I've decided it'd be a good move in tune with overarching project directions to make the cellphones as they are realistically - older models, rugged and functional but not performing at the same level of quality most often. The changes here are mostly superficial of no real practical effect during the gameplay, but they will help differentiate between the two devices when used side-by-side.

### CODE REVIEW

**Comment by Inglonias** [comment]
I'm not sure how I feel about this. I find UPSes pretty rarely, and I'm wondering if that will affect anything. On the other hand, the phone's most useful feature (the clock and alarm) don't use any power, so I guess you can avoid using the flashlight and camera until you actually find a UPS.

**Comment by FulcrumA** [comment]
>I'm not sure how I feel about this.

In a way, that's part of what I was going for. Fancy pre-cataclysm smartphones dependant on chargers and whatnot should be less practical choice after the cataclysm, unless someone will be able to rebuild basic amenities such relatively high tech is dependant on. So a simple survivor should prefer a regualr cellphone making such a device still an useful item, while "luxurious" devices such as smartphones should be free to use only for those who already can maintain a degree of pre-cataclysm luxury, like reliable access to electricity.

It's kinda like this IRL, too. Some people still use extra sturdy cellphones allowing various charging methords, but average fancy smartphone is practically charged only by connecting it to the power grid. If anything, I wouldn't mind it if more high-tech devices would depend on UPS charging though it may be quite a controversial move and out of the scope of this PR.

**Comment by Zireael07** [comment]
>  average fancy smartphone is practically charged only by connecting it to the power grid

Point taken, but there are fancy smartphones that charge via solars or induction (for the folks who travel a lot e.g. mountaineering)

**Comment by FulcrumA** [comment]
>Point taken, but there are fancy smartphones that charge via solars or induction (for the folks who travel a lot e.g. mountaineering)

They are pretty rare but I guess nothing stops anyone, me included, for expanding the feature by various models or even better, simply adding different portable chargers as I believe most smartphones charged "in the field" are still pretty regular smartphones, it's the chargers themselves that are solar and otherwise fancy.

**Comment by FulcrumA** [comment]
@Xhuis 
I don't think the MP3 player functionality would be hard to add technically, but it'd be a really hacky job due to how flashlight works. It transforms the smartphone into a flashlight and while it makes sense that you cannot use a camera in that mode, it'd be less reasonable for a music player - but also impossible as you cannot have more than one "lasting effect" functions active at the same time.

**Comment by rubenpd** [comment]
no solar chargers? https://www.powertraveller.com/au/shop/portable-chargers/outdoor-adventure/

**Comment by FulcrumA** [comment]
@rubenpd
Out of the scope of this work. I merely add smartphones and adjust cellphones a bit, all the paraphernalia associated with them would probably benefit from a separate PR.

**Comment by FulcrumA** [comment]
Jenkins rebuild

**Comment by FulcrumA** [comment]
There was a bug with changes in game's master branch to assign.h and possibly other files that somehow wasn't tracked nor raised any alerts in branches made around that period, while making various checks fail. It likely explains a string of Jenkins check failures from the point of merging of some jsons from between my branches till recently.

**Comment by FulcrumA** [comment]
Closed and reopened to give TRavis a CI a chance to build the thing properly (2 out of 15 jobs failed).

**Comment by FulcrumA** [comment]
Well, never used or had to use tags like such in my previous PRs but I guess if it helps encourage someone to review it at last..

So, it is officially ready, sans potential rebasing I cannot do through web github (though I guess I can just rip it all apart and attempt to redo the ticket) if one's bothered by the number of commits, caused by things mentioned above - mostly rewriting, linting, adjusting stuff in attempt to fix a bugs that turned out to not be ones in the content of this PR and changing/adding to loot tables for various locations/mobs.

**Comment by kevingranade** [comment]
Particularly when there are many PRs open, I wait to do final review/test
of a pr until it loses the [wip] tag.

I do review for, "is this a good idea", but I'm definitely not going to
even consider it for merge until the title says its ready.

**Comment by FulcrumA** [comment]
@ZhilkinSerg 
Yeah, I had to lint quite a few files I worked with - between the aforementioned bug I was hunting and actual errors thrown due to use of formatting/characters in my system the project apparently hates, most of the files I worked with had to go at least partially through some lint.
If there's a way github itself would allow me to do said rebasing that wouldn't be manually going through each of those files and redoing all the work of this PR again by hand, I am up for attempting it.

**Comment by ZhilkinSerg** [comment]
If you are using Github Desktop, you can do the following.

0. Run Github Desktop and Cataclysm repository open Git Bash:

image

1. Update your local `master` with changes from `upstream`:

```
$ git checkout master && git pull --ff-only upstream master
```

image

2. Switch to your branch:

```
$ git checkout patch-1
```

3. Merge changes from `master`:

```
$ git merge upstream/master
```

4. Reset branch to have your changes on top:

```
$ git reset --soft upstream/master
```

5. You will now have all your changes uncommited, so you can commit only necessary files/lines:

image.

6. After all changes are committed you can force push changes to github to rewrite commit history.

```
git push --force
```

**Comment by FulcrumA** [comment]
Hah. Another case where my github website use is insufficient then?

**Pull request merged**
