### PR TITLE
Allow wool to be used to warm clothes

### PR DESCRIPTION
**Pull request by PropaneSoup**
As suggested on the forums, this allows you to use felt patches in addition to fur to warm your clothes. I also changed the wording to reflect the changes, although I couldn't change the item_tags name without breaking save compatibility, so that's all still furred. As it is now, if you have both fur and wool, it will use fur first. If that's a dealbreaker, I can toss in a menu if the player has both, although I've been poking around at doing that, and it's been acting kinda strangely.

### CODE REVIEW

**Comment by PropaneSoup** [comment]
Uh, I don't know why this is failing.

**Comment by Rivet-the-Zombie** [comment]
What would be even better would be for wool to be a separate add-on in addition to fur lining, so if you wanted to make sure your stuff was really warm you could add both.

**Comment by PropaneSoup** [comment]
I had that thought too, though I was concerned about how it should compare to fur stat-wise. If that seems like a better alternative I can scrap this and type that up easily enough.

**Comment by KA101** [comment]
Yeah, I'd say wool should be separate.  Thoughts on differentiation:
-wool is more compact, less encumbrance penalty/volume gain
-wool gives less warmth bonus
-wool retains warmth bonus when wet (add the "wool" material to the item, if possible?)
-wool can trigger allergies

**Comment by PropaneSoup** [comment]
Oof, maybe it won't be as simple as I thought. That's some uncharted code territory for me. Suppose some of these should start getting applied to the other modifications too though, like volume increase. Ok, I'll close this branch and start up with a new wool one, since this branch appears to be un-merageable, and I can't sync it with the master for whatever reason.

**Pull request closed without merging**
