### PR TITLE
split-off `input_context.h` from `input.h`; run iwyu to always include `input.h` directly

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
None

#### Purpose of change
Split-off `input_context.h` from `src/input.h` to reduce compilation time when changing something in header files.
Test how well did I do.
~I want to split `src/input.h` in another PR~.

~I realize that, since there are unneeded includes, it still can happen, that I recompile more than I need to (when working with `input.h`). But the ratio (of files needing recompilation after the future `input.h` split vs before) will say what the ideal (lowest) recompilation file count would be if all indirect includes were sorted out.~

~Sorting out these unneeded includes would take too much time. I do only small bites.~

#### Describe the solution
run iwyu

- [x] First commit: accept (not all) changes that only remove includes / forward declarations (don't add any). I might as well do this since I run iwyu anyway. (almost pure, had to add `lightmap.h` include)
- [x] Second commit: includes in `input.h`, `input.cpp` according to iwyu.
- [x] Third commit: expand includes so that `#include "input.h"` is directly exposed everywhere. On affected files, remove whatever iwyu reports to remove, but add only the minimum needed for compilation (take advantage of indirect includes).
- [x] check iwyu (tests below)
- [x] Fourth commit: split-off `input_context.h` and `input_enums.h` from `input.h` and `input_context.cpp` from `input.cpp`
- - `input_enums.h` contains things that both of the other header files need. It is included in both of the header files.
- [x] Fifth commit: like third, but expand `input.h` and `input_context.h`, if neither is needed, but `input_enums.h`, include it.
- [x] Test how effective this is by counting the number of files needing recompilation before and after this change.

#### Conclusion

Test results [bellow](https://github.com/CleverRaven/Cataclysm-DDA/pull/71141#issuecomment-1905240424).

I set out to reduce re-compilation times for `class input_manager` in `src/input.h`. It **is now (indirectly) included in 36 rather than 240 files**! So this was a resounding success.

I believe, however, that the success comes from splitting the `input.h` file, not from running iwyu alone. As can be seen from not reducing includes for split-off `input_context.h`. Therefore I don't think running iwyu on the whole codebase is worth my time right now. However, it seems that splitting monolithic header files would have a significant impact.

#### Describe alternatives you've considered
Running over the whole codebase. But I want something merge-able. And small bites.

#### Testing
compiling locally
compiling in this pr

(running) iwyu

- suggests no changes for `input.h` and `input.cpp`
- suggests no changes for `input_context.h` and `input_context.cpp`
- doesn't suggest to add or remove `input.h` or `input_context.h` anywhere
- suggests to add `input_enums.h` only if `input.h` or `input_context.h` are already included

#### Additional context
~Not a draft, so that all tests run.~ Ready to merge now!

### CODE REVIEW

**Comment by Brambor** [comment]
If the tests pass, this is ready to be merged!

**Comment by akrieger** [comment]
Clang tidy says
```
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/lightmap.h:45:36: error: no member named 'log' in namespace 'std' [clang-diagnostic-error]
    return static_cast<int>( -std::log( LIGHT_AMBIENT_LOW / b ) * ( 1.0 /
```

**Comment by Brambor** [comment]
> Clang tidy says
> 
> ```
> Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/lightmap.h:45:36: error: no member named 'log' in namespace 'std' [clang-diagnostic-error]
>     return static_cast<int>( -std::log( LIGHT_AMBIENT_LOW / b ) * ( 1.0 /
> ```

It should be resolved now.

**Comment by ehughsbaird** [comment]
> Test how effective this is by counting the number of files needing recompilation before and after this change.

Before
```
% cat obj/*.inc | grep input.h | wc -l
243
```
After
```
% cat obj/*.inc | grep input_context.h | wc -l
240
% cat obj/*.inc | grep input_enums.h | wc -l
244
% cat obj/*.inc | grep input.h | wc -l
36
```

**Comment by Brambor** [comment]
I wondered if the includes in that file could repeat, so I did this, and they don't seem to be repeating.

```bash
% grep -m 1 input_context.h obj/*.inc | wc -l
240
```

**Comment by Brambor** [comment]
Nooooooooooooooooo
A merge conflict :(
Why do you do this to me?

**Comment by Maleclypse** [comment]
Sorry! Ping me in discord when it's passed tests after merge conflict resolution.

**Comment by Brambor** [comment]
Let's just try including both, what could go wrong?

**Comment by Brambor** [comment]
test failed, restarting

**Comment by Brambor** [comment]
trying to restart again

> Clang 12 Asan cancelled during compilation for some reason, so all tests after that also didn't run. Someone should give this a kick probably.

**Comment by akrieger** [comment]
widget_test segfaulted on both windows and mac, which is slightly suspicious. If it were just one, I wouldn't care, but those are two wildly different platforms.

**Comment by andrei8l** [comment]
> widget_test segfaulted on both windows and mac, which is slightly suspicious. If it were just one, I wouldn't care, but those are two wildly different platforms.

That's my fault. See [#71213](https://github.com/CleverRaven/Cataclysm-DDA/pull/71213/files)

**Comment by Brambor** [comment]
As promised, I now need to recompile only 38 files, which is over 6x improvement. I love it!

**Pull request merged**
