### PR TITLE
Allow towels to clean off boomer goo

### PR DESCRIPTION
**Pull request by PropaneSoup**
This includes the glowing goo as well as the regular boomer goop. Using the towel while any are on you will clean them all off, and it'll take longer for the towel to dry off based on how much it cleans up.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs some sort of a move cost

**Comment by Marrim** [comment]
This should probably work more like rags and bleeding.

**Comment by PropaneSoup** [comment]
Towels already allowed you to clean off any slimed effect, so I don't think boomer goo is much farther off. Towels also aren't that useful at the moment, giving them a niche use like this helps their usability.

**Comment by Zireael07** [comment]
@PropaneSoup: +1.

**Comment by kevingranade** [comment]
I think Marrim means you should end up with a "soiled towel" or similar instead of a merely wet one if you're using it to clean up weird monster goop, and that sounds like a good idea to me.

**Comment by PropaneSoup** [comment]
Ok, this'll need a recipe like the bloody rag's to clean it off then.

**Comment by Coolthulhu** [comment]
Needs some restructuring:
* Needs to target slime before water morale penalty. Being drenched in water means less than having even a bit of slime in the eyes
* Keep the if/elses together for readability, like this:
```
if() {
    // Comment here
} else {
    // Comment here
} else {
    // Comment here
}
```

**Comment by PropaneSoup** [comment]
Alright, this should be good to go now. It'll clean off any goop first, then water. Cleaning off goop will also give you a soiled towel, which you just need to wash in some water to get a good, clean towel again. My thinking in making cleaning it simple was that requiring soap or bleach or some-such would act more as an annoyance, and it'd probably be easier just to find or make a new towel.

**Comment by kevingranade** [comment]
I think water is sufficient, possibly consider a more thorough cleaning
requirement if it's something toxic.

**Comment by Coolthulhu** [comment]
Minor:
* Washing the towel dries it
* Wet towel could probably be used to wash off slime (but not soak water)

**Pull request merged**
