### PR TITLE
Extend stats dumper [RDY]

### PR DESCRIPTION
**Pull request by mugling**
Includes ability to output to HTML. The intended using being to aid updating of the wiki. @remyroy if you have any specific suggestions I can extend this as necessary.

```
./cataclysm --dump-stats AMMO HTML > ammo.html
```

Adds ability to dump edible items (inclusive of their vitamin contents) via EDIBLE. This should help us target our effort in defining `vitamins` for outliers and/or in refining the default algorithm.

```
./cataclysm --dump-stats EDIBLE HTML > vitamins.html
```

Mod locations are included for GUN to aid in verying PR's such as #16354

```
./cataclysm --dump-stats GUN > after.tsv
diff before.tsv after.tsv
```

### CODE REVIEW

**Comment by remyroy** [comment]
I'm not the one updating the wiki but the wiki syntax is not HTML. It's [Wiki markup](https://en.wikipedia.org/wiki/Help:Wiki_markup). You might want to check with Mattamue‎ which is the one doing most of the wiki updates.

**Comment by illi-kun** [comment]
I'm not sure we already have description of this special mode of running the application. It's definetely should be described (or expanded with explanations of added feature, if it's already exist) somewhere in ```doc```.

**Comment by mugling** [comment]
@illi-kun some documentation detailing supported modes is added in e8f3c7e

**Comment by mugling** [comment]
Anything further?

**Comment by kevingranade** [comment]
When I ran it, it dumped weird binary stuff at various intervals, e.g. the start of the html:
[?1049h[1;75r(B[m[4l[?7h[?1000h[?1h=<table><thead><tr><th>Name</th>

Please just pass the string parameters through to the dumper, there's no reason to expose the mapping of string to enum globally.

**Comment by kevingranade** [comment]
Maybe more informative, here's the start of the html in hex:
```
hexdump -C stats.html | head
00000000  1b 5b 3f 31 30 34 39 68  1b 5b 31 3b 37 35 72 1b  |.[?1049h.[1;75r.|
00000010  28 42 1b 5b 6d 1b 5b 34  6c 1b 5b 3f 37 68 1b 5b  |(B.[m.[4l.[?7h.[|
00000020  3f 31 30 30 30 68 1b 5b  3f 31 68 1b 3d 3c 74 61  |?1000h.[?1h.=<ta|
00000030  62 6c 65 3e 3c 74 68 65  61 64 3e 3c 74 72 3e 3c  |ble><thead><tr><|
00000040  74 68 3e 4e 61 6d 65 3c  2f 74 68 3e 3c 74 68 3e  |th>Name</th><th>|
```

**Comment by narc0tiq** [comment]
ANSI escapes? Are we trying to syntax-highlight the html?

**Comment by mugling** [comment]
> Maybe more informative, here's the start of the html in hex:

I'm not sure why the code does that but I'll take a look

**Comment by kevingranade** [comment]
Random idea, perhaps ncurses and std::cout are interacting badly?

**Comment by mugling** [comment]
Can't reproduce with `cataclysm-tiles`. I'm building a curses variant now to check. What terminal are you using?

**Comment by mugling** [comment]
> Random idea, perhaps ncurses and std::cout are interacting badly?

Possibly true as I can reproduce this with the curses version

**Comment by mugling** [comment]
So this could be fixed by specifying an output filename but that prevents use in a pipe which makes developing any further tools using that output somewhat more difficult. Further suggestions?

**Comment by BevapDin** [comment]
You need to run the dump before ncurses is even started. It's started in main.cpp via `initscr()`, so your code needs to run before that. Starting ncurses already does some output (`man initscr` says it calls `refresh`).

You may have the problem that some of the debugging / error handling code (triggered by loading the JSON data) calls curses functions.

Another solution (not nice, but possible) could be to remove the curses output via a second program:
```SH
./cataclysm --dump foo | remove-terminal-format-sequences | your-processing-tool
```

Use `sed, `awk`, `perl` or `python` or whatever to implement `remove-terminal-format-sequences`. Add a wrapper script that combines `./cataclysm --dump foo | remove-terminal-format-sequences` into one command, for example called as `./cataclysm-dump foo`.

You can temporally leave ncurses to ensure unformatted output:
```C++
// See http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/misc.html
def_prog_mode();
endwin();
std::cout << "SOME MARKER BEGIN\n";
... // direct output to std::cout
std::cout << "SOME MARKER END\n";
reset_prog_mode();
```
Use the markers to detect where the interesting part begins and ends.

**Comment by mugling** [comment]
fdaba40 provides a solution so that escape sequences don't make it into dumped output when compiled using curses mode. `initscr` is disabled in this mode and then `stdscr` is checked for `nullptr` with `std::cerr` and `abort` being called in this case.

This has the added advantage that any automated tools built upon this interface can continue to use pipes but can correctly distinguish between correct output and JSON errors (the latter are written to `std:cerr` and a non-zero exit code results)

**Pull request merged**
