### PR TITLE
[Magiclysm] Require druid to be in natural surroundings to cast Restoration

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Require druid to be in natural surroundings to cast Restoration"

#### Purpose of change

At first, druids had no healing spells except Sacrificial Healing, and everyone said to play Biomancer. Then druids got two healing spells...and one of them is almost never used. Partially because it was bugged for a long time (which took a long time to notice because no one ever used it), and partially because it requires components. 

Well, these are druids we're talking about. They draw on the power of nature and should be stronger in nature, right? So why not make the powerful healing spell require being in nature to cast, and that reflavors the healing spell that requires components as requiring components because the components are a portable version of the power of nature that the druid brings with them. 

#### Describe the solution

Change Restoration so it requires the same conditions as Nature's Commune--outdoors and not within 1 overmap tile of a road. Floral Healing remains the same and can be used anywhere. 

#### Testing

It works. 

#### Additional context

I have some Biomancer spell ideas I plan to add to help close the healing gap (since Biomancers are supposed to have greater control over their bodies and thus greater self-healing), but in another PR.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Should biomancers lose early access to healing others?  Would it make sense for them to only be able to heal themselves at first and then eventually learn how to heal others?

**Comment by Standing-Storm** [comment]
> Should biomancers lose early access to healing others? Would it make sense for them to only be able to heal themselves at first and then eventually learn how to heal others?

At the moment it's the other way around (which I kind of like because it's different)--their simple healing spells can be used on others but their buffs and powerful healing spells are self-only.

**Comment by Testudo-Cultu** [comment]
This is good, but the logic for checking if you're in or around nature seems flawed. With the current logic only checking for roads you could be on the deck of an aircraft carrier, concrete floor in the middle of nowhere, etc. It would still be pretty flawed, but I recommend changing the logic so that it instead requires that the player is standing on a tile associated with nature rather than requiring that the player isn't on a tile that isn't associated with nature.

**Comment by Standing-Storm** [comment]
> This is good, but the logic for checking if you're in or around nature seems flawed. With the current logic only checking for roads you could be on the deck of an aircraft carrier, concrete floor in the middle of nowhere, etc. It would still be pretty flawed, but I recommend changing the logic so that it instead requires that the player is standing on a tile associated with nature rather than requiring that the player isn't on a tile that isn't associated with nature.

There's an easy fix I can apply to both from the work I've done on Arvore in XE. I'll do that.

**Pull request merged**
