### PR TITLE
Add recipes for some armor items

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add recipes to make elbow pads, knee pads and hard hat.
2. Add makeshift Kevlar vest and recipe for it.
3. Increase time required to make MBR vest and make its' recipe autolearnable.
4. Reduce coverage of hooded hard hat.

### CODE REVIEW

**Comment by mugling** [comment]
Not everything should be craftable. It would be better to add further improved variants that use these as components?

**Comment by Coolthulhu** [comment]
I agree with mugling here.
Kevlar armor should generally exist in player variants and uncraftable variants. MBR is weird here, but I'd rather go with making it uncraftable than extending crafting to other items.

**Comment by Zireael07** [comment]
I can't imagine a survivor making a proper hard hat. Kevlar vest, yes, it's just sewing the plates on a vest.
I'm of two minds when it comes to pads.

**Comment by Darkyhard** [comment]
> I can't imagine a survivor making a proper hard hat. Kevlar vest, yes, it's just sewing the plates on a vest.
I'm of two minds when it comes to pads.

Actually, crafted hard hat would be a plastic helmet made by melting hard plastic and shaping it as needed rather than a hard hat, but if it was a separate item, it wouldn't differ much from a hard hat, I think.

Pads are made in a similar way: you just shape some hard plastic in a shape of a pad and then attach cloth or leather straps to it.

As for Kevlar vest, if it is unreasonable to craft, I'm not sure what would this recipe produce and how would the result differ from the existing Kevlar vest.

**Comment by mugling** [comment]
> I'm not sure what would this recipe produce instead and how would the result differ from the existing Kevlar vest.

If there's no new content then there's nothing to actually implement? I'd rather we added more well thought out variety rather than made everything craftable

**Comment by Coolthulhu** [comment]
I'd say it would mostly differ in armor value and durability.
Sewing kevlar with regular thread meant for cotton would most likely be noticeably less durable than a proper factory-made one.

While we're at hard hats, it would be a good idea to nerf hooded hard hat which kinda went under the radar - it has better coverage than the regular one, very similar armor value, but is made by attaching a bunch of rags behind the hat. It should lose that coverage advantage.

**Comment by Zireael07** [comment]
I said that Kevlar vest IS reasonable. I had my doubts about the hard hat due to the shaping part.

**Comment by chaosvolt** [comment]
That was a bit of a dumb idea on my part, as there's no real way to make a hooded hard hat that logically acts such that the added coverage doesn't equate to full protection. ._.

Right now sun coverage isn't even a thing aside from the glare protection, so both hooded hard hats and normal hooded hats are a tad pointless. Maybe if we had a "baking in the sun" effect similar to how wind chill is a thing?

**Pull request merged**
