### PR TITLE
Delete astyle shell scripts

### PR DESCRIPTION
**Pull request by AMurkin**
```SUMMARY: None```

Delete astyle shell scripts since we have 100% astyle coverage now.

### CODE REVIEW

**Comment by kevingranade** [comment]
I would recommend deleting this script now, we have 100% astyle coverage now, so we don't need to worry about incremental astyling shenanigans anymore.

**Comment by AMurkin** [comment]
What about `tools/astyle_file_changes.sh` and `tools/astyle_lines.sh`?
Delete them too?

**Comment by kevingranade** [comment]
Yes, none of those should be necessary anymore.

**Comment by AMurkin** [comment]
Done.

**Pull request merged**
