### PR TITLE
Add mutagen crafting components to underground lab

### PR DESCRIPTION
**Pull request by zachary-kaelan**
#### Summary
```SUMMARY: Balance "Add mutagen crafting components to underground lab"```

#### Purpose of change
Explain how the scientists there are making mutagens, as well as provide more places for these items to spawn.

#### Describe the solution

Add `tools_science` item group to various item spawnpoints:

- Racks in certain rooms.

#### Describe alternatives you've considered
You don't want to know.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
In the spots you're looking, you've put the science gear in with the cleaning stuff, but there are counters with lab chemicals and things on them in the same definition. I'd suggest putting the science stuff where things like chemicals are, not cleaning supplies.

Also, 80% is a very high spawn rate generally. That means almost every tile will have a piece of science gear. I'd recommend keeping it similar to the other numbers in the definitions here, usually 10-30%.

**Comment by zachary-kaelan** [comment]
I just went based on the Research Lab, which has 80% on every rack. Though the underground lab has a lot more racks, so I guess I would've needed to divide by the number of racks in the room.

I also assumed that they would put the tools away in a closet, underneath the bleach and ammonia, but I can see why they would leave them on the benches. Maybe they would keep a couple extras in storage?

**Comment by I-am-Erk** [comment]
Things like spectrophotometers and balance scales live on lab benches, not usually on racks.

The research facility uses a pretty different spawn criteria, it's much more realistic in terms of quantities of things. You could try to replicate that in the underground lab, but it takes a lot of playtesting and trial and error, and you'll probably want to change the spawns of a few other things at the same time

**Comment by tenmillimaster** [comment]
If you want instruments on racks, it should be damaged instruments; dead instruments are usually the only ones that get out away.

**Comment by tenmillimaster** [comment]
Craftable instrumentation doesn't really belong in this PR.

**Comment by zachary-kaelan** [comment]
@I-am-Erk We kind of discussed crafting of voltmeters but I forgot about it when writing the PR. I moved the changes to a new branch for later.

@tenmillimaster I guess the cleaning rack is more for the walk of shame of someone that made a mess.

**Pull request merged**
