### PR TITLE
Cookies in plastic packets instead of 95% empty boxes

### PR DESCRIPTION
**Pull request by Regularitee**
#### Summary
```SUMMARY: Balance "Cookies now in plastic packets instead of 95% empty boxes"```

#### Purpose of change
Cookies currently come in 1L boxes with four cookies (0.05L of product); see Fig A. This is the equivalent of water bottles (0.5L of water) being the size of plastic jerry cans (10L). Except if the jerry couldn't be refilled. Which would suck.

Cookie Science

#### Describe the solution
Change the container from boxes to plastic bags. As non-rigid containers they adequately fit any size of food product, even those with unusual volumes (like cookies). It also makes more sense manufacturing wise to use plastics for such a small serving size (4 cookies), as plastics are drastically cheaper -- which is why they're the dominant form of packaging in small food servings (chocolate bars, cookies, crackers, chips, etc), and disposable containers in general (cups, grocery bags, etc). 

#### Describe alternatives you've considered

1) Foods come in various sizes. Creating a custom-sized box would require a vast number of discrete boxes: a 0.05L box, a 0.1L box, a 0.2L box, a 0.3L box, etc. It seems more practical to use an existing container rather than making 10 new ones. Especially in this particular case, as using a pre-existing container actually made more sense from a practical manufacturing standpoint (plastic bags are cheaper to manufacture).

2) Making boxes non-rigid, to automatically adjust to food content size. But then they'd not be boxes. They'd be... paper bags.

#### Additional context
Remade the PR because an all-caps title about cookies was taken actually hostile rather than as a joke. Also added diagrams and a paragraph to justify everything thoroughly, because last I took for granted that people would understand why this was a preferable option to a packaging scheme that was literally 5% product, 95% empty air.

### CODE REVIEW

**Comment by NickGrease** [comment]
Is there a technical reason to not just add more cookies to the box? The image of cookies you use, looks like it's from BelVita cookies - which come in a box - about 1L in volume, more then one packet to a box I would assume. Doesn't really matter to me, but [this](https://momluck.com/wp-content/uploads/2015/03/IMG_6667.jpg) and [this](https://pinkcakeplate.com/wp-content/uploads/2014/12/oreo-cookies-walmart1.jpg) are somewhat typical grocery store shelves - you're unlikely to find single packages as you've described above. While you could argue 'specialty' stores may server them that way, most Americans would associate 'package of cookies' with the images I linked.

**Comment by Regularitee** [comment]
Probably two reasons:

1) They're in the vending machine spawn schedules. So they have to be vending machine size/weights. A larger version would require forking cookies into snack and bulk sized products. 

2) Balance. It's the same reason we don't have vitamins in the (much more realistic) 150-300 pill bottles, If you up the quantity, you have to nerf the spawn rates for every location to keep parity. And spawn schedules are finicky in that (as far as I know) you cannot reduce it below 1 of [number of items in list]. Meaning you'd have to stuff more items into a spawn schedule to reduce cookie spawn rates further.

**Comment by NickGrease** [comment]
Fair enough. I admit, I had forgotten about vending machines.

**Comment by KorGgenT** [comment]
why not just make a new box that's the right size?

**Comment by kevingranade** [comment]
> They're in the vending machine spawn schedules. So they have to be vending machine size/weights. A larger version would require forking cookies into snack and bulk sized products.

That sounds fine, tiny servings of single-use foil bags in vending machines, larger boxes elsewhere.

**Comment by Regularitee** [comment]
> why not just make a new box that's the right size?

Plastics are the better choice from a practical implementation standpoint, since it's always easier to use existing items than create brand new ones. It's also a better choice from a realism standpoint; single-use plastics are superior to cardboard on small-scale products from a manufacturing perspective, being cheaper, more water resistant, air-tight to preserve freshness and keep moisture out, harder to tamper with and reseal, etc. That's why they're so ubiquitous despite how much worse they are for the environment.

**Pull request merged**
