### PR TITLE
Add personal and outer aura layers, as well as the intangible flag

### LINKED ISSUE #30897: New Aura equipment layer request
**Is your feature request related to a problem? Please describe.**  
There are a lot of useful functions that can be accomplished with the magic mod, but in making spells I have run into problems with because when I create "protection" from spells (typically a 0 enc, 0 vol, 0 weight suit or body part protection item), regardless of what layer of the body I put it on, it's going to conflict and create an encumbrance penalty even if the object has 0 encumbrance itself. 
I would love to have a spell of warmth for example, that just added a 0 enc/50 warmth layer, or 5 point acid protection layer, but with it supposedly just being some magic field protecting the player, instead they are slowed down when that doesn't make sense, it hampers the implementation of defensive abilities because I don't want to penalize the players nonsensically.

**Describe the solution you'd like**  
Optimally, what I would request is the addition of 2 additional Aura layers (or one Aura and one something else), one that is the last thing before your skin, and one that is the furthest thing outside of you. Neither would have encumbrance penalties or conflict with anything worn or even other auras layer items. This will also be useful for things like sci-fi style forcefields (which would be furthest out aura), which should be easy to do now with the coming items-casting-spells functionality.
Kevin and esotericist both indicated that it shouldn't be difficult to do at all, so I'm asking for two for maximum flexibility. In many cases it may be desired to have something be the first or last layer of defense, protecting your physical body (and not your gear) from acid is a lot different than growing bony magical armor outside to go toe-to-toe with Skeletal Juggernauts, 
I think all mod authors would prefer maximum flexibility and not be forced into giving more benefits than intended to the player, as the one working on spell and item content for Magiclysm I'm keenly trying to avoid that as we try to work out balance with the main game.

**Describe alternatives you've considered**  
Alternatively, the only other solution I can think of is the addition of a flag (NO_CONFLICT?) to specify that the worn item on that layer does not conflict with other worn items on that layer or create the encumbrance penalty. 

I feel my suggestion of two options provides the most long term and future-proof solution to providing this functionality as the game continues to grow, and I think a lot of current and future mod content would benefit from having them.

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Mods "Add personal and outer aura layers, as well as the intangible flag"

#### Purpose of change
There are many effects that should realistically not collide with normal clothing/armor, mostly (but not necessarily exclusively) metaphysical effects from mods. 

Closes #30897

#### Describe the solution
Add two layer flags: `PERSONAL` and `AURA`. These work like other clothing layers, except `PERSONAL` now is the closest to the skin (actually underneath the `SKINTIGHT` layer), and `AURA` is the farthest from the body.

Both flags make an attempt to prevent the usual collisions between equipment (helmets, etc), but still participate in the encumbrance system as normal, on the off chance a spell effect should have some encumbrance penalty while not being a "normal" piece of equipment.

Add the `SEMITANGIBLE` flag, which causes an item to opt-out of encumbrance entirely, and further attempts to prevent collisions between equipment. `SEMITANGIBLE` does not allow more than two copies of a given item to be equipped, nor will it ignore the `ONLY_ONE` flag if present (a `SEMITANGIBLE` item with `ONLY_ONE` is still limited to one equipped).

Added both the `AURA` and `SEMITANGIBLE` flags to the magic light and magic lamp spell items, as a demonstration case of the new mechanisms.

#### Describe alternatives you've considered
The original feature request suggested that the two aura layers opt-out of encumbrance entirely, so I could have done that. I feel like splitting the functionality out into an additional flag gives more flexibility in how effects can be implemented.

I also wanted to try to implement a mechanism for limiting how many of a *kind* of item, with a specified category, but I concluded that is out of scope with this PR and best done in a followup PR.

There was an attempt earlier on in the PR to prevent items in the PERSONAL or AURA layers from being reordered using the `+` armor management interface, but it ultimately got deferred to a later PR (see Additional Context).

#### Additional context

Next steps:

*  Followup PR to properly handle the reshuffling of things within layers but not between layers. This is a bigger project than it looked like, so it isn't getting handled right now (to better ease content creation).
*  Followup PR to add a framework for restricting the number of equipped items in a category, irrespective of kind, bodypart, or layer.
*  Possible followup reworking how power armor collision is handled, pending a discussion on how power armor collision *should* work. The current mechanism seems pretty incoherent to me, and I couldn't see how to directly adjust how power armor collides (or doesn't collide) either with the new layers or the `SEMITANGIBLE` flag without rewriting all of that.

### CODE REVIEW

**Comment by foulman** [comment]
What do you think about having the ability to prevent damage passing though, say on the aura layer? Is it possible to make a flag so that it would be ablative rather than functioning like normal armor?
As in it would have to be destroyed first before anything went through, perhaps increasing the damage the aura item took itself?
also on a similar note would it be possible to have a flag where it would take no damage?
If you have any D&D experience, that would be like.. say.. Stoneskin and the Armor spell respectively.

**Comment by esotericist** [comment]
> What do you think about having the ability to prevent damage passing though, say on the aura layer? Is it possible to make a flag so that it would be ablative rather than functioning like normal armor?
> As in it would have to be destroyed first before anything went through, perhaps increasing the damage the aura item took itself?
> also on a similar note would it be possible to have a flag where it would take no damage?
> If you have any D&D experience, that would be like.. say.. Stoneskin and the Armor spell respectively.

These would be properties of both the damage and item system. In theory, it shouldn't be hard, but we don't currently have a straightforward way of specifying the durability of an item, to my knowledge. Not the way we can vehicle parts

I like the idea (and in particular I think it has merit for non-metaphysical armor), but it's a large project that would need to be tied into adjustments in our damage model, such as some discussions that have been made about revisiting how firearms work against survivors

**Comment by foulman** [comment]
> 
> 
> > What do you think about having the ability to prevent damage passing though, say on the aura layer? Is it possible to make a flag so that it would be ablative rather than functioning like normal armor?
> > As in it would have to be destroyed first before anything went through, perhaps increasing the damage the aura item took itself?
> > also on a similar note would it be possible to have a flag where it would take no damage?
> > If you have any D&D experience, that would be like.. say.. Stoneskin and the Armor spell respectively.
> 
> These would be properties of both the damage and item system. In theory, it shouldn't be hard, but we don't currently have a straightforward way of specifying the durability of an item, to my knowledge. Not the way we can vehicle parts
> 
> I like the idea (and in particular I think it has merit for non-metaphysical armor), but it's a large project that would need to be tied into adjustments in our damage model, such as some discussions that have been made about revisiting how firearms work against survivors

Gotcha, well I hope they can be done in the future, I'd love to sci-fi things up a bit too. I've dreamed of this game being modded out to resemble a much more far future mutated 'Gamma World' environment with force fields and all psychic powers. Are those flags something you think I should work up as another feature request?

**Comment by foulman** [comment]
Also, excellent job on this, you even took it further than I requested! Many thanks! 
I'll put it to use as soon as the PR goes through.

**Comment by esotericist** [comment]
> Gotcha, well I hope they can be done in the future, I'd love to sci-fi things up a bit too. I've dreamed of this game being modded out to resemble a much more far future mutated 'Gamma World' environment with force fields and all psychic powers. Are those flags something you think I should work up as another feature request?

These would be appropriate for another feature request, yes.

**Comment by esotericist** [comment]
Having punted some features to later PRs, this should be ready for review.

**Comment by SomeDeadGuy** [comment]
Can some effects like "slimed", "on fire", and others be remade or act as auras? Right now they appear under any clothes you wearing, and this is not how they should look like.

**Comment by esotericist** [comment]
> Can some effects like "slimed", "on fire", and others be remade or act as auras? Right now they appear under any clothes you wearing, and this is not how they should look like.

Effects have nothing whatsoever to do with equipment layers. There should already be a priority system for you to lean on for tilesets. If that isn't working correctly, or if it isn't adequate, that should be a separate issue.

**Comment by foulman** [comment]
Hey, @esotericist ... is there any chance we could get the semitangible flag to exclude weight as well as encumbrance?  I've been unable to make aura holsters/containers for this reason, I could store all the items I wanted in it, but it would still weigh the player down.. and if we can get this in along with the container changes Korg is working on, then we'll have 'extradimensional' storage all sorted out.

**Comment by KorGgenT** [comment]
actually the container stuff will already do that without an additional flag in an unrelated area

**Pull request merged**
