### PR TITLE
Reloaded ammo

### PR DESCRIPTION
**Pull request by ghost**
When that guy rebalanced ammo a while back he didn't touch the reloaded rounds. This brings more common types into line with the new factory ammo stats.

.308
7.62x51mm
.223
5.56x45mm
00 buckshot
.300 win mag
all .45 ACP variants
all 9x19mm variants
.44 mag
5.45x39mm 7N10/7N22

Damage is 5% lower than that of factory rounds and dispersion is higher. Armor penetration is lower for some.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. If I recall, some handloads had been rebalanced, but not all.

**Comment by illi-kun** [comment]
#13755 contains description that for some handloaded ammo "damage [...] is set to 92% (rounded down) of their factory counterparts", so -5% modifier presented in this PR is not in line with previous changes.

**Comment by Nioca** [comment]
Er... actually, with the exception of the 00 buckshot, I had already rebalanced all of those handloads to 92%. I mean, if 95% is considered the better number, that's fine, I'm just saying.

With that said, I'm more concerned with the fact that you swapped the Jacketed Hollow Point and Full Metal Jacket 9mm rounds around. Because you didn't alter the recipes that go with them, the FMJ recipe get used to make JHP, and vice versa. Plus, it personally bugs me a bit to have "reloaded_9mmfmj" referring to jacketed hollow point bullets, and since there's no place where these really spawn (unlike the factory rounds), there wasn't any reason to swap them.

**Comment by mauledbybears** [comment]
@Nioca I missed that. Last time I was here was 2 years ago. I noticed some of the handloads were more consistent than they used to be but didn't look into it.

I switched FMJ and JHP to keep the ids and names consistent between factory rounds and handloads. 9mmfmj is the id for factory 9mm JHP rounds. I'll check the recipes.

**Pull request merged**
