### PR TITLE
Misc json changes

### PR DESCRIPTION
**Pull request by dholmes215**
This time with fewer deplorable tabs.

### CODE REVIEW

**Comment by karlnp** [comment]
Wearable hip flasks!! Finally!!

**Comment by kevingranade** [comment]
What are you attaching the flask to?  The impression I always got was that
they went in a holster dealy or a pocket (or a boot, feel free to add that
one :)

**Comment by Rivet-the-Zombie** [comment]
>What are you attaching the flask to?

Some come with a little tab on the back that can be hooked onto a pocket or belt. Mine came with a leather cover thing that has a loop on the back for the same purpose.

I'm not sure why anybody would wear one on them like that IRL, though. The whole idea is to be discreet and that rather defeats the whole purpose.

**Comment by karlnp** [comment]
You clip them onto your belt or the waistband of your pants, and put it next to your hip. Or they go in a coat or pants pocket. Or you just tuck them into your waistband.

**Comment by Coolthulhu** [comment]
Minor: diamond nodachi loses the new qualities.

**Comment by dholmes215** [comment]
I didn't even know diamond nodachis existed.  I'll add that.

**Pull request merged**
