### PR TITLE
Adjust Smart phone lens

### LINKED ISSUE #28175: Remove high quality lens from smart phones
**Is your feature request related to a problem? Please describe.**  
Smart phones have becomes quite common due to new zombie drop balance, this makes sense. But Smart phones contains high quality lens that can be use to craft survivor telescope and some gun mods.
Can someone really use the lens from a phone to make a scope ?
**Describe the solution you'd like**  
Remove the lens from the disassemble recipe of the smart phone.
Or make it a small lens that will be added to other appropriate recipes.

**Describe alternatives you've considered**  
Change nothing, this doesn't break game balance, it's just a bit weird.
**Additional context**  
I'm willing to do the json edit, but I wanted to ask before what people think of this.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

```SUMMARY: Balance "Change high quality lens in smart phones for small high quality lens"```  
#### Purpose of change

Fixes  #28175
#### Describe the solution

Change high quality lens in smart phones for small high quality lens and adjust some recipe to use 1 high quality lens and 1 small or normal high quality lens.

#### Describe alternatives you've considered

Simply removing the lens from the smart phone.
#### Additional context

I've change the recipe of all the scopes to allow to replace at most one lens with a small lens.
I've change recipe of the laser sights to allow the use of a small lens for either or both of the lenses.
I haven't touch the camera or the magnifying glass.
The small lens does not light fire, is half the weight and half the price of the normal lens and is made of glass. I don't know if it should be plastic instead.
I have not touch the recipes within mods.

### CODE REVIEW

**Comment by Fris0uman** [comment]
I don't get what's failling. It seems that it's something with recip_other but I don't see the problem, even after running it through the linter it still fails.

**Comment by AMurkin** [comment]
Components in recipe_others.json formatted by http://dev.narc.ro/cataclysm/format.html:
```
"components": [ [ [ "plastic_chunk", 4 ] ], [ [ "lens", 1 ] ], [ [ "lens", 1 ], [ "lens_small", 1 ] ], [ [ "spring", 1 ] ] ]
```

**Comment by Fris0uman** [comment]
Ok thanks, I tried that.

But the web tool gives me : 
```   "components": [
    [ [ "plastic_chunk", 4 ] ],
    [ [ "lens", 1 ] ],
    [ [ "lens", 1 ], [ "lens_small", 1 ] ],
    [ [ "spring", 1 ] ]
  ]
```
So I must be using it wrong ... :/

**Comment by AMurkin** [comment]
Just copy and paste it. This line is not yet formatted. Not enough spaces.

**Comment by Fris0uman** [comment]
Ah I see, I was missing  two spaces.
Thanks !

**Comment by ZhilkinSerg** [comment]
Merged to `0.D`.

**Pull request closed without merging**
