### PR TITLE
Fix monster evolution delay bug

### LINKED ISSUE #36821: Evolution doesn't begin until "Initial day" days after spawning
# Describe the bug

If "Initial day" is set to x, then monster evolution doesn't begin until x days from the character spawning.
So if "Initial day" is set to 500, you will spawn on day 500, but monsters won't start evolving until day 1000.

# Steps To Reproduce

1. Create and load a world with "Initial day" set to 500, and set monster evolution to some very fast value (like 0.05 or something).
2. Debug through 495 days or so and teleport through cities noticing only lowest tier zombies.
3. Debug through another 10 days or so and teleport through cities noticing that it is now very scary.

# Expected behavior

Evolution should start on spawn, except when considering the spawn delay option.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-11025-g9fe2e72d43 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Urban Development [Urban_Development],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Sleep Deprivation [sleepdeprivation],
    No Medieval Items [no_medieval_items],
    No Survivor Armor [no_survivor_armor]
]

### PR DESCRIPTION
**Pull request by Trioct**
#### Summary

```SUMMARY: Bugfixes "Fix monster evolution delay bug"```

#### Purpose of change

Fixes #36821
Evolution was being unintentionally delayed depending on the "Initial day" world option. For default settings this delay should've been 60 days.
Since "Initial day" is defaulted to 60, the player begins on day 60, while evolution starts on day 120, which I do not think is intentional.

#### Describe the solution

This fixes the bug by making the upgrade_time relative to turn zero, where before it was relative to initial day.

#### Describe alternatives you've considered

Initially this whole post was about adding an option to change evolution delay to whatever you'd like, but it was decided it'd probably just be best to fix the bug and not add an option for it.

#### Testing

Create some worlds.
Debug through time and space with arbitrary "initial day".
Notice zombies evolve from day 1.

#### Additional context

Go easy on me, I'm new to this stuff.

### CODE REVIEW

**Comment by SirPendrak** [comment]
I have just one question: Is it clarified in game like it is clarified here that if you want to evolution begin together with start of your game, then you need to set exact same number for initial day and evolution start? ( 60 and 60, 95 and 95 ETC and not 60 and 0, 95 and 0)

**Comment by Trioct** [comment]
> that if you want to evolution begin together with start of your game, then you need to set exact same number for initial day and evolution start? ( 60 and 60, 95 and 95 ETC and not 60 and 0, 95 and 0)

Sorry, I might not have explained it too well.
So long as I didn't mess anything up, the only thing initial day should do now is set which day/season you are in at spawn, it shouldn't affect evolution at all. Evolution delay should act relatively to Initial day, which maybe is hard to see in the description of the option.
So with initial day = 10 and evolution delay = 100, evolution should begin 100 days from the day you spawn.
With initial day = 500 and evolution delay = 100, evolution should still begin 100 days from the day you spawn.
If you can imagine replacing the number in evolution delay with the number in initial day, that's what the current system does, effectively setting evolution delay = initial day.

**Comment by SirPendrak** [comment]
I figured i was wrong before your reply, thats why i deleted my question. 
Now about feedback, i would suggest setting the default value of evolution delay to 0. 
It will change existing default worlds, but they existed in state that was most likely a bug or an oversight. Imho evolution is too slow to challenge the players, especially with 2 months of delay. 
Probably a large % of games dont even last 60 days and players wont ever get chance to see any  fancy zombie types.

**Comment by Trioct** [comment]
I'd tend to agree with you on that, I'll set it to [CR] while I'm gone and see if anyone disagrees by the time I'm back.

**Comment by Brian-Otten** [comment]
Sounds like you've  figured out the correct way to implement it, the solution proposed makes perfect sense to me. 
I'd agree with evolution starting at day 0 to be the default value. It's the one that makes the most intuitive sense, encourages risk/reward playstyles (raid early before evolution vs wait until you are fully prepared), and stops the difficulty from lagging all too much, because the player tends to "evolve" much faster than the zombies.
That and getting to see all the evolved zombie content is nice, i have rarely seen them in recent builds.

**Comment by Trioct** [comment]
Sorry for my bad git work, but it was suggested to just fix the bug and take out the option.
So this should make evolution how you'd expect it, starting like normal on day 1.

**Pull request merged**
