### PR TITLE
Remove [HIT_AND_RUN] flag from swarming amalgamations

### PR DESCRIPTION
**Pull request by bloodbowel**
#### Summary
Features "Removes the [HIT_AND_RUN] flag from swarming amalgamations"

#### Purpose of change
Originally this flag was included for manhacks so they would fly around like they do in Half-Life 2. It was later added to various creatures but doesn't make sense when used in certain ways. Flesh raptors seem fine because they flap around quickly in the air and have to wind up to sting the player. It doesn't make sense for amalgamates which are little bug things that scurry around on the ground. There is no reason for them to do this and it just opens them up to get attacked or gives you an easy chance to escape.

#### Describe the solution
I just removed the flag and have them attack normally.

#### Describe alternatives you've considered
Maybe they could have little wings and a stinger instead. Though making them not run makes them more dangerous. The hit and run quality might make them harder to hit in very specific circumstances but these guys are slower than manhacks and the result is usually just giving a sprinting character a few free attacks while they skitter away.

#### Testing
Tested in debug mode in the tutorial room on my computer.

#### Additional context
Amal

### CODE REVIEW

**Comment by Karol1223** [comment]
> It doesn't make sense for amalgamates which are little bug things that scurry around on the ground. There is no reason for them to do this and it just opens them up to get attacked or gives you an easy chance to escape.

Not really. Swarmings actually cause a lot of bleed from my experience. It makes sense for them to run around since it gives more time for their prey to bleed out and get weaker, allowing them to finish it off later. The flag makes perfect sense for this monster.

**Comment by Karol1223** [comment]
I'll let Venera speak on this, he's the one who added them. The reason you usually find them alone is they're the only amalgams that can spawn from the smallest cocoons I'm pretty sure (maybe caustics can as well? but I think caustics start from small cocoons). I believe from the largest cocoons there are chances to spawn multiple.

**Comment by Venera3** [comment]
Adding `CORNERED_FIGHTER` is the solution, that flag didn't exist back when I added them.

Swarming amalgams mostly happen in swarms from the mid-ish game, solo they are a bit of a pushover for the explicit reason of signposting the mutant->cocoon->enemy progression system. Removing hit and run would A) make them way easier to fight in groups and B) prevent the poor beginner survivor from getting away.

**Review by Venera3 — CHANGES_REQUESTED** [review]
As above.

**Review by bloodbowel — COMMENTED** [review]
I tested adding hit and run back in with cornered fighter, but it still runs against the wall.
Cornered

**Comment by bloodbowel** [comment]
>prevent the poor beginner survivor from getting away

That's the problem. There is no reason for it to let them get away. It's also not particularly hard to run from unless you run into a field or something. Just sprint into a house and close the door.

>they're the only amalgams that can spawn from the smallest cocoons

That gives me an idea. Why not then have a similar generic amalgamate spawn from the smallest cocoon with flags for that situation and have the swarming version exclusively spawn from larger cocoons in groups? The early version could also have weaker stats if it's such a hazard without it running.

**Comment by bloodbowel** [comment]
I remember now the kreck does this too, so I guess the hit and run thing has been used like this for a while. I still don't like the mechanic in this context but whatever. I guess it's not a big deal some little creature isn't very dangerous. But the monsters that do this on land really don't have a logical reason to. I don't think it gives a noticeable advantage to "swarming" tactics either. It just makes it much easier to run from whatever it is. But I guess it's not the end of the world.

**Pull request closed without merging**
