### PR TITLE
Simplify computer console data serialization

### PR DESCRIPTION
**Pull request by codemime**

### CODE REVIEW

**Comment by AMurkin** [comment]
With that changes is it still saves translated strings?
Related issue: #20829.

**Comment by codemime** [comment]
Yes, it still does. The issue you referenced requires more extensive changes.

**Comment by BevapDin** [comment]
Data serialization should be done via JSON, not as string. One should be able to read the current format, but as you're going to change this code, why not write proper JSON?

**Comment by codemime** [comment]
Backward compatibility and simplification are my concerns here.

**Comment by BevapDin** [comment]
> Backward compatibility

Valid for the load function, but not really for the save function.

> and simplification.

But why continue the bad style of manual serialization. And the JSON serialization would probably be even simpler anyway.

**Pull request merged**
