### PR TITLE
Leaping from the dash spell effect handled better

### PR DESCRIPTION
**Pull request by MylieDaniels**
#### Summary
Bugfixes "Leaping from dash spells behaves more rationally"

#### Purpose of change
Previously, a dash spell would prompt safety checks for every tile that would be passed through- and simply pressing No would make you ignore the traps and other effects, while saying Yes would cause irrational effects like falling from every ledge you passed through.

#### Describe the solution
Leaping is now a boolean variable for movement, which prevents the player from falling, being hit by liquid fields or other ground effects, or outputting most terrain descriptions (ie, the messages from walking over an item), at least until the tile they land on.
Dash spells will warn if anything dangerous is present at the final location, or if there is a danger that cannot be avoided by leaping.

#### Testing
Jumped around, walked around, jumped over some gaps and acid.

### CODE REVIEW

**Comment by kevingranade** [comment]
Is dash really supposed to be leaping or 'just' accelerated movement?
I know it's used as such by some mutations, but it seems like it's two different things.

Accelerated movement:
Before triggering, check for visible* dangerous tiles, and prompt once to cancel.
If you proceed, you're still entering and stepping on the tiles, so it triggers dangers.
*Invisible dangers, like land mines, will not prompt, but might be mitigated by you not being in the tile once it goes off.

Leaping:
Check whether the target tile is dangerous or if intervening tiles are dangerous to enter even if airborne, prompt to cancel.
Proceed through the tiles, but only interact with airborne elements, except the last tile, which is entered normally.

**Comment by MylieDaniels** [comment]
That definitely makes sense, I'll implement a separate leap spell effect and make dash do as you suggest.

**Comment by Night-Pryanik** [comment]
In case some day this PR will be finished, it should fix #53532.

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
