### PR TITLE
[WiP] Local acidic weather areas

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Features "Local acidic weather areas"```

#### Purpose of change
Revive acidic weather

#### Describe the solution
* Acidic weather will be it's aquivalent normal weather in the area
* Added a range around overmap specials to be acidic.
* Added acidic clouds/thunder/lightning
* Updated weather debug view to exactly see what's going on.

TODO:
* No acidic snow (yet?) Not sure what to do there.
- [ ] Balance acidic effects
- [ ] Change landscape in area
- [ ] Maybe other harmfull effects?!

#### Additional context
Weather debug view:

### CODE REVIEW

**Comment by dissociativity** [comment]
This definitely provides a solution to the chemistry issues we had after acid rain was gone, weak acid is a pain in the ass to come by naturally without it, I'm all for variety and dangerous biomes!

**Comment by dissociativity** [comment]
Anyway, I suggest irradiation with acid rain and irradiated snow?

**Comment by Mecares** [comment]
Is it possible to capture acid with a funnel in acid rain?

**Comment by Vasyan2006** [comment]
Common acid rains are not happening around the emitter. Gaseous chemicals can travel tens and hundreds of kilometers (miles in some countries) until they interact with water in clouds and produce liquid acid. But from a gameplay perspective your solution is much better.
Lets say something produces evaporated acid and it condenses on nearby territory. In this case should its strength be reduced over distance? Rains have maximum strength on nearby chunks and it will decrease to 1 at maximum radius.

> irradiation with acid rain

Better to add irradiation as a separate json properties. Some locations will have only one type of rain, some will have both.

**Comment by nexusmrsep** [comment]
Does the player actually have the option to see clouds? I always though this overlay was only visible via debug options.

Also personally I think it would be better, instead of acid rain radioactivity, to introduce both regions irradiated via fallout (no damage to terrain, just low radiation) and regions destroyed by atomic bomb and irradiated (big crater special, leveled and/or damaged buildings, burnt down forests, ashes everywhere, maybe skeletons, occasional toxic cloud, significant radiation, burnt zombies). Lore states that acid clouds ar the effect of portals, rather then result of atomic activity on the human side, so I think separating this effects would be better then linking them forcefully together.

Wasn't there someone working on terrain overlays that would alter existing terrain by applying damage, looting, survivor activity (boarded barricaded buildings), fungal infection, radiation, flooding etc. to existing terrain models via active swapping of terrain features when mapgen process take place? Or was it just an idea /rumor /hearsay?

Anyway, nice addition.

**Comment by Zireael07** [comment]
@nexusmrsep: The overlay thing was actually worked on, and I believe a minor portion of it actually happened (something something swamps? also something something looted?)

**Comment by dissociativity** [comment]
What's happening with this PR? I thought it was really cool and provided a solid way that wasn't annoying for the player to gather acids, all the while making gameplay more versatile.

The ability for one to look up at the nearby clouds would likely help make it more viable too.

**Comment by kevingranade** [comment]
> Does the player actually have the option to see clouds? I always though this overlay was only visible via debug options.

That's true, but we could make a player-visible version with limited range pretty easily.

**Comment by OzoneH3** [comment]
> What's happening with this PR?

Kinda had no time for anything recently :(
Will continue this eventually. I'll close for now.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/why-was-acid-rain-removed/21609/2

**Pull request closed without merging**
