### PR TITLE
Add gulrak filesystem, a c++17 compliant std::filesystem polyfill.

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
None

#### Purpose of change

Add ghc filesystem, a c++17 compliant std::filesystem polyfill, and convert handwritten filesystem helpers to use it. This helps with writing more portable code and adds a functional `path` class too.

#### Testing

Create a new game, load a game, save and reload the game.

#### Additional context

Prerequisite for #50143.

### CODE REVIEW

**Comment by akrieger** [comment]
I'm not sure the best way to exclude these sources from clang-tidy. Maybe appropriate to create a third_party directory to shove files like these and others which should be excluded from tidy and astyle?

**Comment by kevingranade** [comment]
This comment outlines how to set header-only libraries as system headers in cmake https://stackoverflow.com/a/64748887/280690

**Comment by akrieger** [comment]
I would never have figured out that's how clang-tidy picks those up. Thanks!

**Comment by akrieger** [comment]
Turns out I had to add extra arguments to clang-tidy-wrapper.sh because the build.sh was just passing each file in isolation to clang-tidy without any extra arguments. At first it was complaining it couldn't find `<ghc/fs_std.hpp>`, adding `-Isrc/third-party` to the wrapper made it find the header but complained, changing it to `-isystem src/third-party` silenced the warnings.

**Comment by akrieger** [comment]
```
+ ./build-scripts/files_changed
+ set +x
Analyzing changed files
No files to analyze
```

Hm. That seems wrong. But my changes to files_changed should've only been fixes or new behavior. HEAD^2 syntax didn't seem to work in my vm, changing it to ~2 did.

**Comment by akrieger** [comment]
Reverted changes to `build-scripts/files_changed`, fixed tests Makefile compilation.

**Comment by akrieger** [comment]
```
+ ./build-scripts/files_changed
LICENSE.txt
Makefile
build-scripts/clang-tidy-wrapper.sh
src/CMakeLists.txt
src/filesystem.cpp
src/filesystem.h
+ set +x
src/third-party/CMakeLists.txt
src/third-party/ghc/LICENSE
src/third-party/ghc/filesystem.hpp
src/third-party/ghc/fs_fwd.hpp
src/third-party/ghc/fs_impl.hpp
src/third-party/ghc/fs_std.hpp
src/third-party/ghc/fs_std_fwd.hpp
src/third-party/ghc/fs_std_impl.hpp
tests/Makefile
Analyzing changed files
3489 warnings generated.
Analyzing remaining files because build-scripts/clang-tidy-wrapper.sh was changed
```

Better, but now the whole codebase is going to barf.

**Comment by akrieger** [comment]
`clang-tidy` build is passing on the new code, it's just failing on the rest of the repo because I actually touched the `clang-tidy` script so it's rerunning the checks. I've fixed every build failure I've found so far, I just haven't managed to get all the builds to run without timing out eventually.

**Comment by akrieger** [comment]
Reverted the change to the clang-tidy wrapper since it's not needed after fixing the cmake build finally.

**Comment by akrieger** [comment]
This is finally ready and passing CI. The only thing I'm not sure about is the exact place in the Makefile that is best to add the include path.

**Comment by akrieger** [comment]
Rebased, moved include directory flags to CPPFLAGS.

**Comment by ZhilkinSerg** [comment]
Android build is broken - https://github.com/CleverRaven/Cataclysm-DDA/runs/3449081942

```
 /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/filesystem.cpp:16:10: fatal error: 'ghc/fs_std_fwd.hpp' file not found
  #include <ghc/fs_std_fwd.hpp>
```

Probably `src/third-party` should be mentioned in Android Makefile.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/window-version-dosent-support-creating-world-use-chinese-characators/26929/2

**Pull request merged**
