### PR TITLE
[Xedra Evolved] Maintenance

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Mostly stuff that i ought to add or want to do in some sort of preparation to the future
#### Describe the solution
new melee weapon for inventor
two spells for dreamer: "return critters", that pull your summons back to you, and "lucid dreams", that works as advanced version of winch
remove CONCENTRATE flag for spells, see Additional context
replace `"skill_penalty": -100` in recipes with `"skill_penalty": 0` that is effectively the same, but looks better
fix that annoying bug with flamer
#### Testing
Tested, works mostly as expected, just needs_ammo makes me feel sad because it is broken
#### Additional context
So, i don't like current spell system. I don't like people grind levels 24x7 reading artifacts, i don't like player that just obtained their class is obligated to grind spell, and i don't like to copy MoM approach with crafting recipes.
my proposition: doesn't exist yet, i'm still trying to think about it - i found that spell difficulty can be a negative value, and i would like to make some sort of consciousness stat, and the less you have one, the better you cast spells, so player who just got a class can cast a spell if they got hammered or high, but without clear understanding how it would be played (and when the only thing i can use is focus, that is imo broken beyond repair) i don't feel good making any changes
any ideas?

### CODE REVIEW

**Comment by Standing-Storm** [comment]
> i found that spell difficulty can be a negative value, and i would like to make some sort of consciousness stat, and the less you have one, the better you cast spells, so player who just got a class can cast a spell if they got hammered or high, but without clear understanding how it would be played (and when the only thing i can use is focus, that is imo broken beyond repair) i don't feel good making any changes any ideas?

You could edit the effects of drunk (and high etc) to provide some sort of vitamin. There'd (currently) be no way to display it in the spell UI, but if you made the actual spellcast NO_FAIL and then made an EoC with an x_in_y based on your level of that vitamin, it'd be possible to makes spells that have a better chance to work or better effects the more smashed you are (or the longer you spend smashed).

**Comment by GuardianDll** [comment]
Oh, i mean not exact implementation, but "would it be fun to play and use"

**Comment by Standing-Storm** [comment]
Based on what I've seen on reddit, there are absolutely players who would do a ton of cocaine to make their fireballs stronger.

**Comment by GuardianDll** [comment]
Sure, but from another side it shifts the "find a thing (book) and use it 24x7" issue to "find a thing (drug) and use it 24x7"

**Comment by Standing-Storm** [comment]
That is true, but a drug has inherent downsides in a way that a book does not that mean the player has to make a choice.  Especially if the spells still work without being high, they're just at 50% effectiveness (or whatever), then the player has a choice of using the lower powered spells with no side effects, or chugging a 40 before heading into battle.  Being strung out on cocaine 24/7 is not sustainable the way holing up in your wizard's tower with a book is.

**Comment by Rokharn** [comment]
About spell system.

For example, if the spells do not gain exp at all in normal ways, this would prevent 24/7 grinding. For example, if the only way to gain spell level is spell school 'proficiency', which add fixed values of spell levels like +3, +6 and so one (for all spells of this school, even future ones, depending of spell difficulty too, newbie proficiency, surely, will not add levels to master spells), the player will begin to gain this proficiency by playing normally (if wish), not just reading scrolls for the seasons. At least this is little more fresh, as regular player I am very tired to all of this 'reading grind', when starting a new game again (mostly after each of new stable game version).

If new spells unlocks via some kind of evolution, like lesser vampire evolving to better version via finding better and stronger blood or some kind of powerful 'limbs' and so on (or newbie mage create some kind of elixir or some other magic stuff), player will start to explore world, not just sitting at their 'wizard tower' and time to time teleport to forge for some new knowledge after find just one or two forge of wonders (this 'tower' way to play is most common for Magiclysm at least, I have not Xedra Evolved deep play experience). 

MindOverMatter have same problems most parts, imho. People forced to grind much. Not so much as Magiclism, but the full spring month at least to achieve enough power to not failure their mind abilities (and no, new longer way to cast it not so helpful here, imho, this is just a last resolve). I like how leveling up their concentration spells at the same time. It's just working and leveling up themselves, when you doing your things like running away from some dinos or lost in the mine. 

But all this is just my humble opinion.

**Comment by GuardianDll** [comment]
Yes, removing the grind is the end point of this all
At this moment i implemented a system, that gives you percentage amount of experience for your level, so i can specify how much casts you need to level said spell (so i can make player learn 1 level after the first cast, but right now there is used a formula, related to mana cost of a spell), and a system, where leveling a spell grant you access to more different spells
After testing i found:
player that just got it's class and first spell completely unable to use said spell because it is too small level, and player's deduction skill is too low - in magiclysm it was countered with reading books giving you both spell level **and** training your spellcasting, up to the spell difficulty
Low level spells are barely usable - most spells are designed to be used around spell lvl 10, not 0 - in magiclysm it was countered by grind
potentially, when spell happen to be very useful, it level grows enormously fast, because of beforementioned percentage experience mechanic - i don't consider it's bad, but spell curve should be adjusted with this in mind

**Comment by Rokharn** [comment]
> low level spells are barely usable
Maybe it can be a good idea to change basic formula of spell casting from one, which currently calculate success change from 'too difficult' to max to another one, which have fixed base good enough change, but with some penalties from some factors like concentration and so on? If someone already achieves some kind of power at normal way (not by 'finding high end scroll' kind of things), it's have logical sense, this one can already do this kind of things for sure.

**Comment by GuardianDll** [comment]
it actually related to p1 and it may even be better to make spells never fail, but their effect rely on different factors
you can use your spell, but in current condition it lasts only few seconds instead of an hours

which, eeh, returns us to p2

**Comment by Rokharn** [comment]
> but in current condition it lasts only few seconds instead of an hours

Seems like active mutations can resolve this issue. Some kind of 'no level at all' or 'fixed levels' spells, for example. With improving via another sources like artefact passive effects, vitamins, pain/hungry (for example hungry vampyre surely more dangerous to pray, than non hungry one, same for rage berserk, who going to revenge and so on), etc. 

Or massive rebalancing of spell effects, which make it usable even at low levels. For example MoM powers have better balance at this way, than Magiclysm ones (imho), and can be effective using even from the beginning (except of not high% of success issue, mostly via low 'focus' stat) and even till the late game, starting powers too (it's rarely obsolete).

**Comment by GuardianDll** [comment]
\> massive rebalancing of spell effects, which make it usable even at low levels
that's what i want, but i need to find some general formula for output, that will make spells with small level reasonably useful, despite being weak, high level being not OP, save player's interest in leveling spells, but without excessive grind we see now

**Comment by Rokharn** [comment]
I think, good idea to start some kind of survey somewhere about current balance to look at more possible solutions to choice from. 

For example, looking at spell files I starting to compare your spells with Magiclysm ones and MoM too and I imagine a situation in which player choice 3 mods at the same time. Which spell this player prefer if having access to similar ones at one situation or another. 

For example, regular player without any magic perks will start with something about 1200 mana. Your nightvision 'Night Sight' cost all of this player mana, cost not changing after leveling up at all. This kind of vision useful, but player surely prefer (if can) just a cheap lantern or 'Dark Sight' from Magiclysm, which have the very same effect as you nightvision, but for 500 mana and min duration of 100.000 turns (and +45k per level) with same 6 difficulty. I think, comfortable starting duration is at least 8 minutes for utility spells (not a life saving spells like 'create twin') and if looking at the mana cost, may be even more. But, again,  I have not Xedra Evolved deep play experience, so this is just example, nothing more. But players for sure usually choice more, than one of big global mods, so situations, where someone play few mods with mana, very possible. 

Another possible solution is to use another energy source that is not a mana. So you can create your own balance without people being able to compare it with anything. Fatigue, hunger, health, hp (MoM, for example, using stamina and focus) or even something new. 
Or attune effects, adds something new after leveling it up, not just a effect time or cost drop. Something like evolution (maybe non linear) of one spells to another per every level (or less often) or unlocking another power this way, creating spell evolution tree and so on.

**Pull request merged**
