### PR TITLE
Correct Density and Volume of Tailoring Resources

### PR DESCRIPTION
**Pull request by ANickelN**
#### Summary
Balance "Audit Density/Volume of Tailoring Resources"

#### Purpose of change

To audit and hopefully work towards resolving issue #54811 

#### Describe the solution

Went back through the category of resources -> tailoring.json and changed the density and volume in order to match real-world values.

I'm totally confused by whoever did this previously as they arrived at completely different numbers than I did.  Maybe I'm taking crazy pills or misunderstanding.
I checked my calculation over and over based on items available to me and information from manufacturers when possible.

The reason I chose 2mm thick fabric for calculation is because I found that a decent middle ground between thin and thicker articles of clothing.  You can plausibly use it for either thicker or thinner without too much suspension of disbelief.  Bigger sheets of fabric should have actual weight now.

Conversions for sheet fabric is: 
30.48cm (12in) x 60.96cm (24in) x 0.2cm (2mm thick) = 371.6cm3 (rounded to 372ml of space taken)

Conversions for 6 inch square patch is : 
6.1976cm x 6.1976cm x 0.2cm = 7.682cm3  (Rounded to 8ml of space occupied)

My density numbers used:
https://github.com/CleverRaven/Cataclysm-DDA/issues/54811#issuecomment-1185092132

#### Describe alternatives you've considered

Not submitting any PRs and making dinner instead.

#### Testing

Game seemed to run fine, spawned in a few of the abovementioned items without issue.

### CODE REVIEW

**Comment by ANickelN** [comment]
Does anybody have a clue why it is failing still?  It seems to be something with crafting maybe, but I'm unsure why that would be as nothing about crafting was changed in this PR.

**Comment by keampe** [comment]
Paging @a-chancey 

2mm is very thick for cloth - are you thinking that it's folded over several times?

   - Shane

**Comment by a-chancey** [comment]
See #54256 for thickness. I took averages from real life measurements

**Comment by ANickelN** [comment]
I'm going to put this on hold while I look over Chancey's work.

**Comment by ANickelN** [comment]
Chancey's values appear to be generally correct for all of these, so going to close this (for now) as there are much more pressing issues with density in other areas.

**Pull request closed without merging**
