### PR TITLE
sentence case the category names

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
There is no reason to have them all caps, and since #70766 will be able to show them, i think it would be better to show them in ~~lowercase~~ sentence case
#### Describe the solution
sentence case category names

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
There's a good argument for them being in all caps and that's so you can tell at a glance which zone they'll get sorted into. Lower case letters are harder to spot.

Zones are listed with the first letter capitalized and the rest lowercase, as seen below, so maybe that's the best way to do it, as it'd still be easier to pick it out of the mess of text when you examine an item. Then it would be like plastic bag < 200 Food

image

**Comment by GuardianDll** [comment]
i made it because #70766 would make it pretty ugly
image
and Andrei's response was 

> I don't want to mangle them in code.

**Comment by Qrox** [comment]
Maybe add a new name field that is used in non-header contexts then?

**Comment by GuardianDll** [comment]
that's beyond my abilities

**Comment by fairyarmadillo** [comment]
> i made it because #70766 would make it pretty ugly

Yeah, I understand, I'm just suggesting it be "Food" instead of "food". "Food" looks good and stands out.

**Pull request merged**
