### PR TITLE
Add a variety of marine plants

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Content "Adds a variety of marine plants, fixes some bugs related to diving and surfacing."

#### Purpose of change

#70341 got posted. I came up with some ideas. I had half an hour to kill. Now we have marine plants.

#### Describe the solution

Adds green algae, red algae, sugar kelp, bladderwrack, sea lettuce, sea anemones, and sea sponges.

Green and red algae are inedible varieties that grow in shalow and deep water, and are by far the most common marine plants. They can be harvested, and the resulting seaweed can be dried and used as fuel for fires. There are probably a million other things that could reasonably be done with it.

Sugar kelp can be harvested with a knife in spring or summer. It gives you big pieces of edible kelp which can be dried to make kombu. Kombu is great for making soup stock. It only grows in deeper water.

Sea anemones are basically just decoration that grows underwater. They can also be used to spice up marine map specials.

Sea sponges are just decoration for now. If someone comes up with a crafting recipe, we could turn them into cleaning sponges.

Dots some random stuff around the sea floor. I tried making kelp patches work, but I couldn't get the game to automatically generate map extras on the ocean floor.

Shallow water plants:

Bladderwrack is edible, and is a component in a lot of natural (probably fake) medicine. One thing that it does do is act as an anticoagulant, but studies show that eating it doesn't seem to have much of an effect due to low intestinal absorption: https://pubmed.ncbi.nlm.nih.gov/19696660/ Maybe we can use it for something later, but for now it's just food.

Sea lettuce is another edible seaweed. Like bladderwrack, it can be found in shallow water.

Currently, these two plants don't spawn because I'm waiting on #70173 so I can add them to the jsons there.

attn @I-am-Erk - I don't want this stuff to conflict with what you're working on, I'd appreciate a review if you get time. Specifically I want to make sure the method I used to spawn plants underwater is acceptable.

**Bugfixes**

It was impossible to swim all the way to the bottom of the sea (or a lake) because the game was only checking for WATER_CUBE and not GOES_UP. I've fixed this. It was also impossible to dive in some circumstances because a check for DEEP_WATER was missing, I fixed that too.

#### Describe alternatives you've considered

I tried to make kelp patches and kelp forests, but I was having difficulty getting map extras or anything else to spawn on the sea bed, so for now I'm just adding these plants and items so anyone who wants to take a crack at that has some stuff to work with.

#### Testing

- Wandered around, harvested some plants, saw that I was getting the right items from them.
- Tried harvesting kelp without a knife. This was impossible. I came back with a knife and it was fine.

#### Additional context

yes i know anemone and sponges are not technically plants

image
For now, this is how the sea floor looks. The New England seabed has a lot of boulders, apparently.

### CODE REVIEW

**Comment by Karol1223** [comment]
> Currently neither. Unless there's some unforseen problem, some will be like lilypads and some will grow on the sea floor.

In this case this is significantly more exciting than I initially thought. I've been waiting for ages for seafloor spawns.

**Comment by RedMisao** [comment]
Yay molusks will return!

**Comment by fairyarmadillo** [comment]
I can manually spawn the kelp patch, but adding it to regional map settings for the ocean_bed terrain doesn't seem to work. I may just leave that to somebody else for now.

**Comment by Consoleable** [comment]
Very excited for more marine content!

**Pull request closed without merging**
