### PR TITLE
Bark missability & bark bonuses not inherited

### PR DESCRIPTION
**Pull request by Kamejeir**
#### Summary
None

#### Purpose of change

Getting shifting bark, then camouflage skin, getting certain addons (Leaves, Vines, Vine Limbs, Vine Sprouter, Transpiration and Flowering) would cause a downgrade of shifting bark. Since jaundice does not change into what the latter downgrades into (protective bark), the mutation system attempting to get jaundice would result in never being able to get shifting bark again.

Related to bark having troubles, shifting bark was not enjoying blister resist that its predecessor got.

#### Describe the solution

Add more prereqs to the afflicted mutations.

~~Add more checks for the bark variants.~~
Replace the check of bark with a character flag (and add them to the bark variants), idea from the courtesy of Venera3.

#### Testing

Thorns happens to be the only mutation that works properly when going through the issue described. Basing the new prereqs on it in the same manner, shall produce excellent results.

~~As for the C++ part, the checks are identical to the existing one the fix is based on. I would not know how to specifically test this working other than it successfully building. Fire lacks sufficient debug tools afaik.~~

### CODE REVIEW

**Comment by Nebnis** [comment]
Could a similar issue be related to #73907 ?

**Comment by Kamejeir** [comment]
> Could a similar issue be related to #73907 ?

No, but the best solution I could come up with for you is to remove the mutation type from Weak Stomach, Nausea and Vomitous. They should upgrade splendidly afterwards. Stomach Cleanse does not have much issue not being mutually exclusive with them, and Strong Stomach is not in any mutation category, so nothing would really happen (except that a cancel between it and Weak Stomach might be needed to prevent character creation weirdness)

**Comment by Kamejeir** [comment]
Before you ask, no, I won't be adding it in this PR. Fris already slapped me for scope creep.

**Comment by Venera3** [comment]
Don't add hardcoded trait id checks, use a character flag instead.

**Comment by Kamejeir** [comment]
right

**Comment by Kamejeir** [comment]
O merger, I'm having some github troubles. I realize need to check a few more things, so please hold off acting for a few, Don't want the test progress going to waste in the case that everything checks out properly, so that's why I'm not going into draft.

**Pull request closed without merging**
