### PR TITLE
Mainline Filthy Clothes mod

### LINKED ISSUE #26228: Mod Inclusion Project: Filthy Clothing
Use the following issue as a space to discuss the inclusion of:

Mod Ident: Filthy_Morale
Name: Filthy Clothing

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

Based on feedback, complete induction is warranted.

- [ ] - Add filthy clothes as default behavior.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Mods "Mainline Filthy Clothes mod."```

#### Purpose of change
Closes #26228.
Discussion in #26228 revealed that filthy clothing mechanics is working rather reasonably and is ready to be mainlined.

#### Describe the solution
Added a new `FILTHY_CLOTHES` external option which is responsible for the whole functioning of filthy clothing mechanics. Default is true.
Changed `FILTHY_MORALE` and `FILTHY_WOUNDS` defaults to true.
Added a new `No Filthy Clothes` mod with all three options set to false.
Obsoleted `Filthy Clothes` mod.
Removed `Filthy Clothes` mod from the default mods list.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I am afraid that this change will disable filthy clothing for those who enabled it previously. It would be better to obsolete existing "Filthy Clothing" mod and make new "No Filthy Clothing" (with new id).

**Comment by Treah** [comment]
I agree with ZhilkinSerg here as changes tend to get lost in the ether and also if you intend to put that warning on the mod then you would have to literally leave it there forever. As he said it makes much more sense to make a new mod with a new ID and just remove the old one. This solves the problem of not having to keep a warning around that will soon not be needed on the off chance some one comes back after a  year of not playing.

**Comment by kevingranade** [comment]
Agreed with above feedback, the reason it's "no filthy clothes" and included by default is precisely so it wouldn't break saves.
You can migrate it away by adding a "no filthy" mod, flipping all the option defaults to enable filthy clothing features, and obsoleting the filthy clothing mod. Since it's a no-op, you don't have to keep the contents of the mod around, just add it to the mod migration list.

**Comment by Night-Pryanik** [comment]
Ok, will do.

**Pull request merged**
