### PR TITLE
Graded steel weapons 

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Graded Steel Blades"

#### Purpose of change
Adds grades of steel to bladed weapons.

#### Describe the solution
Adds versions of common bladed weapons using different grades of steel. A separate PR will add recipes.

Variants
- [x] Arming Sword
- [x] Broadsword
- [x] Cavalry Sabre
- [x] Cutlass
- [x] Estoc
- [x] Falx
- [x] Jian
- [x] Katana
- [x] Kriegsmesser
- [x] Longsword
- [x] Nodachi
- [x] Rapier
- [x] Scimitar
- [x] Wakizashi
- [x] Zweihänder

#### Describe alternatives you've considered
None.

#### Testing
Debug spawned various examples and killed zombies with them. 

#### Additional context
This will give some practice opportunities for the crafting proficiencies like tempering.
A draft showing how the improved crafting results in a blade that holds a sharp edge better, and improvements in the grip materials to represent the player having a higher technological base.
image

### CODE REVIEW

**Comment by OtpalTS** [comment]
The crafting tab needs to be seriously reworked, because once you try to tab past the weapons tab you will stutter like with food and armor tabs (not long but noticable).
 Also there is the issue that these recipes blot out the crafting menu, meaning you need to either know what youre looking for and know what its named to use the search function or you spend ages looking at slight variations of items. Most of which won't ever be made since if you're already investing in a fairly complicated item with a decent craft time you will go for the best one.
 This of course would be a large project that shouldn't block this or even 0.G. But I feel it should be mentioned, even though i truly think all these metallurgy PRs are extremely neat.

**Comment by Terrorforge** [comment]
No, I think that _should_ block this. Don't get me wrong, I'm also excited about these expansions, but it's really not worth making the crafting menu borderline unusable. It's not just that they crowd out all the other recipes, the variants themselves aren't arranged in a sensible way. They're nowhere near each other and in no particular order, to the point where it's still confusing after you use the search feature. I know the weapons wouldn't be as bad since they don't also have the light/medium/heavy variants, but it's already enough of a problem that I don't want to see it made worse

A possible bandaid solution would be to put them in their own tab in the crafting meny, on the same level as "Weapon" and "Armor". That has it's own problems (e.g. some weapons not being in the "Weapon" tab), but it would keep the other tabs from getting cluttered and would help with the internal organization because you could have subtabs like "Mild steel", "Medium steel" etc. in an order that clearly communicates which materials are higher tier.

**Comment by Drew4484** [comment]
> No, I think that _should_ block this. Don't get me wrong, I'm also excited about these expansions, but it's really not worth making the crafting menu borderline unusable. It's not just that they crowd out all the other recipes, the variants themselves aren't arranged in a sensible way. They're nowhere near each other and in no particular order, to the point where it's still confusing after you use the search feature. I know the weapons wouldn't be as bad since they don't also have the light/medium/heavy variants, but it's already enough of a problem that I don't want to see it made worse
> 
> A possible bandaid solution would be to put them in their own tab in the crafting meny, on the same level as "Weapon" and "Armor". That has it's own problems (e.g. some weapons not being in the "Weapon" tab), but it would keep the other tabs from getting cluttered and would help with the internal organization because you could have subtabs like "Mild steel", "Medium steel" etc. in an order that clearly communicates which materials are higher tier.

Fixing crafting isn't within the scope of this PR, yes it needs to be addressed but if we shouldn't stop adding content until that happens. 

> No, I think that _should_ block this. Don't get me wrong, I'm also excited about these expansions, but it's really not worth making the crafting menu borderline unusable. It's not just that they crowd out all the other recipes, the variants themselves aren't arranged in a sensible way. They're nowhere near each other and in no particular order, to the point where it's still confusing after you use the search feature. I know the weapons wouldn't be as bad since they don't also have the light/medium/heavy variants, but it's already enough of a problem that I don't want to see it made worse
> 
> A possible bandaid solution would be to put them in their own tab in the crafting meny, on the same level as "Weapon" and "Armor". That has it's own problems (e.g. some weapons not being in the "Weapon" tab), but it would keep the other tabs from getting cluttered and would help with the internal organization because you could have subtabs like "Mild steel", "Medium steel" etc. in an order that clearly communicates which materials are higher tier.

Updating the entire crafting system is out of the scope of this PR, other people are already working on solutions for that. I agree that the menus are cluttered but that's currently unavoidable whether adding more melee options or food recipes.

**Comment by Drew4484** [comment]
@bombasticSlacks Before I do all the crafting recipes, mind looking at the damage values?

**Comment by Amoebka** [comment]
This completely breaks CVD upgrades, since that one is hardcoded to check for the default "steel" material. Not a difficult fix, but please don't forget it.
Are you going to make steel variants of bronze swords, too? There's no real reason a khopesh can't be forged out of tempered steel.

**Comment by Drew4484** [comment]
> This completely breaks CVD upgrades, since that one is hardcoded to check for the default "steel" material. Not a difficult fix, but please don't forget it.
> Are you going to make steel variants of bronze swords, too? There's no real reason a khopesh can't be forged out of tempered steel.

Yeah this initial list was thrown together pretty quickly. If you have suggestions, here's the criteria I'm using going forward.

The criteria should be purpose built as a cutting weapon: Survivor versions of existing weapons are fine, but not makeshift as those are going to be too flimsy to be worth the blade.
Cut should be the primary damage, the increases for these weapons are based on them having a hard edge that holds up under use.
One or two handed weapons are fine, it just increases the amount of material the grip uses. Likewise the entire weapon does not need to be metal, just the business end, like a spear.

**Comment by Drew4484** [comment]
> This completely breaks CVD upgrades, since that one is hardcoded to check for the default "steel" material. Not a difficult fix, but please don't forget it. Are you going to make steel variants of bronze swords, too? There's no real reason a khopesh can't be forged out of tempered steel.

CVD requires some C++ which I'm not proficient with so I've moved it to another PR (#59876).

**Comment by bombasticSlacks** [comment]
Why did you move the recipes to a separate PR?

**Comment by Drew4484** [comment]
> Why did you move the recipes to a separate PR?

Just chopping a project into smaller pieces, recipes are a real PITA for this.

**Comment by bombasticSlacks** [comment]
That makes sense. Well FWIW I don't feel comfortable merging this without recipes or other spawns. If Cody sold them that would be fine too, or some other rare spawn but they need to exist somewhere to go in IMO.

**Pull request merged**
