### PR TITLE
Remove monattack.h, mondefense.h and mondeath.h from other headers

### PR DESCRIPTION
**Pull request by Coolthulhu**
Remove `monattack.h`, `mondefense.h` and `mondeath.h` inclusions in headers and include them only in relevant source files.
Add forward declarations where necessary.

### CODE REVIEW

**Comment by KA101** [comment]
I don't pretend to be a great programmer, but this looks like it adds the headers more than removes them.  ???

**Comment by Coolthulhu** [comment]
Yeah, adds some more text, but removes a lot of false dependencies.

For example, now if you want to add a special attack, you need to recompile everything that includes either `mtype.h` or `monstergenerator.h` and that's a lot of files.

There's quite a bit of those in the code, which is why changing a single line in some minor header requires recompiling pretty much the entire program.

**Comment by kevingranade** [comment]
The context on includes is that every #include line directs the
preprocessor to find the named file and *literally* insert it at the
location of the #include, this is then repeated on the newly inserted
code.  Every include can represent a huge amount of code being inserted,
and also as coolthulu points out makes header modifications fan out to
large portions of the files.
For a worst case example, game.cpp was 22MB after preprocessing the last
time I checked.

**Comment by narc0tiq** [comment]
Okay, for maximum hilarity, I figured out how to get doxygen to generate include graphs -- check out [the include graph for monattack.h](http://dev.narc.ro/cataclysm/doxygen/monattack_8h__dep__incl.png) (WARNING: **12,195x1,008px**, 2.2 MB image).

This is a very very good change.

**Comment by KA101** [comment]
So noted.

**Pull request merged**
