### PR TITLE
Add a Reinforced Security Camera

### PR DESCRIPTION
**Pull request by GordanGeeko**
#### Summary

Content "Adds a recipe, an item and a vehicle part for a reinforced security camera."

#### Purpose of change

See above.

#### Describe the solution

The JSON file as shown added.

#### Describe alternatives you've considered

Doing nothing.

#### Testing

I tested it in game and it worked as expected.

### CODE REVIEW

**Comment by GordanGeeko** [comment]
Might need to remove some redundancies in the Item file as it's using copy from?

**Comment by BrettDong** [comment]
You should create a new branch in your fork repository and make commits on your own branch.

**Comment by GordanGeeko** [comment]
> You should create a new branch in your fork repository and make commits on your own branch.

Should I close this PR and try again?

**Comment by bombasticSlacks** [comment]
rebasing this so it will run again

**Pull request merged**
