### PR TITLE
Change default map font for Map and Overmap

### PR DESCRIPTION
**Pull request by KurzedMetal**
#### Summary

SUMMARY: Interface "Change default font height/width for Map and Overmap to make square tiles"

#### Purpose of change
I propose changing the Map and Overmap to an square font. This kind of font is arguably better for showing square shaped multi-tile objects (like vehicles and buildings) and feel more natural, also diagonal distance is kept proportional to cardinal distances.

#### Describe the solution
~I had a good experience using the "White Rabbit" font (which is MIT licensed) in my 1920x1080 22" monitor, I set the height, width and size to 20px, which is a bit higher than the current 8px by 16px font, but with this dimensions it seems to avoid rendering artifacts (using 24px gets even better but may be too big for a default)~

Since CDDA have support for internationalization and needs a default font that supports unicode glyphs for multiple languages (including CJK), it's very hard to find a new font suitable for the overmap, but we still can change the fontheight and fontwidth to generate square tiles for the map/overmap.

#### Describe alternatives you've considered
~I tried looking for other "free" (as in freedom) square fonts with glyphs that look good for a map mode but didn't have much success. This one feels quite good, I specially liked the glyphs for symbols and the only criticism I have for it is that some capital letters may look similar (like A and R or O and D), but that's it.~

Google Nato is the only other "libre" font I found that support for multiple languages and could be used instead of "unifont", but it is distributed in multiple .ttf files, or in the case of CJK languages, even .otf /.otc files which aren't currently supported by CDDA.

If anyone think there are a better for to use as default, please recommend it here.

#### Additional context
The default font used for text and other UI elements seems good enough to me, so I didn't change that.

#### Screenshots
Overmap Current default:

20190327_144957_cataclysm-tiles

Overmap New default:

20190327_145031_cataclysm-tiles

"Map" Current default:
20190327_144952_cataclysm-tiles

"Map" New default:

20190327_145026_cataclysm-tiles

### CODE REVIEW

**Comment by Hirmuolio** [comment]
I agree that square map tiles is much better. But using 20x20 font makes the map show way too small area.


I think 15px is much better. Finding a font that works at that size would be the better solution instead of increasing font size.

Also the font itself doesn't actually need to be square. Non square fonts will just have some empty space in between symbols.

with
  "overmap_fontwidth": 15,
  "overmap_fontheight": 15,
  "overmap_fontsize": 15,

Unifont (current used font). Some of the letters get slightly cut when it is forced to be of this size.
vanilla

wabbit
square

**Comment by KurzedMetal** [comment]
I think the main problem is that font don't get rendered correctly due to scaling, because some players will prefer 16px, other 20px, and other 24px.

Also, the font is not the problem, these rendering artifacts happens with pretty much any font I tried and only on CDDA, it's really weird. I'd dig on that myself but I don't have much experience with C++.

As for the size / font preference, I don't mind, I do think that any square font or size will be better than the current setting.

**Comment by KurzedMetal** [comment]
I was read the code that loads the font and use it (stdtiles.cpp) and found out that setting "fontblending" enables font antialiasing (calls to TTF_RenderUTF8_Blended() instead of TTF_RenderUTF8_Solid()).

I remember at one point that I didn't like "fontblending" because it actually blurs all the font a bit, but when I restest it again I noticed that it actually fixes artifacts, like the "c" that seems like an "o" at 15px that I mentioned in my previous comment.

Since the rendering of the TTF fonts seem to be cached, wouldn't be a good idea activate that by default too? or was that causing any issues for some players?

**Comment by Fracture64** [comment]
Definitely should be a thing, at least in tiles version of game.

**Comment by nexusmrsep** [comment]
Long awaited change. Thanks

**Comment by AMurkin** [comment]
This font supports English only. For example, notes on a map in Russian look like empty boxes.

**Comment by Zireael07** [comment]
I believe Unifont is the current font for exactly that reason - it supports pretty much all glyphs that could be needed.

**Comment by ZhilkinSerg** [comment]
Maybe we need to implement an in-game option for font typeface and size change in game?

**Comment by KurzedMetal** [comment]
I changed only the Map / Overmap font, not the UI font, I just switched to a non-english language and the map and overmap still use english characters. Are you sure guys that any non-english char is used on those?

**Comment by ZhilkinSerg** [comment]
> I changed only the Map / Overmap font, not the UI font, I just switched to a non-english language and the map and overmap still use english characters. Are you sure guys that any non-english char is used on those?

If you switch to non-English language and generate new world/overmaps, city names would use names from that language, thus the won't be rendered in this new font.

**Comment by KurzedMetal** [comment]
I've been doing some search to see if I could find another "libre" font that we could use and supported a large range of Unicode characters and the only one I found was [Google Noto](https://www.google.com/get/noto/).

But it has two problems:

1. it only distributes separated fonts for latin+polish+etc on most fonts, but the [Chinese, Japonese and Korean (CJK)](https://www.google.com/get/noto/help/cjk/) are separated in other files, actually they have 1 font file for each of those.
2. Doesn't seem to distribute .TTF for the CJK fonts, only .TTC / .OTF / .OTC, which isn't supported by CDDA.

So I guess the only option left is to go back to "unifont", until some heavy code improvements are implemented, **but I'll still recommend to set the fontwidth/fontheight to an square size.**

**Comment by AMurkin** [comment]
Can you update "Overmap New default" image in the OP?

**Comment by KurzedMetal** [comment]
@AMurkin: Done

**Comment by Beanzy** [comment]
@Firestorm01X2 You have anything to add here? I think the [square font you've posted in the forums](https://discourse.cataclysmdda.org/t/square-fonts-pack/9681) before looks really good.

SQFnt1
SQFnt2

**Comment by Firestorm01X2** [comment]
@Beanzy 

>You have anything to add here? I think the square font you've posted in the forums before looks really good.

No. There is latest version. 

Watch out-  something may be done not as it should be- I don't have a lot of expirience in creating fonts. But it works.

**Comment by ZhilkinSerg** [comment]
> **but I'll still recommend to set the fontwidth/fontheight for map and overmap to an square size, even with unifont.**

I am working on one thing which looks muchbetter in non-square unifont because tiles are seamless:

_square_

image

_non-square_

image

**Comment by KurzedMetal** [comment]
But I was recommending that with no font or code change.

If you are doing any of that, of course my recommendation wouldn't apply anymore.

TBH I don't even know what you changed, if code or font or what.

**Pull request closed without merging**
