### PR TITLE
[WIP] [CR] JSON - Break item_groups into managably-sized pieces

### PR DESCRIPTION
**Pull request by dopeghoti**
Taking related groups of `item_group`s and putting them in to separate files to bring `item_groups` down to a more manageable size, and to make related groups easier to find relative to each other.

### CODE REVIEW

**Comment by kevingranade** [comment]
This didn't come up earlier, but yes, pulling one group out at a time is
ideal.

**Comment by dopeghoti** [comment]
Yeah, that made a whole lot more sense to me than one gargantucommit that would be inscrutable to reviewers.

**Comment by dopeghoti** [comment]
`copbot` - move with the other cop/police `item_group`s, or put in with the other `foobot`s (e. g. `chickenbot`)?

**Comment by karlnp** [comment]
bots with bots, imo

**Comment by dopeghoti** [comment]
Leaning that way myself, just checking my instincts.

**Comment by SunshineDistillery** [comment]
Hey, can you check out my recent commit. We seem to be working on the same thing at the same time.

**Comment by dopeghoti** [comment]
Per discussion in IRC, note to self:  Don't use too fine a filter to break things up.  Hard floor size of 4KB on individual JSON files; soft floor of 1 kiloline.

After pulling out the `_store`s, consolidate into one `_stores` files.  Pull `police` and `firefighter` with `military` into `civil_service`  Chances are there will be a lot of bits and pieces left behind in `item_groups` after the categorical excisions.  Probably rename to `item_groups_misc`.

I do _not_ want to end up with literal scores or hundreds of `item_group` files; that's going too far in the other directions, even not accounting for game load time issues.

**Comment by SunshineDistillery** [comment]
A bunch of item groups are not located in the item_groups.json, but are actually in the mapgen files for those specific stores. So you could banish some groups, like museum for example, to that building and not even bother with making a new file. 

Conversely, you could move those scattered groups out of their mapgen files and organize them in a locations file, but that seems like madness. Or at least a lot of work.

**Comment by dopeghoti** [comment]
Bundling the `item_group`s that are onlly (or primarily) used to distribute items through terrain as part of world generation on one hand makes a lot of sense, but on the other makes it so that if you're looking for a particular `item_group`, you do't know whether or not it's been thusly bundled.  Pros and cons, but at first reading, I'm leaning against doing so, but I'd love to hear arguments in favor of the idea.

**Comment by Coolthulhu** [comment]
Having all items bundled with the mapgen entries cleans things up a bit by limiting "scope", but makes modding item groups a bit harder and also mixes types of content (mapgen data with item groups).

**Comment by dopeghoti** [comment]
Yeah, @Coolthulhu, that's exactly what I was saying, and exactly why I'm not leaning in that direction at present.

**Comment by Coolthulhu** [comment]
Current master from the one this PR started with, it is very unlikely to get mergeable.

**Pull request closed without merging**
