### PR TITLE
fix terrain glitching on crate opening

### PR DESCRIPTION
**Pull request by PlasmaChroma**
resolves issue #18818

else case was dislocated from crates by pry-ability on coffins

### CODE REVIEW

**Comment by pisskop** [comment]
Im sure it was.

Why is the else needed?  if should have covered both scenarios?  :|

**Comment by mutability** [comment]
See earlier in the function, there's all sorts of other stuff that is pry-able other than crates and coffins.

**Comment by PlasmaChroma** [comment]
This is the least code change which could fix the tiles getting mangled with the uninitialized "new_type".

Looking at what's there perhaps this should be restructured so we don't have special cases spelled out for coffins and crates below, as clearly it seems to be more error prone to work with.

**Comment by PlasmaChroma** [comment]
Other things (not coffins and not crates) rely on setting the variable "new_type" (see above code).

For example if you pry a manhole cover off the else case handles setting it to: new_type = t_manhole;

**Pull request merged**
