### PR TITLE
Added pants and leg armor to class

### LINKED ISSUE #55043: CRIT Expansion Mod: CRIT Automatic Rifleman Profession starts without pants
### Describe the bug

The specified profession only has boxers, and no pants and/or protection on.

### Steps to reproduce

1. Have CRIT mod installed
2. Start game as "CRIT Automatic Rifleman"
3. Notice lack of pants

### Expected behavior

Profession has some kind of pants.
e.g. Army Pants, CRIT pants, Cargo Pants, etc

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod],
    More City Locations [cityside],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Useful Helicopters Experimental [useful_helicopters]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KeaneCarotenuto**
#### Summary
Mods "Added CRT pants and CRT leg guard to class 'Automatic Rifleman'"

#### Purpose of change
The class was missing pants and armor

#### Describe the solution
I added the pants and armor into the JSON file

#### Testing
I made the changes to the JSON file to my game, and loaded the mod, then chose the class, to see that the pants and armor were added.
EDIT:
I have now built the game with my changes implemented, and the class now has pants and leg guards.
Shown here:
image

closes #55043

### CODE REVIEW

**Comment by KeaneCarotenuto** [comment]
Hey @Zireael07, I have seen you around a few times, do you know anything about submitting a fix?
I'm not entirely sure if I have done this right, or if there is more I need to do.

**Comment by Zireael07** [comment]
The fix looks ok, it even got a green tick on first try.

For the rest of the CI tests, you will need a maintainer to come by and allow them to run. Just be patient.

**Comment by KeaneCarotenuto** [comment]
Perfect! Thank you very much for confirming, I shall now wait.

**Comment by NetSysFire** [comment]
I approved the run of the tests, please fix your PR summary though: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#all-prs-should-have-a-summary-section-with-one-line

Also add a closing keyword: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by KeaneCarotenuto** [comment]
Thanks for the info @NetSysFire!
I have changed my summary to be one line, like the examples given, and added the closes key word to the end.

**Comment by KeaneCarotenuto** [comment]
I noticed that one of the tests failed, giving the error "Error: Process completed with exit code 1."
Is this something to worry about?

**Review by Maleclypse — APPROVED** [review]

**Review by NetSysFire — APPROVED** [review]

**Comment by NetSysFire** [comment]
>I noticed that one of the tests failed, giving the error "Error: Process completed with exit code 1."
Is this something to worry about?

There are currently no failed tests. They may sometimes fail literally randomly because of the random seed. In this case it has nothing to do with your change.

There is nothing you need to do here except wait for it to get merged.

**Pull request merged**
