### PR TITLE
Fix magazine capacities for .357 Sig Sauer pistols + Clarify P320 model

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Correct magazine capacity for .357 SIG P320/226"```

#### Purpose of change
Fixes error in magazine capacity discovered while doing #37670.

#### Describe the solution
1. Create new magazine ID with correct capacity
2. Change P320/226 to accept that ID.
3. Add migration entry to new magazine.

#### Describe alternatives you've considered
Not obsoleting the magazine, which leaves an ID with the wrong information in it.

#### Testing
Spawned in loaded P320/226 and a spare magazine before changes, applied changes.
Magazine migrates loaded in gun or not, extra 14/13-15th bullet(s) stays in until fired or unloaded. Gun then only allows 13/12 bullets in.

### CODE REVIEW

**Comment by ymber** [comment]
You get 13 round magazines to fit flush in the compact model P320. These are right at 14 rounds for the full size model.

**Comment by LaVeyanFiend** [comment]
SIG doesn't sell the full-size model in .357 SIG anymore, only the compact.

**Comment by tenmillimaster** [comment]
>SIG doesn't sell the full-size model in .357 SIG anymore

Could you provide a source for this claim?

**Comment by LaVeyanFiend** [comment]
> Could you provide a source for this claim?

Their [official website](https://www.sigsauer.com/products/firearms/pistols/p320/) only lists the Nitron Compact for P320 when restricting caliber to .357 SIG among the 12 variants listed.

**Pull request merged**
