### PR TITLE
[Magiclysm] Condense Attunement UI and simplify json code

### PR DESCRIPTION
**Pull request by b3brodie**
#### Summary
Mods "[Magiclysm] Condense Attunement UI and simplify json code"

#### Purpose of change
Most attunements are permanently visible in both the mutations menu and the effects menu.  This clutters the effects menu and debatably doesn't match the effects menu's purpose, which is in my view for temporary effects rather than permanent additions, which is the mutation menu's purpose.  In this pr I moved the description that was previously viewable in the effect menu to the attunement description itself.

Also, the attunements are largely defined in a large amount of files with a small amount of data within.  I think they can be better represented by moving them into 1 or two larger files.

**Examples:**
Current UI:
pre attunement cleanup edited
This character has both the sun mage and earth elemental attunements.  You can see the permanent attunement affects of the sun mage highlighted in yellow and the earth elemental highlighted in green.  For example, when the player gains the earth elemental attunement they will both gain the permanent mutation and the permanent "Earth Creep" effect.  The only actual temporary effect from the attunements is highlighted in red, which is a power that buffs the player when they are in the sun.

New UI:
post attunement cleanup edited

Note that the doubled effect descriptions are no longer here.  Instead, see that the attunement mutation description contains what the old effect description used to tell the player.  Because of this change, the attunement trait information (typically passive buffs) visible to the player is condensed into one location: the mutation menu.  The effects menu remains only for temporary attunement additions if they do exist, such as the sun mage's sol buff when they are in the sun

#### Describe the solution
Moved the effect description into the trait description
Moved the separately defined enchantments into inline enchantments since they are always on and never will be referenced by anything other than the trait.
Create a couple new files to order the 'toggle' mutations, the effect on conditions, and the infrastructure spells.

#### Describe alternatives you've considered
Clutter

#### Testing
Debugged attunements and looked at descriptions, saw that effects were applied, etc

### CODE REVIEW

**Comment by Maleclypse** [comment]
Basic build test seems haunted.  Couldn't find the text it said was problematic in this PR.

**Comment by b3brodie** [comment]
> Basic build test seems haunted. Couldn't find the text it said was problematic in this PR.

Found it.  I initially did a find+replace on my double space before the newlines to get rid of the two spaces, but as it turns out one of them had three spaces which got turned into one space.

**Comment by GuardianDll** [comment]
I am not sure moving files around accomplish anything but removed blame history of changes

**Comment by b3brodie** [comment]
> I am not sure moving files around accomplish anything but removed blame history of changes

The file movement was a secondary feature of the pr.  Basically, after inlining the enchantments I noticed that all these files within the enchantments directory didn't actually contain enchantments anymore.  Instead, they just had a random assortment of spells, mutations, and eocs with each file containing 1 - 3 of them.

If the blame readability is important enough I can revert the file changes, as it was done just because I found the initial files to be incorrect with their naming / contents.

**Comment by GuardianDll** [comment]
You're good

**Comment by Maleclypse** [comment]
Could you place some before and after pictures to show the difference.  I want to make sure I understand what's changing and how it will look before merging this and my minds eye isn't cutting it today. :)

**Comment by b3brodie** [comment]
> Could you place some before and after pictures to show the difference. I want to make sure I understand what's changing and how it will look before merging this and my minds eye isn't cutting it today. :)

I added a before and after photo to the PR description.  Basically, it merges the UI additions from attunements into just the mutation menu instead of both the mutation menu as well as the effects menu.

**Pull request merged**
