### PR TITLE
Smoker zombie rework/nerf 

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Balance "Turns smoker zombies' cloud of smoke into a triggered attack instead of a constant one"

#### Purpose of change

I like smoker zombies, but I'm not a fan of how their main attack works. While the smoke field they produce makes for an interesting enemy that hides both itself and the horde around it, as well as choking anyone without proper equipment if they get too close, the fact that it's a constant cloud of smoke with little to no opening makes them less of an encounter that needs to be approached with caution and more an annoyance that makes you roll your eyes when you see it. Especially if you meet one indoors where it's hotboxed the entire room.

#### Describe the solution

I've decided to change how the smoker and zombies that behave similarly to it function - The smoke field they constantly produce around themselves is much smaller now, and they were given a new special attack when they see an enemy. ~~This special attack causes them to spit out a smoke cloud similar to the one they do currently for 7 seconds.~~ Attempting to do this, I found that monsters aren't able to emit fields like the player is, so I have to compromise. The smokers now emit a larger burst of smoke on a cooldown of 35 whenever they see the player.
This will make the smoker more manageable without ruining it's main gimmick, by giving players an opening to attack it either by waiting for it's attack to dissipate - or attacking it from stealth or range before it can start smoking. This might also have the effect of not alerting players to their presence prematurely, which is a fun thought to me.

Balance aside I was also hoping this would give the impression the smoker goes "dormant" to preserve biomass, only expelling smoke in large quantities when it's chasing something.
#### Describe alternatives you've considered

If I can't make the cloud a steady stream, I could just make it belch out a spontaneous cloud every couple of seconds.

#### Testing

It works, tested it over the course of a couple days.

#### Additional context

none

### CODE REVIEW

**Comment by Daved27hundred** [comment]
okay "rusty" might have been an understatement let me clean this up
image

**Comment by Venera3** [comment]
Smokers are like the *one* zombie you can't just snipe (without explosives), I don't think taking away their concealment is reasonable. We need more zeds you can't deal with at range not less.

I do like turning the attack into a heftier on-demand smoke cloud, but I wouldn't reduce  their constant emission to the level where they are consistently visible outside of extreme wind.

**Comment by AnotherSeawhite** [comment]
What about making the smoke from smoker zombies harmless? I think current smoke being equivalent to smoke from fire is the major issue of the smoker zombies.

**Comment by carlarctg** [comment]
Make it an evolution thing. Smoker zombies being the hulk-evo of this new one

**Comment by Nebnis** [comment]
> Smokers are like the _one_ zombie you can't just snipe (without explosives), I don't think taking away their concealment is reasonable. We need more zeds you can't deal with at range not less.

> I do like turning the attack into a heftier on-demand smoke cloud, but I wouldn't reduce their constant emission to the level where they are consistently visible outside of extreme wind.

Probably reduce their cloud of visibility then, just enough to hide the zombie but not enough to fill an entire screen with smoke. I feel like the current smoke generation sometimes also benefit the player, because it hides you from a zerg or prevent enemies from seeing from inside.

**Comment by Daved27hundred** [comment]
> I do like turning the attack into a heftier on-demand smoke cloud, but I wouldn't reduce their constant emission to the level where they are consistently visible outside of extreme wind.

I think I'll do this. I'll start with a qty value of 8 and test that, see if it needs to be increased or not

**Comment by fairyarmadillo** [comment]
Iin #71717 I discovered that gas-emitting enemies were creating a lot of lag. It sounds like the solution you have here is going to result in fewer overall field tiles per smoke zombie, which might help a lot if something similar is done to the nuckalavee and hound of tindalos.

In the linked issue, I was noticing more lag on poison gas than on regular smoke, but ymmv.

**Comment by Daved27hundred** [comment]
> What about making the smoke from smoker zombies harmless? I think current smoke being equivalent to smoke from fire is the major issue of the smoker zombies.

Apart from me thinking that would make them a trivial enemy, since smoke inhalation is the bigger drawback to their smoke field than vision blocking, I'm not sure how to create a new smoke field from scratch.

> Make it an evolution thing. Smoker zombies being the hulk-evo of this new one

I think that would defeat the purpose of what I'm doing...I do have some smoker evolution ideas though. Those aren't coming until a later PR.

>I discovered that gas-emitting enemies were creating a lot of lag. It sounds like the solution you have here is going to result in fewer overall field tiles per smoke zombie, which might help a lot if something similar is done to the nuckalavee and hound of tindalos.

I looked and it seems the emit they use has a quantity of 24, like the smoker, which is a lot per second. I'll think about it.

**Comment by fairyarmadillo** [comment]
I feel like you wouldn't need much passive emission to screw with guns as long as line of sight is broken every 2-3 seconds.

**Comment by Venera3** [comment]
Just for the record, you don't need to care about the performance impact for JSON work - if there's an optimization to be made it should be made in code, not plastered over with restricting the design space. It also sends you down some very misleading routes since if you're not using an actual profiler the Mark One Eyeball™ is not that helpful.

**Comment by Daved27hundred** [comment]
I've hit a roadblock - The attack works, but since it's a spell it only produces smoke when casted rather than for the duration. 

I tried editing the spell to cast an effect that created the smoke field, but apparently monsters are unable to use proper emitters. I tested the spell on the player and it worked fine, but the zombie just couldn't use it. 

I don't have any ideas of how else to approach this - any ideas?

**Comment by zachary-kaelan** [comment]
In the docs it says only a small subset of enchantment values can be applied to monsters. I checked the code, and it may only apply an enchantment to monsters if it has one of those values. Try adding `{ "value": "ARMOR_HEAT", "add": 1 }` and see if it works. If it does, then the code needs a change.

**Comment by Daved27hundred** [comment]
> In the docs it says only a small subset of enchantment values can be applied to monsters. I checked the code, and it may only apply an enchantment to monsters if it has one of those values. Try adding `{ "value": "ARMOR_HEAT", "add": 1 }` and see if it works. If it does, then the code needs a change.

what should I be able to see, if adding that line works?

**Comment by zachary-kaelan** [comment]
> what should I be able to see, if adding that line works?

The monster should be able to apply the field to itself. Hypothetically.

**Comment by Night-Pryanik** [comment]
@Daved27hundred care to resolve conflicts?

**Pull request closed without merging**
