### PR TITLE
Mana softening

### PR DESCRIPTION
**Pull request by adamkad1**
#### Summary
Mods "Makes mana soft"

#### Purpose of change

Makes concentrated mana a soft material to unrigidify certain things. Stone gauntlets explicitly say they are flexible, and stormfist... how can lightning be rigid anyway? Bonus points for the fact that this change will make magic actually be able to put those things over rigid equipment instead of summoning to your hands because you are allready wearing armguards or something.  Kinda wish we had different ways to make things rigid/not rigid than 'Is the material soft?'

#### Describe the solution

To make magic arm things non rigid, mana has been made a soft material

#### Describe alternatives you've considered

None. If anyone else got better idea, you are welcome to replace this.

#### Testing

Do this, check in game, magic stuff arent rigid anymore

#### Additional context

Nothing here

### CODE REVIEW

**Comment by GuardianDll** [comment]
Does it cause any problems with armor or stuff?

**Comment by adamkad1** [comment]
> Does it cause any problems with armor or stuff?

It makes things comfortable but as far as I know, nothing else changes.

**Review by GuardianDll — APPROVED** [review]
Then i see no problem to make it soft

**Comment by adamkad1** [comment]
> Then i see no problem to make it soft

If anything, someone who knows what they would be looking for could check it, but I didnt notice any stat changes

**Comment by GuardianDll** [comment]
image
image

Now someone need to add length to all items that uses concentrated mana as material 😆

**Comment by adamkad1** [comment]
> image image
> 
> Now someone need to add length to all items that uses concentrated mana as material 😆

XD putting your magic hammer in a bottle is the funniest shiz

**Pull request merged**
