### PR TITLE
Fix invalid JSON

### LINKED ISSUE #25873: Something wrong with lang/extract_json_strings.py
Game version:
#7979.
Operating system:
Linux x64.
Tiles or curses:
Curses.
Mods active:
none but game default.
### Expected behavior
./update_pot.sh has something wrong?
### Actual behavior
When I update the *.pot file,there is some mistake happened in terminal.
Image of Yaktocat
### Steps to reproduce the behavior
none.

### PR DESCRIPTION
**Pull request by AMurkin**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #25873

Note: `chkjson` didn't catch this error

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Please fill out the summary line properly.

**Comment by AMurkin** [comment]
Why is it not proper now?
It's tiny fix. Why push it to changelog?

**Comment by ZhilkinSerg** [comment]
`SUMMARY: None` is valid line.

**Comment by narc0tiq** [comment]
> `chkjson` didn't catch this error

Probably because the in-game JSON parser doesn't care, whereas the Python JSON parser does.

**Pull request merged**
