### PR TITLE
Support total conversion mods

### PR DESCRIPTION
**Pull request by mugling**
Groundwork for supporting total conversion mods. A conceptually much simpler approach than the previous whitelisting attempts (which were complex and contained many bugs).

* Initial cleanup of mod loading code
* Adds support for `core` content packs which are loaded before all other content
* `dda` is the first `core` pack and also enabled by default for all games
* Unit tests and `--dump-stats` both use the `dda` core content pack
* Almost all mods currently depend upon `dda`
* Fully backward compatible with all savegames

Next step is to move the minimal number of items from `dda` to `data/core` and then other contributors can begin to write total conversion mods.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This seems like the inevitable evolution of our mod manager. Cool idea!

**Comment by mugling** [comment]
Added bonus - non-content mods (for example fast zombies) are now much quicker via `--check-mods`

**Comment by Coolthulhu** [comment]
`--check-mods` spews many pages of errors.

**Comment by mugling** [comment]
Found it - some mods were lacking a dependency on `dda` - all mods are going to require this until we have moved the minimal definitions required to prevent load errors to core. Should be fixed by latest commit.

**Pull request merged**
