### PR TITLE
Ranged rebalance. Shifting bonuses from mods to guns.

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Ranged rebalance. Shifting bonuses from mods to guns
https://github.com/CleverRaven/Cataclysm-DDA/issues/24429

# Idea
**Expected behavior:**
Ability to hit with ranged weapons is dominated by skills, stats, and firearm properties.
A highly skilled player with a good gun can achieve maximum firearm performance.

**Current behavior:**
Mods provide a disproportionate amount of gun accuracy.
It's impossible to reach peak gun accuracy without a heavily modded gun.
Proposal is that we shift the majority of gun accuracy from mods into the underlying guns, de-emphasizing the importance of gun mods for basic gun performance.

# Plan
- [x] Remove all non-sight gunmods from accuracy tests.
- [x] Reevaluate which sights are applied at each level to make them appropriate for the level of advancement.
- [x] Rebalance underlying guns and accuracy code to make tests pass again.

https://github.com/CleverRaven/Cataclysm-DDA/pull/24593

# Old range table:
Characters definition: https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403

Character | >50% good | <10% good
-- | -- | --
Novice pistol | 5 | 15
Novice shotgun | 6 | 16
Novice SMG | 6 | 18
Novice rifle | 9 | 25
Competent pistol | 13 | 35
Competent shotgun | 15 | 37
Competent SMG | 20 | 55
Competent rifle | 30 | 90
God pistol | 20 | 120
God shotgun | 24 | 124
God SMG | 30 | 190
God rifle | 60 | 800

# New range table:
Characters definition: https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403

Character | >50% good | <10% good
-- | -- | --
Novice pistol | 5 | 15
Novice shotgun | 6 | 16
Novice SMG | 6  | 18
Novice rifle | 9 | 25
Competent pistol | 15 | 33
Competent shotgun | 15 | 33
Competent SMG | 20 | 40
Competent rifle | 24 | 48
God pistol | 20 | 120
God shotgun | 24 | 124
God SMG | 30 | 190
God rifle | 60 | 800

# Sights for tests:
Unskilled shooter:
* No sights

Competent shooter:
* Red dot for pistol and shotgun. They considered for short range usage mostly without mods and good scopes.
* Telescopic sight for smg and rifle.

Expert shooter:
Best scopes/sights attachable.
* Scopes if attachable. 
* Holo sight otherwise.

# Individual gun changes:

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Ok. Now we have no mods in test except sights/scopes.

Tests should pass.

**Comment by Firestorm01X2** [comment]
>What's the justification for the adjustments to the tests?

Good thing that most tests passed without serious modification.

There are only 2 tests resisting mostly:
* Competent SMG 
* Competent Rifle

Second mostly because I've replaced ruger mini with suspiciously small dispersion of 100 to AR15 with dispersion 150

Other than that a skilled "shooter with an accurate pistol" was underestimated initially
an expert shooter with an excellent pistol just have reduced <10% range. It was sligtly longer than it should be.

To achieve all of that I have to increase accuracy of all base guns on 20%  approximately (dispersion divider 18 instead of 15)

**Comment by Firestorm01X2** [comment]
Well. Now all mods has relatively same dispersion effect. No more -90 and -60.

Ready.

**Comment by Firestorm01X2** [comment]
Looks like the only mods that for some reason gave suspiciously good bonus to dispersion were long barrel (-90 dispersion) and hare trigger (-60 dispersion).
Positive bonuses for dispersion from other mods are in range of [15,40]. So other mods should be fine.

**Comment by kevingranade** [comment]
All barrel mods should go away.
Remaining non-sight gunmods should improve dispersion by no more than 5 or so, otherwise they still contribute significantly to accuracy and invalidate the balance established by the tests.

**Comment by Firestorm01X2** [comment]
>Remaining non-sight gunmods should improve dispersion by no more than 5 or so, otherwise they still contribute significantly to accuracy and invalidate the balance established by the tests.

5 is wothless. Istnalling it gives literally no effect considering scaling effect of skill.

**Comment by Firestorm01X2** [comment]
Also look at this:
http://jaggedalliance.wikia.com/wiki/Gun_Barrel_Extender

Somehow Jagged Allinece 2 can live with barrel extension.

**Comment by Firestorm01X2** [comment]
I recommend to split "fixing" https://github.com/CleverRaven/Cataclysm-DDA/issues/24429 in multiple parts.

Current PR still valuable bacauese of removing non sight gunmods from tests and establishing balance without them.

Also it inculed nerfing 2 most positively affecting accuracy gunmods.

Other work can be done via JSON only (I hope).

**Comment by kevingranade** [comment]
> You basically asking to remove all non sights gunmods affecting accuracy. 

Correct.

**Comment by Firestorm01X2** [comment]
>Correct.

Great.

It can be done via JSON only. And will get resistance. For sure.

**Comment by kevingranade** [comment]
Nope, because taken alone, this PR is a gigantic ranged weapon buff.
I don't want to split the two and have the mod removal mischaracterized as a nerf, even though in reality there is no balance change since the buffs in this PR are what compensates for removing the mods.

If you don't want to remove the gunmods, sit tight and I'll put up a PR doing it.

**Comment by Firestorm01X2** [comment]
>If you don't want to remove the gunmods, sit tight and I'll put up a PR doing it.

Ok.

**Comment by Firestorm01X2** [comment]
Alternate proposal.
Instead of making accuracy affecting mods useless dispersion modifier maybe replaced with handling.

**Comment by Firestorm01X2** [comment]
I've reverted my gunmod changes becuse of: https://github.com/CleverRaven/Cataclysm-DDA/pull/24593

**Comment by Firestorm01X2** [comment]
@kevingranade  
Probably you are going to tweak mods without PR.

 In this case, please test your changes.

My assumption is that dispersion -5 do not do any effect on accuracy, due to scaling dispersion (dividing on 15)

I've explained it here: https://github.com/CleverRaven/Cataclysm-DDA/pull/24479#issuecomment-409301775

It should be at least -15 to get at least some effect.

**Comment by kevingranade** [comment]
Rebased and merged with item obsolescence.

**Pull request closed without merging**
