### PR TITLE
Add qualities to copy-from recipes in mods

### LINKED ISSUE #70884: [Magiclysm] XL demon chitin armor needs no tools
### Describe the bug

Unlike the regular sized version, the XL demon chitin armor needs no tools.

### Attach save file

N/A

### Steps to reproduce

Look at the recipes

### Expected behavior

I'd expect the same tools needed to make a larger set of the same armor.

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marilynias**
#### Summary
None

#### Purpose of change
Many modded items (mostly XL/XS variants) are missing tool requirements.
closes #70884

#### Describe the solution
since copy-from doesn't copy qualities (see #60257 ), add them to the recipes.
check the mods folder for any recipes that copy from another, that do not have the qualities of parent.
 

#### Describe alternatives you've considered
make copy-from properly inherit, but I'm not into the c++ code yet.

#### Testing
Screenshot_20241213_164543
Screenshot_20241213_170848

#### Additional context
It is possible that some of those are intentional, but I find that unlikely and do not know how to distinguish them.

### CODE REVIEW

**Comment by GuardianDll** [comment]
> I found that "armor_cuirass" does not require any tools?

probably uses default tools defined in forging_standard

**Comment by PatrikLundell** [comment]
The solution description is a bit odd, as the first line seems to indicate the PR removes copy-from functionality, when it appears that it actually works around that deficiency.

I'd probably change the first line to something like 
"`Since` copy-from doesn't copy qualities (see https://github.com/CleverRaven/Cataclysm-DDA/issues/60257 )`:`"

**Comment by LyleSY** [comment]
No issues from my end. I can confirm that anything I did in the mainline or in DinoMod was not intended to skip qualities

**Review by LyleSY — APPROVED** [review]

**Comment by Procyonae** [comment]
Making the copy-from work actually looks really easy, the only issue is it needs loads of stuff going through and doing the opposite of this PR otherwise it comes up with a bunch of errors bc it seems to be storing duplicates as individual entries

Change that appears to work
image

In game result
image

**Pull request merged**
