### PR TITLE
Fix AIM container view

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
Bugfixes "Fix AIM container view"

#### Purpose of change
Originally, the container view of AIM is malfunctioning, showing only the first item in the container. The fix is to make AIM correctly show all items in the container.

#### Describe the solution
Use the same way as dealing with the corpses.

#### Describe alternatives you've considered
No.

#### Testing
All tests passed. In-game testing is also good.

#### Additional context
Before:
image
image

After:
image

### CODE REVIEW

**Comment by SurFlurer** [comment]
Found that moving items out of the container is still malfunctioning. Will figure out.

**Comment by SurFlurer** [comment]
It looks like that when moving items out, the legacy_front() of the container will mistakenly report a null item, causing the container to be considered invalid.

**Comment by Qrox** [comment]
IIRC legacy_front is deprecated and should be gradually replaced with newer container methods. It was from before the nested container update when containers only contained a single item.

**Comment by andrei8l** [comment]
#62547

**Comment by SurFlurer** [comment]
@andrei8l Ohhhh I missed that. Thank you for reminding me! I'll close this then.

**Pull request closed without merging**
