### PR TITLE
Adds lifting capacity to Cantilevers description

### PR DESCRIPTION
**Pull request by Dozed12**
Reported on #16779

Each "JACK" quality point seems to give 500Kg lift, doing the math for the cantilever ...

cantilever_medium: 6 metric tonnes
cantilever_small: 1.5 metric tonnes or 1500Kg

### CODE REVIEW

**Comment by mugling** [comment]
It's quite possible `JACK` and `LIFT` will change. I agree there's a deficiency in the UI but hardcoding these values as opposed to providing them via `item::info` may result in them becoming outdated

**Comment by Dozed12** [comment]
Apologies, I've been away a long time, can you give me an example of an item that uses item::info ?

**Comment by mugling** [comment]
No need to apologies - you are quite correct there's an interface deficiency. I'm looking at doing a PR for item::info now.

**Comment by mugling** [comment]
Actually if you still have that branch your solution is possibly more workable than mine.

**Comment by Dozed12** [comment]
I mean, if the overall goal is to make similar descriptions dynamic so we don't have to change both the item and the description I don't know how this helps xD.

**Comment by mugling** [comment]
> I guess it serves as temporary.

^ this

**Pull request merged**
