### PR TITLE
Fix battery related errors in the CRIT_tools

### PR DESCRIPTION
**Pull request by kwl01skz**
#### Summary
None

#### Purpose of change

It seems that many ups powered crit_tools are not written in the correct format.

- The remaining power cannot be displayed correctly because the ups content is not written correctly.
- Some warnings in the game, because the item uses a battery but has no corresponding pocket.

 

#### Describe the solution
Check and rewrite (done)

#### Testing
crt_mask crt_em_vest crt_helmet crt_mess_kit
Get these things
Check their batteries

#### Additional context
 DEBUG    : crt_helmet needs pocket definitions

 FUNCTION : void Item_factory::check_and_create_magazine_pockets(itype&)
 FILE     : src/item_factory.cpp
 LINE     : 2679
 VERSION  : 0.F-2754-gea98516118

### CODE REVIEW

**Comment by kwl01skz** [comment]
Now we don't have a battery with a capacity of 75. I have to use an ultra light battery with a capacity of 50 instead.

If we can, it may be better to add an ultra light plus battery with a capacity of 75. It is also logical.

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
You are still in draft?

**Comment by kwl01skz** [comment]
> You are still in draft?

Yes, almost all props containing batteries need to be modified.
Last week was a holiday. I wasn't near the computer.

**Comment by kwl01skz** [comment]
The JSON of these items is not written correctly, and its battery power can not be displayed.

#51764  fixes the warning, but it will allow the "power" inside the corresponding items to be taken out.

**Pull request merged**
