### PR TITLE
Weariness and sleep

### LINKED ISSUE #48232: The Elfa mutate "Very little sleep and tireless" are not fit well with weariness
as we know, to make weariness recovering, you had to sleep in order to recovering your weariness, but here's problem, because those mutates, making you not tired enough to sleep, and that means you can't recovering your weariness quickly, and that will be a problem if we wanna have those mutates, we need a solution to deal with this problem.

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
Bugfixes "Enables better interaction between weariness recovery and sleep"

#### Purpose of change

Fixes #48232 (if it works).

Have sleep as a less granular (on/off in 5-minute intervals) input for weariness recovery. Make sleep-affecting mutations affect weariness in a logical fashion. See #48409.

#### Describe the solution

First stage: Adds a new activity level of SLEEP_EXERCISE, equivalent to 0.85 (intermediate value between that suggested in three papers giving ~informative results; listed below under "Additional context"). This is not used for caloric expenditure, since that would require increasing NO_EXERCISE to compensate. It is used for weariness and for the calorie diary.

Second stage: Using the above to enable intermediate average activity levels to give some weariness recovery benefit, by making low_activity_ticks a float and proportionally adding to it (from 0 at LIGHT_EXERCISE to 1 at NO_EXERCISE to 2 at SLEEP_EXERCISE).

Third stage: modifiers (usually mutations) decreasing fatigue gain when awake increase weariness recovery while awake; modifiers (ditto) that increase fatigue recovery while asleep increase weariness recovery while asleep.

#### Describe alternatives you've considered

~~Should things that affect sleep deprivation (the "synaptic regeneration" CBM, most notably) affect weariness recovery?~~ (Kevin says no.)

How cumulative in effect should things affecting weariness recovery while awake and affecting weariness recovery while asleep be? Currently, they are additive if someone is asleep. One could use only the higher of the two while asleep. On the other hand, one could instead have while-asleep rates by default doubling the baseline from awake recovery, although this is a bit trickier to do with intermediate average activity levels.

Instead of "just" mutations (and equivalent enchantments IIRC) affecting recovery, should other things that affect rates.recovery in calc_needs_rates (intensity of sleep + pain) affect recovery during sleep? Should other things that affect these during update needs affect this? (Doing either of these would have the difficulty that weariness is only recovered every 5 minutes, and the mixture of possible levels of effects would likely not work right with just consulting calc_needs_rates - or the equivalent in update_needs - at the time of weariness recovery.)

Is there anything with the programming that could be done in a better manner/style? (E.g., is the use of cata_assert in activity_tracker.cpp correct?)

#### Testing

CI, so far. Tests have been added for the effects of fatigue-affecting mutations on weariness levels and recovery (with and without sleep).

Adding CI tests of intermediate average activity levels is desirable, but unlikely with this PR.

PLAYTESTING IS NEEDED.

#### Additional context

First reference: [doi:10.1155/2010/270832](https://dx.doi.org/10.1155/2010/270832)
Second reference: https://pubmed.ncbi.nlm.nih.gov/3136137/
Third reference: https://www.researchgate.net/publication/6506876_Interindividual_variability_in_sleeping_metabolic_rate_in_Japanese_subjects

### CODE REVIEW

**Comment by actual-nh** [comment]
The "info" in the above was the information re fatigue_mod (and fatigue_regen_mod), so mutations do appear to be input. But now something's going wrong with getting the weary info itself?

**Comment by I-am-Erk** [comment]
commenting to remind myself to look more at the fluctuations you're getting

**Comment by actual-nh** [comment]
This does need some cleanup for, well, C++ style as I understand it - access methods instead of making `intake` and `tracker` public, etc.

**Comment by actual-nh** [comment]
Tests so far were green insofar as these changes go (character suffer test failed on MinGW). Did changes to savegame_json.cpp, which definitely need testing!

**Comment by kevingranade** [comment]
> Should things that affect sleep deprivation (the "synaptic regeneration" CBM, most notably) affect weariness recovery?

This specifically should not touch weariness, which is an entirely physical effect.  This kind of CBM would be useful for extending alert/productive periods for sedentary tasks, not predominately physical ones.

**Comment by actual-nh** [comment]
> > Should things that affect sleep deprivation (the "synaptic regeneration" CBM, most notably) affect weariness recovery?
> 
> This specifically should not touch weariness, which is an entirely physical effect. This kind of CBM would be useful for extending alert/productive periods for sedentary tasks, not predominately physical ones.

OK, I'll treat it as mainly stemming from the body (with the brain having knock-on effects).

**Pull request merged**
