### PR TITLE
Always save the latest created character as a template "Last Character".

### LINKED ISSUE #21862: Auto Save "Last Used" character template
Thought I'd try something different but got off to a really bad start and wanted to start over but didn't save a template as I wasn't expecting to go back to it.  Would have made my life easier if the game remembered my last character.

Should be a simple matter of calling the save character template method at game start and using "Last Used" for the name.  However, I haven't spent any time familiarizing myself with that section of code yet.

### PR DESCRIPTION
**Pull request by OzoneH3**
Closes #21862

### CODE REVIEW

**Comment by Leland** [comment]
Super cool. I can't think of any clean ways to implement the UI for it, but having a way to then actually commit that "Last Character" temporary template to a template proper would be great.

**Comment by OzoneH3** [comment]
@Leland What do you mean by that, to rename the template?!
You could just load the "Last Character" template and then saving it again.

**Comment by Leland** [comment]
@OzoneH3 ahhh right right, you can save it once you load it up. Sweet.

**Comment by Theundyingcode** [comment]
@OzoneH3 That was quick... Thanks, I had just about fired my brain trying to seed learn all the player, map and NPC code for my own project but thought this shouldn't have to wait for be to be ready to sort through more code.

**Comment by notafed** [comment]
Would it be possible to highlight the "Last Character" option (in yellow?) and raise it to the top of the list, for convenience sake, and for the folks with (too) many presets already. At first, I hadn't noticed the new option at all.

**Pull request merged**
