### PR TITLE
TOW Humvee variant

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Content "Added a TOW variant Humvee"```

#### Purpose of change
Adding a new Humvee variant with a TOW.

#### Describe the solution
Adding to vehicle.json and vehicle_groups.json. Also fixed a mistake in vehicle_groups.json that made one of the apcs never spawn.

#### Describe alternatives you've considered
The `military_vehicles` item group spawning more apcs than Humvees or cargo trucks probably needs fixing, but I haven't found much data on the numbers.

#### Testing
Used the launcher, spawned a dozen Humvees to test the ammo in the trunk.

### CODE REVIEW

**Comment by ymber** [comment]
This shouldn't be cutting into the Mk19 version's spawn rate. Also while you're on humvees the M60 version should have an M240.

**Comment by RarkGrames** [comment]
> 
> 
> This shouldn't be cutting into the Mk19 version's spawn rate. Also while you're on humvees the M60 version should have an M240.

I did both.

**Comment by I-am-Erk** [comment]
This is throwing a test failure I'm not sure how to interpret, but that doesn't seem coincidental.
```
vehicle_efficiency.cpp:209: FAILED:
  CHECK( to_gram( veh.total_mass() ) == expected_mass )
with expansion:
  5503245 (0x53f90d) == 5501345 (0x53f1a1)

0.128 s: humvee on pavement, full stop every 5 turns
0.128 s: vehicle_efficiency
```
I'll rerun the tests but I wonder if this thing is too heavy for our CI tests.

**Comment by anothersimulacrum** [comment]
I made a PR onto @RarkGrames branch to fix that

**Comment by RarkGrames** [comment]
> 
> 
> This is throwing a test failure I'm not sure how to interpret, but that doesn't seem coincidental.

Per my experience so far every change to vehicle weight makes this test fail, but I don't now anything about it.

Thank you guys for fixing it anyway.

**Pull request merged**
