### PR TITLE
Interface: Add option to edit height, age and blood type to debug menu.

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Interface "Add option to edit height, age and blood type to debug menu."`

- Additional changes: Resolve 'add an effect' hotkey conflict

<br />
Hope you like it.

---

#### Screenshot(s)

Before:

grafik

After:

grafik

grafik

### CODE REVIEW

**Comment by Qrox** [comment]
While you are at it, can you also change the hotkey for `Add an effect[t]`, which conflicts with `Edit s[t]ats`?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> While you are at it, can you also change the hotkey for `Add an effect[t]`, which conflicts with `Edit s[t]ats`?

Changed.

**Comment by gkarfakis19** [comment]
My worry is that this bloats the menu too much with non-essential options that don't really help the debug menu, well, debug. Perhaps you could folder them under a "Change misc options" category?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> My worry is that this bloats the menu too much with non-essential options that don't really help the debug menu, well, debug. Perhaps you could folder them under a "Change misc options" category?

Sure, let me see waht I can do as soon as I'm back home.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> My worry is that this bloats the menu too much with non-essential options that don't really help the debug menu, well, debug. Perhaps you could folder them under a "Change misc options" category?

Changed. Fine now?

Those values might be interesting for role-playing and character-migration reasons. I wouldn't consider them non-essential.

**Pull request merged**
