### PR TITLE
Ballista is 160x less accurate, and other nerfs.

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Balance "Ballista is no longer pure magic"

#### Purpose of change
Magic ballista

#### Describe the solution
Remove magic, apply realism

#### Testing
Not yet.

#### Additional context
The sight dispersion is still way lower than I believe it should be, but I don't feel like digging through scientific papers to find an even worse figure.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
I tried baking the sight_dispersion into the sights and using an integral sight mod called "angle shooting", but our math assumes you are using a vaguely gun-like object and not a crew-served weapon.

I'm running out of ideas to make this possible in the game without coding completely new shooting methods. Which I will not do. If I get to that point, I will change the PR to removing it.

**Comment by wwkk222208** [comment]
I agree that the ballista is too powerful and needs to be nerfed.  However, sight_dispersion and dispersion actually have some “magical principles“. For guns, dispersion has a relatively reliable correspondence with real-world data. I can't be sure if it was intentionally set by the previous contributors, but the current rifle dispersion setting does roughly meet 100 dispersion = 1 moa (in the real world). 

In addition, sight_dispersion also has a relatively clear meaning. Before using the sight to aim and shoot, the user can perform efficient "point shooting", and in this stage, the sight does not take effect. The lower limit of recoil in "point shooting" is 100-200 (determined by the user's perception). Therefore, when the sight_dispersion of a weapon exceeds 200, it only indicates that the weapon has no auxiliary sighting device. For the mechanical sight of a general standard rifle (and a crossbow with a mechanical sight), its sight_dispersion is 30. For a crossbow with only simple auxiliary sighting, following the direction of the crossbow itself can also roughly help to determine the aiming direction. Thus the sight_dispersion of the wood crossbow is set to 90.

In general, I think the accuracy data of the ballista should roughly refer to the wooden crossbow.

**Comment by KnifeFightBears** [comment]
There are historical accounts of Ballistae picking off single infantry at 500 yards, it's a siege weapon designed to engage armies in battle and the physical principles of how they operate make them naturally quite accurate

Maybe don't represent this item in the game at all if you have to make it a wooden crossbow on a mount; crossbows are not ballista, ballistas are not "Big Crossbows" even if they operate in superficially similair ways.

**Comment by wwkk222208** [comment]
> There are historical accounts of Ballistae picking off single infantry at 500 yards, it's a siege weapon designed to engage armies in battle and the physical principles of how they operate make them naturally quite accurate
> 
> Maybe don't represent this item in the game at all if you have to make it a wooden crossbow on a mount; crossbows are not ballista, ballistas are not "Big Crossbows" even if they operate in superficially similair ways.

Very good advice, it would be even better if the source of the original data could be provided. But it must be pointed out that having a 500-yard hit record is completely different from a reliable 500-yard hit, and it should not be expected to be as accurate as an M4 (In the current game, that's really the case.). As I said, the spread of guns is still somewhat referential, while the spread of crossbows is almost completely magical numbers. How to determine the accuracy of weapons requires systematic research. I have been considering doing this recently.

**Comment by RenechCDDA** [comment]
This is waiting for me to get some time to figure out what our dispersion numbers **even mean**. I brought it to the development discord to ask some of the senior devs and the consensus was that none of us know what the dispersion numbers mean. (The documentation does not seem to be correct that 1 dispersion is 0.01MoA)

**Comment by wwkk222208** [comment]
I have confirmed it :1 moa in reality = 12 moa in CDDA = 12*18 dispersion

**Comment by wwkk222208** [comment]
When calculating the hit, the humanoid target is calculated according to 0.5 grids. If it is assumed that the real humanoid target is roughly a rectangular area of 0.5m, then the width of one grid is 1m. Then 1 [moa](coco://sendMessage?ext=%7B%22s%24wiki_link%22%3A%22https%3A%2F%2Fm.baike.com%2Fwikiid%2F4373607166628649451%22%7D&msg=moa) = 12 / 1 * 18 = 216 dispersion. If it is assumed that the area of the humanoid target is the shoulder width of a person, which is about 0.4 meters on average, then 1 moa = 12 / 0.8 * 18 = 270 dispersion.

**Comment by wwkk222208** [comment]
Regardless of which standard is used for calculation, the values of almost all current remote weapons should be corrected, but this is a very huge project.

**Pull request closed without merging**
