### PR TITLE
Life Will Find A Way: Change maintainer of DinoMod to @damien

### PR DESCRIPTION
**Pull request by damien**
#### Summary

```SUMMARY: Mods "Change maintainer of DinoMod to @damien"```

#### Purpose of change

Change maintainer of DinoMod to @damien. Life will find a way.

#### Describe the solution

I'm a huge Jurassic Park fan and enjoyed this mod for the bit that I played with it, but I'd personally LOVE to see it be a lot more expansive. Aside from being sad if it went away, I'd love to see things like:

* Genetic engineering of friendly/neutral/not-so-friendly critters of the cold blooded variety, possibly via base critters and tailored mutations
* Cretaceous era themed plants and biomes
* Jurrassic Park memes

#### Describe alternatives you've considered

Not letting life find a way. Deemed unacceptable.

#### Testing

Mod still loads, JSON files I inspected in the folder seem to be fine.

#### Additional context

<a href="https://imgur.com/a/D1wimlQ"></a>

### CODE REVIEW

**Comment by damien** [comment]
Saw the feedback in #37483 , updated this PR accordingly.

**Comment by I-am-Erk** [comment]
There was significant interest from a few folks in the reddit thread about adopting a mod as well. You might want to see if there are co-maintainers to select. I think your "Jurassic park in cdda" vision is pretty specific and good, and will work well even if a few people are sharing the curator role. Not so sure about genetic engineering myself, but I'll give it a chance.

**Comment by damien** [comment]
@I-am-Erk that was just me spitballing ideas. For the near term I think modernizing what's already in the mod to current CDDA JSON standards (where can I find those, btw?) should be a good start.

re: Other interested parties: Have any reached out? I'm happy to work with or assist anybody else who'd like to jump in, I just don't know how I'd reach them if they haven't stepped forward already.

**Comment by ephemeralstoryteller** [comment]
Hi, I'm one of those interested parties! If I could help with any work, just let me know - my vision for the mod is pretty much exactly the same as what you put down, haha.

**Comment by ZhilkinSerg** [comment]
Someone is working on it in #26525 too.

**Comment by LyleSY** [comment]
Thanks @ZhilkinSerg . I've been trying to get some new content on there since 2018 but I've been struggling with my own lack of knowledge and conflicting content being put on there by faster and more competent devs. Based on my track record I'm probably not the best person to maintain this, so I'm open to someone else taking the title.

**Comment by LyleSY** [comment]
Christ, September 2017. That's brutal.

**Comment by I-am-Erk** [comment]
I'll leave it with Damien in charge, and if you other folks want to add yourself as co maintainer at some point that's cool too

**Comment by damien** [comment]
I think there is definitely plenty of stuff all of us can do. I’ll update this PR later today to include @ephemeralstoryteller and @LyleSY!

@ephemeralstoryteller @LyleSY: What time zones are you in and when are you each usually available to talk? We should have a powwow on Discord to figure out where we’re all coming from. If Discord doesn’t work I can also set up another repo for DinoMod and we can set up a discussion via Github. 👌

I’m a coder by trade and am happy to help where I can. From what I’ve read and @I-Am-Erk has said there’s a lot each of you could do even if you weren’t interested in fiddling with bits—we’ll certainly want to be brainstorming stuff and testing anything new we do. Also happy to bring anybody who needs a bit of help figuring JSON out up to speed.

**Comment by ephemeralstoryteller** [comment]
Thanks!! I'm somewhat new to JSON but I've been familiarizing myself with it through working on a little monster mod of my own. I'll definitely ask if I can't figure something out because I definitely want to help!

My timezone is EST and @ephemeral_storyteller#6980 on Discord. I'm on both of the C:DDA server if that helps!

**Comment by LyleSY** [comment]
I'm not new to JSON but still really terrible at it. Probably using the wrong tools. Entirely self-taught. I've burned a ton of time on this but it's mostly been learning curve. I lost interest when a butchering update broke my ability to play my version of the mod and broke my PR, but I'm excited to be able to play again, it's super fun. I'm EST.

**Comment by LyleSY** [comment]
I just joined Discord, which may be part of why I had so much trouble

**Pull request merged**
