### PR TITLE
Remove vitamin A and B for good

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Bugfixes "Remove vitamin A and B for good"

#### Purpose of change

Vitamin A and B have been useless for years, this removes them definitly from the code base.

#### Describe the solution

- Remove all mentions of vitA and vitB from the json both in mods and in vanilla
- obsolete the vitamin definitions
- remove hardcoded mentions
- remove mentions from test
- remove legacy handling of their useless effect
- obsolete vitamin B injection

#### Testing

load game with a save from beefore ths change without error

### CODE REVIEW

**Comment by Testudo-Cultu** [comment]
This feels like a turn in the wrong direction. Instead of removing them, why not expand on the health system so they have a use? Vitamin B deficiency wouldn't be very difficult to design. It could basically just be increased fatigue, reduced dexterity and reduced intelligence, and then later on anemia that progresses until death. The symptoms are already very similar to conditions in-game, so it feels like more effort to remove it than to just add vitamin B deficiency.

Vitamin A deficiency would basically just be a constant perception penalty and lower infection/disease resistance.

**Comment by anothersimulacrum** [comment]
They ore not being expanded on becausemthey oren't things that it is feasibre to be deficient in in the scope of the game.

**Comment by Testudo-Cultu** [comment]
> They are not being expanded on because they aren't things that it is feasible to be deficient in in the scope of the game.

Both would be pretty easy to get from meat and livers and would be a bit less severe than scurvy, so in terms of complexity it seems pretty simple to manage. I think vitamin B and A would be the easiest way to incentivize someone not to live off of just butter and pine tea or lard and tea. I'm guessing I'm missing something, but it doesn't seem necessary to discard these entirely when we already have vitamin C.

**Comment by Venera3** [comment]
A and Bs have too large stores to develop a deficiency within the game's timeline (we're talking ~year of absolutely no intake).

**Comment by Testudo-Cultu** [comment]
> A and Bs have too large stores to develop a deficiency within the game's timeline (we're talking ~year of absolutely no intake).

Is that really out of scope, though? Just making the new plate armors can take over a third of an in-game year to pull off due to weariness and the requirement to satisfy basic needs. The faction system, while pretty much completely optional, could easily take over an in-game year just to fully develop one base. I've even had characters that spent almost an entire year just chilling in one spot eating smoked meat/pemmican every day while I tried to craft end-game stuff.

**Comment by Venera3** [comment]
Which would not be "completely no intake", but in our system anything below 0.1% RDA per serving is ignored, which throws out trace amounts -and trace intake is all you need from *micro* nutrients. Do give the relevant PRs over the last year a read, but the long and short of it is unless we get to multi-year games being the norm they aren't worth tracking.

**Comment by Testudo-Cultu** [comment]
> Which would not be "completely no intake", but in our system anything below 0.1% RDA per serving is ignored, which throws out trace amounts -and trace intake is all you need from _micro_ nutrients. Do give the relevant PRs over the last year a read, but the long and short of it is unless we get to multi-year games being the norm they aren't worth tracking.

Fair enough I suppose.

**Pull request merged**
