### PR TITLE
Fix gravel construction inconsistencies etc

### LINKED ISSUE #48426: gravel weirdness
# Describe the bug
-gravel blocks moving furniture on to it
-can be smashed easily (str12 with a quarterstaff)
-removing gravel by construction yields 700ish pebbles (vs 100 needed to make it)

# Steps To Reproduce

interact with the gravel

# Expected behavior
-gravel should allow furniture to move over it since it is as flat as dirt
-gravel shouldn't be so easily smashed since there is nothing to really smash
-yield for deconstructing gravel should be 100 or less pebbles

# Versions and configuration

cataclysmdda-0.E-Windows_x64-Tiles-11560
 - Mods loaded:
-disable npc needs
-bionic professions

edit: realized I made a world to test this and didn't use my current game with its mods

### LINKED ISSUE #49263: Making A Gravel Floor And Deconstructing it Makes Infinite Rocks
When you create a gravel floor, it only requires 100 pebbles. However, when you deconstruct it as furniture, it creates near a thousand pebbles and a few rocks, allowing you to clone rocks and pebbles.

1. Create a gravel floor
2. Deconstruct it
3. Rinse and repeat

I expected to get less pebbles than I put in, as I can't think of any logical reason for getting more pebbles.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 25abf78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
Bugfixes "Fix construction and terrain details in gravel"

#### Purpose of change
closes #48426 and closes #49263

#### Describe the solution
Gravel now costs 500 pebbles to construct, and yields 200-400. Bashing gravel is generally unproductive. It supports furniture dragging and behaves like you'd expect gravel to behave.

#### Describe alternatives you've considered
Could nerf yield more and decrease number of pebbles needed, but a square meter of gravel should provide a large number of pebbles.

#### Testing
tk

#### Additional context
Debating adding an alias for t_railroad_rubble to t_gravel

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Why are you merging your own PRs? Until something changed, we have a policy of not merging own PRs, even if they are small and/or obvious.

**Comment by I-am-Erk** [comment]
Timing. We're trying to get these things in for stable and I've been discussing them on discord with other devs.

**Comment by JerryLin1** [comment]
A bit late but this closes #32308

**Comment by sTiKyt** [comment]
Yay, congrats to cult of gravel

**Pull request merged**
