### PR TITLE
[RDY]Make ranged cap a soft cap, add hard cap at 60

### LINKED ISSUE #18299: Gun max range is capped
Known and all, but I'm just leaving it out as a reminder that arbitrary hard cap isn't the right way to do it.
A reality bubble cap is necessary, 30 tiles cap isn't.

Ideas:
- Add a deterministic penalty that scales with range. Essentially a cap on accuracy. If high, it would prevent getting hits near cap. If low, it could still allow guaranteed headshots for overpowered characters.
- Add a hard low cap on dispersion.
- Revise dispersion calculations to prevent near-0 dispersion guns naturally, then nerf all 0 dispersion guns and give them something sensible. Most important parts would be to add some "soft cap" on json dispersion (as in adding a note that "not even futuristic guns should have less than 60 dispersion") and then revising how gunmods affect dispersion. Most likely by making gunmods apply multipliers rather than additions/subtractions. Would also require getting rid (or nerfing) of "accurizing".
- Some range-dependent special case. For example, dispersion penalty that is 0 until soft range cap and then rises with range.
- Generate `missed_by` with a normal distribution rng.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #18299

The current limit - 30 tiles - becomes a soft cap. Aiming at a tile above 30 tile distance adds 3 dispersion to the attack. This can't be mitigated in any way (could be lowered with stats later on, but for now it's just for the uncap).

The resulting effective range (range at which chance to get a good hit is 50+%) goes roughly linearly from ~30 tiles at ~180 dispersion to ~60 tiles at 0 dispersion.

Linear dispersion increase isn't perfect, but it does the job and achieves the intended effect.

Tests are broken for ranges at the cap, but I didn't change anything there. Do gun tests all work in master?

### CODE REVIEW

**Comment by DangerNoodle** [comment]
An improvement at least. I forget what range limit the reality bubble and/or the limit of daytime imposes on it, but I assume that 60 is much closer to the effective limit prior to the cap?

**Comment by Coolthulhu** [comment]
60 is the minimum range from player's spot to edge of bubble. 72 is the maximum such distance.

**Comment by DangerNoodle** [comment]
Ah, I see. I had suspected that the reality bubble limit was close to that number, but had forgotten the exact details. Thank you for that.

**Comment by kevingranade** [comment]
60 is also the maximum sight range, so you could shoot something outside this area with a stray shot, but not target it.

**Comment by DangerNoodle** [comment]
That should significantly improve the matter then, especially for long-range weaponry and heavy mounted weapons.

**Comment by Firestorm01X2** [comment]
Maybe  it wil lbe good idea set this to set dispersion per tile to 2 instead 3 to give player chance to hit target even on extreme range?

**Comment by Coolthulhu** [comment]
Nah, 3 is fine.
It still gives almost 50% of a good hit chance at 60 tiles at 0 dispersion.

**Comment by DangerNoodle** [comment]
Implementation incomplete. See issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/20708

**Pull request merged**
