### PR TITLE
[CR] Add Zombie Shocker Hulks. Yes, totally OP.

### PR DESCRIPTION
**Pull request by valuial**
Not really sure if we really want this. It's just been talked about a lot in IRC...

### CODE REVIEW

**Comment by valuial** [comment]
Just the monster definition for now. Needs some serious discussion for spawngroups and stuff...

**Comment by Coolthulhu** [comment]
I don't think this is a good idea.

Their drops mean they can only evolve from shocker brutes or spawn already evolved. The latter option is out unless they're somehow prevented from joining hordes. The former kinda makes sense, since shocker brutes become weak when players start resisting electricity.

They're strong enough to kill a midgame character, but against endgame ones (with electricity resistance) they are just tanky hulks. We already have a ton of early/mid game crap that ambushes and kills early characters, but then can't do anything against stronger ones.

Their night blindness means shooting them from the edge of their vision and sprinting away is a foolproof tactic of taking them out. Their day vision on the other hand means they're really good at spotting weak characters from the other end of the map and causing an undeserved death.

Their speed is big enough to prevent escape on foot, but does nothing against vehicles. Ramming one with a vehicle is also rather easy, but that's a much broader problem as it also affects tank drones.

**Comment by Zireael07** [comment]
Reduce day vision?

**Comment by Salganos** [comment]
Is there a properly working means of becoming electricity resistant other than the Dielectric Capacitance CBM, or attacking a shocker with something other than an entirely wooden weapon?  The biggest problems I've had with those is that rubber gloves apparently do nothing, and it is hard to tell what might, in-game.

On any character without cybernetics I always end up having to use some sort of gun to kill shockers quickly with minimal pain, and making them any harder to kill would make them as bad as tank drones and such (i.e.: avoid at all costs, barring extremely iffy and convoluted ploys).

**Comment by kevingranade** [comment]
> would make them as bad as tank drones and
> such (i.e.: avoid at all costs, barring extremely
> iffy and convoluted ploys).

You say that like it's a bad thing. It'd be great to have some enemies that
are simply avoided because they're too dangerous to be worth tangling with.

**Comment by Salganos** [comment]
True.  More might be okay, as long as they are rare enough to not interdict literally everything.

**Comment by Karbine** [comment]
> Is there a properly working means of becoming electricity resistant other than the Dielectric Capacitance CBM, or attacking a shocker with something other than an entirely wooden weapon?

Powered RM-13 combat armor. Not that it detracts from your larger point.

I'm in support of adding more high-threat zombies for late-game characters. At the moment even hulks aren't a real challenge for "late-game" characters, who will mostly die of misadventure or their players deciding to re-roll. This was largely the case even before corrosive zombies caught the nerf bat.

Shocker Hulks seem like a good candidate to add some additional risk to survivors who are largely unphased by everything else the blob has to throw at them. As long as they can be added in a way that doesn't have them cold-cocking fledgling survivors, as Coolthulhu suggests, I think adding more enemies worthy of a moment's hesitation is a positive thing. Discussions for reworking electrical threats and the player's ability to cheese enemy sight seem to be broader issues, if not besides the point.

**Comment by Salganos** [comment]
Yeah, I'm coming at this from a frequently CBM-free perspective, since making one cyborg juggernaut or two was enough for me, with the current system, and I tend to avoid using them on characters that are moving towards some other theme (like, say, bird mutant).  That one CBM turns this into a normal hulk again is part of my issue, but it _is_ more a complaint about the electrical resistance system than the Shocker Hulk idea itself, to be honest.

**Comment by DragonLaggin** [comment]
I feel like the YASD count is going to go through the roof if/when this is added.

Fun! all around, eh?

**Comment by jcd000** [comment]
More pain! :)

Next up: Ninja (shady) Hulks.
Especially evil since they will kill you at night with their enhanced nightvision, since you cannot prepare for them.
If they were very lategame though, they could be 'fun'.

**Comment by pisskop** [comment]
:|

Whats stopping me from just running them over like every other hulk?  They even glow in the dark.

**Comment by AppleConnoiseur** [comment]
Ohh, this sounds like fun :D.
If we could have a hulk that do a lot more pain and cutting damage it could be nice. Would deter me from just charge in with heavy survivor gear and a zweihänder. Then pop codeine or morphine when im done.

**Comment by mugling** [comment]
Closed as stalled without consensus

**Pull request closed without merging**
