### PR TITLE
Make a functional travis.yml

### PR DESCRIPTION
**Pull request by kevingranade**
Stealing parts of the travis.yml from https://github.com/onqtam/doctest/blob/master/.travis.yml

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade did you add MIT license to Cataclysm-DDA?

**Comment by kevingranade** [comment]
No, why?

**Comment by kevingranade** [comment]
Oh, you mean a notice of the travis.yml file being originally not LICENSED, yes that's an oversight, it should have a line in LICENSE.txt

**Comment by kevingranade** [comment]
Oh, you mean a notice of the travis.yml file being originally MIT licensed, yes that's an oversight.

Now that I look though, it will require importation of both the MIT and BOOST licenses, since it originated at https://github.com/boostorg/hana/blob/master/.travis.yml

Our copyright system is so very silly.

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade

>Our copyright system is so very silly.

I concur. 

Are you going to add the notice?

**Comment by kevingranade** [comment]
Actually no, I'm going to rewrite it a bit and call it a day.

**Pull request merged**
