### PR TITLE
[RDY] Reduced minimum occurrences of several overmap specials

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
### Reduced occurrences-min to 0:

- `Hotel` - (from 1 to 0);
- `Motel` - (from 2 to 0);
- `Public Works` - (from 1 to 0);
- `Apartments_Con` - (from 1 to 0);
- `Apartments_Mod` - (from 1 to 0);
- `Fungal Flowers` - (from 1 to 0);
- `power_station_large` - (from 1 to 0);
- `Home Improvement Superstore` - (from 1 to 0);
- `campsite` - (from 1 to 0);
- `campsite_cabin_incomplete` - (from 1 to 0);
- `campsite_field_biker` - (from 1 to 0);
- `campsite_a` - (from 2 to 0);
- `campsite_field_biker_destroyed` - (from 1 to 0);
- `rest_stop` - (from 1 to 0);
- `roadstop_a` - (from 1 to 0);
- `roadstop_b` - (from 1 to 0);
- `cemetery_religious` - (from 2 to 0);
- `Dairy Farm` - (from 1 to 0).

### Lowered occurrences-min to 1:

- `FEMA Camp` - (from 2 to 1);
- `Evac Shelter` - (from 5 to 1);

This should free up 26 places for overmap specials for mods like `Urban Development`.

I'm not sure about some of the specials though. `Public Works`, `power_station_large` and `Fungal Flowers` should be probably left intact?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
FEMA, office tower, school and mall have missions or starts associated with them.
Radio tower is needed for radio signals.
The rest can be non-mandatory just fine.

**Comment by ZhilkinSerg** [comment]
> FEMA, office tower, school and mall have missions or starts associated with them.
> Radio tower is needed for radio signals.
> The rest can be non-mandatory just fine.

Right, forgot about start locations.

**Comment by kevingranade** [comment]
The specials that MUST have minimum values are ones that are targets of missions, the mission assignment code searches for a matching terrain and assigns it as the target of the mission, and in some cases edits its map data.  Nothing else actually needs to have a minimum unless it's being used for testing.

**Comment by ZhilkinSerg** [comment]
I've parsed `mission_start.cpp`. Following overmap terrain ids are used in`target_om_ter` and `target_om_ter_random` functions:

function | overmap terrain id
-- | --
target_om_ter_random | evac_center_9
target_om_ter_random | field
target_om_ter_random | bandit_cabin
target_om_ter_random | evac_center_19
target_om_ter_random | evac_center_7
target_om_ter_random | evac_center_17
target_om_ter_random | bandit_camp_1
target_om_ter | forest_thick
target_om_ter | necropolis_c_44
target_om_ter | lab
target_om_ter | haz_sar
target_om_ter | hospital
target_om_ter | prison_1_5
target_om_ter | cabin_strange
target_om_ter | cabin
target_om_ter | necropolis_c_23
target_om_ter | ranch_camp_67
target_om_ter_random | ranch_camp_66
target_om_ter_random | ranch_camp_65
target_om_ter_random | ranch_camp_74
target_om_ter_random | ranch_camp_75
target_om_ter_random | ranch_camp_67
target_om_ter_random | ranch_camp_46
target_om_ter_random | ranch_camp_55
target_om_ter_random | ranch_camp_56
target_om_ter_random | ranch_camp_58
target_om_ter_random | ranch_camp_57
target_om_ter_random | ranch_camp_68
target_om_ter_random | ranch_camp_59
target_om_ter_random | ranch_camp_60
target_om_ter_random | ranch_camp_61
target_om_ter_random | ranch_camp_69
target_om_ter_random | ranch_camp_49
target_om_ter | ranch_camp_49
target_om_ter | ranch_camp_70
target_om_ter | ranch_camp_66
target_om_ter_random | ranch_camp_51
target_om_ter_random | ranch_camp_52
target_om_ter_random | ranch_camp_50
target_om_ter_random | ranch_camp_48

None of this should be affected by current PR, so it is ready to be merged.

**Comment by AlecWhite** [comment]
>Think the lowering of gas stations might be the only controversial change there

I agree.

**Comment by ZhilkinSerg** [comment]
> Think the lowering of gas stations might be the only controversial change there

That is probably true.

**Pull request merged**
