### PR TITLE
[RDY] Jsonify mapgen (churches and doctor office)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Conversion of `church_gothic`, `church_new_england` and `office_doctor` mapgen to JSON.

- [x] Needs #20770 to be merged beforehand in order for computers to work.

### CODE REVIEW

**Comment by Leland** [comment]
@ZhilkinSerg this and #21211 can be updated - #20770 has been merged.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg this and #21211 can be updated - #20770 has been merged.

Should be good to merge now.

**Comment by Coolthulhu** [comment]
Needs update

**Comment by ZhilkinSerg** [comment]
> Needs update

I've just updated to current master.

**Pull request merged**
