### PR TITLE
Battery compartment mod can use medium storage batteries

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Battery Compartment Mod allows medium-sized storage batteries"

#### Purpose of change
I wanted to put a bigger battery in my tools but the game doesn't allow for it.

#### Describe the solution
Car battery is 6.25L, medium storage battery is also 6.25L. Although it is twice as heavy, it occupies the same dimensions so fitting it into the battery mod should be doable.

#### Describe alternatives you've considered
Just use the vehicle mounted welder, kitchen, etc and don't bother.

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
Why do we even have this? It's nonsense. You're stuffing a car battery into a screwdriver or electric chainsaw?

**Comment by anoobindisguise** [comment]
> Why do we even have this? It's nonsense. You're stuffing a car battery into a screwdriver or electric chainsaw?

I see you requested changes, but I can't seem to view what those changes are. Would you rather remove the mod entirely?

**Comment by kevingranade** [comment]
That's what I'm thinking, but I'm not closing it outright in case I'm misunderstanding something.

**Comment by anoobindisguise** [comment]
> That's what I'm thinking, but I'm not closing it outright in case I'm misunderstanding something.

Alright, well let me know what you decide. Ideally the volume should change with the size of the mod, but I don't know if that's possible. The electric jackhammer is the only tool in the game that spawns with a 6.25L internal battery and it is definitely very odd to put such a big battery in say, a flashlight, though for a coffeemaker or something it does make a bit more sense.

**Comment by kevingranade** [comment]
There's room for rationalizing the battery conpartment mod, but extending it to more oversized batteries isn't it.

**Pull request closed without merging**
