### PR TITLE
Fix syringe json error

### LINKED ISSUE #47670: Cannot inject prophylactic antivenom pills
# Describe the bug

Attempting to use those handy antivenom pills doesn't work, even when you have a syringe in your inventory.  Consume and use menus just yell "You need a syringe to consume that!" at you.

# Steps To Reproduce

1. Spawn antivenom pills.
2. Spawn syringe.
3. Notice that you cannot use the pills.

# Expected behavior

You should be able to inject the antivenom pills if you have a syringe in your inventory.

# Screenshots

None.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9778-gddb9e36 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Strange bug, doesn't seem to affect heroin or morphine. I remember being able to inject them like a week ago, I think? So it was probably a recent change that broke it.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fix #47670
Fixes several injectable drugs

#### Describe the solution
Use the actual code that the drug iuse actor uses for tools.  For tools without charges it doesn't matter what number you put in.  For things with charges -1 means don't use any charges.

### CODE REVIEW

**Comment by kevingranade** [comment]
Does it consume the tool?  -1 was being used to indicate "you need one of these, but it does not get used up".

**Comment by Ramza13** [comment]
> 
> 
> Does it consume the tool? -1 was being used to indicate "you need one of these, but it does not get used up".

No it does not get consumed.

**Comment by ZhilkinSerg** [comment]
```
Search "tools_needed" (17 hits in 2 files of 3553 searched)
  C:\Projects\Cataclysm-DDA\data\json\items\comestibles\med.json (16 hits)
	Line 510:       "tools_needed": { "apparatus": -1 }
	Line 613:       "tools_needed": { "apparatus": -1 },
	Line 649:       "tools_needed": { "apparatus": -1 },
	Line 666:       "tools_needed": { "apparatus": -1 },
	Line 696:       "tools_needed": { "apparatus": -1 },
	Line 822:       "tools_needed": { "apparatus": -1 },
	Line 852:       "tools_needed": { "apparatus": -1 },
	Line 932:       "tools_needed": { "apparatus": -1 },
	Line 966:       "tools_needed": { "dab_pen_on": -1 },
	Line 1090:       "tools_needed": { "syringe": 1 },
	Line 1227:       "tools_needed": { "syringe": 1 },
	Line 1423:       "tools_needed": { "syringe": -1 },
	Line 1572:       "tools_needed": { "apparatus": -1 },
	Line 1765:       "tools_needed": { "syringe": -1 },
	Line 1787:       "tools_needed": { "syringe": -1 },
	Line 1818:       "tools_needed": { "apparatus": -1 },
  C:\Projects\Cataclysm-DDA\data\json\items\tool\deployable.json (1 hit)
	Line 188:       "tools_needed": { "hand_pump": 1 },
```

**Comment by actual-nh** [comment]
Given that it is down as "tools_needed", not "extra components needed" or something like that, I am confused as to why the action could use up a "tool".

**Comment by Ramza13** [comment]
Updated this to use the actual code that the drug iuse actor uses for tools.  For tools without charges it doesn't matter what number you put in.  For things with charges -1 means don't use any charges.

**Comment by kevingranade** [comment]
Because some tools have charges or ammunition, e.g. welder charge.  But that might not be the case here, I think we might actually have some cleanup to do because we're not using it this way anymore, but we still have code that expects it.

**Comment by DalenTalas** [comment]
IIUC, this fixes the injection error from #47670. Does this also update the item name for "prophylactic antivenom pill" to reflect that it's injectable?

**Pull request merged**
