### PR TITLE
[WIP] Updated the Cartridge list in GAME_BALANCE.md

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The 7.62x25 hot load has been added to the list of bullets in GAME_BALANCE.md. Would anybody mind if I updated the list of bullets to reflect their current damages?

### CODE REVIEW

**Comment by kevingranade** [comment]
An update there would be great.

**Comment by BorkBorkGoesTheCode** [comment]
What is the current muzzle velocity of the .22 LR? It was nerfed without explanation

**Comment by BorkBorkGoesTheCode** [comment]
I can make note of many changes, but I lack the sources.

**Comment by BorkBorkGoesTheCode** [comment]
@Rivet-the-Zombie could you make up some bullet weight, muzzle velocity, muzzle energy, and muzzle energy figures for the 5x50 cartridges?

**Comment by BorkBorkGoesTheCode** [comment]
Also, how heavy is the 8x40mm bullet, separate from the propellant?

**Comment by BorkBorkGoesTheCode** [comment]
There are so many undocumented changes that GAME_BALANCE can no longer claim that the damage is based on muzzle velocity in most cases.

**Comment by BorkBorkGoesTheCode** [comment]
@illi-kun @Coolthulhu @mugling @Nioca are you online?

**Comment by BorkBorkGoesTheCode** [comment]
@Cyrano7 Would you care to comment on this?

**Comment by Rivet-the-Zombie** [comment]
>@Rivet-the-Zombie could you make up some bullet weight, muzzle velocity, and muzzle energy figures for the 5x50 cartridges?  
>Also, how heavy is the 8x40mm bullet, separate from the propellant?

I'll do the research to make up some reasonable numbers ASAP - likely tomorrow afternoon.

**Comment by Rivet-the-Zombie** [comment]
The 8x40mm's characteristics are fictional, but derived from the common 7.62x51mm NATO, 7.62x39mm, and 7.62x54mmR cartridges. As these caseless rounds possess no case or traditional primer, the majority of their mass is devoted to an advanced form of proprietary propellant.
Most 8x40mm rounds fall within the following specifications: 150-175 gr projectile, ~900 m/sec, ~3000 ft-lbf (~4060 J), ~64000 psi (441 MPa)

The 5x50mm flechette cartridge is also fictional, with some of its statistics derived from the 5.56x45mm ACF cartridge utilized by the Steyr ACR.
The basic 5x50mm round's specifications are as follows: 24 gr projectile, ~1650 m/sec, ~1550 ft-lbf (~2100 J), ~24000 psi (~165 MPa)

**Comment by BorkBorkGoesTheCode** [comment]
What causes the -25 damage reduction for the 5x50?

**Comment by Rivet-the-Zombie** [comment]
Call it a 4.5" base barrel for both, as they are both used in varying lengths.

**Comment by Nioca** [comment]
Some of these cartridges simply haven't been modified to utilize muzzle energy numbers; they're still using pre-energy numbers for damage (like the .50 BMGs or .32 ACP), which is part of what's causing the discrepancies. The other part though, is indeed that there's been some modifications from muzzle energy. Some of which aren't entirely justified and probably need to be fixed, IMO. (9mm and .45 ACP, I'm looking at you)

**Comment by BorkBorkGoesTheCode** [comment]
Temporarily closed

**Pull request closed without merging**
