### PR TITLE
Make some items able to warm food up.

### PR DESCRIPTION
**Pull request by woutershep**
Adds a new COOKING iuse that lets people heat up food next to fires.
Added are the aluminum tongs, frying pan, {,stone,copper,clay} pot.

I've explicitly chosen has_nearby_fire to make sure items such as
lighters that dont have nowhere near enough power to heat a meal are not
considered.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I think `COOKING` is inappropriate name for this iuse, because it heats up food, not cooks it. Maybe `HEATING` will fit better.

**Comment by Coolthulhu** [comment]
> Maybe HEATING will fit better.

Or even more explicitly: `HEAT_FOOD`

**Comment by Darkyhard** [comment]
Tongs shouldn't probably have this use action, because you would be able to heat up soup or other liquids with them.

**Comment by Mecares** [comment]
> Tongs shouldn't probably have this use action, because you would be able to heat up soup or other liquids with them.
Well those have to be in some kind of container like a can you grab with the tongs.

**Comment by Darkyhard** [comment]
> Well those have to be in some kind of container like a can you grab with the tongs.

Yes, this would work actually, didn't consider this at first. That's fine then.

**Pull request merged**
