### PR TITLE
Fix displacement of items after (de)construction

### LINKED ISSUE #31651: Deconstructing things crashes the game
# Describe the bug
Deconstructing things crashes the game

Deconstructing things crashes the game

# Steps To Reproduce
Deconstruct whatever 

1. Get tools to dissasemble
2. Try to dissasemble
3. You will get a error message

# Expected behavior

you will get a error log, and if you will try any option, you will get a crash log and game will crash, i have no idea why this happens.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4722-g52c0721
 - Graphics version: Tiles
 - Mods loaded: Bootleg walkers, Garden pots, Mythical Replicas, Makeshift Gun Pack, Craftable gun pack, Medival and historic content, Alternative map key, hydroponics, mining mod, beta national guard camp, cars to wrecks, vehicle additions packs, tanks and other vehicles, folding parts pack

# Additional context
  
[crash+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310024/crash%2Bdebug.zip)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310029/save.zip)

(sorry for grammar errors, im not a native english speaker)

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
SUMMARY: Bugfixes "Fix displacement of items after (de)construction"

#### Purpose of change
Fixes #31651

#### Describe the solution
Iterate with erasure properly

### CODE REVIEW

**Comment by 7illian** [comment]
Still crashing on deconstruction.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Still crashing on deconstruction.

It doesn't for me. Provide more details - game version, savegame, reproduce steps.

**Comment by 7illian** [comment]
9191 on Android. Deconstructing that fridge I'm standing near causes crash every time. Here's my save.

https://drive.google.com/open?id=1xj2qT2frTkTrenG8lxmRhxUHIyEUDgx-

**Comment by ZhilkinSerg** [comment]
9191 do not contains this fix.

**Comment by 7illian** [comment]
I could have sworn the notes said it did. Did something get rolled back.

**Comment by ZhilkinSerg** [comment]
Notes? Do you mean this changelog - https://ci.narc.ro/job/Cataclysm-Matrix/changes

image

image

**Comment by 7illian** [comment]
Yea I just muddled up with the changelog and the APK download link

**Comment by ZhilkinSerg** [comment]
Oh, I can see that Android build for 9192 actually failed, so that is probably why you have downloaded 9191. Anyway try 9193 which was built successfully.

**Comment by 7illian** [comment]
Yea 9193 fixed it.

**Comment by Deak1113** [comment]
i actually couldn't play, because deconstruction was so important to me, Thanks 👍

**Pull request merged**
