### PR TITLE
Remove (migrate) unused/redundant lasagne_cooked

### PR DESCRIPTION
**Pull request by cake-pie**
#### Summary
```SUMMARY: Bugfixes "remove unused/redundant item lasagne_cooked"```  

#### Purpose of change

The item "boiled lasagne" `lasagne_cooked` was added in #5071, probably intended to represent the plain, boiled pasta. As early as #10573 it was noted that it doesn't have a recipe and thus cannot be crafted.

#20836 added raw lasagne as a possible ingredient in the recipe for "boiled noodles" `spaghetti_cooked` -- despite the item id, this item represents any plain, boiled noodle (spaghetti, macaroni, lasagne or fast noodles)

Since `lasagne_cooked` is not obtainable, and is now superseded by the multipurpose `spaghetti_cooked`, it should be removed.

#### Describe the solution

Remove `lasagne_cooked` from comestibles.json; mark it for migration to `spaghetti_cooked`.

### CODE REVIEW

**Comment by alanbrady** [comment]
No longer used items in migrations are supposed to be there, not moved back into comestibles.  This automatically converts it into spaghetti_cooked.

**Comment by cake-pie** [comment]
Huh, izzat so. (I was just following the example of #25005)

**Comment by alanbrady** [comment]
I *believe* that to be the case.  @BevapDin @kevingranade?

**Comment by cake-pie** [comment]
Nah, based on d5b9e80b72016d6143b551ffd4231893483a3ad3 and 8eb8e416c15b46a890d7d2d0f307fa68a83c87b1 I think you're probably right.

**Comment by cake-pie** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
Probably the best way to state this is there should only be one entry with a given I'd, so you want a regular definition *or* a migration.

It's also the case that if an item was *never* obtainable for a regular player you can just delete it.

**Comment by cake-pie** [comment]
Thanks for the clarification.

I did check comestibles.json blame/history to trace the item back to the point it was added, and ascertained that the PR didn't include the corresponding recipe. However I'm not sure I can confidently assert that it was **never** obtainable -- whether by a recipe that was added later and then removed, or if the item was map spawnable at some point, etc. Unless someone with superior git-fu can provide a stronger guarantee, I'd prefer to err on the side of caution and have the migration entry.

**Comment by kevingranade** [comment]
I agree having the migration entry present is a very low price to pay to
avoid throwing erroneous errors at someone.

**Pull request merged**
