### PR TITLE
Add missing id_suffix to soap_flakes recipe

### LINKED ISSUE #36162: Soap Flakes Uncraftable Except by CBM
# Describe the bug

Soap Flakes require a tool with Cutting 2 or higher. The only tool in the base game with that level is the Extended Toolset CBM, per the Chezzo item browser.

# Expected behavior

Craftable without cybernetic implants.

Reducing it to Cutting 1 or more, upgrading existing higher-quality cutting tools to level 2, or introduction of a cheese grater for the purposes of flaking soap (and possibly hard cheese) are all acceptable.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: None```

#### Purpose of change
Fixes #36162 

#### Describe the solution
Add missing id_suffix entry

### CODE REVIEW

**Comment by Fris0uman** [comment]
image
 As far as I know the suffix doesn't appear anywhere

**Comment by I-am-Erk** [comment]
Huh. That's something we should actually report as a bug, appending the suffix would make the recipes infinitely more readable.

**Comment by arijust** [comment]
It doesn't close issue.
Linked issue was about recipe using CUTTING 2, when only Integrated Toolset had CUTTING 2 in-game.

**Comment by Fris0uman** [comment]
This does solve the issue because now you can make the flakes with CUT 1 in 15min and in 10 min if you have CUT 2.
If you look at the screenshot you'll see 2 recipes, if you look in your game you'll see only one.

**Comment by arijust** [comment]
My mistake.

**Comment by I-am-Erk** [comment]
Yes, this definitely does close the issue. Just brings my attention to a different one.

**Comment by jbytheway** [comment]
> Huh. That's something we should actually report as a bug, appending the suffix would make the recipes infinitely more readable.

The point of the suffix is to provide a distinct internal id for each recipe, even if more than one crafts the same item.  If we want a suffix on the recipe name in the GUI, then that should be a new field.

**Comment by I-am-Erk** [comment]
I know what it does currently, but since the suffix accepts (and very often *is*) a simple descriptive string, appending it, or appending it unless an alternative descriptive suffix is available, would make it much easier to navigate identical recipe names

**Pull request merged**
