### PR TITLE
[WIP][CR] Reverted STEN auto-only limitation

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
http://smf.cataclysmdda.com/index.php?topic=14033.msg294307#msg294307 It does seem to be a selective-fire firearm after all.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Some of the later versions were selective-fire, but the none of the early ones were, as far as I'm aware.

**Comment by BorkBorkGoesTheCode** [comment]
Which version will appear in the game?

**Comment by Rivet-the-Zombie** [comment]
That's a good question!

**Comment by Mecares** [comment]
Maybe split them into two Itema "Sten early model" and "Sten later model" one with and one without burst fire to make everybody happy?

**Comment by DangerNoodle** [comment]
Based on item group placement, it is reasonable to assume that they might have been handmade copies (either pre-cataclysm, or using metalworking machinery not available to the player) rather than originals, given their appearance in the 'guns_survival'. What versions are most likely to be easily researched and reproduced via available schematics?

**Comment by Rivet-the-Zombie** [comment]
>What versions are most likely to be easily researched and reproduced via available schematics?

The cheap, simplest ones that lack a selective-fire option.

**Comment by BorkBorkGoesTheCode** [comment]
Would anyone support a version of chaosvolt's craftable STEN idea as content for Craftable Guns mod?

**Comment by DangerNoodle** [comment]
That would be an interesting expansion to the mod.

**Comment by Zireael07** [comment]
Simple STENs were handmade in the Warsaw uprising, and from the fact that they were handmade, I am guessing they lacked selective-fire.

**Comment by kevingranade** [comment]
Sounds like this would fit better in the craftable guns mod.

**Pull request closed without merging**
