### PR TITLE
Add other wires to rudimentary lockpick recipe

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Lockpicks can use all wires"

#### Purpose of change
With chain fences giving medium wires, you can't make lockpicks out of em. 

#### Describe the solution
Make lockpicks out of em.

#### Describe alternatives you've considered
Not make lockpicks out of em?

#### Testing
Made lockpicks out of em
lockpick

### CODE REVIEW

**Comment by rty275** [comment]
Regular wire is also in the first component of the recipe, should it get the same treatment?

**Comment by Holli-Git** [comment]
> Regular wire is also in the first component of the recipe, should it get the same treatment? Genuinely asking, I don't know the logic behind the recipe

Ah yeah prolly, ngl I don't know the logic either. I'll fix that rq

**Comment by ashGlaw** [comment]
Good fix, thank you!

**Comment by Kantonine** [comment]
> Regular wire is also in the first component of the recipe, should it get the same treatment? Genuinely asking, I don't know the logic behind the recipe

You use the first ingredient as a tool for putting rotational pressure onto the lock, and the second ingredient is to make the pick that moves the lock pins

**Comment by I-am-Erk** [comment]
Yeah, the key thing is htat the first component wire has to be strong enough to maintain some torsion pressure, so eg. copper wire is too soft for that. This looks OK to me.

**Pull request merged**
