### PR TITLE
Fixes the Frozen food problem once and for all

### PR DESCRIPTION
**Pull request by ghost**
It has occurred to me that there is a problem with frozen foods being inedible even if your character does not mind the cold! I fixed this dire issue.

ʲᵒᵏᵉ ᵖʳ ᵖˡᵉᵃˢᵉ ᵇᵉ ⁿᶦᶜᵉ

### CODE REVIEW

**Comment by dissociativity** [comment]
thanks I hate it

**Comment by paulenka-aleh** [comment]
Shouldn't Elsa get penalties for eating hot food than? :D

**Comment by sfsworms** [comment]
Is this intended as a real easter egg? :p

**Comment by Xhuis** [comment]
Nope, this is absolutely a joke PR and I fully expect it to be closed. It is not intended to get into the game fully!

**Comment by Mecares** [comment]
There might be a place in game for a mutation that allows to eat frozen food named pagophage, but I do not know which mutation tree would fit.

**Comment by cainiaowu** [comment]
How about the trog and chimera? they have strong stomach that can eat anything.

**Comment by Inglonias** [comment]
listen.

i hate this.

**Comment by nexusmrsep** [comment]
@Xhuis despite all the hate it gets, I actualy think that you can sneak it in to Crazy Cataclysm mod if you rework it so its more easter eggy and much less mechanic change.

**Comment by ZhilkinSerg** [comment]
Who's Elsa?

**Comment by paulenka-aleh** [comment]
https://frozen.disney.com/elsa

**Comment by kelwyng** [comment]
https://www.smbc-comics.com/comic/frigid

**Comment by Xhuis** [comment]
I suppose the past is in the past.

**Pull request closed without merging**
