### PR TITLE
[Xedra Evolved] Paraclesian natural magical growth

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved] Paraclesian natural magical growth"

#### Purpose of change

It makes sense that human wizards or psions actually have to put in effort to study and learn their powers. Those things aren't natural to humanity, and require effort to master.

The elemental fae from the Paraclesian Birth scenario are _not_ human--they are fae creatures with magic in their veins, born of the elements and native to the Bright Lands, and they shouldn't need to put in nearly as much work.

#### Describe the solution

Set up a group of EoCs that runs every 6 to 36 hours for each of the Paraclesian fae. When it fires, it checks that they're in an appropriate location:

- Arvore: Forest, thick forest, Great Tree, or in a building they built with their magic. (I set it up so you can be within 2 tiles of a forest but not within 2 tiles of a road or on a field, so you can still build a faction camp and benefit from this as long as you do it in the woods). Must be outdoors except if they're in a building they built with their magic (i.e., one made of living wood).
- Homullus: In a city or any faction camp, or in or near actual remnant communities (NECC, refugee center, etc)
- Ierde: On natural dirt or stone, or underground.
- Salamander: There's no overmap tile that works for "very hot" so it's ambient temperature of 80 or above or being in a strong heat field. I'll add the salamander special when that gets added. Unfortunately "have a fire within X tiles" is not possible to detect through EoCs currently. 
- Sylph: Z level 1 or above and outdoors or in a wind stronger than 15 mph, or in a rain or thunderstorm. 
- Undine: in shallow or deep water, in a swamp, or within 1 tile of a natural spring, pond, river, riverbank, lake, lakeshore, ocean, or coastline tile.

An elemental altar of the appropriate aspect always counts as appropriate.

If those conditions are met, the EoC checks through their spells to find a spell that they know. When it finds one, it adds Deduction * 100 xp to it. Repeat until all spells are at max.

This encourages each fae to set up the appropriate elemental conditions for their base.

#### Testing

image

No observable slowdown even with only one spell known (meaning it had to cycle through various branches of the EoC to land on that one spell) 

Tested on each of the appropriate fae types making sure I got the message and nothing crashed or went into an infinite loop. Not loops observed. EoCs triggered in appropriate terrain.

### CODE REVIEW

**Comment by Rokharn** [comment]
If looking at spell progression of Xedra Evolved, this reward seems pretty small.

For example if player have world with Dino mod Undine way to leaving near river can be suicidal because of hordes of Dino zombies. And what's for - just for exp from one extra spell cast (or even less) per day? Maybe at least just check if any inf water source like forest mini lakes and so on here (where folklore undines normally appear). You know, undine is not naiad to needs exactly so big water sources like rivers. 

Same for salamanders. Why their need map check, why not just a active fire source nearby? For example salamander with MOM psychokinetic powers surely can feels like on volcano at any time their want.

**Comment by Standing-Storm** [comment]
> Same for salamanders. Why their need map check, why not just a active fire source nearby? For example salamander with MOM psychokinetic powers surely can feels like on volcano at any time their want.

For the simple reason that it is not possible to check if there is a fire nearby, or even “within X tiles”, using EoCs. Once that functionality is added, this can be updated to include it. 

The point about ponds is a good one—I’m not sure it’s possible to check for a map special that’s not an overmap tile, but I’ll look.

**Comment by Rokharn** [comment]
> not possible to check if there is a fire nearby

When cooking and crafting the game can check if there is fire nearby. Is that's not same thing to check? Or EoC limitation?

**Comment by Standing-Storm** [comment]
> When cooking and crafting the game can check if there is fire nearby. Is that's not same thing to check? Or EoC limitation?

The latter--they use different code.

**Comment by Rokharn** [comment]
About Undine. 

Some locations like private park or pool can else contain decent amount of water. Private park itself contain good pond with flowers and trees, so very nature free. About pool and so on - not sure, if it's good idea, even if it's contain huge amount of water, but water is water.

**Comment by Standing-Storm** [comment]
> About Undine.
> 
> Some locations like private park, fishing pond or pool can else contain decent amount of water. Private park itself contain good pond with flowers and trees, so very nature free. About pool and so on - not sure, if it's good idea, even if it's contain huge amount of water, but water is water.

Private park and similar location are covered by the blanket condition of being in water, I think, though a city fishing pond seems more wild than the other too and being close to it should work. Pool strikes me as too artificial to count for a water spirit, with all the chemical treatments that go into making a swimming pool in America

**Pull request merged**
