### PR TITLE
Nerf makeshift machete in comparison to items used to create it

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

Balance "Makeshift machetes are no longer more powerful than a kitchen knife used in their construction"

#### Purpose of change

The makeshift machete is an improvised weapon made from taking the blade of a large knife (butcher's knife, chef's knife, etc) and wrapping it in duct tape.

It doesn't feel like this makeshift hack should be a *better* weapon than the knife it was made from, which actually has a proper handle and everything, and yet its stats were significantly better than any of the knives it could be created from.

#### Describe the solution

This change reduces the machee from bash 5, cutting 16(!), to bash 2, cutting 10. For comparison, a butcher's knife is bash 2, piercing 10.

#### Describe alternatives you've considered

Nerfing the machete even more. Buffing kitchen knives. Actually playing C:DDA for more than a few minutes before submitting a rebalancing PR. :)

#### Testing

Fired up game with changes applied. Checked makeshift machete stats.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I guess instead of nerfing the makeshift machete we should revise components it's made of, more specifically, the `blade`. It contradicts its own description as it depicts itself as a "large blade", but has only 9 cm length, and this is way too short for a machete. 
Maybe we should craft machete directly from knives. Or maybe we should increase length of blade to bring it in accordance with knives' length (butcher knife has overall length of 35 cm, without handle it should roughly be half of that, ~17 cm, almost twice as long as current blade's length).

**Comment by Photoloss** [comment]
This whole assortment makes no sense. You can create a "makeshift machete" from some dinky kitchen knife or a lawnmower blade by wrapping the tang/handle in duct tape which somehow makes it a viable blocking implement, yet a meat cleaver with a nice professional handle and a wide blade you can easily brace against does *not* have the blocking technique. But if you take the cleaver apart you get a blade which can be used to craft the makeshift machete. Except with this nerf that would simultaneously reduce the cleaver blade's cutting capacity, even though there should be no need to mess with the blade portion at all. Not that magically *increasing* the damage instead is better, but this standardised intermediary "blade" just messes thing up all around.

**Comment by anoobindisguise** [comment]
The real issue is probably that it should only accept the lawnmower/manhack blade as a component.

**Comment by Alex-Folts** [comment]
Not sure what is the issue, makeshift_machete made of blade, item blade have mass of ~550g which should be more or less enough for machete, blade made by blacksmithing, or from sword/machete. Sounds fine to me.

Maybe as pointed above, blade should not be obtained from knives, or knives should yield some small blade.

**Comment by Photoloss** [comment]
> item blade have mass of ~550g

Mass doesn't mean much without further details. A tool blade like you might find on a lawnmower will be pretty thick and sturdy, thus quite heavy for its length and width. Meanwhile a scythe or a falchion can be incredibly thin for its size.

In this particular case a lawnmower or a large cleaver are quite suitable and the manhack is fictional so that can fit too. But a cleaver or lawnmower blade would be pretty much useless as a makeshift bayonet and would require a lot of grinding to use as a small scythe.

**Comment by Alex-Folts** [comment]
> > item blade have mass of ~550g
> 
> Mass doesn't mean much without further details. 

Unfortunately there is not specified length. But what makes me wonder - this blade made from sword or normal machete, so it must be large enough.

**Comment by Night-Pryanik** [comment]
> Unfortunately there is not specified length.

Huh? The blade I seen in game has only 9 cm length.

**Comment by Alex-Folts** [comment]
> > Unfortunately there is not specified length.
> 
> Huh? The blade I seen in game has only 9 cm length.

```
{
    "type": "GENERIC",
    "id": "blade",
    "symbol": "/",
    "color": "light_gray",
    "name": { "str": "blade" },
    "description": "A large, relatively sharp blade.  Could be used to make bladed weaponry, or attached to a car.",
    "category": "spare_parts",
    "price": 28000,
    "price_postapoc": 50,
    "material": [ "steel" ],
    "weight": "553 g",
    "volume": "750 ml",
    "bashing": 6,
    "cutting": 8,
    "to_hit": -1,
    "qualities": [ [ "BUTCHER", -38 ] ]
  }
```

**Comment by I-am-Erk** [comment]
So, the problem here is *definitely* the `blade` item, not the makeshift machete. We need to review where we use a `blade` and, I would say, make probably 3 items - `blade_small` about 5cm, from a paring knife or similar, `blade_medium` about 12cm, from a chef knife or similar, and `blade_long` about 30cm, from a machete, shortsword, or similar. Some things that currently use `spike` could also be converted to use one of these blades, or at least accept as an alternate.

We might also add a `blade_cleaver` item (source obvious), which itself could probably be made into a makeshift hatchet.

**Comment by Photoloss** [comment]
Ideally we'd just have a single modular "blade" item with properties for blade length, number of edges, point, weight/thickness, temper, balance etc. There's nothing really stopping a survivor from adding a medieval hilt to a katana blade or mounting a xiphos on a pole but good luck making a wood-chopping machete from a scythe blade.

**Comment by I-am-Erk** [comment]
Yes, later we might particularly try to distinguish things like number of edges and curve of the blade, but I think as long as we keep the blade items for making `makeshift` items for now, it should be fine to abstract it. If you salvage a blade from a katana to make a machete you're not pushing verisimilitude all that far, especially when we're coming from salvaging a paring knife to do it.

**Comment by pjf** [comment]
I concur that `blade` is the issue here, and that regular kitchen knives shouldn't yield machete suitable blades.

I won't have the timely opportunity to review our knives and adjust recipes to distinguish between blade lengths, but in light of the discussion this PR doesn't feel like it should be merged.

Should I open an issue with links to the relevant parts of conversation and close this PR, or is there a better way to preserve this discussion and work required?

**Comment by Maleclypse** [comment]
> I concur that `blade` is the issue here, and that regular kitchen knives shouldn't yield machete suitable blades.
> 
> I won't have the timely opportunity to review our knives and adjust recipes to distinguish between blade lengths. I've marked this PR as a draft to indicate it should not be merged as-is.
> 
> Should I open an issue with links to the relevant parts of conversation and close this PR, or is there a better way to preserve this discussion and work required?

Issue with links to this PR please.   Thank you for your effort. :)

**Comment by pjf** [comment]
Thank you!

Closed in favour of #53514.

**Pull request closed without merging**
