### PR TITLE
Stackable Currency

### LINKED ISSUE #47740: Currency Stacks/Denominations
# Is your feature request related to a problem? Please describe.
There's some wonkiness around merchant inventories, particularly with currencies(Merch, FlatCoin, Hub Coins). After asking around, people said it wasn't likely to be fixed soon.

# Describe the solution you'd like
So my proposed solution--Reduce the amount of currency items in merchant inventories without reducing the actual amount of currency in their inventory. To that end, I propose a simple solution. Adding items that get unpacked into multiple currency items, along with a way to craft them.

Specifically, I propose that merchants be given items that are 10 times as costly as the normal currencies they carry and which can be crafted from/uncraft to 10 of their respective currency. Then, the normal currency be pared to no more than 10 currency, plus one of these cash-stacks for every 10 this would knock off.

For Merch, I recommend that this be called 'Clipped Merch'--a money clip with 10 merch in it. For FlatCoin and HubCoin, i suggest that they be either 'handfuls' or 'pouches'.

# Additional context

### PR DESCRIPTION
**Pull request by Grubleafeater**
#### Summary
Bugfixes "Make currency stackable"

#### Purpose of change
Simplifies trading; fixes #47740

#### Describe the solution
Adds a ammo type, 'scrip', and assigns all factional currencies to it. Scrip was used because Money is in use for cash cards. 

#### Testing
Opened a new world and teleported to the refugee center. Testing uncovered #48523 but no issues appeared to be inherent to the function of this change.

### CODE REVIEW

**Comment by Grubleafeater** [comment]
Reports of a missing comma are heresy and/or fixed.

**Comment by casswedson** [comment]
Test reported:
image

**Comment by anothersimulacrum** [comment]
Please  don't convert more things to count_by_charges (e.g. ammo) that don't need to be it.

**Comment by Grubleafeater** [comment]
> Please don't convert more things to count_by_charges (e.g. ammo) that don't need to be it.

The problem is that right now, shops have a few million merches/scrips/etc instead of just having merch(50) or even '50 stacks of merch'.

Plus, non-charged items take a century to pick up and put down.

**Comment by anothersimulacrum** [comment]
Okay, then those issues should be fixed, we should not institute hacks in their place.

**Comment by kevingranade** [comment]
I strongly agree with @anothersimulacrum that this is not an ok fix to the stated problems.  We can and should have another mechanism for marking items as stackable in various UIs, and the fact that there's any kind of performance issue triggered by manipulating a different kind of item needs to be fixed, not avoided.

**Pull request closed without merging**
