### PR TITLE
merge lockpicking and traps skills into a new "devices" skill, add proficiencies for it

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Infrastructure "Merge trapping and lockpicking skills into a new 'devices' skill, expand scope somewhat"

#### Purpose of change

The "trapping" and "lockpicking" skills are both highly niche, representing only a couple of things that can be done in the game. They both also represent a certain fairly equivalent set of fine motor skills that are transferrable.

#### Describe the solution
- Merge the trapping and lockpicking skill and call it "devices". 
- Add currently nonfunctioning proficiencies for "lockpicking", "trap disarming" and "safe cracking". Adds crafting proficiencies for "traps" and "trap setting". Assign these to appropriate professions. Someone with some code abilities could make it such that these jobs are more difficult without the appropriate proficiency...
- Move some of the coarse crafting out of traps and into fabrication (nailboard, eg)
- Move some other aspects of fine device manipulation and crafting into the new devices skill
- Move trap and lockpick recipes out of the bloated recipe_others file and into a new recipe_traps file or into tools.json as appropriate.

#### Describe alternatives you've considered
I think these need to be merged, the name and what falls under the umbrella could change.

In particular I think devices could replace mechanics in a lot of things where mechanics serves to represent "little moving parts". Gun crafting comes to mind, and ammo has been suggested below. I know nothing about these skills so would appreciate feedback. That should be done in a second PR.

It has been observed that trap spotting probably should be moved out of this skill. I agree but don't have the ability nor energy to do that just yet. I think it should probably be governed by a trap related proficiency, so that you get a bonus for working specifically with traps in the devices skill, but I don't know that it needs to be a skill all its own. If it does we should probably make a new skill ("observation" or "awareness"?) and add a bunch of other things to it, representing the learned parts of the perception stat.

#### Testing
image

Improvised lockpicks are easier to make with the lockpicking proficiency, but making them doesn't grant lockpicking proficiency XP.
image

Not knowing how to make traps has a slight impact on time, but a high impact on failure rate when crafting the trickier stuff.
image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
The "skill X has only niche use. Let's merge it with completely irrelevant skill Y that has niche use as well!" rationale is flawed. If you think that some skill is underused, make it more useful or remove it from the game, don't merge it with some other underused skill in a naive assumption that this merge will suddenly make them both worthwhile.

As I said on reddit, lockpicking as a proficiency makes much more sense as a part of mechanics rather than a part of traps.

**Comment by Zireael07** [comment]
+1 to making lockpicking a mechanics proficiency.

> Some of what currently falls into Survival might fit here.

What do you mean?

**Comment by Amoebka** [comment]
Merging lockpicking and trapping creates a bizarre situtation where picking locks makes you better at noticing burried landmines from afar.

Really, what's wrong with having skills with niche uses? If you feel like leveling the skills isn't worth the time due to their limited applications, you can simply make them "peak lower" by relaxing the skill requirements on the high-end locks/traps.

**Comment by I-am-Erk** [comment]
Our skill system has almost infinite examples of weird things, like how bicycle repair make you better at welding, and making clay bowls teaches you to build desks.

The primary reason for this is that what constitutes a "skill" needs to be a single transferrable skillset, and the individual knowledge bases are moving into "proficiencies". Lockpicking isn't s single transferrable skillset, there are many things that you can be good at that carry their skill over into lockpicking: anything that requires an extremely delicate and precise touch, navigation by feel, etc 

Mechanics shares a general *concept* with lockpicking, but nothing *transferable*, since the concepts of lockpicking are pretty easy to begin with. Operating mechanics tools has nothing in common with picking locks. On the other hand, disarming a hair trigger has everything in common with it. They're very nearly the same thing.

As mentioned above, the distinction between what makes the sub-skills different should become proficiencies, just like how pottery is a distinct proficiency of fabrication now. Then the skill itself, whether it's called "traps and locks" or some better name like "legerdemain" or "devices", represents your overall finesse with this type of fine work and delicate tool.

**Comment by Zireael07** [comment]
No, trapping and lockpicking do not go together. They have nothing in common except the hair trigger example.

If you insist on making them go together, lockpicking and picking subtle traps could indeed be a 'devices' skill, but trapping (as in, making complex traps and spotting landmines) has nothing to do with 'devices'.

**Comment by I-am-Erk** [comment]
Basically every element of disarming traps is, trivially I would say, similar to lockpicking. Setting many traps is as well, it is actually very surprising to me to get any pushback on that. Remember we're talking about the manual motor skills and precision here, not the knowhow. The knowhow is more governed by recipes and proficiencies.

Spotting traps is less related, and so should have a proficiency basis, and possibly be divorced from skill level entirely. It's far more about your perception ability and the simple question of understanding how traps are set. I don't think being very good at constructing a snare or dismantling a shotgun trap without setting it off makes you better at spotting landmines either: the problem there has nothing to do with the addition of lockpicking to the skill set, it exists already. Why does placing nailboards make you better at spotting landmines?

**Comment by Zireael07** [comment]
Most traps in CDDA do not have a hair trigger - they are either snares or they react to pressure.

**Comment by I-am-Erk** [comment]
> Most traps in CDDA do not have a hair trigger - they are either snares or they react to pressure.

Disabling: Same skills apply to
- beartrap
- landmine
- crossbow trap
- shotgun trap
- blade trap
- dissector

Setting: Same skills apply to
- beartrap
- crossbow trap
- shotgun trap

Same skills don't apply to
- nailboard
- bubble wrap
- constructing blade trap
- setting landmine
- laying caltrops

I can't see any argument at all that these differences are more disparate than the differences between welding and general mechanics, any two branches of fabrication, making a salad and baking a cake, organic chemical extraction and metallurgical scintering, or the disparate ends of any general skillset. I can see an argument, a good one, that nailboards and caltrops should be fabrication, and blades on an engine should be mechanics. Setting those kind of traps shouldn't be a skill at all.

Overall we are faced with two options:
- have skills be nontransferable. Knowing how to disable a spring loaded trigger has no connection to lockpicking. Being able to disable one security system doesn't help your skills with another. Then we should apply this rule elsewhere, which has already been considered and doesn't work well for a game with such broad range of ability.
- Have skills be transferable, using categorical skills the same as we already do. This means some counterintuitive stuff, like practicing pottery makes you a better blacksmith. However, it does mean that learning how to work wood helps you work plastic or metal. We have developed a whole proficiency framework that's being implemented now to help categorize unrelated subskills to try to establish the parts that are nontransferable.

**Comment by Profit0004** [comment]
This is premature, I agree that they are both underused but trapping and lockpicking just seem so different.  Yes, they both can require dexterity, but honestly lockpicking more requires special tools and that skill than dexterity.    The easiest is just a bump key, you file down any key some, put a piece of rubber on it and lightly tap it with something.   It works for the vast majority of locks just takes a bit of time to do.   Less as you get experienced.

**Comment by Amoebka** [comment]
Placing nailboards makes you better at spotting landmines because you better understand where a competent trapper would place their traps and therefore have a better idea on what to look out for. A bit of a stretch, but a lot less of a stretch than "fie motor skills make you better at spotting tripwires".

**Comment by I-am-Erk** [comment]
> This is premature

It's a draft PR with me engaging in discussion. I don't know what is premature about that. I haven't even opened it for review, let alone merge.

Bump keys are a red herring. They don't exist in game. If they did, it's highly debatable if they'd rely on a skill level at all. Your ability to pick a lock with a tension wrench and picking set would be no more applicable to using a bump key than your ability to disable a spring mechanism.

**Comment by I-am-Erk** [comment]
> Placing nailboards makes you better at spotting landmines because you better understand where a competent trapper would place their traps and therefore have a better idea on what to look out for. A bit of a stretch, but a lot less of a stretch than "fine motor skills make you better at spotting tripwires".

And, again, I don't know that spotting traps should be related to your traps skill level, as I said above. That whole cross-training issue can be removed by making it related to your *proficiency* with traps, and your perception score.

**Comment by Amoebka** [comment]
At that point proficiencies basically remain de-facto separate skills that are lumped together in the UI for an arbitrary reason though.

**Comment by I-am-Erk** [comment]
I'm not sure what you mean. Proficiencies *are* separate skills.

**Comment by Amoebka** [comment]
"Devices are a skill that combines traps and locks, but it doesn't actually help you detect traps AT ALL unless you have the trap detection proficiency" is essentially an admission that traps should be a separate skill completely, but they aren't. It is inconsistent with how proficiencies are defined for other skills - high skill in fabrication DOES help with blacksmithing even if you have no blacksmithing proficiency.

**Comment by I-am-Erk** [comment]
Even if I removed lockpicking from traps, I would be making the same argument: Identifying a landmine should not be made easier by batch-constructing caltrops.

**Comment by Amoebka** [comment]
This is a good argument. Trapping is currently a "weird" skill. We have skills for making things (fabrication, tailoring) and skills for interacting with the world (computers, first aid), trapping combines both. This, however, is a separate issue that doesn't really has anything to do with combining trapping and lockpicking and doesn't act as a good reason to do so.

**Comment by I-am-Erk** [comment]
It is a relevant argument, but I'm slightly frustrated because it's one with an answer that seems quite apparent to me.

- Parts of trapping are related to making components of traps. These are better suited for fabrication and/or survival (separate debate, a lot of survival belongs in fabrication as well and fabrication probably needs to be two skills).
- Parts of trapping are related to spotting traps. We don't have currently any skill that fits great with that, but we could represent it as a small bonus from certain proficiencies. As a nice aside, this would allow removal of this unfortunate bit from the detect_trap code:
```
           // Police are trained to notice Something Wrong.
           ( p.has_trait( trait_PROF_POLICE ) ? 1 : 0 ) +
           ( p.has_trait( trait_PROF_PD_DET ) ? 2 : 0 ) >
```
making it data driven instead.

- Parts of trapping are related to precision work setting and disabling delicate devices. This is conveniently similar to lockpicking and safecracking. Lockpicking and safecracking should also be skill based. Lockpicking, safecracking, and disabling traps all share an obvious common thread. These can be merged into one skill which will have a more appropriate umbrella similar to other major skills.

It is, frankly, quite startling to me that there's any pushback on this at all, let alone more pushback than I received for making survivor armour several orders of magnitude harder to craft.

**Comment by Amoebka** [comment]
While I generally agree with your proposal, you skipped over the second point, which is the weak link here. We, indeed, do not have a good place to dump the trap spotting part of the skill. My guess is you want to make it dependant on either trap making proficiency withing fabrication, or trap disarming proficiency within your new devices skill, or both. This is far from ideal, however, as neither skillset is really relevant for spotting traps without extreme mental gymnastics. A person can train to spot traps without knowing much about disabling them and without knowing how to smith beartraps from steel.

My radical argument here is that perception should move from being a stat to being a skill, and then we can dump trap detection as a proficiency there along with other things.

**Comment by I-am-Erk** [comment]
I don't know about perception being a skill, because it relates to things that can be seen as genetic eg. ability to see at night. However, it might be an option to look into "spotting" or something like it as a skill.

**Comment by Zireael07** [comment]
+1 to "spotting"/"awareness" as a skill.

**Comment by I-am-Erk** [comment]
Before it gets made a skill there would need to be a lot more discussion about what could fit into it. It would be worth making an issue to discuss it.

**Comment by Amoebka** [comment]
A more formal way to put it would be, each stat should have one or more correlated skills that represent the ability to improve in that regard, with the stat itself representing the unchangeable "genetic factors".

Strength has swimming (shouldn't we have some sort of "athletics" skill? running a lot makes a person better at running).

Dexterity already has dodging and swimming.

Intelligence has computers, speaking and bartering (these two could probably be combined into a single social skill, no?).

Perception could have this new "awareness" (doesn't really matter how it's called).

**Comment by I-am-Erk** [comment]
I'd really rather this be taken out of this PR discussion, but my already-existing long term plans are, roughly:
- merge speech and barter to "social".
- reorganize fabrication and survival somehow. Probably split out "crafting" for smaller, less durable things like pottery, glassmaking, and jewelrymaking. Still nebulous. Some of survival is crafting/fabricating, I'd prefer that to be out of it.
- change swimming to "athletics", add a couple swimming proficiencies, make it relate to your success climbing downspouts and trees and things
- glare at the "chemistry" skill until a good name for "general laboratory benchwork procedures skill" occurs to me and then roll biology and similar stuff in there
- Add an "inventing" skill, name pending, representing prototyping and designing new stuff and also rediscovering old stuff when you don't have a recipe book.
- Figure out how to reasonably expand cooking to be 'food handling' including stuff like butchery, but also some non-food stuff like tanning should be in there, I haven't got that figured out yet.

Adding an awareness skill could fit in there, but I'd need a better idea of what would actually fall under awareness besides spotting traps. Most likely we'd actually need someone to implement a bunch of new code that tied into the skill, which honestly would probably be really great, but that's out of my scope of abilities. Stuff like 'noticing a shady zombie further away' could go in for example.

This stuff isn't in an Issue because, as you can see, I haven't sorted the details out yet.

**Comment by cosmo-naut** [comment]
This is beginning to get outside the scope of this PR but I'd like to add my thoughts as I think they are somewhat in-line with your intentions Erk. This is all hypothetical to open up the conversation.

Skills should be relevant to the actual action/school of thought that they utilise, and proficiencies are relevant to the application.

For example, with a 'fine mechanisms' skill that requires minute movements, this would help for actions such as lock picking and trap disarming, as well as soldering and ammunition reloading.

Fabrication makes sense as a skill. Logically it should also contain welding and general 'tool working' but not necessarily the design of such things. You can fix and build things, but a high fabrication does not necessarily let you invent things you haven't otherwise seen the internal workings of.

An engineering skill could come into play and encompasses what I believe you intend by the 'prototyping' skill. It relates specifically to the design of certain objects. Proficiences would include such things as combustion which takes on some of the current mechanics stuff as well as electronics and perhaps even programming, which in turn take from the electronics and computers skills respectively.

One of the big flaws of the system I am proposing is it will be code heavy. My understanding is that only crafting recipes actually utilise proficiencies.

**Comment by Night-Pryanik** [comment]
Let's ask ourselves a simple question: "Does it make sense that setting up caltrops/nailboard/landmine makes your character better at picking locks?". If the answer is "no", then the traps skill - which governs the aforementioned process - isn't the best candidate to merge with the lockpicking skill.
Even if some part of the traps skill (in particular, disarming traps) has something common with the lockpicking skill, other parts of the traps skill _in our current implementation_ are just too different and don't fit. We need either to rework the traps skill, or just don't try to merge something that doesn't fit.

**Comment by Fris0uman** [comment]
I think Erk already answered that:

"
   - Parts of trapping are related to making components of traps. These are better suited for fabrication and/or survival (separate debate, a lot of survival belongs in fabrication as well and fabrication probably needs to be two skills).
   - Parts of trapping are related to spotting traps. We don't have currently any skill that fits great with that, but we could represent it as a small bonus from certain proficiencies.
   - Parts of trapping are related to precision work setting and disabling delicate devices. This is conveniently similar to lockpicking and safecracking. Lockpicking and safecracking should also be skill based. Lockpicking, safecracking, and disabling traps all share an obvious common thread. These can be merged into one skill which will have a more appropriate umbrella similar to other major skills.

"

**Comment by Night-Pryanik** [comment]
I asked not about "part of trapping", but rather about the whole traps skill as we have it right now. Erk is not dividing current traps skill into several parts, he suggests combining lockpicking skill with traps skill as a whole in its current implementation.

**Comment by Zireael07** [comment]
@cosmonaut has a good idea concerning "devices/fine mechanics/fine manipulation" skill - soldering and ammo reloading would be excellent uses for it.
@Night-Pryanik I agree, merging as a whole is not the way to go. Splitting some things up, merging some others and renaming, on the other hand...

**Comment by I-am-Erk** [comment]
I know nothing about ammo reloading, but I do think that stuff like that should get added to this skill blanket.

Soldering is a tricky one, but yeah, it's conceivable we could bring a lot of electronics in here, which could in turn lead to splitting electronics up a bit, possibly moving the more theory-based stuff into computers or applied science? Would need further discussion.

For this PR I can see about adjusting a bit of the crafting recipes, but I don't plan to do everything in one go.

**Comment by Zireael07** [comment]
No one is saying it has to be done in one go, but I'd like the PR title up there to reflect the current status quo (it doesn't look like you're merging the two anymore from the recipe changes, and it's likely a part I of multiple?). Would help reduce confusion ;)

**Comment by I-am-Erk** [comment]
I'm still merging the two, and I just changed the description

**Comment by I-am-Erk** [comment]
I am not sold on the "devices" name, I think "sleight-of-hand" might be another good one, but I am also open to the idea of moving a bunch of the gun crafting stuff out of mechanics and into devices, in which case it remains a good name. Opening up to review now.

**Comment by Zireael07** [comment]
Gun crafting imho straddles the line - if it goes in, maybe rename to 'fine machinery' instead of 'devices'?

**Comment by I-am-Erk** [comment]
I don't see much difference in definition between "devices" and "fine machinery". It's an easy change if someone feels like doing it though.

**Comment by I-am-Erk** [comment]
Yay finally got those dang green checks.

**Pull request merged**
