### PR TITLE
[Innawood] Various improvements based on feedback

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Mods "Various Innawood improvements"

#### Purpose of change

Includes various improvements to the Innawood mod found by playtesting both by myself and by others. Mainly discussed at #53960

#### Describe the solution

All changes are to the Innawood mod only.
- Adds mineral loot to more caves
- Makes craters not be radioactive
- Makes cotton repairable with rag again
- Makes plank armguards and plank sword craftable with sticks
- Makes most brewing and distilling recipes autolearn
- Makes many cooking recipes using foraging components autolearn
- Makes water faucet and pilot light auto learn
- Makes fermenting barrels no longer require water faucets

#### Describe alternatives you've considered

Remove craters altogether. Right now the vague lore is that either a meteorite crashed in the large craters, or maybe Mi-Go dropped bombs on fungi structures. It is intentionally left vague, but I think there is enough non-human reasons why craters might exists.
Rework cotton repairing mechanics. Before this pull request, many items could be crafted without cotton, but required cotton to repair. Since cotton is basically non-existent in this mod, it meant many of the clothing items you could craft could not be repaired. Preferably, an item should be repairable by the clothing items used to craft it. But until that has been fully implemented, this temporary fix makes it possible to repair your items for now.
Alternatively, make wild cotton spawn, or make it possible to acquire cotton seeds. Sadly, cotton is not native to New England, which is still the growth zone this mod is taking place in.
Being able to mix seeds with mutagen to create other seeds could be an interesting way to gain access to cultivated crops such as cotton, maybe?
Make separate wooden armguards with different flavour text that describes the item being made out of sticks instead of planks. Maybe make bark arm guards as a stand-in for paper armguards as well.
Instead of removing water faucets from fermenting barrels, a way to make water faucets could be implemented. Currently they require plastic, which is not craftable without vinegar, which is not craftable without a fermenting barrel. Rubber could be used as a substitute, but that is not craftable in game, and all recepies I found requires vinegar or some other hard to get resource.
Again, having a research system for recipes as an in-between between autolearn and only learnable from books would be neat.

#### Testing

Made a character and warped around to different caves to make sure cave material would drop properly. They did. Checked that cotton clothing could be repaired by rags. They could.

### CODE REVIEW

**Comment by kurtisvetter** [comment]
Sheep can't be sheared currently, since shears cannot be crafted without plastic or a vacuum mold. Either the shears recipe should be changed, or possibly the kevlar shears should be given the shearing quality.

**Comment by Proxima-b** [comment]
Without a cave, portal storm can I extremely irritating. prolly should lower protal storm chance.

**Comment by Proxima-b** [comment]
Even after finding a cave, there will always be a NPC blocking the entrance, they need to be removed

**Comment by Proxima-b** [comment]
Also I think steel lump should not be manually crafted, should it act like charcoal production?
One big problem of manual crafting is when I tried to craft a large batch, and got interupted, i will be imposible to pick it up and continue.

**Comment by AcidAntOnAMinefield** [comment]
> Also I think steel lump should not be manually crafted, should it act like charcoal production? One big problem of manual crafting is when I tried to craft a large batch, and got interupted, i will be imposible to pick it up and continue.
I assume that you are trying to [g]rab-pick up the item which being too heavy/volumous, the interface won't allow you if you have dangerous pickups turned off or if your inventory has no spare volume for it.

This is easily fixable by \ dragging the "in-progress" item on top of a counter and then [e]xamining the counter to continue crafting, the normal way of doing it in a minimalistic setup. 

Otherwise, you can "[w]ield" the item and [a]ctivate it and it will continue the crafting process, provided your arms are not too damaged to hold items.

**Comment by NetSysFire** [comment]
How are you supposed to get a clean water supply? With rural mapgen and city size 0 you could randomly find tin cans in the bushes which you can use to boil water, even if it is one unit at a time.
The closest thing you could make innawood is a clay pot but that requires some work to get to.

**Comment by Proxima-b** [comment]
> > Also I think steel lump should not be manually crafted, should it act like charcoal production? One big problem of manual crafting is when I tried to craft a large batch, and got interupted, i will be imposible to pick it up and continue.
> > I assume that you are trying to [g]rab-pick up the item which being too heavy/volumous, the interface won't allow you if you have dangerous pickups turned off or if your inventory has no spare volume for it.
> 
> This is easily fixable by \ dragging the "in-progress" item on top of a counter and then [e]xamining the counter to continue crafting, the normal way of doing it in a minimalistic setup.
> 
> Otherwise, you can "[w]ield" the item and [a]ctivate it and it will continue the crafting process, provided your arms are not too damaged to hold items.

However, batch production materials are too heavy to use either these methods.

**Comment by Proxima-b** [comment]
Also, is there any ways to get mechanics skills?

**Comment by AcidAntOnAMinefield** [comment]
> However, batch production materials are too heavy to use either these methods.

uh... no? 
Item weight/Volume has literally 0 interference when you \ haul items along the ground. Normal counters have a 1000L volume to them. And up to 200 or 300kgs you can wield items using the [w]ield command. It will be painful but you can do it.

**Comment by AcidAntOnAMinefield** [comment]
> Also, is there any ways to get mechanics skills?

Build Wooden Frames. Start Vehicle Construction, then if you have the tools to deconstruct it, just remove the part and do it again. Easy to get to level 1 that way, despite being tedious. Then you just need to do mechanics recipes if you have the materials, unless you just so happen to find a car you can practice on or Supply Crates Drops you can repeatedly seal and pry for easy experience.

**Comment by Proxima-b** [comment]
> > However, batch production materials are too heavy to use either these methods.
> 
> uh... no? Item weight/Volume has literally 0 interference when you \ haul items along the ground. Normal counters have a 1000L volume to them. And up to 200 or 300kgs you can wield items using the [w]ield command. It will be painful but you can do it.

it can't at my side, not without a table/workbench

**Comment by Proxima-b** [comment]
I can't find a way to make glass ,which should be done in medieval age

**Comment by Light-Wave** [comment]
> Sheep can't be sheared currently, since shears cannot be crafted without plastic or a vacuum mold. Either the shears recipe should be changed, or possibly the kevlar shears should be given the shearing quality.

To my knowledge, there are no sheeps. But adding shearing to kevlar shears sounds reasonable.

> Without a cave, portal storm can I extremely irritating. prolly should lower protal storm chance.

You are safe while inside a makeshift shelter. But I'll look into delaying the start of the storms a little.

> Even after finding a cave, there will always be a NPC blocking the entrance, they need to be removed

You can often run past them. But maybe they should be less hostile?

> Also I think steel lump should not be manually crafted, should it act like charcoal production? One big problem of manual crafting is when I tried to craft a large batch, and got interupted, i will be imposible to pick it up and continue.

The big problem with that is that to make it act like charcoal production requires messing around with C++ code. To continue, you might be able to construct a crafting spot and drag the item onto there. Still, the whole thing breaks if you tries to craft a batch of more than around 20. A batch size of 10 seems safe enough. Maybe the recipe should be reduced in size to prevent these issues.

> How are you supposed to get a clean water supply? With rural mapgen and city size 0 you could randomly find tin cans in the bushes which you can use to boil water, even if it is one unit at a time. The closest thing you could make innawood is a clay pot but that requires some work to get to.

Clay pots is the way I do it. Maybe clay should be more common?

> Also, is there any ways to get mechanics skills?

What I found: Create a light wooden frame, use construction menu to start vehicle production, open the vehicle menu and remove the frame. Repeat until level 1. At level 1 you can create a banded wheel for example, and repeatedly install and remove it to grind to level 2. Perhaps a training recipe should be included?

> I can't find a way to make glass ,which should be done in medieval age

With fabrication 4 and chemistry 4 you can make glass shards from sand, ammonia, and some other easy to get stuff. You need a sheet metal for that.

**Comment by NetSysFire** [comment]
>Clay pots is the way I do it. Maybe clay should be more common?

Maybe. I do not know. The main problem is that getting clay requires hard work, which dehydrates you even quicker and I currently have both tapeworms, brainworms and severe pain because of that since I had to drink water from a lake.

**Comment by Light-Wave** [comment]
> > Clay pots is the way I do it. Maybe clay should be more common?
> 
> Maybe. I do not know. The main problem is that getting clay requires hard work, which dehydrates you even quicker and I currently have both tapeworms, brainworms and severe pain because of that since I had to drink water from a lake.

Oof. I found that rushing clay pots is quite important. At your point you might want to restart and try a different strategy. You could also try to go for mugwort oil. Chemistry 3 and survival 4, I believe. But getting to it with brainworms might be rough.

**Comment by NetSysFire** [comment]
I think you need to port the fix for #53637 to this mod. I just checked and caves are still buggy.

>Oof. I found that rushing clay pots is quite important.

Yeah. We might need some parasite balancing, but this is also impacting the base game, so out of scope for this mod.
In "vanilla", you usually have something you can loot or even start with a bit of water, giving you some time. Unfortunately I have no idea how this could be compatible with the innawood gameplay.

**Comment by Light-Wave** [comment]
> I think you need to port the fix for #53637 to this mod. I just checked and caves are still buggy.

Indeed. I'll include that in next patch.

> Unfortunately I have no idea how this could be compatible with the innawood gameplay.

Agreed. I think I will add a starting location that is on a clay mound, and make them slightly more common. As long as you find clay somewhat early during day 1, you have fairly good chances of survival.

**Comment by Proxima-b** [comment]
So here's the thing, I started make steel lumps in batch of 6 (24total), the raw material weighs 418.89kg, so after I start the production, I drop the in production item for food and water.
But when I was tring to pick it up to continue afterward, it said Too heavy tp pick up, so that I cannot continue. a workbench did not help.

**Comment by AcidAntOnAMinefield** [comment]
> So here's the thing, I started make steel lumps in batch of 6 (24total), the raw material weighs 418.89kg, so after I start the production, I drop the in production item for food and water. But when I was tring to pick it up to continue afterward, it said Too heavy tp pick up, so that I cannot continue. a workbench did not help.

Haul the "in-progress item" on top of the workbench, then you yourself stand next to it then examine the workbench and the option to "craft" / "resume crafting" is there. It works for me on a test world, I don't see why it wouldn't work for you in this case, unless you are missing materials or tools due to lack of proximity or something.

**Comment by Light-Wave** [comment]
> So here's the thing, I started make steel lumps in batch of 6 (24total), the raw material weighs 418.89kg, so after I start the production, I drop the in production item for food and water. But when I was tring to pick it up to continue afterward, it said Too heavy tp pick up, so that I cannot continue. a workbench did not help.

> Haul the "in-progress item" on top of the workbench, then you yourself stand next to it then examine the workbench and the option to "craft" / "resume crafting" is there. It works for me on a test world, I don't see why it wouldn't work for you in this case, unless you are missing materials or tools due to lack of proximity or something.

Indeed, you have to drag it to a crafting area and then interact with the crafting area, pick "work on craft or disassembly", I believe.

**Comment by AcidAntOnAMinefield** [comment]
Here it is.

6x Lumps of steel is 24kg, so you should very easily be able to even wield the item in your hands as a weapon too.

https://youtu.be/1lKgU9kf4sM

But yeah, that's essentially it. 
If your item is larger than 30L though, it won't work the same way in a vehicle workbench because of its limitations.

**Comment by Proxima-b** [comment]
Would it be possible to make flintlock rifle and pistol and black powder as a late-game goal of this mod? I seem to remember those have book requirement...

**Comment by Light-Wave** [comment]
I will reduce the amount of resources needed and steel crafted by a factor of four in the next patch. That will make it safe to batch craft 50 units without breaking the game, although a crafting spot would be needed for that. The batch crafting speed bonus has also been altered to stay mostly in line with previous experience.

> Would it be possible to make flintlock rifle and pistol and black powder as a late-game goal of this mod? I seem to remember those have book requirement...

Good idea. That seems like a lot of recipes that needs to be altered, but I'll add it to my todo.

**Comment by Proxima-b** [comment]
> Good idea. That seems like a lot of recipes that needs to be altered, but I'll add it to my todo.

Simply remove all book requirement would be a possible solution, I couldn't think of anything that would break the gameplay

**Comment by Light-Wave** [comment]
> Simply remove all book requirement would be a possible solution, I couldn't think of anything that would break the gameplay

Would be nice if there was an easy way to do that, I suppose.
As for the flintlock weapons, it seems like their ammo requires lead. Now I would want to make lead, tin, and copper minable and refineable, but that is a bit of a larger undertaking.

**Comment by Light-Wave** [comment]
Implemented some of the suggestions in #54181

**Comment by Proxima-b** [comment]
> Would be nice if there was an easy way to do that, I suppose.

Actually there is, just open all recipe json files(not that many) with notepad++

First use regular expression search mode, wrap around
replace
`.*autolearn.*\r?\n`
with
`                 ` (nothing)
that will delete all lines containing autolearn (prevent duplicate).

Then use extended search mode, wrap around
replace
`"time"`
with
`"autolearn": true,\r\n    "time"`
that will add autolearn entry to all items.

I suppose that could make them all autolearn.

**Comment by Proxima-b** [comment]
As for lead, tin, and copper, just make them drop by crushed stone (along with flint, stones and pebbles) in small amount, and make very rare "bog" of those metal. 
A regular furnace should be able to refine them.

**Comment by Proxima-b** [comment]
I would love helping you with the code but I still can't use github properly

**Comment by Proxima-b** [comment]
Also I was thinking, maybe this mod could make bronze age technology more important, a prerequisite to get steel maybe？

**Comment by AcidAntOnAMinefield** [comment]
A genuine question:
Were *all* buildings just essentially removed? And I mean potential cabins, broken sheds, farms etc?
I think it wouldn't be "unrealistic" to see like a random campsite (moderately rarely) / campgrounds (very rare) or two, hunting blinds (very rare), broken sheds or desolated barns and stuff like that (hell, it'd be a "fun" way for players to finally experience the "OG" Wraith for example. :)

**Comment by NetSysFire** [comment]
Yes they were. Use the rural mapgen mod (conflicts with this mod) and set the city size to 0 if you want a couple buildings like campsites and cabins and stuff.

**Pull request merged**
