### PR TITLE
Added folding stock to MP7

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
It should have a folding forward grip, but the game doesn't support folding grip.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Gonna be offline for a few hours.

**Comment by Noctifer-de-Mortem** [comment]
Can't you do a `copy-from` of the grip and create an `intergrated_grip` similar to the `integrated_bayonet` and add the folding flag to it?

**Comment by pisskop** [comment]
this makes it capable of being ankle holstered, is this intended, or even possible irl

**Comment by kevingranade** [comment]
Based on your title and description I thought you were adding a folding stock instead of a folding forward grip.  Might want to be a little more clear.
What's the rationale for decreasing the volume? Its already quite small, and after applying the folding stock reduction it's tiny.  5 volume after applying the folding stock bonus seems about right, which afaict is what you'll get if you leave the base volume at 7.

**Comment by Rivet-the-Zombie** [comment]
>this makes it capable of being ankle holstered, is this intended, or even possible irl

Not sure if it's intended here, but it is possible IRL.

**Comment by kevingranade** [comment]
I'm sceptical of ankle holstering a stock mp7. An image search shows a bunch of "stock" mp7s in thigh holsters and a few images that claim to be mp7s in ankle holsters, but they clearly dont have a stock, just a pistol grip.  A base mp7 is 16.3" long (that's with the stock collapsed) according to Wikipedia, that's crazy long for an ankle holster.

**Comment by Rivet-the-Zombie** [comment]
That's a very good point; our 'ankle holster' items seem to be quite small, so that might be a bit much.

**Comment by BorkBorkGoesTheCode** [comment]
Woah, I didn't expect to be away for so long. Sorry.

@Noctifer-de-Mortem I just tried adding a folding grip made with COLLAPSIBLE_STOCK and NEEDS_UNFOLD flags using a newer experimental. The flags don't seem to negate the volume of the folding grip when stored so much as decrease the volume 7 MP7 to volume 5.

I'm going to revert the volume reduction.

**Comment by BorkBorkGoesTheCode** [comment]
>this makes it capable of being ankle holstered, is this intended, or even possible irl

@pisskop which mod increased the volume limit of the ankle holster to 4 cups? The size of the MP7 with folding stock was only decreased to 4 cups.

**Pull request merged**
