### PR TITLE
Fixed (some) dissection proficiencies (part 3)

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Adjust dissection proficiencies along the lines of #68760 comment 3.
This mainly means adding physiology to a whole lot of places, but the nether critters are not easy to judge. Ended up with "demihuman" on the reasonably biological ones.

#### Describe the solution

See Purpose of change.

#### Describe alternatives you've considered

Reviewers should probably look at this section...

- Ignored natural armor on the grounds that I don't have any feeling for when it should and shouldn't apply.
- Letting "demihuman" be used as it's described and named, but the prior usage rather indicates it's used as "near earth biology", and so that usage was adopted. Could have tried to rename it in its descriptions.
- Adding the normal set of proficiencies on all the weird nether stuff, but opted for only adding it to what's somewhat near normal biology.
- Using the modification syntax to modify proficiencies on inherited critters rather than a complete replacement. Went for the replacement as the risk of screwing up the syntax is lower, at the cost of potentially slightly more maintenance down the line.

#### Testing

Debug spawned and debug killed one critter from each modified file and checked that dissection should provide the proficiencies given.

### CODE REVIEW

**Comment by Terrorforge** [comment]
> Letting "demihuman" be used as it's described and named, **but the prior usage rather indicates it's used as "near earth biology"**, and so that usage was adopted. Could have tried to rename it in its descriptions.

I don't think that's true. As far as I can tell, it was consistently used only for humanoid and once-human monsters. The notable exception is Mi-go, but I thought the implication there was that mi-go are (something similar to) humans who warped themselves into unrecognizability with their biotech. Maybe that was just my headcanon, though.

At any rate, the name doesn't work if you're going to use the proficiency like this. People are going to be really confused when they go to dissect a Yugg and find that it's considered "near human". Unfortunately I don't think just changing the name is a great solution either because the proficiency is used extensively in mods, particularly Magiclysm, for their various elves and orcs so just changing it "alien biology".

I think the correct answer is creating a new "alien biology" proficiency to apply to the netther creatures, but in its absence I think "near human biology" should be taken off the wholly inhuman nether creatures.

**Comment by PatrikLundell** [comment]
Thanks for your input @Terrorforge. That's exactly the type of feedback I was asking for in the alternatives section.

I can't see the mi-go originally using a terrestial like biology given that they're not edible, thus implying they're not using the normal chemical substances used by terrestial life (would they even be edible to the life that normally break down biological material?). I guess it would be possible to achieve the inedibility through a chirality swap, but I fail to see what the point of that would be.

I'm perfectly happy to reverse the nether changes and strip the demihuman proficiency from the ones that don't seem even remotely humanoid, but I don't think I have enough knowledge to introduce a nether biology proficiency, and definitely not any associated weakpoint. Also note that I won't do the change based on only your feedback, given that @I-am-Erk merged the commit, so I'd need to await a senior contributor vote on this issue.

**Comment by Terrorforge** [comment]
There are plenty of terrestrial creatures that are inedible. Mi-go aren't necessarily inedible because their biochemistry is fundamentally incompatible with ours, they might just be poisonous. They drop "tainted meat", same thing as zombies, which does suggest there's something more fundamentally wrong with it than that, but it also suggests they have some sort of connection to the blob, which doesn't seem right either. I wonder if that was just meant as a stopgap until someone got around to creating Mi-go meat? At any rate, I'm not super attached to this interpretation, but if it's _not_ the case that Mi-go are some kind of variant human, I don't think they should have the demihuman proficiency. They should have their own proficiency, probably in addition to physiology and intro_biology. And this is mostly a lore question, so yeah I'm happy to wait for guidance on that.

Fwiw, if I understand the system correctly, there's no inherent connection between proficiencies and weakpoints. In principle, you could give a monster families:prof_wp_syn_armored and weakpoint_set:wps_arthropod_flying and your experience with circumventing kevlar would help you hit it in the wings. So I _think_ it would be as simple as adding an entry to data/json/proficiencies
/weakpoints.json and naming it in the relevant entries, and that would hlp you hit whatever weakpoints those monsters already have. Incidentally, for Mi-gos that's actually wps_humanoid_body, which again doesn't really seem right, but I guess it's the closest we have without creating a custom weakpoint set for them.

**Comment by PatrikLundell** [comment]
Hm. It seems I'm wrong. I wonder where I got that from, as I was rather sure of it? Well, time to adjust to reality...

While it would be better if mi-go dropped their own meat, a general "poisonous" effect provided by the tainted meat is probably better than it not being poisonous in the mean time.

However, in that case I agree biology and physiology would fit them, as well as some mi-go specific one that would require physiology as well as a lot of work (given its rather alien physiology, it can't be that easy to figure out what of the stuff inside it might be vulnerable. Does destroying an "arm" provide any more benefit than just general damage?).  I agree they don't fit demihuman, as they've got lots of legs, lots of "arms", useless wings, and a weird "head" (based on its description). Not exactly a humanoid body plan...
A specific mi-go weakpoint set would probably be useful.

I don't really understand weakpoints, but it does indeed seem to be the case that they're disconnected from proficiencies, which I find a bit odd. I had expected specific proficiencies to activate their bonuses versus specific weakpoints, somewhat similar to how proficiencies can require prerequisites. The weakpoints are there, but there'd be no bonus to find them without the knowledge of how to find them, so you'd need luck. Well, that doesn't seem to be how they work anyway.

And, by the way, I would not use the same proficiency for fantasy races as I'd use for nether weirdnesses. In fact, I'd expect the normal set of fantasy races to be human enough to fully follow the human plan (things would be different for centaurs, harpies, nagas, and the like, of course). You might possibly make use of the child (human) variations for short races, since they probably have proportionally large heads (and possibly the small head for really big ones).

**Comment by Terrorforge** [comment]
The description of the "near human biology" proficiency does say it represents "very basic familiarity", so it might represent knowledge as basic as having taken apart enough of them to confirm that they have bones to break.

But I think you have a point. In vanilla, "demihuman" seems to refer to something pretty specific. According to the lore docs, the Nether creates "creatures, places, and things that resemble mundane objects and ideas from whatever came in contact with the netherum, often in twisted and confused ways,", and 'demihuman' appears to be the term for any such twisted reflection of a human being. I _guess_ it makes sense to use it for e.g. orcs in the sense that it's the "ok it's basically a person but I'm not gonna bet my life on the assumption the heart is in the same place" but they could probably use their own thing

**Comment by PatrikLundell** [comment]
Well, the biology of fantasy races depends on the fantasy setting. In D&D fantasy races are actually races, i.e. biologically compatible with normal humans when it comes to procreation, as well as the procreation of those offspring (as opposed to e.g. mules, who essentially are sterile). In other settings things may be set up differently and fantasy races are separate species, potentially with special biological traits which makes making anatomical analogies riskier. I have no idea what the C:DDA mod lore(s?) are.

**Comment by I-am-Erk** [comment]
Migo aren't meant to be edible, there's an issue up for that already.

Really, every netherum creature should probably have its own proficiency, or at most we could have a "netherum abomination" proficiency. Mi-go should be their own thing.

**Pull request merged**
