### PR TITLE
Animal-mutants can eat animal food of their kind

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Features "Animal mutants can eat respective animal food"```

#### Purpose of change
It seemed odd to me that mutated folk could not eat food specifically designed for their animal "predecessors".

#### Describe the solution
**Post-threshold**:
- felines can eat cat food (with joy, humans can eat it with negative joy),
- lupines can eat dog food (with joy, humans can eat it with negative joy),
- birds can eat bird food,
- bovine/cattle can eat cattle fodder.

#### Describe alternatives you've considered
Considered using some smoother approach, had to use "dirty" hack to decouple eating action of this food with special action designed for those type of food allowing it to be fed to animals.
There might be other alternative foods like this.

#### Additional context
Nutrition, health, and vitamin values were **ROUGHLY** based on typical ingredients, and may be off. If you think so tel me here, and I'm willing to change it. This kind of item actually benefits from pulling calories from ingredients "on the fly", if you consider what options there are to create it.

### CODE REVIEW

**Comment by Photoloss** [comment]
The joy values might be a bit excessive. Modern cat&dog food is not really made to be the absolute most enjoyable culinary delight but rather "good enough" to meet nutrition standards. Cheap brands will contain a significant amount of what the game normally classifies as "butchery refuse", check points 3&4 [here](https://pets.webmd.com/cats/guide/how-to-read-cat-food-labels) for example. +2 health is pretty high too, although if that were also flipped based on mutations it'd make sense as decent foods do often contain vitamin additives.

Options for homemade and "deluxe" pet foods or dedicated treats would justify the implied quality, and could be expanded as more effective pet befriending/training options in the future.

**Comment by nexusmrsep** [comment]
> The joy values might be a bit excessive.

We're talking animal food here. These are especially delightful for those particular animals only and not at all for humans, and I want to reflect that. I'm not speaking from experience of course, nor are you (at least I hope so!), so I'm making assumption that if I was a feline mutant cat food would be especially attractive for me. I don't think I wish to go as deep as differentiating normal vs. luxury, but you may pick up from here and make an add-on later. If someone else also agrees that this bonus is a bit too much then I'll reconsider lowering it.

**Comment by Photoloss** [comment]
I *am* speaking from experience in the sense of cats being snobs and outright *refusing* to eat arbitrary brands of that "delicious" food. Dogs will eagerly [kill themselves](https://pets.webmd.com/dogs/guide/dogs-and-chocolate-get-the-facts) to make you happy so I'm not sure how to classify "joy" there (should chocolate be poisonous for lupine mutants? mandatory carnivore for post-thresh feline?) One thing to be aware of is that mutant PCs do still maintain a mostly human mind which will definitely perceive wet pet food as an unappetising mushy brown paste. The confirmed mind-altering mutations would if anything make you regret missing a hunt rather than appreciate a nutricious bowl.

Cattle and bird should be alright, you already assigned lower joy values and birds sure do love those feeders.

**Comment by Shodan14** [comment]
What about carnivores being able to eat raw meat?

**Comment by dissociativity** [comment]
I feel as if mice and rats should be able to eat all of the above

**Comment by KorGgenT** [comment]
just checking: are the vitamin values you're using RDA percentages?

**Comment by Crunchepillar** [comment]
> (should chocolate be poisonous for lupine mutants? ... ) 
Additionally dogs and cats both find most of anything from the family Allium to be at least mildly poisonous (This includes human favorites like Garlic, Onion, Leek and Chives). I'd love to see that added to dietary restrictions as a consequence of going hard on lupine mutations. 🐶

Obviously this would require adding a new material type and updating items that use those ingredients but I think it would be heckin neato.

**Comment by kevingranade** [comment]
I agree that these food items wouldn't be seen as super delicious to most of the targeted animal types, much less mutated variants of them.  They should be reasonably healthy though.

**Comment by nexusmrsep** [comment]
Ok, that's fair, but that logic can be turned around: you wouldn't have to make those specific items to tame animals if they also like other food. Why make dog food when you can feed it with meat? Why make cattle fodder if you can feed it with wild veggies? This makes me think that there might be a need for a flag or other mechanism to trigger tame using different food types, aka animal diets. Am I right?

**Comment by kevingranade** [comment]
Yep, the whole animal food thing is kind of silly.
I'm not sure how much detail we want to put into it though, this isnt a ranching simulator... yet.

**Comment by nexusmrsep** [comment]
Following discussion, I've cut the extensive fun of the animal food. This PR is now ready to go.

**Comment by kevingranade** [comment]
I'm guessing both Travis and Gorgon are going off the rails because we haven't merged this PR in so long, I don't see any reason for it to be cancelling the job.

**Pull request merged**
