### PR TITLE
Added HPL's Book and made it spawn very rarely in mansions and libraries

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "Added HPL's Book and made it spawn very rarely in mansions and libraries."

#### Purpose of change
To add more Easter Eggs and homages.

#### Describe the solution
Added the Book and made it spawn in mansions and libraries. The chance to spawn is very low.

#### Describe alternatives you've considered
None.

#### Testing
Started game without errors.

#### Additional context
None.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Well, yes, I doubt there's something _fun_ in this book.

**Review by Maleclypse — APPROVED** [review]
Very nice!

**Comment by Amoebka** [comment]
Could probably use INSPIRATIONAL flag to make it more fun for spiritual characters.

**Comment by Night-Pryanik** [comment]
> Could probably use INSPIRATIONAL flag to make it more fun for spiritual characters.

I'm not sure about this. As far as I know, the book drives people mad, no matter if they spiritual or not, so adding fun seems wrong here.

Though in the future we may add a sect worshipping the Old Ones, and they indeed could get a fun value for reading the book.

**Pull request merged**
