### PR TITLE
Add significant encumbrance to dance shoes

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by NickGrease** [comment]
Did you mean 5? 50 seems a bit much.

**Comment by Coolthulhu** [comment]
They aren't THAT fancy.

Plus, 40 (after fitting) is clown shoes tier.

**Comment by Night-Pryanik** [comment]
Regular shoes on heels give 50. I used them as reference point.

**Comment by dbackeus** [comment]
Well being dance shoes they would be designed to be agile so seems like they should be lower encumbrance than regular shoes on heels.

**Comment by Night-Pryanik** [comment]
I think that the "heels" is the keyword in their description, not "dance".

**Comment by NickGrease** [comment]
> Regular shoes on heels give 50. I used them as reference point.

A pair of Roller Blades is 15. I get that heels are supposed to be difficult to move around in, maybe a debuff to move speed is more in order than an encumbrance equal to steel power armor?

**Comment by Coolthulhu** [comment]
Currently foot encumbrance is just a move speed debuff.

**Comment by NickGrease** [comment]
> Currently foot encumbrance is just a move speed debuff.

True enough. A character with heels and an American flag might as well be wearing concrete slippers :)

**Comment by Rivet-the-Zombie** [comment]
By definition, dance shoes are light and comfortable to wear - you are, after all, expected to be able to *dance* while wearing them - and shouldn't have an encumbrance of fifty; their current encumbrance value is fine.

**Comment by Night-Pryanik** [comment]
Of course I never wore something like this, 
245-70sl-fox_lla_019-c-m-rn__catin_kedr_9-1_1xx_xxxxx1
, but from my man's point of view I find it hard to move or even more so dance comfortably in them. 
I think their main sense is beauty, not comfort.
If all my thoughts about encumbrance of these shoes is incorrect, I'll close this PR, no problems.

**Comment by Night-Pryanik** [comment]
obuv-dlya-tancev-3
These shoes I find fitting zero encumbrance very close, not the ones with heels.

**Comment by NickGrease** [comment]
[Do Not Ask How I Found This](https://www.youtube.com/watch?v=kc17H68IKMs)

**Comment by Shadefang** [comment]
I personally always pictured them [along](http://litbimg5.rightinthebox.com/images/190x190/201112/xxorox1325239358348.jpg) [these](http://2lth8w1uv77536l8d72pqh10.wpengine.netdna-cdn.com/wp-content/uploads/2011/03/1940s-dance-shoe-character.jpg) [lines](http://litbimg1.rightinthebox.com/images/190x190/201506/xbbcca1434704925238.jpg). Men's dance shoes should be slightly less encumbering than dress shoes, and women's should be FAR less encumbering than heels. That's what they're designed to be; Fancy shoes that are easier to move in than normal fancy shoes.

**Comment by WizardOfOoo** [comment]
Dress shoes are 15, 
Boots are 10, Steel toed boots are 15

Moccasins, Sneakers, and dance shoes, are  0
The protection values of these shoes are in line with each other and the materials they are made of.

Clown shoes are 60 for a reason.
http://i.imgur.com/cp02WPq.jpg

I don't see a need for a change.

**Pull request closed without merging**
