### PR TITLE
Add hot chocolate

### PR DESCRIPTION
**Pull request by Cyrano7**
Added hot chocolate and Mexican hot chocolate. Also normalized chilie powder with the rest of the spices. If the values seem low for the ingredents its beacuse the result is muti 2x on recipe side.

### CODE REVIEW

**Comment by shedya** [comment]
Aren't hot chocolate and hot cocoa different things? Hot chocolate refers to a thick drink made from molten chocolate and hot cocoa is made by mixing cocoa powder with milk.

**Comment by Cyrano7** [comment]
@shedya according to Wikipedia they are interchangeable.
https://en.wikipedia.org/wiki/Hot_chocolate

**Comment by shedya** [comment]
Alright, got it.

**Comment by mugling** [comment]
> Also normalized chilie powder with the rest of the spices.

A future PR implementing an abstract for these would be an excellent follow-up

**Pull request merged**
