### PR TITLE
Remove Solar Panels CBM

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Based on https://github.com/CleverRaven/Cataclysm-DDA/pull/20696#issuecomment-289637185.

Two questions:
1. How to properly obsolete bionic in `bionics.json` (added a comment for now)?
2. How to properly obsolete a recipe for the CBM in `recipe_electronics.json`?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> How to properly obsolete a recipe for the CBM in recipe_electronics.json?

Remove it from books and autolearn.

**Comment by smolbird** [comment]
This seems rather pointless and a terrible approach to the problem. These are advanced cybernetics including a Megaman blaster, a literal nuclear reactor crammed into your gut, a teleportation device, even the ability to freeze time.

In comparison a bunch of solar panels is downright plausible. Any realism argument to be made here is arbitrary and pointless.

**Comment by smolbird** [comment]
> Why is that? Realism in the fundament for the whole game.

No, the fundament for the whole game is this being a game. Realism shouldn't take priority over good gameplay, and there's literally nothing gained from removing these.

> By the way, how do you see solar panels working on a fully clothed character?

You gave up on the PR too easily. Yes, reducing power generation while clothed would be an annoyance, but there are time periods where the character is idling when the "undress a bit" step could be abstracted out. We already abstract out ability to get warm and comfortable and such while waiting or resting.

The entire PURPOSE of solar CBM is a power generator that functions while the player is idle in good conditions. Making it so that the player gets the most out of the CBM while idle fits its purpose perfectly.

**Comment by Night-Pryanik** [comment]
Then it shouldn't be working in every season except for summer, as I find it hard to imagine someone would be undressing just to get some power, even if idling. Too much abstraction, don't you think?

> and there's literally nothing gained from removing these.

The gain is getting rid of poorly thought non-realistic thing.

> Realism shouldn't take priority over good gameplay

Why don't we add some super-mega-power-source-cbm that don't require no fuel and will work in each and every condition, ever? This would be fun and add greatly to the gameplay!

**Comment by ZhilkinSerg** [comment]
Solar Panel CBM output would be ridiculously low. It is good to have them removed.

**Comment by BorkBorkGoesTheCode** [comment]
I think the Whale's Cataclysm and Granade cataclysm communities are splitting now.

**Comment by Mecares** [comment]
Maybe migrate it to a mod? Instead of removing  it completely?

**Comment by Leland** [comment]
The existence of the internal furnace is a decent parallel here. Stands to reason that the solar panel CBMs could exist – it's just another means to produce energy.

The burden, then, is then to come up with some canon of how the CBM could be installed in such a way that it wouldn't be affected by clothing.

**Comment by kevingranade** [comment]
> Stands to reason that the solar panel CBMs could exist – it's just another means to produce energy.

I disagree, outside of some wacky anime-like nudist cyborg community (I'm looking at you Kill La Kill), there's no reason to install or even build a solar panel CBM, since it is rendered useless if you do something as simple as wear clothes.  Between that and the fact that one of the greatest weakness of a PV panel (fragility) is utterly ignored, it crosses a line from "impractical but a good idea if it worked" to "doesn't make sense even if it does work".

> The existence of the internal furnace is a decent parallel here.

It is, buuuut..... it's also utter nonsense and should ALSO be removed or reigned in (mostly it's too fast and produces too much power).
For example, what if it's a miniaturized plasma incinerator? https://www.wired.com/2012/01/ff_trashblaster/ Turns out these things work, don't produce much in the way of byproducts, and in super-science theory could produce energy out of fairly arbitrary inputs.

> Maybe migrate it to a mod?

Crazy cataclysm welcomes nonsensical additions.

**Comment by Leland** [comment]
> one of the greatest weakness of a PV panel (fragility) is utterly ignored

Head-canon for that caveat should be relatively easy, this being future tech. Ex extremely durable material that's still photovoltaic

> there's no reason to install or even build a solar panel CBM, since it is rendered useless if you do something as simple as wear clothes

This is the real hurdle to me

**Comment by smolbird** [comment]
> It is, buuuut..... it's also utter nonsense and should ALSO be removed or reigned in (mostly it's too fast and produces too much power).

Metabolic Interchange is already king of power supply, so we're basically giving the players even fewer reasons to NOT use MI.

I mean we could balance the systems that exist with gameplay constraints in mind, or we could go for full realism and just remove CBMs entirely.

**Comment by kevingranade** [comment]
> Metabolic Interchange is already king of power supply, so we're basically giving the players even fewer reasons to NOT use MI.

And it's also utterly ridiculous, you may be noticing a pattern.

**Comment by smolbird** [comment]
> And it's also utterly ridiculous, you may be noticing a pattern.

Bionics in general are ridiculous, is that the pattern here?

**Comment by Coolthulhu** [comment]
> And it's also utterly ridiculous, you may be noticing a pattern.

So is:
* Reactor bionic
* Furnace bionic
* Ratchet bionic
* Alcohol burner bionic

The battery charger may seem OK at first, but that feeling passes fast.
Honestly, the only actually "realistic" recharging bionic is the cable charger.

If all but one recharging bionics are gone, what is going to replace them?
They're pretty "fun".

Oh, and I forgot:
@Night-Pryanik 

> How to properly obsolete bionic in bionics.json (added a comment for now)?

Search for the bionic's id in the whole `data` folder and `src` folder too. There are professions that have it and I think also hardcoded spawns in mapgen.

**Comment by smolbird** [comment]
> If all but one recharging bionics are gone, what is going to replace them?
> They're pretty "fun".

Agreed. At that rate we might as well just cripple the CBM system entirely in the name of realism. Or we could just accept that these CBMs need to exist for gameplay reasons, and balance them as best as can be with their gameplay roles in mind.

**Comment by DracoGriffin** [comment]
If it is meant to continue, it should act opposite of the [Body Part] Alloy CBMs; just as the fragility of the panels suggests.

So instead of just flat "you generate energy in sunlight", it's "you can generate energy in sunlight, but you also take more damage in [installed limb]" -- and essentially break it up into the same pieces (I believe Head/Torso/Arm/Leg) -- or at least Torso/Arm, but if both installed, the energy generation is equal to the original energy generation amount. Encumbrance could also be used as a factor of lowering energy generation.

**Comment by Night-Pryanik** [comment]
> Search for the bionic's id in the whole data folder and src folder too. There are professions that have it and I think also hardcoded spawns in mapgen.

Yes, did that, thanks.

**Comment by Night-Pryanik** [comment]
As an alternative I can suggest activable Solar Panels CBM that will retract when activated much like this



They will charge energy only when retracted and will be very fragile. Serious hit to the torso can break the panels, and the bionic will be removed.

**Comment by illi-kun** [comment]
@Night-Pryanik this concept is much better than simple removing cbm, it's a correct fix of described issues with current solar panels.

**Comment by ZhilkinSerg** [comment]
`C` in CBM states for "Compact"? These butterfly wings are cool, but not so compact - where are they stored when folded?

**Comment by illi-kun** [comment]
I guess it's cyberbionic module.

**Comment by illi-kun** [comment]
> Serious hit to the torso can break the panels, and the bionic will be removed.

I'd hold this change till 0.D release, because Coolthulhu proposed the reasonable changes for bionics in #20629 (to track fault status of each of bionics module) but it seems that we keep significant bionics changes for post 0.D time.

In case of implementation of the mentioned feature, the damaged solar panels will not be removed entirely but just tagged as faulted.

**Comment by Night-Pryanik** [comment]
> where are they stored when folded?

I'd say in some small box implanted on one's back.

**Comment by Night-Pryanik** [comment]
Honestly now I'm more in favor of retractable solar panels.

**Comment by smolbird** [comment]
> Retractable is just as bad as unretractable, if not worse.

Better to actually try and rebalance them instead of removing them outright.

**Comment by Night-Pryanik** [comment]
> They're even more fragile

Not now, maybe in the future, and even then only in retracted state.

> they still conflict with clothing on the torso

We can pretend that the box containing folded panels are worn over the clothing, so they don't conflict.

And retracted variant have one big advantage - it is plausible.

**Comment by illi-kun** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
> Not now, maybe in the future, and even then only in retracted state.

The way you're describing the feature, it *should* be even more fragile, but instead it's still impossible to damage.

> We can pretend that the box containing folded panels are worn over the clothing, so they don't conflict.

Make a box with retractable solar panels that you wear outside your other clothes then, not a CBM that by definition doesn't have such a box.

**Comment by smolbird** [comment]
> There an approach to making a solar powered bionic system that's a million times more reasonable than having a bionic. Install the cable carger CBM, make a solar-powered charging station with as many panels as you can find and a bunch of bateries, periodically recharge from the station.

Too bad portable vehicles are kinda awful. Sure, tie the player down to a cart with a solar panel welded to it. After eliminating all other methods of power supply in the name of "realism"

**Comment by Nymall** [comment]
I agree. While the amount of power generated was minute, it is in line with joint torsion ratchet. This feels like a difficulty re-balance in the name of making the game harder and nothing else. The old problem of balancing to the loudest voice is causing a problem here. At present level, it's not even enough to keep a suit of power armor going.

So, here's my question - Why was this needed? Was it to make the player more reliant on vehicle based power systems? And as we've removed this system, what is it being replaced with? Why not make the CBM a lab prize - increase the rarity. The initial line references an off hand comment at the end of the issue which summarizes as "too difficult, remove". I don't understand why this wasn't just left at that(not possible), or removed to a mod instead of nuking from orbit.

**Comment by kevingranade** [comment]
This has nothing to do with game balance, it is strictly an issue of a cybernetically implanted solar panel being an absurd concept on its face.

**Comment by awesine** [comment]
m-muh realism

**Comment by TechyBen** [comment]
I'm sorry to dig this up and jump in.
But "is silly" is not a reason for IRL a product not to be released. If you wish for me to post citation, I will.
So, the fact is, can it be built, and can it be "useful". IMHO it would be.

For example, we have the tree roots mutation. Normally, it's pointless, right? You'd get eaten sleeping in the exposed fields, and rained on, and cold, and you can just eat (if in the mutation bracket, rotten) food.
But we do have it in game, as it serves a slight purpose and state branch to player customisation/role playing/story etc.

I could see some cyborgs in CDDA wanting a "survival" or "off grid" system. "I want to go camping, and not take a tone of chargebars.TM with me for my bionics". A solar option would be made. The "solar backpack" is a partial solution here. Another option would be, as above, fold out panels that only work when the player was "sunbathing", either arms/back/head (depending on location chosen for CBM) would need to be exposed (no problem for arms), and the player would be unable to do anything while charging (like the sleeping function of the roots mutation). It would slowly charge, and the player would be vulnerable to attack at this time.

Any/every CMB is "delicate/fragile" in the game. The argument that *all* of them would break easily can be made. Choosing Solar Panels over anything else makes *no* sense. Either choose most of the CMBs to be fragile, or state why Solar Panels are an exception here. :)

The panels could be said to fold up in an emergency, thus the player would only get charge when they were active+unfolded+sunbathing (one action to activate CMB), and any action would fold/stop them.
Are there CMBs that work like this already? Turn off on any player action other than waiting?

**Pull request merged**
