### PR TITLE
Denim expansion

### LINKED ISSUE #65677: Rework other survivor/mercenary clothing pieces.
### Is your feature request related to a problem? Please describe.

With the merging of #65494, the survivor cargo pants should receive similar treatment. Both light and normal versions use basic cotton and Kevlar to produce waterproof/rainproof pants, which don't make much sense, especially with recent material diversity.  

### Solution you would like.

The mercenary pants we have now should be considered as heavy-duty (Heavy Mercenary Pants), with the light and the normal survivor cargos having modernized coverage and protection. Material changes should be done as well to show a progressive increase in protection as you go up the mercenary armour grading. Using Denim/Canvas/Nylon as replacement for cotton would help as well

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### LINKED ISSUE #68731: Craftable Denim Sheets, Vests, Jackets and Armoured Denim Vests and Jackets
### Is your feature request related to a problem? Please describe.

Denim is unreasonably un-craftable in mainline, being just an alternate cotton weave compared to regular cotton, originally made in its semi modern version in the 1600's in France. To add to this, Denim Jackets and Denim Vests (new addition) should be made craftable, and Armored Versions of Each.

### Solution you would like.

Add a way to craft denim sheets
Add Denim Vests as a item, and a crafting recipe
Add a crafting recipe for Denim Jackets
Add both Armored Denim Vests and Jackets with their own crafting recipes, for parity with leather counterparts

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KeremBabaG**
#### Summary
Content "Add new denim items and recipes"

#### Purpose of change
Denim has kinda been forgotten since its conception. This pr adds some denim related items, recipes and spawns. The jean jacket is also off by being lightweight 8 oz instead of the average mediumweight denim (10-14 oz).

revives and closes #68731
(idk if you can actually do this)

#### Describe the solution
Add some new items, along with their recipes and spawns:
- [x] Jean vest
- [x] Pre-ripped Jeans
- [x] Jkirt (Denim skirt)
- [x] Denim shirt
- [x] Denim backpack
- [x] Denim overalls
- [x] Joots (Denim boots)
- [x] Jhoes (Denim shoes)
- [x] Denim cloak (craft-only)
- [x] Denim gloves (craft-only)
- [x] Armored jean jacket
- [x] Armored jean vest
- [x] Armored jeans

Add recipes for already existing denim items

Change jean jacket because it's weird

#### Describe alternatives you've considered
idk don't do this

#### Testing
In progress

#### Additional context
The values I will use in this pr are as follows:
10 oz: approx 284 grams per square yard (or 0.84 m^2, damn you americans)
12 oz: approx 340 grams
14 oz: approx 397 grams
16.5 oz: approx 467 grams

Our sheets are 12 inches(0.34 yards)(approx 30 cm) to 24 inches(0.67 yards)(approx 60 cm) which makes a sheet approx 0.23 square yards. According to #63913, 6 oz is 0.4 mm thick (1 oz = 0.067mm). That makes 10 oz approx 0.65, 12 oz approx 0.8, 14 oz 0.95, 16.5 oz 1,1 milimeter thick.

For the sake of cohesion, our denim sheets will be considered both 12 oz and 10 oz in our recipes, since it's unclear how thick our sheets actually are. The recipes above 12 oz will use excess sheets in accordance to weight. Items will be completely accurate though.

The average chest size of a man is 40", and the center back is at an average of 33". The armhole is 9" and the sleeve length is 18.5".  I took men's sizes as default because we don't have female/male crafting. [Here's where I take the sizes from.](https://www.craftyarncouncil.com/standards/man-size)

The jean jacket is based on Levi's trucker jacket, which is 14 oz, and the jean vest is just a sleevless version of that. Going from forementioned values, the sleeves require 0.5 square yards of fabric in total. Torso needs approx 1.5 yards. This makes 8 sheets in 12 oz, but I'll also add 2 sheets on top to account for the fact that this is 14 oz. 

This is more or less the measurement process, not gonna go into detail for the others except for the craft onlies. If there is a better method please tell me because this ain't actually very realistic. Gonna add the references below.

- Denim cloak is 16.5 oz with 4 square yards of fabric used. Which makes around 18 sheets + an extra 6 for thickening.
- Denim gloves are 10 oz with approx 0,5 yards used. Which makes around 3 sheets. 2 for fingerless.
- Denim boots based on [this](https://www.riceandbeansvintage.com/products/vintage-1974-acme-denim-western-boots). I couldn't find the thickness of both the cowhide and denim part so both values are an ameteur estimate.
- Denim sneakers based on [Zara (don't @ me) denim casual sneakers](https://www.zara.com/us/en/denim-casual-sneakers-p15427210.html). 10 oz with 3 cm soles.
- Denim shirt based on [wrangler](https://www.wrangler.com/shop/mens-iconic-cowboy-wash-denim-shirt-RKFID.html). Seems to be 12 oz. Based on medium measurements, 8 sheets.
- Couldn't find a detailed heavyweight denim overalls. Roughly 2,5 yards (1,5 for legs, 1 for torso). Roughly 16 sheets together with the extra and pockets.
- Backpack based on [eastpak pak'r](https://www.eastpak.com/uk-en/backpacks-c120/padded-pak-rr-black-denim-pEK62077H+00+999.html), but made with 16.5 oz denim. (It also seems that our standard backpack is based on this as well, given the values. This is it but made of denim.) 1 square yards. 5 sheets together with straps + 1 for thickening.
- Denim skirt on [this but without the pockets.](https://www2.hm.com/en_us/productpage.0779360001.html). Looks like 10 oz. [Half the size of a pair of jeans, which means 0.75 square yards.](https://denimhunters.com/denim-wiki/denim-explained/denim-weight/#:~:text=That%20means%20you%E2%80%99ll%20need%20around%202%20yards%20of%20fabric%20from%20the%20roll%2C%20but%20it%E2%80%99s%20still%20roughly%201.5%20square%20yards.) 4 sheets.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I have a pretty comprehensive rework to survivor gear in progress which will obsolete the sillier stuff and make what exists a lot more sensible. I'm unlikely to use denim in my versions as the primary concern is acid, which denim isn't going to help against. 

If you haven't gotten too far into working on that stuff yet, you may want to leave it be.

**Comment by KeremBabaG** [comment]
> I have a pretty comprehensive rework to survivor gear in progress which will obsolete the sillier stuff and make what exists a lot more sensible. I'm unlikely to use denim in my versions as the primary concern is acid, which denim isn't going to help against.
> 
> If you haven't gotten too far into working on that stuff yet, you may want to leave it be.

oh alright

I was only thinking about survivor cargo pants and heavy survivor gloves. Would you mind it if I momentarily replace their cotton with denim, until your rework?

**Comment by fairyarmadillo** [comment]
> > I have a pretty comprehensive rework to survivor gear in progress which will obsolete the sillier stuff and make what exists a lot more sensible. I'm unlikely to use denim in my versions as the primary concern is acid, which denim isn't going to help against.
> > If you haven't gotten too far into working on that stuff yet, you may want to leave it be.
> 
> oh alright
> 
> I was only thinking about survivor cargo pants and heavy survivor gloves. Would you mind it if I momentarily replace their cotton with denim, until your rework?

Cargo pants mostly aren't made of denim IRL, and survivor pants are made of pre-existing cargo pants or army pants, which are also not denim.

People don't really make gloves out of denim as it's a very bad material for them. They do make them out of leather and kevlar, which is what survivor gloves are made of currently. Even if I wasn't working on survivor gear, I don't think that would be an appropriate material for either item.

**Comment by KeremBabaG** [comment]
kk trusting your rework

**Comment by BlizzDA** [comment]
In the interest of expanding the domain of Denim, may I suggest Joots? The old 1980's ones and the more modern ones, which can exist as a pants+boots one-piece.

[https://mltshp-cdn.com/r/1NA81](url)

80's are vintage and could spawn in Pawn Shops. There's also exists denim-variant cowboy boots, which could be another good fit. 

Another fun one; pre-ripped jeans. A fashion statement pre-Cataclysm, a questionable legwear post-cataclysm. Less coverage on the bits meant to come pre-ripped.

**Comment by KeremBabaG** [comment]
sounds good: addded!

**Comment by BlizzDA** [comment]
If you're find with adding finds. Denim gloves. There's safety gloves made of denim. But notably, recycled jeans gloves (from a notable tailoring culture) that can come with or without pockets, depending on what part of the jeans are used. These are finger-less, but a tailor should be able to make ones with fingers as well. And simple denim hand/foot wraps would be logical to add since the other materials are covered. 

Safety: [http://white.tools/product/jeans-gloves/](url)

Fashion: 
85782904e08f598eaceb0480460bb3b4
Denim Fingerless Gloves With Large Wood Buttons Etsy

Lastly, denim sleeves akin to the cut-resistant sleeves item (in coverage) pops up on searches as well. The items are nothing too rare IRL to be implemented ingame from what I've managed to find.

**Comment by BlizzDA** [comment]
> If you're fine with adding finds. Denim gloves. There's safety gloves made of denim. But notably, recycled jeans gloves (from a notable tailoring culture) that can come with or without pockets, depending on what part of the jeans are used. These are finger-less, but a tailor should be able to make ones with fingers as well. And simple denim hand/foot wraps would be logical to add since the other materials are covered.
> 
> Safety: [http://white.tools/product/jeans-gloves/](url)
> 
> Fashion: 85782904e08f598eaceb0480460bb3b4 Denim Fingerless Gloves With Large Wood Buttons Etsy
> 
> Lastly, denim sleeves akin to the cut-resistant sleeves item (in coverage) pops up on searches as well. The items are nothing too rare IRL to be implemented ingame from what I've managed to find.

**Comment by fairyarmadillo** [comment]
The fashion items would be vanishingly rare.

**Comment by KeremBabaG** [comment]
Agree with fairyarmadillo on the last suggestion. I think denim boots and shoes are relatively common, but not gloves or sleeves.

**Comment by fairyarmadillo** [comment]
Something that might be useful is a denim cloak. Cloaks are OVERSIZE and BELTED so they can be worn over armor and even by mutants. Denim has some pretty decent stats and avoids a few of leather's pitfalls so it would make sense in some cases to want to make one.

I would make it craft-only though. Outside of like very specific festivalwear consignment boutiques you'd never see this sort of thing irl.

**Comment by KeremBabaG** [comment]
yeah good idea. added!

**Comment by KeremBabaG** [comment]
@BlizzDA decided to add gloves as craft-only as well since I'm adding cloaks

**Comment by fairyarmadillo** [comment]
The item should just be called and described as a denim skirt.

**Comment by KeremBabaG** [comment]
> The item should just be called and described as a denim skirt. "Jkirt" does not appear to be a common word for this object and a google search for it returns almost no relevant results. Same with the boots and shoes.

yeah googled them also and realized that :( 
The pr that added denim described it as "jkirts" and I thought it would be funny, changing it nonetheless

**Comment by KeremBabaG** [comment]
@fairyarmadillo you seem to know your stuff, any advices for measuring and shit?

**Comment by fairyarmadillo** [comment]
They should be called "denim boots" and "denim sneakers", anf you've made the boots and backpack waaaay too common. They should be like a tenth of what they are.

I'm also not sure the hardened armor vest or jacket should exist. Leather doesn't get anything similar, and denim is nowhere near as sturdy as leather is, so armoring it up is a much more dubious prospect.

**Comment by KeremBabaG** [comment]
> They should be called "denim boots" and "denim sneakers", anf you've made the boots and backpack waaaay too common. They should be like a tenth of what they are.
> 
> I'm also not sure the hardened armor vest or jacket should exist. Leather doesn't get anything similar, and denim is nowhere near as sturdy as leather is, so armoring it up is a much more dubious prospect.
> 
> The pre-ripped jeans should also probably not exist. The way to model them would just be as damaged jeans, but our system can't do that.

oops, gonna change them after I'm done with tweaking the values

The hardened leather jacket does exist. I also withheld the sturdy flag from the denim stuff, which the leather one does have.

Well these ones specifically don't have knee coverage. It also isn't sold or component of any recipes, I think they should stay

**Comment by fairyarmadillo** [comment]
> The hardened leather jacket does exist.

Oh whoops, I don't know how I missed that.

**Comment by fairyarmadillo** [comment]
As for measurements, the boots should probably only cover the feet, as otherwise they're going to conflict with wearing certain types of pants on the lower leg. If you look around at other boots, such as western boots and survivor boots, that's how they're set up.

This list looks great, but if you want to add another item, you could add skinny jeans, which are thinner than regular jeans but have a bit less encumbrance and like a third of the pocket size.

You could also add vintage jeans which don't appear in the regular item groups but have the Fancy trait so that stylish people can get a bonus from them. Vintage jeans IRL are anything over 20 years old, but the significant ones are from the 1970s or earlier: https://www.gearpatrol.com/style/a37928773/vintage-levis/

If you add these, be careful what itemgroups you put them in, vintage jeans wouldn't pop up in stores other than thrift stores.

**Comment by KeremBabaG** [comment]
> As for measurements, the boots should probably only cover the feet, as otherwise they're going to conflict with wearing certain types of pants on the lower leg. If you look around at other boots, such as western boots and survivor boots, that's how they're set up.
> 
> This list looks great, but if you want to add another item, you could add skinny jeans, which are thinner than regular jeans but have a bit less encumbrance and like a third of the pocket size.
> 
> You could also add vintage jeans which don't appear in the regular item groups but have the Fancy trait so that stylish people can get a bonus from them. Vintage jeans IRL are anything over 20 years old, but the significant ones are from the 1970s or earlier: https://www.gearpatrol.com/style/a37928773/vintage-levis/
> 
> If you add these, be careful what itemgroups you put them in, vintage jeans wouldn't pop up in stores other than thrift stores.

Yeah ok why not once I'm done with other stuff

**Comment by KeremBabaG** [comment]
Hey @fairyarmadillo how about I add those two in another pr. I'm kinda tired of this one and it got bigger than I anticipated.

**Pull request merged**
