### PR TITLE
[DONE] Police SUV and K9 vehicles

### PR DESCRIPTION
**Pull request by cake-pie**
- [x] add vehicles
- [x] add to vehicle groups (todo: how prevalent are K9 units?)
- [x] ? add variety to `policecar_pileup`

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Some screenshots with the added vehicles would be helpful.

**Comment by DracoGriffin** [comment]
> add to vehicle groups (todo: how prevalent are K9 units?)

Probably rare since it seems most of the states mainly have state-level K9 units rather than county/city-level K9 units, but loan them out to certain jurisdictions.

Connecticut: couldn't find a number, only number of graduates (which supposedly looks like need annual re-certification so not sure if that's a new additional teams or just the entire team being re-certified)
[Revere, Massachusetts](http://reverepolice.org/departments/k9-unit/) (as an example): "2 teams"
[Massachusetts](https://en.wikipedia.org/wiki/Massachusetts_State_Police#K9_Unit): "41 units"
[Maine](https://www.maine.gov/dps/msp/special_units/k9_team.html): "25 teams"
New Hampshire: couldn't find a number
Rhode Island: couldn't find a number
[Vermont](https://www.vtk9.com/current-teams.html): "51 teams"

**Comment by cake-pie** [comment]
Thanks @DracoGriffin , I also did some digging and found a more detailed breakdown for NYPD (not in New England, I know): [[2](https://thebark.com/content/job-nypds-k-9-teams)]
> * 40 transit (e.g. subway patrols)
> * 40 emergency service unit (e.g. vehicle patrol, response)
> * ~8 narcotics
> * ~8 bomb squad
Which we can put in context: ~100 dogs vs ~36,000 uniformed officers.

From that we can make a ballpark estimate of 60~70 K9 vehicles to support this many dogs -- 75~80% pursuit-rated, and the remaining of transport type, with some allowance for vehicles taken out for downtime.

[[3](https://www1.nyc.gov/site/nypd/about/about-nypd/equipment-tech/police-vehicles.page
)] NYPD have 9,000~10,000 vehicles in total. Subtract 10~15% for other types of vehicles, and then consider that their police cars are in approximately 2:1 ratio marked:unmarked. This yields an estimated 5,000~6,000 marked patrol vehicles.

Hence I would estimate K9 vehicles to be about 1~1.5% as common as a "normal police car" for spawn weighting purposes. Slightly higher in a city setting, lower for highways.

Does that sound reasonable?

**Comment by cake-pie** [comment]
Went ahead and redistribute policecar 50-50 between cars and SUVs.
Used abovementioned estimates for K9 vs regular units.

For review / comment / objections.

**Comment by cake-pie** [comment]
To test changes I made to the police pileup, I hacked `data/json/road_vehicles.json` so that it occurs with ridiculous frequently on many kinds of roads, then generated a new world. Here are a couple of samples, showing a mix of policecar and policesuv:

pileup1
pileup2

Around 17 or 18 pileups later, I found one that included a K9 vehicle:
pileup_ac
pileup_ac_e

**Comment by cake-pie** [comment]
One last thing while I'm at it: the vehicle spawn functions for city and police pileups are fundamentally identical, refactor to condense the two into one.

**Pull request merged**
