### PR TITLE
Adjust helmets to the new automated encumbrance modifiers system

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
None

#### Purpose of change

Follows up Slack's #57243

#### Describe the solution

A helluva lot of manual data entry to replace manually specified encumbrance values for helmets. Currently, this PR only targets everything in hats.json, hoods.json, helmets.json, and some of the helmets in custom_headgear.json. This definitely misses some helmets somewhere, notably I couldn't find the EOD helmet.

Also includes an extra upper bound in bodyparts.json for the weight-encumbrance array to fix an error that gave helmets that were too heavy randomized 10-digit encumbrance values (as fun as a 528497163 encumbrance kettle helmet was).

#### Describe alternatives you've considered

Making someone else do all the work.

#### Testing

There are two bugs I've noticed so far that I can't fix. For one, VARSIZE is handled incorrectly making VARSIZE headgear with encumbrance higher than 10 end up with inflated encumbrance values.

The second bug vexes me, but some helmets have around 2-5 less encumbrance than they should, but I've found no consistent reason why. Some examples are the leather armor helmet (which goes to -2 encumbrance, -1 when I tested after removing VARSIZE), the baseball helmet, and the hooded hard hat. I tried checking if it was caused by VARSIZE or PADDED flags but that was a dead end. The most vexing of them is the hooded hard hat; it is equal in every way to the non-hooded hard hat in the JSON with the only different being it weighs about 80 grams more, but for some reason in-game it has 6 encumbrance while the regular hard hat has 8 with these changes in place, so I don't think this error is on the JSON end. It seems to be random and only affects a minority of headgear.

Otherwise, the game runs fine without exploding into a fireball and the encumbrance for the majority of headgear is correct.

EDIT: Bugs fixed thanks to Slacks!

#### Additional context

Balance-wise this mostly leads to a lot of lowered encumbrances, particularly on light helmets like the bike helmet or baseball helmet, but especially on casual headwear. Examples being the sombrero going from 20 to 3, a baseball hat going from 15 to 2, etc.

### CODE REVIEW

**Comment by Termineitor244** [comment]
The EOD helmet is on the tool_armor.json file (outside of the armors folder, on the items folder). There are untouched hats/helmets/hoods on the cuttingroom.json file (inside the bespoke_armor folder), the power_armor file.json, the obsolete.json file (Which I guess would be fine to be left alone, its on the items folder) and the tool_armor.json file (appart from the EOD helmet).

There some other files with items that cover the head (along with other body parts), like the cloaks and some bodysuits/mutations armor, but I'm not sure what is the plan with them.

Good work as always!

**Comment by Aerin-of-the-Toast** [comment]
> The EOD helmet is on the tool_armor.json file (outside of the armors folder, on the items folder). There are untouched hats/helmets/hoods on the cuttingroom.json file (inside the bespoke_armor folder), the power_armor.json file, the obsolete.json file (Which I guess would be fine to be left alone, its on the items folder) and the tool_armor.json file (appart from the EOD helmet).
> 
> There some other files with items that cover the head (along with other body parts), like the cloaks and some bodysuits/mutations armor, but I'm not sure what is the plan with them.
> 
> Good work as always!
> 
> Edit: Oh, the tiaras cover only the head too, in the jewelry.json file.
> 
> Edit2: There are 2 scarfs (on the scarfs.json file) that cover only the head too.
> 
> Edit3: wetsuit_hood on the swimming.json file and the harmonica_holder on the tool/musical_instruments.json file cover only the head too, the harmonica I think its wrong, since it should be belted around the neck/torso I think, rather than the head, but well, those should be all the base game items/files with items that cover only the head.

Any special sci-fi headgear like exodii stuff or power armor is possibly best left to manual encumbrance values due to being special exceptions, but thanks for letting me know about tool_armor and tiaras, that'll help later (but for now, if I have to look at a JSON file for another minute I'm going to eat a hard hat :P). I also don't think I'll bother with cuttlingroom.json cuz, well, by its nature stuff in there likely won't stick around forever.

**Comment by Termineitor244** [comment]
> Any special sci-fi headgear like exodii stuff or power armor is possibly best left to manual encumbrance values due to being special exceptions, but thanks for letting me know about tool_armor and tiaras, that'll help later (but for now, if I have to look at a JSON file for another minute I'm going to eat a hard hat :P). I also don't think I'll bother with cuttlingroom.json cuz, well, by its nature stuff in there likely won't stick around forever.

Haha I know that feeling, its best to leave it for later then, that's what I do!

**Comment by bombasticSlacks** [comment]
Hey so I'm working through the reported bugs now the hard hats are just correct 😆 
hard hat is 800 grams so exactly 8 encumbrance

the other one is 880 grams:
between 800 g : 8 enc and 1300 g: 20 enc

so 500 grams between 1300 and 800. 80 grams is 16% of that distance. So is should be 16% of the way on encumbrance:
12 encumbrance in the difference, 12 * .16 = 1.92
so 8 + 1.92 (rounded) = 10 which is the new correct value for the hooded hard hat.

**Comment by bombasticSlacks** [comment]
I realize what I said above is gibberish so this is a graph of it https://www.wolframalpha.com/input?i=+line+%7C+points+%28800%2C+8%29+%7C+%281300%2C+20%29+%7C+Cartesian+equation+

**Pull request merged**
