### PR TITLE
Bulk items: food

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds bulk items for food."```

#### Purpose of change
Item spawning in the early game is unrealistically low. Given that the cataclysm happened 5 days ago, and most of those 5 days were sheer violence, there cannot have been true widespread looting: there just wasn't time for it. While people may have had time to stock up on groceries and empty the supermarkets, most other types of store would be fine. Nobody would have had a chance to make a run on lumber in preparation for total societal collapse.

Further, all the food items that would have been looted would have made their way to peoples' basements and stockpiles, and then been abandoned when the person piling the resources died. Houses should be full of bottled water and canned goods purchased or looted at the end of days (or before). The people who would have used them died before they could be used.

#### Describe the solution
This will have a pretty profound effect on game balance. This is meant to change as we implement NPC looting, which will make it so that towns are rich in supplies at the beginning of the game but slowly get picked over.

Addresses part of the lack of item spawns in the game by creating bulk items, which can be disassembled to yield a container (cardboard box or plastic bag or similar) and a large number of items contained inside.

At the moment I have been pretty general with the size and weight of the 12 and 8 packs added. I might need to get a bit more granular to suit the size of these cans in game.

This PR adds the following:
 - "multipack_beans", 12 pack
 - "multipack_broth", 12 pack
 - "multipack_chicken", 8 pack
 - "multipack_chili", 12 pack
 - "multipack_chowder", 12 pack
 - "multipack_clams", 12 pack
 - "multipack_can_cheese", 8 pack
 - "multipack_coconut", 12-pack
 - "multipack_con_milk", 8 pack
 - "multipack_corn", 12 pack
 - "multipack_curry_veggy", 12-pack
 - "multipack_curry_meat", 12-pack
 -  "multipack_herring", 8 pack
 - "multipack_lasagna", 6 pack
 - "multipack_macaroni", 6 pack
 - "multipack_noodles_fast", 24 pack
 - "multipack_peach", 12 pack
 - "multipack_pineapple", 12 pack
 - "multipack_pork_beans", 12 pack
 - "multipack_ravioli", 12 pack
 - "multipack_salmon", 8 pack
 - "multipack_sardines", 8 pack
 - "multipack_sauce_red", 12-pack
 - "multipack_sauce_pesto", 12-pack
 - "multipack_soup_meat", 12-pack
 - "multipack_soup_chicken", 12-pack
 - "multipack_soup_mushroom", 12-pack
 - "multipack_soup_tomato", 12-pack
 - "multipack_soup_dumplings", 12-pack
 - "multipack_soup_veggy", 12 pack
 - "multipack_spaghetti", 6 pack
 - "multipack_spam", 8 pack
 - "multipack_tomato", 12 pack
 - "multipack_tuna", 8 pack
 - "multipack_water", 12 pack
 - "multipack_water_mineral", 12-pack
To add:
Canning jars (empty)

Please let me know if I've missed any major canned foods in the game.

#### Describe alternatives you've considered
It doesn't add that much to put these in boxes, I could instead just bump spawns of cans... but if you ask Dino Dave, those cardboard boxes are important! Further it adds a little bit of immersion, I think.

#### Additional context
Similar content packs to add
- building supplies
- "entertainment" foods - alcohol, junk food, and things (separate PR, same idea. And then we could have six pack rings in game, just what everyone wants)
- ammo?

#### Stages
- [x] Add items
- [x] Add deconstruction recipes
- [x] Add to itemgroups
- [ ] Check spawning in game
- [ ] Check to see if recipe inheritance is okay or if I need to use nutritional overrides

### CODE REVIEW

**Comment by Shodan14** [comment]
I hope the amounts per package get fixed along with it. There's still the infamous 1 macaron box.

**Comment by KorGgenT** [comment]
> I hope the amounts per package get fixed along with it. There's still the infamous 1 portion macaroni box.

that's a separate issue

**Comment by I-am-Erk** [comment]
>I hope the amounts per package get fixed along with it. There's still the infamous 1 portion macaroni box.

Not fixing that, but I will probably be adding giant boxes with multiple macaroni boxes

**Comment by Shodan14** [comment]
> 
> 
> > I hope the amounts per package get fixed along with it. There's still the infamous 1 portion macaroni box.
> 
> Not fixing that, but I will probably be adding giant boxes with multiple macaroni boxes
Praise be!

**Comment by Ilysen** [comment]
I hate this solely because I'm an instinctual hoarder and this shall multiply my problem tenfold. Curse you, Erk!

**Comment by Throwaway-name** [comment]
Here's multipack_broth converted into an item_group:

```
      {
        "collection": [
          { "item": "box_small" },
          { "item": "bag_plastic" },
          { "item": "broth", "container-item": "can_food", "count": 12 }
        ]
      }
```

**Comment by I-am-Erk** [comment]
> I hate this solely because I'm an instinctual hoarder and this shall multiply my problem tenfold. Curse you, Erk!

I'm targeting you and people like you. Soon you won't be able to loot an entire house into the back of your compact car.

**Comment by Shodan14** [comment]
> I'm targeting you and people like you. Soon you won't be able to loot an entire house into the back of your compact car.
-"Your engine is not powerful enough to move the frame"

**Comment by Ilysen** [comment]
Not if I have any say in it. I'll just make the car bigger and bigger.

**Comment by Rivet-the-Zombie** [comment]
Idea for a future PR: twelve-packs of soda and beer.

**Comment by I-am-Erk** [comment]
Yeah, six packs of pop are upcoming. Right now I need to pester a coder to make it possible to disassemble items into containers automatically.

**Comment by dissociativity** [comment]
Come to think of it, why don't cars spawn with food and drinks stockpiled at least sometimes?
You'd think people escaping early would bring supplies they'd either looted or grabbed from home.

This would also make it make sense for it to spawn less often in shops

**Comment by Ilysen** [comment]
Sorry for resurrecting this PR, but might I ask why it was closed? It seems like a really good change.

**Comment by I-am-Erk** [comment]
I just closed it for the moment, it needs some code support and I didn't have time to get a coder to help me finish it. Currently you can't disassemble an item into a container, so you can't produce tins of beans... Just beans and empty tins.

**Pull request closed without merging**
