### PR TITLE
Allow mounting leather and makeshift funnels on a vehicle

### PR DESCRIPTION
**Pull request by Rail-Runner**
Allow attaching leather and makeshift funnels to a vehicle. As a bonus, they are foldable, though I'm not sure if foldable liquid containers for vehicles exist.

### CODE REVIEW

**Comment by mugling** [comment]
Why not the inverse and just allow mounting of metal funnels. Gives the latter more reason to exist?

**Comment by Darkyhard** [comment]
> Why not the inverse and just allow mounting of metal funnels.

They can already be mounted.

**Comment by mugling** [comment]
Yes, as in removing that ability and going with just metal (and/or the regular type).

**Comment by Darkyhard** [comment]
> Yes, as in removing that ability and going with just metal (and/or the regular type).

Does anything prevent you from attaching a small funnel on your vehicle?

**Comment by Coolthulhu** [comment]
I tested them and they were incredibly underwhelming - 6 hours of thunderstorm wasn't enough to gain a single charge of water from 6 makeshift funnels.
Those two will need a major buff before it becomes sensible to allow mounting them on a vehicle.

**Comment by Darkyhard** [comment]
> Those two will need a major buff before it becomes sensible to allow mounting them on a vehicle.

Would 200 radius be enough for them?

**Comment by Coolthulhu** [comment]
200 radius would be OK, I think. It would give them 4/9 of the power of a regular funnel.
But change that screwdriving to nailing. Installing a funnel is more than just putting it there. It should actually require a rubber hose per funnel (to connect it to the tank), but we don't have support for multi-components parts yet. At least nailing suggests some modifications and costs something.

**Pull request merged**
