### PR TITLE
Suspend inventory overflow checks during player activity

### LINKED ISSUE #15079: Reload from ground fails when insufficient inventory space
`game::reload` is bugged when the inventory is too full to temporarily contain the item.

To reproduce:

- Spawn STANAG magazine and drop it
- Ensure you have no free inventory space and empty hands
- Spawn AR-15 and wield it
- Try to reload using STANAG magazine from ground

Sequence of events is:

- Item is picked up by `item_location::obtain` and placed in inventory
- `player::assign_activity` is called to start reloading using the item
- `Character::process_turn` calls `drop_inventory_overflow`
-  Activity fails with debugmsg *"Tried to get an item from a character who doesn't have it"*

Possible solutions:

* Require sufficient space when calling `item_location::obtain` (trivial)
* Mark item as `job item` and exclude it from inventory volume calculations until activity completes
* Rework activity handlers to use `item_location` (difficult)
* **... any others?**

### PR DESCRIPTION
**Pull request by mugling**
Fixes #15079

### CODE REVIEW

**Comment by chaosvolt** [comment]
This would also allow the logical "reload gun that already has a mag" suggestion I proposed to go without a hitch.

**Comment by chaosvolt** [comment]
o.O

**Comment by mugling** [comment]
Accidental closure

**Comment by kevingranade** [comment]
I intentionally rebased this change back out, as discussed in #15079, this is too wide a change.

**Comment by Rivet-the-Zombie** [comment]
Ah, I hadn't read #15079. Sorry about that!

**Pull request merged**
