### PR TITLE
added batch time saving of 80% from 2 units for all nuts based recipes

### PR DESCRIPTION
**Pull request by 8ctopus**
#### Summary

```SUMMARY: Content "added batch time saving of 80% from 2 units for all nuts based recipes"```

#### Purpose of change

IRL cooking/roasting nuts in batch would give significant time saving. In game, most nuts take too much time to cook/roast. The purpose of this commit is to introduce 80% time saving from 2 units.

#### Describe the solution

Added batch saving 80% from 2 units.

#### Testing

Tested in game on pine nuts only.

### CODE REVIEW

**Comment by Mecares** [comment]
I agree that time should be saved when cooking and roasting but saving that much time when using a quern seems odd to me.

**Comment by 8ctopus** [comment]
@Mecares you are right, I'll make some adjustments.

**Comment by 8ctopus** [comment]
I've made the following changes:

- 50% speed gain > 1 unit for all recipes requiring a mortar and pestle / quern.
- 80% speed gain > 1 unit for all recipes that just require cooking.

**Comment by I-am-Erk** [comment]
There really isn't a great batch speed gain with pestles especially. I'd put that down a little further, maybe 30?

**Comment by 8ctopus** [comment]
@I-am-Erk Thank you, I did as you suggested.

**Pull request merged**
