### PR TITLE
Adjustments to Blade Trap recipe components

### PR DESCRIPTION
**Pull request by Mecares**
Adds an small storage battery to the recipe so that the electric motor has not to run on thin air, also adds 4 pointy sticks to attach the tripwire to.

### CODE REVIEW

**Comment by pisskop** [comment]
4?

And couldn't you get away with splintered wood to simulate a stake?  pointy sticks are large enough to use as a spear, thats not small and subtle.

**Comment by Mecares** [comment]
Yes four because they are in each corner around the trap and overall this trap does not seem to be very subtle.

**Comment by Zilenan91** [comment]
Does it really need to be any harder to make though? I've never had a reason to make one of these and I certainly won't after this because of the variety of resources I'll need.

**Comment by pisskop** [comment]
tbf I dont use any traps.  Caltrops or nailbords on rare occasion.

Traps are better for woodsy starts or people, those who dont have access to hulking deathmoibles to run things over in or automatic shotguns to sweep streets with

**Comment by mugling** [comment]
Appears stalled

**Pull request closed without merging**
