### PR TITLE
Fixing mi-go slaver beam

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Fixing mi-go slaver beam. It is more immediate hotfix.

#### Summary

SUMMARY: Bugfixes "Fixing mi-go slaver beam"

#### Purpose of change

Player reports that mi-go's slaver cripples them instantly and leaves vulnarable for attacks without chanse to fight back. Thit PR fixes that.

#### Describe the solution

* Fixed spelling error in daze duration. Looks like it was 10 times higher then planned so before change  likely it wears off after you death.
* Significaclty reduced pain effect and stamina lowering effect. 
* Increased cooldown of the mi-go slaver beam. x10 for slaver mi-go. x5 fo others. Mi-go uses beam one in each 100 turns (or 100 seconds)
You will likely be hit with beam only once in combat. But it is still may end up badly  for you in non ideal condition.

Examples for mi-go slaver (other mi-go's  beam somewhat less dangerous)
Before:
screenshot 2019-09-04 001

After (with dazed effect):
screenshot 2019-09-06 001_af1

After (after dazed effect wears off):
screenshot 2019-09-06 001_af2

As you can see now you can fight back.

#### Additional context

Solution is non ideal. I've nerfed spell noticable. But it is hard to balance it in that state.
Mi-go' slaver beam as werid non missing spell shoud be revisited completely. Or removed.
I  still have no idea how player supposed fight multiple mi-gos with that beam. Even in nerfed state.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

**Comment by LaVeyanFiend** [comment]
Jenkins doesn't exist anymore 😛

**Comment by Firestorm01X2** [comment]
I've removed stamina lowering effect for mi-go slaver beam. I expect it hard to balance vs multiple mi-gos. Other effects still intact.

**Comment by Firestorm01X2** [comment]
> 
> 
> Go ahead and cut the stamina damage to 10% of it's current level, but removing it isn't an option.

Likely I will havo to nerf stamina_damage this way. Or do werid thing by setting
{ "id": "stamina_damage", "max_level": 0 }
Surpsingly it is works, but looks like hack.

So probably I'll just edit stamina cutting spell itself.

**Comment by KorGgenT** [comment]
the stamina damage spell was made for the slaver beam, so it's ok to adjust it.

**Comment by Firestorm01X2** [comment]
> 
> 
> the stamina damage spell was made for the slaver beam, so it's ok to adjust it.

In fact it was not
Cataclysm-DDA\data\mods\Magiclysm\Spells\item_only.json
```
{
    "id": "twisted_restore",
    "type": "SPELL",
    "name": "Twisted Restoration",
```

Sy I will go for special spell effects

**Comment by Firestorm01X2** [comment]
@kevingranade 
> Go ahead and cut the stamina damage to 10% of it's current level, but removing it isn't an option.

Ready. Damage to stamina ended up higher than 10% to be more noticeable. But not 50 as it was in first attempt.

Additonally I've ipmpelement separate spells for mi-go beam to make it separate from magic mods and provie easier future tweaking.

Screenshots updated.

**Comment by KorGgenT** [comment]
if you're going to make a new spell in order to adjust it, would you please move the other one to the magiclysm mod?

**Comment by Firestorm01X2** [comment]
Spell infastructure rework probably should be done outside current PR. I ' ve created new spells only to avoid conflicts with existing mods.

**Comment by Firestorm01X2** [comment]
Ready. Still some further rebalnacing may be required.

**Comment by Night-Pryanik** [comment]
While I appreciate this work for balancing, I think proper solution would be removing the use of unavoidable and armor-ignoring mumbo-jumbo "spell beam" altogether and replacing it with something more sensible, more "solid", like a laser ray or a projectile.
What is this beam, after all? Psionics? Psionics is forbidden in vanilla. If not psionics, then what powers it? What fuel does it use? There's too much questions and balance issues for leaving it for something abstract.

**Comment by kevingranade** [comment]
It's intentionally not specified, and that's ok when you're talking about literally alien technology.
We don't specify how zombies are animated, we don't specify mi-go metabolism, we don't specify all kinds of things.  They work the way they work.

When something is a conventional technology or close to one, it should act the way we understand such things to work, but when it's a completely alien technology, we don't have to try to come up with a rationale, it's alien.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/request-to-developers/22170/1

**Pull request merged**
