### PR TITLE
[WIP] AIM Addition (again!)

### PR DESCRIPTION
**Pull request by DavidKeaton**
Hello again! This is an update to AIM, that allows you to pickup items on the ground and vehicle tiles.
I marked as [WIP] as it is still being fixed/implemented, but it's not as scary as [WIP] implies. :-)

Features:
- Allows one to switch between ground or vehicle storage in the AIM menu, and allow you to transfer from/to ground from/to vehicle storage, even if on the same tile.
- Minor UI adjustments to give visual indications you are picking up from ground/vehicle.
- Updates to minimap with new symbols to show where you are getting items from.
- Minor tweaks to UI to make colors easier to distinguish relative to other colors in UI.

Just as a note, a lot of this is broken at the moment. ;-)

That's it this time!
-Davek

### CODE REVIEW

**Comment by tivec** [comment]
I can't thank you enough for this patch. I have already been using the minimap, and now this will really help me when moving stuff around in my base. I'll be fetching this PR for testing later today :)

**Comment by DavidKeaton** [comment]
@tivec yeah man! improvements I have been meaning to do, but that bags PR sorta stole my soul for a bit. :-P

**Comment by sparr** [comment]
while you're in there, improving [,] to work from [A]rea would be nice. that's next on my to-do list for the AIM, if you don't want to.

**Comment by Coolthulhu** [comment]
Don't remove the `veh == nullptr` - it is clearer when it is explicitly compared with nullptr rather than being implicitly cast to bool.

**Comment by BevapDin** [comment]
> Don't remove the  veh == nullptr  - it is clearer when it is explicitly compared with nullptr rather than being implicitly cast to bool.

+1. Actually: +INF.

**Comment by DavidKeaton** [comment]
@Coolthulhu @BevapDin duly noted :)

@sparr what do you mean mate?

**Comment by sparr** [comment]
@DavidKeaton #11721

I'm going to do it if you don't, but since you're already in there, I thought I'd pitch the idea in case you can roll it in easily.

**Comment by DavidKeaton** [comment]
@sparr I'll take a look into it mate.

**Comment by kevingranade** [comment]
One wrinkle here is the ground under a vehicle is inaccessible unless it's
adjacent to the edge of the vehicle, e.g. is it reasonable to reach through
a floorboard to grab something? (Hint, no)
Not sure if this runs into that issue, if not disregard :)

**Comment by sparr** [comment]
I don't know how the edge of the vehicle is defined, but I'm able to pick up items from the ground in the center tile of my 3x5 vehicle, without this patch.

**Comment by DavidKeaton** [comment]
Redoing this from a new branch, wanted a fresh take.

**Comment by KA101** [comment]
Closing based on the fresh-branch note.  Let us know if you want it reopened.

**Comment by DavidKeaton** [comment]
Will do my man. :-) Working on it as we speak.

**Comment by DavidKeaton** [comment]
Now see #11926

**Pull request closed without merging**
