### PR TITLE
Add folding knife item.

### PR DESCRIPTION
**Pull request by Noctifer-de-Mortem**
P.S: "child_items" and "school" are being intentionally passed over as it seems less likely that schoolkids would be carrying around full-on folding knives compared to the slip-joint knives already in the itemgroups.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
It has bashing damage, but not cutting damage.

**Comment by illi-kun** [comment]
No cutting damage and no explicit ```to_hit``` calc are blockers for this PR.

**Comment by illi-kun** [comment]
As a general comment, I don't think this item gives something new to the game (due to minor distinction with named ```pocket knife```.

**Comment by kevingranade** [comment]
They're quite different irl, so I definitely think there's a niche for them.
A folding pocket knife aka penknife is significantly more portable (half the size or less) of a folding knife like this.
The blade on a penknife doesn't generally lock open, and is fairly flimsy. The larger folding knife has a tougher and higher quality blade that locks open.
The penknife has an almost unusably small handle, and it's not at all ergonomic, the folding knife has an adequate handle.

In game, making The penknife even more portable is impossible since its already minimum size, folding knife is probably volume .5, and the pocket knife is more like .1, but they both round up to 1.
Similarly pocket knife and folding knife already have cut 1, though we could certainly give pocket knife something even worse than butcher 12.
To hit and damage of folding knife should be better, that might just be by a point or two, but that's fairly significant if you have nothing else.

So, 1-2 higher to-hit and damage, better butchering (even if it means making the pocket knife worse).
I'm tempted to say we should take cut 1 away from the pocket knife, it's seriously not ok for a lot of the things it gets used for, and I strongly suspect if you used it for half the things it gets used for IRL it would break.  That's probably too extensive to ask for here though.

Especially if we nerf butchering on the pocket knife, some professions could get upgrades to folding knife.

**Comment by illi-kun** [comment]
Any progress with this PR, @Noctifer-de-Mortem?

**Comment by illi-kun** [comment]
Closing due to inactivity to shorten the mergeline. Feel free to implement a new item per Kevin's description above.

**Pull request closed without merging**
