### PR TITLE
Add Emus

### PR DESCRIPTION
**Pull request by TheSaddestGoomba**
#### Summary
Content "Adds Emus and Emu Chicks as farm animals"

#### Purpose of change
Emus are an uncommon, though far from rare, sight on farms all across the USA. New England is no different.
They are not yet in the game, this adds them, their chicks, and eggs.

#### Describe the solution
Create 2 new monsters, Emu and Emu Chick.
Add them to appropriate monster groups to spawn on farms.
Create new Emu Egg item and setup the life cycle for all three objects.
Make Emu Eggs functional for existing egg recipes.

#### Describe alternatives you've considered
Adding a new weakpoint set, adding zombie emus; both will be a future PR.
Include new farm map(s) for an Emu Farm, better as a separate PR.
Include a process for extracting oil, maybe in the future.

#### Testing
None yet, still need to handle the egg item, and all the relevant group and list objects.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
The [2022 census of agriculture](https://www.nass.usda.gov/Publications/AgCensus/2022/Full_Report/Volume_1,_Chapter_1_US/usv1.pdf)(Table 30) reports 1,566 farms with 12,580 Emus in the country.

[Massachusetts](https://www.nass.usda.gov/Publications/AgCensus/2022/Full_Report/Volume_1,_Chapter_1_State_Level/Massachusetts/mav1.pdf) lists a mere 8 farms and 15 animals. [New York](https://www.nass.usda.gov/Publications/AgCensus/2022/Full_Report/Volume_1,_Chapter_1_State_Level/New_York/nyv1.pdf), which I expect to have the most, has only 47 farms and 145 animals.

I don't think there's any reasonable occurrence for an Emu farm to spawn.

**Comment by Karol1223** [comment]
As much as I love Emus this is far too niche of an addition to make it in, in my eyes

**Comment by TheSaddestGoomba** [comment]
This PR only intends to add them as a low weight spawn to GROUP_DOMESTIC and GROUP_SAFE. So, spawning in 1's (maybe 2's) on farms and in barns. I planned to set the weight similar to the existing llama (which is weighted twice as high as a goat?) to represent the small farms and homesteads that have one or a pair.

This would **not** add a dedicated emu farm. I was considering that as a map unique for a future PR but wow, their numbers really dropped off recently.

Thank you for the sources. I wasn't aware quite how low the emu numbers had gone in the US. Another source I found said an overall 75% reduction in the country over the last ten years.

**Comment by GuardianDll** [comment]
I'd recommend to consult, and if agreed, make it globally unique spawn for a single map

**Comment by Karol1223** [comment]
It *might* pass as a globally unique map location. And, for the record, if the llamas were being added now I'd have the exact same feelings about them. Unfortunately that ship is already sailed, and I am not bothered enough to make a unique llama farm myself.

**Comment by Maleclypse** [comment]
You could make one of the zoo enclosures have a chance to be emu's instead and I'd say a globally unique emu farm is possible if not likely but definitely not just a random assortment of emus in various farms and barns.

**Comment by kevingranade** [comment]
You need to understand the census data is saying there are literally 15 emus on farms in the state.
A farm is any business that sells $1,000 of agricultural products a year, tiny homesteads would be included.
With expected attrition from the cataclysm we would expect maybe one surviving emu in the entire state.
That is absolutely not worth adding.

**Pull request closed without merging**
