### PR TITLE
Added (vehicle equivalent of) home appliances recipes

### PR DESCRIPTION
**Pull request by FulcrumA**
#### Summary
SUMMARY: Content "Added (vehicle equivalent of) home appliances recipes"

#### Purpose of change
I promised to PR a recipe for a freezer. While at it, I've decided other moderately-complicated but theoretically buildable home appliances, like a fridge and a washing machine could also be introduced.

#### Describe the solution
Recipes for a freezer, fridge and washing machine were added.

#### Describe alternatives you've considered
I've considered some sort of coolant for the sake of fridge and the freezer but then again, we already have such devices without any coolant and while such could be quite beneficial and worth consideration, I didn't want this PR to grow into whole remake of such appliances, adding not only recipes but whole new gas/liquid and other components.

A thought to make separate, noticeably hand-made devices merely similar in function to the ones one would scavenge was entertained. However, looking at the descriptions, the devices already in game are generic and vague enough that a skilled craftsman could likely make similar given time, skill and resources.

Initially, I wanted to include a dashboard, interchangeable with electronics control as components of the appliances but ultimately decided against, as one still requires such parts to be installed separately in the vehicle to interact with said appliances.

#### Additional context
Bits and pieces one could acquire from smashing similar furniture (like fridges in the building) were taken into account when considering potential components, then the size difference of various appliances. To underline moderate complexity, the devices have considerable, but not very high skill requirements. This way also current way of acquiring such - scavenging - is still viable.

Washing machine provides a handful of scrap back, despite using smaller amount of it in the construction. It's a little flavor detail meant to simulate how the tank is being partially filed and cut down to size for the device, leaving leftover pieces.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Hour and a half to construct minifreezer from a scratch? Is it plausible?

**Comment by FulcrumA** [comment]
@Night-Pryanik 
Good point. The values are a bit weird when I look at recipe file in general but I think we can safely assume that it should take more like several hours per device. Will adjust in a minute.

**Comment by FulcrumA** [comment]
@kevingranade 
Alright, what item in existing devices as already in game should I add to the recipes in this PR? It seems that if the coolant is a hard requirement, it'll have to be tracked, in which case current disassembly of furniture will need to provide tanks of the new liquid before I could add said liquid/tank as crafting requirement, correct? 

Should the scope of this PR be expanded with such cooling devices remodelling and if so, are there any particular refrigerant limitations? I can see an issue with handling of such liquid, as unusual properties of many of such blends make them usually hard to transfer between tanks and whanot thus requiring special rules in mechanics, unless you'd be fine with creating a dummy item a'la 'hermetically sealed tank of refrigerant'.

**Comment by kevingranade** [comment]
> It seems that if the coolant is a hard requirement, it'll have to be tracked, in which case current disassembly of furniture will need to provide tanks of the new liquid before I could add said liquid/tank as crafting requirement, correct?

Yep

> Should the scope of this PR be expanded with such cooling devices remodelling and if so, are there any particular refrigerant limitations?

They need a dedicated tank and a way to harvest refrigerant from existing devices.

> maybe we could even use some sort of vague 'refrigerant cells' given somewhat futuristic setting

No.

**Comment by FulcrumA** [comment]
@kevingranade 
Since I edited and expanded the post when you were answering - regarding the cells, it wouldn't be pure sci-fi. I am talking about the stuff like thermoelectric cooling using Peltier cells etc, which is something that is done IRL. Would making the freezers/fridges thermoelectric in nature be somehow bad?

**Comment by kevingranade** [comment]
> thermoelectric cooling using Peltier cells etc, which is something that is done IRL.

There's peltier cooling, there’s acoustic coupling cooling, there's laser refrigeration.  These all have one thing in common, they're less efficient and less craftable than a compression cycle based refrigeration system.

So no, it's not ok to ignore physical realities to make it easier to craft things.

**Comment by FulcrumA** [comment]
>So no, it's not ok to ignore physical realities to make it easier to craft things.

No on does. Refigeration on the basis of the Peltier cells doesn't seem more complicated than many devices a survivor can already make. But sure, since you seem adamant about it and it is some sort of way of doing it, I will check various refrigeration blends and then introduce something on their basis in the game that will be relatively reasonably transferrable, probably also adding small tanks to the components.

I assume it'd be good if I'd also change furniture fridges to include new refrigerant?

**Comment by HotSake** [comment]
Might I recommend anhydrous ammonia as a refrigerant? It's commonly used in industrial cooling, mostly because it's slightly more efficient than household refrigerants, and leaks can be detected rapidly due to the strong odor. It's been in use for over a hundred years, so it's more on the level of something a survivor could craft. It would be craftable using a chemistry set and household ammonia commonly found in-game, because it's basically just pure ammonia (anhydrous = without water). Household ammonia is about 10% ammonia by weight, with the rest being water that we can assume is boiled off and lost in the process. This would put the requirements to acquire refrigerant at a chemistry set, chemistry text for recipe, low-to-mid cooking (comparable to other chemical recipes like concentrating acid) and a reasonably large amount of household ammonia (requiring scavenging, AKA gameplay).

It's not chemically compatible with copper tubing, so it wouldn't normally be the stuff found in household refrigerators, but I think we can safely ignore that inconvenient fact. After all, acid can be stored in just about anything, we're not interested in the difference between LDPE and HDPE plastics, and more sophisticated chemical interactions are basically outside the scope of the game. I like the fact that it can be crafted from precursor chemicals already found in-game. Real-world appliances use HFCs which are much more complex, and I don't think they're feasible to craft by a survivor.

**Comment by FulcrumA** [comment]
To be honest, crafting of the refrigerant is of secondary importance for me. I'd be perfectly fine with all of it coming from scavenged appliances. It shouldn't be running out as an ingredient so it shouldn't be an issue either and possibly could be even done as a mock item rather than actual liquid (though it could work as aliquid as well).

The gretest importance is whether it could be stored in average small 2L tank and siphoned/transferred between other containers for liquid without too much hassle (or at least not more than current acids etc cause).

**Comment by FulcrumA** [comment]
This PR was stuck in a limbo for quite some time and in the meantime, @KorGgenT created something nice himself at #27082 about fridges/freezers that should be more up to taste of some. After some talk he agreed to migrate washing machines as well which makes this PR obsolete. Thus, closing.

**Pull request closed without merging**
