### PR TITLE
Unarmed crafting organization

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Interface "Creates a new subcategory for unarmed weapons crafting"

#### Purpose of change
One comment of #61682 reminded me that unarmed weapons (armor) do not have their own subcategory for ease of finding, most are in the bashing department, one is in stabbing and another one is all the way until armor/hands...

So, if you want to craft a weapon (armor) for unarmed combat, you have to search among different crafting lists and read the descriptions to try and guess which weapon is an unarmed weapon or not.

#### Describe the solution
A new crafting subcategory for weapons, "UNARMED" where you can find all kinds of knuckles, the cestus, the studded gloves and any future unarmed weapon/armor that could be added.

#### Describe alternatives you've considered
To make it a new subcategory of armor crafting, but these things will be searched as weapons first.

#### Testing
Started the game, opened the crafting menu, the items are under a new header; "unarmed".

#### Additional context
imagen

### CODE REVIEW

**Comment by Dan1ss1mo** [comment]
i think adding sabatons, demi gauntlets and mittenn gauntlets here would also be reasonable, can item be in 2 categories at the same time though?

**Comment by Termineitor244** [comment]
A good idea, but as you say I don't think its possible to add a recipe to 2 categories, I will try when I arrive at home, but if not then this would probably need some c++ changes to work.

**Review by bombasticSlacks — CHANGES_REQUESTED** [review]
Can this PR be rearranged to not move the items to new files? It makes it harder to track the GIT history.

**Comment by Termineitor244** [comment]
Of course! I considered a petition like this when making the PR so I just have to revert the last commit, which only created and moved the items to the new file.

I will do it when I arrive at home after work today.

**Comment by AcidAntOnAMinefield** [comment]
Absolutely legendary PR. Thank you!

**Pull request merged**
