### PR TITLE
Updates survivor utility belt to include screwdriver iuse action.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**

### CODE REVIEW

**Comment by DavidKeaton** [comment]
another thing to add, you always can make the tool belt, but not the survivors belt. perhaps they should be unlocked by the same level/book?

**Comment by Rivet-the-Zombie** [comment]
I think that one was changed because it makes sense to require specific skills to make the belt itself, but it shouldn't really require any skills to figure out how to put tools in it once you actually have the belt on hand.

**Comment by DavidKeaton** [comment]
I guess I can see that.

**Comment by kevingranade** [comment]
Coolthulu's thingy superseded this one.

**Pull request closed without merging**
