### PR TITLE
Add graded explosion display to tiles

### PR DESCRIPTION
**Pull request by Coolthulhu**
Explosion strength now also displayed in tiles. 3 possible strength values, like in console display (red/yellow/white).

The problem is, no tileset has the new tiles. Is there any fallback option for missing tiles or should I just let them look weird until tileset authors fix it?

Also, it would be nice if I could add explosion sections with 0, 1 and 4 neighbors. Is any fallback possible here?

I'm looking for a function that checks if the current tileset has tile with a given name and a second one to check if it also has a subtile of a given value. Or just a way to make it automatically substitute the missing tile/subtile with appropriate equivalent that exists.

EDIT: Also, made it not draw over unpassable tiles, because players found it confusing.

### CODE REVIEW

**Comment by Zireael07** [comment]
Great!

There is a fallback code but all it does is show the 'missing tile' tile if the tileset has it.

**Comment by kevingranade** [comment]
We don't have that information in the tile creation docs?  If not that's
its own problem :/

**Comment by Coolthulhu** [comment]
I may have been searching in the wrong place, but I couldn't find the docs for tiles. At least not with an obvious name, like docs/TILES.md.

**Comment by Coolthulhu** [comment]
I'll mark it as non-WiP, because I have no idea of how to fix that without help from tileset makers or a big upgrade to tileset system to allow fallbacks, and because it's not all THAT critical.
Until new explosions are added, tiles for them probably won't be created.

The fallback tiles are usually smaller than the explosion ones, so it will look more or less OK, with only the strong tiles looking dangerous.

**Comment by chaosvolt** [comment]
What the...AUGH. Is this the cause of https://github.com/CleverRaven/Cataclysm-DDA/issues/13250 then?

Nice. I went and gave everyone on the forum ample warning about https://github.com/CleverRaven/Cataclysm-DDA/pull/13151 but no one thinks to warn us about this? >_>

**Pull request merged**
