### PR TITLE
Fix some Innawood missions

### LINKED ISSUE #59367: [Innawoods] New missions can't be completed
### Describe the bug

Modded missions for Innawoods won't spawn labeled item

### Steps to reproduce

1. Get into Innawoods world
2. Spawn NPCs and acquire MGOAL_FIND_ANY_ITEM mission (relic, stick, etc)
3.  There is no way to get the required item

### Expected behavior

Spawn the tagged item at the start of the mission, making it completable

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-9961-gb96015a73a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

Currently, all MGOAL_FIND_ANY_ITEM are related to terminals and I couldn't find any code related  to automatically spawn items with the mission_id value.
Changes were merged in #59263

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Mods "Fix some broken Innawood missions"

#### Purpose of change
Fixes #59367
Some innawood missions required you to fetch items that were tagged. These tagged items did not spawn.

#### Describe the solution
Replaced `MGOAL_FIND_ANY_ITEM` with `MGOAL_FIND_ITEM` in data/mods/innawood/npcs/missiondef.json
Thus these missions should now accept any item of the given type.

#### Describe alternatives you've considered
None

#### Testing
None

### CODE REVIEW

**Review by pjf — APPROVED** [review]
These changes fix things for me, including (thankfully!) for quests that have already been given.

**Comment by Light-Wave** [comment]
> These changes fix things for me, including (thankfully!) for quests that have already been given.

Glad to hear that that also gets resolved!

**Comment by Light-Wave** [comment]
As far as I can tell, the errors are about mutations and density, and nothing related to my changes.

**Comment by LyleSY** [comment]
Nice! But also, does this mean that MGOAL_FIND_ANY_ITEM is completely bugged? If so that's probably worth it's own issue

**Comment by Light-Wave** [comment]
> Nice! But also, does this mean that MGOAL_FIND_ANY_ITEM is completely bugged? If so that's probably worth it's own issue

It's my understanding that MGOAL_FIND_ANY_ITEM is for when you want the player to get an instance of the item that has been tagged by the quest, and not when you want to get any item with the given item ID. Kind of poorly named, but seems to work as intended.

**Pull request merged**
