### PR TITLE
Fix list menu filter not working

### LINKED ISSUE #54355: Debug spawning item menu "find" no longer working
### Describe the bug

The "find" function of the debug item spawning menu doesn't work anymore. It's possible to type a match into the field, but that does not filter the menu at all.

### Steps to reproduce

Load save.
Bring up the debug menu and go to the item spawn menu.
Try to filter the menu to find what you're looking for.
See that the menu is unchanged.

### Expected behavior

Filtering still working.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5210-g73825af5c9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It worked yesterday (with an updated master), but fails today (with an updated master), so something in the last day has caused a problem.

I tested the crafting menu filtering, and that still works, so the problem is hopefully isolated to the debug menu.

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

#### Purpose of change
* Fix #54355

I made a mistake in #54333 where I assigned value to the wrong variable.
#### Describe the solution
Correct code logic.

#### Testing
Enter wish item debug menu and filter anything.

### CODE REVIEW

**Comment by Coseo** [comment]
I ran into the same bug you're fixing here and triaged it, and have some notes of my own. There's still some issues here, at least in my opinion.

First of all, redundancy - the whole segment that transforms to lower case is unnecessary because lcmatch is used afterwards. Unless there's some bizzare reason involving translations that this has to be done this way (and in that case that logic should be in _lcmatch_, not here) then you can remove that entire block of code. Since lcmatch seems to already be using wide chars (at least as of #54333), it should still uphold your goals for that PR.

Second, currently, the two searches are not exclusionary. you either want to do the case-insensitive lcmatch search OR the case sensitive search with the unmodified filter/fstr values. Doing both is not only unnecessary, but hurts both readability and performance - and I'd consider readability a worthwhile note for this function since it seems so easy for it to get messed up. 

Your proposed fix, as far as I understand it, will also **break case sensitive searches** - or rather, it will leave them broken. If the case sensitive search doesn't find anything, it'll follow up by doing the case insensitive search automatically. This means instead of getting an empty list telling you "theres nothing with that case sensitive name", if there are any case insensitive matches, you'll get those instead. This seems like unintended behavior. If this is the intended behavior it should be documented, because it certainly doesn't seem like it.
This is how I'd do it:

```
    bool notfiltering = !filtering || filter.empty();
    int num_entries = entries.size();
    // TODO: && is_all_lc( filter )
    bool nocase = filtering_nocase;
    
    fentries.clear();
    fselected = -1;
    int f = 0;
    for( int i = 0; i < num_entries; i++ ) {
        if( notfiltering ||
            (nocase ? static_cast<int>( entries[i].txt.find( filter )) != -1 : lcmatch( entries[i].txt, filter ))) {
```
Ternary operator is optional, you can split it into two exclusionary comparisons (one using !nocase &&, the other using nocase&&) if you'd prefer. 

If you change the code to this, fstr is nolonger necessary, and a whole lot of unnecessary code goes away. This also resolves the search-exclusivity issue, and furthermore is more performant, as it only ever does one search, never two.

**Comment by BrettDong** [comment]
Thank you for your comment, I found the same problem before submitting this pull request, but I am afraid of causing other unintended side effects if I were to refactor the filter logic, so I kept the code logic as it was before in the scope of this pull request.

**Comment by BrettDong** [comment]
I agree the filtering logic is problematic and needs addressing in a future pull request.

**Comment by MikuMiddo** [comment]
I found this bug occured again in the lastest version, @BrettDong

**Pull request merged**
