### PR TITLE
Rejoin horde option

### PR DESCRIPTION
**Pull request by CIB**
Adds an option that will put spawned zombies back into a horde on the horde movement processing. This makes hordes a tiny bit more functional, as you can't effectively stop a hordes movement by moving through it and making all zombies in it spawn.

I also nerfed the range of sound signals by factor 5, because in my game I would drive into a bush and zombies from two towns over would start moving my way. Effectively all the hordes on the map would just keep following me whenever I made noise. With the nerf, hordes disperse across the map better, meaning there's always zombies to fight, but it's at least possible to stay in a place for more than a few hours without fighting all zombies on the entire map.

### CODE REVIEW

**Comment by kevingranade** [comment]
I don't see a good reason for this to be an option, not rejoining the horde is IMO a bug and this simply fixes it.

**Comment by Rivet-the-Zombie** [comment]
Yeah, better to make this a proper part of the wander spawn itself.

**Comment by Zireael07** [comment]
Thanks for the sound nerf!

**Comment by CIB** [comment]
> I don't see a good reason for this to be an option, not rejoining the horde is IMO a bug and this simply fixes it.

Okay. The reason I made it an option is simply that I'd like to see it tested more before replacing default horde behaviour.

The current behaviour is that all zombies can be added to hordes, not just the horde spawned ones. Personally I find that desirable, but it can lead to weird things, like small towns being almost vacated when you visit them for a second time.

Ideally I'd like hordes not to wander completely randomly, but stick to towns and easy terrains like roads when not drawn by a signal, and return to towns a while after they've lost interest in a signal.

**Comment by kevingranade** [comment]
I agree hordes should have some default motion back toward towns so that it's not trivial to empty towns out by leading a horde through one, but I think it could use a patchy fix of some kind rather than making this an option.  For example, leave behind some proportion of the horde if it's in a town-type map square, that would both prevent it from stripping all the townie zombies if a horde moves through, and even make hordes repopulate towns (which would be tactically useful if you had an enpty town handy to lead a horde through).

I'm not totally sure, but checking for zombie species sounds reasonable, some of the outliers are e.g. jabberwocks, should they get snapped up by hordes?

**Comment by CIB** [comment]
Okay, that should be everything.

**Comment by CIB** [comment]
Another thing, I'd like to make the size of hordes configurable, but not sure how that'd best be done.

**Comment by chaosvolt** [comment]
Interesting to see. I would hope this has since been tested and found to work?

**Pull request merged**
