### PR TITLE
[CR] Add Shower Victim profession (Wilderness Scenario)

### PR DESCRIPTION
**Pull request by maltouzes**
Just for fun!
Sometimes you are in the shower, zombies come in your bathroom. You're scared, you run... run... and run, and you're in the forest.... alone... with a towel.
Really, it's happen sometimes!

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Amusing, if potentially suicidal.

**Comment by maltouzes** [comment]
> Amusing, if potentially suicidal.

Indeed! Very hard to survive but not impossible. I play many times with this scenario/profession and it's possible to survive.
Pick up cattaill stalk -> plant fiber -> string), stone, heavy stick and other stuff in the forest. Make a bindle, stone knife, stone hammer, rag (plant fiber), wooden needle.... Build an Improvised Shelter, after you can use tailoring skill for make "Armor". Build a basic fishing rod... plant seeds you find in the forest...

Careful! Moose are your real enemy.

Ps: More easy if you take the "Fast Healer" Traits.

**Comment by DangerNoodle** [comment]
That does become a stumbling block if not near a swamp, though.

**Comment by maltouzes** [comment]
> That does become a stumbling block if not near a swamp, though.

Yes, maybe I should create a new scenario with swamp for Scenario Location and add the Shower Victim profession (and others) only to this new scenario.
@illi-kun @BrettDong What do you think about that?

**Comment by DangerNoodle** [comment]
If I recall, the More Survival Tools mod already changes the wilderness scenario to allow specifically starting in swamps as an alternative.

**Comment by mugling** [comment]
I'm with @illi-kun on this - it just further bloats the starting locations

**Comment by illi-kun** [comment]
Sorry for late response but mugling formulates my opinion pretty good.

**Comment by DangerNoodle** [comment]
True. Wilderness scenario has a decent array of choices. If there are any scenarios I'd like to see more variety in, it would be Sheltered, Ambush, and The Next Summer. Not certain what would be good additions for those.

**Comment by maltouzes** [comment]
> it just further bloats the starting locations

Understood.

**Pull request closed without merging**
