### PR TITLE
[CR] Color coded construction menu

### PR DESCRIPTION
**Pull request by drbig**
Construction menu needs love - it's so far back behind the crafting menu...

This simple PR adds basic and hopefully useful color-coding:
- Red if you have all but the skill needed
- Light blue if your skill matches the difficulty (so you know this will make you _practice_)
- White if you can make it but it's below your skill
- Gray as before

The light blue is especially helpful imho.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Is the light blue different than the blue for other "I can do this" stuff?

**Comment by drbig** [comment]
@DavidKeaton I'm not sure if I get what you're exactly asking about, but the blue used is the same as for books that you can learn from (and also the same color as recipes you can learn from a book once #11620 gets merged).

**Comment by drbig** [comment]
Also obligatory screenshot:
Color coded construction menu

**Comment by DavidKeaton** [comment]
okay cool, asking because shades of blue confuse me a lot.

**Comment by KA101** [comment]
Any other thoughts?

**Comment by drbig** [comment]
Seems like that'll be it.

**Comment by Zireael07** [comment]
I love it!

**Pull request merged**
