### PR TITLE
Add recipe for fried chicken take 2

### PR DESCRIPTION
**Pull request by Cyrano7**
Adds recipe for fried chicken. Should I increase the seasoning cost?
Updated from this https://github.com/CleverRaven/Cataclysm-DDA/pull/15030

### CODE REVIEW

**Comment by chaosvolt** [comment]
Sorry about that.

**Comment by Cyrano7** [comment]
@chaosvolt its fine. Its called githeadachehub for a reason haha.

**Comment by Rivet-the-Zombie** [comment]
The amount of seasoning seems good.

**Comment by Zireael07** [comment]
why close?

**Comment by chaosvolt** [comment]
;A;

**Comment by Rivet-the-Zombie** [comment]
Semi related: some kind of generic 'fried meat' recipe would be really good to have as well.

**Comment by chaosvolt** [comment]
Hmm, maybe. Assuming we don't go the other way and have more distinction between meats for differing morale bonuses, but that'd be high complexity for little gained.

**Comment by Cyrano7** [comment]
So I closed it cause I want to go about it in a different direction. The canned chicken is more of a paste I guess. So better to wait for proper chicken meat to implement this.

**Comment by chaosvolt** [comment]
Ah, sorry. ^^"

**Pull request closed without merging**
