### PR TITLE
Add butchering quality to everything with cutting quality

### LINKED ISSUE #47176: Some items have a cutting quality but no butchering quality
# Is your feature request related to a problem? Please describe.
While I was digging through items for a different issue I found a few items which had a cutting quality but no butchering quality. A person "could" butcher a corpse with all of them so they should be given a butchering quality.

# Describe the solution you'd like
Assign a butchering quality to the following items.
| Item  |
| ------------- |
| pair of scissors |
| X-Acto knife |
| shears |
| scalpel |
| boxcutter knife |
| simple knife spear |
| knife spear |

# Describe alternatives you've considered
-Remove butchering quality entirely and just expand cutting quality to take it's place.

# Additional context
Suggested qualities when compared to existing items.
| Item | Butchering Quality | Based On |
| ------------- | ------------- | ------------- |
| pair of scissors | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher, this really depends on the quality of the scissors as they can vary drastically from scissors which break at the sight of cardstock to scissors which could probably take off a finger at the joint without issue |
| X-Acto knife | 7 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, should also be slightly worse than scalpel, this puts it at the same level as a multi-tool |
| shears | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher |
| scalpel | 8 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, this puts it at the same level as a swiss army knife |
| boxcutter knife | 8 | Same level as swiss army knife, roughly same blade sharpness as X-Acto knife but has a larger blade and a grip more suited for large cuts, smaller blade than swiss army knife but much sharper |
| simple knife spear | -42 | Same level as makeshift glaive |
| knife spear | -28 | Same level as glaive |

### PR DESCRIPTION
**Pull request by Fosheze**
#### Summary
Balance "Add Butchering quality to cutting items"

#### Purpose of change

Fixes #47176 
Ensure that all items which have a cutting quality have a butchering quality

#### Describe the solution

Add the following butchering qualities to the following items.

pair of scissors | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher, this really depends on the quality of the scissors as they can vary drastically from scissors which break at the sight of cardstock to scissors which could probably take off a finger at the joint without issue
-- | -- | --
X-Acto knife | 7 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, should also be slightly worse than scalpel, this puts it at the same level as a multi-tool
shears | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher
scalpel | 8 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, this puts it at the same level as a swiss army knife
boxcutter knife | 8 | Same level as swiss army knife, roughly same blade sharpness as X-Acto knife but has a larger blade and a grip more suited for large cuts, smaller blade than swiss army knife but much sharper
simple knife spear | -42 | Same level as makeshift glaive
knife spear | -28 | Same level as glaive

#### Describe alternatives you've considered

-Not adding butchering quality to any of these items.
-Leaving out scissors and shears because butchering with them would be difficult.
-Dropping the butchering quality below 0 for scissors and shears because butchering with them would be difficult.

#### Testing

Loaded game with edited values. Verified that items had a butchering quality.

#### Additional context

This is my first PR so please let me know if I missed anything.
I am also open to changing any of these values. These were just what I first came up with.

### CODE REVIEW

**Comment by BrettDong** [comment]
The format for summary is like

Balance "One line summary"

**Comment by Fosheze** [comment]
> The format for summary is like
> 
> Balance "One line summary"

Just saw that it failed. I think I've got it now. Thank you.

**Comment by actual-nh** [comment]
Why do bolt cutters not have cutting (and now butchering) qualities? They can cut through bone.

**Comment by Abstract-Note** [comment]
possibly because they suck at cutting anything other than bone or metal.

**Comment by Fosheze** [comment]
> Why do bolt cutters not have cutting (and now butchering) qualities? They can cut through bone.

The point of this PR wasn't to audit everything and determine if it should have a cutting or butchering value. I just wanted to take the items which already had a cutting value and assign them a butchering value.

As far as the bolt cutters go though, from my experience they do most of their work through crushing rather than cutting. They would make as effective of a cutting tool as a splitting maul. I could see the argument for giving them a majorly negative butchering value because with enough work and determination I imagine that you could maybe dismember something with them. However as I said, that is something for a different PR.

**Comment by actual-nh** [comment]
> > Why do bolt cutters not have cutting (and now butchering) qualities? They can cut through bone.
> 
> The point of this PR wasn't to audit everything and determine if it should have a cutting or butchering value. I just wanted to take the items which already had a cutting value and assign them a butchering value.

OK.

> As far as the bolt cutters go though, from my experience they do most of their work through crushing rather than cutting. They would make as effective of a cutting tool as a splitting maul. I could see the argument for giving them a majorly negative butchering value because with enough work and determination I imagine that you could maybe dismember something with them. However as I said, that is something for a different PR.

I can see the argument (although it does depend on how sharp they are). As far as I can tell, the game currently lacks gardening/bush-cutting shears/snips/whatever (can't think of the exact name) - things used to cut thin branches? I can say from personal experience doing dissections that those work wonderfully for getting through bone, etc. As you said, something for a different PR.

**Comment by actual-nh** [comment]
Scalpel: Really depends on whether the blade is fresh; if so, I'd give it about that of a paring knife due to how sharp it is, despite the small size. If it's at all blunt, much worse. Sort of like scissors. As it is, an average of 8 looks OK.

**Comment by Fosheze** [comment]
> I can see the argument (although it does depend on how sharp they are). As far as I can tell, the game currently lacks gardening/bush-cutting shears/snips/whatever (can't think of the exact name) - things used to cut thin branches? I can say from personal experience doing dissections that those work wonderfully for getting through bone, etc. As you said, something for a different PR.

Gardening shears would definitely work as you said and should probably be added for that purpose (hacksaw replacement for butchering?) but generally bolt cutters don't have a sharp blade. It is left dull deliberately because a sharp edge would just break off the first time they are used. You can repeatedly run your hand across a brand new bolt cutter blade and not even scratch yourself. It's more accurate to think of them as a pair of blunt wedges with a lot of force behind them than as a shears. They would be able to easily crack bone but getting through any sort of flesh would be difficult. Most commercially available bolt cutter jaws also only open to about an inch wide so getting around a large bone would be an issue.

To put it rather morbidly, if you took a bolt cutters to your finger you would break the bone and completely ruin the finger but odds are you wouldn't actually be able to cut the finger off without having to do a whole lot of "gnawing" on it with the bolt cutters.

**Pull request merged**
