### PR TITLE
Changed formula for character strength required to install something in a vehicle

### PR DESCRIPTION
**Pull request by Night-Pryanik**
If item weight is less than 10 kilograms, then required strength is 1. Else - 1 strength per 10 kilograms (based on comment for `STR_LIFT_FACTOR`  (now deleted) from `game_constants.h).

Before: 300-kg V12 engine can be installed by a weakling with only 6 strength.
After: 300-kg V12 engine requires a 30-strength superhuman to install.

### CODE REVIEW

**Comment by AMurkin** [comment]
Why not `weight() <= 10000_gram` for conditional part?

**Comment by AMurkin** [comment]
Or even better: `return std::max( weight() / 10000_gram, 1 );`

**Comment by AMurkin** [comment]
Question: why not change STR_LIFT_FACTOR value?
Than only one usage of STR_LIFT_FACTOR left: in item::lift_strength().

**Comment by Night-Pryanik** [comment]
> Why not change STR_LIFT_FACTOR value?

It's meant to be constant. We should get rid if it.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Pull request merged**
