### PR TITLE
Adds Metric values to item descriptions.

### PR DESCRIPTION
**Pull request by Dozed12**
weapons.json - Done;

Doing the rest.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm mildly against, keeping every item in the game that has units updated
with two measures seems like a pain, and I don't like the extra clutter.
On the translation front, definitely delay this until after 0.C.

**Comment by Dozed12** [comment]
For me it is a immersion killer to have only imperial system as I am clueless of what 1 inch, 1 feet is. Maybe I could add it as a mod so it doesn't bothers people familiar with imperial.

**Comment by KA101** [comment]
Opposed on maintenance grounds.

**Comment by kevingranade** [comment]
An alternative is an en_uk translation that just changes the units.  You'd
only need to define translation strings for the ones you want to change.

**Comment by Snaaty** [comment]
How about we simply change it to something like " a piece of string, roughly as long as your arm"?

**Comment by KA101** [comment]
Arm-length can vary by player (I'm kinda gangly, for example).  That said, that's a better solution than specific measurements IMO.

**Comment by Dozed12** [comment]
I like that, do you want both the imperial and that rough measure or just the rough measure?

**Comment by kevingranade** [comment]
Neither, I don't think making it needlessly vague is an improvement.

**Comment by i2amroy** [comment]
>An alternative is an en_uk translation that just changes the units.  You'd
only need to define translation strings for the ones you want to change.

This is probably the best way to go about it right here. And I agree with kevin, making measurements needlessly vague isn't really an improvement IMO.

**Comment by Dozed12** [comment]
I will take look on how to do so later, I'm quite busy now but in a few weeks I may give it a shot.
Btw, cata players must be mostly english/american for this wasnt made before... or other people simply dont care or arent ignorant like me and are used to Imperial measures.

**Comment by i2amroy** [comment]
Yeah, the majority of Cata players by far live in the US.

**Comment by KA101** [comment]
More like the majority of the devs.  Kevin, Rivet, i2amroy, and myself are all USian (we've got the time zones pretty well covered, too!).  Narc is Romanian, I suspect but don't *know* that BevapDin is German, and we lost illi-kun with the MSVC jettison, so we lost the Russian dev.

Playerbase, well, comes from everywhere based on the translations.  :-)

**Comment by KA101** [comment]
Closed with encouragement to make it a UK translation.  We aren't *that* opposed.

**Pull request closed without merging**
