### PR TITLE
Allow cellphones to be used as flashlights similarly to PDAs

### PR DESCRIPTION
**Pull request by ghost**
Cellphones have been relocated to tools.json and can now be activated to illuminate LED.
Cellphone now appears under Tools in Inventory.

Light Range: 30
Turns per charge: 30

### CODE REVIEW

**Comment by pisskop** [comment]
Gotta change their recipe to prevent battery returns from disassembly.

**Comment by pisskop** [comment]
Light Range: 30

thats ridiculous

**Comment by Coolthulhu** [comment]
Light luminance isn't the same thing as radius.
Not sure what is the exact formula, but I think it's logarithmic.

**Comment by Reclusive-reptile** [comment]
Should cell phones recharge via ups?

**Comment by pisskop** [comment]
Light 30, if it is an item standin for luminescence, is something like 7-10 tiles.  It should be 2 or maybe 4, imo.

I dont think it should be ups recharged by default.  its a civilian item.

**Comment by Nasuga** [comment]
I've been playing with whitespace and using some online JSON linters (which my changes validate against ) but I cannot figure out the issue. The error isn't descriptive enough for me to make heads or tails of it. This fails the linter included with Cataclysm but is correctly interpreted by the Cataclysm engine. 

I'm at a loss and appreciate any ideas as to what my issue is.

**Comment by Nasuga** [comment]
@pisskop , the radius specified in description is the same in source code. a PDA with a white screen yields 10 while a flashlight yields 100. Using 30 seemed like a fair compromise.

**Comment by cainiaowu** [comment]
the issue is your weight field is in wrong places.

ERROR: Format error at line 5200
<     "material": [ "plastic", "aluminum" ],
>     "weight": 226,

HINT: Canonical output for this block was:
    "id": "cell_phone",
    "type": "TOOL",
    "name": "cell phone",
    "name_plural": "cell phones (off)",
    "description": "This is a typical cell phone but features an LED for use as a flash.  Using this cellphone will turn it on and provide light, assuming it is charged with batteries.",
    "weight": 226,
    "volume": 1,
    "price": 10000,
    "price_postapoc": 2000,
    "material": [ "plastic", "aluminum" ],
    "symbol": ";",
    "color": "light_gray",
    "ammo": "battery",
    "initial_charges": 100,
    "max_charges": 100,
    "charges_per_use": 1,
    "use_action": {
      "target": "cell_phone_flashlight",
      "msg": "You activate the flashlight app.",
      "active": true,
      "need_charges": 1,
      "need_charges_msg": "The cellphones's batteries are dead.",
      "type": "transform"
    },
    "flags": [ "WATCH", "ALARMCLOCK" ]

**Comment by Nasuga** [comment]
Changes:
I changed the luminescence on @pisskop 's recommendation, for reference PDA is 10 and cellphone is now 20 from 30 originally. Cellphone should be brighter as it isn't using a white screen to illuminate but rather an led. 

The recipe for cellphone disassembly now will not return a new battery.

Code has been refactored thanks to the help of @narc0tiq . I'd like to thank everyone else on IRC who tried to help me resolve the linting.

**Comment by pisskop** [comment]
4-5 tiles, and making you visible to half the map.  Its a decent compromise.

**Pull request merged**
