### PR TITLE
Expose daily calories calendar to math

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
json power
#### Describe the solution
make a math function to return value from calorie calendar, thanks Andrei8 for their help
#### Testing
Compiled, played a little with it
image
#### Additional context
I am a bit worried to touch commit history because of branch update, so i'd ask to squash the PR if possible

### CODE REVIEW

**Comment by IdleSol** [comment]
If you can, add two more boxes:
- Total
- Average consumption per day for the last week (or all time)

Off topic, would this be for vitamins?

**Comment by GuardianDll** [comment]
\> Total
total of what? Nevertheless, one could make a simple jmath to do the same, the result would be equal

**Comment by IdleSol** [comment]
>total of what?

Total calories consumed for the entire period. Is this list limited to 30 days? Then for 30 days.

Oh, and if I'm being brazen, then:
pict

And perhaps we should change the format of the calorie display? 12000 -> 12 000

**Comment by GuardianDll** [comment]
oh, this screenshot is just showcase of the funciton, this PR do not add such UI because the way it works is too ugly for my taste

**Comment by IdleSol** [comment]
Then I'll hope someone will take on the UI for this feature.

**Pull request merged**
