### PR TITLE
[CR]Add a no flintlock or cap and ball firearms mod

### PR DESCRIPTION
**Pull request by Cyrano7**
This is how I play the game. I'm sure some other people would like to play this way as well. IDK how people feel about the no old guns mod at the moment. It would nice to see it be more specific about what should be included though.

### CODE REVIEW

**Comment by mugling** [comment]
Was this not supposed to be the intention of `No antique guns?`

**Comment by Cyrano7** [comment]
I think so but it changed over time it seems. I can see having both or just scaling back no antique guns to just flintlocks and cap and ball guns.

**Comment by Cyrano7** [comment]
Sometimes I don't like playing with thompsons, bars and other ww2 stuff too though.

**Comment by Coolthulhu** [comment]
I don't think we need more no-bloat mods, except maybe one grand no-any(/most)-bloat mod.
We do already have a lot of those tiny customization mods and filntlocks don't unbalance anything (unlike energy weapons or rivtech) and aren't unrealistic.

**Comment by Cyrano7** [comment]
I think https://github.com/CleverRaven/Cataclysm-DDA/pull/18651 is a good middle ground for a gun exclusion mod so this would be unnecessary.

**Pull request closed without merging**
