### PR TITLE
Bug(flesh)fixes

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary

SUMMARY: None

#### Purpose of change

While messing with the giant insects I added some new species for footsteps and anger triggers, however that broke some hardcoded stuff referring to the INSECT species. Thankfully, I could replace all* of them with the material "iflesh".

#### Describe the solution

- The message shown for not penetrating the armor of a bug now check for "iflesh"
- Insecticidal gas field now checks for the material "iflesh" to see if the mob is vulnerable, I also added a new monster flag "INSECTICIDEPROOF" to allow things to be made of bug flesh but not be hurt by the gas (currently only the mass of zombie spiders have it)
- The monmove code checking for immunity against insecticide now checks for material and the flag (not convinced it does anything, but whatever)

TODO:

<strike>- [ ] Make bugs bleed that sweet haemolymph </strike> Rolled into #46156 

- [x] Adjust the Insect Pheromones trait to work on appropriate insects

#### Describe alternatives you've considered

Backpedal on the whole "adding species" thing. I'd rather not, since then most of the anger/fear triggers and all the footsteps would need to move into the monster defs themselves.

#### Testing

Compiled, shot a centipede with a slingshot, it bounces off its carapace instead of its thick hide. Thrown an insecticidal gas grenade at said centipede, it died in short order. Spawned a dragonfly, an ant and a mass of zombie spiders in the same cloud, all but the zpiders died. Checked the pathing in an unmodified game, noticed no difference.
Spawned a wasp in detection range, mutated Insect Pheromones before it ate my face, it decided to not want to eat my face any more ( unless I stayed close for too long ). Removed mutation, wasp proceeded to eat my face. Same test with the other affected factions, to more or less the same effect ( soldier ants are too pissed off for it to work, but the rest was a bit chiller).

#### Additional context

The pathing is kind of weird, since they don't seem to path *out* of a cloud, and because of the limited vision range in there they lose aggro every few turns, so they tend to just sit in one place and die quietly.

*I left the code checking for INSECTs in the Granade untouched.

### CODE REVIEW

**Comment by actual-nh** [comment]
Regarding the pathing - that would be especially inappropriate behavior for roaches. They can associate smells with "not feeling good", as far as I can tell; for instance, if a food causes them to start not feeling well (e.g., poisoned bait), and they survive, they will avoid that food thereafter.

Note also that insects have two physically separated, and indeed movable, sources of a sense of smell - antennae. They should definitely be able to tell what direction to go to get out of such a cloud, by comparing them.

**Comment by Venera3** [comment]
The insect pheromones now work their (limited) magic on acid ants, ant, bees, and wasps instead of all insects in general. Having one generic pheromone for all social insects is a thing that could be expanded, but it makes at least more sense than you wooing a dermatik with your stench.

**Comment by actual-nh** [comment]
To see if the Travis build indicates any actual errors, looks like you'll need to do a fast-forward from the CDDA master. There was a spacing error that got fixed 2 days ago.

**Comment by anothersimulacrum** [comment]
I've just kicked travis, no need to do anything.

**Pull request merged**
