### PR TITLE
Parking garage

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary

```SUMMARY: Content "Adds parking garages"```

#### Purpose of change

Adds more parking spaces and some more terrain.
Also, variety.

#### Describe the solution

Added 2x1x4 parking garage including an underground and a rooftop parking space. It has a space for 49 cars.  

#### Additional context

Pony wall is concrete railing and the yellow wall is the yellow concrete floor.
parking_garage_1
parking_garage_0
(2x)
parking_garage_3
parking_garage_2

### CODE REVIEW

**Comment by dom4op** [comment]
Umm, it doesn't look like an SUV would fit in one of those elevators. And yet we see it on the roof.

**Comment by LovamKicsiGazsii** [comment]
Fixed it.
fix
Now the SUV fits in the elevator. This wasn't really important, because you still can't bring the car down.

**Comment by JeanLucVanDamme** [comment]
I like this addition no matter what.

But it does remove some of the fun / emergent-gameplay-ness that you can't take the car down. Is that a choice, or is that kind of behavior (e.g., changing z-levels while/with a vehicle) not possible yet?

But hey, if working car-elevators are impossible, you still have two options. One, drive a car off the 2nd floor edge, hope you survive. Two, elevated parking garage base, with the greatest barricades of all (leave cars in front of the stairs to block incoming zeds).

**Comment by anothersimulacrum** [comment]
>  One, drive a car off the 2nd floor edge, hope you survive.

Right now, this will just lead to you driving a car through the open air.
Perhaps cars spawning on the upper levels should be removed for now and revisited once vehicles properly transition z-levels?

**Comment by kevingranade** [comment]
It's currently not possible to drive a car down a ramp, and it's not possible to use the elevator since they would have no power.

It's inconsistent either way. Either you have no cars on top of parking garage where you would expect them to be, or you have cars on top of parking garages and can't get them down. I would prefer to have the cars there than not.

**Comment by Rail-Runner** [comment]
> Perhaps cars spawning on the upper levels should be removed for now and revisited once vehicles properly transition z-levels?

Well, I think it has to be solved somehow either way. If it's true, then even as it currently is, player can build a foldable vehicle, fold it, bring it upstairs, unfold and drive it thorough the air.

**Comment by JeanLucVanDamme** [comment]
Here's another vote for keeping the cars on the 2nd level, even if you can't get them down yet.

**Pull request merged**
