### PR TITLE
Add Storage Lines

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "Adds new survival / camping gear storage lines"

#### Purpose of change
Adds a new item Storage Line based off of https://www.niteize.com/product/GearLine.asp
It's a tough reliable way of carrying multiple small tools/items on a line. My intent was for it to be attachable to carabiners on backpacks.
 

#### Describe the solution
Adds the item, and adds it to a few item groups for camping and hunting.

This item has a few weird things. Specifically:

- it uses the minimally used HARD tag so that it will have a minimum length. 
- It's minimum length is set to a little longer than the longest item that can fit in it since you can't roll something up more than what is attached to it. 
- I've also set the number of pockets to be smaller than the actual number of carabiners you can see attached online. There aren't rules for overall weight for items just per pocket so this seems like a good balance.

It also isn't great to work with to put stuff in it with the current UI. The best way currently is to wield it, insert the items then put it in your inventory. This however will be a good item to work on making putting things in internal pockets work better and smoother.

In the future it would be cool if you could actually hang these up at camp sites but it's more than I can do over the holidays. 

#### Testing
Spawn a Storage Line,
Wield it,
Insert a few items,
Put it in a backpack.
image

#### Additional context
here's a pic of what this is based on
image

in game:
image

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm not seeing a justification for this being wearable, Yes it has pretty high encumbrance to reflect it being awkward, but I really don't think we want to dive this far into, "well technically you can clip a carbiner to anything so everything has infinite storage".
There are major down sides to wearing something like this that we do not and probably will not reflect in-game, so until and unless we start doing so I don't think this goes in as a wearable.

**Comment by bombasticSlacks** [comment]
That's reasonable. Are they acceptable to go in as just an organizing tool with the option to wear removed?

**Comment by bombasticSlacks** [comment]
I went ahead and just updated it to be an organizational item.

**Comment by kevingranade** [comment]
Ok so you clip things to it to keep them together, so in game terms it's kind of an inside-out toolbox?  Sure that works.

**Pull request merged**
