### PR TITLE
NPCs disengage from combat in order to follow the player.

### PR DESCRIPTION
**Pull request by CIB**

### CODE REVIEW

**Comment by Zireael07** [comment]
Woo!

**Comment by BevapDin** [comment]
The branch is named "npc_stop_suicide", but is actually the opposite. NPC won't *defend* themself. I had (past tense!) a companion that just stood there, starring stupidly at the zombie. The zombie eventually landed enough hits.

I think, the NPC should either defend (if the attacker is adjacent) or move away.

**Comment by CIB** [comment]
Hmm.. That's odd. The code should only trigger when they're following you. So they decided that, rather than follow you, they'd prefer to tie their shoe lace or what? That's possible, but I can't think of a fix that doesn't involve a bigger overhaul.

**Comment by BevapDin** [comment]
The problem could be that you skip the call to `choose_monster_target`, which leaves `target` with its initial value (`INT_MIN`). At the end of `npc::move`, this is checked and the nearby monster is only attacked if it's not `INT_MIN`.


Actually, you might want to put your code at the end of `npc::move`, where the comment stats:
>Sometimes we'll be following the player at this point, but close enough that
"following" means standing still.  If that's the case, if there are any
monsters around, we should attack them after all!

That sounds suspiciously similar to what your code is supposed to do. Maybe you only need to check there for adjacent vs non-adjacent monsters?

**Pull request closed without merging**
