### PR TITLE
Tweak strong mixed alcohol

### PR DESCRIPTION
**Pull request by Cyrano7**
Remove pine wine and mead, add brandy and moonshine.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Change 7 to 7 exchange to 1 to 1 like weak mixed alcohol.

You made it take 7x as much volume

**Comment by Cyrano7** [comment]
@Coolthulhu Ah true forgot about that. Can you have a result multiplier that's less than one for recipes?

**Comment by Coolthulhu** [comment]
Stack size might work

**Comment by Coolthulhu** [comment]
> mead because its not distilled

It has stats like all distilled alcohols: ALCOHOL flag and 7 charges per stack.

**Comment by Cyrano7** [comment]
There are mixed drinks that have the ALCOHOL use action too. Doesn't mean they should be in here. You meant use action not flag right?

**Comment by Cyrano7** [comment]
Pine wine a mead should be made closer to grape/dandelion wine really. But I'll leave that for another PR.

**Comment by Coolthulhu** [comment]
> You meant use action not flag right?

No, I mean the flag. The use action is for all alcoholic things, the flag governs alcohol content. ALCOHOL and ALCOHOL_WEAK. There is also ALCOHOL_STRONG, but only on moonshine.

**Comment by Cyrano7** [comment]
Go check the code, I'm still pretty sure you are talking about the use action. There aren't any alcohol flags I can see.

**Comment by Coolthulhu** [comment]
OK, yeah - there are 3 actions. I confused it with some other similar mechanic.

Still, alcohols should be grouped by their strength. Weak/strong depends mostly on the flag. If mead isn't strong, then it should have the weak action.

**Comment by Cyrano7** [comment]
Ya I totally agree but I'll go change those in another PR. Because it might be a few that need changing and a haven't really looked. Pine wine and mead are the 2 that I know of so far that could be bumped down to the weak action.

**Comment by Cyrano7** [comment]
@Coolthulhu So it seems that the wines are split between weak and normal. bum, fruit and dandelion are weak and the rest of the wines are normal. Its kinda of the same story with the mixed drinks. Are there any good numbers to go off of balance wise? like weak = <%20 normal = %20-%50/60 strong = >%50/60 ABV.

**Comment by Coolthulhu** [comment]
The best way would be to rewrite the alcohol function into iuse actor and have any arbitrary granularity.

But if we're staying with the current functions, we have to balance medium alcohols with stack size.
The alcohol functions assume that medium alcohol is 2x as strong as weak and strong is 3x as strong as weak. Per single charge. Meaning that 250 ml of vodka contains 14 times as much alcohol as 250 ml of beer.

We have the following options:
* Weak alcohol, 1 stack size = 1 au ("alcohol units"). Example: beer
* Medium alcohol, 1 stack = 2 au. Imperial stout
* Weak alcohol, 7 stack size = 7 au. Bum wine
* Medium alcohol, 5 stack = 10 au. The weird named wines
* Medium alcohol, 7 stack = 14 au. Vodka

The "au"s should correlate linearly (and quite strongly) with ABV.
There is a large gap between 2 and 7, which is why having an actor/value instead of a regular function would be good.

**Comment by mugling** [comment]
> The best way would be to rewrite the alcohol function into iuse actor and have any arbitrary granularity.

This would be the best approach, possibly using the system:
```
1 unit = 10ml @ 100%
1 unit = 25ml @ 40%
1 unit = 250ml @ 4%
```

**Comment by Coolthulhu** [comment]
Moonshine stands out, it was intentionally excluded from the list because it is stronger and less healthy than all other strong alcohols.

**Pull request merged**
