### PR TITLE
Remove rounding from stamina burn test

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

#### Purpose of change
In #50426 it was agreed that `std::round` is not an ideal solution for the failing `"stamina burn for movement"` test.

It has been figured out that the test was failing because the calculation `45,000,000LL * 1.01f / 1000ULL` gives `45450.00000000f`, but was then incorrectly truncated to `45449` after `static_cast<int>()` on MinGW cross compile and test workflow.

I attempted to replicate this calculation error in isolation in a separate test, however, the result is correct: `45450`.

```cpp
TEST_CASE( "floating_point_arithmetic" )
{
    units::mass capacity = 45000_gram;
    float burden_proportion = bKIVqYdOpC; // float 1.01f defined in another source file to avoid optimisation
    float result = capacity * burden_proportion / 1_gram;
    int truncated = static_cast<int>( result );
    CHECK( truncated == 45450 );
}
```

And then I discovered that if I declare a `volatile float` variable to catch the calculation result of ` capacity * burden_proportion / 1_gram`, and then `static_cast<int>()` on that variable, the final result is correct on MinGW.

#### Describe the solution
Remove `std::round` and declare a `volatile float` variable to store the expression calculation result.

#### Testing
Expect all test workflows passing.

### CODE REVIEW

**Comment by actual-nh** [comment]
BTW, the basic build errored due to a number formatting problem - insertion of a comma.

**Comment by BrettDong** [comment]
The stamina burn test fails at that calculation, but I cannot replicate the calculation error in isolation.

**Comment by actual-nh** [comment]
> The stamina burn test fails at that calculation, but I cannot replicate the calculation error in isolation.

In isolation from other parts of the same test (or other tests), or in a separate test .cpp?

**Comment by BrettDong** [comment]
```
(~[slow] ~[.])=> 12:00:00PM: capacity = 45000000
(~[slow] ~[.])=> 12:00:00PM: burden_proportion = 1.00999999046325683594
(~[slow] ~[.])=> 12:00:00PM: before rounding = 45450.00000000000000000000
(~[slow] ~[.])=> 12:00:00PM: After truncation: 45449
```

**Comment by actual-nh** [comment]
Possibly reorder the build matrix to put the one of interest (MinGW?) first? It may not actually run first from my experience, but even if so it should run second at least. OTOH, that GCC error will likely still happen with the GCC used for the cross-compile! (`-Wno-error-strict-aliasing`?)

**Comment by BrettDong** [comment]
I start to suspect this is an aggressive compiler optimisation related issue. If there is debug outputs that print the result of the expression, then the test passes. But if I remove the debug output, but the calculations themselves remain the same, the test starts to fail.

**Comment by actual-nh** [comment]
> I start to suspect this is an aggressive compiler optimisation related issue. If there is debug outputs that print the result of the expression, then the test passes. But if I remove the debug output, but the calculations themselves remain the same, the test starts to fail.

Sounds like it. What are the compiler flags in use?

**Comment by BrettDong** [comment]
```
CCACHE_SLOPPINESS=pch_defines,time_macros ccache '/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-'g++  -DRELEASE -DCROSS_LINUX -DWIN32_LEAN_AND_MEAN -DGIT_VERSION -DTILES -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DCATCH_CONFIG_ENABLE_BENCHMARKING -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -fsigned-char -std=c++14 -MMD -MP -I/usr/lib/mxe/usr/i686-w64-mingw32.static/include/SDL2 -I/usr/lib/mxe/usr/i686-w64-mingw32.static/include/opus -DSDL_SOUND -I/usr/lib/mxe/usr/i686-w64-mingw32.static/include/libpng16 -I/usr/lib/mxe/usr/i686-w64-mingw32.static/include/SDL2 -I/usr/lib/mxe/usr/i686-w64-mingw32.static/include/freetype2 -I../src -Wno-unused-variable -Wno-sign-compare -Wno-unknown-pragmas -Wno-parentheses -MMD -MP -Wall -Wextra -Ipch -Winvalid-pch -fpch-preprocess -include tests-pch.hpp -DCATA_CATCH_PCH -c ../tests/vehicle_efficiency_test.cpp -o objwin/tiles/vehicle_efficiency_test.o
```

**Comment by actual-nh** [comment]
> Nothing special, just `-Os`
 "-Os" for g++ is the equivalent of most of -O2 plus some extras.

As a side note, I wonder how well "-Og" would do? (Does all optimizations that won't get in the way of debugging.)

**Comment by BrettDong** [comment]
All tests passing. Ready for squash-merge.

**Pull request merged**
