### PR TITLE
Decreased volume of pillows but made them a little bit heavier.json

### PR DESCRIPTION
**Pull request by Entott**
#### Summary
Bugfixes "Decreased volume of pillows but made them a little bit heavier"

#### Purpose of change
Transportation of incompressible 40 L pillows is pain in the butt.

#### Describe the solution
I made the pillows smaller purely for transportation, because you can roll enormous 40 L pillow up by hands to about 9-11 L depending on the material. 

#### Describe alternatives you've considered
I considered making an action to roll up the pillow but it "adds nothing but additional micromanagement".

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> Transportation of incompressible 40 L pillows is pain in the butt.

Sounds like a poor rationale to me. What's the problem with taking pillow in hands for transportation, like one would do IRL? Or use hauling? Or use AIM? Plenty of options.

> enormous 40 L pillow
This "enormous" pillow is just about 50x60x10 cm.

**Comment by Entott** [comment]
> Sounds like a poor rationale to me. What's the problem with taking pillow in hands for transportation, like one would do IRL? Or use hauling? Or use AIM? Plenty of options.
One would roll up pillow and put it into backpack IRL.
> This "enormous" pillow is just about 50x60x10 cm.
50x60x10 cm = 30 L
Also my default home pillows are 50x35x10 cm. I guess they are bigger in USA, idk.

**Comment by Night-Pryanik** [comment]
> One would roll up pillow and put it into backpack IRL.

Then add a roll up action to pillows. Reducing volume to arbitrary smaller volume just for the sake of convenient transportation in backpack is a bad solution.

Or add a small camp pillow which would fit nicely in a backpack.

> 50x60x10 cm = 30 L

Did you notice word "about" in my message?

I have two types of default home pillows, one is 50x70x12, the other is 70x70x13. So they are even bigger than 40 L.

**Comment by Entott** [comment]
> Then add a roll up action to pillows. Reducing volume to arbitrary smaller volume just for the sake of convenient transportation in backpack is a bad solution.

Well, the respected people in the discord came to the conclusion that adding a separate item called "rolled pillow" is even worse solution.

> I have two types of default home pillows, one is 50x70x12, the other is 70x70x13. So they are even bigger than 40 L.

Ok, so tell me how they've been delivered to you?

**Comment by GuardianDll** [comment]
> Then add a roll up action to pillows. 

Please do not, it doesn't add anything but churn, and follows the example of #55902

> Rolling the pillow will not significantly reduce its volume

I have a small 20 L pillow i use daily; i tested it right now, and i was able to compress it to approximately 8 L of volume with my bare hands

> I support the idea of adding separate camp or shitty pillow

While we can have a smaller version of pillow, i do not think it should be necessary for a simple stat tweak of existing items

**Comment by IdleSol** [comment]
So are we in favor of realism or not?

Vacuum pump + package + 5 minutes = packed pillow, with a volume 10 times smaller.

Bear, only 3 liters, but helps you fall asleep too.
https://github.com/CleverRaven/Cataclysm-DDA/blob/1b9e07666858f85c028b5d85c47af41b49f5dfe4/data/json/items/toy.json#L4

**Comment by RedMisao** [comment]
The volume reduction is specially absurd for the dakimakura. They're **supposed** to be large.

> One would roll up pillow and put it into backpack IRL.

You absolutely cannot do this manually with a dakimakura and a medium sized (35 L) backpack IRL, at the very least. Either disassemble it, compress the stuffing _somehow_, or carry it strapped.

Btw, one weighs around 3 kg, so the mass should be increased further.

**Comment by GuardianDll** [comment]
Quick google says body pillows are generally 125 L of volume, so i think halving it would be relatively dafe assumption

**Comment by Night-Pryanik** [comment]
> Ok, so tell me how they've been delivered to you?

I bought them at local supermarket. They weren't vacuum-packed, only packed in a factory package. They were large, no reason to deny it, so I transported them in hands (supermarket -> my car -> my house).

**Comment by IdleSol** [comment]
@Entott Could you please clarify exactly what the problem is?

I can only think of two possibilities:
1. Isolation Protocol mod. And the need to constantly move with a pillow (to comfortably sleep in a new place)
2. A bed in a vehicle and problems with cramped space (which is really a problem for a house on wheels).

**Comment by Entott** [comment]
> The volume reduction is specially absurd for the dakimakura. They're **supposed** to be large.

Why is this absurd? 

> You absolutely cannot do this manually with a dakimakura and a medium sized (35 L) backpack IRL, at the very least. Either disassemble it, compress the stuffing _somehow_, or carry it strapped.

You can roll up dakimakura as easy as common pillow. Should i really prove this?

> Btw, one weighs around 3 kg, so the mass should be increased further.

Cheap 60x150 cm dakimakura from Aliexpress weights 1700 g.

**Comment by Entott** [comment]
> Quick google says body pillows are generally 125 L of volume, so i think halving it would be relatively dafe assumption

50x160x15 cm bodypillow from Aliexpress is about 90 L of volume if you take into account that they are not a flat parallelepiped

**Comment by IdleSol** [comment]
Then it's not a pillow problem.

So I suggest a compromise: 
1. Keep the existing high volume pillows (would probably revise the weights, if necessary).
2. Add comments that specify the dimensions.
3. Add a small pillow, with a size of 30x40x8 = 9.6 L or 30x30x8 = 7.2 L. Include the size in the comments.

Alternative. Add a pillow container:
```
    "moves": 1000, 
    "volume_multiplier": 0.5,   
    "item_restriction": [ "pillow", "makeshift_pillow", "down_pillow" ]
```
And perhaps with a TARDIS flag?

If I understand correctly, then the container and pillow will take up half the volume ~ 20 liters. But the pillow will not provide comfort when sleeping. And it will take you 10 seconds to tamp the pillow into this container.

**Comment by Entott** [comment]
> Then it's not a pillow problem.
> 
> So I suggest a compromise:
> 
> 1. Keep the existing high volume pillows (would probably revise the weights, if necessary).
> 2. Add comments that specify the dimensions.
> 3. Add a small pillow, with a size of 30x40x8 = 9.6 L or 30x30x8 = 7.2 L. Include the size in the comments.
> 
> Alternative. Add a pillow container:
> 
> ```
>     "moves": 1000, 
>     "volume_multiplier": 0.5,   
>     "item_restriction": [ "pillow", "makeshift_pillow", "down_pillow" ]
> ```
> 
> And perhaps with a TARDIS flag?
> 
> If I understand correctly, then the container and pillow will take up half the volume ~ 20 liters. But the pillow will not provide comfort when sleeping. And it will take you 10 seconds to tamp the pillow into this container.

Why can't we all just silently agree that in the current case, the volume of the pillow is the minimum volume that the pillow can take when compressed with bare hands? This will simplify the gameplay without any major impact on realism.

**Comment by IdleSol** [comment]
Because it's not noted anywhere. And tomorrow everyone will forget about it. And the day after tomorrow there will be a new bug report that the volume is too small.

My personal opinion. (I'm not a developer). It can be done. But, add a comment directly to the json file. The cushion size is ..., that corresponds to ... liters. But when carrying it, it can be shrunk/folded/rolled to a volume of ... liters. Made to avoid doing a transformation and increasing the number of recipes/items.

So that any other person could understand why it has such parameters.

For me personally, that would be enough. Will it satisfy the development team? I don't know.

**Comment by Night-Pryanik** [comment]
Ok, leave your changes as is, but please update a description of all pillows with something like this: "The pillow is rolled for compact storage and transportation.  You will automatically unroll it when you place it for sleeping." Also you may add a comments like @IdleSol suggested, this is desirable, but not necessary.

**Comment by Entott** [comment]
I updated description of all pillows and body pillows as @Night-Pryanik suggested and made body pillows a little bit bigger.

**Comment by Night-Pryanik** [comment]
Please follow our text style: double spaces after periods and ellipses, period at the end of the sentence.

**Comment by RedMisao** [comment]
> Why is this absurd?

Because you're reducing the volume of what's supposed to be a body-sized item, which **is** unwieldy IRL, to seemingly arbitrarily low values, enough to make it not body sized, so it's easier to move around in game.

[Dakimakura from amazon](https://www.amazon.com/Full-Pillow-Vacuum-Package-150x50cm/dp/B01C6OX860?th=1). The absolute max dimensions are 59x20x7 (in) = 150x50x15 (cm) ~ 112500 cm^3 or 112 L. Which I agree is too much given it's not perfectly shaped, so the rough estimate of 90 L, even 80 L, is good. Which is close to the current volume and **four times** the value in this PR.


> You can roll up dakimakura as easy as common pillow. Should i really prove this?

It's not about just rolling the item. It's about compressing it enough so you can put it inside a backpack. Can you prove this?
This is the goal of the PR, to make it small enough to carry inside a normal backpack, no tools required right?
Of course, I'm ignoring how much time it will take for someone to do this, given the PR is just making them small at all times.
This is also ignoring how the item inside the backpack will expand enough so you could not use any other pocket.


> Cheap 60x150 cm dakimakura from Aliexpress weights 1700 g.

See link from amazon above. The **minimum** weight is 1796 g. I have the 160 cm one, so it's ~2268 g plus [the cover](https://www.amazon.com/Custom-BISPOKER-Personalized-Picture-Occasion/dp/B0DFHPD3Y4/ref=sr_1_1?dib=eyJ2IjoiMSJ9.vY6NKHJqBmUAakCqs94XJ4ZVBZUgmhsKByGi7DvbWYTGjHj071QN20LucGBJIEps.yoK43B8C6fGpN664lxO9q0jqp9ilhhvaYj0X4FuBnrc&dib_tag=se&keywords=BISPOKER&qid=1731780224&sr=8-1) at 8.8 ounces ~ 250 g, total 2518 g, give or take variation in filling.

**Comment by Entott** [comment]
> It's not about just rolling the item. It's about compressing it enough so you can put it inside a backpack. Can you prove this? This is the goal of the PR, to make it small enough to carry inside a normal backpack, no tools required right? Of course, I'm ignoring how much time it will take for someone to do this, given the PR is just making them small at all times. This is also ignoring how the item inside the backpack will expand enough so you could not use any other pocket.

I don't have dakimakura but right now i succesfully shoved 4 ~18 L pillows in my ~30 L backpack without even rolling them.
Of course, it would be much easier if you rolled them up and tied them with a rope to prevent expansion, but again, this would be an unnecessary complication of the gameplay for the sake of realism.

> See link from amazon above. The **minimum** weight is 1796 g. I have the 160 cm one, so it's ~2268 g plus [the cover](https://www.amazon.com/Custom-BISPOKER-Personalized-Picture-Occasion/dp/B0DFHPD3Y4/ref=sr_1_1?dib=eyJ2IjoiMSJ9.vY6NKHJqBmUAakCqs94XJ4ZVBZUgmhsKByGi7DvbWYTGjHj071QN20LucGBJIEps.yoK43B8C6fGpN664lxO9q0jqp9ilhhvaYj0X4FuBnrc&dib_tag=se&keywords=BISPOKER&qid=1731780224&sr=8-1) at 8.8 ounces ~ 250 g, total 2518 g, give or take variation in filling.

I have already made them weighing 2300g, I think this will be an average weight together with the pillowcase.

**Comment by RedMisao** [comment]
>I don't have dakimakura but right now i succesfully shoved 4 ~18 L pillows in my ~30 L backpack without even rolling them.
Of course, it would be much easier if you rolled them up and tied them with a rope to prevent expansion, but again, this would be an unnecessary complication of the gameplay for the sake of realism.

Yeah sorry, I not just not believe you, I just tried compressing my 160 cm long body pillow and the minimum volume I got while standing on top of it is +34 L (15x10x14 in^3). The longest side of the circumference (14 in or 35 cm) barely fits the in game backpack (40 cm), and does not fit the average backpack I wear every day.
This is **me standing on top** to try make it as small as possible, which is something you cannot do if you try to put it inside a container, as again the dakimakura are body-sized items.







Which is similar, but not the same as [this one](https://www.gosawa.com/deals/x-sports-by-chenson-black-backpack).

Regarding using a rope or tools, this is the point. It is not possible to manually compress a dakimakura to something remotely close to the vacuumed volume. You require tools to do so, and even then you have to put effort and spend time into the task.
This isn't about realism, this is turning the dakimakura item into something that's not a dakimakura item.


> I have already made them weighing 2300g, I think this will be an average weight together with the pillowcase.

My mistake, I did not see the changes. I do agree with these.

**Comment by GuardianDll** [comment]
Just to repeat, i find the average compression rate for pillows is 1/2 of it's full volume, for me decrease from 120 L to 60L is something reasonable, no need to increase it even more without providing additional tools

**Comment by Entott** [comment]
> Yeah sorry, I not just not believe you, I just tried compressing my 160 cm long body pillow and the minimum volume I got while standing on top of it is +34 L (15x10x14 in^3). The longest side of the circumference (14 in or 35 cm) barely fits the in game backpack (40 cm), and does not fit the average backpack I wear every day. This is **me standing on top** to try make it as small as possible, which is something you cannot do if you try to put it inside a container, as again the dakimakura are body-sized items.

Judging by the photos, your dakimakura is denser than the cheap ones I saw, which is also indicated by its greater weight.
However, you managed to compress it more than 2 times without any tools. Doesn't that prove my point?
Also, let's not forget that there are smaller dakimakura sizes available, down to 100x35. Why do we assume that all the body pillows in the game are expensive, dense, and large, and not small and cheap?

IMG_20241117_142753
So here is my ~30 L backpack with 4 shoved without rolling pillows in it.

IMG_20241117_142841

IMG_20241117_142943
They are different, smallest 1 is ~14 L ~950 g, biggest is ~22 L ~1500 g.
Sorry for shit photos, i'm too lazy to make good ones. 

> Regarding using a rope or tools, this is the point. It is not possible to manually compress a dakimakura to something remotely close to the vacuumed volume. You require tools to do so, and even then you have to put effort and spend time into the task. This isn't about realism, this is turning the dakimakura item into something that's not a dakimakura item.

So, if I understand correctly, you insist on the need to create a crafting recipe for, say, a "rolled body pillow" with the necessary tools and rope?

**Comment by Entott** [comment]
> Just to repeat, i find the average compression rate for pillows is 1/2 of it's full volume, for me decrease from 120 L to 60L is something reasonable, no need to increase it even more without providing additional tools

The same question as the previous comment arises. 120 L is almost the largest dakimakura in real life, the smallest is 53 L. Do we assume that all body pillows in the game are dense and large?

**Comment by RedMisao** [comment]
> Judging by the photos, your dakimakura is denser than the cheap ones I saw, which is also indicated by its greater weight.

My dakimakura is the 160x50cm from the amazon store above, no further modifications done to it.


> However, you managed to compress it more than 2 times without any tools. Doesn't that prove my point?

This **disproves** your point that you can fit one inside a standard backpack. I had to stand on top of it, which makes me unable to handle it in any way without plenty of effort to keep it shaped like that. And even then the diameter was larger than my IRL backpack, barely smaller than the in game `backpack`.


> Also, let's not forget that there are smaller dakimakura sizes available, down to 100x35. Why do we assume that all the body pillows in the game are expensive, dense, and large, and not small and cheap?

No, this is just wrong. The standard sizes are 160x50cm, or 150x50cm for shipping without extra fees. Mine is also what would be considered a bootleg, unless you can access that store from Japan (I don't know, I don't live there). You can easily prove this by searching for "body pillow covers" and see the standard sizes match either of those dimensions. The cheapest materials are not elastic, so when the dakimakura is covered by those it will be slightly compressed and stiffer.

----

Regarding the pillows, are you sure those are 20 L ? My personal standard point of reference for large volumes are those blue water bottles used on dispensers (20 L - 5 gallons). My estimate is that the pillows from your pictures are 10 - 15 L or less.
Even then, the pillows are not fitting inside the backpack, but sticking out.

> So, if I understand correctly, you insist on the need to create a crafting recipe for, say, a "rolled body pillow" with the necessary tools and rope?
> The same question as the previous comment arises. 120 L is almost the largest dakimakura in real life, the smallest is 53 L. Do we assume that all body pillows in the game are dense and large?

No, that's not it. My point is that a body-sized item which is unwieldy to be moved around, cannot be sucessfully handled in such a way to put inside a backpack for convenience. I mention tools not because that's what should happen in game, but to show you that it is not possible to do it manually. I'm in agreement with GuardianDll's pointing out pillows being ~50% of its total volume, which _still_ sets the dakimakura into the 60 - 40 L range.

**Comment by Entott** [comment]
> No, this is just wrong. The standard sizes are 160x50cm, or 150x50cm for shipping without extra fees. Mine is also what would be considered a bootleg, unless you can access that store from Japan (I don't know, I don't live there). You can easily prove this by searching for "body pillow covers" and see the standard sizes match either of those dimensions. The cheapest materials are not elastic, so when the dakimakura is covered by those it will be slightly compressed and stiffer.

It is true that on Amazon I found mostly 20x54 inches size, but almost every lot from Aliexpress indicates sizes from 100x34 cm to 180x60 cm. Both for [body pillows](https://sl.aliexpress.ru/p?key=eDrorG7) and [body pillow cases](https://sl.aliexpress.ru/p?key=ddrortX). 
So we don't count Aliexpress?

> Regarding the pillows, are you sure those are 20 L ? My personal standard point of reference for large volumes are those blue water bottles used on dispensers (20 L - 5 gallons). My estimate is that the pillows from your pictures are 10 - 15 L or less. Even then, the pillows are not fitting inside the backpack, but sticking out.

Yep. BR is 52x12x35 cm = 21,8L, TR is 52x11x35 cm = 20 L ,BR is 32x42x12 cm = 16 L BL is 50x25x11 = 14 L. So it is total 70 L of volume inside 30 L backpack without any rolling. And they are fitting inside when you shove them in and close the zipper.

**Comment by GuardianDll** [comment]
We count whatever option is most popular, and for me the option with 160x50 seems to be the one

**Comment by Entott** [comment]
> We count whatever option is most popular, and for me the option with 160x50 seems to be the one

Alright, i'll change the volume to 50 L then, so it can at least fit in a hiking backpack.

**Pull request merged**
