### PR TITLE
Allow talking to pets

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
none

#### Purpose of change
Handle second part of #51992
Allow talking to pet

#### Describe alternatives you've considered
Doing the first part of #51992 as well.  Turns out its a lot harder than this was.

#### Testing
Added this line to mon_cat in json and then started a cat dude. 
```
"chat_topics":["TALK_CITY_COP_NEWS","TALK_CITY_COP"],
```

### CODE REVIEW

**Comment by Entity-y** [comment]
So would this allow me to yell a sentence containing my pet's name to have it come to me?

**Comment by Ramza13** [comment]
> 
> 
> So would this allow me to yell a sentence containing my pet's name to have it come to me?

Nope

**Comment by Ezsk** [comment]
Interesting feature, but it seems to crash on TALK_DONE.

**Comment by Ramza13** [comment]
> 
> 
> Interesting feature, but it seems to crash on TALK_DONE.

Ha so just tested this and I'm getting a crash on starting the conversation not TALK_DONE.  That said by chance my PR #52717 should fix the crash I am seeing and hopefully the issue you are having as well.

**Comment by Ramza13** [comment]
> 
> 
> Interesting feature, but it seems to crash on TALK_DONE.

So can you still cause a crash on TALK_DONE with the latest experimental?  If so I'd love some details to fix it.

**Pull request merged**
