### PR TITLE
Little Monsters - Feral and Civilian Children

### PR DESCRIPTION
**Pull request by TheSaddestGoomba**
#### Summary
Content "Adds two new child civilians and a child feral"

#### Purpose of change
We have child zombies, and a number of upgrades, but there are no child ferals or civilians.

#### Describe the solution
Add three new monsters:
1. Absent Adolescent - young version of the Petrified Person; despondent, tucked close in on self, thousand yard stare
2. Careless Child - young version of the Panicked Person; hiding in make believe, plays gleefully and insistently
3. Feral Child - child version of the typical Feral Human, no ranged attack, only melee attacks with an improvised stabbing implement (small knife, scissors, etc.)

#### Describe alternatives you've considered
- More complicated variants of the feral child. A tattler that runs to get help and brings the horde to you. A ranged 'menace' that avoids melee and can leave simple dropped traps like caltrops and marbles.
- Due to the possibly sensitive nature of the content, I considered posting a discussion issue prior to this PR. Those don't seem to get much traffic these days and I think it would be easier to have a discussion with something to show, hence the PR. I also don't believe that what I have here goes beyond the bounds of good taste. These are certainly no wretched hatcheries.

#### Testing
Very little so far. Will likely play through a few school starts as my first tests.

### CODE REVIEW

**Comment by Maleclypse** [comment]
I appreciate that this seems like it may be an empty design space, but it is empty by design.  The dev team does not want to get into the living child death space.  If NPC children were ever implemented they would have a "run and hide" feature that prevents players from killing them.  I want to prevent you from putting more work into this as it won't be accepted for merging.  You've done good work on other PRs so this isn't an indictment of you or your work.  Again I apologize for this but I checked with others before doing this.

**Comment by I-am-Erk** [comment]
What maleclypse said. I'll try to add a faq thing about this, you did nothing obviously wrong. This just goes into an edgy space I think we should steer clear of.

**Comment by TheSaddestGoomba** [comment]
That is disappointing but not surprising. I accepted there was a chance this would be cut before I started it, so no worries.

Definitely add something to the frequent suggestions because it's not obvious why this design space is left empty. It seemed like it was just open because no one had got to it yet. Also, the existence of some other things like the aforementioned wretched hatchery and maternity wards full of zombie newborns set an unclear standard.

Personally I would rather just not have NPC children than recreate Bethesda's 'essential NPC/immortal children' weirdness.

**Comment by I-am-Erk** [comment]
Well, while I have an idea how they'd be implemented, it's worth noting that it's still not something I've been in any hurry to try out.

**Pull request closed without merging**
