### PR TITLE
make the game faster when player sleep near the tree

### LINKED ISSUE #73552: Trying to fall asleep next to a tree is incredibly slow, but waiting is not
### Describe the bug

There are no nearby monsters either.

I ran the game in gdb to see what it was doing:

```
Thread 1 (Thread 0x7ffff748f7c0 (LWP 1664080) "cataclysm-tiles"):
#0  0x0000555555e8816c in trig_dist () at src/line.h:159
No locals.
#1  rl_dist () at src/line.h:184
No locals.
#2  0x0000555556b324d3 in cast_horizontal_zlight_segment<1, 0, 0, 1, 1, float, &(sight_calc(float const&, float const&, int const&)), &(sight_check(float const&, float const&)), &(accumulate_transparency(float const&, float const&, int const&))> () at src/shadowcasting.cpp:298
No locals.
#3  0x0000555556b371ac in cast_zlight<float, &(sight_calc(float const&, float const&, int const&)), &(sight_check(float const&, float const&)), &(accumulate_transparency(float const&, float const&, int const&))> () at src/shadowcasting.cpp:607
No locals.
#4  0x000055555655ef65 in map::build_seen_cache () at src/lightmap.cpp:1019
No locals.
#5  0x00005555565d5b27 in map::build_map_cache () at src/map.cpp:9591
No locals.
#6  0x00005555561ca439 in do_turn () at src/do_turn.cpp:655
No locals.
#7  0x0000555555ccb9df in main () at src/main.cpp:868
```

Weird. I tried sleeping outside of the improvised shelter but no dice. Wild guess: treetops? I know these would do z-level shading things. And indeed going just a bit west into the open makes this issue go away.

### Attach save file

~~[Innawoods-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15225886/Innawoods-trimmed.tar.gz)~~

Reproducible by trying to sleep adjacent to a tree.

### Steps to reproduce

(While the save is obviously an innawoods one, I highly doubt this is mod specific)

1. Load save.
2. Try to sleep.
3. The progress is excruciating slow.
4. Cancel and see if waiting is faster.
5. Waiting is indeed blazingly fast.
6. Go a bit west, away from trees.
7. Try sleeping again on the floor.
8. It is fast.

### Expected behavior

Falling asleep progresses as fast as waiting under tree tops.

CC @PatrikLundell since you did a lot of tree tops related things and might know whats going on here.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-05-06-1236 3428b61 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
fix #73552
#### Describe the solution
Apply suggested fix 
#### Testing
Compiled, slept afar from tree
image
slept near the tree
image
booted up unedited version of the game, sleept near the tree, dropped it because it was like 1:1 real time to game time ratio
#### Additional context
Pure magic to me ngl

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I think the intention with the cache weirdness was to ensure that vision radius changed as soon as the player crouched or went prone next to a piece of cover, as these actions don't take any time. It would be inappropriate for them to only update one second later after the player passed a turn kr something.

I don't have time to compile your PR to test it but you may want to make sure that's still working as intended.

**Comment by fairyarmadillo** [comment]
Thanks for checking for me. That's a separate issue then, and not something that matters for this PR.

I swear it used to happen on the same turn.

**Comment by IdleSol** [comment]
You may have already seen it. The topic offered another solution to the problem. More precisely, they added a condition for checking.

**Comment by GuardianDll** [comment]
actually i did miss the second Ren suggestion, i'll check it now

**Comment by IdleSol** [comment]
You update the value `previous_move_mode` 21+ times per game turn.

**Comment by GuardianDll** [comment]
i'll compile and test it later

**Comment by GuardianDll** [comment]
@RenechCDDA nope, third attempt do not resolve the bug either
image

**Comment by RenechCDDA** [comment]
> @RenechCDDA nope, third attempt do not resolve the bug either

Here's what I get on master:
image


and after applying the patch:
image

**Comment by RenechCDDA** [comment]
Profiling before:
image

And after:
image


And you might think our additions inside map::build_vision_transparency_cache are themselves a problem. Nope! It's all the memcpy.
image

**Comment by GuardianDll** [comment]
Do you mean something is wrong with my test method or compiling?

**Comment by RenechCDDA** [comment]
I would absolutely ask you to double-check what code you compiled, maybe even do a fresh rebuild to be 200% sure there's no compiler junk going on.

**Comment by GuardianDll** [comment]
After complete rebuild confirmed the suggestion worsk as expected
image

**Comment by I-am-Erk** [comment]
This is the one we discussed on discord right? Kevin didn't seem to think it was a problem, and it's passing the test, so let's see what happen, and if someone set up us the bomb.

**Pull request merged**
