### PR TITLE
Fungal Insects & fungal zombie fixes.

### PR DESCRIPTION
**Pull request by zdlpoppa**
#### Summary
Content "Add's more fungal insect monsters, fixes bugs I forgot in last PR."

#### Purpose of change
Always wanted to see some annoying fungal wasps to mess with players more; Decided to combine this PR with a quick bugfix PR for some mistakes I missed.

#### Describe the solution
Adds more monsters. Saw I missed some evolutions and butcher changes, which will be changed by this PR.

#### Describe alternatives you've considered
Not adding fungal wasps and bees.

#### Testing
None yet.

#### Additional context
Feedback on what should have fungal variants and how I should scale their stats should be appreciated, because I'm mostly going off of just lowering their base stats. (also, a possible addition of fungal flesh only consumable by specific monsters/mutations, I.E triffids, or ants, and the mycus/rat? mutations.)

### CODE REVIEW

**Comment by ADekema** [comment]
A few thoughts:

1. Why do the wasps have nobreath? They are still living creatures that need oxygen. Being parasiticed by fungus doesn't change that.
2. Why are they still hard to shoot? This makes sense for normal gaint wasps who fly around but it doesn't for fungal wasps if they can't fly.
3. Why do they get the poison flag? Every other fungalized creature keep thier original butchering results. Feral humans and other gaint insect are still edible when infected with Fungus.

**Comment by zdlpoppa** [comment]
> A few thoughts:
> 
> 1. Why do the wasps have nobreath? They are still living creatures that need oxygen. Being parasiticed by fungus doesn't change that.
> 2. Why are they still hard to shoot? This makes sense for normal gaint wasps who fly around but it doesn't for fungal wasps if they can't fly.
> 3. Why do they get the poison flag? Every other fungalized creature keep thier original butchering results. Feral humans and other gaint insect are still edible when infected with Fungus.

1: anything infected by fungus as such is essentially dead, They aren't alive by their own volition. This can imply multiple organs stopping or being punctured, lungs collapsing, but still having the host move on the command of the infestation.
2: hard to shoot is something i'm looking to remove soon, a small oversight on my part.
3: similar to the fungus ant, it gains the poison flag as the flesh is fainted. Other ferals and insects being edible still could've been an oversight, although I may have to check

**Comment by Karol1223** [comment]
Fungal infection absolutely does not kill the host in the... uh, traditional sense. Look at current fungalized feral humans. Something infected with the mycus doesn't suddenly become a zombie equivalent, so wasps becoming tainted and not needing to breathe does not make sense.

**Comment by fairyarmadillo** [comment]
> > A few thoughts:
> > 
> > 1. Why do the wasps have nobreath? They are still living creatures that need oxygen. Being parasiticed by fungus doesn't change that.
> > 2. Why are they still hard to shoot? This makes sense for normal gaint wasps who fly around but it doesn't for fungal wasps if they can't fly.
> > 3. Why do they get the poison flag? Every other fungalized creature keep thier original butchering results. Feral humans and other gaint insect are still edible when infected with Fungus.
> 
> 1: anything infected by fungus as such is essentially dead, They aren't alive by their own volition. This can imply multiple organs stopping or being punctured, lungs collapsing, but still having the host move on the command of the infestation. 2: hard to shoot is something i'm looking to remove soon, a small oversight on my part. 3: similar to the fungus ant, it gains the poison flag as the flesh is fainted. Other ferals and insects being edible still could've been an oversight, although I may have to check

This is incorrect. You're likely confused because fungal zombies exist. Fungal zombies are people who died and then became zombified, so their flesh is still tainted and they still don't need to breathe, because that's how things worked before the Mycus got them. Insects can't zombify, so if they fungalize they need to do it while still being alive.

Fungal monsters probably should not be edible as the mycus itself is not normally edible, but that's a separate issue.

**Comment by zdlpoppa** [comment]
After seeing the comments, I do agree that having no_breathe on the wasps doesn't make much sense, but I do feel that any fungal infected monsters shouldn't have consumable flesh; eating regular mold is a horrible idea, mycus mold is even worse. Ideas are still completely on the table though.

**Comment by fairyarmadillo** [comment]
> After seeing the comments, I do agree that having no_breathe on the wasps doesn't make much sense, but I do feel that any fungal infected monsters shouldn't have consumable flesh; eating regular mold is a horrible idea, mycus mold is even worse. Ideas are still completely on the table though.

Your best options are
1) Leave it as normal insect flesh for parity with existing monsters, and make a note in the PR that someone should get around to fixing this sometime
2) Make a new type of meat called fungal_flesh which has a new flag similar to POISON that makes it cause injury and sickness if eaten, then make this meat poisonous to everyone except mutants who specialize in eating fungus. IMO this should be insect and plant, as ants farm mold to eat and plants love to eat food broken down by fungus.

#2 is a tall order if you don't know C++. If you do #1, I'll be happy to add #2 to my short list of things to do.

**Comment by fairyarmadillo** [comment]
> 2 is most definitely what I'd want to do, but I have no C++ coding ability, so option 1 is the one I have to go with currently. I do really like the idea of flesh only consumable to some due to it's fungal nature. I'll make a note of it!

If this gets merged I'll make it a priority to handle it on my end. Plant has a lot of trouble feeding itself and this seems like a solid way to go.

**Comment by ADekema** [comment]
Hate to nage again but I just saw that the bleedrate of the wasps is 0. Doesn´t the same thing we went over with ¨fungal wasps need to breath becease still functional vitals and organs¨ also apply to the circulatory system? So fungal wasps should bleed just like normal wasps?

**Comment by zdlpoppa** [comment]
> Hate to nage again but I just saw that the bleedrate of the wasps is 0. Doesn´t the same thing we went over with ¨fungal wasps need to breath becease still functional vitals and organs¨ also apply to the circulatory system? So fungal wasps should bleed just like normal wasps? Doesn´t the same also go for standart fungal zombies?

Any feral (or human) monster will bleed. Any other type of monster won't. I'm sticking to what's already set in code, so they don't bleed.

**Pull request merged**
