### PR TITLE
[Magiclysm] Added Technomancer mana-toolbar to the 'Fior Di Battaglia' martial art.

### LINKED ISSUE #53923: [Magiclysm] upgrading Technomancer Toolar to Technomancer Mana-Toolbar disables martial art
### Describe the bug

Technomancer Toolbar can be used in Fior Di Battaglia, but the mana-toolbar cannot. Is this another oversight or does the style not translate well after the electronic is attached ?

### Steps to reproduce

check recipes

### Expected behavior

Preferably both qualify for FDB :)

### Screenshots

_No response_

### Versions and configuration

version 524a7db
build 2021-12-31-0620

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Mods "Added Technomancer mana-toolbar to the 'Fior Di Battaglia' martial art."

#### Purpose of change
Fixes #53923

#### Describe the solution
Added the weapon category `HOOKING_WEAPONS` to both the Technomancer toolbar and Technomancer mana-toolbar.

#### Describe alternatives you've considered
Adding the mana-toolbar to the extended list of weapons for 'Fior Di Battaglia' in `data\mods\Magiclysm\martialarts`. once weapon categories are finished this file should ideally become obsolete.

Having the weapons inherit categories from vanilla weapons. I didn't do this because there isn't a great vanilla equivalent of the items. The closest is the Halligan bar, which notably lacks the `HOOKING_WEAPONS` category and is not included in 'Fior Di Battaglia' so inheriting from it seems like a bad idea. I could add the `HOOKING_WEAPONS` category to the Halligan bar, but then I'm suddenly making fairly impactful design decisions about the base game, which isn't my goal.

#### Testing
1. start a new game
2. unlock all martial arts via debug menu
3. see if both the toolbar and mana-toolbar are listed for 'Fior Di Battaglia'

#### Additional context
The base Technomancer toolbar is already used in 'Fior Di Battaglia', so this effectively only adds the mana-toolbar

### CODE REVIEW

**Comment by Maleclypse** [comment]
I think it would be better to add hooking weapon category to both technomancer toolbars.

**Comment by catdach** [comment]
> I think it would be better to add hooking weapon category to both technomancer toolbars.

That is in fact what I did, sorry If that wasn't clear.

**Comment by Maleclypse** [comment]
> > I think it would be better to add hooking weapon category to both technomancer toolbars.
> 
> That is in fact what I did, sorry If that wasn't clear.

Nope I just read it wrong.  Thank you! :)

**Comment by Maleclypse** [comment]
I think you are going to need to go into the test that uses the technomancer toolbar and change the first number into the second.  9.3685617447 == Approx( 11.7113554632 )

**Comment by Maleclypse** [comment]
I don't think either of these test failures are your fault, but I need to let someone with more experience check.

**Pull request merged**
