### PR TITLE
Fix for cooking oil.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
It's supposed to be two charges per 250 ml.

### CODE REVIEW

**Comment by mugling** [comment]
It would be simpler if most comestibles became `charges 1` unless there is a good gameplay reason of which I'm not aware? Cooking oil is not a difficult resource to obtain and indeed in most recipes is reusable.

**Comment by Rivet-the-Zombie** [comment]
The reason for stuff like this is because we can't use a portion of a charge, and 250 ml is way more than we need for most recipes.

**Comment by mugling** [comment]
What recipes actually consume cooking oil as opposed to just require it?

**Comment by Coolthulhu** [comment]
Biscuits, johnnycakes and I think corn version of those.

Cooking oil had charges halved to bring it in line with lard and tallow. If cooking oil is to be 2 charges per volume, lard and tallow should be like that too.

**Comment by mugling** [comment]
> Biscuits, johnnycakes and I think corn version of those.

We can rescale those recipes if necessary

> Cooking oil had charges halved to bring it in line

Yes indeed this is one of the reasons for wanting to avoid specifying `charges` unless unavoidable

**Comment by Coolthulhu** [comment]
> We can rescale those recipes if necessary

They're already producing a lot of output. Single craft of biscuits is more than 100 nutrition.

**Comment by Rivet-the-Zombie** [comment]
>They're already producing a lot of output. Single craft of biscuits is more than 100 nutrition.

Stuff like biscuits tend to be really calorie-dense, with most averaging around 200 calories per serving.

**Comment by mugling** [comment]
Perhaps the goal here should to be adjust `charges` and other properties for items that require cooking oil?

**Comment by kevingranade** [comment]
I'm unclear why you're considering multiple charges for comestibles a bad
thing. Any comestible that is singular in nature, but consists of more than
one serving of food is modelled as having multiple charges.  The
alternative is to define everything in terms of portions and have a
mechanism to keep the seperate portion items together, but that seems
unecessary.

**Comment by Cat09** [comment]
cooking is actually a very complicated and precise process, attempts to virtualize it too much will probably seem really odd in practice. this is a good example, most things really don't use much oil in their recepies, and otherwise you don't use much (a 750 ml bottle lasts me a very very long time)
It really doesn't directly apply to _this_ PR, but I'd just as soon use flat ml amounts when it comes to liquids in all cases.

**Comment by Coolthulhu** [comment]
I'm not against 2 charges per volume of unit, but "energy" of cooking oil should match lard and tallow, since they're all almost pure fats.

**Comment by Rivet-the-Zombie** [comment]
Meaning matching nutrition/calories?

**Comment by Coolthulhu** [comment]
Lard and tallow aren't too useful as direct food, so it would be better to match their recipes instead.

That is, if biscuits use 0.5 volume of cooking oil, they should also use 0.5 volume of lard.

**Comment by Rivet-the-Zombie** [comment]
That would be a lot of alterations, but I can look into it tonight.

**Pull request closed without merging**
