### PR TITLE
Add Electric Chainsaw Lajatang

### PR DESCRIPTION
**Pull request by Theundyingcode**
#### Summary
```SUMMARY: Content "Add electric chainsaw lajatang"```

#### Purpose of change

We have electric chainsaws so why can't I make an electric chainsaw lajatang?

#### Describe the solution

Add it.

#### Describe alternatives you've considered

stick it in my personal extra items mod but, I think everyone deserves to enjoy this.

#### Additional context

There is literally no difference between chainsaws and electric chainsaws besides their ids and ammo types. (I'm 90% sure the electric chainsaw in the garage is lighter than that but MEH) As such, the electric chainsaw lajatang is basically a copy paste of the gas version.

Looking at combat chainsaw next

### CODE REVIEW

**Comment by Inglonias** [comment]
This is stupid, but I can't think of any reason not to let you do this, so...

**Comment by Theundyingcode** [comment]
> This is stupid, but I can't think of any reason not to let you do this 

That my good friend is among the highest of praises.

**Comment by ZhilkinSerg** [comment]
You've missed two things:

- name of iuse action should be added to `item_actions.json`;
- mapping of iuse action should be mapped to C++-function in `item_factor.cpp`.

I've did this for you in this PR.

**Comment by ZhilkinSerg** [comment]
Also ammo type is `battery`, not `batteries`.

**Comment by ZhilkinSerg** [comment]
Also `max_charges` was set to invalid value of `00` for `_off` version, instead of `800` (as in `_on` version).

**Comment by ZhilkinSerg** [comment]
Also colon was missing in summary line.

**Comment by Theundyingcode** [comment]
thanks

**Pull request merged**
