### PR TITLE
Remove old compiler workaround in src/compatibility.h

### LINKED ISSUE #36370: compatability.h needs review
**Is your feature request related to a problem? Please describe.**  

"compatability.h" is a file made to fix GCC compiler versions  
before 4.8 due to flag (MinGW) and newlib (Cygwin) issues  
(std::to_string was not provided)

As current minimal GCC version supported is 5.3, most code  
in the file regarding MinGW is not used.

After extensive googling I have found several mentions of  
CygWin not giving the error with `-std=c++11` and `-std=c++14`  
flags. (later of which is what is used in this codebase)

**Describe the solution you'd like**  

Some testing needed whether whole file, parts of it or at least Cygwin build  
flag can be deleted.

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Build "Remove old compiler workaround in src/compatibility.h"

#### Purpose of change
Closes #36370. `src/compatibility.h` is a workaround to old GCC prior to 4.8 lacking `std::to_string` and `std::advance`. But now the minimum supported version is GCC 5.3 (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILER_SUPPORT.md), so this workaround is no longer needed.

#### Describe the solution
* First (930a939) migrate all references to proxy function `to_string()` defined in `src/compatibility.h` to real `std::to_string`
* Then (84f51d7) remove `src/compatibility.h`

#### Testing
Compiles locally for me. <del>Wait and see if this compiles on all CI environments as well.</del>

So far GitHub Action and Travis CI checks have all passed but AppVeyor failed because of time out and there isn't a rebuild button on AppVeyor.

### CODE REVIEW

**Comment by BrettDong** [comment]
Doing a force-push to retrigger timed-out AppVeyor build.

**Comment by BrettDong** [comment]
AppVeyor still times out.

**Comment by actual-nh** [comment]
@ZhilkinSerg, @BrettDong: Should I put up an issue for the Appveyor builds timing out?

**Comment by ZhilkinSerg** [comment]
We need a branch that we can use to refresh vcpkg package cache, we can ask Appveyor to increase timeout to 90 minutes (I've seen they do that on request), we can disable building and/or tests.

Maybe think of a way of storing vcpkg cache somewhere or use a specific vcpkg commit, so we won't need to rebuild packages most of the time.

**Pull request merged**
