### PR TITLE
clear_npcs in monster test

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: None

#### Details
After #30051 `clear_creatures` no longer clears NPCs.  Add a call to do that in these tests where it is needed.

Also, in clear_map, remove NPCs before vehicles to avoid unboarding errors (as already hinted at in `npc_test.cpp`).
    
Simplify `npc_test` to use the new improved `clear_map`.
   
#### Additional context
Verify that the Mingw tests pass before merging.

Ultimately, this is all a workaround for the fact that vehicle detaching does not properly mark NPCs as not in the vehicle.  That should also be fixed.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
The tests are still failing, but due to another probably unrelated issue.

**Comment by jbytheway** [comment]
I think it's still related.  Will keep investigating.

**Comment by jbytheway** [comment]
I managed to reproduce a similar error locally and fix that.  We'll see if this helps on Mingw...

**Comment by kevingranade** [comment]
Looks like that did it, woo

**Comment by jbytheway** [comment]
Finally worked.  In the end I had to fix the underlying issue, not just patch over it.

It's now the case that any vehicle that is detached from the map will have all passengers unboarded.  I haven't investigated fully to see whether that may have any unfortunate side-effects.  For example, it might cause NPCs to leave vehicles when the map section is unloaded.

**Comment by ZhilkinSerg** [comment]
I've still getting this locally (could be unrelated though):

image

**Comment by jbytheway** [comment]
It's probably related.  Can you post the full output with `-d yes`?

**Comment by jbytheway** [comment]
Never mind, I've seen the same error on another PR.  I think this change never fixed it, we just got lucky this one time.  Harrumph.

**Pull request merged**
