### PR TITLE
Even more SI unit spacing adjustments

### PR DESCRIPTION
**Pull request by Milopetilo**
#### Summary
None

#### Purpose of change
Continuing on from #70905.

#### Describe the solution
Adjusting the spaces and units in the json files. Avoiding changing non user-facing strings, also not adding spaces to ammunition. Also removed a newline that was unnecessary.

#### Testing
Went in-game, noticed my changes took place.

#### Additional context
Put the units in the ammo can descriptions in full capitalization since most pictures I found online were like that.

### CODE REVIEW

**Comment by harakka** [comment]
What is the point of changing the stuff that isn't shown to the user? That just looks like churn.

**Comment by Milopetilo** [comment]
I assume you're referring to the changes i make to spacing in `volume`, and I'm doing those mostly for consistency. I don't think those values are ever shown directly to the user so I can stop changing those if that's what would be preferred.

**Comment by ehughsbaird** [comment]
They won't ever be shown (the values they represent will be), and imo shouldn't be changed.

**Comment by Milopetilo** [comment]
I won't be changing that in future PRs then.

**Comment by Maleclypse** [comment]
> They won't ever be shown (the values they represent will be), and imo shouldn't be changed.

Does our json reader not require them to look a certain way? Does it treat 200L the same as 200 L?

**Comment by ehughsbaird** [comment]
There can be 0 more spaces between the number and the unit, it's permissive in that regard.

**Pull request merged**
