### PR TITLE
Fix eternal season for scenarios with season flags

### LINKED ISSUE #18379: Eternal season breaks winter/summer start tags
Enabling eternal season causes the starting season to always be Spring, regardless of if Sheltered, The Next Summer, or Ambush scenarios are selected.

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #18379.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Question. In what way will this be fixed? Will the selected option for eternal season override the scenario season, or will it forcibly set the season to eternally be the scenario starting season?

**Comment by sethsimon** [comment]
The scenario season will be used if it has one. Otherwise the `Initial Season` in the world settings is used.

**Comment by DangerNoodle** [comment]
Ah, seems like a reasonable solution.

**Comment by Coolthulhu** [comment]
Initial season settings are pretty volatile. How does the calendar start offset differ from initial season at the moment?

**Comment by sethsimon** [comment]
`calendar::start` is used for calculating the number of days adventured (as opposed to survived), and in `monster::try_upgrade`. `calendar::initial_season` has only one usage- in `calendar::sync`:
```
if( eternal_season ) {
    season = initial_season;
} else {
    season = season_type( turn_number / DAYS( season_length() ) % 4 )
}
```

Now that you bring it up, I notice that `initial_season` is a useless variable since `season_type( calendar::start.get_turn() ///snip` can be used instead.

**Comment by Coolthulhu** [comment]
I got it to break:
* Start "next summer"
* Turn on eternal season
* Change time to autumn
* Season changes to autumn
* Save
* Load
* Still autumn

**Comment by sethsimon** [comment]
Good find. That happens because changing it midgame wouldn't change `calendar::eternal_season`, so I did away with that variable and call `get_world_option` instead.

Also, I found and fixed a crash caused by starting an eternal season game in summer and repeatedly setting the season to spring. Each time you do that, it subtracts 14 days, but the season remains the same. So you can do it without limit and make `calendar::turn` negative.

**Comment by Coolthulhu** [comment]
> That happens because changing it midgame wouldn't change calendar::eternal_season, so I did away with that variable and call get_world_option instead.

That bug was better than the solution:
The function you changed (`calendar::sync`) is called a lot when accumulating food rot, funnels and solars. Acquiring value of an option isn't all that cheap - it's fine once per turn, but we're talking about 1000s of times after a section of the world loads.

**Comment by Coolthulhu** [comment]
Other than that, it works.

**Comment by Coolthulhu** [comment]
Needs that sync updated or reverted.

**Comment by sethsimon** [comment]
The change does cause a performance penalty (units are ms per 5,000,000 calls to `calendar::increment`, with 3 samples, using the test case 
[cal.cpp.git_wont_let_me_attach_cpp_files.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/843071/cal.cpp.git_wont_let_me_attach_cpp_files.txt)):

master | 71781ec | after making "ETERNAL_SEASON" static const | after making "SEASON_LENGTH" static const |
---------- | ---------- | ------------------------------------------------------------ | ----------------------------------------
| 3105/2604/2588 | 6186/5393/6373 | 4248/4204/5393 | 3905/3725/3789 |

But I'm not sure that it's a major problem. According to a flat profile with gprof, it accounts for 0.03% of the total time, even after dropping a couple thousand charges of bread nearby.

**Comment by Coolthulhu** [comment]
> According to a flat profile with gprof, it accounts for 0.03% of the total time, even after dropping a couple thousand charges of bread nearby.

Spawn a bunch of electric vehicles and drop few charges of bread, teleport away, accelerate time by 10 years and then walk into the area.
If that doesn't cause a hiccup, it should be fine.

**Comment by sethsimon** [comment]
With 18 solar cars, 8k charges of bread, 4k charges of cornbread, 6k charges of flatbread, 2k charges of sweet bread, and 10k charges of wastebread, it took:
2 seconds for 0 years
3 seconds for 10 years
14 seconds for 100 years
36 seconds for 2200 years.

On a related note, setting the year insanely high can make the calendar negative and cause a crash.

**Comment by Coolthulhu** [comment]
Charges don't matter - each bread stack is treated as one item.

Looks safe enough, though.

**Pull request merged**
