### PR TITLE
[CR] Adjust coverage & encumbrance values of various boots

### PR DESCRIPTION
**Pull request by illi-kun**
as continue of discussion started in #14534.

90% coverage:
- (regular leather) boots (was 100%, encumbrance increased from 5 to 10, has `VARSIZE` flag)
- fur boots (was 100%, unchanged enc 20, has `VARSIZE` flag)
- steeltoed boots (was 100%, unchanged enc 15, has `VARSIZE` flag)
- winter boots (was 100%, encumbrance increased from 15 to 20, has `VARSIZE` flag)

95% coverage:
- hiking boots (unchanged coverage, encumbrance increased from 5 to 8, has `VARSIZE` flag)
- western boots (was 100%, encumbrance reduced from 40 to 22, has `VARSIZE` flag)
- chitinous boots (unchanged coverage, encumbrance increased from 10 to 12)
- bone armor boots (unchanged coverage, unchanged enc 15, has `VARSIZE` flag)
- leather armor boots (was 90%, unchanged enc 15, has `VARSIZE` flag)
- motorcycle boots (was 100%, unchanged enc 20, has `VARSIZE` flag)

100% coverage:
- combat boots (unchanged coverage, enc increased from 15 to 18, has `VARSIZE` flag)
- rubber boots (unchanged coverage, enc increased from 20 to 30)
- turnout boots (unchanged coverage, enc increased from 30 to 35, has `VARSIZE` flag)
- armored boots (unchanged coverage, enc increased from 20 to 35, has `VARSIZE` flag)
- winter survivor boot (unchanged coverage, unchanged enc = 37, has `VARSIZE` flag)
- survivor fireboots (unchanged coverage, enc increased from 30 to 35, has `VARSIZE` flag)
- survivor wetsuit boots (unchanged coverage, enc increased from 25 to 32, has `VARSIZE` flag)
- light survivor boots (unchanged coverage, enc increased from 13 to 15, has `VARSIZE` flag)
- survivor boots (unchanged coverage, enc increased from 20 to 24, has `VARSIZE` flag)
- heavy survivor boots (unchanged coverage, enc increased from 30 to 35, has `VARSIZE` flag)
- XL survivor boots (unchanged coverage, enc increased from 30 to 35, has `VARSIZE` flag)

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. Though personally I have no opinion either way regarding the coverage changes, as I tend to feel the effects of low coverage on legs, arms, torso and head far more often.

**Comment by Coolthulhu** [comment]
Hiking boots are a bit too good compared to regular ones. Better coverage and lower encumbrance for just a tiny bit lower armor.

Armored boots got hit a bit too hard. Their armor values are only 27% higher than those of leather armor and coverage is 5% higher, while encumbrance is 4 times as high.
They are rare and really hard to craft (harder than survivor boots).

Bone armor boots are now strictly better than motorcycle ones. That isn't necessarily bad as it gives some sort of a reward for dragging all those bones to one place, but motorcycle boots are quite rare.

Rest looks good, though I'm not too sure about that winter boot encumbrance nerf.

**Comment by chaosvolt** [comment]
Regarding the armored boots, I forgot whether their protection has been buffed to match the light plate armor. Or failing that, to match plated leather armor. Would make the encumbrance increase worth it, especially if we're beefing up their encumbrance to be in between plate armor and ornamental plate armor. :V

**Comment by illi-kun** [comment]
Numbers for hiking boots, motorcycle boots, armored boots, winter boots were tweaked, and my initial message was updated accordingly.

**Pull request merged**
