### PR TITLE
Put Soap in Mall Sinks

### PR DESCRIPTION
**Pull request by Aimless-dude**
#### Summary
Content "Put Soap In Mall Sinks"

#### Purpose of change
Currently, mall sinks do not spawn anything at all, which dosen't make much sense and also makes Mall starts a little harder, as you cannot wash any filthy gear easily.

#### Describe the solution

 Each sink will now spawn a small amount of soap, and also adds a itemgroup for spawning things in other Public sinks. 

#### Describe alternatives you've considered

Find the spawn tables for the campsite bathrooms if there are any, add towels or toilet paper, Give up on my dreams of hygiene.

#### Testing
Boot up a new save, select a mall start, and navigate to the nearest bathroom sink. Observe that each one holds an amount of soap.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
Where are you finding soap *bars* in malls? Most establishments use liquid soap 🤔

**Comment by Aimless-dude** [comment]
> Where are you finding soap _bars_ in malls? Most establishments use liquid soap 🤔

The Liquid soap we have says it's more like Bodywash or Shampoo, which I assumed was different enough from squirt able hand-soap to be a poor choice.

**Comment by fairyarmadillo** [comment]
> > Where are you finding soap _bars_ in malls? Most establishments use liquid soap 🤔
> 
> The Liquid soap we have says it's more like Bodywash or Shampoo, which I assumed was different enough from squirt able hand-soap to be a poor choice.

I would suggest either changing the liquid soap description to be more generic (probably the better idea), or making a new liquid hand soap item and using that. Soap bars in public bathrooms is going to stand out to everyone as weird.

Really it should be in dispensers bolted to the wall in most public bathrooms, but that may be a step farther than we need.

**Comment by casswedson** [comment]
sorry about the review spam btw

**Comment by Aimless-dude** [comment]
> sorry about the review spam btw

Don't worry about it, I'm glad I could reveal this error in our linting bot.

**Pull request merged**
