### PR TITLE
Fix vehicle turret behavior and reorganize targeting code

### LINKED ISSUE #17071: "Semi-manual" turret mode doesn't work
You can only set turrets to the fully automatic (acquire targets + shoot) or fully manual mode (sit at turret, grab it and point it at stuff). The "sit at controls, point turrets at stuff, otherwise have them sit still" mode is no longer accessible.

### LINKED ISSUE #17294: Can't aim turrets from controls
Aiming turrets from controls does nothing. The menu appears, it is possible to pick a target, but nothing happens on confirmation.

### LINKED ISSUE #20088: Game crashes when manually controlling turrets in a vehicle
It just crashes when I go and manually aim a turret. I do not know if it is just me or if it happens to others also, could someone test this and verify? This is happening on build 6164.

### LINKED ISSUE #20245: Vehicle turrets auto firing even when set on manual
Heard some gunfire and saw a Hum-vee firing on a pack of zeds. "Odd" i thought, "Don't vehicles spawn with their turrets set to manual?" Wander over, and sure enough, its turret *was* set to manual. I then went and grabbed my vehicle and as I drove past the pack of zeds *its* turret started firing...despite being in manual mode also.

### PR DESCRIPTION
**Pull request by brian-donovan**
Refactor turret targeting and firing code.
Fix manual firing of turrets from vehicle controls.
Allow manual override of automatic turret targeting.
Allow aiming and firing of individual turrets from vehicle controls.
Wrap the turret's targeting npc in a factory function, used in multiple places.

Screenshot of the vehicle control menu: https://i.imgur.com/VGiOBjU.png

Fixes #17071, fixes #17294, fixes #20088, fixes #20245.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That's a pretty big change: 500+ lines of diffs. Try not to increase it further for now, unless it is necessary (for example, because of a bug) or makes things more readable.

Is the summary in OP up to date with all the later commits?

**Comment by brian-donovan** [comment]
I think that's it for now. Sorry about the big diff size. In retrospect, the plfire and turret changes probably belong in separate branches.

The screenshot is a bit obsolete, but the summary is up to date.

**Comment by brian-donovan** [comment]
The changes unrelated to turret fixes are reverted and the PR summary is updated.

**Comment by Coolthulhu** [comment]
Conflicts with current master.

**Comment by Coolthulhu** [comment]
Conflicts with your #20531 which is newer than this one.

**Pull request merged**
