### PR TITLE
Holster adjustments

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Bugfixes "Made crafting requirements of holsters more systematic"```

#### Purpose of change
Back holster uses marksmanship instead of rifles, shotguns etc. to not close out anybody from crafting the item.
Used this method to make the requirements more systematic, also fixed an inconsistency.

#### Describe the solution
Changed XL holster from pistols to marksmanship (to be used with shotguns, small rifles etc.)
Changed ankle holster from marksmanship to pistols (it's for small pistols)
Changed all four quivers from archery to marksmanship (so crossbowman without training in archery can craft them)
Changed all the melee weapon holsters to melee requirement, because polearms, knives and swords can use piercing and cutting.
Lowered the weapon skill requirements to 1 for every weapon holster and sheath according to the feedback.

#### Describe alternatives you've considered
An OR function for recipe skill requirements would be ideal, but it doesn't exist as far as I know.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Honestly I'd remove additional marksmanship and specific gun skill requirement for crafting any sort of clothing, even designed to hold weaponry. A skilled tailor could craft a holster or quiver without any practice with guns.

**Comment by darktoes** [comment]
I appreciate the catch on quivers, I'd never actually thought of that.

> Honestly I'd remove additional marksmanship and specific gun skill requirement for crafting any sort of clothing, even designed to hold weaponry. A skilled tailor could craft a holster or quiver without any practice with guns.

I can't say much about holsters, but quivers are significantly harder to get right than you might think and you would need experience with bolts or arrows to make a proper one, which I say from experience. That said, the requirement is only for level 1 or 2, so it's not a huge concern for most players.

**Comment by RarkGrames** [comment]
@Night-Pryanik Unfortunately I have not enough knowledge to have a reliable opinion on this. It has to be taken into consideration that these recipes are auto-learn ones, and the timely drawing of the weapon depends on the construction of the holsters. If you give the exact specifications of a factory made holster to a tailor, he can make it easily, but if he has to improvise it, I'm not convinced that the gun won't get stuck or won't be loose in it. I'm not disagreeing with you, but I have a family member who is a trained tailor, and I just can't imagine her thinking up and sewing a pistol holster that matches the quality of a factory made one, even if she would have the pistol at hand.

I have to take a pass on this one.

**Comment by tenmillimaster** [comment]
I have to agree with darktoe and rark- holsters need a degree of contextual knowledge to get right. Holsters designed for use, like good kydex ones fo competition and such, are pretty practical. Holsters with mandated features and designed by others for the user- like say, bureaucracies or police departments, tend to have sometimes-not-well-thought-out features like encumbering retention straps, flaps, etc.

**Comment by Night-Pryanik** [comment]
So you're saying that a skilled tailor couldn't find out how to sew something that's essentially a container for a gun without even the basic knowledge of how does this gun operated?

**Comment by tenmillimaster** [comment]
They would make an ineffective holster, yes.  The holster could be [unsafe](https://www.usconcealedcarry.com/wp-content/uploads/2012/06/is-your-holster-dangerous-cover.jpg), [slow](https://epsaddlery.com/wp-content/uploads/2017/03/elpasosaddlery_2000_flap-600x600.jpg), or [poorly positioned](https://media.10kya.com/media/catalog/product/cache/1/image/1080x/b05d625d6b6a602168d46abb7a406194/1/0/10dare-pistol-holster-khakhi-2-10kya-1100x1100.jpg). Another [slow](http://aliengearholsters.com/media/wysiwyg/alien-gear-shoulder-holster.jpg) holster. I have no problem believing that any tailor could make what's essentially a bag that sits at the waist, but making an effective bag that is safe and quick to use would require some familiarity with firearms in general.

**Comment by darktoes** [comment]
Quivers are the same way. Getting them to sit right, be balanced, and not bounce around to much or just drop all your arrows is surprisingly difficult. Unless you know what you're trying to do.

**Comment by Night-Pryanik** [comment]
If so, then 1 level in specific gun skill should be more than enough. 2 or 3 level is overkill.

**Comment by darktoes** [comment]
Perhaps. The difference between level 1 and 2 isn't that great. That's still most early books or less than a day's practice.

**Comment by RarkGrames** [comment]
@Night-Pryanik Updated per your suggestion, lowered every holster and sheath requirement to 1. Also while being there I changed all the melee weapon holsters to melee requirement, because polearms, knives and swords can use piercing and cutting.

**Pull request merged**
