### PR TITLE
[CR] Customize Disassemble Item menu

### PR DESCRIPTION
**Pull request by codemime**
Follows #19755.
The screenshots feature #19951.

### Overview

- It's now possible to disassemble nearby items.
- Various reasons why you can't disassemble stuff are shown.
- The stuff you can't disassemble no matter what, isn't shown at all.

- Queries feature the list of components (they don't always fit):

### CODE REVIEW

**Comment by lucasmr** [comment]
Maybe repeat the cost of the action before asking Y/N?

**Comment by Coolthulhu** [comment]
Nit: most game time is measured in seconds rather than turns. While turns are actually more informative, it is weird when it's turns/minutes/hours and also non-standard.

**Comment by Coolthulhu** [comment]
It would be great if the menu had binds. Manually scrolling menus is a pain, bad UI design and should be avoided where possible. We have too much of it, though usually only in the menus that actually allow searching.
It would be enough if the item's invlet was always used as the bind for it, with invlet-less items not having binds in the menu. Alternatively, autogenerated binds.

**Comment by codemime** [comment]
> It would be enough if the item's invlet was always used as the bind for it, with invlet-less items not having binds in the menu. Alternatively, autogenerated binds.

Could you elaborate on this? They have invlets (which can also be autogenerated). What do you mean by binds in the first place, keys assigned via `REGISTER_ACTION` or something different?

**Comment by codemime** [comment]
@Coolthulhu See #19956. I'll tweak this menu as soon as that PR (I hope) lands.

**Comment by Coolthulhu** [comment]
>  They have invlets (which can also be autogenerated). What do you mean by binds in the first place, keys assigned via REGISTER_ACTION or something different?

I didn't read the code thoroughly, but judging from the screenshot, pressing an invlet in the disassembly menu won't pick an item with said invlet.
And said invlets aren't displayed on the left of item names, like it is expected of inventory menus.

**Comment by codemime** [comment]
> but judging from the screenshot, pressing an invlet in the disassembly menu won't pick an item with said invlet. And said invlets aren't displayed on the left of item names, like it is expected of inventory menus.

They simply weren't assigned here. Everything works just as usual. I didn't touch that mechanics at all, only have written yet another `inventory_selector_preset`, and refactored the existing code to reach the goals listed in the description. Otherwise it's just a regular inventory menu.

**Comment by Coolthulhu** [comment]
Minor: picking up the object should not be required. Objects directly under the player can be disassembled without picking them up, extending that to nearby ones wouldn't be hard.

**Pull request merged**
