### PR TITLE
Update Hub 01 merchants

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
None

#### Purpose of change
Hub 01 Intercom:
1. restocks by-value and tends to be lackluster (very rarely has new armor pieces)
2. uses a Free Merchants trader as a clutch to sell more items after completing missions
3. can only sell some items once and only through dialogue

The Free Merchants trader in Hub 01's parking lot restocks by-value and is richer than the pope

#### Describe the solution
Depends on #57952 #58141 #58174
1. Let the Intercom sell armor pieces after the player completes 2 missions or displays potential earlier (by picking the right dialogue option)
2. Let the Intercom sell UHMWPE armor pieces occasionally after Hub 01 finishes analyzing the blueprint
3. Let the Intercom sell the environment suit occasionally after the player buys a the first one through dialogue or finishes the associated mission
5. Let the intercom sell HWP mags after fabricating a gun for the player, and occasionally a new gun kit as well
6. Let the intercom sell HWP EXOTIC barrels after fabricating the first one for the player
7. Only spawn the Free Merchant trader in Hub 01's parking lot after a trade route is established (ie. the next time the player talks to the Intercom after finishing the "Unknown Recipient" mission)
8. Once the trade route is established, let the Free Merchants accept Hub 01 Gold Coins as currency at 0.85 of its value.
9. Blacklist all Hub 01 gear so the Intercom always refuses to buy it back

For the Free Merchant trader:
1. remove mapgen loot spawn. Instead, the trader has a small chance to stock some Hub 01 gear at a hefty markup
2. made its shopkeeper group rigid. It was already pretty nice so I didn't change anything else.

For both:
1. slightly increased the prices of Hub 01 gear and added a large markup (2x for Hub 01, 2.5x for Free Merchants) to better match the dialogue rates (though they're still cheaper in trade).

<details>
<summary> TODO (done) </summary>

- [x] Nerf the Free Merchants trader: didn't have to do much here; just added `rigid`
- [x] Increase prices of Hub 01 gear to match old dialogue rates: adjusted slightly increased prices and added a hefty markup
</details>

#### Describe alternatives you've considered
N/A

#### Testing
Play through the Hub 01 quest line and check the shop. Or just set the variables manually and advance time.

#### Additional context
~Number 6. above spawns a duplicate merchant in existing saves. Don't have a solution for this atm.~ fixed with #58112

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
This looks great!

**Comment by andrei8l** [comment]
This is ready for review but I'll keep it in draft until the dependencies are resolved.

**Comment by andrei8l** [comment]
This is ready for review but I'll keep it in draft until the dependencies are resolved.

**Comment by andrei8l** [comment]
Thanks for merging!

**Pull request merged**
