### PR TITLE
Make m38DMR usable with krav maga. Fixes #48263

### LINKED ISSUE #48263: M38 DMR Not Valid for Krav Maga
# Describe the bug

M38 DMR is not considered a valid weapon for the Krav Maga style.

# Steps To Reproduce

1. Make a player with a M38 DMR and the Krav Maga style.
2. Switch style to Krav Maga.
3. Wield M38 DMR.

# Expected behavior

M38 DMR should be a valid weapon for Krav Maga. The M38 DMR is a variant of the M27 IAR, which currently is on the valid weapon list for Krav Maga. The M38 is just a slightly optimized version of the M27 with an attached scope mod, so this is likely a small oversight.

# Screenshots

# Versions and configuration

 - OS: Windows 10 64bit
 - Game Version: 0.E-10212-gb725af3
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: StatsThroughSkills, Stats_through_kills, no_npc_food, package_bionic_professions, speedydex

# Additional context

### PR DESCRIPTION
**Pull request by Zeropol**
#### Summary
Balance "Make m38DMR usable with krav maga"

#### Purpose of change

To fix #48263 , and train myself on a simple issue.

#### Describe the solution

Add m38dmr to the krav maga weapon list in martialarts.json.

#### Testing

Created a character with krav maga knowledge. Spawned a m38DMR. Saw it is usable with krav maga.

### CODE REVIEW

**Comment by actual-nh** [comment]
If you put in `To fix #48263` (and/or possibly change the title to end with "Fixes #48263"), it should link this to that issue so the issue is closed if/when the PR is merged.

**Comment by zeropol** [comment]
> 
> 
> If you put in `To fix #48263` (and/or possibly change the title to end with "Fixes #48263"), it should link this to that issue so the issue is closed if/when the PR is merged.

Thanks a lot !

**Comment by actual-nh** [comment]
> Thanks a lot !

Oh - one English tip, if I may - "Thanks a lot" (at least in the US, and I _think_ elsewhere) is most frequently used sarcastically, although I understand what you mean (quite welcome!). "Thanks very much" is preferable.

**Comment by zeropol** [comment]
> 
> 
> > Thanks a lot !
> 
> Oh - one English tip, if I may - "Thanks a lot" (at least in the US, and I _think_ elsewhere) is most frequently used sarcastically, although I understand what you mean (quite welcome!). "Thanks very much" is preferable.

Wow, I may have offended a lot of people through the years so.
Thanks very much for the precision, it will help me to communicate.

**Comment by actual-nh** [comment]
> > > Thanks a lot !
> > 
> > Oh - one English tip, if I may - "Thanks a lot" (at least in the US, and I _think_ elsewhere) is most frequently used sarcastically, although I understand what you mean (quite welcome!). "Thanks very much" is preferable.
> 
> Wow, I may have offended a lot of people through the years so.
> Thanks very much for the precision, it will help me to communicate.

Quite welcome; anyone reasonable will have understood your meaning. (I am aware of exactly how difficult English is - my spouse is not a native speaker.)

**Pull request merged**
