### PR TITLE
Make laser weaponry deal 'Heat' type damage

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary

SUMMARY: Balance "Change laser weaponry to deal 'Heat' type damage"

#### Purpose of change
It came to my attention that most laser weaponry was exceedingly weak, and useful only against completely unarmored targets. This was mostly to the fact that they deal low amounts of stab damage, which was easily resisted, even when counting for the relatively high armor penetration of the weapons.  

#### Describe the solution
To resolve this I have changed the damage type to 'heat', which I feel better describes the damage type dealt by a laser (ablation damage to non organic surfaces and  burning of organic tissue). As such lasers are now highly effective against most organic foes, but very bad weapons vs metallic or other mostly inorganic foes.

Power and damage types were also adjusted in accordance of this comment by  Mlangsdorf, although I didnt increase damage that highly as because 'heat damage' is already barely resisted among vulnerable foes.

image

#### Describe alternatives you've considered

Im still not fully content with the reloading and charge draw of lasers, and hope to revise it once the magazine code is overhauled. I'd like them to use their own charge-pack ammo instead of drawing power from common comercial batteries.

 But this can be a change for another day, I believe/

#### Testing
Laser goes pew-pew, killing zombies very dead. Robots remain unimpressed.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
These should probably lose the armor penetration.

**Comment by John-Candlebury** [comment]
>These should probably lose the armor penetration.

I kept it only because I didnt feel like nomex gear should meaningfully protect against lasers, but I'm sure of that myself.

**Comment by Dacendeth** [comment]
Nomex protects against heat, if lasers do heat damage it makes sense to me that it protects from it. Perhaps reduce the penetration around 4 (the fire resist of flame resistant undergear) so it penetrates basic defenses but still allow for heavier gear to help against laser damage?

**Comment by dissociativity** [comment]
I don't really see why laser should have any real armour penetration, it's appeal is being able to work around targets that are armoured against things that aren't heat, or unarmoured targets.

I personally can only really see laser weapons irl useful for protestor dispersion or something similar, at least the pistol, perhaps the rifle is a little bit more powerful, but it's a more pain based weapon than anything, creating surface level wounds that stun, even on armoured targets, but not doing much /real/ damage beyond that?

**Pull request merged**
