### PR TITLE
Modified hard cheese recipe for realism

### LINKED ISSUE #28161: Crafted hard cheese lacks calories
**Describe the bug**  
Looted/spawned hard cheese has ~3.8kcal/g (or 130 per "portion") in line with e.g. [parmesan](https://en.wikipedia.org/wiki/Parmigiano-Reggiano). Crafted from curdled milk however it only has 0.76kcal/g (26 per portion).

**To Reproduce**  
1. Spawn in some hard cheese via debug menu
2. Spawn in some curdled milk and craft it into hard cheese
3. Compare calorie amounts

**Expected behavior**  
Crafted hard cheese should have close to identical calorie amounts. The portion yield of the recipe might need to be adjusted as the current chain is 15 milk->18 curdling->18 curdled->21 hard cheese while in real life the milk is condensed down a lot.

**Version:**
0.C-37270-g86ec372

**Additional context**  
The curdling milk was displayed as "rotten" in the fermenting vat. This does not currently seem to change the calorie content of the product but may become an issue.

### PR DESCRIPTION
**Pull request by cburns2017**
#### Summary
SUMMARY: Content "Makes crafted hard cheese have the same kcals as spawned hard cheese"

#### Purpose of change
Fixes #28161 

#### Describe the solution
Added `"flags": [ "NUTRIENT_OVERRIDE" ]` to `cheese_hard`

### CODE REVIEW

**Comment by Mecares** [comment]
That would make quite a lot of calories appear out of thin air, a change to the number or size of portions seems preferable to me.

**Comment by austin9240** [comment]
Proposed solution, change the portions from the crafting recipe to only give 1 hard cheese but change the requirements of curdled milk to 2, and the salty material to 1. Let me know if this would be a good solution.

**Comment by KorGgenT** [comment]
my suggestion: more ingredients for the recipe output to make sense.

**Comment by Photoloss** [comment]
One serving of hard cheese is about 34.3g in-game. According to [this](https://www.thekitchn.com/how-much-milk-makes-one-pound-131332) we're looking at a 10:1 ratio milk:cheese by weight so 343g of milk (260g/milk unit). So roughly 4:3 in current in-game portions end-to-end. Keeping the current curdling milk recipe (which I did not check for realism) it would be 8:5 curdled:cheese.

Calories "out of thin air" is not a valid argument in general as humans are not able to digest all hydrocarbons in food. Comparing wikipedia values for parmesan and cow's milk the cheese only has about 60% of the original calorie content though. On that note in-game milk is on the high side at 73kcal/100g while the wiki lists 66kcal/100g and [Jersey-breed cow milk](https://www.myfitnesspal.com/food/calories/generic-raw-jersey-cow-milk-483726553) with a higher fat content is 69kcal/100g.

**Comment by austin9240** [comment]
Changed the recipe of cheese_hard to reflect my proposed solution

**Pull request merged**
