### PR TITLE
Fix json style regression (2019-08-14)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Self merging to fix builds.

**Comment by ampersand55** [comment]
Sorry, this is the second time some of my stuff had needed linting. 

I've made a linting script now so it should not happen again.

**Comment by ZhilkinSerg** [comment]
You can run `make style-all-json`.

**Comment by ampersand55** [comment]
An hour making a script can save you minutes of reading the manual!

I just use the cdda launcher and I don't have make or other linux tools on this machine. It would probably be a good idea to get that though.

**Comment by ZhilkinSerg** [comment]
If you are on Windows, then try [MSYS2](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING-MSYS.md).

**Comment by ampersand55** [comment]
I know.

**Pull request merged**
