### PR TITLE
Total tailoring overhaul, attempt 2

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Overhaul tailoring to be more realistic"```
#### Purpose of change

https://github.com/CleverRaven/Cataclysm-DDA/projects/25
#### Describe the solution

Making clothing from scratch now takes much more time and uses purpose-made material sheets as well as "secondary" parts like zippers, buttons, buckles or whatever, as needed. Most are craftable; base materials may be crafted via weaving as well (the most basic craftable loom was added for that purpose).

Awls were added as well, to be used for leatherworking.

Tailoring pattern set was added, to be used for more advanced and/or fancy tailoring projects.

Requirements for working with different soft materials were implemented, as well as for waterproofing and dyeing cloth. They have guidelines in comments as to how much time the resulting recipe should take, how much material should be used, and how much waste material should be created.

A few recipes were made/changed to showcase how it's supposed to work for recipes in general.

Tailoring recipes produce waste material as byproducts; some types of it can be reused.

Uncraft recipes were added for clothing items whose recipes were changed/added, as simply cutting it into bits wouldn't let one recover fasteners that the clothing may have. There may be an issue of fasteners changing to different fasteners if someone crafts some clothing and then disassembles it, but this seems too difficult to abuse (and really not worth it).
#### Describe alternatives you've considered

Adding more tailoring recipes in this PR, but it already has grown quite large as I was working on it.

Trying to handle more of the things noted in the project, but once again, this PR already got quite large.
#### Additional context

All changes are manually copy-pasted from #32766, since I messed up the branch while trying to resolve merge conflicts.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
This pull request is kinda huge to be merged at once and I would suggest keeping this as guidance and split changes to several smaller chunks.

For example, create separate PRs for basic new infrastructure:

- add new tailoring tools;
- add new tailoring material;
- add new tailoring crafting qualities.

Then create PRs of reasonable size (up to 200 lines changes) with changes to tailoring recipes.

**Comment by Rail-Runner** [comment]
The project isn't abandoned, by the way, I'll resume work on splitting this soon.

**Comment by DaviBones** [comment]
Hey, just wanted to say that this project is awesome! If there is anything I can do to help, let me know. Even if not, please message me if you end up having to abandon it, I will gladly pick up the torch and make sure it gets finished.

**Comment by anothersimulacrum** [comment]
You may not have noticed, but you have merge conflicts.

**Comment by snipercup** [comment]
I see you have scrap_cotton in this PR. I can use it to help with weight balancing. Anything I can do to help get this item merged?

**Comment by Rail-Runner** [comment]
> I see you have scrap_cotton in this PR. I can use it to help with weight balancing. Anything I can do to help get this item merged?

You can just copy this item from this PR if you need to use it for something. Would be best if you didn't alter its weight or volume, though.

**Comment by ANickelN** [comment]
What's the status of this re-work?  Is there still some conflicts that need to be solved, or is it simply being segmented/something else?

**Comment by Rail-Runner** [comment]
> What's the status of this re-work? Is there still some conflicts that need to be solved, or is it simply being segmented/something else?

I'll be splitting parts off of this PR. Next will be adding items from this PR, I think; so I'm waiting for #34871 to get merged so that I could add some items related to fabrics added there. All those items will be unobtainable until this project is finished.

**Comment by ZhilkinSerg** [comment]
Needs conflict resolution.

**Comment by Rail-Runner** [comment]
I'll split this into multiple PRs later on once there's less pull requests hanging. Guess I can close this for now.

**Pull request closed without merging**
