### PR TITLE
Added recipe for small storage batteries made out of car batteries

### PR DESCRIPTION
**Pull request by Cosmitz**
Small storage batteries are the base for crafting the other ones which are the basis of many vehicles and it makes little sense to leave them as 'find-only'. 

The recipe maintains itself in line with the requirements of the other batteries, as a sum of the previous' battery, and following the same thought of 'chaining' smaller sets of batteries together.

Car batteries are easy to find and would make for a good stepping stone instead of going out to salvage/harvest existing storage batteries, skipping small storage batteries completely.

Also it would allow of earlier-accesible small-storage batteries in smaller vehicles like electric motorbikes or small vehicles, instead of stacking car batteries everywhere. 

It would also make feasible for earlier use in for the welder with a magazine battery mod.

### CODE REVIEW

**Comment by angoddu** [comment]
About time there was a recipe for this. I almost never actually find small storage batteries so I usually jump straight to the storage battery. Should there be a truck battery variant as well? Maybe like 2 truck batteries = 1 small storage battery?

**Comment by Cosmitz** [comment]
There is no such thing as a truck battery anymore. And the only other unique battery is the motorcycle one but to be fair, it seems a bit too ridiculous that you'd find 8-10 motorcycle batteries to use for this.

**Comment by kevingranade** [comment]
This was an intentional omission, truck batteries are lead-acid and storage
batteries are LiOn or similar.

**Comment by Cosmitz** [comment]
Ok, then in that case would a better path to solve this, given that small storage batteries could be gotten out of things like laptops, to increase the number of things that use small batteries? Cell phones and such? It's a matter of density and accesibility of small storage batteries than one of where we get them per se.

Looking through the jsons, minus laptops, portable generators and three carts which are rare spawning anyway, there are no other places one can get them. 

On the other, for gameplay purposes, we can allow them to be made out of normal batteries then, since given that they can be recharged via the UPS mod, means they are of the rechargeable variety, so it's not a stretch of the imagination we can use them as small storage batteries. Batteries are also plentiful enough that you can craft a few small storage batteries out of them when needed.

**Comment by angoddu** [comment]
Also a car battery has a charge of 2500 and a small storage battery only has 500 charge. So 4 car batteries would seem like overkill. What about a recipe where 750 batteries would craft into a small storage battery?

**Comment by kevingranade** [comment]
> Ok, then in that case would a better path to solve this

It depends on what "this problem" is.  It seems to be "we need sources of components for vehicle crafting", in which case I can see a few options:

The simplest way to make storage batteries more available is to simply spawn more cars that have them, the existing ratios aren't really balanced around anything.  Anything up to about 20% electric cars would probably go in with little to no debate, and I think that'd leave you with plenty of cells to scavenge.  If you need still more than that for some reason it can probably happen, but will need some thought to determine what that higher ratio can be.

Instead of alternate sources of "storage batteries", you could substitute a new item that is a large array of lead-acid batteries, that has a worse charge / weight ratio, but can be substituted for some use cases.  This is particularly attractive for non-vehicle applications that want a lot of power.

A big pile of laptop batteries is certainly the right *kind* of battery (see the [Tesla Roadster battery system](https://en.wikipedia.org/wiki/Tesla_Roadster#Battery_system) ), so that would be fine (though you're right about how much battery they yield currently, the Roadster used 6,831cells, a laptop battery pack has something like 6-10 of those cells, so you'd need to harvest from ~1,000 laptops to make what you'd probably consider to be a large storage battery).  It makes sense to allow it, but the amount of scavenging is pretty prohibitive.  Similarly there's not much difference between these cells and an average rechargeable battery, but again you need thousands to do anything with.

I don't think having "storage battery" type components be "find only" is a problem.  It's an advanced piece of technology that you can't reasonably recreate, frankly just stacking a bunch of LiON cells into a vehicle-scale battery system is already a major technical feat, and converting between arbitrary kinds of battery systems is simply impossible, but I think you can pick one or more of the approaches I outlined, and I *think* they'll do what you want.

**Comment by angoddu** [comment]
> Instead of alternate sources of "storage batteries", you could substitute a new item that is a large array of lead-acid batteries, that has a worse charge / weight ratio, but can be substituted for some use cases. This is particularly attractive for non-vehicle applications that want a lot of power.

This would be perfectly fine for me. I would use them to power my base not my car anyway. Right now I am using the storage batteries for this and am using the car batteries for either battery compartment modded tools or taking them apart to make normal batteries

**Comment by Cosmitz** [comment]
At the moment storage batteries, the standard, large ones, are the most common and plentiful and they come only late in the game, plus are a bitch to haul at the beginning of the game to even use. 

They also are not able to be disassembled into Mediums, if we're working off the stacking methodology, because of their weight and the disassemble bug. However, there still are too many of them. 3 in a fire truck, i think two in an RV and generally we get swamped with so many of them that the mid-ground ones, smalls and mediums get completely unused since almost everything you find is either a swappable storage batteries and storage batteries, both which have higher-level uses than slapping a small on an electric motorbike out the gate.

I'll give this more thought, maybe i'll redestribute smalls across all electric cars and mediums around trucks keeping storage batteries as a one per large vehicle kind of thing. No use for another set of batteries, we just need to allow small ones and medium ones to be as or even more accessible than the 'large' storages.

One final thing, putting together batteries in packs is fantastically easy with some minor soldering, or for car batteries, just wiring the leads together. 

This PR can be closed, won't be going in. Thanks for your time.

**Comment by angoddu** [comment]
> They also are not able to be disassembled into Mediums, if we're working off the stacking methodology, because of their weight and the disassemble bug.

One final comment on that bug - You can pick up/wield the items too heavy/large to normally disassemble and then you can disassemble them while overburdened.

**Comment by Cosmitz** [comment]
It is a horrid workaround and one which i hope to fix to be able to be disassembled right out the gate.

**Comment by atlaua** [comment]
@Cosmitz, you're aware items on the ground can be disassembled using the 'B'utcher menu, right? I just tried disassembling a storage battery this way with a STR 5 character who wasn't able to pick it up -- worked perfectly fine.

**Comment by Cosmitz** [comment]
The Disassemble menu "(" which should handle all matters of disassembly, is weight-limited.

**Comment by atlaua** [comment]
I'm not saying this isn't a bug, merely pointing out that there's an easy workaround until said bug gets fixed. :)

**Comment by angoddu** [comment]
> Neither is diassembling them while in crippling pain after wielding an ok compromise

If you don't move while overburdened you don't experience pain

**Comment by Cosmitz** [comment]
Time still passes while you're waiting for the disassemble. And you can take pain from serious overburden even without moving.

**Comment by Coolthulhu** [comment]
> The Disassemble menu "(" which should handle all matters of disassembly, is weight-limited. Butcher is a bit of a hack.

Even if it's a hack, it's much better than the "proper way". Butcher is much faster to select than the disassemble menu, which lists a ton of items it doesn't need to. Butcher also allows mass disassembly.

**Pull request closed without merging**
