### PR TITLE
Firestation variant

### PR DESCRIPTION
**Pull request by chaisawlajatang**
#### Summary
```SUMMARY: Content "Firestation variant"```  

#### Purpose of change
There's only one type of the firestation, I wanted to add some variety.

#### Describe the solution
I made another one type of the building to let firefighters enjoy the sunlight.

#### Describe alternatives you've considered
Leave everything as is.

#### Additional context
There are spawnpoints for up to two fire engines in the garage.
firestation

### CODE REVIEW

**Comment by chaisawlajatang** [comment]
Hmmm, IDK where the conflict is.

**Comment by ZhilkinSerg** [comment]
You've probably based your changes on some old commit. You wanna do `git pull --ff-only upstream master` and then `git rebase upstream/master` on your branch.

**Comment by Inglonias** [comment]
I like the new building. It's secure, but less so than the existing fire station. Since fire stations were never designed to be fortresses against zombies, this is fine.

**Comment by ZhilkinSerg** [comment]
Merged to 0.D and master with #28146.

**Pull request closed without merging**
