### PR TITLE
NPC specific snippet describe in JSON

### PR DESCRIPTION
**Pull request by ti360gh**
#### Summary
Features "NPC specific snippet describe in JSON"

#### Purpose of change
Make changes similar to #50361 to other talk tag snippets and speech lines in `npc.cpp`, `npcmove.cpp`, `npctalk.cpp` and `talker_npc.cpp`.
This will make NPCs more unique and will help to create a kind of fully characterized NPC follower.

#### Describe the solution
 - The hard-coded snippet or lines are now can read from npc's json.
 - The custom snippet or lines is handling with `npc.chatbin` in game.
 - Hard-corded snippet or lines replaced with `chatbin.<name>`.
 - formatted string(%s) in snippet or lines are accepted.
 - save/load that snippet or lines.
 - Update NPCs.md

#### Describe alternatives you've considered
 Nothing. I wanted to replace the hard-coded values with JSON.

#### Testing
- Unit test passed.
- Play-testing
  - Setup
I created the scenario with 2 NPC instances.
One of NPC have all customized topics in json.
The other one have nothing above fields in json.

  - Testing
Play-testing by roam around with NPC, fought zombies together and gave items.
I confirmed 24 of 71 customized message in game, but I could not confirmed other messages.
But I think the other messages will be fine, too.

#### Additional context

Example1: customize end of a conversation
```json
{
  "type": "npc",
(snip)
  "snip_bye": "<snip_bye>"
},
{
  "type": "snippet",
  "category": "<snip_bye>",
  "text": [ "Bye.", "Goodbye.", "Farewell" ]
}
```
image

Example2: customize some more.
```json
{
  "type": "npc",
(snip)
  "snip_bleeding": "<snip_bleeding>",
  "snip_pulp_zombie": "<snip_pulp_zombie>"
},
{
  "type": "snippet",
  "category": "<snip_bleeding>",
  "text": "talk-tag snippet:snip_bleeding from %s."
},
{
  "type": "snippet",
  "category": "<snip_pulp_zombie>",
  "text": [ "talk-tag pulp_zombie1: target is %s.", "talk-tag pulp_zombie2: target is %s.", "Hold on, I want to pulp that %s." ]
}
```
image

### CODE REVIEW

**Comment by ti360gh** [comment]
I saw 420 files changed and a lot of conflicts.
I think I did something wrong with my last commit, but I don't know what to do.

Could anyone tell me what to do?

**Comment by Maleclypse** [comment]
> I saw 420 files changed and a lot of conflicts.
> I think I did something wrong with my last commit, but I don't know what to do.
> 
> Could anyone tell me what to do?

OK I am not the person to walk you back through the step where the mistake happened, are you on Discord?  The #dev-help channel would be best for someone or several someones to walk you through how to fix this in real time.

**Comment by ti360gh** [comment]
> > I saw 420 files changed and a lot of conflicts.
> > I think I did something wrong with my last commit, but I don't know what to do.
> > Could anyone tell me what to do?
> 
> OK I am not the person to walk you back through the step where the mistake happened, are you on Discord? The #dev-help channel would be best for someone or several someones to walk you through how to fix this in real time.

Thank you for the information. I'll go to Discord!

**Comment by ti360gh** [comment]
@actual-nh Your commit log was lost due to rebase. I'm sorry...

**Pull request merged**
