### PR TITLE
Adds Android Build to release workflow & fail-fast: false

### PR DESCRIPTION
**Pull request by Cruentus-Tigris**
#### Summary

Build "Added fail-fast=false and android builds to actions."

Purpose of change
Continuing from CleverRaven#48784
Added fail-fast tag to enable matrix to build others even if one fails.
Added android builds that all require a "keystore" and "properties" file to be stored in GitHub secrets to be signed.

Describe the solution
Added fail-fast=false that stop the jobs from exiting if one of the matrixes fails.
The attribute handling is a bit messy, added an android attribute to split the android builds up and separate the Linux builds out.
Linux hosts come preloaded with android build software so added option to select java for build and install "gettext".
Android build is setup to do arm64/arm32 or bundle, selects which version and builds it and moves that file to be uploaded.

The below need to be done to hide the keys.
Requires the below files to be converted to encrypted base64 strings using the command "gpg -c --armor " and that string from that added to uploaded to GitHub secrets with the matching passcode for decryption for the app to be signed and able to be installed on devices.(apps cannot be updated by apps with different signs).

GitHub Secrets Needed = item inside
KEYSTORE_PASSWORD = "password" used by gpg -c --armor to encrypt below files
KEYSTORE = (release.keystore) file
KEYSTORE_PROPERTIES = (keystore.properties) which is text file with the below info

storeFile=app/release.keystore
storePassword=store_password
keyAlias=your_key_alias
keyPassword=key_password

Describe alternatives you've considered
Not having android builds or waiting for some else to do it.
And not adding the fail-fast=false and the whole action stop on one build failure.

Testing
Tested by building it on own repo and testing the windows64 & mobile 64bit only.

edit: changed storefile location to app/release.keystore

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
We will need `versionCode` customization in order to allow easier updates from previous versions. Right now it is taken from Jenkins environmental variable `UPSTREAM_BUILD_NUMBER` here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3cd92bed7f2acd4b49fe82da77119c3b5454b308/android/app/build.gradle#L240

We can use something like this and provide value from :

```gradle
def override_versionCode = getProperty("override_versionCode").toInteger()
if (localProperties.getProperty('override_versionCode') != null) {
    override_versionCode = localProperties.getProperty("override_versionCode").toInteger()
}
```

But for the start we can just set up `UPSTREAM_BUILD_NUMBER` environmental variable based on `11581` + `{{ github.run_number }}`, where `111581` is last successful Jenkins build number.

**Comment by Cruentus-Tigris** [comment]
used override version code had troubles saving the variable but could pass it direct in the cmd to build.

**Comment by Cruentus-Tigris** [comment]
> We will need `versionCode` customization in order to allow easier updates from previous versions. Right now it is taken from Jenkins environmental variable `UPSTREAM_BUILD_NUMBER` here:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/3cd92bed7f2acd4b49fe82da77119c3b5454b308/android/app/build.gradle#L240
> 
> We can use something like this and provide value from :
> 
> ```groovy-gradle
> def override_versionCode = getProperty("override_versionCode").toInteger()
> if (localProperties.getProperty('override_versionCode') != null) {
>     override_versionCode = localProperties.getProperty("override_versionCode").toInteger()
> }
> ```
> 
> But for the start we can just set up `UPSTREAM_BUILD_NUMBER` environmental variable based on `11581` + `{{ github.run_number }}`, where `111581` is last successful Jenkins build number.

this has been added using UPSTREAM_BUILD_NUMBER

**Comment by Cruentus-Tigris** [comment]
been tesing the 64bit on my device, using a daily build and updates are working fine

**Comment by actual-nh** [comment]
@Cruentus-Tigris: Could you take a look at the push failures for the Android builds? There seems to be something with regard to the keying. (Admittedly, they may well fail after that point due to the need for #49048.)

**Comment by ZhilkinSerg** [comment]
> @Cruentus-Tigris: Could you take a look at the push failures for the Android builds? There seems to be something with regard to the keying. (Admittedly, they may well fail after that point due to the need for #49048.)

Don't worry - that was expected as Kevin have not set up secrets with key yet.

**Pull request merged**
