### PR TITLE
Allow camera(_pro) for security camera crafting.

### PR DESCRIPTION
**Pull request by woutershep**
They are both digital so should be fine in that regard.

If you can craft a security camera from the broken remains of eyebots surely
you can just reroute the camera's display to your camera control display.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs more than one - the camera looks in multiple directions at once.

**Comment by Rivet-the-Zombie** [comment]
>looks in multiple directions at once

So does the player though.

**Comment by Rivet-the-Zombie** [comment]
>looks in multiple directions at once

So does the player.

**Comment by Coolthulhu** [comment]
The player can freely turn around. The camera is mounted. It doesn't even take a motor component.

**Comment by woutershep** [comment]
How about requiring 3 normal camera's (ive found 6 sofar in my current game) but still 1 camera_pro (ive found 0) handwaving it in that you modified the mirror and lenses in it since its a fancy DSLR. The description of both cameras say it has high resolution and the security camera has poor resolution and great field of view. Im not an expert in optics but it sounds sensible in that you can sacrifice one for the other with some fidgeting?

**Comment by cainiaowu** [comment]
You can sacrifice one for the other, but you need to change lens design which i doubt it could be done by hand improvised.

https://en.wikipedia.org/wiki/Photographic_lens_design

**Comment by woutershep** [comment]
I was thinking more something like this but then not as nice and smooth cone wise but segmented mirror shards that would be 'good enough' to see.

robot_mirror

**Comment by kevingranade** [comment]
I really doubt hanging a disco ball above the camera is going to get you a
useable 360deg view, just use multiple cameras.

**Comment by woutershep** [comment]
How many do you want?

**Comment by Coolthulhu** [comment]
2 bot wrecks are enough so 2 cameras should be too.

**Pull request merged**
