### PR TITLE
MShock Modded Tileset: zombie children evolutions

### PR DESCRIPTION
**Pull request by chaosvolt**
- Anklebiters
- Sproglodytes
- Shreiklings
- Creepy crawlers
- Snotgobblers
- Skeletal waifs

### CODE REVIEW

**Comment by Malkeus** [comment]
They merged as snotgobblers? Too bad...

**Comment by chaosvolt** [comment]
The PR train left the station, and Kevin stole the brakes. XP

**Comment by Malkeus** [comment]
Theres still that ongoing zombie naming conversation going on in a separate issue. Hopefully something comes of that. If not I'll throw together a PR and listen to the screams...

**Comment by kevingranade** [comment]
It was drifting into bikeshedding, if someone wants to make a further
change they can discuss it and/or open a pr, I had no intention of stopping
didcussuon, just getting some working code merged so it didn't linger.

**Comment by chaosvolt** [comment]
No worries, was good to have the actual code details sorted out, naming is a minor thing compared to that. XP

**Pull request merged**
