### PR TITLE
Add seed recipe and canola stalk product.

### LINKED ISSUE #56688: Canola has no use (Biodiesel related)
### Is your feature request related to a problem? Please describe.

Canola oil has no use and as far as I am aware can't be found in-game. 
https://nornagon.github.io/cdda-guide/#/item/canola

### Solution you would like.

First the player has to be able to find Canola (either in the wild or in certain locations). I don't think I've ever found Canola in-game, I'm not a 100% sure it doesn't exist.

Implement canola as a plant that can be found in the Cataclysm that has a use in the Biodiesel recipe (or is an alternative biodiesel recipe).
Another way to do this might be to make a recipe that turns canola into vegetable cooking oil. This way it can be used in the biodiesel recipe.

I am by no means an expert in the petrol industry, so if this is not realistic / possible to be done by someone in game I suggest removing canola from the game (because it doesn't do anything gameplay wise). 

### Describe alternatives you have considered.

Remove canola from the game files.

### Additional context

I have no idea how difficult this is to implement, if this takes a lot of work removing the item might be a better option (I don't think it will have that much gameplay effect).

### PR DESCRIPTION
**Pull request by ryanhaney97**
#### Summary
Balance "Adds canola seed recipe and canola stalk product."

#### Purpose of change
Resolves #56688

#### Describe the solution
Adds the actual canola stalk item to the game, as it previously wasn't obtainable despite being present. Also adds a seed extraction recipe for it.

#### Describe alternatives you've considered
Amount of seeds/stalks obtained might need to be adjusted, currently left as is.

#### Testing
Start a game
Spawn a shovel, 2 canola seeds, and fertilizer
Make a mound with the shovel
Hack time to noon so it's warm enough to plant
Plant the two seeds, fertilize one of them in order to test effects of fertilizer if necessary
Hack time to day 151, change weather back if necessary (usually get a portal storm here)
Teleport back and forth in/out of the local reality bubble so the growth stages update
Harvest plants and check amounts/items produced
Finally, craft seeds from the stalk using the related recipe (if survival isn't 2 hack it to that number first)

### CODE REVIEW

**Comment by AtomicFox556** [comment]
Why? That is pretty much just adding an extra unnecessary step between harvesting canola and actually using the seeds for something. If anything, "canola" item should probably just be migrated to "seed_canola"

**Comment by yoshiquest** [comment]
> Why? That is pretty much just adding an extra unnecessary step between harvesting canola and actually using the seeds for something. If anything, "canola" item should probably just be migrated to "seed_canola". If only the seeds are useful, then harvesting the canola should just yield the seeds directly to reduce amount of keypresses needed, any other mostly-useless plant material is abstracted away as "withered plant" item.

I mean, I was just looking for "good first issues" and ran into that one which is still open. So if you don't want to add this you don't need to.

**Comment by PatrikLundell** [comment]
I think you've been misled by the suggestion thread mentioned.

As far as I understand, canola seeds are the only usable part of the plant, in which case harvesting seeds and withered plants ought to be the desired behavior in order not to introduce unnecessary steps (as mentioned). If the plant itself actually has a distinct use it might make sense to harvest it, allow seeds to be extracted from it, and introduce a process whereby the plant is processed into whatever its use is yielding seeds as a byproduct.

The odd thing about canola is that it isn't farmed. I don't know about New England, but I would have thought it would be a plant farmed there. However, farming in the game is odd in that almost all the commercial farming is producing corn, with a small patch of oats in some farms. All other plants are farmed only in community farms and backyards.

I'd consider adding canola to the set of plants farmed in community farms and backyards to be "reasonable", and I'd also like to see a variety in the crops grown on farms, although that may take some work to implement, as you'd still want a monoculture approach (i.e. all the crops on a farm field.

I don't think attaching the "Good first issue" tag to the suggestion was a good idea...

**Comment by Fris0uman** [comment]
Obsoleted by #59437

**Pull request closed without merging**
