### PR TITLE
Aftershock Exosuit Module Fixes

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Bugfixes "Minor corrections to exosuit modules"

#### Purpose of change
Corrects an issue preventing worn equipment from providing intended effect (load support module not providing carry capacity bonus as an example).

#### Describe the solution
Apply c++ changes from @andrei8l. Also some small json corrections.

#### Describe alternatives you've considered
None.

#### Testing
WIP

#### Additional context
None

### CODE REVIEW

**Comment by Raikiri** [comment]
Is there an issue tracking exosuits roadmap progress and plans? I'm very interested to know what's in the works, what's planned for aftershock and what's going into CDDA.

**Comment by Drew4484** [comment]
> Is there an issue tracking exosuits roadmap progress and plans? I'm very interested to know what's in the works, what's planned for aftershock and what's going into CDDA.

https://github.com/users/Drew4484/projects/1

Big issues remaining are UI/UX and balance testing.

**Comment by Raikiri** [comment]
Very interesting, I hope you will have enough enthusiasm to pull it through. Currently power armors are in a really sad state: they're extremely OP and extremely boring because you can't combine them with anything else. Basically once you find a power armor set, there's no reason to be looking for anything else and they are so strong that doing it would not be interesting anyway.

I really hope that power armors will become a longer-term commitment for a player, ideally similar to building a vehicle. A good comparison would be fallout 4 power armors that you find, build and assemble piece by piece and only use for certain particularly dangerous situations.

What are the plans on including them to the base game vs aftershock? I'm really afraid that if all this work goes into making an aftershock-restricted content, then 90% of players would never get the chance to interact with it.

**Comment by Drew4484** [comment]
> Very interesting, I hope you will have enough enthusiasm to pull it through. Currently power armors are in a really sad state: they're extremely OP and extremely boring because you can't combine them with anything else. Basically once you find a power armor set, there's no reason to be looking for anything else and they are so strong that doing so would not be interesting anyway.
> 
> I really hope that power armors will become a longer-term commitment for a player, ideally similar to building a vehicle. A good comparison would be fallout 4 power armors that you find, build and assemble piece by piece and only use for certain particularly dangerous situations. Having a rack on your vehicle dedicated for power armor maintenance would be amazing.
> 
> It would also be great to have multiple semi-deterministic locations for individual armor pieces rather than spawning the whole set in a TCL. I'd love to raid multiple dangerous POI's hunting for different power armor parts.
> 
> What are the plans on including them to the base game vs aftershock? I'm really afraid that if all this work goes into making an aftershock-restricted content, then 90% of players would never get the chance to interact with it.

Take a look at #61486 for the plans on core game exoskeletons.

**Pull request merged**
