### PR TITLE
Add daily health widget

### PR DESCRIPTION
**Pull request by phelieros**
#### Summary
Interface "Add daily health widget"

#### Purpose of change
Add widget to display `daily_health`, for use in customized sidebars.
Useful for those who likes to have all the obfuscated info right in the UI without having to look it up in the save file.

#### Testing
Used a few consumables that reduce daily health, added addictions that are harmful to it. In both cases displayed number reflected changes.

### CODE REVIEW

**Comment by harakka** [comment]
You should be doing these changes against experimental, we're not really adding new content to 0.H.

**Comment by Maleclypse** [comment]
Ok on review this would add translation in 0.H that won’t happen before release so I’m closing this. If something changes where 0.H isn’t releasing in near future this can reopen.

**Comment by RenechCDDA** [comment]
New features are not going to be added to stable, you should target master.

**Comment by esotericist** [comment]
to clarify: new features are not going to be added to _this_ stable release. there is a possibility of a point release to update 0.H down the road, but that isn't guaranteed. eventually we'll have another stable release. 

but right now we have to have a line or we'll never get stable out the door. it's been stuck in limbo for far too long as it is

**Pull request closed without merging**
