### PR TITLE
[CR}Simple vehicle auto-driving

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Features "Activity to auto-drive simple road routes"```

#### Purpose of change
An Activity whilst in charge of a car - open overmap and select destination, like the overmap auto-walk, will only preview route if destination is on a road though.

Vehicle will then attempt to drive there automatically.

#### Describe the solution
Vehicle will have a set of omt path points.
It finds the next point which is on the shared border of the current and adjacent overmap point, ( thanks to OrenAudeles for some Amazing Algorithmical Assistance  ) and paths there in a loop with pldrive()

Caveats : It's a bit dumb - it will just simply stop if it encounters an obstacle or a part gets damaged.
It cant avoid obstacles. it will stick to a fairly low speed.

It still can basically, without much input, make it far less tedious to travel a long road journey that you know is clear ( maybe you pre-cleared it )

[CR] because , I dont know for sure if I've got the tileray stuff down completely, where it pre-checks for potential collisions ahead of its proposed angle, sometimes it finds a tree near the corner of a road and stops, and its beyond me I think to tweak it any further when I dont really know what Im doing with it.

secondly - the turning is a bit last-minute - the centre-point of the vehicle gets to the point at which the road turns, and then the vehicle hs to turn drastically to align with the diagonal - A very long vehicle would certainly smash into trees as it turned in.

Hoping maybe someone can help tweak the algorithms here, but if not, its semi-usable and perhaps has some utility under controlled road conditions.

#### Describe alternatives you've considered
N/A

#### Additional context
Heres a GIF of the auto-driving

You can see it leaves the turns a bit late .  https://gfycat.com/fatallightheartedarkshell

### CODE REVIEW

**Comment by Inglonias** [comment]
Even what you have here is really impressive. Wonderful stuff.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/player-overmap-autotravel/20572/26

**Comment by OrenAudeles** [comment]
awwww yiss this looks (ignoring the overshooting) great! :D :+1:

**Comment by paulenka-aleh** [comment]
Looks impressive.

A question I have in my mind: should this be interface feature like now or rather a vehicle autopilot (e.g. robot controls + sensors + tracking device)?

**Comment by ProfoundDarkness** [comment]
Maybe instead of taking this away from the player (without such toys) we could instead extend this to robotic controls and such.  That way if you don't have robot controls installed you can still have this auto driving take place.  Meanwhile those who have such robot controls installed can sit back and let the car drive itself while they do something else, like read or play a game or something (sleep?).

I wouldn't recommend moving about the vehicle while it's in motion though...

**Comment by DieAxtImWald** [comment]
Wonderfull feature, if i only could use it... Autotravel on foot works, but autodrive with a vehicle not. The path is simply not visible. Testet different vehicles... What did i miss? a new world?

**Comment by anothersimulacrum** [comment]
It only works on roads.

**Comment by DieAxtImWald** [comment]
i've tested this on different roads. 
Guess, i have to test again with a new world...

**Comment by DieAxtImWald** [comment]
i can't get it. 
fresh install > no mods > new world > spawned a vehicle on a road > started to drive, but no route in the map available/visible. Shift + w does nothing. 
Autowalk works flawless. i've no idea why...

**Comment by joe9000** [comment]
can you make it treat #lake tiles as road to give boats some more use for it?

**Comment by davidpwbrown** [comment]
> Looks impressive.
> 
> A question I have in my mind: should this be interface feature like now or rather a vehicle autopilot (e.g. robot controls + sensors + tracking device)?

A full in-game autopilot may be possible on some vehicles, I can look into tht, so the player can do other things while the vehicle ( attempts to ) drive itself.

**Comment by davidpwbrown** [comment]
> Maybe instead of taking this away from the player (without such toys) we could instead extend this to robotic controls and such. That way if you don't have robot controls installed you can still have this auto driving take place. Meanwhile those who have such robot controls installed can sit back and let the car drive itself while they do something else, like read or play a game or something (sleep?).
> 
> I wouldn't recommend moving about the vehicle while it's in motion though...

as above

**Comment by davidpwbrown** [comment]
> i can't get it.
> fresh install > no mods > new world > spawned a vehicle on a road > started to drive, but no route in the map available/visible. Shift + w does nothing.
> Autowalk works flawless. i've no idea why...

Idk what to say really, the route should appear on the map , when you press shift+W, when you are in a vehicle, the vehicle is running with you in control of it, and the start and endpoints of the route are on a road.

**Comment by davidpwbrown** [comment]
> can you make it treat #lake tiles as road to give boats some more use for it?

Yes, good idea. I can do that.

**Comment by DieAxtImWald** [comment]
> > i can't get it.
> > fresh install > no mods > new world > spawned a vehicle on a road > started to drive, but no route in the map available/visible. Shift + w does nothing.
> > Autowalk works flawless. i've no idea why...
> 
> Idk what the problem may be really, the route should appear on the map , when you press shift+W, when you are in a vehicle, the vehicle is running with you in control of it, and the start and endpoints of the route are on a road.

Thanks for your reply. For now i quit playing CDDA. 
In a few weeks or so i will try again. Great time saving feature, so wont play without it :D

**Comment by ZhilkinSerg** [comment]
It is a pity you cannot yet auto sail in boats yet. In have a a pier base and a city across the lake that I raid at nights.

**Pull request merged**
