### PR TITLE
Remove token bash damage from knives

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Removes token bash damage from knives.  

#### Describe the solution
Removes bash from low weight knives where it makes up a third or less of the damage.

#### Describe alternatives you've considered
None

### CODE REVIEW

**Comment by Fris0uman** [comment]
Looks like you need to update some tests

**Comment by Maleclypse** [comment]
> Looks like you need to update some tests

Yeah, I'm trying to decide if I want to update the tests, add additional pierce damage, or a combination of both.

**Comment by fairyarmadillo** [comment]
> > Looks like you need to update some tests
> 
> Yeah, I'm trying to decide if I want to update the tests, add additional pierce damage, or a combination of both.

Most of the knives already do a crapton of stab damage, and could stand to be reduced.

**Comment by Karol1223** [comment]
Could you edit the affected weapons for ferals as well, while you're at it? I know this is going to affect the combat knife special attack, not sure if the other knife is going to be affected or not.

**Comment by Maleclypse** [comment]
> Could you edit the affected weapons for ferals as well, while you're at it? I know this is going to affect the combat knife special attack, not sure if the other knife is going to be affected or not.

Feral soldier doesn't have any bash damage on him?
```
"melee_skill": 6,
    "melee_dice": 2,
    "melee_dice_sides": 2,
    "melee_damage": [ { "damage_type": "cut", "amount": 6 } ],
```

**Pull request merged**
