### PR TITLE
Update junkfood.json

### PR DESCRIPTION
**Pull request by Regularitee**
> `SUMMARY: None "FUCKING FINALLY SOMEONE FIXES COOKIES SO THE BOXES AREN'T 2000% THE SIZE OF THE CONTENTS INSIDE"`

### CODE REVIEW

**Comment by KorGgenT** [comment]
1) your summary is invalid
2) cookies don't come in bags irl, generally.
3) do you really need to use that tone?

**Comment by Regularitee** [comment]
1. You're invalid. But really, it's to address the junkfood listed in #27863. And it's a one-word change, so doesn't need much of a summary. 
2. The cookie serving (that is, total volume in the container) is 50 grams in CDDA. According to google the average cookie is 16 grams. So roughly three, maybe four cookies. At that serving size they usually do come in bags/wrappers (with a cardboard insert, much like chocolate bars)
3. Well, it was meant as hyperbole. Though that said, a 6-month old issue, reported on multiple tickets, which only required a one-word change in the code (or two, since I did the same to Malted Milk Balls). So it was long overdue.

**Comment by anothersimulacrum** [comment]
> doesn't need much of a summary.
You still need a summary line, in this case ```SUMMARY: None```

**Comment by KorGgenT** [comment]
i do not think that picture of a plastic bag of cookies with a bow, that's obviously not a commercial way of cookies being sold en masse, is a reasonable response. go to any cookie aisle in america, and they're usually sold in plastic containers.

**Comment by ZhilkinSerg** [comment]
> 
> 
>  And it's a one-word change, so doesn't need much of a summary.

Use ```SUMMARY: None``` in that case.

**Comment by Regularitee** [comment]
Is this better, Kor?  

51CGwsYcmUL

In CDDA, cookie come in batches of four, weighing 50 grams. The pictured packet (not the box), is exactly four cookies together weighing 50 grams. I guess this would have been a better choice of image, but I didn't really expect any pushback on the choice of box versus plastic bags at the time so just grabbed the first thing on Google images.  ¯\_(ツ)_/¯

I mean, I cookies usually come in boxes. But the boxes are usually vastly larger than 50 grams, I thought.

**Comment by nexusmrsep** [comment]
It seriously has to be one of those scummy practices where you open a big box and find little cookies and lot of empty (sometimes packed) room. Notorious chocolates practice.
image

**Comment by kevingranade** [comment]
Denied due to poor attitude and weak rationale.

**Comment by Regularitee** [comment]
@kevingranade I know I'm rude abrasive at times, true. But is "a box is 95% empty space, 5% product" not a justified rational for it needing to be fixed? Imagine if each and every water bottle (0.5L liquid) were the size of an entire plastic jerry can (10L). Would it be preferable to leave it as is, or fix it? 

Improving the game and reprimanding me for bad behavior should be two separate issues.

**Comment by kevingranade** [comment]
You've already been reprimanded and ignored it, this is the first escalation.
The second escalation is you being banned from the project, because I don't have time to babysit people with poor impulse control.

The change itself is ALSO a problem, because the existence of a problem does not imply a particular fix. You have expended zero effort establishing what the correct contents are rather than simply that there is a disparity. Do that, stop being rude about everything, and follow instructions instead of arguing about them, and we can try to merge some PRs.

**Pull request closed without merging**
