### PR TITLE
Hacking on vehicle IDs

### PR DESCRIPTION
**Pull request by mutability**
Related to #19437. Not intended to be merged, this is just to throw ideas around.

A quick overview:

All the ID-related stuff is templated around the target type. Here I'm using `vehicle` but it should generalize to other types without too much trouble.

`PersistentID<vehicle>` is the long-term ID for a vehicle. It is a wrapper around a `long` mostly for improved type safety

`PersistentHandle<vehicle>` is a handle to a `vehicle`. It behaves somewhat like `weak_ptr`: you can get a handle from a `vehicle*` and if the vehicle is later deleted, all handles that refer to it are safely invalidated (`get()` will return `nullptr`). This isn't really used much yet, but the intent is that you can store PersistentHandles in long-lived structures where you need to have a safe, long-lived, fast reference to some other object that might move or be destroyed.

You can construct a `PersistentHandle<vehicle>` from just a `PersistentID<vehicle>`; the handle will try to locate the vehicle on demand. A `PersistentHandle<vehicle>` that refers to a `vehicle` that got deleted will also try to re-locate the vehicle by ID. The intent here is that handle-based references will survive a save/load cycle and will survive the target moving out/in of the reality bubble. What to do if you need to deal with a target that's currently out of the bubble is an unresolved question.

Locating vehicles is done by a specialization of `PersistentID<vehicle>::find_by_id`. In this implementation it just goes looking for a matching vehicle in the reality bubble.

`Persistent<vehicle>` is a helper mixin that `vehicle` inherits to provide the basic persistent ID hooks and invalidation of handles on destruction.

IDs are allocated on first use and are persisted in the saved json.

player_activity can store handles (they get serialized as the underlying ID).

I updated the vehicle interaction stuff to store the ID in the activity and use it to re-find the vehicle when the action completes. The other obvious place (that I haven't done yet) is the jumper cable stuff.

paging @mugling @Coolthulhu to the thread..

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The idea looks good.
Not sure about the split between handle/ID. Does handle "contain" an ID or does it require explicit refreshing from the ID?

The code is rather hard to read in places, though. Mostly because of similar names and lots of implicit casts.

While `long` would probably be enough for vehicles, later on we'll need something better for the rest of the types. We may need a bigint.

**Comment by mutability** [comment]
Handle contains an ID; that is what it _is_ to a large extent, it is a reference to some persistent object by that object's ID. There might be many handles with the same ID all referencing the same object. The control block / referent pointer works as a cache of the ID -> current in-memory object for that ID so that you can use a handle about as cheaply as a smartpointer.

I am considering dropping PersistentID as a separate class, there's no real reason that users of the code need to deal with the ID separately from the handle, the only places that should care about the structure of the ID is code that deals with persisting it to json.

Template code is always going to be somewhat hard to read, I don't know if there is much I can do about that. Which bits did you have trouble with in particular?

It is pretty simple to widen the `long`, I mostly just used `long` because it minimized the extra work I needed to do in the json stuff.

**Comment by Coolthulhu** [comment]
We need something sane to happen in the case IDs get to the end of the line.

It can be just a debugmsg+wrap, but it shouldn't totally give up on handing out further IDs.

**Comment by kevingranade** [comment]
The ID should only be attached to the vehicle for the duration of the
activity, not as an intrinsic part of the vehicle.

I don't think wrapping the ID in a smart pointer is a good idea, the smart
pointer implies that accesses are fast, but they might not be, this would
be much clearer if you simply used a handle (wrapper are round the id) to
retrieve a pointer, which is implicitly volatile as usual.

As discussed elsewhere, a simple sequence number does not have the
robustness we are looking for. It needs to be a uuid or aware of maps and
game sessions to manage concurrency and avoid collisions.

**Comment by mutability** [comment]
On 4 December 2016 at 02:26, Kevin Granade <notifications@github.com> wrote:

> The ID should only be attached to the vehicle for the duration of the
> activity, not as an intrinsic part of the vehicle.
>

Why?

How do you discover when you can release an ID, given that some references
might not be in memory?

As a more complex usecase (I just implemented vehicle activities because
they were a straightforward demo) consider using IDs for jumper cable
targets. There could well be an unloaded vehicle A that refers to loaded
vehicle B (or vice versa).


> I don't think wrapping the ID in a smart pointer is a good idea, the smart
> pointer implies that accesses are fast, but they might not be, this would
> be much clearer if you simply used a handle (wrapper are round the id) to
> retrieve a pointer, which is implicitly volatile as usual.
>

That's what this implementation does already?


> As discussed elsewhere, a simple sequence number does not have the
> robustness we are looking for. It needs to be a uuid or aware of maps and
> game sessions to manage concurrency and avoid collisions.


Where is this discussion elsewhere? What is the scenario where a sequence
number that is managed per-world (as these ones are) collides?

Oliver

**Comment by mugling** [comment]
> As discussed elsewhere, a simple sequence number does not have the robustness we are looking for. It needs to be a uuid or aware of maps and game sessions to manage concurrency and avoid collisions.

CAP theorum states this should be impossible. Databases are a good examples of attempts to solve that problem and they all typically select incrementing integers. Multiple users on the same save will will always be inconsistent for at least this reason (plus many other bugs we have).

> On 4 December 2016 at 02:26, Kevin Granade ***@***.***> wrote:
>  The ID should only be attached to the vehicle for the duration of the
>  activity, not as an intrinsic part of the vehicle.
> Why?

It would be conceptually simplerr if all objects just had an `id` and I can't see a significant disadvantage to that.

**Comment by mutability** [comment]
Not much point prototyping this further as kevin has mututally-incompatible ideas about the requirements for persistent IDs.

**Pull request closed without merging**
