### PR TITLE
[CR] Encumbrance Granularity

### PR DESCRIPTION
**Pull request by PropaneSoup**
Along with increasing Encumberance by a factor of 10, it also gives small encumberance penalties to the clothing modifications. The values for those were picked more or less on a whim, and are up for discussion to make them higher or lower. 

Other than the modificaiton encumberance, the functionallity of the rest of the system shouldn't have changed. If it did, it means I forgot a spot in the code, although I believe I got everything.

### CODE REVIEW

**Comment by Frost-wood** [comment]
An increase of encumberance by 10x seems rather... extreme

**Comment by PropaneSoup** [comment]
Functionally, nothing's changed. 10 encumberance now is what 1 used to be. This is to make it possible for the tailor's kit modifications to have small encumberance penalties, rather than a crippling +1 encumberance for a little extra armor. With this PR, if you armor a few pieces of clothing, you'll end up with a +1.

**Comment by Lain-** [comment]
Good idea.

**Comment by Snaaty** [comment]
Yeah, this is a great thing. I believe the next step should be to make encumberance penalty not simply reduce skills by a certain level but to give different penalties (with the same effect). 
This also would make space for a couple of traits slightly reducing/increasing encumberance penalties.

**Comment by PropaneSoup** [comment]
I resolved the merge conflict, although my Code::Blocks is failing to compile with the latest master, so I can't check that everything is as it should be. I'll try and find out what's wrong with it.

> EDIT: Perhaps someone with lots of common sense should also eventually look over the items and rebalance some of them that currently have the same encumbrance value, even though they shouldn't.

I was thinking the same thing myself.

**Comment by KA101** [comment]
Ah, a JSON audit, what fun.  >_<

**Comment by PropaneSoup** [comment]
For those that don't want to scroll past the mile and a half of a json change, how do these values sound?
Wooled: +2
Furred: +5
Leather: +4
Kevlar: +6

**Comment by KA101** [comment]
With those being equivalent to 0.x of the current system, so two kevlar'd things ~= 1.2 current!Encumbrance.  If so, I'm thinking wool is realistic but probably going to draw complaints for under-encumbering.  Fur seems about right, might go a bit higher.  I've not worn a lot of leather- or kevlar-lined gear so I'll leave that for comment from folks who have.

**Comment by PropaneSoup** [comment]
I've never worn much leather or kevlar myself (read: none), so I based those two off of more game balance than realistic.

**Comment by Snaaty** [comment]
I don't know the exact numbers but isn't 1.2 extra encumberance ( in the old system ) a little much for only relatively little extra protection?

**Comment by PropaneSoup** [comment]
Increase the protection/warmth bonuses a little bit now that there are actual drawbacks then?

**Comment by Rivet-the-Zombie** [comment]
That sounds good.

**Comment by KA101** [comment]
@DavidKeaton, others who wear kevlar-lined gear, thoughts?  (DaveK has stated he wore kevlar'd motorcycle gear at one point, IIRC.)

**Comment by KA101** [comment]
OK, in the interest of knocking down the backlog, I'll merge this and we can tweak it later.

**Comment by PropaneSoup** [comment]
Sounds good KA101, I'll keep an eye on the forums for complaints of OP-ness

**Comment by DavidKeaton** [comment]
Crap sorry about the delay on my ping.

**Comment by DavidKeaton** [comment]
Leather should be a 6 or 7, Kevlar a 4 or even 3.

**Comment by sparr** [comment]
I'd like to discuss possible rounding concerns, and non-concern ideas, related to this change. Should I open a new issue or is here good?

**Comment by PropaneSoup** [comment]
Open a new one, it's a more natural place for discussion, rather than a closed PR.

**Comment by sparr** [comment]
@PropaneSoup #11625

**Comment by DeNarr** [comment]
@PropaneSoup I thought the tailor kit specifically mentioned how upgrading your equipment with those enhancements were not supposed to increase encumbrance.

**Comment by sparr** [comment]
@DeNarr the patch changes that description to say it increases it a little. the problem previously is that increasing by 1 was too much. Now we have the option to increase by [what was] 0.1 which gives a lot more flexibility to people building new items and coding new crafting mechanisms

**Comment by DeNarr** [comment]
@sparr Well, now it just seems like people would need to micromanage every piece of equipment, trying to tell if that increase would push them over the encumbrance limit. If you have a suit that was 1, you used to be able to fit it down to 0, then add some small enhancements. Now the first enhancement would pop it right back up to 10.

**Comment by sparr** [comment]
@DeNarr no, the first enhancement will bump it up to 4-7, which is still "zero" on the old scale (assuming nothing major comes of my other issue regarding rounding). And there isn't a "limit". Making things more granular will also serve to smooth out the penalties. Previously in a lot of situations there was no penalty for 0, and it jumped right up to a significant penalty for 1 encumberence. Now we can have 10% or 90% or 150% of that penalty as the circumstances warrant.

**Comment by DeNarr** [comment]
@sparr I did not see any partial penalty that you are speaking of. It seemed to only give the penalty once it reached above 10. I also noticed that encumbrance is adding together over separate layers.

Related note, the character screen does not seem to report layered penalties separate from item encumbrance anymore.

**Comment by sparr** [comment]
@DeNarr there are many penalties for encumbeance. Some that previously had thresholds of E>=1 are now E>=10, true. However, some that previously did calculations with X-E are now using X-E/10, so you can have 0.1 to 0.9 as much penalty as E=1 used to produce.

**Comment by Snaaty** [comment]
Yeah, we probably want to avoid those thresholds at intervals of 10. It ony encourages tedious micro-management.

**Comment by DeNarr** [comment]
@sparr But does giving -.4 to dodge actually do anything?

Also, if we are going to stick with adding a static encumbrance each time we modify a piece of equipment, then I think for balance purposes we would need to change to adding a static armor value. Otherwise it would only be worth adding kevlar/leather to armor that is already strong.

**Comment by sparr** [comment]
A quick survey of the patch says...

These things now have smooth penalty increase from 0,1,...,19,20 instead of stair steps at 0/1/2:
reload time
move cost

These things still have thresholds at 10 (used to be 1):
hit roll
swim speed (slightly more granular)
melee skill
dodge skill
melee cost

However, over in #11625 I'm already starting a discussion about changing the order of operations on some of the threshold items to be smooth instead.

**Pull request merged**
