### PR TITLE
Removed restriction to blood draw kit so centrifuge can work with any container with blood

### LINKED ISSUE #23539: Hospital centrifuge doesn't recognize some blood samples
Game version: 0.C-27430-ge5d2149

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Upon inserting a flask or other small container containing any kind of blood - including containers of blood spawned by the game as part of regular loot of the location - into centrifuge, the sample
can be analyzed.

### Actual behavior
Centrifuge console reports "ERROR: Please use blood-contained samples".

### Additional notes
Shouldn't it be "blood-containing samples" in the message, anyway?

### Steps to reproduce the behavior
Insert game-spawned flask of blood into hospital's centrifuge, attempt to analyze it.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #23539.

### CODE REVIEW

**Comment by Chezzo** [comment]
IRL only one type of container fits in blood draw kits. And it comes included in the kit.

**Comment by Night-Pryanik** [comment]
I made it so any container can be placed on centrifuge, not in the blood draw kit.

**Comment by JKTraktor** [comment]
I hope there is still someone alive here, I just wanted to ask, how do I insert a container of blood into a centrifuge? I really don't understand, so please explain

**Comment by Night-Pryanik** [comment]
Just drop container on the centrifuge.

**Pull request merged**
