### PR TITLE
Change longest side on pistol crossbow to 42 cm

### PR DESCRIPTION
**Pull request by YuPro**
#### Summary
Balance "Change longest side on pistol crossbow to 42 cm"

#### Purpose of change
Other crossbows are 80-100 so it's nothing "pistol" in 70 cm.
45 cm will allow to store it in XL holsters.

#### Describe the solution
Changed "longest side" to 42 cm.

#### Describe alternatives you've considered
None.

#### Testing
Launched the game, made sure that no errors happen.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
https://www.amazon.com/Pound-Self-cocking-Pistol-Crossbow-String/dp/B00O369NI2 looks like this guy is 50cm. You gotta find actual specs for a hand crossbow that's 45cm for this to be mergable "it should fit in this holster" with no historical / real world justification isn't good enough. 

Mind you, I think you are right it is too long but gotta find some specs to prove it.

**Comment by YuPro** [comment]
Do I need to find variant with exactly 45cm length or just shorter is enough?
https://www.amazon.com/WILLIAM-TELL-ARCHERY-WT-Mini-Crossbow/dp/B08B5GCMXW - 38,1 cm, and variant on your link can be shorter without stock too. Actually, I'm not even sure if 51cm on amazon is about package or crossbow itself.

P.S. https://www.amazon.com/Crossbow-50-Pistol-Archery-Hunting/dp/B00FH7DRFG - almost exactly 45cm
@bombasticSlacks

**Comment by bombasticSlacks** [comment]
Sorry I was out for the day. Definitely doesn't need to be 45cm, my point was supposed to be "if you want it to be 45 you gotta find proof it should be 45". In the case of a real item that proof can be easy to find. 

Since you did some digging already pick a model that is a real pistol crossbow and adjust all of the attributes (weight, longest side and volume) to match. While your there it can also be useful to add a comment like:

```"//": "based on the Brand Name Product Name Hand Crossbow (and include a url link if you want)"```

Then if someone else comes along in the future they will know why it's the way it is and that someone already put work into it.

**Comment by YuPro** [comment]
Done

**Comment by YuPro** [comment]
@bombasticSlacks

**Comment by bombasticSlacks** [comment]
If you don't have good measurements leave it at 500. Round numbers like that signify that it's never been calculated. Otherwise just do LxWxH and ball park out a few chunks since it isn't a box

**Comment by YuPro** [comment]
@bombasticSlacks 
Volume changed

**Comment by bombasticSlacks** [comment]
gotta change Balance "Change "longest side" on pistol crossbow to 45 cm" to Balance "Change longest side on pistol crossbow to 45 cm"

**Comment by YuPro** [comment]
Done

**Comment by Maleclypse** [comment]
You have to leave the ####  in front of each part of the template instead of having two asterisks on each side of the section title for the PR validator test to pass.

**Comment by kevingranade** [comment]
This also needs a flag to make it not fit in a holster, because *it's a crossbow*.

**Pull request closed without merging**
