### PR TITLE
Mixing a fancy hobo no longer breaks the laws of physics

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

```SUMMARY: Bugfixes "Mixing a fancy hobo no longer breaks the laws of physics"```

#### Purpose of change

Fancy hobo recipe:

- 250ml spirits
- 250ml beer
- 250ml mixer

Result:

- Many *litres* of fancy hobo drink.
- Law of conservation of mass *broken*.

<details>
  <summary>Violate the basic laws of physics?</summary>

gif loading... you're welcome!

</details>

This was caused by `drink_hobo` having a weight of 249, a volume of 2, and the recipe producing *ten* portions.

#### Describe the solution

Given it was producing ten portions, I'm assuming the intent was to have something that could be consumed in about the same portions as wine, so I've made the following changes:

- Fancy hobos are now 5 units per 250ml, same as wine
- Fancy hobos provide quench 4, the same as wine
- The recipe now produces fifteen portions (750ml), thus obeying conservation of mass.

#### Describe alternatives you've considered

Having a portion size of 250ml (the same as beer).

#### Additional context

- I've not edited drinks before, so an extra sanity check that my changes are sane would be appreciated.
- I was previously cool with mass appearing out of nowhere, but @kevingranade tells me that [sometimes realism is not a bad thing either](https://github.com/CleverRaven/Cataclysm-DDA/issues/29770#issuecomment-485310957). :)

### CODE REVIEW

**Comment by evankimori** [comment]
I opened an issue similar to this at #28899. Just asking if this is the same level here so that I can close it off. :)

**Comment by pjf** [comment]
@evankimori : Oh, yes! That's almost certainly related. And these changes should hopefully fix that as well! :tada:

Thanks for spotting this!

**Comment by evankimori** [comment]
@pjf - Just trying to clean up my open tickets and ensure that I'm contributing to the community guv! :) Thanks for the update! 

Should I wait for the pull and further testing to ensure that the issue is gone? Or should I close it off for now?

**Comment by pjf** [comment]
@evankimori : This PR is already merged, so it's out there in the wild already if you want to test it. :)

Otherwise I'd say close the ticket (since we expect this change to have fixed it), and re-open if it persists (which means there's another Fancy Hobo bug hiding somewhere!).

Thanks again for the reporting and issue maintenance! :)

**Comment by pjf** [comment]
@evankimori : Also your vehicle in that issue report is *awesome*! :)

**Comment by evankimori** [comment]
@pjf - Thank you! There's a reason I got awarded 'Vehicle God' as my Reddit flair. XD I make it my business to test all the vehicle parts you folks come up with! 

Closing the issue ticket now.

**Pull request merged**
