### PR TITLE
Revert save and exit on SIGHUP

### LINKED ISSUE #18486: Autosave upon exit can be an issue.
Some background info: http://smf.cataclysmdda.com/index.php?topic=13298.0

Since #18212 was merged it is no longer possible to avoid a gamesave by exiting the game via the close window button.

While C:DDA is ostensibly a roguelike, there are certainly situations where not autosaving is desirable (e.g.: preserving a save where a glitch or bug killed your character).

Anyway, this issue is here so that some official implementation of quitting without saving can be discussed and added to the game.

### PR DESCRIPTION
**Pull request by mugling**
Arguably causes more problems than it solves:
- Greatly increases difficulty of debugging
- Destroys saves on JSON load error
- Changes the status quo about save scumming

Closes #18486 
See also http://smf.cataclysmdda.com/index.php?topic=13298.0

> This has a nasty side effect outlined in git. If you load a game which doesn't load due to JSON error on load, it saves an invalid character on exit rendering the save unplayable.

Please add thumbs up/down dependent upon your viewpoint leaving the comments for alternative solutions

### CODE REVIEW

**Comment by Zireael07** [comment]
In the linked thread, I suggested making it an option - the default would be reverted behavior but if someone plays over SSH and wants save-on-connection-lost, s/he could turn it on. But I'm not sure if that's necessary - I recall two aborted SSH server attempts but am not sure if there's one at the moment.

**Comment by Coolthulhu** [comment]
Should be pretty simple to make it a switch. While going with the ssh-unfriendly option is better than enforced saving, it may be easy to combine those two.

**Comment by mugling** [comment]
@Coolthulhu I'm not sure if it's worth the complexity to be honest

**Comment by mugling** [comment]
Does anyone want to claim the task to work on a configuration switch or are we to go with this?

**Comment by Coolthulhu** [comment]
It's OK I guess. Will merge in the next run if no one takes it before me.

**Comment by Coolthulhu** [comment]
Github interface doesn't work well here, I'll merge right away and then revert (the revert) if it breaks.

**Pull request merged**
