### PR TITLE
Fix cooked (and fried) morel mushrooms still being poisonous.

### LINKED ISSUE #28443: Cooked (and Fried) Morel Mushrooms Are Still Poisonous
**Describe the bug**  
Cooking a morel mushroom is supposed to remove the poison from it. Even after cooking, it's still poisonous to eat.

**To Reproduce**  
Start a new game, wish in a cooked morel mushroom, attempt to eat it. Get the poison Y/N, then press Y and eat it. Presto! Food poisoning + poisoned.

**Expected behavior**  
You eat the cooked morel mushroom. Yum yum. No barfy.

**Screenshots**  
https://cdn.discordapp.com/attachments/143055624828223488/551130758367150090/unknown.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37564-g412ee85
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead (Tested this on a vanilla world with no mods installed.)

### PR DESCRIPTION
**Pull request by ianestrachan**
#### Summary
```SUMMARY: Bugfixes "Fix cooked/fried morel mushrooms being poisonous."```

#### Purpose of change
Fixes #28443 

#### Describe the solution
Cooked and fried morel mushrooms copy from the basic morel mushroom, which has the use_action of `POISON`. This PR overrides the use_action to revert to the default one for cooked/fried morel mushrooms while leaving the base one untouched.

#### Additional context
Tested this by wishing for all three types of mushrooms and eating them. Only the basic morel mushroom causes poison.

### CODE REVIEW

**Comment by DracoGriffin** [comment]
Welcome back @ianestrachan !

**Comment by ianestrachan** [comment]
Thanks @DracoGriffin, it's been a long time. I've been playing experimentals here and there and thought I'd see if I could contribute again.

**Comment by ZhilkinSerg** [comment]
Please do not forget to [lint](http://dev.narc.ro/cataclysm/format.html) json files which aren't in [blacklist](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/json_blacklist).

**Comment by ianestrachan** [comment]
@ZhilkinSerg Thank you. I'll do that for future json changes.

**Pull request merged**
