### PR TITLE
[DinoMod] use fungalize_into

### LINKED ISSUE #47145: Friendly baby monsters disappear when they grow up
# Describe the bug

DinoMod includes tameable baby dinos that cannot be tamed when they are adults. The intention is that you can therefore have huge and dangerous dino pets, in the same way that people have pet elephants and tigers today if you put in the time and effort. However, Discord user Elizzyble reports that the baby dinos just disappear instead of growing up into adult dinos with the "friendly" tag, I'm betting because they lack the same "catfood" or whatever tag to enable it.

# Steps To Reproduce

1. Debug spawn a velociraptor egg
2. Debug time ahead a week or two. 
3. Give the baby raptor catfood.
4. Debug time ahead a month.
5. Bye bye pet raptor

# Expected behavior

Adult spawns with the "friendly" tag

# Versions and configuration

Mods loaded: DinoMod

# Additional context

Second test from same player here https://discord.com/channels/598523535169945603/598523535169945607/783899516863774720 Can't find the first report

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Mods "use fungalize_into"

#### Purpose of change

Implement new fungalize_into mechanic

#### Describe the solution

Give every basic zombie dino, pterosaur, and mosasaurus a  fungalize_into entry, create new fungal versions for Qianzhousaurus, Amargasaurus, Pteranodon, Quetzalcoatlus, and Mosasaurus. Add Amargasaurus, Pteranodon, and Quetzalcoatlus to fungal spawn lists. Updated for compatibility with #49439 Added monster and monstergroup updates from #49585 so this can move forward so now incorporates content from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/521 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/625 . Should fix #47145 by fixing some juveniles

#### Describe alternatives you've considered

More fungals, especially for brute evolutions. Shady fungal zombie dino?

#### Testing

Game loads, no errors, monsters look right
Screen Shot 2021-07-23 at 6 59 26 PM

#### Additional context

Thanks to @Fris0uman for making this happen

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
I have been waiting to review this one until it comes out of draft.  Are you waiting on my review to take it out of draft?   Because that would be amusing if that's the case.

**Review by Maleclypse — APPROVED** [review]
This looks great! 

edit:  I've rerun the tests to make sure I didn't miss anything.

**Comment by LyleSY** [comment]
I was just waiting for a chance for a clean test, all good

**Comment by actual-nh** [comment]
Looks like spacing stuff re JSON formatting... sigh.

**Comment by LyleSY** [comment]
Tried a few methods of fixing this, slicing it up into new PRs that are hopefully less broken by github

**Pull request closed without merging**
