### PR TITLE
Antenna changes

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
Balance "Changes to material and crafting recipe for the antenna"

#### Purpose of change
The antenna was the last problem-causing item made of aluminum that I know of. The issue is that most commonly antennas aren't even made of aluminum. This applies several changes to make antennas more what they should be.

#### Describe the solution
- Changes the antenna's material to copper and the description to reflect that.
- Changes the antenna's recipe massively. It now requires electronics of 2, is present in the Ham Radio Illustrated magazine, requires the bold turning quality instead of metal sawing, needs a two way radio or an RC control as tools to craft, takes significantly longer and uses copper wire instead of steel or butter knives.
- Changes the directional antenna recipe to use an antenna instead of 6 wire.
- Moves the current old antenna recipe to Innawoods, as Innawoods players over at discord informed me antennas are currently either the only or the most available way to train up electronics. The note is added that the recipe should probably be changed there soon but what happens is Innawoods is beyond my interest.

#### Describe alternatives you've considered
Initially, I was supposed to differentiate the antennas by their uses, however, I don't believe I can justify the recipe edits just for a little more realism where I honestly don't know much of anything when it comes to electronics.

#### Testing
Booted up the game, no crashes, recipes appear as intended

### CODE REVIEW

**Comment by a-chancey** [comment]
Missed the discord discussion so I'm throwing in my two cents. Just want to mention that this change makes electronics impossible to level without books. Even with books, you can only get to practical 1 by using the practice recipe for electronics soldering.

Antenna is currently the *only* autolearned electronics difficulty 0 recipe, and with how crafting failure chances work, only the practice will not auto fail at practical 0 if antenna is changed to difficulty 2.

just throwing in my two cents. If we're fine locking an _entire skill_ behind books, then I guess I'll drop my complaint :D

**Comment by Karol1223** [comment]
> Missed the discord discussion so I'm throwing in my two cents. Just want to mention that this change makes electronics impossible to level without books. Even with books, you can only get to practical 1 by using the practice recipe for electronics soldering.
> 
> Antenna is currently the _only_ autolearned electronics difficulty 0 recipe, and with how crafting failure chances work, only the practice will not auto fail at practical 0 if antenna is changed to difficulty 2.
> 
> just throwing in my two cents. If we're fine locking an _entire skill_ behind books, then I guess I'll drop my complaint :D

Yesterday someone pointed out that electronics should probably be that one skill that could actually be locked behind books or disassembling a copious amount of electronic devices and personally I agree with that. I am not sure if an average poor knowledge (skill level 0) would allow you to actually meddle with electronics at all (and certainly not in the form of an antenna as making a usable one that actually works with frequencies is a whole lot harder than clumping some metal together). The one situation where this would actually flip the scenario upside down is Innawood, which is covered in this PR. I don't think it's an unrealistic approach but if the devs believe otherwise I am open to changing it (at least temporarily, because the antenna seriously shouldn't be the basic one)

**Comment by a-chancey** [comment]
Like I said, I missed the discussion, and since I have a little bit of a microelectronics background from college, maybe I wouldn't be a good source for folks who don't know _anything_ about electronics heh

I've been considering looking into reworking some electronics stuff after next stable drops, and knowing they're gonna be locked behind books completely is great information. Our current system is entirely unrealistic. You can't just take the circuit board you took out of a digital camera and wire it so it's magically a handheld game system. So many electronics recipes require multiple "circuit boards" and "processor boards" but don't require a computer or any other way to actually reprogram them or flash/install/set up software.

And seeing as the general Internet is permanently down post cataclysm, it's not like you're gonna be able to access online resources for *how* to program shit - software development is completely ignored as part of electronics crafting, and in reality, most of those how to books are at best coming with a (horribly out of date) software disc, and at worst telling you to download the source from their website. 

Bah I need to get off my ass and add arduinos. I don't know that we need to get fully into flashing individual programmable logic chips or crafting PCBs, but a programmable arduino (or family of microcontrollers like arduinos) would make a ton of sense

**Comment by Karol1223** [comment]
> I've been considering looking into reworking some electronics stuff after next stable drops, and knowing they're gonna be locked behind books completely is great information. Our current system is entirely unrealistic. You can't just take the circuit board you took out of a digital camera and wire it so it's magically a handheld game system. So many electronics recipes require multiple "circuit boards" and "processor boards" but don't require a computer or any other way to actually reprogram them or flash/install/set up software.

If you don't mind, please notify me when you actually get to reworking electronics. I don't know a whole lot about the topic but I'd be more than happy to assist in this in any way possible, even if just the grunt work of coding in some items or changing disassembly recipes. I'm all in for making the crafting and salvaging more realistic on any step of the way.

**Comment by a-chancey** [comment]
I may lay some groundwork and get some new parts introduced and worked into recipes before content freeze, but the software side of electronics crafting is gonna have to wait for post stable :)

**Comment by Amoebka** [comment]
Maybe I'm wrong, but I feel electronics 0 -> 1 should be something like connecting a battery and a bunch of LEDs with copper wires. Low skills levels are generally assumed to be basic stuff people can figure out without dedicated textbooks.
For comparison, training chemistry 0 -> 1 is done by mixing soap with water.

**Comment by Karol1223** [comment]
> Maybe I'm wrong, but I feel electronics 0 -> 1 should be something like connecting a battery and a bunch of LEDs with copper wires. Low skills levels are generally assumed to be basic stuff people can figure out without dedicated textbooks. For comparison, training chemistry 0 -> 1 is done by mixing soap with water.

Honestly, I agree. Would make for a decent practice recipe if someone were to add that.

**Comment by a-chancey** [comment]
> Maybe I'm wrong, but I feel electronics 0 -> 1 should be something like connecting a battery and a bunch of LEDs with copper wires. Low skills levels are generally assumed to be basic stuff people can figure out without dedicated textbooks.
> For comparison, training chemistry 0 -> 1 is done by mixing soap with water.

I’m really torn on this, as someone who studied electronics. 

Did you know that LEDs have polarity that’s denoted by one lead being longer than the other? Most folks don’t. Also hooking up a single LED to a battery is going to blow the LED pretty much instantly - you’d need resistors to reduce the current. And without documentation(or a LOT of prior knowledge), you’ll waste so many components. 

I’ve convinced myself that electronics should probably be completely locked behind books and a handful of proficiencies lol

**Comment by Amoebka** [comment]
Please take a good look at design docs first. Skill levels up to and including 4 are supposed to be hobbyist tier. 5 is undergrad. Skill level 1 in cooking is gained by learning to use a pot to boil water. Skill level 1 in survival is gained by wrapping pants into a makeshift bindle. This is the level of mastery we are talking about.

I understand that we all like to think our knowledge is unique and irreplaceable, but you don't see me insisting chemistry should be impossible to learn. The basics or anything are basic.

In your specific example: I did know that LEDs have polarity. Most of the ones I saw outright had "+" printed on the glass near the right lead. If you blow it up because the battery is too strong - that's wasting ingredients in a failed craft attempt, you learn not to do it in the future (gain skill progress). This is exactly the type of thing that can be figured out without books.

Remember, most low-level electronics crafting isn't really even circuit soldering from scratch. You literally just take appliances apart and recombine the parts.

**Comment by Fris0uman** [comment]
The solution to "There's no recipe to train lvl 1 electronic" is to add more low level practice recipe and not to keep antenna being made by cutting a butter knife in two

**Pull request merged**
