### PR TITLE
Allow using Niten with fake katanas

### PR DESCRIPTION
**Pull request by Soadreqm**
Right now, of the various katanas, Niten Ichi-Ryu only works with regular, diamond and burning flavors. This adds the cheap, flimsy knockoffs to the list, and the cheap wakizashis and nodachis too. As I understand, they're basically identical to the real swords, except made of shittier materials.

### CODE REVIEW

**Comment by kevingranade** [comment]
The knockoffs are also not going to be balanced prooerly, th8s is more
important if you're trying to make sophisticated attacks as with a martial
art.

**Comment by Coolthulhu** [comment]
It allows the training wooden ones and ones with heavy fire-generating equipment on them.
Allowing the ones made from crap steel wouldn't be that much of a stretch IMO.

**Comment by Mecares** [comment]
Making them usable seems sensible to me, the worse handling should be already covered by the to hit values.

**Comment by pisskop** [comment]
At high skills you negate to-hit values, making these knock off effectively the real thing.


No, martial arts is about practiced manuvers using carefully balanced augments and finely tuned movements.  These knock-offs arent made with combat in mind.  They are wall pieces.

**Comment by Mecares** [comment]
Obviously it should be harder but completely impossible?

**Comment by Soadreqm** [comment]
Well, the budget steel version is explicitly said to have "the right edge and weight". It's supposed to be inferior in materials used, not design, the main drawback being that it breaks easily. Exactly the same shape as a real sword, but made of a different steel alloy.

The aluminum version is an actual wall piece, and more of a stretch as realism goes. Niten already works with the ordinary wooden cudgel, though, and works the same way with wakizashis, katanas and nodachis despite the size difference, so I don't think the weapon weight needs to be an exact match. Also, the aluminum one has has shit damage, actually very close to the wooden cudgel. 6 bash 2 cut instead of 8 bash, and +1 to-hit instead of +2.

**Comment by kevingranade** [comment]
> It allows the training wooden ones

These are designed to have the correct balance, that's the whole point.

> and ones with heavy fire-generating equipment on them.

I agree, they shouldn't be allowed either, but those should also be relegated to a, "we don't care about physics or making sense" mod anyway.

> Niten already works with the ordinary wooden cudgel

WTF? How the hell are you supposed to do draw cuts with a cudgel? Those should go.

**Comment by mugling** [comment]
> but those should also be relegated to a, "we don't care about physics or making sense" mod anyway.

Tangent: effectively the fireweapons mod would become opt-in?

**Comment by Coolthulhu** [comment]
> effectively the fireweapons mod would become opt-in?

That would be a good idea. They are pretty crazy and pretty useless.

**Pull request closed without merging**
