### PR TITLE
Add butter to pie recipes.

### PR DESCRIPTION
**Pull request by sharkfinsouperman**
#### Summary

`SUMMARY: Features "Add butter to pie recipes."`

#### Purpose of change

Resolves issue #37471

#### Describe the solution

Added the equivalent of 1 stick ( 8 tbsp ) of "any-butter" ~~and "lard"~~ to the following recipes:

- Fruit Pie
- Veggie Pie
- Meat Pie
- Maple Pie
- Humble Pie

Update: Lard units of 250ml are too big for use, so they've been removed from the recipe unless more reasonable units become available.

#### Describe alternatives you've considered

Leaving it as is.

#### Testing

Compiled locally and made pies.

### CODE REVIEW

**Comment by pjf** [comment]
@sharkfinsouperman : Oh hey! Welcome to github and CDDA! And thank you for saving us from terrible crusts! :)

The auto-checking bots are pretty picky about [JSON styling](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md). However if you've got a local build environment set up, you can run `make style-json` and it will adjust the formatting for you. Then it's just a quick commit and push.

Thanks again for the tasty PR! 🥧

**Comment by sharkfinsouperman** [comment]
It seems Notepad++ and its JSON plugin likes to use tabs on newlines when it formats.

I'll run `make style-json` and try another push.

**Comment by sharkfinsouperman** [comment]
Its the hidden tabs. `make style-json` didn't detect and fix them, so I'll do it by hand.

**Comment by sharkfinsouperman** [comment]
Ugh, forgot to update the calories in game generated pies.

Used lard instead of butter because these are mass produced pies.

**Comment by pjf** [comment]
I've applied this to my local branch, and can't way to make tasty pies. Thank you! :)

(I don't have permission to merge to master, but I do like welcoming first-time contributors!)

**Comment by sharkfinsouperman** [comment]
Thank you for the greet. I was feeling a little stressed and grumping when I made the PR because this old dog had to learn and relearn a lot during the process, so I apologize for not responding directly until now.

**Comment by pjf** [comment]
I haven't checked the JSON files to see how much a unit of lard is, but having just made a pie with 2,600 calories per slice, I think that 8 lard might be a bit much. :)

**Comment by sharkfinsouperman** [comment]
Thank you for testing. I only tried butter and neglected to try lard in my own trial.

The problem is I mistakenly assumed butter and lard/tallow shared the same unit volume. While butter is 15ml or 1tbsp per unit, lard inherits its values from tallow, which is 150ml or 1/2cup per unit.

I'll make the necessary changes to hopefully correct this oversight.

Ugh, I feel oils, butter, lard and tallow should share the same unit volume in the JSONs as they're all interchangeable in many cases involving cooking, and not being able to use less than 1/2 of lard/tallow could be restrictive in some cases now that nutrition has been improved and acts more finicky. Standardization would also make recipes simpler to write and add without the need to worry about differing unit volumes.

Out of curiosity, how would changing tallow/lard unit volume from 150ml to 15ml and adjusting all related recipes affect games in progress that update?

**Comment by sharkfinsouperman** [comment]
After reviewing the JSONs, I had to remove lard. :(
Unit size of 250ml is too large for this recipe and unreasonable to work with in a kitchen. >:(

**Comment by sharkfinsouperman** [comment]
I just finished testing the failed recipes and they were within expected and acceptable caloric limits.

I also don't understand why the bot passed with the lard pies of doom, but it won't pass now that they've been removed.

**Comment by CSHague** [comment]
If you remove ingredients it changes the average so you have to change the calorie values of the default pie so it falls within the acceptable range. I found this out when I fiddled with the canned fruit calories.

**Comment by kevingranade** [comment]
Feel fee to reopen if you can sort out the nutrition test issue, that is indicating that something is inconsistent.

**Pull request closed without merging**
