### PR TITLE
Fixed the behavior of the zombie burner (and WONDER spells in general)

### LINKED ISSUE #59054: Zombie burner explouding. Bug or feature?
### Describe the bug

 After [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139)
Killing zombie burner cause them to exlpode

I think, problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/58980 
But I didnt find anything in this pr about adding to zombie burner explouding effects
And now its very hard to loot military objects, becouse of exlouding zombie burners, which will burn all there and nearby loot into ash
And I am playing without magiclysm

Text of crash. I will also add crash and debug log

DEBUG    : ERROR: Fireball Death has invalid spell effect.

 FUNCTION : void spell_effect::none(const spell&, Creature&, const tripoint&)
 FILE     : src/magic_spell_effect.cpp
 LINE     : 1249
 VERSION  : 4608ba2

### Steps to reproduce

Update game to [Cataclysm-DDA experimental build 2022-07-07-0033](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0033)
Spawn zombie burner
Kill him
See him unexplouding
Update game to [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139)
Spawn zombie burner
Kill him
See crash text and explouding of the zombie

### Expected behavior

If its not new feature - I wanted to see zombie burner without explouding
If it is new feature - I dont want to see crash text, and its needed related pr

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 4608ba2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9068339/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9068341/debug.log)

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Bugfixes "Fixes spells with the WONDER flag"

#### Purpose of change
Fixes #59054 
Mitigates #59248 

#### Describe the solution
Wonder spells were, despite their documentation, executing ALL of their additional spell effects after choosing a random number of them.

#### Testing
Tested the zombie burner. It usually does not explode now.
Magic spell unit tests are passing. If someone wants to do some more in-depth tests, feel free. I have no Magiclysm experience.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Could you please test and confirm that with your changes burners ain't dying twice, like I described in #59054?

**Comment by Inglonias** [comment]
@Night-Pryanik Given what I know about how this works I can say "maybe". I'm out to lunch at the moment, but I will test it when I return to the computer.

**Comment by Inglonias** [comment]
They're still dying twice. I wasn't planning to fix that, to be perfectly honest. We can either split that out into its own issue, or I can take a further look at it before merging. I'll leave that up to whoever is merging the code.

image

**Comment by Inglonias** [comment]
I'm going to recommend that you split that out into its own issue. It looks like any monster with a death spell dies twice. 
image

**Comment by Inglonias** [comment]
Created an issue for the double death bug at #59366

**Pull request merged**
