### PR TITLE
Complexify the RM13 Armor

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Update RM13 to new armor standards"

#### Purpose of change
RM13 combat armor was still using the old system of coverage, and weirdly got thicker (2mm->5mm) when powered even though a material specifically exists to represent it getting stronger when powered.

#### Describe the solution
The new armor is 3mm in total. 1mm of standard unlayered kevlar, 0.5mm of carbide, and 1.5mm of hyperweave. Since each layer is made of non-rigid material they are all 100% coverage. Eyes are 1mm ballistic glass and 1mm thermoplastic resin since they must be of a different material, and feet trade 0.5mm of kevlar for 1mm of leather and have 2mm of rubber to represent the soles. Base encumbrance, fitted, is 8, since it is roughly similar to one of the Kevlar jumpsuits in terms of thickness.

When powered on, the armor remains the same thickness, but its hyperweave becomes charged hyperweave. Encumbrance reduces to 2. Power draw was changed from 466w (5 per 18 seconds) to 100w (1 per 10 seconds). This is a fairly high buff but I am using the other hypertech armors as comparisons - phase immersion uses 40w, while power armor uses as little as 500w (admittedly this is suspect as the power armor interface bionic is no longer canon).  It being charged now has an overall lower impact on its total defensive rating so the extreme power cost is no longer as necessary.

Also, the armor is no longer conventionally repairable as it is somewhat nonsensical that you can tailor this hypertech armor back together, i. Instead it is nanofab repaired like the phase immersion suit. Since it can be assembled from a nanofab template this felt fitting. As a result it is no longer fitted/unfitted since you cannot refit no_repair items.

One of the first things any survivor does when obtaining this armor is mod it to accept any battery instead of just plutonium fuel batteries. As such I have made it able to accept all heavy batteries as there is nothing actually special about the plutonium batteries, they're just efficient normal batteries that are interchangeable with regular ones. There would be little reason to design an armor that intentionally is only able use fewer batteries than it otherwise could based on its magazine well.

#### Describe alternatives you've considered

This is part of a broader goal of mine to rework the power armor suits to be more appropriate as well. I'm waiting for Bombastic's dehardcode of power armor but I aim to make the power armors more representative of layered armor plating and alter their encumbrance changes - it is super weird that field combat armor had *zero* encumbrance when unpowered making RM13 clumsier than power armor.

I also intend to distribute (usually damaged or faulty) RM13s to bio-operators as their sprites seem to indicate they are wearing them and these enemies were going to become ferals to justify their CQB powers.  Making them into "Rivtech-kitted spec ops" will be a good way to make Rivtech stuff reasonably obtainable and also keep these enemies special to make up for their newfound lack of bionics.

#### Testing

loaded up in game, seems to be working! I also tried having Hub01 repair the armor and I was able to complete that dialogue. After 24 hours they handed me the repaired armor.

#### Additional context
rm13a3
rm13a1
rm13a2

### CODE REVIEW

**Comment by Broken27** [comment]
This is really good, nice work.

**Comment by bombasticSlacks** [comment]
For the feet, sole rubber is usually 6mm also you should split it to the sublocation so people can properly layer stuff above the foot. 

I would just ditch the kevlar it isn't doing much and it gives the impression this is a more "terrestrial" design than it actually would be. Leather I'm less sold on since it's more of an accent. Perhaps the new foam as a partial layer would make sense for aesthetics. 

On that note I don't think these will get distributed to bio ops. Perhaps a lab facility could get someone wearing one as a boss but it shouldn't end up in general distribution. There's lots of cool spec ops stuff we should put on bio ops that isn't sci Fi.

**Comment by anoobindisguise** [comment]
> For the feet, sole rubber is usually 6mm also you should split it to the sublocation so people can properly layer stuff above the foot.
> 
> I would just ditch the kevlar it isn't doing much and it gives the impression this is a more "terrestrial" design than it actually would be. Leather I'm less sold on since it's more of an accent. Perhaps the new foam as a partial layer would make sense for aesthetics.
> 
> On that note I don't think these will get distributed to bio ops. Perhaps a lab facility could get someone wearing one as a boss but it shouldn't end up in general distribution. There's lots of cool spec ops stuff we should put on bio ops that isn't sci Fi.
> 
> Oh also I feel like having big batteries is kinda silly for a sleek suit. Maybe it should get the smart phone treatment and just be a rechargable device. The amount of power it holds could be high with a high draw meaning it pulls a lot of base power.



Per your advice,
- Got rid of standard kevlar, it is now solely 1mm carbide, 2mm hyperweave. encumbrance increased to 10 unpowered, 3 powered.
- Battery now functions like smartphones, it has a 5000kJ internal battery. Power draw increased to 10 kJ/minute from 6 kJ/minute. Giving it an operational lifetime, per charge, of about 8 hours.

**Comment by Shados** [comment]
Might want to make the mouth & eyes coverage `OUTER` layer to allow it to be compatible with gas masks, similar to the phase immersion suit.

**Comment by bombasticSlacks** [comment]
I appreciate the thought but what does this look like with outer eyes and mouth. The reason the phase immersion is outer is because it's a space helmet so a huge glass sphere. If this is all one sleek integrated piece, how is it layed out for that to be the case.

**Comment by anoobindisguise** [comment]
Hub01 repairs are now functional. Same process as the phase immersion suit.

> Might want to make the mouth & eyes coverage `OUTER` layer to allow it to be compatible with gas masks, similar to most helmets & the phase immersion suit.

The armor already provides more than enough enviro protection for mouth to count as a gas mask, so this is probably not necessary. And as Bombastic said the armor keeps fairly low profile, so leaving the NORMAL eyes/mouth layer open didn't feel needed.

**Pull request merged**
