### PR TITLE
Removed artifact with super clairvoyance showing debug fields in item description

### LINKED ISSUE #22417: See through all artifact allows me to see rot time of food in crafting menu?
Game version:
0.C-24831-g6a32f4f
Operating system:
OSX
Tiles or curses:
curses
Mods active:
DDA, Disable NPC needs, folding parts, vehicle additions, tanks and other vehicles, disable religious texts, no antique firearms, stats thru skills and food preservation through ionizing radiation

I found an artifact that has a passive "See through everything" effect. When I am in the crafting menu it lists all sort of additional (hidden?) values for food and other recipes. 

screen shot 2017-11-13 at 13 23 16

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #22417.

I think that if player or dev needs debug fields, he can activate debug mode.

### CODE REVIEW

**Comment by Soyweiser** [comment]
Now I'm wondering how you activate debug mode.

**Comment by AMurkin** [comment]
Bind a key at keybindings and hit it.

**Comment by Soyweiser** [comment]
Thanks AMurking, will update the wiki with this information. (I had totally missed it).

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
> Is it still useful?

Yes, it is. It will show the neighborhood in the large radius, and plus through the walls too.

**Pull request merged**
