### PR TITLE
[RDY] Fix interference effect of radio messages in localized version

### PR DESCRIPTION
**Pull request by BrettDong**
To emulate the effect that the radio sound is unclear due to weak signal and interference, the program walked through the `std::string` and replace characters with `a-z` or `#` symbols. This approach works fine with languages which a letter takes exactly a byte to store. But for languages such as Chinese, Japanese and Korean, a character might take two or even three bytes to store in memory. For instance, consider a case when the radio message (localized) contains a Chinese character, encoded as `0xe7 0x9a 0x84` in memory. In the `for( char i : str )` loop, the program replaces the first byte `0xe7` to `0x23`(`#`), then the sequence becomes `0x23 0x9a 0x84`. These three bytes might represent another Chinese ideographic character. "OK,"  you might say, "then the sentence becomes senseless, didn't we achieve the desired 'fuzzy' effect too?". Yes, however, these three bytes also may represent nothing: they are illegal, or in another word, invalid, UTF-8 sequence.

Players in Chinese community complained that radio messages were often unreadable, either blank, or full of `#` symbols and other weird Unicode symbols. I investigated and found that the unreadable message weren't because of "weak radio signal". When there is only a few hashes in the English version, the message is still completely unreadable in Chinese version. The reason is the UTF-8 string is corrupted.

### CODE REVIEW

**Comment by BrettDong** [comment]
What the fuck?
```
src/cata_utility.cpp:21:10: fatal error: 'codecvt' file not found
#include <codecvt>
         ^
1 error generated.
make: *** [obj/cata_utility.o] Error 1
```

Isn't `<codecvt>` a C++11 standard header?

**Comment by Coolthulhu** [comment]
> Isn't <codecvt> a C++11 standard header?

The header is `<locale>`.

**Comment by kevingranade** [comment]
Classic ASCII-only string handling, yuck, and thanks for the fix.

cppreference indeed says to use the <locale> header, it's also possible that gcc is lagging in facet support, see http://stackoverflow.com/questions/15615136/is-codecvt-not-a-std-header

Try stripping the reference to codecvt, that should work.

**Comment by BrettDong** [comment]
Someone on that stackoverflow page said 'code conversion facets' were
added in GCC 5. codecvt is the simplest solution to do the UTF-8
std::string / wide std::wstring conversion as far as I know. If
upgrading compilation environment isn't an option here, I might be going
to try out other solutions but they're quite more complex:


* Call OS-dependent API (MultiByteToWideChar on Windows, mbtowc on *nix)

* Use a third-party library:
https://www.codeproject.com/kb/string/utfconverter.aspx

**Comment by BrettDong** [comment]
I removed codecvt and now use system API instead. It's working fine on Windows, but needs testing on *nix systems.

**Comment by BrettDong** [comment]
I removed codecvt and now use system API instead. It's working fine on Windows, but needs testing on *nix systems.

**Comment by kevingranade** [comment]
Cool, I'll test on linux while merging.

**Comment by BrettDong** [comment]
You'd better test it with different languages, including Russian and C/J/K whose characters are multi-byte thus truly utilizing the UTF8->wchar_t->UTF-8 conversion procedure. I want to test too, but the CPU speed is so terribly slow in virtual machine. I've been waiting for half an hour, and the compilation is still on-going.

**Comment by kevingranade** [comment]
I'm getting the "utf8_with differ" debugmsg, is that indicative of a bug, or more likely just a missing translated string?

**Comment by BrettDong** [comment]
Ugh. That's unexpected. There's something wrong. I'll debug it after I get the game built in this Arch Linux VM.

**Comment by BrettDong** [comment]
Okay now. I misread the man documentation and wrote wrong parameters.

**Pull request merged**
