### PR TITLE
Mod cleanup: no_fungi mod

### PR DESCRIPTION
**Pull request by arijust**
#### Summary

```SUMMARY: None```
#### Purpose of change

Helps with #36171
#### Describe the solution

Slowly fix bugs as test show them.
I was unable to check that locally, so I set up this as draft.

### CODE REVIEW

**Comment by arijust** [comment]
There are two errors which I don't have idea how to fix.
1. "fruit" material seems to be invalid at comestibles.json
2. overmap_feature_flag_settings seems to poorly support blacklists. Which could explain why certain third-party mods still have fungal overmap areas, unless that was caused by something else.

**Comment by ralreegorganon** [comment]
> overmap_feature_flag_settings seems to poorly support blacklists. Which could explain why certain third-party mods still have fungal overmap areas, unless that was caused by something else.

Got a link to an issue for mods having fungal overmap areas with this mod enabled (or a link to the mods in question)?

**Comment by arijust** [comment]
Mod in question is called Cataclysm++.
https://github.com/Noctifer-de-Mortem/nocts_cata_mod

**Comment by arijust** [comment]
>These two errors I mentioned before, don't show up anymore.

I sometimes don't understand these code tests.

**Comment by ralreegorganon** [comment]
@arijust The fungal special in that mod doesn't apply the FUNGAL flag to the location, therefore the blacklist can't exclude it. It needs to have the FUNGAL flag added to the flags here: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/blob/c97418014ecdd2255cd4e2157934fb09ff038b32/Terrain/overmap_special.json#L141

**Comment by arijust** [comment]
>The fungal special in that mod doesn't apply the FUNGAL flag to the location, therefore the blacklist can't exclude it.

That explains everything. I will need to tweak these myself at my next playthrough with that mod, I guess.

**Pull request merged**
