### PR TITLE
Aftershock generic name to object

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: none```

#### Purpose of change
Contributes to #36110

#### Describe the solution
Change name to object
Added str_pl where I think is appropriate 
I noticed that there are two afs_titanium_frame items in 2 separate files with identical json except for 'color'. @Maleclypse do you know why this is? 

image

#### Describe alternatives you've considered
Not changing

#### Testing
image
image
image

### CODE REVIEW

**Comment by Maleclypse** [comment]
I'm trying to understand why that wouldn't be causing a duplicate item error?  My first instinct is that it's an accident but if it were an accident there would be an error preventing the mod from loading?

**Comment by snipercup** [comment]
The error did not show up for me. I only noticed because there were two items of the same name, but I could only spawn 1. Is one supposed to be vehicle_part instead of type GENERIC?

**Comment by Maleclypse** [comment]
I think you are correct it should be vehicle part instead of generic for the one in the vehicle parts file.

**Comment by snipercup** [comment]
I removed the change on afs_titanium_frame from this pr. please merge this pr as it is. The issue with afs_titanium_frame will be resolved in another pr.

**Comment by Maleclypse** [comment]
Thank you for catching that. I’m surprised they worked as vehicle parts without them being labeled correctly. But I’m probably missing something doing this from my phone.

**Pull request merged**
