### PR TITLE
Added deconstruct recipe for vehicle controls

### PR DESCRIPTION
**Pull request by Soyweiser**
Added deconstruct recipe for vehicle controls and changed recipe a bit so it no longer generates weight from nothing.

#### Summary
SUMMARY: Balance "Added deconstruct recipe for vehicle controls, reduced component requirements for crafting controls"

#### Purpose of change
Right now a set of vehicle controls weighs 2721, but the components you make it out of weigh between 15973 or 14773, which is a huge difference. Also when you deconstruct the controls you get the full 15973 or 14773 in components back.

I wanted to fix the materials coming from nothing and increase the weight of the controls a bit.

#### Describe the solution
I added a deconstruction recipe that gives back 5918 in weight, upped the controls weight to 6000. (reduced the dashboard from 6000 to 2721 to compensate so default car weight is not changed). The deconstruction recipe no longer gives back the full amount of items you put into it, which represents the player cutting pipes/cables etc down to size when making it. It also has lower requirements.

I also reduced the amount of components you need for making vehicle controls from:

    "components": [ [ [ "pipe", 10 ] ], [ [ "steel_chunk", 12 ], [ "scrap", 36 ] ], [ [ "wire", 3 ] ], [ [ "cable", 10 ] ] ]
to:

    "components": [ [ [ "pipe", 6 ] ], [ [ "steel_chunk", 4 ], [ "scrap", 12 ] ], [ [ "wire", 3 ] ], [ [ "cable", 10 ] ] ]

Deconstructing only gives back:

    "components": [ [ [ "pipe", 4 ] ], [ [ "scrap", 12 ] ], [ [ "wire", 2 ] ], [ [ "cable", 8 ] ] ]

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Did you run the vehicle efficiency tests?

**Comment by Soyweiser** [comment]
The what? (nope I didn't, what do I need to do?)

**Comment by mlangsdorf** [comment]
you need to run 
```
make tests
```
then
```
tests/cata_tests "vehicle_efficiency"
```
basically, you're changing the weight of a common component, the effective range of vehicles may change. If the vehicle efficiency test fails, you'll need to update it but that's a separate post.

**Comment by mlangsdorf** [comment]
and Travis CI did run the vehicle efficiency tests, and the weight change broke a couple of them.
you'll need to run
```
tests/cata_tests "vehicle_make_efficiency_case"
```
and take the output and overwrite the test block at the end of tests/vehicle_effeiciency.cpp with it.

**Comment by Soyweiser** [comment]
Thanks! Will look at it tomorrow, been busy today.

**Comment by Soyweiser** [comment]
Sorry I have not reacted to this, but I ran into problems because well, I use codeblocks and windows, and that doesn't support makefiles correctly, so I ran into issues with running the tests.

**Comment by Soyweiser** [comment]
So yeah, I can't get make tests to run on windows.

**Comment by mlangsdorf** [comment]
Replace the tail end of tests/vehicle_efficiency.cpp with this
```
test_vehicle( "beetle", 287700, 230500, 15990, 13310 );
test_vehicle( "car", 281700, 163300, 16070, 9336 );
test_vehicle( "car_sports", 323400, 185500, 16690, 9176 );
test_vehicle( "electric_car", 69460, 45070, 3620, 2300 );
test_vehicle( "suv", 589700, 288700, 31870, 15320 );
test_vehicle( "motorcycle", 80860, 44810, 3885, 2195 );
test_vehicle( "quad_bike", 52140, 35180, 3310, 2195 );
test_vehicle( "scooter", 71290, 66960, 3707, 3707 );
test_vehicle( "superbike", 94350, 10150, 4005, 1407 );
test_vehicle( "ambulance", 378800, 287200, 23740, 18680 );
test_vehicle( "fire_engine", 452700, 380000, 27350, 23150 );
test_vehicle( "fire_truck", 311100, 68740, 20680, 4312 );
test_vehicle( "truck_swat", 340100, 75240, 24760, 5527 );
test_vehicle( "tractor_plow", 281900, 281900, 16630, 16630 );
test_vehicle( "apc", 1081000, 960200, 77710, 71540 );
test_vehicle( "humvee", 438400, 210500, 28000, 12950 );
```
remember to indent them.

**Pull request merged**
