### PR TITLE
Fix muscle-powered vehicles causing fatigue and thirst

### LINKED ISSUE #46663: Riding a bicycle make you tired instead of weary.
# Describe the bug

I was riding a bicycle for about 1-3 hours from the start of the game and I got Tired status and only Lightly Weary. The bug is that bicycle acts like a sleeping pill, instead of something that physically exhausts you.

# Steps To Reproduce

1. Find a bicycle.
2. Ride for a couple of hours.
3. Notice that by the time you got Tired you have almost no Weary status.

# Expected behavior

By the time you get Tired status you should be Extremely Weary already. I think that riding a bicycle should not make you sleepy at all until Extremely Weary status. And when you reach Extremely Weary it should start adding to your desire to sleep.

# Screenshots
None.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2; Codename: Nibia; 
- Game Version: 0.E-8888-g4f5916841b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I was doing a low weight start, with that trait that makes you 35% starving.

### PR DESCRIPTION
**Pull request by natsirt721**
#### Summary
Bugfixes "Fix muscle-powered vehicles causing fatigue and thirst"

#### Purpose of change
#47512 removed the fatigue penalty from most fatiguing tasks when weariness was implemented, however a similar change was not applied to muscle-powered vehicles. This PR removes the fatigue and thirst penalties in line with that change.

See #49074 for detailed rationale.

Fixes #46663

#### Describe the solution
Removed the code responsible for decrementing player fatigue and thirst as a function of load. 

#### Describe alternatives you've considered
Considered leaving thirst in to simulate perspiration. Did not do this consistent with #47512.
Considered adjusting activity level based on load factor. Not comfortable enough to make balance calls like that or dedicated enough to playtest.
Considered that this is intentional, but it seems out-of-line with the rest of the fatigue->weariness changes.

#### Testing
Playtesting: Created a STR 8 character with no additional features, spawned a brand new bicycle and rode in circles. Took ~2hrs 45min for activity to drop from Fresh to Light. Player was not thirsty or hungry. Total weight was ~75kg. Did not test with a boat.

#### Additional context
It seems reasonable that the load factor should affect the activity level, but I don't have a solid enough grasp on either the vehicle code or the weariness mechanics to determine what loadings deserve what activity level. This is probably worth further discussion.

### CODE REVIEW

**Comment by actual-nh** [comment]
Something that may be creating some confusion is that "fatigue" actually means "need for sleep". Is that your difficulty, @sayke, or is there something else?

**Comment by Salty-Panda** [comment]
> Something that may be creating some confusion is that "fatigue" actually means "need for sleep". Is that your difficulty, @sayke, or is there something else?

If you expand the code upward, there is properly handled activity (set to EXERCISE), bionics too.
He only removed additional cost in thirst and fatigue.

**Comment by sayke** [comment]
Got it, sounds good, thank you!

**Comment by actual-nh** [comment]
The vehicle ramp test on one Travis build (ming) went wrong because the motorcycle ran into a zombie, BTW.

**Comment by esotericist** [comment]
while I want to ask for load awareness at the same time as we drop the old penalties, we don't do that for walking yet either so it's hard for me to insist.  future problems

I couldn't find an open issue or anything about getting perspiration effects added to sustained activity, so we probably don't want that forgotten either.

**Comment by Salty-Panda** [comment]
The perspiration PR does nothing directly with weariness, but if activity levels were to raise body temperature then when/if the PR got implemented it would work with that.

**Pull request merged**
