### PR TITLE
[CR] Debug build crash fix in active item lists

### PR DESCRIPTION
**Pull request by bdragon28**
This appears to be where the iterator invalidation issues in the active item lists in debug mode were coming from. ( #14381 #11108 #12743 #15628 etc... )

I have absolutely no clue what the old code is doing, so CR because I want a second opinion here.

### CODE REVIEW

**Comment by bdragon28** [comment]
My assumption currently is that the iterators in the active item caches were being invalidated because of the way the code here was making a *cough* "temporary" *cough* copy of the item and then sticking that back in instead of the original item?

**Comment by BevapDin** [comment]
I'm curious, what gave the impression the temporary copy was *not* made on purpose?

FYI, the temporary is for things like bombs that explode and may destroy other items on the map, or even the very same cargo part they were in.

**Comment by bdragon28** [comment]
Yeah, but it's then discarding the original instead of the copy.

**Comment by bdragon28** [comment]
and when it discards the original, the iterator being stored in the active item cache goes invalid....

**Comment by BevapDin** [comment]
Test your changes with the following scenario: a shopping cart with damaged (but not broken) cargo part, put a few active bombs (dynamite, C4, whatever) in it and wait for them to explode.

If the explosions destroy the cargo part, the currently used iterator is invalidated right there. And the item is *not* removed from the game as it is not accessible from that function, when the cargo part gets destroyed, its contents (including the currently exploding bomb) are dropped on map.

> and when it discards the original, the iterator being stored in the active item cache goes invalid....

Well, *that* looks like a problem. But why does it not happen for items on the map?

**Comment by bdragon28** [comment]
Nuking a turned-on ice cream cart with perishables onboard crashes with or without this change.
Nuking a shopping cart with perishables onboard crashes with or without this change.

**Comment by bdragon28** [comment]
On my main machine where the compiler is NOT catching this stuff, I can nuke stuff as much as I want without getting any crashes, with or without this change.

**Comment by bdragon28** [comment]
I had earlier brought up a fedora core 23 VM just to test this stuff when looking into #15628 (although I used the save file from #14381 to do the actual testing), since it seems to be able to reliably catch this stuff.

My main compiler is gcc 4.9, which doesn't seem to catch this stuff. (fwiw some of the tests are currently failing when I compile with this...)

GCC 5.3 seems to have no issues finding this stuff though.

**Comment by bdragon28** [comment]
doh, the crash that I was hitting testing was that thing I fixed recently. Forgot to update the fc23 vm's codebase. Retesting.

**Comment by bdragon28** [comment]
Turns out vehicle->active_items was not being updated when the vehicle origin was being updated.

Also, items were not being removed from the vehicle's active_items properly when parts were being removed.

**Comment by Coolthulhu** [comment]
I can't reproduce the crash, with or without the PR. I'd rather leave it to someone who can reproduce it at least once.

I'm trying to understand what is the item processing code supposed to do, but it's a bit spaghettified - passing functions to templates, alternating between 2-3 different collection types etc.

I'd say that the cache shifting part is safe, but I'm not too sure about changing that part which makes the copy of an item. Rest of explosion code also makes copies of items before exploding them.

Consider the case where a grenade is sandwitched between two pieces of bread (let's say one below is fully damaged and the one above is not and is a flatbread so that they don't stack), active and is about to explode. Then it goes like this:
* Grenade explodes
* Lower piece of bread is destroyed
* Grenade shifts into its position, flatbread shifts into grenade's old position
* `this` pointer of the grenade code now points to the flatbread

Now, this example is rather innocent as `process`ing of the tools (like the grenade) is at the bottom of the function and could only activate a charger gun that way, but it's still as close to undefined behavior as it can get without really being undefined (unless vector can move after it shrinks, then it is undefined).

**Comment by bdragon28** [comment]
actually there's several levels of copying going on, map has a lot of functions that take an item directly. Lots of construction and deconstruction going on I imagine.

map and vehicle REALLY need some tidying up in the item handling. I'd like to get it to the point where I can remove my old hack that does the deferred processing of removed parts.

**Comment by bdragon28** [comment]
The crash seems to be easy enough to reproduce on fedora 23 and possibly other other gcc 5.3 environments. Debian just isn't tripping over this stuff currently, although it used to (in wheezy) -- whether this is due to how libstdc++ was built or whether there's a bug in the squeeze version that prevents this check from working properly, I dunno.

And when I say "crash" I really mean "assertion" -- this all comes down to the following check when copy constructing the item_iterator of an item_reference in an acive item cache:
```c++
      /**
       * @brief Copy construction.
       */
      _Safe_iterator(const _Safe_iterator& __x) _GLIBCXX_NOEXCEPT
      : _Iter_base(__x.base())
      {
	// _GLIBCXX_RESOLVE_LIB_DEFECTS
	// DR 408. Is vector<reverse_iterator<char*> > forbidden?
	_GLIBCXX_DEBUG_VERIFY(!__x._M_singular()
			      || __x.base() == _Iterator(),
			      _M_message(__msg_init_copy_singular)
			      ._M_iterator(*this, "this")
			      ._M_iterator(__x, "other"));
	_M_attach(__x._M_sequence);
      }
```
This purpose of this bit of code from debug/safe_iterator.h is to prevent copy constructing from a singular (i.e. invalid) iterator.

**Comment by kevingranade** [comment]
> and when it discards the original, the iterator being stored in the active item cache goes invalid....

items.erase() should transitively remove the item from the active item cache.  If there is something broken, it is in the implementation of the vehicle specialization of item_stack, but that erase must happen for the reason Coolthulu outlined.

**Comment by kevingranade** [comment]
The change in map.cpp is definitely wrong, but the others might fix things, as with many others I'm having trouble reproducing it though.

**Comment by Coolthulhu** [comment]
Most likely obsoleted by #17364

**Pull request closed without merging**
