### PR TITLE
Crafted varsize clothes is no more always fitted

### PR DESCRIPTION
**Pull request by Night-Pryanik**
The chance for crafted clothes to become fitted now depends on player's tailoring skill and the difficulty of the recipe.

Had to remove the check for fitting from the `recipe.cpp`, because prior to that the chance was calculated at the time of looking at the recipe in the crafting menu, and could be easily changed by switching to another recipe and then returning to wanted recipe.

### CODE REVIEW

**Comment by ituluwituluwzev** [comment]
This is quite logical, but might lead to grind.

**Comment by Night-Pryanik** [comment]
> This is quite logical, but might lead to grind.

Well, I think fitting non-fitted-during-craft clothes isn't so a big problem.

**Comment by ituluwituluwzev** [comment]
Is it automatically refitted during crafting? Successful refitting requires higher skill than crafting, and damages the item on failure.

**Comment by Night-Pryanik** [comment]
> Is it automatically refitted during crafting? Successful refitting requires higher skill than crafting, and damages the item on failure.

In master, yes. Refit automatically and every crafting without chance to failure.

**Comment by DangerNoodle** [comment]
This will unfortunately require the player to grind skill just for a minor quality of life feature, and in addition I find the realism of this questionable. If you are at the point of making your own clothing, you are not going to get very far unless you are able to take essential measurements.

"Does not fit" covers more than simply having one or two areas shorter, wider, etc than would be ideal for a fitted suit. This can outright mean too small to be comfortable, or so big that it becomes excessively baggy.

In balance terms, the only upshot to this is making scavenged clothing "better" in comparison by making player-made clothing worse. This is an example of negative balancing.

**Comment by Night-Pryanik** [comment]
The numbers in formula can be adjusted for balance, but at the moment I find it unlikely that a noob in tailoring IRL (1 or 2 levels in game) could craft even an easy clothes that would `fit you perfectly`.

**Comment by DemAvalon** [comment]
If a "realistic feature" adds nothing but tedium to the player it should not be added.

[http://tvtropes.org/pmwiki/pmwiki.php/Main/AcceptableBreaksFromReality](url)

**Comment by AlecWhite** [comment]
I don't think the small level of realism this adds, justify the increase in difficulty of crafting tailoring items.

Specially when you could argue that the player fits the item in the same crafting action.

**Comment by kevingranade** [comment]
I think you're reading too much into, "it fits you perfectly".  The reality is, "it fits you well enough to avoid encumbrance penalties". Not fitting is indicative of the article of clothing being 1+ size too large or too small.

If we had a spectrum of fit levels I could see this making sense, but not at it is now.

>  I find it unlikely that a noob in tailoring IRL (1 or 2 levels in game

The required tailoring levels are most likely nonsense from a IRL point of view, so reasoning about them as if they make sense is going to cause problems.

**Comment by Night-Pryanik** [comment]
Ok, closing.

**Pull request closed without merging**
