### PR TITLE
Mine entrance expand

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "Mine entrance expand"

#### Purpose of change
Add loading zone for excavated materials.

#### Describe the solution
- Added loading zone next to the mine entrance. Moved fuel depot and storage shed to this zone. Added a 50% chance to spawn a truck in this zone.
- Added separate elevator for excavated materials. It's connected to conveyor belt which leads to storage shed.
- Added mess hall with a kitchen in free place of mine entrance.
- Reworked underground section to accommodate for additional elevator. Added narrow-gauge railway and conveyor belt. Added new Trolley vehicle and made it spawn on the railway. For now the railway leads to nowhere, but in the future I hope I will connect it to outer sections of mine tunnels.
- Expanded list of possible excavated materials so now it could include sand, soil, rock salt, rhodonite, and zincite.

#### Describe alternatives you've considered
None.

#### Testing
Debug-spawned the location and checked if everything is ok.

#### Additional context
Bird-eye view of both sections
изображение

Close view of newly added section
изображение

Reworked underground section
изображение

### CODE REVIEW

**Comment by actual-nh** [comment]
See #47874 for the error in Travis and the General build matrix - #47915 is the fix.

**Comment by Xenomorph-III** [comment]
can players ride the trolley like a vehicle?

**Comment by Night-Pryanik** [comment]
> can players ride the trolley like a vehicle?

Well, trolley doesn't have any controls, so I think no.

**Comment by kholat** [comment]
liked, upvoted, commented, subscribed

**Pull request merged**
