### PR TITLE
Facial hair

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Content "Adds facial hair that can be chosen at chargen."```

#### Purpose of change
This follows the new hairstyles recently added to the game.

#### Describe the solution
It's mostly JSON work along the lines of hair styles and skin tones.

#### Describe alternatives you've considered
Considered locking this "mutation" type for female characters for obvious reasons, but this should be done separately imho.
This might be later enhanced by some extra attributes like long beard protecting your mouth from wind or giving a bit of extra warmth.

#### Additional context
Tileset artists, especially @SomeDeadGuy, might want to take a look at this.

**I used some shenanigans in GitHub Desktop to cut the extra commits that got merged from upstream/master, if it's worthless let me know, and I'll postpone this PR until forever (as i doubt I ever get a grip of the command line git).**

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I don't think there's any need to lock it for female characters. If they want beards, let them have 'em.

**Comment by SomeDeadGuy** [comment]
It is not friggin dwarf fortress!
These are people, not dwarfs.
This is why I’m not playing dwarf fortress, cause women dwarfs look exactly like men dwarfs. Women with beards is Ewww and should be outlawed and banished forever into forbidden zone!

**Comment by Fris0uman** [comment]
Come on it's [current year] let them have beard.
Also as long as it's only cosmetic there's really no reason to make it sex specific, we can think later of introducing some asymmetry in gameplay between male and female but that's probably going to be a touchy subject.

**Comment by nexusmrsep** [comment]
Must close again due to this shuffling and mixing shenanigans that makes me confused. Another day perhaps.

**Comment by I-am-Erk** [comment]
I can't possibly think how a player deciding to give their female character a fantastic moustache in their own game could gross you out at all.

I'm not about to put them into NPC trait spawn lists.

**Comment by SomeDeadGuy** [comment]
It is not just about grossing me out. It is about common sense. Women do not have facial hair (tiny ass invisible mustashes in some cases do not count). Do not put facial hair for women at the start of the game. It will make character creation screen farcical.
Facial hair for women is something unusual and should not be near character creation screen. I can see facial hair growing on woman's face as result of genetic mutation, sure. But normal women cant have facial hair and do not have ability to have them. And character creation screen should mirror that.
And on that note i would be completely fine with Crazy Cataclysm having mustasches on women, cause it is silly.

**Comment by I-am-Erk** [comment]
I am confident this is an argument you are going to lose, given that there is no definition of a "normal" woman that applies to clicking "female" on your character in cataclysm.

**Comment by SomeDeadGuy** [comment]
And i am confident if i am gonna lose it i am not gonna work on tileset anymore.
Female characters can choose facial hair on character creation screen? I am not making tileset anymore. Simple.

**Comment by I-am-Erk** [comment]
K. Weird hill to die on.

**Comment by SomeDeadGuy** [comment]
Matter of principle. I do not want game to be become silly starting right on character creation screen.

**Comment by Fris0uman** [comment]
This a useless remark : women post menopause can probably grow some decent amount of facial hair by shaving regularly.

**Comment by davidpwbrown** [comment]
If a player chooses to roleplay a woman with facial hair, or whatever gender variant thereof they want, and somebody else chooses not to, how come it's a "principle" when it doesn't affect you whatsoever?

I don't understand a lot of modern stuff re:gender, but an option for people to play how they want does not hurt me one little bit.

**Pull request closed without merging**
