### PR TITLE
adjust makeshift bandages crafting and cutting

### LINKED ISSUE #61566: Cutting up makeshift bandages (crafted from 1 cotton patch) can be cut up to get multiple cotton patches
### Describe the bug

A player can create multiple cotton patches from a single cotton patch, as long as the player mentally thinks of it as a bandage before cutting it up.

### Steps to reproduce

1. Craft makeshift bandage using 1 cotton patch
2. "Cut up" the makeshift bandage
3. You will get usually get 11 to 14 cotton patches from what was once 1.

### Expected behavior

Makeshift bandages should not break the laws of conservation of mass. Should only get 1 cotton patch.

Maybe remove the ability to cut them up, instead being able to disassemble them to return the single cotton patch.

### Screenshots

Screenshot (457)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 91310b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LiramuIorin**
#### Summary
Balance "Makeshift bandages now require patchwork cotton sheet to craft, with similar weight and volume."

#### Purpose of change
Fixes #61566

#### Describe the solution
The resource to craft makeshift bandages under medical.json have been changed from cotton_patchwork to sheet_cotton_patchwork. To help match the properties, I altered the weight and volume of bandages to be similar to that of a cotton sheet. Now, a single bandage weighs 0.08 g, and occupies 0.05 liters, same as a sheet of cotton.

#### Describe alternatives you've considered
None

#### Testing
Through debugging, I acquired a patchwork cotton sheet, and measured it's weight and volume. I compared it to a single makeshift bandage in the crafting menu, and it matches. Regular bandages weigh and occupy 3 times as more, as they are crafted in a set of 3, and weigh 0.25 g, and occupy  0.15 l. Cutting up a single makeshift bandage gave 6 patchwork cotton.

#### Additional context
None

### CODE REVIEW

**Comment by LiramuIorin** [comment]
Restored the original weight and volume under "bandages", and instead added weight and volume fields under "bandages_makeshift" only, in order to only change their stats to fit the new material.

**Comment by LiramuIorin** [comment]
Sorry about that, running the json formatter now.

**Comment by LiramuIorin** [comment]
Okay, here's hoping I did that correctly. Ran the Visual Studio tool, and the formatter in the terminal. I'd also appreciate it if someone could tell me if what I did for comestibles/med.json was correct. I had a cyclic redundancy check error earlier with that file, though not sure why it happened.

I pulled a fresh copy, made the changes again, and it seems to work now. Tested it again to be sure.

**Comment by Fris0uman** [comment]
the only change here is to the recipe, no weight or volume change. Is that intended?

**Comment by LiramuIorin** [comment]
It is not. For some reason that I am unaware of, that wasn't included in the last commit. Maybe I forgot to add everything. Doing it now.

**Comment by LiramuIorin** [comment]
Ignore the last one, need to run the format again to be sure.

**Comment by LiramuIorin** [comment]
Okay, yeah. seems fine now. I'm thinking it's because I added one file last time, instead of all. Should be okay now, fingers crossed.

**Comment by LiramuIorin** [comment]
I'm just going to close the pull request, I'm bungling something up here.

**Comment by Karol1223** [comment]
Hi, sorry for the bother but do you intend to take a second approach to fixing this issue? I've been looking into fixing the bandage issue but seeing as you already took steps in this direction I don't want to step on your toes in this regard if you intend to take a second attempt.

**Comment by LiramuIorin** [comment]
It's alright, go for it. I'm thinking of looking at it again, but I've been having a busy few days. You'll probably finish before I do, and having more than one proposed solution would be good.

**Pull request closed without merging**
