### PR TITLE
Require mastering Basic Knapping and Wound Care to use speed knapping and adv. bandaging practices

### PR DESCRIPTION
**Pull request by TheShadowFerret**
#### Summary
None

#### Purpose of change

Both activities are the more advanced version of previous practice and train the better proficiency, but you can go straight to advanced practice while not finishing the basics(and rush healthcare 0-3 very fast, so I considered it a bug).

#### Describe the solution

Add prereqs as required proficiencies.

#### Describe alternatives you've considered

Becoming an expert before you become an apprentice. 🤔

#### Testing

Spawn in with First Aid and Bushcraft hobbies.
image
image

#### Additional context

This will make very early game harder if players refuse to take the First Aid hobby as they can't instantly rush health care 3 with just two rags. This was entirely intended. 😈

### CODE REVIEW

**Comment by sonphantrung** [comment]
You're so evil

**Comment by TheShadowFerret** [comment]
> You're so evil

seagull-failarmy

**Review by NetSysFire — APPROVED** [review]

**Comment by Termineitor244** [comment]
Sorry!

**Comment by BrettDong** [comment]
You need to format your JSON changes: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md#formatting-tool

**Comment by I-am-Erk** [comment]
This doesn't seem to change the proficiency prerequisites, just the practice recipes. Is that inyended? It's not what you described

**Comment by TheShadowFerret** [comment]
> This doesn't seem to change the proficiency prerequisites, just the practice recipes. Is that intended? It's not what you described

Speed Knapping and Wound Care Expert have prereq proficiencies, this makes learning those required to do the associated practice. This was intended.

**Pull request merged**
