### PR TITLE
Fix gdb unknown target exception on Windows

### PR DESCRIPTION
**Pull request by Qrox**
When trying to debug the game on Windows using gdb, it exits with the message "unknown target exception". It was caused by SDL naming threads by raising exceptions, and gdb does not handle this well. See https://stackoverflow.com/a/43923860/4039134.

### CODE REVIEW

**Comment by kevingranade** [comment]
Awesome, one request though, can you move this to a file that is already dealing with SDL initialization?
I'd rather not have more compilation units than necessary having SDL deoendencies.

**Comment by Qrox** [comment]
> move this to a file that is already dealing with SDL initialization

Done.

**Comment by AMurkin** [comment]
Causes build failure.
In current SDL_hints.h there is no line
#define SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING "SDL_WINDOWS_DISABLE_THREAD_NAMING"

**Comment by Qrox** [comment]
Well, it seems that `SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING` is a recent introduction to SDL (https://wiki.libsdl.org/SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING). Most likely Matrix is using some old version of the SDL headers.

**Comment by AMurkin** [comment]
Yes. Strange that one server uses two versions of SDL.

Your link mentions
> This hint is available since SDL 2.0.5.

**Pull request merged**
