### PR TITLE
Whips and Chains 2: Blunt-force Boogaloo

### PR DESCRIPTION
**Pull request by Greevv**
#### Summary
SUMMARY: Content "Adds two new whips, the chain whip and a sharpened variant."

#### Purpose of change
My PR #30815 wasn't as well received as I had hoped, most of the complaints were based in realism and practicality, which are definitely valid complaints. I attempted to address this issue by removing the (admittedly, poorly thought out) razor whip altogether and adding two new whips, the chain whip and a sharpened variant. Chain whips are real, actual weapons that were used in China and other countries in which Silat is common.

#### Describe the solution
-Removed razor whip.
-Added chain whip.
-Added sharpened chain whip.
-Added both new whips to Silat.

#### Additional context
Main sources are below:
https://en.wikipedia.org/wiki/Chain_whip
https://en.wikipedia.org/wiki/Weapons_of_silat#Flail_weapons
http://www.krazyenrique.com/weapons-of-silat.html
https://martialartssupermarket.com/product-category/kung-fu-chinese-martial-arts/weapons-iron-whip-whip-chains/

### CODE REVIEW

**Comment by Inglonias** [comment]
might be worth it to add a migration entry so that existing games with razor whips don't throw (admittedly small) errors.

**Comment by Greevv** [comment]
Shouldn't be any razor whips in games, it was never merged.

**Comment by Greevv** [comment]
Uh, I think gorgon is brokeded.  Same for travis.

**Comment by kevingranade** [comment]
Jenkins Rebuild

**Comment by Greevv** [comment]
Jenkins Rebuild

**Comment by Greevv** [comment]
Jenkins Rebuild

**Comment by YukariMindGap** [comment]
Hell yeah. A blunt weapon with reach attack! This could be the blunt version of the mighty spear

**Comment by kevingranade** [comment]
Is there any precedent for this? There are some weapons with similar properties I'm aware of such as the war flail or the meteor hammer, as well as the kusarigama and kusari fundo, but I'm not aware of anything treated as whip-like in serious use.

The war flail is IMO the best bet for a ranged bludgeoning attack, the meteor hammer is also a weapon that develops a significant amount of force and has serious reach, but it requires an absolutely stupid amount of practice to use at all, much less well.  The kusarigama and kusari fundo are both too light and too short ranged to meaningfully enter this niche.

**Comment by Greevv** [comment]
Yes, there are some sources in my original PR, but [here's another.](https://blackbeltmag.com/arts/southeast-asian-arts/silat-indonesia-and-malaysia-deadly-martial-art)
Of particular note is this paragraph:
"A silat practitioner will normally be skilled with a knife, stick, sword, staff, spear, rope, chain, whip, projectile weapons or a combination thereof."

**Comment by kevingranade** [comment]
Your sources say, 'Silat practitioners use chains', not 'chains are used in a whip like manner to strike targets at a distance'.

If Silat's use of a chain is anything like the Kusari Fundo in jujitsu, it reaches no further than an additional arms length from the wielder, making it no better than an average cudgel at extending one's reach.

**Comment by Greevv** [comment]
Here's a video of a guy demonstrating some silat whip techniques. As you can see, it's really nothing like the Kusari Fundo. https://www.youtube.com/watch?v=co9_YVQpiTU

**Comment by kevingranade** [comment]
Of course it's not, it's a whip not a chain.

I also note that the engagement distance demonstrated is not what we consider a reach attack.

I'm closing this PR, if you can find any evidence of a chain being used to attack at significant range with significant force feel free to present it.

**Comment by DemAvalon** [comment]
Unfortunately, I can't find someone actually using the chain whip to hit something significant (like a ballistic gel head or a steel sheet), seems most people just like swinging them around their bodies (it does look impressive) this is what I found: [Guy hitting a watermellon](https://www.youtube.com/watch?v=WbrlEX7NbPw)

[Edgelord hiting tvs with what he calls a chain whip](https://www.youtube.com/watch?v=6iGFJB7fo3E)

Note on the this^ video, it looks like he is using an improvised version (it looks like its just a chain with a padlock at the end so assume that a proper one would be better)

now doing some research, I found that the [rupture strength of a watermelon](https://www.tandfonline.com/doi/pdf/10.1080/10942910802056143) (unpelleed) is 183N (on average) which is about 18 kg, in the video (the first one) he cuts through the watermelon, so the chain whip is able to generate at least the rupture strength of the watermelon on impact.

I did find this video however:[We DID NOT Expect This!!! WATCHDOGS 2 Thunderball put to the test!](https://www.youtube.com/watch?v=wrJxyRRjmgs)
in the video they use the "thunder ball" (an eight ball on a section of paracord) to strike a dummy with shock watch stickers inside its head (just the sensors) and on the second try he was able to trigger the 50g one, so I would say that a steel chain with a weight at the end (which is what the chain whip is basically) would have enough strength to cause lethal damaged.

I don't know about the length however, I don't know what distance a melee weapon must be able to cover to be considered for reach attack.

**Comment by kevingranade** [comment]
None of this is the slightest bit compelling.

None of these are reaching more than an arms length from the attacker, and
the wind up is ridiculous.

This is the Chinese chain whip, which might be used in silat, though I
doubt it. Whether it is or not, it's not a reach weapon.

**Comment by DemAvalon** [comment]
It did look kind of short to me too, but what about as a regular melee weapon? (no reach attack, much like the steel chain)
also :"Rantai 
The rantai is a chain which can be swung offensively or used to lock and seize opponents. It can sometimes be substituted with a length of rope (tali). A common variant is the rantai batangan, l**iterally meaning "stick chain". Originating in China, it consists of several metal rods links together by iron rings**. The ends are weighted, each about 2 ounces. One end has a dart used for piercing. Chain whip techniques in silat are the same as the staff, centrifugal force keeping the weapon straight."

the rantai is a variation of the whip I showed (it's not really a whip...) so it would likely work for silat.

**Pull request closed without merging**
