### PR TITLE
Spell-casting NPCs

### PR DESCRIPTION
**Pull request by araneyl**
Adds spellcasting npcs to magiclysm

#### Summary
SUMMARY: Content "Adds Spell-casting NPCs"

#### Purpose of change
Introduces NPCs that know spells to Magiclysm. Includes npc specific factions and quests. 

#### Describe the solution
Adds 3 new npc classes, an old Magus, a Priest that can heal, and a Technomancer 'Child'
2 new factions, an ancient group of Magus that are now out in the open and a group that want to purge the world of its curse (the cataclysm) using their new found powers
and 4 new quests specific to the new npcs, 2 'fetch' quests and 2 kill missions. 

#### Describe alternatives you've considered
n/a

#### Testing
Appears to work. Loads into game, npcs talk and give quests. Quests seem to function as intended but they havnt been put through a strenuous test.

#### Additional context
I had hoped to put more work into this but life keeps getting in the way. Eventually I'd like to expand the dialog and quest lines as well as fill out the missions and npc stats to make them more 'thematic' to their factions. But since I don't know when I'll get the chance I'm going to see if this is enough for now and go from here when I can.

### CODE REVIEW

**Comment by aoae23** [comment]
Blessed be.

**Comment by araneyl** [comment]
For anyone watching this, its not abandoned; I just havn't had as much time to work on it as I had hoped. I should have more soon(tm).

**Comment by KorGgenT** [comment]
going through the healer questline:
- i would like it to be more obvious from what he tells you when you accept the quest that you need to go kill zombies. i had to check the mission menu in order to know what i needed to do
- after completing the second mission, and asking for another quest, i got this error message
image

**Comment by KorGgenT** [comment]
for the magus:
- make sure to mention the name of the book you're looking for in both the quest response and the mission screen

**Comment by araneyl** [comment]
on my local files i have the changes to make clearer what you need for both of the npcs. i can push those any time.

i have no idea how to change the text on the mission screen. someone is going to have to point me in a direction, i havnt seen anything about that so far.
that error makes no sense to me, theres a line to link missions sequentially that i thought i used correctly but i have no idea why it threw that error.

**Comment by araneyl** [comment]
Last night someone was on discord and mentioned getting that nullptr error while dealing with 'Dino Dave' from the refugee center. I tried to get more from them about it but they didnt respond. I don't have the time atm to see if I can reproduce the error with DDave but I will when I get a chance. Perhaps there is something undiagnosed or a new error with mission chains? I wont make an issue till i can confirm the error on my side.

**Comment by KorGgenT** [comment]
note to self: all the periods need an extra space (for when i come back to this tonight)

**Pull request merged**
