### PR TITLE
Remove Superglue Recipe

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Removes superglue recipe"

#### Purpose of change

Superglue has a much more complex recipe IRL than what it currently is, and while it in theory _could_ be made, it'd be quite impractical and difficult to do.

#### Describe the solution

Removes the recipe, and has innawoods migrate it into bone glue. 

#### Describe alternatives you've considered

Not doing this

#### Testing
Recipe before:
image
Recipe after (there is nothing): 
image
Here is the migration working innawoods:
image

#### Additional context

Gonna try cooking up a PR that makes superglue spawn in multiple amounts in a proper tube, though that may be a bit

### CODE REVIEW

**Comment by casswedson** [comment]
> it'd be quite impractical and difficult to do.


I would love to hear all about this

**Comment by Holli-Git** [comment]
> I would love to hear all about this
From my google-fu, the process would involve formaldehyde, chlorine, sulfuric acid, and cyanide

**Comment by ADekema** [comment]
Removing the recipe outright is pretty drastic. Superglue is used for a whole bunch of things. Would it be possible to rework the recipe to a makeshift glue strong enough to be a substitute for modern superglue?

**Comment by Holli-Git** [comment]
> Removing the recipe outright is pretty drastic. Superglue is used for a whole bunch of recipes. Would it be possible to rework the recipe to a makeshift glue strong enough to be a substitute for modern superglue?

No.

**Comment by Inglonias** [comment]
i support this on the grounds that it's hilarious.

**Comment by sonphantrung** [comment]
> Removing the recipe outright is pretty drastic. Superglue is used for a whole bunch of recipes. Would it be possible to rework the recipe to a makeshift glue strong enough to be a substitute for modern superglue?

I've never really relied on crafting superglues, as they are very common in the (vanilla) game. Most of the said recipes can be replaced by duct tapes iirc, which are also common.

**Comment by adamkad1** [comment]
> > Removing the recipe outright is pretty drastic. Superglue is used for a whole bunch of recipes. Would it be possible to rework the recipe to a makeshift glue strong enough to be a substitute for modern superglue?
> 
> No.

How mature.

**Comment by Holli-Git** [comment]
> How mature.

How is this immature? 

> Also didnt we use to require irl examples for stuff? And not just 'it would be too hard or impractical or something'

The synthesis requires reacting ethyl alcohol and sulfuric acid at 100C refluxing for a few hours to produce ethyl chloroacetate. That product is then reacted with sodium cyanide to create ethyl cyanoacetate. It is then reacted with formaldehyde to produce superglue. Note, this is not impossible, just much more complex than the current recipe. If you feel like making a PR to add a superglue recipe, by all means, go for it. But at the end of the day it is not my job, or anybodys job, to make a recipe for superglue.

**Comment by Roet718** [comment]
But it is your job to indefinitely wreck a significant portion of the game with no clear plans to remedy those issues, simply because of some "google-fu"? I don't mean to be rude but I just don't see any benefit to making this change now, instead of at a later time bundled with at least some attempt at the relevant recipe adjustments.

**Pull request merged**
