### PR TITLE
Removed mention of bashing damage from BARK mutation

### LINKED ISSUE #23259: Bark mutation description inaccurate
" "Your skin is coated in a light bark, like that of a tree.  This provides resistance to **bashing** and cutting damage and minor protection from fire.  Greatly reduces wet effects.","

says it provides bashing resistance but there is only cut resistance provided 
"armor" : [ { "parts" : "ALL", "cut" : 2 } ] 

FWIW I think there should be 2 bashing armor as well, but at the very least just remove that bit from the description.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #23259.

### CODE REVIEW

**Comment by Zireael07** [comment]
I seem to remember it being removed for balance reasons. If it gets added back, inevitably the issue that was fixed by removing it will pop back up.

**Comment by ZhilkinSerg** [comment]
> I seem to remember it being removed for balance reasons. If it gets added back, inevitably the issue that was fixed by removing it will pop back up.

There was bashing protection and no cutting protection, but when mutation armor values were moved to json in #17124 that was changed (@Coolthulhu could do that intentionally for the sake of balance).

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/e5e3490a71198988831e721096aa5de77bb612bd/src/player.cpp#L12194-L12236

**Comment by Leland** [comment]
Maybe add bash protection instead? See #16739

**Comment by Coolthulhu** [comment]
I didn't intentionally nerf bark (it doesn't need nerfing), that's a mistake in editing. The description was always wrong, though: my mistake was switching bash resistance to cut resistance.
Bark isn't really an important mutation, so all fixes (description, bash->cut + description, buff to match description) are OK.

**Pull request merged**
