### PR TITLE
Makes water extinguish fire based lit items (explosives excluded)

### LINKED ISSUE #14151: Candles work underwater
`iuse::autotransform` is bugged in that the check for `when_underwater` will never be called

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Bugfixes "Makes water extinguish fire based lit items (excluding explosives)"```

#### Purpose of change
Fixes #14151
I wanted to fix a very old bug and it seems like it grown on me to a new feature.
**Previously:** lit items like candles, fiery baseball bats, and cigarettes did not care if you were swimming, diving or simply standing in a pouring rain, and stay lit no matter what.

#### Describe the solution
This PR introduces checks in item `process()`-ing for conditions:
- does player have the item with him and is in `deep water` (swimming or diving is same here, but in shallow water I assume that item is not submerged),
- is item placed on `liquid` terrain (`shallow water` etc.)
- is it raining or snowing - this condition is based on precipitation severity, and on chance, and because in bad weather this chance factor will be processed few times statistics do the rest, so in a drizzle you might get a chance to finish your cigar or at least take a couple of lungfuls but in a thunderstorm it will go out fast.
If conditions are met items are extinguished and either reverted to their inactive states or their 'dead' states.
As a side job I managed to to remove fixed (lit) (on) (off) suffixes from affected items, as they were showing as (lit) (active), and I added dynamic appending of (lit) that replaced (active). Since double (lit) (lit) is unwanted I had to remove those from JSON items names. Some are left, but they are either explosive (see below) or other special items not based on fire.

#### Describe alternatives you've considered
Considered adding this feature to explosives like lit dynamite, but most explosives are one-way tickets, and have no JSON info of an item they could be reverted to and their 'dead' state is "BOOOOM!"

I'm also considering adding another condition for spilled liquids, similar to their ability to quench fires.

#### Additional context
N/A

### CODE REVIEW

**Comment by mlangsdorf** [comment]
The title/summary is confusing.  It sounds like the bug you're fixing is that water extinguishes fire, instead of making sure that water appropriately extinguishes fire.

**Comment by lucasmr** [comment]
What if the player is wielding an umbrella?

**Comment by nexusmrsep** [comment]
> What if the player is wielding an umbrella?

I'm quite torn on that since when you wield an umbrella you put the *burning* torch/candle/etc. in your backpack, and how does that even work? Comments?

**Comment by lucasmr** [comment]
You could use one hand for wielding the umbrella and the other for another activity, unless you're restricted with a bindle, for example.

**Comment by Rivet-the-Zombie** [comment]
>I'm quite torn on that since when you wield an umbrella you put the burning torch/candle/etc. in your backpack, and how does that even work? Comments?

I grip the cigarette in my mouth.

**Comment by nexusmrsep** [comment]
Ok, I'm convinced enough.

**Pull request merged**
