### PR TITLE
Improving modding support via adding ability to load game options directly from JSON

### PR DESCRIPTION
**Pull request by Firestorm01X2**
#  What this PR does:
1) Adds ability to load game options directly from JSON without necessary to add it via code first.
2) Now mods can overwrite not only bool options but string, int and float too.
3) Gives easy way to dump some constants into JSON.
**4. Now options with flag COPT_ALWAYS_HIDE no longer save. It should help to prevent situation, explained there: #22769 (comment).**

#  How:
Just write somewhere in JSON:

 ```
{
        "type": "EXTERNAL_OPTION",
        "name": "DISPERSION_PER_GUN_DAMAGE",
        "info": "Value that adds to weapon dispersion per weapon damage level.",
        "stype": "int",
        "value": 60
   }
```
This way you dinamically add option DISPERSION_PER_GUN_DAMAGE with type int and value 60.
This thing will be normal hidden game option. No need to add this options in options.cpp via code editing - this option will be added dynamically.
So now you can get it as normal option:
`int dispPerDamage = get_option< int >( "DISPERSION_PER_GUN_DAMAGE" );`

#  Modding support:
External options support overrding via mods. So if you want to overwrite it with mod then well- just do it in your mod:
 ```
{
        "type": "EXTERNAL_OPTION",
        "name": "DISPERSION_PER_GUN_DAMAGE",
        "info": "Modified Value that adds to weapon dispersion per weapon damage level.",
        "stype": "int",
        "value": 10
   }
```

Also if option with same name already added via source code - then external option just overwrite its value.

**Additionaly now options with flag COPT_ALWAYS_HIDE no longer save in game save. It should help to prevent situation, explained there: https://github.com/CleverRaven/Cataclysm-DDA/pull/22769#issuecomment-358242636**

#  Example provided:
In this PR you will find ranged_balance.json there you will find value that adds to weapon dispersion per weapon damage level.". It was JSONized using new external option system.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Ready.

**Comment by John-Candlebury** [comment]
Another interesting option this could add is the ability to influence the sleep health regen rate. To disable it and make it so the player must resort to items to heal. 

Could serve as the base for an increased difficulty mod.

**Comment by BrettDong** [comment]
Will the `info` string `"Value that adds to weapon dispersion per weapon damage level."` ever be displayed on user interface?

**Comment by Firestorm01X2** [comment]
>Will the info string "Value that adds to weapon dispersion per weapon damage level." ever be displayed on user interface?

No. At least in foreseeable future. Just like options for mods.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/request-to-developers/22170/1

**Pull request merged**
