### PR TITLE
[Xedra Evolved] Add more Arvore Paraclesian mutations

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "Add more Arvore Paraclesian mutations"

#### Purpose of change

I still had more ideas but the other PR was already gigantic.

#### Describe the solution

Add some mutations
(More to come?)

**SPELL-GRANTING MUTATIONS**
- Traverse the Wilds: Allows the Arvore to teleport, but only when in a FOREST, FOREST_THICK, FOREST_WATER, or Arvore altar overmap tile. (Ideally they would also need to end the teleport in one of those tiles, but that's currently not possible.  It would also be nice to limit teleporting to the same Z level so people can't teleport into a lab that's under a forest tile...but if they do that they can't get out, so maybe it'll all work out okay).  (_Requires Greenstride and Shadow of the Trees_)
- Tending the Garden: An anti-plant damaging and DoT spell. Affects PLANT, LEECH_PLANT, and FUNGUS enemies (and ARVORE...)

**PASSIVE MUTATIONS**
- Insight of the Grove: Passive bonus, +3 Perception. (_Requires The Forests' Warning and Commune with Nature_)
- The Fallen Branch Suffers Not: The Arvore suffers 25% less pain. (_Requires viridian skin and Nurturing the Green_)
- Arvore Ears: The Arvore's ears are more leaf-shaped (fae _have_ to have pointed ears!). It doesn't increase their hearing, but it does protect them from hearing damage.

**ACTIVE MUTATIONS**
- Commune with the Ancient Oaks: I got annoyed enough about the way my weird hack worked that I installed Visual Studio, edited some code, compiled the game, and now it works the way that that Mycorrhizal Communion works.  It's faster than Mycorrhizal Communion (the Arvore is literally a plant spirit and not a mutant, so I think that's reasonable) and the activation message is different, referring to communing with the tree spirits instead of entwining roots with the trees.
- Essence of Hemlock: Makes the Arvore's flesh toxic at the cost of 1 thirst per 2 minutes (a periodic mana cost would be ideal, but that's impossible at the moment). Testing this one was very confusing until I remembered that zombies are immune to poison. 

**POST-THRESHOLD MUTATIONS**
- Solar Empowerment: When in the sunlight, the Arvore gains nutrients, heals faster, regenerates mana 50% faster, and has 50% more maximum mana. (_Transformed from Solar Revitalization_). Transforms to:
- Solar Ascendancy: When in the sunlight, the Arvore gains nutrients, heals faster, regenerates mana 50% faster, has 50% more maximum mana, and gains +2 to all stats.
- Fallen Trees Decay to Soil: Teaches a spell that does significant DoT damage to everyone in a radius around the Arvore.  The spell is indiscriminate, so don't use it near allies. (_Requires Verdant Infusion_)
- One With the Forest: Transform into a tree! Heal much faster, metabolism is slowed and thirst is nearly nonexistent, gain more rest from sleep, become able to sleep at any time, and nearly every type of monster will ignore you, but the Arvore will be blind, deaf, and unable to move.  You must transform outdoors on diggable ground. (_Requires Leaves Return When Winter Ends and Solar Repast_)
- Sap Maintains the Heartwood: Makes the Arvore immune to bleeding, parasites, infection, and the Mycus (_Requires the old Sap Maintains the Heartwood, renamed Sap Defends the Trunk, and also Tending the Garden_ )

#### Testing

Spells work as intended.  Solar Ascendancy provides extra mana and stat bonuses. Fallen Trees Decay to Soil does biological damage. Essence of Hemlock poisons poisonable targets.  One With the Forest, works as described.  Commune with the Ancient Oaks is now an active mutation and doesn't require a spell hack (spell was obsoleted--no one has probably learned it yet, but you never know)

For the C++ changes, I compiled the game and tested them as intended, where they worked, and in a world with no Xedra Evolved, where Plant and Elf-A mutants could still use Mycorrhizal Communion without problems. 

#### Additional context

Making One with the Forest unable to move spams the same message:
image

But has no other ill effects.

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
About the exclusion of Nether beings and robots from Fallen Trees Decay to Soil, what if you just made it do biological damage, allowing it to interface with the BIOLOGICALPROOF flag.

**Comment by Standing-Storm** [comment]
> About the exclusion of Nether beings and robots from Fallen Trees Decay to Soil, what if you just made it do biological damage, allowing it to interface with the BIOLOGICALPROOF flag.

That was the reason I put up the BIOLOGICALPROOF PR, I just didn't have time to get to it and test it before Yom Kippur.  Now that that's over, I should be able to implement it in just a moment

**Comment by Maleclypse** [comment]
This whole mutation tree (tree hahaha) is gorgeous and innovative.  Thank you for your contributions

**Comment by Standing-Storm** [comment]
You're very welcome!

It's like D&D--the DM runs the campaign that they actually want to play in.  When I saw the description for Arvore I really wanted to play one, so...

**Comment by Standing-Storm** [comment]
Actually a good thing the tests failed because I think I have a better way to do the C++

**Comment by Standing-Storm** [comment]
Okay, the new C++ changes work.  This is ready.

**Pull request merged**
