### PR TITLE
Sawn-down barrel shouldn't be craftable

### PR DESCRIPTION
**Pull request by mugling**
See #14783

### CODE REVIEW

**Comment by Zireael07** [comment]
I fail to see where it says it shouldn't be craftable in the linked issue :(

**Comment by kevingranade** [comment]
I haven't looked it over yet, but I believe this is making some now
obsolete items uncraftable, there is another way to shorten your gun.

**Comment by mugling** [comment]
> there is another way to shorten your gun.

With a hacksaw via `iuse::saw_barrel`

**Comment by Rivet-the-Zombie** [comment]
@Zireael07, you no longer need to craft them at all; you can use a hacksaw to cut a gun's barrel down directly now!

**Comment by Shadefang** [comment]
@Rivet-the-Zombie Please correct me if I missed something, but when you do that it's irreversible. it (arguably) shouldn't be. An extended barrel would replace the whole barrel, so while you couldn't remove a sawed off barrel you should be able to replace it with another barrel mod. At very least you should be able to make the short barrel mod from the long barrel (barrel extension) mod But seeing as that's currently just made from pipes as well, why can't you just make the short one?

**Comment by Rivet-the-Zombie** [comment]
@Shadefang, that may become an option in the future.

**Comment by mugling** [comment]
Sawing down a gun barrel is a permanent affair and I much prefer this being achieved using a hacksaw rather than via a temporary and universal barrel mod. I'd quite like to remove the barrel extension mod as in it's current form it's not sensible (@Rivet-the-Zombie?).

Ported barrel is salvagable (and indeed ~~once~~ now #15177) is I'd like to make this a permanent mod applied via careful use of the cordless drill. No reason you can't have both a sawn and ported barrel. The implementation would probably be via `iuse_actor` so other mods can be applied using tools.

In the long term the correct mechanic is exchangeable barrels but that's a long way off.

Actually, if I implement porting of barrels can we go ahead and deprecate the barrel extension mod for now?

**Comment by Rivet-the-Zombie** [comment]
>In the long term the correct mechanic is exchangeable barrels but that's a long way off.

That's what I was thinking of.

>Actually, if I implement porting of barrels can we go ahead and deprecate the barrel extension mod for now?

It is a pretty silly idea, somehow sticking a piece of pipe on the end of a gun's barrel like that. Anybody got any ideas on what we could replace it with, or perhaps we should just get rid of it?

**Comment by mugling** [comment]
> or perhaps we should just get rid of it?

`obsolete.json`

I'm going to mockup the ported barrels though and make them irremovable with the muzzle brake as a swappable alternative.

**Comment by Rivet-the-Zombie** [comment]
A muzzle brake attaches (often with threads) to the end of a gun's barrel; porting changes the barrel itself.

**Pull request merged**
