### PR TITLE
Partially mainline Medieval Stuff mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
Move weapons and armor that is not made from bronze and a recipe book from Medieval Stuff mod into the main game.  Also tweak some recipes during the process and update No Medieval Items mod.

Full list of moved items:

Armor:

galea (+recipe) (+itemgroups)
nasal helm (+recipe) (+itemgroups)
conical helm (+recipe) (+itemgroups)
tunic (+recipe) (+itemgroups)
gambeson (+recipe) (+itemgroups)
lorica segmentata (+recipe) (+itemgroups)
chainmail hauberk (+recipe) (+itemgroups)
lamellar armor (+recipe) (+itemgroups)
baldric (+recipe) (+itemgroups)

Melee:

arming sword (+fake) (+recipe) (+itemgroups)
longsword (+fake) (+recipe) (+itemgroups)
estoc (+fake) (+recipe) (+itemgroups)
halberd (+fake) (+recipe) (+itemgroups)
scimitar (+fake) (+recipe) (+itemgroups)
glaive (+recipe) (+itemgroups)
naginata (+recipe) (+itemgroups)
jian (+fake) (+recipe) (+itemgroups)
qiang (+recipe) (+itemgroups)

Ranged:

fire lance (+recipe) (+itemgroups)

Ammo:

fire lance charge (+recipe) (+itemgroups)
fire lance shot (+recipe) (+itemgroups)

Book:

Arms and Armor of Imperial China (+itemgroups)

Non-mod recipes changed by mod:

crossbow
boiled leather armor
plated leather armor
leather armor boots
black gunpowder

### CODE REVIEW

**Comment by kevingranade** [comment]
Seriously, too big.

**Comment by Coolthulhu** [comment]
Could be broken up by types quite easily.

**Comment by chaosvolt** [comment]
Meep. Was not expecting that. Now if only I knew what to do about shields. ;w;

**Comment by mugling** [comment]
I like the mod but does it necessarily need to be mainlined?

**Comment by Darkyhard** [comment]
> I like the mod but does it necessarily need to be mainlined?

I can't think of a reason to keep something as a mod if it isn't contrary to the game setting (that's why Arcana mod should exist only as a mod) and if the mod itself is already finished and has no bugs. Also, it's easier to update mod content if it is mainlined, because it would be stored in the same file that contains main game content.

**Comment by kevingranade** [comment]
I'm not at all against mainline most of the content, I just don't want huge
diffs ;)

**Comment by Shadefang** [comment]
Just a thought to consider, but when compared to reality a couple of the swords in this are WAY too heavy. The arming sword weighs about 6 lbs, over twice what it should, and the longsword isn't much better (6.5 lbs, should be around 4 max). They're actually heavier than most of the polearms added.

I'm happy to move this to an issue if that'd be better, but felt it should be brought up.

**Comment by kevingranade** [comment]
Yea, the main blocker for mainlining stuff is reviewing it for things like
that.

**Comment by Darkyhard** [comment]
Closed this for splitting.

**Comment by chaosvolt** [comment]
> and if the mod itself is already finished and has no bugs.

Technically it isn't, due to shields and professions not yet being ported over from the dropbox'd version, but those will have to wait for a good while.

Plus Kadian over at the forums had poked me with more ideas for the mod, but I hadn't really got around to considering any of it due to being kinda burnt out lately. @_@

**Pull request closed without merging**
