### PR TITLE
Allow Refugee Center and Tacoma in classic mode.

### LINKED ISSUE #49285: error when searching for a refugee camp
Hello, I found a bug in the latest experimental version for android, when in the shelter in the terminal you click to find a refugee camp, the game freezes and after a while gives an error, fix it you are welcome

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Allow Refugee Center and Tacoma in classic mode"

#### Purpose of change

Fixes #49285

#### Describe the solution

Tag the 2 overmap specials as CLASSIC so they they won't get removed by the classic_zombies mod.
Also change the Old Guard mission 4 to spawn zombears instead of graboids as a fallback when graboids are not allowed.

#### Describe alternatives you've considered

Changing the classic_zombies mod to disable the refugee center quest in evac shelter consoles. But I don't see any reason why the Refugee Center would be incompatible with classic mode.

#### Testing

Started a new game with classic_zombies enabled, used the evac shelter console to get the Refugee Center location and teleported there. Started the quest to clear the back bay and verified that the "boss" zombie is a classic zombie (tough zombie).
Talked to the Old Guard representative and did their missions, verified that mission 4 spawns zombears instead of graboids.

#### Additional context

screen

zombears

I thought this might help #38993 too, but that's actually a different issue unrelated to classic mode.

### CODE REVIEW

**Comment by eltank** [comment]
I checked all the quests from the Refugee Center. The only thing that's broken in classic mode is MISSION_OLD_GUARD_REP_4, which wants to spawn Graboids but can't. There's no error, but when you get to the target location you don't find anything and are unable to complete the quest. I'll see if I can get the graboids replaced by zombie animals (which are allowed in classic). Now... what's the most dangerous zombie animal?

**Comment by RenechCDDA** [comment]
> I checked all the quests from the Refugee Center. The only thing that's broken in classic mode is MISSION_OLD_GUARD_REP_4, which wants to spawn Graboids but can't. There's no error, but when you get to the target location you don't find anything and are unable to complete the quest. I'll see if I can get the graboids replaced by zombie animals (which are allowed in classic). Now... what's the most dangerous zombie animal?

Probably the antlered hammer? Although a similar level of difficulty would be the antlered horror or acidic zombear.

**Comment by eltank** [comment]
Honestly, I don't know if the antlered hammer is supposed to be allowed in the classic_zombies mod. It is at the moment, because of copy-from inheritance propagating the CLASSIC category, but it may be an oversight. Acidic zombear should definitely not be allowed.
It might also be a bit too tough. So I'll go with a couple of zombears unless someone objects. Antlered horror seems too weak.

**Comment by eltank** [comment]
For the sake of being thorough, I searched for "place_monster" and "monster" in all the NPC dialogue files and found another incompatibility with classic_zombies. One of the Isherwood missions (MISSION_ISHERWOOD_JESSE_2) wants you to kill flying polyps.

Out of scope for this PR since I'm not touching the Isherwoods, but if anyone has suggestions on fixing that one I could make another PR.

**Comment by I-am-Erk** [comment]
This is actually an intentional omission. For one thing there are quests and dialogue that refer to or require vanilla cataclysm,  but maybe more importantly, I'd like to replace it with a new in-lore faction center. If you'd like to help me make that, I have ideas but not time.

**Comment by eltank** [comment]
Ok, how about Isherwood Farm? That's currently allowed by classic_zombies but has at least one reference to disallowed content. Should the farm be removed as well?

**Comment by I-am-Erk** [comment]
It definitely should, yeah

**Pull request closed without merging**
