### PR TITLE
Wasp changes

### PR DESCRIPTION
**Pull request by Roguecop**
#### Purpose of change

The wasps are an old friend of every CDDA player, but few changes have been introduced since time ago. I wanted to introduce new variations in the way these monsters work together and fight

#### Describe the solution

New types of wasp evolved from the "small" wasp

- Close combat : Reforced and juggernaut wasp

Heavier and without the capacity to fly, converting the wings into some form of natural armor. The task in combat is to run to the enemy and block their path by biting and grabbing the attacker.

- Attack at distance: Gunner, Snipper, and Torret Wasps

Giving up the speed to fly, they evolved to be better defenders of the hive, shooting a black, solidified liquid from the abdomen. With every evolution, they are slower and more deformed, ending as an unnatural mass whose only purpose is to guard and shoot.

- Special type: Kamikaze wasp

A bloated wasp with a substance similar to sludge. Can make the escape difficult and make the prey vulnerable to range attacks.

- A new pet: Pitiful wasp

Something was wrong with the evolution of this wasp. The best you can do for this deformed monster is end his suffering. The second best? Give him some food and obtain a new friend.

#### Describe the alternatives you've considered

I like the idea of making the wasp evolve to work better in a team and defend the nest. I think that can fit with the core of CDDA, but it can be implemented in a mod too.

Other things I consider changing:

The wasps with attacks at a distance are difficult to kill and have a high rate of fire and damage. Maybe reduce it.
I'm not sure the evolution rate is balanced with the difficulty expected as the small wasps evolve into more challenging types.
Names and descriptions can be improved.
I wanted to make the pitiful wasp milkable, but I decided not to introduce this possibility.

#### Testing

A manual test using a wasp nest and summoning the wasps one by one

#### Additional context

Captura de pantalla 2024-07-22 213352
Captura de pantalla 2024-07-22 213812
Captura de pantalla 2024-07-22 214503

### CODE REVIEW

**Comment by Karol1223** [comment]
@Venera3 I'm gonna need you to double look over this but I personally am 100% against just adding every single variation possible to the wasps. That's not only boring but also over the top as hell. 

200% no for some weird tameable variant that's tameable because it's deformed. It being deformed wouldn't make it any more friendly towards you.

**Comment by Holli-Git** [comment]
Yeah I don't like this. Why does a wasp shoot? Also, why're you removing other wasps from the monster groups? Also wings are not strong at all, it makes 0 sense to have it as armor

**Comment by Holli-Git** [comment]
Okay going into more depth one by one:
Kamikaze wasp: Wasps aren't a suicidal monster, they'll run away if hurt, fear fire, etc. They also attack by stinging, not by exploding. Mutated animals don't just mutate into super specific things like zombies do, they mutate mainly by growing bigger.
Gunner wasp: No. Why would a wasp shoot out a dense liquid?
Sniper wasp: No, even more. 
Turret wasp: Even more no. This is going further outside the realm of possibility into make-believe. A wasp wouldn't evolve from a quick insect that stings, into a stationary gun thing.
Reinforced wasp: Wings are not sturdy and wouldn't provide any benefit. Giant wasp queens already cannot fly due to their size, and IMO that should remain as its unique thing.
Juggernaut wasp: Why is it so fast? Wasps legs aren't their means of transportation. 
Pitiful wasp: Why would a deformed wasp be able to be befriended?

Why did you remove the other wasps from monster groups? Also why is a giant wasp such a rare thing to evolve into? 

Overall I do not think this PR is a good idea. It adds monsters that feel unbelievable in a way that reads "These monsters were created as clear and set roles one would play into in an RPG class or hero shooter".

**Comment by Roguecop** [comment]
It's not my best idea, I admit. I created the evolutions thinking more about the combat than the reality of the game.

Defenders with high health to melee and grab, some gun-firing enemies at some distance to make damage, and a fast unit to stop the character using sludge. Maybe it could be interesting in other situations, but not as shown in this PR with the wasps.

Something like a room in a lab or a small dungueon that includes some sort of fast humanoid robot with the capacity to grab, a moving turret, and a small flying dron that can shoot some sticky shoots to slow down could have been an acceptable idea. But not wasps, trying to force some evolutionary path.

About the wasp as a pet, I was thinking of an animal abandoned from the rest because it cannot do anything for the nest and only follows you because you give him food and protection. But, once again, wasps are not the best animals for this, and it sounded like a "deformed wasp is now my friend because of some unknown reason."

In any case, thanks for the review  @Karol1223 , @Holli-Git and @zachary-kaelan . Next one I'm going to try to be less "creative"

**Comment by Little-119** [comment]
This is already closed but I hope you don't mind me giving my two cents anyway.

I don't entirely agree with the argument that the wasp varieties don't make in-universe sense. They're not undergoing evolution in any real world way, they're being mutated by ???. I think.
I do agree with the argument that it'll probably stand out as too 'game'-y.
Additionally, I don't think wasps are in need of a buff, because I am very salty about all the times they've killed me or my buddy Liam.
I don't think the variations you added cover any of the wasps' weaknesses. In my experience, they're very hard to evade or kill and wasp nests are a sort of area denial for the player, at least until they're able to deal with them.
Maybe if you'd like to add content to wasps, you could expand on that niche they fill?

**Comment by zachary-kaelan** [comment]
Situations in CDDA aren't often intended to go any specific way. Things are randomly generated and then thrown together and what happens, happens. Coordinated teams is more a thing for NPC squads, and is often just not worth trying to fight against.

I would look at nature to find ideas that can get added, you'd be surprised at what you can find. [The bolas spider](https://en.wikipedia.org/wiki/Bolas_spider), for example, throws a strand of silk with weighted ends at its prey.

**Comment by Karol1223** [comment]
> I don't entirely agree with the argument that the wasp varieties don't make in-universe sense. They're not undergoing evolution in any real world way, they're being mutated by ???. I think.

This, in principle, is true - but despite the basic force causing mutation in both wildlife and zombies, the process is different.

In general, it's not impossible for mutations like these to occur, hence me not using this as an argument in my comment. I just think giving them class galore is really boring. We have way better alternatives that could use this than gamifying actual animals.

**Comment by Roguecop** [comment]
About adding new content for wasps, I was thinking about two possibilities. 

1º. A new place related to wasps. 

Wasps are one of the enemies of the game with "more to lose, less to gain" in a fight, because the places where they spawn are a nest without reward, a normal house, and a tower radio that usually we are going to evade. 

A new type of nest could be created, but the only reason someone could enter would be to obtain something useful. And I don't know what could be interesting to motivate the players to enter a place like this. The only idea I can think of now is something related to scientific experiments and leaving behind mutagens or material.

2º A mutation or item that can make the wasps your ally. Something related to the insect mutations could be interesting to add, but difficult to do without errors.

My idea after this PR is to start with something small, like a new type of house to better understand how to mapgen works. After that, I could try something again with insects or other types of monsters or enemies

**Comment by Holli-Git** [comment]
> About adding new content for wasps, I was thinking about two possibilities. 
> 
> 1º. A new place related to wasps. 
> 
> Wasps are one of the enemies of the game with "more to lose, less to gain" in a fight, because the places where they spawn are a nest without reward, a normal house, and a tower radio that usually we are going to evade. 
> 
> A new type of nest could be created, but the only reason someone could enter would be to obtain something useful. And I don't know what could be interesting to motivate the players to enter a place like this. The only idea I can think of now is something related to scientific experiments and leaving behind mutagens or material.
> 
> 2º A mutation or item that can make the wasps your ally. Something related to the insect mutations could be interesting to add, but difficult to do without errors.
> 
> My idea after this PR is to start with something small, like a new type of house to better understand how to mapgen works. After that, I could try something again with insects or other types of monsters or enemies

1: CDDA isn't developed around typical game ideas like a more dangerous location having more loot. 

2: Mutagen isn't going to make you into a wasp on the same level as an actual wasp

**Comment by zachary-kaelan** [comment]
According to the Wikipedia page for [paper wasps](https://en.wikipedia.org/wiki/Paper_wasp):

> Nests can be found in sheltered areas, such as the eaves of a house, the branches of a tree, on the end of an open pipe, or on an old clothesline. Some species, such as [Ropalidia romandi](https://en.wikipedia.org/wiki/Ropalidia_romandi), will vary their nest architecture depending on where they build their nest.

There's your inspiration. Maybe it could be some kind of giant mutated tree that "co-evolved" with the wasps.

> the only reason someone could enter would be to obtain something useful

There are a few reasons why I massacre wasps, personally:

* To get to the top of a radio tower for vision
* A lot of bodies to dissect to learn weakspots
* Target practice in an isolated location
* Testing out all the insecticide spray and grenades I got 
* Revenge and personal hatred for bullying me early game

You can also add more uses to the [items gotten from wasp butchery](https://cdda-guide.nornagon.net/monster/mon_wasp). They are of minimal use, particularly the [cluster of gas sacs](https://cdda-guide.nornagon.net/item/mutant_bug_hydrogen_sacs) which aren't used for anything. You can add more uses to the [venom gland](https://cdda-guide.nornagon.net/item/venom_wasp) and [wasp stinger](https://cdda-guide.nornagon.net/item/wasp_sting) or the things they are used for.

> A mutation or item that can make the wasps your ally

There's nothing that would make wasps your ally. However, wasps *do* attack other creatures. I lead the zombies from a mass grave towards a wasp nest and watched the wasps massacre them. Some species of wasps in reality are used for biological pest control to control other species. Do research into the methods used to get the wasps from the wild to the target location.

**Comment by Venera3** [comment]
Just since I have been summoned:
- Re mutant animal design in general : they aren't as diverse in-species as zombies are, take longer to change, and they are at the end of the day still living animals. Changes are *mostly* per-generation and they still care about selection pressures - they are *not* zombies and they don't play by zombie rules. They are also way more fun if they touch on the real life biology of the base species.
- Adding wasp nests: Yes please. Adding weird loot drops: No. You can have extermination quests, rescue quests or something similar but no Skyrim boss chests at the end of every location. A wasp nest should have wasps, wasp eggs, wasp babies, wasp queen(s), wasps, and some guts and bits of lunch. That's about it.

**Pull request closed without merging**
