### PR TITLE
lint.sh has bashisms, make it use bash

### PR DESCRIPTION
**Pull request by mutability**

### CODE REVIEW

**Comment by mugling** [comment]
Can you give examples? I suspect your right explaining the difficulty running under some variants of linux and I'd prefer cross-platform if possible

**Comment by mutability** [comment]
`IFS=$'\n'` breaks on dash, I didn't see a simple/portable way to get the same effect from my 30 seconds of looking at it.

**Comment by mugling** [comment]
Fair enough but you need to use `env` as not all nixes have `bash` at the same path

**Comment by kevingranade** [comment]
Indirecting through env is another change, I suspect that if it could find sh it can find bash.

**Comment by mugling** [comment]
> I suspect that if it could find sh it can find bash.

Absolute paths such as `/bin/bash` don't use `PATH`

This PR breaks FreeBSD, OpenBSD, NetBSD, probably many other unixes plus innumerable linux distributions that don't install bash under `/bin/bash`

**Pull request merged**
