### PR TITLE
JSONize electrohack tool by adding HACK quality

### PR DESCRIPTION
**Pull request by b3brodie**
#### Summary
Infrastructure "JSONize Electrohack Tool"

#### Purpose of change
Currently, hacking into safes, card readers, and gas tanks is hardcoded to require the electrohack item, where it uses charge in multiples of 25.  This prevents adding any other hacking tools with potentially differing charge counts, different levels of hacking ability, or even combining the hacking ability into more generic items.

#### Describe the solution
Adds the HACK quality which is checked in order to hack a device.  If a device does have a HACK quality, hacking consumes the given "charges_per_use" on an attempt start and various multiples of this value on differing levels of failure. For example, in order to match current values the electrohack has a "charges_per_use" of 25, which means it takes 25 KJ to begin a hack, it takes 25 KJ when lightly failing a hack, and takes an extra 50 KJ when severely failing a hack.  Furthermore, the hack difficulty is affected by the level of HACK quality, where 2 is a default value of no difference, below 2 is a harder hack, and above 2 is an easier hack.  This allows potential shoddy electrohack stand ins that do not function as well as the actual item.

Currently, the electrohack functions exactly as it currently does, with the same energy consumption and hack difficulty.

#### Describe alternatives you've considered
Add a 'hack' use action as well. This path leads to suffering.

#### Testing
1. Created a character with a lab started and teleported to the entrance
2. Examining reader without an electrohack does not allow hacking
4. Spawned an electrohack and hacked into the card reader
5. Successfully fail, extra fail, and eventually succeed hacks modified by character hacking ability
6. Successful hacks open the doors
7. Temporarily modify electrohack JSON with lowered / raised charges_per_use and HACK quality and see that energy use and difficulty are modified respectively.
8. Spawn in electrohack CBM and try and hack door. Fails when not powered enough and succeeds when 25 KJ is contained within system.

#### Additional context
Primarily motivated by a potential MOM additions, but I can see mods like Aftershock potentially adding other hacking tools

### CODE REVIEW

**Comment by Standing-Storm** [comment]
> Primarily motivated by a potential MOM additions, but I can see mods like Aftershock potentially adding other hacking tools

Electrokinetic hacking was immediately what I thought of too. 

If you have an item with HACK but no charges defined at all (not just being out of charges), will the interaction still work?

**Comment by b3brodie** [comment]
> > Primarily motivated by a potential MOM additions, but I can see mods like Aftershock potentially adding other hacking tools
> 
> Electrokinetic hacking was immediately what I thought of too.
> 
> If you have an item with HACK but no charges defined at all (not just being out of charges), will the interaction still work?

An item with no "charges_per_use" defined will hack correctly, simply consuming no charges for the hacking process or short circuits.

**Comment by Maleclypse** [comment]
@John-Candlebury  we should look at this feature upgrade for any use in aftershock

**Comment by John-Candlebury** [comment]
Thanks Mal yeah this is pretty good.

**Pull request merged**
