### PR TITLE
Obsolete chickenbot, tripod, tankbot

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Content "Obsolete fictional combat robots"

#### Purpose of change
These were in the process of being phased out because scifi combat robots don't fit the game and because they're completely fictional it's hard to reason about how they should behave.

#### Describe the solution
Obsolete the chicken walker, tripod, and tank drone. These can be properly removed after 0.E.

#### Describe alternatives you've considered
Adding a larger real world UGV to replace them.

#### Testing
Game loads correctly. Monsters do not spawn where they were removed.

### CODE REVIEW

**Comment by Rail-Runner** [comment]
Why not move them to Aftershock instead?

**Comment by SirPendrak** [comment]
Whats the criteria for fictional combat robots to not fit the lore while bionics, cyborgs, some fictional firearms, laser and teleport technology is fine?

**Comment by Maleclypse** [comment]
> Why not move them to Aftershock instead?

@ymber Would you prefer to move it to aftershock or for me to move it from obsolete to Aftershock?  I also notice it looks like some cpp items are changed relating to these robots in this PR and in #36437.   I currently don't operate outside of JSON so I would need someone to re-enable anything C++ related to these bots.  I appreciate any consideration you can give to this!

**Comment by ymber** [comment]
I'm not interested in maintaining aftershock but move them there if you want. The C++ changes are just cleaning up unused code after monster spawns got changed in places that still use hardcoded mapgen so you want need to touch them.

**Comment by I-am-Erk** [comment]
I'm not convinced these need to be obsoleted. Currently they only show up in lab finales, if I recall correctly. Having these as something that never reached field use but still exists as a dangerous prototype activated during the final days isn't really a problem.

**Comment by esotericist** [comment]
> I'm not convinced these need to be obsoleted. Currently they only show up in lab finales, if I recall correctly. 

all three robots show up in other places than lab finales, both in the json mentioned here, and in places not mentioned here (there's c++ code and monster groups that reference them, although I don't know offhand how used those are)

> Having these as something that never reached field use but still exists as a dangerous prototype activated during the final days isn't really a problem. It becomes a problem when we need to rationalize them existing on the street.

I'm not even a little convinced the chicken walker or tripod make any sense in our setting at all, but even *if* they did, neither of those nor the beagle would make sense to be in a fully assembled, armed, and operable form in an indoors context if they're just prototypes.

Platforms of this type don't get fully prepared for combat until they're delivered to somewhere that it makes sense to use or even test them. You generally don't test anti-tank rounds underground in a building you also are in. you especially don't on a platform that might in any fashion potentially malfunction.

If you want to argue that parts related to them might exist in labs, I'd believe that. But fully operational active versions *with* munitions loaded? That's a very hard sell for me.

**Comment by Marrim** [comment]
Might want to remove the mention of chickenbot in start-up tips.
It says something like "Why is it called the chicken bot? Because you'll chicken out every time you see it."

**Comment by Amoebka** [comment]
The only non-lab places these show up in are equally sci-fi. Tribots are used in collapsed towers (which have ruins of a lab in the basement), chicken walkers and tank drones are used in Necropolis (roadblocks are already removed).

**Comment by kevingranade** [comment]
Ok two issues, one is chickenbot and tripod, these are pretty much right out for main game. The first is effectively a Star Wars reference, and the second is a War of the Worlds reference. Neither has a place as a terrestrial combat robot.

Second is the issue @esotericist brings up, which is that the tankbot is either a deployed piece of ordinance (which isn't completely out of the question), or it's a prototype, in which case having the thing be fully armed and operational requires a really contrived scenario, such as the thing being set up for a live fire test right when the cataclysm happened, or it's developers assembled and configured it to defend them mid-cataclysm. Neither of these scenarios lends itself to being repeated more than once ever, so it's not something we can just stick in a lab finale.

IMO where we need to go with anything like this is set up a scenario where the thing were deployed in at least a provisional way pre-cataclysm, which puts them as perimiter guards or deployed with assault troops.  Or I'm fine with the things simply not existing, they are in no way essential to any part of the game, we can set up turrets, or sentry bots, or even bandits or armed forces remnants with conventional military hardware and have them fill more or less the same role.

At the end of the day, I think the right thing to do right now is to evict them from the main game. If @Maleclypse wants them for Aftershock that's fine, but my primary concern is the main game.

**Comment by Marrim** [comment]
> Ok two issues, one is chickenbot and tripod, these are pretty much right out for main game. The first is effectively a Star Wars reference, and the second is a War of the Worlds reference. Neither has a place as a terrestrial combat robot.
Isn't the chickenbot a RoboCop reference? ED-209 was pitched as a police robot, but never made it into mass production because it was buggy and kept shooting people. We could assume the same lore stance and that would mean the chickenbot could not be deployed by police or the military.

It could, however, be found in a corporate building, and it's not a far fetch to assume an executive with access would activate one as a last resort, or leave it to "guard" the place when evacuating.

Are there large corporate facilities in the game? Rivtech plant, anyone?

**Comment by Rail-Runner** [comment]
> Second is the issue @esotericist brings up, which is that the tankbot is either a deployed piece of ordinance (which isn't completely out of the question), or it's a prototype, in which case having the thing be fully armed and operational requires a really contrived scenario, such as the thing being set up for a live fire test right when the cataclysm happened, or it's developers assembled and configured it to defend them mid-cataclysm. Neither of these scenarios lends itself to being repeated more than once ever, so it's not something we can just stick in a lab finale.

Can we have only tankbot parts and schematics spawning in some places then, with player assembling them into a finished tankbot if they feel like it? Seems fitting for prototype tech.

**Comment by I-am-Erk** [comment]
If we're going the "military prototype" scenario then finding scattered parts and assembling and programming them by hand is pretty silly

**Comment by Mister-Cultist** [comment]
fucking realism crowd needs to get their own seperate mod so they can stop ruining the game

**Comment by ZhilkinSerg** [comment]
@Mister-Cultist Go rant somewhere else please.

**Comment by Nacarbac** [comment]
If they're being obsoleted... will the realistic replacements actually be made realistic for the timeline? CROWS shouldn't be a thing by the time of the cataclysm, they're already a finished product - [MAARS ](https://youtu.be/wMEru9ORYGY?t=102)is next. 

Plus the tankbot, is (barring the AI) something that already exists ([but hasn't performed very well](https://www.businessinsider.com/russias-uran-9-robot-tank-performed-horribly-in-syria-2018-7?r=US&IR=T)). 

So they're hardly science fiction when _eyebots_ are explicitly mentioned in the timeline.

**Comment by davidpwbrown** [comment]
Depends what you think the time of the cataclysm is. Because its present-day.

**Comment by Fris0uman** [comment]
eyebots are just quad copter drones.

**Comment by Mister-Cultist** [comment]
> 
> 
> Depends what you think the time of the cataclysm is. Because its present-day.
> 
> https://cataclysmdda.org/design-doc/#world

oh yes the cataclysm is present day, that explains why there are loads of random people in the streets with cybernetic implants and the fact that solar and nuclear cars are now in mass civilian production, is the realism crowd coming for the nuclear sports cars and the cbms as well?

**Comment by Mister-Cultist** [comment]
> 
> 
> @Mister-Cultist Go rant somewhere else please.

so you're just going to ignore the fact that the majority of the player base likes keeping the setting scifi and gets annoyed when the realism crowd keeps removing content without making somthing to replace it?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Depends what you think the time of the cataclysm is. Because its present-day.
> > https://cataclysmdda.org/design-doc/#world
> 
> oh yes the cataclysm is present day, that explains why there are loads of random people in the streets with cybernetic implants and the fact that solar and nuclear cars are now in mass civilian production, is the realism crowd coming for the nuclear sports cars and the cbms as well?

World of CDDA is located in an alternative reality based on present day Earth. There are some light sci-fi elements in this reality, but nothing major. We are moving most ridiculous sci-fi things out of vanilla, but code infrastructure still supports creating more hardcore sci-fi content via mods.

> 
> 
> > @Mister-Cultist Go rant somewhere else please.
> 
> so you're just going to ignore the fact that the majority of the player base likes keeping the setting scifi and gets annoyed when the realism crowd keeps removing content without making somthing to replace it?

"Realism crowd" is not obliged to appease "majority player base". The latter could easily move any cut-out sci-fi content to the mod instead of getting annoyed of its removal. I strongly urge you to do that.

**Pull request merged**
