### PR TITLE
Add ascii art for guns

### PR DESCRIPTION
**Pull request by Boondiggle-III**
#### Summary

SUMMARY: Content "Add ascii art for guns. Graphics are added to ascii_arts.json; references to graphics are added to the respective item's json file in the 'items' folder"

### CODE REVIEW

**Comment by Fris0uman** [comment]
You need to follow the template for the PR
Use this aas the summary
SUMMARY: Content "Add ascii art for guns"

You also need to fill the Test part of the template

Finally you need to astile your changes, see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md for how to do it.

**Comment by Boondiggle-III** [comment]
I ran all the changed files through the helpful linting tool, but it is still failing the style check with "needs linting". Files double and triple checked and the files I pushed match with what the linting tool has output. Summary updated.

**Comment by Fris0uman** [comment]
Alright it's looking much better. Next step would be to add a `ascii_arts` folder, split the `ascii_arts` file at least into `generic_ascii` and `gun_ascii` and put that in the folder

**Comment by Boondiggle-III** [comment]
I agree with splitting the arts into separate files. That file is going to get huge really fast.

**Comment by I-am-Erk** [comment]
In the future please be sure to follow the pr template, maybe throw in some in game screenshots and stuff

**Pull request merged**
