### PR TITLE
[Aftershock] Flickering Lights EOC AFS

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Mods "Flickering Lights EOC Aftershock"

#### Purpose of change
Adds a flickering lights eoc to go along with the crashing ship.

#### Describe the solution
Adds the terrains and eoc needed to create a flickering lights effect.

#### Describe alternatives you've considered
None

#### Testing
TBD

### CODE REVIEW

**Comment by Maleclypse** [comment]
I'm half asleep right now and I'm missing several things I want this to do and I'm not positive what's the best way to make it happen.   

I would like for it to randomize which light terrains switch instead of flipping all of them in radius each time.

**Comment by Maleclypse** [comment]
@Ramza13 I can't decide if this is the best way to create this type of EOC or if I should do a bunch of nested eoc randomizers?  Do you have any suggestions?

**Comment by John-Candlebury** [comment]
I'm uncertain is this integrated with the crashing ship already?

**Comment by Maleclypse** [comment]
> I'm uncertain is this integrated with the crashing ship already?

I'll double check but I don't think so.  I've kind of wondered if the crashing ship is already too much going on to add flashing on-off lights.

**Comment by John-Candlebury** [comment]
Thematically I think it'd help convey whats going on. And the general effect can probably be reused in several parts

**Comment by Maleclypse** [comment]
Need to test this in the crashing spaceship

**Pull request closed without merging**
