### PR TITLE
Restore repairability of some vehicle parts

### LINKED ISSUE #21129: Wooden cart wheel is repairable with welder
Wooden cart wheel have `TOOL_WRENCH` and `WHEEL` flags, repairing parts with them require welding tools.

### LINKED ISSUE #21187: Repairing of some vehicle parts is broken
Seems like #20550 has broken repairing of vehicle tracker, saddle, foldable seat, seatbelt, 5-point harness, vehicle curtain, aisle curtain, water faucet, bicycle horn, car horn, truck horn, back-up beeper, wing mirror, inboard mirror, aisle lights, atomic lamp, floodlight, car headlight, reinforced headlight.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #21187.
Closes #21129.

(On a side note: guys, congratulate me - at last I managed to learn how to use git and finally sync my heavily outdated repo. Please don't look at all these lousy commits, only the 75202de577a4e46d0ff23d9d16b1f274ce92b685 matters).

### CODE REVIEW

**Comment by cainiaowu** [comment]
You could use git rebase to squash your latest commit.

https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Night-Pryanik** [comment]
> "retain a copy -> delete the current fork -> refork the newest master -> copy back your change"

Could you please tell me how can I retain a copy?

**Comment by cainiaowu** [comment]
By making an copy of the changed file to another directory on your local hard drive.

And uploading it back when you done the refork.

**Comment by Night-Pryanik** [comment]
Ok, thanks.

**Comment by kevingranade** [comment]
Squashed and pushed.

**Pull request closed without merging**
