### PR TITLE
Fix deflated off-road bicycle wheel recipe, plus set correct length and volume for wheel rims (#51264)

### LINKED ISSUE #51264: Off road bicycle wheels made using incorrect rims?
### Describe the bug

The 27" off-road bicycle wheels are using the wide steel rim that wide vehicle wheels are also using, and not the bicycle rim.

### Steps To Reproduce

Just spawn them and look at the item info panel.

### Expected behavior

That bicycles don't use huge car tire rims.

### Screenshots

Wide steel rim and bicycle rim:
image

### Versions and configuration

Win10 64, experimental tiles 2021-08-31-920 (0447a46), no mods

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Fix deflated off-road bicycle tire recipe, plus set correct length and volume for tire rims"

#### Purpose of change
Fixes #51264

#### Describe the solution
Change deflated off-road bicycle wheel recipe to use correct rim
Change longest side and volume of wheel rims as follows (With thanks to @RandDenner for the calculations here):
Bicycle rim (27", 30mm wide) - 686mm, 11L
motorcycle (20", 60mm wide) - 508mm, 12L
medium steel (17", 190mm wide) - 432mm, 28L
wide steel (24", 240mm wide) - 610mm, 70L

Modified the volumes of deflated and inflated versions of tires based on these rims to line up

#### Describe alternatives you've considered
Suggestion by @actual-nh to create a wider rim for off-road bicycle wheels, will look at that in a future PR as well as current wheel volume

#### Testing
Loaded into base game and tested

#### Additional context
rims 1

rims 2

rims 3

rims 4

### CODE REVIEW

**Comment by RandDenner** [comment]
> Suggestion by @actual-nh to create a wider rim for off-road bicycle wheels, will look at that in a future PR as well as current wheel volume

Actually, in each case I used the larger dimensions. So the bicycle wheel I calculated is an off-road size of 30mm width.
20mm is a normal bicycle rim width. This would drop the volume by 1/3 to 7.4L

**Comment by kevingranade** [comment]
I don't know what happened here with the github infrastructure, can you just rebase this and push to see if we can get the tests running?

**Comment by occulti** [comment]
@kevingranade No problem, should have been rebased and pushed as requested

**Comment by occulti** [comment]
Closed due to resubmission

**Pull request closed without merging**
