### PR TITLE
Add the no_fungal_growth mod by default

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Balance "Add the no_fungal_growth mod by default"

#### Purpose of change

A lot of players are using the No_Fungi mod, which removes the Mycus completely. This can break some quests and removes a lot of interesting content.
As suggested by @I-am-Erk, "turn 'no fungal spread' on by default until fungal spread is better managed".

#### Describe the solution

Modify `data/mods/default.json`, add `no_fungal_growth`.
Make No_Fungi obsolete.

#### Testing

Create World on a new profile.
image

#### Additional context

`no_fungal_growth` was added in #51418. Summary: prevents additional fungaloids from spawning.
Does not prevent fungaloids and other fungal creatures from spreading fungal terrain.

### CODE REVIEW

**Comment by actual-nh** [comment]
Why not _also_ mark No_Fungi as obsolete? (I'm not saying remove it entirely, BTW.)

**Comment by eltank** [comment]
> Why not _also_ mark No_Fungi as obsolete? (I'm not saying remove it entirely, BTW.)

Done.

**Comment by I-am-Erk** [comment]
Agreed on obsoleting no fungals as well yes. 

Can you link the PR that created this mod, or quickly list what is and is not turned off for people wondering?
- do spores still form
- do spores still spread fungus or is all fungalization disabled entirely
- do new fungaloids spawn

**Comment by eltank** [comment]
> Can you link the PR that created this mod, or quickly list what is and is not turned off for people wondering?

Sure, that was #51418.

> * do spores still form

Yes.

> * do spores still spread fungus

Yes.

> * do new fungaloids spawn

No.
They normally spawn from spores (either via special attack or evolution), but both of those are disabled by the mod.

**Pull request merged**
