### PR TITLE
[Xedra Evolved] No werealfs

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Bugfixes "[Xedra Evolved] No werealfs"

#### Purpose of change

Saw a screenshot of someone with a werewolf changeling. You can't be born two supernatural species at once, especially when one of them has you being swapped in the crib.

#### Describe the solution

Add the `HERITAGE` type to the werewolf traits so you can't pick changeling (or Gracken) as a species background

#### Testing

When picking the Natural-born Shapeshifter background, the Species backgrounds do not even appear available to select.

#### Additional context

🎶 Werealf Bar Mitzvah
Spooky, Scary
Boys becoming elves,
Elves becoming wolves 🎶

### CODE REVIEW

**Comment by Maleclypse** [comment]
This is what i thought of https://www.youtube.com/watch?v=4T9-LK4CGnI

**Comment by emixa-d** [comment]
>Saw a screenshot of someone with a werewolf changeling. You can't be born two supernatural species at once, especially when one of them has you being swapped in the crib.

Is the lack of a `HERITAGE` type for the various paraclesians intentional?

**Comment by Maleclypse** [comment]
> >Saw a screenshot of someone with a werewolf changeling. You can't be born two supernatural species at once, especially when one of them has you being swapped in the crib.
> 
> 
> 
> Is the lack of a `HERITAGE` type for the various paraclesians intentional?

They use a different method of restriction. But let us know if there are ways around that we haven't seen yet.

**Comment by Standing-Storm** [comment]
> Is the lack of a `HERITAGE` type for the various paraclesians intentional?

No. And now that you mention it, they should probably have it too, but I can make another PR for that.

**Pull request merged**
