### PR TITLE
Allow Emitters to use vars

### LINKED ISSUE #65993: Implement variable objects as possible inputs for emitters
### Is your feature request related to a problem? Please describe.

Some types of JSON objects have fields that accepts variable objects as input instead of constant values thus providing possibility to more dynamical mechanics. But most of the json types doesn't support variable objects as input to it's fields.
One of such type is emitters.

### Solution you would like.

Implement variable objects as possible input for emitters json fields. More specifically:
- "qty" - dynamical amount of fields placed which also would mean dynamical radius of space where fields are created;
- "chance" - dynamical chance of spawning the fields each time fields is emitted;
- "intensity" - dynamical intensity of the emitted field.

### Describe alternatives you have considered.

_No response_

### Additional context

Many other json object types would also benefit from implementing variable objects as their field types.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fix #65993

#### Testing
Used this json 
```
  {
    "id": "emit_toxic_belch",
    "type": "emit",
    "//": "Large cloud of toxic gas emitted infrequently",
    "field": { "global_val": "field", "default_str":"fd_toxic_gas" } ,
    "intensity": { "global_val": "int", "default":3 },
    "chance": { "global_val": "chance", "default":1} ,
    "qty": { "global_val": "qty", "default":25 }
  },
```

#### Additional context
If there are any other places you want variables just ask.

### CODE REVIEW

**Comment by GuardianDll** [comment]
May i ask you to check how hard would be to implement #72891?

**Comment by Ramza13** [comment]
Ha I looked at that and was debating doing it instead.  I'll work on it next.  

What context are you seeing this in?  What kind of eoc are you using in it? I'm assuming its not a item activation since that would be alpha talker, is this a spell?

**Comment by GuardianDll** [comment]
Initially i planned to use it with terrain/furniture, but they can't store variables at all, so i moved to the items. What i tried to do is to store the time_since_cataclysm inside the item upon activation (and some another value), and then future activations would check is the value stored, and is specific amount of time passed
I think it was in context of the mod Karol worked, they would need a machine that would produce calorie slurry out of items that are put into machine, so i planned to wrap it as:
User activates the item, inventory EoC searches all items with amount of calories (functionality was added by Karol itself with the help of Renech), user picks all food they want to put into machine;
After pick, EoC is run on all picked items, calorie value (I'll try to make code, so math could return calorie amount, on my own) of all food is added to a single variable, then this variable is stored inside the item, with the day when it happened. 
Some amount of time later player activates the item again, time check is passed, and EoC generate X amount of slurry
Thinking now, it probably won't work because there is no way to confirm the machine were powered all this time

**Comment by Maleclypse** [comment]
Please resolve conflict

**Pull request merged**
