### PR TITLE
One more filesystem loose-end cleaned up

### PR DESCRIPTION
**Pull request by bkentel**

### CODE REVIEW

**Comment by bkentel** [comment]
Looks like GCC (and evidently clang) are missing std::put_time; I'll change the implementation to work around it.

**Comment by narc0tiq** [comment]
Heh, yeah. As of [2014-11-20](http://stackoverflow.com/a/14142342), `std::put_time` had just entered GCC trunk. Maybe in 4.9.

**Comment by bkentel** [comment]
Too bad, that. It's a pretty neat addition to c++11. I'll just use `std::strftime`, which, AFAIK is available.

**Comment by kevingranade** [comment]
Code looks fine, can we get a mingw build verification before we land it?

**Comment by Rivet-the-Zombie** [comment]
I'm on it.

**Comment by Rivet-the-Zombie** [comment]
Tests and runs fine on MinGW32.

**Comment by KA101** [comment]
OK, then feel free to merge it, Rivet?

**Comment by Rivet-the-Zombie** [comment]
If that was all we were waiting for, I'll do so.

**Pull request merged**
