### PR TITLE
Refactor the json files relative to the three rigs among Aftershock and BlazeIndustries

### PR DESCRIPTION
**Pull request by martinrhan**
#### Summary
Bugfixes "Refactor the json files relative to the three rigs among Aftershock and BlazeIndustries"

#### Purpose of change
https://github.com/CleverRaven/Cataclysm-DDA/pull/48373
As replied under this PR, I found "MetalMaster forge buddy", "cooking rig", "KitchenMaster cooking buddy", these three things are missing from my game. I wasn't able to find those recipes and I wasted a lot of time to look for it. My friends also ensured this with his game and got same result. 
After some research I found the stated PR. I just atempted to remove the three recipes in data\mods\Aftershock\recipes\obsolete.json the the recipes exist in game again.
I thought it was fine already. However, in game, it was shown that the item is from mod Aftershock. Then I searched "afs_metal_rig" in the repo directory, I was given what's shwon in screenshot0
The item itselves, appeared twice in Aftershock as well as one existence in Blaze. The vehicle part is also being written in both. The recipe has one obsoleted version (as described above) in Aftershock folder and a non-obsoleted version in Blaze folder.
This is a mass, I am going to fix it.

#### Describe the solution
1. Remove the three rig recipes from data\mods\Aftershock\recipes\obsolete.json
2. Remove the duplicate json codes in data\mods\Aftershock\items\obsolete.json and mods\Aftershock\vehicles\part_items.json, which is displayed in the screenshot.

#### Describe alternatives you've considered
N/A

#### Testing
Tested with WIN10, MSVC release build, all three recipe can be seen after unlocking all recipes with debug menu.

#### Additional context
screenshot0
image

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @shacknetisp?

**Comment by shacknetisp** [comment]
This looks good to me as far, as far I can tell; I didn't realize this duplication existed on the aftershock side. The only potential issue I can think of is what happens when an old aftershock save using these items when they were still part of aftershock is loaded now? But again, I am not familiar with this area, or how important that is.

**Comment by anothersimulacrum** [comment]
Yes, it will cause poor behavior with old saves before the linked PR.
@martinrhan Try to add `id_suffix` to the blaze industry recipes, that will likely fix this problem without needing all of this.

**Comment by martinrhan** [comment]
> Yes, it will cause poor behavior with old saves before the linked PR.
> @martinrhan Try to add `"id_suffix": "blaze"` to the blaze industry recipes, that will likely fix this problem without needing all of this.

Don't you think its necessary to remove the duplicates in Aftershock? If it was a decision two move those things from Aftershock to Blaze Industry, then there should be nothing relative remaining in Aftershock.

**Comment by anothersimulacrum** [comment]
What remains in Aftershock is for old saves with the item. Removing it could break those.

**Comment by martinrhan** [comment]
> What remains in Aftershock is for old saves with the item. Removing it could break those.

Just done it. I tested, it was ok

**Comment by Maleclypse** [comment]
> > What remains in Aftershock is for old saves with the item. Removing it could break those.
> 
> Just done it. I tested, it was ok

When you tested it what did you do?  Because when I tested it right now, it made those items stop working in Aftershock only saves which is the reason they are obsolete instead of removed.

**Comment by martinrhan** [comment]
> > > What remains in Aftershock is for old saves with the item. Removing it could break those.
> > 
> > 
> > Just done it. I tested, it was ok
> 
> When you tested it what did you do? Because when I tested it right now, it made those items stop working in Aftershock only saves which is the reason they are obsolete instead of removed.

1. Build the repo.
2. Launch game, create a new world with Aftershock only.
3. Debug menu, spawn item, search "buddy". Can see  "MetalMaster forge buddy" and "KitchenMaster cooking buddy"
4. The recipes cannot be seen after unlock all recipe, this is espected because they are obsoleted in data\mods\Aftershock\recipes\obsolete.json
5. create a new world with both Aftershock and Blaze Industry.
6. Debug menu, spawn item, search "buddy". Can see  "MetalMaster forge buddy" and "KitchenMaster cooking buddy"
7. After unlocking all recipes, the three recipes are visible in craft menu.

**Comment by anothersimulacrum** [comment]
You need to have instances of those items spawned in a world with Aftershock only, then apply these changes and load that world.

**Review by Maleclypse — APPROVED** [review]
Thanks for your help in cleaning this up!

**Pull request merged**
