### PR TITLE
New vehicle: Automatic Tractor

### PR DESCRIPTION
**Pull request by Core0verload**
Automatic Tractor is a small fully robotic vehicle similar to Automatic Street Sweeper and produced by the same manufacturer. It has one advanced reaper, one plow and one advanced seed drill on board. Unlike a regular tractor, it can't plow/seed/reap three field lines at once, but it's more precise and reliable than a tractor with human driver, it uses cheap electricity instead of expensive fuel and it can work day and night without any human intervention.

Of course, the world has ended. All the control centers are down and Automatic Tractors, just like Automatic Sweepers, are **only useful for spare parts**. They are the only source of advanced seed drills and advanced reapers in game. You can find them at ranches, they spawn instead of regular tractors with 1/4 chance.

This tractor features a new vehicle part: advanced reaper. It has a storage space and will collect and store everything it reaps.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by Rivet-the-Zombie** [comment]
Don't reaper's need scoops behind them to pick up the plants?

**Comment by Core0verload** [comment]
Regular reaper tractor has no scoops, and scoops can't harvest crops at all. First version of robotic tractor had one, but it didn't worked. Then I found this comment in scoop code: "Street sweepers are not known for their ability to harvest crops".

**Comment by Rivet-the-Zombie** [comment]
The whole thing is odd either way; real tractors reap and gather the crops with the same mechanism. They don't typically chop them down and leave them on the ground like our current 'reaper' parts do.

**Comment by Coolthulhu** [comment]
It should probably have noticeably lower weight, as a high tech vehicle. The farms in the game are currently low tech stuff. We could have a "plantation" farm variant for plants like soy or corn, but I don't think we currently have those.

**Comment by kevingranade** [comment]
The reaper in question is a compromise because it's relatively easy to make.
A more advanced reaper would certainly place the reaped plants in storage,
but should not be craftable.

**Comment by Core0verload** [comment]
Who the heck has thought that having one union for 4 diffirent car part values that are not even mutually exclusive is a good idea?

**Comment by Core0verload** [comment]
Advanced reaper is in. It has 350 storage and will collect anything it reaps.

**Comment by kevingranade** [comment]
Something is missing, I can't turn the attachments on or off.

**Comment by Core0verload** [comment]
Maybe it's because it has a robotic control unit instead of controls?

**Comment by kevingranade** [comment]
That seems likely, #15298 looks like at least an attempt at a fix, I'll check them out together.

**Comment by kevingranade** [comment]
It needed another little fix, good to go now.
In future though, this is really something you should have tested before making the pull request.

**Comment by Core0verload** [comment]
Just like robotic street sweeper, this vehicle wasn't intended to be used by player as is. It's just a fancy way to spawn some parts.

**Pull request merged**
