### PR TITLE
All the Realism: Chemistry Edition: Batteries Chapter

### PR DESCRIPTION
**Pull request by roaringjohn**
#### Summary
```SUMMARY: Content "Add chemicals for use in batteries, as well as prerequisite chemicals"```

#### Purpose of change
There is a very narrow collection of actual chemicals that are useful in practical ways in Cataclysm, which doesn't really lend itself to the possibilities of chemistry. Disposable batteries can't be crafted or recycled, despite such things being possible in reality.

#### Describe the solution
To add chemicals that are useful in the creation of batteries, and adjust some recipes around this. I plan to change the probabilities of finding disposable vs rechargeable batteries, in favor of being more likely to find (loads) more disposable batteries than rechargeable.

#### Describe alternatives you've considered
Just change the probabilities of finding disposable vs rechargeable batteries. Which is boring and not full of chemistry stuff.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
This is exciting, as there's a pathway to making a broadly used oxidizer from MnO2.

**Comment by roaringjohn** [comment]
> This is exciting, as there's a pathway to making a broadly used oxidizer from MnO2.

Yeah, I am finding a lot of chemicals that are likely to be added just because of my goal of making disposable batteries realistically craftable. The addition of all these chemicals will open up a large array of possible recipes.

**Comment by dunstad** [comment]
I'm a little worried that finding far more disposable batteries than rechargeable ones might not be that realistic, although I haven't been able to find any useful information about that. Any idea where might be a good place to look?

**Comment by anothersimulacrum** [comment]
In my personal experience, rechargable batteries are much rarer than disposable ones - that said, I have no hard evidence. You could try finding sales numbers?

**Comment by CorvetBlyat** [comment]
However, as solar and nuclear power is more commonplace in the world of Cataclysm, wouldn't it also make sense that rechargeable batteries would be more common than in real life America?

**Comment by BaumgeistOne** [comment]
I think we're missing a very important point here: rechargeable batteries are _rechargeable_.

If 20% of all manufactured batteries are rechargeable, then the majority of all batteries in working condition you will find when looting houses will be rechargeable.

Why? Let's say x rechargeable batteries are sold per cycle, and thus 4x disposable batteries are sold in the same span of time.

The disposables are used one time and then discarded. The rechargeables are used one time and then recharged.

In the next cycle, again there are x rechargeables sold, and 4x disposables, adding up to 2x rechargeables and 4x disposables in households.

Go through this cycle enough times, and the disposables will be a small minority in households, despite having a much larger market share of batteries sold. And since "Lifetimes of 500 to 1200 cycles are typical" ([https://www.mpoweruk.com/life.htm](url)), the rechargeables will keep on accumulating in households.

But if one were to loot a factory for batteries, sure, the disposables will be in the majority.

**Comment by roaringjohn** [comment]
Not to mention that it's said that the C battery, in terms of Cataclysm's batteries, has about 40 "charges". Which means the batteries in Cataclysm would have more of a charge than C batteries.
http://data.energizer.com/pdfs/non-rechargeable_faq.pdf

> When stored at room temperature (i.e. 70°F/ 21°C), cylindrical alkaline batteries have a shelf life of 5 to 10 years

**Comment by BaumgeistOne** [comment]
> What you aren't realizing is that batteries tend to last a long time, even disposable batteries. There'd be plenty of disposable batteries that still have charge after the Cataclysm due to this

Well, I guess we'd need to have numbers on how many batteries get trashed a year to know how much of a factor that is.

All I'm saying is that a very large percentage of rechargeable batteries that were sold the last few years will be around. For the disposable ones, that percentage will be a lot lower.

**Comment by BaumgeistOne** [comment]
By the way, in gaming terms, I do appreciate making rechargeables more rare, because it makes it a little harder to build an infrastructure for recharging the tools.

But I tend to get most of my rechargeables through cellphones and the like, so maybe this change will not affect gameplay that much...?

**Pull request merged**
