### PR TITLE
Quick typo fix for Xedra Evolved (mics to misc)

### LINKED ISSUE #65498: [Xedra Evolved] Misspelled category in Xedra crafting tab
### Describe the bug

A group in the Xedra tab at crafting menu is written as `Mics`. Unless there's a Xedra Evolved Mic stuff pr i missed, i think it should've been `Misc`

### Attach save file

N/A

### Steps to reproduce

1.Get into world with xedra evolved mod on
2.get into crafting menu and go to xedra tab
3."Mics"

### Expected behavior

`Misc` instead of `Mics`

### Screenshots

Screenshot_20230506-095930

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a9fea5f [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FickDiddler**
#### Summary
Mods "Typo fix for Xedra Evolved"

#### Purpose of change
I am not sure if this was intentional, but misc is spelled as mics.

#### Describe the solution
From mics to misc. Or MICS to MISC.

#### Describe alternatives you've considered
Leave it be as it may be intentional.

#### Testing
Yup, just a quick spelling alteration. Nothing big.

#### Additional context
Closes #65498
Hope everyone is having a great day!

### CODE REVIEW

**Review by GuardianDll — APPROVED** [review]

**Comment by TealcOneill** [comment]
@FickDiddler If you use the link system then it will automatically close that issue when this one is successfully merged.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by FickDiddler** [comment]
Thanks for the helpful tip! Not sure if I did it correctly, but I added the Keyword "Closes" in front of the Issue number.

**Comment by bombasticSlacks** [comment]
Looks like the recipe has a mismatched category

**Comment by Maleclypse** [comment]
> Looks like the recipe has a mismatched category
These and maybe more need to be corrected.

```
ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe trinket_damage has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe trinket_range has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe trinket_sound has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe inventor_lasmod_close_range has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
+ test_exit_code=1
+ sed_exit_code=0
+ '[' 1 -ne 0 ']'
+ echo '--mods=dda,standard_combat_test,sees_player_retro,Tamable_Wildlife,alt_map_key,sees_player_hitbutton,blazeindustries,backrooms,no_fungal_growth,bombastic_perks,No_Rail_Stations,magiclysm,speedydex,stats_through_kills,package_bionic_professions,no_hope,tropicata,DinoMod,generic_guns,extra_mut_scens,deadly_bites,xedra_evolved,Only_Wildlife,megafauna,my_sweet_cataclysm,MMA,ruralbiome,cbm_slots,no_npc_food,Mythos-Creatures,translate_dialogue,personal_portal_storms,crazy_cataclysm,StatsThroughSkillstest exited with code 1'
+ exit_code=1
+ '[' 0 -ne 0 ']'
+ return 1
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe inventor_lasmod_long_range has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe inventor_lasmod_capasitor has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe inventor_lasmod_mega_capasitor has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
(all_mods)=> 16:12:02.100 ERROR : src/recipe_dictionary.cpp:665 [static void recipe_dictionary::check_consistency()] recipe inventor_lasmod_energy_safe has subcategory CSC_XEDRA_MICS which is invalid or doesn't match category CC_XEDRA
```

**Comment by FickDiddler** [comment]
Hmm, it would appear there are more things using MICS. I'll check the whole mod to see what other things to correct. Thanks for notifying me!

**Comment by FickDiddler** [comment]
Thanks everyone for the help! I thoroughly checked all the fines, and I am pretty sure no more recipes are using the MICS format. If you find more errors, please let me know!

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
