### PR TITLE
Allow overmap specials to use eocs.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
Infrastructure "Allow overmap specials to use eocs."

#### Purpose of change
More json power.

#### Describe the solution
Added ability to set an eoc for overmap_specials

### CODE REVIEW

**Comment by haveric** [comment]
Just a heads up that I'm restructuring the evac shelter to eliminate the duplicate entries for the computer in this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/57061, which is going to conflict with your changes here.

**Comment by Inglonias** [comment]
This EOC stuff continues to impress me with its versatility. Great job all around.

As for the change itself, while I support it, I can't help but wonder how sensible it is that these places are all so close to one another. I know the concept of distance in cataclysm is kind of fuzzy. It's still weird to me.

**Comment by PatrikLundell** [comment]
I definitely like the concept, but I'm not sure the CDDA world is ready for it, because there are a lot of things that can make these places unreachable and/or unusable.
- Fungal hell. These monstrosities have a RADIUS of 20 tiles, which can cover the features completely or partially, not to mention block access to them, at least until you've been able to get a vehicle that can smash through them both ways without falling apart. And each trip is worse than the previous one.
- Other monster structures, like those of ants, slimes, and triffids also cover areas as well as paths, although their radii are smaller. Also, once you're advanced enough, you can actually reduce the issue by killing off the roaming monsters.
- Choke points: Bridges are hard choke points, and they're often blocked in one or both ends. Most often by mine fields that can be bypassed with a little work (crate dragging, if your character is strong enough, exhausting smashing if not), but also by the monsters above, portals, or road blocks. "Lesser" blockers like wasp nests and fungal structures can also block passage until you're advanced enough to deal with them. In addition to the hard choke points you also have soft ones in the form of roads through forests and swamps. If something blocks your passage there you can bypass them on foot (in forests: the swamp survivability is questionable, and swamp monsters tend to block roads as well), but that's of limited value if you've still have a long way to go to actually reach the destination.

I don't have a problem with the sites being close to each other. In my view there sort of are other things in other places, but they haven't been implemented yet, so until the day there are enough of these things to place them evenly over the map with a reasonable spacing (which will probably never happen) the player centric distribution sort of indicates that these are the things in your vicinity, and they happen to be the same ones from one play through to the next one because those are the only ones implemented.

**Comment by Ilysen** [comment]
I probably don't have much new to offer, but I can comment that I've been using global uniques for my playthroughs for the past few weeks (there was an orphaned PR before this one whose code I up until this one) and I can report that things, for the most part, work well. The refugee center comes to mind as a special that is surrounded by its very large fence that's flagged to prevent fungaloids etc. from spawning inside of it; the Isherwoods have their giant forest around them. Hub 01 is vulnerable, but the way you speak to the faction is through an intercom that's inside of a concrete building (although the Free Merchants that show up outside, after mission 2, are vulnerable.) The isolated artisans do, however, come to mind as particularly affected, although they're surrounded by a trench of spike pits and turrets.

While others are vulnerable to locations like anthills, they're also vulnerable to that in the existing game right now too. I guess the point I'm trying to make is that the large majority of affected specials already have in-built measures to let them be accessible without breaking them even if there are environmental hazards around the, and the ones that don't have direct code measures (like a large fence) have indirect defensive measures (like a large collection of milspec turrets.) I personally believe that making these locations unique contributes to verisimilitude more than it risks detracting in the experience, but that's just subjective.

**Comment by PatrikLundell** [comment]
Well, I've kept away from Isherwood in my current game, as most of that "giant forest" is within fungaloid territory. The area is large, but the people are spread out, so most of them are fairly close to one border or another. I think the forest house side is outside of the horror zone, but that's not particularly useful.

In my 0.E2 game a part of the Tacoma farm was within acid ant territory (although I managed to kill them off there).

The pits "protecting" the artisans are useless because of how zombies spawn, which allow them to spawn inside what should have been impassable defenses. The turrets may work, though, although not against the mycelium spread.

If the locations are unavailable due to any blockers, you can currently work around it by going to another. The Refugee Center - Tacoma farm link is strong and problematic, while the Refugee Center - Hub01 is less so: you can visit another to get its quests, although the Refugee Center quest chain gets blocked. All of the Refugee Center - Lab quests (and thus their chain) are quite vulnerable, although the chance of a subway access provides a second chance for some of them (in my current game the Ice Lab one has to pass through fungaloid territory. I've made one trip in a normal vehicle, but further trips probably require something that can mow them down).

It can also be noted that the Refugee Center is constructed such that there is only a single path through which you can reach it with a vehicle (which is essentially required to haul a lot of the stuff required by quests), and that path tends to pass along several sides of the site, making them quite vulnerable unless they happen to be next to plains.

**Comment by dseguin** [comment]
Just linking to the previous discussion about unique locations in #49322

**Comment by esotericist** [comment]
while i absolutely want this to happen in the long run, i still think it's premature. most notably, i think we need better frameworks for making sure key locations are a) better spread out, b) have actual connectivity (such as getting highways/freeways working again). i'll cite [kevin's post in the aforementioned PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/49322#issuecomment-862475937) for his previously stated position on that.

we have somewhat better protections against key pieces of content being rendered nonfunctional at world generation time than we did as of my very long-winded comment in that same PR, but i personally don't think we have exactly enough groundwork just yet pull the trigger on actually forcing only one each of these locations.

**Comment by Zireael07** [comment]
Counterpoint: poor connectivity but one of each is better than spawning lots of those. Highways have been planned for years and have yet for materialize, so I wouldn't wait on those.

**Comment by PatrikLundell** [comment]
I politely disagree with @Zireael07 : My opinion is that multiple instances is a work around for the very high risk of inaccessibility of one or more of the proposed unique instances. Highways (when/if they appear) would reduce the inaccessibility issue somewhat, but that wouldn't be sufficient.

**Comment by esotericist** [comment]
i mentioned highways as a possible way of addressing the connectivity issue, i was not suggesting it was a hard (or sole) pre-requisite. there are a number of other concerns, discussed in the previous PR. i didn't feel the need to rewrite all of that out again when the previous conversation was right there.

but the connectivity problems are substantive *now*: we do not have adequate cross-connections between points of interest, so we do not reliably generate a road network, but instead get a strangely sparse mesh.

as patriklundell indicates, the locations being able to spawn more than once are a way of mitigating connectivity issues, ensuring content is not being localized to a small area, recovery from content rendered inoperable in worldgen, and other issues.

i'm not going to claim we need to solve all of the issues in advance, but we at minimum need a _**plan**_ and a better accounting of what all can be done to continue to improve the game around this part of the design, rather than up front worsen it in several respects just for the sake of a single concern.

**Comment by Ramza13** [comment]
Ok so based on feedback I have removed the json changes, for now this is just the framework for making things unique or basing spawning on world events or time.

**Comment by I-am-Erk** [comment]
#57419 is a tangentially related suggestion that would help with some of the same unique spawning issues.

**Comment by Zireael07** [comment]
@I-am-Erk: If NPCs had some way of being uniquely tagged and/or having slightly different names/dialogue (replace a word or two, I'm reminded that someone wanted to flag snippets based on amount of curse words and the like and match them to NPC personality? ) then that would likely reduce or completely obviate the need to make those locations unique

**Comment by I-am-Erk** [comment]
> @I-am-Erk: If NPCs had some way of being uniquely tagged and/or having slightly different names/dialogue (replace a word or two, I'm reminded that someone wanted to flag snippets based on amount of curse words and the like and match them to NPC personality? ) then that would likely reduce or completely obviate the need to make those locations unique

Reduce, not obviate. We still don't want empty versions of hub01 appearing. Many other locations we'd probably want a modified version, not the same one but without NPCs.

**Pull request merged**
