### PR TITLE
Spear and staff weapon balance (Part 7 of melee weapon balance project)

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary

```SUMMARY: Balance "Rebalances spear and staff weapons"```

#### Purpose of change
Mlangsdorf has been doing some deep analysis of the melee weapons and both analysis of dps of weapons and evaluating their strength ingame, and started a large "melee weapon balance" project. His analysis and his proposed values can be found here:
https://docs.google.com/spreadsheets/d/14eQIe4AO_f6OxCt1XcB4NLAs6-5R1wQW-ydZG0orYdY/edit#gid=1655515751
He wanted someone to start implementing the new values ingame, so i started work.

#### Describe the solution
Rebalances spears and staff weapons according to excel sheet.
#### Additional context
Credit to Mlangsdorf for the excellent analysis and for most of the proposed values.
Credit to vastin for review of the excel sheet.
Credit to hymore24/hirmuolio for the initial complaint.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
This seems to be failing a melee weapons test and i don't see why so i probably won't be able to fix the test failure.

**Comment by SirPendrak** [comment]
L-stick get +4 to hit when its turned ON, wutttt? 
The comment in pipe spear saying it has same stats as some old version of steel spear is no longer true since all the changes, probably could be deleated. 
Oh boy, theese buffs on pike, i can already smell new drama. IMHO lastest nerfs to it were not resonable but this thing swings from being super OP to being total crap and then being super OP again.

**Comment by mlangsdorf** [comment]
L-staff base -2
Grip: Weapon +2
Length: Long +2
Striking Surface: Every +1 (electric weapons are a canonical example)
Balance: Balanced +1
Total: +4

It's still a balanced stick and has crap DPS.  Insane accuracy numbers have a rapidly decreasing benefit, because the standard deviation of the normal curve for attacks is 5.

The pike is reasonably good at range 2 or 3 - 44 pierce at +0 Acc for 162 moves gives it the same DPS as the better knives, but then it get a big bonus for that reach.  In close, it's considered a polearm and is doing 30 pierce at +0 Acc for 162 moves, and you should replace it with a combat knife.   So it should be a good weapon if you use it properly but it's not so great if you get mobbed.

**Comment by kevingranade** [comment]
I think the test failure is the pointy stick, and just glancing at the numbers, they seem really high? Either it's a thin stick that makes a small wound, or it's a thick stick that's going to have trouble penetrating?  Technically the problem is just that the numbers changed.

**Comment by SirPendrak** [comment]
> L-staff base -2
Grip: Weapon +2
Length: Long +2
Striking Surface: Every +1 (electric weapons are a canonical example)
Balance: Balanced +1
Total: +4

But come on, its not a taser, its just a fancy glowing batton. If its light makes it easier to score a hit then its descrieption should mention it being a friking lightsaber.

**Comment by Brian-Otten** [comment]
Pendrak has a point in the L-staff, it does only give light and not have actual electric or other additional effects when turned on. I did a bit of a doubletake when i first saw it and put it in anyway, but it probably should be at +3 like the quarterstaff and the L-stick (off)

**Comment by Brian-Otten** [comment]
Also agree with kevin, pointy stick should pretty much be in the "weapon of desperation" tier, adjusted it here and in the spreadsheet to lower piercing damage.

**Comment by Brian-Otten** [comment]
Lowered L stick value when on to 3 and adjusted it in the spreadsheet as well.

**Comment by Brian-Otten** [comment]
Spears got a second balance pass after some more feedback and i'm filling in the numbers to PR now.

**Comment by Brian-Otten** [comment]
Numbers were all filled in. Barring anyone noticing things that still need changed this should be good to merge.

**Comment by Brian-Otten** [comment]
Had a quick look, for the pointy stick to pass the test the values the test expects need to edited. changing the values to the new one seemed simple enough but i'm not sure what expectations the test has when setting dps values.

The lines that need editing (i think) are lines 182 to 189 in iteminfo_test.cpp

**Comment by mlangsdorf** [comment]
```diff
diff --git a/tests/iteminfo_test.cpp b/tests/iteminfo_test.cpp
index 09fd28c8a9..39318bef45 100644
--- a/tests/iteminfo_test.cpp
+++ b/tests/iteminfo_test.cpp
@@ -179,14 +179,14 @@ TEST_CASE( "weapon attack ratings and moves", "[item][iteminfo][weapon]" )
         test_info_equals(
             item( "pointy_stick" ), q,
             "--\n"
-            "<color_c_white>Melee damage</color>: Bash: <color_c_yellow>4</color>"
-            "  Pierce: <color_c_yellow>8</color>"
-            "  To-hit bonus: <color_c_yellow>+1</color>\n"
+            "<color_c_white>Melee damage</color>: Bash: <color_c_yellow>5</color>"
+            "  Pierce: <color_c_yellow>9</color>"
+            "  To-hit bonus: <color_c_yellow>-1</color>\n"
             "Moves per attack: <color_c_yellow>100</color>\n"
             "Typical damage per second:\n"
-            "  Best: <color_c_yellow>11.33</color>"
-            "  Vs. Agile: <color_c_yellow>5.93</color>"
-            "  Vs. Armored: <color_c_yellow>1.24</color>" );
+            "  Best: <color_c_yellow>12.47</color>"
+            "  Vs. Agile: <color_c_yellow>6.53</color>"
+            "  Vs. Armored: <color_c_yellow>1.28</color>" );
     }
 
     SECTION( "no damage" ) {
```

**Comment by Brian-Otten** [comment]
Patch has been applied to the test. Thanks for writing it up.

**Pull request merged**
