### PR TITLE
Enlarge body status window

### PR DESCRIPTION
**Pull request by moxian**
#### Summary
Interface "Makes the Body Status window slightly higher"

#### Purpose of change

The current size of Body Status window is a bit too small, and the body part info on the right gets cut off even when the character is wearing nothing (and gets cut off even more with every subsequent piece of clothing). This makes getting and overview of the armor values somewhat inconvenient using the interface.

#### Describe the solution

Make the window higher.
And vertical center the ascii-art now that it doesn't fill the entire area alloted to it.

#### Describe alternatives you've considered

Condense the display of protection values from two lines per type

```
Bash:
    0.00  0.10  3.60
```

to a single line

```
Bash:  0.00  0.10  3.60
```

This will probably take some space from the leftmost column (the bodypart selection) and might still require making the whole window wider (albeit not taller).

I'm not sure if this is a better approach or not. The main reason i didn't do that (and went for increasing the height) is beacause i only thought of it after making the PR.

#### Testing

Old (live):
20230111-031125-cataclysm-tiles

New (PR):
20230111-032808-cataclysm-tiles

#### Additional context

cc @dseguin who originally added the UI in #57222

### CODE REVIEW

**Comment by dseguin** [comment]
The main reason the UI is sized that way is to support 80x24 character terminals (which we are still supporting). That's also why the body graphs are limited to 40x20.

You can make the panes increase in size dynamically if there's room available as long as the view is still readable at the minimum window size. Just slapping a higher number on the dimensions is not sufficient IMO.

This is how it currently looks in a 80x24 terminal:

current_80x24

Now with your changes the UI isn't rendered at that resolution since the top-left corner of the window is outside of the drawable area (Try it yourself). Even if you move the position of the top-left corner to be within the drawable area, the rest of the UI will be cut off.

**Comment by dseguin** [comment]
I recommend that you undo your changes and instead implement it like so:

<details>
<summary><b>( diff )</b></summary>

```diff
diff --git a/src/bodygraph.cpp b/src/bodygraph.cpp
index 6b117c079b..9801b42c1b 100644
--- a/src/bodygraph.cpp
+++ b/src/bodygraph.cpp
@@ -235,6 +235,7 @@ struct bodygraph_display {
     std::vector<std::string> info_txt;
     int partlist_width = 0;
     int info_width = 0;
+    int all_height = 0;
     int sel_part = 0;
     int top_part = 0;
     int top_info = 0;
@@ -276,7 +277,8 @@ void bodygraph_display::init_ui_windows()
 {
     partlist_width = 18;
     info_width = 18;
-    int avail_w = clamp( TERMX - ( BPGRAPH_MAXCOLS + 40 ), 0, 20 );
+    all_height = BPGRAPH_HEIGHT + clamp( TERMY - ( BPGRAPH_HEIGHT ), 0, 20 );
+    int avail_w = clamp( TERMX - ( BPGRAPH_MAXCOLS + 40 ), 0, 40 );
     for( int i = avail_w; i > 0; i-- ) {
         if( i % 4 == 0 ) {
             partlist_width++;
@@ -285,19 +287,20 @@ void bodygraph_display::init_ui_windows()
         }
     }
     int total_w = partlist_width + info_width + BPGRAPH_MAXCOLS + 4;
-    point top_left( TERMX / 2 - total_w / 2, TERMY / 2 - BPGRAPH_HEIGHT / 2 );
+    point top_left( TERMX / 2 - total_w / 2, TERMY / 2 - all_height / 2 );
 
-    w_border = catacurses::newwin( BPGRAPH_HEIGHT, total_w, top_left );
+    w_border = catacurses::newwin( all_height, total_w, top_left );
     //NOLINTNEXTLINE(cata-use-named-point-constants)
-    w_partlist = catacurses::newwin( BPGRAPH_HEIGHT - 2, partlist_width, top_left + point( 1, 1 ) );
+    w_partlist = catacurses::newwin( all_height - 2, partlist_width, top_left + point( 1, 1 ) );
+    int graph_vpad = clamp<int>( ( ( all_height - 4 ) - BPGRAPH_MAXROWS ) / 2, 0, all_height );
     w_graph = catacurses::newwin( BPGRAPH_MAXROWS, BPGRAPH_MAXCOLS,
-                                  top_left + point( 2 + partlist_width, 2 ) );
-    w_info = catacurses::newwin( BPGRAPH_HEIGHT - 2, info_width,
+                                  top_left + point( 2 + partlist_width, graph_vpad + 2 ) );
+    w_info = catacurses::newwin( all_height - 2, info_width,
                                  top_left + point( 3 + partlist_width + BPGRAPH_MAXCOLS, 1 ) );
 
     bh_borders = border_helper();
-    bh_borders.add_border().set( top_left, { total_w, BPGRAPH_HEIGHT } );
-    bh_borders.add_border().set( top_left + point( partlist_width + 1, 0 ), { BPGRAPH_MAXCOLS + 2, BPGRAPH_HEIGHT } );
+    bh_borders.add_border().set( top_left, { total_w, all_height } );
+    bh_borders.add_border().set( top_left + point( partlist_width + 1, 0 ), { BPGRAPH_MAXCOLS + 2, all_height } );
 }
 
 void bodygraph_display::draw_borders()
 void bodygraph_display::draw_borders()
@@ -328,7 +331,7 @@ void bodygraph_display::draw_borders()
     .offset_y( 1 )
     .content_size( partlist.size() )
     .viewport_pos( top_part )
-    .viewport_size( BPGRAPH_HEIGHT - 2 )
+    .viewport_size( all_height - 2 )
     .apply( w_border );
 
     scrollbar()
@@ -337,7 +340,7 @@ void bodygraph_display::draw_borders()
     .offset_y( 1 )
     .content_size( info_txt.size() )
     .viewport_pos( top_info )
-    .viewport_size( BPGRAPH_HEIGHT - 2 )
+    .viewport_size( all_height - 2 )
     .apply( w_border );
 
     wnoutrefresh( w_border );
@@ -347,7 +350,7 @@ void bodygraph_display::draw_partlist()
 {
     werase( w_partlist );
     int y = 0;
-    for( int i = top_part; y < BPGRAPH_HEIGHT - 2 && i < static_cast<int>( partlist.size() ); i++ ) {
+    for( int i = top_part; y < all_height - 2 && i < static_cast<int>( partlist.size() ); i++ ) {
         const auto bgt = partlist[i];
         std::string txt = !std::get<1>( bgt ) ?
                           std::get<0>( bgt )->name.translated() :
@@ -621,15 +624,15 @@ void bodygraph_display::display()
         } else if( action == "SCROLL_INFOBOX_DOWN" || action == "PAGE_DOWN" ) {
             top_info++;
         }
-        if( info_txt.size() >= BPGRAPH_HEIGHT - 2 ) {
-            top_info = clamp( top_info, 0, static_cast<int>( info_txt.size() ) - ( BPGRAPH_HEIGHT - 2 ) );
+        if( static_cast<int>( info_txt.size() ) >= all_height - 2 ) {
+            top_info = clamp( top_info, 0, static_cast<int>( info_txt.size() ) - ( all_height - 2 ) );
         } else {
             top_info = 0;
         }
         if( sel_part < top_part ) {
             top_part = sel_part;
-        } else if( sel_part >= top_part + ( BPGRAPH_HEIGHT - 2 ) ) {
-            top_part = sel_part - ( BPGRAPH_HEIGHT - 3 );
+        } else if( sel_part >= top_part + ( all_height - 2 ) ) {
+            top_part = sel_part - ( all_height - 3 );
         }
     }
 }
```

</details>

That will smoothly scale the UI's width and height based on the current screen's size.

Starting at 80x24:

new_80x24

And at 140x48:

new_140x48

**Comment by moxian** [comment]
Thanks! I didn't realize there was a good reason for the chosen size, but this makes sense now.

Dynamic sizing sounds like a good idea, I'll try to implement that!

However my PC hdd has *just now* suddenly died, so it might be a couple of days till i get things back in order and be able to code.

**Comment by dseguin** [comment]
> However my PC hdd has just now suddenly died, so it might be a couple of days till i get things back in order and be able to code.

I can commit the changes to a separate PR, or (if you'd like) I can commit them directly to this PR

**Comment by moxian** [comment]
Committed your diff with only insignificant style tweaks (mostly around the math distributing the extra width).
I'm not sure about the etiquette of this wrt attribution, given that I've contributed basically no code here, so feel free to close this PR and create a separate one if that'd be more appropriate.

(the hdd is back in action *knocks on wood*)

**Pull request merged**
