### PR TITLE
Balance biosil chitin items

### PR DESCRIPTION
**Pull request by Salty-Panda**
#### Summary
Bugfixes "Balance biosil chitin items"

#### Purpose of change

Closes: #48363

#### Describe the solution

Changes as suggested by @Venera3

Reduce durability of vehicle parts
Change values on biosil chitin material
Add NO REPAIR to biosil armors and update descriptions

Didn't block repairing of vehicle parts, since loss of acid-resistance is inessential

#### Describe alternatives you've considered

none

#### Testing

Checked in game

### CODE REVIEW

**Comment by souricelle** [comment]
If you wanted to make it more like the ESAPI vest, you could make the crafting recipe require a regular suit of chitin armor and some biosil pieces, then to repair it you'd deconstruct it to (hopefully) get your suit and some of the pieces back, then you'd grab your new biosil pieces and reassemble it to get it going again.

**Comment by Salty-Panda** [comment]
I might make some individual chitin pieces later, but it would be more around the idea of a light armor variant.

Like separate light torso armor, "joint protectors" with smaller coverage etc.

**Comment by Maleclypse** [comment]
Please open a new PR for this targeting the experimental branch.  Was closed as a side effect of deleting the 0.F -dev branch

**Comment by ZhilkinSerg** [comment]
Can you rebase it on top of current master please?

**Comment by Salty-Panda** [comment]
Rebased

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
