### PR TITLE
Aftershock: Translocators

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
Mods "Aftershock: Translocators for semi-convenient long range teleporting."

#### Purpose of change
Translocators for semi-convenient long range teleporting. And also because walking is sorta boring sometimes.

#### Describe the solution
There are three different translocation solutions included here:

-Recall rigs are the most simple, a vest type garment you load with a heavy battery and is good for one use.
-Implanted translocator CBMs are like the item above, but faster in activation and with a more convenient power source.
-The translocator armlet is the best in category, it uses expendable cells, but can both lay down new translocation targets and teleport you to existing targets with near instant speed. Its the only way to create your own teleport targets for now, and due to its speed it can also be used to escape or controllably teleport mid combat.

#### Testing

Tested the new items. and made sure that existing deployable furnitures still work properly after the relevant code adjustment.

#### Additional context

### CODE REVIEW

**Comment by Mom-Bun** [comment]
Ohhh, these are cool!

I'm guessing a lot of these will be extremely useful for looting runs, and some potentially to get out of danger.

Do they give the teleport sickness in base game? or avoid it?

**Comment by John-Candlebury** [comment]
They dont give teleport sickness, mostly because I dont think it fits the setting.

Hoping that just rarity will mean that they wont be that widespread in use either, if they are to convenient  I'll look into limiting them in other ways.

**Comment by Mom-Bun** [comment]
That works; this seems to be good so far, and from what I can tell the current spawn locations are just ordinary bionic locations plus military locations right?

**Comment by John-Candlebury** [comment]
Yeah although the more rare elements should be the telepads and other valid translocation targets.

**Pull request merged**
