### PR TITLE
Leather tarp for butchering (or picnic)

### PR DESCRIPTION
**Pull request by nexusmrsep**
Reference: #24878, #24874

This PR adds a **leather tarp**.
Think of a picnic blanket, but made of leather.
It serves as an **equivalent to other flat furniture needed for butchering** like table, counter, washing machine, dryer, pool table, coffin (I'm dead serious here, you can butcher using a coffin).

- can be sewn from leather, fur, tanned hides or pelts
- can be deployed and rolled for transportation.

All in all a more portable and accessible version of previously added tourist table.

### CODE REVIEW

**Comment by EirenexTheDragon** [comment]
have you thought of an cloth version or alternative with wood or so perhaps? since this very leather is hard to get by without being able to do the proper butchering. (for example survival with no city, cept for butchering leather stuff on corpses)

**Comment by nexusmrsep** [comment]
Yes, a wooden construction. As it can be hard to obtain if you can't butcher without it to get the pelt...
Can you suggest a name for a simple construction made from wood that can be another equivalent? Or actual construction as a reference?

Cloth is useless as it soaks with blood and would need cleaning.

**Comment by EirenexTheDragon** [comment]
i mean that could allow the player to require and use water to clean it off with cloth. a simple Butcherboard maybe? it is what you see in kitchen, and i understand it makes little sense for larger animal, so there could be perhaps a larger version that is to be installed on a frame maybe.

**Comment by nexusmrsep** [comment]
Reference: #24885

**Comment by FantasticFwoosh** [comment]
A comitatus would be more than feasable with some `long sticks/heavy sticks`, connecting `thread` material in large quantities, `wood splinters/needles/nails` to hold the tent down & a `leather tarp` layered over with a hammer used in its construction due to the nature of it being non-easily foldable for re-deployment like modern camper tents.

comitatus a roman style army tent
________________________________________

* Eitherway, the capacity to put objects onto a portable surface like this if not also for roleplay but practical application is much appreciated and broadens skills like tailoring to have increased value.

**Comment by FulcrumA** [comment]
The thing that bothers me is that even such a tarp shouldn't be necessary for indepth butchering, merely considerably helpful.

**Pull request merged**
