### PR TITLE
JSONify moon & lighting widgets

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
Contributes to #55076.

#### Describe the solution
- [x] Add condition for comparing fine detail vision (for lighting)
- [x] Convert moon and lighting widgets to use conditional clauses
- [x] Remove orphaned `widget_var`s
- [x] Unit tests

#### Testing
Added unit tests to verify that moon phases and lighting correspond to widget text.

##### Manual testing
Lighting:
light_bright
light_cloudy
light_dark
light_verydark

Moon:
moon_0
moon_1
moon_2
moon_3
moon_4
moon_5
moon_6
moon_7

#### Additional context
Another 2 down :P

### CODE REVIEW

**Comment by Maleclypse** [comment]
So now that this is jsonified a mod like Aftershock or even during portal storms would be able to set multiple moons at different states?  Like Large Moon 1 is full Medium Moon 2 is waning and tiny moon three is eclipsing moon 1?

**Comment by dseguin** [comment]
> So now that this is jsonified a mod like Aftershock or even during portal storms would be able to set multiple moons at different states? Like Large Moon 1 is full Medium Moon 2 is waning and tiny moon three is eclipsing moon 1?

So the moon phases in-game are based on the actual lunar cycle:

https://github.com/CleverRaven/Cataclysm-DDA/blob/7ba05c95d6819fe4589777b97e1ff8dee3214695/src/calendar.cpp#L78-L88

If you want to track alien/multiple moons, you'd need to add these as new moon phase functions (or more realistically, the moon phases should be JSONified).

What you *could* do here, is add conditions for special events, like a portal storm:

moon_special
```json
{
  "id": "moon_phase_desc",
  "type": "widget",
  "label": "Moon",
  "style": "text",
  "clauses": [
    {
      ...
    },
    {
      "id": "portal_storm_moons",
      "text": "Enormous red moon",
      "color": "red_red",
      "condition": {
        "and": [
          { "compare_int": [ "moon", "==", { "const": 4 } ] },
          { "is_weather": "portal_storm" }
        ]
      }
    }
  ]
}
```

**Comment by Maleclypse** [comment]
> > So now that this is jsonified a mod like Aftershock or even during portal storms would be able to set multiple moons at different states? Like Large Moon 1 is full Medium Moon 2 is waning and tiny moon three is eclipsing moon 1?
> 
> So the moon phases in-game are based on the actual lunar cycle:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/7ba05c95d6819fe4589777b97e1ff8dee3214695/src/calendar.cpp#L78-L88
> 
> If you want to track alien/multiple moons, you'd need to add these as new moon phase functions (or more realistically, the moon phases should be JSONified).
> 
> What you _could_ do here, is add conditions for special events, like a portal storm:
> 
> moon_special
> 
> ```json
> {
>   "id": "moon_phase_desc",
>   "type": "widget",
>   "label": "Moon",
>   "style": "text",
>   "clauses": [
>     {
>       ...
>     },
>     {
>       "id": "portal_storm_moons",
>       "text": "Enormous red moon",
>       "color": "red_red",
>       "condition": {
>         "and": [
>           { "compare_int": [ "moon", "==", { "const": 4 } ] },
>           { "is_weather": "portal_storm" }
>         ]
>       }
>     }
>   ]
> }
> ```

Nifty. :)

**Comment by wapcaplet** [comment]
> moon_special

That's no moon...

**Review by wapcaplet — APPROVED** [review]

**Pull request merged**
