### PR TITLE
Smokes shop tweaks

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
Content "Tweaked the contents of Smokes's shop"

#### Purpose of change

Right now, Smokes's shop inventory is all stored either in his bags or on the tile beneath him. At the time, EOCs were just getting started, but tech now exists to spawn the items in certain areas and restock them dynamically, and I wanted to make use of that.

This partially addresses #54776, but because the shop will still not clear goods that the player trades to Smokes, it isn't an actual solution to the issue.

#### Describe the solution

Changes to infrastructure:
* Split the `FREE_MERCHANTS_Shop` item group into three new items groups: `FREE_MERCHANTS_Shop_Gear`, `FREE_MERCHANTS_Shop_Parts`, and `FREE_MERCHANTS_Shop_Merch`.
* Smokes's shop is now split across three types of furniture: one shelf with the gear and tools (which replaces a trash can), one shelf with the spare parts, and a desk with the merch.
* These furniture pieces are restocked every week using a new EOC that triggers nested mapgen updates. All items on the furniture when it restocks are erased, and new stock is added in their place.
* If Smokes dies, the furniture will no longer update.
* Default mapgen in the office is unchanged due to how the mapgen is split in the relevant json file. Some stuff will still show up in the filing cabinet during initial generation, and so on.

Changes to shop inventories:
* Now stocks copper wire and steel wire.
* Now stocks 1-2 of each clothing group, instead of 0-1.
* Now stocks 1-2 iterations of melee weapons, instead of just 1.
* Now stocks substantially more tools, as well as electronics tools.
* Now stocks more duct tape and superglue.
* Now stocks 1-2 glass sheets per iteration of the parts group, instead of 150-200 glass shards. (This was made since it seemed weird to me to straight-up sell you glass shards - how would they store them, and why? You can still get a load of glass shards from sheets, and this also makes more sense as something they'd actually stock!)

#### Describe alternatives you've considered

1. I remain uncertain if the balance for this shop is at a good spot. I don't know what the Free Merchants should canonically or realistically offer, given their situation. I'm open to and encourage feedback on this.
2. I'd like to create a functionality to erase all of the items that Smokes has received via trade when the shop restocks, but I've been having trouble doing this. My go-to solution right now has been attempting to create a new type of zone that received items go to (which works), but for some reason, the code is not detecting a zone placed in mapgen if the refugee center is at certain rotations.

#### Testing

Spawned in at the refugee center using the Safe Place start and surveyed the stock in each piece of furniture. Fast-forwarded time using debug, then switched overmap tiles to observe a brief game hitch, and went back to discover that the furniture had restocked. Killed Smokes using debug and observed that this no longer happened even after more fast-forwarded time.

#### Additional context

Smokes before this PR. The shelf only has a bottle of melatonin.
cataclysm-tiles_tvTxyM1bp0

Smokes after this PR; no items are beneath him and his inventory only consists of what he generates with. The top shelf is for spare parts, and the bottom shelf is for equipment. Note the desk, which contains merch that can't be seen due to the player not being adjacent.
cataclysm-tiles_N6bPf71XGP

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Could the zone/rotation issue be caused by the zone ending up inside walls and the like at the problematic rotations?

**Comment by fairyarmadillo** [comment]
Since you brought up balance for Smokes, I will say that it would be great if he sold bags of cement, as they're not easy to find.

I don't know if the free merchants would have access to cement, I know they're short enough on rebar to put up with Makayla to get it, but it'd be cool if one of the faction camp building materials was buyable and that feels like a good candidate.

**Comment by PatrikLundell** [comment]
Where would they get it? If the refugee center did expand (probably with your help) to set up some industry that might be something they could produce, but otherwise their scavengers would be in the same situation as you are, and they ought to want to use any construction material for their own expansion/protection (just look at the sorry state of that so called fence...).

It can also be noted that faction camps have the logging option, making logs available, and you can also order companions to make planks, making them available as well.

**Comment by andrei8l** [comment]
> My go-to solution right now has been attempting to create a new type of zone that received items go to (which works), but for some reason, the code is not detecting a zone placed in mapgen if the refugee center is at certain rotations.

The zone rotation code wasn't bounded for z-level so zones were rotated too many times if maps had more than one level. I've fixed that issue in [my PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/56720) though. It seems we had very similar ideas so maybe we can work together.

**Comment by Ilysen** [comment]
Very good stuff. Since you seem to have a pretty better idea of what to do with that, I'll close this PR and wait 'til you're done with it, then I can re-open this one.

**Pull request closed without merging**
