### PR TITLE
[CR] Beginnings of monster behavior fix

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
Bugfixes "Changes monster behavior to make more sense"

#### Purpose of change

There are some considerable oddities in the monster behavior code relating to attitudes, factions, and emotions (anger/morale). This is a start on fixing some of those:
- The ordering of effects in monster::attitude()'s not-friendly section did not make sense.
- Some effects on morale conditional on anger level, such as from Animal Kinship (ANIMALEMPATH2), did not take into account the attack trigger level of 10.
- Take into account attitudes toward the player's faction and vice-versa in figuring out the behavior of monsters differing on whether they're friendly to the player or not.
- Pay more attention to mon_faction (monster equivalent faction). (These last two should fix the Whately cyberhound attack problem, unless that requires monster::plan() to be working better.)

#### Describe the solution

Rearrange the ordering and change the numbers compared to by the conditionals, for the first two. Check attitudes for the third. Do something with mon_faction aside from testing whether the factions are the same (assumed - incorrectly - to mean FRIENDLY was automatically the case).

#### Testing

None as yet - no time.

#### Additional context

Ping: @Venera3?

### CODE REVIEW

**Comment by Venera3** [comment]
I have given the factional behavior re: WARY etc some thought lately. The main problem I can see is that monster factions are an mtype-level thing, and faction relations are completely handled by factions. Do you think it would be possible for monsters to save a mutable "relation list" on generation in addition to their base faction, and modify this list in gametime to handle emergent faction relations? IE, the centipede faction includes `"wary": "zombie", "hate": "insect"`, on monster generation the newly spawned centipede extracts these to their own little relation list (possibly with some flag-based variations of what exactly wary is supposed to mean), and when checking for anger triggers if the mob tripping them belongs to a `wary` faction and the centipede is pissed off it flips its own zombie relation to `hate` without influencing the decision-making of other centipedes in the world.

**Comment by actual-nh** [comment]
> I have given the factional behavior re: WARY etc some thought lately. The main problem I can see is that monster factions are an mtype-level thing, and faction relations are completely handled by factions. Do you think it would be possible for monsters to save a mutable "relation list" on generation in addition to their base faction, and modify this list in gametime to handle emergent faction relations? IE, the centipede faction includes `"wary": "zombie", "hate": "insect"`, on monster generation the newly spawned centipede extracts these to their own little relation list (possibly with some flag-based variations of what exactly wary is supposed to mean), and when checking for anger triggers if the mob tripping them belongs to a `wary` faction and the centipede is pissed off it flips its own zombie relation to `hate` without influencing the decision-making of other centipedes in the world.

(Sorry I didn't see this earlier!) That's about what I was thinking would be needed. Before that, cleaning up the FRIEND_DIED and FRIEND_ATTACKED triggers with regard to actually using factions, not species, would be very desirable. If this PR functions properly in play, that and/or fixing the morass that is monster::plan() would be my next (monster behavior) goal, I think.

**Comment by LyleSY** [comment]
Should this have Feature Freeze?

**Comment by Night-Pryanik** [comment]
Closing as abandoned.

**Pull request closed without merging**
