### PR TITLE
Give Sadie more survival options.

### PR DESCRIPTION
**Pull request by KymasTuran**
#### Summary
Balance "Brief description"

Add some bionic to show why she is not starving or dead, also she is more badass now.
#### Purpose of change
Fun

### CODE REVIEW

**Comment by Maleclypse** [comment]
https://dev.narc.ro/cataclysm/format.html needs linting to be easier to review

**Comment by Zireael07** [comment]
IIRC bionics are slowly being phased out of the main game, no?

**Review by LyleSY — APPROVED** [review]
Definitely fits the spirit of the content

**Comment by KymasTuran** [comment]
> Definitely fits the spirit of the content

Thanks. Is one of my favorite NPC and I did a lot of edit on this one. I also add an option in is dialogue using is bio (cant find a better way) so I can ask for another injection. But even after "linting" both files still show red flags :p the other is for more deactivated robots for jury rig them later.

**Pull request merged**
