### PR TITLE
[MoM/CrazyCata Interaction] Rename Metaphysics to "woo woo"

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM/CrazyCata Interaction] Rename Metaphysics to "woo woo""

#### Purpose of change

As title.

#### Describe the solution

You're telling me all this nonsense works?? Jinkies!

#### Testing

Untitled2

### CODE REVIEW

**Comment by Psithief** [comment]
`spellcraft` is feeling left out.

**Comment by DukePaulAtreid3s** [comment]
Without Kevin?!?!??

**Comment by kevingranade** [comment]
They checked in with me on discord :D

**Comment by Standing-Storm** [comment]
> `spellcraft` is feeling left out.

I'll make a PR if I think of something funny, but nothing right now is coming to mind.

**Pull request merged**
