### PR TITLE
Fixes for the SWAT classes

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
fixes https://github.com/CleverRaven/Cataclysm-DDA/pull/56302#issuecomment-1094379676

#### Describe the solution
SWAT now wear pants, don't have two tactical vests on.

Added a new sheriff shirt variant for the black shirts worn by SWAT.

#### Describe alternatives you've considered
Adding specific SWAT pants

#### Testing
Load the game

Check that Swat professions have pants

#### Additional context

It works
image

image

### CODE REVIEW

**Comment by Termineitor244** [comment]
Could you add knee and elbow pads to the professions too? Many swat members I see online have them (painted in combination with the vest) and the old swat armor had some coverage in the arms and legs too to represent those sections.

**Comment by bombasticSlacks** [comment]
yeah that makes sense!

**Comment by Jarewill** [comment]
Just wanted to say that the profession still doesn't have any shirt.

**Comment by bombasticSlacks** [comment]
Oh my God why did they have no clothes on 😆

I'll fix it.

**Pull request merged**
