### PR TITLE
Placing specials around cities now scales with city size

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Bugfixes "Placing specials around cities now scales with city size"

#### Purpose of change

Originally specials were placed with a set min/max distance from a city center point, and the mapgen would work excellently as long as you kept the city sizes at the same setting.  Changing the slider up meant a larger city would start to "eat" up specials, leaving no close spawning specials on the maximum city sizes.  In this case it can lead to fewer specials available and things such as mission buildings or starting spawn structures being unable to be spawned.

#46881
Partially fixes this bug.

unable
This should happen less often as well.

#35376
Potentially fixes.

#### Describe the solution

The "can this belong to a city" ? check all specials go through was measuring the distance from the city center to the special location.

The line was changed to instead measure from the city center, minus the radius size of the city, so it is measuring from the edge of the urban sprawl instead.

#### Testing

Generating entirely too many maps to test.

You can see here - The farm min/max distances were changed temporarily to allow spawns only 10-20 blocks from a city.  You can observe how the farm placement scales in line with the citys size below.  The distance setting remained the same for each screenshot.

Size 1 town with farms around it to demonstrate distance scaling.

size zero town

Normal city sizing. 3 farms around to demonstrate.

normal city farms

City size 12.  Farms along the lower edge to demonstrate.

max size farms

#### Additional context

I have tried it with the special jsons unmodified, and it appears to all work well, the scaling moves fluidly as the city sizes are scaled up and down, and is considered on a per city basis. I don't think any further json modification would be needed at this stage. 

However it seems that the distance away is increased a little, with the more extreme city sizes.

### CODE REVIEW

**Comment by actual-nh** [comment]
It may be a good idea to add the default average city size to the radius, to keep things the same for that size. (Admittedly, that size doesn't seem to actually itself be being used...)

**Comment by stubkan** [comment]
> It may be a good idea to add the default average city size to the radius, to keep things the same for that size. (Admittedly, that size doesn't seem to actually itself be being used...)

I think I see what you mean.  I think since cities were generating at very different sizes at that level, sometimes size 1 as with the other pr as you saw that the distance settings were set to accomodate a variety so the settings are ... okay at this stage.

Perhaps Venara can chip in.  I'll be going over the jsons later anyway and might rework them similar to that other pr that got closed, and will check them then.

I think also, it'll be better to have the jsons to be changed directly if they need to be a different distance, rather than having the code do weird things like this that may not be apparent to future editors.

**Comment by actual-nh** [comment]
> > It may be a good idea to add the default average city size to the radius, to keep things the same for that size. (Admittedly, that size doesn't seem to actually itself be being used...)
> 
> I think I see what you mean. I think since cities were generating at very different sizes at that level, sometimes size 1 as with the other pr as you saw that the distance settings were set to accomodate a variety so the settings are ... okay at this stage.

Point.

> Perhaps Venara can chip in. I'll be going over the jsons later anyway and might rework them similar to that other pr that got closed, and will check them then.

Ping: @Venera3?

> I think also, it'll be better to have the jsons to be changed directly if they need to be a different distance, rather than having the code do weird things like this that may not be apparent to future editors.

😕

**Comment by Venera3** [comment]
That was quick! I had to use broader spawn bands than I'd liked to for some locations to account for the distance problem, that could be reined in a bit at this stage. Another implication is that microlabs can't spawn underneath large cities without modification. That will fix some weird subway station/lab overlaps, but it might make subway hopping a bit more predictable.

I'll give it a looksie in the next few days and adjust the distances if necessary. Could you also update overmap.md with the new distance rules?

**Comment by stubkan** [comment]
> I'll give it a looksie in the next few days and adjust the distances if necessary. Could you also update overmap.md with the new distance rules?

I'll go look at overmap.md, no worries.  

I think with strict spawning distance rules, theres a higher chance for specials to be unable to be placed, since they are placed randomly first, then only afterwards checked to see if they are meeting the rules.  So the loop to place them only runs 10 times, each.  So broad conditions may be good...

I want to do another branch for the special json, to tool it to accomodate more specials on cityless overmaps - maybe we can both work on it that way?

**Comment by Venera3** [comment]
I am not sure if they only get checked ten times. Back when I was beating my head against getting Isherwood to spawn properly I raised that cap to 100 iterations without any noticeable effect (on that special, at least).

I'd PR the adjustments mad necessary by these changes to your branch, if we're both happy with them they can be merged into this PR. There's no real rush, I think this will not make it in until the first experimental flurry on the new dev cycle dies down (and you can set it to be a Draft, so nobody merges it prematurely).

The cityless spawns I'd handle in a separate PR in the same way: github is made for collaborative changes, after all.

**Comment by stubkan** [comment]
> I am not sure if they only get checked ten times. Back when I was beating my head against getting Isherwood to spawn properly I raised that cap to 100 iterations without any noticeable effect (on that special, at least).
> 
> I'd PR the adjustments made necessary by these changes to your branch, if we're both happy with them they can be merged into this PR. There's no real rush, I think this will not make it in until the first experimental flurry on the new dev cycle dies down (and you can set it to be a Draft, so nobody merges it prematurely).
> 
> The cityless spawns I'd handle in a separate PR in the same way: github is made for collaborative changes, after all.

I think it goes like this,

Split overmap into sectors
proceed to place a special in 1 sector
try placing a random special
if special type is not individually capped yet (ie, only 2 hospitals per map)
then attempt to place one,
When placement success, less 1 try
otherwise keep trying
when counter reaches 10, proceed to next sector

So, I guess, it does keep going until something is placed.  Though the same issue remains, as it would end up placing other, easier to place specials before hard-to-place specials instead, getting the cap filled up with those.  There are mandatory specials though and they get placed first, so they are more guaranteed to be there.

I am not sure how big sectors are

**Comment by Venera3** [comment]
There are no mandatory specials anymore, apart from what a mission tries to place (and let's keep it that way, eh?). Sectors are 15x15 OMTs, as defined by `OMSPECFREQ`.

**Comment by actual-nh** [comment]
From my calculations, the average number to subtract from existing JSON min distance entries would be ~7 (6.85) with the old rng and default city size base of 8.

**Comment by stubkan** [comment]
> From my calculations, the average number to subtract from existing JSON min distance entries would be ~7 (6.85) with the old rng and default city size base of 8.

It is not necessary at this point to change the numbers, it is working within parameters - the parameters are just followed better.  The distance numbers were distributed in a way to accomodate default city spacing which included size 1 cities.  While, yes there will be a further pr at some point to fine-tune the numbers - they do work well at this point.  

But that aside, I'd like to ask...  Is the feature freeze necessary?  This pr fixes one of the more serious bugs that fails to generate starting locations.  So, I think this pr should be considered for inclusion.  If the reason for freezing it is because the numbers maybe need tweaking - I think it is much more serious that many specials don't generate at all.

Ie, you can start a new game on large city spacing and choose a golf course - most of the time it will fail.  But after this fix, you can successfully generate a golf course.  It gives people who use large city spacing for the first time, successful generating of specials that could not spawn before.

**Comment by Zireael07** [comment]
Feature freeze is so this doesn't generate unexpected regressions/weirdness just before release.

**Pull request merged**
