### PR TITLE
Additional color variations (blue, pink, etc.) for vanilla hairstyles that didn't have them

### LINKED ISSUE #62382: Add Standard long hair for the new hair colour types
### Is your feature request related to a problem? Please describe.

There should be standard long hair for the new hair colours (e.g Hair: blue, long , Hair: purple, long , etc) for all the new colours of hair that have been added like blue, purple, green and pink.

### Solution you would like.

There should be standard long hair for the new blue, purple, green and pink hair colours. 

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LazyFluf**
#### Summary
Bugfixes "Added color variations to hairstyles missing them"

#### Purpose of change

To add color variations to hairstyles that previously did not have them.  Fixes #62382

#### Describe the solution

Adds blue, green, pink, and purple color variations to the crewcut, mohawk, 'fro, medium-length, and long hairstyles in appearance_hair_styles.json in keeping with the existing coding style for Crow's hair mod.

#### Describe alternatives you've considered

Also adding color variations for the vanilla short hairstyle.
Simply not making this.

#### Testing

Created multiple characters, trying out various hairstyles.  All worked.  No graphic tiles have been created for the new hairstyles, but the trait showed up in my character menu.

#### Additional context

None needed.  At least I think lol

### CODE REVIEW

**Comment by KilroyWasHere451** [comment]
For some reason the changes the bot recommended made the .txt file look like hot garbage, just so you know.  I'm going to keep the original file, and would appreciate help that anyone would be willing to give.

**Comment by casswedson** [comment]
everything looks good here I would say; the pr's contents are fine, consider reopening

**Comment by harakka** [comment]
Just in case you're not aware, the project has a specific way that json files need to be formatted to keep things consistent, the bot does that for you, and it's needed for the content to be included. The game also comes with json_formatter.exe that does the formatting for you locally if you want to try it out.

**Comment by gettingusedto** [comment]
Looks like #62663 already did the thing for you.

**Comment by GuardianDll** [comment]
Well, we want not nice strings, but rather consistent strings, with the same style applied. We can resolve the issue here, but it'll make them ugly in another place

**Comment by KilroyWasHere451** [comment]
> Looks like #62663 already did the thing for you.

Yeah, I know.  Kinda sucks, I had to go to sleep before I could fix it :[

**Pull request closed without merging**
