### PR TITLE
DeoxyMod

### PR DESCRIPTION
**Pull request by cddaDeoxy**
This is a mod to make several parts foldable (generally at the same size as the item used to make the vehicle part, a few bigger) and make atomic lighting able to be "turned off", described as closing the cover so the light is sealed inside.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>make atomic lighting able to be "turned off"

That kinda removes the downside, doesn't it?

**Comment by Darkyhard** [comment]
Well, such a device is supposed to have a function which allows "turning off" the light by some means, so that you wouldn't have to move it to another room if you want to sleep.

**Comment by Rivet-the-Zombie** [comment]
The entire reason that they can't be turned off by default is so that they aren't better in all ways than other portable light sources which require fuel. I suppose their weight could be seen as another downside to them, though.

**Comment by Coolthulhu** [comment]
By the time atomic lights are available (barring a lucky drop early on), fuel for anything weaker than a flashlight isn't a problem.

**Comment by Rivet-the-Zombie** [comment]
This is true. With that in mind, I'm not really seeing much of anything here that would keep this stuff out of the mainline.

**Comment by kevingranade** [comment]
The large foldable parts would definitely keep it out of mainline, aisle
lights and such are fine, if a little weird to put on a foldable vehicle,
but quarter panels, engines and storage batteries are right out as far as
foldable.

I don't mind mainlining mods, but I have to ask, what's the goal here?  The
'foldable everything' changes are downright nonsensical.

**Comment by Cat09** [comment]
I think the idea is to have an Item-ication process to make it handleable in an item fashion rather than a vehicle fashion. as long as the total volumes make sense it should work... engines are big though, and they could by no means compress.

**Comment by kevingranade** [comment]
That's my point, that isn't what the foldable vehicle feature is for, so
I'd like to find out what is really wanted here, probably a separate
feature.

**Comment by Rivet-the-Zombie** [comment]
@cddaDeoxy, it would be really awesome if you were to move the toggleable atomic lights to a mainline PR.

**Comment by cddaDeoxy** [comment]
The atomic light issue can certainly be moved to mainline - someone want to tell me what to do differently?  Outside the game balance issues, the idea that you can't just put it inside a tube (gut a regular flashlight, for goodness sake!) is just plain ridiculous.  Heck, put it in your pocket, and it's significantly dampened...

As to the foldables: "I think the idea is to have an Item-ication process to make it handleable in an item fashion rather than a vehicle fashion."  EXACTLY this - and nothing I made foldable is "compressed" in terms of volume.

The main thing that made me think of it was the inability to TOW things, so I considered making EVERYTHING foldable at the same volume as the item that it takes to make it (except maybe the stuff that's made from sheet metal - it should probably be bigger, actually), but I didn't go that far.  Really, I think you could, though, as you can just take the silly thing apart and put it together again when you get there... anyway, here's the things I did.

I made all solar panels foldable at relevant solar panel item volume.

I made a foldable version of "extra light quarter panel" that already existed - it's made from a single pipe, foldable frames are made of exactly the same ingredients as extra-light frames, so I made foldable extra-light quarter panels take a pipe and have a lot less durability.

I made the swappable storage battery CASE foldable, but not the storage battery.  The small storage battery was already foldable (I didn't do it).

I made the little tanks foldable, but not the small or regular.

I made the small electric motor foldable - it's volume 4 as an item, so it's clearly VERY small.

I didn't make ANY engines foldable.

I added a foldable "armor" slot thing - a superalloy sheet (which otherwise seems to have essentially no use) that adds just a little bit of durability (not much).

I made a few more of the electronic things foldable - security system, camera system, clock, atomic light, that sort of thing.

The only stuff I've actually used (other than testing) was to make a 3x3 solar array that I can unfold and attach to whatever needs more power with a jumper cable.  It's a little over 250 volume and quite heavy, so it's not like I'll to carrying it around manually (I keep it in the storage area of my vehicle), and you really couldn't make something just a whole lot bigger and still be able to do anything with it, as it would soon go over 1000 volume and not fit in anything at all...

Hope that clears things up.

**Comment by kevingranade** [comment]
I suspected it was something like that, that'll be ok for now and it'll
become obsolete once we have better in-game support for towing things.

**Comment by karlnp** [comment]
A stone in the hand vs. two birds in the bush, as they say

**Comment by cddaDeoxy** [comment]
Even when there is better support for towing, I would support making all one-tile vehicles inherently foldable (or "itemable" or something).  Picking up a shopping basket and walking off with it (or throwing it in the bed of a pickup) is less absurd than picking up a 55-gallon drum full of water, for instance.

**Comment by kevingranade** [comment]
If that's the case it would be better handled with a check for the vehicle
being a single tile than marking a bunch of components as foldable.  That's
why I'm trying to get at what you want out of this, in case there are
better alternatives that do the same thing.

**Comment by cddaDeoxy** [comment]
Oh sure, that would certainly be very helpful - these sorts of changes are what can be done in the existing game, but improvements to the game would be very nice.

That said, I think several of these things are still better served by the "folding" mechanic - a foldable solar array larger than just one tile, for instance, makes a LOT of sense.  I was conflating the stuff that I actual put in the mod (stuff that I think is largely pretty reasonable, even after towing/vehicle merging/splitting is implemented) and what I was considering as a stop gap measure until then (essentially everything).

**Comment by cddaDeoxy** [comment]
Cool.  Thanks for all your hard work on CDDA!

**Pull request merged**
