### PR TITLE
[RDY] Updated subway railroad tracks

### LINKED ISSUE #23547: Subway corners and horizontal straight courses spawn misaligned occasionally
Game version:
0-c-27466
Operating system:
windows 10
Tiles or curses:
tiles
### Expected behavior
Subway tunnels are always aligned.
### Actual behavior
Subway corners occasionally spawn rotated 90 degrees misaligned. Straight courses spawn misaligned every few maps. Horizontal courses are affected.
### Steps to reproduce the behavior
Create a new world in the affected experimental and walk in a subway tunnel.

screenshot 1054

screenshot 1056

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- added diagonal tracks;
- added more railroad terrain variants (for using with tiles);
- made subway railroads 7 tile wide (to allow 5 and 7 tiles width railroad cars);
- added `"connects_to": "RAIL"`;
- removed `subway_tunnels.json` (fixes #23547).

# Screenshots:

image

image

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
@ZhilkinSerg are you going to work on this in the next few months?

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg are you going to work on this in the next few months?

I hope so. Though we are waiting for a new vault baby dweller to be delivered somewhere around next week, so I'm not sure about spare time yet :)

**Comment by Zireael07** [comment]
If I'm reading that right, congratulations are in order @ZhilkinSerg !!! <3

**Comment by ZhilkinSerg** [comment]
> If I'm reading that right, congratulations are in order @ZhilkinSerg !!! <3

Thanks!

**Pull request merged**
