### PR TITLE
Adds good mutations to their new categories

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Balance "Adds several positive mutations to mutation categories"```

#### Purpose of change
Some categories were missing mutations that thematically fit within them, some of which are also traits. Another problem is that many traits, both good and bad, are only obtainable at character creation, when they should also be obtainable through mutating. 

Another part to this issue is that many traits, such as Disorganized (-40% max volume) or Addiction Resistant (reduces the severity of addictions) are rarely picked. This happens for two reasons; one, there is a way to get more points/use less points with less disadvantage (e.g: don’t overuse addictive substances and you won’t need Addiction Resistant). Two, because some of the traits are impossible to remove in the game, such as Disorganized. This is because the only mutation that cancels Disorganized is Packmule, which is trait only, and traits can’t be purified, so it’s a permanent disadvantage.

This PR adds many negative and positive traits, to sort two variants of this issue out. First, if the player chooses Packmule, they never have to worry about losing it, since Disorganized (the only mutation to cancel Packmule) is trait-only, and being a trait it is unpurifiable. Second., if the player chooses Disorganized, they are given a permanent disadvantage they can never remove. A player with knowledge of traits would most likely pick Near-Sighted instead, every single time, since Near-Sighted is easily fixed by wearing glasses, and later resolved by installing Telescopic Eyes or mutating Scout.

This PR is part of a series of changes to mutation trees I have planned. The changes encourage the player to gamble with mutagen even more for the results they want (i.e: good, useful mutations), and to use more kinds of mutagen in a single play through. The point of these changes is to make gambling give greater rewards (i.e: traits like Stylish or Packmule), with greater risks (i.e: traits like Far-Sighted, Disorganized and Hoarder).

This PR fixes all the above issues by making many more traits mutatable. Traits which carry obvious psychological effects, or that come from a certain lifestyle (such as traits like Cannibal, Savant and Psychopath) are still trait-only.

This particular PR focuses on making positive mutations mutatable.

#### Describe the solution
Here’s a quick summary of the mutations, where they were added, and in some cases why they were added.

Insanely Dextrous - Added as a post-threshold Feline mutation, since all cats are very dextrous (they have 4 at the moment)

Very Perceptive - Added as a Feline mutation, since cats are good at spotting things.

Durable/Unbreakable (upgrades to Tough) - Previously unobtainable, since they were not part of any mutation categories and were not possible traits. Added to normal mutagen category, but still requires Tough to gain them.

Flowering - Added to Elf-A, which gives them another post-threshold mutation (they have 3 at the moment), while fitting in nicely with their other plant and beauty mutations.

Deft - Added to Cephalopod (they have lots of tentacles, and they are very flexible) and Feline (cats are very dextrous)

Good Hearing - Added to Feline, since cats have great hearing

Weak Scent - Added to Bird (Birds don’t smell that much)

Scout - Added to Bird, since birds have excellent eyesight.

Optimist - Added to Elf-A and Plant. It fits in the same way that other mutation categories have Bad Temper.

Strong Back - Added to Lizard, Cattle and Plant, both of which would have strong spines from their physiology (Lizards are four-footed and close to the ground, Plant has a body like a tree trunk, Cattle are pretty close to horses)

Spiritual - Added to Elf-A, and also involve a description rework. Elf-A is a very close-to-nature mutation line, so this fits in my opinion (after the description change at least)

Addiction Resistant - Became a mutation that can be mutated with normal mutagen. Will also be added to Cattle/Plant

Drunken Master - Became a mutation that can be mutated with normal mutagen

Stylish - Added to Elf-A, to go along with the superhuman beauty it grants (they would be vain/care about their appearance). Also added to Bird to go with their upcoming Preening mutation (in the next PR)

Masochist - Added to Medical. It’s a good, pre-threshold first step for Pain Junkie/Cenobite

Packmule - Added to Rat and Troglobite, since thematically they seem the most likely to be hauling large caches of supplies

Tough Feet - Added to Bird, since birds have tough feet

Parkour Expert - Added to Bird/Feline, because cats are very flexible, good at judging distance and excel at climbing things, while birds are light and great at hopping around/jumping short distances with their wings

### CODE REVIEW

**Comment by Mecares** [comment]
I disagree that all traits should be obtainable via mutations and or possible to get rid of via mutations.

**Comment by Fris0uman** [comment]
Optimist, stylish, drunken master and spiritual feel very weird as mutations.

Optimist could be a thing but it would need a rework of the description saying it has something to do with your internal chemistry ( endorphine and stuff) and might fit better in the medical mutant line then.

**Comment by Bulletfang** [comment]
Bird already has Scout and Medical already has Masochist (its stronger version at least), they're not on the wiki (because it's hella outdated) but you can see that they're assigned via the ingame mutation option in the debug menu.

**Comment by kevingranade** [comment]
Repeating from the sibling negative traits PR:

> Another problem is that many traits, both good and bad, are only obtainable at character creation, when they should also be obtainable through mutating.

This isn't a problem, this is working as intended.

Non-mutation traits use CANCELS very differently since it is enforced by character generation rather than the mutation system, adding traits with CANCELS as mutations has a much greater impact than that same character trait since you can, for example, gain a mutation that removes another trait, which is especially high impact when the cancelled trait is not supposed to be removable.

> This PR is part of a series of changes to mutation trees I have planned.

This worries me, you frankly do not seem to understand how the mutation system works, but you are proposing very far-reaching changes to it.

If anything, the mutation system is TOO far reaching and impactful to the game, and needs to be reigned in rather than increased in scope.

If you want to continue with this, please open a coordination issue to discuss your plans and how to make them happen, but from what I've seen so far I'm sceptical that our vision of how the game should work is compatible.

**Pull request closed without merging**
