### PR TITLE
More light sources [CR]

### PR DESCRIPTION
**Pull request by mugling**
Changes the wearable flash light to be worn as a head torch and adds a recipe for an upgrade 'survivor head torch' which is more durable and with a larger battery. Presuming there are no objections to #13673 I would intend to add the FRAGILE flag to the regular head torch but not to the survivor version.

It should be perfectly possible for zombies to claw at your (only?) source of light and leave you scrabbling around in the dark...

How about also adding much larger tubular aluminum flashlights that can function also melee weapons (think security guards), possibly with belt loops as suggested in #12089

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
>How about also adding much larger tubular aluminum flashlights that can function also melee weapons

Two hands for this.

**Comment by chaosvolt** [comment]
Ye olde flashlight of head-smacking would be interesting, yes.

Not sure what other suggestions to add. I almost wish solar-powered flashlights were a thing, but adding a way to make tools self-charge in sunlight (rather than being left in a vehicle charging station) would be beyond the scope of this PR.

**Comment by Ishindri** [comment]
Seconded on the heavier flashlights. Could also add handheld floodlights, something like [this](http://stormprepare.com/images/floating_flashlight.JPG).

**Comment by Rivet-the-Zombie** [comment]
>How about also adding much larger tubular aluminum flashlights that can function also melee weapons

>Two hands for this.

They're not that heavy; a 6 D cell Maglite only weighs a little over three pounds with batteries.

**Comment by chaosvolt** [comment]
I was gonna say, are they saying you'd need two hands to wield that, or is that a weird way of saying "I second this idea" instead? o3o

**Comment by mugling** [comment]
Single handed would seem more appropriate. Is it going too far to add a special DAZZLE attack?

**Comment by Coolthulhu** [comment]
> Is it going too far to add a special DAZZLE attack?

I'd say just limit it to light for now. There are more powerful light sources - for example vehicle floodlight - that do not dazzle.

**Comment by chaosvolt** [comment]
Though we could add that via abuse f the flashbang property. Would be too hackish, and again floodlights should be dazzling but aren't.

**Comment by mugling** [comment]
@Coolthulhu @chaosvolt the effect is greatest when shining a focused beam directly at the eyes. Still, probably too much complexity.

@Rivet-the-Zombie head torch chosen as the most obvious body part as one is needed for the item to be damaged. The existing wearable flashlight could also be updated to have a small area of coverage on the torso and possibly in other ways distinguished from a headtorch (brighter, larger capacity?)

**Comment by Rivet-the-Zombie** [comment]
>The existing wearable flashlight could also be updated to have a small area of coverage on the torso

Then it will cause encumbrance and it will never be used again; it's better to waste two volume of inventory space for the same effect, with no encumbrance.

**Comment by mugling** [comment]
Yes. The head doesn't have such a problem though?

**Comment by Rivet-the-Zombie** [comment]
>The head doesn't have such a problem though?

Correct.

**Comment by chaosvolt** [comment]
Exactly. Having it occupy the head slot, possibly the strapped layer, would be best.

**Comment by mugling** [comment]
So if we are excluding (for this PR anyway) solar-powered variants and any other wearable types (considering encumbrance) that leaves the heavy duty version.

Is the item I've implemented for this suitably balanced?

**Comment by Coolthulhu** [comment]
I'm not too sure about that balancing. The heavy-duty one doesn't consume much more energy, but has significantly more range. The old nerfed lights lost range, but didn't lose any energy consumption.

Also, the "survivor x" name.
It kinda makes sense in the case of survivor gear, because it is all custom made to be protective (to survive stuff while wearing it), but for the "survivor machete" and "survivor head torch" it sounds like an ego item name ("survivor machete of undead slaying", "razor boy's combat knife of cutting", "otaku katana" etc.).
"Reinforced head torch" would be better.

**Comment by chaosvolt** [comment]
Hmm. I'd always assumed that the survivor weapons/tools were implying they were essentially handcrafted, improvised but not shoddy. Like with the survivor mess kit being rigged from an oil lamp, if I recall.

It is a bit of an odd moniker, though.

**Comment by Chezzo** [comment]
I made wearable flashlights show on your head in the tileset, anyways. I had no idea they were on another layer.  I thought I even asked Kevin and dRbiG where I should put em too.

Flashlights have a wielded on and off too, because I made tiles before I knew how the game works.

**Pull request merged**
