### PR TITLE
Use acetylene torch to open all locked safes

### PR DESCRIPTION
**Pull request by jiornojiovanni**
#### Summary

SUMMARY: Features "You can now use an acetylene to open all locked safes"

#### Purpose of change

I thought it was weird that you couldn't open a safe using the torch, especially because you can open them with a pickaxe.

#### Describe the solution

Press a and use the acetylene torch near a Locked Safe, Gun safe, Jammed Gun safe or a  Electronic safe. Now they are open.

I used the same amount of time ( 15 seconds ) for the process as the metal doors, considering that the other options such as the stethoscope are pretty lengthy (I wanted to maintain that "difficult") .

Also It's a way to give something unique to the acetylene torch. Now you have more reason to carry it with you.

#### Describe alternatives you've considered

Curse every safe that I find because I can't open them.

#### Testing

Spawned all the safes described above and tested them. 
Also I searched for safes spawned naturally in the game world. They maintain the loot.

#### Additional context

first PR be kind :)

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Good work. 
Shouldn't there be a risk of setting fire to the flamable items inside included in this process?

**Comment by Night-Pryanik** [comment]
> Shouldn't there be a risk of setting fire to the flamable items inside included in this process?

This is the exact reason of why simple changes like these weren't implemented before.

**Comment by jiornojiovanni** [comment]
probably this is wrong, but I want to try anyway.
Now when I try to open a safe sometimes it start a fire and sometimes not (~50%, not really sure about that rng function).

**Comment by DialoMalison** [comment]
I think 15 seconds is way too short a time (for the door and the safe both). Acetylene torches operate at up to 4500 F. 
In this video [TheBackyardScientist](https://www.youtube.com/watch?v=9npSxELHxGo) used a plasma cutter (20,000 F) to cut the back panel from a floor safe and it took about 10 minutes. I think it would take longer with an acetylene torch.

**Comment by jiornojiovanni** [comment]
I based it on the time it takes in game to open a metal door (like the ones you find at the lab, I think). Tbh all these kind of operations should be much longer.

**Comment by kevingranade** [comment]
I'm inclined to agree about the time taken needing a large increase, I'm seeing 10+ minutes for doors and 3+ hours cited for safes.  But I also agree that this is a preexisting problem that shouldn't block this PR.

**Pull request merged**
