### PR TITLE
Treat format strings without arguments as pure string

### LINKED ISSUE #25892: Some tooltips doesn't properly load during character creation.
**To Reproduce**  
1. Go into character creation.
2. See this yourself.

**Screenshots**  
https://cdn.discordapp.com/attachments/290559371656822784/495267580798435351/bug_report_thexus.png

**Versions and configuration:**
 - OS: Win 7
 - Game Version: 7982
 - Graphics version: Tiles
 - Mods loaded: StatsThoughSkills, SimplifiedNutrition

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
```SUMMARY: Infrastructure "Treat format strings without arguments as pure strings"```

#### Purpose of change
Special case `string_formatter::parse()` without argument to treat the format string as a pure string. This ensures that format functions such as `mwvprintz` have the same behavior when passed a `std::string` (the non-template definition is chosen) or a `const char *` without argument (the template one is chosen). Fixes #25892.

#### Describe alternatives you've considered
An alternative is to change the new getters in #25860 to return `std::string`, but I think this approach is more general and IMO is how the behavior should be anyway.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by BevapDin** [comment]
How does translation affect this? Translations should pass through any formatting specifiers, be it a "%%" or a "%s" or a "%2$s". Remember that the translation may not happen at all (translation is deactivated at compile or runtime).

**Comment by Qrox** [comment]
Yes, you're right. What I meant is that for non-format strings, `%` should not be escaped no matter in the untranslated or the translated string, and for actual format strings, `%` should always be escaped untranslated or translated. Sorry for not being clear.

**Comment by BevapDin** [comment]
Yes, you're right. What I meant is that for non-format strings, % should not be escaped no matter in the untranslated or the translated string, and for actual format strings, % should always be escaped untranslated or translated. Sorry for not being clear.

What I mean is: in JSON (and in fact everywhere else) it's not clear what string is formatted and what string isn't, same as in the code itself:

```
add_msg( "The mutation makes you move 25% faster." ); // no formatting
// soon somebody changes it:
add_msg( "The %s mutation makes you move 25% faster.", mutation_name ); // formatting will be done
// now the % will make a difference
```

This is simply very inconsistent and can very easily cause errors.

**Comment by Qrox** [comment]
In your case, just change the second line to
```c++
add_msg( "The %s mutation makes you move 25%% faster", mutation_name );
```
Then with this PR both lines will give the correct result.

I understand your concern about inconsistency, but let's suppose that someone writes
```c++
add_msg( mut.desc() );
```
and someone writes in another place
```c++
add_msg( "Effect: %s", mut.desc() );
```
Without this PR, if `mut.desc()` contains `%`, then no matter it is escaped or not, only one line of the two will give the correct result.

Of course, we can alternatively:
1. Print every non-format string with `"%s"`. But that would also require not escaping `%` in the said string, since it's not used as format string anymore. And if someone wants to turn it into a format string, they'll still have to remember to escape the `%` when changing the code.
2. Return a `std::string` from `mut.desc()` or cast `mut.desc()` into a `std::string`. But having two very similar signature of a function to behave differently is in my opinion even more inconsistent and can more easily cause errors. The translation funtions such as `_()`, `pgettext()` etc also return `const char *`, and it's easy to forget to cast the result to `std::string`.
3. Change all formatting print/message functions to have different names from their non-formatting counterpart. I would rather not do it since it will inevitably turn into a super-bloated PR.
4. Also require escaping `%` in formatting arguments. ...Well, this will probably cause more problems than it solves. (With user inputs, for example.)

Simply treating format strings without argument as pure strings, then we just need to review current occurences of percent signs and adjust them, and remember to properly escape `%` in strings intended as format strings afterwards. When someone forgets the escaping rule, the mistake will also be immediately visible, either as duplicate `%` signs or error messages.

Anyway, if someone has better alternative please let me know, I'm more than happy to close this in favor of the better solution. Or if someone can think of a situation where this PR won't work, please let me know too.

And sorry for the wall of text. Since this PR now seems a bit contentious, I think it's necessary to provide more details about my thoughts.

**Comment by Qrox** [comment]
Changing this to WIP until I fix the failing tests and update percent signs in the code and json files.

**Comment by BevapDin** [comment]
> In your case, just change the second line to

Yes, it is easy *if you remember* to change the single '%' into '%%'. The "if you remember" part is the troublesome part.

> I understand your concern about inconsistency, but let's suppose that someone writes
> add_msg( mut.desc() );
>
> and someone writes in another place
> add_msg( "Effect: %s", mut.desc() );

Yes, this has the same problem. But here we have a simple rule: no user supplied strings as formatting string. So the first messages must be `add_msg( "%s", mut.desc() )`.

> Return a std::string from mut.desc() or cast mut.desc() into a std::string. But having two very similar signature of a function to behave differently is in my opinion even more inconsistent and can more easily cause errors. The translation funtions such as _(), pgettext() etc also return const char *, and it's easy to forget to cast the result to std::string.

`desc` should not return a `const char*`. We should not use anywhere `const char*` at all. The code is written and interpreted as C++, not C. (And you have many functions like that which return `std::string` anyway.)

> Change all formatting print/message functions to have different names from their non-formatting counterpart. I would rather not do it since it will inevitably turn into a super-bloated PR.

Not different names, but different types. This is something that I have thought about for a long time. Ideally we have a `format_string` class and a `formatted_string` class. The first is suitable as formatting string in `string_format` and the second can not (will throw a compile error). The classes could be convertible by escaping (`formatted_string -> format_string`).

> Anyway, if someone has better alternative please let me know, I'm more than happy to close this in favor of the better solution. Or if someone can think of a situation where this PR won't work, please let me know too.

Escape the '%' in the JSON data? This seems like the most simple fix. It has nearly effect on any code, while changing the behaviour of `string_format` affects nearly all code.

**Comment by RosaEscura** [comment]
Hi! Could you also rearrange the order of the traits to be alphabetical as it used to be? That'd be much appreciated. It's so difficult to find the traits you want quickly with the random order.

**Comment by Qrox** [comment]
> The "if you remember" part is the troublesome part.

> no user supplied strings as formatting string. So the first messages must be add_msg( "%s", mut.desc() ).

That's equally true for remembering to use "%s". And even if we use `%s` for all user-supplied strings, the user still have to remember to escape `%` in format strings while not to escape `%` in non-format strings. One thing to remember is better than two things to remember, isn't it? And I'd say if someone writes `add_msg( some_string )` it's very clear that `some_string` is not intended as a format string, since there's not format arguments. So treating it as a non-format string is arguably the expected behavior.

> desc should not return a const char*. We should not use anywhere const char* at all. The code is written and interpreted as C++, not C.

I chose to return `const char *` because that's what's returned from gettext. And even if we used `std::string` in this case, gettext still returns `const char *`, so there will still be problems if someone uses gettext directly.

> Ideally we have a format_string class and a formatted_string class.

That'll be the ultimate solution, but I'm afraid it will require some time to sort out how that interracts with the existing code and the gettext functions. Before that's possible this is a solution that is immediately viable.

> Escape the '%' in the JSON data? This seems like the most simple fix. It has nearly effect on any code, while changing the behaviour of string_format affects nearly all code.

That's just a workaround which does not fix the real problem. If someone uses the descriptions elsewhere as format arguments then it will break again. Also, this PR does not "affect nearly all code". It only affects code where a string is passed to a format function without arguments. I've looked into the code, and there's only a few places which need adjustments. And FYI, all occurences of literal percent signs in the json files are unescaped, which indicates that the json writers haven't formed the habit of escaping `%` in their strings. Perhaps it's better to cater to this (lack of) habit rather than trying to change it?

**Comment by Qrox** [comment]
> Hi! Could you also rearrange the order of the traits to be alphabetical as it used to be? That'd be much appreciated. It's so difficult to find the traits you want quickly with the random order.

Oops, it seems I screwed the sort function up in #25860. I'll post a fix for it too.

**Comment by kevingranade** [comment]
I agree with @BevapDin regarding this causing more confusion due to it effectively creating a seperate class of strings. Additionally I am very against making changes to how string functions work, and this change would make many "works in c++" examples break.

Specifically regarding add_msg( "%s", msg) vs add_msg( msg ) checking, there is build tooling to insure that the latter causes a warning/error that we have taken steps toward enabling, making the standard alternative more foolproof.

**Comment by Qrox** [comment]
Examples can always be updated, and I'd say if we want to check for `add_msg( msg )` and warn the author to change it to `add_msg( "%s", msg )`, why not simply treat `add_msg( msg )` as `add_msg( "%s", msg )` then? Can you give an example where `add_msg( msg )` cannot be simply changed to `add_msg( "%s", msg )`?

**Comment by kevingranade** [comment]
> Examples can always be updated,

They are from outside the project, so they cannot be.  The issue is format strings are "how c++ does string interpolation", and departing from how that normally works causes irreconcilable confusion.

> why not simply treat add_msg( msg ) as add_msg( "%s", msg ) then?

This has already been answered, because it's not a simple substitution (due to escape sequences), and because the adjustment has to be made to format strings (turning them into "literal strings") that are sometimes stored at a distance from the call site (in the case of post-translation strings, these aren't even in the repository!).

**Comment by Qrox** [comment]
Ok then. A final question: how do we solve the inconsistency that `add_msg( some_std_string )` does not do formatting, while `add_msg( some_c_string )` does formatting?

**Pull request merged**
