### PR TITLE
Use monster groups for pet store spawns and wilderness cat spawns

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
None

#### Purpose of change

Pet stores and wilderness spawns were hardcoding `mon_cat` and sometimes even `mon_dog`. This adds a dedicated `GROUP_PET_CATS` (+ the dog equivalent), uses it in pet stores (since pet stores get their animals from breeders, so there would be no mutants) and uses the stray equivalent for the wilderness.

#### Describe the solution

Adds some groups, one includes the other so there is no redundancy. I hate redundancy. Followup to #59104 but I actually want this to get merged first, even if this causes minor conflicts for me in the other PR.

#### Describe alternatives you've considered

Nested spawns? @Venera3 mentioned that but I hope this is fine, too. Only problem I am seeing with my current approach is that `GROUP_STRAY_CATS` in the wild would also include iridescent cats which are already handled separately for some reason.

#### Testing

Applied changes locally. Manually spawned pet stores and checked for the changes I was expecting. I also checked some natural spawns.
For the wilderness ones, I teleported around in the world a bit, staying close to nature-related structures in the cities like parks and sure enough: I saw more than shorthair cats.
I do not mean to brag but this all worked on the first try.

#### Additional context

Meow.

### CODE REVIEW

**Comment by NetSysFire** [comment]
Test failures look unrelated.

**Comment by nik-ovchin** [comment]
Is it somehow changed spawn rate? In innawood run I see dozens of cats everywhere

**Comment by NetSysFire** [comment]
This should not affect the spawn rate, but innawood has their own spawning stuff. @Light-Wave might know more.

**Comment by Light-Wave** [comment]
As far as I can tell, this should not alter spawn rates for Innawood in any meaningful way, no.

**Comment by nik-ovchin** [comment]
It is strange. Today I see only different cats while runing through fields. No crows, coyoute or other small animals.

**Pull request merged**
