### PR TITLE
Bleeding type for species

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Features "Bleeding type for species."

#### Purpose of change
Implement @kevingranade's [suggestion](https://github.com/CleverRaven/Cataclysm-DDA/pull/45000#issuecomment-720273025). 
Make it possible to bleed for most monsters (not only those with `WARM` flag and with `flesh` as material).
Make it possible to easily adjust bleeding type for species in json.

#### Describe the solution
- Added a `bleeds` field in `species.json`. It needs `field_type`. Defaults to `fd_null`.
- Added `get_bleed_type()` function which reads aforementioned `bleeds` field.
- If species doesn't have a defined bleeding type, they're considered immune to bleeding.
- Added various types of bleeding for various species: 
  `MAMMAL`, `AMPHIBIAN`, `BIRD`, `REPTILE`, `FISH`, `HUMAN` and `ZOMBIE` species bleed with `fd_blood`;
  `INSECT`, `CENTIPEDE`, `INSECT_FLYING`, and `SPIDER` species bleed with `fd_blood_insect`;
  `MOLLUSK` and `WORM` species bleed with `fd_blood_invertebrate`;
  `SLIME` species bleed with `fd_slime`;
  `PLANT` species bleed with `fd_blood_veggy`;
- I didn't completely replace `mtype::bloodType()` function with `get_bleed_type()` function as the former is useful for various rare edge cases, like for `mon_zpider_mass` monster, which has `ZOMBIE` first species type, but as it has `iflesh` material, it will bleed with `fd_blood_insect`.

#### Describe alternatives you've considered
Replace or complement checking for material type in `mtype::bloodType()` with check for species type. But it would be hardcoded, while my current variant allows changing bleeding type (or removing it altogether) with simple json editing.

#### Testing
Spawned giant frog, graboid, giant centipede and made them bleed. Checked if they actually bleed with their bleeding type field.

#### Additional context
изображение

изображение

изображение

### CODE REVIEW

**Comment by SirPendrak** [comment]
Accidic zombies and monsters still bleed acid?

**Comment by Night-Pryanik** [comment]
> Accidic zombies and monsters still bleed acid?

Yep.

**Comment by Venera3** [comment]
Would declaring it in the monster definition itself overwrite the species' blood data? And can you exclude a monster from bleeding, even if it has a species with blood data?

**Comment by Night-Pryanik** [comment]
> Would declaring it in the monster definition itself overwrite the species' blood data?

Monster flags are read before the species' bleeding type. So, for example, any monster with ACIDBLOOD flag will bleed acid, no matter what species it is. However, checks for specific flags (or combinations of these flags) are all hardcoded, and there ain't many of these checks, so in most cases the species' bleeding type will be used.

> And can you exclude a monster from bleeding, even if it has a species with blood data?

Not directly. Only through use of some hack, like changing the monster's in question species to something without bleeding type set.

**Comment by Shodan14** [comment]
What about a small chance for mobile mechanical enemies to bleed hydraulic fluid or whatever?

**Comment by Night-Pryanik** [comment]
> What about a small chance for mobile mechanical enemies to bleed hydraulic fluid or whatever?

I plan to add new fluids to bleed in subsequent PR.

> Oh and is the Mi-Go lymph fluid still included?

For some reason mi-gos have ARTHROPOD_BLOOD flag, so they will bleed fd_blood_insect. Might need to add specific Mi-Go blood, but again, in subsequent PRs.

**Pull request merged**
