### PR TITLE
Catches a few stray pixels in ChestHole's shrubs.

### PR DESCRIPTION
**Pull request by chaoko99**
Old
met8yw3

New
2smrqew

### CODE REVIEW

**Comment by chaoko99** [comment]
They became incredibly visible once they grayed out.

**Comment by Soyweiser** [comment]
Does this fix this? https://www.reddit.com/r/cataclysmdda/comments/7cxm2j/weird_black_frames_around_new_trees_in_chesthole

**Comment by chaoko99** [comment]
Doesn't touch that file.

**Comment by Cyrano7** [comment]
Just looping @Chezzo the creator of the tileset into the conversation.

**Comment by Chezzo** [comment]
Aww, I bet that is caused by turning software rendering on. I think I can fix it on my end.

I will make sure I make OP's change in my copy before I upload it too.

**Comment by chaoko99** [comment]
Any progress?

**Pull request merged**
