### PR TITLE
[Magiclysm] Add fantasy skin colors 

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Add fantasy skin colors"

#### Purpose of change

If you're playing a goblin, you should be able to have green skin, and if you're playing a dwarf, you should be able to have gray skin (like the stone), and if you're playing a lizardfolk, you should be able to have green, red, or blue skin, and if you're playing a ravenfolk, you should be able to have very dark skin (like actual ravens).

Also, I didn't realize originally when I gave elves the PALE mutation that it was a skin tone that overrode other skin color choices. You should be able to have dark-skinned elves.

#### Describe the solution

Make PALE visibility 0 and ugliness 0 for Magiclysm, since this a world with ravenfolk and goblins as part of society and very pale skin is not that big a deal. Add blue, gray, green, midnight, opal, and red as possible skin color choices. 

Remove PALE from NPC elves.

#### Testing

Options show up in-game, PALE is selectable as a starting trait.

#### Additional context

Not sure about `midnight` as the name for the very dark option, I'm open to suggestions.

### CODE REVIEW

**Comment by RedMisao** [comment]
I would add thematic names and tones for each race, such as dwarven pink and dark skin are "granite" and "basalt", while for lizardfolk red and blue are "salamander" and "iguana". To avoid anachronisms, one can argue that's how their names are translated to human language. This enables outlandish stuff such as non-humans having the rare iridescent skin.
This would also be a nightmare for people working from the graphical side.

**Comment by Standing-Storm** [comment]
> This would also be a nightmare for people working from the graphical side.

I could do it as a variant, I think, the way hairstyles work, and then the variants could just each link up to the same graphic, but because the species are set up as hobbies there's no way it could be contextual. The ideal solution would be that if you picked elf, then "skin tone: midnight" would show up as "skin tone: dökkálfar" (or maybe "skin tone: black cherry" if they're themed after trees) and if you picked dwarf it would show up as "skin tone: basalt", but what would actualyl happen is everyone would have access to every single variant it would crowd the list immensely.

**Comment by RedMisao** [comment]
> I could do it as a variant, I think, the way hairstyles work, and then the variants could just each link up to the same graphic, but because the species are set up as hobbies there's no way it could be contextual.

I _think_ this is possible by using species as professions, which force a "core" mutation, which blacklists minor appearance mutations you don't want (i.e. dwarf cannot choose elf ears). I don't say possible as I use the profession-to-core-mutation system to whitelist specifics, instead of the other way around...

> The ideal solution would be that if you picked elf, then "skin tone: midnight" would show up as "skin tone: dökkálfar" (or maybe "skin tone: black cherry" if they're themed after trees) and if you picked dwarf it would show up as "skin tone: basalt" (as you say), but what would actually happen is everyone would have access to every single variant and it would crowd the list immensely.

...the downside is that, due blacklisting a lot of options, the appearance list is cluttered with the appearances and variants you can't select




> How did you know I was planning to include this but took it out?

I was thinking in implementing a very annoying quest that relies in the PC finding a NPC with rare appearance traits at some point

**Comment by Zireael07** [comment]
I like 'midnight' for a very dark fantasy option <3

**Pull request merged**
