### PR TITLE
Fix for #25244

### LINKED ISSUE #25244: Travois don't carry enough volume!
During a recent hunting trip in game I managed to nab a coyote and a dachshund. I was carrying a Travois around so I could carry things back, but it struck me as pretty weird that a coyote couldn't fit on the Travois, but something as small as a wiener dog just barely fit, so I went ahead to do some research on Travois in general and saw video evidence repeatedly of people using home made Travois made with thick twigs and string to carry full sized people and deer around.

The Travois should probably at least carry 100 volume, just a little over a deer's volume. They're supposed to do that already, but I understand if that's a little too much volume for something like a Travois--- even if it makes so much noise from use.

Video proof and reference of a Travois being made and being used to carry a person around: https://www.youtube.com/watch?v=vCpo_giGWOM

### PR DESCRIPTION
**Pull request by Shinino**
#### Summary
Balance "Adjust travois capacity and deer, sheep, fat zombie and bloated zombie size to allow for travois to work as expected with medium-sized corpses."

#### Purpose of change
Fixes #25244 -- deer, sheep, fat zombies and bloated zombies should not be the same 'size' as a cow or chicken walker.  This is the reason that they cannot fit on a travois. 

#### Describe the solution
Adjusted size from LARGE to MEDIUM on all four of these.  

#### Describe alternatives you've considered
Originally, I considered changing the size on the travois itself from 200 to 400, giving it a volume of 100.0L (a large creature, in this case a deer, was 92.5L).  That would resolve the issue, but have the unintended consequence of loading, say, a chicken walker onto a travois.  Or any other large creature.  

Given the relative size of a deer, sheep, fat zombie and bloated zombie compared to a) large mammals such as cows, horses, bears and moose and b) the relative size of a fat zombie and bloated zombie to a zombie brute the simplest change appeared to be to adjust the size of these four to be more in line with their actual size.  

#### Additional context

Tested -- need to adjust travois size from 200 to 300 (75.0 L -- medium creature is 60ish L)

### CODE REVIEW

**Comment by cainiaowu** [comment]
We have mon_boomer /mon_boomer_fungus/ mon_boomer_huge both are LARGE.
Maybe mon_boomer and  mon_boomer_fungus should change to MEDIUM too.

**Comment by Shinino** [comment]
Eh.  Boomers are significantly larger than even a fat-person zombie, based on what I recall from Left 4 Dead.  I could see them being 700+ pounds, pushing 'Large' size.

**Comment by Shinino** [comment]
Side note:  Thinking about this, there are some medium monsters which can also be downgraded to small.  Coyotes being a prime example, as they top out around 45lb.  I'll poke at this more later.

**Comment by cainiaowu** [comment]
Well, perhaps mon_boomer_huge can push up to HUGE?

**Comment by Regilith** [comment]
I think @nexusmrsep is working on adding granularity to monster weights atm. Going around modifying flags might end up being wasted effort. See #24921 and #24909

**Comment by kevingranade** [comment]
Unless I'm missing something you also nerfed the butchering yields fir
these, was that intentional?

**Comment by nexusmrsep** [comment]
@kevingrenade its a problem of size granularity and weight being hard-coded derrivative of sizes and meat count being its derivative too, mentioned in recent issues. There is no space for ex. between human sized MEDIUM and a cow sized LARGE, so in result a 40kg SMALL (???) dog yields 1/3 of its weight in meat chunks. I pray that chihuahua was set to TINY, else it can rival a rottweiler in body mass. This PR by switching down one level of size to some smaller (mid size?) game is gracious, while there are some other more exagerated example where this lack of granuarity has stretched its usefullness. Give some guidelines where to go with untangling this problem and someone will pick it up. Cant remember issue number, but there is one, so if you can, please drop a comment.

**Comment by kevingranade** [comment]
It sounds warranted, just wanted to make sure it wasn't accidental.

**Pull request merged**
