### PR TITLE
PBA mask revamp: Second encounter.

### PR DESCRIPTION
**Pull request by Maskrow**
#### Summary

SUMMARY: Features "Changes to the PBA mask"
#### Purpose of change

More realistic approach to the different types of respirators, as well as the first step to make a tiered system of air filtration equipment at the player's disposal.
#### Describe the solution

Firefighter nitrox tank harness interacts with PBA mask similar to how power armor interacts with an UPS. The harness is reloaded with nitrox cylinders which are a magazine type item.
#### Describe alternatives you've considered

First version of revamp had separate ItemID for active PBA mask, but this approach - adviced by @Vasyan2006 - allows for the later addition of other types of the SCBA gear.
#### Additional context

The endgoal of this work will be the separation of different breathing equipment into different tiers that are going to have different downsides and upsides.
**Tier 1** would be simple clothing items that provide air filtration mostly as a side effect - bandanas, kuffieh, nomad cowls and such. They require no maintenance.
**Tier 2** will have simple mechanical filters - dust masks, water-soaked rags, filter masks. They will provide meager environmental protection, but are cheap as you can easily "renew" them by washing the filtration medium or crafting a new one.
**Tier 3** is the chemical filters like gas masks. They give good enough defence and their "ammunition" is plentiful and craftable (high enough skills provided).
**Tier 4** will see addition of powered air-purifying respirators (PARPs). They will provide borderline immunity to the most contaminants barring the strongest ones and will use the same filters as the gas masks. This is offset by being noisy and requiring batteries to function.
**Tier 5** is self-contained breathing apparatuses (SCBAs) like the PBA mask in this commit. They give complete immunity to outside contaminants and are low on encumberment (while active). They, however, are pretty cumbersome and the cylinders last for a limited time before requiring a reload.
**Tier 6** is power armor that probably uses some kind of sci-fi chemical process.

### CODE REVIEW

**Comment by Vasyan2006** [comment]
Looks like nitrox can be consumed only if the tank is inside a harness? Considering survival situation wearing a special harness is not always possible. It will be better to use nitrox charges from any air tank in characters inventory.

**Comment by Maskrow** [comment]
@Vasyan2006
The idea is that the harness items will be including the manometer and all the hoses/counterlungs required for the functioning of the mask. 
As for the gameplay standpoint, the requirement to wear a harness is a downside specific to that tier of breathing equipment. The idea behind that tier is that it is used to venture into the areas with the most dangerous environmental hazards, while in daily survival the simple gas mask will probably suffice.
Later I will also add some other harness types such as diving harness with a semi-closed circuit, military harness with a closed circuit, makeshift harness and, of course, an armored survivor harness merged with a backpack (for maximum efficiency).

**Comment by Vasyan2006** [comment]
I want to point out that harness by itself is a part of clothing. Manometer and all the hoses/counterlungs are most important items. If you will add more harnesses in the future it will require to add them to the code, so modding will be more difficult. Maybe add new item with flag "manometer_and_all_the_hoses" (sounds like a name of the band), load it with air tanks and check if it has nitrox charges. In this case all harnesses wil work like a holster.

**Comment by Maskrow** [comment]
Ah, I catch your drift now. Will be closing the PR once again for now.

**Pull request closed without merging**
