### PR TITLE
[CR] [WIP] Saw off Stock

### PR DESCRIPTION
**Pull request by hyper2snyper**
```SUMMARY: Content "Adds the ability to saw stocks off guns"```

#### Purpose of change
 related #26969
#### Describe the solution
makes the wood saw able to saw of stocks of guns.

### CODE REVIEW

**Comment by sneeze-attack** [comment]
@hyper2snyper 
Line 203 typo:
"type": "item_actiom",

**Comment by hyper2snyper** [comment]
> @hyper2snyper
> Line 203 typo:
> "type": "item_actiom",

that was quick, thanks

**Comment by SirPendrak** [comment]
Pardon me if I am wrong, but sats you proposed seem weird. Handling modifier 1 will reduce recoil instead of increasing it dramatically (probably -6 or -8 would be suitable). 
I dont know exactly what aiming modifier does, but if proposed -20 is to increase aiming speed, just decreased volume of weapon will increase aiming speed. 
I believe -8 handling and -5 dispersion modifier would be prefferable, but thats just me, aregular player with no programming experience.

**Comment by hyper2snyper** [comment]
> Pardon me if I am wrong, but sats you proposed seem weird. Handling modifier 1 will reduce recoil instead of increasing it dramatically (probably -6 or -8 would be suitable).
> I dont know exactly what aiming modifier does, but if proposed -20 is to increase aiming speed, just decreased volume of weapon will increase aiming speed.
> I believe -8 handling and -5 dispersion modifier would be prefferable, but thats just me, a regular player with no programming experience.

Right, thanks for the feedback

**Comment by Xhuis** [comment]
When are we gonna get shotguns that are just a trigger and 2 inches of barrel? Its effective range is one tile.

**Comment by hyper2snyper** [comment]
> When are we gonna get shotguns that are just a trigger and 2 inches of barrel? Its effective range is one tile.

soon, im trying to figure this out

**Comment by ZhilkinSerg** [comment]
Marking as stalled. Please ping me to reopen when you are ready to pick up where you left.

**Pull request closed without merging**
