### PR TITLE
Use `id` instead of `ident` for identifier member names in JSON

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Fix inconsistencies in identifier member names in JSON.

#### Describe the solution

Use `id` instead of `ident` for identifier member names in JSON while keeping temporary support for legacy `ident` member name.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm fine with fixing this inconsistency, but we need to accept ident for these for a little while at least to give mods the chance to catch up, shouldn't be too hard?

**Comment by ZhilkinSerg** [comment]
> 
> 
> I'm fine with fixing this inconsistency, but we need to accept ident for these for a little while at least to give mods the chance to catch up, shouldn't be too hard?

Yeah, it is pretty easy. Both `ident` and `id` would be supported now. I've left FIXME comments near places of `ident` usage. Shall we add some user/log output too when we find `ident` instead of `id`?

**Comment by jbytheway** [comment]
> Yeah, it is pretty easy. Both `ident` and `id` would be supported now. I've left FIXME comments near places of `ident` usage.

Suggest it be `TEMPORARY until 0.G` rather than `FIXME`.

> Shall we add some user/log output too when we find `ident` instead of `id`?

Seems like a good idea.  Would probably have to be a `debugmsg` if you want anyone to notice.

(I'm starting to wonder whether we need to have a global option for mod developers to turn on more warnings that regular players shouldn't be concerned with).

**Comment by ZhilkinSerg** [comment]
Temporary closing this one. I will need to change some other things in generic_factory first.

**Comment by kevingranade** [comment]
Test failure.
```
+'[' -n 1 ']'
+blacklist=build-scripts/mod_test_blacklist
++./build-scripts/get_all_mods.py build-scripts/mod_test_blacklist
Traceback (most recent call last):
  File "./build-scripts/get_all_mods.py", line 29, in <module>
    ident = e["ident"]
KeyError: 'ident'
+mods=
```

**Comment by ZhilkinSerg** [comment]
Should be fixed now.

**Pull request merged**
