### PR TITLE
[Aftershock] Modify flatbread recipe

### LINKED ISSUE #35800: Flatbread has 9x more calories than player crafted flatbread.
# Describe the bug
Crafted flatbread yields far too little calories.
 
# Steps To Reproduce
1. Debug spawn some wheat & water.
2. Craft dough.
3. Using dough craft flatbread.
4. Notice the pitiful amount of calories it contains. 

# Expected behavior

Crafted flatbread to have more or less similar caloric value to normal flatbread.

# Screenshots

Crafted flatbread on the left, flatbread I debug spawned on the right.
Crafted flatbread has exactly 9 times less calories than normal flatbread.
image

# Versions and configuration
- OS: Windows
- OS Version: 10.0 1903
- Game Version: 0.D-9376-gb17746f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mundane Zombies [Mundane_Zombies],
    No Acid Zombies [No_Acid_Zombies],
    No Ants [No_Anthills],
    No Bees [No_Bees],
    No Monsters [Only_Wildlife],
    No Fungal Monsters [No_Fungi],
    No Big Zombies [No_Big_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Spiders [No_Spiders],
    Whitelist [Whitelist],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

Probably somethings to do with crafted food inheriting their caloric value from their ingredients. Probably other examples out there.  
Crafting flatbread directly out of flour, without using dough seems to yield expected amount of calories.

### PR DESCRIPTION
**Pull request by arijust**
#### Summary

```SUMMARY: Mods "Modify flatbread recipe in Aftershock"```
#### Purpose of change

Close #35800
#### Describe the solution

Change amount of charges to 2. 
It makes crafted flatbread have the same amount of calories as normal one.
Except for one extra portion for crafted one.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Why does aftershock have a recipe for bread and flatbread in it? What's scify about bread?

**Comment by arijust** [comment]
>Why does aftershock have a recipe for bread and flatbread in it? 

I don't know. It isn't bad idea to mainline that, I guess.

>What's sci-fi about bread?

Means of its production for paleolithic age?

**Comment by Maleclypse** [comment]
Dough could also be mainlined from Aftershock.

**Comment by DaviBones** [comment]
I don't understand what dough adds to the game. There is no reason for a differentiation of two separate processes (from dough and from flour) for bread-making, as such a differentiation doesn't exist in real life. So if we added `bread from dough` into mainline, it would have to *replace* `bread from flour` since `bread from flour` implicitly includes dough as an intermediate product.

I don't see what that replacement adds, besides more unnecessary fiddling with the UI; why would someone ever want to craft dough, but not craft anything *from* said dough?

**Comment by Maleclypse** [comment]
> I don't understand what dough adds to the game. There is no reason for a differentiation of two separate processes (from dough and from flour) for bread-making, as such a differentiation doesn't exist in real life. So if we added `bread from dough` into mainline, it would have to _replace_ `bread from flour` since `bread from flour` implicitly includes dough as an intermediate product.
> 
> I don't see what that replacement adds, besides more unnecessary fiddling with the UI; why would someone ever want to craft dough, but not craft anything _from_ said dough?

I'm more stating that I'd like to see things that can be mainlined, out of Aftershock.  I'm not pro dough or anti dough.  But I definitely would prefer flatbread be mainlined rather than in Aftershock.

**Comment by DaviBones** [comment]
> I definitely would prefer flatbread be mainlined rather than in Aftershock

Flatbread is not in Aftershock, it's part of the base game. The only thing regarding flatbread that Aftershock adds is an additional recipe for flatbread that uses dough instead of flour, so dough is central to this discussion.

I totally agree that Aftershock should have a defined direction and not be adding weird food recipes. But I also don't think the dough recipes fit in the base game. And simultaneously, I don't really use/maintain Aftershock personally, so I don't really feel qualified to say we should remove dough and all related recipes from it.

**Comment by Maleclypse** [comment]
> I totally agree that Aftershock should have a defined direction and not be adding weird food recipes. But I also don't think the dough recipes fit in the base game. And simultaneously, I don't really use/maintain Aftershock personally, so I don't really feel qualified to say we should remove dough and all related recipes from it.

I'll try and examine dough in Aftershock more closely this winter, since I've currently volunteered to maintain it. I haven't spent enough time with Aftershock yet to really feel good about making decisions to remove things the mod creator put in completely.  
@arijust thank you for putting this fix together.

**Comment by arijust** [comment]
>thank you for putting this fix together

You're welcome.

**Pull request merged**
