### PR TITLE
Add myself to /confirm permissions list

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
None

#### Purpose of change
This is just how the github module works

#### Describe the solution
I put my name right there, at the bottom of the list

#### Describe alternatives you've considered
I thought the starship troopers reference was pretty good

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by TheShadowFerret** [comment]
*Me who didn't even realize I was on this list*

**Comment by casswedson** [comment]
You sir have no excuse, I @'d you in the pr introducing this https://github.com/CleverRaven/Cataclysm-DDA/pull/57072#issuecomment-1108000348

**Comment by TheShadowFerret** [comment]
> You sir have no excuse, I @'d you in the pr introducing this

>Implying I read my email for notifications

Wrong! :3

**Comment by nopenoperson** [comment]
can i join the mobile infantry today?

**Pull request merged**
