### PR TITLE
Changed empty wall list on gates to match all walls

### LINKED ISSUE #73879: Why can't I open the garage door?
### Describe the bug

This one is very similar:
- #72965
- #67285

The difference is that it doesn't open.

I haven't found any patterns. Some doors open, others don't. In the main world, I have a neighborhood in which not a single garage door opens.

Is this a bug or am I not meeting some conditions? Like it was with wooden doors and electronic locks.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15349273/test-trimmed.tar.gz)

### Steps to reproduce

Create a world and go open garage doors.

### Expected behavior

That I can open any garage door or get an explanation as to why I can't open it. More detailed than “nothing happened.”

### Screenshots

pict

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-16-0649 d435fb1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #73879, i.e. inability of gate controls to control gates if the palette has selected a non approved wall.

#### Describe the solution
- Change the gate control logic from listing every kind of wall permitted beside a gate control for it to work, treat an empty list as compatible with all walls (everything having the "WALL" flag), while a populated list restricts the set to those listed. The two types of controls that seem to be intended to be general had their wall lists emptied.
- Update the listed set of walls working with barn door controls to work with all current colors of the wood wall.

#### Describe alternatives you've considered
Continue the whack-a-mole game of trying to update a very long list (it would be if updated to work properly) with new entries as new walls and wall colors are created. It can also be noted that the developers actually whacking said moles are few and far between.

#### Testing
Teleported to a city and operated garage doors. transmuted walls back to wood and verified they still worked. Also tried a couple of other versions, like some nether glass thing.
Haven't actually tested the updated barn door, but assumes loading the game would complain if I've gotten any of the new colored walls wrong.

### CODE REVIEW

**Comment by Maleclypse** [comment]
How does it know to only affect the walls in one direction then?   Like if I had a gate button at a three way corner/intersection of walls but they were different types of walls two brick one metal how does it know I only want the metal?  I’m not at my computer so I might be missing something.

**Comment by PatrikLundell** [comment]
You don't. I think the logic searches for a matching wall in the cardinal directions (the code I changed only affects the "is there a matching wall at this coordinate?" logic, not the one deciding on the coordinates to query.). I also don't know what it does when a control has the same kind of wall with gates to their sides in two directions. I'd guess it probably opens the first one found according whatever search order it uses, but it might affect both of them.
Heck, what about the case where you place a control by  central wall with gates to either side (such double gates typically have their controls at the further ends in the game, as I think the fire station has such a setup)?

However, to pull off a "different controls for different directions" implementation you'd have to carefully select the walls to match either the somewhat general case or the narrower barn door case. Thus, the answer really is to don't try to do overly smart things the logic can't deal with.

What I'm arguing here is that it's better to have the controls be general and more usable than narrowly specific with arbitrary wall selection gaps in them.

You may have a different opinion, of course.

**Comment by Maleclypse** [comment]
> You don't. I think the logic searches for a matching wall in the cardinal directions (the code I changed only affects the "is there a matching wall at this coordinate?" logic, not the one deciding on the coordinates to query.). I also don't know what it does when a control has the same kind of wall with gates to their sides in two directions. I'd guess it probably opens the first one found according whatever search order it uses, but it might affect both of them. Heck, what about the case where you place a control by central wall with gates to either side (such double gates typically have their controls at the further ends in the game, as I think the fire station has such a setup)?
> 
> However, to pull off a "different controls for different directions" implementation you'd have to carefully select the walls to match either the somewhat general case or the narrower barn door case. Thus, the answer really is to don't try to do overly smart things the logic can't deal with.
> 
> What I'm arguing here is that it's better to have the controls be general and more usable than narrowly specific with arbitrary wall selection gaps in them.
> 
> You may have a different opinion, of course.

I’ll try and test it out and see if I can find anything already existing it breaks once I have some computer time.

**Comment by Maleclypse** [comment]
witchcraft

Welp it looks like witchcraft to me as to why it works but it definitely does work.  Thanks for doing this!

**Pull request merged**
