### PR TITLE
[CR] [WIP] Add force_refresh()

### PR DESCRIPTION
**Pull request by drbig**
In an attempt to fix the real underlying issue of e.g. #12957 or #12797 (and probably many more) I came up with this. It works just fine on Linux for both tiles and curses builds, but I'd rather have it tested on Windows and perhaps OS X first.

I have a [patch fixing](http://ix.io/jMy) #12957 that uses this and I also used it for testing.

So if this is ok and doesn't blow anything up I could go on and fix at least the two mentioned issues.

And lastly: yeah it doesn't touch the _real_ real underlying issue - whatever it is, but is still better than black boxes, no boxes or weird UI just to hide black boxes.

### CODE REVIEW

**Comment by drbig** [comment]
Found another related: #12128

**Comment by karlnp** [comment]
The windows implementation of catacurses.h is bad, because it uses Very Legacy APIs, so I'm in the middle of porting to libtcod as a SDL wrapper, which should fix most of these. This seems like a good patch in the meantime, though.

**Comment by drbig** [comment]
Aye. It definitely should work on everything that has real ncrurses. It did work with tiles on Linux in my case, so I'd assume it *should* work at least on Unix-likes. And adding platform `#ifdef`s is always an option too (albeit one I would prefer to avoid).

**Comment by BevapDin** [comment]
Why do you actually need this force redraw thing in to solve the trap interaction bug? Your patch fixes #12957 just fine without the forced refresh.

**Comment by karlnp** [comment]
Didn't build on windows due to undefined curscr. At least for wincurses/catacurse, including catacurse.h and changing the reference to mainwin works. https://github.com/karlnp/Cataclysm-DDA/commit/472d5ccb08da3ea02d3f243d09ca471611d8caf1

```
[14:05] <karlnp> dRbiG: speed increase in gneral, saving/loading is quicker, but the pause at the end of sleeping is still there (likely map recalculations/monster sight tracking)
```

**Comment by drbig** [comment]
@BevapDin it does leave a 'black box' without the forced refresh here, both in tiles and ncurses,

**Comment by BevapDin** [comment]
> it does leave a 'black box' without the forced refresh here, both in tiles and ncurses,

It does not with the patch applied, but the patch does not work anyway, see my edit comment.

**Comment by drbig** [comment]
@BevapDin you're edit is related to the iexamine trap fix, and I think I see it (there's a check earlier that checks position).

What I'd like to concentrate here is the forced refresh. I can patch test it against #12797. But @karlnp already reported `curscr` doesn't work with our 'wincurses'.

**Comment by drbig** [comment]
Indeed doesn't seem to work for  #12797 now. Very much `[WIP]` then.

**Comment by drbig** [comment]
So I'll close this one; try to find at least one case at current where it helps (e.g. removes a black box(es) in tiles), and if so PR it anew as a thing that "won't hurt to have".

**Pull request closed without merging**
