### PR TITLE
Mainline most of CraftGunpowder mod content

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Mainline most of CraftGunpowder mod content"```
#### Purpose of change

This PR updates and mainlines most content from CraftGunpowder mod that I think would make sense to have in mainline. This includes:
1. More craftable single-shot pipe rifles of different calibers and their recipes. They're probably not any more difficult to make than single-shot pipe rifles in mainline.
2. More makeshift magazines. They have been changed to double as makeshift magazines for some factory-made guns, as well as fit mod's makeshift SMGs, to partially mitigate "found guns but not mags" problem. They are also now contained in some item groups. Also it does seem quite possible to make a firearm which uses a factory-made magazine.
3. Makeshift SMGs (but not their recipes yet). Right now, they can sometimes be found as part of new makeshift SMGs item group. Recipes were left in the mod for now, until proper tools to craft these are implemented, and related comments were added to their item entries. Their description was rewritten to state that they're Luty pattern SMGs. 9mm SMG was changed to use makeshift 9mm magazine which already exists in mainline, to avoid magazine bloat while possible. SMG stats got changed a bit as well.
#### Describe the solution

JSON editing.
#### Describe alternatives you've considered

Moving guns one-by-one in separate PRs, but this would probably take a lot of time. Easier to just decide at once what mod content should be mainlined and what shouldn't, I'll revert it if it ends up not making sense.
Adding actual SMG recipes as well, but considering the necessity of adding lots of new tools for use by those new recipes, this would make this PR way too large.
Also more of a question here, but would it make sense to create automatic (smoothbore) rifles in a similar way? Seems like they could be decent expansion for makeshift armory, if possible to craft (or if not, just put them into this mod). 
#### Additional context

Content remaining in mod includes recipes for: STEN, makeshift SMGs, caseless ammo, smokeless gunpowder, red dot sight, rifle scope, pistol scope.
Related issue for craftable SMGs: #22688 (not really resolved by this PR since there are still no recipes yet, but is a step towards that)

### CODE REVIEW

**Comment by Mecares** [comment]
Might be better to move it to the Craftable Guns Mod than to mainline. I am a bit sceptical especially regarding makeshift smgs are there cases where it was done in real life with the tools and materials  that are available ingame?

**Comment by kevingranade** [comment]
Pipe guns are fine, just need to make sure they don't pretend to be rifled.
Magazines are doable, but need to be extrordinarally unreliable.
SMGs are also fine assuming they have appropriate (bad) stats.

**Comment by Rail-Runner** [comment]
> Magazines are doable, but need to be extrordinarally unreliable.

Would reliability of 5 be low enough?

**Comment by kevingranade** [comment]
> Would reliability of 5 be low enough? That's what they have currently.

I need to double-check what that number means right now, but if it hasn't changed, it should either be 1 or 2.

**Comment by Rail-Runner** [comment]
Done, all existing makeshift magazines now have a reliability of 1. Seems a little too much of a nerf for me, but whatever. I don't really know how reliable makeshift guns and magazines can be anyway.

**Comment by kevingranade** [comment]
Sorry no that's just an observation, I can add an issue for it and it can be added in due time

**Pull request merged**
