### PR TITLE
Fix Fingerhack

### LINKED ISSUE #50289: Electronic Gun Safe cannot be hacked
### Describe the bug

When trying to hack into an electronic gun safe using either an active Fingerhack CBM or an electrohack, receive the message "You don't have a hacking tool with enough charges!"

### Steps To Reproduce

1.  Load save [Pickett.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6896806/Pickett.zip)
2. Attempt to hack nearby safe

### Expected behavior

Able to use either the CBM or the electrohack to attempt hacking into the safe

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary
Bugfixes "Give fake item generated by bionics the USES_BIONIC_POWER tag"

#### Purpose of change

Fixes #50289

#### Describe the solution

In `Character::charges_of()`, the fake item generated by bionics has the same id as the real item ( activated Fingerhack generates electrohack which does not use bionic energy by default ). 
~~Manually set the USES_BIONIC_POWER tag for that fake item so that the bionic energy is counted for checking remaining charges.~~

New approach: just return bionic power level, since this fake item shouldn't be able to use any other energy sources. :joy_cat:
#### Testing

The player is able to hack electro gun safe using Fingerhack

#### Additional context

`Character::use_charges()` worked as intended for bionics, no need to modify.

### CODE REVIEW

**Comment by Hirmuolio** [comment]
I think it would be better to make a separate fingerhack fake item that has the appropriate json flag. I don't like json functionality being overrided in c++.

**Comment by Menschheit** [comment]
My thought was if I make a new fake item then all the related codes contain ` itype_electrohack` are to be adjusted (not so many though, there are two from `iexamine::try_start_hacking`, the others are from `hack_attempt`). Either to make some other codes for the fake item too which essentially do the same thing, or find all items with a new flag indicates the ability to hack, like `Character::find_firestarter_with_charges` and `Character::use_fire` using the flag FIRESTARTER, I'm thinking about it.

Or even generalize all similiar bahavior? like` Character::find_tag_with_charges( tag, qty)`? But that would be beyond my ability, since I am a player not a developer so I tend to do local changes to fix things instead of reconstructing the codes globally.

**Comment by Hirmuolio** [comment]
If `Character::all_items_with_flag()` also returned fake items things would be much simpler. But it turns out it can't because pointers don't work on them.

Though there is `Character::get_pseudo_items()` that should simplify some cases since you don't need write the looping through of all bionics.

**Comment by GoLoT** [comment]
> If `Character::all_items_with_flag()` also returned fake items things would be much simpler. But it turns out it can't because pointers don't work on them.
> 
> Though there is `Character::get_pseudo_items()` that should simplify some cases since you don't need write the looping through of all bionics.

I implemented a cache of pseudo_items in #50347 and it became a generic solution for all CBM tools after dealing with the ammo code for USES_BIONIC_POWER, fixing #50289 in the process.

**Pull request closed without merging**
