### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by Cyrano7**
#### Summary

```SUMMARY: I18N "Fix some minor spacing and typos"```

### CODE REVIEW

**Comment by MetroidHunter** [comment]
It looks like you added double spaces between sentences in some descriptions. Was that intentional?

**Comment by KorGgenT** [comment]
you have an invalid summary line.
also, i am wondering if you ran these files through the web linter? if so, i think some of these files are in ```json_blacklist``` and could stand to be removed from that file

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Pull request merged**
