### PR TITLE
Make hard-hat based helmets adhere to a singular logic

### PR DESCRIPTION
**Pull request by jcd000**
This should make the hard hat derivatives adhere to one standard.
As of now we got:

Hard hat: 
- Vol=10
- Weight=796
- Encumbrance=15
- Cut,Bash Protection = 12,12
- Warmth = 5

Hooded hard hat:
- Vol=10
- Weight=838
- Encumbrance=13
- Cut,Bash Protection = 11,11
- Warmth = 4

Miner Helmet:
- Vol=10
- Weight=796
- Encumbrance=10
- Cut,Bash Protection = 12,12
- Warmth = 5

And after this the stats should be (taking into account the added rag & flashlight, plus removing the 'cotton' mat from the hooded hat & making it thinner):
Hooded hard hat:
- Vol=11
- Weight=876
- Encumbrance=13
- Cut,Bash Protection = 12,12
- Warmth = 6

Miner Helmet:
- Vol=12
- Weight=1196
- Encumbrance=15
- Cut,Bash Protection = 12,12
- Warmth = 5

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Honestly I'd just obsolete the hooded hard hat. It isn't a well thought out item. A cotton hood on the back of a hard hat won't make it resist rain well and any other change (+5 warmth or -5 encumbrance) won't be noticeable in any way. As it stands, hooded hard hat is useful for one thing: removing damage from a hard hat (because the newly crafted item spawns at 0 damage).

Miner helmet could be turned into actual miner helmet rather than hard hat + flashlight taped on it. Thus made uncraftable (or harder to craft). We already have head torch, which handles the miner helmet's role.

**Comment by kd8qdz** [comment]
"Hooded" hardhats are a thing.  but they are not used to keep you dry (hard hats are plastic, they already do that)  but to keep you from freezing.   A hooded hardhat should have a nicer warmth than 6.

**Comment by jcd000** [comment]
If you want to add just one rag to it, it cannot be too warm. I'd say that lining the helmet should handle that.

@Coolthulhu, i cannot disagree with your logic. Head encumbrance of +/- 2 is not that important anyway, while both hats are waterproof already.

I can delete the hooded one and make a new miner's.
How  does this sound:


Miner Helmet:

    {
        "id": "miner_hat",
        "type": "TOOL_ARMOR",
        "category" : "armor",
        "symbol": "[",
        "color": "yellow",
        "name": "mining helmet",
        "description": "This is a mining helmet with a heavy duty LED flashlight.  Using this will turn the flashlight on and provide light, assuming it is charged with batteries.",
        "flags": [ "WATERPROOF" ],
        "price": 12500,
        "material": [ "plastic" ],
        "weight" : 1400,
        "volume": 15,
        "bashing": 6,
        "max_charges": 400,
        "initial_charges": 100,
        "charges_per_use": 1,
        "ammo": "battery",
        "use_action": {
            "type": "transform",
            "msg": "You turn the helmet on.",
            "target": "miner_hat_on",
            "active": true,
            "need_charges": 1,
            "need_charges_msg": "The helmet's batteries are dead."
        },
        "covers" : ["HEAD"],
        "techniques" : ["WBLOCK_1"],
        "warmth" : 5,
        "encumbrance" : 15,
        "coverage" : 80,
        "material_thickness" : 5
    }

Mostly i made it slightly thicker, heavier and with a larger max charge.

**Comment by Coolthulhu** [comment]
400 max charges is a lot, the light on the helmet is unlikely to have a battery compartment holding this much. 200 should be fine.

It could also get the flashlight stats of a heavy duty flashlight (more power but more consumption) to make it differ from hooded hat + head torch.

**Comment by Mshock777** [comment]
Instead of hooded hard hat I would rather see more interesting examples: hard hat with face shield, hard hat with welding mask, hard hat with different protective (kevlar?) hoods.

**Comment by jcd000** [comment]
Not that easy to modify a hard hat i guess.

But if it were me, i'd either put a real hat over it to shield myself from the sun, or some kind of hood to increase its warmth (depending on the season)

Increasing its coverage is what i'd also like to do, but i don't see a good IRL way for it.

**Comment by kd8qdz** [comment]
hearing protection is a common addon to hard hats as well

**Pull request merged**
