### PR TITLE
Korean .po update

### PR DESCRIPTION
**Pull request by ghost**
Newly updated ko.po

### CODE REVIEW

**Comment by fenjo** [comment]
first time using github.
anything done wrong, let me know.
Thanks.

**Comment by VlasovVitaly** [comment]
You need to push to ```lang/po/ko.po```
```lang/incoming``` is special dir for developers when they need to bulk updates of all languages.

This translation is synchronized with launchpad https://translations.launchpad.net/cdda/trunk/+translations? If so, then you need to change file to ```lang/po/ko.po```. If not, this is not acceptable.

**Comment by fenjo** [comment]
Yes I export this translation from that trunk 3days ago.
well. i will revert mself

**Comment by VlasovVitaly** [comment]
One more thing.
When you import from launchpad it add lot of comments at end of file. You
must remove them.
27.08.2015 5:18 пользователь "fenjo" <notifications@github.com> написал:

**Pull request merged**
