### PR TITLE
Added Taurus Raging Judge Magnum [realguns]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Just a rename for now.

EDIT: increased the weight of the Raging Judge as well. This PR will only affect the realguns mod.

### CODE REVIEW

**Comment by kevingranade** [comment]
What's the reason for the change?  AFAICT the Raging Judge is a variant of the Raging Bull, so redefining it doesn't make sense.

**Comment by BorkBorkGoesTheCode** [comment]
The Raging Bull appears to be .454 Casull only. The Raging Judge Magnum has the ability to fire .454 as well as .410 and .45 Long Colt, which this mod allows.

**Comment by kevingranade** [comment]
Unless I'm missing something, it isn't doing that.  Leave the rename for when the definition is actually changed.

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade The definition is already changed at the ammo level using the multiple ammotype system added by mugling.

**Comment by BorkBorkGoesTheCode** [comment]
I've decided against overwriting the Raging Bull. I'm going to add the Raging Judge as a separate item.

**Pull request merged**
