### PR TITLE
Remove the legacy folder for good since it's useless

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
None

#### Purpose of change

Remove the legacy folder for good since it's useless

#### Describe alternatives you've considered

Delete the folder and commit

### CODE REVIEW

**Comment by Salty-Panda** [comment]
Out of curiosity, may I ask what was its purpose and how was it different than `obsolete.json`?

**Comment by kevingranade** [comment]
So just to clarify, this is a structured migration/obsoletion feature we haven't used since 2017 or so.  The idea was that any time you obsolete something you stick it in a new numbered directory, and then as the older directories age enough, you delete them.  Clearly that didn't go according to plan since the earliest ones were added in January of 2017 and have never been deleted.

The only meaningful difference compared to the unstructured mechanism we use now is that this would hypothetically allow migrations and such to be applied just once and then the save version could be consulted to skip older migrations, but that's not actually a meaningfully consistent system since we never systematically load all world save data for migration, and once we decide to "move past" a particular chunk of migration data, we can just delete it instead of configuring the system to ignore it but still ship it.  I'll follow up with a PR to remove the code side of the feature as well as no one is using it.

**Comment by ZhilkinSerg** [comment]
```
  File "lang/extract_json_strings.py", line 1467, in <module>
    extract_all_from_dir(i)
  File "lang/extract_json_strings.py", line 1378, in extract_all_from_dir
    allfiles = os.listdir(json_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'data/legacy'
Error in extract_json_strings.py. Aborting
```

https://github.com/CleverRaven/Cataclysm-DDA/blob/56c78d6bdbc12c7a4345f2c1565ca2341305b4b9/lang/extract_json_strings.py#L1013

**Comment by actual-nh** [comment]
Ping: @BrettDong?

**Pull request merged**
