### PR TITLE
Don't strip positional arguments when unlocalized

### PR DESCRIPTION
**Pull request by davidapgar**
This is to fix some crashes with messages when running a build that wasn't localized.

The easiest reproduction for this is to have an NPC in the game, being attacked repeatedly (eventually their armor will block a hit, resulting in the crash).

The most common one that I encountered was from:
https://github.com/CleverRaven/Cataclysm-DDA/blob/64e98cba21385806f7b8139a800f6c64ad550fbd/src/monster.cpp#L828

(since positional argument 2 is used twice, when stripped, it would cause printf to try and reference the 5th argument, which doesn't exist).

I replaced the positional stripping with an effectively empty macro that just leaves the string as is. I did validate that using positional parameters with gettext appears to work correctly.

### CODE REVIEW

**Comment by vache** [comment]
This is controlled through conditional compile items.  This looks like it will completely break all translations.

**Comment by kevingranade** [comment]
I'm pretty sure the reason this is here is because some libraries don't handle positional arguments to printf and friends, so on those systems it will break unlocalized builds.  Did you honestly think that huge chunk of code was there for no reason?

**Comment by KA101** [comment]
OK, I'm thinking the correct solution is to fix the messages if they're breaking, not the handler.  Those can be handled in another PR.

Closing with leave to reopen if there's some reason to do so.

**Comment by davidapgar** [comment]
Makes sense. Part of what lead me to this was the number of strings I saw in the source code that were relying on position parameters already, and seemed to work cleanly when localized.

It looks to me that the positional parameters are more of a localizing hint (since the result after they are run through msgfmt for gettext keeps them in there).

I'll open a different PR with fixes for the messages that are resulting in crashes on an unlocalized build.

**Comment by kevingranade** [comment]
The positional parameters allow translators to shuffle around the locations of the inserted elements when translating the string.
e.g.
```printf( _("You $1%s the $2%s"), _("eat), _("cheese") );```
becomes
```printf( "Anata wa $2%s o $1%s", "taberu", "chīzu" );```

**Pull request closed without merging**
