### PR TITLE
Misc debug stuff

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Few debug things that i made for my stuff
#### Describe the solution
Debug mutations for HP and HP regen, because high str mess this too much, and spell to kill any creature

### CODE REVIEW

**Comment by PatrikLundell** [comment]
What's wrong with the current debug means to kill off creatures? Wouldn't it be better to fix those if there's something wrong with them than introducing a new one?

**Comment by GuardianDll** [comment]
It doesn't count as player kill, and i found impossible to obtain lot of experience because of this. Now i can just cast this spell to kill a person, and take a lot of xp instantly

**Comment by PatrikLundell** [comment]
If you just want to get a lot of XP and kills and if there aren't useful means to do so, it would be better to create debug commands that allowed you to to gain XP and kills respectively, without creating an additional kill command with side effects. Test purposes usually benefit from as pure debug commands as possible.

**Comment by GuardianDll** [comment]
Great idea, except i have no clue how to make it from code side

**Comment by bombasticSlacks** [comment]
I think these are fine, you have to go looking for them 👍

**Pull request merged**
