### PR TITLE
[Magiclysm] Partially bugfix spellcasting proficiencies

### PR DESCRIPTION
**Pull request by rty275**
#### Summary
Mods "Fixes spellcasting proficiencies adding when they should be subtracting"

#### Purpose of change
I noticed doing another PR that Apprentice and Master level proficiencies were doing the opposite of what they should have done in the specific case of being used as cost/time reductions.

#### Describe the solution
Change some + to -.

#### Describe alternatives you've considered
Letting the proficiencies keep working against you?

#### Testing
Checked both before and after, spells were properly adjusted by the math after the fix.

#### Additional context
During testing, I also noticed that Channeling proficiencies had a significantly lesser impact than other proficiencies had? Or maybe Evocation is just that powerful since it's working with smaller numbers. Dunno, but it's maybe worth looking into by someone who understands the math better than I do.

Edit: This does NOT deal with #72428, that's outside my level of coding ability to handle.

### CODE REVIEW

**Comment by Cadvin** [comment]
Regarding the additional context: it seems to be because the bonuses from the proficiencies are operating via addition. With Novice Evocation, an evocation spell gets a +10 to its base damage, its maximum damage, and probably most impactfully, its damage increment per level (meaning most evocation spells hit damage cap quickly).
Channeling spells, meanwhile, get a -10 to the moves it takes to cast them, or enhancement spells a +10 to their duration in moves, which doesn't end up being much when these measure in the thousands or tens of thousands.

It should probably add a multiplier of the values instead (plus or minus 0.3, or something similar). I'd be happy to do a PR for this as my first contribution but I'll need to figure out how to work git properly first.

**Comment by rty275** [comment]
That makes a lot of sense. It's mostly notable on the spells with either very low baseline numbers or very high ones. Magic Missile doing twice its base damage is cool, but perhaps more than being an expert at the spell would mean? Or maybe that is intended, I'm not sure, I wasn't the one who designed the proficiency system. And for spells with high numbers, the proficiencies are not very helpful because they're only removing a dozen or two seconds from an hour long spell. I have absolutely no idea how one would fix this, that kind of math and specifically coding is above me, but it is something I've noticed recently. I really like the proficiency system overall though, it *feels* more like learning how to wizard than reading spellbooks does.

**Comment by MNG-cataclysm** [comment]
> That makes a lot of sense. It's mostly notable on the spells with either very low baseline numbers or very high ones. Magic Missile doing twice its base damage is cool, but perhaps more than being an expert at the spell would mean? Or maybe that is intended, I'm not sure, I wasn't the one who designed the proficiency system. And for spells with high numbers, the proficiencies are not very helpful because they're only removing a dozen or two seconds from an hour long spell. I have absolutely no idea how one would fix this, that kind of math and specifically coding is above me, but it is something I've noticed recently. I really like the proficiency system overall though, it *feels* more like learning how to wizard than reading spellbooks does. 

I think the earlier-suggested idea of a multiplier would be the best fix, as it allows for scale on spells. I also did not realize just how powerful the per-level damage addition would be, so that should probably have a scale of 0.1 or something similar.

**Comment by rty275** [comment]
Multiplier makes sense, and .1 per tier of proficiency makes sense. I suppose in theory the most flexible solution would be to be able to set how effective the proficiencies are in the actual spell itself rather than as a universal constant, but that sounds like vastly overcomplicating things for very very little actual benefit.

**Pull request merged**
