### PR TITLE
Baseball bats love

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Balance "Adds missing techs and flags to the baseball bats"

#### Purpose of change
The baseball bats are a good early weapon... Somewhat, they lack techniques and they are not usable by any martial art, they can't even be strapped to your belt like the cudgel, so carrying them becomes more difficult than other similar weapons.

#### Describe the solution
Adds the "BRUTAL" technique to the bats (except the foam rubber bat), and the "BELT_CLIP" and "NONCONDUCTIVE" flags (because of their typical plastic handle/wrapping) to all of them. The rationale with brutal is, well... These are baseball bats, they can hit hard and drive an enemy away if you make a strong hit (home run!), other bashing weapons with similar stats have this tech too, so it was a little unfair to leave the baseball bat without it.

#### Describe alternatives you've considered
To add them to a weapon category, but they do not exactly fit with the idea of a "baton" or a "quarterstaff", and they are too short to be considered polearms.
To add to them another tech, like precise strike, maybe quick, but I think BRUTAL is a pretty fair option for this kind of weapon.

#### Testing
Applied the changes to my game, tried to make a home run out of a zombie, it works! And the items have their flags/techs applied as well.

#### Additional context
imagen
It works!

### CODE REVIEW

**Comment by catdach** [comment]
Should the aluminum bat be nonconductive? Seems a little strange.

**Comment by Termineitor244** [comment]
> Should the aluminum bat be nonconductive? Seems a little strange.

I'm mostly going for the "plastic handle = you will not suffer from electricity damage through it" approach, since many other metal weapons seem to follow that rationale (And it makes sense, at least for me).

**Comment by TheShadowFerret** [comment]
> To add them to a weapon category, but they do not exactly fit with the idea of a "baton" or a "quarterstaff", and they are too short to be considered polearms.

Maces? Also end-heavy and most maces are 80cm compared to BB's 90(and bats can obv. vary in length, but we only got one size 😛)

**Comment by Termineitor244** [comment]
> Maces? Also end-heavy and most maces are 80cm compared to BB(of which we only have one size despite reality's multiple lengths)'s 90.

Huh, you are right about that, seems reasonable, what do you think, @catdach and @MylieDaniels? (Since you were the ones that implemented the categories/martial art that would be affected by this change).

**Comment by catdach** [comment]
> > Maces? Also end-heavy and most maces are 80cm compared to BB(of which we only have one size despite reality's multiple lengths)'s 90.
> 
> Huh, you are right about that, seems reasonable, what do you think, @catdach and @MylieDaniels? (Since you were the ones that implemented the categories/martial art that would be affected by this change).

I personally wouldn't against it, but I'm not knowledgeable enough to speak for Barbaran Montante

**Comment by omni-Var** [comment]
The wrapping on an aluminum bat probably isn't enough to insulate an individual (9 years of baseball). It's very thin and typically has gaps in the wrapping, after a few games. 

Wooden bats wouldn't have to worry about the wrapping, as the dry wood itself is an insulator.

**Comment by Termineitor244** [comment]
> The wrapping on an aluminum bat probably isn't enough to insulate an individual (9 years of baseball). It's very thin and typically has gaps in the wrapping, after a few games.
> 
> Wooden bats wouldn't have to worry about the wrapping, as the dry wood itself is an insulator.

Done in another PR!

**Pull request merged**
