### PR TITLE
Unify holster code (part 3)

### PR DESCRIPTION
**Pull request by mugling**
Continuing from #13982 this PR changes existing holsters to `holster_actor` and adds any new items.

Summary of changes (see also commit notes):
- [X] Knife sheath has larger capacity (3) than ankle sheath (2) and is much faster to draw from
- [X] Scabbard can hold a katana but larger blades will need a different (slower/bulkier) sheath
- [X] Shoulder holster becomes quick draw holster with less capacity but faster draw
- [X] Survivor utility belt accepts slightly larger blades with draw speed equivalent to knife sheath
- [X] ~~Deprecate back holster which is redundant due to shoulder straps~~
- [X] Back holster starts slower than shoulder strap but the former this can be improved with training
- [X] Add back scabard for very large blades ~~(likely replacing the back holster)~~
- [X] Survivor harness draws moderate sized weapon quickly but has storage capacity slightly reduced
- [X] Add any other suggested holsters/sheathes

@chaosvolt if you still want to contribute any holsters this would be a possible opportunity

### CODE REVIEW

**Comment by chaosvolt** [comment]
Hmm? Ah right. Not sure what other types would be good to add. o.o

**Comment by Rivet-the-Zombie** [comment]
>Deprecate back holster which is redundant due to shoulder straps

The back holster should draw faster than a gun worn across the back on a sling.

**Comment by chaosvolt** [comment]
Yesss, a sheath for proper bowie knives? o3o

**Comment by mugling** [comment]
@Rivet-the-Zombie I was considering implementing a tactical sling as an alternative with slightly more encumbrance than a shoulder strap but where the draw speed scaled with increasing weapon skill? The standard sheath holds up to volume 3 (a1a6ec4) and the ankle sheath up to volume 2.

**Comment by Rivet-the-Zombie** [comment]
>I was considering implementing a tactical sling as an alternative with slightly more encumbrance than a shoulder strap but where the draw speed scaled with increasing weapon skill?

Or you could implement that in the extant back holster, so we're not having to add a new item/remove an existing one.

>The standard sheath holds up to volume 3 (a1a6ec4) and the ankle sheath up to volume 2.

I'm glad to see this; having to put a RM42 knife (volume 3) in a scabbard (volume 7) because it wouldn't fit in a normal sheath was silly.

**Comment by Zireael07** [comment]
Back holster is a good idea, please do not remove it. Just give it the scaling draw speed.

**Comment by mugling** [comment]
> Or you could implement that in the extant back holster, so we're not having to add a new item/remove an existing one.

Yes, I suppose that makes the most sense. I've gone with scaling the draw speed as suggested by @Zireael07. At level 2 of the relevant weapon skill the back holster is equivalent (in speed) to a shoulder strap with continuing improvement thereafter.

**Comment by mugling** [comment]
That's everything converted to use `actor_holster` with the key details for each item set out in the commit notes

**Comment by mugling** [comment]
@kevingranade this PR and #14058 are the last outstanding code split as requested from #13936. I'm going to continue any further work in #14113

**Comment by Ygdrad** [comment]
How about a sheath/quiver hybrid for throwing knives?

**Comment by chaosvolt** [comment]
Hmm. I would be easier if quivers could define what ammo types they can hold as an array.

**Pull request merged**
