### PR TITLE
[WIP] Little rework of Find Dog quest

### PR DESCRIPTION
**Pull request by El-Jekozo**
Little rework of Find Dog quest

#### Summary
SUMMARY: None

#### Purpose of change
Little rework of "Find lost dog" mission, to be more JSONised and actually working. As stated here #44833 , it's not working properly. This rework should fix this issue.

#### Describe the solution
I made a little rework of this quest to be more JSONised, added effect of getting dog_whistle upon starting and spawning friendly dog in closest house, changed dialogue, so that it will reflects on how MGOAL_FIND_MONSTER works.

#### Describe alternatives you've considered
 I put "search_range": 75 just in case someone plays with large distances between towns, and that value may change to larger or smaller number.

#### Testing
I did a test locally, works mostly as intended. For some reason, sometimes, mission may put dog on house_roof or house_basement, although I stated "z": 0 at assign_mission_target. Additional testing is appreciated.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> For some reason, sometimes, mission may put dog on house_roof or house_basement, although I stated "z": 0 at assign_mission_target.

I guess this is happening because this snippet `"om_terrain": "house", "om_terrain_match_type": "PREFIX"` could find `house_roof` or `house_basement`. And `z=0` is used only when _searching_ for appropriate house on the overmap. In other words: game searches for `house_foo` on z=0 level, not places monster on this specified z-level.

Also you should remove `place_dog` mission start function as with your change it isn't used anywhere anymore.

**Comment by El-Jekozo** [comment]
> Also you should remove `place_dog` mission start function as with your change it isn't used anywhere anymore.
I'm not so good with C++, so if someone point out on what should I remove (or if someone more experienced suggest changes to PR) I would appreciate it.

**Comment by El-Jekozo** [comment]
I'm back on this issue. Any thoughts how to do it right? To search only on specific z-lvl.
At first I thought that specifying z-lvl will search only on that z-lvl, but it turns out, it didn't. It still search on any z-lvl and can chose any tile with `house` prefix, such as `house_n_roof` or `house_n_basement`, and it places dog on a tagged tile, that can be on any `z`. So the only solution I see at the moment would be searching for specific house(?), but there will be problems with replacing overmap tile(?).

**Comment by faefux** [comment]
Hi, What needs to be done for this to be mergable?

**Comment by faefux** [comment]
Hi, @El-Jekozo, What needs to be done for this to be mergable?

**Pull request closed without merging**
