### PR TITLE
game::butcher() ==> avatar_action::butcher()

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Infrastructure "Move game::butcher() to avatar_action"```
#### Purpose of change

part of the side project to debloat classes.

### CODE REVIEW

**Comment by ifreund** [comment]
Conflicts with #31406 which modified these functions to use iterators and item_location instead of indexes. Would be nice if moving these functions could wait till that gets merged as conflicts will be a little annoying to resolve, but I can manage if need be.

**Comment by KorGgenT** [comment]
ah, sure sorry. that should be easy to do after that gets merged.

**Comment by KorGgenT** [comment]
so i'm going to go ahead and close this temporarily while the colony stuff is being sorted.

**Comment by ifreund** [comment]
Thanks, I appreciate it.

**Pull request closed without merging**
