### PR TITLE
CR Bionic Sniper Profession- CBM Change

### PR DESCRIPTION
**Pull request by KingApep**
Changes the Bionic sniper profession to have the telescopic eyes cbm instead of the taste blocker cbm.

```SUMMARY: Balance "[Bionic Sniper Profession: Replaces the Taste Blocker CBM with the telescopic eyes CBM, Adds Night Vision CBM]"```

#### Purpose of change

It doesn't make sense for the bionic sniper profession to not be equipped with the CBM that allows for longer range shooting and vision; likewise, the bionic sniper class should not be a downgrade from Bionic Solider (which is 3 points cheaper) and not have the night vision CBM.

#### Describe the solution
Removed the the bionic taste blocker CBM so that telescopic eyes could take its place due to it being more thematically appropriate. Added Night vision CBM.

#### Describe alternatives you've considered

Keep the bionic taste blocker and just add the telescopic eyes CBM to the profession rather than exchanging them.

Remove Climate Control CBM in favour of Night Vision CBM rather than just simply adding NV.

### CODE REVIEW

**Comment by Treah** [comment]
I find it strange that this had the taste blocker CBM? Maybe it was copied from another profession when it was being made?

**Comment by KingApep** [comment]
> I find it strange that this had the taste blocker CBM? Maybe it was copied from another profession when it was being made?

From what I can tell, considering bionic soldier also shares it I guess they just thought it suited the military MRE style food? I find the taste blocker cbm strange in and of itself however. In any case, I did think that the profession needed the telescopic eyes CBM, but I presume that it hadn't been in the game when this class was first introduced.

**Comment by thethunderhawk** [comment]
Taste modifier CBM is indeed strange. I wonder if a CBM that simply induces euphoria at-will would make more sense. Less complicated to justify lorewise, still negates bad tasting food, more potential to interact with other mechanics (addiction?)

**Comment by tenmillimaster** [comment]
Brain stimulation of pleasure centers, especially as a means of control, is an incredibly unethical thing and downright terrifying.

It's a bad idea and an implant like that wouldn't ever be fielded.

>The insatiable self-stimulating (male) rat pressed a lever that stimulated its own brain’s “pleasure centers” at a rate of up to 8,000 (sometimes even 10,000) presses per hour, forsaking food, water, sleep, and sex (a female rat in heat)—until it collapsed from exhaustion, convulsed, or even died.


https://www.journals.uchicago.edu/doi/pdfplus/10.1086/688162

**Comment by Noctifer-de-Mortem** [comment]
Gave bionic sniper the telescoping eyes cmb once before but got removed here. https://github.com/CleverRaven/Cataclysm-DDA/pull/19520

**Comment by dunstad** [comment]
If it were possible to prevent certain professions from having certain traits, the reasons it was removed before would no longer be relevant. Killer Drive is an example of the opposite, where the Death Row Convict profession requires a certain trait.

**Comment by thethunderhawk** [comment]
@TenMilliMaster yeah it’s definitely a terrifying concept, as are a lot of the things we see in the game.

>it’s a bad idea and wouldn’t ever be fielded

Just ‘cause it’s a super unethical and could have awful consequences doesn’t mean it would never be fielded. 

You’re right though it maybe doesn’t solve the problem of the taste modifier CBM being weird.

**Comment by np-vortex** [comment]
I would like to follow up on a suggestion made here by @dunstad
`If it were possible to prevent certain professions from having certain traits, the reasons it was removed before would no longer be relevant. Killer Drive is an example of the opposite, where the Death Row Convict profession requires a certain trait.`
Extending "forbidden traits" in scenarios to professions (if implemented exactly the same way) would be relatively simple, for example: https://github.com/np-vortex/Cataclysm-DDA/pull/1/files
Would people be interested in a proper implementation of this?

**Comment by anothersimulacrum** [comment]
Yes, please add that.

**Comment by KingApep** [comment]
Apologies for being away for a month; had some pressing matters; does anyone else have any critiques, suggestions or improvemments before this can get implemented?

**Pull request merged**
