### PR TITLE
increase fire drill charges

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Balance "increase charge capacity of fire drills"

#### Purpose of change
increases fire drill charges

#### Describe the solution
increases initial and max charges by 500 for both bow fire drill and pump fire drill

#### Describe alternatives you've considered
staying as it is

#### Testing
no testing needed, as its just a simple small number change

### CODE REVIEW

**Comment by oosyrag** [comment]
It was to represent the notched plank being consumable, afaik. https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Bow_Drill_with_annotations.svg/1280px-Bow_Drill_with_annotations.svg.png

**Comment by Devengel** [comment]
while its true that it would wear down IRL i disagree with making it the same in-game, there is no point in going down to this level of detail of realism on this particular item, IMHO only creates annoying micromanagment.

and sadly the game doesn't tell you anything when the charges out, for several IRL days i thought i was encountering a bug as i clearly had a source of fire making in my inventory, yet the game refused to make it.

sadly i do not have any C++ coding experience else i'd fix that too.

**Comment by Croisis** [comment]
Increasing the number of charges to effectively infinite on a drill that is made in 5 minutes from two sticks (or one plank), one splintered wood and a short string feels weird. If anything, it should be much lower than the current 50. 
10-15 would be a lot more appropriate I think unless you massively increase the volume of the drill itself. 
How long of a plank to drill holes into do you really get from the 250 ml the bow fire drill has? The pump version is bulkier because of the added stone for better holding so not much better case either.
There is a nice pic of IRL version linked by @OnTheDouble in the original discussion for that visible charges PR at issue #56219.
It is rather small and you are unlikely to be able to use the same hole more than once...
Just my 2 cents...

**Comment by oosyrag** [comment]
Minor digression, but a pump drill is a completely different thing than a bow drill. The stone isn't for "holding", its a flywheel used to preserve momentum so that the drill can re-wind itself. Anyways the notched plank is indeed the same for both and 50 is already very generous for a plank of wood.

**Comment by Croisis** [comment]
@oosyrag Thanks for clarification, I kinda automatically assumed the stone part was to be used as a cap/handle on top of the stick being rotated by the bow to increase pressure on the plank and start the fire faster because of increased friction.
I've checked it on YT and now I get why the recipe has additional DRILL_ROCK quality requirement in it... TIL 👍

**Pull request closed without merging**
