### PR TITLE
New "Bordered" scenario

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "New 'Bordered' scenario"

#### Purpose of change
To add a new challenge type.
I'm working on another location, for which I created this border location, but I think it could be used as a new challenge type, implemented as a new scenario. You are limited only to your initial overmap, the loot is limited too. Limited resources should provide different experience of survival as you can't simply go to adjacent overmap when the loot on initial overmap is exhausted (or it wasn't very good from the start) anymore.

#### Describe the solution
- This scenario creates a 24-tiles width walls of solid rock on borders of initial overmap. This wall doesn't respect terrain it's placed upon, so it actually could "cut" cities, rivers, and roads.
- The scenario is based on evacuee scenario, with evac shelters as possible starting locations. It earns 2 points to the player.
- The `rock_border` location won't spawn naturally, only through the use of `BORDERED` scenario flag.
- Rock border could be successfully pickaxed or jackhammered if player is stubborn enough, but it's not the intended way to play this scenario.

#### Describe alternatives you've considered
- Make border consist not from solid rock, but instead of some (new) indestructible terrain type. I just wanted not to add redundant matter.
- Replace evac shelters as starting locations with some other locations, or maybe instead add some other locations to the list.
- Increase or decrease points earned from selecting this scenario. Make it cost 0 points.

#### Testing
Created a new world. Selected new scenario. Started the game. Checked the existence of the Wall.

#### Additional context
изображение

изображение

изображение

изображение

### CODE REVIEW

**Comment by Zireael07** [comment]
Would be cool to have a version with water instead of a wall - this way we could maybe do an actual coast on our New England...

**Comment by Night-Pryanik** [comment]
We don't need no education...

**Comment by Maddremor** [comment]
How tall and/or deep is this wall? It should probably not be defeated by a stepladder.

Would mobs like the giant moles cause issues by digging through the wall (I admit there is a bit of the honor system at play. Perhaps use migo resin if you really need a tough wall?

If the starting location (evac in this case, but it could expand to other stuff in the future) isn't placed in the central overmap, will the player start outside the wall?

**Comment by Night-Pryanik** [comment]
Game will place borders exactly in the overmap the player spawned in.

**Comment by ZhilkinSerg** [comment]
There is some code in defense mode that prevents going out of initial overmap special/terrain. Maybe you should utilize this in this challenge scenario.

**Comment by Night-Pryanik** [comment]
Thanks, I'll check it out.

**Comment by Shodan14** [comment]
You know this is going to be about getting through that wall lol.

**Comment by Night-Pryanik** [comment]
Yeah, most probably. 
Though I'm not sure if I should _really_ make the getting out impossible, or should I left the possibility as a part of challenge itself.

**Comment by ZhilkinSerg** [comment]
> You know this is going to be about getting through that wall lol.

Easily avoidable by making every other overmap filled with solid rock.

**Comment by Maddremor** [comment]
As the person who pointed out the need for a giant rock wall, will the giant rock wall cast a giant shadow?

Will stuff like the evac computer and quests create destinations outside the border?

Is a mininuke enough to make it through? Probability travel? Teleport trap? 

Can map extras override part of the terrain?

All that said, I think there has to be some level of honor system at play. You can't keep all players from getting out, just remove any short term opportunity or motive to do so.

**Comment by Night-Pryanik** [comment]
> will the giant rock wall cast a giant shadow?

Nope, neither any other tall structures (apartment towers, radio towers) cast shadows. That could be an interesting idea. Not in this PR though.

> Will stuff like the evac computer and quests create destinations outside the border?

Yes. Our missions mechanics isn't aware of the surroundings when generating quests and thus it doesn't consider the Wall as an obstacle. I think making quests spawn targets only within the Wall would be too much of a hassle, though I'm not against it.

> Is a mininuke enough to make it through? Probability travel? Teleport trap?

Only tests can show.

> Can map extras override part of the terrain?

Yes. The Wall is just like any other special consisting of ordinary terrain, it doesn't have any mechanisms to prevent its modification, and I doubt it should have them.

>All that said, I think there has to be some level of honor system at play. You can't keep all players from getting out, just remove any short term opportunity or motive to do so.

Exactly my thinking. The Wall is just one step ahead of self-limiting for players who consciously want to play a challenge like this.

**Comment by krulunio** [comment]
Resin wall

**Pull request merged**
