### PR TITLE
Chemistry PPE

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Adds toolsets for Personal Protective Equipment intended to be used with chemistry."

#### Purpose of change
Several of our recipes are extremely hazardous IRL and would be dangerous to create without proper protective gear. This adds some toolsets that can be added to recipes that require the appropriate equipment. 

#### Describe the solution
Adds toolsets for gloves, goggles, and gasmasks. The latter requires at least a single charge of gasmask cartridge.

#### Describe alternatives you've considered
Ventilation hoods/fume extractors would be nice but A) require things we don't already have in game and B) can be added as furniture/appliances to the toolgroups later.

#### Testing
Initial toolsets are complete without errors. Game loads successfully.

#### Additional context
Suggestions welcome, we have lots of protective equipment and I've tried to capture everything appropriate.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
>Suggestions welcome, we have lots of protective equipment and I've tried to capture everything appropriate.

``ppe_skin``, consisting of OUTER torso+arm-covering garments, such as labcoats, to protect from splash.

**Comment by flybye3o6** [comment]
i was working on this in #61516 because id need it for chem recipes 
if you wanna take a look at how i had a go at it, this is cleaner then my attempt 
dose it use filter/gas charges because gas and filter cartridges are pretty easy to make and gas masks don't provide any breathing protection without them

**Comment by Drew4484** [comment]
> i was working on this in #61516 because id need it for chem recipes if you wanna take a look at how i had a go at it, this is cleaner then my attempt dose it use filter/gas charges because gas and filter cartridges are pretty easy to make and gas masks don't provide any breathing protection without them

I think we're on the same track, I didn't add cloth covers because they're of marginal value but otherwise same idea. Shoot me a DM when you're free and we can probably merge these.

**Comment by flybye3o6** [comment]
the angle i was coming at this was to think about hazard lvl for the recipes and what they mite require
hazard lvl 1 would be eye protection,
hazard lvl 2 would be surface protection to prevent skin contact and burns,
hazard lvl 3 would be filtered breathing,
hazard lvl 4 would be closed circuit breathing and/or airtight full body suit

**Comment by Paprika-H** [comment]
Isn't there a fume hood in the lab part of the sewage treatment plant?

**Comment by Drew4484** [comment]
> Isn't there a fume hood in the lab part of the sewage treatment plant?

Yes, there a few other places. It contains smoke, but you can't build it anywhere. I figured survivors were more likely to have a gas mask than install a fume hood, which would take a bunch of extra work to make function for this anyway.

**Pull request merged**
