### PR TITLE
remove rand_charges

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Attempt to support #73208
#### Describe the solution
Replace all use cases of rand_charges with item group effect, that does the same
Do not remove the code part to not cause conflicts with #73208
#### Testing
Spawned myself, walked around, killed bunch of zeds, their cash cards still work the same
#### Additional context
Made from scratch using some parts of #73209 because it was easier than debug odd errors

### CODE REVIEW

**Comment by Procyonae** [comment]
I'd forgotten how silly the cash cards were ;D
Removing charges-min and charges-max (in favour of `charges: [ min, -1 ]` and `charges: [ 0, max ]` in their individual usages) would be nice too but that might want to be several PRs looking at how much it's used >_<
image

**Comment by GuardianDll** [comment]
i can make a regex that clean it up in like a minute
20 minute adventure, what could possibly go wrong

**Comment by Procyonae** [comment]
I should've kept it to myself, I were figuring I'd do that c;

**Comment by BalthazarArgall** [comment]
Nice, one less thing to clutter the code for no reason

**Pull request merged**
