### PR TITLE
Robofac reloaded

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary

```SUMMARY: Content "Adds the Robofac"```

#### Purpose of change

This is the initial work on adding the robofac, as  mentioned on  #27479

What this PR adds is still a bit bare bones, contains only a single trader, a single mission and a basic, small location (of which the underground is still not done completely) however I think its enough to start with.

#### Describe the solution

So lets talk about the lore this PR tentatively adds to the Game:

The in-game name for robofac is "Hub 01", after the lab its headquartered on. Hub 01 was the easternmost  regional hub of the  pre-cataclysm Melchior system. Since it was mostly dedicated to Robotics/Computer-Science and executive work, instead of the more dangerous blob or dimensional research of other labs. Hub 01 survived through the cataclysm event without completely collapsing, but this also means that Hub doesnt actually have (at least initial) access to mutagen, teleportation, cloning and other neat stuff other labs have, the player will have to get access to these by claiming other labs in name of the Hub.

Since the Hub has sufficient resources for short-midterm survival, the remaining staff is very isolationist and distrustful to outsiders. Their interactions are mostly limited to trading lab trash and surplus weapons with survivors that make a very very good argument, or hiring people to do dirty surface based work their own robots cant do. Members of the hub also show their surface paranoia in the few cases when they leave the lab. Their standard surface outfit is a unnecessary  hazmat uniform.

This attitude is reflected in the first mission. They interact with you only through a door intercom (after forbidding you access to their lab) and hire you to find what happened to a prototype robot they were modifying to scavenge and fight surface threats. The great reward for surviving  this jabberwock tier foe is trade access, and a debt in your favor of 5 dollars. Initially, the Hub is only interested in using people from the surface and their first handful of missions will reflect this, with the player being kept outside of the lab, and being given meager rewards for their dangerous work.

Initially, its not obvious that a mayor player within the Hub is actually the AI Melchior IV. Initially Melchior might even be malfunctioning and bringing it online will require the player to clear a dangerous part of the lab, that is dimensionally unstable (AKA full of Nether foes) due  to Melchior's multidimensional OS.

---

Redone without the commit mess

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I'd love to see some screenshots of your locations. The content looks great.

**Comment by faefux** [comment]
Hey, if you want any help with this i'd be happy to help with this. I have no idea how to message people privately on github though, sorry.

**Comment by John-Candlebury** [comment]
Heres the map:

### Surface Access
This is were the player takes the first series of missions. Has a perimeter wall and a sofa to sleep in. Might later become a small robotic farm or become infested with fungaloids.

image


### Main Chambers

Still inaccessible during normal play so empty and prone to changing. This will be the main  room where the player, once made a proper Hub member, interacts with quest givers and can live an idyll and sheltered life. Missing a subway connection. Roughly from top left:

Crafting rooms, Cafeteria/Kitchen, Elevator, Reception, Central room, Directors office, Dormitory, Library, Directors Quarters.

image

---

@faefux  I could do with some help doing the exterior missions, ideally with some  cool unique interactions, if you want to help me with  those it that be awesome!

But you can also help with other stuff if you want, the only things I have partly done are the Hub Director and Security Head NPCs and the rest of the Hub mapgen. So if you want to do NPCs you could do the head of robotics or lab hydroponics or similar.

I'm Candlebury in the discord, and John_Candlebury in discourse, if you want we can discuss over there.

**Comment by faefux** [comment]
Hey, would you like any help doing more faction work? Really interested in helping flesh out the faction stuff of the game and kind of thinking that maybe I should help with the ones people want first rather than continuing with my own.  Would be happy to help you if you would like.

**Comment by faefux** [comment]
@John-Candlebury Would be happy too!! Do you use IRC?  It doesn't seem that github has a messaging feature (that or i'm an idiot.) and not really sure how else we can collaborate.

Incidentily, I'm writing some missions for a hacker NPC i am building and have been thinking there could be at least one crossover mission here. :)

**Comment by John-Candlebury** [comment]
@faefux Sorry, I dont use IRC.

That said I saw you post a topic for npcs in the Discourse forums, you can PM through there if you want, I'm John_Candlebury over there.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/robot-npcs-for-bases/20117/5

**Comment by faefux** [comment]
> @faefux Sorry, I dont use IRC.
> 
> That said I saw you post a topic for npcs in the Discourse forums, you can PM through there if you want, I'm John_Candlebury over there.

The machine i'd dev on is pretty dead at the moment so i'm currently just writing a lot of notes and very rough psuedo-json from memory, that said i'll try to message you over there with something solid and usable within the next week or so.

**Pull request merged**
