### PR TITLE
ChestHole32, Iso, adds PK, Razorclaws, coal, bio blade, offal, and more

### LINKED ISSUE #13347: Multitile water not showing properly when it meets deep water.
The multi-tiles we have for shorelines show up when they meet corners deep water, as seen in this picture.

http://i.imgur.com/yUgwHkx.png
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25943359-multitile-water-not-showing-properly-when-it-meets-deep-water?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Chezzo**
This PR changes terrain.json to add the CONNECTS_TO flag.

Closes #13347

It also updates the Chesthole32 and Iso tilesets, adding Zombie's R Us' (and some of mine and Kedryn's) PK rebalance tiles to both, as well as adds a whole lot to the 32 tileset, Razorclaws, coal, bio blade, offal, and more.

Before:
Jersey Shore

After:

No Shore

### CODE REVIEW

**Comment by hitbutton** [comment]
Water shouldn't be connecting to wooden fences. It should be simple to add a new connect group for water instead.

Shallow water shouldn't be using AUTO_WALL_SYMBOL either.

**Comment by Chezzo** [comment]
I don't have your coding powers, though @hitbutton!

**Comment by hitbutton** [comment]
The new group should just need to be added to:
mapdata.h (in the enum for ter_connects)
and
mapdata.cpp (in the declaration of ter_connects_map).

**Comment by Chezzo** [comment]
I'm'nna split this up into two PRs, one for the tilesets, and one for the water connects to.

**Pull request closed without merging**
