### PR TITLE
[WIP New Mod] A long drive/Desert bus/Desert train/going in a straightish line with some kind of vehicle

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Content "New mod [Route Z]"

#### Describe the solution

This is Ringtail's idea I just tinkered around and made the worldgen work, we'll hopefully be doing this together ^_^
Named [Route Z] currently as a filler by Maleclypse
Currently dependant on desert_region
Uses MAs predetermined omap system to make the map one long road for the true Desert Bus/A Long Drive experience

#### Testing

image

#### Additional context

Requires #70752 so the vertical column of pregenned OMs can be surrounded by desert rather than lake
desert_region is obsoleted currently and needs a few errors fixing

Todo:
- [ ] Whitelist buildings
- [ ] Make whitelisted buildings spawn adjacent to the road/railroad
- [ ] Mutable settlements with bus stop/rail station to connect them to the long road/railroad?

In Progress
- [ ] Windy road/railroad through the desert - the general shape works, needs bend direction handling and a fix for x > 89 point joining

Done:
- [x] Straight road through the desert
- [x] ~~Straight "Railroad" (using subway for now) through the desert~~ Any linear map through any terrain

### CODE REVIEW

**Comment by Rabadash94** [comment]
It will surely be interesting, since that game has the defect of being too short.

**Comment by harakka** [comment]
DeZert Bus let's gooo!

**Comment by Ring-Tail** [comment]
I've drafted a design document for a brief overview gameplay, not sure if I can attach it on here. Unfortunately my knowledge of Git is limited at the moment. Actively trying to learn though.

[Cataclysm DDA - Route Z .docx](https://github.com/CleverRaven/Cataclysm-DDA/files/13886436/Cataclysm.DDA.-.Route.Z.docx)

**Comment by Rabadash94** [comment]
Reading that docx, it seems that the mod is not inspired by the video game called "Route Z". I guess there won't be any problems with the name, right?

**Comment by Procyonae** [comment]
Welp there's the temp name out the window

**Comment by MNG-cataclysm** [comment]
What about "Long Haul Through Hell" for a name?

**Comment by Ring-Tail** [comment]
I like the alternate DeZert name, unless that was referencing something as well?

**Comment by Rabadash94** [comment]
If what is needed is an "ending", it could be the classic rumor of a "safe zone", an area that the player must try to reach by collecting, not only supplies, but also clues and directions along the way, assuming that the route has bifurcations.

**Comment by Ring-Tail** [comment]
> If what is needed is an "ending", it could be the classic rumor of a "safe zone", an area that the player must try to reach by collecting, not only supplies, but also clues and directions along the way, assuming that the route has bifurcations.

It's a singular road, the journey to get there will take a considerable amount of time (I dom't know the map gen limits) hell, maybe the end structure could be randomised so each playthrough will render a different "prize"

**Comment by Procyonae** [comment]
I don't like the idea of just calling it DeZert because then peeps would get it confused for the desert region mod
>I don't know the map gen limits

We can make it as long as we want pretty much, idk how easy it is to stick something at the end rn though

**Comment by Rabadash94** [comment]
Will this mod use the mechanics of #70056? I say, taking advantage of the fact that here distances will not be a problem, but, on the contrary, a great advantage.

**Comment by Procyonae** [comment]
> Will this mod use the mechanics of #70056? I say, taking advantage of the fact that here distances will not be a problem, but, on the contrary, a great advantage.

Not to begin with but it would be nice later sure

**Comment by Procyonae** [comment]
This isn't dead Ringtail just hasn't doesn't seem to have much interest and I were mainly interested in seeing if it was doable and it is, I will come back to it though

**Comment by alp7292** [comment]
is there a future plan to make it work without desert but with green roads too (maybe snowy)

**Comment by Procyonae** [comment]
> is there a future plan to make it work without desert but with green roads too (maybe snowy)

There aren't any "future plans" rn so no, I don't see any reason why you wouldn't be able to easily switch it though if I don't lean into requiring the desert mod for more than just terrain

**Pull request closed without merging**
