### PR TITLE
Longest side for torso armor

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Adds longest sides to items that need it.  

#### Describe the solution
I looked up the height of breastplates and found that at the large end they are 60cm tall.  Anything that was solid metal or other armor that I don't believe would fold, got put in at 60cm.   If I thought it had some give to it and might be vaguely foldable I reduced it as I went. 

#### Describe alternatives you've considered
none

#### Testing
Auto testing only.

### CODE REVIEW

**Comment by Photoloss** [comment]
* Even "boiled" leather armour probably is flexible enough to squish a bit, maybe 45 cm as a middle ground between fur and rigid.
* The non-boiled is thinner and has not been hardened to my knowledge so it should collapse similarly to thick fur.
* "Plated leather" is a little ambiguous, a proper [brigandine](https://youtu.be/DCf-CnjbWcg?t=20) can fold a fair bit but "sheet metal in a leather vest" probably won't.
* Lamellar is constructed similarly to brigandine only the "plates" are made of leather in this instance, it's fairly flexible.
* If the cleansuit and beekeeping suit are getting a set length then chainmail probably should as well, it can't fold in on itself as well as textiles.
* The hazmat suit probably should match either the cleansuit or the beekeeping suit.
* Power armour seems to be completely untouched.

**Comment by Maleclypse** [comment]
> * Even "boiled" leather armour probably is flexible enough to squish a bit, maybe 45 cm as a middle ground between fur and rigid.

I have some experience with boiled leather armor and the only parts of it that can bend would be the parts that go over the shoulders on either side of the neck and they don't bend much. My measurement was covering from bottom of throat to right around the belt line so the belly is covered.  So I probably have underestimated the length of all these armors by the shoulder height.

**Comment by Photoloss** [comment]
It also depends on the exact processing method. [This](https://youtu.be/tDvTXprbAO4?t=114) looks like you could still squeeze it down a bit whereas [this](https://youtu.be/GiNUZwug5t0?t=624) is pretty solid. The in-game recipe allows both wax (half a litre seems fairly low for a full suit though) and tallow, but also vinegar as an alternative which must function differently. Amusingly the in-game description claims it is "not rigid" but that seems to be an artefact of the pocket/encumbrance settings ;)

**Comment by Maleclypse** [comment]
> It also depends on the exact processing method. [This](https://youtu.be/tDvTXprbAO4?t=114) looks like you could still squeeze it down a bit whereas [this](https://youtu.be/GiNUZwug5t0?t=624) is pretty solid. The in-game recipe allows both wax (half a litre seems fairly low for a full suit though) and tallow, but also vinegar as an alternative which must function differently. Amusingly the in-game description claims it is "not rigid" but that seems to be an artefact of the pocket/encumbrance settings ;)

https://medium.com/@jasontimmermans/a-comparative-study-of-leather-hardening-techniques-16-methods-tested-and-novel-approaches-8574e571f619

I hadn't realized vinegar was in the recipe until you mentioned it.   I'm thinking after reading all of that about removing vinegar from the recipe.

**Pull request merged**
