### PR TITLE
[RDY]Add 3L jar canning and pickling recipes, add canned red sauce, update kompot, update some missed .5L canning recipes

### PR DESCRIPTION
**Pull request by Regilith**
#### Summary
```SUMMARY: Content "Adds and modifies 3L, regular, red sauce, and kompot canning recipes."```

#### Purpose of change
Makes 3L jars more useful and versatile. Fix the canning recipes of some non-updated foods. Make the kompot recipe more realistic and versatile. Allow preservation of red sauce.

#### Describe the solution
Semi-resurrection of #22526
- Add canning recipes for red sauce
- Add 3L recipe variants for all canning and pickling recipes
- Make base kompot recipe craft .5L portions instead of 3L portions
- Add .5L canning recipe for kompot
- Adjust kompot recipe to use more power (previously 2, which was lower than boiling water)
- Adjust kompot recipe to use more sugar. 1 gallon of kompot calls for ~1 cup of sugar, which translates into 27g per .5L. 1 unit of sugar is 5g, so .5L should use ~5 units. It's an art, not a science. http://ukrainian-recipes.com/apple-kompot.html https://polishhousewife.com/kompot/
- Adjust kompot recipe to use 50% more fruit, from 4 to 6. This is both more realistic, and to make it a multiple of 6.
- Adjust kompot calories to account for increased sugar and fruit. 1 apple (~100 kcal) + 25g sugar (97 kcal) = 197 kcal, or rounded to 200 kcal per .5L portion to reflect the wide variety of ingredients able to be used to make kompot. A single portion is 250ml, or ~100 kcal.
- Update some other canning recipes to include use of canning pot, which I missed in #25661 because they didn't use the vacuum sealer for some reason. The previous lack of any canning method in these recipes was probably an oversight. The list includes: canned offal, canned meat, canned fish, canned human, canned veggy, canned fruit, canned veggy soup, canned tomato.
- Add 3L foods to kitchen and canned droplist

### CODE REVIEW

**Comment by Regilith** [comment]
This PR involves a lot of numbers balancing, so I'd appreciate it if someone gave it a once-through to make sure I didn't miss anything.

I decided to abstract the power usage of canning to 100 per .5L jar, and 200 per 3L jar for the following reasons:

- To purify 1 unit of water via boiling, it takes 5 minutes and 3 power. Water bath canning involves cooking the food, getting the water to a boil, and maintaining boil for ~10 minutes for .5L and ~25 minutes for 3L (larger jar means longer time to sterilize)
- I'm assuming the survivor maintains temperature when they boil water (as I do at home), so maintaining a boil would take 9/18 power per unit of water for .5L/3L jars, respectively. As the survivor is boiling 10 water, that power usage goes to 90 and 180.
- Add in the fact that all the power requirements for cooking the non-sealed variants of these foods adds an additional ~2-30 power, the costs would be around 92-120 and 182-210, so I decided to simplify the power costs to 100/200 for easier maintenance.

I changed the id_suffix of the 3L kompot recipe to keep inline with the other 3L recipes, which hopefully shouldn't break anything. I played a world before this PR, spawned a 3L jar of kompot, quit the world and applied the update, and the 3L jar remained the same and was usable.

This may change sealed jar spawns (whether they spawn in .5L or 3L jars in world, if applicable). I need to add canned red sauce to the drop list, as well as perhaps some other 3L drops.

I removed the ["result_mult": 12] from the 3L jars as they seemed to spawn with the correct amounts without it. If this was wrong, let me know.

**Comment by Regilith** [comment]
Aside for the aforementioned discussion on whether 100/200 power for canning is acceptable balance-wise, constituting a significant nerf compared to the previous vacuum sealing power component, this should be ready for review.

**Comment by Rivet-the-Zombie** [comment]
Pickled offal is *supposed to* have a better fun value than the basic canned stuff.

**Comment by Regilith** [comment]
That's probably outside the scope of this PR

**Comment by Regilith** [comment]
Jenkins rebuild

**Comment by l29ah** [comment]
I've made 3L worth of pickled meats, but only got one meat in the jar.

**Pull request merged**
