### PR TITLE
Eggnog rebalance

### PR DESCRIPTION
**Pull request by Cyrano7**
Hopefully this is better.
Fixed some inconsistent spacing.
Tweaked the recipe and stats a bit.
Buffed nutrition and fun.
Changed charges from 1 to 2.
Taken out of spawn groups.

[old] I'm happy eggnog made it in but I think it was to far down the PR chain and didn't get looked at properly. Fixed some inconsistent spacing and cinnamon amount as that comes in bottles of 100 and 1 is to little. As for balance I haven't done the math yet but I think it needs some work. Changed the amount cause 1 is to low for the amount of ingredients. As for lore I took it out of the spawn groups. Its a holiday item that would be uncommon different parts of the year. You can still learn it from a cookbook.
Edit: From this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/14382
Edit2: Summon @chaosvolt @railmonkey @Coolthulhu for balance debate.
Edit3: Yes I realize "Eggnog rebalance" is quite a silly title to see on the PR page.

### CODE REVIEW

**Comment by Darkyhard** [comment]
>As for lore I took it out of the spawn groups. Its a holiday item that would be uncommon different parts of the year.

I think that you still can find some eggnog in shops, even if it isn't a holiday now.

**Comment by Cyrano7** [comment]
Ya you can but its more of a question of how commonly like how commonly would you find spiked eggnog in your average liquor store.

**Comment by Darkyhard** [comment]
1 or 2 is rare enough. Frequently spawned items have much higher numbers than that.

**Comment by chaosvolt** [comment]
You summoned a derpdragon? o3o

Not entirely certain just yet, though I do see a thing to check in recipe_food.json. Looks like a lot of extraneous spaces got added in various brackets, that I'm assuming the merger cut out while merging.

**Comment by railmonkey** [comment]
Not much to say that hasn't been said. As for the spaces, that comes from me copying and pasting a base to work off of. Milk for eggnog and I one of the alcohols for the spiked variety. I was trying to make the spaces consistent, ironically enough. As for the cinnamon, you really truly don't need much. It's a garnishment, and cinnamon itself has a very strong flavor anyway. Nutmeg, too, which cinnamon is replacing. Also, what is your reasoning behind changing the charge amount?

**Comment by Cyrano7** [comment]
Don't worry about the spaces, happens to everyone. For the cinnamon since I was upping the charges I thought id add more. Also It comes in bottles of 100. Like with all spice types the kinda minimum value is 5 it seems. 10 is not really that much.

**Comment by Cyrano7** [comment]
I'll be able to sit down and do the math later today hopefully.

**Comment by Cyrano7** [comment]
Okay I think i'm about done. @railmonkey I've just changed the charges to 2. Its really about the amount of ingredients. Hard to fit that in one portion. 
So for math from the ingredients for the normal eggnog you can get about 98 nutrition and 45 quench total. So I upped nutrition. As for the fun I raised it because of rarity and amount/cost of the ingredients. For the spiked I tried to bring it in line with the other hybrid cocktails like bees knees. Changed fun and use action to alcohol_weak. 
@railmonkey I don't mean to harshly scrutinize your work or anything. Just giving it a second look.

**Comment by railmonkey** [comment]
Not contesting any of your changes but one: I believe that the use action should remain ALCOHOL. That stuff can and will knock you on your butt at the strength needed to make it non-perishable. For the rest, well, I freely admit to taking shots in the dark.

**Comment by Shadefang** [comment]
I ran some numbers, and if we're being realistic 10 is way too much. Be aware i'm using rough numbers here, but I can pull out precise ones if people want.
Most recipes I found use about a teaspoon of cinnamon and make about a pint of eggnog. A pint is about 500 ml. 
Spices usually come with 100 charges in a 250 ml bottle. 250 ml is about 50 teaspoons, so each charge is about half a teaspoon. 
Therefore the standard small bottle (250ml) of eggnog should have about 1 charge (1/2 tsp) of cinnamon in it.

On a separate note, unless i misunderstand how the spoils_in works, spiked eggnog spoils WAY too fast. If you're going to add enough alcohol to have it actually have an alcohol effect (weak or not) it'll keep pretty much indefinitely (according to wikipedia it's often aged for up to a year).

**Comment by chaosvolt** [comment]
> If you're going to add enough alcohol to have it actually have an alcohol effect (weak or not) it'll keep pretty much indefinitely (according to wikipedia it's often aged for up to a year).

I thought the idea here WAS to give it a full alcohol effect, and make it non-perishable?

**Comment by railmonkey** [comment]
It is, yes. I somehow overlooked that tweak. It's intended to be non-perishable, yes. Fix that, too.

**Comment by Cyrano7** [comment]
Okay looking at spoiling again. I guess spiked can be changed back. Milk spoils at 8 so having regular eggnog spoil at 8 makes sense. As for cinnamon it can be cranked down.

**Pull request merged**
