### PR TITLE
[Magiclysm] Allow mutants to wear magic items too

### PR DESCRIPTION
**Pull request by gisaku33**
#### Summary
Mods "Allows mutants to wear magic items"

#### Purpose of change
Currently, huge mutants are unable to use most worn magic items due to them not fitting. This makes very large mutants cry very large tears.

#### Describe the solution
Adds the "OVERSIZE" tag to most magic items to represent them magically resizing to their wearers, allowing mutants to wear them.

#### Describe alternatives you've considered

Adding variants of current magic items for mutants, either by just added the "OVERSIZE" tag or making them XL.

#### Testing

Created a new character, debugged him to be a Bear with the Huge mutation, spawned in magic gear and put it on without issue.

### CODE REVIEW

**Comment by Salty-Panda** [comment]
Have you tried using it with Small character, like Rat mutant?

**Comment by gisaku33** [comment]
Hm, tested with a mouse mutant since I think those are the only ones that get the small mutations, unfortunately things are coming up as (huge!) and increasing encumbrance, but they're still wearable.

**Comment by SariusSkelrets** [comment]
If you find a way to make an item fit all sizes, tell me

I have a PR opened that solve similar issues with spell-made wearable items

**Comment by Salty-Panda** [comment]
We could add flag for that and in `item::get_sizing` we could return `item::sizing::ignore` in this case.
I just glanced at the code but I think it should solve this properly.

**Comment by gisaku33** [comment]
I'm only barely familiar with JSONs, so if you know how to implement that it'd be amazing. (I'm also not very familiar with github, so if I need to do something to authorize changes/additions to this let me know)

**Comment by I-am-Erk** [comment]
Closing as stale for now, feel free to reopen when you are active

**Pull request closed without merging**
