### PR TITLE
Customizable widget height

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
Followup to wapcaplet's work on #51438.

While working on #53980, I ran into the 1-line limitation of custom widgets. I would like the compass legend to occupy an arbitrary number of lines (and I expect future widgets could make use of this as well - ex: Log messages).

#### Describe the solution
I've added a new field `"height"`, which is intended to be used for non-layout widgets (ex: compass legend). This field reserves the specified number of lines for the widget. Functions in the `display` class can split the text into lines by using a newline (`\n`) delimiter.

I pushed a demo of the compass widget using the custom height feature:
https://github.com/dseguin/Cataclysm-DDA/tree/widget_height_test

Specifying a height of 1:
compass_legend_1

Specifying a height of 3:
compass_legend_3

Specifying a height of 5:
compass_legend_5

#### Describe alternatives you've considered
PatrikLundell suggested using 2-3 different widgets to split the compass legend. While that would work, it would involve some hackery that I'd like to avoid.

#### Testing
Added unit tests to check that multiline rendering splits the content properly. Also tested in-game using the compass widget demo above.

#### Additional context
Ping: @wapcaplet. This is your work, let me know if you have any issues with this.

### CODE REVIEW

**Comment by wapcaplet** [comment]
Awesome, looks good on a skim-through of the code.

I'm not sure how to test UI functions that actually render things into a window. Something like this might be easier to test if we could build a string-only representation of the whole multiline widget, with all the color code markup and embedded newlines (which would finally be rendered line-by-line to the `window` instance). This seems like a natural thing for `widget::layout()` to do for "rows" layouts, and there's no reason even `widget::show()` couldn't embed newlines if it's helpful (like once the overmap becomes widget-ized with "width" and "height", for example).

Doing it that way, the test cases could exercise the bulk of the widget look-and-feel and layout testing just with string comparisons (see `tests/iteminfo_test.cpp` for examples like that), and the custom draw function(s) could perhaps become simpler, since they'd only need to render the multi-line string from top to bottom, and not have to deal as much with layout concerns.

Looking forward to seeing where this goes!

**Comment by dseguin** [comment]
Great news! I found a way to scrape the window's contents and retrieve text on the screen (see [widget_test.cpp#L51-L66](https://github.com/CleverRaven/Cataclysm-DDA/blob/6ddd11b35fa5d03915523aedf7ff7ba286c824d3/tests/widget_test.cpp#L51-L66)).

With this, unit tests should be good to go.

**Comment by PatrikLundell** [comment]
Much superior to multiple widgets (and with a much wider additional potential usage). I assume the unused lines remain blank when there's nothing to show on them (e.g. the 5 line layout with no hostiles in view)?

Why is the 1 line layout content offset ('d' halfway between"SW" and "S")?

**Comment by dseguin** [comment]
> Much superior to multiple widgets (and with a much wider additional potential usage). I assume the unused lines remain blank when there's nothing to show on them (e.g. the 5 line layout with no hostiles in view)?
> 
> Why is the 1 line layout content offset ('d' halfway between"SW" and "S")?

Single-line widgets are all left-padded, which is fine, but I found that the padding interferes with the formatting for multi-line widgets:

compass_left_padding

**Pull request merged**
