### PR TITLE
Reworked 5 houses for better style consistency

### PR DESCRIPTION
**Pull request by Mshock777**
Don't forget to use `&w=1`.

### CODE REVIEW

**Comment by mugling** [comment]
Includes changes from `place_items` to `place_loot` (a good thing) but this is hidden within many presentational changes. Either submit those as a separate commit (or ideally leave them unchanged). Placement of the colon isn't especially relevant so long as each file is consistent with itself.

**Comment by Coolthulhu** [comment]
Oops, I merged the PR before reading the full comment. What are the changes? Should I revert?

**Comment by Mshock777** [comment]
1. Restyled code (spaces around colons, aligned everything for better readability).
2. Changed symbols to fit unified standard that I'm working on (and hopefully for every single mapgen) 
3. Replaced `place_items` with `place_loot`.

**Comment by mugling** [comment]
> Should I revert?

No. That said I didn't even notice part 2 with the symbol changes (a good idea). We should aim to keep behavioral changes and presentational changes separate

**Comment by Mshock777** [comment]
I'm working on the rest of houses, should I do this in 2 separate pulls?

**Comment by mugling** [comment]
Separate commits is sufficient although I'd avoid making formatting changes at all unless necessary to avoid inconsistent style within a file.

**Pull request merged**
