### PR TITLE
Vehicle installation requirements (part 3) [RDY]

### PR DESCRIPTION
**Pull request by mugling**
Refactor `veh_interact.cpp` with no behavioral changes

### CODE REVIEW

**Comment by Coolthulhu** [comment]
You could also fix #17314 here and change one of the "You don't have requirements" that was left out in the last PR.

**Comment by Coolthulhu** [comment]
Managed to get a crash.
I tried to install a cargo carrier on a car chassis. I turned on debug hammerspace and tried installing it while spawning extra tools. After few tries, I got a bunch of debugmsgs relating to failed install and a segfault.

**Comment by mugling** [comment]
Let me take a look

**Comment by mugling** [comment]
#17314 can be addressed via  #17324 which provides an ideal mechanism to ensure all installation requirements are consistent

**Comment by mugling** [comment]
> Managed to get a crash.

Does it occur only with `DEBUG_HS`?

**Comment by Coolthulhu** [comment]
> Does it occur only with DEBUG_HS?

I think yes.
But fixing it would be easy - just making the function break rather than continuing when `base.is_null()`.

**Comment by Coolthulhu** [comment]
#17324 isn't ready to be the proper solution yet. It would be better to fix #17314 in the simplest way at the moment.

That "you lack the requirements" - it's just weird phrasing, but it's trivial to fix.

**Comment by mugling** [comment]
Ok both pushed

**Pull request merged**
