### PR TITLE
Migrate digging to constructions

### LINKED ISSUE #54511: Make digging pits a pauseable task.
### Is your feature request related to a problem? Please describe.

For someone that dig pits a lot, this is a big problem. Digging is extreme work which drains fatigue like crazy, however, you MUST finish it in one session or redo the entire process from scratch which horribly wastes time. It needs to be pause-able, like construction projects.

### Solution you would like.

Make digging pits into construction project probably, if you can make the fatigue cost vary on construction projects. Or make something similar for them.

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
None

#### Purpose of change
Digging can't be paused or resumed very well

Pits can be filled for free

Deep pit is already a possible construction, used as a prerequisite for other constructions, but it uses different mechanics compared to the digging activity

Fixes #54511

#### Describe the solution
Migrate digging to constructions and add the missing bits:
1. add exertion level to constructions
2. add a `do_turn_special` to run arbitrary functions on each turn of the build activity
3. pass the actor to `post_special` and `do_turn_special` too instead of just the location
4. improve the improved `ACT_MULTIPLE_CONSTRUCTION` from #57327 to allow building prerequisites recursively

TODO:

- [x] migrate `ACT_FILL`
- [x] add byproducts to dig/mine down and constr_pit_underground
~maybe pass the actor to `pre_special`s too in order to fix being able to spot traps with the construction direction prompt~ this PR is already enormous

#### Describe alternatives you've considered
Various hacks to make the dig activity properly pausable (ex: spawning fake items to mark the activity status)

#### Testing
Two new unit tests for point 4 above

`iuse` digging from shovels should not be significantly different from before

Exhuming graves is still bad for morale, etc

#### Additional context
This looks pretty scary and risky for 0.G, but most of the code was just moved around and/or deduplicated. I think we should be safe thanks to the test units, but I'm not married to getting this into 0.G

### CODE REVIEW

**Comment by andrei8l** [comment]
Not sure why autocalculated blueprints now demand soil for digging

**Comment by FayFlightee** [comment]
Oh thank goddess someone is doing this.
Thank you, construction (if someone wants them for some reason... Well I do) is finally WAY better. Not faster, but better.

**Comment by andrei8l** [comment]
> Not faster, but better.

Let me know if I made it slower though.

**Comment by andrei8l** [comment]
The old digging activity had a small novel as inline documentation for hardcoded values that I've now [removed](https://github.com/CleverRaven/Cataclysm-DDA/pull/57466/commits/98c75f1de5ad8d46cdae3942ebb5b2ff106461c3#diff-99adfdaa9690fab771878f30cd5fe3b30b0d4e87f994e1d4176cf3331fcd906fL2790). Not sure if I should move it somewhere instead, or where.

**Comment by kevingranade** [comment]
The documentation needs to be persisted somewhere, into a file in docs/ if nowhere else makes sense.

**Comment by andrei8l** [comment]
Thanks for merging.

**Pull request merged**
