### PR TITLE
[WIP] Flatter vehicle control menus

### LINKED ISSUE #24802: Allow electronics management from top-level vehicle menu
Game version: 0.C-30348

Operating system: Win7

Tiles or curses: Tiles

Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

A small quality of life issue. Currently any management of electronic devices in a vehicle requires one to first enter relevant menu and then turn on/off required device. Previous versions, where all electronic devices and their state were immediately available upon interaction with the vehicle worked just fine without requiring one to enter any submenus. Now, if one often turns on/off devices, there's plenty of additional keystrokes for hardly any benefit as even pretty huge, loaded with electronics vehicles should be relatively easily contained in said menu given how much space an average screen offers.

Ticket mostly in reference to stationary installation one doesn't drive around as an actual vehicle (base workstations and similar) where one cannot activate electronics without either choosing "control vehicle" or "control multiple electronics first".

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary

SUMMARY: None

#### Purpose of change

Vehicle menus are sprawling into nested menu trees which are (imo) hard to navigate and reason about;
Also some menus close immediately, others like electronics allows setting a few things at a time
There's also 2 very similar menus - the examine tile menu and control vehicle one, former nested-opens the latter too

This patch makes them flatter and allow access to functions with less keystrokes/eye movements

#### Describe the solution

- [x] Merge both menus into vehicle::interact_with - this menu then looks up which menu items to expose
- [x] Flatten the menu where it makes sense - fixes #24802
- [x] Move hardcoded hotkeys from vehicle::interact_with into keybindings json file
- [x] Avoid closing menu where it makes sense; e.g. no activity is started or no turn-passing feedback from the action is expected
- [ ] Resolve hotkey conflicts due to flatter-er but longer menus
- [ ] Consider removing some hotkeys - E.g. stuff like washing machine doesn't really deserve a hotkey by default - opening post apocalyptic laundry shop seems unlikely
- [ ] Split forming the menu into sections that make sense - engine stuff, turrets, utilities etc similar to ECU section
- [ ] Move stuff out of the menu and into functions as possible - e.g. put engine shutdown sounds somewhere saner

##### Make sure menu opens/closes/operates sanely and safely for:
- [x] Normal controls
- [x] Controls with stuff on top like towel hangers
- [ ] Remote controls - interacting with most stuff/parts shouldn't be available

#### Testing

Unfortunately this is a UI change where manual testing is needed
TODO: Write out a scenario once I'm closer to wrapping this up

#### Additional context
Menus for an RV's controls tile;
Examine tile menu on left, ^ menu while driving on the right (selection defaults to "Stop driving" if available)

image

### CODE REVIEW

**Comment by mlangsdorf** [comment]
I changed the title because "vehicle interaction menu" has a specific and different meaning than the sense used in the original title.

**Comment by dchieh222** [comment]
How is this going?

**Comment by irwiss** [comment]
It's mostly ready except for LGTM bot complaining about something I haven't traced yet, but needs testing, I'm a bit busy with studies atm so it'll take me a while unfortunately

**Comment by irwiss** [comment]
I'll get back to this once I get some free time back, or if someone feels like they can take over - though rebasing this late will be a chore

**Pull request closed without merging**
