### PR TITLE
Adding clip on storage pockets

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "extra encumbrance pockets and related features"

#### Purpose of change
Implements #52512 

#### Describe the solution
~Doing this I also found a few bugs with grab which I'm going to make PR's for. Ripoff from this wont work correctly until those are squashed.~ 

To do:

- [x] make noise function
- [x] add some carabiner pockets
- [x] min_item_length
- [x] extra encumbrance
- [x] ripoff
- [x] make best_pocket have high encumbrance pockets as low prio

On the code side this isn't too involved. There are now the additional pocket entries specified in #52512 they are handled as one would expect. There is now a call in game to make sound from the items, encumbrance is added in a similar way to ablative plates, and grab escape now has rules for losing items. 

Only additions that aren't laid out in the original issue are I've added some rules so "bad" pockets are selected less frequently for "best_pocket" so you don't put something in a 10 encumbrance pocket.

On the JSON side I've standardized the added pockets to the following forms primarily based on what I-am-erk laid out:
Tucked pocket - stuck behind your back very encumbering and uncomfortable. Really nice backpacks just wont have one of these since they rely on tightly balancing and distributing weight which requires the pack to be tight.
```json
        "//": "tucked against back",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "5 L",
        "max_contains_weight": "4 kg",
        "max_item_length": "150 cm",
        "min_item_length": "60 cm",
        "moves": 200,
        "extra_encumbrance": 10,
        "ripoff": 3
```
Carabiner Pocket - clipped to the back of the backpack. Some encumbrance but can handle quite long tools. Makes noise when you move. 
```json
        "//": "carabiner pocket",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "5 L",
        "max_contains_weight": "6 kg",
        "max_item_length": "120 cm",
        "min_item_length": "40 cm",
        "moves": 150,
        "extra_encumbrance": 3,
        "ripoff": 2,
        "activity_noise": { "volume": 8, "chance": 10 }
```
Waterbottle Pocket - holds a plastic water bottle or something else similar, added it to some of the more basic packs
```json
        "//": "waterbottle pocket",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "510 ml",
        "max_contains_weight": "1 kg",
        "max_item_length": "12 cm",
        "min_item_length": "7 cm",
        "moves": 80,
        "ripoff": 2
```
Strapped Pockets - very securely holds tools and guns. Can't be as long as carabiner clips but much more secure. This is an abstraction for sliding items between compression straps, using a daisy chain or things like ice axe loops. 
```json
        "//": "dedicated tool loops. either a daisy chain, hooking to compression straps, or ice axe loop",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "4 L",
        "max_contains_weight": "6 kg",
        "max_item_length": "100 cm",
        "min_item_length": "40 cm",
        "moves": 300,
        "extra_encumbrance": 1,
        "ripoff": 5
```
Duffel Slipped - an item slipped under the carrying straps of a duffel bag and poorly secured. Very easy to slip out / fall off and difficult to maneuver while having.
```json
        "//": "items slipped under the top of a duffelbag not well secured",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "4 L",
        "max_contains_weight": "6 kg",
        "max_item_length": "100 cm",
        "min_item_length": "40 cm",
        "moves": 80,
        "extra_encumbrance": 5,
        "ripoff": 1
```

Once #53114 goes through I would also like to add the modular functionality to the more military backpacks. So you could have tool loops or molle pouches on the sides (with tool loops using the new stuff from this). so for now things like the [MOLLE pack](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi.ebayimg.com%2Fimages%2Fi%2F291828450695-0-1%2Fs-l1000.jpg&f=1&nofb=1) will suffer since the big pockets on the sides mean you can't tuck items there. 

#### Testing
image

#### Additional context
here is the spread sheet of all of the items changed and what was added to them: 

Storage Item | Waterbottle Pocket | Tucked Pocket | Carabiner Pocket | Strapped Pocket | Duffel Slipped | Reference Image
-- | -- | -- | -- | -- | -- | --
backpack | TRUE | TRUE | 1 | 0 | 0 |  
backpack_hiking | FALSE | FALSE | 2 | 2 | 0 |  
backpack_tactical_large | FALSE | FALSE | 3 | 0 | 0 | https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.D22rJ7trd1E5QVJtRjCFNQHaHa%26pid%3DApi&f=1
bigback | FALSE | FALSE | 0 | 2 | 0 | https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FHTB1kucnQpXXXXcQXFXXq6xXFXXXK%2F65L-5L-Large-capacity-NylonWaterproof-Backpack-Outdoor-Hiking-Camping-Backpacks-for-Man-Women-Sports-Bag-High.jpg&f=1&nofb=1
boxpack | FALSE | TRUE | 1 | 0 | 0 |  
daypack | TRUE | TRUE | 1 | 0 | 0 | https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.ems.com%2Fon%2Fdemandware.static%2F-%2FSites-vestis-master-catalog%2Fdefault%2Fdw22b97b3e%2Fproduct%2Fimages%2F2007%2F879%2F2007879%2F2007879_203_main.jpg&f=1&nofb=1
duffelbag | FALSE | FALSE | 0 | 0 | 1 |  
makeshift_knapsack | FALSE | TRUE | 0 | 0 | 0 |  
molle_pack | FALSE | TRUE | 2 | 0 | 0 | https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi.ebayimg.com%2Fimages%2Fi%2F291828450695-0-1%2Fs-l1000.jpg&f=1&nofb=1
rucksack | FALSE | TRUE | 3 | 0 | 0 | https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.qiannipicture.com%2Fpic%2FUploadfile%2F6%2FSKU148450%2FD893139D93839ECA9BFCD253932623D2CBC8D55383D293CB369BD202CA9ACB9CCE9E73CC0DCA9CC69D36F68F97BAF5CE23.jpg&f=1&nofb=1
travelpack | TRUE | FALSE | 0 | 2 | 0 | https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.webshopapp.com%2Fshops%2F24973%2Ffiles%2F170563211%2Flowe-alpine-at-voyager-5515l-travelpack-anthracite.jpg&f=1&nofb=1
survivor_duffel_bag | FALSE | FALSE | 0 | 2 | 1 |  
survivor_pack | TRUE | FALSE | 2 | 1 | 0 |  
survivor_rucksack | FALSE | FALSE | 3 | 2 | 0 |

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I think a majority of backpacks could have an extra encumbrance pocket. Leather backpack shouldn't, nor should a runner's pack or the novelty giant backpack. A military or hiker's pack should have several. IMO those would be enough to start, then when it's tested we could put out a call for some folks to add a few more.

Not necessarily for this PR: 
- Depending on user experience we may want to be able to examine the item and toggle 'strap things to the outside' on or off, so your low-encumbrance pack stays low encumbrance.
- We may want to mark items in rip-off pockets separately in inventory. Like, if the normal 'contained in this item' prefix is a `>` symbol, then `!>` for "contained in a rip-off pocket" would help players to know the item is at risk of getting pulled off by a zombie.

**Comment by bombasticSlacks** [comment]
alright if every back pack (or just about) will have a really really bad pocket I'll have to also update the "best_pocket" algorithm to try to avoid high encumbrance pockets.

also I was in general going to make most of the pockets holsters (single item only) since it leads to less weirdness.

I'll put the bad pocket on some of the usual suspects that drop a lot and a carabiner pocket and then focus on the high end packs and bespoke packs for multiple more functional pockets really designed to hold tools and guns.

**Comment by bombasticSlacks** [comment]
alright I did all the backpacks at least that are in storage and bespoke_storage I might have missed something in tool_armor or some other file but this should be a good starting point

**Comment by Shodan14** [comment]
Shouldn't the daypack also have a strapped pocket? Isn't that what the elastic straps are for on the example one?

**Comment by bombasticSlacks** [comment]
I didn't think it would at the weight limit that I had set for them in general (if you've ever tried to hook something on those elastics they aren't particularly strong) I'm sure someone could get one added with modified values though!

**Comment by Paragonid** [comment]
@bombasticSlacks hiking backpack now has 2 pockets with "base moves to remove item: 3". is it a bug?
image

**Comment by bombasticSlacks** [comment]
A little sleuthing seems to show those were added 2 years ago and they might be older than that. The last time those pockets were audited was https://github.com/CleverRaven/Cataclysm-DDA/pull/50841 4 months ago. I feel you are correct it is too low but it's a seperate problem unrelated to what changed here.

**Pull request merged**
