### PR TITLE
Add teleport dialog function and new portal storm effect

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Add more power to dialog system
Add portal storm effect of getting teleported back to where you were, for a few times.

### CODE REVIEW

**Comment by Termineitor244** [comment]
Awesome! It this gets merged first, can I call this EOC for the portal traveler effects? it would be a nice touch as it is already.

**Comment by Ramza13** [comment]
> Awesome! It this gets merged first, can I call this EOC for the portal traveler effects? it would be a nice touch as it is already.

Sure.

**Comment by adorableNYNICG** [comment]
Sorry for making late question...
Is it possible to teleport to outside of reality bubble? It seem teleport fails if I attempt to go long distance.

**Comment by Ramza13** [comment]
> Sorry for making late question... Is it possible to teleport to outside of reality bubble? It seem teleport fails if I attempt to go long distance.

It should be, so that sounds like a bug.  I'll add it to my todo list

**Comment by Ramza13** [comment]
> Sorry for making late question... Is it possible to teleport to outside of reality bubble? It seem teleport fails if I attempt to go long distance.
Fix submitted. #53563

**Comment by adorableNYNICG** [comment]
Downloaded cdda-experimental-2021-12-21-0353 and confirmed that bug was fixed. Thank you for solving this problem.

**Pull request merged**
