### PR TITLE
Heavy close helms

### LINKED ISSUE #65904: Custom close helms are somehow worse than greathelm in both protection and encumbrance
### Is your feature request related to a problem? Please describe.

In game, custom steel close helms are supposed to be pinnacles of plate head protection, taking days to craft even with all proficiencies, yet even the best one (tempered steel close helm) has next protection values for head:
<html>
<body>

Thickness | 1.3mm | 1.0mm
-- | -- | --
Coverage | 100% | 1%
Bash | 13.75 | 1.00
Cut | 13.75 | 3.00
Ballistic | 9.38 | 2.00

</body>
</html>

Compared to greathelm's values:
<html>
<body>

Thickness | 2.5mm | 2.5mm
-- | -- | --
Coverage | 100% | 100%
Bash | 15.00 | 2.50
Cut | 15.00 | 7.50
Ballistic | 7.50 | 5.00

</body>
</html>

Greathelm can be hammered out in less than a day from scrap steel, if you don't know.

The steel on close helms is too thin. Most helmets sold today (and made historically, too) are at least 1.5 mm thick, reaching up to 2.5 mm. And if the custom cuirasses have the metal thickness of 4 mm in game, so why the head has to have THAT much lower protection?

The other problem is that despite greathelm IRL sits on the wearer's shoulders over the armor and doesn't allow to rotate itself with the head (unlike the close helm, that can turn with the head and rests on the shoulders under the gorget), it has lower head encumbrance value of 49 vs 54 of close helm. I repeat, a helmet that forces you to turn with your whole body to see a threat that is not directly in front of you allows you to react to threats better than a helmet that can turn with your head.

Finally, in-game armet, that is pretty similar in construction to close helm has neither of the close helm's drawbacks, as it has both good thickness and reasonable encumbrance.

Also, why close helm has conductive flag despite (supposedly) having a leather lining? And why its leather layer has only 1% coverage? Same goes for many other custom-built armors (like nomad plate armor, despite it has 100% coverage with 3 layers of fabrics, it's still conductive, and custom plate armors all have 1% leather coverage for some reason), though.

### Solution you would like.

1. I think copying armet's material thicknesses and head encumbrance values would be reasonable. 
2. Increase crafting cost in metal by about 1.5-2 times. 
3. Maybe make a light close helm variation with 1.5 mm thick plating.
4. Warmth value of close helm should be increased to 15. 0% breathability still applies.
5. custom plate armor pieces with leather in their recipes should get 90-100% leather coverage with 2 mm thickness
6. Custom plate armors should have their conductive flag removed, unless the leather/textile is to be be removed from their recipe (which is unrealistic, because padding is important). 
7. Warmth value of close helm should be increased to 15. Breathability value of 0% still applies, so it should be essentially a nerf for wearing one in warm weather.

### Describe alternatives you have considered.

1. Nerfing non-custom-made plate helmets into ground. Neither fun nor too realistic.
2. Having a top-of-the-line custom-made helmet overmatched by a tin can cobbled together from scrap metal.

### Additional context

References:
1. Commercially available close helm with known weight and thickness (16 gauge steel is about 1.5 mm): https://www.by-the-sword.com/p-42205-european-close-helm-16-gauge-steel.aspx Some historical examples are even heavier, and thus likely to be thicker.
2. Another commercial example: https://www.eviltailors.com/en/helmets/42789-close-helmet-ca-1520-16-mm-steel.html
3. Historical cuirassier helmet with known weight: https://www.metmuseum.org/art/collection/search/26524
4. Historical tourney helmet with known weight: https://www.artic.edu/artworks/147140/gorget-and-close-helmet-for-foot-tourney-at-the-barriers

None of those have less than 1.5 mm thickness, even those with unspecified thickness are too heavy to have such thickness.

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Content "Adds thicker, heavier close helm variations"

#### Purpose of change

Relevant to #65904. Greathelm and other ungraded steel helmets still need a revision, though.

Adds a way for survivor to create more competitive, if heavy, head armor. Current close helm had thickness of light plate extremity pieces and provided a critical weakpoint when used with heavier plate sets. Head was historically the body part that had the most attention in terms of protection, so it makes no sense to not have heavier plate head protection options.

#### Describe the solution

Renames current close helm into light close helm.

Adds two new variations of close helm: medium and heavy. Medium provides same protection as medium plate extremity pieces, heavy helmet provides same protection as heavy plate extremity pieces. Weight increases by 1 kg per protection tier increase, compared to (now) light close helm.

#### Describe alternatives you've considered

1. Rebalancing existing ungraded steel helmets (needs to be done anyways in the future).
2. Leaving custom plate helmets underwhelming.

#### Testing

Loaded in, spawned armor, used it, checked recipes.

The renaming and essentially restatting of plate helm will very likely cause it to gain 0.5 mm of steel if you crafted one before playing with these changes, but it will conserve naming consistency, as current close helm is renamed into light close helm both in ID and visible name, being lighter than both new helmets.

#### Additional context

None.

### CODE REVIEW

**Comment by Dan1ss1mo** [comment]
This is technically not directly relevant to you're pr, but it would be neat to also have a double visor on a close helmets. Would add a bit of extra flexability, so you can, for exaple, remove upper visor for shooting, but still keep you're head mostly protected

**Comment by randomtyper** [comment]
> This is technically not directly relevant to you're pr, but it would be neat to also have a double visor on a close helmets. Would add a bit of extra flexability, so you can, for exaple, remove upper visor for shooting, but still keep you're head mostly protected

Well, visor lifting in game only opens mouth and eyes (while leaving the rest of head protected), and adding separate actions for lifting eyepiece and lifting facepiece in general will need adding another pack of variations, all just to have ability to protect the mouth. I'd rather keep that simple. At least, for now.

**Comment by Dan1ss1mo** [comment]
It seems that you defined them as nested without actually adding nested groups for them, which cousing an error on checks

**Comment by randomtyper** [comment]
> It seems that you defined them as nested without actually adding nested groups for them, which cousing an error on checks

Yup, gonna fix that.

**Comment by randomtyper** [comment]
Okay, what did I screw up now?

**Comment by randomtyper** [comment]
Hm, loaded into game with the changes, all is fine...

**Comment by randomtyper** [comment]
@Drew4484, I hope you don't mind me tagging you here. Should be ready for merge, or at least a review.

**Comment by Drew4484** [comment]
> @Drew4484, I hope you don't mind me tagging you here. Should be ready for merge, or at least a review.

What do the respective light/medium/heavy encumbrances work our to with these changes?

**Comment by randomtyper** [comment]
> > @Drew4484, I hope you don't mind me tagging you here. Should be ready for merge, or at least a review.
> 
> What do the respective light/medium/heavy encumbrances work our to with these changes?

Light close helm is a pre-PR close helm with a rename, 54 encumbrance. Medium is 61 and heavy is 68. 7 encumbrance per additional kilo compared to original helm. The head encumbrance caps out for normal-sized character at 72 for XL heavy close helm. The rest of variations are arrayed in-between these values (72 and 54). The helmets are supposed to rest on the gorget that lays on the shoulders anyways, so weight would not matter as much as for the helmets that rest on the head.

Thought you could guess the calculation results, though. I only used the in-game encumbrance auto-calculator with the smae modifiers as original close helm (restricts neck, well-balanced) and only factor that could change the encumbrance was weight.

**Comment by Drew4484** [comment]
> 

Thanks, I'm on my phone not at my machine to test it out. Looks good.

**Pull request merged**
