### PR TITLE
NPC Interaction Tweak

### PR DESCRIPTION
**Pull request by LordMadness**
#### Summary

Interface "NPC Interaction tweak"

#### Purpose of change

A little Quality of Life change when using the "There's something I want you to do" (TALK_ALLY_ORDERS).
Whether you are in or outside a Camp, the NPCs shortcut for _"Let's talk about your current activity."_ and _"Let's go."_ change.
These are frequently used, and the shortcut change is a bit annoying.

To address that, I've put all conditional interactions (which are all related to the Camp) inside a fixed interaction _"Let's talk about the camp."_

Additionally, the "We need to abandon this camp" didn't have any confirmation validation from the player and would instead simply abandon the camp. I consider this decision too big to be left open for accidents without confirmation, so I've added a confirmation request.

#### Testing

Simple rearrangement. No issues were found.

#### Additional context

new approach

### CODE REVIEW

**Comment by actual-nh** [comment]
There does not appear to be any change currently.

**Comment by LordMadness** [comment]
> There does not appear to be any change currently.

I was struggling with GitHub. It should work now. I'll be uploading screenshots to show the change.

**Comment by actual-nh** [comment]
Travis check was canceled for some reason?

**Comment by Jamuro-g** [comment]
am i looking at your screenshots the wrong way or is the quit dialog option ("lets go") now in the middle of all the other options?
shouldn't that one always be at the bottom?

**Comment by PatrikLundell** [comment]
@Jamuro-g The logic was to always place the fixed options first and the variable ones after that, which causes the "let's go" option to appear in the middle when there are optional ones available.

I agree having the hot keys jump around is annoying, resulting in the wrong orders being given because of the key not meaning what it used to, so rearranging into a fixed and a variable section is a definite improvement.

I'd prefer the "let's go" option to be at the top (alternative 3) because it will then both be at a fixed position shortcut wise and in the same position visually (at the top).

**Comment by LordMadness** [comment]
Thanks, everyone. After reading the commends and giving it a night of thought, I've changed my approach to it, I'm very quite satisfied on how it is now. The screenshot has been updated.

**Comment by PatrikLundell** [comment]
By the way, does this also take quests into consideration, pushing those to the end?

Collapsing the camp related dialogue looks good,through.

**Comment by LordMadness** [comment]
> By the way, does this also take quests into consideration, pushing those to the end?
> 
> Collapsing the camp related dialogue looks good,through.

The quests is in a different block of code, these changes I did was specifically in the TALK_ALLY_ORDERS, but from the looks of it, it's not conditional and would always show up in the options, even the NPC has no quests for you.

**Comment by PatrikLundell** [comment]
That's not the part of the quest dialogue I meant. If you do have an open quest that companion will have a dialogue option to report that it has been done (including lying about it), and that option is available only of you have an outstanding quest, and also pushes the hot key for the subsequent dialogue options one step downwards.

Anyway, dealing with that seems to be out of scope for this PR, judging by your answer.

**Pull request merged**
