### PR TITLE
[CR]Minor changes to zombie children

### PR DESCRIPTION
**Pull request by Coolthulhu**
Moved the kids to a new file, for ease of maintenance.

Some number tweaks:
- Evolution time halved to 14 days. Kids are far weaker than the evolved adults (that spawn on start anyway) and so can appear earlier
- Kids with night vision above day vision changed to 10/10 vision. Short day vision range is currently bugged.
- Daytime kids, except unevolved ones, got 5 night vision
- Anklebiter got speed increase. It runs a tiny bit faster than player walks
- Waif got a dodge buff (1->2) and minor cut armor
- Sprog gets a dodge nerf (3->2), since it can be hard to escape from it and it can block the way. We have no charge/push through maneuver, so something this small shouldn't block the way too often

Finally, added kids to monster groups:
- Upgraded zombies
- Park, the playground version

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Sproglodyte is a combination of 'sprog' and 'troglodyte' as in *Pan troglodytes*.

**Comment by Coolthulhu** [comment]
> Both paint a far more vivid mental image than boring names like 'snot' or 'skippy'.

Snotgobbler is a bit too... "icky". Descriptive is one thing, but this is bodily functions. It would be like describing boomer's vomit as chunky or something like that.

Sproglodyte is not descriptive. "Troglodyte" means first and foremost a cave dweller, which goes against the critter's jumpy nature.

**Comment by mugling** [comment]
I'd prefer sproglodyte over skippy. but agree we should consider changing snotgobbler for similar reasons to @Coolthulhu. That said I think we need a better name than snot however.

**Comment by Coolthulhu** [comment]
Hence the [CR]

Those names aren't final or anything, I just wanted to change those two, because of the reasons mentioned above.

**Comment by pisskop** [comment]
hmmmm. . . . .

jumpy
dutchy
sugarfiend
brat <<--
leghugger

Sproglofyte does onjure up a little disney caveboy hopping along with a hunched back on all 4s.

**Comment by mugling** [comment]
Bounder is quite good

**Comment by kevingranade** [comment]
Please drop the rename from this PR as it seems to be the only
controversial change, we can discuss changing its name again ad nauseum in
a different PR.

**Comment by Coolthulhu** [comment]
Reverted name change for now

**Pull request merged**
