### PR TITLE
Pirate Captain Profession.

### PR DESCRIPTION
**Pull request by Killer-Kat**
Adds pirate captain profession, starts with a sword and 4 flintlock pistols but also has an alcohol addiction. (Note this is my first time, I tried to follow the guide I hope I'm doing it right)

#### Summary
Content "Adds Pirate Captain Profession"

#### Purpose of change
Thought it would be fun, in a similar vein to the medieval peasant profession. Would be great for a deserted island start.

#### Describe the solution
Adds Pirate Captain profession.

#### Describe alternatives you've considered
Adding different types of pirates (figured that would be excessive) adding other professions (maybe later, pirate was fun to put together), making a mod (Unsure if a mod that adds a single profession would be worthwhile)

#### Testing
Created Pirate captain character, if you have low strength you will be overweight due to all the pistols.

#### Additional context
If you love to sail the sea then you are a pirate.

### CODE REVIEW

**Comment by Killer-Kat** [comment]
I have been having a lot of fun thinking of characters and then manually making them via debug when I realized, why not add them. I didn't see style rules about historical characters, but I don't know if I just missed them.

**Comment by Karol1223** [comment]
This really isn't a profession that fits basegame whatsoever.

**Comment by Maleclypse** [comment]
> I agree that this does not fit into the base game. Maybe crazy cataclysm or another mod?

I'd be happy to have this in Xedra Evolved.  That mod has a lot more room for dimensional seepage.

**Comment by Killer-Kat** [comment]
I am going to move this to my own mod. I have a lot of fun profession ideas so I think its best if I just make a mod that can house them all.

**Pull request closed without merging**
