### PR TITLE
Preparation for using typed tripoints consistently

### LINKED ISSUE #71852: The coordinate system set design does not seem to be consistent with the implementation
### Describe the bug

The theoretical description of coordinate systems to be used (POINTS_COORDINATES.md) clashes with the code implementation (which is currently largely untyped).

The same operations are used to modify tinymaps as well as regular maps, even though the former clearly uses very local coordinates (matching the description of tripoint_sm_ms), whereas the latter uses a local coordinate system based on the current map, which corresponds to tripoint_bub_sm. Both of these would, however, fit the more generic tripoint_rel_sm description.

Edit: It's actually worse than this, as tinymaps are anchored at a tripoint_abs_sm (through the `load` operation inherited from map), but actually consists of 2*2 submaps, and so use coordinate ranges appropriate for tripoint_omt_ms, and most, probably all, usages actually project a tripoint_abs_omt to tripoint_abs_sm for the call.

You need the map to be able to be shifted by a single submap for the reality bubble usage, but it's questionable whether there actually is any use for the submap granularity for the tinymap use. A submap coordinate misaligned with the omt grid is likely an error. If there is a need for an actual submap granularity for "quick" manipulation, a micromap class consisting of a single submap would probably be a better choice.

### Attach save file

N/A

### Steps to reproduce

Examine usages of map.h operations on both "normal" maps and tinymaps. Note that the coordinates used for the former usage would usually use tritype_bub_ms coordinates when those are available, while the "same" tinymap operations restrict the coordinates to fit within the boundaries of that map.

### Expected behavior

Either:
- Use a more generic relative location type (tripoint_rel_ms) throughout and ditch the tripoint_bub_ms, tripoint_omt_ms and tripoint_sm_ms, or
-  Make map and tinymap use different coordinate types (when typing is implemented), with tinymap using tripoint_omt_sm for its `load` operation and tripoint_omt_ms for its relative operation. Get rid of tripoint_sm_ms unless there is an actual use for it (such as a potential future micromap that operates on a single submap).

### Screenshots

_No response_

### Versions and configuration

N/A. It's a deep rooted design issue.

### Additional context

I ran into this when trying to typify item_location.h by getting rid of the `tripoint position()` operation in favor of `tripoint_bub_ms pos_bub()`.

Longer description:
Introduction of tripoint_bub_ms overload operations for tripoint ones resulted in failures to compile code due to ambiguity about how to interpret `{ x, y, z }` coordinate specifications, and nailing them down as tripoint_bub_ms would definitely be inappropriate (although it would be the naïve "obvious" "convert everything" choice).

Would it be possible to implement the second "Expected behavior" option by renaming the current map class into an abstract_map class that provided all the operations required for both implementations as protected operations and then define map and tinymap as derived classes that provided the appropriate subset of the operations as their operations?
You might have the abstract_class provide the untyped operations as public ones as a temporary measure until they can be removed, rather than duplicating temporary operations over both derived classes.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Fix #71852
i.e. prepare for a usage of typed points and tripoints for coordinates in a consistent manner.

#### Describe the solution

Separate tinymap's set of operations from map's set by inheriting map privately into tinymap. This makes map's operations unavailable for usage with tinymaps, which means you cannot use the typed operations using the wrong type from map.
This has had a knock-on effect where operations in other files have had to be split into map and tinymap ones.
There are essentially two places where splitting wasn't really feasible, and that's the mapdata struct and operations pointed to from recipes, so those usages unfortunately requires casting. It's probably possible to change the code to deal with this, but it's probably not worth the effort and added complexity.

#### Describe alternatives you've considered

- Abandon typed usage completely.
- Use unspecific tripoint_rel_ms throughout and ditch tripoint_bub_ms and tripoint_omt_ms. I don't see any usage for tripoint_ms_sm in the current code base regardless until a potential micromap operating on a single map square is introduced.

#### Testing

It compiles and loading a save doesn't result in any unexpected errors (expected ones are stuff no longer fitting in pockets, complaints about overmaps no longer supported etc.). Note that there should be no change in functionality as the whole set of changes should be a rearrangement with no functional effect.

#### Additional context

I've failed to find a syntax to allow me to make casting of tinymap to map accessible to usages of tinymap. If there is a syntax for it I'd be grateful to be told what it is.

### CODE REVIEW

**Comment by akrieger** [comment]
Where exactly do you need this cast syntax? cast_to_map() doesn't work?

**Comment by PatrikLundell** [comment]
`cast_to_map` works, but I was looking for the less clunky option of reexporting the native casting mechanism.
However, if experts think `cast_to_map` is acceptable I'm satisfied with that.

**Comment by PatrikLundell** [comment]
Thanks for the advice!

It does indeed obfuscate things. I was hoping to be able to use explicit casting while blocking the implicit one.

**Comment by Maleclypse** [comment]
so does this have more changes coming to it or is it ready for merge as is?

**Comment by PatrikLundell** [comment]
I'm not planning any more changes to this PR, so it's ready.

**Pull request merged**
