### PR TITLE
[Magiclysm] Goblin encampment / orc village revamp + additions

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Goblin encampment / orc village revamp + additions"

#### Purpose of change

With the setting of Magiclysm as "modern world + magic + fantasy species," the existence of goblin encampments and orc villages raises a lot of questions:

1. Where did they come from? Why wasn't the army deployed to deal with the man-eating armies of the Dark Lord Sauron that are encamped in between suburban New England towns?
2. Goblins were part of pre-Cataclysm society, but what about orcs?  Have there just always been orcs eating people in the wilderness?
3. Where did they get all of this medieval gear to outfit themselves with? If they're a parallel society with a warrior aristocracy who maintained their traditions, see 1.

#### Describe the solution

Rework quite a lot:

- [X] Replace the various goblin monstergroups here and there with a single monstergroup that calls different entries, changing as the Cataclysm progresses.
- [X] Orcs are explicitly mutated goblins.  So are bugbears, which are being added.
- [X] Add bugbears
- [X] Rework goblin descriptions and add `feral_goblin_death_drops` to goblin warriors, slingers, and chieftains, indicating that these were people before the Cataclysm just like you.
- [X] Add goblin sorcerers that spawn rarely in the goblin monstergroup, as well as a nested location in the goblin encampment that could have spells or magical loot.
- [X] Add more nests to the encampment.  It could be more densely packed.
- [X] Allow goblins to spawn in the forest at night
- [X] Change goblin day/night vision so they're nocturnal
- [X] Add wargs, mentioned in one of the initial PRs for goblins but never implemented.  These serve the function of defending goblin locations during the day and howling to alert the goblins that there are enemies .
- [X] Rework orc and goblin drops to be more obviously improvised weapons with the occasional scavenged magical weapon. 
- [X] Reduce the frequency of orc villages spawning and rename them "goblin outpost"
- [X] Move the goblin encampment to spawn in the deep forest and move the goblin outpost to spawn in the forest.
- [X] Add an orc sorcerer to the goblin outpost
- [X] Add the existing but unused tamed troll to the possible goblin monstergroup.
- [X] Base goblinkin weapon attacks on the actual weapons they're using, including techniques.  If you used to let goblins surround you, it's probably a bad idea to do that now (and risk getting stunned by their cudgels).

#### Testing

Example of new goblin encampment with nests:

image

Balance is most as before--goblin warriors and slingers are dangerous in numbers but not individually, goblin leaders can be nasty if you get close with the new "attacks based on actual weapon damage" principle and now that goblins have the armor that their armor drops say they should have, but have no ranged attacks--the slow fire axe was almost a death sentence but using a shillelagh led to an easy kill.  Also, goblins are now nearly blind during the day, the same as player goblins. I also generally reduced their melee and dodge skill, since these are supposed to have been office and service workers six months ago.

Orcs and bugbears are both slightly more troublesome, but not insurmountable.  Wargs' main danger is that they'll alert nearby goblinkin during the day--while they're big and have nasty attacks, I easily took one down with the shillelagh.

Orc blood-mages are not themselves, dangerous, it's the buffs they put on other goblinkin that make them a priority target. Goblin thornweavers are the reverse--rather than speeding up nearby allies, they slow and poison you to make you get swarmed.  As always, shoot the mage in the head first.

Goblin camps no longer allow you to roll up with a rifle and leave with a truckload of +1 weapons, but if there are any mages there, they still have magical loot. There's also room for more nests with more interesting loot or items, but this is already almost 1500 lines.

#### Additional context

Why do feral goblins build villages and encampments when feral humans can barely keep themselves alive? Well, goblins and humans are different species and there's nothing to say that blob psychosis affects them the same way. Maybe goblins become more communitarian but only with other infected goblins--even non-infected goblins would be seen as outsiders and would be attacked.

I am planning to give goblins (and ravenfolk) the SOCIAL1 mutation once #70797 is merged.  Goblins might even get SOCIAL2, since it would fit them as portrayed here (when reverting to more instinctual behavior, they gather in groups).

The answer to "How did these encampments get built?" is that the goblins who went feral were wandering off into the wilderness and banding together to work on this in the months leading up to the Cataclysm (I wrote a snippet or two to this effect), and mostly people didn't notice because of the constant rioting and breakdown of society and because the goblins were off in the deep woods.

### CODE REVIEW

**Comment by ashGlaw** [comment]
If they're just large goblins, maybe orcs should be hobgoblins instead

**Comment by Standing-Storm** [comment]
> If they're just large goblins, maybe orcs should be hobgoblins instead

I wanted to use "hobs" for a kind of nature spirit (as per folklore), so figured that using hobgoblins as well would lead to confusion

**Comment by Naadn** [comment]
If the `mon_goblin_mage_poison_thorn_spell` is undodgeable, why it has miss msg?

**Comment by Standing-Storm** [comment]
> If the `mon_goblin_mage_poison_thorn_spell` is undodgeable, why it has miss msg?

If you have some way of gaining the UNCANNY_DODGE flag it can miss.

**Pull request merged**
