### PR TITLE
[Xedra Evolved] Hedge magic

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Xedra Evolved] Hedge magic"

#### Purpose of change

We've got a lot of powerful magic modded stuff in CDDA, but what about weak magic? Peasant village magic, the kind of magic people in the past thought worked? Hedge magic.

#### Describe the solution

Add some hedge magic to Xedra Evolved. These are the principles I'm using to develop it:

1. All hedge magic requires spell components, special conditions (being outdoors, finishing the ritual within an hour of noon, being on the shoreline, drawing blood, etc), or both.
2. Hedge magic does not use mana. It's the components and conditions that make it work, not the caster's personal power.
3. All hedge magic has the NO_FAIL flag. Either you have the appropriate circumstances and it works, or you don't and it doesn't.
4. Hedge magic has no spell levels, or rather, max level is always 1. You can't keep practicing your fire-calling charm until you can burn a whole house down, you use it to light tinder or you can't use it at all. 
5. Hedge magic mostly has minor effects, the kind of thing that modern technology is just better at. You can use the To Ward off Rain ritual or just carry an umbrella. You can summon a Witchlight or just use your smartphone. It's for fun and spooky flavor, not necessarily for making your character much more powerful (it would probably be very good Innawoods, though).  Not to say there won't be things that can only be accomplished by magic--for example, I'll probably put in long-distance scrying if I can figure out a good way to do it. 
6. Hedge magic does not do direct damage. It's "curse your enemy to suffer terrible luck" or "curse them with a wasting disease that will slowly kill them over a score of years" kind of magic, not the "rip out their heart from a distance" kind of magic. The closest I put in was "To Befuddle As the Thunderbolt" which causes a flashbang effect, but that a) only works outside and b) causes a flashbang, so a _lot_ of zombies are going to get curious what the racket is. 

#### Testing

The existing charms all work. Starting profession is selectable and has the appropriate charms.

At the moment there's no way to get these other than the starting profession. Since this is already 700 lines, I'll do a follow-up PR with some books or a cabin variant that has some recipes. 

#### Additional context

After all the work GuardianDII has done making a new magic system for Dreamer/Inventor etc., I thought, "You know, how would XE magic that just used the base system designed for Magiclysm work?" and so here we are.

Also my copy of _Jewish Magic and Superstition_ arrived like two weeks ago so maybe I should crack that open and put some stuff in XE synagogues.

### CODE REVIEW

**Comment by Rokharn** [comment]
Can be really useful for Innawood. How about ritual to create firestarters tool as well? Maybe ritual to create cold/warm air too can be interesting (like one from mom psychokinetic power). Some kind of bandages, mades by rituals (like ones from vitakinesis power) can be useful as well.

**Comment by Standing-Storm** [comment]
> Can be really useful for Innawood. How about ritual to create firestarters tool as well? Maybe ritual to create cold/warm air too can be interesting (like one from mom psychokinetic power). Some kind of bandages, mades by rituals (like ones from vitakinesis power) can be useful as well.

The two other ones I had an idea for were a ritual to make crops grow better and one to start fires (through the magic of EoCs I can make the ritual directly start a fire instead of making a tool that then starts the fire), so those will go in once I add more stuff

**Comment by Rabadash94** [comment]
It sounds like magic to turn items into single-use makeshift tools.

**Comment by Standing-Storm** [comment]
> It sounds like magic to turn items into single-use makeshift tools.

EoCs now let you produce just the tool effects instead of the tool (by spawning a tool and then immediately activating it), so when I make the plant fertility ritual it'll just immediately make magic fertilizer, activate it through EoC so you have to pick a place to put it, and then delete it afterwards in case you cancel choosing a location, so from the player's perspective it'll be "Do ritual" -> "Pick plant to fertilize" -> "plant grows better through magic"

**Comment by Standing-Storm** [comment]
Thank you Undo Last Commit for fixing VSC deciding to randomly delete the ammo.json file (!?)

**Comment by Maleclypse** [comment]
I love this. Thank you!

**Pull request merged**
