### PR TITLE
Buffed .50 BMG

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
It's now competitive with the .300 WinMag, and it's closer to reality.

### CODE REVIEW

**Comment by mugling** [comment]
I'm not sure this is a good idea from a gameplay POV considering how available 50BMG is versus 300 (think belts on vehicles).

**Comment by BorkBorkGoesTheCode** [comment]
I just realized the .50 has 700 recoil. That is waaay to low. I'm testing a change.

**Comment by mugling** [comment]
As above and in #19042 - we should determine what we are trying to achieve before we make ad-hoc adjustments

**Comment by fr1gid** [comment]
The .50 BMG is in an almost completely different class from the .300 WinMag, at least as far as damage goes. .50 hits much harder. The ballistic performance is 3850-4100ft·lbf  for the .300 WinMag and 13050-15000ft·lbf  for the .50.

Theoretically, .300 should be more common outside of army drops. Pretty much every gun store IRL will have it.

**Comment by mugling** [comment]
> As above and in #19042 - we should determine what we are trying to achieve before we make ad-hoc adjustments

**Comment by BorkBorkGoesTheCode** [comment]
Please close unwanted PRs if you have no intention to merge them. It saves contributor time.

**Comment by BorkBorkGoesTheCode** [comment]
Until you complete your project of removing the joule-to damage system from the game, the damage dealt by the 50 BMG remains an outstanding bug. This PR brought 50 BMG damage in line with GAME_BALANCE.md and had no code issues, yet you closed it.

**Comment by mugling** [comment]
The route your taking with this multitude of PR's is needlessly time consuming versus the actual benefit. We should be focusing development time on other more significant issues

**Comment by BorkBorkGoesTheCode** [comment]
Dude, you complained about unreviewable PRs, then stopped reading PR contents in favor of the summary.

**Comment by DracoGriffin** [comment]
@BorkBorkGoesTheCode if you'd like to complete this PR, I can re-open it for you. It was discovered by a user on Discord:
>[Dynamic] MP7A1 Today at 11:44 AM
Huh. Looking at GAME_BALANCE.md, it looks like .50 BMG damage is massively lower than it should be.

And looks like this PR was attempting to resolve that bug.

Please let me know, thanks.

**Pull request closed without merging**
