### PR TITLE
Gem stones part 1

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
 ```SUMMARY: Content "Adds new gem stones and some jewelry."```

#### Purpose of change
increase variety of items in the world.

#### Describe the solution
This is part one of another jewelry expansion.  I've added 14 precious gems, a group material type "gemstone", gold based dental grills for 12 gems (pearl and opal being unsuitable for mouth wear), and earrings for all 14 in gold, silver and platinum.

I've added them to some initial item groups.  item_groups for each type that are then used in the jewelry_furshop, jewelry_front and jewelry_safe groups.

#### Describe alternatives you've considered
I'm not using copper for these gems, but I'll get to it when I add semi-precious stones.

#### Testing
spawned in world, checked the looks-like entries, checked the item groups using the in game item_group debug.

#### Additional context
I'll be adding the same variations for necklaces, bracelets and some other jewelry types but this was already getting long.  A future PR will also need to include recipes and deconstruction entries.

More item_group integration will occur once I have the gemstone line of jewelry completed.

image
image

### CODE REVIEW

**Comment by Rail-Runner** [comment]
Could you utilize copy-from for those items? They really look very simillar to each other.

**Comment by curstwist** [comment]
Probably,  I've never used copy_from, I'll have to look into it.

**Comment by FuelType-Memes** [comment]
A 200ml pearl is HUGE! It would weigh around 0.5kg 🤣

I suggest you tweak some of the numbers for volume and weight

**Comment by curstwist** [comment]
> 
> 
> A 200ml pearl is HUGE! It would weigh around 0.5kg 🤣
> 
> I suggest you tweak some of the numbers for volume and weight

right, I'll fix it.  I based it off diamonds, which I now remember are also overweight.

**Pull request merged**
