### PR TITLE
[wip] fix food typos

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "Fix food typos in canned chicken and eggs"```
#### Purpose of change

as per [this spreadsheet](https://docs.google.com/spreadsheets/d/1n1roPzIsRvABg3Ry0q7SPxnUK_C0GR9cjK27m4cF9ok/edit#gid=1707455741), I made a couple typos that people on reddit caught. i fixed them.

### CODE REVIEW

**Comment by Photoloss** [comment]
Err, not going to fix powdered eggs and the resulting scrambled mess?

**Comment by KorGgenT** [comment]
powdered eggs aren't a typo.

**Comment by Photoloss** [comment]
What else do you call it when they have about a third of the calories the worst inputs would provide, destroy additional calories via NUTRIENT_OVERRIDE and [this](https://ndb.nal.usda.gov/ndb/foods/show/01133?fgcd=&manu=&format=&count=&max=25&offset=&sort=default&order=asc&qlookup=egg&ds=&qt=&qp=&qa=&qn=&q=&ing=) gives me 41.4kcal per 7g portion as opposed to the 27kcal set in-game? Boiled and scrambled eggs also use the (typo'd) value for chicken eggs as their baseline which does not align with the USDA database either.

**Comment by KorGgenT** [comment]
because of tests, gotta fix one piece at a time

**Pull request closed without merging**
