### PR TITLE
Capture pc

### LINKED ISSUE #57926: [ Feature Request ] PC knocked unconscious and captured
### Is your feature request related to a problem? Please describe.

Since we now have the ability to move player control to NPC followers upon death and the ability to move NPCs locations and gear, plus having Unique IDs for NPCs I think we are pretty close to being able to simulate instances when the PC is knocked unconscious and captured by either other NPCs,  mi-go and any other instances where that would be appropriate.  

### Solution you would like.

I would like for Mi-go to sometimes capture characters that they knock to zero hp and for those unique characters to be moved to empty mi-go prison cells somewhere on the overmap.   This would enable followers who weren't nearby to launch rescue missions or if an early PC is captured and the world isn't reset the new character in the world might encounter and rescue the PC.

### Describe alternatives you have considered.

Other alternatives I don't know about.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Leonkoithara**
#### Summary
Features "Player gets Abducted by monsters and Factions"

#### Purpose of change
Feature so that slaver monsters and Factions with sufficient motivation might try to abduct you instead of killing you directly.
Fixes #57926  

#### Describe the solution
This is a WIP and can change. Create map updates using EOCs to enslave PC and monsters use Spell to capture the player.

#### Describe alternatives you've considered
Hardcoded solutions but avoiding it since it would not be as flexible.

### CODE REVIEW

**Comment by kevingranade** [comment]
To be clear,  the final capture effect needs a branch where it checks if you have any eligible followers,  if you don't it would (optionally) spawn a NPC based on the player at the camp, and kill the player.  If there is an eligible NPC it would switch control to that NPC.

**Comment by Leonkoithara** [comment]
I think I misunderstood your comment initially but after some conversation in the discord and re-reading your comment. I would like to make a small change in that:

```
if some followers:
    transfer_control_to_one_of_them
else:
    if dice(1, 100):
        nearby_npc_hears_commotion_maybe_investigate
```

**Comment by Maleclypse** [comment]
> > To be clear, the final capture effect needs a branch where it checks if you have any eligible followers, if you don't it would (optionally) spawn a NPC based on the player at the camp, and kill the player. If there is an eligible NPC it would switch control to that NPC.
> 
> I think I misunderstood your comment initially but after some conversation in the discord and re-reading your comment. I would like to make a small change in that:
> 
> ```
> if captured:
>     if ask_continue_as_npc_false:
>         goodbye cruel world!
> if some followers:
>     transfer_control_to_one_of_them
> else:
>     if chance(20, 100):
>         nearby_npc_hears_commotion_maybe_investigate
> ```
> 
> Currently branch is still WIP haven't implemented the checks yet.

So you are saying that if a non follower NPC happens to be nearby on the overmap the pc gets the option to transfer control to that NPC to choose to investigate?  I’m not sure about that 100% but as long as it only has a chance to happen if you have no NPC followers I think that might be ok. But if you have followers you should always transfer to one of them.

**Comment by Maleclypse** [comment]
I hope you come back to this. I am excited for it!

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
