### PR TITLE
[WIP] New trait: Throwing Addict

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
```SUMMARY: Content "Added a new negative trait: 'Throwing Addict'"```

#### Purpose of change
Add a new negative trait worth 4 points that remove the use of bows and guns, and use throwing as the primary means of ranged attacks. Ranged weapons using pebbles and rocks are still allowed (slings and slingshots).

Throwing addict description:
While others have bows and guns, your only choice of ranged weaponry are thrown items, slings, and slingshots.

#### Describe the solution
Prevent the usage of the following with pseudo-witty remarks:
Finger lasers
All guns (including holster firing, and all bows since they're categorized as guns)
All bows (see above)
Turret usage from controls
Manual turret usage

Allow the usage of anything using ammo_types classified as pebbles and rocks. To my knowledge, they are the following:
Sling
Slingshot
sling staff

#### Testing
Extensively tested with firing finger lasers, guns, bows, and turrets.
I also tested throwing, slings, and slingshots. These are allowed.
Tested reach weapons to make sure they're left unaffected.

#### Notes
Previously called "No ranged weapons". It was semantically and descriptively inaccurate as pointed out by feedback. It has been changed to Throwing Addict.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Honestly this trait feel way too "game-y". I can't imagine IRL equivalent of it.

**Comment by CodeBandit** [comment]
> Honestly this trait feel way too "game-y". I can't imagine IRL equivalent of it.

It wasn't really a trait with IRL in mind. It's more of a "choose this so you can't use bows or guns" similar to how wayfarer denies use of vehicles. It's definitely more game-y since the goal in mind for the trait is player challenge and play diversity -not realism.

Other traits that are also "gamey" (personal opinion only, and not a comprehensive list): Animal empathy, deft, fleet footed, quick, gourmand, night vision, parkour expert, robust genetics, scout, genetic downward spiral, imperceptive healer, wayfarer etc.

**Comment by Brian-Otten** [comment]
I love the fact that we have some slightly "gamey" traits that let you mix up your gameplay, and this fits in well with those. Would make for a fun alternate run.

A thought i have that might make it feel slightly more thematic might be changing it to "no guns" instead of "no ranged weapons". Would go well with churl, or for characters that are somehow anti-gun.
In practice this means adding an exception for bows/crossbows in addition to throwing weapons.

**Comment by Siersha** [comment]
I agree with Brian-Otten that slightly gamey traits lead to some fun alternate runs. I feel this trait would be a great addition to the game.

As a counter point, I see OP's intent in denying bows along with guns (despite being thematically inconsistent). Bows and guns are ultimately different sides of the same coin, and one could just as easily opt for the other if one of them were "disabled".

**Comment by KorGgenT** [comment]
Is magic a "weapon"? does it make sense to disallow ranged attack spells as well?

**Comment by ymber** [comment]
This doesn't need a trait. If you want to play a character without guns you the player can easily do that without any game mechanic for it.

**Comment by FuelType-Memes** [comment]
> 
> 
> This doesn't need a trait. If you want to play a character without guns you the player can easily do that without any game mechanic for it.

You can play as vegan without traits too, but this removes even the possibility. Basically the same as Wayfarer

**Comment by CodeBandit** [comment]
> Is magic a "weapon"? does it make sense to disallow ranged attack spells as well?

I don't know how exactly ranged attack spells work, so I can't say for sure since I don't play with magiclysm. Do ranged attack spells require a weapon? Is that weapon in the gun category? If it is, then does it not use pebbles or rocks as ammo? If all of the above is true, then it is disallowed. The goal is only bows and guns. I can look into adding an exclusion if this is the case.

> This doesn't need a trait. If you want to play a character without guns you the player can easily do that without any game mechanic for it.

The traits illiterate (books), wayfarer (vehicles), squeamish (filthy clothes), and wool allergy (well, wool) are some other traits that disable some mechanics. They can all be categorized as "you can do that without a game mechanic". To a much lesser degree hoarder, nomad, pacifist, and rigid table manners could also fit that description.

**Comment by enaantd** [comment]
a way to make this trait plausible could be to rename it to "unable to aim". It could be seen IRL as some innate psychomotor limitation that prevents the player from anticipating where their projectile are going to go.
however, this would also remove the throwing possibility.

**Comment by CodeBandit** [comment]
> a way to make this trait plausible could be to rename it to "unable to aim". It could be seen IRL as some innate psychomotor limitation that prevents the player from anticipating where their projectiles are going to go.
> however, this would also remove the throwing possibility.
> EDIT: this could be combined with @Brian-Otten's suggestion, and have two new traits (one that blocks you from firearms exclusively, another that blocks you for anything aim-related)

I'm averse to completely being unable to aim. I feel it would remove far too much from the game and make some enemies completely un-beatable when they would otherwise be deal-able with through alternative means. An example would be turrets. With throwing, atleast you can inch closer while hiding behind a bookshelf and pushing yourself closer to peek around and toss whatever you like to. With throwing, grenades are also possible. It would also push it out of the scope of a 4 point trait, and i'd like to keep it that way.

I'm definitely not against a "guns only" trait, but that would be out of scope for this PR and need to be added in a different PR.

**Comment by CodeBandit** [comment]
Due to feedback, I have changed the name and description. It is now Throwing Addict, and description says the following:

While others have bows and guns, your only choice of ranged weaponry are thrown items, slings, and slingshots.

**Comment by Siersha** [comment]
> Due to feedback, I have changed the name and description. It is now Throwing Addict, and description says the following:
> 
> While others have bows and guns, your only choice of ranged weaponry are thrown items, slings, and slingshots.

This is definitely a big improvement over "No ranged weapons"! Atleast now, with the new name and description it's thematically consistent with your implementation. For what it's worth, it gives it a tie-in to IRL.

**Comment by Fris0uman** [comment]
Isn't it just a "give me point to play this throwing build I want to make" trait?

**Comment by CodeBandit** [comment]
> Isn't it just a "give me point to play this throwing build I want to make" trait?

You can play any throwing build you want regardless of this trait's existence though?

**Comment by enaantd** [comment]
> I'm averse to completely being unable to aim. I feel it would remove far too much from the game

You don't have to pick this trait at character creation, in the same way that you don't have to pick Wayfarer. I suggested this as I imagine some players would be interested in a "melee-only" challenge.

> and push it out of the score of a 4 point trait (which I would like to keep).

Why do you want to keep this specific score?

> Keeping throwing and other throwing related weapons is a big part of why I chose to go with excluding some things. It would give a niche use to slings and slingshots, and give throwing some mid to end game relevance. An example would be turrets. With throwing, atleast you can inch closer while hiding behind a bookshelf and pushing yourself closer to peek around and toss whatever you like to. With throwing, grenades are also possible.

I'm in favor of adding traits that encourage using the throwing skill, as long as they make sense.

My point is, @Brian-Otten's suggestion makes sense in real life as some people are opposed to or afraid of using guns. My suggestion would make sense for someone that can not aim at all. However I can't see why someone would be unable/unwilling to use a bow when they can use a sling (barring strength requirements of course).

If you can find a (valid) reason for this, I'd suggest adding another separate trait preventing from using bows and such, and you could have your run by taking these two traits (no guns + no bows). It would be a total of 3 traits (no guns, no bows, no ranged at all, the third being exclusive with the first two). As you said, the third traid is out of scope for this PR, I'm just sharing thoughts for the future.

**Comment by Siersha** [comment]
> You don't have to pick this trait at character creation, in the same way that you don't have to pick Wayfarer. I suggested this as I imagine some players would be interested in a "melee-only" challenge.

Understood. Please note above that I'm not averse to other traits, it's just not the goal of this PR.

> Why do you want to keep this specific score?

To keep compatibility with other high point challenge traits -namely fragile, imperceptive healer, and wayfarer.

> I'm in favor of adding traits that encourage using the throwing skill, as long as they make sense.
> 
> My point is, @Brian-Otten's suggestion makes sense in real life as some people are opposed to or afraid of using guns. My suggestion would make sense for someone that can not aim at all. However I can't see why someone would be unable/unwilling to use a bow when they can use a sling (barring strength requirements of course).

Just because I disagree with you doesn't mean I fail to understand your reasoning.
To quote my first response above:
image

**Comment by Siersha** [comment]
> You don't have to pick this trait at character creation, in the same way that you don't have to pick Wayfarer. I suggested this as I imagine some players would be interested in a "melee-only" challenge.

Understood. Please note above that the above states he's not averse to other traits, it's just not the goal of this PR.

> Why do you want to keep this specific score?

To keep compatibility with other high point challenge traits I would figure -namely fragile, imperceptive healer, and wayfarer. Moving it above 4 points would be over the default 12 point cap.

**Comment by enaantd** [comment]
@Siersha

> Understood. Please note above that I'm not averse to other traits, it's just not the goal of this PR.

As stated in my previous reply, we agree on this point.

> To keep compatibility with other high point challenge traits -namely fragile, imperceptive healer, and wayfarer.

Balance is a valid point. However I think we ought to balance traits once we've clearly defined them.

> Just because I disagree with you doesn't mean I fail to understand your reasoning.

I never stated (nor thought for that matter) that you failed to understand my reasoning. Plus, I was replying to @CodeBandit, so except if you're the same person I don't understand why you tell me this?

**Comment by Siersha** [comment]
@enaantd 
Sorry, your post came across as "Your -blank- doesn't make sense, my -blank- makes sense". 

@CodeBandit 
Apologies for speaking out on your behalf

**Comment by CodeBandit** [comment]
@Siersha got the first 2 points down. As for the third for why you're speaking on my behalf, I don't really understand what the discourse was about; he wasn't really coming across as what you say -just definitely something to keep in mind for the future.

Just a thought, maybe I'll also work on a sub-tab in trait selection to show and hide unwanted traits As it is, I'm happy with the trait for its intended purpose. Beyond this is the hand of merging or closing.

**Comment by enaantd** [comment]
@CodeBandit 

> @Siersha got the first 2 points down. As for the third for why you're speaking on my behalf, I don't really understand what the discourse was about; he wasn't really coming across as what you say -just definitely something to keep in mind for the future.
> 
> Just a thought, maybe I'll also work on a sub-tab in trait selection to show and hide unwanted traits As it is, I'm happy with the trait for its intended purpose. Beyond this is the hand of merging or closing.

Please refer to my edited comment above as a reply to this comment.

**Comment by kevingranade** [comment]
I don't like the goal of, "convince people to do suboptimal things by awarding them character generation points", if you want a challenge take a challenge, but it's incoherent to then award points for it
The rationale is wonky, it's pro throwing specifically because throwing is bad, which is why the description is so contrived. Also keying off of ammo types is super weird.
I don't like the proliferation of random trait checks all over the place.

Solutions:
Make it point neutral, this is clearly an arbitrary challenge, so there's no reason for it to grant points in character generation.
Split it into, "no guns" and "no bows", people can take both if they want to. Also consider basing it on skill used rather than ammo.
I really want some kind of more centralized way to enforce this. This isn't a hard blocker for now, but if you want to add more behavior restrictions it's going to start being one.

**Comment by CodeBandit** [comment]
With Kevin's response and after reading through this:
https://github.com/CleverRaven/Cataclysm-DDA/issues/37869

I've decided to scrap this trait completely

**Pull request closed without merging**
