### PR TITLE
[CR] Some general cleanup

### PR DESCRIPTION
**Pull request by aparent**
Eliminates some code duplication and clarifies similarities between branches

### CODE REVIEW

**Comment by aparent** [comment]
Am reading through the code for the project in order to understand how it is organized for more substantial contributions in the future.  This section initially confused me, especially:
```
if (a) {
 ..
}
if (a) {
 ..
} 
```
I rewrote it in a hopefully more clear way.

**Comment by karlnp** [comment]
Where'd the glass breaking noises go?

**Comment by aparent** [comment]
In each case 2 if statements were consolidated into one.  The glass breaking noises are still there just not duplicated like they were before.

The original: 
```
  else if( terrain == t_window_domestic_taped ||
               terrain == t_curtains ) {
        if (ammo_effects.count("LASER")) {
            dam -= rng(1, 5);
        }
        if (ammo_effects.count("LASER")) {
            dam -= rng(0, 5);
        } else {
            dam -= rng(1,3);
            if (dam > 0) {
                sounds::sound(p, 16, _("glass breaking!"), false, "smash", "glass");
                ter_set(p, t_window_frame);
                spawn_item(p, "sheet", 1);
                spawn_item(p, "stick");
                spawn_item(p, "string_36");
            }
        }
    } else if( terrain == t_window_domestic ) {
        if (ammo_effects.count("LASER")) {
            dam -= rng(0, 5);
        } else {
            dam -= rng(1,3);
            if (dam > 0) {
                sounds::sound(p, 16, _("glass breaking!"), false, "smash", "glass");
                ter_set(p, t_window_frame);
                spawn_item(p, "sheet", 1);
                spawn_item(p, "stick");
                spawn_item(p, "string_36");
            }
        }
```

Was changed to:

```
else if( terrain == t_window_domestic_taped ||
               terrain == t_curtains ||
               terrain == t_window_domestic ) {
        if (ammo_effects.count("LASER")) {
            if ( terrain == t_window_domestic_taped ||
                 terrain == t_curtains ){
              dam -= rng(1, 5);
            }
            dam -= rng(0, 5);
        } else {
            dam -= rng(1,3);
            if (dam > 0) {
                sounds::sound(p, 16, _("glass breaking!"), false, "smash", "glass");
                ter_set(p, t_window_frame);
                spawn_item(p, "sheet", 1);
                spawn_item(p, "stick");
                spawn_item(p, "string_36");
            }
```

It also removes an unnecessary `ammo_effects.count("LASER")`check

**Comment by karlnp** [comment]
ah! ok. forgive me - normally I wouldn't just go from the diffs but with these enormous files it's impractical to look at the source sometimes.

**Comment by aparent** [comment]
No problem!

**Pull request merged**
