### PR TITLE
New Numb Mutation

### PR DESCRIPTION
**Pull request by GalacticApple**
#### Summary
Content "New Numb Mutation"

#### Purpose of change
I felt that there was a room for a new PR-able mutation to compliment the Medical tree's Deadened. Essentially this will alter the game so that a character with the Numb trait will have a much harder time feeling emotion. 

#### Describe the solution
In-game, the mutation works by essentially cannibalizing the parts of the brain responsible for personality. As a consequence, the morale of characters with Numb will only change by about 25%.

#### Describe alternatives you've considered
Could be moved to the Alpha tree.

#### Testing
Compiled and tested in VS. I didn't see any issues.

#### Additional context
I'm pretty new to C++ and GitHub in general. I actually tried to post this a few weeks ago but GitHub decided to randomly flag my account.

### CODE REVIEW

**Comment by Maleclypse** [comment]
So to make sure I understand this part, the PC won't be impacted by either negative or positive morale effects right?

**Comment by GalacticApple** [comment]
That is the idea. They should just be at neutral morale from then on.

**Comment by Saicchi** [comment]
Though the tests have not complained yet, your `.cpp` files and probably the `.json` files too are not linted.
Give these a read:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/DEVELOPER_TOOLING.md#code-style-astyle

**Comment by GalacticApple** [comment]
I'm trying to use the Astyle extension for VS but I can't seem to figure out how to install it. Whenever I click on the solution it just says It can't find something in the path. Anyone have any suggestions?

**Comment by meelock** [comment]
> 
> 
> That is the idea. They should just be at neutral morale from then on.

Wouldn't this change make Normal Human never activate? I feel like the trait should just make it impossible to have positive moods to counter this, or maybe make it cancel normal human.

**Comment by GalacticApple** [comment]
Ah, I didn't think about that one. This would should cancel that out.

**Comment by meelock** [comment]
> 
> 
> Ah, I didn't think about that one. This would should cancel that out.

Maybe Normal Human could be a prerequisite for Numb, as both relate to emotional states. Numb is post thresh right?

**Comment by GalacticApple** [comment]
Yes it is. I set it to cancel out normal human, but I can change that.

**Comment by meelock** [comment]
> 
> 
> Yes it is. I set it to cancel out normal human, but I can change that.

It would be funny to me if Numb somehow required a special and rare potion to acquire, as a nod to the original story of Jekyll and Hyde. But that might be a bit overkill, I guess medical mutagen could be considered a rare potion made out of exotic materials.

**Review by kevingranade — CHANGES_REQUESTED** [review]
I'm not a fan of how many different things this does, or how large an impact it has.  This outright obsoletes every trait, item, or other mechanic related to morale, and in addition makes the character strictly better at social interactions despite the description indicating it has a negative impact, and makes them learn every noncombat skill at an increased rate.

**Comment by Zireael07** [comment]
> , and in addition makes the character strictly better at social interactions despite the description indicating it has a negative impact, and makes them learn every noncombat skill at an increased rate.

Color me confused by that. This should definitely NOT be a result of being numb to emotions (and I'm interested in this "mutation" for the RP purposes)

**Comment by GalacticApple** [comment]
Numb is supposed to be a side-effect, not the cause of the boost to intelligence. As for RP, that is definitely up to the individual though I personally had Psychopath in mind when making this.

**Comment by GalacticApple** [comment]
I suppose an alternative to removing morale would be that Numb instead just reduces the effects of both positive and negative morale. It would take a lot to make you either happy or sad.

**Comment by kevingranade** [comment]
Reduce impacts instead of eliminate (for little things it can even truncate to nothing, but big things should still have an impact), remove the learning bonus, and make the social thing either a penalty or remove it, and we've got something.

**Comment by Zireael07** [comment]
> Numb is supposed to be a side-effect, not the cause of the boost to intelligence.

Nope, if you don't feel emotions, you don't get a boost to intelligence, or anything else. Compensation *is* a thing, but it's not a "losing a b and c makes me more intelligent". All those sites saying we're only using a few percent of our brain are just perpetuating a silly myth.

**Comment by GalacticApple** [comment]
The brain is functionally a computer. It has finite processing power and can only do so much at once. Mechanically this mutation takes the parts of the brain responsible for emotions/personality etc. and converts then into parts meant to do other tasks related to this games intelligence metric. It's not just removing stuff.

**Comment by Zireael07** [comment]
@GalacticApple: Nope, it doesn't work that way. If it worked, as a disabled person (brain damage to both movement areas and hearing areas) I would have a boost to some other sense or intelligence or both. Nope, cerebral palsy which is basically infant brain damage/brain bleed doesn't work that way, and neither does autism (which is also usually a result of, essentially, brain damage). I know the 'super intelligent autistic' is a trope since Rain Man, but it's a minority and no one really knows how it happens. Probably some form of compensation, but again, it's not a calculator where you remove 2 from somewhere and can add 2 somewhere else - NOPE NOPE.

**Comment by GalacticApple** [comment]
This mutation had nothing to do with brain damage. The brain here is physically identical to the way it was before it's just a matter of what that brain is prioritising. Let's say you have a person doing three tasks a, b and c. If a is deemed not important, while c is seen as essential you could have the person stop doing a in favor of doing c twice. This is what is going on in the brain of a PC with Numb. In a game with teleportation and mind rays I would argue this is downright realistic.

**Comment by Zireael07** [comment]
@GalacticApple: In that case, it makes even LESS sense. All the known ways for people not to feel emotions do NOT involve brain "prioritizing other things" - they involve outright brain damage OR they involve heavy drug regime that blocks enzymes/hormones (such as serotonin which is how we feel happiness). You can't become numb (fully or partially) to emotions by "prioritizing other things" - if this were possible, PTSD wouldn't be a thing since front line soldiers definitely prioritize other things such as survival and winning the combat...

**Comment by GalacticApple** [comment]
Assuming your correct, let's just say that the near-magical alien entity that has infected the CDDA world has mucked about with the wiring of the PCs brain in some truly unfathomable way our human science cannot comprehend.

**Comment by GalacticApple** [comment]
Alright, I've gone ahead and made those changes. Numb should now reduce all morale impacts down to 25% of normal. The social modifier keeps the intimidation, but now it's harder to lie or persuade others (on par with the growl mutation). I've also removed the learning boost and added some flavor text for certain actions.

**Comment by GalacticApple** [comment]
Are the workflows that are waiting for the status to be reported stuck?

**Review by GalacticApple — COMMENTED** [review]
Sorry for the wait, I didn't think to submit a comment on this review. I've gone ahead and made the changes you suggested. Numb now reduces all incoming morale (positive or negative) down to 25% of normal. I've removed the learning boost and made the social thing on par with the growl mutation (hard to lie or persuade npcs, still somewhat intimidating). I've also added some flavor text for certain actions.

**Pull request merged**
