### PR TITLE
Add new vehicle parts

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add vehicle parts:
1. Dirty water barrel.
2. Opaque wooden door.
3. Cloth board.
4. Cloth quarterpanel.
5. Wooden aisle.
6. Storage bag.

### CODE REVIEW

**Comment by tyrael93** [comment]
>+        "flags" : ["FUEL_TANK", "NAILABLE"],

I only fuck around with jsons, so I'm probably reading this wrong, but does this actually mean you could use it to store fuel? As if, like a regular fuel tank?
Because that sounds silly.

**Comment by Darkyhard** [comment]
Well, it's a "fuel tank" for dirty water only, other liquids won't work. Wooden barrel for clean water already existed, so I have added another one,but with the ability to store dirty water.

**Comment by tyrael93** [comment]
Gotcha, I need to learn more about the .jsons altogether to make some quality of life fixes and every little bit helps.

**Comment by Chezzo** [comment]
Cloth board and quarterpanel? That would let you make a car out of sheets? Really? That exists in real life?

**Comment by sparr** [comment]
I've seen pedicabs with cloth walls on the passenger compartment. Never a high speed vehicle though.

**Comment by Darkyhard** [comment]
> Cloth board and quarterpanel? That would let you make a car out of sheets?

No, you still can't make a vehicle out of sheets, you would still need a rigid material to make a frame for it, so that sheets could be nailed to something. And I can't think of something that would make this impossible in real life, except that the resulting wall is very fragile if compared even to wooden walls, but it still does block sight and passage unless smashed through.

**Comment by Malkeus** [comment]
A lot of solar cars use an ultralight rigid frame with some kind of tough fabric stretched over it to save weight. It's just there to make the car aerodynamic.

**Comment by chaosvolt** [comment]
Hmm. Or you could imagine the canvas-and-wood frame of early aircraft. So this would be hilarious if airplanes ever become a thing in this game.

**Pull request merged**
