### PR TITLE
Changes to Helicopter Crash scenario

### PR DESCRIPTION
**Pull request by chaosvolt**
1. Surrounded start. Seriously, it's minus 8 bloody points.
2. Replaced mundane generic survivor with additional options of military
   recruit or special operator. Go home default survivor profession, you're
   drunk.
3. Minor tweak to scenario description.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I don't think this is the way to go. Surrounded start only changes how hard is it at the very start, after that it's free 8 points. It needs a drop in points. Surrounded start itself only makes it a RNG roulette.

**Comment by chaosvolt** [comment]
Hmm. I did say tin the relevant thread that we might still need to adjust the point cost, yes. The surrounded start is more a logical result of a noisy crash than a balancing factor.

So you said adjust it by 2 in some way? Not sure how these changes would affect your recommended point cost.

**Comment by Coolthulhu** [comment]
Not by 2. To 2.
Though that was before checking how much points do the professions cost. 2 points above what the cheapest profession gives should be OK.

Noisy crash doesn't explain surrounded start. Surrounded start will not only make the crash site spawn crash site zombies (who should be fresh corpses at the moment), but will also spawn an entire horde that shouldn't appear for the next few minutes.

Note that survivor's wounds are still fresh - bleeding and all that.

**Comment by chaosvolt** [comment]
Hmm. I see. So still in favor of removing the SUR_START flag? And I'm still unsure if you mean have it give 2 points or cost 2 points. Having removed survivor from the list of professions in favor of professions that all cost points alters this further.

**Comment by Coolthulhu** [comment]
It can give 2 points. As in, if you pick it and the cheapest profession, you have +2 points above what you'd have with default scenario+survivor.

As for SUR_START: test it out. If you find it easily survivable, it can stay. But if you have to re-roll 2-3 times just to survive that, it's not OK.

**Comment by chaosvolt** [comment]
Hmm. Guess I'll remove the SUR_START flag. Using the "2 points more than cost/bonus of cheapest profession" would set it at 1 point COST, due to removal of survivor and military recruit (3 point cost) now being the cheapest profession.

Unless there are any 0-point-cost professions that'd make more sense for this scenario?

**Comment by chaosvolt** [comment]
I also kinda wish we had a "delayed surrounded start" flag, or a simulation thereof by spawning with a large amount of noise generated to attract whatever spawns elsewhere.

**Comment by Coolthulhu** [comment]
> Using the "2 points more than cost/bonus of cheapest profession" would set it at 1 point COST

```
x = (cheapest profession cost) + 2
cheapest profession cost = 3
x = 3 + 2
x != 2 - 3
```
Though I didn't check how good that profession is. 5 points may be too much if the class isn't just extra points in stuff like marksmanship that is only useful in midgame and later.

> I also kinda wish we had a "delayed surrounded start" flag, or a simulation thereof by spawning with a large amount of noise generated to attract whatever spawns elsewhere.

Wouldn't be hard to write. Basically just 3 lines `if(noisy) make_noise` in game.cpp in the start game function. Optionally before spawning player or with player having deafness removed.

**Comment by chaosvolt** [comment]
Hmm. Well you said that if we had survivor (0 points) as cheapest, it should be a bonus of 2, right? Or am I misreading and you meant a COST of 2?

**Comment by Coolthulhu** [comment]
> Well you said that if we had survivor (0 points) as cheapest, it should be a bonus of 2, right?

Yeah. But you changed the cheapest class to something else, so the bonus should be a bit higher to make the start sensible.

**Comment by chaosvolt** [comment]
Ah. So it should be high enough so that you're still 2 points ahead of a default scenario+profession if you pick the cheapest class? Instead of strictly interpreting the "X points more than cost of profession Y" basically.

**Comment by Coolthulhu** [comment]
Something like this, yeah.

**Comment by chaosvolt** [comment]
Ah good, hopefully that avoids further confusion on my end.

And yeah, if we had that "generate noise prior to spawning" it'd be excellent to add this.

Also, couldn't we make the Really Bad Day even WORSE by using the injuries given by the crash flag?

**Comment by chaosvolt** [comment]
I am pondering other plausible uses for the SUR_START flag though. It would make sense for this if the player spawned with their injuries but no bleeding, as then it could apply you'd had time to get out of the wreck, tend to your wounds at a basic level, and gather your equiopment. That might give enoughh time for a horde to gather. But that would trade one difficulty element (bleeding) for another (surrounded).

**Comment by Coolthulhu** [comment]
> if we had that "generate noise prior to spawning"

It's literally 3 lines. 4 with deafness removal.
Literally just `if( scenario has flag ("noise at start") ) sounds::sound( stuff ), u.remove effect( "deaf" ) )` in `game::start_game` or `start_location::handle_heli_crash`.

**Comment by chaosvolt** [comment]
Hmm. Would be interesting, yes.

**Comment by Coolthulhu** [comment]
Looks like the game already finds the lowest point profession and adds the points to scenario points. Heli crash gives 5 extra points AND soldier profession bonuses rather than 2 points+soldier.

**Comment by chaosvolt** [comment]
Oh derp. I'd heard mention of something being done to tweak that.

So I should thus alter the point cost to just a straight 2 bonus?

**Comment by chaosvolt** [comment]
And that is why I should've checked this sooner. ;A;

**Comment by chaosvolt** [comment]
Hmm. Anything else to adjust?

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
