### PR TITLE
[READY] Draw power directly from UPS with UPS mod.

### LINKED ISSUE #18912: Vehicle repair charge counting doesn't get multiple UPS sources right
Given:
- a welder with a UPS conversion mod and 189 charges, in inventory;
- a UPS with 113 charges, in inventory;
- a UPS bionic, activated, with 646 power available

I can't do a repair on a vehicle that needs 300 welder charges.

The bionic UPS on its own, or the standalone UPS plus welder charges, should be able to cover 300.

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #18912 

Patch UPS lookups into various parts of the infrastruture.

Test Case:
Find a damaged vehicle, or make a vehicle become damaged.
Spawn a welder, UPS mod, UPS, batteries and welding gear.
Apply mod, load batteries into UPS.

Attempt to repair vehicle.

### CODE REVIEW

**Comment by BevapDin** [comment]
How does it handle the following test:

Have one soldering iron and one hotplate, both with UPS mod, but 0 contained charges.
Have one UPS with 10 charges.

Attempt to craft an electric carver (off) (requires 10 soldering iron and 10 hotplate charges).

Because currently the "has tool" tests are all independent, meaning the game checks "has 10 soldering iron charges" (yes via UPS) and "has 10 hotplate charges" (yes again via *the same charges of the same UPS*). The game reports you have a total of 20 charges.

**Comment by kevingranade** [comment]
That will break for two reasons, and I intend to fix both of them:
1. Crafting calls aren't overridden, just vehicle repair.
2. You are correct that it will "overcommit" by counting the UPS charges twice when deciding whether the operation will succeed.

For 1, I need to override things in more places, which kinda sucks but I also don't want to overhaul crafting and item marshalling right now (however it very much needs to be done, this PR is a demonstration of how inflexible it is, and I don't see any incremental improvements that can be made, it just needs to be rethought).
For 2, I'm planning on adding a UPS_charges_used member that is persisted for the duration of charge evaluation, for each group of tools it will deduct the smallest number of UPS charges needed.  As long as we consistently minimize the number of UPS charges used in both pre-validation and use, we shouldn't encounter any inconsistencies.

I also intend to write some tests for this, it's super fragile and a PITA to set up, so they're going to pay off really quickly.

**Comment by kevingranade** [comment]
> 1. Crafting calls aren't overridden, just vehicle repair.

Whoops, looks like I accidentally fixed this already.

**Comment by kevingranade** [comment]
Tests in place, an UPS charge lookup code patched to avoid overcommitting charges.

**Comment by kevingranade** [comment]
What this does NOT address:
Satisfying tool charges from multiple entries.  (i.e. drawing charges from a "welder" and a "crude_welder")
Dynamically drawing charges from a UPS when activating tools.
Drawing charges from the UPS CBM while crafting or repairing.

**Comment by kevingranade** [comment]
Extended crafting test to verify that expected charges were consumed.

**Comment by kevingranade** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
This has been up in a finished state for almost a week now, I'll wait a bit longer for comments, but unless it gets merged pretty soon I'm going to have to go ahead and merge it myself.

**Pull request merged**
