### PR TITLE
Speed up making batches of tea

### PR DESCRIPTION
**Pull request by ildifa**
#### Summary
None

#### Purpose of change
Making four cups of tea (1 L) shouldn't take more than half an hour.

#### Describe the solution
I raised the batch crafting bonus for tea, from 20% to 90%.
Now making 1 L of tea doesn't take much longer than making a single cup.

#### Describe alternatives you've considered
Adding another recipe for making a big batch of tea

### CODE REVIEW

**Comment by GuardianDll** [comment]
When i tried to do same change, I've got the response "the biggest part of making tea is boiling the water, and it mostly linear function (ie if you boil 1 liter of water for 5 minute, 2 liters will spend 10 minutes, 3 - 15, 4 - 20 etc.). So increasing the batch bonus for this craft recipe at 90% is not correct.

**Comment by oosyrag** [comment]
If 1 unit of liquid is 250ML, or 1 cup, I can decidedly say it doesn't take 8 or 10 minutes to bring to a boil on a hotplate. Lowering it to 3-4 minutes would be reasonable.

**Comment by Danny-Alexander** [comment]
What about adding an alternate recipe which requires boiling water (like you eventually get if you leave a filled vessel in a fire) with 90% batch time saving?

Can the current recipe system specify ingredient temperature (or state e.g boiling) requirements?

**Comment by Fris0uman** [comment]
Closing as stale

**Pull request closed without merging**
