### PR TITLE
Magiclysm: Magical Tools

### PR DESCRIPTION
**Pull request by connorpmartin**
#### Summary
Features "Magiclysm: Magical tools"

#### Purpose of change

Magic having existed pre-Cataclysm implies that there would be a heavy demand for magical tools.

#### Describe the solution

Gives crowbar+1 level 4 prying (same as a halligan bar) and crowbar+2 level 5 prying. Adds magical bottle jack, butchering items (and butchering kit), and scalpel. 

#### Describe alternatives you've considered

Not implementing all these tools. Coming up with a better way to distribute the items in item groups: apart from the scalpel, which I figure would rarely be on hand in hospitals and other medical areas, most of these items don't go super well together. Suppose that's also true for a lot of +1 weapons, but I'm not sure how to fix that other than spending a bunch of time manually populating each item to appropriate locations.

#### Testing

Increased prying works as expected.
image

Spawned in all other items; they work as expected. Butchering kit crafting recipes work as expected.

### CODE REVIEW

**Comment by connorpmartin** [comment]
I've expanded this pull request to add a few more magical tools and set them to spawn in the technomancer house, the Forge, and rarely in the black dragon lair.

**Comment by connorpmartin** [comment]
I am having some trouble getting the items to spawn naturally. Guess I'll check on the json guide a bit later: should be fixed in a bit once I come back to this.

**Review by KorGgenT — APPROVED** [review]
looks good.

**Comment by CountAlex** [comment]
None of the items in this PR has a plural name set which creates incorrect namings.

**Comment by connorpmartin** [comment]
Yeah, I think I made this PR before plural name sets were a front. Or I just forgot.
there’s also a standing issue with actually getting the items to spawn.

Could someone unmerge the PR? I think I’ll resubmit it when I have time to fix this stuff.

**Pull request merged**
