### PR TITLE
EOD helmet revision

### LINKED ISSUE #65952: EOD helmet has unreasonably and unrealistically low encumbrance for its protection
### Is your feature request related to a problem? Please describe.

In game, EOD helmet has next protection values:

<html>
<body>

Material | Rigid Kevlar | Nomex
-- | -- | --
Thickness | 7.5mm | 7.5mm
Coverage | 100% | 100%
Bash | 22.50 | 7.50
Cut | 30.00 | 7.50
Ballistic | 37.50 | 7.50

</body>
</html>

And head, eyes and mouth encumbrance of 20, 10 and 15 respectively.

Which leads to a problem: an unpowered armor piece (the battery is for headlight) that weighs 5.6 kg and has better protection than many other pieces is somehow less encumbering than an army helmet (23 fitted). Unrealistic and unbalanced, at least in my opinion.

An EOD helmet IRL would severely restrict head movement (comparable to heavy medieval helmets, it weighs about as much as some of those, too), especially if worn with EOD jacket with a collar.

Meanwhile, in-game EOD jacket has pretty reasonable 80 encumbrance (maybe even a bit too much, though).

If the helmet in question is modeled after something like an Advanced Bomb Suit, it would be not realistic to make the visor kevlar, too. Thick plastic (like on ballistic goggles) would be much more representative of the face shield material.

If talking even more realistically, EOD suits should not have such extreme ballistic protection value. Their job is absorbing blast wave impact (high blunt resistance) and covering whole body from fragments (that usually have much lower penetration capabilities and velocity than actual bullets).

### Solution you would like.

Increasing EOD helmet head encumbrance to 40-50. 60 at most. That's it.
Optionally, changing eye (and maybe mouth) protection material to about 15-20 mm of plastic (on IRL Advanced Bomb Suit faceshield is made of acrylic glass and polycarbonate).

### Describe alternatives you have considered.

1. Decreasing EOD helmet protection and weight to approximate Advanced Bomb Suit helmet (weighs 3.6 kg).
2. Having an overperforming and unrealistic armor piece in game.

### Additional context

EOD helmet analysis study: https://www.mdpi.com/2076-3417/10/22/8227 Outer hard shell is about 4 mm. The rest is shock-absorbing foam. Does the game have a specific shock-absorbing (blunt damage resistant) material, btw? Something like quilted cotton, but more advanced. Maybe neoprene?

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Balance "Makes EOD helmet thickness, protection values and materials closer to realistic"

#### Purpose of change

Resolves #65952.

#### Describe the solution

Implements changes suggested in relevant issue.

Will likely go through other EOD armor, but the EOD helmet had the most glaring balance issues (better protection AND encumbrance than army helmet? I loot two!) and, as such, had to be reined in.

#### Describe alternatives you've considered

Faceplate 20 mm thick and made out of generic plastic. 40 bash, 40 cut, 40 ballistic resistance compared to 15 bash, 30 cut, 27   ballistic of 3 mm lvl4ballisticglass. lvl4ballisticglass was described as polycarbonate in glass though has extreme protection per mm... 3 mm thickness value was because of the thickness of the simulation material that was used.

See relevant issue.

#### Testing

None for now, will do when possible.

#### Additional context

See relevant issue. 

Weight value based on https://en.wikipedia.org/wiki/Advanced_Bomb_Suit

Thickness values based on article linked in the relevant issue.

### CODE REVIEW

**Comment by randomtyper** [comment]
The test said I had to remove EOD helmet from known_bad_density.json for some reasons...

**Comment by randomtyper** [comment]
After some hesitation, I think I should use an actual widespread material instead of some abstract high tech over9000 protection per mm thing that is only used for bionics, phase immersion suit and RM13 armor.

**Comment by randomtyper** [comment]
Huh. 6 mm of rigid plastic is somehow better at protecting your head from concussion than 14 mm of soft foam... Some food for thoughts. Maybe add some mechanic that makes non-rigid materials much more effective versus blunt when absorbing damage dissipated by rigid armor?

Because in the current state of things, face plate of EOD helmet vastly outperforms other parts of helmet in terms of protection, and those other parts of helmet are underperforming when comparing to the army helmet even in the areas where they are supposed to be strong (blunt protection).

**Comment by randomtyper** [comment]
After some research, it seems that protection values for generic plastic are derived from specialised polycarbonate composite (that is certainly not your usual plastic found in your pen, bag or bottle). Said composite also has a blue-green hue when thick enough (something that is absent from most EOD helmet visors I have seen, in fact, most have white edges, something more resembling acrylic glass). I also did not find such "glass" (bulletproof polycarbonate) made in highly bent shapes.

Sources:

Composite 3 inch glass from uparmored HMMWV (FRAG 5/6/7) stops an FMJ .50 bullet. When using in-game values, Barrett gives about 154 damage vs about 150 of generic plastic at 3 inch thickness. The results are close to real life, BUT: the plastic in game is supposed to be your usual everyday plastic, not composite lightweight polycarbonate specifically made to be an armored windshield, and add in the fact the thickness itself gives some additional protective value through added rigidity (polycarb in a 20 mm thick visor wouldn't be as protective as a solid 3 inch brick of composite):

https://www.youtube.com/watch?v=OpDIoFHZfRs

**Comment by randomtyper** [comment]
Yeah, this PR is leaking heavily into this issue: #66139

**Comment by bombasticSlacks** [comment]
I'm going to merge this because it seems like a step in the right direction. If you don't make issues or work on all of the text above, it will die here, never being looked at again by another person, food for thought.

**Pull request merged**
