### PR TITLE
feat(content): New Epilogues for NPCs

### PR DESCRIPTION
**Pull request by Empyrean-Heaven**
#### Summary
Content "New Epilogues for NPCs"

#### Purpose of change
I decided that since I am not well-versed in the deeper code of the game, I may as well contribute where I can: in JSON. Similar to last time when I added more nightmares, this one is aimed at adding more endings for NPCs.

#### Describe the solution
Added several new epilogues for both male and female NPCs.

#### Describe alternatives you've considered
Leaving it be.

#### Testing
Seems to be working fine. Just some simple new lines in JSON.

#### Additional context
Hope everyone's doing great. 😄

### CODE REVIEW

**Review by MNG-cataclysm — COMMENTED** [review]
What if you added these backgrounds to both male and female epilogue trees, and just changed the syntax to fit?

**Comment by Empyrean-Heaven** [comment]
> What if you added these backgrounds to both male and female epilogue trees, and just changed the syntax to fit?

I'll try :D

**Comment by Empyrean-Heaven** [comment]
Finished implementing your suggestion MNG. 😄

**Review by MNG-cataclysm — APPROVED** [review]
This looks great!

**Pull request merged**
