### PR TITLE
Summary27 added

### LINKED ISSUE #25985: 0.D PR title summarization 27
This is one of a number of issues to crowd-source categorization of PR titles in order to construct a changelog for the 0.D release.

 Please prepend a category title to each line listed at the end of this issue and commit the lines as a new file in the repository with the provided name.

 Feel free to summarize or expand on the titles to make them better fit in the changelog.

 See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/changelog.txt for previous changelog entry examples.

 # TITLES
 The categories to choose from are: Features, Content, Interface, Mods, Balance, Bugfixes, Performance, Infrastructure, Build, I18N
 See the Changelog Guidelines at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CHANGELOG_GUIDELINES.md for explanations of the categories.

 # FILENAME 
 summary27

 # Lines to summarize

Remove grab when target is destroyed
Text input window should ignore non-digits when in digit-only mode.
Converts church braziers from item to trap
Bash shouldn't give better items than deconstruct now
Swap game::zoom_in and game::zoom_out
Added missing ammo capacity to SVS robodrum and added reload time
Explanation for the player when choosing the direction for the new headlight
Encapsulate the WINDOW pointer in class game in unique_ptr
[RDY] Fix interference effect of radio messages in localized version
Fix vehicle turret behavior and reorganize targeting code
Remove battery charges from the handpress
Sheath knives and fill quivers for rest of professions
Standardizes and alters mining construction
forbids filling of tanks with rotten liquids
Add gcc instructions for macOS
Move user-default-mods.json to config folder
Some fixes to the filter popup of pickup menu
Fix switching language not affecting season names
Show "Time: ???" when underground and without watches
Add non-incendiary variants to milspec rifle ammo itemgroup
fix for #20923 relax gas aiming loop
Moves ethanol to after disinfectant in recipes
Add FIRE flag to lit oil lamp
Don't repeat last ranch foreman mission
Fix crash in profession::items  alternative fix
Add Polish language
Compare to mission type ID instead of mission name when dealing with 'Install Repeater Mod'
Fix message window overlapping border in advanced inventory UI
Fix revealing invisible monster when looking around
Fix season names not being detected by xgettext
Add error sound effect to main menu and use menu change sound effect for options
[RDY] Fix flamethrower sound effects and add railgun sound effect
[RDY] Makeshift mod and bayonet update. (2nd)
Fix side not cleared when taking off an item
Fix unexpected popup when trying to sleep while E-ink PC music is on (#18033)
Some assorted scrollbar related fixes
Blazemod flamethrower parts update
Stops roadblocks from spawning live zeds
Fix "get_option silently returns defaults if invoked on a world option"
Make a functional travis.yml
[READY] Add explicit instantiation of string_id<T>::NULL_ID to make clang happy.
Remove gasoline and disel from explosive recipes.
Restore sum of errors based dispersion.
Hotfix: remove remaining recycling calls from makefile
Change harvest_by_season to new nulls
Add PR-24 to Eskrima martial art
Buff RM451 Flamethrower item spawn chance
Implement separate class for gun mod location:
Fix debug storage not working in advanced inventory
Add canned meat and canned fish to meat aspic recipe
Don't cancel activity if electricity-immune player is struck by it
Fixed clang again...
Nerf bullet explosion scaling
Remove game::mission_npc hack
[CR]Add Chili Pepper, Seed, and Chili Powder Recipe
Convert string_id::NULL_ID to a static method
[CR] Fix compilation errors with MinGW
Fix blazemod
Disallow crafting with filthy clothing.
Road-Runner and Slow Footed cancel each other
Properly fix debug storage
Add missing includes
 Battery compartment mod update. 
Use game:critter_at instead of getting the index separately
Adds options to build and seal coffins
Imports breeches and cavalry saber
Rebalances return of smashing foliage
Add BELTED flag to missed arm guards
Debuff cloutie
Fixup vehicle alarm disable check
Correct dispersion at misses
Places fire first in reversible recipes
Fix logged notice when escaping out of throw menu
[CR] Enable to customize 16 ANSI color slots
Debug menu fixes
Fix another case of debug storage overflow
Expands vehicle water purification, ad-hoc with funnels
Hide bionic slots for 0.D
Curry and curry with meat nutrition balance
Added trait_id call around DEBUG_CBM_SLOTS to fix regression in #20370
Add Food Processor tool
[READY] Enable unit tests in Travis builds.
Fix reload failure message
Chesthole, 32, Fixes boarded up windows, broken down doors, adds the bitten effect
(Beta) National Guard Camp
Properly fix debug storage 2
Encapsulate data of worldfactory  
Fixes spawning in cabins and farms
Add worthwile loot to the shipwreck
Add detergent and allow it to be used in washboard
Info about conductivity now mentions item, not weapon
Fix gdb unknown target exception on Windows
Sleep-through messages
Sand/clay extraction re-do
Nat guard fix
Message Window Makeover
Alterations to steel spear and other polearms
Fixes redundant use of char_forge in recipes
Remove unused members of class game
Make attack distribution test deterministic

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
```SUMMARY: Content "Summarizes change set #27"```

Fixes #25985

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Please add fixes #25985, so people can see that it is being worked on.

**Comment by Inglonias** [comment]
> Please add `Fixes #25985`, so people can see that it is being worked on.

done.

**Comment by kevingranade** [comment]
> I believe prefixes like RDY, Ready, CR, etc. can be safely removed in the process

I agree, this would save me a lot of time.

**Comment by Inglonias** [comment]
> > I believe prefixes like RDY, Ready, CR, etc. can be safely removed in the process
> 
> I agree, this would save me a lot of time.

Done.

**Pull request merged**
