### PR TITLE
Minor house mapgen tweaks

### PR DESCRIPTION
**Pull request by tjole**
#### Summary
Content "Tweaks default house08 map, introduces house08 variant and fixes house22 typo"

#### Purpose of change
While testing another branch, I noticed issues with house08 and house22. These changes address those issues.

#### Describe the solution
An interior tile in a house22 variant was showing exterior floor. I fixed this by changing it to interior floor.

I also noticed that there was strange furniture placement in house08 (see attached pic). This change replaces the default house08 variant with one with more sensible furniture placement. I also added a new variant for house 08 in case the strange furniture placement was intentional, with the furniture being used to block the door. In this variant, the idea is that a person fortifying their house was interrupted by zombies. They were injured, fled to another room where they applied first aid, before fleeing through a window.

#### Describe alternatives you've considered
I considered whether these issues were intentional. For house22 with the exterior floor inside, I believe this was accidental. I believe houses are usually built with some interior floor, and the fact that it was a single tile with no tools/building materials spawned nearby makes me think this was a mistake rather than a choice.

I also considered separating the house08 and house22 changes into different branches, but that seemed excessive for the one character change in house22.

I wasn't sure whether the furniture placement in house08 was meant to imply someone hastily tried to block their door with furniture. There were no other features in the map that supported this, though. While I do believe this was a mistake, I've also introduced a variant with the concept of a partially fortified house, just in case.

I considered different item spawns in house08 and tried avoiding extending the tramadol and cotton_patch items, but was unsure how to get the effect otherwise. I'm happy to make changes to this to better fit the codebase, if necessary.
****

#### Testing
I spawned each house variant and checked that furniture spawns were correct, with the right floor-type underneath. I also checked that items were spawning in the expected locations, and in the expected amounts.

#### Additional context
Original house08 furniture placement, notice the couch and bookshelves by the front door on the north wall.
original

New furniture placement in default house08 variant.
newDefault

New house08 'interrupted fortifying' variant.
InterruptedFortifying

### CODE REVIEW

**Comment by Zireael07** [comment]
I strongly suspect the original placement was intentional, i.e. someone barricading the door

**Comment by LurchingOtter** [comment]
> I strongly suspect the original placement was intentional, i.e. someone barricading the door
Ok. Should I revert the default variant to this placement? Alternatively, I could add that layout as another variation with a higher likelihood.

**Comment by Zireael07** [comment]
/shrug

Either way is fine by me but I'd wait for more devs to weigh in (I mostly contribute ideas and JSON edits but not mapgen stuff)

**Comment by Night-Pryanik** [comment]
> I could add that layout as another variation with a higher likelihood.

This.

**Pull request closed without merging**
