### PR TITLE
Greatly reduced item spawn chance in churches, so it won't look like …

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
…rapture

Fixes https://www.reddit.com/r/cataclysmdda/comments/730for/something_strange_happened_at_this_church/

### CODE REVIEW

**Comment by pisskop** [comment]
i thought the point was rapture

**Comment by kevingranade** [comment]
It is supposed to look like a rapture, but I think it went overboard due to
that item spawn change.

**Comment by ZhilkinSerg** [comment]
Does this look like rapture? I didn't have one yet, so I need help figuring out.

default

**Comment by kevingranade** [comment]
That looks about right, were going for, "church full of people disappeared, leaving the items they no longer need".

**Pull request merged**
