### PR TITLE
partial vehicle damage reduction hotfix

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
Bugfixes "partial vehicle damage reduction hotfix"

#### Purpose of change
pull request #32595 attempted to shift some vehicle part resilience from durability (effectively vehicle part HP) to damage reduction.

while a reasonable step, many of the values were extremely high, including heavy duty frames having a damage reduction of 112 to all damage types.

this resulted in vehicles being able to outright ignore an extremely high percentage of damage, especially from collisions.

#### Describe the solution

through discussion with @mlangsdorf determined some baseline acceptable values for structural elements suitable enough to make vehicles less immortal.

the frame values below are used for frames and structural elements that use those same items (doors, hatches, trunks, etc)

these values are all substantially lower to represent the fact they're designed to hold up to the load they're under, but not in any way specifically engineered to resist substantial outside forces.
they're grouped into three primary tiers:
wood, aluminum (which is somehow only one frame type), and steel

|frame type|resistance|durability|item|
|--------------|--------------|--|--|
|folding_wood_frame     |3|   15 |      foldwoodframe|
|frame_wood_light       |4 |   100|     frame_wood_light |
|frame_wood             |5   |   150|   frame_wood|
|xlframe                |7       |  150 | xlframe|
|folding_frame        |  10|   50|     foldframe|
|frame                  |20    |  400 |  frame|
|hdframe               | 30 |   760|    hdframe|

like with frames, the board values below are used for boards, quarterpanels, stow boards, etc

|board type     |          resistance|  durability|    item|
|--------------|--------------|--|--|
|clothboard       |    bash 3 | 15 |      sheet|
|woodboard      |        5     |    100 |  wood_plate|       
|board              |    7        |  80 | sheet_metal|
|hdboard         |       20    |   450 |   steel_plate|

armor plating is all substantially higher than their equivalent frames/boards due to the fact they're actually meant to resist outside forces (such as collisions or attacks)

rams are 1.25 times both the durability and damage reduction of their respective platings

armor type| resistance | durability | item
--|--|--|--
wooden armor| all 16, cut/stab 8 | 250 | wood_plate
steel plating| 56 | 660 | plating_steel
superalloy plating | 56 | 600 | plating_superalloy
spiked plating | 48 | 620 | plating_spiked
hard plating | 70 | 780 | plating_hard
military composite armor plating | all 60, ballistic 105 | 700 | plating_military
chitin plating | 20 | 200 | plating_chitin
biosilicified chitin plating | 24 | 200 | plating_acidchitin

these values are admittedly a bit more arbitrary, but largely tuned around steel plating in particular (which is approximately 12mm thick) being able to stop shots from .30 Carbine. the military composite plating has ballistic protection aimed towards contending with .50 BMG

after discussion with @I-am-Erk chitin and acid chiting have been repositioned as something between wooden armor and steel, closer to wooden. they're the only non-ram objects i adjusted durability on, making them more fragile than wood.

spiked plating is noteworthy in that it was simply flat out better than steel plating, despite having a different purpose. i brought it slightly below steel plating

hard plating is currently kind of a mystery substance, but it seems to be intended to be some kind of differentially hardened steel of some kind. whatever it is, that's not post-cataclysm manufacturing any more than military composite is, so its recipe has been removed (but you can still find it in military wreckage and in military locations).

testing also showed a remarkable tendency for vehicle batteries, seat belts, and clocks (?!?) to get destroyed from cascading shock damage in collisions when the vehicle otherwise didn't care. added a small amount of bash resistance to help mitigate this.

magiclysm's orichalcum frames were also reduced, but not nearly as intensely as their equivalents in the core game.

substantially altered the vehicle portion 'explosion damage test', to instead track total damage to the vehicle in percentage form (instead of checking for no damaged parts, minus some specific exceptions). added additional scenarios and had it iterate 20 times while i was at it, to help catch surprises in future PRs. 

#### Describe alternatives you've considered

letting 0.f stable continue to ship with nearly immortal vehicles despite it slipping by us for 0.E stable without being addressed?

i could also have put more work into durability, and covering all of the other non-structural bits, but i see this as a "oh crap we can't let another stable go by with this" bandage, and we need a more proper balance pass later.

#### Testing

in a test world made a huge span of pavement, and added several kinds of walls, repeatedly ran vehicles into walls.

walls tested:
wooden privacy fence (basically everything motorized considered this a gentle suggestion)
"white walls" (`t_wall_w`), the standard housing wall and what also gets used for evac shelters
log walls
brick walls
concrete walls

primary vehicles tested:
bus (as in the commercial vehicle, not a schoolbus)
humvee (mostly without any rams added in the front, but also a couple of incidents with)

before these changes, the humvee was able to work its way through everything with some effort and minimal actual damage, especially at speeds of around 2-3 tiles per second (8 to 12 mph)
the bus wasn't quite as prepared to shrug it off, but it could work through any of the above with effort and a bit more damage 

notably, around 5 tiles per second the bus took meaningful damage from collisions, but the humvee mostly only took cosmetic damage to the composite armor plating, and shock damage to soft components further into the vehicle (such as the battery, clock, or seat belts)

after these changes, trying to simply grind your way through log walls, brick walls, or concrete adds up to quite a lot more damage, so piercing a hard wall wants an impact around the 5 tiles per second range, and the bus *definitely* feels this. probably drivable afterwards, but not guaranteed.

at 10 tiles per second (around 40 mph), the bus gets savaged by its impact with the brick wall. it still clears a hole, but it suffers extreme damage, and is reasonably likely to be fatally damaged.

at 12 tiles per second (around 50 mph) the humvee is able to get through a fair amount of concrete, but takes substantial damage. not as bad as the bus in the previous example, but enough to be highly debilitating (in my test, the front left wheel hub assembly was destroyed, resulting in that wheel being dropped to the ground)

also mowed some zombies, a skeletal juggernaut, and an iron golem (magiclysm) with a tow truck that i installed military composite rams on the front.

it was remarkably prepared to cope with this, and only after all of that did i start to see substantial damage to the vehicle. 

#### Additional context

privacy fence didn't meaningfully slow humvee or bus

bus struggled a bit with residential walls (5 t/t)

humvee did better (5 t/t)

bus vs brick (5 t/t)

humvee vs brick (5 t/t)

bus vs brick (10 t/t)

humvee vs reinforced concrete (12 t/t)

final fate of ramming tow truck

solar car versus residential wall. still drivable. not structurally sound. (also the storage battery is draining)

### CODE REVIEW

**Comment by esotericist** [comment]
crap, I forgot about the explosion test. I'll have to look into that later

**Review by mlangsdorf — APPROVED** [review]
Looks great.  Thank you for doing the testing and for revising these numbers.

**Comment by actual-nh** [comment]
A search on Google Images for "bus house building collision" may be informative for what one would expect.

**Comment by esotericist** [comment]
> A search on Google Images for "bus house building collision" may be informative for what one would expect.

that's a fair point. and many of the results i see there are remarkably similar to what i got.

**Comment by esotericist** [comment]
additional fun report:

made an ersatz soapbox racer. 3x3 of foldable wooden frames (since that's the closest thing to a rational 'light' wooden frame we have at this moment), added wooden quarterpanels and doors, put in a small electric motor (the same as what's in an electric scooter), and a medium storage battery. wheels were all 27" bicycle wheels on wooden wheel mounts. used a solar car i had laying around from a previous test to charge it.

drove into the wooden privacy fences at 12 t/t (80 kph, 50 mph)



result: two `XX` frames (front center, front right), one `\.` frame (front left). front left wheel and front center quarterpanel ("hood") are at `|\`. 

the two fences were both hit within the same turn, and the second row of privacy fences bled off all the velocity, so at the time of that screenshot, the vehicle was moving at 0 t/t. naturally, my survivor was thrown against the hood of the vehicle, which probably would have sucked immensely if it wasn't an immortal debug character (a deceleration from 80 kph to 0 kph in ONE SECOND is not small).

considering what the vehicle was impacting, how, and under what context, i consider this also successful; the vehicle is thoroughly messed up but not completely obliterated, despite the lack of damage reduction.

unrelated: wooden vehicle tiles in ultica when?

**Comment by esotericist** [comment]
on request from discord, same vehicle vs street light

12 t/t (80 kph, 50mph) like before


somehow i ended up the cargo box in the rear



damage report:
front row:
`XX` FL wheel and front center frame. hood is `|.`, motor is `|\`. front right frame is `\.`, quarterpanel, wheel mount, and wheel are `|\`

all three center row frames are `XX`, left door, dash, and controls are `|\`, seat is `XX` (but that doesn't mean much since it's a sheet for some forsaken reason)

rear row:
back left frame is`\.`, other two are `|.`. battery is fine, everything else in that row is `|\`

**Pull request merged**
