### PR TITLE
use units::to_liter<double> template explicitly (fix #18430) 

### LINKED ISSUE #18430: Volume rounding issue
This was discovered while working on #18426

In the inventory screen (`inventory_ui.cpp`) and the pickup screen (`pickup.cpp`), and soon in the advanced inventory screen (`advanced_inv.cpp`).

In short: everywhere we use `units:to_litre`, there is a volume rounding issue.

Here, if I begin to grab a crowbar:
capture_d ecran_2016-09-19_a_15_17_47

Then, when its inside my inventory:
capture_d ecran_2016-09-19_a_15_20_06

### PR DESCRIPTION
**Pull request by pierredavidbelanger**

### CODE REVIEW

**Comment by mugling** [comment]
You can replace the bad template with:

```
inline constexpr double to_liter( const volume &v )
{
    return v.value() / 1000.0;
}
```

The buildbot failed this PR because of astyle. Presuming your compiling under unix try `make astyle`.

**Comment by pierredavidbelanger** [comment]
I see you did it (#18432).

**Comment by mugling** [comment]
If you reopen and adjust to match #18432 you may as well take the credit for that

**Comment by pierredavidbelanger** [comment]
I dont mind the credit.
And I did not know how to fix it properly anyways ;)

**Pull request closed without merging**
