### PR TITLE
[RDY] Inreased jack weight for boom crane to support potentialy all superheavy deathmobiles

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Here jacking stats was changed: https://github.com/CleverRaven/Cataclysm-DDA/pull/18947
Now boom crane is designed to be usef for crazy player construced deathmobiles. So for boom crane I set jack weight to 20 tonnes (JACK 40).
I thought 20 tonnes would be enough for anyone. I was wrong. 

I digged here: http://smf.cataclysmdda.com/index.php?topic=212.0 and realized that weight cap to 20 tonnes is not enough for players who REALLY dedicated to build rolling superfortress.

So I propose to increase boom crane jack weight to 200 tonnes (JACK 400). 

Actually IRL that kind of weight accesible for cranes of that type: http://f-kran.ru/arenda-avtokrana-liebherr-ltm-1200

200 tonnes ought to be enough for anybody.

### CODE REVIEW

**Comment by Zireael07** [comment]
The whole reason cranes were introduced was to limit the deathmobiles. 20t is enough, thank you very much.

**Comment by Firestorm01X2** [comment]
>The whole reason cranes were introduced was to limit the deathmobiles. 20t is enough, thank you very much.
Why do we need to limit player? Deathmobile is one of the game feature. Achievement of player that do not come free.
Just look at this:
http://s32.postimg.org/a23wbs0lv/wind.png

**Comment by Coolthulhu** [comment]
As far as I recall there is a hardcoded limit on effective vehicle weight for purposes of jacks and cranes.
Boom cranes should be able to lift all vehicles because of that cap.

**Comment by Firestorm01X2** [comment]
>As far as I recall there is a hardcoded limit on effective vehicle weight for purposes of jacks and cranes.
Boom cranes should be able to lift all vehicles because of that cap.

What is that cap. 6 tonnes?

**Comment by Firestorm01X2** [comment]
// cap JACK requirements at 6000kg to support arbritrarily large vehicles

**Comment by Firestorm01X2** [comment]
Here it is: https://github.com/CleverRaven/Cataclysm-DDA/pull/18979

Current PR will have only visual effect on Boom crane stats if we take JACK requirment limit for vehicles.

**Comment by mugling** [comment]
> As far as I recall there is a hardcoded limit on effective vehicle weight for purposes of jacks and cranes.
> Boom cranes should be able to lift all vehicles because of that cap.

The cap is broken - we should fix that as opposed to this PR.

**Comment by mugling** [comment]
As above we should fix the broken cap in the code as opposed to implement a JSON workaround

**Comment by Firestorm01X2** [comment]
Wait. Are you sure that broken cap bag realy exist?
Look at this closely: https://github.com/CleverRaven/Cataclysm-DDA/pull/18979

It is just cap, that restricts weight requirement for jacks. That is why boom crane can lift anything. I thought it is obvious.

**Comment by mugling** [comment]
I'm pretty sure the relevant code is in `veh_interact.cpp`. I'll take a look

**Comment by Firestorm01X2** [comment]
It is even commented:
// cap JACK requirements at 8000kg to support arbritrarily large vehicles

**Comment by mugling** [comment]
The bug is that `LIFT` is supposed to be an equivalent to `JACK`

**Pull request closed without merging**
