### PR TITLE
Cleanup office tower, room dividers

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
Content "Office tower cleanup, updates office nesteds, adds room dividers"

#### Purpose of change

I came to cleanup office_tower.json and office_nested.json, and stayed to overhaul the short office tower.

#### Describe the solution

office nested chunks:
* gave them more descriptive names — even I forgot what the old names were supposed to mean
* moved things around so that nested chunks with a similar purpose are now next to each other
* removed redundant rotation values
* removed floors and brick walls for added compatibility
* shrank some nested chunks to remove unused space
* added a microwave and a coffee maker to the breakroom chunk
* replaced walls with new furniture: room dividers — this should increase the 'officey' feel of the two versions
* minor reworks for a few nested chunks
* replaced random counters with desks
* fixed swivel chair placements

Large office tower:
* removed useless solid earth, as mentioned in #58162
* moved nested lists (about 280 lines) to the palette
* replaced hardwood flooring with linoleum to further differentiate the two versions
* added SUS item groups
* replaced `place_monsters` with `monster`, `place_vehicles` with `vehicles`
* replaced uncomfortable lobby benches with sofas
* added proper elevator controls
* repalettized roof to use the dedicated roof palette, also fixed roof nested chunks

Office tower:
* renamed to 'office building', as mentioned in #62747
* removed useless solid earth, as mentioned in #58162
* replaced `place_vehicles` with `vehicles`
* reworked ground floor to utilize office nested chunks
* added proper elevator controls
* repalettized roof to use the dedicated roof palette

#### Describe alternatives you've considered

Adding room dividers to a couple more locations.

#### Testing

Debug-spawned multiple times to check if nested chunks spawn alright.

#### Additional context

<details>

  <summary>Screenshots:</summary>

Nested chunks are highlighted.

Office building:
kép

Office tower:
kép

</details>

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Should this close #58152?

**Comment by LovamKicsiGazsii** [comment]
> Should this close #58152?

Do you mean #58162? AFAIK the apartments still have those soil walls, so the issue is not yet resolved.

**Comment by Night-Pryanik** [comment]
Ok, got it.

**Review by Maleclypse — APPROVED** [review]
I appreciate it.  Any cleanup you want to do to the Xedra Office is great.  I'm not great at mapgen.

**Comment by LovamKicsiGazsii** [comment]
> I appreciate it. Any cleanup you want to do to the Xedra Office is great. I'm not great at mapgen.

For another PR, sure.

**Pull request merged**
