### PR TITLE
[WIP] make forest_trail qualify for faction purposes

### LINKED ISSUE #30408: NPC Camp: Forest trails invalid for logging/cutting/fortifying
**Describe the bug**  
On attempting to "Cut Logs" or "Clear a forest" and selecting an overmap "Forest Trail" tile, it reverts to initial prompt asking to select a tile to log. Admittedly the prompt does specify 'forest' and 'swamp' as being allowed selection for loggings and 'forest' as the only acceptable option for clearing, but it is rather perplexing that the presence of a minor dirt path prevents cutting trees there.

Similarly for the "Construct Map Fortifications" task, it specifies that forest, swamps and fields are valid options only, and having a forest trail included between the two designated points to dig a trench gives a "invalid terrain in construction path"

**To Reproduce**  
1. Make an NPC camp, reach level for cut logs, clear forest, make map fortifications.
2. Attempt to include a forest trail in the selection of either of the listed tasks

**Expected behavior**  
A forest trail is just a rough dirt path through the forest, it should not prevent the cutting of trees to convert it to a field-type over time, or of having a companion dig a trench through it to make a fortification. Adding the forest trail map type to acceptable tiles is (probably) all it needs to work.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version: 0.D-2786-gb574176
 - Graphics version: Tiles

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "make forest_trail qualify for faction purposes"```

#### Purpose of change
Fixes #30408

#### Describe the solution
Identifies the 'forest_trail' overmap terrain as a valid 'forest' area for faction purposes.

#### Describe alternatives you've considered
N/A

#### Testing
Clang hates me. Pending CI checks.

Addendum: I waited for the CI checks so that I didn't have to compile multiple times myself in case any of the CI checks came back negative, lazy bugger that I am with a hatred for clang. Once they all looked alright(ish) I compiled it on ye ole server, downloaded it, and did some quick testing by spawning a veritable army of NPCs and tossing them around.  I removed the [WIP] prefix from the title and marked it ready for review after it seemed to have fixed the bugs in the tagged issue above. The changes were small, didn't think it needed more than a quick test.

#### Additional context
N/A

### CODE REVIEW

**Comment by korvyr** [comment]
astyle regressions eh? fine, fine...

**Comment by esotericist** [comment]
Please elaborate more in your post on what testing you did to verify that this works in-game as you expect.

**Comment by korvyr** [comment]
> Please elaborate more in your post on what testing you did to verify that this works in-game as you expect.

Sure thing.

**Comment by ralreegorganon** [comment]
This does not work.

Forest trails are a linear feature, which means that their actual id is more complicated than `"forest_trail"` and because this code is doing direct string matches on id, it will never resolve a match to `"forest_trail"`.  If you pop open an overmap save file you'll see ids like `forest_trail_nes`, `forest_trail_end_west`, `forest_trail_es` and so on.

To actually match a forest trail you need get the underlying type for it which WILL resolve to `"forest_trail"`. The appropriate mechanism for this comparison is to use `is_ot_match` which allows specifying your target id string and an `ot_match_type`, which in this case should be `ot_match_type::type`, like this: `is_ot_match( "forest_trail", omt_ref, ot_match_type::type )`.

You would need to not only use this where you've done a manual match like [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/35214/files#diff-f0b0c8fa40ef01f73d3a3913c5e2afccR1731) but you'd also need to update [om_target_tile](https://github.com/CleverRaven/Cataclysm-DDA/blob/da37b0bb34bb9b7c26eb9c92c774290cd11852ee/src/faction_camp.cpp#L372) to use `is_ot_match` and a collection of matches rather than string equality and a vector of strings--and that change is a PR that should be done all on it's own, since it's pretty high impact.

**Comment by korvyr** [comment]
Interesting. Obviously needed more than just quickly tossing NPCs around.

There's an example of exactly what you mention in the same function. I'll knock it out this afternoon.

**Comment by korvyr** [comment]
Going to attempt to go at this from a different angle. Revert time.

**Pull request closed without merging**
