### PR TITLE
Improve monster tracker by eliminating the unecessary vector member.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: Performance "Overhauled monster tracking class to stop using a vector."

Do be careful with this PR, it's adjusting a pretty core part of the game and might break something badly.

#### Purpose of change
I noticed when profiling with a huge number of zombies nearby (~5,000) that an inordinate amount of time was being spent in creature_tracker::update_pos().  Since one of the backing containers for the tracker was a std::vector, it required a scan through the vector to find a monster, which made updating position scale linearly with the number of monsters, but if you consider moves taken over the course of a turn, it made monster movement scale exponentially with number of monsters.

#### Describe the solution
I refactored callers of the tracker to no longer require the monsters to be stored in a particular order (mostly serialization), and then removed the list, now monster moves are (amortized) constant time with respect to number of active monsters.
I also dialed down the frequency of random stumbling movements from 1/3 turns to 1/10 turns, it was an arbitrary number in the first place and necessary to keep so high.

Between these changes time spent dealing with monster stumbling in my test case went from 20% to 6%.

#### Describe alternatives you've considered
Just reducing the stumble frequency would have addressed my particular issue, but other similar scenarios like "being chased by 1,000 zombies" would still be problematic.
Overhauling the creature tracker more extensively is an option, but it's quite central to the game and quite fiddly to adjust, so I'd rather not get into that at the moment.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I am not sure yet if it is this PR, but I got crash twice with command line message:

```
pure virtual method called
terminate called without an active exception
```

**Comment by ZhilkinSerg** [comment]
image

**Comment by ZhilkinSerg** [comment]
I've started new world with 50x monster spawn, wander spawns on and surrounded start. Debug mutated to invincibility, debug teleported to pile of monster and waited there until game crashed.

**Comment by kevingranade** [comment]
Well crap, I finally have a chance to test it and I'm not getting a crash...

**Comment by kevingranade** [comment]
There we go, reproduced with your instructions, related to monsters considering each other as targets maybe?

**Comment by kevingranade** [comment]
You posted what it is, "pure virtual method called".
Guess I'm being slow. 

My only guess is I'm doing something to make it lose its type data...

**Comment by kevingranade** [comment]
Ran across a reference that this can be a symptom of deference after free, so that's my top candidate.  I wonder if I'm breaking the shared pointer relationship somewhere.

**Comment by kevingranade** [comment]
I think no see the problem now, if one creature died and another creature stepped into the same tile on the same turn, the previous code would remove the dead creature from the map but leave it on the list, and this code will instead overwrite the dead monster entry with the live one, but then a subsequent monster planning pass would try to access the now-deleted object in the faction map.

I'm adding a dead monster list to keep monster entries valid until they can be properly cleaned up.

**Comment by kevingranade** [comment]
Last guess was correct:
1. Monster turn starts, the code builds a map of faction entries to optimize monsters targeting each other.
2. monster A dies
3. monster B steps onto the tile with monster B.  This was causing the creature tracker to discard the monster since it didn't have anywhere to put it.
4. Monster C attempts to consider monster A as an enemy, triggering an access of the now-invalid pointer in the faction entry.

I fixed it by pushing dead monsters onto a dedicated list if they conflict with a live monster.

There's a much more extensive fix that exposes weak_ptr s to monsters all over the place, I'm a bit sceptical that I really want to do that.

**Comment by kevingranade** [comment]
This should be hood to go btw.

**Comment by ZhilkinSerg** [comment]
Time to sleep besides thousand of zeds.

**Comment by Balgamtr** [comment]
https://www.reddit.com/r/cataclysmdda/comments/9x2ciu/with_zui_quan_game_is_still_playable_after_last/

**Pull request merged**
