### PR TITLE
Calories tracking for QOL

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
Features "Calories tracking for QOL"

#### Purpose of change

Nutrition system has become very robust lately (that's good). This results in necessity of tracking of what & when you eat. There are already some feedback systems like hunger, satiety, calorie density etc., but up until now there was no way to track what your character ate calories-wise, other then writing it down and trusting your stomach (which can't be trusted for that purpose).

#### Describe the solution
This quality of life change introduces a new feature for calories intake and expenditure measurement:
- [x] calorie tracking in Consume Menu (scalable)
Consume (Eat) menu will now show estimates about daily calories intake - based on fractions of `base_bmi` (base calories expenditure of non active character including metabolism traits).
This information will be expanded if you have tracking items as mentioned below.

- [x] calorie intake tracker for your smartphone
If you have a smartphone it will show you ("registered in an app") daily consumed calories for today and yesterday.
This feature can be also invoked by activating your smartphone.

- [x] calorie intake and expenditure tracker for your fitness band
If you wear a fitness band instead it will show you both calories consumed (intake) & spent (burned) today and yesterday.
This feature can be also invoked by activating your fitness band.

#### Describe alternatives you've considered

There are more paths to go from here:
- option to hide kcal info for comestibles (replacing with estimates) for more hardcore gameplay
- hobbies and/or professions for exact calories count (dietician)
- adding steps per day and other movement related statistics to fitness band from score trackers / event bus

#### Testing

Compiled. Invoked Consume Menu, with and without smartphone & fitness band, in few scenarios that included eating various foods and passage of time. Activated said items for effect.

#### Additional context
Eat menu without trackers:
image

Eat menu with smartphone:
image

Eat menu with worn fitness band:
image

Activating smartphone:
image
image

Activating fitness band:
image

### CODE REVIEW

**Comment by GoLoT** [comment]
My only gripe with this is that it doesn't actually "track" calorie intake, it "checks" it. It'd be more realistic to use the separate counter so it only increases if you eat while having your tool at hand (e.g. call `add_ingested_kcal()` only if you have a phone/band in your inventory). It should be an easy change but this might be me nitpicking.

**Comment by nexusmrsep** [comment]
>  it doesn't actually "track" calorie intake, it "checks" it

I'm fully aware that the current implementation takes the liberty of some mental shortcuts. One thing is what you mentioned, but there are others. For example how would you explain that if you throw out your smartphone and later that day pick another that it shows your registered values? It's a mental shortcut for having that info in a "cloud" but then "how is internet even working", etc. This is partially the reason why I refrained from longer tracking history and cut it to two days only.

Per device tracking and registering only in the presence of the device would be much harder to implement, and might ruin the QOL benefit. It still can expanded later if need be.

**Comment by GoLoT** [comment]
> Per device tracking and registering only in the presence of the device would be much harder to implement, and might ruin the QOL benefit.

Agreed. I wouldn't go that route either, global tracking is good enough either way (storing all values or only when you have a device).

> It's a mental shortcut for having that info in a "cloud" but then "how is internet even working", etc.

There is Bluetooth that can sync multiple devices you own (i.e. your fitness tracker with your phone) and could justify not losing data when changing devices, just as a suggestion. But I'm fine with the current implementation, nitpicks aside.

**Comment by Amoebka** [comment]
From a QoL perspective, requiring any tool at all is undesirable. Foods display perfectly accurate calorie counts, so a player (or the character) can write them down and add together with any writing tool. It becomes a choice of "do you want to manually count your calories out of game" or "do you want to only get an inaccurate estimate, even though you could have calculated accurate values".
Smartphones are dirt common, so it's not really a big hurdle to clear, but that's even more of a reason to ditch the requirement altogether.

**Comment by nexusmrsep** [comment]
> that's even more of a reason to ditch the requirement altogether.

Yes and No, at the same time.

- Knowledge of exact calories amount is a kind of meta-knowledge and I will treat it as such. Thus one meta-knowledge is no justification for introducing other meta-knowledge, period.

- I am willing to go the other way though - after introducing the optional feature of hiding the exact calorie count knowledge from food (Soon™) and replacing it with estimates I can make it so that if you opt-out from it, you'd also see exact calories intake in the Eat menu regardless from having a tracker at hand.

**Comment by thuctran289** [comment]
As a side comment, I think that CAMERA items actually do have a per-item tracking of the photos [which record date/situation/etc], so this might be a situation to implement an analogous thing if we wanted to do a more accurate tracking.
 
I do think that it might be interesting to see some kind of feature of amortizing/consolidating data from different devices, but that I think a bigger challenge. 

Somewhat unrelated, any thoughts on having the precision of the calorie estimates be based on nutrition proficiency?

**Comment by nexusmrsep** [comment]
> Somewhat unrelated, any thoughts on having the precision of the calorie estimates be based on nutrition proficiency?

Not a bad idea for possible future development. Like I said in the introduction: for example a dietitian profession with relevant proficiency that can be also learned somehow that would do the above is totally feasible in my opinion.

**Pull request merged**
