### PR TITLE
Added Flamethrower mags to spawns.

### PR DESCRIPTION
**Pull request by Soyweiser**
#### Summary
SUMMARY: Bugfixes "Added flamethrower magazines to all flamethrower spawns, magazine spawns to a lot of guns missing them, and launchers now spawn with ammo."

#### Purpose of change
Flamethrowers (almost) never seemed to spawn with magazines, this fixes that, I also added a lot of magazine spawns to other gun spawns in the generic guns spawn list. To prevent the annoying problem where your gun has no magazine (and it might not even spawn anywhere ingame). As an added bonus one of the launchers spawns now also spawns with ammo.

#### Additional context
You can craft a 'small pressurized fuel tank' for the aux flamethrower. But not the 'pressurized fuel tank' for the flamethrower. Perhaps we should add the 'small pressurized fuel tank' as a potential magazine for the normal flamethrower.

Tested the changed item_groups with the ingame debug menu item_group tester.

Thanks Highwayman on discord for pointing it out (indirectly).

### CODE REVIEW

**Comment by ymber** [comment]
When I added fuel tanks for flamethrowers I left the standard ones uncraftable assuming they has to be build to better standards than the survivor scrap aux flamethrower.

**Comment by AbsalomAchitophel526** [comment]
The "simple" flamethrower also requires the uncraftable pressurized fuel tanks, despite being a crafted scrap weapon.

**Comment by BorkBorkGoesTheCode** [comment]
Adding 100% guaranteed gun magazines to nearly every gun spawn is too excessive; you can add magazines to the specific location and mapgen extra spawns you think are deficient without doing this.

**Comment by ZhilkinSerg** [comment]
Changes to magazine spawn look rather controversial on the second look, so I've reverted it to restore previous status quo. Such changes will need more playtest than I did on the initial occasion.

**Comment by kevingranade** [comment]
Needs a justification for why these locations should always spawn guns worth magazines.  "Because it's annoying" doesnt mean it needs to change.

**Comment by Soyweiser** [comment]
Well atm, there are not enough magazine spawns in the game. Various magazines spawn so rarely that you cannot use those weapons ever. (people complain about this with the rivtec guns semi regularly).

Add to this that as the game grows in content, both locations and more weapons/magazines, the chance of finding a working rare weapon (you need : ammo, magazine, and the weapon) massively decreases. (each new location decreases the chance of the more rare military spawns, each additional magazine/weapon in those droplists also decreases the chance of finding the 3 matching items you need for a working gun). Due to these factors, all the interesting strong weapons that spawn (compared to the common glocks) will be pushed more and more into endgame, and less and less players will experience this content.

Add tot his that nobody thinks to ever include magazine spawns in locations at all. Gun spawns are several times more common than magazine spawns. (which is a bit unrealistic, as I assume people have more magazines than guns if they own guns, and it is unrealistic that there are so many mismatched mags/guns).

I could go and update all the locations in the game and add new magazine spawns to various locations, but that is:
* A lot of work (and this still has the problem of large amounts of mismatched magazines/guns) 
* Not a good long term solution as every new location/gun/magazine/etc that is added will also have to be checked by devs to ensure that the objects actually spawn in usable levels.

Sure, we could keep the various things as rare as they are now, but that imho just makes stuff so rare that it cannot be found realistically ingame except for a few players with a very high amount of ingame time. (This also means that various (coding) efforts to improve rare guns is pretty much wasted time, as the guns are never used ingame). It also forces people who add content (and people who check this content) to do more work, which seems like a waste of time.

**Comment by Soyweiser** [comment]
Ow yeah, there are a lot of ideal things that could be changed on the spawn system to make it perfect. But that takes up a lot of time, I just wanted to make it a little bit better. (enemy being the perfect of the good and all that). But I upped the scope past my initial fix (the flamethrower thing) so it is debatable if adding more mags is a way forward (I think it is, others appantly agreed).

As the flamethrower thing still needs to be fixed, im going to create a differnt pr just to fix that.

Ideally we various new spawns like : 'spawn gun with mags with ammo, but not loaded', 'this area has the theme 556 ammo, spawn guns/mags/ammo with 556 ammo' 'this area has the theme that it only spawns unloaded guns, spawn from this gun list, but no ammo/mags etc' 'this is the fuck you area, spawn rare items, but none in working condition' (all random examples on the top of my head) but all that is a bit more work to implement.

**Pull request merged**
