### PR TITLE
Add basket fish trap (plastic free)

### PR DESCRIPTION
**Pull request by merrygin**
#### Summary
Content "Adds basket fish trap (plastic free)"

#### Purpose of change
Currently, there is only the option to make makeshift fish traps from plastic bottles. Especially for wilderness runs (/innawoods) this is unnecessarily limiting, as non-plastic (mostly woven) fish traps are very common for numerous pre-industrial societies all over the world.

#### Describe the solution
Add the option to craft a fish trap without needing plastic. More concrete: add a woven fish trap that uses the basketweaving proficiency, adding a new item+recipe.

Values for crafting time, requirements (skill + materials) and properties (weight, length, etc.) I am eyeballing values for crafting time, requirements (skill + materials) and properties (weight, length, etc.) a bit. The idea is to take this as the model:
Đó
So roughly in the ballpark of 50x18x18cm, quite voluminous with 12l. 
I decided to use survival 4 as primary and tailoring 3 as secondary skill, to keep consistent with other fishing implements on the one hand (hobreel is survival 4 as well) and basketweaving items (which use tailoring).
The idea would be that this is a mid-tier/advanced item, since, when positioned at the right spot, this will generate quite a lot of food. Maybe bumping up the skill level even more because of that would be in order (survival difficulty 5, for example, also to provide a reason to even craft other fishing tools like the hoboreel instead of this trap).

#### Describe alternatives you've considered
Could also just add crafting requirements variants, for example adding "plant_cordage" types next to the plastic bottles. That would mean no new items/recipes need to be created (thus, avoid bloating). At least the description text would need to reflect that though, as it specifically refers to the item as being a simple, primitve plastic bottle-based tool. 
On the other hand, with the basketweaving proficiency existing, having a basket option for crafting the exisiting fish trap item without that proficiency would add inconsistency.

**_Also_**
Ideally, a new/seperate item could also represent a better tier of fish trap, working more effectively (like the distinction of basic vs. pro fishing rod). However, the fish trapping function is C++ territory afaik, which I don't know how to manipulate. This would also make it more justifiable to add a new item+recipe. Maybe someone is able and willing to help with the C++ portion? Otherwise, the RP can just stand for itself.

#### Testing
Tested crafting the item, generating it as well, and successfully catched some fish with it.

#### Additional context
References for basket style traditional/survivalist fish traps:
https://www.youtube.com/watch?v=1bAedGSUcro
https://www.youtube.com/watch?v=vbhiuFYa-sQ
https://www.fao.org/3/X2590E/x2590e07.htm
https://en.wikipedia.org/wiki/Fish_trap (although i actually primarily used the german one, since I am german)
https://www.reddit.com/r/cataclysmdda/comments/dx6kz2/my_studies_in_fishing_experimental_9903/

### CODE REVIEW

**Comment by merrygin** [comment]
I very much appreciate feedback on the idea, but also on the specific values for skill req, materials, weight/volume and all that stuff!

**Comment by merrygin** [comment]
Ok, something's up with the json formatting, despite me using the weblinter. There is clearly something I am missing?!

**Comment by bombasticSlacks** [comment]
gotta lint both files you changed. The recipe file should look something like this 
```json
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "fish_trap_basket",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "tailor",
    "skills_required": [ [ "survival", 3 ] ],
    "difficulty": 3,
    "time": "10 h",
    "proficiencies": [ { "proficiency": "prof_basketweaving" } ],
    "qualities": [ { "id": "CUT", "level": 1 } ],
    "components": [ [ [ "plant_cordage", 12, "LIST" ] ], [ [ "cordage", 2, "LIST" ] ] ]
  }
```

**Comment by merrygin** [comment]
Thanks a lot! 
Weirdly, thats not the format the weblinter gave me. Maybe its not up to date (or I used it wrong)? I saw now though that the check also provided the answer, so I'll keep an eye on that next time. ^^

**Comment by merrygin** [comment]
Not sure why some of the checks failling (they didn't before I changed the material values like length). latest error was:
(~[slow] ~[.],starting_items)=> ../tests/weakpoint_test.cpp:96: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( wr2.PercHits( "the bugs" ) == Approx( 0.25f ).epsilon( 0.20f ) )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   0.3f == Approx( 0.25 )

What do I make of that?

**Comment by bombasticSlacks** [comment]
Sometimes tests fail.

The head maintainers have been busy with projects so they haven't been reviewing and merging much for PR's other than small typo fixes and critical bug fixes. It's not a random test failure that is keeping this from being merged. 

I can't say with 100% confidence but it looks like this will be merged in the next batch merge which should be soon :)

**Comment by remd** [comment]
@merrygin Is it intentional that the plastic fish trap recipe received autolearn at Survival 2, requires Basketweaving, and the recipe for a basket fish trap has no recipe source or autolearn level?

I think that lines 1476-1477 in `recipe_others.json` might be intended to apply to `fish_trap_basket` only. Is that true?

**Comment by merrygin** [comment]
> @merrygin Is it intentional that the plastic fish trap recipe received autolearn at survival 2, uses Basketweaving proficiency, and the recipe for a basket fish trap has no recipe source or autolearn level?
> 
> I think that lines 1476-1477 in `recipe_others.json` might be intended to apply to `fish_trap_basket` only. Is that true?

woops, don't know how I missed that, very sorry. What a stupid mistake, probably shuffled around stuff absentmindedly. Gonna have to fix that with a new PR right?

**Comment by remd** [comment]
No need to apologize, I appreciate your contribution to the game! 

Yes, a new PR will be necessary for additional code changes.

**Pull request merged**
