### PR TITLE
New player bases: Evac Shelter 1

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds a map for a player-NPC camp built around a type 1 evac shelter"```

#### Purpose of change
Currently base camps can only be built if the player and an NPC are out standing in their field.

Some day it will be great to build base camps that are more fluid in structure, fitting into any building. In the meantime, though, a good interim solution is to allow basecamps to be built in existing structures. A very obvious example of this would be to recruit the NPC to assist in reinforcing and securing the starting evac shelter.

#### Describe the solution
This adds a series of maps, in "phases" of development, that reinforce the shelter and turn it into a decent player-NPC base.

Unlike the original base camp, I am allowing some flexibility here by making each phase have an option for which upgrade to take. These are differentiated in map name as "a" and "b" options. You do still need to get both upgrades before moving to the next phase (the number of maps becomes prohibitively high otherwise.)

#### Tentative plan

0. Create a base camp in the shelter. No structure changes.

1a. Convert one of the lockers to a brazier. No material requirements for this one. The mission should perhaps produce leftover material from the process.
1b. Board up all the windows and one each of the doors, still leaving point entries on each side.
1. Both boarded windows and a brazier have been built.

2a. Construct makeshift beds for the player and NPC
2b. Dig some simple pits outside doors to deter zombies.
2. Both pits and beds.

3a. Add spikes to pits outside.
3b. Dismantle extra furnishings in shelter, to produce nails and wood.
3. Spiked pits and furnishings dismantled.

4a. Make a wider perimeter of pits to begin preparations for an outer defensive wall.
4b. Upgrade remaining benches to a working/dining area.
4. Outer perimeter 1/2 done, table built.

5a. Finish outer perimeter of pits.
5b. Reinforce boarded windows and doors.
5. Finish perimeter, reinforce.

6a. Begin construction of a junk metal wall around base.
6b. Upgrade sleeping arrangements and dig a well pit.
6. Junk wall 1/2 done, bunkhouse rooms laid out

7a. Complete junk metal wall around base.
7b. Finish rooms and work on well.
7. Junk wall done, well begun.

8a. Finish well.
8b. Expand storage shelves in building and add a comfy sofa by the light.
8. Both of the above.

Going forward
-add an outbuilding for a generator, build a generator, and have powered lights inside the base
-build metal doors in junk wall
-build a root cellar

#### Describe alternatives you've considered
I could use a more linear format, without choices at each phase, but I like the idea of letting players set some of their own priorities, and it really doesn't add much work.

#### Additional context
- I would like to revisit the original canvas base camp and consider reducing its reliance on a huge number of tents right at the outset. However I don't know how interested I am in playing around with the existing camp rather than just making more possible varieties of camp.
- This does not include C++ support for the camp. Just maps.

#### Progress
- [x] Phase 0 - make files, clean up file structure
- [x] Phase 1
- [x] Phase 2
- [x] Phase 3
- [x] Phase 4
- [x] Phase 5
- [x] Phase 6
- [x] Phase 7
- [x] Phase 8
- [ ] add recipes for construction

### CODE REVIEW

**Comment by Wokko1** [comment]
I never really played with faction camps, but what if the player destroys the lockers/windows/doors before upgrading? Would it lead to some strange behaviour like making braziers out of thin air? Will it just require more materials, or completely block the option to make a camp on the evac shelter?

**Comment by I-am-Erk** [comment]
Presently, the system isn't smart enough to notice if the landscape has changed. This is a problem with the existing faction camp as well; you can dismantle the stuff in the camp to get material to expand the camp with. Improving that ties into making flexible camps. For now though, this works well enough.

**Comment by I-am-Erk** [comment]
This is about ready to go. I may add a few more phases based on feedback, but I'd love some opinions on the current layout. I will see about making a map that has all 8 phases side by side for comparison

**Comment by chaisawlajatang** [comment]
There are several types of shelter layouts in the game. Wouldn't it work for the one particular layout only?

**Comment by I-am-Erk** [comment]
Yes, that's why it's called "shelter 1"

**Comment by ZhilkinSerg** [comment]
Can you please resolve conflicts?

**Comment by I-am-Erk** [comment]
Given how much needs changing it's probably simpler for me to close this and reopen it with new material.

**Pull request closed without merging**
