### PR TITLE
Remove the baseball with barbed wire wrapped around it

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
Noticed this existed when it shouldn't.

#### Describe the solution
Removed the definition and recipe and migrated instances to regular baseballs.

#### Describe alternatives you've considered
A game where we do silly things for no reason? Ehhh pass.

### CODE REVIEW

**Comment by Fris0uman** [comment]
The tileset edits will get overwritten next tileset update

**Comment by KeremBabaG** [comment]
My heart skipped a beat because I thought you were removing the barbed baseball bats

**Comment by SariusSkelrets** [comment]
That was my first reaction when reading it

Then I read closer and it changed to "we had balls wrapped in barbed wire? Who ever thought that making such a thing was a good idea? Sounds like a massive pain to throw, the kind of weapon hurting the user more than the target"

**Comment by kevingranade** [comment]
And sticking it in a staff sling is no better,  how would it not get stuck in the pouch?

**Comment by Cormac1991** [comment]
sounds like something youd see in a zombie game, just not this one, because its shooting for realism, just ignore the acid spitting ants . . *enters tear in reality*

**Pull request merged**
