### PR TITLE
Fix field related segfault

### LINKED ISSUE #47308: Crash to desktop. Invalid field types id "65537". Unknown intensity level 65543 for field type .
# Describe the bug

My game has crashed several times and shown the debug messages:
Invalid field types id "65537"
NEW Invalid field types id "458759"
Unknown intensity level 65543 for field type .
NEW Unknown intensity level 196615 for field type .

I've noticed that all the crashes happened as I drove near forests at night.

# Steps To Reproduce

I've loaded the game and drove through the same path but the game wouldn't crash.
1. Drive near forests at night.
2. Hope the game crashes.

# Expected behavior

Driving at night near forests should not cause crash to desktops.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9461-g0638fba7a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

Save game, debug.log, crash.log.
[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5939479/Champlin.zip)
NEW
[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5939742/Champlin.zip)

### PR DESCRIPTION
**Pull request by Trioct**
#### Summary
None

#### Purpose of change

Fixes #47308
#47076 introduced a couple of crashes all related to the same thing

#### Describe the solution

`map::mod_field_intensity` sometimes calls `remove_field`, whereas `field_entry::mod_field_intensity` doesn't.
Use the one that won't bust my pointers.

#### Describe alternatives you've considered

The naming scheme + hidden side effects seems pretty confusing honestly, as you can tell by the fact that there's like 12 lines of comments for these three loops describing how to not break everything. Unfortunately, comments aren't legally binding.

I also don't know why `cur.set_field_intensity( cur.get_field_intensity() - 1 );` was changed to `mod_field_intensity( u.pos(), ft, -1 );`, or why `cur.mod_field_intensity( -1 );` wasn't used in the first place. I think I've looked too deep into the spaghetti. Maybe @Aivean can save the day.

#### Testing

Failed to crash my game using sap and webs layered with 300 other fields where previously it would.

### CODE REVIEW

**Comment by actual-nh** [comment]
@Trioct: Before the fix, did the errors look like #47308?

**Comment by Aivean** [comment]
Thank you for spotting this. I’m away from my laptop at the moment, so I’ll post more detail later, but the brief version is following:
Both `cur.set_field_intensity( cur.get_field_intensity() - 1 )` and `cur.mod_field_intensity` ignore map cache invalidation, while `map::add_field`, `map::remove_field` and `map::mod_field_intensity` properly invalidates map caches. Also see `map::on_field_modified`.

The proper fix to this issue would be to fix the semantics of `map::mod_field_intinsity`, so it doesn’t lead to crash in the first place.

**Comment by Trioct** [comment]
> Before the fix, did the errors look like #47308?

Yep, thanks for linking the issue.

And aivean, yeah, I was aware this seemed a bit like slapping a bandage on the problem rather than *actually* fixing the code, but I kind of lost track of the intent of the code and just decided to throw a fix on it. I understand it a bit better today though, and am thinking I could just simply subtract from the field intensity in `mod_field_intensity` and let it get cleaned up later in `process_fields`, but I can't think of whether the `add_field` in `mod_field_intensity` could cause a crash too? Maybe I could do with a specific function called like `safe_sub_field_intensity` or something.

**Comment by Trioct** [comment]
#47329 looks like a better solution.

**Comment by Aivean** [comment]
> And aivean, yeah, I was aware this seemed a bit like slapping a bandage on the problem rather than _actually_ fixing the code, but I kind of lost track of the intent of the code and just decided to throw a fix on it. I understand it a bit better today though, and am thinking I could just simply subtract from the field intensity in `mod_field_intensity` and let it get cleaned up later in `process_fields`

I agree that marking field as "not alive" and cleaning it up later is a way to go. I've put together a PR that uses this approach:  #47329. With it, all field related methods in `map` are safe to use.

> but I can't think of whether the `add_field` in `mod_field_intensity` could cause a crash too? Maybe I could do with a specific function called like `safe_sub_field_intensity` or something.

The root issue is `std::map` iterator invalidation. It was happening only when field was removed by `map::remove_field` or intensity was set to zero (by `map::set_field_intensity` and `map::mod_field_intensity`). So, `map::add_field` was safe, but other methods were not.

**Comment by Trioct** [comment]
I should've let you comment before closing this so quickly, but thanks for the alternative. I'm much more confident in your solution than mine. It looks much safer and more coherent. Shows which one of us in more experienced for sure :P

**Comment by Aivean** [comment]
> I should've let you comment before closing this so quickly, but thanks for the alternative. I'm much more confident in your solution than mine. It looks much safer and more coherent. Shows which one of us is more experienced for sure :P

It's fair that I'm more familiar with the fields code, I introduced that bug in the first place ;)

**Pull request closed without merging**
