### PR TITLE
Alterations to steel spear and other polearms

### PR DESCRIPTION
**Pull request by DangerNoodle**
First change is reworking the steel spear. Instead of a fast, small spear improvised from a pipe with scrap metal, the spear has been changed to a forged weapon, of a similar recipe quality as the forged sword. The spear has been increased in bulk and damage, and given the same to hit as the dory and qiang. Moves per attack has therefore increased from 108 to 137, while effective damage per turn has been increased from 26.48 to 29.78, slightly below that of the qiang.

Due to requests from commenters, the older makeshift spear has been retained as an option in the form of the pipe spear.

The dory, being a heavy bronze spear with an effective damage per turn of 32.65 due to high base damage, as had base damage lowered by 4, making the effective damage per turn 29.38. Ideally bronze weapons should be comparable to or slightly better than iron ones, while inferior to steel.

The ji has also had its damage lowered slightly and differentiated from the halberd. Both had the same combined damage of 51 and the same moves per attack. The ji has had total damage reduced to 47, making for an effective damage per turn of 31.86. Both retain their weights and volumes however, as I was uncertain how best to alter those.

Lastly, the handle wrapping in various spear recipes has been standardized around allowing rags, felt patches, leather patches, or fur pelts.

Main reasoning is that the various polearms have not been as strongly affected by prior rebalances, leaving some with disproportionate damage relative to other spears that have been rebalanced. The steel spear is also an oddball weapon that could be adapted to fill the missing role of a bog standard spear, of forged quality that is still more accessible than the book-learned polearms.

### CODE REVIEW

**Comment by Mecares** [comment]
Maybe leave the old one in the game named "pipe spear"?

**Comment by Zilenan91** [comment]
yeah if you left it in and called it a pipe spear that'd be nice. It has a niche that's very useful and would remain unfulfilled in gameplay.

**Comment by DangerNoodle** [comment]
Very well then.

**Comment by DangerNoodle** [comment]
Additonally observed that most of the medieval polearms, including the awl pike, have `DURABLE_MELEE`, but the qiang does not.

**Comment by Coolthulhu** [comment]
Halberd is already worse than naginata, despite comparable recipes.

If you want to establish some sort of balance here, it would be good to rate the value of reach in some way. Say, effective damage per turn multiplier.
Otherwise the balancing becomes arbitrary and hard to keep consistent.

Looking at your numbers and https://github.com/CleverRaven/Cataclysm-DDA/wiki/Weapons-Balance it would make sense to treat reach 1 as ~25% increase in DPS, as halberd is a good example of a weapon of war.

Do you have the rights to edit https://github.com/CleverRaven/Cataclysm-DDA/wiki/Weapons-Balance ?
If you do, add the reasoning there too. Can be in techniques - reach isn't exactly a technique, but it's very close to being one.

**Comment by DangerNoodle** [comment]
I see. Should I undo the change to halberd then, or more than that?

**Comment by Coolthulhu** [comment]
Revert the nerf or nerf naginata too. Or both.
Also check other reach weapons - if you're rebalancing some of them, they shouldn't get too much out of line from the rest, unless there is a reason for that.

**Comment by DangerNoodle** [comment]
I reverted the halberd nerf for now. The ji remained slightly nerfed largely because beforehand the two weapons had identical damage and moves per attack, differentiated only by different ratios of bash and cut damage.

I would want to further evaluate and determine a plan for balancing all other polearms, but that might be best for a later pull request. Current changes are already rather extensive.

**Pull request merged**
