### PR TITLE
Code optimizations reported by static code analysis (2019-05-13)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

SUMMARY: Performance "Code optimizations reported by static code analysis"

#### Purpose of change

Cleanup code while increase performance and fix minor errors.

#### Describe the solution

See commit messages.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm a little concerned that some of these include changes are undoing what IWYU has done.
Can you run that locally?

**Comment by ZhilkinSerg** [comment]
> 
> 
> I'm a little concerned that some of these include changes are undoing what IWYU has done.
> Can you run that locally?

Not yet, but maybe @jbytheway can run it on this PR?

**Comment by ZhilkinSerg** [comment]
After vision tests are resolved Travis will run on more compile environments, but I've already tested on VS, MSYS (gcc) and Linux (clang) and everything compiled successfully, so these headers are really not used. I wonder why IWYU keeps them in.

**Comment by kevingranade** [comment]
From the IWYU page, ``"Include what you use" means this: for every symbol (type, function variable, or macro) that you use in foo.cc, either foo.cc or foo.h should #include a .h file that exports the declaration of that symbol.``.  This can result in "over-including" when foo.cpp includes bar.h which includes baz.h, but foo.h does not include baz.h.  The idea is that everything is more stable so you're not vulnerable to breakages from shuffling around includes in other files.

Side note, my concern might be unfounded and most of these really are dead includes.

**Comment by jbytheway** [comment]
The IWYU folks have still not reponded to [my last PR](https://github.com/include-what-you-use/include-what-you-use/pull/681), so it's not easy for anyone but me to run it on CDDA.  I can try running it on this branch.  I suspect it will indeed disagree with whatever tool you're using in many places.

**Comment by jbytheway** [comment]
I checked, and indeed IWYU does re-add most of these includes.  Taking the first file `activity_handlers.cpp` as an example, I suspect the difference is that your tool deems it sufficient when the e.g. `set` being used within that file was defined elsewhere, whereas IWYU says "if you're using members of `set`, you'd better `#include <set>`".

**Comment by ZhilkinSerg** [comment]
So, what do you think it is better to keep these headers, while it compiles fine without them?

**Comment by jbytheway** [comment]
Indeed, I think I'd prefer to keep IWYU as the arbiter of header inclusion.  Removing those includes (I believe, based on a quick glance at what's being done) isn't going to actually help compile-times because they are still being included indirectly.

**Comment by ZhilkinSerg** [comment]
Agreed.

**Pull request merged**
