### PR TITLE
Manhacks dont drop combat knives

### PR DESCRIPTION
**Pull request by pisskop**
Now its spikes and scrap and blades.

And skitterbots can drop scrap instead of a taser too.

### CODE REVIEW

**Comment by Mecares** [comment]
I thought those drops were intended to supply you with decent weaponry early on in the Lab challenge, but i guess a blade is almost as good since you can craft a makeshift machete with them.

**Comment by pisskop** [comment]
Part of the problem with gthe manhack dropping things is that a combat knife isnt really going to improve your odds of survival if you managed to kill one and sneak into a lab early enough for the ck to be a significant boost to power.

And the manhack also drops a broken version of itself.  I think that perhaps the blade is even too much perhaps.

**Comment by Mecares** [comment]
I kinda think they should also have "hardtoshoot" because they are small, move erratically and fast, but perhaps that would make them too dangerous in the early game. Perhaps as a mid- to late-game Manhack Mk II equipped with a Leadworks evasion matrix.

**Comment by Soyweiser** [comment]
@Mecares that would just make them death sentences. In most cases they already are a huge pain. (Remember, they can also spawn on the overmap due to the Z scientists dropping them). Can't just close the door on them then :).

**Comment by John-Candlebury** [comment]
What's the point of this nerfs?
The combat knife is not a reliable drop, so its risky and of little use to farm manhacks when you are low level. 

Plus it doesn't really make sense from an in-game point of view. Why would the milspec robots be using a blade of so poor quality you could make it from scraping two pieces of metal together?

**Comment by Coolthulhu** [comment]
> Why would the milspec robots be using a blade of so poor quality you could make it from scraping two pieces of metal together?

Why would they be using a whole combat knife with a handle and all?

**Comment by pisskop** [comment]
A blade requires a forge to make, and is one of the rarer items of the game.

So rare as to make makeshift machetes or vehicle mounted blades impractcal early game.

By comparison, every scientist is not using a rambo-knife to make their pet manhack with.  They are most likely using trinkets or pocket knives or anything else they can.


The point of the nerf is that the manhacks dont even attack as if they have a combat knife.

**Comment by John-Candlebury** [comment]
>Why would they be using a whole combat knife with a handle and all?

I always understood that its just a blade similar enough to a combat knife to not warrant its own item. Which you held from the part that was attached to the bot.

It just seems weird that robots made for the military would drop terrible quality spikes. Blades make more sense at least

**Comment by pisskop** [comment]
Manhack recipe calls for 2 spikes.

**Comment by Soyweiser** [comment]
Well, perhaps we could change the recipe as well then? Make it all blades?

**Comment by pisskop** [comment]
why?  Does the idea of a cheap and effective miniature ramrod with sharp spikes turn you off or seem even a little unrealistic?

**Comment by Soyweiser** [comment]
I found this a good reason: 

> Why would the milspec robots be using a blade of so poor quality you could make it from scraping two pieces of metal together?

Also the description mentions blades.

So the question is, do we make manhacks to be just drones modded and changed by the scientists, or are minidrones as weapons something the cataclysm military uses?

(And the other question, gameplay wise, which is more valuable, the spike or the blade, and do we care when/where you get one? The blade can be made into a machette with tape (for the lab start), but then again, a spike can be made into a knife with the same. So im not sure if that is a concern for the lab start).

Another small thing, why is the manhack the only thing called manhack, while the rest is 'grenade hack' or 'mininuke hack'? I would expect 'man hack', if you follow the naming standards of the other hacks.

**Comment by BorkBorkGoesTheCode** [comment]
Minidrones are already a thing, so this would nt be implausible.

**Comment by Coolthulhu** [comment]
> Another small thing, why is the manhack the only thing called manhack, while the rest is 'grenade hack' or 'mininuke hack'?

Manhack is from Half Life 2. Other "hacks" are just bomb drones and the "hack" part does not make sense in their case.

**Comment by BorkBorkGoesTheCode** [comment]
> Manhack is from Half Life 2. Other "hacks" are just bomb drones and the "hack" part does not make sense in their case.

Then why are they in the game?

**Comment by BorkBorkGoesTheCode** [comment]
@pisskop could you rename the manhack to killer drone or something better?

**Comment by nikheizen** [comment]
Why do you want to biff this reference in particular?

**Comment by BorkBorkGoesTheCode** [comment]
> Why do you want to biff this reference in particular?

This PR is modifying the Manhack. If there are others, the references may need to be reviewed.

**Comment by pisskop** [comment]
There would need to be a discussion about that.

**Comment by nikheizen** [comment]
I don't think it fits in the scope of this PR, which is just re-balancing their drops.
Perhaps create an issue for removing all references from the game?

**Comment by Soyweiser** [comment]
Think manhack as a name works fine. Esp when you let people google what it is: http://vignette2.wikia.nocookie.net/half-life/images/4/4b/Manhack.jpg/revision/latest?cb=20090527003317&path-prefix=en look at that huggable thing. I was only pointing out the strange naming. I think renaming them to 'drones' just looks ugly, and removes some of the character from the game.

**Comment by Mecares** [comment]
Well H.A.C.K could mean something like  Hovering Autonomous Combat Kit - the modern battlefield device transportation system compatible to various functions and applications

**Comment by Coolthulhu** [comment]
Forced acronyms are the worst.

**Comment by pisskop** [comment]
Hubris Accelerated Combat Kiter

**Pull request merged**
