### PR TITLE
Added explicit num capture state to drop/clean menus to allow numpad navigation

### LINKED ISSUE #50819: Numpad navigation in inventory screens is ignored
### Describe the bug

Tested in Windows. Other OS may behave differetly.

Numpad navigation in inventory screens is not handled correctly, even with the interface option for "Use key code input mode" set to keycode.

Numpad keys return same number code as keyboard keys.

### Steps To Reproduce

1. Shift-d to open multidrop screen.
2. Attempt to navigate the menus with numpad.
3. Numpad inputs are treated the same as keyboard number keys. No navigation is possible.

### Expected behavior

Numpad navigation should be possible in inventory screens.

I did find a way to get it working but am not confident that it is a correct fix:

In inventory_selector::inventory_selector()
change    , ctxt( "INVENTORY", keyboard_mode::keychar ) to  , ctxt( "INVENTORY", keyboard_mode::keycode )
https://github.com/RoyBerube/Cataclysm-DDA/blob/ae7e5b9d962ba9d6e7926e6d8f509ac44d198b5d/src/inventory_ui.cpp#L1980
and  set "Use key code input mode" to keycode.

For reference:
https://wiki.libsdl.org/SDLKeycodeLookup

### Screenshots

_No response_

### Versions and configuration

- OS: [Windows 10]
- Game Version: [0.F latest experimental]
- Graphics version: [Tiles and Terminal]
- Ingame language: [English]
- Mods loaded: [dda]

### Additional context

_No response_

### LINKED ISSUE #50860: numpad keybindings don't work in (d)rop item menu
### Describe the bug

the numeric keypad movement buttons (4 8 6 2) don't work in the multidrop menu despite showing in the keybindings menu.

This issue affects both numlock off and numlock on

### Steps To Reproduce

open (d)rop items menu
check keybindings
try to use arrow keys (as shown in keybindings) to verify those work
try to use numpad keys (as shown in keybindings), note those don't work

### Expected behavior

the settings to either be clearly bound locally (i.e. not show the numpad bindings) 
or to respect the global keybindings

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by StStep**
#### Summary
Bugfixes "Added explicit num capture state to drop/clean menus to allow numpad navigation"

#### Purpose of change
Fixes #50860 and Fixes #50819 

#### Describe the solution
As discussed on #50860, an explicit state was added that captured number keys. This state can only be entered if the new keybinding (MARK_WITH_COUNT) is bound to a key, I recommend '#' or '+', and when it is bound you can use numpad number keys for navigation within the affected menus (mutli drop and clean). If it isn't bound, which it isn't by default, then the menu behavior stays the same where it captures all number keys and it prevents numpad navigation. I've also added a display of the current number for both number entry methods where the filter text shows up. This means the legacy method of selecting uses <enter> instead of TOGGLE_ENTRY to choose the number, I feel this is appropriate now that the user can see the numbers they are typing.

#### Describe alternatives you've considered

As far as macro implementation:
Letting one of the other Drop/Clean menu PRs handle this. Potentially migrated inventory menus to use keycodes.

Micro implementation:
Rather than introducing a new bool variable to track num capture, do something fancy and reuse count as an indicator (setting to -1 or something).

#### Testing

With MARK_WITH_COUNT unbound:

1. Spawn character with multiple of an item
2. Enter drop menu, highlight item with quantity > 4
3. Move selector with arrow keys to select the item and type "4" and verify the count entry area shows a 4
4. Press enter to note that 4 of of the item have been selected for dropping
5. Perform a similar action with the clean menu, summoning 10 filthy toothbrushes, a washing kit, and 20 soap.

With MARK_WITH_COUNT bound to "+":

1. Spawn character with multiple of an item
2. Enter drop menu, highlight item with quantity > 4
3. Move selector with numpad "2" to select the item then press "+", verify count entry shows and type 4, verify it now shows 4.
4. Press enter to note that 4 of of the item have been selected for dropping
5. Perform a similar action with the clean menu, summoning 10 filthy toothbrushes, a washing kit, and 20 soap.

### CODE REVIEW

**Comment by kevingranade** [comment]
Even with the extra keypresses this is arguably better *for numpad users*, but for people not using the numpad, this is an extra keypress for no reason.  I think we can have our cake and eat it too though, how about we leave the new keybinding unbound by default, and activate this new logic *if the keybinds are assigned*?

Alternately, that might be too clever, and we just want a persistent toggle to select which numeric entry method is preferred.

**Comment by StStep** [comment]
Supposedly using keycodes could nicely separate numpad users from number key users, but those talking about them made it seem much more complicated.

I'm fine with either way but this inventory UI is unique in that it has a hidden number capture, most of the number enter areas open up a new prompt (like setting world settings, or batch crafting). Most of the numbers you'd enter here are short enough that I could understand not needing to see what you are typing, but it is kind of weird for new users.

**Comment by kevingranade** [comment]
I'm 100% behind the "bring up a text entry field", but that's orthogonal to adding an additional keypress to the process.

**Comment by StStep** [comment]
> 
> 
> I'm 100% behind the "bring up a text entry field", but that's orthogonal to adding an additional keypress to the process.

Ah okay, I misunderstood. You want the number prompt to show while its in capture mode and maintain the Toggle as accepting the values?

**Comment by kevingranade** [comment]
I want there to be two modes:
"Legacy mode" if you will, hitting any numeric key opens the number prompt and populates it with said number. (alternately just leave it working the way it was before)
"Numpad mode", requires hitting a configured hotkey to open the number prompt.
Toggling between these two modes should be persistent, I'd like the legacy mode to remain the default as per the principle of least surprise.

**Comment by StStep** [comment]
Gotcha, I can do that

**Comment by StStep** [comment]
So I've updated the PR description with the current state of the code due to suggestions. The one thing I wasn't sure how to do was to properly inform the user how the unbound key acts. I wanted to add to its "?" description to say leaving the key unbound does the legacy entry while binding the key allows for using numpad keys for something else, but there isn't enough room to be that descriptive.

**Comment by ZeroInternalReflection** [comment]
As an alternative to the currently proposed behaviour, I would suggest adding another line to the footer of the menu.  This eats into vertical real estate a bit, but I don't _think_ that's a problem for the inventory menu very often.  I did a quick test of how it would look based on @StStep's current work.  If "MARK_WITH_COUNT" is unbound, have a note saying numpad navigation is off.  
Keybinding_unbound
If "MARK_WITH_COUNT" is bound, have a message similar to "[/] filter" to show them what key to press to enter a number of items to drop/use:
Keybinding_bound
And when a number is entered, display it in it's own spot:
Entering_count
(It would probably be good to have some context there of "Items to select: <____>" or similar)

Would that allow for both input methods while minimizing confusion/surprise?

If this is something that StStep want's to pursue, I can pass him my current rough-draft patch.  However, as someone fairly new to GitHub, I'm not sure what the recommended method for that would be.

On a separate note, I did have a hard crash while testing this out.  I've been unable to replicate it, but I was entering numbers to select while in category selection mode.

**Comment by StStep** [comment]
I'm cool with it having its own area and not infringing on the filter text area. I also like the idea of explicitly telling the user they could do numpad navigation, since a lot of other menus already allow it. One reason I kept it simple was because I'm not that familiar with how the whole UI works.

I'm slightly afraid of calling it something like numpad mode though, that suggests something more comprehensive than what is happening. For something like that, we might want to review all the menus and have some kind of global numpad usage option. In any case, I would like to see the patch.

As far as the crash, if I had to guess it relates to string to int parsing, if you didn't include a try catch then it's really easy to get an exception from it.

**Comment by ZeroInternalReflection** [comment]
> I'm cool with it having its own area and not infringing on the filter text area. I also like the idea of explicitly telling the user they could do numpad navigation, since a lot of other menus already allow it. One reason I kept it simple was because I'm not that familiar with how the whole UI works.
> 
> I'm slightly afraid of calling it something like numpad mode though, that suggests something more comprehensive than what is happening. For something like that, we might want to review all the menus and have some kind of global numpad usage option. In any case, I would like to see the patch.
> 
> As far as the crash, if I had to guess it relates to string to int parsing, if you didn't include a try catch then it's really easy to get an exception from it.

Yeah, I can see how "numpad navigation mode" might be taken as a grander idea than it is.  A better phrasing might be "Numpad navigation disabled on this screen" or, if we're confident in having enough room, "To enable numpad navigation on this screen, bind a key to 'mark item count'" or something to that effect. 

This almost certainly isn't the recommended GitHub method, but my (very) rough work for the mockup above is attached here:
[51085TestPatch.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/7088173/51085TestPatch.txt)
I did most of my changes in inventory_selector even though it's not actually relevant there.  I just wanted to avoid implementing it in both inventory_iuse_selector and inventory_multiselector.  The cleanest way is probably to have the _capability_ in inventory_selector, but disable it, then enable it in the various derived classes.

I don't think the crash I ran into was string parsing because I played around with that separately without issue, but if the issue recurs I'll let you know.

**Pull request merged**
