### PR TITLE
Removes invulnerablity for worn healing/storage items

### PR DESCRIPTION
**Pull request by pisskop**
Why on earth your toolbelt cant be unseated from your seat by a zman, Ill never know.  But it can and will be now.

Same with the stim injectors.

### CODE REVIEW

**Comment by pisskop** [comment]
1 encumbrance is virtually nothing.

Items like biowatches are described as bulky, and on the hand it would be an impediment.  My watch gets in my way at work, and its a small exercise watch.

Most items get a coverage rating, not an encumbrance rating.  Those that do are items that would get in the way of casual survival operations, such as fighting, climbing, dodging, dexterous hand movements.


All the items get a coverage rating to so as to expose them to harms way.  many of these items received material thickness and armor rating, but with no coverage rating they had zero percent chance of being damaged or being armor.

**Comment by Coolthulhu** [comment]
Damage on items like watches is trivial detail, not worth tracking.

**Comment by pisskop** [comment]
Then why is it tracked in vehicles

**Comment by Zireael07** [comment]
> Every single zombie drop has damage.

I'm not sure it's true. Watches dropped by Zs don't seem to be.

Also I believe this only detracts from gameplay in name of realism.

**Comment by pisskop** [comment]
Watches are examples of the exact type of item that makes a huge impact early game, or for those without a car.  To be able to raid at night, or know how to avoid the things that go bump in the night, and you cant really budget your time without one.

To be able to wear one on your wrist and forget it ever existed is to take away a players need to balance inventory space with encumbrance or functionality.

A watch isnt something that even has to be fragile.  The timepiece itself is a fairly sturdy strucuture, and with a 1% coverage rate youd have to go out of your way to destroy it.

Trivial it is not, its an inconsistency with the game's own mechanics, not an attempt to introduce realism in any grandiose way.

**Pull request closed without merging**
