### PR TITLE
Fancy clothing affects NPC opinions

### PR DESCRIPTION
**Pull request by zachary-kaelan**
#### Summary
```SUMMARY: Features "Fancy clothing affects NPC opinions"```

#### Purpose of change
Add a use for the countless fancy items, besides the Stylish trait.

#### Describe the solution
I basically just slapped a square root on the final morale bonus (max 20), for a resultant maximum of 4 to 5.

#### Describe alternatives you've considered
Probably want to add filthiness to it as well in the future, among other things.

### CODE REVIEW

**Comment by Qrox** [comment]
Looks like you're revert some recent changes to the code. Some kind of rebasing error?

**Comment by zachary-kaelan** [comment]
> Looks like you're reverting some recent changes to the code. Some kind of rebasing error?

Yup, that'd be it.

**Comment by kevingranade** [comment]
From a rationale point of view I'm sceptical that wearing *specific* kinds clothes are going to improve NPC opinion.   If I ran into someone running around in the cataclysm wearing a tux, I'd assume they're crazy.  That's a pretty hard blocker, I don't want to require people to do silly things like this for optimal social play.

From a game balance point of view, there is no downside to wearing stylish clothes around friendly NPCs other than carrying the extra clothes around and micromanaging swapping out clothes.

**Comment by I-am-Erk** [comment]
Yeah this seems both illogical and imbalanced. Why would it be easier to persuade an NPC if you're in a wedding dress and gold necklace versus normal survivor stuff?

I do like the idea of filthy clothing having a negative impact on persuasion.

**Comment by zachary-kaelan** [comment]
The same reason why being attractive improves your social skills. Clothing is just another way to make yourself more attractive. Blame the human race, not me. 

Though one thing I noticed is that Ugly says "for people who care about that sort of thing" in the description, but as far as I can tell, *everybody* cares about that sort of thing. Perhaps we should make it so some people like fancy clothes, others like fancy faces, some like big guns, etc.

> there is no downside

There's the downside of stylish clothes being less protective. Also, stylish clothes *have no upside* if you don't have the trait.

**Comment by I-am-Erk** [comment]
"stylish" as a clothing characteristic is meant only to mean "interacts with the stylish trait". It's not _meant_ to have any other benefit. Again, I don't think someone dressed in a tuxedo with a gold necklace, high heels, and a crown would be considered by NPCs to 'look better' than someone in body armour, particularly since the majority of uses of persuasion are to convince NPCs to do what you want them to do in the context of you being a prepared survivor.

You might instead replace the word stylish with 'bling' (in fact I sort of wish we would). It doesn't mean you look better, it means you're wearing fancy-ass stuff because you're a strange sort of person who loots and wears fur coats and gold chains after the apocalypse simply because you can.

**Comment by kevingranade** [comment]
On second look, this simply isn't happening, you aren't dating, you're recruiting a team of people to survive the apocalypse together.

**Comment by zachary-kaelan** [comment]
You guys are talking about conscious decision-making, but I'm talking about *unconscious* decision-making. You tend to form first impressions within a second upon first seeing someone. There are thousands of studies on this.

[Here is a study showing how wearing a minorly fitted suit vs unfitted made someone appear "better".](https://uhra.herts.ac.uk/bitstream/handle/2299/12766/906722.pdf?sequence=2&isAllowed=y)

[Here is a study showing how people rate someone formally dressed as more attractive, intelligent, and socially-competent.](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.852.2586&rep=rep1&type=pdf)

*However*, one thing the second study noted is how more "stylish" people are more likely to judge other people based on their clothes. And something the first study noted, is that people with higher earnings - and thus more access to that style of clothing - are less impressed by such things (though tend to still look down on more casual dressers).

I am radically rethinking this. Getting a tuxedo in this new world is significantly less difficult compared to before. Though NPCs with the Stylish trait would still judge others based on this sort of thing (they judge themselves, after all). But NPCs *still* need to judge based on clothing. Like you said, @kevingranade, if you saw someone in a tux, you would think they were crazy.

[Chris Crawford has a lot to say about game personality models](http://www.erasmatazz.com/library/course-description-2018/a-more-artistic-example.html), and he's been working with them for around 40 years. One aspect of his models I find quite interesting, in the context of CDDA, is how "opinions" are essentially your perceptions of the traits of others. For example, "Fear" is basically the difference between an NPC's aggression value and the theoretical *perceived* aggression value for somebody else. 

What I think wearing a tux would realistically do, is increase people's perceptions of your bravery, or some other currently-nonexistent trait, but only if you prove it's not a facade. Like imagine this: you're in heavy armor and use a long-ranged weapon to kite zombies and take them out carefully. Then you see some guy in a tux, bare-knuckles brawling groups of zombies with some serious technique. Afterwards, he takes out a handkerchief and wipes the blood off his hands and suit, with a slightly irritated look, before carefully folding it and putting it back away. You gotta admit, that has some serious appeal.

One of the most important aspects of a leader in crisis, is convincing everyone that everything is going to be alright: humanity isn't going to go extinct, the rest of their lives isn't going to entirely be a horror show, and nobody's going to have to eat each other. Even if it's irrational and dead wrong, *they still want to believe it*. They want to be taken away from their horrific reality and vicariously shown a much happier one.

**Comment by I-am-Erk** [comment]
Again, you're confusing the "stylish" clothing tag for *actually looking good*. The average survivor decked out in as much "stylish" gear as they can find does *not* look good. They probably look pretty ridiculous, that's why you have to have the trait to get a morale boost from it.

Your code here is still useful. Wearing ill fitting or filthy clothes should have a negative impact on persuasion. I'd suggest recycling the code to work like that.

**Comment by kevingranade** [comment]
> Then you see some guy in a <anything>, bare-knuckles brawling groups of zombies with some serious technique. 

The clothes are irrelevant in this scenario, the physical prowess displayed is 100% of the effect. If you can capture that impressiveness, great, but the clothes are at best a minor contribution.

You're also ignoring the reality of what your code does compared to your stated scenario.  According to the code, someone shows up wearing mismatched finery and jewelry, displays *no* combat or other ability, but still yields a better impression than someone wearing pragmatic clothes.

If you want to do something serious with someone "looking good" based on their clothes, you're going to need to start from scratch, because the stylish trait and clothing tag are literally a joke and should not have anything else built on them.

**Comment by zachary-kaelan** [comment]
> look pretty ridiculous

Yeah, alright, so *too much* stylishness should be penalized. Or perhaps certain clothing should have an inherent factor representing this. 

And it’s obvious now that only other stylish NPCs should care.

***

> clothes are irrelevant

It would look a *lot* different if he was in armor so thick you couldn’t even see his face. But “impressiveness” is a good name for a value. Basically, it provides some meager form of entertainment for the NPCs.

> ignoring the reality of your code

That’s why I said I’m radically rethinking things. The code was just a little change to expand on later. I already modified it to only work if the NPC is also stylish. Though I agree I’ll have to take some more time on this before presenting it again. 

> literally a joke

Well how was I supposed to know that? Is there a list somewhere of all the jokes?

**Pull request closed without merging**
