### PR TITLE
Chickens can no longer fly

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
```SUMMARY: Bugfixes "Chickens can no longer fly```

#### Purpose of change
Chickens can't fly in real life, so they should be able to ingame.

#### Describe the solution
Remove the "FLIES" flag from chickens

#### Additional context
@curstwist Turns out the issue just was that chickens could fly

### CODE REVIEW

**Comment by adamkad1** [comment]
realism!

**Comment by Rivet-the-Zombie** [comment]
But chickens can fly IRL, just usually not for super long distances.

**Comment by ifreund** [comment]
Yeah I’ve seen chickens fly over fences when scared.  They can’t fly well, but they can fly.

**Comment by anothersimulacrum** [comment]
Perhaps a new flag like `GLIDES` or `SHORT_FLIGHT` could better simulate this?

**Comment by kevingranade** [comment]
If we get a flag to represent short barely capable flight, yes chickens can have it, but the current flag gives highly competent flight.

**Pull request merged**
