### PR TITLE
wild stab at, stabbing weapon gaining cutting experience bug

### PR DESCRIPTION
**Pull request by aierce**
a wild stab at the bug where stab weapon gain cut experience

### CODE REVIEW

**Comment by aierce** [comment]
even if this doesn't fix the experience bug, this is still a valid bug, i think, maybe there are multiple bugs contributing to this problem

**Comment by aierce** [comment]
OK Coolthulhu said on the forum:


"It works like this:

Every knife-type weapon deals "equally random" amount of cutting and piercing. As in, if it deals 1d10 cutting, it also deals 1d10 piercing.
Only the higher of the two is actually dealt.
Only the actually dealt damage contributes to training.

Most survivors get cutting quicker, because there are more (good) weapons that do this AND because cutting damage has a lower penalty from low skills.
Therefore most survivors deal and train cutting when using knives early on.

As a result, most survivors train cutting only by using knives."
 
and he is right. If this is intentional please ignore this pull request

or if this is not intentional, like KA101 suggested, this will (i think) make knife-type weapons act similar to spear-type weapons, where they both train and use only pierce skill.

**Comment by aierce** [comment]
Yeah line 2126

 if (p.weapon.has_flag("SPEAR") || (p.weapon.has_flag("STAB") && stab_dam > cut_dam))

pretty much proves that this behavior is intentional and not a bug

**Comment by Zireael07** [comment]
I don't understand how that line proves the behavior (stabbing weapons giving cutting exp) is intended.

**Comment by Rivet-the-Zombie** [comment]
The problem is that as the character's cutting skill rises, their cutting damage increases so that eventually it's pretty much impossible for them to do more stabbing than cutting damage, so their piercing skill stops increasing after that point.

What we need is for piercing skill to be improved by using piercing weapons, full stop. Having the ability to improve the skill based off hoping your cutting skill is sufficiently low to allow random chance to give piercing some XP is silly, and it's basically broken the piercing skill.

**Comment by aierce** [comment]
Spear weapons only improves piercing damage, wooden and knife spears are easy to make. KA101 also suggest on the forum to turn off cutting skill experience in the @ character menu with the space bar

**Comment by KA101** [comment]
Rivet's right: stabbing needs to be equal to cutting when a weapon does both.

**Comment by bookofguns** [comment]
Um could there be a stance with melee weapons to dictated rather the player is in a "Slashing" stance, "Bashing" stance, or "Stabbing" stance. Along with a default that just rolls the original code?

**Comment by KA101** [comment]
Not impossible, but I'm thinking it's not worth the trouble.

**Pull request merged**
