### PR TITLE
Fix item duplication from reloading with magazine

### LINKED ISSUE #16445: Ruger 10/22 magazine clone bug.
#When reloading a magazine inside a Ruger 10/22 with a magazine in your inventory, the below bug occured and additionally - whilst my Ruger 10/22 was reloaded successfully and the depleted/empty magazine was added to my inventory - I would gain an additional magazine of the same type/ammunition type/rounds within the magazine.

> Debug: Tried to remove an item from a character who doesn't have it
> 
> Function: virtual void item_location::item_on_person::remove_item()
> File: src/item_location.cpp
> Line: 216

### PR DESCRIPTION
**Pull request by BevapDin**
This should fix #16445 and #18101

It requires a gun with magazine and another identical magazine in the inventory and another identical magazine to reload from. That is: three identical magazines (they must appear as one stack in the inventory), one in the gun, one in the inventory and one somewhere accessible (ground or inventory).

Upon reloading the gun with one of the magazines, the game displays the "dispose item" menu and upon any selection (even canceling it) the debug message appears.

What happens is this:

``` C++
// item.cpp:
// eject magazine to player inventory and try to dispose of it from there
item &mag = u.i_add( *obj->magazine_current() );
if( !u.dispose_item( item_location( u, &mag ), prompt ) ) {
    u.remove_item( mag ); // user canceled so delete the clone
    return false;
}
```

The `i_add` adds the magazine to the _end_ of an existing stack in the inventory. The returned reference is to the added item at the end.

`u.remove_item( mag )` gets called here (when canceling the menu) or from the handler in `player::dispose_item` (via `item_location::remove_item`). `visitable::remove_item` forwards to `remove_items_with` with a lambda that compares the _address_ of the item.

``` C++
// visitable<inventory>::remove_items_with
for( auto stack = inv->items.begin(); stack != inv->items.end(); ) {
    if( filter( stack->front() ) ) {
        // remove the first std::min(stack->size(), count) items from stack
    } else {
        for( auto &e : *stack ) {
            remove_internal( filter, e, count, std::back_inserter( res ) );
            // remove_internal only considers e.content
            // filter( e ) is *never* called
        }
    }
}
```

The first item of the magazine stack is old (it was there since _before_ even attempting to reload) and does not match `mag` (`filter(...)` returns `false`). The other items of the stack are _not_ compared against the predicate, only their content is (in `remove_internal`), but that is not relevant here. `mag` is one of the other items in the stack.

In the end, `visitable::remove_item` can't find the item to be removed because it never applies the predicate to it.

---

I changed the code to always iterate over all the items of the stack.

### CODE REVIEW

**Comment by mugling** [comment]
Well spotted indeed

**Comment by crom7** [comment]
I'm still getting the error when I try to reload a full mag when the gun is already loaded with an empty mag but not the other way around.

**Comment by mugling** [comment]
> build: 5434

This PR is not yet included in any of the published Jenkins builds

@BevapDin granted correctness is more important than performance but does this fix not adversely affect performance of a lot of unrelated code?

**Comment by BevapDin** [comment]
> @BevapDin granted correctness is more important than performance but does this fix not adversely affect performance of a lot of unrelated code?

Yes, this affects performance (after all, the filter is invoked more often). The question is: does it matter?

Typical predicates are small (`return i.is_gun() && !i.is_ammo();` or `return i.has_flag("foo");`) and the amount of items a character carries around is not huge either, so it will probably not matter.

What other solution do you propose? A separate implementation for `remove_item(const item&)`?

**Comment by mugling** [comment]
> Yes, this affects performance (after all, the filter is invoked more often). The question is: does it matter?

For the player inventory I would doubt it. For map and vehicle tiles possibly.

> What other solution do you propose? A separate implementation for remove_item(const item&)?

Possibly a separate implementation. Only the primitive operations (find, delete) should really ever need to compare by address?

If you didn't want to work on that now it would be more than reasonable to merge this however as correctness is more important than performance?

**Comment by BevapDin** [comment]
> For the player inventory I would doubt it. For map and vehicle tiles possibly.

Well, the changes here only affect the inventory. `remove_items_with` *already* applies the filter to all items one the map/in a vehicle, that part is not touched at all.

> If you didn't want to work on that now

I'd work on that *if* it actually turns out to be a problem. Note that the changes here only affect the searching in the inventory.

**Comment by mugling** [comment]
> Note that the changes here only affect the searching in the inventory.

I can't see it being problematic in that case

**Pull request merged**
