### PR TITLE
Tweaking values of (heavy) flashlight, also giving longest side

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
Balance "Tweaking of values of flashlight and heavy flashlight"

#### Purpose of change
Alright, another small change. Both heavy and normal flashlight now have a lengh and the volume was reduced for both to "make more sense".

#### Additional context
https://www.amazon.de/Taschenlampe-Wiederaufladbar-Karrong-Einstellbarer-Taschenlampen/dp/B07N37YCST/ref=psdc_2076991031_t1_B08D9JX8HB <- Values for normal flashlight
https://www.amazon.com/-/de/dp/B00002N6SI/ref=sr_1_6?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=142JCRCS6S540&dchild=1&keywords=heavy+duty+flashlight&qid=1613861617&sprefix=heavy+du%2Caps%2C258&sr=8-6 <- Values of heavy duty flashlight.

### CODE REVIEW

**Comment by actual-nh** [comment]
The melee damage output (per move, I think) of the heavy flashlight has changed, setting off the test.

**Comment by wapcaplet** [comment]
The failure message from the `new_character_test.cpp` test case is quite obtuse, but it appears to be due to the starting professions that have a flashlight - they do not have space in their inventory to store the lengthened flashlight.

- Mall Security (`mall_cop`)
- Security Guard (`security`)

These professions only have pants, a holster, and a light jacket - none of which have enough length to hold the newly lengthened flashlight. You'll see a more helpful message if you start a new scenario as "Mall Security" or "Security Guard":

```
DEBUG    : ERROR: Could not put flashlight (off) into inventory.  Check if the profession has enough space.
```

These other professions also start with a flashlight, but they appear to have enough storage

- Electrician (`electrician`) - flashlight fits in the tool belt
- Survivalist (`survivalist`) - flashlight fits in backpack
- Survivalist Jr. (`jr_survivalist`) - flashlight fits in backpack

For the Mall Security and Security Guard professions, perhaps you could give them a police duty belt (`police_belt`) to store the flashlight in?

**Comment by Lamandus** [comment]
> 
> 
> The failure message from the `new_character_test.cpp` test case is quite obtuse, but it appears to be due to the starting professions that have a flashlight - they do not have space in their inventory to store the lengthened flashlight.
> 
>     * Mall Security (`mall_cop`)
> 
>     * Security Guard (`security`)
> 
> 
> These professions only have pants, a holster, and a light jacket - none of which have enough length to hold the newly lengthened flashlight. You'll see a more helpful message if you start a new scenario as "Mall Security" or "Security Guard":
> 
> ```
> DEBUG    : ERROR: Could not put flashlight (off) into inventory.  Check if the profession has enough space.
> ```
> 
> These other professions also start with a flashlight, but they appear to have enough storage
> 
>     * Electrician (`electrician`) - flashlight fits in the tool belt
> 
>     * Survivalist (`survivalist`) - flashlight fits in backpack
> 
>     * Survivalist Jr. (`jr_survivalist`) - flashlight fits in backpack
> 
> 
> For the Mall Security and Security Guard professions, perhaps you could give them a police duty belt (`police_belt`) to store the flashlight in.
> 
> _Edit_ I tried simply adding `police_belt` to the `"items"` array for those professions, and it did not work - the test still fails, and they still get the error when starting a new game. Maybe a better solution would be to define a `max_item_length` on the `pants` and/or `jacket_light` pocket(s)? They appear to have the default length now (inferred from the cube root of the pocket volume), but I think it's reasonable to define a length (say, 15cm) so they can fit a 14cm flashlight.

most flashlights nowadays have a clip or a hoop, so if I add the flag belt_clip to both, and give both professions a belt, it should do the work, right?

**Comment by Lamandus** [comment]
yes that does the trick. Should work now.

**Pull request merged**
