### PR TITLE
Enhance the XEDRA Evolved weakening effect to its original intended use.

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Balance "Enhance the weakening effect in XEDRA Evolved to achieve it's intended use"

#### Purpose of change
This was brought to my attention earlier today, and I figured since it's possible now, why the hell not?

#### Describe the solution
Add enchantments to the weakening effect as per its original comments

#### Testing
I, uh... didn't.

#### Additional context
I'm not merging this without an okay from the maintainers, obviously. Pinging @Maleclypse and @GuardianDll

### CODE REVIEW

**Comment by Inglonias** [comment]
Be aware that `ARMOR_BASH` is currently only applied if you're already doing bash damage. It may be worthwhile to add all damage types here.

**Comment by Inglonias** [comment]
wow, you just... you just merged it, huh? No worries about balance issues or anything like that? I just got it right on the first try? Are you SURE? I'm not questioning your wisdom as a developer here, I just find it THAT hard to believe I shot a hole in one.

**Comment by GuardianDll** [comment]
It's a mod, it has much more laxed rules

**Comment by TheShadowFerret** [comment]
You forgot to update the effect description 👉👈

**Comment by Inglonias** [comment]
> You forgot to update the effect description to not say it's a slowdown anymore 👉👈 

I wish you had said something before this merged. Now it's too late, and there's absolutely nothing we can do to fix the problem. Oh, if only someone had reviewed it. If only the _author_ had reviewed it. Then maybe this game wouldn't now be ruined forever by incorrect information that we have absolutely no way to fix!

(I'll put in another PR later)

**Pull request merged**
