### PR TITLE
fixed typo in description of "Peanut Butter Bruised"

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary

SUMMARY: None

#### Purpose of change

fixing a glaring spelling error in the description of the book "Peanut Butter Bruised"

#### Describe the solution

changed the line "the idea of become a professional chef" to "the idea of becoming a professional chef" in the book's description

#### Describe alternatives you've considered

N/A

#### Testing

Testing unnecessary; only one word in one line of code was touched, shouldn't cause any major problems

### CODE REVIEW

**Comment by BrettDong** [comment]
> SUMMARY: [None] fixed a spelling error in a book's description

Should change `[None]` to `None`

**Comment by BrettDong** [comment]
> SUMMARY: None fixed a spelling error in a book's description

Forgot to mention that the subject needs to be quoted like
SUMMARY: None "Fixed a spelling error in a book's description"

**Comment by actual-nh** [comment]
> > SUMMARY: None fixed a spelling error in a book's description
> 
> Forgot to mention that the subject needs to be quoted like
> SUMMARY: None "Fixed a spelling error in a book's description"

Actually, if it's "None", then one should not put anything after it. (I ran into that problem with my first PR...)

**Comment by BrettDong** [comment]
Sorry

**Pull request merged**
