### PR TITLE
[RDY] Whitespace exorcism - ammo.json

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by mugling** [comment]
Did you do this manually as you have a JSON error in there?

**Comment by BorkBorkGoesTheCode** [comment]
Yes.

**Comment by illi-kun** [comment]
I see no point to do this manually since we have perfectly reliable formatting tool for that.

**Comment by mugling** [comment]
> I see no point to do this manually since we have perfectly reliable formatting tool for that.

Yes, automated reformatting is backed by unit tests so very unlikely to introduce errors.

I don't want to discourage anyone working on JSON cleanup as it's badly needed. If you can lint then great (and we have a web-based solution underway for everyone else). If you can't then cleaning up entries by adding sensible inheritance (`copy-from`) or breaking apart obese files are also useful contributions.

**Comment by BorkBorkGoesTheCode** [comment]
>I see no point to do this manually since we have perfectly reliable formatting tool for that.

If it's Linux-exclusive, I cannot use the tool at this time.

**Comment by mugling** [comment]
Try http://dev.narc.ro/cataclysm/format.html

**Comment by BorkBorkGoesTheCode** [comment]
Have tried the automated tools, they are great.

**Comment by BorkBorkGoesTheCode** [comment]
Ready to be tested.

**Comment by BorkBorkGoesTheCode** [comment]
Okay. I am not a garbageman .

**Pull request closed without merging**
