### PR TITLE
base hardtack is inedible

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
I was reminded that we have hardtack and it was left edible without processing.

#### Describe the solution
Throw the inedible flag on it,  it needs to be processed into another item before it becomes edible. 

#### Describe alternatives you've considered
There are several options for processing,  we already have soaking,  there are credible reports of soldiers breaking hardtack into small chunks and holding them in their mouths to soften them enough to eat. I'm not interested in adding any more because IMO they're too niche to bother with,  but someone else can feel free.

### CODE REVIEW

**Comment by Aimless-dude** [comment]
If I'm remembering correctly, the reason for keeping hardtack edible by default is that it would be really hard to implement common eating practices, like putting it in your mouth for a day, and chewing on it as it gets softer, in a way that wasn't cumbersome and annoying. I think it must have been in the discussions on not making Hardtack count as Gross Rations (Like the protein stuff).

**Comment by Maleclypse** [comment]
> If I'm remembering correctly, the reason for keeping hardtack edible by default is that it would be really hard to implement common eating practices, like putting it in your mouth for a day, and chewing on it as it gets softer, in a way that wasn't cumbersome and annoying. I think it must have been in the discussions on not making Hardtack count as Gross Rations (Like the protein stuff).

The fact that we don't have consumption time modifiers on food items is why it's now going to be inedible until treated in one of the methods already set in recipes

**Comment by kevingranade** [comment]
My understanding is trying to eat hardtack raw is not at all a normal practice, but more an act of desperation. The normal practice is rehydrating it and eating it, and potentially incorporating it into a dish.

**Comment by NetSysFire** [comment]
I wonder if we can keep this edible but making it like 5 minutes to consume. We could do this with `use_action` (obviously, replace moves with something fitting; this was copied from the corn cob):

```json
"use_action": { "type": "consume_drug", "moves": 500 }
```

Maybe even paired with a "Now your teeth/jaw hurt" debuff.

**Comment by Maleclypse** [comment]
> I wonder if we can keep this edible but making it like 5 minutes to consume. We could do this with `use_action` (obviously, replace moves with something fitting; this was copied from the corn cob):
> 
> ```json
> "use_action": { "type": "consume_drug", "moves": 500 }
> ```
> 
> Maybe even paired with a "Now your teeth/jaw hurt" debuff.

That looks viable to me.

**Comment by kevingranade** [comment]
`"use_action": { "type": "consume_drug", "moves": 500 }`
I'm not totally against someone adding such (just do it on top of my PR, I'm not messing with it).
It does overshoot in the other direction, now you have to stand still for the duration of eating the stuff.
Ideally it would work like smoking used to and just occupy your mouth for the duration but allow you to do other stuff.

I did just notice that the item in-game is a bizzarely tiny chunk of hardtack instead of a normal sized loaf of the stuff, ideally the real deal is going to be a sizeable chunk, like .3" - .5" thick and 3"x3" width.  If you make it so small it has much higher surface area, which interferes with preservation and storage.

**Comment by Maleclypse** [comment]
I’ll merge this and look at the item size if netsysfire wants to look at the action or how smoking works?

**Comment by NetSysFire** [comment]
Unlikely. As far as I know smoking is hardcoded and for me to do such changes to the effects/use_action/consume_drug menu I need C++ knowledge and sufficient motivation, both of which I lack.

**Comment by Maleclypse** [comment]
> If anyone's gonna be mucking about with the size of hardtack, have a look at #61312
> 
> Partly to fix the absurd density while you're at it, but mostly because the comments have some relevant discussion of how and why bread items have ended up with such silly numbers (hint: it's `stack_size`)

Comment your suggestions on #74887 I probably won't go digging on the issue as I'm only trying to fix one thing but if you let me know what other things to fix while I'm still trying to get that fix completed I'll be able to slide them in if they are appropriate.

**Pull request merged**
