### PR TITLE
Load mineral water in plastic bottles (close #12607)

### LINKED ISSUE #12607: [Holding water] Fancy mineral water
"Fancy mineral  water, so fancy it makes you feel fancy just holding it."

So after checking a vending machine and holding a button down to buy everything quickly, I discovered i have items in liquid form in my inventory, without the container. Surely this is a bug, yes?
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21298983-holding-water-fancy-mineral-water?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BrettDong**
Plastic bottles won't be shattered.

plastic bottled mineral water

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Stating "Closes #12607" in description of opening post will close the related issue when this is merged.

**Comment by pisskop** [comment]
I _like_ them in glass bottles, tbh

**Comment by DangerNoodle** [comment]
Having them break if occurring in vending machines is unfortunate though.

Is it possible to have their default container be glass, but have them appear in plastic bottles when in vending machines? It should since I am fairly certain that vending machine selection is an item group.

**Comment by BrettDong** [comment]
My fault, I forgot to write 'closes #12607' in the main body. @kevingranade could you please close that issue manually?

**Comment by BrettDong** [comment]
> I like them in glass bottles, tbh

How about adding a some kind of 'premium mineral water', resembling eg. _Perrier_?

Perrier

Bottle it in glasses, make it more rare, more expensive, and even make it supplies calcium.

Calcium (Ca)	147.3
Chloride (Cl−)	21.5
Bicarbonate (HCO3)	390
Fluoride (Fl)	0.12
Magnesium (Mg)	3.4
Nitrate (NO3)	1.8
Potassium (K)	0.6
Sodium (Na)	9
Sulfates (SO4)	33

Data from [Wikipedia](https://en.wikipedia.org/wiki/Perrier).

**Pull request merged**
