### PR TITLE
[Magiclysm] Add spell to make magic noise

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

Mods "Add spell to make magic noise"

#### Purpose of change

Add spell to make magic noise

#### Describe the solution

- [ ] Add the ability to spawn an item at the target of the spell
- [ ] Jsonize noise emitter
- [ ] Make a magic noise emitter item

#### Describe alternatives you've considered

Just use the "noise" spell effect

#### Testing

TBD

### CODE REVIEW

**Comment by Salty-Panda** [comment]
You need to increase range_increment on the spell

**Comment by Fris0uman** [comment]
Well it doesn't even work currently ^^"
But good catch, I'll make sure to have an increment that make sens

**Comment by KorGgenT** [comment]
i'm not clear why we need this one as opposed to your proposed alternative which is already part of the codebase

**Comment by Fris0uman** [comment]
Tis was a silly idea. Plus I'm lacking time to make it properly.

**Pull request closed without merging**
