### PR TITLE
Revise small/medium/full size storage battery stats to be more internally consistent

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Balance "Revise small/medium/full size storage battery stats to be more internally consistent"

#### Purpose of change
The lithium-ion based power storage options currently in the game have some highly dubious thermodynamic implications:

The medium storage battery has 14 times the capacity of the small storage battery...
... but is only 12.4 times the mass, and only uses 8 small storage batteries for components.
The large storage battery has 80 times the capacity of the small storage battery...
... but is only 60 times the mass, and uses only 32 small storage batteries for components (after accounting for medium storage battery recipe)

Further, with the recipe-as-reversible it is entirely too easy to disassemble medium/large storage batteries with high/full returns. Dismantling li-ion arrays trends towards destructive without much higher skill than is needed to assemble them in the first place.

#### Describe the solution
After having confirmed that the existing power levels were to be taken as writ in stone, I corrected the mass and components for medium and full size storage batteries. 

I also made full size storage batteries be assembled from small storage batteries, to make disassembly/assembly more granular and to represent the fact the 'small storage battery' we use in-game is fairly similar in concept to the li-ion cell packs used in larger arrays. After all, it doesn't make sense to make a few medium storage batteries then make a large storage battery out of those, rather than just building the larger unit to begin with. You'd get better far results by assembling at that scale to begin with.

While I was at it, I slightly adjusted the skill requirements of the assembly recipes, made them non-reversible, and added explicit uncraft recipes with a higher skill requirement (electronics 8), to make it harder to get 100% return from even a fully undamaged storage battery. The recipes also take longer now.

The uncraft recipes are also specifically set to return 1 less than each type of component used in the items. This guarantees that someone can't get lucky to tear apart a nearly-destroyed storage battery and immediately reassemble it. 

Right now the uncraft recipes take the same amount of time as the crafting recipes, but this is essentially a placeholder value: once it's possible to pause/resume disassembly the way we can with crafting, I would expect this value to go up. This is a painstaking task.

I also discovered and fixed a data entry error that caused storage batteries to be repairable with welding while directly installed without a storage battery case.

Relevant regression tests should be correct for the new values.

#### Describe alternatives you've considered
I could have left well enough alone, but some of this would have happened eventually because the thermodynamic implications of creating both mass and energy storage out of air would have eventually needed addressing.

My recipe difficulty changes were more optional; I considered leaving the recipes simply reversible and not attempting to model the difficulty differential with uncraft recipes, but it seemed worth it while I was doing it.

#### Additional context
The additional weight on the full size storage battery makes it much harder to disassemble than before; this could be addressed with either a mechanism for disassembly without needing to carry/wield it, or a mechanism for lifting objects (e.g. cranes) to negate weight for wielded items while in range.

### CODE REVIEW

**Comment by esotericist** [comment]
Actual math details on the items, since I forgot to include those:
Small storage battery was unchanged.

Medium storage battery went from 31kg to 35kg, now needs 14 SBS components (instead of 8) and doubled in volume (2.5 liters to 5.0 liters).

Large storage battery went from 150kg to 200kg, now needs 80 SBS components (instead of 32) and doubled in volume (from 10L to 20L)

For recipes, I added electronic scraps to both the recipes for medium/large batteries. I considered adding plastic to the recipes, but I honestly forgot about it by the time I was submitting this, so I didn't do that. I could add that in revision if requested.

**Comment by mlangsdorf** [comment]
Looks good, but could we have a recipe to make full size batteries from medium batteries?  I agree it doesn't make sense to require people to merge small to medium to full size, but I think it makes sense to allow someone with a bunch of medium batteries from electric scooters or whatever assemble them into a full size battery in one step.

**Comment by esotericist** [comment]
I can do this in probably a few hours. Anything else desired while I'm at it?

**Comment by esotericist** [comment]
The new recipe takes 5 medium storage batteries, 10 small storage batteries, and additional components equivalent to a medium storage battery construction.

Had to do it this way because medium storage batteries have a charge capacity of 7,000, which doesn't divide 40,000 evenly. An alternative would be to change mediums to be 8,000 or somesuch, but I was told not to tinker with the power values.

**Comment by esotericist** [comment]
If possible #29631 should be merged before or at the same time as this, because the 200kg storage batteries are a pill to work with.

**Pull request merged**
