### PR TITLE
Obsolete fusion gun and fusion pack, move to Aftershock

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Mods "Move fusion gun to Aftershock"

#### Purpose of change
These items have little basis in reality, and as such have no place in the main game.
Additionally, they contain a reference to the game being set in 20XX, which hasn't been the case for years.

#### Describe the solution
Move the definitions for the fusion gun, fusion packs, fusion gun turret, and fusion pack recipe into both Aftershock, and `obsolete.json` (in a much reduced form).
Remove all references to these items in base game item groups, and add them to Aftershock item groups.
Remove the hardcoded spawn of these items in one of the lab finales.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Isn't there also a  fusion gun arm CBM?

**Comment by anothersimulacrum** [comment]
Yep, got that too now.

**Comment by Night-Pryanik** [comment]
I don't like this. Fusion gun is a kind of sci-fi stuff that _could be_ developed in our alternate Cataverse.

**Comment by I-am-Erk** [comment]
I don't know about that. Everything else has a basis in real life energy weapons, with the cdda caveat of compact folded dimension energy cells making power availability less problematic. I don't think fusion cannons are based on real life tech

**Comment by chaisawlajatang** [comment]
>Additionally, they contain a reference to the game being set in 20XX, which hasn't been the case for years.

So just change the description, maybe?

>These items have little basis in reality, and as such have no place in the main game.

There are already a lot of things with little basis in reality, but they exist in game. Bionics aka artificial stomachs, cybernetic brains, teleport devices, quantum tunnels, finger screwdrivers are ok, but fusion blaster is not?

**Comment by Firestorm01X2** [comment]
> These items have little basis in reality, and as such have no place in the main game.

Why? So the point of removing is THIS?  Unrealistic? And that is all?

>Additionally, they contain a reference to the game being set in 20XX, which hasn't been the case for years.

Why not just remove that reference?


Zombies and blob are unrealistic also. So let's remove them, right?

**Comment by Mecares** [comment]
Well Kevin said repeatedly that one unrealistic thing in the game is not an argument for another to be in the game, but rather an argument for the removal of both.

Let's talk about gameplay effects: 
Fusion gun is for me at least too good to use since the ammo is too rare, I hardly ever use it.
Fusion blaster arm, I never use it because i don't want to lose an arm.
Fusion blaster rifle is extremely Op: an explosive weapon with huge blast radius and free ammo.

For me the gameplay effect would be very little, one less too good to use weapon in my gun pile and other explosives would get a bit more interesting.

**Comment by Firestorm01X2** [comment]
> For me the gameplay effect would be very little, one less too good to use weapon in my gun pile and other explosives would get a bit more interesting.

Then maybe it better to rework gun to make it more useful than to remove it completely.

> Let's talk about gameplay effects:
> Fusion gun is for me at least too good to use since the ammo is too rare, I hardly ever use it.
> Fusion blaster arm, I never use it because i don't want to lose an arm.
> Fusion blaster rifle is extremely Op: an explosive weapon with huge blast radius and free ammo.

Yes that is. Some arguments from gameplay point of view. This arguments questionable and discussible.

But none of it exist in PR' author description. Exact point of author's view is "unrealistic- let's remove."

**Comment by paulenka-aleh** [comment]
Well, it's definetly for Kevin to decide what fall under 'isolated sci-fi elements' but fusion weapons in general for an evil government lab that created alien invasion from other dimension causing zombie apocalypse doesn't seem to be 'that much' sci-fi.

I'll be a bit sad to see it go while other stuff like cloaking (way unrealistic giving it hides clothes) and nanobots (destroys balance) CBMs remain around. There are really kore weird things to remove or rework.

**Comment by I-am-Erk** [comment]
The fusion gun is extremely rare, unnecessarily powerful, uses ammo so rare it's prohibitive to use it at all, and does nothing a LAW shouldn't do. There's really no play balance to discuss here, you're working up a lather over very little.

There are other very high tech elements of the game that need re-examining, sure. That is beyond the scope of this pr.

**Comment by chaisawlajatang** [comment]
> is extremely rare, unnecessarily powerful
I can say the same about mininukes, hexamine charge, some rivtech guns and grenade launchers. 

>uses ammo so rare it's prohibitive to use it at all
Fusion blaster uses UPS energy.

>and does nothing a LAW shouldn't do
It's a high-end weaponry with it's own niche. And I can say the same - endless rows of recently added glocks and nuts do nothing another 9 mm pistol and hickory nut shouldn't do.

**Comment by Night-Pryanik** [comment]
> The fusion gun is extremely rare

Rarity isn't a reason to remove.

> unnecessarily powerful

Power isn't a reason to remove.

> uses ammo so rare it's prohibitive to use it at all

Ammo scarcity isn't a reason to remove.

> does nothing a LAW shouldn't do

Comparison not in a favor of another weapon isn't a reason to remove.

All things you mentioned could be tweaked in one way or another. None of them (individually or all together) act as a good reason to remove.

**Comment by Mecares** [comment]
Obviously they could, i was just saying that there would be no big gameplay impact if they were removed because they are unrealistic. I was not saying they should be removed because of gameplay reason just that it wont have much consequences gameplay wise.

**Comment by chaisawlajatang** [comment]
> there would be no big gameplay impact if they were removed 

It's not the reason to remove them. Honestly - about 1/3 (maybe even half) of all current content can be cut out without big gameplay impact.

**Comment by Mecares** [comment]
I do not claim that they should be removed because of gameplay impacts all i say is that the gameplay impact is no argument against their removal.

**Comment by Lorith** [comment]
If this is being removed, blazemod needs to be set to require aftershock, as it makes use of the fusion blaster.  All my other points have already been covered by multiple people, might as well just remove half of the game if we can't have anything that is unrealistic by today's IRL standards.

**Comment by anothersimulacrum** [comment]
> If this is being removed, blazemod needs to be set to require aftershock, as it makes use of the fusion blaster.

Thanks, I missed that! I'll adjust it as such.

> Change the description

That's what I was originally going to do, but I was told by Kevin that the Fusion Blaster has almost no place in the base game, so that's why I expanded into migrating this into Aftershock.

**Comment by I-am-Erk** [comment]
Again, "other things are unrealistic" isn't a defense against taking out something off theme, it's at best an argument for evaluating those things.

My point wasn't that those were reasons to remove the fusion blaster, I was pointing out that there is no "balance evaluation" that needs to occur to remove it.

The reason for removing it is that unlike other weapons we've chosen to keep, it's not based on real life technology with a few small handwaves. It's purely fictional. Yes, there are other items with that problem; they, too, will be re-evaluated. Probably most can be refluffed, like plutonium cells were, but this one doesn't need refluffing.

If arguments are going to continue to just be "but other things are unrealistic", I think this can safely be merged. At the very least, people could try to make a salient point instead of repeating the same ancient arguments repeated every single time something hits the cutting room floor.

**Comment by Lorith** [comment]
Also now that I think of it, can the game add mods mid-load if a listed mod has a required mod that isn't in the existing load order?  If not, that may be a problem, as many people (including myself) use blazemod but not aftershock.

**Comment by chaisawlajatang** [comment]
>instead of repeating the same ancient arguments repeated every single time

But this argument is repeatingly used as a reason to remove something. Unrealistic? Remove. It's unrealistic and should be removed. 

>If arguments are going to continue to just be "but other things are unrealistic", I think this can safely be merged

Alright. No, seriously. Merge it. But if content gets removed because it's not realistic and not based on IRL technology, please for consistency sake remove all CBMs, all robots, manhacks, mutagens, autodoc et cetera et cetera. It's a GAME, a nice GAME with its own unique setting - apocalypse with zombies and sci-fi elements. And all what will remain after is a generic roguelike, but with 9000 almost identical pistols. Cool.

>people could try to make a salient point

Ok. Fusion and laser weaponry has its own niche. It's difficult to obtain, it has problems with ammo, it may be too powerful, fusion blaster has to be crafted into gun, but it's a heavy weapon with colossal firepower. And it's fun.

**Comment by I-am-Erk** [comment]
> But this argument is repeatingly used as a reason to remove something. Unrealistic? Remove. It's unrealistic and should be removed.

Yes. Because we have a design document that says what our goals are, and removing or changing things that don't fit with the goals is an ongoing theme. Of course you hear it repeatedly.

> Alright. No, seriously. Merge it. But if content gets removed because it's not realistic and not based on IRL technology, please for consistency sake remove all CBMs, all robots, manhacks, mutagens, autodoc et cetera et cetera. They're unrealistic and not based on current tech level in no way.

CBMs, robots, mutagens, and manhacks all have basis in real life technology with a clear explanation of where they diverge. That's why I specified that as a point of difference with fusion guns. Seriously. Manhacks? It's literally a quadcopter drone with cutting weaponry on it, how is that unimaginable by current science?

Of note, Autodocs *are* slated for massive changes.

> It's a GAME, a nice GAME with its own unique setting - apocalypse with zombies and sci-fi elements. And all what will remain after is a generic roguelike, but with 9000 almost identical pistols. Cool.

Another argument that we hear every time something gets cut from mainline, and yet strangely the game remains popular and fun. It's almost as if we're following a carefully crafted design pattern and not just running around madly with scissors.



> Ok. Fusion and laser weaponry has its own niche. It's difficult to obtain, it has problems with ammo, it may be too powerful, fusion blaster has to be crafted into gun, but it's a heavy weapon with colossal firepower. And it's fun.

Like I said, there is no niche the fusion blaster occupies gameplay wise that can't be occupied identically by a LAW.

Lasers aren't slated for removal. They are based on a real technology with a caveat we can easily explain in game. Bringing them up is a great way of demonstrating exactly where the line in the sand is.

**Comment by Rail-Runner** [comment]
I looked up, but couldn't really find any info on real-life prototypes with the same operating principle as the fusion gun. Maybe the gun could be converted to essentially be a heavy laser rifle, fulfilling a role similar to conventional anti-materiel rifles. Currently there are only two laser weapons: a pistol and an assault rifle; having more variety on it could be good.

**Comment by I-am-Erk** [comment]
I'm not sure lasers really have the capability to be anti materiel with modern technology... Afaik they have troubles penetrating heavy plating and things because the contact site turns to plasma and the plasma convection insulates the material under it. I'm not sure though, it's not something I keep up on.

Really I think huge anti-materiel energy weapons *belong* in the supertech sci fi content pack.

**Comment by chaisawlajatang** [comment]
>Yes. Because we have a design document that says what our goals are, and removing or changing things that don't fit with the goals is an ongoing theme. Of course you hear it repeatedly.

So the argument "We remove it just because it's unrealistic" is valid, and the argument "Don't remove it just because it's unrealistic" is not. Ok. Got it.

>CBMs, robots, mutagens, and manhacks all have basis in real life technology

Really? Are there IRL equivalents of cortex-compatible processor, synthetic gastrointestinal system, artificial cybernetic eyes, teleportation device, extreme speed enhancer (time dilation), soldering iron and screwdrivers in fingers, palm implanted EMP projectors etc? 

Robots - almost autonomous robots with semi-independent AIs, allowed to fight criminals and assist surgery?

>It's literally a quadcopter drone with cutting weaponry on it, how is that unimaginable by current science?

A drone. With almost unlimited maneurability and flight time. With such accuracy it could really cut someone without topping over.

>Another argument that we hear every time something gets cut from mainline, and yet strangely the game remains popular and fun.

Is it fun? Cutting en masse started not long ago, and I just ant to emphasize the tendency.

>Like I said, there is no niche the fusion blaster occupies gameplay wise that can't be occupied identically by a LAW.

But with this very argument we should severely reduce the amount of content, because a LOT of weapons overlap their roles. Dozens of swords, spears, axes, guns, calibers, occupying almost the same roles. 

> They are based on a real technology with a caveat we can easily explain in game.

IRL technology requires an enormous power source and in no way can be fitted into a laser rifle (and laser pistol as well) in current technology level.

**Comment by I-am-Erk** [comment]
Again, and again, we're not cutting it *because* its role can be filled by something else, it's just that arguing that it has a gameplay role is irrelevant, since that gameplay role can be wholly filled by other things that fit with the design direction.

At this point it's clear you're not paying any attention to what I'm saying, so I'm going to stop responding to you.

**Comment by chaisawlajatang** [comment]
Feel free to ignore this post, I don't ask for your respond.

You say I'm not paying attention to your words but you don't pay attention to mine. 

I said that a lot of things (almost everything with a tiny bit of scifi) don't fit the design direction, so they should be removed too. 

You say

>we're not cutting it because its role can be filled by something else

With a controversy to yourself

>that gameplay role can be wholly filled by other things

"We're not cutting it because its role can be filled by something else, we're cutting it because its role can be filled by something else"

**Comment by jeremyshannon** [comment]
> "We're not cutting it because its role can be filled by something else, we're cutting it because its role can be filled by something else"

No, he just said it's slated for removal because it doesn't fit the design doc. He was pretty clear about it. You're not really making any arguments about why it should be included or how it could be made to fit with the doc.
 That said, I feel you. I won't be happy to see the old fusion gun get removed, if only because I use it in a couple of my saves, and splicing a new mod like Aftershock into existing saves is a nuisance.

**Comment by chaisawlajatang** [comment]
>No, he just said it's slated for removal because it doesn't fit the design doc

https://cataclysmdda.org/design-doc/

>**Super-technology exists,** but it is mostly restricted to secret lab facilities and military special forces.
>Balance is adjusted by placement of otherworldly or other **fictional** elements such as zombies and robots in addition to natural hazards.

I already pointed that AI-driven robots and CBMs are somehow realistic but other scifi elements are not, but well, okay, they're in the design document, fine. But the same document says about super technology.

>You're not really making any arguments about why it should be included or how it could be made to fit with the doc.

As said in the doc, super technology exists, but restricted to secret lab facilities and military special forces. And I'm not arguing about why is should be INCLUDED, I'm arguing about why it shouldn't be REMOVED. Long story short - because it fits the lore, because it's a heavy weaponry (and it differs from grenade launchers, it requires power to operate, requires different skill, requires a skill and recipe to craft fusion blaster from CBM, it ignites the ground and it feels like secret super technology). Sure, it may be not enough or not clear enough, but that's my point. Cataclysm always was with a lot of sci-fi, making an interesting setting. Sure thing, everything can be migrated into Aftershock or Bright Nights or whatever, but what remains?

**Comment by I-am-Erk** [comment]
@jeremyshannon you are right on that, you shouldn't need to install aftershock to use the item if you have it already, just to have it spawn in game. It would be best to keep the full functional stat block in obsolete.json and just remove spawning information from mainline.

**Comment by Night-Pryanik** [comment]
Fusion gun fits the design doc - it's a rare, restricted and fictional super-technology. By these features it has a right to exist in the Cataverse.

I'm asking @kevingranade to make a final decision on this matter.

**Comment by nexusmrsep** [comment]
Setting aside "fusion" aspect for a small mental leap. Technologically speaking - is there perhaps any other weapon platform or a prototype with viable future, that would work like this? A thermobaric TBX/EBX serial 40mm grenade launcher perhaps? If there is, why don't we replace the fusion weapon wirh an extrapolation of existing tech, rename it, and enjoy it, rather then flushing the existing code down the drain?

**Comment by Night-Pryanik** [comment]
Fully agree with @nexusmrsep. Right now I'm reading [Raygun article on the Wikipedia](https://en.wikipedia.org/wiki/Raygun) searching for variants of converting fusion gun into.

**Comment by kevingranade** [comment]
First regarding the PR itself, we need an obsoletion process, not just ripping it out.  In other words this shouldn't break anyone's saves.

In short:
Remove things that generate the fusion gun, including marking them obsolete if necessary (e.g. recipes).
Move the fusion gun and related definitions to obsolete.json without changing them (except in this case maybe fix the description).
Optionally add spawns and recipes to a mod if desired.
In a MUCH later PR (probably post-0.E), actually move the definitions to a mod or delete them.

Regarding the discussion around reskinning the fusion gun:
If you have a craving for supertech weapons, you can feel free to discuss, propose, etc new additions here or on one of the discussion forums, but I will not consider simply re-describing the fusion gun, because it is PACKED FULL of problems.
1. The whole arm-replacement thing is just silly.
2. The stats are nonsense.
3. t's impossible to fix the stats because the operating mechanism is nonsense.
4. The "salvage the arm and turn it into a rifle" thing is silly.

If you want a supertech gun in mainline dda, you need to come up with a supertech gun that fits the existing lore and improves the game. A rebranded fusion gun is not a good starting point for this, it's better to start from scratch.

**Comment by Firestorm01X2** [comment]
@kevingranade 

> If you want a supertech gun in mainline dda, you need to come up with a supertech gun that fits the existing lore and improves the game

And here is some problems.
First. Where can anyone read what fits game and what is not?  What is silly and what is not? What is nonsense and what is not?

Some kind of design document on that maybe? 

And second. Why not to remove all CBMs right and for all? What is the point of ripping it piece by piece?

**Comment by I-am-Erk** [comment]
It appears that this tech overview for the design doc wasn't added to the TOC... mea culpa there I think. Like all the design doc stuff, it's an ongoing work, but it should answer a lot of these questions.

https://cataclysmdda.org/technology.html

**Comment by Firestorm01X2** [comment]
Ok
>Weaponry
Like power armor, the major divergence point for weaponry is the existence of high density fictionalized power cells.

So you cunt you arm away, install gun in place of it and connect it to me kind of power rare power source.
Now let's compare it with teleportation and time stopping.

And second. Bio fusion blaster already somehow fitted in the past. So things has changed dramatically since then?

**Comment by I-am-Erk** [comment]
Who is to say it "always fitted in the past"? It fit in the original 20XX cataclysm, but Dark Days Ahead has been set in an only slightly different near future for many years now.

Time and teleportation tech fall under a category I haven't added there, dimensional manipulation. I can go add a little blurb on it if it makes you happy, although I wouldn't say the fates of those CBMs has been totally decided.

**Comment by chaisawlajatang** [comment]
Is it ok to throw ideas here? 

> Technology that hasn’t even been prototyped, or at the very least modeled theoretically, in our world is probably not appropriate for Cataclysm.

I just wanna to pinpoit CBMs were nor prototyped nor modeled theoretically IRL, but they're appropriate for Cataclysm. Returning to plasma weaponry (which perfectly fits definition "supertech gun that fits the existing lore"):

https://en.wikipedia.org/wiki/MARAUDER

>Specifically, the objective of the program was the acceleration of a toroid of 0.5-2.0 mg plasma to a kinetic energy level on the order of megajoules using a 5-10 MJ coaxial gun design.[3]
In 1993, the Phillips Laboratory developed a coaxial plasma gun capable of accelerating 1–2 mg of plasma by up to 1010g in a toroid of 1 meter in diameter

https://en.wikipedia.org/wiki/Shiva_Star

>Shiva Star was also used to develop an experimental weapon known as MARAUDER for the SDI effort between 1989 and 1995. The idea appears to have been to create compact toroids of high-density plasma that would be ejected from the device using a massive magnetic pulse.[2] The plasma projectiles would be shot at a speed expected to be 3000 km/s in 1995 and 10,000 km/s (3.3% of the speed of light) by 2000

https://en.wikipedia.org/wiki/Electrolaser

>An electrolaser is a type of electroshock weapon that is also a directed-energy weapon. It uses lasers to form an electrically conductive laser-induced plasma channel (LIPC). A fraction of a second later, a powerful electric current is sent down this plasma channel and delivered to the target, thus functioning overall as a large-scale, high energy, long-distance version of the Taser electroshock gun.

>Publicly traded company Applied Energetics (formerly Ionatron) develops directed-energy weapons for the United States military. The company has produced a device called the Joint IED Neutralizer (JIN) which was deemed unfit for field use in 2006.[3] The JIN is intended for safely detonating improvised explosive devices (IEDs). Future designs include weapons mounted on land, air and sea vehicles and as a hand-held infantry version.

>Scientists and engineers from Picatinny Arsenal have demonstrated that an electric discharge can go through a laser beam. The laser beam is self-focusing due to the high laser intensity of 50 gigawatts, which changes the speed of light in air.[6] The laser was reportedly successfully tested in January 2012

So plasma gun of sorts is possible IRL, it was modeled and even prototyped dozens years ago.

**Comment by Firestorm01X2** [comment]
Ok. Just stop it.

Really important hing here is:

>Well Kevin said repeatedly that one unrealistic thing in the game is not an argument for another to be in the game, but rather an argument for the removal of both.

So we can't compare things. And probalbly don't need to waste time on argumentation.

Thing is have been decided already by Kevin. Now deal with that or go away.

**Comment by I-am-Erk** [comment]
> CBMs were nor prototyped nor modeled theoretically IRL

https://openbionics.com/hero-arm/
https://www.mayoclinic.org/tests-procedures/ventricular-assist-device/about/pac-20384529
https://www.mayoclinic.org/tests-procedures/cochlear-implants/about/pac-20385021

A plasma weapon isn't a fusion cannon. I don't even know what a fusion cannon *is*, but plasma weaponry certainly doesn't have anything to do with fusion.

**Comment by nexusmrsep** [comment]
@Firestorm01X2  when comparing green aliens with grey aliens, or any other fictional thing with literally any other fictional thing, it's the game owner word that is the judgement between what goes and what's not. In that manner your arguments and comparisons are pointless. What holds and what stays is his decision and you've literally seen the judgement before your eyes. You may not like the verdict but making comparisons between inexistent things or calling out "mystical" design document like it's the unremovable amendment to the Constitution of the USA just misses the point and is arguing for arguings sake. Design doc, in it's vagueness, can be changed or edited at any point. The final say in this particular matter is there at a platter before you.

**Comment by chaisawlajatang** [comment]
Ok, I admit, we have implants to improve hearing and blood pumping and replace missing arm. I was wrong. Maybe it could be extrapolated further, and you stated earlier about refluffing and reexamining them.

>A plasma weapon isn't a fusion cannon. I don't even know what a fusion cannon is, but plasma weaponry certainly doesn't have anything to do with fusion.

Of course, this has to be changed and refluffed, I totally agree. "Fusion" gun is something very... obscure?Plasma gun is much better.

**Comment by I-am-Erk** [comment]
I would say in general, before adding a new high tech device, it would be good to consider if there is already a current tech weapon that will accomplish the same goal and have more common ammunition. If you want to do that, I would suggest brainstorming it on discord, discourse, or the issues section. it's not going to be a refluff of the fusion rifle for reasons already stated.

**Comment by Firestorm01X2** [comment]
@chaisawlajatang 
>Maybe it could be extrapolated further, and you stated earlier about refluffing and reexamining them.
Nope, not going to happens.

Goodbye fusion blaster CBM.

There is no point to discuss then.

**Comment by anothersimulacrum** [comment]
So, I've made changes.
I've moved everything but the recipes intact to `obsolete.json`, and added a recipe obsoletion entry there.
I added spawns on the gun to Aftershock, and put the recipes there as well.

**Comment by Firestorm01X2** [comment]
Game was really improved here. Thank you for cooperation, I guess.

**Comment by Human-Shield** [comment]
Fusion cells = very small bullet that contains group of hydrogen atoms in a super material casing.
Fusion cannon = uses dimensional manipulation to start chain reaction on bullet casing to fold space inward which mimics extreme gravity. Hydrogen atoms convert to helium in nuclear fusion and release the explosion of an atom sized unstable star. 

Cutting off the arm part was stupid.

**Comment by Lorith** [comment]
As I said before, blazemod needs to be updated to require aftershock since it makes use of the fusion gun, and it needs to be looked into if the load process can add required mods that are missing or at least pop up a message since many people use blazemod and not aftershock.

**Comment by I-am-Erk** [comment]
Lorith: the fusion gun still exists in the main game, blazemod will work fine. If people using blazemod want to get fusion gun stuff to build blazemod fusion gun parts, they'll need aftershock on for it to spawn, but load order doesn't matter at all in those cases.

**Comment by lgordon85** [comment]
> 
> Of note, Autodocs _are_ slated for massive changes.
> 
Might I also note. Autodocs essentially already exist.  I can pretty much guarantee you that Intuitive Surgical could program their surgical robots to perform surgeries by themselves rather than as a conduit for a surgeon, but I suspect the AI tech or public confidence just isn't there to meet safety tolerances or make it marketable.

I would suspect that in 20-30 years (or sooner) some specialist surgeons could find themselves replaced in some cases by robotic surgeons.

**Comment by I-am-Erk** [comment]
That is essentially the technology I'm using as the basis for what the existing autodoc will do. Basically you have to either do quite a bit of work reprogramming it to try to run autonomously, in which case you need to know a lot (or more likely have npcs who know a lot) about medicine and computers; or, much more easily, you can get an npc with at least basic medical knowledge to stand behind it and push buttons and do decision making for it. The more knowledge the npc has, the better.

**Comment by lgordon85** [comment]
I look forward to that PR.

Possibly make it so that pre-existing program sequences of varying quality for CBM installation can be hacked from hospital computers, labs,  underground CBM operations (autodoc basements).  Adds some additional benefit to computer skill.

**Comment by Firestorm01X2** [comment]
> I look forward to that PR.
> 
> Possibly make it so that pre-existing program sequences of varying quality for CBM installation can be hacked from hospital computers, labs, underground CBM operations (autodoc basements). Adds some additional benefit to computer skill.

Instead of starting to shoot birds with BFG there is something like that can be done:
https://github.com/CleverRaven/Cataclysm-DDA/issues/27837
https://github.com/CleverRaven/Cataclysm-DDA/issues/27826

Just consider this.

**Pull request merged**
