### PR TITLE
Persist installed CBMs across revives

### LINKED ISSUE #55389: NPCs drop all installed bionics when their bodies rise as zombies
### Describe the bug

When a dead NPC rises from the dead into a zombie form, all of their bionics drop on the ground without dissection.

### Steps to reproduce

1. Spawn NPC
2. Install any bionics into them
3. Kill them and wait a day for them to rise
4. Bionics will be on the tile where the body was "risen"

### Expected behavior

I expect the bionics to stay in the body or only get them via dissection of the corpse/zombie.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c7ffe3e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### Additional context

PrepNet orchards from Aftershock revealed this one to me, as NPCs who spawn with many bionics. Visiting a previous location where I killed the NPC and didn't pulp their body, his entire loadout dropped without any dissection required. Not sure how many NPCs spawn with bionics preinstalled but it sure doesn't seem intended.

### PR DESCRIPTION
**Pull request by psuedolet**
#### Summary
Bugfixes "Persist installed CBMs across revives"

#### Purpose of change
Closes #55389. Reviving no longer drops a corpse's CBMs. Corpses with installed CBMs revive into a zombie with the (non-active) CBMs, so that when it dies, the player can dissect the corpse and recover the CBMs. 

#### Describe the solution
1. When reviving, broaden the itemtype == corpse check to include all items with the corpse flag (npcs drop corpse_generic_human, not corpse)
2. Add a bionics inventory to monsters. 
2a. pull from it when the creature dies
2b. fill it when a corpse revives
2c. add it to json save/load

#### Testing
1. Install CBM into friendly NPC
2. Kill NPC 
3. Wait until corpse revives - should not drop CBM
4. Save/Load
5. Kill zombie
6. Dissect corpse - should drop CBM

#### Additional context
Currently no way for the player to tell that a zombie has cbms in it's inventory.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Nice, while you're at it could you see if you can put CBMs in the corpse pocket for every zombie. For exemple let's say a player kills a zomborg, instead of spawning the CBMs when the player dissect the zomborg the CBMs could be generated once at put in the corpse pocket and stay there through subsequent revivification untill dissection. That would open at least two new mechanics: checking for CBM without dissecting, and maybe dropping dmaged version of CBMs when the zombie rots for good

**Comment by psuedolet** [comment]
That's certainly doable. I'll need to look at the butchering code again, but I think the CORPSE pocket drops for any kind of butchering. So that'd need to change so it only drops when dissecting.

**Comment by psuedolet** [comment]
With the latest changes, CBMs are generated at death, and dissection pulls from the CORPSE pocket instead of the monster type's dissect list. It mostly works as expected with 2 caveats:  
1. Dissection no longer displays the harvest group's message. 
2. There's now a hard-coded relationship between certain item types and harvest drop types  
I could change the bionics_inv (now dissectable_inv) to a vector<harvest_entry> type and retain the harvest info from the monster type, but then we still wouldn't have a harvest message or harvest drop type for items not from the monster type (e.g. cbms installed into npcs)  
I changed the PR to a draft while I solicit feedback.

**Review by dseguin — CHANGES_REQUESTED** [review]
> There's now a hard-coded relationship between certain item types and harvest drop types

I think this is the wrong way to go about it. The harvest drop type should be preserved with the item. There's not a great way to do it, I'd make it a property of the item that gets updated on monster-item transformations

**Pull request closed without merging**
