### PR TITLE
Missing flags for gloves

### PR DESCRIPTION
**Pull request by Cyrano7**
Edit: Things have evolved a bit.
Added OUTER flag to mittens
Added OUTER flag to bag gloves

### CODE REVIEW

**Comment by illi-kun** [comment]
Currently, they're in line with fur gloves, winter gloves, wool gloves, rubber gloves, so I guess all of them should be approx. the same.

Also, I didn't find any gloves in outer layer, why army winter gloves should be so special?

**Comment by Cyrano7** [comment]
hmmm. When I was looking at gloves earlier I must have missed that some gloves don't have VARSIZE. As for OUTER I think there is an argument that your not really suppose to be wearing something over them. 

As for them being special are you saying that they shouldn't have OUTER or that fur, wool, winter and army winter should all have OUTER?

**Comment by illi-kun** [comment]
Re: ```OUTER```: AFAIK, currently only skintight level & regular level are used for all types of clothes for hands. It make no sense to move everything from regular level to outer one since it changes nothing. The only gloves-like item which should be ```OUTER``` is muff (I'm not sure it is in the game). And yes, all gloves listed above should be changed simultaneously.

Re: ```VARSIZE```: this flag may be omitted intentionally since not all clothes can be fitted.

**Comment by Coolthulhu** [comment]
VARSIZE means their actual encumbrance is 10.
With material thickness 4, they have armor noticeably better than leather gloves (9 vs 6, pre-reinforcement). This would be OK, but they also have 100% coverage, compared to leather gloves' 95%.
Since their role is warmth and not protection from damage, some of the protective stats should drop. Either 1 less thickness and 5% less coverage or 2 less thickness.

OUTER should probably be reserved to very bulky gloves that can be easily worn over regular size gloves. Oven gloves, for example. Nothing small enough to allow comfortably pulling a trigger of a handgun (unless it was fingerless or something like that).

**Comment by mutability** [comment]
Bag gloves might make sense as OUTER too?

**Comment by Cyrano7** [comment]
@Coolthulhu we have oven gloves? If not that's a good idea. They could be slightly fire resistant to. I don't think the fire proof stuff actually protects you yet though in game.

**Comment by Coolthulhu** [comment]
> we have oven gloves?

Not yet.
> I don't think the fire proof stuff actually protects you yet though in game.

Fire protection (for characters) isn't implemented yet.
Implementing it would be easy, but then the balance would break instantly because most fires deal low damage, just often. Kinda like acid, which is a major pain to balance.

And it would look weird when flamethrowers ignored the resistance with the initial hit (because all ranged weapons deal piercing damage).

**Comment by Cyrano7** [comment]
So finial verdict. Army winter gloves should be left alone and wear-over/very bulky gloves without fingers should have OUTER flag?

**Comment by Coolthulhu** [comment]
Sounds good to me

**Comment by Rivet-the-Zombie** [comment]
Works for me.

**Comment by SunshineDistillery** [comment]
Some armor gauntlets could be made outer. Like plate gauntlets from the gothic armor. They're more like heavy mitts. Some don't even have fingers but have a shell that goes over the back of the hand. Player crafted armors might be the same.

**Comment by Rivet-the-Zombie** [comment]
>Some armor gauntlets could be made outer. Like plate gauntlets from the gothic armor. They're more like heavy mitts. Some don't even have fingers but have a shell that goes over the back of the hand. Player crafted armors might be the same.

Sounds like it would be worth looking into.

**Comment by Cyrano7** [comment]
@SunshineDistillery @Rivet-the-Zombie  So the armored gauntlets and all the plate armor actually have the VARSIZE flag. And at 20 base that means that the plate gloves have less encumbrance then the army winter gloves. So maybe they need to be looked at separately in another PR or issue.

**Comment by illi-kun** [comment]
Current state is much better than initial one, works for me.
Re: gauntlets: they can be tweaked separately, if it's required.

**Pull request merged**
