### PR TITLE
Add bratwurst to the game

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Content "Add bratwurst"`

#### Purpose of change

As Rivet-the-Zombie suggested (#27243) there should be another type of sausage that does not need to be smoked and could be cook or fried more easily.

I was not sure if I had to add anything to **recipe_companion.json**, do I need to?

#### Describe the solution

I decided to add bratwurst to the game.

grafik

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I think you need to update your master, you shouldn't need to add 67k lines and remove 47k to add a new recipe and item.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> I think you need to update your master, you shouldn't need to add 67k lines and remove 47k to add a new recipe and item.

You are right! The only way to update my master right now seems to be to delete my repo entirely and reforke it afterwards or to pull the latest changes into my actual repo. I choose the latter since there still was / is an open PR #27243.

**Comment by anothersimulacrum** [comment]
If you can revert the first commit in this branch, Update (#1), that should just leave your changes, and may work.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> If you can revert the first commit in this branch, Update (#1), that should just leave your changes, and may work.

Hmmm. it's not getting any better, aye?

**Comment by anothersimulacrum** [comment]
You might just want to delete this branch and remake it then.

**Comment by Pupsi-Mupsi** [comment]
I open a new PR one to fix the mess i made!

**Pull request closed without merging**
