### PR TITLE
[MoM] Fix possibility of studying new powers concurrently

### LINKED ISSUE #75119: [MoM] Wave of Force learning recipe fails, incorrectly references Enhance Strength
### Describe the bug

I unlocked three contemplation recipes for new Telekinetic powers (Enhance Strength, Wave of Force and Slowfall), and after some shenanigans acquired the necessary crystal dust and decided to learn them. I successfully learned Enhance Strength, and a little later I decided to try to learn Wave of Force.

I spent several hours meditating, as expected, but when the meditation finished I got a message saying I'd unlocked Enhance Strength, a power I'd already unlocked earlier that day. I didn't learn Wave of Force, or any other power.

### Attach save file

still having that issue with save archives failing

### Steps to reproduce

1. Attempt to use the contemplation recipe to learn Wave of Force?

### Expected behavior

The contemplation recipe for Wave of Force teaches Wave of Force.

### Screenshots

image
Received a notification I'd learned Enhance Strength, a power I already knew.

image
The last thing I crafted was the contemplation recipe for Wave of Force.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 48419ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I tried looking in telekinesis_practice.json to see if I could fix the problem, because this feels like it could be a simple copy-paste error. I didn't find anything relevant, but I did find an unrelated copy-paste error and adressed it in #75118

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary

Bugfixes "[MoM] Fix possibility of studying new powers concurrently."

#### Purpose of change

It was possible, by canceling and starting new contemplations repeatedly, to attempt to learn multiple powers simultaneously. 

Fixes #75119

#### Describe the solution

Originally I was going to add a `compare_string` section to each learning EoC to make sure it only fires for the most-recently contemplated power, and I thought I could genericize it, but while I accounted for most problems, the one I can't account for is "start trying to learn an easier power (that takes less time), then cancel it and start trying to learn a harder power, in order to learn the harder power in less time." Since queued EoCs can't be cancelled or have their queue time modified, I don't think there's a way around that one.

Also, make it so you learn the power learning tracking effect when the learning EoC fires, which I can't believe I wasn't previously doing.

#### Testing

Started and stopped contemplation on a dozen powers before settling on the most difficult one--the learning EoC only fired once. Started and stopped contemplation on four powers and did not stop contemplating when I got the "you did not learn anything" Eoc to make sure that all conditions for learning were still being met. The learning EoC still only fired a single time.

### CODE REVIEW

**Comment by GuardianDll** [comment]
> there's no way for EoCs to check whether other EoCs are queued

`time_until_eoc()` math is exactly about it - if it returns -1, EoC is not queued

**Comment by Standing-Storm** [comment]
> `time_until_eoc()` math is exactly about it - if it returns -1, EoC is not queued

But you can't affect that EoC, correct? Just know it exists

**Comment by GuardianDll** [comment]
That is true, yes

**Comment by Standing-Storm** [comment]
> That is true, yes

Alas. Once that's possible I can finally genericize this, but for now I'll just fix the bug.

**Pull request merged**
