### PR TITLE
Renamed id of f_floor_canvas to f_punching_bag

### PR DESCRIPTION
**Pull request by Night-Pryanik**
I assume this was a mistake and not some joke or obscure reference.

### CODE REVIEW

**Comment by Leland** [comment]
Changing IDs poses concerns to existing worlds, no? If so, may want to leave alone as IDs have no player impact.

**Comment by ZhilkinSerg** [comment]
You can try `migration.json`:

```
[
  {
    "id": "music_cd",
    "type": "MIGRATION",
    "replace": "plastic_chunk"
  }
]
```

**Comment by Night-Pryanik** [comment]
I think migration is for items only.

**Comment by DracoGriffin** [comment]
Yeah, that's what I seem to have[ found in #24007](https://github.com/CleverRaven/Cataclysm-DDA/pull/24007#discussion_r195958309).

So for migration.json to work for this, it will need to be adjusted to influence outside just created items.

**Pull request closed without merging**
