### PR TITLE
Weapon Categories: Fencing (Second Pass)

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Balance "Change the weapon categories for Fencing"

#### Purpose of change
Partially implements #51867.
Fencing: Apply suggestions from the comments in #52786.

#### Describe the solution

| Weapon Category  | Martial Art | Includes |
| ------------- | ------------- | ------------- |
| FENCING_BLADES  | Fencing  | The Foil, Épée, Sabre, and similar weapons  |
| BATONS | Krav Maga, Eskrima, Silat, Fencing  | Batons, tonfas and weapons of similar shape |

Added BATONS as a possible weapon category for fencing, changed the FENCING_WEAPONRY to FENCING_BLADES and removed the batons from the category, the hammer and wench were removed from the batons category.

1 new weapon category:

- FENCING_BLADES
Swords and pointed, bladed weapons usable in fencing, these are generally pointed, slender and of medium length.

#### Describe alternatives you've considered
To divide the style along the lines of the 3 fencing weapons: The Foil, Épée and Sabre, but they seem the same to me.
Another alternative is the original implementation in the previous PR, but I think this is better.

#### Testing
Spawned in game several fencing weapons, all working without problem.

#### Additional context
Style weapons before the first pass PR:
imagen

Style weapons after the first pass PR:
imagen

Style weapons now:
imagen
I'm not sure if the umbrella should really be called a "Fencing blade" but it **does have** cutting damage...

Fencing weapons:
https://en.wikipedia.org/wiki/Fencing#Weapons

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
The cavalry saber should probably not be a fencing blade. It's a curved sword 
( something like this - [https://www.medievalcollectibles.com/product/american-cavalry-officers-steel-sword-with-scabbard/?matchtype=&keyword=](https://www.medievalcollectibles.com/product/american-cavalry-officers-steel-sword-with-scabbard/?matchtype=&keyword=) ) primarily used for slashing attacks and wouldn't be useful for the quick thrusts in a fencing style.

This can be confusing as saber/sabre also refers to a fencing sword ( [](https://www.thehemashop.com/hutton-sabre) ) which is really just a stout rapier-type weapon.

I'm also not sure about the shillelagh. I get the logic of a collapsible baton or umbrella, but the shillelagh/loaded stick are big heavy knob-ended clubs. By that logic couldn't you also use a mace or a hammer in this style?

Fencing also seems to variably refer to both the dueling sport and the general concept of swordfighting, so that further muddies the issue. It seems to me like the fencing in-game is the former style and should be restricted to broadswords, sideswords, foils, and maybe thin batons, while the choppy swords could go to HEMA and the heavy clubs could go elsewhere.

**Comment by Termineitor244** [comment]
> 
> 
> The cavalry saber should probably not be a fencing blade. It's a curved sword ( something like this - https://www.medievalcollectibles.com/product/american-cavalry-officers-steel-sword-with-scabbard/?matchtype=&keyword= ) primarily used for slashing attacks and wouldn't be useful for the quick thrusts in a fencing style.
> 
> This can be confusing as saber/sabre also refers to a fencing sword ( https://www.thehemashop.com/hutton-sabre ) which is really just a stout rapier-type weapon. This is represented in-game by the "fencing saber". Same name, completely different weapon.

Following the blame I arrived at #21084 as the PR that implemented the cavalry saber (And added it to fencing), sadly, there was no image or clear reference for the weapon, but seeing the one in your link and [others](https://witherells.com/lot/3-imperial-german-swords-cavalry-saber-1889-cavalry-sword-and-hunting-sword-3162116), it seems like the cavalry saber has a shape close enough to be used for fencing (Even if not as the most appropriate weapon), I'm not too sure about removing it from the style.

> I'm also not sure about the shillelagh. I get the logic of a collapsible baton or umbrella, but the shillelagh/loaded stick are big heavy knob-ended clubs. By that logic couldn't you also use a mace or a hammer in this style? Similarly the tactical tonfa seems out of place here.
> 
> Fencing also seems to variably refer to both the dueling sport and the general concept of swordfighting, so that further muddies the issue. It seems to me like the fencing in-game is the former style and should be restricted to broadswords, sideswords, foils, and maybe thin batons, while the cavalry saber could go to HEMA and the heavy clubs could go elsewhere.

The [shillelagh](https://www.pinterest.com/pin/474215035768226588/) has (for me) a form very similar to the other batons if taken from the heavier side, the weight is already taken care of in the game by its effect in the velocity of the weapon.

The martial arts (in my opinion) should be as inclusive as possible with their weapons, one cant be picky in the middle of the cataclysm, that was one of the reasons why I started working on the weapon categories.

**Comment by Terrorforge** [comment]
"Cavalry saber" is a rather broad term, since it can refer to pretty much any sword used by cavalry in the last ~400 years or so. Many of them, especially later in history, were quite straight and emphasized the use of the point. Sure, on the [extreme end](https://i.ytimg.com/vi/Sj5ssMdrMKY/maxresdefault.jpg), they're not very much like modern fencing swords, but even then the way they're used _is_. Notably, they all make heavy use of quick, maximum-range attacks through lunge-and-retreat footwork. Also worth mentioning that one the things setting modern sabre apart from other fencing weapons is that cutting is allowed.

Besides, I am of the opinion that Fencing does, can and should represent modern period swordfighting in general. As I said, they share a lot of fundamentals - but more importantly, if we go the other direction and acknowledge that a cavalry saber isn't very much like a fencing saber, we kind of also have to acknowledge that a rapier isn't very much like a fencing foil. And once we go down that route, well, should we perhaps consider that it's likely no martial arts practice would be all that helpful? After all, fighting a horde of mindless zombies is not very much like fencing with a single human opponent.

We we gotta fudge _somewhere_, and I think letting Fencing have a little more than maybe it's strictly entitled to is the most fun option.

**Comment by Shodan14** [comment]
I can see discussing expanding the selections of blades, but I'm very unclear why any batons would be included in the style. There's nothing similar about the use of a precision blade and a baton. And even if superficially similar, poking someone with a walking stick or an umbrella seems useless. Having what's basically a wooden weighed mace ([Shillelagh](https://en.wikipedia.org/wiki/Shillelagh_(club))) here seems beyond ridiculous.

There are already other styles that incorporate a wider variety of weapons(and the number keeps increasing), not to mention brawling.

**Comment by Termineitor244** [comment]
Several batons were already in the style before these PRs, and they were added under the idea that, given their similar form, they could be of some use to execute the techniques of the martial art in the game, I'm not planning to remove them from the style but if there are enough complaints about adding the category to fencing, then I would rather close this PR and leave the weapons with a general category like in the first pass. If someone would like to make an audit of the weapons later then it would easier that way.

> We we gotta fudge _somewhere_, and I think letting Fencing have a little more than maybe it's strictly entitled to is the most fun option.

I'm of the same mind, we should not heavily limit the player, specially for a style with its main weapons (the fencing blades) being difficult to obtain.

**Comment by fairyarmadillo** [comment]
The wikipedia entry for Sabre pretty clearly states that the fencing sabre bears no resemblance to the cavalry saber and the latter is not used in the sport [https://en.wikipedia.org/wiki/Sabre#Modern_sport_fencing](https://en.wikipedia.org/wiki/Sabre#Modern_sport_fencing). It also mentions, as I did, that cavalry sabers are used in HEMA, which is also a martial art in the game. It seems like a pretty clear cut case to me. The cavalry saber is a curved chopping sword meant primarily for use from horseback (e.g. cavalry) where the thrusts and quick steps of a fencing style would not be applicable. You can't really stab people effectively with a sword that curves backwards. The cavalry sabre in-game is described as "This is a curved sword associated with cavalry from the Early Modern period onwards. Lightweight, but a deadly slashing weapon." It is unambiguous about what kind of sabre it is.

Certain clubs were used in the style because cudgels _are_ used in fencing as practice tools and have been for centuries, a cudgel being a lightweight stick that can train users in the use of a straight sword without risk of serious injury. It's not an appropriate style for heavy knob-ended clubs, nor does it make sense for tonfa which are gripped in a completely different manner. 

We already have HEMA and a few other styles to cover historical or modern improvisational swordfighting, the fencing martial art is supposed to represent the skillset associated with the sport. Fencing is a well documented and regimented sport that's widely practiced today, and randomly adding in weapons that don't fit the style because it's fun or convenient to the player or seems outside of the game's primary design philosophy. 

I'm also not sure about your logic for removing the monomolecular sword. It's a straight, lightweight (.1 kg) and presumably quite narrow blade (its edge is one molecule thick!). It is described as "A foot-long blade made from high-tech alloy and edged with bonded nanocrystals."

**Comment by Termineitor244** [comment]
> I'm also not sure about your logic for removing the monomolecular sword. It's a straight (fits inside your forearm), lightweight (.1 kg) and presumably quite narrow blade (its edge is one molecule thick!). It is described as "A foot-long blade made from high-tech alloy and edged with bonded nanocrystals." I might buy that a foot simply isn't long enough to fence with but then it probably ought to be culled from all the sword styles and treated (and named) as a knife in another PR.

Its too long to be considered a knife (but too short for use as a normal short sword), and it has already been culled from most martial arts when appropriate, if its to be added again, it should have an expanded or reduced length to be more easily used as a sword or as knife (And be categorized as that).

> The list should be amended to include cudgels

It has always included cudgels, from before weapon categories, to the fencing weaponry category, to this second pass, the cudgel has not stopped being a fencing weapon.

> drop the cavalry saber, tonfa, shillelagh, and loaded stick

Following your comments about the cavalry saber, I think it would make more sense to change its description to make it more similar to the one in the picture I linked, since the cavalry saber was added only to fencing and was added as fencing weapon years ago (So the goal should be adjusting the item to match what was intended when created). The shilelagh and loaded stick being removed from use in fencing is something that I could see happening, even if I'm not entirely convinced, the tonfa indeed is gripped in a completely different manner, but it can easily being gripped like a normal baton if you want.

> favor cutting/thrusting and drop the bashing damage bonuses

This was a problem with fencing until the martial art rebalance (#33210), maybe with the new restriction of techniques with categories it could be to made to work, but I'm not interested in drastically changing the balance of the martial art for the time being.

As I see it, most of your problems with the PR would be better resolved just closing it and leaving it with the general category of "fencing weapons", and doing some minor changes to items or removing 1 or 2 from the list, so I'm going to close it and leave it in is previous status, for reference, the weapons available to the style would remain as follows:

imagen

More changes can be done in other PRs, but it would be mostly minor changes for what I'm seeing.

**Comment by Terrorforge** [comment]
> The wikipedia entry for Sabre pretty clearly states that the fencing sabre bears no resemblance to the cavalry saber and the latter is not used in the sport https://en.wikipedia.org/wiki/Sabre#Modern_sport_fencing.

Again, the same could be said about the rapier. The closest thing to a real weapon with the characteristics of a sport fencing blade is the [smallsword](https://en.wikipedia.org/wiki/Small_sword), and that's not even in the game.

> It also mentions, as I did, that cavalry sabers are used in HEMA, which is also a martial art in the game.

There is no martial art called "HEMA" in the game. There is a martial art called "medieval swordsmanship", which is a very different beast to later-period sabre fencing. The cavalry saber was added to it not because it's a "HEMA weapon", but because "[dusacks](https://en.wikipedia.org/wiki/Dusack) and [messers](https://en.wikipedia.org/wiki/Messer_(weapon)) are part of germans swordsmanship", see #51462. I think that's kind of spurious tbh, but it wasn't my change

> It seems like a pretty clear cut case to me. The cavalry saber is a curved chopping sword meant primarily for use from horseback (e.g. cavalry) where the thrusts and quick steps of a fencing style would not be applicable. You can't really stab people effectively with a sword that curves backwards.

No offense, but do you actually know anything about historical sabre fencing? Because I'm hardly an expert, but I know enough to tell you that most cavalry sabres are only [lightly curved](https://www.by-the-sword.com/images/product/large/88HCS.jpg), and that their use on foot involves a lot of thrusts and quick steps.

> Certain clubs were used in the style because cudgels _are_ used in fencing as practice tools and have been for centuries, a cudgel being a lightweight stick that can train users in the use of a straight sword without risk of serious injury. It's not an appropriate style for heavy knob-ended clubs, nor does it make sense for tonfa which are gripped in a completely different manner.

I think it would be silly to give Fencing its own category that's just "batons but minus a few things". However, I think this might once again be a problem with the "batons" category. I wouldn't be opposed to splitting it into "batons" and "clubs", the former being the balanced sticks and the latter top-heavy ones.

The tonfa are... debatable. The item simply called "tonfa" is one of [these](https://images.blitzsport.com/item/blitz-plastic-tonfa.jpg?auto=compress), which is clearly meant to also function as a baton, and even traditional wooden tonfa are [sometimes](https://i.ytimg.com/vi/fNAQ47X7U_I/maxresdefault.jpg) wielded in a baton-like fashion. But the CDDA stats (specifically the Parry ability) seem to imply they're wielded in the traditional manner. I'm inclined to keep them in "batons", mainly to not have to add a dedicated "side handle" category for just three weapons, but you culd go either way.

> We already have HEMA and a few other styles to cover historical, modern, or improvisational swordfighting, the fencing martial art is supposed to represent the skillset associated with the sport. Fencing is a well documented and regimented sport that's widely practiced today, and randomly adding in weapons that don't fit the style just because it's fun or convenient to the player seems outside of the game's primary design philosophy.

Again, very few real weapons actually correspond very closely to fencing swords. If you take this attitude as strictly as you seem to want to, you will be left with a style that has the three fencing swords, their sharpened equivalents, and literally nothing else.

> I'm also not sure about your logic for removing the monomolecular sword. It's a straight (fits inside your forearm), lightweight (.1 kg) and presumably quite narrow blade (its edge is one molecule thick!). It is described as "A foot-long blade made from high-tech alloy and edged with bonded nanocrystals." I might buy that a foot simply isn't long enough to fence with but then it probably ought to be culled from all the sword styles and treated (and named) as a knife in another PR.

Lacking the wrist joint makes it a completely different weapon. It also wouldn't have a protective hilt, which is pretty important for this style of fencing. Not to belabor the point, but a cavalry sabre is way more similar to a a fencing epée than what is essentially a surgically implanted [pata gauntlet sword](https://i.ytimg.com/vi/l1uo8Y1Mz2c/maxresdefault.jpg).

> The list should be amended to include [...]

The point of this is exercise to divide weapons into reasonable categories, not to fine-tune each individual style to use precisely and only the very most appropriate weapons. Granted, we have to do a bit of that, but I would rather err on the side of questionable inclusions like the shillelagh over making a bunch of specific exclusions from specific styles.

If you have alternative ideas, you should express them in the form of how you want the categories to be set up. Like, you say the shillelagh should go. Okay. Do you want to remove it from the "batons" category? Do you want to create a separate and overlapping "light batons" category for Fencing to use? Do you want to keep the current situation where the "fencing weapons" category is essentially just the old 'list every weapon for the style individually' system?

**Comment by fairyarmadillo** [comment]
Are we talking about early modern sabre fencing though? All of our current fencing stuff - the Competitive Fencer profession, the Fencing hobby, the fencing gear, and the description of the martial art itself (referencing _flexible swords_) points to present day sport fencing being repurposed for zombie killing. The swords used in the sport of fencing in the present day are all straight-bladed and controlled with the wrist. I do know a fair bit about 18th century swordfighting, but it's simply not relevant if what the game calls fencing is the 21st century sport as described here: [https://en.wikipedia.org/wiki/Fencing](https://en.wikipedia.org/wiki/Fencing)

Are there other things called fencing? Yes. People call all manner of sword-based martial arts fencing. It's not uncommon to hear it applied to katana techniques or any number of other things, but a decision has to be made about what kind we're talking about here in Cataclysm and it seems to me like the decision has already pretty extensively been made.

I have been using HEMA to refer to Medieval Swordfighting, which comes in a book called Historical European Swordfighting, which is described as a present-day manual of pan-medieval European sword techniques. HEMA in real life is a trademarked brand and does not allow their name to be used without permission, so the book was given a generic sound-alike name, or so I assume.

Given the extensive evidence for fencing in Cataclysm to be taken as the kind of 21st century sport fencing that suburban New Englanders might get up to, the fencing weapons category should refer to weapons appropriate to this style of sport/combat. you make a fair case that Medieval Swordsmanship might not be an appropriate place for Early Modern sword techniques, but that sounds like a case where we'd either need a different martial art, or we'd need to clarify that fencing in Cataclysm refers to a broader spectrum of dueling styles. This being New England, it might be fun to add a colonial era re-enactment style that includes half-pikes (spontoons?) and bayonets, but I don't know whether any revolutionary war re-enactors go farther than basic drills, or whether any of it would reasonably be in print.

You also make a good case for the monoblade, but it becomes hard to differentiate it from bionic claws if treated it as a pata. Maybe it ought to be reskinned into a different sort of weapon, or switched to piercing?

**Pull request closed without merging**
