### PR TITLE
Make item::item_vars private

### LINKED ISSUE #10727: Crafting results in incorrect quantity
Craft a batch of, say, 5 nachos. The result will be a single nacho rather than a stack of 15.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7455953-crafting-results-in-incorrect-quantity?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Add getter / setter functions to access it. They automatically handle numeric data (this removes all the `ostringstream` / `istringstream` / `string_format` / `atoi` / ...) that very spread across different files.
Add nice documentation.

Fixes #10727 with  3e1cd19 (can be applied separately if desired) - my fault, my apology, my fix.

### CODE REVIEW

**Comment by KA101** [comment]
Interesting: my starting plastic bottle of clean water and a (otherwise functionally identical) plastic bottle of clean water that I created via debugging in a plastic bottle, then boiling water to it*, don't seem to stack.  Not sure why, and I don't think it a dealbreaker, but thought it was worth mentioning.

*Testing http://smf.cataclysmdda.com/index.php?topic=9128.msg207723#msg207723 .

**Comment by KA101** [comment]
Weird thing I thought was related to this, but isn't (still in master, I just checked): the porta-kiln for charcoal doesn't count down its charge counter, but still processes and can be harvested after a while.

**Comment by BevapDin** [comment]
> stacking issue

Found the bug, and if you weren't to fast with merging I could have add the fix here. Now I have to create a new PR.

> kiln

It should not have charges at all. It uses the same system (based on the item birthday) as the yeast flask. Will fix that, too.

**Comment by KA101** [comment]
???

Your PR, as merged, fixed at least two other bugs that were causing much more serious problems (weightless water, weird negative charges, stuff that breaks DDA logistics) than a cluttered, weirdly stacking inventory.  This was good work, and you're just gonna have to live with that fact.

**Comment by BevapDin** [comment]
You probably missed the invisible irony tags, my fault. Adding two commits to an existing branch is easy, creating a new branch, creating a new PR conflicts with my infinite laziness (-:

**Pull request merged**
