### PR TITLE
Ask to ignore repeating distractions when performing an activity

### PR DESCRIPTION
**Pull request by DarkDaskin**
We have two types of dialogs to ask whether to cancel an activity. The first one is a simple yes/no query, the second one also allows to ignore further distractions. The latter is only used when the player hears a noise. But there are other kinds of repeating distractions which cause the activity cancel dialog to show, so you might need to repeatedly select "no" to finish. This is especially annoying when you need to perform an action in combat, this dialog keeps immediately reappearing when you dismiss it.

This PR replaces the yes/no dialog with the one which has the ignore option for most situations. You can separately ignore the following types of distractions:

- noise
- pain
- being attacked
- spotting a hostile monster/NPC
- being talked to by NPC
- asthma attack
- motion alarm bionic
- weather change

I left the old dialog for deadly tired condition since it is not expected to become tired more than once during an activity.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I am not sure about `being attacked` - it is possible to be attacked to death if you `[i]gnore` accidentally.

Maybe we should display additional before ignoring possibly lethal ignore action?

**Comment by DarkDaskin** [comment]
Even if you ignore being attacked accidentally, you will be additionally prompted for feeling pain when you will receive actual damage. And in many cases ignoring is safe if the attacking creature isn't particularly strong and you are doing something quick like reloading your weapon - in this case you will only be prompted once.

**Comment by WizardOfOoo** [comment]
Make "ignore" require a capital "I" to activate. Just like some yes/no dialogs.  Solves the "accidental" problem.

**Comment by DarkDaskin** [comment]
"Require capital Y/N" option affects "I" as well.

**Pull request merged**
