### PR TITLE
Add vehicle direction indicator in tiles mode.

### LINKED ISSUE #13269: Draw vehicle facing indicator in Tiles mode,
In curses mode, the option VEHICLE_DIR_INDICATOR controls drawing a cursor (an 'X') in front of the currently driven vehicle, but this feature was not implemented in tiles mode.
The method that controlls it is game::draw_veh_dir_indicator() called from game::draw_ter().
The tiles equivalent would most likely be called from cata_tiles::draw().

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25729516-draw-vehicle-facing-indicator-in-tiles-mode?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #13269

### CODE REVIEW

**Comment by chaosvolt** [comment]
Yay. o3o

**Comment by BevapDin** [comment]
@chaosvolt Yes, that's it.

@kevingranade Any reasons why the logic to check for options and valid vehicle is duplicated? It could go into `get_veh_dir_indicator_location`, it could return `tripoint_min` or `g->u.pos()` when no pointer should be drawn.

**Comment by drbig** [comment]
I concur with BevapDin on having the logic checks in one place only.

**Comment by chaosvolt** [comment]
Curses, merge conflicts.

**Comment by kevingranade** [comment]
Yea that's superior, will do.

**Comment by kevingranade** [comment]
@chaosvolt That was one question I had, as a tileset author would you rather it be the same as the look around and aming cursor, or different?

**Comment by chaosvolt** [comment]
Sprite-wise I could just use the look/aim cursor, or add a separate sprite that's the same in a different color.

I'm guessing that getting the game to cite the tile_config entity for aim/look would be easier? That seems fine, yes.

**Comment by kevingranade** [comment]
Implemented @BevapDin's suggestion, and leaving it using "cursor" for now.

**Comment by chaosvolt** [comment]
That should work quite well, yes. For me at least, hopefully other active tileset authors are fine with it that way.

However it works out, at least it'll be well-timed if that changes, since I'm steadily working on another tileset update. I should probably be a bit more quick about it though, since accounting for a terrain item I added recently is on my to-do list. XP

**Pull request merged**
