### PR TITLE
[CR] Context-dependent skills and more descriptive unmet requirements

### PR DESCRIPTION
**Pull request by codemime**
### Rationale
- We have a special case `weapon` skill. It's treated separately from other skills and every possible occurrence of it starts with the condition: `skill == "weapon" ?` or `!skill.is_valid()` (means that it's `weapon`). There are cons:
  - This makes the code quite fragile, it cannot be maintained easily since these occurrences are scattered
  - `weapon` is an invalid skill (in terms of identifiers)
  - `weapon` skill is not applicable to melee weapons (inconsistency)
  - Adding new context-dependent skills is hard (like, for example, `repair` which can be `tailoring` for items made of cloth, `electronics` or `mechanics` e.t.c)
- Only the first unmet condition of an item is printed (the rest remains concealed until you meet the first one)
### Observable behavior

Before (only the first unmet skill is listed):

before

After (both unmet skills are listed along with the context):

after
### Implementation details
- Add context-dependent skills. List them (there's only one for now) in `skills.json` along with other skills
- Make `item` class responsible for providing context (can be replaced with a dedicated class if we need more flexibility in the future)
- Prevent illegal usage of context-dependent skills (like assigning them to `Character` or getting without a context)
- Separate fast silent checks from those that print messages (no need to mess with strings that nobody sees, no need to pass a boolean flag)
- Enumerate all unmet requirements in one function that returns `string` (conveniently reusable)
- Make unmet stats translatable (they weren't)
- Pull `can_use()` down to `Character` class and make it print customized messages. This allows NPCs to use it directly
- Replaced `string` ids with `skill_id` in `item::min_skills`
- Remove unused flag `gun_type` from `skills.json`
- Remove unused function `Skill::random_skill_with_tag()`.

### CODE REVIEW

**Comment by mugling** [comment]
Prevents compilation of unit tests?

**Comment by codemime** [comment]
Tried just now. Everything compiles fine (both gcc and Clang). What error message go you get and with what config?

**Comment by mugling** [comment]
`cataclysm/tests/savegame_test.cpp:181: undefined reference to `Character::get_skill_level(string_id<Skill> const&) const'`

**Comment by codemime** [comment]
Clear your build and try again. Your linker uses an old `obj` for some reason.

**Comment by mugling** [comment]
Will try

**Pull request merged**
