### PR TITLE
Fix liquid temperature for map liquid sources

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary
```SUMMARY: Bugfixes "Fix temperature for liquids that come from the map"```

#### Purpose of change

Fixes: #28779

When liquids from map source (such as rivers) were put into a big container the container would get very wrong temperature. Around 5-30 K for big containers.

#### Describe the solution

The bug happens due to something like this:

1) Player starts to fill 60l tank.
2) 4 liters of water with -0.4 energy is added in it (energy comes from the default value).
The contents get processed. Since the energy is negative the liquid temperature is set to enviroment temperature. Everything is good.
3) Another 4l of liquid with -0.4 energy is added in the container.
The new 4l is mixed with the already added 4l.
The energy of the liquids are summed.
The result is completely wrong energy.
The temperature of the result liquid is calculated from this wrong energy.
4) Repeat step 3 until container is full.

The solution is to set the liquid temperature before the mixing even begins.

#### Describe alternatives you've considered
The temperature could be set after the mixing begins. Then the enviroment temperature would need to be found from the liquid (or the container since the added liquid may not even really exist in a position anywhere). But the map position is easily available in this place so I put the temperature set there.

#### Additional context

I also added a debug message. If message "Poured item has no defined temperature" appears then this fix needs to be applied in other places too.

### CODE REVIEW

**Comment by Hirmuolio** [comment]
Removed the sap fix since I couldn't get sap collecting to work at all.

This should be ready now.

**Comment by Crunchepillar** [comment]
Pouring concentrated acid throws that debug message you added in.

image

**Comment by Crunchepillar** [comment]
Milking cows into an existing container of milk has no temperature.
Version 0.D-915-gfd09969 (tiles)

Is this the right place to keep telling you when I find liquids that don't have temps?

**Comment by ZhilkinSerg** [comment]
> Is this the right place to keep telling you when I find liquids that don't have temps?

You better [open a bug issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/new?template=bug_report.md) an report all your findings there.

**Pull request merged**
