### PR TITLE
Allow gunmods to consume less (or no) volume when installed

### PR DESCRIPTION
**Pull request by mugling**
Continues from #15153 and adds the `integral_volume` property which if unspecified defaults to `volume`. This new property is used in place of `volume` when the item is considered to be integrated with a parent item (for example a gunmod installed inside a gun).

This allows for example a gunmod to consume differing space when in the inventory vs when installed. For example the `5.7mm caliber conversion kit` now consumes `volume 1` when carried in the inventory but adds no extra volume when installed in a gun.

A separate PR is going to cover making installing gunmods more time consuming and/or with a chance of failure without the correct tools and adequate skills. @Rivet-the-Zombie I suspect you're likely to have an opinion as to the latter.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This is very nice! I foresee a lot of updates and improvements to be made to gunmods in the wake of this PR.

>A separate PR is going to cover making installing gunmods more time consuming and/or with a chance of failure without the correct tools and adequate skills.

I like the sound of this in particular.

**Comment by DeadLeaves** [comment]
Will this allow a gunmod to also reduce the volume of a weapon? That would allow for new / reworked mods

**Comment by mugling** [comment]
I'm going to implement `integral_weight` also but this will only ever (by design) reduce the weight of the mod when integrated

**Comment by mugling** [comment]
Rebased against master

**Comment by Coolthulhu** [comment]
Semi-minor problem:
Installed conversion kit can be removed at any time with no problems and yet it takes no volume. Where did the parts go? Maybe it should produce spare parts required to remove the conversion kit?

**Comment by mugling** [comment]
My intention is to make at least the `bore` conversion mods permanent. At a later date it might however be interesting to give the player the inverse conversion kit back in return.

**Comment by kevingranade** [comment]
Or just return metal scrap if you don't want it producing a "kit".

**Comment by mugling** [comment]
> Or just return metal scrap if you don't want it producing a "kit".

I'll probably include that in #15177

**Pull request merged**
