### PR TITLE
Fix generic factory aliases

### LINKED ISSUE #19170: Gate winches are broken

### PR DESCRIPTION
**Pull request by codemime**
Fixes #19170.

### CODE REVIEW

**Comment by illi-kun** [comment]
@codemime do you have a save file for easier testing this?

**Comment by codemime** [comment]
@illi-kun Here you go. [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/573814/save.zip).

**Comment by illi-kun** [comment]
Thank you for save and fix, it works properly.

**Comment by codemime** [comment]
@illi-kun You're welcome.

**Pull request merged**
