### PR TITLE
Beginnings of Hygiene

### PR DESCRIPTION
**Pull request by MichaelMacha**
#### Summary
SUMMARY: Infrastructure

#### Purpose of change
There's a lot of talk about managing scent in a more complex way. I feel that a glaring absence in the CDDA game has been the usage of hygiene products, like deodorant and toothpaste. I know that a lot of people are considering the addition of scent management and there are probably some good stealth ideas out there, so let's get them on the table.

#### Describe the solution

Toothbrushes are now usable, as is spray-can deodorant; but they're under the added "reduce_odor" item effect, which does not (yet) have a basis in the code. I imagine that it will temporarily reduce ambient smell by a set amount. That still needs to be done before this is really ready to be pulled.

#### Describe alternatives you've considered

Cosmetically, we should be able to find and use toothpaste and deodorant. We all (hopefully) have sticks, cans, and tubes of it in our bathrooms right now; they should be lying around after the cataclysm.

As to the effect on scent, I'm up for suggestions. I think there's a lot to consider with olfactory mechanics, as a man in an airtight bodysuit or wet suit should also be scentless. (Unless it's a stinky wet suit, but that's a different kind of smell.) Additionally, one would imagine that zombie dogs would have an enhanced sense of smell compared to zombie humans.

I've been working on some what-I-do-for-money projects lately and am not yet that familiar with the C++; but it looks very simple. I'm hoping to dig through it on Wednesday or Thursday, maybe get a basic implementation of reduce_odor going.

#### Testing

I've implemented the JSON in 11574 and it's worked fine, aside from the lack of C++ support.

#### Additional context

I chose "reduce_odor" for a reason. If we're implementing aerosols, it also makes perfect sense to have repellents, or ambient effects, down the line; and when we get to that, it should be easy enough to add an "increase_odor" or some evolution of that afterward. Maybe perfumes to increase social skill for a time, that sort of thing.

If smell is going to be expanded on, we need to give up on the whole "magical zombie super-senses" thing. It's good to start with the basics because it's only going to get more complex from here.

### CODE REVIEW

**Comment by actual-nh** [comment]
I doubt toothpaste will do anything to what zombies will react to - more likely a combination of social effects with eventual health effects. Long-term, this will also relate to the perspiration implementation; if retention of perspiration is avoided (via weather, moisture-wicking clothing, or whatever), shampoo works as a substitute for deodorant.

**Comment by Zeropol** [comment]
I love the idea ! Swimming in a river could also help with hygiene, while deodorant have nothing to do with hygiene, only odor.

**Comment by Ramza13** [comment]
So are you planning to do the C++ for this or are you hoping to get some help for that part?  Either way once #48360 is merged, it should be pretty simple to add a mod_scent dialog function and then add your item via the dialog system.  Which then lets other things affect scent.  

If you decide to follow my suggestion I don't mind creating the dialog function to handle this when this is closer to being ready.  Or if you want, it should be relatively simple to add.  Either way feel free to ask me any questions you might have.

Good luck!

**Comment by Venera3** [comment]
First off, I'm very happy somebody tackles scent. That's a system that feels very barebones in execution, and there's a lot of parts that seem unfinished (scent types, for example). That said

- I'm pretty skeptical about toothpaste affecting your odor in a way that influences scent tracking. If the zombies can smell your breath they should be able to either smell your everything or more likely already see you.
- Unless we're talking 100% odorless antiperspirants changing your smell to Choco Charm or whatever Spade's most popular scent was before the Cataclysm would probably do a bad job at avoiding zombies - they already investigate novel stimuli like sound so a scent that stands out from a dead city could invite more attention than it prevents.
- There are monsters changing your scent should work on, of course, and there's already infrastructure to defining tracked and ignored scents though I don't know how well they work in practice.
- Bodysuits masking your own scent provided 100% coverage could be an interesting niche, especially if them getting *damaged* would interfere with their ability to keep the stank in. This ties into perspiration, but a perforated bodysuit should expose the ungodly stench a survivor doing heavy exercise for hours on end would produce in a full-body PPE.
- I could very much see such rituals working as a hefty "nostalgic" morale boost and influencing your rapport with the more civilized survivors.

**Comment by actual-nh** [comment]
> * I'm pretty skeptical about toothpaste affecting your odor in a way that influences scent tracking. If the zombies can smell your breath they should be able to either smell your everything or more likely already see you.

Agreed.

> * Unless we're talking 100% odorless antiperspirants changing your smell to Choco Charm or whatever Spade's most popular scent was before the Cataclysm would probably do a bad job at avoiding zombies - they already investigate novel stimuli like sound so a scent that stands out from a dead city could invite more attention than it prevents.

Smelling enough like, say, charcoal should work... at least for the zombies; whether or not anyone else would care for it is another matter.

**Comment by kevingranade** [comment]
I'm not super hyped about toothpaste and deodorant being about scent masking, they're both tuned for human olfactory senses and processing (sensitivity aside, a hunting animal like a dog does whole levels of processing that a human does not, so deodorant isn't going to impact them the same way, or potentially at all).

There are several issues conflated here, let's see about teasing them apart.
1. Doing *something* about scent (for the player).
My understanding is that when you're talking about an animal tracking by scent, they're not just or even primarily following a literal cloud of scent their target emits (even though that's how the game models it, that needs fixing too), instead they are following scent emitted by traces the target leaves behind, such as skin cells and hair on the ground.  This is why dogs following a trail often have their nose to the ground, that's where those traces are.  As such you either need to avoid leaving those traces (such as by wearing a cleansuit or similar) or eliminate the source of the volatile compounds emitted by those traces, which AFAICT means eradicating your skin biota, which is not a GREAT idea... Even if you're talking about immersion in water, the *instant* you aren't completely soaked you're going to start dropping skin flakes again and leaving a trail, and as soon as those skin flakes dry out enough they're going to start emanating volatile compounds that you can be tracked by. If there are sources indicating that there are chemical means of suppressing scent *that work on scent tracking animals* feel free to share them, but I haven't run across anything like that and it seems unlikely.
2. *fixing* scent (in the game)
As I mentioned in the earlier section, we treat scent as a cloud emanating from the player, this is only part of the picture, and the way we model it especially as diffusion based is completely wrong.  The scent traces a player leaves would be dominated by the path they walked to reach somewhere, tracking animals would mostly be following this trail.  In an enclosed area with NO wind, the player might develop a "cloud* of scent around themselves as well, but more likely there would be some air movement, which is going to completely dominate diffusion and pull the player scent into a "plume" that streams off the edge of the map every turn.  The good news is this is actually faster to calculate than the current scent map and lets us do tings like have multiple different types of scent on the map, the bad news is it's more *complicated*.
Another area we might want to change is zombie scent abilities, right now all zombies have "regular" scent tracking abilities and some have "good" sent tracking ability.  Arguably, if a zombie is "mostly a human but really pissed off", it shouldn't have *any* meaningful scent tracking ability, and that's something that would surface later in the game with evolutions (or with zombie dogs).
3. Tooth brushing and deodorant
These don't IMO meaningfully intersect with scent tracking.  They could be a thing, but *should* not appear except as "a thing you do automatically once you have the appropriate items".  In the case of dental hygiene, there are long term health implications such that ignoring it indefinitely is a Bad Idea :tm:, but it also shouldn't be a *chore* for the player.  Deodorant on the other hand only has implications for morale and maybe NPC interaction, but honestly I don't see it being particularly important. The whole concept of deodorant is a manufactured issue, if you don't use it, you don't really notice it.  There could be a trait reflecting a character's inability to let go of that aspect of civilization, but it seems pretty far to go for such a minor effect.  The deodorant item itself though, could be a valuable source of chemicals.

**Comment by actual-nh** [comment]
> I'm not super hyped about toothpaste and deodorant being about scent masking, they're both tuned for human olfactory senses and processing (sensitivity aside, a hunting animal like a dog does whole levels of processing that a human does not, so deodorant isn't going to impact them the same way, or potentially at all).
> 
> There are several issues conflated here, let's see about teasing them apart.
> 
> 1. Doing _something_ about scent (for the player).
>    My understanding is that when you're talking about an animal tracking by scent, they're not just or even primarily following a literal cloud of scent their target emits (even though that's how the game models it, that needs fixing too), instead they are following scent emitted by traces the target leaves behind, such as skin cells and hair on the ground.  This is why dogs following a trail often have their nose to the ground, that's where those traces are.  As such you either need to avoid leaving those traces (such as by wearing a cleansuit or similar) or eliminate the source of the volatile compounds emitted by those traces, which AFAICT means eradicating your skin biota, which is not a GREAT idea... Even if you're talking about immersion in water, the _instant_ you aren't completely soaked you're going to start dropping skin flakes again and leaving a trail, and as soon as those skin flakes dry out enough they're going to start emanating volatile compounds that you can be tracked by. If there are sources indicating that there are chemical means of suppressing scent _that work on scent tracking animals_ feel free to share them, but I haven't run across anything like that and it seems unlikely.

Wouldn't this vary by recency? For longer-term/range scent tracking, yes, you'd be needing to pick up more subtle scents like what you're talking about. Following a more-current - and closer - scent cloud can be different. (For instance, AFAIK mosquitoes aren't interested in tracking where a particular person/animal has traveled - they're interested in locating the nearest cloud of carbon dioxide that they might be able to feed from.)

**Comment by MichaelMacha** [comment]
I figured this would be the kind of thing we'd have to mull over as a group. @kevingranade made some excellent points about zombie tracking; if they're closer to, say, a dog's sense of smell then humans barely even have an allegory for it. (Imagine being able to pick apart a smell with the same precision that you can a picture, and you've got a dog nose. We can barely relate to that.) Moreover, The Blob™ has been radically altering zombie phenomes in a lot of fun/terrifying ways already. I wasn't entirely sure how that worked.

I feel that the absolute absence of toothpaste in the game is a glaring hole. I don't think people would just _stop brushing their teeth_ after an apocalyptic event, though; maybe only for a little while; and I would be perfectly happy to start small, such as with a very mild morale boost. I mean come on, you can feel bad breath and aching teeth.

I also think it would be really funny if toothpaste was weaponizable in My Sweet Cataclysm. Maybe some kind of cinna-fresh mouthwash bomb.

I didn't know about 48360, and it makes it sound as though the more advanced things we're discussing could stand to wait. I don't have an enormous amount of time lately, and I'm usually burnt out on programming after working through a section of the book I'm writing; but like I said, the C++ is quite reasonable.

There are such things as targeted scent-eliminating cleansers which have been shown to work on dogs, but they're a lot more sophisticated than just soap. I could see us encountering them in labs, maybe. There's also military clothing designed to reduce scent by being laced with activated charcoal. Additionally, how thorough is wind direction mapping in the game? Does it consider the environment at all? I agree that it isn't everything, but staying downwind of prey is hunting 101.

For reference, consider this and note that it's targeted at hunters.
https://www.amazon.com/gp/bestsellers/sporting-goods/3413671

It's difficult to find the activated charcoal clothing, but the fabric has become popular recently in face masks. Interestingly, it also appears to be available in a powder for applying to regular clothing. Only some of this is applicable, but it gives you the idea.
https://www.amazon.com/s?k=activated+charcoal+cloth

Where chemicals go, modern deodorants tend to be a combination of alcohols, sodium chloride, sodium stearate or some form of  soap, and stearyl alcohol (a saturated fatty alcohol which in most cases is in the form of solid granules). They used to have all kinds of other juicy cancer-causing stuff in them like formaldehyde, zinc oxide, and ammonium chloride, but the buzz-kill FDA put a stop to that.

Toothpastes can vary, but pretty consistently are in a base of glycerol. Fluoride's a big ingredient, but you'll also find sodium lauryl sulfate (a foaming agent in just about everything), sorbitol (which is a reduced form of sugar), and calcium carbonate. Of course, you would have to spin it apart or something to separate it, I'm not entirely sure how it would be done. Something for the chemistry guys.

As to why the military would bother with scent-reducing clothing, I remember reading the biography of Richard Marcinko (SEAL captain) when I was a kid. From Vietnam, he had stories about how every time someone started smelling potent Pho or some kind of a curry they knew the Viet Cong were close. Apparently in jungle warfare, keeping your scent low is amazingly important for keeping your head. Don't get me wrong, Marcinko seems crazier than a rabid pig; but like most rabid pigs he knows his shit.

I have to admit that what I'm most concerned about is a visual aid for this. No one really thinks about the role that scent plays in zombies finding them. I'm not sure how to approach that. If it changes the game, and no one notices at all, then one has to wonder how much of a difference it's actually made.

**Comment by Shodan14** [comment]
> Wouldn't this vary by recency? For longer-term/range scent tracking, yes, you'd be needing to pick up more subtle scents like what you're talking about. Following a more-current - and closer - scent cloud can be different. (For instance, AFAIK mosquitoes aren't interested in tracking where a particular person/animal has traveled - they're interested in locating the nearest cloud of carbon dioxide that they might be able to feed from.)

I like he mosquito analogy for this. There's obviously the bloodhound scent tracking angle to consider as well, but if you have been running around for days without washing you're going to be detectable to normal humans from a few meters away at least, and much longer if you slept in once place etc. Consider a foul smelling person on a bus/metro, I'm sure most have experienced that.

**Comment by kevingranade** [comment]
> Wouldn't this vary by recency? For longer-term/range scent tracking, yes, you'd be needing to pick up more subtle scents like what you're talking about. Following a more-current - and closer - scent cloud can be different. (For instance, AFAIK mosquitoes aren't interested in tracking where a particular person/animal has traveled - they're interested in locating the nearest cloud of carbon dioxide that they might be able to feed from.)

That's absolutely the case of course, if you're modeling a mosquito, their primary mechanism is CO2 tracking, which is going to be a plume moving downwind and nothing else.  Also there's not much you can do about it.  Likewise at close range dog-like scent tracking is going to detect body odor in a plume as well, but the longer-range mechanism is trace-oriented.

> Another factor is the possibility of covering one scent with another one with a lot of other sources - charcoal/ashes, for instance.

Source please, when I last looked into this covering up scents was deemed ineffective (again for dog-type scent tracking), if you have a source that says otherwise I'd love to read it.

> Further evolutions enhancing this seems likely. Note that it might well actually start with using human olfactory capacities, just being hyper-aware of everything (not being distracted by thinking...) - meaning scent masking (antiperspirants, etc) could initially have some effectiveness, but as they evolved further, they'd get less and less human-like in this ability.

That's a good point, I was thinking of human-like scent ability as being too useless to model, but at relatively close range, or especially if the scent level is much higher than what we're used to, it could provide a bit of detection ability, but that would be easier to fool than dog-like scent tracking ability.

> I feel that the absolute absence of toothpaste in the game is a glaring hole. I don't think people would just stop brushing their teeth after an apocalyptic event, though; maybe only for a little while; and I would be perfectly happy to start small, such as with a very mild morale boost. I mean come on, you can feel bad breath and aching teeth.

It's 100% fine for the item to exist, that would be a great addition all by itself, and a minor morale bonus is in line with food consumption and totally fine to add.  It's long-term health impacts or large morale or social impacts that I'm more leery of because it could become a de-facto requirement to perform this chore.

**Comment by actual-nh** [comment]
How is a cybermoose related to hygiene?

**Comment by MichaelMacha** [comment]
Oh, it's not; I had to break away from this for work stuff before I could
come back to it and clean it up.  Sorry about the confusion there; it's two
changes at the same time.

Yeah, I know; I'll be sane again in a few months once my animation work
dies down a bit.

I totally get it if someone wants to cleave it in two; I still need to
comprehend the C++ enough to add dental hygiene as it stands and it looks
like it's going to be a bit.

Also, while I feel that cleanliness in general should have more of an
impact in the game, dental hygiene specifically seemed a lot more exciting
at the time... I'm thinking that something more general, like a defense
against infections or illness, would be better.

**Comment by I-am-Erk** [comment]
I'm closing this for now. this is a change we want, but complex, and I think this Pr will need a fair bit of work to get it in line. That doesn't mean you should never return to it of course! Let us know if you're back around to take another stab.

**Pull request closed without merging**
