### PR TITLE
Evac shelters mapgen tweaks

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Evac shelters mapgen tweaks."```

#### Purpose of change
Evac shelters with doors to all sides of the world look a bit silly to me. The same for necessity to walk from road through the dirt or grass to enter the building. So I decided to slightly tweak shelters' mapgen.

#### Describe the solution
- Evac shelters will now have only one double doors leading to the north side. Other doors have been removed;
- Shelters will now have a guaranteed road connection leading to their north side;
- Shelters will now have a small parking next to the entry;
- Also I fixed a small oversight in item spawn locations for `evac_shelter_2` roof which sometimes could spawn items in the air.

### CODE REVIEW

**Comment by Inglonias** [comment]
The gameplay purpose of the doors leading out in all directions is small, but worth mentioning. If there's something that would immediately kill you just outside (a tank, chicken walker, or zombie hulk), you can evacuate through another door.

I feel like a fire exit of some sort (Just a back door, really) would be an appropriate compromise in that regard.

**Comment by Amoebka** [comment]
Well, you can just as easily evacuate through one of the windows?

**Comment by Inglonias** [comment]
> Well, you can just as easily evacuate through one of the windows?

You can, but I'm pretty sure the fire code inspector would have words with the architect who decided that was good enough.

**Comment by Night-Pryanik** [comment]
Ok, I'll add a single back door.

**Pull request merged**
