### PR TITLE
Military Vehicle Group and Source Changes

### PR DESCRIPTION
**Pull request by chaosvolt**
I'm always leery of messing with the source, so I'm hoping I don't screw
up.
1. Added a vehicle group for military vehicles. Cargo truck
   predominates, with other existing vehicles increasingly rare.
2. Source tweaks in only two places. The parking lot result that spawns
   a cargo truck, and the turret result for military checkpoints.

I am assuming that the chicken walker and tank drone are much bulkier
than a pair or turrets and need a cargo truck to haul them, so those
spawn results are unchanged. I am likewise leaving the truck spawning in
the hazardous waste sarcophagus unchanged.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, I knew I'd mess something up. :V

**Comment by chaosvolt** [comment]
Ah...hah...scheisse squared.

**Comment by chaosvolt** [comment]
Meh. For now it seems at least mapgen.cpp can be messed with.

**Comment by KiwiTrinsic** [comment]
From a quick glance, I'm guessing that the problem is that the veh_type variable is of vproto_id, while you are trying to assign a vgroup_id to it. That won't work. vgroup_id can handle individual vehicle types as well as groups, but vproto_id can only handle individual vehicle types. The map's add_vehicle function can accept either a vproto_id or a v_group_id without problem, which is why the changes in mapgen.cpp work.

You should be able to get the mapgen_functions.cpp change to work if you change veh_type from vproto_id to vgroup_id. Doing that you will need to change all the assigns to veh_type to vgroup_id. Example: vproto_id("bubble_car") needs to become vgroup_id("bubble_car")

**Comment by chaosvolt** [comment]
Ah, I see. The error that kept showing up was "candidate function (the implicit copy assignment operator) not viable: no known conversion from 'string_id<VehicleGroup>' to 'const string_id<vehicle_prototype>' for 1st argument" if that helps any.

**Comment by narc0tiq** [comment]
Right, and `string_id<VehicleGroup>`

**Comment by chaosvolt** [comment]
Hmm, I see. I could've sworn mapgen.cpp used both vproto_id and vgroup_id though.

**Comment by KiwiTrinsic** [comment]
Yes, the map add_vehicle function can handle either a vproto_id or a vgroup_id. You still cannot assign a vgroup_id value to a vproto_id variable ;)

**Comment by chaosvolt** [comment]
Hmm. So what I need to do is figure out how to change the add_vehicle function as defined in mapgen_functions.cpp and get it to take vgroup_id instead? Still unsure. :V

**Comment by KiwiTrinsic** [comment]
The way mapgen_functions.cpp is working right now is that it creates a variable veh_type of vproto_id. Then it will put the value into that variable. That is the part where you see veh_type = vproto_id( "military_cargo_truck" ), veh_type = vproto_id( "bubble_car" ), and so on. Because veh_type is a vproto_id variable, it can only be assigned a vproto_id value. 

If you change veh_type to be a vgroup_id variable, you will then be able to assign it a vgroup_id value. This means that all the vproto_id values will have to be changed to vgroup_ids or you will have the same problem you are having now, except in reverse (trying to put a vproto_id value into a vgroup_id variable.)

**Comment by narc0tiq** [comment]
...no. Your variable named `veh_type` from the line that reads `veh_type = vgroup_id( "military_vehicles" );` has been declared as `const vproto_id veh_type` or similar. You're trying to put a `vgroup_id` in it. It's right there in the report from Jenkins at <http://ci.narc.ro/job/Cataclysm-Jently/29392//consoleText>. It's no longer there in the latest commit, suggesting you did something to fix it. Most likely this part of the diff: <https://github.com/chaosvolt/Cataclysm-DDA/commit/4a01afe2ff808e5f70475a684d001d7c9dd339e1#diff-59604ea2f6e3da1d8c5be9188964f1c9R1794>.

**Comment by narc0tiq** [comment]
Also, is the pull request builder busted again?

**Comment by chaosvolt** [comment]
Hmm. I undid my changes to mapgen_functions is why it isn't there, because it was breaking. But does it at least function correctly in mapgen.cpp?

If it's instead trying to spawn a VEHICLE named "military_vehicles" I'm going to be several different kinds of annoyed. ;-;

**Comment by chaosvolt** [comment]
Also also, yeah it looks like something broke on the pull request builder, as update 4 hasn't been checked. O.o

**Comment by narc0tiq** [comment]
Oh, no, I see what's going on now -- that "Update 4" is actually a reference:

> **chaosvolt** referenced this pull request from a commit in chaosvolt/Cataclysm-DDA

Incidentally, it would be really nice if your commit titles were more informative. "Update 4" doesn't tell me anything, and if I'm looking at abbreviated `git log` output, the one line is all I have. Maybe you're not making enough commits if you feel the only possible short titles would be "Here's another update".

**Comment by KiwiTrinsic** [comment]
Everything looks fine to me in the mapgen.cpp code. It is calling directly to the add_vehicle function with the vgroup_id instead of using a variable so it won't have the same problems you are having in mapgen_functions.cpp.

**Comment by chaosvolt** [comment]
> Incidentally, it would be really nice if your commit titles were more informative. "Update 4" doesn't tell me anything, and if I'm looking at abbreviated git log output, the one line is all I have. Maybe you're not making enough commits if you feel the only possible short titles would be "Here's another update".

Sorry about that. I usually list changes in the notes for it, but I probably should start titling commits with what I'm changing instead of numbering them. @_@

**Comment by chaosvolt** [comment]
In any case, hope the mergening goes well.

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Comment by chaosvolt** [comment]
Also @Coolthulhu if you know what I messed up in that initial commit, it would be nice to know. Was it a lack of additional includes like my guess was, what KiwiTrinsic guessed was the cause, or something else entirely?

**Comment by BevapDin** [comment]
> what I messed up in that initial commit, 

It's what KiwiTrinsic guessed was the cause. You're assigning to the variable `veh_type`, which is of type `vproto_id` (vehicle prototype id). But you assign a value of type `vgroup_id` (vehicle group id).

Those are both ids, but they are ids of different things. It would similarly fail if you try to assign a martial art style (`matype_id`) or a monster group id (`mongroup_id`).

You can try to spawn from the group there directly (call `m->add_vehicle( vgroup_id( ... ), ... )`, just like the final `add_vehicle` call at the end of the loop).

Besides the whole if-else block should be moved to JSON, I think the vehicle group system allows that now.

**Comment by chaosvolt** [comment]
Hmm, I see. No doubt if I tried to puzzle out how to get that to work, I would've broke it even harder. ;w;

**Comment by KiwiTrinsic** [comment]
@BevapDin Yeah, I've taken another look at the code and it is basically trying to hard code a vehicle group. I'll look into ripping the whole thing out and replacing it with a json vehicle group.

**Pull request merged**
