### PR TITLE
Balance livestock carrier weight

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: Balance "Balance livestock carrier weight"```

#### Purpose of change
The livestock carrier is almost 10kg heavier then its components:
image

Also, in this recipe pipes are used as an alternative to steel. It can be used like that but it makes more sense to use pipes and steel together (see solution).

The other recipe for livestock carrier is 1kg short
image

#### Describe the solution
I imagine the survivor putting 1 frame at the bottom and use the remaining 3 to cover each side and then uses the pipes to create bars at the front, using rope and scrap metal to combine the parts.
- Uses steel_standard as a component instead of an alternative to pipes
- Adjusted the amount of components to match the weight of the cargo carrier

The new calculation looks like this:
image

You lose 300g somewhere along the process

As for the other recipe:
- Added 1kg of steel_standard (to weld the pipes to the cargo carrier, i imagine).

New calculation:
image

#### Describe alternatives you've considered
Decrease the weight of the cargo carrier but I think the weight is good although I don't really have a reference.

#### Testing
first recipe:
image

Second recipe:
image

#### Additional context
The grapnel (grappling hook) throws the calculation off a bit.

### CODE REVIEW

**Comment by AMurkin** [comment]
Sidenote: you can do [tables with Markdown](https://guides.github.com/features/mastering-markdown/). To make information be searchable.

**Comment by snipercup** [comment]
Weight results for: | livestock_carrier |   |   |  
-- | -- | -- | -- | --
Components needed | Component weight in g | Component count | Total weight | Avg. weight
frame | 20000 g | 4 | 80000 | 80000
pipe | 1250 g | 11 | 13750 | 13750
rope_6rope_30rope_makeshift_6rope_makeshift_30vine_30grapnel | 6 g6 g6 g6 g6 g760 g | 5*41*45*41*41*41*4 | 1202412024243040 | 558
steel_lumpsteel_chunkscrap | 1000 g250 g50 g | 1*24*220*2 | 200020002000 | 2000
  |   |   | Total weight | 96306
  |   |   | Weight difference | -306

Oh, I thought it messed it up, at least it did so last time, thanks!

**Comment by AMurkin** [comment]
You can use `<br>` tag for the new line.

**Comment by snipercup** [comment]
What a pain. I'll have to think about how to make it easier. 

Also, please review/merge this PR.

**Pull request merged**
