### PR TITLE
Small QOL change to location sidebar window

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- decreased height of message log window and increased height of location window in sidebar by 1 line;
- moved weather and temperature data to second line of location window;
- moved moon phase and lighting data to third line of location window;
- increased visible part of current overmap terrain name to max width of location window in sidebar;
- slightly update layout.

# Screenshots:

### overground

image

### overground with thermometer

image

### underground

image

### undergroundwith thermometer

image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Can anyone remember me, what type of information do we have to the right of the temperature indicator, right to the `Chilly` text on the screenshot above, under the stamina indicator?

**Comment by DracoGriffin** [comment]
>Can anyone remind me, what type of information do we have to the right of the temperature indicator, right to the Chilly text on the screenshot above, under the stamina indicator?

As far as I know, nothing except for longer character temperature information but I could be wrong as I play in smaller windows.

temperaturestaminauitest

**Comment by Night-Pryanik** [comment]
Weather indicator will be the only text on the added line, or am I wrong?

**Comment by ZhilkinSerg** [comment]
> Weather indicator will be the only text on the added line, or am I wrong?

Correct. If player is underground `Underground` will be displayed and if player is overground weather name will be displayed.

```c++
    if (get_levz() < 0) {
        mvwprintz(w_location, 1, 18, c_light_gray, _("Underground"));
    } else {
        mvwprintz( w_location, 1, 18, weather_data( weather ).color, weather_data( weather ).name );
    }
```

**Comment by ZhilkinSerg** [comment]
> Then maybe unite moon indicator, weather indicator and lighting indicator on one line?

There is not enough width to place all three fields if weather name is too long:

image

But I can do the following:

### ground level

image

### ground level + thermometer

image

### underground

image

### underground + thermometer

image

**Comment by ZhilkinSerg** [comment]
# Widebar screenshots:

image

image

**Comment by Night-Pryanik** [comment]
Honestly I'd remove the moon indicator for good (anyone ever used it?), and if after that it would be possible, place weather, temperature and lighting indicators on one line.

**Comment by Night-Pryanik** [comment]
Cool. I like the latest changes.

**Comment by ZhilkinSerg** [comment]
We should implement some suggestions from #23906.

**Comment by Night-Pryanik** [comment]
> We should implement some suggestions from #23906.

Which ones? I reread the whole issue again, and I can't find not a single suggestion that will satisfy everyone, as they are too radical in my opinion.

I can suggest remove the `(Falling)` and `(Rising)` suffixes to the body temperature and replace them with `(^)`, `(^^)` and `(^^^)` for various degrees of rising and `(v)`, `(vv)` and `(vvv)`for falling. So it should look like `Comfortable (^)` or `Chilly (vv)`. This way we could save a little bit of free space on the line and probably place there some information from other line.

**Comment by ZhilkinSerg** [comment]
Nice suggestion about

**Pull request merged**
