### PR TITLE
Let Debug characters use the debug menu hassle-free

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Interface "Let Debug characters use the debug menu hassle-free"

#### Purpose of change

When I'm debugging I often see "Using this will disable achievements.  Proceed?". Although it's easy to dismiss, it's still annoying. And if I wanted to test something achievement-related, I'd have to go though the extra hassle of re-enabling achievements.

#### Describe the solution

Disable the debug menu nag message if the avatar or world name starts with one of these words: "Debug", "Test", "Sandbox", "Staging", "QA", "UAT".
Also remove the guilt-tripping message.

#### Testing

Start a new game with a character named "Debug McDebugface". Spawn a zombie nag-free.

image

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Let's include some additional magic words, like "Test", "Sandbox", "Staging", "QA" and "UAT" and check world names too.

**Comment by actual-nh** [comment]
Thanks very much! For keeping track of multiple debug characters, I had in mind allowing if any section of the name was "Debug" (probably case-sensitive).

**Comment by actual-nh** [comment]
> Let's include some additional magic words, like "Test", "Sandbox", "Staging", "QA" and "UAT" and check world names too.

As an alternative, or required as well?

**Comment by eltank** [comment]
> Let's include some additional magic words, like "Test", "Sandbox", "Staging", "QA" and "UAT" and check world names too.

This is done.

**Comment by eltank** [comment]
> Thanks very much! For keeping track of multiple debug characters (different traits, for instance), I had in mind allowing if any section of the name was "Debug" (probably case-sensitive).

Changed to support names that start with "Debug" etc. as a first word.

**Comment by actual-nh** [comment]
I might do a followup PR to put this into a function and also check it for whether to do the long message in `debug_menu_uilist`.

**Comment by eltank** [comment]
> I might do a followup PR to put this into a function and also check it for whether to do the long message in `debug_menu_uilist`.

I like that idea. Done.

**Comment by eltank** [comment]
One of the tests failed due to `invalid trait id "PARKOUR"`, which is unrelated to this PR. I wonder if anyone is working on fixing that, I might look into it.

**Pull request merged**
