### PR TITLE
More realistic contents of bots and turrets

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "More realistic contents of bots and turrets."```

#### Purpose of change
More plausible bots and turrets.
Most turrets were lacking targeting modules in them. All bots were lacking a mean to move themselves (i.e. no motors) at all.

#### Describe the solution
Added targeting modules to craft and uncraft recipes for turrets that were lacking them. Added robotic controls to craft and uncraft recipes for all turrets and bots.
Also tweaked recipe for turret control unit. Now it additionally requires identification module, and can use camera or camera pro or security camera or sensor module.

Also fixed a typo/bug in recipe when you could craft makeshift turret with 1 MP5, destroy the turret and get 2 MP5s from disassembling it.

#### Describe alternatives you've considered
Adding turret control units to turrets instead of set of various modules. But crafting TCU require laptop to configure them, so this change would require overhauling the way laptop works.

#### Testing
Loaded the game, no errors.

#### Additional context
With this change crafting TCUs should be much simpler, as all components you need to craft it you can get from disassembling any disabled or broken turret.

### CODE REVIEW

**Comment by cainiaowu** [comment]
Will that modular turret mod get some love to update it with new feature?

**Comment by Fris0uman** [comment]
I don't get why all robots would need robot controls:
`A set of servos, microcontrollers and other devices, together capable of driving an unmanned vehicle [...]`
It seem to be the same thing as "ai_core" but with the capacity to steer a vehicle on top. Is it that all robots were remote controlled?

**Comment by Night-Pryanik** [comment]
> Is it that all robots were remote controlled?

All bots have to move somehow, right? They are not remote controlled, but operating independently based on their programming instead. They use an AI module to decide what to do next, and then this module makes robotic controls execute its command.

**Comment by Fris0uman** [comment]
What I understand is that robot controll are basically meant to turn a steering wheel and operate a vehicle. Robots have arms/wheel/rotors/tread etc that already contains the motor/servo-motor and what-not to operate. I'm not sure we need to add robot control on top of that.
I think it make a bit more sense for turrets since they were supposed to be remote controlled before the cataclysm.

**Comment by Night-Pryanik** [comment]
> Robots have arms/wheel/rotors/tread etc that already contains the motor/servo-motor and what-not to operate. 

Yeah, I haven't thought on that. Will revert adding robot controls to robots.

**Comment by tenmillimaster** [comment]
The turrets probably don't need identification modules. They shoot at everything.

**Comment by Fris0uman** [comment]
Maybe add a `broken_identification_module`?

**Comment by tenmillimaster** [comment]
That's part of the idea, none of the ID's can be trusted since it'd look the same; it cannot tell the difference between humans and zombies. It shoots at everyone, friendly or hostile I.

**Comment by Night-Pryanik** [comment]
> The turrets probably don't need identification modules. They shoot at everything.

While they indeed shoot at everything, that's not because they don't have identification modules, but rather because they were programmed to fire at everything using their modules.

**Pull request merged**
