### PR TITLE
Mosin-Nagant EBRs, conversion stock, and recipes

### PR DESCRIPTION
**Pull request by KA101**
As stated, here's a conversion stock you can install your M-N into to get those delectable 0-dispersion noscope norecoil NO MERCY pre-Revolution Russian rifles back.

Spawns in separate commit.

### CODE REVIEW

**Comment by KA101** [comment]
Spawns:

EBRs:
rifles, 1
allguns, 1
lmoe_guns, 1
mansion_guns, 1

Kit:
gunxtras, 1
gunsmith_gunparts, 1
pawn, 1

**Comment by KA101** [comment]
Hey, @Darkyhard, I knew there were no JSON errors here because I made a new branch, made my changes, ran DDA with them, and actually converted a M44 to the EBR version.

That's the basic test for JSON PRs.
1) does the game load up when you hit Play Now!, or does the JSON parser throw an error?
2) does it do what it's supposed to do: in this case, use up some gunsmith-kit charges & three hours of game time, then change your rifle and give you back the stock it was using?

**Comment by Rivet-the-Zombie** [comment]
And when it comes time for us to test it for merge, we run those same tests again to be absolutely sure.

**Comment by Darkyhard** [comment]
Thanks. Looks like I've got the point.

**Pull request merged**
