### PR TITLE
Add a sprite for ferns to NeoDays (same as in RetroDays)

### PR DESCRIPTION
**Pull request by Tairesh**
#### Summary
Interface "Add a sprite for ferns to NeoDays (same as in RetroDays)"

#### Purpose of change
Sprite for RetroDays added in #48504 but not in NeoDays

#### Testing
fern
harvested fern

### CODE REVIEW

**Comment by Fris0uman** [comment]
PLease add it to the tileset repo first, oherwise it will be overwritten next time we update the tileset. https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/NeoDays

**Comment by Tairesh** [comment]
> PLease add it to the tileset repo first, oherwise it will be overwritten next time we update the tileset. https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/NeoDays

Thank you, I just figured out how it works and created a [pull request](https://github.com/I-am-Erk/CDDA-Tilesets/pull/603) to correct repository.

**Comment by Fris0uman** [comment]
Now that it's pushed and merged on the tileset repo you can get the composed version from there https://github.com/I-am-Erk/CDDA-Tilesets/actions/runs/802554885 by downloading the artefact, lint tile_config.json and put that into this PR

**Comment by Tairesh** [comment]
> Now that it's pushed and merged on the tileset repo you can get the composed version from there https://github.com/I-am-Erk/CDDA-Tilesets/actions/runs/802554885 by downloading the artefact, lint tile_config.json and put that into this PR

There are too many changes in tile_config.json to figure it out for me. I don't feel it's okay to put it all in that PR

**Comment by Fris0uman** [comment]
I can do it for you, but really the changes in tile_config are normal.

**Pull request closed without merging**
