### PR TITLE
Sidebar position option

### LINKED ISSUE #13384: Suggestion: Add option to toggle sidebar from right-side to left.
Just a small request someone asked me about.
Instead of the sidebar being just on the right side, add an option to switch it to the right side or left side of the screen.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26092278-suggestion-add-option-to-toggle-sidebar-from-right-side-to-left?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by drbig**
Closes #13384.

Tested in tiles and curses (Linux x64). Looks OK. Barring any weird edge-cases that I'm unaware of (hope not hope not...) this was as sane as I wished it would have been.

### CODE REVIEW

**Comment by Metallumere** [comment]
Huzzah! Good work. :D

**Comment by BevapDin** [comment]
There are a bunch of other windows that are supposed to overlay the sidebar, but they are still placed at the right side (which is actually the wrong side, not the right, but they still are at the right side, language is confusing):

- ~~live view~~ (works correctly)
- editmap (via debug menu)
- ~~look around~~ (works correctly)
- view monsters / items around
- zone manage
- ~~throw/firing~~ (works correctly)

**Comment by drbig** [comment]
Aye. This was sort'a expected... Will look into it!

**Comment by drbig** [comment]
@BevapDin Addressed these three and they look to work fine. Also did testing in tiles, but I see no reason curses could behave differently here.

**Comment by drbig** [comment]
Hm, I think I might have forgotten one term for the editmap.

**Pull request merged**
