### PR TITLE
Make ammo belts wearable [RDY]

### PR DESCRIPTION
**Pull request by mugling**
Weight, volume and **now encumbrance** depend upon their length scaled relative to ammo `stack_size`

### CODE REVIEW

**Comment by Mecares** [comment]
Nice, now i need two ammo belts a sombrero and a mustache.

**Comment by chaosvolt** [comment]
Oh this should be Fun.

**Comment by DeadLeaves** [comment]
if you start burning while wearing one of these, what happens? O_o

**Comment by mugling** [comment]
Try it and report back

**Comment by Coolthulhu** [comment]
Nothing special unfortunately. Burning worn items weren't updated for a loooong while and the reactions are hardcoded just by material.

**Comment by chaosvolt** [comment]
As I suspected, yeah. I could've sworn only items on the ground could cook off. :V

**Pull request merged**
