### PR TITLE
[RDY] Add CUT_FINE 1 to Pocket Knife

### PR DESCRIPTION
**Pull request by Cosmitz**

### CODE REVIEW

**Comment by Reclusive-reptile** [comment]
CUT_FINE is currently only used for removing bionics and therefor limited to precise surgical tools. You will have to explain how a pocket knife is the same as a scalpel.

**Comment by Cosmitz** [comment]
Because i want to use CUT FINE for archery crafting instead of CUT and given CUT FINE 1 is set to combat knives, a trench knife, a kukri and even a butcher knife... Those are really not 'precise' instruments. Indeed CUT FINE 2 and CUT FINE 3 are set to x-acto and scalpel but, it makes no sense not to use CUT FINE for the pocket knife given new usage, given how widespread it is within the other items. CUT is too widely used for a lot of things, including stuff like broadswords which would be entirely too unwieldy for cutting and placing fletchings on arrows.

If anything a cut-down on what constitutes 'CUT FINE' given the uses it has is is more recommended but outside the current scope of works. For the moment just bringing a basic tool in line with new use is what i'm aiming for. And i don't think it will imbalance anyone wanting to remove bionics that they'll have access to an easier to find option at that point in the game.

**Comment by Leland** [comment]
> CUT_FINE is currently only used for removing bionics and therefor limited to precise surgical tools

`CUT_FINE` around level 3 or so certainly is a precise surgical tool, but a level of 1 should be completely acceptable for a pocket knife. We have it on the [switchblade](https://github.com/CleverRaven/Cataclysm-DDA/blob/2e4c2a7b1138b98bc784dee491ab252be99b5ee4/data/json/items/tools.json#L6823
) and [butcher knife](https://github.com/CleverRaven/Cataclysm-DDA/blob/2e4c2a7b1138b98bc784dee491ab252be99b5ee4/data/json/items/tools.json#L3924), for instance.

**Comment by Cosmitz** [comment]
More weird is that it's on army knives and bayonettes which are far from the sharp, precision, small instruments you'd want for careful work. But again, for this exact PR, just CUT FINE 1 on pocket knife will be enough.

**Comment by angoddu** [comment]
So is this PR a precursor to a future PR where fletching requires fine cutting 1?

**Comment by Cosmitz** [comment]
It can be considered that, but given a lot of similar (and even bigger) tools have Fine cutting 1, it can be considered just a pulling of the pocket knife in line. It doesn't steal any thunder from the xacto/scalpel.

**Comment by angoddu** [comment]
Agreed. I wouldn't mind if butcher knife was no longer fine cutting as well

**Comment by Night-Pryanik** [comment]
> I wouldn't mind if butcher knife was no longer fine cutting as well

> It's also on the butcher knife, which is pretty weird.

What's wrong with butcher knife having fine cutting? 
oh77

I think it qualifies for 

>sharp, precision, small instruments you'd want for careful work

**Comment by Cosmitz** [comment]
I think this is the butcher knife the game is allowing us to imagine. 

https://asharpslice.com/wp-content/uploads/2015/03/31OD78yqw4L-300x218.jpg

"This is a sharp, heavy knife."

**Comment by Night-Pryanik** [comment]
I'd call the tool on your picture a hatchet, not knife.

**Comment by Cosmitz** [comment]
Either way, not the point of this particular PR. And either way, said butcher knife already has CUT FINE 1. :)

**Comment by AlecWhite** [comment]
>I'd call the tool on your picture a hatchet, not knife.
That's a cleaver knife. https://en.wikipedia.org/wiki/Cleaver
The most stereotypical butchering knife ever.

**Comment by Night-Pryanik** [comment]
Butcher hatchet = cleaver. For chopping. Don't qualifies for fine cutting.
Butcher knife. For cutting. Qualifies for fine cutting.

That's what I had in mind when I added fine cutting to the butcher knife in #20382.

**Comment by Leland** [comment]
Not the place for this discussion, y'all. Open an issue to talk about further `CUT_FINE` changes – this PR only adds it to the Pocket Knife, which no one so far has had an issue with.

**Comment by Cosmitz** [comment]
Well, might as well edit the description to say 'a small, wieldy knife used by butchers to skin and cut various fats and meats'. But again, not the point of this PR. :P

**Comment by angoddu** [comment]
I agree with the changes made in this PR and believe it is fitting to be added to the main game.

**Pull request merged**
