### PR TITLE
Set age for monster corpses in json mapgen

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Infrastructure "Set age for monster corpses in json mapgen"

#### Purpose of change
Contribute to #56958.

#### Describe the solution
Added new `age` field for `corpses` and `place_corpses` in json mapgen. This value means age (in days) of monster's corpse. If not set, `age` defaults to current turn.

#### Describe alternatives you've considered
Use minutes or hours instead of days.

#### Testing
Modified `mx_grave` map extra so it spawns only graves with corpses of pets. Spawned this map extra. Checked age of pet's corpse (0). In json set age to 3 days. Checked age of pet's corpse once again.

#### Additional context
None.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Could this mean we'd no longer find freshly pulped corpses when exploring new terrain, but rather would find only the items they carried if the age was set to -1 and significant time had passed since the save's start (with -1 assumed to mean start of time, rather than age)?

**Comment by Night-Pryanik** [comment]
I'm not entirely sure what you mean. Could you please elaborate?

**Comment by PatrikLundell** [comment]
Currently, when traveling around to new places you discover recently pulped human corpses on top of a pile of stuff. These corpses can be found out in the terrain, in particular plains (or at least it's easier to see them there) scattered about scarcely.
It's somewhat odd that they'd just been killed wherever and whenever encountered, instead of having perished at the time zero, in which case the corpse should have rotted away when you get to the location later in the game.

Thus, if you could say that the corpse had an age of "before start of time" = created at time 0 - 1, it could be decayed appropriately by the time you find it.

**Comment by Night-Pryanik** [comment]
`place_corpses` and this new `age` field only works for monster corpses. The corpses of humans scattered around the world are placed by other means, usually simply by placing `corpse` item. My PR isn't adding a way to set age for human corpses, only for monsters corpses.

**Comment by PatrikLundell** [comment]
Thanks for the clarification.

**Pull request merged**
