### PR TITLE
Remove space before "cm"

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
None

#### Purpose of change
Keep units unified.

#### Describe the solution
Remove space before "cm" as all other unites don't use space before it.

#### Describe alternatives you've considered
None.

#### Testing
Simple text change, should be seen with Magiclysm enabled, e.g. in debug.

#### Additional context
None.

### CODE REVIEW

**Comment by andrei8l** [comment]
SI convention is to leave a space between the value and unit though

**Comment by Faalagorn** [comment]
> SI convention is to leave a space between the value and unit though

We do keep the space in Polish, but not sure about the American English? They don't follow the SI convention much and in ammo names, the space isn't present, e.g. 9mm.

**Review by Maleclypse — APPROVED** [review]

**Comment by perryprog** [comment]
Bit late, but in American English I've always seen (and written) with a space between number and unit (SI or customary). The SI standard also says to use a whole space between the number and its unit, which is what most technical style guides also recommend.

I would argue that ammo sizes are their own thing that live outside of normal unit conventions, just because of the context they're presented in, but I could be wrong there (I know nothing about gun-stuff).

**Comment by Faalagorn** [comment]
> Bit late, but in American English I've always seen (and written) with a space between number and unit (SI or customary). The SI standard also says to use a whole space between the number and its unit, which is what most technical style guides also recommend.
> 
> I would argue that ammo sizes are their own thing that live outside of normal unit conventions, just because of the context they're presented in, but I could be wrong there (I know nothing about gun-stuff).

American English is weird indeed, I see it was merged now anyway, but maybe I should take a deeper look indeed, not being a native English speaker, especially in the US and the rules _do_ differ indeed, including the ones here :thinking:.

**Pull request merged**
