### PR TITLE
KSG second barrel and primary now show same stats

### LINKED ISSUE #20583: Kel-Tec KSG Stats are different when using second magazine.
V 0.C-21676-gff203dbfe5 (tiles) Windows x64  (Current as of a couple hours ago, Jenkins Build 6335)

These are two stock KSGs loaded with 00 shot.  The longer reload time makes sense, but the rest should be identical.  Also, it appears that effects from gun mods also do not apply.

image

### PR DESCRIPTION
**Pull request by kolsurma**
Fixes #20583

### CODE REVIEW

**Comment by kolsurma** [comment]
As a note, the KSG primary isn't nearly as OP as it was before this, the secondary is so much better though.

This doubles the weight of the weapon, the primary barrel still reloads 2 seconds faster. It could possibly use a bit more weight as it's still fairly OP in that regard.

**Comment by BorkBorkGoesTheCode** [comment]
I proposed a similar fix last year. From muglings comments:

>Correct solution is to fix auxiliary mod recoil calculation to use base weights

>this PR obfuscates any actual fix - it's a JSON hack in core for a non-critical issue.

**Comment by kolsurma** [comment]
But hacks are so much easier! Oh well.

'non-critical issue' is relative though. It's not a crash bug but it's a bug none the less.

**Comment by BorkBorkGoesTheCode** [comment]
I don't know what fix will be acceptable for merging.

**Comment by kolsurma** [comment]
Looks like this is a non-trivial change. The way I'd want to fix it is for it to have a pointer to its parent, as of right now the parent can see any children in `contents`, but not the reverse.

**Comment by kolsurma** [comment]
bloody tabs.

**Pull request merged**
