### PR TITLE
Added spawn of three types of road violence

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Added spawn of three types of road violence."```

#### Purpose of change
Roads always seemed too calm to me as if no Cataclysm struck. This PR is meant to slightly change that by adding three types of road mayhem and violence.

#### Describe the solution
Added new map extra with three types of spawns and made them spawn on roads.

#### Additional context
Car accident resulted in a shootout with two victims

Some cocky moron with friends got dragged out of limo and shooted down by a military

Some unfortunate stopped at the roadside to change tire, but was ambushed and killed - either by unknown people or by wolves

### CODE REVIEW

**Comment by faefux** [comment]
>Some cocky moron with friends got dragged out of limo and shooted down by a military
This is my favourite PR!

**Comment by ifreund** [comment]
This is awesome, we need more signs chaos like this in the cataclysm

**Comment by faefux** [comment]
I know it's beyond the scope of this PR but are there any plans to move this to json?

**Comment by Night-Pryanik** [comment]
> I know it's beyond the scope of this PR but are there any plans to move this to json?

I think plans for this exist, but I don't know if anyone is working on it.

**Comment by NerosShadow** [comment]
need more like this

**Pull request merged**
