### PR TITLE
Obsolete radiation zombies

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Our radiation zombies have been in a limbo for years, being a relic of Necropolis which has since been removed. They were extremely odd in several blatant cases - most noticeably being stronger than regular zombies despite being basically just radiation-damaged corpses. And frankly the description just sounds like Fallout. Doesn't help that the charred nightmare apparently hasn't been used in vanilla *at all*.

#### Describe the solution
Remove the charred nightmare and irradiated wanderers from vanilla, move their definitions to No Hope where they're still used.

In the bunker group boosted up the chance for bio ops and soldiers, so that packs of power armor zombies didn't appear 1/11 times the group spawned

#### Describe alternatives you've considered
I initially didn't do this because someone on the devcord wanted to audit them, but they have since given up on the idea and gave greenlight for obsoletion.

#### Additional context
I do feel like there's some fun design room for zombie flesh affected by radiation, but weirdly strong corpses in jumpsuits isn't that.

### CODE REVIEW

**Comment by RanikOrtega** [comment]
What would be necessary for their audit rather than obsoletion?

**Comment by GuardianDll** [comment]
Someone to audit, and solid idea that fit the game

**Comment by Karol1223** [comment]
Some to actually want to put the time and effort into reworking them to be interesting and make sense, yes. Currently they're neither interesting nor make much sense (again - damaged corpses that are stronger than normal corpses???)

Personally when I think of zombie radiation I think of stuff like that one flesh growth from Metro, but we've been getting flesh growths elsewhere, so I don't exactly have many ideas.

**Comment by Holli-Git** [comment]
Also radiation just is not that common, especially not in huge amounts. Sure, hazardous waste sarc and lab reactors but those are outliers and wouldn't make sense as to why zombies are in there

**Comment by John-Candlebury** [comment]
> No Hope and Aftershock where they're still used.

Please remove them from aftershock instead. Zombies arent meant to be a thing there.

**Pull request merged**
