### PR TITLE
Remove obsolete mods which are maintained in other repos

### LINKED ISSUE #20326: Deleting the Pks_Rebalancing Mod folder from this repository
I would very much like to, to allow my own repository to be the primary and only source.

The version here still causes confusion for new players to the mod, and its been on the obsolescence list for a while now.

The mod is still being actively developed and is still enjoying growing popularity, and I would be willing to provide a backup of the old version included with this repository, although it should be unplayable due to the majority of commits and linting method improvements.

### PR DESCRIPTION
**Pull request by cainiaowu**
Fix #20326.

Remove obsoleted Arcana and PK Rebalancing mods as both authors expressed that they want them removed from master.

They are maintained in following repo:

Arcana: https://github.com/chaosvolt/cdda-arcana-mod

Pisskop's Rebalancing: https://github.com/pisskop/PKs_Rebalancing

See also 

https://github.com/pisskop/PKs_Rebalancing/issues/30

https://github.com/cataclysmbnteam/Cataclysm-BN/issues/22

### CODE REVIEW

**Comment by Leland** [comment]
What would this do to old saves?

**Comment by Cyrano7** [comment]
Maybe just add "obsolete": true to Arcana for now? Maybe some legacy stuff could be dropped after or right before a stable release?

**Comment by pisskop** [comment]
it _is_ 30k lines removed ...

**Comment by cainiaowu** [comment]
@Cyrano7 They have been "obsolete": true for over a year now, which means they are invisible to new gamer for over a year, unless someone has a savefile that doesnt beak on load with these mods on in newest experimantal (which doesnt exist, see chatsvolts issue), we can drop these two mod just fine.

**Comment by cainiaowu** [comment]
@Cyrano7 They have been "obsolete": true for almost a year now, which means they are invisible to new gamer for almost a year, unless someone has a savefile that doesnt break on load with these mods on in newest experimental (which doesnt exist, see chatsvolts issue), we can drop these two mods just fine.

**Comment by kevingranade** [comment]
10 and 11 months of obsoletion, seems like plenty of notice.

**Pull request merged**
