### PR TITLE
Stop adding fur lining to guns

### LINKED ISSUE #11242: You can sew pockets on guns.
I sewed some on an MP5. Also kevlar plates.

Works with other guns and ````tailor's kit```` -based enhancements as well.

### PR DESCRIPTION
**Pull request by PropaneSoup**
Fixes #11242. Also I cleaned up that double-modification check. Thanks to Coolthulu for that.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Why not an ````is_gun```` check to see if the target it a gun?

This looks like it would block armor that contains cloth and metal from being modified.

**Comment by KA101** [comment]
Yeah, is_gun would be the way to go.

**Comment by PropaneSoup** [comment]
Oh, I had no idea that is_gun existed. I think leaving in the check for superalloy is alright though, unless you think adding pockets and such to power armor is alright.

**Comment by Rivet-the-Zombie** [comment]
It would also affect superalloy-filled MBR vests, so I'm going to push for an is_gun type thing.

**Comment by KA101** [comment]
>power armor

I'd have trouble with adding linings, etc when it requires complete skin contact.  Prefer allowing the PC to craft a non-powered hauling frame, I'd think.

**Comment by PropaneSoup** [comment]
I never knew all these checks existed! This makes this all so much easier. And I agree that there wouldnt be much room/can't melt and reform the superalloy that it's made out of. So I'll add an is_gun and is_power_armor check. I'll have to get to those tomorrow, busy this night.

**Comment by KA101** [comment]
OK, tomorrow it is.  Happy Cheap Candy Eve.

**Comment by DavidKeaton** [comment]
Cheap candy? No way!

**Comment by KA101** [comment]
Tested, works, merging.

**Pull request merged**
