### PR TITLE
Misc ui improvements

### PR DESCRIPTION
**Pull request by Asmageddon**
SUMMARY: Interface "Assortment of UI improvements"

Entails the following four changes:
-----
* Charges and skill used now shown in item repair screen:

 * Color-coded and slightly rearranged the aim panel(also includes some layout fixes, and now no lines ever get cut off):

 * Items with contents or charges now show maximum capacity:

 * Unavailable due to skill requirement recipes are now shown in brown in book description:

-----

# Possible issues:

 * I don't 100% understand how the maximum capacity displaying code works. I have tested every likely-to-break case I could think of, but the only issue I noticed is that battery compartment-modded items still display 0/N charges, but I couldn't find a solution not involving either hardcoded checks, or JSON changes or additions.

 * I put the color-coded `get_colored_bar`(variant of `get_labeled_bar`) in the file it's used in, rather than in `output.cpp`, because I couldn't decide whether that should be done - both overloads of `get_labeled_bar` are only used in `ranged.cpp` anyway... well, now, one of them is, since the other is dead code.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Could item repair screen also show number of rag/leather/kevlar/... used ?

**Comment by Asmageddon** [comment]
@Fris0uman It almost certainly could, but that's slightly more involved and I didn't feel like digging through the code, plus it could either get cramped or need several lines when multiple items can be used, and I didn't feel like making the decisions on how to display it.

**Comment by Xhuis** [comment]
When I saw "UI improvements" I felt a sinking feeling due to the sidebar stuff lately, but I like this. Just a heads-up, if #28022 gets in before this, any items powered by bionic power would display errant charge to max charge ratio (i.e. `1532/1000`) since they ignore max charges.

The aim panel is also a little grating on the eyes; as someone who loves ranged combat I could see it getting stressful. I'd personally suggest changing it to something like great being white and normal + graze being gray. I like the rest though!

**Comment by Asmageddon** [comment]
@Xhuis Since I kinda agree with you, I changed the colors to this:

**Comment by Asmageddon** [comment]
Also, can someone tell me why the gorgon-ghprb checks are failing for my PRs? :-(

**Comment by AMurkin** [comment]
It says:
```
astyle regressions found.
Formatted  src/activity_handlers.cpp Formatted  src/ranged.cpp Formatted  src/item.cpp
```
You should astyle changed lines in this files.

For `src/activity_handlers.cpp` it wants:
```diff
@@ -2325,18 +2325,18 @@ void activity_handlers::repair_item_finish( player_activity *act, player *p )
         }
 
         std::string title = string_format( _( "%s %s\n" ),
-            repair_item_actor::action_description( action_type ),
-            fix.tname() );
+                                           repair_item_actor::action_description( action_type ),
+                                           fix.tname() );
         title += string_format( _( "Charges: <color_light_blue>%s/%s</color> %s (%s per use)\n" ),
-            used_tool->ammo_remaining(), used_tool->ammo_capacity(),
-            item::nname( used_tool->ammo_current() ),
-            used_tool->ammo_required() );
+                                used_tool->ammo_remaining(), used_tool->ammo_capacity(),
+                                item::nname( used_tool->ammo_current() ),
+                                used_tool->ammo_required() );
         title += string_format( _( "Skill used: <color_light_blue>%s (%s)</color>\n" ),
-            actor->used_skill.obj().name(), level );
+                                actor->used_skill.obj().name(), level );
         title += string_format( _( "Success chance: <color_light_blue>%.1f</color>%%\n" ),
-            100.0f * chance.first );
+                                100.0f * chance.first );
         title += string_format( _( "Damage chance: <color_light_blue>%.1f</color>%%" ),
-            100.0f * chance.second );
+                                100.0f * chance.second );
 
         if( act->values.empty() ) {
             act->values.resize( 1 );
```

**Comment by Inglonias** [comment]
I absolutely adore that first change, and have no problems with the other changes presented here. Good work.

**Comment by Asmageddon** [comment]
@I-am-Erk Alas, had a bad day so it is the only thing I did, but here you go:

**Comment by I-am-Erk** [comment]
That is awesome asmageddon, thanks

**Comment by Xhuis** [comment]
I didn't know I wanted a blue stamina bar until I saw it. Neat!

**Comment by Asmageddon** [comment]
@kevingranade I have played with these changes for over a week and found no issues other than what the minor ones already mentioned here. Could this get merged in time for 0.D?

**Comment by I-am-Erk** [comment]
0.D is already in release testing, this will have to wait.

**Pull request merged**
