### PR TITLE
Adding Extracts and Concentrates Mod

### PR DESCRIPTION
**Pull request by NastyNate2612**
Adding Extracts and Concentrates Mod

#### Summary
SUMMARY: Mods "adds working equipment for manufacturing essential oils, along with misc items for crafting recipes and comestibles"

#### Purpose of change
<I noticed a lack of cannabis related comestibles. this mod will add more forms of cannabis along with the ability to make edibles and all sorts of fun stuff using essential oils. (think about using essential oils to mask smells and for effect changes etc.>

#### Describe the solution
<Add this Mod i made! ive spent 60+hrs working on this thing over the past couple weeks. its fairly complete but will need small reworking/overhaul when other required systems are changed>

#### Describe alternatives you've considered
<nope>

#### Testing
<Ive fully tested the mod, crafting each recipe with and without tools and electricity to make sure everything works well and inputs/outputs are comparable to real life figures>

#### Additional context
  <I have extensive knowledge in the creation and operation of these systems. most of the knowledge i have and have put into this mod are trade secrets that you either have to go to very expensive classes for or have experience in practical application in manufacturing.  Most likely ill have to write a step-by-step guide explaining the process that will appear in-game. i doubt theres that many people that can step into a hash lab and whip up a batch of grade AAA shatter or distillate playing cataclysm, but u never know... The vac_oven_large item needs work, i want to make it operate like the furniture item rock kiln but using battery power at the same time. couldnt figure that one out without cpp changes. Also the dab_pen_empty/dab_pen_full and similar item dab_rig need a little work, i tried getting them to be tools similar to the ecig so i tried making it a tool but could use the action command "consume drug" consuming "hi_q_distillate" as charges but theres no morale effect ("fun" field doesnt apply to tools im guessing) and when there isnt enough distillate charges in gives an error code instead of the error message thats in the json data. other than that everything works pretty well. Sooooo to recap vac_oven_large, dab_pen_full, and dab rig need a little TLC, but the rest works great. whenever we get the vac oven to work like the rock kiln i can make the vac_oven_small do the same thing, for now that one works good. 
   Id like to make a new location as well, similar to the grow house except its a blackmarket hash lab. cool thing about that is it could have 2 different spawn types: 1 where its still intact and another where it blew up (mini nuke equivalent probably). You need a lot of plant material to run these types of machines so we're gonna need to do something with agriculture for this to work properly. Also power system wise i barely have enough juice to run these things. i noticed in a previous PR u guys talked this fact and about changing the storage size of batteries or changing the basic unit of measurement for 1 battery charge. whenever the power system gets overhauled ill do the same to all the equipment. i did use "power_draw" as much as possible assuming that when things do change then the power draw field will be the best way to do it.
  Thanks for reading! this is my first mod ive EVER made, i had 0 previous knowledge .json files or modding in general. im proud of it and it took me quite a lot of time. Hope everybody likes it.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
This shouldn't be a mod, this should be in the base game.

**Comment by NastyNate2612** [comment]
not sure why but some of the lines didnt "line up" the same why as they did on my notepad++. weird

**Comment by anothersimulacrum** [comment]
You used tabs instead of space. You need to run your JSON through the [linter](https://dev.narc.ro/cataclysm/format.html).
Paste the entire file in, lint it, then paste it back where it came from.

**Comment by NastyNate2612** [comment]
ahh ok i gotcha. i didnt notice it really doing anything when i was making all the entries, but now i see the subtle change it makes to it occasionally. ill go through and lint them

**Comment by NastyNate2612** [comment]
i only used spaces, no tabs, but it didnt like the format i used for the and/or components stuff

**Comment by NastyNate2612** [comment]
I need to add a few things to the item_groups file too, forgot about that. i made a bunch of additions at one point and stopped adding them to the item groups as i went

**Comment by NastyNate2612** [comment]
well i ran everything through the linter and it still says some of the files are unformatted. runs fine in game so not sure what the problem is with that.

**Comment by NastyNate2612** [comment]
> 
> 
> This shouldn't be a mod, this should be in the base game.

This is all new to me so i dont know whats supposed to be called a mod and whats supposed to be in the main game. i figured everything that other people make is a mod until u guys confirm if its worth going into the main game or staying as a mod to be selected on world creation or not on the list at all

**Comment by I-am-Erk** [comment]
Glad to see you came!

Yeah these can be added straight to the files in the data/JSON directory they fit best, no need to miss around with mods.

I did the same thing when I was starting out and mlangsdorf responded to me in the same way, no worries.

**Comment by NastyNate2612** [comment]
If I'm gonna put them into the matching game folders then yeah that makes sense, I'd rather do it a couple entries at a time. I already organized it like that so it wont be too difficult. I also want to change a few placeholder descriptions and not enter in the work in progress items so they can be worked on. Or should I still enter the work in progress items but with a pseudo flag or something?

**Comment by NastyNate2612** [comment]
Oh never mind u know what to do. I'll open up separate PR's for the work in progress items

**Pull request closed without merging**
