### PR TITLE
More Survival Tools Series 7

### PR DESCRIPTION
**Pull request by chaosvolt**
While I'm waiting on the Big Fat Tileset Update, figured I'd add another
round of these.
1. Flint and steel now takes longer to craft, and requires a chunk of
   steel plus a sharp rock. Best way I could think of to make it less of a
   straight upgrade to the fire drill.
2. Gave tinder a requirement of survival 1 to make.
3. Replaced the hooded hat's rainproof quality with waterproof. Not
   getting your hair wet, sure. But since any item with rainproof flag
   seems to give full protection from rain, that's a bit much.
4. Reduced the marksmanship requirement for steel and lead bearings,
   from 4 to 2.
5. Added a recipe allowing you to craft slings using just short or long
   strings. This has a fabrication requirement of 1, takes longer than the
   normal recipe (you're essentially weaving/braiding a cord sling), but is
   reversable.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Hmm. And now to pose the question: pliers, or no pliers? If I do add them, should I add a limited number of ammo uncraft recipes, with the specific caveat that it returns less lead than using a bullet puller would? o3o

**Comment by Rivet-the-Zombie** [comment]
We're pretty vague with our tools; we don't differentiate between types of screwdrivers or hammers, and we use wrenches for EVERYTHING. I'd just have it use the wrench.

**Comment by chaosvolt** [comment]
Hmm. True, though I would love pliers as a more readily-available source of non-fine bolt turning.

Being able to take apart certain lower-tech ammunition without a puller, at a net material loss, would also be interering. owo

**Comment by Rivet-the-Zombie** [comment]
If you're going to add pliers as a lower-quality counterpart to the wrench, would you please do so in a separate PR, and add it to the mainline?

It strikes me as the sort of thing that if we're going to add it, we might as well add it to the mainline.

**Comment by chaosvolt** [comment]
Hmm. Might be a good idea, yes.

What about using them for that purpose, and the "intact .22LR case" idea? Mainline either, or mod-only?

**Comment by Rivet-the-Zombie** [comment]
Both other ideas would be good for mainline.

**Comment by chaosvolt** [comment]
Meep. I might have to do exactly that then. Maybe use that as an opportunity to add additional weapons, tools, and ammo?

.357 Magnum and .45 Long Colt would be high on my "do want" list, as would a BAR. owo

**Comment by Rivet-the-Zombie** [comment]
Until we have a system whereby weapons can use multiple ammunition types, .357 isn't going to work (IRL, you can load .38 special into a .357, but you can't load .357 into a .38 - and even if you can, you definitely shouldn't).

**Comment by chaosvolt** [comment]
I did mention on the forums that I would love ammunition type overlap. For now I'm thinking simply add to existing ammo types.

Maybe...Thompson SMG, Sten (simple enough to manufacture that it'd be in reach for a well-read survivor), Browning Automatic Rifle, M1903 Springfield, M1 Garand, M240, and M60? o3o

The Garand's "en-bloc clip landing on a hard surface after empting the magazine" thing might not be feasible to code though.

**Comment by chaosvolt** [comment]
Also, heavy rain here, so might mess with my satellite and/or power. >w<

**Comment by Rivet-the-Zombie** [comment]
Having fired an M1, I can tell you that they make that weird clanging noise when they run dry even if the clip lands in the grass. It's something in the way the mechanism works I guess. Either way, I wouldn't sweat that part.

**Comment by chaosvolt** [comment]
Hmm. Very well then. Will branch and start work on the stuff.

**Comment by chaosvolt** [comment]
Swiggity swooty: https://github.com/CleverRaven/Cataclysm-DDA/pull/12481

**Comment by chaosvolt** [comment]
Ooh, surprised to see this right before I woke up, it seems. Thank you for the merge.

**Pull request merged**
