### PR TITLE
Allow for cross-compiling from Linux to Windows in Devcontainer

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
Build "Allow for cross-compiling from Linux to Windows in Devcontainer"

#### Purpose of change
Expanding the use of the devcontainer to fit my use case. I want to build on a Linux VM and play on the Windows host. Besides that, since the devcontainer is flexible, you can use it for all kinds of purposes, for example using github codespaces.

#### Describe the solution
Takes the instructions from https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md#cross-compile-to-windows-from-linux and put it in the dockerfile with some adjustments. 

The section of the dockerfile that installs the Windows dependencies are displayed as comments in the dockerfile so users that do not want to cross-compile don't install unnecessary packages. This means users that DO want to cross-compile will have to un-comment that section and build the container as per the guide in the docs.

The devcontainer guide has also been updated to reflect the changes.

#### Describe alternatives you've considered
I chose to add the section as comments because that's the easiest for users to adjust. An alternative would be named build stages, but the user will have to adjust the parameters of the build command for the devcontainer. I'm not sure if that can be done in a user-friendly way.

#### Testing
Follow https://github.com/snipercup/Cataclysm-DDA-1/blob/Devcontainer-Dockerfile-Crosscompile-Windows/doc/COMPILING/COMPILING-DEVCONTAINER.md from top to bottom.

### CODE REVIEW

**Comment by snipercup** [comment]
So if you build the container right now, you'd get:
```
=> CACHED [ 9/16] RUN git clone https://github.com/mxe/mxe.git ./mxe                                           0.0s
 => CACHED [10/16] RUN cd mxe                                                                                   0.0s
 => ERROR [11/16] RUN make -j4 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static'     MXE_PLUGIN_  1.7s
------
 > [11/16] RUN make -j4 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static'     MXE_PLUGIN_DIRS=plugins/gcc12 sdl2 sdl2_ttf sdl2_image sdl2_mixer gettext:
1.521 make: *** No rule to make target 'sdl2'.  Stop.
------
Dockerfile:47
--------------------
  46 |     # Builds windows version of SDL2 which is required to later cross-compile CDDA.
  47 | >>> RUN make -j4 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' \
  48 | >>>     MXE_PLUGIN_DIRS=plugins/gcc12 sdl2 sdl2_ttf sdl2_image sdl2_mixer gettext
  49 |     RUN cd ../libbacktrace/
--------------------
ERROR: failed to solve: process "/bin/sh -c make -j4 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static'     MXE_PLUGIN_DIRS=plugins/gcc12 sdl2 sdl2_ttf sdl2_image sdl2_mixer gettext" did not complete successfully: exit code: 2

 *  The terminal process "/usr/bin/bash '-c', 'docker build --pull --rm -f ".devcontainer/Dockerfile" -t cataclysmdda1:latest ".devcontainer"'" terminated with exit code: 1. 
```

I'm pretty sure it has something to do with the file structure. Clearly it deviates from https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md#cross-compile-to-windows-from-linux in that. I say this because that guide has the CDDA branch in the ```~src/``` folder next to the mxe and libbacktrace folders, while my PR puts the mxe and libbacktrace folders in the CDDA/src folder although I haven't verified that.

I want to do the following steps to make this work:
1. try to adjust the file system folders so the cdda, mxe and libbacktrace are sibling folders. This probably requires an adjustment in the build context of the dockerfile
2. find another way to get SDL2 in the right format on the devcontainer. This probably is not easy because if it was, the ```COMPILING.md#cross-compile-to-windows-from-linux ``` guide would include it.

I am looking for help on this and already asked @rtizzy for help

**Comment by snipercup** [comment]
After the container was built, I tried to build the game using the makefile extention in VSCode using the makefile settings in settings.json (which I edited in this pr). It resulted in failure:
```
make: Nothing to be done for 'cataclysm-tiles'.
rm -rf *bindist
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-g++ -Isrc -isystem src/third-party -DRELEASE -DCROSS_LINUX -DWIN32_LEAN_AND_MEAN -DGIT_VERSION -DTILES -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -O3 -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -g1 -fsigned-char -std=c++17 -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/opus -DSDL_SOUND -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/libpng16 -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/webp -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/harfbuzz -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/glib-2.0 -pthread -I/opt/mxe/usr/x86_64-w64-mingw32.static/lib/glib-2.0/include -mms-bitfields -DPCRE_STATIC -I/opt/mxe/usr/x86_64-w64-mingw32.static/include/freetype2 -MMD -MP -Wno-error -c pch/main-pch.hpp -o pch/main-pch.hpp.gch
rm -rf save
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-windres -J rc -O coff src/resource.rc -o objwin/tiles/resource.o
make: *** No rule to make target 'VERSION.txt', needed by 'cataclysmdda-0.F.zip'.  Stop.
make: *** Waiting for unfinished jobs....
rm -rf lang/mo lang/mo_built.stamp
rm -f data/options.txt
rm -f data/keymap.txt
rm -f data/auto_pickup.txt
rm -f data/fontlist.txt
// NOLINT(cata-header-guard)
#define VERSION "0.E-27637-g4692cf60ba-dirty"

 *  The terminal process "/usr/bin/bash '-c', ''make' 'cataclysm-tiles' '-j4' 'CROSS=/opt/mxe/usr/bin/x86_64-w64-mingw32.static-' 'RELEASE=1' 'TILES=1' 'SOUND=1' 'LOCALIZE=1' 'bindist''" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
It's not immediately clear to me where it fails, I will have to look into it more. Suggestions are welcome.

**Comment by rtizzy** [comment]
@snipercup 

Good work so far. I'd suggest a quick sanity check. 

Have you built this in the container without the VSCode extension yet? If you haven't, I'd suggest giving that a go. 

1. Grab a shell inside the container (Either via VSCode or Docker Run/Exec)
2. Attempt to run with `make` (and the appropriate flags) directly. 

If it builds in that manner then it's likely something up with how the VSCode extension has been configured and you can start digging in more there.

**Comment by rtizzy** [comment]
As an aside, the symlink is fine but you may want to consider using `https://linuxpip.org/python-is-python3/`.

**Comment by snipercup** [comment]
I got it working. I did all my actions for this PR. I was unable to get rid of ```make: *** No rule to make target 'VERSION.txt', needed by 'cataclysmdda-0.F.zip'.  Stop.``` but my goal was to compile on Linux and play on Windows and that is a success. It works fine.

Feel free to test and/or merge.

**Pull request merged**
