### PR TITLE
Make the ice axe resemble an ice axe instead of a strange hammer

### PR DESCRIPTION
**Pull request by MoocowTG**
#### Summary
Balance "Bring ice axe in line with reality"

#### Purpose of change

Currently, the ice axe is busted. These are it's stats with 5 in relevant skills and 12 str, It's DPS is higher than combat machetes, maces, and hatchets, and it has a very high vs armoured DPS, thanks to it being bash damage for some reason. Its damage per stam is also the highest I've ever seen, able to clear entire screens of zombies without dropping past half stam. It is very compact, and has excellent utility qualities. The only downside is that it is -2 to hit.

image

#### Describe the solution

image

This is roughly what I assume the ice axe is trying to resemble. You wouldn't swing this thing on the hammer side, so it's being changed to pierce damage with some bash. The pry values have been lowered since there's no way you're prying a door with it. The materials are updated to include aluminum since ice axes often use that and are very light. The to_hit has been increased by one by giving a neutral balance to bring it in line with hatchets.

#### Testing

Checked values in game.

#### Additional context

This unfortunately a big nerf to the ice axe, but the weapon in it's current state just doesn't make any sense.

### CODE REVIEW

**Comment by MoocowTG** [comment]
Hm unsure why the latest tests failed. Don't see anything in the log related to what I changed.

**Comment by Karol1223** [comment]
It's a random test failure. You can close and reopen the PR if you want to restart the tests. Or, well, wait until someone with merge rights restarts them for you.

**Comment by tornikeo** [comment]
RIP sweet prince. You will be missed.

here-lies-squidwards-hopes-dreams-v0-NtiIZeCr2XlBWNoTC2wYm54EqViOS3BT4aImomVPF2g

**Comment by Tranberry** [comment]
composition

I wonder if this was the initial intent, a not so modern ice axe. But I do not think climbers have as much use for it.

**Comment by KnifeFightBears** [comment]
I'm not a developer and it's not my call, but I'm gonna ask you guys honestly here: Have you ever actually tried prying open a wooden door before?

It's really not that hard, and you could definitely do it with a modern ice axe

You might have a little trouble with somebody' secure front door but I could pry open interior doors in my last apartment with a butter knife

**Pull request merged**
