### PR TITLE
Add WIP Limb Stuff mod and move mainline limby stuff over

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Content "Add WIP Limb Stuff Mod"

#### Purpose of change

Begin #70703 with moving in-progress content to a mod that communicates its WIP-ness.

#### Describe the solution

Added a WIP Limb Stuff Mod, made myself its code owner
Moved limby JSON over to the mod
 -  Gastropod Foot's limb and enchantment
 -  All prosthetics including spawns and EoC
 -  Vitakinetic's limb regrowth power
 - Some slight prosthetic spawn adjustments
 - [x] Reset in-progress amputees - prosthetics are migrated to planks, on load amputee chars get a nice popup with instructions should they insist on continuing as such and get reset to full limbs.

#### Describe alternatives you've considered

~~Obsoleting all of it to keep in-progress amputee characters safe, but that just shifts breakage down the line to when this stuff will have been reworked and begins its migration back to mainline.~~
Went with the safe way.
#### Testing

Started a normal save without the mod - no errors
Started a canned amputee save - some missing EOC errors, on load (and waiting one tick) get the informative popup and my limbs back
Started a modded save - no errors

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
#70443 adds two new limbs for bird wings, replacing the mutant's arms and hands. The PR will still function without those parts being limbified, but given that it's about ready to merge, would it be possible to wait for that to happen, then move the limbs over to the mod? It would make my life easier.

**Comment by fairyarmadillo** [comment]
Whoops, I mean #70479

**Comment by Venera3** [comment]
The law of the land is "first merged wins" - if yours makes it in first the conflict resolution is on me and vice versa.

**Comment by Maleclypse** [comment]
So many conflicts

**Comment by Venera3** [comment]
> So many conflicts

Well if only y'all didn't merge limby stuff... Migrated bird wings over and rebased, should be ready now.

**Comment by Maleclypse** [comment]
Proceeded to fail tests I didn’t even know existed ;)

**Comment by Maleclypse** [comment]
I see you ran into the same confusion I did when I was trying to fix the ravenfolk errors.  I was gonna be helpful and instead I just complained in discord.

**Comment by fairyarmadillo** [comment]
I am not 100% sure what the design intent for ravenfolk is. They were using Bird's bird_wings mutation so I gave them parity with that, but it may be the original contributor's intent that they have wings separate from their arms.

**Comment by peearler** [comment]
I don’t see recipes for making prosthetic legs and arms after the system was added to a separate mod. for now just look in spawn places?

**Comment by Venera3** [comment]
> I don’t see recipes for making prosthetic legs and arms after the system was added to a separate mod. for now just look in spawn places?

Slight migration problem, I'll have a fix up soonish.

**Pull request merged**
