### PR TITLE
Quick to-hit fixes for a couple of weapons

### PR DESCRIPTION
**Pull request by RandDenner**
#### Summary
None

#### Purpose of change

Found a couple of poor to-hit category values for some weapons. They were never checked after a PR from last year went stale.

#### Describe the solution

Update values.

#### Testing

Check resultant DPS for match with expected values.

### CODE REVIEW

**Comment by NetSysFire** [comment]
You gotta fix the tests though. They fail because your changes modify their dps. So you either adjust the weapons so the dps matches again or you adjust the tests, that is up to you. I think the better approach of the two is to adjust the weapons because there was a reason why their dps was defined like this in the tests.

**Comment by RandDenner** [comment]
Yep. I wanted to see what he values changed to first, though.

**Comment by RandDenner** [comment]
Golf club before/after: 14  /  17.4479551583
Chainsaw before/after: 28  /  39.290876937
Electric chainsaw before/after:  28  /  39.290876937

Attempt reducing golf club damage by 3
Chainsaws by 11

**Comment by RandDenner** [comment]
Not enough. golf club is good, but combat saws only down to 33.7108314822 DPS
an 11 point reduction only got me a 5.6 DPS reduction
DPS needs to be within 0.5 of 28, so I need a further reduction of 5.5
5.6/11 = .51
5.5/.51 = 10.78, round up to 11
so another 11 points should do it

**Comment by Paprika-H** [comment]
> Not enough. The golf club is good, but combat saws are only down to 33.7108314822 DPS an 11 point reduction only got me a 5.6 DPS reduction DPS needs to be within 0.5 of 28, so I need a further reduction of 5.5 5.6/11 = .51 5.5/.51 = 10.78, round up to 11 so another 11 points should do it

I think it'd be worth it to make the golf club fragile, thin aluminum shafts aren't known for their durability

**Comment by RandDenner** [comment]
That's an interesting point.

**Pull request merged**
