### PR TITLE
Military base updates

### PR DESCRIPTION
**Pull request by aMegaSloth**
#### Summary
Content "Updates several items to the military base"

#### Purpose of change
This updates the military base to be slightly more up to date, and realistic.

#### Describe the solution
1. 5.56 and 7.62 ammo belts spawn full in the armory.
2. Adds M18 to the armory. This replaces one of the two shelves of M17 to M18. M18 is the compact service weapon to the M17 so I don't see why it shouldn't be included.
3. Adds gun repair kits to the armory. this goes in where the sheaths were, and the combat knifes were consolidated to one shelf.
4. The ballistic vests were without plates. This adds plates to the vests.
5. Swaps out a 9x18 15 round magazine for a 21 round magazine.

### CODE REVIEW

**Comment by GuardianDll** [comment]
#58016?

**Comment by aMegaSloth** [comment]
> #58016? but im not really sure, the military base is rely on random distribution, adding the collections can totally break it, im afraid

By collections are you referring to the ballistic vests? 
It just runs loops of place_items, and hardly if ever really touches any item groups.

**Comment by GuardianDll** [comment]
by collection i mean the collections i use in 58369

**Comment by aMegaSloth** [comment]
Ohh right. The military base has essentially pretty set spawns so I dont think collections would help it.

**Comment by Night-Pryanik** [comment]
Should this fix #48829?

**Pull request closed without merging**
