### PR TITLE
[CR] Coat non steel weapons

### LINKED ISSUE #56678: Allow the CVD machine to coat non-steel weapons
### Is your feature request related to a problem? Please describe.

Certain weapons cannot be diamond-coated due to the materials they're made of, such as bronze or iron. I really wanted a diamond khopesh, too...!

### Solution you would like.

I'd like for the CVD machine to be able to coat non-steel weapons.

### Describe alternatives you have considered.

Making steel variations of bronze weapons, and switching all iron weapons to steel (basically what I've been doing in my own self-modded game anyway).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vamshibon**
#### Summary
Bugfixes "CVD machine can now diamond-coat non-steel weapons" 

#### Purpose of change

Fixes #56678

#### Describe the solution

The material doesn't have to be non-steel in order to be diamond coated.

#### Testing

Passes all relevant tests

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
looks like your steel bar changes were added to this as well. 

Also I think it should still be limited to metals, or perhaps some more elegant solution like by max temperature the material can heat too since diamond coating a wooden spear doesn't make much sense.

**Comment by victorknox** [comment]
Ah my bad, I can revert the changes. 
However, I think it should be limited to metals as well, maybe we can just ignore these changes.

**Comment by bombasticSlacks** [comment]
I'm not sure on the science but you can just replace the current line with something like:
```c++
(e.made_of( material_steel ) || e.made_of( material_bronze ) || e.made_of( material_iron ) || etc. ) 
```
and at the top where material_steel is defined add additional definitions for the other materials

**Comment by AtomicFox556** [comment]
Iron (or budget steel for that matter; it's a distinct material at the moment) should work, but I haven't managed to find any attempts at growing synthetic diamonds on bronze. In fact, this improvised process uses an oxyacetylene torch as an attempt to make a synthetic diamond; bronze certainly couldn't handle it as it would melt.

https://www.youtube.com/watch?v=3yamzOeNDAA

**Pull request closed without merging**
