### PR TITLE
More bundles of patches

### PR DESCRIPTION
**Pull request by langp11**
#### Summary
Content "Add more types of bundles of fabric patches"

#### Purpose of change
We already have bundles of cotton, leather, synthetic fabric and felt patches, so why not add bundles for other fabric types.

Bundles of patches reduce the item count for things that don't stack, so your pile of many, many scavenged Kevlar patches don't need to occupy an entire square.

#### Describe the solution
Copy the existing recipe for 'bundle of synthetic fabric' for each of: canvas, denim, fur, faux fur, Kevlar, lycra, Nomex and neoprene.
Copy the corresponding item definition, adjusting the weight, volume and price(s) based on the existing source item (eg denim_patch)
Add the new recipes to the nested recipe group.

#### Describe alternatives you've considered
Some of the existing bundles (cotton, felt) use 100 items, some (leather, synthetic fabric) use 50. We could make the all the same.

I notices that the volumes, weights and prices of the various source items (patches) seem a bit inconsistent (eg fur patch is over 4 times the weight of denim. It makes sense that it be more voluminous - being fluffy and all - but why is it so heavy?). This seems a larger issue with no dramatic benefit (to me...)

#### Testing
Load game, ensure that the recipes appear in the nested group and can be made.
Check scaling of time, volume, weight and price for batches

#### Additional context
List of nested bundle recipes before:
before bundles
and after:
after bundles

### CODE REVIEW

**Comment by Golfavel** [comment]
See #68417

**Comment by langp11** [comment]
> See #68417

Had not seen that - should this PR get cancelled or get let it ride pending a better long term solution.

**Comment by Golfavel** [comment]
It will likely get closed without merge as the other PR was

**Comment by langp11** [comment]
No problem either way.

**Comment by Maleclypse** [comment]
Sorry about closing this.  I understand the desire to improve the situation but bundles are not working well as is so it's best to avoid them, as you've read above.

**Pull request closed without merging**
