### PR TITLE
font and rasterization improvements for ImGui

### LINKED ISSUE #76420: Properly hint text and improve font rendering.
### Is your feature request related to a problem? Please describe.

I think this screenshot makes the problem pretty clear. We are unable to detect the actual cap height of the text, leading to text being off centre. 
image

Additionally, there is an extra 1px of space before and 3px of space after text (drawn in purple). This is the natural spacing embedded in the font, and it would be nice to remove it. 
Screenshot 2024-09-14 175153

### Solution you would like.

Change the current font rendering stack so that we can support autodetecting the cap height for different fonts and adjusting as necessary See https://github.com/CleverRaven/Cataclysm-DDA/pull/76404#issuecomment-2350813614 for initial direction.

### Describe alternatives you have considered.

Hand adjusting text in all user-visible UIs. Unfortunately, this breaks if the user changes the font, the font size, the font height, the font width, the font rendering mode, etc. 

### Additional context

Naming this issue was hard. The scope is strange, and I feel like the current label isn't very clear about what the actual goal is. I certainly didn't start this with the goal of rewriting the font renderer, but I guess that's what I am doing now.

### PR DESCRIPTION
**Pull request by db48x**
#### Summary
Interface "use Freetype to render fonts for ImGui, and use multiple fonts in the ImGui interface"

#### Purpose of change
Make ImGui use Roboto by default, and the Freetype rasterizer. Load both the configured gui font and the normal monospaced font for use by ImGui. Make item descriptions use the mono font for drawing ASCII artwork. Configure hinting so that Terminus and unifont don’t look awful.

Fixes #76420

#### Testing
Check out the artwork for a pistol or something.

#### Additional context
This is a draft for a reason: I need someone who builds on Windows and/or Mac to give me the right CFLAGS/LDFLAGS for linking against Freetype2

### CODE REVIEW

**Comment by db48x** [comment]
Good questions. Yes, the reason for adding Roboto is that it is a proportional font. We could pick from quite a selection, but Roboto was ready to hand, appropriately licensed, inoffensively styled (not deliberately weird or thematic, or deliberately bad like Comic Sans, etc), and has relatively thick strokes even at small font sizes (which makes it render well even if we stick to the default STB rasterizer which cannot do any hinting). And of course the user can override the choice if they prefer something else.

Apache 2.0 is completely compatible with the Creative Commons license, and it meets the definition of an Open Source license.

**Comment by db48x** [comment]
I guess it builds fine on OSX. Anyone want to give it a try and make sure it works?

**Comment by db48x** [comment]
Weird. It compiled just fine on Windows while it was a draft…

**Comment by Maleclypse** [comment]
It's broken at the macOS build referencing imgui so I'm assuming this isn't a random failure?

**Comment by db48x** [comment]
I wish it were. It's been more than 15 years since I did any development on OSX, and I never had to dig too deep into the build system on that project. I don’t have a Windows machine either. I’d appreciate some help getting this patch to work on those platforms from anyone who has the time.

I spent a little time last weekend trying to find documentation on the subject, but didn’t make much headway. I didn’t really want to spam the CI system with guesses, but on the other hand the only guess I have is to add `-lfreetype` to the `LDFLAGS` and hope for the best.

**Comment by katemonster33** [comment]
@db48x I took a look. does not compile on VS2022. VS2022 does not like your usage of '__attribute__((unused))'. Instead it prefers the C++17 '[[maybe_unused]]'. If we can't use C++17 across the board, maybe consider a preprocessor definition?

**Comment by db48x** [comment]
Oops, sorry about that. It looks like I fixed that last week and then just never pushed it. Must have gotten distracted.

**Comment by db48x** [comment]
A little improvement:
Screenshot from 2024-10-19 01-40-13
Screenshot from 2024-10-19 01-49-23

**Comment by Maleclypse** [comment]
Crap I misread this and thought it was no longer breaking Mac builds.

**Comment by RenechCDDA** [comment]
Hi @db48x I realize this is super, super late... but can I ask what motivated the choice of Roboto-Medium? I just spent a while chasing down what's going on in this menu only to find out that the `|` and `.` characters are simply how Roboto-Medium renders them. (I used [this](https://fontdrop.info/) to compare the characters outside of the game's rendering pipeline)

image

(Side note, the mismatched lines is because we were previously relying on utf8width. I can mostly paper over that: )
image

I don't want to say "Hey, let's change the font again! A year after the last change! (which itself had 3 changes in as few months)"... but it is pretty ugly here. So just looking for your opinion, thanks.


For comparison, unifont looks absolutely great:

image

(It also plays nicely with utf8width!)

**Comment by db48x** [comment]
I gave my reasons [in a previous comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/76529#issuecomment-2359977607).

If you just want the health bars to make an actual column, then put them in the second column of the menu entries. Instead of calling `uilist::addentry`, call `uilist::addentry_col`.

If you want the health bars to look more like bars, might I suggest changing what characters we use? What if we used `██▃▁▁` or `██▍  `?

**Pull request merged**
