### PR TITLE
Add Vital Numbers section to custom sidebar

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Features "Add Vital Numbers section to custom sidebar"

#### Purpose of change

To make it easy to toggle visibility of info formerly shown by the Self-Aware trait, removed in #53802 

#### Describe the solution

Add JSON to define sidebar widgets and layouts for a new ~~"Self-Awareness"~~ "Vital Numbers" section (disabled by default), showing HP numbers for each body part, as well as numbers for pain, hidden health, stamina, and cardio fitness.

#### Describe alternatives you've considered

This could be useful for debugging as well, and I considered naming it the "Debug" section, but for actual debugging I think a full "Debug" *sidebar* would be much more appropriate. For this feature, my objective was to provide an easy way to restore the small quality of life that "Self-Aware" formerly provided, since it was always rather arbitrary.

#### Testing

Use `}` to configure sidebar; switch to "custom" and toggle "Vital Numbers" on.

#### Additional context

image

image

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Please consider further upgrading by color coding the values for better feedback. Thanks in advance.

**Comment by nexusmrsep** [comment]
Also: stamina is extremely important and it's high numerical value, mutable because of cardio, might be less informative then the bars.

Suggested solution: If you have enough space, consider placing a percentage of max stamina in brackets before the number.

**Comment by Terrorforge** [comment]
> Please consider further upgrading by color coding the values for better feedback. Thanks in advance.

Also, the current version of the self-aware health doesn't change color to indicate bleeding/infection. It would be nice if it had that functionality.

**Comment by wapcaplet** [comment]
These are nice ideas, but I am really not interested in doing a big expansion of the "Self Aware" UI in this PR, since I personally think it was a bogus trait to begin with.

I will implement some very basic color-coding for these, but we need quite a bit more work on variable ranges (minimum, maximum, and the concept of a "normal" range, see #54083) before the colors will be coherent and meaningful.

**Comment by Night-Pryanik** [comment]
I suppose "self-awareness" should be renamed to something more clear as it's no longer a name of character trait but rather a name of a widget.

**Comment by Inglonias** [comment]
"Vitals (numerical)" might be a better name?

**Comment by wapcaplet** [comment]
I've renamed it to "Vital Numbers".

**Pull request merged**
