### PR TITLE
APCs tweaks

### PR DESCRIPTION
**Pull request by illi-kun**
Replaces board by stow board for providing the storage area (see snapshot for exact location), and covers driver's place & stow board place by roof (previously, both these places were tagged as "OUT", which is incorrect). 
apc

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Later on APCs should be changed so that the turret is accessible, but for now this is OK.

**Comment by illi-kun** [comment]
@Coolthulhu, did you mean that tile with installed turret should be passable for the gunner?

**Comment by Coolthulhu** [comment]
Yeah. The current manual gun system only works with the shooter standing on the same tile as the turret. Having a board there prevents manual usage.

**Comment by illi-kun** [comment]
apc
Here is modified design for APC: locations of gunner's place & engine section are shuffled, gunner place now contains folding seat and camera control system. Cameras are installed at places pointed by arrows. Is it okay? What do you think about the shape of stowboard between driver's and gunner's places?

**Comment by Rivet-the-Zombie** [comment]
I like all of it!

**Pull request merged**
