### PR TITLE
Automatic Garbage Truck [Github Bugged out]

### PR DESCRIPTION
**Pull request by Wyrdean**
#### Summary
Content "Adds a self-driving capable garbage truck, sort of an upgraded street sweeper."

#### Purpose of change
Cdda doesn't have garbage trucks, so I took it upon myself to fix that. As cdda has an automatic street sweeper, I felt it would be good to make a larger, more industrial version of that.

#### Describe the solution
Adds garbage trucks, which can be found in the city somewhat commonly, on the highway fairly rarely, and rather commonly at junkyards and dumps

#### Describe alternatives you've considered
Not adding them, making them basic boring person driven trucks, or having them spawn in other places; but I feel this is the best solution.

#### Testing
Garbage truck can spawn in, and is drivable

### CODE REVIEW

**Comment by Wyrdean** [comment]
Christ, closing this as github is freaking on on my end. I could not create a pr, anywhere, without the garbage truck inserting itself into it

**Comment by BrettDong** [comment]
Do not make changes on master branch. Create topic branches on top of master branch for your work.

**Comment by Wyrdean** [comment]
Relatively new to GitHub all things considered, unfortunately this time my newness seems to have bit me pretty terribly.

**Comment by LyleSY** [comment]
I've done this several times, it gets easier

**Comment by Wyrdean** [comment]
I've been trying to figure out how to fix this, is there any way I can?

**Comment by anothersimulacrum** [comment]
I just fetched it and did a rebase off of a clean master branch: https://github.com/anothersimulacrum/Cataclysm-DDA/tree/58212

**Comment by Wyrdean** [comment]
Sorry, but could you explain what you did and what it does?
From what I can see on the link you posted the fork is still ahead of the master which means you wouldn't be able to make a new pr without there being issues.

I know now to use branches instead, but I can't figure out how to get rid of these commits ahead of master so that I can actually do anything without them haunting me.

**Comment by anothersimulacrum** [comment]
It's ahead of master because it has the commits you added to it. Branches that are not ahead of master have no changes to PR.
I did:
```c
 // Fetch this PR to a branch called 58212
git fetch upstream pull/58212/head:58212
// change to that branch
git switch 58212
// Take all commits on this branch that are not part of master, put them to the side.
// Reset this branch to master, and then re-apply those commits. 
// Because only the 5 commits you added are not in master, this gets you a branch with those 5 commits.
git rebase master
```

**Comment by Wyrdean** [comment]
So to fix the problem I have, and get rid of the commits that are ahead of master, I follow your instructions there and enter those commands into git? (I might be mistaken but I think you have to use git, to use the command line to do stuff with github?)
I'll have to get git set up, I have it downloaded and installed but it's also been giving me issues, thanks a bunch for your help however.

**Comment by anothersimulacrum** [comment]
They're all git commands, yes. To do that exactly, you will need to have a remote called upstream pointing to this repo, and have a master branch tracking upstream/master.

**Comment by Wyrdean** [comment]
Specifically, the issue I'm having now is that github desktop is failing to find git on my system, despite it being installed and as far as I'm aware, all setup, I hate to ask for more help but do you know a solution to the problem? I've looked it up and tried the solution posted [Here:](https://www.alancoleman.co.uk/blog/2019/02/12/github-desktop-git-not-recognised-when-installed/), but unfortunately it didn't seem to actually do anything to help.

**Comment by anothersimulacrum** [comment]
Unfortunately, I don't know anything more about how to solve that problem, sorry. Github desktop would not be able to work without git, so it is installed somewhere.

**Pull request closed without merging**
