### PR TITLE
Makes Chlormorph an explicit upgrade over Roots/Rooter

### PR DESCRIPTION
**Pull request by OmniscientQ**
#### Summary
Bugfixes "Chloromorph is now an upgrade of Rooter, and does everything Rooter does (and more!)"

#### Purpose of change

Chloromorph now has the LEGS tag, which means a character couldn't have it and the Roots or Rooter mutations simultaneously. However, much of the code obviously expected the root mutations to stick around. After mutating Chloromorph, a survivor lost much of the functionality of the roots.

#### Describe the solution

I simply made Chloromorph an explicit upgrade of the Roots3 mutation, and added Chloromorph to any checks in the code that checked for Roots3. Chloromorph now does everything Roots3 does in addition to its own sleeping bonus.

#### Describe alternatives you've considered

I thought about taking the LEGS tag off of Chloromorph to allow the Roots mutations to stick around. While Chloromorph is not purifiable, the roots are, though, and we wouldn't want someone to mutate their way to Chloromorph and then swap their roots out for a set of hooves. The messages when using Chloromorph clearly assume the roots are still around.

#### Testing

Compiled and tested all roots-based functionality. Chloromorph even adds the speed penalty that Roots3 is supposed to have!

### CODE REVIEW

**Comment by Venera3** [comment]
Instead of hardcoded trait id checks consider turning them into character flags - that allows it to be applied to the bodyparts themselves (or effects/bionics/other traits for mods) and is pretty straightforward.

**Comment by OmniscientQ** [comment]
> 

I'm afraid I haven't dug into any of the new systems yet. I just copied what was already there, since I knew exactly how it was broken.

**Comment by Venera3** [comment]
You only need to declare a static json_character_flag for whatever levels of granularity there are and check them with `has_flag(flag)` instead of `has_trait(trait id)`.

**Comment by I-am-Erk** [comment]
This is basically ready to go and could be merged, and it's a nice PR. @OmniscientQ if you're around, I do think we should use the current modern structure for mutations on this, which should be about two or three lines more code. I will add this to release blockers just because it's so little to get it going.

**Review by I-am-Erk — DISMISSED** [review]
Per Venera's comment I would like this to be done with current json standards and bodypart stuff, as I mentioned abvoe

**Pull request merged**
