### PR TITLE
Remove 30 tile limit on gun range

### PR DESCRIPTION
**Pull request by Eighth-of-Third**
> It's fine to just remove the artificial limit and have it work as in master - just allowing that weird range increase near the end. It's better to keep the old oddities and fix them later than to introduce new ones to fix the old ones, then to fix them in next PR anyway.

I couldn't agree more.

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Didn't you already submit this? #18173

**Comment by Lady-Luck** [comment]
Didn't you already submit this? #18173

I imagine the response you're going to get is going to be the same as last time: You haven't addressed the problems that make the max_range of 30 a necessity for the new system in the first place.

The new system isn't perfect, but it's a lot better than what we had.

**Comment by Izicata** [comment]
That PR was redundant. This one is not. Also, range limits via JSON are already applied. The code for that is in lines 3902 to 3914, literally right above the line of code this PR changes.

**Comment by Lady-Luck** [comment]
So you're saying that this limit doesn't need to be hardcoded because the limit is already specified elsewhere?

**Comment by Izicata** [comment]
I disagree that capping max_range at 30 is a necessity. Weapons already have their own maximum range based on their range and the range of their ammo type. I've already gone on at length about this in #18020.

**Comment by Izicata** [comment]
Also, it looks like I was wrong when I said that the only way to deal with anti-material turrets now is by being invisible. If you have high enough strength and throwing, you can just throw grenades at them from beyond the range of their (and your) sniper rifle. [Image 1](https://i.sli.mg/ZkwPLJ.png), [Image 2](https://i.sli.mg/iwjrZU.png). 14 strength and 10 throwing suffices to be able to throw a grenade 31 tiles; yet more reason to go Alpha.

**Comment by mugling** [comment]
Implementation is incomplete (does not remove all instances of `MAX_RANGE`). Is well known issue, tracked in #18299 and to be resolved by fixing underlying implementation.

**Comment by Izicata** [comment]
>Implementation is incomplete (does not remove all instances of MAX_RANGE).

IIRC the other two instances are the creation of the constant and the use of the constant for experience calculation. Given that experience calculation is not something I'm particularly familiar with, I thought I'd leave that one alone for now. However, I can remove the other two instances if that's what you would prefer. Closing the PR seems like an overreaction to an easily fixed oversight.

Regardless, I don't believe there's sufficient reason for range to be capped even while the range scaling issue exists. The range cap just replaces a scaling issue that the end user might not even notice with a host of other issues that the end user definitely will notice, like .50 cal anti-materiel rifles having the same maximum range as WW2-era assault rifles.

**Comment by mugling** [comment]
> Didn't you already submit this? #18173
> 
> I imagine the response you're going to get is going to be the same as last time: You haven't addressed the problems that make the max_range of 30 a necessity for the new system in the first place.
> 
> The new system isn't perfect, but it's a lot better than what we had.

This is indeed a duplicate and the new system is a marked improvement. @Coolthulhu has outlined some potentially new algorithms. If you want to submit a further PR you do indeed need to address the issue at source. We hack around bugs, not core parts of the game.

**Comment by Izicata** [comment]
>This is indeed a duplicate and the new system is a marked improvement. 

Again, that PR was redundant. This PR is not.
It's a marked improvement marred by an unnecessary range limit.

**Comment by mugling** [comment]
We are going to fix #18299 along with making other improvements to aiming. I don't have anything new to say that hasn't already been covered above

**Pull request closed without merging**
