### PR TITLE
Add 'swamps' as a viable spawn location

### PR DESCRIPTION
**Pull request by pisskop**
Adds in swamps as a viable overmap special spawn location.

This allows for swamps to be a more valuable location.  Anything secret, hunter or hermit based, or otherwise isolated benefits from this.

Locations in the game currently that could/should benefit:

-LMOEs
-Pump stations
-Radio Towers
-Strange Temples
-Fungal Flowers

Locations added by this PR

-Bogs, saltwater ponds.
-Swamp shacks, small buildings that can serve as hunter/hermit cabins.

  A reopening of #19142, after too many overmap.cpp updates compromised its intent.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Something must be wrong here. I can't get even a single bog to spawn, even after turning up their mandatory occurrences so high that I get debugmsgs at start.
Same for shacks and fungal flowers.

**Comment by pisskop** [comment]
I just cloned a copy of the master, stuck in this one line of code, genned a world, and Ive already found one.

And Ive just forced 1 fungal flower to spawn via overmap-special [occurences] and it did.

this works fine.  Would you like me to send you the game folder?

**Comment by pisskop** [comment]
If all I need to do is prove this works and not interfere with established code/spawns then I can do this.  Fungal Flowers can spawn wherever they please; they both however do spawn and it was tested to work.

**Comment by Coolthulhu** [comment]
I couldn't get it to spawn at all. Checked a lot of overmaps. Not a single bog, shack or fungal flower.
Will check later, though I still don't see why would that attempt not work. Undefined behavior? Compiler acting up?

**Comment by pisskop** [comment]
idk.

neither the 'bog' nor the 'swamp shack' are mandatory or easily picked out from the swamp itself.

One is a cyan F and one is a blue F.

If I had to start taking stabs at anything its that there is so little swamp in basegame.  But its been in all the non-modded worlds Ive been spawning.  And all the modded ones Ive been compiling for the last week or so.

**Comment by pisskop** [comment]
Would you prefer I simply prove the addition of swamps work and not force any existing structures to spawn in it?  Ill post a few pictures of the coregame and the fungal flowers.

**Comment by Coolthulhu** [comment]
Any is fine, it's just that last time I tested it I didn't get any dedicated swamp spawns - not the old, not the new.
I probably won't have the time to test it today or tomorrow, but if no one merges it before saturday, I'll test it once again. Could be just compiler being weird.

**Comment by Coolthulhu** [comment]
Had to disable all specials and leave just bogs and shacks to get a single shack (not one bog was generated). Could be pre-existing.

**Comment by l29ah** [comment]
Swamp shacks and swamps themselves draw in exactly the same way in my terminal. How do i change the letter which is used to denote them? I failed to find that via grepping the json's.

**Pull request merged**
