### PR TITLE
Slingshot nerf

### LINKED ISSUE #40605: The repeating crossbows, and other crossbows might be in need of a balance rework
# Describe the bug
This crossbow usefulness is terrible compared to other similar 'tech' weapons in game, for how much you could expect from it and for how much effort you put into getting it.

My defining example, featured in the screenshots, for this is using the [repeating crossbow](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Repeating_crossbow) and with [simple metal bolts](https://cdda-trunk.chezzo.com/bolt_metal). They have utterly pathetic damage for what is a bolt entering zombies flesh. 
The bolts even bounce on fat zombies, which is pretty ridiculous when pebbles from a bullet crossbow somehow go through.
Especially depressing when the target is just a regular [shady zombie](https://cdda-trunk.chezzo.com/monsters/mon_zombie_shady), yet 3 bolts out of 10 still bounce off harmlessly.

Meanwhile, the bullet crossbow takes no skills to craft, is lighter, smaller, has much more range, has basically infinite and lighter ammo because it is rocks, does consistent damage of around 10 to 16 and has the magical ability to go through fat zombies reliably.

In my opinion, it needs a serious skill decrease or a buff to range, damage and some basic armor piercing to be really considered by anyone. 

# Screenshots

image

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Slingshot type weapons were overlooked in the bow rebalance and are dealing significantly more damage than they should.
Also sling and slingshot damage types were incorrect.
Fixes #40605 

#### Describe the solution
Nerf slingshot type weapons since they're only suitable for hunting small game.

#### Testing
Make sure slingshot type weapons can take down various small game.

#### Additional context
https://en.m.wikipedia.org/wiki/Bullet-shooting_crossbow

### CODE REVIEW

**Comment by Barhandar** [comment]
I'd like to note that while real slingshots are very weak, real _slings_ are not, because they toss much heavier projectiles at much higher speed - the limit isn't draw weight of slingshot's string, but instead how fast you can move your arm, tensile strength of the mateiral and the length of the sling itself, and are on the record as being able to knock out helmeted conquistadores. And in modern, video-proof times, they can [noticeably dent steel plates](https://www.youtube.com/watch?v=zd-8MlpfONQ&list=UUNu-O2k4o-AE1U6mw5qRXKg&index=39) among other things.

The sling's description still says it uses pebbles for ammo while the PR makes it use solely rocks.

Additionally, while this is most certainly out of scope for this PR, I think that "clay pebbles" should be changed (because earthenware generally has lower density than stone, approaching 2g/cm3 for higher firing temperatures while rock averages 2g/cm3 and higher for minerals) or duplicated into "clay bullets", rock-type ammo for slings.

**Comment by lbnesquik** [comment]
Maybe just changing ammo types before damage reductions? 
Less than half the damage is a hefty nerf.

**Comment by kevingranade** [comment]
> I'd like to note that while real slingshots are very weak, real slings are not, because they toss much heavier projectiles at much higher speed

Yea I've restored this behavior, sling got switched to use pebbles as ammo instead of rocks at some point, now it's back to rocks.

> The sling's description still says it uses pebbles for ammo

Aha, yes I'll fix that, thanks.

**Comment by EvgenijM86** [comment]
Slingshots can be very different in strength. This one has 148 joules of energy per shot, which is more than enough to cause serious injuries to human body - https://www.youtube.com/watch?v=50jD9klhRPw

**Comment by EvgenijM86** [comment]
They even banned some type of slingshots in Germany (wrist braced slingshots), because they where used by protester and it was a threat to police force. So they definitely have more use than just hunting small game.

**Comment by kevingranade** [comment]
True, submissions of *appropriately rare* high powered slingshots and slingshot manufacturing materials would be very welcome, but the existing slingshots represent very light small game hunting slingshots and that is the rationale for the nerf.

**Comment by EvgenijM86** [comment]
There is not much technology to making a powerful slingshot. You just need a good rubber and some projectile with high density (lots of weight in small space).

The rubber is described here - https://www.youtube.com/watch?v=dGmOkDo7mwg . Slingshot enthusiast seems to prefer **theraband gold** over everything else.
The dense projectiles are just lead balls that you can melt from any lead source in the game.

And once you have those materials you only need to choose how much rubber you are going to use for your character arm strength. If you want to make your slingshot stronger you just add double layers of rubber, or even quadruple layers (if you are some sort of super mutant).

And as you increase your slingshot strength you probably want projectiles with more mass, so that all of that energy is converted to projectile momentum. Because if you add 4 layers of rubber vs 1 layers of rubber - it is not like the maximum possible acceleration will increase. 4 layers of rubbers will stretch at the same speed as 1, but 4x can pull 4x mass to the same speed. Or we can just ignore all those details and make a constant increase in damage as we add more rubber layers (as well as increasing max strength needed to shot it).

The weakest part of the slingshot is its rubber. I read people reporting that on average they can get about 200 to 1000 shots until they need to replace the rubber, depending on how much they stretch the rubber with each shot. I assume that 200 is for maximum power shots.

I will look into how to add new materials to the game. So far I am a newbie when it comes to Cataclysm source code.

**Comment by EvgenijM86** [comment]
The person doing the world record is using 4x Theraban Gold layers. While he is not super mutant it is not easy to shot that slingshot. You will probably tire a lot after doing like 10 shots, unless you have amazing arm strength.

**Comment by ParaplegicRacehorse** [comment]
It should be noted that a Roman-era warrior slinger fired cast-lead bullets of 60-80 grams to ranges of +150 meters with enough force to kill (leather) armored opponents. That bullet is about twice the physical size of a late-19th Century .500 mini-ball rifle bullet. Slings should be changed back to pebbles; and should have option to fire marbles and metal bullets.

Staff-slings have been known to fire 200-300 gram projectiles +200 meters. They have also been known to fire 60-80 gram cast lead bullets +400 meters with enough force to pierce  a body through-n-through after first punching through metal armor; and then getting stuck in the back-plate of said armor. Staff slings should be able to fire everything from marbles and pebbles to hand grenades.

A good slinger does not twirl the thing 'round their head. This costs an enormous amount of time and accuracy for precisely zero gain in projectile velocity. A sling is used more like an atlatl: it's a flexible extension of the throwing arm. Think mini-trebuchet. I have a great deal of first-hand experience with slings and staff-slings.

It is sensible for a sling be skill_used: throwing because it is basically an extension of your throwing arm. When it comes to staff slings, we could argue between throwing and launchers and never come to complete agreement.

I see this is already merged, but I'd really like it to be re-visited.

**Pull request merged**
