### PR TITLE
Add fit-over ice cleats

### PR DESCRIPTION
**Pull request by tornikeo**
#### Summary
Content "Fit-over fit-over ice cleats"

#### Purpose of change

Adds fit-over ice cleats that you can belt over your main boots to reduce chances of slipping on slime. See issue #71615 for more details.

### CODE REVIEW

**Comment by db48x** [comment]
Nice idea. Does it work on ice too? You should add some hobnail boots as well, along with a recipe for making them.

**Comment by tornikeo** [comment]
@db48x  ice isn't a thing in the game for now... is it? :thinking:

**Comment by harakka** [comment]
Universal protection from slipping isn't right. On some surfaces, like ceramic or stone tile, the metal studs should actually make your grip worse.

**Comment by fairyarmadillo** [comment]
> @db48x ice isn't a thing in the game for now... is it? 🤔

It will be, but it isn't currently.

**Comment by BlizzDA** [comment]
I was originally thinking about it looking at Geta and similar footwear, but could it provide some acid protection by minimizing contact with the puddle? It sort of has the similar function, even if it isn't meant for it. (Not that it's currently modeled, IIRC)

**Comment by fairyarmadillo** [comment]
Rubber-soled shoes should be blocking most acid already. They're not, but that's only because soles were added after acid was. I'm in the middle of overhauling acid, so it'll get done.

**Comment by Zireael07** [comment]
As someone who was looking into those IRL recently, those don't work on anything other than ice. Won't help you with slime, and won't help you inside buildings

**Comment by tornikeo** [comment]
@Zireael07  Perkele. Welp, thanks for saving me the trouble. I'll close this now, since there's no other real use for these in the game right now.

**Pull request closed without merging**
