### PR TITLE
Fix throwing

### LINKED ISSUE #20414: Throwing is too good
Throwing got all the buffs that aiming got, but without any requirements to aim.
It also uses the old XP formula, back then when guns were incredibly inaccurate even when aimed. That old formula scales with accuracy. Result is that you can gain throwing 7 before your melee reaches 3 or so.

The only thing preventing throwing from being the ultimate hulk killer is the UI issues of having to re-select the item over and over.
Which is pretty much the worst possible situation when it comes to balancing - balancing with tedium (unintentional, but still).

### PR DESCRIPTION
**Pull request by alanbrady**
#### Summary
```SUMMARY: Bugfixes "Fix OP throwing"```

#### Purpose of change
Throwing is OP on the low end.  A survivor with base 8/8/8/8 stats and zero throwing skill can fend off some zombies with nothing more than a pile of rocks.  This should not be possible.

The end result of the changes here essentially re-orientates the throwing to be more heavily weighted on skill.  This causes a decrease in damage output with zero skill and gives a significant boost to accuracy on the high end, without also increasing damage output significantly.

This PR also slightly changes the throwing dynamic by forcing you to be wielding whatever it is you're trying to throw.

#### Describe the solution
This is a multi-facet solution that is actually more about adding some basic tests and drawing a baseline for the current state of throwing.  We know that on the very low end, throwing is over powered, beyond that there's some flexibility in interpretation and further balancing, but at a minimum we should address this case.

This addresses the problem by first templatizing the `statistics` class.  This allows us to better utilize the great functionality in the class and extend it further.  Most notably we can now gather regression stats on continuous data, not just discrete binary data.  This also reinforces the class with some strictness to help prevent it from being using improperly in the future.

From there, we can create some baseline tests that model the current statistics for throwing.

Once complete, I tweaked the scenario test from range >= 10 down to 1, where it should be thus causing it to fail.  From there I made some small modifications to the core model to then pass the scenario test.  I then needed to redo the modelling tests to reflect the new values.

After fixing the tests, rebalance is complete.

#### Describe alternatives you've considered
More balancing may be required in the future since I did not attempt to do any kind of major overhaul and instead focused on addressing the greatest offender.  However, now with tests in place and better infrastructure for statistics, this should be easier in the future.

#### Additional context
screenshot from 2018-09-06 20-14-47

###### Before
chart
###### After
chart 1

###### Before
chart 2
###### After
chart 3
_*including misses_

Closes #20414

### CODE REVIEW

**Comment by EirenexTheDragon** [comment]
forcing to wield the item would make things like my hand grenade bandolier pr and the already released javelin bag more viable instead of just saving your inventory space, as activating both makes you wield the item anyway.

**Comment by alanbrady** [comment]
Jenkins rebuild

**Comment by cainiaowu** [comment]
Force wielding seems like more keypress for tedium.
We can pop up a menu like the current ammo reloading menu with list of items and different movecosts depend on their locations.

**Comment by cainiaowu** [comment]
Movecost is then calculated as if you wield them first then throwing of course.

**Comment by alanbrady** [comment]
> Force wielding seems like more keypress for tedium.
We can pop up a menu like the current ammo reloading menu with list of items and different movecosts depend on their locations.

You've misunderstood how this is implemented I think.  If you're not wielding something and press 'T' to throw, you will automatically wield it and throw it.  No additional keypresses required.  Now, if you're already wielding something then you need to choose what to do with it, which would be no different than what you're suggesting.

Your suggestion does not improve the number of keypresses required to throw something and the only additional keypress required after this change is if you're wielding something already.

**Comment by logros13** [comment]
While throwing might be in need of a nerf does lowering the damage per attack for a close range low skill character from 15 to 0.9 (a factor 16) and at range 5 from 0625 to 0.015 (a factor 41!) bring it rather to far in the other direction? and that without taking into account the need to wield the items now... Unless there there is some other factor that is not clear from the table this seems to bring throwing from op to completely useless?

With this wont it essentially be impossible to level throwing through actually using it, forcing the player to find a skill book to actually make the skill useful? Well, either that or gaming the system by kiting a zombie around in a circle forever to grind throwing against it...

**Comment by alanbrady** [comment]
> While throwing might be in need of a nerf does lowering the damage per attack for a close range low skill character from 15 to 0.9 (a factor 16) and at range 5 from 0625 to 0.015 (a factor 41!) bring it rather to far in the other direction? and that without taking into account the need to wield the items now... Unless there there is some other factor that is not clear from the table this seems to bring throwing from op to completely useless in the early game?

Your concern is shared and others have convinced me it still needs work.  This is WIP.

**Comment by kevingranade** [comment]
> While throwing might be in need of a nerf does lowering the damage per attack for a close range low skill character from 15 to 0.9

Just to point one thing out, the damage-per-hit is unchanged, the damage number is the average per throw, so when missing a lot it drops a great deal.

The ideal niche for early-game throwing IMO is that you use it to soften up an enemy as it approaches, but have little to no chance of killing it with just throwing attacks.  That is the goal of this PR, because as stated in the description (and the linked issue), the current status quo trivializes early game encounters with zombies as long as you stock up on rocks first.

Later on, it could be used to safely deal with weak enemies at a bit greater than arms length, and soften up tougher enemies, but it should never be a main weapon (at high skill levels a sling becomes somewhat formidable, but it never approaches the effectiveness of a gun).  This PR doesn't do anything for that scenario, it's substantially unchanged.

**Comment by cainiaowu** [comment]
So how does it work in the game? 
Did the player get feedback about the movecost and accuracy like the current firing interface?
Some screenshot please.

**Comment by kevingranade** [comment]
The interface is completely unchanged, this only adjusts chance to hit and the wield on throw thing.

**Comment by alanbrady** [comment]
Jenkins rebuild

**Comment by alanbrady** [comment]
I just realized the way I implemented the wielding thing has problems and I need little bit more complicated solution with how the thrown item gets removed.  The `pos` index can be out of sync after `u.wield`.  Fixing real quick.

**Comment by alanbrady** [comment]
That should do it.

**Comment by alanbrady** [comment]
Neat travis failed on the scenario test.  Apparently more nerf is needed.

**Comment by kevingranade** [comment]
Weird, I'm getting a crash:
Starting program: /home/ec2-user/Cataclysm-DDA/tests/cata_test 
Missing separate debuginfos, use: debuginfo-install glibc-2.26-28.amzn2.0.1.x86_64
Starting the actual test at Sat Sep  8 23:44:47 2018
Can't display menu options, 1 0 available screen rows are occupied by
'  Stop wielding metal tank (60L)?     | Moves  
(snip)
  Stop wielding metal tank (60L)?     | Moves  '
This is probably a bug.


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bbea98 in _nc_printf_string_sp () from /lib64/libncursesw.so.6
Missing separate debuginfos, use: debuginfo-install libgcc-7.3.1-5.amzn2.0.2.x86_64 libstdc++-7.3.1-5.amzn2.0.2.x86_64 ncurses-libs-6.0-8.20170212.amzn2.1.1.x86_64
(gdb) bt
#0  0x00007ffff7bbea98 in _nc_printf_string_sp () from /lib64/libncursesw.so.6
#1  0x00007ffff7bb8660 in vwprintw () from /lib64/libncursesw.so.6
#2  0x00007ffff7bb87f4 in wprintw () from /lib64/libncursesw.so.6
#3  0x0000000000d7a561 in catacurses::wprintw (win=..., text="…") at src/ncurses_def.cpp:110
#4  0x0000000000eba49d in wprintz (w=..., FG=..., text="…") at src/output.cpp:2164
#5  0x0000000000ec25b4 in print_colored_text (w=..., y=y@entry=1, x=x@entry=2, color=..., base_color=..., text="…") at src/output.cpp:130
#6  0x0000000000ec3602 in trim_and_print (w=..., begin_y=begin_y@entry=1, begin_x=begin_x@entry=2, width=-5, base_color=..., text="  Stop wielding metal tank (60L)?     | Moves  ") at src/output.cpp:179
#7  0x0000000001231333 in uimenu::show (this=this@entry=0x7fffffffba90) at src/ui.cpp:577
#8  0x000000000123390b in uimenu::query (this=this@entry=0x7fffffffba90, loop=loop@entry=true) at src/ui.cpp:812
#9  0x0000000001027629 in player::dispose_item (this=this@entry=0x1ddbde0, obj=..., prompt="Stop wielding metal tank (60L)?") at src/player.cpp:7837
#10 0x0000000000fe6cee in player::unwield (this=this@entry=0x1ddbde0) at src/player.cpp:7595
#11 0x000000000102b07d in player::wield (this=0x1ddbde0, target=...) at src/player.cpp:7533
#12 0x00000000004835d8 in test_throwing_player_versus (p=..., mon_id="mon_zombie", throw_id="rock", range=range@entry=1, pstats=..., hit_thresh=..., dmg_thresh=..., min_throws=<optimized out>, max_throws=<optimized out>)
    at throwing_test.cpp:103
#13 0x000000000048a648 in ____C_A_T_C_H____T_E_S_T____13 () at throwing_test.cpp:170
#14 0x000000000043348b in Catch::FreeFunctionTestCase::invoke (this=<optimized out>) at catch/catch.hpp:7298
#15 0x00000000004235f9 in Catch::TestCase::invoke (this=<optimized out>) at catch/catch.hpp:8291
#16 0x0000000000469f12 in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffddb0) at catch/catch.hpp:6852
#17 Catch::RunContext::runCurrentTest (redirectedCerr="", redirectedCout="", this=0x7fffffffddb0) at catch/catch.hpp:6819
#18 Catch::RunContext::runTest (this=this@entry=0x7fffffffddb0, testCase=...) at catch/catch.hpp:6632
#19 0x0000000000431960 in Catch::runTests (config=...) at catch/catch.hpp:6992
#20 0x000000000046fe3f in Catch::Session::run (this=this@entry=0x7fffffffe240) at catch/catch.hpp:7126
#21 0x00000000004330a3 in main (argc=<optimized out>, argv=<optimized out>) at test_main.cpp:162

**Comment by kevingranade** [comment]
Simple fix:
```
diff --git a/tests/throwing_test.cpp b/tests/throwing_test.cpp
index f99cfbbb6e..dfa7e09bb7 100644
--- a/tests/throwing_test.cpp
+++ b/tests/throwing_test.cpp
@@ -65,6 +65,7 @@ static void reset_player( player &p, const throw_test_pstats &pstats, const trip
     p.set_dex_bonus( 0 );
     p.worn.clear();
     p.inv.clear();
+    p.remove_weapon();
     p.set_skill_level( skill_throw, pstats.skill_lvl );
 }
```

**Comment by alanbrady** [comment]
Ah ha, thanks.  Dunno why it wasn't triggering for me, I'm guessing the ordering of tests happened to be slightly different from when I last rebased this.

**Pull request merged**
