### PR TITLE
Gas mask descriptions

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Improved gas mask descriptions"

#### Purpose of change
Gas masks (and similar items) are confusing.  They claim good environmental protection, but their stats are poor.  It's not obvious that they will improve when activated.  It's also not obvious that activating them won't immediately waste all your gas mask cartridges.

#### Describe the solution
Enhance their descriptions in two ways:
* List the environmental protection they will have when activated.
* Explain that cartridges are only used when necessary.

cata-gas-masks
To achieve this I have made it possible for any `iuse` function to have an associated description without having to promote it to a whole new `iuse_actor`.  So far `GASMASK` is the only one using this feature.

#### Describe alternatives you've considered
`GASMASK` could be promoted to its own `iuse_actor` class.  That would also mean that `env_resist_w_filter` could be removed from `itype`.  That might be nice, but on the other hand it would make it harder to show the new "when active" field.

The new description could be pulled out into json, similar to `data/json/flags.json`, but I think it's premature to do that when there's only one example.

#### Additional context
I also added an `iteminfo_parts` flag for this part of the item info, since all the other parts seem to have one already.  Not sure what it's for, but seemed like a good idea for consistency.

### CODE REVIEW

**Comment by AMurkin** [comment]
Will consume *charges*, maybe?

**Comment by jbytheway** [comment]
> Will consume _charges_, maybe?

Yeah, that's probably better.  I've changed to:
`Will consume charges when active, but <info>only when environmental hazards are present</info>.`

**Comment by Pupsi-Mupsi** [comment]
Minor Bug: I noticed while translating that the **firefighter PBA masks** seems to loose some of its enviromental protection when active - at least on paper. **(20 -> 16)**

grafik

**Comment by jbytheway** [comment]
> Minor Bug: I noticed while translating that the **firefighter PBA masks** seems to loose some of its enviromental protection when active - at least on paper. **(20 -> 16)**

Looks like that's because reinforcing improves environmental protection.  I wasn't aware that was a thing.  Thanks for letting me know.  Will look into a fix.

**Pull request merged**
