### PR TITLE
Seperate weather tolerance from stomach related traits

### PR DESCRIPTION
**Pull request by aMegaSloth**
#### Summary
Bugfixes "Separates weather tolerance traits from stomach related ones"

#### Purpose of change
Addresses issue #65330. Seems like to me that being tolerant of weather shouldn't exclude stomach related traits.

#### Describe the solution
Separate the mutation category so they do not conflict.

### CODE REVIEW

**Comment by hr-shafiei** [comment]
thanks, that was my issue
but is that possible to simply fix the trait in a way which it doesnt cancel the other one ?
instead of adding a new mutation type ?

**Comment by aMegaSloth** [comment]
You need to add a new mutation type because as it stands they are in the same mutation 'type' as the stomach related ones as mutation categories are mutually exclusive.

**Comment by hr-shafiei** [comment]
crushes the game !
at creating a new character

**Comment by aMegaSloth** [comment]
Not sure where that crash is coming from. It loads just fine past creation for me.

**Comment by Maleclypse** [comment]
You have errors that will prevent this from being merged on both the new mutations. 
IMG_0136

**Review by hexagonrecursion — APPROVED** [review]

**Comment by anoobindisguise** [comment]
I think Cold Tolerance could have ECTOTHERMIC on it at least though.

**Comment by aMegaSloth** [comment]
I've thought about expanding the category a little with a few more traits, but felt it was out of scope from a simple bug fix. I'll ponder it and probably include additional things in another PR.

**Pull request merged**
