### PR TITLE
Aftershock: Remove several non sci-fi items

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
SUMMARY: Mods "Aftershock: Remove several non sci-fi items"

#### Purpose of change

Removes a handful of non sci-fi items and unnecessary overwrites from the mod.

#### Testing

Game loads

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
I’ve tried to link this to the card “audit old aftershock content” but my phone is having trouble with that part.

**Comment by actual-nh** [comment]
Is there any of this that could/should be moved to non-mod?

**Comment by Maleclypse** [comment]
Rope lighter, chain wrench, and basin could be reworked by someone interested in meeting the requirements set by the devs for them to go in mainline.

**Comment by Mom-Bun** [comment]
Thanks for doing this, appreciated :)

**Comment by Mom-Bun** [comment]
> Is there any of this that could/should be moved to non-mod?

Like Maleclypse said, if a user wants to step up to add this to mainline, they are free too; however this stuff is currently has no business being in aftershock anyway, and was due for an audit for a very long time.

**Comment by actual-nh** [comment]
> Like Maleclypse said, if a user wants to step up to add this to mainline, they are free too; however this stuff is currently has no business being in aftershock anyway, and was due for an audit for a very long time.

They indeed do seem rather out of place, and I certainly agree on their removal from Aftershock. When I finally get around to inserting a few other items, I may include one or more of these (TODO reminder for myself...).

**Pull request merged**
