### PR TITLE
Book mini-overhaul part 1

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

```SUMMARY: Content "Add "classic literature" and "collector's edition" books, move choice book spawns to library, and adjust library/mansion book spawns overall"```  

#### Purpose of change

These book types are missing from the list of possible spawns and would be useful in adding appropriate spawns to mansions and things.  These are particularly useful for replacing basically inappropriate books in mansions that should be exceptionally weird to find in a place like that.

#### Describe the solution

Adds classic literature and collectors edition books that spawn in mansions. These will be much more common than textbooks and books about combat and survival; those books will be more common in libraries.

Given that many things people went to mansions for (in particular rare textbooks and martial arts manuals) are no longer available in mansions, I have moved them to the much more logical home: libraries. Book spawns in libraries are much higher now.

While adding classics to other spawn lists I adjusted some of the associated spawn rates: dojos now have a much higher rate of spawning martial arts books. Lab libraries and bookshelves now spawn only either entertainment books or textbooks relevant to the lab; books on bowmanship and medieval weaponsmithing are exceedingly rare finds in labs now.  I took care to try to maintain the books that are needed to make it through the lab start.

#### Additional context
- These are my first test-run of books with descriptions based on snippets, allowing two book types to have many more titles.
- I plan to replace a lot of the spawns of survival-type books in mansions with these books, and generally increase book spawns of all types in libraries to make up for it.

To-do:
- [x] Add classic literature and collectors edition, with snippet variants
- [x] Test in game
- [x] Add item_groups
- [x] (maybe not this PR) adjust spawning of various books

### CODE REVIEW

**Comment by int-ua** [comment]
How do you plan selecting books when every contributor will want to add their favorite?

**Comment by I-am-Erk** [comment]
Not quite sure what you mean. If people want to add their favourite books to title lists I don't think that's an issue... They just need to do a PR like everyone else

**Comment by Vasyan2006** [comment]
Will reading classic literature cure insomnia? Or character will randomly fall asleep while reading?

**Comment by I-am-Erk** [comment]
Why would reading a good book cure insomnia?

**Comment by Vasyan2006** [comment]
>good book

It is very subjective and depends on a reader. And many readers are not human beings any more, so they should have different reactions. For now only religious and cannibalistic books have different moral effects based on traits. But psychopath don't have empathy and will not get any fun from reading most novels, gourmand and stylish characters should receive bonuses from reading cooking and tailoring books, and so on.
Classic literature is considered by many as something extremely boring, so falling asleep while reading is well known (but not actually real) reaction.
Purely RP stuff.

**Comment by Frost-wood** [comment]
Why are we stipping martial arts books from the dojo?  It’s not a guarantee to find martial arts books in a dojo.

IRL martial arts books arn’t that rare, and a rich person’s mansion is exactly where i’d expect to find a few.

The Mansion is exactly where i’d expect weird, out of place books to be, and now that the mansion has been rebalanced and made considerably more rare, i dont’t see the need to nerf mansions into oblivion.

**Comment by I-am-Erk** [comment]
> Why are we stipping martial arts books from the dojo? It’s not a guarantee to find martial arts books in a dojo.

I'm not, I'm making them more common in dojos by a fairly large margin.
 
> IRL martial arts books arn’t that rare, and a rich person’s mansion is exactly where i’d expect to find a few.

Real life martial arts books also don't give you a matrix-upload-style ability to practice the martial art. They are considerably rarer in cataclysm due to their very high power.

> The Mansion is exactly where i’d expect weird, out of place books to be, and now that the mansion has been rebalanced and made considerably more rare, i dont’t see the need to nerf mansions into oblivion.

This doesn't even come close to nerfing mansions to oblivion, it just reduces one type of loot that can spawn there. They remain quite a high grade loot pinata.

**Pull request merged**
