### PR TITLE
Implement export&import of the protagonist and follower NPCs

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary

Features "Implement export&import of the protagonist and follower NPCs"

#### Purpose of change

This is intended as a replacement for the "character to template" feature as described here #55094. Note: the "character to template" feature will **not** be removed until it is confirmed that this is a satisfactory replacement.

#### Describe the solution

Implement 3 new debug commands:

- Export a follower - exports an NPC from your faction
- Import a follower - spawns a new NPC based on a file and adds her or him to your faction
- Export self - a shortcut to export the protagonist if you don't have a follower to switch to

#### Describe alternatives you've considered

1. I did not add an "Import self" command as it appears to be redundant: the same effect can be achieved with "Import a follower" followed by "Control NPC follower"
2. Export&import of followers is not required to replace the "character to template" feature, but the extra features are useful to me personally (original motivation for this PR). I hope other players will find them useful too
3. I have considered not hiding this in the debug menu, but I can not imagine any way to replace the "character to template" feature that would not be some form of "cheating"

#### Testing

Tried exporting and importing characters - appears to work.

#### Additional context

Please reopen #55094. The button is unavailable to me. :(

This is still raw-ish. There are likely edge cases I have not considered. As we know, devs make poor testers. It would be great if someone who was not involved in writing this tried to break it.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Reopened

**Comment by hexagonrecursion** [comment]
I am considering expanding this: 
- allow exporting any character - not just followers
- let the player choose npc faction when importing

**Comment by RenechCDDA** [comment]
> * allow exporting any character - not just followers

Would the only determination for valid exports be 'they are of the character class'? I think that would be a valuable addition, but I wonder if there are cases where it would be difficult to maintain. (None of this is meant to discourage you, but since you posted about it I assume you to discuss it.)

For example, there's two characters I can think of that have (flavor-important!) EoCs attached. Would the EoCs migrate with them? Would it be *reasonably possible* to do that? (Is it a good idea for the EoCs to follow them? I don't know!) It's one thing to export followers, it's another thing to yoink any NPC out of the world.

Makayla Sanchez (the refugee center arsonist) has... some sort of EOCs which force certain mutant traits to appear on them during portal storms, or something. (It's not 100% clear to me *how this would ever be encountered in gameplay* but it seems very intentional! Going from static NPC --> follower ---> avatar seems like the intended route, and I can see ways this would break if they never became a follower. Link for reference.)
https://github.com/CleverRaven/Cataclysm-DDA/blob/1560777d9d2ad6a3ad5cc429692fb80680e31b1d/data/json/effect_on_condition.json#L408-L411

On the flipside, there's an ancilla bar merc which disappears after you talk to them, this is accomplished by forcing a mapgen update which removes any NPC(?) of that class. I can imagine scenarios where you exported the character previously, the class is inherited, and then mapgen comes along, sees your avatar is technically a member of the character class and you inherited the `BEM_anchor_seller` class, and then crazy stuff happens! (link for reference.)
https://github.com/CleverRaven/Cataclysm-DDA/blob/1560777d9d2ad6a3ad5cc429692fb80680e31b1d/data/json/npcs/robofac/robofac_ancilla_npcs/BAR_ENCOUNTER_MERCENARIES/BEM_anchor_seller.json#L43-L49

And then there's Apis, ~~who has a bunch of hardcoded exceptions~~ apparently is fully json nowadays, but could otherwise produce weird results.

As CDDA continues to take contributions I expect to see *more* cases where content involves bounds and bounds of EoCs and other data attached to characters that is hard to classify or automatically migrate without human intervention.

**Comment by bombasticSlacks** [comment]
This looks good as is, since it's only debug it'll be fun to see what weird stuff most people find.

**Pull request merged**
