### PR TITLE
Several tweaks to the military bunker basement mapgen

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Several tweaks to the military bunker basement mapgen."```

#### Purpose of change
Improving plausibility and risk vs. reward ratio for military bunker basement.

I feel that military bunker basement provides too much loot and poses absolutely no threat to survivor, so I decided to add a defender for this loot.

#### Describe the solution
Added water dispensers, air conditioners and speakers to the basement. Had to move or remove some existing furniture to fit them.
Also added rifle turret right next to the antechamber, so if survivor decides to smash their way into the bunker instead of using id card... well, they'd better think twice on that.

#### Describe alternatives you've considered
Adding a generator, but I couldn't find a place for it.

#### Testing
Spawned location several times.

#### Additional context
изображение

### CODE REVIEW

**Comment by snipercup** [comment]
I like it and your JSON is looking good. Maybe you can alternate between several turret types? Maybe you'd get lucky and find a 9mm turret instead.

**Comment by anothersimulacrum** [comment]
9mm turrets are now makeshift turrets the survivor makes. The `*CROWS*` turrets are the turrets the military would use. So either an m249 or m240 (.50 cal is overkill) turret would be what you'd find in here, if there would be alternates.

**Comment by snipercup** [comment]
The CROWS turrets are rather new so I don't know how powerful they are. I would support a bunch of military zombies as well.

**Comment by Night-Pryanik** [comment]
The problem is that `cardreader` iexamine function at the moment is hardcoded to despawn only the rifle turrets. If there would be any other types, using id card won't despawn them.

**Comment by snipercup** [comment]
So you want to disable the threat if a player gets in by an ID card? I wouldn't be surprised to see military zombies after I swiped an ID card though.

**Comment by Night-Pryanik** [comment]
> So you want to disable the threat if a player gets in by an ID card?

Yeah, exactly that. You have an id = welcome aboard. You don't have an id = you're a trespasser = you'll be shot. 

> I wouldn't be surprised to see military zombies after I swiped an ID card though.

That's another problem, as zombies and turrets are hostile to each other, so most zombies will likely be gunned down by the turret by the moment player steps in.

**Comment by snipercup** [comment]
Can you alternate between zombies and a turret so they don't spawn at the same time? Like 75% chance for turret and 25% for zombies.

**Comment by Night-Pryanik** [comment]
Honestly I'd prefer turret spawning all the time. Zombies don't pose even a remote resemblance to the threat turret pose.
I could have spawned zombies in closed rooms so turret don't see them, but as experience shows, zombies usually destroy all the furniture by the moment player encounters them, and I don't want that.

**Pull request merged**
