### PR TITLE
Added Russian "ё" to remove_accent function

### PR DESCRIPTION
**Pull request by achpile**
#### Summary
I18N "Added Russian 'ё' to remove_accent function"

#### Purpose of change
In Russian language we often use "е" instead of "ё". (not interchangeable). So when an item name has 'ё' the search query should have it either.

And despite what said in `lang/notes/ru.txt`:

> Также не стоит забывать про букву Ё.
> (Do not forget about letter Ё)

Sometimes there is Е where Ё should be.

#### Describe the solution

I added Ё to `remove_accent` function to make it easier for russian players to search 

#### Describe alternatives you've considered

None

#### Testing

None

#### Additional context

Probably needs discussion with russian devs.
I mean if there is a reason it haven't been done earlier.

### CODE REVIEW

**Review by GuardianDll — APPROVED** [review]

**Comment by achpile** [comment]
Not sure how to properly ask for this, but could this also be cherry-picked to `0.H` ? And if yes - what should I do to achieve that?

**Comment by GuardianDll** [comment]
Make a branch out of 0.H branch, and commit it to 0.H
I agree with it

**Comment by achpile** [comment]
> Make a branch out of 0.H branch, and commit it to 0.H I agree with it

Great! I'll do it as soon as this PR got merged.

**Comment by GuardianDll** [comment]
Technically nothing stops you from doing it before the pr is merged :)

**Pull request merged**
