### PR TITLE
[CR]Hungry Hobo: one can one charge

### PR DESCRIPTION
**Pull request by LyleSY**
Removes the concept of "charges" from all comestibles that can appear in cans. This reduces clicks, improves realism, and solves issue https://github.com/CleverRaven/Cataclysm-DDA/issues/18168
Appears to work as intended in my testing.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I don't like this. Why can't my character eat half of the soup, for example, and leave the rest in the can?

**Comment by Cyrano7** [comment]
@Night-Pryanik Agreed, and this would be a band aid fix anyways and wouldn't really solve the issue.

**Comment by kevingranade** [comment]
Not the right fix.

**Comment by Brambor** [comment]
I would just like to add that "fun" is appliable up to three times so the max amount of fun would be tripled by this change :).

**Pull request closed without merging**
