### PR TITLE
Scorpion451's XL Holster

### PR DESCRIPTION
**Pull request by chaosvolt**
And now, we shall make...spaghetti! Er no, we're making a pull request.

Issue where this idea, and code for it, came from: https://github.com/CleverRaven/Cataclysm-DDA/issues/14567

Can further tweak the item @scorpion451 presented to us as needed, unsure yet what else will be good to alter.
- Altered recipe to remove tabs, style tweaks.
- Added draw speed penalty, as Rivet requested.

Unsure of ideal value, literally just started with the back holster and scaled down based off volume capacities. Can tweak further as needed.

### CODE REVIEW

**Comment by mugling** [comment]
`encumbrance` and `draw_cost` seem reasonable but `volume` is arguably too high considering the regular holster, survivor harness and back holster are `volume` 5, 8 and 15 respectively.

To avoid making the other holsters obsolete consider reducing volume to 8-9 (which is still enough for a heavily modded pistol) and/or specifying `max_weight`.

This holster would work better if the shortened barrels mod provided volume reduction scaled appropriately for each weapon. If there's sufficient interest I might implement the ability to (permanently) saw down a gun barrel using a hacksaw as that could provide the XL holster it's own niche.

**Comment by chaosvolt** [comment]
Hmm. Might be interesting. Not sure how to implement barrel sawing without piles of recipes, but would be interesting.

And ah, might work. What's the biggest, beefiest thing that you'd stuff in it, Scorpion? Also unsure ab out what the max weight should be.

**Comment by mugling** [comment]
> Not sure how to implement barrel sawing without piles of recipes, but would be interesting.

Probably via `item::set_var`

**Comment by chaosvolt** [comment]
Also, hmm. Max weight seems to only be used by belt clip items.

**Comment by illi-kun** [comment]
> Not sure how to implement barrel sawing without piles of recipes, but would be interesting.

I think it should be possible to set flag ```BARREL``` (or various ```SHORT_BARREL```, ```LONG_BARREL```) to some weapons by default and remove it by 'a'pplying a hacksaw.

Another option (and more correct from architectural point of view, I suppose) is to add permanent gunmod ```BARREL``` to some weapon. And again, it should be removable via hacksaw action.

The thing we have to keep in mind during the implemenation of this feature is save compatibility.

**Comment by Rivet-the-Zombie** [comment]
This looks good; I'll check it out tonight.

**Comment by chaosvolt** [comment]
> This looks good; I'll check it out tonight.

Hope it goes well then.

And I was thinking an irremovable gunmod would be the most feasible, but also the most hackish and likely to cause bugs (see my additions of the KSG and pipe combination gun for shining examples).

**Pull request merged**
