### PR TITLE
Fixes Plastic Bowl volume.

### PR DESCRIPTION
**Pull request by Rod995**
#### Summary
 ```SUMMARY: Bugfixes "Fixes the inconsistent volume of the plastic bowl."```

#### Purpose of change
Fixes the inconsistent volume of the plastic bowl!
I'm offended, really.
Water doesn't even compress, reeeee.

#### Describe the solution
Changes the volume of the plastic bowl.

#### Describe alternatives you've considered
Letting this *heresy* go by unmolested.

### CODE REVIEW

**Comment by MrHrulgin** [comment]
I disagree with this change. While it may hold .75L of liquid, it only holds liquid when held in someone's hands. When empty, other things in a pack can fit in and around it, and so it doesn't take all of that volume. A set of bowls nested together for storage take up much less space than the total liquid carrying capacity of the stack.

**Comment by paulenka-aleh** [comment]
I might be wrong, but you cannot store "plastic bowl of something" into your inventory or even a vehicle. You have to carry it or keep on the flat surface. While in inventory an empty bowl doesn't necessarily take the space "inside" it by itself. E.g. here's an example how a lot of 200ml plastic cups can take less space while empty: https://partycity6.scene7.com/is/image/PartyCity/_pdp_sq_?$_1000x1000_$&$product=PartyCity/259325

**Comment by Rod995** [comment]
@MrHrulgin IIRC, there's a tag for something to take up more space when it's filled. I might think about using that.
@paulenka-aleh 
I'm not qualified to do volume savings like this, sadly.

**Comment by EirenexTheDragon** [comment]
Right now it also makes water bottles completly useless.
you can make plastic bowl earlier with less skills too. i think its best kept at its old value which was 0.25 liter, but we can keep the .75 version that is not craftable but can still be found outside , while also giving it 0,25 volume ofcourse.

**Comment by I-am-Erk** [comment]
The intent with most bowls is that I assume you don't just shove it into your bag and let it take up 750mL of air, you take the lid off and pack stuff in and around it. I did forget to revisit the size of this when I bumped the storage up though, it should be around 500mL.

Making it take more space when full would be completely reasonable.

**Comment by EirenexTheDragon** [comment]
> 
> 
> The intent with most bowls is that I assume you don't just shove it into your bag and let it take up 750mL of air, you take the lid off and pack stuff in and around it. I did forget to revisit the size of this when I bumped the storage up though, it should be around 500mL.
> 
> Making it take more space when full would be completely reasonable.

like the waterskin basically? if so, i think its best it applys as full when theres just one single portion of liquid inside already, since you dont want to soak the items either

**Comment by I-am-Erk** [comment]
Yeah, basically you'd assume if there's anything in it at all then the volume is 750mL and the container is closed.

**Pull request merged**
