### PR TITLE
Add visual evidence of vomiting

### PR DESCRIPTION
**Pull request by codemime**
Issue: duplicate messages "You throw up heavily!" in painkiller addiction.
Flaw: all messages "You throw up heavily!" go without any visual evidence. Bile seems to be suitable for that purpose.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I like this; it's funny.

Now we really need to add a morale penalty for barfing, since it's a rather miserable experience.

**Comment by Coolthulhu** [comment]
Would be a bit more visual if it vomited on adjacent tile. Vomiting under own feet will hide the puddle until player moves.

**Comment by Night-Pryanik** [comment]
Ugh! I'd like to see this!

**Comment by codemime** [comment]
@Rivet-the-Zombie I like the proposal alot. Barfing shouldn't be left without negative consequences (also, maybe a scent penalty?), but I'd prefer to make it a separate PR, since otherwise it would conflict with #15459 (I moved the `morale_type` enum). What duration and amount of morale penalty would be appropriate?

**Comment by codemime** [comment]
@Coolthulhu You're right. I'll do that right away.

**Comment by Rivet-the-Zombie** [comment]
I think the duration and intensity should be enough that it doesn't just disappear into the morale granted by eating more food to replace what you just lost.

**Pull request merged**
