### PR TITLE
Fixed H&K G80 requires zero charges with effective emitter gunmod

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Fixed H&K G80 requires zero charges with effective emitter gunmod."```

#### Purpose of change
Fix H&K G80 requires zero charges with effective emitter gunmod.

G80's base UPS drain is 5 charges. After installing effective emitter, which reduces UPS drain by 5 charges, G80 doesn't require charges to fire at all. And even if emitter doesn't reduce UPS drain to zero, proportional values for mods seem more natural rather than a fixed one (reduction of 5 is far more noticeable for a 10 base UPS drain weapon (-50%) rather for a 100 base UPS drain weapon (-5%)).

#### Describe the solution
- Renamed `ups_charges` field of the `GUNMOD` item type to `ups_charges_multiplier` and made it float instead of int.
- Made effective emitter reduce UPS consumption by 10% of base value; electrolaser conversion increases consumption by 20%; high density capacitor increases consumption twofold.
- While I'm here, I changed exact date of production (2033) of G80 to vague `first quarter of 21st century`.
- Also I think G80 isn't an electromagnetic weapon as is and thus shouldn't have an emitter gunmod slot, so I removed it.

#### Additional context
With a new emitter, G80 will consume 4 charges instead of base value of 5.

### CODE REVIEW

**Comment by Maddremor** [comment]
I though someone would notice the same deal with the coilgun first. Rest in peace noble cheese.

**Comment by Night-Pryanik** [comment]
Thanks for the tip. Removed emitter gunmod slot from coilgun as well.

**Comment by Maddremor** [comment]
Well, the coilgun is an electromagnetic weapon, but it could previously be reduced to zero power consumption.

**Comment by Night-Pryanik** [comment]
> the coilgun is an electromagnetic weapon

By "electromagnetic weapon" in this particular case I meant "something that inflict damage directly by electromagnetic waves, such as laser". Neither railgun nor coilgun fit this description.

**Pull request merged**
