### PR TITLE
Mainline the makeshift crossbow from More Survival Tools.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary: Content: "Adds the makeshift crossbow from More Survival Tools to base game".

Added the makeshift crossbow from More Survival Tools to base game.

#### Purpose of change

In light of darktoes' Archery Rework in #28069, I thought it would be good to give players a weak early-game crossbow.

#### Describe the solution

This simply adds the makeshift crossbow to the base game.

#### Describe alternatives you've considered

Enabling More Survival Tools every time I make a new world.

#### Additional context

If the stats need adjustment, I'll be happy to take advice regarding that, as well as help with the pull request itself.

### CODE REVIEW

**Comment by Xenomorph-III** [comment]
I'm not sure why this is conflicting. Can someone help?

**Comment by Night-Pryanik** [comment]
Don't you forget to remove the crossbow and the recipe from the MST?

**Comment by Xenomorph-III** [comment]
Let me check. 

I accidentally pasted the crafting recipe into `data/json/items/ranged.json`. I'll see if I can delete it.

**Comment by Night-Pryanik** [comment]
Also, you shouldn't make changes in your `master`. Create a separate branch for every PR.

**Comment by Xenomorph-III** [comment]
> Also, you shouldn't make changes in your master. Create a separate branch for every PR.

Noted. Managed to make another branch. I'll have to try again.

**Comment by Night-Pryanik** [comment]
I advice you to close this PR, make a separate branch, make your changes in this new branch, and then make a new PR from your new branch.

**Comment by darktoes** [comment]
I've actually already got a number of ideas for makeshift crossbows. You're welcome to do this regardless, but bear in mind I will probably completely re-balance it in my coming PRs.

**Pull request closed without merging**
