### PR TITLE
add ellipsis pref to style manual

### PR DESCRIPTION
**Pull request by Jerimee**
#### Summary
```Summary: None```

### CODE REVIEW

**Comment by I-am-Erk** [comment]
As discussed elsewhere, I pretty strongly disagree with this being a preference, since it's not readily accessible from most JSON editing tools like notepad++.

**Comment by Jerimee** [comment]
@I-am-Erk I remember you saying that. Me personally, I don't care what the standard is, so long as it is consistent. I think currently the JSON validation script will fail if you have "..."

I don't know if this counts as "readily accessible" (I suppose it doesn't) but as you likely know the character insertion tool in Notepad++ is edit - > Character Panel (and then ascii 133).

**Comment by I-am-Erk** [comment]
The JSON validation probably won't fall on "..." since using periods in mapgen is extremely common.

I know it's possible to add ”…" as a special character, but that's a pretty big pain in the butt when trying to type dialogue, for no real benefit.

**Comment by Qrox** [comment]
> The JSON validation probably won't fall on "..." since using periods in mapgen is extremely common.

Actually the clang-tidy check currently fails on "..." in a subset of the translatable JSON strings. And in my personal opinion it's not that much of a hassle: you can always type the dialogue using three dots, and change them to the ellipsis in a final commit.

**Comment by DaviBones** [comment]
Hmm, what if I (or somebody else, if they want) added a `...` to `…` to the linter? Would that help? @I-am-Erk

**Comment by I-am-Erk** [comment]
You'd have to make it distinguish between any time "..." appears in mapgen

**Pull request merged**
