### PR TITLE
MShock Modded Tileset Series 16

### PR DESCRIPTION
**Pull request by chaosvolt**
Well, back to something I can do properly, this time. Among other things, re-added some long-since-dummied-out sprite assignments now that a mod re-added pipe SMGs, and partial progress on spriting dinosaurs.

Changes:
- Darkened the exposed bones of zombears, antlered horrors, and decayed pouncers to a similar extent as that of zombie dogs and grim howlers. Claws and teeth remain bright.
- Removed anomalous patch of blur in a random empty spot of the cordless drill's sprite.
- Gave generators and gas station tanks actual sprites.

Sprite assignments:
- Pipe rifles (.38, .45, .44, .40)
- Pipe SMGs (.22, .38, .45, .40, 9mm)

Sprite additions:
- Dazzling effect
- Compsognathus
- Gallimimus
- Titanis
- Spinosaurus
- Tyrannosaurus rex
- Triceratops

### CODE REVIEW

**Comment by Midaychi** [comment]
Is it just me or is there no sprite for the big gasoline tank at automated gas pumps?

**Comment by chaosvolt** [comment]
Oh right. I've been meaning to give gas tanks and generators proper sprites sometime. When I get home, if this hasn't been merged I'll work on that.

**Comment by Mshock777** [comment]
Can I make a request: can you make bones on zombie bear/moose grey like on zombie wolf/dog.
Also there is a weird spot on a cordless drill.

**Comment by chaosvolt** [comment]
Could be done, I guess. Hmm. Weird spot? I've noticed that lots of the older sprites have fuzzy bits, yeah. In most cases I've tried to be consistent about giving newly-added sprites a clear border, like how most of the 32 sprites are.

**Pull request merged**
