### PR TITLE
Water purification tablets only purify up to 4 water each

### LINKED ISSUE #71818: Water purification tablet. Wrong work?
### Describe the bug

I noticed that with one tablet, you can purify any amount of water. For example, a 200 liter barrel.

I'm assuming that's a mistake. Since the description and recipe say one tablet per 250 ml of water.

By the way, the recipe from the crafting menu, doesn't work.

### Attach save file

N/A

### Steps to reproduce

1. Create a character and a world
2. Go to a water source, such as a river
3. Create a Water purification tablet
4. Create a 200 liter barrel
5. Open the crafting menu, make sure the "pure water" recipe is not available
6. Fill the container with water
7. Activate the tablet
8. See the result

### Expected behavior

I expect the tablet to work as written will match the description.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 45fcb0e [64-bit] - cdda-windows-tiles-x64-2024-02-18-0606
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Not quite on topic. I would prefer if the tablet was remade similar to the washing kit.

A menu in which a container is selected and the number of tablets is calculated from its volume. After which the water is purified, without the participation of the character. Something like: throw a tablet into a container and wait a certain time.

### PR DESCRIPTION
**Pull request by ZeroInternalReflection**
#### Summary
Bugfixes "Water purification tablets purify 1-4 water each"

#### Purpose of change
Attempt 2:
Water purification tablets do not appear to be modeled on any specific real-world item and behave in unexpected ways:
1. `a`ctivating the tablets will purify any amount of water selected, and
2. The "clean water" crafting recipe lists water purification tablets as an option, but can't actually use them in crafting
Fixes #71818 

In addition, there are some odd behaviours related to activating/examining/consuming comestibles that I needed to fix to get this working satisfactorily:
1. If you `e`xamine a water source, select the "consume" option, then back out (e.g. because you decide the toilet tank water is too gross, or because you're full), a unit of water is still consumed from the source
2. If you `a`ctivate water or certain other comestibles (such as alcohol), it will immediately consume all charges rather than only one

#### Describe the solution
1. Pick the 49mg [Aquatab](https://aquatabs.ca/products/aquatabs-water-purification-tablets-49-mg-canadian-pack) as a reference item for behaviour (this is a smaller version of the brand linked by Rokharn below, designed for hiking/camping, which I think is likelier to be the more common style in New England)
3. Split the tablets out to a new iuse function that figures out how many tablets are in your crafting inventory and using them rather than trying to use charges of an uncharged item
4. Add a new recipe for using the tablets from the crafting menu where the tablets are a component rather than a tool (tools expect charges, and there doesn't seem to be a way to require a tool _or_ a component)
5. Add a new water_purifying item that, after 40 minutes, can be activating/consumed to turn into clean water.
6. Document the usage instructions for the equivalent real tablets in the pur_tablets json so we know what we're abstracting

Tasks remaining:
- [x] Figure out why you can, in-game, turn "purifying water" into clean water immediately when it's in a toilet tank
- [x] Increase spawn of the tablets? (I believe they currently spawn in groups of up to 15, but the real-world tablets are sold in packs of 50)
- [x] Define the water:tablet ratio in json (This could use a second set of eyes, as it doesn't look like many items use this feature)
- [x] Fix consumption of water via `a`ctivation
- [x] Fix handling of consuming water_purifying via `e`xamination

#### Describe alternatives you've considered
 - Restoring charges to pur_tablets
I think this is how they originally worked, but initial testing didn't seem promising
 - Removing the activation from purification tablets
I was sorely tempted, but then you can just `E`at the tablets to do nothing, which is less than ideal
 - Expanding water quality into clarification/etc
Not today.

#### Testing
**In-game testing:**
1. Crafting clean water using the tablets works in a 1:4 tablet:water ratio
2. `a`ctivating the tablets uses 1 for up to 4 water in the container selected
3. `a`ctivating the purifying water 40 minutes later turns it into clean water
4. `E`ating the tablet leads to the `a`ctivation route and works
5. `E`ating the purifying water leads to the `a`ctivation route and works
6. `a`ctivating six tablets will turn a toilet tank to water_purifiyng, which becomes clean water after 40 minutes
7. `e`xamining a toilet tank or tank full of water allows you to back out after selecting "consume"
8. `a`ctivating various food/drink items follows the same route as `E`ating them, and adds the appropriate nutrients to the player's stomach
9. Both existing and new pur_tablets work, though existing ones don't have the variable pulled from json

**Unit testing:**
 - A variety of combinations of water and tablets in your inventory and sitting around nearby.  Yes, every single one of those combinations broke on a previous iteration of the iuse action, why do you ask?
 - water_purifying turns in water_clean after 40 minutes and not earlier, even if the water is old
 - Using purification tablets on water known to cause food poisoning results in water that doesn't cause food poisoning
 - Changing `a`ctivation to use the consume_activity_actor broke one of the eoc unit tests, since the eoc was structured to expect the character to immediately get the effects from consuming the item.  I think my modification still fits the intent of the test

### CODE REVIEW

**Comment by Rokharn** [comment]
Interesting moment, most of real world water purification tablets not works instant, but takes time (from 30 min to 4h). Mostly something like 1-2 tablet for 5-10 liters depending of water quality.
For example https://www.cdc.gov/healthywater/pdf/global/posters/11_229310-o_aquatabs_blue_print-africa.pdf
So I am not sure, what source of ingame description of this item. Cannot find prototype from our world, which worlds with just a 250 ml of water per tablet.

**Comment by ZeroInternalReflection** [comment]
I've been doing some digging trying to figure out the origin of the stated 1:250mL ratio, and can't find any documentation behind it, so I don't know if there was a particular 'model' of tablet in mind.  The description change was way back in #5586, and the tablets themselves were added back in 2013: https://github.com/CleverRaven/Cataclysm-DDA/commit/a6b5cd0455caba546c0542ca5658779fd3feb39a. The clean water recipe json lists references for purifiers and charcoal filters, but nothing for tablets.

Changing the ratio of tablets:water is (probably) pretty simple if we want to point at a specific tablet like that.

Having the transformation take time makes sense from a 'realism' perspective, but a previous attempt apparently fell apart: #39973.  I believe there's infrastructure to turn the water into an item that can be `a`ctivated into clean water 30 minutes later, but I'd have to look into the code for that.

**Comment by Rokharn** [comment]
> I believe there's infrastructure to turn the water into an item that can be activated into clean water 30 minutes later

Something like fermentation tank mechanics? Sounds pretty similar at least on code logic. I could be wrong, but it seems that we once had large carbon water filters with similar mechanics (but not sure here, in another fork or in mods).

Anyway, I think 1 to 250ml per unit will make tablets mostly useless with current spawn numbers of this kind of items. With this changes needs some re-balance as well, imho.

**Comment by PatrikLundell** [comment]
A delay process would be good.

In progress items are weird for liquids, though. Back before someone informed me that you could purify water passively with fire I had manual water purification being broken off a lot, resulting with in progress items.

Note that an increase in the amount of water a tablet can purify shouldn't make it mandatory: an early game character may only have access to one or two bottles, and demanding that they'd have 10 (or whatever number) before they could start to purify the water would be bad.
For a similar reason, I think it would make sense to allow a player to purify the water in their starting container, such as a toilet tank. I suspect an interaction might be capable of performing an "up to" calculation that the recipe rigidity doesn't allow for.

**Comment by ZeroInternalReflection** [comment]
The notion | have at the moment (pending sifting through the code for transforming items) is:
1. via crafting/activating, turn the tablets and water into a "water (purifying)" object
2. The crafting action should be brief, so that the player can go do something else (and you're unlikely to end up with an 'in-progress' craft for 'drop the tablets in the water')
3. The "water (purifying)" is either not consumable or is equivalent to drinking regular water (the first is probably easier, but I somehow see someone complaining about it)
4. After 30 minutes (unless someone finds a better reference for water purification tablets that are faster/designed for smaller volumes), the "water (purifying)" can be activated to turn it into clean water (automatically might also be possible, but I'm not sure)

If we specifically reference the aquatabs that Rokharn found then I'd rework the tablet:water ratio.  However, there's probably also a minimum recommended ratio.  The link gives "8-10L" and "20L if clear", but is pretty insistent on the 'do not swallow tablets' thing, and they may not be suitable for use in, e.g. a 500mL water bottle.
It would (probably) be fairly straightforward to set up the logic so that one tablet purifies a minimum of 5L and a maximum of 20L.  And if that's the logic, then I'd make sure to include tests for it, including one of "the player dropped a tablet in a toilet tank"

To think I only touched this to fix the crafting recipe so I could continue with #60417...

**Comment by Rokharn** [comment]
> to turn it into clean water (automatically might also be possible, but I'm not sure)

For example water, heat and time can automatically turn 'water' into 'clean water' already, mostly same thing, I think. Aftershock ice can be turned into water at similar way.

Another example of similar sounds mechanic (currently ingame) is 'sauerkraut' and 'wild yeast'. Using some components and container sealing recipe, after some time we can get complete new item or items. This one might work better.

**Comment by PatrikLundell** [comment]
I think the sealed container recipes suffer from a standard problem with recipes; namely that the container is a fixed part of the recipe result, so while you can vary a container input item through a list of alternatives, the resulting product is always going to be in the same fixed type of container.

**Comment by ZeroInternalReflection** [comment]
Alright, this is most of the way to "put in the tablets, walk away, and come back half an hour later to clean water".  The tablets create "water (purifying)" which is not yet consumable, but can be transformed into clean water 40 minutes later.  The transformation uses the existing mechanism used for sourdough starters and was surprisingly easy to set up.

It also _almost_ works in a toilet tank, but some more testing and debugging is still required, so I've marked it as draft for now.

**Comment by ZeroInternalReflection** [comment]
I'm calling this one ready for review.  There are still a variety of water-quality-related issues, but this PR is already complicated enough.

There are also a couple of bits I'm not sure about, particularly how I go about pulling the water_per_tablet variable  from json and the use of test_mode in iuse.cpp, but at this point it needs another set of eyes.

**Comment by Inglonias** [comment]
This looks super cool. I like it!

**Comment by RenechCDDA** [comment]
Needs a rebase for clang and some minor touch-ups to switch over to mod_moves instead of touching moves directly.

**Comment by Maleclypse** [comment]
@PatrikLundell  sorry to bother but when I resolved conflicts on this stale PR it looks like some mapgen changes since then have changed how this should have been written.  If you have any suggestions on how to fix it I would greatly appreciate it.  If not and I was confused about the cause, my apologies.

**Comment by PatrikLundell** [comment]
I assume you're referring to test failures (at least something in the first one seems related to my changes)?

I'd need some help, in that case. In order to examine and modify the code in a sane manner I'd need to know how to download it and then push the modified code up again onto the same branch (assuming, of course, it could be fixed). I can get master and my own branches down, but I don't know how to "name" someone else's as I assume the branch name isn't global.

**Comment by mqrause** [comment]
> In order to examine and modify the code in a sane manner I'd need to know how to download it and then push the modified code up again onto the same branch (assuming, of course, it could be fixed).

The easiest option is probably to add ZeroInternalReflections fork as a remote, then you can just pull the branch this PR is based on. Though I doubt you'll have the permissions to push directly back to it. But if you push your changes to your fork and then make a PR to their branch on their fork, Maleclypse might be able to merge that.

**Pull request merged**
