### PR TITLE
Header include cleanup (2018-11-06)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Cleanup unused and duplicate includes. Sort includes alphabetically. Modernize includes.

#### Additional context

Also includes changes from #26548.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
@narc0tiq: I don't get what's wrong here - http://gorgon.narc.ro:8080/job/Cataclysm-PR-Builder/10043/console. Makefile on Jenkins differs from the one on repo? Somebody fixing MacOS builds right now?

**Comment by narc0tiq** [comment]
Very possible, I just created @veid's user -- he [offered to help fix the osx builds](https://github.com/CleverRaven/Cataclysm-DDA/issues/23171#issuecomment-435189078) some time ago.

**Comment by narc0tiq** [comment]
I've reverted the change, so **Jenkins rebuild**.

**Comment by Veid** [comment]
@ZhilkinSerg @narc0tiq Yes, that was me. I was testing a macOS build. I'm about to create a new pull request to fix the crashing macOS builds.

**Comment by narc0tiq** [comment]
@Veid No worries, we'll fix it. Jenkins might be spotty for a few minutes, though, as I'm running package updates.

**Comment by ZhilkinSerg** [comment]
Thanks, @narc0tiq! Can you please also check this when you have some spare time - http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/8128/console?

**Comment by Veid** [comment]
@ZhilkinSerg I've fixed this

**Comment by ZhilkinSerg** [comment]
Thanks.

**Pull request merged**
