### PR TITLE
Faction camps store, track, and consume vitamins

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Features "Faction camps store, track, and consume vitamins"

#### Purpose of change
Despite the introduction of vitamins and their deficiencies several years ago, NPCs have been languishing without attention. Camps use calories to pay for construction and crafting but they just vanish. You can stuff all sorts of weird things into the larder and it just ignores all the downsides of e.g. an all-alcohol diet.

#### Describe the solution
This is not a full solution, as calories spent on *work projects* still vanish into the ether.  This PR is just a huge infrastructure change before I can even start to do that. Things this DOES do:

-Adds vitamins appropriately when food is distributed

-Retains those vitamins over save/load and as new food is added to/removed from the larder.

-Removes a proportional amount of vitamins when kcal are deducted from the larder.

-*Returns that value* as a nutrients struct. Right now this is only used in one place but the infrastructure is there for your workers to eat properly

-Because the drain of vitamins is proportional to consumed kilocalories this means that if you stuff your larder full of toxins you'll be pulling toxins right back out whenever you eat from it. With all the appropriate effects. You still can stuff mutant meat in the larder... but you'll be paying for it just like if you shoved it down your own throat.

-As of this PR the only time vitamins are actually pulled from the larder and put into a character's stomach is when a hungry NPC eats from the larder by being near it. This is not the same thing as NPCs consuming(vanishing) calories when they are assigned to work.

There is not currently a non-debug way to view the vitamin contents of the larder.

#### Describe alternatives you've considered
We could just delete the larder entirely but I think it's a necessary *and good* abstraction, although it needs even more work than this.

#### Testing
In a completely empty field I stripped an NPC of all their belongings, debugged them to starving, and then magic'd up some protein rations and put the rations into the larder. Then I waited until they ate from the larder.

Some time later, after their body was able to start absorbing the food...
image

#### Additional context
That default mod is going away sooner or later. Prepare your salt

Known issues:
`calories` in the nutrients struct is a 32-bit integer, and can be overflowed. After this PR camps have a practical limit of ~2.1 million kcal (about 178 worker-days worth of food at EXTRA_EXERCISE). Changing that to a 64-bit integer will take some careful work as the nutrients struct is more widely used outside of camps.

`calories` as defined by a faction template is now actually calories. Previously it was **kilocalories**. This means that factions have 1000x less food available to them. However the docs already indicate that it's supposed to be calories and this has no current ingame effect, so nothing further has been done for this. In the future as we add basecamp support for NPC factions they will need to have this looked at.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I commonly supplement my character's food with mutant meat under the daily limit, which prevents the worst effects but lets me stretch my reserves of high-quality food for longer. It would be nice (maybe out of scope for now) if the game could proportionally track the number of calories in the larder which were tainted by toxins, and NPCs could try to eat under the daily limit as long as other food was available.

A similar issue shows up with vitamin C. it would make sense to ration it so your friends don't eat all the orange preserves on day 1 and then get scurvy a month later because the only other thing in there was dog meat.

The dream would be to set up rationing rules and store larder items in a more complex way, but I'm not sure how possible any of that is.

**Comment by RenechCDDA** [comment]
This is effectively already the case, since the vitamins will be consumed in proportion to available kcal. If you aren't storing lots of toxins, you won't take lots of toxins out. You can dump a week's worth of toxins into storage, but if you already had a year's worth of food, it won't matter.

**Comment by fairyarmadillo** [comment]
Oh awesome. That works.

**Comment by PatrikLundell** [comment]
I'm not sure this will work.
The problem is that the calorie requirements of a character is dynamic, depending on the activity level, while the vitamin ones are static. If the storage content is converted into an average, we may get in a situation where companions on guard duty suffer from deficiencies because that average is too low, while the ones tasked with mining get far more vitamins than they need because of their huge calorie consumption.
Also note the hysteresis in a poor vitamin quota in the store can get large, so when you notice that your companions are getting unwell you're then in a hurry to get large quantities of food with a very high concentration of the missing vitamin to affect the average.

I don't have any good solution to the problem.

A bad one would be to actually keep track of everything dumped into the storage and have auto consumption select items based on expiration date and calorie/vitamin needs, so they'd start with food high in the vitamins they need and then top up with calories over the course of the day. That, however, risks causing lag. Also, you'd probably want to go the full way in that case and designate actual storage as camp storage (which basically would act as auto eat/drink for companions).

**Comment by fairyarmadillo** [comment]
We could just do away with the abstract pantry. Since the system was coded, we've added a lot of stuff that's more dynamic than "good food" and "bad food" - characters can be saprovores, they can be cannibals, they can be vegans or have grain allergies or be mutant meat-tolerant. 

We might instead create pantry zones which could include things like freezers and refrigerators. NPCs aren't constantly eating, so the game would only need to think about what to feed them when paying out after jobs or at mealtime.

**Comment by PatrikLundell** [comment]
If it can be done at a reasonable performance cost I would prefer a switch to pantry zones. It would, however, also require an investment in the coding of eating logic (including potential extras such as sweet teeth over eating into obesity and alcoholics getting wasted) to make sure food is consumed in a reasonable manner in terms of expiration dates and nutritional needs.

**Comment by RenechCDDA** [comment]
> If the storage content is converted into an average, we may get in a situation where companions on guard duty suffer from deficiencies because that average is too low, while the ones tasked with mining get far more vitamins than they need because of their huge calorie consumption.

Yeah that's uh... that's how eating already works, for the player as well.

If it turns out that eating is somehow imbalanced and you can't actually get a balanced diet at base metabolic rate then 1) that means our vitamin values are broken, 2) that means it should be fixed there, and 3) if for some reason it isn't fixed there I can just allow you to put multivitamins and other non-calorific comestibles into storage

You also retain the option of giving NPCs multi-vitamins and food directly, as currently exists.

This is not the one-stop solution to turning NPC needs on. It's a step on the way there, but there is more to be done.

**Comment by fairyarmadillo** [comment]
> Yeah that's uh... that's how eating already works, for the player as well.

The player isn't mixing all of the food that they have in a blender and consuming that for every meal for the rest of their life. They're eating individual items which will have wildly different nutritional balances than that.

Picture for example a situation where a player distributes 10000 wasp jerky at the faction camp, or accidentally drops some mutant tallow. Now all of the food is tainted with mutant toxins and there's no way to get the NPCs to not poison themselves when they eat out of it except to go find a billion corn cobs to dilute it, which doesn't make logical sense. This goes double if we add vitaminosis for iron, and also doesn't address the fact that going "oh all my guys have scurvy" and dumping a handful of oranges into a pantry that has 200000 kcal stored in it will only increase the stored vitamin c by a fraction of a percent.

I don't think most of those problems are addressable without doing something that would require reverting this PR, and I think the fact that the pantry ignores dietary restrictions, addiction counters, and so on is a big deal, so I question whether you want to move forward with it at all.

**Comment by RenechCDDA** [comment]
>Picture for example a situation where a player distributes 10000 wasp jerky at the faction camp, or accidentally drops some mutant tallow. Now all of the food is tainted with mutant toxins and there's no way to get the NPCs to not poison themselves when they eat out of it except to go find a billion corn cobs to dilute it, which doesn't make logical sense. 

Yes that's the point.

Don't put toxins into storage if you don't want to eat toxins. 

You put aside a food supply for the winter and it contains 1000 wasp jerky, you will be eating that wasp jerky sooner or later. **That is explicitly the point.** The way you draw it down is *uniform*, but other than that it's the exact same intake you would be consuming with the regular items. If you put only 100 wasp jerky in, you'd(with 1 eater) be effectively eating 1 wasp jerky/day for the entirety of winter. If you want to eat the wasp jerky, you are getting the toxins, there is no way around that. You cannot selectively avoid consuming the toxins as the toxins are part of the food. The food that you are eating.

>This goes double if we add vitaminosis for iron, and also doesn't address the fact that going "oh all my guys have scurvy"

Vitamonisis is not being added and I do not need to accommodate future hypothetical changes to the vitamin system unless there is some indication that it will be happening.

>dumping a handful of oranges into a pantry that has 200000 kcal stored in it will only increase the stored vitamin c by a fraction of a percent.

Again, this is the point! You have tons of abstract food to eat and only a tiny bit of vitamin C. The camp larder is long-term abstracted food storage, if you have a short-term crisis and you shove stuff into the larder saying "Well, I'd like to plan ahead" then the game will ration it for you. If you want a lot of vitamin C being dispensed with every meal, stock it with lots of vitamin C.

Again I will remind you that you retain the option of manually distributing food. If you are playing at a scale where that idea bothers you, that's exactly why we need the abstracted larder system.

**Comment by PatrikLundell** [comment]
Both toxins and vitamins operate differently from calories. You need a certain amount of vitamins and can tolerate a certain amount of toxins, while calorie need scales with exertion. I'm not even sure there is a way to handle the blender goo apart from discarding a lot of calorie dense food because it contains too few nutrients to ensure it's nutrient rich enough to serve as a idle activity diet, which doesn't seem like a sound logic to me.

Requiring that the player plans ahead with the nutrient store by ensuring it's balanced in all aspects creates a noob trap where a stocking mistake can destroy the camp system for that game because it's so hard to recover from that mistake. The fact that the non store system can be used to work around stocking mistakes is not a good argument.
Requiring micro management of the nutrient store also largely defeats the purpose of having it.

**Comment by RenechCDDA** [comment]
Listen. If this all gets in to working order, NPC needs are enabled\*, NPCs being affected by toxins is a real problem\*, the workers actually get the vitamins\*, (\*all of which this PR will not do!) and then we find out players commonly manage to stock only food without vitamins, despite their player character having *the exact same needs*... then at that time I can add an actual-noob-trap button to dump your larder. That is like, 5 minutes of work.

Players are able to manage their PC's consumption just fine.  It is rather silly to think they cannot handle it for NPCs.

**Comment by fairyarmadillo** [comment]
The food probably needs to be tracked individually solely because you can have four NPCs who are allergic to wheat and nothing in the larder but bread, and they'll eat it just fine with no penalties.

**Comment by RenechCDDA** [comment]
And if for some reason you still believe this will destroy the game, here is a simple patch you can use in the future to turn it all off, if for some reason all our C++ contributors have been hit by trucks:

```diff --git a/src/faction_camp.cpp b/src/faction_camp.cpp
[fake hash, commit this manually if needed]
--- a/src/faction_camp.cpp
+++ b/src/faction_camp.cpp
@@ -636,7 +636,7 @@ nutrients basecamp::camp_food_supply( nutrients change )
-                return consumed
+                //Make new empty struct
+                nutrients given_to_npc;
+                //Return empty struct to indicate nothing was consumed
+                return given_to_npc;
```

**Comment by RenechCDDA** [comment]
> The food probably needs to be tracked individually solely because you can have four NPCs who are allergic to wheat and nothing in the larder but bread, and they'll eat it just fine with no penalties.

Not handled with the vitamin system.

**Comment by RenechCDDA** [comment]
After a ~2-hour evening detour into vitamin land (100 calcium is actually 96 calcium, did you know?) this is now ready for review. The summary has been edited to include known issues, neither of which I consider pressing or in scope. Let the good times roll.

**Comment by fairyarmadillo** [comment]
> > The food probably needs to be tracked individually solely because you can have four NPCs who are allergic to wheat and nothing in the larder but bread, and they'll eat it just fine with no penalties.
> 
> Not handled with the vitamin system.

It's an argument for not going this route and simply removing the larder instead. I was trying to save you work that's going to have to be deleted sooner or later, because I don't think the issues that PatrickLundell and I have described are resolvable as long as the larder is abstract.

**Comment by db48x** [comment]
Unless you (or someone you know) is actually working on a replacement for the larder system, it’s not worth stopping someone from doing good work now even if it will be replaced in the future.

**Comment by fairyarmadillo** [comment]
> Unless you (or someone you know) is actually working on a replacement for the larder system, it’s not worth stopping someone from doing good work now even if it will be replaced in the future.

But it introduces new problems that didn't exist before via the noob trap issue PatrickLundell described.

**Comment by db48x** [comment]
It seems really hard, even for a noob, to accidentally put toxic food into their camp’s larder. However, if you’re so concerned about it why don’t you add a confirmation before the larder accepts toxic food?

**Comment by RenechCDDA** [comment]
Clang does not like the way I'm (de)serializing, back to draft while I sort that out.

**Comment by RenechCDDA** [comment]
I realized that the deserialization functions also work for loading faction templates, so I just plain implemented that. That's one less obstacle to further improving factions.

image

**Comment by kevingranade** [comment]
@fairyarmadillo , @PatrikLundell you may not realize that your positions boil down to,  "I want to keep dumping tainted meat and vegetable oil into the larder", but that is exactly what is happening here.  These issues evaporate with the simple expident of "only feed the larder with good food".
I could see a warning in the frontend when you add food that evaluates whether the addition will push the larder over some threshold of unhealthiness, but I'm not going to ask for it in this PR.

Regarding converting to pantry zones. 
1. No,  the most I'd be ok with is a larder that tracks food items, there is absolutely no reason to have all of a factions food be present and simulated in the map at all times.
2. If we did go with tracking individual foods, I would not be ok with toxin/fat micromanagement or any kind of detailed rationing system, the only purpose I see being presented for it is micromanaging around the intended drawbacks of mutant meat and other bad foods,  just avoid them.

**Comment by PatrikLundell** [comment]
- I'm fine with just introducing harder limits on what you can dump into the store while retaining the current calorie only usage metric. As soon as the definition of "good food" starts to depend on what's in the store things get tricky, and I wouldn't want to go there. Setting up safety measures some time never is not suitable, so any "vitamin" tracking would need to also come with warnings, recommendations, and recovery mechanisms.
- I have no problem with a non physical store, as long as it can be transported to a new base camp (and as far as I know it's currently shared and so is automatically available).

**Comment by Montimorency** [comment]
This game's design is fundamentally not suited to player handling of complex NPC Needs without comprehensive reconstruction, and it is another distraction from the gameplay loop past a certain point. 

There is an abstract solution that will displease micromanagers, but will save the player time and also account for the fact that the dev team never intends for all world NPCs to just die of dehydration on their own after the first days (if this isn't the case, then...). 

Require the faction leader to allocate a certain proportion of an NPC's waking hours to securing their own Needs. During this time they will be unavailable to perform any formal or informal faction work. The implementation could be as crude as a craftable pseudo-item that will deliver calories and vitamins to each given NPC on completion. Formal (BB) construction or base tasks could require additional raw calories as is currently implemented.

**Comment by Tou1on** [comment]
It remains to add the option to add multivitamins to the larder

**Comment by RenechCDDA** [comment]
> It remains to add the option to add multivitamins to the larder

This will never be optional.

**Pull request merged**
