### PR TITLE
Add Weakpoint Proficiencies to More Zombies

### LINKED ISSUE #59053: Dissecting a Skeletal Dog doesn't improve proficiency for Natural Exoskeletons
### Describe the bug

Skeletal Dogs, despite having a natural bone exoskeleton, do not provide any experience towards the Natural Exoskeletons proficiency.

### Steps to reproduce

Perform a dissection on a Skeletal Dog with the appropriate prerequisites already completed.

### Expected behavior

Increase to progress towards proficiency in Natural Exoskeleton

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 873f768 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SolventMercury**
#### Summary
Bugfixes "Fix Many Missing Zombie Weakpoint Proficiencies"

#### Purpose of change
Many creatures of all kinds are missing definitions for weakpoints and proficiencies that can be gained from dealing with them. I've sought to add some missing ones. This updated focuses on updating proficiencies for zombies, excluding the misc, ferrous, winged, radiation, and pupating categories of zombies, which I will review later. I also renamed the "Natural Exoskeletons" proficiency to "Ossified Exoskeletons", as its original name was very misleading.

Fixes #59053

#### Describe the solution
- Renamed Natural Exoskeletons proficiency to Ossified Exoskeletons to clarify the nature of the proficiency.
- Added zombified animals to the Intro Biology and Zombie Biology weakpoint families
- Added burned-type zombies to the Intro Biology and Zombie Biology weakpoint families
- Added Ossified Exoskeletons proficiency and weakness to the Skeletal Dog, Skeletal Wolf, Skeletal Zombear, and Fiend
- Z-9 now trains the Synthetic Armor proficiency, as it is wearing a kevlar vest.
- Scorched Zombies and Zombie Fiends now train Burn Care, as intended in https://github.com/CleverRaven/Cataclysm-DDA/pull/56487
- Beekeeper Zombies now added to Natural Armors proficiency, due to its tough hide of scar tissue.
- Gave scientist zombie standard weakpoints

#### Describe alternatives you've considered
N/A

#### Testing
Spawned, killed, and dissected monsters to ensure they provided proficiency XP in the relevant proficiencies. I'm unsure how to test whether learning such a proficiency actually improves your combat with monsters, or whether such information is even presented in the debug log.

#### Additional context
Still have to work on misc, ferrous, winged, radiation, and pupating categories of zombies, but I've given a thorough review to all others. Just splitting things up to avoid having too massive of a PR, and for my own sake.

### CODE REVIEW

**Comment by SolventMercury** [comment]
I did not modify any code, so I'm going to assume the test failure was erroneous.

**Comment by anothersimulacrum** [comment]
Not a safe assumption, but correct here.

**Comment by Boonlike** [comment]
Thanks for doing this! The weakpoints have been one of my favorite additions, it's nice to see it expanded. Have you been adding additional dissection flavour text as well?

**Comment by SolventMercury** [comment]
> Thanks for doing this! The weakpoints have been one of my favorite additions, it's nice to see it expanded. Have you been adding additional dissection flavour text as well?

No, I did only what was in the PR.

**Pull request merged**
