### PR TITLE
Attempted to fix build error part two

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by keyspace** [comment]
There are more occurences of the same down the file.

It's currently complaining on a trailing space (line 13).

**Comment by keyspace** [comment]
I'm running the linter locally and can submit a full PR if desired. This would be faster than picking lines one-by-one.

**Comment by keyspace** [comment]
Issue addressed in #20109. OK to close.

**Comment by BorkBorkGoesTheCode** [comment]
Thanks @keyspace !

**Pull request closed without merging**
