### PR TITLE
Add unarmed_weapon flag to tonfas, alter unarmed_weapon behaviour

### PR DESCRIPTION
**Pull request by Eighth-of-Third**
As the tonfa is primarily a weapon designed for use with martial arts, it should be able to be used with martial arts. When holding the tonfa by the side-handle with the long end pointed towards your elbow, it can augment almost all hand and arm strikes, including punches, elbow strikes, and knife-hand strikes (karate chops).

Example video: https://www.youtube.com/watch?v=35gzIUOzb60

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Giving it generic unarmed means it is useful at boosting boxing punches, can't be removed from the wielder by disarms or similar actions, and ignores non-conductivity.

**Comment by Izicata** [comment]
I don't see why it wouldn't boost boxing punches. Punching with a tonfa is a lot less different from a regular punch than punching with a katar is. I didn't know unarmed weapons weren't disarm-able, but it's no more weird than not being able to be disarmed of a punch dagger. If you're going to be punching someone with this, you're going to have to get close enough for sparks to jump from the zombie to you; tonfas can be used to block, but they don't have a guard per-se.

What would you suggest instead? Adding it to all the martial arts weaponlists?

**Comment by Coolthulhu** [comment]
> What would you suggest instead? Adding it to all the martial arts weaponlists?

Adding it to weaponlists for martial arts that teach using tonfas.

Later on we should probably disable the whole katar bullshit and buff martial arts to compensate. This results in really dumb stuff, like punch daggers buffing kick damage.

**Comment by Izicata** [comment]
I always thought that was simulating using the weapon before or after the kick; i.e. a punch, then a kick, as part of the same attack.

**Comment by Izicata** [comment]
Now unarmed weapons don't ignore non-conductivity, all unarmed weapons that were previously conductive remain conductive, and tonfas remain non-conductive.

**Comment by Izicata** [comment]
Unarmed weapons are now disarm-able. As far as I can tell unarmed weapons are now considered the same as regular weapons, except that they're usable with unarmed melee styles.

**Comment by Coolthulhu** [comment]
> Unarmed weapons are now disarm-able.

How are you going to disarm brass knuckles or a cestus?

**Comment by Rivet-the-Zombie** [comment]
We could move disarm-immunity into a separate flag so that some 'unarmed' flagged weapons can be disarmed and some can't.

**Comment by Izicata** [comment]
```
src/melee.cpp:83:14: error: out-of-line definition of 'is_disarmable' does not match any declaration in 'player'
bool player::is_disarmable() const
             ^~~~~~~~~~~~~
1 error generated.
```

Why does this not work, when is_armed and unarmed_attack work?

**Comment by Izicata** [comment]
Aww fug, adding a no_disarm flag description causes conflicts. Should I just revert that, and add it after the merge?

**Comment by Izicata** [comment]
This thing is bitrotten, I'll just remake it.

**Comment by Coolthulhu** [comment]
I'm still not sure if unarmed on tonfas is a good thing.
We have those weird unarmed attacks which allow kicks to benefit from brass knuckles and all.
It should probably just be allowed for specific martial arts.

**Comment by Izicata** [comment]
A tonfa boosting kicks is no weirder than brass knuckles boosting kicks; allowing brass knuckles to work with martial arts and not tonfas is inconsistent. Either tonfas should have the unarmed_weapon flag or all unarmed weapons should only be allowed for specific martial arts, and I'm not going to go through all the unarmed weapons manually adding them to the weapons lists of unarmed_allowed styles. The whole reason the unarmed_weapon flag exists is to avoid having to do that.

**Pull request closed without merging**
