### PR TITLE
Reduce number of charges for oxyacetylene torch

### PR DESCRIPTION
**Pull request by mugling**
As previously raised, most recently in #14788, the acetylene torch has far too many charges and/or is far to easily acquired. It has some niche usages should otherwise differentiate itself from the electrical welders which it currently renders largely obsolete for most tasks.

This PR proposes reducing the number of charges by 75% however it will be interesting to see what the various opinions are as to the appropriate value?

### CODE REVIEW

**Comment by Malkeus** [comment]
I'll restate my opinion from #14788: I think a 50% reduction would be a
good balance between having a useful lifespan and being too limited.

**Comment by Core0verload** [comment]
50% is good. 75% is too much for a non-rechargeable bulky welder-cutter.

**Comment by Malkeus** [comment]
These tanks come in a [variety](http://www.reifsnydersag.com/TICPhoto.jpg) of sizes. If we go the 75% route, I'd like to see the volume come down to 8 or 12. They are too bulky as they are, but that's one of the justifications for the massive number of uses I think. I don't think they should be particularly portable, but shaving a bit of volume while reducing the number of uses would be acceptable.

**Comment by chaosvolt** [comment]
Agreed, if we reduce the charges we should reduce the volume.

**Comment by Marrim** [comment]
They combine a lot of convenience (forge + welder!) and inconvenience (no recharging + large volume, especially annoying when you have like 3 torches each with 100 charges left).

I'd be all for reducing their charges if their volume/weight is also reduced in some fashion.

**Comment by Coolthulhu** [comment]
Current volume is fine, they replace a whole forge.

**Comment by chaosvolt** [comment]
> Current volume is fine, they replace a whole forge.

Last I checked, there are several recipes (armorsmithing mostly) that explicitly require a forge, but don't allow an acetylene torch. >_>

**Comment by Marrim** [comment]
It's volume is not fine if they'll only have 500 charges.

My survivors use torches and welders and forges, and I've always felt their benefits are balanced out. If you feel acetylene is too abundant, you can nerf its avaliability, but please don't make it impractical to use! Note I'm not saying volume and weight should be halved -- maybe just reduce volume to 10-12.

And they don't replace a whole forge, you still need the other tools (most notably anvil), so it is not going to suddenly allow forging stuff while hiking far away from your base/vehicle.

**Comment by chaosvolt** [comment]
It would appear that glassworking is the only thing that allows a forge but not acetylene. Has it always like like this? I could've sworn there used to be other exceptions, just like how some items permit a welder/torch but not forges.

That said, making this thing stupendously bulky while retaining its volume would make this PR even more of an annoyance than it will already be. ;A;

**Comment by Coolthulhu** [comment]
> It's volume is not fine if they'll only have 500 charges.

240 actually.
500 wouldn't be anywhere near "only".

240 charges is enough for:
* 60 car repairs (duct tape for that would take 30 volume, same for batteries WITHOUT welder)
* 3 light plate armors
* 4 barbute helmets
* 60 steel spears
* 6 maces
* 4 morningstars
* 2 zweihanders, nodachis or katanas

Acetylene torch is 7.5 times as volume-efficient as charcoal (without the forge) and 33% more volume-efficient than battery-powered forge.
That's with 240 charges.

**Comment by chaosvolt** [comment]
Okay, this bring me back from my mistaken point to wondering about another point.

Does it MAKE SENSE that we can forge armor using an acetylene torch? Though I legitimately wouldn't be surprised if this is something Rivet's tried. XP

Either way, I should point out that the welder has 10 volume, and...wait, it's not allowed as a substitute for forges in most recipes. So fucked if I know how to balance welders versus torches, all I know is that this volume discussion has been more about balancing forges and rtorches instead. :V

**Comment by Coolthulhu** [comment]
> So fucked if I know how to balance welders versus torches, all I know is that this volume discussion has been more about balancing forges and rtorches instead. :V

> 60 car repairs (duct tape for that would take 30 volume, same for batteries WITHOUT welder)

With welder, we subtract 5 volume (500 batteries) and add 10 volume (for the welder itself).
So the acetylene torch is over 2x as volume efficient for car repairs.
In recipes where torch can replace a welder, it uses 20% of the charges. Meaning that oxy torch is comparable to a welder with 1200 charges, which would occupy 17 volume total.

**Comment by chaosvolt** [comment]
Hmm. Guess that makes sense then. ._.

**Comment by Coolthulhu** [comment]
It could have volume reduced to 10 to stay strictly better than welder when it comes to volume (welder has the double battery mod thing), but it looks much better than it did when it comes to other stuff, like total amount of crafting that can be done with it.

**Comment by chaosvolt** [comment]
So, either 10 volume or maybe 12. Hell, even 14 sounds acceptable. While it is more efficient than the welder, it does have its other balancing factors.

As much as I like 1000-charge acetylene torches, I must admit that the original usage essentially made one torch last for more than long enough to set up a vehicle welding rig, at which point there goes half of your reason to need a torch. Nerfing the usage is acceptable, but retaining the bulk still only seems like a "balance through player annoyance" thing.

That said...other stuff? That still leaves the question of whether its other crafting uses make sense. As much as I hate to say it, if its use for smithing proves to be unrealistic, then it no longer NEEDS to be directly balanced against forges.

However, that can remain the subject of another PR.

**Comment by Coolthulhu** [comment]
Merged
Volume reduction can happen in a next PR.

**Comment by chaosvolt** [comment]
Agreed.

**Comment by Marrim** [comment]
Why does it even need to have different charge measurement?
Why not just make it a welder and electric forge substitute (same way an oil cooker or chem set substitutes for a hotplate) and give it 1200 charges?

Or it can't be set to substitute for both?

**Comment by chaosvolt** [comment]
Hmm. No. Making the torch a straight *substitute* for a tool would worsen the problem.

**Comment by Rivet-the-Zombie** [comment]
>Does it MAKE SENSE that we can forge armor using an acetylene torch?

It works fine for small stuff. You're substituting a compressed gas flame for a forced-air furnace; it just doesn't heat as large an area at once, so there's a lot more heating time involved for really large projects.

As for why you can forge stuff with an oxy torch and not a battery welder, that would be because the battery one is presumably something like a flux core MIG welder which operates on a completely different principle and can't be used to heat metal in the same fashion as a torch.

**Comment by chaosvolt** [comment]
> Though I legitimately wouldn't be surprised if this is something Rivet's tried. XP

Totally called it.

**Comment by Rivet-the-Zombie** [comment]
You did indeed!

**Comment by chaosvolt** [comment]
That does lead to ponder what recipes are logical the way they are now, and which might be a bit odd (or failing that, require differing ratios of torch usage to forge usage).

**Pull request merged**
