### PR TITLE
feat: label issues by template+confirm bug command

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
@Maleclypse asked me if it was possible to label issues based on their template, aka their type bug report or feature request, the templates have quite a lot of non-editable parts, perfect for a bot to classify them, here as (S1 - Need Confirmation) and <Suggestion / Discussion> respectively

A command to "confirm" a bug report was also requested it does not require any access to the repo permissions, it can be done by anyone as long as their username is in the allowed users list `.github/comment-commands.yml` in this pr
"confirming" here refers to removing the (S1 - Need Confirmation) label and adding the (S2 - Confirmed) label to an issue, it's done by commenting `/confirmed` in an issue this also works
```
/confirmed
x and y reason confirms this bug report
or
/confirmed x and y reson ...
```

I need more users for the list that are or aren't maintainers, collaborators or whatever, I don't think I can be the one to hand down the permission to use

#### Testing
Issues are auto labeled by type and a comment can confirm them
<https://github.com/casswedson/issue-labeling/issues/8>
<https://github.com/casswedson/issue-labeling/issues/4>

#### Additional context
For some reason, (the structure of the actions I used, not because I got carried away) this also serves a base to add more "commands" triggered by comments, like comments can be used to run any old [code](https://github.com/actions/github-script) one wants, if you can think it, it probably can be implemented

### CODE REVIEW

**Comment by Maleclypse** [comment]
I'll try and start the list this weekend.

**Comment by Termineitor244** [comment]
Nice feature! It would be nice to be able to confirm (with labels) a bug, since the people with repo permissions can get pretty busy as they are.

**Comment by casswedson** [comment]
In case you missed your mention by Maleclypse
@Faalagorn @Ilysen @Aerin-of-the-Toast @anoobindisguise @PatrikLundell @TheShadowFerret

**Comment by Ilysen** [comment]
I could *try*, but I caution that most of my bug reports/confirmations come from my regular playthroughs, so I might suck at doing them directly. :P

**Comment by Faalagorn** [comment]
> In case you missed your mention by Maleclypse @Faalagorn @Ilysen @Aerin-of-the-Toast @anoobindisguise @PatrikLundell @TheShadowFerret

Thanks for the ping, otherwise I'd probably miss it :).

So if I understand correctly, it's giving us the permission to confirm the issues by typing the commands? I unfortunately often lack the time to check all the issues, so might not be as helpful, but I don't mind as long as it doesn't have any obligations and it might indeed come handy eventually. it doesn't give much permissions anyway, but I try to 2FA and a strong password everywhere, so hopefully the risk of my account getting compromised is minimized as well. :)

**Pull request merged**
