### PR TITLE
butchery requirements 2

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Features "Finish jsonizing butchery requirements"```

#### Purpose of change
This is a follow up to #42372 and continues to push the data to json. This PR should be the last required PR to polish off the C++ changes necessary. This also keeps the status quo from the previous PR for butchery requirements, to be followed up with a json-only PR. (i am not volunteering to write the json-only PR.)

#### Describe the solution
create a new class called `butchery_requirements` which holds a variety of data, arranged in maps for easy access: float activity speed modifier, creature size, butchery type, requirement id. When the butchery action is set up, it tries to find the "fastest" (highest modifier) requirement with the given creature size and butchery type and tools available. if it can't match a requirement to tools available, it will return the highest modifier so it can display the tool requirements in the butchery menu.

#### Testing
WIP

#### Additional context
@I-am-Erk had some ideas about the sample json i posted in discord

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/butchering-in-0-e/24288/38

**Comment by KorGgenT** [comment]
as this is the completion of a feature that was merged last week, i think it makes sense that this doesn't get caught in feature freeze.

**Comment by NoahGoldFox** [comment]
Does this fix it so quick butchering and the other sloppy butchering options no longer require surface?

**Comment by KorGgenT** [comment]
as i said in the summary:
> This also keeps the status quo from the previous PR for butchery requirements, to be followed up with a json-only PR. (i am not volunteering to write the json-only PR.)

**Comment by NoahGoldFox** [comment]
But the clean surface requirement for all butchery is ridiculous! it pretty much requires debugging in some kind of sheet and is unrealistic

**Comment by I-am-Erk** [comment]
Are you volunteering to make the follow up pr that fixes the requirements such that having a clean surface makes field work faster, rather than being necessary? The tools are now all in place, that is the point of this pr, so I'm not sure what else you'd be trying to argue here.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/dissecting-in-0-e/24327/20

**Pull request merged**
