### PR TITLE
Correct inaccurate Kickboxing moves, let you start with it.

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
Balance "Adjust Kickboxing and let you start with it"

#### Purpose of change

Far as I could tell, there wasn't a way to start with kickboxing at all. As for the art itself, it included two knee strikes despite kickboxing not using knee or elbow strikes _(Muay Thai Kickboxing_ does, but we already have Muay Thai), while missing some foundational moves.

Obsoletes #60649

#### Describe the solution

Added Kickboxing as a possible choice for the "Self Defense" background, and another lower-tier "Cardio Kickboxing" background as it is a popular fitness thing.

Removed the two knee strikes. Also removed the side kick, as it was redundant with the roundhouse kick and while it _is_ a technique in kickboxing it's not as foundational. Added the "Cross" technique (basically a copy of Pankration's cross) and "Push Kick" technique (basically a copy of Taekwondo's side kick).

Slightly buffed the roundhouse kick from 1.2x to 1.4x damage to separate it from Cross (higher base damage but there's not really any good foot weapons compared to fist weapons) and made it crit_ok so there was a usable crit technique on enemies that can't be uppercut.

#### Describe alternatives you've considered

Leaving the side kick in mostly for flavor, or trying to figure out how to differentiate it from the roundhouse/push kick.
Increased the skills in Cardio Kickboxing; maybe getting actual instruction should be 2 melee/unarmed even if all you're doing is punching a bag and 1 is undershooting it.

#### Testing

Checked to make sure the backgrounds spawned, kickboxing was chooseable, and the techniques were reflected in game.

#### Additional context

I made this PR after coming home from my own cardio kickboxing class. It was leg day. orz

### CODE REVIEW

**Comment by ymber** [comment]
Modern kickboxers all know knees. I've never trained with one who doesn't. Old school American rules didn't allow knees but they've been legal in every major organization since the K1 era.

**Comment by Aerin-of-the-Toast** [comment]
> Modern kickboxers all know knees. I've never trained with one who doesn't. Old school American rules didn't allow knees but they've been legal in every major organization since the K1 era.

In the US? As far as I'm aware American Kickboxing is still the dominant version of kickboxing in the US and K1 isn't really a thing here. When googling it at least I keep seeing about it being popular in Europe and Japan but not the US, and that jives with my (_extremely_ limited tbf) personal experience.

**Comment by ampersand55** [comment]
Most major US-based kickboxing promoters allow knee strikes, e.g. Bellator Kickboxing, Strike-force kickboxing and the International Sport Kickboxing Association (ISKA).

But that doesn't necessarily mean knee strikes are used or taught in general sports kick boxing classes, or "Cardio Kickboxing". Perhaps we could put the knee techniques behind high lvl melee skill to indicate they are not used until you are at an advanced level aiming at competing for above promoters?

**Comment by Zireael07** [comment]
My Google seems to be divided on whether knee strikes are allowed. There seem to be various organizations, like various "belts" in boxing except even MORE of them!, and some allow them some don't.

I *know* kickboxing is an Olympics sport, but I'm having zero luck trying to figure out WHICH variant is at the Olympics. Anyway I'd just gate the knees behind a separate manual.

**Comment by ymber** [comment]
> > Modern kickboxers all know knees. I've never trained with one who doesn't. Old school American rules didn't allow knees but they've been legal in every major organization since the K1 era.
> 
> In the US? As far as I'm aware American Kickboxing is still the dominant version of kickboxing in the US and K1 isn't really a thing here. When googling it at least I keep seeing about it being popular in Europe and Japan but not the US, and that jives with my (_extremely_ limited tbf) personal experience.

That's possible, I'm in Britain and we've got a lot of Dutch and Thai influence in the styles you see at a lot of gyms here. A lot of the guys I train with have trained in Thailand and I generally compete in Thai rules. Could be people still train old school American style over there.

**Comment by Aerin-of-the-Toast** [comment]
Based off the comments I'm gonna specify in the description it's based off American Kickboxing to clear up confusion then. Thanks for helping me clear some stuff up and learn about different kickboxing styles!

**Pull request merged**
