### PR TITLE
Fixed range field and added .38 Super pistols [Extended Realistic Guns]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
@DangerNoodle is it intended? It looks like an artifact.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Likely an artifact of whatever weapon I based it off of.

**Comment by BorkBorkGoesTheCode** [comment]
It can be removed then.

**Comment by DangerNoodle** [comment]
Hmm? No reason to close it. I mean that yes, the range addition was an artifact and not really required. If anything it might be better on the long-barreled firearms.

**Comment by BorkBorkGoesTheCode** [comment]
I've combined my .38 Super update with this PR to reduce the number of potential open PRs and merge conflicts.

**Pull request merged**
