### PR TITLE
Remove NV conflicts from Telescopic Eyes CBM

### PR DESCRIPTION
**Pull request by sonphantrung**
#### Summary
Balance "Remove NV conflicts from Telescopic Eyes CBM"

#### Purpose of change
Hell, the Telescopic Eyes CBM removing Night Vision-derived traits/mutations no more! The only true thing that it affects are eye lenses, for Far/Near-sightedness and binocs-like vision, and even funnier, the removal message is `The Telescopic Lenses are part of %1$s eyes now.  Removing them would leave %2$s blind.`

#### Describe the solution
Obviously, remove conflicts

#### Describe alternatives you've considered
Changes the "unable to remove" message, and add weak night vision bonus akin to Night Vision trait

#### Testing
If it doesn't throw errors, it should be good

#### Additional context
'a'
https://modernsurvivalblog.com/security/human-night-vision/

### CODE REVIEW

**Review by Maleclypse — CHANGES_REQUESTED** [review]
You would need more justification for this than I'm currently seeing here.

**Comment by dseguin** [comment]
Just to add, it looks like the conflict might be intentional (see https://github.com/CleverRaven/Cataclysm-DDA/pull/18139#issuecomment-269741715 and #38903)

**Comment by sonphantrung** [comment]
https://modernsurvivalblog.com/security/human-night-vision/

Human's night vision is affected by eye rods/cones. If I knew C++ (I only know C D8), I would change the removal reason, and add basic night vision bonus (+2 night vision tiles)

**Comment by aMegaSloth** [comment]
I agree with the other comments. The telescopic eye CBM literally scopes out the eyeballs. There wouldn't be anything left to mutate.

On the other hand I think there is a feature to 'upgrade' CBMs somewhere, and you can promise eye upgrades to the telescope eyes after they are installed.

**Comment by sonphantrung** [comment]
Well yeah, there's Implanted Night Vision CBM, but if it replaces the whole eyeball, there should be some night vision bonus

**Comment by Ilurker** [comment]
> Well yeah, there's Implanted Night Vision CBM, but if it replaces the whole eyeball, there should be some night vision bonus

I think the barrier is you're not explaining/justifying why that's the case. There's nothing inherent about telescopic lenses to suggest they should make your retina more sensitive in the dark. My camera has an optical zoom, it doesn't have night vision. Other cameras have night vision, but no optical zoom. The two aren't linked and from the consumer CBM perspective, there's good reasons re: complexity and cost why the two wouldn't always be bundled.

**Comment by sonphantrung** [comment]
After thinking, I don't really see it valid. PR closed

**Pull request closed without merging**
