### PR TITLE
[MinGW TEST REQUIRED] vstring_format() huge speed up

### PR DESCRIPTION
**Pull request by BrettDong**
Benchmark:

| implementation | 100k calls(s) |
|---|---|
| original | 2.657 725 |
| b55075e | 0.070 906 |
| current PR | 0.107 415 |

(b55075e uses `vasprintf` which isn't available on all platforms, so I implemented a common version later. It is supposed to function on all platforms, but is a little bit slower compared to `vasprintf` approach.)

The original approach of formatting a string is weird and slow, it constructs a `std::vector<char>` every time being called, and trials for an appropriate buffer size using bisection method, which might call `vsnprintf` a number of times in total. In fact, if the first parameter given to `vsnprintf` is `NULL`, then it will return the number of bytes required to store the result. No need to bisect.

I wrote a test case called `string_format`, and a benchmark called `string_format_benchmark`. Welcome to check out my branch and see if this work on your arch/OS/compiler, **especially MinGW and Cygwin**.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Why the special case for windows?

**Comment by BrettDong** [comment]
iirc, `vasprintf` isn't available on Windows.

**Comment by Coolthulhu** [comment]
Results on Cygwin (MSYS2):
```
100k calls of string_format() executed in 3190183 microseconds.
```

Passes the tests.

**Comment by illi-kun** [comment]
This PR built fine with MinGW in Code::Blocks on Windows but I have no idea how to run tests, sorry.

**Comment by Coolthulhu** [comment]
Open a console in the main cataclysm directory and call
```
tests/cata_test.exe -D "string_format"
tests/cata_test.exe -D "string_format_benchmark"
```

After the first line finishes, the output should not have any failed tests.
The second line should print a "test finished in x milliseconds".

**Comment by illi-kun** [comment]
@Coolthulhu I compiled only .cpp files included in C::B project by default. I have no idea how to deal with unit tests actually, so simple incorporation of test folder content to the project doesn't help, so probably I'll not provide you feedback on this any time soon, sorry for that.

**Comment by BrettDong** [comment]
That is pretty slow. I doubt whether this is actually picking up speed on
Cygwin. Would you like to measure the time elapsed for 100k calls to the
original implementation of string_format() function too? If this PR is
actually making things slower on Cygwin, I might have to apply the changes
only to *nix platform.

**Comment by mutability** [comment]
How often do we call vstring_format() with a result that's >1k characters? (Which is the initial buffer size of the old code)

**Comment by mutability** [comment]
I measure no significant difference between current master and this PR:

| upstream/master | PR 19075 |
| -- | -- |
| 91756us | 90815us |
| 86157us | 87537us |
| 86634us | 86808us |

(Linux, release build)

**Comment by BrettDong** [comment]
Then it's system dependent. In #19240 I found `vstring_format()` is called very frequently, and after this change, at least on my macOS system, the game is 1/3 faster when batch crafting jerked meat.

**Comment by mutability** [comment]
I think you are accidentally optimizing something else here; note how the old code only calls vsnprintf _once_ for any string that fits into the initial (1k char) buffer, which must be just about always.

**Comment by mutability** [comment]
Try just the change to using std::string as the buffer, without touching the rest of it. That gave about a 10% improvement here and it's the only other noticeable change in your version.

**Comment by BrettDong** [comment]
Yeah, we have the same idea. The bottleneck in the old code is vector memory allocation. After change the buffer to `std::string`, the performance is better. Why I refactor the entire function here is that I think the original code is too _ugly_ . If we could know how much bytes of buffer will be required, why would we still trial-and-expand?

**Comment by mutability** [comment]
Well, you have to call vsnprintf twice to do that, which means it has to process the format string and arguments twice. Plus if you have a nonstandard vsnprintf it may not even be _able_ to tell you the size. There are a lot of variations on the return value (just look at the old code) and this is hard to get right.

I would suggest instrumenting the old code so it logs whenever it actually had to try expanding the buffer. I expect that it happens rarely or never.

**Pull request closed without merging**
