### PR TITLE
Revise hallula

### PR DESCRIPTION
**Pull request by ToxiClay**
#### Summary

None

#### Purpose of change

This change applies a fix to my hallula bread; I forgot to include lard in the recipe. I think I've got it now, though.

#### Describe the solution

This adds the lard.

#### Describe alternatives you've considered

None.

#### Testing

Integrated the changes into my existing (very old, I need to update it) game version. Eventually found the recipe, and it looks correct.

#### Additional context

I don't know why it's claiming it can't automatically merge this. I based this PR off of 0.F-dev, as was proper.

```
Omega@Shinryu MINGW64 /g/GitHub/Cataclysm-DDA (revise-hallula)
$ git checkout upstream/0.F-dev
Updating files: 100% (583/583), done.
Note: switching to 'upstream/0.F-dev'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 3a8ae4e09f [Aftershock] misc typograpical fixes (#47783)

Omega@Shinryu MINGW64 /g/GitHub/Cataclysm-DDA ((3a8ae4e09f...))
$ git branch -D revise-hallula
Deleted branch revise-hallula (was 1ae66c97a0).

Omega@Shinryu MINGW64 /g/GitHub/Cataclysm-DDA ((3a8ae4e09f...))
$ git switch -c revise-hallula
Switched to a new branch 'revise-hallula'
```

image

### CODE REVIEW

**Comment by KorGgenT** [comment]
it probably just needs a force push to 0.F-dev again, since 0.F-dev was force pushed. this has been happening fairly often over the past few weeks.

**Comment by Saicchi** [comment]
I like rebasing of master to avoid this problem, since the 0.F-dev branch is rebased all the time.

**Comment by ToxiClay** [comment]
There shouldn't be any conflicts, though, because rebase asked me to fix them.

**Comment by BrettDong** [comment]
Probably because the 0.F-dev copy on your computer is not identical to the one here on GitHub.

**Pull request merged**
