### PR TITLE
Remove bridgehead_ramp vehicle nests

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change

I forgot to remove the vehicle spawns from the z1 bridgehead_ramp during #70098 at CoroNaut's request where you're very likely to crash in to them if not peeking up the z level

#### Describe the solution

Straight up yeets them

#### Describe alternatives you've considered

Also removing the bridgehead_ground ones

#### Additional context

Thanks to TheMurderUnicorn for pointing this out ^^

### CODE REVIEW

**Comment by Maleclypse** [comment]
I feel like these are less of a gotcha and more of a "you should drive carefully around corners in the apocalypse because there are wrecked cars everywhere especially around blind corners and up ramps."   This sounds like "I keep wrecking on the one out of twenty bridges that have wrecks on them because they are such a low occurrence and I drive 80 miles an hour around blind corners because no one punishes me".    Why wouldn't a better PR increase the number of wrecks at these blindspots?

**Comment by Maleclypse** [comment]
I can probably be convinced this is a good idea to merge, but I'm just not sure.

**Comment by Procyonae** [comment]
I mean the only way to tell there's a wreck there is to use "experimental" z vision and peek up. I'm leaving the ones at ground level bc I think we can expect the average player to be using the depth vision stuff but having to peek up is a bit eh and irl it wouldn't be a blindspot just a mild incline, the only reason it's a z level change is so boats fit under bridges

**Comment by Procyonae** [comment]
This does also only give ~12 tiles of leeway, if you're going 80mph and not playing upmost attention you'll still crash with the new closest spawn

**Pull request merged**
