### PR TITLE
Nerf outlandish drug effects

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: Balance "Nerf outlandish drug effects."

#### Purpose of change
Various forms of drugs have inordinately large physical impacts.
This is both extremely unrepresentative of reality and presents very poor balance as the supplies of these substances is very high in the game.

#### Describe the solution
Nerf physical effects of many mundane drugs to bring them closer to what one would expect in reality.

#### Describe alternatives you've considered
Renaming some of them to be explicitly fantastical drugs, but that doesn't explain how comon they are.
Adding new fantastical drugs. I'm not interested.

#### Additional context
I have no objection to adding some of these effects back with sci-fi drugs or similar, this would address both the realism issue and the balance issue that the current drugs have.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
For the record to anyone seeing and getting angry about the nerf, I fully intend to add these effects back into the game as dangerous supersoldier drugs... And taking them out now helps assess how to balance them.

**Comment by l29ah** [comment]
AFAIK amphetamine does improve intelligence a little IRL. Methacola though surely was too good.

**Comment by KyrasRisven** [comment]
Yeah after looking over the changes amphetamines like Adderall now seem to not act like they do IRL. Due to their focus enhancing effects IRL I'd suggest drastically increasing their morale value or adding a new focus modifier effect to the stimulants that gives a bonus to your focus (this also leads nicely to my idea of an ADD trait that applies a general focus reduction that can be fixed with stimulants)

As for intelligence I can understand getting rid of that, as they don't make you smarter per se, they just improve your ability to use what you already know and perform certain tasks associated with intelligence better (see https://en.wikipedia.org/wiki/Wechsler_Adult_Intelligence_Scale ). They don't suddenly help you understand how to install a bionic better. A focus modifier would allow them to help with textbook studying without applying an intelligence increase.

Regarding cigarettes, nicotine can have positive effects on the mind (see https://www.health.harvard.edu/newsletter_article/Nicotine_It_may_have_a_good_side ) so maybe a slightly higher morale effect for it would be fair. As the above article states, people with depression and anxiety disorders often self-medicate with it, so I feel morale boost makes sense.

The rest of the changes seem fine to me based on my knowledge of their effects.

**Comment by kevingranade** [comment]
While that sounds reasonable, novel benefits can be added in another PR, unless you have sources that indicate that the previous effects are justified, please open a new issue or PR to discuss it.

**Comment by I-am-Erk** [comment]
I do agree that having a focus boosting effect to stimulants would be perfect. And that it belongs in another PR.

For the most part I think focus does a better job of simulating stimulant effects than intelligence does.

**Comment by Orinyau** [comment]
Are there any plans to change the description/crafting of the crack pipe? 

The crack pipe described in the game is actually a meth pipe. A crack pipe is typically a glass cylinder with a piece of copper scouring pad as a filter (ignoring makeshift alternatives such as a marijuana pipe with ashes in it, or a soda can with holes punched in the bottom, also, usually with cigarette ashes in it. Smoking crack in the pipe described in-game would just lead to a foul, coppery smell, and sadness (from wasted drugs)

**Comment by Asmageddon** [comment]
Have the drugs made poppy been nerfed too? I recall a few months ago that many drug recipes treated 2 poppy buds worth of drugs as equivalent to heavy duty pharmaceutical substances.

**Comment by TechyBen** [comment]
> Have the drugs made poppy been nerfed too? I recall a few months ago that many drug recipes treated 2 poppy buds worth of drugs as equivalent to heavy duty pharmaceutical substances.

Those ones are fictional, I always assumed the "mutated" description covered them being super substances.

**Comment by Asmageddon** [comment]
@TechyBen Yes, but even so. You can substitute a season's worth of medicine looting with a day's poppy gathering. A little questionable balance, in my opinion.

**Comment by TechyBen** [comment]
> @TechyBen Yes, but even so. You can substitute a season's worth of medicine looting with a day's poppy gathering. A little questionable balance, in my opinion.

This should now change with some chem preparation tools requirements. Though I don't know if it's recipes is getting changed to match.

**Comment by I-am-Erk** [comment]
They haven't been yet, but all it would take is someone doing a bit of research on how to extract opiates from poppy precursors and plugging that in. If nobody else gets to it before me it's pretty high on my list.

**Comment by kevingranade** [comment]
Jenkins Rebuild

**Pull request merged**
