### PR TITLE
Use WELL512a as the pseudorandom number generator instead of stdlib rand

### PR DESCRIPTION
**Pull request by remyroy**
Here are the benefits of using WELL512a instead of stdlib `rand`:
1. It is faster. ~2.18 times faster on my Ubuntu system, ~3.12 times faster on my Windows system and ~1.94 times faster on my Mac OS X system.
2. It is consistent across platforms which is not the case for `rand` which can prevent weird bugs like #14410.
3. It has a long period length (2^512)-1 compared to most rand implementations which are at most between 2^32 and 2^64. Historical implementations of LCG have even shorter period lengths because of [improper `m`, `c` and `a` constant values](https://en.wikipedia.org/wiki/Linear_congruential_generator#Period_length).
4. It has a better equidistribution than the other popular PRNGs like the twisted GFSR and the Mersenne twister. It evolves better and in a more chaotic way than comparable PRGNs with low bits seeds and low bits internal states.
5. It has [a _free_ SSE2 optimized implementation](https://github.com/ppettersson/random_well512a_simd/blob/master/RandomWELL512a_SSE2.h) that could be easily swapped in if we want to go that route. That implementation gives an additional ~2 times faster run speed on processors who support [SSE2 instructions](https://en.wikipedia.org/wiki/SSE2) on top of what is mentioned in 1.
6. It passes with success all the important statistical tests in Smallcrush, Crush and Bigcrush
   of TestU01 except those that look for linear dependencies in a long sequence of bit which is fine for this use. There is no need to use a cryptographically secure random number generator for a game.

Have a look at the [WELL Random number generator white paper](http://www.iro.umontreal.ca/~panneton/WELLRNG.html).

### CODE REVIEW

**Comment by remyroy** [comment]
Yeah, I tested the running the game for a while with this change. There are asserts in std::uniform_int_distribution which caught many cases of maxVal being lower than minVal.

**Comment by kevingranade** [comment]
1. None of the stated benefits actually matter to the game as a whole.  Unit tests that demonstrate otherwise are welcome.
2. You're not compliant with the license.  To do so we'd have to add a menu that spits out the copyright notice.
3. Just use std::something if you want a "better" RNG, I'm going to push back hard on anything else.

**Comment by remyroy** [comment]
It's all good. I'm closing this.

**Comment by sparr** [comment]
Couldn't we still use all the augmenting code you wrote and just use a standard generator instead of this one?

**Pull request closed without merging**
