### PR TITLE
My first small pull request to README.md

### PR DESCRIPTION
**Pull request by uzername**
This is my first pull request. Is it successful? I'm studying git/github capabilities now so don_t beat me hard ._.

### CODE REVIEW

**Comment by chaosvolt** [comment]
...I just realized how many times this has been referenced accidentally due to Github formatting. XD

**Comment by narc0tiq** [comment]
Yeah, the early-numbered issues tend to clutter up hilariously like this.

**Review by artkirienko — COMMENTED** [review]
👀👍

**Comment by Throwaway-name** [comment]
Commenting and connectivity test.

**Comment by sonphantrung** [comment]
99999 commits later....

**Comment by anothersimulacrum** [comment]
Not to be rain, but there were at least ~340 commits before this.

**Comment by DukePaulAtreid3s** [comment]
So this is where it all began...

**Comment by DukePaulAtreid3s** [comment]
So this is where it all began...

**Pull request merged**
