### PR TITLE
Claws can now butcher corpses

### PR DESCRIPTION
**Pull request by AnotherSeawhite**
#### Summary
None

#### Purpose of change
Someone in Community Server Discord mentioned that claws can't butcher corpses, despite having butcher quality.

#### Describe the solution
Simply change the claws' cut quality from 1 to 2.

#### Describe alternatives you've considered
Not doing it.

#### Additional context
I can confirm that cats can "butcher" something in real life. My cats occasionally bring something for us, and one of them... was a mess.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Butcher and shred to pieces isn't the same thing. You get a mess from shredding, and you get usable pieces of meat, organs, bones, etc. from butchering.

**Comment by AnotherSeawhite** [comment]
> Butcher and shred to pieces isn't the same thing. 
Claws have only 4 (or 6) butchering quality, so it wouldn't yield usable stuff that much.
Wouldn't be a concern if you could eat the corpse right away, but that's not a thing, so I'd assume this is a workaround for that.
Also considering the mutants are (were?) humans (or have human-like intelligence), they would make use out of what they have.

**Comment by AnotherSeawhite** [comment]
There could be oversight issues, like being able to make a smoking rack with your claws, but until the "eating corpse right away in case of emergency or you don't care eating it raw" feature gets introduced, this is the only way.

**Comment by fairyarmadillo** [comment]
Is there a reason basic butchery needs Cut 2? Could we at least allow Quick Butchery, Field Dress,  and Bleed to use Cut 1?

**Comment by AnotherSeawhite** [comment]
> Could we at least allow Quick Butchery, Field Dress,  and Bleed to use Cut 1?

Definitely a better solution, but it's beyond my level to PR that.

I'll close this PR if someone makes a solution for this.

**Comment by AnotherSeawhite** [comment]
Turns out the butchery requirements are written in JSON. I'll discuss this in communities and make a PR.

**Pull request closed without merging**
