### PR TITLE
[CR] Performance boost for SDL ASCII drawing. (SDL Direct3D currently)

### PR DESCRIPTION
**Pull request by DanmakuDan**
~~(Temporarily includes #19066 benchmarking in the debug menu.)~~

This PR helps to deal with some of the slowness from #19071, by replacing SDL_RenderFillRect with a SDL_RenderCopy of a color modulated texture (https://wiki.libsdl.org/SDL_SetTextureColorMod). If the color modulation is not available, it will fall back to normal SDL_RenderFillRect behavior. The RenderCopy is applied in FillRectDIB in `sdltiles.cpp`, so all draw operations for text should be affected. The usage of SDL_RenderFillRect in the minimap code was also updated.

I'm not sure if the solution works for Mac yet (see profiling below), so this is marked as a solution so far for SDL's usage of Direct3D in rendering.

The benchmarks used were 2 with minimap closed, 2 with minimap open, and 2 with minimap closed again:

Integrated graphics, ASCII, before changes:
int_before_ascii
Integrated graphics, ASCII, after changes:
int_after_ascii
Integrated graphics, Tiles, before changes:
int_before_tiles
Integrated graphics, Tiles, after changes:
int_after_tiles
Dedicated graphics, ASCII, before changes:
ded_before_ascii
Dedicated graphics, ASCII, after changes:
ded_after_ascii
Dedicated graphics, Tiles, before changes:
ded_before_tiles
Dedicated graphics, Tiles, after changes:
ded_after_tiles

Overall, there are improvements for everything but integrated graphics Tiles rendering. The benchmark code is in this PR to facilitate confirmation of performance improvement.

There is some further improvement to be gained by having all font glyphs in one texture, but that has a more complicated implementation.

### CODE REVIEW

**Comment by BrettDong** [comment]
Testing on my mac.

**Comment by BrettDong** [comment]
| Interface | FPS(debug) |
| ASCII in SDL | 17.601 |
| tiles in SDL | 31.987 |

**Comment by DanmakuDan** [comment]
For your Mac benchmarks, is SDL 2.0.5 available? Also, how far in depth can you get on the profiling info?

**Comment by BrettDong** [comment]
1. I'm going to do a profiling on debug builds. 

2. I'm using SDL 2.0.4 currently. I'll try to build a SDL 2.0.5 from source later to see if there's a difference.

**Comment by BrettDong** [comment]
Above is the profiling of release build.

**Comment by DanmakuDan** [comment]
Are there any driver updates for your graphics card? I don't have much else to go on since the profiler indicates that GL_RenderCopy takes nearly all of the rendering time. SDL's openGL rendering source is here (https://hg.libsdl.org/SDL/file/03531deafb03/src/render/opengl/SDL_render_gl.c line 1304), and I'm not sure where the more expensive gleBeginPrimitiveTCLFunc from the profiler is located.

**Comment by BrettDong** [comment]
Graphics driver are integrated in mac OS. I have no idea why OpenGL functions would take up so much time. GPU performance shouldn't be a bottleneck here. Although I'm using an integrated GPU (Intel HD Graphics 6000), it has no problem playing those fancy commercial games eg. COD:AA, FIFA 16, DiRT, Battlefield 3 under normal settings at 30 fps.

**Comment by DanmakuDan** [comment]
I think the rendering requires our own openGL implementation, since SDL's compatibility restricts how much performance can be gained from these optimizations. Sprite batching would be really useful for the rendering the game does.

Alternatively, if you check in `sdltiles.cpp` and replace the code in `WinCreate()` where the hardware accelerated renderer is created (first `if` statement):
```
    if( !software_renderer ) {
        dbg( D_INFO ) << "Attempting to initialize accelerated SDL renderer.";

        int numRenders = SDL_GetNumRenderDrivers();
        int rendertouse = -1;
        for(int ii=0;ii<numRenders;ii++){
            SDL_RendererInfo ri;
            SDL_GetRenderDriverInfo(ii,&ri);
            std::string riname = "opengles";
            if(riname==ri.name){
                rendertouse=ii;
                break;
            }
        }
        renderer = SDL_CreateRenderer( window, rendertouse, SDL_RENDERER_ACCELERATED |
                                       SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_TARGETTEXTURE );
        if( renderer == NULL ) {
            dbg( D_ERROR ) << "Failed to initialize accelerated renderer, falling back to software rendering: " << SDL_GetError();
            software_renderer = true;
        } else if( !SetupRenderTarget() ) {
            dbg( D_ERROR ) << "Failed to initialize display buffer under accelerated rendering, falling back to software rendering.";
            software_renderer = true;
            if (display_buffer != NULL) {
                SDL_DestroyTexture(display_buffer);
                display_buffer = NULL;
            }
            if( renderer != NULL ) {
                SDL_DestroyRenderer( renderer );
                renderer = NULL;
            }
        }
    }
```

you can try out the `opengles` and `opengles2` renderers (change `riname` string so it checks for one of them) that might be available for your system (the game automatically picks the `opengl` renderer because it fits the rendering requirements first).

**Comment by Coolthulhu** [comment]
Has merge conflict.

Do we have any active dev who has tiles set up?
I can set it up, but I'm on Windows, where tiles can be a pain to build.

**Comment by DanmakuDan** [comment]
The merge conflict should be resolved.

**Comment by mutability** [comment]
Since there are a relatively small number of colors used for filling via FillRectDIB, how about creating a texture with a pixel per color and blitting from a rectangle within that? Then you don't need to rely on support for SetTextureColorMod.

I did this when playing with SDL_gpu:

https://github.com/mutability/Cataclysm-DDA/blob/9a070a715ec519c49e58561e1b1fcd131b8fe696/src/sdltiles.cpp#L481

https://github.com/mutability/Cataclysm-DDA/blob/9a070a715ec519c49e58561e1b1fcd131b8fe696/src/sdltiles.cpp#L1761

Haven't followed the minimap stuff back, it may still need the general case.

**Comment by DanmakuDan** [comment]
Closing for now, #19412 provides a more comprehensive fix for these rendering issues.

**Comment by ZhilkinSerg** [comment]
Reopened in #21748.

**Pull request closed without merging**
