### PR TITLE
Improve ammo belts

### PR DESCRIPTION
**Pull request by mugling**
Factored out of #17860

Allows setting of `default_ammo` for specific magazines and improves the naming of ammo belts.

Before: .223 belt with .223 remngton
After: .ammo belt with 5.56 NATO

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Pretty sure it's this one that breaks generic guns.

**Comment by mugling** [comment]
Trivial fix could include setting appropriate `default_ammo` for ammo belts in generic guns mod?

**Comment by Coolthulhu** [comment]
Yes, that would probably work.

**Comment by mugling** [comment]
Includes fix for generic guns. Ready

**Pull request merged**
