### PR TITLE
Remove some ferals, rework some others

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
We had a bunch of ferals that made no sense. This removes some of them.

#### Describe the solution
1. Feral swimmer - ~~uses a kickboard to fight. Wears nothing. Deathly convinced it needs to stay where it was swimming prior to the psychosis onset and considers an oversized chunk of plastic a good weapon. This is not something that'd survive, nor is there any good reason why this would not become a normal feral wielding a weapon.~~ **EDIT: No longer being removed. They no longer are better swimmers and use a stick instead of a plastic kickboard. Will spawn only if the season isn't winter and stop spawning roughly in the middle of the first autumn.**
2. Feral diver - as outlined in the comments of  #67677, it's one of the ones that make the least sense. There's no way a feral could operate diving equipment. Check comments for a more detailed debate/explanation for this one.
3. Feral archaeologist - ~~extremely obscure spawn only in some mine finales. Our mines are already iffy as is, we don't need to add an Indiana Jones to the mix. Not to mention that the odds of specifically an archaeologist (singular!) being in a NE mine at the time of C-day and surviving until the events of the game (as a feral but this still matters) are ungodly low~~ **EDIT: No longer being removed. Will now spawn only in the aboveground buildings of mines, so that their existence is actually plausible. Given the ingame snippets, if we assume those haven't gone outdated, presence of archaeologists in the region would be granted.**
4. Armored ferals - ~~they would make a limited amount of sense if they wore imitation armor and used fake weapons but no, they have proper armor and weapons. Why would a mansion have those, and why would it have enough full sets for several armored zombies? The odds of this are extremely low, and it joins the archaeologist in the niche content club~~ **EDIT: No longer being removed. WIll now appear more rarely at mansions, have had their obsoleted gear removed from possible loot and will now wield replica weapons instead of proper medieval weaponry. They live to fight another day, at least until someone bothers to rework mansions to not be weird central.**

#### Describe alternatives you've considered
1. Anything that shoots guns, but we don't have a clear outline on whether our ferals are smart enough to reload or not. Even if assuming that they don't, a few would be able to spawn in locations where they wouldn't have been able to use up the ammo. It's a weird grey area
2. Servants and Well-Dressed. They are both extremely iffy, and servants specifically make me uncomfortable but besides the weirdness of descriptions and lootgroups there's no reason why a servant/maid/whatever wouldn't go feral so...
3. Starers need some love, specifically with the odds of them happening. They are supposed to be fungal-infected ferals that became burned when unconscious (i.e. our current death state, because we don't have support for unconscious monsters) but survived and the Mycus healed them up. This would be rare but not impossible, the problem I have is I don't know how to make this process happen very rarely when a fungal feral is burnt, as opposed to 100% of the time

#### Additional context
I said I wouldn't do that in #67677, and I didn't. But I am a weak man.

### CODE REVIEW

**Comment by Karol1223** [comment]
> Remove SWIMS and it's just a variation of feral with stick which is fine. AFAICT its spawn locations are appropriate.

This is actually not a bad argument. Regardless, it would need something else to wield, but I suppose a stick is good enough.

> Remove NO_BREATHE and it's fine; same as above.

I disagree with that. Finding a diver is relatively a rare thing, and although it may not be impossible the spawn locations are certainly off.

> It survived because it ate the other archaeologists, hence why there's a singular feral dude. They're not dressed up like Indiana Jones so they're not just memes either.

The absolute utter odds against this happening still apply. I don't agree that this is good material for a feral.

> So give them poor quality weapons+armors and reduce their number?

This would be a good way to go about this, but would require me to add new items for non-functional medieval armor, which is beyond the scope of this or my interest. If someone wishes to bring them back from the dead reworked and using these items, which would (to my knowledge, if I am wrong please correct me) need to be added first, they're free to do so - the code will still be available in older versions on GitHub. As it stands, they are quite literally the easiest source of the weapons they use *and* make little sense.

**Comment by Night-Pryanik** [comment]
I hope someday you'll create something great and put all your soul into the creation process, and someone comes in and opens a PR in which he will cut your content with some goddamn stupid and highly subjective rationale.

**Comment by Karol1223** [comment]
ALRIGHT! So as always with the monster obsoletions, second iteration:

1. Swimmers are back, I gave them a stick instead of a kickboard like Andrei said (forgot to take ``SWIMS`` away, I'll do that in a second) and they are actually acceptable right now in my book. A little bit weird, but not any weirder than swimmer zombies and perfectly acceptable.
2. @John-Candlebury convinced me to bring back Armored zombies, though for now they are restricted back to the mansion start. The problem with them is more that our mansions are all around not what they should be (or they are way too common, or both). The armored zombies still have the problem of carrying real gear, though, and they are the easiest source of real maces and battleaxes in the game currently from my experience, so I don't know what to do with their spawns. They certainly should not be as common as they currently are in the game.
3. Divers I don't consider negotiable. Like give me it's backstory. It's clad in diving gear, so C-day and psychosis must have struck either between the time of it gearing up in it and diving, between the time since it came up and it taking the gear off or while it was underwater ***and then it had to live through the initial C-day bullshit, remember and function enough to swim back up before it runs out of oxygen and get the gear off so it could breathe***. The odds are against this one in every way.

**Comment by anoobindisguise** [comment]
Armored Ferals are holders of a bunch of obsolete items like the old armor_lightplate and chainmails so at bare minimum that should be fixed.

**Comment by ampersand55** [comment]
> Like give me it's backstory. It's clad in diving gear, so C-day and psychosis must have struck either between the time of it gearing up in it and diving, between the time since it came up and it taking the gear off or while it was underwater and then it had to live through the initial C-day bullshit, remember and function enough to swim back up before it runs out of oxygen and get the gear off so it could breathe. The odds are against this one in every way.

Perhaps solo divers were some of the first victims of the blob as it entered the groundwater  Divers made the perfect test subjects to fine-tune the feralization process as they were isolated and would be presumed to have died in diving accidents if they went missing.

**Comment by Karol1223** [comment]
> Perhaps solo divers were some of the first victims of the blob as it entered the groundwater Divers made the perfect test subjects to fine-tune the feralization process as they were isolated and would be presumed to have died in diving accidents if they went missing.

This implies conscious infection choices and processes from the Blob. We don't do that here.

**Comment by fairyarmadillo** [comment]
> 1. Swimmers are back, I gave them a stick instead of a kickboard like Andrei said (forgot to take `SWIMS` away, I'll do that in a second) and they are actually acceptable right now in my book. A little bit weird, but not any weirder than swimmer zombies and perfectly acceptable.

I have one problem with this and it's that ferals would not be able to survive living in a river or even a pool for any length of time. There is nothing to eat there and hypothermia would be a serious risk around game start time. Anyone who went feral near a body of water would need to head toward a place with food and shelter or they would quickly die of exposure or dehydration.

**Comment by Karol1223** [comment]
> I have one problem with this and it's that ferals would not be able to survive living in a river or even a pool for any length of time. There is nothing to eat there and hypothermia would be a serious risk around game start time. Anyone who went feral near a body of water would need to head toward a place with food and shelter or they would quickly die of exposure or dehydration.

I think it's safe to assume that if the ferals made it into the ingame events they're capable of taking care of basic needs like thirst, hunger and temperature, though you do have a point that them running around in swimwear doesn't bode very well for their longevity...

**Comment by ampersand55** [comment]
> > Perhaps solo divers were some of the first victims of the blob as it entered the groundwater Divers made the perfect test subjects to fine-tune the feralization process as they were isolated and would be presumed to have died in diving accidents if they went missing.
> 
> This implies conscious infection choices and processes from the Blob. We don't do that here.

I'm admittedly not super familiar with Blob lore, but in the lore document (unless what I'm using it's outdated or I have misunderstood something) it seems it does act deliberately in spreading and have phases with different strategies. 

> January: The blob reaches satisfactory global-level groundwater saturation and makes the decision to commence the concentration and replication phase.

https://docs.cataclysmdda.org/Lore/lore-background.html#year-0-the-current-irl-year-1

If it had a spreading phase, a concentration phase and a replication phase, perhaps it also had a testing phase? If it's not so omniscient that it doesn't need any testing. 

It doesn't have to be the Blob with a capital B making deliberate these strategic choices, but the XE-037 sample employing a standard multi-phase planetary takeover-strategy with some degree of autonomy.

I dunno, I'm just trying to make sense of feral divers.

**Comment by Karol1223** [comment]
> I dunno, I'm just trying to make sense of feral divers.

That's the problem. Making sense of content should be done when it's being added, not as a last ditch effort to keep them in the game. The Blob's infection process (to my understanding, which admittedly may be wrong) is more like an immune response. It wouldn't purposefully affect only divers because it knew they were a better target. Them being more exposed may be a different story, but realistically they wouldn't be much more exposed than anyone just... you know, swimming

**Comment by ampersand55** [comment]
I agree that would be the best way of going about it. I was just using "Like give me it's backstory" as a writing prompt to give an ad hoc justification for feral divers.

In general I agree with your OP and that ferals should make sense.

**Comment by ilovehans10** [comment]
I don't like the idea of removing the archaeologist just because it's "extremely obscure". There are a lot of spawns that are rare or are flavor that make the game world feel much more lived in, and I feel like this is one of them. It also makes the snippets for the mines about [how there were some archaeologists down in the mine investigating the Amigara Fault](https://github.com/CleverRaven/Cataclysm-DDA/blob/8c55459790690a58ce73dce68af197fd843ddfa1/data/json/snippets/amigara.json#L20C7-L20C7) make more sense. For that matter, why aren't there more ferals in the mines? I can't seem to find any reference to a feral miner, which it seems like would be a logical addition to the mines.

Also, I would like to say that monotasks from #61505 might make things like diver zombies make a little more sense to people. This might mean that divers don't make sense as ferals, but they do make some sense as monotasks that are stuck forever diving. The fact that diving gear is complicated to use doesn't mean that a monotask can't use it. A monotask isn't simply fueled by rage, but is instead in a state of blob psychosis that makes them zeroed in on diving, and upset at anything that might stand in their way.

**Comment by Karol1223** [comment]
> I don't like the idea of removing the archaeologist just because it's "extremely obscure".

There's more, and it also ties down to your later point about more ferals in mines:

1. Assuming that the snippets were right and there were pre-C-day archaeological expeditions into the mines then okay - you have archaeologists in the region. That solves the problem of plausibility
2. The archaeologist, at least one, would have had to go feral. Which is a dice roll on C-day, but isn't technically that rare. If it ended here I would say it'd be fine as a unique encounter
3. Somehow that feral would have had to survive in the mines. Even if we assume that like Andrei said the feral would eat it's team-expedition friends the two issues are that it'd have to somehow eat them raw and survive while also eating them all before they zombify as that'd taint the meat and kill it. Second issue is it getting water, but I suppose we can handwave it as there maybe being some subterranean water in the mines
4. Mines are home to monsters that don't play on team feral. You've got Amigaras and Things as just a few examples. They would kill a feral first opportunity they get.

> Also, I would like to say that monotasks from https://github.com/CleverRaven/Cataclysm-DDA/issues/61505 might make things like diver zombies make a little more sense to people. This might mean that divers don't make sense as ferals, but they do make some sense as monotasks that are stuck forever diving. The fact that diving gear is complicated to use doesn't mean that a monotask can't use it. A monotask isn't simply fueled by rage, but is instead in a state of blob psychosis that makes them zeroed in on diving, and upset at anything that might stand in their way.

I don't disagree but that's extremely heavy what-if territory. Nobody even started works on monotasks. If we want a monotask feral, it'd have to be coded differently regardless. And how it would have to be coded is a question for if/when someone actually implements monotasks. This is not a blocker for the removal of our current feral diver, as these two would be separate entities regardless.

**Comment by Karol1223** [comment]
> I'm not sure what "c-day" is that you're referring to, but the apocalypse happened gradually over several weeks. People went feral at various times in there, some went very feral and got better. There are gradations of feral from "barely functioning monster" right up to the not yet depicted in game "almost normal human, can speak and reason".

This DOES indeed change a lot. Any time on the devcord I've been on a discussion about ferals it came back to that ferals happened during a specific event, and from there on no new ferals were created. If this is NOT the case, the situation is different, though I'm not sure how much for those specific two.

The archaeologist matters mostly how much from when shit broke down we assume the default start to be - which frankly I don't know because I heard everything between 2 days to 2 weeks. If it *is* 2 weeks, I don't believe any would have survived until then. If it's just a few days they would work as a rare spawn that stops happening a month or so in.

The divers I still can't see functioning at all, though. As monotasks? Maybe. But if a feral is functioning enough to not only handle diving equipment but also seek new air tanks or refill used tanks, I don't know if this is still something that should be handled via monster code. That's way beyond any ferals we have and I'm not convinced would be a common encounter.

**Comment by ilovehans10** [comment]
> This DOES indeed change a lot. Any time on the devcord I've been on a discussion about ferals it came back to that ferals happened during a specific event, and from there on no new ferals were created. If this is NOT the case, the situation is different, though I'm not sure how much for those specific two.

I am not personally on the devcord, but from what I read in a lot of the lore documents is that people went [mad over the span of months](https://docs.cataclysmdda.org/Lore/lore-background.html#year-0-the-current-irl-year-1). I don't remember where but somewhere in exodii lore it was mentioned that the player character would never be accepted into the exodii as they are too much of a risk-taker, which was caused by the blob just as another example. There have also been additions of frightened people who have been put into a permanent state of panic by the blob. Yes, a lot of the time the blob made people more violent, but that doesn't mean it made them less intelligent, or forget how to do their favorite hobbies.

> The archaeologist matters mostly how much from when shit broke down we assume the default start to be - which frankly I don't know because I heard everything between 2 days to 2 weeks. If it is 2 weeks, I don't believe any would have survived until then. If it's just a few days they would work as a rare spawn that stops happening a month or so in.

Making them spawn early on might be a good solution. Another solution would be to make them spawn in the offices for the mine. This would make it so that their needs being abstracted are more logical, and would make them more likely for the player to encounter. This could also lead the player wondering why a mine would have an archeologist on site and want to go exploring for that reason.

> The divers I still can't see functioning at all, though. As monotasks? Maybe. But if a feral is functioning enough to not only handle diving equipment but also seek new air tanks or refill used tanks, I don't know if this is still something that should be handled via (current) monster code. That's way beyond any ferals we have and I'm not convinced would be a common encounter. I am of the belief that if we want divers to be so high functioning they should still be in timeout until monotasks. Though it is entirely possible I'm misunderstanding the core concept here as well, be it with real-world diving (I have no experience myself so I'm trusting your judgment on operating the equipment itself) or monotasks

Removing a type of enemy because they have been abstracted until they can be fully implemented doesn't seem like the right call here to me. It is true that we do not yet have a way to make monotasks do things like refill their air tanks or eat. But removing an enemy type just to add them back in eventually feels like it is just keeping an enemy type from getting play testing.

I guess this is sort of the way that I feel about a lot of ferals. They have a lot of their needs abstracted away, and feral cops might eventually have their cousin the monotask cops added, who go around arresting anyone who breaks the law. Until then, it is good having a feral cop in the game so when their attacks and armor can be better balanced now and easily copied to their cousin later. Yes, it is sort of backwards and leads to some enemies that don't make tons of sense with player facing information, but it can help pre-balance future features.

**Comment by Karol1223** [comment]
> but that doesn't mean it made them less intelligent, or forget how to do their favorite hobbies

This is a bold claim that I am very much not convinced about.

> Another solution would be to make them spawn in the offices for the mine. This would make it so that their needs being abstracted are more logical, and would make them more likely for the player to encounter. This could also lead the player wondering why a mine would have an archeologist on site and want to go exploring for that reason.

I applaud you because I didn't think it'd be possible to make a completely reasonable argument for the archaeologist and yet you did. This is 100% fair, and a good idea I believe. If I can figure out how to make monsters spawn via mapgen (I only ever made them no longer spawn in the past) I'll tackle that tomorrow if I manage to figure it out.

> Removing a type of enemy because they have been abstracted until they can be fully implemented doesn't seem like the right call here to me

This unfortunately is 100% subjective and I have to play the devil's advocate... or my own advocate in this case, I suppose. While I would love to support the idea that monotaskers are a matter of "when", they really are not. Having an issue open for something is MILES ahead of just floating the idea around, and I would hope that one day we do get monotaskers, but unfortunately we've had issues (and PRs!) that have been floating around for months or even years in some cases without anyone picking them up. I would 100% agree with you if there was a PR open implementing monotaskers or some code for more advanced ferals, but unfortunately as it stands I disagree. Having said that - hell if I have any idea just how much a monotasker diver would differ from a normal feral diver. I like to believe more advanced AI but... our NPCs already sorta struggle there (though I do admit Erk has been putting in work in that regard which is great to see). And what else could it be? NPC health system? That's not very ideal either. I'd actually like to hear Erk's opinions on this, because it's entirely possible I got caught up here and a more advanced feral diver would function identically, as you wouldn't be able to see their intelligence at first glance that well. What I would hope for is it actually having a functional scuba tank system i.e. being able to spend time underwater for a limited amount of time only, but I couldn't tell you if that's a reasonable expectation.

**Comment by I-am-Erk** [comment]
I'm not super familiar with the feral diver. Is your concern just that they can apparently hook up oxygen tanks? Or is it something to do with their other abilities?

Frankly, hooking up a tank just isn't that hard. It's comparable to say, reloading a weapon. It's already in the lore that ferals can sometimes handle that stuff. They should be very rare, but there's nothing inherently challenging around the concept. Alternatively, a feral snorkeler would be a possible intermediate design

**Comment by Karol1223** [comment]
> I'm not super familiar with the feral diver. Is your concern just that they can apparently hook up oxygen tanks? Or is it something to do with their other abilities?

The oxygen tanks is mainly from storytelling perspective, frankly. Though according to HHG (didn't check the lootgroup in detail yet), they don't have 100% chance to spawn with a tank in the first place, which is weird, but I'll look more into that later today probably. Frankly my main concerns are:
1. Since it has ``NO_BREATHE`` it is capable of indefinitely staying underwater and in any gasses without any adverse effects. In theory this isn't as big of a deal, because realistically how often are you gonna use tear gas against a diver, but that's one thing.
2. Second, which I am not 100% familiar with how it works in the C++ land, frankly - it's speed. It has a speed of 100 on land, and unless ``SWIMS`` already makes it proportionally faster in water, we can't make it better at swimming but, due to having fins (at least presumed, as it's supposed to be in diving gear - again, according to HHG only ~16% of having those, I'll need to look into that) it should not be as fast as the player on land. This is mainly a problem for my other PR, #67677, because due to this divers suddenly become really strong land enemies as well with their knives.

**Comment by fairyarmadillo** [comment]
> I'm not super familiar with the feral diver. Is your concern just that they can apparently hook up oxygen tanks? Or is it something to do with their other abilities?
> 
> Frankly, hooking up a tank just isn't that hard. It's comparable to say, reloading a weapon. It's already in the lore that ferals can sometimes handle that stuff. They should be very rare, but there's nothing inherently challenging around the concept. Alternatively, a feral snorkeler would be a possible intermediate design

Feral divers are just randomly scuba diving around New England lakes and rivers in early spring, often nowhere near any zombies and in areas that have a lot of aggressive mutant insects and no resources for the diver to eat.

I know ferals can behave arbitrarily, but even if this is a particularly intelligent feral, why are they behaving this way? It's not like there's anything in the water for them.

**Comment by Zireael07** [comment]
re: "nothing for the feral diver to eat": Aren't there fish in the lakes/springs?

**Comment by fairyarmadillo** [comment]
> re: "nothing for the feral diver to eat": Aren't there fish in the lakes/springs?

So the blob is having our guy is use complex equipment to perform a leisure activity 24/7, and in order to survive he's spending 90% of his waking time fishing in an uninhabited area, just on the off chance that the main character of the apocalypse happens to pass by?

**Comment by Karol1223** [comment]
Actually, this made me realize something else about divers - if we assume they're smart enough to refill a scuba tank - are we assuming the proper setup with an air compressor? How do they get the air compressor running at that point? This is quite literally NPC levels we're reaching here... Or can scuba tanks just be safely refilled with normal atmospheric air? I am pretty sure they can't, but it's not like I ever researched that topic.

**Comment by fairyarmadillo** [comment]
Also, what are they doing diving? A feral prepper etc is just trying to survive and will shoot at any humans who walk by. A feral security guard is stuck in their workplace and is going through the motions of "protecting" it. Ferals in town are basically zombies that eat and sleep sometimes. Why is a feral diver leaving town, walking or driving all the way to the river, putting on complicated dive equipment, and entering the water? There is no explanation that doesn't feel like an attempt to justify the enemy after the fact. It just seems goofy and player-centric when you run into it.

**Comment by Karol1223** [comment]
Drafting it until I get the time to look closer at making the Archaeologists spawn with what Devengel commented. As it stands I think afterward, though, the PR is gonna be in a solid state since there seems to be more arguments against Divers.

**Comment by Karol1223** [comment]
@Devengel could I get a review from you on this to double-check if I understood you correctly?

**Comment by Devengel** [comment]
> @Devengel could I get a review from you on this to double-check if I understood you correctly?

Just tested it, Looks good to me 👍

**Comment by Karol1223** [comment]
In this case I believe this PR is in an acceptable state

**Pull request merged**
