### PR TITLE
JSONize NPC talk tags

### PR DESCRIPTION
**Pull request by Coolthulhu**
Moves all the tags like `<ok>`, `<yawn>` and `<ill_kill_you>` to jsons.

Reusing the `text_snippets` class because it does most of what I'd like to be done here already.

Could conflict with the regular snippets, but that would require someone to use a `<>` bracketed category, meaning it's unlikely. The results would be harmless, but quite silly - NPCs using company slogans instead of swear words and the like.

### CODE REVIEW

**Comment by BevapDin** [comment]
The snippet supports a terse syntax: the "text" member can contain an array of strings instead of a single string. Each entry of the array is loaded as separate snippet of the given category.

**Comment by kevingranade** [comment]
In other words it'd probably be reasonable to have just one file for all of these with one entry per type of statement.

**Comment by Coolthulhu** [comment]
1000 lines removed

**Comment by Coolthulhu** [comment]
I marked this one as priority because pretty much all NPC code that adds new dialogue will conflict or depend on it.

**Pull request merged**
