### PR TITLE
The Trencher

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Construction vehicle that can be used to quickly create trenches (represented as lines of shallow pits ingame). Basically copies the functional of plow vehicle part, except for it creates shallow pits instead of dirt mounds.
Something like this:

800px-a_marais_micro_trencher_machine_-_side_cut_rt100

Inspired by @mlangsdorf's request in #24243.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
default

It might not be the greatest fortification evar, but it took me less than half an hour to encircle this cabin with trenches.

**Comment by mlangsdorf** [comment]
You're the best. Thanks.

**Comment by Mecares** [comment]
Can it be used against Zombies directly?

**Comment by Night-Pryanik** [comment]
> Can it be used against Zombies directly?

Well, yes, like most other vehicle parts. The rockwheel also has rather high `damage_modifier`, so one can probably mush zombies with it.

**Pull request merged**
