### PR TITLE
Aim overhaul and guns/gunmods balance

### PR DESCRIPTION
**Pull request by wwkk222208**
#### Summary
Balance "Aim overhaul"

#### Purpose of change

The current aiming time has the following problems:
1.The aiming speed of sights is almost ineffective, which results in the rifle scope is always the best choice, and the sights for CQB (such as laser sights) are trash.
2.The difficulty of high-precision shooting is not reflected. Whether it is a sniper rifle or a carbine, the aiming time they need is almost the same.
3.Due to the problem of setting the aiming attenuation curve, semi-automatic shooting can be accurate and high rate of fire at the same time, and the advantage of automatic shooting is not reflected.

The purpose of this PR is to solve the above problems, and make firearm and gunmods more distinctive and effective.

What are the new features of this PR？

**Change shooting process**
The new aiming process is divided into 3 steps: Rapid draw->Aim with laser sight(if it is available)->Aim with selected main sight->Fire->Backswing. 

Rapid draw: In the progress of rapid draw, skill of character is not so important and sights do not work, short and small weapons will help you a lot. 

Aim with laser sight: After rapid draw, if your prey is in a place where the light is not too strong and not far from you, you can quickly locate it with the cursor projected by the laser sight.

Aim with selected main sight: If the laser sight fails to work, you need a red dot sight or a holographic sight to quickly lock the target. Or the target is too far away, you need ACOG or rifle scope to aim accurately. You can also install offset sights to deal with different enemies. The default w key switches sights. Note that having switched sights will reset a small amount of aiming progress (because you usually need to tilt the gun).

Fire: The firing time is relatively fixed, and will no longer change drastically as the skill level changes. Because the skill level can effectively speed up the aiming speed in this PR.

Backswing: If the weapon recoil is too strong, you need to spend some time to maintain your balance. Here I borrow the concept of backwing in the MOBA game. For ordinary people (str=8), there is usually no need to worry about backswing unless you hold a .50 caliber rifle and shoot.

**Strengthen the characteristics of different types of weapons**

Pistol: Pistols have the fastest rapid draw speed and no punishment for fighting in a confined space.Although they are sometimes less powerful, they are still good secondary weapons.

Shotgun: Shotguns no longer have the advantage of fast aiming speed, but have high damage to unarmored creatures at close range aoe ability instead. When using a shotgun, you usually don’t need precise aiming. You only need an estimated hit rate of 50%, which can often cause considerable damage.
(Thanks Kevin. The shotguns live up to their name. But in the master version they still behave like short-range rifles. In fact, the shot spread in the real world is more prominent than in the game. 
shot_strings_choke_effect
So shot spread has been increased a lot in this PR.)

SMG: Shotguns no longer have the advantage of fast aiming speed as well. They now have very little recoil ability during automatic shooting and almost won't cause backswing.

Carbine or small-caliber rifle: The performance of the carbine or small caliber rifle is similar  to the SMG, which is also suitable for CQB operations. But without mods to reduce recoil, the automatic shooting accuracy will not be ideal.

Full power rifle: The full-power rifle can be equipped with a high-magnification scope to act as a sniper rifle or marksman rifle (it will take more time to aim). But you can also install red dots or holographic sights on shorter one of them for close combat(eg. M14-EBR), if you can solve the problem of recoil.

Large-caliber rifle and MG:They are powerful, but usually need to cooperate with bipod to offset the excessive recoil. (Ordinary people wield large-caliber rifle shooting is very fantasy, but this is very common in previous versions).

Bow: It is difficult for beginners to use, but as the proficiency increases, the archer’s aiming speed and accuracy will be significantly improved. Their power is still relatively low.

Crossbow: Sorry, they are still difficult to use, and basically no optimizations have been made to them in this PR.

**Enhance gunmods**
Rifle scope: A kind of extremely precise sight, and can offset most of the perception penalty. But its aiming speed is very slow.
ACOG scope: ACOG scopes  designed to be used with the "Bindon Aiming Concept" can guarantee  aiming speed and high precision at the same time.

Laser sight: They are very good sights for cqb, which can effectively improve the aiming speed. But it is invalid when the target is in a place with too high brightness or too far away from the shooter.

Holographic sight and red dot sight:They can effectively increase the aiming speed, but do not increase the aiming accuracy too much compared with the master version. Good for close combat.

Muzzle braker: They can effectively reduce the recoil of firearms in reality, but their performance in the current game is too poor. So their ability to reduce recoil has been greatly enhanced. 

Choke(new): Chokes can shapes the spread of the shot cloud to gain better range and accuracy.

4.**Miscellaneous modifications**

The size of the gun affects the speed of rapid draw.

The length of the gun affects the speed of rapid draw when shooter is in a confined space.

Accuracy improvement has obvious marginal effects, and in many cases precision shooting is not the best choice.

The accuracy error caused by low skill proficiency is no longer affected by the accuracy of the firearm itself. Because according to the original setting, novices should use high-precision guns, which obviously does not conform to the facts.

The first aiming time becomes shorter but the subsequent aiming time becomes longer.

The sum of recoil of continuous automatic shooting will converge, which is consistent with reality.

#### Describe the solution

Many codes have been changed, so here are only some important changes.

1.Modified function'aim_per_move', 'get_fast_sight' to overhaul the aiming mechanism.
2.Modified function ‘fire_gun’ to introduce backswing.
3.Writed function 'laser_sight_available' to judge if laser sights are available.
4.Writed function 'aim_factor_from_length', 'aim_factor_from_volume' to introduce the effect of gun volume and length on shooting.
5.Modified function ‘do_aim’'get_aim_types''target_ui::run''..etc to introduce function of sight switch.
....
#### Describe alternatives you've considered

Maybe so much content shouldn't be put in one PR. However, any change may have an inestimable effect on the whole, so I put all the content together and push it.
#### Testing
To be continued.

#### Additional context
The content of this PR is too much, and I personally inevitably have some omissions. Looking forward to your `suggestions.`

### CODE REVIEW

**Comment by BrettDong** [comment]
You need to follow the format for summary line:

#### Summary

Category "Summary"

----

For example,

#### Summary
Balance "Aim overhaul..."

**Comment by BrettDong** [comment]
You are still missing the category and the quotes.

**Comment by BrettDong** [comment]
````
#### Summary
Balance "Aim overhaul..."
````

**Comment by Photoloss** [comment]
How does this affect the less "standard" weapons included under the mantle of "guns"? Recoilless rifles, rocket launchers with backblast, slings, CBMs and mutations, flamethrowers in "semi-auto", sci-fi guns and especially lasers? A key physical feature of radiation weapons is that they have basically zero recoil which might break that balancing aspect or else leave them overnerfed.

**Comment by BrettDong** [comment]
You may need to update ranged balance tests to agree with your changes.

**Comment by wwkk222208** [comment]
Thank you for

> 

Great views. I just tested them.
For A7 in the original version, the PR basically does not affect its power. Because in the original version, it could shoot continuously within a range of 30 very accurately. For laser weapons in some third-party mods, the rifle scope in this PR may make them more accurate, but I think the balance of this part should be considered by the third-party mod authors themselves.
Launchers are indeed overnerfed, and I will tackle this problem.

**Comment by Photoloss** [comment]
What about the CBMs, Assault Barbs mutation, and come to think of it all the pseudo item "guns" enemies use nowadays? Turrets, mechs, acid, thorn zombies, mi-gos and so on. Or do these changes only affect the player?

**Comment by kevingranade** [comment]
The most important feedback is you're doing too many things at once here. Aiming overhaul, adding chokes for shotguns, changing damage output of various weapons, etc.  You need to break out anything not directly related to the aiming overhaul into separate PRs.  The result of this is PRs can be more easily reviewed, and small and obviously correct changes (such as the shotgun choke change) can be merged quickly.  If you don't break the PR up, you will suffer from longer waits between feedback sessions as well as delays because parts of the PR are ready to merge but other parts are not.

You say the impact of splitting the PR is inestimable, but you have accuracy changes mixed together with damage and shot-specific changes at least, these have almost nothing to do with each other.  If you look, you will find other things you can split out and make incremental as well.

For specifics:

I like the "rapid draw" concept of relegating penalties from weapon size to a pre-aiming stage of shooting instead of applying them throughout the aiming process, the name is a bit unclear and misleading since it's not necessarily rapid, and it's never a draw. "bring on target" is more accurate but a bit unwieldy, we can come up with a better option.

The increase in shot spread is most likely correct, but needs to be broken out into a separate PR and have success criteria, ideally with a unit test just for shot spread.

The gunmod changes seem mostly good, though I want to see some support for muzzle brake effectiveness, and they can all be pulled into a separate PR.

The laser sight changes seem reasonable and can definitely be split out into a follow-up PR.

Manually switching sights is not ok, just select the most beneficial option and use it.

The backswing concept seems to overlap with recoil plus strength/skill based recoil mitigation, which is already present.  I'm not clear what it adds other than simply having a higher recoil value.

**Comment by wwkk222208** [comment]
Thank you Kevin. Your suggestion helped me a lot.
I will proceed to separate this PR.
At first I also thought that manually switching sights was not a good idea, because it would bring unnecessary burden to the player and it would be very complicated to implement. But why did I write this function in the end? Because according to the original automatic switching mechanism of sights, a sniper rifle always needs to be equipped with a secondary sight to help complete the mid-range aiming. Even if it only needs to shoot long-distance targets, this is very strange and unrealistic.
I have considered another solution, which is to introduce the time to switch sights, and calculate the best sight switch time point through the code. But in this way, we have to face the problem of how to judge which result is the best. And this is also very strange, because @ is not a super AI.
So in the end I decided to give this option to the player. In fact, in most cases, players do not need to manually select sights, because there are not many guns suitable for both sniper and close combat, and most guns do not need to be equipped with rifle scopes and holographic scopes at the same time.
Why was the concept of backswing introduced in this PR? Because without it, the 0.50 caliber rifle with the short barrel and the rifle scope removed would always be the best choice for CQB.(just ‘bring on target’ and fire).

**Comment by wwkk222208** [comment]
>Though there are numerous ways to measure the energy of a recoil impulse, in general, a 10% to 50% reduction can be measured. Some muzzle brake manufacturers claim greater recoil reduction percentages. Muzzle brakes need sufficient propellant gas volume and high gas pressure at the muzzle of the firearm to achieve well-measured recoil reduction percentages.
From https://en.wikipedia.org/wiki/Muzzle_brake
Muzzle brake can effectively reduce recoil.

**Comment by wwkk222208** [comment]
The performance of cbm weapons in the original version is already terrible, and I don’t think they will get worse in this PR.
This PR will only affect players and NPCs.

**Comment by Shodan14** [comment]
No effect based on weapon weight, just size?

Any changes to the other various mods that affect recoil like stocks, suppressors etc?

**Comment by wwkk222208** [comment]
> No effect based on weapon weight, just size?

Weight could reduce effective recoil and do not effect aiming speed in master. I did not change it. Maybe it is a good idea to take it into consideration.

> Any changes to the other various mods that affect recoil like stocks, suppressors etc?

No changes to the other mods. But as lower recoil becomes more critical, they also become more useful.

> Depending on the practical effects from the laser sight changes, might be good to introduce different grades (from a ducktaped laserpointer to an actual military one)?

It seems to be a good idea, I might do it in a seperate PR.

**Comment by wwkk222208** [comment]
>Manually switching sights is not ok, just select the most beneficial option and use it.

I just thought of a good idea. That is to set the best target range for each scope, so that the most suitable sight can be automatically selected through the code, so that there is no need to manually switch sights.

**Comment by ISuckM8** [comment]
Return of the king.

**Comment by Photoloss** [comment]
> I just thought of a good idea. That is to set the best target range for each scope, so that the most suitable sight can be automatically selected through the code, so that there is no need to manually switch sights.

Not sure to what extent the code currently reflects this but absolute distance is not the correct scale, angular size is closer. A 5m large car at 500m looks the same as a 1m large cart at 100m if you do not change sight configuration at all.

For slow projectiles or long-range precision shots a sight's ability to account for gravity and wind might become important but that is a secondary consideration (and scales with projectile velocity in addition to distance and target size).

Plus there might be a difference between the most precise aim and the fastest aim which is "good enough". For example if I'm targeting a manhack 15 tiles away I don't really want to use the scope to 100% snipe it directly in the left blade mount. Instead ideally I want to secure a 100% chance of landing any halfway decent body shot as quickly as possible so the little sucker doesn't dash up and cut me while I'm peeking through the scope.

**Comment by wwkk222208** [comment]
> > I just thought of a good idea. That is to set the best target range for each scope, so that the most suitable sight can be automatically selected through the code, so that there is no need to manually switch sights.
Very helpful suggestion, lad.
I will seriously consider it and redesign a better solution.

**Comment by wwkk222208** [comment]
Thank Photoloss. I just came up with a very interesting solution.
Use field of view (FOV) (angle of view in the code instead) instead of the existing ‘aiming speed’ to describe how fast it is to aim with a sight. If a target does not appear in the sight of the scope or looks too small, the aiming speed will be slow.
In this way, for a target that is too far or too small, whether it is equipped with a secondary sight has no effect on aiming.
For mid-range targets, rhe secondary sight will help aim faster.
For short-range targets, the role will directly use the secondary sight.
In addition, if the target moves during the aiming process, the aiming progress will be partially reset (especially when the target is too close), which will not cause much trouble to shooters using large FOV sights (because the target may still be In the field of view). But if the shooter only has a scope with a narrow field of view, he may not even be able to complete the aim.
How do you like it?

**Comment by Photoloss** [comment]
> Use field of view (FOV) (angle of view in the code instead) instead of the existing ‘aiming speed’ to describe how fast it is to aim with a sight.

There might still be properties inherent to the sight or gun which make aiming harder or easier so replacing the abstract "aiming speed" entirely might not be the best idea. Even simple iron sights can have varying spacing which affects parallax shift.

> In addition, if the target moves during the aiming process, the aiming progress will be partially reset

This sounds like a lot of work and should probably go into a separate PR. It's easy to shift your FoV if the target's movements are *predictable* such as a dog running right at you compared to just zooming around erratically like a bird or insect which hasn't spotted you or how leaping abilities currently work.

Additionally the effect should probably be proportional to current aim steadiness in addition to the angular shift. Just keeping your muzzle pointed towards the target is no big deal even if it jumps over you but good luck keeping a scope trained on its head specifically.

In general I also wonder how "sane" the size definitions of various monsters are. It might be necessary to compute a generic fallback e.g. the cubic root of their volume.

**Comment by wwkk222208** [comment]
>There might still be properties inherent to the sight or gun which make aiming harder or easier so replacing the abstract "aiming speed" entirely might not be the best idea. Even simple iron sights can have varying spacing which affects parallax shift.

You're right. But I think FOV is not the only factor that determines aiming speed, but it is at least an important factor (perhaps the most important factor). Other factors can be abstracted as "misc aiming speed modifier" or something else. The distance between iron sights and parallax should be classified as sight dispersion rather than speed. (This is obvious for pistols, but it is not reflected in the game. Of course, this is not in the scope of this PR discussion.)

>This sounds like a lot of work and should probably go into a separate PR. It's easy to shift your FoV if the target's movements are predictable such as a dog running right at you compared to just zooming around erratically like a bird or insect which hasn't spotted you or how leaping abilities currently work.

There is no real concept of speed in CDDA, and other creatures are stationary when the player moves. After the player finishes the action, there is some randomness in the behavior of other creatures. Of course, this feature is somewhat controversial and is not a major concern, and it is indeed more suitable to be placed in a separate PR. In fact, this is a not very complicated task, at least much simpler than manually switching sights.

>In general I also wonder how "sane" the size definitions of various monsters are. It might be necessary to compute a generic fallback e.g. the cubic root of their volume.

There are only several sizes of creatures in the game. For example, the size of humanoid creatures is 0.5, and the size of Hulks is 1.

Aiming speed of sights did not really take effect. The original intention of my PR was to solve this problem.
But if nothing else is changed, then every sniper rifle should be equipped with a secondary sight, which is not true. **I don't really want to replace ‘aiming speed’**, but I still hope that there is a mechanism to explain why not every sniper rifle needs a secondary sight.

**Comment by Photoloss** [comment]
> I think FOV is not the only factor that determines aiming speed, but it is at least an important factor

Yes. My point was only that the existing "game-y" aim speed calculation should still remain as a secondary addition while FoV takes over the bulk of the actual influence.

> There is no real concept of velocity in CDDA, and other creatures are stationary when the player moves.

There is the innate "speed" stat, the rest would depend on monster flags and the previous action taken (or inflicted upon) the target. This was intended as a caution to motivate a separate PR not as an exhaustive guide on implementation.

> I still hope that there is a mechanism to explain why not every sniper rifle needs a secondary sight.

Well they don't need one *for sniping* but players use weapons in unintended ways if the game allows it. Sitting on a rooftop overlooking a public street the scope is just fine, but the problematic scenario is a hulk busting through a wall 5m behind you. In that situation the scope is useless whereas in-game a decent rifleman can still do a 180° spin, line up and nail it right in the eye before getting punched. So if you want to use the same rifle for both sniping and corridor shootouts you absolutely should need to invest in a laser pointer, an offset sight rail or some kind of futuristic VR aiming assistant. Rivtech guns could just have an integrated laser pointer if that is desired for gameplay.

Part of it also depends on how we interpret the "built in sights" and the "obscures default sights" flag. Bows, crossbows and flamethrowers don't really have "sights" in the modern sense by default but they still need values in the code. Just looking along the barrel of a long rifle gives you a more accurate picture of where it's pointed at compared to hip-firing an SMG. Basically some guns might have an innate "integrated improvised aim assist" which is not obstructed by sight mods and better than hip firing but still worse than the iron sights obscured by your tacticool scope mod. I have no idea how to assign values for specific weapon types though because instinctively aiming a crossbow really does not compare very well to quick-drawing a revolver.

**Comment by wwkk222208** [comment]
>So if you want to use the same rifle for both sniping and corridor shootouts you absolutely should need to invest in a laser pointer, an offset sight rail or some kind of futuristic VR aiming assistant.

That makes sense. When snipers need to tackle close targets, they do need some other sights. But the current game mechanism is that no matter what target is aimed at, the secondary sight can effectively reduce the fixed time: (precise: 400moves to 350 moves, careful: 350moves to 300moves, normal: 300moves to 250 moves). And I think the correct result should be (precise: 400 moves to 390 moves, careful: 350moves to 320moves, normal: 300 moves to 250 moves)

**Comment by wwkk222208** [comment]
> I have no idea how to assign values for specific weapon types though because instinctively aiming a crossbow really does not compare very well to quick-drawing a revolver.

n the master version, all weapons have an iron sight by default (most sight dispersion is 30).
From the code, we can find out the residual settings of earlier versions. If the weapon does not have a sight, the sight dispersion is 90.
The current setting is not very reasonable, but it does not seem to cause much trouble to the game. I hope the first separate PR will focus on aiming speed rather than aiming accuracy

**Comment by kevingranade** [comment]
I really like your FOV proposal as the primary mechanism for differentiating between and selecting sights, each sight would have a preferred effective range for a given target size, and that answers the question of "why have secondary sights on a rifle?", the answer being a restrictive FOV from a magnifying scope is going to make the thing useless at close range (IRL that's something like 100m, in-game due to gun range compression that means about 6 tiles).

You might even want to flip that around and set a min and max range for a sight instead of trying to specifically set FoV in MoA or whatever.

**Comment by wwkk222208** [comment]
>
I am glad you can approve my proposal. But I think it is most appropriate to use angle to reflect FOV in json, because it can be consistent with the expression method of sight dispersion.
Of course the distance is quite intuitive data. The best distance (aim at a medium-sized enemy) of sight can be displayed in the game

**Comment by wwkk222208** [comment]
>"bring on target" is more accurate but a bit unwieldy, we can come up with a better option.
We could call it 'point shooting'.

**Comment by wwkk222208** [comment]
The content of this PR has been implemented in a separate PR, so it will be closed. Thank you for your help and suggestions.

**Pull request closed without merging**
