### PR TITLE
Fix erroneous check in veh_type

### PR DESCRIPTION
**Pull request by Willenbrink**
#### Summary
Bugfixes "Fix erroneous check in veh_type"

#### Purpose of change

This check prevents compilation using GCC 12 (see #58123).

#### Describe the solution
The check was erroneous as it could dereference a null pointer. This was fixed.

#### Testing
None. This code wasn't called before (as it would segfault) so simply removing it does not alter behavior.

### CODE REVIEW

**Comment by dseguin** [comment]
It looks like this check was originally fixed in #19370, but was reverted in 749e97ddd608bc1a99c526faf038ce63fcd56266

The intended fix seems to be:
```diff
diff --git a/src/veh_type.cpp b/src/veh_type.cpp
index d3e5a07134..29aa64110a 100644
--- a/src/veh_type.cpp
+++ b/src/veh_type.cpp
@@ -1265,7 +1265,7 @@ void vehicle_prototype::finalize()
             } else {
                 for( const auto &e : pt.ammo_types ) {
                     const itype *ammo = item::find_type( e );
-                    if( !ammo->ammo && base->gun->ammo.count( ammo->ammo->type ) ) {
+                    if( !ammo->ammo || !base->gun->ammo.count( ammo->ammo->type ) ) {
                         debugmsg( "init_vehicles: turret %s has invalid ammo_type %s in %s",
                                   pt.part.c_str(), e.c_str(), id.c_str() );
                     }
```

**Comment by Willenbrink** [comment]
So why was this reverted in the first place? I did some quick digging in the Discord and apparently there was some drama with mugling resulting in all his commits being removed. So this is not related to the commit itself?

**Comment by kevingranade** [comment]
This was part of a revert of a massive overhaul of the vehicle code.
The overhaul introduced a huge number of issues and needed to be rolled back to a working state.

https://github.com/CleverRaven/Cataclysm-DDA/commits/master?after=4d34ea090f39a9cf4912b4f3f7eb2eff23254e15+50314&branch=master&qualified_name=refs%2Fheads%2Fmaster

**Comment by Willenbrink** [comment]
Okay, thanks for the clarification. I've now basically restored that commit.

**Comment by dseguin** [comment]
Cheers, looks like you've uncovered a bug in the vehicle part finalization. When the `generic_guns` mod is loaded, guns and ammo types should be migrated before validating this check, something like this:

```diff
diff --git a/src/veh_type.cpp b/src/veh_type.cpp
index 135d7ea58c..5b99287959 100644
--- a/src/veh_type.cpp
+++ b/src/veh_type.cpp
@@ -1248,6 +1248,20 @@ void vehicle_prototype::finalize()
                           blueprint.part_count(), pt.pos.x, pt.pos.y );
             }
 
+            std::vector<itype_id> migrated;
+            for( auto it = pt.ammo_types.begin(); it != pt.ammo_types.end(); ) {
+                if( item_controller->migrate_id( *it ) != *it ) {
+                    migrated.push_back( item_controller->migrate_id( *it ) );
+                    it = pt.ammo_types.erase( it );
+                } else {
+                    ++it;
+                }
+            }
+
+            for( const itype_id &migrant : migrated ) {
+                pt.ammo_types.insert( migrant );
+            }
+
             if( !base->gun ) {
                 if( pt.with_ammo ) {
                     debugmsg( "init_vehicles: non-turret %s with ammo in %s", pt.part.c_str(),
@@ -1275,20 +1289,6 @@ void vehicle_prototype::finalize()
                 }
             }
 
-            std::vector<itype_id> migrated;
-            for( auto it = pt.ammo_types.begin(); it != pt.ammo_types.end(); ) {
-                if( item_controller->migrate_id( *it ) != *it ) {
-                    migrated.push_back( item_controller->migrate_id( *it ) );
-                    it = pt.ammo_types.erase( it );
-                } else {
-                    ++it;
-                }
-            }
-
-            for( const itype_id &migrant : migrated ) {
-                pt.ammo_types.insert( migrant );
-            }
-
             if( type_can_contain( *base, pt.fuel ) || base->magazine ) {
                 if( !item::type_is_defined( pt.fuel ) ) {
                     debugmsg( "init_vehicles: tank %s specified invalid fuel in %s",
```

That will allow this check to work for generic guns and pass the CI tests.

**Comment by Willenbrink** [comment]
Thanks, I couldn't figure out what exactly the problem was.

Unfortunately that doesn't seem to be enough as some tests in `tests/ammo_set_test.cpp` and `tests/ammo_test.cpp` still fail. Although I'm not sure if those are caused by errors in the migration or simply aren't supposed to be run with `generic_guns` enabled.

One failure, for example, is:
```
REQUIRE( cz75.magazine_default()->magazine->default_ammo.str() == ammo9mm_id.str() )
with expansion:
"pistol_ball" == "9mm"
```

**Comment by dseguin** [comment]
The tests don't run while mods are loaded, it only checks that the loading/verifying/finalizing checks are working. Basically, it runs with these args:

```
./build-scripts/get_all_mods.py | xargs -I{} ./tests/cata_test --min-duration 0.2 --use-colour yes --rng-seed time --error-format=github-action '~*' --user-dir=all_modded --mods={}
```

So no worries, should be good to go once the tests are done.

**Pull request merged**
