### PR TITLE
Nested Recipes - All Batteries

### PR DESCRIPTION
**Pull request by ANickelN**
#### Summary
Interface "Nested Recipes - All Batteries"

#### Purpose of change

Nest batteries, you get the drill by now.

#### Describe the solution

Add necessary json.

Division is:

_Batteries_ -> Categories -> Item

#### Describe alternatives you've considered

AHHHHHHH

#### Testing

cataclysm-tiles_TswyhbXrPg

### CODE REVIEW

**Comment by RelMayers** [comment]
I see no reason to nest batteries so much. Single category would work.

**Comment by esotericist** [comment]
i too feel this is going a bit too excessive. the nesting feature has merit for de-cluttering the base list, but multiple layers deep is unnecessary and just adds more navigation overhead.

i would probably have a small number of base entries in the main list with a number of entries in them that don't nest further

**Comment by descan** [comment]
I wouldn't nest the categories any deeper than "Rechargeable" and "Disposable," myself. Even that might be more needless clicking than just "Batteries" as the base and only category. There aren't *that* many batteries, after all.

**Comment by ANickelN** [comment]
Thank you for the feedback!  I've adjusted the nesting accordingly and hope this makes it feel less clunky!

**Pull request merged**
