### PR TITLE
Ma style and mana

### PR DESCRIPTION
**Pull request by dikiy4eburator**
#### Summary

Interface "added mana indicators and Kickboxing to ma_style_legend"

#### Purpose of change

add missing indicators

#### Testing

tested on a local build

#### Additional context

- added mana bar and mana nubers indicator to spacebar, that fits in the visual style.
- added Kickboxing to ma_style_legend widged

### CODE REVIEW

**Comment by NetSysFire** [comment]
Could you please update your PR summary? If merged it will appear in the changelog and there is no additional context section, so it is essentially of no use to the reader.

**Comment by dikiy4eburator** [comment]
> Could you please update your PR summary? If merged it will appear in the changelog and there is no additional context section, so it is essentially of no use to the reader.

done, but i think it is to long now :)

**Comment by NetSysFire** [comment]
No, in my opinion it is completely fine and looks way better now. Thanks for updating!

**Comment by GuardianDll** [comment]
Sorry, but what was the reason to separate `spacebar_mana_bar_block` and `spacebar_mana_numbers_block` into vanilla? doing some stuff with it right now, and kinda surprised with such decision

**Comment by dikiy4eburator** [comment]
> Sorry, but what was the reason to separate `spacebar_mana_bar_block` and `spacebar_mana_numbers_block` into vanilla? doing some stuff with it right now, and kinda surprised with such decision

Sorry for late answer, i just saw your questtion.
i have not separaten anything :), the spacebar uses its own versions of the mana indicators, so they fit visualy to the spacebar style.

**Pull request merged**
