### PR TITLE
Fixed "Zone construction build wooden wall builds window instead. #32965"

### LINKED ISSUE #32965: Zone construction build wooden wall builds window instead.
# Describe the bug

When a player or NPC does a Zone Activity - Construction - Build wooden wall, the result of construction is a Window instead.  (The wrong thing is built.)

# Steps To Reproduce

1. Make a player with the ability to construct wooden wall (fabrication 2)
2. Spawn in the necessary supplies (ie 100 planks, 20 wooden panels, 10000 nails)
3. Spawn in apt tool (ie toolbox)
4. Setup a construction zone for Wooden Wall near the supplies.
5. Attempt to execute the construction job.

# Expected behavior

Instead of a phase1 window I expect a phase 1 wooden wall since wooden wall is what I picked.

# Screenshots

cdda-WallBuildsWindow

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6227-gd8a9aea [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test01-WallBuildsWindow.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3472385/Test01-WallBuildsWindow.zip)

Included a handy save though reproduction steps are easy. (The WallBuildsWindow character.)

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
SUMMARY: Bugfixes "Zone construction build wooden wall builds window instead. #32965"

#### Purpose of change
Fixes #32965

#### Describe the solution
Added recursive functions to handle complex constructions:

`get_final_construction` detects what was really selected from the construction menu.
Not just <First construction that contains "Build Wood Wall">, 
but <The final construction is Wood Wall (t_wall, not t_wall_half)>.

`find_base_construction` looks up the construction "tree" for the first building that we can actually construct here, and which will lead to our goal (may be indirectly). 

Now it is possible to have a zone "Build Wood Wall" over some chipped/broken wooden walls or empty windows. The result will be "wooden wall where possible".

EDIT: 
Now blueprint construction is a continuous process. Once started it can be interrupted at any time (for ex., using `5`) and then continued. 
Partial (unfinished) construction in the blueprint zone will be continued. 
Note, that there is no extra check that this specific construction will lead to the goal in blueprint.  It is just assumed. I think it is safe enough, no? 

#### Describe alternatives you've considered
Need some dependency structure in constructions (like a tree). For now just use logic like <"*_half" is not the final construction>.

#### Additional context
None

### CODE REVIEW

**Comment by ipcyborg** [comment]
Jenkins Rebuild

**Comment by davidpwbrown** [comment]
Ill review this properly later, if its working better , then I will incorporate it into the new activity loop im working on.

**Comment by ZhilkinSerg** [comment]
Needs rebase.

**Comment by ipcyborg** [comment]
Rebased.

**Comment by anothersimulacrum** [comment]
Looks like something went wrong 
image

**Comment by ipcyborg** [comment]
Agreed. I followed the git hub rebase instruction here:
https://help.github.com/en/articles/using-git-rebase-on-the-command-line

Don't know how to fix this. 
Probably faster to just open new PR and move the changes there?

**Comment by ipcyborg** [comment]
Closed by #33673 (clean rebase)

**Pull request closed without merging**
