### PR TITLE
Convert item damage value to int

### PR DESCRIPTION
**Pull request by Qrox**
### What does it do
It fixes incorrect loading of item's damage values. As my previous PR #24901 was rejected, this is another approach to the issue. Damage values may still be incorrect after first loading an old save if the precision of `std::pow` is low enough, but it should not change again after saving with the new version.

A lot of files are changed in this PR, but most of them are just `item::damage()` calls changed to the new `item::damage_level()` call or the likes.

It should fix the last remaining issue in #19592.

### What is changed
Item damage values are changed from double to int, and related code are changed accordingly. I choose to change the range of damage from [-1.0, 4.0] to [-1000, 4000], because I see this as the only way to preserve item damage's granularity while avoiding incorrect input caused by the json library (apart from actually fixing the json library, that is). Damage values in data files are also converted so the new metrics will be compatible with existing files. I did not add support for specifying the precise value in data files since I don't see a great need for it, and it was not supported for the old double value anyway. A new method `damage_level` is implemented to perserve the old behavior of `damage` (mostly, the mapping is a bit different from before), and to provide a way to scale the damage value for various needs. I also fixed a call to `std::min` which I believe should be `std::max` in `player.cpp`, and a comment in `item::damage_color` regarding `getDurabilityColor` which I cannot find in the sources: I think it refers to `veh_interact::countDurability`.

### Compatibility with old saves and data files

The range of damage value is changed, which means that the old damage values need to be converted to the new metrics in save loading, and the new values need to be saved to a different variable. This breaks older version's ability to read damage values from newer saves, but I think most people won't do that anyway.

Old data files will be compatible since the values will be mapped to the new metrics automatically.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
A quick review of the code and this looks like a straightforward refactoring. damage_level is an annoying construct, but it's necessary for now. I think you should add warning comments, telling people not to use it in new code, so it can eventually be migrated out of the system.

**Comment by Qrox** [comment]
`damage_level` is not completely obsolete: it is specifically used in functions like `item::damage_symbol` and `item::damage_color` where scaling is needed. In other places where continuous value is needed they should be migrated out, so I'll add a warning comment as you suggested.

**Comment by narc0tiq** [comment]
Jenkins, rebuild.

**Comment by narc0tiq** [comment]
Once again, Jenkins, rebuild. (sorry for the notification spam)

**Pull request merged**
