### PR TITLE
remove wheat-free bread items and recipes

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
#74763 is online, which means allergens are delivered from vitamins, and correctly inherited from products, which means we do not need to make a duplicate copies of each bread food to be wheat free
#### Describe the solution
Obsolete and migrate wheat-free items and recipes, tweak the only itemgroup that spawned said food naturally to spawn bread made out of wheat-free
#### Testing
Power of autotests, but nothing should change technically
#### Additional context
Superior way to clean up bad density list is to delete the item itself

### CODE REVIEW

**Comment by Maleclypse** [comment]
Out of curiosity does this mean that Gluten free bread no longer exists at the start of the game or that all bread is gluten free at the start of the day?  Or is there some other way to make it so some bread is gluten free and some isn't when spawning mapgen?

**Comment by GuardianDll** [comment]
All bread has gluten by default, because it has a wheat vitamin in item definition. Player can cook it out of wheat-free flour, and this bread would carry vitamins from the ingredients, and wheat-free flour do not have a wheat vitamin, hence it would be safe to eat

**Comment by Maleclypse** [comment]
> All bread has gluten by default, because it has a wheat vitamin in item definition. Player can cook it out of wheat-free flour, and this bread would carry vitamins from the ingredients, and wheat-free flour do not have a wheat vitamin, hence it would be safe to eat
> 
> There is a way to spawn item, specifically made out of some ingredient, i used it in the only place where the game spawns gluten-free bread naturally

That’s friggin awesome.

**Comment by Consoleable** [comment]
cool intersection of vitamin and material system(or some parallel system)!

**Pull request merged**
