### PR TITLE
Treat 'road, manhole' tiles like bridge and road tiles for overmap pathing.

### LINKED ISSUE #32971: Autodrive doesn't path through manhole overmap tiles.
# Describe the bug

Basically it seems auto-drive doesn't consider "road, manhole" tiles to be valid.  When trying to set a route directly onto said tile or if the only road path is through such a tile, autodrive fails to set a route.

# Steps To Reproduce

1. Make a new player capable of driving.  May need to check/regen map to have an apt tile nearby.
2. Spawn a vehicle.
3. Take control of the vehicle.
4. Open the map.
5. Locate a "road, manhole" tile and try to set a path to it with shift-w.
6. Bonus, if your map has a section of road that is only reachable by going through the manhole tile, try setting a route to the other side of the manhole tile from where you are.

# Expected behavior

That auto-drive will set a route and (attempt to) drive the path as if the manhole tile were a road (or bridge) for that matter.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6227-gd8a9aea [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test01-AutodriveAvoidsManholes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3473305/Test01-AutodriveAvoidsManholes.zip)

Included a save (character AutodriveAvoidsManholes) since the setup can be finicky (I kinda goofed around more than needed to set it up).  There should be several manholes spread around the nearby towns, to the south-east (directly) there is a road stretch that requires going through a manhole tile to reach.

### PR DESCRIPTION
**Pull request by ProfoundDarkness**
#### Summary

SUMMARY: Bugfixes "Treat 'road, manhole' tiles as road tiles in overmap pathing."
#### Purpose of change

Fixes #32971 

#### Describe the solution

Added "road, manhole" to the tiles allowed when only road tiles are allowed.
Also added "road, manhole" tile pathcost 1 (like road and bridge), which if I follow the code properly also affects non-road only pathing.

#### Describe alternatives you've considered

- jsonize the pathing allowance and costs.  Probably not me, at least not anytime soon.
- Do a string check for if the name includes "road" so that it catches "road, manhole".  Didn't do this one as it may have unintended side effects and is probably slightly more expensive relative to 'just one more tile' check.

### CODE REVIEW

**Comment by ProfoundDarkness** [comment]
Jenkins Rebuild

**Comment by ProfoundDarkness** [comment]
\<sigh\> I've done the astyling, maybe something screwed up in my configuration but it was working fine (or I got lucky).  I'm not feeling well enough to fix whatever is wrong with my config and thus whatever isn't being astyled properly.

I'm gonna close this but if someone else wants to reopen and fix the astyling or grab the changes in their own PR, they can.  I won't be looking back here until I've got some good days to figure out what's wrong (probably not for a while).

**Comment by anothersimulacrum** [comment]
What version is your astyle? We support 3.0.1 or 3.1

**Comment by ProfoundDarkness** [comment]
Feeling kinda OK much sooner than expected and checked, there were two problems with my astyle setup (so luck that it worked before).

1. I did have the wrong version of astyle (2.05.1).  Since I don't want to mangle my distro state (again) with something dumb like sudo make install I did the same thing I did with git and compiled/installed the newest version to my user account rather than system wide. -- Thanks @anothersimulacrum for that tidbit.
2. Somehow my editor (which is supposed to come pre-configured to find/use .astylerc) was failing to find it.  A settings tweak and things are looking OK on my end now (make astyle with right version isn't complaining).

I like to have astyle in the editor so I don't astyle stuff I didn't change.  I find it *MUCH* harder to externally astyle (make astyle) and then find what I changed/revert what I didn't.

Looks like I'll have to create a new PR as I wiped the commits that astyled stuff I shouldn't have.  I'll try to look at that once the master branch compiles for me again.  Good luck dealing with those wonderful inconsistencies.

**Pull request closed without merging**
