### PR TITLE
Skeletal creatures revised

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Features "Skeletal creatures drop bones around on death. Juggernauts can't smell no more, but are hard to shoot."```

#### Purpose of change
Inspired by this conversation on Reddit:
image

#### Describe the solution
1. Revisited butchery yields and noticed that it's old logic does not fit the new skeletal creatures lore. They are not skeletons extracted from bodies, they are skeletal monsters with overgrown bone carapace. Previous logic just made sure that skeletons did not drop meat, now if creature is made of bone it converts some of  its mass to extra bones. Expect boosted bone yields.
2. I've decoupled overkill splattered effect from the `mdeath::normal`, so it can be independent `death_function` while it is still called from `normal`. `splatter` can also be combined with `normal`, to achieve splatter and a corpse where needed. In other words you can make your monster rain gibs, meat and blood at your whim, no need for overkill damage, if you wish so.
3. Revisited skeletal creatures and:
- they got both `normal` and `splatter` `death_function`s; effect: they rain bones on death, and it simulates disconnected bones flying around, when this monster can't hold'em together after it dies.
- juggernaut got `SMELL` flag removed to put it in line with other skeletal creatures, but is now `HARDTOHIT` (it should be from the beginning), that might require slight tactics change (break line of sight, approach at night, it won't smell you).
- also removed `NOGIB` from juggernaut to allow bone rain

#### Describe alternatives you've considered
N/A

#### Additional context
This: #25714 will be resolved elsewhere.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Doot doot!

**Comment by Tygrende** [comment]
Why would the skeletal juggernaut be hard to hit? The description clearly states that he's huge, slow and covered in plates all over his body. He's nothing like a regular skeleton.

**Comment by Xhuis** [comment]
The bony plates are very resistant to bullet damage. It's hard to *shoot*, not to hit. Small-arms fire would probably just deflect off of it.

**Comment by kevingranade** [comment]
Hardtohit means you count as one size class smaller for the purposes of
getting shot.  The juggernaut qualifies for the same reason skeletons do,
it has long spindly limbs and a small torso, it's just jaeger in absolute
terms.

**Pull request merged**
