### PR TITLE
Remove irremovable mods after the gun is destroyed by fire

### LINKED ISSUE #24242: Integral gunmods can be detached by burning the parent gun
Game version: build 7459

Operating system: Windows 10

Tiles or curses: curses

Mods active: none

### Expected behavior
Integral gunmods cannot be detached under any circumstances and should suffer the fate of the parent weapon.

### Actual behavior
Integral gunmods can be detached by destroying the parent gun by burning, then attached to other weapons.

### Steps to reproduce the behavior
Spawn a Kel-Tec KSG and/or Lemat Revolver, drop it along with fuel (e.g. log), set it on fire. The KSG will burn almost instantly because it is made of plastic, but the KSG second magazine will not because it is made only of steel.

image

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #24242.

### CODE REVIEW

**Comment by Amariithynar** [comment]
I don't necessarily agree with this, unless you're making the base gun also give the decomposition components of the mod. The mod should remain and degrade in the fire on its own if the material is sturdier than the base weapon is (as in the case here). Furthermore, with a high firearms skill (pistol/shotgun/rifle) and fabrication, why not allow the player to be able to modify other guns to accept it?

**Comment by Night-Pryanik** [comment]
Plastic case and intensives of the KSG doesn't disintegrate into complete nothing. I think that after melting they are fused with the magazine, rendering it unusable. We don't have that level of details for our items, so items degraded like that are effectively destroyed.
Removing irremovable mods is topic for discussion out of scope of this PR.

**Comment by Amariithynar** [comment]
The second magazine is a basically just a steel tube with a physical selector mechanism for which tube it's loaded from, is the problem. That wouldn't melt at all in all but the most intense fires; iron is one of few substances we commonly use that you can pick a pailful of lava up with or even immerse it in, and it won't melt.

**Comment by Rivet-the-Zombie** [comment]
Whether a particular component would melt in a fire isn't the point of this PR; this is entirely about making sure that item-specific irremovable gunmods can't be glitched off of their base items and used on other weapons.

**Comment by Amariithynar** [comment]
Which is exactly what I'm arguing AGAINST, using basic logic. Good grief.

**Comment by Rivet-the-Zombie** [comment]
We don't want irremovable mods to be removed in the first place. It's not a matter of logic, but rather one of game design. Those mods are tailored specifically for the guns they come on to make them special, and are not intended to go on anything else.

**Pull request merged**
