### PR TITLE
Cut the vending machine's power to reflect the main power grid wrecked by the Cataclysm

### PR DESCRIPTION
**Pull request by gettingusedto**
#### Summary
None

#### Purpose of change

Since the end the world happened and the main grid got rendered non-functioning, it's safe to say that vending machines in places shouldnt be powered at all.

#### Describe the solution

Delete the vending machine's vending examine action and change the descriptions to reflect the fact.

#### Describe alternatives you've considered

Not doing so and pretend that it has it's own power gen thing inside.
#### Testing

yeeted the examine action for both vending machine and reinforced vending machine in my own build, go into my debug world and spawn in said vending machines.

interacting it yields nothing.

#### Additional context

:trollface:

### CODE REVIEW

**Comment by kevingranade** [comment]
Hoisting this from the discord conversation for visibility.
The only holdup here is mod authors might want to override this to re-enable vending machines in their settings.
Looks like that's MoM, Backrooms, and Aftershock at a glance, but there might be more.
Maybe pull the ALARMED flag as well? Or maybe that does deserve a (much smaller) battery backup.

**Comment by TheShadowFerret** [comment]
So they exist as lootboxes to be smashed open with great pipe maces?

**Comment by oosyrag** [comment]
I nuked all the cash cards out of my game when they were causing issues during charge migration, haven't missed them.

They're everywhere in game but are they actually a thing in NE? I'm more familiar with octopus, suica, and ez card in HK,jp,and tw but I don't know of any here. Assuming the cash cards in game are like those instead of the common credit, debit, and gift cards that need a financial institution to verify or only work in one place.

**Comment by Qrox** [comment]
Don't forget the ATM and gas pumps. Death mobile drivers would be mad though.

**Comment by Maleclypse** [comment]
> Hoisting this from the discord conversation for visibility. The only holdup here is mod authors might want to override this to re-enable vending machines in their settings. Looks like that's MoM, Backrooms, and Aftershock at a glance, but there might be more. Maybe pull the ALARMED flag as well? Or maybe that does deserve a (much smaller) battery backup.

Backrooms definitely, I think AFS but I'll let @John-Candlebury make that call, and @Standing-Storm for MoM

**Comment by John-Candlebury** [comment]
Yes aftershock wants working vending machines, same goes for the ATM although thats not the topic here.

**Comment by Standing-Storm** [comment]
I don't use vending machines anywhere except in places where they'd have the same problem of no power (Project PHAVIAN lab sites), so MoM shouldn't need any overrides.

**Comment by PatrikLundell** [comment]
As noted above, cash card usage is basically vending machines and gas pumps, with ATMs essentially used as facilitators (they're also rather dubious deposit machines for cash, but that shouldn't work either).

Logically none of this should be working when the grid is gone. However, removal should include alternatives:
- Vending machines should replace the purchase action with a breaking open action (with smashing as a separate thing), although reinforced vending machines might only be dealt with through smashing.
- Vending machines should not have any (working) alarms, although I would not complained too loudly if reinforced ones still do.
- Gas stations should have means to get at the fuel, probably either by somehow disconnecting them from the grid and power them locally, or by digging down to the tanks and pump from those manually.
- ATMs would just be useless decoration.
- Cash cards should probably be removed completely as they don't seem to correspond to anything that's actually in use, although I guess they could be converted into (almost completely) useless credit card items.

This PR should probably not be expanded to cover more than the vending machines, though, but the PR that removes the last use of cash cards should clean up the ATMs and the cards as well.

**Comment by Hyperseeker** [comment]
Cash cards could be turned into a variant of a generic card (debit, credit, gift etc.), to have them remain in the world but strip them of functionality. They're everywhere IRL, and the game is still modelling cash coins and bills. Pulling cards when the equally-useless bills still spawn would make no sense.

**Comment by gettingusedto** [comment]
As suggested by @Fris0uman, i made the regular vending machine pryable with the crowbar. If ya have something to say about the values (since i kinda just copied this from crate's json) and/or have an idea of how reinforced vending machine should be opened, feel free to tell me bout it.

**Comment by gettingusedto** [comment]
i just realized that `"vendingmachine"` in the mapgen json is a thing, and i presume it uses `f_vending_c` and `f_vending_reinforced` id. The issue is that i cant change it due to the fact that im doing all of this on mobile and i doubt i can change it here. I'm quite stumped bout this predicament.

**Comment by carlarctg** [comment]
There's many vending machines in labs, old and new, and those still have functioning lights and computers. Makes no sense if those don't work when the power there clearly is.

**Comment by Qrox** [comment]
> There's many vending machines in labs, old and new, and those still have functioning lights and computers. Makes no sense if those don't work when the power there clearly is.

I think the problem is that when the grid is down so is the internet, and the vending machines probably need to connect to some central database via the internet to use the cash card. It might work if the cash card supports offline payment, but that would probably make the cash card pretty easy to hack.

**Comment by Zireael07** [comment]
@Qrox: The first vending machines operated in 1880s, so way before the internet... it's not a requirement

**Comment by yuganxia** [comment]
Why is it that there are no coins in the world of CDDA, I can only find paper money.
Coins can be used in vending machines that do not require electricity.

**Comment by yuganxia** [comment]
> Why is it that there are no coins in the world of CDDA, I can only find paper money. Coins can be used in vending machines that do not require electricity.

Vending machines that don't require electricity shouldn't be used anymore.

U.S. coins are made of brass or cupro-nickel alloys, which should serve as a source of copper and could even be used to make bullets (not sure)

**Comment by oosyrag** [comment]
There actually are coins in CDDA. They're just rare. As for why they are rare, it's probably because it is very uncommon for people to carry or use them anymore.

**Comment by AnotherSeawhite** [comment]
I was wondering if lockpickable vending machines can be added in this PR.

**Comment by PGR-14** [comment]
What about that dude in the abandoned house bunker that uses atms & USD for trading?

**Comment by kevingranade** [comment]
* Lab vending machines: labs are supposed to be on emergency power, vending machines shouldn't be on emergency circuits.  Also as long as they're card based they aren't working since the bank is down.
* Coins aren't more common because no one has added them.  They're neither super common nor super rare nowadays.
* Coin- operated machines are possible,  gumball, toy,  and pharmacy* machines still exist so those are possibilities.
\* If you're not familiar with pharmacy machines, you see them mostly in bars from what I've seen.They vend things like cold medicine and aspirin and also sometimes condoms.
* melting down coins for bullets or most* anything else is a bit of a stretch, un-alloying them might be complicated.
\* other than sling bullets maybe?

**Comment by gettingusedto** [comment]
So, i'm closing this pr due to the fact that it require me to do c++, which i dont have the know-how nor a computer (since i only have a mobile phone) to do it.

If someone else can take over what i was doing, by all means.

**Pull request closed without merging**
