### PR TITLE
More crops!

### PR DESCRIPTION
**Pull request by AllisonBW**
Adds broccoli, celery, cucumber, oat, and zucchini seeds, as well as seed potatoes (these being bigger/heavier than other seed items is intentional); adds raw oats; adds recipe to process raw oats into oatmeal; adds all six new seed items to farming_seeds item group.

### CODE REVIEW

**Comment by Darkyhard** [comment]
What about growing wild plants like buckwheat and dandelions too?

**Comment by Barhandar** [comment]
>What about growing wild plants like buckwheat and dandelions, so that you could grow someting without having to search for seeds?

That is being covered by MormonPartyboat over on forums, oh, and buckwheat won't grow on same fertilizer in same place as nearly any other crop, that's why it's "wild" in the first place and not grown commercially.

**Comment by Darkyhard** [comment]
No, I meant that you could be able to find some buckwheat seeds in the forest to plant them.

**Comment by AllisonBW** [comment]
I'm leaving wild stuff, herbalism, and beans to MormonPartyboat, like Barhandar said.

**Comment by KA101** [comment]
Might want a bit of water (Wiki says oat-rolling involves steam as well as light toasting) but I'm willing to forgo that based on the quantities involved.

**Pull request merged**
