### PR TITLE
[MoM] Even more powers

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Even more powers"

#### Purpose of change

Adds four more powers I thought of.

#### Describe the solution

Biokinesis:

- Oxygen Absorption (C) (Diff 2): Breathe through your skin, allowing you to breathe underwater!
- Metabolic Hyperefficiency (C) (Diff 7): Greatly reduce your need for food, water, and sleep.

Electrokinesis:

- Pain Suppression (C) (Diff 4): Reduce the amount of pain you suffer and recover from it faster
- Analgesic Block (Diff 6): Completely stop the pain signals from reaching your brain, removing all pain and making you immune to further pain.  Your nerves are still sending the signals, however, and when the power ends all that pain and more comes back.

#### Testing

Oxygen Absorption allows you to breathe underwater (I don't think there's currently any low-oxygen environments. If they're added, I'll get it to work with them too.
Metabolic Hyperefficiency allows you to stay up days on end and eat and drink once a day or less.
Pain Suppression decreases taken pain and reduces the time taken for pain to fade.
Analgesic Block works. 

#### Additional context

I had an idea for one more power (biokinetics changing their physical appearance) but it seems impossible at the moment.

Yes, it's intended that people extrapolate that a powerful biokinetic/vitakinetic would be an immortal, nigh-unkillable breatharian, the last surviving human on a Cataclysm-ravaged world.

### CODE REVIEW

**Comment by Standing-Storm** [comment]
> Why is that? You can grant traits via spells, which I think would cover most of the potential effects of changing your appearance.

Some of the appearance traits are coded as cosmetic mutation variants and the in-game EoC commands to bring up the menus that allow changing them through already-existing methods only function in either NPC dialogue or evoked from an item (and one of those item function is bugged). Because of that, to allow appearance switching I'd have to write hundreds of lines of EoC statements covering every possible hair, eye, skin, and beard choice.

So it's not necessarily that it's impossible (except maybe for eye color) as it would take an inordinate amount of work to replicate something there are already methods of accomplishing, just that they're currently inaccessible.

**Comment by Shibimon** [comment]
Im not even sure how you gain more powers (though use?) if i keep using my already biokinetic advanced character powers will eventually gain these new powers?

**Comment by Standing-Storm** [comment]
> Im not even sure how you gain more powers (though use?) if i keep using my already biokinetic advanced character powers will eventually gain these new powers?

Correct--leveling your starting powers will get you new powers, and leveling those powers will get you more powers, and so on.

**Comment by Shibimon** [comment]
> > Im not even sure how you gain more powers (though use?) if i keep using my already biokinetic advanced character powers will eventually gain these new powers?
> 
> Correct--leveling your starting powers will get you new powers, and leveling those powers will get you more powers, and so on.
> 
> When new powers are added, on load the game checks your existing power levels and should grant you anything you qualify for.

What i meant is if i already leveled those powers before this update im locked out of getting the new ones?

**Pull request merged**
