### PR TITLE
Allow mods to modify professions

### PR DESCRIPTION
**Pull request by BevapDin**
Allows to modify the list of items, CBMs, addictions, skills and flags of professions.

Modify the list of CBMs:

``` JSON
{
    "type": "profession",
    "ident": "bionic_prepper",
    "name": "Bionic Something",
    "edit-mode": "modify",
    "remove:CBMs": [ "bio_tools", "bio_sunglasses", "bio_blindfold" ],
    "add:CBMs": [ "bio_plut_filter" ]
}
```

Modify skills, addictions and items (removing is done with the skill/addiction/item id only):

``` JSON
{
    "type": "profession",
    "ident": "cop",
    "edit-mode": "modify",
    "remove:skills": [ "gun" ],
    "add:skills": [ { "level": 3, "name": "barter" } ]
},
{
    "type": "profession",
    "ident": "smoker",
    "edit-mode": "modify",
    "remove:addictions": [ "nicotine" ]
},
{
    "type": "profession",
    "ident": "bionic_prepper",
    "edit-mode": "modify",
    "items": {
        "remove:both": [
            "flashlight",
            "knife_swissarmy",
            "rope_30",
            "canteen"
        ],
        "add:both": [
            "water_clean",
            [ "tshirt_text", "allyourbase" ]
        ],
        "add:male": [
            "rope_30"
        ],
        "add:female": [
            "knife_swissarmy"
        ]
    }
}
```

### CODE REVIEW

**Comment by MisterFelixFox** [comment]
I like this a lot. Every now and then I'd modify a profession with a mod but it was a bit of a hassle to make sure most things stayed the same. Thanks for this.

**Comment by Zireael07** [comment]
Great!

**Comment by macrosblackd** [comment]
Will players be able to modify the point costs of professions?

**Comment by BevapDin** [comment]
> Will players be able to modify the point costs of professions?

Yes, and name and description.

**Pull request merged**
