### PR TITLE
Change strawberry & blueberry bush colors

### PR DESCRIPTION
**Pull request by Voker57**
Currently bushes are green, same as underbrush. That makes them very difficult
to locate in forests. This commit changes their colors to red and blue.

### CODE REVIEW

**Comment by Frost-wood** [comment]
Sounds good- I hate forging and then finding that its a strawberry bush that isn't ready until summer.

**Comment by Rivet-the-Zombie** [comment]
More visible information per glyph is always good!

**Comment by Tomcost** [comment]
Oh, we foragers need this so much!

**Comment by Coolthulhu** [comment]
Those colors make them look really... metallic.
How about colors with green backgrounds? For example, `ltred_green`. We could later also change regular shrubs to be brown on green background.

**Comment by i2amroy** [comment]
>Those colors make them look really... metallic. Blueberry shrubs look like metal wreckage tiles, strawberries like bloodied dirt heaps.

Agreed. We definitely need some sort of change, but as is it's only confusing other things.

**Comment by Lain-** [comment]
+1. IMO the colors of real life are mostly uninteresting. Blueberrie and strawberrie bushes should be of normal color most of the time even when they bear fruit.

**Comment by Zireael07** [comment]
I like the idea, let's make the blueberries blue on green bg and strawberries red on green bg.

**Comment by Voker57** [comment]
> let's make the blueberries blue on green bg and strawberries red on green bg.

Done that.

**Comment by Snaaty** [comment]
Why not the other way round? I imagine the '#'-sign always kinda looked like a bush, so changing the color of it seems odd to me, whereas using the background color for providing additional information is "harmless", as the background color is only seen by the player and not by the character, similar to the changed background color when there are items underneath each other.

**Comment by kevingranade** [comment]
Also background color is already used to signal 'items here'

**Comment by Zireael07** [comment]
Items here background color is blue IIRC.

**Comment by narc0tiq** [comment]
I think the "items here" display is just inverting the foreground and
background colours. In this case, I think just changing the foreground
colour would be all right, given we already do something like that for
fruit trees (if memory serves).

**Comment by Coolthulhu** [comment]
I'd say that having a different colored "items here" is precisely what we want for bushes full of fruit.
Not sure about the empty ones.

**Comment by Coolthulhu** [comment]
> I think the "items here" display is just inverting the foreground and
background colours.

It changes the background color to blue or light blue.
If we had bushes with green background, it would look similar to them having items under them. To me this sounds like what we want, because they essentially do contain items, just on them rather than underneath them.

**Comment by Zireael07** [comment]
@Coolthulhu : Agreed.

**Comment by narc0tiq** [comment]
SGTM!

**Comment by Coolthulhu** [comment]
One final nitpick: bright colors kinda blend in with the green background. This makes harvested bushes stand out more than the un-harvested one.

Either background needs to be made brighter (and then foreground would have to retain its colors) or colors of harvested/unharvested variants should be swapped.

It still looks good, just could look a small bit better.

**Pull request merged**
