### PR TITLE
Rename all occurrences of 'microwave generator' to magnetron

### LINKED ISSUE #50045: "Microwave generators" should be called magnetrons
# Is your feature request related to a problem? Please describe.
Disassembling a microwave oven results in an item called a "microwave generator". This describes what it does in this instance, but it's actually called a magnetron.

# Describe the solution you'd like
This could easily be a rename, I just don't have the time to implement it myself during the day.  (It's amazing I'm finding time to play. )

# Additional context
One would not recognize the use of a magnetron with simple garage electronics skills. A magnetron is a lot like a vacuum tube, but contains a perforated metal block which emits microwaves as electrons stream past it. There's usually a few of them, as I recall. It wouldn't be labeled. 

Not urgent, just something that needs to be fixed sometime. I may get around to it myself in a few weeks.

### PR DESCRIPTION
**Pull request by dgobi**
#### Summary
Category "Bugfixes"

#### Purpose of change
Fixes #50045 by renaming all occurrences of 'microwave generator' in the game to the more correct 'magnetron'.

#### Describe the solution
As above, simple renaming.

#### Describe alternatives you've considered
None seemed to make sense here.

#### Testing
Spawned in magnetrons and disassembled microwaves to verify changes in debug.

#### Additional context
I am new to contributing - please don't hesitate to give any advice/suggestions/feedback!

### CODE REVIEW

**Comment by actual-nh** [comment]
I doubt any files in lang should be changed - they'll get updated automatically.

**Comment by dgobi** [comment]
> 
> 
> I doubt any files in lang should be changed - they'll get updated automatically.

Sorry about that, is there a way to remove those commits? I wasn't sure how they get updated.

**Comment by actual-nh** [comment]
You only have one commit, so that won't do it. The only file you actually need to change is `data/json/items/electronics.json `, as far as I can tell, so if you revert the commit and change that one file and do a commit, it should do the job.

**Comment by ToxiClay** [comment]
> > I doubt any files in lang should be changed - they'll get updated automatically.
> 
> Sorry about that, is there a way to remove those commits? I wasn't sure how they get updated.

I bet you did a global search-and-replace in the Cataclysm-DDA directory for "microwave generator" to "magnetron."

**Comment by dgobi** [comment]
I'll try again when I'm more competent. :)

**Pull request closed without merging**
