### PR TITLE
Nerf the warmth values of some undergarments and thin clothes.

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
Balance "Lower the warmth values of some undergarments and thin clothes."

#### Purpose of change

Staying warm even in the dead of winter without any cold-weather clothing is really easy right now, largely due to a few outlier clothing, usually undergarments that are extremely thin, very low-encumbrance, high warmth, and in the least-competitive "close-to-skin" category. This makes actual proper cold weather gear undesirable if you can replace a thick jacket with some long johns that don't interfere with your armor, are less encumbering, and somehow are warmer despite being thin cotton.

#### Describe the solution

Nerf the warmth values of the long underwear bottoms, long underwear tops, and union suits to 10 down from 30 (35 for the union suit). Nerf the light gloves to 10 warmth, down from 20. Nerf glove liners to 5 warmth down from 15. Nerf the undershirt to 5 from 10 warmth. For all this cotton clothing, I generally just made it so that 0.1mm of cotton was 5 warmth and 0.2mm of cotton was 10. This means they can help take the edge off if it's a little nippy but you can't replace your winter coat just by wearing two sets of long johns to survive in sub-zero temperatures mid-winter.

"Nerfed" the compression top/shorts to 4 warmth from 20. This actually gives them their proper niche as warm-weather undergarments to help keep you cool due to the moisture-wicking, which previously was pointless when they were warmer than jackets or thick pants and would make you overheat. Also, from experience, they really don't do much for cold at all.

#### Describe alternatives you've considered

There's almost certainly clothes I missed; debated touching on stuff like the arm or leg warmers or the thermal shirt but either wasn't sure if they're that warm or not, or just figured they weren't as egregious. I don't have experience with them.

Alternatively, make a massive overhaul that automatically fills in warmth based on material and thickness similar to armor (I'm not doing this).

#### Testing

Game works, fingies are properly chilly.

#### Additional context

weh

### CODE REVIEW

**Comment by XygenSS** [comment]
It could be argued that undergarments provide extra warmth than they appear to because of insulation benefits from layering your clothes.

But I guess a better approach would be to actually implement a layering warmth bonus.

**Comment by Maleclypse** [comment]
Leather gloves aren't very warm in the winter either.  Do they already have a low warmth value or should you audit them while here?

**Comment by Aerin-of-the-Toast** [comment]
> Leather gloves aren't very warm in the winter either. Do they already have a low warmth value or should you audit them while here?

25 for 0.5mm of leather. I mostly didn't touch them since I've never tried wearing leather gloves in winter, so I've no idea if that's accurate or not. They're also less egregious in terms of the warmth:encumbrance (25:5) compared to light gloves (20:1) so I wasn't really looking at them.

**Comment by Maleclypse** [comment]
> > Leather gloves aren't very warm in the winter either. Do they already have a low warmth value or should you audit them while here?
> 
> 25 for 0.5mm of leather. I mostly didn't touch them since I've never tried wearing leather gloves in winter, so I've no idea if that's accurate or not. They're also less egregious in terms of the warmth:encumbrance (25:5) compared to light gloves (20:1) so I wasn't really looking at them.

Fair, I just know when I lived in Mass my leather gloves were for fall and early winter, once the snows come you needed heavier stuff. :)

**Comment by Hyperseeker** [comment]
I feel like dress shirt with its warmth of 10 might be a good fit for this PR, as well.

**Comment by Aerin-of-the-Toast** [comment]
> I feel like dress shirt with its warmth of 10 might be a good fit for this PR, as well.

Not convinced it's inaccurate (I'm not trying to make 0.1mm cotton being 5 warmth a _law_ and dress shirts a bit stuffier than t-shirts) and even if it was it's hardly egregious IMO.

**Pull request merged**
