### PR TITLE
feat: label issue closing PRs as bugfixes

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
someone once said it would be a good idea to label prs that use
any closing keywords as bugfixes, I took a mental note of that and
immediately forgor about it, oops!

implement that idea; to be specific you gotta add any of these
keywords:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
close
closes
closed
fix
fixes
fixed
resolve
resolves
`#` and an issue number, the regex for this specific bit was borrowed
from one of the commands in the cdda discord server `#([1-9][0-9]{3,4})`
also increase the upper limit of an issue number up to 7

I had to repeat the bugfix labeler entry cuz YAML do be like that

~~big point this specific labeler workflow happen to be case sensitive, I
take this compromise, the "fix it" or looking for a different labeler
are ehh options honestly~~ scratch that, I remembered how regex works

website to see this regex in action, string to test included
https://regex101.com/r/pBIUNe/1

or just take a look at this
Screenshot from 2022-08-19 17-51-47

#### Testing
https://github.com/casswedson/issue-labeling/pull/23
https://github.com/casswedson/issue-labeling/pull/24

### CODE REVIEW

**Comment by Qrox** [comment]
Might want to actually use the feature/bug label of the issue to be closed, but I'm not sure how doable is that.

**Comment by casswedson** [comment]
I don't quite get what you mean by that

**Comment by Qrox** [comment]
I mean a PR that closes a issue is not necessarily a bugfix: it could close a feature request, add some requested documentation, etc, so it would be better to use the issue's label to determine that label to add to the PR.

**Comment by casswedson** [comment]
That's certainly possible, tho fairly complicated; _I think_ this (+some of the other autolabeling) covers most cases at a satisfying level, like if the pr adds documentation it gets the docs label, other things like features/enhancement need author input, not bad if you ask me

**Pull request merged**
