### PR TITLE
Self-Driving Garbage Truck [Reuploaded]

### PR DESCRIPTION
**Pull request by Wyrdean**
#### Summary
Content "Adds a self-driving garbage truck, an upgraded street sweeper."

#### Purpose of change
Cdda doesn't have garbage trucks, so I took it upon myself to fix that. As cdda has an automatic street sweeper, I felt it would be good to make a larger, more industrial version of that.

#### Describe the solution
Adds garbage trucks, which can be found in the city somewhat commonly, on the highway fairly rarely, and rather commonly at junkyards and dumps

#### Describe alternatives you've considered
Not adding them, making them basic boring person driven trucks, or having them spawn in other places; but I feel this is the best solution.

#### Testing
Garbage truck can spawn in, and is drivable

#### Additional context
This is a reupload as, due to my inexperience with github, I didn't realize making edits on the master branch would have such far-reaching (and extremely hard to fix, not to mention time-consuming, requiring several days) consequences. Many thanks to another simulacrum who helped me fix this pr.

### CODE REVIEW

**Comment by BrettDong** [comment]
It seems that you are still working on the master branch in this pull request.

**Comment by Wyrdean** [comment]
> It seems that you are still working on the master branch in this pull request.

I am still trying to figure out how to solve the issue, github doesn't seem to like the idea of making it easy to actually "undo" things; so in the meantime thanks to simulacrum I can reupload the pr. If it gets merged in the meantime while I'm figuring things out it'd save me a lot of time, so it's a win-win.

**Comment by Maddremor** [comment]
Conventional garbage trucks would be preferable unless automatic variants has become common in New England without me noticing.

**Comment by Wyrdean** [comment]
I can redesign the truck if that's preferable, but it was roughly based on this:
[here](https://www.waste360.com/trucks/volvo-testing-self-driving-garbage-truck)

**Comment by I-am-Erk** [comment]
Do you mind updating to master to see if that solves the tests?

**Pull request closed without merging**
