### PR TITLE
[Sky Island] Re-add zombie bio operators to Sky Island

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Sky Island] Re-add zombie bio operators to Sky Island"

#### Purpose of change

Sky Island has an item to allow you to bring an autodoc back up to your island, implying that finding CBMs is the intended way to gain them in Sky Island. That requires that there be CBMs in the world to find.

#### Describe the solution

Add the zombie bio operators, with the dissection CBM drop table of zomborgs. Put them in the places they are in No Hope (and used to be in vanilla). 

#### Testing
Bio operators exist in the world, and dissecting them gives you CBMs if you're good enough at it.

### CODE REVIEW

**Comment by Karol1223** [comment]
> That requires that there be CBMs in the world to find.

So why aren't zomborgs enough, exactly?

**Comment by Standing-Storm** [comment]
> So why aren't zomborgs enough, exactly?

Zomborgs are pretty rare, and CBMs are not designed to be that rare in vanilla (part of the point of moving them to the Exodii and allowing the player to access them relatively early). Furthermore, the constraints of Sky Island mean that it is impossible to aim for finding zomborgs--they exist as part of a map extra, so you can't do any scouting, you'd just have to aimlessly run through fields until you find a drop pod with them. The only current way to actually aim for CBMs, lab vaults, is also due to be removed from vanilla which will make CBMs almost totally inaccessible for Sky Island (especially since it will remove the main remaining source of findable autodocs to bring back to the island).

I'll address that when it happens (maybe readding the vault to Sky Island specifically), but that's not necessary yet. 
 
> Also... No, I do not see how this makes sense at all. Bio operators stopped providing CBMs in vanilla before Sky Island was even mainlined. What's the thought process here?

That bio-operators did used to drop CBMs and so are a reasonable candidate for adding an additional monster source (since those who played before will remember, they still drop CBMs in No Hope, and their name evokes the idea of bionics). They were found rarely in military locations and already existed in Sky Island as high-end enemies during elite Slaughter missions before they were all moved to No Hope, so the infrastructure for being able to find them already existed. That Sky Island should have more sources of CBMs that it's possible to seek out in a way that isn't just randomly wandering and hoping you get lucky.

**Comment by Karol1223** [comment]
> That bio-operators did used to drop CBMs

Correct, but that was removed before Sky Island was mainlined.

**Comment by John-Candlebury** [comment]
I dont think the dates in which vanilla implemented/unimplemented a feature is as relevant vs the question of wheter this achieves a game balance goal within the mod.

I think this doeas achieve the goal. With the caveat that making the zombies bucherable for bionics isn't as intuitive for new players in comparison of just making zomborgs spawn rarely within cities or in new map specials.

**Comment by Standing-Storm** [comment]
I'm not opposed to changing them to some variation on zomborg, but I originally went with bio-operators because they're deadlier in combat and an Exodii-related idea I had (that it's versions of zomborgs where more of the tech survived and was directing the movements of the dead flesh, a faster version to match with the zomborg's slow tanky version) failed since the Exodii don't have AI that they can put into installable CBMs.

I suppose one possibility would be making those `feral brains in a robot hunter-killer body` things the Exodii have, and scatter some around that went rogue due to the transit.

**Pull request merged**
