### PR TITLE
Change option groups to sentence case

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
Interface "Make the option groups sentence case"

#### Purpose of change
Unify names to be sentence case.

#### Describe the solution
Make strings sentence case

#### Describe alternatives you've considered
Interface "Make the header of Auto Notes Options title case" (original PR, changed following the comment)

#### Testing
None (string changes).

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Maybe we should go the other way and de-capitalize all headers? I mean, is there a reason for "options" to be written in upper case, anyway?

**Comment by Faalagorn** [comment]
> Maybe we should go the other way and de-capitalize all headers? I mean, is there a reason for "options" to be written in upper case, anyway?

Sure, should I change this PR to that instead or open a new one? I already decapitalize them all in Polish translation, as title case in here is generally reserved for just places and titles of magazines, movies and such.

**Comment by Night-Pryanik** [comment]
You can change them in this PR.

**Comment by Faalagorn** [comment]
> You can change them in this PR.

It should be done now, also fixes from  #76977 _should_ be included, let me know if something else needs adjusting!

**Pull request merged**
