### PR TITLE
Adds City Location: Strip Mall

### PR DESCRIPTION
**Pull request by pshepjr**
#### Summary
Content "Adds City Location: Strip Mall"

#### Purpose of change

Strip Malls are pretty common in the USA, and the New England area is no exception. 

The Strip Mall location makes heavy utilization of nested mapgen to generate its shops, therefore replicating the real-world equivalent which can often have anything from salons to clothing stores to lawyer's offices.

#### Describe the solution

The strip mall is a 5x1 city location containing 4 shops and a parking lot. Upon spawning, each shop will pull from a designated list of nested mapgens to determine the tenant. There are 24 total shops at the creation of this PR, and they are split into 4 separate groups of 6 to ensure there are no duplicate spawns.

Further, each shop has its own custom sign that often use >name_tags> to add more randomness and variety. The strip mall, itself, also has its own sign out front with over a dozen different variations.

The list of shops are below, one from each group will be selected via nested mapgen when the location spawns. The type of shop is on the left, and the sign out front is on the right:

**SHOP A**
Laundromat                          | _<family_name> Family Laundry_
Office - Insurance Agency    | _<family_name> of >city>, Insurance Co._
Clothing Store - Shoes         | _<given_name>'s Shoe Emporium_
Gaming Store                       | _<family_name> Worlds, Gaming Center_
Restaurant - Pizza, Variant 1 | _<given_name> & <given_name>'s World Class Pizza_
Empty - for lease, [ chance for survivor's camp inside containing zombies and loot ] | _FOR LEASE_

**SHOP B**
Empty - for lease | _FOR LEASE_
Salon | _<given_name>'s Beauty Parlor_
Office - Shady Hills Corporation | _Shady Hills Corporation, >city> Branch_
Lingerie and sex shop | _<given_name>'s Undisclosed_
Electronics Store | _<given_name>'s Electronics Unlimited_
Book Store | _<family_name> Family Books_

**SHOP C**
Furniture store,   variant 1 | _<family_name> Discount Furniture_
Office - Lawyer, Variant 1 | _<family_name> & <family_name>, Attorneys At Law_
Clothing Store - general, variant 1 | _>city>'s Finest Clothiers_
Restaurant - Ice Cream | _<given_name>'s Sundae Fundae_
Camping Store | _Ultimate Explorers of >city>_
Dojo | _<full_name>'s School of Self Defense_

**SHOP D**
Restaurant - Pizza, Variant 2 |	_<family_name>'s Humble Pies_
Furniture store, variant 2	| _>city> Furnishings_
Office - Lawyer, Variant 2 | _<family_name> & <family_name> & <family_name> & <family_name>, Attorneys At Law_
Clothing Store - general, variant 2	| Clothing Family <family_name>
Hunting Supply Store	| _<family_name>, The Huntsman_
Fitness gym	| _Champion <given_name>'s Fitness Center_

#### Describe alternatives you've considered

Adding more shops....... I got burnt out :)

If more locations are added, I could see myself making a larger variant of the location (for example, with 8 shops instead of 4).

#### Testing

The weight of the location in regional settings is 750. In my testing this generally resulted between 0 and 2 spawns per overmap.

Spawning the location overandoverandoverandoverandoverandoverandover

BIG THANKS to @ANickelN for also helping me test! You were a HUGE HELP!

#### Additional context

In the nested mapgen file (strip_mall_nested) I added a sample nested mapgen with brief instructions on how to properly create a new shop for this location. This way any new contributions can remain consistent:

Text: "Strip mall stores must be 23x by 23y, each chunk must include a back wall and storefront, and both the bottom and top row should be a sidewalk.  Use this sample as a base.  Rename it to one of the following: strip_mall_shop_a; strip_mall_shop_b; strip_mall_shop_c; strip_mall_shop_d"
image

<details>
  <summary>Location Screenshots</summary>
  
Overmap tile:
image

Visiting the >city> Discount Shops [part 1]
image

Visiting the >city> Discount Shops [part 2]
image

Visiting the >city> Discount Shops [part 3]
image

Visiting Ye Olde >city> Shoppes [pt 1]
image

Visiting Ye Olde >city> Shoppes [pt 2]
image

Visiting Slappin' Jimmy's >city> Strip Mall [pt 1]
image

Visiting Slappin' Jimmy's >city> Strip Mall [pt 2]
 image

</details>

### CODE REVIEW

**Comment by casswedson** [comment]
I spy with my little eye dirt tiles under these
image

**Comment by pshepjr** [comment]
> I spy with my little eye dirt tiles under these image

Fixed, thank you :)

**Review by MNG-cataclysm — APPROVED** [review]
For the names in the strip_mall_sign mapgen, you could place the names in several snippet entries, to help cut down on repetitive mapgen entries. You've done a great job with this.
On another note, could we add "Slippin' Jimmy's" as a name for the law office?

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by John-Candlebury** [comment]
Loot feels somewhat on the low side after giving it an in-game look. Looking at the definitions, theres probably too many 50/50 chances

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by pshepjr** [comment]
> Loot feels somewhat on the low side after giving it an in-game look. Looking at the definitions, theres probably too many 50/50 chances

I did some more comparisons and increased some of the loot in a few of the areas as a result. Thank you for the feedback.

**Comment by sparr** [comment]
> and they are split into 4 separate groups of 6 to ensure there are no duplicate spawns.

What, you've never seen Walgreens and CVS right next to each other? Or two pizza places in the same shopping center?

**Pull request merged**
