### PR TITLE
Tell the player that their shout is muffled

### LINKED ISSUE #19758: Yelling while wearing a gas mask appears bugged.
In that you do not see the reason why yelling with a gas mask on does nothing.
It should display a message informing you that you can not do this.

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #19758.

### CODE REVIEW

**Comment by codemime** [comment]
```
The sound of your voice is almost completely muffled!
You hear yourself scream/shout loudly!
```
There's a bit of contradiction.

**Comment by sethsimon** [comment]
Even with good hearing or canine/lupine/feline ears, the "You hear..." message doesn't show up for sounds that quiet.

**Comment by codemime** [comment]
> Even with good hearing or canine/lupine/feline ears, the "You hear..." message doesn't show up for sounds that quiet.

Dunno. I was testing this and I saw the messages simultaneously.

**Comment by sethsimon** [comment]
Fixed. I missed that case because my C-4 and stomach experiments gave me impaired hearing.

**Pull request merged**
