### PR TITLE
Prisoner transport van

### PR DESCRIPTION
**Pull request by faefux**
#### Summary
Content "A new prisoner transport van"

#### Purpose of change

Part 1 of adding some new vehicles and verity in vehicles as in my view it would be nicer to have some more vehicles.

#### Describe the solution

Decided to start with this simple prisoner transport van based on the already existing security van and the images on the following website: https://www.fleetsafety.com/american-aluminum-ford-transit-inmate-transport-modular-systems-extended-length-low-roof-mid-roof-and-high-roof-with-compartment-options/

#### Describe alternatives you've considered

Letting an american make this, I've never been in or even seen IRL an american sweat box so I've no idea if these are the ones even actually used.

#### Testing

Tested it on an older version due to constriants, worked fine.

#### Additional context

image

**Edit**: I had a thought to have a few of the new prisoner zombies spawn inside of them. Can anyone point to me to any other examples monsters are spawned inside vehicles?

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
It should spawn somewhere.

**Comment by faefux** [comment]
> It should spawn somewhere.

One step ahead of you. :) 
I added it to `/json/vehicle_groups.json` with a completely arbitrary number, if anyone would like to make it more or less common a spawn.  
I didn't add it to any actual maps because I always find placing vehicles pretty difficult so i'll leave until I change the prison map to have its own vehicle group (police car, police SUV, prison van 1 and prison bus[updated, next pr]) as it only has a `id: prison_bus` spawn right now. It would be nice if others wanted to place it anywhere though.

**Comment by Maleclypse** [comment]
How do they spawn inside of prison buses or is that only on prison bus wreck map extras?   It may require creating a map extra.  I wish I knew more about building vehicles.

**Comment by faefux** [comment]
> How do they spawn inside of prison buses or is that only on prison bus wreck map extras? It may require creating a map extra. I wish I knew more about building vehicles.

I do not quite understand what you mean, really sorry.  Where you referring to my comment above comment?

**Comment by Maleclypse** [comment]
> > How do they spawn inside of prison buses or is that only on prison bus wreck map extras? It may require creating a map extra. I wish I knew more about building vehicles.
> 
> I do not quite understand what you mean, really sorry. Are you referring to the second part of my comment above?

Sorry, there are occasionally prisoner zombies near prison buses and I was asking if that requires a map extra.  I think it does I'll try to link one later.

**Comment by Maleclypse** [comment]
> > > > How do they spawn inside of prison buses or is that only on prison bus wreck map extras? It may require creating a map extra. I wish I knew more about building vehicles.
> > > 
> > > 
> > > I do not quite understand what you mean, really sorry. Are you referring to the second part of my comment above?
> > 
> > 
> > Sorry, there are occasionally prisoner zombies near prison buses and I was asking if that requires a map extra. I think it does I'll try to link one later.
> 
> Cool. When this is done along with the bus I was considering doing a random little map actually that would depict a prisoner escape with some cop and prisoner zombies. That might be a fun little map extra if that's the kind of thing you're thinking of. :)

So this is what one of the prison bus map extras looks like.  You'd want to make new map extras using the prison van I think.

```
  {
    "type": "mapgen",
    "method": "json",
    "update_mapgen_id": "mx_prison_bus",
    "object": {
      "place_vehicles": [ { "vehicle": "bus_prison", "x": 5, "y": 15, "chance": 100, "rotation": 180 } ],
      "place_monsters": [
        { "monster": "GROUP_ZOMBIE_PRISON", "x": [ 0, 23 ], "y": [ 0, 23 ], "repeat": [ 1, 5 ], "density": 0.1 },
        { "monster": "GROUP_ZOMBIE_COP", "x": [ 0, 23 ], "y": [ 0, 23 ], "repeat": [ 0, 1 ], "density": 0.1 }
      ]
    }
  },
```

**Comment by faefux** [comment]
@Maleclypse great, much appreciated. :)  
I'll stick it in another PR after this is merged.

**Pull request merged**
