### PR TITLE
Multiple starting pets ( crazy cat lady )

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

```SUMMARY: Features "Allows professions to have multiple starting pets"```

#### Purpose of change
After the starting pets PR was merged, people asked if multiple pets were possible. now they are.

#### Describe the solution
Just made the JSON into an array and loaded that.
Added a crazy cat lady to showcase it.

#### Describe alternatives you've considered
N/A

#### Additional context
unknown

### CODE REVIEW

**Comment by curstwist** [comment]
They should start in a basement or contained area, to protect the cats.

**Comment by RarkGrames** [comment]
Gives a whole new meaning to Crazy Cataclysm.

**Comment by Rail-Runner** [comment]
Is it intended that this profession lacks a cell phone? I was adding it to most professions a while ago.

**Comment by davidpwbrown** [comment]
> Is it intended that this profession lacks a cell phone? I was adding it to most professions a while ago.

Yes. In my head, the stereotype of the crazy cat person is someone whos never got a cell phone, and connects to the internet via AOL dial-up still.

**Comment by I-am-Erk** [comment]
The truly important additions.

**Pull request merged**
