### PR TITLE
[RDY] Formatted most of data/json/item_groups.json using weblinter

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
No gameplay changes intended.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade Is formatting this file necessary at this time?

**Comment by kevingranade** [comment]
I'll get right on that the next time I want to read almost 10,000 lines of json.... in other words, no it's not necessary to rush this kind of thing.  Ideally we can do a lot of it in digestable chunks...

**Comment by BorkBorkGoesTheCode** [comment]
@narc0tiq I apologize for overloading your build and format system.

**Comment by narc0tiq** [comment]
Doesn't look like anything's broken, so... eh?

**Pull request closed without merging**
