### PR TITLE
removed type category from "Killer Drive" trait

### PR DESCRIPTION
**Pull request by voiddeal**
#### Summary
Bugfixes "fixed "Killer Drive" trait"

#### Purpose of change

Addresses issue #65849. i think you can have both traits without conflict

#### Describe the solution

removed `type` from "Killer Drive" trait so it doesnt conflict with "Psychopath" and stand out of the `HUMAN_EMPATHY` mutation-type
also removed its `prereqs`

#### Testing

small json changes

### CODE REVIEW

**Comment by Qrox** [comment]
What exactly does psychopath offer that is not offered by killer drive though? Judging from the json code, killer drive is an upgrade to psychopath and is strictly superior to psychopath. If there's any hardcoded effect that is not present in killer drive, it should probably be updated in the c++ code to use a psychopath flag instead. (There's an open PR replacing hardcoded trait ids of psychopath with flags #65849)

**Comment by harmez7** [comment]
yes, killer drive seems like an upgrade to psychopath
but i not sure if killer drive has the benefit of psychopath as well since they both share a same point cost (2)
going to check it out...

**Comment by Venera3** [comment]
All traits need a base human trait category to be cancelable, this will not pass the unit test. Also, the traits are both mental and build on each other.

**Comment by harmez7** [comment]
> All traits need a base human trait category

you mean `type` ?
if so well, not all traits have their own type according to the json file. "fast learner" for example

**Comment by Venera3** [comment]
Yes, don't remove the type. 
Point cost is pretty irrelevant in the first place, especially with the new character creation

**Comment by harmez7** [comment]
ok thanks

**Pull request closed without merging**
