### PR TITLE
Add more nutrition debug

### PR DESCRIPTION
**Pull request by RadHazard**
#### Summary
None

#### Purpose of change
As part of debugging my fix for #47663, I needed a good way to check/edit NPC stomach contents and the faction camp larder.  This adds debug tools for both things.  I'm adding these tools as a separate PR from that (pending) fix due to the string freeze.

#### Describe the solution
Added stomach contents to the needs menu, and also a function to edit faction camp calories

#### Describe alternatives you've considered
It was suggested I could add this with untranslated strings to make it into 0.F, but I figured since this is a debug menu feature it's not critical to have in 0.F

#### Testing
Ate something, verified that the displayed stomach contents changed as expected.  Removed stomach contents and verified that the contents are correctly gone.  Edited the faction camp larder and verified that the `#` menu shows the new value.

#### Additional context
image

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
We should have a broader discussion about whether or not we translate debugging tools/messages - I'm not sure they really need to be translated.

**Comment by actual-nh** [comment]
> We should have a broader discussion about whether or not we translate debugging tools/messages - I'm not sure they really need to be translated.

From TRANSLATING.md:
```
Error and debug messages must not be marked for translation.
When they appear, the player is expected to report them *exactly* as they are
printed by the game.
```
Debugging (and error) messages are not included in String Freeze - only translated messages are. (I asked about this in #42658.)

**Comment by anothersimulacrum** [comment]
> Debugging (and error) messages are not included in String Freeze - only translated messages are. (I asked about this in #42658.) I believe this includes anything going into debug.log, or emitted during tests; it does not include debug menu items and responses to them, as in this case, probably at least partially because a user may be instructed to use one of them in order to fix a problem with their game.

In that case, this should not be translating the strings it is introducing.

**Comment by RadHazard** [comment]
> In that case, this should not be translating the strings it is introducing.

Are you sure?  It seems like actual-nh was saying that debug log message should not be translated, but debug menu items should.  This adds new debug menu items, so would fall under the latter category.

Incidentally, the current debug menu is almost if not entirely translated, and that's the example I followed.

**Comment by actual-nh** [comment]
> > In that case, this should not be translating the strings it is introducing.
> 
> Are you sure? It seems like actual-nh was saying that debug log message should not be translated, but debug menu items should. This adds new debug menu items, so would fall under the latter category.

That is my interpretation. @BrettDong, any comments?

> Incidentally, the current debug menu is almost if not entirely translated, and that's the example I followed.

**Comment by BrettDong** [comment]
Debug messages shown in the sidebar are generally not translated, while debug menu interface shown as pop-up windows displayed in the center of the screen are generally translated.

**Comment by anothersimulacrum** [comment]
Ah my bad, I totally misread what you said (and then I quoted it!).

**Pull request merged**
