### PR TITLE
Add OVEN tool quality

### PR DESCRIPTION
**Pull request by mythosmod**
#### Summary
Content "Add OVEN tool quality"

#### Purpose of change
As suggested in #53684 - add OVEN tool quality

#### Describe the solution
Add OVEN tool quality to tool_qualities.json, add improvised and dutch ovens, add OVEN 2 quality to electric ovens, modify recipes that require baking to need OVEN quality

#### Describe alternatives you've considered
None

oven 3

oven 4

Oven

Oven 2

### CODE REVIEW

**Comment by mythosmod** [comment]
> We try not to do small orphan PRs like this, in order to implement this the OVEN quality should be added to some tools and recipes.

No problem, I will convert to a draft and then add some more before resubmitting :) thanks

**Review by LyleSY — COMMENTED** [review]
Love the idea and the approach here. My only concern is that this appears to remove the ability to cook a lot of stuff with a saucepan or skillet that can be cooked either on stovetop or baked. For those that can be cooked either way, I'd recommend something like "qualities": [ { "id": "COOK", "level": 2 }, { "id": "OVEN", "level": 1 } ], to use either, if I understand the code correctly. Might need another set of brackets in there.

**Review by LyleSY — APPROVED** [review]

**Comment by Night-Pryanik** [comment]
@mythosmod could you please resolve conflicts?

**Comment by mythosmod** [comment]
> @mythosmod could you please resolve conflicts?

Should be good to go now, took much longer than it should for me to spot the duplicate entry!

**Comment by I-am-Erk** [comment]
I'm ready to merge this but it's still failing the basic build test. Maybe try updating to master and see if that helps

**Comment by mythosmod** [comment]
> I'm ready to merge this but it's still failing the basic build test. Maybe try updating to master and see if that helps

Thank you, looks like that has helped :)

**Comment by OldFriendEr** [comment]
Hi, I think that you forgot to add the OVEN quality to the oven appliance

**Comment by Naadn** [comment]
Is cast-iron dutch oven didn't belong to any itemgroup so it won't spawn a oversight or intended? I want cook something that required oven 2 but haven't find a good place to settle down so I need the portable cast-iron dutch oven.

**Pull request merged**
