### PR TITLE
Changing flyer lore

### PR DESCRIPTION
**Pull request by Ruminator24**
#### Summary
Content "Changing flyers to fit with the lore of the game."

#### Purpose of change

There are going to be some more changes soon, if the mods permit it. For now, I've moved the missing person's flyer and remade it into an actual poster, in a similar style to the others. 

#### Describe the solution

I have reformatted and changed the flyer so that it now a missing's person report, rather than a flyer. In it's place, I added a flyer for a music venue featuring a local DJ.

#### Describe alternatives you've considered

There's a few more flyers I wish to change or remove, since some of these are old, and don't reflect the current lore. Here is a few:
-flier_57 "This is a leaflet about autoclaving procedure.  One sentence catches your attention \"/!\\Always place your tools into an autoclave pouch before autoclaving./!\\\" 
This seems like an odd subject to make a flyer for. It seems more better suited as a sign to be placed in hospitals.

-flier_71 "TOO LONG TO PUT HERE" 
This seems better suited as a survivor letter, rather than as a flyer.

-flier_52 "This is a poster advertising a underground bunker.  The poster shows a nuclear bomb wiping out a city while a family huddles safely underground.  There a slogan \"Concerned about enemy attack?  Want to protect your family?  Join the VAULT program today.\" which is written in the middle.  However, there seems to be no information about *how* one might do so."
This is just a fallout reference, but it makes no sense within the context of the game. This should probably be removed.

-flier_2 "This is an advertisement for compact bionic modules.  \"Nerve pain?  Depression?  Tardiness?  There's not a problem a compact bionic module can't solve.  Talk to your doctor to find out of CBMs are right for you!\""
This one I admittedly am not too sure about, but I believe a few others have discussed that the lore about CBMs have changed, and this is a outdated remnant of it. This should be changed to better reflect the lore currently.
#### Testing

Checked to see if they spawned correctly, and they did. 

#### Additional context

More changes may come, depending on what I'm allowed to do. People are also allowed to comment on which flyers they believe are outdated and such, or request to add new ones in, as long as they fit within the lore.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
The vault thing is a reference to an area that's been obsoleted, so it should probably get pulled.

**Comment by Venera3** [comment]
Both the Vault/Necropolis and bionic flyers should be removed, as well as the autoclave one.

**Comment by Legofan94** [comment]
Flier_54 should also be removed, It's both a holdover to when the game setting was in the late 20th century, and also a dated reference to the show Jersey Shore.

**Review by Maleclypse — DISMISSED** [review]
Thanks for these updates

**Comment by Ruminator24** [comment]
It's not finished for now, once I have the time I'll replace these with something more fitting.

**Comment by Ruminator24** [comment]
I have now replaced the bionic flyer, the vault flyer, the jersey shore flyer, the autoclaving flyer, and added a new flyer (thanks to u/Mycelium_Running on reddit for giving permission for letting me use it.) Hopefully these replacement flyers are to your liking, I tried to give them a vague resemblance to the originals that i replaced.

**Comment by Ruminator24** [comment]
Oh yeah, for posterity, I am OneBanana#3156 on discord.

**Comment by Ruminator24** [comment]
Man, i really need to check for spelling errors before I submit things.

**Review by Maleclypse — APPROVED** [review]
These are great! Thanks!

**Pull request merged**
