### PR TITLE
Rework more tool groups

### PR DESCRIPTION
**Pull request by mugling**
Move more tools in to `itemgroups/tools.json` and adjust some map drops to use the new groups.

`tools_electronics` is provided as a stub to be extended in a further I'm working on which includes a multimeter and oscilloscope (plus their improvised variants) as optional crafting tools that can improve crafting rate and success chance.

The majority of the deleted lines are in 248c785 which appears to be dead code?

### CODE REVIEW

**Comment by mugling** [comment]
Fixes #15679

**Comment by kevingranade** [comment]
> The majority of the deleted lines are in 248c785 which appears to be dead code?

I believe it, just one of the problems of having what is effectively data in code.

**Comment by Coolthulhu** [comment]
Doesn't fully fix #11090 - I still see zombies dropping aluminum kegs and lawnmowers.

**Comment by Mshock777** [comment]
I don't know if you already noticed, but item groups in power stations should be deleted and replaced
with new ones.

**Pull request merged**
