### PR TITLE
[CR] Fixed deprecated color used in mods

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
SUMMARY: Mods "Fixed deprecated color used in mods"

#### Purpose of change
Fixed warnings/errors about deprecated colors from the issue #32490.

#### Describe the solution
Changed colors to somehow appropriate alternative:
ltred -> light_red (obvious)
gray -> light_gray (not sure if this is ok)
tan -> brown_white (close enough)

#### Describe alternatives you've considered
Script required to check all json colors to find incorrect/deprecated.

#### Additional context
None

### CODE REVIEW

**Comment by ipcyborg** [comment]
I'm getting these errors from build system:
1. 
`ERROR: Error fetching remote repo 'origin'`
2.
`fatal: unable to access 'https://github.com/Homebrew/homebrew-cask/': transfer closed with outstanding read data remaining`
`Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!`

How to redo the build test?

**Comment by anothersimulacrum** [comment]
Jenkins Rebuild

**Comment by ipcyborg** [comment]
Thanks!

**Comment by ipcyborg** [comment]
> ... then someone with permissions needs to kick Travis.
And how do I summon someone with permissions?  Or should I just wait?

**Comment by anothersimulacrum** [comment]
Someone already kicked it, it failed again. But you just post a comment asking.

**Pull request merged**
