### PR TITLE
More cars!

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Content "Adds new cars, big and small"

#### Purpose of change

Expanding the variety of cars in game. Generic cars that are currently in game are almost exclusively station wagons with changed bells and whistles and small trunks.

#### Describe the solution

Car parts changes:
- [x] Add sedan trunk;
- [x] Increase the size of station wagon (walk-through) trunk;
- [x] Increase storage size of hatchback hatch.

Rename old car into station wagon.

Add more cars!

- [x] Generic sedans (diesel, gas, engine variations);
- [x] Microcars (like Smart, variations: gas, hybrid, electric);
- [x] Generic coupes (diesel, gas, v8 muscle cars, v12 sport cars, v6 sport cars);
- [x] Supercompacts (gas (?), hybrid, electric, tandems, wheel amount variations);
- [x] Town cars (5-tile wide sedan monstrosities, v6-v8);
- [x] Shooting brakes (sporty coupe station wagons);
- [x] Trunk-forward sportcars;
- [x] Three-wheeled motorbikes (like those made by Can-Am).

- [ ] Addition of all those new cars into spawngroups and into spawns.

#### Describe alternatives you've considered

Living with the utter lack of variety among the in-game cars despite the amount of RL car types and subtypes.

#### Testing

None for now.

#### Additional context

Sedan trunk sizes:
https://www.edmunds.com/sedan/before-buy.html#:~:text=Subcompacts%20offer%2010%2D12%20cubic,large%20sedans%20offer%2017%2D21.

Station wagon trunk sizes (about 600 L):
https://www.autoexpress.co.uk/ford/focus/estate/practicality
https://www.autoexpress.co.uk/volkswagen/golf/estate

Hatchback trunk sizes (about 400 L, and those are medium ones, can reach into 500s):
https://www.whichcar.com.au/car-advice/boot-sizes-of-best-selling-hatchbacks
https://www.carbase.co.uk/news-and-features/used-car-buying-guide/best-family-hatchbacks-with-big-boots/

### CODE REVIEW

**Comment by randomtyper** [comment]
Will probably axe the current sports car. 

A consideration for the future is adding a turbo V6. Similar/better performance and efficiency then even V8, but hungrier than V6. Intended for V6 sports car.

**Comment by Ruminator24** [comment]
Pls fix the cube van, I know the volume space is kinda fucked rn, but the fact that only 6 of the 9 spaces can only be used always bugs me :((

**Comment by randomtyper** [comment]
> Pls fix the cube van, I know the volume space is kinda fucked rn, but the fact that only 6 of the 9 spaces can only be used always bugs me :((

Sadly, it's not on my agenda as of now and does not really fit the theme of the PR (adding cars and car-related stuff, not vans). Nothing stops you from making the PR yourself, though, given you already have the Github account.

**Comment by GuardianDll** [comment]
you should add them into https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_groups.json where it fits

**Comment by randomtyper** [comment]
> you should add them into https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_groups.json where it fits

See the checkmarks) Will be done. At some point.

**Comment by Procyonae** [comment]
We need a really rare google maps car 😉

**Comment by randomtyper** [comment]
> We need a really rare google maps car 😉

I'll leave it to you. As for me, I got my hands full enough.

**Comment by randomtyper** [comment]
Ok, do I create a replacement beetle? Because a small cahne makes it fail the tests, it seems.

**Comment by GuardianDll** [comment]
The best and easiest would be to copy the old beetle, paste it into TEST_DATA mod, and tweak id's to be smth like "debug_test_car" to not overwrite original beetle - that would create a version of a car, specifically used for tests, and will not use the vanilla car

**Comment by randomtyper** [comment]
> The best and easiest would be to copy the old beetle, paste it into TEST_DATA mod, and tweak id's to be smth like "debug_test_car" to not overwrite original beetle - that would create a version of a car, specifically used for tests, and will not use the vanilla car

Aight, I hope I did it the least intrusive way.

**Comment by GuardianDll** [comment]
How it's going?

**Comment by randomtyper** [comment]
> How it's going?

Got distracted by other stuff and actually playing the game. The only thing that needs to be done is adding all vehicles into spawns, that's it. No ETA, though.

**Comment by randomtyper** [comment]
Aight... What is to do as of now:

- [ ] Long shooting bakes (4-seat ones, still 2 doors);
- [ ] Addition of said shooting brakes to the hunting lodge.

**Comment by randomtyper** [comment]
Well, the only thing that stands between me and having this being able to merge is that apparently you can't put a vehicle group into another vehicle group.

**Comment by GuardianDll** [comment]
are you sure you need a nested vehicle groups in it? why you can't just put them straight into groups even if some of them would intersect?

**Comment by GuardianDll** [comment]
Is it abandoned?

**Pull request closed without merging**
