### PR TITLE
Add night vision helmet attachments

### PR DESCRIPTION
**Pull request by b0bhat**
#### Summary
Content "Night vision helmet attachments"

#### Purpose of change

New NVGs which can be attached to military helmets via a pocket and can be quickly deactivated and swung out of the way to avoid obstructing eyes.
#70533

#### Describe the solution

Adds three new helmet NVG attachments, attaching on military helmets, mutually exclusive with face shields.
An older NVG, modern GPNVG, and a fancy enhanced/fusion NVG (light amplification + thermal).
These nvgs are a bit better and more efficient than the existing light amp goggles but need to be mounted on the army helmet, tactical helmet, or airsoft helmet. I tried to follow online stats for these goggles while keeping them in line with other gear.

Night vision goggles also use the low light overlay instead of the green overlay due to the NIGHT_VIS enchantment.

Old light amp goggles are reworked to clarify they are civilian active night vision goggles (IR camera + IR flashlight), which are comparatively more available, less expensive, and draw more power. Distribution has also been changed.

The ENVG is currently only issued to a few US army units right now so it'll probably be the rarest to find.

#### Describe alternatives you've considered

re-add in green overlay?
Also add a craftable headband thingy which can be worn with other hats to mount NVGs 
Allow crafting the old light amp goggles
Remove light amp goggles entirely
Instead of the helmet inheriting the nvg flag, change character nv detection to check in certain pockets for nv

#### Testing

Spawned soldier zombies and tested spawning
looked around
tested powered and unpowering conditions
Tested morale with filthy helmets

### CODE REVIEW

**Comment by GuardianDll** [comment]
why use hardcoded vision mod instead of something like `NIGHT_VIS` enchantment?

**Comment by Hyperseeker** [comment]
For what it's worth, the GPNVG (presumably that from [L3Harris](https://www.l3harris.com/all-capabilities/ground-panoramic-night-vision-goggle), since the weight matches) goes for around $47k: [source 1](https://licentiaarmsco.com/product/l3harris-gpnvg-18-ground-panoramic-night-vision-goggle/), [source 2](https://tnvc.com/shop/l3harris-gpnvg-ruggedized-bridge/).

Also, for what it's worth, it seems to be powered by [a battery pack](https://tnvc.com/shop/l3harris-pvs-31-battery-pack/) that straps at the back of the helmet. I believe a better implementation of that in the game would be making the GPNVG feed from UPS, and maybe adding a small helmet-mounted UPS pack. AA batteries (which is what the light battery is supposed to be) really don't do an NVG justice.

**Comment by b0bhat** [comment]
@Hyperseeker thanks for your feedback, will adjust the stats. It's a bit hard to figure out the volumes since they can fold, though I did bump them up.

The helmet UPS idea is an cool idea, maybe it could also be used alongside helmet flashlights, but I don't know how to prevent the helmet UPS from powering a character's ups tools too. I'm guessing it would also take light batteries.

The GPNVG requires a battery pack, some other NVGs have internal battery packs, taking CR123A or AA, and the battery pack linked takes 4 AA batteries.
What do you think about adding a head back coverage portion to the GPNVG to represent the battery pack and cutting battery longevity by ~4 or so, while keeping the light battery internal?

**Comment by Hyperseeker** [comment]
The thing about volume is that it remains the same regardless of the item's position or shape. Even when folded, they would take up exactly as much space, even if their 3-dimensional bounding box would look very-different. Like I mentioned, though, I think the 3 L volume from available dimensions is nonsense: one of the promo images puts the NVG (attached to a helmet) next to (what looked like) an MP7, and the NVG wasn't quite as big as the SMG.

> but I don't know how to prevent the helmet UPS from powering a character's ups tools too

This may not be relevant. The UPS is a nebulous technology that connects to any number of devices simultaneously using no cables. We can contemplate all the possible ways to make it more-realistic (like only allowing this UPS model to power that device, because proprietary connectors are a thing), but as long as the game itself isn't bothering with it, I reckon neither should you. Make it a low-capacity UPS that takes light or medium batteries (as opposed to the original UPS' heavy batteries), and let it be used in whatever ways the game allows.

Maybe one day someone will make the UPS something meaningful, like a USB power bank that needs a cable to connect and can only take up to X connections. Maybe that would also pave way to in-game proprietary power connectors and such. Until then, I figure we play the hand we've been dealt.

> What do you think about adding a head back coverage portion to the GPNVG to represent the battery pack and cutting battery longevity by ~4 or so, while keeping the light battery internal?

That's viable. You will also need to bump up the GPNVG's volume to represent the battery pack.

Though if you're going with batteries, you probably should go with medium ones for the device, and ditch the battery pack altogether. The medium battery would be enough to "fill out" the NVG in terms of volume and power supply. When attached, the battery would add volume to the whole arrangement, effectively acting as "that thing that hangs off the back of your helmet".

In fact, now that I think about it, this is probably the best solution. It adds viable content without requiring additional infrastructure (e.g., a custom UPS) that you'd have to make fit into the world as a developer. (And if you do like the idea of a custom UPS enough to add it into the game, you can always add it later, and keep the changes manageable within the scope of their respective PR.)

**Comment by Meadevil** [comment]
@bObhat  Can you clarify the intended impact on the function of the old light amp goggles? You mentioned the old LAGs were "reworked to clarify they are civilian active night vision" which I do see the 'infrared LED / IR camera' in the flavor text. You also said of your new NVG helmet attachments "Night vision goggles also use the low light overlay instead of the green overlay due to the NIGHT_VIS enchantment." - Did you also change the old LAGs to use low light overlay instead of the green overlay? Is this as intended? See #74208

**Pull request merged**
