### PR TITLE
Reload using magazines (part 3)

### PR DESCRIPTION
**Pull request by mugling**
Refactor `game::unload`

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Unloading liquids doesn't work properly. It always empties the container, even on partial unload or canceled unload.
(Might be one of the other PRs I'm testing, but that's quite unlikely)

**Comment by Coolthulhu** [comment]
Unloading guns with auxiliary gunmods doesn't properly determine what to unload.
Example: RM11B rifle with masterkey shotgun. Loading both the rifle and the shotgun and then unloading the rifle will always unload the shotgun first.

**Comment by mugling** [comment]
> Unloading liquids doesn't work properly. It always empties the container, even on partial unload or canceled unload

I can't reproduce this. What are the exact steps?

> Unloading guns with auxiliary gunmods doesn't properly determine what to unload.

What is the correct behavior?

**Comment by Coolthulhu** [comment]
> I can't reproduce this. What are the exact steps?

* Spawn contained gasoline (and get jerrycan of gasoline)
* Unload it
* When prompted for container, cancel with escape
* When prompted for direction, cancel with escape
* Jerrycan is now empty

And even worse:
* Spawn contained gasoline
* Spawn a plastic bottle
* Unload jerrycan with gasoline into the bottle
* Bottle is now full, but jerrycan is empty

> What is the correct behaviour?

Loading is possible in any order, unloading should be too.
If fire mode is not set to use auxiliary gunmod, unload the gun itself first. If it is set to one, unload that mod first.
Or ask the player what to unload with a menu.

**Comment by mugling** [comment]
> Or ask the player what to unload with a menu.

This sounds like a useful addition

**Comment by mugling** [comment]
@Coolthulhu the first of your examples is actually a segfault on my platform. Does e8bdb44 resolve the problem for you?

**Pull request merged**
