### PR TITLE
Sync some bullet recipes to their ammo count

### PR DESCRIPTION
**Pull request by Cyrano7**
Similar to https://github.com/CleverRaven/Cataclysm-DDA/pull/16801
There are still more to do but those numbers come out much messier. We might need a better system for handling this in the future.

### CODE REVIEW

**Comment by Cyrano7** [comment]
The fixed recipes are reloaded_44magnum, reloaded_500_Magnum, reloaded_57mm, reloaded_3006_incendiary, reloaded_762_51_incendiary.

**Comment by mugling** [comment]
> We might need a better system for handling this in the future.

Agreed but I'm not sure how to implement this

**Comment by mugling** [comment]
Have you considered migrating these to a separate `ammo/bullets.json` file?

**Comment by Cyrano7** [comment]
Ya but I don't like fixing/changing things and moving them at the same time.

**Comment by mugling** [comment]
It's not essential for this PR. You could consider doing them in separate commits? The recipes overall could do with some attention.

**Comment by Cyrano7** [comment]
Ya. Another thing to take a look at is the spawn counts too.

**Comment by mugling** [comment]
I'd leave `itemgroups/` alone for now as that's a separate topic

**Comment by Cyrano7** [comment]
Oh I misread the comment before the last one I posted. I was trying to say I'll look into migrating in another PR later and another thing to take a look at is the spawn counts.

**Comment by mugling** [comment]
No worries

**Pull request merged**
