### PR TITLE
Add M202A1 TALON UGV

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Content "Add an M202A1 FLASH armed TALON UGV"

#### Purpose of change
The M202A1 largely supplanted flamethrowers in American service and it would be a good choice for clearing infested buildings. The SWORDS mount on TALON UGVs can take M202A1s which makes them an attractive option for remote monster disposal.

#### Describe the solution
- Update M202A1 and reorganize data
- Add new `mon_talon_m202a1` to spawn rarely in lab security and in some of the same groups as flamethrower zombies
- Add crafting and disassembly recipes and items for new robot

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
>     * Add new `mon_talon_m202a1` to spawn rarely in lab security and in some of the same groups as flamethrower zombies

Is not that thing will just burn lab down?

**Comment by ymber** [comment]
Labs and outposts are mostly fireproof. There's a very small chance of these spawning somewhere flammable. They probably should spawn more with soldiers who were out fighting monsters.

**Comment by kevingranade** [comment]
I was struggling to come up with a place where I'd actually expect a M202A1 to be deployed, but I think you found it, I feel like the use case here is the secubot would be triggered to immolate an entire room as a failsafe in case of biohazard contamination, and in a whole facility lockdown it would fill a similar role.

**Comment by Firestorm01X2** [comment]
I've heard mention that labs supposed to be beatable with kevlar. But now I see tendention to install very heavy weapons on everything.

Will rule " labs should be beatable with kevlar" apply after that?

I've did some testing with new M294 CROW turret vs player with enabled RM13.

screenshot 2019-09-09 001_turret_test

One burst with on 1tiles may even instakill player in enabled RM13.

So overall tendention of installing vere heavy weapons everywhere  may end up very badly.

**Comment by kevingranade** [comment]
We do not have a defined difficulty level for labs, there is a STRONG consensus that they are too easy to deal with by a very wide margin, so increasing the danger level is moving us in the right direction.

The kevlar thing sounds like a rule of thumb promoted by players, please don't confuse wishful thinking with design.

**Comment by ymber** [comment]
There's a big gap between an area being reasonably doable with certain gear and that gear making you immune to everything in the area. It was never a design goal for labs that nothing in them should penetrate kevlar. A lab diving plan should involve not getting shot and that isn't unreasonably difficult if you check what you're walking into before you walk into it.

If you're taking that much damage from a 5.56x45mm round while wearing RM13 armor there might be an oversight in that armor's stats.

**Comment by mlangsdorf** [comment]
"Labs are beatable with kevlar armor" is not in a known design document.

Turrets have less than 50 tiles of vision, so you can just shoot them from outside their vision range.

There's an edge case of a turret that is far enough back that you can't throw an EMP grenade at it safely but close enough that you can't shoot it from outside it's vision range, but the game should have some challenges, and I think you can get past that with a couple of smoke grenades to give yourself cover while you get close.

**Pull request merged**
