### PR TITLE
to make draft pr - this will make anvils useable as work area surfaces and installable into vehicles as such

### PR DESCRIPTION
**Pull request by misterprimus**
#### Summary
Category "Brief description"

#### Purpose of change

Make anvils installable into a vehicle as such:

https://www.youtube.com/watch?v=ufXeIQgMr8Q

It would be installable only on empty vehicle tiles like steel rams to account for space needed to operate the anvil as someone suggested.

Reason is to cut down the step of constructing an anvil every time to smith when traveling in a van/truck. Also the anvil can act as a work surface, as that's where the work is done anyway.

#### Describe the solution

Installable anvils sort of like mounted electric forges. **_Waiting for devs to approve the general concept since this has apparently been discussed and rejected before._**

### CODE REVIEW

**Comment by GuardianDll** [comment]
I suspect having an anvil installed in a car would not give a good, immovable surface comparing to installing it on a flat ground 
It won't be accepted

**Comment by Brambor** [comment]
There was a discussion about this exactly. The car suspension defeats the purpose of an immovable anvil.

**Comment by misterprimus** [comment]
> There was a discussion about this exactly. The car suspension defeats the purpose of an immovable anvil.

Good point. Hadn't thought of that.

Would they be open to something like this? https://www.well-shod.com/FORGING/anvil-stands/class/AN-ANVILS-:-AN3-VANVIL--AND--TRUCKVIL?page=1

Basically there would be an additional step to modify an anvil into a vehicle mounted anvil item (sort of like an electric forge is fabricated into a mounted vehicle forge) that can then be installed onto the vehicle. Given that forging is only doable while the car is parked, it would essentially be abstracted into the game that the player takes a second to deploy the stand to bypass the vehicle suspension and have the anvil resting directly against the ground below.

**Comment by Brambor** [comment]
> Would they be open to something like this? https://www.well-shod.com/FORGING/anvil-stands/class/AN-ANVILS-:-AN3-VANVIL--AND--TRUCKVIL?page=1

I don't know. The stand is only for getting the anvil out of the vehicle. It still needs to be placed on the ground, right? What if the car is parked such that anvil cannot be placed next to it? As stated in a previous discussion, it isn't that much work to deploy the anvil manually.

I recommend reading the discussion here and possibly even elsewhere:
 - #68386

**Comment by misterprimus** [comment]
> > Would they be open to something like this? https://www.well-shod.com/FORGING/anvil-stands/class/AN-ANVILS-:-AN3-VANVIL--AND--TRUCKVIL?page=1
> 
> I don't know. The stand is only for getting the anvil out of the vehicle. The anvil still needs to be placed on the ground, right? What if the car is parked such that anvil cannot be placed next to it? As stated in a previous discussion, it isn't that much work to deploy the anvil manually.
> 
> I recommend reading the discussion here and possibly even elsewhere:
> 
> * [Fixing up anvils, round 1 (attempt 2) #68386](https://github.com/CleverRaven/Cataclysm-DDA/pull/68386)

But why can't this: https://www.youtube.com/watch?v=ufXeIQgMr8Q

be usable, just deployed within a vehicle with the stand arm going through a hole in the floor vs off the edge of the trunk?

**Comment by misterprimus** [comment]
> I suspect having an anvil installed in a car would not give a good, immovable surface comparing to installing it on a flat ground Not saying you would need to level it almost constantly for it to be flat It won't be accepted



> There was a discussion about this exactly. The car suspension defeats the purpose of an immovable anvil.

I guess I'll wait for the devs to reply to my latest post that has an example to see if they think it's realistic enough to be worth it to proceed before I make the changes.

**Comment by Maddremor** [comment]
You can just deploy an anvil next to your vehicle with the construction menu in 1 in-game minute as it is. Why make it more complicated than that? Also, you have no justifications or reasoning at all in your PR description.

**Comment by misterprimus** [comment]
> You can just deploy an anvil next to your vehicle with the construction menu in 1 in-game minute as it is. Why make it more complicated than that? Also, you have no justifications or reasoning at all in your PR description.

I corrected it and added to the OP.

**Comment by Brambor** [comment]
> But why can't this: https://www.youtube.com/watch?v=ufXeIQgMr8Q
> 
> be usable, just deployed within a vehicle with the stand arm going through a hole in the floor vs off the edge of the trunk?


To have a floor hole, you need surrounding space to be empty. You need to stand as low as the anvil is. Otherwise you are hammering the floor level, that is too low.

You cannot have a frame under the anvil, then suspension takes the hammer blows. So it needs to deploy next to the vehicle.

You need to swing your hammer, so no roof either. In a regular car, you cannot stand up when there is roof.

If you show us a video that doesn't need deployment, then you can omit the deployment. You showed a vid that needs deployment. That doesn't help your argument "not needing deployment".

**Comment by Brambor** [comment]
Are you actively playing with anvils in vehicles? (Deploying it outside.) Or is this more on the theoretical side?

For a feature to get merged it needs to be better than an available system. You need to be in-game familiar with the anvil construction.

**Comment by misterprimus** [comment]
> > But why can't this: https://www.youtube.com/watch?v=ufXeIQgMr8Q
> > be usable, just deployed within a vehicle with the stand arm going through a hole in the floor vs off the edge of the trunk?
> 
> To have a floor hole, you need surrounding space to be empty. You need to stand as low as the anvil is. Otherwise you are hammering the floor level, that is too low.
> 
> You cannot have a frame under the anvil, then suspension takes the hammer blows. So it needs to deploy next to the vehicle.
> 
> You need to swing your hammer, so no roof either. In a regular car, you cannot stand up when there is roof.
> 
> If you show us a video that doesn't need deployment, then you can omit the deployment. You showed a vid that needs deployment. That doesn't help your argument "not needing deployment".

What if the vehicle anvil is something that can only be build on an empty/adjacent tile of the vehicle like a steel ram?

**Comment by misterprimus** [comment]
> Are you actively playing with anvils in vehicles? (Deploying it outside.) Or is this more on the theoretical side?
> 
> For a feature to get merged it needs to be better than an available system. You need to be in-game familiar with the anvil construction.

That's what got me thinking about it.

**Comment by Brambor** [comment]
> What if the vehicle anvil is something that can only be build on an empty/adjacent tile of the vehicle like a steel ram?

AFAIK you can make that. Just like bicycle holder. I don't know if the deployment can be abstracted away. Definitely cannot be used while driving. It would constantly stick out of the vehicle. Which is fine for you.

**Comment by misterprimus** [comment]
> > What if the vehicle anvil is something that can only be build on an empty/adjacent tile of the vehicle like a steel ram?
> 
> AFAIK you can make that. Just like bicycle holder. I don't know if the deployment can be abstracted away. Definitely cannot be used while driving. It would constantly stick out of the vehicle. Which is fine for you.

Yes let me enter this into my description and I guess we'll see what the devs say.

**Comment by Maddremor** [comment]
You still haven't articulated why this should be added. When doing so, remember that smithing inside a vehicle is a very silly thing to do.

**Comment by misterprimus** [comment]
> You still haven't articulated why this should be added. When doing so, remember that smithing inside a vehicle is a very silly thing to do.

Added.

**Comment by Maleclypse** [comment]
Farrier anvil needs are not equivalent to survivor anvil needs.

**Pull request closed without merging**
