### PR TITLE
Edit lobster helmet description

### PR DESCRIPTION
**Pull request by TannHaals**
#### Summary
None

#### Purpose of change
Edited the lobster helmet's description to make it clearer that it was referring to a colonial marines helmet:

download

and not a 17th century lobster-tailed pot helmet:

download

I was seriously confused since a search for "lobster helmets" turned up only images of the latter.

#### Describe the solution
Reworded the description.

#### Describe alternatives you've considered
Changing the item name as well.

### CODE REVIEW

**Comment by Zireael07** [comment]
wow, I never realized it WASN'T the 17th century helmet xDD

**Comment by kevingranade** [comment]
If it's a fictional helmet it should be removed instead...

**Comment by TannHaals** [comment]
If it's to be removed, deleting all references to it in the code should work, right? If that's fine I can create a new PR to delete the item instead.

**Comment by kevingranade** [comment]
For removal the item needs to be moved to one of the obsoletion holding files, if there's a crafting recipe it needs to be turned into a migration entry, and any item group or other entries that mention it need it removed.

Alternately take it the other direction and turn it into the medieval version? Either way works.

**Comment by TannHaals** [comment]
Ok, I'll take a look at those and see if I can get a PR up.

**Pull request closed without merging**
