### PR TITLE
Test cases for player's morale after killing an NPC

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Infrastructure "Test cases for player's morale after killing an NPC"

#### Purpose of change
There have been some recent changes to morale upon killing NPCs. The code handling it is admittedly complex, and difficult to tell by reading exactly when morale penalties are, or are not, applied. Manual testing is difficult and time-consuming.

#### Describe the solution
Make some tests cases. Let the computer do the work for us!

#### Describe alternatives you've considered
Require contributors to submit proof-of-testing forms in triplicate whenever they touch a feature

#### Testing
Tests pass locally.

#### Additional context
CC @fairyarmadillo
You mentioned being unfamiliar with making test cases. This PR is not intended as instruction, but it's a simple setup that works and you may find it useful for the future.

### CODE REVIEW

**Comment by IdleSol** [comment]
Do these tests account for such situations?
 #71619

**Comment by RenechCDDA** [comment]
> Do these tests account for such situations? [ #71619](https://github.com/CleverRaven/Cataclysm-DDA/issues/71619#issuecomment-1937676007)

"Guilt" comes from killing *monsters* and is handled differently, this does not test it.

**Comment by IdleSol** [comment]
If I understand correctly what the tests say. It only tests melee kills ```player.melee_attack```. Correct me if I'm wrong.

But would there be a similar result if a firearm was used?

In the situation in the link. I received guilt if I killed a child up to 5 tiles away and didn't if the distance was more than 6.

I checked in manual mode. In that situation, the death of the NPC gives the guilt. But I checked only the standard relationship of the NPC to the player.

**Comment by RenechCDDA** [comment]
> If I understand correctly what the tests say. It only tests melee kills `player.melee_attack`. Correct me if I'm wrong.
> 
> But would there be a similar result if a firearm was used?
> 
> In the situation in the link. I received guilt if I killed a child up to 5 tiles away and didn't if the distance was more than 6.
> 
> I checked in manual mode. In that situation, the death of the NPC gives the guilt. But I checked only the standard relationship of the NPC to the player.

NPCs and monsters are different.
Killing a zombie child/animal/whatever --> MORALE_KILLED_MONSTER
Killing a **NPC** who was innocent --> MORALE_KILLED_INNOCENT

This PR has nothing to do with MORALE_KILLED_MONSTER.

**Comment by fairyarmadillo** [comment]
Oh cool. I've never understood how the test system works but this seems pretty straightforward.

It's no big deal if it's out of scope, but if you wanted to test morale values with different traits after killing the innocent, it should come out to:

Spiritual+Pacifist: -115
Numb+Spiritual+Prozac: -22
Uncaring: No change
Sapiovore: No change
Killer Drive+Spiritual+Prozac: +5

While writing these numbers up, I discovered a bug. Prozac affects numb+spiritual+prozac, but doesn't appear to be affecting killer drive+spiritual. I'm not really sure why that would be.

**Pull request merged**
