### PR TITLE
Grammar and punctuation fix

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Snaaty** [comment]
I'm gonna say it before KA101 does; double spaces are the style that is being used here. I didn't know until most recently, etiher.

**Comment by Night-Pryanik** [comment]
But... there were PRs that addressed these excess spacing, like https://github.com/Rivet-the-Zombie/Cataclysm-DDA/commit/618ad39ef68c31374f8c86673332e65201ec5030 or https://github.com/Rivet-the-Zombie/Cataclysm-DDA/commit/1fd620827b2383804e623b106cf43be411888426.

**Comment by narc0tiq** [comment]
@Night-Pryanik Both of those _added_ double spacing after the periods. Which is the Cataclysm style.

**Comment by Night-Pryanik** [comment]
Ouch. Seems like my eyes failed me. Two questions: 
1) Is there a way to edit my commit?
2) So we should add double spacing wherever there is single spacing?

**Comment by narc0tiq** [comment]
For the first, you could just push another commit. For the second, yes.

**Comment by Rivet-the-Zombie** [comment]
>So we should add double spacing wherever there is single spacing?

All text visible to the player should be double spaced after periods. It's not sd vital for comments, or any other text not actually seen in-game, but we still tend to use double spacing there, too.

**Pull request merged**
