### PR TITLE
Forward grip for KSG and other shotguns with pump-rail

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Hopefully this PR solves issues mentioned by @kevingranade in #22150.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
You could divide the unnecessarily inclusive underbarrel slot into one slot for things like lasers and grips and another one for large attachments like grenade launchers and flamethrowers.

**Comment by kevingranade** [comment]
Special casing it for the ksg isn't an option.
A new slot type would work, like "grip-only-rail".

**Comment by Night-Pryanik** [comment]
How about adding new flag to KSG and the same guns like `PUMP_ACTION_RAIL` and special-case flag instead of a gun in question? Or new slot type is better?

**Comment by Night-Pryanik** [comment]
We don't have rail-mounted flashlights, or did you mean rail-mounted laser sight?

**Comment by Wishbringer** [comment]
They both use the same type of rail.

**Comment by mlangsdorf** [comment]
special casing this to only support grips seems very weird to me. You can mount a rail laser spot on a KSG's pump rail.

Wouldn't it make more sense to flag mods that can be mounted on the pump rail with a new flag in the JSON, and then check against that flag instead of grip? Something like
```
+    } else if( has_flag( "PUMP_ACTION" ) && mod.type->gunmod->location.str() == "underbarrel" && !mod.has_flag( "PUMP_ACTION" ) ) {
+        return ret_val<bool>::make_failure( _("can only accept small mods on that slot") );
```
grips and rail laser sights would get the PUMP_ACTION flag, but underbarrel crossbows and grenade launchers wouldn't.

**Comment by Night-Pryanik** [comment]
> You can mount a rail laser spot on a KSG's pump rail.

You can, yes (and many other underbarrel mods too), but wouldn't it stand in a way of pumping its action?

**Comment by mlangsdorf** [comment]
No, the forearm grip rail is about 6" long, so a 2" laser spot still leaves you about 4" of space to hold the pump.  See http://blog.cheaperthandirt.com/wp-content/uploads/2011/11/KSG_ammo_4401web.jpg

**Comment by Night-Pryanik** [comment]
Ok, now only mods with PUMP_RAIL_COMPATIBLE flag can be installed on underbarrel slot of guns with rails on their pump action.

**Pull request merged**
