### PR TITLE
[RDY] Subway

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# Description

- Subway tunnels with rails and better subway stations;
- Based on railroad code from #21792;
- Sewer tunnels are on z-1 level, subway tunnels are on z-2 level (as metioned in #21488) to prevent crossing;
- Subway station consist of three levels: `sub_station` located overground (z0 level), `sewer_sub_station` located on z-1 level and `underground_sub_station` located on z-2 level;
- Subway stations aren't rotated, so subway tunnels are always connected on north and south ends.

# Screenshots:

*Overground of subway station (curses)*
default

*Underground of subway station and some tunnels (curses)*
default

*Overground of subway station (tiles)*

default

default

*Underground of subway station and some tunnels (tiles)*
default

default

*Z-1 level (only sewer tunnel and subway ladders):*
default

*Z-2 level (subway tunnels and stations):*
default

*`sewer_sub_station` on Z-1 level (tiles)*
default

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Is this going in 0.D, or is it too complex?

**Comment by ZhilkinSerg** [comment]
> Is this going in 0.D, or is it too complex?

Changes from this PR will provide better subway than current one, but I need to address some things before it will be ready to be merged.

**Comment by ZhilkinSerg** [comment]
jenkinks rebuild

**Comment by ZhilkinSerg** [comment]
jenkins rebuild

**Comment by ZhilkinSerg** [comment]
jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Should be good to go now. What do you think?

**Comment by BorkBorkGoesTheCode** [comment]
It's a hell of a lot prettier than the old map.

**Comment by BorkBorkGoesTheCode** [comment]
t_rubble might need to be renamed t_rubble_rail to avoid id confusion in future.

**Comment by ZhilkinSerg** [comment]
> t_rubble might need to be renamed t_rubble_rail to avoid id confusion in future.

Good point

**Comment by BorkBorkGoesTheCode** [comment]
As I've said before, this is a great addition. Thank you.

**Comment by BorkBorkGoesTheCode** [comment]
@Mshock777 @Chezzo Are you planning to add terrain sprites for these?

**Pull request merged**
