### PR TITLE
New monster: Colossal Zombullfrog, and zombie frogs no longer fear fire/pain.

### PR DESCRIPTION
**Pull request by Nebnis**
#### Summary
Content "Added new zombullfrog evolution and removed their fear of fire and pain"

#### Purpose of change
Due to feedback and as outlined by https://github.com/CleverRaven/Cataclysm-DDA/pull/65702#issuecomment-1552382898 and bombasticSlacks, i made a new monster that will evolve from the zombulfrog I also removed their amphibian species so they no longer fear fire/pain since it doesn't make sense that zombies fear them. Solves some of #66477

#### Describe the solution
New evolution from Zombullfrog who will have a higher weight than frog mother to tone down their ubiquity. This new type of frog will leap much farther and scream to daze survivors, i figured if we have a frog mom, then we can have a frog dad who will "sing" sweet melodies to survivors :P. Removed their fear of fire and pain due to being zombos.

#### Describe alternatives you've considered
Numbers are flexible

#### Testing
Logged and fought it.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
I'd like to quote Kevin on this one:

`You didn't present a rationale for it being a problem.`

`"Not practical to kill in melee" is not a problem.`

`"Requires specialist weaponry" is also not a problem.`

`"Has regeneration as good as X" is not a problem.`

Frog mother is a very dangerous enemy, but it's certainly not unkillable. The fact it can be encountered in the wild is not a *problem*. It's very slow, and the player can easily see it and stay away from it (its leap is on a *12* turn cooldown). 

Something like the zombear or **acidic zombear** is legions more dangerous than it, the latter having twice the speed, acid blood, and an acid ranged attack.

Even beyond direct comparisons there are enemies like the kraken which are vastly stronger than both of them put together while having actual armor. And then there's the scylla, with a staggering 75 ballistic armor, 7d9+10 damage, 850 HP, and still enough speed to run you down.

**Comment by Nebnis** [comment]
The problem is that you can meet it very often inside forests since it can spawn in rivers and swamps and wanders off chasing everything. This isn't something i was considering to nerf because of melee in the slightest. Even with a gun you would have a really hard time killing this monster and only a grenade is something you want to use to kill effectively, and ofc you cant use a grenade if you just spot this around corners in forests, so specialized weaponry is out of picture too. You can just randomly die, just like that, if this shows up in front of you.

>Something like the zombear or acidic zombear is legions more dangerous than it, the latter having twice the speed, acid blood, and an acid ranged attack.

I feel like you haven't fought one in a while if you think this is true or you severely underestimating how strong the regen or the new grab is.

Would at least removing the amphibian tag be okay  so they aren't scared of fire or damage?

**Comment by sadenar** [comment]
I disagree with reducing the speed of the tadpoles unless you find a new flavor for them.
Their description very clearly shows they're not "newborns" in the classical sense, they're supposed to be non-viable pseudo-organisms that are biological seeker missiles that literally burn away their limited stores of energy chasing after you. Unless that description is changed your speed nerf makes no sense.
It's very understandable to nerf the frog mother herself and/or her spawn probability, because flavor wise, her being a very slow threat with very mobile summons is what I think she's supposed to be, and I think it would make more sense for her to be confined to specific situations/later in the game would make her "broken" stats less oppressive.

**Comment by KHeket** [comment]
"Not practical to kill in melee" is not a problem.`

Frog mother is not practical to be killed both by melee and range weapon

> `"Has regeneration as good as X" is not a problem.`

It will not be a problem, if frog mother is not that common in late game. Go to the swamp or to sewer - you will meet them very frequently. And also cataclysm if going in realism way, and if colossal croaker, its previous version, have 4 regen, and magicaly frog mother have x 12.5 inreased regen boost (1250%) - its unrealistic and unreasonably

Making something super unrealistic is problem

> Frog mother is a very dangerous enemy, but it's certainly not unkillable. The fact it can be encountered in the wild is not a _problem_. It's very slow, and the player can easily see it and stay away from it (its leap is on a _12_ turn cooldown).

Frog mother due to its discription - have crippled legs, so it mast be super slow and dont have ability to jump becouse of crippled legs, its size and weight

> Something like the zombear or **acidic zombear** is legions more dangerous than it, the latter having twice the speed, acid blood, and an acid ranged attack.

Acidic zombear is very easy to kill and very rare anemy. You can kill it with few shots or just by knife/spear

> Even beyond direct comparisons there are enemies like the kraken which are vastly stronger than both of them put together while having actual armor. And then there's the scylla, with a staggering 75 ballistic armor, 7d9+10 damage, 850 HP, and still enough speed to run you down.

I dunno, who is scylla, but kraken is super rare in localized in the special cave, so you cant meet it, while gathering swamp plants, or going in sewer. I also met few frog mammas in sewers

After grab rework - frog mother is now less dangerous, but leaving unreasonable stats have no sense

**Comment by fairyarmadillo** [comment]
Frog mother didn't used to spawn all over the place, so it may be time to revisit those old arguments.

**Comment by RenechCDDA** [comment]
>The problem is that you can meet it very often inside forests since it can spawn in rivers and swamps and wanders off chasing everything. 

I am not sure this is a problem either. You've described the behavior of most enemies, including the most common faction (zombies) who blindly follow whatever sounds/enemies they see. The reality bubble is really the only thing hemming them in. If you enable wandering hordes, even that won't stop them.

>I feel like you haven't fought one in a while if you think this is true or you severely underestimating how strong the regen or the new grab is.

Their regen has been that way for years, so I am not sure what this means. I wouldn't let them grab me before 0.G either - automatic gunfire is a preferred option. As it should be.

>and ofc you cant use a grenade if you just spot this around corners in forests

Following on from the idea that it wanders away, this requires you to get within 3 overmap tiles of a swamp, at which point you should know the swamp is there. I give swamps a wide berth precisely because they have a bunch of nasty critters in them, and it's generally good practice.

>Would at least removing the amphibian tag be okay so they aren't scared of fire or damage?

They should be amphibians so I cannot see a rationale for removing it?

>Kheket: Frog mother due to its discription - have crippled legs, so it mast be super slow and dont have ability to jump becouse of crippled legs, its size and weight

Indeed they are already hideously slow, which makes them very trivial to avoid.

**Comment by KHeket** [comment]
> Would at least removing the amphibian tag be okay so they aren't scared of fire or damage?

Tadpoles after grab rework became very less dangerous so their speed can be leaved as it is. I think, reducing regen of frog mother and removing amphibian tag is okay, because its zombie. And also is will be good, if you reduce speed of it to 10-20, because frogs are not good runners, and frog mother also have crippled legs, big size and lots of tadpoles inside, so it should not be fast as normal creature

**Comment by Nebnis** [comment]
> > The problem is that you can meet it very often inside forests since it can spawn in rivers and swamps and wanders off chasing everything.
> 
> I am not sure this is a problem either. You've described the behavior of most enemies, including the most common faction (zombies) who blindly follow whatever sounds/enemies they see. The reality bubble is really the only thing hemming them in. If you enable wandering hordes, even that won't stop them.
> 
> > I feel like you haven't fought one in a while if you think this is true or you severely underestimating how strong the regen or the new grab is.
> 
> Their regen has been that way for years, so I am not sure what this means. I wouldn't let them grab me before 0.G either - automatic gunfire is a preferred option. As it should be.
> 
> > and ofc you cant use a grenade if you just spot this around corners in forests
> 
> Following on from the idea that it wanders away, this requires you to get within 3 overmap tiles of a swamp, at which point you should know the swamp is there. I give swamps a wide berth precisely because they have a bunch of nasty critters in them, and it's generally good practice.
> 
> > Would at least removing the amphibian tag be okay so they aren't scared of fire or damage?
> 
> They should be amphibians so I cannot see a rationale for removing it?
> 
> > Kheket: Frog mother due to its discription - have crippled legs, so it mast be super slow and dont have ability to jump becouse of crippled legs, its size and weight
> 
> Indeed they are already hideously slow, which makes them very trivial to avoid.

Well, it is a zombie who is being afraid of fire and damage. It is inheriting the amphibian tag flags.

**Comment by RenechCDDA** [comment]
> Frogs can spawn in rivers as well which makes their habitat to stay a wide berth off pretty huge

This doesn't appear to be correct, or rather it's not relevant. mon_frog_mother can *only* appear as natural placement, zombifying from dead mon_frog_mega (which requires something to *kill them*), or upgrading from mon_zombullfrog.

mon_zombullfrog can only be naturally placed or zombify from dead mon_frog_small. The presence of regular frogs and mutant frogs will not give rise to frog mothers, unless they are killed and revived (and possibly upgraded from mon_zombullfrog).

The appearance of frog mothers around rivers should be essentially 0, and **actually** 0 on your first time visits.

**Comment by KHeket** [comment]
> mon_zombullfrog can only be naturally placed or zombify from dead mon_frog_small. The presence of regular frogs and mutant frogs will not give rise to frog mothers, unless they are killed and revived (and possibly upgraded from mon_zombullfrog).

I just pushed the time of the world by 1 year and visited sewers, mostly sevage treatment plants and pump stations, and saw frog mothers and sometimes two of them at once, so no one killed them, because its freshy. But yeah, I didnt meet them in swamps and rivers.

<details>
  <summary>screenshots</summary>

image
image
image

</details>

Anyway, after rebalancing it will be more dangerous than its previous stage, and will be a big pain, if you meet it with other monsters

**Comment by RenechCDDA** [comment]
>I just pushed the time of the world by 1 year and visited sewers, mostly sevage treatment plants and pump stations, and saw frog mothers and sometimes two of them at once

Those are places it spawns naturally. Not sure *why* it does, but it does.

**Comment by Nebnis** [comment]
> > I just pushed the time of the world by 1 year and visited sewers, mostly sevage treatment plants and pump stations, and saw frog mothers and sometimes two of them at once
> 
> Those are places it spawns naturally. Not sure _why_ it does, but it does.

It is because zombullfrog can spawn in sewers from the group category of the map, and then they evolve naturally to mothers.

**Comment by Venera3** [comment]
Them being a guaranteed upgrade to zombullfrogs is a valid concern, but the solution to that is turning them rarer - add a alternative evolved frog with something like an acid flavor with a higher chance to result from zullfrogs.

To reiterate, having an "oh fuck" enemy spawn in the wild is *not* a real problem, so the nerfs to the combat stats is not actionable - they *are* killable if you come loaded for them, and they *are* lategame enemies that for once can threaten a lategame character. The rest of the post-year gang being wet noodles is the problem there.

The species adjustment is valid.

**Review by bombasticSlacks — CHANGES_REQUESTED** [review]
suggestions have been passed by other people,

fixing ubiquity is a more desired solution

**Comment by Nebnis** [comment]
Very well, i will start with removing their amphibian species flag then if that's alright. Should i edit this pr or just close with a new one?

**Comment by RenechCDDA** [comment]
Regarding the species change, I was confusing it with *faction*. Species does seem to only be used for flags and as a basic (non-intelligent animal) zombie I agree the inherited flags can be removed.

**Comment by Nebnis** [comment]
Hm i guess this needs the tests to rerun to not fail? Since there is no basic build passed

**Comment by NetSysFire** [comment]
Can you look into the mentioned issue and potentially add a closing keyword into your PR description?

**Comment by Nebnis** [comment]
@NetSysFire 

Done, i think. I'm not sure if i need to do anything else for this pr other than wait, it gone stale once already.

**Comment by anoobindisguise** [comment]
This is breaking a basic build,

**Pull request merged**
