### PR TITLE
Remove water_acid_weak from the game

### PR DESCRIPTION
**Pull request by Cyrano7**
Its dosn't spawn and can't be crafted. It's been out for a long time should I bother obsoleting it?

### CODE REVIEW

**Comment by pisskop** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/PKs_Rebalance/pk_recipe.json#L823

Lines
-823
-895
-918

**Comment by Coolthulhu** [comment]
Even in the core game, it is still used in weather.cpp.
The lines that mention it don't get invoked in unmodded game where acid rains are disabled, but no json entries mentioned in the code can be removed without removing the code parts.

**Comment by Cyrano7** [comment]
@Coolthulhu  Ya I had my search parameters off but I see it now, my bad.

**Comment by Cyrano7** [comment]
I don't have the time to test this atm so ill close this for now.

**Pull request closed without merging**
