### PR TITLE
Pain is Painful

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Balance "Pain is painful"
#### Purpose of change
Venera told me that the current formula for pain is bullshit: pain 100 can be obtained by taking 400 damage, which is pretty dang close to being dead; but 100 pain decreases only 4 of each stat, except perception, that decreases only for 3 unit. what the fuck 
#### Describe the solution
~~Change formula from `(pain^0.8)/10` to `pain/10` = now 100 pain would result in 10 stat decrease, except for int and per, for this two it would be 20 stat decrease~~
~~Changed the formula for int and per penalty, while str and dex penalty is untoched~~
~~Red is str and dex formula, Blue is int and per formula~~
Changed the formula to be percent based for each pain you lose 1% of your int and per stat, and for each pain you lose 0.7% of your str and dex
#### Testing
I'll make test in #72681 when this PR would be merged
#### Additional context
I didn't touch speed decrease because i don't know how this should be calculated
#### Additional context 2
image

### CODE REVIEW

**Comment by Hyperseeker** [comment]
An alternative would be to make pain modify limb scores instead of stats directly. One does not suddenly lose their muscle mass or the flexibility of their joints due to pain: they lose their capacity to exert the force of their muscles (sensory overload, concentration, and/or willingness to fight) and the coordination. The same, I believe, would apply to intelligence and perception, although we barely have their bonuses quantified as limb scores per se. (The only ones I see as being viable are reaction score and [night] vision score.)

While that would be outside of the scope of this PR, I believe that, if accepted as a better solution, this solution would supersede it.

**Comment by Venera3** [comment]
That comment was specifically re tanking intelligence and perception earlier, the rest of the stat scaling is not in a horrible place.

Limb scores are an optional add-on, but e.g. intelligence will never be limbed in any capacity and it should be the first to go - pain *hurts*, and you're distracted earlier than you let your sword go or whatever.

**Comment by Nebnis** [comment]
What about the adrenaline rush people usually get to muffle pain when in a dangerous situation? The stat decrease should be delayed a bit for the first time.

**Comment by RedMisao** [comment]
Agreeing with the people before me: this would worsen the current pain stunlock problem
(Basically, characters with certain amount of pain (the soft cap) quickly spiral into becoming effectively disabled (the hard cap), as when the character is hit it reduces their dodge and speed, which makes them an easier target for monsters, which gives them more pain and makes it worse for them to react, repeat until you're dead)

I don't mean "I want to clear the entire city in a single night with my katana" kind of situation
I'm talking how just getting lots of pain in a short period of time already makes the character virtually useless until they recover, regardless of hp or any other stat/number/value/effect. This change will make it so getting a _smaller_ amount of pain will have the same outcome

Not only that, as pain not _just_ reduces speed and dodge _and_ Dex _and_ Str for melee oriented characters, but reducing Int also greatly reduces spellcasting abilities, as the mana pool is directly proportional to Int

**Comment by SirPendrak** [comment]
Also, in current state, adrenaline is mutation or bionic only, while in reality, most fights would make normal people high enough on adreanaline that they would not notice some injuiries

**Comment by ADekema** [comment]
It feels wierd that pain scales liniarly. It would make more sense to make it a exponentional curve. Most people can deal with a bit of pain and be affected minimally especially if you have higher pain tolerance or experience with pain. But past a certain point pain becomes increasingly hard to deal with until you simply pass out.

**Comment by PatrikLundell** [comment]
I agree with @Venera3 that the STR/DEX penalties aren't in a horrible place currently (at least for characters with reasonably normal stats). Penalties hurt, and you typically need to withdraw/flee when beyond a couple of stat points in penalties, assuming you can: some enemies are too fast to get away from, so you have to bring out your emergency measures to try to kill it off before fleeing the scene.

However, there's probably room for additional penalties for superhuman characters so they get a meaningful impact from penalties (although they probably still won't be badly affected until close to death, but that's superhuman for you).
There may also be room for some capping of penalties for low score characters so they won't end up with negative scores from getting a cold (look at the horrible scores of the beggars when the RNGs produce a bad roll, one of mine had an INT of 0 when not subjected to any penalties at all).

I don't do magic mods, but normally fantasy magic is heavy on concentration, so being severely impacted by pain seems appropriate for normal types of magic (pain or emotions as fuel may work differently). Similarly, precise aiming of ranged weapons may also seem reasonable targets for precision reduction due to pain (presumably via PER).

**Comment by Aerin-of-the-Toast** [comment]
> Also, in current state, adrenaline is mutation or bionic only, while in reality, most fights would make normal people high enough on adreanaline that they would not notice some injuiries 

Adrenaline isn't magic, people do fight worse as a fight drags on and they get more and more battered and tired. (Hell they usually fight worse partially *because* of the adrenaline but we don't model that)

Regardless of adrenaline levels you're going to get worse as you get more injured even if you're not necessarily paying attention to the pain. Especially if you're fighting zombie after zombie and constantly fighting new, fresh enemies compared to you getting more and more battered.

**Comment by GuardianDll** [comment]
changed the formula based on discussion with Venera

**Comment by RanikOrtega** [comment]
A new survivor should be at real risk to succumbing to pain. But someone who has fought for months and been through the ringer should be able to shrug off a good amount before penalties kick in. Similar to cardio and fatigue we may need some sort of system of "How used to pain are you?" rather than simply you took pain resistant trait or you didn't. 

Perhaps some sort of soft "floor" or multiplier at the end of the pain formula based off of avatar_damage_taken statistic that reduces the affects of pain? And Pain resistant should instead kick that number up by a set starting value.

This may be an issue for a different PR but Pain in general seems wonky in that someone who is used to it should be able to shrug it to some extent and would help simulate survivor "toughening up" over time to some extent.

**Comment by I-am-Erk** [comment]
So, I think you're in a decent place here for the concept, but if we're going to change this I think we may as well finish it off: rather than a flat penalty, eg -1 int, make it a percent penalty based on your base stat. Having a 20 int should not mean you can shrug off pain penalties.

What I'd suggest is that for int and per, 1 pain drops your max stat by 1%, rounded appropriately. You could either do the equivalent for str and dex, or leave them unchanged for now, since they'll probably get limbified soon anyway.

**Comment by GuardianDll** [comment]
Won't it has an opposite issue, where character with, for example, 4 int, won't be affected by pain until, like, 25 pain (ignoring rounding)? Characters with higher stat would be penalized more, sure, but opposite would be true, and i don't think it's correct
I'll redo formula anyway

**Comment by I-am-Erk** [comment]
A person with 4 int already doesn't experience much penalty, they're not substantially affected by losing three int

**Comment by I-am-Erk** [comment]
All right, let's see where this takes us.

**Comment by AcidAntOnAMinefield** [comment]
Out of curiosity: is there a table or something that mentions what certain levels of pain should be equivalent to? 

Something like: Pain 1 being equivalent to being pinched by your granny, pain 5 being accidentally biting your tongue when chewing, pain 20 when you tweak/sprain your ankle when walking, etc etc?

**Comment by kholat** [comment]
At this point its kinda like - you cant even lift a glass of water after you take a few hits.

Besides, where is the rationale in this PR? Theres just a screen of Veneras msg from discord.
Where are the people like Kevin asking things like "what makes you think pain should be amplified? Can you link at least 1 paper that explains how debilitating pain is to a human body?". 
Is this really okay?

**Comment by I-am-Erk** [comment]
Some of the discussion took place in other venues, but since one of the lead devs reviewed it and decided it was okay, yeah it's ok. Feel free to read and comment in the follow up issues for more.

**Comment by gnneo** [comment]
Although there are some results regarding the effects of acute pain on muscle strength (cf. [1], [2] and their references), the exact relationship is complicated. Naively speaking, the maximum reduction should be around 50% initially and return to normal strength after a few minutes. 

To the best of my knowledge, there is no scholarly justification for reducing perception or intelligence from pain. Anecdotally speaking, I thought far more clearly and decisively when I was in serious pain, and was more keenly aware of my surroundings. So the relationship here may be more complicated still.

1. Farina D, Arendt-Nielsen L, Graven-Nielsen T. Experimental muscle pain reduces initial motor unit discharge rates during sustained submaximal contractions. J Appl Physiol (1985). 2005 Mar;98(3):999-1005. doi: 10.1152/japplphysiol.01059.2004. Epub 2004 Oct 29. PMID: 15516369.
2. Graven-Nielsen T, Arendt-Nielsen L. Impact of clinical and experimental pain on muscle strength and activity. Curr Rheumatol Rep. 2008 Dec;10(6):475-81. doi: 10.1007/s11926-008-0078-6. PMID: 19007539.

**Comment by I-am-Erk** [comment]
See #72851

**Pull request merged**
