### PR TITLE
Ability to examine non-interactively

### LINKED ISSUE #54159: Inconsistency of auto foraging when hauling stuff
### Describe the bug

When hauling stuff ( and *autoforaging* set to *everything* ) and walking next to : 
- Plants like Datura, Spurge... There is a prompt for picking up but saying *yes* results in no foraging.
- Trees ( at least I tried Pine tree ). And ferns. There is no prompt and the tree is not foraged.
- Underbrush. There is no prompt and the bush is foraged.

### Steps to reproduce

1. Haul something.
2. Move next to a Datura, a Pine tree, an Underbrush ( see it only collect the underbrush and see there is only a prompt for Datura ).
3. Stop hauling.
4. Repeat 2, see everything is foraged ( except when there is multiples tiles to be foraged at once, like a tree *and* a bush next to you ). See there is only a prompt for Datura.

### Expected behavior

Consistency of actions, be it impossibility to forage while hauling, or possible.
Consistency of messages, be it prompt or no prompt.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Sorry if duplicate, I just made a quick search before posting this issue.

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

### Purpose of change
Fixes #54159.
Some folks on reddit and on discord have raised some concerns about the missing harvest prompts. Also, autoforaging causes popups whenever the player walks next to a flower.

### Describe the solution
The problem is that `iexamine` functions don't really support examining things "non-interactively". This PR makes it possible to call most `iexamine` functions either "interactively" or "non-interactively" so that the caller can choose whether to present the player with prompts. It's also possible to add new features that trigger examine actions without interrupting the player with prompts/popups.

See the table of functions below for details about non-interactive behaviour.

### Describe alternatives you've considered
Not really an alternative, but I'd like to automate some of these actions and this is a good first step.

### Testing
Here's an example of `harvest_plant_ex`. Manually examining the crop calls the function interactively, prompting the player to continue. Automatically harvesting using autoforage calls the function non-interactively, which omits the prompts.

https://user-images.githubusercontent.com/12537966/140879477-e9aa33b2-481e-412e-9d70-5dc2b7661f98.mp4

These examinable actions have non-interactive functionality and should be tested:
- [ ] Translocators
- [ ] Attunement altars
- [ ] Elevators
- [ ] Controls gates
- [ ] Foodplace cardreaders
- [ ] Rubble
- [ ] Fences
- [ ] Bars
- [ ] Deployable furniture
- [ ] Portable structures
- [ ] Covered/uncovered pits
- [ ] Slot machines
- [ ] Safes and electronic gun safes
- [ ] Generic locked objects
- [ ] Wyrm pedestals
- [ ] Temple pedestals
- [ ] Door peepholes
- [ ] Flipable switches
- [ ] Dahlia flowers
- [ ] Poppy plants
- [ ] Cactii
- [ ] Generic harvestable furniture (plants)
- [ ] Generic harvestable terrain (plants)
- [ ] Nectar from plants (furniture/terrain)
- [ ] Marloss plants/trees/fruits
- [ ] Egg sacks
- [ ] Mounds of dirt
- [ ] Kilns
- [ ] Arc furnaces
- [ ] Autoclaves
- [ ] Hickory trees
- [ ] Untapped maple trees
- [ ] Reloading furniture (kilns, burners, etc)
- [ ] Signs
- [ ] Workbenches
- [ ] Workout

### Additional context
<details>
<summary>Expand to see a table of functions with non-interactive behaviour</summary>

*Functions that just return early are labelled as No-op*
| Function | Non-interactive behaviour |
| -------- | ------------------------- |
| `none`   | Same as interactive |
| `cvdmachine` | No-op |
| `change_appearance` | No-op |
| `nanofab` | No-op |
| `gaspump` | No-op |
| `attunement_altar` | Randomly select an available attunement |
| `translocator` | Automatically activate/deactivate translocator |
| `atm` | No-op |
| `vending` | No-op |
| `toilet` | No-op |
| `elevator` | Automatically use elevator if available |
| `controls_gate` | Automatically use the gate |
| `try_start_hacking` | Same as interactive (no prompt) |
| `cardreader_robofac` | No-op |
| `cardreader_foodplace` | Automatically attempt to unlock door if wearing Foodperson mask |
| `intercom` | No-op |
| `rubble` | Automatically clear rubble using available digging implement |
| `chainfence` | Automatically climb obstacle |
| `bars` | Automatically slip through bars with AMORPHOUS mutation |
| `deployed_furniture` | Automatically take down furniture |
| `portable_structure` | Automatically take down structure |
| `pit` | Automatically place a nearby plank over the pit |
| `pit_covered` | Automatically attempt to remove the plank from the pit |
| `slot_machine` | Play the slot machine once |
| `safe` | Automatically attempt to crack the safe |
| `gunsafe_el` | Automatically attempt to hack the safe |
| `locked_object` | Automatically attempt to pick a pickable object |
| `locked_object_pickable` | Automatically attempt to pick the object |
| `bulletin_board` | No-op |
| `pedestal_wyrm` | Automatically remove the petrified eye from the pedestal |
| `pedestal_temple` | Automatically place an available petrified eye on the pedestal |
| `door_peephole` | Attempt to unlock door from the outside |
| `fswitch` | Automatically flip the switch |
| `flower_poppy` | Automatically collect the poppy plant (or drink the nectar if possible) |
| `flower_cactus` | Automatically collect the cactus plant |
| `flower_dahlia` | Automatically collect the dahlia plant (also collects roots if there's a digging implement available) |
| `harvest_furn_nectar` | Don't prompt on harvest |
| `harvest_furn` | Don't prompt on harvest |
| `harvest_ter_nectar` | Don't prompt on harvest |
| `harvest_ter` | Don't prompt on harvest |
| `harvested_plant` | Same as interactive |
| `flower_marloss` | Automatically collect the marloss plant |
| `egg_sackbw` | Automatically collect the eggs |
| `egg_sackcs` | Automatically collect the eggs |
| `egg_sackws` | Automatically collect the eggs |
| `fungus` | Same as interactive |
| `dirtmound` | Plant a random seed if available |
| `harvest_plant_ex` | Automatically harvest a harvestable plant |
| `aggie_plant` | Choose a random available fertilizer on mature plants |
| `kiln_empty` | Automatically fire the kiln |
| `kiln_full` | Same as interactive |
| `arcfurnace_empty` | Automatically turn on the furnace |
| `arcfurnace_full` | Same as interactive |
| `autoclave_empty` | Automatically start the autoclave |
| `autoclave_full` | Same as interactive |
| `fireplace` | No-op |
| `fvat_empty` | No-op |
| `fvat_full` | No-op |
| `keg` | No-op |
| `tree_hickory` | Automatically attempt to pick the tree |
| `tree_maple` | Place the tap into the tree, but don't select a container to attach |
| `tree_maple_tapped` | No-op |
| `shrub_marloss` | Automatically pick marloss fruit |
| `tree_marloss` | Automatically pick the marloss tree |
| `shrub_wildveggies` | Automatically forage the shrub |
| `water_source` | No-op |
| `clean_water_source` | No-op |
| `reload_furniture` | Automatically attempt to reload the furniture with the most possible compatible items |
| `curtains` | No-op |
| `sign` | Print the signs message to the message log instead of a popup |
| `pay_gas` | No-op |
| `ledge` | No-op |
| `autodoc` | No-op |
| `quern_examine` | No-op |
| `smoker_options` | No-op |
| `open_safe` | Same as interactive |
| `workbench` | Automatically undeploy bench |
| `workout` | Automatically set workout activity |
| `invalid` | Same as interactive |
</details>

### CODE REVIEW

**Comment by dseguin** [comment]
Wow that PR description was a mess. Cleaned it up a bit.

**Comment by kevingranade** [comment]
I think this would be much better served by splitting methods into interactive and non-interactive parts.
The non-interactive part would just accept parameters saying what to do and would be called directly. The interactive part would just prompt for those parameters and pass them to the non-interactive part.

**Comment by dseguin** [comment]
That's tricky since some prompts rely on the outcome of earlier non-interactive bits. Although I do see some functions that can be broken out.

**Comment by Zireael07** [comment]
Hopefully goes into the list of PRs to be redone *hint hint*

**Pull request closed without merging**
