### PR TITLE
Tilesets updated to use portal sprite for tear in reality

### LINKED ISSUE #18953: Chesthole32 tileset lacks art for Tear in Reality
So after spending a good while fending off dozens of assorted sub-prime abominations, I finally figured out where they're coming from.

There's a tear in reality, which is completely invisible while using the chesthole32 tileset. I only managed to find it by accidentally attempting to walk through it, whereupon the game asked me if I was sure I wanted to do so.

Screenshot attached
error 5

### PR DESCRIPTION
**Pull request by Veraghin**
Tiles checked in Tiled, to make sure ID matches the suggested portal sprite in all cases

Closes #18953

### CODE REVIEW

**Comment by Leland** [comment]
FYI, fix from tileset creator in #23203

**Comment by illi-kun** [comment]
@Veraghin thank you for fix, it will be useful even with #23203. Namely, these files are changed in the current PR but wasn't touched in #23203:
```
gfx/MShock24TilesetModded/tile_config.json
gfx/MShock32TilesetModded/tile_config.json
```

My proposition is to remove Chesthole tilesets fix from your PR (because #23203 contains more complex update of these tilesets) and focus only on MShock tilesets here.

**Comment by Veraghin** [comment]
I'll just close this and submit another fix then

**Comment by Veraghin** [comment]
New Pull request submitted just for MShock tilesets

**Pull request closed without merging**
