### PR TITLE
Reveal overmap when submaps are 25%+ revealed by light/visibility

### LINKED ISSUE #11718: Change overmap reveal to depend on LOS more than light level?
During the daytime, the overmap reveals in a radius around the player, including being able to see things deep in the forest. This seems like too much. Maybe we could use LOS calculations, and declare that certain overmap types block LOS, like normal map tiles do?

At night, as soon as you step on a single square of a new submap, the overmap tells you what kind of submap it is. This seems like too much. Maybe you should have to reach the middle X% of the submap to have it revealed, or have LOS to more than Y% of it?

At night, when you have a flashlight or headlights illuminating some, most, or even all of a submap, it doesn't get revealed on the overmap until you step onto it. This seems like too little. If I drive around at night with a vehicle covered in headlights, I should get the overmap revealed one or two tiles around me, as the headlights reach.

I can probably implement this; I'm looking for feedback, balance concerns, reasons it's done the way it is, etc.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9847758-change-overmap-reveal-to-depend-on-los-more-than-light-level?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #11790: map::draw() and cata_tiles::light_at() do the same job, not quite the same results
It looks like these two functions do very similar tasks, one for ascii and one for tiles. However, they don't quite match up, for things like the indoors check in map::draw(). Am I missing something, or is this a bug?

I'd like to try to consolidate this code into one place, rather than having a bunch of dupicate information in map and cata_tiles (such as map.light_sight_range and cata_tiles.sightrange_light, etc).

This will reduce code duplication, remove inconsistencies between the two modes, and also make the relevant functionality usable elsewhere. If there's something I'm overlooking that explains why this needs to stay separate, please let me know?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9983793-map-draw-and-cata_tiles-light_at-do-the-same-job-not-quite-the-same-results?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sparr**
This patch is a superset of #11797

It changes map::draw and cata_tiles::light_at to use the same base loop and just different square-rendering functions.

On top of that, it adds functionality so that making submaps visible with light (or otherwise) will reveal them on the overmap, even at night when overmap view distance is otherwise limited.

Resolves #11718 
Resolves #11790 
Closes #11797

### CODE REVIEW

**Comment by KA101** [comment]
Looks like the future is now.  :-)

**Comment by BevapDin** [comment]
To continue from the other issue:

> Within the 132x132 arrays related to the reality bubble, there are blocks of 24x24 entries that refer to an OMT. If you want to do something inside that array that applies to an OMT (like the patch I linked to above), you have to do multiple layers of coordinate conversion (not necessarily manually).

Actually only one: _to_omt.

> I actually gave up on that and just stopped at submaps, which was a cheap out for me.
> You can see, right there, where I'm doing something to an OMT in the context of map-square coordinates.

Why go over the submaps if you want overmap terrain in the first place? Use `ms_to_omt`. This has nothing to do with submaps or their size.

- loop over the map, for each square:
 - calculation absolute position, transform to **OMT** coordinates,
 - increment visibility counter for that **OMT**

- loop over all **OMTs** in the map, for each:
 - compare visibility counter and make it visible

Note the `omt_offset` is only to get coordinates that fit into the array.

```C++
// Number of overmap terrains the map contains:
static constexpr size_t OMT_COUNT = ( MAPSIZE + 1 ) / 2; // round up or so
// visibility counter, each entry has the number of map square on the overmap terrain that
// are visible to the player.
size_t map_squares_seen_per_omt[OMT_COUNT][OMT_COUNT];
memset( map_squares_seen_per_omt, 0, sizeof( map_squares_seen_per_omt ) );
// offset, because we want to put data into the array, the points must be in the range
// 0 ... OMT_COUNT-1.
const auto omt_offset = overmapbuffer::ms_to_omt_copy( getabs( 0, 0 ) );
for( int x = 0; x < my_MAPSIZE * SEEX; x++ ) {
    for( int y = 0; y < my_MAPSIZE * SEEY; y++ ) {
        if( !visible( ... ) ) {
            continue;
        }
        // abs_omt can be any large number, therefor we apply the offset,
        // which is guaratend to be less or equal to abs_omt, so the resulting point
        // is >= 0
        const auto abs_omt = overmapbuffer::ms_to_omt_copy( getabs( x, y ) );
        // transform coordiantes to be in the range 0 ... my_MAPSIZE / 2 + 1, so they fit
        // into the array.
        // e.g.: x,y = (0,0) -> abs_omt == omt_offset -> rel_omt == (0,0)
        // e.g.: x,y = (24,24) -> abs_omt == omt_offset + (1,1) -> rel_omt == (1,1)
        // ...
        const auto rel_omt = abs_omt - omt_offset;
        map_squares_seen_per_omt[rel_omt.x][rel_omt.y] ++;
    }
}
static constexpr size_t map_squares_per_omt = ( SEEX * 2 ) * ( SEEY * 2 );
for( size_t x = 0; x < OMT_COUNT; x++ ) {
    for( size_t y = 0; y < OMT_COUNT; y++ ) {
        if( map_squares_seen_per_omt[x][y] > map_squares_per_omt / 4 ) {
            // transform back, so we have the *very*same* values as abs_omt in the loop above
            const auto abs_omt = point( x, y ) + omt_offset;
            overmap_buffer.set_seen( abs_omt.x, abs_omt.y, abs_sub.z, true );
        }
    }
}
```

Same code using a map instead of an array:

```C++
std::unordered_map<point, size_t> map_squares_seen_per_omt;
for( int x = 0; x < my_MAPSIZE * SEEX; x++ ) {
    for( int y = 0; y < my_MAPSIZE * SEEY; y++ ) {
        if( visible( ... ) ) {
            continue;
        }
        const auto abs_omt = overmapbuffer::ms_to_omt_copy( getabs( x, y ) );
        map_squares_seen_per_omt[abs_omt]++;
    }
}
for( auto & e : map_squares_seen_per_omt ) {
    if( e.second > map_squares_per_omt / 4 ) {
        const auto &abs_omt = e.first;
        overmap_buffer.set_seen( abs_omt.x, abs_omt.y, abs_sub.z, true );
    }
}
```

**Comment by sparr** [comment]
That loop is, as you mentioned in a previous discussion, part of a critical code path. Doing the coorindate conversion in as few operations (and function calls) as possible is desirable.

I can get from relative map squares to relative submap with just one division, so that's where I stopped. Any other conversion involves conditions, among other things.

**Comment by BevapDin** [comment]
> I can get from relative map squares to relative submap with just one division, so that's where I stopped. Any other conversion involves conditions, among other things.

??? Every coordinate conversion is the same: map squares to submap: divide with 12, map square to overmap terrain: divide with 24, map squares to overmap: divide with (24*180). Only the numbers differ.

**Comment by sparr** [comment]
You forgot the relative to absolute change. I can convert relative map squares to relative submaps with a division. I don't think relative overmap terrain exists, so converting to that means doing the rel/abs conversion too. I went as far as I could get from relative map squares doing just division, afaik.

**Comment by BevapDin** [comment]
Omitting a few integer calculations looks a bit like premature optimization to me, have you tested that it matters? However, as long as it works (and it certainly looks correct), it's fine.

Btw. shouldn't you extract `my_MAPSIZE * SEEY` into a variable if you care so much about performance? Also, under certain circumstances, you call `light_at` twice in `apparent_light_at`.

**Comment by sparr** [comment]
At the time I wasn't sure of all of the steps involved in the coordinate conversion. I've learned a lot more in the last few days.

I expect the compiler to recognize that my_MAPSIZE and SEEX / SEEY don't change, although I wouldn't be opposed to putting them in a variable.

I've pushed a commit to remove the redundant light_at, good catch!

**Comment by sparr** [comment]
I've really enjoyed playing with this patch enabled, exploring at night by driving around with my headlights on. I'm not sure if "25% of any submap" is an appropriate threshold to reveal an OMT, but it feels reasonable so far.

Once #11808 lands I might even consider extending this to NOT reveal OMTs that you've only seen 4-9 squares of (such as when you walk into a new OMT at the corner).

**Comment by Zireael07** [comment]
I like the idea!

**Comment by DavidKeaton** [comment]
I like this.

**Comment by KA101** [comment]
If I wasn't Not Up For Testing at the moment (BevapDin's that I'd previously looked at is about it), I'd queue this as the only serious issue I'd known was Kevin opposing the underlying premise.  With that in, I'm not opposed to this.

**Pull request merged**
