### PR TITLE
Remove "handful" and "serving" from item names

### PR DESCRIPTION
**Pull request by Kodiologist**
#### Summary
```SUMMARY: BALANCE "Remove \"handful\" and \"serving\" from item names"```

#### Purpose of change
These prefixes make item names longer and don't seem to provide any information to the reader. Because they're prefixes rather than suffixes, the main part of the item name gets cut off in preference to them when there isn't room for the whole name.

#### Describe the solution
I removed the prefixes. I kept each `name_plural`, duplicating the respective `name`, so the game doesn't attempt to pluralize e.g. "blueberries" into "blueberrieses".

#### Additional context
See the discussion in #29074.

### CODE REVIEW

**Comment by KorGgenT** [comment]
while you're changing names, you could update it to the new format `"name": { "str": "goose", "str_pl": "geese" }`

**Comment by Kodiologist** [comment]
@KorGgenT Done.

**Comment by KorGgenT** [comment]
[you'll need to lint it now](http://dev.narc.ro/cataclysm/format.html)

**Comment by Kodiologist** [comment]
@KorGgenT Done.

**Comment by dunstad** [comment]
As someone who regularly plays on a tiny screen I really appreciate this!

**Pull request merged**
