### PR TITLE
[WIP] Prototype for new underground lab

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds a new json-coded secret lab style."```

#### Purpose of change
The current procedurally generated secret lab is very hard to update, and beginning to run quite far behind compared to other mapgen. In addition, while the variability of procedural generation is great, it's not well suited to a structured government facility. While the code might be salvaged for a lot of other stuff, secret labs might be better suited to follow a more functional and rigid floorplan.

#### Describe the solution
Functional and rigid floorplans are doable in json!

This uses json mapgen to create the basic prototype maps for a new style of secret lab.

The new labs will follow a fairly standard floor structure, although I'll make a few types of them:

z-1 will have a security entrance, a subway station, a decontamination area, and a loading dock.
z-2 will contain a ventilation maze overtop of the labs below. This will require some code support to work it out, but for now I can do a simple prototype.
z-3 contains labs, medium security close to the central elevator shaft with at least one wing extending to high security, requiring a pass.
z-4 in some facilities contains more labs, starting with high security and moving to ultra high. not every facility has these extra high and ultra high security things, so in those ones the lower levels move up one.
z-5 contains admin and living facilities.
z-6 contains maintenance, servers, main power, and some heavy bunkers.

Each floor from z-3 and below follows a basic `+` shape around a central elevator shaft. There are basic labs and things coming off the main hallways, then a secondary hall behind them with large back rooms for storage.

Using nested mapgen, I can add quite a lot of variability. This prototype is going to be pretty straightforward, but I hope to soon add some wacky things like collapsed hallways.

#### Describe alternatives you've considered
Upgrading the current lab facility.

#### Testing
All the way along.
image

#### Additional context
This is going to sit underneath #36578 for now. It will be a facility where CBMs and mutagens were studied.

### CODE REVIEW

**Comment by 8street** [comment]
> z-1 will have a security entrance, a subway station

I'm not sure, but probably in the game a subway rails are at level z-2. Here is a entrance to existing labs.

**Comment by Inglonias** [comment]
Is this intended to replace the existing labs completely at some point?

**Comment by Amoebka** [comment]
Subways are indeed at -2 currently.
Might also be nice to have an optional station at -4.

**Comment by I-am-Erk** [comment]
Thanks for the reminder, I'll remember to work subways onto 2.

This pr alone isn't meant to replace procgen labs, but it should start a movement in that direction

**Comment by I-am-Erk** [comment]
I'm going to close this one and file an issue for a mapgen problem that is driving me insane, that I'd like solved before I continue.

**Pull request closed without merging**
