### PR TITLE
Update Evac Center

### PR DESCRIPTION
**Pull request by pisskop**
Line by line this goes through and deletes extraneous entries.
This adds a few pieces of decoration, such as empty vending machines and indoor plants.
This also adds more functional bits, such as a second arsonist and a bookcase with a 20% chance of spawning a textbook and rubble outside every window to help slow down the zombies some.  Also adds a few trash cans, some of which can spawn trash.  Which isnt always useless.

Turns the rock walls into masoned stone walls, and adds a random shrub/dirt/grass generation in most regions instead of the fixed locations that were before.

### CODE REVIEW

**Comment by mugling** [comment]
Evac center shouldn't be smooth rock. Also why rubble outside every set of windows?

**Comment by pisskop** [comment]
I think its an improved look for it.  Rough hewn rock from the ground fits things like houses where everything around it is 'clean', but besides being in the wilderness where things are 'dirty', evac shelters are also designed in the lore to be these structures built to impress and assure the populace.  Clean lines really bring that out.

The rubble is the same as trash thrown outside the windows as an impromptu baracade.  They  do that with lockers and chairs, and they board the windows, so they wouldn't throw trash outside the windows?

**Comment by pisskop** [comment]
<a href="http://imgur.com/Uc84dpl"></a>

And two more:
http://imgur.com/ryLeOxZ
http://imgur.com/v2a7EUg

**Comment by pisskop** [comment]
I dont _need_ the rubble or the stone, but I feel like its a boon and overall enhancement.  It allows more inferral to happen.  Such as empty vending machines, they can infer that the shelter took the snacks.  With the rubble, its deliberately placed so that a player would be able to figure it out.


Letting players come to their own conclusion is better than telling them.

**Comment by mugling** [comment]
TBH I thought it was a JSON error. Not all (any?) tilesets have smoothed stone so it would be best to avoid use outside of mods until those have caught up further. Separarately the evac center should be brick or timber built anyway, not hewn from rock.

**Comment by pisskop** [comment]
They wont add a sprite for it until it becomes common enough to b required.

**Comment by pisskop** [comment]
Brick works for me.  Lumber would too, but wr have different ideas of what this building was before the fall

**Comment by Coolthulhu** [comment]
Lumber would make it too prone to fires. Brick is better.
Concrete would probably be the best, though. It's common and used for cheap, ugly buildings, resistant to fire, tough etc.

The refugee center must have been built before the cataclysm, so it should be assumed to be some sort of captured utility building, like a warehouse or a factory.

**Comment by mugling** [comment]
Now always filled with zombies and no NPC's?

**Comment by pisskop** [comment]
I don't know hwo you mean.

http://i.imgur.com/XnQ9GbK.png

^^ all the guards spawn, and so do the reps and arson and merc.

Zombies have [i]always[/i] spawned in the top left corner.

**Comment by mugling** [comment]
May bad, I had static NPC's turned

**Pull request merged**
