### PR TITLE
Fixed Fictional Weapons mod [WIP]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Several things were wrong with the mod: the Five0 Handcannon could not be used due to a range penalty of -70; The arc cannon had a low damage, several modslots didn't make sense; all the guns had ridiculous loudness penalties; etc..

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Who included the MP5A5 EOD? It looks like it's from City LifeRPG, maybe Half-Life.

**Comment by BorkBorkGoesTheCode** [comment]
@DeadLeaves did you create the MP5 A5 EOD originally, before this game?

**Comment by BorkBorkGoesTheCode** [comment]
I retire.

**Comment by DangerNoodle** [comment]
> Who included the MP5A5 EOD? It looks like it's from City LifeRPG, maybe Half-Life.

From the movie End of Days, and possibly more well-known here has referenced in Half-Life. http://www.imfdb.org/wiki/End_of_Days#Heckler_.26_Koch_MP5A3

**Pull request closed without merging**
