### PR TITLE
Revert #69555

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
None

#### Purpose of change

Again this is a bit too much and needs further consideration

- 2 different kind of pink eye, but they come from the same source, do the same things, are very difficult to distinguish from each other, can only be treated if you figure out which one you have. It's a bit too much, one kind of pink eye could be enough
- random tweak to glasse coverage thrown on top
- random fix for a different completly unrelated issue gets put in the middle without explanation
- re introduce slipping on ground like in a cartoon after we already denied it in the past #47851
- add a random obscure meme to crazycata

Maybe there's some things to keep in there, but probably not all of it, and it should definitly never have been all thrown in the same PR

TODO:
- [x] Keep antihistamines

#### Testing
Compile and runs without error
Pre revert: run around boomers and covered in bile > save > reload save post revert > no issue

#### Additional context

Eye irritant will come back either as part or after #72169

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Not sure whose cheerios I peed in. Why didn't anyone say anything for 4+ months?

And there are only two kinds of pinkeye, bacterial and viral. That's how pinkeye works in real life.

**Comment by fairyarmadillo** [comment]
Sorry to double post, but I'm also going to quote @kevingranade  from #47851 

[kevingranade](https://github.com/kevingranade) commented [on Mar 4, 2021](https://github.com/CleverRaven/Cataclysm-DDA/pull/47851#issuecomment-791145182)
If someone wants to jump through the hoops to have this be more fully consistent, like basing the risk on properties of the ground surface and/or footwear and/or gait, they can revert this and do so, but in it's current state it's a bit too cartoonish.

#69555 did all of that. The risk is based on the properties of the ground surface (a check for the ROAD flag), footwear (character's balance score), and gait (penalty for running, crouching characters don't slip). All of these factor in for monsters as well.

**Comment by kevingranade** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/pull/69555 did all of that.

Just checking for "FLAT" is not remotely sufficient, it needs to be flat, smooth, and nonporous for a slippery fluid to have any meaningful impact. We don't have those attributes so it also requires adding them to terrain. I thought this was obvious.

The bacterial or viral conjunctivitis thing is a hard no from me, chemical irritant based would be fine.

The meme is not ok.

**Comment by fairyarmadillo** [comment]
> > #69555 did all of that.
> 
> Just checking for "FLAT" is not remotely sufficient, it needs to be flat, smooth, and nonporous for a slippery fluid to have any meaningful impact. We don't have those attributes so it also requires adding them to terrain. I thought this was obvious.

`    if( has_effect( effect_slippery_terrain ) && !is_on_ground() && !is_crouching() &&
        here.has_flag( ter_furn_flag::TFLAG_FLAT, pos() ) ) {
        int rolls = 0;
        bool u_see = get_player_view().sees( *this );
        //ROAD tiles are hard, flat surfaces, so they are extra slippery.
        if( here.has_flag( ter_furn_flag::TFLAG_ROAD, pos() ) ) {
            rolls++;
        }`

It checks for FLAT to see if it's possible at all, then increases the chance if it's a ROAD tile, which indicates a tile smooth, hard, and flat enough to drag furniture or drive over without resistance.

**Comment by anoobindisguise** [comment]
So it seems to me like the proper response to "there are too many kinds of pinkeye" is to reduce the amount of pinkeye to just be one kind; the "I got zombie barf in my eyes" variety and just keep it nonspecific and treated with a specific drug, in this case antihistamines. Something bad should happen if zombie barf does get in your eyes, and pinkeye seems like a decent representation of that. TBH you don't even have to call it pinkeye, just "your eyes are irritated from having zombie barf on them, antihistamines might help" but pinkeye is a good colloquial term, I'm not sure what else you'd call it.

"ROAD" is a pretty good approximation of "manmade non permeable ground" but it's not perfect - I've also ran into issues where the terrain flag isn't quite specific enough to be ideal. That's kind of its own issue in general though and would require a lot of JSON churn of adding a second more specific flag to manmade/natural terrain. I'm inclined to agree that the "slippage" formula should generally be requiring more bile than a boomer can produce except maybe on death; if it barfs 42 ml at you there should just be zero chance of slippage at the impact point rather than a tiny chance (I know that the slip chance is scaled with field intensity, but any chance at all for the minimum intensity scenarios is probably too much imo).

Rather than outright slipping bile pools would ideally count as some kind of difficult terrain; you have to go a bit slower to cross them safely but don't ever slip. However as far as a I know fields just cannot do that at all and it would require a huge code infrastructure to support.

**Comment by Kamayana** [comment]
> It checks for FLAT to see if it's possible at all, then increases the chance if it's a ROAD tile, which indicates a tile smooth, hard, and flat enough to drag furniture or drive over without resistance. It could easily be swapped to only work on ROADs. The full list of ROAD tiles is here and I don't see any where slippery stuff wouldn't be an issue: https://cdda-guide.nornagon.net/json_flag/ROAD

ROAD looks a lot more believable to me, yeah. FLAT contains a lot of absorptive surfaces that I couldn't see becoming slippery from bile, like carpet, grass, and mud. ROAD has a few exceptions too, though, most notably dirt, so I'd be behind adding a new flag or parameter - `SMOOTH` / `smoothness: x`, as a suggestion. Having a parameter might be preferable because while I don't think bile could make mud slippery, ice definitely could, so a parameter would give more flexibility than a flag.

If that thing with surfaces gets changed then I don't really see a problem with slipping. Slippery icey sidewalks are a persistent concern in areas like where the game is set, and the game should have support for adding that in the future. To me a "cartoony" slip would be sliding forward out of control like on a slip and slide - just falling down is what actually happens in real life.

Also, I kinda like the two kinds of pinkeye because I didn't actually know that before - it's fun to learn things from this game.

**Comment by fairyarmadillo** [comment]
It wouldn't be hard to add a variable or a flag to determine terrain eligibility, yeah. Personally I think a flag would be sufficient and less work for future contributors. Adding it would just be a matter of sticking it on everything in the ROAD list with one or two exceptions.

**Comment by I-am-Erk** [comment]
Irritant conjunctivitis from bile exposure is a totally reasonable outcome. Viral conjunctivitis is most commonly caused by adenovirus, and I'm not quite sure why that would be in boomer bile... Especially not in combination with bacteria that could cause infection as well. The bacteria that cause conjunctivitis might be in there, but just generally it is more believable and playable to model it as irritation... this is going to be far and away the most likely outcome of getting boomer bile in your eyes. Plus that can then be extended to getting other things in the eyes, like acid spit. The concept itself is fine and will not be removed permanently, it just needs tweaking.

The slipperiness thing is a more complex issue requiring a lot more data to drive it properly, as evidenced here. It's a reasonable thing to have in the game, but it has to be more developed to work. If someone is willing to take that on, I'd suggest an optional "slip" value for terrain and fields, where the final chance of slipping is determined by the sum of the field slip value plus the terrain. So boomer bile on grass - not slippy. Deep blood on linoleum - slippy.

I haven't personally looked at how chance of slippage is calculated as I've been busy with work, but that also needs to take into account a few things like what the character is doing. Monsters also need to be susceptible, so that we can make slippery traps.

**Comment by fairyarmadillo** [comment]
> So boomer bile on grass - not slippy. Deep blood on linoleum - slippy.
> 
> I haven't personally looked at how chance of slippage is calculated as I've been busy with work, but that also needs to take into account a few things like what the character is doing. Monsters also need to be susceptible, so that we can make slippery traps.

This is already the case. I posted the code further up in the comments. I wish people would at least look at the PR body being reverted before they start saying what I've done is insufficient - combined with the fact that Fris and Kevin are just stonewalling me here it just feels like the devs are not interested in listening to me. The current method is:

If it's flat, slipping is possible, but unlikely.
If it's a ROAD, slipping is more likely.
If the character is running, clumsy, skating without the skater trait, slipping is more likely.
If the character is deft or slimy, slipping is less likely.
If the character is crouching, lying down, or has gastropod food, slipping is impossible.
The actual roll is determined by a combination of dexterity, athletics skill, footing, and balance scores.

Monsters use a simplified version of the above, bonused by their dodge skill, penalized by their speed and the STUMBLES flag. Monsters immune to prone and flying monsters are immune to slipping. The chance for monsters to slip is slightly too high, but was reduced by #71964 and is now IMO in a good place.

Changing it so that ROAD is required, or adding a smoothness value to tiles, or adding a SLIP_POSSIBLE flag to tiles would be only a few minutes' work (SLIP_POSSIBLE would just be a subset of ROAD excluding only a few terrain types) and shouldn't require a reversion.

**Comment by I-am-Erk** [comment]
> This is already the case. I posted some of the code further up in the comments and discussed this upthread. I respect that you're busy at this moment, but I wish people would at least look at the PR body being reverted before they start saying what I've done is insufficient

I know what you posted above, I read that. That's what I am commenting on. It's what other people have commented on. "ROAD" isn't adequate to represent what we want for a feature like this. A dirt road should be barely slippery. An asphault road is also unlikely to get very slick at all. About a third of my post was expanding on what we could do instead. I kinda took it for granted that you would understand the context, ie. that "road" isn't sufficient, for reasons posters above me had already stated.

For the remainder, I wasn't asking how slippage is currently calculated, my point was that it wasn't something I'd looked at so I can't comment on if it's fine as is or if it needs tweaking. What you've written looks ok, I just don't want to commit and sound like I'm approving it without a deeper look because of, well, \*gestures to all this\*.

I understand very well that you're feeling called out now. It's a shitty situation to be in and it's not meant to be personal, but I know there's no other way to feel about it. The senior dev team have been absent for a while, and some of our standards of review have slipped as a result. The same thing happened a few years ago when Kevin's first kid was born, and he again had to step in after a while and do some sweeping rewrites. *This is not your fault*, and you're caught in the crossfire because you tend to make huge, ambitious changes to the game, and quite frankly your design sense is different from ours - I do not mean that negatively, and it doesn't mean you can't contribute. It just means that as Kevin has come back and started reading over the changes he's missed and running them by the other senior devs, we're spotting stuff that shouldn't have gone in its current state. *This is not your fault*. It is ours; I personally take a lot of responsibility for it, as I've been invited to comment a few times and simply haven't been present enough to do so.  In the background, we're taking steps to try to prevent it from happening again, at least in the near future.

All that said, because you're the first prolific contributor in this time period to come under some scrutiny, I absolutely don't blame you for feeling frustrated. I'd be completely pissed in your situation as well. All I can do is assure you that the work you've done is valued, even the stuff we're having to adjust, and this isn't about you as a person or contributor.

**Comment by fairyarmadillo** [comment]
> "ROAD" isn't adequate to represent what we want for a feature like this

Sure, but as I have explained, it would be the work of an afternoon to draft up a better solution, and opening an issue asking me to do that, or simply doing it yourself in a PR, would have been great. I clearly have a lot of free time and until recently no shortage of enthusiasm, so the chance to improve what I thought was a pretty clever system (and one that we really should have especially in wintertime, this being New England) would have been great. There's broad agreement in the comments here that at least most of the ROAD tiles would work. If asphalt's not one of 'em, that's really easy to fix. If there's not time for a dev to thoroughly review it in the immediate future, then a comment in the resulting PR like, "hey, we're busy right now, it might take us a while to get to this" would suffice. I still don't see any justification for calling the idea "Looney Tunes" or removing it from the game entirely without debate.

And hey, it's called experimental for a reason. The players and contributors are playtesting it 24/7. @Montimorency was offering some feedback that I think was pretty illuminating. I'd love to put some of that to good use, but now I can't.

> I understand very well that you're feeling called out now
> 
> All that said, because you're the first prolific contributor in this time period to come under some scrutiny

I'm having trouble taking this in good faith because it's coming from you and not Kevin or Fris. There has not been word one from either of them about it. My comments have been ignored, even those that have been me trying to figure out what I need to do to right the plane here, and they've continued pushing commits and opening new pull requests, so I know they're not just absent or busy. If Kevin took five minutes to go, "hey sorry this is all coming down at once, things just worked out that way" or "I don't have time to reply right now, please sit tight until the weekend" that'd be fine. Well, I'd still feel kind of put out given the circumstances, but it might have saved everybody a lot of bad blood. I don't think that's an unreasonable expectation, either.

Instead, we have #72186 -

> Drunkenness as a protective measure is a pernicious and dangerous concept and I will not be party to it.
>
>Mental illness as a protective measure is also extremely problematic, and encouraging people to not take their medication is beyond the pale.

This was posted and merged in just a few minutes in an attempt to head off any discussion. If it's Kevin's opinion that these things should not be in the game and that's a hard no, then he's in the driver's seat and I guess that's fine. What I have a problem with is, on top of the fact that all of this stuff has targeted me and only me, the hostile and accusatory language here. Dude busted out a ten dollar word like "pernicious" and straight up said that I am _encouraging real-life people to not take their medication_ (for a fictional condition!).

But even with that PR text, in a vacuum, I'd have waved off the hostile phrasing. I disagree with the core complaints, but fine, whatever. I could have bought that Kevin hated the idea and not the person who submitted it. Except it's from a month ago and it's _only_ my stuff being reverted. What conclusion can I draw except that Kevin is specifically going through my PR history and nobody else's?

You're not the only dev who's reached out. Everybody thinks this sucks, but so far that hasn't done much to fix anything. It sounds like you either need to take on more devs or you need to do something about the submission and review process. Maybe a feature freeze for 0.I would have been the right move after all. But I don't see what that has to do with me being singled out, stonewalled, and pushed out.

**Comment by I-am-Erk** [comment]
> it's coming from you and not Kevin or Fris.

That's because I'm generally the one who tries to write this kind of thing, and because as I noted above, I feel a bit responsible for how much of this was missed. You *are* getting a "hey sorry this is all coming down at once, things just worked out that way", from me, because I'm one of the project's highest ranking development leads and the one most willing to write this kind of thing out. I'm speaking on behalf of the lot of us at the moment though.

> Instead, we have 72186 -

That's a pretty standard revert, the language isn't meant to target you personally. It's something Kevin feels strongly on so he used strong language and merged it promptly, it wasn't intended to indicate anything about you.

> it's only my stuff being reverted. What conclusion can I draw except that Kevin is specifically going through my PR history and nobody else's?

We've been going through a ton of stuff. Your PRs are consistently large scale, ambitious, and to be as blunt as I can, often go in directions we've previously avoided or decided against, like the slippage thing Fris linked in the PR description.  It's unmistakably the case that some of this stuff has been implemented in ways that shouldn't have been merged in the first place. Again, that's not your fault. We weren't paying close enough attention, and as a result, you've been doing things in ways that we should have addressed a long time ago. (For context, [one of the other ones](https://github.com/CleverRaven/Cataclysm-DDA/pull/72217) from the same review hit the floor yesterday).

Phrases like "looney toons" aren't meant to be personal attacks. Fris was making a reference to the fact that he previously had to remove banana peels for similar reasons, when he wrote the branch name.

> It sounds like you either need to take on more devs or you need to do something about the submission and review process.

Changes have already been enacted. It was mostly a matter of talking to one of the people with merge permissions and becoming more involved again in the process.

> I'm just kind of stuck sitting here feeling like I'm being pushed out.
﻿
Like I said, I can understand why you'd feel that way. However, you've had what, four reversions here? Two of which are specifically about the bile changes, and one of which you agreed with reversion and rewriting in the PR.
﻿
**bottom line though**
﻿
So, we're running afoul of one of the problems here, and it's one that is hard to put kindly: in my experience, it's been very hard to give you feedback that results in a productive two-way discussion. I've only got like five minutes every hour to read and reply to your comments here, and I'm trying to be as concise as I can in my replies. They're running into the 1kish word counts and it's really hard to have the time to read them thoroughly, let alone compose a reasonable reply. This is compounded by a tendency to assume bad faith, *which is very understandable on your part right now*, but not always. I saw your reddit thread about our disagreement on handling mutagen, and that was very 'missing missing reasons'. It's really hard to spend a huge chunk of my time trying to give you meaningful, actionable feedback about what you're concerned about, only to find you relaying it to reddit as "I-am-Erk responded with a definitive no". It makes it harder to offer the feedback you're asking for. Many of the issues we identified back then persist and relate to these PRs, such as renechCDDA noted [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/72169#issuecomment-1977476702), and related to the sort of things I was talking about [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/70699#issuecomment-1879753843) regarding the difficulty of giving and acting on feedback in some of these PRs.

**Comment by LucioMagno** [comment]
Honetly this entire drama could be avoided if you guys clarified things. if the better idea (the idea most people like) is to have a generic eye irritation, then let that be, it would make for a better gaming experience anyway even if its not SO realistic, a lot of the things in game already are not. If you guys think the process of implementing slippery surfaces is way too much work for right now, then just postpone it. The work the person who wrote the code that got reverted does not need to go to "waste" as it can be referenced or reworked in the future, its not good practice to hold onto work people in your team did not support just because it took time to make. Its hard to manage a project as big as this but with proper relations and clarifications, things could run a bit smoother, like some of the tiles in the near future <3 much love!

**Pull request merged**
