### PR TITLE
Prevent specifying default JSON values [RDY]

### PR DESCRIPTION
**Pull request by mugling**
Prevents specifying default values in loaded JSON whilst still allowing child items to reset fields back to the default. Combined with the linter should markedly improve the quality of our JSON data.

Code changes are relatively simple ~~~with the major issue being how to structure the JSON updates (especially mods) as a lot of lines will need updating~~

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This should be a warning, not an error that causes loading to be aborted. Otherwise it will be a major pain for people playing with non-mainline mods each time we update default values.

As for the mods, I see the following solution:
* Script that works per-mod
* Lints each file and notes size of the diff
* If the diff size exceeds some sane number, roll back and wrap it up as a PR
* Repeat until everything is good

**Comment by codemime** [comment]
If I get it right looking at the code, there's an obstacle: 

Mod A changes a value of an object: from default to X
Mod B changes the same value: from default to X

Being loaded independently, they would work without exceptions/warnings. But if they're loaded together, then not (though each of them is considered correct).

**Comment by mugling** [comment]
@Coolthulhu good suggestion, lets go with a less hostile `debugmsg` as the JSON data is still valid

@codemime well spotted although I'm not sure what to propose other than for now not checking mod data. This perhaps might be more expedient anyway as the major goal is to get the core data cleaned up - most mod authors copy from this initially anyway

**Comment by mugling** [comment]
Change of approach:

* Allow object parsers to accept second optional `src` field specifying from where data is loaded
* Source for all core game data is `core`
* Source for mod data is `mod.ident`
* Source for data loaded directly from world directory (espeiclaly third-party mods) is `custom`

The `assign` function then supports a `strict` argument (defaults to off) which can be optionally enabled for certain sources/fields - for example in aa33906 all `core` item weights are checked for redundant defaults.

**Comment by mugling** [comment]
Resolved merge conflict

**Pull request merged**
