### PR TITLE
More Survival Tools Series 6.5

### PR DESCRIPTION
**Pull request by chaosvolt**
Well, Graysage1 and Coolthulhu had a little argument over the nerfs to
tinder and the hobo stove that the latter recommended, so toning down
The Nerfening a bit.
1. Volume of hobo stove reduced from 8 to 6, still bulkier than hotplate
   but not horrendous.
2. Tinder volume reduced from 1 per 25 units to 1 per 50 units.
3. Ember carrier has been given 1 more volume in exchange for 50 more
   capacity, better ensuring you can run it overnight if you're willing to
   waste the tinder.

### CODE REVIEW

**Comment by graysage1** [comment]
>still bulkier than hotplate

Also note: it's also bulkier than [gasoline cooker](http://cdda-trunk.estilofusion.com/gasoline_cooker) and [oil cooker](http://cdda-trunk.estilofusion.com/oil_cooker).

**Comment by chaosvolt** [comment]
Hmm. Those also have less renewable fuel, and those are broken as fuck if I recall, as there are no cost multipliers for cooking with them despite the high charges of gasoline and lamp oil conpared the batteries. :V

**Comment by graysage1** [comment]
> there are no cost multipliers for cooking with them despite the high charges of gasoline and lamp oil conpared the batteries

I don't understand.  What is a cost multiplier?

**Comment by chaosvolt** [comment]
I mean well...for example, cooked meat takes...I think 7 charges of a hotplate? That means 7 battery units of a hotplate, 7 tinder from a hobo stove, 7 gasoline, 7 hexamine, etc. No way to tweak the usage to match how much fuel the item in question holds.

**Comment by graysage1** [comment]
>I mean well...for example, cooked meat takes...I think 7 charges of a hotplate? That means 7 battery units of a hotplate, 7 tinder from a hobo stove, 7 gasoline, 7 hexamine, etc. No way to tweak the usage to match how much fuel the item in question holds.

Oh, I see what you mean.  I thought that was deliberate.  It's because how dense these fuels are is handled in other ways having nothing to do with charges, but having to do how much fuel you can store per unit of volume.  Or so I thought anyway.

>Or in short, a little gasoline or lamp oil goes a LONG way, whereas the esbit stove had to had hexamine's stack size buffed to avoid having the opposite issue to too severe a degree.

I haven't come across any hexamine yet, or the items that use it.

**Comment by chaosvolt** [comment]
Mostly because Series 6 was the update that added esbit stoves and added hexamine to more item groups. Unmodded it's only useful for crafting a couple explosives.

**Comment by graysage1** [comment]
>Mostly because Series 6 was the update that added esbit stoves and added hexamine to more item groups. Unmodded it's only useful for crafting a couple explosives.

Uh huuuhh...  I see.  I didn't realize this.  New toys to play with.  It doesn't seem like my present char is qualified to make an esbit stove or hexamine, so I'll keep an eye out for them.

**Comment by chaosvolt** [comment]
At present they're like the acetylene torch in that you find them, not craft them. ^^"

**Comment by graysage1** [comment]
@chaosvolt Silly me assumed all the items in your mod are craftables. :)

Do you have plans to adjust the skill requirements for the ember carrier?  @Coolthulhu suggested that 2/2 would be fine if you felt like adjusting it.  Currently it's 4 survival 1 fab.

**Comment by chaosvolt** [comment]
Meep. Ah right, must've missed that part. And yeah, not all items are currently craftable, but most are.

**Comment by chaosvolt** [comment]
Also relevant from the discussion of mainlining coke...er, content. What to do about the flint and steel. o3o

**Comment by graysage1** [comment]
>What to do about the flint and steel.

I think it's a great item.  If you ask me, everything in your mod should be mainlined, but I am a rabid fanboi of this mod, and its general theme.  Obviously I am biased.

**Comment by chaosvolt** [comment]
I mean in terms of crafting it. Main issue is it makes the fire drill obselete due to unlimited usage, plus the realism issue of needing carbon steel. owo

**Comment by graysage1** [comment]
>I mean in terms of crafting it. Main issue is it makes the fire drill obselete due to unlimited usage, plus the realism issue of needing carbon steel. owo

Flint and steel is a thing, and in real life it's probably a superior kit anyway.  People were using flints long after they stopped using fire drills, IIRC.

So if we want to balance it, maybe flint should be a special stone instead of just an ordinary rock.  The game should maybe generate 1 flint per X rocks.

But like in real life, some items are just meant to be superior.  Not everything is equal.  So outside of making flint and steel harder to craft I have no idea how to balance it without ruining the whole point behind it.

Another way to balance it is to make flint and steel require tinder for each use.

**Comment by chaosvolt** [comment]
Not sure, but for now I figure giving flint and steel a fabrication requirement in addition to the survival requirement is a good first step, based on the assumption that you'd need to either know what to look for in a good firesteel material, and/or be able to work the metal into a basic striker shape. As for flint, if we had proper chert or flint that would be nice. owo

**Comment by graysage1** [comment]
I agree with your ideas.  Yea, we already have rock and sharp rock, and if you drill underground you sometimes get another kind of mineral (I forget now which).  So the game already has a concept of different minerals.  Teaching it about flint and other kinds of minerals/rocks might be possible.

**Comment by chaosvolt** [comment]
Limestone, if I recall, is the main thing I've seen underground in addition to mundane rocks. Flints for flintlocks would also be a clever detail.

Cataclysm: Dorf Days Ahead.

**Comment by graysage1** [comment]
I agree again.  If flint or chert are rare materials, that would means fire drill is what you make by default to start with.  Then once you get lucky enough to find flint, you can upgrade to flint and steel.

If we really want to get realistic, it's also possible to strike steal against steal and get sparks, but that will probably make flint and steal too easy to craft, unless again, we want to start separating steals by grade.  Right now all steal is just steal.  There is no stainless, high carbon, etc.

**Comment by chaosvolt** [comment]
Unless you assume superalloy is an iron alloy mainly and not a titanium alloy, yeah. o3o

**Comment by graysage1** [comment]
If questions of balance come up, we should remember that lighters and matchbooks are still the best.  Unless there are plans to make lighters and matchbooks exceedingly rare, it's kind of a moot point to stress too much over other sources of fire, imo.

**Comment by chaosvolt** [comment]
True, so a few minor nudges towards balance go a long way. owo

**Comment by chaosvolt** [comment]
Squee. And thank you for the merge. <3

**Pull request merged**
