### PR TITLE
Adding two json mapgen variations for hardware stores

### PR DESCRIPTION
**Pull request by KiwiTrinsic**

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This looks great!

**Comment by PropaneSoup** [comment]
Very nice, love to see more variants.

**Comment by KiwiTrinsic** [comment]
Thanks!

**Comment by vache** [comment]
This is something I sort of nitpick on, but be careful about creating structures with walls that butt right up to the edge of the 24x24 area.  If two such structures are placed next to each other, it creates an ugly double wall that sticks out like a sore thumb.  Also, I'm a big believer in back rooms (for offices and storage) and back doors.

**Comment by Rivet-the-Zombie** [comment]
>back rooms (for offices and storage) and back doors

These add a huge amount of character to structures.

**Comment by narc0tiq** [comment]
> This is something I sort of nitpick on

But it is important, so please keep doing so.

**Pull request merged**
