### PR TITLE
Ally zombies and robots with arthropods

### PR DESCRIPTION
**Pull request by Coolthulhu**
Zombies don't want to attack arthropods because those are too small and won't zombify. While described as "size of a small dog", most arthropods aren't anywhere near dog-like in shape, don't smell like anything zombifable and run away easily. For flying insects, the most of the extra size goes to wingspan.

Bees, wasps and spiders don't want to attack zombies because those are inedible.
Later on they could attack them to protect own nests, but for now they spawn too close to each other which only results in player seeing a fight break out. And arthropods would eventually lose that fight due to zeds rezing, so its better to just let the player see the aftermath: arthropods "figuring out" that attacking zeds doesn't work.

Roaches don't attack zombies because even though they probably could tank that blob poison, they have a lot of better food around. And zombies also provide protection by removing ants and fungus - two things very good at removing roaches.

Similar reasons for minor arthropod factions, such as centipedes or mosquitoes.

Robots and arthropods also ignore each other. Robots are not edible (not even for roaches), arthropods don't register as anything a robot would care about.

Bees, wasps, roaches, spiders etc. will attack each other just fine. Different species of spiders will attack each other. It's just that they will ignore zombies and zombies will ignore them.

Ants don't get the alliance with zombies. Ants have the means of dismantling zombies, it's just that it's not implemented yet. Plus, ants are quite big and thus the zombie instinct of ignoring small stuff doesn't protect them.

### CODE REVIEW

**Comment by Zireael07** [comment]
Nice!

**Comment by Core0verload** [comment]
I'm against making wasps and bees ignore zeds. Wasps are very aggressive, they wouldn't stop attacking something just because they can't kill it. And there is nothing wrong with player seeing his enemies fighting each other.

**Comment by John-Candlebury** [comment]
Yeah agree core overload. Wasps and bees are very agressive when it comes to self defense.

And I think that seeing the occasional wasp/zombie fight break out  gives a bit more flavour to the game, don't know why it has to go.

**Comment by Coolthulhu** [comment]
The problem is, wasps always lose it at the end.
They wouldn't establish those hives in the middle of the city.

So either the hostility or the city hives should go away.

With bees, I could just special case scarred zeds.

**Comment by kevingranade** [comment]
Either that or make the wasps win, what if wasp poison rendered zombies unrezzable?
Then you could have a map filter that kills and deactivates nearby zombies, leaving corpses scattered around, and the wasps would win skirmishes on the edge, but then wouldn't be inclined to expand further (unless we added that specifically, maybe they'd colonize a city over time).  Leading zombies into the area would then be a tactic, but playing with wasps is quite dangerous.

**Comment by Coolthulhu** [comment]
> make the wasps win, what if wasp poison rendered zombies unrezzable?

I like this idea. The poison could even be extractable.

How about this:
Wasps could produce their own zlaves, a bit like https://en.wikipedia.org/wiki/Emerald_cockroach_wasp except with zombies.  
A zombie with enough wasp poison would still rez, but this time in wasp faction (ie. hostile to other zombies). After a while it would die and spill a bunch of wasp larvae. This would explain why wasps settle in cities rather than in safer places.

As for bees, I'd make scarred zombies neutral to bees (and bees neutral to scarred zombies) because those spawn in hives. Other zombies could gain a "rez as scarred" tag if filled with enough bee poison on death.

**Comment by Malkeus** [comment]
This is a very cool idea, interaction between the factions will always get
a thumbs up from me. Some wasps make a living depositing their eggs in
unsuspecting hosts to give the larva a fresh meal when they hatch. This
could even be a disease for the survivor; remove the eggs and deal with the
pain or suffer something even worse than fungal disease.

**Comment by Rivet-the-Zombie** [comment]
>This could even be a disease for the survivor; remove the eggs and deal with the pain or suffer something even worse than fungal disease.

Like dermatiks?

**Comment by Malkeus** [comment]
Tbh, I've never encountered a dermatik at close range. The horror stories
from the forums always made me run the other way or do unto them before
they did unto me.

**Comment by kevingranade** [comment]
Yes, zombie zlaves sounds like a great idea.
Do say the word and we can merge this as is though, them ignoring each other is ok for the moment.

**Comment by Coolthulhu** [comment]
Reverted the bees and wasps part for now because of the discussion above. Left in spiders, roaches and other minor arthropods.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/zombie-insect-interaction-ideas/25037/1

**Pull request merged**
