### PR TITLE
Finish making consume take time

### LINKED ISSUE #36972: Make eating take time
**Is your feature request related to a problem? Please describe.**  
One of the issues remaining with the current food system is that food instantly enters your stomach, making it possible to overeat because you're still in the food menu stuffing yourself before you get feedback. It also removes the need to hide and find a safe place to eat, which is too bad because that's a staple of running from hordes of zombies.

**Describe the solution you'd like**  
Make eating take time, based on the volume of the food and whether it is solid or liquid.

Although it's possible to imagine a system where you choose to eat slowly to ration your food, quickly because you're in a hurry, or at a normal speed, we could probably get by with just the normal speed option:
- For liquids, I suggest 15 mL (1 tablespoon) per second.
- For solids, I suggest 5 mL (1 teaspoon) per second.

With those numbers you'd drink a can of soda in about 20 seconds, or eat a hamburger in about two minutes.

The food menu should display the time to eat all the food you've selected.

There should also be hooks to allow mutations to adjust eating speeds by a multiplier, ideally possibly allowing an eat speed multiplier for specific nutrients (you now eat plants faster / meats slower), for just liquids, or for just solids, or for all food.

**Describe alternatives you've considered**  
As stated, it would probably be acceptable to do it with just one eating speed, but it would be reasonable too to have +/- adjust eating speed between "normal", "eat quickly", and "ration food". I'd double eating time for rationing and half it for eating quickly. If you really want to get silly you could add a small chance to choke if you're eating too quickly.

**Additional context**  
In a first pass it would be acceptable to just have the player wait two minutes and then get their whole hamburger added to stomach contents. In the future, it would be ideal to borrow the %crafting mechanic, and track how much of a food item is eaten with each bite. (`Hamburger: 40% eaten`)

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Features "Finish making consume take time"

#### Purpose of change
Fixes #36972
Add rest of features to consumption taking time.

#### Describe the solution
Mutations can now alter eat/drink speeds and I moved the existing mutation based eat time logic into json.  The consume menu now shows consume time.  Drug's and medicine have had their consume times broken out.  To fix auto eat/drink I made them simply instant.  

#### Describe alternatives you've considered
The linked PR suggested showing percentages of completion but someone else is doing a generic solution for that so I left it undone.  The drug/medicine times are what sounded good to me and I welcome suggestions to tweak them.  Making auto eat/drink take time as well but the prospect of pausing the current activity to start another and then resume didn't seem worth it considering consume times are tiny compared to the crafting time.

### CODE REVIEW

**Comment by rsulli55** [comment]
Because #40126 was recently merged, if you want this activity to be resumable you will need to add an override to`activity_actor::can_resume_with_internal` .

**Comment by Ramza13** [comment]
> 
> 
> Because #40126 was recently merged, if you want this activity to be resumable you will need to add an override to`activity_actor::can_resume_with_internal` .

That's probably a good idea but after my previous git misadventures I'm going to wait until this is merged first.

**Comment by rsulli55** [comment]
> > Because #40126 was recently merged, if you want this activity to be resumable you will need to add an override to`activity_actor::can_resume_with_internal` .
> 
> That's probably a good idea but after my previous git misadventures I'm going to wait until this is merged first.

Sounds good, being newish to git myself I definitely understand that.

**Comment by kevingranade** [comment]
I don't know how, but this breaks some crafting tests.

**Comment by anothersimulacrum** [comment]
Could you change that `Finishes` to `Fixes` so that issue is automatically closed when this PR is merged?

**Comment by Ramza13** [comment]
Ok tests should be fixed and I added in the can_resume_with_internal override

**Pull request merged**
