### PR TITLE
Conditionally prompt for follower control on death

### PR DESCRIPTION
**Pull request by perryprog**
#### Summary
None

#### Purpose of change
There's no reason for the player to be given a prompt on if they want to
take control of a follower that's nonexistent; so this fixes that.

#### Describe the solution
This adds an and condition to the EOC trigger for if the player has allies.

#### Describe alternatives you've considered
None.

#### Testing
Died with and without allies and confirmed I had no invisible friends.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
This effectively reverts https://github.com/CleverRaven/Cataclysm-DDA/pull/56220, and I think that is wrong to do so.

**Comment by dseguin** [comment]
> This effectively reverts https://github.com/CleverRaven/Cataclysm-DDA/pull/56220, and I think that is wrong to do so.

Oh I didn't even notice! I think the previous behaviour could be preserved by using a new condition like `npc_allies_global`

<details>
<summary>Patch (untested):</summary>

```diff
diff --git a/data/json/effect_on_condition.json b/data/json/effect_on_condition.json
index 440c0c740d..7ecc9dc48f 100644
--- a/data/json/effect_on_condition.json
+++ b/data/json/effect_on_condition.json
@@ -358,7 +358,7 @@
     "id": "EOC_DEATH_SWITCH",
     "type": "effect_on_condition",
     "eoc_type": "AVATAR_DEATH",
-    "condition": { "and": [ { "npc_allies": 1 }, { "u_query": "You have died. Continue as one of your followers?", "default": false } ] },
+    "condition": { "and": [ { "npc_allies_global": 1 }, { "u_query": "You have died. Continue as one of your followers?", "default": false } ] },
     "effect": [ "take_control_menu" ]
   },
   {
diff --git a/src/condition.cpp b/src/condition.cpp
index 0fdbc50ae2..74111035c1 100644
--- a/src/condition.cpp
+++ b/src/condition.cpp
@@ -729,6 +729,17 @@ void conditional_t<T>::set_npc_allies( const JsonObject &jo )
     };
 }
 
+template<class T>
+void conditional_t<T>::set_npc_allies_global( const JsonObject &jo )
+{
+    int_or_var iov = get_int_or_var( jo, "npc_allies_global" );
+    condition = [iov]( const T & d ) {
+        return g->get_npcs_if( []( const npc &n ) {
+            return n.get_faction()->id == get_avatar().get_faction()->id;
+        } ).size() >= static_cast<size_t>( iov.evaluate( d.actor( iov.is_npc() ) ) );
+    };
+}
+
 template<class T>
 void conditional_t<T>::set_u_has_cash( const JsonObject &jo )
 {
@@ -1985,6 +1996,8 @@ conditional_t<T>::conditional_t( const JsonObject &jo )
         set_npc_role_nearby( jo );
     } else if( jo.has_int( "npc_allies" ) || jo.has_object( "npc_allies" ) ) {
         set_npc_allies( jo );
+    } else if( jo.has_int( "npc_allies_global" ) || jo.has_object( "npc_allies_global" ) ) {
+        set_npc_allies_global( jo );
     } else if( jo.get_bool( "npc_service", false ) ) {
         set_npc_available( true );
     } else if( jo.get_bool( "u_service", false ) ) {
diff --git a/src/condition.h b/src/condition.h
index 0afc5c3913..8f5278ca86 100644
--- a/src/condition.h
+++ b/src/condition.h
@@ -36,7 +36,8 @@ const std::unordered_set<std::string> complex_conds = { {
         "u_is_wearing", "npc_is_wearing", "u_has_item", "npc_has_item", "u_has_move_mode", "npc_has_move_mode",
         "u_has_items", "npc_has_items", "u_has_item_category", "npc_has_item_category",
         "u_has_bionics", "npc_has_bionics", "u_has_effect", "npc_has_effect", "u_need", "npc_need",
-        "u_at_om_location", "u_near_om_location", "npc_at_om_location", "npc_near_om_location", "npc_role_nearby", "npc_allies", "npc_service",
+        "u_at_om_location", "u_near_om_location", "npc_at_om_location", "npc_near_om_location",
+        "npc_role_nearby", "npc_allies", "npc_allies_global", "npc_service",
         "u_has_cash", "u_are_owed", "u_query", "npc_query", "u_has_item_with_flag", "npc_has_item_with_flag",
         "npc_aim_rule", "npc_engagement_rule", "npc_rule", "npc_override", "u_has_hp", "npc_has_hp",
         "npc_cbm_reserve_rule", "npc_cbm_recharge_rule", "u_has_faction_trust",
@@ -129,6 +130,7 @@ struct conditional_t {
         void set_has_move_mode( const JsonObject &jo, const std::string &member, bool is_npc = false );
         void set_npc_role_nearby( const JsonObject &jo );
         void set_npc_allies( const JsonObject &jo );
+        void set_npc_allies_global( const JsonObject &jo );
         void set_u_has_cash( const JsonObject &jo );
         void set_u_are_owed( const JsonObject &jo );
         void set_npc_aim_rule( const JsonObject &jo, bool is_npc );
```

</details>

**Comment by perryprog** [comment]
Ack! I didn't see that PR—or realize the reality bubble issue—at all. Thanks for spotting the issue, @anothersimulacrum.

@dseguin, I don't see a patch in your comment, but I take it you're looking into fixing this?

**Comment by dseguin** [comment]
> I don't see a patch in your comment, but I take it you're looking into fixing this?

It's in a collapsible element, you can click on the `Patch (untested):` text to expand it. I wasn't planning on doing anything with it, I just added a snippet with a possible fix.

**Comment by perryprog** [comment]
Oh, weird, the little arrow dropdown isn't rendering for me like it normally does. I'll take it a look at it in a bit after I eat and see if I can get a fix written.

**Comment by perryprog** [comment]
> > This effectively reverts #56220, and I think that is wrong to do so.
> 
> Oh I didn't even notice! I think the previous behaviour could be preserved by using a new condition like `npc_allies_global`
> 
> Patch (untested):

Unfortunately, `get_npcs_if` still only iterates over everything in the reality bubble (and is also what `allies().size()` used internally), so this still doesn't quite work.

Unless you have another idea, do you want me to open a PR that reverts this one until something is figured out?

**Comment by dseguin** [comment]
I see, then you'd probably need to use `overmap::get_npcs` to get all NPCs on that overmap. If you're not comfortable implementing that, you could revert the PR and keep the prompt for now.

**Pull request merged**
