### PR TITLE
Expanded NPC conditions; spell levels, loaded mods & proficiencies

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Infrastructure "Expanded NPC conditions; spell levels, loaded mods & proficiencies"

#### Purpose of change
Adds a couple integers that can be read and written to by dialogue arithmetic

#### Describe the solution
Implement read
- [X] highest spell level
- [X] highest spell level in school
- [X] level of a given spell
- [X] exp of a given spell
- [x] if a given mod is loaded or not
- [x] proficiency level of a given proficiency

Implement write
- [x] level of a given spell
- [x] exp of a spell
- [x] proficiency level of a given proficiency

Test
- [x] highest spell level (read)
- [x] highest spell level in school (read)
- [x] level of a given spell (read)
- [x] level of a given spell (write)
  - [x] forgetting a spell you don't know
  - [x] forgetting a spell you know
  - [x] learning a spell you don't know
  - [ ] learning a spell you know
- [x] exp of a given spell (read)
- [x] exp of a given spell (write)
- [x] if a mod is loaded or not (read)
- [x] proficiency level of a given proficiency (read)
  - [x] Int
  - [x] time_spent
  - [x] percent
  - [x] permille
  - [x] total_time_required
  - [x] time_left
- [x] proficiency level of a given proficiency (write)

[x] Documentation

#### Additional context
Kind of surprised there doesn't seem to be an existing way for dialogues to interact with proficiencies.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I'm not sure this is the right way to interact with other mods, I don't think mod load order should be exposed like this.

**Comment by Light-Wave** [comment]
> I'm not sure this is the right way to interact with other mods, I don't think mod load order should be exposed like this.

That's a fair question to ask. The main reason I want this is because TropiCataclysm causes problems if it is loaded after Innawood due to TropiCataclysm overwrites road data, and I want a way to warn the player that their load order is wrong. So in that case I would be checking if TropiCataclysm's load order is greater than that of Innawood.
I also want ways for a EoC to detect if another mod is loaded in general.

**Comment by anothersimulacrum** [comment]
Load order problems should be handled in modinfo, not EoCs. Similarly, I think most mod interaction should be done through the conditional loading of data (read: patch mods) as is described in an issue I'm too lazy to find right now.

**Comment by Light-Wave** [comment]
#60351

**Comment by Light-Wave** [comment]
> Load order problems should be handled in modinfo, not EoCs. Similarly, I think most mod interaction should be done through the conditional loading of data

Adding "load_before" and "load_after fields to modinfo would probably be a better way to deal with the Innawood / TropiCata load order problem, yes. With that implemented, knowing the exact load order of a mod should no longer be needed. Although knowing if it is loaded at all or not would still be very useful.

As for conditional mod loading, it sounded like that got vetoed by a senior developer in the previously liked issue, so that doesn't seem to be happening soon.

So my current take is something like this: If we get a way for a modinfo file to say "If I am added to a world, and you also want to add any of these mods to the world, make sure to load them before me, and load these mods after me. But you don't _have_ to add them.", and if we also get a generic condition that checks if a given mod is loaded or not, then we don't need to know the load order of any mod. Perhaps that would be a better solution.
However, I'm not sure I can implement the load order thingy on my own, and I want to at the very least be able to give the user a warning if they messed up the load order completely. So adding the changes in this PR seems to me to be an improvement, but perhaps a step in the wrong direction? I don't know any more. I guess I'll ask for more feedback on the discord.

**Comment by anothersimulacrum** [comment]
I don't think ZS is opposed to a feature which would automatically load mods if two other mods requested it be loaded when the other mod is loaded.

**Comment by Light-Wave** [comment]
This is now ready for review.

**Comment by Maleclypse** [comment]
I wish I felt capable of reviewing this.

**Review by dseguin — APPROVED** [review]
LGTM, other than exposing mod load order to EOCs, which I can't comment on

**Comment by Light-Wave** [comment]
> LGTM, other than exposing mod load order to EOCs, which I can't comment on

Sorry for the confusion, I hid the load order again and instead went with only checking if a mod is loaded or not.

**Pull request merged**
