### PR TITLE
Allow advanced 'm'ove query text to be empty

### LINKED ISSUE #20234: Advanced inventory 'm'ove autofills dialogue
Using 'm' for moving part of a stack in the advanced inventory now automatically fills the dialogue box with the full size of the stack, when it used to start empty. Means you now have to backspace every time you use it. If you wanted to move the whole stack you can just use upper-case 'M' instead.

possibly related: when searching in the wish-for-item menu the cursor now always starts at the beginning, even if the box already has something in it from a previous search, when it used to start at the end of any text. Means you now have to move the cursor back to the right or END when spawning different types of items.

both present in build 6217, but not 6208 (latest previous successful build). Possibly from #20033?

### PR DESCRIPTION
**Pull request by kolsurma**
fix #20234 

note: If enter is pressed with no input in the text box 0 is returned

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Is that the only usage of the box? If not, is there a usage that works better with pre-typed text?
If there is one, it could be useful to add an overload that accepts a default value.

Most uses are probably fine with empty box, though.

**Comment by kolsurma** [comment]
As far as I can tell this is the only one that uses a type `long` reference. 

I'd personally prefer most input boxes be empty by default.

**Comment by Coolthulhu** [comment]
> As far as I can tell this is the only one that uses a type long reference.

They can't differ just by type. If `long` boxes are empty, then `int` ones need to be empty too.

**Comment by kevingranade** [comment]
I agree with Coolthulu, even if this fixes the immediate issue, it breaks the ui of string_popup.  It needs a setter to select the desired behavior.  Thanks for finding it though, that's way more than half the work here.

Basically this: https://github.com/kolsurma/Cataclysm-DDA/commit/250098275ad626a8e6d8929824052c1d613ef6c6 was mistaken about the universality of setting the text of the widget to the stringified original value.

**Comment by kevingranade** [comment]
Actually the API is fine, that one place just needs to use the less generic version of the method, and probably the debug menu too...

**Comment by kolsurma** [comment]
I'm unsure of what you mean by the less generic version.

One simple way to fix edit, from what I can see, is to set a bool if it should have a default value.

**Comment by kevingranade** [comment]
I have a fix ready, just compiling and testing, you'll see what I mean.

**Comment by kolsurma** [comment]
I'm all for learning new things

**Comment by kevingranade** [comment]
It's nothing fancy, just found a different place to stick the fix :D

**Comment by kolsurma** [comment]
I'm just going to throw what I got up here, went ahead and did the boolean thing, it defaults to use whatever value is in ... &value, but can be turned off to start with a blank prompt. 

Since this renders my previous commit pointless, should I add this one as a fixup? The previous message still applies.

**Comment by kevingranade** [comment]
#20507 is an alternative fix, you make the call @Coolthulhu

**Comment by Coolthulhu** [comment]
I'd prefer the fix here, because in the end, it simply does `atol` on the result, like the revert but "cleaner" (wrapped in the class).

**Comment by kevingranade** [comment]
Just seems like a lot of overhead in the class to handle a single case, you generally don't want to do this kind of thing unless a lot of things are using it :/

**Comment by Coolthulhu** [comment]
We could invert it then.

Are there cases that need pre-typed text?

**Comment by kolsurma** [comment]
>Are there cases that need pre-typed text?
The issue I see is the string overload is used all over to autofill filtered items if it's already been input once.

Not a terribly big issue with strings, since they can be empty. When integers are used as a 'default' value they will either be whatever value the reference is or 0.

**Comment by Coolthulhu** [comment]
For now I merged the other fix. But if you could locate the cases where it needs to be filled and empty, that would be a better solution than either the revert was and than making it a special case.

**Comment by kolsurma** [comment]
There are 8 calls to `string_input_popup::edit( std::string &value )`. All calls except one are filter based, the one off is in `options_manager::cOpt::setNext()` when setting the default characters name. They all work the same, display empty unless there is prior input.

There is one call to `string_input_popup::edit( long &value )` from the OP.

There are two calls to `string_input_popup::edit( int &value )`. A lambda function in void `minesweeper_game::new_level` and `debug_menu::wishitem`. I have no idea about the minesweeper game. wishitem always starts with 1, then changes to the last entered amount.

**Comment by kevingranade** [comment]
I don't follow, ::edit(val) was specifically added for cases where there's an existing value and you want to update it, the other instances query for a new value, so just use ::query().  Whether it casts the result or whatever is a separate issue, we can just have different flavors of query() (the caller knows whether they want a string or an int obviously).

**Pull request closed without merging**
