### PR TITLE
Earthbag/sandbag disassembly recipes

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: None```

#### Purpose of change
Ability to empty the bags without building a wall out of them then bashing it.

#### Describe the solution
Same recipes as crafting, except shovel is not needed to empty the bags.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
It might be easier just to add `"reversible": true` field to the crafting recipes.

**Comment by RarkGrames** [comment]
> 
> 
> It might be easier just to add `"reversible": true` field to the crafting recipes.

Yeah, I've tried that first, but then you need a shovel to empty the bags.

**Comment by Night-Pryanik** [comment]
> you need a shovel to empty the bags.

We could add a special case in the crafting code for this kind of recipes, but... I think it's not worth the hassle.

**Comment by RarkGrames** [comment]
Yes, there is a huge amount of disassembly recipes anyway, so a couple more doesn't really matter.

**Pull request merged**
