### PR TITLE
Changed "What are you" and "Did you see that" to questions

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
Replaced "What are you!" and "Did you see that %1$s!" strings in player.cpp to "What are you?" and "Did you see that %1$s?" respectively, changing exclamation marks to question marks.

#### Purpose of change
Fixing a potential typo.

#### Describe the solution
Changed exclamation marks to questions.

#### Describe alternatives you've considered
I think "What are you" should be a question, not an exclamation.

#### Additional context
I think "What are you" and "Did you see that %1$s" should be questions, not an exclamations. Found it while translating the game to Polish on Transifex.

### CODE REVIEW

**Comment by Regilith** [comment]
I'm against this change, grammatically they both work, but the ! gives it more flavor

**Comment by kevingranade** [comment]
‽

**Comment by Faalagorn** [comment]
I made them end with question mark in Polish translation, but feel free to close this PR if it doesn't fit, as different languages can have different grammar rules indeed.

**Comment by Kelenius** [comment]
!?

**Comment by Faalagorn** [comment]
@kevingranade and @Kelenius I was actually thinking about it, but didn't search the code what was used in other files in those situations :thinking:

**Comment by kevingranade** [comment]
‽ is not a serious suggestion, but !? would be ideal I think.

**Pull request merged**
