### PR TITLE
Deduplicate item name in info window

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

```SUMMARY: Interface "Remove duplicate item name in item info panel"```

#### Purpose of change

Many items (clothing, stuff in containers, fresh food, tools marked as favorite) display a duplicate name in the item description panel. The duplicate item name adds no information (since the first line always includes the text of the second) and it takes up a potentially quite valuable line of screen space.

#### Describe the solution

Slightly changes the conditional in `src/output.cpp` in the `draw_item_info` function, so that `type_name` is only output if `tname` does not already include it. Normally, `tname` includes `type_name` anyway, thanks to this bit inside the `tname` function:

https://github.com/CleverRaven/Cataclysm-DDA/blob/6bb5b9dc8151dc55e844eee18f557ad63c7b8793/src/item.cpp#L3883-L3884

In the few cases where it does not, both lines will be shown - such as when an item has a custom label.

#### Describe alternatives you've considered

Considered leaving as-is, and also considered fixing as part of #38030 , but seems worth doing on its own.

#### Testing

Checked descriptions of various items and saw the duplicate line removed. Checked items that had no duplicate before (guns, regular tools and weapons) and saw they still have the name intact.

#### Additional context

Any item that previously duplicated the exact same text in both lines, now has the duplicate second line removed. This includes:
- Wearable items (with/without health bar)
- Food with (fresh), (hot), (rotten) modifier
- Favorite items with `*` next to them

image

Since `type_name` is responsible for adding the descriptive modifiers (when a food has human or mutant meat as an ingredient, for example), I tested a few of those as well:

image

Any item whose first line does not include the exact text of the second line, has both lines displayed. This includes items that have been re-labeled using a marker or knife. The display of such items remains unchanged:

image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Could you please inscribe some text (to give it a custom name) on some item and check if everything is working as it should?

**Comment by wapcaplet** [comment]
> Could you please inscribe some text (to give it a custom name) on some item and check if everything is working as it should?

@Night-Pryanik Ah, this is an edge case I didn't think about. Sure enough, in that case the original item name would no longer be shown:

image

With my change, there is only "knifey", which is no good. I find a way to merge in the original name in this case.

**Comment by wapcaplet** [comment]
My solution for items with custom labels is to output the `type_name` line only if the `item_name` does not already include the same text.

Now, if you write a custom label on an item, the original item name is shown after it, *unless* your custom label also includes the original item name, for example:

image

**Comment by kevingranade** [comment]
I just want to say, this is an elegant and well thought out change, thanks.

**Pull request merged**
