### PR TITLE
Football Field

### PR DESCRIPTION
**Pull request by RogueYun**
I put this project on hold for a long time because I was struggling to figure out how to use github. I'm still struggling with some things but less so thanks to remyroy and drbig.

_Bugs_ There appears to be some sort of lag that is introduced when running through the football field.  I am not sure why. I am making this pull request namely because I need help resolving this. Any help on fixing this would be much appreciated.

Things to be added later:
-Zombie Brutes
-Painted white lines on grass (instead of linoleum_white tiles)

Thanks in advance for any feedback and I'm open to suggestions!

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>Painted white lines on grass (instead of linoleum_white tiles)

This would need to happen before this PR can be merged; ````linoleum_white```` has a roof.

**Comment by chaosvolt** [comment]
Hmm. Half-tempted to suggest implementing paint as a field. Now if I could remember what those rolling turf-painting push...things are called. >.<

In any case, interesting idea. Though I do wonder if it's up to scale. Tiles are usually somewhat vaguely-defined in terms of how much space they represent, but it's more or less officially a square meter. I think.

**Comment by vickio** [comment]
Looks good! I think the lag is due to complex lighting calculations since linoleum tiles are flagged `indoors`. Switching it to a tile without that flag fixed it for me. You should add `t_painted_grass` to `terrain.json`.

Here are some ideas:

- How about a little food shack with a fridge and open windows on one side
- Maybe put a fence around the whole thing?
- This would be cool standalone, and also as a variation of the school with the field out back
- I understand why the column is there, but it does seem weird that you can't see over/around it. Maybe use `t_little_column` instead?

**Comment by RogueYun** [comment]
Thank you all for the recommendations. I did my best to clean things up and make things more balanced. Any other thoughts or comments?

**Comment by illi-kun** [comment]
I really like this PR.

@RogueYun please remove [WIP] & [CR] tags if you implemented all required changes.

**Comment by Rivet-the-Zombie** [comment]
Yeah, I like this one!

**Comment by RogueYun** [comment]
Okie doke. Since I can't think of what else to add or change, I will leave it to be assimilated.

**Pull request merged**
