### PR TITLE
Add sealed animal stomach as water container for early survival

### PR DESCRIPTION
**Pull request by tivec**
A character starting out in the wild has a fairly low chance of finding any sort of containers except for searching bushes. Even so, the chances are pretty slim.

This gives the hunter style character the ability to butcher two sizes of stomachs from small and above woodland creatures (right now, butcherable creatures that are not plants or tainted). It also comes with the recipe to craft two sealed stomachs using string, water, a tool with cutting, a tool with boiling and of course the stomach itself.

### CODE REVIEW

**Comment by Zireael07** [comment]
Nice idea.

**Comment by narc0tiq** [comment]
Marked WIP because it's currently not letting you fill sealed stomachs from a water source.

**Comment by dustinlacewell** [comment]
Super excited for this

**Comment by tivec** [comment]
As of 373efa3, the sealed stomachs can properly be filled from water sources.

**Comment by Rivet-the-Zombie** [comment]
Simply cutting the stomach out of a creature and boiling it will **not** produce a permanent waterskin. Unless you actually go through the trouble of preserving it through tanning, it will decay in a matter of days.

This is a really cool idea for a PR, but it needs some more steps.

**Comment by dustinlacewell** [comment]
The problem with involving tanning in the process of creating the container is that tanning involves crafting that assumes the capability of working with water so it is a chicken or egg problem. I do like the idea of the stomach waterskins lasting say just under a week or something. Can Cata support that?

**Comment by graysage1** [comment]
I think this idea is exciting.  I decided to try to gather some information.  So far I have found this:

[info on primitive waterskins](http://www.primitivearcher.com/smf/index.php/topic,30765.msg407813.html?PHPSESSID=ia7drqpfqs9bo535cm60ioo9d1#msg407813)

[a waterproofed basket is apparently possible](http://blog.survivalfrog.com/make-primitive-survival-tools/):

>The waterproof glue is pitch glue and is by far much more commonly used in the wilderness. You only need to melt hardened pine pitch in a container and add an amount of charred wood as a binder. This black glue is very sticky and will seal up many things. You can even use it to completely cover a twig basket to make it hold water.

[cotton clothing can be used to soak up the dew off the grass and wrung](http://www.survivalistboards.com/showthread.php?t=150962):

>For some water, though not too much, soak a piece of clothing in water. If you walk through some tall grass with morning dew on it, it will soak the water up, and you can wring it out later. Of course, thats what I would do if I had absolutely nothing else. 

From the same topic above, gourd plants can be used, but apparently they don't grow in every area:

>Gourds if they grow in your area.

More ideas:

>Around here, birch bark is plentiful. I would probably make something out of that, sealed with pine sap.

[Here's what a birch bark container looks like](http://wildwoodsurvival.com/survival/containers/birchbarkcontainers.html).

Also, birch tree sap is drinkable and it eliminates thirst.  Birch tree sap is slightly sugary, so don't pour it into a car radiator, but other than that, it's a good replacement for water in a survival situation.  There are some other plants that also yield water.

**Comment by Coolthulhu** [comment]
What about adding at least one food recipe that uses the stomach? Even something as simple as "tripe soup". Or at least the ability to cut the stomach up into a piece of raw meat. Otherwise most of those will simply go to waste.

Also, getting the stomach of the same size from smaller creature should probably be harder. You could have the skill roll to harvest a stomach from a small creature be harder than to harvest it from a medium one.

Later on it would be cool if you added a check for insect type - ants and flies don't have the same kinds of stomachs that dogs or moose have.

**Comment by Zireael07** [comment]
@dustinlacewell: Cata already has pelts rotting, so I don't see why the stomachs couldn't be made to rot, too.

**Comment by tivec** [comment]
It is not, as far as I can tell, possible to make non-comestibles rot. The "spoils_in" tag is not available for any other types of items. I do not know the implications of moving the tag up one level to the base item, but it seems likely it would cause lots of issues.

I have thrown about the idea of having durability and hook that through an iuse, to limit the amount of sips you get out of the bladder. Unfortunately, that won't stop people from crafting a whole bunch of these sealed bladders for storage.

I have trawled the intertubes to find out what the old procedure of making water skins, but the most information I have gotten is that the cured and tanned leather used in waterskins was usually lined with some form of bladder from a creature. It says little on what the procedure is for the bladder, unfortunately. I was under the impression that you washed and scraped it before hanging it to dry. This would produce a bladder that, while not 100% waterproof, was good enough to hold some liquids for a while.

Do we want to go 100% realism and force people to go through the chicken/egg procedure in fully tanning their hides to make the waterskin, or do we want to give some leeway?

@coolthulhu: I'm going to look into your suggestions here. I went for a more middle of the line for what animals would produce stomachs. Tripe soup and perhaps even haggis can be added - but that recipe might be form a book, I don't know. As for rotting, the stomachs have a shorter rotting timer than chunks of meat so leaving them around won't clutter the fields too much

**Comment by Coolthulhu** [comment]
> Tripe soup and perhaps even haggis can be added - but that recipe might be form a book, I don't know.

At least one recipe for stomach food should be autolearned at low level. Just throwing the organ in water and boiling it to kill the parasites, so that it doesn't have the RAW_MEAT iuse.

**Comment by Rivet-the-Zombie** [comment]
If we're going to go so far as differentiating the specific insides of butchered critters, perhaps it behooves us to add more types of assorted guts to butchered critters, so we could have some offal-centric recipes for desperate survivors.

Previously, I'd always figured that the nonspecific 'meat' you get from cutting stuff up included edible organs as well.

**Comment by tivec** [comment]
Yeah, that's simple enough. "Boiled stomach" could be a new delicacy! Not a lot of nutrition, and definitely not very enjoyable. 

@Zireael07: The pelts rot, so do the stomachs - just not the sealed stomachs.

**Comment by Coolthulhu** [comment]
A bit beyond the scope of this PR, but having a separate "muscle meat" item used in tasty recipes and lots of "organ meats" used in nutritious un-tasty ones would make sense. IRL organ meats are generally far richer in pretty much every single nutrient except protein. Muscle meat is the carnivore's white flour.

**Comment by Rivet-the-Zombie** [comment]
>Do we want to go 100% realism and force people to go through the chicken/egg procedure in fully tanning their hides to make the waterskin, or do we want to give some leeway?

At least make the recipes include a few pine boughs for pitch, or something of the sort.

**Comment by tivec** [comment]
@Rivet-the-Zombie It is a good compromise to add 2 pine boughs for the small sealed stomach, and 4 or 6 for the large.

In response to splitting up the different meats, I can do a bit of work with that, adding a few more generic guts, but then we really need to set that up in the species.

Perhaps it would be more right to move the functionality where we specify what a creature can be butchered to in the jsons for that particular monster/animal? Right now this is part of the activity handler for butchering. The skill rolls and all can still be there, but the butcher weights could be added in the json.. Thoughts on that?

**Comment by BevapDin** [comment]
> It is not, as far as I can tell, possible to make non-comestibles rot. The "spoils_in" tag is not available for any other types of items. I do not know the implications of moving the tag up one level to the base item, but it seems likely it would cause lots of issues.

As most item types won't use it, it should not be part of the base `itype` class. It can however be moved into an item slot (like book, container, gun) to be available for all item types. Raw hide might be another candidate for this spoiling non-comestible thing.

There are some serious shortcomings in this scenario:
- rotten items are as usable as unrotten ones.
- really old rotten items are only remove from the map (when it's loaded into the reality bubble!), not from the player inventory, nor from the cargo parts of vehicles.

I suppose the player would keep the container with its content close all the time and therefor it would never actually disappear.

**Comment by tivec** [comment]
So we need to update the rotting functionality to take rotting items from the player inventory and vehicle cargo parts, as well as from the ground around the player. Perhaps that could be added to the new field decay functions that were added - they work with cleaning up blood and gore etc.

I do think that is outside the scope of this PR. I'll add a recipe for boiled stomach, but I'm probably not going to branch out in too many other features.

**Comment by Rivet-the-Zombie** [comment]
Of course you realize, this means haggis.

**Pull request merged**
