### PR TITLE
Turn toolbox into a truly versatile tool

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Added ability to saw wood, metal and barrel of a gun, remove mods and pull nails as toolbox contains wood saw, hacksaw, screwdriver set and hammer.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That knife action on it is a mistake. Toolbox takes 25 duct tape per use of any of its functions. It can't have both repair action and any "free" action until that changes.

**Comment by Night-Pryanik** [comment]
Then I should remove knife action, as well as all my additions?

**Comment by Coolthulhu** [comment]
Yes. Or the repair action and the repair kit from the recipe.

**Comment by Coolthulhu** [comment]
Misclick

**Comment by Night-Pryanik** [comment]
Done.

**Comment by Night-Pryanik** [comment]
Hmm, we probably also need some "stout metal box" (as in description) in ingredients.

**Comment by Coolthulhu** [comment]
It needs to lose the ammo, not just gain functions. Currently it consumes (and requires) 25 charges of duct tape per use.

**Comment by Coolthulhu** [comment]
Now that it no longer includes basic repair kit, it could lose 1-2 units of volume.

**Pull request merged**
