### PR TITLE
Radio-modded explosives on RC car update

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Explosives with added radio activation mod now can be put into a RC.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs some weight and volume check so that you can't strap a giant keg of explosives to the RC tiny car.

**Comment by Night-Pryanik** [comment]
Oh, I think that's beyond my coding abilities. I'll try nevertheless, but don't promise anything.

**Comment by Night-Pryanik** [comment]
I think I did it. At least when I tested it, it worked.
As RC car has volume 4 and weight about 1 kilogram, I made it so only explosives not bigger than volume 5 and 2 kilograms can be put on RC car.

**Comment by Coolthulhu** [comment]
Not caused by this PR, but radio dynamite is weirdly light. Until it is activated, then it becomes heavy.

**Comment by Night-Pryanik** [comment]
Yeah, I noticed that too.

**Comment by Coolthulhu** [comment]
Non-minor bugs (those need to be fixed before merging):
* Remote bombs go through their timers when attached to RC car and then activated. Check out how `"BOMB"` items are handled in `trigger_radio_item` in map.cpp - their charges are zeroed only if they are standalone items, but this should also happen for those in RADIO_CONTAINER
* RC car can be armed with radio modable items, even if they aren't moded yet

Minor issues related to (not necessarily caused by) the PR:
* Radio-activated bombs keep their old messages like "you pull the pin on x"
* Some car bombs - tear gas, for example - shouldn't destroy the RC car
* Screwdriver iuse doesn't list radio bombs for removal, but still accepts them if selected with inventory letter

**Comment by Night-Pryanik** [comment]
>RC car can be armed with radio modable items, even if they aren't moded yet

What radio modable items behave like that?

**Comment by Coolthulhu** [comment]
> What radio modable items behave like that?

Worked with incendiary grenade.
Hmm... if it isn't obvious, it may be related to the fact that I first installed a mod on the 'nade, then removed it.

**Comment by Night-Pryanik** [comment]
I tried to arm RC car with a bunch of explosives. The car didn't allowed to arm itself with these explosives if they aren't moded **yet**.

**Comment by Coolthulhu** [comment]
I see it now: you added the RADIOCARITEM tag in the mod, but forgot to remove it when removing the mod.

**Comment by Night-Pryanik** [comment]
>I see it now: you added the RADIOCARITEM tag in the mod, but forgot to remove it when removing the mod.

Well, that's an easy part, if I understand it correctly.

**Comment by Night-Pryanik** [comment]
The hard part is this:
>Remote bombs go through their timers when attached to RC car and then activated. Check out how "BOMB" items are handled in trigger_radio_item in map.cpp - their charges are zeroed only if they are standalone items, but this should also happen for those in RADIO_CONTAINER

It seems that I just don't understand what the problem is.

**Comment by Coolthulhu** [comment]
> It seems that I just don't understand what the problem is.

* Spawn RC car, 2 grenades, 2 radio mods
* Mod both grenades to activate on red
* Stick one on the RC car and put the car on the ground
* Put one on the ground, preferably few tiles away from the car
* Activate the red signal
* One grenade will detonate immediately, the other one will take 5 turns to detonate

You need to change the `trigger_radio_item` to proc the radio items twice when attached to the car, just like they proc twice when lying on the ground.

**Comment by Night-Pryanik** [comment]
Goddammit, now I can't even detonate armed RC car with radio control!
Could you please confirm that activating the signal will detonate armed RC car?

**Comment by Coolthulhu** [comment]
> Could you please confirm that activating the signal will detonate inactive armed RC car?

It should, if the car is on the map (not sure about inventory) and has a bomb with the selected signal.

**Comment by Night-Pryanik** [comment]
My tests results:
1. Pressing the button on the radio control when car is inactive and armed leads only to "click" message. Bomb will not detonate.
2. Pressing the button on the radio control when car is active, armed and in my inventory leads only to "click" message. Bomb will not detonate.
3. Pressing the button on the radio control when car is active, armed and on the ground invokes the transformation to active explosive with all these "you light the fuse" and "you pull the pin" messages. Then the explosive does countdown to zero and detonates.
I think that sending radio signal function to the explosive should be rewritten, because now it behaves like I'm distantly pulling the pin of the grenade with my radio control, and not like it causes the ignition in the bomb (or how it is goes IRL, I'm not an explosives expert).

**Comment by Coolthulhu** [comment]
> But this is 100% beyond my skills, and I'm not sure if it's in the scope of this PR.

Told you 2 times already:
In `trigger_radio_item` in map.cpp, you've got two sections: one for bomb items, one for bomb containers.
The one for bomb items works correctly.
You only have to copy the code from there to the bomb container section, after `n->make(bomb_type);`

Bombs detonating on activation (rather than n turns later) already work for non-car bombs. Copying that behavior for car bombs is not just well within the scope of this PR, but pretty much required for this PR to make sense.

**Comment by Night-Pryanik** [comment]
>Bombs detonating on activation (rather than n turns later) already work for non-car bombs.

Well, I don't know what bombs you talked about, but I tested it on black gunpowder bomb and charge, RDX sand bomb and several types of grenades - they all detonate after n turns.

**Comment by Coolthulhu** [comment]
Just tested:
* Spawn RDX
* Apply radio mod
* Send radio signal
* Detonates in the same turn

The same has to happen for items placed on cars.

The code that does this is already in trigger_radio_item in map.cpp, you only need to copy it to the `else` below and change a bunch of names.

**Comment by Night-Pryanik** [comment]
RDX has 2 charges, so it looked like it detonated on the same turn as it was activated. Test it on ordinary grenade (or black gunpowder charge) - it will take 4 turns to detonate.

**Comment by Coolthulhu** [comment]
Tested on incendiary, worked the same.

**Comment by Night-Pryanik** [comment]
Then why the explosives I mentioned earlier worked different?

**Comment by Coolthulhu** [comment]
Old version of the game? Mods? Old save? Possible save game issue?

**Comment by Coolthulhu** [comment]
I can't really replicate what you're describing. Are you activating the items by hand or something like that?

**Comment by Night-Pryanik** [comment]
Latest experimental, no mods, brand new game.
Step-by-step:
1) spawn grenade, radio activation mod and radio control;
2) apply mod to the grenade (red signal, for example);
3) drop modded grenade on the floor and run away;
4) push the red button on the radio control;
5) voila, modded grenade detonate on the floor after 4 turns.

**Comment by Coolthulhu** [comment]
Did exactly that. Generated a new world and a new character just to test it. The grenade detonated when I pressed the button, not 4 turns after.
Repeated that with a freshly uncompressed game with no save and config directories, just to make sure. Same result: immediate detonation.

You should probably file a separate bug report, with detailed info about things like game version (including tiles/console, windows/linux, 32/64).

**Comment by Night-Pryanik** [comment]
Submitted an issue. 
To makes thing worse, sometimes pushing the button on radio control even crashes the game.

**Comment by Night-Pryanik** [comment]
Uhmmm, did I do something wrong?

**Comment by Coolthulhu** [comment]
Looks like you manually copied the changes instead of merging my commit. Git sees this as a conflict.

Merge the newest master to your branch and solve the conflicts. If you're using some sort of a git tool, it should have a semi-automatic way of solving the conflicts.

**Comment by Night-Pryanik** [comment]
I need some help with merging. I'm using online editor, no command line or git tools.

**Comment by Coolthulhu** [comment]
Can't find anything related in google, this will probably be easier with a tool like "github for windows" or something like that.

**Comment by Night-Pryanik** [comment]
Ok, I'll try to do this with github for windows.
(to myself) Oh god, why all this is so unintuitive to use? I start to think it's easier to close this PR and make a new one.

**Comment by Coolthulhu** [comment]
If you can't do it any other way, close and open a new one. But learning it is helpful and will save on annoyance in frustration sooner or later.

**Comment by Zireael07** [comment]
@Night-Pryanik: I recommend SourceTree instead of GitHub for Windows. More intuitive interface.

**Comment by Night-Pryanik** [comment]
Made another PR (https://github.com/CleverRaven/Cataclysm-DDA/pull/13719).

**Pull request closed without merging**
