### PR TITLE
Nerf Broth to 5 Calories

### LINKED ISSUE #30904: Negative-calorie food
Crafting a food with high-calorie side products from low-calorie ingredients results in negative food. This happens for stewed tripe; I don't know if other recipes meet the requirements.

Steps to reproduce:
1: Craft stewed tripe from a large boiled stomach, two cabbages, salt and water. It produces four servings of 90-calorie broth and two servings of -15-calorie stewed tripe.

I guess expected behavior would be low-calorie broth and low-calorie tripe instead of high-calorie broth and negative-calorie tripe.

negativetripe

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Disable Religious Texts [no_religious_Texts],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Bens GF recipes [Tolerate_This],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by Three-Winters**
#### Summary

SUMMARY: Bugfixes "Nerf Broth to 5 calories to prevent stewed tripe having negative calories."
#### Purpose of change
Fixes #30904  

#### Describe the solution
Reduce broth calories to 5, which makes stewed tripe give 155 calories when crafted. I would think tripe would give a lot more calories than broth also.

#### Describe alternatives you've considered
None, feel free to suggest others.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Broth has many more than 5 calories. This is not a good solution to the bug.

**Comment by Mecares** [comment]
Weird, the broth in my kitchen claims 5 kcal per 100ml and 13 kcal per 250ml, are you sure 5 kcal is an appropriate amount?

**Comment by I-am-Erk** [comment]
Ah, it appears "broth" refers specifically to vegetable broth.

5kcal is still low for 250mL of veggie broth. I'd suggest 12. [Source](https://www.livestrong.com/article/401537-the-nutrition-in-vegetable-broth/)

**Comment by John-Candlebury** [comment]
I dont opose this but its really just a bandaid fix of #30904, properly fixing it properly requires some logic to ensure calories are split somewhat equitably between products and side products.

**Comment by kevingranade** [comment]
This is breaking a unit test, I'm pretty sure 13 is the more correct value anyway.

**Pull request merged**
