### PR TITLE
Remove redundant oil as tool from chips recipes

### LINKED ISSUE #55642: tortilla chips recipe lists oil as tool
### Describe the bug

tortilla chips uses oil as ingredient and as tool

### Steps to reproduce

look at the recipe

### Expected behavior

Don't list oil as **tool** if it's also needed as a **component**.

### Screenshots

image

### Versions and configuration

Win 8.1, Stable 0.F-3, tiles, english, default mod + "@" soundtrack

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oosyrag**
#### Summary
None

#### Purpose of change
Fixes #55642 

#### Describe the solution

Removed redundant oil as tool requirement, as oil is required as a component.

#### Describe alternatives you've considered

Increase amount of oil as a tool requirement to better represent the amount of oil required to deep fry something.

#### Testing
Screenshot 2022-02-26 170947

Checked recipe in game, oil no longer shows up as tool requirement.

### CODE REVIEW

**Comment by oosyrag** [comment]
They are baked now instead of deep fried. Someone else can add the deep frying back in another PR, or I can make another commit to this one if the man upstairs wills it.

**Comment by I-am-Erk** [comment]
If we're baking them, they should have an oven requirement. I would argue that the default "tortilla chips" item is fried though, and baked tortilla chips are the variant recipe.

**Comment by oosyrag** [comment]
Fine by me to leave as is, was just addressing the request in the linked issue.

Or should I increase the amount of oil required as a 'required tool' as suggested above? And a cooking vessel while I'm at it?

**Comment by I-am-Erk** [comment]
Yeah I think I'd increase the tool requirement to *more* oil, and add a cooking vessel and possibly the deep frying proficiency.

**Pull request closed without merging**
