### PR TITLE
Add a check for duplicate recipe_ids on load

### LINKED ISSUE #63138: Duplicated recipes are silently overwritten
### Describe the bug

When two recipes with the same `result` exist without an `id_suffix` to differentiate them, the game overwrites the first one that if finds with the last one that it finds. In other words: *Load order matters.*

### Steps to reproduce

Debug a character to know all recipes

Look at recipes for zinc powder

See there is only one recipe, despite two being present in the files

https://github.com/CleverRaven/Cataclysm-DDA/blob/d6d5349c992826d17eee88822464e1d83aa6ae70/data/json/recipes/recipe_medsandchemicals.json#L1421-L1434

https://github.com/CleverRaven/Cataclysm-DDA/blob/d6d5349c992826d17eee88822464e1d83aa6ae70/data/json/recipes/other/materials.json#L307-L320

See also: #62743

### Expected behavior

If two of the same recipe are loaded from the same source (e.g. both from DDA) then it should throw an error on loading to indicate there is erroneous data.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: d6d5349c992826d17eee88822464e1d83aa6ae70
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### LINKED ISSUE #71768: Recipes for garlic and chili powder are missing id suffixes
### Describe the bug

As the title says, there are multiple recipes for garlic and chili powder, but they get overridden because they lack id suffixes.

### Attach save file

n/a

### Steps to reproduce

Check the recipes in json and notice the lack of some of them ingame.

### Expected behavior

All recipes show up.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ZeroInternalReflection**
#### Summary
Infrastructure "Add a check for duplicate recipe_ids on load"

#### Purpose of change
Multiple recipes can be defined in the json with the same recipe_id.  These recipe_ids are not checked for conflicts on load, which causes some recipes to silently fail to appear in-game.
Fixes #71768 
Fixes #63138

#### Describe the solution
1. Update the recipe class to work with mod_tracker to track the source of each recipe (ident_ -> id)
2. Add a check on creation of recipes for duplicate recipe_ids.  Handle any duplicates like so:
- If the new recipe is defined by a mod and is overwriting the base definition, assume it's intentional and ignore it
- If the new recipe is defined by a mod and is overwriting a _different_ mod, add a note in the debug log so there's a way to check "Hey, why isn't x recipe from y mod showing up?"
- If both recipes are defined in the same mod, throw a debugmsg, because (based on #72002 and #72209) it's either lacking a suffix, a duplicate, or something that was intended to be a different recipe, but wasn't completed.

#### Describe alternatives you've considered
~~Adding a check in the test suite for recipe conflicts?~~
~~Wouldn't really be as useful for many people who only modify the json, but it would probably be worthwhile to automatically check all the in-repo recipes before release~~
The current CI system appears to load each json file and catch the debugmsg thrown by this change.  Between that and throwing a debugmsg on loading the game, that should cover most use-cases.

#### Testing
 - Loaded into Cataclysm and into worlds containing each of the in-repo mods with the check on, identifying a variety of conflicts.

 - Loaded into Cataclysm with several mods loaded, resulting in the debug log including a bunch of messages like this:
```
15:34:31.344 WARNING : Recipe_id conflict: fried_brain is included in both 'Innawood' and 'Aftershock'.  Only the latter recipe will be loaded
15:34:31.344 WARNING : Recipe_id conflict: grilled_sweetbread is included in both 'Innawood' and 'Aftershock'.  Only the latter recipe will be loaded
15:34:31.345 WARNING : Recipe_id conflict: thermometer is included in both 'Innawood' and 'Aftershock'.  Only the latter recipe will be loaded
```

 - I have _not_ tested any 3rd party mods, but I expect there are some in use that have recipe_id conflicts in their json.  This update will throw debugmsgs on loading any mod with conflicts.

~~There is no _automated_ test included, but if anyone has any ideas on how to set up a test to load the json from each in-repo mod, then it would probably be useful~~
No specific test suite is included, but it looks like any errors are caught by the all_mods check noted by mqrause below.

#### Additional context
 - The enumerate_as_string handling of the source _probably_ isn't necessary for recipes, but I based the infrastructure off of profession source handling and felt it was worth leaving in place

~~I'm holding this as a draft until #72209 is merged, because otherwise it'll throw debugmsgs on load for several in-repo mods~~
Now that the other PR is merged, I'm marking as ready for review.  Let's see if I need to rebase/if there are any other id conflicts I've missed.

### CODE REVIEW

**Comment by mqrause** [comment]
> * There is no _automated_ test included, but if anyone has any ideas on how to set up a test to load the json from each in-repo mod, then it would probably be useful

We already have test runs for groups of mods that load and check all the json. Although it doesn't check all valid combinations, I believe, but just makes sure every mod is loaded once. It should cover most cases, though. You'll see multiple test runs in the basic build that are labeled "all_mods".
The script to group up the mods is https://github.com/CleverRaven/Cataclysm-DDA/blob/master/build-scripts/get_all_mods.py. It could be altered if we find the tests done lacking.

**Comment by PatrikLundell** [comment]
Only very tangentially related, but I think that if I was responsible for a mod I would like to receive a notification whenever a recipe my mod overrides is changed, to allow me to adjust the recipe to match relevant changes, and possibly remove the override if the base recipe doesn't need to be replaced anymore.

**Comment by ZeroInternalReflection** [comment]
> We already have test runs for groups of mods that load and check all the json. Although it doesn't check all valid combinations, I believe, but just makes sure every mod is loaded once. It should cover most cases, though

Ah, you are correct.  Looking at the test runs for this PR, we find this failure:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8182628921/job/22374263691?pr=72220#step:17:216
Which flags one of the duplicates fixed by #72209.  So, any PR introducing recipe_id conflicts should fail without adding anything specific to the test suite.

I don't think an automated test checking combinations is necessary.  Mod B overriding the recipe in mod A isn't, in and of itself, a problem.  In fact, I'm betting in many cases it's desirable.  The trick comes when a user thinks the mods are loaded in a different order than they are, and wonders why something doesn't show up.  Hence the entry in the debug log.

> Only very tangentially related, but I think that if I was responsible for a mod I would like to receive a notification whenever a recipe my mod overrides is changed, to allow me to adjust the recipe to match relevant changes, and possibly remove the override if the base recipe doesn't need to be replaced anymore.

I'm sure that's possible, but I have no idea how an automated notification might be accomplished.  I could see a non-default test run to output a list of everything a mod overrides, with the original version summarized next to it, but that's a slightly different thing.

**Comment by RenechCDDA** [comment]
Would close #63138 on merge

**Pull request merged**
