### PR TITLE
Update magic_spell_effect.cpp

### PR DESCRIPTION
**Pull request by Kyoufi**
#### Summary
Features "Make spells hit walls instead of stopping on a tile in front of wall"

#### Purpose of change

It's just so stupid that i need to carry heavy sledgehammer everywhere just to occasionally shatter walls when my spells do damage similar to .50 BMG ammo. So i decided to make a mod that will add bash effects to spells that's supposed to have it. But there is a problem of the way spells interact with walls. If there is an impassable terrain, spell just stops on a tile in front of a wall, no matter its power. So i went even further and so here we are, with me making this pull request.

#### Describe the solution

So with adding one more iteration to few cycles spells will actually hit the walls, and if has enough power and bashing effect, shatter it.

#### Describe alternatives you've considered

Now im thinking about implementing the "BASH" spell flag that will add bash effect to spell, so we will no longer need to use consecutive casting for this.

#### Testing

Well i compiled game myself and all works fine for all spell shapes

### CODE REVIEW

**Comment by GuardianDll** [comment]
does any spell obtain an ability to bash terrain after this PR, or only one that already uses bash effect?

**Comment by Kyoufi** [comment]
> does any spell obtain an ability to bash terrain after this PR, or only one that already uses bash effect?

Basically this just makes spells hit the walls to, not stopping in front of
To actually shatter walls we still do need bash spell effect

**Comment by Maleclypse** [comment]
Looks like you've got a clang warning?

**Comment by Kyoufi** [comment]
> Looks like you've got a clang warning?

Is it bad?

**Comment by Maleclypse** [comment]
> > Looks like you've got a clang warning?
> 
> Is it bad? Will it prevent merging?

I think you would need to follow the instructions it gives 
```
use range-based for loop instead [modernize-loop-convert,-warnings-as-errors]
```

You can see what line it's in reference to on the files tab.

**Pull request closed without merging**
