### PR TITLE
Juice tweaks

### PR DESCRIPTION
**Pull request by Cyrano7**
Removes water from oj recipe. Changes result of juice recipe to 2 portions.
Water is not really an ingredient for orange juice. Currently you only yield 1 oj per 1 unit of water and 2 oranges. With the same cost you get 4 units of fruit juice currently. For fruit juice you get 4 units from 1 unit water and some fruit. I think this was done on accident as it come in twos and It doesn't need a multiplier.

### CODE REVIEW

**Comment by chaosvolt** [comment]
If it was from concentrate maybe. Though freshly-squeezed? I'm unsure, but it would be consistent with my altering fruit juice to have an option to make it without needing water. Though in that case it involved ADDING a new recipe, not replacing the old one fully.

**Comment by Cyrano7** [comment]
I'm not replacing the fruit juice recipe. Just removing the multifier. Since it spawns with 2 charges I figured whoever added the recipe must not have seen that part and probably intended it to have 2 charges.

**Comment by chaosvolt** [comment]
Ah, I see. That someone being me. I could've sworn @Coolthulhu had a reason involved in balancing, given all the tweaking that ensued when I added the alternative "juice using no water" recipe.

**Comment by Rivet-the-Zombie** [comment]
Good implementation! Using a multiplier is the proper way to go here, since giving a liquid charges subdivides each volume unit of water into portions, rather than resulting in more liquid.

**Comment by chaosvolt** [comment]
...are we reading the same code here, Rivet? They removed the result_mult for fruit juice, not changing how many charges it has. Which is the exact opposite of what you said. >.>

**Comment by Rivet-the-Zombie** [comment]
Yeah, I MB must've had a dumb moment there. I'll blame it on the fact that I'm on my phone instead of my desktop system. My point still stands though; if we want multiple units of juice, then we need a multiplier, since a stack size >1 means multiple servings per 250ml unit.

**Comment by Cyrano7** [comment]
Currently in game fruit juice spawns in groups of two. I'm not sure if I should described them as units or charges. So having a multiplier of 2 gets you 4. Which dosnt make sense with the current ingredients.

**Comment by chaosvolt** [comment]
Ah, no worries. And yeah, there was some reasoning behind the combination of charges and result_mult though. Some math that Coolthulhu did based off the combined quench/nutrition for the different recipes, additionally factoring in how much fruit pulp was being produced in each case. I vaguely recall just following along with the math as best as I could and implementing suggested tweaks accordingly. >.<

**Comment by Cyrano7** [comment]
ya I've defiantly spun my self around doing recipe math as you need to have the comestibles file open also. Currently you can use the same ingredients to get 1 oj for 35 quench and 3 fun or 4 fruit juice for 20 quench and 3 fun each.

**Comment by chaosvolt** [comment]
Hmm. I could've sworn that oranges were removed from the fruit juice recipe for the same reason that lemons were, due to a more specific version existing.

**Comment by Cyrano7** [comment]
I can just remove them in this PR if you want since i'm already here.

**Comment by chaosvolt** [comment]
Might work. Will need to re-figure out the logic for fruit juice now. ;w;

**Comment by Coolthulhu** [comment]
How does total nutrition and quench compare after removing the doubling?

**Comment by chaosvolt** [comment]
> How does total nutrition and quench compare after removing the doubling?

I need to figure that out, because you were the one to do all the math last time. @_@

**Comment by Cyrano7** [comment]
@chaosvolt your math is a little off btw, only by two 2 on the edited recipe quench total. I think I may have found one of the problems though. For making orange juice you get 2 charges of pulp for -2 quench and 30 nutrition. From the 2 oranges you start with you get 16 quench and 28 nutrition! Maybe you should only get 1 pulp from every 2 units of fruit. Especially for the fruit juice where you can use things like raspberries.

**Comment by chaosvolt** [comment]
Ah, doh. I see that now, yes. ;w;

And hmm, unusre how best to tweak things then.

**Comment by Coolthulhu** [comment]
Don't target one fruit type though - pick at least 4 common types (strawberries, blueberries, apples and cherries, for example).

**Comment by Cyrano7** [comment]
Well I guess making it only one charge since the pulp has more nutrition them some fruit. This would be one way as irl you don't really get very much pulp from one orange or apple.

**Comment by Cyrano7** [comment]
On a side note the grape cost is 4 grapes on both juice recipes.

**Comment by Cyrano7** [comment]
Okay. So nutrition for a lot of the fruit is around 14-18 per unit (like the strawberry, blueberry, apple, watermelon, orange). Juice pulp is 15. So after making juice your pulp nutrition is higher the the watermelon and orange and close to the other fruits I listed. So changing the pulp amount would bring pulp + the juice closer to the nutrition of the original fruit instead of being way ahead.

**Comment by chaosvolt** [comment]
Basically, juice pulp was tweaked to be more or less in the middle, relative to fruit on its own. Likewise, it was given a minor quench penalty for...some math reason. I need to find the PR where all this discussion took place.

**Comment by Cyrano7** [comment]
Oh wow I must have looked at the nutrition for juice wrong. Only 4?

**Comment by chaosvolt** [comment]
Meep. Ah, I see. Not yet sure how it all works out, but hopefully.

**Comment by Coolthulhu** [comment]
Pulp is `2*15=30` nutrition, `2*-1=-2` quench.
Juice is `2*4=8` nutrition, `2*20=40` quench.
For a single craft of "watery" juice we get 38 nutrition + 38 quench
So for ideal balance we'd like the fruit to have 38 nutrition and -12 quench.

Ingredients | Nutrition | Quench | Extra nutrition | Extra quench
--- | --- | --- | --- | --- | ---
2 apples | 32 | 6 | 6 | -18
2 appricots | 32 | 6 | 6 | -18
2 blackberries | 30 | 6 | 8 | -18
2 blackberries | 32 | 4 | 6 | -16
2 pears | 26 | 14 | 12 | -26
2 grapes | 36 | 10 | 2 | -22

Looks like crafting the watery juice is a good way to produce nutrition, but will always result in noticeable losses in quench.
Looks better than the old version, which would produce even more nutrition.

**Pull request merged**
