### PR TITLE
Treat bleeding from pets

### PR DESCRIPTION
**Pull request by Roguecop**
#### Summary
Features "Add option to make the bleeding of a pet stop"

#### Purpose of change

In the game until now, when a pet starts bleeding, we have no option to stop it using bandages or other meds that stop the bleeding effect.

This was tried to be solved by @Maleclypse in this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/62216, but was unfinished and moved to [Abandoned but Desired PRs](https://github.com/CleverRaven/Cataclysm-DDA/projects/51#card-89577648)

#### Describe the solution

I wanted something easy to solve the problem.

1. When a pet is bleeding, a new option is added in the menu opened when we examine (key "e") our companion
2. We need to have any "heal" item with "bleed" value in hand
3. We use the items wielded, and the bleeding of the pet disappears.

In case we don't have an item in hand or the item cannot be used to stop the bleeding, a message pops up in the log

#### Describe alternatives you've considered

There were other options I considered:

- When clicking to stop bleeding, open a menu to select a healing item
- Using the wielded item but only healing proportionately to the effect of the healing item to stop bleeding

I chose the option implemented because it was the easiest one and could make the work without complications or make the pet die while the player is making the healing.

#### Testing

I did manual testing, summoning a pet and making him bleed. After that, I tried:

- Heal without wielded items
- Heal with items without "heal" value
- Heal with items with "heal" value, but without "bleed" value
- Heal with items with "heal" and "bleed" values

I wanted to create some tests to automate this, but I was a bit confused when I found there's no tests in the test folder related to examine a pet (Swap, saddle, rename, etc.).

Because I don't know if this is a decision or something we lack, I just wanted to wait and maybe create the tests in a different PR

#### Additional context

stop_bleeding

### CODE REVIEW

**Comment by Termineitor244** [comment]
Finally!! I have been hoping for someone to take on this since the PR from Maleclypse was closed! Long live our pet overlords!

**Comment by Roguecop** [comment]
I'm a bit confused with the check failing. Anyone know what could be wrong?

error

**Comment by Maleclypse** [comment]
That failure isn't yours.  Clang and all the required tests passed so you should be good on this.

**Comment by DSeyka** [comment]
Why have this been merged without even basic proofreading?

**Comment by zachary-kaelan** [comment]
> I don't know if this is a decision or something we lack

By default assume it's something we lack. The tests in general seem to be outdated in many places.

**Pull request merged**
