### PR TITLE
Cannabis enhancement.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
I've always wondered why we can't actually use our hemp plants for plant
fiber, and why it produces so very few seeds. This PR changes cannabis
to be harvested in the form of a plant which is disassembled to produce
the consumable drug portion, plant fiber, seeds, and a withered plant
byproduct.

Cannabis seeds added to cooking oil recipe.
One new item: cannabis plant.
One new deconstruction recipe: cannabis plant.
Various tweaks to relevant items.

### CODE REVIEW

**Comment by Zireael07** [comment]
Great!

**Comment by Coolthulhu** [comment]
Shouldn't the weed crafting require some tools for those fibers? Some of those distaffs and spindles, carding paddles or whatnot?

That low seed production is the case for all plants right now. Your change would increase the seed production by a factor of 8, making hemp produce 4 times more seeds than any other plant in the game (8 times more than the most).
It would be better to keep the seed and "fruit" part separate for now, later on we can add a seed multiplier to all plants to balance their counts.

Isn't there a significant difference in size/fiber/etc. between the "illegal weed" and "legal hemp"? I assume the seeds in the game are all for the THC-rich cultivars.

In the cannabis description, you mention hemp oil. Currently it doesn't exist, as cooking oil doesn't allow "seed_weed" component. Adding it could be a part of this PR.
Though hemp shouldn't be better at oil making than dedicated oil plants, such as sunflower or canola.

**Comment by Rivet-the-Zombie** [comment]
>Shouldn't the weed crafting require some tools for those fibers?

You can typically just bend the stalks until they split using your hands, though a cutting implement would probably be a good addition to the recipe.

>Your change would increase the seed production by a factor of 8

Currently we get a single seed per planted tile, and the current version of this PR would give us eight per tile instead - numbers in deconstruction recipes count individual charges, not stacks. That's why a single plant grants 20 units of marijuana, and not 100. That being said, I can reduce it down to four seeds per plant by removing them from the deconstruction recipe if you think it's going to be that big of a deal - though to be fair, cannabis tends to produce a LOT of seeds if you don't separate the male and female plants.

>Isn't there a significant difference in size/fiber/etc. between the "illegal weed" and "legal hemp"?

The only real difference is that industrial hemp has been inbred to the point where it's devoid of THC. The physical structure isn't really any different between 'weed' and 'hemp' plants though.

>cooking oil doesn't allow "seed_weed" component. Adding it could be a part of this PR.

A danged good point!

**Comment by Coolthulhu** [comment]
> Currently we get a single seed per planted tile
> the current version of this PR would give us eight per tile instead

That may be a bug. If seed count at 8 survival is the same as one at 0 survival, that's most likely a bug. Though the test may require more than one tile per skill level - it's all RNG.

> though to be fair, cannabis tends to produce a LOT of seeds if you don't separate the male and female plants.

I assume a lot of plants currently have downscaled seed numbers. Could be explained as low skill resulting in wasted seeds, bad storage, young plants dying etc.

Later we could rescale the numbers, though it should probably affect all plants more or less linearly to avoid making some of them better at the role of other plant (say, making cotton better at being an oil plant than canola). As in, having a single big "seed rebalance PR".

**Comment by Rivet-the-Zombie** [comment]
>I assume a lot of plants currently have downscaled seed numbers.

Definitely in this case, as it now produces four per plant rather than something on the order of four *thousand* per.

**Comment by chaosvolt** [comment]
Note: More Survival Tools edits the recipe for plant fiber to accept hemp in addition to the default options of cattails and dogbane.

**Comment by Chezzo** [comment]
>The only real difference is that industrial hemp has been inbred to the point where it's devoid of THC. The physical structure isn't really any different between 'weed' and 'hemp' plants though.

Absolutely true. The hemp plants and weed plants are all reproduced by cloning for their good rope and good high traits. Going back to the seeds restarts the genetic lottery (to a great extent) that made the plants.

Apples are the same way. Johnny Appleseed wasn't planting trees from seeds for eating. He was planting trees from seeds for making Apple Jack. He was a drug dealer with a very good public relations agent.

Don't even get me started on strawberry seeds and bushes.

**Pull request merged**
