### PR TITLE
Water camouflage: Make fish not visible from unrealistically far away

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary
Bugfixes "Make fish not visible from unrealistically far away"

#### Purpose of change

Currently, fish (and other aquatic creatures) are visible when in water from entirely too far away, particularly from out of the water. This has, among other problems, forced various contortions in monster factions to avoid fish getting slaughtered by aggressive critters that really shouldn't be able to see them in the first place.

#### Describe the solution

This PR:
- Adds a new flag, `WATER_CAMOUFLAGE`, that acts like `CAMOUFLAGE` when the critter is underwater. (~~I need to add this to `doc/JSON_FLAGS.md` as well; will when I have a moment.~~ Added.)
- Adds a function to Creature, is_likely_underwater() - possibly to become a (non-pure) virtual function later - that not only checks is_underwater() (which for monsters is only counting deep water, via map::is_divable()) but also any SWIMMABLE water _if_ the creature is AQUATIC.
- Changes `Creatures::sees()` not only to use the above flag in a distance-based check, but to use is_likely_underwater() to tell whether the viewer is above-water and the viewed creature is below-water. The portion originally using is_divable() did not account for Z-levels; it now checks for any 2 of: `WATER_CAMOUFLAGE`; the terrain having `DEEP_WATER`; being on different Z-levels.
- Added `WATER_CAMOUFLAGE` to all critters with the `fish` faction in `data/json/monsters/fish.json`, plus some other vanilla monsters suggested by Venera3 (thanks!), plus the triffid vinebeast (which has SWIMS).
- Added `WATER_CAMOUFLAGE` to one monster each from DinoMod and DSA.
- Did some miscellaneous fixes in `data/json/monsters/fish.json`, such as making fish (smaller than a human) not show up on IR (have the `WARM` flag) as if they were warm-blooded and adding the `ARTHROPOD_BLOOD` flag to lobsters and normal-size crayfish (the mutant ones already had it), and similarly in mammals.json and triffid.json.

#### Testing

Compiles; JSON loads; playtested by myself and Venera3 (again, thanks!). I would actually like to add testing for this, Venera3's original `CAMOUFLAGE` flag, `NIGHT_INVISIBILITY`, the `HIDE_PLACE` terrain flag, and the `DIGGABLE` terrain flag's effects on vision - but this will be later.

### CODE REVIEW

**Comment by actual-nh** [comment]
I've done a modicum of playtesting and it does seem to make a difference (easiest to see on a low-per, no-spotting-proficiency character) for PCs. @Venera3, could you - or anyone else who can compile this locally - check re monsters, using whatever testing you did for that for `CAMOUFLAGE`? Thanks!

**Comment by actual-nh** [comment]
I have added this as a flag to two creatures from mods, both of which have AQUATIC. These are one DinoMod creature (the otherwise rather defenseless, but still aquatic-specialized, mosasaurus hatchling) and one Dark Skies Above creature (the lurker, which is described as more specifically hard to see than is the sewer lurker).

**Review by ephemeralstoryteller — APPROVED** [review]
This is basically exactly what I intended!

**Review by LyleSY — APPROVED** [review]
Looks great!

**Comment by Venera3** [comment]
After some (very limited) testing, I don't really see the difference. I have fish chilling in deep water at 45 tiles range showing up without incident, which only changes when they `dive into the deep water`. I think I'd also include shallow water in this, so potentially leaving `SWIMMABLE` as the sole requirement.

**Comment by actual-nh** [comment]
> After some (very limited) testing, I don't really see the difference. I have fish chilling in deep water at 45 tiles range showing up without incident, which only changes when they `dive into the deep water`. I think I'd also include shallow water in this, so potentially leaving `SWIMMABLE` as the sole requirement.

OK, will look at further. The portion that acts like your CAMOUFLAGE flag is supposed to work whether they're in shallow or deep water... I may have misunderstood the is_underwater function.

**Comment by actual-nh** [comment]
> > After some (very limited) testing, I don't really see the difference. I have fish chilling in deep water at 45 tiles range showing up without incident, which only changes when they `dive into the deep water`. I think I'd also include shallow water in this, so potentially leaving `SWIMMABLE` as the sole requirement.
> 
> OK, will look at further. The portion that acts like your CAMOUFLAGE flag is supposed to work whether they're in shallow or deep water... I may have misunderstood the is_underwater function.

I've partially changed it to use SWIMMABLE as well as is_underwater, but it would be preferable not to - that doesn't seem to be used for things that aren't _humanly_ swimmable. Could you check again? (Bit overloaded here - car accident.)

**Comment by actual-nh** [comment]
@Venera3: I am now quite certain this works, at least from the PC's viewpoint. (It finally occurred to me to simply back up and see if fish started disappearing...)

**Comment by actual-nh** [comment]
I have wound up still checking AQUATIC critters for being in SWIMMABLE terrain - instead of assuming that they're in SWIMMABLE terrain - even though they aren't supposed to be capable of moving anywhere else and can't survive anywhere else, because even if they're dying from being out of water, they should be visible as out of water.

There are actually two checks for dying AQUATIC critters - game.cpp checks if they've been knocked back out of something with the LIQUID flag; monmove.cpp checks for SWIMMABLE (as it does for what they can normally move to). These should be unified, and that fish can survive some period of time out of water (their injuring the fish-catcher in the meantime is a significant worry for some fish) should be taken into account.

**Comment by Venera3** [comment]
Tested with fish from the PC perspective, and spawned dragonfly naiads to check if they still see fish only from their night vision range. Nice! Some hostile monsters could use the flag as well - (zom)beavers, otters, sewer snakes, dragonfly naiads and jawed terrors come to mind (maybe the swimming zombie line to set them apart).

**Comment by actual-nh** [comment]
> Tested with fish from the PC perspective, and spawned dragonfly naiads to check if they still see fish only from their night vision range. Nice! Some hostile monsters could use the flag as well - (zom)beavers, otters, sewer snakes, dragonfly naiads and jawed terrors come to mind (maybe the swimming zombie line to set them apart).

Thanks! After the tests get finished running, I'll upload revisions for some additional hostile monsters.

**Comment by actual-nh** [comment]
@Mom-Bun: Perhaps add WATER_CAMOUFLAGE to the (triffid) vinebeast? (To sum up the above, this would make it hard to see when it's underwater if either you're at a distance or you're above reasonably-deep water.)

**Comment by actual-nh** [comment]
I did not add WATER_CAMOUFLAGE to the sewer snakes because they're yellow, BTW.

**Comment by actual-nh** [comment]
Ah, hell. How did I manage to do that? Sigh... fixing.

**Review by Mom-Bun — APPROVED** [review]
Sorry these past few weeks been chaotic for me, but just got to this! I'm totally 100% fine with vine beasts havng water_camoflage if they can swim, makes sense to me and will add extra danger :)

Plus some underwater triffid shenanigans could be neat

**Pull request merged**
