### PR TITLE
Add a way to enchant items in magicalysm

### LINKED ISSUE #63243: Magicalism Add ability to enchant weapons
### Is your feature request related to a problem? Please describe.

no

### Solution you would like.

adding new item called Enchanter's Toolkit that spawns in wizard tower
adding a new book for enchantment recipes
adding ability to craft enchanted items with it example:
Lucerne hammer+1 
Required: tool: Enchanter's Toolkit
Time:2 hours
Required: Materials: Lucerne hammer and 20 mana dust/4 lotus flowers/ 9 funnelcap chunk
Result:Lucerne hammer+1 

Lucerne hammer+2
Required: tool: Enchanter's Toolkit
Time: 3 hours
Required: Materials: Lucerne hammer+1 and+ 25 mana dust/5 lotus flowers/ 12 funnelcap chunk
Result:Lucerne hammer+2

### Describe alternatives you have considered.

no

### Additional context

just an idea we can discuss adding it or about crafting recipes

### PR DESCRIPTION
**Pull request by alp7292**
#### Summary
Mods "Adds item enchanting to magicalysm mod"
#### Purpose of change
closes #63243
adds a way to enchant items
#### Describe the solution
adds a new profeciency for enchanting
adds a new book that has a chance to spawn in magic shop that gives recipe for enchanting
adds a new category for enchanting recipes
adds enchanting recipes

#### Describe alternatives you've considered
 a different method of enchanting

#### Testing
created character and checked magic shop for book. found one and with mana dust, copper bracelet and crowbar i enchanted crowbar. gained profeciency

#### Additional context
we can adjust recipes with request.
every tier increases damage by %10 and decreases weight by %10 so i find it suitable for same requirement for both +1 and +2
sorry for inconvenience this is my first time using github

### CODE REVIEW

**Review by GuardianDll — APPROVED** [review]
Looks good for me

**Comment by alp7292** [comment]
slightly increased the chance of recipe book spawn as new item added to the pool

**Comment by GuardianDll** [comment]
Oh, replace your summary please, with `Mods "Adds item enchanting to magicalysm mod"`
It is made in this way so bot can harvest this text afterwards, and put it into weekly log

**Comment by alp7292** [comment]
> Oh, replace your summary please, with `Mods "Adds item enchanting to magicalysm mod"` It is made in this way so bot can harvest this text afterwards, and put it into weekly log

updated

**Comment by KorGgenT** [comment]
i'd love to see more mercury used in magical metal recipes, but this seems more or less ok at a glance.

**Comment by alp7292** [comment]
drafted as i will add mercury to metal recipes when i have time

**Comment by alp7292** [comment]
added mercury to recipes fixed wrong metal qualities

**Review by GuardianDll — APPROVED** [review]
Looks good for me

**Pull request merged**
