### PR TITLE
Fix typo in faction camp recipes

### PR DESCRIPTION
**Pull request by 790**
#### Summary

SUMMARY: Bugfixes "Fix typo in faction camp upgrade recipe json"

#### Purpose of change

Fixes a typo on an ID that prevented a couple of faction camp upgrades from working properly

#### Describe the solution

Use the correct ID.

#### Describe alternatives you've considered

n/a

#### Testing

Tested after making change and could complete the faction camp upgrades.

### CODE REVIEW

**Comment by jbytheway** [comment]
Can you explain in what way these were wrong?  What would need to be checked to catch similar errors in the future?

**Comment by ZhilkinSerg** [comment]
There were objects of `mapgen` type with `X` in `update_mapgen_id` field without corresponding object of `recipe` type with `X` in `construction_blueprint` field.

Here is pair of such two related objects (with `X` equal to `fbmc_shelter_beds_straw_NW`, which is erroneously called `fbmc_shelter_shelter_beds_straw_NW` in recipe blueprint, which also caused it to have empty blueprint requirements as it was not related to any existing mapgen):

```
  {
    "type": "mapgen",
    "update_mapgen_id": "fbmc_shelter_beds_straw_NW",
    "method": "json",
    "object": { "place_nested": [ { "chunks": [ "fbmc_shelter_bed_straw_west_wall" ], "x": 5, "y": 9 } ] }
  },
```

```
  {
    "type": "recipe",
    "result": "faction_base_modular_beds_straw_NW",
    "description": "Let's furnish the northwest bedroom with straw beds.",
    "category": "CC_BUILDING",
    "subcategory": "CSC_BUILDING_BASES",
    "autolearn": false,
    "never_learn": true,
    "construction_blueprint": "fbmc_shelter_beds_straw_NW",
    "blueprint_name": "furnish the NW bedroom",
    "blueprint_requires": [ { "id": "fbmc_shelter_bedroom5" }, { "id": "fbmc_shelter_beds_w" } ],
    "blueprint_provides": [ { "id": "fbmc_shelter_beds_nw" } ],
    "blueprint_excludes": [ { "id": "fbmc_shelter_beds_nw" } ],
    "blueprint_needs": { }
  },
```

**Comment by jbytheway** [comment]
Presumably it is acceptable to have `update_mapgen` objects with no corresponding recipe (if they're not used for faction camps or similar).  So the check we want here is to verify that any recipe's `construction_blueprint` is valid?

I'll add that to the recipe validation I created for #43033 once that is merged.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/digging-further-into-faction-camps/24630/4

**Pull request merged**
