### PR TITLE
5.45x39mm Mainlining and Weapon Additions

### PR DESCRIPTION
**Pull request by chaosvolt**
I hope that mainlining the 5.45 ammo will be acceptable, as it's a bit odd to have that be mod-only. And odder still that Icecoon didn't add any real weapons alongside it. :V
1. Mainlined 5.45x39mm ammo.
2. Added the AK-74 and AN-94 weapons. Seriously, who adds a real-world
   ammo and then only uses it for futureguns?
3. Also added 9x18mm Makarov ammo.
4. Makarov pistol and 2 variants of Skorpion SMG. .32 ACP could use a
   little more love.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Now to hope that it doesn't bork.

**Comment by Rivet-the-Zombie** [comment]
Very nicely done!

**Comment by Rivet-the-Zombie** [comment]
It throws a debug error: duplicate ammo id '545'.

**Comment by chaosvolt** [comment]
Ack. Huh, let me see what I derped up here...

**Comment by chaosvolt** [comment]
Also, the only piece of mod content removed instead of mainlined was the inclusion of 5.45x39mm ammunition into the "HOME_GUNS" item group. Only a limited selection of ammunition appears on that list, whereas a far wider selection of casings are present.

**Comment by chaosvolt** [comment]
And thank you for the merge. ^^

**Pull request merged**
