### PR TITLE
Add scissors to the First Aid Kit

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Add scissors to the First Aid Kit"

#### Purpose of change

The First Aid kit does not have scissors. Likely an oversight, as first aid kits you can buy IRL have them.

#### Describe the solution

Add scissors to the First Aid Kit

#### Describe alternatives you've considered

Leave our survivors to cut bandages using their teeth.
#### Testing

Put in game, test if it works.

### CODE REVIEW

**Comment by actual-nh** [comment]
Problem: One of the "slow" tests is using one or more first aid items in a test. I suggest copying the original full and used kits to the mods/TEST_DATA directory's items.json (IIRC) file, calling them something like test_full_1st_aid/test_used_1st_aid.

**Comment by Xenomorph-III** [comment]
I think it's done. Hopefully, it won't complain again.

**Comment by actual-nh** [comment]
Evidently it requires a name (e.g., "Test Full First Aid Kit")...

**Comment by mqrause** [comment]
The issue seems to be that the first aid kit container is too small to fit all items with the scissors added. Your original commit failed because a test spawned a car that contained a full first aid kit, not because any test directly uses first aid kits. Adding the original kits with new ids doesn't help in that case, because they wouldn't be spawned anyways.

I don't think scissors really use up 250ml, so giving them an appropriate volume (and probably length and weight) might be enough to fix that. If not you probably need to increase the volume of the container.

**Comment by actual-nh** [comment]
They come in different lengths - I'm guessing 3.5" for the first aid kit; the below values assume some of the given dimensions are packaging for shipping.

[5.5": 6.5 x 3.25 x 0.5 inches; 1.4 oz](https://prodentusa.com/shop/surgical/surgical-scissors/surgical-scissors-standard/lister-bandage-scissors-5-5/)

[3 from 3.5 to 5.5: 0.2 lbs, 4.7 x 4.4 x 0.2 inches](https://www.amazon.com/EMI-Lister-Bandage-Scissors-Piece/dp/B00AVA32P4)

3.5" estimated as:

- 4 x 3.25 x 0.2 inches; 1.1 oz
- With rounding: 31 g; 10.2 cm length; volume 43 cm^3 (43 mL)

**Comment by actual-nh** [comment]
OTOH, simply adjusting the existing scissors would be a lot easier. From the above proportions, call it 145 ml for the volume for regular scissors?

**Comment by Xenomorph-III** [comment]
@actual-nh  Thanks for the PR!
What about the tests? Can I just delete them?

**Comment by actual-nh** [comment]
> @actual-nh Thanks for the PR!
> What about the tests? Can I just delete them?

Quite welcome. And deleting the test items looks to be a very good idea.

**Comment by actual-nh** [comment]
Sigh. Looks like the kit box still needs adjusting. I'd go with a pocket that can do 2450 ml, with the overall volume being, say, 2650.

**Comment by Xenomorph-III** [comment]
Thank you for the PR, @actual-nh , but I've already made modifications per your suggestion. Can I just close your sent PR?

**Pull request merged**
