### PR TITLE
Fix many limited duration items not lasting long enough since 1-second turns

### LINKED ISSUE #33192: Items with "turns_per_charge" property don't last long enough
# Describe the bug

Predictably, ever since the turn length was altered from 6 seconds to 1, items with turns_per_charge property (mostly light sources AFAIK) don't last nearly long enough. I tested this with the oil lamp and glowstick, but presumably others are affected as well.

# Steps To Reproduce

1. Spawn a character and cheat in an oil lamp and 0.5L of lamp oil.
2. Fill the lamp with oil and switch it on.
3. Wait for 3 in-game hours.
4. The lamp will run out of fuel after ~2.8 hours.

# Expected behavior

In real life, 0.5L of lamp oil will last about 34 hours (source: https://www.redhillgeneralstore.com/Oil-Lamp-Parts/Lantern-Oil.htm )

This fix could be as simple as multiplying all the "turns_per_charge" values in the JSONs by 6, thus returning them to their previous behavior. Alternatively, we could take this opportunity to come up with more accurate numbers -- for example, for the oil lamp, a turns_per_charge value of 240 matches the numbers I retrieved from the above link.

# To-Do list
Stuff that probably doesn't need changes:
- Explosives use ```turn_per_charge``` but seem fine (fuse times of 1-10 seconds for grenades, 1-2 minutes for timed bombs)
- Flaming weapons are for fun and have no basis on reality AFAICT so any changes would be rather arbitrary

Stuff that could use a reality check:
- [x] ```candle_lit``` lasts 1.4 hours (Fixed in #33665)
- [x] ```oil_lamp_on``` lasts 4 hours (Fixed in #33665)
- [x] ```glowstick_lit``` lasts 40 minutes (Fixed in #33665)
- [x] ```gasoline_lantern_on``` lasts 2 hours (Fixed in #33665)
- [ ] ```oxylamp_on``` lasts 4 hours with small welding tank
- [ ] ```ref_lighter_on``` lasts 10 minutes
- [ ] ```torch_lit``` lasts 25 minutes
- [ ] ```hobo_stove``` lasts 8 hours
- [ ] ```tinderbox_on``` lasts 16 hours
- [x] ```rm13_armor_on``` lasts 4 hours (Fixed in #33621)
- [ ] ```rebreather_on``` and ```rebreather_xl_on``` last 10 minutes
- [ ] ```mask_h20survivor_on``` and ```mask_h20survivorxl_on``` last 20 minutes
- [ ] ```scuba_tank_on``` last 10 minutes
- [ ] ```small_scuba_tank_on``` lasts 3 minutes
- [ ] ```combatsaw_on``` lasts 15 minutes
- [ ] ```handflare_lit``` lasts 5 minutes

Battery-using stuff that needs ```power_draw``` property:
- [ ] ```cell_phone_flashlight``` lasts 75 minutes
- [ ] ```smartphone_music``` lasts 5 hours
- [ ] ```smart_phone_flashlight``` has both ```power_draw``` and ```turn_per_charge``` properties
- [ ] ```geiger_on``` lasts 15 minutes
- [ ] ```noise_emitter_on``` lasts 10 minutes
- [ ] ```angular_grinder``` lasts 3 hours

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6301-g3597e0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
Many items' ```turns_per_charge``` values weren't fixed for 1-second turns.
I went through and did research for each case and corrected them.

#### Summary
```SUMMARY: Bugfixes "Fix many items not lasting long enough since 1-second turns"```

#### Purpose of change
Fixes #33192 

#### Describe the solution
Addressed each item individually:
- refillable lighter - doubled to 20 minutes from full charge ([source](https://www.youtube.com/watch?v=dL2XNR-NNfg))
- torch - doubled to 50 minutes ([source](https://www.reddit.com/r/AskHistorians/comments/1e7adh/weve_all_seen_the_unrealistic_torches_used_in/))
- hobo stove and ember carrier - untouched, seem fine based on discussion [here](http://www.wilderness-survival.net/forums/showthread.php?790-Carrying-fire-ember)
- rebreathers - tripled to 30 minutes. [According to wikipedia](https://en.wikipedia.org/wiki/Rebreather#Scrubber_effectiveness), rebreather scrubbers last from 30 minutes to several hours. Given the tiny size of C:DDA's rebreather, it seems like it would be on the low end.
survivor's divemasks - tripled to 1 hour. Just mantaining the ratio of survivor's divemasks lasting twice as long as standard rebreathers.
- scuba tank - from 10 minutes to 1 hour. ( http://www.elitedivingagency.com/articles/long-scuba-tank-last/ )
- small scuba tank - multiplied by 6 to maintain ratio with regular scuba tank.
- flare - from 5 minutes to 30 minutes, to match description.

The following were altered to use ```power_draw```:
- cell phone flashlight, smartphone flashlight - 500 mW, assuming full screen brightness ([source]( https://www.usenix.org/legacy/event/atc10/tech/full_papers/Carroll.pdf))
- smartphone music - 300 mW (same source as above)
- geiger counter - 200 mW based on [this one on amazon](https://www.amazon.com/GQ-GMC-500Plus-Radiation-Detector-Dosimeter/dp/B071JWB7TJ?ref_=Oct_BSellerC_318143011_0&pf_rd_p=0a889183-3ac8-5311-b709-562bd28c59ba&pf_rd_s=merchandised-search-6&pf_rd_t=101&pf_rd_i=318143011&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=1DW902AJ1RQY1SX697HC&pf_rd_r=1DW902AJ1RQY1SX697HC&pf_rd_p=0a889183-3ac8-5311-b709-562bd28c59ba) which uses uses 45-200 mW
- noise emitter - 10000 mW (based on a mini portable speaker I have that uses a maximum of 10 W)
- angular grinder - 800000 mW based on [this one on amazon](https://www.amazon.com/BLACK-DECKER-Grinder-6-5-Amp-BDEG400/dp/B00RZV20CS?ref_=Oct_BSellerC_552812_1&pf_rd_p=364fda04-227e-5d42-a407-eb28c0587a44&pf_rd_s=merchandised-search-6&pf_rd_t=101&pf_rd_i=552812&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=YE3FA0588NQYBZTH4SB3&pf_rd_r=YE3FA0588NQYBZTH4SB3&pf_rd_p=364fda04-227e-5d42-a407-eb28c0587a44) which uses 6.5 A and 120 V, multiplied to get 780 W

#### Describe alternatives you've considered
Assigning ```power_draw``` values to more of these items, though I wouldn't know where to start with assigning wattage values to lighters and torches.

### CODE REVIEW

**Comment by ymber** [comment]
`power_draw` is only intended for electrical items. It assumes a single charge of the items ammo represents 1kJ.

**Comment by DaviBones** [comment]
@ymber You're sure about ```power_draw``` only being intended for electrical items? In #33154 gasoline chainsaws were modified to use ```power_draw``` instead of ```turns_per_charge```. It's relevant because in this PR I modified combat chainsaws to match those changes (which I just realized I forgot to document in the OP, whoops)

I'm now not sure whether to undo my changes to combat chainsaws and leave it how it was before, modify both combat and normal chainsaws back to using ```turns_per_charge```, or not worry about it and let the PR be merged as is.

**Comment by ymber** [comment]
When I wrote it in #30656 `power_draw` assumed the ammo being consumed was 1kJ battery charges. I can't check now if this has been changed since but I don't think it has. Unless it got generalized using it for anything that doesn't use battery charges for ammo won't behave how you expect.

**Comment by DaviBones** [comment]
Ok, I wasn't sure if the ```energy``` property in ```fuel.json``` was perhaps the specific energy of the substance in MJ/kg, and the unit conversion was being done in C++ somewhere. Seems like that's not the case though. I think the fact that ```turns_per_charge``` is listed as deprecated in ```JSON_INFO.md``` has introduced confusion to both ampersand55 in #33154 and myself.

**Comment by kevingranade** [comment]
That's my bad, I wasn't thinking about non-electrical resource consumption when I labelled them deprecated.

**Comment by DaviBones** [comment]
Ok, no problem, thanks for clarification. Returned chainsaw to using ```turns_per_charge```, using a fuel tank of 450 mL and a run time of 30 minutes as per discussion in #33152. Also changed combat chainsaw values to match. PR should be ready now.

**Pull request merged**
