### PR TITLE
Construct resin terrain

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds constructible, nearly indestructible resin terrain made from alien pods"```

#### Purpose of change
The mi-go base adds resin pods, which can be detached and stolen as an examine action. These store the resin used to make their base, which is I believe the most durable terrain in the game. The pods are meant to be one of the better loots available in the place.

#### Describe the solution
Adds recipes for using these pods to construct some of the terrain types seen in the mi-go base.
Adds charges to the pods, so that a single mi-go camp provides enough resin pods to do at least a decent little fortification. This may require the resin pod to be retrieved by smacking or deconstructing it, not sure.

#### Describe alternatives you've considered
I am considering making the mucus filled alien pod stealable as well, and having it be a component to build some of the special furniture types in the mi-go base such as the light fronds and the valve doors.

#### Additional context
- [x] Add recipes
- [x] Add count to resin pod
- [ ] Test in game

### CODE REVIEW

**Comment by Rail-Runner** [comment]
> I am considering making the mucus filled alien pod stealable as well, and having it be a component to build some of the special furniture types in the mi-go base such as the light fronds and the valve doors.

Do want.

Aside from that, would it make sense to make personal or vehicle armor from this material? If so, that could actually be some decent loot.

**Comment by I-am-Erk** [comment]
It has plant-like roots, I don't think it would be a good idea to see what it would do on your body.

More meta wose

**Comment by I-am-Erk** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/harvesting-alien-resin-pods-from-mi-go-towers-should-take-1-2-minutes-at-the-most/24175/1

**Pull request merged**
