### PR TITLE
Add passenger cars to subway stations

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Content "Add actual train parts to subway stations"

#### Purpose of change

Subway stations without trains are a bit boring.

#### Describe the solution

Adds some vehicle spawns to the subway station.

image

(demonstrates the varying y placement, this one used a fixed 100% chance for demo purposes)

#### Describe alternatives you've considered

n/a

#### Testing

Applied changes locally (which is how I got the screenshot).

#### Additional context

I like trains.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Oh neat can you add one of these to the -2 hub01 station?

**Comment by NetSysFire** [comment]
That should be easy but I am not too familiar with the hub01 lore. Would it make sense for them to be undamaged?

**Comment by John-Candlebury** [comment]
Undamaged would make sense there yeah. Thank you!

**Comment by NetSysFire** [comment]
image

I hope that works for you because apparently one can not place vehicles over grid bounds (e.g `x: [23, 24 ]`), this makes it really hard to place these passenger cars.

**Comment by John-Candlebury** [comment]
Its pretty great thank you!

**Pull request merged**
