### PR TITLE
Increase availability of tin and only allow it to be extracted with electrolysis

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary

```SUMMARY: Balance "Increase availability of tin and only allow it to be extracted with electrolysis"```

#### Purpose of change

Due to the recent addition of tin as a material, and the change tin crafting (#33111) tin has been very hard to come by. 

Currently tin_plate and bowl_pewter could be "deconstructed" for tin with a basic hammer which defeats the purpose of the electrolysis tin crafting recipe.

#### Describe the solution

* Remove tin and pewter hammer deconstruction.
* Add pewter bowl to tin crafting recipe (pewter is 93–98% tin).
* Increase tin yield of tin crafting recipe so that most of its weight is extracted.
* Change tin description to reflect that it's a powder.
* Add more tin and pewter items to appropriate item groups to make tin more available.

---

Update: Tin item groups have been overhauled. Every instance removed and new one's added.

I've made a item collection called "tinware" consisting of pewter_bowl, tin_plate and tin_cup.

The tinware group is added to the following itemgroups: 

* trash, trash_cart, trash_forest, art, medieval, dining, camping, kitchen_nonfood, antique, museum_misc, pawn, dollar_kitchen.

In mansions, tinware is added to the following itemgroups: 

* kitchen_nonfood, clutter_mansion, clutter_ballroom, table_wine, table_sideboard, table_ballroom, table_livingroom

I made also made it possible for a glass of wine to spawn. The container distribution for the glass of wine is is 75% glass, 25% tin_cup, 5% glass bottle and the content is taken from the wines_worthy item group.

A glass_of_wine is added to the following itemgroups: 

* table_wine, table_sideboard, table_ballroom, table_livingroom, table_card, wetbar_counter, nightstand.

Raw tin is added to the following itemgroups: 

* pawn, chem_school, chem_school, chem_lab, science

#### Describe alternatives you've considered

An alternative would be to remove the tin electrolysis recipe and instead let players deconstruct it with a hammer as tin is quite ductile and malleable. But tin is only used to make solder and to coat containers with electrolysis so it makes sense to imagine it as a powder.

It's no point having both the electrolysis recipe and the deconstruct option for tin.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Are tin containers really that common? A quick google search for 'tin cup' shows mostly stainless steel campware, and a very small number of reproduction cups.

I think the only places reasonable for these are antique stores, and not frequently either due to their low value.

**Comment by ampersand55** [comment]
> 
> 
> Are tin containers really that common? A quick google search for 'tin cup' shows mostly stainless steel campware, and a very small number of reproduction cups.
> 
> I think the only places reasonable for these are antique stores, and not frequently either due to their low value.

You're right, I was a bit lazy and mostly added it to places where the pewter bowl was. 

I think finding tinware in mansions, antique stores, pawn shops, and raw tin in hardware stores, metal working shops and chemistry labs/stores is plausible. There could perhaps be a small chance of it spawning in dining rooms.

I'll update later. Requesting more suggestions for tinware/tin locations.

**Comment by Moonsabrt** [comment]
Garbage dump is one place where you may find tin. 'w')/

**Comment by ampersand55** [comment]
I've completely reworked where tin items and tin can spawn.

**Comment by kevingranade** [comment]
You've got some kind of error with "tinware".

**Comment by ampersand55** [comment]
I think it's fixed now.

**Comment by AMurkin** [comment]
Now it's this:
> item id wines_worthy is unknown

**Comment by ampersand55** [comment]
Bloody hell.

Again, I think it's fixed now. But it seems like I have bad luck when thinking.

image

**Pull request merged**
