### PR TITLE
Added holster for polearms [CR] [WIP]

### PR DESCRIPTION
**Pull request by Stone94**
added a recipe for the holster, it wont work for halberds or awl pikes because they are long weapons, and added a Flag to each of the compatible weapons.

I just need help balancing it, or suggestions for improving (or pointing out anything i should change)

### CODE REVIEW

**Comment by Xhuis** [comment]
This always felt like it was missing. Now I can wield my holstered spears like I wield the holsters for my normal weapons!

**Comment by Night-Pryanik** [comment]
Please add a description of your new flag to the `JSON_FLAGS.md`.

**Comment by DracoGriffin** [comment]
I don't know about this one. All the research and searching I've seen is that spears almost never use scabbards, sheaths, holsters or the sort.

*However*, there have been a number of different styles of wearing the spear (albeit rarely, most were carried in hand or by animal transport/wagon) -- essentially a shoulder strap. There was a [mini-mod](https://www.reddit.com/r/cataclysmdda/comments/71zurp/preliminary_reddit_release_of_my_strapped_poles/) on the CDDA subreddit that did just that -- added mods for spears so shoulder straps could be attached. Although that worked, I don't think that's great design (although it does open up to melee modifications of improving weapon hilts and grips, and other such things which would be great).

I highly recommend switching from holsters to just simply the shoulder strap mechanism, or at least making the them wearable, I suppose?

Sources: [one](https://myarmoury.com/talk/viewtopic.php?t=34789) [two](https://www.quora.com/How-did-pre-modern-warriors-carried-their-weapons-into-the-battle-field) [three](https://www.reddit.com/r/NoStupidQuestions/comments/5x5xst/how_do_soldiers_carry_spears_and_stuff_on_their/) [four](https://worldbuilding.stackexchange.com/questions/53155/how-to-carry-a-spear)

**Comment by Stone94** [comment]
> > I don't know about this one. All the research and searching I've seen is that spears almost never use scabbards, sheaths, holsters or the sort.
However, there have been a number of different styles of wearing the spear (albeit rarely, most were carried in hand or by animal transport/wagon) -- essentially a shoulder strap. There was a mini-mod on the CDDA subreddit that did just that -- added mods for spears so shoulder straps could be attached. Although that worked, I don't think that's great design (although it does open up to melee modifications of improving weapon hilts and grips, and other such things which would be great).
 I highly recommend switching from holsters to just simply the shoulder strap mechanism, or at least making the them wearable, I suppose?

I'll look into trying to go with the shoulder strap method as that would be ideal, but as of right now i dont think its possible to mod melee weapons through JSON, I dont think it would be beyond my current ability to do it through c++, but I dunno whether or not i could implement it in a non messy way, worth a try though. but i have found some sources of spears being strapped (not with a holster) with the bashkir people, maybe I'll try going that route and see if i can make shoulder straps attach to the spears and staves.

**Comment by Stone94** [comment]
Im gonna close this PR, i cant think of a good reason for it. but it was fun practicing git :) ill probably package it into a mod for those who want it.

**Comment by thethunderhawk** [comment]
Dude make it wearable like a bindle! It makes perfect sense, you can still wield a handgun with it, and it solves the problem of keeping it out of storage without wielding it or making a new item or mechanic.

**Comment by Stone94** [comment]
Well i would have to either make them wearable by default or make a new crafting recipe for each spear, thats kind of a quick and dirty fix. Without being able to attach stuff to melee weapons. Plus if your holding  a spear which are presumably 6' and using a handgun or any other firearm, your aim wont be very accurate due to recoil etc. In thise situations it would be better to just drop the spear outright.

**Pull request closed without merging**
