### PR TITLE
Adding missing weight property to some foods

### LINKED ISSUE #27685: Certain foods have no mass
**Describe the bug**  
Few foods have no mass.

Foods with this problem: 
deep fried tripe
fried brain
deviled kidney

They do not have mass at all defined in the json.

**To Reproduce**  
Look at the item in game. The item is listed as 0.00 kg.

**Expected behavior**  
The item should have some mass.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-36728-ga67b4a0 (tiles)
 - Mods loaded "dda", "alt_map_key", "filthy_morale", "no_npc_food"

### PR DESCRIPTION
**Pull request by saurocyte**
#### Summary
```SUMMARY: bugfixes "No more weightless food!"```

#### Purpose of change
Fixes #27685

### CODE REVIEW

**Comment by AMurkin** [comment]
Valid category would be: `bugfixes`.

**Comment by KorGgenT** [comment]
What are these weights from? they are very far off from the other foods.

**Comment by AMurkin** [comment]
Sorry. I meant this:

SUMMARY: bugfixes "No more weightless food!"

Fixes #27685

**Comment by saurocyte** [comment]
Thanks, corrected.

**Comment by KorGgenT** [comment]
jenkins rebuild

**Pull request merged**
