### PR TITLE
more mutant traits, TCL start

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Features "TCL Labs have mutant starts, mutant starts have more trait options"

#### Purpose of change
I wanted the mutated starts to have more options to choose from, there are a lot of cool mutations that can change up how you play. I also wanted to give TCL more options, mutant starts like the traditional labs. Since oldstyle labs are being phased out anyways a new lab mutant start will be needed.

#### Describe the solution
TCL is split into two types: TCL Staff, which allows Security, Medical Resident and Lab Technician like the old labs, and TCL Mutant, which allows Unwilling/Volunteer Mutants which get to pick mutations as traits. Both are now worth 8 points instead of 6, because TCL is significantly more challenging to escape than the traditional labs which were themselves worth 8 points.
Mutants get to pick a wider variety of traits as well.

#### Describe alternatives you've considered
I wanted to also allow some stat-changing mutations such as Freakishly Huge but it causes serious issues, the stats are counted towards your base stat total which breaks your point totals. I don't know how to fix this but I would love to figure out a solution (likely requires c++ magic) because starting the game Huge would be a fun mixup to the game and make the XL tag a lot more meaningful. I can't ever see myself crafting XL cloth gambeson or whatever when better options are available by the lategame point you can become huge.
This also runs into an issue that trait-mutations cannot be purified and don't count towards thresholds. This was an issue before but adding more traits exacerbates the issue.

#### Testing
I loaded this up in game, things are working fine and traits seem to be blocking each other fine.

### CODE REVIEW

**Comment by Maleclypse** [comment]
I think the additional mutations are in the in-repo "extra mutated scenarios" mod.

**Comment by anoobindisguise** [comment]
> I think the additional mutations are in the in-repo "extra mutated scenarios" mod.

This approach is a bit different than extra mutated scenarios. EMS gives you the option of picking every trait - with no regard for the aforementioned statpoint bug, and also offers post thresh mycus mutations, this list is a little bit more curated. Also no options for post thresh, I think it's meaningfully different and just an expansion of what we already have in main.

**Comment by Saicchi** [comment]
I think there is no point on worrying about points, since freeform is a better way to play the game.
The Post Tresh Mycus mutations only happen if you select the `Mutant - Mycus Threshold` scenario. The generaly mutations are pre-threshold, that includes Marloss Vessel, Marloss Carrier, etc.

**Comment by anoobindisguise** [comment]
Okay, I *think* freakishly huge is working now but I haven't made sure.

**Comment by anoobindisguise** [comment]
OK, can confirm! This compiled and tested perfectly, taking freakishly huge is pushing my "range" of strength up from 4-14 to 8-18 and behaving normally. 
image

**Comment by curstwist** [comment]
Overall looks good.  I'm fine with adding additional starts on the concourse.  Kevin didn't want starts that began too deep into the lab and these don't so it should be fine.

I'm not sure why you changed the description for the staff start from essential to non-essential and I don't think it is necessary but I'll let others weigh in if they like. It changes the context of the start characters back story.

I don't know much about mutations so I won't comment on those additions, expansion.

**Comment by anoobindisguise** [comment]
Yeah, essential-nonessential is up in the air. I changed it because that was the terminology the last lab start used so I wanted to update it to address that but it doesn't have to happen that way.

**Comment by anoobindisguise** [comment]
bird wings got made a threshold mutation in the time this has been waiting to be merged... fixed that and it won't show up here anymore.

**Comment by anoobindisguise** [comment]
fuck it, closing this and trying again. I hate github so much.

**Pull request closed without merging**
