### PR TITLE
Snippets can now call EOC effects

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Snippets can now call EOC effects"

#### Purpose of change
Something Erk wanted so the game can track what the player does and doesn't have knowledge of for convos with NPCs

#### Describe the solution
Added the infrastructure to attach an "effect_on_examine" to any snippet with an ID.

the effect is invoked the first time you query the info on the snippet (so on examine). The snippet is stored as being seen and won't call again.

I've added example snippets of "engineer scribbles" to Cody the Artisan Blacksmiths house which after looking at you can ask her about. She'll brush you off currently but in the future there may be followup. 

#### Testing
Spawn the isolated road OMs
talk to Cody
image
examine the papers in front of her
image
talk to her again and note the new dialogue.
image

#### Additional context
_Currently the game crashes if you attempt to give the player an item as an effect while they see a snippet from the look menu. 
As well if you open an item from the inventory and it adds an item you can drop the item you were going to examine and get the item info for the spawned item.
In reality no piece of paper should be spawning an item so this shouldn't come up and I imagine would require some heavy reworking of the menus in question to fix._

### CODE REVIEW

**Comment by Ramza13** [comment]
So this works but it might be simpler and more powerful if you just supplied an EOC id and then activated that EOC.  it would give you access to conditions and I think mean less new code.

**Comment by bombasticSlacks** [comment]
Can an EOC add a variable based on the invoking item. I thought about that option but if 30 snippets have 30 EOCs that is each just u_add_var: has_read_snippet_x context: world_knowlege that seems really cumbersome and bloated

**Comment by Ramza13** [comment]
So you could make it able to read inline EOCs so it wouldn't be separate entries but you're not wrong that it is kinda bloated.  

Another though is to take a look at the message function in npctalk.cpp and the same_snippet argument.  I think all I-am-erk wants is to set a variable and you could make a message argument that causes it to set a variable.  Not sure if that would mean changing all the newspapers or not though.

Or just ignore me and leave it alone as it does whats needed at the moment.

**Comment by bombasticSlacks** [comment]
I think I might have to make it also handle inline EOC's cause erk wants to be able to increment a general knowledge variable. The setup I have works fine for 
```set variable to true``` 
cause a true variable being set to true again doesn't matter but for a counter variable you need to check 

```if(has not yet seen this) increment```
otherwise it would increment each time the effect was called unconditionally. I'll mull it over and confirm with Erk what he thinks would be easiest on the implementation side.

**Pull request merged**
