### PR TITLE
Fix rendering routine on native wayland

### LINKED ISSUE #49886: cataclysm-tiles "lags" when run natively under Wayland
### Describe the bug

When the game is run natively under Wayland, it looks like some kind of lag is happening. The window content is updated only after another keypress/resize/etc event happened.

(Might just be a bug in SDL)

### Steps To Reproduce

1. Run the game under wayland, not XWayland. (I used `SDL_VIDEODRIVER=wayland cataclysm-tiles`)
2. Press the right arrow key in the main menu
3. Press the left arrow key in the main menu and observe the selection moving to the right

### Expected behavior

Direct input feedback, the window updates according to the given input as it does under X11.

### Screenshots

(Tried to take a screenshot of the off-center main menu after a window resize, but didn't manage to do it. The screenshot always looks correct)

### Versions and configuration

- OS: nixos-unstable, sway 1.6
- Game Version: 0.F
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: []

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MalteT**
#### Summary
Bugfixes "Fix rendering routine on Linux/Wayland"

#### Purpose of change
Fixes #49886.

#### Describe the solution
Adjust rendering routine to work under native wayland.

#### Describe alternatives you've considered
None.

#### Testing
- [x] Tested under Sway v1.6 using `opengl` renderer.
- [x] Tested under Sway v1.6 using `software` renderer.
- [x] Tested under Android.

### CODE REVIEW

**Comment by MalteT** [comment]
I tested the patch under native Wayland using Sway (wlroots) and it works fine except for the software renderer. The software renderer is still broken. I haven't tested it on Android yet and I'm currently lacking the time to debug the building errors for the mobile platform.

I personally think the Android test is the only blocker on this. If someone has the time and energy to fiddle with Android, I would be happy about the feedback.

**Comment by Faalagorn** [comment]
Indeed, I just realized that after switchng to software renderer behavior seems to be the same as an old one, at least on my old instance of the game with the patch applied – it isn't like that for OpenGLES2, too. Might take a look, might be something easy, but don't count on it.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/steam-dark-days-ahead/26348/47

**Comment by MalteT** [comment]
For those in need of software rendering on native wayland, let me introduce you to this ugly patch:
```patch
diff --git a/src/sdltiles.cpp b/src/sdltiles.cpp
index 07e6c294f3..d17626aba5 100644
--- a/src/sdltiles.cpp
+++ b/src/sdltiles.cpp
@@ -3711,6 +3711,7 @@ input_event input_manager::get_input_event( const keyboard_mode preferred_keyboa
     wnoutrefresh( catacurses::stdscr );
     if( needupdate ) {
         refresh_display();
+        refresh_display();
     }
 
     if( inputdelay < 0 ) {
```
I'm currently trying to understand where the `refresh_display` is _really_ missing, but my gdb skills are very rudimentary.

**Comment by Faalagorn** [comment]
Okay, I just compiled the latest master with both patches applied (g 09095afde0-dirty as of writing) and tested all three modes (opengl, opengles2 and software) with both `SDL_VIDEODRIVER=wayland` (set globally in `.bash_profile`) and `SDL_VIDEODRIVER=x11` (set at runtime) on sway (Arch Linux) and it all work fine – I tested whether `xeyes` correctly detect the application running xwayland (they do) and loaded to a game with both tiles and graphical overmap loaded.

I didn't do performance benchmarks; there is noticeable performance drop with software rendering (not sure how it is without the patch, but I guess it might be similar).

The only minor issue I noticed is with `SDL_VIDEODRIVER=wayland` after I maximize the game from tiled position the menu stretches only after you perform action, it isn't like that with different modes, but given the fix is hacky I'm positively surprised how well it works!

screenshot_2021-09-19-133334
screenshot_2021-09-19-133337

I'll try compiling and testing the Android version, as I would really like the patch to make into the game. :)

**Comment by Faalagorn** [comment]
Okay, it turned out to be #51708 being the issue on Android.

After compiling, I tun the game with both patches applied – the regular rendering one was running fine, no issues noticed. However, I can't test the software rendering as it makes it crash for me, but it happens with the regular 0.F-2 version from Play Store (both when chosen from in-game option or from the start after clearing data). I installed a 64-bit armv8 version (I guess the same is the one from store), my device is not rooted.

Screenshot_20210919-180946
Screenshot_20210919-182904

I'll see if I can solve it, until then I sadly can't test how software rendering works on Android. :/

**Comment by Faalagorn** [comment]
@MalteT Can you mark both testing as done? Also, are you still working on the PR? If not, since it works maybe remove the draft mark so at least the OpenGL/OpenGLES render works natively on Wayland and add software rendering in a separate PR? Though unless there's some terrible regressions, I'd include software one too. I don't use software renderer generally, but I still include the patch in my builds and so far it brings no issues for me.

**Comment by MalteT** [comment]
Hey @Faalagorn, thanks for all your work! :)

I can't really work on this at the moment, but I think this could be merged as is. I'd feel quite bad to see the second patch actually make it into the repo. Software rendering is slow enough as is, no need to randomly double computations.

**Pull request merged**
