### PR TITLE
Added ammo to ammo machines and buffed vending machine

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Instead of using older itemgroups, the machines are stocked with 1-2 ammo_common and 1 ammo_rare each.

### CODE REVIEW

**Comment by pisskop** [comment]
Can we make them stronger or something?  Maybe like stronger than a wall?  A safe with a dispenser box?

**Comment by BorkBorkGoesTheCode** [comment]
Now it's beefed up.

**Comment by mugling** [comment]
Works as intended but the contents could be improved. One option could be for each vending machine to carry a different type (pistol, smg, rifle, shotgun) with a 50% chance of `ammo_*_rare` (0-1 repeats) and a 50% chance of `ammo_*_obscure` (no repeat)?

**Comment by BorkBorkGoesTheCode** [comment]
Hi. I have been busy.

**Comment by mugling** [comment]
Stalled?

**Comment by BorkBorkGoesTheCode** [comment]
I'm gonna try to fix the merge conflict.

**Comment by BorkBorkGoesTheCode** [comment]
Abandoning this: if anybody wants to copy the gunstore changes, feel free.

**Pull request closed without merging**
