### PR TITLE
Move magazines to CSC_WEAPON_MAGAZINES

### PR DESCRIPTION
**Pull request by Cyrano7**
The only value changed was the subcategory

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Can they not get a category of their own?

**Comment by Cyrano7** [comment]
@BorkBorkGoesTheCode Ya your probably right.

@Everybody How should we handle CSC_WEAPON_OTHER? It will be empty in vanilla cata but some mods use that subcategory.

**Comment by BorkBorkGoesTheCode** [comment]
I just started a vanilla game using default screen size, and I found a problem. New subcategories may get bumped offscreen unless they wrap around to the next line.

**Comment by Cyrano7** [comment]
Hmm its showing up fine on my screen.

**Pull request merged**
