### PR TITLE
Wipe out unused flags 'SMALL_BITES' & 'SMALL_BITER'

### PR DESCRIPTION
**Pull request by illi-kun**
Related to #14211.

I found that flag 'SMALL_BITES' wasn't declared & used in code. Declared version in code (see monstergenerator.cpp:L367) and described in doc (see JSON_FLAGS.md) is 'SMALL_BITER'.

The issue is that flag 'SMALL_BITER' actually also not used, it was just declared with following code:

> `SMALL_BITER` Creature can cause a painful, non-damaging bite. Not implemented.

...so maybe it's better to just wipe it out.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, right.

As to what use the monster flag actually is, as you asked earlier? I'm not sure. Right now a provoked vermin with the flag doesn't really do anything but interrupt crafting/reading/waiting/etc, so making them able to do something might be interesting.

There likely should be a way for the player to retaliate and swat pests though, as most such creatures also have small_vermin and can't be targeted..

**Comment by Coolthulhu** [comment]
I don't really see a good use of SMALL_BITER flag.
It could trigger when swapping places with vermin, but since vermin are hard to spot (and even harder to kill), it would probably be more of an annoyance than a feature.

**Comment by chaosvolt** [comment]
Possibly, yeah. Alternatives would be a "biter dies or takes damage when biting" effect, or...hmm. I'm not sure how else to make it work, and the alternative makes vermin mostly flavor creatures.

**Comment by illi-kun** [comment]
@Coolthulhu, that's exactly what I'm thinking about this flag. Let's put [WIP] tag on this PR and take a look on other opinions, and if no one will argue, I'll wipe both ```SMALL_BITES``` and ```SMALL_BITER``` from code & documentation.

**Comment by chaosvolt** [comment]
Seems like a good idea either way. If I could think of any way to make small biters something other than basically flavor entities, WITHOUT them being invulnerable stinging hellspawn, I would suggest such a thing.

As it is, I can't think of any good arguments in favor of retaining the flag.

**Comment by kevingranade** [comment]
Yea, I don't think it actually adds anything, and even if it did it would be annoying as hell to deal with unless we added something to make interacting with vermin more streamlined.

**Comment by chaosvolt** [comment]
Agreed. Only thing I can think of to that effect is having the player automatically get a chance to swat at the offending insect, but that's about it as far as my ideas go.

**Pull request merged**
