### PR TITLE
Medieval churl JSON

### PR DESCRIPTION
**Pull request by forkingpath**
A friend (who provided the lovely Middle English descriptions) was playing a conduct game as a medieval transplant, so I thought it might be a fun addition to the game proper.

Future work: make chat with NPCs unintelligible.

### CODE REVIEW

**Comment by drbig** [comment]
Maybe add some seeds and a pitchfork/shovel? Like you were teleported straight from the field :)

**Comment by Coolthulhu** [comment]
Do we have a pitchfork?

Hoe would probably be more fitting than shovel, though.

**Comment by drbig** [comment]
Yeah, some seeds and some farming tool.

**Comment by karlnp** [comment]
How about I do a separate PR for a medieval farmer profession? That way we still get the bare-bones challenge intended here, and we can have a more agrarian approach if we want.

**Comment by drbig** [comment]
Just throwing ideas around. This looks good as it is.

**Comment by karlnp** [comment]
😊

**Comment by Night-Pryanik** [comment]
Oh, I suspect some difficulties translating this Middle English descriptions.

**Comment by drbig** [comment]
@Night-Pryanik I'd assume the translations for stuff such as this should be more about the 'spirit/idea' preservation. E.g. for Polish something that *looks like* Old Polish would probably do. It's a game after all and the point here is 'snatched from medieval straight into future post-cataclysm'.

**Comment by chaosvolt** [comment]
And very belatedly, I should point out that, concerning the scenario, shouldn't forcing the Illiterate trait ALREADY prevent taking Fast Reader and Slow Reader? o.O

**Comment by karlnp** [comment]
They cancel each other out, so it's possible to take Fast Reader and undo the Illiterate trait while keeping the bonus points. IIRC - it's been a weekish since I was writing/testing this.

**Comment by chaosvolt** [comment]
Ah, odd. O.o

**Comment by chaosvolt** [comment]
One other thing I noticed. Briefs and loincloth? o.O

**Comment by karlnp** [comment]
nobody wants things dangling in the apocalypse

**Comment by chaosvolt** [comment]
Riiiight. Smells more like a modding fail to me. Why would a medieval peasant have briefs? :V

**Comment by Rivet-the-Zombie** [comment]
>Why would a medieval peasant have briefs?

aliens

**Comment by chaosvolt** [comment]
Is always dem aliums. :V

**Comment by karlnp** [comment]
because we don't have rough-hewn stockings and nylon seemed less objectionable! 

although i know now i could have used long underwear, but i hadn't seen that then

**Comment by chaosvolt** [comment]
Huehuehue. Maybe I should've mainlined the fur leggings from More Survival Tools. XP

**Comment by chaosvolt** [comment]
...ignore that, I done derp. Real one will exist in a moment.

**Pull request merged**
