### PR TITLE
Add bullet damage type

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Features "Separate bullet damage type from cut/stab"

#### Purpose of change
Currently, bullet damage is modeled the same as cut/pierce damage. This is incorrect  - bullets mechanically deal damage differently than a knife or lower velocity projectile, like an arrow, would. Because bullets deal damage in a different way than a knife or arrow, they are also protected against in a different. This is evident in materials like kevlar, which is excellent at blocking bullets, but performs less well against cutting/stabbing implements.  

#### Describe the solution
Depends on #37329 and #38882.
The first three commits are from those two PRs.
Commit by commit:
##### Damage loading code
 - Add `bullet_protec` member to bionics, holding the bullet protection armor that a CBM gives.
 - Add `bullet` type clothing mods.
 - Add `armor_bullet_bonus` member to Creature
 - Add code to load `bullet` type damage from damage objects
 - Add `DT_BULLET` to the damage type enum
 - Allow spells to do bullet damage and bullet damage related enchantments
 - Add `bullet_resist` to materials
 - Add `armor_bullet` to monsters
- Adds a warning (using `debugmsg`) when an item is loaded using the old damage format, because this means it is likely a gun that should be using this damage type, not stab.
##### Update logic for bullet resistance 
 - Add bullet damage/armor getters
 - Use bullet damage in shotgun traps
 - Update tests for bullet damage
##### Bullet damage UI bits 
 - Update UI to show bullet armor/damage
##### Update materials for bullet damage 
 - Set bullet resistance for materials to 80% of their cut resistance, arithmetically rounded
##### Update guns to use bullet damage 
 - Change the damage type from `stab` to `bullet` for guns
##### Update ammo to bullet damage
 - Change the damage type from `stab` to `bullet` for ammunition.
##### Update monster bullet damage
 - Bullet damage is set equal to stab damage (generally 80% of cut), arithmetically rounded
##### Add documentation
 - Update the docs

There should be few changes to how guns damage and interact with monsters, the player, etc. in this PR, and the changes that there are should just be slight changes to armor due to rounding.

#### Describe alternatives you've considered
I considered setting the values for armor to be something other than largely what they were before (duplicates of piercing damage), but I decided that that probably deserved a more thorough and careful examination than I could do in this PR.

#### Testing
Bullet damage works correctly: Shooting a kevlar hulk with a .308 rifle does ~30 damage when their bullet damage field is populated, and ~70 when it is not.
Looking at clothing items shows bullet resistance.
Looking in the `+` menu shows bullet resistance. 
This is a pretty big PR, so I probably need to come up with some more tests.

#### Additional context
I considered JSON-izing damage types first, as requested by @ZhilkinSerg, but I figured this was more important to do now (I'll JSONize later).

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
No more bulletproof chainmail?
image

**Comment by Aphegis** [comment]
This is a big improvement.

**Comment by mkikt4743** [comment]
cool now we can balance ESPAI vests

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cut-piercing-dmg-should-not-be-used-against-bullet-dmg/23217/5

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/way-of-solving-excessive-damage-of-new-turrets-just-replace-ammo-type/23051/22

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/esapi-armor-is-still-hilariously-broken/23258/3

**Pull request merged**
