### PR TITLE
Feral Cops

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Content "Feral Cops"

#### Purpose of change
I wanted to challenge myself to add a dangerous feral that doesn't use a gun.

#### Describe the solution
Feral cops very rarely appear in place of zombie cops. They are semi intelligent capable of coherent, but limited sentences. They use a baton as their weapon and will blow a whistle at you when they see you, creating noise and attracting other zombies. Thus they're a sort of living equivalent of a screamer zombie. 
Their gear is in marginally better condition than actual zombie cops and they more often have a complete set of gear. Otherwise they drop the same stuff as a zombie cop, just not filthy.
They use a special faction which is allied with COP_BOT so police bots won't attack them, and they won't attack police bots or eyebots. This might be lore breaking since they ARE on team blob but feralism occurs in degrees and these ones might remember some bits that let them differentiate police bots from other stuff to kill. Like all cops though they are still bastards and cannot be reasoned with.

#### Describe alternatives you've considered
Give them an airhorn instead of a whistle. Or adjust whistle noise.
Make them attack police bots/vice versa.

#### Testing
Cops spawn, approach player, make noise and seem to work properly, code compiles. They team up with their robot buddies in pursuit of the player.

#### Additional context
ACAB

### CODE REVIEW

**Comment by liminalRoar** [comment]
Wouldn't need to be too high, but what about giving them some dodge? I guess i haven't checked other ferals, but i feel that some some dodge skill should be standard perhaps, since they are a bit more "lively" than regular zombies.

**Comment by anoobindisguise** [comment]
> Wouldn't need to be too high, but what about giving them some dodge? I guess i haven't checked other ferals, but i feel that some dodge skill should be standard perhaps, since they are a bit more "lively" than regular zombies.

Good point, they didn't have any. I went with the feral soldier's 4 dodge since they are geared similarly.

**Comment by liminalRoar** [comment]
I am all for making him a tough enemy, however, I feel like 3 might be more appropriate after checking the other ferals some. But whatever ppl think is reasonable. 4 seems a little high for anything with a lot of armor. But i really don't know too much about what is standard.

**Comment by Night-Pryanik** [comment]
@anoobindisguise could you please resolve conflicts?

**Comment by Maleclypse** [comment]
This needs a rebase again.

**Pull request merged**
