### PR TITLE
[Ready] Basic climbing implementation

### PR DESCRIPTION
**Pull request by Coolthulhu**
Mostly as a dependency for 3D explosions, so that the player can get out of holes created by those.

Made 3D mode ledges not insta-kill zeds, but instead deal impact damage.

Allowed monsters to stumble up and down (currently only fliers).

TODO:
- [x] Make 3D ledges work on monsters properly
- [x] Balance 3D ledges and make player code use those

I won't be adding much balancing for the climbing itself in this PR, it's only so that falling down a hole isn't a guaranteed starvation death.

As usual, all the new 3D stuff will only work in 3D mode.

### CODE REVIEW

**Comment by tyrael93** [comment]
There's a thing I've wanted to do for years when playing DDA: get to the first or second floor of a building, throw down a rope from a window, go down using a rope or a ladder, bash/blow up the staircase to the first floor so zombies can't reach me and then climb back up. Perfect base. climbing would take some turns, stamina and a dexterity check, but generally zombies would be too dumb to climb up the rope. Then maybe create some kind of automatic ladder or something.

Do you think that could be possible in the future?

**Comment by vache** [comment]
> Do you think that could be possible in the future?

Only if it is also just as possible for zombies to smash down all the walls below you!

**Comment by kevingranade** [comment]
>> Do you think that could be possible in the future?
>
> Only if it is also just as possible for zombies to smash down all the
walls below you!

Yes to both :D
That kind of interaction is the main goal of z-levels work.

**Comment by Rivet-the-Zombie** [comment]
>so that falling down a hole isn't a guaranteed starvation death

No more Sinkhole of Amontillado? This is a very welcome fix indeed. Nice work, @Coolthulhu!

**Comment by Coolthulhu** [comment]
Should be ready now. I went conservative with nerfing fall damage (jumping down a 1 story building still hurts a lot) and monster AI (non-animals don't understand falls hurt).

Monsters will not travel up/down using sight or smell, only sound and stumbling. Climbing monsters are currently very good at the job, while player is quite bad. But since all climbing monsters are very agile (the tag is only on monster like hunters and spiders), this shouldn't be a problem.
As for the player - this is for escaping from holes rather than dedicated climbing at the moment.

**Comment by Zireael07** [comment]
Woo!

**Comment by kevingranade** [comment]
Good scoping, I appreciate cutting it off before it gets too extensive :D

**Comment by kevingranade** [comment]
Climbing needs some better feedback, because it's not at all obvious what you need to do to climb out.
AFAICT there are three scenarios/messages that will cover it.
"There's a ceiling above you, you can't climb here."
"There's no wall to climb next to you."
"You're not good enough at climbing to climb this sheer wall, maybe if you had other walls to brace against you could do it."

I probably would have patched those in, but this is also happening:
Make a big crater with a mininuke or something.
Spawn a bunch of zombies on the other side of it from you.
As they fall in, you start getting:
```DEBUG: update_zombie_pos: wanted to move the zombie to x, y, -2, but new zombie already has the zombie.```
and
```DEBUG: update_zombie_pos: no the zombie at x,y,0 (moving to x,y+1,0)```
``DEBUG: the zombie at (x, y+1,0) was not found in the tracker```
With the same x/y/z values from what I'm seeing.

Aah... if a square that a zombie would fall to is occupied, the fall cancels and the zombie instead floats, and even walks across other zombies.  At the cost of an absurd number of debug messages you can fill up a crater with zombies.

**Comment by kevingranade** [comment]
Unrelated, managed to cause a div/0 by having str 0.

**Comment by Rivet-the-Zombie** [comment]
>you can fill up a crater with zombies

This would be cool if it were properly implemented - i.e. not comfortably walking across each others heads and such.

**Comment by kevingranade** [comment]
Yea, we've thus far avoided the multiple monsters on one square problem, but this might finally force our hands (not in this PR though).

**Comment by Coolthulhu** [comment]
I'm not sure if multiple monsters per tile are worth the effort. It would require rewritting pretty much everything that uses `mon_at` or `critter_at` to understand lists of monsters.

Having monsters push each other and get prone/stunned when covered would work for a while.

I think I got both the bug and the messages fixed. Currently the ceiling message doesn't show up often, because most buildings don't have ceilings as terrain (only as tag). This doesn't allow the player to phase through ceiling because there is nothing to stand on above.
I will add actual roofs (and thus ceilings) later.

Jenkins is complaining about lua, but I didn't touch lua here. Did any important lua-related PR get merged? I'll check if merging master will help.

**Comment by kevingranade** [comment]
The effect where craters fill up is super weird.  We need to sort out how we want that to work.
A slightly more sensible approach that doesn't allow multiple creatures to occupy one space is to make open air where the next level down is occupied count as impassible, that prevents both monsters and the player from simply walking across a filled-in crater.
I was thinking explosions should probably leave "slopes" which count as climbable when they don't quite destroy a section of solid ground, this would make craters act more like craters, it shouldn't be THAT hard to climb back out of them, and that would generally prevent the problem of zombies filling up the crater too.

**Pull request merged**
