### PR TITLE
Clang Fix

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
Clang is failing this should hopefully fix it?

#### Describe the solution
make it no lint next line instead of nolintbegin

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
AFAIK we need to either do what the check suggests, or add this to the line above the suggested tripoint. Our version of clang-tidy isn't recent enough for the comments I tried to work.

**Comment by bombasticSlacks** [comment]
That makes sense. I basically did a lazy kick at it on mobile I can try to wrap the lines when I get to my PC.

**Comment by anothersimulacrum** [comment]
> doesn't throw for the above array

AFAICT those are constructed to avoid any of the named tripoints, which I didn't quite think to do for this.

**Comment by bombasticSlacks** [comment]
Oh I see, sorry I got distracted doing other dev and haven't really put much heart into this.

I can fix this tomorrow if you want, but I feel like I'm making double the work for you by halfheartedly trying stuff and making you have to check in on the progress😆

**Pull request closed without merging**
