### PR TITLE
armor penetration gets used up like damage

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Bugfixes "flat armor penetration is spread across all armor layers instead of applying its full value to each"

#### Purpose of change
Partially address #65173
Armor penetration is broken, both because it has absurdly high values and also because it renders single armor layers useless (you could wear 20 individual hypothetical 1mm kevlar shirts and still take full damage from a 5.56 nato round, which has 6 armor penetration, but if you had a single 8mm thick kevlar shirt, it would stop the bullet almost entirely)

#### Describe the solution
Armor penetration is "used up" by the amount it penetrated a single armor layer. If there is a flat armor penetration in addition to a multiplier armor penetration, the actual defense code always applies flat before multiplier, so the same thing is true here (even if the attack has 0.5x armor mult, a 10-armor armor will always reduce the total flat penetration in the attack for the next layer by 10)

#### Describe alternatives you've considered
I have not thought of any.

#### Testing
Compiled and tested using a special Giant Wasp (mon_wasp) which had its normal attack reduced to 1 damage and its special attacks changed to always do 10 damage instead of a variable amount and wore increasingly large numbers of phelloderms to test its damage. The bite has 20 pen and does cut damage, and the sting has 25 and does stab damage. Phelloderm has 3 cut and 2.4 stab protection.
- At 6 or fewer phelloderms, I took full damage from each attack (10)
- At 7 phelloderms I have 21 cut and 16.8 stab prot. The bite did 9 damage and the sting did 10 damage.
- At 8 phelloderms, I have 24 cut and 19.2 stab prot. The bite did 6 damage and the sting did 10 damage.
- At 9 phelloderms, I have 27 cut and 21.6 stab prot. The bite did 3 damage and the sting did 10 damage.
- At 10 phelloderms, I have 30 cut and 24 stab prot. The bite did 0 damage and the sting did 10 damage.
- At 11 phelloderms, I have 33 cut and 26.4 stab prot. The bite did 0 damage and sting did 9.
- At 13 phelloderms, I have 39 cut and 31.2 stab prot. The bite did 0 damage and the sting did 3.
- At 14 phelloderms, I have 42 cut and 33.6 stab prot. The bite did 0 damage and the sting did 1.

### CODE REVIEW

**Comment by Venera3** [comment]
Broad strokes I'm for this, but I'd expect the multiplier to be applied before the flat AP - in your example the 10 AP should get reduced to 5 instead of zeroed out.

**Comment by anoobindisguise** [comment]
> Broad strokes I'm for this, but I'd expect the multiplier to be applied before the flat AP - in your example the 10 AP should get reduced to 5 instead of zeroed out.

Yeah so how it works currently, is that the flat amount is applied to your armor, then the remainder is multiplied. So if you have 20 armor and face a 10 damage attack with 10 pen, and 0.5x multiplier, you take 5 damage if the multiplication is done after the flat reduction, and 0 if the multiplier is applied before the flat damage. IMO it should work like the former way, rather than the multiplier doubling the effectiveness of all flat armor penetration too.

**Comment by Venera3** [comment]
Whatever you're doing on your attack that makes the armor half as effective should make armor half as effective, not half as effective unless it's about defeating armor penetration. 

Regardless, whichever you go with should be documented explicitly.

**Comment by bombasticSlacks** [comment]
> 
    At 6 or fewer phelloderms, I took full damage from each attack (10)
    At 7 phelloderms I have 21 cut and 16.8 stab prot. The bite did 9 damage and the sting did 10 damage.
    At 8 phelloderms, I have 24 cut and 19.2 stab prot. The bite did 6 damage and the sting did 10 damage.
    At 9 phelloderms, I have 27 cut and 21.6 stab prot. The bite did 3 damage and the sting did 10 damage.
    At 10 phelloderms, I have 30 cut and 24 stab prot. The bite did 0 damage and the sting did 10 damage.
    At 11 phelloderms, I have 33 cut and 26.4 stab prot. The bite did 0 damage and sting did 9.
    At 13 phelloderms, I have 39 cut and 31.2 stab prot. The bite did 0 damage and the sting did 3.
    At 14 phelloderms, I have 42 cut and 33.6 stab prot. The bite did 0 damage and the sting did 1.

Gotta get you writing unit tests 😁

**Comment by anoobindisguise** [comment]
So the issue is that in damage.cpp you have 
```
float resistances::get_effective_resist( const damage_unit &du ) const
{
    return std::max( type_resist( du.type ) - du.res_pen,
                     0.0f ) * du.res_mult * du.unconditional_res_mult;
}
```
So if I made penetration reduction apply after the multiplier, it would introduce an incongruity. I mean that can be rewritten too but as is right now, you need an armor with 15 resistance to tank a 10 damage, 10 arpen, 0.5x multiplier attack, not 20.

**Comment by bombasticSlacks** [comment]
So I'm good to merge this as it is now, I think any math changes would need more comprehensive work. Just waiting on some form of documentation, it looks like none of this is documented at all right now, so adding it somewhere would be appreciated. A comment in the cpp file about how armor pen gets used up would make sense too I think.

**Comment by anoobindisguise** [comment]
> Also, if mult applies before flat pen, there's no reason you wouldn't just get rid of the mult and double the flat pen in JSON. Under the current proposed system having a flat pen and mult leads to a different scaling system, where the remainder of whatever the flat pen couldn't defeat is multiplied by a fraction, which means you need less armor for your armor to start mattering, but your armor matters less, rather than your armor mattering the same amount, but needing more armor for it to start mattering. If that makes sense

I just realized this isn't true 100% of the time. Gonna put this in draft for a bit because that throws off my assumption for why this is this way

**Comment by bombasticSlacks** [comment]
> I just realized this isn't true 100% of the time. Gonna put this in draft for a bit because that throws off my assumption for why this is this way

That's true but I think this is still a step in the right direction.

**Comment by anoobindisguise** [comment]
OK so. I can change the line ` du.res_pen -= res.type_resist( du.type )` to be ` du.res_pen -= ( res.type_resist( du.type ) * du.res_mult )`.

Scenario1: 40 damage attack, 0.5x armor multiplier, 5 flat pen. You have a cuirass with 20 armor which is hit. Mitigation = 20 - 5 = 15, 15 *0.5 =7.5 protection, so you take 32.5 damage. Mitigation = 7.5. Arpen is reduced by 20 (becoming 0). This is how it would currently work.  If the change is made, instead it works like this: Mitigation still = 20 - 5 = 15 * 0.5 = 7.5, but arpen is reduced by 10, becoming 0 again. There is no difference.

Scenario2: 40 damage attack, 0.5x armor multiplier, 15 flat pen. You have a cuirass with 20 armor which is hit. Mitigation = 20 - 15 = 5 * 0.5 = 2.5, so you take 37.5 damage. Arpen is reduced to 0, because 20 armor > 15 flat pen. If the change is made, it instead works like this: Mitigation is still 2.5 total, but arpen is reduced by 10 instead and 5 flat pen remains to apply to any other layers. There was enough armor to still have some mitigation against the attack, but despite that there was some armor penetration that gets passed to the next layer. This strikes me as wrong.

Scenario3: 40 damage attack, 0.5x armor multiplier, 25 flat pen. You have a cuirass with 20 armor which is hit. Mitigation = 20 - 25 = 0. All 20 of the armor is used up, leaving 5 flat armor pen remaining and the full 40 damage still incoming.  If the change is made, instead it works like this: Mitigation still = 20 - 25 = -5 * 0.5 = 0, but arpen is reduced by 10, meaning 15 arpen gets through. The difference is instead of reducing incoming armor penetration by 20, it's instead reduced by 10.

**Pull request merged**
