### PR TITLE
Tick tock

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: Infrastructure "Replace LUA mods"```

#### Purpose of change
LUA support is going to be removed soon, this is the first step of removing it.
Replaces the Zombie adjustment mods with jsonized equivalents.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
> 
> 
> What is the intended replacement for complex custom actions like the [manhack example mod](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/sample_mods/lua_manhack_iuse/preload.lua)?
> 
> The old discussion you linked to in Issue #20819 seems to have been deleted and the issue itself is locked for comments so I'm not sure where else to ask.

Eventually after stable `0.D` is released Lua will be fully removed from Cataclysm-DDA. There is no intention to replace anything except for a few mainline mods which can be easily recreated in C++ and little JSON.

**Comment by KITbutler** [comment]
> Eventually after stable `0.D` is released Lua will be fully removed from Cataclysm-DDA. There is no intention to replace anything except for a few mainline mods which can be easily recreated in C++ and little JSON.

So there will be no way of adding complex custom logic without putting the burden of compiling on the end-user? I am sure all of this was discussed somewhere but as I said the "official" link is dead. Considering the explanation given in the old issue:

> I can't afford to keep investing in LUA support on the basis of modders that don't contribute their changes back to the project. From the project point of view, "I need this for a private mod" is indistinguishable from, "I theoretically might need this, but I'm going to say I'm actually using it to make my argument stronger". If you need LUA support for a private fork of the game, it's on you to maintain it.

I am not sure I understand what an "official"/"non-private" mod is supposed to be either. Something like boats or statsthroughskills *clearly* requires additional lua/C++ code to work so what distinguishes those from regular "world options" like surrounded start if not the ability to add them as modular components **after** compiling the base game?

**Comment by ZhilkinSerg** [comment]
It is as simple as this: Kevin doesn't want to waste his time on maintaining Lua in his project.

More details info can be found here - https://discourse.cataclysmdda.org/t/lua-may-be-getting-axed-how-many-people-care/13488 and https://discourse.cataclysmdda.org/t/the-state-of-lua-in-dda/15291 (I guess first link is the dead one from #20819).

**Comment by ZhilkinSerg** [comment]
Current change to Lua has little to do with rules on which content can be mainlined, so same rules as yesterday. I personally prefer to use common sense.

You can get some things about current mainline lore here - https://github.com/CleverRaven/Cataclysm-DDA/issues/27452.

**Comment by TinkerWorX** [comment]
@KITbutler There's no such thing as "mod-only" content when it comes to C++. If the core game doesn't use it, it's not going to get merged as this will mean the developers have to maintain it even if it's not being used which is problematic.

**Comment by KITbutler** [comment]
@TinkerWorX Sticking to the sharknado example my line of thinking was that someone *might* implement gale-force winds fairly soon given the recent weather changes and aquatic zombies can be added anytime. So the "mod" portion would only add a persistent source of *circular* gales and spawn a load of zombie fish inside its AoE.

Actually StatsThroughSkills is an excellent example of a "mod" which has otherwise unused code. Since it *already exists* its future is fairly obvious but if it *didn't* what would be the correct approach for adding it?

**Comment by TinkerWorX** [comment]
@KITbutler Best approach is to relate whatever the mod does to a core mechanic to give it a reason to exist and then make it available through modding.

**Comment by dissociativity** [comment]
Given things are increasingly jsonized lately and so many avenues have been opened to modders, I expect this to continue and removing LUA at this state is warranted .

**Comment by KorGgenT** [comment]
#20819

**Pull request merged**
