### PR TITLE
Revert cramped vehicle changes for 0.H

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
We are still not happy with the way this feature works right now in experimental, see #74263 #74348
and there is no resolution in sight.  It seems like this feature will need heavy additional work before we're happy with it, as such it is not something we should be pushing in a stable release.

#### Describe the solution
This reverts this set of changes back to the original PR that introduced it.

### CODE REVIEW

**Comment by Procyonae** [comment]
How many errors does this produce for peeps with existing 0.H saves, I imagine a few of them at least would be easy to suppress

**Comment by kevingranade** [comment]
Hrrrm yea there are a few vehicle parts and some mutations, and one effect, we can maybe migrate those away.

**Comment by fairyarmadillo** [comment]
Why not leave Renech's code fixes in place and simply roll back the inventory and height based player volume calculation? Then no obsoletion would be needed. I can't imagine that would be more work than obsoletion.

Reverts will also cut many seat and bed capacities by 60 liters or more which may or may not cause errors when player vehicles full past capacity are loaded in.

**Comment by kevingranade** [comment]
Because I'm not launching into trying to fix this,  any additional edits bring further risks.

**Comment by KnifeFightBears** [comment]
> Why not leave Renech's code fixes in place and simply roll back the inventory and height based player volume calculation? Then no obsoletion would be needed. I can't imagine that would be more work than obsoletion.
> 
> Reverts will also cut many seat and bed capacities by 60 liters or more which may or may not cause errors when player vehicles full past capacity are loaded in.
> 
> Very Tall should be obsoleted and not brought back imo, as players were not really understanding that it was supposed to represent gigantism and the restrictions it imposed were confusing a few people. Very Short didn't have this problem.

I really like Very Tall and would be very disappointed if this was removed, for what it's worth. The size restriction issues associated with it only briefly bothered me and once I understood how the mechanics worked I really enjoyed the changes to gameplay that came with the trait. I mention this because I was the first person to complain about these gameplay effects when VT was first implemented and I very quickly got over it. I'm sorry for the off topic comment.

**Pull request merged**
