### PR TITLE
[WIP] [CR] Split Comestibles.json into smaller, more manageable files

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Infrastructure "Split comestibles.json into smaller, more manageable files"```
#### Purpose of change

When adding new comestibles to the game, it has become a chore to browse through the bloated `comestibles.json` at over 10,000 lines. By coming up with ways to separate comestibles (mostly by material) it will become much easier to find a specific comestible one is searching for.
#### Describe the solution

I have split `comestibles.json` into multiple files for ease of use
Outlined in the new file `GUIDE_COMESTIBLES.md` I have come up with a "priority list" for people to use in order to keep the comestible files as orderly as possible.
#### Additional Context
I will be breaking up this PR later, but this PR shows the intent of what I am going to do. I'll leave it like this for a bit, to give a chance for people to give their 2 cents on my choices of "category"

### CODE REVIEW

**Comment by cainiaowu** [comment]
These changes are big, I doubt anyone could review this properly.

**Comment by mlangsdorf** [comment]
Just leave this entire PR up as [WIP] or [DO NOT MERGE] and then have all the split-up PRs refer back to it.  I've been doing that for all my big multi-step PRs and it seems to work reasonably well (or at least no one has yelled at me to stop).

**Comment by KorGgenT** [comment]
I would like a suggestion from a maintainer about how small i should break this PR into, if even at all.

**Comment by KorGgenT** [comment]
all smaller PRs merged, making this one obsolete

**Pull request closed without merging**
