### PR TITLE
Add alternative black gunpowder recipe

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add alternative black gunpowder recipe which uses generic chemicals, based on old gunpowder recipe which was removed, as specific chemicals can only be scavenged currently.

### CODE REVIEW

**Comment by kevingranade** [comment]
Is there any indication that this recipe is similar to an actual recipe for black powder? From what I know, it's not even close, but I'm no expert.

**Comment by Darkyhard** [comment]
Black gunpowder is a mix of charcoal, potassium nitrate and sulfur. I couldn't think of better generic chemicals than those.

**Comment by Mecares** [comment]
This recipe seems odd to me, normally Black-powder is made out of roughly 75% KNO3 (oxidizer) + 10% Sulfur + 15% Charcoal as a quick Google Search told me. Your recipe currently is 11,5% NaOH (lye) + 11,5% KNO3 + 14% NH3 (ammonia)+ 63% Charcoal which sounds like far too much Charcoal and not enough KNO3. http://www.musketeer.ch/blackpowder/recipe.html suggests a recipe with only oxidizer and charcoal with 80% KNO3 and 20% Charcoal. Which could be done with 800 Oxidizer Powder and 1 Charcoal (0.8 kg and 0.22 kg) which should produce 200 Black Gunpowder (1kg)

**Comment by Darkyhard** [comment]
It says that it becomes harder to ignite a gunpowder if it has no sulfur in it, so you may want to add some.

**Comment by Mecares** [comment]
Oxidizer Powder is the same as potassium nitrate as far as i know. Sulfur is harder to find outside of labs currently the only idea i have right now are heads of matches but those are not made from pure sulfur anymore.

**Comment by Mecares** [comment]
I just checked and realized that the normal recipe in game is even worse it uses 7kg of ingredients to craft 0,25kg of black gunpowder. It uses 75 Saltpeter and 10 Sulfur and 15 Charcoal which would be right if the weight per unit would be the same but it is far off since weight is not standardized for chemicals. Corrected it should be more like 150 Saltpeter (0.78 kg) and 20 Sulfur (0,1 kg) and 1 Charcoal (0,22kg) for 200 Black Gunpowder (1kg)

**Comment by chaosvolt** [comment]
Yeah, that sounds....hnnng. Someone failed to account for the fact that all of those have different charges-per-stack.

**Comment by kevingranade** [comment]
Ok cool, I'm happy to be wrong about something from time to time :)

**Pull request merged**
