### PR TITLE
The great gunmod reorganization.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Our singular gunmod file is cluttered and annoying to deal with. Time to
make use of that new folder!

This doesn't add or remove anything other than files: all gunmods are
now listed in separate files depending on where they are attached, with
separate files for irremovable variants and debug/test objects.

### CODE REVIEW

**Comment by mugling** [comment]
Nice but could this wait until after #15288 as it's going to be a merge conflict with that?

How would you feel about adjusting the field ordering to match the others I've been doing for the other subdirs (eg. `id`, `type`, `name`, `description` ... see `bore.json`). It does take a few minutes per file but makes everything much easier to read? As everyone tends to copy and paste when creating a new JSON it's self-perpetuating to future items.

At a minimum items in alphabetical order by (`brass_catcher` before `shoulder_strap` etc) is pretty much essential to meet the original goal of avoiding future merge conflicts.

Finally, and easily set by regex, is there any objection to setting of tabspace 2 for the JSON data similar to the other files?

**Comment by mugling** [comment]
Actually disregard the above, I've got a 90% solution for automatically formatting the JSON data so I'll do a pull request to this PR and we could then merge after #15288?

**Comment by Rivet-the-Zombie** [comment]
I'm somewhat confused by what you mean; you want to use this PR in https://github.com/CleverRaven/Cataclysm-DDA/pull/15288, or you want me to use https://github.com/CleverRaven/Cataclysm-DDA/pull/15288 in this PR?

**Comment by mugling** [comment]
> I'm somewhat confused by what you mean

Sorry, that wasn't very clear. The changes in #15228 conflict with this PR.

I have a `jq` script that does the same job as your PR so I was proposing that we merge #15228 first and then use that script later to split `mods.json` into separate files.

**Comment by Rivet-the-Zombie** [comment]
Oh, yeah we can do that. I guess that pretty much invalidates this whole PR then?

**Comment by mugling** [comment]
Yes I suppose so. No disrespect intended

**Comment by Rivet-the-Zombie** [comment]
Not a problem; I'll just be glad to see them organized.

**Pull request closed without merging**
