### PR TITLE
A mod for generic guns.

### PR DESCRIPTION
**Pull request by SunshineDistillery**

### CODE REVIEW

**Comment by tyrael93** [comment]
"pistol ammo"?
How unamerican.

**Comment by narc0tiq** [comment]
Hm. That should be "handgun ammo", surely?

**Comment by tyrael93** [comment]
No, I mean the mod in itself. Universal ammo and generic pistol/guns sounds so bland.

**Comment by kevingranade** [comment]
If nothing else the names of the Rivtech ammos and guns are rather jarring since they're still highly specific.
I'm not going to hold it up on that basis though.

**Pull request merged**
