### PR TITLE
Riverside dwelling overhaul

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary

Content "Adds lakeside cabins, updates riverside dwellings"

#### Purpose of change

Continues roof project and my campaign against artificial forests.

`whaleys_house_river.json` is a bloated file filled with maps that haven't been updated in many years.

#### Describe the solution

I overhauled the riverside dwelling location.  I moved some of the variants - the cabins that seemed to be in use - into a new file, (`lakeside_cabin.json`), and created a new location: lakeside cabins.  I removed nulls, defined predecessor mapgen, palettized maps, improved readability, and added roofs for both locations.

I also changed the way riverside dwellings spawn.  Instead of generating in the middle of rivers as islands, now they'll spawn next to river banks.
kép

Lakeside cabins generate the same way boat rentals do.  They can generate on islands as well:
kép

#### Describe alternatives you've considered

None.

#### Testing

Debug-spawned all 6 lakeside cabins and 4 riverside dwellings.  No mapgen errors were spotted, and monsters, vehicles and items seem to spawn properly.  Then I surveyed the land for these locations, and they generate as expected: riverside dwellings no longer generate in the middle of rivers, and lakeside cabins face the right direction.

#### Additional context

<details>

  <summary>Screenshots:</summary>

**Lakeside cabins:**
kép

**Riverside dwellings:**
kép

</details>

### CODE REVIEW

**Comment by curstwist** [comment]
No specific comments on this except it looks fine.  
Wanted to extend by thanks for all the great mapgen fixes and updates you've been doing lately.

**Comment by LovamKicsiGazsii** [comment]
> No specific comments on this except it looks fine. Wanted to extend my thanks for all the great mapgen fixes and updates you've been doing lately.

Thank you so much!

**Comment by Maleclypse** [comment]
Is my browser failing to show me a file?  I don’t see a file with changes to riverside dwellings just that Whaley’s riverside dwelling file is completely deleted?

**Comment by LovamKicsiGazsii** [comment]
> Is my browser failing to show me a file? I don’t see a file with changes to riverside dwellings just that Whaley’s riverside dwelling file is completely deleted? Or are all the changes for riverside dwellings in the overmap special only?
> 
> Edit: Yeah so this PR currently only deletes riverside dwellings so I'm not sure why you are showing pictures of them in the screenshots or are you showing them that they aren't good and aren't easily salvageable? I'm also not sure how this is passing tests when all the riverside dwellings for the riverside dwelling terrain have been deleted. Clearly I'm misreading something.
> 
> Post edit: OK opened the file that github is showing as only having deleted lines and saw that you have fixed things in that file. Much apologies for all of this rambling.

It's incredible how much a file could down and still be left

**Pull request merged**
