### PR TITLE
[MoM] Drain overhaul + Power Maintenance overhaul, take 2

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Drain overhaul  + Power Maintenance overhaul"

#### Purpose of change

Drain is a little too predictable. The penalties accrue in a linear and easy fashion, and since the penalties are so harsh, Drain is always bad, there's never any reason to live with it, and you should meditate it away as soon as possible. It's not as interesting as as it could be.

Also, I thought of a way to make maintaining too many powers riskier.

#### Describe the solution

Make the effects of Drain more random. Drain now has only minor penalties and doesn't scale at all. However, having Drain causes a chance of other effects when you use you powers, escalating depending on how much Drain you have: headaches, small amounts of extra Drain, nosebleeds, weariness, sudden fatigue, muscle weakness, and eventually the chance of suffering overload even if you succeed at channeling your powers. But this is all things that _might_ happen, so there's never an immediate disadvantage to having some Drain.

For power maintenance, you can now safely maintain a number of powers equal to 1/4 of your Intelligence. If you go over that, your powers have a chance to be disrupted when you use other psionics, causing you to drop all your maintained powers and accrue some Drain. This makes maintaining more powers riskier, but if you're in your base and just want to have 6-7 utility powers on, it should be safe (unless you're a Teleporter who refuses to use the stairs, anyway).

Project PHAVIAN might have developed ways to make maintaining powers easier.

Also, when in strongly Nether-connected areas--the monster corpse, Research Facilities, the Physics Lab, crystal formations, or during portal storms--there's a chance that your powers can attract the attention of...something out there. At the moment, all this does is have a chance to give you nightmares. It'll be expanded in the future. Telepathic shield protects you from being noticed.  PORTAL_PROOF/DIMENSIONAL_ANCHOR do not, because there's a difference between passively existing on the borders of the Nether and actively using Netherum mathematics and expecting to go unnoticed. 

#### Testing

Drain mishaps can occur and the various different mishaps all showed up.  They're very rare at low levels of drain and get much more common at higher levels. Channels powers in a Nether location causes the Observed status, which causes nightmares. Maintaining too many powers can risk breaking them.

### CODE REVIEW

**Comment by Terrorforge** [comment]
> Drain is always bad, there's never any reason to live with it, and you should meditate it away as soon as possible.

The update sounds cool, but it doesn't really change this basic fact.

The obvious solution would be to apply some sort of bonus to increasing Drain alongside the penalties. This is in the spirit of the fiction, as overusing psychic powers is often shown to result in increasing power at the cost of control. My first thought was a simple Int bonus, but that seems inappropriate as it increases your level of control. A cost reduction for psychic powers could work, representing the power flowing more easily. What I'd _want_ to do is to increase the raw power level (damage, AoE, duration, etc.), but I don't know if that's even possible, especially not without tearing open every single power entry to scale everything with Drain. An Int bonus _would_ do this for most powers, but you'd need such a significant bonus that people would end up intentionally Draining themselves so they can sit on 30 int while training proficiencies.

You could also gate some of the stronger powers behind Drain; e.g. your mind just isn't permeable enough to Oubliette someone unless you've already got a significant amount of psychic lightning bouncing around in your head. I kind of like this option, because it creates a distinct gameplay difference between the cautious psychic who uses her powers responsibly to compliment her mundane skills and the Omega-level existential threat who flattens an entire shopping mall with her mind while cerebrospinal fluid dribbles out of her ears, and clear incentives to lean in either direction. I suppose this could even be a soft limit, if you made it so that Drain does increase your success rate at the cost of all those other penalties, which could make it so that higher-level powers are only possible (or at least practical) to cast with significant Drain.

If this is the sort of direction you decide to go in, Drain should probably be renamed to something like Overload, since it would represent something building up rather than being taken away.

> For power maintenance, you can now safely maintain a number of powers equal to 1/4 of your Intelligence. If you go over that, your powers have a chance to be disrupted

I just wanna say that I really like this mechanic, because it creates a very interesting risk-reward dynamic, particularly as int can drop as a result of pain. In the interest of that dynamic, it might be good if the penalty scaled with the difference between current and "intended" intelligence. E.g. having 3 effects active with 12 intelligence is perfectly safe, with 11 it's slightly risky, with 10 it's kind of dangerous, etc.

**Comment by Standing-Storm** [comment]
> The update sounds cool, but it doesn't really change this basic fact.

Nothing is going to change it for people who don't want any possible penalty in their permadeath roguelike (a significant amount of people, I expect). I'm reminded of all the people who are absolutely horrified at any possibility of negative mutations. 

The point here is to make Drain more like wounds or weariness, where as long as you're out doing things (psionically) the trend is for it to keep going up such that the player will need to decide whether to keep going and risk worse things happening or cut and run back to base to recover. A player in their base is never going to want to have any Drain, but they're never going to be cold or hungry or thirsty or have anything else bad happen to them if they can avoid it, and that's fine. 

The Drain-to-greater-powers (or something similar) is something I've thought of for the future (after I include more locations, or skill leveling speed slows down, or something), when I'll probably have a Tiering system for powers (off the top of my head, like Tier 1 is Difficulty 1-3, Tier 2 is Difficulty 4-6, etc), and then jumping up a Tier requires some kind of player action and choice. Like, you can stay at Tier 1 and be mostly safe (and probably have a cap on the amount of Drain you can get so it never gets too dangerous), or you can go meditate somewhere and unlock Tier 2, which means you can never have lower than X Drain. And so on with other Tiers.

Like, in my ideal world, if you stay at Tier 1, maybe the Drain vitamin has a maximum of 70 so it never gets that bad. You unlock Tier 2, and now the maximum is 120 and the minimum is 10. You unlock Tier 3, now the maximum is 150 and the minimum is 20. And other paths' tier unlocks also increase this but to a lesser extent. And yeah, in this case it would need a name change because people would go berserk if they saw "Drained" on their @ page 24/7. That makes it more like mutations, where it increases your power level, provides drawbacks, and there are certain things you can never take away.  This would be a good place for your idea about power scaling with Drain, too: Tier 1 you don't have enough connection to the Nether for it to matter, but Tier 2 and above? Galaxy brain (coming out your ears) time.  And then if the psion wants to lower their risk, they can do it the same way that Project PHAVIAN did--[with drugs](https://github.com/CleverRaven/Cataclysm-DDA/blob/7ae6d0f2166e8c2bef19dcb8aef8063ce6fbcfd5/data/mods/MindOverMatter/items/medical.json#L46).

(This also may require new infrastructure--I'm not sure it's currently possible to change the decay or limits of a vitamin at all in-game or to set it dynamically using math)

The reason I don't really want a charge-up system is then I'd probably need to make Drain less random, otherwise there would be complaints from people about needing to channel a bunch of powers they didn't want to use to get high enough Drain to use the big stuff and then meditate it all away once they got home so they would be safe, which people would definitely do in the same way they spent minutes every turn micromanaging their workers in Civilization so no production was ever wasted and then complaining about how much micromanagement the game "requires."
 
> I just wanna say that I really like this mechanic, because it creates a very interesting risk-reward dynamic, particularly as int can drop as a result of pain. In the interest of that dynamic, it might be good if the penalty scaled with the difference between current and "intended" intelligence. E.g. having 3 effects active with 12 intelligence is perfectly safe, with 11 it's slightly risky, with 10 it's kind of dangerous, etc.

At the moment what scales is the chance of all your maintained powers failing, which is based on the ratio between (Intelligence / 4) and number of powers, so every power past the limit increases the chance of failure. The odds are pretty low (ratio * 3) but it's checked every time you use a power and every time any maintained power requires maintenance.

**Comment by Terrorforge** [comment]
>Nothing is going to change it for people who don't want any possible penalty in their permadeath roguelike [...] The point here is to make Drain more like wounds or weariness

What if you don't have a grace period? If any amount of Drain, or even no Drain, still leaves you with _some_ chance of negative outcomes, you don't hit that psychological wall of "oh no! I have Crossed the Threshold!" that scares people into going home. If it's always on a sliding scale, it should become more about what risks you're personally comfortable with taking instead of pulling over the moment you see the "check engine" light

Incidentally, my favorite thing about MoM is that it allows me to worry less about managing these sorts of things. I don't have to agonize so much over being fully healed and optimally equipped at all times, because fuck you I can teleport.

> I'll probably have a Tiering system for powers (off the top of my head, like Tier 1 is Difficulty 1-3, Tier 2 is Difficulty 4-6, etc)

My gut feeling is that Tier 1 should be 1-4 because several iconic and useful powers are Difficulty 4 - but that's probably a strong indicator that 1-3 is correct. Tier 1 _should_ feel a little disappointing, or you won't be tempted to take the Faustian bargain.

> (This  also may require new infrastructure--I'm not sure it's currently possible to change the decay or limits of a vitamin at all in-game or to set it dynamically using math)

I think you could probably hack it with EOCs, but it would be... well, hacky. Run one every so often and set the vitamin to the minimum level if it's below. Probably build it into the Centering Meditation EOC as well so it actively tells you "no" when you try to get it below the minimum level. Ugly, and probably buggy.

> there would be complaints from people about needing to channel a bunch of powers they didn't want to use to get high enough Drain to use the big stuff and then meditate it all away once they got home

You _could_ have some sort of tool (drug, amplifier item, special crystal) that allows you to temporarily count as being higher Drain, but people would still do it if/when that tool isn't available and it takes the focus of the mod away from developing your psychic powers and towards a constant treasure hunt, which I don't like. I much prefer your idea where acquiring better powers requires accepting a minimum level of Drain.

**Comment by Terrorforge** [comment]
> Hmm. I prefer the idea that there is a safe stage, because then when you choose to go up to tier 2 you're consciously deciding "I want power so much that I am okay with my use of psionics never being completely safe again."

Okay yeah, that makes sense in the context of the tier system. Tier 1 lets you play in the kiddie pool and stay completely safe forever if you want to, or you can choose to step into maelstrom.

**Comment by Shibimon** [comment]
Sorry if is not exactly the scope of the PR but how many "meditations" you normally need to reduce drain?
I had a very intense use of MoM powers for a bit as i normally reduced it at a steady rate by just sleeping, and reached lvl3 drain, one meditation has reduced it to 2 and i have meditated a dozen times in the last 2 days with corresponding sleep and 0 use of powers and stays at 2, now called nether-attunement as i update regularly.
Im missing something?

**Pull request merged**
