### PR TITLE
yarn is unsalvageable

### LINKED ISSUE #61331: Cutting up 1 yarn results in multiple felt patches.
### Describe the bug

Cutting up yarn results in several felt patches which can be disassembly for more yarn, creating an infinite loop of extra materials.

### Steps to reproduce

1. Use any knife to cut up yarn which results in several felts patches

### Expected behavior

Dunno, i think yarn is supposed to turn into something else

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 5542e8a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
none

#### Purpose of change
fixes #61331

### CODE REVIEW

**Review by Maleclypse — CHANGES_REQUESTED** [review]
Yarn literally turns into felt.

https://support.lionbrand.com/support/solutions/articles/17000035404-felting-techniques#:~:text=Yarns%20made%20of%20wool%20(non,together%20and%20%E2%80%93%20voil%C3%A0%20%E2%80%93%20felt!

edit: if there is a problem it's that we may be turning it into too much felt? but if you can turn yarn into an equivalent weight of felt that seems like it would be correct.

**Comment by anoobindisguise** [comment]
> Yarn literally turns into felt.
> 
> https://support.lionbrand.com/support/solutions/articles/17000035404-felting-techniques#:~:text=Yarns%20made%20of%20wool%20(non,together%20and%20%E2%80%93%20voil%C3%A0%20%E2%80%93%20felt!
> 
> edit: if there is a problem it's that we may be turning it into too much felt? but if you can turn yarn into an equivalent weight of felt that seems like it would be correct.

The problem is is that in Cata Yarn is to Felt as Thread is to Cotton Patches. One felt disassembles into 50 yarns.  So it would be like cutting up threads and getting cotton patches. Those ratios may be entirely wrong though, because they seem to be missed by the tailoring rework.

**Comment by Nebnis** [comment]
> Yarn literally turns into felt.
> 
> https://support.lionbrand.com/support/solutions/articles/17000035404-felting-techniques#:~:text=Yarns%20made%20of%20wool%20(non,together%20and%20%E2%80%93%20voil%C3%A0%20%E2%80%93%20felt!
> 
> edit: if there is a problem it's that we may be turning it into too much felt? but if you can turn yarn into an equivalent weight of felt that seems like it would be correct.

I think you misunderstood the issue maleclypse, yarn turn into felt patch if you craft it not if you hacking up with your knife with butcher choice.  Anoob is right about giving yarn an unsalvageable tag much like thread can't be cut up with a knife and turn into cotton scraps.

> Yarn literally turns into felt.
> 
> https://support.lionbrand.com/support/solutions/articles/17000035404-felting-techniques#:~:text=Yarns%20made%20of%20wool%20(non,together%20and%20%E2%80%93%20voil%C3%A0%20%E2%80%93%20felt!
> 
> edit: if there is a problem it's that we may be turning it into too much felt? but if you can turn yarn into an equivalent weight of felt that seems like it would be correct.

Well i think i know what the problem of that issue was, according to your link, agitating yarn, (i assume with cutting?) turn into felt patches but felt patch should never go back to being yarn again. So what we actually can't do add a unsalvageable tag to felt patch. I think it already has but it isn't working?

**Comment by Maleclypse** [comment]
I think felt shouldn’t disassemble into yarn is the correct solution. Felt shouldn’t disassemble into anything.

**Comment by anoobindisguise** [comment]
Nebris has a separate PR they submitted to my fork; I asked them to just submit it here.

**Pull request closed without merging**
