### PR TITLE
Melee autoattack feature

### PR DESCRIPTION
**Pull request by Coolthulhu**
Simple yet effective de-tediumizer: picks the most dangerous hostile critter in melee range (including reach) and walks into it or reach-attacks it. For when you don't really care which one of the weak critters you want to hit as long as you're hitting any of them.

Doesn't walk towards enemies or use ranged weapons yet. If there are no targets in range, it will say so and do nothing.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This is a neat idea!

**Comment by pisskop** [comment]
so instead of seven you press a hotkey?  or instead of holding down 'f' to autoattack?

does it repeat?

**Comment by Coolthulhu** [comment]
> instead of holding down 'f' to autoattack?

Mostly like this, except you don't need a spear to do it.

Later on it will probably prioritize damaged targets and possibly also walk towards things (or wait if they are walking towards us).
Maybe even find good targets for AoE attacks (wide strike, impale).

**Comment by nikheizen** [comment]
This is great.
If you haven't picked a default keybinding, may I recommend 'tab'?

**Comment by Soyweiser** [comment]
> If you haven't picked a default keybinding, may I recommend 'tab'?
Shouldn't we use 'tab' for autoexplore?

**Comment by nikheizen** [comment]
@Soyweiser You are thinking of 'o'.
I would love to see autoexplore work in an infinitely sized world though!

**Comment by Coolthulhu** [comment]
> In seriousness, I like that it doesn't try to move.

I wouldn't make it move unconditionally. It would be controlled either by a switch (like safe mode) or by a global option.
Something like: "fallback: cancel/pause/chase".

**Comment by Coolthulhu** [comment]
> If you haven't picked a default keybinding, may I recommend 'tab'?

I was pretty sure I already set it to 'tab'. Looks like I updated the wrong file.

**Comment by mugling** [comment]
DCSS provides a somewhat similar example of how carefully designed automation (in their case autoexplore) can remove a lot of tedium. This feature is a good idea but needs to be very well designed and tested to avoid YASD.

**Comment by Soyweiser** [comment]
> DCSS provides a somewhat similar example of how carefully designed automation (in their case autoexplore) can remove a lot of tedium. This feature is a good idea but needs to be very well designed and tested to avoid YASD.

Yeah, the autoexplore in DCSS is great. But I don't think it is a good fit for CDDA. I think a 'move to map location x' System would be a better fit. Esp when you just let it stop when safemode triggers, or you get an interrupt "really step on that mine?" "you were hurt" "hungry becomes very hungry" etc. (Of course, making you travel while driving a vehicle or dragging something is a lot harder to implement).

**Pull request merged**
