### PR TITLE
Add ability to cut metal bars on windows with hacksaw

### LINKED ISSUE #13677: Impossible to cut metal bars on windows with hacksaw
The metal bars in prisons or sewers are cuttable, but metal burs on windows are not. This seems strange because in both cases it's the same metal bar.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27025355-impossible-to-cut-metal-bars-on-windows-with-hacksaw?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #13677.
Assuming there is just a regular, not reinforced, glass behind the bars.

Also, tweaks to cutting window w/bars and window frame w/bars with oxytorch.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Should cause an alarm on attempt - no free sawing.
Alternatively don't allow sawing until the window is broken.

**Comment by Coolthulhu** [comment]
Also, it seems that you can saw the alarmed windows, but not the ones with glass broken.

**Comment by Night-Pryanik** [comment]
>Should cause an alarm on attempt - no free sawing.
Alternatively don't allow sawing until the window is broken.

I always thought that alarm is the breaking detector mounted on the glass, and the bars is in front of the glass. Carefully sawing the bars (not touching the glass) won't set off the alarm.

**Comment by Rivet-the-Zombie** [comment]
>I always thought that alarm is the breaking detector mounted on the glass.

I agree that this makes a lot of sense.

**Pull request merged**
