### PR TITLE
Use maps on all zlevels so they actually reveal things.

### LINKED ISSUE #24919: Survivor's Map doesn't reveal when used on different z-levels
The title pretty much describes this. I had trouble reproducing this since map gen would just never spawn stuff that had multiple z-levels but its done and dusted.

image

This is an image of the town I had used to reproduce this. I used a survivor map on the 2nd floor of this nice mansion and it revealed nothing new.

OS Windows 10
Version 0.C-30680-gb8ef478
Tiles
Mods DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Bugfixes "Use maps on all zlevels so they actually reveal things."```  

#### Purpose of change
Fixes #24919

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Won't it break maps which should reveal things on Z-levels other than 0?

**Comment by ZhilkinSerg** [comment]
What if we add new iuse action property which will define which z-level map is working on?

**Comment by OzoneH3** [comment]
As a compromise I could reveal on all overmaps. That would allow future maps to work regardless of zlevel (Subway/sewer map or something) without adding an unused feature.

**Comment by ZhilkinSerg** [comment]
> As a compromise I could reveal on all overmaps. That would allow future maps to work regardless of zlevel (Subway/sewer map or something) without adding an unused feature.

Yeah, that's much better.

**Pull request merged**
