### PR TITLE
Rename `No Fungal Growth` mod to `Slowdown Fungal Growth`

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
People always think No Fungal Growth means total removing fungal from the game, which is not. Of course no one read the description also.
#### Describe the solution
Rename the mod name in attempt to highlight this
#### Describe alternatives you've considered
Drop it
#### Additional context
There is probably a better name we can use, but i can't find it

### CODE REVIEW

**Comment by Karol1223** [comment]
Why not just 'no exponential fungal growth? like in the description? I feel like that explains it perfectly

**Comment by GuardianDll** [comment]
Because people are not aware fungals has ability to spawn more fungaloids exponentialy, for them "no grow" means "this shitty terrain do not spawn around"
and when they see it indeed spawn, they don't think "hey, i guess i read the mod info wrong", they go to our discord and ask "ayo wtf no fungal mod doesn't work"? (btw mod id should be changed also, but its kinda another pain in ass to deal with)

**Comment by NetSysFire** [comment]
Any reason this is still a mod and not in the base game?

**Comment by GuardianDll** [comment]
We want to improve the fungal grow in the future, and remove this mod entirely, but the task seems to be extremely complicated, see #52242

**Pull request merged**
