### PR TITLE
Complete bio_solar removal

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Content "Complete bio_solar removal"```

#### Purpose of change
Solar panel actually lives under the bn_bio_solar id
bio_solar has been removed from saves by #23317 which was more than a year ago
This removes the remaining references to bio_solar

#### Describe the solution
Search for bio_solar and remove it

### CODE REVIEW

**Comment by Maleclypse** [comment]
So I know the CBM is still in Aftershock are there any lines from what you are removing that I need to carry over to Aftershock to keep it working there?

**Comment by anothersimulacrum** [comment]
It's `bn_bio_solar` in Aftershock, shouldn't need to do anything.

**Comment by Maleclypse** [comment]
I was hoping that was the case. Thanks!

**Comment by ZhilkinSerg** [comment]
There is a reference to `bio_solar` somewhere in savegame code and that is probably what fails tests on CI.

**Pull request merged**
