### PR TITLE
clang-tidy check to ensure data is (de)serialized

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Infrastructure "clang-tidy check to ensure data is (de)serialized"

#### Purpose of change
When adding a new feature, it's easy to forget to serialize the new data members.  And such a mistake is not likely to be caught in testing because people usually don't save and load much during testing.

This happened to me for example in #49980 (although I fixed the issue before it was merged).

To save future contributors from similar mistakes, we'd like an automated check to look for such errors.

#### Describe the solution
Add a clang-tidy check that analyzes each (de)serialize function and flags each data member not mentioned in it.

The warnings can be suppressed in the usual way by adding `NOLINT(cata-serialize)` to the data member.  They can also be suppressed for a particular function by adding `CATA_DO_NOT_CHECK_SERIALIZE` somewhere in that function.

These supressions help to highlight things which are not serialized, which also serves a documentary function.

This picked up lots of issues, which I tried to resolve as best I could:
* The majority were simply suppressed.
* Some seemed like they ought to be saved, so I made them so.  Mostly these were in `activity_actor` stuff or `vehicle`.
* A couple of fields were completely unused, and I just deleted them.
* One field (`ebooksave_activity_actor::time_per_page`) was constant, so I made is a `static constexpr` field instead.
* Some fields were serialized via getter functions rather than directly, so the check couldn't see that they were.  I removed this indirection.
* The serialization functions for `uistate` were un-templated (they should also be moved to the cpp file but I didn't want to clutter this PR further by doing that here).

This entailed:
* Adding `enum_to_string` support for a couple more enums.

#### Describe alternatives you've considered
Could extend this to `load` functions also, but I think this sort of error is much less likely there, so probably no need.

#### Testing
This is unfortunately something that's just not covered by the unit tests.

I loaded and saved a few games.  Nothing obviously went wrong.  Most of these newly serialized items are only relevant in corner cases, like an autosave that happens during moving a stack via AIM.  I didn't attempt to recreate the necessary conditions.

One thing I did verify is that the screen offset that happens when you're driving a vehicle fast is now saved when it previously wasn't.

#### Additional context
It's likely I've broken something here, but hopefully it's a net win, especially taking into account future bugs avoided.

### CODE REVIEW

**Comment by KorGgenT** [comment]
I do remember writing a test for serialization and deserialization of spell_type. It's a bit hard for that test to pick up on new members though

**Comment by actual-nh** [comment]
How difficult would it be for the unit tests to include saves and loads?

**Comment by jbytheway** [comment]
> How difficult would it be for the unit tests to include saves and loads?

It's something we should definitely work towards. Testing serialisation of individual classes is pretty easy. Saving the entire game state might be trickier. There's also the question of what you'd test for exactly.

As a first step, simply saving and loading to verify that we don't have a fatal save corruption big would be a good start. I'd hope that wouldn't be too bad, but it's hard to predict. I encourage anyone who feels inclined to give it a try!

**Comment by actual-nh** [comment]
> As a first step, simply saving and loading to verify that we don't have a fatal save corruption big would be a good start. I'd hope that wouldn't be too bad, but it's hard to predict. I encourage anyone who feels inclined to give it a try!

So essentially call game::serialize( iostream ) with an appropriate open iostream, close it, reopen, and call game::unserialize( iostream )?

**Pull request merged**
