### PR TITLE
Fix HK 12mm ferromagnetic Ammo flags

### LINKED ISSUE #18339: H&K 12mm Railgun Ammo should not have "powder" flag and "cookoff" effect
As far as i understand the rail-gun ammo is just a slug of ferro-magnetic metal that gets accelerated by magnetism and not by a gunpowder propellant.

### PR DESCRIPTION
**Pull request by Mecares**
Removes powder flag from material and cookoff  flag from effects since it is a
ferromagnetic projectile accelerated by magnetism and not by an
explosive propellant.
Fixes #18339

### CODE REVIEW

**Comment by Mecares** [comment]
That is weird i can not really find anything that would qualify as a stray character at the start of the file just the bracket that all similar files also have.

**Comment by mugling** [comment]
What editor are you using?

**Comment by Mecares** [comment]
Notepad++

**Comment by mugling** [comment]
Both git and the game binary think there is a change at the start of the file. No problem with your changes, just that. Possibly byte ordering mark? Try a new branch in just regular notepad

**Comment by Mecares** [comment]
Git shows the change at the start of the file with a new branch using notepad for the changes, too.

**Comment by mugling** [comment]
Did you start a **new** branch from master

**Comment by Mecares** [comment]
Yep directly from CleverRaven/Master

**Comment by BorkBorkGoesTheCode** [comment]
> Yep directly from CleverRaven/Master

Did you edit your copy of master?

**Comment by Mecares** [comment]
Okay i experimented a bit and it even happens if i only open  ammo.json with notepad and save without changing anything, and changing other files works fine. But only with Notepad or Notepad++, Wordpad seems to work without problem. Strange.

**Comment by illi-kun** [comment]
untitled

**Comment by illi-kun** [comment]
I'm not sure but try to play with EOL conversion (this option is available in Notepad++ in ```Edit``` menu).

**Comment by BorkBorkGoesTheCode** [comment]
Finally I know what was causing this bug.

**Pull request closed without merging**
