### PR TITLE
Stone and shakcles pt 2

### PR DESCRIPTION
**Pull request by pisskop**
finishes up json mapgen modifiying.

The objective is in many cases to add ambience and variety, but in the cases of electronics stores or gun stores it prevents using a car to quite such efficiency.

Adds an itemgroup for human remains of various meaty and fleshy compositions.

### CODE REVIEW

**Comment by pisskop** [comment]
The s_gun ids are scattered over several files and arent listed alphabetically.

**Comment by pisskop** [comment]
Here we are:  top-right

<a href="http://imgur.com/9NoSMct"></a>

**Comment by Coolthulhu** [comment]
Json errors

**Comment by pisskop** [comment]
Aye.  Apparently there isnt an option to liberally scatter bodies onto the ground.

So theres an item_group for that.

**Comment by Coolthulhu** [comment]
JSON error.
Test your PRs. Something basic enough to be detected on load is OK once in a longer while (mistakes happen to everybody), but that goes well beyond "once in a while".
It looks like you're just pushing the JSONs through the online github interface, without checking if it works even once.

**Comment by mugling** [comment]
I like the idea of differing walls for buildings but there are some significant concerns with these PR's.

Firstly they appear to duplicate JSON mapgen for each building in it's entirety. Such duplication imposes a very high maintenance penalty and would no doubt be fertile source of future errors.

Secondly @Coolthulhu was correct in that you're introducing new JSON style problems (#17533). It isn't acceptable to dismiss those with *'it will not do so*' and *'suit yourself'*. It is sometimes acceptable to defer fixes to future PR's but not for something so trivial as the issues highlighted.

Thirdly you have you have to test your PR as expecting the merge tester to do so is unreasonable. Infrequent mistakes are understandable but if they become to common then you'll find the number of developers willing to test your PR's falls off pretty quickly.

**Comment by pisskop** [comment]
As mentioned in #17533, the building files are outdated, and need to be updated before these changes can be made.


If the current method of adding building material shifts is too intensive, and in it kind of is, than perhaps a way of specifying whole-symbol conversions would work.  The current method of adding new materials to a symbol in json allows for tile-by-tile chances, instead of a single roll determining the vale of the symbol.

This can be reopened once somebody has updated the syntax of the mapgens.

**Pull request closed without merging**
