### PR TITLE
Place wished for liquids in containers by default

### PR DESCRIPTION
**Pull request by TheStoneWolf**
#### Summary

SUMMARY: Interface "Place wished for liquids in containers by default"

#### Purpose of change

When wishing for liquids through the debug menu, all liquids are by default uncontainerized - meaning that they will fall onto the ground when wished into the game. More often than not though, that is not a desirable option which neccessitates having to press 'f' to put it into a container. This can get quite tedious if many liquids are to be wished for as when debugging is taking place f.ex.

#### Describe the solution

All wished for liquids will by default be in a container, but can, as before, become uncontainerized by pressing 'f'.

#### Describe alternatives you've considered

For this specific problem I do not see any other solution. There will always be different implementations though.

#### Testing

I wished for different liquids to see if they would by default be in a container. Also pressed 'f' to wish uncontainerized liquids into the game.

#### Additional context

I have been thinking about doing the same thing for gases, but since I'm not very experienced with the gases of CDDA I felt it best to consult with you all to see if that is desired. Are there even any gas items to put in a container?

### CODE REVIEW

**Comment by KorGgenT** [comment]
hold up - if you wish for a liquid through the debug menu right now, it will try to place it in a watertight container you already have. maybe you want to do this.

**Comment by TheStoneWolf** [comment]
@KorGgenT My bad, I completely forgot to think about that case. That can still be done though by wishing it in uncontainerized.

The question is though, what is desired most often - filling your already existing containers vs getting the liquid in a new container? When debugging, I think the later is most often desired since you most often start the game with no or few containers to fill. When it comes to the players who use the debug menu to 'cheat', I'm not so sure what would be the best default. Any thoughts?

**Comment by KorGgenT** [comment]
for debug options, you don't need to think about the UX for players who want to use it to cheat. It's the people who are debugging the game that use this feature.

**Comment by KorGgenT** [comment]
but as long as you can still switch back and forth in the debug menu i have no issue with this.

**Comment by TheStoneWolf** [comment]
Well, if we don't have to think about them, then I'm sure it will be a net positive. Yeah, you can still make it not come in a container as you could before.

**Pull request merged**
