### PR TITLE
[Interface] sidebar-mobile

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Interface "sidebar for mobile users"

#### Purpose of change
Heavily modified sidebar. Mostly for mobile users that use Terminus font (shipped with the game).
Relies on the font (but some other fonts can be used too). Uses as less rows as possible, second guide is to be as compact as possible. Adds as much indicators as possible.

#### Describe the solution
Expected size of fixed data - 25 lines, 41 width.
Two main colors defined by t_border and t_label widget templates.
First letter of the widget defines it functionality (some widgets are like existing ones but with small quirks):
- t - template
- l - label
- i - indicator
- a - layout Arrangement
- w - widget
- r - sidebar Row
Labels used only for sidebar rows.

#### Testing
default colors / dark scheme / vintage scheme
image

#### Additional context
TODO:

- [ ] add different bg color for replaced limbs (#57426)
- [ ] add descriptions (#59462) and variants for the rows
- [x] lint it obviously
- [x] change some width to actual numbers (need issue #58991 to be solved, probably #59454 is a solution)
- [x] change vertical dividers to the space instead of vertical line
- [x] add horizontal space dividers
- [x] change compass to alternate version (?)
- [x] rearrange martial arts, wielded item and compass
- [x] change time to sundial if no WATCH weared (need issue #58684 to be solved, (#59442))
- [x] show moon phase only at night (need issue #58684 to be solved, probably #59442 is a solution)
- [x] change "broken" and "splinted" indicators for head and torso to something more meaningful (stunned / anemia)
- [x] change bionic power to 5 segments indicator (need variable "u_val": "power_percentage" to be accessible) #59475
- [x] add widget about power balance (#59368)

### CODE REVIEW

**Comment by mlange-42** [comment]
> change time to sundial if no WATCH weared

This can already be solved by the new text var `sundial_time_text` / widget `sundial_time_desc_no_label`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2b29aca4b8c7923eca70883c8d418185a9fdf807/data/json/ui/time.json#L19

**Comment by vetall812** [comment]
> > change time to sundial if no WATCH weared
> 
> This can already be solved by the new text var `sundial_time_text` / widget `sundial_time_desc_no_label`:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/2b29aca4b8c7923eca70883c8d418185a9fdf807/data/json/ui/time.json#L19
> 

Yeah, sundial widget exist. But it doesn't change to actual time if you have a watch on you.

**Comment by mlange-42** [comment]
> Yeah, sundial widget exist. But it doesn't change to actual time if you have a watch on you.

This one does (it is quite new and was introduced here: #59182). Check the "structured" sidebar.

Drop everything with `WATCH`:

grafik

Pick up wrist watch:

grafik

**Comment by vetall812** [comment]
> > Yeah, sundial widget exist. But it doesn't change to actual time if you have a watch on you.
> 
> This one does (it is quite new and was introduced here: #59182). Check the "structured" sidebar.

Nice! Thank you!

**Comment by vetall812** [comment]
Well, it is ready to be published!

**Pull request merged**
