### PR TITLE
Remove obsolete no_x mods

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: None

#### Purpose of change
Remove mods that are no longer supported. I think it's been long enough that we shouldn't need to worry too much about old saves using these.

#### Describe the solution
`git rm -r data/mods/No_*`
`git rm -r data/mods/no*`
(then restore the non-obsolete ones)
Remove the removed mods from the mod test blacklist.

#### Describe alternatives you've considered
Waiting longer. It's entirely possible this is too early.
Adding these mods to the mod migration list. I have elected to not do this, to make it easier on people continuing to use these mods out of tree.

#### Additional Context
I'd appreciate it if github would stop changing the name of the PR when I refresh, if it doesn't change the rest of the PR text.

### CODE REVIEW

**Comment by Angelin01** [comment]
I'm sorry to necro a MERGED pull request from May, but I can find no other discussion of this anywhere, so I must ask. If my Google-Fu failed me and there is some discussion of this anywhere else, please point me to it, I'd be grateful.

What was the reason for these removals? What I've read in many other discussions and threads about these was "they're marked as obsolete, not removed, if you wanna play with the unsupported mods simply reenable them". Now, with these, the only way I could find of getting them was to actually get them from a previous release. If there is another way, I couldn't find it easily.  

Now, if the argument is going to be "they were not maintained", I should simply state that a tool that is working perfectly does not need to be changed. If you have a ball and it's purpose is to roll, and when you push it, it rolls, then you don't need to fiddle with it.

Let me use an example: the No Revive mod for zombies. I saw that it was "merged" with the classic zombies. What if I still want the other zombie types, but just don't want to go around destroying the corpses? If the No Revive mod accomplished that perfectly and was not hindering anything, I see no reason to change it or remove it, it does exactly what it says. Much like a finished statue, it could be left alone. Now, I can understand if this was hindering progress, let's say you wanted to change the modding system and noone wanted to update these old mods, but I haven't actually seen anything like that from my quick looks at the 0.F branch.

Surely, with some simple things like these I could easily fix them for my own game, but other folks may not be as tech savvy, which is the whole reason I'm asking about these changes here. I'd appreciate any clarifying info.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/IN_REPO_MODS.md

**Comment by Angelin01** [comment]
> While it may be counterintuitive, simply having a mod in the repository increases maintenance burden for the team, even for the people who don't use the mods itself.

See, but that is why I need to ask. Why do many of these even need "maintenance"? I've been searching on Reddit and the forums and all I get from people are suggestions of "oh, just readd the mod", and they copy paste the old code that they had and tell people to put it in the correct folder.

Alternatively, if they really must be removed, could we possibly provide an easier way to get them, a "legacy obsolete mods download" per say, or, alternatively, at least a list somewhere and small instructions on how to get them (download an old release and copy them over) instead of simply having to scour through GitHub commits and PRs, asking on forums what to do? It would certainly help with the confusion I'm seeing on many places. This entire comment was inspired by a friend being confused on why a few of the mods he used to play with weren't there and he not finding any concrete info on it, being confused why he couldn't unmark them "obsolete" on the files, like many pointed, because they were just missing, and me trying to help.

**Comment by ZhilkinSerg** [comment]
I believe you better seek help from whomever supports these mods now. The only thing I can advice you here is to use any stable version (`0.D` or `0.E`) which still contains these mods which will be removed in stable `0.F`.

**Comment by anothersimulacrum** [comment]
The specific purpose this PR is removing dead data. 
These mods were marked obsolete because we have no interest in maintaining or hosting them, which having some guide or similar like you suggested explicitly defeats the purpose of.
I'm sorry for you friends confusion, but I'm not sure what could be done to avoid that.

**Comment by Night-Pryanik** [comment]
Simply put, devs have no interest in having these mods in mainline. Most of them aren't "obsolete" per se, they are working just fine, it's just a matter of taste. Devs dislike the mod - devs delete the mod from the mainline.
  
From the other side, devs have no interest (and/or free time) to implement and maintain a separate repository for all the non-mainlined mods. So for now if someone wishes to get a non-mainlined mod, they should make an effort to find the mod they want themselves.

**Pull request merged**
