### PR TITLE
Forge item to appliance

### LINKED ISSUE #61585: Electric forge should cease being battery powered and move to appliance
### Describe the bug

Even a heavy battery wouldn't really make sense for an induction forge setup it seems likely.

### Steps to reproduce

Find electric forge, see it takes battery, marvel at it's efficiency.

### Expected behavior

We have appliances now that can more reasonably make sense for some items. This is one such item.

### Screenshots

_No response_

### Versions and configuration

Current experimental until this is fixed or deemed not needed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Updates to forge item and appliance"

#### Purpose of change
The portable electronic forge was battery powered, but often required more power than batteries could be provided. Now that it can be installed as an appliance, we no longer need this battery functionality. Additionally, this removes the vehicle forge item as running a forge inside an enclosed vehicle is impractical and extremely dangerous at best.

#### Describe the solution
Removes the battery from the forge item, making it usable as an installed appliance. Also removes the vehicle forge.

#### Describe alternatives you've considered
None.

#### Testing
Spawned electric forge item, installed as appliance.

#### Additional context
Will resolve #61585.

### CODE REVIEW

**Comment by KHeket** [comment]
Dont do this. If you make electrnic forge only as an apllience - it will make players a lot of unneedable actions. As mentioned in https://github.com/CleverRaven/Cataclysm-DDA/pull/61157 "turning off the mechanic is not the best way to improve this mechanic". For me it was much more comfertable to reaload batteries in electronic forge rather than placing each time to start crafting. You can craft for a lont time, for example, steel spear, then kill some zombies/drive by car to anather place, and then contine crafting, without needed to waste time and actions to place down forge, connect to car/electrical network, and then dismantle it. This change is not improving anything, only make all worse. "extremely dangerous" - world of cataclysm is filled with extremely dangerous, instaling bonics extremely dangerous, mutation, full storage of grenades and nuke epxlosives, but they are not going to be deleted

**Comment by Drew4484** [comment]
> Dont do this. If you make electrnic forge only as an apllience - it will make players a lot of unneedable actions. As mentioned in https://github.com/CleverRaven/Cataclysm-DDA/pull/61157 "turning off the mechanic is not the best way to improve this mechanic". For me it was much more comfertable to reaload batteries in electronic forge rather than placing each time to start crafting. You can craft for a long time, for example, steel spear, then kill some zombies/drive by car to anather place, and then contine crafting, without needed to waste time and actions to place down forge, connect to car/electrical network, and then dismantle it. This change is not improving anything, only make all worse. "extremely dangerous" - world of cataclysm is filled with extremely dangerous, instaling bonics extremely dangerous, mutation, full storage of grenades and nuke epxlosives, but they are not going to be deleted

Would you light a cooking fire in the back of your van? How about a forge that's heated to 900°C and maintains that temperature for several hours?

**Comment by KHeket** [comment]
> Would you light a cooking fire in the back of your van? How about a forge that's heated to 900°C and maintains that temperature for several hours?

Bad way to see only cons and dont use imagination to solve it. You can simply make ventilation, to solve problem with heating. Also, electric forge dont use fuel, like coal, gas or something like this, so there is no promblem with high heat gas, wihich cannot be solved with ventilation
There is also no need of air for it, beacouse of induction. And you can simpli made it closable to prevent heated air spreading
So there is no need to make forge only as appliance, becouse we have exaples of little forges in real life
As example - I simply googled very little metal melter, which can have temperature up to 1100℃ and its also closable and have no need of ventilation
https://www.ebay.com/itm/324475000084
<details>
  <summary>image of forge</summary>

  image
</details>


And there is no need to tell, that in world of laser guns, bionics, exosceletons, aliens, mutants and mutations, autoturrets and ather things easily can be created such simple construction

**Comment by anothersimulacrum** [comment]
When electric forging costs are vaguely sensible, you would find it extremely inconvienient to use battery-forges. This will be sooner than you think.
That aside from the fallacious argument about other things in the world.

**Comment by KHeket** [comment]
> When electric forging costs are vaguely sensible, you would find it extremely inconvienient to use battery-forges. This will be sooner than you think. That aside from the fallacious argument about other things in the world.

So, deleting battetry forge is bad choice, as I mentioned early, "turning off the mechanic is not the best way to improve this mechanic". Rather than removing battery forge, its much more better to make portable forge as an item, which can be plugged to the car without placing it like appliance, simular how the character connecting to car with cable via cable charger system cbm, or make it only recharchable by accumulator, not by heavy battery

**Comment by anothersimulacrum** [comment]
No thanks.

**Comment by Drew4484** [comment]
> > Would you light a cooking fire in the back of your van? How about a forge that's heated to 900°C and maintains that temperature for several hours?
> 
> Bad way to see only cons and dont use imagination to solve it. You can simply make ventilation, to solve problem with heating. Also, electric forge dont use fuel, like coal, gas or something like this, so there is no promblem with high heat gas, wihich cannot be solved with ventilation There is also no need of air for it, beacouse of induction. And you can simpli made it closable to prevent heated air spreading So there is no need to make forge only as appliance, becouse we have exaples of little forges in real life As example - I simply googled very little metal melter, which can have temperature up to 1100℃ and its also closable and have no need of ventilation https://www.ebay.com/itm/324475000084
> 
> image of forge
> And there is no need to tell, that in world of laser guns, bionics, exosceletons, aliens, mutants and mutations, autoturrets and ather things easily can be created such simple construction. And also there is lots of results in google by "electric metal melter", lots of them is also very little and portable

That's a great tool if you want to melt some scrap into a lump, but it's absolutely not a forge. If you think you can find a justifiable forge that can be used inside a vehicle, show some research.

**Comment by KHeket** [comment]
> > > Would you light a cooking fire in the back of your van? How about a forge that's heated to 900°C and maintains that temperature for several hours?
> > 
> > 
> > Bad way to see only cons and dont use imagination to solve it. You can simply make ventilation, to solve problem with heating. Also, electric forge dont use fuel, like coal, gas or something like this, so there is no promblem with high heat gas, wihich cannot be solved with ventilation There is also no need of air for it, beacouse of induction. And you can simpli made it closable to prevent heated air spreading So there is no need to make forge only as appliance, becouse we have exaples of little forges in real life As example - I simply googled very little metal melter, which can have temperature up to 1100℃ and its also closable and have no need of ventilation https://www.ebay.com/itm/324475000084
> > image of forge
> > And there is no need to tell, that in world of laser guns, bionics, exosceletons, aliens, mutants and mutations, autoturrets and ather things easily can be created such simple construction. And also there is lots of results in google by "electric metal melter", lots of them is also very little and portable
> 
> That's a great tool if you want to melt some scrap into a lump, but it's absolutely not a forge. If you think you can find a justifiable forge that can be used inside a vehicle, show some research.

You sad about forge which can melt up too 900°C, I showed you cheap variant, which can heat up to 1100°C. Electrig forge have only one use - melt metal. There is lots of metal melters in internet like https://www.amazon.com/LEE-PRECISION-90021-Melter-Grey/dp/B00162UONY And its need only 500 watts AC (simular to heavy batterys)
And, obviosly, I googled only variants for homemade. But for factory or professional crafters I shure there is more specific and usefull portable melters, and, obviosly, in world of LASERS, ROBOTS, labs, radiation food facilitys and other sci-fi thing there techologys MUCH MORE better, then in our time. Electric forge is very-very rare loot in world of cata, and often you can fing it ot pump stations or some factory-like structures. So, they are costs much more than variants which I showed to you
You asked me for research - but if you delet something for realism and make game worse and more uncomfortable - you must have some analog and examples in real life and add this to your pr. Not only "I think its dangerous and must be deleted"

**Comment by Drew4484** [comment]
> > > > Would you light a cooking fire in the back of your van? How about a forge that's heated to 900°C and maintains that temperature for several hours?
> > > 
> > > 
> > > Bad way to see only cons and dont use imagination to solve it. You can simply make ventilation, to solve problem with heating. Also, electric forge dont use fuel, like coal, gas or something like this, so there is no promblem with high heat gas, wihich cannot be solved with ventilation There is also no need of air for it, beacouse of induction. And you can simpli made it closable to prevent heated air spreading So there is no need to make forge only as appliance, becouse we have exaples of little forges in real life As example - I simply googled very little metal melter, which can have temperature up to 1100℃ and its also closable and have no need of ventilation https://www.ebay.com/itm/324475000084
> > > image of forge
> > > And there is no need to tell, that in world of laser guns, bionics, exosceletons, aliens, mutants and mutations, autoturrets and ather things easily can be created such simple construction. And also there is lots of results in google by "electric metal melter", lots of them is also very little and portable
> > 
> > That's a great tool if you want to melt some scrap into a lump, but it's absolutely not a forge. If you think you can find a justifiable forge that can be used inside a vehicle, show some research.
> 
> You sad about forge which can melt up too 900°C, I showed you cheap variant, which can heat up to 1100°C. Electrig forge have only one use - melt metal. There is lots of metal melters in internet like https://www.amazon.com/LEE-PRECISION-90021-Melter-Grey/dp/B00162UONY And its need only 500 watts AC (simular to heavy batterys)
> And, obviosly, I googled only variants for homemade. But for factory or professional crafters I shure there is more specific and usefull portable melters, and, obviosly, in world of LASERS, ROBOTS, labs, radiation food facilitys and other sci-fi thing there techologys MUCH MORE better, then in our time. Electric forge is very-very rare loot in world of cata, and often you can fing it ot pump stations or some factory-like structures. So, they are costs much more than variants which I showed to you
> You asked me for research - but if you delet something for realism and make game worse and more uncomfortable - you must have some analog and examples in real life and add this to your pr. Not only "I think its dangerous and must be deleted"

"Electrig forge have only one use - melt metal." You need to do some basic research on what a forge is, how it works, and what it's used for. Or, just say "I don't like this change" so we can all move on.

**Comment by anoobindisguise** [comment]
due to variable efficiencies when cooking food I found that it was roughly 4u charcoal to 25u of kJ assuming induction cookware; is there a plan to increase the electric forge's power usage accordingly too? I assume it's an induction (non induction was 35kJ per 4u charcoal)

**Comment by Drew4484** [comment]
> due to variable efficiencies when cooking food I found that it was roughly 4u charcoal to 25u of kJ assuming induction cookware; is there a plan to increase the electric forge's power usage accordingly too? I assume it's an induction (non induction was 35kJ per 4u charcoal)

The current (haha) issue is with the toolset for blacksmithing_standard in that's the charges there can't be filled by the appliance since it doesn't have a battery. If I can get that working, I'd be happy to change the numbers for that toolset (and presumably the scattered items that don't use the toolset).

**Comment by KHeket** [comment]
> "Electrig forge have only one use - melt metal." You need to do some basic research on what a forge is, how it works, and what it's used for. Or, just say "I don't like this change" so we can all move on.
And what is forge in your understanding?
"This is a portable electric metalworking forge, powered by batteries. Combined with the right tools, you could use this for metalworking. With a little mechanical know-how, you could probably even convert it to run directly off a vehicle's power system."
By the discription and its ingridients - its metal furnance for metal melting

**Comment by Dan1ss1mo** [comment]
didn't fiddle with appliance system at all, but as far as i understand i could just place my forge outside and plug it to my car, is it right?

**Comment by Drew4484** [comment]
> didn't fiddle with appliance system at all, but as far as i understand i could just place my forge outside and plug it to my car, is it right?

Absolutely. Appliances don't care about where the power comes from, just that it has enough. A big issue with the battery was that it often was insufficient to complete a crafting task, requiring reloading mid-project.

**Comment by Dan1ss1mo** [comment]
> > didn't fiddle with appliance system at all, but as far as i understand i could just place my forge outside and plug it to my car, is it right?
> 
> Absolutely. Appliances don't care about where the power comes from, just that it has enough. A big issue with the battery was that it often was insufficient to complete a crafting task, requiring reloading mid-project.

well, i personaly always have a shit ton of batteries, so that wasnt really a problem, but as long as i dond have to setup stationary base to use my forge- i am perfectly fine with this change

**Comment by sonphantrung** [comment]
Should we move the electric forge (vehicle) to Blaze Industries? Or should we remove the forge ability from MetalMaster Forge Buddy?

**Comment by Drew4484** [comment]
> Should we move the electric forge (vehicle) to Blaze Industries? Or should we remove the forge ability from MetalMaster Forge Buddy?

Operating it in an enclosed space like a vehicle is going to be a very hard sell, if you've ever seen a food truck with ranges going in it, they're sweltering even with the sides and doors opened up. A forge is several times as hot and you can't do much ventilation or it cools too fast. Electric forges are a bit different but constantly re-heating will drain power like nobody's business. Outside of a specialty service vehicle or a towed workshop, there really isn't a good case for them when you can just set one up outside.

**Pull request closed without merging**
