### PR TITLE
Make salvaged combat exoskeletons repairable

### PR DESCRIPTION
**Pull request by BalthazarArgall**
#### Summary
Features "Make salvaged combat exoskeletons repairable"

#### Purpose of change
We have salvaged combat exoskeletons in the game but they're mostly useless, you can technically use them as a platform for exoskeleton armor plating but at this point you're better off using any other armor. Especially since armor platings are extremely hard to find outside of fully functional exoskeletons spawning with them.

#### Describe the solution
I made it so you can ask Hub 01 to repair your exoskeleton, mostly copying and modifying already existing dialogue for repairing the RM13 and Phase Suit.

The cost is double because while exoskeleton technology is advanced, it's not the near-sci-fi levels of the RM13 or the phase suit and the Hub wouldn't have much to gain in studying them, reparation is mostly a service to the player (the guy at the intercom won't be very excited about it, wow such great writing).

The repair time has been kept the same as the other armors due to the nanofabricator being almost certainly used to repair the item and making repairs trivial.

I changed a few minor things about the salvaged exoskeleton item itself, it now represents the environmental suit but has 50% coverage on it due the irreparable (by the player) damage to the suit.

#### Describe alternatives you've considered

1. Add different versions of salvaged exoskeletons. It's a lot of work for a small payoff, the mk1-2 versions were way less popular than the mk3 in universe, we could add two other types of armored zombies to represent them but they would be so rare that they wouldn't be worth simulating in my opinion.

#### Testing
Tested the dialogue individually, works perfectly. Tested the armor, no error on load anymore, worn without issues.

#### Additional context
Some dialogue authored by SomeGuy. #75033 needs to be merged first

### CODE REVIEW

**Comment by kevingranade** [comment]
Two days for repairing a heavily damaged piece of very complex kit is an absolutely ludicrous turn around time, this is something that would require a month or more because they're having to reverse engineer and fabricate components for the thing. Even that is honestly super short and not really factoring in "just how much time are they willing to spend on this".  The cost is likewise crazy low.

**Comment by BalthazarArgall** [comment]
> Two days for repairing a heavily damaged piece of very complex kit is an absolutely ludicrous turn around time, this is something that would require a month or more because they're having to reverse engineer and fabricate components for the thing. Even that is honestly super short and not really factoring in "just how much time are they willing to spend on this". The cost is likewise crazy low.

I went full cargo cult on this, is there something fundamentally different about repairing the RM13 and phase suit compared to the combat exoskeleton? If anything I would thing the combat exos would be less complex/easier to repair.

**Comment by John-Candlebury** [comment]
If the complexity is required I'd go for a month and a few weeks first time and just a pair of weeks everytime after that. I dont know what the time for the other two suits is, but it should also be a pair of weeks.

I'd go with between 10 and 12 coins for the cost, the economy in general is still very bad with no guidelines on how to price things, so I wouldnt really  about finetuning the cost too much.

**Comment by BalthazarArgall** [comment]
> If the complexity is required I'd go for a month and a few weeks first time and just a pair of weeks everytime after that. I dont know what the time for the other two suits is, but it should also be a pair of weeks.
> 
> I'd go with between 10 and 12 coins for the cost, the economy in general is still very bad with no guidelines on how to price things, so I wouldnt really about finetuning the cost too much.

Got it. o7

**Comment by PatrikLundell** [comment]
A fundamental difference between repairing their own "products" and the suit is that they don't have the "blueprints" for either the suit itself or its parts, so they would have to be developed (basically saying the same thing as @kevingranade did above).

While we obviously don't know how a nano fabricator is supposed to work, I would assume it's not magic, but rather an extremely advanced 3D printer capable of handling multiple materials and parts. I can't see how such an item could repair anything (imagine trying to use a 3D printer to repair something it made) without someone first specifying what to repair and how to do it. A 3D printer wouldn't be able to repair anything it can't reach (such as parts now obstructed by layers deposited later), while a fabricator potentially could be instructed to take the item apart to reach the things to repair.

**Pull request merged**
