### PR TITLE
Fix item stacking issues

### LINKED ISSUE #30029: Batteries migrated from old saves sometimes do not stack.
**Describe the bug**  
Some batteries from my savegame before the battery overhaul will not stack.  This is likely due to them having different parameters in the save game.  Correct batteries (particularly freshly crafted ones) have a `bday` parameter in the save file.  Badly migrated ones have a `charges` parameter.  They can also be distinguished by how bad batteries gain 120 cents in displayed value per charge in them.

**To Reproduce**  
1. Migrate and old save from before battery overhaul to after the overhaul, probably with some battery tools in your inventory.
2. Unload batteries from the tools and try to stack them with freshly spawned or crafted batteries.

**Expected behavior**  
I would expect the migration code to create batteries that are identical to fresh ones and that stack.

**Versions and configuration:**
 - OS:  Windows 10
 - Game Version: 0.D-2341-g1c62c69
 - Graphics version: Tiles
 - Mods loaded: dda, aftershock, vehicle additions

**Additional Context**
From my investigation, I am pretty sure this is using the same code used to migrate guns to the magazine system, `item::magazine_convert()` at savegame_json.cpp:158 (as the PR for the battery overhaul had no code changes outside of unit tests), and that the batteries have different parameters than magazines (for instance, batteries shouldn't gain value with charge).  The solution would likely to be to create a special case for batteries in the migration code, as well as something to correct existing bugged batteries.

Additionally, the bulk of my battery stash came from unloading tools that were dropped by zombies before updating, and those batteries behave properly, so whatever happens to tools on the ground while migrating seems to work fine.

### PR DESCRIPTION
**Pull request by BevapDin**
``` SUMMARY: None```

Several items were created with a "hidden" charges value. "Hidden" because it was not shown in the game UI, only the effect was there: items that looked identical did not form a single common stack.

This is because the items *are* different: they have `item::charges` set to different values.

An easy to reproduce example: Create a new game as "Electrician" (spawns with a light battery). Now use the debug menu to create *another* light battery and look at their JSON string in the map editor. The item from the debug menu won't have "charges" listed, the other will have them.

Charges in those items are actually stored in `item::contents` as an amount of "battery" items (those *have* charges and that is fine), but the container item (the battery cell) should not have them.

----

Another example: butcher a creature with chitin so you get chitin pieces. Note how they stack nicely. Now butcher another one (preferably with a different size so you get different amount of items). See how the chitin pieces stack as well. See how the pieces from the first creature do not stack with the pieces from the second creature. Wonder why that is. Look at the commit for an explanation.

----

Another source of those issues are item groups that give charges to items that don't have them (laptop, USB drive, even pipes).

Generally "item_groups.cpp" will happily assign charges to items that don't allow them.

----

## Solution:

Beside the obvious change in the JSON files, I added code in "src/savegame_json.cpp" to fix those items. A new function `itype::can_have_charges` is used to determine whether the item can actually have charges, and if it can't, they are reset to 0 and a `debugmsg` is shown (the message is suppressed for items that are known to have that problem).

## ~~WIP~~

~~I marked this as WIP, because I'm no sure the logic to determine items that can have charges is complete.~~

Are there any other items that can have charges?

I suppose this fixes #30029.

### CODE REVIEW

**Comment by ymber** [comment]
If `charges` is being set for BATTERY type items it's a bug. Their state of charge is stored in `item::energy` which is a `units::energy` variable. The stacking code would need updating to consider this when it determines stackability.

**Comment by SunshineDistillery** [comment]
There is a bug related to this in NPC dialog when it grants the player items.  For items with charges, like beer, it works fine.  For other items you only get one, with hidden charges (unless you define it in a container, then you can see it as rock (25) or whatever). 

Also, i don't know if items that use countdown or delayed transform use charges or something else.  If so it might affect ethereal items from Magiclysm too.

**Comment by BevapDin** [comment]
@ymber Fixed that. The only battery item that is actually a battery seems to be the test battery, am I correct?

**Comment by ymber** [comment]
Yes, currently the item type is implemented but only used by that test item. The battery project is #32067 and finishing it depends on #32227.

**Comment by jbytheway** [comment]
Can we have some kind of check on item groups (at game-data load time) to sanity-check that they don't add inappropriate charges?

**Pull request merged**
