### PR TITLE
Improve naming of uilist single letter parameters

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
None

#### Purpose of change
`uilist` single letter parameters are confusing to read. Here are such examples.
```cpp
uilist_entry( int R, bool E, int K, const std::string &T, const std::string &D, const std::string &C );
uilist_entry( int R, bool E, int K, const std::string &T, const nc_color &H, const nc_color &C );
void addentry( int r, bool e, int k, const std::string &str );
void addentry_desc( int r, bool e, int k, const std::string &str, const std::string &desc );
void addentry_col( int r, bool e, int k, const std::string &str, const std::string &column, const std::string &desc = "" );
```

#### Describe the solution
`addentry`
- r &#8594; retval &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: return value
- e &#8594; enabled : is entry enabled
- k &#8594; key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: keybind code
- t &#8594; txt &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: entry text

`uilist_entry`
- T &#8594; txt &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: entry text
- D &#8594; desc &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: entry description
- K &#8594; key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: keybind code
- R &#8594; retval &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: return value
- E &#8594; enabled &nbsp;: is entry enabled
- C &#8594; ctxt &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: entry second column text ( std::string )
- C &#8594; txtcolor &nbsp; : text color ( nc_color )
- H &#8594; keycolor : hotkey color

#### Describe alternatives you've considered
Change `txt` to `text` or `name`  
Change `ctx` to `coltext` or `column_text`

#### Testing
It compiles without errors and `uilist` is working without problems.

#### Additional context
I assume other text editors ( it does in vscode ) use the parameter names in the header for hints, so only the text in header was changed.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Personally I think the ancient UNIX style single finger tapping oriented command strategy is bad, while readability is good:
retval->return_value
key->key_binding
txt->entry_text
desc->description
ctxt->second_column_text
txtcolor->text_color
keycolor->key_color

However, the change made is a definite improvement over the previous key press averse implementation.

**Comment by Saicchi** [comment]
This is just my opinion:
`retval` has the same name as its variable inside the `uilist_entry` struct.
`description` would be too long, `desc` is shorter as is just as easy to understand
`second_column_text` is also too long.
`entry_text` would be redundant.
Otherwise I'm not opposed to the other changes.

**Comment by Saicchi** [comment]
From what I can see in the failed build error, the parameters in the `.cpp` file must have the same name... I'll fix it tomorrow.

**Comment by actual-nh** [comment]
`ctx` is way too confusable with `context`, as with translation helpers.

**Comment by Saicchi** [comment]
Should I rename `ctxt` to `coltxt` or just `column`?
Because the one for description just uses `desc`, instead of something like `desctxt`.

**Comment by Saicchi** [comment]
I've renamed `ctxt` to `column`, the same parameter name as in `addentry_col`.

**Comment by KorGgenT** [comment]
since you didn't go with the long-form variable names, can you make comments in the header detailing the variable usages?

**Pull request merged**
