### PR TITLE
Chemistry skill

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Features "Chemistry skill"

#### Purpose of change
Crafting mutagens shouldn't require character to be able to cook bœuf bourguignon.

There were lots of talk about separating chemistry from cooking skill in the past. I guess the time has come. 

#### Describe the solution

- [x] Added a skill to `skills.json`. Updated description of cooking skill so that it doesn't mention mixing chemical mixtures.
- [x] Books `Advanced Physical Chemistry`, `chemistry textbook`, `The Modern Tanner`, and all mutagen recipes books now train chemistry instead of cooking. 
Books `The Essential Oil Enthusiasts Handbook` and `Art and Science of Chemical Warfare` now train chemistry instead of fabrication.
- [x] Added chemistry as starting skill to `Bionic Prepper`, `Sheltered Survivor`, `Lab Technician` (changed from cooking), `Survivalist`, `Volunteer Mutant` (changed from cooking), `Bionic Sniper`, `Meth Cook` (changed from cooking), `Naturalist`, and `Science Club Member` (changed from cooking) professions.
- [x] Changed LOTS of chemical recipes that were previously required or used cooking skill to require or use chemistry skill.
- [x] Add a low-level skill book to train chemistry.
- [x] Check chemistry skill books' `required_level` and `max_level`.
- [x] Check recipes' required or used chemistry skill level.

#### Describe alternatives you've considered
None.

#### Testing
Started game, debug-learned all recipes, skimmed through `CHEM` category.

#### Additional context
Assuming that basic chemistry is roughly level 3 cooking, in first approach we could simply subtract 3 from all current chemistry skill level requirements, but this will still require careful examination.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Progress update:
1) Basic-level book trains chemistry from 0 to 3 levels;
`Modern Tanner` trains chemistry 3..4;
College-level book and indirectly-related books (about gas warfare and oil extraction) trains chemistry 4..6;
University-level book trains chemistry 5..7;
Various mutagen-books trains chemistry 6..8.

2) Reduced all mutagens and purifiers recipes' difficulty by two (from previous cooking levels). So now the easiest recipe from this category requires 5 level of chemistry, the hardest requires 8 level.

**Comment by Zireael07** [comment]
So, I remember from previous discussions that the main blocker to splitting chemistry to a separate skill was the fact that most things are fairly high-level (5+).
Have you added/tweaked recipes so that chemistry has a use at skill levels lower than 5?

**Comment by Night-Pryanik** [comment]
> Have you added/tweaked recipes so that chemistry has a use at skill levels lower than 5?

Not yet. It's on my todo-list. I'm working on it.

**Comment by Night-Pryanik** [comment]
The current situation is as follows:
We have a book to train chemistry from 0 to 3 levels. It should spawn rather frequently (in schools, libraries, and houses).

We have one 0-1 levels chemistry recipe (soapy water). It's rather questionable for this recipe to train chemistry to level 1, because it could train nothing as well.
We don't have any 1-2 levels chemistry recipes, so the only way to level chemistry to level 2 is to read the book.
We have several 2-3 levels chemistry recipes, so one could "naturally" level the skill up just by crafting things.
Higher level recipes are more abundant, also there are several books of 3-8 levels to increase the skill even higher.

In general, though, most of low-level recipes are not really useful or required in everyday activity, so finding the book and reading it could be the only effective way to get to higher levels. I see several variants to deal with this matter:
- leave things as is. With the basic book you still can get to higher levels. It's not really fun, but it works;
- decrease difficulty of some higher-level recipes to lower-level ones. As for now I can't think of any examples for this variant, so suggestions are welcome;
- globally decrease all difficulties of all recipes that require chemistry (and `book_learn` values for all chemistry books) by one. Thus we'll remove the "no recipes for 1-2 levels" gap we have now.

**Comment by nexusmrsep** [comment]
Or add some low level recipes, for example for extracting some basic reagents, or making easily obtainable chemicals (for use in more complex reactions in the future). What would they be I cannot tell, someone with expertise would come in handy here. My guess would be something as simple as boiling salt from salt water, or perhaps extracting hydrogen via electrolysis?

**Comment by Zireael07** [comment]
Boiling salt is a perfect candidate for 0-1 level indeed (and soapy water shouldn't train anything IMHO).
I'd put various examples of electrolysis around level 1 and 2.

**Comment by Night-Pryanik** [comment]
> Or add some low level recipes

I fully support this variant, though for now I can't think of any appropriate recipes. We just should also keep in mind the fact that 0..3 levels recipes should be totally feasible for kids around 8-12 years.

**Comment by Zireael07** [comment]
Given the hint above, I tried to google for "primary school chemistry" but just about the only experiment shown that could be useful at all to a survivor is "vinegar + baking soda = boom! + foam"

**Comment by Night-Pryanik** [comment]
Progress update:
Now we have three 0..1 levels, one 1..2 levels, and nine 2..3 chemistry recipes.

**Comment by Torbenbeta** [comment]
As a Chemistry student (M.Sc., Germany) in his last semester, I thought a bit about beginner level (university) chemistry experiments mainly from the field of organic synthesis.
The first organic reaction, as far as I know not in game, I did was extraction of  eugenol from clove. So an extraction ( for an in-game example from mutated poppy flower) should be chem lvl 1 or 2.
The synthesis of aspirin (acetyl salicylic acid) is quite easy too, so chem lvl. 2 (currently cooking 4) seems fair as well.
One of the first organic reactions taught in lectures, which I never did in a lab, is saponification. So reaction of sodium hydroxide with an alcohol to form soap, should be lvl. 1 (currently cooking 3).

For chemistry lvl. 0 (an inorganic example), would be the aforementioned creation of salt (mainly NaCl) from salt water via evaporation.  
The vinegar and soda reaction is fine.
A reaction which was demonstrated in my first general chemistry course by the professor is the creation of gun cotton. It is not very complicated in theory or practice, but dangerous. So the classification is a bit harder. I am unsure between lvl. 0 and 1.
Distillation is a mainstay of organic reactions, so should lvl. chemistry as well. Moonshine is learned at cooking 2. I would set it to autolearn at cooking 2 and chemistry 0, as a good cook without much chem. education can distill just fine.
Most other reactions normally done in beginner lab courses are classical analytical chemistry or the creation of substances without practical (in the cdda setting) use, which do not serve the survivor chemist that well.
Question: I noticed two-three inconsistencies while browsing the chem crafting section, shall I post them here or in another issue?
Are suggestions for real text books (like SICP for computer) wanted or should they remain general?

**Comment by Night-Pryanik** [comment]
@Torbenbeta thanks for your input, I lowered chemistry skill requirement for crafting aspirin from 4 to 2, and for crafting soap from 3 to 2 based on your feedback. I have one question though, should I also add a requirement of basic chemistry book for these two recipes, or they are good with autolearn?

> Question: I noticed two-three inconsistencies while browsing the chem crafting section, shall I post them here or in another issue?

Post them here.

>Are suggestions for real text books (like SICP for computer) wanted or should they remain general?

I don't know. Generally I avoid using real names for books.

**Comment by nexusmrsep** [comment]
This looks like a promising source for ideas (perhaps not low level, but nevertheless): https://catbull.com/alamut/Bibliothek/Kings_Chemistry_Survival_Guide.pdf

Also as far as I remember you can extract cyanide from apple seeds, and since we have orchards, you can *wink* *wink* Not sure what would you use it in-game, but idea is an idea.

**Comment by nexusmrsep** [comment]
Another broad idea: introduce more household chemical products and add low level recipes to extract/purify the relevant substances and chemical compounds.
Reference: https://en.wikipedia.org/wiki/Household_chemicals and subsequent sub-links.

**Comment by Night-Pryanik** [comment]
I think more chemical recipes could/should definitely be added, but in subsequent PRs, after (and if) this PR will be merged.

**Comment by Torbenbeta** [comment]
@Night-Pryanik, I am happy to be able to add something to this game and be able to use my expertise.
Regarding your question: aspirin should not be autolearned but remain book-bound as the practical requirements of the synthesis reaction cannot (or only very limited) be deduced from the reaction equations and are empirically found.
The saponifcation reaction is another matter as it could be argued that their components (base+alcohol) and their reaction are widely known. So even though the same objection as above applies, from the player point of view autolearn seems reasonable, to reduce dependence on the chemistry textbook.

**General chemical issues/inconsitencies** 
More points than I originally thought. 

- Acid water from salt water. I do not know how this can be possible without other chemicals. There are acidic salts but normal table salt (NaCl) does not belong to them.

- Lye powder from charcoal and water. I think you would get cleaner water as charcoal is used as a purifier but it will not get caustic nor will it generate solid NaOH (lye).

- Formaldehyde from Methanol, I am unsure about this as this reaction can be done but needs an oxidizing agent which heat is not. Given the low yield (50 units of methanol per unit Formaldehyde) the possible auto oxidation with air oxygen could be meant. The description text mentions that it is mixed with water, which would not result from the reaction ingredients.

- Saltpeter (NaNO3) from ammonium nitrate with caustic powder is fine but would need water (if one unit is 250 ml, that should be sufficient [guess]) as a solvent.

- Ammonia (NH4+) from water+scrap metal and coal/charcoal (C) or lye powder (NaOH), where should the nitrogen (N) come from?

- Potassium iodide tablet (KI) from salt (NaCl) and Aspirin. Where does the K or I atoms come from? Assumption: salt is NaCl (table salt)

-The book 'Advanced physical chemistry' mentions that it is a book about organic and inorganic chemistry not about physical chemistry.

One point where I totally leave my area of expertise is the creation of mutagens. Even with much knowledge of chemistry, Imo more than a cursory knowledge of medicine seems necessary.
This is it what I can think of.

**Comment by Night-Pryanik** [comment]
Thanks again for feedback!

> reaction of sodium hydroxide with an alcohol to form soap

We have alternative recipe for crafting soap (from lye and without any alcohol). Would you be so kind to provide a recipe for "your" saponification (in game terms)? I.e. ingredients, their amount, time required etc.

> Lye powder from charcoal and water. I think you would get cleaner water as charcoal is used as a purifier but it will not get caustic nor will it generate solid NaOH (lye).

Hmm, when I added a recipe for creating lye, it was craftable from boiling ash, not boiling charcoal. Somehow missed the moment it was changed. Should I change it back to ash?

> Saltpeter (NaNO3) from ammonium nitrate with caustic powder is fine but would need water (if one unit is 250 ml, that should be sufficient [guess]) as a solvent.

Added water to the recipe.

> Ammonia (NH4+) from water+scrap metal and coal/charcoal (C) or lye powder (NaOH), where should the nitrogen (N) come from?

What should I add to the recipe? Or remove it altogether as unrealistic?

> Potassium iodide tablet (KI) from salt (NaCl) and Aspirin. Where does the K or I atoms come from? Assumption: salt is NaCl (table salt)

What should I add to the recipe? Or remove it altogether as unrealistic?

**Comment by Torbenbeta** [comment]
Regarding lye from boiling charcoal instead of ash: 
I would be in favor of changing it back to wood ash only. 
Regarding the creation of Ammonia:
My chemist girlfriend and I are both in favor of removing the recipe.
As written by others above and mentioned by my girlfriend, extraction of Ammonia from detergents or electrochemically would be viable alternatives.
Regarding the creation of potassium iodide (KI):
As she pointed out to me, to commercial table salt normally some potassium iodate is added which can be reduced to KI. But I would give the benefit of doubt here. Interesting would be to find the pr introducing the recipe.

As you @Night-Pryanik and others wrote, this pr could be merged (after the book title advanced physical chemistry is changed and the suggested changes are adopted or not) and recipes for electrolysis and bulk chemicals are implemented later.
Question: as neither she nor me ever did a pull request, were it easier if she and me were to write a list of ideas/suggestions here, here in a new issue or in the forum at discourse or in an e-mail?

**Comment by nexusmrsep** [comment]
@Torbenbeta - it would be best if you could provide those ideas as issues in the Issues section on GitHub. When possible you could split it up, for example one proposed recipe (chemical process) in one issue. I believe it would be easier that way for developers to pick it up one by one for implementation.

**Comment by Fris0uman** [comment]
Does it need some migration code so that current save with hight cooking skill get some level of chemistry instead of starting from 0?

**Comment by Night-Pryanik** [comment]
I think we can go without this migration in this case.

**Comment by meladath** [comment]
Theres a great book you might be able to find online called assorted nasties. Put together by a CIA member in the cold war I believe, has loads of information about how to "home brew" poisons/various other.... well assorted nasties. It should be added to the game and part of this skill imo.

**Comment by Zireael07** [comment]
@meladath: Good idea (fits the game) but for a separate PR imho.

**Comment by pescepalla** [comment]
> Ammonia (NH4+) from water+scrap metal and coal/charcoal (C) or lye powder (NaOH), where should the nitrogen (N) come from?

Couldn't this come from fertilizer or even from litter?

**Comment by Iron-Tree** [comment]
Someone should just add a haber-dasher veicl part that allows you to make as much ammonia as you need/want... just needs mechanics, electronics, fabrication, chemistry, all at ten and a metric ton of platinum... The thing should be an option only for a stationary base just by being ridiculously heavy...
https://en.wikipedia.org/wiki/Haber_process

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/scarfys-mod-because-urine-in-a-bowl-is-realism-too/24711/2

**Comment by Xelat84** [comment]
> * Acid water from salt water. I do not know how this can be possible without other chemicals. There are acidic salts but normal table salt (NaCl) does not belong to them.

Actually it's very easily possible. Using only table salt (NaCl) solution in water (H2O), applying electrolysis you get lye (NaOH) and gases H2 and Cl2. Hydrogen chloride may be formed by the direct combination of chlorine (Cl2) gas and hydrogen (H2) gas; the reaction is rapid at temperatures above 250 °C. A solution of the Hydrogen chloride gas in water is called hydrochloric acid.
So I vote for returning this recipe.

Production of ammonia is also possible, just more complicated comparing to as it was, but still. You can use Hydrogen from reaction described above, and Nitrogen from air (same as IRL), after that you also need ability to create high pressure (100bar), which is possible using some high-pressure tanks, valves and pumps for example, and relatively high temperature (500°C) which is also pretty doable, and of course an iron catalyst (IRL it's iron with some fractures of aluminum, potassium and calcium oxides, but this can be omitted in a game, or implemented as a recipe for catalyst item just for this process).

So I don't get why introducing chemistry on the same time we just removing some recipes, instead of making them more accurate?

**Comment by Night-Pryanik** [comment]
> So I don't get why introducing chemistry on the same time we just removing some recipes, instead of making them more accurate?

I'm not a chemist myself, so I thought that when someone with more knowledge in chemistry (@Torbenbeta) participates in a discussion, I'd better hear them out. 
If you are such proficient in chemistry, you could return the deleted recipes with your own suggestions.

**Comment by JBloodthorn** [comment]
The Haber Process (1909) literally uses a metal catalyst and pressure to react atmospheric nitrogen with hydrogen to make ammonia. That's probably what the recipe was referencing. 

Ammonia being removed could have been avoided by just adding a pressure pot to the basic chemistry set recipe.

**Comment by Zireael07** [comment]
@JBloodthorn: Basic chemistry set is taken from here: https://en.wikipedia.org/wiki/Chemistry_set
No pressure pot in the set. And I don't think anyone ever added an "advanced set" because there wasn't a need for it...

**Comment by JBloodthorn** [comment]
@Zireael07 Could also have just added the pressure pot as a tool for the ammonia recipe, but that would probably trigger a need to look at every chem recipe to see which require pressurization. Either way would work, but adding it to the chem set is less clutter, especially when more chemistry gets added.

**Pull request merged**
