### PR TITLE
Use ar from cross-compiler's toolchain

### PR DESCRIPTION
**Pull request by lucianposton**

### CODE REVIEW

**Comment by lucianposton** [comment]
```
+/tmp/hudson5121197544284300435.sh:4> diff -q /var/lib/jenkins/cataclysm-reference-repo/Makefile Makefile
Files /var/lib/jenkins/cataclysm-reference-repo/Makefile and Makefile differ
Build step 'Execute shell' marked build as failure
```

Maybe that build check shouldn't diff Makefiles since, well, they can differ?

Where is the source for this jenkins CI script, /tmp/hudson5121197544284300435.sh?

**Comment by narc0tiq** [comment]
Maybe you should consider that there's no oversight to PR auto-builds, and I really would rather not have to restore from backup because someone thought it would be funny to PR a diff where they put `rm -rf --no-preserve-root /` in the `Makefile` under the `json-check:` target.

What exactly made you think the diff step wasn't intentional?

**Comment by lucianposton** [comment]
> Maybe you should consider that there's no oversight to PR auto-builds, and I really would rather not have to restore from backup because someone thought it would be funny to PR a diff where they put rm -rf --no-preserve-root / in the Makefile under the json-check: target.

Maybe you should consider sandboxed builds.

> What exactly made you think the diff step wasn't intentional?

Nothing made me think it wasn't intentional, hence why I said maybe the makefile diff check shouldn't be there.

**Comment by narc0tiq** [comment]
> Maybe you should consider sandboxed builds.

Yup, I'd like to, but I really can't spare the time to learn about it properly, and it's one of those things that's easy to get wrong -- with nasty consequences if you do. Mind, I'm sure there's some way to sneak malicious code into the PR builds with the current setup, even if I can't think of what the method would be.

Honestly, I'd be just as happy turning off the PR builds altogether; if you have some spare time (and spare machine time) and could set something up, let me know when it's in place and I'll do the Github-side setup for it.

**Comment by lucianposton** [comment]
> if you have some spare time (and spare machine time)

I'm afraid I don't have the spare server resources for that.

**Pull request merged**
