### PR TITLE
Revisit Fire Drills (Refills)

### LINKED ISSUE #34063: fire drills take zero time to activate fire-dependent items
# Describe the bug

Even though it still takes a lot of time to set a piece of tinder on fire.

# Steps To Reproduce

1. Load the game.
2. Note the time.
3. Light either a candle or some furniture nearby.

# Expected behavior

Fire drill taking same time to use.

# Versions and configuration

0.D-7657-g3648a54071-dirty
[2019.09.16.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3616287/2019.09.16.zip)

### LINKED ISSUE #59093: You need a bow fire drill to craft one
### Describe the bug

The recipe of the bow fire drill requires as components a plank or a stick and a bow fire drill.
So we have to imagine you already have one and toss the stick away or something?
: )

### Steps to reproduce

check out recipe

### Expected behavior

we expect the bow fire drill to be made from other stuff than an already existing bow fire drill

### Screenshots

_No response_

### Versions and configuration

win7, experimental from early june 2022

### Additional context

_No response_

### LINKED ISSUE #61076: Recrafted Pump Fire Drill Out of Fuel when put into hiking backpack
### Describe the bug

Crafting a refueled Pump Fire Drill and wielding it has it show the correct like new fuel level. As soon as I put it into my hiking backpack it reverts to Fuel: almost completely burned out.

### Steps to reproduce

1. Recraft Pump Fire Drill with Plank
2. Wield/examine Newly crafted Pump Fire Drill and see refreshed fuel.
3. Place into backpack and see that the Fuel level reverts back to almost burnt out and cannot be used.

### Expected behavior

Retains the refreshed charges when placed into backpack.

### Screenshots

in inventory pre craft
post craft

pump drill gif

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 6a176f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Innawood [innawood],
    DinoMod [DinoMod],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Retains charges as long as it isn't put into the backpack.

Save file attached.

[Naples Park_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9592034/Naples.Park_copy.zip)

### PR DESCRIPTION
**Pull request by oosyrag**
#### Summary
Balance "Removed fire drill refill recipes, added notched fire boards as ammo"

#### Purpose of change

Apparently a recurring source of confusion for new players is "Why does a fire drill need a fire drill to craft?", not understanding that it is a refill. Fixes #59093 by removing the refill recipes and adding new fire boards recipes (notched plank, notched stick) as ammo for fire drills. They function as disposable batteries.

Also plan to resolve #34063, increasing the base move time of starting a fire drill by a lot. Seems like code is available to account for a "long action".

Fixes #61076, fire drills no longer have BURNOUT flag.

#### Describe the solution

I think the confusion stems from being having access to the reloading recipes at survival 0, without having or seeing the base recipe yet, which is auto learned at survival 2. ~~Various solutions below, went with option "a" as the least invasive change, as fire drills are not found in the world, so having access to the reloading recipe before being able to make it doesn't matter anyway.~~

Ideally the ability to change the name of a recipe on the crafting screen would be nice, such as "Refill fire drill" that results in a new fire drill. However, the crafting screen has to use the resulting item name. The workaround could be "c" below, with a new item named "Pump/Bow Fire Drill Reloaded". But I struck that out as adding item bloat for a very niche item(s), and not respecting the current string freeze, and basically overkill.

Edit: Moving forward with option "e". Fire drills will be able to be (re)loaded with new notched plank and notched stick magazines, with notches as ammo.

- [x] Remove fire drill reload recipes
- [x] Remove plank requirement from fire drill recipes
- [x] Add recipes for notched stick and notched plank
- [x] Add notch ammo
- [x] Allow fire drills to take notched stick and plank as ammo
- [x] Add notched stick or plank to starting inventory for Innawoods
- [x] Test
- [x] Balance pass for weight/volume/length and other values
- [x] Lint
~~- [ ] Figure out how to display in inventory loaded fire drill and fire board ammo as "charges" (or at least "notches") instead of  blank and "notch" respectively~~

This seemingly simple change is a quite a bit more involved than I thought it would be. This is a largest pr I've done so far please let me know if I missed something or did something wrong or there are other things to consider that I didn't think of.

Balance:
Notched plank to 24 charges, notched stick 10 charges.
Bow fire drill base moves adjusted to 30000 (5 minutes), moves_slow to 60000 (10 minutes)
Pump fire drill base moves to 6000 (1 minutes) and moves_slow 12000 (2 minutes)
(Basically hard to light items take 2 tries, or twice as long. Would be nice to model this as a chance for success upon using up a charge instead, but that could be something to explore in the future.)
Fire drills now require tinder. Let me know if this requirement is unduly burdensome for Innawoods. Could be mitigated by adding more sources of tinder like paper/newspaper, or reverting this tag.
Fire boards (notched planks and sticks) can now be made with drilling 1 as well as a cutting 1. Although you still need cutting 1 to make a primitive rock drill. ~~Besides which bow drills and pump drills could probably make pretty excellent primitive rock drills themselves.... but that's another feature for another day ><~~
Fire drills now have rock drilling 1 quality
Pump fire drill only requires CUT: 1 quality to make, like the bow fire drill.
Fire board recipes give you 4 boards, conservation of mass. (the boards and sticks are cut into 1/4 the size of a plank/stick, so that the loaded fire drills still fit into backpacks.

#### Describe alternatives you've considered

a. Make the refill require fabrication 2, so it auto learns at the same time making the drill from scratch shows up.
b. Make the drills require fabrication 0, so both the refill and the drill are available from the start.
c. Make a new item for each, "fire drill reloaded", so the name of the item is more intuitive on the crafting screen.~~
d. Get rid of the reloading recipes completely and have people make a new drill from scratch when the charges run out.
e. ~~Make wood planks a reloadable ammunition for fire drills~~ A notched plank/stick magazine/ammo item.

#### Testing

Started a survivalist character, with bow fire drill. Confirmed it started loaded with a 24/24 notched plank. Crafted a pump fire drill, new notched plank, new notched stick, tinder, and used both to try burn the evac shelter down. Great success.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
This change breaks Innawood, as characters start with a fire drill in that mod, and so may have a need to be able to "reload" it before they have gained a fabrication skill level of 2 (you go through charges quickly when all fires will have to be made from branches and the like which only burn for a short time, as you don't have access to anything to cut firewood with).

**Comment by oosyrag** [comment]
Ahh thanks for the info, that does make it a little more complicated. The notched plank idea starts looking more favorable, but seems like this is going to have to wait for G.

**Comment by oosyrag** [comment]
I wish I made the connection that fireboards are basically disposable batteries when I started this ><

**Comment by oosyrag** [comment]
Apologies, I seem to have blown this up by rebasing...

**Pull request merged**
