### PR TITLE
Obsolete trickle charger CBM

### PR DESCRIPTION
**Pull request by Testudo-Cultu**
#### Summary
Balance "Obsolete trickle charger CBMs"

#### Purpose of change

No nuclear generator is capable of this output without being too large or heavy to be practical with modern tech or likely even near-future tech. Balance is also in question for any CBM capable of giving "free energy."

#### Describe the solution

Ctrl + F, remove bio_trickle and add to obsolete items. Add to Aftershock with three times the output.

#### Describe alternatives you've considered

Make a larger RTG CBM, but there's just no practical application for this and no reason anyone would make it.

#### Testing

It just works.

#### Additional context

I moved them to Aftershock by request of Candlebury.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
The trickle charger isn't a betavoltaic. Frankly, it can be nearly anything but I based its efficiency on the asrg. Compared to the asrg it is 1/65th the power output and weight using an~18g plut chip to generate 2 watts (at 25% efficiency like the real asrg) and 6-7w of waste heat (which should be not an issue) and comes in at 1\65th of the real asrg's weight at 500g. The only "magic" involved is that it is abnormally small but it doesn't break the laws of physics or anything.
It's not necessarily a mini asrg either, that's just the guideline i used for its specs.

**Comment by Maddremor** [comment]
I'm in favor of this, not because it's unrealistic, but because passive free power is kinda boring as a mechanic. Make the player do stuff and have bionics feel visceral instead.

**Comment by John-Candlebury** [comment]
I'd greatly appreciate if you moved the bionic to aftershock in here. Afterall you are already removing several things from the mod already. An aftershock equivalent is just the same bionic but with 3x power output (mostly because I intend to get rid of the sillier "passive recharge" bionics"

I'd do it later but I'm in the midst of some larger scale projects and this would help quite a bit.

**Comment by Testudo-Cultu** [comment]
> I'd greatly appreciate if you moved the bionic to aftershock in here. Afterall you are already removing several things from the mod already. An aftershock equivalent is just the same bionic but with 3x power output (mostly because I intend to get rid of the sillier "passive recharge" bionics"

No problem. Part of why I set this to draft was because I became unsure of whether or not to leave it in Aftershock, since it's effectively the exact same mechanically and just needs two lines of JSON data changed to fit properly. That, and the build failed because of a missing comma and I was too busy/lazy to fix it immediately...

For that matter, should I leave it in Aftershock with everything exactly the same, or would you like for me to give it 3x the power output and a new description while I'm at it?

**Comment by John-Candlebury** [comment]
I'd prefer if you can give it the extra power gen here. A reworked description can just be the previous one from the issue you linked in discord, but if you want to write something different that's cool.

**Comment by Testudo-Cultu** [comment]
> The trickle charger isn't a betavoltaic. Frankly, it can be nearly anything but I based its efficiency on the asrg. Compared to the asrg it is 1/65th the power output and weight using an~18g plut chip to generate 2 watts (at 25% efficiency like the real asrg) and 6-7w of waste heat (which should be not an issue) and comes in at 1\65th of the real asrg's weight at 500g. The only "magic" involved is that it is abnormally small but it doesn't break the laws of physics or anything. It's not necessarily a mini asrg either, that's just the guideline i used for its specs.

Basing it off of the ASRG is a confusing choice. I know it doesn't technically break the laws of physics, but it is still entirely infeasible.

SRGs are very complicated mechanically and haven't seen real use, with the ASRG project by NASA being cancelled in 2013 after 13 years of development with roughly 40 years of other SRG research preceding it. A flight-ready SRG may not even be ready until 2028, according to NASA. This is absolutely not a technology mature enough to be miniaturized into a medical implant where it is expected to continuously operate without failure and be shielded enough to not burn or irradiate the person it's inside of. Regardless of this, you can rarely (if ever) take a complex device and say how it will perform at a specific scale just by dividing everything by an arbitrary number like 65.

With the 25% efficiency you have given it, there is no other nuclear device you could be speaking of, and as I said, SRGs are out of the question for a miniaturized medical implant.

When it comes to a conventional RTG, we're looking at a (small) backpack-sized unit for just a couple watts.

**Comment by Testudo-Cultu** [comment]
The extremely sci-fi CBMs will most likely be explained as having been taken by the Exodii (or possibly the player) from a far more technologically advanced civilization's dimension. This CBM could be reintroduced with the same explanation later, but I very much doubt it will be, both for balance and because it just isn't interesting enough. For now, one thing at a time.

**Comment by Zireael07** [comment]
> SRGs are very complicated mechanically and haven't seen real use,

Nitpick: not true, see Voyager 1 and 2

That said I agree "get power for free" is boring from player pov and that this CBM doesn't really fit current game

**Comment by tenmillimaster** [comment]
I agree that it's not worth surgery to install any low current nuclear battery alone.

**Comment by Testudo-Cultu** [comment]
> I'd prefer if you can give it the extra power gen here. A reworked description can just be the previous one from the issue you linked in discord, but if you want to write something different that's cool.

I made the changes you requested. Felt the original description is okay for now, since I really can't think of any technology that would explain how this thing works. Maybe a miniaturized cold fusion reactor or something.

I chose to add "bn" to the CBM ID because that was added to the solar panel CBM. I decided I might as well make it a trend to use for CBMs obsoleted in the base game, assuming it wasn't the intention in the first place.

**Comment by kasanryukin** [comment]
> > I'd prefer if you can give it the extra power gen here. A reworked description can just be the previous one from the issue you linked in discord, but if you want to write something different that's cool.
> 
> I made the changes you requested. Felt the original description is okay for now, since I really can't think of any technology that would explain how this thing works. Maybe a miniaturized cold fusion reactor or something.
> 
> I chose to add "bn" to the CBM ID because that was added to the solar panel CBM. I decided I might as well make it a trend to use for CBMs obsoleted in the base game, assuming it wasn't the intention in the first place.

Since John uses super science terms throughout his mod, you could describe it in broad terms.  Just called it a miniaturized Deuterium-Deuterium Fusion Reaction and leave it there.

**Comment by Testudo-Cultu** [comment]
> > > I'd prefer if you can give it the extra power gen here. A reworked description can just be the previous one from the issue you linked in discord, but if you want to write something different that's cool.
> > 
> > 
> > I made the changes you requested. Felt the original description is okay for now, since I really can't think of any technology that would explain how this thing works. Maybe a miniaturized cold fusion reactor or something.
> > I chose to add "bn" to the CBM ID because that was added to the solar panel CBM. I decided I might as well make it a trend to use for CBMs obsoleted in the base game, assuming it wasn't the intention in the first place.
> 
> Since John uses super science terms throughout his mod, you could describe it in broad terms. Just called it a miniaturized Deuterium-Deuterium Fusion Reaction and leave it there.

Could work. I'd like to rename it as well

> > > I'd prefer if you can give it the extra power gen here. A reworked description can just be the previous one from the issue you linked in discord, but if you want to write something different that's cool.
> > 
> > 
> > I made the changes you requested. Felt the original description is okay for now, since I really can't think of any technology that would explain how this thing works. Maybe a miniaturized cold fusion reactor or something.
> > I chose to add "bn" to the CBM ID because that was added to the solar panel CBM. I decided I might as well make it a trend to use for CBMs obsoleted in the base game, assuming it wasn't the intention in the first place.
> 
> Since John uses super science terms throughout his mod, you could describe it in broad terms. Just called it a miniaturized Deuterium-Deuterium Fusion Reaction and leave it there.

Getting into the actual reaction it uses for fusion is probably not necessary, so I'll just say it's a miniaturized fusion reactor with an internal fuel reservoir capable of sustaining the non-specific reaction for a couple hundred years.

**Comment by Cenness** [comment]
Will Metabolic Interchange `bio_metabolics` be removed as well? It is equally powerful in terms of generating free energy as trickle, if not more. The character is required to eat regardless.

**Comment by fairyarmadillo** [comment]
Metabolic power isn't "free", it requires that you have a surplus of food. That food itself isn't a huge issue at the moment in our survival game is a separate issue, and one that's being worked on.

**Comment by Cenness** [comment]
> one that's being worked on

So let's get it straight. It's ok to leave op as of right now CBM in mainline, because it might be indirectly nerfed in future. But instead of reworking CBM that takes 1/3 of slots and gives exactly enough power to have cranial flashlight on, maintainers decided to remove it.

Example of rework could be changing trickle CBM to a fuel powered one, with fuel being plutonum cells or cobalt-60 pellets.

**Comment by kasanryukin** [comment]
> > one that's being worked on
> 
> So let's get it straight. It's ok to leave op as of right now CBM in mainline, because it might be indirectly nerfed in future. But instead of reworking CBM that takes 1/3 of slots and gives exactly enough power to have cranial flashlight on, maintainers decided to remove it.
> 
> Example of rework could be changing trickle CBM to a fuel powered one, with fuel being plutonium cells or cobalt-60 pellets.

We had a very long conversation about the trickle charger on the development discord. While there was some arguments both for and against, it was ultimately unanimously decided that it didn't fit with the narrative theme around CBMs at this present juncture.  John wants to keep it, so it's being moved from mainline to aftershock.

As for "op" CBMs, there is discussion about removing a fair number CBMs that no longer fit the narrative of the base game.  Likely, they'll be moved to aftershock as well.  The trickle charger is just the first one to be obsoleted.  I wouldn't worry about other power generation CBMs as they're in a good place balance wise.

**Comment by Cenness** [comment]
>removing a fair number CBMs that no longer fit the narrative

It would be nice to have a list of those published somewhere more accessible (projects maybe?), so it would prevent experimental players from wasting time playing with unsupported items

**Pull request merged**
