### PR TITLE
Correct CMake install locations on *nix

### PR DESCRIPTION
**Pull request by perryprog**
#### Summary
None

#### Purpose of change
PR #61225 changed the location some stuff got installed in, which while correct for the Windows style install location, is incorrect for the default *nix style install locations. (`CMAKE_INSTALL_DIR` is by default `/usr/local` instead of `c:/Program Files/${PROJECT_NAME}/` according to [here](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).)

#### Describe the solution
Adjust these install locations to be correct for both OS's, hopefully. I'm not sure what the install locations for `gfx/` and `doc/` are intended to be for Windows, so I've set it to what it was previously, which is under `DATA_PREFIX`. I'd like it if this can be confirmed before the PR is merged so I can make the default install locations for both of those directories also depend on OS.

#### Testing
Builds and runs on macOS. I'd appreciate it if someone on Windows can test.

#### Additional context
CC @alef: I'd like to know what would be the correct directories according to what you were trying to do.

### CODE REVIEW

**Comment by alef** [comment]
The CMake builds do not install correctly, it should be fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/61880.
I suggest you rebase this PR after mine gets merged (@akrieger is back)

**Comment by akrieger** [comment]
I mean I'm still *on* vacation but I found time to hop on discord today :p

**Comment by perryprog** [comment]
Ah, thanks, I didn't realize you had opened the second PR already. Because install is effectively broken on *nix right now, do we want to merge this as a temporary fix? (I'm thinking it's find to wait considering I seem to be the first person to notice, unless there's an issue I missed.)

**Comment by Night-Pryanik** [comment]
@perryprog could you please resolve conflicts?

**Comment by perryprog** [comment]
All done; sorry for the delay. @alef, can you confirm this still installs as expected for Windows? It looks good to me on macOS.

**Pull request merged**
