### PR TITLE
Arrows recipe balance

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Sequel to #15476 as of @Coolthulhu suggestions.
Did not removed the glue as component for the recipe as I think that though glue is rare, but not uncommon to happen in inventory while there is no thread or rags nearby.

### CODE REVIEW

**Comment by Moonsabrt** [comment]
DAAAMN YOU

**Comment by Night-Pryanik** [comment]
@Moonsabrt Pardon me?

**Comment by ejseto** [comment]
I think he's confused GitHub for a forum for shooting the breeze.

**Comment by Rasip** [comment]
While 1 aluminum foil was way too little, 40 is a bit much don't you think?

**Comment by Coolthulhu** [comment]
40 is fine - it has stack size 200.

**Pull request merged**
