### PR TITLE
'Twas Brillig

### PR DESCRIPTION
**Pull request by i2amroy**
Adds some fun little Lewis Carroll references; if you kill a jabberwock with one of the larger diamond swords then you get a fun (but very rare) OHKO critical technique that triggers on .4% of your critical hits (with the broadsword at least, due to the way techniques are selected from the list the other swords only trigger either .2% or .13% of the time). It's mostly a cosmetic effect at that point, since with those weapons and skill levels often 1-2 critical hits kills whatever you are hitting anyways. Additionally in low light levels you might catch a glimpse of something in the blade of such a sword when you draw it.

Also properly updates two outdated technique arguments, adds the ability for negative weighting on techniques (only are valid one_in(abs(weight)) amount of the time), and the ability to give techniques to item instances as well as types. The last one isn't particularly useful at the time, but if we ever get around to letting players make their own custom weapons or something similar it could come in handy (and it lets me make this pull request :P).

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
By Beamish, this looks like fun!

**Comment by Frost-wood** [comment]
Looks awesome, I didn't know you could insert techniques from weapons.

**Comment by i2amroy** [comment]
>I didn't know you could insert techniques from weapons.

You can't at the moment, at least not until this gets merged in. :P

**Comment by John-Candlebury** [comment]
This is rather awesome

**Pull request merged**
