### PR TITLE
Added SIMULTANEOUS to AN-94

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by mugling** [comment]
Should be part of #17328

**Comment by BorkBorkGoesTheCode** [comment]
This is a separate issue, and I cannot afford the sizable internet bill generated by multiple rebases.

**Comment by mugling** [comment]
As it stands this PR alone does nothing as code support for `SIMULTANEOUS` is not yet implemented

**Comment by BorkBorkGoesTheCode** [comment]
Shelved until SIMULTANEOUS is implemented.

**Pull request closed without merging**
