### PR TITLE
Add "strictly_unarmed" to buff_taekwondo_static2

### PR DESCRIPTION
**Pull request by Zenefess**
#### Summary
Bugfixes "Prevent Tae Kwon Do's 'Unhindered' static buff from activating when hands are not empty."

#### Purpose of change
Addresses issue #72179 

#### Describe the solution
Added the `strictly_unarmed` property to `buff_taekwondo_static2` and set it to `true`.

#### Describe alternatives you've considered
It's a simple fix, so didn't need to think of another solution.

#### Testing
Loaded an existing save. "Unhindered" appears. Pick up freezer. "Unhindered" disappears. Drop freezer and wait a turn. "Unhindered" reappears. Repeated the process with a rifle, carving knife, and knuckle dusters; same result.
Started a new game and repeated above process with a pocket knife; same result as above.

#### Additional context
N/A

### CODE REVIEW

**Comment by Zenefess** [comment]
I realised I modified my master branch after committing. Senior moment. If it's not an issue on your end, @Maleclypse , I'll leave it as is until it's merged.

**Comment by Zenefess** [comment]
After rereading Taekwondo's description, it states "Focused on kicks, it does not benefit from wielded weapons", so not allowing the unarmed weapons to be used with the +33% damage boost would make sense.

**Comment by RedMisao** [comment]
> After rereading Taekwondo's description, it states "Focused on kicks, it does not benefit from wielded weapons", so not allowing the unarmed weapons to be used with the +33% damage boost would make sense.

I was going to comment something about wielding vs wearing weapons and give some ingame examples, but the `UNARMED_WEAPON` flag was removed from items and I'm unaware how the game considers a weapon to be unarmed.

> ...Now that I think about it, should `unarmed_allowed` be `false` for all Taekwondo buffs, since those weapons aren't attached to the legs?

`"unarmed_allowed": true` means the buff is applied when you have no weapon equipped. If you equip any weapon the buff goes away. If it's set to `false`, you don't get the buff if you're unarmed.
Similarly, `"melee_allowed": true` means the buff is applied when you have a weapon equipped. If you unequip the weapon, the buff goes away. If it's set to `false`, you don't get the buff if you're wielding a weapon.

So, by setting `"unarmed_allowed": false` you will only make the Taekwondo buffs to not be applied by being unarmed.

**Comment by Zenefess** [comment]
@RedMisao 
Ahh; cool. So what should I do about this pull request; leave it as is? Close it? I figure -- in the grand scheme of things -- this is a low priority issue when it comes to dedicating time to testing & merging.

**Comment by RedMisao** [comment]
Nvm I was wrong, setting `unarmed_allowed` or `melee_allowed` to `false` don't remove the buffs, it just means the buffs are not applied in either condition.

The PR you submitted will fix the issue of the Unhindered buff being applied while not being unarmed.

**Pull request merged**
