### PR TITLE
Add light industry basecamp

### PR DESCRIPTION
**Pull request by krulunio**
#### Summary
Content "Add light industry basecamp"

#### Purpose of change
I'm working on more basecamp types, here's light industry basecamp (2 variants) and Industrial Workshop expansion.

#### Describe the solution
Add 2 similar upgrade paths: barricade windows with wooden/resin walls; build 5 pairs of beds mattress/straw beds; build root cellar, then butchery rack; build water pump; build radio; reinforce doors.
This basecamp starts with 2 beds (1 expansion slot), kitchen_recipes_1 and fake_oven (only in 1 variant of basecamp), primitive_camp_recipes_1 and missions: gathering, firewood, foraging. The main downside of this basecamp is that it can only have 6 expansions, 1 of which must be Industrial Workshop.
Industrial Workshop starts with dismantling mission, industrial_recipes_power_lathe, drill_press, hydraulic_press, air_compressor and related fake tools. Those recipes aren't done yet.

#### Describe alternatives you've considered
1. Adding only Industrial Workshop: this was my original idea, however I noticed that office could be used as base and I decided to add whole basecamp.

#### Testing
I created and upgraded both variants, the only error I have found is that when starting blueprint recipe has wrong `"result"`, then it won't give correct `"blueprint_provides"`, so I had to use `"result"`s that don't match my naming standard. [Here](https://github.com/CleverRaven/Cataclysm-DDA/files/6704828/fbmc_lightindustry.zip) are screenshots.

#### Additional context
I was suggested to include changes from #49320. It's messy, so I included new OMs without copying PR.

### CODE REVIEW

**Comment by CaseMonster** [comment]
https://i.imgur.com/4d6JzIm.png

Is the bed supposed to be one unit over?

**Comment by krulunio** [comment]
> Is the bed supposed to be one unit over?

I didn't notice it, somehow.

**Comment by schealex** [comment]
@krulunio i really love that you are doing all thease additions to the faction camps and i'm so eager to try them out! Is there a list of the current possible locations with their possabilities and extensions etc.? Would really appreciate it. The Wiki seems to be pretty outdated.

**Comment by krulunio** [comment]
As far as I remember, NPC companions have option to tell you about valid basecamp locations.

**Comment by Maleclypse** [comment]
I can’t remember have you been updating the NPCs to list these locations you’ve added?  I’m not sure that they update themselves.

**Comment by schealex** [comment]
Yeah the npcs are listing the new locations but I thought it would be nice to have a markdown file maybe with all possible base locations and their upgrade path, pros and cons as stated in your PRs. I think that would be useful.

**Pull request merged**
