### PR TITLE
Large, but straightforward cleanup of weather

### PR DESCRIPTION
**Pull request by bkentel**
A pretty straightforward refactor. No changes to functionality; just trying to reduce compile time and needless dependencies.
- Remove all global (`extern`) variables from the header.
- Nuke dead code (can pull it from history if it's ever needed again).
- Eliminate explicit init functions and use function local const static variables.
- Flip pointer to members to regular function pointers.
- Forward declare types and remove unnecessary includes.
- Touch up a few function signatures.

### CODE REVIEW

**Comment by kevingranade** [comment]
On hold pending 0.C

**Comment by bkentel** [comment]
@kevingranade No problem. What yet needs to be finished for 0.C to go ahead?

**Comment by kevingranade** [comment]
Any bugs listed under the 0.C milestone, and the release process itself,
which usually takes me several days (workday-sized days, not evenings).
We'd also like to so some looking around for showstopper bugs.

**Comment by bkentel** [comment]
Thanks for the info.

**Pull request merged**
