### PR TITLE
[Splitting] Adds the Medical Assistant, Autocannibalistic Nanobots, and Mechanical Repeaters CBMs

### PR DESCRIPTION
**Pull request by ghost**
```SUMMARY: Content "Adds the Medical Assistant, Intravenous Needletip, Autocannibalistic Nanobots, and Titanium Joint Bearings CBMs."```

# This PR is split from #25142.

### Short version

This adds three new CBMs.
* Medical Assistant, while powered, lets you see the exact health values of yourself and monsters around you, in addition to making you better at healing yourself and installing bionics.
* Autocannibalistic Nanobots damage each body part by 1 every turn, cause 1 pain per turn, and generate 10 power. They won't damage a limb if it's at or below 25 health. Using Repair Nanobots within 24 hours of using the Autocannibalistic Nanobots has a 1 in 3 chance per turn to destroy the Repair Nanobots CBM, and doesn't heal you at all.
* Mechanical Repeaters increases crafting speed by 30%.

### Long version

Here's the specifics of the CBMs.

#### Medical Assistant

The medical assistant is a dime-sized computer chip that slots into your brain and carries a narrow-spectrum AI filled with medical knowledge. It takes 1 power per 200 turns while active. Its auxiliary effects are focused around smoothing out sharp declines:
* If first aid skill is less than 3 when using bandages or disinfectant, it is treated as being 3.
* Failure chance for bionic install is capped at 75%.
* If success chance for bionic install is 95% or higher, it's bumped up to 100%.
* If failure chance is below 75%, success chance is increased by 10%.

My initial idea was simply a CBM that allowed you to see enemy health, but I decided it would be more interesting to expand upon that. Because complex medical AIs are evidently commonplace (as every hospital has an Autodoc), a slimmed-down, less useful version seemed natural. Software interactions between the two makes bionic installation a smoother experience, since it can accommodate for the quirks of your body rather than the Autodoc having to guess about it.

#### Autocannibalistic Nanobots

There aren't many power generation CBMs, and I thought this presented a very interesting tradeoff. It's a huge amount of power generated - 10 power per point of damage you take - but because Repair Nanobots are nullified, sleeping is the only way to regenerate the health lost effectively, and the pain caused by the nanobots makes that difficult.

I consider it mainly an "emergency power" type of bionic. If you tunnel through a wall that you can't get back through, and you'll starve to death if you don't get out, you can afford to bring yourself to near-death to survive. Lategame characters can also exsanguinate themselves if they run out of power for their welder, which is amusing.

#### Mechanical Repeaters

A crafting speed increase is something I've always felt is long-overdue, and this attempts to remedy that. By allowing your hands a greater range of movement and motors to perform tasks and command your hands automatically while you focus on other things, it provides a 30% increase in crafting speed to most recipes. Cooking and chemical recipes, however, are unaffected, as many things such as boiling water can't be sped up that way.

### CODE REVIEW

**Comment by Lorith** [comment]
Really like everything in this except the titanium joints, not sure on that one.

**Comment by mrkybe** [comment]
I like all of these also.  Perhaps the **Titanium Joint Bearings** could be split into two CBMs?  Like, **Titanium Hip Replacement** which gives you the carrying capacity buff and **Ceramic Omniball Finger Joints** for the crafting bonus?

**Comment by tyrael93** [comment]
They're all good. High time we have a bionic that speeds up crafting.

**Comment by mrkybe** [comment]
@Lorith makes a really good point.  Does batching/NPC assistants have the same problem?  If not, then it could work by providing the benefit of always having an NPC assistant nearby when crafting? or from batching?

If batching and NPC assistants do have that issue, maybe water can just boil faster.  🤷‍♂️

**Comment by Xhuis** [comment]
That's a good point about the mechanicals. I can restrict it pretty easily to certain mob types.

Titanium Joint Bearings being split up seems like a good idea.

I'll try to implement a categorical split for recipes, so that things like cooking are still the same.

**Comment by kevingranade** [comment]
#### Medical Assistant
Agree about limiting it to living creatures, otherwise great.

#### Intravenous Needletip
I'm not sure how this works, is it like a permanent iv port? Do you plug an ampule in somewhere, or pour the drug into something? Do you have a needle that sucks in the drug?
No problem with the concept, just confused.

#### Oxygenator
Is this an external lung, or does it make your lungs work better? Again no problem with the effect, but the description is a bit unclear.
Depending on how this works, it could also enhance short term fatigue recovery.

#### Titanium Joint Bearings
Agree on splitting the effects.
No problem with the load bearing effect.
I think the crafting boost is not a good fit, I think "learned economy of motion" is going to be way more impactful than "ability to flex joints faster".

I'm not against a crafting speed boost in principle, but the mechanism needs to be better, maybe an autopilot for crafting that automates repetitive motions?

**Comment by Xhuis** [comment]
Needletip is a retractable needle in your fingertip that draws liquid like a syringe, but instead of being held in a syringe the liquid is fed directly into your bloodstream.

Oxygenator is not actually new, and already exists in the game as a tool to help breathe underwater. This is merely a new effect. The existing bionic is just described as "an advanced oxygen delivery system."

**Comment by kevingranade** [comment]
> Needletip is a retractable needle in your fingertip

No problem with that then, makes sense.

> Oxygenator ... exists in the game as a tool to help breathe underwater.

So does it only work underwater? It seems unlikely to operate both above and below water, though I could be missing something.  Does it extract oxygen from water? Does it store air?

**Comment by Xhuis** [comment]
I'm not sure fluffwise, since as I mentioned, it's not described well. It works underwater, but also can be activated to speed your stamina recovery even outside of water, so I figured that it made enough sense to include the asthma tweak.

**Comment by Kelenius** [comment]
>If success chance for bionic install is 95% or higher, it's bumped up to 100%.
>If failure chance is below 75%, success chance is increased by 10%.

So if you start with a failure chance of 4%, you get 0%. But if you start with a failure chance of 8%, it's below 75%, so success chance is increased by 10%, bringing you to 0% again?

>crafting speed is increased by a flat 30%

Does it apply to **everything**? It's weird that they allow you to boil water faster.

**Comment by Xhuis** [comment]
Your point about the bionic success chance made me realize that that is indeed the case. I'll do some numbers tweaks to fix that.

I do agree about the crafting speed, which is why I'll take a look at it to make it apply selectively instead, likely to things that do use your hands more (such as electronics recipes, as opposed to cooking food or smithing metal.)

**Comment by Maddremor** [comment]
Looks nice overall. Something like the needletip actually [exists IRL](https://en.wikipedia.org/wiki/Peripherally_inserted_central_catheter). 

I'm a bit sceptical on the nanobots though. Even if the standards for realism is pretty relaxed when it comes to bionics, I still consider it a weird precedent to have human meat be the most high effect energy source. If you want energy at the cost of corporeal damage, I would prefer to have something akin to pushing the microreactor into overdrive.

**Comment by Lorith** [comment]
The microreactor originally did damage to you if you put too much into it, but I was requested to remove that aspect or at least seriously reduce it before it would be merged, so you only notice anything if you put stupid amounts of effort into having it happen.  Additionally it can be used as 'overdrive' by using the plutonium filter cbm for a bit, which increases the rate the power is generated, but not the total amount.

As to nanobots being the most effective, internal furnace would still be fare better due to it being a buggy piece of crap that lets you eat robots and fire extinguishers for stupidly high amounts of power, in addition to eating basically anything you find on corpses.

**Comment by Maddremor** [comment]
> As to nanobots being the most effective, internal furnace would still be fare better due to it being a buggy piece of crap that lets you eat robots and fire extinguishers for stupidly high amounts of power, in addition to eating basically anything you find on corpses.
Don't get me started on the Internal Furnace, I really want it gone from the game, but that's not in the scope of this PR. 

Considering that Power Storage is constructed with plutonium, perhaps you could squeeze out extra power from them at the cost of permanently lowering your power capacity.

**Comment by TechyBen** [comment]
> Don't get me started on the Internal Furnace, I really want it gone from the game, but that's not in the scope of this PR.

Making it partly external would work. Peltiers (heat transfer to power, works both ways as cooling/heating or power from heat gradients) exist in real life. But need external cooling (in game could use own blood stream XD) and are low yield.

So in game, the "CMB Thermoelectric Generator" could work. Low power output, but easy to use.

Either same mechanic, just description is "you burn up the towel and get X power from your Thermoelectric Generator CMB". Or require you to stand next to a fire and "use" CMB/fire to get CMB power.

Then either track and simulate heat absorption into the body then loss, or just make the player character hotter each time (until they are lava! :P ) you use it. The player would then have to manage waiting to cool down manually.

**Comment by sfsworms** [comment]
For the crafting aid CBM, how about some "Autonomous Off-Hand CBM": Your off-hand is fitted with some basic computer so it can do simple tasks on its own while you craft. The effect could be to set a minimum batch crafting modifier. (Normally, if you're assembling some electronic or something, you can't really make batch of them because they each need to be assembled, but having your off-hand do its thing would let you prep the next one while you assemble the one you're working on).

**Comment by kevingranade** [comment]
Please take discussion of other CBMs elsewhere, this is a noisy enough issue as it is.

> It works underwater, but also can be activated to speed your stamina recovery even outside of water, so I figured that it made enough sense to include the asthma tweak.

This is a detail I missed, it already somehow functions both above and below water.  I don't have a problem then.

I recommend you fork off the needletip, oxygenator, and possibly the load bearing version of the joint replacement CBM, as it sounds like they can be merged almost immediately, and we can narrow the scope of the discussion to crafting enhancement and medical cbm, which are both a bit more involved.

**Comment by Xhuis** [comment]
I've had a fluff design for the nanobots as that they tear off pieces of your body and use them for biofuel. No energy is gained magically, as it's just the potential energy being transferred into bionic power.

As for the name, it is illegal. It's used in military and scientists on occasion as I was trying to imply some sort of internal corruption or black ops operating under the radar who weren't afraid to resort to more extreme measures - or, hell, perhaps even installed and then controlled remotely as a blackmail agent. Set up dead drops for us or the nanobots eat your organs.

I called it Autocannibalistic because the nanobots were housed on you, and thus used parts of you for fuel despite living in your body.

**Comment by Night-Pryanik** [comment]
It could be named like `Autophage Nanobots`.

**Comment by MT-Arnoldussen** [comment]
>This comes from something I heard from someone in Discord about a movie in which cyberjunkies used tubes to their brains to inject drugs into themselves.

That was me. I recently found out what movie I got the idea from and it's [Redline]https://youtu.be/aQoQ2MUnlok?t=3m27sl). Turns out I misremembered that scene quite a bit, because he was using the direct brain access to control a plane, and not to do drugs!

I still think it's a fun idea though, and I'm glad to see you implemented it. I'll make sure to add this to a profession or two after it gets merged.

**Comment by Xhuis** [comment]
Alrighty, split is complete. I'm gonna do some testing to make everything works as intended and then push the commit that finalizes the split. The other PR can be found over at #25142.

**Comment by nexusmrsep** [comment]
Jenkins wants src/crafting.cpp to be AStyled.

**Comment by Xhuis** [comment]
As Medical Assistant is quite a significant bionic on its own, and the PR has fallen into conflict hell, I'll be closing this and re-opening some of its changes shortly in different ones.

**Pull request closed without merging**
