### PR TITLE
bearings recipe metal requirements

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary

```SUMMARY: Bugfixes "Fix bearing requiring both "weight" and "steel""```

#### Purpose of change

Crafting bearings requires both weight (lead/gold/silver...) and steel. So the bearings were always made of steel and some other random metal.

Lead bearings definitely should be possible for ammo use. Bearings from other metals make sense too as lead replacement.

You should be able to make the bearings from one metal only.

The amount of metal required was also wildly inaccurate. Crafting 0.50 kg of bearings required 6 kg of steel and 0.15 kg of other metal.

#### Describe the solution

Moved "steel_standard" from using to component.

Changed the material numbers so that it now requires 0.50 kg of steel or 0.51 kg of other metals.

#### Describe alternatives you've considered

If there are uses that assume hard steel bearings then the softer metal barings for ammo use could be split to separate item.

#### Testing

Recipe works.

#### Additional context

Before:
before

After:
after2

### CODE REVIEW

**Comment by Brian-Otten** [comment]
You changed the amount of material going into the bearing (steel or gold VS steel and gold) without changing the amount of bearings produced. you should probably audit the recipe so there is an attempt at conservation of mass and see what the correct amount of bearings would be.

**Comment by Hirmuolio** [comment]
Yeah the weights seem to be all over the place.
Those steel parts weight 6 kg while the other metal parts weight 0.15 kg.
The resulting stack of bearings weight 0.5 kg.

**Comment by Mecares** [comment]
Are bearings used in any crafting recipes or only as ammo? Because bearings made from lead sound like a terrible idea if used as actual bearings to me. Maybe make them uncraftable and instead use the crafting recipe to craft a similar item called sling bullets?

**Comment by Hirmuolio** [comment]
I am not seeing it used in any recipes other than soime shot recipes.
It is in some uncraft recipes. But that just means you get bearings from those items. Nobody has implemented recipes for player crafting those items yet.

**Pull request merged**
