### PR TITLE
Spaces around colons in comestibles

### PR DESCRIPTION
**Pull request by Cyrano7**
Strictly for organization and my sanity. From issue https://github.com/CleverRaven/Cataclysm-DDA/issues/15791 Should make searching and macro functions easier in the future. Sorry if this is too many line changes.

### CODE REVIEW

**Comment by mugling** [comment]
This just adds a space before the colon?

Such changes to formatting have the disadvantage that they break `git-blame` and similar tools making it harder to check when an item was most recently updated. Better formatting does aid readability so it is of course a subjective balance.

I'll forward the argument used by the PostgreSQL project that you restyle a whole block when you have something to change within that block (fields to add, remove etc).

**Comment by Cyrano7** [comment]
@mugling I should add that there were a few spaces added after some colons also.

**Comment by mugling** [comment]
Sure, but that's still just pure formatting changes. I'd wait to see what other opinions are posted.

**Comment by Mshock777** [comment]
So should we use spaces around colons from now on in all jsons?
[https://github.com/CleverRaven/Cataclysm-DDA/pull/15822/files?w=1](https://github.com/CleverRaven/Cataclysm-DDA/pull/15822/files?w=1) can be used to see if there are only whitespace changes.

**Comment by Cyrano7** [comment]
Well Id also like to add to the formatting argument that since comestibles is so big still the only way to find anything is with the search function. If you don't know about the different formats your going to get misleading results or miss changing something. That's what happened during the last round of json optimizations and migrating earlier this year. Or if I wanted to add something to all items with a "comestible_type" : "DRINK" value some will be missed.

**Comment by mugling** [comment]
@Cyrano7 searching for `"DRINK"` should be sufficient in that case.

You're answer suggests you are unaware of regular expressions - your recent work is a good use case for this and I had presumed that was how you were completing it?

**Comment by mugling** [comment]
@Mshock777 good point, I forgot about that the option to ignore whitespace

**Comment by Cyrano7** [comment]
@mugling That was a bad example that I just pulled off the top off my head.

**Comment by mugling** [comment]
@Cyrano7 Sure. I don't want to dissuade you at all from working on the JSON but that's a lot of lines to review for just a change in formatting.

> comestibles is so big

Yes, it really wants splitting into small units, possibly starting with `comestibles/meds.json` and continuing from there

**Comment by Cyrano7** [comment]
@mugling I'm aware of regular expressions. Its not me i'm worried about. The level of experience needed for contributing via the json files is low so making it easier and safer for everyone including myself is more what I was going for. I defiantly agree that splinting things up is the ideal move in the future.

**Comment by Cyrano7** [comment]
As for reviewing and the origin of the changes. They were made with a macro in notepad++ so I'm pretty confident that there shouldn't be any mistakes if that means anything. I will thumb through and double check though.

**Comment by mugling** [comment]
> I will thumb through and double check though.

running `jq` with the script `. []` on the before and after versions then checking the output is equivalent via `diff` could work.

**Comment by Cyrano7** [comment]
"I will thumb through and double check though" is how I talk irl and spills over into how I type. I'm not actually going to print it and thumb through it. All the tests on my end aren't coming up with anything unusual.

**Comment by Cyrano7** [comment]
@mugling I should say thank you for the suggestion but I have to add that with my level of understanding in these sort of things I can not comprehend that sentence.

**Comment by Mshock777** [comment]
What do you think on removing all spaces inside square brackets, `[23,23]` is easier to read than 
`[23, 23]`

**Comment by Cyrano7** [comment]
@Mshock777 So @kevingranade outline some things in this issue https://github.com/CleverRaven/Cataclysm-DDA/issues/15791 I think that's a good idea and it is easier to read. But I think we should save some purely cosmetic stuff for after we split up comestibles like @mugling said.

**Comment by kevingranade** [comment]
I mostly agree with what @mugling said, with the caveat that if we can do it just once it might be worthwhile.  The problem is without some kind of auto-formatter we can't guarantee that we're only going to do it once, because regressions can go unnoticed in new PRs, which can be very substantial in size and sometimes have lived outside the main repository for a long time.

**Comment by Cyrano7** [comment]
So I been thinking about closeing this as it will be easier to do this while breaking up comestibles in the future. I'll look into doing it when I get back from vacation. I can also just add the rest of the styling as I do it. Much less hassle in the long run.

**Comment by illi-kun** [comment]
Enjoy your vacation!

**Comment by Cyrano7** [comment]
Thanks!

**Comment by Cyrano7** [comment]
@mugling Would the best way be to have a new file in the items folder called "med"? and put all the comestibles of type med there from all the different files?

**Comment by mugling** [comment]
Yes, but for consistency name the folder `comestible` and then the file `med.json`

**Pull request closed without merging**
