### PR TITLE
Nether Monster Corpses - Yugg

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Our Nether monsters have a plethora of different things that happen to their corpses on death. While this is on brand for chaos bullshit the nether is, we can do better than having them always disappear or just... give normal corpses, like this guy here.

#### Describe the solution
- [x] Slightly rebalance the stats for the yugg - remove dodge, increase size, give it ``GOODHEARING, RANGED_ATTACKER, PUSH_VEH``
- [x] Add three new corpse items - rubber yugg corpse, oversized fleshy tube, jade yugg statue
- [x] Add new mutagenic flesh - obtained from the oversized fleshy tube, supposed to give random mutations when ingested
- [x] Add new deatheffect for Yugg that gives one of five results in the form of corpse undergoing material transmutation - steam (spawns steam fields), mutagenic flesh, rubber, glass (pile of black glass shards), and jade

#### Testing
I was able to get the different death effects to fire, so I consider it working. If there's any issues I haven't managed to catch them in testing

#### Additional context
The reason Yugg goes first is that it was the one most edible out of the bunch, and it really rubbed me the wrong way

### CODE REVIEW

**Comment by GuardianDll** [comment]
\> glass (pile of glass shards)
i surely hope glass shards are accelerated toward any living and unliving creatures around?

**Comment by Karol1223** [comment]
> glass (pile of glass shards) i surely hope glass shards are accelerated toward any living and unliving creatures around?

So did you ever figure how to do that for your bombardier boomers so I can steal it from you, or are you trying to fool me into figuring out how to do this so you can steal it for the boomers? 🤔

**Comment by GuardianDll** [comment]
sadly there is no proper way to use `shrapnel` from spell/EoC side, unless you want to make a spell, that just explode around

**Comment by Standing-Storm** [comment]
> and take away HAS_MIND which appears to be a flag cargo culted across most nether creatures

I added that, it's used in MoM and XE.  It's for monsters with consciousness and that are capable of thought (I thought it was more interesting to imply that Yuggs were sapient). If Yuggs are just animals, they shouldn't have it.

**Comment by Karol1223** [comment]
> > and take away HAS_MIND which appears to be a flag cargo culted across most nether creatures
> 
> I added that, it's used in MoM and XE. It's for monsters with consciousness and that are capable of thought (I thought it was more interesting to imply that Yuggs were sapient). If Yuggs are just animals, they shouldn't have it.

To be fair, when I read what the flag implies I assumed it was something used in MoM but I didn't check GitBlame. I laughed around a little on the devcord about this meaning Yuggs just find it funny to mutate survivors into weird shit, didn't realize it was intentional. The flag doesn't change anything for me so I'll give it back to them

**Comment by Karol1223** [comment]
@GuardianDll I'm gonna need your review as to why the hell do the messages I wrote for the EoC not get printed

**Comment by fairyarmadillo** [comment]
If you are looking for more nether critter corpse ideas, either here or in a future PR, having some of them petrify and rapidly burn into a pile of quicklime would be both really cool and situationally handy. There have been a few occasions where I needed a ton of the stuff and it can be kind of annoying to track down.

**Comment by TheSaddestGoomba** [comment]
> If you are looking for more nether critter corpse ideas, either here or in a future PR, having some of them petrify and rapidly burn into a pile of quicklime would be both really cool and situationally handy. There have been a few occasions where I needed a ton of the stuff and it can be kind of annoying to track down.

The Nuckelavee may be a good choice for that, though with washing soda instead of quicklime. There are elements of period folklore that claim burning seaweed for soda ash would enrage them. Makes some sense they would collapse into a steaming pile of what they hate.

**Comment by Karol1223** [comment]
> If you are looking for more nether critter corpse ideas, either here or in a future PR, having some of them petrify and rapidly burn into a pile of quicklime would be both really cool and situationally handy. There have been a few occasions where I needed a ton of the stuff and it can be kind of annoying to track down.

I do need ideas, but I am still really trying to feel out just how helpful I want those corpses to be. Keep in mind that nether monsters are infinitely renewable. I do not want to make minecraft-esque material farms. I already am making those for glass and rubber with this, and I don't like that.

> The Nuckelavee may be a good choice for that

Full disclosure, I likely will not touch the Nuckalavee at all with this project. It's currently my least liked Nether critter since it is 100% just a direct rip from folklore. I feel a similar way about the albino penguin but it gets more leeway because penguins are awesome.

**Comment by GuardianDll** [comment]
\> I already am making those for glass and rubber with this
Replace glass with black glass, iirc it's completely useless

**Comment by Maleclypse** [comment]
I've resolved the conflict and replaced the special attack.  Everything else I left as you have adjusted.

**Pull request merged**
