### PR TITLE
Backport #77390 "Make battery chargers work outside the reality bubble"

### LINKED ISSUE #42911: Can't recharge batteries outside the reality bubble
# Describe the bug

It seems that in the latest experimentals, when outside the reality bubble the "battery charger" and the "recharging station" don't recharge any battery.

# Steps To Reproduce

1 - Install a battery charger and a recharging station in a vehicle with enough battery to make the charging.
2 - Activate them and put a battery "on them".
3 - Go away till they are out of your reality bubble.
4 - Wait 8 hours or more and come back.
5 - Notice that they didn't recharged even a bit of the battery power.
6 - Try waiting 8 hours or more near them and notice that they recharged a lot of energy to the battery.

# Expected behavior

Those parts should update once they get into your reality bubble, calculating how much energy was recharged and drained for this as needed.

# Screenshots

Not needed.

# Versions and configuration

I am using using the CDDA 0.E-b10900 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

None.

### PR DESCRIPTION
**Pull request by ThePirate42**
#### Summary
None

#### Purpose of change

Fixes #42911 in 0.H

#### Describe the solution

Backport #77390 that fixes the issue

### CODE REVIEW

**Comment by Maleclypse** [comment]
I'm assigning @kevingranade because we are too close to release for me to feel solid about backports at this point.

**Comment by ThePirate42** [comment]
Yeah sorry, I hoped to sneak it in since I usually play stable and I always found this bug annoying

**Comment by ThePirate42** [comment]
I tried because I wasn't sure of how soon exactly the release would have happened, but if a merge is considered too risky at this stage it's perfectly understandable.

**Comment by Night-Pryanik** [comment]
O.H was released, this is no longer relevant?

**Comment by ThePirate42** [comment]
> O.H was released, this is no longer relevant?

I guess? I'll close it for now.

**Comment by Maleclypse** [comment]
> > O.H was released, this is no longer relevant?
> 
> 
> 
> I guess? I'll close it.

Please reopen we are considering this for a point release PR

**Pull request merged**
