### PR TITLE
More npc locations revival

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Add more NPC locations"

#### Purpose of change

The purpose of this change is to add more places where NPC's can spawn, either alone or in groups; providing a greater variety within the world of Cataclysm.

This adds more NPC's in various places. Currently, two random lone NPC's will spawn at evac shelters and homeless camps. This also adds a homeless camp with a group of survivors; so far including a chain of missions and an ability to trade. Additionally, this adds several new varieties of evac shelters.

Essentially, this is a revival of pull request #55196, with great thanks to onura46 for resurrecting it.

#### Describe the solution

This branch contains the same content as #55196, adding various NPCs to the world of Cataclysm. onura46 added cooldown timers for certain rare products sold by the chemist, fleshed out dialogue, and had the player spawn in the basement of the evac shelter for the “Infested Shelter” challenge start.

#### Describe alternatives you've considered
 None

#### Testing
According to onura46, all code runs smoothly and works as intended.

#### Additional context

The original content was inspired by two Discourse boards, seen below:

https://discourse.cataclysmdda.org/t/more-evac-shelter-varieties/27336/9

https://discourse.cataclysmdda.org/t/npc-s-what-do-you-want-changed-and-improved/27102/18

### CODE REVIEW

**Comment by haveric** [comment]
This is way too big for anyone to even consider reviewing this. From a quick glance, I can already see that that it's including an entire soundpack and it's not using the new structure for shelters. This seriously needs to be broken up into more reasonable chunks.

**Comment by MNG-cataclysm** [comment]
> This is way too big for anyone to even consider reviewing this. From a quick glance, I can already see that that it's including an entire soundpack and it's not using the new structure for shelters. This seriously needs to be broken up into more reasonable chunks.

That's underway, the pull request will reopen once finished.

**Comment by onura46** [comment]
Yeah, this was my mistake. I don't think my master branch is clean like I thought it was. I'm working to fix that before contributing any more PRs and I'm coordinating with MNG to do a proper one. Sorry for the confusion!

**Comment by MNG-cataclysm** [comment]
This pull request's branch has been terminated, new one can be found in #57483.

**Pull request closed without merging**
