### PR TITLE
NPCs get mad if you mess with their property

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Features "NPC factions get mad if you mess with their property by smashing or deconstructing it etc"

#### Purpose of change
RUIN THE GAME

Currently the NPC factions don't consider ownership of anything besides items. You can break down their walls right in front of them without them even raising their voice.

#### Describe the solution
Make them ANGRY! Anytime you're at a NPC camp (oh right I added those) we can simply assume the NPCs should own that stuff. No need to make custom zones, or rely on mapgen. Just if you're nearby, they own it. There's lots of other places you can go.

Currently this does not check if anyone is nearby to actually see you, or assess whether they should 'know' of your offense. It is simply telepathically communicated to them.

Currently this draft only handles the following:
examining furniture/terrain (not serious offense, is public goods)

smashing (is serious offense, not public goods)

grabbing furniture (not serious offense, not public goods)
(Note this only triggers with *new* grabs, dragging stuff doesn't spam you every turn.)

construction (is serious offense, not public goods)

sleeping (not serious offense, is public goods)

tree cutting (is serious offense, not public goods)

I am open to ideas for where else this needs to be checked.

Currently there is very little nuance to their reaction. You simply get warned and if you ignore the warning you take a relationship hit. The more serious offenses (smashing down their walls or trying to) cause a very big relationship hit, otherwise it's moderate. They don't try to talk to you and warn you, like if you steal items.

#### Describe alternatives you've considered
Mapgen-based ownership zones

#### Testing
Not nearly enough yet, hence in draft. I am sure that even after I have tested this will cause many issues and require lots of followup work. I would like to thank our experimental players in advance for their thorough playtesting :)

https://github.com/user-attachments/assets/0f77bb18-e229-4411-b3af-4604341059f4

#### Additional context
~~So far I know of exactly one issue this will cause: The refugee center's boarded up back bay. If you're not allowed to smash, grab, or interact with the furniture in the way there's no way to get in. I don't have a solution for that yet.~~

Shouldn't be an issue https://github.com/CleverRaven/Cataclysm-DDA/pull/76810#issuecomment-2395315378

### CODE REVIEW

**Comment by Fris0uman** [comment]
> I don't have a solution for that yet.
Mayybe have it so you have to talk to a guard to tell them you're ready and that triggers a map update that un board the door?

Is there room to get some usage allowance later on? Like if they like you you can start using the fireplace and craft benches?

**Comment by RenechCDDA** [comment]
>Is there room to get some usage allowance later on? Like if they like you you can start using the fireplace and craft benches?

I'm pointing it at basecamp::allowed_access_by() right now, which permits it if you are a member of the owner faction or if the faction has the "share my stuff" relationship to the requesting character (you).

https://github.com/CleverRaven/Cataclysm-DDA/blob/5f6f5e06a32ce82eac22e3ccebac27f1d1640c0f/src/basecamp.cpp#L335-L337

We could make the less invasive checks (like examining furniture/appliances) use the "water_request" bool, which instead checks if they have the "share public goods" relationship

https://github.com/CleverRaven/Cataclysm-DDA/blob/5f6f5e06a32ce82eac22e3ccebac27f1d1640c0f/src/basecamp.cpp#L339-L343

Discriminating on *what the examine action actually is* is nasty though, it would probably mean hardcoding a list of allowed actions. i.e. if examining a fireplace to start a fire is allowed but using their furniture is not

**Comment by RenechCDDA** [comment]
Since then I added a discriminator so that the easier asks (examining furniture/terrain) goes by the "shares public goods" rule. AFAIK exactly 0 factions have this relationship to the player, but the potential is there at least, and it's a simple json flip. Still plugging the check into a bunch of other places before I even bother pushing it again.

**Comment by PatrikLundell** [comment]
It should always be permitted to examine, as that's a common method to look at stuff. The issues should start when you go one step further and try to do things beyond looking at it, i.e. activate stuff. This may mean you may have to disable automatic activation (which I think may be a good thing anyway, as I've had the issue that doors are broken up when I try to pick their locks, because they're of an unpickable kind, which is annoying, especially if it means also triggering an alarm).

If I remember correctly, Cody, in her anti capitalist wisdom, accepts a donation to the people from you to use her stuff. If that works currently you may have something to study as a model. If it doesn't, you've got another problem case to solve.

**Comment by RenechCDDA** [comment]
>It should always be permitted to examine, as that's a common method to look at stuff. 

Hmm, what do you mean by this? It doesn't restrict you from seeing if the tile can be examined(activated), just if you actually try to activate it it'll warn you off with the prompt. I don't think I can delay it anymore than that short of putting a check into each individual iexamine:: function at an appropriate point. That *could* be done, but I'm not sure it's necessary.

As an example, if there was a filled charcoal kiln which needed to be examined to be finished you could *see* that it had an action, but trying to finish it would warn you off. So it would not be possible to actually finish spawning the charcoal in unless the local faction allowed you or you were willing to transgress them.

Thanks for the note about Cody, I'll have to look into that.

**Comment by PatrikLundell** [comment]
Your description seemed to indicate that they'd get annoyed if you went around 'e'xamining stuff, but if you mean continuing on to perform an action while there we're on the same page (as long as examining doesn't automatically result in also performing the action. If there are any such cases they should be moved to requiring an additional step).

**Comment by RenechCDDA** [comment]
Nah it's queried/checked before the iexamine_func->call call, so it's never possible to accidentally run the iexamine. You can't accidentally bother the local faction without explicitly getting a warning for it first.

I've considered tying it into the thief mode check to suppress it if people are doing something like... smashing a wall 20 times, but it stops checking if the faction is already guaranteed hostile. If you're doing a minor action it's a 5 rep hit, and assuming you start at 100 rep you could only do that 22 times before they are guaranteed hostile. So not much point in bypassing the check even in that case.

I'll make a more comprehensive video example before I pull this out of draft.

**Comment by db48x** [comment]
What about chopping down trees?

**Comment by RenechCDDA** [comment]
> What about chopping down trees?

Thanks I forgot about that one.

I added a specific check inside iuse::chop_tree, but I'm not terribly happy about that. It's better than blocking all iuse actions, but I hope we don't have to check this on every specific iuse.

**Comment by RenechCDDA** [comment]
Hilariously I cannot find a way to actually trigger the back bay mission and check. However, it looks like it should clean up the furniture barricade:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f71f48dc8ed6e02ff7416d211992fe1dd9426594/data/json/npcs/refugee_center/surface_refugees/NPC_Boris_Borichenko.json#L616-L623

So I guess we're good to mark this as ready for review.

**Comment by RenechCDDA** [comment]
-That actually happens at the end of that mission

-I am a big dumb dumb

-The mission that needs to open the back bay is actually offered by smokes

I pushed a new commit to handle smokes' mission.

https://github.com/user-attachments/assets/3f2cb163-b3cb-4a52-a489-74d1864276c6

**Comment by tenehea** [comment]
The back bay should probably still have barricade remnants.. I don't really see the point in completely removing them. It is the difference between a reasonable early-mid game fight and instant death button

**Pull request merged**
