### PR TITLE
Encounters out in the fields

### PR DESCRIPTION
**Pull request by John-Candlebury**
#### Summary
Content "Add a variant of standing stones for fields"

#### Purpose of change

Its an Yrax content PR. I'll add a small chance for these to spawn in meatlabs later.

#### Describe the solution
This adds a scientist type Yrax robot and its defensive drones. They are only active during portal storms.

Also includes a likely bugfix for character aggro based on hurt allies.

#### Testing
Made sure the weather based activation happened properly and that the monsters worked properly in general.

### CODE REVIEW

**Comment by KHeket** [comment]
Is there any use of this monoliths for now? Because I met them in the field when there was no portal storm and thoght, that I can have any quest at hub for it, but as I can see - there is no use for it. And also I cant deactivate it with hub12 duzzle rifle

**Comment by John-Candlebury** [comment]
Its not really intended to be anything but a weird encounter.

**Comment by Procyonae** [comment]
```diff
  {
    "id": "sphenocorona_active",
    "type": "SPELL",
    "name": { "str": "Activate Sphenocorona", "//~": "NO_I18N" },
    "description": { "str": "Golden monoliths to Sphenocoronae.", "//~": "NO_I18N" },
    "copy-from": "activate_yrax",
-    "targeted_monster_ids": [ "mon_yrax_sphenocorona_inert" ],
+    "targeted_monster_ids": [ "mon_golden_monolith" ],
    "effect_str": "mon_yrax_sphenocorona"
  },
  {
    "id": "sphenocorona_inactive",
    "type": "SPELL",
-   "name": { "str": "Activate Sphenocorona", "//~": "NO_I18N" },
+   "name": { "str": "Deactivate Sphenocorona", "//~": "NO_I18N" },
    "description": { "str": "Sphenocoronae to Golden monoliths.", "//~": "NO_I18N" },
    "copy-from": "activate_yrax",
    "targeted_monster_ids": [ "mon_yrax_sphenocorona" ],
    "effect_str": "mon_golden_monolith"
  },
```
Does this look sensible? `mon_yrax_sphenocorona_inert` doesn't appear to exist and throws an error when the attack is called

**Comment by John-Candlebury** [comment]
Please make an issue, I'm going to forget about it in here.

**Pull request merged**
