### PR TITLE
Adds missing mod slot to rifle.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Anti materiel rifles have to have grips, or else you wouldn't be able to
handle their recoil.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Plus, you know, holding the gun. o3o

**Comment by Rivet-the-Zombie** [comment]
I've always thought that the specific 'grip' slot is for the sort of firearms that have a separate pistol-type grip, as opposed to things like firearms with hunting-type stocks. But either way, giant rifles of this sort absolutely require a good stock and a proper set of grips.

**Comment by chaosvolt** [comment]
True, or more specifically ones that can be readily swapped out. So it's not so much a LACK of a grip,, just whether the grip is meant to swapped out. Which it likely is on that, yeah.

**Comment by Midaychi** [comment]
Offtopic: when is supported mode so you can crouch by cover and get better less recoil/dispersion?

**Comment by chaosvolt** [comment]
Going off-topic to bring up a related issue gets you yelled at.

Going off-topic to an utterly unrelated issue gets you eaten then yelled at. o3o

**Comment by Midaychi** [comment]
Well you're going on about how important grips are, for rifles that only insane people would shoot standing. The offtopic part was irony.

**Comment by chaosvolt** [comment]
He as in me, or her? :v

**Comment by Midaychi** [comment]
Her. What I'm saying is irrelevant anyways. Sorry.

**Comment by chaosvolt** [comment]
It's fine, though opening an issue for the suggestion might be worthwhile, if it isn't already a thing.

**Comment by Midaychi** [comment]
I extrapolated it into a suggestion on the forum.

**Pull request merged**
