### PR TITLE
Sleep v. Pain Changes

### PR DESCRIPTION
**Pull request by i2amroy**
This PR:
1) Makes only pain which passes the pkill threshold trigger stop messages.
2) Raises the "something hurts" threshold for pain to 2 for activities like crafting (thus stopping most "ache" type pains from constantly asking if you want to stop).
3) Makes pain much less likely to wake you up from sleep. The exact chance is modified by mutations like HEAVYSLEEPER.
4) Having untreated pain causes an overall reduction in how restful your sleep is. Somewhere around 50 untreated pain your sleep will be about half as restful, and around 100 it should come close to stopping being restful. (Just estimates though, the actual value to determine that is a bit more complicated).

Note: This doesn't change the chance of getting hurt waking you up. If a zombie hits you and you take damage then you should be able to wake up just like normal, it just greatly lessens the chance of diseases constantly forcing you to wake up when they increase your pain levels.

### CODE REVIEW

**Comment by Zireael07** [comment]
> 2) Raises the "something hurts" threshold for pain to 2 for activities like crafting (thus stopping most > "ache" type pains from constantly asking if you want to stop).

Yay for quality of life changes!

**Comment by Coolthulhu** [comment]
I'm not so sure about that fatigue regeneration reduction. At those values, it looks like it will only affect survivors who were heavily hurt by some weird effect and thus easy to miss.

What is the intent? Giving damaged players longer sleep or representing pain inhibiting rest?

If it's to speed up healing, then it actually makes sense.

But if it's about pain hurting rest, it would make more sense to interrupt the sleep at low tiredness; make it work like partial insomnia, but not only at falling asleep, but also at waking up. Like, instead of "feeling well rested", you'd wake up earlier with a message about pain waking you up.

**Comment by i2amroy** [comment]
Pain inhibiting rest. After looking into it I found that rather than waking people up (though it does do that occasionally when it gets hit with a hard burst of pain) one of the biggest effects of pain is to essentially kick you out of the deeper levels of sleep, making the sleep that you do get much less restful. It doesn't actually wake you up, but after a night's worth of sleep you end up not much more rested than you were at the start.

Though thinking about it now, I think I might have a better way to emulate that by messing with the intensity than just a flat penalty. I'll look into it.

**Comment by kevingranade** [comment]
I think this is a better way to handle it, kicking people out of sleep is
bad user experience, I feel like doing the same for cold would also be an
improvement.
In both cases, a message after the fact like, "you slept terribly because
of (pain/cold)" would be good feedback.

**Comment by Coolthulhu** [comment]
Kicking people out of sleep randomly certainly is bad user experience, but having pain/cold/heat lower "rest cap" would make sense (it is possible to sleep in hot room - when very tired) while not being all that annoying (the only exception would be pain rising by the end of sleep, for example because painkillers wore off).

Alternatively, resting while in pain/cold should probably lower healing rate too. Otherwise it would make sense to sleep while in pain/cold in order to recover more health.

**Comment by kevingranade** [comment]
Certainly we should restrict healing, etc as well, everything about
sleeping (other than passing time I guess) should be hampered to the same
degree.

I'm not against "it's too foo to sleep" happening, with foo including pain,
light, hot, cold, noise, etc, and with all of the above offset by level of
tiredness.  In fact I think it's essential to prevent things like making NO
progress when sleeping if the environment is really bad.

Also it serves as a warning if we keep around the mechanic where you
repeatedly try to sleep until it sticks, possibly with a 'keep trying to
sleep?' prompt after the first failure, but with a 'it's too foo to sleep'
if there's no chance of getting rest.  When it's a little bad you get
warnings that you should adjust something, but if it's extremely bad the
player should refuse to try.

**Pull request merged**
