### PR TITLE
Dialed back ocular zombie vision to reduce it's calculated difficulty

### LINKED ISSUE #72276: Ocular Zombies have an anomalously high difficulty rating of 120
### Describe the bug

Ocular zombies (added in #70749 ) have an abnormally high difficulty rating of 120, likely due to its VERY high sight range.

### Attach save file

N/A.

### Steps to reproduce

Spawn an ocular zombie or look at it on the [Hitchhiker's guide](https://cdda-guide.nornagon.net/monster/mon_zombie_ocular)

### Expected behavior

A difficulty level that is somewhat analogous to the monster's actual threat level 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3155 (23H2)
- Game Version: 7d3234e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Bugfixes "Reduced ocular zombie vision range to make it less dangerous looking"

#### Purpose of change
Fixes #72276

#### Describe the solution
Because of their ridiculous `vision_day` value of 1000,, ocular zombies had a difficulty rating of 120, or "fatally dangerous". Considering they're new and don't have a sprite yet, this could easily fool people into thinking they're far more dangerous than they truly are. Ocular zombies now have a vision range of 94, which is the farthest away the monster can be from the player while remaining in the reality bubble. I am open to increasing this and making it the diameter of the reality bubble instead. I also gave them a `vision_night` rating of 10 because the thing is made of eyeballs. It seems reasonable enough to me, but I'm pinging @carlarctg for their opinion.

#### Describe alternatives you've considered
Removing the concept of monster difficulty entirely. While I did dismiss this idea more or less immediately, I did also technically consider it for a brief moment. I also considered letting someone else take care of this, taking a nap instead of fixing the bug, and many other things I will not list here because they're even less relevant to the patch. I did something reasonable instead.

#### Testing
Difficulty color of ocular zombies is less red, but still too high in my opinion.

### CODE REVIEW

**Comment by Inglonias** [comment]
I forgot the reality bubble is cube-shaped, not circuar.

**Comment by Inglonias** [comment]
I also forgot we can manually mod the difficulty, which we should probably do here, but unfortunately I don't know what that value needs to be - the difficulty calculation is a little too tricky for me to figure out on paper.

**Comment by Karol1223** [comment]
> I also forgot we can manually mod the difficulty, which we should probably do here, but unfortunately I don't know what that value needs to be - the difficulty calculation is a little too tricky for me to figure out on paper.

...are you sure we can? I was under the impression we can only manually *increase* it by the amount set in the JSON field. I'm preeeetty sure that's not what you want.

**Comment by Brambor** [comment]
If it sees you at 94, it doesn't see an NPC in the other corner, as said in Discord. I think it should, as Renech suggested, have a vision of 200.

If this PR doesn't mean to change gameplay, only difficulty, the ocular zombie still should see an NPC at maximum possible distance.

**Comment by Inglonias** [comment]
Vision changed to 200. Let me know if you're still not happy for whatever reason.

**Comment by Inglonias** [comment]
Reducing the value to 200 still causes the zombie to show as cherry red in difficulty on the sidebar. We will need to allow for negative difficulty modifiers in order to fix this issue.

**Comment by Inglonias** [comment]
I'm closing this without merging, as the acceptable solution does not actually solve the problem. This will require a code change.

**Pull request closed without merging**
