### PR TITLE
Gun volume audit for .45 Long Colt

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Content "Realistic gun volumes for .45 Colt"```

#### Purpose of change
Helps #37374. 

#### Describe the solution
Gun volume as surface area times width. 

#### Describe alternatives you've considered
None.

#### Testing
Loaded ingame. 

#### Additional context
Bond Arms Derringer(Using Century 2000), total length 5.5" and weight 21oz: https://www.academy.com/shop/pdp/bond-arms-century-2000-45-lc-410-bore-derringer-handgun#repChildCatid=4851027
Barrel Width obtained by taking measurement from hexagonal barrel: https://imgur.com/a/8ugySaR

Frame Width(frame interchanges with all Bond derringer barrels, as stated on page 14 of the manual) obtained by scaling the manual's top view to the barrel width: https://imgur.com/a/gyKRGdN
Manual for top view: https://www.bondarms.com/Assets/ProductDocumentation/BondArms_Derringer-Style_Handguns_Manual.pdf

SA Results: https://imgur.com/a/0TbpcRW

Colt Lightning Carbine(Using Uberti's steel & wood reproduction for width calculations, using Taurus's steel & polymer reproduction for surface area overall length), overall length 43": https://www.gun-tests.com/gow/long_guns/Taurus-Thunderbolt-C45BR-45-LC_14343-1.html
http://www.ubertireplicas.com/product/1884-lightning-rifle-carbine/
Overall length of 43": https://media.taurususa.com/instruction-manuals-archive/send/1581-product-manuals-archive/6448-thunderbolt-manual
SA Results: https://imgur.com/a/zBzxpdc
Barrel width for getting firearm width: https://imgur.com/a/aZbnhoc
Getting width of .994" on Uberti's blueprint after using barrel width for scaling: https://imgur.com/a/KRUzKC4

Uberti Cattleman, total length 11" for 7.5"(per description): https://www.uberti-usa.com/1873-single-action-cattleman-revolvers/
Coloring in Cattleman Nickel New Model 7.5" for binarization: https://imgur.com/a/xj2UlOM
Width of 1.308" by vertical line on cylinder: https://imgur.com/a/WzyCIsJ
SA Results: https://imgur.com/a/Xg69EWy

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Looks like it affects holsters.

**Comment by LaVeyanFiend** [comment]
I don't understand what you mean. Do you mean the ability for each gun to use a certain type of holster has changed?

**Comment by ZhilkinSerg** [comment]
> 
> 
> I don't understand what you mean. Do you mean the ability for each gun to use a certain type of holster has changed?

Some gun probably doesn't fit a holster anymore after its volume was changed. See failed tests - https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/646238960#L4592.

**Comment by LaVeyanFiend** [comment]
Ah, the Western Gunslinger doesn't like his Cattleman shrinking.

**Comment by LaVeyanFiend** [comment]
I shall do a holster audit early then in another PR to fix the Travis tests, then rebase.

**Pull request merged**
