### PR TITLE
Mutable "generic" mine

### LINKED ISSUE #52517: Bugged Mine / Mineshaft Mapgen - No Exit
### Describe the bug

While playing, I took an elevator down into a mine. Once down I found no way back up. 

### Steps To Reproduce

Default world gen

### Expected behavior

An exit would have been nice

### Screenshots

Capture

### Versions and configuration

- Windows 10
- c9d5870
build type: windows-tiles-x64
build number: 2021-10-17-0638
commit sha: c9d58704a4575e3ba450db2a32edf699b6f402db
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/c9d58704a4575e3ba450db2a32edf699b6f402db

### Additional context

[Syracuse.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7438077/Syracuse.zip)

### LINKED ISSUE #53331: Bottom of a mine scenario causes error and trapped spawn.
### Describe the bug

Every time I do the bottom of a mine start the game shows an error, and if I click continue I spawn in a completely enclosed square with random dead bodies in it and no way out.

### Steps to reproduce

1. Chose bottom of a mine scenario, (mods, character choices, etc, do not seem to affect bug).
2. Start the game.
3. An error will appear.
4. Click continue(I) to find yourself permanently trapped.

### Expected behavior

I expected to play the scenario.

### Screenshots

_No response_

### Versions and configuration

- Ubuntu 18
- Mods don't change anything (I've tested multiple configurations)
- Experimental build d85abc7 although I've had this bug in stable too.

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7689899/debug.log)

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "Mutable 'generic' mine"

#### Purpose of change
* Close #52517.
* Close #53331.

#### Describe the solution
- Added mutable mine mapgen. 
- This mine considered as a "generic" variant, without any specific theme associated to it, in contrary to thematic "amigara", "spirals", and "wyrms" variants. 
- This mine has the usual mine entrance level, shaft level, and 3 underground maze-like levels.
- On 3rd underground level there is a finale location - for now it will always be "The Thing" variant.
- This mine variant has "default" 0..2 occurrences per overmap. Reduced "thematic" mine variants occurrences twofold (from 0..2 to 0..1 per overmap).
- This mine variant has following dangers: some zombie miners population, occasional sinkholes, occasional lava currents, occasional toxic gas vents, occasional piles of metal wreckage.
- This mine has roughly two times tighter tunnel width versus a hardcoded one.
- "Formulas" for mutable tunnels layout in general was shamelessly stolen from anthill layout.
- Reworked old hardcoded mine finale layout from a boring square to something more natural-looking and interesting.

#### Describe alternatives you've considered
- Honestly I don't like the concept of "always The Thing" finale for this "generic" mine variant. But unfortunately at the moment I couldn't invent some good "generic" finale for "generic" mine, so I left this finale for now. I'd be glad if someone suggests "generic" finale so I could implement it, not necessarily in this PR.
- I don't like the original concept "mine finale with all its dangers and artifact as a starting location", so I considered creating a separate starting location somewhere in the tunnels, so player could have a choice of finding the finale or rushing to the mine exit. But for now I left it as is.

#### Testing
- Debug-spawned `Generic mine` overmap special and strolled from ground level to the finale, checked for mapgen errors.
- Selected `Bottom of a Mine` scenario, started in a finale, checked for mapgen errors.

#### Additional context
One of the major issues with this PR is that until #54172 is resolved, mutable mines will spawn without any connections to road network, like this:
изображение

I don't know whether this issue is a blocker for merging this PR.

Example of -2 level of mine tunnels. `OO` here is a lower level of mine shaft, leading to the tunnels. There are many dead ends in the tunnels, but only one of these dead-ends provides a way to go up or down. Player has to manually search for it, as overmap doesn't provide any help on this matter.
изображение

Example of -4 level of mine tunnels. `M` here is a mine finale
изображение

Example of T-shaped tunnel with lava current, puddles of water, piles of metal wreckage, some mining-related loot, and a pair of zombie miners
изображение

Example of straight tunnel leading to the dead-end with sinkholes and toxic gas vent
изображение

Example of mine finale
изображение

### CODE REVIEW

**Comment by NetSysFire** [comment]
Having tighter tunnels means the player will have to actually find a way to deal with the obstacles, mainly lava and toxic gas. I like that. With the hardcoded variant you could just circumvent that due to there being enough space.

**Comment by Xaritscin** [comment]
Id say a generic mine should just have equipment and stuff at the finale. not all mines should have an Amigara/Spiral/The Thing event at the end. maybe its just a regular mine that just happened to get fucked up due to the cataclysm.

However, i wouldnt bar some extra options to diversify the place a little (kind of copied from the cave mapgen):

-Archaeology Ruins with a few zombie archaelogists and stuff at the end and some tools apart of bones/artifact

-Broken Excavator with several chunks of ore/mineral and a few zombie miners guarding the machine

-A microlab chamber that when opened connects to the subway lab tunnels grid, maybe have some loot rooms before leading to the railway.

-Giant Naked Molerat colony with the artifact inside what would be the "queen's chamber"

**Review by John-Candlebury — CHANGES_REQUESTED** [review]
Why are you removing artifacts from the netherum distorted microlab and from the lab containment chambers as a part of these changes? Is there some specific justification for that, mostly since they fit the role-lore of microlabs?

Also if they are going to get gone, at least consider replacing them with something, the rooms they are set to spawn now will be completely empty otherwise

**Comment by John-Candlebury** [comment]
Oh also and unrelated to the change request above? I recently made quite a lot of mapgen pieces for a somewhat similar aftershock dungeon #54385. 
It should be possible to make the bare mapgen pieces (found in tunnel_tiles.json) part of vanilla with little trouble, they are a bit more dynamic than what you have here now (but also bigger) just letting you know if you have interest in using them.

**Comment by Night-Pryanik** [comment]
> Why are you removing artifacts from the netherum distorted microlab and from the lab containment chambers 

I'm not removing them. I just moved artifacts definitions from mapgen files to newly created artifact file - mostly for organization and ease of searching for artifacts in the future.

**Review by John-Candlebury — APPROVED** [review]
Ah failed to notice them there on my first look, I just assumed it was a stray change.

**Comment by Night-Pryanik** [comment]
I don't understand why the tests are failing. According to the logs, game fails right at the `root` phase and can't place even the first overmap terrain of this special. 
But I successfully debug-spawned the location dozens of times without any error. I teleported around the map and "naturally" found dozens of this locations and didn't get any error like this. I successfully started game with a Bottom of a Mine scenario dozens of times without any error.

@jbytheway @John-Candlebury any ideas?

**Comment by jbytheway** [comment]
Which logs are you looking at?  In the CI tests and when I run locally I only see unresolved join errors.  I'll see if I can figure those out, but not today.

**Comment by Night-Pryanik** [comment]
> Which logs are you looking at?

Logs from CI tests and local testing.

> In the CI tests and when I run locally I only see unresolved join errors.

So do I. Error about unresolved joins, starting from the very first phase, despite in-game this location is placed without any errors (at least in my testing).

> I'll see if I can figure those out, but not today.

Much appreciated.

**Comment by jbytheway** [comment]
OK, there were two problems here:
* When you have a large mandatory chunk such as this special uses at the start you need to ensure that the `check_for_locations` finds enough suitable locations to place all elements of that chunk, *and* all outward joins from it.  In this case your `check_for_locations` was only checking a few places on the surface.
* You needed some 4-way connections to use in the cleanup phases, because sometimes the random placement ended up with four connections all pointing at the same tile.

I agree that the errors you get for the first issue are not very clear.  It's hard to know how to make them more clear without making the error output much more verbose.  I'd welcome any feedback on how to improve either the error or the docs to help future people understand this issue.

Here's a patch that I believe fixes both issues.  With this, I was able to run the `overmap_terrain_coverage` test a few times without failures.

```patch
diff --git a/data/json/overmap/overmap_mutable/mine_mutable.json b/data/json/overmap/overmap_mutable/mine_mutable.json
index 7bcb411a62..8d672616ab 100644
--- a/data/json/overmap/overmap_mutable/mine_mutable.json
+++ b/data/json/overmap/overmap_mutable/mine_mutable.json
@@ -7,7 +7,18 @@
     "city_distance": [ 10, 40 ],
     "occurrences": [ 0, 2 ],
     "flags": [ "WILDERNESS" ],
-    "check_for_locations": [ [ [ 0, 0, 0 ], [ "land" ] ], [ [ 1, 0, 0 ], [ "land" ] ], [ [ 0, 1, 0 ], [ "land" ] ], [ [ 1, 1, 0 ], [ "land" ] ] ],
+    "check_for_locations": [
+      [ [ 0, 0, 0 ], [ "land" ] ],
+      [ [ 1, 0, 0 ], [ "land" ] ],
+      [ [ 0, 1, 0 ], [ "land" ] ],
+      [ [ 1, 1, 0 ], [ "land" ] ],
+      [ [ 0, 1, -1 ], [ "subterranean_empty" ] ],
+      [ [ 1, 1, -1 ], [ "subterranean_empty" ] ],
+      [ [ 0, 1, -2 ], [ "subterranean_empty" ] ],
+      [ [ 1, 1, -2 ], [ "subterranean_empty" ] ],
+      [ [ -1, 1, -2 ], [ "subterranean_empty" ] ],
+      [ [ -2, 1, -2 ], [ "subterranean_empty" ] ]
+    ],
     "joins": [
       "parking_lot_to_road",
       "surface_to_shaft",
@@ -31,6 +42,7 @@
       "tunnels_east": { "overmap": "mine_shaft_lower_east_north", "above": "shaft_lower_to_shaft_middle" },
       "tunnel_entrance": { "overmap": "mine_tunnel_ew", "east": "tunnel_entrance_to_tunnels", "west": "tunnel_to_tunnel" },
       "tee": { "overmap": "mine_tunnel_nes", "north": "tunnel_to_tunnel", "east": "tunnel_to_tunnel", "south": "tunnel_to_tunnel" },
+      "cross": { "overmap": "mine_tunnel_nesw", "north": "tunnel_to_tunnel", "east": "tunnel_to_tunnel", "south": "tunnel_to_tunnel", "west": "tunnel_to_tunnel" },
       "straight_tunnel": { "overmap": "mine_tunnel_ns", "north": "tunnel_to_tunnel", "south": "tunnel_to_tunnel" },
       "corner": { "overmap": "mine_tunnel_ne", "north": "tunnel_to_tunnel", "east": "tunnel_to_tunnel" },
       "dead_end": { "overmap": "mine_tunnel_end_south", "north": "tunnel_to_tunnel" },
@@ -41,6 +53,13 @@
         "east": "-3_tunnel_to_-3_tunnel",
         "south": "-3_tunnel_to_-3_tunnel"
       },
+      "-3_cross": {
+        "overmap": "mine_tunnel_nes",
+        "north": "-3_tunnel_to_-3_tunnel",
+        "east": "-3_tunnel_to_-3_tunnel",
+        "south": "-3_tunnel_to_-3_tunnel",
+        "west": "-3_tunnel_to_-3_tunnel"
+      },
       "-3_straight_tunnel": { "overmap": "mine_tunnel_ns", "north": "-3_tunnel_to_-3_tunnel", "south": "-3_tunnel_to_-3_tunnel" },
       "-3_corner": { "overmap": "mine_tunnel_ne", "north": "-3_tunnel_to_-3_tunnel", "east": "-3_tunnel_to_-3_tunnel" },
       "-3_dead_end": { "overmap": "mine_tunnel_end_south", "north": "-3_tunnel_to_-3_tunnel" },
@@ -52,6 +71,13 @@
         "east": "-4_tunnel_to_-4_tunnel",
         "south": "-4_tunnel_to_-4_tunnel"
       },
+      "-4_cross": {
+        "overmap": "mine_tunnel_nes",
+        "north": "-4_tunnel_to_-4_tunnel",
+        "east": "-4_tunnel_to_-4_tunnel",
+        "south": "-4_tunnel_to_-4_tunnel",
+        "west": "-4_tunnel_to_-4_tunnel"
+      },
       "-4_straight_tunnel": { "overmap": "mine_tunnel_ns", "north": "-4_tunnel_to_-4_tunnel", "south": "-4_tunnel_to_-4_tunnel" },
       "-4_corner": { "overmap": "mine_tunnel_ne", "north": "-4_tunnel_to_-4_tunnel", "east": "-4_tunnel_to_-4_tunnel" },
       "-4_dead_end": { "overmap": "mine_tunnel_end_south", "north": "-4_tunnel_to_-4_tunnel" },
@@ -93,7 +119,8 @@
         { "overmap": "dead_end", "weight": 2000 },
         { "overmap": "straight_tunnel", "weight": 100 },
         { "overmap": "corner", "weight": 100 },
-        { "overmap": "tee", "weight": 10 }
+        { "overmap": "tee", "weight": 10 },
+        { "overmap": "cross", "weight": 1 }
       ],
       [
         { "overmap": "-3_straight_tunnel", "max": { "poisson": 20 } },
@@ -111,7 +138,8 @@
         { "overmap": "-3_dead_end", "weight": 2000 },
         { "overmap": "-3_straight_tunnel", "weight": 100 },
         { "overmap": "-3_corner", "weight": 100 },
-        { "overmap": "-3_tee", "weight": 10 }
+        { "overmap": "-3_tee", "weight": 10 },
+        { "overmap": "-3_cross", "weight": 1 }
       ],
       [
         { "overmap": "-4_straight_tunnel", "max": { "poisson": 20 } },
@@ -129,7 +157,8 @@
         { "overmap": "-4_dead_end", "weight": 2000 },
         { "overmap": "-4_straight_tunnel", "weight": 100 },
         { "overmap": "-4_corner", "weight": 100 },
-        { "overmap": "-4_tee", "weight": 10 }
+        { "overmap": "-4_tee", "weight": 10 },
+        { "overmap": "-4_cross", "weight": 1 }
       ]
     ]
   }
```

**Comment by jbytheway** [comment]
> I added only four checks for `land` in `check_for_locations` because I thought that `locations` having `subterranean` already covers subterranean part of that chunk. Looks like I was wrong on this matter?

`locations` having `subterranean` only influences the attempt to place the chunk itself.  However, because the chunk has only one valid location relative to the root, we need to ensure that the root is placed somewhere that the chunk will fit, and `check_for_locations` is how you control where the root is placed.

**Comment by jbytheway** [comment]
Looks like the CI here uncovered another bug, which I've PRed a fix for at #56625.

**Comment by I-am-Erk** [comment]
Still failing something in basic build... I'd be happy to merge if that can be fixed

**Comment by Night-Pryanik** [comment]
The error is

>Overmap special id Mine Entrance has been removed or migrated to a different type.

I'm not sure what to do with it.

**Comment by dseguin** [comment]
> I'm not sure what to do with it.

You'll need to remove references to `Mine Entrance` in mods as well:

https://github.com/CleverRaven/Cataclysm-DDA/blob/e0413aebc548d5c8b22c96702b12d01f45302554/data/mods/Dark-Skies-Above/blacklists/location_blacklist.json#L85

https://github.com/CleverRaven/Cataclysm-DDA/blob/e0413aebc548d5c8b22c96702b12d01f45302554/data/mods/aftershock_exoplanet/setting_blacklists/location_blacklist.json#L85

**Pull request merged**
