### PR TITLE
Obsolete Para-Amputee

### PR DESCRIPTION
**Pull request by LordBarkBread**
Obsolete Para-Amputee scenario.

#### Summary
None

#### Purpose of change
I saw the PR that merged this morning, while I think showing support and representation is a wonderful thing, as it stands right now we do not have proper mechanics, ways to go about, or features to properly and correctly showcase something like this without it being a bit ablest and crude.

#### Describe the solution
Obsolete the changes.

#### Describe alternatives you've considered
We would need better alternatives simple as it is, more features, ways to handle, accessibilities, and possibly a chance for bionic limbs or mutations to help out the player if they so choose. This requires someone to add in a lot more things before we instantly jump to the end like the PR done. At the very least we need a better foundation first all in all.

### CODE REVIEW

**Comment by GuardianDll** [comment]
\> we have no way to correctly showcase such issues right now

Can you bring some examples?

**Comment by lispcoc** [comment]
I think Github is not a place for editing battles. If you have such a hobby, please do it on Wikipedia.

**Comment by MNG-cataclysm** [comment]
> features to properly and correctly showcase something like this without it being a bit ablest and crude.

How exactly is this showcase ableist and crude? The profession doesn't demean, lessen, or cheapen anyone in any way, nor does it portray the condition or person as something to be feared or shunned.

**Comment by LordBarkBread** [comment]
> > we have no way to correctly showcase such issues right now
> 
> Can you bring some examples?



> > we have no way to correctly showcase such issues right now
> 
> Can you bring some examples?

 My direct quote as read. 
 >we do not have proper mechanics, ways to go about, or features to properly and correctly showcase something like this without it being a bit ablest and crude.
 
 Currently as it stands there is no accessibility. Once you leave the wheelchair it's over. We don't have mechanics where a person could still their hands and arms to move about out of their wheelchair.
 Past the fact it seems like a rushed feature with very little thought to it other than "I want to have this."
I'm not against the idea, but I believe we need more things before we jump the gun.

**Comment by LordBarkBread** [comment]
> > features to properly and correctly showcase something like this without it being a bit ablest and crude.
> 
> How exactly is this showcase ableist and crude? The profession doesn't demean, lessen, or cheapen anyone in any way, nor does it portray the condition or person as something to be feared or shunned.

Because there arent enough features to just add in this rushed piece. There needs to be more accessibility, without it, it comes off and quite crude.

**Comment by MNG-cataclysm** [comment]
> Because there arent enough features to just add in this rushed piece. There needs to be more accessibility, without it, it comes off and quite crude.

I took the time to figure out how to add this in a proper way, I didn't just throw it together and call it done. I did say in my previous PR that I was going to add the proper infrastructure if it was merged, and I'm starting on that here soon.

**Comment by MNG-cataclysm** [comment]
The easiest thing to do here is to start working on the proper infrastructure to interface with this, rather than scrapping it all entirely and putting it on hold. I can contribute to this to the best of my ability, and it's more constructive than throwing it all out.

**Comment by lispcoc** [comment]
If you're going to make a prosthetic arm or leg, I think it's natural to first create the conditions that make it necessary. I don't think there's anything wrong with reversing the order, but considering the development process, it's just a waste of time.

**Comment by CHCOOH** [comment]
This has nothing to do with this PR, but if you are going to implement a prosthetic leg or hand, it would be cool to have a gun or blade built in.

**Comment by Zireael07** [comment]
As someone who uses a wheelchair occasionally, I was looking forward to playing around with the new profession. 

Please do not remove it!

**Comment by UmbralReaver** [comment]
I'm an amputee (albeit not legs) and wheelchair user and I don't think this profession should exist in game until as said, proper support is included.

Otherwise it just ends up being an SS13-style ableism meme regardless of intention.

**Comment by lispcoc** [comment]
As has already been mentioned several times, the author of #68298 has previously indicated the prospect of adding replacement item for your legs and feet.
This PR criticism is completely off base to me and seems like it's purpose is just to attack the author.

**Comment by lispcoc** [comment]
> I'm an amputee (albeit not legs) and wheelchair user and I don't think this profession should exist in game until as said, proper support is included.

I think your claim is completely wrong. It would certainly be an issue if the game was in that state when it was officially released, but what you're playing is just a build in development. I don't think this is much different from looking at a bronze statue in progress and criticizing the deficient.

**Comment by MNG-cataclysm** [comment]
> I'm an amputee (albeit not legs) and wheelchair user and I don't think this profession should exist in game until as said, proper support is included.
> 
> 
> 
> Otherwise it just ends up being an SS13-style ableism meme regardless of intention.

How does it become an "ableism meme"?

**Comment by EvanBalster** [comment]
When I spotted the original PR last week I quickly jumped in with [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/68298#issuecomment-1732666616) referring to an article, video and organization (AbleGamers) oriented toward reforming disability representation in the game industry.  I emphasized that difficulty probably shouldn't be the primary driver for a feature like this.  I get the sense that the unsubtle profession name **Para-Amputee** is a factor in the current discussion — it certainly caught my eye and it suggests a similarly unsubtle approach to the subject matter.  Indeed, the PR was put together and merged in just a few days which would support that interpretation.  I think there's a strong argument that an addition like this should be approached more slowly/deliberately than a typical contribution, in conversation with community members living with disabilities.

However, I also think it's unreasonable to suggest a feature like this must be much larger in scope before it can be added to the game.  During my brief time contributing here I've come to understand that CDDA's development mostly happens in tiny bits and pieces rather than large, one-and-done contributions.  If adding disability representation to the game requires a huge contribution, it just won't get done unless an extremely motivated volunteer appears to do the legwork.  Should such volunteers exist, they could just as easily contribute smaller and more incremental changes in the context of an ongoing and thoughtful discussion about how to achieve representation in this game.

**Comment by MNG-cataclysm** [comment]
I saw the video you linked my PR on representation ([You Can Take an Arrow to the Knee and Still be an Adventurer](https://m.youtube.com/watch?v=Vb39BFs1UK0)), and it was very eye-opening. From what I learned, I tried to make the PR in such a way that it would be respectful and constructive, and I thank you for showing me how.

**Comment by alp7292** [comment]
rome wasnt built in a day and we need to start from somewhere instead of removing it why not work on improving it

**Comment by LordBarkBread** [comment]
> When I spotted the original PR last week I quickly jumped in with [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/68298#issuecomment-1732666616) referring to an article, video and organization (AbleGamers) oriented toward reforming disability representation in the game industry. I emphasized that difficulty probably shouldn't be the primary driver for a feature like this. I get the sense that the unsubtle profession name **Para-Amputee** is a factor in the current discussion — it certainly caught my eye and it suggests a similarly unsubtle approach to the subject matter. Indeed, the PR was put together and merged in just a few days which would support that interpretation. I think there's a strong argument that an addition like this should be approached more slowly/deliberately than a typical contribution, in conversation with community members living with disabilities.


I do think it was hasty, and I think something of this caliber should be looked at and approached slowly. I had talked with Maleclypse, the one who merged it, and voiced some concerns, worries, and uncertainties and they suggested that I make this PR to have a double look at and discussed a little to figure out a little more. But it seems instead folks have looked at my words and concerns in the PR and decided it was hostile and baseless so it's kind of upsetting and nerve-racking and I think instead I'll just close it and see if MNG or others do actually plan to work further on this.

**Comment by Maleclypse** [comment]
I would like to come here and say that I know that Bark wasn’t trying to call anyone out but rather expressing worries and I suggested that if there were worries they could be worked through here and if they weren’t able to addressed we could revert to work on things. I am going to try and find time to reach out to the AbleGamers group to receive suggestions on what we’ve missed or anything we need to change. The biggest problem on the internet is that there is no tone so there is a 50% chance for tone to be misunderstood. Everyone in this thread wants to make this project better and healthier. I hope that we can all recognize that and give each other space and grace as needed.

**Comment by lispcoc** [comment]
I understand your feelings, but the proliferation of RPs aimed at canceling content like this will greatly confuse development. I think we should have spent several days discussing it on issues and Discord beforehand.

**Comment by MNG-cataclysm** [comment]
I see what you mean, but in the future, I would prefer we talk about things like this before making PR's to cancel content. @LordBarkBread if you have any future concerns over content I'm involved in, please contact me on Discord and we'll discuss the matter.

**Comment by EvanBalster** [comment]
I would like to suggest making extra time to seek community input into contributions like Para-Amputee before merge.  It seems to me that @LordBarkBread raised valid concerns about changes like this being cooked up so quickly there wasn't much opportunity for input from disabled players.

I would suggest that PRs like MNG's para-amputee ought to be reviewed and discussed a bit more slowly and deliberately than typical additions to the game.

**Pull request closed without merging**
