### PR TITLE
NPC @ menu: Show morale, medical; Change name, gender, armor sprite

### LINKED ISSUE #72138: NPC Prisoners and beggars should lose their title upon recruiting
### Is your feature request related to a problem? Please describe.

When you recruit the refugee center beggars, or rescue prisoners from a mi-go camp, your new followers are still named "(npcname), beggar" or "(npcname), prisoner" despite the fact that they are no longer that. Currently the only way of ridding them of those titles is to use the debug menu.

### Solution you would like.

NPCs should lose such monikers upon recruitment.

Failing that, you should be able to customize the NPC's name the same way you can do so in your character sheet.

### Describe alternatives you have considered.

Is the fact that they were once a beggar or once a prisoner something to be preserved about their identity? It's hardly relevant after they join your ranks.

### Additional context

_No response_

### LINKED ISSUE #74314: Show NPC morale (some keys in @ menu don't work for NPCs)
### Describe the bug

I don't know how to see NPCs morale. It affects crafting so it is important.

Pressing `m` in this NPC stat window doesn't show their morale:
image

### Attach save file

N/A

### Steps to reproduce

1. Have NPC in fraction.
2. Talk to them.
3. `c` -> `I would like to know more about your abilities.`
4. Observe: @ menu is opened, not for the player character but for the NPC character.
   - image
5. The menu does work as you would expect with the exception of the following. They do nothing observable:
   - image
   - `y` -> `Customize base appearance and name`
   - `m` -> `View character's morale`
   - `@` -> `Open medical menu`
   - `W` -> `Change sprite for armor.` (Additionally, there shouldn't be the `.` at the end.)

6. Look in the player character menu (for your character) and check that all of these do work

### Expected behavior

Ideally, implement them for NPC.

Otherwise, hide the keybindings or make a popup("Not implemented for NPCs").

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-10024-g124adb8057-dirty [64-bit] - master was 02d16e39de
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
Features "NPC @ menu: Show morale, medical; Change name, gender, armor sprite"

#### Purpose of change

Resolve #74314 - my issue, all the info is there
Resolve #72138

#### Describe the solution

 - Move disp_morale, medical, from `avatar` to `Character`.
   - Medical menu `apply` uses some avatar use_action. Changed the behaviour so that: If called on avatar, use as before, if NPC, popup `Apply not implemented for NPCs.`
 - Allow calling all the things mentioned in summary from NPC @ menu.
 - Conversation topic "I'd like to know a bit more about your abilities." now does allow customization of name and gender.
 - Show the `display_name` in widgets in the side panel: https://github.com/CleverRaven/Cataclysm-DDA/pull/74406#issuecomment-2156253373

#### Describe alternatives you've considered

Train of thought:
1. "I'd like to know a bit more about your abilities." calls `reveal_stats`.
2. `reveal_stats` is called from allied NPCs, and unique NPCs under topics: `TALK_FRIEND_Liam_Abilities` and `TALK_FRIEND_Luo_Abilities`.
3. So we could split the calls to not be able to change these two unique NPCs but still change allied NPCs.

But I decided to keep it as is, I never met those guys and I assume it is not super important to forbid customizing these characters specifically. Should we forbid to do other actions (show morale, medical)?

Also, do IWYU. I would need to compile tests, so I didn't do it.

#### Testing

Compile, launch game try all the shortcuts. Try the popup in NPC @ menu > medical > apply.

Didn't test: medical: check that `.pos()` still works. - if it were called by an NPC. I believe it does still work.

#### Additional context

Ref:
 - #66931
 - #51142

### CODE REVIEW

**Comment by XygenSS** [comment]
If this allows customizing follower names without debug #72138 perhaps could be considered resolved

**Comment by Brambor** [comment]
The name shows in lots of menus: 
image

But it doesn't show in this side panel: 
image

**Comment by Brambor** [comment]
Fixing Clang-tidy 17 / build (other) (pull_request)

**Comment by Brambor** [comment]
Random fail, restarting https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/9435673460/job/25989420549?pr=74406#step:17:179

**Comment by Maleclypse** [comment]
Rebase for conflicts please

**Comment by Brambor** [comment]
Maybe this fixed the tests, so I am restarting them
 - #74476

**Comment by I-am-Erk** [comment]
This is going to cause a lot of mess in dialogue for static NPC followers like Luo and Liam

**Comment by Brambor** [comment]
Well, the alternative is making `reveal_stats_constant` on top of `reveal_stats`. The constant version wouldn't allow any changes. But then, in the constant version, inaccessible keybindings should be removed.

**Comment by Brambor** [comment]
> This is going to cause a lot of mess in dialogue for static NPC followers like Luo and Liam

Could you please make an issue or tell me how to test it? I am not familiar with those NPCs so if I were to fix that, I would have to spend a lot of time figuring out what was wrong in the first place.

**Comment by I-am-Erk** [comment]
I haven't got a lot of free time for GitHub for a while but I'll see what I can do or ask someone to help me out with it

**Pull request merged**
