### PR TITLE
Increases nutrition of pemmican.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
It seems that pemmican lost something in the last big food rebalance.

Traditional pemmican averages between 100 and 200 calories per ounce,
and each serving is approximately four ounces.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Nutrition isn't even that strongly correlated with calories, otherwise cooking oil and lard would have a lot of it.

And pemmican is 8*37 = 296, which is more than the sum of its parts unless we're taking only the least efficient ones.
Say, 4 dry meats (which could be turned into 200 nutrition worth of cooked meat instead of drying), 2 lards (2*18=36) and 2 dry veggies (which could be 80 nutrition worth of cooked veggies). And pemmican is permafood, unlike other efficient foods (such as cooked meat, not dry meat).

Finally, when did the rebalance nerf pemmican? As far as I recall, it was either 6*50 or 4*50 before, now it's 8*37.

**Comment by kevingranade** [comment]
Nutrition should correlate well with calories, at a 1-1 ratio in fact (no
idea what the multiplier should be though).
If something has a lot of calories but "you can't survive on this", it
should have a health penalty to reflect that rather than reduced nutrition.

**Comment by Zireael07** [comment]
@kevingranade: While I like the idea, I think it's more suitable for another PR which would update all the nutrition.

Do you guys know any good resources on the calories? Nutrition is all in JSON, so I could do it provided I had a resource...

**Comment by Zireael07** [comment]
Also, @kevingranade's comment reminds me of #13649.

**Comment by kevingranade** [comment]
Sorry if that was unclear, that was a comment about the system as a whole
rather than a request to change this specific PR.

**Comment by Rivet-the-Zombie** [comment]
My mistake; it was originally 74 * 4 for a 'unit' of pemmican. I seem to recall it being higher than that, but I was wrong.

**Pull request closed without merging**
