### PR TITLE
Rework gasoline tank explosions

### PR DESCRIPTION
**Pull request by i2amroy**
Stops the problem where the explosions from external tanks are screen-filling. Also fixes up some strange logic, such as the one_in(X) chance that never actually did anything because it was called on a bool instead of an int.

The new formula is approximately the same at most values short of the top end, the bottom end is slightly less explosive, the middle is slightly more, and the upper range is much less explosive. In addition the fact that the one_in(x) now works means that the majority of car crashes will _not_ cause giant explosions, similar to real life and unlike how it used to be.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Diesel doesn't actually explode until vaporized, so having diesel explosions larger than gasoline ones is actually anti-realistic.

Having diesel not explode at all would probably be the most proper way to handle it.

**Comment by Rivet-the-Zombie** [comment]
>Having diesel not explode at all would probably be the most proper way to handle it.

This right here.

**Comment by i2amroy** [comment]
Okay, I don't have exactly the same experience with diesel as I do with hydrogen and wasn't quite sure about that. Would you say that diesel *never* explodes, or just that it was extremely unlikely to do so? This also includes heat-type damage, so if necessary I could make it very unlikely to explode normally, or limit it to only exploding from heat damage, or something else. I'm totally open to suggestions here.

**Comment by Coolthulhu** [comment]
Realistic diesel explosions would be small, more like big "puffs" than "blasts" that happen with gasoline tanks. They wouldn't use the entire fuel at once, only a percentage of it (or maybe a minimum of % of fuel and % of total fuel capacity) and not 50%, but closer to single digits. And of course wouldn't happen from physical damage.

The closest approximation would probably be something like this: low explosion chance from heat damage (to simulate fuel having to heat up before exploding), non-fiery explosion (it's a gas that explodes, not liquid), using up a percentage of fuel and only getting explosion power from that percentage. No explosion chance from physical damage.

But I'm not sure if it's worth trying to balance. Just having a significantly smaller (20%?) exponent and explosion chance would help. Making diesel totally non-explosive would also be easy and would make fuel choice tactical: gasoline with V12 and easy availability or diesel with safety.

**Comment by i2amroy** [comment]
Dropped diesel explosion chances down to 5% for heat damage and .1% for normal damage (from 10%). Dropped explosion factor from 110% that of gasoline down to 20%. Diesel explosions no longer leave fire behind.

Looking at the two of them now, diesel is almost certainly a much safer choice, basically none of your diesel cars are going to explode from damage, and those that do will have rather small explosions (though the entirety of the fuel is still used up in the explosion right now, I could possibly change that to scattering around more of the fuel if desired, though that would be a bit more in-depth than just a simple numbers change).

**Comment by narc0tiq** [comment]
This, uh, sounds like a really good reason to drive a diesel Narcmobile.

**Comment by pouar** [comment]
>Diesel doesn't actually explode until vaporized.

Same for gasoline.

**Comment by i2amroy** [comment]
>Diesel doesn't actually explode until vaporized.
>Same for gasoline.

The difference is that where diesel doesn't vaporize until 125 F, gasoline vaporizes at *-40* F. Yes, gasoline explosions in car crashes are rather rare (which I've accounted for, and it's set up in a way it will be very easy to tweak it in the future), but they are nowhere near as rare as diesel explosions. You can literally take a match and put it out by sticking it into a bucket of diesel (note: if you just poured it it is still possible to get a very nice *whump* due to the air/diesel mixture you've created while pouring, but if it's been sitting for a while there isn't any real danger of that). Try that with a bucket of gasoline and you are basically guaranteed to lose your eyebrows. :P

**Comment by pouar** [comment]
https://www.youtube.com/watch?v=vln5-HZpgcA

**Comment by pouar** [comment]
I've seen people put cigarettes out with gasoline. As for matches, I've only seen that happen when it was snowing

**Comment by Coolthulhu** [comment]
Any news on this one? Jenkins says it's not buildable

**Comment by i2amroy** [comment]
Oh lol, forgot to declare one of the variables. I'll put a quick fix up in like 5 min when my computer is done restarting to the Windows side.

**Pull request merged**
