### PR TITLE
npc-board-player-vehicle fix

### LINKED ISSUE #66968: npc_test frequent test fail
### Is your feature request related to a problem? Please describe.

npc_test is failing the test case npc-board-player-vehicle very frequently with ```(~[slow] ~[.],starting_items)=> ../tests/npc_test.cpp:386: FAILED:
(~[slow] ~[.],starting_items)=>   REQUIRE( companion->pos() == player_pos + point( 2, 0 ) )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   (61,62,0) == (62,60,0)``` 

### Solution you would like.

Tests not to fail all the time
~~As far as I can tell this is happening bc the NPC decides to get in the back reclining seat of the ambulance rather than the passenger seat because it's a shorter distance. I have no idea whether the test intentionally only wants them to go for the passenger seat or not.~~
No idea what the problem is see the PR below for a failed fix

### Describe alternatives you have considered.
~~Just allowing the other seat in the test.~~
Removing the test until someone finds a proper solution

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change

Fixes #66968

#### Describe the solution

Swaps the ambulance out for test_van as that has the same size and shape but only 2 seats while still testing the NPC doesn't get stuck in the back

#### Testing

Ran the test locally a bunch of times with no fails

### CODE REVIEW

**Comment by GuardianDll** [comment]
Fyi you don't need to make an issue if you are ready to make a fix

**Comment by Procyonae** [comment]
> Fyi you don't need to make an issue if you are ready to make a fix

Ik :p I weren't sure what the right way to fix it was but Snup cleared it up on the devcord

**Comment by Procyonae** [comment]
Welp it failed despite only passing locally ;-;

**Comment by Maleclypse** [comment]
I’ve kicked the tests since it looked like it passed the test that’s been failing.

**Comment by Procyonae** [comment]
I mean it looks like the same test to me, afai can tell that's their starting position so they're now more broken

**Comment by Maleclypse** [comment]
What’s weird to me is it’s no longer failing on the mac build that all the others fail on.

**Comment by Procyonae** [comment]
Reopening just to see what the debug message for the "new" fail say

**Comment by NetSysFire** [comment]
I added it to the abandoned but desired PRs project, maybe someone will pick it back up. Theres usually larger things in there, but I dont see why this wouldnt fit.

**Comment by Procyonae** [comment]
> I added it to the abandoned but desired PRs project, maybe someone will pick it back up. Theres usually larger things in there, but I dont see why this wouldnt fit.

I mean this needs solving asap and that's a long term thing imo but ok

**Comment by mqrause** [comment]
Didn't this only fail because of the uncommented code?

**Comment by Procyonae** [comment]
> Didn't this only fail because of the uncommented code?

Nah it failed twice before that, see the fail on [4f2721d](https://github.com/CleverRaven/Cataclysm-DDA/pull/66969/commits/4f2721d89b2a71de9a1a49299945fe17618a8ce9)

**Pull request closed without merging**
