### PR TITLE
medical zombies

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "Medical zombie loot and medical zombie variants"

#### Purpose of change

Realism, monster diversity

#### Describe the solution

Creates new monsterdrop groups "zombie_medical" and "zombie_medical_clothes" and gives it to some new copy-from medical zombies and spawns those, especially on medical lists. New medical upgrade group passing to zombies with medical or no drops.

#### Describe alternatives you've considered

Bizarre new medical zombie powers and evolutions. Hopefully a future PR.

#### Testing

Game loads no errors, monsters spawn and look right

Screen Shot 2021-06-10 at 10 39 57 PM

Monsters drop appropriate loot

Screen Shot 2021-06-10 at 10 50 50 PM

#### Additional context

Inspired by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/493

### CODE REVIEW

**Comment by actual-nh** [comment]
> Bizarre new medical zombie powers

I wouldn't mind seeing some possibilities...

**Comment by LyleSY** [comment]
I've been eyeing yonder medical mutation tree. I see a lot of stuff about lots of hit points, so basically a tough medical variant. Also a bunch of acid stuff so I added the acid variant. I was also thinking about healing itself and others if that isn't too fantasy.

**Comment by Ali-Anomma** [comment]
> 
> 
> > Bizarre new medical zombie powers
> 
> I wouldn't mind seeing some possibilities...

maybe like necromancer,it can help other zombies by healing they with its special attack

**Comment by actual-nh** [comment]
> I've been eyeing yonder medical mutation tree. I see a lot of stuff about lots of hit points, so basically a tough medical variant.

Tough or brute? Possibly lower armor but higher HP than the standard brute?

**Comment by krulunio** [comment]
I have 2 ideas:
zombie doctor - deals low damage, but can stab you with scalpel, giving you arterial/normal bleeding and bad infection
- zombie bio-doctor: like normal doctor, but faster, gives medical bionic when butchered and can inject you with paralysing poison or , rarely, with mutagen (medical/alpha/purifier?). Basically, medical version of bio-operator

**Pull request merged**
