### PR TITLE
Add Quick and Quick-NoTiles configurations to MSVC solution

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary
None

#### Purpose of change

Add `Quick` and `Quick-NoTiles` build configurations to MSVC solution that skip building tests suite and json formatter

### CODE REVIEW

**Comment by Brambor** [comment]
Ugh, now git wants to do this, when I turn off tests in compilation.

I guess I am back to `git update-index --skip-worktree msvc-full-features/Cataclysm-vcpkg-static.sln`

```git
diff --git a/msvc-full-features/Cataclysm-vcpkg-static.sln b/msvc-full-features/Cataclysm-vcpkg-static.sln
index 916c9c2af4..a26529942f 100644
--- a/msvc-full-features/Cataclysm-vcpkg-static.sln
+++ b/msvc-full-features/Cataclysm-vcpkg-static.sln
@@ -1,7 +1,7 @@
 ﻿
 Microsoft Visual Studio Solution File, Format Version 12.00
-# Visual Studio Version 17
-VisualStudioVersion = 17.1.32104.313
+# Visual Studio Version 16
+VisualStudioVersion = 16.0.34729.46
 MinimumVisualStudioVersion = 10.0.40219.1
 Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{04F55049-F0DE-4AE6-9D10-3DB97DFF2E2F}"
 	ProjectSection(SolutionItems) = preProject
@@ -36,18 +36,18 @@ Global
 		Debug-NoTiles|ARM64EC = Debug-NoTiles|ARM64EC
 		Debug-NoTiles|x64 = Debug-NoTiles|x64
 		Debug-NoTiles|x86 = Debug-NoTiles|x86
-		Release|ARM64EC = Release|ARM64EC
-		Release|x64 = Release|x64
-		Release|x86 = Release|x86
-		Release-NoTiles|ARM64EC = Release-NoTiles|ARM64EC
-		Release-NoTiles|x64 = Release-NoTiles|x64
-		Release-NoTiles|x86 = Release-NoTiles|x86
 		Quick|ARM64EC = Quick|ARM64EC
 		Quick|x64 = Quick|x64
 		Quick|x86 = Quick|x86
 		Quick-NoTiles|ARM64EC = Quick-NoTiles|ARM64EC
 		Quick-NoTiles|x64 = Quick-NoTiles|x64
 		Quick-NoTiles|x86 = Quick-NoTiles|x86
+		Release|ARM64EC = Release|ARM64EC
+		Release|x64 = Release|x64
+		Release|x86 = Release|x86
+		Release-NoTiles|ARM64EC = Release-NoTiles|ARM64EC
+		Release-NoTiles|x64 = Release-NoTiles|x64
+		Release-NoTiles|x86 = Release-NoTiles|x86
 	EndGlobalSection
 	GlobalSection(ProjectConfigurationPlatforms) = postSolution
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Debug|ARM64EC.ActiveCfg = Debug|ARM64EC
@@ -62,18 +62,6 @@ Global
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Debug-NoTiles|x64.Build.0 = Debug-NoTiles|x64
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Debug-NoTiles|x86.ActiveCfg = Debug-NoTiles|Win32
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Debug-NoTiles|x86.Build.0 = Debug-NoTiles|Win32
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|ARM64EC.Build.0 = Release|ARM64EC
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x64.ActiveCfg = Release|x64
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x64.Build.0 = Release|x64
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x86.ActiveCfg = Release|Win32
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x86.Build.0 = Release|Win32
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
-		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick|ARM64EC.Build.0 = Release|ARM64EC
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick|x64.ActiveCfg = Release|x64
@@ -86,6 +74,18 @@ Global
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick-NoTiles|x64.Build.0 = Release-NoTiles|x64
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Quick-NoTiles|x86.Build.0 = Release-NoTiles|Win32
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|ARM64EC.Build.0 = Release|ARM64EC
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x64.ActiveCfg = Release|x64
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x64.Build.0 = Release|x64
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x86.ActiveCfg = Release|Win32
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release|x86.Build.0 = Release|Win32
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
+		{19F0BE17-3DAF-40E8-A9D2-904A56382E54}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug|ARM64EC.ActiveCfg = Debug|ARM64EC
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug|ARM64EC.Build.0 = Debug|ARM64EC
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug|x64.ActiveCfg = Debug|x64
@@ -98,10 +98,15 @@ Global
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug-NoTiles|x64.Build.0 = Debug-NoTiles|x64
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug-NoTiles|x86.ActiveCfg = Debug-NoTiles|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug-NoTiles|x86.Build.0 = Debug-NoTiles|Win32
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|x64.ActiveCfg = Release|x64
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|x86.ActiveCfg = Release|Win32
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
+		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|ARM64EC.Build.0 = Release|ARM64EC
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x64.ActiveCfg = Release|x64
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x64.Build.0 = Release|x64
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x86.ActiveCfg = Release|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x86.Build.0 = Release|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
@@ -110,12 +115,6 @@ Global
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|x64.ActiveCfg = Release|x64
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick|x86.ActiveCfg = Release|Win32
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Quick-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug|ARM64EC.ActiveCfg = Debug|ARM64EC
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug|ARM64EC.Build.0 = Debug|ARM64EC
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug|x64.ActiveCfg = Debug|x64
@@ -128,18 +127,6 @@ Global
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug-NoTiles|x64.Build.0 = Debug-NoTiles|x64
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug-NoTiles|x86.ActiveCfg = Debug-NoTiles|Win32
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Debug-NoTiles|x86.Build.0 = Debug-NoTiles|Win32
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|ARM64EC.Build.0 = Release|ARM64EC
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x64.ActiveCfg = Release|x64
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x64.Build.0 = Release|x64
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x86.ActiveCfg = Release|Win32
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x86.Build.0 = Release|Win32
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
-		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick|ARM64EC.Build.0 = Release|ARM64EC
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick|x64.ActiveCfg = Release|x64
@@ -152,6 +139,18 @@ Global
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick-NoTiles|x64.Build.0 = Release-NoTiles|x64
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Quick-NoTiles|x86.Build.0 = Release-NoTiles|Win32
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|ARM64EC.Build.0 = Release|ARM64EC
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x64.ActiveCfg = Release|x64
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x64.Build.0 = Release|x64
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x86.ActiveCfg = Release|Win32
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release|x86.Build.0 = Release|Win32
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
+		{0009BB11-11AD-4C14-A5FC-D882A942C00B}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug|ARM64EC.ActiveCfg = Debug|x64
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug|x64.ActiveCfg = Debug|x64
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug|x64.Build.0 = Debug|x64
@@ -162,6 +161,12 @@ Global
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug-NoTiles|x64.Build.0 = Debug|x64
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug-NoTiles|x86.ActiveCfg = Debug|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug-NoTiles|x86.Build.0 = Debug|Win32
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|x64.ActiveCfg = Release|x64
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|x86.ActiveCfg = Release|Win32
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|x64.ActiveCfg = Release|x64
+		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|x86.ActiveCfg = Release|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|x64.ActiveCfg = Release|x64
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|x64.Build.0 = Release|x64
@@ -172,12 +177,6 @@ Global
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release-NoTiles|x64.Build.0 = Release|x64
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release-NoTiles|x86.ActiveCfg = Release|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release-NoTiles|x86.Build.0 = Release|Win32
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|x64.ActiveCfg = Release|x64
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick|x86.ActiveCfg = Release|Win32
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|x64.ActiveCfg = Release|x64
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Quick-NoTiles|x86.ActiveCfg = Release|Win32
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug|ARM64EC.ActiveCfg = Debug|x64
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug|x64.ActiveCfg = Debug|x64
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug|x64.Build.0 = Debug|x64
@@ -188,6 +187,12 @@ Global
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug-NoTiles|x64.Build.0 = Debug|x64
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug-NoTiles|x86.ActiveCfg = Debug|Win32
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Debug-NoTiles|x86.Build.0 = Debug|Win32
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|x64.ActiveCfg = Release|x64
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|x86.ActiveCfg = Release|Win32
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|x64.ActiveCfg = Release|x64
+		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|x86.ActiveCfg = Release|Win32
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release|x64.ActiveCfg = Release|x64
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release|x64.Build.0 = Release|x64
@@ -198,12 +203,6 @@ Global
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release-NoTiles|x64.Build.0 = Release|x64
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release-NoTiles|x86.ActiveCfg = Release|Win32
 		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Release-NoTiles|x86.Build.0 = Release|Win32
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|x64.ActiveCfg = Release|x64
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick|x86.ActiveCfg = Release|Win32
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|x64.ActiveCfg = Release|x64
-		{534A4E38-96A1-40E4-BDA7-8D17607F0270}.Quick-NoTiles|x86.ActiveCfg = Release|Win32
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug|ARM64EC.ActiveCfg = Debug|ARM64EC
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug|ARM64EC.Build.0 = Debug|ARM64EC
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug|x64.ActiveCfg = Debug|x64
@@ -216,18 +215,6 @@ Global
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug-NoTiles|x64.Build.0 = Debug|x64
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug-NoTiles|x86.ActiveCfg = Debug|Win32
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Debug-NoTiles|x86.Build.0 = Debug|Win32
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|ARM64EC.Build.0 = Release|ARM64EC
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x64.ActiveCfg = Release|x64
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x64.Build.0 = Release|x64
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x86.ActiveCfg = Release|Win32
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x86.Build.0 = Release|Win32
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|ARM64EC.Build.0 = Release|ARM64EC
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x64.ActiveCfg = Release|x64
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x64.Build.0 = Release|x64
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x86.ActiveCfg = Release|Win32
-		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x86.Build.0 = Release|Win32
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick|ARM64EC.Build.0 = Release|ARM64EC
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick|x64.ActiveCfg = Release|x64
@@ -240,6 +227,18 @@ Global
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick-NoTiles|x64.Build.0 = Release|x64
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick-NoTiles|x86.ActiveCfg = Release|Win32
 		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Quick-NoTiles|x86.Build.0 = Release|Win32
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|ARM64EC.Build.0 = Release|ARM64EC
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x64.ActiveCfg = Release|x64
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x64.Build.0 = Release|x64
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x86.ActiveCfg = Release|Win32
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release|x86.Build.0 = Release|Win32
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|ARM64EC.ActiveCfg = Release|ARM64EC
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|ARM64EC.Build.0 = Release|ARM64EC
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x64.ActiveCfg = Release|x64
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x64.Build.0 = Release|x64
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x86.ActiveCfg = Release|Win32
+		{8A533A64-435D-4D4F-9FF0-1E97AACE9374}.Release-NoTiles|x86.Build.0 = Release|Win32
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug|ARM64EC.ActiveCfg = Debug|ARM64EC
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug|ARM64EC.Build.0 = Debug|ARM64EC
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug|x64.ActiveCfg = Debug|x64
@@ -252,18 +251,6 @@ Global
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug-NoTiles|x64.Build.0 = Debug-NoTiles|x64
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug-NoTiles|x86.ActiveCfg = Debug-NoTiles|Win32
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Debug-NoTiles|x86.Build.0 = Debug-NoTiles|Win32
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|ARM64EC.Build.0 = Release|ARM64EC
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x64.ActiveCfg = Release|x64
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x64.Build.0 = Release|x64
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x86.ActiveCfg = Release|Win32
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x86.Build.0 = Release|Win32
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
-		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick|ARM64EC.ActiveCfg = Release|ARM64EC
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick|ARM64EC.Build.0 = Release|ARM64EC
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick|x64.ActiveCfg = Release|x64
@@ -276,6 +263,18 @@ Global
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick-NoTiles|x64.Build.0 = Release-NoTiles|x64
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
 		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Quick-NoTiles|x86.Build.0 = Release-NoTiles|Win32
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|ARM64EC.ActiveCfg = Release|ARM64EC
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|ARM64EC.Build.0 = Release|ARM64EC
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x64.ActiveCfg = Release|x64
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x64.Build.0 = Release|x64
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x86.ActiveCfg = Release|Win32
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release|x86.Build.0 = Release|Win32
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|ARM64EC.ActiveCfg = Release-NoTiles|ARM64EC
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|ARM64EC.Build.0 = Release-NoTiles|ARM64EC
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x64.ActiveCfg = Release-NoTiles|x64
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x64.Build.0 = Release-NoTiles|x64
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x86.ActiveCfg = Release-NoTiles|Win32
+		{0C0B2BEA-311F-473C-9652-87923EF639E3}.Release-NoTiles|x86.Build.0 = Release-NoTiles|Win32
 	EndGlobalSection
 	GlobalSection(SolutionProperties) = preSolution
 		HideSolutionNode = FALSE

```

**Comment by ZhilkinSerg** [comment]
That's VS fault. Changing things in this menu is buggy:

image

Anyway the whole point of this PR is to use the dropdown to select `Quick` instead of `Release` when you don't need tests built instead of using that menu:

image

**Comment by Brambor** [comment]
Thank you! Now that I understand this is amazing :)

**Comment by akrieger** [comment]
Huh. I guess I always just manually build the game binary or hit the green build-and-debug button which does the same.

**Pull request merged**
