### PR TITLE
Touhou Professions mod

### PR DESCRIPTION
**Pull request by RedMisao**
#### Summary
Mods "Touhou Professions"

#### Purpose of change
This is a fork of Taberone's old [Touhou Professions](https://github.com/Taberone/Cataclysm-DDA-Touhou-Mod) mod.  It adds several Touhou Project characters as professions, focusing mostly on spells and abilities, but also adding their custom clothing, and some new mechanics (new as in: I haven't seen them in other mods, or that exist but were modified in such a way to fit the characters).

Some background:
<details>
    <summary>What is Touhou Project?</summary>
Touhou Project (Japanese: 東方Project, Hepburn: Tōhō Purojekuto), also known simply as Touhou (東方, literally "Eastern" or "Oriental"), is a bullet hell shoot 'em up video game series created by one-man independent Japanese doujin soft developer Team Shanghai Alice.
</details>

<details>
    <summary>What is the setting?</summary>
Touhou Project is set in Gensokyo, a land sealed from the outside world and primarily inhabited by humans and yōkai, legendary creatures from Japanese folklore that are personified in Touhou as little girls. Reimu Hakurei, the miko of the Hakurei Shrine and the main character of the series, is often tasked with resolving supernatural "incidents" caused in and around Gensokyo.
</details>

<details>
    <summary>Why was Gensokyo sealed?</summary>
Humans developed civilization, which allowed them to "illuminate the darkness of the night".  This caused them to start explaining the world on a non-supernatural way, which caused all supernatural phenomena to lose power and influence.  Some very powerful youkai came to work together to develop the Great Hakurei Barrier, which has the double purpose of protecting the supernatural inside the barrier (and keeping everything inside, inside), and calling forth anything that has a supernatural component.  This includes "anything forgotten by humans", encompassing extinct animals, lost tools, knowledge, and so on.  The plan enabled youkai to survive and thrive on a science-dominated world.
</details>

<details>
    <summary>What are incidents?</summary>
Incidents are very large events that affect everyone on Gensokyo.  These tend to happen because there's a new youkai on the block, someone gets bored enough, or a third party intervenes and threatens the status quo.  These are resolved by the playable characters in the mainline games, and always end with everyone drinking tea together.  Until the next incident, it is.
</details>

Characters are then: humans, youkai or similar entities, with supernatural abilities that fight each other on the regular.  This combination of species + ability is what separates any character in Touhou capable of using fire spells from any common "Fire mage" archetype.

Some character and their abilities in-game are:
* The vampire, a strong youkai, can transform into a bat to fly, summon her Gungnir spear and then throw it without missing, and attack with blood-flavored spells.  Naturally, she burns under the sun, or by water, and has to consume human blood or flesh on the regular or gets weakened.
* The human maid can stop time around her, temporarily move faster or slow her enemies down in combat. She can also increase her movement speed with no time limit as long as there are no enemies nearby.
* The moon rabbit manipulates wavelengths and can choose one of: turn invisible, increase her processing speed, become immune to mental debuffs, or see in the darkness, and switch between the other three or deactivate her ability.
* The immortal girl fights in close combat by use of self-immolation spells and a custom martial art that increases the damage done and received the more she fights.  She's literally unable to die (or here, she can't die repeatedly in a short period of time).
* The celestial (deva) brawls aided by her divine sword and critting-based martial art.  She can manipulate earth, being able to cause earthquakes, and summons several kinds of keystones (boulder, pillar, vehicle), then dismisses them.
* The half-human half-phantom wields two youkai-forged katana.  Her martial art is an inversion of Niten, and can temporarily materialize her phantom-half to aid her in combat.

There's also the crow tengu, the gatekeeper, the heavenly messenger, the moon rabbit recruit, the kasha, the wicked hermit and the hell raven.  Each with distinct spells, abilities and species combinations.

The new, EOC-based mechanics were integrated in distinct characters, consist of the following:
* Auras: some spells emulate aura/stance/mode type abilities, that can be toggled ON or OFF manually by casting the specific spell, and give different effects to the PC as long as they're ON.
* Blood thirst: human materials now have `hblood_vitamin` vitamin, which has no effect unless the PC has the `VAMPIRE` trait.  If that's the case, the character has to keep it above certain thresholds else they get thirst demerits, worsening over time.
* Immortality: the immortal girl can can die as many times as she wants, but there's a soft cap.  Dying triggers `PREVENT_DEATH` and checks a counter vs a random threshold, if it's lower then she immediately resurrects and adds to the counter, which slowly goes down on its own.
* Wings: conceptually similar to Auras, some PCs are winged and can "fly" (read: hover) at will over over ledges and open spaces, consuming stamina until they're tired enough.  This is toggled by activating a mutation.
* Youkai form: similar to Wings, some youkai can now switch between their human and youkai forms, each having different passive effects, such as becoming `SMALL`er and faster, but also reducing their melee damage and reducing carry weight.

#### Describe the solution
The mod adds each of the characters mentioned above, trying to translate as much as possible into CDDA by modding JSON.

#### Testing
Each spell, ability and mechanic was tested by creating a new world and casting or using it.  Everything that appears, or can be used in-game, should be fully functional and produce no errors.  The last version I used to check was experimental 2022-12-24.
Balance is another story though, all numerical values can be considered arbitrary.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Can you add the original author as a co-author of at least one commit so that they get properly credited please. By adding a commit message like the exemple below, the two empty lines are necessary
```
[describe commit]


Co-authored-by: name <username@users.noreply.github.com>
```

**Comment by TheShadowFerret** [comment]
Me thinks this needs to be split up so it can be reviewed
image

**Comment by I-am-Erk** [comment]
I think this is some pretty questionable trademark territory as it stands.

**Comment by KorGgenT** [comment]
i explicitly state it, the concern is a cease-and-desist, and i think it might be acceptable to mainline if trademarked names are changed just enough to not be trademarked anymore.

**Comment by GuardianDll** [comment]
If i recall correctly, touhou project uses custom license, that is pretty similar to public domain - more investigation required, but i don't think we must care about copyright so much in this case

**Comment by kevingranade** [comment]
More lenient does not mean it is compatible with our license.
https://touhou-project.news/guidelines_en/
In fact this conflicts with the game license in many ways.
This would need to be *unrecognizeable* as Touhou to be ok.

**Comment by RedMisao** [comment]
> Can you add the original author as a co-author of at least one commit so that they get properly credited please. By adding a commit message like the exemple below, the two empty lines are necessary
> 
> ```
> [describe commit]
> 
> 
> Co-authored-by: name <username@users.noreply.github.com>
> ```

Sorry... I'm not sure how that's done. I can @ Taberone but the email doesn't show up. I already asked their github's mail in an issue at their [main repo](https://github.com/Taberone/Cataclysm-DDA-Touhou-Mod/issues/42), now I'm waiting for the reply.


> Me thinks this needs to be split up so it can be reviewed image

I could split the mod into a character-by-character basis, which would greatly reduce the number of lines.


> I think this is some pretty questionable trademark territory as it stands, for mainline

Regarding trademark and copyrights, this is what GuardianDll mentioned https://en.touhouwiki.net/wiki/Touhou_Wiki:Copyrights, specifically https://touhou-project.news/guidelines_en/. In short, the mod is "Fan Content" and doesn't infringe any of rules.
I believe the gray area is "Distribution" from a legalistic point of view, as the section is:
a) mostly directed to things like manga, anime, music and games, which are presented on
b) physical form, in
c) events, shops or platforms where official Touhou content can be found, prepared to distribute a)
As this is a mod (in contrast to a full game), it is already outside the first two categories, and because this is a mod for a non-Touhou official or fan game, it will also not fulfill the third

**Comment by kevingranade** [comment]
The Touhou guidelines include demands (non-commercial, non-disparagement) that are not acceptable for inclusion, full stop.

I repeat, if it is recognizeably Touhou, it can not be included.

**Comment by Maleclypse** [comment]
> If i recall correctly, touhou project uses custom license, that is pretty similar to public domain - more investigation required, but i don't think we need to care about copyright so much in this case

8. For the commercial production of derivative material, or the mass circulation of derivative
   material outside of doujin shops, you must seek my permission. 

https://en.touhouwiki.net/wiki/Touhou_Wiki:Copyrights

I don't know what Touhou is but I was interested in your mention of how the copyright was worded and found it mostly agreed with you but that line 8 might be problematic.

**Comment by kevingranade** [comment]
Final answer, I do not agree with your reading of the touhou fan work guidelines, it is not compatible with our license.

**Pull request closed without merging**
