### PR TITLE
[CR]Rebalance of player melee accuracy/crits

### PR DESCRIPTION
**Pull request by Coolthulhu**
Trying to address 4 problems here:
- Torso encumbrance is deadly early on, totally crippling any non-dexterous survivor against small animals
- Crits very quickly become nearly guaranteed, especially with above average dexterity
- Melee accuracy increases very quickly, making all the small dodging stuff harmless to mildly competent survivors
- Dex is too good compared to other stats, especially perception

Torso encumbrance is deadly because it is a flat penalty to a value that's low at start. A fresh survivor with a backpack won't hit anything, while an old one won't even feel it. It actually has a linear effect too, but it doesn't matter much.
Removed the flat penalty, left the linear in. Torso penalty now lowers melee attack rolls by a percentage only.
Before it was `dice( numdice - torso_encumb, 10 - torso_encumb )`, now it's `dice( numdice, 10 - torso_encumb )`.

Rebalanced the crit chance to reward moderate and high values much, much less, while allowing more crits at low values. Most apparent with dexterity and unarmed weapons (including fists). Removed extra bonus to crits for high levels of unarmed combat (this was an overkill anyway, non-crits didn't happen at those levels).
Made crit chances weakly depend on both dexterity and perception, with perception having twice the effect of dexterity.

Halved the effect melee skill and dexterity have on accuracy. Removed extra accuracy bonus for high levels of unarmed combat and halved its effect on accuracy. Buffed accuracy bonus of bashing weapons to skill/3, like other "typed" weapon skills.
This halved dexterity effect required buffing base hit roll. Added 3, for a total of `3 + dex/4`, so that at 8 dexterity it is the same as before (`3+8/4 == 5 == 1 + 8/2`).

Fixed miss messages displaying "torso encumbrance throws you off" even when it can't because it's below 10.

Buffed stumbling miss penalties, so that they matter a bit. They're more flat now, but capped at 60 move points. "DEFT" trait negates them completely rather than just decreasing them now (it is still a bad trait, though).

Changed manhacks to have a stronger attack (they were pathetic), but dodge way less. This should make them less annoying and more dangerous.

I may have missed some important things and balanced some things incorrectly, hence the CR.

### CODE REVIEW

**Comment by i2amroy** [comment]
Sounds like good changes. I'll need to take a look at the actual numbers before I can make any true judgements, but it definitely sounds like you're on the right track here.

**Comment by Rivet-the-Zombie** [comment]
Very nice!

**Comment by tyrael93** [comment]
Great work.

**Comment by John-Candlebury** [comment]
Seeing that it's got the CR tag, what about:

Having the deft perk give you a chance to crit enemies that are stunned. That should make it more valuable.

Anyways, this is great stuff.

**Comment by Skidborg** [comment]
Looking forward to this getting added, especially the fix on early game encumbrance.

**Comment by macrosblackd** [comment]
Been playing around with this and I'm loving it. Melee may need some further balancing but I think that this is much better than before.

**Comment by Rivet-the-Zombie** [comment]
Oh, didn't see that Coolthulhu was already working on a big merge right now!

**Pull request merged**
