### PR TITLE
Adds broken cyborg profession

### PR DESCRIPTION
**Pull request by chaosvolt**
This is a thing I'd been toying with in the past, and decided to PR finally. The basic gimmick? All the faulty bionics. All of them.
1. Added a broken cyborg class. Like the failed cyborg, only infinitely worse. Additionally, the only positive bionics are all passives (armor plating for example), which is a gameplay niche only filled by the razor boy/girl class.
2. Added said profession to the experiment and lab challenge scenarios.

Feedback would be appreciated, especially concerning point cost and whether or not to retain the useful bionics. I would still prefer to retain the "every faulty bionic" gimmick though.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I like this. It seems like it might fit in the hospital scenario too.

**Comment by chaosvolt** [comment]
Hospital as well? Tempting. o.o

**Comment by Rivet-the-Zombie** [comment]
>bionic patient gone wrong

That was what I was thinking.

**Comment by chaosvolt** [comment]
Might be interesting, yes. And augh, bad satellite, stop hnnging at me. >.<

**Comment by Coolthulhu** [comment]
With painkillers stopping pain from waking you up this should now be doable, but it is a very restricted challenge. For example, Fast Healer is pretty much mandatory unless you get huge luck at start.

The part about passive positive bionics doesn't fit, though. At least 2 of the negative ones rely on player having a store of energy. It would be better to add a useful energy generation bionic that can't be turned off (torsion ratchet? solars?) and at least 1 energy storage CBM.

**Comment by chaosvolt** [comment]
Hmm, that might work. It does hinder the player's long-tern bionic prospects, but...could add those then. And suggests on active bionics to use them with, and whether to remove any of the passive positive bionics?

**Comment by Coolthulhu** [comment]
I'd get rid of strength enhancement. Doesn't really fit the theme of a falling apart semi-robot, because while in game it is fully passive, IRL such a thing would be reactive (would have to read user's actions to know what to "enhance").

**Comment by chaosvolt** [comment]
Ah, could work. Any active bionics? Hydraulic muscles, or something else?

**Comment by Coolthulhu** [comment]
No, that would offset the negative bionics that use it to harm the player.

**Comment by chaosvolt** [comment]
True. Was thinking that giving the player a way to drain power would be a good thing, but you're right in that it'd mitigate the drawback. X3

**Comment by Coolthulhu** [comment]
Looking at the stats, I'm not sure if it's worth -5. On one hand, the mandatory Fast Healer means you're down 2 points on traits. However then you gain Fast Healer, which isn't that bad.

You gain a lot of rare bionics - armor and razors won't just drop on shockers.

-5 is A LOT and you can get it in Lab.

I'd remove it from Lab challenge and possibly lower the point bonus to -4 or -3. It's fine in experiment and regular, because those don't give extra points, but Lab gives a lot and also allows mutations as traits.

**Comment by chaosvolt** [comment]
Hmm. Understandable, though would be interesting to have it be in the lab challenge.

**Comment by Coolthulhu** [comment]
It would need a low point bonus, though. Like, -2 instead of -5.
It doesn't really offer much extra challenge in labs - you don't sleep a lot in there, stealth isn't needed, ear mufflers actually help a lot with sleep (mi-gos won't shut up), only acid and sleepy hurt.

**Comment by chaosvolt** [comment]
Hmm. How horrendous would it be if the point cost was -2 when playing the other scenarios?

**Comment by Coolthulhu** [comment]
Not all that bad. A bit worse than failed cyborg early on, but failed cyborg already has most of the annoying CBMs. It only lacks leaky bionic for the evil combo of leaky+acid.
On the other hand, it has no buffs - all its CBMs are bad, unlike broken cyborg's.

**Comment by chaosvolt** [comment]
Hmm, so essentially the broken cyborg's isn't quite a straight-up "failed cyborg, only worse" profession. More of a sidegrade I guess.

Thing is when I've toyed with this, I found itchy metal thing to be the worst part of it actually. XP

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
