### PR TITLE
Move sheet to ARMOR_OTHER with the blankets and towel

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by mugling** [comment]
It's not armor though

**Comment by Cyrano7** [comment]
@mugling It's clothing technically.

**Comment by mugling** [comment]
It's also used for constructing vehicle parts

**Comment by mugling** [comment]
A number of other items can be worn and yet aren't armor. It does correctly belong in a miscellaneous (eg `other`) category

**Comment by Cyrano7** [comment]
True I didn't think about the vehicle parts. That's why we have the armor other category to. Those items like binoculars or head torch can't keep you warm or cover you though so I don't think they are comparable.

**Comment by Cyrano7** [comment]
@mugling Since sheets are used in vehicles I guess it should stay where it is for now. I'm fine either way really. Not something worth fussing with to much.

**Pull request closed without merging**
