### PR TITLE
Allow mods to override specific properties of monster types.

### PR DESCRIPTION
**Pull request by BevapDin**
Only the first encountered definition of a monster type needs to be complete (including all mandatory properties). Once the type has been loaded, it can be loaded again (e.g. via mods), but they can omit any property and only need to specify changed properties.

For example, a mod may only change the name and hp of a monster:

``` JSON
{
    "type": "MONSTER",
    "id": "mon_zombie_tough",
    "edit-mode": "modify",
    "name": "not so tough zombie",
    "hp":20
}
```

The only required data here is the "type" and the "id" to identify the existing object and the "edit-mode".

Edit mode defaults to "create", it can also be "override" or "modify". "create" creates a new object and throws an error if an object with that id already exists. "override" simply overrides an existing object (if there is any at all). "modify" allows to modify an existing object (and fails if there is no object with that id).

"create" is the default, so one gets informed when accidentally using the id of an existing object. Some mods override core monster types and now require `"edit-mode": "override"`. They could perhaps be changed to only modify the existing types, but I don't know what exactly the mods change.

---

Implementation:

A `generic_factory<T>` instance is used to store the loaded objects (it's basically a `map<id, T>`). It handles insertion, overriding existing entries (examine "id" and "edit-mode" properties), and resetting. The class can be used to implement the `string_id` functions that access the loaded objects.

Objects that are supposed to be loaded via the `generic_factory` must have a `string_id id` member (as usual) and a `bool was_loaded` member. They must be default constructable and must have a `load(JsonObject &)` member function.

That `load` function is the center of all loading, it is either called on a new object, or on an already loaded object that is to be modified. The `was_loaded` member can be used to distinguish those two situations (it is initially `false` and set to `true` by the `generic_factory` after loading the object for the first time). It allows to ignore missing mandatory JSON data, if the object had already been loaded.

---

There are some helper functions:

`mandatory(jo, was_loaded, name, member)` loads a mandatory member (`member` is a reference to that member) from the member `name` of the JSON object `jo`. The function will fail if the JSON data doesn't contain the requested member.

`optional(jo, was_loaded, name, member, default)` is similar, but sets the member to the given default value if it is not in the JSON object.

Both functions will silently skip the member if `was_loaded` is true and the JSON data does not contain the requested member, thereby keeping the existing value.

There are overloads for both functions that takes an additional parameter: a `reader` object. It can be used to read/convert complex data from the JSON, for example for loading a set of flags or a `nc_color` from a string. Examples:
- `translated_string_reader` automatically translates the loaded string (if non-empty).
- `color_reader` converts a color string to `nc_color`.
- `generic_typed_reader` loads or changes a container of things, e.g. a flag set. It is used by some other readers that convert the JSON input to properly typed data.

The `generic_typed_reader` can override the existing data completely, or it may add/remove single entries:

``` JSON
{
    "type": "MONSTER",
    "id": "mon_zombie",
    "edit-mode": "modify",
    "remove:flags": [ "REVIVES" ],
    "add:flags": [ "IMMOBILE" ]
}
```

This adds the IMMOBILE flag and removes the REVIVES flag, any other flag is left as is. However, this is only used when the object has already been loaded, and when there is no JSON member "flags" (if the JSON contains both "add:flags" and "flags", the "add:flags" entry is ignored).

The names of the add and remove arrays are generic: the are derived from the requested member name, so it works for triggers (e.g. "add:anger_triggers"/"remove:anger_triggers") and the list of death functions and the categories/species of a monster.

Most properties of the monster type can only be override at once, that means one can override the list of special attacks, but not modify part of it. This could be implemented later.

Monster upgrades can be disabled with `"upgrades": false;`, or one can change the target of the upgrade or the half life.

---

This PR may conflict with some other PRs (notable "Jsonized monster attacks"), those should get in prior so I can update this one.

It's huge because adding the helper functions and the `generic_factory`. Both can be reused with other object types. I have a branch in work that implements overriding specific properties for other things like traps, vehicle parts, skills, item types etc.

Btw. the code does more checks for valid input now: monster flags and monster triggers and monster size. Those were invalid in some files, but had been silently ignored.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, this is interesting. I suppose if/when this gets merged, I can change my mods that edit monsters to use modify. XP

**Comment by Coolthulhu** [comment]
Looks good, though also huge.

I see some monster flags removed. Are those flags all obsolete/unimplemented/misnamed?

**Comment by BevapDin** [comment]
> I see some monster flags removed. Are those flags all obsolete/unimplemented/misnamed?

The current code does not check those flags and ignores invalid ones, now it does check and the removed/changed flags triggered those checks:

The creature size is an all uppercase string, the change "medium" => "MEDIUM" doesn't change a thing in game as the "MEDIUM" was the assumed default anyway.

There is no monster flag "DEAF" nor "SMALL_BITER", I removed both.
There is no trigger "BONES", so I removed that as well. Both changes should not affect the game as the invalid values had been ignored anyway.

The flag "ACID_PROOF" is not defined, but "ACIDPROOF" is, so I changed the former as that seems to be the intention. This will change the behavior to the intended behavior.

**Comment by illi-kun** [comment]
> There is no trigger "BONES", so I removed that as well.

I don't get it, ```monstergenerator.cpp:L353``` contains implementation of ```BONES``` flag:
```flag_map["BONES"] = MF_BONES```

**Comment by Zireael07** [comment]
Flag != trigger.

**Comment by BevapDin** [comment]
Yes, it has the flag, but not the trigger. Monster flags and triggers are different things. Valid triggers are defined in mtype.h:
```C++
enum monster_trigger : int {
    MTRIG_NULL = 0,
    MTRIG_STALK,  // Increases when following the player
    MTRIG_MEAT,  // Meat or a corpse nearby
    MTRIG_HOSTILE_WEAK, // Hurt hostile player/npc/monster seen
    MTRIG_HOSTILE_CLOSE, // Hostile creature within a few tiles
    MTRIG_HURT,  // We are hurt
    MTRIG_FIRE,  // Fire nearby
    MTRIG_FRIEND_DIED, // A monster of the same type died
    MTRIG_FRIEND_ATTACKED, // A monster of the same type attacked
    MTRIG_SOUND,  // Heard a sound
    N_MONSTER_TRIGGERS
};
```
Maybe `MTRIG_MEAT` was meant?

**Comment by illi-kun** [comment]
I somehow missed that ```"anger_triggers"``` array is changed (and not ```flags``` as I expected), sorry for that.

**Comment by chaosvolt** [comment]
Oh, hell yes. o3o

**Comment by Malkeus** [comment]
doc\JSON_FLAGS.md - FRIENDLY_SPECIAL monster flag.
Does it exist in a different form? It's still in the Docs but I had to remove it from Jury Rigged Robots in order to fully load the mod.

**Comment by BevapDin** [comment]
FRIENDLY_SPECIAL was removed a while ago. Monster attack functions decide on their own whether they are used by friendly monsters.

**Comment by Malkeus** [comment]
Ok, thank you

**Pull request merged**
