### PR TITLE
Quantum solar panels now break into quantum solar cells

### PR DESCRIPTION
**Pull request by Core0verload**
New item: quantum solar cell. It's used in crafting quantum solar panels (8 cells) and Solar Panels CBM (2 cells). It never spawns naturally and can't be crafted. You can found these cells when disassembling quantum solar panels, Solar Panels CBM and inactive laser turrets (4 cells per turret, these turrets are really rare). Breaking a quantum solar panel will spawn 2-8 quantum cells. 

This explains why Solar Panels CBM is so efficient at generating power and makes losing a quantum panel a bit less painful.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That breaking apart part is OK, but I'm not sure about the CBM and laser turret parts.

Quantum panels are currently only found as lab finale drop. I assume that in the lore they're cutting-edge technology, not yet released anywhere, possibly top secret.
Solar panel CBMs are way more common than that.

As for the laser turret, it is already risky to ever deploy it. It has a stupidly high cost in components compared to its usefulness. It doesn't need more expensive, rare, uncraftable components to make it into an item you only ever deconstruct.

So,
Breaking into quantum cells is OK.
CBM with quantum cells is OK if we change lore and get rid of quantum panel's primary gimmick of being a lab finale drop.
Laser turret with quantum cells is not OK.

**Comment by Core0verload** [comment]
Laser turret can be crafted with regular cells, but it will require a lot of them. It spawns with quantum cells by default.

**Comment by Coolthulhu** [comment]
> It spawns with quantum cells by default.

It should spawn with the most efficient setup, ie. cheapest one, with regular solars.

**Comment by Core0verload** [comment]
I doubt "efficient setup == cheapest setup" was ever true for cutting edge military equipment. Lasers consume a lot of power. Turret with quantum cells will be smaller and less noticeable, with all cells built into a hull, while survivor-crafted version will have a pair of large and bulky solar panels strapped on it's sides.

**Comment by Coolthulhu** [comment]
> Fluff-wise, turret with quantum cells will be efficient: smaller and less noticeable

They produce highly visible lasers. They're not cost-efficient and would get even less cost-efficient if quantum cells were added to them.

If you want to make them use quantum cells by default, remove them from spawns other than lab finale.

**Comment by Cat09** [comment]
Ideally, any system with the turrets would be wired up to backup batteries and a full solar array.
For any of the electric stuff to make sense though, we really need at least a semi-working wiring system for buildings.
Solar cells on an underground laser turret is quite silly, they should be assumed to be connected to the building's power supply, in that case. they would then need to be balanced differently I think, infinite ammo as long as there is a power supply, 100% accurate, long recharge time (filling capacitors?)

I like the quantum cells, that does make panel loss much easier to swallow.
Solar panel CBMs are just rediculous to begin with, I think they should be removed honestly.

**Comment by kevingranade** [comment]
Buildings made with map gen aren't getting wiring, that would be a huge
amount of processing in the background in order to support a handful of
incredibly niche use cases, not to mention the time and maintenance burden
of the code.

**Comment by Coolthulhu** [comment]
> Buildings made with map gen aren't getting wiring

We could have localized "pseudo-wiring", like what is going on with military outposts' searchlights. Replacing outpost turrets with laser ones would make them capable of fending off zombie hordes indefinitely.

**Comment by kevingranade** [comment]
"Implied" wiring is fine (I think that's what you mean), or even a wiring network like what the player can build, just not pervasive "wired buildings".

**Comment by Cat09** [comment]
do you guys think it would be feasible to have each building (mapgen unit?) have implied wiring and lighting (that does nothing at all without power to avoid processing)
you could then set up a proper house base with solar panels and charging stations.
that could lead to docking points for electric farm bots to tend your crops
that'd be a neat power goal, anyway.
there would obviously need to be a good method for retroactive processing (power gen vs power use, storage capacity, etc.) otherwise it'd have the potential to be far too resource intensive.

**Comment by kevingranade** [comment]
On Feb 18, 2016 12:12 PM, "Cat09" <notifications@github.com> wrote:
>
> do you guys think it would be feasible to have each building (mapgen
unit?) have implied wiring and lighting (that does nothing at all without
power to avoid processing)

The problem is, the only way to check if it's active is to scan through all
the wiring items to check if there is a power source attached. There might
be some caching we can do here, but it still means nearly doubling the
amount of data used to define a house.

> you could then set up a proper house base with solar panels and charging
stations.
> that could lead to docking points for electric farm bots to tend your
crops
> that'd be a neat power goal, anyway.

But this is my main problem with the concept, you (and basically everyone
else who has asked about it) seem to want it to all "just work", but in
reality it would be quite difficult to modify the existing wiring in such a
way that it will be safe to use, and that's assuming nothing has happened
to the wiring in the house.  The likely outcome is plugging in a generator
and some lights, and shortly afterwards burning the house down.

Meanwhile there is already a system in place for point-to-point wiring, why
aren't you using that?

**Comment by mugling** [comment]
Appears stalled, closed to reduce the PR queue somewhat. Could be reopened if OP wanted to resume work.

**Pull request closed without merging**
