### PR TITLE
Unloading magazines is interruptable 

### LINKED ISSUE #23440: Unloading magazines (especially belts) can lead to player move starvation for a long time.
### Expected behavior
Unloading an ammunition belt can be interrupted by '.' or safe mode.
### Actual behavior
Unloading an ammunition belt is uninterruptable and can allow a monster to kill you while performing it.
### Steps to reproduce the behavior
Stand near the corner of a building.
Spawn a full (hundreds of rounds) ammunition belt.
Spwn a hostile monster nearby.
Run around the corner of the building, breaking sight with the monster.
Turn on safe mode.
'U'nload the ammunition belt.
Monster will round the corner and attack a large number of times before the layer has an opportunity to act.

Thnaks to vipchess for reporting: https://discourse.cataclysmdda.org/t/is-there-something-wrong-about-the-ammo-belt/15257

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

 ```SUMMARY: Bugfixes "Unloading ammunition belt can be interrupted"```  

#### Purpose of change

Fixes #23440 - Removing ammunition belt leads to player move starvation.

#### Describe the solution

- Created a new activity_handler::unload_mag_finish that allows the action to be interrupted. 

- Moved add_or_drop_with_msg from game.cpp to player.cpp

#### Describe alternatives you've considered
Considered also moving unload() methods from game to player class?

### CODE REVIEW

**Comment by f0cus10** [comment]
For future reference, the issue that persists is this:

After *unloading*, accessing the **inventory** crashes the game

Here's the crash log: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2696110/crash.log)

**Comment by OzoneH3** [comment]
The activity is started after the ammo is already removed from the belt which makes no sense at all.
Wouldn't it be better if it was an activity for all unload actions and not just belts?

**Comment by f0cus10** [comment]
> The activity is started after the ammo is already removed from the belt which makes no sense at all.
Hmm... we'll look into that

> Wouldn't it be better if it was an activity for all unload actions and not just belts?
We considered doing it for magazines, but the original issue only included ammo belts as the target. More than willing to revise, if necessary, though.

**Comment by yizongk** [comment]
Current version of the branch, in player::unload(item), if it pass the check that the item is a magazine, it will create a player activity and assign it to the player. Before it finishes the function, it will go through the contents list of the item, calculating the necessary moves it would need for the action to be completed, and set it to the player_activity::moves_left that we just created. 

When the game loop calls on the player activity, it will do what it does to decrement  player_activity::moves_left. During this phase, the activity will do NOTHING. It is only when player_activity::moves_left is <= 0 that it will call the finish function associated with our current player_activity. 

It is only in the finish function that we remove the actual ammo away from the ammo-belt, and getting a belt-linkage from the ammo-belt.

I would love to hear what you guys think of this current version

**Comment by yizongk** [comment]
The crashes from the previous fix are no longer existing. This PR is open to review.

**Comment by kevingranade** [comment]
Testing proves out ok, thanks a ton!

**Pull request merged**
