### PR TITLE
Normalize shot ammo

### PR DESCRIPTION
**Pull request by mugling**
`stack_size` of 20

drops `shot_scrapbag`, `reloaded_shot_beanbag` and `reloaded_shot_bird` similar to earlier deprecation of useless reloaded `22` ammo types.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
We want to keep `reloaded_shot_bird` because the `NOGIB` flag makes it good for hunting small game.

**Comment by mugling** [comment]
Fair enough

**Comment by Mecares** [comment]
Not very useful ammo was nice for disassembling and crafting different ammo.

**Comment by mugling** [comment]
Sure which is why we have beanbag rounds and the like which are left in. `reloaded_shot_bird` has a reason to exist as pointed out by @Rivet-the-Zombie points out, however there's little reason to craft reloaded beanbag rounds.

**Comment by kevingranade** [comment]
@mecares if I understand correctly this just makes them uncraftable, it
doesn't prevent them from spawning or being disassembled.
@mugling is that correct? Also is the goal here to de-clutter crafting
menus?

**Comment by mugling** [comment]
@mecares Beanbag ammo is still in but is nolonger craftable. You can still craft birdshot as per @Rivet-the-Zombie's suggestion

@kevingranade Yes, but also de-clutter of JSONs

**Comment by Darkyhard** [comment]
Actually, those beanbag shells could be used as shotgun ammo if you have everything but metal for making proper shotgun shells. Or later one could use beanbags to calm down NPCs and make them flee if they don't want to kill them for a morale penalty. So I think that they still have a reason to exist.

Also, beanbag ammo could get a NOGIB flag, as it is even less deadly than birdshot and therefore certainly not more likely to turn small game into a pile of gore on hit.

**Comment by mugling** [comment]
> Actually, those beanbag shells could be used as shotgun ammo if you have everything but metal for making proper shotgun shells.

In what scenario do you lack metal in any form but have the extremely rare `rubber_slug` component? Even without `lead` or similar supplies for `reloaded_shot_00` or `reloaded_shot_slug` you can use scrap metal for ``shot_scrap` and `shot_scrapslug`.

> @mugling is that correct? Also is the goal here to de-clutter crafting menus?

We have a lot of undocumented features and items of marginal interest. Removal of these is good for everyone. The crafting menu is an excellent example of such bloat but it's the manageability of the JSON's my main concern.

In case that escaped anyone's notice shotgun ammo even has three grades for each type, 'standard', 'reloaded' and 'makeshift'. Such complexity must surely be off-putting to new players? We should focus on documentation not new items. I know @remyroy has shown some interest in working on the wiki - perhaps a collaboration on an article on the reloading/ammo etc?

> Or later one could use beanbag to calm down NPCs and make them flee if they don't want to kill them for a morale penalty. So I think that they still have a reason to exist.

Whilst that would be a nice feature I'm not aware of anybody working on it and given the number of outstanding large projects underway I can't see it being added any time soon. The current plan I'm following with `obsolete.json` breaks nobodies saves and allows for fast resurrection of an item if an appropriate niche can be found.

> Also, beanbag ammo could get a NOGIB flag

Makes sense

**Pull request merged**
