### PR TITLE
Fixed player test

### PR DESCRIPTION
**Pull request by kevingranade**
Fixed the long-broken player temperature test, and tweaked the values to reflect the current reality in the game.
My next step is to refactor player::update_bodytemp() to not call into game and map, but instead have the environmental conditions passed into it.
Then I'm planning on tweaking update_bodytemp to finally act as intended as per the commented out tests, which as you can see is much harsher than the existing behavior at the low end.  Don't worry, the exact values are up for discussion, but I think we can agree it's nearly impossible to freeze right now, making cold only a hassle unless it slows you down enough for a monster to get you.

### CODE REVIEW

**Comment by Barhandar** [comment]
Hopefully that means summer won't cause figurative melting with clothes on like it does now. 

Why Turks wear their khalats, which can get pretty thick? Outside might be -20C or it might be +40C with intense sunlight, but inside will be 36.6C regardless.

**Comment by kevingranade** [comment]
Thick != warm, that kind of clothing is actually rather cool, but in dda
would be encumbering.

**Comment by DavidKeaton** [comment]
The idea of insulation is more accurately stated as not "keeping one warm," so much as "keeping the outside temp outside" of oneself. A knit hat keeps you warm because it keeps your body heat from being pulled away. Some clothing instead keeps the heat on the outside, even though it looks like it would be hot to wear.

**Comment by kevingranade** [comment]
I think it's the other way around, humans generally need to get rid of excess heat, so warmth is "trapping body heat".
On the other hand if heat from sunlight dominates the equation, e.g. in a desert, keeping the sun off you is more important.

**Comment by DavidKeaton** [comment]
Well that is what I said. It keeps the ambient air from pulling that heat.

**Comment by Coolthulhu** [comment]
Got it to compile now, but couldn't link on MinGW because:
```
ld.exe: cannot find -lrt
```

When I removed `-lrt` from tests/Makefile, it linked fine but crashed at start.

**Comment by BevapDin** [comment]
> When I removed  -lrt  from tests/Makefile, it linked fine but crashed at start.

Had the same problem. One entry in "data/json/vehicle_groups.json" is not accepted. Removing the file (temporarily while running the tests) fixed *that* crash, but I still got another crash later. Maybe a full recompilation will help.

**Pull request merged**
