### PR TITLE
Cowboy profession

### PR DESCRIPTION
**Pull request by SirPiecemaker**
Closed due to being merged in #33683

### CODE REVIEW

**Comment by SirPiecemaker** [comment]
> While the LeMat wouldn't be outside the realm of possibility, it'd really be more likely for a cowboy to use the Colt Navy revolver. For one thing, there were around 2,700 LeMats built in total betweel 1856 and 1865; there were _270,000_ Colt Navies produced between 1850 and 1873.

Afraid I wasn't aware the Colt Navy was in the game. That being said, it seems exceedingly weak right now.

**Comment by Kanexan** [comment]
Using it, it is kinda underwhelming. Definitely feels like it could do with a bit of a rework (and a cut down on all the damned smoke it makes! You can't shoot the thing without choking half to death!), but it would be the more likely choice for a gunslinging desperado flung through time.

**Comment by tenmillimaster** [comment]
Lemat's are rather finicky; The dual firing pin design isn't exactly the best (even on the repro's). This isn't the sort of weapon I'd expect a 'performer' to rely upon. 

On account of the comments here, I have spot checked the ballistics of a few varying loads chrono'd on the internet.
.36 Paper's Json entry says it deals 19 damage, or 361 J.


Below are the loads I was able to find.

[Commercial Go-ex loads](https://goexpowder.com/wp-content/uploads/2018/06/rb-pistol-revolvers.pdf) : 70gr lead ball, 22 gr FFF Goex, 710 fps. Produces 106 J, or 10.30 CDDA damage.
[Commercial pyrodex loads](http://ns.hodgdon.com/PDF/muzzleloading_manual_2008.pdf?CHECKBOX_1=on): 79 gr lead ball, 30gr pyrodex p, 935 fps.  Produces 208 J, or 14.42 CDDA damage.
[Hotter load mentioned on wikipedia page](https://en.wikipedia.org/wiki/Colt_M1861_Navy): 80gr @ 1000fps:  241J or 15.52 CDDA damage.


[Loads worked up by THR forums](https://www.thehighroad.org/index.php?threads/powder-load-for-1581-navy-replicas.340059/)83gr lead ball, 25gr FFFg Swiss, 1101 fps. Produces 303 J, or 17.41 CDDA Damage.
[Very similar to this published load.](https://books.google.com/books?id=LQausfRgWvYC&pg=PA123&lpg=PA123&dq=Dixie+Gun+Works+Catalog++"grains"+".36"&source=bl&ots=XCASntte-P&sig=ACfU3U1lKYXs-AN8nLFyBzkrM75tGp7Gjg&hl=en&sa=X&ved=2ahUKEwjct_3SkqjkAhVCT6wKHW1fA6MQ6AEwEHoECAkQAQ#v=onepage&q=Dixie%20Gun%20Works%20Catalog%20%20"grains"%20".36"&f=false)



So it appears that the .36 m1861 does *too much* damage. Bear in mind that with an open frame revolver, frame stretching with hotter loads can be a bit of a long term durability concern.

**Comment by SirPiecemaker** [comment]
> So it appears that the .36 m1861 does _too much_ damage. Bear in mind that with an open frame revolver, frame stretching with hotter loads can be a bit of a long term durability concern.
> 
> If you're looking for **oomph** from black powder, [this ](https://en.wikipedia.org/wiki/Colt_Walker)is what you want.

The colt is basically unusable right now, making it even worse seems like a rather bad idea.

**Comment by tenmillimaster** [comment]
> > So it appears that the .36 m1861 does _too much_ damage. Bear in mind that with an open frame revolver, frame stretching with hotter loads can be a bit of a long term durability concern.
> > If you're looking for **oomph** from black powder, [this ](https://en.wikipedia.org/wiki/Colt_Walker)is what you want.
> 
> The colt is basically unusable right now, making it even worse seems like a rather bad idea.

It seems unusable because of how damage works on zombies. Against living targets, it should be quite adequate.

**Pull request closed without merging**
