### PR TITLE
add translation::serialize

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Features "adds translataion::serialize member"```
#### Purpose of change

This is to make it more accessible to serialize translations. this serialize shall be used in the nested container series of PRs, but this is a standalone feature.
#### Testing

serialize and deserialize functions

### CODE REVIEW

**Comment by Qrox** [comment]
I don't think serializing a translation is a good idea. Once the original string in the code/json files changes, the serialized translation won't translate correctly, as the po files will no longer contain the serialized strings.

**Comment by KorGgenT** [comment]
i can see this also being needed to be addressed for artifacts as well, so what might you suggest instead?

**Comment by Qrox** [comment]
Ideally all persistent information needed to generate an artifact's name should be saved, for example, random seeds or snippet ids, which are persistent through the game's changes. Or you can just follow the current approach for artifact names, that is saving the name as a translated string, and loading the name and call `no_translation` with it to construct a translation object.

**Comment by KorGgenT** [comment]
well you've convinced me i think. i'm not sure what i'm going to do about artifacts specifically, but i'm just going to remove the ability to specify the names of pockets in nested containers until some future date.

**Pull request closed without merging**
