### PR TITLE
Add ability to revert submaps to update mapgen.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Part of #52475 
Allow saving maptiles to be reverted later.  

#### Describe the solution
Previously the goal for nether dungeon placement was to just find a field and place it.  This would erase anything already there so instead just save and revert the map tile, now they can be placed anywhere as a bonus.

#### Describe alternatives you've considered
Also saving items.  Seemed like a lot more data to store and bug prone so I avoided it.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
What about vehicles? Portal storms eating your deathmobile would probably not go down well...
Also, erasure of items is definitely not going to be appreciated if it hits you stockpiles, especially if the relaxed restrictions allow placement over non field terrain (such as the farm you're staying at, the building you're staying in, or your base camp).

**Comment by Ramza13** [comment]
> What about vehicles? Portal storms eating your deathmobile would probably not go down well... Also, erasure of items is definitely not going to be appreciated if it hits you stockpiles, especially if the relaxed restrictions allow placement over non field terrain (such as the farm you're staying at, the building you're staying in, or your base camp).

So to be clear nether dungeons will not erase items at all, they will stay where they are and even if they are in a wall when it changes back they will still be where they started.  As for vehicles they also should remain untouched but I didn't test what a wall appearing inside of them would do so good call.

**Comment by PatrikLundell** [comment]
A sorry for misunderstanding what you actually wrote.

**Comment by Ramza13** [comment]
> A sorry for misunderstanding what you actually wrote.

Ha no worries, I'm better at coding than documenting it.

**Pull request merged**
