### PR TITLE
IWYU support (part 2): Miscellaneous prep work

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: None

#### Purpose of change
To permit [IWYU](https://github.com/include-what-you-use/include-what-you-use) to run cleanly on the codebase requires various tweaks and tidying up.  This PR makes the necessary changes.  The plan is to follow up with a PR which contains only the changes made by IWYU once this is in.  Don't want to put it all together because the header changes make other changes too difficult to find and review.

#### Describe the solution
Various things, including:
* Pragmas to explain things to IWYU when it is unable to understand them.
* Manually moving some includes when IWYU moves them wrongly (e.g. it would move them out of a `#ifdef`).
* Adding mapping files to explain to IWYU which files provide what symbols, and which headers are private.
* For IWYU to be happy, when a function takes an argument whose type is implicitly convertible from some other type, the header declaring that function must include the header defining that type.  See [here](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhatIsAUse.md) for more details.
* For related reasons, any function return types must be either directly included or forward-declared before running IWYU.
* Moved the `io::..._archive_tag` definitions into a separate header and included it elsewhere instead of forward-declaring.
* Removed forward declarations of unit-related types and included the header instead, so that implementation details of units don't leak out.
* Un-inlined one move constructor (defining it in the cpp file) to reduce the dependencies in the header which IWYU didn't understand.
* Tidied up the SDL headers, so they are almost exclusivley included via the `sdl_wrappers` header, that deals with the platform-specific issues in one place.
* Added some docs about running IWYU.

#### Describe alternatives you've considered
We could just not do this.

#### Additional context
To make this work I've also had to patch IWYU.  I've made four PRs, of which two have so far been merged.  The other two will need to be merged before anyone else can run IWYU without much hassle.

If you're curious as to whether IWYU will actually save us compile time: I'm now finally in a position to answer that, ~~but I haven't done the necessary experiments yet~~ and the results are below.  It doesn't make much difference; this is more about maintaining order in the codebase than getting build performance, but at least it means that future efforts towards compile-time optimization ought to be easier.

### CODE REVIEW

**Comment by jbytheway** [comment]
Gorgon isn't happy because I added a blank line to `json.h`.

**Comment by jbytheway** [comment]
Have now calculated some build timings.  These are times for a from-scratch rebuild with -j4.  Debug build with all the features turned on.  Three trials for each of three situations.

on master:
```
real    8m17.082s
user    31m15.490s
sys     1m27.512s

real    8m21.513s
user    31m34.502s
sys     1m27.682s

real    8m14.620s
user    31m11.736s
sys     1m26.803s
```

on this branch:
```
real    8m18.163s
user    31m25.603s
sys     1m27.586s

real    8m16.442s
user    31m20.368s
sys     1m27.438s

real    8m16.883s
user    31m19.518s
sys     1m27.470s
```

after running IWYU on this branch:
```
real    8m39.643s
user    32m10.881s
sys     1m28.938s

real    8m18.126s
user    31m26.778s
sys     1m26.859s

real    8m16.669s
user    31m21.480s
sys     1m27.112s
```

So, as expected, not much difference.  If anything it might be a little slower.

**Comment by ZhilkinSerg** [comment]
I am not totally sure yet, but I suspect this PR causes linking issues under MSYS (and probably MinGW too):

image

Possibly related - https://github.com/libSDL2pp/libSDL2pp/issues/66.

**Comment by ZhilkinSerg** [comment]
Android builds were also broken - https://ci.narc.ro/job/Cataclysm-Android/8389/console

```
06:06:11   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/main.cpp:57:24: error: use of undeclared identifier 'read'
06:06:11           if( ( ( rdsz = read( pfd[0], buf, sizeof buf - 1 ) ) > 0 ) ) {
06:06:11                          ^
06:06:11   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/main.cpp:77:5: error: use of undeclared identifier 'pipe'
06:06:11       pipe( pfd );
06:06:11       ^
06:06:11   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/main.cpp:78:5: error: use of undeclared identifier 'dup2'
06:06:11       dup2( pfd[1], 1 );
06:06:11       ^
06:06:11   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/main.cpp:79:5: error: use of undeclared identifier 'dup2'
06:06:11       dup2( pfd[1], 2 );
06:06:11       ^
06:06:11   4 errors generated.
06:06:11   make: *** [/var/lib/jenkins/workspace/Cataclysm-Android/android/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/main/main.o] Error 1
```

**Comment by Barhandar** [comment]
>I am not totally sure yet, but I suspect this PR causes linking issues under MSYS (and probably MinGW too):

Can confirm that I have same issue with compiling latest repo with MSYS.

**Comment by jbytheway** [comment]
I've gone ahead and made the final PR in the set (#27713) because I thought that would probably break both Mingw and Android builds as well, and there's little point fixing them between this one and that one.

**Comment by jbytheway** [comment]
#27713 didn't go through immediately, so I've made PRs (#27755, #27757) that I hope might fix the two issues raised above in the mean time.

**Pull request merged**
