### PR TITLE
Add tupelo and nannyberry trees

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Content "Add tupelo and nannyberry trees"

#### Purpose of change

More native flora so we can eventually replace all those orchard-grade random fruit trees with just those. There is no nutrition information for those on the web, like most lesser known foraged foods, so I copy values from elderberries as they are the closest resemblance. As this is literally just a copy-from this is trivial to change however.

#### Describe the solution

- Add tupelo and nannyberry trees.
- Add item, harvest and regional mapgen entry for them, add them to fruit leather and dehydrated fruit

#### Testing

Applied changes locally. I was able to find both trees in swamps ingame and harvested them. The fruits can be crafted with, too, as intended.

#### Additional context

What do I do next? Maybe black cherry. There are also the wild raisins and foxgrape, another viburnum like nannyberry.

Edit: Forgot to paste my sources lol

- https://gobotany.nativeplanttrust.org/species/nyssa/sylvatica/
- https://gobotany.nativeplanttrust.org/species/viburnum/lentago/
- https://www.eattheweeds.com/nyssus-tart-botanical-tangles-2/
- https://eattheplanet.org/black-tupelo-an-unknown-native-fruit-tree/
- https://practicalselfreliance.com/nannyberry-viburnum-lentago/
- https://foragerchef.com/nannyberries/
- https://plants.ces.ncsu.edu/plants/viburnum-lentago/

### CODE REVIEW

**Comment by ampersand55** [comment]
> What do I do next? Maybe black cherry. There are also the wild raisins and foxgrape, another viburnum like nannyberry.

With all these foraging options, it's a bit weird that we only have one type of named mushroom in the game, morels.

Some common New England mushrooms, besides morels, are:

* Oyster Mushrooms (Pleurotus ostreatus) 
* Chicken of The Woods (Laetiporus sulphureus) 
* Hen of the Woods (Grifola frondosa)
* Chanterelles (Cantharellus spp.)
* Black Trumpet (Craterellus cornucopioides)
* Lion's Mane (Hericium erinaceus)
* Boletes (Boletus spp.)	
* Lobster Mushroom (Hypomyces lactifluorum)
* Puffballs (Calvatia spp., Lycoperdon spp.)
* Winecap (Stropharia rugoso-annulata)

**Comment by NetSysFire** [comment]
I looked into mushrooms and the difficulty there is id'ing those as there is a much, much greater risk into running something super dangerous there as compared to trees and we do not support conditional item names and descriptions. Plus I am currently working on good replacements regarding nutrition and no matter what mushroom, these usually do not have much calories. So adding those is flavor, not utility.

It would be super fun to model dangerous or even deadly mushroom effects using the vitamin system however. That is for later though.

**Comment by ampersand55** [comment]
> I looked into mushrooms and the difficulty there is id'ing those as there is a much, much greater risk into running something super dangerous there as compared to trees and we do not support conditional item names and descriptions. 

There's already some support for poisonous look-alikes being foraged with the `HIDDEN_POISON ` and `FORAGE_POISON` flags. I'm not sure they are functional though.

Many of the mushrooms I listed are quite distinct and can't really be mistaken for any poisonous mushrooms. Especially Chicken of The Woods, Hen of the Woods, Lion's Mane, Lobster Mushrooms and Puffballs. The most common types of poisonous mushrooms in New England that could be mistaken for an edible mushroom would be some type of [false morel](https://en.wikipedia.org/wiki/False_morel), and the morel is already in the game. 

Besides, any type of foraging of plants you don't recognize can be dangerous. you could confuse e.g. black nightshade berries with other black berries or baneberries for other red berries. 

Another foraging suggestion, some poisonous berries such as black nightshade berries, baneberries and winterberries. 

> Plus I am currently working on good replacements regarding nutrition and no matter what mushroom, these usually do not have much calories. 

They have a low amount of calories per mushroom as mush of the volume is just water and air, but that just means you just need more of them per serving. Mushrooms generally grow in droves. I sometimes go picking chantarells in Sweden with my family, and on a good day I can pick about 5 kg chantarells per hour, which is ~1500 calories. But of course, picking berries is more calorie efficient. 

> It would be super fun to model dangerous or even deadly mushroom effects using the vitamin system however. That is for later though.

That would indeed be super fun. However in the meantime there's the "Toxins" vitamin that's is already being used generically to represent the poison in mayapples.

**Comment by NetSysFire** [comment]
Please make a dedicated issue about this. Besides, there are enough shrooms that are poisonous and a spoiled big city evacuee will not know them. Even in real life there are many cases of unintentional mushroom poisoning.

`FORAGE_POISON` is meh because that is just generic poisoning which you can not customize. You can not even customize how often poisoning occurs with that flag.
I did not know about `HIDDEN_POISON` however. But all that as a discussion in a feature request please.

**Pull request merged**
