### PR TITLE
Add cattle samples to more ungulates

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
Recently realized we had a bunch of ungulates that didn't give cattle samples when dissected

#### Describe the solution
Add cattle samples to llamas, lambs, sheep (and so goat and goat kids by extension) as well as horse foals (don't start this argument in the comments - cattle is a generic ungulate line, and adult horses already give samples)

Also removed the useless empty anger trigger field from llamas

#### Describe alternatives you've considered
Pigs? They're ungulates. But they feel unique enough in dietary preferences at least if nothing else to warrant not being included in the Cool Cattle Club

### CODE REVIEW

**Comment by IdleSol** [comment]
What I think about it, I've already said.

Add a command to close the topic #73679 if this change is merged. As an automatic resolution to the dispute.

**Comment by Maleclypse** [comment]
These are all singles?  
```
{
    "id": "dissect_cattle_sample_single",
    "type": "harvest",
    "message": "With cuts and pulls equally similar to both extraction and vandalism, you scrape together the most important parts of the creature.",
    "entries": [ { "drop": "cattle_sample_single", "type": "mutagen_group" } ]
  },
  {
    "id": "dissect_cattle_sample_small",
    "type": "harvest",
    "message": "With cuts and pulls equally similar to both extraction and vandalism, you scrape together the most important parts of the creature.",
    "entries": [ { "drop": "cattle_sample_small", "type": "mutagen_group" } ]
  },
  {
    "id": "dissect_cattle_sample_large",
    "type": "harvest",
    "message": "With cuts and pulls equally similar to both extraction and vandalism, you scrape together the most important parts of the creature.",
    "entries": [ { "drop": "cattle_sample_large", "type": "mutagen_group" } ]
  },
  {
    "id": "dissect_cattle_sample_huge",
    "type": "harvest",
    "message": "With cuts and pulls equally similar to both extraction and vandalism, you scrape together the most important parts of the creature.",
    "entries": [ { "drop": "cattle_sample_huge", "type": "mutagen_group" } ]
  },
``` Llama seems like it would at least be large?

**Comment by Karol1223** [comment]
> Pigs and boars should drop beast samples IMO

That was my first thought as well but I don't wanna be the one to pull the trigger on this decision in particular tbh

> Llama seems like it would at least be large?

I could increase it but I think after all this time we're still missing guidelines of how many samples should be given for which monster weight category, so I typically just throw in singles as a safety measure.

**Comment by Karol1223** [comment]
> We're not going by taxonomy

You quoted this yourself, and continue to argue that we should care about taxonomy. We do not. Our samples and mutations aren't genetics-based, they're phenotype-based. Taxonomy does not matter. Stop repeating yourself all the time.

**Comment by IdleSol** [comment]
Then use the correct words. Not a cow sample, but an ungulate sample.

**Comment by Karol1223** [comment]
> Then use the correct words. Not a cow sample, but an ungulate sample.

Then we'd have you arguing that since it's an ungulate sample, all ungulates should be included like pigs. No, it's trading one problem for another, and I have no interest in discussing this further.

**Comment by fairyarmadillo** [comment]
> Then use the correct words. Not a cow sample, but an ungulate sample.

It's not a cow sample, it's a cattle sample. Cattle in English can refer both to cows and to any large hoofed animal of the sort raised on farms. I recall that your primary language is not English, so it is possible that the translation you are working with is inaccurate and could be updated.

> (https://www.merriam-webster.com/thesaurus/cattle)
> 1
> : domesticated quadrupeds held as property or raised for use
> specifically : bovine animals on a farm or ranch

Cattle is not a scientific term and its usage is somewhat loose - it can sometimes mean specifically a cow such as you get beef from, or it can mean any animal owned for farming. It's even been used to refer to people in some cases.

Ungulate is a broader term, but may be less appropriate as it literally just means an animal with hooves. But not all ungulates are cattle - for instance, rhinoceros and elephants are not cattle. Cattle is also what the mutation line has been called since it was added to the game many years ago, and changing it is probably beyond what Karol is trying to do here.

**Comment by Karol1223** [comment]
> Cattle is also what the mutation line has been called since it was added to the game many years ago, and changing it is probably beyond what Karol is trying to do here.

I am pro-changing some mutation lines but there's no ideal solution. 

Again, "insect" includes myriapods. "Cattle" includes basically all grazing ungulates (with exceptions like Rhinos, so it's even more convoluted). My personal nemesis is Lupine (there's 0 reason for it to not just be Canine)

But you're right in that it is way beyond the scope of what I want to do.

**Comment by Karol1223** [comment]
@Maleclypse I looked at some other definitions and most ungulates use singles. I would like a full review of how many samples we end up giving per bodymass kg in the future but for now I'd like to keep them all as singles since I don't want to replace one asspull with another.

**Comment by Maleclypse** [comment]
> @Maleclypse I looked at some other definitions and most ungulates use singles. I would like a full review of how many samples we end up giving per bodymass kg in the future but for now I'd like to keep them all as singles since I don't want to replace one asspull with another.

Fair due.  Let me know if you need any help with deciding what sample groups should belong to what size.

**Pull request merged**
