### PR TITLE
Obsolete Dark Skies Above

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Mods "Obsolete Dark Skies Above"

#### Purpose of change
Remove Dark Skies Above as an in-repo mod. It has not had any standalone content updates in over a year, only unrelated bugfixes designed for the main repository. The creator has not been active since 2021, and no one of which I know is working on it at this time. I find that it adds additional time to bugfixes in development and content releases which could be saved.

#### Describe the solution
The entire directory of the mod has been deleted.

#### Describe alternatives you've considered
Leaving it as is, moving it into the obsoletion folder, or moving the mod out of the repo to a different repository.

#### Testing
None needed, everything was self-contained inside the mod folder.

#### Additional context
If someone is working on new content for the mod, please let me know. Additionally, I have created a storage repository for the current version of the mod here: https://github.com/MNG-cataclysm/Dark-Skies-Above-Cold-Storage-

Currently, I have made the mod obsolete in modinfo.json. I'm not deleting it right now.

### CODE REVIEW

**Comment by Maleclypse** [comment]
No, this isn't how this is handled.  You would need to set `"obsolete": true` in modinfo for an entire stable.  Then if it gains no maintainer in that time it could be deleted in the next experimental cycle but probably wouldn't be.  Straight deleting it now will cause problems and prevent a possible maintainer from appearing.

**Comment by LyleSY** [comment]
@ephemeralstoryteller any thoughts on this or words of wisdom to those who may be interested in taking this up? Thanks for making a fun thing either way.

**Comment by MNG-cataclysm** [comment]
> No, this isn't how this is handled. You would need to set `"obsolete": true` in modinfo for an entire stable. Then if it gains no maintainer in that time it could be deleted in the next experimental cycle but probably wouldn't be. Straight deleting it now will cause problems and prevent a possible maintainer from appearing.

I've just made it obsolete in the mod info for now, according to this recommendation.
However, the project has been lying open for over a year, nearly for the entire experimental cycle from 0.F to 0.G. The developers have asked around a few times for a maintainer, but no one has picked it up.  I think someone would have taken the role by now.

**Comment by MNG-cataclysm** [comment]
I'm sorry about that, that makes sense.

**Comment by Maleclypse** [comment]
> I'm sorry about that, that makes sense.

It’s ok I should have used the actual words “this will break saves and promises” :)

**Comment by ephemeralstoryteller** [comment]
> @ephemeralstoryteller any thoughts on this or words of wisdom to those who may be interested in taking this up? Thanks for making a fun thing either way.

First and foremost: Sorry for inactivity. *gestures broadly*. Adulting, yknow? I have a few half-finished files that I haven't touched in over a month, bouncing around but not making good progress towards a commit. wish I had more time and energy to put towards this project. I've sort of just been in denial about ever coming back to this, and probably confusing a lot of people who have been trying to load every mod in the list along the way to this day lol.

I bit off more than I could chew all things considered, and it shows - I really needed to assemble a team for this sorta thing first to really make it work, given the sort of features a competent-seeming alien invasion was going to need. 

I hope it was at least fun to look at and think about for those who joined me.

**Review by LyleSY — APPROVED** [review]

**Comment by Maleclypse** [comment]
> > @ephemeralstoryteller any thoughts on this or words of wisdom to those who may be interested in taking this up? Thanks for making a fun thing either way.
> 
> First and foremost: Sorry for inactivity. _gestures broadly_. Adulting, yknow? I have a few half-finished files that I haven't touched in over a month, bouncing around but not making good progress towards a commit. wish I had more time and energy to put towards this project. I've sort of just been in denial about ever coming back to this, and probably confusing a lot of people who have been trying to load every mod in the list along the way to this day lol.
> 
> I bit off more than I could chew all things considered, and it shows - I really needed to assemble a team for this sorta thing first to really make it work, given the sort of features a competent-seeming alien invasion was going to need.
> 
> I hope it was at least fun to look at and think about for those who joined me.

I hope that even if you decide this mod is too much for you that you continue contributing as life and your own joy brings you to it. You have a gift and thank you for choosing to make the apocalypse in your mind one that’s associated with Cataclysm.

**Comment by ephemeralstoryteller** [comment]
I will say that I do have this like... quiet hankering in me to make some sort of TC? If I may pour my heart out for a second: I really love Cataclysm, I really love how involved its systems are, and how that generates both tension and storytelling. While perhaps not the woman for a solo-developed alien TC, one day bringing something like a Warhammer Fantasy type would be much more feasible given that magic (and Chaos ;p) is a very flexible medium to explain certain discrepancies and gameplay decisions. ;p

If I were to do so, though, I think I'd want to bring something that's much better finished to the table before making a commit, and asking for a lot of help along the way so I can present a functional, if not totally fleshed out, game using the Cataclysm engine. Nothing anytime soon, but. Maybe one day when I'm more settled in life! 

'til then, take care! Now, feel free to message/ping me on Discord if you need new monsters. If nothing else, I hope the prose  in their descriptions was enjoyable, hah.

**Comment by MNG-cataclysm** [comment]
@ephemeralstoryteller If you ever want to access the files again, I have a copy of them stored here: https://github.com/MNG-cataclysm/Dark-Skies-Above-Cold-Storage-, should they be needed. 

Did you have anyone particular in mind as a new developer for Dark Skies Above? If so, we could try and get the ball rolling again.

**Comment by ephemeralstoryteller** [comment]
> @ephemeralstoryteller If you ever want to access the files again, I have a copy of them stored here: https://github.com/MNG-cataclysm/Dark-Skies-Above-Cold-Storage-, should they be needed.
> 
> Did you have anyone particular in mind as a new developer for Dark Skies Above? If so, we could try and get the ball rolling again.

I wish I could be of more help, but I've drifted from the community (out of no malice or dislike so much as time and energy) so I don't have a good recommendation. At this point, any wishing to bear the mantle are free to it.

**Comment by Zlorthishen** [comment]
lol

**Comment by Raiph-Benesz** [comment]
May I please keep a tab on Dark Skies Above in order to repurpose it for a new Alberta region mod?

**Comment by MNG-cataclysm** [comment]
> May I please keep a tab on Dark Skies Above in order to repurpose it for a new Alberta region mod?

https://github.com/MNG-cataclysm/Dark-Skies-Above-Cold-Storage-
Here it is.

**Pull request merged**
