### PR TITLE
Revert "Fix size() accessor in active_item_cache." to avoid crashes

### LINKED ISSUE #36138: SIGSEGV processing items on map
# Describe the bug
Segmentation fault processing some item. I can't determine the specific cause and the reproduction case is not consistent.

# Steps To Reproduce
Steps to reproduce the behavior in the attached save:
1. Continue riding south down the road past the map note then turn east for a few OMTs

# Expected behavior
No segfaults.

# Versions and configuration
 - OS: Arch Linux x86_64 kernel 5.4.3-arch1-1
 - Game Version: RELEASE=1 bindist built from e667aa09a3eccf7464e909c1e3f193fe2188449f with #36096 and #35865 applied
 - Graphics version: Tiles
 - Mods loaded: [ dda, disable npc needs, no rail stations, no fictional guns, no flaming weapons ]

# Additional context
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.C-47852-g8603027fa9
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x39) [0x557e6a3c8939]
    ./cataclysm-tiles(+0x745976) [0x557e6a3a3976]
    ./cataclysm-tiles(+0x7455d8) [0x557e6a3a35d8]
    /usr/lib/libc.so.6(+0x3bfb0) [0x7fe9c6483fb0]
    /usr/lib/libstdc++.so.6(_ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base+0x13) [0x7fe9c684ea93]
    ./cataclysm-tiles(_ZN3map13process_itemsEbPFbR10item_stackR14safe_referenceI4itemERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEf16temperature_flagESG_+0x3a7) [0x557e6a9fda07]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x1467) [0x557e6a56bc27]
    ./cataclysm-tiles(main+0x1a0c) [0x557e6a9b83dc]
    /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fe9c646f153]
    ./cataclysm-tiles(_start+0x2e) [0x557e6a01cdae]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash(char const*, char const*)
    ld-temp.o:?
    signal_handler(int)
    ld-temp.o:?
    ??
    ??:0
    local_Rb_tree_increment
    …/src/c++98/tree.cc:65
    std::_Rb_tree_increment(std::_Rb_tree_node_base*)
    …/src/c++98/tree.cc:85
    map::process_items(bool, bool (*)(item_stack&, safe_reference<item>&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, temperature_flag), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?
```

### PR DESCRIPTION
**Pull request by mark7**
This reverts commit 44a91c2acab89187de2243ce99b2057ac1903206.

#### Summary
SUMMARY: Bugfixes "Stop SIGSEGVs in get_nonant"

#### Purpose of change
Fixes #36138 - SIGSEGVs in get_nonant showing up periodically in game.  44a91c2 on PR #36025 introduced a crash that sporadically shows up in the game.  It does not appear to be critical to have in for the game functioning.  Back that commit out.  @kevingranade may want to push in a modified version of that patch.  Also back out the commit for the associated unit test for which 44a91c2 was a fix, 1a4c39b1820c10418d411d203fad7304df504b7d, so as to keep CI tests passing.

#### Testing
Briefly ran the game using the repro case provided by @HarleyLorenzo on #36138 and the crash no longer manifested itself.

### CODE REVIEW

**Comment by Zireael07** [comment]
Why did you revert the test?

**Comment by mark7** [comment]
> Why did you revert the test?

44a91c2 was something that the test relies on; without it, there'll be CI failures cluttering up other people's patches.

**Comment by mark7** [comment]
Just to clarify -- my wording in the PR description was confusing -- the test wasn't present and failing and then fixed in 44a912.  A week back, 44a91c2 was pushed, and then 1a4c39b, the test in that ensures that there are no regressions to its functionality.  My PR here reverts the test and then the patch that it tests.

If 44a91c2 is pushed and 1a4c39b left in, that test will keep showing a failure on each PR that someone pushes henceforth; one more thing to dig through in every patch.

I can get someone wanting to remember to look into that issue, but I'd suggest that the place to track it would be on the issue tracker, and not as failing regression test.

**Comment by ralreegorganon** [comment]
@mark7 Have you taken a look at if <https://github.com/CleverRaven/Cataclysm-DDA/pull/36025#pullrequestreview-334246687> resolves the issue, keeping the changes and test in place?

**Comment by mark7** [comment]
Nah.  I'm not looking to get into fixing the crash-causing patch itself -- if someone else wants to push a PR to fix it, though, that'd be great.  My aim is just "get game back to a non-crashing state".

**Comment by Qrox** [comment]
Just curious: why would the changes in #36025 cause a crash? It only seems to be checking the emptiness of containers, so I don't see why would it crash.

**Comment by mark7** [comment]
@Qrox has a fix for #36025 over in #36250.  Dropping this PR in favor of his.

**Pull request closed without merging**
