### PR TITLE
Automate translation template push

### LINKED ISSUE #18796: Automate the translation pot update
So that issue like #18657 could be spot earlier and make translation up to date.

If possbile, could someone setup the jerkins bot to also upload new translation pot to transifex?

http://docs.transifex.com/integrations/jenkins/
http://docs.transifex.com/integrations/github/

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
SUMMARY: I18N "Automate translation template push"

#### Purpose of change
Fix #18796.

#### Describe the solution
Add a GitHub Action workflow to generate a new translation template and push it to Transifex remote whenever a new PR is merged into `master` branch.

#### Describe alternatives you've considered
Tried to do this in Travis CI, but I am very confused about their documentation and failed to configure it despite two hours of trial-and-errors.

#### Testing
I tested this in my own fork repo. When pushing a new commit to `master` branch, the workflow will be triggered and do the task.

#### Additional context
* For this to work, I need to put my Transifex API token into the _secrets_ of this repo but I don't have the permission to do so.

* I removed translation template from Git because I believe it is redundant. That file can always be re-constructed by `lang/update_pot.sh` from game content.

* The next step can be automatically pulling latest translations from Transifex when making experimental builds. If that is realised, it will be great for players and translators. Players can play with latest translations without needing to wait for my weekly manual updates. Translators can see their work in game within the magnitude of hours and can adjust translations as soon as they find it inappropriate in the context. But I have no idea how to achieve this since experimental versions are currently built on Jenkins.

### CODE REVIEW

**Comment by BrettDong** [comment]
Q: Why do you remove the translation template `lang/po/cataclysm-dda.pot` from Git repo?

A: I think that file is redundant information. It can always be re-constructed by `lang/update_pot.sh` from game content. I believe there is no point of keeping it in Git repo so I removed it in this PR.

**Comment by ZhilkinSerg** [comment]
Was `pot` file changed just to test workflow is working?

**Comment by BrettDong** [comment]
> Was pot file changed just to test workflow is working?

It is no longer used by anybody so I believe it can be removed from Git.

**Comment by Qrox** [comment]
`compile_mo.sh` uses the `.pot` file to compile the English `.mo` which is needed to workaround a libintl bug on MinGW targets, and removing the `.pot` file broke the script. I guess we should either restore the `.pot` file or change the script to automatically generate the file or fetch it from Transifex.

**Comment by BrettDong** [comment]
> `compile_mo.sh` uses the `.pot` file to compile the English `.mo` which is needed to workaround a libintl bug on MinGW targets, and removing the `.pot` file broke the script. I guess we should either restore the `.pot` file or change the script to automatically generate the file or fetch it from Transifex.

POT file can be re-constructed by Lang/update_pot.sh

**Comment by Qrox** [comment]
Yeah I know that, but `update_pot.sh` is slow so I think the two other approaches are also worth considering.

**Comment by BrettDong** [comment]
My suggestion is to generate it when needed. Generating it takes only 3-5 seconds, but pulling from Transifex can take a minute.

**Comment by Qrox** [comment]
Well, it takes minutes for me to generate it on my laptop...

**Comment by BrettDong** [comment]
On macOS, even without `lang/po/cataclysm-dda.pot`, despite there is a line of error saying cannot find that translation template, English `.mo` file is still produced, and the game is playable without a problem in English language:
```
[brett] ~/Cataclysm-DDA [master] ?? % rm -rf lang/po/cataclysm-dda.pot lang/mo
[brett] ~/Cataclysm-DDA [master] ?? % lang/compile_mo.sh all
msgen: error while opening "lang/po/cataclysm-dda.pot" for reading: No such file or directory
[brett] ~/Cataclysm-DDA [master] ?? % ls lang/mo    
ar	de	es_AR	hu	it_IT	nb	pt_BR	tr	zh_TW
cs	el	es_ES	id	ja	nl	ru	uk_UA
da	en	fr	is	ko	pl	sr	zh_CN
[brett] ~/Cataclysm-DDA [master] ?? % ls -la lang/mo/en/LC_MESSAGES/cataclysm-dda.mo
-rw-r--r--  1 brett  staff  7711157 12 19 23:31 lang/mo/en/LC_MESSAGES/cataclysm-dda.mo
```
Is it behaving differently on MinGW on Windows?

**Comment by Qrox** [comment]
The English `.mo` file has to contain the text from the `.pot` file to workaround a `libintl` caching bug. Otherwise the game is indeed playable, but translation calls may slow down due to the caching bug.

**Comment by BrettDong** [comment]
I am against tracking `lang/po/cataclysm-dda.pot` in git because it is redundant information (it can always be precisely reconstructed by `lang/update_pot.sh` from game content) and it has been taking a lot of space:
```
[brett] ~/Cataclysm-DDA [master] ?? % git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | grep cataclysm-dda\.pot
# too many lines...
6954c5dbdd3d  6.3MiB lang/po/cataclysm-dda.pot
556c23a6cb35  6.3MiB lang/po/cataclysm-dda.pot
700adfbb30f3  6.4MiB lang/po/cataclysm-dda.pot
b25f43d586ee  6.4MiB lang/po/cataclysm-dda.pot
46fd2bb235a5  6.4MiB lang/po/cataclysm-dda.pot
9ab0e1ce3591  6.4MiB lang/po/cataclysm-dda.pot
6b4405169602  6.5MiB lang/po/cataclysm-dda.pot
dc350ea9dbad  6.5MiB lang/po/cataclysm-dda.pot
b778d0c06c38  6.5MiB lang/po/cataclysm-dda.pot
be042baa674b  6.5MiB lang/po/cataclysm-dda.pot
b217083f0dc9  6.6MiB lang/po/cataclysm-dda.pot
447587df880b  6.6MiB lang/po/cataclysm-dda.pot
ee864e8cb44e  6.7MiB lang/po/cataclysm-dda.pot
b0b55284a952  6.7MiB lang/po/cataclysm-dda.pot
```
So in my personal opinion, if you really need `lang/po/cataclysm-dda.pot`, generating from `lang/update_pot.sh` is the best solution. Generating it locally on your machine gives the matching version of the translation template with the commit your HEAD is pointing at. Pulling it from Transifex may not match your local game content since the translation template on Transifex is always tracking the latest `master` branch on GitHub.

Costing minutes to run `lang/update_pot.sh` is definitely abnormal. My old laptop has an ultra-low voltage Core i5 back in 2015 and it just takes 4.5 seconds to run the script. I feel it is a problem with MinGW, or Windows file system.
```
[brett] ~/Cataclysm-DDA [master] ?? % /usr/bin/time lang/update_pot.sh
        4.45 real         3.14 user         1.04 sys
```

**Pull request merged**
