### PR TITLE
Added Urban Development Mod

### PR DESCRIPTION
**Pull request by acidia**
This is the first step to implementing the urban development concept #21488.  I've broken the buildings into 5 parts each containing 10 buildings.  

This only contains houses designed based on traditional suburban styles.

Forum thread: http://smf.cataclysmdda.com/index.php?topic=14812.0

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Looks good to me from the jsons, though I didn't check everything.

It's a bit hard to see from the jsons, but are you aligning stairs on connected z-levels? That is, connected stairs having same x/y coords.
At the moment it isn't strictly required, but some time in the future it will be.

Jenkins is complaining about un-linted modinfo.json

**Comment by acidia** [comment]
I'd lose my mind on larger buildings if I didn't make it a habit of aligning stairs.

Strange about the linting, I put all the files in the browser linter but I think only the building and over map terrain had templates.  Unless it was a copy/paste error.

**Comment by BorkBorkGoesTheCode** [comment]
Hmm. From http://gorgon.narc.ro:8080/job/Cataclysm-PR-Builder/1041/console

```
21:33:19 Linting data/mods/Urban_Development/modinfo.json
21:33:19 ERROR: Format error at line 1
21:33:19 < [
21:33:19 > [
21:33:19 
21:33:19 HINT: Canonical output for this block was:
21:33:19 [
21:33:19   {
21:33:19     "type": "MOD_INFO",
21:33:19     "ident": "Urban_Development",
21:33:19     "name": "Urban Development",
21:33:19     "authors": [ "acidia" ],
21:33:19     "description": "Holder for suburban and urban buildings.",
21:33:19     "category": "buildings",
21:33:19     "dependencies": [ "dda" ]
21:33:19 Makefile:946: recipe for target 'obj/lint.cache' failed
21:33:19 make: *** [obj/lint.cache] Error 65
21:33:19 Build step 'Conditional step (single)' marked build as failure
21:33:19 Setting status of abaccc9eecc810f46e753f3643902a7fc777964a to FAILURE with url http://gorgon.narc.ro:8080/job/Cataclysm-PR-Builder/1041/ and message: 'Build finished. '
21:33:19 Using context: gorgon-ghprb
21:33:20 Finished: FAILURE
```

**Comment by acidia** [comment]
Sooo, not exactly sure how to fix it or what is wrong with the linting?

**Comment by Zireael07** [comment]
@acidia: The only thing I can think of is some sort of invisible characters messing with you.

**Comment by acidia** [comment]
Copy and pasted the modinfo from a different mod and rewrote the description but it still kicks the same error at line 1.

**Comment by kevingranade** [comment]
It's complaining about a windows-style newline.
```
hexdump -C data/mods/Urban_Development/modinfo.json
00000000  5b 0d 0a 20 20 7b 0d 0a  20 20 20 20 22 74 79 70  |[..  {..    "typ|
```
the "0d 0a" part is a windows-style newline.

**Comment by acidia** [comment]
Any tips on how to fix it from an android phone?  I'm just copy and pasting from the browser linter so its automatically converted.

**Comment by ZhilkinSerg** [comment]
> Any tips on how to fix it from an android phone? I'm just copy and pasting from the browser linter so its automatically converted.

I've attached version with converted newlines if it helps: [modinfo.json.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/1210677/modinfo.json.txt). Just remove `.txt` extension.

**Comment by acidia** [comment]
That's crazy... all other json files were handled the same way but none of them threw an error.  Must be an omission in the linter or modinfo template to cause it?

**Comment by codemime** [comment]
These JSON files cause an issue to my git (and, most likely, to everyone else's on Unix/Linux machines). It shows that the files has been changed no matter what I do. The difference is (as @kevingranade pointed out) line endings: they're `CRLF` for these files and `LF` for all the rest. I suspect they were committed on a Windows machine with `"core.autocrlf"` set to `"false"`.

**Comment by AlecWhite** [comment]
@codemime I'm using Windows and I have the same problem using MINGW64 bash thingy, and given that I'm closing on 20 hours without sleep, thought I was slowly going crazy.

**Pull request merged**
