### PR TITLE
Fix bird egg sizes

### PR DESCRIPTION
**Pull request by RocketPapaya413**
#### Summary
```SUMMARY: Balance "Makes chicken eggs appropriately sized and slightly heavier"```

#### Purpose of change
Chicken eggs are currently described in the code as:
```
"weight": 50,
~
"volume": "62 ml"
"stack_size": 4
```
However since stack_size serves as a divisor to volume that means that each individual chicken egg has an in-game volume of .0155L

tinyegg

The USDA defines egg sizes in terms of ounces per dozen, 24 ounces per dozen large eggs gives 2 oz (57 g) on average per egg. The volume is variable and harder to pin down but [Sauder's Eggs](https://www.saudereggs.com/blog/egg-sizing-guide/) and [Gourmet Sleuth](https://www.gourmetsleuth.com/articles/detail/leftover-egg-whites) give 3.25 tbs (48 ml) liquid volume per egg. Add a tiny bit for the shell and round up to a nice even number and I came out to 50 ml.

I don't have a specific source on "large" eggs being the default size in American recipes but it's very common knowledge. Check your nearest cookbook and I'm sure it will confirm.

I checked the other bird eggs - duck, goose, and turkey eggs all specify particular weights and volumes - and they seemed appropriate as they all already had a stack_size of 1.

#### Describe the solution
```
"weight": 57,
~
"volume": "50 ml"
"stack_size": 1
```

Changing 4 characters across 3 lines of text and this urgent matter is put to rest.

#### Describe alternatives you've considered
Any other particular arbitrary size is probably valid but I think some degree of consistency with real-world recipes is desirable.

If someone wanted they could go in and add a degree of randomization to the volume, weight, and calorie level of organically spawned food items (farming overhaul perhaps?) but that would be beyond me.

#### Additional context
goodegg
All is finally right with the world once again.

### CODE REVIEW

**Comment by RocketPapaya413** [comment]
You know what actually the price was bothering me. I figure these are nice, happy eggs so I based them off the fancy brand.

fancyeggs

**Comment by FulcrumA** [comment]
Your screen shows an egg worth $2.50, your image afterwards shows relatively expensive brand, package of 12 eggs worth $5.24. So similar package of ingame eggs would be worth $30.00. That doesn't seem "right with the world" to me. Am I missing something?

Also, adjusting the size of eggs should probably also include a check on whether their nutritional qualities as fine in various foods. Now that eggs differ considerably from others, we need some mechanics requiring various quantities of various sized eggs to create meals.

**Comment by RocketPapaya413** [comment]
Sorry, that was a lack of clarity on my part, I posted that image then changed the prices. I'll update the OP image.

And as far as I understand the nutrition inheritance system should handle that automatically and for the record I didn't change anything in terms of some eggs differing from each other.

**Comment by bhel08** [comment]
2b383a4

**Pull request merged**
