### PR TITLE
Added significant stab thrown damage to combat knife and RM42 knife

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Balance "Added significant stab thrown damage to combat knife and RM42 knife."```

#### Purpose of change
Make combat knife and RM42 knife decent throwing weapons.

I did some testing, and it seems that throwing all knives (except for _the_ throwing knife) is almost useless. Maximum damage I was able to inflict to ordinary zombie after throwing 40 combat knives at distance 5 with level 3 throwing and standard 8-8-8-8 character is miserable 8 points.

#### Describe the solution
Added `thrown_damage` field to combat knife and RM42 knife. I used 14 points of `thrown_damage` of _the_ throwing knife as a reference point, as it is a specifically designed throwing weapon. As such, no knife has throwing damage higher than 14.

After the change average throwing damage with the same conditions (40 throws) for combat knife was increased from 3.75 to 15.9.

Also I changed damage type of throwing damage for throwing knife from cutting to stabbing, but in my further testing I didn't see any significant change in average damage output. 
Also changed its "ordinary" damage from cutting to stabbing as ts description specifically states that it has a dull cutting edge.
Also made throwing knife sheathable and durable.

### CODE REVIEW

**Comment by shadowsapex** [comment]
You can't throw kitchen knives. Most knives are terrible for throwing. I don't think we need any buffs to knife throwing in the game

**Comment by Moonsabrt** [comment]
You can't throw kitchen knives. Most knives are terrible for throwing. I don't think we need any buffs to knife throwing in the game
Terrible for throwing...Probably true, but expertise should at least come through in making that kitchen knife into a better projectile.

**Comment by kevingranade** [comment]
After a quick look over the updated knives, only the combat knife and rm42 stand out as deserving this update, everything else would be unusable as a throwing knife.

Except I'm not familliar with the kirpan.

**Comment by Night-Pryanik** [comment]
> You can't throw kitchen knives. 

>everything else would be unusable as a throwing knife.

Why? I've successfully thrown kitchen knives myself. If you don't believe me, there are LOTS of proofs that throwing kitchen knives (and most other types of knives too) is possible. Check out [this](https://www.youtube.com/watch?v=yUA7S7ueLs8), [this](https://www.youtube.com/watch?v=zz3vSX-mUZY) or [this](https://www.youtube.com/watch?v=YfA1Q4sK4y0) video, for example.
Results of throwing kitchen knives can vary, of course, but it's absolutely possible, and it could be deadly (especially at closer distance). In fact, you can successfully throw almost everything.
https://www.quora.com/What-normal-knives-can-also-be-used-as-throwing-knives

**Comment by kevingranade** [comment]
What your videos indicate is that you can throw random things at barely past arms length and get a minuscule amount of penetration.  The fact that you can force a pair of pliers to stick in soft enough wood should be telling you that "can make it stick in soft wood at barely beyond arms length" is not a good criteria for "is this a reasonable thing to use as a throwing weapon".

The problems with using crappy knives appear at longer distances where the knife has time to twist and tumble, eliminating any chance you had of reliable penetration. Meanwhile, your steak knife isn't going to penetrate deeply enough to matter even at close range because it simply doesn't have enough momentum to do so.  Meanwhile your heavier but still not full tang knives are going to break their handles from impact shock.

**Comment by Night-Pryanik** [comment]
Ok, I'll remove throwing damage from kitchen knives. But there are other not-crappy knives that are used as tools and/or for warfare, heavy enough to inflict enough damage and sturdy enough not to break, such as tanto, kris, rambo and hunting knives. What about them?

**Comment by kevingranade** [comment]
I already addressed those. If the balance is wrong they're going to start tumbling after you throw them and they're not going to reliably stick.

If you want to add a feature where a poorly balanced Throne blade is reliable outfit to just two tiles or so and after that tumbles and is unlikely to stick go ahead but with the current system adding a thrown damage to these is an incredibly reliable source of damage at any range.

**Comment by Night-Pryanik** [comment]
Following your reasoning, I should delete throwing damage even from combat knife and rm42 knife, as they both are most probably not balanced to be successfully used as a thrown weapon.

**Comment by Moonsabrt** [comment]
> Following your reasoning, I should delete throwing damage even from combat knife and rm42 knife, as they both are most probably not balanced to be successfully used as a thrown weapon.

Mate just let what he said go through 'w')/
Kevin is the 'admin' and he has the word for what is pulled in and isn't.

**Comment by Night-Pryanik** [comment]
I know that, mate, but we're discussing things here, and even an admin could change his opinion as a result of discussions like this.

**Comment by kevingranade** [comment]
Combat knife balance and construction is conducive to throwing.

**Comment by Firestorm01X2** [comment]
Scarred battle hardened commandos arguing about throwing  various knives  including fictional ones.

**Pull request merged**
