### PR TITLE
Add space for easy translation

### PR DESCRIPTION
**Pull request by GeekDuanLian**
#### Summary
I18N "Add space for easy translation"

#### Purpose of change
Because some languages ​​such as Chinese do not need spaces to separate, so you can delete the spaces when translating.

#### Describe the solution
Add space.

#### Describe alternatives you've considered
Don't Add space.

#### Testing
Will CI automatically compile for me? After compiling, I will test it.

#### Additional context
None.

### CODE REVIEW

**Comment by GeekDuanLian** [comment]
Why does compilation fail?

**Comment by GeekDuanLian** [comment]
@NetSysFire
Doesn't CI compile the windows version? I plan to run the result of his compilation, but I didn't see the artifact he uploaded for windows.

**Comment by NetSysFire** [comment]
The windows job is at https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3656786573/jobs/6179629028

**Comment by GeekDuanLian** [comment]
Yes, but it does not upload the compiled executable file artifact. I don't have the environment to compile it myself.

**Comment by NetSysFire** [comment]
Weird. No idea why it does so, I dont know much about how the builds work.

**Comment by GeekDuanLian** [comment]
😢

**Comment by Maleclypse** [comment]
> 😢

Passed all checks now.

**Comment by GeekDuanLian** [comment]
> > 😢
> 
> Passed all checks now.

But CI still hasn't uploaded the executable file artifact. I want to download CI compiled executables to actually run the game for testing purposes.

**Comment by BrettDong** [comment]
CI builds on pull requests do not upload artefacts.

**Comment by GeekDuanLian** [comment]
I will delve into how to compile and debug online using only github's CI and web editor. I hope this can help people to modify and test without installing a compilation environment.

**Comment by Zireael07** [comment]
@GeekDuanLian Just FYI, Github's web editor isn't the best, and using the CI to compile is frowned upon in many projects as a drain on resources. Not sure what Cata's stance on this is, though

**Comment by GeekDuanLian** [comment]
> @GeekDuanLian Just FYI, Github's web editor isn't the best, and using the CI to compile is frowned upon in many projects as a drain on resources. Not sure what Cata's stance on this is, though

Press the `.` key in the repository to open the web version of the `Visual Studio Code` editor. The experience is very good.

Cata only uses Github's CI, and the resources used after fork are in its own account, and CI is free for public repositories. It just so happens that the repositories just forked are public by default.

**Comment by Zireael07** [comment]
@GeekDuanLian I thought VS Code was only for selected repos?

When I said "a drain on resources" I didn't mean files or money. I mean every CI runs on some cloud machine, and with some less experienced contributors you can get many runs and many commits before their PR is mergeable.
This runs the risk of GH deciding free CI isn't worth it (it's already happened in other hosts) because it can be abused (I know there were cases of people forking random repos and using CI for bitcoins...)

**Comment by GeekDuanLian** [comment]
> @GeekDuanLian I thought VS Code was only for selected repos?
> 
> When I said "a drain on resources" I didn't mean files or money. I mean every CI runs on some cloud machine, and with some less experienced contributors you can get many runs and many commits before their PR is mergeable. This runs the risk of GH deciding free CI isn't worth it (it's already happened in other hosts) because it can be abused (I know there were cases of people forking random repos and using CI for bitcoins...)

VS Code can be used with all repositories, even private ones, because this runs on the user's browser, not the cloud, and all operations are performed by the user's browser.

The abuse of CI is their own business. If the user submits malicious code, it will not occupy the resources of the official repository, because it runs in the user's own account, not the automatic CI of the official PR.

**Comment by Zireael07** [comment]
> because it runs in the user's own account, not the automatic CI of the official PR.

Gotcha! In this case it should be fine with the main repo. <3

**Pull request closed without merging**
