### PR TITLE
fix pixel minimap height with toggle

### LINKED ISSUE #28812: Minimap crash
**Describe the bug**  
There is no minimap in my loaded game. Hitting 'N' to bring up the minimap results in a crash.

**To Reproduce**  
- Load a game.
- Observe an empty space where the minimap used to be.
- Hit 'N'.

**Expected behavior**  
Minimap to be on by default. Working 'N' toggle.

**Versions and configuration(please complete the following information):**
 - OS: Win 8.1 x64
 - Game Version: 8628
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Disable Npc Needs, Disable Religious Texts, Prevent Zombie Revivication, StatsThroughSkills

**Screenshot**
Untitled

**Additional context**  
This is a very recent regression. 8623 worked fine.

```
CRASH LOG FILE: config/crash.log
VERSION: 0.D-673-g353ca4b
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x555AF5[cataclysm-tiles.exe+0x155AF5]
    @0x5566A2[cataclysm-tiles.exe+0x1566A2]
    SMPEG_error+0x4B034@0xE2C8C0[cataclysm-tiles.exe+0xA2C8C0]
    _C_specific_handler+0x96@0x7FFBD33A1E26[ntdll.dll+0x81E26]
    _chkstk+0x9D@0x7FFBD33B349D[ntdll.dll+0x9349D]
    RtlRaiseException+0xF67@0x7FFBD33748D7[ntdll.dll+0x548D7]
    KiUserExceptionDispatcher+0x3A@0x7FFBD33B262A[ntdll.dll+0x9262A]
    @0xC628B3[cataclysm-tiles.exe+0x8628B3]
    @0x63562E[cataclysm-tiles.exe+0x23562E]
    @0x69FB9C[cataclysm-tiles.exe+0x29FB9C]
    @0x682EB7[cataclysm-tiles.exe+0x282EB7]
    IMG_LoadWEBP_RW+0x4D6869@0x13F4F99[cataclysm-tiles.exe+0xFF4F99]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x22@0x7FFBD11C13D2[KERNEL32.DLL+0x13D2]
    RtlUserThreadStart+0x34@0x7FFBD33354F4[ntdll.dll+0x154F4]
```

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "fix pixel minimap height with toggle"```
#### Purpose of change

Fixes #28812 (maybe? i can't reproduce the actual crash on my system)
also, setting the pixel minimap height to 0 actually sets it to a correct height. ```N``` actually toggles the pixel minimap, as well.
#### Describe the solution

alter the window_panel::get_height() function a little bit for the pixel minimap, since it's a special case.

### CODE REVIEW

**Comment by KorGgenT** [comment]
i also threw in the minor edit to the rectangle drawn around the overmap minimap in classic

**Comment by Bloodblind** [comment]
Receiving the same segmentation fault as shown in #28825 in latest build.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Receiving the same segmentation fault as shown in #28825 in latest build.

Yeah? And where did you get it if it is still building right now?

**Comment by Bloodblind** [comment]
> > Receiving the same segmentation fault as shown in #28825 in latest build.
> 
> Yeah? And where did you get it if it is still building right now?

Ah, sorry. The changelog showed the fix and I incorrectly assumed it had was included in the current build. I see that the commit is now in place and functioning properly.

**Pull request merged**
