### PR TITLE
sludge crawlers can't dodge

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Sludge crawlers don't have 12 dodge"

#### Purpose of change
Sludge crawlers are a gigantic, slow, refrigerator sized slug. Them having 12 dodge is complete nonsense, they cannot dodge. Every other mollusk has 0 dodge skill.

#### Describe the solution
Give them zero dodge.

#### Describe alternatives you've considered
These enemies regenerating 50 hp per turn basically doesn't make sense in any conceivable reality, but the Blob has mutated things beyond our own conceivable reality and it's a decent enough gimmick for an enemy, even though from a realism/verisimilitude standpoint it's rather ludicrous. So I'm not touching their absurd regeneration speed, as it can be handwaved away with blob magic. But, no amount of blob magic will make a giant slow slug literally the most acrobatic monster in the game (the only enemy I've found with more dodge than them are kittens). Their impossibly high dodge values were why they were basically unkillable in melee.

#### Additional context
I'm not salty at all. Where did you get that idea?

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Seems WAI https://github.com/CleverRaven/Cataclysm-DDA/pull/50439#pullrequestreview-721473029,  https://discourse.cataclysmdda.org/t/are-sludge-crawlers-currently-behaving-as-intended/26779/4

**Comment by anothersimulacrum** [comment]
Or I can read the rest of the linked PR before posting... https://github.com/CleverRaven/Cataclysm-DDA/pull/50439#issuecomment-893171454
> > Are they supposed to have a dodge of 12?
> 
> This is a bit out of scope for this PR, but I'd accept a PR that reduces their dodge and increases their armor.

**Comment by anoobindisguise** [comment]
OK, I gave them extremely high bash armor (since they're basically just a big squishy meatbag), moderate ballistic armor (you need strong bullets that tear chunks off them) and almost no cut armor, so high caliber rifles and sharp weapons will be the best option for killing them.

**Comment by TheShadowFerret** [comment]
>I'm not salty at all. Where did you get that idea?

If you were, the slug would've died on contact🥁

**Comment by Venera3** [comment]
12 bullet armor feels pretty small for wanting to blow chunks off them. Bash+cut looks about right, though I'd add a toke dodge to them to keep the crits down at low levels (and to allow for their weird fluid movements).

**Pull request merged**
