### PR TITLE
JSON-ify rules for climbing down & simplify UX

### PR DESCRIPTION
**Pull request by EvanBalster**
#### Summary
Infrastructure "Add JSON-based system for climbing aids."

#### Purpose of change

After working on #68120 (climbing risk) and #68150 (ledge bumping UX) I began working on a rebalancing contribution for climbing.  I started to realize that the current C++ implementation of vertical movement is a bit of a mess.  It involves a variety of functions located in different regions of the codebase:  most importantly `iexamine::ledge`, `map::climb_difficulty`, `game::slip_down`, `game::climb_down` and `game::vertical_move`.  The last two functions are a daunting nest of interacting conditions and special cases, and it is apparent that various gameplay features have been broken or inconsistently implemented as a result of this factoring.  I encountered similar difficulties trying to implement new features and balance changes.

The control flow in the current implementation also complicates user experience.  A player could potentially encounter up to four modal dialogs when interacting with a ledge (what to do, use grapple? use webs?, confirm climbing down).

This is a result of breaking a more multifaceted contribution [68190](#68190) into smaller pieces.  That earlier PR incorporates balance changes and a few gameplay additions in addition to the code changes in this contribution.

#### Describe the solution

* Introduce a new JSON type called `climbing_aid`, which represents a tool, ability or environmental feature supporting the player's body as they climb.
  * Overhaul `climb_down` to integrate this new type.
  * [Develop some JSON features](https://github.com/EvanBalster/Cataclysm-DDA/blob/eb-climbing-jsonify/doc/CLIMBING.md) to support future development & balancing of climbing mechanics.
    * `slip_chance_mod` is set to `-1000` for climbing aids that formerly bypassed the check.
    * See the original PR [68190](#68190) which experiments with 11 new climbing aid rules and balance changes.

JSON climbing aids are fully integrated with _climbing down_ mechanics.  Refactoring the code for climbing up will be a separate project.  The following mechanics have been reimplemented as climbing aids in [climbing.json](https://github.com/EvanBalster/Cataclysm-DDA/blob/eb-climbing-jsonify/data/json/climbing.json)

* Default  (ie, lowering your body from a ledge)
* Stepladder in the space below  (gameplay feature added in #68120)
* Grappling hook deployed from inventory
* Web Diver mutation (WEB_RAPPEL player trait)
* Debug tail (WALL_CLING player flag)

In addition, I made some UX improvements based on the above.

* The WALL_CLING mutation is now part of climbing down rather than 
* Integrate climbing aids as options in `iexamine::ledge` to reduce the number of menus.
* Climb safety prompt is skipped under certain conditions (ie, absolutely safe 1-story descent with no impact on items/furniture).
* The climb safety prompt now displays "You should be easily able to climb back up." when considering a one-story descent with a grappling hook.  Previously it could be misleading.

I stripped virtually all gameplay changes out of my earlier PR to produce a "code-only" contribution.  There are some very minor exceptions, though:

* Grappling hooks no longer descend an unlimited distance (this seemed like a bug).
* Grappling hooks are now left attached to the ledge above rather than the floor below when descending with them.
* Multi-story descents are now handled one story at a time, rolling to slip and fall once per story.

#### Describe alternatives you've considered

* **Integrating with EOCs.**  Currently this PR implements "climb conditions" which are specific to climbing aids.  Incorporating with EOCs or at least their logical syntax could be a good direction for further development but at the moment EOCs don't have a mechanism for performing the vertical scan used by climb conditions.  It's out of scope for a first pass.

* **Refactoring the C++ without introducing a JSON type.**  I did this at first, using an enum class for climbing aids.  A fellow contributor suggested JSON conversion and the result seems much nicer. 

* **Integrate with upward climbing.**  This is too much for a single PR.  It will require a new set of JSON fields.  Currently upward climbs can't usually harm the player so I deprioritized work on them.

* **New features & rebalancing.**  I tried some of this in [68190](#68190) but it made the PR too big and multifaceted.  I'll re-introduce those contributions after the new JSON type is in.

* **Repairing features like vines mutation and rope tying.**  Out of scope for similar reasons, but explored in [68190](#68190).

* **Climbing down things we can climb up.**  Out of scope for similar reasons, but explored in [68190](#68190).

#### Testing

- Tested various ledges on a 2-story building.
- Tested with stepladders.
- Tested with downspouts.
- Tested with grappling hook placement.
- Tested with varying levels of stamina, torso encumbrance & weight, and two-handed item wielding.
- Limited testing with web mutations.
- Did _not_ test with `WALL_CLING` which does not appear to be available in the base game.

#### Additional context

image
image

### CODE REVIEW

**Comment by EvanBalster** [comment]
The code changes in this contribution have previously undergone two rounds of review by @ehughsbaird and various discussions in its previous incarnation #68190.  Consequently it is in a near-finished state as I post it.  I'll be following up on a few remaining code review comments and `clang-tidy` issues.

**Comment by Maleclypse** [comment]
Testing results: Spawn in walk to nearest evac shelter, start climbing up and down the "tricky" downspout. Menu is super easy and intuitive, love it.   Around two bars of stamina left fall while climbing down for first time.  Damage to all limbs but not a full bars worth.  Begin failing to climb up around 50% of time at this point.  Teleported to apartment building and found a ladder and climbed up it.  Got on roof and found a skylight.  Walked across skylight no trouble.  Smashed skylight.  Peeked down, worked perfectly.  Jump across, no issue, Selected fall down, prompt works and stepped back from ledge.  Set stamina to various levels and attempted jump over the broken skylight.  Succeeded at jumping over even with only 100 stamina.  That seems off.  Testing pain effect on jumping over square.  Set pain to 90, jumped over no problem.  Set pain to 180, too weak to jump over obstacle.  Fair enough.  Effective strength is down to 2 at this point.

Deployed grappling hook on ground level next to building climbed up using grappling hook.  Couldn't manage to figure out how to use grappling hook to descend or if I was using it when I moved towards it, it was not showing in the menu that I had a climbing aid of any kind.  Wooden stepladder, still at massive pain, slipped once going up, menu showed that stepladder was in the direction I was climbing down, and successful descended.

Testing successful in expected places except for grappling hook climb down.  

Let me know what I've missed testing please.

**Comment by Maleclypse** [comment]
Ah ha, having the grappling hook in wielded brings up the attach grappling hook climbing aid.  Still not sure how to use a grappling hook to climb down that you used to climb up.  will test examine. Examine did not change anything.  Is there a way to reclaim a grappling hook from the floor you've climbed up to?  I can reclaim it from ground zero.

**Comment by EvanBalster** [comment]
> @Maleclypse Jump across, no issue, Selected fall down, prompt works and stepped back from ledge. Set stamina to various levels and attempted jump over the broken skylight. Succeeded at jumping over even with only 100 stamina. That seems off. Testing pain effect on jumping over square. Set pain to 90, jumped over no problem. Set pain to 180, too weak to jump over obstacle. Fair enough. Effective strength is down to 2 at this point.

Out of scope.  I haven't changed the implementation of "jump over" at all, only the UX for picking it.  The code and message text for it could definitely use a pass though ("obstacle" always means a gap, seems like a copy of some now-absent original).  I think it would be an appropriate topic for another PR.

> Deployed grappling hook on ground level next to building climbed up using grappling hook. Couldn't manage to figure out how to use grappling hook to descend or if I was using it when I moved towards it, it was not showing in the menu that I had a climbing aid of any kind. [...]

> Testing successful in expected places except for grappling hook climb down.

> Ah ha, having the grappling hook in wielded brings up the attach grappling hook climbing aid. Still not sure how to use a grappling hook to climb down that you used to climb up.

The grappling hook issue predates this PR:  In the current experimental, grappling hook _furniture_ doesn't help you climb down.  Then item has to be in your inventory.  My previous contribution #68190 addressed that with [this slightly hacky climbing_aid](https://github.com/CleverRaven/Cataclysm-DDA/pull/68190/files#r1335058961), but I rolled that change back along with 11 other "rebalance and expansion" rules when deriving this smaller PR.  I'll be including all of those later in a follow-up to this contribution.

> Is there a way to reclaim a grappling hook from the floor you've climbed up to? I can reclaim it from ground zero.

This is another out-of-scope thing I'd like to fix in a future contribution:  it should be possible to collect a grappling hook and (debatably) a stepladder from the tile above.  I think the tidiest approach would be something like an EXAMINE_BELOW flag that we can apply to furniture.  That would be a completely different PR.

**Comment by Brambor** [comment]
Minor PR style problem: You reference #68190 but it actually links to this issue (#68265), because your links look like this: [68190](https://github.com/CleverRaven/Cataclysm-DDA/pull/68265#68190)

**Pull request merged**
