### PR TITLE
Unhardcode bio recycler, add hunger enchantment

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Unhardcode bio recycler, add hunger enchantment. Fix bio_recycler not affecting calorie usage

#### Describe the solution
Removed hardcoded bio_recycler code, used enchantment instead.  Added hunger modifier enchantment.  Simplified recycler formula to make it work as enchantment, it will now stack with mutations, but there are planned changes to make bionics and mutations harder to use at the same time which should help balance this. Added metabolism enchantment to simulate using less calories

### CODE REVIEW

**Comment by KorGgenT** [comment]
please add this to the markdown file detailing enchantments.

**Comment by KorGgenT** [comment]
that's in MAGIC.md, though i thought it had a bit more information than that, sorry. it just lists it instead.

**Comment by actual-nh** [comment]
BTW - is the recycler supposed to only affect hunger and thirst, and not actual calories (or vitamins, for that matter) available to the body? Thirst is what is keeping track of actually needing water, so that's fine - but hunger isn't keeping track of whether you are actually starving.

**Comment by Ramza13** [comment]
> 
> 
> BTW - is the recycler supposed to only affect hunger and thirst, and not actual calories (or vitamins, for that matter) available to the body? Thirst is what is keeping track of actually needing water, so that's fine - but hunger isn't keeping track of whether you are actually starving.
> 
> EDIT: I see, as I suspected, that the original version didn't affect actual nutrient intake/consumption - I am guessing it was put in prior to hunger and nutrition being separated. I think I would have to call this a bug - sort of the reverse of #47663 - not in your revisions, but in the original.

Good catch, I added a metabolism effect to simulate that.

**Pull request merged**
