### PR TITLE
Fixed translated "HEAD" limb name overlapping head health bar in "labels" panels mode

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: None```

#### Purpose of change
This is just fucking atrocious - making decision of whether we need an extra space after the text based only on the length of limb's name in only one language!

изображение

изображение

#### Describe the solution
Check for length of limb's name, not it's position. If the length is 4, as in `HEAD`, then add an extra space after the text.

### CODE REVIEW

**Comment by KorGgenT** [comment]
hmm, this'll work, but it would actually be cleaner to figure out how long the longest string is, and print the colon there.  this way it'll probably look much better if there's for example a translated name that's less than four letters long, or if all of the translated names are less than 4 letters long. conversely, in that screenshot all of the translated names are 6 letters long except for torso which is 4.

**Comment by Night-Pryanik** [comment]
I agree a more complex solution is needed, but this would suffice as a bugfix for time being.

**Comment by eilaattwood** [comment]
The same approach is required for formatting other translated strings. On that screenshot there is a space missing before speed value, and also I saw missing space before wielded item in Russian translation. That issues are not as annoying as overlapping health bar, but they are still there.

**Comment by Night-Pryanik** [comment]
@eilaattwood these are Russian-translation issues. I already fixed them on Transifex.

**Comment by eilaattwood** [comment]
> 
> 
> @eilaattwood these are Russian-translation issues. I already fixed them on Transifex.

Ah, nice! I actually thought that original issue is translation problem too, but it turned out that it lays deeper :)

**Comment by Night-Pryanik** [comment]
Yeah, that seems to work.

**Pull request merged**
