### PR TITLE
New lower torso items

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Content "Adds new items that cover the lower torso area"

#### Purpose of change
Currently there is a lack of items for use in your lower torso, I assume the waist items could soon be moved to this location, but even then, there are no undergarments for this location. 

#### Describe the solution
Adds a waist or underbust corset, a somewhat smaller version of the current corset but that only occupies the lower torso sub location. The corset have been changed so they can be loosened a little, putting them on the normal layer.
Adds a garter belt, a belly band, a belly band (holster) and more wraps.

#### Describe alternatives you've considered
None.

#### Testing
Spawned the items in the game, and revised their recipes they all seems to work...

#### Additional context

<details>
<summary>Images</summary>

imagen
imagen
imagen
imagen
imagen

</details>

### CODE REVIEW

**Comment by Photoloss** [comment]
> To add some other undergarment that occupies this space? But I can't think of any right now.

The various "wrap" items could be changed from low-coverage full limb to high-coverage sub-location garments. See e.g. the [Sarashi](https://en.wikipedia.org/wiki/Sarashi) or just the general logic of wrapping cloth around pretty much any body part like bandages. A garter belt might also be better suited in the SKINTIGHT lower torso than the "Waist" layer used for tool belts. Other garments include the [Haramaki](https://en.wikipedia.org/wiki/Haramaki_(clothing)) and modern [compression belly wraps](https://www.amazon.com/Postpartum-Section-Bandit-Abdominal-Compression/dp/B07G2XW2TY) which in gameplay terms would just be a corset made of modern fabric (no idea whether lycra or nylon matches better).

**Comment by PatrikLundell** [comment]
I think a lifting belt covers the lower torso, but I would expect it to be on top of the "normal" clothing weight lifters tend to wear. Don't know if it is in the game, though (or whether it would actually help lifting higher weights if so).

**Comment by Termineitor244** [comment]
> The various "wrap" items could be changed from low-coverage full limb to high-coverage sub-location garments.

Just the chestwraps, but this its already done in #52897, the ones on the chest are somewhat lacking in coverage, but in real life they are not meant to cover all the upper torso.

Some ideas:

The waist corset is in the SKINTIGHT layer because the normal corset is too, I could add garter belts, I think they are not in the game right now... 
About the Sarashi, I think I can add one "belly wraps" to the game, I would like to add a "Sarashi" item that covers from the knees to the upper torso, but I'm not sure if it would be accepted. 
I will also see to include the Haramaki as a generic "Bellyband" (its translation to english) made of cotton or lycra/nylon, as well as a bellyband holster since they seem to be a thing.

> I think a lifting belt covers the lower torso, but I would expect it to be on top of the "normal" clothing weight lifters tend to wear. 

Isn't this just a normal belt?

Anyway, thanks for the ideas! I will put the PR as a draft while I work on implementing the items, and I think I will implement a function to adjust the corset (So you can just put it as an undergarment or above clothes if you prefer).

**Comment by PatrikLundell** [comment]
As far as I've seen/figured (never been near one myself) lifting belts essentially cover the area above the hips and below the rib cage and are intended to support the stomach muscles and the back, which is the area I'd consider the lower torso. However, it would be good if someone who actually know how they work could provide some insight.

**Comment by Termineitor244** [comment]
> As far as I've seen/figured (never been near one myself) lifting belts essentially cover the area above the hips and below the rib cage and are intended to support the stomach muscles and the back, which is the area I'd consider the lower torso. However, it would be good if someone who actually know how they work could provide some insight.

Hmmmm sounds very similar in function to a bellyband, I could add it as copy-from of the belly band, maybe with a little more thickness, apart from that, I don't think I can make them help you lift weight haha.

**Comment by Photoloss** [comment]
> Just the chestwraps, but this its already done in #52897, the ones on the chest are somewhat lacking in coverage, but in real life they are not meant to cover all the upper torso.
> About the Sarashi, I think I can add a "belly wraps" item to the game, I would like to add a "Sarashi" item too that covers from the knees to the upper torso, but I'm not sure if it would be accepted.

Yes, I meant adding a separate set of "stomach wrap" items for the usual materials to complement the "chest wrap" which would be limited to the upper torso. If/when #52826 gets added each of these would be something like 40-75% coverage on its non-overlapping sub-location instead of the global 20-30% range they currently use. Also this stuff should be clothing-thin so not a way of cheating in some early armour by turning yourself into a leather-clad mummy even if we eventually get >90% coverage wraps for all sub-locations.

**Comment by Termineitor244** [comment]
> Yes, I meant adding a separate set of "stomach wrap" items for the usual materials to complement the "chest wrap" which would be limited to the upper torso. If/when #52826 gets added each of these would be something like 40-75% coverage on its non-overlapping sub-location instead of the global 20-30% range they currently use. Also this stuff should be clothing-thin so not a way of cheating in some early armour by turning yourself into a leather-clad mummy even if we eventually get >90% coverage wraps for all sub-locations.

The wraps are definitely not good armor haha, I think the stomach wrap does cover the whole lower torso area, but apart from that we think the same.

**Comment by Termineitor244** [comment]
[This](https://stealthgearusa.com/stealthgearusa-belly-band-holster/l) is the belly band holster I based the one I added, I'm not sure about the exact values of its pockets so if anyone wants a different value, I'm all ears.

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
