### PR TITLE
Adds a dedicated item category for seeds

### PR DESCRIPTION
**Pull request by illi-kun**
This PR completes another one request from #19930, namely all seeds are moved to a dedicated category.

seeds

I'm not sure about ```raw beans```, I guess they are more ```seeds``` and less ```food``` but comments welcomed.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Looks good, but there are also plantable `marloss` and `datura` seeds whcih belong to `FOOD` and `OTHER` categories.

image

**Comment by illi-kun** [comment]
Re: ```marloss``` - i'll fix this;
Re: ```datura``` - this is weird that it's 'other' on your screenshot, take a look on my one - it's in the middle of the ```seeds``` list. Did you testing it by manual copying the files? Or do you know another potential reason of this difference?
Re: ```coffee beans``` (```other``` category) and ```raw beans``` (```FOOD``` category): your screenshot helps to find out that it's better to move them both to ```seeds``` for consistency.

**Comment by ZhilkinSerg** [comment]
Sorry, `datura` is good - I forgot to copy `med.json` when testing.

**Comment by illi-kun** [comment]
Jenkins, rebuild.

**Comment by Mecares** [comment]
Do you plan to migrate them to an own file in a later PR?

**Comment by illi-kun** [comment]
@Mecares totally correct, linting and migration is planned.

**Comment by Leland** [comment]
Nice, love that you're tackling things from #19930. Linking #14855 as well for posterity.

**Comment by illi-kun** [comment]
@Leland Yeah, I've found this list by one of your references, thanks for that btw. The list itself contains reasonable and neat requests, so it's a joy to implement it.

**Comment by Soyweiser** [comment]
Are raw beans and coffee beans plantable?

**Comment by illi-kun** [comment]
yes for beans and no for coffee beans (due to New England's climate restrictions I guess).

**Comment by Mecares** [comment]
Also coffee plants grow for 3 to 4 years before first harvest...

**Pull request merged**
