### PR TITLE
Contained item actions

### PR DESCRIPTION
**Pull request by Coolthulhu**
Includes #11562

Allows long salvage and item action menu to use contained items (sheathed knives).

### CODE REVIEW

**Comment by KA101** [comment]
Been holding on the previous one for the loss of constness, wanted that to go through the code-side devs.

**Comment by Coolthulhu** [comment]
In #11554 BevapDin said that casting away constness from the result of `character::items_with` is not wrong. Here I'm also using the result of `character::items_with`, so I assumed it would be OK.

**Comment by KA101** [comment]
Nice to feel treated like a rubber stamp.  >_<

**Comment by Coolthulhu** [comment]
Not sure what do you mean here. You wanted a dev to approve it, so I found a post that suggests it should be OK. Right?

**Comment by Coolthulhu** [comment]
Hack-less version is in.

KA101, please don't take my posts personally - I was just joking there. Sorry

**Comment by KA101** [comment]
Noted.

**Pull request merged**
