### PR TITLE
Compilation Fixes!

### PR DESCRIPTION
**Pull request by DavidKeaton**
Hey ya'll! Noticed these when trying to compile my latest branches! ;-)

Two minor issues, fixes included for free!

-Davek

### CODE REVIEW

**Comment by Coolthulhu** [comment]
```
src/veh_typedef.cpp: In member function 'const T& string_id<T>::obj() const [with T = vehicle_prototype]':
src/veh_typedef.cpp:302:9: error: missing initializer for member 'vehicle_item_spawn::pos' [-Werror=missing-field-initializers]
         };
         ^
src/veh_typedef.cpp:302:9: error: missing initializer for member 'vehicle_item_spawn::chance' [-Werror=missing-field-initializers]
src/veh_typedef.cpp:302:9: error: missing initializer for member 'vehicle_item_spawn::item_ids' [-Werror=missing-field-initializers]
src/veh_typedef.cpp:302:9: error: missing initializer for member 'vehicle_item_spawn::item_groups' [-Werror=missing-field-initializers]
```

**Comment by DavidKeaton** [comment]
on it

**Comment by Coolthulhu** [comment]
OK, this one compiles.

**Comment by DavidKeaton** [comment]
Cool beans! :-) Gotta make it EXTRA obvious for clang! ;-)

**Comment by BevapDin** [comment]
> Gotta make it EXTRA obvious for clang! ;-)

Well, *my* gcc (5.1.0) and *my* clang (3.6.0) very much accept
```C++
static const vehicle_prototype dummy{};
```

But whatever, as long as it works for everyone.

**Comment by narc0tiq** [comment]
> Notice(CDDA-Jenkins): Project Cataclysm: Dark Days Ahead »
Curses,Linux_x64 build #3171: FIXED in 2 min 58 sec:
http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Linux_x64/3171/

Thanks.

**Pull request merged**
