### PR TITLE
Adjust fridge/freezer power consumption

### PR DESCRIPTION
**Pull request by cake-pie**
#### Summary
```SUMMARY: Balance "Adjust fridge/freezer power consumption"```

#### Purpose of change
From part of discussion in #25139 

>If the complaint is that "running the fridge drains batteries too quickly", another factor to consider is duty cycle.
>
>Currently, vehicle fridge and minifreezer operate on a simple model. They are in an "always-on" state, and simply maintain a constant internal temperature; they do not absorb heat from the surrounding environment or react to opening/closing the fridge door, nor do they care about what their contents are or what temperature those are at.
>
>Real world fridges generally aren't running all the time

tl;dr: fridge/freezer consume way too much electricity

#### Describe the solution

Reduce the electrical consumption of the fridge and freezer.

Instead of using the max wattage indicated on the appliance rating plate, base our values for `epower` on average consumption.

I looked at a few refrigerators while window shopping and found one that was 71L capacity advertised as 250+kWh per annum. Using 260kWh / 1 year ≈ 30W as a conservative setting for the fridge. Freezer scaled accordingly.

### CODE REVIEW

**Comment by woutershep** [comment]
Not saying it should be blocking this PR but when i read the 'cause' i wonder why we don't change to a simple system where we charge a small amount of epower all the time and additional epower for every downward temperature change of an item? (disclaimer: i havent seen the fridge vpart code since before all the temperature overhauling, im not sure if this is still as simple as i think it is)

It won't be as close to simulating full environmental interaction but it might be sufficient. It would consume a lot of epower for a bit when putting hot tea into it, to cool that tea down. But once its cooled down it would consume a very small base value. This would also mean players are incentivised to let their stuff cool before shoving it in just like in the real world.

**Comment by cake-pie** [comment]
> additional epower for every downward temperature change of an item

Not opposed to the idea of more sophisticated modeling of fridge operation, but out of scope for this PR.

> (disclaimer: i havent seen the fridge vpart code since before all the temperature overhauling, im not sure if this is still as simple as i think it is)

It probably isn't. If you want to look into it, starting points are:

- Temperature change on items is currently applied in [`map::apply_in_fridge()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/d1b91f34ef405e3ee76bb52306ba316c4196be70/src/map.cpp#L4280) but will be moved into [`item::calc_temp()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/9c63847463a45762ce8f3aef8f96b52de44d94a8/src/item.cpp#L5935) by #25509 .

- Fridge/freezer electricity consumption -- at a constant, always-on rate -- is processed together with all other `ENABLED_DRAINS_EPOWER` parts [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/d1b91f34ef405e3ee76bb52306ba316c4196be70/src/vehicle.cpp#L2680-L2682).

**Comment by PenceGL** [comment]
I'm glad to see other people have noticed they seem to drain quickly. Even with 8 upgraded solar panels on my vehicle, running the fridge by itself was too much to be sustainable for more than a few in-game days. Looks like it'll feel much more lenient after this change.

**Comment by nexusmrsep** [comment]
Some quick research result, from manufacturer Q&A:
image
,61 Ah/h times 12 Volts equals 7,32 W/h times 24 h = 175,68 W / day if my calcs are right for a small fridge.

**Comment by cake-pie** [comment]
> .61Ah/h

Uhm... that's a strange way of putting it, but if it draws 0.61 amps under the given conditions, then consumption is just 7.32W.

That's a tempting low figure, but this product is a [10.5L portable fridge](https://www.dometic.com/en-us/us/products/food-and-beverage/coolers/electric-coolers/dometic-cdf-11-_-139583), and as such isn't a good point of reference.

The in game minifridge has 75L capacity. I actually went into a store and looked at a 71L model.

**Pull request merged**
