### PR TITLE
Fire in fire-containing furniture will move with it while grabbing - take two

### LINKED ISSUE #21283: moving a wood stove with a fire on the tile does not move the fire
while not exactly a bright idea, it should be possible to move a lit wood stove/brazier without burning the rest of the building down

supposedly this means that the fire is burning in the same tile but not on the fire ring/stone fireplace or whatever

image

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Fire in fire containing furniture will move with it while grabbing."```  

#### Purpose of change
Closes #21283.

#### Describe the solution
The code is mostly the same as in #21338. 

Pushing and shifting fire-containing furniture is handled in `grabbed_furn_move`. Works as follows: 
Remember fire strength and age at the old place before moving -> move furniture -> remove fire from old place -> create fire at the new place with old strength and age -> move player.
Pushing and shifting works perfectly.

Pulling fire-containing furniture is handled in `walk_move` because player should move prior to creating fire field at the destination point. Works as follows: 
Move furniture -> move player -> remember fire strength and age at the old place before moving -> remove fire from old place -> create fire at the new place with old strength and age.
~~Unfortunately, I encountered some very strange behavior while pulling fire-containing furniture. As seen in gif below, at some point (next to the stairs) my character continues to pull furniture, but loses fire within! At the same time duplicating fire spawns outside the shelter (behind the west wall). Suggestions, anyone?~~

#### Describe alternatives you've considered
None.

#### Additional context

Also added several periods in the end of some sentences.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Experiments revealed the following.

My character is moving to the right. Furniture with contained fire moves correctly within submap borders.
first

X coordinate changes from 70 to 71.
second

My character is still moving to the right. 
third

X coordinate for some reason becomes 60 instead of 72.
fourth

Furniture moves correctly, but contained fire stays within submap borders.
fifth

**Comment by ifreund** [comment]
This is happening because `place_player()` can cause a submap shift, throwing off your coordinates.  I resolved this same issue in #28365 with this calculation:
https://github.com/CleverRaven/Cataclysm-DDA/blob/70d228c08167456718343fc55f91fa587675e2d0/src/game.cpp#L10601-L10602

I think you'll need to make place_player return the shift returned by `update_map()` then use that value to calculate the adjusted position from your `furn_dest` tripoint.

**Comment by Night-Pryanik** [comment]
Ok, thanks, I'll try.

The one thing I still don't understand is why this is happening only with pulling - pushing furniture with contained fire will move them correctly all the time.

**Comment by ifreund** [comment]
>The one thing I still don't understand is why this is happening only with pulling - pushing furniture with contained fire will move them correctly all the time.

That'd be because `grab_furn_move()` is called in `walk_move()` before `place_player()` is called causing the possible submap shift

**Comment by ZhilkinSerg** [comment]
Great it is not stalled!

**Comment by Night-Pryanik** [comment]
Either it isn't working or I'm doing something wrong (most probably).

I modified `update_map( player &p )` to return a `point` value:
```c++
{
    int x = p.posx();
    int y = p.posy();
    - update_map( x, y );
    + return update_map( x, y );
}
```
Then I modified `game::place_player` to also return a `point` value:
```c++
- update_map( u );
+ point submap_shift = update_map( u );

...

+ return submap_shift;
```
Then I used your code in `game::walk_move`:
```c++
+ const tripoint old_pos = u.pos();

- place_player( dest_loc );
+ point submap_shift = place_player( dest_loc );

+ const tripoint adjusted_pos( old_pos.x - submap_shift.x * SEEX, old_pos.y - submap_shift.y * SEEY,
        old_pos.z );

...

- m.set_field_strength( furn_dest, fd_fire, fire_str );
- m.set_field_age( furn_dest, fd_fire, fire_age );
+ m.set_field_strength( adjusted_pos, fd_fire, fire_str );
+ m.set_field_age( adjusted_pos, fd_fire, fire_age );
```

And it still leaves the fire on the submap border.

**Comment by ifreund** [comment]
Think I've got it working, will send you a PR after I test it some.

**Comment by Night-Pryanik** [comment]
Thanks A LOT for this!

**Comment by ifreund** [comment]
No problem, this ones been a while in the making and I'm glad to see it finished!

**Comment by Night-Pryanik** [comment]
Guess this PR at last could be considered done.

**Comment by kevingranade** [comment]
In loving memory of Bob, who died testing this PR.
Wandered into range of a roadblock while dragging a brazier.

**Comment by Tsunder** [comment]
/o/ yay

**Pull request merged**
