### PR TITLE
Plumbing: connects urban_25 to the main sewer system

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
Content "Connects urban_25 to the main sewer system."

#### Purpose of change

Partially addresses #62747. Yep, still not given up.

There used to be line of sewage tiles underneath dense urban `#25`, which, due to technical limitations, couldn't be linked up with the main sewer line.

Sanitation for the people!

#### Describe the solution

Connected the sewage line to the main sewage system using fake sewer connectors.
I also added an abstract overmap terrain for future sewer tiles.

#### Describe alternatives you've considered

None.

#### Testing

Loaded in a world.

kép
kép

#### Additional context

Connecting every building to the sewer system?  I feel like these sewage lines should only represent larger infrastructure and let the smaller ones be filled out by our imagination.

### CODE REVIEW

**Comment by Procyonae** [comment]
~~Yay another merge conflict for my subway PR~~ Good to see you back in action ^_^

**Comment by LovamKicsiGazsii** [comment]
> ~Yay another merge conflict for my subway PR~ Good to see you back in action ^_^

Great to be back!

And sorry about that!

**Comment by Maleclypse** [comment]
> > ~Yay another merge conflict for my subway PR~ Good to see you back in action ^_^
> 
> Great to be back!
> 
> And sorry about that!

While you are here I want to mention you inspired me to do things like extend params usage in houses and even try and add some additional houses. Glad to see you again!

**Comment by Maleclypse** [comment]
```
 Backtrace emission took 1 seconds.
([slow] ~starting_items)=> (continued from above) ERROR : sym is not defined for overmap_terrain: sewer_connector (sewer)
```

**Comment by LovamKicsiGazsii** [comment]
Oh, that makes sense. Thanks!

**Pull request merged**
