### PR TITLE
added sheathable to bokken

### PR DESCRIPTION
**Pull request by Xpyder**
added sheathable to bokken for consistency

There is some discussion about whether it should fit in the same sheaths as other swords, realism vs gaming concession.  Either way we should establish consistency before making larger changes.

### CODE REVIEW

**Comment by Cyrano7** [comment]
@Xpyder Couldn't one also establish consistency by removing wooden swords from sheaths? The conciseness + Kevin seemed to be in favor of having wooden swords not fit in sheaths.

**Comment by Xpyder** [comment]
Certainly, but I figured since this requires the fewest changes and because sheaths do exist for bokkens this was the closest to current implementation until other changes are decided upon.

**Comment by Xpyder** [comment]
if you're looking for something to get past suspension of disbelief I'll offer this: Most sheaths are attached to a belt/sling via rings of material (leather?).  In theory you could just remove the actual shield part of the sheath and slip the non-swords through those rings, provided it wasn't sharp enough to cut them.

**Comment by kevingranade** [comment]
I find it hard to believe that removing sheath ability from the other
wooden sword-like things is considerably more difficult than adding it to a
bokken.
Trying to break out non-controversial changes to get them merged is great,
but this change is at the core of the controversy.

**Comment by Xpyder** [comment]
It's not about coding difficulty

I see a fundamental difference between bringing existing items in line with the currently implemented paradigm, and changing the paradigm itself.

The former is a simple process only requiring coding changes, the latter is a high level issue that requires discussion and community consensus (or developer override).

I'm just trying to do the former, and since the bokken was added most recently and it's the only sword like option that lacks sheathing ability and it has an actual sheath in real life this seems closest to the current paradigm.  We already accept the gaming concession that a rapier and a scimitar share the same sheath in the game but not in real life.  It's no more unreasonable for a bokken to follow this same pattern.  Please note that I didn't say the concession was a reasonable one, only that it's currently accepted.

**Comment by Xpyder** [comment]
TL:DR

they are two different issues, one is a coding change to bring uniformity, the other is a request to change how they these items are intended to be implemented.

**Comment by Xpyder** [comment]
@kevingranade 
My understanding is that you're the core developer for this project, if you want to exercise your right to developer override I'll create an alternate PR removing the sheath from those items and post a conceptual prototype for one way custom sheathing could work.

I just wasn't comfortable taking that liberty with there being strong enough counter arguments in play.  Plus I don't really have an issue with the universal sheath myself, it's easier for me to accept than universal weapon attachments and I accept that because my loot piles would get SO messy without them.

**Pull request merged**
