### PR TITLE
add earthworms and their delicacies

### PR DESCRIPTION
**Pull request by juur**
#### Summary
Content "Add earthworms to the game, as a food source"

#### Purpose of change

Earthworms are quite [nutritious](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10217592/). so would be good to have them in the game. Top soil contains quite a lot, on average, [250 per m2 potentially](https://www.wigglywigglers.co.uk/blogs/blog/how-many-worms-do-i-have-in-my-garden), and can be [cooked](https://www.wikihow.com/Eat-Worms) into things not totally disgusting 

#### Describe the solution

Create earthworm (1x worm) and earthworm_handful (10x worms). Allow purifying into earthworm_boiled (10x worms), smoking into earthworm_dried and cooking into earthworm_fried. Update digging_soil_loam_50L to have a topsoil variant, and include random worms in it. Add to various existing lists as meat alternative.

### CODE REVIEW

**Comment by juur** [comment]
I don't understand why adding this to the itemgroup causes the game to crash on load - am I missing something obvious?

**Comment by RenechCDDA** [comment]
Ahhh this is the infamous [rock crash](https://github.com/CleverRaven/Cataclysm-DDA/issues/50493)! It's not your fault that it crashes.

I'll try to give it a poke later today, if I can fix it you'll have to rebase to after the commit that fixes it.

**Comment by juur** [comment]
> Ahhh this is the infamous [rock crash](https://github.com/CleverRaven/Cataclysm-DDA/issues/50493)! It's not your fault that it crashes.
> 
> I'll try to give it a poke later today, if I can fix it you'll have to rebase to after the commit that fixes it.

I thought it was something ticking when it shouldn't.. thank you so much!

**Comment by RenechCDDA** [comment]
Christmas came early, I've put a PR up for it. Sorry this issue came up, I think your PR is quite interesting! I hope we can quickly knock out the crash for you.

**Comment by fairyarmadillo** [comment]
I think your kcal value might be too high.

https://www.outdoorlife.com/blogs/survivalist/2014/07/survival-skills-3-safe-bugs-and-how-eat-them/ says that earthworms have about 1 kcal/gram. 

Hard numbers for calorie content of actual earthworms is pretty hard to find, but we can fact-check the above claim by comparing it to chicken breast meat, which is 2kcal/gram. Since a whole earthworm is obviously going to be less calorie-dense than a prepared piece of meat of the same size (some percentage of the worm's body is not going to be digestible matter), 1kcal/g sounds right to me.

I'd also suggest bumping the size down to 2g. 3g is like at the outside of what a typical earthworm can get to, and not every one you find is going to be that big.

Lastly if I'm reading the json right, you have it so that digging up a patch of soil will always produce 1-10 earthworms. I see worms a lot where I live but I don't find one every time I turn over a shovel, maybe adding a probability there, so that people aren't flooded with worms every time they dig?

https://www.youtube.com/watch?v=3ILoGcSxCAY

**Comment by juur** [comment]
> I think your kcal value might be too high.
> 
> https://www.outdoorlife.com/blogs/survivalist/2014/07/survival-skills-3-safe-bugs-and-how-eat-them/ says that earthworms have about 1 kcal/gram.
> 
> Hard numbers for calorie content of actual earthworms is pretty hard to find, but we can fact-check the above claim by comparing it to chicken breast meat, which is 2kcal/gram. Since a whole earthworm is obviously going to be less calorie-dense than a prepared piece of meat of the same size (some percentage of the worm's body is not going to be digestible matter), 1kcal/g sounds right to me.
> 
> I'd also suggest bumping the size down to 2g. 3g is like at the outside of what a typical earthworm can get to, and not every one you find is going to be that big.
> 
> Lastly if I'm reading the json right, you have it so that digging up a patch of soil will always produce 1-10 earthworms. I see worms a lot where I live but I don't find one every time I turn over a shovel, maybe consider adding a probability there, so that people aren't flooded with worms every time they dig?
> 
> Great idea though! If it gets merged I'll add a thing that lets fish and bird mutants enjoy eating worms, because that's funny to me.
> 
> https://www.youtube.com/watch?v=3ILoGcSxCAY

I think the current values are a bit too low. 3.2 tonne of soil, giving 183 earthworms. That doesn't feel right. Different Internet sources:

- [200 per sq.M](https://www.nhm.ac.uk/take-part/monitor-and-encourage-nature/project-archive/earthworm-watch.html)
- [60 per sq.M for intensively farmed, up to 450 for richer organic](https://www.dw.com/en/earthworm-numbers-dwindle-threatening-soil-health/a-37325923)
- [A bit complicated ... around a 100 per sq.M maybe?](https://www.biorxiv.org/content/10.1101/587394v2.full)

image

**Comment by juur** [comment]
> > Lastly if I'm reading the json right, you have it so that digging up a patch of soil will always produce 1-10 earthworms. I see worms a lot where I live but I don't find one every time I turn over a shovel, maybe consider adding a probability there, so that people aren't flooded with worms every time they dig?

I've made some changes to reduce the item count, and hopefully balance spamming inventories vs. realistic amounts of food..

**Comment by fairyarmadillo** [comment]
> I think the current values are a bit too low. 3.2 tonne of soil, giving 183 earthworms. That doesn't feel right. Different Internet sources:

Yeah but the player isn't going to realistically be able to capture all of those, even if they're trying. We also don't currently have any way to vary their distribution, so a forest, a swamp, a farm, and a construction site are all going to produce the same number of worms, even in the dead of winter. That last part is probably fixable in another PR so I wouldn't worry about seasonal distribution too much, but if you take a shovel and dig a 3 foot pit, most of the worms you get are going to escape while you're busy digging, unless you want to sift every shovelful for worms, which is going to take the work take much longer.

I propose keeping the numbers received from digging low for now, and then later adding a proficiency-based worm grunting method (like in the youtube video I linked) that produces many more. We can make these guys work as bait for fishing, so IMO it's worth quibbling about.

**Comment by juur** [comment]
> > I think the current values are a bit too low. 3.2 tonne of soil, giving 183 earthworms. That doesn't feel right. Different Internet sources:
> 
> Yeah but the player isn't going to realistically be able to capture all of those, even if they're trying. We also don't currently have any way to vary their distribution, so a forest, a swamp, a farm, and a construction site are all going to produce the same number of worms, even in the dead of winter. That last part is probably fixable in another PR so I wouldn't worry about seasonal distribution too much, but if you take a shovel and dig a 3 foot pit, most of the worms you get are going to escape while you're busy digging, unless you want to sift every shovelful for worms, which is going to take the work take much longer.
> 
> I propose keeping the numbers received from digging low for now, and then later adding a proficiency-based worm grunting method (like in the youtube video I linked) that produces many more with less time and effort. We can make these guys work as bait for fishing, so IMO it's worth quibbling about.

If you have a preference vs the current patch, let me know and I'll change it. I can't merge until the linked bug is resolved anyway.

**Comment by fairyarmadillo** [comment]
No I think the current count is good, just letting you know there's a method we can add later to get more worms if the player really wants some.

**Comment by RenechCDDA** [comment]
As you're still in draft, I think they could be added to the [fish bait recipe.](https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-02-18-0606/data/json/recipes/other/other.json#L2-L28)

**Comment by AcidAntOnAMinefield** [comment]
> Toxic metals such as vanadium (0.2 mg·kg−1 DW), lead (0.2 mg·kg−1 DW), cadmium (2.2 mg·kg−1 DW), and arsenic (2.3 mg·kg−1 DW) were found in EAP, which pose safety considerations. 

> ICP-MS analysis detected 15 minerals in EAP with relatively high levels of calcium, potassium, phosphorus, sodium, iron, zinc, and manganese. However, levels of some heavy metals (cadmium, arsenic, and lead) were detected, which presents food consumption and safety considerations.

The study isn't quite 100% on them being actually completely safe, so I would probably suggest making it so there's some drawback to a character eating them - so far I can only see that they provide 10x more calcium and iron when cooked, compared to raw.

**Pull request merged**
