### PR TITLE
Move remaining forum links to discourse

### PR DESCRIPTION
**Pull request by Leland**

### CODE REVIEW

**Comment by AMurkin** [comment]
Change www.cataclysmdda.com to cataclysmdda.org too?

**Comment by Leland** [comment]
Yeah, what's up with that? Is the Github Pages .org site the new homepage? What's happening with the .com one?

**Comment by AMurkin** [comment]
Can't find a message, but it will gone to ethernity.

**Comment by kevingranade** [comment]
> Is the Github Pages .org site the new homepage?

Yes
> What's happening with the .com one?

Going away in March AFAIK

**Pull request merged**
