### PR TITLE
Fix reloading using liquids in containers

### LINKED ISSUE #15200: Reloading item with liquid dumps the liquid into inventory with no (easy) way of returning the liquid to a container.
As per this comment on the forum: http://smf.cataclysmdda.com/index.php?topic=14.msg266539#msg266539

I've verified that this happening, to reproduce:
- Item that uses liquid charges (I used oil lamp)
- reload item so that there is spare charges remaining (get 400/800 charges, then refill with full bottle (800) of lamp oil)
- Oil will now be in inventory.

### PR DESCRIPTION
**Pull request by mugling**
Closes #15200 

Please drop any non-contained liquids in your inventory and walk several tiles away before testing this fix.

### CODE REVIEW

**Comment by macrosblackd** [comment]
This appears to fix the issue.

**Comment by Coolthulhu** [comment]
Not sure if its this PR or some other one, but something wrecked all magazine reloading. I suspect this one, because it handles reloading. Won't be merging this one right now, unless a fix gets pushed before I finish this mergetest batch.

**Comment by mugling** [comment]
What specifically is the problem?

**Comment by Coolthulhu** [comment]
I'm testing both this and #15207 at the same time.
I can't load a gun with a loaded magazine, only with an empty one.
I can load a magazine into a magazine, which then can be loaded into a gun.

**Comment by mugling** [comment]
I think the problem was that `is_ammo_container` includes magazines so I've moved the more specific check for `is_magazine` before it. See 06a40bf

**Pull request merged**
