### PR TITLE
Format item.h

### PR DESCRIPTION
**Pull request by ghost**
The original indents are so chaotic!

### CODE REVIEW

**Comment by Coolthulhu** [comment]
If it is fully astyled, you should add it to `astyle_whitelist` too.

Needs a rebase, though.

**Comment by DLaboratory** [comment]
```
astyle regressions found.
Formatted  src/item.h
```

How to deal with this? It seems that `astyle` has a bug formatting code below:
```C++
struct fire_data;

enum damage_type : int;

std::string const &rad_badge_color( int rad );

struct light_emission {
    unsigned short luminance;
```

It always produces
```C++
struct fire_data;

enum damage_type : int;

    std::string const &rad_badge_color( int rad );

    struct light_emission {
    unsigned short luminance;
```

**Comment by Coolthulhu** [comment]
Yeah, it is a bug in the `astyle`. We currently don't have a proper solution.
The workaround is to have all the forward declarations before a small `struct` or `class` - it stops being bugged after a closed brace for some reason.

**Comment by mugling** [comment]
Too many lines at once - will cause merge conflicts with all other outstanding PR's

**Comment by DLaboratory** [comment]
Closed for a period.

**Pull request closed without merging**
