### PR TITLE
Normalize and balance .38

### PR DESCRIPTION
**Pull request by mugling**
Slightly higher `weight` and lower `stack_size` and `damage` than 9mm but less `recoil` and when jams are added the inherent reliability of the revolvers will be a significant advantage.

### CODE REVIEW

**Comment by kevingranade** [comment]
>  jams are added the inherent reliability of the revolvers will be a
significant advantage.

I think the rate of jams is going to be low, the unit will probably be
something like jams / 10,000 rounds fired, and guns with rates above 1/1000
should be very rare. That's based on some reading about jam rates in
military studies I did a while back. If there are sources indicating some
guns jam at higher rates I'm happy to hear about it though.
That can be significant, especially since some of those jams will be very
hard to clear, but I want to make sure we're on the same page before you
factor high jam rates into your balancing of firearms.

**Comment by mugling** [comment]
> but I want to make sure we're on the same page before you factor high jam rates into your balancing of firearms.

Thanks for the heads-up. I was considering an implementation with three types of failure:

* `MISFIRE` - Ends any burst early and wastes remaining moves whilst you cycle the action
* `BAD_MISFIRE` - As above but damages the gun
* `JAMMED` - Status effect applied to gun which must be unloaded and reloaded before use

Factors affecting frequency would include:

|            |  gun `durability`  | mag `reliability` | burst fire | ammo `RECYCLED`  | ammo `OVERPRESSURE`  |
|----------|----------------------|---------------------|----------|-----------------|----------------------|
| `MISFIRE` |   X   |   | X | X | | 
| `BAD_MISFIRE` | X   |  | | X | X | 
| `JAMMED` | X | X | X | X | |

> I think the rate of jams is going to be low, the unit will probably be something like jams / 10,000 rounds fired, and guns with rates above 1/1000 should be very rare

Likely true but at 1/10'000 all in-game weapons are effectively infinitely reliable. How would you feel if we started out with most guns being very reliable (>=1/1000) but that abuse (damage, recycled ammo, improvise magazines etc) could cause significant problems.

For example an inherrrently unreliable STEN using a makeshift magazine and reloaded ammo fired on full auto should be 20x more likely to jam than an inherrently reliable ak47 fired semi-automatic with a factory magazine and ammo:

| gun | magazine | ammo        | mode | `MISFIRE` | `BAD_MISFIRE` | `JAMMED` |
|--------|------------|---------------|-------|--------|--------------|--------|
| ak47 | factory   | standard    | semi | 1000 | ∞ | 2000 |
| ak47 | high cap | standard   | semi |1000 |  ∞ | 1000 |
| ak47 | factory   | `OVERPRESSURE`   | semi | 1000 | 500 | 1000 |
| ak47 |  high cap  | `RECYCLED`   | burst | 500 |  ∞ | 500 |
| sten | factory   | standard    | semi | 500 | ∞ | 500 |
| sten |  makeshift  | `RECYCLED`   | burst | 100 |  ∞ | 100 |

**Comment by Rivet-the-Zombie** [comment]
@mugling, would you mind altering gun handling so that guns can support multiple caliber types? It would provide support for stuff like .357 magnum firearms, which can load both .357 as well as .38 rounds, whereas .38 firearms can only use .38 rounds.

The lack of such a feature is why we still don't have calibers like .357 and .410 in the game.

**Comment by Coolthulhu** [comment]
> How would you feel if we started out with most guns being very reliable (>=1/1000) but that abuse (damage, recycled ammo, improvise magazines etc) could cause significant problems.

Crafted ammo and magazines yes, but don't balance it too much around gun damage. It is currently handled rather badly - most midgame characters can fix it in no time, with negligible resource usage, while early game ones are totally stuck with it and can't repair even the smallest scratch.

Another thing to consider when checking for reliability: weather.

**Comment by kevingranade** [comment]
Something I realized I was taking for granted, are we actually modelling
fire *rate* in a way that matches reality?
If in-game a player fires 1/10 as many rounds as a real person would in a
similar situation, then jam rate should be 10x as high to compensate. No
idea where those numbers really are.

**Pull request merged**
