### PR TITLE
Support recursive palettes

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Infrastructure "Support recursive palettes"

#### Purpose of change
Resolve the long-standing implied promise in our error message "Recursive palettes are not implemented yet".

Right now support for recursive palettes doesn't simplify much, although it might make it easier to factor our some common parts of palettes without the mapgen using those palettes becoming too verbose.

However, my plan for the next mapgen enhancement to add is support for a weighted list of palettes.  This is intended to allow e.g. houses to choose between a 'regular' palette and a 'vandalized' palette.  We don't want the weights to be repeated in every house mapgen, so we need an intermediate palette which contains the weighted list of other palettes.  That entails recursive palettes, and it seemed like a mostly independent feature so I'm PRing it in isolation.

#### Describe the solution
The problem with recursive palettes is that we have no control over palette load order.  So, we just store the ids of the referenced palettes as we load them.  Only when inlining palettes into the final mapgen object which uses the palettes do we then recursively search all the palettes it uses, since they will all have been loaded by then.

Add error checking to ensure we don't get into an infinite loop if palettes refer to each other.

Use the new feature in the new `'lab_mutagen` special to verify that it works.  @curstwist I hope you don't mind me taking advantage of this to use as a test.  If you don't want to use recursive palettes there I'm happy to excise that commit from this PR (or you can revert it later).

At the same time, I made `palette_id` a proper `string_id` rather than just a `std::string` alias.  And I added it to `cata_variant`.  That turned out not to be needed for this PR, but it's a good thing anyway and I expect to need it in the future.

#### Describe alternatives you've considered
Trying to topo-sort palettes and load them in a particular order, but I think that would be much messier.

#### Testing
Unit tests.  Verified that the mutagen lab mapgen still looks reasonable.

#### Additional context
Part of my ongoing effort to provide more mapgen features.

### CODE REVIEW

**Comment by curstwist** [comment]
It is fine to use the lab.  Let me know if you need anything on my end.

**Comment by actual-nh** [comment]
When one is _not_ specifying weighting (including before that PR goes in), what will happen with conflicting palette entries?

**Comment by jbytheway** [comment]
When multiple palettes define the same symbol, they will all be applied, in depth-first in-order traversal order. So for terrain or furniture the last, least nested palette wine. For items or monsters you get all the stuff from all the palettes.

**Comment by actual-nh** [comment]
A couple of thoughts:
- Eventually, a flag for "don't override nested palettes" on a palette could be nice.
- Currently, arrays are not overridden correctly, from what curstwist has stated on the dev discord; any effect on that from these changes?

**Comment by jbytheway** [comment]
>     * Eventually, a flag for "don't override palettes nested from this one" on a palette could be nice.

That would be tricky.  The structure of the code is such that you don't really retain the information you would need to make that happen.  A lot is lost to type erasure.  It could be done, but I think I would need a compelling use case.

>     * Currently, arrays are not overridden correctly, from what curstwist has stated on the dev discord; any effect on that from these changes?

Can you give an example (@curstwist?)

**Comment by curstwist** [comment]
Sure, example... 

In the standard_domestic_palette, we have:
`"+": [ [ "t_door_c", 5 ], [ "t_door_o", 5 ], [ "t_door_locked_interior", 1 ] ],`
If I change the `+` symbol to a different terrain (say `"+": "t_privacy_fencegate_c",`) in the main mapgen file (choose any house to test), and spawn the house.  Then the array is still used, instead of my replacement terrain.  Usually, the main mapgen would "win" and set the terrain based on our normal mapgen rules.

**Comment by jbytheway** [comment]
Ok, I think I understand what causes that behaviour of inconsistent overriding. It's unrelated to this PR, but I'll see if I can confirm my suspicion and open a separate PR to fix it.

**Pull request merged**
