### PR TITLE
Aftershock: Remove organ/meat related recipe overrides

### PR DESCRIPTION
**Pull request by ERRORCODE509**
#### Summary
Bugfixes "Aftershock: Organ/Meat Related Recipes Are No Longer Overridden"

#### Purpose of change
Aftershock has a bunch of overrides that were never updated to the new accurate crafting times in vanilla. Additionally, they appear to have never been updated to include human and demihuman components, only generic ones. This made it impossible to cook human and demihuman organs. This didn't appear to be intentional, so I went through and updated the recipes appropriately. Overrides were also made for human and demihuman flesh, as Aftershock overrides the recipe for standard cooked meat but didn't touch that of humans and demihumans.

#### Describe the solution
Updated existing recipe overrides and added new ones where appropriate.

#### Describe alternatives you've considered
Removing the organ/meat related overrides.

#### Testing
Added the overrides to my local copy and verified that they appear in-game without any issues.

#### Additional context
Let me eat people, damnit!

### CODE REVIEW

**Review by Maleclypse — CHANGES_REQUESTED** [review]
`Aftershock has a bunch of overrides that appear to be intended to reduce the crafting time for cooking organs` is not accurate.  
Correction
`Aftershock has a bunch of overrides that were never updated to the new accurate crafting times in vanilla"

**Comment by ERRORCODE509** [comment]
Updated the crafting times appropriately. Have we considered just removing the organ-related overrides? They seem somewhat unnecessary.

**Comment by Maleclypse** [comment]
> Updated the crafting times appropriately. Have we considered just removing the organ-related overrides? They seem somewhat unnecessary.

I asked in the current and former Afs dev chat and it looks like someone accidentally added these while trying to do something that was eventually completed using requirements instead. So these can be deleted. Thanks!

**Comment by ERRORCODE509** [comment]
Got it, I'll remove them once I get home from work.

**Pull request merged**
