### PR TITLE
Motor boat

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Added a metal motor boat with a single gasoline engine."```

#### Purpose of change
More water-based content.
- [X] Added a boat
- [x] Made it spawn somewhere

#### Describe the solution
Added a new vehicle. Gave it large 1-cylinder engine which seems appropriate for a vessel this size. Also after quick googling I decided that 3A bicycle alternator and 12Ah motorbike battery will fit nicely here too. Gave it a trunk to store items in.

#### Additional context
Wheeeeee!!!

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Zireael07** [comment]
Nitpick: most modern outboard engines are more than 1 cylinder. Tried to find out whether my parents' old engine is 1 or 2 cylinder, but the instructions are in Russian :(

**Comment by Night-Pryanik** [comment]
Yes, I know that, but at the moment we don't have 50-60 HP motor with >1 cylinders.

**Comment by Night-Pryanik** [comment]
Made motor boats spawn at the marina with a small chance (10%).

I couldn't make them spawn at the docks for some reason. 
```
{
    "type": "mapgen",
    "method": "json",
    "om_terrain": [ "lake_dock_small" ],
    "weight": 750,
    "object": {
      "predecessor_mapgen": "lake_surface",
      "rows": [
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "      dddddddddddd      ",
        "      dddddddddddd      ",
        "      dddddddddddd      "
      ],
      "palettes": [ "dock_small" ]
    },
    "place_vehicles": [ { "chance": 99, "fuel": 15, "vehicle": "boat_motor_single", "x": 12, "y": 10, "rotation": 0 } ]
  }
```
isn't working. @ralreegorganon maybe you can help?

**Comment by LovamKicsiGazsii** [comment]
> I couldn't make them spawn at the docks for some reason.
> 
> ```
> {
>     "type": "mapgen",
>     "method": "json",
>     "om_terrain": [ "lake_dock_small" ],
>     "weight": 750,
>     "object": {
>       "predecessor_mapgen": "lake_surface",
>       "rows": [
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "                        ",
>         "      dddddddddddd      ",
>         "      dddddddddddd      ",
>         "      dddddddddddd      "
>       ],
>       "palettes": [ "dock_small" ]
>     },
>     "place_vehicles": [ { "chance": 99, "fuel": 15, "vehicle": "boat_motor_single", "x": 12, "y": 10, "rotation": 0 } ]
>   }
> ```
Doesn't the ```},``` close the ```object``` line?

**Comment by Night-Pryanik** [comment]
Yeah, I was dumb and placed `place_vehicles` in the wrong place. Thanks for catching that.

**Pull request merged**
