### PR TITLE
Allow batch crafting for reversible items

### PR DESCRIPTION
**Pull request by BevapDin**
That was way easier than I though it would be, why haven't I done this before? Well, someone will surely find a flaw in this solution.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Heh, that was fast

**Comment by Barhandar** [comment]
Time to make some sandwiches for a legion!

**Comment by ejseto** [comment]
Isn't it a matter of balance?

**Comment by Barhandar** [comment]
>Isn't it a matter of balance?

There's no balance matter that I can think of that is affected by being able to long-action craft X of reversible item.

**Comment by ejseto** [comment]
Well instead of crafting one at a time and disassembling it over and over, you batch craft a dozen and disassemble them over and over, to build skill faster. Granted, it still won't prevent munchkins from munching, but that's the impression I got since it's so easy to fix. It's not even a "fix," it's undoing an arbitrary rule. Figured there had to be a reason for an arbitrary rule like that.

**Comment by Barhandar** [comment]
>you batch craft a dozen and disassemble them over and over, to build skill faster. 

If someone wants to do that instead of using that time for something useful, like, say, searching for a skill book, they're welcome.

**Comment by BevapDin** [comment]
> Well instead of crafting one at a time and disassembling it over and over, you batch craft a dozen and disassemble them over and over, to build skill faster.

You can already use the "Craft as long as possible" function, which works for all recipes. Or You craft an item, disassemble it and use the "Recraft last recipe" key to craft it again. All those methods should yield the same and should consume the same in-game time.

**Comment by Barhandar** [comment]
>All those methods should yield the same and should consume the same in-game time.

Batch-crafting can take less time than longcraft and recraft, if the recipe has batch time factor.

**Comment by chaosvolt** [comment]
And naturally I didn't find out this was fixed until Coolthulhu was halfway through merging a PR and wondered why I'd still set some recipes as uncraft versions instead of making the recipes reversible. Slowpoke as always.

**Comment by Barhandar** [comment]
>And naturally I didn't find out this was fixed until Coolthulhu was halfway through merging a PR and wondered why I'd still set some recipes as uncraft versions instead of making the recipes reversible. 

If it's any consolation, it got fixed _specifically_ because you've changed them to uncraft instead of them being reversible.

**Comment by chaosvolt** [comment]
Doh? o3o

**Pull request merged**
