### PR TITLE
Improving range of Barret System

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Current Barrett  M107A1 has dispersion stats same as other sniper rifles but at the same time lower max range (45). At the same time .50 BMG ammo has more dispersion then 30-06. That give overall slightly worse accuracy performanse to Barret in comparsion of Remington 700.

But according to this: 
https://github.com/CleverRaven/Cataclysm-DDA/pull/22756
and this:
https://en.wikipedia.org/wiki/Barrett_M82
https://en.wikipedia.org/wiki/Remington_Model_700

Barret has twice as longer effective range that Remington 700. And Longer max range.

To improve Barret accuracy its max range increased to 120 from 45. It should be good enoguh approximation of its real stats.

Now it least should be slightly better than non moded scoped Remington 700 not worse.

### CODE REVIEW

**Comment by FulcrumA** [comment]
I am.. somewhat cautious about that. If I understand correctly, With those changes Barrett will become ultimate single-shot rifle (it is arguably already seen as) under every circumstance other than CQB favoring a full-auto machineguns. Already its the single weapon community favors the most in taking down late-game enemies from afar.

It's a powerful, very long range gun but at least not superior to everything else under the sun at every range because of that accuracy penalty. Improving its dispersion will not only allow players to shoot at things from very far, but also as accurately as other guns which I'd consider a bit unfair.

**Comment by Firestorm01X2** [comment]
>It's a powerful, very long range gun but at least not superior to everything else under the sun at every range because of that accuracy penalty. 

So that that max range limit of 45 was intended?

**Comment by Firestorm01X2** [comment]
Travis, rebuild.

**Comment by FulcrumA** [comment]
Frankly, I do not know if any of the Barret traits were set to what they were due to any particular balance concern, I just know that Barrett already is seen as one of the best rifles in the game. I am not against the change, just underline the importance of caution since taking that all into consideration, I suspect it's very easy to mess things up with improving Barrett's performance.

**Comment by Firestorm01X2** [comment]
>I suspect it's very easy to mess things up when improving Barrett's performance.

We are talking abount setting its range to reality buuble and giving it +2 tiles of effective range. That is not much in comparsion of other rifles.

**Comment by kevingranade** [comment]
> We are talking about setting its range to reality bubble and giving it +2 tiles of effective range in some cases. That is not much in comparsion of other sniper rifles.

Pretty sure the point is the accuracy difference is the only area in which the barret is weaker than any other rifle in any way, if you remove that it simply becomes the best gun in the game without question, which you generally try to avoid from a game balance point of view.

Also, referencing other PRs doesn't "prove" anything, so please tone it down a bit.  Unfortunately most of the numbers in that spreadsheet either have no rationale, or very sketchy ones, i.e. for the barret its, "longest recorded hit ever with a gun of this kind", which is not particularly convincing.

**Comment by thethunderhawk** [comment]
If recoil and weight were modeled somewhat more realistically, trying to fire the Barrett from a standing position should have a chance of dislocating your arm. IRL it’s so heavy that you probably wouldn’t be able to aim the thing without using the bipod. In that sense it’s “balanced” IRL, snipers pretty much only ever use them from static positions and a guy who intends to move around a lot is likely gonna carry something else.

**Comment by Theundyingcode** [comment]
> IRL they're balanced by the very real probability of permanent hearing loss just like cannons.

Maybe add warning to  description?

**Comment by cainiaowu** [comment]
Could we change it into a gun that needs to be deployed before firing so you cant run and gun with it?

**Comment by cainiaowu** [comment]
To somwhat simulate this, we could add a json flag that if a gun has it any movement will maximize your recoil meter, so you have to be stationery long enough to get a accurate shot.

**Comment by kevingranade** [comment]
> any movement will maximize your recoil meter

That's how all guns act right now.  This would need to be something even more extreme to account for the time spent setting up.

**Comment by thethunderhawk** [comment]
Firing without a full stability meter could cause pain and/or have a significantly penalized accuracy?
(It’s not lost on me that I’ve been suggesting a lot of work that I probably can’t do myself, I’m not sure of the etiquette here. I’m just spitballing I hope I’m not ruffling any feathers I ought not be ruffling...)

**Comment by NotFuji** [comment]
What exactly is the problem with the Barrett being the best gun in the game?  It's not a common gun by any means, in fact, it's less common than laser rifles.

And @thethunderhawk The notion that you can dislocate your arms shooting an M107 is absurd.  The gun weighs almost 30lbs and has very minimal recoil.
https://www.youtube.com/watch?v=RzUAQoyvrOw
https://youtu.be/pAW3dlTMv6g?t=85

**Comment by thethunderhawk** [comment]
@NotFuji 
After a few mins of googling I’m a little embarrassed to say that you’re absolutely right and I’m way off about that.
Still though, I think it’d be fair to represent it and balance it as “difficult to fire from a standing position”. It’s 30lbs, you’d have a hard time holding it up and steady for long enough to accurately aim and hit a long distance target, especially for someone without a lot of experience, and especially when compared to other scoped rifles.

**Comment by Firestorm01X2** [comment]
>Still though, I think it’d be fair to represent it and balance it as “difficult to fire from a standing position”. It’s 30lbs, you’d have a hard time holding it up and steady for long enough to accurately aim and hit a long distance target, especially for someone without a lot of experience, and especially when compared to other scoped rifles.

But even in this case range limit of 45 should go away. There was no point to limit it to 45.

**Comment by Firestorm01X2** [comment]
>Also, referencing other PRs doesn't "prove" anything, so please tone it down a bit. Unfortunately most of the numbers in that spreadsheet either have no rationale, or very sketchy ones, i.e. for the barret its, "longest recorded hit ever with a gun of this kind", which is not particularly convincing.

Then I'll reference this:
https://en.wikipedia.org/wiki/Barrett_M82
https://en.wikipedia.org/wiki/Remington_Model_700

**Comment by FulcrumA** [comment]
@NotFuji 
>What exactly is the problem with the Barrett being the best gun in the game? It's not a common gun by any means, in fact, it's less common than laser rifles.
The same problem in every game when forcing a player to use particular weapon arbitrarily, providing illusionary alternatives there's little of a point of as they're all subpar, I'd imagine.

Clear favoritism of particular item, not to mention making it all depend on RNG - if you'll manage to find Barrett relatively early (and it can happen - I stumbled upon it in the very beginning once, in a crate abandoned off-road) then you're already set and barring lack of ammo, there's no drive or point in acquiring other firearms. Tactical decisions, different playstyles - it all goes out the window. If you have Barrett and you have ammo for it, you have no alternative but to use this single gun or cripple yourself by not doing so.

Lastly, to make it believable. There's no end-all military sniper rifle. No, Barrett isn't one either.

**Comment by NotFuji** [comment]
@FulcrumA 
That's bupkis.  Almost everything is already dependent on RNG.  Whether or not you find a running car is pure RNG, tools depend on RNG, finding any gun whatsoever is RNG.  What's the point of having a makeshift welder if a player _might_ find a regular one early on?

Does finding an awl pike or katana early on mean you never have to use a different melee weapon?  Kinda yeah.  Why should it be any different for guns?

**Comment by BorkBorkGoesTheCode** [comment]
>But even in this case range limit of 45 should go away. There was no point to limit it to 45.

The range field is additive, not an override; the Barrett will use the total of gun+ammo range when firing. Another example is the Cx4 which has +20 range bonus. The "Maximum range" field should be renamed to avoid this confusion.

**Comment by thethunderhawk** [comment]
@NotFuji
I’ve lost track of your argument here. You’re obviously not saying that the Barrett ought to be balanced as the best gun in the game right? 
I think we’re all in agreement here that the ideal solution would incorporate an increase in the Barrett’s range while nerfing it in other ways, both to bring it more in line with its real world use and to keep it logical from a game design perspective. Am I right about that?

**Comment by NotFuji** [comment]
@thethunderhawk 
I'm saying that if you set it's stats to real-life analogues, or at least consistent values and it ends up the best gun in the game, that's just the way it goes.

**Comment by thethunderhawk** [comment]
@NotFuji
If that’s true it’s only because gun weight isn’t modeled to deal with guns that heavy. Until that changes, you’re totally right, but that means that from a game design perspective these changes right here probably go too far towards making the Barrett the undisputed best gun in the game. Realism is great, but you shouldn’t make a change in the name of realism if it’s going to mess up the dynamics of the game.

Plus, at this point any changes that make the Barrett better for standard fire-and-maneuver (kiting) is gonna result in a less realistic outcome. Running around with a gun that big is just silly.

**Comment by Firestorm01X2** [comment]
>Plus, at this point any changes that make the Barrett better for standard fire-and-maneuver (kiting) is gonna result in a less realistic outcome. Running around all day with a gun that big is just silly.

There is no way to prevent that now. Even before changes you can do it. Or you can do it with other sniper rifle.

**Comment by thethunderhawk** [comment]
>There’s no way to prevent that now.

Yes, and until that changes there’s no making this weapon more realistic with the updates you’ve proposed, and they’ll throw the gun balance out of whack.

**Comment by Firestorm01X2** [comment]
>Yes, and until that changes there’s no making this weapon more realistic with the updates you’ve proposed, and those updates will throw the gun balance out of whack.

Are you tried it?
This change do exactly to thins:
* Adds +2 to effective range of Barret. To make slightly more effective than usuas sniper rifle.
* Adds reality buble range to barret (as for other sniper rifles).

About what "throwing away balance" you are talking about?

**Comment by thethunderhawk** [comment]
@Firestorm01X2
No I haven’t tried it you’re right I ought to. I was just taking Kevin’s word that the Barrett was ranged as such for specific balance reasons and that disturbing that would mess up that balance.

**Comment by Firestorm01X2** [comment]
>No I haven’t tried it you’re right I ought to. I was just taking Kevin’s word that the Barrett was ranged as such for specific balance reasons and that disturbing that would mess up that balance.

If it is "special case" then I'll agree with that. But it definetly needs confirmation.

**Comment by Firestorm01X2** [comment]
@thethunderhawk 

Ok. I've reverted accuracy change. But I think that range increase should stay.
In fact Barret initally has same accuracy as other sniper rifles- it is .BMG make it less accurate.

**Comment by thethunderhawk** [comment]
I’ll be real interested to see what @KevinGranade thinks I’m not real familiar with the specifics of the weapon balancing as it stands now. He mostly just seemed concerned with making sure it has some specific weakness to prevent it being the absolute no-brainer best choice rifle.

**Comment by FulcrumA** [comment]
@NotFuji 
>Almost everything is already dependent on RNG. Whether or not you find a running car is pure RNG, tools depend on RNG, finding any gun whatsoever is RNG. What's the point of having a makeshift welder if a player might find a regular one early on?

The fact that makeshift one is still comparable in usefulness. By that you kinda support my point of importance of making those good weapons still balanced against at least some others so they won't be an ultiamte choice straight away.

Yes, tools and whatnot depends on RNG. It's important then that the player won't have some single ultimate thing that may or may not be acquired through RNG but a range of comparable equipment fitting for various situations and which can substitute other pieces of equipment to some degree. It all falls under favoritism as an issue in the game, a thing I've mentioned. 

>Does finding an awl pike or katana early on mean you never have to use a different melee weapon? 

No. You can choose not to but you won't necessarily cripple yourself by choosing some other items. If you're sure it's not the case, maybe awl pike/katana, controversy time, may require nerfing vs weapons of similar complexity.

Awl pikes and similar, while very popular in their own right, aren't ultimate weapons and there are people choosing other equipment, be it due to martial arts or because there are weapons overall roughly as useful, at least under certain circumstances. And so it should be with Barrett.

**Comment by BorkBorkGoesTheCode** [comment]
Since the .50 BMGs usefulness is due to overrides in Experimental Realistic Guns mod and not the Barrett it might be good to discuss it and ammo damage modeling in general.

**Comment by Firestorm01X2** [comment]
Now barret get only increased max range. Accuracy remain the same. It should be good compromise. "Usual" sniper rifle will be still more accurate. Barret- more powerful but less accurate. But at least now usual "sniper" rifle have no advantages by max range as it is IRL.

Ready.

**Comment by Firestorm01X2** [comment]
Jeez. Changes are not needed for range.
Barret ammo has 45 range. Barret itself has 45. And sum give us 90 already.
Closed.

**Pull request closed without merging**
