### PR TITLE
Electric combat chainsaw

### PR DESCRIPTION
**Pull request by Theundyingcode**
```SUMMARY: Content "Adds electric combat chainsaw"```

Twin sibling of #25938

### CODE REVIEW

**Comment by lcy03406** [comment]
You say 'chainsaw', so why not install it on my deathmobo?

**Comment by ZhilkinSerg** [comment]
You've missed two things:

- name of iuse action should be added to `item_actions.json`;
- mapping of iuse action should be mapped to C++-function in `item_factor.cpp`.

I've did this for you in this PR.

**Comment by ZhilkinSerg** [comment]
Also ammo type is `battery`, not `batteries`.

**Comment by ZhilkinSerg** [comment]
Also `electric prefix` was missing in `name_plural` for `_on` version.

**Comment by Theundyingcode** [comment]
thanks

**Pull request merged**
