### PR TITLE
Fix UPS tool charge draw

### LINKED ISSUE #18912: Vehicle repair charge counting doesn't get multiple UPS sources right
Given:
- a welder with a UPS conversion mod and 189 charges, in inventory;
- a UPS with 113 charges, in inventory;
- a UPS bionic, activated, with 646 power available

I can't do a repair on a vehicle that needs 300 welder charges.

The bionic UPS on its own, or the standalone UPS plus welder charges, should be able to cover 300.

### PR DESCRIPTION
**Pull request by epsilon-phase**
Fixes #18912

I'm not sure that this is done correctly, so anyone who knows
the ammo system better should probably weigh in.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That is a special case. Special cases aren't the proper way to fix this: there are still other cases not handled here, like all the other electric tools that are UPS-moddable.

If it is to be fixed correctly, it needs to be addressed in `ammo_required` and family, not in welder special case.

**Comment by jaked122** [comment]
This isn't specific afaik to the welder. The welder was just the most common complaint I have with it.

I don't know if it works with the electric chainsaw. Really I suppose that I ought to check the other saws and things you turn on and off too.

**Comment by jaked122** [comment]
I'm a bit surprised but it seems to work properly on the electric chainsaw for me. It draws as expected from the UPS device, and starts up with zero charge.

**Comment by Coolthulhu** [comment]
You could add the user as an argument to `ammo_sufficient` and family, then check for UPS there.

**Comment by jaked122** [comment]
That's not a bad idea, but I should still have the charge consumption code in the player::consume_charges function, right?


Also, I'm not sure, but it looks like the ammo_sufficient function is called in a bunch of places where it isn't used by the player. I'm not really sure what to do with that.

Should I just add an overload?

I think it might look a  bit like this

```c++
item::ammo_sufficient(player *p, int qty)const{
   if( !has_flag( "USE_UPS")){
       return ammo_sufficient(qty);
   }
   // Other stuff
}
```

**Comment by Coolthulhu** [comment]
> Also, I'm not sure, but it looks like the ammo_sufficient function is called in a bunch of places where it isn't used by the player. I'm not really sure what to do with that.

When no player argument is supplied, it should just ignore the UPS, like now.

It would probably be better to declare the player argument via a reference than a pointer, to avoid casts. As in:
```
bool ammo_sufficient(player &p, int qty) const;
bool ammo_sufficient(int qty) const;
```

Rather than just `bool ammo_sufficient(player *p=nullptr, int qty=1) const;`, which would lead to `ammo_sufficient(1);` being interpreted as `ammo_sufficient((player*)1);` and most likely crash the game.

Later on the player-less option could be left only for items lying on the ground or even changed into `ammo_sufficient( item_location, int )`, with location being mandatory.

**Comment by jaked122** [comment]
> Later on the player-less option could be left only for items lying on the ground or even changed into ammo_sufficient( item_location, int ), with location being mandatory.

That's not in scope for this right now, is it?

**Comment by Coolthulhu** [comment]
Oh wait, it looks like this overload already exists: `item::units_sufficient`. So it should be enough to just use that.

**Comment by jaked122** [comment]
@Coolthulhu I don't know that it does what it needs to though. 

I'm not a template master, but it seems as though it doesn't handle the UPS flag in any manner.

**Comment by Coolthulhu** [comment]
I think just replacing usage of `ammo_remaining` with `units_remaining` (with extra character parameter before quantity) should make it recognize UPS.

Won't make it consume UPS, but should make it count it.

**Comment by Coolthulhu** [comment]
Now that @mugling is back, it would be good for him to comment on this.
Specifically: if replacing `ammo_remaining` with `units_remaining` to handle UPS-modded tools is the proper way to go.

Also, this PR needs a rebase or having master merged onto it.

**Comment by jaked122** [comment]
Yeah, I've got that locally, I'll push it tomorrow.

**Comment by mugling** [comment]
> Now that @mugling is back, it would be good for him to comment on this.

It's somewhat reassuring that a weeks absence was noted. I'll take a look into this

**Comment by Coolthulhu** [comment]
This was assigned for a month.

Is there something wrong with it?

**Comment by mugling** [comment]
I'm not sure if it's the correct solution and there are a lot of UPS bugs open with which this PR could interact. I'll take another look though

**Comment by jaked122** [comment]
@mugling to be honest, neither am I. After I submitted this, something changed, my most recent attempt to fix this seems to work imperfectly.

It works for some things, but it also shows an error message that also shows up on the master branch.

**Comment by kevingranade** [comment]
last comment was that this is broken, any progress?

**Comment by jaked122** [comment]
I'm afraid I don't feel like I don't have Enough time or patience to figure
out how to make it work.

**Pull request closed without merging**
