### PR TITLE
bone spike and bone spear

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "bone spike and bone spear"

#### Purpose of change

Crafting options, realism

#### Describe the solution

Item created by combining characteristics of "bone" and "spike". Can be created by carving a bone. Can be used to make a very basic spear with a bone spike

#### Describe alternatives you've considered

More recipes, may do if there is interest. Add to harvest lists that would have a horn, tooth or other sharp spiky bone of the right size or larger. Zombie variant but it looks like those bones are not considered strong enough for crafting, which is the interest here. Make this by disassembling a bone (snapping on your knee like a long stick). Add to existing spear recipes but it looks like the material definitions make that impossible. Define antler spikes and antler spike items and recipes. A durable recipe and item variant similar to stone spear.

#### Testing

Game loads no errors, items and recipes appear and work as expected

#### Additional context

Inspired by player requests for more tool and weapon crafting in DinoMod that would require this infrastructure to exist

"Bone idol! Bone idol!" - The Drones

### CODE REVIEW

**Comment by AtomicFox556** [comment]
As far as I know, normal bones don't make good weapons or tools as they are too fragile. You'd want to use something like horns or antlers for this; not sure what would be the equivalents of those that come from dinosaurs.

In either case they'd still be inferior to metal weapons and tools, so you'd want weapons and tools made from this material to be different items.

**Comment by Shodan14** [comment]
Shouldn't you craft it? You can't disassembly wood into anything but splinters etc.

**Comment by AtomicFox556** [comment]
> Here is an article about the history of bone spears and their usefulness in murdering large game and modern cars https://www.nationalgeographic.com/science/article/early-hunters-killed-mastodons-with-mastodons-also-you-can-chuck-a-bone-spear-through-a-car-who-knew for those like me who are not very familiar with bone spear history

Well, it'd still be inferior to metal weapons. I'm sure there are reasons why people preferred steel over bone for weapons.

**Comment by Cerberus1746** [comment]
I think it would be interesting to have a separate recipe for bone spike and bone weapons with slightly reduced damage

**Review by kevingranade — CHANGES_REQUESTED** [review]
Need a source that doesn't require a login and that justifies "practically the same damage as stone", which I'm super skeptical of.
In very real terms, bone is only marginally harder than wood and takes a barely better edge, and is *massively* outperformed by stone, which is then incredibly far behind metal, this doesn't reflect that.

**Comment by LyleSY** [comment]
I'm not finding a lot of open access material on this question. I see this stack exchange discussion about relative hardness, showing that bone appears to be harder than metal so presumably should have similar or higher damage https://chemistry.stackexchange.com/questions/55514/which-is-hardest-iron-brass-or-bone
There appears to be agreement that bone can't handle the same kinds of stresses so would need to be replaced more often. My understanding of the physics of piercing weapons ( https://aapt.scitation.org/doi/10.1119/1.1533055 looks promising but of course no open access to anything as mysterious and proprietary as a spear) is that damage is not dictated by the properties of the point so much as the amount of force behind it and how large a surface that force is concentrated into. Many cultures appear to have used them worldwide https://www.gibmuseum.gi/news/solutrean-assegai-bone-spear-point-109 https://gizmodo.com/why-papuan-men-made-daggers-from-human-thigh-bones-1825504685 and across vast time scales. This source suggests that flint is even harder than bone (7 vs 5) so presumably should do even more damage than bone or metal https://www.rockrollers.com/features/hardness.html and importantly would not break as much as bone points. From all of this I take it that there probably shouldn't be a durable bone point option, and the damage should be about halfway between a metal spear (more) and stone (less) but not by much. My sense from researching this is that bone is reasonably effective, but usually persists for cultural reasons or reasons of convenience, not because it is a superior material to metal or stone.

**Comment by LyleSY** [comment]
Closing this for now, happy to take this up again in the future if there is interest. Thanks again to the players who requested this.

**Pull request closed without merging**
