### PR TITLE
Magiclysm mod:  add a magic shop and a hidden cabin

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
 ```SUMMARY: Mods "Adds 2 buildings for Magiclysm, a magic shop and a cabin."```

#### Purpose of change
Give Magiclysm items dedicated places to spawn.

#### Describe the solution
Add a magic shop in the city and a hidden cabin in the woods.  I've added a few basic item groups so the books, wands, and spells can at least spawn.  I expect these will be refined once KorgGent can find time.

This also adds a worldgen folder and the necessary companion files for both specials and multlitile_city_buildings for future contributers.

#### Describe alternatives you've considered
Some more buildings I may add later.
#### Additional context
Magic shop:
(note spawns in screenshots are my placeholder spawns and have been replaced)
magic shop
magic shop 2nd floor
magic shop roof

cabin: (I fixed that bad roof tile!)
magic cabin
magic cabin roof

### CODE REVIEW

**Comment by KorGgenT** [comment]
looks like the json needs to be linted.

**Comment by John-Candlebury** [comment]
But does the magic shop randomly shift between dimensions?

Great content

**Comment by ZhilkinSerg** [comment]
You probably need to add it to region overlay in mod to actually spawn.

**Comment by curstwist** [comment]
> 
> 
> You probably need to add it to region overlay in mod to actually spawn.

Thanks! I made one but it looks like I forgot to include it.  I'll upload it later today.

**Pull request merged**
