### PR TITLE
Extra blackpowder loads, part 1: Pistols

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Add blackpowder loads for pistol cartridges"```
#### Purpose of change

Making use of #30985 by adding more blackpowder cartridges.
#### Describe the solution

Add ammo item entries for blackpowder recipes, crafting recipes for them, and related JSON values to guns of calibers that are involved.
#### Describe alternatives you've considered

Considered doing something about "36paper" and "44paper" ammo (right now they are blackpowder-only already), but couldn't quite figure it out, so for now just added "BLACKPOWDER" effect to them and left them alone otherwise.
Numbers in list below are very rough estimates and guesses, so if anyone actually knows something on the topic of using blackpowder loadings in guns not designed for that, making them more accurate would be helpful.
A few existing blackpowder loads recipes also got tweaked to be reversible and to have the same craft time as other handloading recipes.
#### Additional context

All blackpowder loads have 30% price, 65% damage and recoil, 50% pierce, and 120% dispersion from equivalent smokeless gupowder loads. Overpressure blackpowder loadings also aren't available.

MCR is chosen as 90% of default ammo recoil for guns that in my opinion can't cycle with blackpowder ammo, and as 65% for guns that can. For PPSH, I specifically chose 270 (50%), to allow it to cycle with current subsonic ammunition (no idea if it's actually correct, but it was the "old" behaviour and I didn't change it). For .460 Rowland guns, I assumed .45 ACP as the default caliber, as they are probably designed to fire those much less powerful rounds without any malfunctions as well. 

BT is blackpowder tolerance (if it equals 8, I have absolutely no idea about this gun's blackpowder performance)
MCR is minimum cycle recoil (specified only for autofire-capable guns)

List of affected guns, by caliber:

**.32 ACP:**

SIG Sauer P230: BT 8
Skorpion Vz. 61: BT 8, MCR 135
Walther PPK: BT 8
Kel-Tec P32: BT 8

**.36 paper:**

Colt M1861 Navy: BT 96

**.38 Special:**

2 Shot Special: BT 60 (makeshift gun)
COP .38: BT 96
Pipe rifle: .38 Special: BT 60 (makeshift gun)
Ruger LCR .38: BT 56
Luty SMG: .38 Special: BT 24, MCR 162 (makeshift gun)
S&W 619: BT 56
Taurus Pro .38: BT 8
Model 10 revolver: BT 56 (from Realguns mod)

**.380 ACP:**

MAC-11: BT 8, MCR 270
Kel-Tec P3AT: BT 8
FN 1910 .380: BT 8
Ruger LCP: BT 8

**.40 S&W:**

Glock 22: BT 48
Pipe rifle: .40 S&W: BT 60 (makeshift gun)
SIG Pro .40: BT 8
Luty SMG: .40 S&W: BT 24, MCR 364 (makeshift gun)
Handmade six-shooter: BT 60 (makeshift gun)
S&W 610: BT 56

**.44 Magnum:**

Desert Eagle .44: BT 8
Henry Big Boy .44: BT 32
LeMat revolver: BT 56
Pipe rifle: .44 Magnum: BT 60 (makeshift gun)
Ruger Redhawk: BT 56
S&W 629: BT 56

**.44 paper:**

Colt M1860 Army: BT 96

**.45 ACP:**

TDI Vector: BT 8, MCR 540
H&K UMP45: BT 8, MCR 540
M1911: BT 48
MAC-10: BT 8, MCR 540
Pipe rifle: .45: BT 60 (makeshift gun)
Luty SMG: .45: BT 24, MCR 390 (makeshift gun)
Homemade hand cannon: BT 60 (makeshift gun)
Thompson submachine gun: BT 8, MCR 540
USP .45: BT 48

**.454 Casull:**

Taurus Raging Bull: BT 56
Taurus Raging Judge Magnum: BT 56 (from Realguns mod)

**4.6x30mm:**

H&K MP7A2: BT 8, MCR 81

**.460 Rowland:**

L39-460: BT 8 (fictional gun)
L39B-45: BT 8, MCR 540 (fictional gun)
L2031 Enforcer: BT 56 (fictional gun)
L1820 Long Ranger: BT 32 (fictional gun)

**.500 S&W Magnum:**

Big Horn Model 89: BT 32
S&W 500: BT 56

**5.7x28mm:**

FN Five-Seven: BT 8
FN P90: BT 8, MCR 81

**7.62x25mm:**

PPSh-41: BT 8, MCR 270
Tokarev TT-33: BT 8

**9x18mm:**

Makarov PM: BT 8
Skorpion Vz. 82: BT 8, MCR 270

### CODE REVIEW

**Comment by kevingranade** [comment]
Did you verify that these calibers *have* recommended black powder loadings?
The initial batch were checked for existence of such, but it is not open season on black powder for all calibres.

**Comment by Rail-Runner** [comment]
> Did you verify that these calibers _have_ recommended black powder loadings?
> The initial batch were checked for existence of such, but it is not open season on black powder for all calibres.

Well, something's got to happen if you do that, whatever is the caliber. I may adjust the stats to be even worse if they're suboptimal.

**Comment by kevingranade** [comment]
> Well, something's got to happen if you load any cartridge with blackpowder, whatever is the caliber.

No, it doesn't, it's perfectly reasonable to disallow BP loads for cartridges where it won't work.

> I may adjust the stats to be even worse if they're particularly suboptimal. 

If you want to adjust it such that by default no autoloading actions cycle ever, that would be a reasonable starting point.  Basically anything that's not a pump, bolt, or lever-action or a revolver would jam and require manual cycling every shot.

**Comment by Rail-Runner** [comment]
> If you want to adjust it such that by default no autoloading actions cycle ever, that would be a reasonable starting point. Basically anything that's not a pump, bolt, or lever-action or a revolver would jam and require manual cycling every shot.

It's already the current behaviour for most full-auto guns whenever one tries to fire a burst, though not the default one; if MCR isn't set, it's 0 and gun will cycle just fine; can't provide any other reasonable default as it actually depends on caliber, and if you set it too high, it won't cycle even with standard smokeless loads. This default works fine for manual actions like those you mentioned, though.

Current exceptions to this are PPSh-41 (to allow it to cycle with subsonic smokeless loads which have half the recoil of default ammo; blackpowder loads have 65% recoil for reference, and so will cycle) and Luty SMGs. If either or both exceptions aren't reasonable to have, I'll increase their MCR to 90% of default ammo, therefore not allowing them to cycle with blackpowder loads.

Currently, the fact that a gun may not cycle with blackpowder doesn't really mean anything for semi-auto guns. This is because game currently doesn't require player to spend some time working the manual action on the gun to chamber the next cartridge (and working the bolt on a bolt-action would actually take more time than manually cycling a semi-auto gun's action). I might try implementing that feature in this PR, but semi-auto guns being as quick-firing as bolt-action guns really seems like a separate issue.

**Comment by Rail-Runner** [comment]
I'll update this PR soon, using the coefficients listed in issue above.

For cartridges with projectiles smaller than .30" in diameter, by plan is to further reduce (linearly) damage and recoil by 2.5% for each .01" under .30". The only ammo types present in this PR that would be affected by this are 5.7x28mm (which would get 0.56x damage and recoil) and 4.6x30mm (which would get 0.46x damage and recoil).

**Comment by kevingranade** [comment]
> It's already the current behaviour for most full-auto guns whenever one tries to fire a burst (gun simply stops firing after firing one shot)

This isn't *quite* what I asked for, it should fail to cycle on every shot, requiring the player to cycle the action manually to load a new round in the chamber.  This could just be time folded into the firing action (along with a message telling the player where their time is going) or it can be a jam that requires a separate action to clear.

The current setup AFAICT is that full auto degrades to semi-auto, what I'm looking for is for both full auto and most semi-auto to degrade to "bolt action that jams a lot".

Side note, This discussion should have happened in the previous PR, I got your PR mixed up with stuff that Greev was doing, which was sourced differently.

**Comment by Rail-Runner** [comment]
Updated it. Most blackpowder loads now have 76% damage and recoil of equivalent smokeless loads, and 50% more blackpowder charges (couldn't count the extra 1% as our charges aren't granular enough), and most full-auto and semi-auto guns now need manual cycling while firing blackpowder loads, each one wasting 50 moves (half a second currently; I may adjust it to be higher/lower if necessary). Cycling happens automatically as player attempts to fire a gun, to prevent it from becoming tedious, or can be done manually via mending a respective fault.

As exceptions due to their small size (and reliance on high projectile speed that can't be provided by blackpowder), 4.6x30mm and 5.7x28mm loads have 46% and 56% recoil/damage coefficients, respectively.

**Comment by Throwaway-name** [comment]
The reloaded PDW cartridges (original and black powder) shouldn't have high armor-piercing ability.

**Comment by Rail-Runner** [comment]
> The reloaded PDW cartridges (original and black powder) shouldn't have high armor-piercing ability.

It's halved right now for blackpowder cartridges and not changed for reloaded ones. What multipliers do you think would be better?

**Comment by Throwaway-name** [comment]
0.1 and 0.2. Both recipes use pure lead and lack any armor-piercing component. I might be wrong about the importance of steel/aluminum cores in the piercing process; @tenmillimaster what do you think?

**Comment by Rail-Runner** [comment]
Done, they have much less armor penetration now than normal loads. Maybe I'll implement proper versions which use actual penetrator projectiles at some point, but not in this PR.

**Comment by NeviNovat** [comment]
I think that an important detail has been missed. I've looked through this PR and #31553 and I see that BP loads will end up not being 1.5x the mass of smokeless powder, because 6 units of smokeless =/= 6 units of BP by weight in-game:

The_diffff

As seen in the screen-shot 10.000 units of smokeless weighs 10kg but 10.000 units of BP weighs 50kg not to mention the volume disparity.

I mention this because looking at the code a change that has been done was increasing BP by roughly 1.5x ( an example is "bp_454_Casull" that is now modified from 6 to 9 ). I think that if we want to have BP loads of the same casing we need to standardize the items used either we use volume or weight, but weight is used here so I think i'll open a pull request soon ( and put it here, I am new to github this might take a while ) not only because of this PR but I want to work out the crafting recipe of craftable explosives as noted in #32275 and #32274 to make more sense.

**Comment by Rail-Runner** [comment]
> I think that an important detail has been missed. I've looked through this PR and #31553 and I see that BP loads will end up not being 1.5x the mass of smokeless powder, because 6 units of smokeless =/= 6 units of BP by weight in-game

The real problem here is that powder (both smokeless powder and blackpowder) should be measured in units weighing less than gram, and that currently is impossible. I think the cartridge weight increase if using blackpowder instead of smokeless gunpowder would be approximately on the same scale anyway, for most cartridges.

**Comment by tenmillimaster** [comment]
The specialty cores is pretty much all the magic in those cartridges, yes. Otherwise they perform like very hot 22LR (.22 WMR)

**Comment by Rail-Runner** [comment]
This is done ready for merging, by the way.

**Comment by kevingranade** [comment]
When I spot checked a few guns they were cycling normally when I expected them to be failing to cycle regularly, and the relationship between recoil and cycling and loads etc is a bit more involved than I've had attention to spare to untangle it, so I haven't gotten around to figuring out what the problem is.

In other words, I provided this feedback https://github.com/CleverRaven/Cataclysm-DDA/pull/31485#issuecomment-502868211 and there's either a bug or you decided to not do what I asked.

**Comment by Rail-Runner** [comment]
Must be a bug, I'll investigate it.

**Comment by Rail-Runner** [comment]
Bugs fixed, everything is now working as intended.

**Pull request merged**
