### PR TITLE
Add spell "Heal Fatigue" 2/3

### PR DESCRIPTION
**Pull request by KymasTuran**
#### Summary
Mods "Add spell Heal Fatigue from Magiclysm . File 2/3. Both with linting."

#### Purpose of change
New spell

#### Describe the solution
This

#### Describe alternatives you've considered
Mentioned in the other file

#### Testing
Mentioned in the other file

### CODE REVIEW

**Comment by Fris0uman** [comment]
duplicate of #61935

**Comment by GuardianDll** [comment]
It was not a duplicate, used don't know how to use github, and decided to aplit change on 3 separate PR

**Comment by GuardianDll** [comment]
also, due the #61406 merge, this pr probably has some merge conflicts
if you're interested, i can add this thing for myself, propely and clear

**Comment by Fris0uman** [comment]
Yes, this is a bad way to submit change, they should close the extra PR, and just add the change in the same one.  Here's the link to the dev discord server https://discord.gg/jFEc7Yp to get help on doing that

**Comment by KymasTuran** [comment]
> also, due the #61406 merge, this pr probably has some merge conflicts if you're interested, i can add this thing for myself, propely and clear

Yes! Please. I probably dont use github again. With my old pc the first change I upload was 2 hours of time. And it was just a "-" a "minus".

**Comment by KymasTuran** [comment]
> Yes, this is a bad way to submit change, they should close the extra PR, and just add the change in the same one. Here's the link to the dev discord server https://discord.gg/jFEc7Yp to get help on doing that

I know is not right but at least I upload these in a way that dont cause errors, in the right order. 
Every time I try to upload the changes github want to merge all the files or just one, also each action  takes a lot of time because my pc is too old for this site. I dont upload anymore here. 
I try luck in discord maybe someone want to upload for me.

**Pull request closed without merging**
