### PR TITLE
Improve transparency and seen caching

### PR DESCRIPTION
**Pull request by Aivean**
#### Summary

SUMMARY: Performance "Improve transparency caching"

#### Purpose of change

Alternative approach to the #44074. 
The goal is to improve performance of the transparency cache building.

#### Describe the solution

The main idea is to make `level_cache::transparency_cache_dirty` flag more granular, specifically, submap granular. When it's possible to trace transparency change to a single tile/submap, invalidate transparency for that submap instead of invalidation of the whole cache.

This is a relatively large change that touches several related areas:
* transparency cache
* "seen" cache 
* fields processing

Transparency cache building overhead is noticeable only when character is performing long tasks and by far the biggest source of single point cache invalidations in this case comes from various fields. 

That's why I had to make some changes in field processing logic. Specifically, I changed transparency (and "seen") cache invalidation to point-based when fields are added and removed from the map. To do this I had to replace all calls to `maptile::add_field` with `map::add_field` (which now contains point-based cache invalidation).

I've also improved and fixed seen cache invalidation (expanding on Kevin's idea). Details are too long to list here, but basically there was a bug with cache invalidation and also current z-level invalidation was triggered by changes in other levels.

#### Describe alternatives you've considered

One alternative is #44074.  Another alternative is to make transparency cache even more granular (tile level) and/or calculate it on demand.

#### Testing

Manually checked the following and more:
* fields spreading works as intended and consistent with previous builds (fire, smoke, gas)
* cache invalidation triggers when expected (moving, fields, z-level change, vehicles, remote controlled vehicles)
* transparency works as expected in general (also see #44112 for the fixes of some transparency-related issues that I've uncovered)

#### Additional context

This PR adds minor overhead to the gas and fire spreading (as `map::add_field` is bit more expensive), but as profiling shows it's negligible.

See comments below for the profiling results.

### CODE REVIEW

**Comment by Aivean** [comment]
Here are some profiling results. Unfortunately, there is no "before", as the bug in seen cache skews the results.

Here are two "after". 
First one is near outside the hotel building near the smoke vents (constantly changing smoke in sight):
image

Second one is inside the small dark room in the same hotel, with lots smoke outside the room (not in sight):
image

Notice, that `map::build_map_cache`, that includes seen and transparency cache is relatively small.

I'll post the "before" results with the older build tomorrow.

**Comment by Aivean** [comment]
Profiling results.  
Scenario: high-rise hotel with the smoke vents on multiple floors. Character is waiting for six hours, I'm profiling 30 real-time seconds of that.

Here, the [the character is outside](https://user-images.githubusercontent.com/2865203/92769116-80f82980-f34d-11ea-9c98-2c4103dc41a3.png), smoke fields are in the view.


Before (build dcf31cddbd2164c773af713c1244e57fda412b90):
image

After:
image

**Comment by Aivean** [comment]
Scenario №2, same hotel, [the character in inside the dark room](https://user-images.githubusercontent.com/2865203/92769850-39be6880-f34e-11ea-99be-038c9e872fb4.png), smoke is not in the view.

Before:
image

After:
image

**Comment by Aivean** [comment]
Fixed minor bug when changes seen only thorough mirrors/camera did not invalidate "seen cache".

**Comment by Aivean** [comment]
I finished the testing. I believe this PR is ready to go.

**Comment by jbytheway** [comment]
Can you add any unit tests?  We have infrastructure in `tests/vision_test.cpp` intended to make such tests easier.  They only apply for static situations, but the hiding-avaters-tile-in-smoke bug might be testable (you'd have to add some support for spawning fields in the test).

**Comment by Aivean** [comment]
> Can you add any unit tests? We have infrastructure in `tests/vision_test.cpp` intended to make such tests easier. They only apply for static situations, but the hiding-avaters-tile-in-smoke bug might be testable (you'd have to add some support for spawning fields in the test).

Sure, I can do that. "Hiding in smoke" is definitely testable, it reliable happened when character stand on non-transparent tile and all 8 neighbors were also non-transparent tiles (so this was also happening with, for example, wall, it's just you don't often stand inside walls).

**Comment by jbytheway** [comment]
Cool.  For the purposes of the test it may be easier to have the avatar in a wall than add support for fields to the test.

**Comment by kevingranade** [comment]
I'm a *teensy* bit concerned about replacing the maptile indirection, IIRC that was specifically added as an optimization to avoid excessive bounds checking.  I need to dig through some history and find the case that it was added for.

**Comment by Aivean** [comment]
> I'm a _teensy_ bit concerned about replacing the maptile indirection, IIRC that was specifically added as an optimization to avoid excessive bounds checking. I need to dig through some history and find the case that it was added for.

This is a valid concern.
I've thought about that myself and came up with two considerations that alleviate that concern.

1. Most of the `add_field` cases that I've replaced happen after direct search for the field in the corresponding maptile (at least inside `spread_gas`). This means that longer direct route takes place only for cases when fields did not previously exist, i.e. on the perimeter of the gas cloud. And the perimeter is much smaller compared to the area of the gas field, where most of the work happens.

2. Profiling that I've done (copied from the comment above) shows negligible performance impact in the case of gas spreading. Note, that `process_items` and `process_fields` take approximately the same % of the turn time before and after.
Before
image
After
image


Now, this is true for gas spreading. I will need to also check the performance of the fire spreading.

**Comment by Aivean** [comment]
As an alternative, I can add overloaded `add_field` method that takes in `maptile` instead of the point and skips bounds checking. However, to do that I'd need to add "submap coords within a map"  to a `maptile` (it currently has only local point coords within corresponding submap). 

@kevingranade , are there any objections to that?

**Comment by Aivean** [comment]
I've profiled the fire spreading case (set ≈one submap of forest on fire and fast-forwarded time):
image

`add_field` is definitely not a bottleneck.

**Comment by kevingranade** [comment]
Ok cool, consider my concerns alleviated.

**Pull request merged**
