### PR TITLE
Fixes trying to use null armor data on sort screen

### LINKED ISSUE #64058: CTD upon opening "Sort Armor menu"
### Describe the bug

Trying to use the armor sorting menu in this current version crashes the game directly to desktop.

### Attach save file

[Hellertown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10917936/Hellertown.zip)

### Steps to reproduce

Opening the Armor sort menu.

### Expected behavior

Not crashing upon opening the Armor sort menu

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 650f9ae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10917996/debug.log)

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
fixes #64058

#### Describe the solution
added checks for not having armor data at all

#### Testing
Still compiling to test

#### Additional context
image

### CODE REVIEW

**Comment by NetSysFire** [comment]
Maybe a backport candidate?

**Comment by bombasticSlacks** [comment]
#64006 would need backported too, but it probably should be the old UI was just returning junk!

**Comment by adamkad1** [comment]
Not to be rude, but between what's this fixing and the insert CTD, there should be more testing for potentially relevant things with pr's like #64006 or #63873 , and not just the thing that was changed. Code is a fickle beast.

**Comment by bombasticSlacks** [comment]
Not rude at all, we'll gladly accept any test cases you want to add 😄

**Comment by adamkad1** [comment]
> Not rude at all, we'll gladly accept any test cases you want to add 😄

Related things so like, if changing categories/inventories, make sure items and other inventories work properly, and generally a quick sweep of basic game functions when something is more serious than changing a single ingredient in a recipe or such. Unless thats not what you meant by cases?

**Comment by esotericist** [comment]
@adamkad1 
slacks meant automated test cases. if you mean "check all of these interactions manually every time", that's going to be rather difficult, and part of the expectation of experimental is discover things that got overlooked in the PR development.

remember, experimental has no promise of playability, things break, that's life.

**Pull request merged**
