### PR TITLE
Thigh protectors, more vest modularity, and light vest disassembly.

### PR DESCRIPTION
**Pull request by epebe**
#### Summary
Content "Ballistic thigh protectors, shoulder attachments for more vests, fix light vest disassembly."

#### Purpose of change

Add ballistic thigh protection and allow shoulder protector attachment to other vests.

In #71376 it was mentioned that light ballistic vests disassemble into synthetic cloth despite having ballistic kevlar in the armor data. When light vests were added in #52361, they were nylon only, and when ballistic kevlar was added to them in #56302, the disassembly recipe wasn't updated.

#### Describe the solution

Add ballistic thigh protectors and pockets to attach them on US vest. Add pockets for shoulder protectors on the other vests too.

Add ballistic kevlar to light vest's materials and add ballistic kevlar panels to their disassembly recipe. I used a proportion of the US vest disassembly based on the ratio of nylon.

Also reduced shoulder protectors' encumbrance, because 5 is a bit much when lower arm armor has around 2-4 encumbrance.

#### Describe alternatives you've considered

Leave vests as they are.

#### Testing

Spawn kevlar zombies, kill them, and find occasional thigh protectors dropped too. Disassemble light vests and see ballistic kevlar as a result.

#### Additional context
Armor values were taken from #62981.

### CODE REVIEW

**Comment by Hyperseeker** [comment]
FYI: no US military ballistic vest has thigh protectors as a component. The best you get with standard issue is groin protectors, which we already have, and the BPP. Starting with the former:

Most modern ballistic vests are not designed to be used with shoulder/deltoid protectors. The IOTV (previous generation of US Army vests) can have a pair because it was specifically designed to for it. By contrast, the SPCS (current-issue vests in the Army) are not nearly wide-enough to have the straps be a viable base for the protectors:

https://arborarmsusa.com/wp-content/uploads/2021/12/SPCS_On-Soldier_Front-Oblique-Right_Taktic_Color-Pop.webp

Nor are they supplied with a different set of protectors for the shoulder area. This is similarly the case with other contemporary vests in the Army or the Navy (e.g. the Marine Corps Plate Carrier), as well as many other aftermarket options. In fact, I would wager that damn near every single one of those carriers that provide thigh protectors have their own, proprietary systems for attaching them. This means, of course, that you can't simply strap a thigh protector onto any other plate carrier.

Even if you could, the IOTV doesn't come with one, so naming it `iotv_groin_plate` is misleading. "IOTV" is not a generic name: it refers to [a specific design](https://en.wikipedia.org/wiki/Improved_Outer_Tactical_Vest), with [known features](https://ciehub.info/spec/PD/FQ-PD-07-05G.pdf) which, to my knowledge, have not been augmented by aftermarket options.

If you want to implement thigh protectors, realistically, you should implement a plate carrier that can have those attached. The commercial section of the market is full of options.

Alternatively, you should implement the [Blast Pelvic Protector](https://www.armorexpress.com/product/blast-pelvic-protector-bpp/): a [standalone](https://govtribe.com/opportunity/federal-contract-opportunity/blast-pelvic-protector-bpp-request-for-information-rfi-w91crb21rbpp) (i.e., worn separately) ballistic apparel designed to protect against fragmentation. It's essentially the Army's second attempt at groin protection after the IOTV ballistic flap; it's augmented by [frag-resistant underwear](https://www.army.mil/article/74306/kevlar_underpants_protect_pelvic_region), but seems to have meant to provide a significant level of protection on its own. The Armor Express listing says it should protect against fragments *and* 9mm, which is not intended by the contract which produced it, but (1) multiple sources state it, (2) in-game, ballistic and fragmentation protection are the same thing – or so I'm led to believe – so giving protection from one would automatically give protection from the other.

Alternatively (take two), if your goal is to enhance modularity of the existing armor, the IOTV still has [collar/neck protector](https://ciehub.info/equipment/protective/IBA/IOTV/YokeCollarAssembly.html) and [lower-back protector](https://ciehub.info/equipment/protective/IBA/IOTV/LowerBackProtector.html) unimplemented. Again, to my knowledge, these are IOTV-only pieces. Even though the "US ballistic vest" was implies to be the IOTV, it likely isn't, as I've argued in [my own armor mod](https://github.com/FrontierMods/Armory/blob/ca33a89bee5196eed0d1c1f5fba550678cf1b2d8/json/items/override/armor/carriers.json#L285). Still, if those are the things you add, you add them to that vest.

I don't decide anything in this game, so you're free to do what you want until someone from the core dev team stops you. Still, I've done plenty of research into ballistic armors and other tactical gear over the course of my modding for this game. Correct me if I'm wrong, but I don't believe the current approach for this PR works.

**Comment by epebe** [comment]
No, you're absolutely right. I came into this without researching anything (my bad) and was planning to piggyback off existing json entries. Thanks for notifying me.

**Comment by Kantonine** [comment]
hmmm, what about having the thigh protectors as a seperate wearable item? ive seen pics floating about with them available, and I don't think it would be too hard to justify having it be part of the paramilitary/survivor zombie drop group. Looking at the notes for the ballistic vest, it says its based off of the USMC Modular Tactical Vest, *not* the IOTV, which excludes shoulder and upper arm protection entirely, and has a diffent groin protector as well!  Id rather say that the vest is atleast *somewhat* ambiguous when it comes down to what should and shouldnt be attachable, especially when we really cant make our minds up on what its supposed to be in the first place
Is it a IOTV? then the current state of it is perfectly fine
Is it a Marine MTV? then there shouldnt be shoulder protectors that can attach to it.
Is it a Hodge-Podge between the two? then at least some liberties should be considered when it comes to that, regarding the less extensive accessory armor pieces

**Comment by epebe** [comment]
Yeah, there are discrepancies in the US vest data. The US vest right now weights 2900g, which is closer to the SPCS than the IOTV or the MTV. I'm currently trying to change the weight values to match the IOTV data.

Alternatively, I could readd the heavy vest and move the iotv plates back, then change the US vest to the SPCS. The lower body coverage would have to be reduced though: I see in pictures it ends at about elbow height, so it shouldn't have 100% coverage down there. The IOTV shouldn't either, but I'm going to say the lower back protector adds extra coverage.

**Comment by Kantonine** [comment]
> Yeah, there are discrepancies in the US vest data. The US vest right now weights 2900g, which is closer to the SPCS than the IOTV or the MTV. I'm currently trying to change the weight values to match the IOTV data.
> 
> Alternatively, I could readd the heavy vest and move the iotv plates back, then change the US vest to the SPCS. The lower body coverage would have to be reduced though: I see in pictures it ends at about elbow height, so it shouldn't have 100% coverage down there. The IOTV shouldn't either, but I'm going to say the lower back protector adds extra coverage.

That could work! the vests are already in a pretty odd spot with how the esbi plates are the only way to have lower body protection, so it gives a good reason to grab the lower back protecor to cover up a weakzone, and still keep it kosher with realistic portrayal, same with the neck and nape protection, because idrk about how the some of the coverage system works, and if some sublimbs are really more intended for Mic./Utility Wearables like whistles and such, would like more info on that

I know belts are in a odd area, (which miiight solve the ballitstic thigh protection issue if you make either a ablative slot on molle belts to have thigh protection coupled with, or a seperate belt and thigh items entirely) with belts now being worn as a overbelt, which in the case of MOLLE belts, technically conflicts with what the game tells you when you check armor coverage, as the belt is worn directly in the middle of your Lower Torso, at the same spot as fanny packs and deployment bags, or in the shared space when Ballistic vests have molle attachements

**Pull request closed without merging**
