### PR TITLE
Craftable Gold Crown is now SUPER_FANCY

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Bugfixes "What it says on the tin"

#### Purpose of change
It’s a freakin’ solid gold crown, what is there to explain?

### CODE REVIEW

**Comment by Brambor** [comment]
Could a copy-from be used? It has a different postapoc price than a gold crown for some reason...

**Comment by XygenSS** [comment]
the summary line can't be "what it says on the tin" because people who only read changelog has no context (the PR title is only visible here)

**Comment by kevingranade** [comment]
Too silly,  no thanks.

**Comment by Brambor** [comment]
> Too silly, no thanks.

The idea or the PR presentation?

**Pull request closed without merging**
