### PR TITLE
Nailboard, 2-by-sword, nord, crude sword adjustments + fixes

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
None

#### Purpose of change

The volumes of the 2-by-sword and derivative weapons were low in comparison to other weapons and the to-hit calculations for them and the nailboard were off as well.

#### Describe the solution

For the nailboard, it went from "solid" to "none" grip (as it doesn't have a handle, so the same as a plank), from "any" to "line" attack surface (as it's used as an example for a line-of-attack weapon), and from "good" to "neutral" balance (since it's just a plank you hammered nails into one end of). This makes it _significantly_ worse as a weapon, and it wasn't even that good to begin with, but it is literally just half a plank with six nails in it you're swinging width-ways like a paddle, so it being unbearably awkward and kinda terrible makes sense. I even gave it a small damage buff from 10 -> 12 to compensate but there's no saving it as a mace, really. I also got a bit distracted by the bikeshed and fiddled with its mass and length to better represent just being half a plank with 6 whole nails in it, as well as removing the stick as a viable option for the recipe since that wouldn't really be a nail _board_ at that point. I also fixed the weights of the trap as well. Was it necessary to make this minor adjustment? No, I just have ADHD. O_o

The 2-by-sword and derivatives had their volumes adjusted, since they were roughly as long as an arming sword and presumably thicker so there's some heft to them still. As such their volumes were raised to be a bit higher than the arming sword's, which makes them a bit slower per swing as well, but the 2-by-sword is still a decent upgrade over other fab 0 options, especially since it requires the somewhat rarer wood sawing 1 instead of just cutting 1. The 2-by-sword's to-hit was also adjusted from "line" to "any" (since it's still a bludgeon so coldcocking at an angle is still a solid hit) but the weight was changed from "good" to "neutral" since it's still just a plank. In the end, it's the same as it was before, basically.

The nord's to-hit was similary updated, going from a "weapon" grip to "solid" to match the 2-by-sword, but going from "uneven" back to "neutral" balance because 12 nails barely weighs anything. Which also means the to-hit in the end is the same anyway. I also gave the nord "fragile_melee" for the same reason the nail bat loses "durable_melee" in that the nails introduce structural weakness and hitting an enemy with a nail at an awkward angle is a great way to split the wood.

Lastly, the crude sword (which was the reason I went into this rabbit hole) had its angle of attack changed from being erroneously "every" to "line," as it is using a sharp edge (even if a crappy one) and isn't really a jagged tearing like the nord. This nerfs its to-hit substantially, but it's still overall the best of the 2-by-sword upgrades and is still very easy to craft regardless.

#### Describe alternatives you've considered

Not doing this. Maybe making a nailed version of the wooden clubs.

#### Testing

Game still functions with these changes, crude sword out-dps's the nord but the nord is easier to use due to much higher to-hit, both out-dps the 2-by-sword which still out-dps's the wooden club; all seems fine to me there.

#### Additional context

I apologize for the bikeshedding, I went in to fix the "every" crude sword attack angle thing and accidentally got distracted by other minor issues.

### CODE REVIEW

**Comment by Shodan14** [comment]
Appreciate the in-depth arguments. Can't disagree with anything here.

**Comment by Drew4484** [comment]
It might be good to change the metal to budget steel, reflecting the shoddy nature of these weapons. I made a component group "mixed_steel" that accepts any kind of steel as a construction option, the scrap armor uses this to represent a mix of whatever metal the player can acquire.

**Comment by Aerin-of-the-Toast** [comment]
> It might be good to change the metal to budget steel, reflecting the shoddy nature of these weapons. I made a component group "mixed_steel" that accepts any kind of steel as a construction option, the scrap armor uses this to represent a mix of whatever metal the player can acquire.

I didn't even notice that the crude sword was only considered "wood," good catch. I added budget steel as a material for it and gave it nonconductive so you wouldn't get electrocuted through the wood.

> I would like to disagree with the volumes but... You are right, they should be more bulkier, the bad thing with this change is that they no longer fit in a normal scabbard, could you at least add the BELT_CLIP flag to the 2-by-sword? It's basically a club so it should be able to be clipped without much problems.

Good idea. They're all likely too thick to fit in a sheath meant for swords anyway, so I just gave belt_clip to all 3. (The nord didn't fit in a sheath regardless for obvious reasons but now it can be clipped as well)

**Comment by TheShadowFerret** [comment]
>Maybe making a nailed version of the wooden clubs.

Please? 

image

**Comment by Termineitor244** [comment]
> Good idea. They're all likely too thick to fit in a sheath meant for swords anyway, so I just gave belt_clip to all 3. (The nord didn't fit in a sheath regardless for obvious reasons but now it can be clipped as well)

I suggest adding back the SHEATH_SWORD flag, since they (except for the nord) still can be put in a back scabbard (I do not use them, but every player plays differently).

**Pull request merged**
