### PR TITLE
Tidy up ammo

### PR DESCRIPTION
**Pull request by bkentel**
- clean up includes.
- move the static map out of the header and use an unordered_map instead.
- add a check for duplicate ammo definitions.
- return and take as param a const ref and not a copy.
- make more of the interface private and expose via friendship.

### CODE REVIEW

**Comment by BevapDin** [comment]
Why this cumbersome load from json, why not simply:
```C++
auto const id = jo.get_string( "id" );
auto &new_type =  all_ammunition_types()[id];
new_type.id = id;
new_type.member1 = jo.get_string( "member1", default_member1 );
new_type.member2 = jo.get_string( "member2", default_member2 );
```
This allows easy addition of more members (without fiddling those into the constructor, one step less to do).

It also establishes a clean and obvious connection between json and the class members and their default values (if any). Btw. (does not apply here) that's why I would list the default values there explicitly instead of taking the from the in-class initialization.

A reader can easily see "If I leave out 'member1' in the json data, it will have the value default_member1, that's what I want anyway." or "I know, I need to set member2 to X, but what json do I need to change to do that?"

**Comment by bkentel** [comment]
@BevapDin I was debating whether to change it or not, and in retrospect I think the way you suggest is best for readability and clarity -- all the more so since performance isn't really an issue here.

**Comment by bkentel** [comment]
What about the check for duplicates? Do you think it's worthwhile to leave in?

**Comment by BevapDin** [comment]
> What about the check for duplicates? Do you think it's worthwhile to leave in?

I was torn on that, but it is good and should stay. It would only affect modding, but ammo types that are not used (because the mod removed all items that would use them) are invisible anyway and I see no reason why a mod would want to override the ammo types properties.

**Comment by BevapDin** [comment]
> I see no reason why a mod would want to override the ammo types properties.

Seems I was wrong. The Vehicle Additions Pack sets the name of the ammo type "modified mininuke" (as it appears in the mainline) to "heavy projectiles". That triggered the debug message reported in https://github.com/CleverRaven/Cataclysm-DDA/pull/11821#issuecomment-87300315. I guess it should be allowed to override ammo types.

Alternatively, one could remove the ammunition_type entry `mininuke_mod` in data/mods/blazemod/blaze_ammo_t.json to prevent the message.

**Pull request merged**
