### PR TITLE
Rashguard combo armor

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Content "Armored Rashguard Shirt"

#### Purpose of change
I wanted an early-game armor that could fit on the normal layer.

#### Describe the solution
Armored rashguard shirt - take a rashguard shirt, cut up some parts of leather clothing, and sew/tape them onto the shirt after tightening the fit a little bit to compress it down. Does not cover the joints, because those are where most of the difficulty of leather comes from. It is NOT sturdy since its components are not sturdy and it's more or less a crude, fast craft of putting some clothing together. You can also just make the torso armor, just make the sleeves, or cut up the armor into both components. Sleeves only cover 50% of the shoulders when detached from the armor, so it's no longer total coverage.
Total thickness of armor is 2.5mm which should be reasonable for a normal layer gear. All the pockets have been removed also, it is purely armor.

#### Describe alternatives you've considered
Don't do this. Different encumbrance. Different craft requirements.

#### Testing
Tried this in game, recipes look ok, armors look OK when created.

#### Additional context

armored rashguard
rashcraft

### CODE REVIEW

**Comment by AtomicFox556** [comment]
I think making use of overly specific components for such a recipe isn't particularly helpful if you want it to be available early game, unless someone just gets lucky with finding those exact pieces of clothing.

I imagine you could at least allow using generic leather patches instead of leather clothing for this purpose, and probably also add a recipe for sewing together an unmodified rashguard, so that this armor can be built from scratch if deemed useful.

**Comment by anoobindisguise** [comment]
> I think making use of overly specific components for such a recipe isn't particularly helpful if you want it to be available early game, unless someone just gets lucky with finding those exact pieces of clothing.
> 
> I imagine you could at least allow using generic leather patches instead of leather clothing for this purpose and using glue instead of duct tape, and probably also add a recipe for sewing together an unmodified rashguard, so that this armor can be built from scratch if deemed useful.

If you were building it from scratch, you'd make something better. The goal here is to take easily available early components and combine them in a semi-efficient manner. You craft it quickly and with a low skill requirement because all the hard work has already been done for you. Also, I would typically have these components within an hour of starting the game if not 10 minutes, they are very common. The awl is the hardest thing to find. I also am not using other kinds of materials because the jackets, dusters and trenchcoats are all 1.5mm which directly translates into their values on the resulting craft, if I included more variable leather types it would massively complicate the recipe. The Nomad Jumpsuit is what you're looking for based on what you're saying here.

**Comment by RelMayers** [comment]
Wearing "shirt" made out of trench coat under trench coat would still probably feel like trench coat.

**Comment by kevingranade** [comment]
Rashguards are singularly bad for modification, much less into armor.  Lycra is notoriously difficult to work with in the first place, and these things are so light they have essentially no structural integrity.

If you want to make a tough piece of clothing, start with a reasonably tough article of clothing to modify.

**Pull request closed without merging**
