### PR TITLE
WIP [ Magiclysm ] Add no_trade flag to unique cloak

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
SUMMARY: None
cloak of no trade

### CODE REVIEW

**Comment by Maleclypse** [comment]
@esotericist I think I've misunderstood how to use the flag.  The NPC was wearing it and traded it straight away as seen in the picture above.

**Comment by kevingranade** [comment]
Or I screwed up when I "refactored" it to shut clang-tidy up, I'll take a look.

**Comment by esotericist** [comment]
Yeah, #42294  is missing a pair of parens. (And I personally found it much harder to read, took me a bit of staring)

**Comment by kevingranade** [comment]
IDK what's going on, when I tested in a debugger it looked like the flag check was returning true, but it didn't end up even calling is_worn().

**Comment by esotericist** [comment]
near as i can tell the actual problem is in `npc_trading::init_buying()` https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npctrade.cpp#L144

it looks like it checks to see if the NPC wants to buy *or* sell that item, and `wants_to_buy()` is pretty much a stub.

unfortunately, i think fixing this is going to require a substantial refactoring of how NPC trading is initialized; it looks like it's a pretty blind globbing of nearby stuff, and it figures out which list to put it in after the fact.

**Comment by esotericist** [comment]
on an additional note, there's a separate bug that causes it to sometimes fail to evaluate some items for trade at all, but i wasn't able to pin down what causes this. i suspect it would either be resolved or at least surfaced in a refactoring.

**Pull request merged**
