### PR TITLE
Jewelry Rework

### PR DESCRIPTION
**Pull request by bandti45**
**Summary** 
```SUMMARY: Balance "Adjusting jewelry skill requirements to closer match other recipes of similar dificulty"```

**Purpose of change**
Allows both the book "Antique Adornments" to increase your fabrication skill and the crafting of jewelry at a lower skill since its not a difficult task with the proper tools.

**Describe alternatives you've considered**
Just lowering the minimum skill to 5 to allow you to learn from "Antique Adornments".

### CODE REVIEW

**Comment by Mecares** [comment]
It was intentional that the book contains the recipes only and is not for skill training, since it is not meant to be a text book describing the techniques how to craft them but a collection of pictures that allows to reverse engineer the recipes if you are skilled enough.

**Comment by bandti45** [comment]
If that's all its for the book should be removed because the majority of people understand how rings and necklaces look, they are definitely common enough, and the recipes should be auto-learned at fab 6.
I am willing to do this change if that is preferred

**Comment by FuelType-Memes** [comment]
> 
> 
> If that's all its for the book should be removed because the majority of people understand how rings and necklaces look, they are definitely common enough, and the recipes should be auto-learned at fab 6.
> I am willing to do this change if that is preferred

Maybe people can come up with simple designs, but something more intricate requires a reference/inspiration

Why not make the book contain more "complex" designs, while making simple rings/necklaces autolearn?

**Comment by bandti45** [comment]
Unless some items can give different joy amounts to stylish characters than others there is no point to having multiple gold and silver rings

**Comment by Mecares** [comment]
It may not be necessary from a pure minmax gameplay point of view but it is realistic and does offer some role play opportunities.

**Comment by I-am-Erk** [comment]
Gold and silversmithing is typically a postgraduate level course in universities teaching metalworking, and in earlier times was an advanced apprenticeship. I don't see anything suggesting it's a simple skill.

Learning designs and how to implement them is certainly not trivial, especially if the working itself isn't. I don't think anyone should simply autolearn goldsmithing because they reached fabrication level 6.

**Comment by bandti45** [comment]
After looking through the other recipes that require fabrication 6 more I have to agree with keeping the recipes at fab 6 but here are two videos showing people actually working with jewelry, both videos show it in very different aspects 
https://www.youtube.com/watch?v=xDE4vZkF_sw
https://www.youtube.com/watch?v=4VSqrP_1mhY

>  I don't see anything suggesting it's a simple skill.
I didn't say it was simply because I understand that forging anything isn't simple, but I did say it was not difficult based on smithing things of higher fabrication levels like swords that need more techniques and understanding of the metal and how to work it than making a band out of malleable metal. Gold is much easier to work and mold then iron and steel making it easier to make the same things out of it. and this line of thinking made me feel that fab 6 is higher than what the skill should be

Also, I always picture the gold and silver rings as plain gold and silver rings is that not the case in the game? If it is then you shouldn't need a book to understand the shape of a ring and how chains link together by fabrication 6

**Comment by bandti45** [comment]
Is there any interest in removing the book or adding better versions of the rings and necklaces through the book (i was able to find a super fancy tag I could apply to them). If not I will close this PR.

**Comment by kevingranade** [comment]
There is no interest in removing the book, your reasoning about items with no utility needing removal does not match project direction.

**Pull request closed without merging**
