### PR TITLE
Coins and banknotes overhaul

### PR DESCRIPTION
**Pull request by chaohedgehogs**
#### Summary
Content "coins and banknotes overhauled"

#### Purpose of change
Coins and banknotes were too rare, both in quantity and spawn location, preventing the player from hoarding them for RP puposes. Initially began as a means of disassembling the money bundle, then snowballed into an overhaul.

#### Describe the solution
- Missing US coins and banknotes added.
- Individual currency items (coins/banknotes/merch/denarii) are now ammo_types, allowing the player to hoard them without lag/tile item limit problems.
- Banknotes/Merch can now be combined into currency straps (100 notes+1 paper), which in turn can be combined into currency bundles (10 currency straps+2 rubber bands/strings), quantity and colour in line with American Bankers Association standards. These straps/bundles are standard items, rather than containers/ammo_types, allowing them to be burned/hoarded without issues.
- Coin wrapper item added, functions the same as a magazine. Can hold 20-50 US coins, with the quantity allowed for each type in line with Federal Reserve coin rolls issued to banks.
- Wallets now spawn with more money in them, with distribution of coinage based on the circulating coin production for 2019, and banknotes based on circulation for 2020 (with $100 notes excluded to avoid skewing contents).
- Coins and banknotes (excluding $100) now itemgroups, items moved to generic\currency.
- CURRENCY item category added, includes coins/banknotes, cash cards and gas discount cards.
- ATMS and bank vaults now contain a significant amount of banknotes, mostly in bundle/strap form.
- Slot machines potentially contain a significant amount of quarters, vending machines have small mix of coins and notes.
- money_bundle obsoleted, migrated to $20 currency strap (in line with description), mod/code references to it replaced with money_one.
- $50 and $100 notes have postapoc value of 1 cent per note, to reflect demand from Free Merchants, who lorewise overprint them to use as Merch.
- Rubber bands added, spawn in offices.
- ATM no longer explodes when destroyed.

#### Describe alternatives you've considered
Deprecate cash cards in favour of using banknotes/coins when using vending/slot machines. Would require more than JSON though.  EDIT: see #51090

#### Testing
Copied JSON to copy of current experimental build, does not appear to be any bugs.

#### Additional context
<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Currency in Circulation: Volume</p>

  | $1 | $2 | $5 | $10 | $20 | $50 | $100 | $500 to $10,000 | Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Year 2020 in billions of notes | 13.1 | 1.4 | 3.2 | 2.3 | 11.7 | 2.3 | 16.4 | 0.0004 | 50.3
Year 2020 in percent | 26 | 2 | 6 | 5 | 23 | 5 | 32 | 0 | 100

</body>
</html>
<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2019 Circulating Coin Production<br style="box-sizing: border-box;"><a rel="nofollow" href="https://www.creditloan.com/blog/value-of-us-currency-in-circulation/" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;">https://www.creditloan.com/blog/value-of-us-currency-in-circulation/</a></p>

  | 1c | 5c | 10c | 25c | 50c | $1 | Total
-- | -- | -- | -- | -- | -- | -- | --
Year 2019 in millions of coins | 2192 | 378.76 | 737 | 504.2 | 3.4 | 2.94 | 3813.8
Year 2019 in percent | 0.574 | 0.09931 | 0.19324 | 0.1322 | 0 | 0 | 1

</body>
</html>

ATM contents:
https://www.npr.org/templates/story/story.php?storyId=125621359
"ATMs typically hold cassettes with room for 1,000 bills each. If you're talking twenties, ten cassettes add up to as much as $200,000."

Banknote volume:
156 mm width x 66.3 mm height x 0.10922mm thickness
100 notes = 10.922mm thickness (112.964062 ml)
1000 notes: 109.22mm thickness (1129.64062 ml)

Coin roll volume (if items instead of magazine/ammo_types):
https://www.thesprucecrafts.com/number-of-coins-in-roll-768862
https://www.omnicalculator.com/math/volume
<html>
<body>

Coin | by diameter | by radius | Volume
-- | -- | -- | --
Penny Roll | 19.05 mm diameter x (1.52mm thickness x 50) | 9.525mm radius x 76mm height | 21.66ml
Nickel Roll | 21.21mm diameter x (1.95mm x 40) | 10.605mm radius x 78mm height | 27.56ml
Dime Roll | 17.91mm diameter x (1.35mm x 50) | 8.955mm radius x 67.5mm height | 17ml
Quarter Roll | 24.26mm diameter x (1.75mm x 40) | 12.13mm radius x 70mm height | 32.36ml
Half-dollar Roll | 30.61mm diameter x (2.15mm x 20) | 15.305mm radius x 43mm height | 31.64ml
Dollar Roll (Susan B. Anthony) | 26.5mm diameter x (2mm x 25) | 13.25mm radius x 50mm height | 27.6ml

</body>
</html>

Bulk Coin Bag Sizes (not implemented):
https://catalog.usmint.gov/bulk-purchase-program-landing.html

Info on ATMs accepting straps/bundles:
 (p52, 6.2 APPENDIX B: DENOMINATION BREAKDOWN – NON -MERCHANT)
https://www.gs1us.org/DesktopModules/Bring2mind/DMX/Download.aspx?Command=Core_Download&EntryId=665&language=en-US&PortalId=0&TabId=134

### CODE REVIEW

**Comment by Entity-y** [comment]
The ATM PR was recently merged, might be worth adding the `OLD_CURRENCY` flag to currencies to be accepted into the ATM.

**Comment by ifffrt** [comment]
This is not in scope of this PR but I'd love for denarii, hub coins, merchs, chits, etc. to become ammo types so that using them to buy stuff from the Forge lords in Magiclysm be less of a pain.

**Comment by chaohedgehogs** [comment]
> The ATM PR was recently merged, might be worth adding the `OLD_CURRENCY` flag to currencies to be accepted into the ATM.

Done. The bundles/straps got the flag as well, since ATMs can apparently accept them if they comply with official standards.

> This is not in scope of this PR but I'd love for denarii, hub coins, merchs, chits, etc. to become ammo types so that using them to buy stuff from the Forge lords in Magiclysm be less of a pain.

I'd consider currency from any mods bundled with the game to be within the scope of this PR. The base game faction currencies were converted earlier, and the denarii is now an ammo_type as well. I think that covers all of them, but if there are any others I'll convert them too.

**Comment by Brambor** [comment]
I crunched additional context into tables for you. Note: I added zeroes where they were missing. You can just copy-paste this into your description.

<hr>

Currency in Circulation: Volume

|  | $1 | $2 | $5 | $10 | $20 | $50 | $100 | $500 to $10,000 | Total |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | ---  |
| Year 2020 in billions of notes | 13.1 | 1.4 | 3.2 | 2.3 | 11.7 | 2.3 | 16.4 | 0.0004 | 50.3 |
| Year 2020 in percent | 26 | 2 | 6 | 5 | 23 | 5 | 32 | 0 | 100 |

2019 Circulating Coin Production (millions of coins)
https://www.creditloan.com/blog/value-of-us-currency-in-circulation/

|   | 1c | 5c | 10c | 25c | 50c | $1 | Total |
| --- | --- | --- | --- | --- | --- | --- | ---  |
| Year 2019 in millions of coins | 2192 | 378.76 | 737 | 504.2 | 3.4 | 2.94 | 3813.8 |
| Year 2019 in percent | 0.574 | 0.09931 | 0.19324 | 0.1322 | 0 | 0 | 1 |

ATM contents:
https://www.npr.org/templates/story/story.php?storyId=125621359
"ATMs typically hold cassettes with room for 1,000 bills each. If you're talking twenties, ten cassettes add up to as much as $200,000."

Banknote volume:
156 mm width x 66.3 mm height x 0.10922mm thickness
100 notes = 10.922mm thickness (112.964062 ml)
1000 notes: 109.22mm thickness (1129.64062 ml)

Coin roll volume (if items instead of magazine/ammo_types):
https://www.thesprucecrafts.com/number-of-coins-in-roll-768862
https://www.omnicalculator.com/math/volume

| Coin | by diameter | by radius | Volume |
| --- | --- | --- | --- |
| Penny Roll | 19.05 mm diameter x (1.52mm thickness x 50) | 9.525mm radius x 76mm height | 21.66ml |
| Nickel Roll | 21.21mm diameter x (1.95mm x 40) | 10.605mm radius x 78mm height | 27.56ml |
| Dime Roll | 17.91mm diameter x (1.35mm x 50) | 8.955mm radius x 67.5mm height | 17ml |
| Quarter Roll | 24.26mm diameter x (1.75mm x 40) | 12.13mm radius x 70mm height | 32.36ml |
| Half-dollar Roll | 30.61mm diameter x (2.15mm x 20) | 15.305mm radius x 43mm height | 31.64ml |
| Dollar Roll (Susan B. Anthony) | 26.5mm diameter x (2mm x 25) | 13.25mm radius x 50mm height | 27.6ml |

**Comment by eltank** [comment]
> Done. The bundles/straps got the flag as well, since ATMs can apparently accept them if they comply with official standards.

The ATM code assumes each piece of currency can be processed by the ATM in 1 second. I don't think that's true for bundles of money; those should require disassembly first, hence not having the currency flag.

**Comment by chaohedgehogs** [comment]
> > Done. The bundles/straps got the flag as well, since ATMs can apparently accept them if they comply with official standards.
> 
> The ATM code assumes each piece of currency can be processed by the ATM in 1 second. I don't think that's true for bundles of money; those should require disassembly first, hence not having the currency flag.

Done. I was initially going to work out how to add another flag for the straps/bundles so that they could take longer to deposit than an individual note, but still be faster than the eqivalent number of them, but couldn't work out how. When cash cards get obsoleted the deposit code would only be used by machines that wouldn't accept straps/bundles anyway.

**Comment by chaohedgehogs** [comment]
Not sure why Clang 12 is failing, error log looks like it might be something not related to this PR.

**Comment by anothersimulacrum** [comment]
Please don't convert items that do not need to be count by charges count by charges. It is a hack https://github.com/CleverRaven/Cataclysm-DDA/pull/48525 and charges are asnoying to deal with in code and in JSON.

**Comment by Zireael07** [comment]
@anothersimulacrum: In that case, some other way to fix #https://github.com/CleverRaven/Cataclysm-DDA/issues/48937 ?

I seem to remember an issue where it was suggested currency be counted by charges but NOT ammo, but I can't find it atm. As it stands, things likely to be in large quantities (including cash) induce horrible lag...

**Comment by chaohedgehogs** [comment]
> Please don't convert items that do not need to be count by charges count by charges. It is a hack #48525 and charges are asnoying to deal with in code and in JSON.
The JSON for item groups/map spawning uses regular item counts rather than charges (the game seems to automatically convert them) specifically to avoid such an annoying inconsistency. As for the coins/notes using charges to stack, the sheer quantity of such items means treating them discretely is going to be a performance/QoL nightmare (an IRL slot machine is going to have thousands of coins each, items are limited to 4096 per tile, a player that collects banknotes is going to have even more).

I agree that treating the items as ammo is a poor hack; is the issue that or the use of non-discrete stacking itself? If the former, then allowing non-ammo types to use an equivalent of charges would be a welcome change. If the issue is the latter, then I can open a PR converting the coins/banknotes back into items again.

**Comment by Entity-y** [comment]
It's not the best solution but until there is a better system in place for dealing with seconds of RT loss from moving a couple wallets worth of cash or from having several pages of inventory that consists of just money, I think this change should remain effective.

On the other hand it might incentivise a reason to bundle straps of money together.

**Comment by anothersimulacrum** [comment]
> @anothersimulacrum: In that case, some other way to fix ##48937 ?

This doesn't, it patches over it with an ugly hack.
 
> I seem to remember an issue where it was suggested currency be counted by charges but NOT ammo, but I can't find it atm. As it stands, things likely to be in large quantities (including cash) induce horrible lag...

They're synonymous for this purpose. What you are thinking of is probably what I linked.
I need profiling to back claims about performance (it doesn't need proper tooling, the tools provided in game can do).

> The JSON for item groups/map spawning uses regular item counts rather than charges (the game seems to automatically convert them) specifically to avoid such an annoying inconsistency. 

Yes, making more annoying and error-prone special cases in the code.

> items are limited to 4096 per tile, a player that collects banknotes is going to end up with thousands/millions from banks).

If this is a problem, we should look at it, not insert a hack and ignore it.

> I agree that treating the items as ammo is a poor hack; is the issue that or the use of non-discrete stacking itself? If the former, then allowing non-ammo types to use an equivalent of charges would be a welcome change. If the issue is the latter, then I can open a PR converting the coins/banknotes back into items again.

Count by charges is bad, we should be trying to use it as little as possible.

> It's not the best solution but until there is a better system in place for dealing with seconds of RT loss from moving a couple wallets worth of cash or from having several pages of inventory that consists of just money, I think this change should remain effective.

If we just hack over stuff, we don't get better systems, is the problem. We need a better system, and just making the flaws of the current one ignorable doesn't move us there.

I will open a (draft) PR converting them from ammo (hopefully soon), and I think we should talk there, because it will get a little lost here.

**Pull request merged**
