### PR TITLE
Rename doc/LORE.md to doc/Lore/LORE.md

### LINKED ISSUE #75016: doc/lore/lore.md and doc/LORE.md
### Is your feature request related to a problem? Please describe.

There seems to be a lore folder in doc but there is a LORE.md outside of it.

### Solution you would like.

Put LORE.md in lore folder.

I'm assuming that .md files are not case sensitive, so LORE.md or lore.md might need a slightly new name. 

Maybe lore-setting.md is a better name for lore.md

### Describe alternatives you have considered.

Leave it how it is.

### Additional context

New to contributing.
Would like to try and make a PR for this myself if the issue is valid.
Advice or feedback appreciated.

### PR DESCRIPTION
**Pull request by GusMorphism**
#### Summary
None

#### Purpose of change

Close #75016

#### Describe the solution

Moved `LORE.md` to `doc/lore/`

*edit 1*

Updated `LORE.md` to `LORE-FAQ.md` in line with other file names in /Lore

#### Describe alternatives you've considered

Leave it where it is.

#### Testing

It looks like it worked from the file structure?

### CODE REVIEW

**Review by ZhilkinSerg — CHANGES_REQUESTED** [review]
There is already `lore.md` in the destination folder, so please do not use the same filename in different case.

Would be better to rename `doc/LORE.md` to something like `doc/LORE_FAQ.md` as it was aimed to be a document to answer lore questions and consolidate lore decisions (see https://github.com/CleverRaven/Cataclysm-DDA/pull/66238).

**Comment by GusMorphism** [comment]
Updated LORE.md to LORE-FAQ.md in line with other file names in /Lore

**Comment by marilynias** [comment]
> There is already `lore.md` in the destination folder, so please do not use the same filename in different case.
> 
> Would be better to rename `doc/LORE.md` to something like `doc/LORE_FAQ.md` as it was aimed to be a document to answer lore questions and consolidate lore decisions (see #66238).

requested change seems to be made for a month now, please re-review

**Comment by Night-Pryanik** [comment]
@marilynias care to resolve conflicts?

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
