### PR TITLE
Overhauls chances of good or bad mutations

### PR DESCRIPTION
**Pull request by MylieDaniels**
#### Summary
Features "Mutations now cause genetic damage"

#### Purpose of change
A continuation of the mutation rework that began in PR #55233 

#### Describe the solution
- Introduces Instability, a hidden tracker that increments every time you mutate or demutate.
- Fully rebalances the proportions of "good" (positive point cost) versus "bad" (negative point cost) mutations
- Lays the framework for a future feature that also relies on Instability

#### Testing
Mutated multiple times at various Instability levels.

#### Additional context
image
100 Instability is currently gained per mutation, though it can be changed on a per-mutation basis as it ties to "vitamin_cost".

### CODE REVIEW

**Review by Maleclypse — COMMENTED** [review]
If you are intending to include some markdown changes to explain how instability works and the rate it decays at so people know how to appropriately adjust instability at the mutation design level you might want to move this to draft so it isn't merged without that.  This is really cool so far.

**Comment by avianArsonist** [comment]
On the surface, I'm not a fan of this change. One of the larger appeals of Cataclysm, to me, is how the mechanics treat inhumanity as non-negative, and potentially something to strive towards. With the caveat that I don't have much experience with the current mutation mechanics, this looks like it would encourage low to moderate mutation and harshly discourage heavy mutation/threshold crossing, and would prefer to have becoming post-human through mutations remain, at the least, a viable sidegrade path, if not necessarily an upgrade.

**Comment by MylieDaniels** [comment]
I understand the trepidation, but hope you will be open to an explanation.

Just on the basis of percentages, this is almost a strict buff to mutations, even if you choose to cross the threshold or mutate 80 times or anything.  This is most clearly evidenced by the fact that the dotted red line, which represents the percentage of negative mutations you will have at this point, never crosses the black line, which is the percentage of negative mutations you would have had with the old system (and without Robust Genetics, which was overhauled with this system).

Inhumanity is definitely still, if not more, powerful with this system- these changes largely come out to this:
You will have more good mutations than before if you play carefully, but are punished for using mutagen recklessly or backtracking on a mutation tree.

**Comment by SariusSkelrets** [comment]
Is there's a plan to accelerate the base lowering of instabillity or add a way to lower it?
Currently, the reduction over time seems really low (100 days needed to cancel one mutation)

**Comment by MylieDaniels** [comment]
> Is there's a plan to accelerate the base lowering of instabillity or add a way to lower it?

You can use Robust Genetics to up it to 25/day, and in the future there will be rare loot to affect it.

> Currently, the reduction over time seems really low (100 days needed to cancel one mutation)

Yes, this is intentional.  I'm inclined to make it 0/day, to be honest.

**Comment by TieSKey** [comment]
Mmmmm why should "de-mutating"/purifying also add instability instead of decreasing it???
If a player mutates in a tree and finds out they don't like it, having the ability to revert back and try something else on the same character should be allowed.
Getting/crafting mutagen is quite an irl time investment so if a player already knows the mutations on a tree and wants to invest 40 hours on a mutate/purify cycle until they roll only the good ones (very small chance), well, good for they.

**Pull request merged**
