### PR TITLE
Alter the amount of fuel vehicles spawn with

### PR DESCRIPTION
**Pull request by benjamin-allen**
A small change to modify the amount of fuel that spawns in most road vehicles. The previous setup was for vehicles to spawn with one of three amounts of fuel:

Possibility 1: Spawn with full fuel. (100%)
Possibility 0: Spawn with no fuel. (0%)
Possibility -1: Spawn with fuel from a range of values, currently a very low amount. (1-7%)

The first two options are easy enough to rationalize. I assume 1 is for debug purposes, where vehicles spawn with max fuel, and that 0 is good for completely destroyed vehicles, or ones that could be assumed to be left running and died completely. I find the -1 values to be somewhat unrealistic and unnecessary to gameplay difficulty. The lack of realism in these values is most noticeable when one comes across a car that is assumed to be parked, as I don't see anyone parking a car with between 1% and 7% fuel.

That aside, the new values place fuel between 7% and 35%, which I feel is okay in the realism aspect and fair enough in the gameplay aspect. Thoughts?

### CODE REVIEW

**Comment by karlnp** [comment]
I find them perfectly acceptable from a realism perspective. In an apocalypse scenario, you drive until you run out of gas or nearly, park it, and go find some other way to continue (or turn into a zombie.) Fuller tanks would already have been siphoned.

**Comment by NANOsoldierEnke** [comment]
That does make sense, but I still don't like that explanation for cars parked in garages or such. Guess what would be good to have would be some way to state that spawning on a certain map tile multiplies or divides your rng fuel value by some amount.

**Comment by Coolthulhu** [comment]
It would make more sense if all the mid-fuel cars were damaged enough not to be drivable. You could check it at the end of car spawn function and bump the fuel a bit if the car lacks a vital function.

**Comment by karlnp** [comment]
That sounds reasonable.

**Comment by NANOsoldierEnke** [comment]
Makes sense. I'll take a look around and see if I can do that.

**Comment by NANOsoldierEnke** [comment]
Alright, new commit reverts the initial fuel back to 1-7%, and adds fuel in case the controls, engine, or tires are destroyed.

**Comment by kevingranade** [comment]
Balance question, how much total fuel does this add to the game? It's
unlikely it's enough to overwhelm e.g. gas stations, but it's worth knowing.

**Comment by NANOsoldierEnke** [comment]
The maximum that can be added to a car is 18%, for a maximum spawn of 25% fuel.

**Comment by Coolthulhu** [comment]
Minor: this also increases "fuel" content in battery.

**Pull request merged**
