### PR TITLE
Add gcc 7 and 8 to build matrix.

### PR DESCRIPTION
**Pull request by kevingranade**
Let's see if it just works...

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Have you tried `[[fallthrough]];`?

**Comment by ZhilkinSerg** [comment]
I made `gcc++-7`, `gcc++-8`, `clang++-3.9`, `clang++-4.0` and `clang++-5.0` happy in #23712 (see https://travis-ci.org/CleverRaven/Cataclysm-DDA/builds/377678875?utm_source=github_status&utm_medium=notification).

There are a few issues remaining:

- Error `error: attributes at the beginning of statement are ignored [-Werror=attributes]` in `gcc` prior to `gcc++-7`;
- `clang++-3.9` does not know about `fallthrough` attribute, so it is possible we need to use `[[clang::fallthrough]];` there;
- `clang++-6.0` complains about something unrelated to fallthrough statements.

**Comment by ZhilkinSerg** [comment]
So I guess I made all compilers, but `clang++-6.0` happy in #23712 (see https://travis-ci.org/CleverRaven/Cataclysm-DDA/builds/377735911?utm_source=github_status&utm_medium=notification) with `FALLTHROUGH` macro which is defined as follows in `\src\compiler_defines.h`.

Besides Travis my trunk compiles just fine in VS 2017 on Windows, but I didn't check VS 2015 and Code::Blocks on Windows yet.

```C++
#pragma once
#ifndef COMPILER_DEFINES_H
#define COMPILER_DEFINES_H

#ifndef __has_cpp_attribute       // Optional of course.
#define __has_cpp_attribute(x) 0  // Compatibility with non-clang compilers.
#endif

#if __has_cpp_attribute(fallthrough)
#define FALLTHROUGH [[fallthrough]];
#elif __has_cpp_attribute(clang::fallthrough)
#define FALLTHROUGH [[clang::fallthrough]];
#else
#ifdef _MSC_VER
#define FALLTHROUGH [[fallthrough]];
#else
#define FALLTHROUGH
#endif
#endif

#endif
```

**Comment by ZhilkinSerg** [comment]
So, I made `uimenu` class final and `clang++-6.0` stopped complaining about its destructor in `loading_ui.obj`, but there are multiple other errors now (see https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/377776831). I guess much more changes should be done for this clang version.

Is it possible to use certain version of clang via some MAKE option, so I could test changes locally and do not load Travis?

**Comment by kevingranade** [comment]
The comment-based fall through annotation *should* work, I'm not interested in switching to the annotation until we switch to the c++17 standard, which IMO is years away.
Considering the small number of callsites, I'd rather just refactor the code to avoid the fall through instead of making compiler-aware macros to work around it.

Take a look at what travis does, it just installs the target compiler and then invokes it with a specific name.

Word of warning if you use ccache, it ignores comments, so it will skip rebuilding a file that only has a comment or whitespace change.

**Comment by ZhilkinSerg** [comment]
> The comment-based fall through annotation should work, I'm not interested in switching to the annotation until we switch to the c++17 standard, which IMO is years away.

I am sorry, but I didn't get the point - you mentioned "annotation" twice, but must have been meant another word in the latter occurrence?

> Considering the small number of callsites, I'd rather just refactor the code to avoid the fall through instead of making compiler-aware macros to work around it.

Isn't marking intentional fallthrough in the comments is non-standard either and won't be respected by some of the compilers?

> Take a look at what travis does, it just installs the target compiler and then invokes it with a specific name.

Thanks. I thought it will be harder, but turned out I can simply install required version of clang and define compiler executable version like this:

`make CLANG=clang++-6.0`


> Word of warning if you use ccache, it ignores comments, so it will skip rebuilding a file that only has a comment or whitespace change.

Thanks, I will test without CCACHE then.

**Comment by kevingranade** [comment]
> I mean you probably wanted to mention something "non-comment-based"?

Yes, sorry for being unclear, I meant I would prefer to stick with the comment-based approach for now.

> Isn't marking intentional fallthrough in the comments is non-standard either and won't be respected by some of the compilers?

As far as I know the comment-based approach is the only thing that is documented to work with all compiler versions we use.  They all either recognize the comments or ignore them, unlike annotations.
GCC 7 and 8 are acting strange though.

**Comment by kevingranade** [comment]
So this is just super amazingly awesome, I have this version of gcc installed on my laptop:
```
[kevingranade@newlaptop Cataclysm-DDA]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.1 20180406 (GCC)
```
And it does NOT warn/error about the implicit fallthrough thing.

I haven't been able to find any documentation about what might be happening.

Next time I take a run at this I guess I'll install the travis docker image and start from there, but I'm out of time for the moment and I can't reproduce the issue to even try to work on it.

**Pull request merged**
