### PR TITLE
JSON survival basement and zombies [RDY]

### PR DESCRIPTION
**Pull request by mugling**
This PR overhauls the survivalist basement as more thematic JSON version and also migrates the survivor zombie drops.

Before this PR item drops for both didn't include appropriate magazines and were sometimes OP including military flamethrowers and the like. After this PR drops are made from `guns_survival` and always with accompanying magazines. Sufficient improvised guns are migrated to demonstrate the itemgroup so as to keep the diff manageable with a further PR intending to add the remainder.

Loot is more carefully selected from `gear_survival` which is derived from a number of other groups. The intention of such a hierarchy is both to remove much of the duplication from the JSON and also aid addition and balancing of future items. For example if we add a new light source it need only adding once to `tools_lighting` at the appropriate weighting.

Finally the `misc_smoking` item group is added as the first example of a series of small item groups I want to implement to help make the world look more lived-in.

New item groups
- `tools_tailor`
- `tools_lighting`
- `tools_survival`
- `drugs_heal_simple`
- `gear_survival`
- `clothing_outdoor_*`
- `guns_*_improvised`
- `guns_survival`

### CODE REVIEW

**Comment by mugling** [comment]
Once I've reworked some of the mapgen code the intention is to add a belt with a random quantity of remaining ammo to the last stand but that can wait for a separate PR.

**Comment by Mshock777** [comment]
Maybe it's time to add pipe rifles to all the other ammo types?

**Comment by mugling** [comment]
I'd actually prefer to avoid this as it reduces the differentiation between different ammo types. If you've got `45` ammo but not `9mm` its better that you have to use the survivor hand cannon rather than implementing a `45` pipe rifle.

**Comment by Mshock777** [comment]
@mugling I see your point, but I was talking mostly about .44 and .357.

**Pull request merged**
