### PR TITLE
Move longsword from Medieval Stuff mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
Move longsword and its' fake version from Medieval Stuff mod into the main game.

Other changes:
1. Reduce longsword weight to 1814 and reduce bashing damage to 10.
2. Reduce longsword crafting time to 7 hours from 8 hours and 10 minutes.
3. Reduce fake longsword weight to 939 and bashing damage to 10.
4. Reduce inferior longsword weight to 1814 and bashing damage to 10.
5. Add inferior longsword to some spawn groups.
6. Update No Medieval Items mod to include longsword and its' fake version.
7. Reduce spawn rate of longsword in some item groups.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. What's the reasoning for the reductions, though? It is meant mainly to be in-between the arming sword and the zweihander, if I recall. Though I'm not sure if it was flat-out in-between in that regard, it might've still be closer to the zweihander than the arming sword, which would explain it.

**Comment by Coolthulhu** [comment]
How does it compare to broadsword?
I mean, in `damage / attack time`

**Comment by Darkyhard** [comment]
Wikipedia says that longswords usually weigh 1.1 - 1.8 kilograms, not 2.9 kilograms, so I've decided to decrease the weight and reduce damage caused by one hit so that it doesn't become overpowered. Old variant of longsword was more close to a claymore, not a longsword.

**Comment by chaosvolt** [comment]
Ah, right. I'm not sure where on wikipedia I got the figure that I based the longsword's weight of it, in that case. o.O

**Pull request merged**
