### PR TITLE
[WIP] Add end-game item allowing mutagenic save-states

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Content "Add end-game item allowing mutagenic save-states"

#### Purpose of change
Add an end-game item that can be utilized as a means to obtain a player's desired "perfect" mutation list. The only current way is to win the lottery on purifier and serum rolls. Meanwhile, this is easily done with bionics since it is on a per-CBM basis.

#### Describe the solution
Create an item called "recovery serum" that saves the player's current mutation list in the item. Using the item again in its activated state will return the player to their original char-gen state, then aggressively mutate them up to the saved mutation list. This will hurt a lot, depending on the player's number of mutations. Worst case, this will kill the player due to extreme pain -so this is not done without risk.

This has the following implications:
-If the player mutates something they did not want to mutate, they can revert back to a previously saved state.
-If the player purifies, and it purifies what they didn't want to, they can also revert.
-If the player likes their current mutation list, they can save it.
-This may be the only way to return back to human after reaching post-threshold. This requires the player to not have reached any threshold and saved their state though.
-Once activated, it cannot be de-activated. This means the player would require a lot of recovery serum to become their intended perfect being.
-This should not be spammed since it can kill the player from stacking too much pain. This can be mitigated with strong levels of pain reduction.

image

The recipe may be found in any of the elf-a, alpha, and medical recipe books. However, all 3 are essentially required in order to mass-craft recovery serum.

#### Describe alternatives you've considered
-Targetted mutation
-lower barrier to entry

#### Testing
-Check recipe list
-Spawn one of the three books with the recipe and make sure it is learnable.
-Exhaustively test different permutations of positive/negative traits with mutation gains and losses.

### CODE REVIEW

**Comment by Fris0uman** [comment]
I'm not sure it fits with the plans we have for mutations https://github.com/CleverRaven/Cataclysm-DDA/issues/28277

**Comment by CodeBandit** [comment]
For the sake of having a way to do this in-game, I will convert this into a mod

**Comment by EvgenijM86** [comment]
The only thing that I dislike about current mutation system is that to try a different post-threshold mutation path you need to create a different character, which feels dumb. Post-threshold mutations should prevent you from getting mutations from other post-threholds paths at the same time, not prevent you from switching paths at all (if you are willing to give up your current path).

**Comment by nexusmrsep** [comment]
Sounds more likely viable for genetic recombination unit for a lab finale, rare as CVD machine. Also - although I understand that you want to reset character to zero before mutating again to accumulate potential risk, but wouldn't it be more logical to forcefully reroll mutations towards the save state from the current status, backwards if needed, untill it hits the jackpot on the lottery, with risk being within the randomness of each reroll and the relentless rewriting until success or death?

**Pull request closed without merging**
