### PR TITLE
typed tripoints in iexamine functions

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
None

#### Purpose of change

Typed tripoints.

#### Describe the solution

Convert tripoints mostly to tripoint_bub_ms.
I focused on the iexamine functions present in `iexamine_functions_from_string`.

#### Testing

Tested hacking cardreaders, using elevators including vehicles and monsters and climbing down ledges. Those were about the most touched examine functions, as well as the ones with the most complex location handling. The rest should be straight forward enough.

#### Additional context

I think after this I'm done for now with tripoint conversions.

### CODE REVIEW

**Review by PatrikLundell — CHANGES_REQUESTED** [review]
- activity_actor.cpp: I don't really understand the "tripoint_bub_ms()" syntax, although I guess it defaults to tripoint_zero as its parameter. Is there a reason for not using tripoint_bub_ms_zero?
- iexamine.cpp line 5469-70->5465: I think this is wrong and "-" should be "+" as the "minus" is built into the tripoint itself.
- 5526-28->5521-22: ditto
- 5530-31->5524-24: ditto

**Comment by mqrause** [comment]
> * activity_actor.cpp: I don't really understand the "tripoint_bub_ms()" syntax, although I guess it defaults to tripoint_zero as its parameter. Is there a reason for not using tripoint_bub_ms_zero?

It simply defaults to the default value of the underlying point type, so {0,0,0} for a tripoint. And I think I wrote that before I noticed we have constants for the typed points. Might actually be best to use the _min one, to make clear it's an uninitialized value just needed to create the object. These PRs of the last couple days were more or less written in reverse order upon realizing how deep the typed point rabbit hole goes.

**Review by PatrikLundell — APPROVED** [review]

**Comment by Maleclypse** [comment]
I've merged https://github.com/CleverRaven/Cataclysm-DDA/pull/76712 and this is not currently showing merge conflicts do I need to wait a few hours for that to show up or does it require some kind of test rerun?

**Comment by PatrikLundell** [comment]
I don't know what causes PRs to detect merge conflicts, only that you're not notified when they occur, and they're hidden beneath the test block so you won't see it when looking at comments.

Regardless, there were quite a few conflicts. I've done a first pass to resolve them through the web UI, and am currently compiling locally to see if it's consistent. Strangely enough, resolving conflict doesn't seem to have triggered the tests, but local compilation shows failures, so I need to fix that and upload it.

Oh, the previous test run was one of the rare "no failures" one.

**Comment by mqrause** [comment]
It might not have direct conflicts as in we changed the same line of code in different ways, but there might be code issues like mismatching point types now. I'll rebase and see what the compiler says.

**Pull request merged**
