### PR TITLE
Antidepressant overhaul + some new drugs using the new pharmacological system

### PR DESCRIPTION
**Pull request by gkarfakis19**
#### Summary
Content "Overhauls antidepressants to make them more realistic and adds a few new misc drugs."

#### Purpose of change

Overhauls antidepressants according to Erk's suggested changes in #53152.
Adds a few misc drugs that do not spawn that lower and raise heart rate / blood pressure, building on my previous PR and Erk's suggestions in #53152.
Some small infrastructure changes to make EOCs able to query heart rate and blood pressure for the future.

#### Describe the solution

Antidepressants work as such:
When a player takes an antidepressant, say an SSRI, SSRI_pre vitamins are added to their blood 30 mins after consumption. These are capped to the value of 1 pill and slowly decay into the actual SSRI vitamins. This means a player can't simply take 20 SSRI pills in one sitting and get full antidepressant effects. Instead, they need to take them regularly for many days.

As SSRI_pre vitamins get transformed into SSRI vitamins, effects are caused on the player according to the total amount of vitamins in their system.

Between 0 days and 1 week of regular daily intake, the player will experience no antidepressant effect, but instead short-term side effects such as fatigue and nausea.

Between 1 week and 2 weeks, the player will experience those same side effects, with lower intensity.

After 2 weeks, the player will have full antidepressant effects and no side effects.

Antidepressant effects, compared to the old prozac, are far less intense (30% reduction in negative morale). This may be tweaked in the future for balance reasons.

I have ported prozac to this new system as an SSRI, and then added separate SSRI, SNRI, and DNRI antidepressants that all work independently of each other and are subtly different.

A known limitation of this vitamin based approach is that if a player that has been taking these pills for 3 weeks stops taking new pills, instead of going into withdrawal, he will instead regress down the aforementioned pyramid over twice this time.
So if stopping at 3 weeks:

2 weeks of full antidepressant effects.
2 weeks of reduced side effects
2 weeks of intense side effects

and then nothing.

This is obviously not realistic, but better than what we have now. I am open to suggestions on how to improve this.

#### Testing

TODO

### CODE REVIEW

**Comment by gkarfakis19** [comment]
Jesus christ. Something went *really* wrong with this PR.

**Comment by Venera3** [comment]
You could have the third (effective) level of the antidepressant effect build up a `withdrawalium` vitamin with the desired symptoms and add a short-term "took SSRIs" effect blocking it from triggering if you take them regularly.

Otherwise the timeline is a bit compressed but feels like the right ballpark (especially since taking them isn't automated).

**Comment by Maleclypse** [comment]
Please resolve conflict

**Review by I-am-Erk — COMMENTED** [review]
Noting for myself. Working on merge conflicts and need to save progress.

```c++
        } else if( checked_value == "heart_rate" ) {
            return [is_npc]( dialogue const & d ) {
                Character const *you = static_cast<talker const *>( d.actor( is_npc ) )->get_character();
                if( you ) {
                    return static_cast<int>( 100 * you->get_heartrate_index() );
                } else {
                    return 0;
                }
            };
        } else if( checked_value == "blood_pressure" ) {
            return [is_npc]( dialogue const & d ) {
                Character const *you = static_cast<talker const *>( d.actor( is_npc ) )->get_character();
                if( you ) {
                    return static_cast<int>( 100 * you->get_circulation() );
                } else {
                    return 0;
                }
            };
```

this code is from std::function<double( dialogue & )> conditional_t::get_get_dbl( J const &jo ) in condition.cpp which seems to have been totally rewritten. Gotta figure out how to rework it.

**Comment by I-am-Erk** [comment]
NOT a complete conflict resolution. Having C++ issues, see above

**Comment by I-am-Erk** [comment]
OK. I have "fixed" the merge conflicts. I will try to find time in the next few days to properly read and understand what's up to fix the mess in condition.cpp, or see if I can get someone to help with it. Would very much like to get this merged.

**Pull request closed without merging**
