### PR TITLE
CRIT Expansion Update [WIP]

### PR DESCRIPTION
**Pull request by Soupster89**
SUMMARY: Mods "Buff monsters and fix MA styles"

#### Purpose of change

Necromorphs have been rather underwhelming for monsters that are meant to be resistant to shooting down. This will buff them a little and make them more of a challenge.

The MA styles are still missing some weapons from the mod itself.

#### Describe the solution

Buff Necromorph armor values and health/speed.

Add CRIT Hatchet and Entrenching Tool to respective styles.

#### Additional context

Necromorphs are monsters form Dead Space that can take multiple shots to the body and keep attacking. In this mod, they are underwhelming, taking 2-4 good shots at most before going down.

It also seems silly that a Spec Ops force can't use their own tools/weapons for their own schools of fighting.

### CODE REVIEW

**Comment by Maleclypse** [comment]
I think you may be pulling from an already merged branch. I think that may cause some commit issues but I don’t know enough to be sure of that.

**Comment by Soupster89** [comment]
> I think you may be pulling from an already merged branch. I think that may cause some commit issues but I don’t know enough to be sure of that.

I am still not sure what to do when it comes time to update things, I just reuse what I have and simply go from there. Is there a better way to do this? I would really like to know. :/

**Comment by Maleclypse** [comment]
> > I think you may be pulling from an already merged branch. I think that may cause some commit issues but I don’t know enough to be sure of that.
> 
> I am still not sure what to do when it comes time to update things, I just reuse what I have and simply go from there. Is there a better way to do this? I would really like to know. :/


If this works for you then do that, I'm sorry if I held you up in any way.  I was hoping someone who knows more than me would comment.  :(

**Comment by ZhilkinSerg** [comment]
You are using a single `master` branch to add new things. It is possible to work like that, but that needs some git work to get rid of that multiple commits showing on PR. I suggest you to use separate feature branches for each PR.

**Comment by ZhilkinSerg** [comment]
Closing to clean up PR queue, but feel free to reopen.

**Pull request closed without merging**
