### PR TITLE
plantain → cooking banana

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
None

#### Purpose of change
Unify the "cooking banana" name.

#### Describe the solution
Change "plantain" to "cooking banana".

#### Describe alternatives you've considered
Leave it as is.

#### Testing
Name change, can be seen when spawning an item.

#### Additional context
Fixes Transifex issue.

### CODE REVIEW

**Comment by haveric** [comment]
Why not switch these to just be called plantains everywhere? I feel like "cooked cooking banana" is unnecessary here. (Note that I know nothing about these plants and have no idea if there's an actual difference, but from what I can find, plantain is the common name for them)

**Comment by Sathra225** [comment]
Ehh, kinda. Plantains are kind of like potatoes. You actually have to cook them for them to be reasonably edible (chalky and astringent). However, not all cooking bananas are plantains, while all plantains are cooking bananas.
For general use, plantains is used for all cooking bananas, but technically its only for certain types.

Besides that, cooked cooking banana does sound silly. So either changing the item name of 'cooking banana' to plantain, or changing the recipe string to 'roasted cooking banana' would be good.

**Comment by Faalagorn** [comment]
> Why not switch these to just be called plantains everywhere? I feel like "cooked cooking banana" is unnecessary here. (Note that I know nothing about these plants and have no idea if there's an actual difference, but from what I can find, plantain is the common name for them)

I thought about it and what @Sathra225 mention is a valid point too. What do you think then? Plantain for everything or roasted?

**Comment by Zireael07** [comment]
Nitpick: non-native English speaker here, I wouldn't know what a plantain is, I suggest "cooking banana" and "roasted cooking banana". If you do go with plantain, please leave a translator comment.

**Comment by Faalagorn** [comment]
Commited the roasted one for now :)

**Comment by NetSysFire** [comment]
>I wouldn't know what a plantain is

Fun fact, there is a common weed in New England which goes by the name plantain, too. So clarifying that is definitely the right step.

https://gobotany.nativeplanttrust.org/species/plantago/major/

**Pull request merged**
