### PR TITLE
[CR] Tiny menu appearance harmonization.

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Interface "Menu appearance harmonization."`

**This PR got a bit messy.
I'm going to close it and reopen smaller ones.**

#### Purpose of change

I know there's a new bionic-menu on the way (#34061). This is just an idea for UI consistency as suggested in #12112. Perhaps @akozhevn is willing to incorporate some of these changes.

- That's it for now. Hope you like it. I make more changes as soon as I can spare more time.

#### Revised menus:
- Bionic
- Mutation
- Armor-Layers + F1 help text
- Martial Arts Style
- Construction
- Message Log Filter Info
- Advanced-Inventory + Search Filter
- Player Info

#### Screenshots

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

### CODE REVIEW

**Comment by Pupsi-Mupsi** [comment]
jenkins rebuild

**Comment by Night-Pryanik** [comment]
Consider adding a [WIP] tag to the PR's title if you're actively working on it.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Consider adding a [WIP] tag to the PR's title if you're actively working on it.

Sorry. You're right.

BTW -Can you help with the astyle issues in this PR?

**Comment by Night-Pryanik** [comment]
Seems like you're resolved all astyle issues.

**Comment by Pupsi-Mupsi** [comment]
Thanks.
But still "Travis CI build could not complete".
Any idea?

**Comment by Night-Pryanik** [comment]
I restarted Travis builds for you.

**Comment by anothersimulacrum** [comment]
Big patch for astyle issues:
```diff
diff --git a/src/armor_layers.cpp b/src/armor_layers.cpp
index e08ab33ab3..09635464c4 100644
--- a/src/armor_layers.cpp
+++ b/src/armor_layers.cpp
@@ -829,35 +829,36 @@ void player::sort_armor()
                 }
             }
         } else if( action == "USAGE_HELP" ) {
-            popup_getkey( _( "Use the [<color_yellow>arrow- or keypad keys</color>] to navigate the left list.\n"
-                             "[<color_yellow>%s</color>] to select highlighted armor for reordering.\n"
-                             "[<color_yellow>%s</color>] / [<color_yellow>%s</color>] to scroll the right list.\n"
-                             "[<color_yellow>%s</color>] to assign special inventory letters to clothing.\n"
-                             "[<color_yellow>%s</color>] to change the side on which item is worn.\n"
-                             "[<color_yellow>%s</color>] to sort armor into natural layer order.\n"
-                             "[<color_yellow>%s</color>] to equip a new item.\n"
-                             "[<color_yellow>%s</color>] to equip a new item at the currently selected position.\n"
-                             "[<color_yellow>%s</color>] to remove selected armor from oneself.\n"
-                             "\n"
-                             "\n"
-                             "Encumbrance explanation:\n"
-                             "\n"
-                             "<color_light_gray>The first number is the summed encumbrance from all clothing "
-                             "on that bodypart.  The second number is an additional encumbrance penalty "
-                             "caused by wearing either multiple items on one of the bodypart's layers or "
-                             "wearing items the wrong way (e.g. a shirt over a backpack).  "
-                             "The sum of these values is the effective encumbrance value "
-                             "your character has for that bodypart.</color>" ),
-                          ctxt.get_desc( "MOVE_ARMOR" ),
-                          ctxt.get_desc( "PREV_TAB" ),
-                          ctxt.get_desc( "NEXT_TAB" ),
-                          ctxt.get_desc( "ASSIGN_INVLETS" ),
-                          ctxt.get_desc( "CHANGE_SIDE" ),
-                          ctxt.get_desc( "SORT_ARMOR" ),
-                          ctxt.get_desc( "EQUIP_ARMOR" ),
-                          ctxt.get_desc( "EQUIP_ARMOR_HERE" ),
-                          ctxt.get_desc( "REMOVE_ARMOR" )
-                        );
+            popup_getkey(
+                _( "Use the [<color_yellow>arrow- or keypad keys</color>] to navigate the left list.\n"
+                   "[<color_yellow>%s</color>] to select highlighted armor for reordering.\n"
+                   "[<color_yellow>%s</color>] / [<color_yellow>%s</color>] to scroll the right list.\n"
+                   "[<color_yellow>%s</color>] to assign special inventory letters to clothing.\n"
+                   "[<color_yellow>%s</color>] to change the side on which item is worn.\n"
+                   "[<color_yellow>%s</color>] to sort armor into natural layer order.\n"
+                   "[<color_yellow>%s</color>] to equip a new item.\n"
+                   "[<color_yellow>%s</color>] to equip a new item at the currently selected position.\n"
+                   "[<color_yellow>%s</color>] to remove selected armor from oneself.\n"
+                   "\n"
+                   "\n"
+                   "Encumbrance explanation:\n"
+                   "\n"
+                   "<color_light_gray>The first number is the summed encumbrance from all clothing "
+                   "on that bodypart.  The second number is an additional encumbrance penalty "
+                   "caused by wearing either multiple items on one of the bodypart's layers or "
+                   "wearing items the wrong way (e.g. a shirt over a backpack).  "
+                   "The sum of these values is the effective encumbrance value "
+                   "your character has for that bodypart.</color>" ),
+                ctxt.get_desc( "MOVE_ARMOR" ),
+                ctxt.get_desc( "PREV_TAB" ),
+                ctxt.get_desc( "NEXT_TAB" ),
+                ctxt.get_desc( "ASSIGN_INVLETS" ),
+                ctxt.get_desc( "CHANGE_SIDE" ),
+                ctxt.get_desc( "SORT_ARMOR" ),
+                ctxt.get_desc( "EQUIP_ARMOR" ),
+                ctxt.get_desc( "EQUIP_ARMOR_HERE" ),
+                ctxt.get_desc( "REMOVE_ARMOR" )
+            );
             draw_grid( w_sort_armor, left_w, middle_w );
         } else if( action == "HELP_KEYBINDINGS" ) {
             draw_grid( w_sort_armor, left_w, middle_w );
diff --git a/src/player.cpp b/src/player.cpp
index 25cbb7784c..84f7c98a5a 100644
--- a/src/player.cpp
+++ b/src/player.cpp
@@ -3222,7 +3222,7 @@ bool character_martial_arts::pick_style( const avatar &you ) // Style selection

     uilist kmenu;
     kmenu.text = colorize( string_format( _( "Select a style.  "
-                                             "Press [<color_yellow>%s</color>] for more info." ),
+                                          "Press [<color_yellow>%s</color>] for more info." ),
                                           ctxt.get_desc( "SHOW_DESCRIPTION" ) ), c_white );
     ma_style_callback callback( static_cast<size_t>( STYLE_OFFSET ), selectable_styles );
     kmenu.callback = &callback;
diff --git a/src/player_display.cpp b/src/player_display.cpp
index 491eb88127..a580558cc1 100644
--- a/src/player_display.cpp
+++ b/src/player_display.cpp
@@ -1312,8 +1312,8 @@ void player::disp_info()
     std::string action;

     right_print( w_tip, 0, +4, c_white, string_format(
-                             _( "< [<color_yellow>%s</color>] keybindings >" ),
-                             ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
+                     _( "< [<color_yellow>%s</color>] keybindings >" ),
+                     ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
     wrefresh( w_tip );

     draw_initial_windows( w_stats, w_encumb, w_traits, w_bionics, w_effects, w_skills, w_speed, *this,
```

**Comment by Pupsi-Mupsi** [comment]
Thanks a lot!!!
> 
> (What version is your astyle?)

grafik

**Comment by anothersimulacrum** [comment]
Ah, that'd do it. This project only supports astyle version 3 and 3.1

**Comment by Pupsi-Mupsi** [comment]
> , that'd do it. This project

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Ah, that'd do it. This project only supports astyle version 3 and 3.1

Thanks. I try to update astyle to 3.1 as soon as I understand how to do this ;-) I have not used "Code Blocks" in a while. I downloded astyle from sourceforge (https://sourceforge.net/projects/astyle/), but sitll have to figure out what to do next.

**Comment by Pupsi-Mupsi** [comment]
This PR got a bit messy.
I'm going to close it and reopen smaller ones.

**Pull request closed without merging**
