### PR TITLE
Specify volumetric units via JSON

### PR DESCRIPTION
**Pull request by mugling**
- Allows specifying of volumetric units in json, eg .`""volume": "10ml"`, `"volume": "5L"`.
- Legacy format (per 250ml) remains supported
- Some items can now stop being `AMMO` (for example `string_6` in 13f17e1)

### CODE REVIEW

**Comment by mugling** [comment]
Ready

**Comment by Coolthulhu** [comment]
```
src/units.h:240:42: error: ‘numeric_limits’ is not a member of ‘std’
 const volume volume_min = units::volume( std::numeric_limits<units::volume::value_type>::min(),
```

Then few related errors.

**Comment by mugling** [comment]
Can you try an `#include <limits>` in `units.h` and if that works for you'll I'll push that change to this branch

**Comment by Zireael07** [comment]
> Some items can now stop being AMMO (for example string_6 in 13f17e1)

Yaay!

**Comment by Coolthulhu** [comment]
Jenkins reports problems

**Comment by mugling** [comment]
No idea why that copy constructor is deleted. I've switched to a move instead and we'll see if its happy with that

**Comment by mugling** [comment]
Found it - useless use of `auto` hiding in plain sight

**Comment by mugling** [comment]
Good to go (last commit was astyling)

**Pull request merged**
