### PR TITLE
Fixed fingerless survivor glove thickness, tidied up items and recipes for consistency

### PR DESCRIPTION
**Pull request by venum4k**
#### Summary
Bugfixes "Updated fingerless survivor glove recipes and item"

#### Purpose of change

The fingerless survivor glove item had some inconsistencies when compared to the prerequisites and appeared to be a mixture of light and medium glove variants.

#### Describe the solution

I changed the thickness value, tidied up the descriptions and names. I also added a separate light fingerless glove item and recipes for normal size and XL versions. I also changed the base XL survivor glove id to keep it inline with other XL glove ids.

#### Describe alternatives you've considered

Changing the thickness on its own would have solved the armour value issue.

#### Testing

I checked the items and recipes in-game for any notable issues.

#### Additional context

 #49523

### CODE REVIEW

**Comment by Maleclypse** [comment]
Your desire for consistency is appreciated however unless you include a migration to the new ID it will break saves.

**Comment by actual-nh** [comment]
Suggestion: For master (future 0.F), do just a thickness fix. Do the rest, which can't go into master, as a PR for 0.F-dev. Admittedly, there's no guarantee even the first part will get into 0.F.

**Comment by venum4k** [comment]
Alright I think that's the migration json sorted out, Seeing as 0.F released this morning I'll leave this PR for now. Unless anyone has any further suggestions that is.

**Comment by FuelType-Memes** [comment]
Maybe reevaluate encumbrance numbers after the change in thickness?

**Comment by venum4k** [comment]
I went for 80% of the base, same as the original fingerless gloves. I guess cutting fingers off could have more of an impact, 15% less coverage for 20% less encumbrance. Could bump those up further seeing as fingers are nearly half the area of hands from a visibility point of view.

**Comment by actual-nh** [comment]
Removed 0.F Backport Candidate due to #49802.

**Comment by anothersimulacrum** [comment]
It has string changes, it wouldn't be backportable to 0.F

**Comment by ZhilkinSerg** [comment]
> 
> 
> It has string changes, it wouldn't be backportable to 0.F regardless

We can backport translations too, though it is kinda tricky to do.

**Pull request merged**
