### PR TITLE
Lowered coverage for subject suit

### LINKED ISSUE #44076: Subject suit with wrong description or wrong coverage
# Describe the bug

image

### PR DESCRIPTION
**Pull request by arijust**
#### Summary

SUMMARY: Bugfixes "Lowered coverage for subject suit."

#### Purpose of change

Close #44076
#### Describe the solution

Lowered subject suit coverage from 95% to 60%.
#### Describe alternatives you've considered

Change it into other percentage or just change description.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
This should change the coverage just for the bodyparts, not the whole suit.

**Comment by LaVeyanFiend** [comment]
Replacement of:
```
    "covers": [ "leg_l", "leg_r", "arm_l", "arm_r", "torso" ],
    "coverage": 95,	    "coverage": 60,
    "encumbrance": 3,	    "encumbrance": 3,
    "max_encumbrance": 7,	    "max_encumbrance": 7,
```
with:
```
"armor_portion_data": [
      { "covers": [ "torso" ], "coverage": 95, "encumbrance": 3, "max_encumbrance": 7 },
      { "covers": [ "leg_l", "leg_r", "arm_l", "arm_r" ], "coverage": 60, "encumbrance": 3, "max_encumbrance": 7 }
    ],
```
To make the more correct solution seems to have shown a different bug:
image

**Comment by jbytheway** [comment]
Perhaps part-specific encumbrance isn't supported, so you're just seeing the default encumbrance values there?  What happens if you leave `encumbrance` and `max_encumbrance` at the top level rather than moving them into `armor_portion_data`?

**Comment by akirashirosawa** [comment]
> Perhaps part-specific encumbrance isn't supported, so you're just seeing the default encumbrance values there? What happens if you leave `encumbrance` and `max_encumbrance` at the top level rather than moving them into `armor_portion_data`?

I don't know how it works, but in the game my character has such a wonderful helmet.

**Pull request merged**
