### PR TITLE
[RDY] Translate some Chinese world names (part.1)

### LINKED ISSUE #16129: Random world name will always be "Tom" in Chinese version
Tested with zh-cn/zh-tw/ja, press \* will generate random name, and it will only be "tom" (and related translated word).

Random character name will also generate "Tom" a lot ("Tom" only, without last name),  some where around 1 in 5.

English version does not have this issue.

0.c-12763-g100d5bd ,windows

### PR DESCRIPTION
**Pull request by ghost**
This adds some Chinese world names.

### CODE REVIEW

**Comment by DLaboratory** [comment]
Is that a bug of GitHub? I just rebased this branch and pushed (`--force`), then this pull request was automatically closed and reopened.

**Comment by DLaboratory** [comment]
@cainiaowu Any suggestions on acquiring translated toponyms? Translate those in `en.json` is an inappropriate approach, many of them are not quite translatable, and translating them is so boring.

**Comment by cainiaowu** [comment]
I think the correct fix should let the name selector fall back lookup en.json if no proper name found in current languages instead of throw out a "Tom".

**Comment by DLaboratory** [comment]
I'll translate more names in the future, but at least those names I've translated so far can be merged now.

**Pull request merged**
