### PR TITLE
ID cards are now categorized as KEYS

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Content "ID Cards are now categorized as KEYS not OTHER"

#### Purpose of change
ID cards now have a sort zone and can be caught by custom filters.

#### Describe the solution
Added new category, added it to all the items in id.json

#### Describe alternatives you've considered
manually adding every id to a custom filter in game

#### Testing
Load up the game spawn a visitors badge, spawn a military ID
image

#### Additional context
If someone wants a different name that's fine too. There is already some discussion and I think @Terrorforge argument of all items that unlock doors should be separated is valid.

### CODE REVIEW

**Comment by Terrorforge** [comment]
I don't think "documents" is the right term, because that implies the category would contain stuff like lab reports and the corporate accounting ledger. I suggest something like "ID"/"Identification", or perhaps the broader "Keys".

I also suggest the various TCL badhes be added to this category as well.

**Comment by bombasticSlacks** [comment]
TCL badges are in this category by inheritance. 

I'd like to split the books into 3 inventory categories, also for better sorting: manuals/instructional, leisure books, and documents. So I would _actually_ like the corporate accounting ledger to go in this category 😆. Lab reports with recipes in them would be manuals. 

If that isn't appropriate then credentials might be a good category name, keys seems a bit meta but I think ID would work too!

**Comment by PatrikLundell** [comment]
What about score cards, loyalty cards, etc. that you can find in wallets together with the ID cards? And the maps that don't seem to fit into any category (and thus remain after having sorted loot)? And survivor notes?

I think all of those would fit into this category.

**Comment by Terrorforge** [comment]
Personally I would prefer if all the door-opening ID cards and whatnot had their own category, separate from any books or lore documents. It's already kind of a pain to pick them out from whatever "Other" nonsense you may have picked up, no need to recreate that.

Maps are already listed underhave their own "Maps" category

**Comment by PatrikLundell** [comment]
Hm, if maps already have their own category, their failure to be sorted must be a hole in the sorting zone coverage, then.

**Comment by bombasticSlacks** [comment]
I was also surprised to learn it while working on this PR but maps can in fact be sorted currently. 
image

I think you are right Terrorforge I will go with keys instead of "documents" and it will just be items which allow access to specific areas. That is certainly a valuable category on its own.

**Comment by PatrikLundell** [comment]
What about both an ID category and a "Miscellaneous Documents" one?
Also, thanks for correcting the misconception regarding Maps sorting.

**Comment by bombasticSlacks** [comment]
I'm gonna work on that in a separate PR, or someone else could if I don't get to it, but it would be a lot of JSON to work through. More than I can manage on a couch while chatting with the family 😄.

**Pull request merged**
