### PR TITLE
Removing legacy json name / name_plural convention.

### LINKED ISSUE #36110: Obsolete legacy JSON
**Is your feature request related to a problem? Please describe.**
We've got a load of legacy JSON making game data inconsistent and it's harder to make tooling for our data when it isn't well standardized.

**Describe the solution you'd like**
All game data should use current conventions and support for loading legacy JSON objects should be dropped. Most of the updates should be relatively easy to automate.

- [ ] item groups
- [ ] name strings
- [ ] `volume` ints
- [ ] `weight` ints
- [ ] `time` ints
- [ ] `burst` attributes

### PR DESCRIPTION
**Pull request by jayhide**
#35102  Summary

SUMMARY: Infrastructure "Replacing legacy json for name strings with more up-to-date conventions."

#### Purpose of change
As described in #36110 this is for replacing the legacy json throughout the code with more current conventions, keeping it consistent for ease of tooling and other development. This PR switches all older instances of name string formatting to the current convention. 

#### Describe the solution
Changes were automated via python script.

Progress:
* Removed instances of "name_plural": "fishes" key / value in json items and replaced with the "name": {"str": "fish", "str_pl": "fishes"} format.

#### Testing
Ran all unit tests and wish-spawned some of the affected items in plural and singular numbers just to check.

#### Additional context
This was done via python script rather than by hand, and as I am brand new to the codebase, I would appreciate any eyes or commentary.

### CODE REVIEW

**Comment by ymber** [comment]
Don't try to do all of #36110 in a single PR.

**Comment by jayhide** [comment]
> Don't try to do all of #36110 in a single PR.

Yeah good idea, I'll break it up.

Doing this update for data/json/body_parts.json alone breaks tests, because (I think) of hardcoding in bodypart.cpp lines 185-186 where we expect name and name_plural. Should I leave body_parts.json alone or change the code?

**Comment by Qrox** [comment]
The `plural_name` of bodyparts are actually not plural names -- they are names for a pair of body parts, such as arms and legs. It's done this way because some languages do not have plural forms so these names should be separately translated.

**Comment by jayhide** [comment]
Ah, gotcha. I'll just leave that one alone then.

**Comment by I-am-Erk** [comment]
This is incredibly long. I've reviewed a large number and seen no problems, but have not read every single change. If there's a problem, I'll have your badge and gun jayhide!

**Comment by ymber** [comment]
Did you do a new script for this or adapt adjust_values.py? If you did something new put it in tools/ so other people can use it. Checking the script is valid is also a lot easier than going through thousands of automated changes.

**Comment by kevingranade** [comment]
This touches too many strings to sneak it in right now, it's a perfect "right after a release" PR though.

**Comment by ZhilkinSerg** [comment]
I will close this PR as it has too many conflicts while @snipercup is doing the same thing in small steps.

**Pull request closed without merging**
