### PR TITLE
Color clothing items depending on damage value. (Inventory, Pickup, etc)

### PR DESCRIPTION
**Pull request by OzoneH3**
Proper item coloring in V menu.
Clothing damage colors taken from armor_sort().

### CODE REVIEW

**Comment by Barhandar** [comment]
:rainbow:

**Comment by narc0tiq** [comment]
I'm with @Barhandar on this one. Too much color for too little gain.

**Comment by Rivet-the-Zombie** [comment]
Also remember that some of us have a hard time with colors. Adding lots more colors only makes stuff harder for us to read.

**Comment by KA101** [comment]
Yeah, skittles* are good in moderation but get old in quantity.  Afraid this one isn't gonna merge.  Thanks anyway.  :-(

*Taste the rainbow!

**Comment by OzoneH3** [comment]
What about something like this:



Another less rainbowy aproach. Less space used for the itemname, can probably trim down (fits) as well as other modifiers.

You can see on one glance what item is damaged. Its also easier to see what the actual itemname is without having to read the damage type first, especially in a long worn list with longer and shorter damage texts.

This could also just be an option to use for a different way of displaying stuff.

**Comment by Nevets-** [comment]
You could compress the damage indicators down to two characters like this:
`++ Reinforced` (Blue)
`|| Undamaged` (Dark Green)
`|\ Ripped` (Light Green)
`|. Torn` (Yellow)
`\. Shredded` (Light Red)
`.. Tattered` (Dark Red)
With the spaces instead of periods, and then everything stays lined up.

**Comment by narc0tiq** [comment]
I like both of those ideas. Like a smaller version of the limb HP display for items.

**Pull request closed without merging**
