### PR TITLE
Add dashboards to vehicles

### PR DESCRIPTION
**Pull request by illi-kun**
This is a first step in splitting of controls to separate "steering controls" and "electric controls" discussed in #15807.

Currently, the part is not very useful (it's a bigger copy of electronic control unit, distinction of these parts will appear a bit later).

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I believe vehicle tests should be adjusted due to new part with additional weight.

**Comment by illi-kun** [comment]
@ZhilkinSerg yeah, I see. I didn't expect any tests are affected by these changes.
I'll test next PRs with similar changes on a linux machine for avoiding such issues with tests.

**Comment by illi-kun** [comment]
Okay, it seems that I have to test it deeply, so set it to [WIP] state.

**Comment by ZhilkinSerg** [comment]
Tests look good now.

**Pull request merged**
