### PR TITLE
Removing and/or using some unused itemgroup IDs

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
- ``accessory_ring`` got back in use after I removed it from use in #63311, just without wedding rings since we already spawn them through different means anyway, and it means I can use the group for child spawns as well
- Removed a bunch of unused full medication itemgroups - it appears we do not spawn those full ever?
- ``corpse_child``, ``milk_powder_bag_plastic_4``, ``milk_powder_bulk``, ``flour_bag_paper_powder_10`` and ``flour_bag_paper_powder_70`` removed, since they were completely unused
- The full cinnamon group now actually uses full subgroups
- ``yeast_bag_plastic_full`` and ``seasoning_salt_bag_plastic_full`` added back into circulation
- Removed all the self-deprecating JSON comments in food itemgroups. I already said in the review of that PR to remove those. We do not need useless clutter like that

### CODE REVIEW

**Comment by Maleclypse** [comment]
All the full drug bottles should have a chance to spawn behind the counter in pharmacies.

**Comment by Maleclypse** [comment]
except the homeopathic ones that should spawn in the aisles of pharmacies and gas stations

**Comment by Karol1223** [comment]
> All the full drug bottles should have a chance to spawn behind the counter in pharmacies. 

I believe we use different itemgroups for that entirely, that instead of using full bottles spawn between 20 and 60 pills? It's weird, but the point is we don't use full bottle spawns for that.

**Comment by Maleclypse** [comment]
> > All the full drug bottles should have a chance to spawn behind the counter in pharmacies.
> 
> I believe we use different itemgroups for that entirely, that instead of using full bottles spawn between 20 and 60 pills? It's weird, but the point is we don't use full bottle spawns for that.

I thought I’d gone through and moved to the commercial bottles that are like 100-600 pills but maybe I just gathered details on what sizes various meds came in for pharmacy purchases.

**Comment by Karol1223** [comment]
>I thought I’d gone through and moved to the commercial bottles that are like 100-600 pills but maybe I just gathered details on what sizes various meds came in for pharmacy purchases.

Yeah you're gonna have to tell me exactly what to do because nothing in medical groups adds up.

**Comment by Maleclypse** [comment]
I'll see if I can find any decent options but I think you've probably made the right choices short of someone going in and redoing pharmacy spawns.  which is a bit out of scope.

**Pull request merged**
