### PR TITLE
Adds milk material to cheeseburgers for the cheese

### PR DESCRIPTION
**Pull request by remyroy**

### CODE REVIEW

**Comment by pisskop** [comment]
does adding milk make the cheeseburger 33% milk?

afa nutrient base

**Comment by remyroy** [comment]
It might make the cheeseburger 33% milk but there is no way to specify ratios from my understanding.

**Comment by Rivet-the-Zombie** [comment]
I'm not sure if the few grams of cheese is worth adding as a listed material, since that will probably raise its calcium content a great deal.

**Comment by remyroy** [comment]
A better way would be to specify the ratios in the json file. It would probably apply to other comestibles as well. However, I'm not sure it's worth the added complexity. An even better way might be to use the ratios of the components used to craft the item in the recipe although the complexity would be shifted in the implementation of such a system.

In the meantime, I think it would be good to include milk because of the new vitamin system and to prevent someone with lactose intolerance from recycling its milk into better food without the downside.

**Comment by mugling** [comment]
Changing `material` to influence `vitamins` is the wrong approach. Specification via materials is just to bootstrap the system with some reasonably sane values.

You can specify `vitamins` for a comestible but please don't do this for individual items for now as the overall mechanisms and balance may change. Grouping of items using `abstract` and `copy-from` is a better approach, for example defining `abstract: legume` with specific `vitamins` and then inheriting from this for specific vegetables.

**Comment by remyroy** [comment]
How does `copy-from` work? Could or should I create something like a cheese slice and `copy-from` it? Can you copy from multiple stuff and add up all their vitamins?

**Comment by illi-kun** [comment]
> How does copy-from work? 

I wonder why it's not yet described in ```/doc/JSON_INFO.md```

**Comment by mugling** [comment]
@illi-kun I should probably tackle the documentation as part of #14250

**Comment by Coolthulhu** [comment]
If it's just for the allergies, you can add "ALLERGEN_MILK" flag and it will do the job.

**Pull request closed without merging**
