### PR TITLE
Multistory office tower

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content "Added new levels to the office tower"```

#### Purpose of change
It had only 2 floors. I added 2 more, so now it's an actual tower. 
Also, I kind of modernized it.

#### Describe the solution
I added 2 more storeys.
I added coat racks, file cabinets, satelittes and **lots of** nested chunks. (probably in a bad way)
Also, I removed ```office_tower``` from ```regional_map_settings```, because the two looked similar, but this one had one extra floor, and I am pretty sure the other one is not in json.

#### Screenshots
Marked the new nested chunks:
loffice_0
loffice_1
loffice_2
loffice_3
loffice_4
Also, is this better?
linoleum

### CODE REVIEW

**Comment by curstwist** [comment]
I like the chunks (so many!).  
Both floors are nice, hard to choose but I think I prefer wood.  Linoleum is more realistic though.

Will this still have the lab spawn chance?

**Comment by LovamKicsiGazsii** [comment]
Nope, this one doesn't have a lab. (and didn't have one)
When I add more levels to ```office_tower_2```, I'll definitely keep that feature.

**Comment by LovamKicsiGazsii** [comment]
This doesn't sound good.
I don't know what I am doing wrong. :confused:

**Comment by ifreund** [comment]
No worries, it looks like gorgon doesn't want to build since the `json.h` on your branch is not the same as the one on master.  You could fix this with a quick `git rebase`.

**Comment by LovamKicsiGazsii** [comment]
Sorry for taking this long, I couldn't really understand ```git rebase```. Is there another way to solve this, like rewriting ```overmap_terrain.json```? I think the problem is, that the original om. terrains got moved to ```overmap_terrain_commercial.json```.

**Comment by ifreund** [comment]
> I think the problem is, that the original om. terrains got moved to overmap_terrain_commercial.json.

Yeah that's exactly what caused the conflict, I just went ahead and resolved it for you.

**Pull request merged**
