### PR TITLE
Translation updates

### PR DESCRIPTION
**Pull request by BrettDong**

### CODE REVIEW

**Comment by ZenZen2** [comment]
In some cases you removed the german translation from some sentences and replaced is by english ones, why?

**Comment by BrettDong** [comment]
I've just fetched the changes of different languages from Transifex. I
didn't take part in German translation. Would you like to list some
cases, so I could take a look on what was going on?


在 2016/11/19 下午6:17, ZenZen2 写道:

**Comment by ZenZen2** [comment]
Im Sorry my skills are low on this, looks like i am wrong about my last Message. They are not replaced by english text, they are removed.
One example of many at Line 98818 the translation is removed. -msgstr "Ausziehen:" to +msgstr ""
I am sorry if i read it wrong. Im new to this.

**Comment by BrettDong** [comment]
Don't worry. Texts were just moved to another place.

lang/po/de.po line 62309:

#: lang/json/keybinding_from_json.py
msgid "Take Off Worn Item"
msgstr "Ausziehen"



在 2016/11/19 下午7:31, ZenZen2 写道:

**Comment by ZenZen2** [comment]
Ok, thanks for explanation :)

**Comment by BrettDong** [comment]
BTW, how do you think about #4652? Is it a crucial issue? Will the game
play awkwardly?


在 2016/11/19 下午7:39, ZenZen2 写道:

**Comment by ZenZen2** [comment]
I personaly dont see it as a problem. Its not perfect but still understandable. Those grammatical errors dont change what the sentences mean. It only doesnt look nice.
Each language has its own way. I think fixing this for all languages would be a lot of work.
I think its better to keep it simple.

**Comment by BrettDong** [comment]
Thank you for your reply!


在 2016/11/19 下午8:20, ZenZen2 写道:

**Pull request merged**
