### PR TITLE
Ranged balance tests have archery in them now

### PR DESCRIPTION
**Pull request by Saint-of-Grey**
#### Summary
```SUMMARY: Features: "New ranged balance tests for archery"```
#### Purpose of change
Part of the requested changes for #35971 is a new suite of archery tests. Made into a separate PR since CI doesn't seem to like you fussing with the tests too much.
#### Describe the solution
Adds some new categories to `ranged_balance.cpp`, in this case, the bad shooter gets a self bow, the competent shooter gets a recursive bow with sights, and the good shooter gets a high-drawn compound bow with a bow scope.

The good shooter was... very accurate, so that's the only one with numbers not set relative to other guns. For the other two, I tired using numbers that other weapons were already using.

EDIT: Worth noting these were made with #35971 as a requirement, but they oddly enough still work without it. I'd still strongly recommend merging this after the archery redux.
#### Describe alternatives you've considered
Could always just fly fast and free, not conforming to any logic or reason!

(I'm told this isn't actually an option on a project this big. At least not one I can pick.)
#### Testing
Extensive trial and error. 

I'm not actually sure if that's the right way to get numbers. But, they pass the tests most of the time, from what I can tell. If someone has a better set of data in mind, or a good way to get it, please let me know.
#### Additional context
Made based on #27823, but the numbers actually pass the test.

### CODE REVIEW

**Comment by kevingranade** [comment]
The rationale for the numbers is in fact quite problematic, you made the various tiers of bows similar in performance to similar-ish tiers of guns that's not at all ok, especially at the low end.

On top of that, the selfbow isn't comparable to an entry-level gun it's comparable to a pipe gun, which we don't have in the tests because it's ridiculously bad.

I recommend either dropping the selfbow off the test or adding a lower-than-lowest tier for it, and as you line up bows against guns, the bows should be strictly worse than the guns, unless you have some sources that say otherwise.

At higher skill levels, the gap can narrow a bit, but bows should still be lagging behind guns in all cases.

**Comment by Saint-of-Grey** [comment]
I do know how many joules they deliver, and it seems like all the damage numbers derived from these this are multiplied by x2, unlike with guns. I'm not that attached to that solution, but I can't think of anything better that isn't a very heavy-handed nerf.

...upon examination, the sortbow and the selfbow are... very close in stats, which probably shouldn't be the case. I can swap the self-bow with the shortbow, and I'll look into cranking the dispersion on the selfbow up in the other PR. Could also remove it entirely, since it mostly exists to be an entry into archery. As for overall accuracy, I can push that down a bit, but a practiced archer can hit just as well as a practiced shooter, especially if using modern gear.

Is there an overall formula for converting real life range into cataclysm range? I can give you numbers of how far all the bows can roughly shoot in real life, but still not sure on cataclysm ranges.

**Comment by kevingranade** [comment]
> a practiced archer can hit just as well as a practiced shooter, especially if using modern gear.

This is a ridiculous assertion, have you done ANY research into effective ranges?
Even very pro-archery sources place maximum effective range at under 100meters, placing the top tier of bows in a similar neighborhood to good pistols and middling SMGs.
https://outdoortroop.com/how-far-can-a-compound-bow-shoot/

**Comment by Saint-of-Grey** [comment]
I suppose it depends what your definition of a "hit" is. Most hunters are trying to kill in one shot, since they prey has a tendency to run off after you hit it. That would certainly limit a bow hunter's effective range. Of course, if you just want to put an arrow in it, then your range extends much further.

**Comment by kevingranade** [comment]
> I can't think of anything better that isn't a very heavy-handed nerf.

This is a very problematic way of looking at it.  The goal is to represent reality, not maintain a particular balance point.  The degree to which it changes the status quo is irrelevant.

> I suppose it depends what your definition of a "hit" is.

If you want to push another interpretation, please provide the sources that back it up. Yes a bow hunter is generally aiming at a target no more than a few inches wide, and a Cataclysm "good hit" is probably significantly larger than that, but instead of just vaguely asserting a difference, work out what that means and provide some sources that support it.

> Is there an overall formula for converting real life range into cataclysm range?

No, compare the effective bow ranges to effective ranges of guns and check their actual vs in-game ranges.

**Comment by Saint-of-Grey** [comment]
> No, compare the effective bow ranges to effective ranges of guns and check their actual vs in-game ranges.

I would assume those without listed ranges are meant to shoot to the edge of the reality bubble then.

I can dig up the historical accounts of various longbow ranges, and for damage, I'll take another look at the terminal ballistics of an arrow versus a bullet.

**Comment by Saint-of-Grey** [comment]
Well, that's an odd one. I found a few sources saying that english longbowmen were expected, at minimum, to practice on a target 240 yards away. They were also aiming up, shooting it like artillery - all the scoping in the world isn't going to help with that.

This does seem to suggest that new forms of archery mechanics are needed if one wants to shoot at similar ranges. As for direct fire, I'm only finding secondary sources approximating range. There's an appealing looking formula though, trying to find sources to back it up before using it.

**Comment by kevingranade** [comment]
Ancient longbow volley fire isn't going to be particularly informative, the idea was getting arrows in the right general area and relying in numbers to get hits.  The point of placing the practice target at that distance was to force the archer to practice firing at that distance, which was near the maximum achievable. Finally, just because they practised with a target at that distance doesn't mean they *hit* the target, just that the arrow got that far.

At that range you literally cannot hit a moving person sized target, the flight time is several seconds, much too long to "lead your target" in any meaningful way.  As such unless we are in fact doing some kind of massed volley fire, there is no reason to support anything other than direct fire, which as far as I can tell limits effective range to ~90m, which in DDA for shooting purposes maps to about 15 tiles.

**Comment by kevingranade** [comment]
To reiterate and be more concrete about it:
Put max bow range at 15 tiles and rescale your tests to match, and you're done.
OR
find me sources for direct fire reliably hitting a person-sized target at over 100m.

**Comment by Saint-of-Grey** [comment]
> find me sources for direct fire reliably hitting a person-sized target at over 100m.

Darktoes' data does seem to point to a few people doing that with roughly 10% accuracy. It all seems anecdotal, this is the one part of archery that doesn't have extensive physics papers written on it. Anything he dug up indicating longer ranges seems to be indicating the shooter aiming at the sky, rather than the target. I'll adjust the tests

**Comment by Saint-of-Grey** [comment]
I seem to be running into a bit of an issue, code wise. In order for bows to perform at your expectations long-range, I need to increase dispersion by a factor of 500, which causes them to fail the short-ranged tests, among other things...

In my research, what I'm finding is somewhat accurate shots at 100, 150, even 200 meters IS possible if one has good enough equipment and the needed skill. The hard limit for distance seems to be the fact the arrow drops. A 10% hit chance at 400 meters actually makes a lot of sense, assuming similar ballistics to bullets, but practically, your arrow will start pointing down long before that.

Cranking up the dispersion to match expected behaviors at long range is going to make virtually zero sense at close range. I think we need better ballistic simulation overall for this to make sense.

**Comment by kevingranade** [comment]
> Darktoes' data does seem to point to a few people doing that with roughly 10% accuracy. 

10% is not "reliably", and if you can't share "Darktoes's source", it doesn't exist.  Frankly it really bugs me that you keep asserting sources that agree with you, but you haven't linked any of them.

> I need to increase dispersion by a factor of 500, which causes them to fail the short-ranged tests, among other things...

This doesn't make sense, the selfbow test was passing with ``test_shooting_scenario(shooter, 4, 5, 18);``, I don't see any reason that other bows can't pass with similar parameters and stats.
If you don't like some aspects of it, you need to be specific about what those are, because right now you're just making a lot of noise and wasting time because you refuse to be specific.

**Comment by Saint-of-Grey** [comment]
Because the selfbow was handled by a bad shooter, an expert shooter given more than 300 turns to aim never seems to miss, ever.

**Comment by Saint-of-Grey** [comment]
https://www.youtube.com/watch?v=7u-4CwlFZ-k
https://www.youtube.com/watch?v=6f-j17JD85I

Two sources I fully watched of people hitting the killzone of a deer from +100 meters. Can probably link a few more, but I'd rather watch them entirely first.

**Comment by Saint-of-Grey** [comment]
http://mimkr.bplaced.net/bc/

Found a ballistic calculator that shows overall drop, alongside the other aspects of arrow ballistics. Unless characters are rigidly holding their bows with their arrows perfectly parallel to the ground at all times, you can easily get ranges up to 100 meters and more (depending on how you adjust your launch angle, this calculator lets you do that). 

It doesn't account for wind, temperature, and barometric pressure, but that's why I thought it would be good for this game, since those aren't firing factors here anyway.

You need only to angle up 3 degrees with a compound bow, and your arrow will travel up to 125 meters before it drops 2 meters from it's launch height. Aiming with these kind of conditions is only really a matter of skill.

**Comment by kevingranade** [comment]
> That's because the selfbow was handled by a bad shooter, an expert shooter given more than 300 turns to aim never seems to miss, ever.

So change that too, no one said you'd be able to make it work by just touching the weapon stats.

You are latching onto the wrong things here.  One, some guy on youtube saying he's making a 100m+ shot *at a stationary target* is totally irrelevant.  Two, forget the ballistics, they don't mean anything.

**Comment by Saint-of-Grey** [comment]
Well then, after our talk on the discord and a nights sleep I decided I'll close this one for the time being and hammer out something batter.

**Pull request closed without merging**
