### PR TITLE
More realistic Javelin lengths

### PR DESCRIPTION
**Pull request by Ordasto**
#### Summary

SUMMARY: None

#### Purpose of change
As I was changing the Javelin pockets for a previous fix I noticed that Javelins were 90cm which is a bit to short for a Javelin
Modern Javelins are around 2-3 metres
Javelins like the Pilum were around 2 metres (Used by Roman Legionaries)
The further back you go the shorter they get it seems

#### Describe the solution

Increased both Javelins(Iron, Wood) to 140 cm and Javelin bag pockets to 150 cm

#### Describe alternatives you've considered

Making another javelin type that's 3m long for sports_store but the length of normal spears in game aren't that long

#### Testing
Imported the changed Jsons into my own version of the game and tested if they could go into the bag and were throwable

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>The further back you go the shorter they get it seems

So do the people using them, so that's probably got something to do with it.

**Comment by Ordasto** [comment]
> > The further back you go the shorter they get it seems
> 
> So do the people using them, so that's probably got something to do with it.

Good point

**Comment by Xenomorph-III** [comment]
can javelins be used for reach attacks?

**Comment by Ordasto** [comment]
Most spears in game are around 160 cm I think the longest "spear" is a pike which is 300cm in game in real life a pike can range from 3 to 7 metres.
the reason I didn't add the ability to reach attack is because I think it would mess with the balance a bit too much and I have no idea what the intended size of a tile is.

**Comment by kevingranade** [comment]
I don't believe javelins are stiff enough for you to hold one end and maintain reasonable control over the head for reach attacks, the thing would be wobbling all over the place and be quite fragile.

**Pull request merged**
