### PR TITLE
Fix plants spawning on dirt mounds

### LINKED ISSUE #50982: [0.F stable] Preplanted farm fields remain plowed after harvest, but player planted ones do not
### Describe the bug

Farm fields are now mostly planted with corn, but there are unplanted prepared tiles in the rows. Plant something with a reasonably short growing time in such tiles and wait for the corn to be ripe for harvest. Harvest both the corn and the PC planted tiles, and not that there are now gaps in the rows of furrowed ground where the PC planted crops grew.

### Steps To Reproduce

The description is basically a reproduction recipe...

### Expected behavior

Harvesting should behave in a consistent manner, i.e. either all furrowed tiles should revert, or none should, with the former presumably being the intended result.

### Screenshots

Screenshot (9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The issue isn't restricted to corn, but can be seen at any pre planted areas, such as community farm areas.

Looking closely at the screen, I can see that the pre planted tiles have a furrowed background, while the player planted ones do not. I suspect the issue arose when farms changed from being furrowed ground with harvested crops lying on top of it to planted fields. In that transition, the planted tiles should probably have had their furrowing removed, while the unplanted ones should keep it (or, if that's too hard to implement, not being furrowed, although that would increase the difficulty of first year farming).

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Fix plants spawning on dirt mounds"

#### Purpose of change

Fixes #50982
~Might be a solution (needs more testing) for: #55739~
Related to #55993, #53615

#### Describe the solution

Convert dirt mounds to dirt for plants on furniture creation

#### Describe alternatives you've considered

None

#### Testing

Created a new world, saw plants spawned without dirt mounds under them.

#### Additional context
Some dirt tiles exist which matches up with the code `"#": [ [ "t_dirtmound", 98 ], [ "t_region_soil", 2 ] ],`:
image
image

Oat field:
image
image

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Looks like a clever solution to the most important problem, assuming it works, as the testing indicates it does. The caveat is that I don't quite understand how this works (from farm.json):
"sealed_item": { "D": { "item": { "item": "seed_corn" }, "furniture": "f_plant_seedling", "chance": 70 } }
but if testing shows that it does place an f_plant_seedling furniture that triggers the conversion of the ground underneath it is splendid.

**Comment by PatrikLundell** [comment]
There should be a fairly large number of empty dirt mounds, as the seedling/seed sealed container thingy should spawn 70% of the time, thus leaving 30% empty. Thus, seeing them is a good sign.

As far as I understand from the snipped I posted above, f_plant_seedling is a "furniture" (but not a pseudo furniture: those are virtual items that mirror/complement corresponding actual furniture for crafting purposes), with some logic somewhere that causes it to be displayed as a plant of the species I assume the seed it somehow contains provides.

**Comment by haveric** [comment]
> There should be a fairly large number of empty dirt mounds, as the seedling/seed sealed container thingy should spawn 70% of the time, thus leaving 30% empty. Thus, seeing them is a good sign.

That seems accurate. I'm seeing a handful of regular dirt tiles as well, which is my concern, but I think it might just be some fields. Haven't had the chance to test more yet.

> As far as I understand from the snipped I posted above, f_plant_seedling is a "furniture" (but not a pseudo furniture: those are virtual items that mirror/complement corresponding actual furniture for crafting purposes), with some logic somewhere that causes it to be displayed as a plant of the species I assume the seed it somehow contains provides.

I was probably using pseudo too generally here as that's an actual thing as you've noted. I'm not sure on the actual plant code as I haven't dug that deep into the codebase... yet.

**Comment by PatrikLundell** [comment]
Yes, terminology gets messy when descriptive terms end up being the same with terms that have been given a specific meaning.

When it comes to the regular dirt tiles, I'd check whether they're actually supposed to be furrowed/planted, rather than part of the general background. As far as I understand there shouldn't be any in the furrowed/planted tiles, but I can't guarantee there isn't something I don't know that would result in these, such as e.g. some process that could cause crops to fail (I don't think there is one, but I don't know for certain that there isn't).

**Comment by haveric** [comment]
Looks like dirt is intended as 2% of the crops, so that confirms those aren't a bug at least:
`"#": [ [ "t_dirtmound", 98 ], [ "t_region_soil", 2 ] ],`

I also don't see dirt mounds created for basecamps, so I'm pretty sure that was fixed a while ago, possibly by you @PatrikLundell , although I think I found a new bug which is that planting fields in a basecamp shows they can return before they actually can. Not quite sure what's going on there. I thought it was using the max plants amount, but I think the time is somewhere between the seeds planted and the max seeds. (That or changing time via debug is not 100% accurate?)

**Comment by PatrikLundell** [comment]
Thanks for finding the dirt tiles.

I did nothing to change base camp dirt mounds, so if it has changed I can't take the credit for that.

I'm not aware of changing the logic for base camp planting, so either it's an old bug or something I've screwed up. I'll try to look into it, though.
Changing time via the debug menu seems to be exact. However, for some reason changing the time by exactly two hours for a task that takes exactly two hours does not allow you to return the companion: the time passed has to be greater rather than greater/equal. Don't know why, but I haven't changed it.

**Comment by haveric** [comment]
> However, for some reason changing the time by exactly two hours for a task that takes exactly two hours does not allow you to return the companion

This isn't that big of a deal and is really only seen when debugging, although it's probably an easy thing to switch.

> The code for farm missions uses a hard coded minimum time of 15 minutes

That definitely explains what I was seeing. Nice job figuring that out. Glad I mentioned it, because I was struggling to figure out why it was happening.

**Comment by PatrikLundell** [comment]
Yes, I'm glad you mentioned it too, as without that there wouldn't have been any reason to look at it closer. Once I knew there was a problem it didn't take long to see what it was, since I'm now fairly familiar with the code in that particular file.

**Pull request merged**
