### PR TITLE
Added no_thirst flag to metabolic rehydration

### LINKED ISSUE #47400: Metabolic Rehydration does not work
# Describe the bug

Thirst still goes up, dispite having the mutation "Metabolic Rehydration"

# Steps To Reproduce

Just wait and see the thirst go up.

# Expected behavior

Thirst wont go up with "Metabolic Rehydration", since the mutation normaly removes the thirst requirement.

# Screenshots
thirst2
thirst1

# Versions and configuration

 - OS: Windows 10.0 2004
 - Game Version: 0.E-9545-g034ac15-dirty [64-bit]
 - Graphics version: Tiles
 - Ingame language: English [en]
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

# Additional context

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fixed metabolic rehydration"

#### Purpose of change
Metabolic rehydration didn't have the no_thirst flag set

Fixes #47400

#### Describe the solution

Added the missing flag

#### Testing

- Add mouse mutations until you can add metabolic rehydration
- Watch your thirst disappear

### CODE REVIEW

**Comment by Fris0uman** [comment]
Is it that simple, no need to add a thirst_mod entry or something like that? Also is the description still right? It says that your first will be equal to your hunger, that doesn't seem right.

**Comment by Jamuro-g** [comment]
> Is it that simple, no need to add a thirst_mod entry or something like that? Also is the description still right? It says that your first will be equal to your hunger, that doesn't seem right.

From what i could see, there is no special code that handles this mutation (yet).
I don't know if it is still under development or if this is sufficient.

**Comment by Fris0uman** [comment]
I need to double check but I think that if you don't add `    "thirst_modifier": -1.0,` to it that trait is just making it impossible to slate thirst and so anyone with the trait will die of thirst. If you do add the thirst modifier it will remove thirst for good though, which might be OP, and is not really what the descriptions implies.

**Comment by Jamuro-g** [comment]
> I need to double check but I think that if you don't add ` "thirst_modifier": -1.0,` to it that trait is just making it impossible to slate thirst and so anyone with the trait will die of thirst. If you do add the thirst modifier it will remove thirst for good though, which might be OP, and is not really what the descriptions implies.

Character::update_stomach sets thirst for characters with the no_thirst flag to 0 everytime the stomach is updated and modify thirst also checks it.
From what i can tell, the only way to die from thirst with that flag would be if thirst gets set to lethal levels via set_thirst (instead of mod_thirst)

**Comment by Fris0uman** [comment]
Right, ok so it will remove thirst without problem. So I guess you just need to update the description then.

**Pull request merged**
