### PR TITLE
Remove non-ascii chars from comment

### PR DESCRIPTION
**Pull request by bkentel**

### CODE REVIEW

**Comment by kevingranade** [comment]
What's the rationale for this?

**Comment by KA101** [comment]
Can't say as I see any benefit here either.  Motion to close.

**Comment by BevapDin** [comment]
Running `./lang/update_pot.sh` fails because of that:

```
[...]
Loading data/mods/necromancy/necronimicron.json
Running xgettext to create .pot file...
Fixing .pot file headers...
Stripping .pot file from unneeded comments...
Check pot-file compilation...
Check for wrong Unicode symbols...
Unicode error on line 71768:
#. ~ This is a string to construct the item name as it is displayed. This format string has been added for maximum flexibility. The strings are: %1$s: Damage text (eg. �bruised�). %2$s: burn adjectives (eg. �burnt�). %3$s: sided adjectives (eg. "left"). %4$s: tool modifier text (eg. �atomic�). %5$s: vehicle part text (eg. �3.8-Liter�). $6$s: main item text (eg. �apple�). %7$s: tags (eg. � (wet) (fits)�).
                                                                                                                                                                       ^^^
Updated pot file contain broken Unicode symbols. Aborting.
```

It smoothly after applying the commit:
```
[...]
Running xgettext to create .pot file...
Fixing .pot file headers...
Stripping .pot file from unneeded comments...
Check pot-file compilation...
Check for wrong Unicode symbols...
Update finished. It's safe to commit.
```

**Comment by bkentel** [comment]
It wasn't just that it was non-ascii but some combining characters that multiple editors weren't particularly happy about. Nothing *bad"* per se, just created a bit of friction for no benefit.

**Comment by KA101** [comment]
OK, so "broke the pot-updater".  That's a serious problem and would have been helpful to know about.  Thanks, BevapDin.

**Pull request merged**
