### PR TITLE
Changed Chloromorphosis to work in more types of weather.

### PR DESCRIPTION
**Pull request by root-reindeer-flotilla**
Per my issue ( #23652 ) I took it upon myself to change this as best I could find. I am not a programmer, I simply tried to figure out what affects what.

I was going to edit "is_in_sunlight" but then I realized that would affect more things than my intention. My way is probably not the best, but I'm not a programmer so all I could do is work with what I see.

I used to have the name as "is_in_growablelight" but I thought of a slightly better name, "is_in_fairweather".

My intention was to make it so Chloromorphosis would work in more weather than just clear and sunny. As plants still grow in cloudy weather (otherwise seattle would be a desolate wasteland) I added: Cloudy, Drizzle, Raining, Flurries, and Snowing. I left out acid rain, heavy snow, and thunder and lighting storms for balance sake, though feel free to change that at will.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
You only use the function in one place, it would be better to just add those conditions where you use it.
You also enumerated pretty much all the weathers. At this point you should consider some other conditions.

For example, you could only check for `is_outside` and `g->natural_light_level` above certain threshold, then scale the hunger drop by `natural_light_level`.

**Comment by patq911** [comment]
yeeahhh the problem with that is at most I'm an editor, I can't come up with anything myself, especially because I know literally 0 c++ or any programming language.

I just gave it a shot and this was the best I could do. I could do slightly better if I know what the range of light levels were, I couldn't find that though.

``      if( calendar::once_every( 10_minutes ) && has_trait( trait_id( "CHLOROMORPH" ) ) &&
            g->is_outside( pos() ) && natural_light_level( p.z ) >= 40 ) 

        { 

            if( natural_light_level( p.z ) >= 50 && get_hunger() >= -30 )
            {
                  mod_hunger( -1 );
            }
            if( natural_light_level( p.z ) >= 60 && get_hunger() >= -30 )
            {
                  mod_hunger( -2 );
            }
            if( natural_light_level( p.z ) >= 70 && get_hunger() >= -30 )
            {
                  mod_hunger( -3 );
            }
            if( natural_light_level( p.z ) >= 80 && get_hunger() >= -30 )
            {
                  mod_hunger( -4 );
            }
            if( natural_light_level( p.z ) >= 90 && get_hunger() >= -30 )
            {
                  mod_hunger( -5 );
            }

``

so yeah, I tried to make it so it scales from -1 to -5 based on 10 increments of whatever scale light uses, but I really can't find it so I'm completely guessing it's by 10 and not like 1000.

**Comment by patq911** [comment]
Another thing I came up with. Simpler I guess.

```
if( calendar::once_every( 10_minutes ) && has_trait( trait_id( "CHLOROMORPH" ) ) &&
            g->is_in_fairweather( pos() ) && weather == WEATHER_CLEAR || weather == WEATHER_SUNNY || 
            weather == WEATHER_CLOUDY || weather == WEATHER_DRIZZLE || weather == WEATHER_RAINY || 
            weather == WEATHER_FLURRIES || weather == WEATHER_SNOW ) {
            // Hunger and thirst fall before your Chloromorphic physiology!
            if( get_hunger() >= -30 ) {
                mod_hunger( -5 );
            }
            if( get_thirst() >= -30 ) {
                mod_thirst( -5 );
            }
        }

```

**Comment by patq911** [comment]
Alright so I have no idea what I'm doing, I can't make it different like you said.

**Comment by patq911** [comment]
So I reverted to the build I submitted last night that actually worked. I'm sorry I couldn't do better.

**Comment by patq911** [comment]
huge distaster

**Comment by BorkBorkGoesTheCode** [comment]
@patq911 this can be salvaged. First, back up your work. I'll try to help afterwards.

**Comment by patq911** [comment]
@BorkBorkGoesTheCode I've been tinkering around and I have some type of solution. I compiled it and tested it and it works, though it works always now instead of certain scenarios. I deleted that fork because it was a disaster like I said above. this is my new one that doesn't commit straight to master.

https://github.com/patq911/Cataclysm-DDA/commit/08d239d9856c7c9d1972914f12adb10b0d674994

**Pull request closed without merging**
