### PR TITLE
Minor fixes for wasps and slugs.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Wasps:
Fixes a spelling error in their description.
Changes their icon to the period used by other tiny vermin - seeing that 'a' and thinking it was something bigger got old really fast.
Fixes their size - SMALL is the size of a cat; this should be TINY.

Slugs:
Were HUGE, now TINY.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ack. More derps on my end. @_@

Could've sworn some of the vermin was at small rather than tiny.

**Comment by Coolthulhu** [comment]
> Could've sworn some of the vermin was at small rather than tiny.

As far as I recall, slugs are huge. As in, hulk or tank drone sized.
Copy+paste is as dangerous as is it powerful.

**Comment by chaosvolt** [comment]
Oh wow. I thought it was...either the dragonfly, or one of the spiders, that I based the size off of.

Either that or I looked at mosquitoes being tiny, made note of wasps being quite a bit larger than mosquitoes, then blanked out a bit and forgot that there's a big difference (pun intended) between the tiny and small sizes.

**Comment by Rivet-the-Zombie** [comment]
We can fix slugs while we're at it.

**Pull request merged**
