### PR TITLE
Chopping trees rework

### LINKED ISSUE #22659: Chainsaw is inferior to wood axe
Game version: o.C-25440-g217f504

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: PK

### Expected behavior
Activated chainsaw uses gasoline and is significantly more rarer than wood axe. It should have tree cutting 3, or 4 to compensate for its rarity and/or difficulty in construction.

### Actual behavior
Woods axe is tree-cutting level 3, and as a hand tool is superior to powered tools. 

### Steps to reproduce the behavior
Standard behavior in game.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
- Moved chopping trees from construction to an item action, made it a long action (`a`ctivate woodcutting tool to chop down a tree);
- Time required to chop down a tree depends on tool quality and player's strength:
-- average player with 10 strength and a wood axe will chop down a tree in a half an hour;
- Changed `"AXE"` quality of some tools capable of woodcutting:
-- hand-made primitive tools such as `stone axe` or `copper axe`, and tools not quite suitable for woodcutting such as `lobotomizer` have 1 `AXE` quality;
-- factory-produced axes such as `wood axe` or `fire axe` have 2 `AXE` quality;
-- powered and turned on chainsaws have 3 `AXE` quality.
- Added messages following the process (based on pickaxe, burrow, and hacksaw activities);
- Closes #22659.

### CODE REVIEW

**Comment by Vidiveni** [comment]
Will sawing boards/chopping up tree trunks into logs get the same treatment?

**Comment by Night-Pryanik** [comment]
@Vidiveni what do you mean by "treatment" in particular?

**Comment by kasanryukin** [comment]
He means removing them from construction and adding them as item actions, such as with saws, circular saws and the like.

**Comment by Night-Pryanik** [comment]
I didn't plan to convert them right now, but maybe some time later..

**Comment by smolbird** [comment]
Um. Did no one think this one through? Now you can't chop down trees in a pure wilderness setting, using the resources available to you. Which completely stops dead most of the intended crafting and especially construction.

**Pull request merged**
