### PR TITLE
Update Radio Tower Mapgen

### PR DESCRIPTION
**Pull request by John-Candlebury**
### Summary

 ```SUMMARY: Content "Renovated radio towers to be actual towers."```

#### Purpose of change

Radio towers were very outdated, and didnt really resemble the real deal at all. So I made them actual climbable towers.

I also wanted this for a Hub sidequest.

#### Describe the solution

Climb the radio tower to scout nearby maps, the top might even contain cool stuff now.

#### Describe alternatives you've considered

Adding parkour minigames to tower climbing

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Looks really neat!
(Warning: Very long)
Screenshots:
radio-dead1radio-dead2
radio-dead3radio-dead4
radio-dead5radio-dead6
radio-dead7radio-dead8
radio-retro1radio-retro2
radio-retro3radio-retro4
radio-retro5radio-retro6
radio-retro7radio-retro8

**Comment by Petethegoat** [comment]
Excited to see this turned into a proper tower. Quickly skimmed the json and the submaps sound cool!
Probably all the generic roof bits (tarmac in deadpeople) should be turned into metal floors though?

**Comment by John-Candlebury** [comment]
Thanks for pointing that out @Petethegoat, those roofs shouldn't have been there at all. 
I tested this with z levels disabled, and I didnt realize they would appear

**Comment by Kanexan** [comment]
This is something super cool that we've needed for a long time! Thanks for making it!

**Pull request merged**
