### PR TITLE
Move the cockatrice to Mind Over Matter

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Mods "Move the cockatrice to Mind Over Matter."

#### Purpose of change
With #69208 removing the cockatrice from the base game, I figured that it might be a good addition to Mind Over Matter, considering its mutant nature.

#### Describe the solution
Move most of the cockatrice code to Mind Over Matter. I decided to make it a telepathic monster, which begins spawning 10 days after the Cataclysm in most places where chickens can be found and wandering the wilderness on occasion. I did modify the aggression and morale to match the hodag, so the cockatrice could actually attack, but the monster is otherwise the same as it was before.

#### Describe alternatives you've considered
Not doing this, or leaving it in the base game.

#### Testing
Went into the game, played around with the cockatrices. Punched one in a large group and died quickly when they ganged up on me.

#### Additional context
This relies on #69208 being merged. The cockatrice in this new form also has the tendency to gang up on threats with psychic barrages, much like the cuckoos from Legend of Zelda.

~I don't know about Mind Over Matter's lore all too well regarding psychic animals, so I don't know if psychic animals can birth more of themselves. I figured that the cockatrice's mutations and psychic powers were all caused by portal storms, and due to sufficient mutation, they could pass these traits on. @Standing-Storm is this lore-accurate?~

### CODE REVIEW

**Comment by Daved27hundred** [comment]
I dunno, does it have any specific powers or implied powers?

**Comment by MNG-cataclysm** [comment]
> I dunno, does it have any specific powers or implied powers?

It's telepathic, but can only use a psychic blast attack.

**Comment by Standing-Storm** [comment]
Nice, more psionic animals! 

I'm deliberately leaving the inheritance mechanics of psionic powers vague (because over the timescale of the game it doesn't really matter), but it's certainly possible to inherit powers from an awakened parent. I saw that regular chickens can rarely result from cockatrice parents, which is good.

> It's telepathic, but can only use a psychic blast attack.

One suggestion I have is to make this a fear-based attack (using telepathic_horror_monster), so it has a psionic version of the modern mythological "cockatrice freezing victims in place with its stare/turns them to stone," but the old mythology was that cockatrices killed victims with their stare so a telepathic blast does also work.

**Comment by MNG-cataclysm** [comment]
> One suggestion I have is to make this a fear-based attack (using telepathic_horror_monster), so it has a psionic version of the modern mythological "cockatrice freezing victims in place with its stare/turns them to stone," but the old mythology was that cockatrices killed victims with their stare so a telepathic blast does also work.

What if the cockatrice had both attacks? Would that be too powerful for an animal of this nature? Alternatively, could we combine both into a stare attack that applies fear and damages the target?

**Comment by Standing-Storm** [comment]
I think a combo attack is a great idea--I agree that giving them both as separate attacks would be too powerful (especially since they come in flocks).

**Review by Standing-Storm — APPROVED** [review]

**Pull request merged**
