### PR TITLE
Overmap terrains with dark gray color of symbol now have white color

### LINKED ISSUE #11737: dark_gray overmap tiles 'conflicting' with the toggle explored function.
Having dark_gray tiles on the overmap make the toggle explored function difficult to use as It won't make any visible change to the tiles.
I think the easiest way to go will be, to change the military building tiles colour (M, B) to light_green/green (witch in turn will make them hard to spot near forest...) And I got no Ideas for the parking Lot....

An other way to go may be to change the colour of the 'Explored' tiles.

I'll begin to drop PR once I'm comfortable with git (that will take some time) in the mean time I pray the Code Elders to ear/implement/push so of my ideas.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9867680-dark_gray-overmap-tiles-conflicting-with-the-toggle-explored-function?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #19816: Bunkers on the overmap the same colour as "already explored"
A little nitpick, but it's a bit of a pain you can't effectively mark bunkers -- and I guess to a lesser extent, roads -- as explored using the "[E] - Toggle Explored" option in the overmap, because the explored colour is identical to their unexplored colour.. 

Any chance of getting these recoloured, or is there some game engine limitation that prevents this?

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #19816.
Closes #11737.

Ranch camp, evac center, necropolis, mall, subway, parking lot, military bunker, military outpost, mine shaft, rat cave, basement, rock (old and new).
Didn't change road and hiway.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Some of the recolored parts are named "road" and so should have the same color as regular road.

**Comment by ZenZen2** [comment]
@Night-Pryanik Can you please review the colors from all the different parking places? they have the same symbol and color as garage. Its a bit confusing now.

**Comment by Night-Pryanik** [comment]
@ZenZen2 you mean parking lots in mall, necropolis and ranch camp?

**Comment by ZenZen2** [comment]
Yes please.

**Comment by ZenZen2** [comment]
@Night-Pryanik Yes please. Maybe the same color as roads?

**Comment by ZenZen2** [comment]
parking lots in mall are called "lot" on map and in towns are called "parking lot"

**Comment by ZenZen2** [comment]
In my opinion solid rocks shouldnt be white, its a bit eye hurting pressing map in the basement and geting a full white screen.

**Comment by Night-Pryanik** [comment]
@ZenZen2 You can create your own PR with all things you propose. Changing colors is easy, no programming knowledge needed.

**Comment by ZenZen2** [comment]
@Night-Pryanik You are right, i should do that myself, i have already changed them in my own game.
I will have to find out how github works. I will look into that when i have the time.

**Comment by DangerNoodle** [comment]
This was poorly thought out. You need to consider whether any map entries will appear identical to over entries.

**Pull request merged**
