### PR TITLE
Improve rendering performance by using robin-hood hash map (FPS improved ≈9%)

### PR DESCRIPTION
**Pull request by Aivean**
#### Summary

SUMMARY: Performance "Improve rendering performance by using robin-hood hash map (FPS improved ≈9%)"

#### Purpose of change

After the #44917  `cata_tiles::find_tile_looks_like` still takes significant percentage of `game::draw` time (although less than before). Combined percentage for all layers adds up to more than 6% of `game::draw` time. Most of that time is spent on tile lookup by string key in `unordered_map`. 

Also some rendering time is spent in `generic_factory` on `string_id::obj` lookups by dynamically constructed string_ids.

#### Describe the solution

`std::unordered_map` is not the fastest possible hash_map implementation for the `std::string` key. I did a quick research and found that there are commonly mentioned third party alternatives (see [benchmarks](https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-04-04-result-RandomFindString/)). 

I evaluated two of them, [tsl::robin_map](https://github.com/Tessil/robin-map) and [robin_hood:unordered_map](https://github.com/martinus/robin-hood-hashing).  

My test involved replacing `tileset::tile_ids_by_season` and `generic_factory::map` with different map implementation and performing several 30s rendering benchmarks on the same (backed up) save on the freshly started and loaded game.

The results were pretty good. Isolated map lookup time was ≈2x faster in my test (397ms total time before vs 204ms after), which is consistent with the third-party benchmarks.

As a consequence, combined time of  `cata_tiles::find_tile_looks_like` was reduced to  2.6% of  `game::draw`   (vs 6% before).

The measured FPS was improved by ≈9% , from 20.8fps before to 22.6 fps after (city scenario with clairvoyance, farthest zoom).

#### Describe alternatives you've considered

As discussed with @kevingranade, it's a good idea to have a good open-source alternative to `std::unordered_map` that can be carefully used in selected performance-critical places, where performance gain is noticeable.

I picked `robin-hood-hashing` over `tsl::robin_map` because performance difference between them was negligible, while `robin-hood-hashing` provides more useful collection types, specifically:
* `robin_hood::unordered_flat_map` 
* `robin_hood::unordered_node_map` 
*`robin_hood::unordered_node_set`
* `robin_hood::unordered_flat_set`    

([see details here](https://github.com/martinus/robin-hood-hashing#design-choices)). 

 `tsl::robin_map` is more feature-rich itself ([see details here](https://github.com/Tessil/robin-map#key-features)), but has weaker guarantees ([see here](https://github.com/Tessil/robin-map#differences-compared-to-stdunordered_map)). Specifically, this one:
> References and pointers to keys or values in the map are invalidated in the same way as iterators to these keys-values.

limits its usage significantly, while `robin_hood::unordered_node_***` collections can be used almost like a drop-in replacements for the std::unordered_map and set.

#### Testing

I did a smoke test of the game, but I haven't tested robin-hood map correctness, relying on their tests on github. 

#### Additional context

Before:
image

profiling (filtered, look at absolute values)
image

After:
image
image

### CODE REVIEW

**Comment by Aivean** [comment]
I'll need to double-check the memory usage.

**Comment by akrieger** [comment]
If folly didn't have such a huge dependency graph then I was going to put in a plug for the Folly F14 map implementations. Unfortunately they're SIMD accelerated so won't help mobile at all.

Abseil, however, has fewer (no?) external dependencies and recommends embedding in a project directly. Can you try their flat map which has performance on par with the Folly maps and better than these, per that benchmark you linked?

**Comment by Aivean** [comment]
Cross-compiling to Windows using i686-w64-mingw32.static-g++ is not working:
```
/usr/lib/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.5.0/include/bmiintrin.h:104:1: error: inlining failed in call to always_inline 'unsigned int _tzcnt_u32(unsigned int)': target specific option mismatch
 _tzcnt_u32 (unsigned int __X)
 ^
```

I'll try [suggestions from here](https://github.com/martinus/robin-hood-hashing/issues/98).

**Comment by I-am-Erk** [comment]
Are you still working on this?

**Comment by Aivean** [comment]
No, I should have closed it.

**Pull request closed without merging**
