### PR TITLE
Update Mutation armor Values

### PR DESCRIPTION
**Pull request by souricelle**
#### Summary
Bugfixes "Update Mutation Armor Values"

#### Purpose of change

Many armor values for mutations predate more recent armor updates that derive protection automatically from an item's thickness and its material. To bring skin mutations in line, I've gone through and determined new values using this system.

#### Describe the solution

To do this, I checked the flesh material's protection values at thickness 2 (average skin thickness on the human body is 2mm per google). It gives protection values of Bash 2, Cut 2, and Ballistic 2. As far as I know, a normal human character's skin doesn't offer these protection values, so I used this as a base value, then derived protection values for materials appropriate to each mutation and subtracted 2 from their bash, cut, and ballistic protection.

Ursine and Lupine Fur as well as Chitin Armor are stated to be thicker, so I brought them to 3mm. In the case of chitin/furred plate, I went up to 4mm as these mutations are described as being similar to plate mail (thickness 4 for gothic and 5 for normal). Lynx fur essentially adds 1mm to the thickness only on the character's head and stacks with the existing mutation, so it was given values of 2 across the board. Per light fur's description, it doesn't offer protection from attacks, so I left its values alone. I also left hairy chitin and furred chitin/plate's values to be determined by their chitin thickness, ignoring the hair on top of them. Scales/sleek scales use values derived from leather, and thick scales are 1mm thicker than that.

Phelloderm, Bark, Mycus Flesh, and Mycus Fireproofing were derived from wood. Bark and Mycus Fireproofing is thicker than human skin so it's stepped up by one millimeter in a similar fashion to the furs. Lastly, thick skin simply makes the character's flesh .5mm thicker, while thin skin does the opposite. These are traits that normal humans can have so it seemed appropriate to make them less drastic.

**Mutation: Bash, Cut, Ballistic**
Scales/Sleek Scales: 2, 2, 2
Thick Scales: 4, 4, 4,
Thin Skin: -1, -1, -1
Thick Skin: 1, 1, 1
Chitin, Hairy Chitin, Furred Chitin: 4, 6, 0
Fur, Sleek Fur, Feathers: 2, 2, 2
Gray Fur, Shaggy Fur: 4, 4, 4
Chitin Armor: 7, 10, 1
Chitin Plate, Furred Plate: 10, 14, 2
Phelloderm: 4, 2, 2
Bark: 6, 4, 4

#### Describe alternatives you've considered

Mycus might more appropriately be compared to chitin than to wood, or even biosilicified chitin since it talks about silica something or other, but I don't know much about the lore there. Thickness values could also be adjusted as needed, in particular chitin plate is very strong against ordinary zombies now, but the player probably wouldn't be worried about ordinary zombies anyway when they were post-threshold and the drawbacks are as serious as ever what with the dex debuff and permanent 10 encumbrance everywhere but eyes/mouth - which is more than you get from metal plate mail.

#### Testing

I loaded up the game and tried getting in fights with a few of these different mutations. As stated above, chitin plate was very durable in combat but a vanilla zombie did wind up clawing my unprotected eyes out after a while.

### CODE REVIEW

**Comment by actual-nh** [comment]
I'm a bit surprised that your chitin figure is 4, 6, 0; the base material is 3, 4, 1.

**Comment by souricelle** [comment]
My clever method for pulling these numbers appears to have been suspect. Looks like I have to get the right numbers and re-do the arithmetic.

**Comment by souricelle** [comment]
Chitin is: 
    "bash_resist": 3,
    "cut_resist": 4,
    "bullet_resist": 1,
    
    2mm of Chitin is therefore 6, 8, 2.
    
    We subtract 2, 2, 2 because that's the value for 2mm of flesh (which confers no armor to an unmutated human player, so we assume that -2 is a baseline), and get 4, 6, 0.

**Comment by actual-nh** [comment]
> @actual-nh
> 
> That's the first thing covered in **Describe the Solution**

Oops. Sorry about that.

> Chitin is (per 1mm):
> "bash_resist": 3,
> "cut_resist": 4,
> "bullet_resist": 1,
> 
> 2mm of Chitin (the average thickness of human skin) is therefore 6, 8, 2.

Ah! I was thinking that was rather thin; you're doing epidermis and dermis, but not hypodermis? (Possibly of interest: <https://www.nature.com/articles/s41598-017-15830-7>.) Your sources likely varied on whether they counted hypodermis as part of skin; it'd **_maybe_** double that 2mm on the **_average_**.

**Comment by souricelle** [comment]
The hypodermis is mostly made of fat so probably wouldn't be super different in a human with chitin or different integument. Also if we doubled those values we'd be looking at numbers that would require some pretty big adjustments on how these skin mutations work in general unless we wanted players walking around with huge runaway armor values all the time.

**Comment by actual-nh** [comment]
> The hypodermis is mostly made of fat and connective tissue so probably wouldn't be super different in a human with chitin or fur or w/e

True. (Heh. And there are some oddball similarities on those even between species - AFAIK, there's only one non-primate critter that can catch leprosy, and you wouldn't think its skin/hypodermis was similar to human at all - armadillos!)

> Lastly, as you alluded to, if something has stabbed through your skin and is all up in your fascia you are probably now taking damage.

Really, if you get into dermis, there's at least some damage - might not be enough to reach 1 hp, however.

**Pull request closed without merging**
