### PR TITLE
UI, Added color themes

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Interface "Added color themes for future use"

#### Purpose of change
Base colors of the game is ok when it used in terminal. But deeper the game goes into tiles and other graphical stuff the further those interface colors from main view. So I've created four different color schemes that can be used to improve UI.
Green and amber are just cosmetic and to provide additional varians.
White and dark are usable themes that is easier for eyes. 

#### Describe the solution
It would be great if player can change color themes from options menu like we can change tileset.
It is also possible to add another option similar to mobile users - use system theme. Then game can mimic bright/dark theme based on operating system theme.

#### Describe alternatives you've considered
It is acceptable if these themes will be presented in /config folder of installed game. So with small efforts players can change them via file explorer.

#### Testing
Dark theme examples:
image
image
image

Bright theme:
image
image
image

Green theme:
image
image
image

Amber theme (one screenshot):
image

### CODE REVIEW

**Comment by BrettDong** [comment]
JSON needs to be formatted: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md

**Comment by vetall812** [comment]
> JSON needs to be formatted: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md

Fixed.
Have to say that json validator is very strict.

**Comment by Inglonias** [comment]
You can use the makefile to style the json: `make style-all-json`

**Comment by leemuar** [comment]
This is interesting. So the game does not use abstract colors in the code like "form_bg_color", "health_bar_color", instead it uses direct color, and the way to create color themes is to redefine what BLACK is? BLACK can actually be white or red?
Looks hacky

**Comment by bombasticSlacks** [comment]
This is great I've been using the dark theme colors and really liking it. I'm leaving it up right now since someone else might have a better way of storing it or want to add an in game menu.

**Comment by sonphantrung** [comment]
> This is interesting. So the game does not use abstract colors in the code like "form_bg_color", "health_bar_color", instead it uses direct color, and the way to create color themes is to redefine what BLACK is? BLACK can actually be white or red?
> Looks hacky

Yes, it’s the terminal-y color scheme configuration, BLACK can be any colors possible

**Comment by vetall812** [comment]
> This is interesting. So the game does not use abstract colors in the code like "form_bg_color", "health_bar_color", instead it uses direct color, and the way to create color themes is to redefine what BLACK is? BLACK can actually be white or red? Looks hacky

Fun thing is that minimap is using some colors defined in the color scheme BUT some (i've noticed red for enemies for example) are hardcoded.

**Comment by bombasticSlacks** [comment]
> Fun thing is that minimap is using some colors defined in the color scheme BUT some (i've noticed red for enemies for example) are hardcoded. 

if this gets added to the game I imagine a number of the hard coded colors will get fixed since it will become obvious.

**Comment by leemuar** [comment]
> > Fun thing is that minimap is using some colors defined in the color scheme BUT some (i've noticed red for enemies for example) are hardcoded.
> 
> if this gets added to the game I imagine a number of the hard coded colors will get fixed since it will become obvious.

A lot! But that's a good refactoring

**Comment by Maleclypse** [comment]
This is excellent!

**Comment by bombasticSlacks** [comment]
Infrastructure is done

#58856 so I'm gonna merge this

**Comment by leemuar** [comment]
I would love to continue this awesome work and add a distinct object ThemeManager and abstract color definition to it: bg_color, text_color, limb_damaged_color etc. It will require a lot of refactoring, but I think it is worth it

**Comment by Zireael07** [comment]
@leemuar: Please do. I often find many premade themes to be too constrasting for me (I'll likely try out amber and dark first, white looks painful already)

**Comment by leemuar** [comment]
> Also, right now there are just like... 5 of backgrounds, can we make more?

Yes, we could register and use any color with ThemeManager

**Pull request merged**
