### PR TITLE
Add HitButton_iso tiles for rain gutters and downspouts, better Foodperson head, and more

### PR DESCRIPTION
**Pull request by kristleifur**
#### Summary
```SUMMARY: Interface "Add HitButton_iso tiles for rain gutters, some rooftop props, Truly True Foodperson, and more"```

#### Purpose of change
Added HitButton_iso tiles for the recently-arrived rain gutters. Plus some more stuff like roof things. And including a new Foodperson mask that looks like the description in the original pull request! A big head!

Also cropped empty tiles off the bottom of the big hitbutton tilemap for some minuscule space and time savings.

#### Additional context
Screenshot 2019-06-27 at 23 51 32

Here we see True Foodperson enjoying the view of the roofside rain gutters, some antennas, a vent, and a solar panel.

### CODE REVIEW

**Comment by AnthonBerg** [comment]
Sharp-eyed readers will notice that the new Foodperson head is a real honest-to-goodness IBM DOS BIOS smiley-face character.

**Comment by AnthonBerg** [comment]
And in all seriousness, please let me know if it's better to save these tile additions up for fewer and bigger pull requests.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
> please let me know if it's better to save these tile additions up for fewer and bigger pull requests.

No. Smaller PRs are incomparably easier to review and therefore and more likely to merge.

**Pull request merged**
