### PR TITLE
Adds argument parser so commandline documentation can be inlined. fix #7289 [WIP] [CR]

### LINKED ISSUE #7289: Documentation for Command-line options
DF has command line.txt   
CDDA has many more options and I can't say that i know where the documentation for them is. So I just went though main.cpp and by a very unscientific method arrived at the following:

```AsciiDoc

Cataclysm: Dark Days Ahead recognizes the command line options explained in this file. 
They are not required.

 GLOBAL
 --seed <string of letters and or numbers>
	 initializes the random generator

 CHECK
 --jsonverify
	 checks the cdda json files
 --check-mods
	 checks the json files belonging to cdda mods

 FILE PATHS
 --basepath
	 
 --datadir
	 default paths for the ./data directory
 --userdir
	 default paths for user-overrides to files from the ./data directory and named below
 --savedir
	 path to save-files. 

 FILE NAMES
 --optionfile
	 overrides name of "options.txt" 
 --keymapfile
	 overrides name of "keymap.txt" 
 --autopickupfile
	 overrides name of "auto_pickup.txt" 
 --motdfile 
	 overrides name of "motd" 

```

this got started by me looking at the proposed map-sharing code.
map-sharing would add these options:

```AsciiDoc
MAP SHARING
 --shared
	activates the map-sharing mode when present.
 --competitive
	instructs map-sharing code to disable access to the in-game cheat functions.
 --username <username>
	tells the map-sharing code to use this name for your character.
 --addadmin <username>
	tells the map-sharing code to use this name for your character 
	and give you access to the cheat functions.
 --adddebugger
	informs map-sharing code that you're running inside a debugger
```

I'll take your comments and integrate them into the above until someone decides on a name and place for it .. can't see me adding to the top of the tree ;)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1736709-documentation-for-command-line-options?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abaire**
Attempts to address #7289 by bundling documentation with the command-line flags. This way they'll theoretically stay in sync as updates to the actions will be made next to the docs.

It doesn't conform to the style used in the rest of the codebase, I wanted to make sure this is a reasonable direction before renaming/reformatting. Also hasn't been tested on Windows yet.

### CODE REVIEW

**Comment by abaire** [comment]
Fair enough. My hope was that the level of understanding necessary would be limited to the (to-be-fully documented) API but there is certainly a requirement for code maintenance.

How do you feel about lambdas in general? Assuming getopt_long is available on Windows I wonder if something like:

struct commandline_param {
  int pass;
  std::string documentation;
  std::string help_group;
  struct options;
  std::function<bool(const char *maybe_param)> handler;
}; 

might work? This way it's still relatively straightforward to abstract out documentation generation and any flag interdependencies and preserve the benefit of keeping the flag handling code next to the definition as it is today. It'd end up being somewhat similar to the proposed change but would remove all the ArgHandler subclassing and push a bunch of the argv management out behind getopt_long.

**Comment by kevingranade** [comment]
Sorry for the delay, lost track of this one.
That sounds like a reasonable way to go, but I wonder about just populating a simple container of {flag, function, documentation} tuples and dispatching to that as needed.

**Comment by abaire** [comment]
No problem, took me awhile to get back to this myself.

I dropped the argparse classes and switched to a simple struct in main.cpp. I didn't bother with getoptlong as the existing parsing code was simpler than having to set up getopt structs in addition to the documentation structs.
There are still some opportunities to reduce some code duplication around the multiple parsing passes, please let me know if this general approach looks good to you and if you think lambda-izing the parsing loops is worthwhile.

**Comment by KA101** [comment]
Any thoughts on moving this?

**Comment by kevingranade** [comment]
It looks good now, I'm on it.

**Pull request merged**
