### PR TITLE
Farm Tractor Changes

### PR DESCRIPTION
**Pull request by chaosvolt**
Remind me to rename the Tankmod tractor (heavy tractor, maybe) and possibly give it variants, now that we have tractors that DO something in mainline. I might do that in this PR actually, alongside making use of the new farming vehicle group...
1. Changed part slot numbers so that 0/0 isn't an unboardable location, fixing an error that cropped up when spawning tractors via debug.
2. Changed vehicle layout to cover the exposed diesel tank and otherwise clean up the appearance (this might need further tweaks).
3. Replaced V8 engines with V6. Even then it's still pushing 100+ MPH safe speed. Couldn't find reliable info on engine differences between smaller open-top tractors and enclosed-cab models.
4. Fixes advanced seed drill part not using the advanced seed drill item to build.

### CODE REVIEW

**Comment by chaosvolt** [comment]
And add http://smf.cataclysmdda.com/index.php?topic=11325.0 to my to-to list. @kevingranade, this (and the earlier redundant vehicle.cpp definitions) is why the majority of PRs tend to be assigned to another dev instead of self-merged, even when it's another collaborator doing the pull request. Having a second pair of eyes during the merging process is a good thing.

**Comment by BevapDin** [comment]
> EDIT: And for an issue I don't think I can fix, plows don't seem to be churning up the ground like they should.

Have you turned it on? Did you drive across diggable terrain (e.g. dirt or grass)?

**Comment by chaosvolt** [comment]
The controls menu listed no option to enable/disable the plows.

**Comment by chaosvolt** [comment]
Okay, this is just plain weird.

dafuq

I'd initially encountered an issue when testing in build 3725, and vehicle plows were FUBAR both before and after adding the changes this PR made.

Then, as I mentioned later today, testing with a later build (need to start up my laptop to check exactly which build) revealed the plow was working both before and after dumping the PR's changes into it.

I didn't see any mention of recent PRs unfucking plow functioning, so I had no idea what caused it and what fixed it.

**Comment by kevingranade** [comment]
> @kevingranade, this (and the earlier redundant vehicle.cpp definitions) is why the majority of PRs tend to be assigned to another dev instead of self-merged, even when it's another collaborator doing the pull request. Having a second pair of eyes during the merging process is a good thing.

That's fucking rude man, and you're wrong about it.  I *wrote* the damn policy that people don't merge their own PRs, and I follow it.  I made a mistake *while merging BevapDin's fixes to the branch*.  I had previously posted the PR for review, and got a "this works, except for bla bla" from BevapDin.  After I said something about being too busy to get back to it right away, BevapDin posted the fixes to the issues he had raised.  I pulled, merged, built and tested those changes.  In the meantime someone merged something else, then I merged again and pushed.  I should have rebuilt, I should have rebuilt and tested, but it was midnight and I'd been working on it for several hours already (the merges were a mess because of the way the original developer did their commits, not "wrong", but it makes merging hard).  Yes that was a mistake, but it's not cool for you to call me out on it multiple times in public.  I've cleaned up your messes a number of times, but I don't chew you out for it, and I expect some common courtesy here.

**Comment by chaosvolt** [comment]
Sorry about that. I shouldn't have put it that way, yes.

Admittedly I can be just as prone to mocking my OWN mistakes on commits. >.>

**Comment by chaosvolt** [comment]
And...given it was had gone through so many changes and had already changed hands at least once, it's understandable. I shouldn't have gotten pissy about it.

**Comment by BevapDin** [comment]
> I'd initially encountered an issue when testing in build 3725, and vehicle plows were FUBAR both before and after adding the changes this PR made.

Build 3725 does not have plows or any of the farming parts. It's based on 55864e9c6dac4ae723c024bba905a9f559ce77f5, which is right *before* the farming stuff PR was merged. Whatever plow/reaper/planter part you have tested there could not have worked. The next build (http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/3726/) has the farming parts.

> Then, as I mentioned later today, testing with a later build (need to start up my laptop to check exactly which build) revealed the plow was working both before and after dumping the PR's changes into it.

Yes, because the farming PR was merged in the meantime and is therefor included in the "later build". Next time, please state the versions you have issue with and *what* you have changed in it.

**Comment by chaosvolt** [comment]
Huh. That is weird. I could've sworn I tested it before dumping my changes into the game. More importantly, that test didn't include any vehicle part tweaks, so if it was unedited it should've puked up an error about the relevant parts not existing.

I can only assume I dumped some other JSON folders in it for testing before and utterly forgot. ._.

**Pull request merged**
