### PR TITLE
STR-dependency for muscle engines

### LINKED ISSUE #85: Bicycle enhancements 0#0
Some basic new features to round out bicycles.
Limit foot crank to operating when the player or a NPC is in the same square.
Derive foot crank power from player or NPC in same square.
Rebalance bicycle speed.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1366729-bicycle-enhancements-0-0?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by illi-kun**
Put proper flag to oars, updated names of flags.
Closes #85.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Old issue is old! Nice!

**Comment by Coolthulhu** [comment]
Why are the hand rims (and oars) penalized so much compared to pedals when it comes to scaling? People generally vary more in arm strength than leg strength and the strength stat changes arm strength more than leg strength (for example, bashing and weapon damage is affected more than weight capacity).
Also, instead of hardcoding the flat scaling, you could instead tie it to part's base power. Say:
```
pwr_factor = base_power * str / 10
```

**Comment by tyrael93** [comment]
I think it's the face that you can go at 30 mph on a wheelchair without damaging any parts of the wheelchair itself even if your speedrange is critical (in the reds). Muscle cars' high speeds only influence stamina consumption and since you don't get penalties from pedaling at full stamina or ":" stamina, I guess being able to go around at 30/40 mph for free only using a wheelchair is pretty silly.

**Comment by DavidKeaton** [comment]
They see me rollin...

**Comment by Coolthulhu** [comment]
Bug not caused by this PR, but tangentially related:
* Going above certain speed doesn't make the car go faster. Despite biking at 10k mph, my debug bike is still only traversing ~15 tiles

**Comment by sparr** [comment]
@Coolthulhu arm power for vehicles is more about stamina than momentary strength, unlike bashing.

**Comment by kevingranade** [comment]
Either vehmove or vehproceed has an arbitrary cap on total speed allowed,
feel free to remove it.

**Comment by illi-kun** [comment]
@Coolthulhu, I've tried to set presented flat scaling for making it reasonable, your approach about scaling of base factor is more general but it's not necessary until we have very few muscle-driven engines. Hand rims were nerfed intentionally for making it not so fast.
Sorry for late answer and thanks for merge.

**Pull request merged**
