### PR TITLE
Drop useless plasma fuel code

### PR DESCRIPTION
**Pull request by mugling**
It doesn't exist any more so we don't need code support for it either

### CODE REVIEW

**Comment by Coolthulhu** [comment]
BTW how much until fuels are fully jsonized?
Is it just those two lines per fuel type?

**Comment by mugling** [comment]
Pretty much just those two (explosions and smoke). Are we keeping fuel explosions - I recall you had objections to them?

**Comment by Coolthulhu** [comment]
I personally don't like them because they don't add anything good to gameplay and are also unrealistic as fuck, but most others seem to like them. I guess it's the same kind of wacky action movie flavor as flaming weapons, death rollers and laser guns.

**Comment by BorkBorkGoesTheCode** [comment]
Explosions from gas tanks could be replaced with fiery gas puddles.

**Comment by mugling** [comment]
@illi-kun this PR would also be helpful if that's practical for you so as to avoid a merge conflict when I drop the hardcoded smoke values for gasoline and diesel

**Comment by mugling** [comment]
@illi-kun thanks

**Comment by illi-kun** [comment]
np!

**Pull request merged**
