### PR TITLE
Fixed weird changing room windows

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
None

#### Purpose of change

Passers-by shouldn't have a clear view of a school's changing rooms.

kép

#### Describe the solution

I replaced the windows with ones that have curtains.

#### Describe alternatives you've considered

None.

#### Testing

Debug-spawned a regional school.  You can't see inside the changing room from the street anymore.

#### Additional context

None.

### CODE REVIEW

**Comment by NetSysFire** [comment]
Don't schools usually have frosted glass for this? So theres still light coming through but you can only see shadows at most.

**Comment by NetSysFire** [comment]
There are two solutions here:

- Add frosted glass windows. Should not be too difficult, basically it has to let light through but blocks sight.
- Add some other lighting if possible like a ceiling lamp or a skylight.

The latter solution is probably the easiest. All the bathrooms you find in houses would benefit greatly from the former solution.

**Comment by LovamKicsiGazsii** [comment]
> There are two solutions here:
> 
>Add frosted glass windows. Should not be too difficult, basically, it has to let light through but blocks sight.
> 
>Add some other lighting if possible like a ceiling lamp or a skylight.
> 
> 
> The latter solution is probably the easiest. All the bathrooms you find in houses would benefit greatly from the former solution.

Unfortunately, frosted glass can't simultaneously let the light through and block vision due to JSON limitations.  Should I add it in anyway or wait until someone makes a `TRANSLUCENT` flag?

**Comment by 337722** [comment]
You can hang a curtain on the window.

**Comment by Maleclypse** [comment]
I'm questioning my sanity here but @Fris0uman were you working on making stained glass windows allow light but block sight?  I couldn't find it in your PR list when I looked but maybe I overlooked it?

**Comment by Zireael07** [comment]
@Maleclypse I think they didn't get around to making a PR for it, just throwing out ideas

**Comment by LovamKicsiGazsii** [comment]
I replaced it with closed curtains instead.  Not sure why the lack of natural light was an issue, but fine I guess.

Once we have proper frosted glass, those should be used here.

**Comment by Fris0uman** [comment]
@Maleclypse  No, I just made a feature request about it https://github.com/CleverRaven/Cataclysm-DDA/issues/56633

**Pull request merged**
