### PR TITLE
Removed lamp oil as valid fuel for engines and oil burner CBM

### PR DESCRIPTION
**Pull request by Ilurker**
#### Summary
Balance "Remove contaminated fuel sources"

#### Purpose of change

Removes the ability for diesel engines and the Oil Burner CBM to burn lamp oil, as the current lamp oil recipe does not produce kerosene or a related product. The current recipe for lamp oil can be, and is likely most commonly, produced using materials as crude as an open fire, a pot, and food products like vegetable oil or unprocessed mutant fat. Removal of the item from valid fuels preserves the realistic practice of home-crafting lamp oil without allowing for players to substitute boiled animal byproducts for refined hydrocarbons.

#### Describe the solution

By allowing both the use of lamp oil as a fuel and player crafting thereof, the game simulates operating high-performance diesel engines by effectively pouring unfiltered olive oil and beef tallow into the engine, presuming they took the time to boil them first. It is common, and effective, to use these dirty and poorly refined fuels for their intended purpose of lighting lamps, and most use cases of lamp oil production will be towards that end, so the most reasonable solution is to remove lamp oil, as is, as a valid hydrocarbon fuel, as they would produce catastrophic engine fouling, presuming they reached ignition at all.

#### Describe alternatives you've considered

Removing craftable lamp oil, replacing lamp oil spawns with kerosene (more appropriate as a separate PR).

#### Testing

Spawned diesel vehicle, confirmed it no longer allowed the selection of lamp oil as a fuel type. 
Spawned and installed Oil Generator CBM, confirmed it did not recognize lamp oil as a fuel type

#### Additional context

While kerosene itself can be added to diesel without much harm, operating a diesel engine on refined kerosene alone creates its own set of fouling and reliability issues. As unknown degrees of fouling has been identified as a fuel-excluding factor in the case of avgas varieties which may contain low lead content (#58181), it would be inappropriate to assume kerosene monofuel should be integrated without a PR to examine its realism.

Biodiesel, in its current form, suffers from nearly the exactly same realism concerns, having a recipe that effectively heats organic fats with a saponifying agent and then cutting it with ethanol to create "fuel". This appears to have little similarity to the actual processes used to create biodiesel and would also result in extremely crude, contaminated fuel. As biodiesel doesn't have a use case outside of fuel, it is more appropriate to update its recipe to be much more complicated, with higher yields to compensate.

### CODE REVIEW

**Comment by Termineitor244** [comment]
Uhhhh... #58201

**Comment by Ilurker** [comment]
You unfortunately can't make kerosene via the routes in the recipies. I do believe there would be a very strong use case for creating a separate kerosene item type and using it to make diesel blends, but that would have been a much bigger PR.

**Comment by kevingranade** [comment]
As this will break existing games, (i.e. Someone stocking up on lamp oil and being left stranded by this change), it's a no-go. I'd be perfectly happy with renaming to kerosene and tightening up the recipes though.

**Comment by pushard** [comment]
I am sorry for the strong words but thit is the most stupid idea I've ever seen.... Clay OIL lamp can't use LAMP OIL any more.

**Pull request closed without merging**
