### PR TITLE
Fix zombie insta-healing after reviving

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Fix zombie insta-healing after reviving"

#### Purpose of change

Found this bug while testing #51183
Most zombies are not supposed to instantly heal all hp after reviving (unless flagged with REVIVES_HEALTHY), but rather very slowly (1 point per hour, as set in `monster::on_load`).

#### Describe the solution

In `game::despawn_monster()`, put the call to `critter.on_unload()` which updates the monster's `last_updated` time _before_ the call to `overmap_buffer.despawn_monster` (which stores inactive monster), otherwise the change to `last_updated` is not persisted. Without the fix, when they spawn back into the reality bubble, this makes the game simulate multiple days of healing (since time 0), which fully heals them.

I also included some tangential code cleanup (refactoring and simplification) for code related to this. I tested all of the changes together.

Edit: I also adjusted the heal rates as suggested by @Venera3 to scale off of max hp.
I changed it to 2% of max hp per hour for zeds and 0.05% of max hp per hour for critters.

#### Testing

Spawn a normal zombie, kill it, wait until it revives. It is very low on HP:

image

Teleport away (so the zombie despawns), wait 1 turn and teleport back. Without the change, the zombie is at full HP.

image

With this change, the zombie is still nearly dead when you come back.

image

Teleport away, wait 6 hours and come back. The zombie healed a bit more.

image

You have to wait a couple of days (max hp / 24) for the zombie to fully recover. During this time its speed is also impaired and recovers gradually. 

It is very easy to re-kill a recently reanimated corpse now.

I also did a test with a dissolute devourer, which has a natural healing rate of 1hp/turn. That's in https://github.com/CleverRaven/Cataclysm-DDA/pull/51183#issuecomment-907747848

#### Additional context

Some questions regarding game balance:

Should the default zombie heal rate of 1hp per hour be buffed a little?

Should they recover their max speed stat sooner than before they're fully healed?

### CODE REVIEW

**Comment by Venera3** [comment]
I think a max hp-based regen would be more useful (to keep it 1hp/hour for a zed `0.12*max_hp` or similar), otherwise a hulk needs half a month to regenerate to full. I'd also either normalize normal critters to half the zombie rate, or add a `regen_rate` field to monsters to allow fine-tuning - in this case the hardcoded material requirement could be removed entirely.

**Comment by eltank** [comment]
> I think a max hp-based regen would be more useful (to keep it 1hp/hour for a zed `0.12*max_hp` or similar), otherwise a hulk needs half a month to regenerate to full. 

Sounds good, I'll do that.

> I'd also either normalize normal critters to half the zombie rate, or add a `regen_rate` field to monsters to allow fine-tuning - in this case the hardcoded material requirement could be removed entirely.

Normal critter regen is currently a quarter of the zombie rate. They don't have magical blob powers.
I'll make that scale off hp as well.

**Comment by eltank** [comment]
Done. 2%/hour for zeds, full heal in ~2 days.
I believe this will include animals that can zombify (which makes sense, they already have blob in them).

0.5%/hour for critters, full heal in ~8 days.

**Comment by eltank** [comment]
Out of scope for this PR, but I think we should simulate corpses reviving outside the reality bubble by running catch-up code on any z corpses entering the reality bubble (figure out when they would have revived and if it's in the past then instantly raise the z and heal it based on time passed since the simulated revival).

**Comment by Venera3** [comment]
Definitely, now you have this weird window of opportunity to spawnkill them the first time corpses get loaded. Agree on it being out of scope for now, though.

**Comment by actual-nh** [comment]
Re PR text - `last_updated`, not `last_update`.

**Pull request merged**
