### PR TITLE
Switch gender in game

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Features "Switch gender in game"

#### Purpose of change
Add an option to switch gender at any time in game

#### Describe the solution

Pressing `y` in the `@` menu switches the gender

#### Testing

https://user-images.githubusercontent.com/41293484/130859505-59835e3d-4c13-413f-9786-23a0de0066d0.mp4

### CODE REVIEW

**Comment by realbang** [comment]
I think that its a good thing, but to add to the realism that the game strives to achieve i suggest adding feature of 30% chance of suicide some days after the gender change so it would match the real world statistics.

**Comment by MooseyHey** [comment]
What an awful decision.

**Comment by basedcringe** [comment]
I hate trannies

**Comment by Iksman** [comment]
Why do people with mental disabilities influence the development of the game? I am against this patch.

**Comment by nobodysu** [comment]
Why personal preference should affect the game world? Is this a game or constructor? This PR is a major hit to [suspension of disbelief](https://en.wikipedia.org/wiki/Suspension_of_disbelief).

By the same logic, I prefer to set all my stats to 20 at will. Or set health of anything in my aim to zero.

**Comment by Winterous** [comment]
Lot of dumb responses.
@nobodysu This isn't changing your physiology, it's just changing how your character is presenting to themself and the world; so no it doesn't affect suspension of disbelief. You aren't psychically changing the world, you're just changing your mannerisms or something like that, playing pretend. So chill.

**Comment by nobodysu** [comment]
@Winterous 
>You aren't psychically changing the world

Related video clearly contradicts that.

>you're just changing your mannerisms or something like that, playing pretend.

Consequences for which is only applicable in NPC interactions, which should be done in text format and player actions, otherwise it's bad game design. Role playing and game mechanics should complement, not supersede one another, by definition.

**Comment by FindusCrispyPancakes** [comment]
Just look at all the deleted responses. Shame on this dev team for such an awful addition to the game and then for censoring the community. 

This update is nothing more than the devs forcing their political beliefs into the game & onto the rest of us. These devs are clearly using the game as a vehicle for their personal politics. 

CDDA players like me are simply asking themselves "How can I remove this from my game?" Shame on this dev team.

**Comment by I-am-Erk** [comment]
Please stop using a closed and resolved PR to complain about your inability to understand gender. Even if one of you had a relevant point, it would remain off topic as a closed PR is never the appropriate place to complain about a feature.

**Pull request merged**
