### PR TITLE
Content: Add vehicle back seats

### LINKED ISSUE #45654: Cars with backseats?
I feel like most cars should have real back seats instead of just normal "front seats".
Here's a mockup of how it would look like. **What do you think?**
This change would be mostly cosmetic.

Mockup:

car-back-seat-mockup

This is how cars look right now:
car-back-seat

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Content "Add vehicle back seats"`

#### Purpose of change
 
- This adds back / rear seats (normal and leather) to the game to improve realism and immersion..
- Already spawned vehicles are not affected.
- Closes #45654.

Changelog:
- Removed item and recipe
- Added wooden bench
- Added more comfort, storage capacity and warmth to normal back seat and leather back seat.
- Added back seat shapes.
- Added back seats to vans_busses.json
- Added back seats to emergency.json
- Added back seats to carts.json
- Added back seats to cars.json

My thanks to @curstwist, @Fris0uman and @l29ah for their help, suggestions and answers.

#### Testing

- Compiled using microsoft visual studio 2019.
- Checked that everything is working as expected.
- Testen on small screens.
- Spawned every altered vehicle.
- Installed and removed the new seats.

#### Screenshot(s)

For now, this is just a model / mockup. Tileset creators will decide what the rear seats will actually look like.

car-back-seat-mockup

This is how normal cars look right now:

car-back-seat

Shapes:
grafik

grafik

This is how they ended up looking with the UndeadPeopleTileset:

https://github.com/SomeDeadGuy/UndeadPeopleTileset
- I made three variations of the horizontal ones (seat_back_left - seat_back - seat_back_right)
- And three variations of the vertical ones (seat_back_vertical_left - seat_back_vertical - seat_back_vertical_right)
-> So there's still room for improvement here - which is totally up to titlesetmakes

grafik

grafik

### CODE REVIEW

**Comment by Fris0uman** [comment]
So it's a special part with it's own recipe but it has the same stats as a regular seat?
Shouldn't it work more like chiral parts and not actually require a new item/vehicle part since it's just a cosmetic thing?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> So it's a special part with it's own recipe but it has the same stats as a regular seat?

-> I'm not planning it to be an exact copy. It probably would use up more material and what not.

> Shouldn't it work more like chiral parts and not actually require a new item/vehicle part since it's just a cosmetic thing?

-> Can you give me an example?

**Comment by Fris0uman** [comment]
Something like this https://github.com/CleverRaven/Cataclysm-DDA/pull/42803

**Comment by curstwist** [comment]
It should offer more storage then 2 adjoined seats and probably similar sleep bonus as a couch as well.

**Comment by Pupsi-Mupsi** [comment]
Can someone help me out with the storing capacity of seats and reclining seats? I'm not sure why a reclining seat should only hold 6.25 liter while a regular seat stores 25 liter.

grafik

grafik

**Comment by Pupsi-Mupsi** [comment]
@curstwist 
Is the woodbench okay like this?
-> It's a bit more durable than a standard wood seat.

@Fris0uman
-> Is this what you had in mind?

**Comment by Pupsi-Mupsi** [comment]
@curstwist 

Tested the new `seat_wood_bench` on a wagon.
I haven't done any big JSON-Edits in a while, but isn't `"looks_like": "seat_wood",` supposed to act as a tileset fallback?

grafik

**Comment by curstwist** [comment]
seat looks good, I don't know anything about how tile set fall backs work for vehicles, but Fris0Man does.

**Comment by Fris0uman** [comment]
Actually I don't really know if looks_like works for vehicle parts or not

**Comment by mlangsdorf** [comment]
looks_like works fine for vehicle parts.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> looks_like works fine for vehicle parts.

Thanks Mark. I can't figure out why it's not working for me.

**Comment by emptytriangle** [comment]
I was messing with looks_like earlier and also couldn't get it to work, was trying to make a vehicle cot and looks_like: "tr_cot".  Might be unrelated, idk

**Comment by Pupsi-Mupsi** [comment]
That's it. Could someone please take a look at it before it is merged.

**Comment by Pupsi-Mupsi** [comment]
Ready to be meged.

**Review by Maleclypse — APPROVED** [review]
This is pretty cool

**Comment by Mrzjadacz** [comment]
What prevents you from installing only one rear seat and obtaining better stats?
What prevents you from installing it as a driver's seat?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> What prevents you from installing only one rear seat and obtaining better stats?
> What prevents you from installing it as a driver's seat?

Well, nothing. And I think it's fine. There are no starting vehicles with back-seat in the front but there are Cars with benches in the front in RL.

grafik

**Comment by BrettDong** [comment]
This PR is probably causing CI check failures on latest PRs.

**Comment by Pupsi-Mupsi** [comment]
You're right. This PR was fine when I finished it on December 4th, 2020. Thanks for fixing this one!!!

**Comment by ToxiClay** [comment]
This PR is causing tileset graphical errors in builds downstream of its merge. Is there a reason I shouldn't make a reverting PR?

image

**Comment by ZhilkinSerg** [comment]
A missing tile is not an error - this happens all the time.

**Comment by acepleiades** [comment]
Why doesn't it use looks_like related sprite?

**Comment by Pupsi-Mupsi** [comment]
@acepleiades 
Could not figure out why "looks_like": "seat" is not working properly. I did implement it though.

**Pull request merged**
