### PR TITLE
Removed references to weight torque and recoil from M134D-H

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by Noctifer-de-Mortem** [comment]
I would just suggest mention the need for mountable terrain.

**Comment by Mecares** [comment]
It would be cool if you would not need the mountable terrain if you wear power armor.

**Comment by BorkBorkGoesTheCode** [comment]
@Mecares I lack the skill to implement that at the moment, but I might try to do it later.

**Comment by BorkBorkGoesTheCode** [comment]
This reverts most of my earlier M134 rewrite.

**Pull request merged**
