### PR TITLE
Add an optional translation context for option items

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
```SUMMARY: I18N "Add an optional translation context for option items"```

#### Purpose of change
In the options for auto pulp/butchery and auto forage, one option is "disabled", which is also the name for an effect (as in "physically disabled"), and other languages (such as Chinese) may have different words for these two meanings. This PR adds an optional translation context to the option items so they can be properly translated in such cases. The option items for auto pulp/butchery and auto forage are updated to use the new optional translation context.

As a bonus, I fixed a place where the code is using the untranslated string's size for popup width calculation.

### CODE REVIEW

**Comment by BevapDin** [comment]
Does this actually work? You only added the context to be extracted, but not to the place where it's actually translated.

**Comment by Qrox** [comment]
You're probably right. I guess it's not so easy as it seemed to actually allow different translation in this case then.

**Comment by Qrox** [comment]
I have come up with another approach which should work, see the OP for details. It's not pretty, but it gets the job done, and makes as little changes as possible to the code.

**Comment by Qrox** [comment]
#26402 obsoletes this PR.

**Pull request closed without merging**
