### PR TITLE
Remove belted on mds torso

### PR DESCRIPTION
**Pull request by epebe**
#### Summary
Balance "MDS no longer covers strapped layer on torso"

#### Purpose of change

I wanted to use molle with the MDS, but it kept conflicting with loadbearing vests. Turns out the mds occupies the strapped layer on the torso and conflicts with other harnesses. 
#### Describe the solution

Remove the "belted" from the MDS torso armor data.  Does the same for the MDA, since leaving it unchanged would make it no different from wearing the anchor and MDS together. 

#### Describe alternatives you've considered

Eat the encumbrance penalty

#### Testing

Started game with no errors.

#### Additional context

Per the code comments, "in the real world you can just buy a bag with the pockets and utility you want, or as the current fad in Tacticool Operators ™️  go with a micro rig or a dedicated pre pocketed harness." Don't think it makes sense for the suggested alternative to have conflicts with the armor.

### CODE REVIEW

**Comment by DukePaulAtreid3s** [comment]
> since the anchor is strapped.

I don't think it is: according to the description of the Modular Defense Anchor it's mounted underneath the poncho, not on top.

**Comment by epebe** [comment]
Yeah, I thought so too at first, but "a portion of the front has been raised upwards from the rest". Because the 5 point anchor on its own is strapped, I interpreted this as the fabric is covering a forward protrusion that would interfere with a loadbearing vest.

**Comment by epebe** [comment]
But if this change goes through, the MDA will offer no advantage over wearing both separately which feels kinda disappointing. Yeah, I'll change the MDA too. 

If anyone thinks this is too much of a change, lmk and I will undo it.

**Comment by John-Candlebury** [comment]
The MDS covers the strapped layer because that's where both the poncho and the integrated bags are placed. It also helps preserve game balance by making it less flexible than the military Molle system. Allowing the mds to be compatible with molle makes it by far the best armor in the game. 

At most you could add an extra integrated  holster  but I think this change is too much.

**Comment by epebe** [comment]
I see. Thanks for letting me know.

**Pull request closed without merging**
