### PR TITLE
Update README.md with ascii title

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
#### Summary

```SUMMARY: Infrastructure "Updates README.md with ascii title"```

#### Purpose of change

To update the 'front page' of the repo with a graphic for the new .E release.

- Adds a new title image to the README.md
- moves the status images
- minor grammar fixes/changes

#### Describe the solution

I used the same 'logo' used in-game and on the reddit.

#### Testing

[Light Theme](https://i.imgur.com/Y8ojqRa.png) | [Dark Theme](https://i.imgur.com/eqg3GIP.png)

(new versions in comment down below)

#### Additional context

If you aren't a fan of parts of the change, lmk.

### CODE REVIEW

**Comment by Leland** [comment]
Cyan is super tough to read on a white background

**Comment by ZhilkinSerg** [comment]
<html>
<pre>
   _________            __                   .__                                
   \_   ___ \ _____   _/  |_ _____     ____  |  |   ___.__   ______  _____      
   /    \  \/ \__  \  \   __\\__  \  _/ ___\ |  |  <   |  | /  ___/ /     \     
   \     \____ / __ \_ |  |   / __ \_\  \___ |  |__ \___  | \___ \ |  Y Y  \    
    \______  /(____  / |__|  (____  / \___  >|____/ / ____|/____  >|__|_|  /    
           \/      \/             \/      \/        \/          \/       \/     
    ________                   .__      ________                                
    \______ \  _____   _______ |  | __  \______ \  _____    ___.__   ______     
     |    |  \ \__  \  \_  __ \|  |/ /   |    |  \ \__  \  <   |  | /  ___/     
     |    `   \ / __ \_ |  | \/|    <    |    `   \ / __ \_ \___  | \___ \      
    /_______  /(____  / |__|   |__|_ \  /_______  /(____  / / ____|/____  >     
            \/      \/              \/          \/      \/  \/          \/      
                     _____   .__                         .___                   
                    /  _  \  |  |__    ____  _____     __| _/                   
                   /  /_\  \ |  |  \ _/ __ \ \__  \   / __ |                    
                  /    |    \|   Y  \\  ___/  / __ \_/ /_/ |                    
                  \____|__  /|___|  / \___  >(____  /\____ |                    
                          \/      \/      \/      \/      \/                    
</pre>
</html>

**Comment by cosmiccoincidence** [comment]
I agree cyan may not be easily readable against white. I was simply using the colors in the game... I came up with an alternative that might be more appealing (lime green):

[Light Theme](https://i.imgur.com/CLfCg0a.png) | [Dark Theme](https://i.imgur.com/BAjgFSw.png)

But since @ZhilkinSerg posted the actual ascii (thanks), here is that version:

[Light Theme](https://i.imgur.com/xJFmoKh.png) | [Dark Theme](https://i.imgur.com/kwQdsMR.png)

Which I think looks pretty good (obviously more concerned about the standard light theme), but felt the corners could use something, so I threw together a quick biohazard ascii symbol to put there:

[Light Theme](https://i.imgur.com/fbFLdB3.png) | [Dark Theme](https://i.imgur.com/eqB8TDD.png)

Let me know what you guys like and I'll update the PR with it.

**Comment by AMurkin** [comment]
image
Can the text glow, since this is an image?

**Comment by cosmiccoincidence** [comment]
Ultimately is up to what the devs like... But my first (colored) attempts were images, but the later two are just pure ascii in the text, not even a picture file. I can test your image but you should export it without a background. Just a transparent image with only the text. Could you do that and I'll try to make it work? @AMurkin

**Comment by AMurkin** [comment]
> the later two are just pure ascii

I didn't catch that the final version will not be an image. And this is for the better due to the fact that it's possible to customize the style on the user side.
Nevermind my previous comment.

**Comment by cosmiccoincidence** [comment]
Since I havent received anymore opinions recently, I updated it to the ascii version without the extra symbols, and you can see it running on [my branch](https://github.com/cosmiccoincidence/Cataclysm-DDA/tree/readmeimg).

**Comment by olanti-p** [comment]
I think the blue+green image version looked nice. Text is kinda finicky
image
(Firefox 74.0 on Kubuntu)

**Comment by cosmiccoincidence** [comment]
Personally I'm kinda leaning toward the ascii myself, as it's more true to the nature of the game. And you will also be able to see the ascii if you manually open the readme file, as opposed to seeing link to a img in the docs folder.

**Pull request merged**
