### PR TITLE
Allow artifacts with negative resonance (neg cap at -1k)

### PR DESCRIPTION
**Pull request by tornikeo**
#### Summary
Content "Allow artifacts with negative resonance"

#### Describe the solution

I like the grind of hunting for artifacts. And I LOVE min-maxing items/skills for a character. Since artifacts aren't allowed a negative resonance, after getting 2-3 artifacts, hunting for more feels really useless. Allowing some artifacts to have at most -1000 resonance, makes hunting for more artifacts feel worthwhile for me. 

#### Describe alternatives you've considered

Making negative resonance artifacts somehow special, but for now, it's just a matter of RNG. If you get lucky, you will find one with enough negative traits to have negative resonance.

Future work should include making these artifacts feel even more unique. 

#### Testing

kuva

### CODE REVIEW

**Comment by anoobindisguise** [comment]
As the creator of resonance, hard disagree on this. I deliberately capped minimum resonance at zero because I didn't want you to just carry around a bunch of artifacts with bad active effects in order to get more stat buffs. While you currently can sometimes get "less-resonant" artifacts that have good passives and bad actives those are pretty rare (and thus special).

**Comment by tornikeo** [comment]
@anoobindisguise  I'm thinking about a adding separate rare artifact class that always has negative resonance. Code is all there to make it happen.

Just thinking about where to place those things - it should be incredibly hard/dangerous to get them. :thinking:

**Comment by AnotherSeawhite** [comment]
What about giving a tiny bit of negative resonance on artifacts with bad passives & actives? Being able to bear more artifacts (have less artifact downside) in exchange for your character's overall health and performance *might* work.

**Comment by RenechCDDA** [comment]
I don't see any reasonable way to balance this, you could stack ever-increasing amounts of -resonance artifacts with +resonance artifacts into an endless power spiral. It basically encourages the player to peek behind the curtains and read artifact effects, too, so they can be sure they're min-maxing properly.

**Pull request closed without merging**
