### PR TITLE
Turning book items into snippets

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Content "Turning book items into snippets"

#### Purpose of change
Make more thorough use of snippets and reduce item bloat.

#### Describe the solution
Turns a plethora of books into snippets for their category item.

#### Describe alternatives you've considered
Not doing this.  I have concerns with how snippets work compared to individual items that this is going to make libraries look more empty.  I've decided to do this section of books and hopefully it can be tested by other people and then if it's not working out reverted.

#### Testing
TBD

### CODE REVIEW

**Comment by Qrox** [comment]
This is going to makes these books lose their unique names and chapter numbers. I personally never care about non-skill books, but someone else might argue that these unique names and chapter numbers add flavor to the game.

**Comment by anothersimulacrum** [comment]
I can make variants more generic to resolve the name issue.

**Comment by Zeropol** [comment]
I've tested this and I've met a problem, the same problem paper news already have : items with different snippets will merge in the inventory. ( that's why I don't collect newspaper, an activity who would be nice to role play, to document the end of the societies )

I've made a GIF of this because I'm not fluent in English : 
GIF of the problem mentionned
( before GIF : spawned two swashbuckling novels with different snippets, one on the South tile, one of the South East tile )
GIF :
- Look at the first book, "The code of the Buccaneer". Grab it.
- Look at the second, "The black freighter". Grab it.
- Open inventory, items have merged, "The black freighter" is lost.

**Comment by Qrox** [comment]
Maybe we can still stack items with different snippets, but allow inspecting a stack of items to see the unique snippets within. (Items not counted by charge are stored as different items, but displayed as a stack, so this is doable. Items counted by charge however may merge into a single item, so that needs extra handling).

**Comment by Maleclypse** [comment]
> I can make variants more generic to resolve the name issue.

I'd like this as I think all of classical literature is already snippets.

**Pull request closed without merging**
