### PR TITLE
Buff RM451 Flamethrower item spawn chance

### LINKED ISSUE #20931: RM451 Flamethrower is so rare it might as well not exist
I challenged myself with a character that can only kill enemies with fire and explosions, so I was looking for the RM451 flamethrower and after a (long) while I got frustrated and started savescumming a bunker... still havent found it after 150+ tries (yes I know about the debug menu but I want to do it this way).

I checked the code and I found out it can only appear in two places, so I calculated the chances of finding it:

Around 1 in 250 Military Bunkers (5/408/14x6x0.8)
Around 1 in 25 thousand Survivor zombies (5/408/218)

I know it's a powerful weapon but imho it's wayyy too rare, (who checks 250 bunkers?) It's a lot rarer than all the other powerful stuff.

My suggestion is to simply change the weapon probability in the mil_hw item group from 5 to 25, so it's 1 in 50 bunkers, still rare but not insane.

On a side note I would really really like if there was a recipe to reload 40mm grenades frag or concussive, as it is now you can only reload 40mm flechette and buckshot which completely defeats the purpose of using a grenade launcher.

### PR DESCRIPTION
**Pull request by AMurkin**
Closes #20931

### CODE REVIEW

**Comment by pisskop** [comment]
its more common than the military issue flamer now

**Comment by AMurkin** [comment]
Than issue should be closed, another opened and new changes PRed.

**Comment by Rivet-the-Zombie** [comment]
Or just alter this one? You can change it and then sync the changes to Github without having to open a new PR.

**Comment by kevingranade** [comment]
The most I could see bumping it is 2x instead of 5x, the RM451 is *supposed* to be rare.

**Comment by AMurkin** [comment]
Now i could change this PR. Done.

**Pull request merged**
