### PR TITLE
Build roofs over dirt, and dig stairs in roofed dirt tiles

### PR DESCRIPTION
**Pull request by ashGlaw**
#### Summary

```SUMMARY: Features "Let the player construct a dirt floor with a roof, and made the dirt floor tile diggable so you can dig stairs down indoors "```
#### Purpose of change
I've been frustrated that I can build stairs up in a building, but there was no way to dig down indoors. 

#### Describe the solution
I added a dirt floor construction, letting the player construct the preexisting dirt floor tile. I made the dirt floor tile and the dirt floor with thatched roof tile "DIGGABLE". 

#### Describe alternatives you've considered
I've considered adding a way to dig out a wooden floor, turning it into a dirt floor tile. Not sure how that would interact with preexisting underground structures

#### Testing
I used the construction menu to create both a dirt floor and a dirt floor with thatched roof tile. When that was successful I saved and reloaded, going up to the roof to check that the construction had added the roof properly, and it had. Then I dug a downstair in both tiles. The stairs worked when tested. The roof was still over them.

#### Additional context
This doesn't address the problem of not being able to dig downstairs on wooden floor terrain, but I'm thinking on it

### CODE REVIEW

**Comment by AMurkin** [comment]
You need to [format](http://dev.narc.ro/cataclysm/format.html) changed JSON files.

**Comment by Night-Pryanik** [comment]
Please add diggable flag also to `t_dirtfloor_no_roof` in `terrain-floors-outdoors.json`.

**Comment by ashGlaw** [comment]
I formatted the files I changed and made the feature request for diggable outdoor dirt floors

**Comment by ashGlaw** [comment]
I didn't mean to bother you Erk, I'm still learning and didn't mean to request your attention

**Comment by I-am-Erk** [comment]
It's okay, I'm probably going to be the one doing the final review on this anyway.

You seem to have gotten your fingers into some other files that you didn't mean to on this. I would suggest just keeping that initial dirtfloor recipe, nothing else

**Comment by ashGlaw** [comment]
I'm not sure how those other lines were changed. I did my best to fix that. Now all this is changing is an additional construction recipe, and making three kinds of dirt floor tiles diggable, touching three files. 

Erk, you think I should revert back to only adding diggable to dirt floors and make the new construction recipe a different PR? I'm not sure I understand your suggestion, sorry.

**Comment by ashGlaw** [comment]
All checks have passed, yay! Is there anything else needs done?

**Comment by I-am-Erk** [comment]
Nope, looks good.

All i meant by limiting your changes is that if you really did mean to do edits to the stats of dirtfloor terrain that was best suited to another PR. It doesn't look like you meant to do that at all so no worries

**Pull request merged**
