### PR TITLE
Improve terrain bashing with experimental z-levels

### LINKED ISSUE #23250: RDX charge detonation turns ground into "flat roof" tiles
Game version:
672a53d

Operating system:
macOS 10.13.2

Tiles or curses:
Tiles

Mods active:
* Filthy Clothing
* Disable NPC Needs
* Simplified Nutrition

### Expected behavior
N/A

### Actual behavior
After an RDX charge detonates, a certain amount of tiles turn into "flat roof" tiles

### Steps to reproduce the behavior
Debug spawn an RDX charge, activate and drop it, and run away.

Following the explosion, you should see something like this:

screen shot 2018-03-18 at 10 04 32 pm

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: Bugfixes "Improve terrain bashing with experimental z-levels"

#### Purpose of change

Fixes #24707
Fixes #23250

This change allows for differentiating between terrain bashed from the side and above, introduces a new `t_rock_floor_no_roof` terrain for `t_rock` to transform into when bashed from above (as opposed to `t_rock_floor` which has a roof), and removes the `bash_below` flag from several terrain types that don't meet the requirements for it.

If you're testing, make sure the experimental z-levels are enabled. With them disabled, bashing terrain generally just leaves t_dirt behind at the current z-level (no holes to the next z-level) before and after this change.

#### Describe the solution

First, for differentiating between terrain bashed from the side and above:

Add ter_set_bashed_from_above to bash data, and default it to ter_set.

This allows terrain to define the terrain it should be transformed into when it is bashed from above as opposed to from the side, as sometimes it makes sense for that to be different (e.g. when bashing into t_rock, which normally transforms into t_rock_floor, which has a roof of t_flat_roof--this makes sense when bashing from the side, but from above there shouldn't be a solid roof since you just bashed through it to get to the t_rock you bashed).

Add new t_rock_floor_no_roof which has t_open_air for a roof, and use it as the ter_set_bashed_from_above for t_rock.

The end result is when experimental z-levels are on and you smash the floor of your current z-level through into the rock a z-level below you and destroy that too, instead of a t_flat_roof magically appearing at your z-level despite the terrain below being hollow, you instead get t_open_air so you can climb/fall down into the hole you made.

Secondly, for making bash_below false for some terrain types:

Bash below is poorly documented (just "TODO" in the json documentation) but the comment in the source code says that:

// This terrain is the roof of the tile below it, try to destroy that too

I think this is inappropriately applied to some terrain types, such as t_pavement, because it means that if you have experimental z-levels enabled and you use a pickaxe to destroy a piece of road pavement, instead of breaking up the pavement, exposing the underlying terrain and leaving behind the debris byproducts, you instead dig an entire z-level down below your current z-level and mine out the rock there too.

The pavement is not the roof of the rock below it, and in general where this flag was set to true for something that is actually more of a layer on top of the ground (e.g. pavement, woodchips, sidewalk, wood floor) I've removed it.

#### Describe alternatives you've considered

The only alternative I could think of is a much broader revisiting and potential reworking of how the z-level terrain bashing works, both in terms of data definitions/structures and process.

#### Additional context

**setting off an ANFO charge with experimental z-levels enabled leaves a crater**
image

### CODE REVIEW

**Comment by ralreegorganon** [comment]
Jenkins rebuild

**Comment by ralreegorganon** [comment]
> Roof collapsed?

It did, but this looks to actually be a consequence of the terrain types in the basement and how they interact when destroyed.

Here's a test I just did. The two structures are exactly the same, except that one has a basement of `t_rock_floor` while the other is just `t_rock` underneath.

explosives

I set off an RDX charge in both. The roof is destroyed in both cases and when there is no basement the blast continues downward as expected, furthering the open air. However, the rock floor basement completely stops the blast--the `t_floor` of the building gets "blasted off" revealing the `t_flat_roof` below, which is the defined `roof` of the `t_rock_floor` terrain type.

**Comment by ralreegorganon** [comment]
Ok, I updated this with two things.

1. A new (initially) failing test `explosion_on_floor_with_rock_floor_basement` to capture some of the oddity from the example @ZhilkinSerg provided. It follows the example of the other tests for this problem area, doesn't run by default, and behavior will change depending on ZLEVELS settings. Run with: `tests/cata_test --option_overrides=ZLEVELS:true "explosion_on_floor_with_rock_floor_basement"`

2. An update to fix the failing test and somewhat address the case highlighted in the example by adding COLLAPSES and SUPPORTS_ROOF to `t_rock_floor`. This brings the terrain type in line with the other floors with a roof overhead. The lack of this was causing issues with "indestructible basement roofs" where an explosion at the level above would strip the "dirt" off the roof of the basement, exposing a t_flat_roof, but would never actually destroy the roof of the basement.

Now, while this improves things even more, it's still not 100%. As I noted in the original PR, my goal was to *Improve terrain bashing with experimental z-levels* and fix those two initial bugs, but I don't think it can be comprehensively fixed without doing the alternative I considered and dismissed: *The only alternative I could think of is a much broader revisiting and potential reworking of how the z-level terrain bashing works, both in terms of data definitions/structures and process.* and honestly I'd expand that to *The only alternative I can think of is revisiting and reworking the entirety of how floors and roofs are defined, placed, and interacted with, both with and without experimental z-levels enabled.*

If you play around with this, you'll see all sorts of oddities. For example:
* concrete floors in labs don't cause the same problem because they actually have no roof defined, so if you look at the surface entry for a lab, you'll see it's wide open to the air above.
* walls on the subsurface level will cause the surface level ground to not be completely destroyed despite the wall itself being destroyed, because in general the walls do not have the "COLLAPSES" attribute, but DO have a roof defined
* terrain features inconsistently have roofs defined, which causes oddities when collapsing those structures. A `t_window` has no roof defined, a `t_door_c` has a roof defined, but both may be placed in a `t_wall` which does, so the view from above is patchwork open air and roof. A `t_concrete_wall` has a roof defined, a `t_sconc_wall` does not. 
* a given terrain's roof is defined as part of the terrain, so in order to have a version with a different roof (e.g. open to the air) you have to define an entirely different terrain, and then determine how to transform between them
* and even more, everywhere you look

I was interested in tackling the two linked issues in the interest of closing 0.D blockers, but I'm not interested in taking on reworking the entirety of floors/roofs and their z-level interactions right now. If we think this PR is a worthwhile incremental improvement, cool. If we'd rather tackle all the these issues holistically, just let me know and I'll close this PR.

**Comment by kevingranade** [comment]
Patching away the most egregious failures is fine for this revision, I agree it needs an overhaul, but I don't want one *right now*.

**Pull request merged**
