### PR TITLE
Update materials for survivor suits

### PR DESCRIPTION
**Pull request by PlutusPleion**
#### Summary
Balance "Updated survivor suits to utilize the material thickness system and renamed to jumpsuits"

#### Purpose of change

Survivor suits armor_data is outdated and not yet in line with newer armor. An attempt to balance heavy survivor suit.

#### Describe the solution

I think it's good to keep survivor gear at 100% coverage because it fits a niche but also nerf the material coverage.

What's the difference? With 100% coverage, we always ensure we get some defense while wearing survivor suit even if we fail at steel material roll. With 95% coverage on kevlar chainmail, you get full resistance 95% of the time and no resistance 5% of the time.

There are 2 separate tempered steel layers(stronger than the generic) with 0.6 thickness at 90% because it allows for more nuanced variation rather than copying a flat 95% that most other gear have. In terms of realism it can mean nearer to joints there's 0.6 thick steel layer and at more important/central locations the 2 steel layers overlap.

Pockets were removed to be more in line with jumpsuits and the increased encumbrance from carried volume was removed.

Survivor suits were renamed to be more descriptive(light kevlar jumpsuit, kevlar jumpsuit, steel-plated kevlar jumpsuit). Light kevlar jumpsuit is slightly weaker, kevlar jumpsuit is stronger, and steel-plated kevlar jumpsuit is weaker compared to originals.
 
Steel-plated kevlar jumpsuit is still very strong but is now updated for the material layering and still holds a niche.

#### Testing

- No errors
- Changes reflect in game 

#### Additional context

Is there a precedent for using multiple layers of same material? yes. [example](https://nornagon.github.io/cdda-guide/#/item/armor_lc_plate)

No, I don't dislike heavy survivor gear. I'm using it [on my current character](https://i.imgur.com/5H5TTog.png).

[updated fire,winter and wet variants as well](https://github.com/PlutusPleion/Cataclysm-DDA/pull/7).

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
So as a preface the current plan is to get rid of the heavy survivor suit entirely. However this redesign actually makes me at least feel like it could stay in.

A few suggestions
The Chain Armor is OUTER not NORMAL

The other survivor suits also had their pockets removed and moved to a strapped armor storage https://nornagon.github.io/cdda-guide/#/item/survivor_rig. I didn't bother doing it for this armor since it was planned for removal. So moving down the encumbrance on this guy to match doesn't make sense unless you cut the pockets.

So I would suggest giving this armor no encumbrance scaling with volume [16, 16], reducing the pockets to match the other survivor armors, and making it OUTER layer.

I think with that it would be a strong, light outer armor.

**Comment by Testudo-Cultu** [comment]
> So as a preface the current plan is to get rid of the heavy survivor suit entirely. 

The main purpose for the heavy survivor suit (or any of them) is just to act as a crutch for the coverage system being inadequate. I'm glad that we're getting a new system, because it's sad to always have survivor gear be your ultimate solution to armor (not including power armors).

**Comment by PlutusPleion** [comment]
> So as a preface the current plan is to get rid of the heavy survivor suit entirely

Oh ouch. It would be really nice if we could keep them in the game in some form.

The specific gear I was comparing it to was the kevlar chainmail armor which has an active that switches it between normal and outer layer.

I've taken most of the pockets out and made it more in line similar to "winter survivor suit". I still like the idea of it being in the normal layer because it still goes with the "light, standard, and heavy" variants we have.

**Comment by bombasticSlacks** [comment]
> The specific gear I was comparing it to was the kevlar chainmail armor which has an active that switches it between normal and outer layer.

The underlying gambeson it is made from has that function but it, in my copy of experimental and on HHG does not have a transform to and from outer/normal.

Pocket changes look good.

People are looking at removing most the survivor suits in favor of more interesting and nuanced armors. So there will still be survivor clothing it just wont be 6 different best in slot jumpsuits.

I do want to keep a Kevlar Lined "Survivor Suit" on the normal layer which will be that iconic armor you want to keep around (it's a favorite of mine as well) but on normal layer you can't just keep making things thicker. If something is thicker than a Jacket it should really go on the OUTER layer. 

I think this would be solid as outer armor as you have designed it that would work as a flexible, jack of all trades suit. 

I know your trying to come from a "min-max-y" but still balanced position on a lot of these balance changes. Trying to find things powerful niches and I can appreciate that, it should feel good to use lots of different stuff. Fundamentally in this case the game is moving towards where you get most of your protection from the OUTER not NORMAL layer. Here's the relevant issue #52514

For example under the assumption outliers like the Heavy Survivor are going away, some really powerful platemail has been added recently as well as the Hub 01 Modular Armor.

**Comment by PlutusPleion** [comment]
> The underlying gambeson it is made from has that function but it, in my copy of experimental and on HHG does not have a transform to and from outer/normal.

Oh my mistake, I must have confused the two in my head.

The thickness argument makes sense as well. I tried changing the leather layer to 0.5 and kevlar to 1.5:



Changing it to this would only be giving slightly better stats than the normal survivor suit.  For now I think the current one is a good compromise/stopgap and could be a nice test to see how everyone likes it. 

Although it seems like some time away since it's a full rework of all gear, I look forward to the future system that's envisioned in the discussion you linked.

**Comment by bombasticSlacks** [comment]
I know it makes them worse but I *think* if all the jumpsuits had their leather / cotton moved to .2mm which is the thickness of the jumpsuit that this would be a good solution and wouldn't get push back. That way also its thematic in that you are reinforcing a real jumpsuit (or the equivalent) with this padding. This also doesn't effect the armors too much while still getting this in a sensible thickness range to be worn under other clothing.

**Review by bombasticSlacks — APPROVED** [review]

**Comment by bombasticSlacks** [comment]
add 
```  
  {
    "type": "recipe",
    "result": "hsurvivor_suit",
    "obsolete": true
  }
```
to the bottom of recipe_obsolete.json so that error goes away

**Comment by bombasticSlacks** [comment]
> updated recipes as well to be more consistent with the changes: https://github.com/PlutusPleion/Cataclysm-DDA/pull/5/files . Let me know if it's good for merge to this PR.

I originally removed the option to use ballistic vests and kevlar vests for the survivor suit crafts since you would need to cut up the panels and put them on the arms and legs as well. I think they only really make sense if the armor is exclusively on the chest which it isn't. 

Otherwise it looks good to me at least

**Comment by PlutusPleion** [comment]
> I like these changes, a reinforced jumpsuit is a better fit. Since these are supposed to be high-end and require other advanced supplies/tools, it might make sense to use **tempered steel** by default since that can be **made much more easily than full plate**. I realize this goes against our previous discussion but I don't want to have multiple levels of the highest tier suits like these.

Updated to tempered steel, reduced total thickness from 2->1.2 to compensate. Added relevant proficiencies and tools to craft. Ended up with 8 weeks 5 days with zero proficiencies, up from 4 weeks 5 days of original. One week if you have all proficiencies except blacksmithing, armorsmithing and quenching.

> I originally removed the option to use ballistic vests and kevlar vests for the survivor suit crafts since you would need to cut up the panels and put them on the arms and legs as well. I think they only really make sense if the armor is exclusively on the chest which it isn't.

Makes sense, the player can always just cut up the armor into kevlar panels anyways. Removed them again in the recipe.

Where it's at right now:

**Review by anothersimulacrum — COMMENTED** [review]
You need to lint your JSON. Copy the entire file you want to lint, paste it into [this website](https://dev.narc.ro/cataclysm/format.html), format it, and paste it back.

Can we give these items more descriptive names?
e.g. Light Kevlar Jumpsuit (light survivor, cotton + kevlar), Heavy Kevlar Jumpsuit (medium survivor, leather + kevlar), Steel-plated Kevlar Jumpsuit (heavy survivor, leather + steel + kevlar). Not that these particular names are good, but I hope they get the idea across, and I think moving away from 'survivor X' is useful is making these items better.

> Retains niche of having high coverage. Survivors know the value of coverage so thematically it makes sense.

I think everyone knows the value of this, it's just not something that can happen in every application due to other concerns (such as fit, but those are custom-made).

**Comment by PlutusPleion** [comment]
> You need to lint your JSON. Copy the entire file you want to lint, paste it into [this website](https://dev.narc.ro/cataclysm/format.html), format it, and paste it back.
> 
> Can we give these items more descriptive names? e.g. Light Kevlar Jumpsuit (light survivor, cotton + kevlar), Heavy Kevlar Jumpsuit (medium survivor, leather + kevlar), Steel-plated Kevlar Jumpsuit (heavy survivor, leather + steel + kevlar). Not that these particular names are good, but I hope they get the idea across, and I think moving away from 'survivor X' is useful is making these items better.
> 
> > Retains niche of having high coverage. Survivors know the value of coverage so thematically it makes sense.
> 
> I think everyone knows the value of this, it's just not something that can happen in every application due to other concerns (such as fit, but those are custom-made).

Ran all 5 through linter and updated names and descriptions.

**Comment by PlutusPleion** [comment]
All "survivor suits" updated:


Only suits are updated, boots, gloves, hoods, backpacks, and weapons are untouched.

**Comment by Drew4484** [comment]
This looks good to go, are you ready to have it merged?

**Comment by PlutusPleion** [comment]
Yeah all good as long as no one else has further concerns on it.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/survivor-suit-recipes-dont-show-up-for-me/27797/3

**Pull request merged**
