### PR TITLE
Tongs rationalized

### PR DESCRIPTION
**Pull request by TealcOneill**
#### Summary
None

#### Purpose of change
I saw #55017 the other day and it prompted me to take a look at the flatjaw tongs recipe and I noticed it didn't really make much sense at the time.

#### Describe the solution
I gave the tongs realistic proportions based on some common flatjaw tongs online. I changed the recipe to get rid of the random chunk of steel and added metal sawing to cut off the ends of the rebar/pipe. I also added byproducts roughly equal to the amount of rebar/pipe left after 

#### Testing
Loaded up the game and made sure everything made sense.

### CODE REVIEW

**Comment by OanMkvenner** [comment]
Even though i like the byproduct idea and understand the Metal Sawing change, this change makes the Henn-Egg problem even worse, since you need Flatjaw Tongs to create a Hacksaw and a Hacksaw to make Flatjaw Tongs.

**Comment by TealcOneill** [comment]
> Even though i like the byproduct idea and understand the Metal Sawing change, this change makes the Henn-Egg problem even worse, since you need Flatjaw Tongs to create a Hacksaw and a Hacksaw to make Flatjaw Tongs.

Like I mentioned in #55017 I don't see this as a problem, this game relies on you scavenging. You can find a hacksaw in 15% of garages and tons of other places. It's neat to be able to make a hacksaw but it's a lot easier for a survivor to find these than to remake all tools humanity has ever made from scratch. We should introduce more tools that can be found or made that would allow you to hold metal while blacksmithing and give it it's own quality.

**Comment by TealcOneill** [comment]
> The only change I see here I agree with is the length. The weight change is just a tweak, the volume seems to be placed on displacement instead of bounding size (46cm x 3cm x 3cm = 414 ml, not 100) The steel lump should be in there because what it's asking for is simply "enough metal to forge", not an "almost right shaped metal rod". If you have a forge, you can cut off the ends, so the metal saw is complicating things for no reason.

The weight is just a tweak but I actually put the wrong thing there, it's supposed to be 847 grams which is the average between 36" of pipe and rebar that would be reasonable to use for this. I personally like having the weight and volume be fairly specific because it makes these hand crafted items feel more real. I totally forgot we were supposed to be calculating volume based on bounding size and it should actually be 593 based on what sketched out. I honestly don't understand what you mean with the steel lump, I went based on this video(https://www.youtube.com/watch?v=ts7NsnltiNk) which shows some tongs being made from rebar and I don't see how a 2lb lump of steel could add anything to the recipe. You could cut it cleanly with a hotcut, but that requires the tongs to make and is a lot harder to scavenge than a hacksaw or the like. I don't think you could cleanly cut the end off with just a hammer and level 1 anvil.

**Comment by kevingranade** [comment]
It doesn't need to be a clean cut, it just needs to be cut

**Comment by TealcOneill** [comment]
> It doesn't need to be a clean cut, it just needs to be cut

Okay, and all the other things I said?

**Pull request closed without merging**
