### PR TITLE
Fletching tweaks

### PR DESCRIPTION
**Pull request by Night-Pryanik**
1. Removed separate fletching recipe as we already using some materials for fletching when crafting arrows;
2. Moved components from the fletching recipe directly to the recipes of arrows;
3. Added credit card as a possible fletching component to add some usefulness to cards.

### CODE REVIEW

**Comment by Zireael07** [comment]
Cool!

**Comment by Coolthulhu** [comment]
Merged, even though it noticeably alters arrow balance, because currently archery is rather tedious to get going.

As a result of the changes:
* Arrows can be crafted in bulk by just smashing furniture and cutting sheets. This was not possible before because the glue component necessary to turn rags into fletchings was expensive
* Many alternative components are now obsolete. Most importantly the expensive duct tape

Other weirdnesses to address:
* Aluminum foil spawns in stacks of 200 or so, but arrows only use one charge per stack
* The non-small water bottle component is redundant, bottles can be easily cut up into that plastic
* More Survival Tools mod still has one recipe that uses fletchings
* Fletchings should be moved to obsolete.json now that they are obsolete

**Comment by Night-Pryanik** [comment]
I hardly imagine how non-rigid rags or leather patches can become efficient fletching. I'd rather remove remove them as all.

>Many alternative components are now obsolete. Most importantly the expensive duct tape

Didn't understand that.

**Comment by Coolthulhu** [comment]
Using duct tape when you can use rags is a waste. Components that are way more expensive than their alternatives should be removed.

For example, using an entire UPS for an UPS mod is only a risk of misclick.

**Comment by Night-Pryanik** [comment]
Ok, I got it. And what about removing rags and leather patches?

**Comment by Coolthulhu** [comment]
Well, you just added them in as an alternative option. The glue part was probably to stiffen them, not just glue together.

But yes, removing them would be fine. I don't think anyone crafted fletchings using glue, as glue is just too expensive. Same for arrows themselves - the thread recipe is much more efficient, glue could be removed from there as well. Or glue charges could be multiplied by 10.

**Pull request merged**
