### PR TITLE
add a golem summoning spell to Magiclysm

### PR DESCRIPTION
**Pull request by joffreemaverick**
#### Summary
this is my version of a summoning golem spell. you are requesting help on json spells ad i'm just trying to help (will re-upload file after work failed to upload.

#### Purpose of change
Working on some of the json spells requested 

#### Describe the solution
Ive created the spell

#### Describe alternatives you've considered
Someone else can create this spell?

#### Testing
Ive used it in game. Uses steel and mana summons an iron golem

#### Additional context
This is a spell

### CODE REVIEW

**Comment by dissociativity** [comment]
uhh, you may want to base your spell addition against the master branch, not 0.E, that's extremely old and conflicting with experimental.

**Review by mlangsdorf — CHANGES_REQUESTED** [review]
Please base your changes on the latest experimental version, not 0.E.

Please fill out the PR header information fully and completely - there are instructions on what you're supposed to fill out, you *must* read and follow them for your PR to be considered for merging.

You don't seem to have actually committed your changes for the golem spell, so I can't even review that part of your submission.

**Comment by joffreemaverick** [comment]
There isn't a summon golem spell so I was just trying to share the text document I had for the new spell i created. I haven't used this program before. But your saying the file didn't even attach?

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 7:11 AM, Mark Langsdorf<notifications@github.com> wrote:   


@mlangsdorf requested changes on this pull request.

Please base your changes on the latest experimental version, not 0.E.

Please fill out the PR header information fully and completely - there are instructions on what you're supposed to fill out, you must read and follow them for your PR to be considered for merging.

You don't seem to have actually committed your changes for the golem spell, so I can't even review that part of your submission.

**Comment by joffreemaverick** [comment]
Ok thank you its just a text file with the json for a new spell. Wasnt sure how to get this to work appreciate the response 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 2:47 AM, dissociativity<notifications@github.com> wrote:   


uhh, you may want to base your spell addition against the master branch, not 0.E, that's extremely old and conflicting with experimental.

**Comment by Zireael07** [comment]
You can't send attachments via the e-mail function, just FYI

**Comment by joffreemaverick** [comment]
I didnt try i was on a computer, it must no have added correctly last night when I dragged the file over.

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 8:55 AM, Zireael07<notifications@github.com> wrote:   


You can't send attachments via the e-mail function, just FYI

**Comment by esotericist** [comment]
Please actually read the new contributor document you have already been linked (but in case you forgot how to find it, it's [right here](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors)); pull requests require you to have a git repository of your own on github, commit the changes to that repository, then submit a pull request from that repository to ours for the changes in question.

You cannot simply attach a file and expect it to be accepted as a submission (although you appear to have repeatedly failed to even do that).

Once you have read and understood the new contributor document, you can try again.

**Comment by joffreemaverick** [comment]
First and lastly of fucking all I already wrote afte ri get done from work I will fix it. Please read what I wrote ymbefore you and everyone sends me the same fucjing message all day. Cool thanks. Eat shit

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 5:51 PM, eso<notifications@github.com> wrote:   


Closed #45037.

**Comment by mlangsdorf** [comment]
People are trying to help you make a successful contribution, there's no need for the abusive language.

**Comment by joffreemaverick** [comment]
Oh wow I'm so upset virgin neck beard fuck face ill just redo it later how about get out of your moms basement and learn some fucking social skills before messaging people you sorry shit

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 6:36 PM, Mark Langsdorf<notifications@github.com> wrote:   


People are trying to help you make a successful contribution, there's no need for the abusive language.

**Comment by ZhilkinSerg** [comment]
@joffreemaverick Closed pull requests can be easily reopened, so you could've just edit it whenever you are ready and ask to reopen it.

**Comment by joffreemaverick** [comment]
I am not at home period cant do anything till I get home. 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 6:43 PM, ZhilkinSerg<notifications@github.com> wrote:   


@joffreemaverick Closed pull requests can be easily reopened, so you could've just edit it whenever you are ready and ask to reopen it.

**Comment by ZhilkinSerg** [comment]
Well, you managed to insult people, so you could've just wait instead until you get home and engage in conversation politely.

**Comment by joffreemaverick** [comment]
I put on the website will change when I get home and had about 50 pretentious assholes message me all day about this and that all freaking day. 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 6:51 PM, ZhilkinSerg<notifications@github.com> wrote:   


Well, you managed to insult people, so you could've just wait instead until you get home and engage in conversation politely.

**Comment by ZhilkinSerg** [comment]
What you are saying is a lie and you know that. I kindly ask you not to do this anymore - it really does not help you and you are basically sinking yourself further with each message.

**Comment by joffreemaverick** [comment]
Look whatever man ive been sitting here for thr last hour trying to do all this work to get this github the way you people want it. Im making a repository for these text files. And ill add them there. 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 7:28 PM, ZhilkinSerg<notifications@github.com> wrote:   


What you are saying is a lie and you know that. I kindly ask you not to do this anymore - it really does not help you and you are basically sinking yourself further with each message.

**Comment by joffreemaverick** [comment]
Indont understand how ti link my repository to the pull request.

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 7:38 PM, mad mav<joffreemaverick@yahoo.com> wrote:   Look whatever man ive been sitting here for thr last hour trying to do all this work to get this github the way you people want it. Im making a repository for these text files. And ill add them there. 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 24, 2020 at 7:28 PM, ZhilkinSerg<notifications@github.com> wrote:   


What you are saying is a lie and you know that. I kindly ask you not to do this anymore - it really does not help you and you are basically sinking yourself further with each message.

**Comment by mlangsdorf** [comment]
The easiest way is probably to do the following:
1. commit your changes to your local repository
2. push the changes from your local repository to your upstream repository
3. wait a few minutes
4. go to <https://github.com/CleverRaven/Cataclysm-DDA/pulls> and use the new green button to open a new pull request

**Pull request closed without merging**
