### PR TITLE
Ocean versions of lake specials

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Content "Existing lake specials now spawn in the ocean"

#### Purpose of change

Oceans are empty of locations

#### Describe the solution

- Lake specials now also spawn in ocean
- Doesn't remove any specials designed for the ocean from lakes (ie Aircraft Carrier) as getting to the ocean is tedious rn
- In the future some of these will want either more customised variants to better match the coastal feel or removing entirely once more ocean specials have been made and there's less need to fill the gap
- Includes some minor changes/fixes/organisation to lake specials

#### Describe alternatives you've considered

- Making an ocean vehicle group to replace the lake one where appropriate using conditional predecessor nests but I think I'd rather that be a separate PR with new vehicles to complement some of the existing ones
- Ideally there'd be some way to make sure a few of these like the lighthouse spawn within a range of natural ocean_shore

#### Additional context

Thanks to ralreegorganon for fixing predecessor stuff with lakes so I can test properly

This does mean alot of things with lake in their JSON name now also relate to ocean, not sure where our "no renaming bc wastes reviewers time" stance is on this. Also the "water" special_location is very misleading bc it's only river not lakes nor ocean. Also "river_cave" doesn't even spawn in river.

**[WIP Ignore for now] List of lake specials and their new status:**

Boat Rental/Boat Rental 1/Boat Rental 2
- Still spawns on lake
- Ocean and lake merged specials under the same ids

Lakeside Cabin/Lakeside Cabin 1/Lakeside Cabin 3/Lakeside Cabin 4/Lakeside Cabin 5
- Still spawns on lake
- Ocean and lake merged specials under the same ids

Alcatraz Prison/Island prison
- Still spawns on lake
- Ocean and lake merged specials under the same ids

lake_shore_dock_small
- Still spawns on lake
- Ocean and lake merged specials under the same ids

Island/Island Forest/Sandy Island/Island_1/Island_2/Island_3/Island_4/Island_5_swamp/Island_5_forest/Island_5_forest_thick/Island_5_field
- Still spawns on lake
- Ocean and lake merged specials under the same ids

Lighthouse Island
- Still spawns on lake
- Ocean and lake merged special under the same id

Lake Island Cabin
- Still spawns on lake
- Ocean and lake merged special under the same id

marina
- Still spawns on lake
- Ocean and lake merged special under the same id

Freshwater Research Station
- Still spawns on lake
- Ocean and lake merged special under the same id

aircraft_carrier
- Still spawns on lake
- New ocean special under the old id, with a new id aircraft_carrier_lake for the old one due to aircraft_carrier being GLOBALLY_UNIQUE so this allows one to spawn in a lake and one in the ocean in the same playthrough
- 'chievo for reaching it is gained by visiting either

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I suggest we do at least make the aircraft carrier ocean-only. Finding one is a gigantic windfall, and since it's a possible starting location it's not too hard to get to if you really want. We could even make it not globally unique.

Other ocean-specific starts would be great for players who want to guarantee they have access to ocean content in their runs. If limiting the carrier to oceans has to wait for that, then so be it.

**Comment by Procyonae** [comment]
Erk said just to make copies for now rather than remove lake ones, for the carrier I'm going to have 2 globally unique ones (1 for lake 1 for ocean) I think so one is at least guaranteed to spawn in the ocean. Changing relevant stuff to be ocean only in the long run should be reasonably trivial.

Being able to manipulate your spawn coords for scenarios would obv be great but I don't think that alone should remove elements from elsewhere.

**Comment by BlizzDA** [comment]
While you say it isn't removing any specials, I'd suggest removing the lake lighthouse. It makes no sense for it to exist in a lake. And it'd give people a ocean/shore-based spawn if they use the Safe Place start, for example.

**Comment by Procyonae** [comment]
> While you say it isn't removing any specials, I'd suggest removing the lake lighthouse. It makes no sense for it to exist in a lake.

I'm not removing things from lakes at present bc the average player isn't going to be going to the ocean atm so it would essentially be removing content for them until we have better long distance travel.

>And it'd give people a ocean/shore-based spawn if they use the Safe Place start, for example. Or is it better to be a dice roll at present?

If you set an ocean only thing as a scenario start location it will just fail, scenarios don't search that far, we need infra so you can change the initial search coords for that to work

**Comment by Zireael07** [comment]
> If you set an ocean only thing as a scenario start location it will just fail, scenarios don't search that far, we need infra so you can change the initial search coords for that to work

Definitely a thing that would be welcome in a follow-up PR so that lighthouses can be moved to oceans

**Comment by I-am-Erk** [comment]
Yes, if we get it set up so that people can choose to start near the ocean then I'd be ok with moving a few things over there completely. As it stands right now that's close to deleting the content.

**Comment by Procyonae** [comment]
Waiting on me or someone else to implement #70471 or something similar

**Comment by Procyonae** [comment]
Waiting on going back to this until I finish #72866, this isn't abandoned

**Pull request closed without merging**
