### PR TITLE
Support plants in json mapgen

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Features "Allow for plants in json mapgen definitions"

#### Purpose of change
I was led to this work by the `debug.log` error that sometimes reports "a seed item has vanished".  After some investigation, this turns out to have the following cause:
* Various furniture represents plants.  These have the `PLANT` flag (such as `f_plant_seedling`).
* The furniture does not determine the species of plant.  For that, there is a hidden seed item on the tile from the appropriate species.
* It mapgen (or the player) tries to spawn or drop an item on a `PLANT` furniture, it is displaced to an adjacent tile, because only the special seed item is supposed to be there.
* Mapgen was able to create `PLANT` furniture without the seed item, and when such map tiles were actualized, the error message was generated and the furniture removed.
* Several mapgen definitions were doing this, to no useful effect.

#### Describe the solution
A few changes:
* Add a new special to mapgen definitions called `sealed_item`, intended to be used for this purpose.  It specifies an item and a furniture, and creates the item **before** the furniture, to avoid the issue with the item being displaced.
* Update all existing mapgen using `PLANT` furniture to use this new feature.
* Add various sanity checks on mapgen to prevent anyone using `PLANT` furniture in any other way.

#### Describe alternatives you've considered
I considered simply forcing item placement to happen before furniture placement, but that seems like it could creak other things, and is fragile.

I considered adding a flag to allow mapgen item placement to circumvent the `NOITEM` flag which causes the item displacement, but it would mean adding that flag in many places and it would only be used in one place.

Ultimately, I like the solution chosen best because it allows us to generate useful error messages to explain to map designers how this feature is intended to be used.

#### Additional context
None of the existing mapgen was adding seeds to its `PLANT` furniture, so I had to choose what seeds to use.  I think I made reasonable choices, but of course I don't know what the original intent of the designers was.

As part of this change I added the infrastructure needed to perform any other verification-stage checks on mapgen definitions, should anyone wish to do so.

### CODE REVIEW

**Comment by paulenka-aleh** [comment]
I feel like farms might finally get their plants growing soon :+1:

**Comment by Night-Pryanik** [comment]
Will this feature be safe to use for some fake items that should lay in furniture but shouldn't be visible?

**Comment by jbytheway** [comment]
> Will this feature be safe to use for some fake items that should lay in furniture but shouldn't be visible?

You'll have to look at each furniture item and think about the consequences.  There are a few flags that are relevant:
* `NOITEM` prevents you from putting an item there.
* `SEALED` prevents you from removing the item.
* `CONTAINER` prevents you from seeing what item is there.

Plants have all these flags.

This patch is really about circumventing the `NOITEM` flag during mapgen.  It will let you do that for any furniture, but if the furniture is also `SEALED` then you can't get the item out, so it might not be relevant.  It's only useful for plants because they have special handling for the hidden items within them.  Of course, you could add similar mechanics for other furniture (or perhaps it already exists).

**Comment by Night-Pryanik** [comment]
Thanks. I suspected this already, just wanted the confirmation.

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Pull request closed without merging**
