### PR TITLE
chickenfeed: make chickens and other small domestic birds tameable

### LINKED ISSUE #24216: Bird feed
Now that we have the means to raise chickens (and other birds) we could get an item (like we have cattle fodder) to make chickens (also ducks and cockatrice?) friendly, so my NPC friends stop bashing them into oblivion because chickens dared to cross their path, I'm not saying that they should follow the player (even though speaking from experience, raising chickens from chicks all the way to adulthood makes them very friendly, walking close to you and even letting you get close and pick them up) but at least make it so companions won't treat them as enemies.

Also, if this is implemented, we should be able to put them in pet carriers for safe transport (that way if the player wants to move some place else they don't have to start their chicken coop from zero)

### PR DESCRIPTION
**Pull request by mlangsdorf**
Extends the pet food system to cover chickens, turkeys, and crows.
Adds craftable chickenfeed, made from seeds, grains, or bread.

Slightly refactors the petfood call, because the various specific
food cases were getting out of hand and were basically identical
code.

Fixes #24216

### CODE REVIEW

**Comment by nexusmrsep** [comment]
[Reference](https://en.wikipedia.org/wiki/Poultry_feed)

**Comment by DemAvalon** [comment]
don't forget ducks!

Though chickens would easily eat wild veggies, the suggested ingredients don't seem like they would be trouble to acquire.

**Comment by mlangsdorf** [comment]
Can you tame wild ducks? I felt crows were a bit of stretch but were stylish so I went with it.

**Comment by DemAvalon** [comment]
Ducks can hatch from eggs, you can raise them when they are still ducklings, they would be tamable.

Also, crows are very intelligent and they are kept as pets by some, so I don't think it's a stretch at all.

**Comment by mlangsdorf** [comment]
ducklings are a separate entry; I can extend the flags to cover them.

**Comment by DemAvalon** [comment]
Would the adult remember if it is tamed?, from my understanding of how aging works, they just get replaced with the correct monster

as in, the game checks time that has passed, then takes all plague nynphs that should grow up, removes them then adds the plague vectors to the area.

**Comment by DracoGriffin** [comment]
>Would the adult remember if it is tamed?, from my understanding of how aging works, they just get replaced with the correct monster

I believe the updated monster inherits the same flags but I could be wrong.

**Comment by mlangsdorf** [comment]
I don't think monsters keep the friendly field when they upgrade, but it looks like a straightforward code change to monster.cpp. I'll add it on Monday with the duck upgrades and the build fixes.

**Comment by kevingranade** [comment]
This was already a stretch for cats and dogs, but it seems pretty far out
there for birds.

Smarter birds can certainly learn, "hey this person drops food, I should
stick around", but even that is a stretch for e.g. a chicken.

If there are sources that say otherwise I'm happy to change my mind, I dont
see any balance issues.

**Comment by DemAvalon** [comment]
We are talking about birds you raise yourself, from egg all the way to adulthood (but even adult birds can become friendly), as I said I know this from experience, I raised chickens and ducks before, and at the school I went to (I guess you would call it elementary grade... I think) had a few tame paturi* (in an enclosed space with other birds... and a tortoise) and while they would peck our shoes, they were not really afraid of us and were very friendly towards their owner.

*This bird:https://en.wikipedia.org/wiki/White-cheeked_pintail

also look at these very tame chickens:https://www.youtube.com/watch?v=UCZzKNVWiE8

also talking about training chikens:https://www.youtube.com/watch?v=Nvn4MZ1fKn4

quick google-fu:http://www.yourchickens.co.uk/care-and-advice/are-yours-tame-1-4096292

More google fu:https://www.omlet.co.uk/guide/chickens/chicken_care/how_to_tame_your_chickens

I seriously think taming a stray cat might be harder than a chicken, but it all depends on how they were treated, a dog who was treated badly will avoid humans, and it takes a lot of work to get them to trust humans again, but if they were treated well and you teach them that they can trust humans, then they will trust humans, its the same with chickens, don't chase them around, corner them, or just don't be an asshole to them and they will trust you.

**Comment by DracoGriffin** [comment]
>If there are sources that say otherwise I'm happy to change my mind, I dont see any balance issues.

[Here](https://www.dummies.com/home-garden/hobby-farming/raising-chickens/how-to-train-your-chickens/)... maybe.

[Something](https://www.backyardchickens.com/reviews/category/chicken-breeds.2/) on [chicken breeds](https://tscpl.org/wp-content/uploads/2014/03/Top-10-Birds-for-Backyard-Chickens-PDF.pdf).

**Comment by nexusmrsep** [comment]
> Smarter birds can certainly learn, "hey this person drops food, I should
stick around", but even that is a stretch for e.g. a chicken.

It's not a stretch. The wilder the bird the harder it would be to make it "stay", but chickens were breeded for so long that, just like dog to a wolf, _Gallus gallus_ is now more then a distant cousin, and lot of wildness is gone from them. Chickens are stupid, and you won't be a friend to a chicken like to a dog, but fed by the owners they get pretty used to them, and return to their home barn even if let astray during the day. Same with ducks. If, however, they are not tamed enough at the moment you might want to make a fence, and cut down (shorten) the feathers on their wings. It won't hurt the bird, and it won't fly away (chickens don't fly well anyway from years of cross-breeding and natural predispositions). Feathers will be eventually replaced in time, but that time might be enough for the birds to get used to. Personal experience from my grandfathers farm. I'm not proposing the feather thing, but just saying that you can tame the birds by feeding them regularly to a level where you can keep the flock together, and I believe that thats the scope of the game.

**Comment by mlangsdorf** [comment]
I went with the assumption that chickens were already domesticated, and will respond positively to being fed. Adult ducks, pheasants, grouse, and crows are wild and can't be domesticated with food, but baby versions can be fed at which point they imprint on you and become friendly.

I tested that a chick that was friendly stays friendly when it becomes an adult, so you can raise domesticated birds from birth.

Some future PR will need to add infrastructure for feeding animals, and having unfed animals become neutral but this is good enough for now.

**Comment by mlangsdorf** [comment]
Even though I'm logged into Travis and can restart builds for my day job, I don't have permission to restart the failed Travis builds for this PR.

**Comment by Night-Pryanik** [comment]
Travis restarting are limited to members of CleverRaven only. I restarted it for you.

**Comment by ZhilkinSerg** [comment]
> This was already a stretch for cats and dogs, but it seems pretty far out there for birds. Smarter birds can certainly learn, "hey this person drops food, I should stick around", but even that is a stretch for e.g. a chicken. If there are sources that say otherwise I'm happy to change my mind, I dont see any balance issues.

I would vote to merging it. Chickens can be tamed and trained to do tricks - seen them in the circus.

**Comment by TechyBen** [comment]
Domestication =/= taming
https://en.wikipedia.org/wiki/Domestication#Theory
(AFAIK anyhow). Though the scope of this PR may only cover domesticated animals. That is fine. Just make it clear to the player in the text/flavour descriptions as suppose to "taming". :)

**Comment by ZhilkinSerg** [comment]
Sure, but we are just heading towards making Cataclysm to Stardew Valley.

**Comment by nexusmrsep** [comment]
> Sure, but we are just heading towards making Cataclysm to Stardew Valley.

More like Graveyard Keeper. And that's not a bad thing if people are into it, if you ask me.

**Comment by TechyBen** [comment]
@ZhilkinSerg I see no problem with that [slides away with secret ulterior motives... ;) ]

**Comment by sfsworms** [comment]
Question, how hard would it be to add incubators or something to make chickens from eggs?

**Comment by mlangsdorf** [comment]
I think chicks already hatch (sometimes) from rotten eggs. And food already rots faster at higher temperatures. So you need to co-ordinate with nexusmrsep for an incubator device that works like a fridge, but in reverse: hot instead of cold. Conceptually it's straightforward enough, but I want to wait until he finishes the cold stuff overhaul before messing with that code.

**Comment by Mecares** [comment]
Luckily those eggs are usually found by foraging and not by looting super markets.

**Comment by nexusmrsep** [comment]
@langsdorf I think there is no need to simulate temperature inside the incubator. But hatching should interact with rot so eggs should not hatch from rotten egg. Perhaps some flags could be set so hatching eggs will not rot but won't be edible too (unless by those "barbarians" who eat cooked embryos).

**Comment by GroeneAppel** [comment]
I will mention again that chickens have no problems eating anything from worms to leftover meat scraps and vegetables/greens. The game should reflect this somehow, either through making these kinds of food edible for poultry, or by making them part of a crafting recipe for bird food. 

The reference @nexusmrsep has linked supports this

>Before the twentieth century, poultry were mostly kept on general farms, and foraged for much of their feed, eating insects, grain spilled by cattle and horses, and plants around the farm. This was often supplemented by grain, household scraps, calcium supplements such as oyster shell, and garden waste.

On the note of intelligence in chickens
> Smarter birds can certainly learn, "hey this person drops food, I should stick around", but even that is a stretch for e.g. a chicken.

Chickens are far more intelligent than one would expect. Training them is not a long shot whatsoever and is done more often than you'd think. You can train chickens to perform tasks for rewards, chickens are even smart enough to refuse a reward if they expect a better reward to follow afterwards. 
[Reference](https://www.springer.com/gp/about-springer/media/research-news/all-english-research-news/think-chicken---think-intelligent--caring-and-complex--/11952522)

**Comment by nexusmrsep** [comment]
What do we consider a tamed animal to be in this game? A companion like a trained dog or just a farm animal that doesn't run from us at the first sight and allows some basic actions like milking a cow, shearing a sheep? Becouse now I'm not even sure we are talking about the same principle.

**Comment by GroeneAppel** [comment]
That is a good point. I think for now we should focus on animals being tame. This meaning an animal should not run away, be milkable/shearable and you should be able to lead them around with a rope if needed. Animals like chickens perhaps should be wieldable to allow the player to move them around for short distances.

That said, tamed and trained animals might have a rather small gap between them. A cow might still want to approach a player knowing he is there to feed and pet him. In a sense this means it is trained to perform a certain behavior (approach the player). Perhaps in the future we can consider the difference between Tame and trained, where a tamed animal simply is friendly and wont run and a trained animal can take simple commands.

**Comment by mlangsdorf** [comment]
Not in the PR, but at some point I would like animals to have a couple of states:
  Wild/Feral (current state of non-friendly animals)
  Tolerant (animal will ignore you and not be frightened by you unless you attack it, but you can't interact with it)
  Friendly (animal is friendly, wants to be around you, will let you interact with it)
  Trained (animal is friendly and responds to orders)

and then there could be a way to turn some feral animals tolerant by repeatedly feeding them, and some tolerant animals into friendly and/or trained.

But the original request was "please make it so I can feed chickens and my allied NPCs will stop killing them." Let's just do that here and continue working on improving the game.

As far as a wide variety of chickenfeed: the recipe is ridiculously long already and takes a wide variety of options. If it really bothers you, I could add the CHICKENFEED flag to raw meat, raw offal, and stomachs, but that's also easily enough done in a separate PR.

**Comment by kevingranade** [comment]
I've been convinced re: domesticated birds, but please remove the flag from quail and Turkey, crows are pretty smart and fearless, but quail and turkeys are notoriously skittish.

Please change the flag to BIRDFEED if it's not going to be chicken specific.

Definitely dont expand the list of alternative components any more, it should be just things the bird will particularly aporeciate, but that has no migration implications so I'm fine to hash that out in another PR.

**Comment by mlangsdorf** [comment]
quibble: pheasants aren't quail but I get your point.
quibble: the flag was only for turkey and pheasant chicks, so you  could raise them to be friendly but not domesticate adults.

regardless, requested changes made in the new commit

**Comment by DracoGriffin** [comment]
>Sure, but we are just heading towards making Cataclysm to Stardew Valley.

This is coming in super late, but just wanted to point out (if Serg forgot and also for anyone unaware) there is a [long-term project for farming](https://github.com/CleverRaven/Cataclysm-DDA/projects/11) (and basically all that entails), especially if someone wants ideas on what to work on -- the projects page is useful for looking at bigger picture stuff, whereas working on Issues is always good for experience and patch up stuff.

**Comment by kevingranade** [comment]
If an action is a viable way to try and survive, then we want it in the game, it's that simple.  
Farming and animal husbandry DEFIINITELY meets this criteria, though honestly with our focus on realism, it's not going to be all that *fun*, because farming and animal husbandry is frankly boring as hell.  Ideally we can abstract this process out to:
1. Resource aquisition.
2. Logstics management.
3. Upkeep
If these are handled in a streamlined enough way, it becomes, "get your farm set up and producing, at which point many of your needs are met, and you just invest (off-screen hopefully) time to maintain it, and otherwise deal with more core game elements like exploration and combat."

That's the ideal of course, clearly we have a lot of streamlining/automation to do to meet that goal, but we can get there.

Also if someone wants to just run a farm simulator and occasionally fight off zombies and triffids, cool.

**Comment by nexusmrsep** [comment]
>  clearly we have a lot of streamlining/automation to do to meet that goal

If @acidia will make an player-NPC base on the run, that we all wish to see soon, then perhaps a farm supported by NPC's wouldn't be far behind?

**Pull request merged**
