### PR TITLE
NPCs - Free Merchant traders and trader guards 

### PR DESCRIPTION
**Pull request by Brytenwalda**
#### Summary
```SUMMARY:  Content "A gas station trading post with a merchant and two guards."```

#### Purpose of change
I believe that the game needs more trading outposts where players can exchange items. We already have a faction to do it, why not expand it a bit?

Overall, this should add another level of plausibility to this world - a traveling merchant who brings various individuals - hunters, fishermen, scavengers, and other survivors together through trade.

#### Describe the solution
1. Two new NPC classes - a field merchant and a guard.
2. A new mapgen building - a copy of the existing gas station, but with the merchant and two guards inside it. All items belong to the Free Merchants. 

#### Testing
I've tested this PR - everything works as intended and there are no errors.

### CODE REVIEW

**Comment by Brytenwalda** [comment]
I replaced the garage with a gas station - with garages merchants would often spawn in the middle of towns, densely populated by zeds, which made little sense. This doesn't replace the original gas station, but rather create another variant.

**Comment by Brytenwalda** [comment]
I added this mod to two of my games using the latest build and they worked like a charm, adding a lot of life to the world.

**Comment by Night-Pryanik** [comment]
Why did you remove garage mapgen?

**Comment by Brytenwalda** [comment]
> 
> 
> Why did you remove garage mapgen?

The merchants would spawn only deep inside cities which makes little sense.

**Comment by Night-Pryanik** [comment]
> The merchants would spawn only deep inside cities which makes little sense.

That's not a valid reason to remove pre-existing locations. If you want for your traders not to spawn in existing garages, add your own version which will spawn outside of the cities.

**Comment by I-am-Erk** [comment]
@Brytenwalda I'd love to merge this and your other changes, they just need a few fixes and some conflict resolution. Feel free to reopen these if you come back to fix up the last bits. I can talk to you on discord to help fix the last bits if you need help.

**Pull request closed without merging**
