### PR TITLE
Makes skin tone mutations conflict more consistently

### PR DESCRIPTION
**Pull request by Morat2255**
#### Summary
```SUMMARY: Bugfixes "Makes skin tone mutations conflict more consistently"```

#### Purpose of change
It is currently possible for a mutant to be both Albino (lacking all color or pigment) and possess a Phelloderm skin (described as green and containing chlorophyll, which is a pigment)

#### Describe the solution
Added "types": [ skin_tone] where appropriate. This should cause plant mutants to lose Albinoism or its more severe versions, as well as removing superficial skin color traits that would conflict with the description of Phelloderm claiming that the survivor has light green skin.

#### Describe alternatives you've considered
This could have been done using "cancels": [ ], but this way is more consistent, and makes it easier to maintain consistency with other mutations that could affect skin tone in the future.

I could also have added a superficial green_skin mutation with the skin_tone type as a prerequisite to Phelloderm in the same way that Pale acts as a prerequisite to Albino, but I thought that adding an extra trait was unnecessary, and carrying the "types": [ skin_tone] forward onto traits that evolve from Pale is more consistent with how other traits work, for example Fangs has "type": [ teeth ] and doesn't lose this type when it evolves into Shark Teeth.

A superficial Green Skin mutation could still be added in at a later date if necessary for the sake of consistency with how Albinoism works.

#### Testing
Created a character in a new world, spawned in a bunch of plant and troglobite mutagen. Found that gaining the Phelloderm mutation correctly removes Albinoism.

#### Additional context
This is an indirect buff to pre-threshold Troglobite mutants, because it makes it much easier to remove one of the major drawbacks to the mutation line simply by taking a small amount of Plant Mutagen. It's not a big deal, but it might be worth noting.

### CODE REVIEW

**Comment by DaviBones** [comment]
Your summary line is wrong; it has to be in a very specific form so the automated changelog can find it. Like this:
````
#### Summary
```SUMMARY: Features "skin_tone type added to mutations that alter skin tone"```
````
Also (this is more subjective) remember that a changelog should make it clear to the end-user (players) what is being changed, so try to word them to that end, e.g.: "Make skin tone mutations conflict with each other"

Your PR also failed the JSON validation -- this means you need to lint the JSON files you changed. You can use [this webtool](http://dev.narc.ro/cataclysm/format.html) to do so.

Other than that, good work! This is a great change.

**Comment by Morat2255** [comment]
Okay, thanks. Is there any way to make it rerun the PR Validator manually, or do I re-commit with no changes or something? This is my first time contributing anything to github.

**Comment by DaviBones** [comment]
You're good! It's annoying and confusing, but the old, failed PR Validator sticks around. However, the successful ones indicate that you've done it correctly.

**Comment by I-am-Erk** [comment]
I'd also suggest this is less a feature, more a bugfix

**Comment by DaviBones** [comment]
Yes I didn't even think of that, this definitely isn't a feature; a feature adds functionality to the game that wasn't present before. I'd say the proper category is either bugfixes (fixes things that cause faulty or inconsistent behavior) or balance (tweaks existing content and features in a way that adjusts difficulty levels, or makes the game more consistent with reality).

**Comment by Morat2255** [comment]
Yeah, you're right. I was just hesitant to call it a bugfix when the original functionality wasn't a "bug" exactly. It was working as intended, just not as it should work. It's a detail that was missed instead of something that was done wrong. But yeah, realistically, I should call this a bugfix.

**Comment by DaviBones** [comment]
Sorry, editing this summary line must be getting tiresome by now, but the proper name for the category is `Bugfixes`. Easy to miss, I make that mistake all the time myself.

You can always double check the categories and their meanings here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CHANGELOG_GUIDELINES.md

**Comment by I-am-Erk** [comment]
I don't know how to reset the pr validator, so I'm going to ignore it because the summary line is fine now.

**Pull request merged**
