### PR TITLE
Add Alcohol wipes to the game

### PR DESCRIPTION
**Pull request by ISuckM8**
#### Summary

Content "Add alcohol wipes to the game"

#### Purpose of change

Always carry alcohol wipes with you, kids. It could save your life. Jokes aside, alcohol wipes are pretty common (As far as I know at least) disinfectants, I'm surprised we still don't have them in the game yet.

#### Describe the solution

Simply adds alcohol wipes to post-apocalyptic New England. They spawn inside small cardboard boxes. They have a chance to spawn inside houses, doctor offices, and pharmacies.

#### Describe alternatives you've considered

Not adding them.

#### Testing

Well, it spawns, and my game is working just fine.

#### Additional context

image

### CODE REVIEW

**Comment by Venera3** [comment]
You're not cleaning a deep bite (or 80% of a deep bite) with a single alcohol wipe in a second. They're good for surface disinfection and aight for shallow cuts, but that's a different use case entirely.

**Comment by ISuckM8** [comment]
> 

So, 5 seconds?

**Comment by Venera3** [comment]
Bump the bite cleaning effectiveness down to 0.2-0.3 or so. 5 seconds are still very optimistic, since you need to get in all the hurty hurty nooks with your wipes,  but at least you don't get to do it in the middle of combat I guess.

**Review by kevingranade — CHANGES_REQUESTED** [review]
You seem to have a very major merge conflict or accidental inclusion here.

**Comment by ISuckM8** [comment]
> You seem to have a very major merge conflict or accidental inclusion here.

The file wasn't linted I guess, if I didn't lent it it would've gave an error on GitHub

**Comment by Termineitor244** [comment]
> > You seem to have a very major merge conflict or accidental inclusion here.
> 
> The file wasn't linted I guess, if I didn't lent it it would've gave an error on GitHub

@ISuckM8 the problem is that you replaced a whole file (data/json/itemgroups/Drugs_Tobacco_Alcohol/drugs.json) with another, and now your PR includes that, check the changes of your branch.

**Pull request closed without merging**
