### PR TITLE
Glass Shard Resize

### PR DESCRIPTION
**Pull request by roaringjohn**
#### Summary
SUMMARY: Balance "resizing glass shards to a more realistic volume"

#### Purpose of change
To fix the problem of glass shards being unrealistically large at 250 mL, which is a small sheet instead of a shard.

#### Describe the solution
Typically, a sheet of glass is going to be 2.5 mm thick, at the least. Based on the size of glass shards, a glass shard would likely be only a few inches long and wide.

So, therefore, I set the volume of the glass shard to reflect the likelihood of the glass being 2.5 mm thick, 6 inches long and 3 inches wide, thus being about 30 mL.

#### Describe alternatives you've considered
To leave the glass shard's volume where it is practically a sheet of glass.

### CODE REVIEW

**Comment by roaringjohn** [comment]
Everything has been linted already.

**Comment by I-am-Erk** [comment]
Although it's definitely not 250mL, I am sure glass shards in game are more than 2" long given that they're used for shivs and things. I'd assume something more around 6" long and 2-4" wide

**Comment by roaringjohn** [comment]
In which case, I'll change it to 30 mL, which means I'll have to change everything to be 5 times less as they are now.

Eh, all in the name of realism.

**Comment by I-am-Erk** [comment]
Why are you increasing the count of glass shards needed for everything so dramatically? Many of these recipes aren't volumetric

**Comment by Rail-Runner** [comment]
You might also want to reduce weight of glass shards to match its new volume, make them stackable (like ammo), and figure out how many glass shards the recipes have to use from the resulting item's weight.

**Comment by roaringjohn** [comment]
I've done so, now. Volume is considered for certain things, while weight is considered for others.

**Comment by SirPendrak** [comment]
I am not sure that giving irregular objects their exact volume is a right way to go. For example giant two handed sword that weights 3,5kg is only 0,5l in volume. So you should be able to store it in your jeans pockets, right? 
Or now you can fit large ammounts of shards in perfect order into your backpack. This doesnt seem right to me.

**Comment by roaringjohn** [comment]
Glass shards should be able to be stacked on each other. I changed a lot of recipes to reflect these changes, so that it would actually be balanced enough to not cause a problem as a "giant two-handed sword" would.

Realistically, they should do damage to whatever they're stored in, but I don't think that's implemented yet, so I can't do anything about that.

**Comment by bandti45** [comment]
Small tip you need to keep the same format so the change of ``` { "item": "glass_shard", "prob": 20, "count": 8 },``` when the spawn chance was formatted like ``` [ "glass_shard", 20 ],``` will cause errors.

**Comment by roaringjohn** [comment]
> Small tip you need to keep the same format so the change of ` { "item": "glass_shard", "prob": 20, "count": 8 },` when the spawn chance was formatted like ` [ "glass_shard", 20 ],` will cause errors.

From what I see in the files, it seems the format I'm changing them to should work? The change of format is intended to keep with the changes in volume and weight.

**Comment by dunstad** [comment]
Just curious, would it be possible to take existing glass shards in the world or on the player and multiply their number appropriately so that players don't effectively lose glass with this update? I know there are some kind of save migration features in this game, but I'm not sure if this is the sort of thing they're for.

**Comment by ZhilkinSerg** [comment]
Some migration code can be added, but I don't think it worth a trouble 4 weeks after this change is already in (not to say glass shards are basically trash).

**Pull request merged**
