### PR TITLE
Fixes for 84x246mm smoke rocket

### LINKED ISSUE #23573: errors in base game load.
Game version:0.C-27524-ga088cbc

Build: 7339
Operating system: Windows 10

Tiles or curses: Tiles

Mods active: 
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "brightnights",
  "AAA",
  "bio_mod",
  "FIC_Weapons",
  "realguns",
  "generic_guns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "crazy_cataclysm",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "Experimental-Z-Level",
  "trailerpark",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "battle_maid",
  "higanjima",
  "rf_food_keeper",
  "greaper",
  "hokuto",
  "Make_a_Lot_of_Items_Mod",
  "add_mutant",
  "tekitoumap",
  "Two_handoguns",
  "Useful_Goods",
  "windoor",
  "mori",
  "vorpal_weapons",
  "ATM",
  "more_classes_scenarios",
  "RL_Classes",
  "no_reviving_zombies",
  "StatsThroughSkillsFour",
  "StatsThroughKills"

happens on load.
cataclysm_ dark days ahead - 0 c-27524-ga088cbc 4_22_2018 2_44_59 pm

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Fixes #23573.

### CODE REVIEW

**Comment by AMurkin** [comment]
Thanks. No debug messages with this changes.

**Comment by 0Petya** [comment]
@ZhilkinSerg how did you figure out that it was the 84x246mm smoke rocket that caused the issue?
I'm trying to learn how to debug and navigate the project to contribute better.

**Comment by AMurkin** [comment]
Find in files or grep for a quoted text.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg how did you figure out that it was the 84x246mm smoke rocket that caused the issue?
I'm trying to learn how to debug and navigate the project to contribute better.

The issue started to appear after  experimental release 7339 (http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/7339/) which contained only changes from #23548, so I had to search for some strings displayed during error in tiny amount of files.

**Comment by 0Petya** [comment]
Ahh gotcha, thanks for the insight. I didn't think to see when the issue appeared and what recent changes may be causing it. That definitely narrows down the problem space.

**Comment by BorkBorkGoesTheCode** [comment]
Thank you for PRing this. Sorry for being such an annoyance.

**Pull request merged**
