### PR TITLE
Add field_remove and clear back bay and garage

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Infrastructure "Add field_remove and clear back bay and garage"

#### Purpose of change

Clean the back bay after Boris's cleanup quest.

#### Describe the solution

- Added `field_remove` similar to `item_remove` that removes all fields (blood, acid, etc.)
- Clears the back bay/garage after Boris's quest.
  - Removes all fields (blood, acid)
  - Removes all items
  - Clears most furniture (crates, lockers) from garage. Leaves vending machine, trash can, and shelves alone.
  - Clears beds from back bay. Moves lockers along the wall

#### Describe alternatives you've considered

Make `field_remove` work more like `trap_remove` where you have to define an id.

#### Testing

Load game right before finishing Boris's quest.

#### Additional context

Before:
image

After:
image
image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
We already have a way to remove fields: #53605.

**Comment by Ilysen** [comment]
Quick side note: "back bay" is actually kind of a misnomer. The place with concrete floors with the teamster and the guard is the garage; the back bay is the room with beds and lockers that actually has all the zombies in it. You could probably run the same (or a similar) mapgen on that tile too!

**Comment by haveric** [comment]
> Quick side note: "back bay" is actually kind of a misnomer. The place with concrete floors with the teamster and the guard is the garage; the back bay is the room with beds and lockers that actually has all the zombies in it. You could probably run the same (or a similar) mapgen on that tile too!

That's a fair point. I figured it would need to be expanded, but I focused on the initial garage area where the combat is likely to happen. It's fairly easy to expand this to another overmap though. Erk's planning on expanding this out to happen over time, so I'll work with him to see what needs to be expanded here.

**Comment by I-am-Erk** [comment]
We'll want to look into whether or not we need to clean up the map on the other side of the "back bay" as well, but this is good for the moment. Thanks!!

**Pull request merged**
