### PR TITLE
remove obsolete mods since 0.E

### PR DESCRIPTION
**Pull request by AriaMoradi**
#### Summary
Mods "remove obsolete mods since 0.E"

#### Purpose of change

Some of the obsolete mods are too old and not usable, we can remove them after a cycle according to policy.

More_Locations became obsolete in #37626
Mutant_NPCs became obsolete in #37272
National_Guard_Camp became obsolete in #37626
Urban_Development became obsolete in #37626
~~Military_Professions(Fuji_Mil_Prof) became obsolete in #37272~~
Other obsolete mods have not passed the "only if they've been obsolete for a whole cycle" condition for removal

#### Describe the solution
Removes the mods

#### Describe alternatives you've considered
Wait even more on removal

#### Testing
The mods are obsolete and can't be used in the game therefore no testing is necessary.

#### Additional context
This continues the work in #55887

### CODE REVIEW

**Comment by curstwist** [comment]
Hey, I still plan to mainline more of more locations and urban development,  but I have copies so I have no objections to this being obsoleted.

I'm not sure if that would cause any snags later when I make them vanilla though, per IDs. I could use new IDs if needed.

**Comment by Maleclypse** [comment]
#52736 is when military professions was obsoleted so deleting it now may cause some problems.  I'm pretty certain it was originally obsoleted when you listed but it was put back in until November 2021

**Comment by AriaMoradi** [comment]
> #52736 is when military professions was obsoleted so deleting it now may cause some problems. I'm pretty certain it was originally obsoleted when you listed but it was put back in until November 2021

So should I not remove that one?

**Comment by Maleclypse** [comment]
> > #52736 is when military professions was obsoleted so deleting it now may cause some problems. I'm pretty certain it was originally obsoleted when you listed but it was put back in until November 2021
> 
> So should I not remove that one?

Removing that one now would cause save migration issues.

**Pull request merged**
