### PR TITLE
Allows shrubs to drop withered plants, saw and hatchet alterations

### PR DESCRIPTION
**Pull request by DangerNoodle**
Added withered plants as a possible drop from bashing shrubs, foliage, and related plants. Reasoning is this further reduces the chances of a "need cordage for stone knife, need cutting quality to get cordage" scenario. Use of withered plants reduces the effect on the utility of dogbane and cattail stalks, as plant fiber is useful for far more things.

Added woodcutting quality to hatchets. Reasoning is one can plausibly cut trees and split logs with a hatchet, and we do not yet have construction time modifiers for less-than-ideal tools, which stone axes would already be subject to.

Finally, added sawing as an option for cutting tree trunks into logs. Reasoning is wood saws can be used to cut logs into shorter lengths, and that step would likely be a part of cutting them into planks already.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Though further observing forum posts pertaining to the screwdriver subject, the suggestion stated by @kevingranade suggests that use of string or cloth alone might be awkward for applying torque on a makeshift screwdriver.

Maybe adding a handle material to it, such as wood or bone, would be more sensible? Though my assumption was that the torque was provided by flattening the metal that was being held into a bar shape, and that the tape was used to make the shape less likely to cut the hand and fingers when used, a purpose that other materials hopefully would not interfere with in real life.

**Comment by John-Candlebury** [comment]
Isnt the current Stone knife basically the same item as the Stone chopper? What is the difference between them?

**Comment by DangerNoodle** [comment]
Problem is that use of thread or cordage is a natural part of making the knife, though it might be logically for a long enough stone to have an edge worked into it, leaving enough material to hold without needing a handle.

And differences mainly are in only requiring stone and hammering quality, while being inferior as a weapon and for butchering.

**Comment by DangerNoodle** [comment]
That said, as I mentioned earlier it might be viable to give sharp rocks a cutting quality instead. Any such method would sharply reduce the potential for a catch-22 scenario.

**Comment by Cyrano7** [comment]
Well you can already butcher with the sharp stone and it not that hard to find a withered plant or some plant fiber to make the primitive knife. Don't see why we need another rock knife.

**Comment by DangerNoodle** [comment]
Part of it is a focus on starting from zero survival skill as well. Sinew is an infrequent drop at low skill, while in my experience withered plants are surprisingly uncommon. They only spawn as forest trash and from farming.

Maybe a better focus would be in exploring what other sensible alternatives would be an option for obtaining plant fiber. What about wild vegetables? They are common and implied to be mixed species, so adding them as an option would likely require a large number to balance out how widely available they are in most seasons.

**Comment by DangerNoodle** [comment]
One other idea. Should withered plants be added to the forage results for summer and winter?

**Comment by Vidiveni** [comment]
Also don't forget about dogbane, found through foraging. Those are usually how I get my first wilderness string (plant fiber) for the stone knife. Would rather have withered plants or plant fibers added to the bushes than see a the tool added.

**Comment by DangerNoodle** [comment]
Might be good to make plant fiber easier to obtain via multiple methods instead of adding a new tool then. I am thinking mainly by adding withered plants to some seasons (which if I recall was implemented in More Survival Tools), and adding some additional way to find or craft plant fiber.

Allowing wild vegetables as an option might be a useful alternative, but any suggestions for a sensible amount needed? Possibly 2 two 4, but uncertain.

**Comment by Coolthulhu** [comment]
I'm against making screwdrivers essentially free.
If it is to be free, just remove it from recipes and allow using knives for the job.
Honestly, a screwdriver made from scrap hammered into shape is not going to be any better than a pocket knife at the job.

Wild vegetables to thread sounds incredibly arbitrary. And also makes dogbane obsolete.
How are you going to turn wild carrots/tubers/whatever into cordage?

**Comment by DangerNoodle** [comment]
Hmm. I could simply change the construction quality required, since that is the only instance where needing a screwdriver regularly causes absurdity. Any sensible alternatives?

And my main concern was that lack of a cutting quality is far more a gameplay annoyance than it adds to game balance. Realistically a sharpened rock is usable as a tool without a handle in the first place, but not that good a weapon obviously.

A better option might be allowing turning wild plants into withered plants. Rudimentary cordage for something as simple as wrapping an object can be made from grasses for example, so it might be better if wild vegetables or other miscellaneous plants were usable only for cordage, and not for obtaining thread to sew with.

**Comment by Coolthulhu** [comment]
> Hmm. I could simply change the construction quality required, since that is the only instance where needing a screwdriver regularly causes absurdity. Any sensible alternatives?

You could change it into 2 construction recipes: one with screwdriving and hammering 3 (not 2, since we don't want to hammer but to pull nails here, which doesn't have a quality, but real hammers with hammering 3 have it) and one with just cutting and more time.
Though this would be a bit hacky since it would rely on construction pseudo-recipes being read and processed in order (so that the faster one is checked before the slower one).

> A better option might be allowing turning wild plants into withered plants.

Wild veggy is not a whole plant. It is most likely some roots, a handful of small and delicate leaves/flowers (clover, thistle), broad leaves etc.
The more useful as cordage is a part of a plant, the less likely is it to be edible. And if different parts are used for food and thread, the recipe to turn food to thread makes no sense.

It would be better to boost the numbers of withered plants dropped as trash in forests. I'm pretty sure the current implementation already supports multiple drops of forest trash. It may be a good idea to remove the hardcoded 1-in-10 chance for trash drops and just encode it in the item group itself.

**Comment by DangerNoodle** [comment]
Ah, I see. I am unsure what the best way to deal with altering foraging behavior. Increased weight of withered plants in foraging, changing foraging into a distribution, or what? In all honestly though, making sharp rocks able to cut might be the simplest alternative, which is why I considered them as an alternative. All this balancing to work around a handle that is optional for real-world stone cutting tools makes it more awkward.

As for deconstruction, two alternative versions of deconstruction might also be awkward to implement. I wish I had managed to implement the idea of taking down simple constructions without the use of tools.

Apologies for the delay.

**Comment by DangerNoodle** [comment]
Reverted screwdriver recipe for now, as figuring out how to handle screwdriver usage might be best for a later pull request. Also removed the changes to plant fiber recipe. Uncertain about best method regarding stone knives at present.

**Comment by Coolthulhu** [comment]
That cutting on sharp rock should go too.
The only difference between sharp rock and stone knife is cutting, butchery and combat stats. Stone knife isn't good enough for combat, meaning that if sharp rock had cutting, the only difference between them would be butchery.

**Comment by DangerNoodle** [comment]
I see. Very well then, but are there any other alternative methods? I do not think I can easily alter foraging to make withered plants a more reliable source of cordage.

**Comment by DangerNoodle** [comment]
Should be ready, but I had an idea. What about reworking the hand axe in More Survival Tools to fill this niche in regards to tools?

Currently it is a medium-level survival craft that, due to only requiring rocks, outclasses stone knives as a tool, and has minor additional tool uses entirely. Even then, while it is easier to craft, at that point in the game is is utterly redundant. Rebalancing it by changing its tool uses while making it craftable earlier would affect balancing in a different manner. It would fill the more useful niche of a wilderness cutting tool that does not require thread, with the catch being it restricts the niches of the stone knife.

The stone knife would still be vastly better for butchering, as any negative butchering quality is effectively unfeasible, while being able to sheath it would make it more practical to carry around. However, the negative effects of such an idea of easier to justify in mod content, especially if it means rebalancing an underused item in said mod.

**Comment by Shpid0inkle** [comment]
The idea that plant fibers are hard to come by in a forest is ludicrous to start with.  What about a construction option to dismantle undergrowth for plant fibers? Or bushes in the plain if you don't want to lose the loot able ones.

**Comment by DangerNoodle** [comment]
Realistically that might be the best option, but I am unsure how to implement that.

**Comment by BorkBorkGoesTheCode** [comment]
You could make shrubs smashable; look at f_hay for example.

**Comment by Coolthulhu** [comment]
They are smashable already.

Making shrubs/undergrowth produce fiber sounds really bad. Withered plants - sure. Sewing quality fiber - no way.

**Comment by BorkBorkGoesTheCode** [comment]
Sorry, I was incoherent: I meant something like this from t_tree_hickory:

```
        "bash": {
            "str_min": 80, "str_max": 180,
            "sound": "crunch!",
            "sound_fail": "whack!",
            "ter_set": "t_dirt",
            "items": [
                { "item": "stick", "count": [3, 10] },
                { "item": "splinter", "count": [10, 25] }
            ]
```


Where "stick" is replaced with "plant_fibre" or "withered".

**Comment by DangerNoodle** [comment]
Maybe giving them a decent chance of yielding withered plants would be the best option, since a source of cordage is realistic and better for game balance, while sewing thread is not. Any suggestions for chances and amount?

**Comment by BorkBorkGoesTheCode** [comment]
I'd suggest 1-4 withered plants, but that is just an arbitrary amount loosely based on the standard 1-2 withered plant requirement. I'd need to find a reference for the size of the shrubbery, or pick one myself. It would be a significant short-term boon for crafters, since there are significantly more shrubs than any other comparable crafting substitute.

**Comment by Coolthulhu** [comment]
30% chance for 1 would be enough.
It's not like you need a lot of withered plants, no need to spam them.

**Comment by DangerNoodle** [comment]
> 30% chance for 1 would be enough.

Seems reasonable for shrubs and underbrush, then.

**Comment by DangerNoodle** [comment]
Odd though. I can not find an example of a bash result that includes chance.

**Comment by Coolthulhu** [comment]
Bash and deconstruct use same syntax. There is a chance drop for minireactor somewhere.

**Comment by DangerNoodle** [comment]
Ah, thank you. might be under furniture, so far no examples under terrain.

**Comment by keyspace** [comment]
The preamble (and PR name) no longer reflect the changes proposed. :/

Not sure about best way to proceed. Close this and open another PR, referencing this one?..

**Comment by kevingranade** [comment]
Closing this one and opening a new one would be prefferable, but editing
the topic and probably description would be fine too.

**Comment by DangerNoodle** [comment]
My apologies for not being on to respond until now. I can edit the name and description as desired.

**Comment by DangerNoodle** [comment]
This should be ready.

**Pull request merged**
