### PR TITLE
Weapon mods tweaks

### PR DESCRIPTION
**Pull request by Night-Pryanik**
1. Added missing info when mod is applicable to bows, crossbows and launchers;
2. Let the game know that bullet crossbow is a crossbow too.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Now if someone knew how to deal with guns removing integral mods when hitting unload with an empty magazine... >.<

**Comment by kevingranade** [comment]
Please don't complain about things in unrelated issues and PRs, it's not
going to get it fixed any earlier and it's annoying.

**Comment by Rivet-the-Zombie** [comment]
Indeed, it's likely it won't even be noticed since it's hidden in a PR unrelated to your complaint. Open an issue specific to the topic and it will be much more likely that someone will notice it and take action.

**Comment by chaosvolt** [comment]
Sorry.  x.x

**Pull request merged**
