### PR TITLE
Fix AIM item moving bugs.

### LINKED ISSUE #28023: Advanced inventory moves wrong items (bones)
**Describe the bug**  
Advanced inventory moves items not from pile that was selected.

**To Reproduce**  

0. Have different types of bones on the same tile with some other items. Wish for 10 bones. Spawn a beaver. Kill the beaver and butcher it. Put wished-for bones in the same tile as beaver bones. ~~I have three types of bones: one from underbrushes, one from butchered beaver, one form butchered pit bull mix.~~
1. Try moving one bone from each group or some other items from the save tile into your inventory.
2. When selecting bones only one group is moved, additionally sometimes bones from this group is moved when some other item is selected for moving.

**Versions and configuration:**
 - OS: Ubuntu 19.04
 - Game Version: latest master, 37a8bcd
 - Graphics version: Tiles

**Additional context**  
If this will not be confirmed in several hours I'll try to produce a minimal savegame for reproduction.

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: None```

#### Purpose of change
Fixes #28023.

#### Describe the solution
I introduced some faulty logic for finding the indexes of items in  #27793, I blame part of that on an erroneous comment, but I also forgot to take into account that items of the same type can fail to stack with each other.

#### Additional context
went with "None" for the summary cause this really should have been part of the PR that was merged last night.

### CODE REVIEW

**Comment by ifreund** [comment]
Yeah, just confirmed.  Looks like that was a bug even before #27793 when using move all, and I copied the faulty code from that.  Will get to work on it.

P.S. Thanks for catching all my bugs lol

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Comment by l29ah** [comment]
Nah it's still broken.

**Comment by l29ah** [comment]
I cannot move my stuff when it's shown in "All 9 squares" mode.

**Comment by ifreund** [comment]
>I cannot move my stuff when it's shown in "All 9 squares" mode.

Odd, it works fine for me.  Could you possibly open an issue with some details on how to reproduce?  Maybe a save file?

**Pull request closed without merging**
