### PR TITLE
Sanity pass on the fungal acidic zombie

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
So the acidic fungal zombie - the Day Tripper. Because acid? And acid is drug, also, in one of the meanings? And hallucinogenic mushroom drug too? Yeah no.

#### Describe the solution
- Removed all of its hallucinogenic gas - it turning from having corrosive blood to suddenly spitting hallucinogenic spores makes no sense
- Added a new harvestlist for fungal zombies with acid blood
- Added a flag that gives it acid blood
- Added an acid blood death effect
- Removed the dodge that's a remnant of our base acid zombies being dodgy in the past
- Renamed
- New description - written by @themaster567 

#### Additional context
Consider this an offshoot of #77321 that I opted to split since it changed too much even for that PR

### CODE REVIEW

**Comment by Fris0uman** [comment]
Hallucination inducing monster is more interesting that yet another acid zombie, no? At least it's new instead of variant number 50 of brute/acid/boomer

**Comment by Karol1223** [comment]
> Hallucination inducing monster is more interesting that yet another acid zombie, no? At least it's new instead of variant number 50 of brute/acid/boomer

Interesting? Sure. But this is about what makes sense more. 

I am all in for a hallucination inducing monster, but not for this specific use case. There's infinite places to put one in, it does not have to be forced here.

**Comment by Kantonine** [comment]
> Hallucination inducing monster is more interesting that yet another acid zombie, no? At least it's new instead of variant number 50 of brute/acid/boomer

I'd like to put my 2 cents in:

I'd say the best candidate for a hallucination zombie is a offshoot of the zombie necromancer/master line, losing the ability to raise corpses, for direct attacks from a distance (maybe still have it be cowardly against trying to attack you by it's lonesome)

**Comment by Karol1223** [comment]
> I'd say the best candidate for a hallucination zombie is a offshoot of the zombie necromancer/master line, losing the ability to raise corpses, for direct attacks from a distance (maybe still have it be cowardly against trying to attack you by it's lonesome)

That quite literally takes away everything that was unique about the daytripper and just makes it a flimsy Flaming Eye clone that plays on team zombie and somehow is special enough to get advanced intelligence treatment. I would be very against this.

**Comment by ampersand55** [comment]
The hallucinogenic aspects makes more thematic sense than the acid aspects for a fungal zombie. 

A player could make the connection between fungals and real life psilocybin mushrooms, and hallucinating is a big part of the [Mycus lore.](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/Lore/lore-factions.md#the-mycus
) (inline code blocks for emphasis)

> Are these actually an indication of an intelligence directing the zealots' actions, or is it just that the fungal abscess in the brain causes a consistent pattern of `hallucination`, which is commonly personified as a sort of deity? (...) Another way to consider this is to remember that the Mycus should also be written such that it is in fact a delusion created by the infectee's sick brain, and the fungal mass in there secreting happy juices along with it. You start having dreams about mushrooms from a `hallucinated` mushroom god, and those come with happy hormones. (...) It may be helpful to read accounts of what it's like to suffer delirium or psychotic `hallucinations` to get ideas of how to write an experience communicating with the Mycus.

But off course, the day tripper is part of the evolution of acid-type zombies and this PR fits well into that.

**Pull request merged**
