### PR TITLE
Chainmails cleanup and fix

### PR DESCRIPTION
**Pull request by xMordet**
#### Summary
Bugfixes "Modification of chainmail armors for consistency, ease of modification and minor fixes"

#### Purpose of change
The various chainmail armors were a mess of copied pieces of armor, odd pocket sizes and unusable ablative optional pieces.

Now, it's possible to put lamellar armor (9.25L) in the chest pocket of chainmail, as the pocket is now 10.5L, previously 7.5L. Moreover, this has the nice side effect of making adding an additional plate of armor on brigandine possible, when attached, as it used to be too small.

Finally, I modified the nomad chainmail because it was described as a full body armor and the blacksmith makes the armor based on the full body suit but it copied the hauberk. So, while it had armor values on it's legs, it didn't have the pockets to add additional ablative plates.

All in all, removed ~2300 lines while making modifying those classes of armor easier

#### Describe the solution
I created a "master" piece of armor for each type and made the pieces of armor get their values from there. The list for those abstract armor pieces is in items\classes\armor\chainmail.json.
Now, to modify all the pieces of chainmail armor that hold ablative pieces, it's possible to go there and make sweeping changes.

#### Describe alternatives you've considered
The original goal was only to allow the use of lamellar armor with chainmail, so I could have modified only that, but the way they were implemented was kind of inefficient. May as well clean things up.

#### Testing
Spawn any one of any type of chainmail armor that can hold plates of armor, spawn the fitting armor piece, that is any item with one of the ABLATIVE_CHAINMAIL_X (with X being either torso, arms, legs, knees or elbows) and put them in the corresponding pocket. it should also work with XS and XL variants

#### Additional context
While the brigandine can, theoretically hold [EXTRA_PLATING](https://cdda-guide.nornagon.net/json_flag/EXTRA_PLATING), the pocket is not defined with a maximum length, so you can't actually put it in. I'd change that, but I'd rather make another PR and do the same kind of deep work on them.

Finally, to make the abstract pieces of armor, I thought of using a null material to make sure no mistakes can be made, as the game throws an error when a non-abstract item has the null material. However, when using the replace_materials tag, the weight got multiplied by 8, the density of the various steels, since the weight of null is 0. So I could have either divided the weight of the abstracts by 8, used another material that matched the density, or change how replace_materials worked so that it overwrote the density of original material, instead of multiplying it. In the end I went with using generic steel as the base material as it has the same density as the specific steels used for the pieces of armor. I did so because dividing by 8 would have made it odd with weird rounding and changing how replace_materials works is, for one, beyond my knowledge and, for two, I didn't know how deep the repercussions would go.

### CODE REVIEW

**Comment by Maleclypse** [comment]
> This is way to big to review. Especially if you're doing cleanup work and making balance changes, those ought to be separate, because nobody can tell the balance changes you made when everything around it changes.
> 
> > I created a "master" piece of armor for each type and made the pieces of armor get their values from there. The list for those abstract armor pieces is in items\classes\armor\chainmail.json.
> 
> I'd suggest making a PR doing this piece by piece, then once it's all done you can make the balance changes.

Seconding:
If you can keep it to around 500 lines of JSON per PR for something like this, I was not having any luck reviewing it because I basically had to jump from top to bottom for every single item.

**Comment by Maleclypse** [comment]
Seeing these in smaller chunks has been impressive. Great work!

**Comment by Maleclypse** [comment]
I think this is ready to close now?

**Comment by xMordet** [comment]
> I think this is ready to close now?

oops, forgot about this, yeah.

**Pull request closed without merging**
