### PR TITLE
Make EMP Grenades Harmful

### PR DESCRIPTION
**Pull request by Rjtheperson**
Summary
SUMMARY: Balance "Gives EMP Grenade electrical damage."

Purpose of change
This change fixes the fact that holding an EMP Bomb in your hand until detonation is harmless. #41847 

Describe the solution
~~I gave the EMP Grenade 40% of the EMP Bomb's explosion damage since the radius of the EMP Grenade is 60% smaller than the Bomb version's.~~
**EDIT:** I have added an electrical field to the EMP Grenade detonation and removed any damage that isn't electric or EMP.

Describe alternatives you've considered
None

Testing
I edited the grenade's json file and tested it in a copy of CDDA I use for testing and spawned the emp grenade in. ~~I then detonated it in my hand and died.~~ The grenade saps bionic power, breaks robots and deals minor electric damage.

Additional context
None.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@John-Candlebury is this your grenade?

**Comment by Qrox** [comment]
Are EMPs supposed to do physical harm? Don't they just release electromagnetic waves by discharging through an antenna?

**Comment by John-Candlebury** [comment]
In my opinion that the emp grenade shouldn't fragmentate as powerfully as your suggest here. 

There are real life grenades that still explode powerfully but are designed to minimize fragmentation, like Mk3 or  SOGH grenades . I think a similar design to those grenades would make more sense in this case, since the supposed point of an EMP grenade is to disable electronics, not riddle them with fragments.  As such, I suggest you choose to shape it similarly to an SOGH grenade, just because those are newer. That would mean:

- Update its description and weight to indicate that its almost wholly made of plastic.
- Keep the shockwave explosion, but reduce its power so that its not normally lethal unless you are within 2m of it (the open field effective range of a mk3, as I couldn't find it for the SOGH).
- Heavily reduce the fragment weight to something less than 20 grams, to represent the parts that couldn't be plastic. (namely the coil that generates the EMP and the elements of the stripped down plutonium cell that also couldn't be plastic)

---

Aside from the realism/military design perspective. Now that HUB 01 will lose its CBMs, and will also likely loose most of its  advanced robots, to the Exodii I'd like the few remaining scraps of hypertech that are exclusive to them to be good pieces of gear, and the changes proposed here are big nerf  EMP grenades general usability.

I would like to keep the harmless version of the EMP grenade, but lore-wise I dont think plutonium cells are powerful enough to simply produce the EMP effect by being discharged to an antenna. I'd like to be sure about that.

**Comment by Rjtheperson** [comment]
I think it would make more sense if there was a way to give the detonation a small electrical explosion similar to a shocker zombie's ranged attack but there is no electrical explosion type to work with in the explosive tools json.

**Comment by Duck13Tales** [comment]
I too think that a EMP should be harmless to organic beings as it mostly discharge electromagnetic pulses that damage electronic equipment. It's damage isn't due to the explosion or shrapnel that probably isn't needed at all.

Maybe it could damage your CBM's and other electronic equipment that you have in it "range".

**Comment by Rjtheperson** [comment]
Currently working on making the emp grenade do electrical damage.
EMP Test 2

**Comment by Rjtheperson** [comment]
The EMP grenade now releases a small electrical cloud similar to what electrical zombies emit. I removed the explosion radius since it didn't do anything but kept the EMP field. I wanted the electricity to do a bit more damage but I don't think it's possible without somehow altering the electricity field which would affect everything else in the game that uses it.

**Pull request merged**
