### PR TITLE
Exorcised demon, and linted file

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
What's the point of this?

**Comment by BorkBorkGoesTheCode** [comment]
Why not?

**Comment by Nymall** [comment]
It's a pointless change. This is an object that the player has no way of actually encountering.

**Comment by BorkBorkGoesTheCode** [comment]
It's a pointless joke. Although the decision to extend it to 9000 wasn't a good idea. I' reducing it to 1.00. I think you guys are attached to the number for some reason.

**Comment by BorkBorkGoesTheCode** [comment]
There. It's no longer a dumb religion joke or OVER 9000!!!!, and it will speed up the loading times and downloads slightly.

**Comment by Rivet-the-Zombie** [comment]
>Why not?

It's a completely pointless change.

>it will speed up the loading times and downloads slightly.

I'm fairly certain that it will not, or at least it will not do so to a degree that anyone would ever notice.

**Comment by BorkBorkGoesTheCode** [comment]
>I'm fairly certain that it will not, or at least it will not do so to a degree that anyone would ever notice.

When I tried deleting a single whitespace, it did effect the size of the file. The current version of this PR will do the same.

**Comment by Nioca** [comment]
Er, unless Github does weird things to file size, we're talking about a difference measured in bytes here. If someone on 56k dialup (*hand raise*) wouldn't notice it, it's really not worth the effort.

Which brings me back to echoing Rivet about what, exactly, this change is supposed to accomplish.

**Comment by BorkBorkGoesTheCode** [comment]
Originally, to replace the unbelievably "edgy" meme with a modern meme, then an attempt to decrease file size.

**Comment by BorkBorkGoesTheCode** [comment]
Have just linted testing.json

**Comment by DangerNoodle** [comment]
It is a lint fix for a minor file. While it is a strange thing to bother with linting, all the fuss over it is at least as strange.

**Comment by Coolthulhu** [comment]
Hexakosioihexekontahexaphobia

**Comment by illi-kun** [comment]
Third time (afaik) you merge both content changes & formatting stuff.

Please PR these changes separately (formatting changes will be accepted, unreasonable changes of content will be refused).

**Pull request closed without merging**
