### PR TITLE
Reword interrupt prompt

### PR DESCRIPTION
**Pull request by Arokha**
#### Summary
Interface "Reword activity interrupt prompt option"

#### Purpose of change

The prompt is a lie. The current wording `Ignore further distractions and finish` is incorrect in two ways.
1. It implies that you will ignore further distractions. That is not what the button does (and will especially not be what it does if #55913 is merged). It ignores THAT distraction. Not all distractions for the rest of the activity. Instead it should say 'this' distraction, not imply that all distractions will be ignored.
2. It implies you will finish and there's no more interruptions between you and finishing. This isn't knowable to a simple dialog box and instead it should say 'continue'.

#### Describe the solution
Reword the dialog option to `Ignore this distraction and continue`

#### Describe alternatives you've considered
Also fixing the 'No' to something else because 'No' is very useless in that dialog box as it will just prompt you again in the next turn assuming the situation hasn't changed (in a very short amount of time, no less).

#### Testing
Didn't, though it's just a string change.

#### Additional context
Discussed in the discord about this box and it's wording a bit.

### CODE REVIEW

**Comment by Qrox** [comment]
The `.po` files should not be changed here, they are periodically pulled from Transifex and will be overwritten.

**Comment by Arokha** [comment]
> The `.po` files should not be changed here, they are periodically pulled from Transifex and will be overwritten.

Ah ok, I'm not familiar with all that. I removed them from the commit.

**Comment by Night-Pryanik** [comment]
If we need absolutely clear text, it should be something like `Ignore this type of distractions` or `Ignore further distractions of this type`. Because it ignores not one "this" distraction, but "type" of distractions you was distracted by.

**Comment by Arokha** [comment]
> If we need absolutely clear text, it should be something like `Ignore this type of distractions` or `Ignore further distractions of this type`. Because it ignores not one "this" distraction, but "type" of distractions you was distracted by.

It's true, though I think from a user's perspective who won't have any idea that there's actually distraction types enumerated, they might not understand that something like spotting an enemy and the enemy being very close are two different types of distraction. Given that, it's 'over the line' for me in terms of expected user understanding, though I can change it to one of those if you prefer. IMO, anything is better than what it is now.

**Pull request merged**
