### PR TITLE
Minor changes to morale logic

### PR DESCRIPTION
**Pull request by codemime**
This PR incorporates changes proposed by @Coolthulhu in  #16080.
1. Morale penalties are applied independently for "hot" and "cold" morale. [Link to the discussion](https://github.com/CleverRaven/Cataclysm-DDA/pull/16080#discussion-diff-58915676)
2. Players can't benefit from wearing equivalent super fancy items (two monocles, two wedding gowns, etc). Super fancy bonuses are still applied per item, not per body part. [Link to the discussion](https://github.com/CleverRaven/Cataclysm-DDA/pull/16080#discussion-diff-58919143)
3. Unit tests were updated accordingly.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Stylish morale isn't updated in all cases. It would be safer to force a recalculation on every worn item change.

Losing a worn stylish item to damage keeps the bonus. The bonus isn't lost when the same kind of item is worn again and removed.

**Comment by codemime** [comment]
> Stylish morale isn't updated in all cases. It would be safer to force a recalculation on every worn item change.

Could you be more specific, what did you do exactly?

> The bonus isn't lost when the same kind of item is worn again and removed.

Couldn't reproduce. Seems to be fine IMPOV.

> Losing a worn stylish item to damage keeps the bonus. 

Yes, it's an issue. Good catch! `item::on_takeoff()` isn't called when an item gets removed due to damage or after cutting it up. I'm gonna fix it.

**Comment by codemime** [comment]
> Yes, it's an issue.

The issue seems to be more complex than I'd like. Item removing code in `visitable.cpp` has pieces of painful duplication and therefore is fragile. Also, and more important, Items don’t know who wears them; inventory doesn't know whose it is. When you directly remove an item, or delete something from an inventory, they have no way to tell `character`s about it (i.e. to update their `worn` list). This produces ugly (and extremely fragile) workarounds scattered over the code. Subscription would work well here, but I see no easy way to introduce it and avoid explicit copy constructors for subscribers at the same time (the problem I stumbled upon several times here before).

**Comment by BevapDin** [comment]
Btw. (may be related): `player::wear_item` calls either `on_item_wear` (which appears to do some morale related stuff) *or* `item::on_wear`, depending on the parameter `interactive`. This looks wrong. Both functions should be called.

**Comment by codemime** [comment]
@BevapDin I daresay it's unrelated. `item::on_wear` calls `player::on_item_wear` so it gets called in either case. Silent invocation (with `interactive = false`) seems to be meant for NPCs and during chargen. It skips messages, encumbrance recalculation, and artifacts handling (presumably work only for `u`). 

I agree, it's ugly and wrong. A proper solution would be in overriding `wear_item()` if this behavior is intentional. Also, we need a totally different mechanism of suppressing messages than passing flags around. I think, error messages should be returned from checking functions (such as `player::can_wear()`) maybe inside a `sturct` along with some kind of error code. Then the caller should decide what to do with them (either print them somewhere, or simply ignore). Concerning the issuers of messages (`player`, `Character`, `npc`), they should themselves be able to be switched into a `silent mode` and simply ignore all messages whether they sent.

But all those things don't belong to this PR, of course.

**Comment by Coolthulhu** [comment]
* Get naked
* Get Stylish
* Wear a full set of heavy survivor armor
* Wear a wedding dress on top
* Have a zombie bash on you until your wedding dress is destroyed
* +10 Stylish morale is still there and doesn't time out

**Comment by codemime** [comment]
I've put workarounds, but a proper solution is possible only with good encapsulation. The `worn` vector must not be exposed. It's a pain!

**Comment by Coolthulhu** [comment]
It's generally a better idea to recalculate the whole state on a change than to try to keep everything synchronized, at least with containers that aren't encapsulated and calculations that are relatively cheap and not invoked often.

**Comment by codemime** [comment]
> It's generally a better idea to recalculate the whole state on a change than to try to keep everything synchronized, at least with containers that aren't encapsulated and calculations that are relatively cheap and not invoked often.

I disagree. It would be better to increase encapsulation (we definitely want it) gradually, getting rid of the workarounds along the way. I'll add test cases for them later on (not in this PR) and they would be a good indication of consistency during further changes (along with observable behavior). Total recalculation is a step backwards.

**Comment by Coolthulhu** [comment]
> Total recalculation is a step backwards.

Would be, if synchronization was guaranteed. Until it is, it would be better to suppress synchronization and just recalculate everything on every change.
Or maybe recalculate everything all the time, compare it with synchronized state and debugmsg on a discrepancy.

**Comment by codemime** [comment]
> Or maybe recalculate everything all the time, compare it with synchronized state and debugmsg on a discrepancy.

I like that.

**Comment by kevingranade** [comment]
Just FYI, I consider keeping things synchronized instead of recalculate get
them to be a (presumably unnecessary) optimization, recalculating on demand
is generally going to be cleaner.

**Pull request merged**
