### PR TITLE
Implement "time" component for recipes

### PR DESCRIPTION
**Pull request by Coolthulhu**
Currently only for tools and components, NOT qualities. Qualities have a different internal structure and changing that would double the size of this PR.

It's not very usable at the moment due to fixed structure of "requirement tree" - it ANDs list of ORs.
This means it is only really usable for optional requirements: use tool x or don't use it and instead consume extra time.

As an example, I changed cotton ball carding recipe: instead of having by_hand and with carding paddles, there is one recipe that uses paddles or adds 45 minutes to craft time.

### CODE REVIEW

**Comment by angoddu** [comment]
So what you're saying is without the right tools, some crafting recipes can be done but will take far longer?

**Comment by angoddu** [comment]
I like that. It adds a bit of realism and the sense of ingenuity of the survivor

**Comment by AlecWhite** [comment]
>I like that. It adds a bit of realism and the sense of ingenuity of the survivor

And it gives a reason to actually _use_ power tools.

**Comment by angoddu** [comment]
> And it gives a reason to actually use power tools

I almost never use power tools when there is a non-power tool available. I horde my batteries/gas

**Comment by Coolthulhu** [comment]
> I almost never use power tools when there is a non-power tool available. I horde my batteries/gas

At the moment there is no reason to.
If using power tools with vehicle power was faster than manually crafting, it would make sense to use them.

**Comment by dunstad** [comment]
I'm interested in power tools being useful, so I'm curious what needs to happen to get this in the game. Is there a particular part of the crafting overhaul in https://github.com/CleverRaven/Cataclysm-DDA/issues/29210 that it's best to wait on?

**Pull request closed without merging**
