### PR TITLE
[CR] Enable to customize 16 ANSI color slots

### PR DESCRIPTION
**Pull request by mnacamura**
A minimal hack that achieves #19752.
With this PR, you can customize the 16 color slots in `$(config_dir)/base_colors.json`.

It would be better if it were integrated into the color manager.
Unfortunately, that's beyond my ability.

### CODE REVIEW

**Comment by kevingranade** [comment]
Sorry this got lost at the bottom of the pile for so long but...

Exceptions are not control flow :/

You can check to see if your base_colors config file is present directly and then try to load it, but the whole doing something you know will throw an exception ometimes and then goto-ing out of the exception handler has got to go.

**Comment by mnacamura** [comment]
> Exceptions are not control flow :/

My bad habit. Fixed it.

**Comment by mnacamura** [comment]
Any feedback?

**Comment by Coolthulhu** [comment]
I recall there being some (potential?) issues with file paths in localized versions found by @BrettDong 
Is this one safe?

The code looks good to me, though it has minor issues with styling (spacing) and duplication of color loading code in 2 files.

**Comment by BrettDong** [comment]
Not really 'in localized versions', but is the fact that on some
platforms file paths are encoded in another encoding scheme different
than UTF-8. Maybe I didn't make the point clear in my bad English
explanation. For example, in the case of the Chinese language: There are
three different popular Chinese character encoding schemes widely used,
BIG-5, GB-18030 and UTF-8. They arranges the character map differently.
Take a Chinese character as an example, in BIG-5 it is 0xaa 0xba, but in
GB-18030 it is 0xb5 0xc4, and in UTF-8 it is encoded as 0xe7 0x9a 0x84.
CDDA uses UTF-8, and read files as if the file path is in UTF-8.
Thankfully on Linux and macOS, file paths are encoded in UTF-8, so there
isn't any problem. But on Windows, things are different: Simplified
Chinese edition of Windows uses GB-18030 encoding scheme on its
filesystem. In CDDA we try to write the file '0xe7 0x9a 0x84', however
the sequence presents a different character in GB-18030, or even doesn't
present a valid character. Then the thing get messed up.


IIRC, there would be no problem if we were dealing with full ASCII file
paths. If my knowledge is correct, all later character encodings are
backward compatible with ASCII. Although the same Chinese character is
encoded in different sequences in different encodings, '1' is encoded in
0x31, 'A' is encoded in 0x41 as ASCII does. Japanese JIS might be an
exception, but I don't know much about it.

**Comment by AMurkin** [comment]
[It's broke win curses builds](https://github.com/CleverRaven/Cataclysm-DDA/pull/19814/files#diff-d63750223dea1b6d8e916ff75f39ff54R687)
```
src/wincurse.cpp: In lambda function:
src/wincurse.cpp:725:34: error: 'custom_path' is not captured
         std::ifstream colorfile( custom_path.c_str(), std::ifstream::in | std::ifstream::binary );
```

**Pull request merged**
