### PR TITLE
Make Aftershock atomic smartphone a valid music-playing device.

### LINKED ISSUE #37420: Aftershock atomic smartphone not playing music
# Describe the bug

The atomic smartphone doesn't play music.

# Steps To Reproduce

1. Use Aftershock mod.
2. Get an atomic smartphone.
3. Activate listen to music.

# Expected behavior

When activated, music should be playing through headphones like with the mp3 or smartphone.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11598-g075afa3
 - Graphics version: Tiles
 - Mods loaded: Aftershock

### PR DESCRIPTION
**Pull request by eilaattwood**
#### Summary
```SUMMARY: Bugfixes "Aftershock atomic smartphone not playing music"```
#### Purpose of change
Fixes #37420 
#### Describe the solution
Added checks for afs_atomic_smartphone item in iuse::mp3 method

#### Describe alternatives you've considered
Rework that function to avoid item id hardcoding.

#### Testing
Created game with aftershock mod, spawned atomic smartphone, smartphone and mp3 player, tried to use all of them.
Created world without Aftershock, spawned mp3 and smartphone, used them.

#### Additional context
@Maleclypse please comment if I should add something else into that check.

### CODE REVIEW

**Comment by Maleclypse** [comment]
The Wraitheon smartphone could potentially also use MP3 playing. If making play mp3 a flag or some other form of json using instead of a hardcore is within the realm of possibility then that would benefit more than just Aftershock.  But if that’s too much to ask no stress. I appreciate what you are doing.

**Comment by eilaattwood** [comment]
> The Wraitheon smartphone could potentially also use MP3 playing. If making play mp3 a flag or some other form of json using instead of a hardcore is within the realm of possibility then that would benefit more than just Aftershock. But if that’s too much to ask no stress. I appreciate what you are doing.
Yeah, changing the code is too so deeply is too much for me as for now. Maybe later.

So should I also add Wraitheon smartphone to the list? Unfortunally, I would be away from my work computer with C++ development setup for a weekend, so I'll do it next week.

**Comment by Maleclypse** [comment]
> So should I also add Wraitheon smartphone to the list? Unfortunally, I would be away from my work computer with C++ development setup for a weekend, so I'll do it next week.

Please add Wraitheon Smartphone to the list.  Whenever you get to it is great. :)

**Comment by eilaattwood** [comment]
I'm done for now, this can be merged.

**Pull request merged**
