### PR TITLE
Mirror item as vehicle parts

### PR DESCRIPTION
**Pull request by cainiaowu**
Currently, the only use for hand mirror is as vehicle parts. 

So I add some more description and change its category to reflect that.

### CODE REVIEW

**Comment by kevingranade** [comment]
Why? It's not intrinsically a vehicle part, it's a hand mirror.

**Comment by cainiaowu** [comment]
Well, when you take down a wind mirror from pristine car, you get a hand mirror.

Or we might just change the item name as well.

**Comment by Karbine** [comment]
Hand mirrors are used in some crafting recipes, such as makeshift shaving kit and makeshift haircut kit.

**Comment by cainiaowu** [comment]
makeshift item can still use it as components, the main problem here is that you get hand mirror out of factory made car.

**Comment by cainiaowu** [comment]
well, my argument is removing wing mirror from pre-cataclysm factory made car give you a hand mirror, which it should not be. It has nothing to do with item spawn. Not sure if I made my point clear since English is hard.

**Comment by Night-Pryanik** [comment]
@cainiaowu's argument is valid. It's similar to my PR replacing getting flashlight from the car headlight with proper headlight item.

**Pull request closed without merging**
