### PR TITLE
new design for the minefield

### PR DESCRIPTION
**Pull request by RogueYun**
A while ago there was a discussion about the pros and cons of the minefield and there was talk about phasing it out completely... So feeling no worry if I messed it up in a royal way I felt at liberty to try my hand at improving it. All I've really done is added some random barbed wire fence around it. I believe such barbed wire fences are usually around minefields in real life.

Here is an example of what it might look like:
http://s33.postimg.org/7pm1a1jkf/example_017.png

I beg your pardon if my code is not kosher... I just copy pasted/tweaked the code around it until I got it to work the way I wanted. I know very little about c++

### CODE REVIEW

**Comment by John-Candlebury** [comment]
To my understanding, the minefields were supposed to be artillery/air deployed. Hence their weird placement in the middle of roads and the like.

That might gave changed when the warning signs were added however.

**Comment by Mecares** [comment]
I considered the warning signs improvised and placed by survivors

**Comment by RogueYun** [comment]
Maybe we can come up with a better explanation?

Maybe the government deployed minefields to kill zombies and other mindless creatures that are attracted to explosions? And if so... they would probably label them so that they and their allies could understand that their was a minefield there... at least.. that would be my guess. Else, why use mines at all? Why not just use regular bombs or artillery?

It is sort of based on that assumption that I made changes to minefields to help make minefields more distinguishable.  

If people are worried that the changes I'm making will take the fun out of minefields I put it to you  that minefields are still super dangerous! If you are not paying attention and holding down the direction key you can walk right through the barbed wire and into the minefield. If you play with dynamic spawns zombies of all types will make their way to the sounds of the explosions.

My goal was to try to prevent immersion breaking/meta gaming activities. For example, walking on the edge of map tiles at night so that you can see the minefield signs as if each new character had a knowledge that there were minefields and how to detect them. I also wanted to protect players from deaths that they cannot control in a gamely manner. Accidentally wandering into a zombie horde and having to fight/sneak/run/parkour your way out of it is one thing. Accidentally stepping on a land mine that can instakill a character is another.

Now if you are worried that my code is awful and my design for the minefield is poor... then it probably is :D

**Comment by pisskop** [comment]
I always thought that dirt mounds were a good indication of a minefield.

Learned early to stay away from those.  The signs prevent over 95% of minefield confusion.  Why not try to add a second type of minefield?  a larger one with barbed wiring?  Like a json?

**Comment by mugling** [comment]
Closed as stalled. New mapgen code should go in JSON

**Pull request closed without merging**
