### PR TITLE
Make tempered and hardened steel repairable.

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary
Bugfixes "Make tempered and hardened steel repairable"

#### Purpose of change

Most items made out of tempered steel and hardened steel are unrepairable as they require chunk of tempered steel or chunk of hardened steel, which can't be acquired. 

#### Describe the solution

Add or change `repair_with` to medium steel or mild steel on tempered or hardened weapons and armor.

#### Describe alternatives you've considered

Really it should require re-hardening or re-tempering crafting recipes. 

#### Testing

Loads and works as intended.

### CODE REVIEW

**Comment by ampersand55** [comment]
fixes #67333

**Comment by TheShadowFerret** [comment]
>are unrepairable as they require chunk of tempered steel or chunk of hardened steel, which can't be acquired.

Why not just do this 🤔

**Comment by ampersand55** [comment]
> > are unrepairable as they require chunk of tempered steel or chunk of hardened steel, which can't be acquired.
> 
> Why not make them acquirable 🤔

I'm not metallurgist, but given how the hardening and tempering heat-treating processes work, it seems unrealistic to weld a small chunk of tempered steel onto an item to repair it as it would lose its tempered properties.

**Comment by Drew4484** [comment]
Tempered steel is repaired with medium carbon steel and the tempered welding kit. The game just doesn't display it correctly. Chunks and lumps of tempered steel are not crafted, you'd only get them if you destroyed a tempered item. The reasons behind this are some metalworking witchcraft that I don't want to write up here again.

**Review by Maleclypse — CHANGES_REQUESTED** [review]
@Drew4484 Let me know once this meets your plan.

**Comment by ampersand55** [comment]
> Tempered steel is repaired with medium carbon steel and the tempered welding kit. The game just doesn't display it correctly. Chunks and lumps of tempered steel are not crafted, you'd only get them if you destroyed a tempered item. The reasons behind this are some metalworking witchcraft that I don't want to write up here again.
> 
> I do agree that repair recipes would be more accurate but I haven't had the chance to write those up.

Ah, then I did this for nothing :( I should have checked if it was a display bug. 

I'm closing this.

**Pull request closed without merging**
