### PR TITLE
The Great Wiki Mentions Removal

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
None

#### Purpose of change

The wiki is a mess. It is unmaintained, the admins are super inactive and Kevin even said it is "cdda fan fiction". For these reasons it is apparently also not mentioned in the community-managed resources list.

#### Describe the solution

Remove all mentions.

### CODE REVIEW

**Comment by CoroNaut** [comment]
RIP wiki I guess. There's no reasonable alternatives for game mechanics either besides maybe the forums.

**Comment by TheShadowFerret** [comment]
>RIP wiki I guess. There's no reasonable alternatives for game mechanics either besides maybe the forums.

@TheMurderUnicorn's tutorial series? https://www.youtube.com/playlist?list=PLaY-Sp2A8N-BMFwypIHDJNaE5LfMYxxsI

**Comment by NetSysFire** [comment]
The issue runs deeper than that. First, the wiki is horribly outdated. Getting it all up to date is an incredible amount of work. Second, it is unmaintained. There are no people who are overlooking the edits done there and thus many things in the wiki are simply wrong or of horrible quality.

All these things have accumulated over years. I have seen the last admin activity on the wiki in 2020 and given a discussion highlighting all the problems in the development channel yesterday, I finally decided to do the work of removing the mentions.

There are some viable other tools though. For example the hitchhikers guide to the cataclysm, theres some others in https://github.com/CleverRaven/Cataclysm-DDA/blob/gh-pages/index.md#community-managed-resources

**Comment by mkrutov** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/wiki still mentions wiki btw @NetSysFire

**Comment by NetSysFire** [comment]
Thanks! Fixed.

**Pull request merged**
