### PR TITLE
Multistory apartment towers

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
 ```SUMMARY: Content "Added new z levels to apartments"```

#### Purpose of change
Apartments were named apartment towers, but they only had 1 floor. 

#### Describe the solution
Added new storeys, new furniture and terrains, nested chunks.
```Apartment_con_new``` has 6+1 floors.
```Apartment_mod_new``` has 5+1 floors.

#### Describe alternatives you've considered
Renaming it apartments, but this was a better solution.

#### Screenshots
apt_con_new_1
apt_con_new2
tech_roof

apt_mod_new_3
apt_mod_new_2
apt_mod_new_1

### CODE REVIEW

**Comment by curstwist** [comment]
Could add televison spawns. Livingroom look a little empty.

**Comment by LovamKicsiGazsii** [comment]
I'll add televisions, standing lamps and trash cans.

**Comment by Mecares** [comment]
You might want to spawn a small technical room for the elevator tech on the roof it needs to be one level above the top most floor an elevator reaches.

**Comment by LovamKicsiGazsii** [comment]
Added new furnitures to the living rooms, updated the screenshots. I haven't done a techinal room for the elevator (yet). I don't know what to use for that (maybe a broken generator/ heavy machinery and a computer?).

**Comment by Mecares** [comment]
Sounds good to me

**Comment by LovamKicsiGazsii** [comment]
That's a good idea. It could be a new nested chunk. I don't think it would cause an issue, we already have gardens in labs.

Also, I'll need to lint the palette.

**Comment by LovamKicsiGazsii** [comment]
How about this:
tech_room

**Pull request merged**
