### PR TITLE
Remove skill rust from game options

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

None

#### Purpose of change

Since skill rust was transformed into a useful and important gameplay mechanic in #50176, there is no good reason to keep it in the game debug options.

#### Describe the solution

- [x] Remove the "Skill rust" option from the options menu
- [x] Remove references to the `SKILL_RUST` option from code (do skill rust unconditionally)
- [ ] Playtest to make sure skill rust still works as intended

#### Describe alternatives you've considered

There's a migration section at the top of options.cpp that may need altering too. Not sure if it's worth trying to persist effect of the "off" or "capped" settings that some players may have configured.

#### Testing

Game compiles and loads. Options menu no longer includes "Skill rust".

Previously saved configuration with both "vanilla" and "off" setting for `SKILL_RUST` are overwritten with new config without any configuration for that option.

### CODE REVIEW

**Comment by Testudo-Cultu** [comment]
I agree that there shouldn't be an option to completely disable skill rust, but I think a lot of people would agree with me that the capped setting is more fun and less tedious. Capped skill rust is especially nice to have due to the current lack of advanced health care and computer practice recipes.

**Comment by PlutusPleion** [comment]
It seems there's already a lot of confusion regarding theoretical and practical skill levels for newer players. Forcing skill rust will just add further to the confusion.

I also don't see the benefit of removing choice for the player. What is wrong with letting people play with rust on, off or capped?

Does forcing you to re-craft items you probably aren't going to use add meaningful and rewarding gameplay for the player? If a high craft skill level is reached, it's likely the player already spent a lot of time getting there already crafting some useless stuff and disassembling.

The player has already "spent" effort reaching those levels, why emphasize the most tedious and un-fun part of getting there. Leaving the option there seems to be the best middle ground that let's each player customize how they play.

**Comment by PlutusPleion** [comment]
> What are you recrafting items you won't use for? 

I'm at a point where I don't need to craft much but if I have to constantly keep crafting to account for rust I will end up with a bunch of junk and wasted time/materials. 

> lost practical will return _very_ quickly. 
> The "penalty" is negligible as you get a bigger reward of increased XP. Since you don't lose anything

It is not very quick. And a lot of time you're using up ingredients that could be sparse or crafting recipes where you can't exactly disassemble to get it back.

I'd like to clarify that I'm not arguing for or against skill rust, just that the benefit of keeping the option is greater than choosing and forcing the player to play with it.

**Comment by HKMist** [comment]
As a returning player after almost a year, the new skill system work quite properly, although after a few long exploring run I just change skill rust on capped, it is true that catchup process of skill rust is very fast and easy but after some time it doesn't add much other than extra micromanagement. 
To be honest if keeping the option doesn't add extra cost on the game's maintain I think it is better left the option there, after all this is a zombie game with a remove zombie option for player's choose, why not keep more option if it don't hurt :P.

**Pull request closed without merging**
