### PR TITLE
Fixed "Relocating zombie corpses crash" (fixes #32943)

### LINKED ISSUE #32943: Relocating zombie corpses through advanced inventory causes segfault
As described in the title, using the [/] advanced inventory menu to relocate a pile of pulped zombie corpses away from a window tile causes a segfault for unclear reasons. The segfault is consistent in that it keeps happening repeatedly, but not always with the same corpse. Sometimes, the corpses must be moved repeatedly for the segfault to happen.

# Steps To Reproduce

1. Load attached save Riceville 
2. Use [/] menu to move zombie corpses off the broken window
3. Sometimes a segfault will happen
4. If segfault does not happen when all corpses are moved off the window tile, continue moving corpses around until it does.

# Expected behavior

Corpses are moved without any chance of a sudden segfault. 

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on  64-bit Windows 7 Pro SP1 
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    sees-player icon, +attitude [sees_player]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3468990/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3468991/debug.log)
[Riceville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3468993/Riceville.zip)

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
SUMMARY: Bugfixes "Relocating zombie corpses through advanced inventory causes segfault #32943"

#### Purpose of change
Fixes #32943

#### Describe the solution
Add a check in `get_active_items_in_radius`: only include the item if the reference to it is valid.

#### Describe alternatives you've considered
Check other reference (`item_ref`) uses. I see that sometimes they are being validated.

#### Additional context
I have noticed that when one of the corpses has been moved, it becomes active item somehow.

Also, looks like the "safe reference" is not always safe...

### CODE REVIEW

**Comment by AMurkin** [comment]
Code style:
```cpp
            if( elem.item_ref ) {
                result.emplace_back( map_cursor( pos ), elem.item_ref.get() );
            }
```

**Comment by ipcyborg** [comment]
>Wait. How is it says "no astyle regressions"?

Yes, I've done astyle before first commit, and it was fine.
Should be fixed now, thanks!

**Comment by ipcyborg** [comment]
EDIT: fixed *INDENT-OFF* -> *INDENT-ON*
I hope it is correct: leads to a lot of asyle changes in `map.cpp`.

**Comment by ZhilkinSerg** [comment]
Please rebase after #32972 is merged.

**Pull request merged**
