### PR TITLE
Tweaks for crowbar and makeshift crowbar

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
Balance "Tweaking of values of crowbar and makeshift crowbar"

#### Purpose of change
Split of #47572. For realistic values. Did some math for volume.

#### Additional context
https://www.amazon.de/Connex-COX664600-Nageleisen-sechskant-L%C3%A4nge/dp/B001BAWDP8/ref=sxin_10?ascsubtag=amzn1.osa.a97a059a-883d-43c6-80ed-0850dfce3426.A1PA6795UKMFR9.de_DE <- for the real crowbar

### CODE REVIEW

**Comment by Lamandus** [comment]
not sure why it failed.

**Comment by actual-nh** [comment]
> not sure why it failed.

Travis has the informative failure. (The others seem to have a problem with Kubernetes download?) iteminfo_test.cpp again, I regret to say.

**Comment by Lamandus** [comment]
@actual-nh you checked, right?

**Comment by actual-nh** [comment]
> @actual-nh you checked, right?

Oh, drat; I'm sorry, I don't remember things very well from when I just woke up. Looking at now.

**Comment by actual-nh** [comment]
First, all 4 pockets should be the same for the test_belt (it's only looking for one entry saying "pockets"). Second, the test code for total capacity needs to look for 4.8 kg instead of 4.0 kg (this is allowing for the other 3 pockets being adjusted).

**Comment by actual-nh** [comment]
Working on the test failure.

**Comment by actual-nh** [comment]
Humph. Same error. I am putting in an issue. In the test code, there is first a check to make sure a hammer can't fit into the test belt, which is succeeding. Then it's forcing a hammer in there, and checking whether it succeeded, and it did. Then it tries having it "overflow", and checks to make sure that it isn't there anymore - and there is where it the test is failing; there are still 5 things in there when the earlier test said you couldn't fit another hammer in.

**Comment by Lamandus** [comment]
> 
> 
> Humph. Same error. I am putting in an issue. In the test code, there is first a check to make sure a hammer can't fit into the test belt, which is succeeding. Then it's forcing a hammer in there, and checking whether it succeeded, and it did. Then it tries having it "overflow", and checks to make sure that it isn't there anymore - and there is where it the test is failing; there are still 5 things in there when the earlier test said you couldn't fit another hammer in.

what if we take another object which should fit in a lone pocket but not with the others as well?

**Comment by actual-nh** [comment]
> > Humph. Same error. I am putting in an issue. In the test code, there is first a check to make sure a hammer can't fit into the test belt, which is succeeding. Then it's forcing a hammer in there, and checking whether it succeeded, and it did. Then it tries having it "overflow", and checks to make sure that it isn't there anymore - and there is where it the test is failing; there are still 5 things in there when the earlier test said you couldn't fit another hammer in.
> 
> what if we take another object which should fit in a lone pocket but not with the others as well?

In other words, see if something other than a hammer does this?

**Comment by Lamandus** [comment]
> 
> 
> > > Humph. Same error. I am putting in an issue. In the test code, there is first a check to make sure a hammer can't fit into the test belt, which is succeeding. Then it's forcing a hammer in there, and checking whether it succeeded, and it did. Then it tries having it "overflow", and checks to make sure that it isn't there anymore - and there is where it the test is failing; there are still 5 things in there when the earlier test said you couldn't fit another hammer in.
> > 
> > 
> > what if we take another object which should fit in a lone pocket but not with the others as well?
> 
> In other words, see if something other than a hammer does this?

Correct. Something that is too heavy when added to something we got. A hammer has the weight of 550 g. So 2 of them are 1100 g. My guess is, that the test system doesn't check for volume but weight. What if we use another crowbar or similar heavy item trying to fit in there.

**Comment by actual-nh** [comment]
> > In other words, see if something other than a hammer does this?
> 
> Correct. Something that is too heavy when added to something we got. A hammer has the weight of 550 g. So 2 of them are 1100 g. My guess is, that the test system doesn't check for volume but weight. What if we use another crowbar or similar heavy item trying to fit in there.

I've been wondering about volume vs weight myself; good thinking! I'm about to go to bed after getting a couple of things done, but I will be interested in seeing the results in the morning...

**Comment by Lamandus** [comment]
> 
> 
> > > In other words, see if something other than a hammer does this?
> > 
> > 
> > Correct. Something that is too heavy when added to something we got. A hammer has the weight of 550 g. So 2 of them are 1100 g. My guess is, that the test system doesn't check for volume but weight. What if we use another crowbar or similar heavy item trying to fit in there.
> 
> I've been wondering about volume vs weight myself; good thinking! I'm about to go to bed after getting a couple of things done, but I will be interested in seeing the results in the morning...

looking good!

**Pull request merged**
