### PR TITLE
Consistent UPS charge consumption when crafting

### LINKED ISSUE #43054: UPS tools sometimes cause error unless inside inventory
# Describe the bug
UPS converted tools show up properly as available in the crafting menu, but unless you move them into your inventory, the error message "you no longer have a none and can't continue crafting" pops up. This is not consistent with all tools however.

# Steps To Reproduce
1. Install a UPS conversion mod on a tool like soldering iron or food processor.
2. Keep it outside your inventory but nearby, and keep a charged UPS inside your inventory
3. Try and craft a recipe that requires that tool
4. You'll see the crafting start but then stop approximately 3-5% into it with "you no longer have a none and can't continue crafting"
5. Put the required tool inside your inventory
6. You can now craft again.

# Expected behavior
I know that UPS behavior is a bit wonky nowadays after the battery overhaul, but it ideally should automatically connect nearby UPS and UPS-tools automatically. Sometimes it does (e.g. hotplates seem to work just fine), but the behavior is inconsistent.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5221-g315a4f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

### LINKED ISSUE #45330: UPS welder welding but not consuming charges (infinite battery)
# Describe the bug
Welder modified for UPS doesn't consume charges unless both are in inventory

# Steps To Reproduce

Setup
Modified Makeshift Welder to use UPS
Modified UPS (taken from disassembling electric jackhammer) to accept small storage batteries

Tests:
```
+ welder and ups in inventory - can use, Charges consumed
- Welder nearby and UPS in inventory - can use, no charges consumed
- Welder in inventory and UPS nearby - can use, no charges consumed
- welder and UPS both nearby - can use, no charges consumed
+ welder nearby and UPS far away - can't use, not enough charges
```

# Expected behavior

The algorithm appears to correctly identify when a UPS is nearby that has charges it *could* consume
I would expect it to consume those charges when used

# Screenshots
Ask if needed

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7424-gcbcf5fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Example save attached for easy testing
[Mont Clare.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5514714/Mont.Clare.zip)

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Bugfixes "Consistent UPS charge consumption when crafting"

#### Purpose of change

Fixes #45330
Fixes #43054

#### Describe the solution

Multiple problems had to be addressed to fix this bug.
- Tools used for crafting items could be only on the map or in inventory, but not both. Since UPS power and the tool could be in both locations, this was a main source of the problem. Fixed by allowing crafting tools to span the map and players inventory if needed.
- Some code was detecting items on the map while it was only consuming from inventory, causing inconsistencies. This has been fixed by allowing radius to force player inventory only.
- Power consumption of tools on the map were not accounting for UPS. This has been fixed.

#### Testing
Full test program: no problems.

Tested crafting with arc welders and UPS in all possible combinations on the map and in inventory. Power consumption is consistent and reliable.

Tested stopping of craft, moving tools, and resuming. In certain situations such as moving tools from inventory to the map it will give a warning message message of missing charges and stop, but will resume correctly with a prompt for tool selection if the craft is attempted again. Power consumption is correct however and is only a minor inconvenience in a rare circumstance. To eliminate the message would require - in my opinion - prompting the player about tool usage with every resumption of a craft. This way is less intrusive.

### CODE REVIEW

**Comment by Raikiri** [comment]
Is this related? https://github.com/CleverRaven/Cataclysm-DDA/issues/45018

**Comment by Raikiri** [comment]
I was playtesting these changes. Looks like it's significantly better than before, I can almost always use UPS reliably, but it still does not work with kiln and forge that have a UPS mod.

**Comment by RoyBerube** [comment]
@Raikiri Oh well, one more thing to add to the TODO pile. Those tools must be getting handled differently, or they would have been fixed along with the rest.

**Comment by Raikiri** [comment]
@RoyBerube actually after further testing it still happens to all tools. I can't give you a repro case, but I noticed that sometimes I start a craft using an integrated toolset CBM for soldering and then it says "You no longer have a none and can't continue crafting" when it runs out of charges even though I have a UPS'd soldering iron nearby. 

Also with forge and kiln I sometimes have to pick them up, drop them, pick up UPS, just shuffle them around for a bit in order to make them detect each other (?). Sorry I can't give you a more reliable repro, but looks like there's still edge cases left.

**Pull request merged**
