### PR TITLE
Add camera controls to driver seats in APCs

### LINKED ISSUE #13686: APC Vehicle Layout oddity.
For some reason, in the two seats in the APC, the vehicle control and the camera control at on two different seat.  This results in a situation that if you sit in the driver (left) seat, you can see a very narrow area ahead of you while if you sit in the other front seat, you can see in almost all direction (with very tiny blind spots).  I'm not sure if this is an error or but but it seems rather odd and doesn't quite make sense realistic wise (unless I am missing something).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27051152-apc-vehicle-layout-oddity?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by illi-kun**
Fixes #13686.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. Guess that will make things easier on the player, and won't require I make tanks consistent with mainline armored vehicles.

Either solution to the issue (adding a camera OR closing it with the acknowledge that it was intended) is fine with me.

**Comment by kevingranade** [comment]
I like chaosvolt's original rationale for this.  The only issue in my mind
is whether it's factual or not, does the driver of a modern APC have a
restricted field of view or not?  If they do, leave it as it is, if they
normally have all-around vision, make this change.

**Comment by chaosvolt** [comment]
Add that to the list of things I wish I could get more info on, concerning modern armored vehicles. @_@

**Comment by illi-kun** [comment]
OK, I will check it and provide you results.

**Comment by vache** [comment]
Googling "Armored Multi-Purpose Vehicle" and "apc driver seat" would seem to indicate that most APCs have very limited driver visibility directly ahead, but given the technological differences, I could see having a few MPDs which might include cameras for full visibility around vehicle.  See http://media.defenceindustrydaily.com/images/LAND_Pandur-II_Driver_Seat_lg.jpg for an example of a relatively modern design.

**Comment by kevingranade** [comment]
I don't see where you're getting all-around vision out of that picture, that's three fixed periscopes and a glass instrument panel.  Possibly better FoV than the APC in game, but sure as hell not 360 deg.

**Comment by kevingranade** [comment]
Unless someone has a good reason otherwise*, I'm going to revert this, as
far as I can tell the restricted FoV is normal for an APC.

*'future stuff' is not a good reason.

**Comment by Rivet-the-Zombie** [comment]
Works for me. I didn't realize this one was controversial.

**Comment by illi-kun** [comment]
Please do not revert this next couple hours - l'll check it and propose the solution

**Comment by illi-kun** [comment]
Modern APCs don't provide to its driver perfect Field of View (in real life), so we need to remove such cameras controls from driver's place if we want to see the current state of APCs in the game. The only argument (which is strong for me but not for Kevin) is "future" possibilities - if you can install cameras controls to commander / gunner place why you can't do the same for driver?
As compromise solution, we can increase the distinction between APCs & IFVs (defined as aapc in json): for APCs we can merge gunner & driver places to the single all-in-one commander place with cameras controls, and for IFVs we can remove cameras controls from driver's place (as it was initially).

**Comment by kevingranade** [comment]
Hey, I don't know why the gunner has a camera either, I'm just pushing back on an idea that basically boils down to "I want vehicles to be ready-to-go survivor vehicles instead of representative of real-world vehicles".
There has literally been no argument for why this change is a good idea, and as far as I can tell, there is none.

**Comment by illi-kun** [comment]
Removing cameras from gunner will make him completely blind and useless (and, BTW, a lot of photos of APCs show that turrets are equiped by some kind of optical devices).

Taking into account your words, I think it's better to simply revert current PR and keep #13686 closed with conclusion "intended behavior / nothing to fix".

**Comment by chaosvolt** [comment]
Hnng. In that case I'll likely want to tweak the tankmod vehicles by moving the driver's camera to the commander's seat, to restore consistency. =w=

**Comment by vache** [comment]
I find it hard to believe that it's reasonable for a modern minivan to have a camera showing the rear of the vehicle, but its not reasonable for the military in 2040 whatever to not want their APC drives to see anything more than a 20 degree wedge directly in front of them.  Full 360 degree vision maybe, maybe not, but at least some extra tactical awareness would make sense.  If they're still rolling around in equipment from the Vietnam war and earlier era, then fine, leave them with the tiny wedge.

I'm betting if the camera and electronics tech was there, the old school era APCs would have a more secured driver seat with cameras, because the main reason for having such a limited field was also that it presented more limited weak spots for attack.  If cameras were everywhere and there were no need for a direct physical sight line to the outside, then it would be that much more secure.

If game balance is the main factor, then limit where it spawns.  Place them next to the roadblocks with all the enemies people hate, or leave them crawling with soldier zombies.

**Comment by chaosvolt** [comment]
Ah, yet more glorious distractions. I still have a tileset update to work on, I need to sprite up the recent monster additions and the farming parts. >.>

**Comment by illi-kun** [comment]
@vache, I'm with you generally, but I would argue about one point: you need to keep windows for driver anyway, even with cameras around the vehicle. You need windows for satisfaction the failsafe condition -elsewise disabling the electronic system of APC (by EMP, if we're talking about sci-fi future) makes it completely blind.

**Pull request merged**
