### PR TITLE
mom: wield your crystals *today*

### LINKED ISSUE #70652: [MoM] Wielded matrix crystals don't seem to do anything
### Describe the bug

In the world I'm currently playing, I have matrix crystals for biokinesis, clairsentience, and teleportation. However, when I wield any of the crystals, none of the levels for any of the powers are adjusted as shown in #66641. To test if this was a mod compatibility problem or a problem with starting with MoM backgrounds rather than using the crystals for awakening, I made a new world with MoM as the only non-default mod, created a default survivor, spawned in 2 pyrokinesis crystals, awakened with one, and wielded the other. None of the spell levels were adjusted and none of the numbers in the description changed, with or without wielding the crystal.

### Attach save file

[Lunds-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13834373/Lunds-trimmed.tar.gz)

### Steps to reproduce

1. Make a survivor
2. Spawn in 2 non-black matrix crystals of the same color
3. [a]pply one
4. [w]ield the other
5. Check the spellcasting menu

### Expected behavior

Wielding a matrix crystal should give a +4 level adjustment to powers of the corresponding class.

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: eaa25f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
I somehow figured a fix for the level boost wielding a crystal of your school gives you

god please prefix your custom json math functions

fix: #70652

#### Describe the solution
thonk really hard for a couple of hours, fix it, take a shower and test - nice it works!

#### Testing
Screenshot_2024-03-06_20-45-29
Screenshot_2024-03-06_20-45-48

### CODE REVIEW

**Review by Standing-Storm — APPROVED** [review]

**Comment by Montimorency** [comment]
Wielding crystals boosts powers? Damn, what else am I missing. Does it also help with contemplation?

**Comment by Montimorency** [comment]
@Standing-Storm 

I've been loathe to ask you to look into the relationship of psionics with nausea effects, but they really are breathtakingly severe. Nausea typically lasts for a few hours - the game will lie that "you no longer feel nauseous", but all the consequences are still there - and there is a demonstrable 100% chance of vomiting for any action that increases satiety. 

But just now I was playing around with crystals on Nether 2 and I was struck with nausea for over 12 hours, including for most of my sleeptime. 

naus

I don't know if it's hardcoded in the base game or if it's a byproduct of how Nether and other factors interact with the base effect, it's just too much.

**Comment by Standing-Storm** [comment]
What do you mean by "playing around with crystals?" The effects from failed attunements do last an hour, and that's intended--did you stack up multiple levels of `"Headache"` (etc)?

**Comment by casswedson** [comment]
by the way, this is not the place for this talk

**Pull request merged**
