### PR TITLE
Linting blacklisted json files test

### PR DESCRIPTION
**Pull request by zombiethoughts**
SUMMARY: none

#### Purpose of change
Linting files in json_blacklist

#### Describe the solution

Linted the following files
data/json/itemgroups/vending_machines.json
data/json/items/fake.json
data/json/items/generic/ammolink.json
data/json/items/generic/string.json
data/json/items/grenades.json
data/json/items/gun/223.json
data/json/items/gun/22.json

### CODE REVIEW

**Comment by KorGgenT** [comment]
you need a summary line like ```SUMMARY: none```

**Comment by zombiethoughts** [comment]
Ah, forgot to update the summary and info when I updated json_blacklist, I'll do that and add some more files to the PR.

**Comment by KorGgenT** [comment]
image
just hit the ... and edit it there

**Comment by KorGgenT** [comment]
jenkins rebuild

**Comment by KorGgenT** [comment]
looks like ammolink.json didn't take

**Pull request merged**
