### PR TITLE
Arcana mod series 1

### PR DESCRIPTION
**Pull request by chaosvolt**
A tale of arcana awakened, an alchemist, an acolyte, and...um...a blood mage. Dangit, almost alliterative.

This is the first part of the arcana mod as can be found on the forums ( http://smf.cataclysmdda.com/index.php?topic=11013.0 ), broken up into parts to avoid PR bloat. Even then this'll be a hefty one, due to adding the foundation of the itemcrafting and the first 3 of 5 recipe books.

Arcana Skill:
- A new skill, which I'm surprised I got working. It's used as the primary crafting skill for magical items. Thanks to a PR by BevapDin, magic weapons can now use this skill.

The Essences:
- Regular essence drops from slaying several different sorts of anomalous creatures, the more otherworldly the better. Main use is for creating most enchanted items. Certain magical items are also fueled by this.
- Blood essence is drained from non-anomalous beings, using anomalous means. Main use is ammo for magical ranged weapons, and as a less efficient alternative to essence for crafting. Some magic weapons are fueled by this. Certain items will ONLY be able to use blood essence for crafting, and conversely some items will only allow using normal essence to craft them.

Monster Tweaks:
- A wide range of monsters have been edited to allow obtaining essence.

Potions:
- Black potion. Very potent painkiller, but with several side effects. What were expecting, for something so simple?
- White potion. Boosts strength a fair bit, and boosts speed a little, also with side effects.
- Yellow potion. Big speed booster, and shifts stats around. Still a few side effects, almost there...
- Red potion. Heals various injuries and features a milder return of the painkiller effect, which milder side effects. Remove a few of the weird ingredients, add some pearl ash, and what would you get? Go on, guess.

Magic Items:
- Offering Chalice. Used for a few recipes from Oaths to the Chalice, as you could surely guess. Go on, take a swig from it. I dare you.
- Silver Athame. Used for a few recipes in Sanguine Codex. Only a mere 3 butchering quality. Still sharp enough, so don't play around with it. Or do play with it, that's exactly what the authors of the Codex want you to do.
- Symbol of Judgement. Uses blood essence to fire bolts of lightning. Hmm. Lightning, fueled by life force, where have I heard that before...?
- Revenant Crown. Use it to gain temporary immunity to poison, in exchange for increased hunger gain. Since this includes immunity to food poisoning...
- Hellfire Stave. Finally added that fire weapon. Uses bursts of blood essence.
- Veinreaver. Remember that silly "bloodsplosion" idea mentioned previously?
- Thunder gauntlets. Can you say tazerpunch? Exists due to lack of decent lighting-themed items, when I've got multiple fiery explody items.

Books:
- Apprentice's Notes. Entry-level 0-to-1 skillbook, with no recipes. Implied to discuss magical concepts using religious metaphors.
- History of Alchemy. For crafting potions, and for getting from levels 0 to 3. A madman's interpretation of old alchemical texts, with results that would be profoundly useless without magical essence. You get a cookie if you notice the references to historical alchemical concepts, hidden underneath the stranger things the recipes involve.
- Oaths to the Chalice. Also a religious book. This is where we leave the realm of sanity behind and get into stuff that requires some arcana skill to understand, for skill levels 4-7. Allows crafting the offering chalice, recipes for sacrificing items to obtain essence, and a couple magic items . Also needed to extract blood essence from a used chalice.
- Sanguine Codex. Blood magic, for levels 3-6. Allows crafting the silver athame, and producing blood essence. Second option for extracting blood essence from a used chalice.

Misc:
- Meditate has been given an item_action definition due to the chalice being a religious item.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Um. Shit. @BevapDin messed something up in that PR that allegedly removed the issue of ranged weapons citing unexpected skills.

Tested with Windows tile build 3653, and the game crashed upon firing one of the ranged magic items.

**Comment by chaosvolt** [comment]
Jently appears to be stuck again. ;w;

**Comment by narc0tiq** [comment]
So it does. Let me give it a kick.

**Comment by narc0tiq** [comment]
Incidentally, I seem to recall that `chkjson` only looks at `data/json`, so mod content won't be tested. Perhaps it should. I'll make a PR for that.

**Comment by chaosvolt** [comment]
Huh, that's weird, but might explain why I've failed to notice mistakes in mod PRs before. In any case, thank you and sorry about that.

**Comment by narc0tiq** [comment]
Eh. If nobody tells me Jently isn't working, I'm not likely to notice.

Turns out making `chkjson` work on mods is irritatingly non-trivial and I don't really have the time or patience to poke at it properly right now.

**Comment by chaosvolt** [comment]
Ah, it's fine. ^^"

**Comment by chaosvolt** [comment]
Hmm. Is it normal for Jently to take this long to start checking, or is it simply refusing to check the PR due to chkjson not caring about mod content?

**Comment by narc0tiq** [comment]
The former.

**Comment by chaosvolt** [comment]
Ah, I see. Sorry about that. ^^"

**Comment by narc0tiq** [comment]
You don't need to apologize so much. If you have questions, go ahead and ask them; I'm pleased to tell you what I know whenever I have a moment. You're not disrupting my routine in the slightest. Everything is fine.

**Comment by chaosvolt** [comment]
Hmm. Add ice weapons to the list of things I wish was an option. o3o

**Comment by chaosvolt** [comment]
Ah, thank you for the merge. ^^

**Pull request merged**
