### PR TITLE
Routine i18n updates on 31 May 2021

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

### CODE REVIEW

**Comment by actual-nh** [comment]
@BrettDong: The dmgbuild step on the release build has a problem (bad dmgbuild version or something?).

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/what-happend-to-the-german-translation/26496/4

**Comment by I-am-Erk** [comment]
Did this accidentally remove a bunch of translations? I don't follow i18n much but it drops 25000 lines while only adding 8000, and we're getting reports of missing translations.

**Comment by BrettDong** [comment]
I did a full fresh download from Transifex in #49341 and it doesn’t seem to add a lot of translations back.

**Pull request merged**
