### PR TITLE
Converting Materials From Strings To Arrays

### PR DESCRIPTION
**Pull request by klorpa**
#### Summary

```SUMMARY: Bugfixes "Converts all material tags from strings to arrays."```

### CODE REVIEW

**Comment by esotericist** [comment]
What is the purpose of this change?

**Comment by Fris0uman** [comment]
Could you actually fill out te template for the PR description? That would make reviewing it much easier.

**Comment by ZhilkinSerg** [comment]
> 
> 
> What is the purpose of this change?

Enforcing JSON style consistency - use arrays for appropriate fields that support arrays.

**Comment by kevingranade** [comment]
This is something that needs to proceed in small chunks, a large PR is going to accumulate conflicts faster than we can review it.

**Pull request closed without merging**
