### PR TITLE
Shotgun Bandolier update

### PR DESCRIPTION
**Pull request by hyper2snyper**
```SUMMARY: Content "Adds a torso shotgun bandolier, updates the waist bandolier."```

#### Purpose of change
To make the shotgun bandolier more realistic/useful.

#### Describe the solution
Ive added a torso bandolier that can hold 50 rounds, however is more encumbering, takes up more space, and takes longer to draw from. Ive made the waist bandolier carry a few more shells and is quicker to draw from than the torso bandolier.

#### Describe alternatives you've considered
None really

#### Additional context
Shotgun-Bandolier-
41qIpimzzDL

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
This needs a recipe and spawn entries.

**Comment by hyper2snyper** [comment]
> This needs a recipe and spawn entries.

Oh duh, i completely forgot

**Comment by hyper2snyper** [comment]
How do i resolve a conflict?

**Comment by ZhilkinSerg** [comment]
> 
> 
> How do i resolve a conflict?

Don't worry I've resolved conflicts.

**Pull request merged**
