### PR TITLE
Clearer crafting search description

### LINKED ISSUE #26311: Improving discoverability for crafting search options
**The problem**
Here are the current crafting search options:
cata-crafting-search
Everyone I've seen use these options (myself and two or three YouTubers) gets confused.  We all want to search for result quality but end up searching for requirement quality instead.  Sometimes people figure it out after failing that first time, but sometimes they don't.

**Proposal**
I'd like to make two changes:
* Firstly, Move the `Special prefixes for results` section before the `Special prefixes for requirements` section.  It seems much more natural to be searching for results than requirements as the default case.
* Secondly, swap the `q` and `Q` shortcuts around for the two quality searches.  Again, this is because the one currently bound to `Q` is the one I think is wanted more often.

How do people feel about this?  The disadvantage of the second change is of course that it spoils existing players' muscle memory for these options, but I think it's worth it.

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Clearer crafting search help window"

#### Purpose of change
The current help window for crafting search is confusing to newcomers.  The special characters are presented in two ways, with the syntax away from the description.

Also, people generally try `q` when they want `Q`.

#### Describe the solution
New window:
cata-crafting-search-2
* Swap `q` and `Q`.
* Reorganise the search window so that examples are next to descriptions.
* Change colour scheme to highlight relevant words.
* Assemble the content from a table of small strings rather than one large one.  This should make it easier to add more in the future (translators will not have to retranslate the whole thing).

I've implemented my own "align strings in columns of the correct width" code here, which perhaps already exists elsewhere, but I couldn't find it.  `display_table` does something similar, but not the same.

Fixes #26311.

#### Describe alternatives you've considered
We could have a better description without swapping `q` and `Q`, but I really think they should be swapped.

#### Additional context
I noticed that the keys used for searches are hardcoded and cannot be changed in translation.  That may not be ideal, but that's not something I want to address here.

### CODE REVIEW

**Comment by jbytheway** [comment]
Build failures because master is broken right now.

**Comment by jbytheway** [comment]
Rebased on hopefully-fixed master.

**Comment by jbytheway** [comment]
> I don't know if it's related to your change, but I got this result:

Interesting.  I'm guessing that's on curses?  Didn't test curses.  Will look into it.

**Comment by jbytheway** [comment]
It was a classic mistake in string constructor argument ordering.  Unnoticed because the tiles build happens to render `'\x11'` as a space.  Good catch.  Should be fixed now.

**Comment by Pupsi-Mupsi** [comment]
Soon after the last **i18n-update** (commit: 3e5c5a1) i found part of the 'german-crafting-search-help-window' - great work btw - already _pretranslated_. which imho could be very misleading, because you can't really search for **h:ja** / **h:nein** or **m:ja** / **m:nein** - at least one does not get any results out of those searches. Maybe in this particular case **yes** or **no** shouldn't be translatable. Alternatively they could be, if they would lead to the same results.

Personally, i don't feel that either **hidden** nor **memorized** work very well as search-filters. Searching for **h:no** for example just shows what you are already seeing without even searching. **hidden** and **memorized** could be excellent toggles though. "Press h or H and you can toggle between hidden or none hidden recipes..."

german-crafting-search-help-window -> post-3e5c5a1: 
grafik

**Pull request merged**
