### PR TITLE
Boulders for flavor and rocks

### PR DESCRIPTION
**Pull request by jokermatt999**
Adds boulders spawning in fields. Flavor (that rocky New England terrain), as well as a larger source of rocks.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Those should probably not contain rock salt.
Or at least much, much less of it.

Note that a single drop of rock salt is a 14 volume boulder, not a fist-sized rock.

They should be rarer. 8.3 probability would make them a hazard for drivers.

3-7 rocks (volume 1 each) is very little for a boulder that blocks movement.

"SUPPORTS_ROOF" and "WALL" flags don't fit. The boulder would need to be huge to support roof. "WALL" means the object totally blocks smells, ie. is more or less airtight. Should probably be "REDUCES_SCENT", like a tree.

"t_rock_floor" has a roof over it. Pretty sure it's not the kind of the floor (and roof) you'd expect after destroying a boulder.
There should probably be a separate rock floor type that has no roof and isn't indoors.

It would be cool if there were furniture boulders that you could roll around with enough strength, but that would probably require more work than it's worth.

**Comment by jokermatt999** [comment]
Yeah, the supports roof was a hack to have it be jackhammerable without having add a separate flag. Will update, and maybe look into making it furniture instead if I'm adding a tag.

Rock salt is also taken directly from the rock terrain smashing, so I'll fix that too.

**Comment by chaosvolt** [comment]
Ah, nice. Soon we can have first anvil. Maybe. o3o

**Comment by Cat09** [comment]
it might be a good idea to add another size on top of this, New England rocks vary in size quite dramatically, and ones large enough to be a problem for most normal vehicles would be common (outside of active farmland)
If anyone has ever been up here they've likely seen the rock walls around fields... those rocks were not moved in for the wall, they were moved OUT from the field they surround.
and boulders range all the way up to THIS MONSTROSITY - the madison boulder (there are other areas with free standing rocks that are -just- the size of a house, and not a small factory)
madison boulder

**Comment by chaosvolt** [comment]
Hmm. That reminds me, I should get working on that stone anvil idea. Which size should I use, I wonder. owo

**Comment by Cat09** [comment]
I had a nice rock coming out of the ground by my house growing up, it was probably about the size and shape of a cow (as far as we ever saw anyway). we built a fire pit up against the side of it.
but yeah, most cars really wouldn't drive well in a field up here, unless it was cleared very well in the last 50 years or so, rocks push their way up through the soil over time.. even car size rocks will do this over a long period. this makes the saying that rocks are New England's best crop seem pretty true.

**Pull request merged**
