### PR TITLE
Implementation of UI for Bionics Slots System

### PR DESCRIPTION
**Pull request by illi-kun**
This PR implements basic UI functionality for drawing of occupied slots by selected bionic. A few snapshots are shown below:
demo-3_v2

demo-1_v2

demo-2_v2

demo_big

---

This PR is ready to merge but I estimate my work on slots system incomplete because I'm thinking about something like this:
alpha_preview

My current realization of enhanced UI presented above is very fragile and system dependent, so I've decided to start from something simpler (so this is why the current PR is here) and evolve it step-by-step.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
UI looks good, but I'd keep the debug trait as it is in master, unless you want to balance the bionics in this PR. The slots are rather unbalanced right now.

**Comment by illi-kun** [comment]
@Coolthulhu I definitely don't want to include the balancing in this PR, so yeah, if you don't change your mind I'll revert that part.

Just to state, I see nothing bad in enabling restrictions now just for gathering feedback (about poor balance) from end users; There are no penalties due to overflowing of cbm slots (because it can happens only due to rebalance), and number of occupied slots are not stored in the savefile anyway.

**Comment by Coolthulhu** [comment]
> I see nothing bad in enabling restrictions now just for gathering feedback (about poor balance) from end users

A dedicated balancing PR before mainlining the restrictions would be good, though.

**Comment by illi-kun** [comment]
OK, I'm going to remove this part of changes from current PR and instantly open [CR] PR for balancing.

**Comment by illi-kun** [comment]
Done (and renamed the PR for better representation of its content).

**Comment by Coolthulhu** [comment]
Would be cool if this menu also appeared when installing a new bionic, to show how will the bionic state look after it. There it could also highlight conflicts (slot limits).

**Pull request merged**
