### PR TITLE
Fix vehicle_turret test

### LINKED ISSUE #78539: Vehicle turret tests fail randomly
### Describe the bug

Vehicle turret tests fail randomly on PRs unrelated to the tested functionality, and, what's worse, does so in a non repeatable fashion.

### Attach save file

N/A, this is about the github tests failing randomly (attempting to reproduce it locally using the same seed failed, although that could potentially have been because some other tests failed due to local environment not having something preceding tests needed).

### Steps to reproduce

Trigger the test suite until the error sequence is encountered (one failure for every(?) possible turret mounted weapon.

### Expected behavior

No flaky tests.

### Screenshots

_No response_

### Versions and configuration

N/A. It's a github issue.

### Additional context

The failure is caused by an inability to spawn a test vehicle at the standard location, despite attempts by the test to clear everything out. Thus, the reason for the failure is unknown.

What's probably needed to locate the problem is some way to determine why the vehicle can't be spawned (unless someone can analytically identify something that isn't cleared properly). If it was possible to access the debug output from failed tests (and I haven't found a way to do so), it might be reasonable to add such an output to the vehicle spawning code on a failure, containing info specifying why the spawning failed.

If there's some state set on tests that can be picked up by error reports it might even be possible to only generate such a report on a test failure, and do so to the test log. If such a state is available, it might even be possible to do a bit of work to create the test report (such as scanning terrain, etc. to verify that it is actually the expected type).

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
(Hopefully) Fixes #78539

#### Describe the solution
Courtesy of #78540 it appears the issue is just it using the wrong z level
Attempts to prevent this issue from occurring in future by setting the z level of the map to 0 in clear_map(). I'm not aware what the performance cost of that is and it may want removing if the tests start taking noticeably longer on average

#### Testing
Ran the test suite locally with the same arguments as the CI run without anything obvious sticking out
`All tests passed (28669103 assertions in 1102 test cases)`

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Have you checked if any of the tests using clear_map() operates on other Z levels?
If they do, they really should set the Z level after calling clear_map(), but you never know.

vehicle_split_test: The tinymap is set to z level 0, so the change doesn't affect anything (but it's also harmless). However, I wouldn't trust no test cases won't call abs_sub somewhere in the call chain in any operation, so I wouldn't trust just setting vehicle Z levels to zero (but if clear_map() is called for all the changed tests we know from that call it actually is zero).

It looks like a good change to ensure nothing is broken on the vehicle.

**Comment by Procyonae** [comment]
> Have you checked if any of the tests using clear_map() operates on other Z levels?

No I were expecting to get several test fails and have to add an extra function for not changing the z level but that doesn't seem to be a problem unless the CI finds something my local test run didn't (while it was shorter than I remember I don't really feel like repeatedly running it locally)

> vehicle_split_test: The tinymap is set to z level 0, so the change doesn't affect anything

Yeh I mainly just changed it bc it's pretty silly it calling it at all when it has to be using 0

**Comment by PatrikLundell** [comment]
Are tests run in a deterministic order, or are they dumped into some damnable map with a "random" hash function?

I suspect the latter being the cause of why this test only fails sometimes. However, if the full test suite has been run without any test falling over (due to Z levels) then clear_map() calls shouldn't cause trouble.

**Comment by Procyonae** [comment]
Checked on the discord and we think it's deterministic per platform https://catch2-temp.readthedocs.io/en/latest/command-line.html#decl, I'm not entirely sure why this isn't failing 100% of the time tho, maybe GENERATE https://github.com/catchorg/Catch2/blob/devel/docs/generators.md runs aren't in a deterministic order or something

**Comment by RenechCDDA** [comment]
I can confirm that the default is declared order (relative to the translation unit). #78570 should hopefully change it to be easier to work with

**Comment by Procyonae** [comment]
That's not a fun test fail, I think it's doing check_monster_behavior_tree_locust but the plant furnitures need an item sealed in them and that one doesn't have one bc of the way it's placed so it tries to catchup and grow when the map is (re)loaded and flips out

**Pull request merged**
