### PR TITLE
upgrade reversible recipe property

### LINKED ISSUE #36841: Taking stuff apart
**Is your feature request related to a problem? Please describe.**  
Taking stuff apart takes significantly less time than putting it together (even back together, ask any kid if you don't remember). But maintaining thousands of dedicated uncraft recipes reflecting that would be inefficient to say the least.

I'm getting a feeling I haven't elucidated myself properly here, so to reiterate - sans perhaps welded contraptions (unless using 'angular' grinder), _taking things apart, in the real word, is almost always significantly faster than putting them together, hence so it should in game_.

**Describe the solution you'd like**  
Allow `reversible` property to also take time value that would translate directly into auto-generated uncraft recipes.

**Describe alternatives you've considered**  
Have default uncraft time initialized to half of craft time, unless electronics is main skill then it becomes third of craft time - that is what I've been running locally for a while (on top of the above, to quickly deal with exceptions), to save myself effort of updating existing recipes.

**Additional context** 
This could substantially reduce amount of existing uncraft recipes.

NB. This isn't as much a request as proposal, I could have either solution up as PR's in minutes, just looking for input.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Infrastructure "allow reversible to accept time duration"```

#### Purpose of change
Making new `uncraft` recipes and hassling with json formatting just to adjust disassemble time is rather inefficient way spending ones time - which I reckon is the main reason why almost everything defaults to craft time and `uncraft` recipes are barely touched unless absolutely required.

Closes #36841

#### Describe the solution
allow reversible to accept type `time_duration` and assign it to auto-generated uncraft recipe time
add few examples

#### Describe alternatives you've considered
Also provide default values based on main skill used

#### Testing
Observe mp3 and portable_game disassemble time, note that they don't have dedicated `uncraft` recipes.

### CODE REVIEW

**Comment by AMurkin** [comment]
I don't think that mixing value types is the right thing to do, and it should be avoided.

**Comment by ZhilkinSerg** [comment]
Better introduce a new field `uncraft_time` to avoid confusion.

**Comment by 1n17** [comment]
That was my initial approach, but once I ran this for a while I realized that it is unnecessary to add dedicated json property when the parser needs to resolve any latent typing anyway due to nature of language, and that having both types in single value is more efficient and less error prone to update/maintain.

**Comment by kevingranade** [comment]
This lacks clarity, another field is a small price to pay for that, or alternately add a new key with a mandatory time string.

**Comment by kevingranade** [comment]
This has been sitting with "must-have" feedback for two months, feel free to reopen with those points addressed.

**Pull request closed without merging**
