### PR TITLE
Remove y/n prompts for save quitting and quitting from the main menu

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
These prompts don't achieve anything

#### Describe the solution
Just removes them, leaves the quit without saving (eg on Alt-F4) warning bc losing progress unintentionally as a player would suck

#### Describe alternatives you've considered
Was originally adding a debug option so contributors could turn all three prompts off

### CODE REVIEW

**Comment by Brambor** [comment]
It is currently here
image

I would move it here
image

Because that is where I look for it.

Also, rename to "Query on ..."

**Comment by Brambor** [comment]
Unfortunately doesn't fix my issue:
1. open crafting GUI (can open filter in it too)
2. alt + F4 OR "cross" to quit
3. Observe: the game still runs
4. close crafting GUI
5. The game quits

**Comment by Procyonae** [comment]
> I would move it here

This isn't exactly an annoying feature unless you're a contributor imo which is why I've stuck it in debug options, it does kind of fit with those other "Query on" ones tho so ig I will

> Unfortunately doesn't fix my issue

I mean I weren't aiming to fix any imgui window nonsense

**Comment by Procyonae** [comment]
Wait crafting GUI isn't imgui *facepalms*
I don't have that issue it shows the prompt and closes normally for me on today's expimage

**Comment by Brambor** [comment]
You are right. It has to be the filter in the crafting GUI. That is not ImGui either AFAIK.

image

**Comment by Procyonae** [comment]
Ye idk I think that's probably a string_editor_window but idk why it would delay the prompt until after you close the entire crafting GUI, pretty weird

**Comment by kevingranade** [comment]
Instead of an option can you do "really quit? Yes/No/Stop Asking"

**Comment by Brambor** [comment]
> Instead of an option can you do "really quit? Yes/No/Stop Asking"

If this makes it not revertable in options, I disagree.

**Comment by Brambor** [comment]
[On Discord](https://discord.com/channels/598523535169945603/642349261320880128/1314777612832477204) I was recommended SuperF4 (for Windows). Works amazing! Just press ctrl+alt+F4 to SIGKILL (I presume).

**Comment by kevingranade** [comment]
> Why? Then I have to give it it's own save load handling to store it somewhere even if you're Alt-F4ing.

Because were carrying around too many options in the options menu.

**Comment by Brambor** [comment]
> > Why? Then I have to give it it's own save load handling to store it somewhere even if you're Alt-F4ing.
> 
> Because were carrying around too many options in the options menu.

I think it is nice to have a section of options dedicated to "Query on". If the issue is it is not manageable, make it a separate section. Would that make it manageable?

**Comment by db48x** [comment]
Every new configuration option we add makes the maintenance and testing burden higher. In principle it doubles it, because you have to test everything with the option turned on and again with it off, though in practice it’s not quite that bad. I would recommend against adding this option at all; either prompt or don’t prompt. Don’t make it configurable.

**Pull request merged**
