### PR TITLE
[CR]Mission code refactor

### PR DESCRIPTION
**Pull request by Coolthulhu**
Mission code is atrocious, it would be the best to just remove it all and reimplement it from scratch.

Still, I did the wrong thing and cleaned it up instead.

The PR is huge, but most of it is just regex operations to change macros into jsons.
The code quality (and "PR quality") isn't very good, but:
- Mission code is horrible. "Not good" is better than horrible.
- Mission code is broken in multiple ways. From missing dialogue, through missing missions (the book one, at least), to totally unimplemented missions (reach safety).
- This PR has to be huge because hardcoded mission initialization function is huge. Maintaining two versions of mission loading (hardcoded init and json loading) would lead to bugs.

Actual code changes are easily reviewable, since there aren't many of them.

---

Changes:
- Moved mission definitions to a json. This accounts for a giant chunk of this PR.
- Mission type id becomes a `string_id`
- Added migration code from old enum typed missions to new string id ones. Another giant chunk.
- Mission functions (`place`, `start`, `end`, `fail`) become `std::function`s

---

To keep the PR size minimal (yes, this change can't really be much smaller), I won't change the following here:
- Dialogue "code" is another giant block, this time of `if`s and `else`s. More than 2000 lines of horrible "code". Thankfully most of it can be parsed by regexes.
- "Find book" mission is still missing an id

### CODE REVIEW

**Comment by mugling** [comment]
Can you publish the regex and ensure this proceeds as one operation per commit?

**Comment by Coolthulhu** [comment]
> Can you publish the regex and ensure this proceeds as one operation per commit?

I won't be able to do it with just one regex. Mission dialogue code has some popups, wrapped lines, one or two string formats and one `rng` switch. It will need manual changes too.

**Comment by Coolthulhu** [comment]
I think I've found the cause of the
> Mission x wasn't found in the active missions

bug, that also seems to be the same bug as being unable to complete some missions.

I could fix it here or leave that for the next PR.

**Comment by mugling** [comment]
The old code is very uunpleasant. This is a definitive improvement. Bugfix in a separate PR so it's clearer to see the changes.

**Comment by mugling** [comment]
I ran it through the JSON linter - the following fields are unused:

* mission_definition:item
* mission_definition:count
* mission_definition:destination
* mission_definition:followup

The latter two could wait but the first two result in all missions to fetch items being an automatic success

**Comment by mugling** [comment]
I'm going to run this through the linter and merge it. It's not perfect but its much better than what we currently have.

One related issue (but not a regression here) is that the dialog options on mission completion are often repeated (especially the no payment required option).

**Comment by mugling** [comment]
@Coolthulhu can you merge #17957 first as otherwise it's going to conflict when I add your new JSON data to `json_whitelist`

**Comment by Coolthulhu** [comment]
> One related issue (but not a regression here) is that the dialog options on mission completion are often repeated (especially the no payment required option).

Yes, the dialogue code is horribly un-generic and hardcoded. Needs jsonization.

> @Coolthulhu can you merge #17957 first as otherwise it's going to conflict when I add your new JSON data to json_whitelist

Can you add it to whitelist in a separate PR? Can be even based on #17957 branch.

**Comment by mugling** [comment]
> Can you add it to whitelist in a separate PR? Can be even based on #17957 branch.

Enforcing linting found four bugs in this PR and having written a ruleset for it I want to merge with that check enabled. I definitely don't want to add it to #17957 as that's unrelated and I don't want to hold up this PR unnecessarily. There are a number of other files I want to add in a separate branch to `json_whitelist` and as that file is nearly empty almost all new entries are merge conflicts. As #17957 can be verified in a single command merging that first, then this, then submitting further PR's would seem to be the logical order.

**Pull request merged**
