### PR TITLE
Applying FRAGILE_MELEE to glass items

### PR DESCRIPTION
**Pull request by ItsJustAlexC**
Due to recent discussion on FRAGILE_MELEE PRs, if we are to add this tag to some weapons, for consistency we should also add them to items that make sense.

For example, if we were to use a glass bottle for a melee weapon (as inefficient as that is) we would expect it to break pretty fast.  Currently, all glass containers don't seem to follow this consistency. This attempts to fix it. Feedback is highly welcomed, as I plan on tweaking item durability

### CODE REVIEW

**Comment by Lorith** [comment]
You forgot to add a comma to each line with qualities before the line  you added with the flag.

**Comment by 0be1isk** [comment]
@Lorith yea I noticed the moment I PRed it, quick fix

**Comment by Firestorm01X2** [comment]
Wait. For solid glass items game should calculate fragility without flag. Maybe it is better to modify stats of the glass itself.

**Comment by 0be1isk** [comment]
Closing because Firestorm is correct.

**Pull request closed without merging**
