### PR TITLE
Added PARTIAL_DEAF to powered armor [RDY]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
~~And RM13 combat armor.~~ Powered armor should have some kind of hearing protection embedded in it.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Unless something's changed, RM13 armor already provides full hearing/vision protection.

**Comment by BorkBorkGoesTheCode** [comment]
Is it hardcoded?

**Comment by Rivet-the-Zombie** [comment]
[Affirmative.](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L1844)

**Comment by BorkBorkGoesTheCode** [comment]
Rebased out.

**Comment by Mecares** [comment]
Good Idea, i wish someone would add something like a "gun_stabilization" flag to the game allowing Power Armor wearing survivors to wield weapons like the Minigun unmounted.

**Comment by BorkBorkGoesTheCode** [comment]
Ready.

**Pull request merged**
