### PR TITLE
Mapgen readability improvements

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary
Content "Updates bunker shops, gas station bunkers, cemeteries"

#### Purpose of change

I've been editing mapgen files for over 3 years now, but I've always struggled to understand codes like these:
read
The problem (for me) is that these files use seemingly very similar symbols and almost no empty spaces, so unless you skim through every line meticulously, you're going to have a hard time visualizing the location.  The biggest culprits of this are the bunker shops, gas station bunkers, and woodworking stores. 

Another smaller issue is when maps aren't merged.  Personally, I find editing maps easier when a single location isn't divided into multiple 24x24 chunks, because then you don't have to worry about OM connections, or having to create separate furniture and terrain arrays for each tile.  There are lots of examples of this, but I decided to pick the cemeteries for this PR, because they are missing a roof, and don't use regional terrain.

#### Describe the solution

I've tinkered around with the symbols to make the maps easier to read.  I also merged maps and files in some cases.

As per usual, I also did some minor edits to the affected locations:
* **Bunker shop:** palettized ground floor, defined `predecessor_mapgen`, replaced legacy console terrain with furniture version, removed spare guest room.
* **Cemetery (2x1):** added a roof, replaced terrain with regional counterparts, and removed nulls.
* **Cemetery (2x2):** added a roof, replaced terrain with regional counterparts, and landscaping changes.
* **Gas station bunker:** added a roof, replaced terrain with regional counterparts, added cash registers, increased loot, and added `SUS` item groups.
* **Woodworking store:** replaced terrain with regional counterparts, added cash registers, removed infinite water source, increased loot, and added `SUS` item groups.

#### Describe alternatives you've considered

None.

#### Testing

Debug-spawned a bunker shop, a gas station bunker, a 2x1, and a 2x2 cemetery.  Their roofs aren't mismatched, I couldn't find any mapgen issues, zombies, vehicles, and items spawn without issues.

I also loaded a world with No Hope installed, and it didn't cause any errors.

#### Additional context

<details>

  <summary>Screenshots:</summary>

**Bunker shop:**
kép
kép

**Cemetery (2x1):**
kép
kép

**Cemetery (2x2):**
kép
kép

**Gas station bunker:**
kép
kép
kép
kép

**Woodworking store:**
kép
kép

</details>

### CODE REVIEW

**Comment by Maleclypse** [comment]
There are some features that aren't supported well on merged maps, I believe traps are one of them but as long as none of your maps are using the place traps function or one of the others that I can't remember and may have been fixed it should be fine.

**Comment by GuardianDll** [comment]
If you have some advices how to make mapgen better, i think write them to mapmaking guide would be good

**Comment by LovamKicsiGazsii** [comment]
> If you have some advices how to make mapgen better, i think write them to mapmaking guide would be good

Most of what I'm doing ( i.e. adding roofs and regional terrain. palettizing, merging maps ) is already written down in `JSON_ROOF_MAPGEN.md`, `Guide_for_beginning_mapgen.md` and `Guide_for_intermediate_mapgen.md`.  Thankfully, newer buildings seem to follow these guidelines.

**Comment by toweroglass** [comment]
I have literally never seen the shop bunker or gas station bunker.....

**Pull request merged**
