### PR TITLE
avoid using dry vegetables for veggy pie

### PR DESCRIPTION
**Pull request by l29ah**
as they don't spoil unlike other candidates

### CODE REVIEW

**Comment by Cyrano7** [comment]
All this does is reorder how the recipe ingredients are displayed. It doesn't remove anything.

**Comment by anontahoe** [comment]
if the ingredient selection menu orders items the way they are ordered in the recipe then this PR makes sense. i would have kept it above wild herbs though.

**Comment by l29ah** [comment]
On Tue, Oct 25, 2016 at 05:06:55AM -0700, anontahoe wrote:
> if the ingredient selection menu orders items the way they are ordered in the recipe then this PR makes sense. i would have kept it above wild herbs though.

Yes, that was my intention.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Cyrano7** [comment]
@anontahoe It doesn't make sense as you can choose what you put in it anyways.

**Comment by l29ah** [comment]
On Tue, Oct 25, 2016 at 01:25:40PM -0700, Cyrano7 wrote:
> @anontahoe It doesn't make sense as you can choose what you put in it anyways.

http://www.java2s.com/Code/PythonImages/OKcanceldialogbox.PNG
It doesn't make sense to set what button is the default one as you can choose what you press anyways.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Cyrano7** [comment]
The irradiated versions of all those ingredients don't spoil either you know. It looks better in the crafting menu to keep them bunched up with similar ingredients I think. Anyways there are 332 different recipes in this file alone. Manually changing the order ingredients are displayed is maybe not the best way to go at this issue.

**Comment by mugling** [comment]
Agree with @Cyrano7 there is no obvious rationale for this change

**Pull request closed without merging**
