### PR TITLE
Battery charging appliances

### PR DESCRIPTION
**Pull request by mx-moonling**
#### Summary
Content "Adds new battery charger and recharging station appliances to allow charging batteries in a static base."

#### Purpose of change
There are currently no appliances that allow you to charge batteries. This commit adds the functionality to the appliance system.
The box battery charger is slow, but is easily crafted from materials found in any house.
The trunk recharging station requires slightly rarer items, but is still easy to craft and install.

#### Describe the solution
The appliances combines the functionality of three vehicle parts in order to make a working charging station.
- a battery
- a storage space
- a charger

Pull request #50420 mentions that charging stations need the intermediary of a battery in order to function. I added the functionality to the item versions, which was carried over to the appliance.

#### Describe alternatives you've considered
Finding someone to rewrite the RECHARGE flag code in order to remove the need for an integrated battery. 

#### Testing
Created new world with minimal mods. 
Tested crafting both appliances as objects.
Tested placing both appliances, connected to solar panels.
Created a vehicle with a battery charger and charging station.
Debugged in an electric chainsaw to order to quickly empty some batteries.
Tested all the recharging devices to check that the charging speed was as expected, and that the vehicle & appliance charging speed corresponded.
Smashed both appliances to make sure they created the correct debris.
Took down both appliances to make sure they dropped the correct items.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Maybe don't mention trunk in the name since this is not a vehicle part.

**Comment by mx-moonling** [comment]
I added trunk to the name because it copies the functionality of the vehicle trunk in order to have a storage space, and because it can also defined as a large rigid piece of luggage, which fits. What name would you recommend instead? I want it also to be distinguished from the basic recharging station.

**Comment by Fris0uman** [comment]
Could call them recharging station and large recharging station

**Comment by mx-moonling** [comment]
That could be even more confusing in my opinion. The recharging station is faster than the battery charger, and a large recharging station could be construed as tier 3. I spent a while thinking on the issue at the beginning, and I think trunk is useful as a term because it tells the player the size of the storage in the appliance.

**Comment by esotericist** [comment]
maybe 'just use luggage' instead of 'trunk'? not everyone who is english speaking recognizes 'trunk' as 'suitcase-like-object-but-bigger'

**Comment by mx-moonling** [comment]
Thanks for all the advice! I decided that foot locker would probably be the best term, since it is similar to a normal foot locker (which is furniture, and not a vehicle part, which was the concern) with charging capacities.

**Pull request merged**
