### PR TITLE
Consolidate overmap vision bonuses

### PR DESCRIPTION
**Pull request by thquinn**
#### Summary
```SUMMARY: Balance "Consolidate overmap vision bonuses"```

#### Purpose of change
I wanted to standardize the interaction between additive and multiplicative bonuses to overmap vision.

#### Describe the solution
* I got rid of the bonus from ```trait_BIRD_EYE``` since it already increases overmap vision by increasing PER, and because its description specifically mentions seeing enemies better and doesn't mention the overmap like the other bonus sources do.
* I changed the base range from 10 to 6, since the calculation was immediately subtracting 4 from it anyway.
* Binoculars now actually double overmap vision, as their item description claims. Affects other items with the ```ZOOM``` tag.
* Topographagnosia now interacts with other bonuses instead of completely overriding them.

#### Describe alternatives you've considered
I still haven't figured out how diminishing returns from atmospheric conditions and the horizon should be incorporated.

### CODE REVIEW

**Comment by thquinn** [comment]
I also snuck in a refactor from @codemime on #29242.

**Comment by Photoloss** [comment]
> I got rid of the bonus from trait_BIRD_EYE since it already increases overmap vision by increasing PER, and because its description specifically mentions seeing enemies better and doesn't mention the overmap like the other bonus sources do.

Bird mutants don't get the `Scout` trait and 4PER only grants 2 overmap vision instead of the previous 7 total, that feels a little excessive and unfitting as birds of prey *do* have excellent, definitely superhuman in some contexts, vision. I also wouldn't rely on mutation descriptions as they tend to be quite inaccurate at times. I'm not sure whether `Avian Eyes` conflicts with the regular perception traits (they both develop from basic `Perceptive`), if it does this is an undue nerf but if the two can be stacked a more elegant solution would be to simply add `Scout` to the Bird line.

Depending on how exactly they work (and, realistically speaking, the PC's knowledge of optics) it *might* be possible to partially stack the CBM with regular binoculars. Since this would be a pretty awkward experience and likely require additional retina/nerve enhancements it might be a good idea to append the CBM description explicitly saying they obsolete binoculars or render you unable to benefit from them.

Since the `UNAWARE` trait explicitly namedrops Topographagnosia and references brain damage its effects should be separate from front-end optics. Thus it would be justified to make it stack *multiplicatively* which, if tuned to the same 25% baseline, would result in an effective modifier of 0.5 total instead of 1.25 if you have optics (i.e. **half** the standard sight range instead of 25% extra)

> I still haven't figured out how diminishing returns from atmospheric conditions and the horizon should be incorporated.

The horizon should be far enough to not matter much. Haze/dust, hills or trees should obstruct you far earlier. As for weather:

- Light follows the inverse square law so if you want the same brightness at the observer position the viable range shrinks with the square **root** of the brightness modifier (i.e. half sunlight due to clouds -> `sight /= sqrt(2)` ). This obviously does not account for spectral shifts (different absorption of different colours), logarithmic scaling in our conscious impressions and all the ways human eyes can try and adapt. Hopefully the game already has base brightness values defined for *local* vision scaling.
- Strong sunlight *should* cripple your sight towards the sun if you lack glare protection and extend it (a fair bit less) looking away. Since the current system cannot handle anisotropy just apply an arbitrary multiplier **if** the player lacks glare protection, this one I would stack additively with binoculars/telescopes as their reduced field of view also reduces glare but does not fully protect from reflections ("snow blindness")
- Physical occlusion from rain/snow actually scales *exponentially* if you model the rain as a homogeneous mass of identical spheres: `<fraction of object still visible> = exp( - <number density of droplets> * <cross-section of single droplet> * <distance to object> )`. Which exact fraction can be considered "acceptable" for overmap visibility remains open but a very simple conclusion is that to keep that fraction constant between different levels of rainfall the allowed distance scales as the linear inverse of number density times droplet cross-section (basically radius/diameter squared). Maybe @davidpwbrown already has some data handy from other recent work on weather.
- Snow could incur an additional penalty due to covering landmarks and reducing variations in colour. I don't have a simple model for this one.

**Comment by thquinn** [comment]
@Photoloss Thanks for the thoughtful feedback!

> Bird mutants don't get the ```Scout``` trait and 4PER only grants 2 overmap vision instead of the previous 7 total, that feels a little excessive and unfitting as birds of prey do have excellent, definitely superhuman in some contexts, vision.

Added Scout to the Bird line. I do think that's the most elegant solution: it seems janky to have parallel mutations where one only increases sight range, and the other increases PER and sight range. Let me know if there's anything else I need to do to add it properly. I haven't changed mutation lines before.

> Depending on how exactly they work (and, realistically speaking, the PC's knowledge of optics) it might be possible to partially stack the CBM with regular binoculars.

I feel like this opens up questions about holding up rifle scopes to the end of telescopes, multiple pairs of binoculars, etc. Those scenarios are sillier than combining in-eye optics with other optics, but it's hard for me to come up with a clear justification why one should work and not the other.

> Since the ```UNAWARE``` trait explicitly namedrops Topographagnosia and references brain damage its effects should be separate from front-end optics. Thus it would be justified to make it stack *multiplicatively*...

I've put it with the other additive bonuses, giving it a similar interaction with multiplicative effects. It actually makes more sense for it to be there anyway, as its description "incapable of recognizing landmarks and orienting yourself in your surroundings" seems more like the direct opposite of Scout's "excellent navigator and your ability to spot distant landmarks is unmatched" (and of course, one cancels the other, suggesting that they affect the same part of the brain). Of course, we now have a multiplier that only gets changed once, but it could be helpful to have as a guideline in the future in case there come to be additional multipliers. We would probably want multipliers to stack additively in this way (+100% + +100% = +200%) rather than multiplicatively to +300% since that could quickly get out of control.

> The horizon should be far enough to not matter much.

Depends on height, of course, but at human height it looks like it's about 3 miles. I'm not totally sure on the scale of overmap tiles, but I can imagine a future where you could stack enough bonuses to reach that.

> Haze/dust, hills or trees should obstruct you far earlier.

Terrain alright has a sight cost, so we're good on that. I think I'll take a shot at atmospheric conditions in a future PR.

**Comment by Photoloss** [comment]
> Let me know if there's anything else I need to do to add it properly. I haven't changed mutation lines before.

That should work, you *might* need to split that off into a separate PR if anything else comes up though. Based on a quick test in the debug menu I was able to stack ´Avian Eyes` and `Insanely Perceptive` so the former should still be strong enough. I don't have a legit Bird mutant on hand though so if you do please test that.

> I feel like this opens up questions about holding up rifle scopes to the end of telescopes, multiple pairs of binoculars, etc. Those scenarios are sillier than combining in-eye optics with other optics, but it's hard for me to come up with a clear justification why one should work and not the other.

Go with the "rendered obsolete" version then:

`Much of the material in your inner eye has been surgically removed and replaced with an array of high-powered, auto-focusing lenses.  They function as integrated binoculars letting you see much farther than before, and any vision problems you might have had are now gone.`

> seems more like the direct opposite of Scout

A good option (and much simpler) *if* Scout's current status is considered acceptable.

> We would probably want multipliers to stack additively in this way (+100% + +100% = +200%) rather than multiplicatively to +300% since that could quickly get out of control.

Reducing the number of multipliers definitely sounds like a good idea overall. When it comes to penalties (like weather) you **want** to multiply them though so you don't hit 0 or less in the final result.

> Depends on height, of course, but at human height it looks like it's about 3 miles. I'm not totally sure on the scale of overmap tiles, but I can imagine a future where you could stack enough bonuses to reach that.

Tiles have no defined scale. If balance necessitates it we can just slap on an arbitrary cap but I doubt we'd get enough bonuses *without* also negating the horizon issue (read: building a giant watchtower)

> I think I'll take a shot at atmospheric conditions in a future PR. You've given me a good starting point.

Yes, definitely future PR. I can help with the math and physics but not with local conditions in New England.

**Comment by thquinn** [comment]
> I don't have a legit Bird mutant on hand though so if you do please test that.

I don't, but I tested as best I could figure out, and it seemed to work.

> Go with the "rendered obsolete" version then

Good idea, done.

**Pull request merged**
