### PR TITLE
Add MM-1 launcher

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add MM-1 launcher"

#### Purpose of change
Adding more uncommon guns.

#### Describe the solution
Add MM-1 grenade launcher; similar to Milkor MGL, but with doubled ammunition capacity.

#### Describe alternatives you've considered
Making it more common than it currently is.

#### Testing
Launched the game, made sure that no errors happen.

#### Additional context
None.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
>The known operators of the MM-1 reportedly include Brazil, Egypt, El Salvador, South Africa, and the United States. In US service, it was adopted only for special forces use, and it is unclear if it was ever used in combat by US forces. How the MM-1 was acquired by South Africa (during the Apartheid Era, during which there was a strict arms embargo on that nation) has never been explained; however, the subsequent development of the [MILKOR MGL](http://www.military-today.com/firearms/milkor_mgl.htm) may well have been influenced by hands-on experience with the MM-1. A more plausible explanation is that South Africa was listed as an operator by mistake, but another possibility is that they acquired a small number covertly by unconventional means. It also wouldn't have been unique in South Africa's history to have suddenly acquired a suspiciously familiar weapon to one developed elsewhere (see the article on the [Ingwe anti-tank missile](http://www.military-today.com/missiles/ingwe.htm)). The MM-1 has proven much more popular in fiction than in operational service. It has few military users and no notable combat history, but the MM-1 was a mainstay of movies, video games, and technothriller novels alike. Undoubtedly, its most memorable appearance was in Terminator 2 movie.

>http://www.military-today.com/firearms/hawk_mm1.htm

I don't think there are enough in existence to justify this 🤔.

**Comment by AtomicFox556** [comment]
> I don't think there are enough in existence to justify this.

If considering the relative rarity of it to Milkor MGL (of which at least 50000 were made), then as long as at least about 900 have been made, it would be sensible to set the rarity to 1.

**Comment by Fris0uman** [comment]
One thing being wrong does not justify adding more wrong things. If Milkor MGL is too common it should spawn less, or get removed.

**Comment by AtomicFox556** [comment]
> One thing being wrong does not justify adding more wrong things. If Milkor MGL is too common it should spawn less, or get removed.

Sure. The whole list in general seems to be off at the moment, though; 350000 of M79s were made, but it's in fact 6 times *less* common than Milkor MGL of which 50000 were made. Auditing it would need a more accurate way to approximate the relative rarity of those weapons, however.

**Pull request closed without merging**
