### PR TITLE
Magazine Audit - .357, .45, .454, 4.6, .500S&W

### PR DESCRIPTION
**Pull request by ANickelN**
#### Summary
Balance "Audit .357, .45, .454, 4.6, .500S&W Magazines"

#### Purpose of change

Magazines are the wrong size and weight, this PR has better sizes and weights.

#### Describe the solution

Give these magazines the correct dimensions and weight.

#### Describe alternatives you've considered

There is no alternative.

#### Testing

TBD

#### Additional context

This PR is part of issue https://github.com/CleverRaven/Cataclysm-DDA/issues/70784

Auditing information available below as per my post in that issue:

Good site for ammo weights: https://www.thefirearmblog.com/blog/2016/04/09/how-much-does-your-ammunition-weigh/

Values for the following are copied from .44 Magnum Speedloader

### .500 S&W Magnum

Speedloader 5rd

### .454 Casull

Speedloader 5rd
	
Speedloader 6rd

### .357 Magnum

Desert Eagle 9rd Magazine

Values copied from .50AE magazine

### 4.6x30mm

MP7 20rd Magazine
Dimensions from ImageJ
Weight from this post on Reddit: https://www.reddit.com/r/EscapefromTarkov/comments/9w3mwk/psa_the_weight_of_the_mp7_its_mags_and_its_ammo/
Where I did 227g (20rd loaded) - 140g (20rds of 4.6) = 87g
10.5cm tall * 4cm front-to-back * 1.8cm wide
76ml
87g

MP7 40rd Magazine
Dimensions from a pouch sold by TasmanianTiger.
20cm tall * 4cm front-to-back * 1.8cm wide
144ml
165g (Weight proportional from 20rd)

### .45 ACP

MAC 10 30rd Magazine (From ImageJ)
Weight was obtained from ratio: 1.2 g/ml
21 cm tall * 3.5 cm front-to-back * 2.5 cm wide
184 ml
221 g

MAC 10 20rd Improvised Magazine (Based height off of 21 rounds of .45ACP)
25.6cm tall * 3.5 cm front-to-back * 2.5 cm wide
224 ml
269 g

Glock .45ACP Magazine 30rd (Dimensions from ImageJ, weight from vendor)
23cm tall * 3.65cm front-to-back * 2.52cm wide
211 ml
124 g

M1A1

30rd (Dimensions from ImageJ, weight from The Thompson Submachine Gun: From Prohibition Chicago to World War II))
21.25 tall *  3.937 cm front-to-back * 2.5 cm wide
209 ml
226 g 

20rd (ImageJ, Weight from 30rd 1.2 ratio)
15.4cm tall * 3.937 cm * 2.5 cm
152 ml 
182 g

Drum (ImageJ)
21cm diameter, 4 cm depth
1,385 ml
1,110 g

Adds "4.75lb to the weapon" 2155g
20.89g for a .45 Cartridge * 50 = 1044.5g
1100g weight

Improvised 20rd
26.84 tall (22 .45 Cartridges) * 4cm * 2.5 cm wide
268 ml
322 g

UMP .45

25rd (ImageJ, Weight unsourced)
22 cm tall * 3.75cm front-to-back * 2.5 cm wide (estimated)
206 ml
150 g

Improvised 20rd (Weight from 1.2 g/ml ratio)

26.84 cm tall * 3.75 cm * 2.5 cm 
252 ml 
302 g 

USC .45 (lol lamer UMP)

10rd (Image J, weight from UMP Mag Ratio)

18 cm tall * 3.75 front-to-back * 2.5 cm wide (estimated)
169 ml 
123 g 

Aftermarket 15
Can't find good images

Aftermarket 20
Can't find good images

Walther PPQ

12rd (ImageJ)
12.8cm * 3.5 cm * 2.35 cm
105 ml
80g (estimated)

Hi Point JHP

9rd
13.2cm * 3.5cm * 2 cm (single stack)
92ml
110g estimated

Glock 21

13rd (ImageJ)
12.5cm * 3.65cm * 2.5cm
114ml
70g (Glonk 19 Magazine Weighed)

26rd (ImageJ)
22.5cm * 3.65cm * 2.5cm
205ml
126g (Ratio of 13rd mag)

### CODE REVIEW

**Comment by Hyperseeker** [comment]
MP7 mags have stated weights on H&K's page: https://www.heckler-koch.com/en/Products/Military%20and%20Law%20Enforcement/Submachine%20guns/MP7

* 20-rounder: 100 g
* 30-rounder: 150 g
* 40-rounder: 200 g

Those appear to be approximate. See the the H&K USA page: https://hk-usa.com/hk-models/mp7/, where an unknown magazine is stated to be `0.44 in` [sic], which I think should be 0.44 lbs = 199.58 g. This is close-enough to 200 g that we can assume (1) it's a 40-round magazine, because (2) it correlates with the official stated 200 g weight. I haven't found the weight for the 20-rounder anywhere during my most-recent research, but the fact that one of the mags aligns with two official sources suggests the rest of the mags are correct, too.

(Maybe *Tarkov*'s weights are wrong. I'm surprised they would be. I assume Battlestate Games would do their research with calipers and everything. For me, the game had been the last resort for weights I could find nowhere else, like the rear-sight attachment for the ACOG.)

**Comment by Hyperseeker** [comment]
I've also just made some research into the MAC-10 30-round magazine. Here's what I came up with:

* empty MAC-10:
  * source: https://en.wikipedia.org/wiki/MAC-10
  * 6.26 lbs = 2839.5 g
* loaded MAC-10 (.45 ACP):
  * source: https://smallarmsreview.com/mac-10/
  * 8.75 lbs = 3968.9 g
* 30 rounds of .45 ACP (ball?):
  * source: https://www.thefirearmblog.com/blog/2016/04/09/how-much-does-your-ammunition-weigh/
  * 30 × 20.9 g = 627 g
* 30-round magazine weight:
  * 3968.9 - 2839.5 - 627 = 502.4 g

The numbers are staggering, but then, the gun is noted to be quite heavy.

**Comment by Hyperseeker** [comment]
Glock's own website has data for [Glock 21 weights](https://eu.glock.com/en/products/pistols/g21-gen4) with and without magazine:

* no magazine: 745 g
* empty magazine (presumably 13-rounder): 830 g
* magazine weight: 85 g

Additionally, [this aftermarket 26-round magazine](https://www.newfrontierarmory.com/kci-glock-45-26-round-magazine) (admittedly, not factory, but better than nothing) has a stated weight of 0.35 lbs = 158.76 g ≈ 159 g.

**Comment by Hyperseeker** [comment]
The weight of the mag for the PPQ is very confusing, though hovers around the same overall value of ~80 g.

[Wiki](https://en.wikipedia.org/wiki/Walther_PPQ) says PPQ in .45 with an empty magazine weighs ~794 g. (This is corroborated by [this review](https://www.firearmsnews.com/editorial/walther-ppq-m2-45-acp-review/77849), where the weight is listed as 1.75 lbs = 793.79 g, not-rounded. Though confusingly, the weight is listed as "empty".) [This review](https://www.ontargetmagazine.com/2016/01/walther-ppq-45-pistol/) says the gun ("empty") weighs 25.3 oz = 717.24 g.

793.79 - 717.24 = 76.55 g ≈ 77 g.

That said, [this Estonian store](https://www.jahipaun.ee/en/online-shop/toode/weapons/accessories/magazines/walther/padrunisalv-walther-ppq-m2-45-12rds-_v6xws0/) says the weight is 80 g exactly.

Additionally, [this holster manufacturer](https://harrysholsters.com/walther-ppq-vs-glock-19/) presents the weight of the magazine as 2.9 oz = 82.214 g ≈ 82 g (or rather, 24.6 oz [weight with empty magazine] - 21.7 oz [weight with no magazine] = 2.9 oz). [This manual](https://carl-walther.de/uploads/media/testreports/Walther_PPQ_45_VISIER_03_Maerz_RGB_2016.pdf) from the German site of the manufacturer lists the weight ("Gewicht") as 815 g ("with an empty magazine"), which, if we use some of the previous values, makes the magazine 815 - 717.24 = 97.76 g ≈ 98 g.

The differences could be attributed to the mags belonging to at least two different generations of the PPQ (M1 and M2), or maybe even different batches of magazines and imperfections of the weighing methods employed throughout these sources.

So I'd say 80 g is fine, and so would be 77 or 82. 98 g seems outlandish, relatively-speaking.

**Comment by ANickelN** [comment]
Thank you for taking such a detailed look at everything!

**MAC-10**

I think you stumbled across one of the reasons I don't use "loaded" vs "unloaded" weights.  I've found that they are really unreliable since they rarely specify the ammunition used.  Initially I assumed it was ball ammunition for those purposes, but a few times I found that the values were vastly off, leading me to believe that manufacturers loaded their magazines with hollow points instead in order to reduce their "loaded" weight for advertising purposes.

I also am very hesitant to use weights from vendors, and typically only do so as a last-last resort because I find they often use shipping weight instead of item weight.

I don't believe that a MAC-10 magazine would weigh that much when comparing with other magazines.  I don't see what could possibly make them that heavy.  This is one of the instances where I have to use relative weights because numbers from sources are likely not correct.

For reference, a notoriously solid/heavy AK 7.62x39 magazine is 326g per: https://www.reddit.com/r/ak47/comments/3tf05z/762x39_ak_magazine_weight_reference/?ref=share&ref_source=link

**Glonk 21**

Thanks for the values!  I will correct it in the files.

**Pull request merged**
