### PR TITLE
Make the dragon skin armor irreparable

### PR DESCRIPTION
**Pull request by Cyrano7**
Like the description says.

Closes https://github.com/CleverRaven/Cataclysm-DDA/issues/20011

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
It's also too thin. IRL it's 6mm.

**Comment by Mecares** [comment]
Seems more like a bad description, than a item problem. Better approach might be to require armor discs from disassembling another vest for the repair in my humble opinion.

**Comment by Cyrano7** [comment]
I'm totally fine changing the description or having it be non-repairable. When @kevingranade weighed in it looked like he was more in favor of making it non-repairable out of those two choices so I went with that. Trying to move some of these small json fix issues along. This one's been open a year already.

Adding some special ceramic disk component just for fixing dragon skin vests would be kinda cluttery imo though.

**Comment by kevingranade** [comment]
If someone wants to implement the more complex behavior of having dragonskin degrade with wear and repairing it with a ceramic disk that can only be harvested from dragonskin vests, they can feel free, but for now this makes things consistent.

**Comment by BorkBorkGoesTheCode** [comment]
@Cyrano7 Buffing material_thickness to 6 gives bash 12 cut 30

**Pull request merged**
