### PR TITLE
Display inventory quantity of components in crafting menu

### PR DESCRIPTION
**Pull request by thquinn**
#### Summary
```SUMMARY: Interface "Display inventory quantity of components in crafting menu"```

#### Purpose of change
When browsing recipes, I want to be able to see which ones use up ingredients I have to spare, without having to constantly go back to my inventory to check how much of each thing I have.

#### Describe the solution
If you have enough of an ingredient to craft a recipe, it shows the amount in parentheses after the requirement.

ss

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Could you please show how does it look like with items with charges?

**Comment by thquinn** [comment]
ss

Not insanely great... is there a translation-friendly way to make it read "(6 of 100)"?

**Comment by Night-Pryanik** [comment]
Have you tried `text = string_format( _( "%s of %ld)" ), text, qty );`?

**Comment by AMurkin** [comment]
You probably can show quantity text in red when `required == qty`. That would help to see if it's last possible craft.

**Comment by thquinn** [comment]
> Have you tried `text = string_format( _( "%s of %ld)" ), text, qty );`?

That gets me `nail (6) of 100)`... not what I'm looking for either. I just made it a little more explicit to get what I wanted:

ss

**Comment by Night-Pryanik** [comment]
Cool!

**Comment by pjf** [comment]
With regards to UI, I feel that `nail (96/100)` would make sense, be compact, *and* not require translation.

**Comment by pjf** [comment]
Also I absolutely *love this*.

**Comment by thquinn** [comment]
> With regards to UI, I feel that `nail (96/100)` would make sense, be compact, _and_ not require translation.

I might do another PR to clarify and standardize the language on the crafting screen — I don't really understand why we have this inconsistent plural usage in the same ingredient list with `3 heavy sticks` and `nail (8)`.

> Also I absolutely _love this_.

Oh, thank you! :D

**Comment by kevingranade** [comment]
IDK if you saw the compile error, though it doesn't seem to happen on gorgon.
```src/requirements.cpp: In instantiation of ‘std::vector<std::__cxx11::basic_string<char> > requirement_data::get_folded_list(int, const inventory&, const std::function<bool(const item&)>&, const std::vector<std::vector<T> >&, int, std::__cxx11::string) const [with T = item_comp; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
src/requirements.cpp:448:81:   required from here
src/requirements.cpp:478:49: error: overflow in implicit constant conversion [-Werror=overflow]
                     qty = crafting_inv.amount_of( item_id, false, std::numeric_limits<long>::max(), filter );
                                                 ^
src/requirements.cpp: In instantiation of ‘std::vector<std::__cxx11::basic_string<char> > requirement_data::get_folded_list(int, const inventory&, const std::function<bool(const item&)>&, const std::vector<std::vector<T> >&, int, std::__cxx11::string) const [with T = quality_requirement; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
src/requirements.cpp:524:23:   required from here
src/requirements.cpp:478:49: error: overflow in implicit constant conversion [-Werror=overflow]
src/requirements.cpp: In instantiation of ‘std::vector<std::__cxx11::basic_string<char> > requirement_data::get_folded_list(int, const inventory&, const std::function<bool(const item&)>&, const std::vector<std::vector<T> >&, int, std::__cxx11::string) const [with T = tool_comp; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
src/requirements.cpp:529:51:   required from here
src/requirements.cpp:478:49: error: overflow in implicit constant conversion [-Werror=overflow]
cc1plus: all warnings being treated as errors
Makefile:768: recipe for target 'obj/requirements.o' failed```

**Comment by thquinn** [comment]
Is the Travis failure unrelated? It does have to do with crafting, but I can't reproduce it locally.

**Comment by jbytheway** [comment]
> I might do another PR to clarify and standardize the language on the crafting screen — I don't really understand why we have this inconsistent plural usage in the same ingredient list with `3 heavy sticks` and `nail (8)`.

I have an abandoned branch cleaning up plurality on this screen.  Suffice to say, it's complicated and I couldn't find a satisfactory solution.  The issue in particular that I remember is that some foods have (or so I presume) multiple portions per item.  For example, the haggis recipe makes 4 portions (or it used to when I was looking at this), but I think that's just one haggis.  On the other hand the nails recipe is definitely making 100 nails.  It's hard to know when you should pluralize and when you shouldn't.

**Comment by thquinn** [comment]
@jbytheway Ah, that makes sense. I suppose this would require a `charge_name` field on every item that uses charges: "portions" of haggis, "slices" of cake... and even empty strings to indicate that it just uses the plural, like "nails." Sounds like quite an ordeal... one that I could see myself cranking out on a rainy day.

**Comment by kwl01skz** [comment]
@thquinn It's cool, but I think I need it when it's not enough.

**Pull request merged**
