### PR TITLE
Split .40 and 10mm cartridges

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The 10mm is now a separate cartridge.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Itsm my understanding that .40 S&W ammunition has the same diameter of 10mm while having slightly reduced length,  so a revolver capable of firing 10mm should be capable of loading both cartridges. 

Cant guns have more than one kind of ammunition now?

**Comment by DangerNoodle** [comment]
That seems to be reflected in the content of this pull request. A 10mm revolver is given 10mm as the primary ammunition type, while allowing the use of .40 S&W.

Sadly, the ammo type overlap appears to be defined at the individual ammo level only, not at the gun level (unless that is also an option).

**Comment by BorkBorkGoesTheCode** [comment]
I think the multi ammo system only allows defining compatibility at the ammo. The system could allow gun-specific systems by creating custom ammo types for each gun.

Any 10mm weapon can fire .40 ammunition using this system since 10mm is listed as a one-way compatible ammo: `"ammo_type": [ "40", "10mm_auto"],`

**Comment by DangerNoodle** [comment]
As I suspected, though I was not entirely certain. Allowing compatibility at either level would expand versatility, but this pull request amply demonstrates that the current system can be used for a variety of things.

I am considering working on implementing .410 and .45 Colt at some point. Was there also mention of .454 Casull being comparable which one of those?

**Comment by BorkBorkGoesTheCode** [comment]
The .454 Casull was derived from the .45 Colt. If you add ammo_type compatibility, use 454 Casull as the top-level cartridge and add one-way 454 compatibility to the .410 and .45 Colt. You might want to use a unique ammotype for realism. I presume you are going to make something like the Raging Judge?

**Comment by DangerNoodle** [comment]
That what I was thinking of, yes.

**Comment by BorkBorkGoesTheCode** [comment]
The 10mm is now added to conversion gunmods.

**Comment by DangerNoodle** [comment]
That reminds me, my ideas led me to a question. I am wondering whether it is possible to implement a firearm that requires magazines when using one type of cartridge, but loads normally with others. Example being the S&W Governor, which can load .410, .45 Colt, and .45 ACP (but requires moon clips if using ACP).

**Comment by DangerNoodle** [comment]
Decided against moon clips for the time being, current additions in: https://github.com/CleverRaven/Cataclysm-DDA/pull/18986

**Comment by mugling** [comment]
Very against this. This just adds unnecessary complexity for no improvement in gameplay. The purpose of alternate ammo types was to provide novel items, not simulate the minutiae.

**Comment by mugling** [comment]
See #18571. I don't have any suggestions as to how to salvage this PR so closing.

**Comment by DangerNoodle** [comment]
I can contribute my additions as mod content if desired.

**Pull request closed without merging**
