### PR TITLE
adds the target dummy + recipe

### PR DESCRIPTION
**Pull request by kettleswordfang**
uses fabrication 2 + gun 1 to make = 10 rags, 3 two by fours, 1 pile of straw.
use to place a hostile "target" mob with high hp + no attacks for training ranged skills.

### CODE REVIEW

**Comment by kettleswordfang** [comment]
dang, can't figure out why this one failed the build..

**Comment by AMurkin** [comment]
`other.json` formatted by [JSON-linter](http://dev.narc.ro/cataclysm/format.html) looks like [this](https://gist.github.com/AMurkin/12074598bfc8e9f6b98df6bcb426b214).

**Comment by Night-Pryanik** [comment]
I have a feeling that this will cause balance issues...

**Comment by Mecares** [comment]
Some players will certainly like this, but being able to train even more skills by hunkering down somewhere for a season or two might not be good for the game experience. The sitting on a pile of food and books is already bad enough.

**Comment by kettleswordfang** [comment]
yeah, that makes sense.. what about pushing the skills required up & making it harder to make? then give it less health, so it's more to top off a level instead of gaining a whole one?

**Comment by AMurkin** [comment]
Previous PR build were successful: http://gorgon.narc.ro:8080/job/Cataclysm-PR-Builder/2687/
Log at https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/312775729 finished by:
```
Terminated: data/mods//dda/../../json/monsters/drones.json: line 147:13: invalid color name
    "material": [ "wood", "cotton" ],
    "symbol": "@",
    "color":
            ^
             "dkred",
    "aggression": 1,
    "morale": 1,
```

**Comment by kettleswordfang** [comment]
i'm gonna play around with the balance on this one for a while, in light of @Mecares' comments

**Comment by kettleswordfang** [comment]
**brought the health** down from 1000 to `400`, and **upped the recipe requirements** 
i'll have to up the weight of the unplaced / broken targets, too

```        "skill_used": "fabrication",
        "difficulty": 6,
        "skills_required": [ "tailoring", 5 ],
        "time": 20000,
        "book_learn": [
            [ "mag_guns", 2 ],
            [ "mag_pistol", 2 ],
            [ "mag_rifle", 2 ],
            [ "recipe_gunslinger", 1 ]
        ],
        "qualities": [
            { "id": "SEW", "level": 1 },
            { "id": "HAMMER", "level": 1 },
            { "id": "SAW", "level": 1 }
        "components": [
            [ [ "rag"         , 24 ] ],
            [ [ "nail"        , 16 ] ],
            [ [ "2x4"         ,  5 ] ],
            [ [ "straw_pile"  ,  1 ] ]
```

**Comment by ZenZen2** [comment]
Dummy is unable to move. You should not be able to get a high skill from shooting at it.

**Comment by kettleswordfang** [comment]
@ZenZen2 is there a way to change the skill gain from hitting it?
if there isn't, this may be too OP for inclusion regardless of recipe requirements.

**Comment by Broken-Admin** [comment]
@kettleswordfang Why did you add the "generix.json" to the git ignore?

**Comment by illi-kun** [comment]
Closing due to inactivity, merge conflicts, unrelated changes and huge diffs.

**Pull request closed without merging**
