### PR TITLE
Mshock tileset additions and revisions [RDY]

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
I made a few changes to some gun sprites: The extra white pixels on one of the magnums are gone, the PPSH has a straight magazine, some of the lumpiness on one of the SMG magazine has been fixed, I frankenstein'd a new sprite for the SVS-24c and the Rivtech combat armor.

The mininuke launcher looked too much like the Fallout mininuke launcher, so I created a new sprite for it. The Boba Fett Rivtech helmet is gone as well. Both are still present in some of the Chezzo tilesets; they may need to be removed in future.

This will be my first attempt at tileset revision. @Mshock777 , do you object to this?

### CODE REVIEW

**Comment by DangerNoodle** [comment]
What about opened and/or sealed cans, jars, cups, and other items? They no longer use existing spites due to changes in what item IDs occur.

**Comment by BorkBorkGoesTheCode** [comment]
I will add those in a later PR.

**Comment by BorkBorkGoesTheCode** [comment]
@illi-kun any objection to this?

**Comment by illi-kun** [comment]
@BorkBorkGoesTheCode not from my side but unfortunately I'm not able to test Tiles Version due to technical issues on my side (have some issues with my main laptop and building the tiles=1 version on my backup netbook will take years).

**Comment by Lady-Luck** [comment]
Any plans on PK support?

**Comment by BorkBorkGoesTheCode** [comment]
I don't have any sprites for it right now; I may add some in a later PR.

**Comment by mugling** [comment]
> the PPSH has a straight magazine

Sprite doesn't appear for me

Can you list what is changed/needs testing

**Comment by BorkBorkGoesTheCode** [comment]
@mugling Which tileset? How did you view it?

**Comment by BorkBorkGoesTheCode** [comment]
Ready to test now.

**Comment by mugling** [comment]
@BorkBorkGoesTheCode can you list all the items changed?

**Comment by BorkBorkGoesTheCode** [comment]
The mininuke launcher, SVS-24C and Rivtech helmet have new sprites. White pixels were removed from one of the revolver sprites; The PPSH smg sprite was changed, now its magazine is straight; Unsealed drink cans default to can_drink sprite; The PPSH-41 drum magazine uses the generic drum magazine sprite; The PPSH magazine uses the generic extended pistol magazine sprite.

**Comment by mugling** [comment]
...and the PR queue finally fits on a single page

**Comment by BorkBorkGoesTheCode** [comment]
Don't be so sure, I'm going to PR a rebalance to Icecoon's Weapons Pack.

**Comment by DangerNoodle** [comment]
I forget whether or not Icecoon's Weapons Pack has magazines yet. If not, that would be an interesting thing to see.

**Comment by mugling** [comment]
Ammo linkages are a big need, especially following #18362

**Pull request merged**
