### PR TITLE
Modern Lemat revolver

### PR DESCRIPTION
**Pull request by John-Candlebury**
It's been suggested more than once by people in the forums, and I figured it would make a great backup gun.

It fires 12 gauge I don't think  adding .20 or .16 shot for a single gun is a good idea, and since we already have a 12 gauge pistol I didn't think it would have been a dealbreaker.

Same spawns as the desert eagle, but about half the frequency.

### CODE REVIEW

**Comment by kevingranade** [comment]
Isn't the desert eagle amazingly popular? Are you sure half of its spawns
are reasonable?

**Comment by John-Candlebury** [comment]
The ingame Desert Eagle only  spawns in pawnshops, lmoes, and all guns. The chances for the lemat in those lists are 1, 3, and 1 respectively.

It doesn't seem that bad, but guess that I can remove them from the lmoe list so you don't get them from the gun basements.

**Comment by kevingranade** [comment]
That sounds about right. We might have the opposite problem of the deagle
being rarer than it should be, but that's not your problem.

**Comment by chaosvolt** [comment]
Ooh. That was one gun I was going to suggest for the Fictional Weapons mod, as modern takes on it seem more common in fiction that real life, as far as I can tell.

Though if we added a classic version that uses powder and shot...

**Comment by John-Candlebury** [comment]
Well  I am more interested in adding a gun that is both a high capacity revolver and a single shot shotgun to the game, seems like a neat addition to vanilla when you consider the flexibility it gives you. It doesnt really has to be a lemat replica.

I can rename it to something like Ruger Agency Special, Colt Combination or something different altogether;  but I would rather call it a LeMat revolver so people can get a decent idea of what the thing looks like.

**Comment by chaosvolt** [comment]
Maybe. I'm still in favor of adding a cap-and-ball version as well. XP

**Comment by karlnp** [comment]
I thought we already had a cap and ball revolver?

**Comment by chaosvolt** [comment]
Of normal Colt army and navy revolvers, yes.

Of a revolver with an additional integrated shotgun barrel? No.

**Pull request merged**
