### PR TITLE
Added REACH_ATTACK flag to Pointy Stick and Javelins

### PR DESCRIPTION
**Pull request by nanzington**
#### Summary
```SUMMARY: Content "Added reach attacks for Pointy Stick, Javelin, and Steel Javelin."```

#### Purpose of change
Description of the pointy stick and the javelins indicated they are long enough to be considered spears, but didn't have the REACH_ATTACK flag.

#### Describe the solution
Added the REACH_ATTACK flag to the point stick, javelin, and iron javelin to reflect their length.

### CODE REVIEW

**Comment by Zireael07** [comment]
IIRC javelins are thrown, not used in melee?

**Comment by Rail-Runner** [comment]
As far as I know, pointy stick is simply too short to have a reach attack (it's really more like a wooden stake; might be a good idea to rename it to "wooden stake" to prevent further confusion), and javelins are generally shorter than spears too.

**Comment by hootless** [comment]
The pointy stick point is fair, but I think it makes sense to be able to hold a javelin and stab with it. It may not be as effective as a regular spear or even as effective as throwing the javelin, but javelins are typically around 2.5 meters long. Seems more than long enough to justify reach attacks

**Comment by kevingranade** [comment]
It's long enough, but the grip placement and reinforcement is wrong for use as a reach weapon, you hold a javelin in the middle, not on the end, and if you try to hold it on the end it's not going to have appropriate grip or balance.

**Pull request closed without merging**
