### PR TITLE
Fixes several bugs with pocket whitelists and blacklists

### LINKED ISSUE #41816: Pocket priorisation/whitelist doesn't seem to be working at all
# Describe the bug

Despite setting a pocket (or several pockets) whitelisted for something and increasing the pocket priority, picking up an item of that category puts it into an entirely different container

# Steps To Reproduce

1. Spawn a hiking backpack, army pants a butcher knife and some grenades and a joint
2. Wear the hiking backpack and the army pants
3. Set pocket 4 of the hiking backpack to whitelist drugs and increase it's priority
4. Set pockets 5 and 6 of the hiking backpack to whitelist weapons and increase their priorities
5. pickup the joint, the butcher knife and the grenades
6. all items will be put into army pants pockets

# Expected behavior

The items should be added to their increased priority whitelisted pockets

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3706-g16fb746 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Whitelisting specific items, ie the joint doesn't work either
Maybe I just don't understand how the system works correctly, or maybe all the tested bags are somehow restricted, but at least from the hiking backpack description, I can't see any restrictions to the pockets. Also I'm pretty sure pocket 1 of the backpack should take everything, but it doesn't work with that pocket either.
If there are any restrictions they should be clearly shown, and ideally the pocket interface shouldn't allow to set whitelists for categories/items that cannot go into that pocket

### LINKED ISSUE #42804: Pocket category whitelist doesn't work
# Describe the bug

Pocket category whitelist doesn't seems to work. For example, with whitelisted "Magazines" category on army pants pockets P320 mag goes into backpack on pickup, instead of pants. Even if mag inserted into pants manually, it'd go to rucksack on gun reload.
Desired use-case scenario: to define "battle gear" with only essentials in pockets to keep encumbrance down, with mags going into fastest pockets, whereas rest of the loot goes into backpack and can be quickly ditched. 

# Steps To Reproduce

1. Spawn army pants, military rucksack, P320 9x19 mag
2. Wear pants & rucksack
3. Set category whitelist on all pants pockets to "Magazines"
4. pick up P320 mag, it'll go to rucksack instead of pants
5. Fiddle with pocket priorities (set higher for pants, lower for rucksack), repeat test, still goes into rucksack
6. drop mag, remove category whitelist
7. pick up mag, it goes into pants as expected
8. set item whitelist on pants pockets to "p320 mag"
9. pick up mag, it goes into pants as expected

# Expected behavior
With category whitelist set to "magazines" on pants P320 mag to go into army pants instead of rucksack.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Squishums**
#### Summary

SUMMARY: Bugfixes "Fixes several bugs with pocket whitelists and blacklists"

#### Purpose of change
Pocket whitelists and blacklists were a little borked. Not enough test coverage and there were several outstanding issues.

Fixes #41816
Fixes #42804 

Both of these are issues caused by [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/938a274e93f37440de346a24165bb2ee6889640f/src/item_pocket.cpp#L274-L277) check in `better_pocket` where priority was considered the exclusive way of determining the best pocket if either of the pockets defined a whitelist or blacklist.

Also fixes an unreported issue where whitelists and blacklists were not being respected at all in some cases, particularly when pocket restrictions leave the item nowhere to go. See [here](https://github.com/Squishums/Cataclysm-DDA/blob/e184e46766b7262cafce2f42658d66ced0829dc3/src/item_contents.cpp#L504-L516), where the first found pocket is picked as the target, regardless of whether items are allowed in it.

While I was at it, `is_null` for the favourite settings not including the priority felt... strange.

#### Describe the solution

Hoisted the filter check from the pocket `better_pocket` code to the item_contents, as it already assumes that both pockets *can* contain the item. This is only place I can see `better_pocket` being called.

Refactored the whitelist resolution and added tests to clarify the expected handling. Made sure explicit item filters override category filters (because anything else doesn't make much sense).

I want to add additional tests to verify best pocket ordering but... I don't really want to that badly either 🙃

#### Describe alternatives you've considered

More significant refactoring and more reliance on std algorithms, but we're not making anything harder by putting it off for now.

#### Testing

Manual testing as in the two linked issues.

Also for overlapping filters:  
* Strip
* Wear backpack (single pocket container), and spawn a gun magazine on the ground
* On the backpack, blacklist magazines
  * Trying to pickup the magazine prompts to wield it
* On the backpack, leave the magazine blacklist, but whitelist the specific magazine item
  * Trying to pickup the magazine puts it in the backpack.

#### Additional context

The rest of the code here kinda needs more tests. Ordering logic is prone to regressions.

### CODE REVIEW

**Comment by Squishums** [comment]
(Ionno if this is content freeze? It's fixing a blocker for the 0.F release)

**Comment by anothersimulacrum** [comment]
You're right, that snuck in when I was adding labels.

**Comment by wapcaplet** [comment]
Playtested OK, blacklisting and whitelisting magazines from a rucksack - works as expected. Thank you for building up the test cases as well!

**Comment by Squishums** [comment]
No problem! Honestly I feel kind of naked making changes without good test coverage, and it'll save time in the long run.

**Pull request merged**
