### PR TITLE
Enable the wraith monster

### PR DESCRIPTION
**Pull request by BevapDin**
(I found this via #13333, thanks to @VlasovVitaly for inquiring the "darkness" effect. One gets this effect via the `mattack::darkman` ("DARKMAN" in JSON), which is only used by the monster "mon_darkman", named "wraith" in game).

The monster "mon_darkman" was introduced by #4570, but the spawning of it was lost during the merge. (The last commit of the PR was on Nov 23, 2013, it was merged on Mar 2, 2014, which explains the merge problems.)

Seriously: check out dce396da0727acd9dcd25556424f701dda303376, the last commit from that PR and search for "mon_darkman" and "darkness", then check out the merge commit 88fb9d3369db10c225890360e13db2a43eb23cc7 and search again (see also that the merge commit does not touch src/mapgen.cpp and src/player.cpp at all).

And nobody noticed. It's been nearly 1.5 years. The whole `monattack::darkman` function and probably the death function as well were not used at all. Did I mention 1.5 years? The "darkness" effect is not used at all. There are several tileset commits that mention it. @John-Candlebury, didn't you miss your own creation for all the time?

Oh, and the effects of the "darkness" effect are not really applied. The effect only changes the color of all things around the character to gray (see `map::draw_maptile`, the _only_ real reference to it). It's referenced in other parts, but for no effect: monattack.cpp: added from a never spawning monster (since 1.5 years!), mondeath.cpp: removed when the never spawning monster dies (there's an interesting philosophical dilemma in there, somewhere), player.cpp: removed when in sunlight (but where to get it from, 1.5 years).

I re-added the spawning and the effects of the effects.

I'm still not over the 1.5 years and I'll never will (-:

### CODE REVIEW

**Comment by VlasovVitaly** [comment]
C-C-C-C-ombo breaker.

2015-08-18 17:21 GMT+03:00 BevapDin <notifications@github.com>:

**Comment by VlasovVitaly** [comment]
Gj btw =)

**Comment by chaosvolt** [comment]
Oh wow, that's one of those "how did no one notice this" sorta things. What faction are they supposed to be anyway, cultist I'm guessing?

**Comment by Rivet-the-Zombie** [comment]
I barely recall this critter, and I was never aware that the wraith actually got added - well, sorta added, anyway.

Nice work, @BevapDin!

**Comment by chaosvolt** [comment]
I had always assumed it was an obscure spawn, when I noticed it was unsprited in Mshock's set while working on the modded version. So at least it'll have some graphical support for when it makes its year-and-a-half belated debut. X3

**Pull request merged**
