### PR TITLE
Initial shotgun rebalance

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Currently shotguns way too accurate and very close range at the same time. That happens after that:
https://github.com/CleverRaven/Cataclysm-DDA/pull/23720

It is attempt to at least get a first stub on it and get adequate dispersion values. It is only to stabilize situation overall.

# Result
* All shotgun using shot ammo has max range 12. Slug adds +12 so shotgun with slug can shoot to 24 tiles.
* Shotguns now have somewhat smg to pistol accuracy. Don't worry - it is enough for their close range role.
* Shotgun dipersion stats still far from ideal. Most shotgun have way to similar accuracy. But it was before.
* Character likely get effective range to max shot range pretty quickly. Switch to slugs if you need more range.
* Shotgun tests were added. But they use  tests range values between pistols and smg in most cases.
* Buffed effect of riffled barrel upgrade to -200 dispersion instead of -150. Since now slug can give shotgun up to 24 tiles of max range - rifled barrel give player chance to reach it more effectively. Also damage modifier changed to -8 from -20 to make this upgrade worth using without massive damage reduction.

# It is based on that statements:
* I assume that shtoguns dispersion already balanced aginst each other in some way. That is why I'll try to make change relative to previous
* I'll try to put shotguns between pistols and smgs. But with better maximum range with slugs (with shot max range will be worse then pistols).
* Initially I assume thet shotgun will use shells so inital range will be limited with 10-12 tiles. At the same time I'll increase slug bonus to max range to +10 or +12.
* I'll try to keep orignal shotguns role- closer range high damge weapon.

# Range table:
Characters definition: https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403

Character | >50% good | <10% good
-- | -- | --
Novice pistol | 5 | 15
Novice shotgun | 6 | 16
Novice SMG | 7 | 20
Novice rifle | 9 | 25
Competent pistol | 13 | 35
Competent shotgun | 15 | 37
Competent SMG | 20 | 55
Competent rifle | 30 | 90
God pistol | 20 | 120
God shotgun | 24 | 124
God SMG | 30 | 190
God rifle | 60 | 800

Shotgun tests have values between smgs and pistols because shotguns now have somewhat smgs accuracy.
Shotgun with shots limited by 12 tiles. Shotgun with sligs limited by 24 tiles.

Novice shotgun:  just non skilled characted with double barelled shotgun. Less accurate than averege shotgun.
Competent shotgun: mid-game character with modded Kel-Tec KSG. Kel-Tec KSG is accurate and versatile shotgun due 2 built in magazine tubes. Good choice.
God shotgun: end-game character with heavily modded powerfull heavy automatic shotgun. It is not the most accurate shotgun, but godlike character don't really care.

# For modders.

### Convertsion pattert for shotguns:
All  average shotgun must have at least 300 dipersion. It is (almost) smg dipersion.
Dispersion for "normal" shotgun should be around 300-500.
Dispersion for "scrap" shotgun should be around 600-900.
Of course you can violate this rules for special effects. But try to stick to smg dispersion ranges for normal (non handmade scrap) shotguns.

 Simple conversion for exisitng shotguns: add + 300 to your shotgun to get proper dispersion.
Warning it also affects anything the should behave like shotgun. Example -  any shotgun pistol.

### Convertsion pattert for shotgun ammo:
Basic shot now has range 12 Basic slug adds +12 to range.
Just multiply your shotgun ammo range to 2. This way range:
6 X 2 = 12.
5 X 2 = 10.

But most likely your shotgun ammo already has "copy-from".
So likely changes are not needed.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Don't worry  - dispersion modification only temporary hardcoded.

**Comment by Firestorm01X2** [comment]
A lot of shotguns clamped around dispersion 0..100. Adding +400 to it put it to pistol range.

**Comment by Firestorm01X2** [comment]
Ready for review.

**Comment by Firestorm01X2** [comment]
I decided to try 12 to shot and 24 for slug.

**Comment by BorkBorkGoesTheCode** [comment]
The rifled barrel still doesn't work right, but that can be fixed in a later PR.

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

**Comment by Firestorm01X2** [comment]
Jenkins, Rebuild.

**Comment by Firestorm01X2** [comment]
>The rifled barrel still doesn't work right, but that can be fixed in a later PR.

Change at least make it slightly more useful.

**Comment by BorkBorkGoesTheCode** [comment]
>Change at least make it slightly more useful.

I'm not saying it doesn't.

**Comment by Firestorm01X2** [comment]
I need time to check if I should reduce shotguns disperion additionaly to -50.

**Comment by Firestorm01X2** [comment]
Going for -100 for shotgun dispersion. It still gives good accuracy wethout being too accurate.

**Comment by Firestorm01X2** [comment]
Ready.

**Comment by BorkBorkGoesTheCode** [comment]
@Firestorm01X2 you don't need to commit arbitrary code changes to rebuild the PR; just add Jenkins rebuild to a GitHub comment.

**Comment by AMurkin** [comment]
Jenkins, but not travis.

**Comment by Firestorm01X2** [comment]
Do we still wrtiting [RDY] to show that PR is ready?

**Comment by BorkBorkGoesTheCode** [comment]
I was told [RDY] is a redundant notification.

**Comment by BorkBorkGoesTheCode** [comment]
One thing you're missing is a dispersion nerf for the .22 rat-shot.

**Comment by Firestorm01X2** [comment]
@BorkBorkGoesTheCode 
I've diceded to add dispersion to shotguns intself  but not to the ammo. 
Also there are few things:
1) Zero desptioson from shot like ammo repesents that it has spread that increase chance to hit a lot.
2) .22 guns are not shotguns and they already have somewhat adequate dispersion (not nearly zero as it was for shotguns)
3) 0.22 ratshot max range is p 13*.06 = 8. At the same time shotgun shot range max will be 12. So normal shotgun anyway will be better.
4) Ratshot has extremly low damage output.

Yes overall some 0.22 guns with ratshot will be very accurate cosidering zero disperion of ratshot. But considering things above it should be ok. Yes I can add some dipersreion to ratsot but in against 1)

**Comment by Firestorm01X2** [comment]
@BorkBorkGoesTheCode 
Just look at this. Setting 60 dipersion to rathot maybe move even chance of good hit at maximum aming to 10. It will give nothing.

ratshot

And considering damage of 10 and range 7. Well, you can wreak chaos among rats. And that is it.

**Comment by DracoGriffin** [comment]
>Do we still wrtiting [RDY] to show that PR is ready?

No, anything without [CR]/[WIP] is supposed to be [interpreted as being "ready"](https://github.com/CleverRaven/Cataclysm-DDA/pull/23080#issuecomment-373943367).

**Comment by Night-Pryanik** [comment]
> anything without [CR]/[WIP] is supposed to be interpreted as being "ready".

Only without [WIP] prefix.

**Comment by Firestorm01X2** [comment]
Damage modifier for rifled barrel changed from -20 to -8 to make it more worth using.

**Comment by Firestorm01X2** [comment]
It is still ready.

**Pull request merged**
