### PR TITLE
[WIP] Add belt clips to more items

### PR DESCRIPTION
**Pull request by mugling**
Adds `BELT_CLIP` flag to some more items

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Doesn't work properly with items that lose charge over time.
Tested it with the heavy duty flashlight on a firefighter belt. Didn't lose a single charge in 2 hours.

**Comment by mugling** [comment]
Hmm, didn't notice that. Possibly items in containers don't tick? If so that should be an easy fix.

I suppose there should also be functionality to turn off an active item when taking it off and/or putting it in a container?

**Comment by kevingranade** [comment]
(Not directed at you mugling)
Crap, this kind of thing is why I didn't want to extend holstering any
further, we're slipping down a slope toward having two different inventory
systems that work in fundamentally different ways.

**Comment by mugling** [comment]
@kevingranade Yes, having looked at the code I perhaps agree. The inventory/container system is mention in innumerable PRs. There have been attempts to fix *eg.* #10926 and complaints about irrational behavior *eg.* #12781. I guess the above falls into the latter grouping (works but shouldn't).

When I looked in to reloading firearms with magazines (anyone interested?) both the gunmod and container code scared me - as above no offence intended to anyone.

If I perhaps abandon this PR for now as it doesn't add so much in terms of gameplay but could we merge #13936 as the nobody wants to remove the existing holsters and that PR consolidates four differing `iuse` functions in to a solitary `iuse_actor` as previously suggested by @BevapDin in #13683 and is perhaps helpful in discouraging further divergence?

I recall seeing a design specification for a new container system. Does anyone have the PR for this?

**Comment by Zireael07** [comment]
I think the design specification for the new inventory system is floating around on the forums. Variously restated, last time in the thread titled something about forgetting pockets.

**Comment by narc0tiq** [comment]
> both the gunmod and container code scared me - as above no offence intended to anyone.

I don't think anyone would take offense to that -- both are well known as sources of terrible fear. The gunmod system, in particular, is on the official "don't do this again, ever" list.

On the topic of specs for a nested inventory system, I did re-discover #3671, which I think summarizes the big challenges, some of which may have been alleviated by changes in the intervening two years. The biggest problem, by far, is interface -- items acting as containers are relatively simple (if only by comparison).

**Pull request closed without merging**
