### PR TITLE
Makes it possible to just make a concrete floor.

### PR DESCRIPTION
**Pull request by JonahDes**
#### Summary 
```SUMMARY: Content "Makes it possible to make a simple concrete floor."```

#### Purpose of change
Someone asked if they could make floors. Construction option didn't seem to exist, so I made the recipe and added it to the json. Super easy, super simple. It uses 2 Concrete, 2 Water, and requires a pit, to imitate something of a few inches dug out for filling.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
`t_thconc_floor` creates not only floor, but also a roof above. You probably should increase amount of required concrete and time.

**Comment by JonahDes** [comment]
> `t_thconc_floor` creates not only floor, but also a roof above. You probably should increase amount of required concrete and time.

Do you know what will create a floor, but no roof? Time is just half that required to make a roof. Which seemed alright, ingredients halfed, too.

**Comment by paulenka-aleh** [comment]
"Build Concrete Roof" results in the same terrain and it is much harder to make. Also "t_thconc_floor" is not just a floor, it's "bare and cold concrete floor with matching roof". So I suppose you need to add another terrain first for the floor without roof which is not indoors

**Comment by JonahDes** [comment]
> "Build Concrete Roof" results in the same terrain and it is much harder to make. Also "t_thconc_floor" is not just a floor, it's "bare and cold concrete floor with matching roof". So I suppose you need to add another terrain first for the floor without roof which is not indoors

Nope. It exists as a terrain simply called t_concrete in terrain.json.

Issue fixed.

**Comment by Rail-Runner** [comment]
I think it'd be better to replace t_pit with t_pit_shallow, if the pit has to be just a few inches deep.

**Comment by JonahDes** [comment]
> I think it'd be better to replace t_pit with t_pit_shallow, if the pit has to be just a few inches deep.

I agree, changed.

**Comment by adamkad1** [comment]
now we can make roads!

**Pull request merged**
