### PR TITLE
[WIP] bow itemization & progression improvements

### PR DESCRIPTION
**Pull request by nphyx**
#### Summary
```SUMMARY: Content "improves bow itemization"```

#### Purpose of change
Itemization and progression for bow users janky. Early game you start off with makeshift and medieval bows that aren't fit to purpose and can't be customized, and spend most of your time looking for the holy grail - the rare and precious compound bow - or maybe settle for the almost-as-rare recurve.

This is all wrong. The current state of progression for archer characters is from amateur-crated self bow -> short bow -> longbow -> recurve -> compound, akin to if gun progression was arquebus -> flintlock musket -> hunting rifle -> sniper rifle. IOW it's progression by historical technological development, not by skill and availability within a modern context.

This would be fine if it's what people did IRL, but IRL kids and newbies start on modern low draw-weight compound and recurve bows and graduate to higher weight bows as they mature. The only people using medieval weapons are doing it for hobby and competitive purposes, and they're comparatively hard to find.

Those light draw & training bows should exist in game, and should be a little easier to find than the high-end bows (they're less likely to have been looted or taken by their owners on some one-way trip to wherever).  They'd be less useful than a high draw-weight bow, but as modern bows they support standard bow accessories. In any case they're way better than a random stick with a string tied to it.

#### Describe the solution
* surveyed the current state of bow itemization, to find gaps that might be filled
* searched for information on what kinds of modern bows are in common use and stocked in stores in the MA area
* selected a few popular bows that fit the bill as references and figured out their characteristics
* added them to the game

Also:
* obsoleted the hybrid and reflexrecurve bows, which have no real-world analogs (and don't seem to get much use anyway)
* recalculated the range of bows based on their momentum, proportionate to the range of the compound bow
    * a simple linear relationship - but good enough I think, better than what seemed to be arbitrary values
    * this resulted in a slight buff to base range for most bows
* recalculated bow damage
    * using the formula given in the Archery section of the game balance doc, divided by 5 per the recent rebalance
    * this mostly didn't make a difference but there were a few small tweaks
* gave recurve bows a very small advantage in dispersion over compound, based on anecdotal reports that novice archers are somewhat less prone to errors due to their simpler design
    * this is somewhat controversial, so I'm not married to it
* gave compound greatbows the ability to tighten/loosen limbs
    * but these should probably not be in the game, or be an insanely rare find
    * ... and their stats are as-if commercially manufactured, so shouldn't be craftable as they currently stand

#### Describe alternatives you've considered
* this or something like it needed to be done IMO, so none really

#### Testing
* spawned bows in game, made sure they worked
* spawned some zombies and shot at them
    * note I was not really interested in their damage, just checked that nothing funky happens

#### Additional context
!! this is NOT meant to "fix" or "balance" bow damage !!
It's meant to address itemization & realism issues.

That said, I am happy to have my math checked to make sure it all lines up with the current state of the game. Or have better math suggested especially in regard to range and strength requirements.

I'm also not addressing craftable modern bows here or doing anything with primitive/medieval bows.

Spreadsheet with current & new bows, stats, reference links, and some simple sanity check calculations here: https://docs.google.com/spreadsheets/d/18xUCaRRg0_-WfpN0gSfO_cZeHh5TxIWupCSKw1zSRm8/edit?usp=sharing. It's a little messy, sorry about that.

Still to do:
* add spawns for the new bows to appropriate places
* fix a bug where having 3 levels of compound bow draw weight doesn't work (this may be a C++ problem, I haven't dug in yet)

### CODE REVIEW

**Comment by FirebrandCoding** [comment]
Loving your work, man. Keep doing your thing.

**Comment by ampersand55** [comment]
> This is all wrong. The current state of progression for archer characters is from amateur-crated self bow -> short bow -> longbow -> recurve -> compound, akin to if gun progression was arquebus -> flintlock musket -> hunting rifle -> sniper rifle. IOW it's progression by historical technological development, not by skill and availability within a modern context.

> This would be fine if it's what people did IRL, but IRL kids start on modern low draw-weight compound and recurve bows and graduate to higher weight bows as they mature. The only people using medieval weapons are doing it for hobby and competitive purposes, and they're comparatively hard to find.

I agree that finding medieval type bows doesn't make much sense. The reason a survivor would use primitive bows would be because it's preferable to go into the woods and craft a primitive bow rather than raiding a town centre full of zombies to find a modern bow.

For bows a progression from primitive to modern make sense as different materials/technologies of bows represents how good the bow is at converting the elastic energy in to bow to kinetic energy of the arrows. E.g. a low draw weight modern compound bow could reach the same arrow speed (i.e. damage) as a high draw weight primitive bow as less energy is lost to internal friction. [See this](https://www.isegoria.net/2007/09/the-physics-of-medieval-archery/).

Then we could have the progression:

1. self bows (made from a single piece of wood) - easy to craft.
2. composite bows (made from different laminated materials for better elastic energy storage) - harder to craft
3. modern recurve bows (calibrated carbon fibre limbs) - easy to find.
4. compound bows (using a  levering system for a mechanical advantage) - harder to find.

The strength requirement of bows would represent the draw weight and the material/technology would represent how good the bow is at converting energy. E.g. you could get the same damage with a low draw weight advanced bow as a high draw weight primitive bow.

**Comment by nphyx** [comment]
> I agree that finding medieval type bows doesn't make much sense. The reason a survivor would use primitive bows would be because it's preferable to go into the woods and craft a primitive bow rather than raiding a town centre full of zombies to find a modern bow.

Thing is this isn't Minecraft. Crafting is not the first or best option for survivors, it's an alternative for people who want to do the wilderness survival thing as an alternative to raiding and looting. It comes with the caveat that the stuff you make is not going to compare well to the things you can find if you're willing to risk heading into town. *Except* if you want to do an archery build, in which case like I said you're going to spend a lot of time making crappy bows that no sane archer would use, because bow itemization is almost nonexistent. That's the problem I'm trying to solve.

If a survivor wants to go into the woods and teach himself to craft increasingly advanced bows, that's fine. There's been a lot of discussion on what would be possible for a sufficiently skilled craftsman to make. I'm just not personally interested in tackling that (and someone else is, though I won't name them in case they're not ready to talk about it yet).

**Comment by dissociativity** [comment]
I'd recommend making a survivor compound bow using crafting methods similar to those you can find on youtube, a bit worse and importantly due to materials used, heavier than a fancy modern one, then weaken the compound greatbow proportionally so it scales in strength more or less as it would relative to the hand-made compound bow.

Crafting difficulty and parts are up to you.
I've got a friend who understands bows fairly well and could implement it if you do not in future with his help for realism/balancing.

**Pull request closed without merging**
