### PR TITLE
No Fungal Monsters mod

### PR DESCRIPTION
**Pull request by chaosvolt**
A blacklist mod that I've occasionally used, in one form or another, for
quite a while.
1. As the name implies, blacklists all the various fungal monsters
   currently present.
2. Additionally uses the option to blacklist monster groups for the sake
   of redundancy, AND to make things more likely to keep working if
   additional fungal monsters are ever added in.

Now if only I could find where I found out about that "blacklist by
monstergroup" option...

### CODE REVIEW

**Comment by kevingranade** [comment]
This is still going to have fungal tower terrain, but it won't have any monsters in it, right?
For that specific case I think we can check if the fungal tower monster is blacklisted, and if so refuse to spawn the terrain type.

**Comment by DavidKeaton** [comment]
Would it be too much work to enable the ability to blacklist terrain?

**Comment by chaosvolt** [comment]
Ah, hmm. Is there any way to blacklist terrain? I could've sworn when I poked around on the wiki, something claimed that removing the relevant monsters and/or monster groups would affect what terrain spawns. O.o

**Comment by chaosvolt** [comment]
Well this is annoying. I've tried overriding with overmap_specials. I've tried overriding with overmap_terrain. I've tried overriding the MAPGEN files to place faked fields.

Not sure if I can find any other workarounds using nothing but .json files, it seems.

**Comment by DavidKeaton** [comment]
The fungal terrain has been in since Whales I think, so it's very likely hardcoded.

**Comment by chaosvolt** [comment]
You'd think my talent for breaking things would wreck something, but Whales seems to have made it fairly bulletproof. ;w;

**Comment by Coolthulhu** [comment]
You can't blacklist terrain because there is no such thing as "lack of terrain".
You could stop terrain replacements when the terrain is blacklisted, but then all mapgen sections would need to reset the terrain to dirt/grass first.

A better way would probably be to make a replacement table for terrain, so that when something tries to place the wrong type, you overwrite it.
For now you could just overwrite the terrain stats to make it different. Say, just make it moss or sludge and leave it as a weird anomaly for people to be puzzled by.

**Comment by chaosvolt** [comment]
Hmm. Possible. Overwriting terrain would work, but it could only be functionally disguised as dirt, grass, or mundane equivalents in ASCII mode. In tiles mode it would still look fungal.

Removing the "FUNGUS" flag from the respective terrain items is a good step though. Or...hmm. a replacement table? O.o

**Comment by Coolthulhu** [comment]
Now that I think about it, replacement table would probably be an overkill: you'd have to define a json for terrain replacement, load it and implement it where relevant (`map::ter_set`).
For someone who understands the DDA json system (its internals) it could be as little as 5 minutes of work, but learning the json system could well be 1-2 hours otherwise.

You could leave the weird fungal terrain for now. It would be a good idea to override fungal fruits, though.

**Comment by DavidKeaton** [comment]
why not simply add an if statement in mapgen, and delegate fungal to dirt? it's a hack, sure, but it would still work.

**Comment by chaosvolt** [comment]
And back, was dragged out so I'm on the laptop.

Might remove the fungal effect from fungal terrain, and the ability to harvest marloss berries, as a good stopgap measure.

**Comment by Coolthulhu** [comment]
Don't hack stuff up, please. Mapgen is quite ugly already.

If fungal terrain is that evil, it would be better to rewrite the fungal sections of mapgen with jsons.

Oh and another thing to override: fungal infestation effect. Not sure how to fix that one, though. It is hardcoded, but maybe there is a way to have it auto-remove with jsons alone. Even in the absence of real fungi, it can be caused by teleglow.

**Comment by DavidKeaton** [comment]
fair enough, mapgen is an ugly son of a bitch, I can respect that statement.

**Comment by chaosvolt** [comment]
Hmm. I did try mapgen overwrites and it didn't really work. :V

**Comment by Coolthulhu** [comment]
That's because you can't always overwrite C++ sections of mapgen, only the json ones.

**Comment by chaosvolt** [comment]
As I figured from the fungal mapgen entries not being in the mapgen folder. 'w'

**Comment by tyrael93** [comment]
The way I did it I just removed any mentions of fungaloids from monster species, map specials and monstergroups, takes me thirty seconds. I mean, I have no idea how coding a removal works but couldn't you just do that

**Comment by chaosvolt** [comment]
Already got the monsters on a blacklist that makes them not exist, I'm mostly trying to figure out how to dummy out the mapgen effect. It's really just cosmetic, but still.

**Comment by tyrael93** [comment]
removing the mapgen should be a must, it'd just make getting mycus easymode.
Not that mycus is strong or a good mutation tree anyway, it's just that it'd be fairly easy to get free water/food out of  mycus fruit.

**Comment by chaosvolt** [comment]
Heh. Already accounted for that, added an edit to terrain.json that makes marloss plants unharvestable, and makes all fungal terrain harmless.

So while I've yet to figure out how to purge what little's left with modding, I can at least neutralize it.

**Comment by tyrael93** [comment]
Well, that looks good then. Hope you find a way around this.

**Comment by chaosvolt** [comment]
I could even add a overmap_terrain file that makes the now-harmless fungal zones show up as fields, and simply hope players don't stumble upon them to witness my fails. :V

**Comment by Coolthulhu** [comment]
Why did you remove the fungal flag from the terrain? Does it spawn spores through the blacklist?

**Comment by chaosvolt** [comment]
Hmm. It potentially could, though I'll need to test whether it will in spite of this. Mostly a precaution. Now if I could instead figure out how to get the fungal zones removed entirely...

**Comment by chaosvolt** [comment]
Now, the question remains...to keep trying to find a way to get around the hardcoded fungify functions that create fungal regions, or to simply add an overmap_terrain that disguises the modded fungal zones as fields?

**Comment by chaosvolt** [comment]
Wait. Wait. WHAT.

I think I might've fucked something up entirely. Einen moment.

**Comment by DavidKeaton** [comment]
Coolthulhu was right, let's not hack up mapgen, so hide it if there isn't a better way.

**Comment by chaosvolt** [comment]
What would be the best way to hide it then? ;A;

**Comment by Coolthulhu** [comment]
Best would be to move the mapgen functions that generate those areas from c++ to jsons and then blacklisting those.

Having some weird terrain is acceptable - better than having hacks in mapgen.

**Comment by chaosvolt** [comment]
If we had that option... :V

**Comment by Coolthulhu** [comment]
It's always an option, it's just that it takes some work.

**Comment by chaosvolt** [comment]
True. Might be beyond the scope of this PR, or at least beyond the scope of my ability to not break things.

**Comment by DavidKeaton** [comment]
Porting to json would def be in it's own PR. I wouldn't mind tackling it, but I seriously have to get that item rework in.

**Comment by chaosvolt** [comment]
Ah. For now this mod has the fungal terrain not harvestable for marloss, so that's a start. Still, it's weird that I can't simply use overmap_specials to blacklist the mapgen. O.o

**Comment by DavidKeaton** [comment]
It could very well be hardcoded, hence why you can't

**Comment by chaosvolt** [comment]
Possibly. It does have entries in the overmap file though. The more likely cause is that none of the properties overmap_specials lets you play with can be used to dell it to not generate a pre-defined area. Occurrences, for example, doesn't seem to accept "0" as a maximum.

**Comment by Coolthulhu** [comment]
What happens when you change the "overmaps" field in overmap_specials.json?

**Comment by chaosvolt** [comment]
Nothing, sadly. Replacing with a field or crater has no effect, nor does trying to move the fungal terrain underground.

I can't tell if that's a failure of overmap_specials or because the functions in the source create the terrain on the spot.

**Comment by vache** [comment]
Are you sure you fully recreated the overmap?

**Comment by chaosvolt** [comment]
Had actually just copied the overmap entries for the three fungal zones. Which...didn't work. ._.

**Comment by chaosvolt** [comment]
Well. After more thorough testing involving screwing with overmap_specials.json and using a fresh world in each test, I have officially proven that fungal regions give zero fucks about what the overmap file says.

Tell it to use 0/0 occurances? No. Tell it to spawn below ground level? Nein. Tell it that it has to be a minimum of 9001 map tiles from a city? Nyet. Give it the unique flag? Nej. Tell it to connect to a ROAD? Nachi.

**Comment by BevapDin** [comment]
Well, turns out, you can't overwrite the "type": "overmap_special" entries in JSON because they are put into a vector, each new entry is appended, its ID is essentially ignored.

That means if you make a new "overmap_special" with the same ID as an existing one, it will simply add the new the one, but the existing entry will be still be used. The fungal spawns you see on the overmap come from the original special definition. Your own special definition (in the mod) is loaded and considered, but does not spawn, which is essentially what you want.

I'll look into a solution for this.

**Comment by chaosvolt** [comment]
As I suspected.

One additional curious anomaly is that the "id" section in the overmap special entries is written in name format instead of id format. That is, it uses capitalization instead of all lowercase, and uses spaces instead of underscores. May or may not be relevant. Probably not.

**Comment by Coolthulhu** [comment]
BevapDin's update for overmap specials landed. They can be overridden in mods now.

**Comment by chaosvolt** [comment]
Ooh, neat. Will test it out real quick. ^^

**Comment by chaosvolt** [comment]
Fuck. Are you sure if it's in the latest compiled version (3368, cf3ca08)? Because well...still not working. ._.

**Comment by BevapDin** [comment]
How did you test it? I tested this by adding a simple copy of a definition taken from overmap_specials.json to mod, I only changed "location" to `["never"]`.

**Comment by chaosvolt** [comment]
Ah. I started with simply changing occurrences to 0/0. It seems that removing the overtmap and location entries also worked. ^^"

**Comment by Zireael07** [comment]
VERY glad to see this!

**Comment by chaosvolt** [comment]
Meep. Bloody thing didn't update to show that this did a thing. Thank you for the merge.

**Comment by kevingranade** [comment]
Possibly the terrain adjustments are redundant since the overmap features don't spawn anymore, but that's not really a problem.

**Comment by chaosvolt** [comment]
They will appear for those portals that spawn fungi around them, though. Other than that, don't think they'd appear anywhere else.

**Pull request merged**
