### PR TITLE
Crafting flood fill (Please ignore git issues I don't know how to resolve, making new PR)

### PR DESCRIPTION
**Pull request by jmattspartacus**
Please see
https://github.com/CleverRaven/Cataclysm-DDA/pull/30444

It has the code I believe should be ready to merge and use

### How to use
Activate the crafting menu, and see if the crafting menu includes all things within 6 tiles that are not blocked off by impassible tiles, or spaces without floors 

#### Summary
```Summary: Features "Crafting inventory now uses flood fill search"```

Makes the search for items for the crafting inventory use a flood fill for the search rather than only looking for items that are within 6 tiles in a straight line.

#### Purpose of change
When crafting, it's nice to have things in organized containers, but with the current search, it makes it so everything either has to be on the floor, or directly in sight. With a flood fill, it's possible to organize crates or shelves in rows, and provided they are within range, the item will be added to the crafting inventory.

#### Describe the solution
This flood fills tiles, starting from the player's location across the entire reachable area that is passable, and then if the location is found, the items in them are added to the crafting inventory.

#### Describe alternatives you've considered
I've considered hooking into the pathfinding code, but I'm not sure it's the right choice for this, as I don't understand all of the code there.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm having to guess here, so please fill in the details, this is so you can use tools and materials that are reachable but currently out of sight?

**Comment by jmattspartacus** [comment]
> I'm having to guess here, so please fill in the details, this is so you can use tools and materials that are reachable but currently out of sight?

Yes, but only if they are within 6 steps of the player. I think I have it working to some degree with the commit I'm about. I apologize if I wasn't exactly concise with my wording.

**Comment by jmattspartacus** [comment]
Forgot to astyle, don't merge till I do that

**Comment by ifreund** [comment]
Have you profiled your changes?  `inventory::form_from_map()` is fairly performance critical afaik.

**Comment by ifreund** [comment]
Also, you'll need to fix your summary line format.  The required format is:

SUMMARY: Features "Brief description here."

**Comment by jmattspartacus** [comment]
> Also, you'll need to fix your summary line format. The required format (as seen in the pr template) is:
> 
> SUMMARY: Features "Brief description here."

Done

**Comment by jmattspartacus** [comment]
> Have you profiled your changes? `inventory::form_from_map()` is fairly performance critical afaik.

Thanks to OrenAudeles

Both of these are with range 6, for form_from_map
```
[WITHOUT FLOODFILL]
711980 ns :  inventory::form_from_map
723980 ns :  inventory::form_from_map

[WITH FLOODFILL]
  766359 ns :  inventory::form_from_map
14860451 ns :  inventory::form_from_map
16474096 ns :  inventory::form_from_map
12344397 ns :  inventory::form_from_map```

For the data with floodfill
" The first sample is in the middle of a street, nothing around. the rest are in various locations where your flood should be kicking in."

**Comment by jmattspartacus** [comment]
With a range of 20, the performance hit gets even worse, I'll have to work on this some more.

**Comment by jmattspartacus** [comment]
After changing the way that I approached the problem, it will now provide the crafting inventory at range = 50 in between 1 and 5 seconds, depending on surrounding terrain. 

At range =20 (the case of interest since the camp inventory calls for this), it responds almost instantly on my PC.

At range = 6, there's not a real discernible difference between and this and the current approach of form_from_map.

Please feel free to test/break/etc and let me know if there are any improvements I can make.

**Comment by jmattspartacus** [comment]
> Old saves now crash when you come close to the refugee center...
> I had to edit my savefile to add the new faction to it...

I think you're posting in the wrong place about this. You should head to issues and post an issue there.

**Pull request closed without merging**
