### PR TITLE
Fix ratio for lye to lye powder

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
As noted in issue #22406, creating lye powder from lye is inordinately expensive, requiring 40 lye for one completion of the recipe (200 lye powder), or approximately 125 logs worth of wood ash. After several hours of research, I believe I have figured out the problem. 200 lye powder weighs 200 grams, while 40 lye weighs 4.8 kg -- this puts the solution strength at about 4%. This is extremely low, the most commonly used lye solutions are generally between 25% and 33%. Therefore, I altered the recipe to require only 6 lye, putting it at about 28% strength.

Of course, since the current soap recipe requires either 2 lye or 10 lye powder, I had to change it in order to maintain consistency. I elected to simply remove the lye powder option entirely -- mostly because of realism (you would have to reconstitute the lye powder into lye anyway if you wanted to make soap).

Because crafting soap directly from lye powder is no longer available, I added a simple and quick recipe to reconstitute lye powder -- 1 lye from 35 lye powder and 1 water.

I did not touch recipe times; it didn't seem necessary to fix the issue, and any changes I could have made seemed arbitrary.

Final note: I considered removing the recipe for wood ash, since just burning wood yourself is now far superior in every way, but it seemed out of the scope of this PR, so I refrained. I suppose I will make an issue for it.

### CODE REVIEW

**Comment by DaviBones** [comment]
Fair enough, that makes sense. The redundancy of needing water even if you're using lye instead of lye powder will irk me a bit, but water is basically free so it's excusable.

**Comment by Night-Pryanik** [comment]
No, you don't need water if you are using lye. Water should be needed only if you are using lye powder.
Like (lye) or (lye powder and water).

**Comment by Night-Pryanik** [comment]
Oh, my bad, sorry. I imagined that we already have this type of syntax.

**Comment by DaviBones** [comment]
Yes that was my thought process, may as well just have the one recipe... I mean, water isn't _always_ free, but if you find yourself crafting soap of all things with a limited water supply, you have a very strange set of priorities :smile:  I will say though, it would be cool and useful if we had that syntax. Perhaps eventually.

If anyone else has any suggestions/objections I'm happy to make more changes, otherwise this should be ready for merging.

**Pull request merged**
