### PR TITLE
Innawoods tailoring and misc fixes

### PR DESCRIPTION
**Pull request by Sathra225**
#### Summary
Mods "Innawoods tailoring fixes"

#### Purpose of change
Innawoods uses its own tailoring and materials requirements JSON due to fibercloth, so they needed to be updated to mainline numbers. As an example, a gambeson in mainline needs 80 cotton sheets, without this change it needs 1760 cotton or fibercloth sheets in Innawoods.

#### Describe the solution
Changed the relevant numbers in the files.

#### Describe alternatives you've considered
None. Numbers fix.

#### Testing
Made changes, quantities in Innawoods match those for mainline.

### CODE REVIEW

**Comment by Sathra225** [comment]
And yes, the commit history is a mess but not sure if trying to fix it will break my current PR's

**Comment by NetSysFire** [comment]
I would git reset --soft 3b95bad9efe8106bb8dcfc63af9ce1e254c742d6, git commit and then force push.

**Comment by Sathra225** [comment]
Yeah, its the force-pushing I'm concerned about breaking this and the camphine PR's

**Comment by NetSysFire** [comment]
I do not see how that would break the PR. However, anyone merging this should squash regardless, so there is only one commit showing up in master later.

**Review by Light-Wave — APPROVED** [review]

**Comment by Sathra225** [comment]
Adding Fibercloth material and updated weights of cotton (material) and fibercloth sheets to be in parity with mainline. The fibercloth material change is to allow items made from fibercloth sheets to salvage into cotton patches instead of deleting.

I did consider making a range of fibercloth patches and scraps, but at this point in time it wouldn't actually do anything but add item bloat as fibercloth is cotton sheets made from plant fiber.

**Comment by Sathra225** [comment]
Was informed that plastic from chitin wasn't possible anymore due to lye changes, so added potassium lye as an alternate 
 deacetylation chemical at a higher amount.
Data from here: https://pubmed.ncbi.nlm.nih.gov/21700271/
Also fixed up time of crafting fibercloth using spinwheel to the same as cotton sheets.

**Review by Light-Wave — APPROVED** [review]

**Pull request merged**
