### PR TITLE
Fixed canning ratios for tomatoes / fruit / liver / red sauce

### LINKED ISSUE #37504: Canned fruit, canned tomatoes and canned livers not filling the right amounts
# Describe the bug

Canned fruit and canned tomatoes only fill the containers halfway and the canned liver is twice the amount the tin can should be able to contain

# Steps To Reproduce

1. need level 5 or higher cooking, tools with metal sawing 1 or higher, hammering 1 or higher, cutting 1 or higher, food cooking 3 or higher, some form of heat source for cooking, can sealer, canning pot, 3 scrap metal, 3 small opened tins, 2 glass jars, 2 3L glass jars, 30 of a fruit, 8 raw livers, 15 tomatoes and 54 water or clean water
2. Shift + 7 for crafting menu then shift +f search either canned fruit, canned tomato or canned liver (for canned liver only the small tin can version seems weird)
3. craft whichever item you picked.
4. check max amount container could hold vs what is in container.

# Expected behavior

for the livers either make a 4 liver recipe using the small tin can or use the medium sized tin can for the 8 livers since its double the size. for the canned fruit and tomatoes either double the amount put into the container or half the amount of fruit and tomatoes it says the containers can store.

# Screenshots

food containers

# Versions and configuration

  - OS: Windows
    - OS Version: Windows 7 Ultimate
- Game Version: 0.D-11709-g9d46c12 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context

not putting in a save in for this one cause of how messy i made my save checking pretty much every can sealer and canning pot recipe i saw

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Content "Fixed canning quantities and ratios for tomatoes / fruit / liver / red sauce"```

#### Purpose of change
Fixes #37504 and fixes some water and ingredient ratio problems.

The description in #37504 was accurate for tomatoes/fruit/liver. I also noticed that water ratios were inconsistent for tomatoes and red sauce (anywhere from 1:2 to 3:1) based on size of container, and the sugar ratio for fruit in a jar was inconsistent (5:1 sugar:fruit, where small can and 3L jar are 7.5:1).

There are numerous other inconsistencies in canning ratios in other recipes that I noticed, I'm going to open a separate issue for that to work on in the future.

The small canned tomato recipe also did not allow for irradiated tomato while the other recipes did, so I fixed that as well.

#### Describe the solution
Changed the input and output ratios for the different sized canning recipes for tomato, liver, fruit, and red sauce.

#### Describe alternatives you've considered
Either not doing anything or waiting until a larger canning overhaul can be done. Several other canning recipes need to made consistent between sizes and ratios.

#### Testing
Replicated all the cases cited in #37504, and also tested the ratios for red sauce, sugar, and water before and after the update.

#### Additional context
As stated, I'm opening a new issue for taking a pass over all the canning recipes.

### CODE REVIEW

**Comment by jkraybill** [comment]
Urgh, got my first real test failure. Based on my conversation with @ifreund on Discord, and the numbers I ran, the default calories for canned fruit (367) was just simply way too high -- in the game, hand canning gets results ranging from 183 cals per serve (canned cranberries) up to 296 (pomegranate), so I set it down to 240 which I believe will pass the tests and be a saner value. Nerfing found canned fruit caloric content wasn't the intent of this commit, but I believe from my chat that is the right thing to do. I suppose an alternative if that's not desirable would be to bump up the input requirements for canned fruit by 50%?

**Comment by I-am-Erk** [comment]
This might be a good candidate for [cooking requirements](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/requirements/cooking_components.json). If all canned fruit is using the same sugar requirement, you could do a requirement like "simple_syrup" and put the sugar and water for a single batch in there, requiring multiples for 3L batches. That way if we decide to adjust simple syrup, we can do it for all canned fruit recipes at once.

You don't *have* to do it in this PR, but if you're going to continue to do these kind of fixes, Requirements sets for cooking would be very good.

**Comment by I-am-Erk** [comment]
Merge conflict needs resolving

**Comment by jkraybill** [comment]
I'm closting this and going re-open with a new PR in the next couple days. Based on a comment in another PR I need to take another pass at the water ratios because some of them were deliberately "inconsistent" (e.g. the canning jar recipes should use a lot more water, for canning).

**Pull request closed without merging**
