### PR TITLE
[Ready] Delete README.txt from makefiles

### PR DESCRIPTION
**Pull request by mnacamura**
For https://github.com/CleverRaven/Cataclysm-DDA/pull/14088

### CODE REVIEW

**Comment by illi-kun** [comment]
Thank you. I didn't expect to see text file in makefile, my bad.

**Comment by mnacamura** [comment]
My pleasure.
I don't know why the auto-run test failed, but I think it is ready to be merged.

**Comment by illi-kun** [comment]
That's okay. Test is disabled for PRs which are targeted on makefile changes for safety/security reasons.

**Comment by mnacamura** [comment]
I see.

**Pull request merged**
