### PR TITLE
New scores window replacing kills window

### LINKED ISSUE #8957: Kill count screen cuts off on long-named monsters
Example:
kill count cut off
The monster's name being shown in the example is `giant black widow spiderling`, and as far as I can tell, it probably printed the count (in this case, 5) on the next line, where it got overwritten by the 2 from the `giant wasp` kills.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/4344584-kill-count-screen-cuts-off-on-long-named-monsters?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Replace kills window with new scores window showing additional info"

#### Purpose of change
Working towards #4173.

Fixes #8957.

This provides a new, more convenient means to see the newly added scores during play, rather than only after the game is over.

#### Describe the solution
Replace the existing "kills" screen with a new tabbed window.  One tab for scores and another for kills.  I anticipate that achievements will be in a third tab when they are added.

Added a couple of generic GUI features to help this:
* A `new_centred_win` function for creating a window in the centre of the screen.
* A `scrolling_text_view` for scrolling through arbitrary text.

Also, because the calculation of some scores can easily go wrong if the game was started before the scores existed, now scores will only be reported if you started the game with them already in place (this applies to the memorial log too).

#### Describe alternatives you've considered
I would like to use the new GUI features in more places.  I tried to find other instances of scrolling text, but most places with a scroll bar actually scroll based on a selection within the window, not just scrolling the view, which is a bit different.  In the end I didn't find any other uses.

There probably are places to use `new_centred_win`, but I didn't want to delay this PR further by finding them.

The kills are now listed in a single column rather than three.  I could have still used multiple columns, but I've seen some monster names get too long for the columns, and I didn't want to add too much complexity there.  Also, I'm imagining it might be fun to add some other info like the first and last kill times for each monster type to widen that data a bit.

The scores could do with livening up with some colour, but that can go in a separate PR.

#### Additional context
scores-kills
scores-scores

### CODE REVIEW

**Comment by KorGgenT** [comment]
neat! how do the kills display with stats through kills?

**Comment by Night-Pryanik** [comment]
Should also close #8957 - at least if monster's name isn't too long to not fit even with one column.

**Comment by Night-Pryanik** [comment]
While you're working with the windows code, I suggest increasing window size. Currently there is TOO much free, unused space, especially on big resolution monitors.
изображение

**Comment by jbytheway** [comment]
> While you're working with the windows code, I suggest increasing window size. Currently there is TOO much free, unused space, especially on big resolution monitors.

I thought about this, and it would be easy to do, but right now I feel like there really isn't any need to make the window bigger.  It could dynamically size, although that's a bit tricky for a tabbed window because if it's sized well for one tab it might not be for another.  Do you (or anyone else) have any specific ideas about what approach makes the most sense here?  I don't have much UI theory background.

**Comment by jbytheway** [comment]
> neat! how do the kills display with stats through kills?

scores-kills-stk

**Comment by Night-Pryanik** [comment]
> Do you (or anyone else) have any specific ideas about what approach makes the most sense here?

I do. Many menus' (like kills count, missions, message log, sidebar options etc) dimensions are fixed and don't scale dynamically according to the actual monitor resolution. What's worse, the are based on terribly outdated 80x24 dimensions. As such, I propose to get rid of this obsoleted stuff and make menus' dimensions scale dynamically - I provided one example above. However, with your new one-column style instead of a old three-columns style there might be too much free space inside the menu itself. So we need to approach carefully to each case.

**Comment by ZhilkinSerg** [comment]
Let's merge it as it is and increase window size later.

**Pull request merged**
