### PR TITLE
Update 40mm.json

### PR DESCRIPTION
**Pull request by Leviathan21**
SUMMARY: Bugfixes "Update description of 40mm shells."
 #28457

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Add a `SUMMARY: Bugfixes "Update description of 40mm shells."` or something like that to your OP.

**Comment by Leviathan21** [comment]
done

**Comment by kevingranade** [comment]
> It's not a shotgun though, it's a flechette round for a grenade launcher.

**Comment by Leviathan21** [comment]
yet it have function of shotgun

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Pull request merged**
