### PR TITLE
Give Bra for female computer hacker profession

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Gives bra to female computer hackers"

#### Purpose of change
no more topless female computer hackers

#### Describe the solution
gives a bra to female computer hackers

#### Describe alternatives you've considered
uhh

#### Testing
No testing really needed but i did get in the game and check if the bra was shown in female computer hacker profession, and it did.

### CODE REVIEW

**Comment by NetSysFire** [comment]
You need to fix your PR summary https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#all-prs-should-have-a-summary-section-with-one-line

**Comment by Devengel** [comment]
Fixed, Sorry! new to github and a bit of a pleb when it comes to this sort of stuff.

**Comment by Zireael07** [comment]
Not fixed, you just nuked your branch (And this PR along with it)

**Comment by Devengel** [comment]
> Not fixed, you just nuked your branch (And this PR along with it)

Sorry forgot to comment, i did fix it, but i also nuked it to let someone in discord contribute and fix it, so they learn the ropes of contributing (since they discovered it first, and i never mentioned about going and fixing it myself, didnt want them to waste all the effort of reading docs, installing & compiling for nothing)

**Comment by NetSysFire** [comment]
There are enough good first issues they could learn the basics with.

**Pull request closed without merging**
