### PR TITLE
Show compatible ammo for magazines

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Describe the solution
More to come just wanna see test results 

#### Additional context
image
image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Please make sure that blacklisted ammo types from mods won't show up in this info.

**Comment by bombasticSlacks** [comment]
> Please make sure that blacklisted ammo types from mods won't show up in this info.

I checked it with Generic Guns and it worked. Are there any other mods that would be good to check?

**Comment by Night-Pryanik** [comment]
AFAIK there is no magazine-blacklisting mods in the repo, so I guess to test this case it's required to create a mini-mod and blacklist some magazine.

**Comment by Zireael07** [comment]
Something went wrong? 230 hidden commits?

**Comment by bombasticSlacks** [comment]
>Something went wrong? 230 hidden commits?

yeah I messed up and merged before force pushing gonna clean it up after a work meeting

**Comment by Fris0uman** [comment]
I htink this fails one item info test

**Pull request merged**
