### PR TITLE
Fixes some anesthetic bugs, and makes its description more accurate

### PR DESCRIPTION
**Pull request by ghost**
Currently, narcosis doesn't prevent you waking up automatically if you hear a noise, or if your tiredness would naturally wake you up. I changed this so that noise can't wake you up if you're under narcosis, and narcosis keeps your fatigue from going below 25 so that you never wake up due to being rested.

I also tweaked its description to emphasize that it's not usable manually without machinery, since the previous description of syringes implies manual use.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Thanks for fixing premature waking up from anesthesia bug.

But what's the point of making it usable manually? To make character sleep with no means of waking up for ~4 hours?

**Comment by Xhuis** [comment]
I saw two main reasons:
* Since it's a kit meant for manual use, it was more consistent to allow it to be used manually
* For someone with a lot of the stuff, or with no use for it, it lets them sleep without being interrupted by stuff like a mi-go in a lab beneath them, as well as to force themselves to sleep for an extended period for sleep healing even when they're not tired.

**Comment by Night-Pryanik** [comment]
I know powerful hypnotics used for anesthesia IRL have strong side effects, including death, and that patients require medical monitoring when introduced into anesthesia, that's why people don't use them to sleep on a daily basis.

Well, let's hear other contributors' opinions then.

**Comment by kevingranade** [comment]
Anesthesia is not sleep, it does not reduce mental fatigue and I don't know
how it interacts with healing.  This is something we could overlook when it
is used for surgeries, but if it becomes a sleep aid it needs to be
addressed, along with the potential for death if administered improperly.

**Comment by Xhuis** [comment]
Anesthesia as implemented in DDA is simply normal sleep, but you can't wake up from it early. I wanted a manual option for consistency's sake, but if it's too much trouble I can make this simply a bugfix PR. I'm not sure how anesthetic works, but I'd also be happy to make it more true to life, though I'm not sure how it works.

**Comment by kevingranade** [comment]
Let's just fix the bug for now, and revisit whether there's even a need to have application of anesthesia outside of surgery in another issue.

**Comment by Xhuis** [comment]
I'll update this PR once I get to my desktop, as I am on my laptop right now.

**Comment by Xhuis** [comment]
Manual use mechanic is scrapped.

**Pull request merged**
