### PR TITLE
Jump to item's recipe

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
I was inspired by #52669 to add this neat QoL feature:

https://user-images.githubusercontent.com/12537966/140634070-fb220d93-e79c-449c-a7da-f08f04855446.mp4

#### Describe the solution
On the item info screen, you can press `V` or select the "view recipe" option to jump to the item's crafting recipe.

You can even view the recipe of in-progress items!
progress_info
progress_craft

For items that don't have crafting recipes, the option is gray and selecting it lets the player know there's no recipe:
towel_info
towel_craft

For items that have crafting recipes which the player doesn't know yet, the option is red and selecting it informs the player:
cargo_info
cargo_craft

#### Describe alternatives you've considered
Adding information about in-progress items to the info screen, although it's pretty cluttered already.

#### Testing
(See screenshots above)
1. Test items that have no recipe -> does not open crafting window
2. Test items that have undiscovered recipes -> does not open the crafting window
3. Test items that have known recipes -> opens the crafting window at the specified recipe
4. Test in-progress crafts -> opens the crafting window at the recipe of the final product

### CODE REVIEW

**Comment by dseguin** [comment]
According to Clang-tidy, `select_crafting_recipe()` is too complex, which apparently means there are too many variable declarations. Half of this PR is moving stuff out of that function.

**Comment by PatrikLundell** [comment]
I think it also needs to be tested for things that have more than one recipe. I believe there is a bunch of different recipes for making flour using different tools to make it take different amounts of time (I think mortar-and-pestle and quern are among the tools).
There's also the case of dedicated companion recipes for base camps (e.g. using the drop hammer in the workshop expansion). I think all of those produce things the PC can produce as well (but slower), but can't swear on it. You'd want to make sure the recipe you present in those cases is the (or a) PC one, not a companion one.

**Comment by dseguin** [comment]
Looks like neither of those cases are an issue. Only the first available matching recipe is selected. Recipes are pulled from the same list as the regular crafting screen (`&`), so anything that's not in that list is not matched (ex: companion recipes).

**Comment by martinrhan** [comment]
Other than "what is item is made of", its also going to be nice to add "what this item can be used to make"

**Pull request merged**
