### PR TITLE
Rebalance the infection resistant mutation

### PR DESCRIPTION
**Pull request by i2amroy**
Whoever added this number obviously wasn't quite as familiar with how exactly binomial probabilities work. As is someone with the infection resistant mutation will heal from a bite wound (before it ever becomes an infection) 97.5% of the time, with the overall healing rate of bites + infections at 99.69% (as compared to the 46.84% chance without the resistant mutation). That's not "resistant", it's "immune" under another name.

This PR drops the chance down to a 63.26% chance of healing in the bite stage, with a cumulative healing chance of 84.53% in the bite and infection stages combined. It's still almost double the non-resistant chance, but it's not a get-out-of-jail free card until it actually upgrades again into the full-immune mutation. I also took the opportunity to include some helpful percentage chance calculations in the comments for those who are thinking about balance. +/-200 are the effective maximum and minimum health values a player can possibly obtain, even assuming they totally abuse something that adds or subtracts to their health.

Also thanks to stattrek.com for their very handy binomial probability calculator that I used for almost all of my calculations involved in this.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
But this nerfs the trait into uselessness. Drop point value to 1 maybe?

**Comment by i2amroy** [comment]
Uselessness? It drops the combined heal down from 99.6% to 85%. With a 63% chance of not even reaching the stage where you need to worry about permanent effects! (That's basically a 40% less chance of suffering from lasting bad effects). I fail to see how having a better than 4 in 5 chance of not needing any medicine at all is "useless" compared to a less than 50/50 one.

Number wise with this you would treat bites by waiting till they were just about at the infection stage, then treating them if they haven't healed yet (since with the mutation you have a 63% chance of healing before it reaches that point).

This trait raises the chance of you not needing medicine from a 50/50 crapshoot to a "most likely you won't need medicine at all" state. Your chance to heal before suffering any serious effects with the mutation is greater than your total *combined* chance to heal at all without it.

And if anything I'd say that right now by having it as it is makes it so the immunity upgrade should be worth zero extra points on top of it's cost, because it literally does *nothing* that this doesn't already do.

And if you'd like to point out that most people cauterize bites, I'd respond by saying I'm currently working on a PR to change that. Cauterization is literally one of the *worst* things you can do to a wound in danger of becoming infected, and the fact that it can heal bite wounds at all is ridiculous.

**Comment by Coolthulhu** [comment]
It's not just cauterization - disinfectant is common enough for the trait not to matter, except for the "infected" background.

I can't really tell how will it look after bite removal nerf, but at the moment the current 99+% chance of recovery still isn't enough to make the trait worthwhile for anyone but infected/bad day survivors.

The infection immune trait has its own problems (namely that it's crap), but it doesn't have the whole noob trap aspect as it can't be picked at start.

That's why lowering the point value (to 1, not 2) here would be useful. It is - even before the nerf - not worth picking over pain resistant, gourmand or optimist, except in the case of infected start. And it becomes obsolete very quickly (as soon as the first first aid kit drops).

**Comment by karlnp** [comment]
I wouldn't say that disinfectants are common, except if you mean statistically because I haven't looked at the drop tables.

**Comment by i2amroy** [comment]
Hmm, point there, though don't forget that this isn't solely just a "pick at start" trait. It's also part of the medical, rat, and troglobite mutation lines.

**Comment by macrosblackd** [comment]
I would suggest maybe rolling disease resistance and infection resistance into a single trait (name it something to do with the immune system) and balance the point cost around that.

**Comment by Coolthulhu** [comment]
Gained mutations should actually be stronger than the starting ones.

If you think 1 point is too low, making it provide resistance to some of the effects of infection could help with making it worth 2 points. Making it affect pain and stat debuffs in similar way poison resistance affects poison.

One of the biggest problems with infection is the constant pain which blocks all sleep and makes crafting a pain.

**Comment by i2amroy** [comment]
That seems like a pretty good solution to me, and shouldn't take too much extra work to implement, just a fairly simple JSON change. How about a middle road, drop the point cost a little (down to 2?) and give it the ability to reduce some of the more disabling effects of an infected wound, as well as mention that it increases your chance to heal on your own to help educate players about all of it's effects.

**Comment by Rivet-the-Zombie** [comment]
>Whoever added this number

That would be me. Sorry!

**Comment by i2amroy** [comment]
>That would be me. Sorry!

No problem. We caught it, and it was probably at least my fault for not documenting exactly how I got to those numbers well enough. :P

**Comment by i2amroy** [comment]
Dropped cost down to 2, added a variety of resistance effects (which won't be noticeable until #13010 goes in).

>One of the biggest problems with infection is the constant pain which blocks all sleep and makes crafting a pain.

I think the sleep part of this is more of a problem with the sleep v. pain mechanic. In reality only large spikes of pain would make you wake up (though damage should always wake you up); in general low level pain should just make your sleep less restful instead. I'm currently cooking up a separate small PR to change that a bit, which should make the low level pain caused by this (and other effects) much less debilitating.

**Comment by kevingranade** [comment]
Note that any effects that bypass the 'melee' type damage functions now
avoid triggering wakeup if pkill is greater than the pain.

**Comment by i2amroy** [comment]
>Note that any effects that bypass the 'melee' type damage functions now
avoid triggering wakeup if pkill is greater than the pain.

I haven't touched any of that stuff in this particular PR. The other PR that I'm currently working on does it based on size of the amount of pain given at once (though the pkill thing is definitely something that I should make sure to do as well).

As for the effect damage, I'm not sure why they would avoid triggering wakup on damage if you're seeing that. They call apply_damage(), which calls on_hurt() which calls wake_up(); just like any normal damage source.

**Pull request merged**
