### PR TITLE
Added charges to camp fire drill

### LINKED ISSUE #25503: I can't seem to start my charcoal kiln correctly with my regular Fire Drill that has 27 charges
**Describe the bug**  
I examine my kiln with fire drill in hand and don't get the option to light the wood inside it on fire. I have a pic but I'm not sure if this is a bug or not. Is the (fire drill) (50 charges) not considered a fire starter for the charcoal kiln? I don't have any other fire starters

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version [Tiles or Terminal]
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Bugfixes "Added charges to camp fire drill"```

#### Purpose of change
Fixes #25503
Fire drill and camp fire drill are similar items. One is smaller, one is bigger and more efficient, but fire drill has 50 charges and camp fire drill has no charges. This is ok for fire starting but it breaks the logic behind firing items like kilns, that want to consume a charge. This fixes that by adding charges to camp fire drill. Since it is more sturdy by design it will work longer then basic drill, thus 100 charges. Also to differentiate it from fire drill.

#### Describe the solution
Simple json fix.

#### Describe alternatives you've considered
Alternative was changing the logic to include perpetual fire starters, but with 100 charges camp fire drill usefulness is already long, so no need to go that far.

#### Additional context
N/A

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
The camp fire drill used to have a lot more charges than the fire drill to make up for its size - something like 500 or so.

**Comment by nexusmrsep** [comment]
Considered it, but that would pretty much make it infinite-like, and it is easy to fabricate again when depleted, so I went for a lower number. 100 fires are already a big number.

**Comment by Kelenius** [comment]
But it's infinite currently.

**Comment by nexusmrsep** [comment]
I'm not gonna strictly defend number of charges here for no reason, so 500 it is.

**Pull request merged**
