### PR TITLE
Crossbows/archery.json linting

### PR DESCRIPTION
**Pull request by darktoes**
#### Summary
```SUMMARY: Infrastructure "Minor linting of json files"```  

#### Purpose of change
For some reason every line in these two files had two more spaces than it should have as per the standard linting tool at: http://dev.narc.ro/cataclysm/format.html

#### Describe the solution
Ran both files through the linter in full, copy-paste.

#### Describe alternatives you've considered
Go insane adding two spaces to every single line I add to these files as I've done thus far.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
You would like to remove linted files from https://github.com/CleverRaven/Cataclysm-DDA/blob/master/json_blacklist.

**Comment by darktoes** [comment]
I don't really know what you mean, do you want me to remove the two files I linted from that list?

**Comment by AMurkin** [comment]
Yes. Do it. They not blacklisted anymore.

**Comment by darktoes** [comment]
All done, but I'll admit I don't really understand what that blacklist is for.

**Pull request merged**
