### PR TITLE
Partial mine jsonify; new zombie miner

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "Partial mine jsonify; new zombie miner."

#### Purpose of change
Mine in general and mine entrance in particular are very old, are hardcoded, and has very primitive and unrealistic design.

#### Describe the solution
- Created json-variants of mine entrance and mine shaft parts of the location. Replaced old hardcoded counterparts with new layout in mapgen.
- Added a zombie miner monster. It's basically a weaker version of zombie technician, without `PULL_METAL_WEAPON` and CBM harvest. It has its own drop list, most notably there's almost guaranteed miner's hat drop. It seems a little bland at the moment, but we make it somewhat more interesting in subsequent PRs, as this PR is focused on jsonify, not on monster balance.
- Mine tunnels and mine finale are still hardcoded.

#### Describe alternatives you've considered
None.

#### Testing
Due to its weird part-hardcode part-json nature, mine location is rather difficult to test, as you have to find it naturally in the world. If you debug-spawn the location, hardcoded tunnels won't generate.

#### Additional context
Before: a set of random unconnected and boring rooms with minimal sense and loot
изображение

Before: sometimes it's just one room with literally nothing of value
изображение

After: full-fledged mine location with office, housing, storage, and fuel sections.
изображение

Before:
изображение

After:
изображение

Before: mine shaft makes little sense as ladder positions are fixed yet manhole position on the ground level is randomized
изображение

After: ladder positions are perfectly aligned with both ground and underground levels.
изображение

### CODE REVIEW

**Comment by Xenomorph-III** [comment]
Would this change the Mine scenario in any way? Like the point cost, due to the cooler loot and base potential?

**Comment by Night-Pryanik** [comment]
> Would this change the Mine scenario in any way? Like the point cost, due to the cooler loot and base potential?

I haven't thought about it. In this scenario you start in the tunnels, and tunnels ain't changed at all (yet). Base has cooler loot, but it's guarded by zombie miners, so they should compensate each other. I don't know, maybe a +1 or -1 point.

**Comment by Venera3** [comment]
You can up its spawn rate in specials.json to ease the testing and/or do mine starts to get a guaranteed spawn.

**Comment by Night-Pryanik** [comment]
Yeah, I know, thank you.

**Comment by Shodan14** [comment]
Any explosives? That's what I'd look for in mines.

**Comment by Night-Pryanik** [comment]
> Any explosives? That's what I'd look for in mines.

`mine_storage` and `mine_equipment` item groups contains several types explosives, and they both spawn in the location.

**Pull request merged**
