### PR TITLE
Adjust winged zombies to suit lore

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Content "Adjusts winged zombies to fit lore, adds new types"

#### Purpose of change

#42768 adds winged zombies. While I love the idea of flying zombies, I don't think the lore implications of this PR were sufficiently considered before adding it. Zombies can break certain laws of physics, particularly as relates to energy sources and manipulating shape and mass, but something as basic as aerodynamics they should still be beholden to basic physics. The heaviest flying bird on earth is 18kg. A brute with wings shouldn't be flying.

#### Describe the solution
- Winged zombies can't fly, and are generally a major downgrade from regular zombies. They can occasionally make leap attacks.
- Previous 'winged brutes' are now Garghouls, slimmer and more delicate but able to make frequent leaps. In combat they're slow but they should cover ground very quickly and be immune to most of a player's usual bottleneck techniques. I think they'll be a really interesting change.
- Pupated crawling zombies now explode when close to the player, creating a swarm of our first "second generation zombie", flesh-raptors: a creature made by completely redesigning humans into something entirely different but made from our parts. These are, fast-moving, fragile harriers that will mostly be a nuisance, but a hard one to protect against. They can fly. In play they're a bit like nastier manhacks. Raptors, unlike zombies, cannot revive.
- Regular sized zombies can form a pupating version as well, which bursts into a few more raptors.
- In the interest of preserving uniqueness I dropped the leap distance on hunters and predators (which were a little crazy as it was) and put those ranges onto the winged types. Hunters and predators still have deadly leaps but they can't jump halfway across your field of view now.

#### Describe alternatives you've considered
I may add some more types, but I'll save these for a new PR.
- Exploding raptors: I'd like to see them behave like scourge in starcraft. In fact maybe there should be fire, acid, and electric exploding subtypes. The electric ones must necessarily be called zaptors.
- Gasbag zombies: A larger flying zombie as an alternate evo path from the first-gen winged zombie, these would be more like a boomer in appearance and would use their wings to guide their floating direction. I'd love them to explode into a fireball if damaged by something inflammatory.
- Some kind of evolved garghoul that is more threatening in melee. Not yet sure what to do to make them so, as they need to remain light and fast and sort of clumsy.

#### Testing
Plays out pretty good. The garghoul is a little weak: when charging attacks are an option I'd like it to have a strong charging attack to balance it out. It does well with the mobility thing though.

### CODE REVIEW

**Comment by LyleSY** [comment]
Overall this is exciting, but please don't be limited by the little birds we know today when the grand scope of time has shown us wonders.
https://en.wikipedia.org/wiki/Quetzalcoatlus was way bigger and heavier than a zombie brute and it flew across oceans. Great video about that https://www.youtube.com/watch?v=scAp-fncp64
image

**Comment by I-am-Erk** [comment]
It remains hotly debated if Quetzalcoatlus could in fact fly, and that's in a creature with a bodyplan geared toward flight, starting from a cliff. That's a lot different from a humanoid with bat wings starting on the ground

**Comment by aoae23** [comment]
> Some kind of evolved garghoul that is more threatening in melee. Not yet sure what to do to make them so, as they need to remain light and fast and sort of clumsy.

As mentioned in #42768, we could have them attack faster and try to bleed out the player - "death by a thousand cuts".

**Comment by kevingranade** [comment]
It is, but the point stands IMO that many of the limits we're talking about are metabolic rather than based on instantaneous power generation, and metabolic processes are exactly where blobformed mutants get to cheat. They can stockpile energy before transformation, be fed by other zombies, or even receive infusions of energy from *elsewhere*.

I agree that they need an overhauled body plan for full flight, and that Quetzalcoatlus is more of a limit to approach rather than an upper bound to achieve, but I don't see any reason to stick to "The heaviest flying bird on earth is 18kg" as an upper limit considering https://en.wikipedia.org/wiki/Argentavis and https://en.wikipedia.org/wiki/Pelagornis_sandersi weighed in at 70-72kg and 20-40kg respectively.

Having said that, I'm totally fine with the direction you're taking this for now, we can reserve flying brutes that dive bomb from the tops of other buildings for later.

Further refinements we can add:
The opposite of HARDTOHIT, making certain flying creatures "easy to hit relative to their size" to reflect vulnerability of wings.
Explicitly modelling wings as a point where they are very likely to get hit that will cost them their flight ability.
High Wind Advisory effect, perhaps in some adverse weather conditions these threats get grounded.

**Comment by I-am-Erk** [comment]
@aoae23 that's what the raptors do already, and better.

For garghouls I'm thinking about a putrid evolution that rots food, and impedes movement and vision, so their schtick would be getting close to you very quickly and reducing your ability to fight at range.

For raptors, I'm going to work on making them into something like the zerg scourge.

**Comment by Fris0uman** [comment]
> Explicitly modelling wings 

So not yet, but the bodypart rework would allow to give that kind of things to monsters one day.

**Comment by Fallout48** [comment]
> Gasbag zombies: A larger flying zombie as an alternate evo path from the first-gen winged zombie, these would be more like a boomer in appearance and would use their wings to guide their floating direction. I'd love them to explode into a fireball if damaged by something inflammatory.

I read this description earlier and it's been haunting me all day. I like the idea of it, but I can't wrap my head around what it would look like. I keep picturing a grotesque, smelly hot air balloon gracefully bouncing and gliding down the street as it tries to chase me. Like some kind of undead Hindenburg. Or imagine a boomer gliding after you like a plastic bag being carried through the wind.

This is how I'm imagining it. I'm assuming because they're filled with gas they can fly when the basic winged zombies can't, but I don't know if I would be terrified or chuckling at the idea a zombie balloon is attacking me.
cddaflyinggassy

I'm really excited to see what second generation zombies are going to look like though!

**Comment by I-am-Erk** [comment]
For the floater zombies I actually plan to sprite them before I make them, so that I can get the design down, but I imagine they'll be barely recognizable as human. They'll probably be something more like a jellyfish made from human skin.

**Comment by chronicpayne** [comment]
> Some kind of evolved garghoul that is more threatening in melee. Not yet sure what to do to make them so, as they need to remain light and fast and sort of clumsy.

Have you considered doing a shady zombie version with night vision and a limited screech or noise making ability?

Keeps the evolution fast and clumsy and instead allows other monsters to be more effective.  A grabber version would also come to mind, but would have to be very easy to break out of.

**Comment by I-am-Erk** [comment]
Yeah, a shady screeching garghoul would make a lot of sense, especially with how it could leap out of nowhere in the night. That would be lots of fun.

**Pull request merged**
