### PR TITLE
Fix typos in item flags, add runtime item flag validation on loading (part 1 of  #44694)

### PR DESCRIPTION
**Pull request by Aivean**
#### Summary

SUMMARY: Bugfixes "Fix typos in item flags, add runtime item flag validation on loading"

#### Purpose of change

This is the first chunk of changes from #44694.

This part:

* fixes discrepancies and typos in item flags
* adds runtime validation for invalid flags on item loading
* removes obsolete ARTC_ flags and info about them
* add missing item flag definitions into flags.json
* removes `LIGHT_XX` flag after it's used to set `light_emission`
* adds `erase_if` utility method to `cata_utility` and unit test

#### Describe the solution

Found and fixed following flags:
    - ✅ (FIXED) TYPO in flag name `IRREPLACEABLE_CONSUMABLE`
    - ✅ (FIXED) typo in statistics: ALLERGEN_EGGS → ALLERGEN_EGG
    - ✅ (FIXED) typo:  "INDEIBLE" → "INEDIBLE" for dragon_essence in magiclysm
    - ✅ (FIXED) "STRAPPED"→"BELTED" (for dimensional anchor)

Also following issues with item flags were discovered:

Flags that are used (and I had to add them to flags.json) but don't make sense:
    - ❎ (REMOVED) ~~USE_PART_ITEM~~
    - ❎ (REMOVED) ~~REFILLABLE_LIGHTER~~
    - ❎ (REMOVED) ~~RAPIDFIRE~~
    - ❎ (REMOVED) ~~HURT_WHEN_PULLED~~
    - ❎ (REMOVED) ~~NV10_EFFECT (crit mod)~~

Flags that don't seem to have c++ support:
    - ❎ (REMOVED) ~~NO_AMMO~~
    - ❎ (REMOVED) ~~MECH_WEAPON~~ 
     flag introduced in  #32409 , no C++ support, no in-game info.
     Based on description, functionality seems to be covered by the absence/presence of gun mod slots  + `NO_REPAIR` flag.
    - ❎ (REMOVED) ~~FLAMMABLE~~ (no support for items, item flammability is based on materials, single usage in "book_fict_soft_tpl")
    - ❎ (REMOVED) ~~"EXPLOSIVE"~~ used as an item flag (instead of ammo_effect)
    - ❎ (REMOVED) ~~EXPLODES~~  seems to be a duplicate of `itype::explode_in_fire`
    - ❎ (REMOVED) ~~TRANSPARENT~~ (not used anywhere)
    - ❎ (REMOVED) ~~REACH~~  (it's a gunmod flag, not an item flag)
    - ❎ (REMOVED) ~~NO_PICKUP~~  (not implemented, used once in magiclysm)
    - ❎ (REMOVED) ~~ANESTHESIA~~ (it's a quality, not a flag, used as a flag in aftershock mod, also see #44809)
    - ✅ (STAYS??) BACKBLAST currently not implemented, but could be implemented in the future.
    - ✅ (STAYS for now) `BIONIC_NPC_USABLE`  (`bionic` flag used also as item flag for info. When used as item flag has no c++ support. In the future should probably be reworked to provide dynamic item info based only `bionic` flags)
    - ✅ (STAYS for now) `PLANTABLE_SEED` (seeds are marked with it, no cpp usages. Seems only be used to provide item info. Maybe rework in the future to generate this info part dynamically?)
    - ✅ (STAYS) `BAD_TASTE` Although no c++ support, it's used in some cooking mechanic (i.e. some food has it and it then gets removed when cooking). Currently the flag is only for flavor (pun intended).
    - ✅ (STAYS) `MAG_COMPACT` - used in pocket restrictions
    - ✅ (STAYS??) NOGIB  (no support for throwable items). Flag does make sense though. I think C++ support may be added eventually?
    - ✅ (STAYS??) IRREPLACEABLE_CONSUMABLE - used for ammo and comestibles. Perhaps could affect price or be used for tests in the future?

#### Describe alternatives you've considered

See  #44694.

#### Testing

See  #44694.

Checked that no warnings about invalid flags are generated. Checked that warnings are generated if flags are indeed invalid.
Additionally checked that LIGHT_XX flag still works as expected.

### CODE REVIEW

**Comment by Aivean** [comment]
Any suggestions are welcome on what to do with the flags outlined above, especially these:
- USE_PART_ITEM
- REFILLABLE_LIGHTER
- RAPIDFIRE
- HURT_WHEN_PULLED
- NV10_EFFECT (crit mod)

**Comment by ZhilkinSerg** [comment]
> 
> 
> Any suggestions are welcome on what to do with the flags outlined above, especially these:
> 
>     * USE_PART_ITEM
> 
>     * REFILLABLE_LIGHTER
> 
>     * RAPIDFIRE
> 
>     * HURT_WHEN_PULLED
> 
>     * NV10_EFFECT (crit mod)

Just drop flags without code support from item definitions and `flags.json`.

Related issues and pull requests:

* `USE_PART_ITEM` - discussed in #11381;
* `REFILLABLE_LIGHTER` - some legacy code, removed in #11275, but not from JSON;
* `RAPIDFIRE` - some legacy code, added to JSON in #16488, but no code support as far as I can see;
* `HURT_WHEN_PULLED` - some legacy code, added in #4901, removed in #18754;
* `NV10_EFFECT` - added to JSON in #30049, I don't think it was ever implemented code-wise.

**Comment by Aivean** [comment]
@ZhilkinSerg , thanks so much for tracking the flags down.

Removed following flags from json: `USE_PART_ITEM`, `REFILLABLE_LIGHTER`, `RAPIDFIRE`, `HURT_WHEN_PULLED`, `NV10_EFFECT`.

**Comment by Aivean** [comment]
`MECH_WEAPON` flag introduced in  #32409 , no C++ support, no info
Based on description, functionality seems to be covered by the absence/presence of gun mod slots  + `NO_REPAIR` flag.

Removing.

**Comment by Aivean** [comment]
item flag `FLAMMABLE`  (don't confuse with furniture/terrain flag with the same name). 
Used in item templates: `paperback_occult` and `book_nonf_hard_dodge_tpl`. Doesn't make sense, as current item flammability is calculated based on materials.  Removing.

**Comment by Aivean** [comment]
Ok, I think this is good to go.  I removed most of the flags without c++ support.

Following flags without c++ support left intact:
- ✅ (STAYS) MAG_COMPACT - used in pocket restrictions
- ✅ (STAYS) NOGIB (no support for throwable items). Flag does make sense though. I think C++ support may be added eventually?
- ✅ (STAYS) IRREPLACEABLE_CONSUMABLE - used for ammo and comestibles. Perhaps could affect price or be used for tests in the future?
- ✅ (STAYS) BIONIC_NPC_USABLE (bionic flag used also as item flag for info. When used as item flag has no c++ support. In the future should probably be reworked to provide dynamic item info based only bionic flags)
- ✅ (STAYS) PLANTABLE_SEED (seeds are marked with it, no cpp usages. Seems only be used to provide item info. Maybe rework in the future to generate this info part dynamically?)
- ✅ (STAYS) BAD_TASTE Although no c++ support, it's used in some cooking mechanic (i.e. some food has it and it then gets 


I'm kinda doubtful regarding `NOGIB`, `IRREPLACEABLE_CONSUMABLE` and `BIONIC_NPC_USABLE`.  I left them because I think they have a potential to be implemented/used in the future.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cataclysm-mod/10523/723

**Pull request merged**
