### PR TITLE
Add charcoal cooker

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add charcoal cooker and recipe to make it.
2. Add charcoal pieces for use in charcoal cooker and recipe to make them.

### CODE REVIEW

**Comment by kevingranade** [comment]
Please at least start a game after making your changes, there were two simple errors that the json consistency checker caught that you should have fixed before PRing this.

**Comment by Darkyhard** [comment]
Well, if there is any errors, leave them to me until I fix them. After all, I'm supposed to fix stuff that I PR, not someone else.

**Comment by kevingranade** [comment]
I'm not your tester, there shouldn't be any errors by the time I look at
the PR, because you should have tested them already.
Bottom line, if you aren't going to do at least minimal testing on your
PRs, I'm not going to pull them anymore.

**Comment by Barhandar** [comment]
> Bottom line, if you aren't going to do at least minimal testing on your PRs, I'm not going to pull them anymore.

I remember this being said already. In this exact situation. _Eight months ago_.

**Pull request merged**
