### PR TITLE
Methanol fuel cells

### PR DESCRIPTION
**Pull request by Profit0004**
#### Summary

SUMMARY: Content "This change adds direct methanol fuel cells."

#### Purpose of change
This change was done in order to create fuel cells that were requested to create some enhance content. 

#### Describe the solution

These are fuel cells, very loosely based around this small run of fuel cells. 
https://gizmodo.com/the-future-of-charging-gadgets-toshibas-methanol-fuel-5390935

They themselves were based off of direct methanol fuel cells. 
The energy density of methanol is roughly 22/MJ per Kilogram and rechargeable lithium ion is about 0.5/MJ per Kilogram using those numbers and then giving an abysmal efficiency score, far less than real world in order to keep them from being more powerful than plutonium counterparts, I created some believable analogs.  (energy density information from google) 

#### Describe alternatives you've considered

This was actually the second way, the first way was to use simulated containers of methanol and run it through a special UPS.  It had issues so this was was decided on.  I also considered going all out and adding to the program but  so that they could really actually use methanol rather than simulate it, but that was a bit out of my current scope. 

#### Testing

I just kept testing them in the program trying out different ways I could try and have it break.   There were several areas of concern and they have been significantly changed from where they started.  I am hopeful I worked out all the kinks, with the exception of during reloading if a person has a full one and an empty one there is a chance it will reload the already full one unless they drop it .  I consider this almost a realistic mix up considering they would look exactly the same unless they had plugged them into a device to know.  This is a common issue among a lot of crafts though, and  I seriously doubt these will be common enough for that to become any type of problem as currently zero spawn in the world. 

#### Additional context
There is no way to build a "Ground up" fuel cell.  I am not including recipes for actually creating them and only one recipe for transforming one of them.  These are items that were created before the collapse and while they can be recharged with methanol, they can not be replaced.  Specifically the proton exchange membrane is out of the realm of fabrication after the collapse.  Pictures show how reloading takes place, and the one fuel cell that can be made from one of the other ones, also the mod to allow tools and a UPS to actually use these. 
FS1
FS2
FS3

### CODE REVIEW

**Comment by Rogal-Dorn** [comment]
Considering the energy densities I think this would make sense to be found in exoskeleton and mech finales. 
I'm confused about one thing; Do you reload the product of these shown recipes or is the recipe itself the reloading? 
If the latter, why does the super methanol fuel cell say it can be loaded fast while it takes 8 hours? If the latter why does it require methanol?

**Comment by Profit0004** [comment]
The final one is one you build, it has two recipes, I was showing the recipe to make it.  The reloading process is very short for it. 
The recipes turn these, with whatever charges they have into fully charged cells. 

I have no idea how these are going to be exactly used, they were made for someone who has plans for them.  They may indeed end up in finales, with the exception of the toolmod interface which shouldn't be hard to connect and is decidedly low tech by comparison.

**Comment by Profit0004** [comment]
Here's the step-by-step of how they operate.

Step one and probably the hardest part will be finding one of them.
Step two I would recommend using up whatever charges is in the fuel cell.
Step three to recharge the fuel cells there are four separate recharge recipes which basically take the fuel cell and methanol and give a full fuel cell back.

The largest fuel cell is one that I can envision being created, it takes the electronics of a large fuel cell and basically grafts it onto a fuel can in order to get a higher capacity fuel cell that is easier to refill. More suited to the post-apocalyptic world and needs.   

In my vision these fuel cells connect kind of like light bulbs in the real world do just with a more sturdy connection because of their weight.

**Comment by Profit0004** [comment]
Some minor code cleanup and rewording.

**Comment by I-am-Erk** [comment]
I like the concept here but your recipes need work.

I would suggest:
- make a book for fuel cells and make it fairly rare
- make the recipe actually make the fuel cell, using some rare components. A fuel cell housing might be found in a research facility although I'd be reluctant to just dump it into the current research place.

The problem here is mostly that methanol fuel cells should not be spawning in the general world, so even though it's something you can potentially get, it should be hard to obtain.

**Comment by Profit0004** [comment]
Methanol fuel cells spawn in our world..  they are fairly rare but they are used by a few people. You can buy the big ones for your boat or the small ones for your phone right now.  

https://www.imarineusa.com/Efoy151-000-210.aspx?gclid=Cj0KCQjw8fr7BRDSARIsAK0Qqr4TEVyvlpPznQI3oSSonCMJVOnY7-ZeDOA4d5t-pWjBy7Uh32Lfmz0aAv6_EALw_wcB

**Comment by Profit0004** [comment]
The smaller ones ended up being pretty much military only as consumers really didn't need and it was usually cheaper just to buy a big battery them but they are not exactly unicorns. 

https://www.engadget.com/2008/12/11/mti-micro-shows-off-universal-fuel-cell-charger-with-removable-c/

**Comment by I-am-Erk** [comment]
When I say they don't spawn in the general world I don't necessarily mean they should be unobtainable at all, or I'd suggest you make this a mod. I just mean make sure that they're a specialized item found only rarely, not something showing up in cars or people's basements.

**Comment by Profit0004** [comment]
I see, well I currently have them spawn nowhere, someone wanted them for their weapons they were developing and asked for  fuel cells in discord.   I was expecting them to determine the appropriate places to spawn.  I just was giving them the semi-realistic fuel cells.   I. Reality they are about 4 times better than these but I didn't want them to overpower plutonium.

**Pull request closed without merging**
