### PR TITLE
Small lighthouse

### PR DESCRIPTION
**Pull request by harakka**
#### Summary
Content "Small lighthouse"

#### Purpose of change
The currently existing lighthouse map felt too big and fancy for my humble tastes, so here's a smaller one. It's my first map so feedback welcome on how to do things better.

#### Describe the solution
This is a smallish late 1800s lighthouse of stone and mortar construction, still in service up to the cataclysm, renovated to use a modern replacement electric light source. However the generator mysteriously broke so it's no longer functional. Attached to the lighthouse is a small two story structure for storage and to serve as temporary quarters of the (now obsolete) lighthouse keeper and technicians servicing navigational aids in the area.

The map is added as alternative to starts which use the current lighthouse.

This is heavily based on curstwist's lighthouse. Terrains are heavily copypasted from their looks-likes.

##### TODO before undrafting
- [x] whitewashed stone and mortar terrain
- [x] palettize
- [x] upstairs food and tools storage
- [x] storage shed for diesel and firewood
- [x] wrecked generator
- [x] electricals on the ground level of the lighthouse
- [x] more trash indoors
- [x] outhouse
- [x] better ground cover for the island
- [x] proper stone flooring terrain
 

#### Describe alternatives you've considered
Modifying the existing lighthouse, but I think it's fine as a bigger one that has been turned into fancy housing.

#### Testing
Going through lots of A Safe Place starts and looking around

#### Additional context
Screenshots should be up to date minus some roof terrain changes.

Screenshot_20240609_195129

Screenshot_20240609_195157

Screenshot_20240609_195213

Screenshot_20240609_195653

Screenshot_20240609_195638

Screenshot_20240609_195623

##### Possible additions to this in a future PR
- add this to oceans and lake/ocean shores
- appliance for the light for you to fix and power
- achievement if you do fix it as said technician
- navigation aid technician start
- better work boat
- ɴᴏ ᴏɴᴇ ʟɪᴠᴇs ᴜɴᴅᴇʀ ᴛʜᴇ ʟɪɢʜᴛʜᴏᴜsᴇ

### CODE REVIEW

**Comment by Vaskritaya** [comment]
Could make sense to have this spawn coastal to oceans if that's mechanically possible. Probably out of scope since it would be a whole different map, but felt it was worth mentioning for the future since more flavor for oceans is always good.

**Comment by harakka** [comment]
I'll probably look at adding this to oceans after #72866 is done.

**Comment by PatrikLundell** [comment]
The bottom level looks like it has a natural stone floor, which isn't suitable for a man made structure. I may be wrong about the material, though.

**Comment by harakka** [comment]
That's the "proper stone flooring terrain" item on the todo list.

**Comment by Maleclypse** [comment]
Very cool and neat looking!  I went ahead and asked in tileset discord about using the mon_turret_searchlight as a filler sprite for the the lighthouse light.

**Pull request merged**
