### PR TITLE
Store read chapters per book instead of per item

### PR DESCRIPTION
**Pull request by mugling**
For example if you read a chapter of _book of tall tales_ the remaining chapter count should decrease for all other instances of that book also.

There are no behavioral changes except that for existing saves the read chapter count will be reset for all story/morale books. Skills books are entirely unaffected.

This PR is part of a larger refactoring of `player::do_read` that will hopefully support reading from distant tiles (without moving items to and from the inventory) and/or other immobile sources.

### CODE REVIEW

**Comment by Dunkhan** [comment]
So in essence there is only one type of each book in the game? I always thought the old behaviour was based on the fact that there are multiple different books of each type.

**Comment by Soadreqm** [comment]
I thought the current behaviour was intentional. Like, each fantasy novel was implied to be a different fantasy novel. In contrast to the skill books, which all have their own titles.

If the morale books are meant to be specific books, rather than generic books in a specific style, they should probably be fleshed out some. Given titles, with more than one book in each category.

**Comment by mugling** [comment]
> So in essence there is only one type of each book in the game? I always thought the old behaviour was based on the fact that there are multiple different books of each type.

> Like, each fantasy novel was implied to be a different fantasy novel.

It's inconsistent, we have both generic styles eg. *fantasy novel* and specific titles eg. *The Hitchhiker's Guide to the Cataclysm*









> If the morale books are meant to be specific books, rather than generic books in a specific style, they should probably be fleshed out some

Sure, that would be readily achievable

**Comment by BevapDin** [comment]
"The Hitchhiker's Guide to the Cataclysm" is a *very* special book, have you ever tried to read it? It doesn't even have chapters, it only shows a hint from data/json/hints.json.

When chapters were explicitly introduced as per book, not per book type. Quote from the original PR (https://github.com/CleverRaven/Cataclysm-DDA/pull/3550#issuecomment-26015533):

> I'm going to assume that since we're 20 Minutes Into The Future there are enough unique books floating around that, after the selection was thinned out by looting, each one you find is different.

There were no objections to this.

----

Besides, your implementation doesn't work: `player::chapters_read` is not stored in the save and thereby reset whenever you load a game.

**Comment by mugling** [comment]
> "The Hitchhiker's Guide to the Cataclysm" is a very special book

:grin: potentially the worse example I could have picked

> player::chapters_read is not stored in the save and thereby reset whenever you load a game.

That obviously would need to be corrected

The above notwithstanding was the decision in #3550 for ease of implementation or because it was the preferred gameplay mechanic? The reason I ask is that the change in mechanic in this PR is an incidental aspect rather than the primary goal.

**Comment by BevapDin** [comment]
> The above notwithstanding was the decision in #3550 for ease of implementation or because it was the preferred gameplay mechanic?

I know as much as you do, but the PR links to the issue it fixes. Anyway, your changes means that every romance novel is the very same book. In other words: only one romance novel was *ever* written in the whole history of the universe, or the cataclysm somehow destroyed all other romance novels. Both scenarios seem unrealistic.

The linked issue suggest that books get random titles to hide the generic type.

**Comment by mugling** [comment]
The rationale for storing chapter count per type as opposed to per item is that `player::do_read` can then accept an `itype_id` rather than a specific `item *` instance.

The benefit of this is as suggested by the last comment of #13153:

> The only real problem I see here would be extended actions, because the item can disappear

I'd like to eventually implement reading books directly from a bookshelf in your home or vehicle without having to shuffle them to and from the inventory. If `player::do_read` is changed as above the concerns raised in #13153 no longer apply.

Any possible solutions?

**Comment by BevapDin** [comment]
> Any possible solutions?

Store the required data (not necessarily the whole item) when you start the reading action.

**Comment by mugling** [comment]
But how then to update the read chapter count?

**Comment by kevingranade** [comment]
Adding the book to the player inventory is how it should work, because that
is what is actually happening.

**Comment by Marrim** [comment]
Cool change.
I might actually start using morale books now; before it was too easy to run out of reading material.

**Comment by mugling** [comment]
> Edit: pickup the item, store where it comes from, read, drop it again, just as it is done currently. You could check (on each turn) whether the item still exists in the inventory and if not, cancel the activity.

Ok, I'll implement `tripoint item_location::where_from()` and put the book back where it was found after the activity completes

**Pull request closed without merging**
