### PR TITLE
Refactor: Remove unnecessary parameter `avatar` and `map`

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
Infrastructure  "Refactor: Remove unnecessary parameter `avatar` and `map`"

#### Purpose of change

 - Continuation of #76498

#### Describe the solution

Removed all mentions of `avatar` and `map` from `src/ranged.h` and `src/avatar_action.h`. Replaced with `get_avatar()` and `get_map()` in implementations.

#### Describe alternatives you've considered

Remove more.

#### Testing

If it compiles, it should be good.

#### Additional context
 - Found dead code again - removal moved to #76789

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I haven't looked at the changes themselves,only the description, but I have misgivings.
I'm not thrilled by coding that buries dependencies deep into the code, hiding them from the users. It can lead to nasty consequences (such as recursive calls to cache handling because an operation transitively called by cache cleanup hiddenly calls the cache cleanup because the cache is still dirty, as a recent crash example). It also makes it harder to improve the functionality later on when you e.g. want to make PC only operations available to companions or other NPCs, or when you want to be able to make calculations on maps that are NOT the official reality bubble.

Based on the commit texts, most of the removals are from avatar_action, where it should be a reasonable assumption that the target is actually the avatar/PC (if that is to be generalized in the future, the operations should be moved to something with a suitable new name, at which time the character can again be made a parameter).
If the target_handling stuff is all directly tied to UI selections, then, again, it's reasonable to assume it's all PC centered (but it would make it messy if you wanted to support control of multiple characters (party control), or jumping between characters (such as e.g. using mind control magic)). Support operations should not be allowed to make such assumptions, as you may want to allow the "AI" to make use of them for characters/creatures.

**Review by kevingranade — CHANGES_REQUESTED** [review]
Again, "it *can* have nice decoupling effects" is not sufficient justification for all this churn, and "cleaner interface" is definitely not it because the interface just exists and you're obscuring it.

I want to see TANGIBLE benefits for this much code change, and there's been nothing forthcoming, so this is turning into a pretty hard no from me.

**Comment by Brambor** [comment]
resolving merge conflict

**Comment by Brambor** [comment]
> Again, "it _can_ have nice decoupling effects" is not sufficient justification for all this churn, and "cleaner interface" is definitely not it because the interface just exists and you're obscuring it.
> 
> I want to see TANGIBLE benefits for this much code change, and there's been nothing forthcoming, so this is turning into a pretty hard no from me.

I hear ya. I will look into whether I can split the files into more files so that the `#include avatar.h` disappears in this PR in some form.

**Comment by Brambor** [comment]
- Separating dead code removal to #76789.

**Comment by kevingranade** [comment]
> I will look into whether I can split the files into more files so that the #include avatar.h disappears in this PR in some form.

The thing to keep in mind here is that every time you split a file, you re making a new copy of all its headers, so yes huge files are problematic because they led to gigantic code modules, but if the way you fix that is by splitting the file 10 ways so that *some* of them no longer have some mega header in them, you've actually made things worse.  Fundamentally if you have a chunk of code where it dereferences some object, it will always need to include the matching header, there's no way around that, and if it *doesn't* dereference the object, for example because all it does is forward a pointer or reference to said object, then you already don't need the header, just a forward declaration of the class.

**Comment by Brambor** [comment]
- Separated overload removal to #78178. I didn't rebase this.

I no longer believe this is beneficial in its current form and I will not pursue finding how it would become beneficial now. Closing then.

**Pull request closed without merging**
