### PR TITLE
Can stun cyborgs again

### PR DESCRIPTION
**Pull request by Vgoloshivskiy**
#### Summary
Bugfixes "Changed monster type for broken cyborg from Robot to Cyborg and allowed dazzle rifle effect to stun cyborgs too"

#### Purpose of change

Make it possible to stun cyborgs , identify all cyborgs as cyborgs

#### Describe the solution

added to effect check for for cyborg
identified broken cyborgs as cyborg

#### Describe alternatives you've considered

probably a bit differen way of writing check for cyborgs

#### Testing

Get rifle spawn broken/prototype cyborg -> stun and deactivate them-> works

### CODE REVIEW

**Comment by Fris0uman** [comment]
They were robots and the dazzler stuns robot, why make them cyborg and add cyborg to the dazzler check?

**Comment by Fris0uman** [comment]
Maybe you meant to make Prototype Cyborg stunnable?

**Comment by Vgoloshivskiy** [comment]
> [](/CleverRaven/Cataclysm-DDA/actions/runs/10546727929/job/29218586328?pr=75941)
> [ @github-actions ](/apps/github-actions)
> ** General build matrix / GCC 12, Ubuntu cross-compile to MinGW-Win64, Tiles, Sound (pull_request) ** Queued — Waiting to run this check...
> [Details](/CleverRaven/Cataclysm-DDA/actions/runs/10546727929/job/29218586412?pr=75941)

Yes i wanted to make prototype cyborgs stunnable again as they were but i thoought making stunk work on cybogs and robots would be funnier

**Comment by Vgoloshivskiy** [comment]
> Maybe you meant to make Prototype Cyborg stunnable? They were made Cyborgs instead of Robots in this PR #74943 but I'm not clear on why
> 
> Seems like it'd be a good opportunity to move the effects of the dazzler rifle to json to make that kind of things easier to deal with in the futur

Yes i wanted to make prototype cyborgs stunnable again as they were but i thoought making stun work on cybogs and robots would be funnier

**Comment by Vgoloshivskiy** [comment]
> They were robots and the dazzler stuns robot, why make them cyborg and add cyborg to the dazzler check?

I didn't change Prototype Cyborg from Robot to Cyborg it was @Maleclypse i think i just continued this for all cyborgs

**Comment by Maleclypse** [comment]
It seems that I should have left a comment on the broken cyborg.  The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally.  So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,

**Comment by Vgoloshivskiy** [comment]
> It seems that I should have left a comment on the broken cyborg. The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally. So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,

How am i supposed to stun them in order to save prototype cyborg? hit them with a hammer and hope 20 str 7 bash won't turn them in splatter on a floor?

**Comment by Maleclypse** [comment]
> > It seems that I should have left a comment on the broken cyborg. The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally. So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,
> 
> 
> 
> How am i supposed to stun them in order to save prototype cyborg? hit them with a hammer and hope 20 str 7 bash won't turn them in splatter on a floor?

I'm going to check to confirm scrambler grenades still work and adjust them if not.

**Comment by Vgoloshivskiy** [comment]
> > > It seems that I should have left a comment on the broken cyborg. The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally. So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,
> > 
> > 
> > How am i supposed to stun them in order to save prototype cyborg? hit them with a hammer and hope 20 str 7 bash won't turn them in splatter on a floor?
> 
> I'm going to check to confirm scrambler grenades still work and adjust them if not. Or I'll add a different consumable for them.

Thanks

**Comment by Vgoloshivskiy** [comment]
> > > It seems that I should have left a comment on the broken cyborg. The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally. So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,
> > 
> > 
> > How am i supposed to stun them in order to save prototype cyborg? hit them with a hammer and hope 20 str 7 bash won't turn them in splatter on a floor?
> 
> I'm going to check to confirm scrambler grenades still work and adjust them if not. Or I'll add a different consumable for them.

And Zomborgs then also should be Robots as they have no alive brain? or am i missing something

**Comment by Maleclypse** [comment]
> > > > It seems that I should have left a comment on the broken cyborg. The broken cyborg is a ROBOT because the human brain is dead and dazzler's don't affect cyborgs intentionally. So human brain alive, CYBORG not affected by dazzler. Human brain non-existent in mechanical body ROBOT and affected by dazzler,
> 
> > > 
> 
> > > 
> 
> > > How am i supposed to stun them in order to save prototype cyborg? hit them with a hammer and hope 20 str 7 bash won't turn them in splatter on a floor?
> 
> > 
> 
> > I'm going to check to confirm scrambler grenades still work and adjust them if not. Or I'll add a different consumable for them.
> 
> 
> 
> And Zomborgs then also should be Robots as they have no alive brain? or am i missing something

Yep that would be correct.

**Pull request closed without merging**
