### PR TITLE
Urban Development: Multi-tile public library

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
```SUMMARY: Mods "The Urban Development mod now has a large public library."```

#### Purpose of change
I've long felt that multitile libraries would make an interesting addition, and Urban Development provides the perfect place to put it in.

#### Describe the solution
Created a 2x2 public library building that can generate in cities with Urban Development. It has different bookshelf sections for textbooks and novels, as well as a lot of small nooks and crannies to study or read. The floor plan is based off of the upper level of [Groton Public Library's floorplan](http://gpl.org/about-the-library/floorplan/) (I just googled "library blueprint" and it looked nice.)

Novels spawn in very large amounts, and textbooks in decent ones, making this a great place to find books compared to the smaller regional libraries. A metal door along the eastern wall serves as a fire escape. Some bookshelves behind the information desk can have exotic books.

There are also several computer workstations and a computer lab, plus a small break room for staff. (The green question marks are Aftershock books, don't mind that.)

A staircase leads to a second floor with staff areas. There's a small circulation desk plus some bathrooms and a study for public use, and west of that is a storage area, a small break room, and a conference room.

#### Describe alternatives you've considered
Implementing it into the base game. I felt like it would look out of place in cities, and that Urban Development served a better home for now.

#### Additional context
image
image

### CODE REVIEW

**Comment by curstwist** [comment]
2nd story including some office space for book processing would be great (desks, terminals, chairs, shelves, book trucks if you want a challenge), and a roof :)

**Comment by chaisawlajatang** [comment]
Whoa, looks like a really nice place to visit!

**Comment by nexusmrsep** [comment]
It could be also reserved to bigger city sizes if mainlined. But i guess Urban Development will eventually get mainlined anyway.

**Comment by Ilysen** [comment]
I added a second floor, I'm happy with how it came out. No roof, yet, but I might.

**Pull request merged**
