### PR TITLE
[CR] create guidelines for creating food and drinks

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary

```SUMMARY: Balance "create guidelines for creating food and drinks"```

#### Purpose of change

I was about to create some foods and recipes and couldn't find any guidelines. I asked around in the discord chat and I found out that there weren't much/any.

This is a first draft of creating guidelines for players who want to add food and drinks to the game. 

#### Describe the solution

I think I've made a decent first start in calculating `quench` and `health` that is somewhat consistent with both real life and the previous work in #27289 by @KorGgenT.

The TL;DR version is that the basic idea of calculating `quench` is that water adds `quench`, and calories, alcohol and sodium penalizes `quench`. and that the basic idea of calculating `health` is that the vitamins and minerals tracked in-game plus dietary fibre adds to `health`, while sugar, fat, salt and alcohol penalizes `health`. 

The formulas are somewhat complicated and tedious to do by hand, but we could provide a spreadsheet/tool where a contributor could just paste in the table from FDA websites to get the recommended values to use in game.

---

The formula for `quench` is currently :

```
water (g) / 5 - 
1.281 * alcohol (g) - 
0.005 * calories - 
0.004 * sodium (mg)
```

The weighting for calories and sodium are arbitrary and subject to change. The weighting for alcohol is based on the following study:

> In conclusion, only moderate amounts of stronger alcoholic beverages (≥13.5%) resulted in a temporary diuretic effect compared to their non-alcoholic counterparts. 

(Note: "diuretic" means something that increases urine production, and thus dehydration.)

* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5537780/

If we assume that the dehydration effect of 13.5 units of ethanol is equivalent to 86.5 units of water (i.e. quench), and that dehydration scales linearly, then 13.5 ml ethanol would be 86.5/5 = -17.3 quench, Or -17.3/13.5 = -1.281 quench per ml of ethanol.

An example for a hard liquor with 40% alcohol and 60% water the quench for alcohol would be:

```
Ethanol : 40 x (-1.281)  = -0.5126 quench.
Water : 0.6 x 0.2 = 0.12 quench.
Total -0.5126 + 0.12 = -0.3926 quench per 1 ml, or -98.15 quench per 250 ml. 
```

I.e. you would need to drink about 2 glass of water for each drink hard liquor to maintain hydration, which is consistent with (anecdotal) recommendations I've heard.

I've been trying to incorporate electrolytes in quench in a good way as the `sports_drink` has 60 quench due to electrolytes. But so far the attempts to put electrolytes in the formula gives weird values for certain electrolyte rich foodstuffs that shouldn't give quench bonuses.

---

To calculate health we take the average of the RDI of  Vitamin A, B-12, C, Calcium, Iron and dietary fibre and subtract the average RDI of sugar, saturated fats and sodium.

Of course ideally we would have a perfect balance of RDI's from each nutrient, but with the abundance of sugar, saturated fats and sodium in modern food it's generally better to seek-out e.g. vitamins. 

Then we subtract 0.2 for each g pure alcohol.

The formula for `health` is currently :

```
(
  AVERAGE(Vitamin A RDI, Vitamin B-12 RDI, Vitamin C RDI, Calcium RDI, Iron RDI, Dietary fibre RDI) - 
  AVERAGE(Sugar RDI, Saturated fat RDI, Sodium RDI) - 
  0.2 * pure alcohol content
)^2/3
```

Taking it to the power of 2/3 is to get more manageable values. If not, e.g. liver would have a health value exceeding 20.

---

TODO: Similar guidelines for fun, expiration date, stimulation, addiction etc.

#### Describe alternatives you've considered

There are a number of things that could be done differently.

* Simplify the guidelines, or be looser with just general recommendations, so that you could realistically easily add foodstuffs without needing a spreadsheet.
* Expand the formula to take into account more nutrients and perhaps add weighting instead of simply taking average RDI.
* Track several pieces of nutrients in game (like we currently do with vitamins), and rather than a health value for regular foods, calculate survivor health based on if they've consumed sufficient nutrients.

#### Additional context

Here is a spreadsheet of foodstuffs from the [Swedish Food Agency](http://www7.slv.se/SokNaringsinnehall/) where I calculated the would-be in-game values using the formulas:

* https://docs.google.com/spreadsheets/d/1q6SO7M0DDV6rMARBqZ8ZVK5HXB3r3h-0J6dBofmEuSI/edit?usp=sharing

### CODE REVIEW

**Comment by jbytheway** [comment]
@ampersand55 are you likely to continue this?  If not, is what you've done so far in a suitable state to be merged.  Would be better to have partial documentation than none.

**Comment by ampersand55** [comment]
I had kind of forgot about this lol. I was awaiting some feedback, especially from senior devs, since I'm not really sure if my assumptions about what we want is correct. I don't think I'm involved enough to make decisions alone about balance and mechanics. 

I imagine @KorGgenT is quite busy with the nested container system now, but these guidelines would also imply that the values in #27289 would be readjusted for consistency. 

I'm currently at my parents summer place and not in my main developing environment, but I think I can get something done next week.

**Comment by KorGgenT** [comment]
you're saying you need to readjust the calories and vitamins? i don't think that's necessary, as those values are pulled directly from the USDA website for nutrition and the data for how long it takes to become deficient in said vitamins. i did not however touch quench at all in json.

**Comment by ampersand55** [comment]
Nutrition does not need adjusting, I was thinking about health (and possibly "fun").

I should have been clearer.

**Comment by ampersand55** [comment]
I've started working on this again, and I could use some answers regarding stim and addiction of caffeine and alcohol.

The relationship between alcohol and caffeine content and stim and addiction is not linear and I would like some input in how to proceed. I assume stim is supposed to correspond to alertness and drunkenness, but I'm not sure what it does mechanically. What do stim really do? Is it just to determine overdose potential?

It seems like the drunkenness and stat effects comes from the "use action" ALCOHOL_WEAK, ALCOHOL and ALCOHOL_STRONG on alcohol, and alertness from caffeine comes from "fatigue_mod" rather than stim.

---

### Caffeine

"dark cola" in game has 6 stim and 2 addiction per 250 ml.

[Generic cola has about 22.5g caffeine per 250 ml.](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789510/nutrients)

This calculates to 0.2666 stim per g and 0.0888 addict per g.

"coffee" in game has 12 stim and 2 addiction per 250ml.

[Brewed Coffee has about 100 caffeine per 250 ml.](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789337/nutrients)

This gives 0.12 stim per g and 0.02 addict per g.

### Alcohol

"vodka" in game has -12 stim and 5 addict per 250/7 ml (35.7ml) and gives the effect ALCOHOL.

[Generic vodka has 11.93 alcohol per 250ml/7](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789690/nutrients)

This calculates to -1 stim per g alcohol and 0.42 addict per g.

"beer" (all types) in game has -4 stim and 2 addict per 250ml and gives the effect ALCOHOL_WEAK.

[Generic beer has 9.75 alcohol per 250ml](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789593/nutrients)

This gives -0.41 stim per g alcohol and 0.205 addict per g alcohol.

**Comment by Maleclypse** [comment]
> I've started working on this again, and I could use some answers regarding stim and addiction of caffeine and alcohol.
> 
> The relationship between alcohol and caffeine content and stim and addiction is not linear and I would like some input in how to proceed. I assume stim is supposed to correspond to alertness and drunkenness, but I'm not sure what it does mechanically. What do stim really do? Is it just to determine overdose potential?
> 
> It seems like the drunkenness and stat effects comes from the "use action" ALCOHOL_WEAK, ALCOHOL and ALCOHOL_STRONG on alcohol, and alertness from caffeine comes from "fatigue_mod" rather than stim.
> 
> ### Caffeine
> "dark cola" in game has 6 stim and 2 addiction per 250 ml.
> 
> [Generic cola has about 22.5g caffeine per 250 ml.](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789510/nutrients)
> 
> This calculates to 0.2666 stim per g and 0.0888 addict per g.
> 
> "coffee" in game has 12 stim and 2 addiction per 250ml.
> 
> [Brewed Coffee has about 100 caffeine per 250 ml.](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789337/nutrients)
> 
> This gives 0.12 stim per g and 0.02 addict per g.
> 
> ### Alcohol
> "vodka" in game has -12 stim and 5 addict per 250/7 ml (35.7ml) and gives the effect ALCOHOL.
> 
> [Generic vodka has 11.93 alcohol per 250ml/7](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789690/nutrients)
> 
> This calculates to -1 stim per g alcohol and 0.42 addict per g.
> 
> "beer" (all types) in game has -4 stim and 2 addict per 250ml and gives the effect ALCOHOL_WEAK.
> 
> [Generic beer has 9.75 alcohol per 250ml](https://fdc.nal.usda.gov/fdc-app.html#/food-details/789593/nutrients)
> 
> This gives -0.41 stim per g alcohol and 0.205 addict per g alcohol.

Stim I believe reduces tiredness?

**Comment by ZhilkinSerg** [comment]
Feel free to reopen.

**Pull request closed without merging**
