### PR TITLE
Use real keybinds for the tutorial and improve tutorial readability

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Use real keybinds for the tutorial and improve tutorial readability"

#### Purpose of change

Fixes [#54552 ](https://github.com/CleverRaven/Cataclysm-DDA/issues/54552)
Also improves the readability of the tutorial and cleans up some outdated lessons.

Goals:
- [x] Create replace_keybind_tag that allows text to be replaced within keybindings.json 
- [x] Initial pass of replacing hardcoded text with keybindings
- [x] Full pass verifying each piece of text is using the correct keybinding
- [x] Any code cleanup that comes from comments/suggestions
- [x] Figure out how to deal with `<arrow keys>`, `<numpad>`, `<vikeys>`, etc.
- [x] ~Define a default keybinding for fire_burst or remove the mention of it from LESSON_GUN_FIRE~ (Alternatively, reword the lesson to use the select_fire_mode)
- [x] Define behavior for keybinding not being set. (Currently shows as 'Unbound Locally!')
- [x] Handle "Select with mouse" keybinding

Bonus:
- [x] Allow highlighting and/or quote wrapping of keys when multiple are defined. Ex: 'a, b, or c' -> 'a', 'b', or 'c'
- [x] Send a debugmsg() for a non-existent keybind: <keybind_DOESNT_EXIST> (In case of programmer error or keybind deletion/rename?)
- [x] Full spelling/grammar cleanup of all text for the tutorial
- [x] Report feature request for: Create keybinds for liquid handling so they aren't hardcoded: https://github.com/CleverRaven/Cataclysm-DDA/issues/55277
image
- [x] Report bug with ACTION_PICKUP no longer working #55276
- [x] ~Create new issue for unused or not triggered lessons~ Wait for ACTION_PICKUP to be fixed
- [ ] Allow shorthand/hints for specific keys. Ex: '|' -> '| (vertical pipe)'
- [ ] Write test cases for replace_keybind_tag

#### Describe the solution

Add a new tag specifically for keybinds with the following formats:
```
<keybind:category:keybind>
<keybind:keybind> // Uses the default category

Examples:
<keybind:POPUP_WAIT:QUIT>
<keybind:look>
```

Rewrite parts of the tutorial to make it easier to understand and fix broken/outdated information

#### Describe alternatives you've considered

Leave keybindings hardcoded. Leave the tutorial hard to read and partially broken.

#### Testing

I have run through the tutorial a number of times and checked that keybinds and updated text look correct. See additional context for a few comparisons.

#### Additional context
LESSON_INTRO:
image

LESSON_MOVE: 
image

LESSON_MOVEMENT_MODES: 
image

Correctly shows unbound message for an unbound key: 
image

Correctly showing an error when adding <keybind:NONSENSE> to a tutorial lesson:
image

### CODE REVIEW

**Comment by dseguin** [comment]
Great work!

I made a slight improvement to highlight individual keys (see changes in https://github.com/dseguin/Cataclysm-DDA/commit/df836a79814fb723b05b11f26390a8269b30cf31). The advantage is that you don't need to specify colour tags or `'` apostrophes in the text snippets.

tuto_txt

**Comment by dseguin** [comment]
> @dseguin That is a great improvement that I'm not sure I would have figured out on my own. It also has some of the cleanup that I was going to do, so even better. What's the cleanest way to get your changes merged here?

There are several ways to do that with git. I would add my branch as a remote and merge it into yours. But to make it easy I made a pull request against your branch which implements those changes: https://github.com/haveric/Cataclysm-DDA/pull/1

**Comment by haveric** [comment]
I believe I have everything ready for this and all the new issues created that I want to for now.  I'd welcome others to run through the tutorial (especially if you use heavily customized controls) to help get another pair of eyes on it.

The only things left that I could see value in are:
-  creating shorthand or explanation text for some keys, but I feel this is going to require far more effort than it is worth. I can see the value in wanting better descriptors for some characters, such as '|' -> '| (vertical pipe)', but the real keybinds far outweighs this need.
- Writing unit tests for some validation. I'm not sure if this is super useful for this, but I've done my best to cover the edge cases, such as non-existing keybinds as well as unbinding keys. I'm also not familiar with the unit test structure for this codebase.

Please let me know if there's anything that needs modifying or could be tweaked to better fit the style of the existing project.

**Comment by Faalagorn** [comment]
Thanks a lot for that PR! Do you think the same approach could be used to revamp some hardcoded or otherwise unstandarized keybindings? I'd have to take a deep look at the game code to find them all, but I remember seeing a lot of inconsistency when translating the game to Polish and fixing some issues on it, which I mentioned on the official Discord's #translation channel funnily enough. :)

**Comment by haveric** [comment]
> Do you think the same approach could be used to revamp some hardcoded or otherwise unstandarized keybindings?

Possibly. Please reach out to me on discord if you come across anything and I can help take a look.

**Pull request merged**
