### PR TITLE
Shorter item status and coloring²

### PR DESCRIPTION
**Pull request by OzoneH3**
Cherry picked version of #11190 after messing up a merge.

After popular demand item hp option default set to true.

Todo:
- [x] Find all the places where wprint has to be replaced with fold_and_print
- [x] fold_and_print has problems with longer item names, have to find a way to trim first without loosing coloring

Went through all the menus I could find and everything seems ok for now.

### CODE REVIEW

**Comment by Asmageddon** [comment]
Oh god yes. Item status was always something of a pain, this looks wonderful.

**Comment by KA101** [comment]
One major issue: when looking at the NPC window, etc, these get displayed with color tags shown rather than coloring.  `<color_light_green>|| </color>pair of sneakers`, for example.

**Comment by narc0tiq** [comment]
Applying a damaged bandage will also show the color tags when it asks what you're using it on:
color_magenta bandage

**Comment by narc0tiq** [comment]
Shows up as the wielded weapon, as well:
color_yellow baseball bat

**Comment by DavidKeaton** [comment]
Agreed, this looks dope.

**Comment by KA101** [comment]
Weapons and first-aid gear fixed; NPC worn clothing not so much I'm afraid.

**Comment by OzoneH3** [comment]
Is there another npc inventory than this: http://i.imgur.com/6pOfAvV.png Can't find another.
V-menu's one of the first I changed and it's working here ?!

PS: Seems like I'm too bumb to merge with an updated master to get this thing to merge properly after resolvong a conflict ..

**Comment by narc0tiq** [comment]
Trade interface, maybe?

**Comment by OzoneH3** [comment]
No, got the trad interface covered as well.

**Comment by KA101** [comment]
Farlook function; the x or ; keys, not the inventory.

**Comment by OzoneH3** [comment]
Gotcha, fixed. Pretty hard to find all those menus :(

**Comment by KA101** [comment]
Sorry for the unclarity on my part.  :-(

**Comment by moist-zombie** [comment]
Extra color schemes for a colorblind mode, or at least an optional toggle to the original setting in options? I'm not colorblind myself, but I've considered something like this before and thought about it then :>

**Comment by OzoneH3** [comment]
There is an option in "Interface" -> "Show Item health bars" to switch back to the text based style.
Is there a colorblind mode? It's using the same colors as the armor sort screen atm.

**Pull request merged**
