### PR TITLE
Remove Bathroom Scale Recipe

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
None

#### Purpose of change

The recipe doesn't make much sense, it's a few tidbits of metal and two watches.

#### Describe the solution
Removes it. 

#### Describe alternatives you've considered
Just removin it

#### Testing
The recipe in the normal game is not there.

### CODE REVIEW

**Comment by Holli-Git** [comment]
> Few junks of metal and clockwork mechanism This in not crazy, this is wonderful world of mechanics

That is not "junks of metal" those are specifically manufactured parts. Also "clockwork mechanism" is pretty vague and can cover a wide array of stuff. Not to mention you'd likely need to make sure it's accurate

**Comment by kevingranade** [comment]
Just remove,  it's not funny or weird just jank.

**Comment by StarShatter707** [comment]
> > Bathroom scale is existing in real world and you can craft it in real world too. If you think, that recipe or components in it are wrong - fix it or open an issue about this problem, dont simply remove anything
> 
> I've found no instructions on how to do so. If you do have one, please send it this way and I'll happily fix the current recipe for it. You can also PR it yourself, this PR isn't preventing you from doing so

Very detail description in 3d animation.
From 4:53
https://youtu.be/LdZLLR8AfkM?si=WBp3OVevkw_HnWZW

**Comment by Holli-Git** [comment]
> Very detail description in 3d animation. From 4:53 https://youtu.be/LdZLLR8AfkM?si=WBp3OVevkw_HnWZW

You are confusing "how it works" vs actual instructions. If we decided to follow your logic, we'd be allowed to build particle accelerators, M16s, etc etc.

**Comment by Aether1509** [comment]
> > Very detail description in 3d animation. From 4:53 https://youtu.be/LdZLLR8AfkM?si=WBp3OVevkw_HnWZW
> 
> You are confusing "how it works" vs actual instructions. If we decided to follow your logic, we'd be allowed to build particle accelerators, M16s, etc etc.

I am more than sure that most of the parts can be forged, given the fact that the character is capable of making much more complex things, for example, a rack or a spring (which is found in crafts). Gears can be obtained from clock mechs, and since it is not indicated which parts are indicated  in watch mechanisms, it can be absolutely anything.  For the scale, you can use a piece of steel and a marker, the main thing is to set it up correctly.

**Comment by StarShatter707** [comment]
> > Very detail description in 3d animation. From 4:53 https://youtu.be/LdZLLR8AfkM?si=WBp3OVevkw_HnWZW
> 
> You are confusing "how it works" vs actual instructions. If we decided to follow your logic, we'd be allowed to build particle accelerators, M16s, etc etc.
Instructions how to make thin metal rods? Use hammer to make it thin

**Comment by kevingranade** [comment]
None of this is the slightest bit convincing,  you've been told what the criteria is, either supply that or drop it.

**Comment by Aether1509** [comment]
> None of this is the slightest bit convincing, you've been told what the criteria is, either supply that or drop it.

The video shows that the scales consist of an extremely simple mechanism that can be reproduced from different things.  For example, rack and gears can be obtained from old machinery.  There are already springs in the game, everything else can be done by welding steel or forging it.  This is not nanotechnology, and you can clearly do it yourself.

**Pull request merged**
