### PR TITLE
Add data-driven moddable sidebar widgets

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Features "Add data-driven moddable sidebar widgets"

#### Purpose of change

The right sidebar has a number of usability problems. Customizing it requires editing some rather convoluted and finicky `panel.cpp` code, which makes people (at least me) disinclined to try and improve them.

But possibly the biggest problem with the right sidebar panels is how hard-coded they often are. Making the description and layout of the sidebar more data-driven will:

- make it easier to mod
- allow more rapid prototyping of sidebar layouts
- allow showing debug information that is not normally available to the player

#### Describe the solution

Define a new `widget` class implementing JSON objects of type "widget", that can display:

- numeric values ("Focus: 120")
- graph of symbols (`||...`, `||\..` and so on)

Connect these widgets to avatar attributes (HP, pain, thirst etc.) to allow generalized sidebar customization with JSON, and recreation of the existing sidebar info in data-driven form.

- [x] Write documentation first, as a wishlist
- [x] Add JSON equivalent for some major existing sidebar features
- [x] Add test cases for widget JSON loading and correct rendering
- [x] Implement `widget` class using `generic_factory`
- [x] Add graphing function(s)
- [x] Add data-source connector function(s)
- [x] Add colorization support (maybe)
- [x] Add option to use the new sidebar in game
- [x] Add a bunch more tests using `show` and `layout` with an `avatar`

The `}` sidebar configuration menu now includes a "Custom" section that may be added to any of the four layouts (both wide and narrow). For now, this section displays only basic info, similar to the existing builtin sidebars - HP for each body part, stamina, speed, focus, movement, sound, fatigue, STR, DEX, INT, and PER.

#### Describe alternatives you've considered

This is pull request 1 of 2 or more. Here is the initial implementation and demonstration of concepts; it is entirely playable, though not intended as a final "production" draft.

Future PRs will build on this foundation to make it a more complete solution for information display to the player. I hope it can eventually be used to phase out the hard-coded sidebar.

Continued in #47620 

#### Testing

Unit tests can be run with `tests/cata_test '[sidebar],[widget]'`

In-game, use the `}` sidebar configurator to enable the `Custom` section.

Edit `data/json/sidebar.json` to customize it however you like.

#### Additional context

Example of default "Custom" sidebar in "labels" layout mode:

image

And in "labels-narrow" layout mode:

image

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Related issue: #23079.

**Comment by I-am-Erk** [comment]
Food for thought while you're digging around in here, I would love to be able to define tiles instead of ascii characters for the sidebar. I can tell you more about my ideas if you like

**Comment by wapcaplet** [comment]
This will remain in WIP, probably until after 0.F, since it is a significant new feature. But I have taken off the "Draft" status - this is essentially complete and working now (with tests and documentation), well enough for others to test and review it (please do!)

**Comment by jbytheway** [comment]
You have some clang-tidy issues to deal with.

**Comment by Raikiri** [comment]
There's unreasonable amount of wasted space there, especially on small phone screens. I really hope that with this we could make an essentials-only version for compact view.

**Comment by wapcaplet** [comment]
This PR is functionally complete and playable as-is; aside from some clang-tidy cleanup and occasional rebasing to keep it in sync until after 0.F, I don't plan to expand it further here.

In short, I am tying a knot on this PR and have opened #47620 for further enhancements.

**Comment by wapcaplet** [comment]
Reconsidering the large size of this PR, I am thinking of breaking it up somewhat:

- Widget class: ~500 lines
- Documentation: ~300 lines
- Tests and test data: ~500 lines
- In-game sidebar panel: ~500 lines

The in-game panel provided with this PR is rudimentary, hardly more than a demo, and only work on wide sidebar layouts. So I am once again putting this back to DRAFT state, and may end up closing this PR entirely in favor of a new set of cleaner submissions. Thanks for playing!

**Comment by ZhilkinSerg** [comment]
Works fine for me. I think it would make sense to move `sidebar.json` to a separate folder (e.g. `data/json/ui` or `data/core/ui`).

**Pull request merged**
