### PR TITLE
[CR] Cleanup basecamp primitive farm. Fix Plow fields

### LINKED ISSUE #55739: Fampplow
### Describe the bug

Here's a lovely panoramic of my faction camp (AKA "famp") farm:

Screenshot_20220227-145118

Note the missing rows where there's dirt. Here's a pic of my famp's farm expansion screen:

Screenshot_20220227-145202

Note the # of tiles to be plowed.

### Steps to reproduce

1. Make the famp farm.
2. Harvest the famp farm.
3. ???
4. PROFIT!

### Expected behavior

I expected to be able to order my followers to plow the land in preparation for the next seeding after having them harvest.

### Screenshots

_No response_

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Oats went from seed to maturity really fast. Does any crop grow faster?? Is it intended they grow in a couple of weeks or does this warrant another bug report??

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Cleanup basecamp primitive farm. Fix Plow fields"

#### Purpose of change

Cleanup and improve the primitive farm basecamp construction. (May pull some of this out as the scope of this PR has changed)
Fix the basecamp overmap names not being updated on upgrades. (farm survey -> farm)
Attempting to fix the "Plow Fields" functionality for both basecamp farms.
Should fully fix #55739

#### Describe the solution

- Added a new json attribute that controls the overmap updating:
- Move upgrade rotation (and mirroring ideally) to the overmap to reduce duplication of flags

```
  "blueprint_update_oter": "bar"
  "blueprint_update_oter": [ { "pre": "any", "id": "bar" } ] // Same as above
  "blueprint_update_oter": [ { "pre": "foo", "id": "bar" } ]
  "blueprint_update_oter": [ { "pre": [ "foo", "foo2" ], "id": "bar" } ]
  "blueprint_update_oter": [ { "pre": [ "foo" ], "id": "bar" }, { "pre": [ "foo2" ], "id": "bar2" } ]
  ```
- Updated most of the primitive farm requirements and times to match the current state of building (Mostly shorter times, but more materials). I also chose to use the existing dirt floor w/ roof instead of the non-existent log roof, which changed some requirements. (May revert some of this as the scope of the PR has changed drastically)

TODO:
- [x] Fix rotation for the overmap
- [ ] Implement mirror_horizontal and mirror_vertical for overmaps (before rotation, such as `overmap_name_mh_north` or `overmap_name_mv_north`
- [ ] Convert existing overmaps in order to preserve rotation for upgrades
- [ ] Make sure other expansions are updating the overmap name correctly

#### Describe alternatives you've considered

- Remove all missions for plowing fields and only let the "Plow Fields" action plow them
  - Optionally with a number input to plow less
- Figure out how these used to work. I'm pretty sure it used to go off of the result, but I can't find when "Plow Fields" stopped working. Result also isn't consistently being used to reference an overmap, which is why I chose to add a new field.
- Let someone better at maps fix this

#### Testing

In progress.

#### Additional context

~I'm struggling to get the overmap rotation to work correctly. Hoping someone can take a look at my changes and make sense of what I'm trying to do.~ Overmap rotation is working now, but mirroring them is another can of worms that I wasn't planning on having to implement. If anyone wants to help with this, I would love some assistance here.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@curstwist because  I always fail at rotations.

**Comment by PatrikLundell** [comment]
I've stayed away from the legacy stuff largely because of the complications of ensuring backwards compatibility works (in addition to not really understanding how it's supposed to work in the first place).

**Comment by haveric** [comment]
> I've stayed away from the legacy stuff largely because of the complications of ensuring backwards compatibility works (in addition to not really understanding how it's supposed to work in the first place).

For now, I've only added the extra 2 rows of fields from the original layout. Everything else is just cleaning it up from all the changes that have happened, such as made it dirt on the initial survey and bringing the materials and time up to date for what is actually being used in the blueprints. I do want to go further to split out the field plowing from the building, but had the same concerns as you about backwards compatibility, so I may revisit this.

For the "Plow Fields" and overmap update, this is affecting both farms (and likely every expansion and basecamp type). I tried digging into the history of changes to see when this broke, but I had no luck chasing it down, so I went down a new path with the assumption that whatever worked before went off the result assuming it was the same as the overmap, which isn't the case with a lot of the new work. This solution (once rotation is figured out) fixes this for both versions of the farm currently and I'll extend it to the rest once the functionality is working as it should.

**Comment by haveric** [comment]
@PatrikLundell It looks like you were the one to implement mirroring/rotation for basecamps.  Would you be able to assist in figuring out the mirroring/rotation issues? 

As I'm digging into this more, I'm also questioning the mirroring functionality and want to get your thoughts:
- Vertical Mirror is never used.
- Horizontal Mirror appears to be applied to all/most of V2 upgrades for the N, E, S, and W directions, which feels like all of the upgrades are being flipped equally, meaning they either don't matter if they're flipped or should just be built flipped to begin with. (Maybe I'm missing the reason here for something)
- Mirroring doesn't appear to be accessible outside of the the blueprint recipes, making overmap matching impossible as far as I can tell.
- Mirroring doesn't appear to be intended for maps except when you are mirroring it back after an operation. I assume this is because it's not being saved anywhere. Reference comment: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.h#L1718-L1722

Of course, removing something like mirroring now would just cause a whole heap of new issues for existing maps, so even if it's not wanted, I don't know if that's a reasonable option, but I'm stuck on how to handle the plowing of fields since it is relying on the overmap json that doesn't have a good way to match up to the potentially mirrored and rotated map.

Let me know if you have any thoughts, suggestions, or alternatives that might make sense here.

**Comment by PatrikLundell** [comment]
- I could have used vertical mirroring instead of horizontal, or could have mixed it, but decided to use a consistent pattern. I thought it best to have a complete set, rather than just implement the subset I needed.
- All the V2 constructions use the same set of rotations and mirroring. The "base" blueprint is for the NW location (have to use something, and that's the usual coordinate start). The N blueprint is then mirrored so that the border on the right side of the blueprint matches up with a corresponding border of the left side of the N (mirrored) blueprint, creating a path wide enough for most vehicles to drive through (4+4 tiles). The same logic is then applied to the other side via rotation and mirroring, so you get one "road" in from each side.
- It's true mirroring isn't accessible outside of the blueprint itself.
- It would probably be fairly easy to make effective mirroring and rotation visible to base camps by making them "provides". By effective I mean the ones that end up being used, discarding any conditions. However, that would assume everything is using the same set, which may not be the case (it should be for version 2, but I can imagine cases where you want something mirrored within the same expansion). However, directives affecting the survey map ought to be usable throughout.
- The way rotation/mirroring is implemented is somewhat counter intuitive. Instead of manipulating the blueprint and then apply it to the map, the map is manipulated in the opposite direction (for rotation: mirroring is the same in both cases), the blueprint applied directly, and then the updated map is returned to its original orientation. It can be noted that I didn't come up with the code, but someone (I'm horrible with names, unfortunately) provided me with a "quick hack" that did 90% of the implementation, leaving me to only have to add the flags and tie up some loose ends.

By making use of "provides" it ought to be possible to do what you want to do. I'm not completely sure how you go about the job, but if you apply a blueprint, using the same mirroring/rotation as was used originally.

As indicated above, there are some risks involved with storing the manipulations as provides, but my current thought is that the risk ought to be limited.

**Comment by haveric** [comment]
> The "base" blueprint is for the NW location
> creating a path wide enough for most vehicles to drive through (4+4 tiles)

That makes a lot more sense now that I realize what you were doing here. I probably should have built out in all the directions to notice the pattern you were going for.

> It would probably be fairly easy to make effective mirroring and rotation visible to base camps by making them "provides"

This is interesting. I don't know if I like the idea of re-using provides, but I could probably copy that logic specifically for flags. I'll have to think on that for a bit to see if I can make it work that way.

> However, that would assume everything is using the same set, which may not be the case (it should be for version 2, but I can imagine cases where you want something mirrored within the same expansion). However, directives affecting the survey map ought to be usable throughout.

If I'm understanding this correctly, the assumption is that all of the current flags are the same for every upgrade, so they can be all stored once per survey (via provides or something similar), but some upgrades might have overrides. What kind of example are you thinking of here?

> It can be noted that I didn't come up with the code, but someone (I'm horrible with names, unfortunately) provided me with a "quick hack" that did 90% of the implementation

Ha, fair enough. 

> I'm not completely sure how you go about the job, but if you apply a blueprint

I'm mostly using what is already there. The two things this is doing is updating the overmap tile on upgrades (to both update the name and give a reference to how the fields are supposed to be planted) and loading the map back in from the overmap and trying to compare it to the current state (This was already happening, but is a bit broken now). While ideally, I would just have the overmap know the mirror and rotation, only rotation is supported there. That makes me lean towards performing the mirror/rotation on the farm_json fake_map before doing the comparison. It looks like as long as I store it within the basecamp class similar to provides, I should be able to pass along what I need here. This would also have the benefit of de-cluttering the upgrade recipes, which I am all for.

I think I have a path forward now at least, so thank you very much for that and sorry for my confusion about how this works. It's not quite as straight forward as I had hoped, but when is it?

**Comment by PatrikLundell** [comment]
Well, I don't think I've explained the reason for the expansion layouts before (not that anyone has asked).

My use of the flags is consistent for everything within the expansion. However, you can also use flags to mirror things along an axis, such that you e.g. get the left and right residential wings of the base hub mirrored (and I think I've used for the base, which doesn't have any global orientation manipulation). You certainly don't want to pick up these flags, so care must be taken. Note, though, that this is for individual blueprints within the construction chain, not on the hub itself. I currently can't envision any scenario where I'd want to apply orientation modifications to the survey that you wouldn't want to carry through for everything else, but you'd still potentially have cases of non location dependent manipulations (such as mirroring or rotating some standard building blocks), but that would have some trouble working in conjunction with the location dependent manipulations. 

An alternative to using provides would be to just store it as new fields in the expansion struct, which might be what you're thinking of.

I don't think there's any reason for apologizing for not intuitively understanding how things work. I'm willing to answer question (although I can't guarantee to know the answer), and if you want me to look at something specific I can attempt to do so (again, without guaranteeing I'll actually understand it).

**Comment by haveric** [comment]
> However, you can also use flags to mirror things along an axis, such that you e.g. get the left and right residential wings of the base hub mirrored (and I think I've used for the base, which doesn't have any global orientation manipulation). You certainly don't want to pick up these flags, so care must be taken.

Good to know. I'll watch out for those.

> An alternative to using provides would be to just store it as new fields in the expansion struct, which might be what you're thinking of.

Pretty much exactly this. I think it'll be easiest to keep them as different things. Provides gets pulled up to the basecamp level, so I don't want to just use that. I'm looking at creating a new `blueprint_flags`, which just replaces the `flags` section on the survey. Next step is just to figure out where all I need to hook into it to keep functionality. Might change the name by the time I'm done, but I haven't come up with anything better yet.

> I don't think there's any reason for apologizing for not intuitively understanding how things work. I'm willing to answer question (although I can't guarantee to know the answer), and if you want me to look at something specific I can attempt to do so (again, without guaranteeing I'll actually understand it).

I think I was just a bit frustrated initially and wanted to be clear that I wasn't trying to blow away your work. I'll try to add some more documentation for this before I am done to make it more clear for future devs.


Tangent from everything else: I've been thinking about the potential future state of expansions/basecamp upgrades and one idea I keep coming back to is showing the player the preview of the upgrade. Similar to how zone construction or debug map changes work, we could show the entire layout before you build it, which could give people a better idea of what will be there. There's potential to also allow the player to manipulate the rotation/mirroring at this point with a bit of extra work. Not sure how feasible this will be, but it's something I'll consider looking into eventually.

**Comment by haveric** [comment]
> There are probably two different goals for previews, with one being "if I build this section, what will it look like, and where will it be placed" and the second being "if I build it all, what will it look like" (with the bonus of somehow being able to select the variant to use for each step).

This is basically what I'm envisioning. There'd probably have to be a "default" version that is chosen to be shown (and maybe options to switch the version that's shown).

> The second one isn't easy, especially if we'll get more intricate alternative uses than just the same construction using different materials.

Hadn't even thought of this, but that's a good thing to consider. Initial thought would just be to provide one (or multiple) possible outcomes just to give a general idea of what it will end up as. Not sure there's a perfect solution, but my hope would be that a general idea is better than nothing, but it'd have to be clear that it's only a possible outcome (at least for the initial survey).

This is mostly me thinking on what I _want_ it to work like and throwing out ideas that I'll maybe come back to someday. There's probably more important things to improve first, such as grouping the constructions by the same type, but I haven't come up with a good way to handle that yet either.

Not sure if you've got plans for any continued work for basecamps, but if you do, is there a good place outside of this PR that you'd be comfortable with to have long term discussion/goals for improvement? Preferably something like google docs where we could both make edits without it being a long thread of different discussions would be awesome.

**Comment by PatrikLundell** [comment]
The only current way to group constructions is by carefully select the short descriptions so they show up in the desired ordered in the alphabetic ordering currently used as the only available one. My guess is that to improve on that you'd have to somehow be able to attach keywords to blueprint (like e.g. "Keyword": {"Material", "Concrete"}, and "Keyword": {"Function": "Room NE"}, and possibly a way to use code to merge these parts into a short description.

Thing I'd want to see is much more extensive than things I think I might be able to implement... 3D construction (basement, additional floors, respecting orientation (which currently isn't even supported for things like subway stations...)), appliance networks as part of the base/expansion, 3D zone knowledge (to store stuff in the basement), a much better crafting UI, additional workshops, companion milking/egg collection/manure collection, companion crafting of fluids, scanning and detection of player built and destroyed functionality (well, forge, etc) rather than provides, etc.. Also note that at least one core team member has mentioned at least one of the areas above at least once.

As far as I understand there is one suitable place for this, namely the Discussions section, but it's locked.

**Comment by PatrikLundell** [comment]
I did suggest that the blueprints should be updated to support the application of a palette at a later stage, or allow for the palette to be overridden (allowing you to define the layout once, and apply it with different palette "interpretations". Unfortunately, it apparently got pushed down on the implementation priority list.
However, your take to group the recipes together in recipe groups might work to ease the UI level, but there would have to be some way to get the info to the UI (and, of course, for the UI to process it).

As I've mentioned, I'm horrible with names, but I think @I-am-Erk has posted about the crafting side of things, where he wanted to get away from individually adding crafting entries to base/expansions and rather have the available set based on capabilities provided by the recipe provider. No fine details were provided though, but something along the line that having a chemistry set would provide some functionality, adding centrifuges would add to that, and so on. I believe this was slightly before the introduction of appliances, so there might be a new opening there for introduction of gradual refinement that wasn't there at the time (assuming there's a way to integrate appliance functionality into base camp/expansion, e.g. through scanning).

**Comment by PatrikLundell** [comment]
I don't think scanning is difficult. There are already a bunch of pseudo items that are made available through provides, and it would be possible to look for furniture and appliances (don't think any is terrain) that would provide pseudo items. The big and tricky part would be to decide on fine grained functionalities (for cooking you might have oven capability, frying capability, ..., while for chemistry you might have long term stirring, spectrographic analysis, long term heating, microscopy, and a whole lot more. A hotplate would be considered a fairly crude heat source, while some recipes might require equipment capable of keeping an extremely steady well specified temperature for a specific amount of time, possibly with the ability to change to different temperatures automatically) and an even larger task to tag each recipe with all of these detailed requirements. The other great hurdle is the UI, as a single list with everything possible for an expansion won't really work.
I would actually think the UI ought to be the starting point, so it's capable of handling a large number of recipes without overburdening the player. The current categories in the player crafting UI seems like a useful starting point.

I don't think I've added much new to what was in the old discussion, with the exception of of the introduction of appliances, though.

**Comment by haveric** [comment]
I made the decision to move towards removing all of the duplicated mirroring/transforms and holy crap is that some major de-duplication (assuming I can make it work and convert properly). I've also got the overmap rotating properly now, which covers half of the cases needed.

Next step is to make overmaps support mirroring, which I don't think is technically too hard to implement, but I'm not 100% sure how to go about it. Mirroring has to happen first, so I'd imagine the oter_ids would look like:
`overmap_name_mh_north`, `overmap_name_mv_north`, `overmap_name_mh_east`, etc.

@jbytheway It looks like you worked on a lot of the overmap structure. Any chance I could get your advice or assistance in implementing these?

**Comment by PatrikLundell** [comment]
If the manipulation required is coded into the name, I guess there is a need for a function to strip the manipulation part from the name for usages such as searching for a particular kind (as I think you rarely care about its orientation when used as a target)?

Also, there might be a use for the opposite, i.e. only get the manipulations, e.g. for pairing subway station lower levels 
up with the surface level (as a future improvement by someone)?

Also, some orientation would be the canonic one, and I would guess that would be North, but it probably doesn't hurt to have the default orientation in the name. However, it might be a rather substantial task to update oter_its to the new format in existing saves.

**Comment by haveric** [comment]
All of that currently exists for the `_north`, `_east`, `_south`, `_west` rotations. I'm just looking to extend that to also include mirroring.

**Comment by jbytheway** [comment]
> @jbytheway It looks like you worked on a lot of the overmap structure. Any chance I could get your advice or assistance in implementing these?

So there are a few things going on in this thread and I may not have understood everything, but here are some more general thoughts:

* Your PR title "Cleanup basecamp primitive farm. Fix Plow fields" sounds like it should be two PRs, not one.  Some comments in the OP suggest you're already thinking of separating things out to some extent.  I'd definitely recommend not mixing concerns in a single PR, as far as that's feasible.
* Regarding the palette support for blueprints: that's still something I want to implement.  Unfortunately I haven't had time to work on CDDA in a few weeks now, so I'm not making any promises about that.  I will say that such support should be built around the more general concept of mapgen parameters, which includes multiple palettes, but also many other possible customizations.  You could even have multiple orthogonal parameters that vary a particular map in different ways (e.g. independently choosing the type of wall and type of roof, or choosing the materials separately from the layout).

On the subject of adding mirroring support for overmap tiles specifically:

* We only need one sort of mirroring to achieve all eight possible transformations.  Supporting both horizontal and vertical mirroring just means there will be two names for every transformation, which is bad.  If vertical mirror has never been used, let's rip that out.
* Currently there are three categories of `oter_type`: ones that don't support any transformations (e.g. `field`), ones that support rotation (the default case), and linear terrains whose form depends on their connections to their four cardinal neighbours (e.g. `road`).  For mirroring support, are you proposing to change the default case to also support mirroring, or to introduce a fourth category which supports rotation and mirroring?
* If you're planning to change the default, then are you proposing that pre-existing terrains will be flipped by default mapgen, in the same way that they are currently placed with random rotations?  In most cases that would be fine, but there are some terrains which have a defined sidedness (e.g. you want people driving on the right on roads).
* The rotation of OMTs is pretty deeply embedded in the codebase and scattered across many parts of it, so this will not be a simple task.  In particular, one of the hardest parts to grapple with is the GUI rendering code; you're going to need to figure out how to offer tileset authors the option to provide mirrored graphics, and implement a fallback which flips graphics in SDL when they don't.  Bear in mind that e.g. shadows will look wrong on tilesets whcih use them for this fallback approach.  There's also some "faux rotation" done for ASCII rendering, e.g. how houses can appear as `v`, `<`, `>`, or `^`.  That might need tweaking.
* The code is a real mess with regard to how it represents rotations and transformation currently, especially for linear terrains.  There are different enums, there's the concept of "rotation and subtype", some places use bitfields, and some places use various integer encodings of block drawing characters.  There's also confusion between absolute orientation and transformations between them.  For example the 'east' orientation is sometimes used to represent "rotate clockwise by 90°".

If I was going to tackle this then I would start by trying to rationalise this last point.  Make a clear separation between "the states that a particular `oter_type` can be in" and "transformations that act on those states".  Currently we have three possible sets of states and one set of transformations (rotations).  Ensure there is a C++ type for each of these sets and that they are used coherently throughout the codebase.  That should help make it clearer what code will need to change to support additional transformations.

But that's just how I would approach it, and that's a sufficiently daunting refactoring effort that I haven't embarked upon it, despite having a vague desire to.  So you'll probably be more successful in practice by just embarking on some changes and seeing what breaks.  Just expect to spend a long time chasing bugs and corner cases.

**Comment by haveric** [comment]
> Your PR title "Cleanup basecamp primitive farm. Fix Plow fields" sounds like it should be two PRs, not one.  Some comments in the OP suggest you're already thinking of separating things out to some extent.  I'd definitely recommend not mixing concerns in a single PR, as far as that's feasible.

Yeah, I wasn't planning on having to make the kind of changes that I now realize I need to for this, so it seemed like a good idea at the time to make those fixes as well. Obviously, the scope has changed completely since I started, so I fully plan to rip out some of the farm cleanup, but I haven't gotten to that yet as I've been working on other tasks.

> Regarding the palette support for blueprints: that's still something I want to implement.

Sounds like you have plans to take it further than I do at this time. I started looking at implementing it by allowing multiple constructions from one recipe, but that opens a rabbit hole of changes, so I'm holding off until I have more time to spend on it.

> We only need one sort of mirroring -  If vertical mirror has never been used, let's rip that out.

This seems reasonable, but it might be worth keeping the mirror vertical flag and having it convert to horizontal mirroring + rotation, if only for convenience. In terms of storing it for the overmap though, it should only need the one.

>  For mirroring support, are you proposing to change the default case to also support mirroring, or to introduce a fourth category which supports rotation and mirroring?

Because this is only used for basecamps at this time and to avoid creating bloat for other tiles, I feel like it makes sense to go the fourth category route. If other locations make sense to use it, they could gradually be moved to support it, but I'm not sure if it's even wanted outside of this use case.

>  GUI rendering code; you're going to need to figure out how to offer tileset authors the option to provide mirrored graphics, and implement a fallback which flips graphics in SDL when they don't. Bear in mind that e.g. shadows will look wrong on tilesets whcih use them for this fallback approach. There's also some "faux rotation" done for ASCII rendering, e.g. how houses can appear as v, <, >, or ^. That might need tweaking.

I assume you're referencing graphical overmaps here? If not, I'm not sure what you're talking about. I hadn't even considered that would be a concern because I don't use a graphical overmap. I feel like you could get away with just ignoring mirroring entirely for this or just flipping which is shown (if keeping with horizontal, east and west would flip when mirrored and the others could stay). I may be missing something here, so I'm not 100% sure.

> But that's just how I would approach it, and that's a sufficiently daunting refactoring effort that I haven't embarked upon it, despite having a vague desire to. So you'll probably be more successful in practice by just embarking on some changes and seeing what breaks. Just expect to spend a long time chasing bugs and corner cases.

If it's only a new type that is used just for basecamps, does that make it any less daunting? I was feeling pretty confident about the changes up until I realized that mirroring support would need to be added for this to work properly. I'm probably in over my head at this point, so I'll certainly take any support you can provide. I need to finish up some other projects as well before I can get back to working on this, but I should be able to cleanup the out of scope parts today or tomorrow hopefully so it's at least in a cleaner state.

**Comment by jbytheway** [comment]
> > We only need one sort of mirroring -  If vertical mirror has never been used, let's rip that out.
> 
> This seems reasonable, but it might be worth keeping the mirror vertical flag and having it convert to horizontal mirroring + rotation, if only for convenience. In terms of storing it for the overmap though, it should only need the one.

It's not clear to me when you would want to use such a flag, but I haven't looked at the existing use of mirroring.

> > For mirroring support, are you proposing to change the default case to also support mirroring, or to introduce a fourth category which supports rotation and mirroring?
> 
> Because this is only used for basecamps at this time and to avoid creating bloat for other tiles, I feel like it makes sense to go the fourth category route. If other locations make sense to use it, they could gradually be moved to support it, but I'm not sure if it's even wanted outside of this use case.

I think it could be useful.  e.g. semi-detached houses often come in mirrored pairs.  But starting with just basecamps sounds like a sensible first step.  The only downside of that is that very few players interact with the basecamp system, so bugs are less likely to be found.

> > GUI rendering code <snip>
> 
> I assume you're referencing graphical overmaps here? If not, I'm not sure what you're talking about. I hadn't even considered that would be a concern because I don't use a graphical overmap. I feel like you could get away with just ignoring mirroring entirely for this or just flipping which is shown (if keeping with horizontal, east and west would flip when mirrored and the others could stay). I may be missing something here, so I'm not 100% sure.

Yes, I mostly mean for graphical overmaps.  But there is some limited support for rotation in ASCII too, your simple solution will probably work except for mirroring linear terrain.  I'm guessing there's no linear terrain in what you're expecting to change?

For the graphical overmap, just mirroring the graphics will work for some tilesets but not others.  For example, shadows would be wrong if those were present.  So ideally you'd default to just mirroring the raw graphics, but provide an option for all eight versions to have different tiles if the artist wishes.  That probably doesn't have to be in an initial PR, though.

> > But that's just how I would approach it, and that's a sufficiently daunting refactoring effort that I haven't embarked upon it, despite having a vague desire to. So you'll probably be more successful in practice by just embarking on some changes and seeing what breaks. Just expect to spend a long time chasing bugs and corner cases.
> 
> If it's only a new type that is used just for basecamps, does that make it any less daunting? 

I have very little understanding of the basecamp system, so I'm not sure.  From the above discussion it sounds like there is already some limited support for mirroring within basecamp stuff.  Can you clarify in what way that is lacking?

There are probably easier short-term solutions, such as allowing a blueprint to be defined as the mirror of some other blueprint, but use a separate `oter_type`.  My gut says that is hacky, but perhaps full mirroring support is not worth the trouble?

> I was feeling pretty confident about the changes up until I realized that mirroring support would need to be added for this to work properly. I'm probably in over my head at this point, so I'll certainly take any support you can provide. I need to finish up some other projects as well before I can get back to working on this, but I should be able to cleanup the out of scope parts today or tomorrow hopefully so it's at least in a cleaner state.

Perhaps it's worth first taking the easy win of removing the duplication from rotation (which it sounds like you already know how to do?) since mirroring is a bigger ask.

**Comment by haveric** [comment]
> I have very little understanding of the basecamp system, so I'm not sure. From the above discussion it sounds like there is already some limited support for mirroring within basecamp stuff. Can you clarify in what way that is lacking?

The TLDR of this thread is that I am trying to get the correct reference to the layout of a field so that I can know which tiles are no longer plowed and need to be re-plowed to match the initial design. The current system did all of the transformations directly when constructed. As soon as it is built, the tranformations are lost. What I am attempting to do is to move the base transformations to the overmap tile, so that I have a way to reference it in the correct orientation later. Some of the constructions are mirrored instead of rotated, which is where I ran into issues. The secondary benefit to this is the reduction of 5-6 thousand lines of duplicate transformations for every construction.

> Perhaps it's worth first taking the easy win of removing the duplication from rotation (which it sounds like you already know how to do?) since mirroring is a bigger ask.

Without being able to handle both, this just leaves it in a half broken state unfortunately.

> Yes, I mostly mean for graphical overmaps. But there is some limited support for rotation in ASCII too, your simple solution will probably work except for mirroring linear terrain. I'm guessing there's no linear terrain in what you're expecting to change?

Good to know. Everything for basecamps is individual tiles, so I don't think that's a concern at this time.

> I think it could be useful. e.g. semi-detached houses often come in mirrored pairs.

Seems reasonable as something this could provide support for down the road, but I don't think is too much of a concern at this time.

> But starting with just basecamps sounds like a sensible first step. The only downside of that is that very few players interact with the basecamp system, so bugs are less likely to be found.

There's a lot more people interacting with basecamps these days and that will only increase as they get improved.

> It's not clear to me when you would want to use such a flag, but I haven't looked at the existing use of mirroring.

This would mostly be a convenience thing. The example Patrick gave above is being able to flip a specific construction (build west/east, north/south bedrooms or wings of a structure)

**Comment by anothersimulacrum** [comment]
Closing as stale, no activity in over 2 years.

**Pull request closed without merging**
