### PR TITLE
Fix arachnids samples

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Bugfixes "fix arachnids lack of samples"

#### Purpose of change
Dragonfly naiads (babby dragonflies) give spider samples if dissected, because they use drop type 'arachnid'. The giant dragonfly (grown up version) uses arachnid_flying but that doesn't have any sample in it, and neither does the fused dragonfly which uses arachnid_flying_mega

#### Describe the solution
Add `arthropod_sample` to `arachnid_flying`, `arachnid_firefly` and `arachnid_dragonfly_mega`

#### Describe alternatives you've considered

not adding them

#### Testing
butch giant mosquito, got spiders and insect sample

#### Additional context
not my pr, all honors to `@JantDarvus#0415` from discord server

### CODE REVIEW

**Comment by Venera3** [comment]
As far as I can see `arthropod_sample` isn't a thing unless you're adding one. You can just shift spiders' harvest entries to a `actual_arachnid` harvest list with spider samples and have the rest butcher into insect ones.

**Comment by GuardianDll** [comment]
as i said before, thats not my pr, and i barely understand what im doing
if you say there is something wrong i can close it, or you can write right to JantDarvus about this (afaik he is dead tired today, so mayve tomorrow)

**Comment by JantDarvus** [comment]
> As far as I can see `arthropod_sample` isn't a thing unless you're adding one. You can just shift spiders' harvest entries to an `actual_arachnid` harvest list with spider samples and have the rest butcher into insect ones.

Arthropod sample was suggested as an alternative to just giving them spider sample since it keeps them in line with the dragonfly naiad (which gives a spider sample, which I suspect is erroneous but is nonetheless what's established) but also still gives the chance for insect samples (which are what they should probably be giving instead).

Looking it up, arthropod sample is used by the arthropod mutants and it allows them to drop both spider and insect samples. I really don't know enough of the code to understand any deeper how it works, but it does, apparently, with HHG showing them dropping both.

This whole thing was just me being fairly sure of how to band-aid fix a problem but really not having the current mental wherewithal to understand how you actually get these changes made and Dil being very kind and putting them through for me.

**Comment by Venera3** [comment]
That's nice, but "dragonflies drop spider samples half the time" isn't the proper way to fix to "dragonflies don't drop insect samples".

Step one: add <insect> harvest list copying over the current <arachnid> entries, substituting insect sample for spider ones
Step two: replace <arachnid> with <insect> for non-spider critters
Step three: add insect samples to <arachnid_flying>
Step four: cut up a spider, an ant and a dragonfly to check if everything works properly.

**Comment by Venera3** [comment]
Beats me, the harvest list was called arachnid when I got here (and there being no functional differences until samples became a thing meant I built upon that naming convention).

**Comment by GuardianDll** [comment]
im not sure i understand what needs to be done, so i just close this one

**Pull request closed without merging**
