### PR TITLE
Added expected thickness multiple for materials

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Added expected thickness multiple for materials"

#### Purpose of change
Based on #54256 layered kevlar should be exactly 4.4mm. While implementing this I realized I should probably just add the option to force this with a warning if it is wrong.

#### Describe the solution
 So I've moved everything that "should" be that to exactly 4.4mm and everything that shouldn't be (or is way too thin to be) to regular kevlar. 

As well I've added code infrastructure for materials to have a "sheet_thickness" then any item made out of them requires a thickness that is a multiple of that number (since the fabrics would be layered). This is currently only implemented for layered kevlar but could be extended in the future to all materials in #54256 

Also this only works for advanced material defined armor, proportional material defined armor would be too wishy washy for it.

I've also added for odd cases the ability to "ignore_sheet_thickness" I use this on the Kevlar Gambesons since they *total* to 4.4mm thickness but it's basically impossible to infer that from the def.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
Should coverage values for unlayered kevlar be updated alongside? Regular kevlar is flexible and can be worn pretty much normally. Example: Draggin-brand kevlar long-sleeved shirts. Lots of "street clothes" can be outright made of kevlar and nothing else but be comparable in flexibility to cotton.

**Comment by bombasticSlacks** [comment]
Yeah I own a pair of kevlar pants. 

Keep in mind the functional difference between layered kevlar and kevlar was 1 bash resist. They are the same material just with the added value that layering them helps better distribute energy. 

So yeah the game could have kevlar tshirts and stuff but they would be much thinner than what has been changed here and out of the scope of this discussion.

**Comment by Drew4484** [comment]
Can I add sheet thickness to chainmail (or other materials) and get the same enforcement?

**Comment by bombasticSlacks** [comment]
exact same, I have a partial PR with the fabrics from the fabric overhaul already done. I just didn't want to overload the feature PR with content.

**Pull request merged**
