### PR TITLE
Added new dairy farm location

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Added new dairy farm location."```

#### Purpose of change
More content, more locations, more easter eggs!

#### Describe the solution
- Added a new 4x3 dairy farm location, its layout is entirely based on a location from a well-known video game with a handful of my own tweaks here and there;
- Filled farm with iconic characters from the game. There are only 5 monsters on the location, 4 of them being zombies. All creatures have names;
- Location has a very low (5%) chance to spawn on every overmap;
- Added salt lick item and made it spawn on the farm;
- Added dirt floor with no roof terrain type and extensively used it in the mapgen.

#### Describe alternatives you've considered
None.

#### Testing
A lot of debug spawning of the location to check if everything is ok.

#### Additional context
I have a problem with spawning of a vehicle on my location. I want to spawn a portable generator and used this snippet:

```
"vehicles": { "J": { "vehicle": "portable_generator", "chance": 100, "fuel": 40, "status": 1 } }
```

But unfortunately generator isn't spawning on `J` symbols on the map, and I have no idea why. I'd appreciate any help on this matter.

<details> 
  <summary>One screenshot from a bird-eye view. It reveals a portion of a "secret" layout, so I'm putting it under the spoiler</summary>

изображение

</details>

### CODE REVIEW

**Comment by RarkGrames** [comment]
The salt lick gave it away instantly. :D

**Comment by ZhilkinSerg** [comment]
You can try to use `place_vehicles` as a workaround, e.g.:

```
"place_vehicles": [ { "vehicle": "small_utility_vehicles", "x": 11, "y": 22, "chance": 50, "fuel": 20, "status": 0 } ]
```

**Comment by Night-Pryanik** [comment]
> You can try to use place_vehicles as a workaround

I tried that too. It didn't work either.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > You can try to use place_vehicles as a workaround
> 
> I tried that too. It didn't work either. I even tried to create a vehicle group with only generator in it, and tried to place that group. It didn't work either.

I think there is small issue in json - you should probably put only one `J` as you want to spawn a single generator (vehicle has size 2x1).

Anyway, it behaves pretty strange and won't spawn a vehicle reliably - could be some regression in vehicle placement regarding placement chances.

**Comment by Night-Pryanik** [comment]
> I think there is small issue in json - you should probably put only one J as you want to spawn a single generator (vehicle has size 2x1).

I tried putting one, two, three, four `J`s in a row, in a triangle, in a square - with no avail.

**Pull request merged**
