### PR TITLE
Revert "[RDY] Make ranged attacks use a zero-centered dispersion distribution."

### PR DESCRIPTION
**Pull request by mugling**
Reverts CleverRaven/Cataclysm-DDA#18943

The idea is is reasonable but it wasn't tested via the stats dumper/graph output code and in the process probably breaks it. Loss of that functionality would be a huge regression and needs verifying (and probably fixing) before that PR could be merged.

### CODE REVIEW

**Comment by mutability** [comment]
sadpanda

**Comment by mugling** [comment]
> sadpanda

The work was good - we just need to resolve the unintended breakage

**Comment by mutability** [comment]
As now discussed in the original PR, this does not break the stats dumper/graph output code. The output hasn't been examined but I don't think that is the objection here.

Can you revert the revert please?

**Comment by mugling** [comment]
The original PR's were subject to the following constraints:

* Aiming code is critical and needs extensive testing
* Aiming code requires testing framework to guard against regressions

> The output hasn't been examined

You need to test and verify this first.

> but I don't think that is the objection here.

This is the objection. The code isn't necessarily wrong but as neither the PR author nor merge tester checked this it's reasonable to require this first. It wasn't me who declared the above requirements critical but I did comply with them, broadly agree, and expect the testing framework to be maintained.

Quoting #18943

> you could do it directly analytically if you had an inverse-erf function, but the standard library doesn't provide one and my knowledge of that area is not good enough that I would be happy writing it myself

The previously implementation was the direct inverse operation. I agree I don't think I would be confident writing an inverse operation here either but that highlights the problem:

Both myself and @Coolthulhu understood the math behind the previous implementation well but we still made some significant errors (which you identified). There is no guarantee this PR doesn't contain similar problems and indeed as the complexity is higher and we didn't apply a lot of the previous testing the risk is arguably higher.

> I reviewed the changes and they looked similar enough

In the previous PR's there was insistence that I wrote stats and graphs before proceeding further. It's unreasonable to now change that view to *"eyeball it and fix later if necessary"*.

> Do we have any automated tests that are broken here?

Did you run the unit tests? `test_internal` in `gun_aiming.cpp` provides a very minimal sanity check. 

One potential route to resolving this could be to extend the checks there to ensure that the various calculations are commutative/reversible?

**Comment by mutability** [comment]
You have misunderstood my comment about inverse erf

**Comment by mutability** [comment]
So to be clear you reverted not because of any specific breakage but
because a set of tests that are vaguely specified, were never mentioned in
either the original issue nor during the PR process, may or may not fail
but you don't know because you haven't tried them?

If that is the consensus then I wish you luck and I don't have more time to
spend on this.

**Comment by mugling** [comment]
> So to be clear you reverted not because of any specific breakage but because a set of tests that are vaguely specified, were never mentioned in either the original issue nor during the PR process

They are mentioned in the original aiming PR's and in any case it would be reasonable to check what code is using the functions you are updating - this includes the unit tests. It shouldn't have been merged without that testing so this just puts us back to where things were 24 hours ago and avoid the risk you work on a dependent branches in the interim.

> may or may not fail but you don't know because you haven't tried them?

No I haven't run them but @Coolthulhu's comment suggests they weren't run prior to merge testing which does rather obviate the original requirement to write them. Presumably as you don't know about them you also didn't run them either before submitting your PR? Given that I was required to write them it's reasonable to expect that someone (author or merge tester) actually runs them.

> I wish you luck and I don't have more time to spend on this.

Which is precisely my concern that once it's merged nobody will bother to check. You've proved my point perfectly in that respect.

To reiterate:

> One potential route to resolving this could be to extend the checks there to ensure that the various calculations are commutative/reversible?

**Comment by mutability** [comment]
I think the onus is on you to show breakage if you're going to do an emergency revert.

I can look at the points you raised after the changes are reapplied. But not before then; I don't want to get into an neverending cycle of "oh, and one more thing you need to fix which I didn't mention before" which I have seen happen in other PRs. Sorry. I will just maintain my changes in my own fork.

**Comment by mutability** [comment]
To expand on my comment about inverse-erf.

`gun_current_range` already inverts the logic of `projectile_attack`.
It does so by iterating over possible ranges.
You could avoid the iteration and find the inverse directly if you had an inverse-erf function.
But it's an implementation detail.

**Comment by mugling** [comment]
> I think the onus is on you to show breakage if you're going to do an emergency revert.

No, the onus was on the merge tester to check for regression in code that they themself specifically requested was written and had declared critical.

> But not before then; I don't want to get into an neverending cycle of "oh, and one more thing you need to fix which I didn't mention before"

You haven't lost anything here versus had your PR not been merged. I could understand if we were two weeks in and you had done lots of dependent branches but that isn't the case.

> I can look at the points you raised after the changes are reapplied.

Your earlier comments stating you don't intend to further work on it aren't helpful here but in any case it can't be merged until someone has checked the stats dumper works as intended. I've outlined one possible route although there may be others.

**Comment by mutability** [comment]
I'm sorry, perhaps you misunderstood what I wrote.

If it is accepted practice to do emergency reverts on an issue that you hadn't even commented on because a test which you consider important, which was never raised during development, might (might!) be failing. Then that is an unreasonably high bar, and I am not interested in jumping through those hoops to contribute, and I will put my spare time towards other projects.

If that was just a mistake/misunderstanding and you're happy to reapply the changes and deal with any subsequent problems in an incremental way, not via a scorched-earth policy, then I am happy to continue working on it.

Let me know which it is.

**Comment by mutability** [comment]
A good starting point to making progress here would be to describe what the test you want run is, and what the expected results should look like.

**Comment by mutability** [comment]
A note re unit tests: I get dozens of unit test failures on master, so..

**Comment by mugling** [comment]
There's too much passive-aggressiveness in your replies so I'll be blunt:

You are working on some of the most critical code in the game. Your earlier work shows you are a capable developer (for example you were able to navigate git history). I expect you to be reasonably familiar with the area you are choosing to work on, especially as there was extensive recent discussion. If you feel these 'hoops' are too much for you then yes, it may be better if you focus your efforts elsewhere.

There is absolutely no mistake here. Your PR fails the unit tests in `gun_aiming.cpp` which strongly suggest you've broken the unit tests, stats dumper and aiming graphs.

You've told me first that you don't have time for fixes and then later that they are conditional on a merge. This argument is called *"my way or the highway"* and the problem with it is that sooner or later the proposer inevitably forces the latter.

At best your code is untested. Dependent upon the cause of the unit test failures it may also be broken. We should work through it and find out why. But be clear though - if you want this to be a choice between your way or the highway it's going to be the latter.

**Comment by mutability** [comment]
If I get the unit tests passing, will you reapply this?

**Comment by mutability** [comment]
(Er, I mean, the aiming tests. As I said I get dozens of unrelated unit tests failures on master, so I'm not suggesting I'm going to fix them all!)

**Comment by mutability** [comment]
In terms of "reasonably familiar with the area". Nope! Never touched it before. That's why I raised an issue asking about the intent of the code. @-mentioned you since you were the last to touch it, talked with @Coolthulhu extensively, put together a PR, got feedback on it, wrote some simulation code to satisfy myself that it worked well, and got it to the point where it was merged.

I hope you can see why it is an unpleasant surprise, after having done all that, to suddenly be presented with a revert and an extra list of stuff that needs to be done, especially given that I tried to involve you (as the last one to touch the code) from the start and got no feedback.

I saw exactly the same thing happening in #18514; you are making it very difficult to actually contribute changes and I think the project suffers because of it.

**Comment by mugling** [comment]
> In terms of "reasonably familiar with the area". Nope! Never touched it before

It's critical code so you aren't entitled to use your above argument of ignorance about prior PR's and unit tests.

> I hope you can see why it is an unpleasant surprise, after having done all that, to suddenly be presented with a revert and an extra list of stuff that needs to be done,

Yes, but you've gone from surprised to unequivocally offensive. What precisely have you lost from a revert a few hours later other than that you actually have to fix your bugs (which your earlier comments suggest aren't important to you)?

> I tried to involve you (as the last one to touch the code) from the start and got no feedback.

Your PR has been open for 6 days - I'm not obliged to sit and babysit the project every moment of my waking life. More than any other developer I write documentation. You had available to you extensive documentation both in previous PR's and within the functions themselves along with unit tests and the stats code.

> you are making it very difficult to actually contribute changes

Your code is broken:

* It fails the unit tests
* Stats graphs look suspiciously different
* Output stats are definitely significantly different

We don't want or need broken code, especially when a new contributor proposes that bugfixes are in any way conditional.

Before you go any further I'll ask you again to explain why a prompt revert in the face of breakage is a problem unless you aren't intending to actually fix those issues?

**Comment by mutability** [comment]
If another developer (perhaps @Coolthulhu) wants to work with me on this then I can continue, but I think enough bridges have been burned here that I'm going to stop work on this otherwise.

I'll maintain my changes in my repo.

**Comment by mugling** [comment]
You asked for and received a list of known breakges and requirements in #18943 so you should work through those.

> Before you go any further I'll ask you again to explain why a prompt revert in the face of breakage is a problem unless you aren't intending to actually fix those issues?

**Comment by mutability** [comment]
I'm fixing them locally; you can look in my repo once they're pushed there.

**Comment by mutability** [comment]
nb. haven't actually found any breakages in the main code yet, it's all test regressions

**Comment by mugling** [comment]
> I'm fixing them locally; you can look in my repo once they're pushed there.

You can submit a PR that includes all of the bug fixes.

> nb. haven't actually found any breakages in the main code yet, it's all test regressions

A lot of values have definitely changed. It's not known how by how much but they look to be significant.

**Comment by Coolthulhu** [comment]
@mugling Can you state a list of goals that this PR should fulfill? It's easier to work on it when it's all explicit, in one list.

So far I see:
* Unit tests working (just the gun_aiming.cpp ones?)
* Output stats (ranges?)
* Stat graphs (hit ratios?)
* Displaying a graph of before and after (needs specification: how many, for which dispersions?)
* That reverse erf iteration part (not necessary?)

> What precisely have you lost from a revert a few hours later other than that you actually have to fix your bugs (which your earlier comments suggest aren't important to you)?

Reverting PRs like that was unprecedented and can be easily seen as an offense. It suggests that it is no longer a slip-up, but a full fuck-up that needs immediate removal.
From the objective side it isn't a big deal, but it's clearly personal on both sides now and it didn't need to be.

> I'm fixing them locally; you can look in my repo once they're pushed there.

Push the PR again - it's much easier to compare, comment and review that way.
Plus, it informs everyone else what is being worked on, which will help to avoid merge conflicts.

> If another developer (perhaps @Coolthulhu) wants to work with me on this then I can continue, but I think enough bridges have been burned here that I'm going to stop work on this otherwise.

I will review and help all I can, but it will still be up to @mugling to confirm that the requested changes are fulfilled.
If the changes requested are objective, that would be pretty easy to verify, though.

**Comment by mutability** [comment]
Thanks. If I can get that list then I'll set up a new PR.

**Comment by mugling** [comment]
> Reverting PRs like that was unprecedented and can be easily seen as an offense. It suggests that it is no longer a slip-up, but a full fuck-up that needs immediate removal.

It breaks the unit tests and includes unintentional changes to all of the stats. It may well have other breakages as well but the unit tests alone are sufficient grounds - why do they exist if we don't actually run them? These aren't legacy unit tests - they were written at the express request of other developers precisely for such situations. 

I was quite clear about this from the start:

> The work was good - we just need to resolve the issue with the stats dumper

You can compare and contrast the comments from there but we're probably better moving back towards objective issues...

> From the objective side it isn't a big deal

Correct. It should make no difference (providing the reversion is prompt and without dependent branches). It is of course a different matter if it occurs days to weeks later.

> Thanks. If I can get that list then I'll set up a new PR.

Sounds good. This is the development model - we don't do private branches. You already have some patches to your original that improve the situation so an new PR is your best approach. Once you have considered all of the initial suggestions in this and #18943 we can go through a review cycle on that PR.

**Comment by mutability** [comment]
Still need that list.

**Comment by mugling** [comment]
Start with the list in  #18943 and @Coolthulhu's above suggestions. In any case any given list is non-exhaustive if further issues are identified. You should submit a PR addressing as much of the existing issues as possible.

**Comment by mutability** [comment]
I need a clear end point to the PR before I start. Can I get an explicit and bounded list, here, of things you would need to see before accepting the PR?

**Comment by mugling** [comment]
> Can I get an explicit and bounded list, here, of things you would need to see before accepting the PR?

No, because that doesn't exist. The purpose of review is to identify any further issues.

> I need a clear end point to the PR before I start

Submit your PR with the existing suggested changes and then wait for feedback. @Coolthulhu is correct in that it's easiest to review actual code (we don't do private branches).

**Comment by mutability** [comment]
Ok, I'm sorry that we can't make progress on this and I'll continue to maintain it separately.

**Comment by mutability** [comment]
Since it seems unlikely at this point that my work is going to get used any time soon (if at all), I'll raise issues for the bugs I encountered along the way so they can be fixed separately.

**Comment by mugling** [comment]
That's your choice. Submitting a PR with your amended code doesn't involve any additional work on your part and remains an option to you.

**Comment by mutability** [comment]
The reason I don't want to open a PR without a clear end point is that it absolutely does require additional work on my part to create, cherrypick, and maintain a branch separate from the branch I actually play on, and I want some assurance that the PR isn't going to die in a never-ending list of "oh, and one more thing..".

**Comment by mugling** [comment]
Your code is objectively broken so the next step is to submit an amended version. We only review and merge PR's and nobody is in a position to issue you any guarantees.

**Comment by mutability** [comment]
What do I need to do to get a list of things that you want fixed out of you? I mean, this is the stumbling block: I still do not have a clear idea of what your concrete objections are.

**Comment by mutability** [comment]
I'm happy to work with @Coolthulhu's list, FWIW; what do you want to see in addition to that?

**Comment by mugling** [comment]
**Submit a PR with your latest code**. This is no doubt filling everyone's inboxes so I'm closing this thread here and we can continue further discussion as and when there is actual code to be discussed.

**Pull request merged**
