### PR TITLE
Added a sunroof part for vehicles

### PR DESCRIPTION
**Pull request by drachs**
#### Summary

SUMMARY: Features "Adding Sunroof Part to Vehicles"

#### Purpose of change

I had a character who didn't like to wake up with his alarm.   I thought, "Wouldn't it be nice if I had a sunroof to help drag him out of bed in the morning?".

#### Describe the solution

This change adds a sunroof part.  The part is basically a light that shines as the current daylight when enabled.  The blinds on the sunroof can be opened and closed.   It enables the light when it's open.

#### Describe alternatives you've considered

I tried making the sunroof transparent to sunlight, so the interior of the vehicle could be lit naturally.  Turns out sunlight never lights interior regions except for in the horizontal direction during spreading. 

I considered actually looking up light from the Z-level directly above, but it seemed like overkill.  Happy to do it if you want it though.   Maybe some day there will be a bridge where someone parks their RV underneath and files a ticket that the bridge isn't properly occluding the light.

#### Testing

I played it in my own game for some time and used it to purpose.

### CODE REVIEW

**Comment by drachs** [comment]
I don't think the problems with the the Travis CI build are related to my code.  Is there anything in particular I should do to clear them?

**Comment by anothersimulacrum** [comment]
Not your fault, nothing to really do about it.

**Comment by mrkybe** [comment]
Although there's no bridges to park under, there are plenty of garages with cars in them that would conceivably have sunroofs (4x4s, sedans, etc).  I think this needs to use the actual light-level for that tile so that you can't hide in a garage and have free light at the same time.

**Comment by drachs** [comment]
In the case of a garage, the Z level above would probably be over the roof wouldn't it? If so it would be lit and I don't think that would end up helping.

**Comment by ZhilkinSerg** [comment]
Sunroof cannot be closed/opened a creature is on the same tile.

**Comment by ZhilkinSerg** [comment]
Closing to clean up PR queue. Feel free to make requested changes and reopen.

**Pull request closed without merging**
