### PR TITLE
Check for player sight in fling_creature and some monattacks

### PR DESCRIPTION
**Pull request by Coolthulhu**
`game::fling_creatures` would add_msg and redraw the screen even when the player didn't see it happen.
Now it only adds_msg if creature's new position is seen and redraws if the last position is seen.

Also suppress add_msg for jabberwock and bio-operator when the player can't see them.

Oh, and unlocked bio-op's special attack when it's friendly, because it should work fine now.

### CODE REVIEW

**Comment by kevingranade** [comment]
Shouldn't it redraw if the previous *or* next position is visible?

**Comment by DavidKeaton** [comment]
Eyebots being attacked isn't suppressed either if out of LOS. :-)

**Comment by KA101** [comment]
Eyebot attack seems more a generic issue, but yeah.  Can be addressed separately if need be.

**Comment by KA101** [comment]
ZAPBACK kicking in gets reported when not visible.  Not a dealbreaker.

**Pull request merged**
