### PR TITLE
Add a github action to keep doc/JSON_INFO.md table of contents up to date

### LINKED ISSUE #46806: Some links in the JSON_INFO.md table of contents are not clickable
# Describe the bug

While most links in the ToC are clickable, some are not. For example clicking on json/&nbsp;>&nbsp;Harvest&nbsp;>&nbsp;id does nothing. It seams some links have an extra minus symbols in them.

# Steps To Reproduce

1. To to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md
2. click on json/&nbsp;>&nbsp;Harvest&nbsp;>&nbsp;id

# Expected behavior

Navigation to the correct location in the document

# Screenshots

none

# Versions and configuration

N/A

# Additional context

none

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary

SUMMARY: None

#### Purpose of change

Fixes #46806 . Many links in the doc/JSON_INFO.md TOC did not work (anchor names are wrong). Plus it is out of sync with the document.

#### Describe the solution

This PR **adds a github action** to keep doc/JSON_INFO.md table of contents up to date.
* **Warning**: github actions are dangerous. They have complete write access to the repository by default ([details](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token))
* **Warning**: this is my first time using github actions and I have probably screwed something up
* **Warning**: I have **not** performed an audit of the source code of the action

#### Describe alternatives you've considered

Have someone occasionally run a TOC generator locally and check in the result manually.

#### Testing

https://github.com/hexagonrecursion/Cataclysm-DDA/blob/master/doc/JSON_INFO.md
Click on the links - they work.

#### Additional context

none

### CODE REVIEW

**Comment by BrettDong** [comment]
Does TOC generator bot have the permission to commit on `master`?

**Comment by hexagonrecursion** [comment]
It did commit to my master while I was testing it. https://github.com/hexagonrecursion/Cataclysm-DDA/commit/20589a3a947440c44a8f93f30a17e4db0e4ca6fd . I don't know if it is possible to prohibit a github action from committing to master.

**Comment by anothersimulacrum** [comment]
The TOC generator bot does not appear to be a proper github account, it's just who the commits are attributed to, so I don't think permissions apply to it so much.

**Comment by BrettDong** [comment]
You wrote the action to be triggered by a push to master branch, so I am curious how it is going to work.

**Comment by hexagonrecursion** [comment]
> You wrote the action to be triggered by a push to master branch, so I am curious how it is going to work. Because only maintainers like Kevin and ZhilkinSerg have write access to master branch.

As stated above I'm a newbie. I expect the action to be triggered [after a PR is merged](https://github.com/CleverRaven/Cataclysm-DDA/actions?query=event%3Apush). We could test that.

**Comment by hexagonrecursion** [comment]
Note: it is only triggered when a PR touches doc/JSON_INFO.md

**Comment by BrettDong** [comment]
I still don't understand how this works. What will happen if someone touches `doc/JSON_INFO.md` and breaks its TOC? Who and how does this GitHub Action commit to `master` branch? Don't you need [API tokens](https://github.com/technote-space/toc-generator#addition)?

**Comment by hexagonrecursion** [comment]
> Who and how does this GitHub Action commit to `master` branch? Don't you need [API tokens](https://github.com/technote-space/toc-generator#addition)?

I'll do some more testing on my end.

**Comment by hexagonrecursion** [comment]
> https://github.com/technote-space/toc-generator#addition
> The GITHUB_TOKEN that is provided as a part of GitHub Actions doesn't have authorization to create any successive events.
> So it won't spawn actions which triggered by push.
> 
> This can be a problem if you have branch protection configured.

Here is my current understanding of the situation:
* github branch protection offers many knobs. One of the knobs is "Require status checks to pass before merging". This knob can be used to specify a list of automated checks that have to pass before a commit can be pushed to a branch
* A common method of implementing status checks is via a github action
* Every github action added to a repository automatically gets a [GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow). This token grants the action [access to a bunch of github features](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) as well as write access to the git repo via `https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}` ([example](https://github.com/hexagonrecursion/eve/blob/e73d17cede872a106c7b9ee83ad3979bd911b4fc/action.yaml)).
* Based on my testing there does not appear to be any way of blocking an action from accessing the token
* > https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow 
  > When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.

**If** pushing to a branch requires status checks that are **implemented via a github action A** then in order to push to the branch a github action B would have to either fake the check (I have not testes yet if this is possible) or trigger the github action A (eg using a personal access token).

**Comment by hexagonrecursion** [comment]
I can confirm that a github action did fail to push to a branch configured to "Require pull request reviews before merging"

https://github.com/hexagonrecursion/alice/runs/1783744555?check_suite_focus=true

**Comment by hexagonrecursion** [comment]
I do not have sufficient permissions to the CleverRaven/Cataclysm-DDA repo to see the branch protection rules.

**Pull request merged**
