### PR TITLE
Added noise support for reloading

### PR DESCRIPTION
**Pull request by CIB**

### CODE REVIEW

**Comment by DavidKeaton** [comment]
this I like

**Comment by CIB** [comment]
Maybe I should add the noise strings/loudness to various types of guns in the JSON, but I don't know the first thing about guns or how reloading them sounds.

**Comment by Rivet-the-Zombie** [comment]
>Maybe I should add the noise strings/loudness to various types of guns in the JSON

This sounds like a grand idea; most firearms make *very* little sound when reloaded (contrary to what Hollywood and vidjagames would lead you to believe) and stuff like bows/crossbows are pretty much silent unless you're super clumsy.

**Comment by kevingranade** [comment]
Just fyi, added a check for volume <= 0 while merging, I'm not sure it
makes sense to repeat that check, or to have the function silently bail out
when volume is negative or zero.

**Pull request merged**
