### PR TITLE
Challenge start - hunted forever

### LINKED ISSUE #73220: Revivable Nemesis
### Is your feature request related to a problem? Please describe.

The nemesis start is a fun and interesting challenge for players, one of the key aspects of it is 'winning' via killing the nemesis (Relentless Hulk) and having the game take down your "Hunted" Trait.
What if however that instead of the hunted trait disappearing it remained and the Hulk would return in a few days as respite for the player before once more continuing it's hunt down of said player.

### Solution you would like.

Perhaps there could be a new scenario and trait expanded on top of the previous "hunted" trait which forces the player to always have a hulk hunting them down no matter how often they kill it. Even if the hulk were to die it would "come back" or a new one would spawn that would constantly keep the player on their toes at all times. Could possibly add on top of it that not only does the hulk return, but it comes back faster/stronger so the player would see an increase difficulty than the last.

### Describe alternatives you have considered.

Not expanding the Hunted scenario.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Content "Challenge start - hunted forever. Starts with the nemesis, but it comes back stronger everytime it dies"

#### Purpose of change
* Closes #73220

#### Describe the solution
Add some code to wrap around the nemesis mission causing it to respawn on death unless we've reached the kill count (of 1). Gave the existing nemesis mission a kill count (of 1) so it doesn't respawn. Give any monster with the NEMESIS flag a permanent effect which has a JSON-defined enchantment that powers up as more nemesis die (counter is increased by dead nemesis' death function, can be increased by other JSON means as normal too).

#### Describe alternatives you've considered
Fully EOC'd?

#### Testing
~~Currently in draft because this is not how you do JSON enchantments (it whines that the value isn't constant. Of course it isn't!)~~ It is how you do JSON enchantments! It just wasn't evaluating the values at all, which is why it expected a constant.

Spawned and killed some nemesis, no errors.

Spawned and killed a LOT of nemesis, got punted around like a soccer ball as the super-speedy nemesis proceeded to dash across the screen in a single turn. Debug teleported back towards it and tried to kill it with a tempered steel katana only for the weapon to ineffectually bounce off its now 100+ armor.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Swole is a real word, fight me dictionary bot. You won't. You're not swole.

**Comment by Qrox** [comment]
You can make the dictionary swoler with words by adding swole to it.

**Comment by RanikOrtega** [comment]
> to what forms?

Well This nemesis is a direct reference to RE3 Nemesis. His first form is him running around in coat with bazooka. His second is after he is defeated and regenerates. He loses the weapon but gains tentacle attacks.

https%3A%2F%2Fi.redd.it%2F639nz1zuurh41.jpg&f=1&nofb=1&ipt=cc3101727b41075ff10d29676a2bdb5d838cec028d9018e1960b1cceaf317dc7&ipo=images

Third form is basically giant mutated dog thing
http%3A%2F%2Fimages6.fanpop.com%2Fimage%2Fphotos%2F35200000%2FResident-Evil-3-Nemesis-resident-evil-35242186-1024-768.jpg&f=1&nofb=1&ipt=b1b7a3072e31e4e07f405e5ddaff1687737930b9280b17f2fd5aedae2db0f56b&ipo=images

**Comment by GuardianDll** [comment]
i think that's pretty much overkill

**Comment by RanikOrtega** [comment]
> i think that's pretty much overkill

Overkill yes. But I just found it neat and thematic.

**Comment by Nebnis** [comment]
While we don't have to copy resident evil i like the idea of the hulk evolving because eventually the player will get too strong and it will be a nuisance at best

**Comment by Standing-Storm** [comment]
Looking forward to giving this thing increasingly-strong psionic powers in MoM

**Comment by RenechCDDA** [comment]
Enchantment code/enchantments added to monsters wasn't previously set up to actually evaluate conditions inside the enchantment. Now it is.

**Comment by RenechCDDA** [comment]
> I like this idea but man I'd love if instead of just getting a buff, it mutated to 2nd and 3rd forms.

I don't think we currently have a way to do this in JSON, but if you know of a way I'm open to listening. At the very least this PR just makes a simple provision to respawn the nemesis when appropriate (the new scenario), a little kludge to get the effect onto our nemesis friend, and then all the important JSON-y bits to go from there. 

So if we do have a JSON way to do that, it can always be bolted on later. Or the effect and enchantment can be tuned up/down/sideways/whatever as desired.

**Comment by Nebnis** [comment]
Can you cage him? And prevent the buffs.

I would like to believe that an incremental buff to hp and damage is better than speed and armor. At least not speed so you can run away. I know you might have gone with a doomed to die scenario with this PR, but i would like the scenario more if there was just an everlasting growing threat. If his damage increases, he would be able to bash down concrete and stuff too to get to you.

**Comment by I-am-Erk** [comment]
> Debug teleported back towards it and tried to kill it with a tempered steel katana

Nothing personnel, kid.

**Pull request merged**
