### PR TITLE
Remove boozeberry and stawberry surprise

### PR DESCRIPTION
**Pull request by Cyrano7**
The descriptions don't make any sense  The items are very unbalanced. The recipes are narrow needing a open fire to make . No bartender would ever make this and even the descriptions say they are gross. Storing fruit in alcohol is a way of preserving it. But we should have a more generic item/recipe for this that uses all fruit and alcohol and no heat to make. Closes https://github.com/CleverRaven/Cataclysm-DDA/issues/16659

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Preserving fruit with ethanol is a thing IRL.

**Comment by Podesta** [comment]
I've never made them ingame, but from what I could gather and after reading the short discussion on the issue you opened, it would seem that the better option is updating the recipes. The drinks do exist in real life. You could argue that they might not be really relevant ingame, but if you go down that route you'll have to remove a ton of other stuff. This kind of recipe creep is one of the 'traits' of CDDA, so I believe updating and fixing the recipes would be better.

**Comment by Cyrano7** [comment]
It's not that they aren't relevant in game its more that they are really broken and are kinda of half hatched ideas. I'm totally fine with tons of recipes and just for fun items. These two items just left me scratching my head always. After they are removed one could always re-implement them in another form which is kinda my plan anyways. To have a generic fruit preserved in alcohol item/recipe them spin off some related specific items like brandy cherries.

**Comment by Cyrano7** [comment]
@Coolthulhu I realize this which is why I said that in the description.

Would it be better if I included an alternative item/recipe in this PR?

**Comment by Cyrano7** [comment]
I'll reopen this when I have something to replace it with.

**Pull request closed without merging**
