### PR TITLE
Require and validate ENGINE flag

### LINKED ISSUE #19434: Door motor failing to start prevents entire vehicle from operating
> You take control of the vehicle.
> Looks like the door motor is out of none.
> The vehicle's engines failed to start.
> You let go of the controls.

### PR DESCRIPTION
**Pull request by mugling**
Fixes #19434

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Could you silence the warnings in mainline blazemod? It's still technically not obsoleted.

**Comment by mugling** [comment]
I'll take a look

**Comment by mugling** [comment]
Done

**Comment by Coolthulhu** [comment]
Forgot to push commit?

**Comment by mugling** [comment]
I would never do such a thing...

**Pull request merged**
