### PR TITLE
Refactor firing code [RDY]

### LINKED ISSUE #16761: Gun point-blank accuracy penalty checks for "shot" ammo_type instead of "SHOT" ammo_effects
Windows 10
Tiles
0.C-14084-gd5f8f59

The accuracy penalty for using bulky weapons at point-blank range (except when loaded with shot) is checking only for 12 gauge shotgun ammo,
```
if( gun.ammo_type() != "shot" )
```
instead of checking for the "SHOT" ammo effect, e.g.,
```
if( !weapon->ammo_effects().count( "SHOT" ) )
```

### LINKED ISSUE #16796: Reach attacks broken
Updated to the latest experimental and hitting f with reach weapons no longer gives the option to make ranged attacks.

### PR DESCRIPTION
**Pull request by mugling**
See also #16797 

EDIT:
- Fixes #16796
- Fixes #16761

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This really should be its own function

**Comment by mugling** [comment]
Indeed, but for the time being a less ugly hack to get things working again.

**Comment by Coolthulhu** [comment]
This really should be its own function

**Comment by mugling** [comment]
Done. A lot of the firing/targeting code could do with a refactor but this approach is cleaner than #16797 (absolutely no disrespect intended).

**Comment by mugling** [comment]
While were here might as well change the signature of `plfire` as it allows getting rid of the `BIO_WEAPON` hack

**Comment by mugling** [comment]
Fixes  #16796

**Comment by mugling** [comment]
Also fixes #16761

**Comment by narc0tiq** [comment]
I don't believe those will auto-close on merge from the comments, if that was your intention. Editing the OP should work, though.

**Comment by mugling** [comment]
@narc0tiq done

**Comment by mugling** [comment]
I have a number of open PR's: #16573 and #16799 are the most useful so marked these `priority`

**Comment by BevapDin** [comment]
BIO_WEAPON is still referred to in doc/DEVELOPER_FAQ.md

**Pull request merged**
