### PR TITLE
Make piano easy-deconstructable and thus possible to move as an item

### PR DESCRIPTION
**Pull request by KittyTac**
#### Summary
Balance "Pianos can be fast-deconstructed and thus be moved as an item"

#### Purpose of change
You can't really take a piano home if you find one, which I felt was weird since they, well, have a function if mostly a RP one.

#### Describe the solution
Make the piano easy-deconstructable, dropping it as an item. Then you can deconstruct the item to get what you would get if you deconstruct it before this PR. But you can also place it down.

#### Describe alternatives you've considered
Leaving as is.

#### Testing
image

image

image

#### Additional context
Prepare for more mild music-related PRs! Maybe I will make the huge speakers usable.

### CODE REVIEW

**Review by Karol1223 — CHANGES_REQUESTED** [review]
The piano is absolutely not an appliance. Don't put it in that file.

**Comment by KittyTac** [comment]
> The piano is absolutely not an appliance. Don't put it in that file.

idk why I didn't think of putting it in the decorative furniture file. but done. It's about as interactive as the big mirror so that tracks.

**Comment by The-Anjelo-Guy** [comment]
I really appreciate the content of this PR, these little details that no one cares about really transform the game. At least now I can carry a piano home! Good job. I hope this PR is approved and merged correctly.

**Comment by Montimorency** [comment]
Aren't pianos supposed to be moved with special techniques or equipment? This could in principle be addressed by adding an internal stage/variant to the primary Deconstruct construction, targeting pianos.

**Pull request merged**
