### PR TITLE
Magiclysm: professions can start with spells known

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Mods "Magiclysm: Professions can start with known spells"```
#### Purpose of change

i always thought it was a little janky that every starting wizard had to start with a spellbook with no spells known. this addresses that.
#### Describe the solution

add a new member to `professions` that's a map of spell_id and level, then have the avatar learn these spells at that level at the start of the game.
#### Describe alternatives you've considered

continue to use spellbooks

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
So are you going to remove Druid and Pyromaniac Kelvinist's starting books? Would-Be Wizard's description says they just got the book, so I'd expect that one to stay.

**Comment by KorGgenT** [comment]
i *may* remove the druid one, but the pyro is thematically appropriate.

**Comment by foulman** [comment]
It would be nice if we could have some.. say... thematically appropriate methods of them studying spells and learning spellcraft rather than it being an actual book every time. Perhaps the druid could meditate in the forest rather than read a book, or the biomancer... I dunno.. play doctor with a fresh corpse. Who knows... Hell I could make something up like those jedi holocron things for that matter.

**Comment by adamkad1** [comment]
but now you read to book to improve?

**Comment by KorGgenT** [comment]
casting spells gains you some exp. books just allow you to study the spell much quicker, and learn new spells.

**Comment by adamkad1** [comment]
i misspelled

**Pull request merged**
