### PR TITLE
Add evac center basecamp

### PR DESCRIPTION
**Pull request by krulunio**
#### Summary
Content "Add evac center basecamp"

#### Purpose of change
I'm working on more basecamp types, here's evac center basecamp (1 variant).

#### Describe the solution
Add really short upgrade paths for base and expansions. Hardest step is to get 30 human corpses, presumably by killing MOST of people in Evac Center (I didn't count representative, merc, arsonist, doctor and beggars, they technically don't count as part of Free Merchants; also, they can function as "spare parts", if some of other corpses get lost).

#### Describe alternatives you've considered
1. Making base on other Z-levels - there are currently no other Z-levels in Evac Center
2. Making base without commiting genocide - it would be interesting to somehow control Free Merchants, but it's impossible to implement properly with only basecamp mechanics
3. Using corpses as tools rather than components - 30 corpses is a lot of meat, losing it may discourage some characters from making camp in Evac Center; I checked JSON_INFO, it's possible to use corpses as tools, but from what I understand recipe would always require only 1 corpse, not more.
4. Making bases in fields around Evac Center - from lore point of view, Free Merchants wouldn't be happy about player making camps so close and around them; from technical point of view, all fields around Evac Center have, for some reason, uniqe OM ids, so I assume those will be used in future

#### Testing
I created and upgraded few camps, [here](https://github.com/CleverRaven/Cataclysm-DDA/files/6629499/fbmc_evac_center.zip) are screenshots.

#### Additional context
1. Pictures 1 and 2 show base (dining room), rest show workshop (dormitory with Zs).
2. Picture 2 show camp after giving corpses, water pump was created, because I assume there is access to water, but only for refugees, not outsiders. Since refugees are gone, you can take as much water as you want.
3. Workshop looks strange, because:
 - last time I checked, expansions can't rotate with OMT they are placed on. Evac Center's OMTs are rotatable, so I had to make workshop in such a way, to prevent furniture from being placed inside walls or outside of building.
 - I don't know how to remove furniture properly
4. Other expansions' upgrade paths have only initial survey, because of issues mentioned above and I don't think there's need for upgrades.

### CODE REVIEW

**Comment by Paperbell** [comment]
> hardest step is to get 30 human corpses
Hol up what

Is this supposed to simulate conquering the refugee center by killing some of its defenders?

**Comment by krulunio** [comment]
> Is this supposed to simulate conquering the refugee center by killing some of its defenders?

Not just defenders, but NEARLY everyone.
> I didn't count representative, merc, arsonist, doctor and beggars, they technically don't count as part of Free Merchants; also, they can function as "spare parts", if some of other corpses get lost

**Comment by I-am-Erk** [comment]
This is a lot more eDgInEsS than I want to have directly supported personally

**Comment by kevingranade** [comment]
"Making base without commiting genocide" and "Making bases in fields around Evac Center" would be fine.
This super edgy kill them all thing is not something I want to encourage.

**Pull request closed without merging**
