### PR TITLE
Update and simplify scenarios, attempt 2

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Change scenarios to be less restrictive and more generic"```
#### Purpose of change

This PR changes all the currently available scenarios to be more "generic", to let players mix and match professions, scenarios and starting locations however they want to make up their own stories and/or challenges (as long as it makes sense and is fair), and also makes them easier to maintain by reducing total number of separate scenarios. End of the world is a very chaotic event, so one indeed could expect anyone to end up near anywhere and in any circumstances as it happens, as long as it's not some highly guarded place like a lab, a prison, or a military bunker.

List of changes for scenarios:

Evacuee: renamed to Survivor and had the following scenarios integrated into it: Missed, Mall Cop, The Last Firefighter, Assault on Precinct Z, School, At the Zoo, Out Golfing, Apartment Rooftop. Description changed to reflect this.

Surrounded: this is a new scenario; this is an integration of all scenarios in which the player is surrounded by zombies at start. 

Refugee: renamed to Safe Place and had Out of Town integrated into it. Description changed to reflect this.

Missed: integrated into Survivor.

Infected: added more start locations and removed profession blacklist (in previous versions they had items which allowed to get rid of infection right at start and that's why they were blacklisted; now those items don't work that way, so it's fair)

Burning Building: added more locations.

Really Bad Day: added more start locations and allowed all professions (so that players could adjust how much of a challenge it actually is)

Medieval Peasant: added field as a possible start location.

Lab: split into two scenarios: Lab Patient (which can start with mutations as before) and Lab Staff (which don't have mutations). Also add missing Electroreceptors starting mutation (it is available as a starting trait in Experiment scenario, but not in Lab scenario)

Ambush: added extra start locations, allowed it to use all freely available professions (assuming someone who got kicked out of a survivor camp/evacuee center), and added some additional scenario-only professions that make sense. Also added a list of mutations as starting traits (same as for Lab; presumably enough time passed that someone could mutate accidentally or deliberately) 

The Next Summer: added extra start locations, allowed it to use all freely available professions (assuming someone who got kicked out of a survivor camp/evacuee center), and added some additional scenario-only professions that make sense. Also added a list of mutations as starting traits (same as for Lab; presumably enough time passed that someone could mutate accidentally or deliberately) 

Sheltered: no changes.

Abandoned: no changes; wasn't really sure what to do with it.

Prison Break: renamed to Prison and added more professions which could reasonably be assumed to be prison staff, also removed Psychopath as a forced trait because of this change. Description changed to reflect this.

Island Prison Break: added more professions which could reasonably be assumed to be prison staff. Description changed a bit to reflect this.

Experiment: added two more valid professions (which could be escaped experiments as well) and a field starting location.

Mall Cop: integrated into Survivor.

The Last Firefighter: integrated into Surrounded.

Assault on Precinct Z: integrated into Surrounded.

School: integrated into Survivor.

Wilderness: allowed it to use all freely available professions (assuming someone who decided that running into wilderness away from zombies was a good idea), added field as a valid starting location, Camping scenario was integrated into it.

Helicopter Crash: allowed it to use all freely available professions (perhaps they were transported on a military/police/civilian helicopter that was piloted by someone else and crashed, or even they stole a helicopter and unsuccessfully tried to operate it with no training)

Bottom of a Mine: allowed it to use all professions which could reasonably be present on a mining/science operation.

Fled the Riots: integrated into Surrounded.

Out of Town: integrated into Refugee.

High Tech, Low Life: allowed it to use all "outlaw" and "low-life" type professions, as well as those who could have been using their skills to install/trade bionics, changed description to reflect this.

At the Zoo: integrated into Survivor.

Out Golfing: integrated into Survivor.

Camping: integrated into Wilderness.

Apartment Rooftop: integrated into Surrounded.

Rancher: integrated into Safe Place.

The Mascot Rises: no changes (really wasn't sure about what to do with it)

Removed SCEN_ONLY flag from the following professions:

Naturalist: I guess it is possible that such a person decided that they could come back to formerly-populated areas because nearly everyone is dead now. Its high point cost keeps it fair still, so up to the player to decide if it makes sense for their character, as they could walk to cities right after game start anyway.

Miner: escaping from the mine with the tools and going somewhere else seems possible. Cost also raised to 2, as it actually has some pretty useful equipment.

Naked and Afraid: well, it could be possible to find a totally naked person anywhere, depending on what previously happened to the person in question.

Also removed a duplicate starting location that was simply going by different names.

Incidentally the changes included a few changes that were already present in More Classes and Scenarios mod, so I removed them from there as they are now part of mainline. Also removed Golfer profession from this mod, because profession with the same ID and name already existed in mainline and seemed to be more fleshed out.

#### Describe the solution

JSON editing mostly, also did a small C++ code addition to allow scenarios "professions" field to add to default professions rather than replacing them or blacklisting some.
#### Describe alternatives you've considered

None other than those listed here; if anything ends up not making sense, I'll revert it.
#### Additional context

This is a resurrection of #31213 which got killed by merge conflicts.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Ok, just for example would you explain how would I recreate an Attack on precinct Z scenario playing as a Cop in the proposed change?

**Comment by Rail-Runner** [comment]
> Ok, just for example would you explain how would I recreate an Attack on precinct Z scenario playing as a Cop in the proposed change?

Seleect "Surrounded" scenario, then select a "cop" starting profession and a "police station" starting location.

**Comment by Rivet-the-Zombie** [comment]
I can dig expanding options for starting, but this feels like we're losing a lot of narrative flavour this way.

**Comment by nexusmrsep** [comment]
I must agree with @Rivet-the-Zombie here. While achieving overall streamline clean approach this is a regression in terms of flavor.
The only idea I have in solving that would be - if possible - "post-scenarios". What I mean by that is, that if you choose "surrounded", "cop", "police station" the game would generate a "Attack on precinct Z" flavor scenario out of that. In other words a way for the game to name the specific scenarios  after you choose the initial starting circumstances. 

This backfire

**Comment by nexusmrsep** [comment]
Sorry for close/reopen. Misclick.

**Comment by Amoebka** [comment]
I really can't understand why losing the "attack on precintc Z" descriptor is considered loss of flavour when absolutely everything about the scenario stays the same. If anything, I don't want to scroll through dozens of scenarios that each have <5 professions available with the only difference being names and starting locations.

I also think that giving players MORE freedom to roleplay is always better than arbitrarily restricting them. At the very least, make a "freeform" starting scenario that allows all locations and all professions.

**Comment by nexusmrsep** [comment]
@Amoebka
Don't take me wrong. I don't argue with the change, and the freedom and streamline it brings. I see the added value in that.

I - as a player - just want some kind of a  flavour to follow and I want it in game, not only in my imagination. It's like choosing a hairstyle; no mechanic behind it, pure flavor, but +100 to roleplay. I want to play someone with a story, not a nameless character who happened to be somewhere when it started. I want profession and place and scenario to build a story, and not be unrealted choices. I want to identify myself with he character I chose to play. To do it better I want to be able to choose my character's story before Cataclysm. I want basic outline of that story to be in the game, if I so choose, not just in my imagination. Furthermore, in the future development I'd like to be able to tell that story to NPCs, just like they tell my character their stories. For pure RPG reasons. For pure immersion.

Imagine JSONized stories  / scenarios:
Perquisites: "Lawyer" + "police station"
Optional choice of a story: "You were called because your client has bitten a cop. Now they both are under and want to bite you, and this case suddenly had became hard to defend."

I'm not saying this is in scope of this PR. But the consequence of this PR is that it slightly blurrs the *feel* of having a story set. And you are left with your imagination. Perhaps it's a personal thing, and you may not agree, but that's how I see it. But that doesn't mean I oppose the change.

**Comment by Fris0uman** [comment]
What about adding a free form option where you either get what is in this PR or just the ability to pick any start with any profession?

**Comment by Inglonias** [comment]
> I - as a player - just want some kind of a flavour to follow and I want it in game, not only in my imagination. It's like choosing a hairstyle; no mechanic behind it, pure flavor, but +100 to roleplay. I want to play someone with a story, not a nameless character who happened to be somewhere when it started. I want profession and place and scenario to build a story, and not be unrealted choices.

> ... Perhaps it's a personal thing, and you may not agree, but that's how I see it. But that doesn't mean I oppose the change.

I get what you're saying, and I agree both that it's a valid point and still not enough to justify opposing something like this if it helps the game. I don't know whether the proposed change makes the game better or not.

There's a whole bunch of stuff in the game that serves no gameplay purpose, but helps with roleplaying. Do we need to have different flavors of soda from vending machines? Do we need to have different genres of fictional books? Do we need to let players choose their gender? No to all three if you're talking about pure gameplay. 

Ultimately, this decision comes down to what we (or I guess Kevin) feels is more important. Do we make the scenario selection a little more flexible while still shortening the list, or do we prioritize the flavor that we would otherwise lose by standardizing things? I don't know the answer to that.

**Comment by kevingranade** [comment]
> At the very least, make a "freeform" starting scenario that allows all locations and all professions.

Adding such a scenario to the main game as a regular option *endorses* the concept that it's a reasonable thing to do to spawn an arbitrary profession at an arbitrary location with arbitrary flags. It's simply not, the only reason many of these options are remotely reasonable to have is to bake these limitations into the starting scenarios and their associated professions.

*Maybe* having a freeform-only scenario that throws all the professions and all the start locations into one huge basket is a reasonable thing to add, along with disclaimers that you're on your own as far as resulting bugs or unfairness.

I went in and reverted a bunch of the worst offenders for vastly increasing what professions are in what scenario, but now that I'm looking more closely, there's another problem. Many of these locations are not at all fungible, spawning in a shelter is not at all the same thing as spawning in an apartment complex or a hospital or a church or a *mall*.  There's a reason these were added as separate scenarios in the first place, and while the site-specific scenarios might have gotten a bit out of control, adding 36 wildly different location options to the basic sheltered scenario goes very much too far in the other direction.

If we're going to streamline the number of scenarios, they need to be grouped into sensible blocks, for exampled the "sheltered" scenario should stay as it is and spawn in a relatively isolated location outside of a town, then spawn locations inside towns are mostly fungible, except the high-population areas like apartments and malls and hospitals.

**Comment by Rail-Runner** [comment]
> Many of these locations are not at all fungible, spawning in a shelter is not at all the same thing as spawning in an apartment complex or a hospital or a church or a _mall_. There's a reason these were added as separate scenarios in the first place, and while the site-specific scenarios might have gotten a bit out of control, adding 36 wildly different location options to the basic sheltered scenario goes very much too far in the other direction.
> 
> If we're going to streamline the number of scenarios, they need to be grouped into sensible blocks, for exampled the "sheltered" scenario should stay as it is and spawn in a relatively isolated location outside of a town, then spawn locations inside towns are mostly fungible, except the high-population areas like apartments and malls and hospitals.

Well, with this approach, if one would want to have the possibility of starting in any burning building (as current scenario allows), they'd need to have three separate scenarios, one of which is a burning shelter-type building, another is a burning town building, third is a burning large building like mall, hospital or whatever. Same set of three for infected starts, for "surrounded by zombies" starts, etc.; they'd be harder to maintain and eventually will go out of sync with each other anyway. This is pretty much just a way to group all similar starting conditions which could be used together in any combination to avoid having too much repetition.

**Comment by paulenka-aleh** [comment]
> What about adding a free form option where you either get what is in this PR or just the ability to pick any start with any profession?

I badly wanted this thing even in more custmizable level, e.g. choose addictions, effects on your character, set the building on fire, decide if you're surrounded or not. Achievable with json editing for now. If you want to roleplay balance is a secondary thing so I didn't care much about points.

It will be awesome to have such scenario creator/editor in game itself, just the way worlds or characters can be designed now. It would definetly address customizability issue and would allow to keep stylish things like "Attack on precinct Z" at the same time as pre-configured existing ones.

I fully understand that this is much bigger project and not something to do in this PR, just sharing thoughs thst came to me a while back

**Comment by kevingranade** [comment]
> which could be used together in any combination with sensible locations and professions to avoid having too much repetition.

This is the problem, we don't *want* every combination of scenario and profession and location to be selectable.  If someone wants to play with a particular combination, it's *really easy* to add, there's no need for them to all be pre-populated with every possibility.

> If some specific combination of a location and a burning building, having an infection, being surrounded or "having a really bad day" is unreasonable,

You're starting from the idea that every combination is valid and only certain combinations are problematic. This is the opposite of how scenarios and professions work, only a small number of combinations are necessary and reasonable to maintain.

**Comment by Rail-Runner** [comment]
Redone it with that assumption. If anything is still unreasonable, I'll remove it.

**Comment by Corvus-Dismas** [comment]
Doesn't seem to work correctly. 

"Evacuee: renamed to Survivor and had the following scenarios integrated into it: Missed, Mall Cop, The Last Firefighter, Assault on Precinct Z, School, At the Zoo, Out Golfing, Apartment Rooftop. Description changed to reflect this." 

Is still Evacuee, pretty much unchanged.

"Missed: integrated into Survivor"
Still available. Not working since there is no "Survivor" scenario.

"Mall Cop: integrated into Survivor."
Not available. Not working since there is no "Survivor" scenario.

"School: integrated into Survivor."
Not available. Not working since there is no "Survivor" scenario.

"Wilderness: allowed it to use all freely available professions (assuming someone who decided that running into wilderness away from zombies was a good idea), added field as a valid starting location, Camping scenario was integrated into it."

Works as intended. More Survival Tools breaks this, only Prehistoric Hunter and Wanderer are available, just for info.

Fema-Deathcamp disappeared completly.

**Comment by ZhilkinSerg** [comment]
See comments - it was redone and description doesn't reflect contents anymore.

**Comment by Corvus-Dismas** [comment]
@ZhilkinSerg 

The redone state doesn't really make sense to me. For example evacuee has 3 identical "Shelter" location choices. Same with large building, it has 9 identical hospital and 4 apartment rooftop starting locations. 

Bunch of scenarios have multiple identical grocery store, campground, campsite etc.

Challenge - Fema Death Camp is completly missing, not sure if that was intended.

**Comment by ZhilkinSerg** [comment]
> The redone state doesn't really make sense to me. For example evacuee has 3 identical "Shelter" location choices. Same with large building, it has 9 identical hospital and 4 apartment rooftop starting locations.

It has nothing to do with current changes. Each starting location means certain overmap terrain.

**Comment by Rail-Runner** [comment]
> The redone state doesn't really make sense to me. For example evacuee has 3 identical "Shelter" location choices. Same with large building, it has 9 identical hospital and 4 apartment rooftop starting locations.
> Bunch of scenarios have multiple identical grocery store, campground, campsite etc.

Those are actually different overmap tiles, as far as I know. So you'd be starting in a different place in hospital (or in a different grocery store) if you pick a different start location with the same name. I don't have an idea on how to differentiate between them, though.

> Challenge - Fema Death Camp is completly missing, not sure if that was intended.

Looking at the original file, seems like it wasn't present in the first place. Maybe it's mod content?

**Comment by Corvus-Dismas** [comment]
> It has nothing to do with current changes. Each starting location means certain overmap terrain.

>Those are actually different overmap tiles, as far as I know. So you'd be starting in a different place in hospital (or in a different grocery store) if you pick a different start location with the same name. I don't have an idea on how to differentiate between them, though.

Alright got it.

>Looking at the original file, seems like it wasn't present in the first place. Maybe it's mod content?

You are right, sry for that.

**Comment by Rail-Runner** [comment]
> Does it make a difference having a choice between multiple idential single overmap starting tiles?

Yes, kind of. The building layouts of two grocery shops are different (though both still served the same purpose before Cataclysm, apparently).

**Comment by paulenka-aleh** [comment]
This does look weird. I'd say either give them distinct names or pick random in case names are similar at game start. I'm in favor of second.

It looks to be aseparate issue though introduced no by this change specifically...

**Comment by Corvus-Dismas** [comment]
>It looks to be aseparate issue though introduced no by this change specifically...

Yeah Im sorry if this issue isn't supposed to be mentioned here. Just created the account today after I noticed that and thought it related to this change.

**Pull request merged**
