### PR TITLE
[WIP] Add some fun to prozac

### PR DESCRIPTION
**Pull request by Cyrano7**
It is a antidepressant after all. Made it 10 fun like the adderall. xanax is 20.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
That's not how Prozac works at all.
It doesn't make you feel good, it makes you not feel very much of anything. There's a big difference between the two.

**Comment by hitbutton** [comment]
> It doesn't make you feel good, it makes you not feel very much of anything.

I don't think that's representative of Prozac's effects at all.

Specifically it inhibits serotonin reabsorption - serotonin basically being a neurotransmitter that makes you feel happy. So prozac prolongs the effect of serotonin that is released naturally (as opposed to drugs like MDMA which not only inhibit reabsorption of neurotransmitters, but also prompt their release).

It would make most sense for Prozac to prolong the duration of any morale increasing effects, but failing the implementation of that as a mechanic, having it give a small positivie morale modifier sounds fine.

**Comment by Rivet-the-Zombie** [comment]
But it doesn't make you any happier or anything of the sort. It puts you in a state where you're neither sad nor happy, like your emotions are all muted and bland.

**Comment by hitbutton** [comment]
That's still a mischaracterisation of its effects. Prozac can, and does, make many people feel happier.

Indifference/emotional blunting of the type you're describing is a side-effect reported by some people who take SSRI antidepressants like prozac (and if they are experiencing it, then they should definitely discuss it with the person who prescribed it to them). It isn't the intended effect, and it isn't reported by all users.

**Comment by shokolatOtobus** [comment]
As far as I know, emotional blunting is present in practically any SSRI use to an extent, but overall proper administration of the right drug should positively influence mood to outweigh that. Ideally in CDDA this would mean a dulling of all morale modifiers, but significantly less so than positive ones. Sadly as a scrub I am unable to find how this is actually implemented in the code, but it seems decent enough as a player in current implementation.

If I do know one thing for sure though, SSRIs (especially Prozac) do not cause any sort of immediate morale boost (or in real life, mental effects at all) - so this boost should not be added here.

**Comment by Cyrano7** [comment]
Its really not clear in game but after looking more in depth at the code now I have a clearer view of whats happening when you take prozac. In player.cpp it has the lines...
int player::morale_level() const
{
    // Add up all of the morale bonuses (and penalties).
    int ret = 0;
    for (auto &i : morale) {
        ret += net_morale(i);
    }
    // Prozac reduces negative morale by 75%.
    if (has_effect( effect_took_prozac ) && ret < 0) {
        ret = int(ret / 4);
    }
    return ret;
}
That's the biggest part. But It has a more specific effect on the hoarder and masochist traits as well. 

I'm not sure if it recalculates the players morale after taking it though or if its just for incoming morale changes. Might be good to have it effect the bad temper trait more specifically also.

**Comment by illi-kun** [comment]
FYI: similar topic was discussed in #11495.

**Comment by kevingranade** [comment]
Straightforward consensus, no fun for prozac.

**Pull request closed without merging**
