### PR TITLE
Remove incomplete fetch book mission

### LINKED ISSUE #17630: Friendly NPC quest "Find a Book" is broken
Accepted quest from friendly NPC, but all messages was `"Someone forgot to code message id is 78"`.
But in quest window I see active quest "Find a Book".
Looks like `mission_start::place_book` method is empty. So probably quest implementation is incomplete, and somehow merged into master.

### PR DESCRIPTION
**Pull request by kolsurma**
Closes #17630.

Doesn't implement the mission, as the original author's nowhere to be found, and I'm not creative enough to do it.

I do wish there were a flag you could set in the JSON for things which the game should ignore, a "disable" flag if you will.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Errors on load

**Comment by kolsurma** [comment]
> Errors on load

Confirmed, error on load of existing character. 
Continuing, saving and loading same character had no errors.
New world, new character had no errors.

So the issue is the mission is assigned to a npc somewhere or the PC and then saved? Is there a system in place to mitigate this?

**Comment by Coolthulhu** [comment]
It would be easier to just disable the mission rather than removing it outright.
Setting its origin to "ORIGIN_NULL" should prevent it from ever being handed out.

Saves with this mission already existing will keep the unfixable entries, but there isn't much we can do about it. The mission system is convoluted and it's hard to fix anything in it without unwrapping it to get rid of the hacks.

**Comment by kolsurma** [comment]
>Setting its origin to "ORIGIN_NULL" should prevent it from ever being handed out.

Oh neat I'll do that right quick then.

**Pull request merged**
