### PR TITLE
Change leather spear strap recipe to require leather

### LINKED ISSUE #50822: Spear straps need leather to repair even when not made of leather
### Describe the bug

I have a spear strap that I made without using leather, but both the description and the materials tag suggest that it is made of leather. Furthermore, it requires leather to repair.

### Steps To Reproduce

- Make a spear strap without using leather
- Look at the description of the item
- Attempt to repair it

### Expected behavior

Ideally, the spear strap would count as being made out of cotton whenever it is made using only cotton. Alternately, it could be impossible to craft without leather.

### Screenshots

spearStrap

### Versions and configuration

- OS: Windows x64
- Game Version: 9a10b0c
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KanterDev**
#### Summary
Bugfixes "Changes Spear Straps to be crafted primarily out of leather, rather than cotton. Making them impossible to craft without leather. As mentioned in #50822"

#### Purpose of change
Spear straps are described as "A leather strap tied around the torso..." as well as being repaired with leather. But can be crafted without leather currently.

#### Describe the solution
Change "spearsling" recipe to require leather patches rather than cotton sheets.

#### Describe alternatives you've considered
Changing the spear strap to be cotton, adding an alternative item or changing the items description and material.

#### Testing
Crafted item in game.

#### Additional context
Before, Crafting with no leather: 
leather strap no leather
After, Requiring leather
image
Fix #50822

### CODE REVIEW

**Comment by casswedson** [comment]
You want to add "Fix #50822" somewhere, it will automatically close the issue if your PR gets merged.

**Comment by kevingranade** [comment]
Why the huge bump in crafting time? Isn't this just splicing a few strips of leather together and attaching clasps?

**Comment by KanterDev** [comment]
> Why the huge bump in crafting time? Isn't this just splicing a few strips of leather together and attaching clasps?

I was actually wondering that myself!
This is to bring it's crafting time in line with other leather items of similar materials, specifically

 "result": "sholster",
   "difficulty": 3,
   "time": "4 h",
    "using": [ [ "tailoring_leather_small", 3 ] ],
    
   "result": "sheath",
    "difficulty": 3,
    "time": "4 h",
    "using": [ [ "tailoring_leather_small", 3 ] ],
    
     "result": "quiver",
    "difficulty": 2,
    "time": "6 h",
    "using": [ [ "tailoring_leather_small", 3 ] ],
    
Overall leather items seem to be very slow to craft, with only a few items taking less than 4 hours. I'm not really sure what the reasoning is, but I didn't want to create an inconsistency. Personally I think they all take too long, but I also know nothing about leather crafting. 

The javelin bag is an interesting comparison, because it only takes 80m, making it one of the fastest, but it seems out of place requiring 7 tailoring leather.

**Comment by Zireael07** [comment]
Kevin has a point though, for a quiver/holster/bag you need to do much more work than just for making a single strap.

**Comment by kevingranade** [comment]
We can certainly revisit the holsters, but I would assert a holster with a belt is at least twice as much work as a strap, and more generally, please don't adjust stats with the only rationale of "make it the same as something else that's similar".

**Comment by KanterDev** [comment]
I appreciate the feedback from both of you and I was definitely looking at it the wrong way. Unfortunately github isn't allowing me to push commits to this and I haven't been able to resolve that.

**Pull request closed without merging**
