### PR TITLE
Add Sounds to Spell casting Draft

### PR DESCRIPTION
**Pull request by maelynmulder**
#### Summary

Features "When the player casts a spell, the player hears a corresponding sound for that spell"
#### Purpose of change

I like to use sound packs when playing Cataclysm and was surprised to hear nothing when I cast a spell, especially those with explosions like mana bolt. I went ahead and tried to add a sound to spells by gathering a few sound effects and making a JSON to attach them to the spells. None of the spell's JSONs have a no sound_id or sound_variant key to refer to; even if it was added to the spell's JSON, it didn't work. I then went into source code to figure out why this was happening to learn it was simply not implemented.
#### Describe the solution

Added get_sound_id() and get_sound_variant() to the Spell class, and used them in the Spell::make_sound() method with sfx::play_sound_variant()
Describe alternatives you've considered

Accessing the sound_id and sound_variant directly via type->field.
#### Testing

I asked in the discord about the solutions to see what was the preferred way of writing a feature like this. Before each commit, I compiled and then ran the game to perform a test like in the video below to see if everything was working as intended.
#### Additional context

https://youtu.be/dtg-JCmk6BE

### CODE REVIEW

**Comment by MichaelMulder** [comment]
TODO add "sound id" and "variant sound" to all spells

**Comment by actual-nh** [comment]
An appropriate Summary, to make the PR validator happy, would be `Features "When casting a spell, the player should hear a corresponding sound effect for that sound"`. Regarding the astyle check... given that the differences appear to be invisible, either you need to run astyle locally or you need to check for things like spaces at the ends of lines.

**Comment by actual-nh** [comment]
Oh. And currently recommended is having this be "Draft" status instead of "[WIP]" in the title. You can put "[CR]" to indicate that you'd like reviews despite draft/WIP.

**Comment by actual-nh** [comment]
Sorry - for the PR validator to work, the `#### Summary` section header has to be intact. (The PR summary is what goes in the changelog, BTW.)

**Pull request closed without merging**
