### PR TITLE
Updated recipes of cooked fruit and fruit jam

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Removed recipes of cooked berries and berries jam as they are already in recipes of cooked fruit and fruit jam.

### CODE REVIEW

**Comment by KA101** [comment]
Gonna ask that you let folks keep these as ingredients, so people who happened to make berry jams with the intent to use them as ingredients aren't screwed.

Basically, stop the creation of new ones, but don't prevent old from getting used.  Once 0.D (or 1.0) hits, we can remove the ingredient usage and items.

**Comment by KA101** [comment]
Updating as asked, doublepost just to make sure Git pushes the notification: half of this change is good and should be incorporated now (removing the recipes to make the specific jams) and the other half should be delayed (removing the ability to use currently-existing specific jams/cooked fruit in recipes, as ingredients).

That way, folks who have these jams that we're removing from the game aren't penalized for making the specific jams rather than the generic fruit jam.  I'm asking that you reinstate the recipe-ingredient listings for the specific jams until the next stable lands, so we have plenty of time available for players to use up their existing stocks.

**Comment by Night-Pryanik** [comment]
Done, I think.

**Comment by KA101** [comment]
Watch out for those separator checks.  I can fix this in the merge, but let's not make a habit of it.  ;-)

**Comment by Night-Pryanik** [comment]
Oh. If I even knew what separator check is. Sorry for my ignorance.

**Comment by KA101** [comment]
It happens.  Best to actually run your game with the changes in, see if it yells at you.  (And if it does, fix it!  ;-) )

**Pull request merged**
