### PR TITLE
Fix consumption of medications

### LINKED ISSUE #20006: Bandages aren't consumed when used
Using bandages to heal or stop bleeding doesn't actually use up a bandage. First aid kits aren't affected. Probably came from https://github.com/CleverRaven/Cataclysm-DDA/pull/18681

### PR DESCRIPTION
**Pull request by codemime**
Fixes #20006.

### CODE REVIEW

**Comment by codemime** [comment]
This is a quick fix. I'm gonna improve the consumption code further.

**Comment by keyspace** [comment]
* Fixes bandage not consumed.
* Allows activating "cigarette" (and adds effects properly).
* Doesn't allow activating "pack with cigarettes".

Attaching savefile used for testing. It's dirtyish.

[test-vanilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/706088/test-vanilla.zip)

**Comment by keyspace** [comment]
Note: even with fix applied, "cigarette" has "actvivate" and "eat" highlighted in inventory-item submenu, whereas "pack of cigarette" doesn't. Eating/activating the latter still works.

**Comment by codemime** [comment]
Fixed.

**Comment by codemime** [comment]
@keyspace Thanks for testing this.

**Comment by keyspace** [comment]
Heh, thanks for fixing this. :)

Here's a survivor's note:

> I swear, I've been sucking on the same cig for hours now, and IT DOESN'T HELP. All those children at the schoolyard... What have I done?..

**Pull request merged**
