### PR TITLE
[RDY][CR] Update bitrotted gain doubling for working off skill rust

### PR DESCRIPTION
**Pull request by i2amroy**
Previously when a player was working off skill rust they gained twice as many points towards learning the skill. Whenever the skill system was updated so that exercise never went negative this bitrotted out. This updates it to the new system by way of tracking the highest level the player has ever achieved in a given skill; if they have rusted to a lower one then all gains in that skill will be doubled (note, overflow is not an issue because on leveling all additional xp is already thrown away, players will always start a level with exactly 0 experience on the new level).

Comments requested because I haven't played enough recently to know if re-enabling this bitrotted feature would break the current balance or not. If it would this can easily be reduced down to just a small cleanup PR.

(Also replaced an old manual implementation in the focus code with the newer "roll_remainder" function call.)

### CODE REVIEW

**Comment by i2amroy** [comment]
Not sure why the gorgon build failed, checking the console there gives this message as the reason for failure, ```ERROR: Error fetching remote repo 'origin'```, which I don't think is anything on my end.

**Comment by BorkBorkGoesTheCode** [comment]
The buildbot has been experiencing some issues since you left.

**Comment by BorkBorkGoesTheCode** [comment]
Jenkins, rebuild. Please.

**Comment by i2amroy** [comment]
Ah, so those are the magic words I need to trigger a rebuild :P

**Comment by narc0tiq** [comment]
The regex is `.*jenkins,?\W+rebuild.*`, case-insensitive)

**Pull request merged**
