### PR TITLE
Fix check in player::can_hear

### PR DESCRIPTION
**Pull request by BevapDin**
The character can hear the sound if its volume is bigger than the distance, not the other way round. I found this while walking with an active geiger counter through an radioactive crater. It did not make a sound, but it checked directly ("scan the ground"), it would show some radiation.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Intensity error for mp3 players as well, this fix it?

**Comment by BevapDin** [comment]
I'm not aware of that bug, but I fixed another one:

`iuse::play_music` should give morale if one can hear the sound, not when one can't hear it. Compare with the same check in `iuse::einktabletpc` (which is already correct).

**Comment by DavidKeaton** [comment]
I just saw it on debug output yesterday. Made a note of it, but haven't looked into it. Figured since you were working with sound, if this fixed it. :-)

**Comment by BevapDin** [comment]
There is another bug in `get_random_music_description` (or actually, the whole function is one bug, but I'm not going to fix this as I don't know what's the intended behavior):
It's called before the `can_hear` check, but it increases the morale (when it chooses "dramatic classical music." and the int stat is high enough). But even that can be overridden later by "polka", which results in morale increase even though it didn't play classical music.

**Comment by DavidKeaton** [comment]
Oh that sounds like fun. :^) I am still working on an AIM PR, but I can peek if you don't get around to it. :-)

**Comment by KA101** [comment]
Uh, I''m thinking that something got horribly lost in an iuse refactor somewhere.

With this PR in:
1) I don't need the mp3 player on my person to listen to music, earbuds notwithstanding: simply in-bubble at the check will do, apparently.  (Turned it on, waited 5 minutes, ditched it on the evac shelter counter, hiked off: music morale holds steady and then zeroes when you get about three or four OMT away; it comes back much higher than one'd expect: 0->19 Music morale)
2) Still not getting sounds described: my morale just goes up (possibly that needs moved  to the mp3_on?)

As such, I'm afraid I can't justify merging this.  Seems to cause or at least miss as many problems as it solves.  :-(  Sorry, BevapDin.

**Comment by BevapDin** [comment]
About 1: that's a bug in `iuse::mp3_on`, it would use the player position instead of the item position. It is fixed.

This also fixes the faulty behavior of `get_random_music_description` as described above.

About 2: sounds with volume where ignored completely, but they are already used by at least several iuse functions to simulate ticking bombs.

**Comment by DavidKeaton** [comment]
That was the bug I mentioned right?

**Comment by BevapDin** [comment]
> That was the bug I mentioned right?

I assume so, but you better check again once it has been merged, just to be sure.

**Comment by DavidKeaton** [comment]
Con do.

**Pull request merged**
