### PR TITLE
Deconstruction plus

### PR DESCRIPTION
**Pull request by Shangxin-07**
#### Summary
Content "Adds various terrain deconstruction recipes and a masonry saw"

#### Purpose of change
To alleviate the need to jump into debug mode (or break things) to make modifications to already existing houses.  

#### Describe the solution
You can now remove: empty window frames, floors, linoleum tiles, concrete floors, walls, wooden walls, brick walls, concrete walls, roads / pavement / zebra crossings, metal doors, rebar cages, concrete columns, half complete walls, glass walls and glass doors. Recipes and tools required are balanced for mid to late game. These may require some tweaking to get them inline with what is expected though.

#### Describe alternatives you've considered
Debug mode. Breaking all the things. Both work, both are nasty alternatives. Breaking all the things leads to ceiling collapses, which should be relatively easy to avoid when doing the work in a controlled fashion. Moving into Debug mode to do something is always immersion breaking, at least from my point of view, and so I don't really like doing it, and once you do it once, it's always "an option" from there forward. 

#### Testing
Spun up a new world, checked to see if the options were in the build menu, deconstructed things. Built the Masonry saw, turned it on and then off.

#### Additional context
The masonry saw probably needs a little more work, both from a recipe and a use perspective. It's almost literally a chainsaw with the ability to cut concrete.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Really cool! I actually  wanted this  for Aftershock, so many thanks!

**Comment by Shangxin-07** [comment]
I'll lint those files and resubmit.

**Comment by Broken27** [comment]
Make fireplaces deconstructable while you are at this, it has always bugged me that you can't properly deconstruct them when you need rocks. (You have to destroy them instead for 15-30 rocks instead of 40).

**Comment by Shangxin-07** [comment]
- Rewrote the deconstructions with lists of tools and byproducts, where appropriate.
- Explicitly stated which tool was being used and made sure that it was using charges / fuel.
- Added the oxy torch + welding goggles into the removal of metal doors / rebar, although the oxy torch was added as an alternate to the angle grinder, because that was intended as the metal cutting tool.
- Changed the byproducts that come from wall removal as it was dropping too much stuff.
- Tweaked the recipes for removal of metal so that it uses a hacksaw.
- Looked at the times that were low, but still think that they're fair, given that the intent is to use an angle grinder to do most of the cutting, rather than by hand.
- Will probably add fireplace deconstruction soon. :D

**Comment by Shangxin-07** [comment]
I am unsure how to fix this error, am I looking at the correct thing?

([slow] ~crafting_skill_gain)=> ../tests/overmap_test.cpp:51: FAILED:
([slow] ~crafting_skill_gain)=>   CHECK( special->occurrences.min <= special_placement.instances_placed )
([slow] ~crafting_skill_gain)=> with expansion:
Error: ([slow] ~crafting_skill_gain)=>   100 <= 99

**Comment by Shangxin-07** [comment]
I'm assuming, once again, that the reason that fireplaces don't deconstruct is because the default deconstruction tools - hammer and screwdriver, are considered "too basic" to deconstruct a fireplace. I've added a crowbar and chisel to hopefully sort this out.

**Comment by Shangxin-07** [comment]
Suggestion was made that the base builder test was using my deconstruction recipe to create t_pit (by first building concrete walls and then deconstructing them). Not sure if this is the case, but definitely seems possible. 

So I've removed t_pit as a target and replaced it with t_dirt, while also adding DIG 3 to the list of required qualities. Also removed SAW_MASONRY as a quality (nothing was using it), and added a recipe for angle grinders (which I use in nearly all deconstruction recipes)

**Pull request merged**
