### PR TITLE
Refactor monsters shift-v menu

### LINKED ISSUE #24436: List of monsters around player displays incorrectly for monsters with long names
Game version: 0.C-29459-g56a2166

### Expected behavior

In the list of monsters, monster name and monster health never overlap each other.

### Steps to reproduce the behavior

Open the list of monsters around player while a near-death gigantic naked mole-rat is visible.

### LINKED ISSUE #31618: "Look Around" menu z-level direction abbreviations wrapping
# Describe the bug

The UI layout was designed with directions labels of the `N` and `SE` variety, but with z-levels and 3d fov enabled you can see monsters on other zlevels with get labeled as `DN_NE` for "Down Northeast` for example. The ui code does not expect these longer labels which causes wrapping

# Steps To Reproduce

1. Enable z-levels and 3d fov
2. Go up on a roof
3. Press `V` and view monsters

# Expected behavior

There's a couple of possible solutions here.  There seems to be space in the current UI layot for 3 characters, so one option is using labels such as `DNE` or `USW` that fit in the 3 characters.  I personally think this is a little intuitive however.

I'd prefer something like `NE+1`, `S-1`, and `SW+0` as that is in my opinion more intuitive and also 1 character shorter than the current `DN_NE`.  It does however require more space in the UI.

# Screenshots

Screen Shot 2019-06-19 at 12 10 21 PM

### PR DESCRIPTION
**Pull request by 8street**
#### Summary
 ```SUMMARY: Bugfixes "Refactor monsters shift-v menu"```

#### Purpose of change
The monsters shift-v menu does not look very good.

#### Describe the solution
Changes in monsters shift-v menu:
- Added missing border
- Deleted mess border code
- Added missing scrollbar
- Fixed wrong height of info and list windows
- Reposition for "Press x to look around" and "Press f to shoot" (looks better)
- Reposition for "You don't see any monsters around you!" (with a minimal screen size of the game this text was missing)
- Added color of a zombie's name
- Fixes #31618
- Fixes #24436

#### Describe alternatives you've considered
Do nothing.

#### Testing
Before
fix2

After
fix3
fix4

### CODE REVIEW

**Comment by JonnieCache** [comment]
Would it be possible to color code the monster names as well? I often find myself wishing for that.

**Comment by 8street** [comment]
> Would it be possible to color code the monster names as well? 

How would you like to coloring the names of the monsters? In relation to the player, for example, hostile monsters are red. Or do you just want to highlight the name with a different color? Please provide an example.

Note that all changes a colors of monsters here will remain in the monster menu. For global coloring of monster names, please create a theme in the Issues. Maybe someone will make your request.

**Comment by JonnieCache** [comment]
> 
> 
> > Would it be possible to color code the monster names as well?
> 
> How would you like to coloring the names of the monsters? In relation to the player, for example, hostile monsters are red? Or do you just want to highlight the name with a different color? Please provide an example.

In the "compass" view, monster names are shown from gray for the lowest level monsters, through white for slightly more dangerous ones, then pink, all the way through to bright red which is the highest Ive personally seen.

I often see a dangerous monster by spotting the color, then hit shift+V, wanting to know its location, but when looking at the list I realise I didn't actually notice the name of the monster, just the color, so I have to leave the shift+V menu, match the color with a name from the compass, then reopen the shift+V menu to find the right zombie.

**Comment by 8street** [comment]
Well, monsters menu look better.
coloring

Also I'd added coloring of the monster's name in the monster info window.

**Comment by snipercup** [comment]
Should incorporate 3d field of vision?
image

**Comment by 8street** [comment]
> Should incorporate 3d field of vision?

Thx for testing. Fixed.
fix1

**Comment by Night-Pryanik** [comment]
With your latest improvements on directions labels the PR should also close #31618.

**Comment by 8street** [comment]
I discovered another bug #24436. I will fix it a little later.

**Comment by Night-Pryanik** [comment]
Could you please provide a screenshot with more terminal height? Say, 50-60?
Also, with a gigantic naked mole-rat?

**Comment by 8street** [comment]
> Could you please provide a screenshot with more terminal height? Say, 50-60?

screen
The resolution of the my screen is 1080p.

**Comment by 8street** [comment]
Maybe I will need to make a new PR, where the all blue color be brighter. This is not the first time that blue is not visible.

**Comment by Night-Pryanik** [comment]
> Maybe I will need to make a new PR, where the all blue color be brighter. This is not the first time that blue is not clear visible.

You mean blue-on-black names like Z-9?

**Comment by 8street** [comment]
> You mean blue-on-black names like Z-9?

Yes. You have no problems reading such blue text?

**Comment by Night-Pryanik** [comment]
I do have problems with that combination of colors, and I'll appreciate if you change them to, say, light blue on black. But that would be better implemented in separate PR.

**Pull request merged**
