### PR TITLE
Remove Acid Bombs

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove acid bombs"

#### Purpose of change

Acid bombs don't make much sense. None of the acids used in the recipe are nearly that dangerous as to melt flesh on contact, instantly. It sure as hell ain't HF, and you can't store HF in glass.

#### Describe the solution

Removes it.

#### Describe alternatives you've considered

Not removing it.

#### Testing
image
image

#### Additional context
Had to be migrated to sling ready molotovs to avoid an error.

### CODE REVIEW

**Review by Maleclypse — DISMISSED** [review]
I'm marking this request changes as I'm going to modify this PR or put up a competing one doing the same thing but additionally creating an acidbomb that only uses the blob mutated acid blood from evolved zombies and mutants.

**Comment by Holli-Git** [comment]
> I'm marking this request changes as I'm going to modify this PR or put up a competing one doing the same thing but additionally creating an acidbomb that only uses the blob mutated acid blood from evolved zombies and mutants.

I'm planning on changing acid zombies and such to have something like acid ducts/glands that spray some boiling acid, instead of just having this weird video-gamey acid stuff. But, I'm unsure how long that'll take, so feel free to continue with what you are planning

**Comment by Maddremor** [comment]
I'd like to not that the "acid" part of "acid bomb" isn't the only issue with the item, but the "bomb" part too. There is no explosion here or other mechanism to spread the substance. It's literally just a bottle of acid and nothing else.

**Comment by Maddremor** [comment]
> I'm planning on changing acid zombies and such to have something like acid ducts/glands that spray some boiling acid, instead of just having this weird video-gamey acid stuff. But, I'm unsure how long that'll take, so feel free to continue with what you are planning

Might I suggest making that an unspecified alien enzyme sort of thing instead of literal acid? Less risk of the player trying to make industry for it, and we can make the environmental protection needed to protect against it whatever we need it to.

**Comment by kevingranade** [comment]
I'm a fan of the boiling acid thing for this reason because once it fully reacts you're going to have an unharvestable mess.

For example the specific mix that bombadier beetles use is [hydroquinone](https://en.m.wikipedia.org/wiki/Hydroquinone) and [hydrogen peroxide](https://en.m.wikipedia.org/wiki/Hydrogen_peroxide).  Especially once it's partially reacted that's not going to be at all useful, and even the individual glands aren't going to be particularly valuable.

**Comment by zachary-kaelan** [comment]
https://www.militarynewbie.com/wp-content/uploads/2013/11/TM-21-210-Improvised-Munitions-Handbook-1969-Department-of-the-Army.pdf

Page 30 has an "acid type explosive". They soak a bunch of layers of cloth or paper with nitric acid, roll it up, then put it into a bottle with a blasting cap. I'm not entirely sure what it's supposed to do when it goes off.

**Comment by Holli-Git** [comment]
> https://www.militarynewbie.com/wp-content/uploads/2013/11/TM-21-210-Improvised-Munitions-Handbook-1969-Department-of-the-Army.pdf
> 
> Page 30 has an "acid type explosive". They soak a bunch of layers of cloth or paper with nitric acid, roll it up, then put it into a bottle with a blasting cap. I'm not entirely sure what it's supposed to do when it goes off.

Using my really poor understanding of chemistry, I think this isn't meant to be acidic as much as its supposed to make nitrocellulose, judging by the porous material used, and the fact you have to wait before detonating.

**Comment by zachary-kaelan** [comment]
It does say "optimized process for cellulose/acid explosives" so I think you're right on the money.

**Pull request merged**
