### PR TITLE
Migrate names to snippets & add weighted snippets

### LINKED ISSUE #70023: Translations for names share the same strings as others
### Describe the bug

1. After a commit #69919 in the translation file, some names share the same lines as other things like achievements, classes, mutations, actions.
2. After the same commit, the lines for the [names of seasons from the calendar](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/calendar.cpp#L750) disappeared somewhere - instead of them there were only lines with similar surnames. Season names are also needed separately from surnames.

for example:
```
#. ~ Name of achievement
#. ~ Snippet in category "<random_last_name>"
#: data/json/achievements.json data/json/snippets/names.json
msgid "Bowman"
```
```
#. ~ Snippet in category "<random_female_first_name>"
#: data/json/snippets/names.json
msgid "Autumn"
```
Winter/Spring/Summer/Autumn
Bowman
High
Ring
Read
Clay
Cotton
Diamond
Glass
Crystal
Gold
Honey
Silver
Stone
Bean
Wood
Field
House
Church
Block
Cross
Sunny
Light
Thrasher
Fish
Bird
Alpha <-(these one same, but maybe not in some language)
Quick
Scales
Hunter
Strong
Smart
Little
Tiny
Shell
Wolf
Bee
Craven
Hacker <-(and these same)
Farmer
Merchant
Miner
Barber
Carpenter
Foreman
Grove
Reed
Forest
Marina
Christian
Pagan

Upd 12.07:
Craft
Gates
Butcher
Sunday
Sugar

(looks like there's a lot more)

### Expected behavior

I'm expecting someone will separate these strings according to their context

### Versions and configuration

Transifex: master

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
Infrastructure "Migrate names to snippets & add weighted snippets"

#### Purpose of change
Unify the name snippets to use the strings in `names/*.json` everywhere. This should also relieve translators of the burden of having to translate gazillions of names, and fixes #70023:

image
(Over 10k strings untranslated, of which several thousand are names...)

This also implements weighted snippets so that snippets can now have different probabilities to be chosen, which is used to generate full names with snippets.

#### Describe the solution
Migrate code from `name.h/cpp` to `text_snippets.h/cpp`, and update related cpp/json code to use the snippet library and unified name tags.

The second commit adds weighted snippets, which accepts a `"weight"` value along with the snippet `"text"`, and the weight value is used when selecting random snippets from a category by considering all weight values in the same category.

#### Describe alternatives you've considered
Further migrate the name snippets to the normal snippet format, but the current format has the advantage of not requiring translations to have the same number of entries in the name list, which is not supported by the snippet format.

The removed names in dda and Mind Over Matter could be added to `names/*.json` maybe? @MNG-cataclysm @Standing-Storm what are your thoughts?

#### Testing
Tested creating worlds and characters, spawning NPCs and cities, and other related changes, and the names were generated correctly.

#### Additional context
I notice that the current snippets use `<full_name>` in multiple places, but `<full_name>` was actually expanded into the names of the crowdfunding donors, so I'd like some input on whether those are supposed to be any full name or only donor names.

The ~10000 deletion is mostly due to the removal of the snippet name lists.

### CODE REVIEW

**Comment by Standing-Storm** [comment]
Thank you for doing this. I was very surprised that <given_name> (etc) didn't work in dialogue. 

The names in that file in MoM were the top 500 most common given and family names in Massachusetts in (I think) 1990, so they would fit DDA's setting if you wanted to migrate them.

**Comment by GuardianDll** [comment]
Anything that stops us from merging this PR?

> I'd like some input on whether those are supposed to be any full name or only donor names
i think it's fine to have donors names in `full_name`

**Comment by Qrox** [comment]
> Anything that stops us from merging this PR?

I haven't got the time to test this PR yet. I'll probably do it in a few days.

**Comment by Qrox** [comment]
The tests keep failing for unrelated reasons :shrug:.

**Pull request merged**
