### PR TITLE
Fixed move cost for open privacy gate

### LINKED ISSUE #57607: Unable to drag a bicycle through an open gate
### Describe the bug

I am unable to move a bicycle or other vehicle through a wooden gate. As an example, a dairy farm spawns with a pristine quality bicycle, I drag the bicycle to the gates and open them expecting to ride out. I was unable to drag the vehicle through the gate despite it being open.

### Steps to reproduce

1. Teleport to a dairy farm with the wooden gate around it
2. Spawn a bicycle
3. Open the gate
4. Attempt to drag the bicycle through the gate, you will be unable to do so

### Expected behavior

I would expect that an ordinary person would be able to drag a bicycle through an open gate in a fence.

### Screenshots

image

### Versions and configuration

Using build 4a59e7d standard mod set.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Bugfixes "Fixed move cost for open privacy gate"

#### Purpose of change
* Closes #57607.

#### Describe the solution
Changed `movecost` from 1 to 2.

#### Describe alternatives you've considered
None.

#### Testing
Successfully dragged bicycle through the gate.

#### Additional context
None.

### CODE REVIEW

**Comment by metiscus** [comment]
That was incredibly fast!

**Comment by pjf** [comment]
@Night-Pryanik :Pardon my ignorance here, but how does this work? Does `move_cost` 1 or 2 have a special meaning? I thought it was just multiplied by 50 to determine how many moves it takes for the player to enter that terrain.

**Comment by Night-Pryanik** [comment]
This particular issue is not about "how many moves it takes for the player to enter that terrain", but rather about how many moves it takes to drag vehicles to that terrain. The dragging code (and especially collisions check with dragging) is convoluted, I still can't completely figure out how it works.

**Comment by pjf** [comment]
@Night-Pryanik : Thank you! That makes me feel much better about this being an occult incantation! :)

**Pull request merged**
