### PR TITLE
Adding a new tag to the sponge tool.

### PR DESCRIPTION
**Pull request by NEONZARIN**
#### Summary

```SUMMARY: Balance "Adding the ability to wash dirty clothes with a sponge"```

#### Purpose of change

```Adding a new tag to the sponge tool.```

#### Describe the solution

```Added "WASHCLOTHES" tag.```

#### Describe alternatives you've considered

N/A

image
image
image
image
image

### CODE REVIEW

**Comment by Fris0uman** [comment]
You need to follow the PR template. You're missing  the SUMMARY line, somthing like:
```SUMMARY: Balance "Adding the ability to wash dirty clothes with a sponge"```

**Comment by snake-eater911** [comment]
Why do we need this? 
We already have a tool to wash dirty clothing and this PR means that we need to go through 1 additional popup selection to wash CBMs. 
Besides, how do you envision washing a clothes with a soft foam rubber sponge?

**Comment by NEONZARIN** [comment]
Sorry for the incorrect filling of the PR template, it happened.

In real life, I can easily wash my clothes by folding its water tank using a sponge to wash off dirt. 
image
image

**Comment by snake-eater911** [comment]
> Sorry for the incorrect filling of the PR template, it happened.
> 
> In real life, I can easily wash my clothes by folding its water tank using a sponge to wash off dirt.
> image
> image

On the first image there's no sponge visible, while on the second, the sponge used has an _abrasive coating_ which is used to wash sneakers, which are themself relavitely sturdy, compared to clothing made of softer fibers...

**Comment by snake-eater911** [comment]
I take back my words on extra input, sort of, because I've misunderstood how the CBM cleansing works: I've thought that it requires one `apply/use item -> select dirty CBM` sequence per CBM, but in reality it works just as clothes washing, allowing CBM cleansing en-masse. It means that this extra input step won't be as huge a pain as I've thought initially.

**Comment by anothersimulacrum** [comment]
> Still, maybe some differentiation can be made in the clothes washing, so that the washboard is used for cleansing items made of soft materials (that is, ones having "soft": true) and the sponge for hard ones?

That's certainly possible, but requires C++ changes, which the author may not be comfortable with. I'll make that change after this PR is merged (or, more likely, allow the sponge to wash anything, and the washboard to only wash soft things).

**Comment by snake-eater911** [comment]
> > Still, maybe some differentiation can be made in the clothes washing, so that the washboard is used for cleansing items made of soft materials (that is, ones having "soft": true) and the sponge for hard ones?
> 
> That's certainly possible, but requires C++ changes, which the author may not be comfortable with. I'll make that change after this PR is merged (or, more likely, allow the sponge to wash anything, and the washboard to only wash soft things).

You can't realistically wash soft clothing with a sponge.

**Comment by kevingranade** [comment]
> You can't realistically wash soft clothing with a sponge.

Agreed, this would need to differentiate between cleaning hard clothes like shoes and most other clothes, which are flexible fabric.

**Comment by Fris0uman** [comment]
jenkins rebuild

**Comment by kevingranade** [comment]
Feel free to add a more nuanced, "can clean hard objects" flag, but as implemented here this doesn't work.

**Pull request closed without merging**
