### PR TITLE
Update hardcoded effects

### LINKED ISSUE #31792: Bleeding broken since 6 to 1 second time change
# Describe the bug

Not 100% sure on this but been playing a lot of stable D recently and noticing my heli crash guy isn't losing his limbs due to bleeding like they do in unstable.

# Steps To Reproduce

1. Start heli crash
2. Lose limbs to bleeding.
3. Load up stable, repeat, do not lose limbs.

# Expected behavior

Same between D and unstable.

# Versions and configuration

 - OS: W10
 - Game Version: 9213
 - Graphics version: Tiles
 - Mods loaded: dda

### PR DESCRIPTION
**Pull request by deadcutlass2**
```SUMMARY: Bugfixes "Update hardcoded effects post 1 second turns"```

Fixes #31792 and any other chance related effects that weren't updated from the 1 second change. 

manually went through and changed hardcoded values for 1 in # and x in y values by x6. 

effects changed:
fungal spores chance to give fungal infection
fungal infection symptom chance
bleed damage chance
Max duration of hallucination
vomiting during hallucination chance
npc messages from hallucination chance
hot/cold messages chance
hothead effect chance
dermatik formication increase chance
dermatik vomit chance
dermatik formication decrease chance
meth effects chances
teleglow effect chances
brainworms message chances
tapeworm message chances
bloodworms message chances
paincyst message chances
tetanus effect chances
datura effect chances
antibiotic recovery chances
wake from sleep chances
schizophrenia chances

Alternative:
set effects to go off only every 6 turns.

### CODE REVIEW

**Comment by FuelType-Memes** [comment]
Sorry for asking, and it might be out of scope of this PR, but is it possible to also check #31526 ?

**Comment by anothersimulacrum** [comment]
You need to use one of the magic words instead of addresses to automatically close issues.
Fixes and Resolves are two such.
See https://help.github.com/en/articles/closing-issues-using-keywords.

**Comment by kevingranade** [comment]
Just taking the first change, there's a bit of a problem:
```
            x_in_y( intense, 150 + u.get_healthy() / 10 ) ) ) {
            x_in_y( intense, 900 + u.get_healthy() / 10 ) ) ) {
```
you changed the fixed pert of the probability by a factor of 6, but then it is added to ``u.get_healthy() / 10``, which was not adjusted. The result is the base time between infections becomes about the same, but health no longer meaningfully contributes (health is centered on 0, it can be positive or negative, so there's no net change if health is neutral, there's just no change if it's positive or negative)

Also I'm not 100% sure this needs changing, need to check it on a case by case basis.

**Comment by deadcutlass2** [comment]
fixed the example and the others like it where a number was added within the parenthesis of the function. I also went back through to double check that it wasn't multiplying a secondary chance function after a primary chance function.

**Comment by EvgenijM86** [comment]
I remember meth was almost completely useless because it caused dead tired/exhausted status after a single use and you had to sleep several days. I hope this fixes it.

**Pull request merged**
