### PR TITLE
Bronze tools expansion

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Bronze tools expansion"

#### Purpose of change
Expand the selection of bronze tools available in game by making Innawoods-only tools available outside of this mod as well.

#### Describe the solution
Move relevant item and recipe definitions from mod files into game files.

Bronze tools had their damage stats adjusted to be inbetween equivalent copper and steel items. 
  
Shear quality was added to bronze shears, so that it's usable for shearing animals, and fabric cutting cuality was added to steel shears.
  
NONCONDUCTIVE flag was added to both steel and bronze hoe; apparently was an oversight that they didn't have it.
  
Amount of bronze used for crafting bronze axe and bronze pickaxe was increased to more closely match the resulting axe's weight.
  
Bronze sickle had volume and weight increased so as to not be less than the steel sickle.
  
Bronze hoe had wood sawing quality removed and description changed, because the steel hoe doesn't have it and because hoes and adzes are actually different tools. Shouldn't meaningfully impact Innawood mod gameplay as the same qualtiy is already available from the stone adze.
  
Brush axe was changed to be more like an axe rather than a polearm; brush axes just aren't long enough to be used like polearms. I've decided to not remove grass cutting quality despite brush axes being useful for cutting only bushes and branches, because machete has this quality as well and fulfills pretty much the same role in real life. An improved steel variant of it was also added.

#### Describe alternatives you've considered
Adding more entirely new bronze tools and weapons, but decided to deal with already-existing ones first.

#### Testing
Launched the game, made sure that no errors happen with the changes.

#### Additional context
None.

### CODE REVIEW

**Review by Light-Wave — APPROVED** [review]

**Comment by Sathra225** [comment]
The brush axe from Innawoods is based on a black bill, not a kaiser/sling blade. That's why its so long, as those actually **were** polearms. Its only called a brush axe as that's the American term.
Same with the bronze hoe, its really a foot adze/foot hoe. Again, that's why its as long as it is. Adzes were used for hoeing ground, but the stone version is too short to really be good at it.
The bronze shears are what are also known as 'spring scissors'. I'm not actually sure if you could shear something with them.

**Comment by AtomicFox556** [comment]
> The brush axe from Innawoods is based on a black bill, not a kaiser/sling blade. That's why its so long, as those actually **were** polearms. Its only called a brush axe as that's the American term.

Got it. I'll just rename it to bill then to avoid any potential confusion in the future, as brush axe apparently can mean multiple things and this is what made me confused.

> Same with the bronze hoe, its really a foot adze/foot hoe. Again, that's why its as long as it is. Adzes were used for hoeing ground, but the stone version is too short to really be good at it.

I'll add back wood sawing quality to both bronze and steel hoe then. It's never stated exactly what kind of hoe the steel hoe is, anyway, so chances are a steel one could work as well. If this turns out to not be a workable solution though, I'll have to remove it from both as I can't imagine bronze tools being better in any aspect than steel tools, except possibly resisting corrosion better.

> The bronze shears are what are also known as 'spring scissors'. I'm not actually sure if you could shear something with them.

Do they have to be, though? There are those bronze shears which should work fine for this. Innawood players may want that anyway in case they manage to acquire shearable animals somehow. https://trc-leiden.nl/trc-needles/media/k2/items/cache/c1ccbbb5854f60572ac1af4428093ae1_XL.jpg

**Comment by Sathra225** [comment]
Sounds good. The 'forged shears' are also spring scissor-type, just heavy duty. So could increase the weight for the bronze instead.

**Comment by AtomicFox556** [comment]
> Sounds good. The 'forged shears' are also spring scissor-type, just heavy duty. So could increase the weight for the bronze instead.

They already have higher weight than steel shears.

**Pull request merged**
