### PR TITLE
Eternal Season

### PR DESCRIPTION
**Pull request by wito**
Adds a world option to permanently set the current season to the initial season.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Nuclear winter!

**Comment by chaosvolt** [comment]
Whiler I've yet to make a character last 127 days without boredom or Fun ensuing, I like this concept.

**Comment by Nymall** [comment]
How will this affect crops? Aren't they based on the season length?

**Comment by chaosvolt** [comment]
That also makes me wonder what happens if you set construction scaling to 0, which is stated to scale it to season length.

**Comment by wito** [comment]
Eternal might be the wrong word; repeating would perhaps be better.

The season length is still in play, the change is that the season rolls over into itself. Crops proceed as normal, and harvestables still respawn (although not as regularly as with normal seasons; having fruit trees respawn requires staying away from them entirely for a season).

**Comment by chaosvolt** [comment]
Oh, that makes more sense. Not sure how to make trees update in that case.

**Comment by Zireael07** [comment]
> Nuclear winter!

What I wanted to post but Rivet was faster :(

Can't wait to try it out :P

**Comment by Midaychi** [comment]
It'd be better to have all the seasons like normal but instead override the weather of the seasons. Then you wouldn't break anything or have to code in too many special exceptions, and in order to grow crops you'd have to have like, atomic powered underground greenhouses or something.

**Comment by wito** [comment]
The code added to support eternal seasons have _no_ special exceptions.

Trees continue to work by virtue of code that is already in; and not much, if anything, else is actually affected. If anything, what you are proposing would require special exceptions.

**Comment by chaosvolt** [comment]
Ah, I see. Oh right, trees do work right, just that you have to be away from them? o.O

**Comment by wito** [comment]
In short, it's because trees aren't items or creatures with life cycles, they are just dumb terrain objects. There is a check in the system that moves their life cycle forwards that will regenerate them if they are loaded after having been unloaded for more than SEASON_LENGTH days, which is the check that allows eternal season trees and brush to respawn; and so they do, but they are tricksy compared to standard seasons, to be sure.

Still; it doesn't matter much: Spring,
Summer and Autumn has plentiful food, and in the winter there isn't fruit on the trees anyway.

**Comment by chaosvolt** [comment]
Ah, I see. No way to work around the need to KEEP them unloaded that long, I'm guessing? Being able to wait a season length, unload them briefly then come back would probably give some odd-looking results, but would be less awkward. Not sure how to do such a thing though.

**Comment by wito** [comment]
Not without a rework of how harvestables work.

**Comment by chaosvolt** [comment]
Ah right, I see. o.o

**Comment by Midaychi** [comment]
@wito I've been messing around with this and I've noticed that the game still processes the temperature graph to some degree. IE: after three "Months" of eternal winter, the coldest temperature you'll see is 65F, whereas it started around 32F

**Pull request merged**
