### PR TITLE
allow dense bones and bovine mutations to stack hp modifiers

### PR DESCRIPTION
**Pull request by MushroomW**
#### Summary
None

#### Purpose of change
As of right now said mutations do not stack with tough or with each other
this is my first time contributing here

#### Describe the solution
No response

#### Describe alternatives you've considered
No response

#### Testing
no errors on load. hp modifier works

#### Additional context
No response

### CODE REVIEW

**Comment by Terrorforge** [comment]
Does hp_modifier_secondary stack with other instances of hp_modifier_secondary? Because otherwise this makes them not stack with the Resilient line of mutations, which is kind of the whole point.

And if they do stack, do they stack multiplicatively or additively? I don't think it makes a huge difference in itself, but it could make a difference in combinations with other bonuses.

**Comment by MushroomW** [comment]
> Does hp_modifier_secondary stack with other instances of hp_modifier_secondary? Because otherwise this makes them not stack with the Resilient line of mutations, which is kind of the whole point.

i tested it real quick it seems that higher values of hp_modifier_secondary override previous values so it doesn't stack but if for example you crossed the chimera threshold and gained an hp mutation it would override it with the new multiplicative higher value and if they have the same value no change in hp would happen. i'll add  "hp_adjustment":  which gives flat hp instead of multiplicatively and since it's a different effect it shouldn't conflict with any current mutation

**Comment by MushroomW** [comment]
> They don't necessarily need to stack. Since Dense Bones is a prerequisite for Bovine Bulk, it's fine if Bovine Bulk just "upgrades" the bonus from 7 to 20. Or you can give Bovine Bulk 27, and it would be the same as if they stacked.
> 
i did that
> The new flat bonuses do seem a bit high, though. With the old version, Bovine Bulk would give about 10hp, 15 at most, so increasing it to 20 is a pretty significant buff. I'm not necessarily opposed, just be aware that you're making these mutations almost twice as strong.

i'm not great at balancing so i'm not sure which number would be best, also because it's an additive number now higher hp players will gain less hp from this mutation and vice versa due to how multiplicate calculations work

**Comment by MushroomW** [comment]
> > because it's an additive number now higher hp players will gain less hp from this mutation and vice versa due to how multiplicate calculations work
> 
> In theory. But in order for a 10% hp bonus to be larger than a flat 20hp, you would have to have more than 200 base hp. I think the highest I've ever achieved was 193, and that's _with_ Tough and TAAANK. So the only characters who would end up with less hp would be ones that have been pumping Strength with Stats Through Kills and maybe some of the more extreme mod mutants.
> 
> But either way we're not talking about _that_ much more hp. Maybe 10-20 extra with old numbers, now it's probably a little less than before for Bovine Bulk and maybe 10 extra for Bull Roids. Looks totally fine to me, balance-wise.

**Pull request merged**
