### PR TITLE
Migrate uilist to ImGui

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Infrastructure "Migrates the generic uilist class to ImGui"

#### Purpose of change
Continuing work on top-level UI elements and working my way down, uilist tends to show above everything so is a fair choice to migrate.

#### Describe the solution
Based on some work by @db48x , I took a bit of a different approach (using a private implementation class rather than having uilist extend from cataimgui::window) but I used all the ImGui/cataimgui calls from that code and moved them into the p_impl class. This allows us to interface with the p_impl just like a ui_adaptor

#### Describe alternatives you've considered
could have kept the original approach, but IMHO I really prefer to not include imgui-related headers from other headers, this is mostly based on my own pet peeve.

#### Testing
Load inventory UI, examine an item, see that the uilist draws properly. similar thing from the main menu -> load menu, see that uilist draws properly.

#### Additional context
Old: uilist_old
New: uilist_new

### CODE REVIEW

**Comment by db48x** [comment]
Lol, just yesterday I spent a few hours rebasing and cleaning up my patch; guess I wasn’t quick enough.

On a quick skim, the first thing I notice are the commented out lines. A number of lines that used to call `invalidate_ui` that aren’t needed any more, and of course the obsolete code for drawing the text–based ui. None of it is needed any more, so I recommend getting rid if them all.

I’ll review it more thoroughly in the morning.

**Comment by katemonster33** [comment]
> Lol, just yesterday I spent a few hours rebasing and cleaning up my patch; guess I wasn’t quick enough.
> 
> On a quick skim, the first thing I notice are the commented out lines. A number of lines that used to call `invalidate_ui` that aren’t needed any more, and of course the obsolete code for drawing the text–based ui. None of it is needed any more, so I recommend getting rid if them all.
> 
> I’ll review it more thoroughly in the morning.

Hey! Sorry, I actually tried to message you on Reddit to see if you were still interested in this work, never heard back. If you wanna keep going with this I'll put it down.

**Comment by katemonster33** [comment]
The biggest minefield I am seeing with the work is the callback system, lots of places use the callback to overwrite the window and I have no clue how to handle it

**Comment by db48x** [comment]
No, don't stop now that you have momentum!

I really must sleep, but I will take a closer look in the morning. If I have fixes for anything that you haven’t already done, I’ll send you a PR.

**Comment by db48x** [comment]
Man, I hadn’t even gotten as far as these callbacks. I think that anything using the callback just needs to do its own thing and call ImGui directly.

However, since it seems that they mostly use it to put information to the left or right of the uilist’s list of choices, perhaps we should just put some empty widgets there with known IDs and let the caller fill them in if they want to. This would be less work than completely rewriting the four things that use the callback.

Also, there's still some confusion in the code about ints vs uints:

    src/ui.cpp: In member function ‘virtual void uilist_impl::draw_controls()’:
    src/ui.cpp:86:33: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
       86 |         ImGui::Selectable("", i == parent.fselected, flags);
          |                               ~~^~~~~~~~~~~~~~~~~~~

**Comment by katemonster33** [comment]
@db48x i definitely jumped the gun with taking on this migration so soon after ImGui was enabled globally. i will be busy with imgui-related issues for a few weeks probably. if you have some interest you should definitely pick this up

**Comment by db48x** [comment]
Cool. I made some progress this weekend; I’ll be able to keep all of the callbacks, re–implementing them in terms of ImGui commands.

**Comment by katemonster33** [comment]
@db48x looks like you are making steady progress on this work on your own branch so I am going to close this PR unless there's a reason you want it to stay open.

**Comment by db48x** [comment]
This one may as well stay open. My PR is in your repository, and updates this branch. And I would value your time, if you wanted to run your eye over my changes. I know that there will be bugs, and it would be nice to spot their causes early if we can :D 

But if you do prefer to close this PR then I can open my own; that’s no great trouble.

**Comment by db48x** [comment]
Once #73538 is merged, I’ll rebase this branch on top of it to clean up the code.

**Comment by katemonster33** [comment]
Looks like @db48x opened a new PR for this work so I'm closing this

**Pull request closed without merging**
