### PR TITLE
Rebalance floor trunks

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

```SUMMARY: Balance "Floor trunks are their own separate item, and weigh more than an aisle without a trunk."```

#### Purpose of change

Floor trunks do everything that aisles do, use the same materials, and provide some of the best storage in the game. They're also extremely light, require minimal skills to install, and don't slow movement.

The result is that any vehicle is aisles is *always* better if the aisles are removed and replaced with floor trunks, which can be made from the exact same aisles that were removed. This encourages every-floor-a-trunk vehicles, and makes regular aisles something that would never be installed unless roleplaying.

This PR seeks to make aisle vs floor-trunk a more meaningful choice.

#### Describe the solution

Floor trunks are now their own separate vehicle part. This results in the following gameplay changes:

- Finding a vehicle with floor-trunks is more exciting, as they're more valuable for salvage or use.
- It's no longer possible to remove all aisles from a vehicle and reinstall them as floor-trunks using the exact same materials, which always felt cheesy and realism-breaking.
- Floor trunks now weigh more than a regular aisle (18kg vs 6kg), so the choice of aisle vs floor-trunk becomes more meaningful.
- Floor trunks can be player-made at fabrication 4, similar to other cargo parts. They require three sheet metal and two clockwork (which felt the most appropriate for hinges?).

#### Describe alternatives you've considered

- Recoding the vehicle system to have a sense of the clearance under a vehicle and how parts impact that, so floor trunks could only be fitted into spaces where it would reasonably make sense to do so.
- Leaving things as-is.

#### Additional context

This is my first time altering vehicle parts, so an extra check of my changes would be appreciated.

### CODE REVIEW

**Comment by kevingranade** [comment]
You hit the nail on the head with the clearance thing, that's why you don't
normally see these.

We might just want to do that, it shouldn't be too hard to require e.g.
require lifted suspensions (with built in drawbacks) that provide "high
clearance", which is then used by the floor aisles.

**Comment by pjf** [comment]
Aha! A few thoughts on clearance, then:

On a simple level, both lifted suspensions and plain big wheels can be used to increase undercarriage clearance, which could then be used to determine the maximum size of engines, tanks, aisle hatches, and the like. Lifted suspensions should reduce manoeuvrability, as they raise the centre of mass and reduce the ability to take corners at speed.

On a more complex level, one could split clearance into below-floor clearance (described above), and above-floor clearance (from the floor to the roof). This would impact the size of interior fixtures (seats, beds, kitchen units, floor-level tanks, cargo, etc) that could be placed.

On a very complex level, the clearance may differ *per square* of the vehicle. A kneeling bus has a very low under-floor clearance for the most part, but with notable raised sections of floor for the wheels and engine. A typical sedan is entirely under-floor clearance under the hood.

In any case the more vertical space a vehicle has, the higher its centre of gravity, and the less manoeuvrable it becomes.

---

In any case, I'd like to propose that my changes in this PR makes floor trunks less unbalanced than they presently are, even if we change the mechanics for them in the future. :)

**Comment by pjf** [comment]
Updated the tests, but there's still one failing and my consciousness has dropped too low for me to figure out why:

```
vehicle_efficiency.cpp:277: FAILED:
  CHECK( adjusted_tiles_travelled <= max_dist )
with expansion:
  315609 (0x4d0d9) <= 314009 (0x4ca99)
```

**Comment by kevingranade** [comment]
I'm fine with these adjustments also, I misspoke when I said, "might just want to do that".

Each number passed to vehicle_test() after the first sets an expected range for a different scenario, the second one is distance on pavement.

I'm not clear on why the distance got longer though.

**Comment by Rivet-the-Zombie** [comment]
>two clockwork

Far too tiny and way too rare. Should use some springs and scrap instead.

**Comment by dom4op** [comment]
>The result is that any vehicle is aisles is always better if the aisles are removed and replaced with floor trunks

To be fair, sometimes you need aisle lights more than floor trunks. But a regular aisle vs floor trunk is a no-brainer, agreed.

**Pull request merged**
