### PR TITLE
Include headers to fix builds on Windows (CB+MSYS/VS) and OSX

### LINKED ISSUE #23001: Regression: Unable to build on Windows
I would blame #22917 or something else related to pimpl.  

# Errors in build log (Visual Studio):

````
Severity | Code | Description | Project | File | Line | Suppression   State
Error | C2139 | 'auto_pickup': an undefined class is not allowed as an argument to   compiler intrinsic type trait '__is_constructible' | Cataclysm | C:\Program Files (x86)\Microsoft Visual Studio   14.0\VC\include\type_traits | 487 |   |  
Error | C2139 | 'bionic_collection': an undefined class is not allowed as an argument to   compiler intrinsic type trait '__is_constructible' | Cataclysm | C:\Program Files (x86)\Microsoft Visual Studio   14.0\VC\include\type_traits | 487 |   |  
Error | C2139 | 'effects_map': an undefined class is not allowed as an argument to   compiler intrinsic type trait '__is_constructible' | Cataclysm | C:\Program Files (x86)\Microsoft Visual Studio   14.0\VC\include\type_traits | 487 |   |  
Error | C2512 | 'pimpl<auto_pickup>::pimpl': no appropriate default constructor   available | Cataclysm | C:\Projects\Cataclysm-DDA\src\npctalk.cpp | 4537 |   |  
Error | C2512 | 'pimpl<bionic_collection>::pimpl': no appropriate default   constructor available | Cataclysm | C:\Projects\Cataclysm-DDA\src\character.cpp | 114 |   |  
Error | C2512 | 'pimpl<effects_map>::pimpl': no appropriate default constructor   available | Cataclysm | C:\Projects\Cataclysm-DDA\src\creature.cpp | 40 |   |  
Error | C2139 | 'SkillLevelMap': an undefined class is not allowed as an argument to   compiler intrinsic type trait '__is_constructible' | Cataclysm | C:\Program Files (x86)\Microsoft Visual Studio   14.0\VC\include\type_traits | 487 |   |  
````

# Errors in build log (Code::Blocks and MSYS):

````
obj\Release\src\game.o:game.cpp:(.text+0x6181a): undefined reference to `trait_group::debug_spawn()'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x7cb): undefined reference to `Trait_group_collection::Trait_group_collection(int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x984): undefined reference to `Trait_group::Trait_group(int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0xac7): undefined reference to `Single_trait_creator::Single_trait_creator(string_id<mutation_branch> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0xbe7): undefined reference to `Trait_group_creator::Trait_group_creator(string_id<Trait_group> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x20df): undefined reference to `Trait_group_collection::Trait_group_collection(int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x22cc): undefined reference to `Trait_group_collection::Trait_group_collection(int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x23a1): undefined reference to `Trait_group::Trait_group(int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x2701): undefined reference to `Single_trait_creator::Single_trait_creator(string_id<mutation_branch> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x29ac): undefined reference to `Trait_group::add_trait_entry(string_id<mutation_branch> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x2c06): undefined reference to `Trait_group::add_trait_entry(string_id<mutation_branch> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x2d62): undefined reference to `Trait_group::add_group_entry(string_id<Trait_group> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x2e42): undefined reference to `Trait_group::add_trait_entry(string_id<mutation_branch> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.text+0x2ff4): undefined reference to `Trait_group::add_group_entry(string_id<Trait_group> const&, int)'
obj\Release\src\mutation_data.o:mutation_data.cpp:(.rdata$.refptr._ZTV24Trait_group_distribution[.refptr._ZTV24Trait_group_distribution]+0x0): undefined reference to `vtable for Trait_group_distribution'
obj\Release\src\npc.o:npc.cpp:(.text+0xe9c7): undefined reference to `trait_group::traits_from(string_id<Trait_group> const&)'
obj\Release\src\npc_class.o:npc_class.cpp:(.text+0x5658): undefined reference to `trait_group::load_trait_group(JsonIn&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
````

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Fixes #23001.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
If you're re-adding the headers, remove the non-functional forward declarations.  
Even better would be fixing the forward declarations, any idea what's going wrong @BevapDin?

**Comment by Leland** [comment]
Can confirm this fixes #22970 as well

**Comment by ZhilkinSerg** [comment]
Closing in advance of #23048.

**Pull request closed without merging**
