### PR TITLE
Rebalance s'mores nutritional value and crafting

### LINKED ISSUE #23792: S'mores give significantly less nutrition than their components
Game version: 7413

A stack of s'mores is 4 units of 2 nutrition each (total 8).  However, the components (8 graham crackers, 8 marshmallows, 1 chocolate bar) total to 88 nutrition, so s'mores only have less than 10% of the nutritional value of the ingredients.  

Since graham crackers and marshmallows come in units of 8 the intention might have been to use only 1 graham cracker and 1 marshmallow which makes more sense, but even that would be turning 18 nutrition worth of ingredients into 8 nutrition.

### PR DESCRIPTION
**Pull request by drhead**
resolves #23792

Before: Crafting s'mores requires 8 graham crackers (64 nutrition) 8 marshmallows (16 nutrition) and 1 chocolate bar (8 nutrition), returns s'mores with 4 charges that gives total 8 nutrition.

After: Crafting s'mores requires 1 of each component (total 18 nutrition) and s'mores now have a single charge that gives 24 nutrition.

### CODE REVIEW

**Comment by YakumoChen** [comment]
isn't that somewhat of a nerf to the chocolate bar? you need a lot less chocolate to make smores then any of the other ones.

**Comment by BorkBorkGoesTheCode** [comment]
This is an opportunity to reduce the s'mores stim value.

**Comment by drhead** [comment]
I'm not sure I would entirely call it a nerf to chocolate bars.  You could make an entire stack of smores with one chocolate bar, but they weren't good anyways.  I did it this way because chocolate bars in-game are only about 16 grams which is just over a half ounce, and spreading that over multiple smores made no sense.  With this you only get one smore per chocolate bar but you get a lot more out of it.

**Comment by Brambor** [comment]
Caused a bug #23938
I made pull request to fix that, hopefully I did it right.

**Comment by BorkBorkGoesTheCode** [comment]
@drhead maybe the chocolate bar could be made to resemble the 1.55 ounce Hershey bar and gain 4 charges?

**Pull request merged**
