### PR TITLE
Tweak robot/turret return fire to not be uselessly inaccurate

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
In #35784 a feature was added to have turrets and robots return fire, but the feature represented negligible risk to attackers because there was nearly no chance of a hit.  Also the chance to hit was nearly independent of range since it simply represented a chance to choose the right square out of 25 to target.

#### Describe the solution
The turret now always selects the correct target, but has a significant "recoil" number added to represent lack of ability to detect the target accurately.

#### Testing
Fired on turrets from outside their sight range from a variety of ranges with a variety of guns.
At long ranges (for the game, 20+ tiles), the turret would generally score a single hit on the player per burst.
At short ranges (5-10 tiles), the player would be hit by several rounds from each burst.

### CODE REVIEW

**Comment by Reclusive-reptile** [comment]
I can't find a reference to how accurate acoustic shot spotters are. The Raytheon Boomerrang system reports rough direction and range estimates to within 100m and most police systems can pinpoint a street address as the source of gunfire but as far as if these systems can find a target to within a 1m radius I just don't know.

**Comment by kevingranade** [comment]
Many of these systems are detecting location of gun discharge even without line of sight to the shooter. Given a line of sight and related simplifications, i.e. no reflections, it becomes a much easier problem and I expect triangulation to give the desired resolution.

**Comment by AlexMooney** [comment]
How about scaling the recoil similarly to how the noise markers are fuzzed:

https://github.com/CleverRaven/Cataclysm-DDA/blob/278da94c724fd30f6ca8b51a44e72e05e25664d4/src/sounds.cpp#L490-L497

It's only fair that if a player can't pinpoint where a gunshot comes from, then the turret can't do a good job calculating it.  Of course, a turret probably has the equivalent of bionic ears.

**Comment by kevingranade** [comment]
That's more or less what adding a flat recoil value does, recoil is a radial measure, so the further the target is from the turret, the wider the target area.

**Pull request merged**
