### PR TITLE
Map reference migration part nine

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
See #41347 for initial implementation.
The goal is to remove unnecessary game.h inclusions.

#### Describe the solution
This is the ninth in a series of PRs to transition to using the map getter instead of calling directly through the game instance, doing bulk editing instead of targeted edits.
I opportunistically migrated instances of g->u to get_avatar() or get_player_character() as well.
I also downgraded a number of references of type player and avatar to Character to further reduce inclusions.

#### Testing
This is strictly a refactor, so unless I make a horrific entry mistake if it builds it should work.

### CODE REVIEW

**Comment by kevingranade** [comment]
clang-tidy complained about something in sound.cpp, but I didn't change any related code, so I think that was a pre-existing issue.
```
Error while processing /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/sounds.cpp.
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/sounds.cpp:1071:13: error: assigning to 'const player *' from incompatible type 'avatar *' [clang-diagnostic-error]
        p = &g->u;
            ^
```
I'm not really clear what it's complaining about offhand.

**Comment by EvgenijM86** [comment]
The code that it complains about was updated in 2015 and 2017 commits. via `git gui blame src/sounds.cpp`

**Comment by EvgenijM86** [comment]
Adding `#include "avatar.h"` to sounds.cpp fixes the issue for me.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Adding `#include "avatar.h"` to sounds.cpp fixes the issue for me.

We want to get rid of that include.

Possibly that should work:

```DIFF
diff --git a/src/sounds.cpp b/src/sounds.cpp
index 41af771d22..1dfaa4c192 100644
--- a/src/sounds.cpp
+++ b/src/sounds.cpp
@@ -1066,9 +1066,9 @@ sfx::sound_thread::sound_thread( const tripoint &source, const tripoint &target,
 {
     // This is function is run in the main thread.
     const int heard_volume = get_heard_volume( source );
-    const player *p = g->critter_at<npc>( source );
-    if( !p ) {
-        p = &g->u;
+    npc *np = g->critter_at<npc>( source );
+    const player &p = np ? static_cast<player &>( *np ) : dynamic_cast<player &>( get_player_character() );
+    if( !p.is_npc() ) {
         // sound comes from the same place as the player is, calculation of angle wouldn't work
         ang_src = 0;
         vol_src = heard_volume;
@@ -1079,8 +1079,8 @@ sfx::sound_thread::sound_thread( const tripoint &source, const tripoint &target,
         vol_targ = std::max( heard_volume - 20, 0 );
     }
     ang_targ = get_heard_angle( target );
-    weapon_skill = p->weapon.melee_skill();
-    weapon_volume = p->weapon.volume() / units::legacy_volume_factor;
+    weapon_skill = p.weapon.melee_skill();
+    weapon_volume = p.weapon.volume() / units::legacy_volume_factor;
 }
 
 // Operator overload required for thread API.
```

**Comment by EvgenijM86** [comment]
@ZhilkinSerg, your compilation fix works on my machine. I did remove my own fix `include "avatar.h"` before trying yours.

**Pull request merged**
