### PR TITLE
Steel Grades

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Adds grades of steel and two hardened varieties."

#### Purpose of change
The game uses three types of steel currently: Budget, Steel, and Hard. The middle option covers too broad of a range. Aside from poorly made weapons and some armor plate, one kind of steel is used for a huge range of items.

#### Describe the solution
Existing steel (budget, steel, hard steel) remain in game as-is.
Adds
Low Carbon Steel, bash 5, cut 5, bullet 3
Med Carbon Steel, bash 6, cut 6, bullet 3
High Carbon Steel, bash 9, cut 9, bullet 5

Also adds two materials that should only be the result of crafting an item.
Case Hardened Low Carbon Steel, bash 9, cut 9, bullet 5
Tempered Medium Carbon Steel, bash 10, cut 10, bullet 6

#### Describe alternatives you've considered
None.

#### Testing
Thickness 2 of low carbon performs identical to the existing light plate armor.

#### Additional context
Damage resistance is based on the Energy (kJ/m2) needed to defeat (leave a 5mm hole or initiate a fracture) 2mm of steel. The result is compared against the defensive values of iron (using existing bash/cut/bullet). This was based on a test used by Alan Williams in "The Knight and the Blast Furnace", p941. 
Energy to defeat = sum(200+(100*[carbon percentage])-(5*(POW([slag percentage],2)))) 
This is a sheet showing the calculations used,  the carbon and slag content can be changed to represent different grades of steel, especially by adding slag to represent poor quality steel. [https://docs.google.com/spreadsheets/d/1OnByS1P2iCSPtHrUtS9O9R7NtkaEdpE-3yNUbpHPD38/edit?usp=sharing](url)
References:
Machinery's Handbook, twenty ninth edition. ISBN: 978-0-8311-2900-2
Applied Welding Engineering, third edition. ISBN: 978-0-12-821348-3
The Knight and the Blast Furnace: A History of the Metallurgy of Armour in the Middle Ages & Early Modern Period. ISBN 9004124985

### CODE REVIEW

**Comment by Shodan14** [comment]
You could call hard steel "tool steel" if you want to be fancy about it.

**Comment by Shodan14** [comment]
Maybe call hard steel hardened steel and make one of the high carbon ones tool steel?

**Comment by Drew4484** [comment]
> Maybe call hard steel hardened steel and make one of the high carbon ones tool steel?

Tool steel is very broad but in general I'd like to avoid adding more types of hardened steel as it would be very difficult or impossible for a survivor to make/work.

**Comment by Drew4484** [comment]
Realized I need to update chip protection, will do later today.

**Comment by kevingranade** [comment]
Re: tool steels, my understanding is that you really are not going to want to/be able to use a tool steel for anything other than tools.  The hardness of that kind of material is way off in the zone where it's too brittle for armor, or most other things for that matter.
Also it's prohibitively hard to work as Drew mentioned.

**Comment by Drew4484** [comment]
> Maybe call hard steel hardened steel and make one of the high carbon ones tool steel?

The one big advantage I see to adding tool steels and other exotics would be phasing out 'superalloy'. 
Check out #54606, where I've added some (very simplified) conversion recipes. If you have suggestions for changing them or adding options for tool steels, I'm all for it. If you look at the linked spreadsheet you should be able to sort out the calculations I used to stat out the existing options.

If tool steels are added I would suggest two limits: 
1) No single-application metals. If we're adding a new material, spawns, and recipes, I wouldn't want to do that a dozen different times for a metal that is only going to appear on one item in game.
2) Practical manufacturing. The steel in game is simplified, but using techniques that don't require massive metalworks and huge amounts of material/electricity. If it can be made in somebody's yard, that would be a good candidate.

**Pull request merged**
