### PR TITLE
Starting clothes rearranged

### PR DESCRIPTION
**Pull request by niglow**
Tired of characters starting with their underwear on top of other clothes like a superhero wannabe?

### CODE REVIEW

**Comment by WizardOfOoo** [comment]
I'm glad I'm not the only one that is bothered by that.

**Comment by Leland** [comment]
Completely agree. I know that some in the CDDA community prefer to put their least protective/expensive clothing on top so that it receives damage first, but that shouldn't be the default behavior of starting professions.

**Comment by sethsimon** [comment]
Great idea. But what if men get a certain overcoat and women get some other overcoat? Ideally, starting clothes should always be in order by layer, no matter what the JSON author does.

**Comment by Coolthulhu** [comment]
> Ideally, starting clothes should always be in order by layer, no matter what the JSON author does.

It wouldn't actually be too hard to write: just sort the `player::worn` vector by `item.get_layer()` after all items are put on. Preferably using `std::stable_sort`.

**Comment by niglow** [comment]
Clothes are sorted by layers now. In rare cases like with biker-girl bra ends up being on top of the tank-top because they both are "close to skin" but other cases look ok.

**Pull request merged**
