### PR TITLE
[MoM] Some concentration powers were missing kcal cost + XP gain

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Bugfixes "[MoM] Some concentration powers were missing kcal cost + XP gain"

#### Purpose of change

As title.  Some concentration powers were missing both the kcal cost for maintaining them and the XP bonus for same.

#### Describe the solution

Adding missing lines.

#### Testing

Loaded game, concentrated on a few of the appropriate powers, saw XP gains and no errors.

### CODE REVIEW

**Comment by Montimorency** [comment]
Oh sweeet, I had noticed the lack of leveling (after the original lack of leveling was fixed last year) a little while ago but assumed it was a nerf. That is, at first it seemed as though the experience gain might be much lower than with activations; I needed longer to realize that it was actually zero. 

On that topic, Far Hand (possibly the most useful utility function ever modded into the game) used to pull objects as far as the power's level would allow, landing either adjacent to or under the player. E.g. if the max range was 10 at a given time, you could always bring items from 10 tiles away by or beneath your character. But at some point, it came about that Far Hand would no longer pull items more than either 6 or 7 tiles at a time under any circumstances - except with Nether Attunement present - even with the power maxed out at Level 18. 

Is this intended?

**Comment by Standing-Storm** [comment]
That sounds like a bug--Nether Attunement should change the maximum possible range, not the maximum effective range.

**Comment by Montimorency** [comment]
Ah, but if the maximum effective range is capped to 7 now, what does the maximum nominal range represent?

**Comment by Standing-Storm** [comment]
Hmm. Having just tested it, it is acting oddly--there shouldn't be any random factor, it should pull the target the entire distance.

**Pull request merged**
