### PR TITLE
Add titanis walleri from Aftershock to Megafauna, small Megafauna fixes

### LINKED ISSUE #66226: Move Aftershock titanis/terror bird to Megafauna
### Is your feature request related to a problem? Please describe.

So, I used both Aftershock and Megafauna in one of my runs. I met a terror bird, and thought it was a Megafauna beast. Some time later, I was surprised to learn it was an Aftershock beastie. An animal that existed in RL and should have been in Megafauna somehow was in the same file as various alien and non-real creatures (it was in aliens.json).

### Solution you would like.

A Megafauna version of titanis.
Addition of child terror birds/titani.
Rebalance the stats:

- all, or at least most phorusrhacidae should have GOODHEARING flag, based on the article that was based on a study of a well-preserved phorusrhacidae skeleton: https://spectrum.ieee.org/terror-birds-hunted-by-sound
- Weight rebalance - t. walleri is estimated at 150 kg while Aftershock one tops out at 120 kg
- Other changes, like aggression adjustments?

More terror birds?
Tameable titanis? They were likely smart enough to be tameable.

### Describe alternatives you have considered.
Moving titanis to where it belongs - Megafauna mod instead of making a new version.
None.

### Additional context

Some info on titanis walleri and its fossils:

https://www.researchgate.net/publication/249521166_Revised_age_of_the_late_Neogene_terror_bird_Titanis_in_North_America_during_the_Great_American_Interchange
https://www.floridamuseum.ufl.edu/florida-vertebrate-fossils/species/titanis-walleri/
https://en.wikipedia.org/wiki/Titanis

Some info that will be likely used for new titanis version (current terror bird already can grab, though):

http://antediluviansalad.blogspot.com/2015/09/terror-birds-cometh-new-theory.html?m=1

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Content "Adds t. walleri to Megafauna"

#### Purpose of change

Implements #66226

#### Describe the solution

Adds titanis to Megafauna with eggs and spawns. See attached issue.

Aimed to fit the bird as something in-between sabre-toothed cat and direwolf in terms of combat capabilities (while remaining as close to realistic as possible). There is no armor piercing on titani attacks (the "axe beak" is most likely a stereotype, IRL phorusrhacidae (terror birds) more likely grabbed with beak and pulled with whole their body, like vultures), and its attacks are less reliable (3 hit dice instead of 4), but at the same time it gets access to bite grabs, drags, knockback kicks and takedowns (implied to be precise kicks).

Fixes:
- Direwolf cubs can play now
- Auks can spawn from egg now (the egg tried to spawn a non-existing group on rot)

Also, can someone explain to me why animals blacklisted in Megafauna (like "mon_wolf_mutant_huge") are still listed in Megafauna's wilderness.json?

#### Describe alternatives you've considered

Simplify selection of attacks, use attacks that make more sense (ranged pull with distance = 2?), balance stats in a different way, change flags and reproduction properties.

Not doing this, as t. walleri may be out of scope of Megafauna. Will do fixes as separate PR then.

#### Testing

None for now, will do when possible.

#### Additional context

See relevant issue.

### CODE REVIEW

**Comment by randomtyper** [comment]
Aight, should be ready for review and merging.

**Comment by merrygin** [comment]
@randomtyper I don't mind at all in principle (reacting to your q from the corresponding issue), thanks for adding to the mod! :)

Although this particular creature is actually out of scope of the mod, unfortunately. The goal of the mod is to add creatures that humans might reasonably have encountered in NE around 10'000 years ago (thus, the first humans of the area), mainly in order to have more realistic fauna for an innawoods run. So creatures that died out 2m years ago or that only occur in very different parts of the Americas, like Florida in the case of Titanis, I wouldn't want to add.

I think I also outlined in the README what the scope is and whats pushing the limits. 

However, this is merged now anyway, so its totally fine, let's just keep it in for now.

**Comment by randomtyper** [comment]
> Although this particular creature is actually out of scope of the mod, unfortunately. The goal of the mod is to add creatures that humans might reasonably have encountered in NE around 10'000 years ago (thus, the first humans of the area), mainly in order to have more realistic fauna for an innawoods run. So creatures that died out 2m years ago or that only occur in very different parts of the Americas, like Florida in the case of Titanis, I wouldn't want to add.

It is perfectly possible for me to just axe the titanis out and leave the fixes in. That said, I put the spawn rate of titanis at about the same as glyptotherium, maybe I should reduce the number even more to represent the stray specimens that somehow managed to survive (there were surviving dinosaurs after Cretaceous–Paleogene extinction event, they just were past the line of survival, and fossils rarely perpesent full range of time the creature existed) and wander north? I personally find it at least somewhat believable.

And the .md doc mentions "Through the portals rupturing reality in the cataclysm, you were sucked into a world yet untouched by humans". Blob BS is involved, it could throw the player a million or ten years ago in time without much repercussions to realism (I would be more surprised if it strictly threw us into one point in time, I'd say). If it was "you are an ancient human that got lost", I'd remove the titanis right now without any arguments.

**Comment by merrygin** [comment]
Sure, I think its fine this way to let Titanis stay, its fun anyway!

**Pull request merged**
