### PR TITLE
[CR] Make ordinary walls non-flammable

### PR DESCRIPTION
**Pull request by Night-Pryanik**
I asked once about this change in IRC, few people said nay to it, but I want to try nevertheless.

First of all, the main question: what material ordinary wall, `t_wall`, is made of? Because depending on the answer, this whole PR will make or will not make sense at all.
After some research I came to these conclusions:
- it gives rock, nail, or splinter on destruction. Some sort of brick-wood combination?
- it seems very unlikely to me that most of modern buildings in late XXI century is made of wood or some other high-flammable material;

In my tests with non-flammable `t_wall` I set the furniture in houses on fire, and after the fire houses resemble boxes with burnt-out insides, just like IRL.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>what material ordinary wall, t_wall, is made of?

I'm pretty sure it's supposed to be wooden frame and drywall.

**Comment by Coolthulhu** [comment]
> it seems very unlikely to me that most of modern buildings in late XXI century is made of wood or some other high-flammable material;

Most houses in USA are made from wood. It would fit the retro-futuristic theme DDA has if they kept being wooden.

**Comment by Night-Pryanik** [comment]
@Rivet-the-Zombie well, then I'm a bit confused why it is much more sturdy than purely wood wall or palisade.
@Coolthulhu retro-futuristic? Oh, that's news for me. 
But not only houses, but almost every other buildings - including banks, military bunkers and other serious buildings - are made of it too. 
And also, we have separate wood walls for this.

**Comment by Coolthulhu** [comment]
I meant retro-futuristic as in "just basically copying the present, then adding robots and teleporters".

Cars right now are running mostly on gasoline, so cars in DDA are running mostly on gasoline, even if electric cars are likely to replace them in the future.

Electric cars right now have 1 large engine rather than 4 smaller (one per wheel, which is likely to happen in the future), so electric cars in DDA have just one large engine.

Houses in USA are made from wood, so houses in DDA are made from wood.
etc.

Unless there is a good reason for why should it differ, it probably shouldn't.

**Comment by tyrael93** [comment]
>Unless there is a good reason for why should it differ

Crazy untamed flamer NPCs attacking everything in their sight, burning everything in their path.
But I guess that could be a DDA thing.

**Comment by vache** [comment]
Making most walls not flammable is the wrong solution to that problem.  Smarter NPCs is the solution there.

**Comment by tyrael93** [comment]
Yeah, but that's gonna take years.

**Comment by kevingranade** [comment]
As noted in the op, even modern buildings tend to only partially collapse
after a fire, making the outer wall of a house or connercial building
non-flammable is pretty reasonable, though inner walls are another issue
entirely.  Inner walls should burn. How this relates in particular to
t_wall is tricky

Side issue:
> it seems very unlikely to me that most of modern buildings in late XXI
century

Three problems here, first, as coolthulu notes, the setting is
"contemporary with futuristic elements", second, construction methods don't
change particularly fast, so I *would* expect houses built in 2050 or so to
still be flammable, third, houses last a looong time, so new houses are
rarely in the majority.

**Comment by codemime** [comment]
> As noted in the op, even modern buildings tend to only partially collapse after a fire, making the outer wall of a house or connercial building non-flammable is pretty reasonable

We now have "transforms_into" for the terrain. As far as I can see it's used only for harvesting crops. My point is: we could use the same mechanics (maybe even the same field) for transforming terrain into burned terrain, which cannot be burned even more. Along with yet another field which specifies probability of burning to ashes (or rocks or whatever), it would produce solid remains of burned down buildings (and any other flammable stuff).

**Comment by Night-Pryanik** [comment]
We can change outer walls in most mapgen templates to something more sturdy and fire-resistant, leaving inner walls to be _flammable_ `t_wall`. This work will be really really huge, though.

**Comment by codemime** [comment]
@Night-Pryanik We could also use condition-based approach. For example:
if at least one pair of opposite adjacent tiles are floors (of some kind), then it's an inner wall.

scr

The task of determining outer walls seems to be related to the worthwhile proposal #15253.

**Comment by illi-kun** [comment]
It will be better/easier to explicitly define outer walls as separate terrain and not use conditions for doing so (because it adds excessive complexety for really small benefit). I see nothing wrong in step-by-step updating of all houses. Yes, it will take a lot of time but did we rush to some date?

**Comment by Night-Pryanik** [comment]
I thought that maybe we should leave all houses flammable as-is, but update the buildings I mentioned earlier (banks, hospitals, gun stores) with non-flammable outer walls.

**Comment by kevingranade** [comment]
Deciding on flammable vs non flammable walls based on adjacency to
inner/outer tiles would be reasonable *in mapgen*, and would be a 90%
solution to conversion.
Making them flammable or not based on the surroundings while in the game
would cause all kinds of issues.

**Comment by Night-Pryanik** [comment]
I think I'll close this pr as we came to the conclusion that it's better to change mapgen of specific buildings.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/no-hope-mod-v0-7/24971/1

**Pull request closed without merging**
