### PR TITLE
Allow practice of computers skill in the dark

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
Makes the practice of computers skill via recipes easy in the dark, all electronic devices used in the recipes are able to produce light so there is no need for an external light source.

#### Testing
dark_craftable
Can practice computers in the dark.

### CODE REVIEW

**Comment by actual-nh** [comment]
That was how it was originally set, but that would also allow it when blinded (for some reason other than light level).

**Comment by Wyrdean** [comment]
> That was how it was originally set, but that would also allow it when blinded (for some reason other than light level).

Memorized keys + text to speech?

**Comment by PatrikLundell** [comment]
I would have thought E-ink would be dependent on external light sources, as I thought it wasn't backlit.

**Comment by Wyrdean** [comment]
> I would have thought E-ink would be dependent on external light sources, as I thought it wasn't backlit.

The e-ink series is backlit in-game, though in real life they aren't, might be something worth changing

**Comment by kevingranade** [comment]
If they're producing light, they don't need this, right?

**Comment by actual-nh** [comment]
> If they're producing light, they don't need this, right?

Are they producing enough light for the character to be normally active?

**Comment by casswedson** [comment]
I guess if I think of "turning on" the phone or laptop as booting it up it does makes sense, 'cause I don't think I need to go out of my way to turn the screen of my phone or laptop to use it, that would be part of the many abstractions the recipe should make.
Maybe recipes was not the right way to go about implementing this specific set of actions, still this is also not a very good "fix" (see first comment), maybe a better solution will be made.

**Pull request closed without merging**
