### PR TITLE
Fix holes in libraries

### LINKED ISSUE #54237: Libraries have holes in the floor
### Describe the bug

Some variants of the library overmap special have holes in the floor (ledges).

### Steps to reproduce

1. Use the map editor to spawn a bunch of libraries
2. Walk to them (long range teleport masks this bug)
3. Find a variant with holes in the floor

### Expected behavior

I expected to find the concrete foundation in places where the wooden library floor is damaged.

### Screenshots

DeepinScreenshot_select-area_20220110100832

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: dd5c1fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Possibly related: #53549

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Fix libraries spawning with large holes"

#### Purpose of change
Fix #54237

#### Describe the solution
Replace "set": "point": "bash" with "place_rubble"

#### Testing
visit some vandalized libraries and notice that their isn't giant holes in the ground

#### Additional context
after fix
Screenshot (16)
Screenshot (19)
Screenshot (20)

### CODE REVIEW

**Review by Maleclypse — CHANGES_REQUESTED** [review]
Can you show a picture of a few vandalized libraries in this PR after your change?

**Comment by Paleiste** [comment]
> Can you show a picture of a few vandalized libraries in this PR after your change?

Done

**Comment by Maleclypse** [comment]
Ok yeah that's what I worried it would look like.  It looks like what you need to do is replace the set point bash with the following. So you can basically run the below across the same places as bash does.
```
### Place rubble and smash existing terrain with "rubble"

Creates rubble and bashes existing terrain (this step is applied last, after other things like furniture/terrain have
been set). Creating rubble invokes the bashing function that can destroy terrain and cause structures to collapse.

| Field       | Description
| ---         | ---
| rubble_type | (optional, furniture id, default: `f_rubble`) the type of the created rubble.
| items       | (optional, bool, default: false) place items that result from bashing the structure.
| floor_type  | (optional, terrain id, default: `t_dirt`) only used if there is a non-bashable wall at the location or with overwrite = true.
| overwrite   | (optional, bool, default: false) if true it just writes on top of what currently exists.

To use this type with explicit coordinates use the name "place_rubble" (no plural) like this:

```json
"place_rubble": [
    { "x": 10, "y": 1 }
```

**Comment by Paleiste** [comment]
> Ok yeah that's what I worried it would look like. It looks like what you need to do is replace the set point bash with the following. So you can basically run the below across the same places as bash does.

I added your suggestion and updated my PR with the new changes.

**Comment by Maleclypse** [comment]
That looks good! I'll adjust my review after tests complete

**Review by Maleclypse — APPROVED** [review]
Thank you for doing this!

**Pull request merged**
