### PR TITLE
(Beta) National Guard Camp

### PR DESCRIPTION
**Pull request by acidia**
The national guard camp has entered a playable state and I need a bit of feedback to see what people think.  I had to cut a few things to squish it all into a mod but it shouldn't provide any game breaking bugs since it isn't making major code changes.

Next I'll probably be looking into giving the enemies a basic death action and custom attack so they can identify when to switch to anti-armor mode for players in vehicles or wearing power armor (given that even basic power armor can tank 7.62).

I'll add a forum thread after it clears.  Still shooting for roughly end of the year to get it polished.

A continuation of #19257

Note:  I didn't use the linter on the building jsons yet since I have to cut the maps into 5 different chunks to prevent it from timing out and it makes spawn placement far harder by rearranging the spawn info below the map key so I have to scroll up and down a lot.  The unused map tiles in the basement will be culled as soon as I know we don't want to expand into them.

### CODE REVIEW

**Comment by mugling** [comment]
> Help test the national guard camp before inclusion into the base game

This is 113k lines. We currently have ~450k lines of JSON already. Sorry to say but with our current developer count and an attempt underway to reduce the bugs prior to releasing `0.D` there isn't any realistic chance of this being merged to core.

To support such works we may need to implement some system of mapgen deduplication - this has been discussed before, for example in #19387. Adding this many lines, even as a core mod, significantly affects the current work to cleanup mapgen.

The fact this doesn't pass linting only magnifies this problem. We merged the updated and linted `blazemod` under the promise that once it was cleaned up it would be maintained. This hasn't happened and we keep getting a large number of bug reports for it, some serious.

Even if this was reviewed 1 line per second it would take 19 hours to check everything. PR's affecting >1000 lines need some kind of automated proof. We've touched on this for example in #18330.

Rules about large PR's have existed forever and are well known so I'm closing this PR in accordance with them. Options would include distribution as a third-party mod or demonstrating that the content is programmatically generated or has some other method of automated verification.

**Comment by Coolthulhu** [comment]
Could be added to more locations mod and then moved to DDA once deduplication lands.

**Comment by mugling** [comment]
I did consider this but it still has the same maintenance problems whenever we work on mapgen. To make it even worse lack of linting prevents automated cleanup.

There's also the issue of fairness - why do we reject large PR's from one contributor at not another? This would increase the size of the projects json by 25% which is unarguably huge and no mitigations have been provided.

**Comment by Coolthulhu** [comment]
Mostly-duplicate json content, while bad, is not the same degree as "dense" content.
Mapgen is low density.

The actual content of that is closer to 5k lines. Rest is the giant copied over template.

If it was deduplicated into said 5k lines, it would be comparable effort to reviewing a 0.5k line code PR. Simply because of how sparse mapgen data is.

**Comment by mugling** [comment]
> The actual content of that is closer to 5k lines. Rest is the giant copied over template.

That part needs fixing before any merge. Blazemod has been illustrative - I spent a long time writing automated tooling and unit tests for it on the promise that it would be be maintained and that just hasn't happened - not a single maintenance fix from the author and we've reached the point where we just close bugs for it unanswered and suppress the load errors by deleting content.

We can't continue in the current manner where anyone merges content then a tiny number of developers have to maintain it for all time. The rules about PR line count have always existed. I'm not disagreeable to reducing them when there is good reason but I'm not seeing one here. Linting and especially deduplication would reduce this burden a lot and are prerequisites for a merge.

**Comment by mugling** [comment]
@acidia can you post some examples of the duplicated sections so I can take a look at what code support for those might look like

**Comment by acidia** [comment]
Sure, for every overmap tile on z=0 the building utility program used the following template to generate the json.  The z=-1 is a dozen or so lines longer.  This is repeated 484 times, nearly identically from the building utility.
`{
    "type" : "mapgen",
    "om_terrain" : ["national_guard_camp_"],
    "method": "json",
    "weight": 250,
    "_Building_Utility": {
        "cell_map": {
            "object_replace": [
                "object",
                "rows"
            ]
        },
        "cell_num": {
            "string_format": {
                "national_guard_camp_%s": [
                    "om_terrain"
                ]
            }
        }
    },
    "object": {
        "fill_ter": "t_floor",
        "rows": [],
        "terrain": {
		 " ": "t_thconc_floor",
            "~": "t_rock",
            "!": "t_metal_floor",
            "#": "t_thconc_floor",
            "%": "t_fence_barbed",       
            "^": ["t_utility_light", "t_utility_light", "t_utility_light", "t_sidewalk"],     
            "|": "t_brick_wall",       
            "-": "t_brick_wall",       
            "+":  ["t_door_c", "t_door_c", "t_door_o", "t_door_locked", "t_door_locked_interior"],
            ",": "t_pavement_y",       
            "_": "t_pavement",       
            ".": ["t_grass", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_grass", "t_dirt", "t_shrub"],            
            ">": "t_stairs_down",       
            "<": "t_stairs_up",       
            "$": "t_radio_tower", 
            "&": "t_gas_pump", 
            "1": ["t_grass", "t_dirt", "t_dirt", "t_dirt", "t_dirt", "t_dirt"],      
            "2": ["t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_dirt", "t_shrub", "t_tree", "t_tree_young", "t_grass", "t_grass", "t_dirt", "t_grass", "t_grass", "t_dirt", "t_shrub", "t_tree", "t_grass", "t_tree_dead"],      
            "3": ["t_grass", "t_dirt", "t_dirt", "t_dirt", "t_dirt"],
            "5": "t_gates_control_brick",
            "6": "t_console_broken",
            "7": "t_machinery_electronic",
            "8": "t_dirtmound",
            "9": "t_door_metal_c",
            "0": "t_manhole_cover",
            "=": "t_door_metal_locked",
            "A": "t_thconc_floor",
            "a": "t_pavement",
            "B": "t_thconc_floor",
            "b": "t_thconc_floor",
            "C": "t_thconc_floor",
            "c": "t_thconc_floor",
            "D": "t_thconc_floor",
            "d": "t_thconc_floor",
            "E": "t_elevator",
            "e": "t_strconc_wall",
            "F": "t_chainfence_v",
            "f": "t_chainfence_h",
            "G": "t_reinforced_glass",
            "g": "t_thconc_floor",
            "H": "t_sidewalk",
            "h": "t_thconc_floor",
            "I": "t_column",
            "i": "t_sidewalk",
            "L": "t_thconc_floor",
            "M": "t_wall_metal",
            "m": "t_wall_metal",
            "O": "t_thconc_floor",
            "o": "t_thconc_floor",
            "Q": "t_dirt",
            "q": "t_thconc_floor",
            "R": "t_thconc_floor",
            "r": "t_thconc_floor",
            "S": "t_thconc_floor",
            "s": "t_sidewalk",
            "T": "t_thconc_floor",
            "t": "t_thconc_floor",
            "u": "t_thconc_floor",
            "V": "t_thconc_floor",
            "v": "t_thconc_floor",
            "W": "t_window",
            "w": ["t_window_domestic", "t_window_domestic", "t_curtains", "t_window_domestic", "t_window_domestic", "t_curtains", "t_window_frame"],
            "Y": "t_dirt",     
            "y": "t_thconc_floor",
            "X": "t_pavement",     
            "Z": "t_dirt",
            "z": "t_dirt"
        },
        "furniture": {
            "#": "f_indoor_plant",
            "A": "f_sofa",
            "a": "f_sandbag_half",
            "B": "f_bed",
            "b": "f_bench",
            "C": "f_cupboard",
            "c": "f_counter",
            "D": "f_fridge",
            "d": "f_desk",
            "g": "f_glass_fridge",
            "H": "f_table",
            "h": "f_chair",
            "i": "f_bench",
            "L": "f_locker",
            "O": ["f_crate_c", "f_crate_c", "f_crate_o"],      
            "o": "f_bookcase",
            "Q": "f_sandbag_half",
            "q": "f_sandbag_half",
            "R": "f_exercise",
            "r": "f_rack",
            "S": "f_sink",
            "T": "f_table",
            "t": "f_toilet",
            "u": "f_shower",
            "V": "f_vending_c",
            "v": "f_oven",
            "Y": "f_rubble",     
            "y": "f_treadmill",
            "X": "f_tank_trap",     
            "Z": "f_ash"
        }
    }
}
`
I can do linting, it just makes it harder for me to maintain since it separates the picture of the map from where I'm adding the information that isn't just repeated.

**Comment by kevingranade** [comment]
Reopening, this shouldn't have been closed in the first place.

**Comment by Zireael07** [comment]
Is this even mergeable, though? Haven't seen @acidia for a long time and it was opened really long ago...

**Comment by kevingranade** [comment]
It's very isolated from the rest of the code, so it is likely mergeable.

**Comment by Leland** [comment]
It's pretty epic. It also either has created or is victim to a very peculiar graphical error on the map:

screen recording 2017-05-31 at 07 28 pm

**Comment by AMurkin** [comment]
JSON format [error](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/Graphics=Curses,Platform=Windows/6491/console) in modinfo.json

**Pull request merged**
