### PR TITLE
option WEARY

### PR DESCRIPTION
**Pull request by lcy03406**
#### Summary

SUMMARY: Balance "Add an game balance option that sets weariness increment multiplier."

#### Purpose of change

Weariness is an experimental functionality and under balancing for now. So an option wound be fine.

#### Describe the solution

Add an game balance option that sets weariness increment multiplier.

#### Describe alternatives you've considered

A bad idea was to add an option to turn weariness off.

### CODE REVIEW

**Comment by Fris0uman** [comment]
If players turn weariness off then we can't balance it, this does the opposite of what we want. Plus weariness can already be turned off by tweeking the external parameter initially set in game_balance.json

**Comment by lcy03406** [comment]
> If players turn weariness off then we can't balance it, this does the opposite of what we want. Plus weariness can already be turned off by tweaking the external parameters initially set in game_balance.json

Weariness will increase by calories and cannot turned off.

**Comment by lcy03406** [comment]
If the unstable branch is too unstable, it only courage players to use the stable version, so we can't balance it, this does the opposite of what we want.

**Comment by Fris0uman** [comment]
Lets take a concrete exemple of a feature that can be turned off. Skill rust can be turned off, the result is that despite having been in for years it's still not balanced (and no one is working on it) because it can be turned off and thus no one plays with it.

**Comment by lcy03406** [comment]
> Lets take a concrete exemple of a feature that can be turned off. Skill rust can be turned off, the result is that despite having been in for years it's still not balanced (and no one is working on it) because it can be turned off and thus no one plays with it.

Partually agree with you. But another reason is  skill rust is not fun. Read books of every skill on every morning is too simple and too tedious. But maybe the reason for it being not fun is it can be turned off and no one maintains it.

And weariness is not fun too. Maybe it will be always not fun if it can be turned off. But I still want to turn it off for now, because it is really not fun. Maybe an external option in game_balance.json would be better, perhaps.

**Review by ZhilkinSerg — CHANGES_REQUESTED** [review]
Astyle your changes.

Also this option should actually be set to true by default and be one of game balance options set through https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/core/game_balance.json.

**Comment by ZhilkinSerg** [comment]
> If the unstable branch is too unstable

This has nothing to do with weariness feature.

**Comment by lcy03406** [comment]
> Astyle your changes.
> 
> Also this option should actually be set to true by default and be one of game balance options set through https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/core/game_balance.json.

Done.

**Comment by anothersimulacrum** [comment]
This is entirely something that can be controlled by the existing external options for the use case of turning it off, and this external option, unlike those, doesn't have any real development use.
Here's the equivalent of setting this option to 0.2 with the existing options. If you want to entirely, disable it, set the BMR mult to 11x, that's a figure that'd be impossible to reach from anything resembling normal activity.
```diff
diff --git a/data/core/game_balance.json b/data/core/game_balance.json
index e57049eb89..7da0dd22e1 100644
--- a/data/core/game_balance.json
+++ b/data/core/game_balance.json
@@ -151,7 +151,7 @@
     "name": "WEARY_BMR_MULT",
     "info": "What portion of BMR is used as the base for determining weariness threshold.",
     "stype": "float",
-    "value": 0.54
+    "value": 1.08
   },
   {
     "type": "EXTERNAL_OPTION",
@@ -172,7 +172,7 @@
     "name": "WEARY_RECOVERY_MULT",
     "info": "What percentage of calorie intake and expenditure is reduced during each reduction tick.",
     "stype": "float",
-    "value": 0.05
+    "value": 0.10
   },
   {
     "type": "EXTERNAL_OPTION",
```

**Comment by lcy03406** [comment]
existing external options can not turn weariness off.  weariness increment is always positive no matter what values you set. so in the long run weariness level will be positive eventually.

**Comment by anothersimulacrum** [comment]
You clearly do not understand how it works if you think that is the case.

**Comment by lcy03406** [comment]
> You clearly do not understand how it works if you think that is the case.

So you think you know the case. Then let me explain it.

weary tracker is calories consumption, so it increases when you do anything, and also when you do nothing, it will increase by bmr.

weariness only decreases when the character is rest. for now, there are some glitches so that rest means completely idle, but that does not matter and will be fixed eventually.

But, bmr will increase weary tracker. So the tracker will increase and decrease while resting. The increament is linar, basically bmr multiplies time. The decreament is exponential, which is very inefficient around zero. So weary tracker will bounce around a certain balance point, which is not zero.

Then we have WEARY_INITIAL_STEP. For now, it can barely cover the resting balance point. So any furture calories consumption will increase weariness level.

You may say I can set WEARY_INITIAL_STEP to very large. It's not important, I wrote these above only to show my knowledge of the code.

But the true problem/functionality is the tracker **only decreases when the character is resting**. No matter what parameter you set, there must be a work/rest ratio required to not become weary. So it cannot be complately disabled by existing options.

Another solution is to add a parameter that modify the activity level counts for resting. But it seems that developers are working to rework that part, so I don't want to propose a pr for that.

**Comment by anothersimulacrum** [comment]
Sorry, my last comment was quite rude and unfair, and it should not have been.

> But the true problem/functionality is the tracker only decreases when the character is resting. No matter what parameter you set, there must be a work/rest ratio required to not become weary. So it cannot be complately disabled by existing options.

Okay, yes, technically you can never make it is so it is _impossible_ to become weary, but you can quite easily make it so than there is no scenario that is not incredibly, incredibly, contrived under which you will gain the first level of weariness. 
If you set the initial step to say, 40, and the recovery to 100%, you have to consume 40x your BMR, equivalent to _4 consecutive days of EXTRA_EXERCISE_ without having a consecutive 30 minutes of rest or 15 minutes of sleep. I would be beyond shocked if someone managed this feat without knowingly attempting it, because it is somewhat hard to do even if you _are_ knowingly attempting it.

**Pull request closed without merging**
