### PR TITLE
Zombie sounds

### PR DESCRIPTION
**Pull request by bloodbowel**
#### Summary
Features "Zombies make zombie sounds"

#### Purpose of change
The game seems to describe zombies as making sounds in a few instances but zombies are totally quiet. Zombies now make their iconic moaning noises and similar sounds.

#### Describe the solution
Adds extra ambiance at night when walking around in the dark. You might hear zombies at night which can help you avoid them. When they see you they make more noise and alert nearby zombies, though not as effectively as the yelling zombies.

#### Describe alternatives you've considered
Quiet zombies. Or perhaps this as a mod. There might be a better way to do this other than using the parrot attack. I sifted through the various zombies and tried to find what sounds would be most appropriate. Most zombies make noise. Hulks and some others make no sound at all. Boomers and acidic zombies gurgle and skeletons hiss. Didn't check the lore on this one but it's pretty neat to play with.

#### Testing
Tested on my computer in debug mode.

#### Additional context
sounds

### CODE REVIEW

**Comment by SirPendrak** [comment]
Skeletal reapers have no mouth. Skeletal executioners have non-functional mouth, but it might be functional enough to make sounds.

Does it work in situation when zombie uses copy-from basic zombie, but has its own special attacks defined, without using "extend"? In theory it should overwrite basic zombie's special attacks, and it wont have "parrot" this way.

**Comment by bloodbowel** [comment]
It's not the mouth that makes noise but the throat. Though yeah the executioner would be silent since there would be no way for air to move. I was initially thinking of not having the skeletons make any noise but might still make a hissing noise from air traveling through their throat. I'm not sure exactly how zombies breathe. I guess through the goo, but their voice box might still be used for vocalizations as with yelling zombies. You're right about the overwritten special attacks. I would have to go through and manually add the parrot attacks to each zombie with specials overwritten. Might do that tomorrow.

**Comment by Entity-y** [comment]
Can't wait to hear a cacophony of 1000 zombie noises trigger all at once from passing time after sound packs add the sound effects for zombies.

**Review by RenechCDDA — COMMENTED** [review]
I think this is a fine idea. I have some minor nitpicky points, but this shouldn't be construed as rejecting the PR or disapproving.

1) The `speaker` list is enormously long, maybe we could do some C++ so it accepts arguments other than monster IDs. e.g. so you could input `"species": "ZOMBIE"` and anything with the ZOMBIE species would be valid. Or maybe do it by monfaction, etc. Anything to reduce that huge wall of entries and make it more maintainable.

2) The volumes seem a bit high, ranging from 5 (perfectly fine) to 20(!). A 20-volume sound can nominally be heard from 20 tiles away, weather conditions permitting. That's pretty far, maybe too far. Tweaking the number is easy though, so this isn't a big deal. (I also don't know what it *should* be.)

**Comment by RenechCDDA** [comment]
Also I was concerned that `PARROT_AT_DANGER` might trigger the mi-go voicelines or something weird, but mostly it just means they make a lot *more* sounds when they see a target.

image

> Can't wait to hear a cacophony of 1000 zombie noises trigger all at once from passing time after sound packs add the sound effects for zombies.
> 
> Also for hulk zombies you could do something like "you feel the ground tremble".

The 400-turn cooldown on `PARROT` makes this incredibly infrequent, it should not be an issue. Plus this doesn't hook up any new *played* sounds, so doubly not an issue.

**Comment by bloodbowel** [comment]
> I think this is a fine idea. I have some minor nitpicky points, but this shouldn't be construed as rejecting the PR or disapproving.
> 
> 1. The `speaker` list is enormously long, maybe we could do some C++ so it accepts arguments other than monster IDs. e.g. so you could input `"species": "ZOMBIE"` and anything with the ZOMBIE species would be valid. Or maybe do it by monfaction, etc. Anything to reduce that huge wall of entries and make it more maintainable.
> 2. The volumes seem a bit high, ranging from 5 (perfectly fine) to 20(!). A 20-volume sound can nominally be heard from 20 tiles away, weather conditions permitting. That's pretty far, maybe too far. Tweaking the number is easy though, so this isn't a big deal. (I also don't know what it _should_ be.)

1. As it is now there are four groups regarding sound:
*Zombies that make any zombie sound except hissing (Most zombies)
*Zombies that only gurgle (Acidic, Boomer, and headless zombies)
*Zombies that only hiss (Skeletons except reapers)
*Zombies that make no sounds (Hulks, children, and some others)
If you use "species":"zombie" you can exclude zombies from making any sounds by not including a parrot in their special attacks. There are thirteen gurgling zombies and four hissing zombies. So that should work without losing any information. The gurgling list would still be 14 lines long though.
2. I thought you should be able to hear them moan from across the street. 20 tiles is 2 or 3 tiles further than the width of a road. A mi-go coughs and growls at 20 for comparison, though it might amplify it's voice.

> The 400-turn cooldown on `PARROT` makes this incredibly infrequent, it should not be an issue. Plus this doesn't hook up any new _played_ sounds, so doubly not an issue.

The parrot might be too low and the parrot at danger might be too high. How about 10 for danger and 200 for parrot? I don't really know what is ideal here. I should get a good number before I go and add parrots to zombies that overwrite the classic zombie special attacks.

**Comment by sadenar** [comment]
The skeletons hissing in my mind is a lot less cool and logical than them having chafing sounds between you know, the bone plates they all have and would probably create sufficient noise that while not being insanely noisy is more than "silent shuffle with asthma attack hisses"

**Comment by RenechCDDA** [comment]
Are you holding this in draft for a specific reason? It looks good to undraft it.

The test failure *is* related to your changes, but looks like it should be simple to resolve. I'm going to ask some of the other devs about how we want to resolve that - it shouldn't need any changes on your part unless you would like to.

**Comment by bloodbowel** [comment]
There is one I need to fix. A lot of zombies don't make sounds, that should, because their special attacks overwrite the special attacks of the generic zombie. I need to add the parrot attacks to those for this to be complete. I've been dragging my feet to get it done. I didn't want you to merge it with a bug. Though I guess it could be fixed in a later pull request if you want to merge this as is. I'm new to github and still figuring things out.

**Comment by RenechCDDA** [comment]
Those monsters should be using `extend` and `delete` syntax if they aren't already, you don't have to handle that in this PR.

**Comment by bloodbowel** [comment]
In that case it should be ready.

**Comment by SirPendrak** [comment]
I was wondering, since zombies are atraccted to noises, wont this make other zombies attracted to thier mumbling friends? Or maybe even, attracted to their own noises?

**Comment by ADekema** [comment]
I like the idea very much. But why limit it to normal zombie noises like moans? You could easely make some horror by making the zombies make stragely human noises. Think a distorted cry, something that almost sounds like a word but isn´t. Think walking into a school and hearing muffled cries coming from the classroom and hearing ¨Mabaaaaaa... Heeeeee...¨ around the corner. Only to encounter dead children.

**Comment by RenechCDDA** [comment]
You need one more master merge and then it should be passing basic build, #75716's merge should resolve the test failures.

**Comment by GuardianDll** [comment]
Please do not update the branch every day, mergers can't merge it because it reruns all the tests

**Comment by bloodbowel** [comment]
Thanks for telling me. I thought I had to do it to keep with the current updates.

**Comment by GuardianDll** [comment]
only if it says there is a branch conflict, which happens only when multiple people work in the same file at once

**Pull request merged**
