### PR TITLE
[CR] More gear now can be worn with power armor

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Don't know why there are two checks for head gear. Left them as is for now.

### CODE REVIEW

**Comment by illi-kun** [comment]
I see no reason of keeping double entry of ```!to_wear.covers(bp_head)``` -- it's a typo.

**Comment by Night-Pryanik** [comment]
Decided to add some more gear that can be worn with power armor in this PR.

**Comment by Coolthulhu** [comment]
Does this handle both checks?
As in, the check for putting on mouthgear while in PA and the check for putting on PA with mouthgear on.
It can be more restrictive than necessary, but shouldn't allow bypassing the check by doing it in different order.

**Comment by John-Candlebury** [comment]
I'm pretty sure that the fact that you cannot wear stuff like backpacks with PA was supposed to be its balancing point. 

Although I'm not sure.

**Comment by Night-Pryanik** [comment]
@John-Candlebury there is comment in player.cpp, line 10660 "// are we trying to wear something over power armor? We can't have that, unless it's a backpack, or similar."
So I suppose that possibility to wear at least backpack was planned initially. Unfortunately, it didn't work.

**Comment by Night-Pryanik** [comment]
@Coolthulhu tested now: mouthgear can be worn either before or after PA without problems.

**Comment by Coolthulhu** [comment]
Power armor shouldn't allow wearing hoodies and trenchcoats. Only OVERSIZE items should be wearable over power armor.

**Comment by kevingranade** [comment]
Strap-on and oversize items also do not get a pass, it's not a matter of them fitting, it's a matter of you being able to put them on while wearing power armor.  Something that can be worn absurdly easily like a poncho, sure, something you have to thread your arms into and/or cinch up, nope.

**Comment by kevingranade** [comment]
@Night-Pryanik the comment you're citing is erroneous, power armor was never intended to work with backpacks.

**Comment by Zireael07** [comment]
@kevingranade, what is the CDDA power armor supposed to look like? Modern exoskeletons (for factory workers/disabled) go over everything, so I suppose anything except very bulky items would be fair game (the other way than you guys are showing in this discussion)

**Comment by Night-Pryanik** [comment]
@Zireael07 As their description states, it has internal climate control (and IIRC it is imprevious to radiation), and all of this is impossible without full and solid body suit.

**Comment by kevingranade** [comment]
The concept is a very tight-fitting but bulky suit that is driven by capacitive contact pads (it detects when you contract various muscles and moves to match), which means you can't wear anything under it.

In practice this change is going to allow a large number of items that we don't want worn with power armor, such as a survivor vest, utility vest, fanny pack, dump pouches.

Maybe it is clearer if I state that this isn't intended to be treated as clothing, it's more like a vehicle you wear.

**Comment by Soadreqm** [comment]
Wearing a poncho over a climate-controlled metal carapace that covers your entire body sounds a bit absurd, though admittedly very stylish.
If backpacks are out for "realism" reasons, what about messenger packs, duffel bags, strapped guns and other things you sling over a shoulder? I think fanny packs and other belt items sound like fair game, too. If the oversized pauldrons prevent you from touching your hands together behind your back, you could lay it flat on a table or something and pick its ends up.

**Comment by kevingranade** [comment]
Merged the mouthpiece change, if you want to push for the other extensions you can reopen the PR, but just FYI I'm not going to accept simply allowing more items to be worn over power armor.
To have a chance of merging it would have to be much more restrictive than "waist flag", and power armor would be getting a hefty nerf to armor values.  The entire concept for balancing it is you're nearly invulnerable, but limited in your ability to do anything but fight, if the second part is changing, the "nearly invulnerable" part would be too.

**Comment by Night-Pryanik** [comment]
I don't think that wearing a belt is a damn hard task to perform even in PA. And imho it's not harder than swinging some club to smash zombie's head. Not to mention crafting and constructing in PA.

**Comment by Soadreqm** [comment]
I think power armor is more balanced by rarity. Finding one is rare as hell, and although keeping it powered isn't too hard once you've reached the endgame, it's still resource-intensive enough that if you get that one-in-a-million suit lying around just outside your starting shelter, you can't really make use of it until later. The lack of inventory space is annoying, but nothing you can't solve with a shopping cart. Especially since you can now use most items from an adjacent shopping cart.
I think a better approach would be to give power armor wearers a hefty time penalty for using their inventories.

**Pull request closed without merging**
