### PR TITLE
No cost to turn off

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
It was pointed out to me that some items cost a charge of energy to turn off in addition to the turn on cost.  So I went and looked. Changed almost all the ones I found and found a couple items with Turn off as their Turn on message so I changed them.

#### Describe the solution
"ammo_scale": 0,

#### Describe alternatives you've considered
I'll leave this up for a bit for people to review if they believe certain items should have a power down cost.

### CODE REVIEW

**Comment by RedMisao** [comment]
This is adressing #75632 (?). If that's the case, it should close it after merging.

**Comment by Maleclypse** [comment]
> This is adressing #75632 (?). If that's the case, it should close it after merging.

No it's not addressing that.  Devices should take a charge when turned on to prevent the PC from making the game miserable by turning things on and off in the same second just to see where monsters are without the monsters seeing you.

**Comment by RedMisao** [comment]
My bad, I misread the title of the issue.

**Comment by MikasaTanikawa** [comment]
> Devices should take a charge when turned on to prevent the PC from making the game miserable by turning things on and off in the same second just to see where monsters are without the monsters seeing you.

But this already covered by lit up status effect. It sticks to PC at least for one second.

**Pull request merged**
