### PR TITLE
tools: compose.py updates

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Build "tools: compose.py updates"```

#### Purpose of change
Fix some issues with compose.py.

My pyvips version doesn't have hasalpha(), so fail gracefully when that function isn't available.

i-am-erk wanted to be able to throw in a directory of fallback images and metadata and not have to worry about conflicts as he added better images in his primary directory.  Add support for declaring one or more tilesheets as "filler" sheets.  Images and `tile_entry.json` metadata from a filler tilesheet are not composed or added to `tile_config.json` if the tile id exists in a non-filler directory.

#### Describe the solution
Wrap hasalpha() in a try.

Rework the logic of compose.py a bit.  Read all the non-filler, non-fallback directories first, then all the filler directories, then the fallback directory.  When converting a tile_entry, check if the entry came from a filler directory and if it did, check if the item's ids have already been covered by some other entry.  If so, don't convert the entry.

#### Testing
I tested this briefly on the UndeadPeopleTileset and confirmed that an entry for `mon_null` from the filer directory got added to `tile_config.json`, but a duplicated entry for `t_wall_glass_alarm` did not.
I also duplicated the entries and files for `t_wall_metal`, both unmodified and as `t_scrap_wall`; the entries for t_wall_metal did not get duplicated but the entries for t_scrap_wall got added from filter.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Ah, the docs should say that things from filler will be skipped if they're satisfied by a non-filler id or a previous filler id.  So the skipping "overlay_wielded_cs_lajatang_off" messages are the right behavior, just a little confusing.  I've updated the docs, thanks.

Additional tiles are now getting properly prefixed, so duplicates shouldn't be an issue if I did it right.  Thanks for the testing and review.

**Comment by ralreegorganon** [comment]
Ok, I think that addressed some of the issues, and the tileset composed of Ultica and SDG does load in the game now, but I think that skipping the duplicates within the fallback rather than allowing them to overwrite (or whatever the behavior was before for a non-fallback) is causing some issues when it comes to indexing into the sprites. For example, `fd_fire_vent` shows up only in the fallback, but in both of these files:

```
pngs_sdg_normal_32x32\FIELD\17876_fd_fire_vent_0.json
pngs_sdg_normal_32x32\FIELD\17860_fd_fire_0.json
```

Here's a screenshot using the Ultica tileset with an SDG fallback:
image

In this, all of the stuff from Ultica renders correctly, and it renders "something" for others, but the something is clearly wrong. The two shotguns above my character are what it's chosen to use for the line drawing, and the naked person is the targeted location highlight.

The tile_info.json I'm using for this looks like this:

```
[
  {
    "pixelscale": 1,
    "width": 32,
    "height": 32
  },
  {
    "normal.png": {  }
  },
  {
    "tall.png": { "sprite_width": 32, "sprite_height": 64, "sprite_offset_y": -32 }
  },
  {
    "large.png": { "sprite_width": 64, "sprite_height": 64, "sprite_offset_x": -16, "sprite_offset_y": -32 }
  },
  {
    "huge.png": { "sprite_width": 64, "sprite_height": 96, "sprite_offset_x": -16, "sprite_offset_y": -64  }
  },
  {
    "sdg_normal.png": {
      "filler": true
    }
  },
  
  {
    "fallback.png": {
      "source": "https://github.com/Chezzo/Cataclysm-DDA/blob/0ca0b5307f1b2fab7edb5519a3176e1d887087a7/gfx/ChestHole32Tileset/fallback.png",
      "fallback": true
    }
  }
]
```

And the folder I'm composing is this https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/Ultimate_Cataclysm/gfx/UltimateCataclysm plus this folder https://github.com/mlangsdorf/Cataclysm-DDA/tree/5780bf8dd966e2b39f3a6ea855879cba0b91f642/gfx/UndeadPeopleTileset/pngs_normal_32x32 dropped into the same and renamed to pngs_sdg_normal_32x32.

**Comment by mlangsdorf** [comment]
filler, not fallback.
fallback is the emergency ASCII symbols.
filler are sprites that are only used if the main set doesn't define them.
I think there's an indexing bug; I'll look into it tomorrow.

**Comment by mlangsdorf** [comment]
I fixed the off-by one issue, but the index numbers for the filler sheet are crazy.  Seems to be working in my brief tests but more testing is needed.

**Comment by ralreegorganon** [comment]
I think this looks good to merge after the latest set of changes. The scripts are doing what I'd expect, and from there it's just content issues. Nice work! 👍

**Pull request merged**
