### PR TITLE
Harvest items to inventory

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary

```SUMMARY: Interface "harvested items go directly to the inventory instead of being dropped on ground."```  

#### Purpose of change
Currently when you harvest a plant the harvested items are placed on ground.  This adds annoying extra step of picking them up.

Now the harvested items are placed in your inventory instead. If the inventory is full then the items drop on ground.

#### Additional context
Applies only to poppy bud, dahlia roots and plants that use "harvest_common" function (berries, fruits, trees) and spider eggs (if baby spiders spawn then spider eggs are droped on ground).

Bush foraging has too varied drops so they are not changed (drop on ground).
Farmed plants give many different kind of items at once so they are not changed (drop on ground, gives pickup dialog).

### CODE REVIEW

**Comment by Hirmuolio** [comment]
As I look at the farmed plant harvesting I notice that there are currently two different ways to drop the harvest. If anyone has strong opinions on which is best now is the time.

1) Drop harvested items on player feets (currently wild plants, bushes do this).
2) Drop harvested items on the plant location and open the pickup menu automaticlly (currently farmed plants do this)
3) Place harvested items in player inventory (new).

For plants that will give only one kind of things it is obvious that 3 is the way to go (berry bushes/fruit trees/etc.).

Bushes can drop all kind of good items and trash items. Would it be better to automatically open the pickup dialog after foraging or to put the items in inventory automatically?

Farmed plants drop many different items at once (vegetable+seed+byproducts (withered plant) ). Keep the current system where the pickup dialog automatically opens or should the items go to inventory?

**Comment by SirPendrak** [comment]
I would go with option 2 for everything.

**Comment by Hirmuolio** [comment]
Well I tried to implement 2 for foraging bushes and it doesn't work.

Something about being an acitivity stops it from working. And it would probably be a bad idea to make foraging not an activity as it takes several minutes to forage a bush.

**Comment by Hirmuolio** [comment]
Flowers, trees and bushes are in my opinion consistent enough with their items that if you are harvesting them then just taking all items is the best option.

Bushes have so diverse item variety that automatically taking everything is not good. Option 2 doesn't work (at least I couldn't get it working) so I will jsut leave them as they are.

Farmed plants will be left as they are.

Spider eggs are automatically put in inventory only if no spiders spawn. If spiders spawn then the eggs are left on ground.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
There is a `i_add_or_drop` function which could replace the bulky checks you added.

**Comment by Hirmuolio** [comment]
`i_add_or_drop ` wouldn't allow different messages for "harvest" and "harvest and drop".

**Comment by MetroidHunter** [comment]
I suggest refactoring some of the logical duplication into functions. The two spider eggs and poppy seeds really only differ by strings. The portion around `i_add` could also be a small function as well to reduce duplication further in the file and with the aforementioned blocks

**Comment by Xhuis** [comment]
harvestitems

Might I recommend putting this on dandelions, too? Dandelion greens are a great vegetable for broth.

**Pull request closed without merging**
