### PR TITLE
Fix fouling on non-gunpowder ranged weapons

### LINKED ISSUE #35290: CRIT Expansion Mod: Energy Weapons foul despite not using any kind propellant other than Lorentz Force for plasma weapons..
# Describe the bug

Using the CRIT mod, I found myself an Energy Rifle which is just a more powerful laser rifle. After firing a couple dozent bursts with it the gun got the fouling tag in its description. I am pretty sure energy weapons would not suffer through fouling. Worse of all. Cleaning it via pipe cleaner or gun repair kits is impossible. Other weapons affected are: The plasmacutter, any of the other energy weapons from CRIT and PK Rebalance BFG. All of which are beam weapons or plasma weapons. All of which should not suffer from fouling. The base game vanilla weapons are affected aswell after a quick test with a debug character.

# Steps To Reproduce

1. Go in with a character.
2. Acquire one of the CRIT mods weapons.
3. Acquire UPS and energy source
4. Fire said gun a couple dozent times into a horde of zombies.
5. Behold, you got a fouling tag on your energy weapon, THIS INCLUDES VANILLA/NONE MODDED ENERGY WEAPONS
6. Attempt to use: Gunsmith Repair Kit, Firearm Repair Kit, Pipe Cleaner: "You don't have anything to use this on" or "You cannot repair your weapon."

# Expected behavior

Energy weapons should not foul due to "blackpowder" being used since there is no propellant. Sure they should have some other mechanic making them require maintenance of some sort, e.g. having to swap out the capacitors every so often. But fouling should not affect those guns. Atleast they should be cleanable. Which they are not. Pipe cleaner is not doing anything nor are both of the gun repair kits.

# Screenshots

https://media.discordapp.net/attachments/585919978251747343/640634112012451841/This_should_not_rot.jpg?width=252&height=657

Proof of Vanilla Energy weapons being affected. Same Build, same mods loaded:

https://imgur.com/a/8NJP6UK

# Versions and configuration

 - OS: Win 7
 - Game Version: Current Build: 9855
 - Graphics version: Tiles, Dead People 
 - Mods loaded: PK Rebalance, CRIT Expansion, Aftershock, Magiclysm, Arcana

# Additional context:

Vanilla energy weapons ARE in fact affected aswell. The mods loaded should not affect the vanilla energy weapons. Hence I assume that one flag for "no fouling" was not properly applied to the energy weapons.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Add NON-FOULING flag to non-gunpowder ranged weapons"```

#### Purpose of change
Fixes #35290. 

#### Describe the solution
Add NON-FOULING to all non-gunpowder turrets & ranged weapons(items such as crossbows/bows/nailgun/slings don't foul already). 

#### Describe alternatives you've considered
None.

#### Testing
Loaded world with all mods affected active, shot each & marked it for flagging. Re-tested after adding flag & got no fouling.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Is it `NON-FOULING` or `NON_FOULING`?

**Comment by LaVeyanFiend** [comment]
``NON-FOULING``, see #34503

**Comment by EldritchSigma** [comment]
Thank you so much!

**Comment by Soupster89** [comment]
Awesome!

**Pull request merged**
