### PR TITLE
Hide negligable armor info

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Interface "Hide irrelevant data about armor from the player"

#### Purpose of change
Something I've wanted to do for a while. New more organized format from #53816 makes it really easy to do. Armor info entries that are redundant or very near 0 are now no longer displayed. Helps to de-clutter the UI and removes a lot of parsing of "useless" info. If a player has on something that only provides acid resistance they shouldn't need to parse 5 entries worth of data to see that.
 

#### Describe the solution

- Any protection values less than 1 are not displayed
- If all protection values are less than 1 instead "Negligible Protection" is displayed
- If melee or ranged coverage are equivalent to default coverage they are hidden
- If vitals coverage is 0 it is hidden
- Update UI tests for the new info lists

#### Testing
Check out some items in game. 

#### Additional context
Some items in game:
Really simple clothing
image

More complicated clothing
image

High protection simple coverage
image

Very complex armor
image

### CODE REVIEW

**Comment by dseguin** [comment]
Hey, thanks for cleaning this up. It looks so much better!

**Comment by bombasticSlacks** [comment]
I've wanted to do this for ages but when they were in a comma separated list removing chunks means things wont be where people expected them. Now that you've organized everything as a separate row I think it avoids any confusion.

**Comment by Inglonias** [comment]
Does this hide protection values for armor that is damaged, but would otherwise provide more than 1.0 protection?

**Comment by bombasticSlacks** [comment]
It checks based on current state yeah. Once it's repaired they would be displayed again.

**Pull request merged**
