### PR TITLE
Update and fix kevlar chainmail armor, hauberk, missing recipes, errors and inconsistencies

### PR DESCRIPTION
**Pull request by PlutusPleion**
#### Summary
Balance "Update chainmail gear and kevlar-chainmail variants' materials including numerous fixes"

#### Purpose of change

Kevlar Chainmail Armor is made by combining components of:

 
It's safe to assume there should be overlap. There are also minor differences like the gambeson and arming pants being 100% coverage while the chainmail gear being 95% coverage.

We have systems in place to allow for complex armor such as this.

Another problem that was found is that the kevlar chainmail armor had stats that would assume it incorporated a kevlar gambeson hood, except it was not part of the recipe.

#### Describe the solution

Here should be the totals for each bodypart:

head:
95% coverage (1.2 Steel)
100% coverage (1.9 Layered Kevlar, 1.3 Kevlar, 2.5 Cotton*)

torso, arms, legs:

95% coverage (1.2 Steel)
100% coverage (1.9 Layered Kevlar, 1.3 Kevlar, 2.5 Cotton*)
 

- updated material and coverage for all chainmail armor and variants
- *moved cotton to 100% just for simpler end display of stats and since cotton is only 1 resistance shouldn't affect the end result too much
- updated weight,volume, and prices
- increased warmth and encumbrance slightly (we are pretty much layering them on top of eachother)
- Added kevlar gambeson hood to recipe
- updated materials to use low_steel as per armor/material overhaul
- various fixes for typos, recipes not showing up
- normalized "Activity_level" across recipes
- updated xs/xl versions to use "extend" instead of manually setting it so that it's easier to update in the future

#### Testing

-Checked each recipe is correct and shows up
-Checked the materials are correct
-Checked resistances and coverage are correct
-No errors on load

### CODE REVIEW

**Comment by PlutusPleion** [comment]
A lot to do still, wanted to make one small change and there's been new bugs found:

1. The two recipes for kevlar chainmail suit aren't showing up (fixed)
2. The XS versions of the kevlar gambeson hood and arming pants don't exist
3. Allow XS/XL versions to be used to craft XS/XL product respectively

**Comment by Drew4484** [comment]
Overall this looks good, the 100% coverage for the soft layers and the 95% for the chain is in line with other chainmail.

It looks like you've got XS components in recipes for normal sized gear. These should be separate and incompatible between XS/normal/XL.

The steel thickness should be consistent across the entire body, I've used 1 mm on the plate mail and gloves.


I haven't applied new steels to chainmail yet but if you wanted to update these to use the grades you can swap those materials in without worrying about weight or volume.

**Comment by PlutusPleion** [comment]
> Overall this looks good, the 100% coverage for the soft layers and the 95% for the chain is in line with other chainmail.
> 
> It looks like you've got XS components in recipes for normal sized gear. These should be separate and incompatible between XS/normal/XL.
> 
> The steel thickness should be consistent across the entire body, I've used 1 mm on the plate mail and gloves.
> 
> I haven't applied new steels to chainmail yet but if you wanted to update these to use the grades you can swap those materials in without worrying about weight or volume.

Did final check each piece should now only allow similar size for crafting. The exception of allowing normal size to craft for XS as well. I figure resizing normal to xs should be okay. I can remove it if that's not desired.

Which grades should be used for chainmail? I'm not too familiar in metallurgy.

**Comment by Jarewill** [comment]
I can close #55222 however there are still some recipe inconsistencies in this PR.
Namely some recipes are still missing an id_suffix, preventing them from showing up and chainmail armors still require an additional gambeson.
Chainmail hauberks are crafted from chainmail and gambesons, so it makes no sense that the chainmail armors require both hauberks and additional gambesons.
Those recipes should be fixed to only need a hauberk and chainmail/gambeson hoods.

**Comment by PlutusPleion** [comment]
Removed duplicate and gambeson for normal chainmail armor. Kept requiring kevlar gambeson for kevlar chainmail armor because it requires the kevlar aspect as opposed to cotton in normal gambesons.

**Comment by Drew4484** [comment]
1.2 mm is a good number, we can establish that consistent across all chain armor. Because of the way armoring works, if we go for the upper boundary of 2 mm it will be as effective as solid plate steel.

As far as the steel grades, all are suitable as a material. The progression of mild/medium/high/hardened/tempered is effectively linear in terms of protective values and also crafting difficulty.

I would recommend using the mild steel for your initial suit, and then we can copy-from variants for the other grades of steel.

**Comment by PlutusPleion** [comment]
Updated chainmail coif, armor, hauberk, vest, legging and sleeves. All using low_steel and uniform thickness for the steel.

**Comment by PlutusPleion** [comment]
accidentally closed

**Comment by PlutusPleion** [comment]
More encompassing changes in #55455

**Pull request closed without merging**
