### PR TITLE
Robots could "bleed" grease when hit

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Content "Robots could 'bleed' grease when hit."

#### Purpose of change
Add something plausible that can happen to robots when they get hit.

#### Describe the solution
- Added separate `grease_dripping` effect that only robot monsters could get when hit.
- Robots with this effect will "bleed" with newly added `fd_grease` field type. Unlike most other (natural) monsters, they won't get damaged on bleeding.
- Both player and monsters have a small chance to slip and fall down when stepping on a `fd_grease` field.

#### Describe alternatives you've considered
None.

#### Testing
Spawned riot control bot. Hit it with my character's katana so it began dripping grease. Stepped on grease puddles several times and eventually slipped and fell down.
Just in case hit an NPC to test if they still bleed blood, as intended.

#### Additional context
изображение

### CODE REVIEW

**Comment by Shodan14** [comment]
What about hydraulic fluid instead?

**Comment by Night-Pryanik** [comment]
> What about hydraulic fluid instead?

Hydraulic fluid was my first intention, and robots indeed were bleeding it in the first variant. But I thought that there could be robots whose mechanics weren't based on hydraulics. At the same moment I think it's hard to find a robot without any sort of grease in it's intestines.

**Comment by slimeboy460** [comment]
Pretty basic idea, but what about coolant? Most robots would probably get warm regardless of their hydraulic or electronic build.

**Comment by Night-Pryanik** [comment]
The whole thing is mostly fluff stuff, not something with serious gameplay impact. We could as well simply name it like "robot blood" and call it a day.

**Comment by Shodan14** [comment]
> 
> 
> > What about hydraulic fluid instead?
> 
> Hydraulic fluid was my first intention, and robots indeed were bleeding it in the first variant. But I thought that there could be robots whose mechanics weren't based on hydraulics. At the same moment I think it's hard to find a robot without any sort of grease in it's intestines.

Hydraulic fluid apparently includes a number of things from mineral oil to various mixes. I think that robots bleeding grease is a bit cliche. I guess another alternative would be some generic "mechanical fluid" or whatever. I think making it slippery make for fun gameplay, so that's good.

**Comment by Night-Pryanik** [comment]
"Mechanical fluid" was also one of the variants I considered. I'm not attached to the "grease" variant, I can switch to any other one.

**Comment by Shodan14** [comment]
> 
> 
> "Mechanical fluid" was also one of the variants I considered. I'm not attached to the "grease" variant, I can switch to any other one.

That might actually also be good to cover any more mysterious future tech stuff.

**Comment by Fris0uman** [comment]
Isn't slipping on grease a bit of a silly trope?

**Comment by FuelType-Memes** [comment]
> 
> 
> Isn't slipping on grease a bit of a silly trope?

Doesn't make sense on porous surfaces. Might slip on tiles covered in grease, not so much for sand/dirt/concrete

**Comment by Night-Pryanik** [comment]
> Would be good to make sure the description mentions that it's slippery, as it's less obvious than with grease.

Field types doesn't have extended descriptions.

**Comment by Shodan14** [comment]
> 
> 
> Isn't slipping on grease a bit of a silly trope?

Have you ever stepped on grease though? It will make you fall pretty easily. Some surfaces notwithstanding, as mentioned above.

**Comment by Night-Pryanik** [comment]
We don't have absorbtion mechanics for liquid fields implemented yet. Neither blood, acid, slime nor any other liquid fields don't get absorbed by porous terrains and act similarly both on the sand and on the floor.

**Pull request merged**
