### PR TITLE
 Remove "knows_spell" assertion before consuming energy

### LINKED ISSUE #33162: USE_PLAYER_ENERGY flag of spell-casting items cannot work well
# Describe the bug

In my own mod I decided to write a spell-casting crystal which will cost the player's hp to throw a fireball. However, after I added the flag "USE_PLAYER_ENERGY" without which casting would cost absolutely nothing, a debugmsg broke out and told me "owner of spell does not know spell". Mages don't need to know a spell in a magic crystal when they activate it, do they? Maybe the judgment about whether the players know the spells should be moved to the timing when they try to cast them, not when they have casted it and try to cost the energy they need.

# Steps To Reproduce

1. Write an item with the use_action of cast_spell and the flag of USE_PLAYER_ENERGY.
2. Make a player with this item.
3. Try to activate this item and cast that spell.
3. The debugmsg appears.

# Expected behavior

Rewrite the function "can_cast()" in the src file magic.cpp.
Remove the judgment about whether the player knows the spell.
Ideally move this judgment to wherever it should be.(but not here!)

# Screenshots

**If applicable**, add screenshots to help explain your problem.
image
~(W%K_B7WYSLEB%ZD~UP(F8
R5}`JWXDAB9V1$JK8T60 GF

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

### PR DESCRIPTION
**Pull request by RedShakespeare**
#### Summary

SUMMARY: Bugfixes “Remove knows_spell assertion before consuming energy”
#### Purpose of change

Fixes #33162 
Players don't need to know a spell packaged in USE_PLAYER_ENERGY spell-casting items when they try to use them. (Like magic wands in dnd rule)
#### Describe the solution

Delete the "knows_spell" assertion and debugmsg in can_cast() function  in src/magic.cpp.

### CODE REVIEW

**Comment by KorGgenT** [comment]
your summary is incorrect. you need the summary line in quotes after the category.
Otherwise, it looks fine. I must have just been paranoid when i added that assertion in the first place, because i don't see how it would cause issues in the other instances can_cast is called

**Comment by RedShakespeare** [comment]
> your summary is incorrect. you need the summary line in quotes after the category.
> Otherwise, it looks fine. I must have just been paranoid when i added that assertion in the first place, because i don't see how it would cause issues in the other instances can_cast is called

Thx a lot！
Besides, will it be fine if I replace the summary to Summay:Bugfixes "Remove 'knows_spell assertion before consuming energy"?

**Comment by KorGgenT** [comment]
```
SUMMARY: Bugfixes "Remove knows_spell assertion before consuming energy"
```
should be fine.

**Comment by RedShakespeare** [comment]
> ```
> SUMMARY: Bugfixes "Remove knows_spell assertion before consuming energy"
> ```
> 
> should be fine.

thx & changes completed。
may i ask when this pull req will be committed? can't wait to continue writing my new mod.lol

**Comment by KorGgenT** [comment]
jenkins rebuild

**Pull request merged**
