### PR TITLE
Adds bow stabilizer.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Also adds an accessory slot to bows in order to utilize it.

Spawns: homeguns, camping, allsporting.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Shit yes. +1 Rivet!

**Comment by kevingranade** [comment]
Is there anything keeping this from being mounted on pistols, or pistol accessories being mounted on a bow?

**Comment by DavidKeaton** [comment]
If not, my next glock is shooting stabilizers, and tears of joy will stream down my face

**Comment by Rivet-the-Zombie** [comment]
>Is there anything keeping this from being mounted on pistols, or pistol accessories being mounted on a bow?

The sort of counterweights you attach to a handgun are shaped and attached quite differently from the ones that go on bows.

**Comment by kevingranade** [comment]
Cool, "mod_targets" : ["bow"] is just what I was looking for, though I didn't remember the details.

**Pull request merged**
