### PR TITLE
Auditing portable charcoal kiln

### LINKED ISSUE #76658: Tool check: charcoal kiln
### Describe the bug

charcoal kiln https://cdda-guide.nornagon.net/item/char_kiln

https://github.com/CleverRaven/Cataclysm-DDA/blob/a4182b76a76b42881316c331517dbcd56606eba6/data/json/items/tool/metalworking.json#L122

More specifically, the recipe for making filled charcoal kiln.
https://github.com/CleverRaven/Cataclysm-DDA/blob/a4182b76a76b42881316c331517dbcd56606eba6/data/json/recipes/recipe_others.json#L1579

After the material is finished burning, we will have 10 000 charcoal. (This amount of charcoal takes up 50 liters of volume)

The following materials can be used to fill a charcoal kiln:

| Components | Number | Volume (L) | Quantity of charcoal per unit of material | Ratio of the volume of charcoal produced to the volume of material used |
|--------|:-----:|:-----:|:-----:|:-----:|
| splintered wood | 40| 6 | 250 | ~8.3 |
| plank | 6 | 14.64 | ~1 666.7 | ~3,4 |
| stick | 8 | 12 | 1 250 | ~4,2 |
| bone (any) | 40 | 11.60 | 250 | ~4.3 |
| bone skewer | 1000 | 10 | 10 | 5 | 
| pine bough| 20 | 10 | 500| 5 | 
| log| 1 | 50 | 10 000 | 1 | 

**Problems:**

1. For tool making, a 2 liter tank is used.
- The volume of material placed in this oven is 5 to 25 times the internal volume.
- The volume of coal is 25 times the capacity of the container. (50L vs 2L)

2. Separately, I note the transformation of 12 liters of bones (as an example) into 50 liters of coal.

3. Too high efficiency. 
I base this on a charcoal kiln that is built from a construction menu. https://github.com/CleverRaven/Cataclysm-DDA/blob/a4182b76a76b42881316c331517dbcd56606eba6/data/json/furniture_and_terrain/furniture-tools.json#L346

So, it turns 250 liters of material into only 30,000 charcoal (150 liters).

For an example, let's take splintered wood: 250 liters = 1,000 splintered wood = 30,000 charcoal. Or 1 splintered wood = 30 charcoal.
For a charcoal kiln (tool): 1 splintered wood = 250 charcoal.

Total efficiency is about 8 times higher. 

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

1. The easiest option is to remove this tool from the game. Leave only the constructs.

2. Change his recipe so that he uses
- several 2 liter containers
- 20 liter steel canister
- add new variants of 5 or 10 liter metal tanks
- use a 60 liter metal tank

And also change the amount of materials in the recipe and the amount of charcoal produced.

<table>
    <thead>
        <tr>
            <th rowspan="2">Components</th>
            <th rowspan="2">Volume of 1 unit (L)</th>
            <th colspan="5">Metal tank volume (L)</th>
            <th >Charcoal kiln (furniture)</th>
        </tr>
        <tr>
            <th>2</th>
            <th>5</th>
            <th>10</th>
            <th>20</th>
            <th>60</th>
            <th>250</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td >splintered wood</td>
            <td align="center">0.25</td>
            <td align="center">8</td>
            <td align="center">20</td>
            <td align="center">40</td>
            <td align="center">80</td>
            <td align="center">240</td>
            <td align="center">1000</td>
        </tr>
        <tr>
            <td >plank</td>
            <td align="center">4.13</td>
            <td align="center">none</td>
            <td align="center">1</td>
            <td align="center">2</td>
            <td align="center">4</td>
            <td align="center">14</td>
            <td align="center">60</td>
        </tr>
        <tr>
            <td >stick</td>
            <td align="center">2.5</td>
            <td align="center">none</td>
            <td align="center">2</td>
            <td align="center">4</td>
            <td align="center">8</td>
            <td align="center">24</td>
            <td align="center">100</td>
        </tr>
        <tr>
            <td >bone (any)</td>
            <td align="center">0.32</td>
            <td align="center">6</td>
            <td align="center">15</td>
            <td align="center">31</td>
            <td align="center">62</td>
            <td align="center">187</td>
            <td align="center">781</td>
        </tr>
        <tr>
            <td >bone skewer</td>
            <td align="center">0.025</td>
            <td align="center">80</td>
            <td align="center">200</td>
            <td align="center">400</td>
            <td align="center">800</td>
            <td align="center">2400</td>
            <td align="center">10000 (note 1)</td>
        </tr>
        <tr>
            <td >pine bough</td>
            <td align="center">0.5</td>
            <td align="center">4</td>
            <td align="center">10</td>
            <td align="center">20</td>
            <td align="center">40</td>
            <td align="center">120</td>
            <td align="center">500</td>
        </tr>
        <tr>
            <td >log</td>
            <td align="center">50</td>
            <td align="center">none</td>
            <td align="center">none</td>
            <td align="center">none</td>
            <td align="center">none</td>
            <td align="center">1</td>
            <td align="center">5</td>
        </tr>
        <tr>
            <td colspan="8" align="center">Calculation of the charcoal produced. Factor = 1.0 <br /> (Metal charcoal kiln: Factor = 0.9996 (250L -> 49980 charcoal))</td>
        </tr>
        <tr>
            <td >charcoal</td>
            <td align="center">0.005</td>
            <td align="center">400</td>
            <td align="center">1000</td>
            <td align="center">2000</td>
            <td align="center">4000</td>
            <td align="center">12000</td>
            <td align="center">50000</td>
        </tr>
        <tr>
            <td colspan="8" align="center">Calculation of the charcoal produced. Factor = 0.6 (charcoal kiln)</td>
        </tr>
        <tr>
            <td >charcoal</td>
            <td align="center">0.005</td>
            <td align="center">240</td>
            <td align="center">600</td>
            <td align="center">1200</td>
            <td align="center">2400</td>
            <td align="center">7200</td>
            <td align="center">30000</td>
        </tr>
    </tbody>
</table>

*Note 1*. Unable to place. Maximum number on one tile is 4096.

I'm not sure about the time. A linear function won't work: 11 minutes for a 2 liter barrel. Perhaps something with square roots or logarithms would be better.

### Screenshots

_No response_

### Versions and configuration

Tested on game version 2024-09-25-0552

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AudBobb**
#### Summary
Balance "Audit portable charcoal kiln"

#### Purpose of change

Resolve #76658 and remove pocket dimensions from portable charcoal kilns

#### Describe the solution

Mostly implemented as per #76658.
1) Changed recipe for char_kiln to use a 60L tank instead of a 2L tank
2) Adjusted recipe for the filled charcoal kiln to use 50L of whatever materials are being used, from whatever arbitrary amounts where there before, they were all over the place. I chose 50L instead of 60 because this allows to balance the output to the 50L log, instead of having one recipe for the log, and one for the smaller items that can fit up to 60L. This is open for change. I also removed pine boughs from the possible ingredients, because pine needles aren't going to turn into charcoal, they are just going to burn up entirely. Thought about removing bone splinters as well, but I don't know enough about that to say one way or the other. 
3) Change the output to give charcoal(5000) instead of charcoal(10000). This equates to a conversion factor of 0.5, slightly less than the 0.6 factor for the lower tier stationary charcoal kiln. I believe this makes sense, as a portable version should logically be less efficient than a stationary version could be. There will be less insulation, less heat, just all around worse.

#### Describe alternatives you've considered

Removing it, but I don't think that's really necessary. Also considered leaving it at 2L and adjusting everything to that, but that would leave the item practically useless. 

#### Testing

Loaded into test world, checked recipes

### CODE REVIEW

**Comment by AudBobb** [comment]
In order from least efficient to most

`Portable Charcoal Kiln     -    50% conversion rate`
`Stone Charcoal Kiln        -    60% conversion rate`
`Metal Charcoal Kiln        -    100% conversion rate`

The metal charcoal kiln should probably be reduced in efficiency tbh, no process is 100% efficient after all

**Comment by MikasaTanikawa** [comment]
Volume\mass of _filled_ charcoal kiln should be updated too.

**Comment by AudBobb** [comment]
Good catch, I'll look at that tomorrow probably.

**Comment by EvanBalster** [comment]
@theneofusion I think the metal one holds 250L (five logs).  Four 60L tanks are used to build it.  I usually go with that one because it's quick to build and produces a _ponderous_ amount of fuel quickly.

**Pull request merged**
