### PR TITLE
Move my cola dang it!

### PR DESCRIPTION
**Pull request by Robik81**
Removing unnecessary watertight check from SOURCE container.

What the...
moveitfromthecan_01

That's better!
moveitfromthecan_02

### CODE REVIEW

**Comment by CIB** [comment]
Does it still prevent you from moving part of the contents of a container that can't be resealed?

**Comment by Robik81** [comment]
In a sense that only container that spawns with liquid and is not resealable is aluminium can. Or  I wasn't able to find one.

Anyway! So that's why it's there... Annoying cheaters, that is why we can't have nice things.

Switching to [WIP] until I fix it. Thanks for letting me know. Though I will have to change definition of one container to actually test it. Or change whisky to come in the can instead of bottle.

**Comment by Robik81** [comment]
Fixed.

Can be tested by spawning test_whiskey item in a container via debug menu.

test_whiskey and test_bottle_glass are for testing only and should not be merged

**Comment by kevingranade** [comment]
The reason it's asking for watertightness is that you're going to throw that container in your pack and if it isn't watertight it's going to spill.
If you want to enable putting liquids in non-resealable containers you're going to need to add support for having them spill when placed in the inventory, but not when held or placed on the ground.

**Comment by kevingranade** [comment]
Oh yea, and you get to field the complaints about people's drinks spilling :D

**Comment by Robik81** [comment]
@kevingranade Yeah, I can see why letting people only partially unload non-resealable containers is not a brilliant idea. But I already fixed it by checking that 'move' command only works if you empty the source container entirely. Target container still have to be resealable, no change here.

The only purpose of this PR is to allow moving liquids from factory sealed containers (aluminum cans) into different container without having to resort to Unload command.

**Pull request merged**
