### PR TITLE
Hats with pockets

### PR DESCRIPTION
**Pull request by AudBobb**
#### Summary
Content "Two new hats featuring pockets"

#### Purpose of change

There was a distinct lack of hats capable of holding solid items in the wake of #77243. This PR aims to fix this glaring issue.

#### Describe the solution

Added two new hats featuring pockets, the stylish Fanny Cap, perfect for summer time, and an Ushanka with a pocket built into each ear flap, great for those cold winter months.

#### Describe alternatives you've considered

image

#### Testing

Checked that they recipes showed in game. Both new items are present.

#### Additional context

You're welcome Horis, live out your best ammo storing hat life.

Remaking this because visual studio auto formatted the files when I opened them, causing a massive mess

### CODE REVIEW

**Comment by esotericist** [comment]
the fanny cap is ridiculous, and absolutely not acceptable for merging. 

the ushanka pockets are very unclear on how they're intended to work, and without a reference i suspect the answer is "they probably wouldn't as implemented".

it's very obvious this PR is attempting to fill a perceived gap in functionality, without asking the question of "does this make sense" or "are these things really stuff that should be around". that's not how we do things here.

select reasonable, modestly widespread examples of head-mounted storage, or this isn't going to go anywhere productive.

**Comment by AudBobb** [comment]
I mean, fanny pack hats are actually a thing in the real world, and I don't see why a survivor couldn't make one if they wanted to, but if the PR is denied, then so be it, I'm not really married to the items, just made this in response to the additional context on the linked PR, 🤷 

image

As for the ushanka pockets, the are just pockets sewn into the ear flaps of an ushanka. Plenty of real estate there.

image

**Comment by Holli-Git** [comment]
The only real evidence I could find of them being "a real thing" is a one-off novelty/gag gift on Amazon and I don't think those would exist in nearly enough quantities to be reasonable to see in CDDA. The amount of storage is also pretty generous. As for the ushanka, I doubt that it would last very long as pockets. A hat with small pockets for stuff like bandages would be a more than welcome addition, but this seems to be quite a stretch. Closing PR

**Comment by NetSysFire** [comment]
For the reference, I meant something thats not a silly gag. See https://en.wikipedia.org/wiki/Head-carrying.

**Comment by AudBobb** [comment]
:shrug: I don't really understand what how widespread in popularity them being has to do with this change, I wasn't suggesting they be added to loot pools to spawn in the world, but rather adding a recipe for a survivor to sew a pouch onto a hat. I could go and do that right now myself. And admittedly yes, the volume was probably a bit large, I didn't change it from what the ingredient used when I probably should have. But it's really not a hill I care to fight on, I probably wouldn't have used the item anyways, just figured I'd submit the request since at least one person out there seemed interested. 

>For the reference, I meant something thats not a silly gag. See https://en.wikipedia.org/wiki/Head-carrying.
Fair enough. I just assumed based on context in the post that what was being suggested was a substitute for what was being removed through the bug fix of the drinking cap.

**Pull request closed without merging**
