### PR TITLE
Add new vehicle - "Survivor RV"

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Content "Add Survivor RV"`

#### Purpose of change

What would survivors use to travel safely from A to B?
A very **rare and valuable** RV was added that was previously in the hands of survivors.
It should be comfortable for five passengers and offers all types of vehicle extensions.

<br />
Hope you like it.
<br /><br />

#### Screenshot(s)

V2

grafik

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Could I suggest swapping the locations of the cargo containers and the beds, or otherwise modifying it so you don't have to crawl over containers to get through? I think it would be much easier/preferred to clamber over beds than cargo containers filled with stuff. Just my personal preference though.

**Comment by Pupsi-Mupsi** [comment]
> Treating result as failure due to error logged during initialization.

Travis failed.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Could I suggest swapping the locations of the cargo containers and the beds, or otherwise modifying it so you don't have to crawl over containers to get through? I think it would be much easier/preferred to clamber over beds than cargo containers filled with stuff. Just my personal preference though.

Thanks for the feedback. I think it is important to have a closed sleeping area.

**Comment by anothersimulacrum** [comment]
Restarting Travis will make it fail again, you need to fix the errors it's reporting.
https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/jobs/665260670#L4656

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Could I suggest swapping the locations of the cargo containers and the beds, or otherwise modifying it so you don't have to crawl over containers to get through? I think it would be much easier/preferred to clamber over beds than cargo containers filled with stuff. Just my personal preference though.

Better?

**Comment by anothersimulacrum** [comment]
Looks great!

**Comment by Aphegis** [comment]
i think the spawn of this vehicle should be 10 times rarer.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> i think the spawn of this vehicle should be 10 times rarer.

Fine. There you go.

**Comment by Fris0uman** [comment]
So there will be some fully kitted survivor RV chilling on the street from the start of the game, a few days after the cataclysm?
Wouldn't it make more sense to have this spawn in some specific location like survivor houses or LMOE shelters?

**Comment by Pupsi-Mupsi** [comment]
Good thinking. I will prevent it from spawning in city areas and will reduce the spawnrate even further.  So no bionic prepper will walk into it on day one ;-)

Also, as with most vehicles, it's not very likely to be fully functional. It could appear without batteries or surrounded by zombies. Players who have just started the game cannot benefit from this RV without the right recipes, tools and skills. It's nice to look at, but it won't break the game.

**Comment by Fris0uman** [comment]
I'm more worried about the coherence of it than the balance. If the cataclysm was 5 or 6 days ago how come we already have survivor vehicles in cities. It might make more sense to have it where people would have started prepping in advance or something.

Alternatively having a timer to only make it spawn one month after the cataclysm for exemple would be good but that's outside the scope of this PR.

> I will prevent it from spawning in city areas and will reduce the spawnrate even further. 

That would make a bit more sense yeah

**Comment by Pupsi-Mupsi** [comment]
> Alternatively having a timer to only make it spawn one month after the cataclysm for exemple would be good but that's outside the scope of this PR.

A timer would indeed be a nice thing.

**Pull request merged**
