### PR TITLE
Magiclysm - single use 24 hour corpse wrapper

### PR DESCRIPTION
**Pull request by MrHrulgin**
#### Summary
Mods  "Adds a consumable Magiclysm item to temporarily preserve a corpse"

#### Purpose of change

Per the discussion regarding the deep freezer chest magical item, the need for corpse preservation & transport was recognized, but the form and format of the proposed solution wasn't in line with the general vision for new item creation. This is an expansion of the idea proposed by @I-am-Erk, to shift to a cheaper temporary consumable option. This corpse wrapper will delay decay for 24 hours after being taken out of its own wrapper, as well as applying a 40% reduction in size to enable the transport of large corpses in vehicles. It does not modify weight in any way. I put it in the general container item group, as well as the ones for general wizard and animist tools. Testing it on a revivable zombie corpse, it seems that the revival clock is one of the things delayed by the magic of the device, as all surrounding zombies killed at the same time revived while the one contained in the wrapper popped back out after 24 hours when the wrapper dissolved, and then revived only after no longer being contained.

#### Describe the solution
The wrapped corpse wrapper can be bought or found, and when unwrapped, gives you a capacious single-item wrapper that halts decay for 24 hours, whereupon it vanishes, dumping out the body.

#### Describe alternatives you've considered

A larger, more permanent version that is more akin to a magical chest freezer. Larger vehicle freezers in the main game. Being able to use heat pumps in constructions to make a walk-in freezer.

#### Testing

Spawned the wrapped item, unwrapped it. Inserted an item. Waited 24 hours to see it vanish and dump out the corpse.

### CODE REVIEW

**Comment by MrHrulgin** [comment]
I should say: this is erk' joke theming. If it's too silly, please let me know.

**Comment by I-am-Erk** [comment]
I'm not sure about the size reduction part myself, but I'm not the boss of magiclysm. I think if people want to transport huge corpses they should have to think about quartering them and such

**Comment by MrHrulgin** [comment]
If someone wants to do anything with this, they're welcome to pick it up, or not. I'm going to step away from CDDA for a while.

**Comment by I-am-Erk** [comment]
I hope it wasn't due to my comment. I really don't have anything to do with magiclysm development, I was just offering my thoughts. I think it's cool you were working on this.

**Comment by MrHrulgin** [comment]
No, you're fine. My initial enthusiasm for contributing has faded in the face of the feedback structure maintained by some of the senior members of the community, where arbitrary decisions and emotionally charged statements seemed to be the standard. If I'm going to contribute to something for the love of it, I'm going to do so in an environment where the people in charge aren't so abrasive and arbitrary. I wish everyone well, but for my well-being I won't be a part of this community as it exists right now.

**Pull request closed without merging**
