### PR TITLE
Add thyme plant

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add thyme plant from Wilderness Overhaul mod by MormonPartyboat.
( http://smf.cataclysmdda.com/index.php?topic=9568 )
1. Thyme item.
2. Thyme seeds item.
3. Thyme oil item.
4. Add thyme to forage_spring, forage_summer and forage_autumn item groups.
5. Add disassembly recipe to make wild herbs from thyme.
6. Add recipe for thyme seeds.
7. Add recipe for thyme oil.
8. Allow using thyme oil for making bandages and first aid kits.

Also, I plan to add dogsbane, canola, mugwort and bee balm later, but I am not sure which of these are present in New England as wild plants, so I'd like some help with this.

### CODE REVIEW

**Comment by Snaaty** [comment]
Nice. Although I find the strict new-england stance a little silly, considering there are zombies, robots, mutants of all sorts, etc. in this game. Even if those additional plants weren't today findable in new england I wouldn't say it qualifies as a reason not to include them. Just my two cents.

**Comment by KA101** [comment]
Climate for the most part, re New England.  We kinda like to have *some* thematic factors!

I'm holding out for parsley, sage, and rosemary to go with.  ;-)

**Comment by Coolthulhu** [comment]
Forage groups shouldn't include trash like withered plants.

Finding something from forage group results in enthusiastic "you found something useful!". Plus, it would result in megatons of withered plants being found in winter when grinding for survival or even just for useful trash.

**Comment by Darkyhard** [comment]
Hmm, yes, it's probably a good idea to remove withered plants for now and add them along with fiber ropes later so they would be useful. Thanks.

**Pull request merged**
