### PR TITLE
Person can see you through walls

### LINKED ISSUE #61965: Persons cannot see you when you stand near certain walls.
### Describe the bug

Persons, which have the ability to always see the player, will be sometimes unable to do so if the player is standing next to certain walls.

### Steps to reproduce

1. Find or acquire a Person.
2. Stand next to a metal wall.
3. Marvel at the anti-psionic abilities of solid steel.

### Expected behavior

If an enemy can see you no matter where you hide, then that enemy can see you no matter where you hide.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 0.F-12130-g90e9a75e28 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Bugfixes  "Allow the person to see you through walls"

#### Purpose of change
Fix #61965 by applying the suggested changes to the person.

#### Describe the solution
Add the flag `ALWAYS_SEES_YOU` to the person.

#### Describe alternatives you've considered
None

#### Testing
I spawned a person inside a metal silo, like the one in #61965, and they could see me.

#### Additional context
I also replaced the `ALL_SEEING` flag for the relentless hulk to `ALWAYS_SEES_YOU`, as recommended by @andrei8l.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@GuardianDll tagging you to make sure this is the desired behaviour for the person.

**Comment by GuardianDll** [comment]
Commented it in the issue, but it seems it won't fix the problem

**Comment by MNG-cataclysm** [comment]
I just tested the fixes, and the issue is resolved.

**Review by GuardianDll — APPROVED** [review]
Ok, if you say you test it, and the bug does not occur, then no problem

**Comment by andrei8l** [comment]
I've submitted the `ALL_SEEING` fix as an alternative PR [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/62031). If you want to go for this route, you should also remove the code for `ALL_SEEING` and replace the flag for `mon_zombie_nemesis`. That guy is a nemesis for the player so it makes more sense that it only sees the player and not every other creature too.

**Comment by MNG-cataclysm** [comment]
As anderi8l suggested, I've changed the `ALL_SEEING` flag for the relentless hulk to `ALWAYS_SEES_YOU`.

**Review by GuardianDll — APPROVED** [review]

**Pull request closed without merging**
