### PR TITLE
remove mininuke recipe

### PR DESCRIPTION
**Pull request by kevingranade**
Seriously?

#### Summary
SUMMARY: None

#### Purpose of change
A low yield nuke I could see, but a portable nuke is so far beyond the pale that its not even funny.

### CODE REVIEW

**Comment by Xhuis** [comment]
I feel like the recipe was justifiable pre-explosion buffs, but that it's now far too powerful for the cost.

Perhaps add in a "micronuke" with power similar to the pre-buff mininuke (about 3/4 of a screen)? Many explosives now reach about that far or farther with the changes, so I think it's within the realm of possibility, payload-wise.

**Comment by kevingranade** [comment]
I dont actually care about the power, the problem is the prospect of a survivor slapping together a working mininuke without killing themselves with it.

A larger nuke would actually be a lot more reasonable.

**Comment by Xhuis** [comment]
Time for constructable nuke silos. Let's see how the triffids feel about that glorious nuclear sunshine.

**Comment by kevingranade** [comment]
That was two guys with physics PhDs and it took them two and a half years.  Doesn't exactly support your argument.

**Comment by Timonkeyn** [comment]
chaosvolt told me to go reee at you. reee

**Comment by nexusmrsep** [comment]
> Time for constructable nuke silos. Let's see how the triffids feel about that glorious nuclear sunshine.

Yield of existing big nukes in silos are also far too low. They look like ICBM missiles and all the can do is level a small neighborhood when they should be leveling whole town.

**Comment by secretfire42** [comment]
Nukes are incredibly easy to make. Highschoolers could do it with refined material and step by step instructions - and have, before 9/11. Now, many of the books which used to have the details on that have been quietly removed from circulation. When you get a physics B.S., chunks of the education (from what used to be standard) are missing because of this; and older editions of the books are nice to have around.

I'd say: Remove the mininuke recipe, and have as a goal increasing the yields of big nukes in silos tremendouly, and the ability to make a 'small nuke' or a dirty bomb (even easier).

**Comment by darktoes** [comment]
> That was two guys with physics PhDs and it took them two and a half years.

Yeah but a lot of the time was probably bureaucratic nonsense and the fact they had to have everything checked over and simulated. And they didn't have lab notes which are basically "How we built a mininuke: For Dummies".

**Comment by LeKopic** [comment]
Also, don't forget to remove robots, zombies, 99% of crafting recipes. Just transform Cataclysm into Ordinary day in a woods. This game is not about realism and it never was.

**Comment by ZhilkinSerg** [comment]
> Also, don't forget to remove robots, zombies, 99% of crafting recipes. Just transform Cataclysm into Ordinary day in a woods. This game is not about realism and it never was.

You are dead wrong.

**Pull request merged**
