### PR TITLE
JSON regression check

### PR DESCRIPTION
**Pull request by illi-kun**
Well, quick review shows me that json files regress quite fast so now I agree with [Kevin's idea](https://github.com/CleverRaven/Cataclysm-DDA/pull/14965#issuecomment-174209957) about json regression check.

I created short json whitelist, and bash script presented below detects regression correctly but my issue is its integration to makefile (I know about example of the similar thing in #14508 but I never worked with makefile before and it's hard to me to test it on Windows).

``` bash
#!/bin/bash
ENTRIES=( "\"to_hit\".*:[[:space:]]*0" "\"bashing\".*:[[:space:]]*0" "\"cutting\".*:[[:space:]]*0" "\"phase\".*":.*\"solid\" )
number_of_errors=0
for entry in "${ENTRIES[@]}"; do
  number_of_errors=$((number_of_errors + `cat "json_whitelist" | xargs grep $entry | wc -l`))
done
if [ $number_of_errors -gt 0 ]; then echo "json regression found."; fi
```

I'll be glad to get some help with finalizing this PR.

### CODE REVIEW

**Comment by kevingranade** [comment]
That would be helpful, but without 100% compliance, editor based enforcement is not going to fix the problem, so the automatic validation is needed as well.

**Comment by kevingranade** [comment]
Anywhere in the Makefile, you can add a new target and invoke your new script:
```
json-format-check:
        tools/json_format_check.sh

```
If the script returns 0, it's success and the build continues, if it returns non-zero it fails and halts.
You'd also want to add the new target to the release build target, that part is a little weird, changing line 161 to this will do it:
```
  ASTYLE = astyle-check json-format-check
```

**Comment by narc0tiq** [comment]
I suggest the script should actually return non-zero if it detects JSON regressions. Probably just return the number of errors, in fact.

In fact, if you pass the right arguments to grep, you can have it output the file and line that matches, capture that output into an environment variable, and print it along with "JSON regression found", which would allow readers to correct the issue more quickly.

**Comment by illi-kun** [comment]
@narc0tiq you're absolutely correct, it will be useful. I tried to shorten script as much as possible because I thought I have to integrate it in makefile.

Allowing to use dedicated script file for that regression check makes things easier but I little bit worrying about safety: any modification of makefile causes big red __X__ automatically and it will be good to have the same functionality for any script executed by makefile.

Kevin, thanks for help, I will finalize this PR soon (this weekend, I suppose).

**Comment by narc0tiq** [comment]
> Allowing to use dedicated script file for that regression check makes things easier but I little bit worrying about safety: any modification of makefile causes big red X automatically and it will be good to have the same functionality for any script executed by makefile.

Agreed, and since I'm keeping an eye out for this PR anyway, I can (and intend to) make the change on the Jenkins PR builder to add the new script to the safety check already in place. If you wanted to be super-safe about it, let me be the one to merge this and I can time it as closely as humanly possible. 

In fact, let me just assign myself here so we don't forget.

**Comment by illi-kun** [comment]
I suppose it's ready for review.

**Comment by narc0tiq** [comment]
Looks good to me. I did need to fix a couple of things in the merge:

- the script was not marked executable; that was a simple `chmod a+x tools/json_format_check.sh`.
- there was an extraneous `cd ..` near the top of the script; if you're executing it as `tools/json_format_check.sh`, the working directory is already one level up from where the script is.

**Comment by illi-kun** [comment]
Thank you for review, fixing, and merging it.

**Comment by narc0tiq** [comment]
No thanks needed, it was my pleasure.

**Pull request merged**
