### PR TITLE
[WIP] IWYU support (part 6): Apply IWYU changes (take 2)

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Infrastructure "Update header includes to include-what-you-use standards"

#### Purpose of change
To include what we use :).

#### Describe the solution
Three more commits with platform-specific fixes, followed by one big commit with the changes made by running IWYU as described in DEVELOPER_TOOLING.md, followed by astyle.

#### Additional context
Note that although IWYU does sort headers by category, it does not sort alphabetically within categories.  I don't have a tool to do that, so things are now non-alphabetical.

Some blank lines have been introduced in places where we probably don't want them.  If people feel strongly then I can tidy those up, but would prefer to do so in a separate PR.

This is quite likely to break the Android build.

### CODE REVIEW

**Comment by jbytheway** [comment]
Again, Gorgon is complaining because of changes to `json.h`.

**Comment by kevingranade** [comment]
Did IWYU get confused by the #ifdef RELEASE in tests/hash_test.cpp?
```
hash_test.cpp:128:24: error: ‘std::chrono’ has not been declared
     auto start1 = std::chrono::high_resolution_clock::now();
                        ^
hash_test.cpp:138:22: error: ‘std::chrono’ has not been declared
     auto end1 = std::chrono::high_resolution_clock::now();
                      ^
hash_test.cpp:139:17: error: ‘std::chrono’ has not been declared
     return std::chrono::duration_cast<std::chrono::microseconds>( end1 - start1 ).count();
                 ^
hash_test.cpp:139:44: error: ‘std::chrono’ has not been declared
     return std::chrono::duration_cast<std::chrono::microseconds>( end1 - start1 ).count();
                                            ^
Makefile:45: recipe for target 'obj/hash_test.o' failed
```

**Comment by jbytheway** [comment]
> Did IWYU get confused by the #ifdef RELEASE in tests/hash_test.cpp?

Yes; I ran in debug mode so it didn't account for uses in `RELEASE` only.

Will do some more prep and then return to this.

**Comment by jbytheway** [comment]
I think this is now ready (finally got a green tick on the Travis CI), but it probably shouldn't get merged until post-0.D because it will lead to all sorts of annoying merge conflicts between master and the release branch.  I'll return to it then.

**Comment by kevingranade** [comment]
OK this has accumulated a massive list of conflicts, feel free to reopen when you have time and interest.

**Pull request closed without merging**
