### PR TITLE
[CR] Move Messages details behind a pimpl

### PR DESCRIPTION
**Pull request by bkentel**
First, I want to apologize for including what should be two separate PR's together in this one, but they aren't easy to untie.
(1) The original purpose -- move the implementation details of `Message` out of the header.
- Use the pimpl pattern.
- Move the details into the cpp file.
- Use a `std::deque` instead of vector for the message history.
- Eliminate includes and add forward declarations.
- Remove redundant friend declarations.
- Remove a redundant const.
- Give the code a once over for clarity, warnings.
- Add `override`.

(2) The unintended consequences. The json facilities didn't support writing to / from a `std::deque`, so I investigated, and changed more than I wanted to.
- Merged duplicate container io code via some SFINAE ugliness; ideas for simpler SFINAE expressions that could accomplish the same thing are welcome.
- Because of the above, the litany of std container includes are all but gone.
- Touched up a few of the container construction functions to use `emplace`.
- A few tiny modifications to disambiguate overloads, and eliminate warnings.

### CODE REVIEW

**Comment by bkentel** [comment]
Is there some special rule in the makefile for `json.h`? It's failing before compilation.

**Comment by narc0tiq** [comment]
There's a special rule on the Jenkins for `json.h`, yes. Since `chkjson` is compiled and executed (as `make json-check`) by the PR building process, that is protection against arbitrary code execution -- simply put, if the file is different than the latest compiled version, the compile is automatically aborted.

**Comment by bkentel** [comment]
Ahh, thanks for the info @narc0tiq.

**Comment by kevingranade** [comment]
What is CR about this?  It looks ready to go from what I can see.

**Comment by kevingranade** [comment]
By the way, it would be absolutely trivial to make the json changes a separate PR and just note that the other changes depend on it, please consider doing that in the future.

**Comment by KA101** [comment]
One of those times where "never heard of 'a pimpl'" combined with "merge conflict".

Googling, well, I'm not a fan of Hide The Code.

**Comment by kevingranade** [comment]
That was @bkentel 
This looks like a good thing overall, but it's going to require heavy review since it basically rewrites the whole module, and I don't want to embark on that until the author at least considers it ready to go.

**Comment by bkentel** [comment]
I think it's ready to go as it is, but since it touches the json facilities I just wanted to make sure others gave it a look over. I took care of the merge conflict just now as well.

**Comment by kevingranade** [comment]
Not quite ready:
```
(gdb) bt
#0  0x00007f84e2594a97 in raise () from /usr/lib/libc.so.6
#1  0x00007f84e2595e6a in abort () from /usr/lib/libc.so.6
#2  0x00007f84e2ed77b5 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/libstdc++.so.6
#3  0x0000000000799d3f in std::__debug::deque<(anonymous namespace)::game_message, std::allocator<(anonymous namespace)::game_message> >::operator[] (this=0x2ddc0d0, 
    __n=18446744073709551615) at /usr/include/c++/4.9.2/debug/deque:306
#4  0x0000000000799290 in Messages::display_messages (ipk_target=0x3185460, left=0, top=5, right=45, bottom=45) at src/messages.cpp:299
#5  0x00000000009d0827 in game::draw_sidebar (this=0x7f84e24fd010) at src/game.cpp:5030
#6  0x00000000009cf87f in game::draw (this=0x7f84e24fd010) at src/game.cpp:4915
#7  0x00000000009b4bab in game::do_turn (this=0x7f84e24fd010) at src/game.cpp:1417
#8  0x0000000000a666bf in main (argc=0, argv=0x7fffe3421420) at src/main.cpp:295
```
Also needed a number of header adjustments to compile on linux.
```
diff --git a/src/active_item_cache.h b/src/active_item_cache.h
index 478ec9a..78c9651 100644
--- a/src/active_item_cache.h
+++ b/src/active_item_cache.h
@@ -4,6 +4,7 @@
 #include "enums.h"
 #include "item.h"
 #include <list>
+#include <unordered_map>
 #include <unordered_set>
 
 // A struct used to uniquely identify an item within a submap or vehicle.
diff --git a/src/clzones.h b/src/clzones.h
index 2da8f19..038c265 100644
--- a/src/clzones.h
+++ b/src/clzones.h
@@ -6,6 +6,7 @@
 #include <vector>
 #include <string>
 #include <unordered_map>
+#include <unordered_set>
 #include <utility>
 
 /**
diff --git a/src/json.h b/src/json.h
index 99d5abc..153839a 100644
--- a/src/json.h
+++ b/src/json.h
@@ -7,6 +7,8 @@
 #include <vector>
 #include <bitset>
 #include <array>
+#include <map>
+#include <set>
 
 /* Cataclysm-DDA homegrown JSON tools
  * copyright CC-BY-SA-3.0 2013 CleverRaven
diff --git a/src/messages.h b/src/messages.h
index af3dd68..0eccecf 100644
--- a/src/messages.h
+++ b/src/messages.h
@@ -1,14 +1,13 @@
 #ifndef MESSAGES_H
 #define MESSAGES_H
 
-#include "catacurse.h" // WINDOW
+#include "cursesdef.h" // WINDOW
 
 #include <memory>
 #include <string>
 #include <vector>
 #include <utility>
-
-#include <vadefs.h>
+#include <cstdarg>
 
 class JsonOut;
 class JsonObject;
```

**Comment by kevingranade** [comment]
Found the crash, it's because you declared a loop index as ```auto i = size()```, meaning it's an unsigned int, then decremented it past 0, which means it went super-positive and made it past the loop test.

**Comment by kevingranade** [comment]
Patched up a few bugs and merged.

**Comment by bkentel** [comment]
@kevingranade Thanks for taking care of that; I missed those headers as a side effect of using pre-compiled headers. I should have know that there would be some fallout from removing the includes in `json.h` though.

Re: `size()` I don't know how that slipped passed when I was testing -- I must have just been "lucky" to not hit a case where it was decremented past zero; a bit of an embarrassing oversight. Regardless, thanks for taking the time to take care of those issues.

**Comment by bkentel** [comment]
@KA101 it's a way to clearly separate the interface from the implementation -- why should I have to know or care that messages use a vector or a deque internally? It can also greatly improve build times and reduce dependencies when applied well. It's not a panacea though, and can have its downsides with performance sensitive code (the extra layer of indirection) for example. It also requires a bit of annoying boiler-plate.

**Comment by DavidKeaton** [comment]
I know about precompiled headers, worth it?

**Comment by KA101** [comment]
I'm not really concerned about perfectly streamlined code.  I'm concerned about folks who haven't taken formal programming training being able to look at DDA's code and figure out what's going on.

**Comment by bkentel** [comment]
@DavidKeaton It can be -- it's pretty easy to set up on all common compilers; benchmark it if you're curious.

@KA101 in general, where's the balance between compile time, run time, and novice friendliness? This, at least, is a pretty ubiquitous idiom. I do understand your concern though.

**Pull request closed without merging**
