### PR TITLE
A bunch of random density fixes

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
The players yearn for correct density values

#### Describe the solution
- Some integrated patchwork armor got a volume increase - this shouldn't affect the gameplay at all to my knowledge, but shuts up the tests
- Beer is now 2g lighter because both ethanol and water have below 1g/ml density how tf was it heavier
- Pine needle tea is slightly lighter, and had veggy added to its material
- Both dandelion teas got veggy added to its material
- Hot sauce got a 50/50 veggy and water material assigned, and is slightly lighter now
- Soy sauce got a water material assigned
- Alcohol wipes got a cotton material assigned
- Removed a useless volume field from Kentucky coffee grounds
- Adhesive bandage got refreshed material syntax (I'm not convinced this changed anything)

### CODE REVIEW

**Comment by Procyonae** [comment]
Are you just leaving the pine needles/dandelions etc in the tea??? Why are you making them 50% veg and why would they be a non negligible different density to water, use a heavily biased portion if you want to be pedantic

**Comment by Karol1223** [comment]
> Are you just leaving the pine needles/dandelions etc in the tea??? Why are you making them 50% veg and why would they be a non negligible different density to water, use a heavily biased portion if you want to be pedantic

I can only assume that yes, parts of them are being left in the tea, with how the weight of the item is set. Imagine the pine needles like sprinkles. They add the flavor.

**Comment by Karol1223** [comment]
> Beer should be similar to water. It has ethanol which is less dense, but also a lot of matter in free suspension which is heavier and compensates. IRL it is marginally denser (most decent [source](https://hypertextbook.com/facts/2000/BlairElefant.shtml) I found). I'd bet that is the purpose of the current value.

Unfortunately it seems you are correct and it's inconvenient. I suppose it gets banished to 1g/ml limbo.

**Comment by Procyonae** [comment]
I mean again it would make more sense for it to be like `"material": [ { "type": "alcohol", "portion": 4 }, { "type": "water", "portion": 96 } ]` rather than our beer being 50% alcohol...

**Comment by Karol1223** [comment]
> I mean again it would make more sense for it to be like `"material": [ { "type": "alcohol", "portion": 4 }, { "type": "water", "portion": 96 } ]` rather than our beer being 50% alcohol...

That's not the relevant issue, the issue I'm talking about is alcohol's density.

**Comment by Procyonae** [comment]
So bc the test isn't particularly good you don't see any reason to make more logical changes and are instead making things 50% other materials to bypass the values being wrong?

**Comment by Karol1223** [comment]
> So bc the test isn't particularly good you don't see any reason to make more logical changes and are instead making things 50% other materials to bypass the values being wrong?

No, I'm making them 50% because it fixes the test and doesn't matter ingame. If there were any observable differences ingame I would care more about proportions, but for the purposes of comestibles which I cannot be bothered to calculate 50/50 is good enough if it fixes the density test.

**Comment by RedMisao** [comment]
I was going to suggest setting the correct values for reasons of future proofing. Then I looked at the material list and noticed a lot of materials have wrong densities, like `alcohol` being 1, `cardboard` being 2, etc. I'm assuming that, if those are fixed directly more stuff/tests will break? (For reference, IRL ethanol density is 0.789)

After that I realized, applying proportional values to things like beer will make it inconsistent _in game_, as if the `alcohol` density is reduced, it would also result in beer being less dense that water (as it's a mix of both).
The solution to this case example would be to add `veggy` or something denser, but I cannot imagine this approach to every single item to reach the correct densities.

**Comment by Karol1223** [comment]
> I was going to suggest setting the correct values for reasons of future proofing. Then I looked at the material list and noticed a lot of materials have wrong densities, like alcohol being 1, cardboard being 2, etc. I'm assuming that, if those are fixed directly more stuff/tests will break? (For reference, IRL ethanol density is 0.789)

Yes, a lot of our densities are haphazardly chosen. Alcohol has density from water it would appear, but realistically it should have density of the most dense alcohol-based item we have in the game not pure ethanol, since the material isn't ethanol - it's a placeholder for ALL alcohol. And yes, things would break. I'm not trying to be perfect in this PR, I'm trying to have the PR be an improvement.

**Pull request merged**
