### PR TITLE
Edited the description of the Traps skill.

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This may fix issue #16673.

### CODE REVIEW

**Comment by karols146** [comment]
I would just use `your chance to evade a trap after it is triggered`

**Comment by Skidborg** [comment]
It might be worth explicitly explaining that trapping skill does help with detecting hidden traps, since it's been marked as doing the opposite all this time.

**Comment by codemime** [comment]
Howmuchtestinghasbeendone?

**Comment by BorkBorkGoesTheCode** [comment]
Muchtestinghasbeendoneasifigureouthottoupdatemyforkwhenevernewcdeisaddedgesundheit.

**Comment by karols146** [comment]
Read about rebase.

**Pull request closed without merging**
