### PR TITLE
move warning suppression, fix clang-tidy

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
Suppress the warning

### CODE REVIEW

**Comment by kevingranade** [comment]
That didn't do it,  maybe wrap the places where it's invoked?

**Comment by anothersimulacrum** [comment]
This was introduced in clang-tidy 14 https://stackoverflow.com/questions/55165840/clang-tidy-nolint-for-multiple-lines

It looks like we're using 12?

**Comment by anothersimulacrum** [comment]
Let's see if https://github.com/CleverRaven/Cataclysm-DDA/pull/64579 works.

**Comment by kevingranade** [comment]
#64579 is the correct fix.

**Pull request closed without merging**
