### PR TITLE
Scenario and profession traits do not count towards traits point pool

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Bugfixes "Scenario and profession traits do not count towards traits point pool"

#### Purpose of change
Scenario/Profession traits should be considered intrinsic to the scenario/profession the player chooses and should not be part of trait point consideration. It becomes limitting to how the player would choose to play and leads to situations like -15/-12 points for starts like Churl in character generation.

#### Describe the solution
Exclude scenario and profession traits from point cost consideration.

As per @anothersimulacrum , additionally updated the point costs of professions that implicitly held starting traits. This is due to that trait now being a given. Depending on the scenario/profession chosen, this can be considered a buff.

Format: Profession - Point cost
Death row convict :  2 points
Rat prince/princess :  4 points
Traceur/Traceuse :  5 points
zoo keeper : 1 point
Politician :  5 points

#### Describe alternatives you've considered
None

#### Testing
Create a Churl character and use all 12 points allocated for both sides.
Create a Traceur and check total points.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Existing scenarios/professions should probably have these costs tacked on then, otherwise you're skewing the values of them, which I don't think you intend to do in this PR (as that's a larger balance consideration).

**Comment by CodeBandit** [comment]
@anothersimulacrum 
I admit that the skew in balance was not taking into consideration. With that, supposing as part of this PR that I tack on the trait costs of scenarios and professions to their respective total cost, would that not, in itself, throw the balance out of order? Below is all theoretical consideration but...

Suppose we went with Challenge - Medieval Peasant, we get a net of 13 points available for use due to traits. Applying this to the scenario would give it 13 + 8 + 1 for a whopping 22 points for use in skills instead? That would 3 points shy from going from 0 to 10 skill in char gen

**Comment by anothersimulacrum** [comment]
Oh sorry, I meant to clarify all other professions/scenarios barring the one this was being done for.
It may need a more careful eyes, but I (having not examined it) don't think that should cause too many problems outside of this one.

**Comment by CodeBandit** [comment]
Looking through professions.json and scenarios.json, an exhaustive list of all professions and scenarios affected is shown below (surprisingly little):

Professions:
Death row convict : Killer (-2 points) total 2 points
Rat prince/princess : Animal Empathy (-1 point), total 4 points
Traceur/Traceuse : Parkour (-2 points), total 5 points
zoo keeper : Animal Empathy (1 point), total 1 point
Politician : Liar (-1 point), total 5 points

Scenarios:
Challenge - Medieval Peasant (a total of 22 points)
Challenge - Abandoned : Frail (6 points)

I will be waiving any changes to scenarios since it is 100% all down-sides. You are able to grab more negative traits than ever with no additional benefit.

**Pull request merged**
