### PR TITLE
Basements (mapgen) update

### PR DESCRIPTION
**Pull request by Coolthulhu**
Jsonized 3 of the basements:
- Weed
- Game
- Chemset

But also:
- Updated all basements to have wooden walls
- Crunched the basements to have their stairs closer to the center - this makes stairs more likely to be align-able (good for z-levels)
- Allowed all basements to rotate randomly

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>Updated all basements to have wooden walls

Most basements here in the USA tend to have stone walls.

**Comment by mugling** [comment]
> Allowed all basements to rotate randomly

This is good

**Comment by Coolthulhu** [comment]
> Most basements here in the USA tend to have stone walls.

I went with what gun and survivor basements had.

I could change all of them to smooth stone or brick instead.

**Comment by Zireael07** [comment]
> I could change all of them to smooth stone or brick instead.

Please do!

**Comment by pisskop** [comment]
is this all the basements?

From what Ive noticed json ids take precedence over hardcoded rooms with the same id.

case and point -> triffid groves

**Comment by Coolthulhu** [comment]
> is this all the basements?

Junk and spider ones are still hardcoded. Junk basement has this weird furniture placement that makes squares (now rectangles) of furniture and this cannot be jsonized easily. Spider is just a bunch of webs, eggs and spiders on top of junk.

**Comment by DangerNoodle** [comment]
Interesting. That does remind me, I was requested to implement basement entries for Arcana and Magic Items mod, and was provided a link to them by the mod author. I had said I will when I get the chance yet to do so due to business.

**Comment by mugling** [comment]
> I could change all of them to smooth stone or brick instead.
> 
> Please do!

Smooth stone isn't yet in many tilesets so brick would be better

**Comment by Karlieb** [comment]
> I could change all of them to smooth stone or brick instead.

Is the smooth stone not decorative (like irl libraries or government buildings)? If not, I'll need to change the tiles I made for it.

**Comment by Coolthulhu** [comment]
I always imagined the basement walls as concrete. Slav commie blocks around here have concrete basements and most basement photos I've seen had walls either covered or looking like rough concrete.
Plus, lab walls are concrete, meaning that it is well established "underground structure wall" kind of a thing.

**Comment by pisskop** [comment]
nothing is sttong enough to break down rock (but not conrete) that can reasonably brle expected to spawn in b1 anyway.

no hulks, borebots, darkwyrns, grabloids dont exist on the b1 level

**Comment by mugling** [comment]
Everything else in this PR checks out apart from the wall change so I've merged everything except that whilst we discuss the best way forward with that

**Comment by Cat09** [comment]
My vote is for concrete. that is definitely the standard here in New England. Finished basements may have a facade in front, but the actual wall is almost always concrete.

**Pull request merged**
