### PR TITLE
Mega mutant monsters

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Content "Adds mega mutant monsters"

#### Purpose of change

Monster diversity, change game over time

#### Describe the solution

Adds 15 new mutant monsters for insects and crayfish and upgrades existing largest mutants into them. Gives unique names, special attacks, and stats.

#### Describe alternatives you've considered

More, another still bigger upgrade

#### Testing

World loads no errors, monsters spawn and look right (names have all changed since this screenshot)
Screen Shot 2020-09-15 at 10 43 23 PM

#### Additional context

"A titanic beauty spreads a macabre wave of horror! A terrifying masterpiece of shock and chills!" - Attack of the 50 Foot Woman advertisement

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I'm not really all that fond of these being just cookie cutter "the same enemy but now it's bigger" down to the same stats and abilities.

**Comment by aoae23** [comment]
I think that changing the names than just "mega" _ would be a good step to make these new monsters more atmospheric. Would be willing to discuss some ideas.

**Comment by LyleSY** [comment]
I'll look at special attacks again. SMASH would make sense for some of them. Might be some good spell options if I can figure that system out. I'll look at some armor buffs too. Here are the names I brainstormed:
"id": "mon_crayfish_mega",
    "name": { "str": "colossal crayfish" },
    "id": "mon_bee_mega",
    "name": { "str": "alpha bee" },
    "id": "mon_centipede_mega",
    "name": { "str": "infinity centipede" },
    "id": "mon_dragonfly_mega",
    "name": { "str": "great wyrmfly", "str_pl": "great wyrmflies" },
    "id": "mon_fly_mega",
    "name": { "str": "frigate fly", "str_pl": "frigate flies" },
    "id": "mon_mosquito_mega",
    "name": { "str": "bloodbank mosquito" },
    "id": "mon_spider_cellar_mega",
    "name": { "str": "warehouse spider" },
    "id": "mon_spider_jumping_mega",
    "name": { "str": "missile spider" },
    "id": "mon_spider_trapdoor_mega",
    "name": { "str": "deathtrap spider" },
    "id": "mon_spider_web_mega",
    "name": { "str": "wyrd spider" },
    "id": "mon_spider_widow_mega",
    "name": { "str": "black death widow" },
    "id": "mon_spider_wolf_mega",
    "name": { "str": "necrowolf spider" },
    "id": "mon_wasp_mega",
    "name": { "str": "whale wasp" },
    "id": "mon_ant_soldier_mega",
    "name": { "str": "super soldier ant" },
    "id": "mon_locust_mega",
    "name": { "str": "famine" },

**Comment by EvgenijM86** [comment]
Whale Wasps are pushovers. I have seen how a horde of zombie children killed ~10 of them and Whale Wasps scored zero kills (they were just fleeing the entire time).

**Pull request merged**
