### PR TITLE
Remove classic_zombies world setting. Add classic_zombies mod

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary
```SUMMARY: Content "Removed classic_zombies world setting. Added classic_zombies mod"```

#### Purpose of change
The existing classic zombies world option has its issues. Due to how its limits are made it will remove all non "CLASSIC"/"WILDLIFE" things, and in some cases even things it shouldn't. And due to being hardcoded it can't be easily fixed.

Making it into a json mod makes it much easier to modify it.

#### Describe the solution
Added new classic zombies mod that:
* Uses MONSTER_WHITELIST to limit monsters to only "CLASSIC" and "WILDLIFE".
* Uses overmap feature whitelist to limit overmap specials to "CLASSIC" only.
* Uses new external option to disable robots spawning from alarms.
* Uses overmap overlay to remove follwing map extras: mx_portal, mx_portal_in, mx_anomaly, mx_spider, mx_shia, mx_jabberwock, mx_house_spider and mx_house_wasp.

### CODE REVIEW

**Comment by Hirmuolio** [comment]
Something is still letting non-whitelisted monsters leak through.
So far I have encountered one lone giant beem a lone hunting horror anda mi-go with human corpses near it.

**Comment by ZhilkinSerg** [comment]
There is also Mundane zombies mod - would you consider obsoleting it (and merging) with your new mod?

**Comment by Hirmuolio** [comment]
This one does much more than the mundane zombies.
Mundane zombies would still be useful if you want to play with triffids, mushrooms, mi-gos and other odd things but not the advanced zombies that shoot acid and lightning.

**Comment by ZhilkinSerg** [comment]
Yeah, makes sense.

**Pull request merged**
