### PR TITLE
(perf-tweak-2) More careful traversal of item linked-lists during lightmap calculation

### PR DESCRIPTION
**Pull request by bkentel**
This adds a per-cell array `lum[][]` to `submap` to cache the number of items in `itm[][]` which take part in lighting calculations. It can be quite expensive to traverse these lists when item stacks get large due in part to the cache effects of linked lists. I chose `int` as the type, but a smaller type could possibly be used instead since max items is only 4096 AFAIK.

I've patched up all places in the code that touch `submap::itm` as far as I can tell. It probably wouldn't hurt if someone could double check I haven't missed anything.

Changes to `Item`
- added `is_emissive()`.

Changes to  `map::generate_lightmap`
- hoisted a variable out of the loop.
- merged the nested ifs.
- moved a temp variable into the switch statement.
- combined separate mutually exclusive ifs into the if else chain.

See #11180

### CODE REVIEW

**Comment by DavidKeaton** [comment]
If Max is 4k, why not use short?

**Comment by bkentel** [comment]
Is the max actually 4096? The code comments seem to suggest it isn't strict. But yes, I wanted to make it short. It could probably even be just a byte with some extra logic for when the item count exceeds 255.

**Comment by narc0tiq** [comment]
The only 4k maximum I know of is 4,000 volume per tile, which is primarily a sanity cap (though players tend to exceed that fairly often). I'm not convinced there's a maximum number of items per tile, however I can't imagine a situation where it'll even approach `MAX_SIGNED_INT`.

One question -- I've only skimmed the patch, so forgive me if this is obvious, but would an array of bool be as good, just to tell you whether the tile contains any luminous items? The `lum[][]` array only seems to be used for that purpose, as far as I can tell, and submaps are already fairly large objects for how common they are.

**Comment by DavidKeaton** [comment]
Is it standard for `bool` to be `sizeof(char)`?

**Comment by narc0tiq** [comment]
In C++? I think so. I don't believe a pointer can normally have sub-byte resolution.

**Comment by DavidKeaton** [comment]
Pointers almost always tend to be ptrdiff_t in size (which matches bit size for system, or should).

**Comment by narc0tiq** [comment]
Well, arrays are (to the best of my knowledge) handled as pointers to the first item plus `sizeof(item_type)` bytes. So they'd have to have byte-level resolution for that.

**Comment by DavidKeaton** [comment]
Ah, C++ metadata for containers, right. :-)

**Comment by bkentel** [comment]
The problem with using just a `bool` here is that you would have to scan the entire linked list every time an item was removed to be sure it was the last lit item. Maybe that's a problem, maybe not. A `(u)int8_t` would be a good compromise maybe -- only need to fully scan the list when the value is 255.

**Comment by narc0tiq** [comment]
Yeah, that'd probably work well. I can't imagine more than 255 lit items in a tile being terribly common.

**Comment by bkentel** [comment]
On a related topic I was wondering about, how common is it to have more than say 1-3 fields active on a given tile? There are some 40 odd types of fields, but are there ever more than a tiny number active at one time (barring exceptional circumstances)?

**Comment by KA101** [comment]
4 or so is the most I'd suspect sustainable for a significant amount of time: bloodstain a place, then set it on fire and have the fire last long enough to generate smoke & hot air.

**Comment by kevingranade** [comment]
A byte array would probably be fine, remember we're talking 255+ *luminous* items, not items in general.
That having been said, I'm not sure if it's worthwhile to risk it for fragility, though a short would get us half the savings and I'd be quite confident that many light-bearing items on a square would never happen in practice.

**Comment by bkentel** [comment]
A check, wrapped up in a tiny helper, on incrementing or decrementing the value should be relatively simple and only in the most pathological cases should there be more than 255 luminous items on one square let alone multiple squares. But a short would also be a good compromise.
```cpp
if (count == 0xFF) {
    // scan through the whole list
}
```

**Comment by narc0tiq** [comment]
My pre-existing save seems to have acquired a segfault from this PR:

```
Core was generated by `./cataclysm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x086bd931 in map::generate_lightmap (this=0xf712a0b4) at src/lightmap.cpp:96
96                      if (get_submap_at(sx, sy, lx, ly)->lum[lx][ly]) {
(gdb) bt
#0  0x086bd931 in map::generate_lightmap (this=0xf712a0b4) at src/lightmap.cpp:96
#1  0x08713aee in map::build_map_cache (this=0xf712a0b4) at src/map.cpp:5272
#2  0x0841cd4f in game::update_map (this=0xf712a008, x=@0xff9f1444: 70, y=@0xff9f1440: 64) at src/game.cpp:12686
#3  0x083f52f1 in game::update_map (this=0xf712a008, p=0xf717b1cc) at src/game.cpp:12606
#4  0x083edb76 in game::load (this=0xf712a008, worldname=..., name=...) at src/game.cpp:3831
#5  0x086d2d79 in game::opening_screen (this=0xf712a008) at src/main_menu.cpp:670
#6  0x086cbea2 in main (argc=0, argv=0xff9f7898) at src/main.cpp:292
```

I'm guessing there's a missing initialization bit somewhere. Interestingly, a fresh new world exhibits the same symptoms, so I can only question what kind of testing this got.

**Comment by narc0tiq** [comment]
Even more interestingly, the segfault doesn't happen to others. I'm fairly okay with this.

**Comment by narc0tiq** [comment]
And now an even more fun oddity: with gdb attached, it gets through the first four calls to `map::generate_lightmap`, and fails on the **fifth** with this backtrace:
```
#0  0x086bd931 in map::generate_lightmap (this=0xf79d00b4) at src/lightmap.cpp:96
#1  0x08713aee in map::build_map_cache (this=0xf79d00b4) at src/map.cpp:5272
#2  0x083fb77c in game::draw_ter (this=0xf79d0008, posx=68, posy=63, looking=false) at src/game.cpp:5081
#3  0x083f7f42 in game::draw_ter (this=0xf79d0008, posx=-999, posy=-999) at src/game.cpp:5064
#4  0x083a6a88 in game::draw (this=0xf79d0008) at src/game.cpp:4909
#5  0x083a49be in game::do_turn (this=0xf79d0008) at src/game.cpp:1417
#6  0x086cbed8 in main (argc=0, argv=0xffffd7f8) at src/main.cpp:295
```

If I ask gdb to `print get_submap_at(sx, sy, lx, ly)->lum[lx][ly]`, it gives me a value. I don't have the slightest idea wtf this is doing.

**Comment by narc0tiq** [comment]
Further interesting fact: the crash doesn't appear when compiling with g++. What the fuck, clang.

**Comment by KA101** [comment]
Well, shit, sorry, Narc.  Compiler-based bugs are the worst.

**Comment by bkentel** [comment]
@narc0tiq very odd -- does it happen with the newest byte based PR too? Have you tried pulling `lx` and `ly` out of the loop? What were the values of `sx, sy` and `lx, ly` anyway?

**Comment by bkentel** [comment]
By the way, does it fail for you in both optimized and unoptimized builds?

**Comment by bkentel** [comment]
Also, if you have the assembly output generated by that line it could help.

**Comment by bkentel** [comment]
There's another PR coming soonish that makes a further change -- see if that fixes it for you @narc0tiq.

**Comment by narc0tiq** [comment]
> What were the values of `sx, sy` and `lx, ly` anyway?

`0, 0` and `0, 0`, respectively. It was very odd! But the new PR definitely fixes it. I didn't test with the byte-based PR until testing #11201 just now; either one might've fixed it, I guess.

**Pull request merged**
