### PR TITLE
Martial Arts Rebalance for Aikido

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Aikido"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Aikido

#### Describe the solution

`Aikido is a Japanese martial art focused on self-defense, while minimizing injury to the attacker.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Aikido | Unarmed 0 | Static Buff | -50% bash damage |
Double Pain| | Special Ability | Pain inflicted is doubled (doesn't work/exist)
throw|Unarmed 2|Unarmed Tech|Down duration: 1, Knockback distance: 1, Knockback spread: 1
feint at|Unarmed 2|Unarmed Tech|Feint
disarm|Unarmed 3|Unarmed Tech|Disarm
dodge throw|Unarmed 6|Unarmed Dodge Counter|Down duration: 1, Knockback distance: 1, Knockback spread: 1

Aikido is clearly meant to be defensive style that focuses on disabling opponents instead of hurting them. However, there is no reason to do this in CDDA. One could argue that it's meant to be used again NPCs considering it has a disarm tech but the whole "pain" concept isn't implemented and NPCs are much rarer than zombies which should always be killed instead of "disabled". Thanks to the damage penalty, you end up having a style that penalizes you for using it and offers nothing worthwhile in return.

_Problems and issues_
- **-50% damage is a bad way to make a style "defensive".** 
A -50% damage debuff is a HUGE deterent on a martial art. Aikido in no way makes up for it's lack of damage with is sparse moveset either.

- **The double pain special effect doesn't exist in-game.** 
Aikido appears to be balanced on a mechanic that doesn't exist in CDDA. Pain exists for players but doesn't have any effect on monsters or NPCs. Furthermore, Aikido doesn't have any sort of variable set up to utilize that system even if it did exist. You can't balance a martial based on a mechanic that will be added "later". Also, if pain is determined by damage then 50% damage * 200% pain = 100% pain inflicted. So, Aikido inflicts as much pain as any other style. They probably meant double the NORMAL damage.

- **Aikido doesn't teach attacks.** 
Aikido in the older days did have strikes but modern aikido does not. Well, they technically do [(Link)](https://www.youtube.com/watch?v=NPbZMcI9a88) but these are mainly used in sparing to teach students how to properly defend themselves.

- **The technique learning order doesn't make sense.** 
A lot of styles have this issue but aikido is one of the worst. You learn your first technique at Unarmed level 2. Prior to this, all aikido gives you is a damage debuff! You would be better off using "no style" to fight than using aikido if your Unarmed skill is below 2! The dodge throw being given so late is bad too.

_Rebalance Goal_
Aikido shouldn't have attacks at all and should instead focus completely on defense and counterattacks.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block | Unarmed 0 | |
Aikido Stance | Unarmed 0 | Static Buff | Blocked damage reduced by 100% of Dexterirty
Block Counter Throw | Unarmed 0 | Unarmed Block Counter | Down duration: 1, Knockback distance: 1
Dodge Counter Throw | Unarmed 2 | Unarmed Dodge Counter | Down duration: 1, Knockback distance: 1
Intermediate Aikido | Unarmed 3| Static Buff | +1 Block attempts, +1 Dodge attempts
Grab Break | Unarmed 3 | Grab Break |
Block Disarm Throw | Unarmed 4 | Unarmed Block Counter | Disarms, Down duration: 1, Knockback distance: 1
Dodge Disarm Throw | Unarmed 4 | Unarmed Dodge Counter | Disarms, Down duration: 1, Knockback distance: 1
Advanced Aikido | Unarmed 5 | Static Buff | +1 Block attempts, +1 Dodge attempts

_Important Changes_
- **Removed -50% damage debuff**
The defensive nature of aikido should be enforced by not having offensive techniques and not increasing damage dealt, rather than having a damage debuff. This alone will make it "weaker" than other martial arts. 

- **Added arm block, block damage reduction, and block counter**
Aikido's throws come from a combination of dodging and using [soft style blocking](https://en.wikipedia.org/wiki/Hard_and_soft_(martial_arts)) to evade strikes. This translates to using block and dodge counters in a full defensive style like aikido. The throws also work as a grab defense in real life so I translated that into the game by adding a Grab Break.

- **More Block and Dodge attempts**
Aikido is smooth and efficient style of fight that works against multiple opponents.

_Advantages and Disadvantages_
- Aikido is the most defensive style in CDDA. Having both a block and dodge counter that forces opponents away from you will go a long way to keeping you from getting surrounded. Having a grab break is good for the same reason.

- Aikido has no offensive attacks or damage buffs. On top of that, the counters moving opponents away from you is going to increase the amount of time it takes to kill something. It takes a long time to kill things using aikido

#### Describe alternatives you've considered

_If the style is too strong..._
- Reduce the Block and Dodge attempts by 1 each
- Reduce blocked damage
- Don't reduce the damage done.

_If the style is too weak..._
- Increase the Down duration of the counters
- Increase the blocked damage from Dexterity 
- Add a small Dodge skill bonus
- Do not add offensive techniques

#### Additional context

_References:_
[Aikido wikipedia page](https://en.wikipedia.org/wiki/Aikido)
[Hard and soft (martial arts)](https://en.wikipedia.org/wiki/Hard_and_soft_(martial_arts))
[Aikido Demonstration](https://www.youtube.com/watch?v=ugsS2_Z0wpA)
[Aikido Strikes](https://www.youtube.com/watch?v=NPbZMcI9a88)

### CODE REVIEW

**Comment by Hymore246** [comment]
Jenkins rebuild

**Comment by Hymore246** [comment]
Jenkins rebuild

**Comment by kevingranade** [comment]
Playtest:
pretty basic character, stats 8, except dex which I bumped to 10
Unarmed/melee 0, dodge/block 0
Vs a single zombie I took completely minimal damage.
As expected, progress was pretty slow, but the rate of dodging meant I was never in danger except potentially from a bite, even then the ability to slip out of grabs made that minimal.
Stamina also hardly moved, meaning tons of excess ability to maneuver.

First impression is entry level needs to be toned down a bit (this honestly might apply to all unarmed, I haven't compared vs no style).  I expect to take noticeable damage from a basic zombie on turn 0 at no skill.

**Comment by kevingranade** [comment]
Repeated with two zombies at the melee 1 / unarmed 1 state, and the result was similar.
Due to the counter-throws I spent a LOT of time only engaged with one zombie or the other, this is very thematic for Akido, but it's happening way too early in the progression at just skill lvl 1.

Repeated again vs three zombies after bumping skills up to melee 3, unarmed 3 and dodge 1.
Additionally I had started to accumulate some pain, so I was slowed but without stat loss.
This time things did not go nearly as well, the counter throws couldn't keep up with three zombies and I spent most of the time engaged with two of them, which triggered a pain/speed spiral resulting in me taking significant amounts of damage.  That outcome was fine, keeping in mind I was intentionally playing really dumb and just standing in place hitting whoever was in reach that had the least remaining HP.  I also suffered some bites, which is expected since there's no real special handling for it.  I'll have to double check, but I feel like with some tactical play a running fight with three zombies would be totally doable at this level.

My impression is unchanged, at the beginning Akido seems pretty OP, it doesn't feel like you're a beginner, you're pretty proficient.

**Comment by Hymore246** [comment]
>First impression is entry level needs to be toned down a bit (this honestly might apply to all unarmed, I haven't compared vs no style). I expect to take noticeable damage from a basic zombie on turn 0 at no skill.

I think that has more to do with how effective dodge is calculated. I made a normal survivor with 10 dex and 8 in other stats and 0 dodge skill. His effective dodge skill of 2.1 out of the box. There are a few styles that will buff dodge skill but Aikido isn't one of them.

I've made the following changes. This should make the style a bit less front loaded. 
1. Moved Aikido Dodge Counter from Unarmed 0 to Unarmed 2.
2. Moved Aikido Block Counter from Unarmed 1 to Unarmed 0.
3. Moved Arm Block from Unarmed 1 to Unarmed 0.
3. Moved +1 Block and Dodge attempts from Aikido Stance to a new buff, Intermediate Aikido, which is gained at Unarmed 3.

I am hoping that swapping the block and dodge counters will not impact the style very much.

**Comment by kevingranade** [comment]
Those tweaks seem to have had a significant impact, mindlessly soloing one or two zombies is no longer risk-free.

**Pull request merged**
