### PR TITLE
Add repairs_like to runner pack

### LINKED ISSUE #50604: Should the difficulty of repairing runner packs be reduced?
# Is your feature request related to a problem? Please describe.
Even with a tailor's kit repairing a slightly damaged runner pack required tailoring 7 before success chance = damage chance. The failure rate goes up if the pack is more damaged. This seems excessive considering that crafting a *survivor* runner pack (technically not the same item, but close enough. right?) *from scratch* only requires tailoring 4

pack

# Describe the solution you'd like
Reduce the difficulty of repairing runner packs

# Describe alternatives you've considered
Keep as is

# Additional context

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: eec1398 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary
None

#### Purpose of change

Fixes #50604

#### Describe the solution

Add "repairs_like": "backpack"

#### Describe alternatives you've considered

none

#### Testing

* The game loads
* The backpack is much easier to repair

#### Additional context

none

### CODE REVIEW

**Comment by actual-nh** [comment]
The survivor's runner's pack doesn't have repair stats?

**Comment by LaVeyanFiend** [comment]
> The survivor's runner's pack doesn't have repair stats?

This is the regular runner's pack, the survivor's version is craftable & thus its repairability is based on its tailor level.

**Comment by actual-nh** [comment]
I was wondering why not repairs_like: survivor_runner_pack (or whatever). Quite possibly the results would be rather similar.

**Comment by hexagonrecursion** [comment]
backpack: difficulty 3
https://github.com/CleverRaven/Cataclysm-DDA/blob/b7a789fd9b36838f1e94dc29494b8fe7691011e4/data/json/recipes/armor/storage.json#L135-L141
survivor_runner_pack: difficulty 4
https://github.com/CleverRaven/Cataclysm-DDA/blob/b7a789fd9b36838f1e94dc29494b8fe7691011e4/data/json/recipes/armor/storage.json#L1036-L1042
I'll add "repairs_like": "survivor_runner_pack" as suggested

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
