### PR TITLE
[Magiclysm] Add mutations to manatouched

### PR DESCRIPTION
**Pull request by OromisElf**
#### Summary
Mods "add more mutations to magiclysm"

#### Purpose of change

Increase the number of mutations in the manatouched mutation line. My test character was only able to reach a mutation level of ~~48~~ 52 with all pre-threshold mutations ( weak, Albino, reflex photomore, Mana Luminance, Weakening, deterioration, Lesser Mana Sensitivity, Mana Sensitivity, Greater Mana Sensitivity, Mana Regeneration, Lesser Mana Efficiency, Mana Efficiency, Greater Mana Efficiency ) while the code for mutations suggest you need a 50 for strength 3 dreams. ~~During this test I also noticed that Mana efficiency doesn't actually add to the mutation level at all; not even for non-manatouched mutation lines.~~

#### Describe the solution

Added the following existing mutations to the Manatouched category:

- weak stomach
- bad back
- lightweight
- extremely smart
- ~~perceptive~~ light bones

#### Describe alternatives you've considered

not adding perceptive

#### Testing

On a test character without robust genetics I was able to go post threshold with only mana efficiency as an actual mana related mutation which is definitely a thing to consider but with all the mutations it's technically possible to reach a mutation level of ~~88~~ 92 in Manatouched with only pre-threshold mutations.

### CODE REVIEW

**Comment by actual-nh** [comment]
How about removing the `NON_THRESH` flag from the Mana Efficiency mutations?

**Comment by OromisElf** [comment]
that sounds like it could work; will come back to this

**Comment by OromisElf** [comment]
I removed non-thresh for normal and greater efficiency (since that one didn't contribute at all) and the ingame mutation level info says that there's still no mutation level at all

**Comment by actual-nh** [comment]
> I removed non-thresh for normal and greater efficiency (since that one didn't contribute at all) and the ingame mutation level info says that there's still no mutation level at all

Were they starting traits?

**Comment by actual-nh** [comment]
> that sounds like it could work; will come back to this
> Edit: I am definitely confused by what's going on because a lot of mutations that have that flag are actually contributing to the mutation level

They can contribute to it indirectly - the code first scans through all the mutations, including those, and adds the prerequisite/prerequisite2/replacement mutations's categories if THEY don't have the flag and are not base traits.

**Comment by actual-nh** [comment]
From mutation.cpp:
```
        int booster = 0;
        if( mutation_category == mutation_category_id( "URSINE" ) ||
            mutation_category == mutation_category_id( "ALPHA" ) ) {
            booster = 50;
        }
```
@KorGgenT: Does this need to be JSONized as a list, and manatouched added?

**Comment by OromisElf** [comment]
I don't think they were starting traits; I may have selected them when I started the character but I thought this wouldn't matter after I removed them all with debug menu and then only added them with debug menu; give me a second

**Comment by actual-nh** [comment]
52 is capable of crossing the threshold, but it's low as far as I can tell - URSINE and ALPHA get a bonus of +50 in mutation.cpp's `test_crossing_threshold` function, to make them a bit more likely. It's possible these bonuses need to be JSONized and manatouched added.

Did you figure out the 52 and 88 with or without the NON_THRESH flags?

**Comment by OromisElf** [comment]
*92 and yes I actually remembered to put non_thresh back in there *pats self on back*
and yeah I should've figured that thing about starting traits sooner because I know that you need 50 for crossing the threshold (I read some code for that) and had a post-threshold manatouched survivor; it's just... I was save-scumming for that one and at some point gave up in defeat because for the life of me no amount of loading would give me something other than deterioration and/or Albino;
I left the info about needing 50 for strength 3 dreams in the og post since I figured it out I might as well save someone the work :D

the other mutation categories when you have all mutations in the manatouched tree? give me a second

**Comment by actual-nh** [comment]
Even the original version (with 52 points in manatouched mutations) should have a reasonable chance of breaching threshold (52/171 = about 30.4%). I think the problem is that it's so close to 50 (and it has to be _above_ 50 to work) that anything getting left off (including due to being a starting trait for that character) probably drops it to 50 or below.

Three things to try:

- Remove `NON_THRESH` from MANA_ADD# and MANA_REGEN# (note that the flag doesn't do anything for post-threshold mutations like `MANA_REGEN3`);
- Add `MANATOUCHED` to MANA_MULT#;
- Do both, and also remove `NON_THRESH` from MANA_MULT#.

BTW, you may wish to change the PR's title to something like "[Magiclysm] Add mutations to manatouched", since otherwise it looks like you're wanting to add new mutations appropriate for Magiclysm.

**Comment by OromisElf** [comment]
I will try today (probably), thanks for all the suggestions; they sound promising :D
Light Bones sounds like a nice one and I think I'd rather try to add that over perceptive to the manatouched line

**Comment by actual-nh** [comment]
> I will try today (probably), thanks for all the suggestions; they sound promising :D
> Light Bones sounds like a nice one and I think I'd rather try to add that over perceptive to the manatouched line
> 
> Edit: so after a while putting those three things to try into motion and testing a bit with them and freshly generated as well as pre-existing characters with and without things like mana_add as starting traits one thing became more than clear to me: I kinda missed what I am testing for? o.o

Oops! For whether the resulting mutation category value can get to breaching even with a few things being missing (or that are starting traits, which in some respects is worse than missing given the current code... see #48172).

**Comment by OromisElf** [comment]
ah I see; that sounds like some interesting tests; give me a few

**Comment by actual-nh** [comment]
Oh - and note there is one test that tries to make sure the percentage chance for breaching, after you're over 50, is between 0.2 and 0.4. It's designed to make sure a category has some in common with others (thus below 0.4 for particular_category/all_categories) but is sufficiently different also (thus above 0.2 for particular_category/all_categories).

**Comment by OromisElf** [comment]
I can't understand what the meaning of your last comment is, which might be entirely because it's 4:32 am here and I'm _deadly tired_ xD

**Comment by KorGgenT** [comment]
just as a note, you guys are misinterpreting what NON_THRESH is, i think. its purpose is to ignore those mutations when in the test because they are too "dilute" for lack of a better term, they have too many categories attributed to them. i'm not particularly in favor of adding extremely smart to manatouched - they should be mana and magic based, yes, but intelligence sort of applies to everything.

**Comment by OromisElf** [comment]
thanks for the heads up on non_thresh; and I didn't include extremely smart solely based on the fact it'd increase mana; it's just when you think "wizard" you probably also think physically weak and mentally strong
Would you be more okay with it if it was one of the two prior smartness-mutations?

**Comment by actual-nh** [comment]
> I can't understand what the meaning of your last comment is, which might be entirely because it's 4:32 am here and I'm _deadly tired_ xD

Understand! Are you having an easier time with it now?

**Comment by OromisElf** [comment]
> quote from tests/mutation_test.cpp
ooooh, that makes much more sense to me now. I haven't made like 100s of test cases but from what I tested for my table it seemed to me that if you're missing a positive mutation (see "48 points (missing lesser mana regeneration)" in my table) that it becomes a drag to cross over and with a negative mutation missing it looked like it became "too easy" according to those design comments. I want to increase the amount of mutations for manatouched so that if you're missing lesser (and therefore normal) mana regen it won't take 16 serums to get about 2-3 mutations and instead get something fun while you're at it like a bad back :D

>note there is one test that tries to make sure the percentage chance for breaching
Does that actively change things about mutation lines?

**Comment by actual-nh** [comment]
> > quote from tests/mutation_test.cpp
> ooooh, that makes much more sense to me now. I haven't made like 100s of test cases but from what I tested for my table it seemed to me that if you're missing a positive mutation (see "48 points (missing lesser mana regeneration)" in my table) that it becomes a drag to cross over and with a negative mutation missing it looked like it became "too easy" according to those design comments. I want to increase the amount of mutations for manatouched so that if you're missing lesser (and therefore normal) mana regen it won't take 16 serums to get about 2-3 mutations and instead get something fun while you're at it like a bad back :D

The comments actually aren't talking about negative mutations - more what proportion of (pre-threshold) mutations is shared with other categories.

> > note there is one test that tries to make sure the percentage chance for breaching
> Does that actively change things about mutation lines?

I'm not sure what you mean.

**Comment by OromisElf** [comment]
> I'm not sure what you mean.

I guess what I want to know is: what does the test do if it detects a mutation line is below .2 or over .4?

**Comment by actual-nh** [comment]
> > I'm not sure what you mean.
> 
> I guess what I want to know is: what does the test do if it detects a mutation line is below .2 or over .4?

Then the test fails. (For most mods other than the default ones, this would not actually happen - it's more of a strong guideline - but Magiclysm is included in one of the Travis test builds.)

**Comment by actual-nh** [comment]
I've added Content Freeze because, before the need for this to be agreed upon, I think it's going to require some further fixes to and analysis of the mutation category code. I'll try to work on the more general problem after 0.F is out.

**Pull request merged**
