### PR TITLE
[CR]Explosion rework

### LINKED ISSUE #7105: 3-dimensional Z-level support, Fields and Effects [$80]
Master Ticket #6822

This will be a "bounty issue" for the development of z-line track development.

This has following requirements:
Fields and Effects should spread across z-levels if appropriate. Examples include:
-Fire climbing structures
-Smoke fields rising over time. or at least extending upwards, and fire generating significant quantities of smoke above rather than next to the fire.
-Explosions occurring across three dimensions
-Heavy fields, such as liquids, dropping if there is nothing to support them.

<bountysource-plugin>
---
There is a **[$80 open bounty](https://www.bountysource.com/issues/1548620-3-dimensional-z-level-support-fields-and-effects-80?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #7105

Reworked explosions to use a flood-fill-like system. Explosion propagates semi-randomly from the central point, being stopped by tough obstacles. Explosion shape is mostly circular.

The explosion can break through obstacles during propagation. The chance of this happening increases if the explosion is "confined" (doesn't have many passable neighbors). This is supposed to be a sort of shaped charge system to make bashing tough walls (lab walls, for example) more sensible. This can make explosions destroy terrain up to 3 times more powerful than in current master.
Could still use a buff, because dynamite barely scratches solid rock.

Explosion size is much less power-dependent than in master. Currently the effective range is a logarithm of power. This can be changed - just went with it for now because it "looked good".

Termination of propagation is tied to force left. This has a cool effect of breaking windows at the edge of even a weak explosion, but not damaging much else.

Propagation up and down works. Moving across z-levels is arbitrarily penalized (8 times as costly as going horizontally). This flattens the holes quite a bit: ANFO crater is 2 levels deep, even though horizontally it is bigger than in master (although less effective at the edge of the range).

The resulting explosion requires special handling during drawing. 
- [x] Drawing in tiles mode
- [x] Balancing
- [x] Wreck the proper side of the floor/ceiling at the edge of the blast
- [x] Nerf vehicle tank explosions
- [x] Silence some of the bashing
- [x] Draw in multiple colors to show how strong the explosion actually is (Optional)
- [x] Draw shrapnel as lines, because it animates very slowly when drawn as bullets (Optional)

### CODE REVIEW

**Comment by kevingranade** [comment]
Really cool sounding stuff.  I'm not sure this is needed though:
> Could still use a buff, because dynamite barely scratches solid rock.

Dynamite is generally only going to damage thick, solid rock if you drill into the rock and pack the dynamite into it.  Just placing a stick of dynamite against a wall isn't going to do much.

**Comment by Rivet-the-Zombie** [comment]
I like this one.

**Comment by Zireael07** [comment]
Woo!

**Comment by Coolthulhu** [comment]
>Dynamite is generally only going to damage thick, solid rock if you drill into the rock and pack the dynamite into it.

I'll leave the current bonus then. Still, leaving the bashing buff in makes sense, because in current master the bashing force is roughly 3 times weaker than the damage it causes to creatures. Here it also is weaker, unless the explosion is confined, when it gets comparable to damage to creatures.

**Comment by KiwiTrinsic** [comment]
Very cool looking!

**Comment by Coolthulhu** [comment]
I did nerf vehicle tank explosions quite a lot. From "way bigger than a mininuke and ANFO combined", to a more sensible "a big bomb". Mostly because a gasoline tank isn't really a bomb and isn't made to explode.

Also made diesel tanks explode less powerfully than gas tanks. IRL diesel explodes way less readily than gasoline (gas to be heated or compressed first). Replicating the exact physics could be a lot of work, so I just lowered the numbers.

Old formula: `power = amount / 40`
New formula: `power = pow( amount, diesel ? 0.4 : 0.45 )`

I balanced the numbers so that a heavy-power-armored hulk of a man (20 strength) can survive an explosion of an adjacent full external diesel tank (but not the resulting fire). Full gasoline tank would kill him just fine.

**Comment by Coolthulhu** [comment]
Should be ready now.

Explosions are generally nerfed in damage, but have greater ranges. This means that getting 'naded shouldn't kill player so easily, but getting into cover won't be as simple as taking 2-3 steps away.

Shrapnel wasn't nerfed much - I only made it stop piercing walls (in master, shrapnel can't be stopped by a wall). This means that a shrapnel from ANFO charge can easily rip off a leg at the edge of its range. I changed shrapnel drawing to use lines except for the last tile. As a result it draws much faster without being less informative.

Drawing in tiles mode isn't perfect, because we currently have only two explosion tiles: edge and corner. To draw it nicely, we'd need: edge, corner, T-connector, center and unconnected.

Drawing doesn't represent the expansion of explosion. It is calculated after the entire explosion happens, basing it on affected tiles.

Jenkins complains about some lua code, but I didn't touch any in the last commit.

**Comment by kevingranade** [comment]
Will probably want to nudge balance a bit more in various ways, but this is too cool not to merge ASAP.

**Comment by Coolthulhu** [comment]
Thanks

Yes, the balance isn't perfect, but it shouldn't be worse than it was in most cases.

The few cases that might require special attention are high-powered explosives that create craters and shrapnel, which doesn't scale in damage with distance traveled and is also very powerful compared to the blast itself.

**Pull request merged**
