### PR TITLE
Survivor telescope

### PR DESCRIPTION
**Pull request by jokermatt999**
Adds a craftable collapsible telescope that functions like binoculars. 

You know, in case you eat your binoculars because you left your internal furnace running. ;)

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. Though I would assume that actually making it craftable is your next step? :V

**Comment by jokermatt999** [comment]
Sonuva-

Where did I add that recipe to then?!

**Comment by chaosvolt** [comment]
I ate it? ;w;

No idea.

**Comment by jokermatt999** [comment]
I made this update out of inedible code matter.

**Comment by chaosvolt** [comment]
That explains the taste. o3o

And hmm, looks interesting.

**Pull request merged**
