### PR TITLE
Remove the requirement to link with clangTidy

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
None

#### Purpose of change
A requirement to link against `clangTidy` was added as part of the transition to LLVM 17 (#71429), but it breaks the build against LLVM 17 for me locally.

#### Describe the solution
After some discussion below, it seems like @BrettDong and I have found an alternative solution that works for both of us.  I've updated this PR accordingly.

This has to do with a difference between the default linking behaviour on Linux and macOS.

#### Testing
This is the test.

#### Additional context

### CODE REVIEW

**Comment by jbytheway** [comment]
Seems to be working fine ([CI run](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8130978922/job/22219792605?pr=72140)).

So I will mark this as a draft to avoid it getting merged accidentally while I wait to hear from @BrettDong on what inspired the change.

**Comment by BrettDong** [comment]
I got a huge number of "undefined references" linking error when building the plugin locally on my macOS system. The compiler used is Apple Clang from Xcode, and the LLVM library is installed from Homebrew package manager.

**Comment by jbytheway** [comment]
Had you previously built successfully on the same system against LLVM 16?

**Comment by BrettDong** [comment]
Building with LLVM 16 was successful but linking error occurs with LLVM 17.

**Comment by BrettDong** [comment]
A portable way to create our plugin target in CMake is probably to use `llvm_add_library()` function
https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/cmake/modules/AddLLVM.cmake#L372-L401

**Comment by jbytheway** [comment]
I also did some poking around, I wonder if we might be able to work around the issue using `-undefined dynamic_lookup` when linking the plugin.

This is based on some other GitHub issues.  See, for example, [this comment](https://github.com/nasa/cFE/issues/476#issuecomment-579436106) and [this PR](https://github.com/eshard/obfuscator-llvm/pull/5/files).

If this is the issue, though, I'm not sure it explains why LLVM 16 worked but 17 doesn't.

**Comment by BrettDong** [comment]
I can successfully build and load the plugin in clang-tidy 17 on macOS with this patch
```diff
diff --git a/tools/clang-tidy-plugin/CMakeLists.txt b/tools/clang-tidy-plugin/CMakeLists.txt
index 46f3021206..4d5f5e35fb 100644
--- a/tools/clang-tidy-plugin/CMakeLists.txt
+++ b/tools/clang-tidy-plugin/CMakeLists.txt
@@ -55,7 +55,9 @@ if (CATA_CLANG_TIDY_EXECUTABLE)
 else ()
     set(CataAnalyzerName CataAnalyzerPlugin)
     add_library(${CataAnalyzerName} MODULE ${CataAnalyzerSrc})
-    target_link_libraries(${CataAnalyzerName} PRIVATE clangTidy)
+    if ("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
+        target_link_options(${CataAnalyzerName} PRIVATE -undefined dynamic_lookup)
+    endif ()
 endif ()
 
 target_include_directories(${CataAnalyzerName} SYSTEM PRIVATE
```

**Comment by jbytheway** [comment]
Awesome.  I'll update this PR accordingly.

**Pull request merged**
