### PR TITLE
inventory_ui: only hide entries added recursively

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary
SUMMARY: None

#### Purpose of change
Items in collapsed containers are hidden in inventory UIs even if their parent isn't in the list
Fixes: https://github.com/CleverRaven/Cataclysm-DDA/issues/52706
Items in in nested containers are still shown even if the top container is collapsed
Fixes: CleverRaven/Cataclysm-DDA#52699
Fixes: https://github.com/CleverRaven/Cataclysm-DDA/issues/52722

#### Describe the solution
Track the topmost visible parent and gate visibility checks on its presence in the list.

#### Describe alternatives you've considered
Looping over all entries in `inventory_selector::prepare_paging()`: I get sick just thinking about this

#### Testing
For https://github.com/CleverRaven/Cataclysm-DDA/issues/52706:
Start with a backpack, a loaded flashlight, a 3L jar, a fruit jam, and a bandage. Insert the jam in the 3L jar, then the bandage and 3L jar in the backpack, then collapse the backpack.
1. The fruit jam and bandage should still show in the `E`at menu
2. The flashlight should still show in the `a`ctivate menu, but not in the `U`unload menu (unless you un-collapse the backpack first)

Try again after dropping the backpack on the floor or stashing it in a vehicle, or in another container.

For CleverRaven/Cataclysm-DDA#52699:
Start with a backpack and collapse it. Insert a fruit jam into a 3L jar, make sure the jar is not collapsed, then insert the jar into the backpack. The fruit jam should be hidden in the player inventory menu. Both the jam and the jar should show in the `Open item` menu AND you should be able to independently (un)collapse the jar.

#### Additional context
This only works if items are added in a top-down order, which should be the case everywhere at the moment.

### CODE REVIEW

**Comment by kevingranade** [comment]
Ok good I was looking at this and had come up with scanning for the parent and a terrible "disable it on a per-menu basis", but that turns out to be an equally bad tarpit.  Your approach here seems workable.  My other thought in this direction is adding a parents field to inventory entry and populating that... somehow.

I might be missing something here, but the fact that entries can aggregate across several different items seems problematic, if the first item listed in an entry is hidden, the entire entry is hidden, that seems wrong and difficult to fix.  Hopefully I'm just missing something about the preconditions enforced by class construction.

**Comment by andrei8l** [comment]
>  if the first item listed in an entry is hidden, the entire entry is hidden, that seems wrong and difficult to fix

AFAICT contained items don't aggregate across pockets, but let me know if you have a specific demo case. You're right that the fix wouldn't be easy (I'm specifically trying to avoid looping or building parent links in `inventory_entry`)

**Comment by andrei8l** [comment]
I've reverted my second commit since it introduces more edge cases than it fixes ([commit](https://github.com/andrei8l/Cataclysm-DDA/commit/59b80829b050f836fc9d2b665ea2aec9b442af35) for reference). #52699 will have to stay broken for now :(

**Comment by andrei8l** [comment]
After some consideration, I was able to address both #52706 and #52699 with only a minor change to the base idea.

**Comment by andrei8l** [comment]
I just noticed a new bug with (un)collapsing after filtering items. I have a preliminary fix [here](https://github.com/andrei8l/Cataclysm-DDA/commit/82ceb72e2776edbdc10e490b33e02c64d509e45f) but I think I'll open a separate PR for it if this is accepted.

**Pull request merged**
