### PR TITLE
[Magiclysm] Add fantasy species starting option

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "Add fantasy species starting option"

#### Purpose of change

The Magiclysm roadmap mentioned the possibility of starting as an elf, dwarf, etc., so here's my attempt at implementing part of that.

#### Describe the solution

Add Elf (Species), Dwarf (Species), and Lizardfolk (Species) as hobbies to make them compatible with various starting professions. Each starts with a series of mutations designed to evoke the characteristics of generic fantasy elves and dwarves and lizard people, as well as new thresholds (Elf--Firstborn, dwarf--Child of Stone, lizardfolk--Scaled One). While I originally wanted to tie them in to existing mutation paths, I think new paths are better for future content because they allow others to draw a distinction (in dialogue or NPC reactions) between post-Cataclysm mutants and pre-Cataclysm sapient species. 

The mutations are a mix of positive and negative--elves get better hearing and vision and only need to sleep for 5 hours with their eyes open, but junkfood intolerance and flimsy; and dwarves have infrared vision, faster crafting, and better strength but sun sensitivity and heavy sleeper, for example, while lizardfolk start with claws, teeth, and a predatory mindset and can breathe underwater, but are coldblooded with disturbing hissing voices and cannot eat grain (they are also Large, because the default human is 62L/82kg while the default mon_lizardfolk_warrior is 80L/100kg). 

Any feedback on the exact distribution of mutations is welcome!

#### Testing
Species appear, can be selected, and provide the appropriate traits.

#### Additional context

Dwarven Build should probably have the SMALL flag, but until the clothing distribution is redone so that human children have smaller clothes, I think it's unreasonable to start them that way (since they wouldn't be able to fit into the clothes of their starting profession)

### CODE REVIEW

**Comment by Maleclypse** [comment]
I think this is a fairly elegant solution given that you have a different scenario than what I did in Xedra Evolved.  Mine are all professions but the whole XE concept is that they are freshly born creatures in a post cataclysm world, that wouldn't make any sense in Magiclysm for Elf and Dwarf to be AD&D or Heroquest professions.

**Comment by Standing-Storm** [comment]
> I think this is a fairly elegant solution given that you have a different scenario than what I did in Xedra Evolved. Mine are all professions but the whole XE concept is that they are freshly born creatures in a post cataclysm world, that wouldn't make any sense in Magiclysm for Elf and Dwarf to be AD&D or Heroquest professions.

<3 for the Heroquest reference.

Based on the Magiclysm lore, I'm trying to take the Shadowrun approach of "Your elf could have been an investment banker or a baseball player before the Cataclysm," so while it's conceptually a little weird to have elf as a "hobby," mechanically I think it's the best way to represent it.

**Comment by KorGgenT** [comment]
> > I think this is a fairly elegant solution given that you have a different scenario than what I did in Xedra Evolved. Mine are all professions but the whole XE concept is that they are freshly born creatures in a post cataclysm world, that wouldn't make any sense in Magiclysm for Elf and Dwarf to be AD&D or Heroquest professions.
> 
> <3 for the Heroquest reference.
> 
> Based on the Magiclysm lore, I'm trying to take the Shadowrun approach of "Your elf could have been an investment banker or a baseball player before the Cataclysm," so while it's conceptually a little weird to have elf as a "hobby," mechanically I think it's the best way to represent it.

i feel like shadowrun rules are perfectly cromulent for fantasy races

**Comment by Standing-Storm** [comment]
Nearly ready to go barring a few fixes

I did find a bug while doing this, though--If you try to pick both dwarf and elf, they have conflicting mutations so it doesn't work. IF you try to pick dwarf and lizardman, however, not only does the game let you do that you get two threshold mutations:

image

I have a fix for this specific problem but that'll deserve a bug report

**Comment by Standing-Storm** [comment]
Well, I fixed that specific problem in this case but if you try to de-select a species after selecting it...
image

**Comment by ashGlaw** [comment]
This is a cool idea! Hope to see the orcs and goblins get some love too

**Comment by Standing-Storm** [comment]
> This is a cool idea! Hope to see the orcs and goblins get some love too

I have ideas for orcs, goblins, and ravenfolk in the future, but this current one is long enough to start.

**Comment by Standing-Storm** [comment]
Alright, this should be ready to go

**Comment by Standing-Storm** [comment]
If someone ever makes a separation between "mutation category" and "playable species" I'll be able to clean this up a lot, but for now, Elf, Dwarf, and Lizardfolk are going to show up on a lot of mutations they don't actually have.

**Pull request merged**
