### PR TITLE
Fix the casing ejection behavior of The Disorder sledgehammer 

### LINKED ISSUE #57683: Disorder sledgehammer reload_eject flag not working correctly
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/pull/55820
This PR implemented the code for ammo-consuming melee weapons to work, right now it's only used by the Disorder which consumes .22 blanks (sold at hardware stores irl, believe it or not) to drive a piston for extra impact on good hits.

When the piston fires the ammo is consumed correctly, and right after that in the code block it checks for the reload_eject flag and attempts to place a .22 casing in the sledgehammer that will be removed when the player reloads it.

Something isn't working right when the .22 casing is placed into the magazine pocket, because it's not actually going into the magazine pocket as expected. If you reload it after it fires off, you don't get a .22 casing back like you should. Instead the casing will drop to the ground next time you pick something up.

Honestly this makes me scratch my head and leaves me confused. I think something is different about how guns handle their magazines and reloading them, and how everything else handles their magazines and reloading them.

### Steps to reproduce

Get 2 .22 blanks and 1 the Disorder.

1. Load the Disorder and smack zeds until it fires off
2. Reload the Disorder with a new .22 blank, check your inventory and surroundings for a .22 casing.
3. Find something to pick up (might only work if you use the advanced inventory menu) and the missing .22 casing should appear on the ground nearby.

### Expected behavior

The implementation should make the spent casing eject into your inventory when you reload the Disorder like if you'd reloaded a revolver with spent casing.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1415 (20H2)
- Game Version: 7a89bbe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Bugfixes "Fix the casing ejection behavior of The Disorder sledgehammer"

#### Purpose of change
Fixes #57683

#### Describe the solution
Adjusted casings_handle() to work on tools, instead of only working on guns. 
Changed the item type of Disorder to "tool" instead of "generic"

#### Describe alternatives you've considered
Removing the check that makes the casing handler only work on guns. Doing this seems like it would almost certainly break _something_, so I'd prefer not to do that.

Changed the item type of Disorder to "gun." Doing this requires adding a whole bunch of gun data that would basically turn it into a ranged weapon, which is not what I want to do.

#### Testing
~~I've been having some issues with visual studio, so I haven't been able to properly test it myself yet. Once I can, the steps will be:~~
1. spawn in the Disorder, some 22 blanks, and some crawling zombies. (also spawn and put on a backpack)
2. load the Disorder with a 22 blank.
3. hit crawling zombies with the Disorder until the special technique procs.
The Disorder should now contain an empty casing for the 22 blank.
4. (R)eload the Disorder.
The empty casing should now be in your backpack or some other place in your inventory.
5. Success!

Edit: testing is done, everything works correctly.

#### Additional context
Note that trying to pick up an item between steps 3 and 4 will cause the empty casings to fall on the ground. This happens with other weapons too, so it seems like a separate issue.

### CODE REVIEW

**Comment by catdach** [comment]
Ok, I got visual studio to behave for a while. Unfortunately it seems that the disorder refuses to expend its ammo at all. I also tried using it on the master branch and sure enough; I can't get it to expend its ammo, even when the technique procs. 

So it's not a result of my PR, but I'm not even able to replicate the bug that this PR is meant to fix. I swear it worked fine a couple months ago. 

so...yeah 🤷

**Comment by bombasticSlacks** [comment]
Hmmm yeah it worked when I originally PRd it 🤔

If this doesn't solve the issue can you mark it as draft so no one yolo merges it? I'm not apposed to this being fixed but if you've tested this and it doesn't solve it then yah know.

**Comment by catdach** [comment]
Just to clarify; this PR _should_ fix the casings ejection issue, but it's impossible to test unless the weapon actually produces casings.

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/melee.cpp#L1638 I think it's this line, thanks for letting me know, I'm gonna try and write a simple unit test tonight for it expending ammo 😄

**Comment by catdach** [comment]
Finished testing. After https://github.com/CleverRaven/Cataclysm-DDA/pull/59474 everything seems to work correctly 👍

**Pull request merged**
