### PR TITLE
Road warrior

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
A new type of advanced survivor for the winter Ambush scenario.

It's called the Road Warrior and it's pretty much Mad Max without a car.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Rather low on wintery gear

**Comment by Rivet-the-Zombie** [comment]
The leather does a halfway decent job of keeping them warm, but you're definitely correct; warmer clothing is a definite priority with this profession.

**Comment by Coolthulhu** [comment]
Looks like it's missing from the start lists because I can't pick it.

**Comment by Coolthulhu** [comment]
Also kinda weird to mix Mad Max with snow.

**Comment by pisskop** [comment]
Im rather suprised how underdressed many professions are to be honest.

Perhaps a summer/winter version of all professions would be nice?

**Comment by codemime** [comment]
> Perhaps a summer/winter version of all professions would be nice?

Yeah, extended `items` list would be really useful:
```JSON
"items": {
    "both": [
        "pants_leather",
        { "winter": "coat_winter", "default": "jacket_leather_mod" },
        { "winter": "hat_knit" },
```
For all omitted seasons use `default` (or none, if `default` was omitted too).

**Comment by Rivet-the-Zombie** [comment]
@coolthulhu, it's only accessible from the 'Ambush' scenario.

**Comment by Coolthulhu** [comment]
> it's only accessible from the 'Ambush' scenario.

Could be my fault, I might have checked the other winter scenario

> I agree, but the winter Ambush scenario is currently the only scenario that starts you out well after the apocalypse.

Could we have "next summer" option then? It would be fairly simple to add. In `game.cpp` there is `start_calendar` which sets up the date based on flags. Adding a `"NEXT_YEAR"` flag would be very simple:
```
void game::start_calendar()
{
calendar::start = HOURS(ACTIVE_WORLD_OPTIONS["INITIAL_TIME"]);
if( scen->has_flag("NEXT_YEAR") ) {
    calendar::start += DAYS( calendar::season_length() );
}
// Rest of the function here
```

Though this would require a new scenario.

Though Mad Christmax (with furs instead of leather) would fit well in the crazy mod.

**Comment by Rivet-the-Zombie** [comment]
>Could we have "next summer" option then?

Yeah, I can do that.

**Pull request merged**
