### PR TITLE
Increased shot ammo dispersion using Firestorm01X2's method and buffed 20x66mm slug

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Added 800 dispersion to .22 rat-shot, 40mm shot, 20x66mm shot, and .410 shot ammo and most of their copy-from derivatives lacking custom dispersion; buffed 20x66mm slug and derivatives to 800x0.1 dispersion

### CODE REVIEW

**Comment by Wishbringer** [comment]
Regular shotgun slugs should have something similar, rather than just adding 900 dispersion to it, which makes it virtually useless.

**Comment by Wishbringer** [comment]
@Zireael07
"shot_slug" isn't using proportional at all for dispersion or damage, just a flat "dispersion": 900 .
Also shouldn't all slugs have a count of 1, or doesn't that matter unless the SHOT flag is used?

**Comment by Firestorm01X2** [comment]
Also there is another way: rebalance ALL shotguns itself :)

**Comment by Wishbringer** [comment]
On the other hand, slugs has little to do with other shotgun ammo types, so proportional may actually be worse, since they become linked.

**Comment by BorkBorkGoesTheCode** [comment]
Bad rebase.

**Pull request closed without merging**
