### PR TITLE
Toggle compass

### PR DESCRIPTION
**Pull request by nsklaus**
### How to use
toggle compass on/off with default key "?"

#### Summary
 ```SUMMARY: Interface "toggle compass"```  

#### Purpose of change
for those with small resolution, 
it is the same kind of toggle as for the pixel minimap, 
it allows to toggle the compass on/off in order to gain a bit of space on screen and be able to read more lines from the messages log.

#### Describe the solution
i added a new hotkey, new action toggle_compass.
please see attached screenshots.

#### Additional context
screenshot_20190126_090040
screenshot_20190126_090047
screenshot_20190131_142622

### CODE REVIEW

**Comment by nsklaus** [comment]
> Could you please provide screenshot with monsters nearby?

sure, here they are, in all 640x400 glory:
screenshot_20190126_181855
screenshot_20190126_181900

**Comment by Night-Pryanik** [comment]
Maybe leave the monsters indicators (below the compass) even with compass turned off?

**Comment by nsklaus** [comment]
> Maybe leave the monsters indicators (below the compass) even with compass turned off?

that's kind of void the point of this PR. this is to allow users on very low res to get back a little bit of screen space for them to be able to read more of the message log. most user will not run on such low res, and will always have compass and map turned on.

**Comment by nsklaus** [comment]
> In my opinion the `?` key should be reserved for help related commands, having something else bound to `?` would be counter-intuitive. Any chance you could change it to some other key?

you're correct, i will change to another key. thanks for the heads up.

**Comment by Night-Pryanik** [comment]
> that would kind of void the point of this PR. this is to allow users on very low res to get back a little bit of screen space for them to be able to read more of the message log. most users will not run on such low res, and will always have compass and map turned on.

I suppose that even on high res there could be someone that would like to hide the compass (as there is a minimap), but have monsters' indicator around - to see what particular monsters are there in the vicinity.

**Comment by nsklaus** [comment]
"Drink or driving, you have to choose" :)

**Comment by RobertoVGoulart** [comment]
Maybe a single "Monsters spotted" line when the compass is off would work well enough to alert players but still take less space than the full compass?

**Comment by nsklaus** [comment]
> Maybe a single "Monsters spotted" line when the compass is off would work well enough to alert players but still take less space than the full compass?

that the safe option you've just described.

**Comment by nsklaus** [comment]
> Will close #26706 when/if merged.

good catch :)

**Comment by mount2010** [comment]
Perhaps add the option to hide the compass in a menu for those who can't press °? I know you can always configure keybinds, but the game should be 100% playable by default, with no modification... just an idea.

**Comment by nsklaus** [comment]
> Perhaps add the option to hide the compass in a menu for those who can't press °? I know you can always configure keybinds, but the game should be 100% playable by default, with no modification... just an idea.


i've heard that somehow android version have specificities about input but, android specificities shouldn't impact pc version. android related stuffs should be done on android port in a general sense.

that being said, 
i've just looked and indeed, pixel minimap can be disabled from the option screen. so maybe toggling compass too should be available from there. i'll be updating this PR to provide a new option to enable/disable the compass from the settings screen.

**Comment by nsklaus** [comment]
@mount2010 
option added, thanks for the heads up

**Comment by kevingranade** [comment]
This is a stopgap solution that is superseded by #28152 
I'm not interested in using a keybind and an option for this when there are a large number of UI elements we want to be able to toggle.

**Pull request closed without merging**
