### PR TITLE
new tileset retrodays+

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Interface "new tileset based on retrodays "```

#### Purpose of change
i wanted to add transparency to retrodays in my previous PR #36404, but i was told it would be better to make a separate tileset instead for the time being, so here it is.
a new tileset called "retrodays+" which is basically retrodays with transparency for now.
but, considering the opportunity here, i might actually enjoy modifying a bit more, here and here, widening the differences between the two of them. we'll see how it goes. 

#### Describe the solution
in retrodays, there was a black square drawn behind all objects rendering them all 'blocky'.
they obstruct visibility, for example: a table with 4 objects on it, and the table is in practice invisible with classic retrodays. 
now with "retrodays+" and transparency, we can have 4 objects on a table and still see it is there underneath the object placed on it. well, screenshots might describe this better. so for your consideration:

in general look for objects on top of bigger objects, like the tables and sofas:
book_desc

another example, look at bed and table:
grab

before:
retrodays-before

after:
retrodays-after

tiles:
Untitled

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Could I suggest you choose a different name, that says what is different than normal RetroDays?

**Comment by captnblood** [comment]
> Could I suggest you choose a different name, that says what is different than normal RetroDays?

there is the +

**Comment by anothersimulacrum** [comment]
That doesn't say what is different, it provides no information other than that it is different.

**Comment by captnblood** [comment]
> That doesn't say what is different, it provides no information other than that it is different.

your request it is too vague.
and, it is the same for similarily named tileset, like the various chesthole.
one is named chesthole16
the other is named chesthole32

well, here it's "retrodays" and "retrodays+". 
seems ok to me. 
unless you're telling me you really want to rename it "retrodays_with_transparency" ? 
and when i modify a monster or another gfx then what?
"retrodays_with_a_monster_edited_and_transparency_and_what_else" ?
that makes no sense to me. unless i misunderstood you ?

**Comment by anothersimulacrum** [comment]
For those chesthole examples, it conveys a lot of information - it's the size of the tiles.

Something like transparent RetroDays suffices, try to get the core of what makes it different from normal RetroDays.

**Comment by captnblood** [comment]
what do you want me to do ? i have no idea.

**Comment by anothersimulacrum** [comment]
I'm asking that you name it something other than RetroDays+, something that tells you more about what is different than RetroDays.

**Comment by captnblood** [comment]
> I'm asking that you name it something other than RetroDays+, something that tells you more about what is different than RetroDays.

like what?

**Comment by arijust** [comment]
>RetroDays_transparent

Something like that.

**Comment by nullptr98** [comment]
this seems more like a fix to me, otherwise maybe retroydays_rework or retrodays_improved

**Comment by forspamnstuff** [comment]
Captn's RetroDays maybe? )

**Comment by captnblood** [comment]
there is no way for me to know in advance what i will do with this tileset.
potentially, any tile that i might want to customize will be changed.
i have to admit i don't understand the name problem and i don't know what to do with it, however,
if this PR is interesting but have incompatible name for merge, then just tell me what to use and i will do it.

**Comment by anothersimulacrum** [comment]
I think it's very unclear what this tileset it to people who will be looking at changing tilesets, and lead to endless questions about what the difference is. You can change the name anytime you do something different in the future, but I think not having it as `RetroDays_transparent` or similar right now would be very confusing for a lot of people.

**Comment by ZhilkinSerg** [comment]
I think it is okay to keep it named RetroDays+ if there is intent to modify it more.

**Comment by ZhilkinSerg** [comment]
I am not completely sure that all tiles should be transparent, but we'll see feedback from players.

**Pull request merged**
