### PR TITLE
Lint json #34

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: None```

#### Purpose of change
Our json needs linting 

#### Describe the solution
Lint it :)

### CODE REVIEW

**Comment by kevingranade** [comment]
Holy crap that's +2,000 -11,000 non-whitespace changes.

**Comment by ifreund** [comment]
Yeah I’m really sorry about this one, there’s one more national guard camp file too.  I can try to divide up the files or something if you like.

**Comment by kevingranade** [comment]
Since this is large enough that I can't review it in the web interface, that does mean it impinges on more productive work time. I'll be able to get to it sooner if it's split.

**Comment by ifreund** [comment]
Will do

**Pull request closed without merging**
