### PR TITLE
Visual Studio solution with vcpkg support

### LINKED ISSUE #23258: Attributes are not accessible in Lua in VisualStudio builds
Following Lua code returns `nil` values when I compile in Visual Studio 2015 on Windows:

```LUA
local tp = tripoint( 11, 22, 33 )
print("X:"..tostring(tp.x))
print("Y:"..tostring(tp.y))
print("Z:"..tostring(tp.z))
```

It works fine with downloaded binary or when I compile in Code::Blocks (MSYS) on Windows.

Can someone please confirm the issue exists or is it something in my system?

_Edit (2018-05-10):_ Same issue on fresh Windows 10 with Visual Studio 2017.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Build "Visual Studio solution with vcpkg support"```

#### Purpose of change

Enable building on Windows in Visual Studio using packages from `vcpkg`.

Also fixes #23258.

#### Additional context

All credits go to @ralreegorganon for his [initial implementation](https://github.com/ralreegorganon/Cataclysm-DDA/commit/48e6bc860de4ab7b361f028dce714704df56bbba).

***

@narc0tiq: Existing non-vcpkg solution is also affected (include paths were updated), so I've also prepared binaries to put to http://dev.narc.ro/cataclysm/WinDepend-MSVC.zip and http://dev.narc.ro/cataclysm/WinDepend-MSVC.7z (as described here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#dependencies-3). New files contain updated SDL2 libraries:

- [WinDepend-MSVC.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2573248/WinDepend-MSVC.zip);
- [WinDepend-MSVC.7z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2573263/WinDepend-MSVC.7z.zip) (that is actually 7z).

***

I didn't remove existing solution and believe they should co-exist in repo together. 

Appveyor file wasn't updated yet and still links to old solution.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
@narc0tiq:

Will it be possible to update OSXCROSS build environment on Jenkins to use include paths with SDL2 for SDL? There are currently build errors (see http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/8163/Graphics=Tiles,Platform=OSX/console):

```
10:34:23 In file included from src/cata_tiles.h:5:
10:34:23 src/sdl_wrappers.h:6:10: fatal error: 'SDL2/SDL_ttf.h' file not found
10:34:23 #include <SDL2/SDL_ttf.h>
10:34:23          ^
10:34:23 1 error generated.
```

Alternatively I can use some preprocessor commands to change include paths:

This goes to `sdl_wrappers.h`:

```CPP
#ifdef OSXCROSS
  #include <SDL.h>
  #include <SDL_image.h>
  #include <SDL_mixer.h>
  #include <SDL_ttf.h>
  #include <SDL_version.h>
  #ifdef SDL_SOUND
    #include <SDL_mixer.h>
  #endif
#else
  #include <SDL2/SDL.h>
  #include <SDL2/SDL_image.h>
  #include <SDL2/SDL_mixer.h>
  #include <SDL2/SDL_ttf.h>
  #include <SDL2/SDL_version.h>
  #ifdef SDL_SOUND
    #include <SDL2/SDL_mixer.h>
  #endif
#endif
```

and everything else requiring SDL will go with

```CPP
#include "sdl_wrappers.h"
```

**Comment by narc0tiq** [comment]
Ok, so that definitely [worked](http://ci.narc.ro/job/Cataclysm-Matrix/8164/), but obviously if we update the osxcross environment in future, whoever does it will have to remember to reset the symlinks (unless they show up in osxcross itself?). I guess we'll fix that if/when it happens.

**Comment by ZhilkinSerg** [comment]
> Got it, I've updated the files on dev.narc.ro with the ones you linked in the OP.

Thanks a lot. Can you please check http://dev.narc.ro/cataclysm/WinDepend-MSVC.zip? It still seems to be old file (`.7z` is fine).

> Uh... I mean, anything's possible, but will that work for non-cross-compiling OSX builds?

Native OSX builds are apparently working, but I am testing right now.

**Comment by narc0tiq** [comment]
> It still seems to be old file

Probably a cache thing -- what's on disk is updated:

```
[narc@odin /www/virt/dev.narc.ro/htdocs/cataclysm]% ls -l WinDepend-MSVC.zip windepend-pre-26659/WinDepend-MSVC.zip
-rw-rw-r-- 1 narc narc 8009930 Nov 12 19:02 WinDepend-MSVC.zip
-rw-rw-r-- 1 narc narc 7523952 Mar 25  2017 windepend-pre-26659/WinDepend-MSVC.zip
```

**Comment by ZhilkinSerg** [comment]
Native OSX builds are fine with updates paths - both via homebrew and manual builds.

> obviously if we update the osxcross environment in future, whoever does it will have to remember to reset the symlinks (unless they show up in osxcross itself?). I guess we'll fix that if/when it happens.

I've created a project to update compiler documentation - will put info about build environment setup there when I get to osxcross.

> Probably a cache thing -- what's on disk is updated:

Yeah, looks like cache on my side.

**Comment by ZhilkinSerg** [comment]
I've started work on a [workaround](https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/build-conditional-sdl-include-paths) which should work for osxcross, Android and VS solution without vcpkg, but I need to update some more things there before creating a PR.

**Comment by narc0tiq** [comment]
All right, no worries.

**Pull request merged**
