### PR TITLE
Density balance: alcohol and liquid food

### PR DESCRIPTION
**Pull request by batekulve**
#### Summary
Balance "Corrected or unified densities of liquid food consumables"

#### Purpose of change
#54811 Fix incorrect densities of liquid foods.

#### Describe the solution
Sometimes this is correcting a weight that is too high or too low. Sometimes it's bringing similar foods more in line with each other. For example, evaporated milk should not weigh more than milk.

#### Describe alternatives you've considered
I went back and forth on whether I should change weights that are just a little bit off, but mostly decided not to touch it when it's close. I'm not sure why some of these very specific numbers (down to the mg) were used but there might have been a good reason.

#### Testing
Copied changed json files to the latest experimental version. Checked item spawning menu to make sure the items are the correct weight.

### CODE REVIEW

**Comment by batekulve** [comment]
I realize I made a mistake, evaporated milk _should_ be heavier than milk. If you remove some of the water, what's left is a higher proportion of heavier-than-water ingredients. I'll change it this evening.

**Comment by Maleclypse** [comment]
Are you ready for merging? I noticed you have todo listed on your testing.

**Comment by batekulve** [comment]
@Maleclypse  During testing I noticed some weights of brewing products were still incorrect. Those look good now. Tested and ready for merging.

**Comment by RandDenner** [comment]
Sorry to necro, but I only just read this and I have a question.

>I realize I made a mistake, evaporated milk should be heavier than milk.

I assume you mean _if the volume is the same_, evaporated milk should be heavier than milk.

If you simply take, say, a liter of milk and remove some or all of the water, then the weight would go down.

However, if you evaporate, say 3 liters of milk to get 1 liter of evaporated milk (or however many starting liters are required to result in one liter of product), then as the density of the materials is greater, than the weight would be greater as well.

**Comment by batekulve** [comment]
Yes, heavier per ml than milk.

**Pull request merged**
