### PR TITLE
Acid update - rebalance fields, acid zeds, add backgrounds for acid tiles

### PR DESCRIPTION
**Pull request by Coolthulhu**
Problems addressed (at least partially):
- Player sitting on acid field hides the acid field from view
- Acid doesn't scale with density - density 1 fields are dangerous, density 3 fields barely more than that
- Acid field resistance doesn't work too well unless you're approaching immunity
- Acid barfs bypass armor too well compared to acid fields
- Dodged acid barfs don't produce fields
- "Accurate" acid spits are very inaccurate at range, but can randomly get devastating headshots near melee range
- Corrosive zeds can be cheesed by fighting them from a shopping cart or by getting legs/feet protected, but are hard to melee otherwise

Changes:
- Player and NPC symbols get backgrounds according to whether the tile contains electricity, fire, acid or gas. Also, sleeping player gets a background like sleeping NPCs
- Acid field damage rebalanced - less damage at lower density, less damage to legs, except at 3 density (where max leg damage is 5, compared to old 4)
- Acid barfs nerfed - 10-15 to 7-12. Got minimal DoT to partially compensate.
- Dodging barf no longer makes the field not appear
- Accurate acid spits get accuracy penalty at close range, but are more accurate at range. Damage nerfed from 5-10 to 3-5. Got new flag that prevents scaling from accuracy - headshots and glancing hits all deal 100% damage on hit (damage is still lost due to range). This makes them more dangerous at range. They blind on headshot (they always did, just that now you can expect to get hit in the head).
- Corrosive zeds get longer cooldowns (5 instead of 3, on both attacks).
- Corrosive zed defense changed: instead of producing acid fields (which would require a lot of acid), they produce acid projectiles that can hit all body parts for small amount of damage. This removes the ability to cheese them with a cart, but makes resisting their defense easier. Most projectiles hit the torso.
- Buffed raincoat - it is now 7 encumbrance (fitted) and 2 acid resistance. Wearing one will now mostly protect from corrosive zed's defensive capabilities (but not offensive ones)
- Changed projectile hit-but-reflected message to include the body part hit when the target is a character. For example, "projectile reflects off your torso" rather than "your armor".

Acid field damage:

| Density | Old foot damage | Old leg damage | New foot damage | New leg damage |
| --- | --- | --- | --- | --- |
| 1 | 1-5 | 1-4 | 1-3 | 1 |
| 2 | 2-5 | 2-4 | 1-4 | 1-3 |
| 3 | 3-5 | 3-4 | 1-5 | 1-5 |

Increased the chance of getting the DoT from acid fields - immunity from direct acid damage won't necessarily protect from that.

And a minor code quality change:
Removed nonplayer.cpp and .h. Those weren't used anywhere.

### CODE REVIEW

**Comment by tyrael93** [comment]
Praise.

**Comment by Zireael07** [comment]
Amazing!

**Comment by CIB** [comment]
Okay, tested this on my seasoned character by taking off head protection and most other armor and engaging them with a sword. Result: The acid pool on the ground did MUCH more damage than the shots themselves.

**Comment by Coolthulhu** [comment]
> Result: The acid pool on the ground did MUCH more damage than the shots themselves.

Leg (especially foot) protection is still a must when engaging corrosives in melee.

**Comment by CIB** [comment]
As I said, I was wearing leather boots, and no head or torso protection besides regular clothing. I don't think feet should be the only source of damage in that scenario.

**Comment by Coolthulhu** [comment]
Acid spilling on feet is undodgeable. If your character has 5+ dodge, corrosives may have hard time landing a hit.

**Comment by Chezzo** [comment]
Oh man, does this work on tiles? I am really only interested in the sleeping background, as tiles already shows things you are stepping on. 

I could do little zs coming out as a background, and if it was an overlay, I could do closed eyes and zs.

**Comment by Coolthulhu** [comment]
> Oh man, does this work on tiles?

Nope, but the support for it would be next to trivial to add. In `player::get_overlay_ids()`, this needs to be added somewhere before `return`:
```
for( const efftype_id &effect_pair : effects ) {
    rval.push_back( "effect_" + effect_pair.first.get_id() );
}
```

I didn't test it so it might not compile because of a typo or something like that, but that's basically all that needs to be done to allow setting up effect overlays.

**Pull request merged**
