### PR TITLE
Allow rollerskates/blades to work on gym waxed floors

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

SUMMARY: None

#### Purpose of change

Waxed floors, despite being smooth, penalize rollerblades when walked on.

#### Describe the solution

Add ROAD flag to waxed floors so rollerblades work with them.

#### Describe alternatives you've considered

Pretending gym floors aren't smooth.

#### Testing

Before changes, teleport to a school gym & put on rollerblades to see that it takes more than a second to go on waxed floors but less than one on regular floors while walking.
After changes, repeat & see no differeence.

#### Additional context

Credit goes to Compound_Fracture on Twitch to alerting me to this.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Are you sure this isn't going to habe side effects? Road flag only means no penalty for roller blades?

**Comment by LaVeyanFiend** [comment]
> Are you sure this isn't going to habe side effects? Road flag only means no penalty for roller blades?

Times ROAD is invoked:
monmove.cpp: Monsters largely ignore FLAT or ROAD terrain, it already had FLAT so this changes nothing
character.cpp: This+on ground with movecost < 105 activate on_road for only the purposes of ROLLER_INLINE/ROLLER_ONE/ROLLER_QUAD

**Comment by Fris0uman** [comment]
So maybe FLAT and ROAD should be merged then? Or at least the call to ROAD in character.cpp should instead check for FLAT?

**Comment by actual-nh** [comment]
From JSON_FLAGS.md:
- ```FLAT``` Player can build and move furniture on.
- ```ROAD``` Flat and hard enough to drive or skate (with rollerblades) on.
I don't use rollerblades (too much of a clutz), but I would not think a surface would need to be able to support a vehicle for skating to be possible.

**Comment by Fris0uman** [comment]
Okay this might be more bother than it's worth then. I guess just adding the road flag might be good enough but this looked like an opportunity for cleaning/clarifiying flags.

**Comment by actual-nh** [comment]
Admittedly, `ROAD` for gym waxed floors would make vehicles able to drive on them, as far as I can tell. I don't know how desirable this is.

**Pull request merged**
