### PR TITLE
Display calorie value of ingredients while crafting food

### PR DESCRIPTION
**Pull request by Salty-Panda**
#### Summary
Interface "Display calorie value of ingredients while crafting food"

#### Purpose of change

You can choose which ingredients to use on the fly without checking them beforehand and switching between inventory view and recipe.

#### Describe the solution

If the ingredient AND recipe's result is comestible it displays kcals player would get from eating it.
It displays kcal as range, takes min and max value from crafting inventory.
image
When min == max, displays only a single value

If the recipe removes RAW penalty, multiply the ingredient's kcal value and display it will be processed<del>, otherwise display if ingredient is RAW</del> 
__Displaying RAW doesn't seem to be the best idea, I won't do this.__ 
Details: https://discord.com/channels/598523535169945603/598523535169945607/838106196719173653
image

Properly display for items in any location:
image

#### Describe alternatives you've considered

<del>I think I should extend the solution by adding a function that fetches from inventory the average Calorie value of items of given _itype_. So if the flour has default Calorie 30 but the player uses crafted flour which has either 40 or 42kcal it would display 41 instead of 30.</del>

Instead of displaying red RAW, display a smaller green/brown info if the ingredient will be cooked during crafting?

Display TOXIN - that's unreliable, since crafting uses itypes, won't add.

#### Testing

Used in-game, works properly
Only tested in player crafting, don't have any save with full-on basecamp that allows crafting

### CODE REVIEW

**Comment by actual-nh** [comment]
Displaying the range could be useful for working out failures in the recipe_permutations test - especially if it gave the full possible range when in debug mode or something (with an indication that this was happening).

**Comment by Salty-Panda** [comment]
Sry, by accident dragged some commits from master

**Comment by Maleclypse** [comment]
Please open a new PR for this targeting the experimental branch.  Was closed as a side effect of deleting the 0.F -dev branch

**Comment by actual-nh** [comment]
@Salty-Panda: Could you fix conflicting files? This could be rather nice not only during play, but when trying to figure out caloric mismatches between food inputs and outputs of recipes.

**Comment by Salty-Panda** [comment]
Rebased, tested in game

**Pull request merged**
