### PR TITLE
Perspiration And Comfort In Warm Climates

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Perspiration"

#### Purpose of change
This is a desired feature I'm sure I could find a few issues if I went looking. 

Here's the last bit Kevin had to say about it on the Discord which was my inspiration:
`So... probably the way to push clothing insulation through is to just accept the suck and do it piecewise
Like treat "warmth" as "insulation value" so we don't have to audit clothes until later, and start with a really simple formula for how much heat the player is generating and how much of that is being trapped by clothes, and bolt on sweat as "burn water as needed to stay  below X temperature"
I've literally come back to this dozens of times and always end up getting buried under piles of new systems before I even start`

#### Describe the solution
this revives #44880 since it already did some of the leg work or at least I can look in it for all the places I should tweak.

~~TODO:~~ Stuff I've Done:

- [x] Fix basic merge conflicts
- [x] Fix compile issues
- [x] Sort through the basics of this PR to make sure any of it makes sense
- [x] Cull anything that seems out of scope, or is conjecture to get down to a system that can be easily iterated on
- [x] Stringify the "breathability" of materials so it is less numerically arbitrary and clearer in the JSON
- [x] Integrate breath ability values with newer complex armor designs so that per bodypart breath ability is a possibility. 
- [x] Apply some use case information from a few sources like https://www.ncbi.nlm.nih.gov/books/NBK236237/#!po=22.0588 to get reasonable numbers for water loss and perspiration
- [x] Documentation
- [ ] ~~Unit Tests~~

STRETCH GOALS **not in this PR**:
- Integrate metabolism/acclimatization as a long term stat
- Integrate circulation
- Salts replenishment
- Static ways to set temperature for UNIT testing
- More fine tuned water
- Way more involved cool down calculation. 

ASSUMPTIONS:

1.
https://www.ncbi.nlm.nih.gov/books/NBK236237/table/ttt00009/?report=objectonly
Person sweating produces between 750ml - 1250ml of water per hour based on climate with a default of 250mL. I'm going to consider the 250mL base to be part of the base water calculations for characters. So between 500mL - 1000mL. The character can be warm, hot or scorching so I think 500ml for warm and 1000ml for hot+ per hour makes sense as a start point.

the goal is an additional 500mL of water an hour sweating. That increased up to 1L as you approach Scorching. This isn't perfect as your limbs sweating will fluctuate. 

2.
A person should be able to maintain a comfortable temperature by sweating up until just under the HOT effect. This is 7500 temperature units in game or 50 in the UI. This is conv temp, so basically sweating should be able to adjust your temperature back down bellow WARM which is 6500 temperature units, or at least balance you around there sweating. This assumes you are naked, clothes are going to effect this based on how they breathe.

3.
Breath-ability of a piece of clothing is equal to the WORST breathing material per coverage. I know IRL there are fancy "moisture wicking layers" on clothing but CATA doesn't have that currently so until someone makes every piece of sporting gear 4 different materials its just the least breathing material is the blocker.

IMPLEMENTATION:

This PR adds the following:
- JSON strings for material breath-ability ranging from IMPERMEABLE (0%), SOMEWHAT (30%), BREATHABLE (50%), MOISTURE_WICKING (80%), SECOND_SKIN (100%) 
- This is how close to bare skin the clothing facilitates sweating
- All but second skin are applied to current materials (second skin is reserved for sci-fi stuff). Materials default to impermeable if not set
- This info is amalgamated on complex armors
- Some math is done to sort materials by breath-ability and then from worst to best amalgamate the armors breath-ability until the whole coverage is accounted for. Example 20% steel, 100% cotton: steel is first, covers 20% of the armor, cotton is next covers 100% of the armor but steel already covers 20% so you get 20% of steels breath-ability 80% of cottons. 
- UI entry for armor breath-ability 
- Drench and wetness of body parts is no longer probability. All values have been scaled by 100 to accommodate more accuracy.
- Dryness calcs already in place have been replicated closely changing from probability to a direct reduction in wetness but maintaining the feel (this was mostly maintained from #44880
- Dryness additionally is effected by your worst breathing armor pieces on the BP and directly modifies dry time
- Dryness formula now also reduces heat if sweating. The goal is to match the entropy of temperature up to the point mentioned in assumptions above
- Armor breath-ability also matters for sweating however and directly scales your value to reach equilibrium.
- Added a wet effect which appears in the status panel
- Removed the description of sweating from the "hot" effect since it's now it's own thing
- "hot" now causes perspiration as an effect. It generates an amount designed to match approx. the drying of a naked human sweating a normal amount.
- "hot" now causes about the amount of thirst described in the assumption above.
- the "hot_speed" effect is now shifted 500 temp units from the normal hot effect. This is so you can start to sweat *before* you get effected by the slowdown. So it will still happen I haven't reduced it in any way just gives the body time to hit an equilibrium before the effects set in.
- Debug command to see Temp, Temp_conv and wetness for each BP

#### Describe alternatives you've considered
Starting from scratch on this.
Doing something really simple to start but that seemed a waste since someone already worked on breath-ability. It also is a huge part of what manages equilibrium. 

#### Testing
Honestly so many of the systems around this are so eyeballed and complicated using internal units and scales its hard to do solid testing.
Because of breath-ability of different armors, inter-limb heat transfer, weather effects, body/metabolism etc. it's hard to get exact values or test things in a really accurate way.  

The main stuff works: 

Non breathable hot plate armor = soup,

Naked in the heat = comfort but thirsty (seriously really thirsty like die of heat stroke bad) carrying water will now be **way** more important,

Different load outs based on breath-ability will hit different equilibrium values, which is pretty cool. An outfit that's warm could still be practical if you don't mind the sweat and it's breathable.

#### Additional context
I do intend to write some unit tests but it will need some infrastructure and I think having players test this for a bit to get some tuning right and *find the edge cases* would be easier than me trying to find them myself.

### CODE REVIEW

**Comment by dseguin** [comment]
You're my hero for tackling this one!

**Comment by wapcaplet** [comment]
Is this likely to be a large enough project to be held by "Project freeze"? #53318

**Comment by bombasticSlacks** [comment]
Practically this is going to just make you lose water to mitigate heat and materials will have breathability which in first iteration will be I think three levels 'impermeable', 'average', 'breathable'. 

Other than that it's just tying it into the new more complex armor defs which is an ongoing project.

*Also* it's on Erks feature list for .G IIRC, which I should have lead with but I'm just waking up.

**Comment by chrispikula** [comment]
Will the breathability, if not explicitly inputted, be a derived value of thickness and material(s)?

**Comment by bombasticSlacks** [comment]
> Will the breathability, if not explicitly inputted, be a derived value of thickness and material(s)?

It will exclusively be a derived value of thickness and materials

**Comment by chrispikula** [comment]
Ah, no over-ride exceptions for things like chainmaile, or cooling vests/powered armor?  At this point I'd call that utterly fair.

**Comment by bombasticSlacks** [comment]
Powered armor and cooling vests would still have climate control, a different thing.

I think chainmail should be it's own material but otherwise someone else can add edge cases after the initial implementation.

**Comment by AcidAntOnAMinefield** [comment]
The only two questions I have:

1. Will we still get stacked penalties due to being "warm"? Currently what seems to happen is (example below):
- Summer time, your character's "warmth UI numbers" (measured in Unknowniums) is all around, say, 39 Uknowniums - which is "yellow", ie warm. Will the character still get full x6 penalties because each limb is warm? (same for cold too) Or will there be an actual change to this? 

2. When will enemy creatures actually become affected by climate conditions like the player characters are, too?Stuff like Slowed down in heat and cold, barely moving if freezing or a blizzard is going on or accuracy penalties that aren't just relying on Dodging? Because so far what is happening is th**e player is getting bombarded with all these random effects** whereas **every enemy is just immune to everything except furniture, holes and fires**. Enemies that can't breathe but somehow can smell. Zombies with no Brain that somehow can hear (or literally do anything, without a central nerve system to coordinate itself). "Ferals" that magically had their smelling senses sharpened to the point of being able to sniff you out too. Blizzard outside? No worries, Ferals, wild creatures, insects, zombies and nether creatures can just move around just fine. The player? Nah, that person sucks, so they must die immediately.

**Pull request merged**
