### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by Maeyanie**
#### Summary
None

#### Purpose of change

Minor typo fix.

#### Describe the solution

Change "apply them the in a real fight" to "apply them in a real fight"

#### Describe alternatives you've considered

After reading this section's title I briefly considered changing it to "in the real fight apply it" but then I remembered this isn't written by Yoda.

#### Testing

I mean, I could run the test suite on it if you want, but it's one word in a json file...

Edit: Yes, apparently I should have, as this will need localization file changes too. I'll close this for now and make a new one when I get around to fixing it all.

#### Additional context

image

### CODE REVIEW

**Comment by Qrox** [comment]
> apparently I should have, as this will need localization file changes too

If by localization files you mean the `.po` files, these are automatically generated and shound NOT be changed.

**Comment by Maeyanie** [comment]
> > apparently I should have, as this will need localization file changes too
> 
> If by localization files you mean the `.po` files, these are automatically generated and shound NOT be changed.

I did, didn't realize that. Is this actually done correctly then?

**Review by NetSysFire — APPROVED** [review]
This is the kind of PR where you would use None as a summary by the way.

**Comment by Maeyanie** [comment]
> This is the kind of PR where you would use None as a summary by the way.

Okay, changed. The instructions in the comment don't even mention a "None" type, but I did notice it on others when I was trying to figure out exactly how to make the auto-check happy.

**Comment by NetSysFire** [comment]
Yeah it is not intuitive. I wish we could have PR templates as we have issue templates, but github does not support that one yet.

**Pull request merged**
