### PR TITLE
[CR] Change the book recipe list to show what you can learn

### PR DESCRIPTION
**Pull request by tivec**
When you examine a book you have read, recipes that you can learn with that book and your current skills will be listed in light blue color, just like books are in your inventory if you have the skill to learn from them.

Here is a sample:
http://i.imgur.com/FzISyi6.png

### CODE REVIEW

**Comment by KA101** [comment]
Hmm.  Couple issues here:
1) I'm trying to discourage colorizing the interface further until we can make the colors user-configurable.  (Colorblindness is a thing, and we like DDA being accessible to everyone.)
2) We're seriously considering removing the "read book to memorize recipes" function altogether, and requiring folks to have the book on hand when crafting in order to memorize.  Would hate to waste your time, sorry.

Any thoughts?

**Comment by tivec** [comment]
I fully understand the issue with not colorizing the interface further 'til colors are configurable. That is something that we really need to set up. However, that type of patch is way beyond my knowledge. I would like to see it as well, colorblindness is a serious thing to consider.

I could add a (can learn) tag to the list instead, but that will grow the list on some books, and since we can't really scroll that interface that's going to be a pain to work with.

As for removing the memorizing of books, I think that would seriously hamper the ability to craft things. You would not be able to be on the other side of town and quickly check the recipe for that component you need for the FOODCO Kitchen Buddy - because you don't happen to have the book/recipe on hand. 

All that forcing the players to have the book on hand for crafting will result in is that the players will be frustrated and use less in game tools to figure out what to use. And I know that at least I will dump all my books in a pile near my crafting area so I can take advantage of being nearby the books. Won't really change much..

**Comment by KA101** [comment]
OK, good to know.  If nobody's objected by tomorrow, I'll queue this for merge.

**Comment by tivec** [comment]
I have been working on the way the recipe list is displayed for books and have come up with a possible solution: Image

The recipes you can learn, can't yet learn and already known will be grouped under their own headings. This adds a little extra (up to 3 lines) to the book display, so I am a bit worried how it will work out on smaller instances. Can we scroll these item info panes in some way?

I've just come up with some random text that will be shown as headers for the different groups, so please let me know what I can make better.

**Comment by BevapDin** [comment]
> Can we scroll these item info panes in some way?

The main item info ('i' to go into the inventory, select an item) can be scrolled with '>' / '<'. It seems to only work for items in the inventory.

**Comment by Zireael07** [comment]
@tivec: I love that screen.

**Comment by DavidKeaton** [comment]
I for one love this screen. The big issue with color blindness is two things (from personal experience):
1.) Color mixing (Red-Green CB, Blue-Red CB, etc).
2.) Colors over others (i.e. Red over Blue, see above).

**Comment by KA101** [comment]
As we discussed in IRC, the book probably shouldn't tell you exactly what you don't know how to make, since that usually means you don't have the skill to derive a way to craft the item from whatever the book says about it.  Apart from that, sure.

**Comment by tivec** [comment]
The whole point of the PR is that you get to see which recipes you can learn or not. Right now, it's hit or miss, and you read the book and sort of stumble upon the fact that "oh, I can't learn anything more now."

I could read a Haynes manual for a car, but I would know that my mechanical skills are not good enough to understand some parts of the book until I get more practice. Likewise, if I read the instructions for how to make something in chemistry, but realize that I don't know how what a beaker is, I jolly well can't produce the item until I've studied a bit more. Especially in a post apocalyptic setting, where we do not have access to the Internet.

At the moment, books are marked in sevaral colors, just so there is less hit and miss for training. It's hard enough to survive for some people, why not throw them a bone so they can see what sections they can understand?

**Comment by KA101** [comment]
I have no problem whatever with saying that one doesn't have all the skill needed to extract every recipe fro a book.  Thought we covered that on the IRC.

No idea re Haynes manual, but unless it lists HOWTO make various parts, you'd not know that with a little more mechanical background you could look at it and work out how to make an alternator or something.

If we weren't so bloody backlogged I'd offer to split the difference and whip up a tag for hidden/visible recipes.  *shrug*

**Comment by tivec** [comment]
Haynes is a very good manual for car owners - each book they make detail a specific car and splits the activities (repairs, mostly) up in "easy", "intermediate" and "advanced". That way, you have a chance to at a glance understand if you should even attempt the project.

As for hidden/visible recipes, that will make it a LOT harder for people to find what they want to make from the book, and I am not sure that is a positive thing. Look at the PR I sent regarding hidden_unless_craftable (PR #11479) which was closed since there was opposition to hiding recipes and making it harder to figure out what is needed to craft them.

As for how books are now, at least the way I feel they are designed, they are basically recipe books. "This is how you craft a <insert item>". Much like a cookbook. How else could I know after just browsing the index (reading the first time) that I can craft a FOODCO and a Makeshift Welder from the book?

I would like to have a few more people chime in on this to see what the general consensus is for the PR. I'll mark it as [CR] and we can bring in some more people, I guess..

**Comment by narc0tiq** [comment]
I don't see hiding currently-unlearnable recipes being beneficial. I can
easily see a line similar to "There's more in here you don't understand
yet", I'm just not convinced it would play well. Remember that currently
you just _know_ what all the recipes are as soon as you skim the book for
the first time.

**Comment by KA101** [comment]
>Remember that currently you just _know_ what all the recipes are as soon as you skim the book for the first time.

And I consider that a bug.

**Comment by valuial** [comment]
One thing about rougelikes - especially with perma-death - I really enjoyed was that you had all the time to make decisions on knowledge the character doesn't necessarily have, but that you are either offered by the game or learned from previous runs.
Same applies here: the player really needs a lot of information to make decisions. I don't think it a good idea to hide that information from the player and force them to write lists in meatspace.
Some rougelikes hide such information until any (former) character learned of it. Hiding recipes until any character was able to learn them would be a huge code change. Without really improving gameplay... In my opinion the information what a character can learn or can not yet learn should be given to the player, no matter if the character itself would be able to realize the recipe being in the book still way above his knowledge...

**Comment by mugling** [comment]
Closed due to age. Would need rebasing against `master` if reopened

**Pull request closed without merging**
