### PR TITLE
Softcode bunker mapgen

### PR DESCRIPTION
**Pull request by sethsimon**
The softcoded bunker is identical to the hardcoded version except for one difference: In the basement, rooms would either be empty, or have some number of items from exactly one item group. Since JSONized mapgen isn't flexible enough to do that (as far as I know), rooms will have items from more than one group.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
I am fairly certain that conventional item groups can cite item groups, allowing for either-or item group spawning. Unless I am misinterpreting the example seen in the `item_groups.json` file:

````
  },{
    "type" : "item_group",
    "id" : "ambulance_equipment",
    "items":[
      { "group": "tools_medical", "prob": 100 },
      { "group": "drugs_emergency", "prob": 50 }
    ]
  },{
````

That seems to use the default style of item group, where only one entry on the list is picked. But it could interpret that as a collect, spawning tools 100% of the time and additional drugs 50% of the time.

But the ambulances I have seen so far, which seem to sometimes have medical supplies but not tools, would suggest the former.

**Comment by ZhilkinSerg** [comment]
You can create separate item groups for each room, so each room will have distinct loot.

**Comment by codemime** [comment]
You're doing a good job. Please don't forget to update the list of hardcoded overmap specials ([here](https://github.com/CleverRaven/Cataclysm-DDA/pull/20276/files#diff-90df0fb487770203c1f3f21de7b1b6bdL648) is an example).

**Comment by Coolthulhu** [comment]
I'll wait for the hardcoded update.

There is a minor problem with hardcoded updates: they conflict often. So if any of the testers could focus on those jsonization updates (ie. merge at least one in a batch), it would go down much quicker than in my mass-merge method.

**Comment by sethsimon** [comment]
>You're doing a good job. Please don't forget to update the list of hardcoded overmap specials (here is an example).

>I'll wait for the hardcoded update.

Thanks, will do! And sorry about the delay.

@DangerNoodle Yep, that would be `"subtype": "distribution"`.
@ZhilkinSerg @DangerNoodle I think we had a communication error. What I meant is that a hardcoded call to `place_items( one_in(2) ? "groupa" : "groupb", int that isn't 100, ...` can't be softcoded. The closest I can get is defining an item group that's a distribution with a 50% chance of groupa and 50% chance of groupb (see bunker.json). But that translates into the subtly different call to `place_items( "bunker_basement_loot", ...`.

**Pull request merged**
