### PR TITLE
Remove obsolete/unused fields from basecamp blueprint recipes

### PR DESCRIPTION
**Pull request by Alex-Folts**
#### Summary
None

#### Purpose of change
There is redundant fields in basecamp blueprint recipes which no longer used/required, like: "blueprint_needs", "time", "skill_used", "components", i've been told that those no more required and can be omitted. I have issues with my another PR(https://github.com/CleverRaven/Cataclysm-DDA/pull/53431) where some of this fields cause build errors, one of possible solutions was to remove them completely from recipes which cause errors.

This PR similar to https://github.com/CleverRaven/Cataclysm-DDA/pull/53448.

#### Describe the solution
I've gone through all recipes which caused me errors and remove extra json fields, also since i was there  i clean rest of the recipes in the same json file.

#### Describe alternatives you've considered
Add missing components to conflicting recipes. But this things will cause errors for someone else in the future again.

#### Testing
I've run new game, spawn npcs and build camp in open field, build some structures with affected blueprints.

#### Additional context
This is the list of recipes which cause me build errors:
```
faction_base_modular_workshop_room6_wood_north
faction_base_modular_workshop_room6_wad_north
faction_base_modular_workshop_room6_rock_north
faction_base_modular_workshop_room6_migo_resin_north
faction_base_modular_workshop_room6_metal_north
faction_base_modular_workshop_room6_log_north
faction_base_modular_workshop_room2_common_northeast
faction_base_modular_shelter_1_craftspot
faction_base_modular_shelter_craftspot
```
Also `faction_base_modular_firestation1_workbench` but this one already addressed in https://github.com/CleverRaven/Cataclysm-DDA/pull/53448.

### CODE REVIEW

**Review by PatrikLundell — COMMENTED** [review]
The survey recipes (survey the site, often the first one in the "common" file, also marked as "not_an_upgrade") are ones that shouldn't be stripped, as the time taken presumably is meant to survey the site, not just erect a board. In addition to that, the board in these recipes are presumably intended as a necessary interaction interface thing, and so are magicked up with no materials used.
'"check_blueprint_needs": false' is a warning sign that you need to tread carefully.

The "components" part of recipes outside of "blueprint_needs" shouldn't be removed either. They typically represent tools that are then placed there as part of the blueprint (the "components" parts inside should go together with the rest of the "blueprint_needs" as those represent the construction material requirements that the code can figure out by itself).

**Comment by Alex-Folts** [comment]
> The survey recipes (survey the site, often the first one in the "common" file, also marked as "not_an_upgrade") are ones that shouldn't be stripped, as the time taken presumably is meant to survey the site, not just erect a board. In addition to that, the board in these recipes are presumably intended as a necessary interaction interface thing, and so are magicked up with no materials used. '"check_blueprint_needs": false' is a warning sign that you need to tread carefully.
> 
> The "components" part of recipes outside of "blueprint_needs" shouldn't be removed either. They typically represent tools that are then placed there as part of the blueprint (the "components" parts inside should go together with the rest of the "blueprint_needs" as those represent the construction material requirements that the code can figure out by itself).
> 
> Then there the whole infernal testing thing to verify that nothing is broken by the changes.

Got it, i'll fix it soon. I wasnt sure if its fine to remove it from all recipes, but it didnt crash and camp building didnt break so i thought it is fine.

**Comment by PatrikLundell** [comment]
I think the long term path is to convert all of the construction recipes (that aren't exempted from evaluation) to remove further cases of this kind of problems.

If it causes loading to take too long, evaluation of recipes ought to be moved to the time at which they are "introduced", possibly with caching of the results for further calls during the same game session (each recipe listed in a construction list would have to be evaluated when the list is populated to allow the display to show which recipes have the required resources available and which do not), and tests introduced to verify that the recipes are valid ought to be written instead (basically invoke the evaluation for each of the recipes and verify that they don't fail to generate evaluated results).

No player will need all recipes during the same real play session. In fact, only a subset of players construct bases, and those activities take up only a few of the game sessions, where only a small subset of the recipes are available (namely those for that base camp and those expansions selected).

**Comment by Alex-Folts** [comment]
Closing this as i think first need to implement caching so auto-evaluation didn't slow down loading of the game.

**Pull request closed without merging**
