### PR TITLE
Nested Recipes - Gambesons and More

### PR DESCRIPTION
**Pull request by ANickelN**
#### Summary
Interface "Nested Recipes - Gambesons and More"

#### Purpose of change

Continued work towards nesting recipes.
Gambeson and related items, refined cannabis products, the different boxes (metal, wood, cardboard) and patchwork sheets, flintlock weaponry.

#### Describe the solution

Add necessary JSON.

#### Describe alternatives you've considered

Having someone brainstorm a way to automate this.

#### Testing

I tested each grouping individually on a local copy.

### CODE REVIEW

**Comment by esotericist** [comment]
i feel like a misunderstanding occurred in our last conversation; you have hundreds of lines in your changeset here from moving items around, which is exactly the kind of churn i was cautioning against.

**Comment by ANickelN** [comment]
> i feel like a misunderstanding occurred in our last conversation; you have hundreds of lines in your changeset here from moving items around, which is exactly the kind of churn i was cautioning against.

The "churn" was already done by the time we had that conversation.  If it will cause the PR to be rejected I can go back and "restore" things to the wrong place, but otherwise I'll just leave it.  I understand now it is frowned upon.

**Comment by bombasticSlacks** [comment]
>  If it will cause the PR to be rejected I can go back and "restore" things to the wrong place

It will, gambesons have had a lot of changes historically, moving them makes it impossible to track any of it using git. Instead it just brings you to this otherwise unrelated PR.

**Comment by bombasticSlacks** [comment]
BEFORE
Screenshot_20220823-130615

AFTER
Screenshot_20220823-131057

**Comment by ANickelN** [comment]
It is what it is, I'll go back and fix it, and then notify you.

**Pull request merged**
