### PR TITLE
Add menu_text items to items with "transform"

### LINKED ISSUE #19573: New action menu incorrectly shows action for Atomic Lamp
capture2
This shows correctly that the atomic lamp would be "turned on" (show light) if I uncover it.
capture
This should show "Turn off" (cover it) as the option of it"

Instead of using "Turn on"/"Turn off" for this, could we simply make it "Cover"/"Uncover" as the item would suggest?

Also with the Caffeine pill, it shows that you "Drink" it rather than consume it like the aspirin, multivitamin or the tramadol.
capture

### PR DESCRIPTION
**Pull request by bdgackle**
Fixes #19573

Adds missing "menu_text" tag to all items with a "transform" tag in various json files.

This is a second attempt at this PR.  The first time I got json linting errors, but the line printed in the error message was from an earlier commit.  Something strange happened; I'm hoping that closing and reopening resolves whatever it was.

### CODE REVIEW

**Comment by bdgackle** [comment]
Something strange is going on here.

The build bot thinks that there is a comma at the end of line 21 in tools.json... but said comma simply doesn't exist in the commit.

Looks like something got cached strangely?  Or maybe I don't understand the error message.

**Comment by AMurkin** [comment]
imo linter wants menu_text before transform. maybe not only that one place.

**Comment by BorkBorkGoesTheCode** [comment]
> imo linter wants menu_text before transform. maybe not only that one place.
Try this^
@bdgackle

**Comment by bdgackle** [comment]
Yep, looks like it was an order thing (I fixed one to make sure before doing all of them).  Am fixing now.

**Pull request merged**
