### PR TITLE
Adding More Birds

### PR DESCRIPTION
**Pull request by klorpa**
#### Summary
Content "Adds ravens, blue jays, cardinals, robins, and sparrows as animals that can be found throughout the game. Also adds a monstergroup specifically for animals you may find hanging around bird feeders."

#### Purpose of change
Adds more content to the game.

#### Describe alternatives you've considered
I would appreciate any suggestions/additions regarding various animal qualities: hitpoints, weight, volume, aggression, ageing, etc.

### CODE REVIEW

**Comment by Saicchi** [comment]
I suggest adding `mon_raven_ckick`, `mon_magpie_chick`, `mon_bluejay_chick` and `mon_cardinal_chick` to the `GROUP_EGG_BIRD_WILD` monster group in `data/json/monstergroups/eggs.json` so they can spawn from unidentified bird eggs.

**Comment by klorpa** [comment]
I mostly need help with proper values for the `age_grow` and `baby_timer` variables now.

**Comment by LyleSY** [comment]
I just copy the values for chickens. It's close enough unless you can find a better source

**Comment by LyleSY** [comment]
So monstergroups. The freq numbers should add up to 1000, or 800 if you want mods to work. I'd recommend cutting down freq on other monsters to balance the freq you're adding. Anything over 1000 will never spawn, last one listed is removed first. It's confusing

**Comment by klorpa** [comment]
> I just copy the values for chickens. It's close enough unless you can find a better source

The baby_timer is how long an egg takes to hatch, and age_grow is how long for a chick to become an adult, yes? So a value of 1 for a baby_timer is equal to how much actual time?

**Comment by LyleSY** [comment]
Those are documented here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md

**Comment by CivilisationDDA** [comment]
> 
> 
> I mostly need help with proper values for the `age_grow` and `baby_timer` variables now.

I think you've already sorted this out but for future reference:
https://nestwatch.org/learn/general-bird-nest-info/clutch-size-phenology-for-common-species
More info for all US species here: https://www.allaboutbirds.org/guide

Apparently there are no magpies in New England so they can't be in the game unfortunately.

Finally, the chicks of crows and all these new species are helpless and mostly immobile until fledged unlike those of chicken, geese, ducks and grouse. Maybe this is out of scope for this PR but there should be a unfledgedchick group in the game that can't fly or move.

**Pull request merged**
