### PR TITLE
Replace add_spawn() calls in mapgen.cpp with place_spawns()

### LINKED ISSUE #3951: Replace add_spawn() calls in mapgen with place_spawn()
There are several building layouts in mapgen.cpp and building_generation.cpp that have add_spawn() calls placing specific monsters on the map instead of place_spawn, which is more generic and selects monsters from a group.  This causes issues with the options that modify spawn behavior, because add_spawn() doesn't support those options.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1366883-replace-add_spawn-calls-in-mapgen-with-place_spawn?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by brekiy**
#### Summary
```SUMMARY: Infrastructure "Replace add_spawn() calls in mapgen.cpp with place_spawns()"```

#### Purpose of change
Related to #3951 - Replaces add_spawn() calls in mapgen.cpp that essentially hardcoded monsters into the map generation. Monsters were not able to be completely removed from the game via mods due to this. 

#### Describe the solution
The place_spawns() method was used as a replacement as suggested in the original issue. An additional flag was added to the place_spawns() method to allow for spawning an individual monster from the monster group passed in as a parameter.
A few new monster groups were added of individual monsters, like dark wyrms or hazmat bots.

#### Describe alternatives you've considered
I considered changing place_spawns() to also accept individual monsters at first, but realized that was basically just re-implementing add_spawn(), so I didn't do it.

#### Additional context
I will add compiled test builds here when I continue to make more progress and test locally.

### CODE REVIEW

**Comment by xiaohuynh** [comment]
I have a question about how unit testing is done. On Visual Studio, am I supposed to compile the "Tests" project within the Cataclysm solution, and then copy the resulting Cataclysm_test.exe to the root dir and run it?

**Comment by xiaohuynh** [comment]
[Windows distro of the changes up to commit 3119420](https://mega.nz/#!sp0nlSIY!85iXzvt9q04Bnyj1L8jd2F1dFY06z0JsM4mJdXFOILk)

**Comment by ZhilkinSerg** [comment]
Failing char validity test has something to do with VS compiler. Travis CI runs the tests for us, so while tests were successful there you can ignore your local test errors unrelated to your change.

**Comment by ZhilkinSerg** [comment]
There are still a few `add_spawn` calls left in the code, so #3951 shouldn't be fully closed yet?

**Comment by xiaohuynh** [comment]
I found 3 instances of add_spawn() left in mapgen.cpp. Here are their line numbers and my reasons for not changing them.

Line 228: I left it alone because I was unsure if I should change it. It's part of map::generate(), the very first function.

Line 1259: I also left this alone because it was part of the jmapgen_monster class, and didn't want to risk breaking things if it was used elsewhere. It's description says, "Place spawn points for a specific monster (not a group)."

Line 6916: This add_spawn() call is part of the place_spawns() method, and necessary to make it work.

**Comment by ZhilkinSerg** [comment]
I understand there are some lines which should left intact, but there are more in files like `mapgen_functions.cpp` and `map_extras.cpp`. Not saying they should be replaced in same PR - just mentioning that they are still here and need to be addressed.

```
Search "add_spawn" (66 hits in 7 files)
  C:\Projects\Cataclysm-DDA\src\map.cpp (1 hit)
	Line 6746:         add_spawn( spawn_details.name, 1, pnt.x, pnt.y, false );
  C:\Projects\Cataclysm-DDA\src\map.h (1 hit)
	Line 1218:         void add_spawn( const mtype_id &type, const int count, const int x, const int y,
  C:\Projects\Cataclysm-DDA\src\mapgen.cpp (6 hits)
	Line 244:                 add_spawn( spawn_details.name, spawn_details.pack_size, p->x, p->y );
	Line 1269:             dat.m.add_spawn( *( ids.pick() ), spawn_count * pack_size.get(), x.get(), y.get(),
	Line 6928:         add_spawn( spawn_details.name, spawn_details.pack_size, x, y, friendly );
	Line 7063: void map::add_spawn( const mtype_id &type, int count, int x, int y, bool friendly,
	Line 7067:         debugmsg( "Bad add_spawn(%s, %d, %d, %d)", type.c_str(), count, x, y );
	Line 7074:         debugmsg( "centadodecamonant doesn't exist in grid; within add_spawn(%s, %d, %d, %d)",
  C:\Projects\Cataclysm-DDA\src\mapgen_functions.cpp (17 hits)
	Line 478:                 m->add_spawn( mon_bee, 2, i, j );
	Line 479:                 m->add_spawn( mon_beekeeper, 1, i, j );
	Line 696:     m->add_spawn( mon_fungaloid_queen, 1, 12, 12 );
	Line 719:     m->add_spawn( mon_fungaloid_tower, 1, 12, 12 );
	Line 748:     m->add_spawn( mon_fungaloid_seeder, 1, 12, 12 );
	Line 1108:             m->add_spawn( mon_zombie_jackson, 1, SEEX, SEEY );
	Line 2834:             m->add_spawn( mon_wasp, 1, podx, pody );
	Line 2849:                         m->add_spawn( spider_type, rng( 1, 2 ), i, j );
	Line 3028:                 m->add_spawn( spider_type, rng( 1, 2 ), i, j ); //hope you like'em spiders
	Line 3145:                     m->add_spawn( mon_sewer_rat, 1, i, j );
	Line 3149:         m->add_spawn( mon_rat_king, 1, SEEX, SEEY );
	Line 3166:                         m->add_spawn( mon_sewer_rat, 1, cx, cy );
	Line 3186:                             m->add_spawn( mon_sewer_rat, 1, cx, cy );
	Line 3721:         m->add_spawn( mon_ant_queen, 1, SEEX, SEEY );
	Line 3723:         m->add_spawn( mon_ant_larva, 10, SEEX, SEEY );
	Line 3740:     m->add_spawn( mon_ant_larva, 10, SEEX, SEEY );
	Line 3748:     m->add_spawn( mon_ant_queen, 1, SEEX, SEEY );
  C:\Projects\Cataclysm-DDA\src\map_extras.cpp (31 hits)
	Line 168:                         m.add_spawn( mon_zombie_military_pilot, 1, pos.x, pos.y );
	Line 171:                             m.add_spawn( mon_zombie_bio_op, 1, pos.x, pos.y );
	Line 173:                             m.add_spawn( mon_zombie_scientist, 1, pos.x, pos.y );
	Line 175:                             m.add_spawn( mon_zombie_soldier, 1, pos.x, pos.y );
	Line 195:                         m.add_spawn( mon_zombie_military_pilot, 1, pos.x, pos.y );
	Line 198:                             m.add_spawn( mon_zombie_soldier, 1, pos.x, pos.y );
	Line 215:                     m.add_spawn( mon_zombie_military_pilot, 1, pos.x, pos.y );
	Line 249:                 m.add_spawn( mon_zombie_soldier, 1, p->x, p->y );
	Line 252:                     m.add_spawn( mon_zombie_bio_op, 1, p->x, p->y );
	Line 254:                     m.add_spawn( mon_dispatch, 1, p->x, p->y );
	Line 270:         m.add_spawn( type, 1, mx, my );
	Line 285:                 m.add_spawn( mon_zombie_scientist, 1, p->x, p->y );
	Line 299:         m.add_spawn( type, 1, mx, my );
	Line 315:                 m.add_spawn( mon_zombie_tough, 1, p->x, p->y );
	Line 335:         m.add_spawn( type, 1, mx, my );
	Line 366:             m.add_spawn( mon_turret_bmg, 1, x, y );
	Line 368:             m.add_spawn( mon_turret_rifle, 1, x, y );
	Line 396:             m.add_spawn( mon_chickenbot, 1, 12, 12 );
	Line 400:             m.add_spawn( mon_tankbot, 1, 12, 12 );
	Line 436:             m.add_spawn( mon_turret, 1, 12, 1 );
	Line 441:             m.add_spawn( mon_turret, 1, SEEX * 2 - 1, 12 );
	Line 446:             m.add_spawn( mon_turret, 1, 12, SEEY * 2 - 1 );
	Line 451:             m.add_spawn( mon_turret, 1, 1, 12 );
	Line 575:                 m.add_spawn( mon_zombie_spitter, 1, x, y );
	Line 609:                 m.add_spawn( mon_zombie_smoker, 1, x, y );
	Line 636:         m.add_spawn( type, 1, mx, my );
	Line 700:         m.add_spawn( type, 1, mx, my );
	Line 843:                     m.add_spawn( random_entry( monsters ), 1, i, j );
	Line 866:         m.add_spawn( mon_shia, 1, SEEX, SEEY );
	Line 892:     m.add_spawn( mon_spider_web, rng( 1, 2 ), SEEX, SEEY );
	Line 903:         m.add_spawn( mon_jabberwock, 1, SEEX, SEEY );
  C:\Projects\Cataclysm-DDA\src\mission_start.cpp (9 hits)
	Line 73:     doghouse.add_spawn( mon_dog, 1, SEEX, SEEY, true, -1, miss->uid );
	Line 86:     zomhouse.add_spawn( mon_zombie, 1, SEEX, SEEY, false, -1, miss->uid,
	Line 115:     tile.add_spawn( mon_zombie_master, 1, SEEX, SEEY, false, -1, miss->uid, _( "Demonic Soul" ) );
	Line 116:     tile.add_spawn( mon_zombie_brute, 3, SEEX, SEEY );
	Line 117:     tile.add_spawn( mon_zombie_dog, 3, SEEX, SEEY );
	Line 122:                 tile.add_spawn( mon_zombie, rng( 3, 10 ), x, y );
	Line 124:             tile.add_spawn( mon_zombie_dog, rng( 0, 2 ), SEEX, SEEY );
	Line 127:     tile.add_spawn( mon_zombie_necro, 2, SEEX, SEEY );
	Line 128:     tile.add_spawn( mon_zombie_hulk, 1, SEEX, SEEY );
  C:\Projects\Cataclysm-DDA\src\monster.cpp (1 hit)
	Line 415:                 g->m.add_spawn( type->baby_monster, spawn_cnt, pos().x, pos().y );
```

**Comment by xiaohuynh** [comment]
I don't mind working on those in a separate PR.

Looking at those lines, there are a lot of monsters being spawned that don't necessarily have their own monster group like mon_sewer_rat, for example. The sewer rat shows up in the GROUP_SEWER and GROUP_SAFE monster groups. Is it ok to replace
```
add_spawn(mon_sewer_rat...)
```
with
```
place_spawns(GROUP_SEWER...)
```
which allows other things like snakes/gators to be spawned there?

**Comment by ZhilkinSerg** [comment]
It depends on context, but we can always add new monster groups when necessary.

**Pull request merged**
