### PR TITLE
Fix crazy plague vector difficulty value.

### PR DESCRIPTION
**Pull request by kevingranade**
Thanks discord.

### CODE REVIEW

**Comment by Wishbringer** [comment]
That branch name completely breaks my Git. 😭  Anyone else? Using Windows MinGW.
Don't think Windows supports usage of strange symbols in a filename.
Unable to create "kevingranade-(••)-(-••)>⌐■-■-(⌐■_■).lock" file.

**Comment by ZhilkinSerg** [comment]
> That branch name breaks my Git. sob Anyone else? Using Windows MSYS2.
Don't think Windows filesystems support usage of strange symbols in a filename.
Unable to create "kevingranade-(••)-(-••)>⌐■-■-(⌐■_■).lock" file.

It is possible to use any character from current code page, including Unicode, but you cannot use `>` (`less than`) and some other symbols in names on Windows (see https://docs.microsoft.com/ru-ru/windows/desktop/FileIO/naming-a-file).

But why did you try to create branch with same name? You can simply copy pr with `git pr 24214 upstream` (with git-extras installed).

**Comment by Wishbringer** [comment]
Using GUI frontend called SourceTree for expediency.
Can't control what it does so not sure how to fix it.
Hopefully the problem goes away eventually since the branch has been merged.
Full error message:
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks fetch CleverRaven
error: cannot lock ref 'refs/remotes/origin/kevingranade-(••)-(-••)>⌐■-■-(⌐■_■)': Unable to create 'D:/Source/Cataclysm-DDA/.git/refs/remotes/origin/kevingranade-(••)-(-••)>⌐■-■-(⌐■_■).lock': Invalid argument
From https://github.com/CleverRaven/Cataclysm-DDA

**Comment by ZhilkinSerg** [comment]
I see. That is the issue with SourceTree then. Report it there - https://support.atlassian.com/sourcetree/.

**Comment by ZhilkinSerg** [comment]
Which commands are you trying to run?

`git pull --ff-only upstream master` and `git pr 24214 upstream`  both work fine on MSYS2 for me.

**Comment by ZhilkinSerg** [comment]
Oh, I see an issue now when trying to fetch repo from within Github Desktop:

```
error: cannot lock ref 'refs/remotes/upstream/kevingranade-(••)-(-••)>⌐■-■-(⌐■_■)': Unable to create 'C:/Projects/Cataclysm-DDA/.git/refs/remotes/upstream/kevingranade-(••)-(-••)>⌐■-■-(⌐■_■).lock': Invalid argument
From https://github.com/CleverRaven/Cataclysm-DDA
 ! [new branch]            kevingranade-(••)-(-••)>⌐■-■-(⌐■_■) -> upstream/kevingranade-(••)-(-••)>⌐■-■-(⌐■_■)  (unable to update local ref)
```

**Comment by ZhilkinSerg** [comment]
The PR is merged, so I will delete the branch to fix the issue.

**Comment by Wishbringer** [comment]
That fixed it, thanks. 👍

**Pull request merged**
