### PR TITLE
Enhanced Android build process

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Build "Enhanced Android build process"```  

#### Purpose of change

Configure Android build to use pre-compiled dependencies, add build flags and prebuild task automation.

#### Describe the solution

- Added release build optimization flags and restored `-fsigned-char` to `/src/Android.mk`;
- Added precompiled dependency binaries and headers to streamline build process;
- Added possibility to define number of ndk build jobs via passing `-Pj=#` to `./gradlew`;
- Added possibility to configure automatic release build signing via following strings to `local.properties`  (if `storeFile` is not set, an unsigned apk will be produced):

```
storeFile=
storePassword=
keyPassword=
keyAlias=
```

#### Additional context

All credits go to @Dyrewulfe - it was his work and I am just creating a PR to test these changes.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
# TODO:

- [ ] - use Lua 5.3 instead of 5.1 in zipped dependencies;
- [ ] - read `luaBinary` from `local.properties`;
- [ ] - automatic upload to Dropbox shared folder;
- [ ] - document `local.properties`.

image

image

image

**Comment by ZhilkinSerg** [comment]
@narc0tiq: Can we try to setup Android nightlies on Jenkins?

**Comment by Dyrewulfe** [comment]
Well then.  I was procrastinating a bit about the compiling documentation, and ended up busy with something else and spaced finishing this up.  Does this mean I'm off the hook on writing the instructions?

Also, apparently Google has made some improvements to their NDK.  Compiling with LTO is an option these days, and it does help a decent amount with time lapses.  They can be painfully slow on Android. Clang's ThinLTO isn't terribly RAM hungry(uses about as much RAM as compiling game.cpp does, from what I saw), and adds very little to the build times.

**Comment by narc0tiq** [comment]
> Can we try to setup Android nightlies on Jenkins?

We certainly can -- but @a1studmuffin is already looking into it (as and when he gets some time). I've got some higher priorities myself at the moment, so I hope there isn't any hurry.

**Comment by a1studmuffin** [comment]
Yeah I've got basic accounts set up to look into this (thanks @narc0tiq!) but won't have a lot of time in the next few weeks to address it as I'm pretty busy at work, if someone else is keen to have a crack that's fine with me, otherwise sit tight and I'll get to it eventually :)

**Comment by ZhilkinSerg** [comment]
> Well then. I was procrastinating a bit about the compiling documentation, and ended up busy with something else and spaced finishing this up. Does this mean I'm off the hook on writing the instructions?

Don't worry about docs - you did a great job and preparing Android build is very easy now. Thanks a lot! I will update Android compilation guide, but I would be grateful if you could provide more recent Lua precompiled binaries for Lua (5.2 and 5.3). If not I will try to create them myself later. Existing 5.1 binary works already, but I have to provide various workarounds to support older Lua versions.

> Also, apparently Google has made some improvements to their NDK. Compiling with LTO is an option these days, and it does help a decent amount with time lapses. They can be painfully slow on Android. Clang's ThinLTO isn't terribly RAM hungry(uses about as much RAM as compiling game.cpp does, from what I saw), and adds very little to the build times.

So can we use `$(LTO)` now? Should we provide two versions (with and without LTO) as they both could have different performance on different devices?

**Comment by ZhilkinSerg** [comment]
> We certainly can -- but @a1studmuffin is already looking into it (as and when he gets some time). I've got some higher priorities myself at the moment, so I hope there isn't any hurry.

> Yeah I've got basic accounts set up to look into this (thanks @narc0tiq!) but won't have a lot of time in the next few weeks to address it as I'm pretty busy at work, if someone else is keen to have a crack that's fine with me, otherwise sit tight and I'll get to it eventually :) Sorry to sidetrack from the PR discussion.

Thanks, guys. Good to know it is slowly being worked on. No need to rush with it. :)

In the meanwhile I will try to setup nightly builds myself, upload APKs to Dropbox folder and put links to Android thread on the forums.

**Comment by Dyrewulfe** [comment]
@ZhilkinSerg 
I can take a look into updating the lua version.  I need to finish setting up the dependencies repo anyways. 

As far as the LTO, none of the 4 devices I have for testing on have suffered a noticeable performance hit.  Granted, I didn't profile, just timed the same half hour of time on a save in the shelter basement.  LTO consistently shaved off a few seconds on each( doesn't sound like much, but it adds up since passing time is slow on these toasters. )

**Pull request merged**
