### PR TITLE
add 2 new firefighter tools

### PR DESCRIPTION
**Pull request by Aluminumfoil**
Add the New York hook and pike pole as items and add them to the relevant spawn groups.

#### Summary
```SUMMARY: content "Add the New York hook and pike pole as items and add them to the relevant spawn groups."```

#### Purpose of change

Add greater tool variety. 

#### Describe the solution

Add NY hook and pike pole.
Add them to Fire Truck spawn lists, Firefighter Zombie spawn lists, entry tool spawn lists. 

#### Describe alternatives you've considered

Adding these tools to "tools_entry" may not be the right decision, since it'll make them spawn occasionally in police cars. 
These tools come in all different lengths. I gave stats for one common variant each. 

#### Testing

Spawned items and tested them in game. Spawned firefighter zombies to confirm items present in loot. 

#### Additional context

My intent with damage balance is to reflect that these are robust tools with sharp metal tips, but not purpose built weapons. As such, they should outperform crude versions of real weapons, but fall short of well-made melee weapons of similar proportions.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Neither pictures of these tools that I googled nor definition you made assume any sort of loop by which they could be strapped or otherwise attached to the fireman's gear. As we have a convention that zombies can't hold anything in their hands, I suggest not adding these tools to zombie firefighter's loot list.

**Comment by Aluminumfoil** [comment]
If that's the operating convention, I can go ahead and audit the loot list
for everything else that wouldn't be clipped or strapped to your gear.
There's a lot of it.

**Comment by Night-Pryanik** [comment]
That must be done, sooner or later.

**Comment by Aluminumfoil** [comment]
maybe something like this? 

```
  {
    "type": "item_group",
	"subtype": "collection", 
	
	"//": "the way this is called (most notably: once at 100% on a firefighter Z) looks like it's supposed to be the remains of the gear of a single firefighter."
	
    "id": "fireman_gear",
    "items": [
	"//": "rare, but not unheard of - should occasionally spawn. "
      { "collection": [ { "item": "fire_ax" }, { "item": "axe_ring" } ], "prob": 4 }   
      [ "crowbar", 1 ],
      [ "grapnel", 1 ],
	  [ "pocketwatch", 1 ],
      [ "knee_pads", 2 ],
      [ "entry_suit", 2 ],
	  [ "flask_hip", 1 ],
      [ "emer_blanket", 3 ],
      [ "kevlar", 3],	  
	  
	"//": "ubiquetous - majority of living firefighters would have all of these; I just took 50% of reality to account for lost/damaged gear"
      [ "two_way_radio", 40 ],
      [ "wearable_light", 50 ],
      [ "smart_phone", 40 ],
      [ "rope_30", 40 ],
	  
	"//": "common - a significant minority of living firefighters would have one or more of these."
	  [ "1st_aid", 10 ],
      [ "heavy_flashlight", 10 ],
      [ "wristwatch", 15 ],    
      [ "fireman_belt", 15 ],
      { "group": "tobacco_products", "prob": 32 }, 
	  
	"//": "I'm not sure how this works so I'm leaving it alone for now. Spare batteries aren't a very common item to carry with you, though. Those would be on the truck or in the station." 
      { "group": "ammo_pocket_batteries_full", "prob": 50 },

	  
	"//": "Scifi items."   
      [ "throw_extinguisher", 1 ],
      [ "rx12_injector", 1 ],
      [ "ampoule", 5 ],
      [ "rx11_stimpack", 1 ],
	  [ "stimpack_ammo", 5 ],
      [ "UPS_off", 5 ],
      [ "adv_UPS_off", 2 ],
    ]
  },
```

**Comment by tenmillimaster** [comment]
> Neither pictures of these tools that I googled nor definition you made assume any sort of loop by which they could be strapped or otherwise attached to the fireman's gear. As we have a convention that zombies can't hold anything in their hands, I suggest not adding these tools to zombie firefighter's loot list.

These items would not be attached, but slipped in a tool loop attached to the belt.
image
image
http://www.savajake.com/Leather-Firefighter-Truck-Belt-Set_p_483.html

**Comment by Night-Pryanik** [comment]
> These items would not be attached, but slipped in a tool loop attached to the belt.

Then we must ensure that zombie firefighter with this new tools must also have this belt in its drop list.

>Also, some of these tools have, or are modified with straps.

Then it needs to be mentioned in tool's description.

**Comment by Night-Pryanik** [comment]
> maybe something like this?

Looks good, but it's better be done in a different PR.

**Comment by Aluminumfoil** [comment]
Reverted changes to gear.json so the new items will not spawn on FF Zs.

**Pull request merged**
