### PR TITLE
Add monster/character differentiation to monster hostility

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Features "Add monster/character differentiation to monster hostility"

#### Purpose of change

Add a (rudimentary) selection to monster hostility, optionally filtering out characters until a character actually trips an anger trigger.
First pass at #59565

#### Describe the solution

- Add `aggro_character` (default true) to `monster` and `mtype`. `false` means the monster will be passive towards characters.
- Add some logic to anger triggers to allow flipping `aggro_character` when a character trips the trigger: attacking/killing a friendly critter, hurting the monster and threatening offspring will always do so, the other triggers will have a random chance for each time they trigger
- Add a lot of debugmode messages to aggro changes
- Add a chance to reset the `aggro_character` when the monster reached its baseline anger level 

TODO:
- [x] Actually add the filter to monsters where it makes sense (or hook up some smartypants auto-definition for it)

#### Describe alternatives you've considered

Autodefine it if the monster's aggression is 100, but that was going to exclude some smart-but-hateful mobs like ferals.
Use a flag, but those can't be readily removed/reactivated.

#### Testing

Set a monster to `aggro_character: false` before allowing the bool to flip at all, the mob ignored me but attacked other creatures as expected.
After doing the triggers they each are able to flip the aggro filter, debugmode messages trigger.
Aggroed monsters lose aggro both in-bubble and on load after a long time.
NPCs aggro monsters with the same condition as player, an aggroed monster attacks both.

#### Additional context

Includes the changes from #59766 for sanity's sake until that merges.
The list of monsters with the filter is TBD, but will probably include wasps and other problem kids

### CODE REVIEW

**Comment by Venera3** [comment]
First pass on JSON - ground rules for inclusion: an aggression below auto-aggro level, anger triggers that are hooked up to the aggro system and general flavor (properly dumb critters don't care either way). I also did some buggy bugfixes around armored centipedes and ladybugs/striders that came up. 
If any mod maintainer wants me to include the mods in this PR I can do that, but I'll need a pointer what should be smart in them.

**Comment by Maleclypse** [comment]
The prep-net cyber dogs and tripods.

**Comment by Venera3** [comment]
Explicitly tested the forge of wonders as a sticking point for this by spawning a 9*9 grid of zombies in the middle of the garden. Forgeborn and workers got nice and agitated and beat their teeth in (getting hit, killed and all the rest in the process), they still didn't think to punch their Valued Customer. They still did decide to murder all the fish in their own pond, but that's harder to solve.

**Review by Maleclypse — APPROVED** [review]
Aftershock and Magiclysm look good

**Comment by Maleclypse** [comment]
Should be linked with [#54752](https://github.com/CleverRaven/Cataclysm-DDA/issues/54752)

**Pull request merged**
