### PR TITLE
faction/lang: fix typo: Destitue -> Destitute

### PR DESCRIPTION
**Pull request by keyspace**
Used command:

``` sh
for f in `grep -R Destitue * | cut -d: -f1`; do echo $f; sed -i 's/Destitue/Destitute/' $f; done
```

### CODE REVIEW

**Comment by BrettDong** [comment]
I suggest you not to modify anything in `lang/`. Those files, the translation template and translations, are automatically generated and synchronized with Transifex website.

**Comment by Coolthulhu** [comment]
The faction.cpp change is still good, though.

**Comment by illi-kun** [comment]
Yeah, I misread the listed changes.
@keyspace could you remove everything except change in faction.cpp from this PR, in accordance with BrettDong's comment?

**Comment by keyspace** [comment]
Sure! Force-pushed the commit.

**Pull request merged**
