### PR TITLE
Added soldering requirement

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Changed soldering tools to soldering_standard requirement in various recipes.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Can't understand what's wrong.

**Comment by AMurkin** [comment]
In recipe_others.json
```
@@ -154,10 +154,7 @@
     "time": 20000,
     "book_learn": [ [ "recipe_bullets", 6 ], [ "textbook_fabrication", 7 ] ],
     "using": [ [ "soldering_standard", 10 ], [ "surface_heat", 10 ] ],
-    "tools": [
-      [ [ "mold_plastic", -1 ] ],
-      [ [ "swage", -1 ] ]
-    ],
+    "tools": [ [ [ "mold_plastic", -1 ] ], [ [ "swage", -1 ] ] ],
     "components": [ [ [ "plastic_chunk", 5 ] ], [ [ "scrap", 1 ] ] ]
   },
   {
```
If i did it right.

**Comment by kevingranade** [comment]
BTW, you can just do ```make json-style``` to automatically style it.

**Comment by AMurkin** [comment]
`style-json` i think. Is there a docs about it?

**Pull request merged**
