### PR TITLE
Update missions.json

### PR DESCRIPTION
**Pull request by pantherpusher**
#### Summary
Bugfixes "Fixes crash caused by typo"

#### Purpose of change

To fix a typo that was causing a crash

#### Describe the solution
 
 corrects the spelling so the game doesn't freak out and crash when a wrong name is used

#### Testing

Tried the change on my own copy of the game, it fixed the crash.

### CODE REVIEW

**Review by MNG-cataclysm — APPROVED** [review]

**Review by Maleclypse — CHANGES_REQUESTED** [review]
So your change would break the game. Because you aren't changing it in both places.

**Comment by Maleclypse** [comment]
The repo currently has `{ "mapgen_update": "valahllist_remove_raiding_party", "om_terrain": "pagan_cult_henge" }` and `"update_mapgen_id": "valahllist_remove_raiding_party",`  so they match. If they don't that will cause it to fail.  It may be failing silently but it's still failing. Can you post the error you are receiving on crash?

**Comment by pantherpusher** [comment]
well then what that means is the crash was caused by something I don't know how to fix and only fixed by making it not execute properly

**Comment by Maleclypse** [comment]
That’s fair and can happen. Could you share the crash log so I can try and fix it?

**Comment by Maleclypse** [comment]
Or make an issue for it with the error

**Pull request closed without merging**
