### PR TITLE
Double the amount of time between portal storms

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Balance "Double the amount of time between portal storms"

#### Purpose of change
Reduce the frequency of portal storms somewhat.

#### Describe the solution
Change the EOC slightly.

#### Describe alternatives you've considered
Other time intervals, or making a mod for myself personally and not merging it.

#### Testing
None. Testing PROCs is really difficult, so I didn't bother.

### CODE REVIEW

**Comment by NetSysFire** [comment]
CC @Ramza13

**Comment by Inglonias** [comment]
As this is a balance change, I agree that getting Ramza13 to weigh in would be wise before merging this. Alternatively, if another senior dev wants to express their opinion, that is also fine.

**Comment by Ramza13** [comment]
So I'm not really opposed to this change or in favor.  I have plans for a bigger rebalance of some of this stuff which might overwrite this change or change it around as I'm not totally sure what I want to end result to look like.

**Comment by Inglonias** [comment]
In that case, what I'll do is make a mod and attach it to this issue before closing it.

**Comment by Inglonias** [comment]
[Fewer_Portal_Storms.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8758346/Fewer_Portal_Storms.zip)

**Comment by Inglonias** [comment]
[Fewer_Portal_Storms.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8758374/Fewer_Portal_Storms.zip)

**Pull request closed without merging**
