### PR TITLE
Backport #72703

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Bugfixes "Fixes issue where loading a forge with coal does not work"

#### Purpose of change
Labelled for backport

#### Describe the solution
Backport #72703

### CODE REVIEW

**Comment by osuphobia** [comment]
I think this needs to be modified before backporting, #70359 changed relevant functions.

**Comment by Procyonae** [comment]
Shame Erk can't read >-<

**Comment by I-am-Erk** [comment]
Yep. My apologies. I suggest switching to draft if your PR is passing all tests and shouldn't be merged, especially if it's something that's usually routine like a backport.

**Comment by Procyonae** [comment]
It wasn't passing all tests it failed the basic build, the required stuff just only applies if you're targetting master

**Comment by I-am-Erk** [comment]
Ah dang

**Pull request merged**
