### PR TITLE
Changes to foldable gear

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Reduce amount of keypresses needed for using foldable gear"

#### Purpose of change
Improving the ease of use of foldable items and fixing minor inconsistencies.

#### Describe the solution
Reduce amount of keypresses needed for using rain poncho and emergency blanket by assuming that they get folded into their compact form automatically whenever they're not used, rather than needing to activate them to fold/unfold them.

Sleeping bag descriptions now say that they come with a strap to wear it on back. Rolled up variants also had their encumbrance reduced so that it's actually worth it to carry them on backs; encumbrance is balanced around being slightly higher than wearing a backpack which contains only a folded up sleeping bag and nothing else. The rolled and unrolled variants also now have the same volume, so you wouldn't need to activate them before storing to reduce volume.

#### Describe alternatives you've considered
Making a folded version of every clothing item in game.

#### Testing
Launched the game, made sure that item migration happens properly and no errors happen.

#### Additional context

The volume and weight of sleeping bags may need auditing as well, but I didn't do it as I have no information on either.

### CODE REVIEW

**Comment by AtomicFox556** [comment]
Is there anything preventing this from being merged?

**Comment by I-am-Erk** [comment]
I'm not sure about this, at least for sleeping bags. The worn sleeping bag represents you getting inside the thing. The rolled sleeping bag is worn by throwing it over your back to transport. I believe the same applies to the poncho and stuff.

**Comment by AtomicFox556** [comment]
> I'm not sure about this, at least for sleeping bags. The worn sleeping bag represents you getting inside the thing. The rolled sleeping bag is worn by throwing it over your back to transport. I believe the same applies to the poncho and stuff.

My idea here was to make it unnecessary to activate a foldable item to store it somewhere it wouldn't otherwise fit, instead assuming that it happens automatically like for most clothing. I'm thinking that the character would take to carefully fold up any flexible item if it'd not otherwise fit into a container or if it would unnecessarily complicate finding and retrieving other items from said container. It's still possible to wear sleeping bags in both ways, but now you can just throw your "ready-to-use" sleeping bag in your backpack without it taking up extra space due to not being folded.

Folding technically shouldn't affect item volume either; it'd affect the "longest side" parameter, but sleeping bags are flexible anyway.

**Comment by I-am-Erk** [comment]
The issue is that, while you can wear sleeping bags both ways, you wear them quite differently, with different play effects. in one version you are wearing it to stay warm, in the other you are wearing it for transport. This is an important distinction and the only way to keep them separate that I'm aware of is by an activation.

If there are items in here that can only be packed into a container, and have no other functions when rolled/folded, they can be merged to a single item, but I don't think sleeping bags belong here.

**Comment by AtomicFox556** [comment]
> The issue is that, while you can wear sleeping bags both ways, you wear them quite differently, with different play effects. in one version you are wearing it to stay warm, in the other you are wearing it for transport. This is an important distinction and the only way to keep them separate that I'm aware of is by an activation.

I specifically did not merge folded and unfolded sleeping bags into one item. They're still two different items, but they now have identical volume just so that it occupies the same volume no matter if you decide to carry a "transported" or "worn for warmth" version in your backpack.

**Comment by I-am-Erk** [comment]
So you did. Carry on then

**Pull request merged**
