### PR TITLE
Critical hit coverage

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
This is part of a more comprehensive coverage balance. This adds coverage values for additional categories: melee, ranged and vitals. Certain armour pieces would be more effective at protecting vitals (a.k.a. protection from critical hits).

#### Describe the solution
Currently, monster attacks do not generate critical hits. Characters can crit using either melee attacks or projectile attacks. The implementation of critical hits is a bit scattered around the codebase, so some minor adjustments were made:
- The target body part of a melee attack is determined *after* rolling damage. This was moved into the damage roll.
- Crit mitigation reduces *additional* damage from critical hits, which affects:
  - `projectile_attack_results::damage_mult` for projectile attacks (see `Creature::select_body_part_projectile_attack()`)
  - Bash, cut, and stab multipliers and armour penetration for melee attacks (see `Character::roll_all_damage()` and sub-functions)

The optional fields `"cover_melee"`, `"cover_ranged"` and `"cover_vitals"` are used to affect the damage received from different sources.
```json
    "armor": [
      {
        "covers": [ "torso" ],
        "coverage": 95,
        "cover_melee": 80,
        "cover_ranged": 50,
        "cover_vitals": 5,
        "encumbrance": [ 1, 2 ]
      },
      {
        "covers": [ "arm_l", "arm_r" ],
        "coverage": 50,
        "cover_melee": 45,
        "cover_ranged": 30,
        "cover_vitals": 5,
        "encumbrance": [ 1, 1 ]
      },
      {
        "covers": [ "leg_l", "leg_r" ],
        "coverage": 80,
        "cover_melee": 70,
        "cover_ranged": 45,
        "cover_vitals": 5,
        "encumbrance": [ 1, 2 ]
      }
    ],
```
iteminfo_cover2
armor_menu2

TODO:
- [x] Read new coverage fields into `armor_portion_data`
- [x] Display extra coverage values in-game
- [x] Process the correct type of coverage depending on the damage/effect
- [x] Reduce critical hit damage based on vitals coverage
- [x] ~Update coverage values in json~ This should be left to the experts
- [x] Fix tests in iteminfo_test.cpp to accomodate the new format

The following areas of code may be affected:
| Source file | Areas affected |
| -------------- | ------------------- |
| `armor_layers.cpp` | coverage display information |
| `character.cpp` | infections from filthy clothes |
| `character_armor.cpp` | damage absorption |
| `creature.cpp` | new function `get_crit_factor()` to multiply crit effects, crit modifiers in `select_body_part_projectile_attack()` |
| `dump.cpp` | output extra armour fields |
| `item.cpp` | coverage display info, `get_coverage()` and `get_avg_coverage()` |
| `item.h` | new `item::cover_type` enum for identifying coverage type |
| `item_factory.cpp` | process new fields from json |
| `itype.h` | new coverage fields in `armor_portion_data` |
| `melee.cpp` | crit modifiers in `roll_<type>_damage()` functions |
| `iteminfo_test.cpp` | coverage info display tests |

#### Describe alternatives you've considered
Critical hit protection could also be derived from the clothing's materials.

#### Testing
1. Spawn dozens of NPCs, make both hostile and friendly
2. Spawn dozens of monsters of different factions
3. Observe hits:
  - Character -> Character (crit mitigation based on "cover_vitals")
  - Character -> monster (no crit mitigation)
  - monster -> Character (no critical hits)
  - monster -> monster (no critical hits)

### CODE REVIEW

**Comment by Venera3** [comment]
Unless I missed something major critical hits are a strictly player-only (or character-only at most) system, monsters can't crit at all. Including a vitals coverage is at least futureproofing for when we do wounds/vital hits, but until then it will be of limited relevance. 

Also, what's the melee/ranged split supposed to represent?

**Comment by dseguin** [comment]
> Unless I missed something major critical hits are a strictly player-only (or character-only at most) system, monsters can't crit at all

Thanks for confirming, I though I was going crazy! For now, crit mitigation will only be applied to hits from `Character`s like you suggest, but I suspect that monster crits will be a thing very soon.

> Also, what's the melee/ranged split supposed to represent?

@I-am-Erk would have more details about this, but I figure that different armour pieces would effectively cover you differently based on the kind of hit you're taking. Right now it affects armour damage absorption and infection risk from hits to filthy clothing, but also different effects could be added based on different coverage types.

**Comment by kevingranade** [comment]
Gunplay and the newer throwing attacks monsters can make detour through the player code, and can indeed trigger critical hits.

Melee attacks are handled directly in the monster code and do not trigger crits for now, but lacking a way to mitigate them is precisely the reason they aren't there...

**Comment by dseguin** [comment]
> Gunplay and the newer throwing attacks monsters can make detour through the player code, and can indeed trigger critical hits.

I see that `monster::deal_projectile_attack()` basically wraps `Creature::deal_projectile_attack()`. That's convenient because all the crit handling is taken care of there for projectiles.

> Melee attacks are handled directly in the monster code and do not trigger crits for now, but lacking a way to mitigate them is precisely the reason they aren't there...

I think it would make sense to do something similar for melee attacks: migrate `Character::melee_attack_abstract()` to `Creature::deal_melee_attack()` and have `monster::deal_melee_attack()` wrap it. Maybe something for a future PR...

**Comment by I-am-Erk** [comment]
I want to make sure before diving into review... You list a lot of things that could be affected, but I would think that as long as "coverage" the base stat is unchanged, adding more stats that are independent of it shouldn't have any impact on stuff like wind protection

**Comment by dseguin** [comment]
That's right, those are just areas that make use of coverage in general. I made that list before I started on this to figure out the scope of coverage. I'll update the list to avoid confusion.

**Pull request merged**
