### PR TITLE
[WIP] New square font based on Square-Smallcaps and Terminus (TTF) Bold

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Square-Smallcaps included in game is good. Really good. But for me it has one downside. Small letters of that font too similar with large letters. It is not so intuitive to recognize. So I add small letters to Square-Smallcaps from Terminus (TTF) Bold (http://files.ax86.net/terminus-ttf/), resize it and tweak some things. Now small cap letters looks really different from high caps and it still almost fit square.

Also this font conatins regional symbols of some other languages from Terminus (TTF) Bold. Regional symbols also was resized and scaled to fit square.
They are far less polished than basic ASCII but they looks decent for combat messages in SDL version.
This font was playtested by me a lot.

Also that font scales good at different font size.

Impont note: font was designed for map_typeface on SDL mode, So if you will use it as normal text (like for printing document) it will be not so great - new symbols aligned closer to the center of squares.

Here you can find extra description and screenshots:
http://smf.cataclysmdda.com/index.php?topic=10361.0

### CODE REVIEW

**Comment by mugling** [comment]
Not sure where we are going with this one. @Coolthulhu or @Rivet-the-Zombie?

**Comment by illi-kun** [comment]
Lisence (conditions of distribution/use) of these added fonts is the most important part for reviewed, imo.

**Comment by mugling** [comment]
Yes, I'm very wary about redistributing content we didn't create

**Comment by Firestorm01X2** [comment]
Latest versions of Terminus TTF use SIL Open Fontl License
I use version 4.39
http://files.ax86.net/terminus-ttf/#license
So we have this
https://en.wikipedia.org/wiki/SIL_Open_Font_License

> The Open Font License is a free software license, and as such permits the fonts to be used, modified, and distributed freely (so long as the resulting fonts remain under the Open Font License). However, the copyright holder may declare the font's name as being a "Reserved Font Name", which modified versions then cannot bear. The License permits covered fonts to be freely embedded in documents under any terms, but it requires that fonts be packaged with software if they are sold.

Second part of ofered fotn is Square-Smallcaps that was modification of Square. Square-Smallcaps already included in game.
http://strlen.com/square

So everything looks clear.

**Comment by Rivet-the-Zombie** [comment]
I'm of the opinion that we could really use a good square font, so long as its license would allow us to use it freely.

**Comment by illi-kun** [comment]
@Firestorm01X2 please add the presented info about license in ```LICENSE.txt``` (in the same way it's done for font used currently).

**Comment by Firestorm01X2** [comment]
Done.

**Comment by Firestorm01X2** [comment]
And I have idea to switch default game font on Terminus TTF Bold. It is only because Terminus doesn't' contain regional symbols but Cataclysm is multilingual. But it is for separate PR of course.

**Comment by Firestorm01X2** [comment]
Oops

**Comment by mugling** [comment]
> Don't merge it.

Elaborate?

**Comment by Firestorm01X2** [comment]
I am adding wrong commits here.

**Comment by Firestorm01X2** [comment]
Wrong commits was reverted. 
So, PR is ready again.

**Comment by illi-kun** [comment]
Sorry, I've tested the proposed font but I see no benefits from it comparing to original Square-Smallcaps.ttf. I'll keep this PR for testing by someone else.

**Comment by Firestorm01X2** [comment]
[quote]Sorry, I've tested the proposed font but I see no benefits from it comparing to original Square-Smallcaps.ttf. I'll keep this PR for testing by someone else.[/quote]
Even real smallcaps letters that really differs from highcaps?

**Comment by Zireael07** [comment]
@Firestorm01X2: You pushed to bad branch again!

**Comment by Firestorm01X2** [comment]
I see

**Comment by Firestorm01X2** [comment]
Too much dirty thins. I am closing this PR. I'll maybe recrate it later. I messed with branches.

**Pull request closed without merging**
