### PR TITLE
Cleanup legacy recipes, robots.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Clean up some ancient nonsense recipes that made autonomous robots capable of targeting and FFR by plugging an arbitrary CPU into a board.

#### Describe the solution
Just deprecate some recipes from the base game.
These should fit fine in the Craftable robots mod.
Not mergeable because it doesn't do the deprecation properly yet.

#### Alternatives
This kind of thing could use some higher level modules salvaged from existing robots, making it reasonable to harvest from destroyed robots instead of crafting things from scratch.  If anyone is interested in doing that, I'll happily put this on hold for a while in lieu of that solution.

### CODE REVIEW

**Comment by Rail-Runner** [comment]
Maybe change them into repairing recipes, to restore broken robots into functional (inactive) ones?

**Comment by anothersimulacrum** [comment]
>  Or if not done in this PR, would it be feasible as mainline content at least?

> This kind of thing could use some higher level modules salvaged from existing robots, making it reasonable to harvest from destroyed robots instead of crafting things from scratch. If anyone is interested in doing that, I'll happily put this on hold for a while in lieu of that solution.

Looks like it

**Comment by Rail-Runner** [comment]
Well, implementing various scavenged-only modules for robotics requires way more work than just writing repair recipes for robots. Would it be an okay abstraction to just have robot repair recipes for a start?

**Comment by kevingranade** [comment]
So a repair recipe is going to do what, replace some number of components to turn any destroyed robot into an inactive robot of the same kind?

So to model destruction of irreplaceable modules without modelling them explicitly, the simplest thing to do would be to have some chance of crafting failure that remains no matter how skilled you are.  That would be significantly less useful than modelling the critical components directly, but would let you reclaim some fraction of the destroyed robots.

To clarify the "higher level modules" thing since some people have shown interest offline:
My idea is that we have some number of high-level modules that control critical functions of certain robots, the crafting recipe for each robot specifies what is required for each kind of bot.

For example literally every robot might have, "navigation module", a number of "servo control module"s based on how complicated it is, and a "vision analysis module".  Military bots might have one "targeting module" for each weapon, and if the bot is capable of features like selecting targets it might have a "programmable friend or foe module".

Likewise fixed turrets would have a "servo control module", "vision analysis module" and a "targeting module", but might NOT have a friend or foe module, instead shooting at everything they can see, but possibly limited by a field of fire adjustment.  This flavor of turret doesn't exist in the game, but could.

To represent the turrets we DO have in the game, you would additionally add a friend-or-foe module to the turret to make it capable of deciding not to shoot you.

Existing bots would have a chance to drop these same components when disassembled, with recovery chances adjusted as usual for "butchery".

**Comment by kevingranade** [comment]
Superseded by #30456

**Pull request closed without merging**
