### PR TITLE
Add clang-tidy Travis job

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Infrastructure "Run clang-tidy on Travis"

#### Purpose of change
The ultimate goals are:
* Run static analysis in CI to detect bugs.
* Have a sensible `.clang-tidy` file in the repo to make it easy for devs to run `clang-tidy` locally with the right checks.
* Have the facility to add our own checks to enforce our own coding conventions or detect common mistakes specific to the CDDA codebase (e.g. ensuring that all strings are translated).

#### Describe the solution
Initially this is a very minimal clang-tidy run; only using on-by-default checks, and amongst those disabling all the ones that currently fail on this codebase.  The idea is that we can gradually enable more checks as we tidy up more stuff.

#### Additional context
My biggest concern is how long this will take, and whether we risk hitting the Travis job time limit.  To help mitigate that I've set this job to not run any tests.

Pushing this as an experiment to see how it goes.  Probably will require multiple tweaks to figure out the right Travis config; hence marking as WIP for now.

### CODE REVIEW

**Comment by kevingranade** [comment]
Does clang-tidy need the code compiled before invocation? Otherwise we can pass a build target to the makefile to *just* run clang-tidy.

**Comment by jbytheway** [comment]
> Does clang-tidy need the code compiled before invocation? Otherwise we can pass a build target to the makefile to _just_ run clang-tidy.

This is certainly possible in principle, but I haven't found a neat way to do it in practice.  The two easy ways to run clang-tidy are:
* First build a compile commands database and then run clang-tidy.  To build such a database with CMake seems to require actually compiling everything, although in principle it needn't.
* Use CMake with it's built-in clang-tidy support (which is what this PR does).  This runs clang-tidy before compiling, but does still run the compiler.

In searching so far the only thing I've found that looks like it might work is [compiledb](https://github.com/nickdiego/compiledb).  But I'm not going to try too hard unless it seems like the speed is actually a real problem.

**Comment by kevingranade** [comment]
Yipes, made it to about 61%.
So are the warnings about clzones.h a clang-tidy output? If so yay there's an output, but yipes, that takes forever.

I have a really goofy idea.
1. Add a target that only compiles ~50% of the source.
2. After a successful build, those object will be cached in ccache.
3. Incrementally add more files to the build target.
4. As long as we don't edit too many files, it might be able to complete a run, invoking clang-tidy on just whatever files have been changed.

**Comment by jbytheway** [comment]
The `clzones.h` things are just regular clang warnings (possibly appearing now because I've switched to clang-8?).  I wasn't expecting clang-tidy messages because I've disabled all the checks which currently trigger.

Does Travis not cache ccache items on an unsuccessful build?  I feel like it should, but I guess I can understand why it wouldn't on a timeout even if it did in some cases.

Unfortunately, based on my local experiments, I don't think ccache works for clang-tidy.  May be wrong, though; haven't investigated in detail.

Even if that did work, I think that solution is too fragile.  Back when I added the ASan build I was fooled into thinking it fit within the 50 minute limit because it did when everything was in cache, but shortly thereafter someone made a big enough change that it didn't fit anymore, and then it never fit again (until I turned off certain tests to speed it up).  A similar thing would happen if we tried something like that here, I think.

My thought is as follows: first build a compilation database, then randomly permute the source files and run clang-tidy in sequence up to some time limit.  That way any particular error should hit fairly soon.  In particular, issues in headers are almost guaranteed to be found since headers are included from multiple places, so we get better coverage than it might appear.

**Comment by kevingranade** [comment]
> Does Travis not cache ccache items on an unsuccessful build?
It does not.

> Random shuffle through sources
I'm not clear how that works in detail, but seems like it'll work.

Is that at all similar to:
Shuffle source files.
Build source files in this random order, checking time remaining in between.
Bail out before we run out of time.

**Comment by jbytheway** [comment]
> Is that at all similar to:
> Shuffle source files.
> Build source files in this random order, checking time remaining in between.
> Bail out before we run out of time.

Yep, pretty much exactly that.

**Comment by jbytheway** [comment]
That works, but it's wasting a *lot* of time on creating the compilation database, so I'm going to try using [compiledb](https://github.com/nickdiego/compiledb) instead.

**Comment by jbytheway** [comment]
I think this is ready now, but can't be tested properly until the unrelated Mingw errros are resolved, so I'll rebase it when that happens.

**Comment by jbytheway** [comment]
Done, and got the green tick.  So this seems good.  Just a question of whether you're willing to spend ~45 minutes of Travis time per check on this.

**Comment by kevingranade** [comment]
It looks like we're getting through almost all of the files now, maybe we can just extend the sampling approach a bit and cut it off after ~15 minutes instead of ~40?  I'd pull the trigger on a ~15 minute build step right now and we can look at alternatives later.

Now that the compilation DB creation is pretty fast, what if we just eval the cpp files that were changed instead of a random subset?  This potentially misses header file changes sometimes, but it's unlikely to persist for long, and a more complex approach can find a cpp that includes said header and add it to the list.

**Comment by jbytheway** [comment]
I like checking the changed files first.  That makes sense.  I've implemented that and the 15 minute limit.

I'm a little more leery about such a short time limit; that seems like it will make it rather likely that we end up with errors which get merged and then cause grief down the line.  But we can try it and see.

I think this is now ready as it stands.  Might take a while to get a clean test report though, with what else is going on (and it's impossible to get a pass from gorgon, because of the P30k problem).

**Comment by kevingranade** [comment]
Reran without errors, but I don't see clang tidy actually running.  Am I missing something?

**Comment by jbytheway** [comment]
Indeed, looks like I broke it somehow.

**Comment by jbytheway** [comment]
The problem is that it deemed the change to be just json and so skipped all the builds.

This is because the `git diff --name-only $TRAVIS_COMMIT_RANGE` failed with:
```
fatal: Invalid symmetric difference expression 65a05026e7306b5d1228dc6ed885c43447f128b5...8a6b9d95ca018ad53ef79a95eb819738497f8567
```
So that's a bit odd.  Those are both commits it should know about, but maybe they're on divergent branches and this syntax doesn't work in that case?

**Comment by jbytheway** [comment]
After thinking about this further, I guess it's because the shallow clone doesn't fetch enough commits to see the one being compared against.  I've pushed a workaround to make it fail safe in this case, but we might want to actually try to fetch the relevant commit.

**Comment by jbytheway** [comment]
After some fixes to the scripting, I think it's good now.

**Pull request merged**
