### PR TITLE
Continue Evolution of Survivor Armor Take 2

### PR DESCRIPTION
**Pull request by keampe**
#### Summary
Balance "Update and refine Kevlar Jumpsuits for the Tailoring overhaul. Take 2"

#### Purpose of change
The tailoring overhaul made fabrics more consistent but the survivor armor wasn't updated with the new materials.

#### Describe the solution

Changed the suits and recipes for the jumpsuits to use the more accurate material amounts, then took a further look.

Some other changes

   1. The light Kevlar jumpsuit, Kevlar jumpsuit and heavy Kevlar jumpsuit reduced the Kevlar layer by 0.3mm and gave them a 0.3mm layer of Synthetic Fabric keeping the same overall thickness. Why? Kevlar degrades in sunlight. It's the reason why all Kevlar products meant for outdoors applications have a covering or are embedded into something (like racing tires). I assume that the fur, faux fur, and neoprene have an outer layer of their respective materials. Of note: Nomex also degrades in sunlight - but synthetic fabric is nylon - and that's a terrible coating for flame resistant gear. I left it alone - Don't know what to do about it. Also note: Kevlar does come in coated UV resistant varieties, but the survivor doesn't get to pick and choose often.
   2. Removed the raincoat or equivalent from the crafting recipes. Doesn't need it.
   3. Removed the Duct Tape from the crafting recipes. Duct tape, while I'm a huge fan of it in general, is not part of permanent clothing.
   4. Added in fasteners. Lots of them. These are to keep the fit close to the body in some areas while allowing freedom of movement. For example keeping the forearms and upper torso snug while leaving the shoulders, upper arms and elbows free gives good arm movement while keeping the cuff closed. Also, this is a [sturdy] garment and closures are a weak point - they're re-enforced.
   5. Removed the [waterproof] flags. The Nylon layers is water resistant, so I left the [rainproof] flag. Just don't go swimming in it. :)
   6. Adjusted the amounts of materials used for Kevlar to be more appropriate - and changed them from layered Kevlar panels to Kevlar sheets where they were still layered panels.
   7. Kevlar thread - used in these recipes - is often of the coated variety. I left it for this reason.

#### Describe alternatives you've considered

Adjusting the thickness. These suits are very thick for the normal layer. The "Light" Kevlar jumpsuit has a minimum thickness of 1.5mm over 10% of covered areas and 2.5mm thickness over 90% of covered areas. The regular Kevlar Jumpsuit is 2.2mm thick minimum - but this is only over 1% of it's coverage. 18% is 3.2mm and 81% is 4.2mm. This is way over the 2mm guidelines listed in the armor balance doc. Still, they passed earlier muster and wetsuits are often as thick and one could wear a jacket over them.
#### Testing

Modded my game loaded up and all recipes showed up. No errors in loading.
#### Additional context
None I can think of.

### CODE REVIEW

**Comment by keampe** [comment]
Not sure why it's failing the linting check... Might have to re-upload again. Tomorrow.

   - Shane

**Comment by keampe** [comment]
Ran them through that a bunch of times. The error I'm getting is on line 1 - which, of course, is just a [ . I'll try things a different way after work.

   - Shane

**Comment by bombasticSlacks** [comment]
like I said I think your editor (whatever it is) is taking what you format and then writing windows line endings instead of UNIX so it is saying every line changed.

**Comment by keampe** [comment]
I'm using Notepad ++. Is there a setting I should be aware of? If so, that'll make things easier.

   - Shane

**Comment by Maleclypse** [comment]
You want it to say `UTF-8` for encoding

**Comment by keampe** [comment]
Closing and restarting.

**Pull request closed without merging**
