### PR TITLE
Fix msg when trying to close an open crate [Fix #11142]

### LINKED ISSUE #11142: to close an open crate message
I built an open crate. Not sure what they are for, but since it was described as being "open" I tried to close it and got the less than helpful reply "There's an open crate in the way!". Now I think it was an user error to try to close the crate, realizing now that I should have used the construction to seal it, but the message could have told me that or at least say something more intelligent.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8321465-to-close-an-open-crate-message?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by drbig**
What more can I write about it?

### CODE REVIEW

**Comment by BevapDin** [comment]
> What more can I write about it?

New players might not know that this action is done through the construction menu, maybe hint that?

Actually, couldn't you start the construction from within that examine function? looking at `place_construction`, only the construction id seems to be needed, the place is already know,  add a check for required tools/components, etc.

**Comment by drbig** [comment]
I'm all for a better wording of the message, maybe:

"You'll need to construct a seal to close the crate!"

As for auto-starting construction: this feels to me like overdoing it. Is there any case where examining something auto-starts crafting/construction?

**Comment by BevapDin** [comment]
> As for auto-starting construction: this feels to me like overdoing it.

Yes, it would be overdoing it, the hint to constructions is enough. But it would also be a create user experience, maybe. (-:

> Is there any case where examining something auto-starts crafting/construction?

Not as far as I know. Idea for another PR:

Maybe it could also be used for the cleanup (wreckage, rubble), taking down the curtains functions. Changing those into player activities makes them interruptible and allows them to take more time. Those actions only take 200 move points (=12 seconds). But this is just a suggestion.

**Comment by drbig** [comment]
I'm all for an issue dedicated to discussion on auto-starting crafting/construction/actions. At a glance it does look like a better user experience. My concern would be in making it consistent and not 'surprising'.

**Comment by BevapDin** [comment]
> I'm all for an issue dedicated to discussion on auto-starting crafting/construction/actions.

Make it so. It does not have to be an automatic action, it can still contain a question popup. For actions that work only on very specific terrains / furnitures this could be more user friendly than the ever growing construction menu.

**Pull request merged**
