### PR TITLE
Fix some name plurals having to do with crafting ammo

### PR DESCRIPTION
**Pull request by Cyrano7**
No more crafting ammo using "8 coppers" or "5 gunpowders".

Edit: Also fix plural form of chunk and lump of steel.

### CODE REVIEW

**Comment by keyspace** [comment]
Already covered by #19946.

**Comment by BrettDong** [comment]
OH sorry @Rivet-the-Zombie forgot to remind you, this PR should be closed. Plural names of stackable items were removed in my preceding PRs and they shouldn't appear anymore.

**Comment by BrettDong** [comment]
OH sorry @Rivet-the-Zombie forgot to remind you, this PR should be closed. Plural names of stackable items were removed in my preceding PRs and they shouldn't appear anymore.

**Comment by Rivet-the-Zombie** [comment]
Shouldn't this fix still help with other instances of stacked items, like when you're looking at a pile of stuff on the floor?

**Comment by BrettDong** [comment]
plural

Now stackable items should all be displayed as `singular name (charges)`.

**Pull request merged**
