### PR TITLE
Use globs to list source and header files in cmake build

### LINKED ISSUE #17575: Use wildcards for build-related files
I'm not good at all this makefile/cmake business, but I found this:
```
file(GLOB HEADERS
    ${CMAKE_SOURCE_DIR}/src/*.h
)
```

And ditto for sources.

Could we use that to avoid having to edit `CMakeFiles.txt` every time a new file is added?

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #17575.

I'm no CMake expert, but this fixes the CMake build on my machine (previously it was failing with errors related to the fact that safemode_ui.cpp wasn't included in the list of source files).

### CODE REVIEW

**Comment by nornagon** [comment]
(One [caveat](http://stackoverflow.com/questions/2110795/how-to-find-all-c-files-for-cmake-build-system#comment12760668_3366701): just running `make` won't detect an added file. If you make a new file in `src/`, you'll have to run `cmake` again to get it to notice.)

**Comment by illi-kun** [comment]
@Coolthulhu as original author of idea about using of GLOB instead list of files, with the pro et contra presented in the reference above, do you think it worth merging or keeping of status quo is safer?

**Comment by Coolthulhu** [comment]
Our `make` already uses equivalent of globs. Making `cmake` and (if possible) CodeBlocks and Visual Studio do it too shouldn't cause any more problems. Assuming it works.

**Comment by illi-kun** [comment]
Okay, so resolving the conflicts is all we need to merge this PR.

> Making cmake and (if possible) CodeBlocks and Visual Studio do it too shouldn't cause any more problems. 

I already did it for CodeBlocks in #17655.

**Comment by nornagon** [comment]
Conflict resolved!

**Pull request merged**
