### PR TITLE
Remove DURABLE_MELEE on cudgel (#51251)

### PR DESCRIPTION
**Pull request by KonH**
#### Summary
Balance "Remove DURABLE_MELEE on cudgel"

#### Purpose of change

Requested at #51251.

#### Describe the solution

DURABLE_MELEE on cudgel item removed, no other changes applied.

### CODE REVIEW

**Comment by ISuckM8** [comment]
The rise and fall of the cudgel.

**Comment by Maleclypse** [comment]
So we have this go through things all the time.   The ideal solution would be that there is a cudgel item that can be found places like cabins and maybe woodworking shops, that would have been seasoned and possibly even varnished and would have the durable melee flag. Conversely the player would only be able to make "makeshift_cudgel" that lacked the durable melee tag.   Maybe some long term transformation recipes could be done to makeshift cudgels to season the wood and create cudgels with the durable melee flag but that wouldn't have to be part of the original PR.  Anyway I figured I'd let you know what the ideal solution is in case you are willing to pursue part or all of it.

**Comment by KonH** [comment]
@Maleclypse
Thanks for feedback!
I'm not sure about participating in the final solution for now, it's required much more understanding of gameplay mechanics and codebase.

**Comment by JerryLin1** [comment]
This should close #51251

**Pull request merged**
