### PR TITLE
Update entry_tools.json to-hit values to use the new categorized system

### PR DESCRIPTION
**Pull request by RandDenner**
#### Summary

Balance "Adjusts all of the weapon usable tools in the entry_tools list to use the new categorized to-hit system"

#### Purpose of change

Motivated by pending update #56953.
This is just another tiny step in rationalizing the entire weapon set into a coherent whole, instead of the patchwork of various updates going back years that it is now.

This step is just a quick fix for various crowbars and the ice axe from the "entry_tools.json" file that weren't yet updated from archaic, manually set to-hit values.

#### Describe the solution

Edit: well it started simple, but then the DPS checks complained after some stat adjustments and I was obliged to reduce the base damage of the (small) crowbar and ice axe to get their DPS back into the expected range.

The first adjustment to code was to slightly alter the code testing for the expected DPS (in effective_dps_test.cpp) for the crowbar from 15.0 to 15.5, but this was reverted after weight adjustments brought DPS way above the target of 15.

Ultimately the crowbar went from bashing 20 to bashing 15 due to the weight drop and decrease in swing time, and the ice axe was reduced from bashing 24 to bashing 20 for the same reason. Per hit damage decreased but DPS is almost identical.

A Further problem developed with a test (back from the 2020 implementation of pockets) failing because it was based on specific crowbar stats (mostly the weight) that have been changed. Alteration of the test to non game data (in mods/TEST_DATA/items.cpp) was determined as the preferred solution.

#### Describe alternatives you've considered

The alternative is just plain old not doing it.

#### Testing

No issues when standard game version loaded with altered item stats. Despite the test complaints, the tool belt items work fine in the pockets/holsters.

#### Additional context

None

---
#### Notes

Rationale for changes to lengths, weights, and volumes:

Crowbar:
looked at a variety of 18" crowbars.
Weight was averaging 550 grams.
Length reduced to 45 cm to match 18" standard (dropping fractions, plus it's curved).
Volume adjusted to account for steel density (8gm/cm3) giving a volume of 68.75ml. Since there's a significant curve causing some increase in storage difficulty rather than straight volume, I'm rounding up to 100.

Ice axe:
looked at a wide variety, noticed that the listed one was smaller than average, so increased it slightly.
Weight was averaging 300 grams.
Length increased to be closer to average of 50cm.
Volume adjusted to account for actual shape and size (45x1.5x1.5 + 5x1.5x1.5 = 112.5ml) then increased by 25% to 140 to account for T-shape issues while storing in containers.

Makeshift crowbar:
Just used reason.
Weight should be less than actual crowbar due to the fact that it's a hollow pipe and does less damage.
Length matching crowbar.
Volume matching crowbar.

Heavy crowbar:
Looked at some 60" crowbars online. Weights were nowhere near 18 pounds.
Weights averaging about 9 pounds, so 4000g is about right.
Length unchanged.
Volume derived from math. 4000g divided by 8g/cm3 = 500 ml. Even accounting for storage difficulties from the curved end, 1L is a bit much, so reducing to 725 ml, which matches % increase to volume for crowbar for the same storage problem logic.

### CODE REVIEW

**Comment by RandDenner** [comment]
I'm uncertain why General build matrix / Basic Build and Test (Clang 6, Ubuntu, Curses) is failing.
I changed a few lines and the linter is giving me back the same text as I put in it.

**Comment by RandDenner** [comment]
Oh, I get it now. Those are new.
Looks like there are two issues.

First, a DPS check failed since the crowbar's DPS went up when it was properly categorized.
I'm not sure a 2.74 point damage increase for a heavy metal bludgeon is a real problem.

Second, it seems to be having an issue with density.
I didn't change any volume or weight stats, so either it's bugging or was ignoring the problem until I changed the file and brought it to the test's attention.

**Comment by RandDenner** [comment]
Okay, so the density business isn't my problem and I can ignore it.

Making the resolution next step to get the crowbar DPS back into the expected range.

A problem is that the test should ALSO be having an issue with the makeshift crowbar (and heavy crowbar?), and it's not.
Probably because it isn't checking them against a target value.

Table                        starting to hit and damage:    new to hit and damage
Crowbar                   -1 th, bashing 20                    effective +2, bashing 20
Makeshift crowbar   -2 th, bashing 12                    effective +2, bashing 12
Heavy crowbar         N/A                                        effective +2, bashing 45

First try: going to reduce crowbar base damage to 18 and see if that's acceptable for the DPS test.

**Comment by esotericist** [comment]
someone else reported weirdness with the density tests. that'll probably need pursuing.

for the crowbar, @Aerin-of-the-Toast was also looking at tinkering with it a bit.

while i am not particularly against the dps of the crowbar going up, some research during the conversation i had with aerin suggested that the crowbar as we have it in game might actually have too much mass; i was looking at similar length steel crowbars, and they all seemed to be substantially lighter than our basic crowbar. the volume might also be *slightly* (but not substantively) low, but i at least am not super concerned about that.

ultimately, if you end up going through with tinkering with the dps of a tested weapon, you'll also need to be adjusting the test. the purpose of the tests is to make sure someone isn't *accidentally* adjusting the effective properties of certain stable objects, that isn't itself an obstacle to *intentionally* changing the effective properties. if you're prepared to defend the new value, and folks reviewing it agree, it can totally change.

**Comment by NetSysFire** [comment]
>Okay, so the density business isn't my problem and I can ignore it.

>someone else reported weirdness with the density tests. that'll probably need pursuing.

I can confirm that. Do not worry about it.

Also, I am a tiny bit amused by the fact that the "Game: Balance" label is literally quite fitting here.

**Comment by RandDenner** [comment]
All right, that's pretty straightforward.

I think adjusting the crowbar's base damage down 2 points from 20 to 18 should be sufficient.
Given that it's a bit heavy, as stated. If I adjust the weight down a bit, that'll make it a bit more rational, too.

Also, it's a bit weird that the makeshift crowbar is only doing 60% of the actual crowbar's damage (12 vs 20) despite it weighing more despite being less volume, and actually being longer as well, so reducing the crowbar damage a couple of points towards it is not unreasonable.

But tomorrow I'm going to look at the weights, volumes, and lengths more closely, anyway.
Might as well since I'm already doing it.
I'll probably convert this to a draft after I see the new test results.

Gonna wait on merging a day or so until I have a more detailed look at some items.

**Comment by RandDenner** [comment]
Okay, so as I suspected, the tester is reporting:
```
tests/effective_dps_test.cpp#L416

Approx( 15.7825354704 ) == 15.0
```

Less than 1 point of DPS increase for a key makeshift weapon used for general comparisons. That's acceptable imo.

@esotericist, could you please walk me through what I have to do to get the test on board with that DPS.
I think I understand the procedure, but it's a bit beyond my certainty and I don't want to screw it up.

**Comment by RandDenner** [comment]
Converting to draft PR...

**Comment by RandDenner** [comment]
First pass on reality check:

A 50 cm/ 19 inch crowbar should top out at about 600 grams.
They're definitely twice as heavy as they should be.

The makeshift crowbar, being made of a heavy but ultimately hollow pipe (probably of lesser steel, as well) and doing less damage should weigh less. Maybe 400 grams is about right.

Volumes should be pretty much identical, since it's a makeshift tool to do the exact same job.

The heavy crowbar is WAY out of line at 8 kg. Even half that is overkill.
2500 grams or so is about right, given that it's about 4 times as long, and probably a bit thicker overall.

**Comment by RandDenner** [comment]
I'm considering adding a couple of more crowbar tools.
1) a smaller "flat prybar" about 15"
2) an intermediate 36" "wrecking bar" (twice the size of our current crowbar)
3) renaming the heavy crowbar a "demolition bar"

These all more closely reflect real-world terms and common tools.
One issue is adding two new crowbars shouldn't generate 2/3ds more tools in worldgen.
(Great, now I have to look at worldgen...)

**Comment by RandDenner** [comment]
Testing making a slight change to "effective_dps_test.cpp" in order to see if test will succeed.
See the specific file update notes for details.

**Comment by RandDenner** [comment]
All right. Build passed. Now to correct some weights and volumes.

**Comment by RandDenner** [comment]
Rationale for changes to lengths weights and volumes:

Crowbar:
looked at a variety of 18" crowbars.
Weight was averaging 550 grams.
Length reduced to 45 cm to match 18" standard (dropping fractions, plus it's curved).
Volume adjusted to account for steel density and some curvature. Straight would be 180 ml (45x2x2), rounding up to 200.

Ice axe:
looked at a wide variety, noticed that the listed one was smaller than average, so increased it slightly.
Weight was averaging 300 grams.
Length increased to be closer to average.
Volume adjusted to account for actual shape and size (45x2x2 + 5x2x2 = 200ml) then increased by 25% to 250 to account for shape issues in containers.

Makeshift crowbar
Just used reason.
Weight should be less than actual crowbar due to the fact that it's a hollow pipe and does less damage.
Length matching crowbar.
Volume matching crowbar.

Heavy crowbar:
Looked at some 60" crowbars online. Weights were nowhere near 18 pounds.
Weights averaging about 9 pounds, so 4000g is about right.
Length unchanged.
Volume derived from math. 4000g divided by 8g/cm3 = 500 ml. Accounting for curved end, 1L is a bit much. Reducing to 600 ml.

**Comment by RandDenner** [comment]
Reverting change to crowbar volume (200 back to 170) to see if this stops the "item_contents_test.cpp" from unnecessarily wetting the bed doing some puzzling checks.

**Comment by RandDenner** [comment]
Found some DPS issues.
Reverting effective_dps_test change and adjusting base damage.

**Comment by RandDenner** [comment]
Readjusting ice axe damage to achieve target DPS again

**Comment by RandDenner** [comment]
Adjustments to DPS targets successful.

I am utterly stumped on the tool belt test issue.

Anyone got a clue? I don't...

**Comment by RandDenner** [comment]
Okay, I tested in-game and there were no problems with the tools and the tool belt's pocket and 5 holsters with the modified tools.

So the "item_contents_test" is complaining about something that doesn't seem to be a problem, but I really don't understand anything about the tests in lines 69 through 84.

I can't understand the logic behind the test at all. So I'm going to ignore it and finish up.

**Comment by RandDenner** [comment]
Changed the volume of the crowbar from default 170ml to new 200ml value.

**Comment by RandDenner** [comment]
In-game testing indicates that the complaints from the old 2020 pocket implementation tests are irrelevant.
image
image

Density issues are also not a problem with my PR. Ready for merge.

**Comment by RandDenner** [comment]
Fixed a math logic issue with the volumes.

I think this is ready for merge.

**Comment by RandDenner** [comment]
Convert to draft while I fix the tool belt test code.

**Comment by RandDenner** [comment]
Okay, I think I fixed all the merge-stopping errors!

**Comment by RandDenner** [comment]
Nope. Still one error Clang-tidy (clang-12, tiles) found.

**Comment by RandDenner** [comment]
Double spacing after periods in descriptions

**Pull request merged**
