### PR TITLE
I volunteer as tribute: Claiming a maintainer role on Classic Zombies.

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Mods "Set I-am-Erk to maintainer for Classic Zombies. See PR for concepts."```

#### Purpose of change
Classic zombies is currently a basic exclusion mod, but has the potential to be much more, which is why I advocated to keep it when we removed exclusion mods.

#### Describe the solution
For now, just set me as maintainer. I've got other things on the go.

The long term plan is to turn Classic Zombies into Cataclysm: Dark Days of the Dead, a Romero-inspired zombie survival game set in the modern day.

I'll create a project on my own repo with some planned changes, but what I'll get started on soon (ideally with help from interested parties):
- Expand blacklists to include ai, mutagens, cybernetics, power armour, and science fiction gear
- Create a new Zombie Bite effect that makes you incredibly ill (not a guaranteed death, but Very Bad News) and give it to zombies
- Look into applying some type of targeted shot system (there are plans for this for mainline) and require headshots to kill zombies
- Remove the [FILTHY] tag and just have most zombies wearing semi-useless rags and carrying nothing, with a few notable exceptions.
- Start outlining a whole new story mode, blacklist anything related to the Cataclysm storyline and develop a new one.
- Recruit other people excited by a return-to-roots zombie game

#### Describe alternatives you've considered
This could be left as is, but there's so much lost potential in just blacklisting a bunch of monsters. By taking the excisions further it starts to become a flavour of its own. 

#### Testing
n/a

#### Additional context
Conveniently, the development direction of cataclysm:DDA and cataclysm:DDOTD are almost completely parallel, so as a full conversion mod this still benefits from nearly any addition to the base game.

I see this as the polar opposite of Aftershock, a version of cataclysm that takes realism to the opposite extreme and leads to a deadly expedition to the local pub, fighting zombies with a cricket bat, in the desperate hope that the military might arrive before our insufferable stepfathers get bitten. This is the cataclysm you could see happening in your backyard, or your local mall. I hope.

### CODE REVIEW

**Comment by Scrivener07** [comment]
Awesome, thanks for doing this!

**Comment by Scrivener07** [comment]
For a low effort thing, the mod tile `Cataclysm: Dark Days of the Dead (formerly Classic Zombies)` is too many characters to display on the mod list tile in game. Perhaps just title it `Cataclysm: Dark Days of the Dead`, and put "(formerly Classic Zombies)" in the description field?

**Comment by Scrivener07** [comment]
Im a fan of the return to roots zombie survival.
All the anomaly and extraextradimensional creatures certainly are cool and have their place in CDDA but its not the experience Im personally after for my role-play runs.
I like the idea of a build-your-own-apocalypse where we have a platform to make that possible via mods.

To expand on the build-your-own-apocalypse point, what are the guidelines and possibilities for mod distributions?
If having what Ill call "sub-options" for a mod entry is not possible then what do you think about having Dark Days of the Dead as a "family" of separate mods which can be mixed and matched.

# Proposal
This is how I propose the mod be organized.
If having "sub-options" for a mod entry is not possible then, then I propose that the expansion to Classic Zombies be made as a "family" of separate mods which can be mixed and matched.


### Dark Days of the Dead
> Start outlining a whole new story mode, blacklist anything related to the Cataclysm storyline and develop a new one.
This could be perfect for the "core" of the mod.
Remove references to stuff like portals and extraextradimensional creatures.
Reenvision the story line & lore flavor to fit a classic zombie apocalypse.

Add everything that sets the base tone for this, yet is also compatible for what Ill call the debatable points below.

### Dark Days of the Dead - Low Technology
> Expand blacklists to include ai, mutagens, cybernetics, power armour, and science fiction gear
This is a pretty large dimension to the game tieing into maybe character builds an display styles.
An aspect of this mod I feel should be option, but I still feel is a great option to have.

### Dark Days of the Dead - Bad News Bites
> Create a new Zombie Bite effect that makes you incredibly ill (not a guaranteed death, but Very Bad News) and give it to zombies
I dont feel strongly about this aspect one way or the other at this point in time but following with the build-your-own-apocalypse point I feel would be best created as optional.

### Dark Days of the Dead - Aim for Brains
> Look into applying some type of targeted shot system (there are plans for this for mainline) and require headshots to kill zombies
Not all zombie lore requires the brain be destroyed. 
One of the cool zombies already in the game which is brainless is the "Listener Zombie.
Equally terrify and cool, yet still fits into the family of classic zombies in my opinion.

### Dark Days of the Dead - Dead Gear
> Remove the [FILTHY] tag and just have most zombies wearing semi-useless rags and carrying nothing, with a few notable exceptions.
I enjoy finding all the various items and clothing on zombies. Each zombie has their own implied back story in a way depending on the stuff they have.
I can take down some zombies and infer that one zombie was a hipster, or a nerd, or a suburban housewife.
Though limited in depth, I enjoy this subtle environmental story telling.


# Remarks
I hope I have given productive feedback where you will be willing to have a back & forth discussion on various points, and kick around new ideas too.

**Comment by I-am-Erk** [comment]
I plan to keep all this as a single mod, but I do like the way you're breaking it up. It might be reasonable to subgroup mod folders around those lines, so that people can customize their experience with minimal json modification basically by removing a folder. We'll have to see.

Going at this from a more technical standpoint, I'm about to push a WIP for stage one: pull information from most existing blacklist mods to make a more robust blacklist system for DDotD. This is mostly redundant, but will help ensure nothing slips through.

The major blacklist expansions currently ar bl_scifi.json, which removes most science fiction or very fictional stuff from the game. Some of this should eventually be replaced with a migration, so when you would have found an atomic coffeepot for example, you instead find a regular coffeepot. Also bl_mutations and bl_bionics. There will be less room for the player to become a superhuman in DDotD, more in keeping with the grittier feel of classic zombie movies. On the other hand, the zombies are also not mutating into giant horrific beasts, so I'm hoping it will come out a bit even.

I am considering also whether to remove survivor armour, but I think I am biased there by my own personal dislike of it.

**Comment by I-am-Erk** [comment]
I do agree with your argument about zombie stories in their gear though. I would suggest we make sure that "zombie rags" aren't a singular item and that we have a few different types to mix and match.

I'm not completely sold on the "no zombie clothes" thing anyway. FILTHY is mostly working well. We'll have to see.

**Pull request merged**
