### PR TITLE
Disallow filthy components in repair of clean items

### LINKED ISSUE #28089: Repairing items with filthy materials causes error
**Describe the bug**  

When you repair CLEAN clothing and only have filthy stuff around, it will work and you will get an error.

**To Reproduce**  
1. Use a wooden needle or bone needle or something
2. Have filthy rags or something filthy nearby to repair your clothes with
3. Repair clothes.

**Expected behavior**  

Not sure, but not a bug error thing,

**Screenshots**  

https://i.imgur.com/awE7ffw.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-37270-g86ec372
 - Graphics version Tiles
 - Mods loaded quite a few but I don't think they matter to this...

**Additional context**  

Can't believe no one tried this yet... or no one who found it is reporting it...

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: Bugfixes "Disallow filthy components in repair of clean items"```

#### Purpose of change
Fixes #28089.

#### Describe the solution
only allow filthy components if item to fix is also filthy

#### Additional context
Requires #28114.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I think this is just wrong. What's the rationale for not being able to repair filthy clothing with clean components?

**Comment by Brambor** [comment]
I think it should not be "only allow filthy components" but "warn when you do not have filthy components and query for continuing".

**Comment by ifreund** [comment]
>I think this is just wrong. What's the rationale for not being able to repair filthy clothing with clean components?

Maybe I wasn't clear, you can still do this.  Only thing you can't do is use filthy components to repair clean clothing.

**Comment by moxian** [comment]
Can we allow using filthy components to repair clean clothing, as long as this would also make the repaired clothing filthy (and prompt the player if they are sure they want that)?  I've [commented](https://github.com/CleverRaven/Cataclysm-DDA/issues/28089#issuecomment-461316679) on the issue with a bit more words expressing the same idea.

FTR: I'm happy with "no, that's too complicated to implement" as an answer, just want to make sure this possibility has been considered.

**Comment by ifreund** [comment]
>Can we allow using filthy components to repair clean clothing, as long as this would also make the repaired clothing filthy (and prompt the player if they are sure they want that)?

That's definitely a little more involved that this simple bugfix.  I'm not opposed to the idea but don't really want to take the time to implement that right now, rather focus on the release blockers for 0.D.  

If @kevingranade thinks that should be a priority I I could probably throw something together.

**Comment by kevingranade** [comment]
Merged to 0.D and master.

**Pull request closed without merging**
