### PR TITLE
Allow pocket_mods to add magazine or magazine well pockets to items without them

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
Bugfixes "Allow pocket_mods to add magazine or magazine well pockets to items without them"

#### Purpose of change

#69725 throws a ton of errors because gunmods could only alter magazine wells, but not add them.

#### Describe the solution

- gunmods and toolmods will now also add magazine or magazine well pockets if they didn't have one before.
- adds a test to check pocket_mods functionality
- fixes a small oversight from #69794
- `pocket_data::operator==` also compares various restrictions

#### Testing

The new test passes.

### CODE REVIEW

**Comment by GuardianDll** [comment]
btw, what will happen if item has one pocket, but one try to add another one? is there a way to specify "this one should overwrite pocket, and that one add another pocket"?
tho it sound complicated as you need to specify which pocket exactly should be overwritten, if item has multiple

**Comment by mqrause** [comment]
Container pockets can only be added currently, magazine/magazine well pockets only overridden.
It'd be pretty messy to allow both adding and overriding the same pocket type, I imagine.

**Comment by GuardianDll** [comment]
That is better than i expected, thanks

**Comment by mqrause** [comment]
I guess I should have added documentation for this, too.

**Comment by GuardianDll** [comment]
I'll doing it already

**Pull request merged**
