### PR TITLE
Bagpipes Volume Change

### PR DESCRIPTION
**Pull request by WhaleYogurt**
#### Summary  
Balance "Increase bagpipe volume from 24 to 75"  

#### Purpose of change  
This change addresses the request to make bagpipes significantly louder. The current volume of 24 was too low to match the intended gameplay effect of the instrument. This adjustment increases the volume to **75**, making it more realistic and impactful as a tool for gathering the horde.  

This change relates to issue **#78608**: ["Bagpipes should be LOUD"](https://github.com/CleverRaven/Cataclysm-DDA/issues/78608).  

#### Describe the solution  
The volume for the bagpipes was increased in the JSON file from **24** to **75**. This increase better represents the auditory range of bagpipes.  

File modified:  
`data/json/items/tool/musical_instruments.json`  

#### Describe alternatives you've considered .  
- Intermediate values (50-75) were considered, with **75** chosen as a reasonable compromise for realism and gameplay impact.  

#### Testing  
- Verify the sound range increase in-game.  
- Confirmed that the change is isolated to the bagpipe's volume property.  
- No errors or unexpected behavior occurred during testing.  

#### Additional context  
- Bagpipes are traditionally loud instruments that can be heard across long distances, especially in quiet environments.  
- Apparently they can be about as loud as a chainsaw so 24 seemed way to low

### CODE REVIEW

**Comment by GuardianDll** [comment]
Hmm? Why closed? Seems reasonable for me

**Comment by WhaleYogurt** [comment]
Sorry that was a mistake I was trying to clean up my page and something went wrong

**Comment by GuardianDll** [comment]
it seems you removed your entire repo, need to make a fork again

**Comment by WhaleYogurt** [comment]
made a new fork. should have pushed it too

**Pull request closed without merging**
