### PR TITLE
Jsonify Limb Scores & Character Modifiers

### LINKED ISSUE #52846: Arm encumbrance effects are not shown in character menu
### Describe the bug

The character menu (in experimental) states that arm encumbrance should affect melee stamina cost and ranged weapon accuracy; 
however, the numbers shown remain at x1.00 melee and +0 ranged dispersion, even with >50 encumbrance.

### Steps To Reproduce

1. Start as a Survivor in the evac shelter.
2. Look at the values affected by arm encumbrance in the @ menu.
3. Put on two emergency jackets.
4. Look at the values again.

### Expected behavior

Melee stamina cost and ranged weapon dispersion should be shown to increase when encumbrance increases.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 050e934 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

### Additional context

I haven't tested if the values shown in the character menu are reflective of the actual values in combat.

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
Fixes #52846
Also inspired by Venera's awesome work on #53004.

I wanted to have the limb encumbrance descriptions be automatically associated to the appropriate body parts, but there are a couple of roadblocks that I want to address first:
- Encumbrance descriptions are tied to specific body parts, so moving around the limb scores causes a discrepancy between what is displayed and what the actual values are.
- Limb scores are added ad-hoc to the body part struct, so it's not scalable to iterate over them (or to add new ones).
- Most limb scores are calculated the same way, so there's a lot of duplication.

#### Describe the solution
The goal is to create a generic method for defining limb scores, which can be used to generate the encumbrance descriptions for associated body parts, completely defined in JSON.

I created a new JSON type `"limb_score"` with this format:
```json
{
  "type": "limb_score",
  "id": "lift",
  "name": "Lifting",
  "affected_by_wounds": true,
  "affected_by_encumb": false
}
```
`"name"` is a translatable string that identifies the score in the UI. `"affected_by_*"` indicates that this limb score is passed through `bodypart::wound_adjusted_limb_value()` and/or `bodypart::encumb_adjusted_limb_value()`.

<hr>

These limb score types are referenced in `"body_part"` using the `"limb_scores"` array:
```json
{
  "id": "arm_l",
  "type": "body_part",
  "name": "left arm",
  ...
  "limb_scores": [
    [ "manip", 0.1, 0.2 ],
    [ "lift", 0.5 ],
    [ "block", 1.0 ],
    [ "swim", 0.1 ]
  ]
}
```
The array has 2 mandatory fields and one optional field:
1. The id of the limb score
2. The limb score value
3. The max value (mostly just for manipulation score)

<hr>

Since character modifiers are generally tied to limb scores, I decided to jsonify them too:
```json
{
  "type": "character_mod",
  "id": "melee_stamina_cost_mod",
  "description": "Melee stamina cost",
  "mod_type": "x",
  "value": { "limb_score": "lift", "limb_type": "arm", "max": "max_move_cost", "nominator": 1.0 }
},
{
  "type": "character_mod",
  "id": "stamina_move_cost_mod",
  "description": "Stamina move cost modifier",
  "mod_type": "x",
  "value": { "builtin": "stamina_move_cost_modifier" }
}
```
`"value"` is the magic JSON object that defines how the character modifier is calculated. The fields in "value" are as follows:
- **limb_score**: Mandatory. Defines the limb score that derives this modifier.
- **limb_type**: Optional. If present, only sum up the limb scores from this limb type.
- **override_encumb**: Optional. If present, overrides the limb score's `affected_by_encumb` to force the score to be affected/unaffected by limb encumbrance.
- **override_wounds**: Optional. If present, overrides the limb score's `affected_by_wounds` to force the score to be affected/unaffected by limb health.
- **max**: Optional. Can be any float or the special value "max_move_cost". Defines the upper limit of a cost modifier.
- **min**: Optional. Can be any float. Defines the lower bound of the limb score. (ex: melee attack roll modifier has a minimum of 0.2)
- **nominator**: Optional. If present, divide the value by the limb score (essentially `nominator / limb_score`).
- **subtract**: Optional. If present, subtract the resulting modifier by this value (essentially `(nominator / limb_score) - subtract`).

Alternatively, the "value" can be specified as a `"builtin"` which refers to a hardcoded function in character_modifier.cpp.

<hr>

Limb scores can be iterated using `limb_score::get_all()`, which I'm using to generate the encumbrance descriptions:

https://user-images.githubusercontent.com/12537966/143731014-6b1edbba-535f-4a76-a4c1-3e41f1336e33.mp4

#### Describe alternatives you've considered
It would be easy to move the encumbrance descriptions around to reflect the current effects, but that doesn't solve the underlying problem. It also wouldn't scale once new body parts start being added.

#### Testing
Ensure that these are working properly:
- `copy-from`, `extend` and `delete` on all affected types
- Validation catches invalid entries
- Scrolling in the information box doesn't omit any rows
- Limb scores and modifiers are unchanged between before and after this fix
- Unit tests

#### Additional context
TODO:
- [x] Move limb scores to JSON type
- [x] Create generic methods for calculating limb scores
- [x] Create generic methods for generating limb encumbrance text
- [x] Scroll information box to accommodate longer descriptions
- [x] Jsonify modifiers as well
- [x] Documentation
- [x] Testing

### CODE REVIEW

**Comment by Venera3** [comment]
Oh, that's fancy! It should streamline me klutzing together new scores at the drop of a hat nicely. Two things: 

Do you think there's a way to overwrite the `affected_by` under the hood for certain calculations? E.g. while `lifting_score` shouldn't be scaled by armor when calculating it for damage or y'know *lifting*, armor impacting its effect on swing stamina cost makes sense (the first two aren't hooked up yet, but they'll probably be when I do arms).

How well do they play with `copy-from` on bodyparts? It's not a giant problem, but it's always nice when lists support `extend` and `delete`.

**Comment by dseguin** [comment]
> Do you think there's a way to overwrite the `affected_by` under the hood for certain calculations? E.g. while `lifting_score` shouldn't be scaled by armor when calculating it for damage or y'know _lifting_, armor impacting its effect on swing stamina cost makes sense (the first two aren't hooked up yet, but they'll probably be when I do arms).

Sure, it shouldn't be hard to add a new field to give it a little more control. I'll try to keep it open so that I (or anyone else) can easily expand it later on.

> How well do they play with `copy-from` on bodyparts? It's not a giant problem, but it's always nice when lists support `extend` and `delete`.

I don't think I've ever had a problem with `copy-from`, but I'll definitely add it to my tests.

**Comment by Venera3** [comment]
One other thing that could either be moved to a limb score (or limb field in general) would be the function of `avatar::limb_dodge_encumbrance` - something like `enc_dodge_modifier` defined in the BP definition. Alternatively, just showing it in the list of limb modifiers would be nice already, though it takes hardcoded limb IDs so it won't play nice with custom limbs down the line.

**Comment by dseguin** [comment]
@Venera3 Cheers! After one hell of a rebase, your changes should be properly jsonified. I've added new fields to `character_mod` to override how the limb score is affected by encumbrance and/or wounds (currently using it for "melee_stamina_cost_mod").

> One other thing that could either be moved to a limb score (or limb field in general) would be the function of `avatar::limb_dodge_encumbrance` - something like `enc_dodge_modifier` defined in the BP definition. Alternatively, just showing it in the list of limb modifiers would be nice already, though it takes hardcoded limb IDs so it won't play nice with custom limbs down the line.

I refactored `avatar::limb_dodge_encumbrance` to take an arbitrary number of body part types. I created a new field for `body_part` called "encumb_impacts_dodge" that will include it in the calculation. I also included the modifier in the player's display for any limb where "encumb_impacts_dodge" is true.

I've updated the documentation, so you can check JSON_INFO.md in this PR to see a summary of all the changes.

**Comment by alp7292** [comment]
maybe insignificant but hand  encumbrance also affects when you try to put pressure on your bleeding wound meybe it can be jsonified

**Pull request merged**
