### PR TITLE
Fictional Weapons mod

### PR DESCRIPTION
**Pull request by DeadLeaves**
This mod adds 4 new guns to the game, inspired by fiction.
*A 454 revolver with integrated 40mm grenade launcher.
*A Gunsword chambering the powerful .500 S&W
*A Gunknife chambering the powerful .500 S&W
*A Single shot pistol firing .50 BMG rounds.
More to come as the mod is further extended.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Hmm. May I suggest a couple combined movie/videogame references?

1. That Gun, a revolver in .223. Referencing Blade Runner and the Fallout series.
2. An MP3 with integrated 40mm grenade launcher. Referencing an Arnold Schwarzenegger movie I forgot the title of, and Half-Life.

**Comment by DeadLeaves** [comment]
Thanks for the ideas. I have some questions about them though. 
1 - Don't we have the L2037 Backup already. Kinda fits the theme I think.
2 - I assume you mean MP5 as MP3 is a music format afaik. But I like the idea, and will implement it.

**Comment by chaosvolt** [comment]
Doh. Yes, MP5. Such fail.

And hmm, so we already have a .223 revolver? Ah right.

**Comment by chaosvolt** [comment]
;A;

**Comment by kevingranade** [comment]
For context here, I merged everything except the last commit, so this
wasn't discarded but instead partially merged.

**Comment by chaosvolt** [comment]
Ah, I see now. I'd noticed later when updating my master branch that it was suddenly in. Cue confusion. o3o

**Comment by Griffinhart** [comment]
Hmm. If the gunsword is a reference to the FFVIII gunblade, it might be worth knowing that the gunblade in *Parasite Eve II* (also a Squaresoft game, and actually running on a modified FFVIII engine, if memory serves) chambered 12 ga. shotgun shells.

**Pull request closed without merging**
