### PR TITLE
De-couple plant traits from ELF-A

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Balance "De-couple plant traits from ELF-A"

#### Purpose of change
Plant traits (ugly) are antithetic to "drop dead gorgeous elf-people".

#### Describe the solution
Remove ELF-A category where it is primarily plant traits.

#### Describe alternatives you've considered
Create a new mutation line focusing specifically on becoming a "natural" socialite.

#### Testing
None, straightforward change.

#### Additional Context
I'm not even sure what the proper summary tag for this is, so I just placed it under balance.

### CODE REVIEW

**Comment by kevingranade** [comment]
Check the tests, this failure is related to your change
```Having all pre-threshold mutations gives a sensible threshold breach chance

      Given: The player has all pre-threshold mutations for PLANT

       Then: Threshold breach chance is at most 0.4

-------------------------------------------------------------------------------

mutation_test.cpp:120

...............................................................................

mutation_test.cpp:122: FAILED:

  CHECK( breach_chance <= BREACH_CHANCE_MAX )

with expansion:

  0.42857f <= 0.4f

with message:

  MUTATIONS: COLDBLOOD2 THORNS DEFORMED2 HAIRROOTS BARK VINES2

  SUNLIGHT_DEPENDENT FASTHEALER2 BADHEARING HEAVYSLEEPER LEAVES DISIMMUNE

  STR_UP_2 PONDEROUS3 ```
The test is attempting to insure that each mutation branch is sufficiently distinct from other branches.

**Comment by Termineitor244** [comment]
Some of those traits were created with ELF-A in mind (#29767)...
But well, I suppose we should make a differentiation between beautiful elves and plant people.

That said, the elves in fiction do have a strong relation with plants and trees (nature), could you leave the Mycorrhizal Communion trait for the elves too? It makes sense and is not something visually striking (But, well, we still have the HAIRROOTS requisites...).

This changes and #37105 (if it´s merged) would make the ELF-A mutation something more unique, so... Keep going!

**Comment by Rivet-the-Zombie** [comment]
Aren't elves typically depicted as treehugger/druid types? The _Mycorrhizal Communion_ power seems like it'd fit that quite well.

**Comment by CodeBandit** [comment]
Since Fey is deeply rooted (pun intended) into plant mutations, I'll just look to implementing the alternative and focus on making a mutation line focusing mostly on social aspects since that's not a thing yet

**Pull request closed without merging**
