### PR TITLE
Make single corpses spawn much less often

### PR DESCRIPTION
**Pull request by sick-trigger**
#### Summary
```SUMMARY: Balance "Single corpses in the wilderness will spawn less often"```
#### Purpose of change
They're way too common! Stumbling into a dead guy in the forest isn't very spooky when you've been walking past others exactly like it all day. "Less is more."

#### Describe the solution
make number smaller

#### Describe alternatives you've considered
make number less small

### CODE REVIEW

**Comment by tinukedaya** [comment]
It's not supposed to be spooky, it's about to show that there was an apocalypse that killed most people. 
Most of them raised as zombies, but some were lucky and just died.

**Comment by shadowsapex** [comment]
They ought to at least be concentrated around population centers and roads not spread evenly throughout the world

**Comment by tinukedaya** [comment]
That is true, but just reducing the spawn rate is not making that better.

**Comment by shadowsapex** [comment]
It would. The current spawn rate isn't doing good things for my suspension of disbelief. If it were reduced across the board, that'd still help a lot.

**Comment by Night-Pryanik** [comment]
> They ought to at least be concentrated around population centers and roads not spread evenly throughout the world

Death can catch you up literally everywhere after the Cataclysm, you know.

**Comment by shadowsapex** [comment]
Dude. There are more people near population centers. People are not spread evenly throughout riverbanks, forests, meadows, and cities.

**Comment by Night-Pryanik** [comment]
People leave the population centers after they realized how dangerously these centers are.

**Comment by shadowsapex** [comment]
Are we going to go through this one step at a time? Population centers have the highest concentration of people. Population centers had the highest concentration of danger during the cataclysm. People plus danger means corpses. Or are you saying that the comparatively few people out in the wilderness, or who managed to make it out to the wilderness, dropped more corpses to make up for it? I don't even get why we're arguing about this meaningless feature. Just say it doesn't have to be changed because it's meaningless. That's what I'd say.

**Comment by Night-Pryanik** [comment]
It doesn't have any other "meaning" except for adding atmosphere.

**Comment by sick-trigger** [comment]
and they'll have more of an impact when there's not so many of them. an unexpected lone corpse might make you stop and wonder "what happened to them?" "is what killed them still around?", but right now they're just clutter. all these people hanging around in fields, on their own, away from their cars, miles from anything? makes no sense

**Comment by dissociativity** [comment]
Groups of corpses should definitely be more common than individual corpses, humans are a social species that will band together and cooperate during crisis such as these.

**Comment by ZhilkinSerg** [comment]
> all these people hanging around in fields, on their own, away from their cars, miles from anything? makes no sense

There is a lot of sense. Gas is out, cities are filled with monsters. People are desperately trying to flee on their foot, but they are unprepared, so they die due to dehydration, wolves, random migos, and whatnot.

**Pull request merged**
