### PR TITLE
Add reinforced/upgraded solar panels as appliances

### PR DESCRIPTION
**Pull request by ccaviness**
#### Summary
Content "Add reinforced/upgraded solar panels as appliances"

#### Purpose of change
Only regular solar panels are available as appliances. The other variations should be added as well.

#### Describe the solution
Add appliance and construction entries for reinforced solar panels, upgraded solar panels, and reinforced upgraded solar panels. Made installation of all solar panel appliances also require bolt turning 1.

#### Describe alternatives you've considered
* Not adding these at all
* Adding more skill requirements: higher fab? `electronics` as well?
* Requiring pipes or other materials to install the panels on in order to make an appliance

#### Testing
In a test world, built the 3 additional variations and verified they produce power as expected.

#### Additional context

The three new variants installed along with the base model:
panels_installed
Upgraded solar panel output:
upgraded_output

### CODE REVIEW

**Comment by Fris0uman** [comment]
Why fab 2? You're just putting it down, mayb bolting it, alhough I don't think we require any bolt turning quality, but it's basically the same process to install a regular panel or an advanced one.

**Comment by ccaviness** [comment]
Looking at installing solar panels in a vehicle, regular solar panel takes mech 4, and upgraded takes mech 6. So I was just copying that skill increase. I definitely have no strong feelings about this, though, and am happy to make it fab 1.

**Comment by ccaviness** [comment]
Going the other way - I guess if it's just plugging things in, why is there any fab required at all? Perhaps this is a larger discussion. I'm glad to take guidance either way.

**Comment by Fris0uman** [comment]
I think all appliance solar panels could require fab 1 and bolt turning, you're basically just bolting them down to stay in place. The vehicle stuff is a bit different as I think putting solar panels on a car is not intended for solar panels so you have to make more adjustement to have it work.

**Comment by ccaviness** [comment]
Ok, changed to fab 1, and added bolt turning (`WRENCH`) 1 for all solar panel appliance installations.

**Pull request merged**
