### PR TITLE
Move the mass of zombie spiders to No Hope

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
The mass of zombie spiders has been on my radar since forever because:
1. It violates the rule of minimum zombification size
2. It doesn't work as a representation of a swarm of anything even remotely well. A swarm should be immune to nearly all damage types except maybe bash to some degree, and this isn't representable very well with armor values. I am of the opinion we need better handling for swarm-type monsters if we want to do those in the future

#### Describe the solution
Remove it

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Could you please move it to No Hope instead?

**Comment by Karol1223** [comment]
> Could you please move it to No Hope instead?

I can, but not sure if today. I'll draft this and look at it sometime soon.

**Comment by RedMisao** [comment]
Isn't the mass of zombie spiders similar in concept to the fused mosquito monster? Not as in a swarm, but as several, previously independent individuals now permantently blob'd together.

**Comment by Karol1223** [comment]
> Isn't the mass of zombie spiders similar in concept to the fused mosquito monster? Not as in a swarm, but as several, previously independent individuals now permantently blob'd together.

We don't have any fused mosquitoes, but I presume you're talking about fused dragonflies - no, not at all, because one is a mutant and the other is a zombie. The discussion about this monster not fitting the current setting isn't anything novel, but for the last 2 years me and Venera have been going back and forth about reworking them into being caused by a nether artifact, but neither of us really wanted to do it so I'm pulling the plug. If Venera changes his mind in the future he can reincarnate it, especially since the monster will now be preserved in No Hope.

**Comment by Karol1223** [comment]
Vehicle tests being extra flaky today...

**Pull request merged**
