### PR TITLE
Begin integrating new weakpoints info

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
Content "Now you can stab a zombie in the eye and it will go blind"

#### Purpose of change
With #51770, #51961, and #51979, @Joshua-Chin has been implementing a robust framework for detailed monster weakpoints and effects from hitting them, and I am way behind on actually using them in monsters!

#### Describe the solution
This will expand all this new weakpoint information to any zombies that already have weakpoints. I am not looking at non-humanoid monsters currently, because at least with zombies I can carry the same weakpoints forward to all the monsters.

- Hitting the legs has a chance of knockodwn
- HItting the arms has a chance to stagger your opponent
- HItting the head has a chance of stun
- Hitting the eyes has a chance of blinding, and if you do enough damage it can be permanent

In general, most weakpoints are harder to hit at range than in melee. If they are off the front-facing part of the zombie (eg an armpit) they are much harder. Small weakpoints are harder to hit with cut/bash weapons, and easier with stab/ranged attacks. Large ones like legs are easier to hit with wide sweeping cut/blunt attacks. Weakpoints on the extremities have decreased critical hit damage.

This covers all zombies that previously had weakpoints, plus feral humans, acid zombies, and fungals. It does not cover any animal zombies yet.

#### Describe alternatives you've considered
Posting this so people can review the numbers I've selected and offer feedback.

#### Testing
Still needs testing.

#### Additional context
This is so awesome.

We may wish to increase the base armour on some of these zombies, but I would suggest first to do some playtesting to see how much trickier I have made their weakpoints. The effective DPS tests have, for the time being, been set to ignore weakpoints altogether. We should develop new tests for weakpoints, and also buff armour as the weakpoints tests now find effective dps way higher against many zombies.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Also, @Joshua-Chin - it absolutely isn't necessary, but a ton of this is going to be repeated code. It might be nice to be able to create an independent `weakpoints` JSON object and just specify `"weakpoints": "armoured_soldier"` instead of copying it through.

I will have already done weakpoints for all of these before you can possibly get to that, so don't consider it a priority or anything.

**Comment by Joshua-Chin** [comment]
With #51822, weak points should now support `extend` / `remove` based inheritance. That feature would cut down on the duplication. Have you run into any issues using it?

**Comment by I-am-Erk** [comment]
No, that will work for monsters that copy-from each other. Just thinking of the work as a whole, where they don't copy. like I said though, it's not very important, it would just reduce line counts.

**Comment by PatrikLundell** [comment]
I don't have any issue with humans/animals going blind from being hit in the eye, but zombies that regenerate from death surely should be able to regenerate eyes? The blob apparently doesn't bother with brains, and there are listener zombies, but still.

**Comment by kevingranade** [comment]
Regarding long-term effects like blinding, we really aren't as concerned about the consistency of effects impacting zombies as we are the same thing for the player. Things impacting the player are very long lasting and continue to have an impact for potentially the rest of your game, effects on monsters are forgettable once you simply walk away.

There's a very simple version of this would be to simply refrain from carrying these effects forward if a zombie is downed and then raises unless it specifically changes the monster type.

**Comment by Joshua-Chin** [comment]
Would it helpful for  `crit_mult`, `damage_required`, and other similar fields to support shorthand, or is the current interface sufficient?

**Comment by I-am-Erk** [comment]
> Would it helpful for `crit_mult`, `damage_required`, and other similar fields to support shorthand, or is the current interface sufficient?

I don't think it's a big deal, I just had to play around with the format a bit. Now that there are examples for people to follow it shouldn't come up much.

**Comment by Venera3** [comment]
Going forward we really need to make effect information dynamic in the monster examination panel (at the moment all effects that are shown the player are hardcoded). 
Also, when we have weakpoints implemented for a reasonable fraction of our monsters I'd advocate for removing skill-based damage scaling and extra effects from melee altogether - near as I can tell it's supposed to be a stand-in for "hitting the right spot" more or less. In more drastic measures, I'd also do away with critical hits as they stand, since we can now model them properly.

**Comment by I-am-Erk** [comment]
I don't think we should eliminate critical hits, as there is still a difference between "hit the head" and "critically hit the head" for example. Weak points let us rationally divide the impact of criticals, so critically hitting the arm is far different from critically hitting the face.

I agree that once weak points are widespread we should be able to replace damage scaling with being able to hit weak points more easily

**Comment by Joshua-Chin** [comment]
Sorry for the amount of duplication! I completely overestimated the use of `copy-from` inheritance. I assumed that most monsters would inherit from a parent, when in reality barely any do. Would moving weakpoints into their own object still be helpful, or does your current plan obviate the need?

**Comment by I-am-Erk** [comment]
closing for now, will reopen in a new form very soon indeed.

**Pull request closed without merging**
