### PR TITLE
Fixes 66637 and wraps up some typos.

### PR DESCRIPTION
**Pull request by DoctorBoomstick**
#### Summary
Bugfixes "fix reported bugs in 66637, related to the new smartphone case variants and a changed id, and takes the time to ice the typos recorded in #66620"
#### Purpose of change
- Bugs exist.
- Me no like bugs.
- Me sick of these mother fucking bugs in this mother fucking game.
- Me smash smash bugs with hammer of GitHub.

#### Describe the solution
For #66637, I’ve created an obsoletion version of the smartphone case to serve as a fallback migration to keep the game from exploding for saves with the old ID variant.
For #66620, I used my keyboard and pressed buttons to fix the typos and errors. A hard day’s work.
#### Describe alternatives you've considered
Being a jackwagon and not doing the smashy smash to my own bugs with the GitHub hammer and submitting a sarcastically tiny PR to inject a handful of code lines to fix a single issue
#### Testing
Loaded up the changes into a run and  observed that the game didn’t implode.
#### Additional context
Consult #66637 and #66620 for the original issues.

### CODE REVIEW

**Comment by Standing-Storm** [comment]
Are the MoM readme changes the same as those merged in https://github.com/CleverRaven/Cataclysm-DDA/pull/66627 ?

**Comment by DoctorBoomstick** [comment]
> Are the MoM readme changes the same as those merged in #66627 ?

I want to say that what ever was going on with the MoM mod’s readme file has been resolved on it’s own. Idk why it was showing up in my list of edited files considering that I didn’t touch it, but it looks ok now, I think.

**Comment by Standing-Storm** [comment]
> what ever was going on with the MoM mod’s readme file

I wrote basically the entire mod in Github's web interface

(I have a real IDE now!)

**Comment by DoctorBoomstick** [comment]
Got you. I honestly can’t tell what/ if anything was wrong, all I can tell is that it’s not in the list of modified files anymore, so I will take that to mean that my PR isn’t making another oopsy. Cool mod, btw.

**Pull request merged**
