### PR TITLE
Add tools to furniture

### PR DESCRIPTION
**Pull request by krulunio**
#### Summary
Content "Add tools to furniture"

#### Purpose of change
I have noticed that some useful IRL furniture is good only for spare parts, I want to change that.

#### Describe the solution
Add "crafting_pseudo_item" to various furniture, create new fake items if necessary.

#### Testing
I tried various "crafting_pseudo_item" items, the only issue I found is that items reloaded with magazines/batteries, i.e. hotplate, can't be reloaded by examining furniture.
EDIT: "crafting_pseudo_item" items can use UPS to power themselves.

### CODE REVIEW

**Comment by Shodan14** [comment]
How's this going to work with no power though?

**Comment by Zireael07** [comment]
It literally says in the PR - "can use UPS to power themselves"

**Comment by natsirt721** [comment]
What's the lore w.r.t. the UPS? I would expect that these machines would take 120/240 volt AC input and wouldn't be able to operate from a portable UPS that (to me anyway seem like it would) provide a lower voltage DC output.

**Comment by krulunio** [comment]
> What's the lore w.r.t. the UPS? I would expect that these machines would take 120/240 volt AC input and wouldn't be able to operate from a portable UPS that (to me anyway seem like it would) provide a lower voltage DC output.

Yes, those machines use AC input and UPS provides DC power, but UPS is the best solution I could come up with.

**Comment by Zireael07** [comment]
Why close?

**Comment by krulunio** [comment]
> Why close?

I currently don't have time or ideas what to do

**Pull request closed without merging**
