### PR TITLE
Add charcoal smoker to recipes

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Add charcoal smoker as possible heat source to all recipes.
2. Tweak amount of charcoal used in some recipes.
3. Add atomic coffeemaker to bark tea recipe.
4. Add forked spear and survivor naginata to s'mores recipe.
5. Change saline solution recipe to use salt water.
6. Tweak whiskey wort recipe to use 4 integrated toolset charges.

### CODE REVIEW

**Comment by Snaaty** [comment]
Is it really such a good idea to add the chracoal smoker as a heat source to many things?
Firstly, I am not sure what is even meant precisely when speaking of a charcoal smoker, but at first I thought of it solely as a tool for preparing meats that are being smoked. 
Also there is the problem of charges; the ratio to the battery-powered hotplate varies even in the recipes you added between 1:2 and 1:10, as far as I can see. This is probably because one unit of battery is much smaller than one unit of charcoal. However, making a chracoal smoker is not an early-game thing to achieve or easily found to justify the much worse ratio gameplay-wise, and will therefore serve no real purpose except to confuse people.

**Comment by Zireael07** [comment]
Uh, I thought the smoker was only supposed to smoke things, not warm/heat them up.

That said, we could have a charcoal heater (name subject to discussion) which would do what is suggested here.

**Comment by Darkyhard** [comment]
Well, I thought that charcoal smoker is basically a metal container with charcoal that can be ignited, and therefore it could be used in the same way as you could use a fire.

**Comment by i2amroy** [comment]
That's more like a charcoal grill. Charcoal smokers tend to look more like [this](http://www.homedepot.com/catalog/productImages/1000/eb/ebdddcf2-59e5-4de6-8e63-223b6d77ff96_1000.jpg) (cutaway view obviously), i.e. a fairly sealed metal container with a tiny smoldering fire in the bottom.

**Comment by kevingranade** [comment]
Agreed, smokers simply are not going to work as generic heat sources, it's way too low.

**Comment by Darkyhard** [comment]
Okay, I'll close this and add separate charcoal heater, similar to gasoline cooker and oil cooker.

**Pull request closed without merging**
