### PR TITLE
Fix monster interaction with boats

### PR DESCRIPTION
**Pull request by Aivean**
#### Summary

SUMMARY: Bugfixes "Fix monster interaction with boats"

#### Purpose of change

When using boats, I noticed several monster-related issues:
* jawed terror was able to walk (?) on the boat tiles and attack my character
* zombies could swim under the boat and then suddenly surface in the middle of it (through the floor)

#### Describe the solution

* `AQUATIC` monsters now avoid swimming on/under vehicles and cannot attack from under water through vehicle tiles
* land monsters now are forced to surface when moving onto vehicle

##### Technical details:

Moved `is_adjacent` to be the method of the `Creature`, added additional clause:  when one creature is under water while other isn't and they both are on/under vehicle tiles, they don't count as adjacent.

In `monster::will_move_to` forbid `AQUATIC` monsters from moving under vehicles, unless they are already under vehicle (e.g. player was able to run them over, if that's even possible).

In `monster::move_to` added clause that forces non-`AQUATIC` monsters to step out of water if they step on vehicle tiles.

In `monster::melee_attack` added `is_adjacent` check (in case `AQUATIC` monster somehow ends up under vehicle).

#### Describe alternatives you've considered

Not really an alternative, but a quirk of current implementation:

if `AQUATIC` monster somehow ends up under vehicle, player is still able to attack it without response. I'm not sure what could be done about it, as an alternative would be to allow player to step onto the monster (which I'm not sure is allowed) or restrict player's movement which also makes little sense.

#### Testing

Playtested following scenarios:
* Jaw terror:
   * cannot swim under the boat
   * can attack and be attacked from the edge of the boat
   * I tried my best to run it over with the boat, but was not successful (same with out fish)
* Zombie:
  * correctly emerges from the water at the edge of the boat (becomes visible)

##### Before:
zombie (note how fast it is and how it could disappear in the middle of the boat, that's because it's counted as swimming/underwater):
zombie_before

Jawed terror:
shark_before

----

##### After:

zombie
shark

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> In monster::will_move_to forbid AQUATIC monsters from moving under vehicles, unless they are already under vehicle 

Does that mean that aquatic monsters won't be able to dive under vehicle from non-vehicle tiles anymore?

**Comment by Aivean** [comment]
> > In monster::will_move_to forbid AQUATIC monsters from moving under vehicles, unless they are already under vehicle
> 
> Does that mean that aquatic monsters won't be able to dive under vehicle from non-vehicle tiles anymore?

yes

**Comment by actual-nh** [comment]
> > Does that mean that aquatic monsters won't be able to dive under vehicle from non-vehicle tiles anymore?
> 
> yes

Perhaps underwater Z-levels (created for the sealab, IIRC) could be used to help with all this?

**Comment by Aivean** [comment]
> Perhaps underwater Z-levels (created for the sealab, IIRC) could be used to help with all this?

That's a good idea, I was also thinking about that. Shallow water should be similar to a `t_floor` and deep water to `t_wall` in terms of the occupied 3d space. Rivers would have deep water on the z-level below ground and aquatic creatures could use it to swim below surface.

Currently there several other remnants of the single z-level in the game: for example, some roofs are defined as a flag of the terrain, instead of being a terrain on a z-level above. I think this would be changed eventually, but definitely not that that close to the stable release.

**Comment by Aivean** [comment]
> > > In monster::will_move_to forbid AQUATIC monsters from moving under vehicles, unless they are already under vehicle
> > 
> > 
> > Does that mean that aquatic monsters won't be able to dive under vehicle from non-vehicle tiles anymore?
> 
> yes

Just to clarify, the change applies to the water+vehicle tiles on the same z-level. So, if there is deep water on the z-level below the vehicle, AQUATIC monsters are free to use it. But I doubt that current monster pathfinding allows them to navigate in 3d space properly.

**Pull request merged**
