### PR TITLE
Simplify class_definitions.lua: optional arguments

### PR DESCRIPTION
**Pull request by lispcoc**
#### Summary

SUMMARY: Features "Simplify class_definitions.lua: optional arguments"

#### Purpose of change

LUA bindings is written in class_definitions.lua. function that has optional arguments are now written like the following.
```LUA
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration" } },  
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration", "body_part" } },  
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration", "body_part", "bool" } },	  
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration", "body_part", "bool", "int" } },	  
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration", "body_part", "bool", "int", "bool" } },
```
I think it is not so good.

#### Describe the solution

Add "optional_args" attribute. previous example is replaced 
```LUA
{ name = "add_effect", rval = nil, args = { "efftype_id", "time_duration" }, optional_args = { "body_part", "bool", "int", "bool" } },
```

#### Describe alternatives you've considered

I'm still a beginner at English. please tell me something strange.

#### Additional context

I want to expose functions and classes to lua more. this change helps the work.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Both syntax are supported now, right?

**Comment by lispcoc** [comment]
> Both syntax are supported now, right?

Yes, old style syntax is still available for compatibility.

**Comment by ZhilkinSerg** [comment]
Summary should look like this:

```SUMMARY: Features "Simplify class_definitions.lua: optional arguments"```

**Comment by lispcoc** [comment]
oh, I missed that rule sorry.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by lispcoc** [comment]
Thank you!

**Pull request merged**
