### PR TITLE
Medieval swordsmanship rewrite

### PR DESCRIPTION
**Pull request by QuintusAquila**
#### Summary
Content "Rewrite Medieval Swordsmanship"

#### Purpose of change
Currently the techniques used by Medieval Swordsmanship don't correlate to anything in German or Italian Swordsmanship. In particular, the code described the sweeping attack as an undercut, which isn't a cut that targets the legs, and cuts to the leg are somewhat niche and not leg sweeps. Vicious Strike is described as a wrath cut, which isn't wrong, but it's also not a particularly forceful cut.

It also suffers from balance issues. Counterattacks rarely trigger and the blunt damage techniques are worse than regular attacks, in particular mordhau has a move cost penalty.

The Pr had strange time out issues so I was asked to try making a new pr to fix it.

#### Describe the solution
The majority of the old techniques were removed. Mordhau didn't work terribly well within the system even if it was one of the techniques that actually exists. Deflection and manslayer were removed. Deflection could somewhat correspond to something but I want to change how the setup works. The grab break was removed because most grappling techniques in Hema are focused around killing the opponent not breaking their grab. While you spend time getting away they spend time stabbing you. Pommel Strike was removed, because the technique hurt the style when it wasn't free and the concept of punishing an attack out of measure could be used as a dodge counter, I'd prefer to focus the style on blocking since dodging isn't a focus in german, or italian swordsmanship.

A feint was added in the form of Flow Drills. Flow drills are a series of consecutive cuts to help practice flowing from one strike to another so they're decently represented by the feint mechanic. The Sweep was reflavored into a grapple, representing ringen. This sort of grappling frequently uses the sword as a lever, so it retains full damage. Mastercut was added as a block counter with a move cost reduction to represent the block being part of the strikes move. Conserve Momentum is meant to represent the general concept of conserving the momentum of the sword as well as quick follow up cuts to take advantage of breaking the opponent's structure. Part of this is using momentum gained in a parry, but to keep from overlapping with master cut its limited to attacks. To avoid overlap with flow drills its restricted to successful attacks. To make it useable with the slower zweihander its given a two turn duration.

| Name | Level Available | Type |Effect |
| ------------- | ------------- |------------- |------------- |
|Swordsman's Stance|Melee 0|Static Buff|+1 Block, Blocked Damage reduced by 50% Strength|
|Flow Drills|Melee 1|Melee Tech|Feint|
|Conserve Momentum|Melee 2|On Hit Buff|80% Move cost, Duration:2|
|Half Swording|Melee 3 |On Pause Buff|-1 Accuracy, Blocked damage reduced by +50% of Strength, Duration: 2|
|Lethal Strike|Melee 3 |Melee Tech|Requires Halfswording, 150% Str Armor Pen, 0% bash, can crit|
|Grab|Melee 4 |Melee Crit Tech|Requires Halfswording, Down Duration: 2, 50% cut, 33% pierce damage|
|Mastercut |Melee 5 |Melee Tech|Block Counter, 70% move cost|

Strengths
Lethal Strike will help overcome high armor enemies.
It should still perform somewhat well against groups, even lacking grab break, because of the stronger block and move cost buff
Uses Swords

Weaknesses
Still requires some setup. Lethal Strike is stuck with an accuracy penalty.
The lack of a grab break and slowish weapons makes it weak against larger groups.
Uses Swords

I also added the cavalry sabre and cutlass to the style. Dusacks and messers are part of germans swordsmanship so I see no reason that sabres and cutlasses should be excluded.

#### Describe alternatives you've considered

Leaving it as a reflavor or splitting it into two separate German and Italian martial arts.
Adding an excludes buff requirement so prevent using mastercut and feint in halfswording, but it already has -1 accuracy which is bad enough and dealing with compiling/c++ is currently beyond me.

#### Testing
I started up the Game with a test character with the martial art and a sword and hit things till the techniques fired. I also checked in the martial arts menu the the new names were right and the that the buffs had the correct description.

I did some play testing to make sure everything is reasonable.

### CODE REVIEW

**Comment by QuintusAquila** [comment]
@Maleclypse New Pr is made

**Comment by eltank** [comment]
The problem could be the large number of commits in this PR. If you continue getting failures you may try squashing them into 1 commit. The easiest way would be to create a new branch from master, then copy-paste all the files you changed (there are only 3) over the ones in that branch, then commit and push.

**Comment by QuintusAquila** [comment]
> The problem could be the large number of commits in this PR. If you continue getting failures you may try squashing them into 1 commit. The easiest way would be to create a new branch from master, then copy-paste all the files you changed (there are only 3) over the ones in that branch, then commit and push.

That might be worth doing, but this problem started well before there were so many commits.

**Comment by eltank** [comment]
I tried downloading your PR to patch it locally, using https://patch-diff.githubusercontent.com/raw/CleverRaven/Cataclysm-DDA/pull/51461.patch

It failed to apply with `git apply`:
```
51461.patch.txt:708: trailing whitespace.

51461.patch.txt:872: trailing whitespace.
        ]
51461.patch.txt:955: trailing whitespace.
        ],
51461.patch.txt:2218: trailing whitespace.

51461.patch.txt:2382: trailing whitespace.
        ]
error: patch failed: data/json/techniques.json:1033
error: data/json/techniques.json: patch does not apply
error: patch failed: data/json/martialarts.json:770
...
```

**Comment by QuintusAquila** [comment]
> I tried downloading your PR to patch it locally, using https://patch-diff.githubusercontent.com/raw/CleverRaven/Cataclysm-DDA/pull/51461.patch
> 
> It failed to apply with `git apply`:
> 
> ```
> 51461.patch.txt:708: trailing whitespace.
> 
> 51461.patch.txt:872: trailing whitespace.
>         ]
> 51461.patch.txt:955: trailing whitespace.
>         ],
> 51461.patch.txt:2218: trailing whitespace.
> 
> 51461.patch.txt:2382: trailing whitespace.
>         ]
> error: patch failed: data/json/techniques.json:1033
> error: data/json/techniques.json: patch does not apply
> error: patch failed: data/json/martialarts.json:770
> ...
> ```

I don't really know what it means. Does that indicate that the number of commits might be the issue?

**Comment by eltank** [comment]
It means that I'm not able to independently test your PR. But that may also be because your master is 24 days old and I'm trying to apply the patch on a recent master.

**Comment by QuintusAquila** [comment]
> It means that I'm not able to independently test your PR. But that may also be because your master is 24 days old and I'm trying to apply the patch on a recent master.

I rebased it recently unless I screwed that up. I'm assuming that would help with this.

**Comment by QuintusAquila** [comment]
Just in case, I'm going to take your advice and close this and try it with a new branch/squashed commits.

**Comment by eltank** [comment]
image

That doesn't look like a recently rebased branch (742 commits behind)

**Comment by QuintusAquila** [comment]
Then I am assured in my decision to just start clean with a new branch

**Comment by eltank** [comment]
If you decide to squash via the copy-paste method, please do that before rebasing, otherwise you'll overwrite more recent commits to some of the files.

**Comment by QuintusAquila** [comment]
> If you decide to squash via the copy-paste method, please do that before rebasing, otherwise you'll overwrite more recent commits to some of the files.

I've confirmed I don't know how to rebase. I'll copy paste the code into file instead of file over file.

**Comment by eltank** [comment]
If it helps, I did manage to copy, squash and rebase your changes here:
https://github.com/eltank/Cataclysm-DDA/commit/d773e9fb3d6dfa9bd71f3e37f1e1fe89ea6b3b9d
https://github.com/eltank/Cataclysm-DDA/tree/msr

**Comment by QuintusAquila** [comment]
Thanks for that, but I did figure it out after I looked at "my" master. I'm still learning git.

**Pull request closed without merging**
