### PR TITLE
.460 guns can also load .45

### LINKED ISSUE #32549: .460 Rowland caliber guns can't chamber .45 ACP ammo
# Describe the bug

All four .460 Rowland caliber firearms claim to be able to chamber .45 ACP ammo in their descriptions, but are actually unable to because of their `"ammo": "460"`.

# Expected behavior

According to this thread, .460 Rowland chambered guns would be able to fire .45 ACP ammo, but possibly with lower accuracy and higher carbon buildup:
https://www.thehighroad.org/index.php?threads/45-colt-in-460-magnum-pistols.815507/

A solution to this would be to let all .460 Rowland guns and magazines chamber .45 ACP ammo, but with increased dispersion. I personally don't know if a framework for this exists.

### LINKED ISSUE #32889: L2031 enforcer's description says it can use both .45 and 460 ammo, but it only uses 460.
Not much else to say. I added a screenshot showing quotes from both the L2031 and the description of the 460 Rowland ammo. If it is fluff only and it was changed for balance reasosn, it should be corrected.

image

### PR DESCRIPTION
**Pull request by aierce**
It's description says it should be able to fire both .45 and .460

"Fixes #32889"

"Fixes #32549"

#### Summary
SUMMARY: Bugfixes "Made all 460 guns and magazines also accept 45 ammo"

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
Can you add .45 to the speedloader as well? It also says it works with that ammo

**Comment by aierce** [comment]
Can someone explain why gorgon-ghprb check failed? It's not giving an error code.

**Comment by LaVeyanFiend** [comment]
> Can someone explain why gorgon-ghprb check failed? It's not giving an error code.

Jenkins rebuild

**Comment by Hirmuolio** [comment]
Not having the summary in the pull request will also make gorgon complain.

**Comment by anothersimulacrum** [comment]
You need to add a summary line

**Comment by aierce** [comment]
where is this summary line?

**Comment by AMurkin** [comment]
SUMMARY: Bugfixes "Made all 460 guns and magazines also accept 45 ammo"

**Comment by aierce** [comment]
Did you mean Change the line under **summary**? I have done that. Or did you mean Change the title?

**Comment by AMurkin** [comment]
The line under summary. With the category and the description.
Now it should be ok.
Jenkins rebuild.

**Comment by RarkGrames** [comment]
You can also put #32549 in the "fixes" part.

**Pull request merged**
