### PR TITLE
Fixed the error when the 'memorial' dir was not found.

### PR DESCRIPTION
**Pull request by Soyweiser**
See this http://smf.cataclysmdda.com/index.php?topic=12936.15 topic, when there memorial dir didn't exist there was an error message creating the nested directories.

This should fix this.

### CODE REVIEW

**Comment by mugling** [comment]
Could we not just revert the original bad commit?

**Comment by Soyweiser** [comment]
Well, that doesn't implement the feature of different memorial dirs per world. Which was the reason I made the first pr.

**Comment by mugling** [comment]
We still have no way of testing these changes and given that the first PR was trivial yet still resulted in issues it's perhaps not encouraging to make further changes

**Comment by Soyweiser** [comment]
When I noticed the problem on the forums, I asked a friend if she could test it on a win10 machine. (To reproduce the bug). While reproducing, I found the bug myself (on my win7 machine). So I could ask her to test it again on the win10 one.

I have tested it myself by removing the memorial dir. (Something I had not tested before, (assumptions, ass me etc)).

**Comment by Coolthulhu** [comment]
Testing if the dir exists and creating it if it doesn't should be pretty safe and shouldn't introduce other problems.

**Comment by Soyweiser** [comment]
Asked my friend to test on win10. Works there as well. No error messages creating a world and suicide a char.

**Pull request merged**
