### PR TITLE
[MoM] Final 0.H Fixes 

### LINKED ISSUE #71572: [Mind Over Matter] Fountain of Flame Starts at Range Self
### Describe the bug

When creating a new character with the default survivor profession, the Newly-Awakened Pyrokinetic background, and no other changes, the Fountain of Flames spell you start with has a range of self. This renders it useless until you have spammed it enough times to level it up to a point where it has a range of 1.

### Attach save file

[TestWorld-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14186615/TestWorld-trimmed.tar.gz)

### Steps to reproduce

1. Make a character with the Newly-Awakened Pyrokinetic background
2. Use Fountain of Flames

### Expected behavior

Fountain of Flames has a usable range from the outset.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

I also noticed that it has a maximum range of 4 when I made a debug character to see what how the range changed with rank, but I'm unsure if that's a bug to be mention here or a balancing discussion to be addressed as a separate issue.

### LINKED ISSUE #71614: [Mind over Matter] contemplation: gateway (and presumably contemplation: oubliette) resets spell level to 1
### Describe the bug

These two crafting recipes seems to be the only ones that call difficulty_seven_contemplation(1) and difficulty_eight_contemplation(1), in addition to checking if spell level is 1 or above (ie learned). On failing that difficulty contemplation check, after I finish crafting contemplation recipe, meditation starts immediately and attempts to learn the spell (that I already know). On "success", spell level is set to 1.

### Attach save file

[City View-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14209490/City.View-trimmed.tar.gz)

### Steps to reproduce

craft contemplation: gateway recipe

### Expected behavior

Spell level doesn't reset to 1 when attempting to practice it.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    No Bullshit [no_bullshit]
]

### Additional context

_No response_

### LINKED ISSUE #71621: [MoM] Concentrating on Coagulation while you sleep
### Describe the bug

The Coagulation power doesn't deactivate on going to sleep like all the other concentration powers does. I suppose it's not impossible that this is intentional, but if any power could be concentrated on 24/7, Coagulation is not the one I would expect.

### Attach save file

[TestingMoM-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14213409/TestingMoM-trimmed.tar.gz)

### Steps to reproduce

1. Open save
2. Check status menu, take note of four powers being concentrated on
3. Go to sleep
4. Check status menu when you wake, see Coagulation still active

### Expected behavior

I expected that it would turn off overnight like every other concentration power I've experienced. Admittedly, that's only a couple trees so far, so it's possible that there are more like this, but it did stick out to me.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods  "[MoM] Final 0.H Fixes "

#### Purpose of change

Now that the power learning overhaul is done, this is a PR to collect any bugs before setting it to be ported to 0.H stable and I move on to more new content.

Fixes #71572

Fixes #71614

Fixes #71621

#### Describe the solution

Fix bugs

#### Testing

Listed bugs are fixed.

### CODE REVIEW

**Comment by Nebnis** [comment]
Another one, unlocking adrenaline trigger says hardened skin instead

**Comment by Rokharn** [comment]
Not sure if it's intended, but pyrokinesis Crucible have 12000 base stamina cost on the verge of what is possible with pumped up cardio. The difficulty level exceeds the difficulty of other psionics branches, where second high cost is 11500 for telekinesis Earthshaker (much more expensive in terms of stamina too, than other branches). This is 'mind over matter', but in the end this is cardio over mind, so matter over mind.

**Comment by Standing-Storm** [comment]
IIRC the max with pumped up cardio is closer to 21000 (I just checked my and higher but not maxed cardio Sky Island character has 14400 base stamina), so it's a significant cost but it's not insurmountable.

**Comment by Rokharn** [comment]
To maintain cardio person need to do some sorts of exercise, which decrease current max stamina to improve global max stamina level, so as result Crucible rarely possible to use enough time to actually training it like other powers before stamina before current stamina level drop below it's usage level. 

And for some strange reasons I see no effect to cardio, when do all this psionic at all, so needs to use exercise action, as well. After whole season of pyrokinetic practice training day by day (using abnormal amount of stamina daily) I achieved enough stamina to use crucible only after start exercise, which strange. 

At fact I was losing cardio daily, when used only psionic without anything else. The fitness bracelet also showed insufficient body load.

**Comment by Standing-Storm** [comment]
The way I implemented the calorie drain from psionics doesn't count as exercise, which I'm actually happy with (it's supposed to be weird and not really fit how physics works), but it does mean you'll have to supplement your psionics practice with mundane exercise. 

Spellcasting stamina drain not counting as exercise might be unintended, though--I'd report that as a bug and see if that's how it's supposed to work or not.

**Comment by Nebnis** [comment]
Contemplating Lacerating touch also have wrong description.(btw if you think this is spammy i can tonne down)

**Comment by Nebnis** [comment]
Also would be nice if enervating touch scaled the regen debuff with levels. Let's say -4 per level. At 12, that would be -48 and would negate most regen things  in the game. I'm really not really feeling the flat half debuff since the duration is so short for those fights that tend to last a lot

**Comment by Vsevolod-Shustov** [comment]
Minor stuff should be dumped here, right?

practice_biokin_adrenaline typo: success message says "You've unlocked the Hardened Skin power"
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/MindOverMatter/recipes/practice/biokinetic_practice.json#L538

**Comment by Nebnis** [comment]
Hyper enhanced metabolism has no effect description
image

Using wakeful rest, then when it ends and ask you "if you would like to continue this activity" and if you pick "Ignore this distraction and continue"it completely locks up the game with alt+f4 being needed.

**Comment by Standing-Storm** [comment]
> Using wakeful rest, then when it ends and ask you "if you would like to continue this activity" and if you pick "Ignore this distraction and continue"it completely locks up the game with alt+f4 being needed. image image

Known bug with player-defined activities: #69780

**Comment by Nebnis** [comment]
Couple of other things i noticed. I'm not sure if i understood right but voltaic strikes eletricity clouds is hurting me, when it shouldnt? Walking into there hurts.

Also enhanced mobility is preventing me from using my stainless claws(rat mutation) unarmed attack. I can't figure out why this is happening because it has allows natural attacks. Maybe the flag don't work for auras and such.

**Comment by Standing-Storm** [comment]
> Couple of other things i noticed. I'm not sure if i understood right but voltaic strikes eletricity clouds is hurting me, when it shouldnt? Walking into there hurts.

If you have a very low level of Voltaic Strikes, that can happen, but once you get a couple levels it shoudn't be a problem any more.

**Comment by Standing-Storm** [comment]
@Maleclypse 

Now that this is in, here is the list of 0.H Backport PRs:

#70621 (Itzcuauhtli uniform changes--might already be in depending on when in the day 0.H was taken from)
#70623 (Knockdown telekinetic power, assumed in the telekinetic overhaul)
#70729 (Telekinesis learning revamp)
#70830 (Bugfix Nether Attunement gain from rounding down too often)
#70838 (Clairsentience learning revamp)
#70904 (Checks to make sure that players always have the recipes for the powers they know)
#70910 (Bugfix Detoxification power)
#70956 (Pyrokinesis learning revamp)
#70984 (Bugfix Telekinesis contemplation recipes)
#71024 (Bugfix Doomseer starting power name)
#71061 (Telepathy learning revamp)
#71228 (Photokinesis learning revamp)
#71260 (Bugfix Ch47 holster)
#71276 (Bugfix powers missing kcal cost)
#71399 (Vitakinesis learning revamp)

+ This PR, and that should be it.

**Pull request merged**
