### PR TITLE
Replaced 't_misc_floor' with 't_misc_floor_roofed'

### PR DESCRIPTION
**Pull request by UmbralReaper**
#### Summary

SUMMARY: None 

#### Purpose of change
The purpose of this change is to increase clarity in the code in regards to whether a given piece of terrain has a roof or not. This is in response to issue #39972 

#### Describe the solution
Every instance of 't_misc_floor' that had the flags "INDOORS" and "SUPPORTS_ROOF" was renamed to 't_misc_floor_roofed'. I also changed 't_floor_noroof' to 't_floor_no_roof'.

#### Describe alternatives you've considered
None.

#### Testing
None.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I'm not sure I agree with this solution, and this isn't the way to go about it. Done like this it is an enormous and far reaching change that will break nearly every mod and save made for the game.

**Comment by UmbralReaper** [comment]
Ah, I didn't even consider the impacts on save files. Honestly, though, i'm not particularly convinced as to the importance of this change either, it just seemed like a good place to start contributing and learn the basics of using Github.

**Comment by I-am-Erk** [comment]
Ah, well on the bright side this shows you can use github effectively!

**Comment by I-am-Erk** [comment]
Forgot to ask, are you looking for a different first contribution? Cause I can totally suggest a few easy ones.

**Pull request closed without merging**
