### PR TITLE
Customizable bite attacks

### PR DESCRIPTION
**Pull request by Coolthulhu**
Made "BITE" monster attack into a "bite" monster attack actor.
Allows setting:
- Precise damage types (requires quite a bit of text, see the diff) - type, amount, penetration, armor multiplier and post-armor damage multiplier
- Minimum and maximum multiplier on dealt damage (rolled per attack)
- Move cost to execute the bite
- Accuracy separate from monster's default accuracy
- Infection chance (a bit unwieldy, set as `one_in( no_infection_chance - dealt damage )`)

Set the new bite attacks for all critters, set some of the new values for specific critters:
- Slavering biter gets armor piercing bite with nice (dual-typed) damage on it. Higher cooldown and lower non-bite accuracy to compensate.
- Decayed zed and rot-weiler get weaker non-bite accuracy and more infectious bites.
- Feral line gets stabbing bite because needle teeth. Predator's bite is very armor piercing, ones below slightly armor piercing
- Everything else with a bite attack gets slightly lower max bite damage, but slight armor piercing due to damage being rolled post-armor now

Added some helper functions to damage.cpp to allow loading damage instances from jsons.
This could allow, for example, to easily add "weird" damage types to ranged weapons. For example, bashing damage to sling rocks, heat damage to flamethrower and lasers and acid damage to some sort of an acid sprayer.

### CODE REVIEW

**Comment by macrosblackd** [comment]
One of the things that has always bugged me about bite is that it doesn't go through the same logic as other melee attacks. Do you think there might be a way to encapsulate the bite attack into a melee attack that can then go through that logic?

**Comment by Coolthulhu** [comment]
It would be possible to make it use same accuracy rolls, target same body parts, eat up dodge rolls and trigger HIT_AND_RUN, if that's what you mean.

Using same exact logic won't happen, as it would prevent informing the player about what just happened.

**Comment by macrosblackd** [comment]
That would be ideal I think, with all the rebalancing around combat, I don't think special attacks were ever visited.

**Comment by Rivet-the-Zombie** [comment]
Very nice!

**Comment by chaosvolt** [comment]
This gives me an idea. What about acid bites? Logically acidic zombies, spitters in particular, would have some acid effects when biting.

Plus, imagine if we had mutant brown reclude spiders with an necrosis-causing bite. o3o

**Comment by Coolthulhu** [comment]
> What about acid bites?

Technically this PR allows even electric bites and "true damage" bites.

**Comment by chaosvolt** [comment]
> Technically this PR allows even electric bites and "true damage" bites.

Oooh. So even shocker zombies can add to the Fun.

**Comment by Coolthulhu** [comment]
The problem is, all bites that cause damage can cause infections.
So shocker bite could cause infection through metal armor.

**Comment by chaosvolt** [comment]
Ah, that is odd. Why not a way to specify different changes of infection? So not only can different biting enemies be more or less likely to transmit diseases, it would also allow for enemies with zero change of giving an infection.

Which might be acceptible in the case of acid-producing enemies at least, though I doubt electrified innards are really that sterile. XP

**Comment by Coolthulhu** [comment]
> Why not a way to specify different changes of infection?

Because it is big enough already.

**Comment by chaosvolt** [comment]
Ah, true. ;w;

**Comment by macrosblackd** [comment]
I was reminded earlier this morning why I disliked the bite logic - there is no hit roll, the player either dodges or he gets hit, the monster can't miss.

**Comment by chaosvolt** [comment]
Clearly all zombies have legendary Biter skill, by DF logic. o3o

**Comment by BevapDin** [comment]
The assignment in the constructor of `bite_actor` seems to be a bit pointless. It only sets initial values for some members (but not all of them), and they are overridden in the `load` function anyway. Why not keep the constructor empty and in the header, like in the other `mattack_actor`?

**Comment by chaosvolt** [comment]
Errors ensue if Arcana mod is used, fixing in: https://github.com/CleverRaven/Cataclysm-DDA/pull/15085

**Pull request merged**
