### PR TITLE
Add speedloaders for many guns

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Add speedloaders for many guns, mainly revolvers"```
#### Purpose of change

Adds speedloaders for revolvers, for a much faster reloading option for many guns. Reloading without them is still possible.
#### Describe the solution

Add speedloader items, their spawns, and set guns to use them via JSON. Also adds a recipe for tube loader for Marlin 39A.
#### Describe alternatives you've considered

1. Adding crafting recipes for speedloaders. Couldn't find any info on how they could be improvised, though.
2. Set player-crafted revolvers to use speedloaders too. No idea what type of revolver they are, though; depending on design, speedloaders might not work.
#### Additional context

Weight and price of speedloaders are wild guesses; would be good if someone could provide actual info on that.

### CODE REVIEW

**Comment by Throwaway-name** [comment]
Did you test these changes with extended realistic guns mod active?

**Comment by Rivet-the-Zombie** [comment]
Keep in mind that some revolvers have a [loading gate](https://en.wikipedia.org/wiki/Cylinder_(firearms)#Fixed_cylinder_designs) that prevents the usage of speedloaders.

**Comment by kevingranade** [comment]
Echoing @Rivet-the-Zombie 's comment, please do some basic research and determine if a given revolver is at least capable of accepting a speedloader before adding one.

Having said that, I spot-checked all the non-fictional guns you've added speedloaders to, and they all seem to have swing-out cylinders, so they should be fine.

I'd consider making some of the very largest caliber fictional guns fixed-frame, but I won't insist.

**Comment by Rail-Runner** [comment]
Did a bit of research on speedloaders.

Ruger LCR .22 speedloader: https://www.youtube.com/watch?v=8y8JiNhTkfc
Ruger LCR .38 speeloader: https://www.youtube.com/watch?v=e-9Y_Pv7_RE
S&W 610 speedloader: https://www.youtube.com/watch?v=6724UKl2lz0 (it shows moon clips, but this probably means that a speedloader is possible too)
S&W 629 speedloader: https://www.youtube.com/watch?v=wGeVwjLpzF0 (doesn't seem to note that the gun shown is exactly S&W 629, but it is a .44 Magnum S&W revolver, so it should be good enough)
Taurus Raging Bull speedloader: https://www.amazon.com/5-Star-Firearms-Taurus-Loader/dp/B007JL4IVA (one comment seems to say that it works for Taurus Raging Bull .454 Casull specifically)
S&W 500 speedloader: https://www.youtube.com/watch?v=DLybRf4n-Ao (doesn't actually show loading, but video name assumes that it does work for S&W 500)
Marlin 39A speedloader: https://www.youtube.com/watch?v=fJubPAFve2s (even shows that it is possible to make)

**Comment by Throwaway-name** [comment]
You also need to add this to the sw_610 in realguns/gun.json to fix the bug:
`    "magazines": [ [ "10mm_auto", [ "40_speedloader" ] ] ],`

**Comment by Rail-Runner** [comment]
Done, should be working now.

**Comment by jimmydoh** [comment]
Still breaks with Extended Realistic Guns mod active.

Typo in realguns/magazine.json:

"copy_from" instead of "copy-from" and needs a "name" or throws member not found: name and can't load a save / start a new game.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/latest-experimental-features/5582/1106

**Pull request merged**
