### PR TITLE
Changes to primer recipes

### PR DESCRIPTION
**Pull request by DangerNoodle**
Altered the recipes for primers, incorporating the use of matches. This is based off a video found demonstrating the use of matches (both the match heads, and the red phosphorous from the striker) to make an impact-sensitive material. The video reference can be found here: https://www.youtube.com/watch?v=t_7LWCFH5Gc

The match charges used in these recipes do not presently match up with what the video cites, as fully realistic figures would entail using a large number of matchbooks (the red phosphorous from the strikers would be the limiting factor).

An alternative would be to make the recipe similar to Armstrong's mixture, where the role of oxidider (normally the match heads) is replaced by potassium chlorate or potassium perchlorate, which the generic oxidizer powder presumably stands in for in the prior recipe. Since the oxidizer is replacing the role of the match heads, realistically it would not reduce consumption of striker material.

Feedback would be desirable. The main complication in terms of game balance is that oxy powder can be crafted, while match books are uncraftable yet easily scavenged (even with cities disabled).

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I'd like this even more if it allowed matches or oxidizer powder instead of dropping oxidizer from the recipe entirely.

**Comment by Coolthulhu** [comment]
I'd wait with it until we can have tool vs component selections. Or until matches are made into individual items rather than matchbooks.

**Comment by mugling** [comment]
I'm not sure about oxidizer - it's probably both unrealistic and more importantly hard to balance. We could easily split matches though.

This PR also needs some judicious `copy-from` an abstract primer recipe now we have support for that.

**Comment by DangerNoodle** [comment]
> I'd wait with it until we can have tool vs component selections. Or until matches are made into individual items rather than matchbooks.

Is it possible to define a choice of multiple requirements in the `using` section? This would allow

Making matches a discrete item would be less hassle though, though it might also require making the matchbooks themselves items the matches need to activate.

One thing I noticed is all the primer recipes use the same amount of materials to make. I do not have any good data on how much material each uses.

**Comment by mugling** [comment]
> Is it possible to define a choice of multiple requirements in the using section? This would allow using either a tool in one requirement, or a component in a different requirement.

There is no mechanism (by any route) of having tools OR components. This is a hard limitation of the current crafting implementation. `copy-from` and `using` are only for avoiding duplication.

> Making matches a discrete item would be less hassle though, though it might also require making the matchbooks themselves items the matches need to activate.

Just abstract them as individual matches and don't worry about the box - too much detail here. Presume the player keeps hold of it until the last match is consumed.

**Comment by DangerNoodle** [comment]
Very well then. How best should I implement matches as a separate item? A consumable with a use action?

**Comment by mugling** [comment]
> A consumable with a use action?

Or a tool with a really small volume? That needs a new JSON field though for loading volumes <250ml though.

**Comment by DangerNoodle** [comment]
Except the whole reason it is not sanely usable as a component is that it is already a tool. Unless you mean make them each individual tools with a single charge each, but then that leaves the player with a large number of 0-charge matches afterward. Exactly why I suggested making them consumables instead.

**Comment by mugling** [comment]
Tools can be required (and consumed) as a component of recipes.

I think there is a flag to destroy a tool reaching zero charges?

**Comment by DangerNoodle** [comment]
Possibly, but I do recall that making a recipe require, for example, 20 matches as a component actually consumes 20 separate matchbooks, ignoring how many charges is in each. This is why the match head bomb recipe uses 20 charges of matches as a tool, not a component.

**Comment by mugling** [comment]
Well that wouldn't be a problem if each match had only one charge?

**Comment by DangerNoodle** [comment]
That would simplify it, yes. Though if there is a "destroy when used up" code for tools, I am unsure what the advantages are versus making it a consumable, aside from possibly being able to use matches from the eat menu.

**Comment by DangerNoodle** [comment]
Assuming that can be made to work sensibly, where is the flag or property to make tools cease to exist on depletion? As far as I am aware, packs of firecrackers are the only instance I know of this property, and they seem to do so by way of hardcoded behavior.

**Comment by mugling** [comment]
Have a look in `JSON_FLAGS.doc`. If not I'll take a look at adding code support

**Comment by DangerNoodle** [comment]
So far I am seeing no sign of a flag that allows it. Are you aware of any items besides the pack of firecrackers to have this behavior?

**Comment by DangerNoodle** [comment]
In the apparent absence of a way to make tools behave like consumables, what is it that allows first aid kits to not be eaten, that the bandages and improvised first aid kits lack?

**Comment by mugling** [comment]
It's hardcoded by item id

**Comment by DangerNoodle** [comment]
That is very peculiar. It makes sense for non-ingested medical items to not populate the eating menu, so what prompted such a specific change?

**Comment by Coolthulhu** [comment]
A bug that prevented kits from being consumed from outside inventory.

Meds should not use the same menu as food, but at the moment "comestible" includes food, meds, food ingredients that aren't food and shit like bleach that has no place among food.

**Comment by DangerNoodle** [comment]
First aid items are possibly acceptable to only be activated in the `a` menu.

That said, making matches (and bandages, etc) inedible is only a flavor an consistency detail. I could make matches consumables if that is the only sane way to make them work as components.

**Comment by mugling** [comment]
> I could make matches consumables if that is the only sane way to make them work as components.

No, lets try and fix the problem rather than resort to JSON abuse - it only makes later cleanup harder

**Comment by DangerNoodle** [comment]
Very well then. What is the desired idea though? Making matches work in a saner manner is only essential for this if we want to retain oxidizer powder as an alternative to matches.

If it either replaces oxy powder entirely, or we make the recipe require both, then no change to match behavior is required yet.

**Comment by mugling** [comment]
I'd prefer without oxypowder

**Comment by DangerNoodle** [comment]
So for now it hopefully does not require I touch how matches work. Any other suggestions?

**Comment by DangerNoodle** [comment]
Hmm. Do recipes allow for templates and copy-from, or just items?

**Comment by mugling** [comment]
Recipes support both `abstract` and `copy-from`

**Comment by DangerNoodle** [comment]
Hmm. Any current examples of that?

**Comment by mugling** [comment]
> Hmm. Any current examples of that?

Maybe in the recent crafting refactor PR that added support for that?

**Comment by DangerNoodle** [comment]
I will have to look into it later, when I have time,

**Comment by DangerNoodle** [comment]
I have tested this after observing your uncraft example, and it does not appear to work at present.

copy failure

I have made certain that they were copying the correct name I set for the abstract recipe. I implemented `json\recipes\classes\ammo.json` as the place to put it, and placing it someqwhere weird is the only other probable cause I can think of. I will test again with the folder in the recipe folder itself.

**Comment by mugling** [comment]
Where are we up to on this?

**Comment by DangerNoodle** [comment]
I am unsure. It says that Coolthulhu assigned, then unassigned, themselves.

**Comment by kevingranade** [comment]
> The match charges used in these recipes do
> not presently match up with what the video
> cites, as fully realistic figures would entail
> using a large number of matchbooks (the red
> phosphorous from the strikers would be the
> limiting factor).

Why? The reason we don't have a matches->primer recipe is because it's
impractical, if you want to add it and make it realistically impractical,
great, but don't cite evidence showing that it's *possible* and then
willfully ignore the fact that the source also indicates that it's not a
reasonable thing to do.

**Comment by mugling** [comment]
Aren't primers currently made from the even more unrealistic 'oxypowder'

**Comment by mugling** [comment]
What is the matches:primer ratio?

**Comment by DangerNoodle** [comment]
> but don't cite evidence showing that it's *possible* and then willfully ignore the fact that the source also indicates that it's not a reasonable thing to do.

The video indicates it works fine for small scale usage. The currect recipe is even less realistic, while being potentially easier than it should be for the sake of game balance. The changed recipe is at least grounded in reality, while fudging the numbers for the sake of game balance.

> What is the matches:primer ratio?

If we went with the video, 1 match would provide material for 2 to 3 small pistol primers. At present 1 matchhead translates into 5 small pistol primers, as the recipe makes 100 primers and requires 20 matches. This goes up to 1:4 for large pistol and small rifle primers (100 primers, 25 matches), then 1:3.333 for large rifle and shotgun primers (100 primers, 30 matches).

**Comment by mugling** [comment]
Matches are preferable to oxypowder but those numbers are a little high. We should be able to model discrete matches following the recent changes to `stackable` and `volume`?

**Comment by Coolthulhu** [comment]
Oxypowder can be produced.
I'd rather see a matches->oxy recipe than matches->primer replacing oxy->primer or tons of duplicate primer recipes.

**Comment by mugling** [comment]
What actually is 'oxypowder'? We seem to use it as a general reagent when we don't have anything better in mind?

**Comment by Coolthulhu** [comment]
Nonspecific oxidizer.
Not necessarily just
> when we don't have anything better in mind

Often the more important part is that adding a reagent that would have just 1-2 recipes for it would be a horrible idea.

**Comment by DangerNoodle** [comment]
I am guessing that oxidizer powder is meant to be generic, though possibly potassium chlorate (which is an ingrediant in match head). The question is whether making primers harder to produce in a wilderness setting, but easier to obtained via scavenging, is a good or a bad thing. That determines whether the "more realism" idea presented here is itself good or bad

And now I am unsure why it has abruptly decided to declare failure. It is citing astyle regressions?

> Matches are preferable to oxypowder but those numbers are a little high.

High in which regard?

**Comment by mugling** [comment]
I've already pushed a build fix for the astyle regressions.

**Comment by mugling** [comment]
> The question is whether making primers harder to produce in a wilderness setting, but easier to obtain via scavenging, is a good or a bad thing.

Yes, that is a valid point actually - which is better from a gameplay POV?

**Comment by DangerNoodle** [comment]
> I've already pushed a build fix for the astyle regressions.

Ah, thank you. Regarding that gameplay question, that is the thing I am uncertain about. On the one hand, matches cannot be crafted. On the other hand, they are ubiquitous and easily scavenged. Even in my wilderness playthroughs, with cities disabled, I seem to regularly run into isolated locations where they can be found.

**Comment by DangerNoodle** [comment]
Complicating matters, if I recall oxidizer powder can be crafted, but likewise the production chain terminates in something unfeasible to craft. It requires bleach to make, and making that is one of the few recipes to still explicitly demand charges from a chemistry set (presumably electroysis is used).

At that point it boils down to batteries requiring a source of metal for contacts and a metal container, all of which entails scavenging but are again trivial to find.

This presumably means the net effect of this pull request is a realism change that simplifies the supply chain in producing primers, but puts more strain on their consumption of matches. Though as matches are readily hoarded, this might not be much of a downside.

**Comment by kevingranade** [comment]
> The currect recipe is even less realistic, while being potentially easier than it should be for the sake of game balance. The changed recipe is at least grounded in reality, while fudging the numbers for the sake of game balance.

This isn't ok.  just use the numbers from your source.

> If we went with the video, 1 match would provide material for 2 to 3 small pistol primers.

This sounds fine.

I agree with Coolthulu that a Matches->oxy powder recipe would be more useful in general.

**Comment by DangerNoodle** [comment]
Due to disagreements on this idea and merge conflicts, I am closing this. I have been busy lately with other things, and am uncertain what the ideal direction would be here.

**Comment by mugling** [comment]
> I agree with Coolthulu that a Matches->oxy powder recipe would be more useful in general

That could work. It would force the player to continually scavenge for new primary resources. I might rework matches in a separate PR and then we can reconsider primers from there

**Comment by DangerNoodle** [comment]
That might be the best solution then. If I do anything with that, I might prefer to wait until matches have been reworked.

**Pull request closed without merging**
