### PR TITLE
Trading contacts established. Authorize additional resource release.

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
None

#### Purpose of change
The exodii are currently in an early beta state. The store only includes very basic stuff.

#### Describe the solution
- [x] Update tier 1 CBM stock after getting CBMs installed if you are at low trust
- [x] Spawn tier 2 CBM stock at least 2 weeks after meeting Rubik and after trust increases
- [x] Spawn tier 3 CBM stock after at least 4 weeks and after trust increases
- [x] Spawn tier 4 CBM stock after at least 8 weeks and after trust increases
- [x] fix bad link caught in player tests
- [x] Add dialogue about the store stock
- [x] Add more dialogue about exodii lore based on player feedback
- ~~Add more small talk about other topics~~ deferred for a later pr.
- [x] update translation comments

The exodii trust mechanic was added last PR, but did nearly nothing. It can be increased up to a point by regularly trading with the exodii, increasing by 1 every 20 dollars sold. It also goes up gradually by coming back and saying hi and rechecking stock every few days. 

Of note, trade alone can only get you to trust 20, enough to reach tier 3. You can't get tier 4 without at least showing up regularly quite diligently and trading a lot, but generally you'll also want to run a few missions or do something else to prove you're cool.

CBM tier lists:
I'll be revising how these work shortly, primarily to include sub-groups so that a given tier list spawn will include a good variety of stuff.

Further CBMs will be available. Combat CBMs will be added in a future PR as there will be some other things you can do to get those. Top-shelf "tier 5" CBMs will be mission specials.

#### Testing
WIP
Loads without error... _so far_

### CODE REVIEW

**Comment by CountAlex** [comment]
Would you please also add plain English context for Rubik's lines that still lack it?

**Comment by I-am-Erk** [comment]
> I'm struggling to think of a material reason they'd hold it back, but isn't the fact that it's really useful justification enough? I assume part of the reason for this tiering system is that they don't want to hand out their best tools to someone who might waste them - or worse, use them against the Exodii. Doesn't matter if you have 10 AKs or 10,000 AKs, you don't sell a single one to someone if you aren't 100% sure they won't just turn around and shoot you with it.

The exodii aren't worried about you turning cbms against them so much as they're concerned that you'll vanish into the wasteland and they won't get the resources back. That's why time is the primary factor, the longer you survive the more likely you are to return.

Don't debate these tier lists yet as the posted one is a bit out of date, and I have to find the more updated one. Further, after sleeping on it I'm kinda inclined to break up the tier lists a little into utility collections, so that the store has a better likelihood of containing a variety of stuff and not just three batteries and four alarms.

However:
- if a CBM is overly good, but makes sense to be readily available, we should generally consider either nerfing it or making two versions. Like we could make a reduced efficiency battery charger cbm to start, and have a high efficiency one be much higher level. Cost can also be a mitigator, if the cbm is too cheap we can bump it up.
- although battery chargers are a really useful cbm, they're not high tech. In general I don't think exodii would call e to stop you having them
- chargers are less important at low tiers since you won't have much stuff that uses CBM power yet, so a battery charger appearing early isn't a big deal really.

**Comment by I-am-Erk** [comment]
> Would you please also add plain English context for Rubik's lines that still lack it?

I'll try to get them done. Feel free to check back and add review comments for any I've missed when this is out of draft

**Comment by I-am-Erk** [comment]
I have no plans to write a complex system for custom-ordering CBMs, besides the fact that most of these are repackaged and reused. I'm already like seven PRs deep here and not even 1/5 of the way through content.

As I said, this is not the only method for restocking the store. I'd really appreciate not continuing that discussion here, it's not relevant and when I start adding missions and stuff that can boost the store stock, that would be a good opportunity to address concerns about whether or not the store has enough interesting content at low levels, since I'm already planning to do that.

Likewise, concerns about the battery system balance probably should be in a separate issue. It does sound like the CBM does too much... it probably shouldn't double as a power storage CBM, for example. That's not for this PR either though.

**Comment by I-am-Erk** [comment]
Once conflicts resolved this is about ready. I could use some help testing.

**Pull request merged**
