### PR TITLE
nerf finding kitten to level of music enjoyment

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary
Balance "nerf finding kitten to level of music enjoyment"

#### Purpose of change
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/61420

### CODE REVIEW

**Comment by andrei8l** [comment]
You need to find the kitten to get that bonus. That is, play the game that has been bringing boundless joy since 1997. 30 is possibly too low.

**Review by anothersimulacrum — COMMENTED** [review]
Some of these other games also give 30, don't just unfairly nerf robot finds kitten!

**Comment by omni-Var** [comment]
Shouldn't boons that require active input from the user assess a stronger buff? Looking for objections to not make a PR to re-tune it up, somewhat, again.

**Comment by l29ah** [comment]
Do you suggest incentivizing micromanagement?

**Comment by omni-Var** [comment]
Do you suggest removing all reward for additional investment? I didn't hear anyone complaining about this one.

**Comment by l29ah** [comment]
Press `x` 1000 times to get a morale boost with no in-game time expense.

**Pull request merged**
