### PR TITLE
[WIP] Vitamin adjustment in fruits and veggies

### PR DESCRIPTION
**Pull request by Wayticus**
#### Summary: 
SUMMARY: Content "Adjust vitamin levels of fruits and vegetables."

#### Purpose of change
To adjust vitamins that fruits and vegetables give to be more inline with real world levels.

#### Describe the solution
Adjust the vitamin levels to be more accurate rather then based on the healthy level multiplied by 83 for fruits.

#### Additional context
When working on my dried fruits thing, I noticed how the vitamins are handled, also noticed that fruits are off, or just lacking in vitamins, take a banana it does not have as more vitC as an orange(especially if you ate the peels), but does have vitB normally at a higher level then vitC.  Or an apricot, they are a good source of vitA, more the twice the vitC you get from them.  A lot of fruits also are a decent source of calcium and iron.
This will make many fruits have a lower level of VitC but some get a boost, while adding other vitamins, and minerals.  Haven't look at veggies yet.

I know if my dried fruits and this one goes through I'll have to adjust those levels of vitC since they were based on the current levels.

### CODE REVIEW

**Comment by Wayticus** [comment]
Got a question about this, when testing it in a mod the irradiated items did not inherit the new vitamin levels unless I also added them to the comestibles changed, will that be necessary if it is going to be mainlined?

**Comment by Cyrano7** [comment]
@Wayticus IDK what your using as a IRL reference but here is a good database if you need one. https://ndb.nal.usda.gov/ndb/search/list

**Comment by I-am-Erk** [comment]
Your gorgon-ghprb check failed because you don't have a valid summary line. You need something like 
`SUMMARY: Content "fixed vitamin content of fruits"`
This will tell the game updater what's in this PR.

**Comment by KorGgenT** [comment]
With #27233 this will need to be redone to be in correct files

**Comment by ZhilkinSerg** [comment]
Marking as Stalled to clean up PR queue. Please ping me to get it reopened when you feel you can continue working on it.

**Pull request closed without merging**
