### PR TITLE
Merge adjacent wires and improve wire handling

### PR DESCRIPTION
**Pull request by Xenoamor**
#### Summary
Performance "Improve reveal wire handling and performance"

#### Purpose of change
1) Revealed wires will now merge themselves with any neighbours. This drastically reduces the vehicle count and shall hopefully help to improve some of the lag found in #55133.
2) Prevents revealing multiple wires on the same tile
3) Built appliances will only automatically connect to neighbouring vehicles once to reduce the power cord part count

#### Describe the solution
Wiring slowdown occurs due to a large number of connected vehicles which makes walking the connected vehicle graph slow. This combines all wires into a single vehicle to keep the count down. 

#### Describe alternatives you've considered
Another solution would be to rewrite the power grid code so that "networks" are made which are fast to iterate over but slow to create/modify. Whilst much faster this would require a lot of code changes.

We could also merge appliances to the wire vehicles but this would require changes to the dragging code to allow things such as a standing lamp to be detachable from the power grid vehicle.

#### Testing
Confirm wires do merge as they should

#### Additional context
Unfortunately as this only gets triggered on a new wire being revealed any old saves with a lot of revealed wires will still suffer from lag

### CODE REVIEW

**Comment by Maleclypse** [comment]
Is it possible for you to test the performance or create a set of saves with and without this change that someone can test?

**Comment by Xenoamor** [comment]
I made the following test setup:
image
1x storage battery on frame
3x standing lamps
20x uncovered wires

Here's with no appliances or wires:
image

Here's the code as it currently stands:
image

And here's with this patch:
image

**Comment by kevingranade** [comment]
There is an issue if the vehicle is too big, but the failure mode for wires don't have the same severity.
Say you have a 100 tile long vehicle
As you walk toward it, it doesn't load until the origin submap is loaded, so potentially the vehicle pops into existence right in front of you.
But a "wires" vehicle doesn't really need to be loaded unless there's an attached appliance or vehicle on the map, then the jumper code goes and loads it.

There's a hypothetical problem where a wires vehicle isn't loaded and has no attached appliances, or all its appliances are off the current map, and you do the wire reveal thing somewhere it already covers, or try to attach an appliance to it.

To avoid this, I think a "wires" vehicle must refuse to grow more than 60 tiles from its origin, then the player can't be adjacent from it without the vehicle being loaded first.

To avoid "pop", the distance from origin to edge needs to be 24 or less.

**Comment by Fosheze** [comment]
This should probably be applied to solar panels and batteries as well seeing as how those are also likely to be placed in bulk. It would also make sense that those wouldn't realistically just be easily dragged around and plugged in anywhere. 

Having a "STATIC" flag for appliances like that which this code would apply to would probably be handy but is almost certainly out of scope for this PR.

**Pull request merged**
