### PR TITLE
Rescale recovery chance to match previous probabilities

### LINKED ISSUE #74655: Arrows/Bolts are Extremely Brittle and Have Very Low Chance of Recovery
### Describe the bug

Due to some recent changes to game mechanic (some speculate due to this: https://github.com/CleverRaven/Cataclysm-DDA/pull/73931 but I lack the skills needed to tell heads from tails in the code) reclaimable projectiles (arrows/bolts) are extremely unlikely to survive a shot, which leads to bows/crossbows being unusable.

### Attach save file

[Addie-trimmed.tar.gz](https://github.com/user-attachments/files/15888757/Addie-trimmed.tar.gz)

### Steps to reproduce

Here is a test.
1) A character has the weakest bow in the game (survival bow) so arrow breaking another arrow is extremely unlikely and 20 wooden broadhead arrows (one of the sturdiest types of arrows, having a "decent" chance of remaining intact)
fl001
2) First, let's try shooting an imaginary target (as far as I can understand, the practice target is not material and an arrow actually can not collide with it).
fl002
3)After 20 shots only 3 arrows remained!
fl003
4) Now, with another 20 arrows let's try a "living" target…
fl004
5) One dummy "dead" and another one "wounded" (alas, could not get an arrow to embed into them) the result is marginally better. Only 5 arrows remain.
fl005

### Expected behavior

I expect arrows to be as sturdy as they were before the changes: roughly 18-19 wooden broadhead arrows remaining intact out of 20 shot.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-06-18-0730 d3ae4fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
Fixes #74655 
As outlined in that issue, the meaning of recovery chance was changed in #73931 without rescaling the numbers.
They kinda sorta look like percents, but the vast majority of those numbers were working as intended in the previous system.

#### Describe the solution
Rescale all the numbers to match previous behavior.
Had to poke at the menus too because they expected the previous numbers.

#### Describe alternatives you've considered
These aren't golden and perfect numbers, and some authors may well have intended to have single-digit recovery chances for things, but the safest bet right now is restoring the recovery rate we've had for years.

#### Testing
Spawned a hunting bow and a debug monster and 100 simple wooden arrows.
Fired all hundred arrows.
Counted arrows with view window, 89, pretty close to the expected 83.
Examined some arrows and verified that it wasn't claiming every single arrow had a good chance of recovery.

### CODE REVIEW

**Comment by SirPendrak** [comment]
Would it be okay to add recovery chance for pebbles as well? 
Something like: 
98% for pebble,
50% for clay pellet,
10% for glass marble,
99% for steel ball bearing

**Comment by Alm999** [comment]
> Would it be okay to add recovery chance for pebbles as well?

I always assumed pebble is not recoverable not because it is broken upon impact, but rather because it is extremely hard to _find_ in all the grass/pavement cracks etc. Afer all, unlike arrow/bolt (which is also not that easy to find in a field/forest if you miss a shot) pebble is pretty small.

**Comment by SirPendrak** [comment]
Then it would require some new mechanic, like very small items in certain fields are only visable from like 1-2 tiles

**Comment by kevingranade** [comment]
> Would it be okay to add recovery chance for pebbles as well?

Go ahead.  I do think it's reasonable to have some amount of recovery chance represent "you lost track of it and there's no way to find it now", especially for the smaller projectiles.

**Pull request merged**
