### PR TITLE
Added some of mugling's suppressor buffs and buffed compact_suppressor

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Made compact_suppressor compatable with SMGs and added @mugling's suppressor damage buffs from https://github.com/CleverRaven/Cataclysm-DDA/pull/17724/commits/16afc91d7f113611c08fcae1cd39d26490349116

### CODE REVIEW

**Comment by Wishbringer** [comment]
Most suppressors actually increases muzzle velocity, contrary to popular beliefs. 👍

**Comment by BorkBorkGoesTheCode** [comment]
>Most suppressors actually increase muzzle velocity, contrary to popular beliefs. 

mugling just removed the damage penalties from the compact suppressor and suppressor, they didn't give them damage bonuses. This buffs them to "damage_modifier": 0.

**Comment by Wishbringer** [comment]
I'm aware, just meant that removing penalties is a step in the right direction. :)

**Comment by BorkBorkGoesTheCode** [comment]
mugling also suggested making suppressors disable iron sights when installed, as a balance.

**Comment by NotFuji** [comment]
TBH, I think the increased weight and volume is balance enough.  There's already certain guns that won't fit in holsters/etc with suppressors attached.

**Comment by Wishbringer** [comment]
Some smaller guns have their iron-sights blocked when using a suppressor, especially when the suppressor is improvised, larger guns typically wouldn't have that problem.

**Pull request merged**
