### PR TITLE
Astyle mission.cpp and npctalk.cpp

### PR DESCRIPTION
**Pull request by kevingranade**
More semi-automated astyling.
The remaining files have rather large numbers of diffs, I'm going to have to start staging them by a hundred lines or so at a time :P

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
> The remaining files have rather large numbers of diffs, I'm going to have to start staging them by a hundred lines or so at a time :P

How many more files totally have to be astyled?

**Comment by Leland** [comment]
@ZhilkinSerg https://github.com/CleverRaven/Cataclysm-DDA/blob/master/astyle_blacklist

**Comment by kevingranade** [comment]
It's about 100 files, but the last 50 or so have 1000+ lines each that get
adjusted by astyle, and the last few are many thousand.

**Comment by ZhilkinSerg** [comment]
>@ZhilkinSerg https://github.com/CleverRaven/Cataclysm-DDA/blob/master/astyle_blacklist

Thanks!

> It's about 100 files, but the last 50 or so have 1000+ lines each that get adjusted by astyle, and the last few are many thousand.

Oh, that would be huge amount of PRs if we go with ~100 astyled lines. Why can't we astyle more lines per PR?

**Comment by kevingranade** [comment]
it's a balance of making forward progress vs making the PRs a pain in the
ass to deal with.
Probably more than 100 LOC per is fine, 1000LOC is definitely out,
somewhere in between is what needs to happen, most likely on the low side
like ~300LOC or so.

**Comment by kevingranade** [comment]
Jenkins Rebuild

**Comment by kevingranade** [comment]
My local astyle version (3.0.1) is different from the one on Jenkins I guess?

**Pull request merged**
