### PR TITLE
Adds early-game filing tool: sandpaper

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

SUMMARY: Content "Add sandpaper as an early game filing option"

#### Purpose of change

We lack early game filing tools. So I added this. Extremely common, but imprecise option.

#### Describe the solution

Add sandpaper (filing 1). Shows up prominently in houses and workshops. (they have rolls and rolls of the stuff).

#### Describe alternatives you've considered

Leave players without an early game option for filing.

### CODE REVIEW

**Comment by CodeBandit** [comment]
Out of curiosity, what are files even used for currently?

**Comment by Xenomorph-III** [comment]
Not much, I think.

**Comment by CodeBandit** [comment]
From what I saw at a glance, nothing does which makes it dead code unless some mod out there makes use of it.

**Comment by Xenomorph-III** [comment]
EDIT: I have plans to add a recipe for a slam-fire shotgun which uses FILING 1.

**Comment by Testudo-Cultu** [comment]
Realistically, sanding and filing aren't truly interchangeable, but sandpaper should definitely be a thing. It might not be a bad idea to also add a tool quality to sandpaper specifically for sanding.

**Comment by Leland** [comment]
> to also add a tool quality to sandpaper specifically for sanding

I somewhat agree with this, although we could instead just treat "FILING 1" as sanding. Adding yet another quality with no associated recipes seems no bueno.

**Comment by meladath** [comment]
> 
> 
> Realistically, sanding and filing aren't truly interchangeable

Are they not? Do you know of a surface that is too strong for sandpaper but is worn away with a file?

The only difference in them is size/shape/grit really. The purpose they perform is identical, albeit the file has the potential to take off a lot more metal much quicker.

**Comment by kevingranade** [comment]
There are several ways that filing and sanding are different.  Sandpaper wears differently, depending on the type, sandpaper may not be able to sand a particular metal, the shape of sandpaper can be a limitation with fine fitting operations.

**Comment by Testudo-Cultu** [comment]
> The only difference in them is size/shape/grit really.

I think you're missing my point, but it's mostly what Kevin said. You cannot substitute sandpaper with a file. I'm not talking about substituting a file with sandpaper. Sandpaper should work as a mediocre substitute to a file, but you can never wear a material down the same way with a file as you could with sandpaper.

**Comment by kevingranade** [comment]
Good point yes, filing is never going to get you smoothing, it's going to be covered in gouges.

**Comment by CptFail92** [comment]
Perhaps "honing" rather than "sanding?"

It occurs to me that filing should be _required_ to make an edge, like an axe, and honing should likewise be required to make fine edges for knives and swords. The current metalworking recipes seem to assume that a blade comes out of the forge as sharp as it needs to be, which I do not believe is true.

**Comment by Xenomorph-III** [comment]
Yah, that's fine. Using sandpaper for a makeshift barrel seems OK.

**Comment by meladath** [comment]
> 
> 
> There are several ways that filing and sanding are different. Sandpaper wears differently, depending on the type, sandpaper may not be able to sand a particular metal, the shape of sandpaper can be a limitation with fine fitting operations.

Absolutely, thats why I suggested the changes I did. Wrap sandpaper around the wood to make a makeshift "file" good enough for low tier stuff, and sandpaper having charges, which really it should anyway because it wears out over time.

**Comment by Xenomorph-III** [comment]
Any changes I need to make?

**Pull request merged**
