### PR TITLE
More Survival Tools Mod, Series 3

### PR DESCRIPTION
**Pull request by chaosvolt**
Well, it's that time again.

Priority Changes:
1. Tweaked mod's description in modinfo, due to being too long.
2. Removed alumimum foil wraps, since real aluminum foil is a thing.
3. Modernized encumbrance values of clothing added by the mod.

Other Item Changes:
1. Toned down hand axe's damage to be comparable to the sharp rock.
2. Tweaked deliciousness of hard cheese, since it's not assumed to be
fancy.

Other Recipe Changes:
1. Cheese no longer uses a hammer quality, but does need a rag to serve
as a cheesecloth.
2. Fur leggings require less fur to make, and now needs a cutting
quality of 1.
3. Skill requirement tweaks for a couple copper tools.

Item Group Changes:
1. Removal of foil wraps, and foil-wrapped food that were added to make
use of the item.
2. A few rarity tweaks.

### CODE REVIEW

**Comment by graysage1** [comment]
@chaosvolt  Just the person I wanted to see. :)  Do you mind taking a look at #12143?

**Comment by chaosvolt** [comment]
Meep. Okay? o.o

**Comment by chaosvolt** [comment]
*looks* Huh. Oh fuck, ember carrier's active version still has 100 capacity? >.o

**Comment by Coolthulhu** [comment]
Are you removing the foil item completely or only your override?

If completely, make sure saves made with the old version of the mod (that has the foil) load without errors in the new one.

**Comment by chaosvolt** [comment]
Only removing my version of it, the "foil wrap" item that functions as a container. It has the code name "foil_alum" instead of the mainline version named "aluminum_foil" instead.

**Comment by Coolthulhu** [comment]
Total removal of an item from mod will cause errors for those who have this item spawned.
Remove all spawn points and recipes for the foil wrap, but don't remove the wrap itself yet.

**Comment by chaosvolt** [comment]
Ack. I was just editing my last comment to report I discovered that.

I still kinda like the idea of using aluminum foil to cook though. ;A;

**Comment by Coolthulhu** [comment]
Foil is used to cook in ovens, not in hand.

**Comment by chaosvolt** [comment]
Hmm, true. Having it explicitly function in some recipes might work instead? Like alternative recipes for basic cooking/baking items that replace the need for a cooking quality with using some foil, and then...wait, dunno if recipes can specify "product in container" outputs. Seems only the item-transform item action can do such a thing.

**Comment by chaosvolt** [comment]
Also, rain finally coming in. Thanks to satellite net, further updates and responses for today might be delayed or intermittent depending on how heavy it gets.

**Comment by chaosvolt** [comment]
Ah, thank you. Hadn't found any other issues to tweak, so seems to be good for the time being. No ideas for new content either. I was half-tempted to implement that "sand jacket" idea from the bad ideas thread for the hell of it, but that wouldn't fit the theme. o3o

**Comment by Coolthulhu** [comment]
For the future:
* Work gloves are much tougher than leather gloves, but don't have any more encumbrance. They should either have 20 (or more) encumbrance or be unable to be refitted. Or have much less armor, no more than leather gloves.
* Ember holder could have similar code to refillable lighter, except with significantly larger moves cost (it takes a while to set a fire with just an ember). That would make it more future-proof, for the 3D changes and the like

**Comment by chaosvolt** [comment]
Hmm. 10 more encumbrance for the work gloves makes sense, and higher moves cost could work. To basically make it not instant, but not as time-consuming as a fire drill?

**Comment by Coolthulhu** [comment]
Yeah. IRL fire drill creates an ember, which is then dropped on some dry tinder. From there it's basically the same as with a lighter.

Could also waste some charges (10?) because you lose a large part of the ember to start the fire.

**Comment by chaosvolt** [comment]
Hmm, would make sense, and be less cheap since tinder is freely available.

Possibly around a minute or so use time? Not sure what the minimum time for the fire drill is. owo

**Comment by Coolthulhu** [comment]
Fire drill can go as low as a minute.
Two/three turns would be fine - about 3 seconds to open the holder and drop the ember, ~9 to grab the new tinder and set it on fire from the fire that just started and 3-6 to stuff the new tinder into the holder.

If you wanted it to use the entire minute, it should probably use extended firestarter action, which doesn't have move cost setting yet and always uses the same time as fire drill. If you used the regular one, it would not be cancellable, which is OK when it uses a tiny amount of time but not OK for more than about 5 turns.

**Comment by chaosvolt** [comment]
Ah right. Only issue is I'm not sure how to assign a move cost to the ember carrier without tweaking the source files again.

**Comment by Coolthulhu** [comment]
Copy the jsons from refillable lighter and don't use the dedicated function.

**Comment by chaosvolt** [comment]
Does it properly revert to an ember carrier when extinguished, though? Used to be it would turn into a refillable lighter when turned off, hence the function. ;w;

**Comment by Coolthulhu** [comment]
> Does it properly revert to an ember carrier when extinguished, though?

Look at the json for refillable lighter. It will be quite obvious when you see it.

**Comment by graysage1** [comment]
@Coolthulhu , @chaosvolt 

>Ember holder could have similar code to refillable lighter, except with significantly larger moves cost (it takes a while to set a fire with just an ember).

It should be much faster than both fire drill and flint and steel.

The whole point of working the fire drill is to get to the glowing ember stage.  With an ember carrier you already have the ember.  That's why people even bother to carry embers in the first place, and yea, it's a real survivalist tactic as best I know from reading about such things.  Although the ember carriers I've heard of were carved from hard mushrooms that grow on trees and weren't made from tin cans.

So I can accept that an ember carrier is slower than a lighter, but it has to be much faster than the other primitive tools.

**Comment by graysage1** [comment]
Here's something very similar to what I had in mind:

https://www.youtube.com/watch?v=nzyta3_WXz0

**Comment by Coolthulhu** [comment]
> It should be much faster than both fire drill and flint and steel.

Fire drill is always at least 1 minute, which is 10 turns. 3 turns (~20 seconds) sound about right to me, assuming the survivor is trying to be fast, but reload the holder at the end.

**Comment by chaosvolt** [comment]
Hmm, might reduce the ember carrier's volume, yeah.

And I agree, slower than a lighter, which seems to be instant, but faster than the minute or more of a fire drill. Even just 1 turn (which is 6 seconds according to the watches) is slower than a lighter, so I might give it 2-3 turns?

**Comment by graysage1** [comment]
@chaosvolt 

>Birch would just make my fucking day. 

Birch is a very important tree for survivalism/bushcraft, and I do believe it grows in New England (correct me if I am wrong).  It's a source of drinkable water too (technically sweet watery sap), among other things, but it needs to be tapped before that can be extracted.

Chaosvolt, it looks like you're into bushcraft, so you might be interested in this idea here: #11583

That kind of thing might be better in a survivalism mod anyway than in the main game.  In any case, your mod is already great as is.

**Comment by chaosvolt** [comment]
Ah, thank you. Birch would also be the most logical tree to find tinder fungus on, so... owo

Dew collection would be interesting, but might be complex to set up.

**Pull request merged**
