### PR TITLE
Possible fix for RealZogzog's compile error

### PR DESCRIPTION
**Pull request by bkentel**
- use defaulted con/destructors.

### CODE REVIEW

**Comment by RealZogzog** [comment]
I think here would be a better place to discuss that.
Thanks for your attention anyway.

**Comment by bkentel** [comment]
Indeed. From the inline comments: https://gcc.gnu.org/ml/gcc-bugs/2013-02/msg01584.html.
Is upgrading an option? This could probably also be (verbosely, and redundantly according to the standard) worked around by adding an explicit `noexcept` to the destructors.

**Comment by RealZogzog** [comment]
Thank you, I'm out trashing that old broken Debuntu of mine for something else, I'll be back to you then (that WILL take time)

**Comment by RealZogzog** [comment]
Should we clean our inline comments ?

**Comment by bkentel** [comment]
I wouldn't worry about it. Shouldn't be a problem AFAIK.

**Comment by RealZogzog** [comment]
Ok, see you then.
and thanks again.

**Comment by narc0tiq** [comment]
Given that (as demonstrated by the gcc bugzilla link) even `virtual ~classname() = default` doesn't fix it, should we just discard this PR? Or does defaulting the con/destructors explicitly offer other benefits? Talk to me as a C++ outsider -- I've looked in, from time to time, but it still seems somewhat insane to me.

**Comment by bkentel** [comment]
The advice is to to be explicit about what you mean w.r.t to defaulted and deleted special member functions. If your con/destructor does what the compiler would do, don't try to second guess it or make other people second guess your intent: *"did the writer really intend for this destructor to be empty? Why?"*. Say, `= default` if you mean it until your actual needs change. The only thing better would be not saying anything at all -- but that's not an option here.

This PR isn't critical, but it's still not a bad idea IMO.

**Comment by kevingranade** [comment]
This is not higher priority than compiler compatibility.

**Comment by bkentel** [comment]
I know I've asked before, but what is our minimum GCC target anyway? A list of broken language/library features would be helpful.

**Comment by bkentel** [comment]
To fix the build issue this tried to address, `iuse_actor`'s destructor will have to be un-`default`ed. I'll take care of it later if no one else does in the meantime.

**Comment by DavidKeaton** [comment]
I would like some stats on broken tools or libs, I always have latest, but not everyone gets that luxury.

**Comment by bkentel** [comment]
It's surprisingly hard to find a delta of bugs fixed from GCC 4.7.1 (the version shipped with the aging official C::B package) and trunk.

**Pull request closed without merging**
