### PR TITLE
Adds small Ponds

### PR DESCRIPTION
**Pull request by pisskop**
Adds single maptile sized ponds to the game, in field, forest, and swamp flavors.

They can spawn anywhere within their intended terrain, even in cities.

They are set to 0 min so they dont have to spawn.

No critters currently spawn with them, and each one has a degree of variance in size and flora.
   Although I wish Id be able to make more variantion, this will do, and have to do.

Meant to address complaints of water scarcity and provide more flavor

### CODE REVIEW

**Comment by pisskop** [comment]
Plains Pond:
<a href="http://imgur.com/IyjQ1sy"></a>

Forest Pond:
<a href="http://imgur.com/QA94QDi"></a>

Swamp Pond:
<a href="http://imgur.com/aBs0NeT"></a>

**Comment by Rivet-the-Zombie** [comment]
No cattails?

**Comment by BorkBorkGoesTheCode** [comment]
They are also very round.

**Comment by Rivet-the-Zombie** [comment]
>They are also not very round for lakes.

This is true, but have you seen our rivers?

**Comment by BorkBorkGoesTheCode** [comment]
> This is true, but have you seen our rivers?

Yeah, I should have mentioned the rivers as well. Sorry Pisskop.

**Comment by nikheizen** [comment]
> They are also not very round for lakes.

Actually, since CDDA uses squarelos and doesn't have circular distance turned on by default, they will be round for players using the default settings.

**Comment by pisskop** [comment]
I can add cattails.  I knew I forgot something, and it was nonboulder furniture.  I can add boulders too, but Im hesitiant to.

For circular ponds, its something better served as a variation.  Ill see what I cant cook up; the basic permise is here after all.

**Comment by pisskop** [comment]
I knew I forgot something, and it was nonboulder furniture.  Can do cattails.

Round lakes.  Well, it _is_ a pond after all...  with the basic permise down I could make a roundish pond.

**Comment by pisskop** [comment]
Yo
[img]http://i.imgur.com/QFOlH6o.png[/img]

**Comment by Night-Pryanik** [comment]
I like the idea, but ain't they too small? They look more like big puddles rather than small ponds to me.

**Comment by John-Candlebury** [comment]
I dunno, I think they look good

**Comment by nikheizen** [comment]
Those look great, and I think fitting in one map tile is good.
They certainly aren't too small. 12 tiles across is not a puddle IMO.

**Comment by pisskop** [comment]
There are two versions, the original with some small modifications, and this one.  they are 2/3 and 1/3 weighted to spawn, respectively.

**Comment by pisskop** [comment]
Im not getting the swamp one to spawn  right.

Its spawns on roads, in the stead of houses, and in the middle of rivers.  Non of the other ones do this.
  Swamps dont have any dedicated spawns like the rest of the terrains do; lmoes used to do so but idk what happened to that when.

  Swamps are under the id "forest_water", but that doesnt yield a swamppond spawning in the correct location; although sometimes they seem to get it right.

**Comment by pisskop** [comment]
Here is why:

 // then check location flags
    bool passed = false;
    for( const auto& location : special.locations ) {
        // check each location, if one returns true, then return true, else return false
        // never, always, water, land, forest, field, wilderness, by_hiway
        // false, true,   river, !river, forest, forest/field, special
        std::list<std::string> allowed_terrains;
        std::list<std::string> disallowed_terrains;

No swamp option

**Pull request merged**
