### PR TITLE
[READY] Enable unit tests in Travis builds.

### PR DESCRIPTION
**Pull request by kevingranade**
There are a handful of what look like legit failures, I'm planning on having them fail then fix them.

### CODE REVIEW

**Comment by kevingranade** [comment]
Well crap, unit test is segfaulting :/
This might be tricky.

**Comment by DangerNoodle** [comment]
Travis system is already generating constant failed commits. Will this pull request fix that?

**Comment by kevingranade** [comment]
No, its a different issue and should be fixed now, the unit test default is actually reproducing #21045

**Comment by DangerNoodle** [comment]
My apologies, then.

**Comment by kevingranade** [comment]
Now the tests are running, just need to fix the few breakages.

**Comment by kevingranade** [comment]
I don't seem to have anyone interested in merging.  I'm going to go ahead and push this since it provides a huge amount of value re: running tests all the time, but I'd like to see if we can at least get my changes to the main game reviewed going forward.

**Pull request merged**
