### PR TITLE
Added more content to Expanded Realistic Guns

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This PR adds the .357 Magnum I mentioned earlier, the 10mm rebalance, the .50 BMG rebalance, modified versions of the COP 38 and S&W 619 chambered in 357 magnum, and a provisional recipe for .357 Magnum cartridges.

@DangerNoodle , I think your Cataclysm-DDA issue tracker settings are preventing inbound PRs.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Odd. How is that occurring? I am unsure what setting controls that.

**Comment by BorkBorkGoesTheCode** [comment]
I don't really know if it is the cause. The setting is found under the Settings menu in your Cataclysm-DDA fork.

**Comment by DangerNoodle** [comment]
Ah, apologies for that. Let me check the settings.

**Comment by DangerNoodle** [comment]
Is it the "Restrict editing to collaborators only" setting? As that is already disabled.

Either way, I am unsure how uploading content to my fork will facilitate pull requests to the main game. It would still require I keep my fork updated and present pull requests, correct?

Or should I enable you as a collaborator, would that allow what you were intending?

**Comment by BorkBorkGoesTheCode** [comment]
I was thinking about the proposed dropping of mods from core. After that point, we will need to exchange PRs directly when maintaining this mod.

I still cannot create a PR in your repo.

**Comment by DangerNoodle** [comment]
I am still uncertain about the idea of dropping mods. Combining mods and mainlining content would be more reasonable. And I am uncertain how to find what setting controls this.

Are you sure it is not due to my CDDA repository being a fork?

**Comment by BorkBorkGoesTheCode** [comment]
>Are you sure it is not due to my CDDA repository being a fork?

The weird thing is, I can target other forks, not yours.

**Comment by DangerNoodle** [comment]
I left my settings at defaults other than the change as stated, so I am unsure what setting is the cause.

**Comment by BorkBorkGoesTheCode** [comment]
So everybody will know, I didn't create this PR to test PR issues, in case you were wondering.

**Comment by DangerNoodle** [comment]
Understandable. I am still stumped by that. I will need to look at this content when I get the chance.

**Comment by Rivet-the-Zombie** [comment]
I'm still of the opinion that this belongs in mainline. Adding extra ammunition options is a good thing, adds no extra knowledge requirements, and these missing calibers are a glaring omission.

Saying 'this is too complex for mainline players' is an insult to those players' intelligence.

**Comment by DangerNoodle** [comment]
What is your opinion regarding the discussion elsewhere about removing Arcana and Magic Items mod from the mod selection, @Rivet-the-Zombie?

**Comment by Rivet-the-Zombie** [comment]
If those mods are constantly maintained, then I see no reason to remove them from the default package. If not, we can keep them as options for the launcher.

**Comment by BorkBorkGoesTheCode** [comment]
Documentation update: The .50 BMGs' damage and recoil are based on its Weapons Balance entry in the CleverRaven/Cataclysm-DDA developer wiki. It's comparable to several real-world loadings.

The 10mm Auto has a 155 gr. bullet, and a 430 meter per second muzzle velocity. It has a +2 expansion bonus to damage.

**Comment by BorkBorkGoesTheCode** [comment]
@Coolthulhu thanks for updating Weapons Balance. What are the new rules?

**Comment by Coolthulhu** [comment]
There are no strict rules. Follow the guidelines, but try to find a role for each item.
For example, ammo with comparatively low damage and recoil, but high armor piercing. Or something that trades a lot of range for some damage.

The problem with the balance guide is that it looks like it should be followed to the letter and replaces common sense. It is far too simple to do that - we'd need something like damage per turn system to replace common sense (and even then, it would still need to have ranges of values, not direct formulas).

In general, each item should be better than some other GOOD item in some way.
Except for availability - this can only be used to nerf items ("x is free, nerf x"), but not to buff them ("x spawns only once per million years, it can be better than everything else. What do you mean it's a horrible idea?").

It is better to have noticeable deviations from the standard than to have no-brainers and useless items. For example, if you need to buff damage for an ammo type but don't need to keep the range, don't be afraid to handwave +30% damage over comparable calibers by saying "it's made of high-tech expanding bullets, therefore +30% damage but range drops to 5 tiles".

**Comment by BorkBorkGoesTheCode** [comment]
The niche for the .50 BMG cartridge is as the most powerful rifle round. Its flaws prevent no-brainer status: It suffers from large size, high loudness, the highest recoil, heavy cartridge weight, and heavy rifle weight. 

The purely arbitrary and abstract system in Generic Guns is better than handwaving; It allows greater flexibility in game design, reduces realism complaints, and it is honest.

**Comment by mugling** [comment]
@Coolthulu's argument is correct.

> The niche for the .50 BMG cartridge is as the most powerful rifle round. Its flaws prevent no-brainer status: It suffers from

* large size = irrelevant
* high loudness = severely bugged, past an upper limit irrelevant
* the highest recoil = bugged, past an upper limit irrelevant
* heavy cartridge weight = irrelevant
* heavy rifle weight = somewhat valid

This is the problem with value 'tweaks' - what you almost invariably need is mechanic fixes. To edit a value in the core game you need a robust argument about gameplay. Realism is subjective and we've had previous holy-wars between different camps of realists which we should not be repeating.

Summarily we only really have four places content should be going:

* Core - Items with demonstrable gameplay value
* Generic guns - A generically named subset of items from core
* Extended realism - Anything else that exists (now or very near-future)
* Fictional - Anything else at all

**Comment by mugling** [comment]
Or put more succinctly - you could get set recoil to `40'000` yet it would still be possible to walk adjacent to a hulk and one-shot it via 50bmg. What we need are mechanics fixes not value tweak.s

**Comment by BorkBorkGoesTheCode** [comment]
Could the .50 BMG be obsoleted? It will only attract realism arguments.

**Comment by mugling** [comment]
I don't see why that's necessary - you haven't stated a gameplay argument for that option

**Comment by BorkBorkGoesTheCode** [comment]
The only reason to have the .50 in the game is as an elephant gun. In its present form, it could be easily converted into an AP 7.62x51mm NATO cartridge without many alterations.

**Comment by mugling** [comment]
I'd be keen to widen the gap between `223` and `308` - do you want to expand upon your idea a little and how the stats for the latter might change?

**Comment by BorkBorkGoesTheCode** [comment]
>I'd be keen to widen the gap between  223  and  308  - do you want to expand upon your idea a little and how the stats for the latter might change?

@mugling do you just want me to provide a design concept for the .223 and 308 rounds, or do you want me to include the .50 BMG.

**Comment by mugling** [comment]
I'd go with working on a concept for reworking `308` and dropping `50`. It would be good if the difference between `223` and `308` was more significant. Scavenging vehicle wrecks for usable `308` ammo belts is much more interesting than finding more overpowered `50` ammo that lacks any useful guns to fire it with.

**Comment by mugling** [comment]
Tangent: Next up is jams and malfunctions. Probably a minimal set in core but extensible via JSON for those who want more detail.

**Comment by DangerNoodle** [comment]
As in, adding the flags for no misfires and no jams to more weapons, then removing them in the mod? It seems reasonable, but personally I have very rarely encountered jams during gameplay, generally only fully-automatic weapons (and I suspect those are the most likely to retain them in mainline).

**Comment by mugling** [comment]
No, as in allowing specify different types of failures in JSON but restricted those applied in core to a narrow selection that have significant gameplay value (probably misfire and more serious jam)

**Comment by DangerNoodle** [comment]
Ah, that makes sense actually.

**Comment by Rivet-the-Zombie** [comment]
We've got the M2 and a couple of rifles that fire .50BMG, which is sufficient. I see no reason to remove such a common HMG cartridge.

**Comment by mugling** [comment]
Well removal would enable implementation of a more significant difference between `223` and `308` as opposed to the usual problem that our current items are just clones of each other +/-10%

**Comment by DangerNoodle** [comment]
It seems more like making the .50 BMG higher in damage would likewise give more room to differentiate .223 and .308.

**Comment by mugling** [comment]
That's just more stat twiddling though. You need to come up with niches for the different weapons. For example `308` could have much higher recoil but also significant AP. When we implement exchangeable barrels the `308` weapons could have quick-change barrels. We could also change some magazine `308` weapons for those that use belts which would become more frequently found on vehicle wrecks. Now it's a real choice between `223` and `308`.

Having more redundant ammo types isn't helpful here - if the answer to an argument is 'adjust the stats' it's probably already a lost cause.

The problem I have is that whenever I implement a system to increase variety (especially magazines and alternative ammo) it gets hijacked to ensure that a dozen varieties exist of each item which does rather obviate the purpose and strongly discourage future work.

Sure I could write barrels that heat up, jam frequently if so, and can be changed. But not if that leads to four different types of barrel per gun complete with their own 'realistic' stats.

The plan is to simulate more interesting mechanics - not simulate more items in total.

**Comment by DangerNoodle** [comment]
.50 BMG would logically be the best suited for high-piercing, anti-material essentially. Granted, the problem there is that regardless of which rifle round becomes the designated anti-armor rifle round, we have a dearth of enemies durable enough to make it worth the effort.

Part of it is also that the .308 could be made as a middle-of-the-road, jack-of-all-trades ammunition compared to .223 and .50 BMG, but the downsides are not exactly worth it. Fleshing out the effect of recoil on individual shots could go a long way towards mitigating this, but that alone may not be enough. Other than that, the only other present disadvantages are crafting demands (more powder/lead is a logistics concern in the long run) and volume. Volume however is only relevant for players carrying large amounts of ammo, which makes it a balancing factor if trying to sustain an M2 but is less of a concern if players are sniping with the Barret.

**Comment by mugling** [comment]
I want to add lots of new mechanics to help differentiate the items and you're free to do as you please with those mechanics in the extended mod. What I'm not wanting though is a 'content editor' - it's unreasonable to expect me to write an implementation, fix and maintain it and then for anyone to request a superseding viewpoint especially when forgoing the option of prior discussion (#18571)

The project is reaching a crisis point in development where JSON-bashing and item bloating are more popular than actual coding. 100 types of ammo but no new functions (tracers, AP etc) are a perfect example of this./ I'm going to start fixing this - we write new and interesting mechanics along with unique items in core and push other content of non-majority appeal into the extended gun mod. Anyone with strong opinions needs to either write a better implementation, hold a clear majority at that time or make their case in a mod.

We have too many ammo types with no significant differences between them. Dropping 50 and then some of the 308 magazine rifles in favor of belt fed guns would make it a more meaningful trade-off. You could push those items into extended realistic guns. If you want to help then select some items to move to extended guns and possibly outline a proposal for limited replacement items in core.

**Comment by DangerNoodle** [comment]
Understood.

**Comment by mugling** [comment]
Indeed the AP and tracer rounds are perfect examples. They're just names that have no significant in-game effects. They're pure bloat. Why not `9mm +P+ tracer AP` in that case?

If anyone wants to help the project we should concentrate on increasing the appeal to both new players and particularly new developers. When the dust finally settles would anyone be proud with *'Well we saved < item here > but all the developers and players left'*.

Having an active developer for the subject area you want to work on extending the code plus a maintained mod shipped with the game to add the content you wish ought be enough for anyone.

A plan to rework `308` and/or shift some items to the mod would be welcome and might actually lead to the game being more fun to play and progress on this is really a prerequisite before any further features are implemented.

**Comment by DangerNoodle** [comment]
> If anyone wants to help the project we should concentrate on increasing the appeal to both new players and particularly new developers. When the dust finally settles would anyone be proud with 'Well we saved < item here > but all the developers and players left'.

Possibly. A rework for .308 might be desirable, but I am unsure if removing .50 BMG is really related to the contributor crisis, beyond said problem making work more difficult more general.

If we go this route, I would suggest shifting the .50 BMG weapons not only to Expanded Realistic Guns, but also to Vehicle Additions Pack. My in-game experience has generally led me to heavily use the M2 Browning as a vehicle-mounted weapon, and overall it seems to excel in that. Especially due to mounted weapons being poorly implemented and incomplete, last I checked you can not use precise aim like with handheld weapons, so the high damage of .50 BMG makes underwhelming hits less of a problem.

**Comment by mugling** [comment]
> Things that make players and developers leave

Actually I disagree. Every time I write a PR involving guns we end up with arguments - often highly technical yet of incredibly narrow scope. Sometimes the developers fight newly registered accounts, sometimes the dispute is with contributors and finally sometimes the contributors fight each other.

This makes PR's on this subject horrible to implement. Everyone agrees magazines and aiming were a lot of work and a welcome change. The suggestion that we push bloat content to the mod where I can then stop being concerned by any of this is a good idea.

Now given I'm one of the most active developers and I'm finding the workload here too high how do you think potential developers view the situation?

The parties might change but this argument is doomed to repetition. Duplicate gun content and anything new without a strong gameplay argument belongs in the mod.

**Comment by DangerNoodle** [comment]
> Every time I write a PR involving guns we end up with arguments - often highly technical yet of incredibly narrow scope.

That is why I suggested that removing .50 BMG from mainline might cause more controversy, compared to what is gained by removing it.

**Comment by DangerNoodle** [comment]
That said, controversy is not the biggest downside. The bigger issue is that removing it will also require ensuring mod content is not broken in doing so. To not do so is irresponsible.

**Comment by mugling** [comment]
Or put more simply - I spend months writing a series of PR's to add magazines and in response get 1000+ word incivil rants about the weights and capacities of some magazines being off.

> That is why I suggested that removing .50 BMG from mainline might cause more controversy, compared to what is gained by removing it.

This is at the core of the problem. Anyone can create controversy. They don't need a good reason nor a track record of significant and useful contributions. Frequently they have neither.

Moving content to a mod is a reasonable solution. Stalling development because someone demands their own way despite not having contributed to the code is not.

The lack of developers is now an existential threat. Moving 50 to mod content is not.

**Comment by Rivet-the-Zombie** [comment]
The DDA project was started specifically to add content to the original Cataclysm. 'It exists in the real world' is a good enough reason for decently implemented content to be added to the mainline. We've not been in the habit of removing real-life items from the game in the name of reducing similarity, and I don't see why we shoud begin now.

**Comment by mugling** [comment]
The original cataclysm is dead. We're heading that way as well because nobody wants to work on 'the habbit'. None of the other active developers share that vision and we aren't recruiting anyone else who does.

**Comment by DangerNoodle** [comment]
> The original cataclysm is dead. We're heading that way as well because nobody wants to work on 'the habbit'. None of the other active developers share that vision and we aren't recruiting anyone else who does.

I would suspect there are many reasons for the development decline. Part of it is the initial barrier to entry. Github can be a minor stumbling block, and I admit that the linting system tripped me up prior to the addition of the web linter. There is also a higher number of developers that first arrive with specific features they want to focus on or add, with less sticking around to deal with the tedious yet essential work.

The community may also be a part of it. It is, to put it charitably, tumultuous. My lurking in the forums has largely turned me off the idea of joining it, as it is largely a series of three-way arguments between players, contributors, and developers. Much of it is on the part of the sort of people who, as you have stated, often stir up controversy without offering meaningful contributions. But both contributors and even developers seem to frequently be a part of it, and it is often detrimental to the project (see friction between Kevin and Chaosvolt, for example).

**Comment by mugling** [comment]
> We've not been in the habit of removing real-life items from the game in the name of reducing similarity, and I don't see why we shoud begin now.

1. Bloat is harmful to gameplay (subjective)
2. Majority of active developers are opposed to such bloat (objective)
3. Project is showing significant signs of stalling (objective)

Realistically three developers are now writing the majority of the games engine with you mostly concerning yourself with content. What you want to add isn't the majority view and in any case isn't practical due to our lack of resources.

Moving content to mods is a viable solution to resolving the deadlock after which we should focus on fixing bad mechanics, open issues and actually release a new stable.

**Comment by Rivet-the-Zombie** [comment]
>The original cataclysm is dead. We're heading that way as well because nobody wants to work on 'the habbit'. None of the other active developers share that vision and we aren't recruiting anyone else who does.

We've been around this same argument before you joined the project, including doomsayers predicting The End of DDA. @kevingranade and I both share [the same philosophy](http://smf.cataclysmdda.com/index.php?topic=6146.msg109625#msg109625) here.

**Comment by mugling** [comment]
That reads an awful lot like an attempt to pull rank so I'm going to be blunt. By any metric you might use I write the majority of the code, followed by @Coolthulhu. So at the point when we are saying there is a problem it would be sensible to acknowledge that. The split between the developers is widely commented on elsewhere and attempts to disregard that aren't going to do anything to quell the unrest.

It's far too easy to keep saying 'add it' when you're not having to maintain something afterwards

**Comment by chaosvolt** [comment]
> By any metric you might use I write the majority of the code, followed by @Coolthulhu. So at the point when we are saying there is a problem it would be sensible to acknowledge that.

Welp. Time to grab the popcorn, because this is gonna turn into shitposting awfully fast, if we're at the point where Mugling's actually directing snark at one of the three primary devs.

Christ man, pulling the "you don't do shit around here" argument like you did on the forum is one thing when it's directed at me, but slinging it at Rivet is a dick move. :V

**Comment by mugling** [comment]
Locked because the developers need to reach a consensus as to direction, organization and scope and that neither requires nor is helped by chaosvolt posting incitements.

**Comment by Rivet-the-Zombie** [comment]
There's no need for me to pull rank on stuff like this; the decision was made before I ever joined the project. DDA is meant to be a giant sandbox full to the brim with things to see and do. That means lots of *stuff* of all kinds, and that includes guns and bullets and stuff in addition to all of our hideous monsters, spooky locations, and enormous crafting and construction systems.

>Realistically three developers are now writing the majority of the games engine with you mostly concerning yourself with content. What you want to add isn't the majority view and in any case isn't practical due to our lack of resources.

Back when I wrote more code we had a really awesome dev called @KA101 who used to merge most of the stuff. Since he left I've had to ensure that we keep progressing at a constant rate, so I don't post very many PRs any more.

My opinions on adding stuff like this to the mainline aren't going to be changing any time soon, as they're based on the design philosophy laid out by @kevingranade. Speak with him if you think that needs to change.

**Comment by mugling** [comment]
> the decision was made before I ever joined the project

Binding precedent doesn't work for open source. If the active developers disagree they won't submit code and given sufficient neglect the project will stall. Think about it from another angle - would you accept @Whales dictating terms to the developers due to precedence?

> Since he left I've had to ensure that we keep progressing at a constant rate, so I don't post very many PRs any more.

The complaint isn't that you don't write code PR's but you need to acknowledge that the burden of supporting them rests with a very small minority who frequently object to excessive content. Good examples would proposing more mod content shipped with the game when the developers are already struggling to support the 49 mods we already have as well as rehashing the debate about multiple ammo types in core that was settled in #18571.

> we had a really awesome dev called @KA101 who used to merge most of the stuff

We need to get away from our current merging approach which is mostly button-pushing with no actual scrutiny. It's insane that one line PR's seem to be subject to the same rules as 500+ controversial content.

> My opinions on adding stuff like this to the mainline aren't going to be changing any time soon

Opinions are fine but decisions need to be made democratically between the active developers. A simple deescalation would be to confirm you are in agreement with this principle. Long term we need to consider splitting engine and content to further reduce the friction between differing visions.

**Comment by Rivet-the-Zombie** [comment]
>If the active developers disagree they won't submit code and given sufficient neglect the project will stall.

I've seen this same argument numerous times. It's sort of like trying to hold the project hostage in order to force an opinion, and it's never worked.

>Think about it from another angle - would you accept @Whales dictating terms to the developers due to precedence?

Whales isn't the DDA project lead, @kevingranade is.

>Opinions are fine but decisions need to be made democratically between the active developers.

[@kevingranade has already addressed this](http://smf.cataclysmdda.com/index.php?topic=10444.msg244402#msg244402), and I'm not going to change my stance until the boss man says it needs to.

>A simple deescalation would be to confirm you are in agreement with this principle.

Or we could drop that line of discussion entirely - I'm **not** going to start breaking our ground rules because I've been asked to for the hundredth time.

**Comment by mugling** [comment]
> I've seen this same argument numerous times. It's sort of like trying to hold the project hostage in order to force an opinion, and it's never worked.

There isn't a project without developers or releases! We haven't released in 18 months - this ought to be an indication something is seriously wrong. When have you heard all this before?

> @kevingranade has already addressed this,

I'd be almost certain that you should take that as we aren't having the userbase vote. A project of this scale can't survive without a team of developers. Nobody is going to write large amounts of code for a project without a say in how it progresses. Even if you try and suppress their opinion the areas in which they chose to contribute will affect the direction.

If anyone wants to dictate terms to developers that's employment not open source and the last time the project paid for code it wasn't a success.

**Pull request merged**
