### PR TITLE
Separate assign code and refactor

### PR DESCRIPTION
**Pull request by mugling**
* Moves `assign` family of functions to their own file `assign.h` (separation of concerns)
* Changes template overloading from return argument SFINAE to template argument SFINAE (clarity)
* Pure refactor with no behavioral changes

Dependent PR will then tackle #18926 by adding an `assign` function for `std::map`

### CODE REVIEW

**Comment by mugling** [comment]
Template changes are always an exciting test of compiler support so I don't want to continue on dependent PR until certain this works on all platforms.

Can we push directly to Jenkins and see if it is able to build all the various platforms?

**Comment by Coolthulhu** [comment]
I'll merge for now and revert if it breaks things.

**Comment by mugling** [comment]
Probably the best approach with template code. The buildbot is after all a buildbot so it's hardly unreasonable to use it to test changes on platforms we target.

The fact that ~100% of the playerbase updates from the same binary is a long-standing problem. Once @narc0tiq is back it would be good to discuss if the buildbot could understand git tags so we could mark selected releases **STABLE** or something to that effect.

**Comment by narc0tiq** [comment]
There is a (manual) promotion process in place that saves releases to [jenkins-promoted](http://dev.narc.ro/cataclysm/jenkins-promoted/); I see no obvious way to trigger it by anything else, but it doesn't mean it can't be done.

**Pull request merged**
