### PR TITLE
[CR] Add Two New Blacklist Mods

### PR DESCRIPTION
**Pull request by nikheizen**
These two blacklists I strongly feel will have fairly wide appeal, I already know of several people who play CDDA which use these, or use similar ones. Relative to the total people I know who play CDDA, I think that should be enough to warrant mainline inclusion, however I would be interested to gather other's thoughts on the matter.

I have a bit of a bias myself since I hate having untracked files laying about :stuck_out_tongue: 

The first commit removes a selection of silly/atonal/OP items, and the second removes Zombie animals. These would be for boring people who want to have a somewhat more sombre, less OP apocalypse.

[CR] because I may have missed things, and I would like to hear some thoughts on it.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I'd split off the "pet peeves" into "thematic/roleplay items" and something for the sci-fi items. Not sure how to name the latter.

Zombie animals should probably go into a separate PR. Why doesn't it include dogs?

**Comment by tyrael93** [comment]
@Coolthulhu 
Aren't Zdogs static?
They don't spawn dynamically like the other Zanimals that start appearing after summer

**Comment by nikheizen** [comment]
@Coolthulhu Should I consider just scrapping this and restarting as two(three?) separate PRs? I included all this stuff together mainly to reduce on merge commit spam.

**Comment by Night-Pryanik** [comment]
Don't know what's silly or OP in fedora, blindfold, vibrator, spoon and many other items. Maybe you should change the description?

**Comment by Coolthulhu** [comment]
> Should I consider just scrapping this and restarting as two(three?) separate PRs?

Start with just zombie animals and/or the thematic blacklist.
The third one would be a bit hard to define, since it includes all sorts of different items.

> Don't know what's silly or OP in fedora, blindfold, vibrator, spoon and many other items.

Fedora is the "meme hat".
Vibrator is obviously silly and it's obvious that everyone knows it.
Spoons, forks, glasses, underwear etc. are just thematic items with no gameplay roles. Not everyone wants thematic/roleplay items in their games.
Should probably include more items, though. There are many other flavor items not included here.

As for the OP: it's most likely about the diamond weapons and optical cloak.

**Comment by Rivet-the-Zombie** [comment]
>Should I consider just scrapping this and restarting as two(three?) separate PRs?

This sounds like a really good idea; all combined, it seems more like a 'stuff that I personally don't like' blacklist than a 'OP and silly' blacklist.

**Comment by mugling** [comment]
The suggestion in #17398 would make PR's such as this redundant. One interim step would be starting to move items into content packs?

**Comment by Night-Pryanik** [comment]
> Fedora is the "meme hat".
Vibrator is obviously silly and it's obvious that everyone knows it.
Spoons, forks, glasses, underwear etc. are just thematic items with no gameplay roles. Not everyone wants thematic/roleplay items in their games.
Should probably include more items, though. There are many other flavor items not included here.

Then it should be named "No thematic/flavor items or items with no gameplay roles", not "silly" IMO.

**Comment by Rivet-the-Zombie** [comment]
>Vibrator is obviously silly and it's obvious that everyone knows it.

Do tell; what's obviously silly about it?

**Comment by nikheizen** [comment]
Alright. It seems like the consensus here is to split up the lists into separate branches/PRs.

_No_Zombie_Animals_ is the first and most obvious one.

_No_Thematic_Roleplay_ would be the second one (vibrators, fedoras, scanty/impractical clothing, cosplay, and non-craftable&&non-tool cuisinery kitchenware would go in here). We can discuss the name in the thread.

I still think _No_OP_Items_ is a very apt description for some of these items. Diamond weapons, Optical Cloaks, Adrenaline Rigs, Modular xyz are what one could call BIS (if they even have a slot), and provide significant benefits over the alternatives (if there even are such things) If you find them, then you are behooved to use them if you are not intentionally gimping yourself (and if you are, then they may as well not appear). However, discussion as to the merits of such a list would probably best fit in a PR specifically for such discussion.

@mugling Well, until such a thing is reasonably close to completion, I think that if I do work on this, it can easily be retrofitted into such a content pack (the list would be identical, technically) later, so there is not much potential to waste effort there.

As it seems clear from here that discussion on these topics is disparate, this PR can probably be closed.

**Comment by mugling** [comment]
> I think that if I do work on this, it can easily be retrofitted into such a content pack (the list would be identical, technically) later, so there is not much potential to waste effort there.

It could be tricky maintaining savegame compatibility.

**Comment by Coolthulhu** [comment]
> Do tell; what's obviously silly about it?

The part where it is obviously a sex toy, which makes it silly.
And just like with fursuits being "actually just football mascot costumes" - everyone knows they're fursuits.
Sometimes a cigar is just a cigar, but this isn't the case for waterproof objects used to "de-stress" with morale cap of 320.

**Comment by BorkBorkGoesTheCode** [comment]
> The part where it is obviously a sex toy, which makes it silly.
 Sometimes a cigar is just a cigar, but this isn't the case for waterproof objects used to "de-stress" with morale cap of 320.

What is the problem with vibrators?

>  And just like with fursuits being "actually just football mascot costumes" - everyone knows they're fursuits.

Ditto.

**Comment by mugling** [comment]
That issue has surfaced on a few other occasions which raises the question is the joke really worth it or perhaps they should be moved to the crazy cataclysm mod?

**Comment by BorkBorkGoesTheCode** [comment]
I do not object to vibrators or fursuits. If the morale bonus for using vibrators is too high, it should be rebalanced.

**Comment by mutt3x** [comment]
Putting memes and cringe items inside a game? Oh yeah everybody is going to like this... 10/10
This items should all have been a mod in the first place since its a flavour of Thematic_Roleplay.
But NOoo, now you have... this.

These items enhance someones gameplay but for the majority they are bloat = very mod worthy.

**Comment by nikheizen** [comment]
Going to close this now as it is redundant and discussion of the specific mods would belong better in the PRs I plan to open. Thanks for all the comments and suggestions, everyone.

**Comment by kevingranade** [comment]
Please take a look at the history of this kind of thing:
http://smf.cataclysmdda.com/index.php?topic=11926
http://smf.cataclysmdda.com/index.php?topic=6736

In particular my advice here: http://smf.cataclysmdda.com/index.php?topic=11926.msg264313#msg264313

It's a rather contentious and sensitive subject all around, tread lightly and maybe it'll actually happen this time.

**Pull request closed without merging**
