### PR TITLE
Add Treetops

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Features "Adds treetops and makes trees climbable"

#### Purpose of change

Our trees are big enough to block all movement through their tile, but weren't climbable.

#### Describe the solution

- Adds a "roof" to every tree's json entry, either a treetop, a dead treetop, or an evergreen treetop. These are very basic UNSTABLE and TRANSPARENT floor tiles
- Adds a flag, CLIMBABLE_ADJACENT, that lets you climb a tree if you're standing next to it
- Adds a flag, SINGLE_SUPPORT, that always destroys a tile if the tile under it triggers a collapse, even if there are other adjacent SUPPORTS_ROOF or WALL tiles
- Makes the tinymap created during faction camp tree-cutting jobs extend one Z level higher so it can get rid of treetops when you clear-cut or cut logs from a forest tile via the faction camp billboard
- Makes BIRD_LEGS resist the unstable ground effect, 'cause birds perch in trees irl.

#### Describe alternatives you've considered

Out of scope for now, but it probably wouldn't be too hard to make trees have variable heights. Then you'd scale them with something like the WALL_CLING ability that would be available to anyone, so z+1 would be you clinging to the side of the trunk, and at z+2 you'd be on the treetop, etc.

Making it so that some types of trees aren't climbable, or are only climbable with special equipment or mutation flags would also be easy.

There are only 4 forms of treetops right now, and they're all identical except their colors. The base kind is for all deciduous trees, evergreen, dead, and mega_fern are obviously for trees fitting those descriptions. I'm assuming this will be enough for spriters. If not, it's trivial to add more types of treetops in future PRs.

#### Testing

- Climbed a tree
- Fell out of a tree
- Cut down a few trees
- Used the zone menu to cut down some more trees
- Used the zone menu to make an NPC cut down some more trees
- Started a faction camp and ordered a clear-cut
- Ordered a log-cutting mission at the camp as well

#### Additional context

image

### CODE REVIEW

**Comment by Zireael07** [comment]
Somehow you have LOTS of commits here, I suspect something went wrong with git

**Comment by fairyarmadillo** [comment]
> Somehow you have LOTS of commits here, I suspect something went wrong with git

It did, and I fixed it. As you can see this PR only changes 10 files and then only with relatively minor updates.

**Comment by Rokharn** [comment]
Maybe good idea to add some new animal spawn here (squirrels, birds, maybe spiders and so on) too as well for some loot like bird nests?

**Comment by fairyarmadillo** [comment]
> Maybe good idea to add some new animal spawn here (squirrels, birds, maybe spiders and so on) too as well for some loot like bird nests?

Not a terrible idea, but I'm gonna call it out of scope for now. That's a big project.

**Comment by Procyonae** [comment]
> I am worried about balance concerns. This means that as long as you can climb a tree, you can practically dodge any zombie horde in a forest (due to the poor Z handling we have). Can you check to make sure this PR doesn't trivialize that part of the game?

The only major issue I see with this is that you can use a reach weapon, just going up to "escape" doesn't do much for you bc they'll still be able to see you and just chill waiting for you to come down no? I personally feel like reach weapons shouldn't work across z-levels given the difference in height we typically associate with 1 z level compared to the distance of 1 tile across. Doing any serious damage to a zed from the roof of a bungalow with even a really long spear seems pretty difficult. Obviously you could also shoot the zed but that would aggro more stuff so I don't see that as big of a deal.
Idk how UNSTABLE works rn but making it so attacks have a good chance for you to fall based on "recoil" could be good.

**Comment by fairyarmadillo** [comment]
> I am worried about balance concerns. This means that as long as you can climb a tree, you can practically dodge any zombie horde in a forest (due to the poor Z handling we have). Can you check to make sure this PR doesn't trivialize that part of the game?

There aren't zombie hordes in forests, and after the beginning of the game they can reach up and pull you down, or destroy your tree with you in it.

The only thing it's going to get you is surrounded by zombies with no escape route. You can already easily climb on top of any house in town, where the zombies are, and that hasn't caused any issues.

**Comment by fairyarmadillo** [comment]
Also you may not be aware of this, but climbing requires a free hand and there's a roll involved. You can also fall down and injure or kill yourself doing it. Speaking as someone who makes a living playing this game I don't see a balance issue here outside of the one that already exists for reach weapons.

**Comment by GuardianDll** [comment]
\> you can practically dodge any zombie horde in a forest 

Grabber zombies had an ability to grab enemy on another z-level - it was lost when grabs were reworked, but i think we can return it as one of multiple counters to roof chill

**Comment by sadenar** [comment]
> Also you may not be aware of this, but climbing requires a free hand and there's a roll involved. You can also fall down and injure or kill yourself doing it. Speaking as someone who makes a living playing this game (I hate to bring that up to win an argument, but it's relevant here) I don't see a balance issue here outside of the one that already exists for reach weapons.

I think this is good enough to make climbing a balanced action that can save you in a tight spot but implies some innate risk, especially when you're scared/exhausted/overloaded/sick/whatever.
Zomboid already does it very well in my opinion with the fence climbing checks (although treehouses in that game are a bit op)

**Comment by BlizzDA** [comment]
Would some of the treetops provide shelter from the rain or sun (if albino) if standing under them, or would that be for a future PR?

**Comment by Rabadash94** [comment]
Will there be treehouses in the future?

**Review by I-am-Erk — DISMISSED** [review]
fairyarmadillo note this has pretty much nothing to do with your code work, it is a project infrastructure block.

Heads up to mergers, I think we should probably set this as a 'branch' (hehe) point between the H-stable candidate and I-experimental. We should not be merging this into the stable candidate. Normally we'd be tagging it feature freeze but since we're going to try not to do that this time, I'm just setting this up to be blocked until we have the stable candidate.

I'll see about making a PR tag for this once I am sure I understand how that's going to work fully

**Comment by fairyarmadillo** [comment]
> fairyarmadillo note this has pretty much nothing to do with your code work, it is a project infrastructure block.

It's showing that changes are requested but I don't see anything in conversations. Is there anything I need to do on my end?

> Would some of the treetops provide shelter from the rain or sun (if albino) if standing under them, or would that be for a future PR?

> Will there be treehouses in the future?

I don't see why not in the future, but both of these will probably require multi-tile trees, and we're not there yet.

**Comment by GuardianDll** [comment]
> > fairyarmadillo note this has pretty much nothing to do with your code work, it is a project infrastructure block.

> It's showing that changes are requested but I don't see anything in conversations. Is there anything I need to do on my end?

It's just to ensure this PR won't be merged accidentally, this would be merged after the 0.H would be released

**Comment by I-am-Erk** [comment]
No action needed, I managed to get H branch out before it was relevant

**Comment by mqrause** [comment]
> > Somehow you have LOTS of commits here, I suspect something went wrong with git
> 
> It did, and I fixed it. As you can see this PR only changes 10 files and then only with relatively minor updates.

Please note that there are still a bunch of commits listed that are not actually part of your PR. I assume this will cause some issues or side effects when it gets merged.

**Comment by fairyarmadillo** [comment]
I will probably need to make a new PR then.

**Comment by fairyarmadillo** [comment]
Continued in #70669

**Pull request closed without merging**
