### PR TITLE
Small drug synthesis rework

### PR DESCRIPTION
**Pull request by Nabo92**
#### Summary
Content "Partial chemistry rework"

following up on PR #50511, added proper heroin recipe with the item added on previous PR, also removed old meth recipe. Correcting typo on red phosp**h**orous and adjusting weight of acetic anhydride to match it's density. Then the item match head powder was deleted and  all the recipes associated to it were moved it to red phosphorous.

#### Purpose of change

The previous recipes removed by me made no sense, and now there are more realistic ones that can make the same thing. Another thing is that there was an item called "match head powder", and that's basically red phosphorous (which was added by my previous PR #50511), so I switched all recipes that used one to use the other, to have an unified item tied to the proper element. Lastly I removed old heroin recipe and switched for the proper one with the item introduced in #50511, because that's one way to make it in RL.

#### Describe the solution

removed old recipe and added proper one for heroin (acetic anhydride + morphine in a spoon), removed old meth recipe, but only with lower-grade, following up previous PR #50511 .
Red phosp**h**orous now has two **h**'s and acetic anhydride now has weight that's related to its density.
Item called match head powder was removed and all recipes linked to it were redirected to red phosphorous.

#### Describe alternatives you've considered

Leave the work unfinished.

#### Testing

Loaded new save on new world, saw and crafted recipes indclued and didn't find the excluded ones, didn't encounter any errors.

#### Additional context

I thought about simplifying when I removed the match head powder. It's not PURE red phosphorous, but it's enough to make it work to make good meth (or fuses), because if you have access to a lab to make meth, you could easily purify it. Thought that it'd be just boring to do that with a dedicated recipe for it.
The heroin recipe is made as in RL, so no longer bashing salt and morphine together will net you heroin, you have to find the proper reagent for it, and it ONLY reacts with morphine.
The old meth recipe was removed for the same reason: it's just unreasonable and makes no sense at all. I don't think there's place for another recipe for low quality meth, because it'd be just the same thing but with lower skills, which I don't think makes any sense gameplay-wise.

### CODE REVIEW

**Comment by Venera3** [comment]
Not necessarily for this PR, but if you're open to more work in this space we could use growing normal poppies and morphine+codeine production. I did some research a few months back and got a rough outline of a reasonable production chain, but I really hate working with recipes so I haven't worked on it since then.

**Comment by Nabo92** [comment]
Might get into that, another reason for the recipe to exist in first place

**Comment by tenmillimaster** [comment]
I'd prefer to see the match head powder left in. For one - safety matches, which are most common in the US, don't actually contain phosphorus -- the striker on the side of the box does. Secondly, the safety match heads contain things like potassium chlorate, which is fairly useful in some DIY priming compounds.

Refinement via dissolution and drying of the strikers would be pretty simple.

**Comment by I-am-Erk** [comment]
sorry for the delay!

**Comment by I-am-Erk** [comment]
Just noticed 10mm's comment. We could look into adding match head powder back in and allow recrystallization of it to different components, perhaps

**Comment by ZhilkinSerg** [comment]
Need to add obsolete recipe for `chem_match_head_powder` to https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/recipes.

**Comment by Nabo92** [comment]
> Need to add obsolete recipe for `chem_match_head_powder` to https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/recipes:
> 
> ```
>   {
>     "type": "recipe",
>     "result": "chem_match_head_powder",
>     "obsolete": true
>   }
> ```

Yes, I'll work on it next week, I fucked up some of the recipes and will have to fix that, plus add the rest of the stuff that I said I would.

**Pull request merged**
