### PR TITLE
Style clean

### PR DESCRIPTION
**Pull request by karols146**
Make all deconstruction recipes in just one style.

### CODE REVIEW

**Comment by Cyrano7** [comment]
So the first commit is still to big to be viewed on here.

**Comment by karols146** [comment]
Wow git can be hard sometimes, but i think that Part 1 is nice visible now.

**Comment by illi-kun** [comment]
This PR is terribly huge and has some merge conflicts. Each commit here can be a separate PR for easier processing.

**Comment by karols146** [comment]
Ok I make new PR with just one commit. If it will be good, i just post the rest.

**Comment by Cyrano7** [comment]
Another thing would be since you are going through the trouble of rewriting the file is putting spaces around colons and in between brackets.

**Comment by karols146** [comment]
#16581 - New PR here, all file look like this part. 
Thanks for tip @Cyrano7

**Pull request closed without merging**
