### PR TITLE
A bunch of random item reworks: 12

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
You thought I was done?

#### Describe the solution
<details>
<summary>PLASTIC TUPPERWARE</summary>

- Weight: 130g -> 57g
- Volume: 787ml -> 1463l
- Longest side: 17cm -> 20cm
- ``price_preapoc``: 4$ -> 1.32$
- ``to-hit`` values now use modifiers
- Removed it from the horrendous plastic chunk recipe that caused like a 400g mass voiding
- Lowered it's plastic requirement in the crafting recipe

</details>

<details>
<summary>KETTLE</summary>

- Weight: 728g -> 508g
- Volume: 1575ml -> 3205ml
- Longest side:  21cm -> 19cm
- ``price_preapoc``: 45$ -> 13$
- Audited its deconstruction recipe to match new mass, use level 2 metal sawing and no longer train fabrication

</details>

<details>
<summary>GALLON JUG</summary>

- Weight: 190g -> 160g
- Volume: 3825ml -> 4402ml (potentially too generous?)
- ``price_preapoc``: 0$ -> 10$
- ``to-hit`` values now use modifiers
- Removed the horrendous crafting recipe for it that involved duct taping bottles together
- Lowered the plastic requirements and energy cost for crafting it from raw plastic

</details>

<details>
<summary>GLASS BOTTLE</summary>

- Weight: 450g -> 511g
- Volume: 953ml -> 1082ml (potentially too generous?)
- ``price_preapoc``: 0$ -> 2$
- ``to-hit`` values now use modifiers
- Audited its deconstruction recipe to match the weight
- Removed it from the glass pipe recipe since it caused a big weight loss
- Audited its crafting recipe to match its weight

</details>

<details>
<summary>NAPKIN</summary>

- Weight: 3g -> 1.36g
- Volume: 5ml -> 3ml

</details>

#### Additional context
Caused by #71969, because now carrots are too big to fit inside our tupperware...

### CODE REVIEW

**Comment by Karol1223** [comment]
> Shouldn't a gallon jug be for like a gallon exactly, or is just a name thing of something of that type of jug?

It literally holds a gallon what's the issue

**Comment by EternalLaughter** [comment]
> > Shouldn't a gallon jug be for like a gallon exactly, or is just a name thing of something of that type of jug?
> 
> It literally holds a gallon what's the issue

I don't know if there is an issue. I just saw your increased the volume for it, so i assumed it will now hold more then a gallon "Volume: 3825ml -> 4402ml (potentially too generous?)"
But seeing your answer i assume i just misunderstood and this just the volume of space the gallon jug actually takes up.

**Comment by toweroglass** [comment]
i mean it's one empty gallon jug, Michael, what could it cost? $10?

**Comment by Karol1223** [comment]
> i mean it's one empty gallon jug, Michael. what could it cost? $10?

To be fair I think I misread the amazon listing and it cost 20$ per one jug. I love prices.

**Comment by toweroglass** [comment]
thank you for introducing me to the insanity that is people paying $43 for 10 empty milk jugs (for juice?) instead of just rinsing out a milk jug.

i noticed the more expensive heavy duty jugs and that kind of makes sense in an environment where you need clean jugs. The ones we have in game seem like they would be any number of empty, used jugs which have literally zero "preapoc" value.

Whatever, this is merged. the only issue i think this could cause is if someone wanted to put a gallon of milk into a vending machine. The price would be out of control.

**Pull request merged**
