### PR TITLE
[MoM] Merge lasers and photokinetic damage

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Merge lasers and photokinetic damage"

#### Purpose of change

Since Photokinetic attack powers essentially shoot lasers at people, lasers might as well do photokinetic damage so they can interact.

#### Describe the solution

Change the laser weapons to do photokinetic damage and rename the damage type "focused light."

#### Testing

Spawned a feral beacon and shot it a bunch of times with a laser pistol. No effect.

#### Additional context

I think the Hub turrets are the only base-game laser shooting enemy, and I edited their fake gun.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Love this!

**Comment by RAldrich** [comment]
Not a blocking concern (so maybe I should open an issue instead of discussing it here), but why do lasers (regardless of source) need a new damage type? My understanding is that IRL lasers cause burns, or in cases where power output is high enough, wounds that are quite similar to gunshots.

The basic mechanism is flash vaporization of whatever is at the impact site (mostly water, in a biologist target) leads to a concussion wave. You can actually manipulate how much "heating" vs "explosion" you get through various wavelength manipulations.

An academic source:

https://apps.dtic.mil/sti/citations/ADA476965

**Comment by Maleclypse** [comment]
> Not a blocking concern (so maybe I should open an issue instead of discussing it here), but why do lasers (regardless of source) need a new damage type? My understanding is that IRL lasers cause burns, or in cases where power output is high enough, wounds that are quite similar to gunshots.
> 
> The basic mechanism is flash vaporization of whatever is at the impact site (mostly water, in a biologist target) leads to a concussion wave. You can actually manipulate how much "heating" vs "explosion" you get through various wavelength manipulations.
> 
> An academic source:
> 
> https://apps.dtic.mil/sti/citations/ADA476965

Because this is for Mind over Matter the psychic mod.  And if you have one group of psychics who control heat and fire and one that controls light and lasers, you need to divide heat and laser damage or else there is weird overlap

**Comment by Standing-Storm** [comment]
As well, photokinetic damage is [derived from heat damage](https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/data/mods/MindOverMatter/damage_types.json#L9) and laser weapons still have the INCENDIARY flag on their ammo, so there's no physics violation in this part of the psionic powers mod.

**Pull request merged**
