### PR TITLE
Quantum solar panel to [Aftershock]

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
SUMMARY: Mods "Qantum solar to AFS"

#### Purpose of change
Experimental solar panels are being obsoleted from mainline.  They are good candidate for advanced AFS crafting model. 
#### Describe the solution
Move the json text.

#### Describe alternatives you've considered
None

#### Testing
TBD

### CODE REVIEW

**Comment by Shibimon** [comment]
It should somehow replace or add the removed quantum solar panel reward from one of the lab finales too.

**Comment by Maleclypse** [comment]
> It should somehow replace or add the removed quantum solar panel reward from one of the lab finales too.

Resolved currently.  Ideal situation requires JSONized lab finales and aftershock crafting.

**Comment by Maleclypse** [comment]
This is tied to post 0.E and jsonization of solar charging.

**Comment by Maleclypse** [comment]
Note to self : Read and utilize #38770 to complete this PR.

**Pull request merged**
