### PR TITLE
modernized AK names

### PR DESCRIPTION
**Pull request by ghost**
The original 47s and 74s will be museum pieces by 204X.

### CODE REVIEW

**Comment by chaosvolt** [comment]
I was almost afraid you were going to make up some dumb fictional future name for them, just from the title and description.

But yeah, using the AKM and AK-74M is sensible. Especially since I wouldn't be surprised if the AK-74M lasts that long in service in reality anyway. o3o

**Comment by kevingranade** [comment]
We've been treating the starting time as 'the day after tomorrow' rather
than '30 years from now', especially with respect to existing items like
firearms.
I need to go through and correct things that say otherwise...

**Comment by chaosvolt** [comment]
Hmm. Right, though even today, I would guess that the AKM (and Type 56) are likely more common than original AKs.

**Comment by Rivet-the-Zombie** [comment]
Yeah, the AKM was introduced in 1959; most 'AK-47s' you see are actually AKMs, same with a lot of the '74s (1991 in that case).

**Comment by chaosvolt** [comment]
As I guessed, yeah. So this seems like a reasonable rename no matter how far-off the Cataclysm is set. o3o

**Comment by chaosvolt** [comment]
And now AK-74 over on the forums is complaining to me about the stats still implying the original variants despite using the names of modernized variants. >.<

**Comment by Rivet-the-Zombie** [comment]
The stats imply whatever we want them to.

**Comment by chaosvolt** [comment]
The weight at least I can agree could've been tweaked, but unsure if their complaint about the unchanged recoil is valid. Eiher way...much facepalming ensued because I wasn't the one to PR this, and it was brought up in the thread for Artyom's mod which was thus off-topic. @_@

**Comment by kevingranade** [comment]
Tell them that, don't complain about it here.

**Comment by chaosvolt** [comment]
I did, yes. ._.

**Pull request merged**
