### PR TITLE
Rework electricity fields & damage

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Balance "Rework electricity fields and damage"

#### Purpose of change
I was annoyed by the electricity fields and emitters lighting up solid tiles and going through walls as if nothing was there. I decided to tweak the spreading function a bit and finally ended up redoing it from scratch. The new spread looked good (to me) so I decided to also tweak some other things like damage and chance of shock. I also added a new field type to prevent electricity from lighting up solid non-transparent tiles.

This changes electricity so it only spreads to open tiles when the source of electricity is also in an open tile. It also makes electricity prioritize jumping to impassable tiles (walls, trees, etc.) and creatures. The result is that electricity builds up in impassable tiles and stays there until dissipated. If you get close to a "charged" tile it will arc to you and then jump to other nearby tiles.

This is not too realistic but it looks good as it appears to use you to arc through stuff.

#### Describe the solution
Changed spread of electricity fields to use weights to decide which nearby tile to jump to:
* Open tiles prioritize jumping to creatures or impassable tiles, with a small chance of jumping to another empty tile.
* Impassable tiles only allow jumping to other impassable tiles (electricity builds up) or creatures (it arcs if you get too close).
* A new field type (fd_electricity_unlit) is used for non-transparent tiles that only generates light at very high intensity and isn't visible (no tile/symbol). Get ready for a shocking surprise if you get too close to a charged wall.

Maximum intensity for electricity fields has been increased to 10 (previously 3), while capping damage (from fields) to 4 (previously 3). This is a buff to fields so in turn I added a chance to shock (previously 100% for any damage > 0) based on the damage.
Chances to shock:
* 1-2 damage: 40%
* 3 damage: 60%
* 4 damage: 80%
* 5+ damage: 100%

Shocker attacks;
* Nerfed initial spread from a 5x5 area to a 3x3 area.
* Sparks have a 33% chance (down from 75%) of being created in the 3x3 impact area.
* Increased intensity of initial fields to 4-10 (up from 1-3) to account for the initial area reduction.
* The lower initial spread & random shock chance helps dodging the shockstorms and running away from them.
* High intensity initial fields spread around creating mid-intensity fields that are very similar to the old 5x5 shockstorms.

Other weapon/effect changes:
* EMP grenades start with a smaller blast but a lot more intense so it spreads to about the same size as before.
* Chain Lighting CBM is a bit less consistent creating random patches instead of a 3x3 area but sparks are more intense.
* Damage-wise weapons and attacks should stay the same because damage from electricity fields is capped at 4 (for now). I might look into adding resistances or something next. I'll have to check the backlog and open issues to see if there are any ideas, plans or feedback.

#### Describe alternatives you've considered
Remove shockers and husks.

#### Testing
Very basic testing for now, I'll open this as a draft and see if I can playtest it on my current run. Anyone is welcome to do so and comment on it. Hopefully it will not unbalance things more than they already are when it comes to electricity.

#### Additional context
Keep in mind the "9" symbols will be invisible, I left them as symbols for testing purposes so I could tell if the right field was being created. The 9 symbol means it's an unlit electricity field that should only be created on non-transparent tiles.

Husk inside a house:
HuskInHouse

Shocker in a hive:
ShockerInHive

Shocker around hive:
ShockerAroundHiveShort

### CODE REVIEW

**Comment by Photoloss** [comment]
Don't forget the Chain Lightning CBM and possibly some of the plasma or electrolaser weapons. They use "ammo effect" JSON to define field intensity ranges.

**Comment by GoLoT** [comment]
Thanks for the heads-up. I changed the initial burst from Chain Lighting CBM, EMP grenades and lightning ammo_effects. They all start smaller (more concentrated) now but spread about the same. Damage shouldn't change much because of the 4 damage cap for fields.

I can't find the broken generator traps definition but if it uses emit_field it should work with the changes done for husks. There are also a couple of spells/monster attacks I didn't change and a lot of other spells in Magiclysm that I don't play so I don't know if my changes will break balance (if there is any).

**Comment by Tommy-os** [comment]
Artifacts can also spawn with electric field effect on use.

**Comment by GoLoT** [comment]
From what I can find in the json files it's spawning fd_electricity fields randomly so I think it should be fine with the changes as they affect any fd_electricity fields being spawned. The fields will be low intensity (2) so they won't light up the tiles as much as they did before but damage-wise they will be the same as before (with a lower chance to shock) so I'll assume they work fine.

**Comment by I-am-Erk** [comment]
Let's see how much this breaks.

**Pull request merged**
