### PR TITLE
Moved Flaming Electric Car to Bright Nights mod, renamed it to Flaming Atomic Car and made it spawn

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Mods "Moved Flaming Electric Car to Bright Nights mod, renamed it to Flaming Atomic Car and made it spawn."```

#### Purpose of change
While searching through the vehicles' jsons, I stumbled upon a very strange car prototype named Flaming Electric Car. As I never encountered it ingame, I wanted to know where it is spawning. And found out that it isn't spawning anywhere. Because of its weirdness (electric car with a M249 machine gun, a water cannon, and a flamethrower) I decided to move it to Bright Nights mod and made it spawn at last.

#### Describe the solution
Moved car's definition to BN's `cars.json`. Added it to all vehicle groups in mod's `vehicle_groups.json` with a fairly low chance to spawn.

#### Describe alternatives you've considered
Remove it altogether.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Oof I'm  halfway through making bright nights spawn only atomic cars. If you add a mini reactor to this car it would be much appreciated.

**Comment by Night-Pryanik** [comment]
If it's not fully suitable for BN, then maybe I'll move it to AF instead? Pinging @Ilysen.

**Comment by Ilysen** [comment]
I always felt like the FEC was just a dev blueprint someone put in to spawn for kicks. It's true that Aftershock *does* have a good amount of electric cars, but definitely none like this one.

The closest thing I can see is an APC with a flamethrower mounted on it, but otherwise I don't think it'd fit in Aftershock. For Crazy Cataclysm, though, I could see it working, but I dunno!

**Comment by Night-Pryanik** [comment]
Added a minireactor and therefore renamed it to Flaming Atomic Car. 
It's real strange
изображение

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Pull request merged**
