### PR TITLE
PRM:  Remove old ants

### PR DESCRIPTION
**Pull request by pisskop**
Takes out the kwama ant that shot electricity.
  Not because its the most fanciful ant (it was) but because I want a clear theme to each insect species.

bumblebees do electricity.

### CODE REVIEW

**Comment by Soyweiser** [comment]
Just wondering, what happens to players who use your mod, and have had this mob spawn?

**Comment by pisskop** [comment]
what do you mean?  They play the game

**Comment by Soyweiser** [comment]
I just don't know what happens when a monster is loaded with an id that no longer exists. I'm assuming error message, and removal of monster from the savegame.

**Comment by pisskop** [comment]
No?  Theyre still there in another file.

**Comment by Soyweiser** [comment]
Ow, alright. Thought you had just removed the entire monster from the game. Damn, and I wanted to know how robust the current implementation was.

Still have to play with your additions btw. They look interesting, and deadly.

**Pull request merged**
