### PR TITLE
Cutting quality overhaul

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Balance "Cutting quality overhaul"

#### Purpose of change

This should make living off the land possible again. Or say, you just lost everything due to the nemesis destroying your house and setting it on fire. If you are in a forest, you should be able to work your way up again.

#52255, but done right.

#### Describe the solution

I basically asked myself "Can you do this with a sharp rock?" and if yes, it will be cutting quality 1. I tried to keep it restricted to the basics.
Look at things that stayed at cutting quality 1 to see what I have changed manually.
I tried to keep it realistic, but large blades are cutting quality 1 since they are not easy to handle. Try cutting bread with a glaive ([obligatory meme](https://i.kym-cdn.com/entries/icons/original/000/028/139/cover.jpg)).

| Changed thing | Explanation |
|---|---|
| All seeds | Vegetable matter tends to be soft. You can remove their seeds easily. |
| Corn kernels | It should be pretty easy to do that with a semi-sharp rock. |
| Sleeveless stuff made from fabric/rags | Can be cut easily. I intentionally did not add that to (faux) fur and leather or kevlar recipes. Lycra is also exempt.
| Soap flakes | You can even do that with your fingernails in real life. If you really want to. |
| Improvised shelter | Appears to just need a few basic cuts so that the sticks or pine boughs or whatever fit. |
| Fish bait | Preparing a very basic scrap of food should be possible. |
| Woodworking tools | They still have a sharp blade. You should not use an axe or even circular saw to cut your veggies but you can still do emergency survival tasks with it. |
| Cudgels and pointy sticks | Balance reasons. It is really hard to train fabrication without a proper cutting tool and those items are crucial in the early game. |
| Revert taped window | Cutting tape with e.g a sharp rock should still be doable |
| Tobacco pipe | This is basically a semi bugfix, but since it is relatively small you might as well just smash it to get splinters. |
| Shoulder strap | Just cutting a bit of rope so it fits got to be possible with primitive tools. |
| Cooked dandelions and burdocks | They are soft enough that you can cut them without any proper blade. |
| Machetes | I think they are easy enough to handle to keep cutting quality 2 |

I will also adjust recipes a bit so you can train fabrication more easily until you can make a stone chopper (Requires fabrication and survival 2, survival 2 can be achieved with just foraging).

#### Describe alternatives you've considered

There is #52255, but this alternative did not work out.

#### Testing

I did extensive playtesting (see comment below).

**For any reviewers: The diff is large and potentially misleading because I basically did regex replacing of all CUT 1 with CUT 2, you should look at what did not change, as in everything with CUT 1, instead.**

I manually reviewed the changes and took some extra care in inspecting e.g tools and blades.

#### Additional context

n/a

### CODE REVIEW

**Comment by a-chancey** [comment]
I've been working on #53366 and just saw your PR today. Got a little panicked because we were discussing using Cut 2 for certain fabrics (Kevlar, nomex, synthetic fabric), but a machete wouldn't work for those (based on your PR examples). 

However, the general consensus seems to be that *both* ideas are valid - there should be differences between sharp rocks and a knife, and adding a third level to cut just for a few specific fabrics really didn't make sense. Similarly, a sharp rock would be suitable for cutting up clothes to rags and parts, but you're going to have a hard time using it to cut fabric in a manner that it would be suitable for making a t-shirt. 

So the solution we came up with is that I'm going to add a new FABRIC_CUT quality, and I will be holding off on my PR for the Kevlar shears until that is complete, as they'll get the new quality. 

Just wanted to make you aware that a new type of cut quality is coming - but I'm going to handle auditing the tailoring tools when I get the new quality added.

Additionally, I'm planning on documenting tool qualities soon, so we have a rough baseline moving forward, and will likely be pulling some quotes from your PR here when documenting cut.

**Comment by NetSysFire** [comment]
This is reasonable, but I also thought about adding CUT 3. E.g a butcher knife is better than a pocket knife. But adding a new quality and limiting it to specific types of fabric should be good, too.

**Comment by NetSysFire** [comment]
I have been playtesting this a bit and so far and I am satisfied. It is possible to start with literally nothing and work your way up again, making survival in the wilderness a bit more feasible again:

1. You usually start by smashing rocks for a fire ring. This gets you flint stones which have CUT 1. Alternatively, a bone shiv, you just need a stone and a bone, but these tend to be difficult to find, also works.
2. One of the first things you craft is e.g a cudgel or a (long) pointy stick, this can easily get your fabrication up to 1.
3. Just foraging for food and materials can also get your survival up to 2, but a few recipes can speed this up, e.g a digging stick or some throwing sticks. Also creating an improvised shelter is basically a must, which also levels this.
4. The real challenge is now getting fabrication up to 2. Since you need to do tailoring for survival anyways, a frame loom and shed stick will also help level fabrication. There is also the survival bow, bows are important in wilderness survival and will level fabrication quite a bit. You currently can't just craft crude wooden arrows due to them being in a recipe book, but I plan to change this separately since this is only semi-relevant here.
5. You should now have fabrication and survival 2 and can make a stone chopper, which has CUT 2.

This way you are getting essential tools while grinding skills for the stone chopper and it still looks realistic enough™.

**Comment by I-am-Erk** [comment]
Prior to this did we have any use for CUT2?

as long as we did not, I am pretty OK with everything you've done here.

**Review by I-am-Erk — APPROVED** [review]
Prior to this did we have any use for CUT2?

as long as we did not, I am pretty OK with everything you've done here.

**Comment by NetSysFire** [comment]
No, we only had CUT 1. Magiclysm had CUT 2 though:

https://github.com/CleverRaven/Cataclysm-DDA/blob/63e7be66567e97114cfd61193fafb5579a9ffe23/data/mods/Magiclysm/recipes/weapons.json#L108-L117

This is the only mention of CUT 2 at all before my changes and they might be a typo. I nerfed the sharpened bone to be CUT 1 so it can only be used for basic survival tasks, especially because of:

https://github.com/CleverRaven/Cataclysm-DDA/commit/63e7be66567e97114cfd61193fafb5579a9ffe23#diff-23f0a875ae22999f584d6ff319c82791f4bac39eb558d8ad67778071905b50d1L38

**Comment by I-am-Erk** [comment]
Something seems to be breaking the faction camp calculations. It makes sense that this might do that but I don't know anything about those tests. Perhaps @PatrikLundell could help

**Comment by NetSysFire** [comment]
Yes, I modified this file:

https://github.com/CleverRaven/Cataclysm-DDA/pull/53385/files#diff-eb20aa0e7edf13a17078a7745fa6ce0de46d624949e6caca2d484aadf1eadd87

I don't know what else to change for the test to work again, but I will inspect the logs a bit.

**Comment by NetSysFire** [comment]
I just found something interesting, it just specified CUT without any level to it, so I assume it means 1. I specified level 2, and I hope it will work now.

**Comment by NetSysFire** [comment]
Argh, I will do the json linting later. I do hope the other tests will run though.

**Comment by PatrikLundell** [comment]
I know nothing about the tests, including where they are located.

It can be a version of the issues #53431 is encountering.

The first thing I'd try to do is modernize some of the afflicted base camp recipes to remove the explicit statement of requirements to let the code figure them out. If that removes the failures for the tested recipes that's probably the way forward. I don't WHY there would be a conflict, although I guess that specifying explicit requirements for a recipe but have those not match the requirements calculated and not providing an override flag (which I think I've seen in some places) might make the logic grumpy. Thus, updating the construction recipe but not all of the things it did construct (e.g. the wall tile, but not the window one) might cause the requirements to become more complex.
Another thing to check is to verify that the code does consider CUT 2 to also satisfy requirements for CUT 1 in cases where some tiles require one and some the other.

It can be noted that modernization of the base camp recipes is a good thing anyway, but it's a fair bit of work to test, and so will take a fair bit of time to chug through (and it's boring and thus error prone, so unless you have an iron focus control you don't want to push it).

**Comment by NetSysFire** [comment]
>The first thing I'd try to do is modernize some of the afflicted base camp recipes to remove the explicit statement of requirements to let the code figure them out.

This means removing `blueprints_needs`, rights? If the code can figure it out automagically, why do we do it manually at all?

**Comment by PatrikLundell** [comment]
Yes, it's getting rid of unnecessary blueprint needs, and their associated times and proficiencies.

The reason the the JSON files are the way they are is presumably because they were written when the code couldn't figure it out (or were written with such definitions as the template).
There is also the case where you explicitly want to bypass the automatic materials/time/proficiency deduction because it doesn't cover all you actually intend it to do. I believe that's flagged with '"check_blueprint_needs": false'. 
One set  of situations where that's the case are all the initial surveys, where surveying presumably takes some time, and the erection of a bulletin board without the use of materials, presumably so you can start a base camp without having to first get the materials for a board.
Another set of situations is where you want to simulate tearing something down, which construction recipes can't do (such cases can be found in the fire station base camp).

It can be noted that there are "components" sections that appear outside of "blueprint_needs", and those should NOT be removed, as they typically represent placeables that the blueprint assigns (e.g. some pots and pans for a kitchen, tools for a workspace, etc.).

It's a fairly large effort to go through, change, and, in particular, test these base construction recipes, which means it will take time and several PRs, so there's a need for some coordination so people aren't doing the same thing.
I can do the field base camps and expansions given enough time, and probably the others eventually, but the time it takes depends on how complete the testing needs to be.
However, it should be stressed that I don't know if that's the actual issue here, or if it's something else and these recipe failures are just symptoms.
Again, if we should do this the task needs some coordination or we're going to end up with a jumble of PRs doing the same time and "conflicting" with each others.

**Comment by NetSysFire** [comment]
If we do not know what the real issue is, wouldn't it make more sense to just accept this and do the basecamp fixing stuff in another PR since this is getting a bit out of scope here? Assuming the test which is currently running fails

**Comment by PatrikLundell** [comment]
If this PR is dependent on changes to base camps this PR will have to be put on hold until all the PRs that perform those changes have been approved and merged. I don't think it's reasonable to try to cram all that into this PR.

**Comment by NetSysFire** [comment]
Wow, good news. The latest commit actually seemed to have solved the problem. There is still one tiny bit remaining which should be trivial to fix (hopefully):

```
D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\recipe_test.cpp(65): FAILED:
  CHECK( reqs_to_json_string( stove_1->simple_requirements() ) == R"({"tools":[],"qualities":[[{"id":"CUT"}],[{"id":"SAW_M"}]],)" R"("components":[[["pipe",2],["scrap",1]],[["metal_tank",1]],[["pipe",1]]]})" )
with expansion:
  "{"tools":[],"qualities":[[{"id":"CUT","level":2}],[{"id":"SAW_M"}]],
  "components":[[["pipe",2],["scrap",1]],[["metal_tank",1]],[["pipe",1]]]}"
  ==
  "{"tools":[],"qualities":[[{"id":"CUT"}],[{"id":"SAW_M"}]],"components":[[
  ["pipe",2],["scrap",1]],[["metal_tank",1]],[["pipe",1]]]}"

D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\recipe_test.cpp(70): FAILED:
  CHECK( reqs_to_json_string( stove_3->simple_requirements() ) == R"({"tools":[],"qualities":[[{"id":"CUT"}]],"components":[[["pipe",2],["scrap",1]]]})" )
with expansion:
  "{"tools":[],"qualities":[[{"id":"CUT","level":2}]],"components":[[["pipe",2]
  ,["scrap",1]]]}"
  ==
  "{"tools":[],"qualities":[[{"id":"CUT"}]],"components":[[["pipe",2],["scrap",
  1]]]}"
with message:
  reqs_to_json_string( stove_2->simple_requirements() ) := "{"tools":[],
  "qualities":[[{"id":"CUT","level":2}],[{"id":"SAW_M"}]],"components":[[
  ["pipe",2],["scrap",1]],[["metal_tank",1]],[["pipe",1]]]}"
```

Also potentially:

```

D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\iteminfo_test.cpp(2361): FAILED:
  CHECK( item_info_str( iron, disassemble ) == "--\n" "<color_c_white>Disassembly</color> takes about 20 minutes, requires 1 tool" " with <color_c_cyan>cutting of 1</color> or more and 1 tool with" " <color_c_cyan>screw driving of 1</color> or more and <color_c_white>might" " yield</color>: 2 electronic scraps, 1 copper, 1 scrap metal, and 5 copper" " wire.\n" )
```

I really, *really* hope this would be it because putting this PR on hold means lots of merge conflicts later due to 108 changed files.

**Comment by Maleclypse** [comment]
The more the game has to figure out basecamp costs the slower the game loads. Individually not a problem. Collectively it can add up. Not a request for change just for info.

**Pull request merged**
