### PR TITLE
Add several comment commands for issues and PRs

### PR DESCRIPTION
**Pull request by Bobtron**
#### Summary
Infrastructure "Add more comment-commands which apply labels to issues and PRs"

#### Purpose of change
Expand list of labels that can be added with comment commands

#### Describe alternatives you've considered
Add more comment commands to this pr, or remove some added in this pr

#### Testing
Enabled github-actions on my fork of cdda, and tested these commands on issues and prs there

### CODE REVIEW

**Comment by casswedson** [comment]
I didn't want to implement actually closing issues, since stalebot will get to all issues eventually - and in this case _I_ think the limitations are ok, I wouldn't want to hand the permission to close issues to anyone; just slapping a label like "need more info" "needs testing" would be useful

the real tools for helping the organization should be kept behind the member status; Kevin and the other members, take care of filtering the candidates

**Comment by Bobtron** [comment]
> I didn't want to implement actually closing issues, since stalebot will get to all issues eventually - and in this case _I_ think the limitations are ok, I wouldn't want to hand the permission to close issues to anyone; just slapping a label like "need more info" "needs testing" would be useful
> 
> the real tools for helping the organization should be kept behind the member status; Kevin and the other members, take care of filtering the candidates

Good point on the closing issues - I think I'll remove the closing issues command for duplicate + invalid, the issue owner, stalebot, or mods can decide to close it. I checked the [labels](https://github.com/CleverRaven/Cataclysm-DDA/issues/labels) list, doesn't look like theres any 'needs testing' label, otherwise we could add that to the commands, not sure how to make it accessable to all users though, not just the vetted ones.

**Comment by Karol1223** [comment]
I mean, "needs testing" is basically the "unconfirmed" label that gets slapped onto all bug reports at the start anyway, no? Unless we're talking "I could not reproduce it so could someone else try testing this out"

**Comment by Bobtron** [comment]
> I mean, "needs testing" is basically the "unconfirmed" label that gets slapped onto all bug reports at the start anyway, no? Unless we're talking "I could not reproduce it so could someone else try testing this out"

Yeah, was thinking the latter for this one, could also be for PRs which are large enough to need manual testing to make sure nothings broken

**Comment by Maleclypse** [comment]
I'm confused it looks like the closing commands are still in the top file?

**Comment by casswedson** [comment]
closing issues was removed, but we can still label them with invalid, duplicate etc

**Pull request merged**
