### PR TITLE
COMPILING.md: Add OpenBSD with clang

### PR DESCRIPTION
**Pull request by NicanorB**
#### Summary
None

#### Testing
Successfully compiled tiles using this guide.

### CODE REVIEW

**Comment by BouncyMaster** [comment]
Don't merge yet as I still have some problems compiling

**Comment by BouncyMaster** [comment]
The makefile needs to be modified in order to compile, will open a PR

**Comment by BouncyMaster** [comment]
Upon further testing I found that we only get a warning with these build options, not an error, so this can be merged.

**Review by BrettDong — APPROVED** [review]

**Comment by BouncyMaster** [comment]
> Upon further testing I found that we only get a warning with these build options, not an error, so this can be merged.

Turns out we do still get an error when building, it can be fixed by merging this PR: #60208

**Pull request merged**
