### PR TITLE
Martial Arts Rebalance for Sōjutsu

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Sōjutsu"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Sōjutsu

#### Describe the solution

`Sōjutsu, "The Way of the Spear", is the Japanese martial art of fighting with a spear.  Sōjutsu focuses on keeping opponents at a distance in order to maintain advantage in combat.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Sōjutsu Stance|Unarmed 0|Static Buff|+1 Blocks
Sōjutsu Rush|Unarmed 0|OnMove Buff|-1 Blocks, +10% Cut and Stab damage
Push|Melee 1|Melee Block Counter|-50% Bash, Cut, and Stab damage, Knockback distance: 1
Trip|Melee 2|Melee Tech|Down duration: 2
Skewer|Melee 4|Melee Crit Tech|0% Bash damage, +50% Cut and Stab damage, Stun duration: 2, Knockback distance: 1

**Weapons:** Copper Spear, Forked Spear, Glaive, Halberd*, Homemade Halfpike, Knife Spear, Makeshift Glaive, Naginata*, Pike*, Pipe Spear, Pitchfork, Qiang, Simple Knife Spear, Sharpened Rebar, Spike on a Stick, Steel Spear, Survivor Naginata, Wooden Spear
*Includes all variations. 

Sōjutsu is pretty good defensive style. It relies on reach attacks for damage while giving player ways to keep opponents at a distance.

_Problems and issues_
- **Skewer doesn't make sense for the style.**
The Skewer was meant to force the opponent away from the player with a strong attack but it only works on a critical hit and giving bonus damage at close range goes against the way spears are meant to be used in CDDA.

- **Sōjutsu doesn't support bash damage.**
Granted, bash damage isn't something a spear normally does but it is completely possible to use Sōjutsu techniques with a pole that is spear-length.

_Rebalance Goal_
Sōjutsu was my first major contribution to CCDA (#27535) and it's nice to get a chance to give another pass to the style I made a long time ago. I think Sōjutsu does it's job of being a defensive style pretty well. I want to replace Skewer with something more defensive and do some other minor adjustments.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Sōjutsu Stance|Melee 0|Static Buff|+1 block attempts
Sōjutsu Positioning|Melee 0|OnMove Buff|-1 block attempts, +10% damage. Lasts 1 turn.
Push|Melee 1|Melee Block Counter|-50% damage, knockback distance: 1
Shove|Melee 2|Melee Tech|-50% damage, knockback distance: 1
Trip|Melee 3|Melee Tech|-50% damage, down duration: 1

**Weapons:** Copper Spear, Dory, Forked Spear, Glaive, Halberd*, Homemade Halfpike, Ji, Knife Spear, Long Pole, Makeshift Glaive, Naginata*, Pike*, Pipe Spear, Pitchfork, Qiang, Simple Knife Spear, Sharpened Rebar, Spike on a Stick, Steel Spear, Survivor Naginata, Wooden Spear
*Includes all variations.

_Important Changes_
- **Replaced Skewer technique with Shove technique.**
As mentioned above Skewer doesn't make sense in a mostly defensive style. I've replaced Skewer with Shove, which is a normal technique that knocks an opponent back. For those sad at the lose of Skewer, remember that since Sōjutsu no longer has a crit technique, the player will use the crit technique of their weapon (if any) instead.

- **Sōjutsu OnMove Buff damaged now effects all types of damage.**
This buff has been updated to affect all types of damage.

_Advantages_
- Sōjutsu Positioning improve damage as you move and reach attack opponents.
- The styles techniques work to keep other opponents away.

_Disadvantages_
- Reach attacks are the only way you can do any real damage.
- The style can handle small groups but only if you stand still.
- Fast enemies might be able to move close to you after a Shove or recover from Trip quicker than normal.

#### Describe alternatives you've considered

_If the style is too strong..._
- Remove the damage buff from Sōjutsu Positioning.

_If the style is too weak..._
- Increase the Down duration on Trip to 2 turns.
- Increase the duration of Sōjutsu Positioning to 2 turns.
- Increase the damage on Sōjutsu Positioning from 10% to 15%.

#### Additional context

_References:_
[Sōjutsu wikipedia page](https://en.wikipedia.org/wiki/S%C5%8Djutsu)
[Samurai Spear Fighting in Armor - Sōjutsu 槍術](https://www.youtube.com/watch?v=nHnQEfHLr2U)
[Japanese Spear Fighting: Sōjutsu](https://www.youtube.com/watch?v=ladijQstbU4)

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
1. How long is Sojutsu Positioning
2. Learning techniques end at only 3 when the non-Brawling ones end at 5? 😕

**Comment by Hymore246** [comment]
> 
> 
>     1. How long is Sojutsu Positioning's duration?
> 
>     2. Learning techniques ends at only 3 when the non-Brawling ones end at 5? 😕

1. 1 turn. I added that in.
2. Sojutsu leans very heavily on reach attacks which are already really strong. Any sort of normal offensive technique or even a counter would be too much. Not to mention that reach attacks can't trigger buffs like OnHit or OnCrit As a result, Sojutsu ends up looking a light on content. . If people feel like the style is still lacking, I will try to come up with something to fill the gaps.

**Comment by tenmillimaster** [comment]
I have a suggestion, though it may not be one you like.  Make sojutsu learnable through manuals only, not a valid option through character creation.  Sojutsu's wiki article notes that it is a rare discipline, and that there are few school's left globally.

I did a cursory search for dojo's in the states, but couldn't find much.

Raiding libraries, culture centers, households etc for this stuff would be kind of cool. Imagine finding a sojutsu manual in the D&D basement!

**Comment by Hymore246** [comment]
> 
> 
> I have a suggestion, though it may not be one you like. Make sojutsu learnable through manuals only, not a valid option through character creation. Sojutsu's wiki article notes that it is a rare discipline, and that there are few school's left globally.
> 
> I did a cursory search for dojo's in the states, but couldn't find much.
> 
> Raiding libraries, culture centers, households etc for this stuff would be kind of cool. Imagine finding a sojutsu manual in the D&D basement!

Sojutsu might be similar to Medieval Swordsmanship. Learned from very old manuals but has an active community trying to keep the style alive. I don't think Medieval Swordsmanship has traditional dojos either.

**Comment by tenmillimaster** [comment]
> Sojutsu might be similar to Medieval Swordsmanship. Learned from very old manuals but has an active community trying to keep the style alive. I don't think Medieval Swordsmanship has traditional dojos either.

Could you point to any such forums? I'm not able to find anything like this. HEMA, otoh, definitely has a very active community and there are several schools.

I've found a handful of dojos, West LA Dojo and Capital Katori (in California and D.C respectively), GiYu Dojo in Atlanta, Budo in Toronto, and Ottawa Aikikai Dojo in Ottawa,  so I suppose the survivor being the someone who studied those weapons specifically at those schools, then moved to NE, is a possibility. A bit of a stretch IMO, but whatever.

**Comment by Hymore246** [comment]
> 
> 
> > Sojutsu might be similar to Medieval Swordsmanship. Learned from very old manuals but has an active community trying to keep the style alive. I don't think Medieval Swordsmanship has traditional dojos either.
> 
> Could you point to any such forums? I'm not able to find anything like this. HEMA, otoh, definitely has a very active community and there are several schools.
> 
> I've found a handful of dojos, West LA Dojo and Capital Katori (in California and D.C respectively), GiYu Dojo in Atlanta, Budo in Toronto, and Ottawa Aikikai Dojo in Ottawa, so I suppose the survivor being the someone who studied those weapons specifically at those schools, then moved to NE, is a possibility. A bit of a stretch IMO, but whatever.

I was under the impression that Medieval Swordsmanship was derived from HEMA to some extent. I used http://www.learn-sword-fighting.com/ as a reference. I'm not sure if they are a community but they have a bunch of video demonstrations.

That said, you don't need a dojo to learn these styles. You just need to practice fighting with them. The trait description for Melee Weapon Training is ambiguous about how you learned:
```
You have practiced fighting with weapons.  You start with your choice of Eskrima, Fencing, Fior Di Battaglia,  Medieval Swordsmanship, Niten Ichi-Ryu, Pentjak Silat, or Sōjutsu.
```

**Comment by Hymore246** [comment]
Stupid close button. Sorry about that.

**Pull request merged**
