### PR TITLE
Drinking hats

### PR DESCRIPTION
**Pull request by Tsunder**
#### Summary
Summary: Content "mainlines the Drinking Hats mod, adds craftable drinking hats."

#### Purpose of change
For fun, and for the lazy quaffables inebriated engineer.

#### Additional context
The drinking variants of the equipment should be functionally similar to the base hat.
Most are literally just 2 aluminum cans (or equivalent) taped to a hat, while some are a bit bulkier.
Looks like some existing recipes got caught by auto-linter.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
I recommend to add to drinking heavy power armor helmet [ "HAMMER", 1 ] quality. 

Realistically drinking  power armor drinking helmet can be aslo good replacement for hammer.

**Comment by Rail-Runner** [comment]
Uh, maybe to avoid creating lots of "drinking helmets" of all kinds, it'd be best to make it a separate piece of headgear which can be worn over any helmet or even bare head (much like headlamp item)?

**Comment by Vasyan2006** [comment]
This PR is incomplete, because a lot of items like duster or socks dont get drinking options.
And it will be nice to add XL version of every item for mutants, with gallon jugs instead of plastic bottles.

**Comment by Night-Pryanik** [comment]
I don't like the idea of this addition, and I'm strongly against adding it into the game. But that's only me, can't tell for others.

Aside from personal opinions, please remove linting changes as they don't relate to this PR.

**Comment by SomeDeadGuy** [comment]
drinking hats: exist in the reality the game is based on
hardcore cata playas: REEEEEEE

**Comment by Firestorm01X2** [comment]
@Night-Pryanik 
>I don't like the idea of this addition, and I'm strongly against adding it into the game. But that's only me, can't tell for others.
Aside from personal opinions, please remove linting changes as they don't relate to this PR.

It is 1st April days joke. Obviously.
Right?

**Comment by Little-119** [comment]
1. Acquire baseball bat
2. Acquire baseball helmet
3. Create drinking baseball helmet
4. Acquire atomic coffee maker
5. Create atomic coffee
6. ???
7. Roleplay as Scout Tf2

**Comment by Vasyan2006** [comment]
Craft a hat with build-in atomic coffee maker.
Infinite speed bonus.

**Comment by Fris0uman** [comment]
One drinking hat that can be strapped on other hats is actually a pretty good idea. Since head encumbrance doesn't do anything I'm sure plenty of player that are using flasks would swap for the drinking hat since it's penalty free.
Also I don't think that silly/useless item are banned from the game, it always had a bit of flavor to the thing.

**Comment by Ilysen** [comment]
I cannot understand for the life of me why people are so up in arms about a *drinking hat* when almost nobody complained about the addition of a dakimakura. It's both funny and fits the mechanics of the game.

**Comment by Fris0uman** [comment]
Well the current implementation with a new item per type of hat is quite terrible. I thinks that's the main problem here.

**Comment by Tsunder** [comment]
> Apparently it was not April's fool joke. 

I'm glad a lot of people got a kick out of the PR :)

FWIW, the original mod was made like [one and a half years ago](https://discourse.cataclysmdda.org/t/drinkings-hats-mod/14352). so this was just a quick and dirty port. 

> 1. Current solution in curreunt form will not be accepted in current form because it is lack of extensibility. With new added hat there should be new drinkable duplicate this way. It is wrong way of doing things.
>    Not mention the fact that you are not using `"copy-from"` tag that copies data from other json items and allows to get somewhing like inheritance.

When originally made, I think there were some problems caused by using copy-from, due to the implementation being containers that had item data, rather than armor that had container-ability

> 2. Proper way of doing this PR is impelent ONE new item than can be wear on head and can be uses for drinking.
> a new item per type of hat is quite terrible
> One drinking hat that can be strapped on other hats is actually a pretty good idea

Agreed. It looks like there have been some changes to the clothing system, so perhaps someone can redo this better. (i.e., outer + oversize tags/one equip limit)

I have no particular expections of this going either way.

**Comment by kevingranade** [comment]
If you are not a maintainer, do not tell people their contributions will not be accepted. It doesn't matter if you are right or not, its rude and you are overstepping.
I have zero problems with the idea, so if you object to it on principle, too bad.
Haven't had a chance to review the code yet.

**Comment by ZhilkinSerg** [comment]
Marking as Stalled to clean up PR queue. Ping me to reopen this when you feel ready to continue working on it.

**Comment by Tsunder** [comment]
I feel ready to continue working on it. @ZhilkinSerg

**Comment by ZhilkinSerg** [comment]
Please check recipe results - you probably used invalid item ids:

image

image

image

image

image

image

image

image

**Comment by Rail-Runner** [comment]
Either way that's too much separate items and recipes in my opinion; better just make it one item which can fit over any other helmet (or bare head, if needed).

**Comment by ZhilkinSerg** [comment]
Any progress in resolving conflicts and fixing issue I [reported](https://github.com/CleverRaven/Cataclysm-DDA/pull/29191#issuecomment-495675892) earlier?

**Comment by Firestorm01X2** [comment]
> Any progress in resolving conflicts and fixing issue I [reported](https://github.com/CleverRaven/Cataclysm-DDA/pull/29191#issuecomment-495675892) earlier?

Main issue is this, as reported by @Rail-Runner :

> Either way that's too much separate items and recipes in my opinion; better just make it one item which can fit over any other helmet (or bare head, if needed).

Probably it is better to ask contributor directly fix in that way- single item. I mean it is very unlikely that PR will be merged in its original state. 

Let's face it - current implementation is ... frightening. After that need new recipe tab will be needed for drinking hats.

**Comment by Rail-Runner** [comment]
If this gets closed, I think I'll recycle this to make just one drinking hat item.

**Comment by Firestorm01X2** [comment]
> If this gets closed, I think I'll recycle this to make just one drinking hat item.

I recommend to close it yourself. You have access to close button. After that you can create new PR thos single item that is likely will be approved and accepted, beacuse idea itselft is ok.

**Comment by ZhilkinSerg** [comment]
> You have access to close button.

They don't.

**Comment by ZhilkinSerg** [comment]
> 
> 
> If this gets closed, I think I'll recycle this to make just one drinking hat item.

Okay, make one :)

**Pull request closed without merging**
