### PR TITLE
allow allergens to be inherited

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
Infrastructure "change allergens to be more json-based, using material ids instead of flags on items."

#### Purpose of change
the main purpose is actually to allow allergens to be inherited, and the ability to use regular recipes to just use materials that you are not allergic to to create foods you can eat, without making double items and double recipes.

#### Describe the solution
the first part is changing the function that looks at your allergies, making it check materials. then, i had to backtrack to materials and add a morale_type id to materials. then, i needed to add enchantments (since i used the enchantment system for allergies) to the traits that matched the tuples that were originally coded.

#### Testing
spawn some things that you're allergic to, and make sure you're allergic.
then, spawn things you're not allergic to, that can be crafted into an item that nominally you would be allergic to if you spawned it in, and see if you're not allergic to it.

#### Additional context
there's probably some extra bits in here for something like wool allergies, but i didn't touch any of that.
see also #61405

### CODE REVIEW

**Comment by KorGgenT** [comment]
image
i'm running into this issue again. it seems like every time i come back after a while i get this, and i always forget how i fix it.

**Comment by anoobindisguise** [comment]
My characters sometimes had the antifruit and antiveggy traits but would make cookies out of rice and dehydrated fruit, or junkfood intolerant chars laundering sugar by making sweet water... so many loopholes will be fixed by this, love to see it!

**Comment by TiberianErin** [comment]
image
seems like this PR makes multiple of the item traits related to allergens obsolete, and therefore the errors are generated because of this

**Comment by TiberianErin** [comment]
image
This error is complaining because magic enchantments do not know what allergies are anymore.

**Pull request closed without merging**
