### PR TITLE
Add hard seltzer drink

### PR DESCRIPTION
**Pull request by AHolmen**
SUMMARY: Content "Hard seltzer"

Purpose of change:
Adds hard seltzer beverage to items, also it's respective spawn rate info.

Describe alternatives you've considered:

Additional context:

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
1. Please follow the PR formatting.
2. These need to be added to itemgroups to spawn.

**Comment by Maleclypse** [comment]
PR format took me a while to get right since once you've messed it up you have to go to open a new PR to look at what your options are. So it needs to look like this you can copy and paste what I type in below and add your text where appopriate

Summary
SUMMARY: Content  "Add Hard Seltzer"

Purpose of change
Adds hard seltzer to the items in the game

Describe the solution
Create an item, recipe, and itemgroup spawns.

Describe alternatives you've considered
None

Testing
Test to see if it spawns and works correctly

Additional context

**Comment by AHolmen** [comment]
> 
> 
> PR format took me a while to get right since once you've messed it up you have to go to open a new PR to look at what your options are. So it needs to look like this you can copy and paste what I type in below and add your text where appopriate
> 
> Summary
> SUMMARY: Content "Add Hard Seltzer"
> 
> Purpose of change
> Adds hard seltzer to the items in the game
> 
> Describe the solution
> Create an item, recipe, and itemgroup spawns.
> 
> Describe alternatives you've considered
> None
> 
> Testing
> Test to see if it spawns and works correctly
> 
> Additional context
> 
> Edit:
> Looks like you got this done while I was typing mine out.

thanks anyways. Just copied the PR from one of the others.

**Comment by AHolmen** [comment]
Requesting merging.

**Review by BrettDong — APPROVED** [review]

**Pull request merged**
