### PR TITLE
Vehicle water tanks fix/change/addition

### PR DESCRIPTION
**Pull request by Barhandar**
They seem to have been copied from fuel tanks with fuel type changed, with no regard to the 200x multiplier fuel tanks have to match the item count.

Sorry, no more 6000/650 volume small and little water tanks compared to 400 volume regular one.

Now with 100% more matching the actual item volume! Fuel tanks untouched. Side effect is that all RVs now will have 30 gallon barrels instead of metal tanks for water, but considering the only place I've _seen_ these in-game was the depths of a slime pit...

P.S. If I do make 30 gallon drums (metal) and switch current ones to 30gal_barrel (plastic) and it gets merged, disregard the "30 gallon barrel is plastic" commit because it will then be incorrect.

### CODE REVIEW

**Comment by KA101** [comment]
>They seem to have been copied from fuel tanks with fuel type changed, with no regard to the 200x multiplier fuel tanks have to match the item count.

Wouldn't surprise me.  Good catch, but I'm not doing C++ merging at this hour.

**Comment by Barhandar** [comment]
>Wouldn't surprise me. Good catch, but I'm not doing C++ merging at this hour.

There's nothing C++ here. 

"Multiplier" which compensates for charge-counting is in jsons. For example, gas tanks have 30000 "volume", which would be 150 units of gasoline, each unit being 200 charges.

**Comment by KA101** [comment]
Hence why I'm not doing merging that takes anything more than an eyeball check, and these would require actually loading up the game and installing one.

**Comment by Barhandar** [comment]
>Hence why I'm not doing merging that takes anything more than an eyeball check, and these would require actually loading up the game and installing one.

I can wait, no problem.

I've copied the changes onto a build, loaded, and my Luxury RV-turned-craftrig had 450 water. Removing water tank resulted in 30 gallon barrel of water. Emptying it, then reinstalling, resulted in water tank of 450 water. Filling it worked.

**Comment by narc0tiq** [comment]
I'll take this one -- I've got a few minutes to myself at work today.

**Pull request merged**
