### PR TITLE
Remove "Rapid strike" technique from knives

### PR DESCRIPTION
**Pull request by BalthazarArgall**
#### Summary
Balance "Remove rapid strike from knives"

#### Purpose of change
Knives have very low attack costs and the technique amplifies this property, giving some knives inflated DPS.

#### Describe the solution
I removed the technique from all weapons in the "knives" category.

#### Describe alternatives you've considered
Discuss if each knife individually justifies having the technique.

### CODE REVIEW

**Comment by oosyrag** [comment]
Justification: all the knife attacks are rapid to begin with.

The rapid strike technique could be reserved for a normally slow weapon that is utilized as fast as a knife like a katana maybe.

**Comment by KittyTac** [comment]
Finally a combat knife isn't gonna be on par with a sword.

**Comment by BalthazarArgall** [comment]
Help me, something is drying too fast. HEEELP.

**Comment by BalthazarArgall** [comment]
The failing tests are unrelated apparently, should be ready to merge.

**Comment by Maleclypse** [comment]
I am amazed this isn't breaking any dps tests but I think I see the point that knives with rapid strike are double counting their speed.

**Comment by andrewhr** [comment]
> Finally a combat knife isn't gonna be on par with a sword.

well, `knife_combat` (i.e. "National Guard bayonet") was missed from this PR so yeah, the above is still true 😅 

I wonder, there are bunch of decrements in damage aside the RAPID removal. From commits I assume this is to comply to existing DPS tests...  but should the fix be the other way around? New DPS expectations from this removal, so "old tests are wrong". Just a thought

**Comment by Maleclypse** [comment]
> > Finally a combat knife isn't gonna be on par with a sword.
> 
> well, `knife_combat` (i.e. "National Guard bayonet") was missed from this PR so yeah, the above is still true 😅
> 
> I wonder, there are bunch of decrements in damage aside the RAPID removal. From commits I assume this is to comply to existing DPS tests... but should the fix be the other way around? New DPS expectations from this removal, so "old tests are wrong". Just a thought

The dps tests are set based around the planned scale of damage by specific weapons. There's a document in the md's about how they were chosen

**Comment by BalthazarArgall** [comment]
Fuuuugg I missed the bayonet. 💀

**Comment by ProjectMithril** [comment]
Question, I noticed the switchblade still has the Rapid tag, was this done on purpose?

**Comment by BalthazarArgall** [comment]
> Question, I noticed the switchblade still has the Rapid tag, was this done on purpose?

Yes, switchblades are in the SHIV category of weapons. I deliberately targeted knives only because shivs may deserve the rapid tag.

**Pull request merged**
