### PR TITLE
TropiCata: Nether Fauna Part 1 "Alien Reef" (+ Molusks expansion for Vanilla CDDA)

### PR DESCRIPTION
**Pull request by Xaritscin**
#### Summary
Mods "adds new species of nether fauna"

#### Purpose of change

First part on a series of updates focused on nether creatures. Unlike the vanilla game i'd like to explore the idea of the portal storms and tears in reality opening doors to alien planets, bringing strange flora and fauna to the region instead of cosmic horrors. This first PR is all about flying aliens brought from some distant ocean world which the player can encounter living around a reef marked on overmap.

As an addititon to the content on the mod i have also done some expansions to the slugs from mainline CDDA. expanding them from just them to a whole mollusk file containing also snails and a few freshwater species i'd like to introduce via fishing/aquaculture.

This along with regular snails and slugs as forage drops that you can conserve in your base (no shelf life for now but are poisonous to consume raw) or prepare via cooking right away(its a 2 stages process like IRL but is a lightweight snack you can stock and carry).

#### Describe the solution

-added 3 new alien crustaceans
-added 15 new types of alien fishes ranging from tiny to huge
-added cnidarian and echinoderm meat  to mod with their own basic recipes
-added a new mollusk and gastropod meats to vanilla ingredients with their own processing and basic recipes
-added some new molusks to vanilla files including fishables (the fishery ones are not implemented ATM because i need to figure how to process them into food items)
-added 3 new cnidarians and 3 new echinoderms
-added a new alien reef location which spawns the mentioned sea creatures along with its own furniture/terrain (was gonna have a portal spawning the creatures but couldnt pull it out using spells)

#### Describe alternatives you've considered

leave the nether to just meme monsters and Lovecraft references.

#### Testing

Generated a new map, searched for a Portal Reef then checked on the species spawned by the location. traveled to a nearby house and started butchering some of the new creatures to get their meats and then did their basic cooking recipes. 

Tried to do some fishing to see if freswhater snails or mussels would drop but RNG didnt help me with that, technically it should drop them fine.

#### Additional context

I was originally planning to make this into a mainline PR but im not sure if this fits the theme for regular CDDA so im making only one part as mainline to do a minirework and expansion for slugs.

### CODE REVIEW

**Comment by Xaritscin** [comment]
opened but need to do testing before saying its ready

**Comment by Xaritscin** [comment]
added a new spell to use for spawning monsters via portal

**Comment by Xaritscin** [comment]
Portal didnt work, so im removing that part and leaving the rest open for merge review

**Comment by I-am-Erk** [comment]
These actually will probably fit quite well in vanilla. Keep an eye on what we're doing with portal storms and feel free to merge them over when the time is right.

**Comment by Xaritscin** [comment]
id rather see this merged right away and tackle the portal issues in a later update.

**Comment by cainiaowu** [comment]
What are these aeroctinus in simple English term?

**Pull request merged**
