### PR TITLE
Consistent and more accurate quench/stim levels for caffeinated products

### PR DESCRIPTION
**Pull request by geskeca**
#### Summary
Balance "Making the quench and stimulant levels for caffeinated products more consistent and accurate to real life"

#### Purpose of change
Caffeine is a diuretic (increases urine production) which leads to decreased hydration. Currently coffee and coffee related drinks have a quench value of +40.
Compared to sodas’ +18 and water’s +50, I think +40 is quite high I don’t think that coffee should give more hydration than soda, and in fact should be less hydrating than non-caffeinated sodas. 

Also, some of the stimulant values for these caffeinated products didn't seem to make sense with how they are in real life, such as energy cola giving the same stimulant value as an energy drink, and Irish coffee giving the same stimulant value as a cup of coffee when a depressant (whiskey) is mixed in that should at least somewhat counteract it.

Finally the description for green tea "Green tea has a lighter, fresher taste than black and is traditionally preferred in Asian cultures.", the "preferred in Asian cultures" is a pretty broad statement that isn’t the case beyond maybe Japan.

#### Describe the solution
I tried to balance the quench values to how much stimulant (caffeine) the item gives you

My changes:
Atomic energy drink +5 quench
Atomic coffee +6 quench
Energy drink 13 stim +14 quench (stimulant value same as coffee)
Coffee and sweetened coffee +14 quench
Coffee milk and sweetened coffee milk +16 quench
Irish coffee 9 stim +16 quench (stimulant value same as coffee milk/energy cola)
Energy cola +16 quench
Dark cola +17 quench
Black tea +18 quench
Green tea +20 quench
Caffeine pill -4 quench
Caffeinated gum -3 quench
Green tea has a lighter, fresher taste than black ~and is traditionally preferred in Asian cultures~.

#### Describe alternatives you've considered
For me, coffee actually consistently dehydrates me, so I would've thought that it should give negative quench in-game. But after reading a bunch of articles on caffeine it seems that I might be a more extreme case?

Also I'm not 100% sure if the quench value of dark cola should be 17, but it’s the only middle ground between non-caffeinated soda with a quench of 18, and lesser caffeinated and diluted drinks like energy cola and milk coffee with a quench of 16.

#### Testing
Double checked to see that the json code was correct in style and function, so it should work perfectly

#### Additional context
None

### CODE REVIEW

**Comment by GuardianDll** [comment]
Whats your sourse?

**Comment by Gotdamnmiracle** [comment]
I don't know if I really agree with this. 250-300 mg of caffeine is needed to have a mild diuretic effect in individuals with no tolerance (that's 2-3 cups of coffee, 5-8 cups of tea). Tolerance to caffeine (represented ingame with addiction) would cause none of the diuretic effect and likely hydrate to a similar degree to water, in cases where there is no sugar added.

source: https://pubmed.ncbi.nlm.nih.gov/19774754/

**Comment by Stone94** [comment]
I personally think the hydration values needs to be rethought, 250ml of coffee still provides 250ml maybe a little less of water, caffiene is a mild diuretic and the amounts in these beverages aren't enough to cause dehydration compared to the amount of fluid they provide.

Same goes for energy drinks and soda, most of these are approximately 89% water. 

Caffiene itself isn't dehydrating, and the diuretic effect isn't strong enough, and doesn't last long enough to make you dehydrated. Thirst and dehydration aren't the same thing, but one is a sign of the other.

I personally drink far more caffiene then is considered healthy and I am practically immune to the diuretic effect of these beverages, and I'm only dehydrated when I'm sipping on a can all day.

I believe the drinks should be treated the same way food has, there are plenty of other side effects that can come from consuming unhealthy beverages from insomnia, trouble concentrating among a plethora of others.

Alcohol on the other hand, is a much stronger diuretic and can quickly dehydrate you if your not keeping up with your fluid intake.

I would rather track amount of fluids drank vs the quench system but that would be off topic 

Sources:
https://www.everydayhealth.com/diet-nutrition/does-soda-count-as-fluid/

https://www.webmd.com/parenting/features/healthy-beverages

https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/568848

**Comment by fairyarmadillo** [comment]
I think OP might also be confusing the sensation of being dehydrated with actual dehydration. Many things can cause thirst and make your mucus membranes feel dry while you are actually perfectly hydrated, and eating sour foods can make you feel quenched when your body is low on water. Cataclysm only cares about actual dehydration, not how coffee makes you feel.

Furthermore, irish coffee doesn't need to be changed as stimulants already counteract depressants in the effects system. It should have the full alcoholic value of a shot of whiskey and the full stimulant value of a cup of coffee.

**Comment by geskeca** [comment]
> It seems to me like a reduced quench compared to higher hydrating drinks is fine- but not so low that it's next to negligible. For reference there are fruits and berries with about as much quench despite having vastly higher sugar content.

The lowest quench of the caffeinated drinks is +14 with the exception of atomic coffee which is _very_ caffeinated (~2.5x coffee), and atomic energy drink which is even _more_ caffeinated and likely loaded with sugar. I don't think +14 quench is that negligible.
All the berries I checked only seem to have a quench of around 3, less than any of the caffeinated drinks.
The only fruits that have a quench of +14 or higher are watermelon, grapefruit, and tomato, all of them being very juicy and the former 2 being quite sizeable.


> I personally drink far more caffiene then is considered healthy and I am practically immune to the diuretic effect of these beverages, and I'm only dehydrated when I'm sipping on a can all day.

> I don't know if I really agree with this. 250-300 mg of caffeine is needed to have a mild diuretic effect in individuals with no tolerance (that's 2-3 cups of coffee, 5-8 cups of tea). Tolerance to caffeine (represented ingame with addiction) would cause none of the diuretic effect and likely hydrate to a similar degree to water, in cases where there is no sugar added.

I agree with tolerance somewhat negating the diuretic effect, but I don't know how to apply something like that in-game tbh.


> Furthermore, irish coffee doesn't need to be changed as stimulants already partially counteract depressants in the effects system. It should have the full alcoholic value of a shot of whiskey and the full stimulant value of a cup of coffee.

When testing Irish coffee in-game I see the "you feel lightheaded" message but only see the effect of 13 stimulants and no depressants. A shot of whiskey on its own has 13 depressant value and coffee has 13 stimulant value so it seems like there's no counteraction at all.
A 9 stim value seems reasonable considering there's a lot of sugar in it as well

**Comment by Gotdamnmiracle** [comment]
I'd like to clarify in my comment I was not in agreement with the severe reduction in quench, but rather the concept of reducing quench as a way to represent a diuretic. The comparison to fruit is to say that if this is merged some drinks have the same quench as a handful of raspberries which is ridiculous.

Additionally- I would not say tolerance negates diuretic effects somewhat. The meta analysis linked states it fully negates this effect if tolerance is present. The NIH did all the work for us here.

If we want to go to this extreme to represent mild diuretics ingame then we should also begin noting the dehydrating effects of nearly all foods. Digestion and thus excretion cause a decent amount of water loss and high salt and sugar foods are far more represented in modern day foods than they ever were.

I am not in favor of this PR. Unrealistic.

**Comment by fairyarmadillo** [comment]
> > It seems to me like a reduced quench compared to higher hydrating drinks is fine- but not so low that it's next to negligible. For reference there are fruits and berries with about as much quench despite having vastly higher sugar content.
> 
> The lowest quench of the caffeinated drinks is +14 with the exception of atomic coffee which is _very_ caffeinated (~2.5x coffee), and atomic energy drink which is even _more_ caffeinated and likely loaded with sugar. I don't think +14 quench is that negligible. All the berries I checked only seem to have a quench of around 3, less than any of the caffeinated drinks. The only fruits that have a quench of +14 or higher are watermelon, grapefruit, and tomato, all of them being very juicy and the former 2 being quite sizeable.
> 
> > I personally drink far more caffiene then is considered healthy and I am practically immune to the diuretic effect of these beverages, and I'm only dehydrated when I'm sipping on a can all day.
> 
> > I don't know if I really agree with this. 250-300 mg of caffeine is needed to have a mild diuretic effect in individuals with no tolerance (that's 2-3 cups of coffee, 5-8 cups of tea). Tolerance to caffeine (represented ingame with addiction) would cause none of the diuretic effect and likely hydrate to a similar degree to water, in cases where there is no sugar added.
> 
> I agree with tolerance somewhat negating the diuretic effect, but I don't know how to apply something like that in-game tbh.
> 
> > Furthermore, irish coffee doesn't need to be changed as stimulants already partially counteract depressants in the effects system. It should have the full alcoholic value of a shot of whiskey and the full stimulant value of a cup of coffee.
> 
> When testing Irish coffee in-game I see the "you feel lightheaded" message but only see the effect of 13 stimulants and no depressants. A shot of whiskey on its own has 13 depressant value and coffee has 13 stimulant value so it seems like there's no counteraction at all. A 9 stim value seems reasonable considering there's a lot of sugar in it as well

Sugar is not a stimulant.

**Pull request closed without merging**
