### PR TITLE
Adds Saiga-12 magazines.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Updates Saiga-12.

Adds 10 round box and 30 round drum magazines, which spawn in the same
places as AK-74 magazines.

Also fixes it having a burst fire setting, despite being a
semi-automatic weapon.

### CODE REVIEW

**Comment by Darkyhard** [comment]
> Also fixes it having a burst fire setting, despite being a semi-automatic weapon.

As far as I know, burst fire of 2 was given to all semi-automatic shotguns at some point before, so that they would have an advantage over pump-action shotguns.

**Comment by mugling** [comment]
Reloadable box magazine now suffices for an advantage. Don't we already have a separate automatic shotgun?

**Comment by Darkyhard** [comment]
> Reloadable box magazine now suffices for an advantage. Don't we already have a separate automatic shotgun?

I meant that semi-automatic shotguns allow faster firing than pump-action shotguns. Isn't this supposed to be represented in some way?

**Comment by mugling** [comment]
Yes, we really need a `rate_of_fire` field but I'd prefer if we implemented that rather than implied `BURST`. You might want to follow the somewhat related discussion in #15129

**Comment by chaosvolt** [comment]
Glorious.

**Comment by kevingranade** [comment]
Yea, applying burst to non-automatic weapons is problematic.  It's a hack
to let double shotguns fire faster, but really that should be it's own
firing mode instead.

**Comment by chaosvolt** [comment]
Yeah, burst fire for non-fully-automatic firearms...I can see it making sense for gatling guns (which TECHNICALLY aren't full-auto) and coach guns of the dual-trigger type, where you can literally fire twice with one motion.

**Comment by shokolatOtobus** [comment]
Shouldn't the [Saiga-12 30 round drum](https://i.imgur.com/eDhY5PC.jpg) be flagged MAG_BULKY?

**Pull request merged**
