### PR TITLE
Update No Hope mod freshwater_research_station.json

### PR DESCRIPTION
**Pull request by RandDenner**
Adds in roof level from updated main CDDA map

#### Summary
Bugfixes "Adds roof fix from PR #51323 to No Hope mod"

#### Purpose of change
To avoid the same issues with automatic roof generation over down ladders as the main CDDA branch had.

#### Describe the solution
Adding in a map level for the roof.

#### Describe alternatives you've considered
None

#### Testing
Since the addition was tested in the master, there are no conceivable issues for the mod version. It was compared using NP++ and matched exactly.

#### Additional context
It would be helpful if the mod owner reviewed some oddities I found when reviewing their changed mod version of the file.

### CODE REVIEW

**Comment by RandDenner** [comment]
So, I notice there is a missing entry in level -3.
`"C": [ { "item": "tools_science", "chance": 20 }, { "item": "tools_common", "chance": 60 } ],`
But the ASCII characters are still present on the map.
Oversight?

**Comment by actual-nh** [comment]
"Bugfixes", not "Bugfix", for the PR summary BTW. (And yes, I know, the label is "Bugfix"; that makes it hard to remember, at least for me. The changelog puts the category as a header, so it's plural.)

**Comment by RandDenner** [comment]
> "Bugfixes", not "Bugfix", for the PR summary BTW. (And yes, I know, the label is "Bugfix"; that makes it hard to remember, at least for me. The changelog puts the category as a header, so it's plural.)

I actually knew that, and intended to, but my fingers apparently didn't. :P

**Comment by RandDenner** [comment]
Also, are the "lake" vehicles a new addition to the main version after the mod was created, or were they omitted on purpose?
(original on left, mod version on right)
image

**Comment by Night-Pryanik** [comment]
I'm not sure why mod's version doesn't have lake vehicles. Most probably it's from some older version. Could you please re-add them?
Also could you please decrease all ropes chance to spawn to 30%?
Also could you please remove that very strange `status: 3` from motor boat spawn definition?

**Comment by RandDenner** [comment]
> I'm not sure why mod's version doesn't have lake vehicles. Most probably it's from some older version. Could you please re-add them?
> Also could you please decrease all ropes chance to spawn to 30%?
> Also could you please remove that very strange `status: 3` from motor boat spawn definition?

Sure thing. If I notice anything else odd, I'll ask.

**Comment by RandDenner** [comment]
@Night-Pryanik
Adjustments made:
• vehicles added, all status 0
• spawns with higher chances than current base version lowered to base version
• added science equipment to lab level
• adjusted dresser line to match format of base for better comparison

**Comment by RandDenner** [comment]
Reverted dresser format as per linter revision

**Review by Night-Pryanik — APPROVED** [review]

**Pull request merged**
