### PR TITLE
Makeshift War Scythe And War Scythe

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
 ```SUMMARY: Content "Alternative recipe for war scythe"```

#### Purpose of change

In ordre to make a war scythe you need to make a scythe and then remove the blade and tape it again on the handle at a different angle. 
This PR offers a different approach : you start by forging a War Scythe and then you're done.
#### Describe the solution

Use id_suffix to add an alternive recipe that is copy-pasted from the scythe recipe.
#### Additional context

I thought of using toolset and material requirement for this recipe but the scythe recipe does not use them. By that I mean that it require forge 300 and oxy_torch 60 instead of the same amount for both that "forging_standard" uses, same with steel there is a ratio of 3 instead of 4 between lumps and chunks.

So I chose to let it be but if needed I could use this PR to bring both recipe to use "forging_standard" and "steel_standard".

### CODE REVIEW

**Comment by kevingranade** [comment]
Literally the only reason you would ever make a war scythe is if you need a
weapon and all you have is a scythe.  If building a war scythe from scratch
is a compelling thing to do instead of crafting some other pole arm, the
balance of the involved items and recipes needs to be revisited.

**Comment by Noctifer-de-Mortem** [comment]
There is also roleplay reasons. Player will take inferior weapons for themselves and their NPCs if it fits their playstyle/roleplay. Not everyone is going to go for the meta. Some want to use a warscythe over something better stat wise.

**Comment by Fris0uman** [comment]
>balance of the involved items and recipes needs to be revisited.

What do you mean ? That it should use forge and steel standards or that it should be easier ?

I literrally just thought "A war scythe looks cool, it's not that good a weapon but it would go well with the stylish trait of my character" and then it seemed stupid to modifie a scythe with ductape when I have everything I need to forge one.
So basically what Noctifer said. Forging is always a long process in the game and the war scythe doesn't seem very practical as a weapon so everything seems ok.
Now if the problem is clutter of the crafting interface we can just leave it as it is.

**Comment by kevingranade** [comment]
Its partially clutter, but mostly having a recipe to make one from scratch
sends a signal that this is a good idea, and that causes confusion because
it is most definitely not a good idea.

**Comment by Fris0uman** [comment]
But the Scythe can be made from scratch and it is an even worse weapon, a bad butchering tool and not wothe the effort for the cutting quality.

**Comment by int-ua** [comment]
IIRC, Scythe is one of two exclusive items that allow cutting grass. So there is a reason to craft it. Until someone writes a code for lawnmovers

**Comment by Fris0uman** [comment]
Ok, my bad. I thought that ability came from the cutting quality.

**Comment by I-am-Erk** [comment]
The other aspect of making scythes from scratch is that at some point they may serve a farming role.

Kevin is right, a war scythe is by nature an improvised weapon. A scratch made polearm would be better represented by something that's actually designed for use as a polearm - eg an awl pike or a naginata. You could look into adding a voulge or halberd to the game maybe?

**Comment by kevingranade** [comment]
More context on that grass cutting thing.  If we build out animal husbandry more, "cutting grass" turns into "harvesting grass", which is something you need to do to farm cattle intensively.

Also the war scythe probably IS pretty OP compared to what it should be, it should work pretty well a few times but be subject to either extreme dulling or breakage if used to attack something.

**Comment by I-am-Erk** [comment]
Maybe the current "war scythe" stats could be straight ported to a bladed polearm, and the war scythe be weakened? They're a time honoured peasant weapon, I wouldn't make them fragile

**Comment by kevingranade** [comment]
Ehhhh, wikipedia says we're [doing it wrong](https://en.wikipedia.org/wiki/War_scythe), my bad.

My previous assumption was that you can get a war scythe by simply reattaching the blade at a different angle, but it seems that would not result in what is called a war scythe.

As such, we have several options.
An improvised combat scythe weapon and recipe that IS just reattaching the blade at a more useful angle, but it would be FRAGILE_MELEE.
An actual war scythe item and recipe, which requires *reforging* the blade (or alternately crafting from scratch as a polearm), this would be a relatively robust polearm.

**Comment by Fris0uman** [comment]
Yes that's the conclusion I was coming to : current War Scythe becomes Makeshift War Scythe and gets fragile flag. (Wich might mean that we need to change the recipe to use a scythe blade, a long pole and duct tape so that it can be reassembled after breaking).
And if war scythe were a thing we (I) could add a recipe for a Forged War Scythe that would be the real deal with appropriate stats.
I just need to look at that wikipedia article.

**Comment by Photoloss** [comment]
Variety is fun and all but what *functionally* distinguishes the "proper" war scythe from a glaive, naginata or a survivor naginata? We don't even have the tech for reach-techniques and if you scroll down on that article Kevin linked that's a **loooong** list of polearms. A bash-only hammer or a bash-pierce hybrid would be far more interesting than yet another single-edged cutting blade. 

Reforging a scythe blade doesn't sound like a good idea either, agricultural scythes have very wide but thin blades which you'd have to squish down again, plus no guarantee a modern one would be made of anything near weapons-grade high-carbon steel. Some interesting videos on scythe weapons, though unfortunately lacking sources: [1](https://youtu.be/4rzQwzg5_mo), [2](https://youtu.be/_fujM6vvgF4?t=4m)

The martial arts worth considering are Sojutsu (currently a catch-all for reach weapons) and Medieval Swordsmanship which I believe is still relegated to the Medieval Stuff mod. Fencing is based on the martial progenitor to the olympic sport and focuses on one-handed swords with complex hilts.

**Comment by aoae23** [comment]
I mean, Nethack has a long list of polearms. Nothing wrong with CDDA having a lot of them as well.

**Comment by Fris0uman** [comment]
Well from here I see at least two optionss either tweaking the stats of makeshift and forged warscythe untl it makes sens for everyone so this PR would add a second version of a polearm that was already there.
Or just close the PR and go back to doing something else.

(Or just nerf the current war scythe into a makeshift war scythe but that seem a bit mean to nerf a weapon that is already bad and that is probably rarely used)

**Comment by Photoloss** [comment]
Numbers nerfs are Kevin's purview but the re-hafted agricultural scythe should definitely be made FRAGILE_MELEE regardless of any other changes. And **if** you add something representing a historical war scythe it should definitely have a reach attack: just compare the [scythemen](https://en.wikipedia.org/wiki/File:Polish_scythemen_1863.PNG) to [halberdiers](https://en.wikipedia.org/wiki/File:Halberdier-corps.jpg). And add the flags "NONCONDUCTIVE", "SHEATH_SPEAR" to both variants because those seem to be standard for wood-hafted polearms and definitely make sense for these blades as well.

**Pull request merged**
