### PR TITLE
Battery volume reduction

### PR DESCRIPTION
**Pull request by Xanmyral**
#### Summary

```SUMMARY: Balance "Update Battery Volume and Weight"```

#### Purpose of change

https://github.com/CleverRaven/Cataclysm-DDA/pull/37140
MP3 Player and Cellphone are smaller than their current batteries, which had a weird hammer space issue due to this. Batteries (specifically the light ones) were much larger than they should be and previously were comparable in size to steak knives and butchering knives. 

The larger batteries weren't as far off the mark as light batteries, but tweaked their numbers around existing batteries that seemed to fit the right mark. While the light batteries wound up smaller and lighter, the larger batteries generally were found to be too small and too light.

#### Describe the solution

- Compared Light Battery to 9 Volt and changed volume and weight to be near it
- Compared Medium Battery to 6 Volt Lantern and changed volume and weight to be near it
- Compared Heavy Battery to Large 6 Volt Lantern and changed volume and weight to be near it

#### Describe alternatives you've considered

Doing the other PR about the MP3 and Cellphone

#### Testing

Debug spawned all batteries changed, then spawned and killed zeds to ensure that items still spawned fine with batteries and didn't act strange.

#### Additional context

https://en.wikipedia.org/wiki/List_of_battery_sizes#Rectangular_batteries

I based the light battery after the 9v because it was able to fit in radios, flashlights, etc and was capable of powering quite large items for the qualifier light. Since we only use 1 battery per item to power things, instead of considering them AA or AAA (which frequently require several per item to power), I used 9v to be more reasonable.
https://www.amazon.com/AmazonBasics-Everyday-Alkaline-Batteries-8-Pack/dp/B0774D64LT/

Medium battery was originally based off of a power drill battery pack, which was similar size (if larger). Based it as the regular capacity as the battery pack I measured wasn't a particularly quality nor high capacity one. Compared with 6v Lantern Batteries as they were of similar size and used the weight there for consistency (as it is easy to see the scale up from 9v to 6v lantern and presumably these fancy omni-compatible batteries would look similar in style).
https://www.amazon.com/dp/B001J8J7GK/

Heavy battery I didn't really know what to base it off of, as I didn't find much results looking for batteries for the real life versions of the items listed that use heavy batteries in game. So I went with the even larger lantern batteries after a failed attempt to first use computer PSUs (which wound up of inordinate scale).
https://www.amazon.com/Rayovac-918-Lantern-Battery-Terminals/dp/B000BQUUCQ/

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Can't we instead use ultra-light batteries for mp3 players and cellphones?

**Comment by Inglonias** [comment]
Considering the power usage balance that occurred a while ago, I would be ok with restricting cellphones and mp3 players to ultralight batteries.

**Comment by Xanmyral** [comment]
If more people are wanting the change to cellphones and mp3 players I can shuffle back to the other PR, but I don't believe that resolves the oddness with light batteries nor gives some sort of standard to the battery sizes and weight. 

I was wanting to change batteries because, as presented, light batteries being larger than a steak knife struck me as very off from what I thought they were meant to represent (which is batteries that fit inside cellphones, mp3 players, flashlights, radios, etc). Currently they're fancy, fictional, rechargeable, omni-compatible batteries that don't seem to really have much of a basing, so this was an attempt to give them at least a reference to reality.

**Comment by Inglonias** [comment]
When I was implementing the battery overhaul, I decided that light batteries would be basically equivalen to smartphone batteries in size and usage. You're correct that the size of the batteries is a little off.

I don't have a smartphone battery handy with me right now to measure (besides the one locked away in my phone right now), but that's the sort of size and weight class I was thinking.

**Comment by Inglonias** [comment]
I did post my general notion of the sizes of batteries I was thinking in the initial battery overhaul PR, so that might give you another source of info.

#29651

**Comment by Inglonias** [comment]
A quick bit of research on replacement batteries for Samsung Galaxy phones (https://www.batterymart.com/c-samsung-galaxy-s6-edgep-cell-phone-battery.html) shows that their dimensions are 3.9" * 1.72" * 0.16". Converted to liters, that's in the ten to twenty milliliter range, so if a light battery is intended to be like that, yeah, 250mL is way too big.

**Comment by Xanmyral** [comment]
Smartphone batteries are a good comparison to light batteries, yeah. The one you posted would come out to 0.018L (bit smaller than a typical 9-volt, which comes out to 0.022L which I bumped up to 0.025L for it being a round number and my assumption that it being rechargeable and omni-compatible would equal out to a bit larger).

Looking over your overhaul, seems like we made pretty similar assumptions for the general equivalences of the battery types in terms of size.

**Pull request merged**
