### PR TITLE
Feature cryofacility start

### PR DESCRIPTION
**Pull request by Elgrosito**
#### Summary
Content "Added a new scenario involving a new mapgen building and a monster"

#### Purpose of change
Mostly for flavor/fun.

#### Describe the solution
All the additions are json:

A new building was added to mapgen: Cryogenic facility, where the player was placed in cryo stasis before the events of the cataclysm. Inspired by the game Neo Scavenger.

A new monster was added: Dogman, based on the cryptid from folklore.

A new scenario was added: Frozen in time, the player starts in the cryogenic facility, tired and cold.

#### Describe alternatives you've considered

Making a new json file for "cryptid" monsters.

#### Testing

Started the game in the scenario a few times and checked if items placement worked together with all the other additions.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
You _may_ make the character wear some sort of hospital gown on game start, to fully resemble NS start, especially since Naked and Afraid profession with no items whatsoever is a challenge by itself.

**Comment by Holli-Git** [comment]
This doesn't fit in with the vanilla game. Maybe something like No Hope or Aftershock?

**Comment by Astillia** [comment]
Love the reference, but Holli is right, it should probably be tagged over to one of the mods. Unless cryonics are one of the weird techs like exoskeletons that are still retained, its too high tech for the mundane earth.

**Comment by Fris0uman** [comment]
Definitly not fit for vanilla as is. Especially the dogman being literally dropped in from Neo scavenger with no alterations to fit dda

**Comment by WarBarista** [comment]
While not really fitting into the vanilla, i genuinely excited to play this in a form of a standalone modded scenario! (or it being added to Aftershock)

**Comment by Elgrosito** [comment]
> Love the reference, but Holli is right, it should probably be tagged over to one of the mods. Unless cryonics are one of the weird techs like exoskeletons that are still retained, its too high tech for the mundane earth.

I thought it was ok since there are already cryonically preserved people today. The tech exists somewhat. Also, in cdda there are cyborgs, autodocs, lasers, etc. Things that are common in sci-fi media, you can even start as a cyborg, so I didn't see a problem there.

**Comment by SariusSkelrets** [comment]
The current cryogenically-conserved people are frozen corpses that were frozen post-death.

Cryogenics on a living human in a way that allows to unfreeze them alive and without damaging their bodies has still yet to be done.

**Comment by Elgrosito** [comment]
> Definitly not fit for vanilla as is. Especially the dogman being literally dropped in from Neo scavenger with no alterations to fit dda

The doggyman is a creature from folklore though, with many encounters in New England. Initially I thought of making a PR about cryptids; the monsters that humans feared lived in the wilderness for millenia are  now becoming real in the cataclysm, but I thought it was too much and unrelated to the PR.

If I take out dogman, would that make the PR fitting then?

**Comment by Elgrosito** [comment]
> The current cryogenically-conserved people are frozen corpses that were frozen post-death.
> 
> Cryogenics on a living human in a way that allows to unfreeze them alive and without damaging their bodies has still yet to be done.

True, but my point was that the tech was consistant given the sci-fi levels that are currently in the game, like cyborgs and mutants and so on. It didn't seem far-fetched.

**Comment by SariusSkelrets** [comment]
Being able to implant bionics and knowing how to get a semi-controlled reaction from what allows mutation isn't the same as freezing people so they can be unfrozen alive and well later.

There's a reason why the FAQ describes arguments of type "we can go to the moon, where's my jetpack?" as best avoided. 

For example the Exodii, despite their massive cybernetic mastery, still use wetware computers as they lack the knowledge to improve on the design of regular computers and their computers are weaker than ours. The best they can make is using existing computer plans so their printers can make computer-like CBM parts.

**Comment by IdleSol** [comment]
*You were dying. Your last request was to freeze your body after you died. You paid enough to make sure you'd be unfrozen if they found a cure. And apparently it was the right decision. You can already hear the staff rushing over to welcome you to your new world.* 

If we need to justify any strange thing. Point to portal storms. No one knows what they are or what they're capable of. That means they're capable of anything.

**Comment by Karol1223** [comment]
> If we need to justify any strange thing. Point to portal storms. No one knows what they are or what they're capable of. That means they're capable of anything.

We do not use Portal Storms as 'we dont know how to justify something so blame it on this', because if we do this to justify everything then we just allow any bullshit in and nothing is special anymore. This is a nonstarter.

**Comment by Elgrosito** [comment]
> Being able to implant bionics and knowing how to get a semi-controlled reaction from what allows mutation isn't the same as freezing people so they can be unfrozen alive and well later.
> 
> There's a reason why the FAQ describes arguments of type "we can go to the moon, where's my jetpack?" as best avoided.
> 
> For example the Exodii, despite their massive cybernetic mastery, still use wetware computers as they lack the knowledge to improve on the design of regular computers and their computers are weaker than ours. The best they can make is using existing computer plans so their printers can make computer-like CBM parts.


I get that they're not the same, but both bionics that transform a human into a cyborg and mutagens that can transform the player into a werewolf are things that belong to the sci-fi realm. Cryonics might be tricky, but it doesn't feel THAT much wilder given the other tech in this game?

**Comment by Elgrosito** [comment]
> _You were dying. Your last request was to freeze your body after you died. You paid enough to make sure you'd be unfrozen if they found a cure. And apparently it was the right decision. You can already hear the staff rushing over to welcome you to your new world._
> 
> If we need to justify any strange thing. Point to portal storms. No one knows what they are or what they're capable of. That means they're capable of anything.

Beautifully written!

**Comment by Elgrosito** [comment]
> > If we need to justify any strange thing. Point to portal storms. No one knows what they are or what they're capable of. That means they're capable of anything.
> 
> We do not use Portal Storms as 'we dont know how to justify something so blame it on this', because if we do this to justify everything then we just allow any bullshit in and nothing is special anymore. This is a nonstarter.
> 
> Cryogenics do not fit in vanilla because the CDDA universe is technologically supposed to be mostly current year + 1, and stuff like CBMs is explicitly alien tech. The odds of including cryogenics as some form of underground government bullshittery similar to mutagen testing aren't zero, but they wouldn't be something you'd have people willingly wish to participate in, and imo that fits better as a failed testing unique location in the game than a starting scenario at that point.

However, history is filled with examples of governments and militaries pushing the boundaries of technology, often without the full consent or knowledge of the subjects involved. For instance, the US military conducted numerous experiments on soldiers, such as those related to chemical and biological warfare, without their full informed consent. See: Pyridostigmine bromide and Gulf War Syndrome.

Similarly, in the CDDA world, the government might have pursued cryogenic research, potentially on unwilling subjects, as a last-ditch effort and as a desperate attempt to preserve humanity or gain an edge in a post-apocalyptic conflict.

**Comment by SariusSkelrets** [comment]
> are things that belong to the sci-fi realm. 

I already said why this argument is flawed. Something being allowed doesn't allow something else, and the FAQ already adresses that. Your reason to add what you want to add must be better than "other weird stuff exist, so mine can exist too".

I second Karol for making it a findable failed experiment. The researchers tested many things, it's incredibly likely that some weren't ready for use yet. Labs already contain examples of that, like the mutants.

**Review by Karol1223 — CHANGES_REQUESTED** [review]
> Cryonics might be tricky, but it doesn't feel THAT much wilder given the other tech in this game?

What is in the game doesn't matter even remotely, your idea has to stand on its own feet. You're going to want to read the failed rationalizations section of the FAQ instead of arguing back and forth. You've been told several times, including by a lead dev (which isn't me, for the record), that this does not fit vanilla.

**Comment by RenechCDDA** [comment]
@Maleclypse @John-Candlebury @Drew4484 (Aftershock maintainers)

Is this something aftershock wants? Right now it's targeted at vanilla, but I figure it's better to ask before further work is put into it.

**Comment by Elgrosito** [comment]
> > are things that belong to the sci-fi realm.
> 
> I already said why this argument is flawed. Something being allowed doesn't allow something else, and the FAQ already adresses that. Your reason to add what you want to add must be better than "other weird stuff exist, so mine can exist too".
> 
> I second Karol for making it a findable failed experiment. The researchers tested many things, it's incredibly likely that some weren't ready for use yet. Labs already contain examples of that.

Oh but that is not what I meant. If I said that, it would be an "appeal to authority" non-argument. What I meant was that the level of technology in the CDDA world (current year +1), which allows for things like advanced bionics and mutagens, suggests a level of scientific advancement that wouldn't make cryonics entirely out of place. It wouldn't be a simple, readily available technology, but it's plausible that some secretive organizations or factions might have been working on it in the background. For example experimenting with soldiers to preserve humanity.

**Comment by IdleSol** [comment]
Okay, let's go in order.

1. Science employee psychosis.

Any employee of a laboratory related to cryogenics or portal research. Against the backdrop of all that happened, a little damaged in the head and considers himself unfrozen man. Will need to be finalized and appropriate hints, in the form of documents. (This is rather aimed at the player, whether he can put the picture together or remain lost in the initial description of the scenario).

2. Portal Storm.

I understand the reason you don't want to use it as an explanation. Bringing a frozen person back to life as a result of a portal storm is... unlikely. But we have many worlds that are at different stages of progress. And a lot of them have had cataclysmic events. This is Lore. A piece of an advanced world could have been sucked into ours. It could be a cryogenics lab from a world where they've learned to defrost.

(On this idea, a whole mod could be made. A few omt with advanced equipment, but extremely limited. And around ranging from innawood to common cataclysm. Including medieval with indians)

3. Exodii, they've visited many worlds. They could have brought a capsule with a frozen human in it. On purpose or by accident. Though there's still the question of the lab. I'm not very familiar with the timeline of events. Could the government have captured the capsule in time to start studying it?

And any other option you can think of. Including no explanation whatsoever. But from the looks of it, the decision has already been made.

Although I'd be happy to have new subjects to study. But would hardly start this scenario. (With low drop chance, it's hard to get out of empty closed labs).

**Comment by SariusSkelrets** [comment]
It is entirely possible that it was being tested, as it has the obvious medical application of keeping someone in a stable state until they can receive treatment.

The blocker is that if your cryopod malfunctions and thaws you, there's no guaranty the process will be correctly done, leaving your body in a state akin to a bag of thawed strawberries. It would take someone else to do so, but why would they? There are far more pressing issues like not being eaten alive to think about unfreezing people.

Also, be sure to make clear that the character was alive before being frozen. If the character was dead before, it would also require a technology able of resurrection, which is massively far away from DDA's tech level.

However, even if it doesn't fit the main game Aftershock literally have a start as cryosleep survivor and a way to unfreeze cryosleeping people. so that would nicely fit except for the cryptid that must be more distanced from its inspiration.

**Comment by RenechCDDA** [comment]
Hey @Elgrosito just to be clear, this definitely does not fit in the base game. Bionics are not available through this-earth places of technology, while the mutagen research is *specifically* derived from samples of the Blob taken from XEDRA's dimensional research, which takes place in secret.

The cryo facility in your PR spawns on the surface, in the open, with absolutely no secrecy or suggestion that it is anything but routine. That simply does not fit DDA's setting.

At a **minimum** what this would need to fit into DDA proper is:
1) Some level of secrecy, similar to the subway labs. This is not something that can be revealed to the general public without being able to explain its provenance.
2) This also means that it would not be available to the general public, which means explaining why this is a start scenario. Your average joe should not be able to wake up in a secret government facility. They would never be allowed in!
3) A good explanation for why the government would be pursuing this technology, and even *how*. Cryo preservation is not a technology that is feasible in [current year], and it will not be feasible in [current year + 1], either. So there needs to be an explanation of how this changed.

**Comment by Elgrosito** [comment]
> Okay, let's go in order.
> 
> 1. Science employee psychosis.
> 
> Any employee of a laboratory related to cryogenics or portal research. Against the backdrop of all that happened, a little damaged in the head and considers himself unfrozen man. Will need to be finalized and appropriate hints, in the form of documents. (This is rather aimed at the player, whether he can put the picture together or remain lost in the initial description of the scenario).
> 
> 2. Portal Storm.
> 
> I understand the reason you don't want to use it as an explanation. Bringing a frozen person back to life as a result of a portal storm is... unlikely. But we have many worlds that are at different stages of progress. And a lot of them have had cataclysmic events. This is Lore. A piece of an advanced world could have been sucked into ours. It could be a cryogenics lab from a world where they've learned to defrost.
> 
> (On this idea, a whole mod could be made. A few omt with advanced equipment, but extremely limited. And around ranging from innawood to common cataclysm. Including medieval with indians)
> 
> 3. Exodii, they've visited many worlds. They could have brought a capsule with a frozen human in it. On purpose or by accident. Though there's still the question of the lab. I'm not very familiar with the timeline of events. Could the government have captured the capsule in time to start studying it?
> 
> And any other option you can think of. Including no explanation whatsoever. But from the looks of it, the decision has already been made.
> 
> Although I'd be happy to have new subjects to study. But would hardly start this scenario. (With low drop chance, it's hard to get out of empty closed labs).

I wasn't opposed to using the portal storm, I quite liked our idea!

**Comment by Elgrosito** [comment]
> It is entirely possible that it was being tested, as it has the obvious medical application of keeping someone in a stable state until they can receive treatment.
> 
> The blocker is that if your cryopod malfunctions and thaws you, there's no guaranty the process will be correctly done, leaving your body in a state akin to a bag of thawed strawberries. It would take someone else to do so, but why would they? There are far more pressing issues like not being eaten alive to think about unfreezing people.
> 
> Also, be sure to make clear that the character was alive before being frozen. If the character was dead before, it would also require a technology able of resurrection, which is massively far away from DDA's tech level.
> 
> However, even if it doesn't fit the main game Aftershock literally have a start as cryosleep survivor and a way to unfreeze cryosleeping people. so that would nicely fit except for the cryptid that must be more distanced from its inspiration.

Good points, I wasn't aware of Aftershock, so I didn't know there was cryo-facilities there.

**Comment by Elgrosito** [comment]
Based on comments received, I'll close the PR. If it fits on Aftershok, I'll open PR on that repo next year at around march when I'm back from travelling. Happy holidays!

**Comment by Maleclypse** [comment]
> Based on comments received, I'll close the PR. If it fits on Aftershok, I'll open PR on that repo next year at around march when I'm back from travelling. Happy holidays!

Aftershock is the same repo just didn't folders. Happy holidays!

**Comment by Drew4484** [comment]
The concept of waking up from cryogenic storage fits into the tech level for Aftershock, with some caveats. 

Avoid references to NeoScav. Bye dogman, Salus IV is a long way from home.

Superluminal (FTL) travel exists, so cryopreservation strictly for travel wouldn't be necessary for anything but the longest trips. Also waking up from a cryopod being ejected from a ship is the default start for Rimworld.

Cryopreservation on the surface might be appropriate for disease/wound management. There's a hospital start in the core game that could be adapted (spawns you in a hospital with a malus), or random unhealed wounds/health issues applied at spawn could be interesting.

Keep in mind anyone playing on the exoplanet will emerge from their cryo chamber into a world that is not much warmer.

**Pull request closed without merging**
