### PR TITLE
added 'replica' or 'cheap' to the names of relevant weapons

### PR DESCRIPTION
**Pull request by Zapafaz**
#### Summary
None

#### Purpose of change
Some items with id ending in _fake and _inferior are mechanically inferior versions of the 'real' ones (e.g. id 'broadsword_fake' vs 'broadsword') but had the same exact same display names as the real ones. This PR changes the names to add 'replica [weapon name]' or 'cheap [weapon name]' where relevant. Continuing the previous example, broadsword_fake is now 'replica broadsword' instead of 'broadsword'; broadsword_inferior is now 'cheap broadsword'

#### Describe alternatives you've considered
Other words for 'replica' and/or 'cheap' like 'fake' and 'flimsy'. I am fine with other options, I just figured these sounded right.

### CODE REVIEW

**Comment by Procyonae** [comment]
Why?

**Comment by Zapafaz** [comment]
> Why?

To make it easier to determine what the items are without inspecting them, particularly while looting, searching, or sorting at base. Similar to how "makeshift" items are differentiated from their counterparts.

**Comment by Procyonae** [comment]
> To make it easier to determine what the items are without inspecting them, particularly while looting, searching, or sorting. Similar to how "makeshift" items are differentiated from their counterparts.

They're not exactly common enough for it to be annoying, makeshift items are crafted which is quite different imo, seeing recipes for lots of "awesome sounding weapon" s when it's just a few planks roughly representing the awesome sounding weapons would be really annoying

**Comment by Zapafaz** [comment]
> They're not exactly common enough for it to be annoying, makeshift items are crafted which is quite different imo, seeing recipes for lots of "awesome sounding weapon" s when it's just a few planks roughly representing the awesome sounding weapons would be really annoying

Yes, that would be very annoying. I wasn't thinking in terms of how often it's annoying or how annoying it is, it's just something that annoys me sometimes, and I've seen it mentioned on discord as a confusing thing.

**Comment by Zireael07** [comment]
@Procyonae Yes it's confusing and it's basically a noob trap (experienced and/or spoiled players will know which places spawn real weaponry and which spawn inferiors/fakes)

Was an issue on GH recently but my search-fu is failing now.

**Comment by PatrikLundell** [comment]
I'm not fond of using the word "replica" as a synonym for crappy. A replica is a copy of an original, and while some of them may be wall hangers made from cheap materials, some are superior to the original in that they use modern materials with modern material quality while still looking similar to the original.

I'd prefer something like "wall hanger", "imitation", or "pretend" to indicate it's not really suitable for actual use.

**Comment by Procyonae** [comment]
> @Procyonae Yes it's confusing and it's basically a noob trap (experienced and/or spoiled players will know which places spawn real weaponry and which spawn inferiors/fakes)
> 
> Was an issue on GH recently but my search-fu is failing now.

Fair enough I mainly just wanted more than 0 reasoning bc this causes me merge conflicts

**Comment by TrueChevaleresse** [comment]
Was this not intentional? I thought it was deliberate, since it's not always easy to tell at a distance that something is fake, and it adds a bit more risk to going for valuable weapons.

**Comment by Zireael07** [comment]
@TrueChevaleresse Yes it was intentional, but ended up being a noob trap ...

**Comment by fairyarmadillo** [comment]
The entire point of these items is to require inspection to identify and the experience of learning how to do so is a frequently source of praise for the game from people who are in the process of learning it.

**Comment by alp7292** [comment]
its just annoying no other items require close inspection you can tell what type of tree , wall plant, and see small items like aspirins and rocks 50 tile away without any issue why do you need to inspect some weapons to see if its poor quality or not. we dont even have scaling quality items lile rimworld

**Comment by Alm999** [comment]
> its just annoying no other items require close inspection you can tell what type of tree , wall plant, and see small items like aspirins and rocks 50 tile away you can even tell if its a secret wall or not without any issue why do you need to inspect some weapons to see if its poor quality or not.

Ahem… "standpipe maintenance log"… ahem.
But yes, just hitting (E)xamine reveals the nature of an item. A noob trap.

**Comment by kevingranade** [comment]
This is working as intended. "Look at the item description" isn't too intrusive for something that comes up rarely.

**Pull request closed without merging**
