### PR TITLE
Fix light industry gates

### LINKED ISSUE #65672: electronic locked metal door broke this light industry's garage door
### Describe the bug

For whatever reason, this one garage gate at a light industry has 2 electronic-locked metal doors and it broke the gate.

### Attach save file

[Stark City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11486055/Stark.City-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save
2. broken garage gate.

### Expected behavior

The garage gate works as expected.

### Screenshots

Screenshot_20230516-160935

Screenshot_20230516-160951

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a5245ca [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Br1ght0ne**
#### Summary
Bugfixes "Fix light industry gates"

#### Purpose of change

Fixes #65672.

#### Describe the solution

Removes the electronic metal doors for gates, as only the regular ones work with the winch.

#### Describe alternatives you've considered

Making gate winches work with electronic metal doors, which doesn't make much sense to me.

#### Testing

I generated a new world, and teleported to 4 different light industry plants. I made sure there were of both possible variants. All the gates worked correctly.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
The test doesn't actually test the change, it tests that the cause of the problem probably is the one it's thought to be, i.e. part of the fault identification process.

An actual test of the change would be to generate the light industries in the game, go/teleport there (if this is in a variant, it would also require verify it's the correct variant), and verify that the gate works. Apart from testing that the change works when applied normally in the game, it also tests that something hasn't been screwed up elsewhere (there are all kinds of ways to screw up things, from accidentally pasting stuff happening to be in the past buffer, to mistyping the corrected gate type id, and any other weird things that might happen).

**Comment by Br1ght0ne** [comment]
Thanks for the suggestion @PatrikLundell - I'll be sure to do that.

**Comment by Br1ght0ne** [comment]
I updated the testing description.

**Review by Maleclypse — APPROVED** [review]
Thanks for catching this.

**Pull request merged**
