### PR TITLE
Remove CBMs from mines

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Removes CBMs from spawning in mines."

#### Purpose of change
CBMs shouldn't spawn in mines, so now they don't.

#### Describe the solution
Removed all CBMs from the "mine_equipment" item group.

#### Describe alternatives you've considered
None.

#### Testing
None.

#### Additional context
None.

### CODE REVIEW

**Comment by omni-Var** [comment]
And what logic do you derive this from? You just removed a major incentive to ever enter them. Artifacts are not valuable enough to trouble oneself with stepladders and diving into those spots. And I feel like there have been discussions on why the mines would have CBMs. 

Perhaps, limiting the available CBMs that can spawn in mines to ones that make sense would be more appropriate?

**Comment by Drew4484** [comment]
> And what logic do you derive this from? You just removed a major incentive to ever enter them. Artifacts are not valuable enough to trouble oneself with stepladders and diving into those spots. And I feel like there have been discussions on why the mines would have CBMs. 
> 
> Perhaps, limiting the available CBMs that can spawn in mines to ones that make sense would be more appropriate? 

Even if CBMs weren't being moved to the Exodii, why would they exist in mines? If they were cutting edge hardware developed in secret labs, how would they end up scattered around a mineshaft? Mines aren't dungeons, there's no big boss to fight with a rare treasure chest at the end.

**Comment by Zireael07** [comment]
@Drew4484: Mines are commonly used for secret labs and the like in many movies/books/games.

**Comment by Drew4484** [comment]
> @Drew4484: Mines are commonly used for secret labs and the like in many movies/books/games.

Yes but we have secret labs. We have lots of them. They just aren't in mines.

**Comment by hahaha1776** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
