### PR TITLE
Remove vehicle name changes on ownership - Just append owner string to vehicle display

### LINKED ISSUE #32211: Folding and unfolding a vehicle causes duplication of faction ownership indication
# Describe the bug

The (Your Followers) indication is pasted directly into the name of the vehicle, and is duplicated each time a foldable vehicle is unfolded.

# Steps To Reproduce

1. So you have a vehicle that you name "Folding Bike", and it's called "Folding Bike (Your Followers)". 
2. You fold it, and then it's an item called "Folding Bike (Your Followers)" 
3. You unfold it, and then it's a vehicle called "Folding Bike (Your Followers) (Your Followers)" 
4. Each time it's unfolded, the name adds another faction label to the end of the name.

# Expected behavior

A single indication of faction ownership that doesn't duplicate each time the vehicle is unfolded. It's possible to re-name the vehicle to get rid of the extra labels, but it'd be nice to not need to.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5342-g595fee4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    StatsThroughSkills [StatsThroughSkills],
    Safe Autodoc [safeautodoc],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Big Zombies [No_Big_Zombies],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Remove vehicle name changes on ownership"```

#### Purpose of change
Fixes #32211 
Vehicles changing names when they changed owners was not really workable, causing bugs in older saves which didnt have the new `base_name` I added for vehicles.
A much better solution is just to display the name in red when its now owned by you, or green when its owned by you or not owned by anyone.

#### Describe the solution
as above

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Some screenshots?

**Comment by davidpwbrown** [comment]
> Some screenshots?

A random bicycle I found :
image

A bus belonging to the free merchants :

image

**Comment by Night-Pryanik** [comment]
Well, honestly it isn't obvious why in some cases the name is in green, and in others it is red.

**Comment by davidpwbrown** [comment]
> Well, honestly it isn't obvious why in some cases the name is in green, and in others it is red.

It isnt super-obvious no, but other things in the game come with experience, i.e - why is the component in the recipe brown? and so on.

And it is less annoying and finicky to mess with than the vehicle keep changing its name when it changes owners.

Plus - when you interact with a stolen vehicle you get popup warnings " are you sure you want to interact with this vehicle? - it does not belong to you" , so that would be an indicator too.

**Comment by esotericist** [comment]
Color-only based information here is not a complete solution, and I would argue it is a significant regression.
One, color-blind individuals may have trouble distinguishing between the colors selected. Yes, we have that problem elsewhere, but there's been increasing attempts to try to make the information available somehow symbolically when possible, usually through one of the various "detailed info" UIs. For vehicles, that's the screen in your screenshots.
Two, as previously noted by night-pryanik, it isn't really *obvious* what each color means, and while there's plenty of things in the game that aren't clear on casual examination, that doesn't mean we should add more ambiguous information.
Three, we should really know *who* owns it, not just "me" or "not me".

I would instead advocate figuring out how to append the current owner in the display of the name, without changing the actual name of the vehicle.

**Comment by TechyBen** [comment]
Is there another way then to tag the item? It's tagged for colour... so just need some GUI code that writes the tag descriptions instead of changing a colour? I mean, we have "most damaged part" that references that part... why not "vehicle owned by:" that references faction?

(Yes, I just said "just" when referencing programming. Sorry :P )

**Comment by davidpwbrown** [comment]
> Color-only based information here is not a complete solution, and I would argue it is a significant regression.
> One, color-blind individuals may have trouble distinguishing between the colors selected. Yes, we have that problem elsewhere, but there's been increasing attempts to try to make the information available somehow symbolically when possible, usually through one of the various "detailed info" UIs. For vehicles, that's the screen in your screenshots.
> Two, as previously noted by night-pryanik, it isn't really _obvious_ what each color means, and while there's plenty of things in the game that aren't clear on casual examination, that doesn't mean we should add more ambiguous information.
> Three, we should really know _who_ owns it, not just "me" or "not me".
> 
> I would instead advocate figuring out how to append the current owner in the display of the name, without changing the actual name of the vehicle.

Yep, ok I was avoiding the bigger task as is usual for me, I can just fit a new info readout into the UI that shows the current owner, sure I can squeeze it in somewhere.
Owner : Free Merchants
or 
Owner : You
or
Owner : nobody

**Comment by davidpwbrown** [comment]
OK so ive kept the color-coding, but also appended the owner name to the vehicle name, for displaying in the UI only. 
THe name itself isnt being modified, which makes it a lot cleaner.

**Pull request merged**
