### PR TITLE
Gives cutting quality to bayonets.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
It's rather odd that you can't cut stuff with them.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Seems reasonable, yeah. Most modern bayonets are likely to be proper knife bayonets. Unlike, say, a M1905's minimal edge, a K98's lack of one, etc.

**Comment by chaosvolt** [comment]
And I spent so long searching for good examples of WWII-era bayonets before weighing in on this that it was merged while typing my remark. XD

**Comment by Coolthulhu** [comment]
Regular bayonet could be merged with makeshift knife - they have nearly identical stats.

**Comment by Rivet-the-Zombie** [comment]
I've got an old M6 from back in the 70s, and you can shave with it. Makes an excellent hunting knife too.

**Comment by chaosvolt** [comment]
Ah, interesting. But yeah, seems more likely that a bayonet encountered in modern times will be sharpened, whether as-is, by the soldier it was issued to, or by whoever got ahold of it after it became surplus.

As for stats, maybe we should make them more statistically distinct? Either that or split the bayonets into a professionally-made version and a makeshift one.

**Pull request merged**
