### PR TITLE
Bloated zombie changes

### PR DESCRIPTION
**Pull request by John-Candlebury**
While doing the office building, I realized that bloated zombies had both more health and moved more slowly, and In fact their stats were changed some months ago, now ehh it seems that I wasnt around to notice when pr #8583 was submitted, 

I dont think the changes worked so well, they were  fast so that they could pose some sort of danger when you encounter them outside, and to more easily close the gap when one managed to ambush you ( read as: you found one across  a locked room), and it seems to me that the slow walking versions just can't really do this two things well even with their  bigger health.

Well that said thats how I think they should work, but I don't know if people like the slow walking version better.

Also removed their ability to bash things, so they could more easily ambush the player if they spawn inside locked rooms.

### CODE REVIEW

**Comment by Dozed12** [comment]
A bloated zombie should be quite slow yet healthy, I think BASHES and GROUP_BASH

**Comment by John-Candlebury** [comment]
Ehh the problem with that is that they cannot actually work well as walls either (being a monster that commits suicide when adjacent to you). For all intent and purposes this pr reverts them to their original version added in pr  #7042.

I guess the association between the name and speed could result problematic, bloated implies that they should be kinda slow, but design wise, I never intended them to be slow. The name could always be changed to something more appropriate if you have any other suggestions.

Eh dunno about the bash, it doesn't seem like they should be able to bash things without committing suicide.

**Comment by Dozed12** [comment]
I viewed the bloated as a sluggish, very old (infection) zombie, which barely moves and is quite strong.

You viewed and designed it with the intend to make a "suicidal zombie".

Both seem logical and fitting but naming sure is difficult, " suicidal zombie" sounds very boring.

**Comment by Lain-** [comment]
Honestly I'm okay with either way, though I would argue that their HP should be a tad higher to prevent getting one-shotted by a thrown rock or something. I agree that maybe a rename would be sensible, maybe "gasbag" like in the json?

**Comment by i2amroy** [comment]
Gasbag zombie would work fine IMO. Sort of conjures up that "volatile balloon" idea.

**Comment by Rivet-the-Zombie** [comment]
I'm feeling a bit more *Dead Island* or perhaps *State of Decay* than *Left 4 Dead* with this critter.

**Comment by KA101** [comment]
Squarely under "Revert Stuff I don't like", John...

That said, I'd said that revisiting the speed check was an option, and so it is.  Any other opinions?

**Comment by i2amroy** [comment]
Just in case it didn't come across in my previous statement, I like the volatile suicide gas bomber zombie idea. ;)

**Comment by Rivet-the-Zombie** [comment]
I like this.

**Comment by aierce** [comment]
Bloated zombies are obviously boomers from l4d(2). The effects are mostly the same except for spawning more zombies. The debuff effect is even called boomed and tileset mshock looks like the other game too.

If we are going by the other game's standards. bloated zombies should have lower health and slower movement speed.

**Comment by KA101** [comment]
Nope, that'd be the boomers.  ;-P

**Comment by i2amroy** [comment]
Yeah, boomer != bloated zombie, boomer == boomer.

**Comment by Rivet-the-Zombie** [comment]
DDA's *bloated zombie* is more like the [suicider](http://deadisland.wikia.com/wiki/Suicider) from *Dead Island* or (even more like) the [Bloater](http://stateofdecay.wikia.com/wiki/Bloater) from *State of Decay*

**Pull request merged**
