### PR TITLE
remove hardcoding for "dies_into"

### PR DESCRIPTION
**Pull request by juur**
#### Summary
Content "Push dies_into hardcoded C++ feature into JSON"

#### Purpose of change
There is a hardcoded dies_into mapping, used by map::rad_scorch. This patch attempts to push this into JSON instead.

#### Describe the solution

I tried to replicate how transform_into works, however, I'm stuck currently with two things:

1. I get the following error on boot, but transform_into doesn't generate the error, unsure what I've done wrong:

```
> DEBUG    : invalid dies_into  for t_null
> 
> FUNCTION : virtual void ter_t::check() const
> FILE     : src/mapdata.cpp
```

2. I've no idea how to actually test generating sufficient radiation to trigger rad_scorch :-)

#### Testing

It boots! Apart from the error above ...

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Since damaged radiating equipment emits radiation, spawning such items and damaging them ought o produce radiation. If mini-nukes still exist they would probably be suitable objects.

Another alternative would be to teleport to a heavily irradiated location and debug spawn your test subjects there.

A third alternative would be if you can debug spawn fields, in which case you might be able to create a maximum strength radiation field (this would probably the the easiest option if it's available).

**Comment by Procyonae** [comment]
Shouldn't this just use a ter_furn_transform?

**Comment by juur** [comment]
> Shouldn't this just use a ter_furn_transform?

The existing code did not, I don't understand the code base well enough to guess that :)

Is that linked to tranforms_into or can it be used for different targets?

**Comment by Procyonae** [comment]
They're used by JSON mapgen and EOCs to transform terrain/furniture/fields/traps into different ones of the same category ([docs](https://docs.cataclysmdda.org/TER_FURN_TRANSFORM.html))
I'm not entirely sure how you go about calling one from C++ or if there's precedent but it'd make more sense to use the existing infrastructure than essentially rewriting the same thing.
The one you're converting would be something like this:
```json
  {
    "type": "ter_furn_transform",
    "id": "dies_into",
    "terrain": [
      { "result": "t_dirt", "valid_terrain": [ "t_grass", "t_tree_young" ] },
      { "result": "t_tree_deadpine", "valid_terrain": [ "t_tree_pine" ] },
      { "result": "t_tree_birch_harvested", "valid_terrain": [ "t_tree_birch" ] },
      { "result": "t_tree_willow_harvested", "valid_terrain": [ "t_tree_willow" ] },
      { "result": "ter_t_tree_hickory_dead", "valid_terrain": [ "t_tree_hickory", "t_tree_hickory_harvested" ] }
    ]
  }
```

**Comment by juur** [comment]
> They're used by JSON mapgen and EOCs to transform terrain/furniture/fields/traps into different ones of the same category ([docs](https://docs.cataclysmdda.org/TER_FURN_TRANSFORM.html))
> I'm not entirely sure how you go about calling one from C++ or if there's precedent but it'd make more sense to use the existing infrastructure than essentially rewriting the same thing.
> The one you're converting would be something like this:
> ```json
>   {
>     "type": "ter_furn_transform",
>     "id": "dies_into",
>     "terrain": [
>       { "result": "t_dirt", "valid_terrain": [ "t_grass", "t_tree_young" ] },
>       { "result": "t_tree_deadpine", "valid_terrain": [ "t_tree_pine" ] },
>       { "result": "t_tree_birch_harvested", "valid_terrain": [ "t_tree_birch" ] },
>       { "result": "t_tree_willow_harvested", "valid_terrain": [ "t_tree_willow" ] },
>       { "result": "t_tree_hickory_dead", "valid_terrain": [ "t_tree_hickory", "t_tree_hickory_harvested" ] }
>     ]
>   }
> ```

Thanks, I'll take a look and see how to invoke.

**Pull request closed without merging**
