### PR TITLE
Separate gas masks from hazmat suits.

### LINKED ISSUE #24174: Acid and fire protection is affected by having a filter ready
Game version: 0.C-28739-g966bfea

### Expected behavior
The protective gear should protect from acid and fire at all times, if designed to do so. The filter is needed for respiratory protection. (smoke, gases etc)

### Actual behavior
Acid and fire protection depends on having an active filter. It looks especially bizarre in fully enclosed suits like (A)NBC or the hazmat suit, which only use filters to protect the user from inhaling hazardous substances.

### PR DESCRIPTION
**Pull request by Vasyan2006**
- Hazmat, ANBC and entry suits will be armor with constant enviromental protection to resolve #24174,
- These suits will not cover eyes and mouth so additional gas mask* will be required for full protection,
*gas masks sold separately
- Remove PBA mask from entry suit recipe,
- Rename hazmat mask cartridge to chemical mask cartridge to avoid misunderstandings.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Level A hazmat suits do cover the face and head.

**Comment by ZhilkinSerg** [comment]
> Level A hazmat suits do cover the face and head.

+1

**Comment by Vasyan2006** [comment]
Class A hasmats use SCBA instead of the gas masks and its introduce will require new mechanics. It should be more complex and interesting compare to magic rebreather we have now, something like refillable air tanks in the backpack. Based on rebreather cartridge recipe it is some sort of oxygen candle, so once started it cannot be turned off and will produce oxygen until depleted.
But without applications these changed are waste of time, because nobody will use them.

**Comment by glamcube17** [comment]
* Shouldn't there be a chemical mask item to actually use the chemical mask cartridges, then?
* Since hazmat suits do cover the face, IMO it would make more sense to have the normal suit still have the mask but have the option of disassembling it into a mask and an open-face suit.

**Comment by Vasyan2006** [comment]
Common gas masks have15 enviromental protection and provide immunity to all hazard fields. There is no point to add better mask.
Cloth provides the same enviromental protection for all covered body parts. So hazmat suit without filter will not protect legs from acid puddles as pointed in #24174 Separating suits and masks will solve this problem.

**Comment by John-Candlebury** [comment]
I think this issue is better fixed code wise then. The hazmat suit should have a flag that indicates that it'll only protect from gas when its loaded, but will always offer full body protection from other hazards.

**Comment by glamcube17** [comment]
>Common gas masks have 15 environmental protection and provide immunity to all hazard fields. There is no point to adding a better mask.

Then why keep chemical mask cartridges separate if nothing actually uses them? As it is you've made them have no purpose.

**Comment by Vasyan2006** [comment]
@John-Candlebury It will be better to add ability for the items to have different coverage, encumbrance  and enviromental protection for different covered body parts and specify them in jsons. Because now gas masks somehow provide same encumbrance for mouth and eyes. But it will be another long and complex change.

@glamcube17 I am not sure about rules for removing items. At least it will provide error messages on game loading.

**Pull request merged**
