### PR TITLE
Rebalance nodachi (and variants) volume to match zweihander

### PR DESCRIPTION
**Pull request by Griffinhart**
Per [this forum post](http://smf.cataclysmdda.com/index.php?topic=14.msg259995#msg259995), `nodachi` are 2 volume too big to fit in a `back scabbard`.

Further, Wikipedia stats indicate that there is no significant difference in the lengths of typical nodachi and typical zweihander:

["The average length of an ōdachi is 65–70 inches long (approx 165–178 cm)"](https://en.wikipedia.org/wiki/Ōdachi#Purpose)

["Length    up to 180 centimetres (5.9 ft)"](https://en.wikipedia.org/wiki/Zweihänder)

(The Wikipedia article on odachi also has cultural art of samurai wearing odachi sheathed in a back scabbard, so.)

### CODE REVIEW

**Comment by Ygdrad** [comment]
Except the odachi scabbard was meant to be untied because you couldn't unsheathe the blade while wearing it. As for the zweihander itself, here's what wikipedia has to say about it:

"These swords represent the final stage in the trend of increasing size that started in the 14th century. In its developed form, the Zweihänder has acquired the characteristics of a polearm rather than a sword. Consequently, it is not carried in a sheath but across the shoulder like a halberd."

Neither of those should be accessible from a worn scabbard.

**Comment by Coolthulhu** [comment]
Weapon rating changes (due to faster attack speed):
* Diamond nodachi 50 -> 55
* Nodachi 44 -> 49

No problems with the diamond one (it's on par with other diamond weapons), but the regular one is now the best non-diamond, non-cbm core weapon.
That isn't a big problem since it's rare, big and not all that fast, but should be kept in mind when someone decides to do weapon balance changes.

**Comment by Griffinhart** [comment]
+5 rating for a fairly rare, big weapon didn't seem that bad to me. If preferred, I can balance in the opposite direction (i.e. nerf `zweihänder` volume up to 17 to match `nodachi` instead).

**Comment by Coolthulhu** [comment]
Zwei doesn't deserve a nerf, it's one of the worst weapons of its kind.

**Pull request merged**
