### PR TITLE
Magiclysm: Spells affect specific bodyparts with effects

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Mods "Magiclysm: Spells affect specific bodyparts with effects"```
#### Purpose of change

I wanted a way to be able to specify what body parts get chosen for spell effects, so you can create a variety of effects. What I did was added an enum_bitset member to the spell_type object that keeps track of the proper body parts. It's an optional field in json, because not all spells have effects that are applied to bodyparts.
Also, i updated the spells that currently add effects to use the json for this.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Now we can cast "light your head on fire"!

**Comment by ZhilkinSerg** [comment]
Monsters do not have body parts though.

**Comment by KorGgenT** [comment]
hmm, i didn't think of that. i'll have to look into it soon.

**Comment by KorGgenT** [comment]
that should do it: even though creatures do not have bodyparts, they do get effects added to them via add_effect with a bodypart parameter.

**Comment by kevingranade** [comment]
You have some un-astyled chunks in magic.cpp

**Comment by KorGgenT** [comment]
jenkins rebuild

**Pull request merged**
