### PR TITLE
heavy-duty → heavy duty

### PR DESCRIPTION
**Pull request by Faalagorn**
#### Summary
None

#### Purpose of change
Unify spelling of heavy duty.

#### Describe the solution
Change all the remaining instances of heavy-duty to heavy duty.

#### Describe alternatives you've considered
* Change all the remaining instances of heavy duty to heavy-duty.
* Leave both.

#### Testing
Seems to compile fine, can be seen by spawning stuff in question and one changed comment should be seen in Transifex afterwards. 

#### Additional context
Fixes an issue in Transifex.

### CODE REVIEW

**Comment by haveric** [comment]
This is an interesting one that I _think_ makes more sense the other way around in order to avoid confusion in a handful of situations. An article that explains why: https://english.stackexchange.com/questions/404839/should-heavy-duty-always-be-hyphenated-when-used-as-an-adjective

**Comment by Faalagorn** [comment]
@haveric So what your opinion would be? To change it all around, or rather, case-by-case? I'd love to see ither opinions, maybe some style guide consesnus on using hyphen, similar how the serial comma is used.

While I get the possible ambiguity that can result from not using a hyphen, one thing that got me thinking was one of the reply that "but apparently Americans are more likely to discard the hyphen than Brits, according to that NGram"

**Comment by Faalagorn** [comment]
I think I'll keep this PR as is for now, as changing it the other way around would be actually more work than doing the new PR; if a hyphen one would be preferred though, we should make a new PR for that :)

**Comment by haveric** [comment]
Should this one be closed now that your other PR was created?

**Pull request closed without merging**
