### PR TITLE
[Magiclysm] Spells cost 1/5 of their normal cost on spell failure

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[Magiclysm] Spells cost 1/5 of their normal cost on spell failure"

#### Purpose of change

It's always struck me as a little weird that you lose nothing but time for failing a spell. Presumably you're still trying to cast it, you just mess it up, so you still need to call up the mana and some of it would go to waste.

Also, I talked it over with KorGgenT and he agreed. 

#### Describe the solution

Add an EoC that, when you cast a Magiclysm spell (including from attunements) and fail, you lose 1/5 of the normal mana cost. 

#### Testing

Reduced mana is deducted when you fail. The cost of succeeding does not increase.

Hit up those spellbooks, kids.

### CODE REVIEW

**Comment by cainiaowu** [comment]
maybe adding some fluff text to player so that we know something happened instead of wondering why the additional mana cost

**Comment by cainiaowu** [comment]
Thinking about it, the wasted mana need to go to somewhere, so the next step could be turning into something like wild magic surge table, adding more "fun" to the player.

**Comment by Standing-Storm** [comment]
> maybe adding some fluff text to player so that we know something happened instead of wondering why the additional mana cost

This would end up playing every single time you failed a cast, when it already says "You lose your concentration!" I think it'll be less disruptive overall once people get used to the idea that "You lose your concentration!" also means you lose mana.

> Thinking about it, the wasted mana need to go to somewhere, so the next step could be turning into something like wild magic surge table, adding more "fun" to the player.

I already basically did this in Mind Over Matter, so I don't want to replicate it for Magiclysm. I'm also not sure if it fits the one of the mod.

**Comment by keampe** [comment]
> > maybe adding some fluff text to player so that we know something happened instead of wondering why the additional mana cost
> 
> This would end up playing every single time you failed a cast, when it already says "You lose your concentration!" I think it'll be less disruptive overall once people get used to the idea that "You lose your concentration!" also means you lose mana.
> 
Maybe a "special effect" like a tile of lightning on the caster and/or a fissle sound effect - no damage, just a graphical and/or auditory cue.

Might be out of scope for this PR, though. Probably unnecessary, too, for anyone who plays with Magiclysm more than occasionally. 

   - Shane

**Comment by GuardianDll** [comment]
If you want to add classless spells here, they are treated like they are tied by mutation of `NONE`

**Comment by Standing-Storm** [comment]
I thought "Oh, I'll have to do another PR to fix the bug where if you fail to Stop Concentration in MoM while also running Magiclysm, you'll lose mana" but Stop Concentration has NO_FAIL so it shouldn't be a problem.

**Comment by GuardianDll** [comment]
XE spells would be affected also, but they should be gone anyway, and ideally XE dream spells should both get the same treatment and an entirely different way to level them altogether (i wish someone but me make this change, but eh)

**Comment by ashGlaw** [comment]
> XE spells would be affected also, but they should be gone anyway, and ideally XE dream spells should both get the same treatment and an entirely different way to level them altogether (i wish someone but me make this change, but eh) 

Curious what you have in mind

**Pull request merged**
