### PR TITLE
[CR] Electrical damage has a chance to temporarily incapacitate bionics

### PR DESCRIPTION
**Pull request by thquinn**
#### Summary
```SUMMARY: Balance "Electrical damage has a chance to temporarily incapacitate bionics"```

#### Purpose of change
Gives a little more flavor to electrical attacks, and lays the framework for additional electrical effects like unintentionally activating bionics. Cyborgs should think twice before going up against shocker zombies!

ss

#### Describe the solution
I added `Character::on_damage_of_type()`, which serves as a counterpart to `Creature::deal_damage_handle_type()` for character effects. Also added `incapacitated_time` to bionics.

The duration of incapacitation is randomized, but on average scales linearly with the amount of damage. The chance to incapacitate is based on the percentage of the affected body part's HP removed by the attack.

### TO-DO
- [x] don't allow incapacitated bionics to be (a)ctivated
- [x] display incapacitated bionics as such in UI
- [x] bionics like Monomolecular Blade, Bionic Claws, and Fingertip Razors: if incapacitated when extended, should be stuck extended
- [x] more testing/balance

Looking for feedback on all aspects.

### CODE REVIEW

**Comment by Ilysen** [comment]
Doesn't seem too horribly imbalanced and makes sense with how they work. The only thing I'd suggest is a json flag that prevents them from being shorted out by electricity on some bionics, but I'm not sure which ones would have that.

**Comment by thquinn** [comment]
@Ilysen Good idea. I added it to a number of appropriate bionics; let me know if you spot others that should have it.

**Comment by Reclusive-reptile** [comment]
`bio_faraday` definitely shouldn't be disabled by electricity. It prevents shock damage while active.

**Comment by Mecares** [comment]
Could we make the faraday bionic "eat" the first shock in a certain timeframe and protect the other bionics from being deactivated but then deactivate it if another shock hits the player in a too short time frame after the first one? I do not like the have the right bionic and be completely immune to a type of damage mechanism from a gameplay point of view.

**Comment by kevingranade** [comment]
Faraday cages don't work like that.  However there a number of other side effects that could happen based on the presence of the faraday cage.

**Comment by thquinn** [comment]
Did some testing and increased the effects accordingly. Also confirmed that it works with toggleable bionics.

**Comment by ZhilkinSerg** [comment]
Can you resolve conflicts please?

**Pull request merged**
