### PR TITLE
Locker storage update

### PR DESCRIPTION
**Pull request by berangus**
#### Summary

SUMMARY: Balance/Bugfixes "Change locker storage volume to be in line with other furniture options"
#### Purpose of change

Lockers currently have less storage volume than a floor tile, making them worse than useless as storage furniture.

#### Describe the solution

The only change is in furniture.json, changing the locker's "max_volume" from 2000 to 8000. I'm assuming the current storage volume is a bug, as it's half of an empty tile, and dressers have 2000L. Most likely somebody forgot/didn't realize that 1 unit = 0.25L, so they put 2000 instead of 8000. If this is not the case, and lockers are really supposed to have 500L of storage, then ignore this PR.

#### Describe alternatives you've considered

It's a very small change so I haven't really considered any alternatives. Unless you count just manually editing my own JSON every update which is what I've been doing.

#### Additional context

This is my first time using GitHub so if I did something wrong sorry!

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
When I modified lockers volume (among other types of furniture) in #29324, I consulted several sites on their dimensions. I assumed a locker is something like this 

изображение

If so, its volume is [410 liters](https://www.alfa3.eu/high-volume-cloakroom-locker-with-inserted-doors-a1m-25-2-k-p/), so I even was a little generous.

I suppose it's the empty floor volume should be drastically reduced, not the furniture.

**Comment by paulenka-aleh** [comment]
Also I'm not sure useful or not but locker in compare to floor tile does have a lock, at least it used to appear on deconstruction. It can be used either now or in future to prevent NPC thefts.

**Comment by Rail-Runner** [comment]
> I suppose it's the empty floor volume should be drastically reduced, not the furniture.

Well, assuming the tile is a 2-meter-sided square and range from floor to ceiling is 3 meters, one could stuff up to 12000 liters into one indoors tile. For outdoor tiles, it'd be effectively infinite as there's no ceiling. Or would it have to be calculated in some other way?

**Comment by ZhilkinSerg** [comment]
Pile of items dropped to the floor is limited by height either indoors and outdoors.

**Comment by Night-Pryanik** [comment]
> assuming the tile is a 2-meter-sided square

We can't assume that. Tile doesn't have any fixed dimensions.

**Comment by Amoebka** [comment]
Well, a normal speed character walks 1 tile per 1 second now. Assuming the walking speed of 5 km/h, a square tile has 1.4m sides and a surface area of 2 m2.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Well, a normal speed character walks 1 tile per 1 second now. Assuming the walking speed of 5 km/h, a square tile has 1.4m sides and a surface area of 2 m2.

Tile dimensions are defined as necessary in any given context.

https://www.reddit.com/r/cataclysmdda/comments/6q7qgg/what_are_the_dimensions_of_a_tile/

**Comment by kevingranade** [comment]
This is working as intended right now.

**Pull request closed without merging**
