### PR TITLE
Foot pedal power increase

### PR DESCRIPTION
**Pull request by DangerNoodle**
Closes https://github.com/CleverRaven/Cataclysm-DDA/issues/18114

Not sure how much increase is enough. Started with double hand rim value.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
How does it affect the velocity of the stock bicycle at 8 strength and 14 strength?

**Comment by DangerNoodle** [comment]
Sorry for the delay.

Before:
8 Strength: 12/36 MPH
14 Strength: 21/60 MPH

After:
8 Strength: 17/51 MPH
14 Strength: 27/75 MPH

I need to test and see what minimum power @Soyweiser will need.

**Comment by DangerNoodle** [comment]
Tested replacing back basket with a cargo space and dropping an anvil in it, with 8 strength. Can drag it, but even with 64 power it can't drive.

A more complex fix to determine ratio of power to allowed weight might be better, but this is beyond my ability.

**Comment by Coolthulhu** [comment]
There is a hardcoded weight limit for all muscle engines, meaning that pure json changes will not help with that one.

**Comment by DangerNoodle** [comment]
That explains it. Is there a way to make that limit behave sanely relative to vehicle weight drag limit? What source file is it in, and what is the name of the function/int/property/something where it is defined?

**Comment by Mecares** [comment]
Just for comparison: World record for speed on a bike on flat ground (perfect ground conditions and racing bike) over 200 m distance is 77 kph or 47.8 mph anything above is superhuman and horribly unrealistic if possible off road.

**Comment by DangerNoodle** [comment]
So that implies that buffing the safe speed is acceptable. However, that alone failed to resolve the issue. I would assume that somewhere is a formula for calculating how much weight a given type of engine can support.

If it already allows different power/weight ratios based on type of fuel, this allows me to try and make it look at character strength. But if I can even do that, this begs a second question: What IS the ratio of points in strength to vehicle drag weight? I assume that viable wheels modify this in some way?

**Comment by Coolthulhu** [comment]
You can achieve 47 mph at 16 strength and 57 at 20 strength.

**Comment by DangerNoodle** [comment]
That seems like a large amount, but thank you.

Only problem is that this still did not fix that issue with the weight limit not respecting strength, if I recall.

**Pull request merged**
