### PR TITLE
Gourmand nerf, Optimist and Bad Temper rebalance

### PR DESCRIPTION
**Pull request by Xanderga**
```SUMMARY: Balance "Gourmand, Optimist, Bad Temper"```
#### Summary
Gourmand's maximum number of times for consumption (for the sake of morale) has been reduced from 6 to 3.
Optimist and Bad Temper multipliers are now +- 20% instead of +- 25%. They also now give +10 and -10 respectively instead of +5 and -5.

#### Purpose of change
Decreases the abusability of Gourmand for unnaturally large morale boosts (aka, 222 morale for 18 hours simply eating 6 toast-ems, several hundred more from alcohol before sleeping etc). 
Optimist raised to +10 constant instead of +5 to make the trait more attractive while reducing its effect at 200+ morale. For the sake of "realism", +5 morale from Optimist is the same as chewing 2 pieces of gum. Not very optimistic.
Bad Temper aptly changed to reflect the change in Optimist for consistency, and to also increase its malus. At its current state, it's a free 2 points.

### CODE REVIEW

**Comment by Siersha** [comment]
@kevingranade 
For gourmand's case:
Without gourmand, we are capable of eating food twice before the morale bonus caps for a total of 2x for any 1 particular food item.
With gourmand at its current state, we are capable of eating food six times before the morale bonus cap with the addition of a 1.5x multiplier to morale. This caps the morale bonus to 9x the morale of pre-gourmand for any 1 particular food item. Below are some examples of items affected by gourmand, many of which are overwhelmingly common. Alcohol, in general, is only subject to being drunk twice, but with the 1.5x boost, its effect is significant (Though this is a different topic altogether).
image

For Optimist and Bad Temper:
It is not a matter of values being "wrong", but more so that the effects are weak for +-2 points. For the case of Optimist, a constant +5 morale is too small to consider worth taking. The +25% morale is worth consideration, but not for the cost of 2 points. Players may opt to get Gourmand, packmule, tough etc with those 2 points instead as they are simply better options (though, at this point its comparing apples to oranges). Hence, I propose +10 morale, and 20% for balance purposes.
 Bad Temper is too good of a choice not to take in general as well. If the player doesn't plan on utilizing morale outside of some focus boost, it's a free 2 points due to its downsides being inconsequential.

**Comment by nexusmrsep** [comment]
@kevingrenade I believe that it was not always that gourmand would break the balance of the joy system, I think it was either introduced or exposed around the time when freezing and food heating made cold and hot foods much more available at low effort, thus exponentialy increasing gourmand trait influence on the morale. Without it, it takes a significant configuration of actions such as music, food and drugs to get even close to the values presented above as stacking food influence from gourmand. IMHO it's then more then advised to get a second look on validity of overstacking fun from food. In the end of the day it's the law of diminishing returns. If you eat more and more food one by one IRL your overall satisfaction can grow just as much and additional meals wouldn't affect it as you'd be all ready stuffed as a Thanksgiving turkey.

**Comment by kevingranade** [comment]
That's why I'm trying to dig into the scenarios that are problematic , I also suspected that gourmand wasnt the cause of the problem.

I think the real issue is a combination of food stacking and hot/cold bonuses.

**Comment by Siersha** [comment]
I just want to clarify that in the image above, only the Chardonnay, and wines were subject to the hot/cold multipliers. All else were "normal".

**Pull request closed without merging**
