### PR TITLE
Re-add moose taming to tamable wildlife mod

### PR DESCRIPTION
**Pull request by adamkad1**
#### Summary
Mods "Re-adds moose taming to tameable wildlife mod"

#### Purpose of change

Because taming moose is cool.

#### Describe the solution

#64095 removed taming moose entirely which is not cool, so i added it to a mod instead.

#### Describe alternatives you've considered

Not having cool moose taming anywhere.

#### Testing

Get in game, feed moose, works.

#### Additional context

Someone probably should make moose milkable too since that seemingly was half the point of them being tameable. Not sure if I can. And I definitely don't know how much milk should a moose give

### CODE REVIEW

**Comment by Termineitor244** [comment]
Thank you! This was something I put in my back burner some time ago but never went around to do it.

**Comment by adamkad1** [comment]
> Thank you! This was something I put in my back burner some time ago but never went around to do it.

Must have planned that since before the pull to remove it from base got merged eh?

**Comment by Termineitor244** [comment]
> > Thank you! This was something I put in my back burner some time ago but never went around to do it.
> 
> Must have planned that since before the pull to remove it from base got merged eh?

Yeah, I wanted to add their young as tamable in the mod, since they didn't exist when I originally made it, I only remembered it because of the linked PR to remove the taming from vanilla.

**Comment by adamkad1** [comment]
> > > Thank you! This was something I put in my back burner some time ago but never went around to do it.
> > 
> > 
> > Must have planned that since before the pull to remove it from base got merged eh?
> 
> Yeah, I wanted to add their young as tamable in the mod, since they didn't exist when I originally made it, I only remembered it because of the linked PR to remove the taming from vanilla.

Neat.

**Comment by AcidAntOnAMinefield** [comment]
Thank you for this. I was wondering why it was completely removed instead of just being moved towards the mod in the first place.

**Comment by adamkad1** [comment]
> Thank you for this. I was wondering why it was completely removed instead of just being moved towards the mod in the first place.

Laziness? Not caring? One can only speculate.

**Comment by Karol1223** [comment]
> Not caring?

Yeah that one. I care more about mainline making sense than catering to mods, even if it's a mod I personally like.

**Pull request merged**
