### PR TITLE
Add painkiller eyedrops for treatment of conjunctivitis and other eye irritation

### PR DESCRIPTION
**Pull request by zachary-kaelan**
#### Summary
Content "Add painkiller eyedrops"

#### Purpose of change

There are no medicated eyedrops in the game, just saline eye drops for washing your eyes. With conjunctivitis being a thing, there's now a need for such eye drops to be available as treatment. 

#### Describe the solution

Add eyedrops with anti-inflammatory and anesthetic properties. They allow for temporary resistance to conjunctivitis and its effects. It can also help a lot with low-intensity eye irritation (like that from conjunctivitis) and some with tear gas (not touching the lung-related effects). It does not, however, provide total immunity or a cure, as the cause of the irritation is still there. Tear gas primary acts through activation of the tear ducts rather than through pain or inflammation, which is why these eyedrops can't help as much.

In a future PR I plan to track build-up of contaminants in the eyes from standing in smoke or tear gas for too long and add some conjunctivitis if too much accumulates. You can see me starting and reverting it in my commits.

#### Describe alternatives you've considered

Who needs sight anyway?

#### Testing

WIP.

### CODE REVIEW

**Comment by kevingranade** [comment]
What actual product are these supposed to be representing?

**Comment by zachary-kaelan** [comment]
> What actual product are these supposed to be representing?

I based the duration on Oxybuprocaine as a placeholder but I'm not set on anything yet. A wide range of different eye drops are used in response to chemical eye injuries, including artificial tears, antibiotic eye drops, steroid eye drops, cycloplegic eye drops, anti-inflammatory eye drops, and pH balancing drops. Topical anesthetics like Oxybuprocaine are for immediate pain relief, and apparently are sometimes illegally obtained and abused.

**Comment by kevingranade** [comment]
Ok if it's opiod based it needs to be relatively rare (and woo side effects), whereas NSAID based stuff is going to be less effective but more common.  Vs chemical burns I'd characterize ordinary eye drops as pointlessly ineffective.

**Comment by zachary-kaelan** [comment]
None of the eye drops are opioid based. But noticing the "-caine" in all these eyedrops, a quick search found that [cocaine eye drops](https://newdrugloft.com/ophthalmic-compounding/cocaine-hcl-ophthalmic-solution) are indeed a thing. I think a new crafting recipe is the obvious next step. Those wouldn't spawn in many places if at all.

**Comment by kevingranade** [comment]
Why follow up on cocaine eye drops? They're not even really *for* pain relief, and they have *major* side effects.

**Comment by zachary-kaelan** [comment]
Well first it would require a few steps involving professional lab equipment and chemicals and some time to purify the garbage found on the street.

It was [tested on infants](https://iovs.arvojournals.org/article.aspx?articleid=2562755) for use in diagnosis of specific eye disorders with no noted side effects and was [recently FDA approved](https://newdrugloft.com/ophthalmic-compounding/cocaine-hcl-ophthalmic-solution) for use as a local anesthetic during surgeries.

**Comment by kevingranade** [comment]
You didn't answer the question, why would anyone use it, much less to to the potentially extreme difficulty of *making* it? Sure it might be very good at relieving pain, at the cost of being able to use your eyes for you know, seeing things.

In case you're not aware, the main side effect it's used for is "forcible dilatation of pupils" i.e. your pupils are stuck fully dilated until it wears off, which renders you unable to focus properly and incredibly photosensitive, to the point of eye damage if you aren't careful.

This does not provide "get you functional so you can get out of danger" care, which is what pain relief in DDA mostly revolves around.

**Comment by zachary-kaelan** [comment]
> your pupils are stuck fully dilated until it wears off

Oh yeah, I'm dumb, that's a pretty bad side effect for our purposes. I'm just a huge sucker for any opportunity to add more chemistry recipes.

Back to the original eye drops, probably some kind of steroid like prednisolone, as steroids are what keep coming up in my research. The hardcore stuff is mainly for surgeries, examinations, or to make irrigation suck less.

**Pull request merged**
