### PR TITLE
"Zombie kill station" map extra

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Content "Added ''Zombie kill station'' map extra."

#### Purpose of change
Add more content, atmosphere and FUN. Implement idea from discussion in #35500.

#### Describe the solution
Basically, resurrection of #35500 in new dress. I'll just copy and paste most of the description from there.
- Added a `loudspeaker` "monster". It will continually shout a set of messages which should warn player about trap up ahead and will attract zombies to their doom.
- It will spawn at random `road` overmap terrain inside a city radius. I used `road_nesw_manhole` overmap terrain to trigger spawning of map extra because usual `road` OMT is densely populated by other map extras and thus this new map extra will have a minimal chance to spawn at all, just like it was with "minefield at bridges" map extra not so long ago.
- The chance to spawn is 5% per city's _crossroad with a manhole_.
- Messages are written as snippets, so they are easily could be added or edited.
- Messages are chosen randomly from the list.
- Loudness for warning sound is 60, so it should be heard from the border of reality bubble.
- Cooldown for another warning is 10 seconds.
- Loudspeaker will drop some low-importance loot on its death.
- Loudspeaker spawns over the trap's engine. This feels like a hack, but it works perfectly.

#### Describe alternatives you've considered
None.

#### Testing
Debug-spawned map extra, strolled around big cities' crossroads with a manhole, observed zombies walked to their death.

#### Additional context
In the beginning
изображение

After a minute
изображение

### CODE REVIEW

**Comment by mrkybe** [comment]
Is this always going to place dead-center of the road/tinymap?  It would be nice if it was random within some radius of the center so that there's a bit of variation.

**Comment by Night-Pryanik** [comment]
> Is this always going to place dead-center of the road/tinymap? It would be nice if it was random within some radius of the center so that there's a bit of variation.

Well, center of the road feels like most "natural" place for a trap like this. If placed near the edge of the map, it could be blocked by the walls of adjacent buildings, and in theory this should reduce trap effectiveness.

> Also if I'm reading it right, this will appear on 1/5 manholes in a city? That seems too frequent.

`chance: X` for map extras means "one in X", i.e. `chance: 20` in this case means 1/20 = 5%. Thus only 5% of all crossroads with a manhole inside city radius could trigger spawning of this map extra.

Also, little clarification (just in case): this map extra won't necessarily spawn on crossroad with a manhole. If said crossroad actually trigger the spawning, kill station could spawn in any piece of ordinary road inside city radius.

**Comment by mrkybe** [comment]
> Well, center of the road feels like most "natural" place for a trap like this. If placed near the edge of the map, it could be blocked by the walls of adjacent buildings, and in theory this should reduce trap effectiveness.

> Also, little clarification (just in case): this map extra won't necessarily spawn on crossroad with a manhole. If said crossroad actually trigger the spawning, kill station could spawn in any piece of ordinary road inside city radius.

I agree that it should be biased towards being more centered, but this is the sort of thing that'll start to look extremely repetitive on subsequent encounters at least to my brain.  What I was suggesting was to add a random +/-5 in any direction of the center.  Thanks for the clarification btw, so if it can spawn on any road tile in the city, its even more bizarre that it always spawns in the center of road tiles.  Presumably anywhere on the line following the direction of the road would be just as good?

Also (though heavily mitigated by it being possible for it to spawn on any road tile), its possible for an extremely unlucky survivor to take the sewers to get around the city, can and climb out of the manhole, into the death radius of this thing?  I guess with z-levels on they'd be able to hear the warning... if they aren't deaf.  That's actually hilarious.

**Comment by Night-Pryanik** [comment]
> What I was suggesting was to add a random +/-5 in any direction of the center.

Ok, implemented +/-5 random direction from the center.

> its possible for an extremely unlucky survivor to take the sewers to get around the city and climb out of the manhole, into the death radius of this thing?

Nope, code explicitly checks 3x3 pavement terrain to place trap, and manhole is a different type of terrain. The trap would never be placed on a manhole terrain.

> Last point, is this something that could be made controllable with the Control Laptop or some lower tech remote? (or is it already?)

You mean the trap itself or the loudspeaker?

>  How did whoever set this up turn it on?

Honestly, I don't know. It has no energy source, no fuel consumption, it just _works_.

**Comment by mrkybe** [comment]
> Ok, implemented +/-5 random direction from the center.

I'm happy with this.  Thanks :)

> Nope, code explicitly checks 3x3 pavement terrain to place trap, and manhole is a different type of terrain. The trap would never be placed on a manhole terrain.

Ah should've noticed that when I read through it, cool.

> You mean the trap itself or the loudspeaker?

Either/both I guess.

> Honestly, I don't know. It has no energy source, no fuel consumption, it just works.

muh realisms muh immurshun

**Comment by Night-Pryanik** [comment]
> Either/both I guess.

Loudspeaker could be rather easily made controllable through control laptop as it is a monster like any other laptop-controllable turret. 
Making trap controllable is much more harder work which would require a lot of new code. 

> muh realisms muh immurshun

Why the sarcasm? AFAIK this trap is really old one, relict from the times when we didn't bother much about plausibility. It should be reworked some day, or maybe even converted into a vehicle.

**Comment by mrkybe** [comment]
> > Either/both I guess.
> 
> Loudspeaker could be rather easily made controllable through control laptop as it is a monster like any other laptop-controllable turret.
> Making trap controllable is much more harder work which would require a lot of new code.

Can you add the flag/s for that?

> > muh realisms muh immurshun
> 
> Why the sarcasm?

Nothing meant by it.

> AFAIK this trap is really old one, relict from the times when we didn't bother much about plausibility. It should be reworked some day, or maybe even converted into a vehicle.

Agreed.

**Comment by Night-Pryanik** [comment]
> Can you add the flag/s for that?

Done.

**Pull request merged**
