### PR TITLE
Fix Small Lighthouse Tower Floor

### LINKED ISSUE #78553: Inside of small lighthouse tower should be considered inside
### Is your feature request related to a problem? Please describe.

While building a base in a small lighthouse I realized that the lighthouse tower is considered outside (rain starting falling on my bed).  Since the tower is fully enclosed with Stone Masonry Floors/Walls,  the top of the ladder is inside glass walls, and it is roofed I feel it should be considered inside space.

### Solution you would like.

Either change t_stone_masonry_floor to be an inside floor or replace the flooring of the lighthouse tower with one that is.

### Describe alternatives you have considered.

Remove some of the walls around the tower to create slits/openings to make it clear that it is exposed to the elements.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WhaleYogurt**
#### Fix Small Lighthouse Tower Floor
Bugfixes: Lighthouse tower properly marked as inside space**

---

#### Summary  
Bugfixes "Lighthouse tower properly marked as inside space"

---

#### Purpose of change  
Fixes #78553.

Currently, the small lighthouse tower is marked as **outside** despite being enclosed with:  
- Stone masonry walls (`t_stone_masonry_floor`),  
- Glass walls at the ladder's top, and  
- A roof.  

This causes unintended behavior, such as rain falling indoors. This PR ensures the lighthouse tower is correctly marked as an **inside space**.

---

#### Describe the solution  
- Added the `t_stone_masonry_floor_balcony` tile which is considered an **inside floor**.  
    - This resolves the issue while preserving the aesthetic and structural integrity of the lighthouse.  

---

#### Describe alternatives you've considered  
1. **Manual tile replacement:**  
   Replace the `t_stone_masonry_floor` tiles specifically for the lighthouse with another floor tile (e.g., `t_wood_floor` or `t_tile`) to mark the space as inside.  Please consider doing this @harakka so that sky island isn't affects

---

1. **Impact testing:**  
   - Checked for unintended side effects on other locations using `t_stone_masonry_floor`.  

---

#### Notes  
- If modifying `t_stone_masonry_floor` globally is problematic, I will adjust the tiles specific to the lighthouse area.  
- Maintainers have permission to edit this PR as needed.

### CODE REVIEW

**Comment by WhaleYogurt** [comment]
Just mostly reused the old PR text for times sack but in short I added a new tile which is indoors so that the old one doesn't conflict with sky island. So @harakka is now able to change the structure so it uses both

**Comment by harakka** [comment]
This PR doesn't currently fix anything since the terrain you added isn't used anywhere. You can do it trivially yourself, add it to the palette in `data/json/mapgen/lake_buildings/lighthouse_small.json` and edit the `lighthouse_small_z4` map further down in the same file to use it.

**Comment by WhaleYogurt** [comment]
Thanks for telling me that. I know literally nothing about map-making in this game but I guess there's no time like the present. Any other resources I should know about for future reference?

**Comment by WhaleYogurt** [comment]
Does that work @harakka ?

**Comment by Night-Pryanik** [comment]
Yes, this will do.

**Pull request merged**
