### PR TITLE
Buff ranges of numerous bows

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

```SUMMARY: Balance "Numerous bows have had their range increased, especially for lower-end bows."```

#### Purpose of change

A number of bows, especially at the lower-end, had almost no range at all, shooting less far than a sling, and much less than a survivor could throw a grenade. The shortbow had a range of 4, meaning that even with carbon fibre arrows it could barely shoot the length of a car.

#### Describe the solution

This change increases the range of many bows to make them more practical weapons. I used the compound bow as my reference, which has a range of 14/18/22 based upon how it's strung.

Updates are:

- Self bow: 5 -> 8
- Short bow: 4 -> 10
- Composite bow: 5 -> 12
- Reflex bow: 6 -> 12
- Hybrid longbow: 10 -> 14
- Longbow: 10 -> 18
- Compound greatbow: 8 -> 18

I feel that some of these at the higher end could be made even higher, especially since a [modern longbow can do 180m](https://history.stackexchange.com/questions/8022/how-far-could-an-english-war-bow-shoot), with even longer historical ranges. However I'm not familiar with the `STR_DRAW` flag, and I'm not sure if archery skill has an impact on range, so my changes have been kept moderate for now.

This change doesn't alter anything other than the ranges. This change does not claim the new values are balanced, but I believe them to be more balanced than before.

#### Describe alternatives you've considered

Using my sling for everything. :)

### CODE REVIEW

**Comment by esotericist** [comment]
For what it's worth, darktoes is amidst the weapon side of the archery revamp. This is not saying this isn't without value right now, just that some work is in progress.

Also, fun fact, `STR_DRAW` is basically busted at the moment, adding to the range you are allowed to *target* but not the range you can *actually shoot the arrow*.

**Comment by darktoes** [comment]
Yeah bow ranges are pretty broke and I'm well aware. Currently dealing with the fact I have 2 reports and an assignment due monday, then I think I'll get into some hardcore JSON to fix this and some other issues.

I'm fine with this being merged, but it's almost certainly going to be changed not long afterwards, so it's up to the maintainers if they feel it's worth it to have a partial fix a couple of days early.

Also yeah STR_DRAW is so broken I don't even know what to do with it other than just take it out of everything and pretend it doesn't exist.

**Comment by dommon** [comment]
`diff --git a/src/ranged.cpp b/src/ranged.cpp
index 2265b0f715..c083563e41 100644
--- a/src/ranged.cpp
+++ b/src/ranged.cpp
@@ -1598,7 +1598,7 @@ static projectile make_gun_projectile( const item &gun )
     projectile proj;
     proj.speed  = 1000;
     proj.impact = gun.gun_damage();
-    proj.range = gun.gun_range();
+    proj.range = gun.gun_range( &g->u );
     proj.proj_effects = gun.ammo_effects();
 
   `
should fix STR_DRAW, now as for ranges.. sure, tho regarding selfbow etc im pretty sure you could sling a rock further than shoot an makeshift arrow from a 'bow' made from a stick and string in 5 minutes - and more accurately too, anyhow im more worried about bow damages, especially considering disparity with crossbows

**Comment by darktoes** [comment]
Honestly, I don't actually want to fix STR_DRAW, I'd be more than happy to have someone else repurpose it for something else or remove it entirely. The concept of being stronger allowing you to draw a bow back further is iffy an simplistic, so I don't intend to work with it any.

The intended balance for the self bow is that it's reasonably high poundage, but very inefficient and large, which I think is pretty much the only way to make it somewhat useful to a player. That said, under my current numbers, a sling should be roughly on-par with the self-bow. Probably a bit less accurate and with less AP, but having slightly better overall damage.

**Pull request merged**
