### PR TITLE
Spears and Chainmail Sheet Nested Groups, Cow Armor Sub-Category and Estoc Nesting Fix

### PR DESCRIPTION
**Pull request by sadenar**
#### Summary
Content "Miscellaneous recipe category fixes/additions"

#### Purpose of change
Started as a second part to my previous Nestening PR, until I realized I was actually pretty happy not doing much aside from the Spears and Chainmail Sheets nested group, so I decided to fix another few things in the crafting menu while I was at it.

#### Describe the solution
- Reduced the difficulty parameter to what the lowest difficulty item in the nested group was at following devcord feedback on my previous PR.
- Added a new nested group in the piercing weapons for spears, did not include the pike, javelin, forked spear or unsharpened spear shafts, as I considered them out of scope.
- Added a new subcategory to the Animals category called Bovine armor, for armors you put on cows.
- Fixed the nesting of the estocs, there was a bit of an issue that their nested group was pointing at the cutting subcat while they were piercing weapons as well as the fact that they were not hidden into said nested group, that is now fixed.

#### Describe alternatives you've considered
- Adding some more nested groups, however I do not personally think there are many good candidates left, most ideas I had left would either have too few members or too much variety to be viable, this may of course change in the future if/when people add new things that would be good candidates for nesting.
- Not adding the spears nested group, I have gotten feedback on the devcord that it might have too much variety within its members to be a good nested category, but I personally disagree, so I guess I will leave the final decision on whether my opinion is trash to reviewers/players.

#### Testing
Did the changes needed to add what I added, logged into the game, fixed errors until all the recipes showed up where and how they needed to be in the crafting menu.

#### Additional context
Could have used this PR to fix a few typos/inconsistancies I saw, decided against it as modifying more files as this one already was split between 6 of them and more would have just been confusing at review.

### CODE REVIEW

**Comment by TheShadowFerret** [comment]
>Added a new nested group in the piercing weapons for spears, did not include the pike _**SNIP**_, as I considered them out of scope.

Why not subnest it under "pikes" inside the the spears category?

**Comment by sadenar** [comment]
> > Added a new nested group in the piercing weapons for spears, did not include the pike _**SNIP**_, as I considered them out of scope.
> 
> Why not subnest it under "pikes" to contain all 3 craftable pikes inside the the spears nest?

I guess I could do that.

**Comment by sadenar** [comment]
Apparently adding the cows subcategory is what fails the tests, I could have sworn it ran fine when I added it on my game for testing but now it seems this is causing it to CTD, probably need help on that, don't even know where to begin to fix this, probably need help.

**Comment by anoobindisguise** [comment]
I cloned this, compiled it and tested it and I had no errors.
image

**Comment by Maleclypse** [comment]
@andrei8l I hate to bother you but I can't make heads or tails of this error and people who've run these changes say they work fine in game.

**Comment by andrei8l** [comment]
That error happens when DinoMod is loaded because it also has a `CC_ANIMALS` category which lacks `"CSC_ANIMALS_BOVINE ARMOR"`

https://github.com/CleverRaven/Cataclysm-DDA/blob/5d69feefd204fce9f3a4a39e1e6293157fee74eb/data/mods/DinoMod/recipes/recipes.json#L4

**Comment by sadenar** [comment]
Got it. Will fix it tomorrow when I wake up.

**Comment by sadenar** [comment]
Uhhhhhhh

**Comment by sadenar** [comment]
Yep sorry for that, just needed to fix something simple and I broke everything, but now this PR should be more or less ready if the tests will it.

**Pull request merged**
