### PR TITLE
[CR] Fix SDL flickering by moving SDL update calls everywhere.

### PR DESCRIPTION
**Pull request by DanmakuDan**
For #13948.

This attempts to fix flickering and preserve the general benefit of having SDL draw updates more often. Still WIP because I'm not sure where to put the dummy version of try_sdl_update (currently doesn't compile in Linux because cursesdef.h can't contain the method itself).

Some of the try_sdl_update calls may be unnecessary. Maybe only the parts of code with draw calls that don't follow up with user input need fixing.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, hope it goes well. ^^

**Comment by kevingranade** [comment]
What's the rationale for where the update calls go?

**Comment by DanmakuDan** [comment]
It is based on making sure the window was presented to the user before input. Since there is a merge conflict with this PR, I am creating an updated one.

**Comment by chaosvolt** [comment]
Glorious merge conflicts. ;w;

**Pull request closed without merging**
