### PR TITLE
Change vehicle efficiency tests to time-based rather than fuel percentage based

### PR DESCRIPTION
**Pull request by Coolthulhu**
The fuel percentage tests have two edge cases:
* Low capacity vehicles may have too little fuel to actually start
* High capacity vehicles take a while to be tested

By changing it to time-based, the two edge cases would be eliminated.

The time-based tests have different disadvantages:
* Fuel weight affects outcome. Can be considered an advantage because it reflects real results better
* "Ugly" numbers due to the above
* Requires extrapolation

The alternative would be to provide a constant amount of fuel regardless of vehicle type, which would do a better job at comparing high capacity vehicles with regular cars (who cares that SUV can drive 2x as far as car if it needs 2x fuel to do that?), but would require normalizing fuel amount for different fuel types.

Here I also tried to implement a smooth start/stop test to test possible implementation of regenerative braking. Disregard that, it's low priority.

### CODE REVIEW

**Comment by kevingranade** [comment]
Need to look at it in more detail, but looks like a major improvement.

I don't think the shortcomings you list are new, AFAICT the previous
version of the test had all of them.

Just fyi, I was confused as hell about what you were doing, outlining how
the test works now would have helped a lot, like, "the test now loads the
vehicle with fuel, recording the amount, then drives the vehicle forward
for a fixed number of (simulated) turns, then measures the amount of fuel
expended and the distance traveled to determine distance-per-unit-of-fuel".
At first I thought you were changing the test to measure GPH instead of
MPG, very confusing.

**Comment by Coolthulhu** [comment]
> "the test now loads the vehicle with fuel, recording the amount, then drives the vehicle forward for a fixed number of (simulated) turns, then measures the amount of fuel expended and the distance traveled to determine distance-per-unit-of-fuel"

Pretty much this.
I could include something like that in the comments to make sure it's readable.

**Comment by Coolthulhu** [comment]
I'm almost there, but I keep getting non-deterministic results.
Weirder yet: they ONLY affect APC driving on dirt. Everything else has deterministic results in all 10 tries.

**Comment by Coolthulhu** [comment]
OK, got the APC nondeterminism - it was caused by turrets having ammo in them.

Only nondeterminism left is electric cars. It is caused by nondeterminism in `epower_to_power`, which will be hard to fix without overhauling the electricity/fuel status.

**Comment by kevingranade** [comment]
Awesome, what I had done earlier was to launch the unit test in a debugger, set a breakpoint in rng(), and then let it run until it hit the breakpoint.  Then you can check the backtrace and see if it is something that will influence the test.

**Comment by Coolthulhu** [comment]
I included some fixes for tests in this PR, because I broke testing with that overmap generation guard.
I could split them off, but this PR is the only current one that actually deals with tests, so it shouldn't be a big deal.

**Comment by kevingranade** [comment]
Also you said fuel tests are hosed here: https://github.com/CleverRaven/Cataclysm-DDA/issues/20411#issuecomment-284225433, did you sort that out?

**Comment by Coolthulhu** [comment]
Only partly...
The results are better, but electric car on dirt has ~50% of efficiency of gas car, while in actual tests it has ~20%.
Not sure what to do about that.

**Comment by kevingranade** [comment]
OK, can you drop a note about your manual testing in the unit test?  I'd
like to investigate that sometime, but this looks like a big improvement as
well so I don't want to put off landing it.

**Comment by Coolthulhu** [comment]
Oh, it isn't as bad as I thought, I just did my math wrong.
While the actual ratios of efficiency are pretty far from each other (regular car with full tank can travel 250% the range of electric car with 2 full batteries), the misrepresentation in tests is much smaller.

Tests show that car has 200% the range of an electric car, so the error here is `250%/200%-100%=25%`.
Added a comment describing the issue.

**Pull request merged**
