### PR TITLE
[Limb Mod] Limbify Feathered Arms, rework Bird Wings and gliding checks

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Features "Limbify Feathered Arms, rework gaining Bird Wings"

#### Purpose of change

Move the Feathered Arms -> Bird Wings progression over to the eoc-based limb progression framework.
Stamp some weirdness that came out along the way.

#### Describe the solution

Limbified gaining Bird Wings
- Added `Changing Arms`, a pre-threshold bird/raptor trait that triggers a progression EoC every two hours - either printing a snippet, or triggering a custom dream while asleep with enough mutagen in your system and incrementing the generic changing limb timer variable
- `Changing Arms` turns into `Feathered Arms`, granting two feathered arms - they are slightly unwieldy and diverge from normal arms from the elbow down too much for armor coverage, but they don't get in the way too much - slightly debuffed balance score but better swim score, plus they are pretty.
- As long as you have bird mutagen in your system and either the bird threshold or no threshold your `Feathered Arms` will trigger a similar but longer progression EoC, priming for progression after three dreams (so at least 36h)
- Adjusted the scores of `Bird Wings` and fixed some weirdness - they were less likely to be hit than eyes, that sort of cleanup

Flight Adjustments
 - Trimmed the logic slightly and moved it over to use conditional flags
 - Removed pit resistance from WINGS_1 traits, those checks route through ´Character::can_fly´
 - Moved over to limb scores instead of absolute STR for the checks - small birds can still glide

Added a `Debug Genetic Instability` trait to facilitate "natural" mutation testing - it triggers the normal mutation roll every 5 seconds.

Limb Mod Fixage
 - Moved sublimbs into their own file, there will have to be a lot of them because of the armor/limb integration
 - Fixed a badly-written progression eoc leading to bug messages

#### Describe alternatives you've considered

Breaking out the sublimb stuff, but that's pretty formulaic and includes no changes beyond the new subs.

#### Testing

Gained the traits in normal play after the desired intervals using both normal mutagen and the debug mutation.
Raptor or non-bird thresed mutants don't get spammed by the messages.
Gliding works when unburdened, doesn't work when missing limb hp / over capacity / encumbered / winded.

#### Additional context

Part of #70703 and of the Limb Project.
1000 LoC of the diff is the sublimb movage.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Just so you know what I was thinking adding the fall reduction stuff to WINGS_1 and feathered arms specifically, I had come across some research suggesting that smaller theropods may have used their feathered arms to help control their falls, and that this may have paved the way for flight by giving the animals the ability to safely jump out of trees to escape danger or ambush.

Raptor doesn't have a lot going for it, so I figured giving it some minor vertical mobility would make it more interesting.

**Comment by Venera3** [comment]
You need to generate a lot of lift to cancel out *all* your (human-sized) momentum within the let's say 2m that are our pits - even gliding being equivalent is a stretch, given that that doesn't negate your momentum just turns it partly horizontal. 

> Raptor doesn't have a lot going for it, so I figured giving it some minor vertical mobility would make it more interesting.

That's still not really an argument - the end stage of categories gets to be like a human turning into the animal would be like, but they aren't magic in their function. You're not turning into a mouse-sized mouse, and you don't get to crawl into a 5cm opening because that's what mice do, for example.

**Comment by fairyarmadillo** [comment]
> That's still not really an argument - the end stage of categories gets to be like a human turning into the animal would be like, but they aren't magic in their function.

That's not the argument I was making. Going by your own example, a mouse mutant does not become 5cm, but they do become quite small and gain some advantages (and disadvantages) this way.

If human-sized feathered arms can't be good for anything, that's fine. I was just pointing out that there seems to be untapped design space in the line, and given that these were particularly mobile animals, that seemed to me at the time like a logical place to look for things that would make sense to give them.

WINGS1 was also not canceling all momentum, it was only reducing fall damage by one z-level. Again, no reason it has to do that, I'm just offering clarification about what I added. Maybe something like that would make more sense as its own trait that runs off of leg and bone mutations or something, if anyone wants to try to bring it back.

**Comment by Venera3** [comment]
That's canceling 4ms of falling (not to mention most of our falls being a single Z).
Ideally even glide-compatible wings would trigger a glide on fall instead of going "haha nope", but that's not a priority.

Re: design space - sure, but as it stands feathered arms is a prethresh trait meaning you can do a half-ton Cow mutant (no arm/hand mutations yet) and just slap on some feathers to get out of falling since there are no *absolute* weight limits on the checks.

**Comment by Maleclypse** [comment]
Clang is angry at wings

**Pull request merged**
