### PR TITLE
clear on f_null and apply it

### LINKED ISSUE #52747: Assignment of "f_null" in palettes does not have any effect
### Describe the bug

When defining terrain and furniture using palettes (at least for base camps/expansions) assigning "f_null" as the furniture for a palette character doesn't do anything, in particular it doesn't remove any furniture/"vegetation" in the tile.

This issue was originally submitted as #52544, but since further investigations have shown that it's probably undesirable to introduce a new token, and rather processing the existing one "properly" a new bug report was deemed better than replacing most of the contents of the original issue,

### Steps To Reproduce

1. Create a base camp/expansion blueprint using a palette that defines "f_null" as furniture for tiles.
2. Place the blueprint on top of terrain littered by boulders/trees/flowers.
3. See that it has no effect on the "furniture".

The easiest way is probably to add "f_null" as a furniture component for ";" in the version 2 field base camp or any of the version 2 expansions. You need to hunt around a little to find terrain where the modified palette should remove "furniture" (these base camp versions all provide an outline for where constructions will be placed by the base/expansion, so any "contaminant" on the dirt outline is an example of the issue).

### Expected behavior

Defining "f_null" should clear furniture in the designated tile, while not defining any furniture at all should leave existing furniture intact.

### Screenshots

One example, with some boulders and flowers inside a building. Note that this particular building wasn't constructed with "f_null" defined to clear "contaminants" (as it doesn't do anything), but illustrates why it's desirable to be able to do so.
Screenshot (89)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3764-gbcd626de5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Note that it is possible to work around the issue by rejecting the usage of a palette and define placement of "f_null" explicitly using "set" rather than "rows". It is uglier and requires duplication of designations if a terrain designation is needed as well, but it does get the job done.

Also note that it isn't related to usage of the "place_nested" referencing of a separate "nested_mapgen_id" as the issue remains when the "rows" definition is made "inline".

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

Bugfixes "Make f_null clear furniture when in palettes'"

#### Purpose of change

The context of this PR is construction blueprints (to make understanding what's discussed easier).
Fixes #52747 

When "f_null" was specified as "furniture" in palettes it did not do anything when that palette was applied to "rows". In contrast, direct usage of "f_null" in point, line, and square directives caused any "furniture" in those locations to be removed.

This PR makes the behavior the same in both situations. In addition to that, it applies the changed behavior to the base camp/expansions that needed the changed behavior in order to demonstrate the new behavior.

#### Describe the solution

Removal of three lines that explicitly did nothing when "f_null" was encountered, causing it to instead clear any "furniture" on the addressed tile.

Changed version 2 base camp and expansions to make use of "f_null" to clear the building site of boulders and "furniture" vegetation when marking the outline of the future constructions on the building sites.

Some "by-catch" was introduced:
- The base camp outline was changed to be generated using "rows" and a palette like the expansions. It's unknown why that didn't work when the base camp was constructed originally, as that approach was tested and failed at that time (specification of default terrain rather than nothing might have been the cause?).
- A number of expansions were detected to include redundant, unused "common" palettes. The unused version was removed in those cases.

#### Describe alternatives you've considered

Splitting this into two PRs: one for the code change and a single example of its use, and then an additional PR (or 6) to cover the rest of the usages. Each change is rather small, though.

#### Testing

Initiated construction of each of the artifacts on terrain that otherwise would leave boulders and flowers inside buildings to demonstrate that these "contaminants" get removed when the outlines are created.

#### Additional context

This PR will cause issues with furniture placement IF there is some case where the previous logic of "do nothing" was actively used to retain existing furniture when placing something on top and a range of options where "f_null" was intended to mean "don't replace" when several options were listed, rather than "I don't want anything here in this space, but keep it empty".
I find it unlikely this convoluted kind of stacking logic would be used.

The testing location before surveyed for base camp/expansion construction:
Screenshot (102)

Base camp version 2 outline (without boulders or plants in the "cleared" outline indicating future construction):
Screenshot (103)

Canteen version 2 outline:
Screenshot (104)

Storage version 2 outline:
Screenshot (105)

Workshop version 2 outline:
Screenshot (106)

Farm version 2 outline:
Screenshot (107)

Garage version 2 outline:
Screenshot (108)

Livestock version 2 outline:
Screenshot (109)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I don't agree there's any need for a "t_original", because the current, unchanged, functionality does exactly nothing when "t_null" is specified, because it doesn't make any sense to remove the terrain. Furniture, however, is different, as removing furniture doesn't leave a hole in reality. Thus, I can't see a use case for "t_original" (but I'm prepared to change that when someone with more imagination than me provides one).

The comment at line 30 of exodii_crashes.json isn't needed with this change, as "f_null" now clears "furniture", although I don't understand why there's two "f_null" instances: it ought to be sufficient with one, except for the wreckage case, where you may want wreckage half of the time, but this might be related to the bug referenced (there's explicit code to remove "furniture" from walls, but not from floors and doors, which may or may not be related to the bug mentioned).

As far as I can tell, the intention in that file is to generate a rubble strewn crash site and then generate buildings on it, with the rubble generated in the original step being replaced with the buildings but no rubble, which is exactly what this change does (assuming the palettes used actually contain the "f_null" specifications needed, and they do in this case).

Note that I don't have anything against "f_original", but I don't see any pressing need for it. Note that " " in the exodii_crash_ground_palette doesn't have a furniture entry, leaving those tile intact, and I don't think you'd want trees, shrubs, or plants to remain from the original terrain, but I'm prepared to be convinced here as well (in which case the original furniture should only peek out rather occasionally, with most cases cleared [and, in that case, you might want the original terrain to peek through as well, but the functionality doesn't allow you to tie the terrain alternative the RNG came up with to the furniture on it]).

**Comment by PatrikLundell** [comment]
The tests fail because some declarations in code I haven't touched are not in lexical order. Should I really change that code, or will it just complicate things further when it is merged with code that has performed the same changes but merged earlier?

**Comment by BrettDong** [comment]
> The tests fail because some declarations in code I haven't touched are not in lexical order. Should I really change that code, or will it just complicate things further when it is merged with code that has performed the same changes but merged earlier?

It is fixed in #52837, so the test will pass in the next run.

**Comment by PatrikLundell** [comment]
I doubt the changes in this PR has any effect on the monster_throw_sanity_test, so I assume that test is broken (either deliberately to "rarely" fail in regularly occurring edge cases, or due to an error that wasn't deliberately designed into the test).

(~[slow] ~[.])=> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(~[slow] ~[.])=> cata_test is a Catch v2.13.7 host application.
(~[slow] ~[.])=> Run with -? for options
(~[slow] ~[.])=> 
(~[slow] ~[.])=> Randomness seeded to: 1637051183
(~[slow] ~[.])=> 
(~[slow] ~[.])=> -------------------------------------------------------------------------------
(~[slow] ~[.])=> monster_throwing_sanity_test
(~[slow] ~[.])=> -------------------------------------------------------------------------------
(~[slow] ~[.])=> ../tests/monster_attack_test.cpp:174
(~[slow] ~[.])=> ...............................................................................
(~[slow] ~[.])=> 
(~[slow] ~[.])=> ../tests/monster_attack_test.cpp:228: FAILED:
(~[slow] ~[.])=>   CHECK( damage_dealt.test_threshold( epsilon_threshold{ expected_damage, 2.5 } ) )
(~[slow] ~[.])=> with expansion:
Error: (~[slow] ~[.])=>   false
(~[slow] ~[.])=> with messages:
(~[slow] ~[.])=>   expected_damage := 3.25f
(~[slow] ~[.])=>   distance := 5
(~[slow] ~[.])=>   Hit rate: 0.72
(~[slow] ~[.])=>   Avg total damage: 4.58
(~[slow] ~[.])=>   Dmg Lower: 3.27346 Dmg Upper: 5.88654
(~[slow] ~[.])=> 
(~[slow] ~[.])=> Log messages during failed test:
(~[slow] ~[.])=> 5:46:38 AM: You eat your holy SPAM of debugging (fresh).
(~[slow] ~[.])=> 5:46:38 AM: You start walking.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the left arm for 7 damage.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the torso for 7 damage.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the torso for 5 damage.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the torso for 12 damage.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the right arm for 9 damage.
(~[slow] ~[.])=> 5:46:38 AM: The feral human throws a rock!
(~[slow] ~[.])=> 5:46:38 AM: You were hit in the torso for 10 damage.
...

**Comment by jbytheway** [comment]
For consistency, I'd be much happier if `f_null` did nothing, and we had some special way to clear furniture.  I feel it's confusing for `f_null` to clear furniture when null values for all the other mapgen objects (terrain, monster,s items, etc.) simply do nothing.

When thinking about this issue in the past I had imagined that we would have some separate mapgen instruction specifically to clear things, but if it's easier we could make a magic value like `f_clear` to clear furniture in the furniture entry.  I'm happy to defer to people who actually make maps as to what makes the most sense, I just don't think it should be `f_null`.

**Comment by PatrikLundell** [comment]
It can be noted that "f_null" clears furniture when provided by point, line, and square directives (and "t_null" likewise makes holes in the terrain, which I believe I've seen being used for some unknown reason before writing a new terrain value).
Thus, it's possible to use existing functionality to remove unwanted "furniture" as long you use don't use the palette/rows combination (for that purpose)., so I'm able to achieve what I want for base camps/expansions with only mildly ugly changes (which would happen to rely on my desire to clear the ground first and build on it later: it would be a fair bit more work to use it in the building construction blueprints themselves).

So, there seems to be essentially three options:
a. Proceed with this PR (seems the enthusiasm is rather limited at this stage)
b. Replace this PR with the introduction of an "f_clear" token and introduce handling of it everywhere it's needed, which, among other things, means ensuring it's never actually used as on the map itself (with follow up PRs that deal with cases missed originally). Conversion of existing maps to use the new functionality would have to be separate PRs (both because of the volume and because of limited understanding of what the original intentions for those maps were).
c. Withdraw this PR and introduce a new one that only deals with my "private" base/expansion cases using existing functionality.

**Comment by PatrikLundell** [comment]
Closing, as #52865 provides a better implementation.

**Pull request closed without merging**
