### PR TITLE
Open multiple containers in Advanced Inventory Manager

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Interface "Open multiple containers in Advanced Inventory Manager"

#### Purpose of change
The Advanced Inventory Manager can open one container, yes.  But what about _second container_?

#### Describe the solution
When viewing a container in AIM, pressing the "Select items in container" key will actually open a second container and allow you to transfer items between them.  Moving that ring between your pocketses have never been easier.

#### Testing
Opened various containers including nested ones in both panes of the AIM.  Transferred some items around as well.  No problems so far.

#### Additional context
Some hacky solutions are involved, someone familiar with the AIM code might want to take a look just in case.

### CODE REVIEW

**Comment by Kamayana** [comment]
Fantastic! I fixed the container view some months back and this was a followup I wanted to get to eventually, glad to see it. I'll take a look through it.

**Comment by Kamayana** [comment]
Oh shoot, this got merged while I was writing up the adjustments I was going to suggest. I guess I'll make a separate PR instead.

**Comment by dseguin** [comment]
Woops! Please do, I'll review it once it's ready

**Comment by Kamayana** [comment]
It's alright, gives me a reason to add some more substantial changes I was contemplating as well

**Comment by mryellow** [comment]
Thankyou all!

My enjoyment of the game was greatly impacted by AIM container UX.

**Pull request merged**
