### PR TITLE
Fix reinforced_glass_sheet recipe weight and volume inconsistency

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
Content "Fix reinforced_glass_sheet recipe weight and volume inconsistency"

#### Purpose of change
Fixes [#62218](https://github.com/CleverRaven/Cataclysm-DDA/issues/62218)

#### Describe the solution
According to the recipe, 4 reinforced_glass_pane make one reinforced_glass_sheet. I did the math, that the volume and weight of reinforced_glass_pane times 4 produce the volume and weight of the reinforced_glass_sheet.

#### Describe alternatives you've considered
1. Leave as is. This is not optimal.
2. Modify the recipe into 12 reinforced_glass_pane making one one reinforced_glass_sheet. This avoids modifying the volume and weight of reinforced_glass_sheet.

#### Testing
Create a world, and find everything working fine, all the vehicle things and recipe things.

#### Additional context
None.

### CODE REVIEW

**Comment by SurFlurer** [comment]
I'll find out what is failing the tests first.

**Comment by SurFlurer** [comment]
I see that modifying weight will lead to conflict with the hard-coded vehicle-test data. Maybe update those data? Or should I choose alternative No.2?

**Comment by Karol1223** [comment]
> I see that modifying weight will lead to conflict with the hard-coded vehicle-test data. Maybe update those data? Or should I choose alternative No.2?

Are you sure they are hardcoded? I brought up the issue of not being able to modify them previously when I altered the rockwheel and I am 99% sure they have been jsonified since. I'll take a look around to see if there isn't a non-hardcoded list you can edit

**Comment by SurFlurer** [comment]
> The vehicle efficiency test is something entirely different that I know nothing about, though, and it may be hardcoded...

According to /tests/vehicle_efficiency_test.cpp:
```
TEST_CASE( "vehicle_efficiency", "[vehicle] [engine]" )
{
    test_vehicle( "beetle", 707777, 399680, 358994, 110952, 91402 );
    test_vehicle( "car", 1011976, 555111, 399360, 60344, 30655 );
    test_vehicle( "car_sports", 998322, 336539, 283905, 41326, 30440 );
    test_vehicle( "electric_car", 698493, 209563, 182602, 17265, 14957 );
    test_vehicle( "suv", 1246644, 1050949, 630063, 90148, 34734 );
    test_vehicle( "motorcycle", 173585, 109802, 87649, 57566, 44497 );
    test_vehicle( "quad_bike", 275845, 107440, 107440, 44021, 44021 );
    test_vehicle( "scooter", 60441, 200399, 195512, 150909, 147555 );
    test_vehicle( "superbike", 231585, 103010, 65307, 41575, 24945 );
    test_vehicle( "ambulance", 1716993, 562028, 498800, 81698, 68622 );
    test_vehicle( "fire_engine", 2096246, 1844300, 1844300, 419617, 419617 );
    test_vehicle( "fire_truck", 6185223, 398080, 88578, 19710, 4700 );
    test_vehicle( "truck_swat", 6501129, 600602, 93345, 27794, 5999 );
    test_vehicle( "tractor_plow", 742658, 582058, 582058, 125043, 125043 );
    test_vehicle( "apc", 5919120, 1512911, 1042420, 123904, 79286 );
    test_vehicle( "humvee", 5980330, 676881, 284910, 23790, 7337 );
    test_vehicle( "road_roller", 9055909, 542552, 132476, 21598, 6925 );
    test_vehicle( "golf_cart", 319630, 50080, 47850, 22925, 12889 );
    // in reverse
    test_vehicle( "beetle", 707777, 58800, 58800, 45900, 44560, 0, 0, true );
    test_vehicle( "car", 1011976, 76390, 76260, 48330, 30270, 0, 0, true );
    test_vehicle( "car_sports", 998322, 355300, 288600, 38670, 24580, 0, 0, true );
    test_vehicle( "electric_car", 698443, 373700, 231800, 25070, 14310, 0, 0, true );
    test_vehicle( "suv", 1246644, 114900, 112400, 70400, 35200, 0, 0, true );
    test_vehicle( "motorcycle", 173585, 20070, 19030, 15490, 14890, 0, 0, true );
    test_vehicle( "quad_bike", 275845, 19650, 19650, 15440, 15440, 0, 0, true );
    test_vehicle( "scooter", 60441, 58790, 58790, 46320, 46320, 0, 0, true );
    test_vehicle( "superbike", 231585, 18380, 10570, 13100, 8497, 0, 0, true );
    test_vehicle( "ambulance", 1716913, 58600, 57910, 42480, 40260, 0, 0, true );
    test_vehicle( "fire_engine", 2096246, 257400, 257100, 185600, 179400, 0, 0, true );
    test_vehicle( "fire_truck", 6185223, 58700, 58860, 19630, 4471, 0, 0, true );
    test_vehicle( "truck_swat", 6501129, 129900, 130900, 26920, 5308, 0, 0, true );
    test_vehicle( "tractor_plow", 742658, 72490, 72490, 53700, 53700, 0, 0, true );
    test_vehicle( "apc", 5919120, 382000, 382600, 123100, 82750, 0, 0, true );
    test_vehicle( "humvee", 5980330, 89490, 89490, 24180, 7595, 0, 0, true );
    test_vehicle( "road_roller", 9055909, 97090, 97190, 22880, 6545, 0, 0, true );
    test_vehicle( "golf_cart", 319630, 96150, 28800, 35560, 11150, 0, 0, true );
}
```
The first number in each line is the expected total weight of the vehicle.

**Comment by SurFlurer** [comment]
Editing vehicle-part data seems to need to regenerate some test data. Is there any easy way to do it? May I use the actual test cases results to replace the test data?

**Comment by mqrause** [comment]
You can execute the `make_vehicle_efficiency_case` test to generate the test data or just copy the numbers from the failed cases. If you don't want to touch the cpp files, you can wait for #63088 to be merged to do it in json.

**Comment by SurFlurer** [comment]
@mqrause Thank you for your work! Although I can handle the cpp part, I'll wait until your PR gets merged.

**Pull request merged**
