### PR TITLE
Chemistry proficiences continued #1

### PR DESCRIPTION
**Pull request by Alm999**
#### Summary
Balance "Another batch of chemistry proficiencies  added to recipes"

#### Purpose of change

This PR extends https://github.com/CleverRaven/Cataclysm-DDA/pull/64107 in order to add chemical proficiencies to more general recipes.

#### Describe the solution

The principle of addition is this:
1. if a recipe requires any manipulation on chemical stuff -> "Principles of Chemistry";
2. if a recipe mandates operations on inorganic substances (saltpeter, lye, even salt water counts) -> "Inorganic Chemistry";
3. if a recipe needs organic substances (benzene, citric acid, even ethanol counts) -> "Organic Chemistry" (substances need not to be complex, just being a product of hydrocarbons counts);
4. if any distillation process is required (both normal and "fine" variants) -> "Distillation" (maybe adjusting for difficulty of fine distillation is needed as a time modifier);
5. if a product of a recipe is not an "end product" (like "superglue") but intended to be used as an ingredient for more complex chemical synthesis -> "Principles of Chemical Synthesis";
6. for any high level mutagens -> "Complex Chemical Synthesis";
7. if a product is a drug meant for consumption -> "Pharmaceutical Production";
8. if a recipe requires any manipulation on a (recently) living creature including chemical extraction from its internal organs -> "Biochemistry".

#### Describe alternatives you've considered

None.

#### Testing

Texted in-game. Proficiencies successfully added.

I think, still not recipes are reviewed, so maybe another round(s) is/are in order.

#### Additional context

None.

### CODE REVIEW

**Comment by Alm999** [comment]
Great. Now there are two PRs. I guess I don't know what I'm doing. :(
Somebody, help me!

**Review by Venera3 — COMMENTED** [review]
> for any high level mutagens -> "Complex Chemical Synthesis";

This needs to be its own thing, mutagen are a separate anomalous field not Chemistry Plus.

> if a recipe requires any manipulation on a (recently) living creature including chemical extraction from its internal organs -> "Biochemistry".

I'd recommend something like "Natural Products/Extracts", biochemistry is both too broad and included in Pharma

**Comment by Alm999** [comment]
> > for any high level mutagens -> "Complex Chemical Synthesis";
> 
> This needs to be its own thing, mutagen are a separate anomalous field not Chemistry Plus.
> 
This may be true. But I'm working with existing Proficiencies right now (mainly from the ./data/json/proficiencies/chemistry.json).
Could not find anything specifically related to mutagen production, so I thought gating mutagens behind high levels of chemistry (AKA "applied science") skill and secret nearly unobtainable manuals is harsh enough.
Maybe in the future there will be dedicated proficiencies like "Virology", "Microbiology", "Biotechnology" and other scary medical words. ;)

> > if a recipe requires any manipulation on a (recently) living creature including chemical extraction from its internal organs -> "Biochemistry".
> 
> I'd recommend something like "Natural Products/Extracts", biochemistry is both too broad and included in Pharma
Biochemistry is another oddball, serving both as a Weakpoint and Production prof. Its' description states: "The understanding of the chemistry of living things."

Medical stuff is generally broad in C:DDA. For proper medical education we'll need "Anesthesiology", "Immunology", "Infectious Diseases", "Medical Diagnosis", "Neurology", "Parasitology", "Pharmacology", "General Surgery" (and all of its sub-classes and derivatives like "Cardiac Surgery" and "Neurosurgery") and so on. Medical sciences are a hell to learn and even harder to master.

What we have right now is "Physiology", both a pride of the MD ("medical doctors", I believe) and basically just a fancy name for "Human Anatomy" (because ingame it is just that) gated behind additional "moral penalties" in order to make it harder to learn (to promote MD backgrounds, I believe).

"Pharma" is a direct opposite to "Biochemistry", IMO. Instead of extraction from a body (or general knowledge where crucial glands are located), "Pharmaceutical Production" ensures resulting substances are safe for *infusion* into said body.

Maybe someone with medical background will clear all this mess. I myself is more of combustion and chemical kinetics guy.

**Comment by Alm999** [comment]
OK, this is a mess. I'm closing this PR and collapsing all proposed changes into https://github.com/CleverRaven/Cataclysm-DDA/pull/64107 (making that a draft, as the work is obviously not done yet).

**Pull request closed without merging**
