### PR TITLE
Gun Additions Part 1

### PR DESCRIPTION
**Pull request by Epictyphlosion**
It's been awhile since I made any contribution to the game, so I decided to come back in style!
This is the first part of my gun additions, how many there will be, I'm not sure, but there will be more in the future! This one adds some guns from WWII, as well as one very special one from modern day...

### CODE REVIEW

**Comment by Epictyphlosion** [comment]
Damn, I completely forgot to add the guns into the item group file. A rookie mistake I made with my first contribution! Fixing it now

**Comment by I-am-Erk** [comment]
I don't mean to offend, but do we really want *more* guns in core? It's already hard to find magazines and ammo for the guns we do have, this is likely to further discourage use of guns by adding still more magazines you can't find guns for and vice versa.

Perhaps this would be better off added to the realguns mod?

**Comment by NotFuji** [comment]
This kind of thing might be more at home as an addition to the realguns mod instead of a base game addition, there's already an overabundance of firearms for most players' tastes

Also, there's no need to add a specific magazine for the MP 40s, the STEN already uses the same magazine.

The StG 44 magazines are incorrectly labeled as STG44

The replica M3 entry is missing a comma

It's not recommended to increase durability past 9, which only has a 1/1024 chance of failure, and really isn't warrented to have WWII firearms that high.  If you want an utmost durability weapon (which you shouldn't for any of the weapons here) use the "NEVER_JAMS" flag instead.

**Comment by Epictyphlosion** [comment]
@I-am-Erk @NotFuji 
Thanks for the feedback!
I'll close this PR for now, polish the code, and put it into the Realguns mod next time around.
I'll also get to playing the latest experimental when I get home, I've been really out of touch with this game, so I don't know whether what I want to add is needed or not. At the same time, I tend to have a "the more stuff, the better" type of mindset when it comes to games, lol.

**Comment by kevingranade** [comment]
Just a clarification, any guns that it would be reasonably likely to come
across in modern day new england are fine to add to the base game.  My
priority is attempting to have representative numbers of various guns
rather than avoiding having too much variety.

**Pull request closed without merging**
