### PR TITLE
Remove manual text wrapping in the definition of NPC epilogues

### PR DESCRIPTION
**Pull request by illi-kun**
We have a possibility to wrap text to window size automatically, no need to do it manually. I guess that translators have a lot of other work.

Inspired by #20587. 

WIP for now because ~~json file is quite big to process it at once, and also~~ I have to update Python script for proper extraction of updated lines from json file.

~~Maybe a single string of epilogue will be converted back to a vector of strings for separation of paragraphs of epilogue, I'll think about it (a bit later).~~ (not now)

### CODE REVIEW

**Comment by illi-kun** [comment]
Example of updated epilogue window:

npc-epilogue_example

**Comment by illi-kun** [comment]
It's ready for review.

**Comment by ZhilkinSerg** [comment]
How do I get these epilogue windows?

**Comment by AMurkin** [comment]
`disp_NPC_epilogues()` called by `void game::death_screen()`
So, `Q y y` when have some factions at `#` screen.

**Pull request merged**
