### PR TITLE
Updated MSVS windepend.prop for SDL 2.0.5

### PR DESCRIPTION
**Pull request by kolsurma**
updated SDL2ROOT to new version

### CODE REVIEW

**Comment by kevingranade** [comment]
Does this change the minimum version of SDL for VS builds? If it's just to fix the SDL_Hint thing, that should be adressed by #21168 
I don't build on VS though, so you VS users need to tell me which build you prefer (and which one fixes things).

**Comment by AlecWhite** [comment]
>I don't build on VS though, so you VS users need to tell me which build you prefer (and which one fixes things).
https://github.com/CleverRaven/Cataclysm-DDA/pull/21168 fixes it but this to fix it would need to update too the dependencies given in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md  which are /COMPILING.md  http://dev.narc.ro/cataclysm/WinDepend-MSVC.zip and http://dev.narc.ro/cataclysm/WinDepend-MSVC.7z. .

That or modify COMPILE.md to warn that you need to manually update SDL 2.0.4.

**Comment by kevingranade** [comment]
I'm not sure I want to bump the required version of SDL specifically for this issue, basically if you want the GDB fix you need to build with more recent SDL, but otherwise the earlier one is fine.

**Comment by kolsurma** [comment]
Okay, fair enough. The information about GDB fix should be added to COMPILING.md in that case.

**Pull request closed without merging**
