### PR TITLE
Animal husbandry

### PR DESCRIPTION
**Pull request by RafeHaab**
Domesticating/capturing horses to be useful as mounts. There would be easier to mantain (feed), but slower than cars.

### CODE REVIEW

**Comment by macrosblackd** [comment]
This needs to be pushed to master, not a specific branch.

**Comment by tyrael93** [comment]
I think there might have been an error here

**Comment by illi-kun** [comment]
Should be related to #3107.

**Comment by Rivet-the-Zombie** [comment]
Cool idea, but there's some **major** Git errors in here.

**Comment by narc0tiq** [comment]
There's nothing in here at all related to horses or animal husbandry -- this is a request to merge the CleverRaven `0.C-branch` into its `0.8-branch`, which is not going to happen. Similarly, it looks like @RafeHaab has no fork of Cataclysm-DDA, so I couldn't even tell you what the correct pull request should be. In any case, this one won't happen.

**Comment by Rivet-the-Zombie** [comment]
Oh wow, now that I've actually opened the changes (trying to do so on my phone made Firefox crash) I can see that this is a trainwreck of a PR.

I think @RafeHaab meant to open this as an issue so as to suggest a change.

**Comment by RafeHaab** [comment]
I'm sorry. It is the first time I use github. I'm pretty much in dark here.

**Comment by narc0tiq** [comment]
No worries, it's easy enough to fix. But if it was a suggestion, then -- as
noted above -- we do have it on the wishlist.

For future reference, there should be a nice shiny green button labeled
"New Issue" on http://github.com/CleverRaven/Cataclysm-DDA/issues -- with a
search box near it so you can check if it already exists.

**Comment by RafeHaab** [comment]
I'm sorry for causing trouble. When I searched, I did not find anything related to horses.

**Comment by Rivet-the-Zombie** [comment]
It's no trouble. Consider this a learning experience!

**Pull request closed without merging**
