### PR TITLE
Normalize gun recoil [WIP]

### PR DESCRIPTION
**Pull request by mugling**
#### Problem

It is currently impossible to compare ammo via `recoil` as values are incorrectly scaled around zero.
#### Solution
- Ammo always produces recoil (positive sign, `recoil >= 0`)
- Guns always offset recoil (negative sign, `recoil <=0`)

For example `454` ammo has  a JSON `recoil +650` but effective `recoil +710` as the only gun to use that ammo also specifies `+60`. This is more clearly expressed in 5ea662e as the ammo having a recoil of 710 and the gun providing no bonus. 

This PR rescales the values one type per commit without introducing any changes except where `copy-from` is used to derive a variant in a different caliber (for example `Ruger LCR .22` vs `Ruger LCR .38`. Non-regression can be verified via:

```
./cataclysm --dump-stats GUN > gun.tsv
git pull ...
./cataclysm-tiles --dump-stats GUN | gun.tsv -
```

Marked `WIP` as conflicts with #17385 and needs the dumper fixes from #17415

Future extension is likely to include deriving ammo `recoil` values from IRL data and then the gun bonuses via their weight and number of contact points.
#### Balance

This PR does not intend to address balance but for interest normalized values for recoil. Correct scaling allows identification of some obvious balance problems (for example conside `700nx`)

| Name | Recoil |
| --- | --- |
| .22 rat-shot | 49 |
| .32 ACP | 90 |
| .22 CB | 99 |
| RA110 5x50mm flechette | 110 |
| RA119 5x50mm penetrator | 125 |
| .22 LR | 165 |
| .22 FMJ | 165 |
| 4.6x30mm | 180 |
| 7.62x25mm JHP | 195 |
| .38 Special | 215 |
| .38 FMJ | 215 |
| 9x18mm RG028 | 245 |
| 9x18mm 57-N-181S | 245 |
| H&K 12mm | 255 |
| 9x18mm SP-7 | 275 |
| .38 Super | 275 |
| 9x19mm JHP | 285 |
| 9x19mm FMJ | 285 |
| 9x19mm +P | 315 |
| 9x19mm +P+ | 345 |
| .40 S&W | 350 |
| .40 FMJ | 350 |
| 10mm Auto | 410 |
| .45 ACP JHP | 420 |
| .45 ACP FMJ | 420 |
| 7.62x39mm M67 | 480 |
| 7.62x39mm M43 | 480 |
| .45 ACP +P | 480 |
| 40mm teargas | 495 |
| 40mm smoke cover | 495 |
| 40mm incendiary | 495 |
| 40mm frag | 495 |
| 40mm flashbang | 495 |
| 40mm flare | 495 |
| 40mm concussive | 495 |
| 40mm beanbag | 495 |
| .44 Magnum | 500 |
| .44 FMJ | 500 |
| .223 Remington | 570 |
| 7.62x54mmR | 575 |
| 5.56 NATO tracer | 610 |
| 5.56 NATO M855A1 | 610 |
| .500 S&W Magnum | 630 |
| .308 Winchester | 640 |
| .300 Winchester Magnum | 645 |
| 7.62x51mm M80 | 680 |
| 7.62 NATO tracer | 680 |
| .454 Casull | 710 |
| .700 NX | 750 |
| .270 Winchester | 750 |
| .30-06 Springfield | 770 |
| .30-06 M2 AP | 770 |
| .30-06 M14A1 tracer | 770 |
| 40mm flechette | 795 |
| 40mm buckshot | 795 |
| .50 BMG Ball | 975 |
| .50 BMG API | 975 |
| .50 BMG AP | 975 |
| blunderbuss slug | 1130 |
| blunderbuss shot | 1130 |
| blunderbuss flechette | 1130 |

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Guns always offset recoil (negative sign, recoil <=0)

> For example 454 ammo has a JSON recoil +650 but effective recoil +710 as the only gun to use that ammo also specifies +60. This is more clearly expressed in 5ea662e as the ammo having a recoil of 710 and the gun providing no bonus.

Not sure if it makes sense to always normalize recoil for guns like that.

When someone adds a new gun of a given type with worse accuracy, it will require either breaking the normalization or renormalization of all other guns of said type.
Additionally it doesn't allow easy switching between ammo types, as recoil now carries some information about the default ammo type. For example, if you mod a gun from high variance recoil ammo type to a low variance one, it will keep the advantageous recoil.

How about making it approximate some physical quality of the gun instead?
Say, only makeshift (pipe) guns get 0 recoil compensation, everything else goes down from there. Above 0 compensation would imply some major shenanigans like heavy damage to the gun causing it to recoil to the side or something.
That way the "json formula" becomes
```ammo_recoil - gun_recoil```
instead of
```ammo_recoil + min( all_gun_recoils ) - ( gun_recoil - min( all_gun_recoils ) )```

**Comment by mugling** [comment]
> For example, if you mod a gun from high variance recoil ammo type to a low variance one, it will keep the advantageous recoil.

> How about making it approximate some physical quality of the gun instead?

The guns recoil bonus shouldn't be coupled to the ammo used but based instead upon it's intrinsic properties, especially `weight`. Converting a heavy `308` rifle to `22` should as a byproduct result in excellent control of recoil.

> When someone adds a new gun of a given type with worse accuracy, it will require either breaking the normalization or renormalization of all other guns of said type.

That's confounding `dispersion` and `recoil`. The latter should be based upon intrinsic properties and then scaled by a modifier based upon subjective factors (especially points-of-contact), for example a pistol should be modifier `1.0` whereas smg `1.5` and rifle `2.5` as the latter is easier to control.

Values less than 1.0 could be used for particularly poor examples (eg. pipe rifles at 0.5). This should avoid any problems with requiring further rebalances.

Gun mods that control recoil then add to the modifier - for example a forward grip adds `+0.3`

**Comment by kevingranade** [comment]
I agree with Coolthulu, if you're normalizing recoil values around what happens to be the lowest-recoil weapon, you're subject to a new lower-recoil weapon being introduced for that ammunition and throwing off your normalization, which means the effects of this PR are temporary.  I think Coolthulu just mistyped dispersion instead of recoil.

What you're looking for I think is some theoretical "worst possible recoil handling", or possibly a "best possible recoil handling" that models the kinematics of the weapon, which would effectively be a multiplier* on the force exerted on the gun by the firing process.  (note this is not equivalent to muzzle energy, but it might be close enough).

*Whoops, not a multiplier, it would be a possibly-linear equation (or close enough to model it as such) that turns force into effective recoil, to illustrate a very simplified model is something like ( ("inertial moment" * "force of propellant" ) / "mass of gun" ) - "recoil compensation" - ( "handling characteristics" * "shooter strength" * "shooter skill" ).  In other words, force is applied to the gun along the axis of the barrel, which is usually slightly offset from the axis along which force is transferred into the shooter, this offset generates muzzle climb, but is damped by the mass of the gun, it's also potentially directly countered by a muzzle brake or other active recoil management systems, in addition handling characteristics of the gun may allow a shooter of sufficient strength and skill to cancel it out.

If something like that can be reduced to maybe two parameters per gun to plug into that function (not counting muzzle energy), great, but I'm not clear how this change gets us any closer to that.

**Comment by mugling** [comment]
Too deviated from `master` to merge

**Comment by Zireael07** [comment]
Will you revisit the idea though?

**Comment by mugling** [comment]
Yes, I want to calculate recoil from `GUN:weight` and `AMMO:damage` and then allow `GUN` and `GUNMOD` to specify a percentage modifier. For example folding stock would be +10% and adjustable stock would be -15%.

This is likely to be the next thing I work on after #17962 as the two ideas have good synergy.

**Comment by BorkBorkGoesTheCode** [comment]
> Yes, I want to calculate recoil from  GUN:weight  and  AMMO:damage  and then allow  GUN  and  GUNMOD  to specify a percentage modifier. For example folding stock would be +10% and adjustable stock would be -15%.

How will you handle hollowpoint damage bonuses?

**Comment by Rivet-the-Zombie** [comment]
An excellent point; higher damage does not always mean more powerful propellant in the cartridge.

**Pull request closed without merging**
