### PR TITLE
Rename Disinfectant to Antiseptic

### LINKED ISSUE #33368: "Disinfectant" should be called "Antiseptic"
# Describe the bug

On current master, "disinfectant" is used to clean wounds. Medically speaking, this is a bad idea -- a disinfectant is typically a strong solution of some biocide, intended for disinfecting *nonliving* surfaces like railings, tables, or scalpels. Using it on an open wounds will likely cause tissue damage and hurt more than it helps.

The stuff that you use to disinfect open wounds is called *antiseptic*, a much weaker solution that's safe for human consumption. Yes, this is pointlessly confusing, but hey, that's English.

In the game currently, "disinfectant" actually behaves like antiseptic. The closest thing to an actual disinfectant in the game is probably the concentrated hydrogen peroxide you find in labs.

([Source](https://www.healthline.com/health/what-is-antiseptic). Also, the [wiki](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Disinfectant) has a note about this.)

# Expected behavior

I'd suggest renaming the current "disinfectant" item to "antiseptic".

Downside is this might confuse players just for the sake of realism, but that's sorta this game's MO so I think it's worth it.

As an extension, disinfectant could also be added back in, perhaps as a cheaper but less effective alternative to autoclaves. If the game did more tracking of filth on tiles or the player, it could also be used to clean that off, but I don't know if that's a feature anyone's clamoring for.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

```SUMMARY: Interface "Rename Disinfectant to Antiseptic"```

#### Purpose of change
Fixes #33368 

#### Describe the solution
Rename disinfectant to antiseptic
Update all help txt to use antiseptic
Since we don't actually disifect anything, and all our disinfectant is useable as antiseptic replace disinfectant with antiseptic in description of ethanol, bleach, hydrogen peroxide etc...

#### Describe alternatives you've considered
Only changing names.

#### Additional context
I'm not entierly satisfied with discribing ethanol as an antiseptic as it seems to be a bad idea to use it this way. 
Strond disinfectant damage the tissue and actually slow the healing process but we don't model that so I put antiseptic to be consistant for the players.

### CODE REVIEW

**Comment by ampersand55** [comment]
> 
> I'm not entierly satisfied with discribing ethanol as an antiseptic as it seems to be a bad idea to use it this way.

Is it? Most hand sanitizers are 60-70% ethanol.

**Comment by Fris0uman** [comment]
Yeah and you're not supposed to put that on an open wound.

**Comment by ampersand55** [comment]
Fair enough.

**Comment by Moonsabrt** [comment]
> Fair enough, but the same is true for hydrogen peroxide.

Wait, wait, WAIT your NOT supposed to put hydrogen peroxide on cuts and wounds?
.....Uh oh

**Comment by Fris0uman** [comment]
So there might different concentration of the stuff or whatever, but yes peroxyde hydrogen probably also burn tissue.  But like I said we don't currently take that into account and using it for cleaning wound is very common practice, same for alcohol actually

**Comment by ampersand55** [comment]
> > Fair enough, but the same is true for hydrogen peroxide.
> 
> Wait, wait, WAIT your NOT supposed to put hydrogen peroxide on cuts and wounds?
> .....Uh oh

Under normal circumstances you're not supposed to use any hard antiseptic to clean an open wound. Best to rinse it it with a sterile saline solution or clean it with soap and water, and then apply a antibiotic cream such as a [Neosporin](https://en.wikipedia.org/wiki/Neomycin/polymyxin_B/bacitracin).

But if there is some really nasty zombie bacteria that you need to kill, it's might be advisable to use a hard antiseptic between cleaning the wound and applying the antibiotic cream. It's sometimes recommended for rabies wounds.

* https://advancedtissue.com/2015/07/the-best-and-worst-ideas-for-open-wounds/
* https://www.ccohs.ca/oshanswers/diseases/rabies.html

**Pull request merged**
