### PR TITLE
Removed MOUNTED_GUN from M134 and increased UPS power drain

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Now uses a full UPS to fire 100 shots if used unmounted.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
100? Is there some multiplier on those charges?

**Comment by BorkBorkGoesTheCode** [comment]
"ups_charges": was set to 10 per shot, which should empty a UPS filled with 1,000 battery power.

**Comment by kevingranade** [comment]
Rationale for making it unmounted? It's ludicrously impossible to do so.
I might be misremembering what the implications are though.

**Comment by kevingranade** [comment]
Minigun is pretty much the quentissential "must be fired from a mount" gun, closing.

**Pull request closed without merging**
