### PR TITLE
Reduces portions for biscuits.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
It's been pointed out multiple times that biscuits are better than just
about any other food in the game. After some testing, I have to agree.
This knocks them down to a more reasonable level.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good thinking, but now they're noticeably worse than johnnycake (1 flour + 1 oil -> 6*20 nutrition + 4 fun).
Nerf that one too? It would be great if they were nerfed in different ways, so that one had more nutrition (per ingredient) while the other used more common, lower quality resources.

**Comment by facepalm** [comment]
Why do johnnycakes use flour and oil at all?  They're cornmeal and water/milk based, like a simple kind of cornbread... which are  themselves just corn and water, apparently?  No milk, no sugar, no oil?

Who added these recipes?  Did they actually look them up beforehand?

**Comment by Coolthulhu** [comment]
In Australia and Dominican Republic, they have a variant of johnnycake that is made from flour rather than cornmeal and without milk.

**Comment by facepalm** [comment]
Maybe, but we're not in Australia.  And a good thing too, considering how big and poisonous their insects are already...

**Comment by KA101** [comment]
Well, for folks who don't aggressively seek out the cracks, this'll change things up.  We can sort out johnnycake shortly.

**Comment by Rivet-the-Zombie** [comment]
>Why do johnnycakes use flour and oil at all?

The oil is for frying them in. Makes them crispy and delicious!

>Who added these recipes? Did they actually look them up beforehand?

I did. And not only have I looked them all up, I've cooked them in real life, too.

**Comment by facepalm** [comment]
>The oil is for frying them in. It makes them crispy and delicious!

I was under the impression that small amounts of ingredients were generally disregarded in recipes to save on fuss.  Baking soda or powder, teaspoons of salt and sugar, eggs in most things, a tablespoon of oil, etc.  You don't _deep fry_ the things, do you?

**Comment by Coolthulhu** [comment]
> You don't deep fry the things, do you?

You do, at least in one of the variants.

**Comment by facepalm** [comment]
Then why isn't it flagged "junk food" and give crap nutrition, like the fried chicken and the french fries?

**Comment by KA101** [comment]
>Actually, that makes me wonder if it would be possible to have a "zero use" ingredient

Sure, just file it as a component instead.

And in the US, I'm sure you can get deep-fried anything if you look hard enough.  Deep-fried candy bars aren't unknown, FFS.

**Comment by facepalm** [comment]
Deep-fried candy bars are good.  Deep-fried ice cream is surprisingly workable.

I'd stay away from the deep-fried margaritas, though.  It does not work as well as the ice cream.

**Comment by KA101** [comment]
Yeah, that should be "tool" rather than "component".  >_<

**Comment by Rivet-the-Zombie** [comment]
>Actually, that makes me wonder if it would be possible to have a "zero use" ingredient. As in, you'd have to have cooking oil available for a recipe, it just wouldn't use up enough to merit an entire unit of volume.

We've already got a couple recipes that work like this. I believe fried fish is one of them; you just treat the cooking oil as a tool rather than a component, like KA101 said.

>Really. How did the cornbread made from cornmeal and water turn out? ;)

These recipes are all terribly simplified. If you'd like some actual examples of my cooking, I suggest you read our [community cookbook](http://smf.cataclysmdda.com/index.php?topic=9011.msg204561#msg204561).

**Pull request merged**
