### PR TITLE
Dragon skin changes

### PR DESCRIPTION
**Pull request by Brian-Otten**
Changed dragon skin armor to better match its real life counterpart.

#### Summary
```SUMMARY: Balance "Rebalances dragon skin to better fit its real life counterpart"```

#### Purpose of change
Changes dragon skin armor to be a heavier, slightly less protective, and non sturdy variant of the mbr (ceramic plates).
Before this it was a lightweight, low encumbrance, outer vest. one of the best pieces of armor in the game. It should be similar to, but not as good, as the military version of the same thing, as it is in real life.
#### Describe the solution
Increase it's weight and encumbrance, increase it's armor values. remove the sturdy flag. Change the flavor text.
#### Describe alternatives you've considered
Removing dragon skin armor from the game.
Leaving dragon skin as it is, which is different from what you would expect in real life.
Matching i's weight and performance as exactly as possible to its real life performance rather than fitting it into the current armor system.

#### Testing
Spawned the armor, checked that it's values were all correct, wore the armor, spawned some zombies to check for weird interactions.

#### Additional context
image
Additionally, this PR should not be merged before #36853 , because it should make the armor a weaker version of the mbr(ceramic plates) found in that PR. If that PR is closed i can adjust this one so the armor values are slightly below the old mbr vest.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Due to the lack of popularity of dragonskin, and the incredible amounts of controversy that its testing sparked, I'd argue for just outright dropping dragonskin, or relegating it to meme status. There's not enough test data to show how resilient it's supposed to be, or how it really stacks up to multiple hits.

All of it is well out of the 6 year warranty period anyways.

**Comment by arijust** [comment]
Sometimes realism in video games gets too far.
It's one of these moments.

**Comment by Brian-Otten** [comment]
I'll just start a small poll here for convenience then since i'm fine with the other options as well:
Rebalance dragon skin = heart
Remove dragon skin = thumbs down
Keep as is = thumbs up

**Comment by tenmillimaster** [comment]
Changes and commits are not implemented based on user input. Polls have no meaning.

**Comment by Brian-Otten** [comment]
No, but they can give you some idea of what people want which can be useful. The ultimate decision as always remains up the the maintainers of the project, which is for the best.

**Comment by Brian-Otten** [comment]
So got some feedback from the discord that it would probably be best to just keep this one 100% realism based, if we do the weight would go to 21.5 kg, and according to army tests it "sometimes" stops rifle rounds, and where exactly that puts it's armor value is debatable.
I could try and adjust the armor some so it fits those values, but it would probably go unused by all survivors so i think we might want to remove it at that point.
some fun trivia reading on dragonskin armor:
http://www.nbcnews.com/id/18790506/ns/us_news-military/t/army-dragon-skin-armor-failed-battery-tests/
https://archive.defense.gov/DODCMSShare/briefingslide/304/070521-D-6570C-001.pdf

**Comment by I-am-Erk** [comment]
I suspect this was added around the time the armour was getting some press, because it sounds cool. It's rare, it's arguably not significantly different from other plate-based bulletproof vests, the company that makes it is belly-up IRL so no more is getting made, and we can't get good use statistics on it. I don't think there's any argument for keeping it. Just give it a migration flag to mbr with ceramic plates.

**Comment by Brian-Otten** [comment]
Sounds good to me, will close this and open an issue to migrate dragon skin into a suitable replacement.

**Pull request closed without merging**
