### PR TITLE
Make crane determine reachability by LoS instead of walkability

### PR DESCRIPTION
**Pull request by mrkybe**
#### Summary
```SUMMARY: Bugfixes "Make vehicle cranes provide lift based on seeing their destination instead of walkability"```

#### Purpose of change
Cranes should be able to reach over quarter panels.

#### Describe the solution
Adds a `bool visibility_only = false` to the constructor for `vehicle_selector`.  When this is true, it checks if the crane sees the destination tile instead of checking if it has a direct walk-able path to it.

#### Additional context
Short and simple PR.

### CODE REVIEW

**Comment by woutershep** [comment]
for_crane_lift isn't an ideal name for the parameter. The code is generic and doesnt actually rely on it beeing a crane part. With the current name if in the future we might want the behavior for something that isnt a crane lift and then it has to pretend its a crane lift even though its not. You can broaden its potential without actual code change by changing the parameter name. `bool visibility_only = false`? Or maybe an inverse like `bool check_walkability_too = true` something like that. That would open it up to other potential users.

**Comment by mrkybe** [comment]
@woutershep Makes sense.  Done.

**Comment by KurzedMetal** [comment]
So, seems like after this change, I can't access to tiles of the vehicle unless I put the cantilever in a specific position so it has "view" of the tile I want to modify, which can be a bit complicated if the tile is inside the Vehicle and surrounded vision blocking tiles (like full boards).

Example:

My position:
image

if I try to remove a Storage Battery in the blue tile:
image

I can't do it without opening the Opaque door in front of me. I'm pretty sure before this change I could do it just fine without having to move the Cantilever or opening any Opaque Door.

Was this an intended effect of the change?, if the intention was to increase the "range" of the Cantilever, wouldn't have been better to check if it reached through *either* visibility OR walkability?

**Comment by mrkybe** [comment]
I'll take another look at this.

**Pull request merged**
