### PR TITLE
New mod to blacklist electric zombies

### PR DESCRIPTION
**Pull request by marccardinal**

### CODE REVIEW

**Comment by marccardinal** [comment]
Travis is complaining but this is certainly not a regression caused by this addon.

**Comment by Coolthulhu** [comment]
I restarted the job that failed. It might kick in properly this time.

We've got a ton of those "blacklist one thing" mods. Why blacklist electric zombies? Because they hit with non-physical attacks or because they drop CBMs?
Also, this blacklist is incomplete: it only blacklists the basic electric zombie, not shocker brute nor bio-op zed.

**Comment by kevingranade** [comment]
Same as  #21976, if you want to add more blacklists you need to remove others.
Alternately if you want more flexible blacklisting come up with a feature that enables it in a nicer way.

**Comment by marccardinal** [comment]
Agreed @kevingranade, would it make sense to have a general "zombie selector" addon that has a secondary menu where you have a list of zombies and can white/black list them individually?

**Comment by kevingranade** [comment]
Actually what seems like it would make the most sense is a "personal blacklist generator" menu that lets the user select entities to blacklist, perhaps by category or tag in addition to by individual monster.  It would then write a blacklist mod entry that can be seleced as a mod on world creation.

**Comment by kevingranade** [comment]
Not merging as is, but we have a path forward.

**Pull request closed without merging**
