### PR TITLE
Replaced hardcoded terrain list with checking of terrain flag

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Infrastructure "Replaced hardcoded terrain list with checking of terrain flag"```

#### Purpose of change

Replaced hardcoded list of terrains with checking of `PLOWABLE` flag.

### CODE REVIEW

**Comment by Barhandar** [comment]
Agreed; stuff like solid rock or asphalt is unplowed, yet not plowable.

**Comment by ZhilkinSerg** [comment]
Totally makes sense. Thanks!

**Comment by ZhilkinSerg** [comment]
Hmm... Maybe we don't need

> 
> 
> Looks great, but the following instances of "DIGGABLE" in the code should be replaced with "PLOWABLE":
> 
>     * All the roots related stuff in player.cpp
> 
>     * `till_plot_do_turn` in activity_handlers.cpp
> 
>     * `makemound` in iuse.cpp
> 
>     * the second check in `activate_mutation`
> 
>     * `operate_plow()` and `operate_planter()` in vehicle_use.cpp

Suggestions implemented.

**Comment by ZhilkinSerg** [comment]
> 
> 
> The underlying logic changed but those mutations' description haven't.

Do you think it is still an issue?

**Comment by cainiaowu** [comment]
Well, cant remember why I make that comment,  maybe about the mutation 
message mentioning soil.

**Pull request merged**
