### PR TITLE
Introduces the Amplified @'s Features mod

### PR DESCRIPTION
**Pull request by mycus-must-grow**
#### Summary

SUMMARY: Mods "Adds new mod named Amplified @'s Features"

#### Purpose of change

To increase compatibility with some tile-sets, although changes NPC's demographics. Thus: a mod.

#### Describe the solution

Adds new appearance traits and makes changes in how demographics works, adding support for beard color, freckles and eye color. Also changes the way items related to appearance are displayed in the trait selection screen, sorting it for faster selection.

#### Testing

It works as intended :)

### CODE REVIEW

**Comment by Zaragata** [comment]
I used the web linter on all files and travis + json style check are still failing o_o

**Comment by KorGgenT** [comment]
> I used the web linter on all files and travis + json style check are still failing o_o

did you remove the newline at the end of the file? that's the most common copy paste error

**Comment by Zaragata** [comment]
Hi KorGgent, I'm gonna do that rn

**Comment by Zaragata** [comment]
Ended up using the linter inside `/tools/format`

Also had to change some `"description": "lalala"` stuff, like two spaces after a dot and so on

Now it finally looks like it's going forward 😅 I hope

**Comment by Zaragata** [comment]
Ima close and open another repository, sorry for the mess :\

**Pull request closed without merging**
