### PR TITLE
Introduces Amplified @'s Features mod

### PR DESCRIPTION
**Pull request by mycus-must-grow**
#### Summary

```SUMMARY: Mods "Adds new mod named Amplified @'s Features"```

#### Purpose of change

To increase compatibility with some tile-sets, although changes NPC's demographics. Thus: a mod.

#### Describe the solution

Adds new appearance traits and makes changes in how demographics works, adding support for beard color, freckles and eye color. Also changes the way items related to appearance are displayed in the trait selection screen, sorting it for faster selection.

#### Testing

It works as intended :)

### CODE REVIEW

**Comment by I-am-Erk** [comment]
This large of a PR needs a *lot* more information about what you're doing.

**Comment by Zaragata** [comment]
Hi @I-am-Erk, It is just a continuation of [Zetsukase's Hair Extensions](https://github.com/Zetsukaze/Zets-Hair-Extensions), but now npcs can spawn with beards and cute skin.

I had to change the collections and distributions groups, childs of `Appearance_demographics`, so it's no longer as realistic in relation to New England, thus a mod.

`data\json\npcs\appearance_trait_groups.json` should behave like this now, _where squared shapes are distributions and circled ones are collections_:

graph

I am sorry if any of these changes were a bad idea, but I wanted to add support for already existing features in some tile-sets that weren't being used.

Oh, and also to improve the selection screen for appearance traits, leaving the most important ones at the top. I just changed the name of those traits.

**Comment by Zaragata** [comment]
Also, you can get it [here](https://github.com/Zaragata/amplified-player-features)

**Comment by Zaragata** [comment]
Welp, after *that* fiasco there is little point in trying to support *that* tileset. Closing.

**Pull request closed without merging**
