### PR TITLE
(WIP) Faction camp walls

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Content "Adds modular basecamp wall recipes"```

#### Purpose of change
Flexible base camp construction requires flexible recipes to allow players to build walls to their own specs

#### Describe the solution
Breaks walls into two portions: 6x6 corner segments and 12x12 edge segments.
Each of these segments has two layers that can be built separately. This allows you to combine them into such patterns as:
-outer pits/moat and inner palisade
-thin outer wall with more room inside
-double thick walls for extra protection
-double layer of spiked pits for quick and dirty shielding

Currently the only options I am adding are pits, palisades, and junk palisades. I may add barbed wire and chain link before I finish this PR.

Each edge and corner wall will also have the option to include a doorway.  The long edges will may also have the option to include a wide vehicle gate.

#### Describe alternatives you've considered
I would love the option to add gun ports, but the code for that sort of furniture/terrain isn't made yet
I'd like to add more terrain types, but that's quite easy and could be done in other PRs
I am considering adding a vehicle gate, but I'm not sure yet if the pulley will fit on the map.
There may be a second pattern of wall shapes to accomodate hard-shell bases rather than a wide perimeter wall.

### CODE REVIEW

**Comment by Mcrone617** [comment]
Hey @I-am-Erk I'm working with @DracoGriffin , trying to increase public participation and get the PR testing going on the subreddit. Would you be interested in doing something like that for this PR? This PR could definitely benefit from some mass testing, checking if the various wall variants work together properly, and if they're too OP or something like that. It also has the benefit of letting people know that this is something you can do, or something you will be able to do in the near future. Of course you're still working on it, so when you're satisfied with the state of the PR, and if you're interested in PR testing, let me know and we can work out compiling and making a downloadable link. Hope to hear from you!

**Comment by I-am-Erk** [comment]
This is probably not the PR you want to be testing, this is a basic content addition to the code stuff mlangsdorf is doing.

**Comment by Mcrone617** [comment]
> This is probably not the PR you want to be testing, this is a basic content addition to the code stuff mlangsdorf is doing.

Fair enough then. What is the best way to test these sort of changes? From my (very limited) understanding, this PR is dependent on the mlangsdorf stuff getting merged right? but those changes are merely code changes, and allow for this sort of thing to happen, and your PR is the actual content that is built on his code base. Is there a easy way to test this? Or is it better to just leave it be and let people figure it out when it gets merged into experimental, due to making test builds for multiple PR's being a huge hassle.

**Comment by I-am-Erk** [comment]
The code will affect the way changes to the base work, so a start would be to get Mark's code compile and installed and try building a faction camp. Someone with that pr running could then test this one when it's ready... Currently it's a bunch of maps with no in-game implementation

**Comment by I-am-Erk** [comment]
Putting this on hold yet again.

**Pull request closed without merging**
