### PR TITLE
Minor armor audit [CR]

### LINKED ISSUE #11767: bike helmet gives more protection than motorcycle helmet
The bike helmet is twice as protective as the motorcycle helmet (ignoring coverage).

The bike helmet is 100% plastic, with bash_resist 2.

The motorcycle helmet is 50% plastic, 50% nomex, with an average bash_resist of 1.5, which gets prematurely rounded down to 1.

I'm already going to submit a PR to remove the premature rounding. That will bring the disparity from 12/6 up to 12/9. Maybe the material_thickness on one or both of them should be tweaked? At the very least, there should be parity of bash/cut protection (motorcycle would be better then, with higher coverage).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9930075-bike-helmet-gives-more-protection-than-motorcycle-helmet?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sparr**
Resolves #11767 
commit comments describe the changes, just a few things that seemed inconsistent to me

### CODE REVIEW

**Comment by KA101** [comment]
OK, those might need some discussion.  Busy ATM.

**Comment by KA101** [comment]
Mentioned this in IRC, not sure if you saw it: the combat boots are already a very good piece of footgear (armored and 0-Enc when fitted).  They don't need a buff.  (Heavier-armored boots are retrofitted with armor and/or made from thicker/rougher material, and are thus cumbersome.)

**Comment by Rivet-the-Zombie** [comment]
Yeah, combat boots need to stay as they are now, for all the reasons KA101 presented.

**Comment by sparr** [comment]
I guess I get why not to buff combat boots, but I'd think we need to nerf other boots if that's the case? Why would the cumbersome retrofitted other boots have better protection than professionally manufactured combat boots?

**Comment by Rivet-the-Zombie** [comment]
Because combat boots aren't really armored. They're durable as all heck, but they're far from being 'armor'.

**Comment by sparr** [comment]
less armor than winter boots or motorcycle boots??

**Comment by Rivet-the-Zombie** [comment]
Yes. Winter boots are generally made of super thick material, and motorcycle boots **are** made to armor your feet.

**Comment by sparr** [comment]
And we're comparing these to military boots? I mean, I know soldiers aren't exactly getting shot in the ankles, but I'm having trouble wrapping my head around the idea of mass produced combat boots being less armored than something my character sews together out of leather patches.

**Comment by Rivet-the-Zombie** [comment]
I'm guessing you've never worn combat boots?

boots

Take my word as someone who wears combat boots on a regular basis, they are not armor.

**Comment by sparr** [comment]
> I'm having trouble wrapping my head around the idea of mass produced combat boots being less armored than something my character sews together out of leather patches.

previous comment stands. if one isn't buffed, the other needs to be nerfed.

**Comment by Rivet-the-Zombie** [comment]
Crafted armor boots are made to be armored boots. Combat boots are made to be durable boots.

Whether you can wrap your head around it or not, it doesn't change these simple facts.

**Comment by sparr** [comment]
I don't disagree that they are *meant* to be armored boots; I simply disbelieve that a postapocalyptic cobbler can easily make more armored leather boots (without adding the layers that leather padding adds, which can be done to either boot) than average combat boots made today.

**Comment by sparr** [comment]
Just to get this PR landed, I've pushed a commit undoing the combat boots change. I'll bring that up again later in a bigger more footwear-specific balance PR.

**Comment by KA101** [comment]
Yeah, I didn't like some change orders I received back in the day.  Still made 'em.  Thanks.

**Pull request merged**
