### PR TITLE
fix smores error (1 charge)

### LINKED ISSUE #23938: Error while reading consumables.json while loading world
Game version:
0.C-28092-gc3ec9527bf (freshly built experimental as of a few minutes ago)

Operating system:
Arch Linux

Tiles or curses:
Tiles

Mods active:
None

### Expected behavior
No errors

### Actual behavior
The following error appears:

```
An Error has occurred! Written below is the error report:
-----------------------------------------------------------
DEBUG	: line 3.334:20: assignment does not update value
	"material": ["wheat","junk"]
	"volume": 1,
	"charges":
	          ^
	            1,
	"fun":30
    },

FUNCTION : void report_strict_violation(JsonObject&, const string &, const string&)
FILE     : Cataclysm-DDA/src/assign.h
LINE     : 25
```
Checking on the only two files modified since I last build the game, the error appears to be in consumables.json, specifically in the definition for smores.
Smores seems no different than any other food definition on the file, the only exception is that it is the only food that defines "charges" : 1.

### Steps to reproduce the behavior
Start a new game

### PR DESCRIPTION
**Pull request by Brambor**
Fixes #23938

### CODE REVIEW

**Comment by Leland** [comment]
@Brambor can you add `Fixes #23938` to your PR description? It will make it so if/when this PR gets merged, [that issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/23938) will automatically be closed.

**Comment by Brambor** [comment]
@Leland Is it now in the state in which I was supposed to write it? (Is that PR description, whatever PR in this context means?) I'm asking for future reference.

**Comment by Brambor** [comment]
@Leland So if it were like it is now it would have closed it automatically? I'm asking for future reference.

**Comment by Brambor** [comment]
@Leland I believe it wasn't, it was closed by Rivet-the-Zombie. Or we are looking at different things...

**Comment by Leland** [comment]
AH, you added that post-merge. Indeed

**Pull request merged**
