### PR TITLE
Strip ferals from guns

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Balance "Did you heard ferals can shoot you? now they can't"
#### Purpose of change
See #70215, part 2.1
#### Describe the solution
Strip ferals that have had any type of gun so they don't have such. 
Give feral security guard the baton to use instead of a gun
mon_feral_fancy_crossbow is removed completely (monsters do not need to be obsoleted)
mon_feral_prepper is replaced with feral prepper with pipe mace and feral prepper with knife 
milita and feral biker still use their guns as melee weapon, just stripped ammo from their weapon

Melee damage of all ferals is decreased by 10% with assumption their weapon is already deteriorated (each point of the item degradation result in exactly 10% decrease)

Itemgroups of said ferals are tweaked to have less ammo and to spawn empty mags and stuff
#### Testing
Spawned ferals to check they do not shoot me anymore
Mudreded thousands of ferals to verify they spawn much less ammo - they still spawn guns with ammo sometimes for mysterious reasons (i literllay put `"charges": 0` to mossberg_500 in feral_jackboot_shotgun, and the game still spawns it with full mag)
#### Additional context
I also tried to replace `{ "and": [ { "not": { "u_has_effect": "maimed_arm" } }, { "not": { "u_has_effect": "disarmed" } } ] }` with a single EoC and `{ "test_eoc": "is_disarmed" }`, but then realised syntax for `test_eoc` was added much later; will PR it when this will be merged

### CODE REVIEW

**Comment by Kantonine** [comment]
I don't know if this was already brought up, but feral naval officers can also shoot you, so if you can add that before it this gets merged, thatd be great!

**Comment by GuardianDll** [comment]
mon_feral_officer is tweaked, just forgot to mention it in pr body

**Comment by DoctorBoomstick** [comment]
It might be an idea, if you haven’t done it already, to signpost in the descriptions that ferals that still have a gun but only use it in melee have no ammo. For example, the description making  note that the feral officer’s pistol has its slide locked back on an empty magazine, the feral biker continually cocking their shotgun but nothing being ejected, sound snippets of gun racking sound effects, etc. Otherwise, you can leave the descriptions as they are and troll people by letting the descriptions imply that, indeed, there might be a chance of this creature shooting you.

**Comment by GuardianDll** [comment]
i thought about it, but i don't really know is it a good idea, since it is not true that they can shoot you

**Pull request merged**
