### PR TITLE
[ON HOLD] Bright Nights: Introducing the NCBM

### PR DESCRIPTION
**Pull request by ghost**
Ever wanted to replace yourself bit-by-bit with alien matter until you're no longer recognizably human? No? Too bad - now you can anyways!

This PR adds several "NCBM" items to Bright Nights. Developed before the Catalysm, these utilize nether material to achieve things that their unfortunate host creatures are capable of doing. The `POLY-HEMO NCBM`, for instance, replaces your blood with shoggoth hemolymph, making you immune to bleeding and greatly increasing the speed that bandages heal you.

Some of the simpler of these can be crafted, their new recipes found in a book called `lab journal-Higgs`, with nether organs, which can be harvested from nether creatures such as flaming eyes by butchering them. More complex ones are found from butchering zombie scientists and operators.

Full list of changes:
* In Bright Nights, krecks, shoggoths, hunting horrors, and flying polyps do not melt away, and instead leave corpses.
* The corpses of nether creatures now yield various amounts of nether organs. With the right tools, five can be dissolved into nether extract, a key component in NCBM crafting.
* A new book called `lab journal-Higgs` now spawns in labs, and contains the recipes for crafting several NCBMs.
* **037-OVLD NCBM:** Overloads the senses of nether creatures and zombies within range, stunning them at the cost of bionic power. Craftable.
* **GozUp B33fI-B01 NCBM:** Increases your carrying weight by 50%. Craftable.
* **POLY-HEMO NCBM:** Provides immunity to bleeding and increases the speed that bandages heal you by 10x. Craftable.
* **Fromlight-Noself v1.0:** While active, darkness makes you invisible and sunlight kills you dead.
* **Psychic Shield Mk. I:** A less all-inclusive version of artifact psychic shielding. Blocks fear paralysis and flaming eye stares.

As always, comments welcome.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
You should probably ask @Coolthulhu whether this fits thematically with the mod.

They seem interesting, but I dont think they fit with what bright nights is meant to accomplish.

**Comment by Xhuis** [comment]
I'll take a look once I get home.

If this does not fit the "mission statement" of Bright Nights, what is it, might I ask? It isn't clearly placed anywhere that I can tell.

**Comment by ScageDS** [comment]
I like the concept of integrating netherum parts and abilities utilising cybernetics, but I agree that they don't really fit with Bright Nights. It provides more pure sci-fi side-effect free technologies, as well as some game system alterations, that ultimately this doesn't really work for. I think it would do better as a separate mod for the game. Additionally, that would give players who don't play Bright Nights the opportunity to use these.

Concerning balance issues, I have some thoughts. The stun generator should definitely have a higher cost, see the flashbang generator for an example, which uses 125 power. I can't speak on the invisibility of the Fromlight-Noself as I've never had a chance to use any invisibility granting items. As for healing, I couldn't find the specific amount bandages heal, but 10x seems to me to be too much. Maybe tweak it down or give the poly-hemo a different effect? For the Gozup carry weight is never something I've had an issue with apart from lugging engines, but I suppose an upgrade would be useful and I don't foresee any issues by it. I've also never encountered psychic enemies, so I'm not qualified to talk about that either. I've killed Krecks & Co.(tm) with starter survivors, so that could probably use some tweaking.

All in all it's a good concept that I wouldn't mind being in the game. Why not add some lovecraftian nightmares to our transhumanist dreams? I don't know if it would fit in the *base* game, that's a different debate to be had, but I like it a lot. If I'm mistake about something I wouldn't be surprised, so feel free to correct me. I'm a certified idiot after all.
(Also, I see your Prey references you cheeky bugger>)

Citation:
[Flashbang Generator CBM](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Flashbang_Generator)

**Comment by Xhuis** [comment]
I'll do a balance pass on these along with some tweaks to their acquisition and the like once I get a moment. I may also migrate them to their own mod.

**Comment by Xhuis** [comment]
Haven't forgotten about this, just been mulling it over. Will work on it when I feel motivated.

**Pull request closed without merging**
