### PR TITLE
Reverse the polarity of the proton flow

### PR DESCRIPTION
**Pull request by KA101**
Adds a new "is this active mutation turned off?" boolean and applies it to check for NV mutations being turned off, thereby making inactive NV provide the vision and active ones remove it.

Seems backwards, but was specifically requested: http://smf.cataclysmdda.com/index.php?topic=9476.msg215725#msg215725 .  has_inactive_mutation would be handy in a few other places, but it's easy enough to recreate if this one isn't workable.

### CODE REVIEW

**Comment by Gabriel-SE** [comment]
What if we automatically set active mutation with power = 0 to active when the player get it ?
So if someone pick Night Vision at chargen, it will automatically be set to active state rather than waiting for the player to press [ and activate it manually.
If this becomes a problem later we can add flag "AUTO_ACTIVE" in mutations.json to check if a mutation should be set to active or not automatically.

**Comment by KA101** [comment]
Might be workable, will take a look but likely not tonight.

**Comment by Snaaty** [comment]
+1 for the joke, though

**Comment by KA101** [comment]
Always time for a classic!Who reference.

**Pull request closed without merging**
