### PR TITLE
Add cursor navigation to the mutations UI. 

### LINKED ISSUE #25653: Too many mutations causes issues with actives
**Is your feature request related to a problem? Please describe.**  
If you have too many mutations, the game runs out of keys to assign, so you can't select them to assign keys

**Describe the solution you'd like**  
The game either needs more keys to assign or a way to select them beyond pressing they keys the game assigns, as if it never assigned a key, you can't select the mutation to reassign that key

**Describe alternatives you've considered**  
As above.

**Additional context**  
N/A

### PR DESCRIPTION
**Pull request by Rovallen**
#### Summary
Interface "Added a cursor to the mutations tab"

#### Purpose of change
The existing mutation UI becomes unusable if the total quantity of mutations exceeds the number of available hotkeys. This becomes quite a game-breaking issue in the later game. Quite a crude solution, but Fixes #25653 and works perfectly fine in an actual game.

#### Describe the solution
I made a cursor controlled by up and down arrows (and Tab for tab switching). It works pretty much like bionics' UI cursor, but is a lot less complex in its nature. It's quite basic, though, so it might need a polish. It allows the player to activate, examine, reassign (and clear the hotkey too) and hide the mutations even if they don't have a hotkey assigned.
I did exactly as much as was neccessary to fix the issue, but I am willing to improve the code further if the neccessity arises. I couldn't have done it in a perfect way since I am not too familiar with C++.

#### Describe alternatives you've considered
The best solution would be to create a uniform UIs for inventory, bionics and mutation windows, but it would take a lot of time and effort. Since I cannot provide it myself, I have to fix the issue with a temporary solution. As the best solution probably requires a complete rewrite of the mutation_UI.cpp, I believe this little fix won't make the matters worse. 

#### Testing
I tested the UI with a random character, using the debug menu to add a whole bunch of mutations. I didn't encounter any issues. There shouldn't be any regressions because the added code does not tinker with any game-related values, it just reads and shows. The "Confirm" action works exactly the same way the vanilla hotkey press did, so there shouldn't be any troubles either. Since the algorithm is essentially copied from the bionics UI, it should work properly in all the situations bionics UI does. Further testing might be required while dealing with mods that alter the mutations mechanics, but content mods should be compatible. 
Actual in-game usage for a handsome while didn't reveal any issues. A little extended testing featuring a few critical cases went with no problems.

#### Additional context
None yet.

### CODE REVIEW

**Comment by Rovallen** [comment]
Sorry for the terrible copy-paste changelog! First time using Git.

**Comment by kevingranade** [comment]
You seem to have reformatted mutation_ui.cpp away from the project style guidelines, a local `make style` will fix it.
Also this needs to be addressed:
```
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/mutation_ui.cpp:507:44: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
            else if (action == "NEXT_TAB") {
                                           ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/mutation_ui.cpp:520:14: note: end of the original
            }
             ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/mutation_ui.cpp:521:44: note: clone 1 starts here
            else if (action == "PREV_TAB") {
                                           ^
```

**Comment by Rovallen** [comment]
Thanks! Patched that up.

**Comment by Rovallen** [comment]
And yes, I have _no_ idea what's wrong with LGTM checks every single time. I'll be really grateful if somebody gives me a hint of what on Earth should I look into and whether it is my fault at all or not...

**Comment by BrettDong** [comment]
> I have no idea what's wrong with LGTM checks every single time.

It's not your fault, the codebase has grown so big that code analysis exceeds the 4 hour time limit for free plan.

**Comment by Rovallen** [comment]
Phew, thanks for the explanation! I was really nervous about that one

**Pull request merged**
