### PR TITLE
Moose Morale Reduction

### PR DESCRIPTION
**Pull request by chaosvolt**
Dang, so close to delicious alliteration. Moose Morale...um...no, not Minimization, we aren't going that far. Moderating? Sounds derp, sure.

Basically came up in a thread on the forums ( http://smf.cataclysmdda.com/index.php?topic=10703.0 ) and I made the obvious suggestion in response to a complaint that moose are, as usual, implacable terminators.
1. Reduced moose morale from 80 to 70. For reference, bears have 60, though they have has 5 higher aggression.

EDIT: And for now this will be used as an issue instead of a PR, due to accumulated discussion of more effective solutions concerning moose behavior. o3o

### CODE REVIEW

**Comment by kevingranade** [comment]
Do you have any evidence that Moose are not in fact implacable terminators?
All the discussion I've seen on the subject boils down to, "I wish moose would stop attacking me".

**Comment by chaosvolt** [comment]
The whole "getting chased across town by a moose because it caught a mere glimpse of you" seems to be a Cataclysm mainstay. :V

**Comment by chaosvolt** [comment]
Also, the issue here isn't moose aggression, but relentlessness. Do moose normally continue to charge someone who runs away? >_>

**Comment by Coolthulhu** [comment]
I broke one mechanic of moose calming down, but it was never working properly anyway.

Moose are supposed to stop attacking when you're hurt. The problem with that was the fact that a hurt survivor could attack moose without any risk of retaliation.

**Comment by Rivet-the-Zombie** [comment]
Moose are dangerous creatures IRL, but they're not as aggressive as they are in DDA by a long shot. I think reducing their morale a bit might bring that down to a more reasonable level.

**Comment by chaosvolt** [comment]
Hmm. I suppose if "player runs away" was a valid AI flag, that would solve this.

But yeah, less morale would handle that as well.

**Comment by kevingranade** [comment]
I guess the main problem I have is there's no actual goal, I can't evaluate this kind of thing dor, "Does it do what it's supposed to?" because it doesn't have an objective statement of what that is.  Likewise I can't suggest alternatives, because again there's no goal to meat, just tweaking.

**Comment by chaosvolt** [comment]
I'm...not sure what you're getting at, nor does it really justify said earlier smartassedness. =w=

The goal, essentially, is to make moose less likely to pursue players to the ends of the earth. If a minor tweak to morale is enough to accomplish this, then yay. If not, then I guess this is rather pointless.

I mean, the whole "moose will not stop until you are dead" thing has been a Cataclysm running gag for a while.

**Comment by kevingranade** [comment]
How do I decide if this makes moose, "less likely to pursue players to the ends of the earth."?
What's less likely?  Under what circumstances should a Moose ignore or avoid a player instead of attacking?
We need to agree on what those circumstances are before making changes, otherwise we're just endlessly tweaking things.

**Comment by chaosvolt** [comment]
*facepalms* I thought that I'd already said that the main circumstance would be the player attempting to run away, and having succeeded in putting some distance between the two.

From what I know, moose IRL generally don't continue to pursue someone who manages to run away, and especially not to the extent that moose in-game do.

**Comment by kevingranade** [comment]
Now we're getting somewhere, so what you want isn't to make Moose more timid, but rather to make them calm down faster if there are no nearby targets (I assume if the target isn't the player, that's still fine since it gives the player more chance to get away).  So what range are we talking about?

**Comment by chaosvolt** [comment]
A minor amount, enough to make a difference while still making them able to pursue the player long enough to ensure they're thoroughly discouraged? Or towards whatever value would be closest to average real-world moose behavior, assuming we can get more advice on how prone to pursuing fleeing aggressors they are IRL.

**Comment by Coolthulhu** [comment]
Having them drop a moderate bit of anger (not morale!) on move could help, but could also result in them spending half a turn charging, then second half chilling.

Having them simply drop anger faster than the current rate would not allow player to escape once the moose caught up, only if the player managed to keep 6 tile (or more) distance until the animal calmed down.

Implementing a moderately strong (but stronger than closeness anger trigger) placate trigger on hit and an anger trigger on hurt would make them stop being angry after hitting a target few times, unless the target fought back. It would still get angry once again if the target couldn't run far enough.

Implementing a new effect - "standing still", which would be added to a player who deliberately waits (skips turn without using moves) and would prevent moose/bear closeness anger trigger (and possibly have a placate trigger tied to it) could allow the player to wait out the anger, probably taking a few hits, until the animal calmed down.

**Comment by chaosvolt** [comment]
That are good ideas as well, though these are a bit beyond my ability to code out.

**Comment by chaosvolt** [comment]
Also, if a morale tweak isn't the acceptable solution to this, I should presumably close this PR. @_@

**Comment by kevingranade** [comment]
I think losing anger on movement is the best bet for modelling "only chases enemies for a while before giving up".  If you make that higher than the "enemy nearby" boost, then they would have short, abortive charges, which is actually something that happens.

A player can run at very nearly the speed of a moose if unencumbered for a little while, that should be enough to wait out the moose's anger if the player is lucky.

I don't see the rationale for moose calming down based on either attacking or the target being passive, Moose are known to attack and destroy inanimate objects, and they have no compunction killing things, so they're not going to stop just because the target is hurt (actually the existing "target wounded" placate trigger is misplaced, what, are Moose feeling guilty?)

**Comment by kevingranade** [comment]
Or we can use it to discuss solutions.

**Comment by chaosvolt** [comment]
Ah. Very well then. ^^"

**Comment by Cat09** [comment]
I do know that moose are also very territorial, they can randomly decide to "claim" a spot (especially young males) and will not tolerate any perceived opposition. there was an incedent near where I live, in which a moose claimed a section of road. He sat on or otherwise damage several cop cars as they tried to shoo him away.

**Comment by Cat09** [comment]
I also have had a moose try to stay in front of my car and not allow me to get by it before, I had to fake it by starting to turn down a side road, then peel out back onto the main to get by it.... so yeah, moose behave *very* strangely

**Comment by Rivet-the-Zombie** [comment]
And that's why Cervidae are only good when they're steaming on a plate.

**Comment by chaosvolt** [comment]
Lots of things are better as food, yes. o3o

**Comment by i2amroy** [comment]
Just want to point out that it's rather unlikely this would have done anything anyways. The current system for having changing attitudes is basically worthless due to number issues; getting a system that has a bigger gradient of moods with a bit of a more gradual difference between "filled with unstoppable rage" and "running away in a panic" has been a thing on my list of things to for a long time.

**Comment by chaosvolt** [comment]
Hmm. Should've guessed that. ;_;

**Comment by Rivet-the-Zombie** [comment]
Looks like this PR has served its purpose.

**Comment by chaosvolt** [comment]
Doh. I'm wondering why I kept it open all this time. >.>

**Pull request closed without merging**
