### PR TITLE
Added chicken cages.

### PR DESCRIPTION
**Pull request by Kelenius**
As a continuation for the poultry handling - chicken cages are similar to pet carriers, but smaller, craftable, and can only hold tiny animals.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Double spaces after . in the descriptions, but rest looks good.

**Comment by Mecares** [comment]
5 Volume for a Chicken Cage? Sounds like animal cruelty to me.

**Comment by Kelenius** [comment]
>Realistic Volume for a cage for chickens according to following source

I believe this article talks about cages where chickens are kept in the coops, this is a cage used only for transporting them.

>How about enable canvas sack to transport chicken?

I don't know about that. This isn't just a cage for transporting chickens, you can use it to hold any tiny animal.

**Comment by DracoGriffin** [comment]
If you're copying and pasting item entries, try to use "copy-from" please.

**Comment by Kelenius** [comment]
>If you're copying and pasting item entries, try to use "copy-from" please.

That doesn't work well with `properties` AFAIK.

**Comment by Kelenius** [comment]
Pet carrier is 20, and can hold small animals; this cage can only hold tiny ones. I thought that reducing it to a quarter would make sense. I guess 10 would be better?

**Comment by mlangsdorf** [comment]
This needs to be added to the farming improvements project (https://github.com/CleverRaven/Cataclysm-DDA/projects/11) but I don't have the authority.

**Pull request merged**
