### PR TITLE
[WIP] Vehicle Overhaul Part 1a

### PR DESCRIPTION
**Pull request by ghost**
Vehicles are currently a bit of a hot mess. There is precious little room for JSON customization and many of the hardcoded formulas are arbitrary, nonsensical, or both. Balance is sketchy at best, with V12 bicycles gaining a measure of notoriety. Despite these flaws, vehicles are immensely popular. Seemingly everyone not deliberating looking for a challenge attempts to build a Deathmobile. 

Previous attempts to resolve these flaws have encountered a number of problems. Complex and obaque rpm and gearing restrictions proved an inadequate solution to overinflated maximum velocities. In addition, many features such as collisions and multiple engines were removed or broken. These difficulties are non-trivial and must be given due considered lest future projects rediscover them independently.

That said, I believe I can make some progress on the vehicle problem. I've already made good progress on part 1a and I have made an effort to separate features into discrete sections in hopes of controlling PR size. That said, this is very much still WIP. In particular, I need to decrease the size of this PR and tune parameters to avoid disrupting balance. My goal is not to rebalance vehicles but to improve the infrastructure upon which a good rebalancing might be built. 

# Current PR (1a) Progress:
- [X] Improved combustion formula with JSON engine customizability.
- [X] Improved rolling resistance and sinkage formula with JSON wheel and terrain customizability.
- [X] Improved traction formula with JSON wheel customizability.
- [X] Basic aerodynamics formula as placeholder.
- [X] Improved acceleration formula taking into account drag, rolling resistance, and maximum tractive force.
- [ ] Write balance/regression tests to evaluate new mechanics.
  - [x] Ensure reasonable fuel usage.
  - [x] Ensure reasonable engine power.
  - [x] Ensure reasonable acceleration.
  - [x] Ensure reasonable maximum/safe velocity.
  - [x] Ensure reasonable traction.
  - [x] Ensure reasonable rolling resistance.
  - [x] Ensure reasonable drag.
  - [ ] Ensure reasonable collisions.
- [x] Resolve bugs resulting from partial integration of floating point velocity.
  - [x] Collisions.
  - [x] Displayed Velocity.
  - [x] Cruise Control.
  - [x] Low Speed Driving
- [ ] Keep PR below 500 lines of code.
- [x] Test player vehicles for consistent performance before/after PR. (Minor change is acceptable, but major changes to usability should be avoided. e.g. Max speed of 1000/500tpt is functionally identical but safe speed of 20/10tpt is significant.)

# Part 1: Dynamics and Combustion Engines

Combustion engines have very little JSON customizability and 'just work' via a mass of haphazard formulas. Simply improving the absolute basics of the system will have huge benefits. For instance, traction provides a means to limit the utility of large engines on small vehicles while drag can be tuned to prevent excessive maximum velocities.

## Part 1a:

Terrain based traction and rolling resistance. Placeholder drag. Improved engine power and acceleration formulas. Physics based formulas where practical. JSON specification of Engine efficiency, Wheel traction and rolling resistance, and Terrain sinkage. 

## Part 1b:

Improvements which can be independently developed from the base established by 1a.

### Part 1b-I:

Improved collisions. (#23000, #20017, #23578)

### Part 1b-II

Improved drag.

### Part 1b-III

Decibel based noise system. (Lower noise for higher cylinder count.)

### Part 1b-IV

Improved smoke system.

### Part 1b-V

Improved handling system.

## Part 1c:

Improved readability and styling of vehicle.cpp.

### Part 1d-I

#23123

### Part 1d-II

#20520

# Part 2: Reactors, Electrical Engines, etc.

Reactors, electrical engines, and other devices will need an overhaul to maintain consistency with changes introduced in `Part 1`. In addition, there are a number of unresolved issues with the current systems. (#21874, #21964, #22191, #22077, #21215, #20321)

# Part 3: Multitile Vehicle Parts

The ability for a single part to use multiple tiles would be useful for both current and future parts. It would allows treads to behave as expected. It would also be useful for `Part 4`. Multitile functionality would allow improvement of the flotation system and simplify the creation of a watertightness system.

I also intend to model armour and distance between the vehicle and the ground. This will resolve certain flaws discussed in #22025, #20847 and improve collision modeling. In particular, it will greatly improve modeling of a vehicle's ability to traverse very rough terrain. e.g. A pickup a quarter meter off the ground would be able to cross rocky terrain while a sports car 0.05 meters off the ground would become stuck.

# Part 4: Boats

The vehicle code is littered with todos regarding a unified vehicle framework allowing for amphibious vehicles. Such a framework would be premature at this time; land vehicles barely have a unified framework themselves. However, it would make an excellent future goal.

# Part 5: Turrets

Turrets may be seriously broken (#22541, #22512). I haven't look into turrets yet, but if I finish the previous parts it would be worthwhile to make sure turrets aren't broken in some non-obvious way.

# Part 6: Modular Vehicle Parts

Allowing more flexibility in part scavenging, creation, and installation would be cool. Engines could have improved control systems attached, kitchens could have waffle irons installed, etc. However, this may not fit design goals and the  previous 4 parts will provide many more options for it to utilize. It would be nice to have, but is far behind everything else in priority.

# Part Null: What won't be included.

I do not intend to make JSON edits or add new content except as necessary to support code changes. Similarly, I won't be tweaking the vehicle menu except as necessary to maintain current functionality.

### CODE REVIEW

**Comment by Isaacssv552** [comment]
@illikun this is only for 1a. It’s still a bit large so I’ll be trying to pare back the changes to a minimum.  

The part list is just there to provoke discussion and make it easier for reviewers to determine if I’m in danger of putting too much into a single PR.

**Comment by AMurkin** [comment]
Shell scripts probably shoud go separately from vehicle overhaul PR.

**Comment by Isaacssv552** [comment]
@AMurkin They've been moved to another pr.

**Comment by ZhilkinSerg** [comment]
I've updated markup a little. Couldn't look into unformatted text.

**Comment by ZhilkinSerg** [comment]
I suggest putting out any drastic vehicle changes post `0.D`.

**Comment by Isaacssv552** [comment]
The lines of code I've needed to write to make this work properly has rapidly grown out of control, so I'll probably have to split off as many subcomponents as possible into new PRs.

**Comment by kevingranade** [comment]
The only places to split this I can see with a brief read:
Split off some of the unit changes.
Split initial drag equations and traction additions.
Split changes to tests (other than values being asserted) into another PR.

Context for the request to split, sometimes you can only make things so small. If splitting your code further is harder than writing it in the first place, yea call it quits and we'll deal with a big PR. That doesn't change the fact that reviewing will be slow, which is frustrating for everyone.
Almost as good as small PRs is good comments, explain what the tricky functions are doing and it makes reviewing a lot faster.

Direct feedback:
Please cite some sources so we can look at the formulas yore basing this on (In comments).  I'm not good enough with physics to review the raw formulas without some help, and if you wait for me to find your sources we'll be here a looking time :)

**Comment by tyrael93** [comment]
Hey can you fix the ancient "zombies quantum tunneling through vehicles" bug while you're at it
like when a car is like this
---
|o|
|o|
|o|
---
zombies don't have a chance to enter
but when you turn ever so slightly and have only one layer of frames it turns into
---
\o\
 \o\
  \o\
   ---
and zombies can go through the \s and eat your face and pull you from your seat unless you double-layer for some reason

**Comment by Epictyphlosion** [comment]
This is a really good PR, and it will fix a lot of issues! Too bad I won't be able to make a bus with 4 V12s anymore...

**Comment by thethunderhawk** [comment]
@tyrael93 
If I were you I wouldn’t hold my breath on that one. It’s an old issue, a limitation of the game engine. It definitely won’t be addressed in this PR. In the meantime you’ll just have to suspend your disbelief and double layer your deathmobiles.

**Comment by kevingranade** [comment]
No progress and craptons of conflicts, closing.

**Pull request closed without merging**
