### PR TITLE
Don't damage hands when smashing but use your most armored part instead

### LINKED ISSUE #42872: Smashing terrain with bare hands gives an incorrect message when it breaks
> You hurt your hands trying to smash the nothing.

This is the message you get if you smash any terrain feature with bare hands and it breaks.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: Balance "Don't damage hands when smashing but use your most armored part instead"

#### Purpose of change

Fixes #42872 
Reverts #40956
And probably invalidate #41280 

Don't apply any damage on hands when smashing things without a weapon. Instead look for the part with the most bash armor and use it to bash your target. You won't get any pain or damage from it but the strength of your bashing is capped by the bash armor of the part used.
Following this formulae: `smashskill = min( best_bash_armor + smashskill * smash_efficiency, smash_skill *( 1+ smash_efficiency ) )`
Parts have different smash efficiency, head,mouth and eyes have 0.25 the rest has 0.5.
And you get a nice jsonised messaged for each different bodypart. ( credit to I-am-Erk)

#### Testing

image

Try to smah the floor and get a message saying floor instead of nothing
Try to bash a terrain that is not bashable and get no message

#### Additional context

Character with Str 10
Get naked 
Smash cupboard > Doesn't work
Smash window > Smashed

Wear boots (11 bash armor)
Smash cupboard > Smashed
Smash bench > Smashed

### CODE REVIEW

**Comment by ScampsAdams** [comment]
What about mutations? Hooves, curled horns?

**Comment by Amoebka** [comment]
Well, Hooves already sorta work because the mutation adds bash armor to feet. Horns don't.

A lazy solution would be to add bash armor to relevant mutations. A better solution would be to add a new "bashing bonus" attribute to mutations and use that instead, because some mutations (club tail, etc) should greatly help bashing without providing much protection.

**Comment by Fris0uman** [comment]
> A better solution would be to add a new "bashing bonus" 
This already exists
But the code to bash things ignores all of this currently. I'll look into adding it.

**Comment by Wokko1** [comment]
What if I have a completely naked character, who equips a dust mask (+1 bash armor). Is he gonna bash with his face, instead of kicking?

**Comment by Fris0uman** [comment]
Yes

**Comment by Zireael07** [comment]
Maybe exclude head from possible parts, then?

**Comment by Amoebka** [comment]
Excluding the head is bad because sometimes it would be objectively the best option (horns).

I think it would make sense for different body parts to have different innate armor values, so that a lightly covered head is still less durable than naked legs. It would be a much bigger change, though.

**Comment by wapcaplet** [comment]
I did some playtesting and got some surprising results. Using a base 8-STR character:

Wearing steel-toed boots (12 bash protection), I am unable to damage any of the following furnitures/terrains:
- Wood door (kicked over 100 times, but never damaged, and never saw a message like "You don't seem to be damaging the wood door", but I did eventually level up my melee skill)
- Wood bench ("You don't seem to be damaging the bench")
- Metal locker ("You don't seem to be damaging the locker")
- Broken computer console ("You don't seem to be damaging the broken console")
- Wood table ("You don't seem to be damaging the table")
- Sofa ("You don't seem to be damaging the sofa")

These things I can successfully smash with steel-toed boots, though it may take several attempts:
- Young tree
- Blueberry bush
- Flower
- Working computer console
- Beaded curtain
- Chair
- Entertainment center
- Window with curtains

However, I found that I can smash all the same things equally easily with no clothing or weapons at all.

Trying to smash while wielding weapons works better:
- Sledge hammer (bash 50): Door, bench, cupboard, locker, and even walls can be smashed easily (often on first or second try)
- Fire axe (bash 17): Door, bench, cupboard and locker can be smashed; walls cannot
- Hammer (bash 9): Door, bench, cupboard and locker can be smashed; walls cannot

Smashing zombie corpses to pulp them works well, whether I have a weapon or not (even with bare hands).

**Comment by paulenka-aleh** [comment]
One more thing to consider is body part health. I wouldn't smash anything with head if I have open wound there. Even if I wear a helmet and probably even if I had horns I would still rather they with my hands or feet.

**Pull request merged**
