### PR TITLE
More Locations mod. 

### PR DESCRIPTION
**Pull request by SunshineDistillery**
This is some of the the map gen stuff I've been working on.  I thought people might want to look at it, even though it's still a little rough, and maybe give feedback or ideas for new locations.  

It adds three types of multistory houses, a military outpost occupied by bandits, and a factory filled with robots. They don't have items added yet, so they're mainly just to explore or use as bases.

### CODE REVIEW

**Comment by Malkeus** [comment]
This is so big it broke my browser trying to look at the gif. I had to download your whole repository so I could take out the morelocations mod from data/mods. Is there a better way to do this? It wasn't difficult, but it was annoying. I'll let you know how testing it goes.

**Comment by Rivet-the-Zombie** [comment]
>a military outpost occupied by bandits, and a factory filled with robots

These sound particularly interesting, and might be the sort of thing we'd want in the mainline.

**Comment by Malkeus** [comment]
There's some kind of crazy hall of mirrors effect going on in the Factory. Using 'V' shows that there are only 2 security bots and 3 turrets actually on screen here. The rest are a weird graphics glitch.
http://imgur.com/lUepzMh

**Comment by Malkeus** [comment]
Military outposts are basically piles of free loot after you take down the turrets. As you approach it's nothing but massive explosions as the turrets destroy all the zombie soldiers. I've never seen so much free military gear. The grenadier is a nice touch though ;)

**Comment by kevingranade** [comment]
I think the idea is merge it as a mod so people can try it out, then
migrate it (or pieces at a time) as they're considered ready, which I'm
fine with.

**Comment by Malkeus** [comment]
ah. well I guess I jumped the gun a bit then

**Comment by SunshineDistillery** [comment]
I'll edit the monster groups for military outposts. I wasn't sure how much was too much. Maybe I'll make the default type something other than soldiers, or segregate the bots/zombies more so they don't kill each other before you get there. Honestly, since this is mostly about testing out mapgen stuff, the monsters were a bit of an afterthought and are probably pretty out of whack.

Yeah. It's so huge there's no way to mainline this stuff without testing it as a mod first. Even if the files look good there might be weird errors that are only apparent after the map is actually spawned. Every once in a while walls won't line up perfectly, or  maptile is facing the wrong way, or something like that. Also I've kept each maptile as a separate file, which might not be ideal for organization, but makes them a lot easier to work with. They might need to be condensed into fewer, bigger files eventually.

There are a few new terrains and furnishings, so I assume there will be missing tiles.  But I don't use graphics tiles, so I don't know what's going on with that glitch.

**Comment by Rivet-the-Zombie** [comment]
>I think the idea is merge it as a mod so people can try it out, then migrate it (or pieces at a time) as they're considered ready, which I'm fine with.

Oh yeah, I'm totally down with handling it as such; I just wanted to get the idea out there that such additions would be very much welcome in the mainline - if everything works properly of course.

**Comment by hitbutton** [comment]
> But I don't use graphics tiles, so I don't know what's going on with that glitch.

It looks like there are terrain types that the tileset doesn't have tiles for, and the ascii fallback has a transparent background. That means that there are areas of the screen that aren't getting redrawn properly, so you're getting "ghosting" from previous turns.

Basically its a problem with the tileset, and not with your mod.

**Comment by Malkeus** [comment]
I gave t_concrete_floor a tile and the hallomirrors went away. I really liked the layout of the bandit occupied military base with all the zombie soldiers locked in the basement. Got kinda crazy as the bots and zombies fought it out. I noticed a bug where skitter bots were attacking through the floor. It turned one of the hall ways on the ground floor into a no man's land.

I'll make an issue about it after i get to a pc

**Pull request merged**
