### PR TITLE
Fix Ocular Zombie Difficulty

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Fixes ocular zombie sight"

#### Purpose of change

Ocular zombie had a sight of 1 000, well outside the reality bubble, and only made its difficulty be inflated.

#### Describe the solution

Changes it to 100

#### Describe alternatives you've considered

Tried setting "diff" to -75, but it didn't work, as diff just adds to it I was hoping to make it 12 this way.

#### Testing

image

### CODE REVIEW

**Comment by sonphantrung** [comment]
There's actually [`ALWAYS_SEES_YOU`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md#monsters) flag that has the capability of pinpointing the char. Might be interesting.

**Comment by SariusSkelrets** [comment]
That flag would grant them the ability to see through walls, which AFAIK isn't what's intended for the ocular zombies
Their niche is seeing you from far away, not through matter

**Comment by sadenar** [comment]
Alternatively an always sees you zombie could be a much later evolution pumped up with a lot more blob magic?

**Comment by Holli-Git** [comment]
> Alternatively an always sees you zombie could be a much later evolution pumped up with a lot more blob magic?

IMO no, that feels much less blob and more so nether monster, which we already have. Zombies are still kinda sorted bounded by physics

**Comment by fairyarmadillo** [comment]
> That flag would grant them the ability to see through walls, which AFAIK isn't what's intended for the ocular zombies Their niche is seeing you from far away, not through matter

They had this when introduced and it was removed for more or less the reasons Holli-Git has stated.

**Pull request merged**
