### PR TITLE
New trait: Incapable Healer

### PR DESCRIPTION
**Pull request by CodeBandit**
#### Summary
SUMMARY: Content "'Added 'Incapable Healer' trait"

#### Purpose of change
Add a new 12 point negative trait that's extremely debilitating for the player. This is meant only for the seasoned veterans who are confident with their ability to avoid danger or tackle the Cataclysm.

This trait completely disables "natural" healing. This doesn't, however, disable *alternative* means of healing. Healing from certain mechanics such as JET, hypermetabolism, bionics, spells etc. are not disabled.

#### Describe the solution
Add a new negative trait with -1 resting healing and 0 mending modifier. To ensure no healing, add a check to enforce_minimum_healing for the trait as well as to relevant areas in regen().

#### Testing
Debug damage and let time clock for a week with self-aware. HP stayed the same.
Follow in the footsteps of Mama Murphy and inject some jet to check healing is still possible through alternative means.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Isn't it possible via multipliers/modifiers without hardcoding trait id?

**Comment by CodeBandit** [comment]
I tried to rely only on that at first, but it's needed to prevent minimum healing in enforce_minimum_healing(). Since the flag is there from that, I used it as a gate to go around a minuscule float allowing some healing to occur even after setting resting healing to -1.

**Comment by wapcaplet** [comment]
What is the real-world basis for a trait like this?

**Comment by CodeBandit** [comment]
There is none, I was using Genetic Downward Spiral as "inspiration" for feasibility, though it's quite farfetched. Supposing a trait like this is unwelcome and not to be merged, would a challenge scenario involving said trait be a valid alternative instead?

**Comment by Zireael07** [comment]
@wapcaplet: Wound healing is affected by a lot of factors: https://www.diabetes.co.uk/symptoms/slow-healing-of-wounds.html
https://www.woundcareinc.com/resources/factors-that-affect-wound-healing

I imagine the trait could be some sort of a chronic conditions that impedes both absorbing nutrients from what you eat and blood flow?

**Comment by Fris0uman** [comment]
Can't you use this instead of hardcoding it?
```json
    "healing_awake": 0.0,
    "healing_resting": 0.0,
```

**Comment by CodeBandit** [comment]
Trait has been updated to include healing_awake to 0. Healing resting is additional on top of other multipleirs, so setting it to 0 is just default, so I left it at -1.

To prevent hard-coding, I deleted enforce_minimum_healing which looks to have been arbitrarily added in the healing rate nerf #31611

**Comment by CodeBandit** [comment]
Big yikes, history wasn't preserved on rebasing and push -closing the issue and re-PR'ing in the future.

**Pull request closed without merging**
