### PR TITLE
Fix inconsistencies on all sleeveless dusters

### LINKED ISSUE #50118: Proficiency inconsistency: Duster & sleeveless duster
### Describe the bug

Sleeveless duster has two proficiencies (Garment Closures & Fabric Waterproofing) while the regular duster only has one (Garment Closures).

image
image

Looking at similar recipes (trenchcoat and sleeveless trenchcoat) it seems that the duster recipe is missing the fabric waterproofing proficiency.

### Steps To Reproduce

1. Level tailoring to 3+
2. Open the crafting menu.
3. Check the duster and sleeveless duster recipes.

### Expected behavior

Proficiencies should be consistent between similar items.

### Screenshots

_No response_

### Versions and configuration

- OS: Any
- Game Version: d0fb1f3
- Graphics version: Any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by guralub**
#### Summary
Bugfixes "Fix inconsistencies on all dusters/sleeveless dusters"

#### Purpose of change
Fix #50118, as well as fixing the time to craft on all recipes for sleeveless dusters.

#### Describe the solution
I removed the Fabric Waterproofing requirement from the sleeveless duster recipe, which solves #50118.
I also reduced the time to craft from all sleeveless duster variants by 15% of the respective original recipe to match the suggestion in the JSON comment of those recipes.

#### Describe alternatives you've considered
None.

#### Testing
I checked the proficiency requirement and the time to craft of everything that I've change and it seems correct. 

#### Additional context
image

### CODE REVIEW

**Comment by Maleclypse** [comment]
I think the line count of changes on this far outstrips changes to Duster's alone?

**Comment by guralub** [comment]
> I think the line count of changes on this far outstrips changes to Duster's alone?

I think the linting did some changes to lines unrelated to the duster's changes. That might be the reason

**Comment by actual-nh** [comment]
> I think the linting did A LOT of changes to lines unrelated to the duster's changes. That might be the reason

How were you doing the JSON linting?

**Comment by guralub** [comment]
> How were you doing the JSON linting?

I used  http://dev.narc.ro/cataclysm/format.html to do the linting

**Comment by actual-nh** [comment]
Actually, a lot of it seems to be from your first commit (<https://github.com/CleverRaven/Cataclysm-DDA/pull/50240/commits/219aa03ee3230549297c95f2bd09e7e02311b94c>); some files got included in the commit that shouldn't have been (out/build/x64-Debug/CMakeCache.txt, for instance).

**Comment by guralub** [comment]
Well, I think I fixed it, so now it should only have the relevant changes and the linting. Fingers crossed!

**Comment by Brambor** [comment]
@guralub If you know how, you could remove the two complementary "introduced x", "reverted introduction of X" by rebasing to make cleaner history.

**Comment by actual-nh** [comment]
> @guralub If you know how, you could remove the two complementary "introduced x", "reverted introduction of X" by rebasing to make cleaner history.

How does one do that in Visual Studio, which guralub is using?

**Comment by Brambor** [comment]
> > @guralub If you know how, you could remove the two complementary "introduced x", "reverted introduction of X" by rebasing to make cleaner history.
> 
> How does one do that in Visual Studio, which guralub is using?

I have no idea, I would google for a bit and then stick to the command line, which I feel is not more complicated.

1. Just install git if Visual Studio doesn't provide it.
2. `cd` to the folder
3. git rebase
4. move the complementary "revert X" after "X" commit
4.5. press enter, ctrl+s (or ESC, w+q, enter in vim) and enjoy local cleanliness
5. `git push --force` to enjoy cleanliness remotely (in this PR)

It really does sound easy to me.

If you screw up in the process, just `git reset --hard` to the remote branch and start over. The best & safe way to learn git!

**Comment by guralub** [comment]
Thanks everyone, I'll try to follow Brambor instructions and see if I can clean this mess.

**Comment by guralub** [comment]
I think I grabbed one more commit than I should've, lol

**Comment by Brambor** [comment]
> I think I grabbed one more commit than I should've, lol

`git rebase master` maybe solves that...

**Comment by Brambor** [comment]
> I think I grabbed one more commit than I should've, lol

If it really doesn't work I think you can:

1. rebase interactively
2. drop the commit you added by accident
3. rebase onto master

this should not mark you as commuter and therefore solve this issue

**Comment by guralub** [comment]
I finally did it, thanks @Brambor , @actual-nh , my mother and father. Without you I wouldn't be able to achieve this.

**Comment by Maleclypse** [comment]
Has this been linted? It looks like it's in the jsonlint.com dialect instead of CDDA's dialect.

https://dev.narc.ro/cataclysm/format.html

**Comment by guralub** [comment]
> Has this been linted? It looks like it's in the jsonlint.com dialect instead of CDDA's dialect.
> 
> https://dev.narc.ro/cataclysm/format.html

I think with me trying to undo the mess yesterday I messed up with the linting too

**Comment by Brambor** [comment]
> > Has this been linted? It looks like it's in the jsonlint.com dialect instead of CDDA's dialect.
> > https://dev.narc.ro/cataclysm/format.html
> 
> I think with me trying to undo the mess yesterday I messed up with the linting too

But you could use what you learned yesterday and squash two linting commits together to pretty much annihilate them ;)

**Comment by guralub** [comment]
> But you could use what you learned yesterday and squash two linting commits together to pretty much annihilate them ;)

Nooo, not again! I'll try doing that later

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
