### PR TITLE
Maintenance for Expanded Realistic Guns

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Added count to itemgroups

### CODE REVIEW

**Comment by DangerNoodle** [comment]
One thing I neglected when I first combined the revolver edit with my weapon additions. I had intended to change the 10mm Auto revolver in the mod to instead use copy-from so that a full override is not needed. Reducing the amount of code vulnerable to desync with mainline is always useful.

I have been busy lately and thus unable to experiment with how to branch off of your fork and otherwise attempt to collaborate.

**Comment by BorkBorkGoesTheCode** [comment]
Am incorporating @DangerNoodle 's gun entry simplification PR into this one.

**Comment by mugling** [comment]
Looks fine but needs rebase

**Comment by BorkBorkGoesTheCode** [comment]
Well, I closed this PR to keep notifications down while I used git fetch-git rebase origin/master, but now I cannot reopen it. I now know why companies pay peple 75,000 dollars to manage git.

**Comment by DangerNoodle** [comment]
That bodes unwell.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle would you like me to send you a transcribed copy of your changes, s you can PR separately?

**Comment by BorkBorkGoesTheCode** [comment]
Look for patch-55 if you're going to copy.

**Comment by DangerNoodle** [comment]
Very well then, it might be good to do so.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle patch-65 is clean and without git issues.

**Comment by DangerNoodle** [comment]
Ah, I see. Any pull request for it? I was going to simply take the changes listed in the pull request, then use them in a pull request dervied from a freshly updated master branch.

**Comment by BorkBorkGoesTheCode** [comment]
I was intending to PR the changes into your repository, but I discovered that patch PRs cannot be made across forks.

**Comment by DangerNoodle** [comment]
Ah, strange. Apologies for that. Any changes in patch 65 other than what is in this pull request?

**Comment by BorkBorkGoesTheCode** [comment]
Not to my knowledge, but it would be good to check again. I'll check patch 65 again.


PSEUDOEDIT: other than combining all of your changes into two files (one fixed my transcription error.), no other visible changes were made to your PR. However, something has been adding random UTF-8 to my recent PRs, so a hex check may be needed.

**Comment by DangerNoodle** [comment]
Odd. Seems to appear viable when copied from viewing whole files, except the final line of any section copy-pasted loses some of its initial spaces. Easily dealt with.

**Pull request closed without merging**
