### PR TITLE
Last Chance Gas

### PR DESCRIPTION
**Pull request by John-Candlebury**
Actually a pretty nice, small, old style wooden gas station that spawns by roads. Only small cities can generate them (sizes 1 to 3)

### CODE REVIEW

**Comment by Dozed12** [comment]
An office tower and a gas station in one day, Nice!

**Comment by John-Candlebury** [comment]
Thanks!

**Comment by vache** [comment]
Quick note: the city sizes part of overmap specials isn't implemented yet.

**Comment by John-Candlebury** [comment]
Dang! Well let me make some small changes then.

**Comment by KrazyTheFox** [comment]
It looks like one of your spawn groups is misplaced (homebooks; the red box in the middle):

homebooks

It's great to see some new buildings added to the game! I look forward to seeing these in action soon.

**Comment by KA101** [comment]
Go ahead, I'm going to be a while getting the build-bugs sorted, I fear.

**Comment by vache** [comment]
I like the map editor!  Looks like a much better version of one I started working on in the past and never finished: http://imgur.com/8MtYvnV.  One problem you'll run into just having the terrain/furniture icon in the palette is that it hides important information, especially with doors and the various combinations of closed/locked/locked_inside.

**Comment by KA101** [comment]
Yeah, I'd be curious to get a copy of that if it works on XP.

**Comment by KrazyTheFox** [comment]
Thanks! It's very much a WIP (I even have an overhaul of the interface planned out) and that particular problem will be solved better than it is so far when I work out the details (the bottom left of the status bar currently tells you exactly what the tile is). The plan right now is to group variations on tiles together somehow and allow you to pick the variation you want.

I'm absolutely planning to release it once it's ready for general use. It's written in Java using JavaFX 8, so it'll be compatible with just about anything (I'll probably have releases that also bundle Java). The repo is here if you'd like to take a look at it so as not to completely derail this PR: https://github.com/KrazyTheFox/Cataclysm-DDA-Map-Editor

**Comment by KA101** [comment]
Looking at the homebooks problem, I think that counter's the cash register, etc, so the homebooks are either the owner's personal supply (and should be in the back living quarters) or on one of the display racks.  Based on the "home", gonna put 'em in the quarters as part of the merge.

I'll gladly merge a correction, though.

**Pull request merged**
