### PR TITLE
Create tileset inclusion criteria and cull unsupported sets even if we love them

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
Infrastructure "tileset inclusion criteria and maintenance"

#### Purpose of change

We run the risk of developing tileset bloat, with older tilesets not supported and becoming increasingly unusable without updates.

#### Describe the solution

Adds a simple inclusion ruleset for tiles, primarily that the tileset must have been updated since the last stable, or have a maintainer.

Removes three tilesets that haven't got maintainers and are becoming out of date.

Anyone who wishes to decompose these sets and back them up in the tileset repo is welcome to do so. If someone does that to hitbutton I will happily rescue it.

#### Describe alternatives you've considered

We could leave these, but is anyone seriously using Hodor or chesthole16 at this point?

### CODE REVIEW

**Review by int-ua — APPROVED** [review]

**Comment by Fris0uman** [comment]
I guess I can decompose hitbutton real quick

**Comment by Fris0uman** [comment]
Done: https://github.com/I-am-Erk/CDDA-Tilesets/pull/717

**Comment by int-ua** [comment]
(sadly looks at https://github.com/CDDA-Tilesets/ )

**Comment by I-am-Erk** [comment]
> (sadly looks at https://github.com/CDDA-Tilesets/ )

We can continue pushing that stuff too, I honestly forgot we were working on that after my absence

**Comment by ZhilkinSerg** [comment]
Let's move obsolete tileset to tilesets repo?

**Pull request merged**
