### PR TITLE
[CR] SDL Drawing: Load textures as a whole image and add color filtered tile varieties to the same texture

### PR DESCRIPTION
**Pull request by DanmakuDan**
Currently, the tileset loader generates a few thousand mini textures to hold each tile cut out from the tileset. There is probably some performance lost in how the renderer handles constant source texture switching. This PR modifies the loading routine to save the image as a whole, generate the color filtered varieties (dark, night vision, etc) and pastes it into one large image, which gets converted into the tileset texture. Each image that gets loaded will be a separate texture atlas, instead of each tile. 

The coordinates needed to cut out each texture to paste to the screen are stored in a new unordered map that maps every tile to a SDL_Rect and specific image. 

Overall, this seems to save ~10% of the usual drawing time. Testing on default Direct3D renderer on integrated graphics on a mediocre laptop, 34ms -> 29ms drawing time was observed for a large field, 10.5ms -> 9ms on a laptop with better CPU/GPU.

### CODE REVIEW

**Comment by mugling** [comment]
How much memory does a typical tileset consume?

**Comment by DanmakuDan** [comment]
A large tileset like ChestHole32 has a dimension of 512x12000 for the main texture and 512x8192 for fallback, which is about 41 MB based on 4 bytes per pixel, 164 MB total considering color filters that are applied. There isn't much change in memory usage since the textures are just contained in a contiguous space instead of individual pieces. The normal loading process probably doubles that temporarily during tileset loading (surface + texture).

The memory usage could be reduced by having shaders do the color filtering work, but I think that requires additional OpenGL libraries doing the game drawing.

**Comment by mugling** [comment]
I haven't read the SDL code much at all but have you considered the effect of not being able to store the texture in graphics memory?

**Comment by DanmakuDan** [comment]
The tileset should be in graphics memory already from using SDL_Textures to contain the data that will be rendered to screen. SDL_Surfaces are used to process the images (adding color key/transparency, color modification) before they are converted into SDL_Textures.

**Comment by DanmakuDan** [comment]
Closing this for now, will look into using SDL_gpu for related performance enhancements.

**Comment by mutability** [comment]
You may be interested in this as a starting point: https://github.com/mutability/Cataclysm-DDA/tree/sdlgpu_hackery

**Pull request closed without merging**
