### PR TITLE
Change 'Switch Gender' to 'Fix Gender Label', etc

### PR DESCRIPTION
**Pull request by Little-119**
Forget it.

### CODE REVIEW

**Comment by Little-119** [comment]
It changes the bit of text saying whether your character is male or female and changes their sprite.

Whatever. Forget it. Forget I submitted this PR, christ.

**Comment by ZhilkinSerg** [comment]
> 
> 
> It changes the bit of text saying whether your character is male or female and changes their sprite.

It affects dialogs and memorials as well.

**Comment by Little-119** [comment]
> 
> 
> > It changes the bit of text saying whether your character is male or female and changes their sprite.
> 
> It affects dialogs and memorials as well.

Doesn't affect my point

**Comment by ZhilkinSerg** [comment]
> > > It changes the bit of text saying whether your character is male or female and changes their sprite.
> > 
> > 
> > It affects dialogs and memorials as well.
> 
> Doesn't affect my point

It renders your PR unnecessary.

**Comment by Little-119** [comment]
I don't see how gender changing the text of dialogue and memorials affects how necessary my PR is.

Look, @ZhilkinSerg, it's your opinion that my PR is unnecessary. I have my opinion. You have your worldview, I have my worldview. Let's leave it at that.

**Comment by ZhilkinSerg** [comment]
I am not talking world views here. You propose to change the label to a misleading string.

**Comment by I-am-Erk** [comment]
Friends, this is a waste of time, you're taking past each other. Zs, the OP actually has a point about phrasing. However, little-119, with all the dog whistling going on around this topic right now it is a very tricky time to include a bit of humor.

**Comment by Little-119** [comment]
> Friends, this is a waste of time

I know, which is why I already said Z and I are not going to change each other's mind and this should just be dropped.

>However, little-119, with all the dog whistling going on around this topic right now it is a very tricky time to include a bit of humor.

I know, I understood that I was taking a risk with this. I hoped the fact that I'm non-binary would be enough.

**Comment by kevingranade** [comment]
Protip, if you say, "we should drop this" more than once, you're part of the problem, because you can just stop posting at any time.

As for your orientation, we don't know you, so you can't really expect accommodation on that front.

**Pull request closed without merging**
