### PR TITLE
Avoid misplaced portal traps

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Bugfixes "Avoid misplaced portal traps"

#### Purpose of change
In #53506, the exhaustive mapgen test was disabled due to a few issues.

We want to fix them and re-enable the test.

#### Describe the solution
Two major fixes:

* Predecessor mapgen was using the wrong mapgen key.  It was using the `oter_str_id`, which doesn't work when the terrain rotates or is linear.  In particular this was causing issues for anthills on forest trails.  Fix that by using the proper key.
* A couple of hardcoded mapgens were placing portal traps on open air.  This was because the rubble-creation associated with portals sometimes broke the floor and left it open.  That caused an error message because the mapgen was trying to place the portal on another trap.  Fix by re-checking before placing the portal.

Edit: additional fixes:

* Fix the manner in which predecessor mapgen is looked up to use the proper key.

~With those changes in hand, re-enable the test.~

#### Describe alternatives you've considered
The portal thing could have been fixed differently, maybe by resetting the terrain to something not open air, or somehow allowing portals in the open air?

#### Testing
I tried about 50 different random seeds and this fixed all the errors that arose.  There are probably more, but this seemed enough to warrant re-enabling the test.

#### Additional context
These were both genuine mapgen bugs that would have caused issues in play, so this demonstrates that the mapgen test is working as intended, and discovering the mapgen bugs I was hoping it would.

### CODE REVIEW

**Comment by kevingranade** [comment]
What an exciting error
([slow] ~crafting_skill_gain)=> 139.178 s: mutable_overmap_placement
([slow] ~crafting_skill_gain)=> src/mapgen.cpp:2388:17: runtime error: load of value 114, which is not a valid value for type 'bool'
([slow] ~crafting_skill_gain)=>     #0 0x112cb1234 in jmapgen_trap::apply(mapgendata const&, jmapgen_int const&, jmapgen_int const&) const+0x374 (cata_test:x86_64+0x102f08234)
([slow] ~crafting_skill_gain)=>     #1 0x112c3426e in jmapgen_objects::apply(mapgendata const&) const+0x26a (cata_test:x86_64+0x102e8b26e)
([slow] ~crafting_skill_gain)=>     #2 0x112c31f72 in mapgen_function_json::generate(mapgendata&)+0x562 (cata_test:x86_64+0x102e88f72)
([slow] ~crafting_skill_gain)=>     #3 0x112c7cd9a in mapgen_basic_container::generate(mapgendata&, int) const+0x1fe (cata_test:x86_64+0x102ed3d9a)
([slow] ~crafting_skill_gain)=>     #4 0x112c55a10 in mapgen_factory::generate(mapgendata&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const+0x86 (cata_test:x86_64+0x102eaca10)
([slow] ~crafting_skill_gain)=>     #5 0x112c04fbd in map::draw_map(mapgendata&)+0x7f (cata_test:x86_64+0x102e5bfbd)
([slow] ~crafting_skill_gain)=>     #6 0x112c03e25 in map::generate(tripoint const&, time_point const&)+0x71f (cata_test:x86_64+0x102e5ae25)
([slow] ~crafting_skill_gain)=>     #7 0x112a93c2b in map::loadn(tripoint const&, bool, bool)+0x11c9 (cata_test:x86_64+0x102ceac2b)
([slow] ~crafting_skill_gain)=>     #8 0x112a8ecad in map::loadn(point const&, bool, bool)+0x2b1 (cata_test:x86_64+0x102ce5cad)
([slow] ~crafting_skill_gain)=>     #9 0x112a8e27a in map::load(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool, bool)+0x5d0 (cata_test:x86_64+0x102ce527a)
([slow] ~crafting_skill_gain)=>     #10 0x1107f0087 in ____C_A_T_C_H____T_E_S_T____17()+0x19a1 (cata_test:x86_64+0x100a47087)

Followed by a sigabrt

**Comment by jbytheway** [comment]
Ooh, a UBSan error.  Always nice to get one of those.

**Comment by jbytheway** [comment]
UBSan error should be fixed.  I've run across one more lab-trap-placement-related error that I'm working on now.

**Comment by jbytheway** [comment]
Further investigation revealed a whole herd of yaks to be shaved before the mapgen test can be safely re-enabled.  That's going to take a while, and in the meantime this PR has some useful stuff in it.  So I've pulled out the commit that actually re-enables the test and left the test in this PR.  I'll probably open a few more PRs to fix all the other related issues before coming back around the the mapgen test once it's safe to do so.

The fixes in this PR are already a bit of a mishmash.  Let me know if they should be separated out.  If not, I'm hopeful this should now be good to go.

**Pull request merged**
