### PR TITLE
Add screen readers and dictation software to computers for accessibility

### LINKED ISSUE #16348: Every computer has accessibility features, let's let illiterate people use them.
Every major OS has built in accessibility features, isn't it corporate discrimination that the ones in CDDA don't? I think we should change computers to let blind and illiterate players use them, like in real life.

Also, this would make Illiterate playable.

### PR DESCRIPTION
**Pull request by lucianposton**
Fixes #16348 

Because it's ambiguous post-2015 future year, in cdda.

### CODE REVIEW

**Comment by illi-kun** [comment]
You need to implement screen readers as dedicated software if you want to see them in game. Simple removing of limitations is not OK (and you missed a block about glasses right below).

**Comment by lucianposton** [comment]
> you missed a block about glasses right below

Thanks, missed that restriction. Updated PR to fix this.

> You need to implement screen readers as dedicated software

What do you mean by implementing it as _dedicated software_?


>  Simple removing of limitations is not OK

Why?

**Comment by illi-kun** [comment]
It's not okay because OS by default provides very limited accessibility features.

**Comment by lucianposton** [comment]
>  It's not okay because OS by default provides very limited accessibility features.

Actually, the majority of irl modern-day OSes (e.g. windows, osx, linuxes/BSDs with GNOME/Unity desktops e.g. ubuntu) come pre-configured with screen readers and dictation software, which would be sufficient for the computer applications I've encountered in cdda. I see no reason why the cdda universe would be worse in this regard. Anyway, this is more of a discussion point for https://github.com/CleverRaven/Cataclysm-DDA/issues/16348 .

**Comment by illi-kun** [comment]
They are not enabled by default, so its activation requires some computer skills (at least).

**Comment by narc0tiq** [comment]
If it were relatively standardized, then an illiterate person living in that world up to that point would be expected to know the standard method to activate it.

You could technically pretend there are different methods which the character might or might not know: use the world position to gen up a number between, say, 0 and 3, and if it's less than or equal to the character's computer skill, then the character knows how to activate the screen reader function. This also gives you a chance to have the character learn how to use unfamiliar systems. Alternately, tie it to something more permanent about the character, like a genned-up number based on their name.

**Comment by player0981234** [comment]
Some computers in special places such as military buildings or labs are likely to have no such software built-in so you need to add those accessibility softwares as a separate software item

**Comment by John-Candlebury** [comment]
Can an illiterate person actually read the keyboard? I dont  think they can. They might at best memorize some letters from their position, but even then anything that involves writing stuff is impossible. So you're not hacking anything, pretty much removing any point of wanting to interact withcomputers.  
You could probably only "read" the starting shelter computer.

I think it would be much better to let NPCs to interact with computers for us in this case.

**Comment by Rivet-the-Zombie** [comment]
>Some computers in special places such as military buildings or labs are likely to have no such software built-in so you need to add those accessibility software as a separate software item

This right here. There's a surprising number of corporate and military systems out there in the real world that are still running on stuff like DOS or Win95 right now.

**Comment by SeanMirrsen** [comment]
>Can an illiterate person actually read the keyboard? I dont think they can. They might at best memorize some letters from their position, but even then anything that involves writing stuff is impossible. So you're not hacking anything, pretty much removing any point of wanting to interact with computers. You could probably only "read" the starting shelter computer.

An illiterate person can use a screen reader to have text on the screen read out to them, can use the mouse or keyboard arrow keys to manipulate the text input cursor, and can speak into a mic to let a speech-to-text program write for them, assuming they have such software on hand.

**Comment by Rivet-the-Zombie** [comment]
What good is text-to-speech mode going to do an illiterate if it hasn't already been turned on when they get there? You have to enable text-to-speech mode since it's not an option that defaults to 'on' in like, any OS ever, and an illiterate character can't read in order to find the menu for enabling accessibility options in the first place.

**Comment by lucianposton** [comment]
> What good is text-to-speech mode going to do an illiterate if the option hasn't already been activated when they get there? You have to enable text-to-speech mode since it's not an option that defaults to 'on' in like, any OS ever, and an illiterate character can't read in order to find the menu for enabling accessibility options in the first place.

As @narc0tiq said above, standardized methods of enabling accessibility features and/or computer skill. Nobody's suggesting these features would be on by default. Even in irl modern-day OSes, you can enable text-to-speech with a single hotkey, not to mention other accessibility features and how progressive the ambiguous post-2015 future cdda year must have become prior to the cataclysm.

**Comment by BevapDin** [comment]
Illiterate people *may* be able to handle certain common consoles, for example an ATM. They may be used to follow a standard procedure someone else showed them (press top-left button, enter PIN, press bottom-left button, enter amount, press top-left button). But machines from different banks (or just different machines) may have the buttons at different places, so this may not works all the time.

Unusual (military) or unknown (in shelter) devices should be right out.

----

`Character::is_blind` includes various forms of blindness (wearing a blindfold, having boomer stuff in ones eyes). Those are temporary and the character is not used to them.

Even with suitable software (screen reader) or hardware (braille display) one would typically not be able to handle them without training. And non-blind people rarely train for this situation. How many (non-blind) people can activate the screen reader while being blind? Who can even enter commands (correctly!) on a keyboard while being blind. That should at very least require some computer skill, and hope the console uses the known layout (which is not guaranteed).

Similar for braille display: I expect only few people with eyesight to be able to read those. Wearing a blindfold does not grant braille knowledge.

For certain public (and common) machines like ATM, which have a simple standardized interface, one may be able to access them when blind. But even that would require a bit training.

----

And screen readers (if enabled at all) should make noise.

**Comment by kevingranade** [comment]
BevapDin hit on the key point here, the "can't currently see" condition in
the game is not the same as someone who has been blind for a long time.  If
someone were to add a set of features for permanently blind players, screen
readers would be perfectly reasonable to add, but for temporarily blinded
or illiterate players, it doesn't make sense.

**Comment by WizardOfOoo** [comment]
The issue is that being "illiterate" locks you out of the entire endgame.  No other trait even comes close.   Make Illiterate a 12 point flaw if you don't want illiterate PCs to have access to the endgame.

**Comment by illi-kun** [comment]
This PR doesn't implement the feature announced in title (it adds nothing, just revert newly introduced constrains). It's much better to move current discussion to the initial issue.

**Pull request closed without merging**
