### PR TITLE
added a bionic that helps you fall asleep

### PR DESCRIPTION
**Pull request by thquinn**
#### Summary
```SUMMARY: Content "Adds a bionic that lets you fall asleep instantly"```

#### Purpose of change
I kept seeing the same CBMs over and over in research facilities, thought it would be cool to add more "civilian" utility modules. Maybe they're doing sleep studies there? I've always wished I could fall asleep on command...

#### Describe the solution
I added a check right at the beginning of ```player::can_sleep()```, so it works even if the player is on meth. This means that you can just conk out on the floor, in the middle of a fight, and so on. But! The module might get you to sleep, but staying asleep is your problem. You can still immediately get woken up by stimuli, or even after a couple of minutes if you're just not tired.

I also put it in the ```bionics```, ```science```, ```bionics_tech```, and ```bionics_sci``` item groups at relatively low frequencies.

Let me know if I can fix anything!

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I think this bionic needs to drain some bionic power whenever player tries to fall asleep. An electrode stimulating some particular area in the brain needs power to operate, you know. Besides, it's a balance question - install-and-forget-and-no-power-is-required stuff is OP (and not so interesting in my opinion). 

Overall, looks good.

**Comment by Mecares** [comment]
Bionics like that make me want an enemy in the game that can randomly activate your bionics remotely, it would be horrible.

**Comment by thquinn** [comment]
@Night-Pryanik Done. I made the cost 1, since it's gotta be a really small current.

@Mecares Great idea! It could be as simple as making bionics sometimes react to being electrocuted. It would make people with tons of bionics think twice before going up against shocker zombies.

**Comment by 0be1isk** [comment]
So essentially this bypasses any and all sleeping traits so I don't have to choose any negative ones? Seems like a balancing issue there

**Comment by thquinn** [comment]
@0be1isk It definitely negates Insomniac, but I'm not sure why that's necessarily a balancing issue unless I add it to a profession. Could you explain?

**Comment by kevingranade** [comment]
There are a number of mechanics in the game that adjust how hard it is to fall asleep, this negates all of them.
Instead of overriding everything and forcing sleep, this could give a bonus to effective tiredness to make falling asleep easier.

**Comment by thquinn** [comment]
@kevingranade Changed it to a bonus, and it now consumes power with each sleep check.

**Comment by Photoloss** [comment]
The power consumption seems unrealistically high. One unit of battery is supposed to represent 1kJ of energy. Just for an order-of-magnitude estimate [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4507613/)'s a publication which declares 5-10V a "high-voltage" stimulus in this context and [here](https://pubs.rsc.org/en/content/articlelanding/2015/ee/c5ee01593f)'s one wanting to power brain electrodes with flexible electronics yielding "an extremely high current reaching 0.57 mA". At those specs a *single* battery charge could power the electrodes for **almost two days straight!**

Now of course a computer-based monitoring system will consume a fair bit more than the electrode on its own but the total will still be laughably small. If any additional "cost" is desired for gameplay reasons then power consumption definitely is the wrong approach to any kind of neural stimulation short of electrocution. And yes I know 1 charge per "attempt" is negligible in gameplay terms anyway.

**Comment by thquinn** [comment]
@Photoloss That was my thinking when I had it not require battery at all. Maybe in order to represent the near-zero battery usage, I could only have it require battery power to be present, but not actually use it?

**Comment by Photoloss** [comment]
@thquinn If the code allows it could easily be made entirely self-sufficient, harvesting energy from body heat or neck movement for example. Of course it would be more interesting with some kind of tradeoff or downside, sadly I don't know any actual medical studies on artificially induced sleep but as far as sci-fi goes it could for example go haywire when you suffer an electric shock and cause a large amount of fatigue (*not* full-on narcolepsy, that's *way* too severe for what this thing offers). Or it could be similar to the Leukocyte CBM with you becoming dependent on it the more you use it.

That would be a lot of extra work though and I have no idea how valuable the benefit actually is to warrant any such drawback. Since the autodoc required for its installation often spawns in close proximity to bedding material and full-on beds I personally don't see much value in having this CBM in the first place beyond trivial QoL.

**Comment by thquinn** [comment]
@Photoloss I disagree that the QoL is trivial. Bedding is common everywhere, but there are traits/stasuses that make it harder to sleep even with that. And what if you're roaming around on foot, not sure where you're going to sleep next, but don't want to carry a pillow and blanket with you? Given that sleep checks only happen every 30 minutes, failing them burns quite a bit of time. Overall, if it's worth having a positive trait for, it should be worth having a bionic for (although I admit that the appeal is much lower now that it's not a guaranteed KO).

@Night-Pryanik Do you have an opinion on power usage now that it's a "slow burn" rather than a jolt? I agree with Photoloss that 1/30 min seems high for an electrode. Is the notion of requiring battery to be present, but not actually consuming it, too illogical? It's meant to suggest that it's using an extremely low amount.

**Comment by Night-Pryanik** [comment]
> It's meant to suggest that it's using an extremely low amount.

Well, I didn't know that when I suggested adding a power to activate. In that case I think requirement for a battery might not even be needed, but that's only me.

**Comment by thquinn** [comment]
Removed power usage and fixed merge conflict. I kept the requirement for battery to be present; I agree with the original comment that it doesn't make sense to be delivering a current when your batteries are totally empty.

**Pull request merged**
