### PR TITLE
Fixes incorrect blob harness maturation.

### PR DESCRIPTION
**Pull request by aWinglessMonkey**
Fixes growing blob harness maturing into a blob seat instead of blob harness.

(#13969)

### CODE REVIEW

**Comment by Salganos** [comment]
So ... I committed this to my master branch, since the topic fork wanted to pull to there.  Then I pull requested my master branch, but its saying I'm pull requesting the topic branch.

How does I github?

**Comment by Salganos** [comment]
I've been made aware that there is a much more up-to-date, but not built-in, version of this mod, most likely not containing small errors like this (or at least not this one).  Not sure what to do about that, but I am now curious as to why.

**Comment by chaosvolt** [comment]
I've occasionally volunteered to port over Blaze's updates to Github, but I only did so successfully once. The second time I lost interest rapidly because his version retained a ton of formatting and indentation issues that had long since been fixed on the Github version. Had to unfuck it personally, then it went unmerged for a while until merge conflict ensued.

Might see how Blaze's version is coming along, but I'd rather leave porting over the latest version to them. @_@

**Comment by Salganos** [comment]
I can probably just close this and take it as a learning experience on how to start a pull-request (from github) that has access to the full base/head lists, for future reference.

**Comment by chaosvolt** [comment]
No worries. I know I did some derpy things on my first PR. And I still do. XP

**Pull request closed without merging**
