### PR TITLE
Allow JSON linear terrain and unhardcode anthill mapgen

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Infrastructure "Allow JSON-defined linear terrain and unhardcode anthills"

#### Purpose of change
We want to move more mapgen from hardcoded to JSON.

One major obstacle to that was linear terrain, which previously only supported hardcoded mapgen.

Linear terrain is used for things like roads and tunnels that must connect from one OMT to the next.

#### Describe the solution
This is a PR built on top of #51317 and includes the changes therefrom.  It fixes the biggest issue with #51317 in that now ants spawn properly in the tunnels as they should.

The additional changes are:
* Remove all the code related to old hardcoded ant mapgen, both at the overmap and tile level.
* JSON-defined mapgen for linear terrain will now be correctly rotated.  This fixes the problem that previously existed with JSON linear terrain.
* Use that capability to define JSON versions of the ant tunnel terrain.
* Also define all the other ant terrains in JSON (this could have been done at any time, but it makes sense to do it in this PR).
* Make all the ant terrains rotatable.  This is needed to get e.g. the openings for the food, larva, and queen chambers to line up.
* Add migration for the old ant terrains to the new ones.  This is pretty simplistic and will cause some chambers to become disconnected in existing anthills, but it's just a temporary problem.
* Add documentation.

#### Describe alternatives you've considered
My ant tunnel definitions are pretty simplistic.  For example, all chambers are exactly the same layout.  There's plenty of room for improvement, but they're roughly as interesting as the old ones, so I think it's sufficient for now.

Currently I've completely removed all acid anthills.  I want to re-add those but it requires either (a) duplicating everything to define a bunch of nearly identical terrains or (b) adding new mapgen parameter features to allow them to be used in overmap special and overmap terrain definition.  I want to do (b) but it is a major new feature, so it would be too much for this PR.

The bug of not being able to escape from anthills is also still present.  The fix I have planned for that also requires a new feature.

#### Testing
Loaded old games and verified migration works.  Teleported to new overmap and verified that new anthills are generated.

#### Additional context
Some screenshots follow.  The ones with no ants were because I did some testing before I added the ant spawns to these new terrains.
ant-tunnels-new-with-ants
anthill-new
ant-ends-new
ant-tunnels-new

### CODE REVIEW

**Comment by Venera3** [comment]
Is this limited to mutable specias, or can one straight up define a new connection type with JSON mapgen?

**Comment by jbytheway** [comment]
> Is this limited to mutable specials, or can one straight up define a new connection type with JSON mapgen?

You can define a new linear terrain type and use it in fixed or mutable overmap specials, but it won't be a connection, in the sense that connections can be defined for roads and subways.  Those connect different specials together.  That is yet to be JSONized.  This was an important step in that direction, but we're not there yet.

**Comment by jbytheway** [comment]
CI looks clean except for LGTM, and I can't tell what went wrong there; maybe just a timeout.

**Comment by Night-Pryanik** [comment]
Should this close #24628?

**Comment by jbytheway** [comment]
> Should this close #24628?

No, the monster spawning is using the same mechanism, so I'd expect that issue to be the same.

(That said, in the future I want to make it so that ant tunnels connect with other underground stuff like the basement, so perhaps we can fix that bug by making the tunnels penetrate the basement, rather than by stopping the spawning ;)).

**Pull request merged**
