### PR TITLE
Fix incorrect colors

### PR DESCRIPTION
**Pull request by cake-pie**
#### Summary
```SUMMARY: Bugfixes "fix incorrect colors"```

#### Purpose of change
Remove warning in debug log
`couldn't parse color: c_light_magenta`
due to invalid colors used in 32061165a992e565f43df3c1cc0d96277dbfb355

#### Describe the solution
change tulips in `data/json/furniture.json` and `data/json/items/generic.json`
~`"color": "light_magenta",`~
`"color": "magenta",`

---
@cosmiccoincidence, please check your color choices before use.
Previously, 6ac09959d4c157be621dde6cb208dd2628c7c6db (fixed #25393) and e6a6473f147d5bf85d2fa11c27f16e0300994f43 (fixed #24934) also had invalid colors.

### CODE REVIEW

**Comment by Qrox** [comment]
We could perhaps show a in-game debug message if invalid colors are encountered.

**Comment by ZhilkinSerg** [comment]
> We could perhaps show a in-game debug message if invalid colors are encountered.

Invalid colors are already written to debug.log. These errors are not game breaking and there is no sense to show message to player.

**Comment by Qrox** [comment]
> > We could perhaps show a in-game debug message if invalid colors are encountered.
> 
> Invalid colors are already written to debug.log. These errors are not game breaking and there is no sense to show message to player.

It can notify json writers of incorrect color names they've chosen as soon as the game is loaded, and I think it's better than requesting them to remember checking the log each time they modify json files. Also, if there's no invalid color names in the json files, players will not likely actually see the debug message, unless they're writing their own mods, but then they may actually want to see it.

**Comment by ZhilkinSerg** [comment]
Displaying the message would only annoy players using with old non-mainline mods which are barely supported.

Logs are enough for mainline mods.

**Pull request merged**
