### PR TITLE
Fix multi select for washing

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary

SUMMARY: Bugfixes "Allow wash multiple items instead of just one for every stack"

#### Purpose of change

Fix [#40404](https://github.com/CleverRaven/Cataclysm-DDA/issues/40404)

#### Describe the solution

The i_use selector can only track 1 item per stack, it is designed for using one items with charges, this is not suitable for washing dirty items. The drop selector may do the job, but it does'nt have a parameter to track how much water/cleanser are used, moreover, the filter for dropping is not necessary here.

So I made a combination of both selectors, mostly only copy & paste, so it should not cause any serious problems.

#### Describe alternatives you've considered

Somehow play with inheritance?

#### Testing

Spawed 40 filthy items in one stack, washed them all with a single selection.

### CODE REVIEW

**Comment by bloodraven983** [comment]
did you consider that different items should consume different amount of detergent? guess depends from weight and volume of said items. so 40 rags should not consume 40 amounts of detergent

**Comment by Menschheit** [comment]
The original code is strong enough. AFAIK there should not be any problem with detergent consumption.
But better test it yourself. I am struggling learning how to deal with git and astyle and reading online c++ tutorial at the same time so I cant guarantee that I didn't do sth stupid. ( I am trying to learn coding and fix easy bugs cuz the current game is too buggy while I just happen to  have some time to play),

**Comment by EvgenijM86** [comment]
You can use "make astyle" command to automatically apply all astyle suggested fixes. Well, at least if you are using Linux. Not sure what you need to do on windows.

**Comment by anothersimulacrum** [comment]
If you're using msys, you can do that.
If you're using VS, there's an astyle extension.
Otherwise, you can install astyle and use this bat script (from the same directory as the .git file): 
```sh
echo off
astyle --options=.astylerc --recursive src/*.cpp,*.h tests/*.cpp,*.h
```

**Comment by Qrox** [comment]
Why not just modify `inventory_iuse_selector` to return every item location in a selected stack? Because as far as I remember it was working this way before and was probably just broken by the new item pocket system. Showing different item locations in a single stack and then only returning the first item location from that stack even if the whole stack is selected doesn't make sense whatever purpose an inventory menu may be used for.

**Comment by Menschheit** [comment]
Basically I would try to do minimal change to the original codes to avoid conflics. Make a new class via copy&paste is easy and more reliable than a hard modification of current classes.  And I do think that the current i_use_selector is useful in some situations like deciding using how many charges for training.
I just started to read the code a week ago so dont know how it looked like before nested containers. I assume that in pre-nested-container-versions there may be no diffrence between stack and charges?

**Comment by Qrox** [comment]
The difference between stack and charges has been there long before nested containers (not that I like it). I'd suggest you modify `inventory_iuse_selector` instead and test whether selecting charges still works. Making new code is easy for sure, but IMHO if you make new code every time instead of trying to understand the code and fix the actual bug the codebase will soon turn into a bloated mess.

**Comment by Menschheit** [comment]
You are right. Using two lists is redundant, they dont not really have a difference, and type conversion between item_location and *item is almost trival, I didn't read that class in detail.
Don't know if selector is called somewhere else and how it is called though, hope it will be fine.

**Comment by Menschheit** [comment]
Always use item_location so that other informations wont be lost during type conversion.  To prevent making a new list to suit `getstats` I changed the corresponding parameter in iuse.cpp.  Seems like the `inventory_iuse_selector`  is only used for washing multiple items by now, so hopefully it would not cause any problem.

**Pull request merged**
