### PR TITLE
Stop towed vehicles from rear-ending tow-ers

### LINKED ISSUE #51228: [0.F-0] Towed vehicles rear end the tower when stopping, and start out set at silly speed
### Describe the bug

Two bugs that may well be related.
When towing a vehicle, the towed vehicle rear ends the tower as often as not when stopping, even if the speed is reduced gradually, or never having been above minimum.

When taking control of a formerly towed vehicle it tends to start out with a silly speed set, such as a value in the hundreds, rather than the expected 0.

### Steps To Reproduce

1. Connect a towing vehicle to a towed vehicle.
2. Drive straight ahead at minimum speed.
3. Stop after towing the vehicle for at least some distance.
4. Either get rear ended or try again until you do.
5. Enter the towed vehicle and start it. Check the speed it's set to reach: it's typically not zero.

### Expected behavior

When speed is reduced gradually, the towed vehicle should roll to a stop before reaching the towed vehicle on any surface (one could argue that grass would be rougher than furrowed earth, but the towed vehicle should stop in time even on a road).

The target speed for a towed vehicle should be reset to zero when the pulling force ceases (i.e. when the cable slackens).

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I've tried to increase the tower vehicles speed from 0 to minimum when the towee approaches to within two tiles to give the towee additional room to stop, but that does not help: the code probably doesn't model a slack cable not propagating any force. This is OK as long as the towee stops in time.

My last towing resulted in the rear ending vehicle hitting and damaging the tow cable part of the tower...

There are also wild swerving and strange catch ups of the towed vehicle (typically causing any wing mirrors on the towed vehicle to be lost by the end of the trip), but these are minor issues: it's impressing towing works at all.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

Bugfixes "stop towed vehicles from rear-ending tow-ers when stopping"

#### Purpose of change

Fixes #51228

Towed vehicles were (almost?) always rear-ending the tow-ers regardless of the speed at which they were towed, as they rolled to a stop while slowing down very slowly when the tow-er was stationary. The reason was that code that normally added a constant braking factor wasn't applied to towed vehicles, In addition to that, vehicle wheel friction remains the same regardless of the terrain and the weight of the vehicle.

#### Describe the solution

This PR addresses the first problem above by applying the standard braking factor whenever the pulling cable wasn't fully extended. This also means you're less likely to be hit by the pulled vehicle while turning (the pulled vehicle still swings when you turn, as it should).

#### Testing

Pulling a road roller backwards (because that's how I happened to hook it up) with a tow truck and stop from minimum speed, driving around at comparatively high speed while turning (sensibly), and reducing speed gradually to see that the towed vehicle still behaved in a reasonable manner. Reducing speed quickly still gets you rear-ended, which is reasonable.

#### Additional context

I tried to address the issue of the cruise speed getting set at weird values in towed vehicles, but failed to find a good solution.
The cause of the problem is that the cruise control gets enabled when the tow cable starts to move the towed vehicle, at which time the cruise speed is set as well. The cruise speed doesn't seem to be changed from then on, and thus remains when the towing has ended.
Not enabling the cruise control results in a jerky movement where the vehicle jumps a number of tiles whenever the cable gets taut and then waits for it to tighten again, which isn't acceptable.
I've been unable to find a suitable trigger for disabling the cruise control, as stopping is basically an absence of actions.

### CODE REVIEW

**Comment by a-chancey** [comment]
Personally, given that towing happens with tow cables, and not a tow bar, underlift or other more rigid towing solution, this actually would be expected behavior since there is only one driver. 

I would expect the braking force to be applied if the tow truck were directly connected to the other via the boom - like if the boom crane could be interacted with in a similar fashion to how a bike rack attaches two vehicles, but this would require a modified version of that code to handle it. The tow truck in game is specifically an underlift tow truck, but there's no way to directly use it as such. 

Back to tow cables - it takes 5 mins to tie a mattress to a bumper which reduces damage by 50%, which makes a lot more sense in a solo driver using a tow cable situation like this

**Comment by PatrikLundell** [comment]
The problem with the current implementation is that you'll crash when stopping no matter what, as there's very little "drag", so you can't drive slower than minimum speed (because there isn't one) to gradually stop. 
It looked like the towed vehicle would coast for some 15 tiles or so at minimum speed if it wasn't stopped by the collision based on how little the speed changed when coasting.

**Comment by kevingranade** [comment]
tow-ers, things that tow, not towers, tall things.
I was so confused.

**Comment by PatrikLundell** [comment]
English is a linguistic train wreck...

**Pull request merged**
