### PR TITLE
Automatically rotate movement in isometric mode

### PR DESCRIPTION
**Pull request by sparr**
The new option affects player movement and remote control non-vehicle driving, so an action mapped to "move north" will actually move northeast (which is the visual "up" direction in isometric mode).

I put this option on the Graphics tab because it's linked to the graphics mode.

I added the rotation in the following places:

`game::rcdrive` is used for driving rc cars (the item, not rc vehicles)

`game::plmove` is used for walking around

`get_direction` used for ... nothing. So I removed it. I suspect this predates `inputcontext`

`input_context::get_direction` is used for many things, some of which are non-isometric even when the game is using isometric tiles. I've added `input_context.set_iso()` to tell an input_context that it should obey the rotation rule. I tried to set this on all the appropriate contexts.

### CODE REVIEW

**Comment by kevingranade** [comment]
Why's it an option? AFAICT the un-rotated movement in iso-like mode is just bad, so we should just do this if you're using iso tiles and it's better.

**Comment by sparr** [comment]
I can definitely make this not-optional.

At the moment, playing in tiles mode is very hard for me due to computer slowness, so this patch needs some playtesting. Once someone(s) says it's OK, I'll push a change to make it non-optional for you to merge.

**Comment by Zireael07** [comment]
No reason for this to be optional, as Kevin says.

**Comment by sparr** [comment]
ok. I haven't found an inputcontext where this doesn't work. just pushed the patch to make it non-optional. I'll merge this if no one tests/complains soon.

**Comment by kevingranade** [comment]
One thing, rule#1 of merging is don't merge your own PRs.

**Comment by sparr** [comment]
@kevingranade roger that

**Pull request merged**
