### PR TITLE
Update bludgeon lengths

### PR DESCRIPTION
**Pull request by johnrdconnolly**
#### Summary

Summary: Balance "Added lengths to `bludgeons.json`"

#### Purpose of change

Added lengths to bashing weapons to override default lengths based on cubed volumes.

#### Describe the solution

Defines `longest_side` for items in `data/json/items/melee/swords_and_blades.json`

The following is a list of the lengths added to items.

- 10cm: rock in sock, 
- 20cm: baton (collapsed), blackjack, glass shiv, makeshift sap, PR-24 baton collapsed, sharp toothbrush
- 40cm: bowling axe, bowling pin, engineer's hammer,
- 50cm: tactical tonfa, tonfa, wooden tonfa,
- 60cm: War flail, peasant flail, foam rubber bat, baton (extended), cudgel, short sledgehammer, Mjolnir, nailboard, PR-24 baton extended
- 70cm: makeshift macauhuitl,
- 80cm: Walking cane, sledghammer (also adjusted weight to match standard 10lb-4500g), mace (all versions), morningstar (all versions)
- 90cm: Baseball bat, aluminum bat, barbed wire bat, homewrecker, nailbat
- 100cm: Battle axe (all versions), bokken (all versions), heavy sledgehammer, shillelagh (all versions)
- 110cm: Golf club (driver)
- 120cm: Warhammer
- 150cm: hockey stick, pool cue
- 180cm: Quarterstaff, L-stick, staff, powered quarterstaff,
- 200cm: lucern hammer (all versions)

#### Describe alternatives you've considered

Tons of tools need to have lengths added, I am keeping this commit to one file with only lengths added seeing as it is my first commit.

I plan to assess lengths on other tools, as well as balancing of sheaths and and the associated tags seeing as adding lengths will add difficulty to transporting many items considering the lack of long bags.

#### Testing

Added to game files and spawned it items. Cudgel no longer can be placed in pocket, other items behave similarly.

#### Additional context

With lengths being added to these items many of them will need to have the associated sheath tags reviewed so that carrying said weapons doesn't become too much of a pain. i.e. hammer shaped weapons should have the `belt_clip` tag since they could be stored similarly to a hammer. I plan to do this in a different commit/PR

I am also considering creating some sort of "stick bag" or another similar container designed to streamline transportation of long items.

### CODE REVIEW

**Comment by johnrdconnolly** [comment]
I added two commits by mistake. The older of the two, aa042 is incorrect, while the newer one, e15a3d, is correct. Not quite sure how to easily remove a single commit without submitting a new PR.

I'm guessing I should have used `git commit --amend` to correct the initial commit..?

**Comment by anothersimulacrum** [comment]
Yeah, that's an easy way to modify a commit.
There are a couple of ways to remove that erroneous commit:
1. You can do an interactive rebase onto master, and drop that commit.
2. You can cherry pick the correct commit onto a separate branch, then hard reset this branch to that one
3. You can hard reset the branch and redo your changes.

I'd recommend either 1 or 2 :).

**Comment by johnrdconnolly** [comment]
> Yeah, that's an easy way to modify a commit.
> There are a couple of ways to remove that erroneous commit:
> 
> 1. You can do an interactive rebase onto master, and drop that commit.
> 2. You can cherry pick the correct commit onto a separate branch, then hard reset this branch to that one
> 3. You can hard reset the branch and redo your changes.
> 
> I'd recommend either 1 or 2 :).

Any chance you can point me towards some directions for either of those options?

I'm having a wonderful time figuring out how to use github:D

**Comment by anothersimulacrum** [comment]
This should help:
[git rebase](https://git-scm.com/docs/git-rebase)
[git cherry-pick](https://git-scm.com/docs/git-cherry-pick)
[git reset](https://git-scm.com/docs/git-reset)

**Comment by johnrdconnolly** [comment]
> This should help:
> [git rebase](https://git-scm.com/docs/git-rebase)
> [git cherry-pick](https://git-scm.com/docs/git-cherry-pick)
> [git reset](https://git-scm.com/docs/git-reset)

I have created another branch and simply re added the commit instead of cherry picking it over. It's called add_bludgeon_lengths. However I am having a hard time properly hard resetting this branch to the correct one.

**Comment by anothersimulacrum** [comment]
It should be (from this branch) 
```
git reset --hard fixed_branch
git push origin update_bludgeon_lengths --force-with-lease
```

**Comment by johnrdconnolly** [comment]
> It should be (from this branch)
> 
> ```
> git reset --hard fixed_branch
> git push origin update_bludgeon_lengths --force-with-lease
> ```

YES!!! That did it yo. I'm understanding the git reset --hard command a bit more now. I accidentally merged this branch onto the fixed one before fixing it, but used reset --hard HEAD~4 to get rid of those commits, recommitted the correct json, and then hard reset this one to the fixed one. Dang this stuff is gnarly for never having done any coding in my life.

**Pull request merged**
