### PR TITLE
Implement a hack for welding rig long repair

### LINKED ISSUE #14608: "Lost tool used for long repair" when attempting to use vehicle welding rig to enhance items (4096)
Didn't have that bug on 4068. Probably related to 4093 changes.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #14608

Not too pretty, but gets the job done.

Note that welder uses 50 charges per tick, meaning it will drain even big batteries in seconds. To compensate, it is much easier to use than soldering iron.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Hnnng. Already I'm a bit leery of the long repair after finally seeing it action, but so long as the welder can be made to work with it...

Two things though. First, it isn't possible to reduce the drain per tick rather than give it higher repair efficiency? Though a mix of both solutions, somewhere in between, might be best.

Second, any idea on future plans regarding the  `MISC_REPAIR` function? Only thing I can see being a problem with changing that is resinous cord in More Survival Tools, but that's minor.

**Comment by Coolthulhu** [comment]
> Already I'm a bit leery of the long repair after finally seeing it action

Difficulties can be adjusted. Currently it is set to rather difficult to avoid the whole "repair everything for free" thing that was the case with old repairs.

> First, it isn't possible to reduce the drain per tick rather than give it higher repair efficiency?

Could be "json-coded" specifically for that one actor or there could be a rework of `charges_per_use` to fix issues like toolbox consuming charges when cutting. The latter would take more work, though.

> Second, any idea on future plans regarding the MISC_REPAIR function?

It is used rarely enough that I didn't plan for it yet.
MISC_REPAIR consumes expensive resources (duct tape), so wouldn't work too well for training repairs.
Additionally MISC_REPAIR (and gun repairs) always succeed in the current version. This could be workable by simply making them never damage the item, only fail gracefully.

**Comment by chaosvolt** [comment]
Ah. The rework idea might still be a necessity for allowing toolboxes to cut things without consuming . I'm still annoyed at Kevin over that discussion in https://github.com/CleverRaven/Cataclysm-DDA/issues/14453 regarding additional possible uses for that idea.

So now that's two bugs and one suggestion that could be resolved by that idea.

**Comment by mugling** [comment]
> Currently it is set to rather difficult to avoid the whole "repair everything for free" thing that was the case with old repairs.

I much prefer this to the old system whereby clothing repairs were more of a frustration rather than an actual challenge

**Comment by kevingranade** [comment]
If the mechanic was a mere frustration it shouldn't even be in the game.
Why shouldn't it be challenging at low levels? (I'm assuming it's not a
challenge at high levels, that'd be silly)

**Comment by Coolthulhu** [comment]
At high levels it becomes more of a cost than a challenge.
Though now that it is in, it may be worth reducing the material cost of welding. 0.2 of volume can get huge in case of something as huge as hazmat, making repairing one quite hard even at high levels. Especially if it "dips" into damage 3, which requires spending materials to "cross".

Repairing a hazmat suit with a soldering iron and a pile of plastic trash is now at (non-rhetorical) "are you serious?" level.

**Pull request merged**
