### PR TITLE
[CR] Fix bandit cabin mission

### LINKED ISSUE #16390: Old Guard Quest - Bandit Camp couldn't spawn
Got a message after getting quest that the camp couldn't be found, or something like that, and then a hostile NPC spawned in the refugee center, which I killed, thus completing quest.

### PR DESCRIPTION
**Pull request by patternoia**
Fixes #16390
It's hack-ish though, because I added `mission_start` as a friend to the `overmap` class, being not very experienced to refactor and expose it properly.
Any suggestions to improve the situation are appreciated.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Artificially spawning bandit cabins post-overmap-gen sounds really hacky.
It would also only help with this specific mission.

Could the mission be just disabled (in `mission_place`) if there is no viable cabin?

**Comment by patternoia** [comment]
How to then progress this quest line if the mission is disabled?

**Comment by Coolthulhu** [comment]
I wanted to suggest an alternative mission, but as far as I recall the mission system is too bare to allow that.

Would be better to try the following first:
* Search for regular (non-bandit) cabin, proceed as usual except for mines
* Search for cabin in larger radius
* Spawn bandits out in the forest (also no mines)
* Spawn bandits in a random spot anywhere (in case no forest exists, for example on desert maps)

Could include changes to mission description, if it implies a cabin.

Post-mapgen mapgen would work, but it is non-standard and risky.
For one, I'm pretty sure that your solution would not actually call mapgen on already generated map. If it picked a forest tile that is generated, it would probably only mark it as cabin on the overmap, then place NPCs and mines in the wild.
It also can't be generalized too well - if you generated a forced special with a road access that way, said road access would be generated too. And as before, it would not affect already-generated map tiles, resulting in roads with noticeable cut-offs.

**Comment by patternoia** [comment]
Or one should address the source of the issue:
`overmap.cpp` line 4246
`        dbg( D_WARNING ) << string_format( "couldn't place mandatory overmap specials: %s.", unplaced.c_str() );`
fires at least for one non placed **mandatory** special in my latest ~30 tests. Aren't mandatory conditions mandatory to be executed?

**Comment by Coolthulhu** [comment]
Mandatory doesn't imply "will be placed", only "there will be an attempt to place it".
@codemime fixed at least some of the problems with the system, but as far as I recall there is still the ugly sectioning thing, where only one special can appear in a fixed-size block, meaning that a "weaker" special (such as campsite or roadblock) can take the block that would be needed for an important one.

Fixing the sectioning would require going through all the tiles in the overmap, which, without some good optimization (diagram of distances to nearest city - kinda like Voronoi diagram, binning tiles by allowed special types, sorting tiles within bins by distance to nearest city), would cause a giant slowdown in the overmap gen. And overmap gen is already painfully slow.

Then there is issue of maps that genuinely can't guarantee mandatory specials, no matter what (sometimes overmap regen can help, other times it won't).
For example, a desert map will not generate a forest shack, a 16 city radius, 0 city distance map will not generate anything that requires significant distance to city etc. The only way around this is warning the player that the overmap gen failed to generate specials and will continue to fail unless settings are changed.

**Comment by patternoia** [comment]
So I went for ridiculous amount of attempts to place a mandatory special:
`const size_t attempts_mandatory = 5000000000;`
And I still consistently get the problems generating the `bandit_camp` and `campsite_cabin_incomplete`. So it is not only the generator there which has issues but the json definitions of these specials having too aggressive requirements to be generated.
Furthermore, the original code for starting a cabin mission looks for a cabin in a radius of only 50 OM tiles which is literally nothing and has no success. Should be looking for the whole overmap generated to guarantee the successful start of the mission. There are more missions with the same problem.

**Comment by Coolthulhu** [comment]
It doesn't matter how many mandatory attempts you specify, the number of sectors is constant.

**Comment by patternoia** [comment]
> It doesn't matter how many mandatory attempts you specify, the number of sectors is constant.

You are right. One however can change the number of sectors, but it breaks balance and things remain probabilistic, and the specials are not guaranteed spawn.

My one more attempt to hack around and guarantee the spawn of required and vital specials:

```
diff --git a/src/overmap.cpp b/src/overmap.cpp
index ab3eb31..b89cd04 100644
--- a/src/overmap.cpp
+++ b/src/overmap.cpp
@@ -4161,6 +4161,7 @@ void overmap::place_specials()
     as this won't work as desired.
     */
     // Vectors of mandatory and optional specials. Int means number to place.
+    std::vector<std::pair<const overmap_special *, int>> required;
     std::vector<std::pair<const overmap_special *, int>> mandatory;
     std::vector<std::pair<const overmap_special *, int>> optional;
 
@@ -4173,7 +4174,9 @@ void overmap::place_specials()
             continue;
         }
 
-        if( elem->flags.count( "UNIQUE" ) > 0 ) {
+        if( elem->id.str() == std::string("bandit_camp") || elem->id.str() == std::string("bandit_cabin")) {
+            required.emplace_back( elem, 1 );
+        } else if( elem->flags.count( "UNIQUE" ) > 0 ) {
             if( rand() % max <= min ) {
                 mandatory.emplace_back( elem, 1 );
             }
@@ -4189,16 +4192,29 @@ void overmap::place_specials()
     }
 
     // See if we mined anything.
-    if( mandatory.empty() && optional.empty() ) {
+    if( required.empty() && mandatory.empty() && optional.empty() ) {
         return; // Nothing to do.
     }
     // Make random permutations.
+    std::random_shuffle( required.begin(), required.end() );
     std::random_shuffle( mandatory.begin(), mandatory.end() );
     std::random_shuffle( optional.begin(), optional.end() );
     // Walk over sectors.
-    for( const point &sector : get_sectors() ) {
+    std::vector<point> sectors = get_sectors();
+    std::random_shuffle( sectors.begin(), sectors.end() );
+    for( const point &sector : sectors ) {
         const int x = sector.x;
         const int y = sector.y;
+
+        if ( !required.empty() ) {
+            auto iter = required.begin();
+            const auto &special = *iter->first;
+            const tripoint p( rng( x, x + OMSPEC_FREQ - 1 ), rng( y, y + OMSPEC_FREQ - 1 ), 0 );
+            place_special( special, p, om_direction::type::none, 0 );
+            required.erase( iter );
+            continue;
+        }
+
         // Try to place mandatory specials first.
         // If no luck, continue with optionals. This gives them a chance.
         const size_t attempts = 20;

```

Note that "REQUIRED" might be a viable json flag like UNIQUE and substitute the direct comparison in given example.

**Comment by patternoia** [comment]
@codemime I just saw your reaction. Could you please elaborate/make a hint on how to move further?

**Comment by patternoia** [comment]
In future do not limit your responce to emoji please. This produce no email notification.

**Comment by Coolthulhu** [comment]
The problem with your idea is that it creates a new class of mandatory entries that do what mandatory entries are supposed to be doing, except with less checks.

This would cause overwritting. For example, placing cathedrals on refugee centers.
It is not a long term solution, only a hack to temporarily increase the chance of mapgen generating the whole set of mandatory entries.

It would be better to just add a flag that ensures "more mandatory" entries are always sorted before the "less mandatory" ones in the `mandatory` vector.

**Comment by patternoia** [comment]
Assuming the initial changes are reverted (which are already) and keeping in mind the latest raw diff I have posted, it should correspond to the idea of "more mandatory" thing you talk about. It will not overwrite anything, it will just receive the top priority to be placed before any other specials. No overwrites will happen since the later placements are skipped by `continue;` after "more mandatory" (`REQUIRED`) special's placement. Am I confused or confusing anyone further? Should I post the proposed changes by expanding the diff and adding this json flag?

**Comment by codemime** [comment]
@patternoia Sorry for not posting an explanatory comment, I was in a hurry. 
Coolthulhu has already expressed most of my thoughts on the matter (thanks!). I'd just add the following.
In particular:
1. New code should never have special cases based on hacks like `elem->id.str() == std::string("bandit_camp")`.
2. `get_sectors()` already returns a vector of permuted sectors. There's no need to get it again and re-shuffle (that's just waste of time).

In general:
I think the whole approach of hacking `place_specials()` like this, is wrong. I'd suggest something like:
1. Finding the reason why `"bandit_camp"` and `"bandit_cabin"` are the most frequent misses and eliminating it . I suspect it has something to do with the combination of `"city_size"` and `"city_distance"`.
2. Tweaking `attempts` and `attempts_mandatory`. Higher numbers may help, but they can't guarantee anything.
3. Rerolling the whole overmap after a few (say three) futile attempts.

I like Coolthulhu's suggestions on fixing the sectioning, but they probably out of scope of this PR.

**Comment by tuypo1** [comment]
Could just spawn them out in the woods with some tents

**Comment by Zireael07** [comment]
> Could just spawn them out in the woods with some tents

The issue is that the bandit cabin doesn't spawn at all, not that it spawns in wrong place.

**Pull request closed without merging**
