### PR TITLE
Fix deserialize of npc follower rules

### LINKED ISSUE #20867: There must be a mistake when reading json
void npc_follower_rules::deserialize(JsonIn &jsin)
[line 881 of savegame_json.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/savegame_json.cpp#L881)
```
    data.read("aim", tmpeng);
    aim = (aim_rule)aim;
```
Two previous lines:
```
    data.read("engagement", tmpeng);
    engagement = (combat_engagement)tmpeng;
```
PR #20868

### PR DESCRIPTION
**Pull request by AMurkin**
Fixes #20867

EDIT: correct text to autoclose if PR is ok

### CODE REVIEW

**Comment by AMurkin** [comment]
It seems i've done this wrong:

> Never merge from your local branches into your master branch. Only update that by pulling from upstream/master.

**Comment by Coolthulhu** [comment]
You can fix master branch by checking into it and resetting it to upstream version of the master branch. There are tutorials about setting up upstream and resetting.
This will not affect other branches - git stores commits outside branches too.

If you use keywords "Fixes #issue_number_here" or "Closes #issue_number_here" in the PR description, said issue will automatically be closed when the PR is merged.

**Comment by AMurkin** [comment]
Will fix master branch.
But diff looks ok. Do i need to change PR at this particular time?

**Comment by Coolthulhu** [comment]
No, as long as the diff under "files changed" looks fine, it's OK.
That thing with master is only a tip: you can actually PR from master, it's just that those PRs are likely to break fast when you want to PR something else or update your master.

**Pull request merged**
