### PR TITLE
vehicles: Open all doors

### LINKED ISSUE #23382: Vehicle Door Motors - Need All Close/Open Options
Basically, you can install motorized curtains and doors and open/closing anything via the vehicle control panels is done door-by-door basis, instead of also allowing the all open/all close options.

kevin had given me some advice on how to do this, but I have zero understanding of most code, nor the ability to write it. However, this is what I have so far, which is probably nothing.

```cpp
void vehicle::control_doors() {
    std::vector< int > door_motors = all_parts_with_feature( "DOOR_MOTOR", true );
    std::vector< int > doors_with_motors; // Indices of doors
    std::vector< tripoint > locations; // Locations used to display the doors
    doors_with_motors.reserve( door_motors.size() * 2); // it is possible to have one door to open and one to close for single motor
    locations.reserve( door_motors.size() * 2);
    if( door_motors.empty() ) {
        debugmsg( "vehicle::control_doors called but no door motors found" );
        return;
    }

    uimenu pmenu;
    pmenu.title = _("Select door to toggle");
    int doors[2]; // one door to open and one to close
    for( int p : door_motors ) {
        doors[0] = next_part_to_open(p);
        bool open_door_found = false
        doors[1] = next_part_to_close(p);
        bool closed_door_found = false;
        for (int door : doors) {
            if (door == 0)
                continue;
        } else if(door == 1) {
                continue;
        } else if(door == -1) {
                continue;

            int val = doors_with_motors.size();
            doors_with_motors.push_back(door);
            locations.push_back(tripoint(global_pos() + parts[p].precalc[0], smz));
            const char *actname = parts[door].open ? _("Close") : _("Open");
            pmenu.addentry(val, true, MENU_AUTOASSIGN, "%s %s", actname, parts[ door ].name().c_str() );
        }
    }

    pmenu.addentry( doors_with_motors.size(), true, 'q', _("Cancel") );
    pointmenu_cb callback( locations );
    pmenu.callback = &callback;
    pmenu.w_y = 0; // Move the menu so that we can see our vehicle
    pmenu.query();

    if( pmenu.ret >= 0 && pmenu.ret < (int)doors_with_motors.size() ) {
        int part = doors_with_motors[pmenu.ret];
        open_or_close( part, !(parts[part].open) );
    }
}
```

Anyway, it'd be a grand to have so (mainly) closing doors in larger vehicles becomes easier rather than a tedious chore.

### PR DESCRIPTION
**Pull request by mlangsdorf**
adds menu options to control_doors in vehicles.cpp, to allow opening or closing all doors or curtains at once.

Fixes #23382

### CODE REVIEW

**Comment by mlangsdorf** [comment]
I can see a way to refactor the code into a function call, something like:
```
if( open ) 
    open_or_close_all( motor, open, OPENCURTAINS, next_part_to_open);
else
    open_or_close_all( motor, open, CLOSEDOORS, next_part_to_close);

void open_or_close_all(int motor, boolean open, int special, function* get_next_part)
{
    int part = get_next_part( motor );
    int next_part = -1;
    if( part != -1 ) {
       if ( option == special )
           if ( ( special == OPENCURTAINS  && ! part_flag( part, "CURTAIN" ) || 
                ( special == CLOSEDOORS  && part_flag( part, "CURTAIN" ) ) )
                 continue;
            open_or_close( part, open );
            if( option == OPENBOTH || option == CLOSEBOTH )
                 next_part = get_next_part( motor );
             if( next_part != -1)
                 open_or_close( next_part, open );
    }
}
```
but i hate debugging function pointers so I'm not writing it that way unless I have to.

**Comment by 0be1isk** [comment]
very useful addition

**Comment by DracoGriffin** [comment]
Oh thank god, someone finally is going to fix #23382.

Appreciate the work, @mlangsdorf.

**Comment by mlangsdorf** [comment]
I didn't realize there was an existing issue. I just learned about door motors yesterday and installed them on my APC so I could close the curtains after I left the vehicle, and discovered that doing that one at a time for 11 curtains through a remote control is too many button presses.

Added the fixes to the github description; I can push an amended commit with it tomorrow.

**Comment by mlangsdorf** [comment]
what does cloth and blankets have to do with powered doors and curtains?

**Pull request merged**
