### PR TITLE
More Complete and Rebalanced Vitamins

### PR DESCRIPTION
**Pull request by dissociativity**
No more unrealistic vegetarian anemia!
Nuts, Tomatoes and beans all are a great source of iron!
Flesh had unrealistically high iron values previously so that's a bit nerfed too.

Milk and insect flesh also has some now as per real life.

Added materials to appropriate foods and tested ingame for balance, let me know if I missed anything.

Balanced vs Flesh material based on real life statistics.

Game should now be very playable with simplified nutrition off for all players!

Linted before committing!

### CODE REVIEW

**Comment by dissociativity** [comment]
I'd like to make offal a separate material with high iron content too, but it doesn't really seem worth it when as far as I'm aware the current system doesn't have, or at least doesn't show vitamins if an item isn't 'healthy'.

I'm not sure why eating tuna and SPAM which my character hates shouldn't give me enough iron to stave off anemia.

I may make this into an issue, but this particular commit is complete and tested in game as far as I'm aware.

**Comment by dissociativity** [comment]
I'd add Offal as a high iron content material, but that would break herbivore and hates meat traits, so that will be for future commits.

**Comment by sfsworms** [comment]
Uh, how would upping the iron content of offal break herbivore?

**Comment by dissociativity** [comment]
It wouldn't, my initial plan was to make offal a separate material which would break hates meat at least, but it's fine, I've got it all sorted in the upcoming commits!

**Comment by dissociativity** [comment]
So it turns out a few of these things have a chemical that makes it harder for the body to absorb the iron content, so being a vegetarian still has to be hard unless you're eating a lot of tomato or garlic I guess!
Phytic acid sucks

**Comment by dissociativity** [comment]
I think that's complete, but I'll change things as I find them while playing normally if they seem off.

**Comment by TechyBen** [comment]
Sorry, I'm confused as to the tomatoes statement. But this list may be helpful for vegetarian/survival playthroughs (notice top of the list ;) ) http://www.dailyiron.net/red-tomatoes/

**Comment by dissociativity** [comment]
I mean that wheat, nuts and beans have the acid that makes it hard to absorb, it's hard to simulate the actual chemical so I just nerfed them, I'll need to make a separate mushroom material, totally forgot about that, but both garlic and tomato are quite absorb-able iron sources.

Nuts and beans are still decent sources of iron, just worse than meat, for balance it makes sense anyway for herbivore to be less viable than being an omnivore :P

**Comment by dissociativity** [comment]
alright, that's done

**Comment by dissociativity** [comment]
@TechyBen you're right, another source told me tomatoes can have lots of iron, but that's only when canned in tomato juice (in which case it's still not that much), or sun-dried tomatoes, and your average store bought tomato species are there to have a long shelf-life more-so than actually having good nutritional value other than vitamin C.

**Comment by Tharn** [comment]
I've compiled all the foodstuffs that should have some vitamins & minerals but don't as of **4479903**:

`cheeseburger, hamburger helper, cheese pizza, mac & cheese, pickled punk (like pickled meat), hard cheese, hickory nut ambrosia, soylent slice (like canned meat), bologna (like cooked meat), brat bologna (same), mannwurst (like sausage), maple syrup (suggest 10% calcium), french fries & potato chips (think potato), tortilla chips (some corn), clam chowder, french toast, maple pie (see maple syrup), chump cheeseburger (like cheeseburger), sugar beet syrup (suggest 20% iron), chai tea (has milk), cullen skink (milk & fish), chili dogs, dudeluxe sandwich, deluxe sandwich, cooked hot dogs, cheater chili dogs, cooked corn dog, cracklins (trace amounts), hot chocolate, hobo helper, protein drink, soylent green drink, cooked burrito, salted popcorn (see popcorn), nachos with cheese, cooked TV dinner, nachos with meat and cheese, nino nachos with cheese, cheese fries, milk, grilled cheese sandwich, cheese sandwich, coffee milk,  milk tea, quesadilla, campfire hot dog, fast noodles (see spaghetti), onion ring, dried beans (bring in line with dehydrated foods)`

**Pull request merged**
