### PR TITLE
Apex Predator is on top of the food chain

### LINKED ISSUE #74285: PREDATION mutations are white elephants
### Is your feature request related to a problem? Please describe.

PREDATION mutations are white elephants.
All of these mutaions are post-threshold, and to obtain mutations in this chain, you need to get CARNIVORE first (or CARNIVORE_FAKE for URSINE).
Furthermore, if you are not LUPINE, final mutaions in this chain will also give you INT penalty.
With the high price paid, all your character can get are only:
https://github.com/CleverRaven/Cataclysm-DDA/blob/26960ee03550dded3ba0123562fb92f8df5228f7/doc/JSON_FLAGS.md?plain=1#L403-L406
...which seems pity to me.

### Solution you would like.

"As one on top of the food chain", what you need are not only to learn combat skill faster (and less likely to forget them) and to get some morale bonus from eating and killing, but also the ability to fight better with your skills.
I think a reasonable approach is to give characters with PREDATION mutations the ability to learn weak point proficiencies faster, suffer less from lack of certain proficiency, and get more bonus when knowing certain weak point.

### Describe alternatives you have considered.

Directly give character attack bouns without the aid of weak point system?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by osuphobia**
#### Summary
Features "PREDATION mutations will give you bonus on weakpoint"
#### Purpose of change
Close #74285 
Predators should also have the ability to fight better with their skills.
#### Describe the solution
Now PREDATION mutations will give your character bonus on weakpoint proficiencies.

First, you get more bonus from knowing certain weakpoint, and suffer less  when not knowing certain weakpoint proficiencies.
With Culler, default_weakpoint_penalty will have a +1 to decrease the effect of `default_weakpoint_penalty`.
With Apex Predator, you get an extra +3 `default_weakpoint_bonus` when knowing certain weakpoint proficiencies, and will not suffer from `default_weakpoint_penalty`.

Second, your character can learn weakpoint proficiencies faster.
With Apex Predator, you will be able to learn weakpoint proficiencies four times as fast.
Culler is not affected.

For the part of learning speed, I added some infrastructure, so it can be used for other enchantments. See the doc for more details.
#### Testing
Compiled and tested locally. The melee_test failed for one time while adjusting things, it's only once so I'm not sure if I fixed it or it's just some RNG stuff.
#### Additional context

### CODE REVIEW

**Comment by Venera3** [comment]
I can see the higher bonuses when you *did* learn one, but what's the rationale behind removing the penalties for *not* knowing a prof?

I also don't see the wp learn speed bonus from a flavor perspective - you're explicitly giving up learning stuff in favor of instincts, and learning profs are mostly done while meticulously dissecting your enemies.

**Comment by Vaskritaya** [comment]
> I also don't see the wp learn speed bonus from a flavor perspective - you're explicitly giving up learning stuff in favor of instincts, and learning profs are mostly done while meticulously dissecting your enemies.

To this end, perhaps it would make more sense to significantly increase the weakpoint proficiency learned from combat, rather than just give a flat bonus to learnspeed. Maybe even decrease it for dissection? Would make a lot more sense with the flavor of learning more from combat but losing intelligence, although I think it would need new infrastructure to make work.

**Comment by osuphobia** [comment]
> I can see the higher bonuses when you _did_ learn one, but what's the rationale behind removing the penalties for _not_ knowing a prof?

We have infrastructure for crafting profs, to estimate your gradually improvement in certain area, by decreasing penalties along with the progress of getting the prof.
But for default_weakpoint_bonus/default_weakpoint_penalty of weakpoint profs, there are only two states, known or unknow. Of cause it's better to also simulate the improvement curve, but that can be introduced in another PR.

> I also don't see the wp learn speed bonus from a flavor perspective - you're explicitly giving up learning stuff in favor of instincts, and learning profs are mostly done while meticulously dissecting your enemies.

It might be my word choice that makes you have this feeling. It's not really "learning", just "earning" the progress by predation, in the other words, slaughtering and feast of flesh and blood. And yes, dissecting is a huge exp source of prof earing progress, but "instincts" can also let the Apex Predator find its enemy's weakness naturally.
And, if you really think Apex Predator will lose the ability to study things (and the -3 INT is not enough), maybe we should increase the difficulty of certain intellectual activities and forbid or heavily restrict bestial mutants from doing them. But again that should be in another PR.

Fundamentally, if you consider the progress of earning weakpoint profs as the progress of recalling bestial instincts to kill, it's just working like the existing COMBAT_CATCHUP modifier for combat skills IMO.

**Comment by osuphobia** [comment]
> > I also don't see the wp learn speed bonus from a flavor perspective - you're explicitly giving up learning stuff in favor of instincts, and learning profs are mostly done while meticulously dissecting your enemies.
> 
> To this end, perhaps it would make more sense to significantly increase the weakpoint proficiency learned from combat, rather than just give a flat bonus to learnspeed. Maybe even decrease it for dissection? Would make a lot more sense with the flavor of learning more from combat but losing intelligence, although I think it would need new infrastructure to make work.

I just came up with an idea: what if we change the exp source for bestial mutants, like not earning proficiency progress from dissection, but from butchery?

**Comment by PatrikLundell** [comment]
I don't think it's a good idea to make butchery more profitable for beasts than for others. If anything, beasts should be less precise with their butchery than humans. It would be much more fitting to have a higher learning rate from combat and a lower from dissection (although low INT may be enough: I don't know).

**Comment by osuphobia** [comment]
> I don't think it's a good idea to make butchery more profitable for beasts than for others. If anything, beasts should be less precise with their butchery than humans. It would be much more fitting to have a higher learning rate from combat and a lower from dissection (although low INT may be enough: I don't know).

After diving into the codes, I found out that the way we get weakpoint prof to improve is just wierd now. I will make another PR to solve it, as it's not limited to things I implemented here, and I don't want to make this PR too complicated.

**Comment by osuphobia** [comment]
> Buffing prof learned in combat and disabling dissection would be how I'd see that work.
> 
> The point of weakpoints is they are a thing you need to _learn_, and blunting the penalty feels very heavy-handed in that context. `Predators should be the best at everything melee-related` is the wrong way to go about it, `predators are good when they *can* rely on their instincts` is a better pitch.

Did you see https://github.com/CleverRaven/Cataclysm-DDA/issues/74426 ?

**Comment by kevingranade** [comment]
> It's not really "learning", just "earning" the progress by predation, in the other words, killing and feast of flesh and blood.

To be clear about this point,  this rationale is never correct. Skills and proficiencies are always about learning and practice.

Drop the lowered penalty for not having the proficiency,  lower the multipliers you're adding (3x is a ridiculously high multiplier). That seems to apply to both learning speed and bonuses once you have the proficiencies, this shouldn't be many times better than a base human,  just marginal. 

Ideally if you're leveraging instinctual targeting of weak points it would skew toward the weak points that real predators attack (hamstring,  nape of neck) at the cost of others that a more intelligent fighter would focus on such as armor gaps and less obvious anotomical features. That's obviously out of scope for this PR, just trying to look ahead a bit. The way I could see this working is having a list of weakpoints that get a boost, and the others get a penalty. 

Overall I'm kind of sckeptical of this new proficiency configurability on behalf of one mline.

**Comment by osuphobia** [comment]
> Drop the lowered penalty for not having the proficiency, lower the multipliers you're adding (3x is a ridiculously high multiplier). That seems to apply to both learning speed and bonuses once you have the proficiencies, this shouldn't be many times better than a base human, just marginal.

I will calculate the overall improvement later and see how should I change the numbers.

> > It's not really "learning", just "earning" the progress by predation, in the other words, killing and feast of flesh and blood.
> 
> To be clear about this point, this rationale is never correct. Skills and proficiencies are always about learning and practice.

> Ideally if you're leveraging instinctual targeting of weak points it would skew toward the weak points that real predators attack (hamstring, nape of neck) at the cost of others that a more intelligent fighter would focus on such as armor gaps and less obvious anotomical features. That's obviously out of scope for this PR, just trying to look ahead a bit. The way I could see this working is having a list of weakpoints that get a boost, and the others get a penalty.
> 
> Overall I'm kind of sckeptical of this new proficiency configurability on behalf of one mline.

There were not many responses in #74285 , so I just did this one with my own rationale (and I got a 👍 from Maleclypse😣)
I will reconsider it and search around to see if I can find some proof for my idea.

**Comment by osuphobia** [comment]
wp prof | unarmed | melee | dex | per | attacker_skill | wp penalty | wp bonus
-- | -- | -- | -- | -- | -- | -- | --
Principles of Zombie Biology | 0 | 0 | 8 | 8 | 0 | 0 | 2
Principles of Zombie Biology | 3 | 3 | 8 | 8 | 3 | 0 | 2
Principles of Zombie Biology | 5 | 5 | 8 | 8 | 5 | 0 | 2
Principles of Zombie Biology | 10 | 10 | 8 | 8 | 10 | 0 | 2
Principles of Zombie Biology | 10 | 10 | 12 | 12 | 11 | 0 | 2
Principles of Zombie Biology | 10 | 10 | 16 | 16 | 12 | 0 | 2
Xenology | 0 | 0 | 8 | 8 | 0 | -2 | 4
Xenology | 3 | 3 | 8 | 8 | 3 | -2 | 4
Xenology | 5 | 5 | 8 | 8 | 5 | -2 | 4
Xenology | 10 | 10 | 8 | 8 | 10 | -2 | 4
Xenology | 10 | 10 | 12 | 12 | 11 | -2 | 4
Xenology | 10 | 10 | 16 | 16 | 12 | -2 | 4
Natural Armors | 0 | 0 | 8 | 8 | 0 | -4 | 4
Natural Armors | 3 | 3 | 8 | 8 | 3 | -4 | 4
Natural Armors | 5 | 5 | 8 | 8 | 5 | -4 | 4
Natural Armors | 10 | 10 | 8 | 8 | 10 | -4 | 4
Natural Armors | 10 | 10 | 12 | 12 | 11 | -4 | 4
Natural Armors | 10 | 10 | 16 | 16 | 12 | -4 | 4

ttl unknow | p1 unknow | p2 unknow | p3 unknow | p4 unknow | ttl known | p1 known | p2 known | p3 known | p4 known
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0 | 2 | 2 | 3 | 4 | 5
3 | 3 | 3 | 3 | 3 | 5 | 5 | 6 | 7 | 8
5 | 5 | 5 | 5 | 5 | 7 | 7 | 8 | 9 | 10
10 | 10 | 10 | 10 | 10 | 12 | 12 | 13 | 14 | 15
11 | 11 | 11 | 11 | 11 | 13 | 13 | 14 | 15 | 16
12 | 12 | 12 | 12 | 12 | 14 | 14 | 15 | 16 | 17
-2 | -1 | -1 | 0 | 0 | 4 | 4 | 5 | 6 | 7
1 | 2 | 2 | 3 | 3 | 7 | 7 | 8 | 9 | 10
3 | 4 | 4 | 5 | 5 | 9 | 9 | 10 | 11 | 12
8 | 9 | 9 | 10 | 10 | 14 | 14 | 15 | 16 | 17
9 | 10 | 10 | 11 | 11 | 15 | 15 | 16 | 17 | 18
10 | 11 | 11 | 12 | 12 | 16 | 16 | 17 | 18 | 19
-4 | -3 | -3 | -2 | 0 | 4 | 4 | 5 | 6 | 7
-1 | 0 | 0 | 1 | 3 | 7 | 7 | 8 | 9 | 10
1 | 2 | 2 | 3 | 5 | 9 | 9 | 10 | 11 | 12
6 | 7 | 7 | 8 | 10 | 14 | 14 | 15 | 16 | 17
7 | 8 | 8 | 9 | 11 | 15 | 15 | 16 | 17 | 18
8 | 9 | 9 | 10 | 12 | 16 | 16 | 17 | 18 | 19

About the lowered penalty and the bonus from knowing certain weakpoint, see column above. The bonus is not a 3x but +3. Skill level is the most important thing in the formula and has much higher influence about the chance to hit a weakpoint.
The influence of dex and per is lower than buff from Apex Predator, but dex and per also have many other usages, and the gap is minor compare to that of the skill level.

**Comment by osuphobia** [comment]
About the speed bonus, as you can see in https://github.com/CleverRaven/Cataclysm-DDA/issues/74426#issuecomment-2157840717 , the progress you can get from practice_hit and practice_kill is negligible compare to practice_dissect.
In 878ac0b82ad75571e0c9aa51c85364bdc8ce49c0 I just cut the xp from dissection to half for predators as a trade off, so the speed bonus is much more conservative now, it can hardly be called a buff. I'd say it's literally rather a nerf.

**Comment by osuphobia** [comment]
>Ideally if you're leveraging instinctual targeting of weak points it would skew toward the weak points that real predators attack (hamstring, nape of neck) at the cost of others that a more intelligent fighter would focus on such as armor gaps and less obvious anotomical features. 

About this, few weakppoints in dda meet this criteria, maybe Cyborg Anatomy and Synthetic Armors? Even the logic that bestial mutants being bad at finding this kind of wp is doubtful to me, because they are not just ordinary beasts, but survivors and successful predators in this post-apocalyptique world. There is no reason that they can not see cyborgs and fully armed militias as preys, and there is no essential difference between natural armors and implants and synthetic armors IMO.

**Comment by kevingranade** [comment]
To the extent that they are overriding their instincts with their knowledge from being intelligent, they should lose any bonuses gained from their instincts.  You're trying to have it both ways by saying they get a boost because of their killer instincts, without acknowledging how those instincts can be wrong and counterproductive in some circumstances.

**Comment by osuphobia** [comment]
> To the extent that they are overriding their instincts with their knowledge from being intelligent, they should lose any bonuses gained from their instincts. You're trying to have it both ways by saying they get a boost because of their killer instincts, without acknowledging how those instincts can be wrong and counterproductive in some circumstances.

I just found out that I missed a disscusion before, and changed my mind today.
https://github.com/CleverRaven/Cataclysm-DDA/issues/74426#issuecomment-2162489338
So what about this idea? If you think that is acceptable, then I'll make another PR to implement it.
If that one can be merged, then I can change this PR to reflect the part of "lose any bonuses gained from their instincts".
I will give up adding learning speed boost in this PR, but make predators have bonus applied earlier with codes like this:

```
float weakpoint_family::modifier( const Character &attacker ) const
{
    float weakpoint_bonus = bonus.value_or( proficiency.obj().default_weakpoint_bonus() );
    float weakpoint_penalty = penalty.value_or( proficiency.obj().default_weakpoint_penalty() );
    float pct = attacker.get_proficiency_practice( proficiency );
    
    if( attacker.has_flag( json_flag_PRED4 ) ) {
        pct = pct < 0.79f ? std::min( 0.79f, pct + 0.39f ) : pct;
    } else if( attacker.has_flag( json_flag_PRED3 ) ) {
        pct = pct < 0.69f ? std::min( 0.69f, pct + 0.29f ) : pct;
    } else if( attacker.has_flag( json_flag_PRED2 ) ) {
        pct = pct < 0.59f ? std::min( 0.59f, pct + 0.19f ) : pct;
    } else if( attacker.has_flag( json_flag_PRED1 ) ) {
        pct = pct < 0.49f ? std::min( 0.49f, pct + 0.09f ) : pct;
    }

    return weakpoint_bonus * pct + weakpoint_penalty * ( 1.00f - pct );
}
```

**Comment by kevingranade** [comment]
It's extremely unclear what that is trying to achieve (mathematically), and no I don't like the "gradual proficiency gain" concept here, especially since I am pushing for weak point proficiencies to be even more binary than they are now.

**Comment by osuphobia** [comment]
Ok, then I'll close this one.

**Pull request closed without merging**
