### PR TITLE
Autodoc now requires an actual anesthesia to work

### PR DESCRIPTION
**Pull request by Night-Pryanik**
- Added an anesthesia kit item with an `ANESTHESIA` flag;
- Made it spawn in bionic basement (guaranteed), doctor's office (high chance), hospital and veterinarian office (both have average chance);
- Autodoc will check for items with aforementioned flag in player's inventory and his surroundings. If valid item is found, it will be consumed on operation (both install and uninstall of bionics). One kit per operation no matter the duration or difficulty;
- Removed painkiller threshold that was needed to achieve prior to installation of bionics;
- Removed the need of a tool with fine cutting quality and a first aid kit to uninstall bionics;
- Player can use any items with aforementioned flag (though it's only one in vanilla for now) for operations;
- Added description for the flag in `JSON_FLAGS.md`.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Please check a flag and not only the direct Id of the anesthesia item, to make this feature moddable

**Comment by Night-Pryanik** [comment]
> Please check a flag and not only the direct Id of the anesthesia item, to make this feature moddable

Done.

**Comment by Night-Pryanik** [comment]
> Just an idea: with high first aid skill, using few empty syringes, a meter of duct tape, and right ammount of specific drugs and/or painkillers player might be able to make a makeshift anesthesia kit as an option, when not being able to find a real one. I can drop a PR for this if it fits this theme?

I'm not against it. Just wait for this PR to get merged, and describe in details which drugs you are planning to use in the recipe.

**Comment by John-Candlebury** [comment]
> Please check a flag and not only the direct Id of the anesthesia item, to make this feature moddable
> 
> Done.

Thank you!

**Comment by Xhuis** [comment]
Do you plan to remove manual installation of CBMs? I'm not sure how I feel about that idea in particular, but if it stays, it does seem like a good choice to make the Autodoc preferred. Maybe the success chance is increased for the Autodoc, it takes less time, or something along those lines. Making manual installations take time would also not be a bad idea, as right now you can install eight bionics within the space of one turn since it doesn't pass time.

Oh, and since this deprecates the worldmod that removes needing painkillers for bionics, it might not be a bad idea to remove that, or if you're going to remove manual installation, to change it into "easy bionic installation" or something like that that preserves the old way.

**Comment by Night-Pryanik** [comment]
> Do you plan to remove manual installation of CBMs?

Yes, I do.

> or if you're going to remove manual installation, to change it into "easy bionic installation" or something like that that preserves the old way.

I'm not interested in making "old-style bionic installation" mod myself, but I'm not against if someone will implement it.

**Comment by Xhuis** [comment]
Mmk, fair enough.

**Pull request merged**
