### PR TITLE
Updates Vamp mutation line for CRIT Expansion

### PR DESCRIPTION
**Pull request by b3brodie**
Updates Vamp mutation line for CRIT Expansion

#### Summary
Bugfixes "Adds intermediate mutations to vamp line so errors are no longer thrown on world start"

#### Purpose of change
Due to changes in the mutation system, errors are thrown if a mutation line has a mutation such as Solar Sensitivity while not having its prerequisite Albino.  This change adds the intermediate mutations for all of vampire's current mutations.
Furthermore, the two files containing the vampire mutations were merged, as they previously just served to increase file bloat.

#### Describe the solution
Necessary intermediate mutations were added to the vampire line.
The 3 mutations from crt_mutatinoc.json were added to the crt_vamp_mutations.json file and the crt_mutatinoc.json was then deleted

#### Describe alternatives you've considered
Allow CRIT to keep on throwing errors every time the world starts

#### Testing
Started a world with the new mutations added to the vampire line, no errors are thrown.

### CODE REVIEW

**Comment by Maleclypse** [comment]
CRIT is obsoleted.

**Comment by b3brodie** [comment]
I'm aware CRIT is obsoleted, but since I'm keeping it maintained on my own branch is there any reason not to merge the updates even if it remains obsoleted here?

**Comment by Maleclypse** [comment]
> I'm aware CRIT is obsoleted, but since I'm keeping it maintained on my own branch is there any reason not to merge the updates even if it remains obsoleted here?

I believe it reduces the chance of it getting a maintainer, but I'll let other people weigh in.

**Comment by anothersimulacrum** [comment]
I'd rather we only make changes to non-obsolete mods. Keeping obsolete mods from giving errors only encourages people using them and it being an issue when it fatally breaks or is removed.

**Pull request closed without merging**
