### PR TITLE
Make Forge of Wonder Globally Unique

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
The Forge was intended to be globally unique but the code to make it so didn't exist when it was first made.  Now it does.

#### Describe the solution
Adds Globally unique flag.

#### Describe alternatives you've considered
Making it more rare than 1/16

### CODE REVIEW

**Comment by TheAthenaCabin0** [comment]
iirc there are a few lines of dialogue from the various traders there that would have to be changed in addition to this flag - they indicate that there are many copies of the forge all over the world. Would that be fitting for a different pr?

**Comment by SariusSkelrets** [comment]
The diviner can give you [directions to another forge](https://github.com/CleverRaven/Cataclysm-DDA/blob/5ca7f4e59c2d7b0a93fb801a31138477f7b4a761/data/mods/Magiclysm/npc/TALK_FORGE_DIVINER.json#L892), while saying that Valzaim intended having that many forges as part of a "plan" he have

It will definetly need to be changed should the location becomes globally unique

**Comment by b3brodie** [comment]
As an addition to this, since the forge will be unique I think it makes sense to give the npcs defined personalities.  Right now they're rolled randomly, which is very apparent on the traders and can lead to some dramatically different pricing.

**Comment by TheAthenaCabin0** [comment]
It feels like adding distinct personalities and fleshing out the forge a bit more ties in with #73434. Maybe a forge overhaul is due à la the various faction overhauls we are seeing (exodii, hub, isherwoods, etc). Later this week I'll try to draft a pr on that matter, resolving some of the QoL features at least.

**Comment by Maleclypse** [comment]
> It feels like adding distinct personalities and fleshing out the forge a bit more ties in with #73434. Maybe a forge overhaul is due à la the various faction overhauls we are seeing (exodii, hub, isherwoods, etc). Later this week I'll try to draft a pr on that matter, resolving some of the QoL features at least.

Definitely support giving the various traders more definite traits and dialogue. While testing the above issue I discovered that forge dwarves can just wander into the lava.  Added the higher level of danger avoid to fix that.

**Comment by Procyonae** [comment]
Unless I'm missing something the talk topic TALK_FORGE_LORD_DIVINER_OTHER_FORGE where the mission is assigned also needs changing

**Comment by Maleclypse** [comment]
> Unless I'm missing something the talk topic TALK_FORGE_LORD_DIVINER_OTHER_FORGE where the mission is assigned also needs changing

What do you think about that change I've just pushed?

**Pull request merged**
