### PR TITLE
More Survival Tools Series 15

### PR DESCRIPTION
**Pull request by chaosvolt**
No new additions, just balancing stuff.
1. Reduced encumbrance of makeshift sunglasses to 9. Yes, 9. Two reasons. One, a vision slit worn close enough to the eyes does not impede vision as severely as it would if they were even an inch away. Two, the POINT of these is makeshift glare protection. Glare gives you a whopping -1 to perception, any higher and this item is literally worse than useless. At least this way wearing it with any other eye-encumbering gear will be enough to push it over the limit.
2. Removed rapid strike from the spears and javelins, especially important since the overwritten javelins don't have rapid in vanilla cataclysm.
3. Tweaked the ammo properties of javelins, and zeroed the ranged damage on the atlatl to compensate.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Also, a suggestion I'd like to propose prior to implementing it, depending on feedback.

For a standard innawoods character, a quern, while useful for making flour for easy, portable food for later preparation, is not readily practical to make and carry. Without a basic bit of mechanics skill, only a clay quern is available, and this requires access to a large number of rocks to build a clay kiln, not as good for a nomadic character.

An alternative would be some sort of molcajete, mortar and pestle, etc. In theory it could be made more compact and with a different set of skills, making it more accessible.

But there'd have to be a catch to make the quern worth bothering with. The first example that comes to mind is to make separate recipes for grinding using a mortar and pestle, instead of it being a straight substitute for a quern. This allows making it more time-consuming, and allows the option of using more skill or different skills to use it for grinding powders.

**Comment by kevingranade** [comment]
Alternately give the tools grinding 1 vs grinding 2 or similar, and have
that adjust recipe times.  This is a feature we've been meaning to add
anyway.

**Comment by chaosvolt** [comment]
That could be the best way to handle it, though we don't have grinding quality yet do we?

**Comment by Coolthulhu** [comment]
If you want to change the recipes and the whole grinding stuff, you could PR it as a mainline change. Would make sense for bone grinding recipes to just use mortar+pestle.

You can buff the spears a bit now that they don't have rapid. Mainline ones got ~20% buffs to damage in the rapid removal PR.

**Comment by chaosvolt** [comment]
Ah, right. Can save grinding for later, will buff spears then.

**Comment by chaosvolt** [comment]
Minor issue with tweaking the spears is how little room their is for variations in damage. You have the wooden spear with total 18 damage, knife spear with total 20 damage, then it jumps to the forked spear's 23 damage and the steel spear's 26.

I can obviously make the stone spear have 19 total damage and it fits right in, but the copper spear...I don't want to make it blow the knife spear out of the water, so I have to either make it identical in total damage, or no more than 1 point more.

Might have to adjust the weight too, as it stands the copper spear is lighter and only really loses out in the utility department.

**Comment by Coolthulhu** [comment]
Change the weight and bash/pierce ratio. Higher bashing makes it stick less.

**Comment by chaosvolt** [comment]
Ah, right. So more bashing for the more primitive weapons? Should I mess with knife spear, or leave it alone?

**Comment by Coolthulhu** [comment]
You could override the wooden one and nerf it in the override and then place stone one where wooden is now. Don't make stone spear too close to the knife one, it should be more like wooden spear. Don't buff knife spear, it is good already.

**Comment by chaosvolt** [comment]
Hmm, very well then.

**Comment by Coolthulhu** [comment]
Copper one can be better than knife one. Knife one is a crude steel point hammered from scrap metal, as far as I recall copper one requires some primitive forging.

**Comment by chaosvolt** [comment]
Hmm. True, you are presumably using proper work-hardening and annealing. So the progression would be wooden spear, stone spear, knife spear, copper spear, forked spear, steel spear?

That...actually completely removes the need to add an override nerfing wooden spears. One spear can comfortably fit between 18 and 20 damage, obviously. XP

**Comment by chaosvolt** [comment]
Cataclysm: Tweaking Days Ahead.

**Comment by chaosvolt** [comment]
And thank you for the merge.

**Pull request merged**
