### PR TITLE
Cleanup armor.json

### PR DESCRIPTION
**Pull request by illi-kun**
Typical clean-up from default values.

The only interesting thing is a parameter "cut" I found in armor.json. I removed it because the only place I found use of similar parameter is `void ma_technique::load( JsonObject &jo )` and I don't know how it can be related to armor, please correct me if I wrong.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Huh, that is odd. No idea where that parameter came from. Maybe it was assumed to be an alias for the cutting property? Though I would've assumed that things would error if it wasn't used for SOMETHING, as the game tends to throw a hissy fit if JSON files cite non-existent properties.

**Comment by illi-kun** [comment]
> Though I would've assumed that things would error if it wasn't used for SOMETHING, as the game tends to throw a hissy fit if JSON files cite non-existent properties.

I added this line to some random book and game runs correctly (without any complains):
```        "Chaosvolt" : "wrong",```

**Comment by chaosvolt** [comment]
What. Whaaat. Meanwhile last time I tested a magazine-related PR with the wrong build, it threw a fit about `"reload_time"` not existing. ;w;

**Comment by illi-kun** [comment]
Well, that obviously means that someone added secret parameter ```"Chaosvolt"```!
Just kidding, it seems that any properly defined parameter is fine for program (so you probably missed comma sign or something like that).

**Comment by chaosvolt** [comment]
Hmm, very odd. Possibly I defined them wrong, though the same changes worked when I dropped them into a build that didn't pre-date the magazine additions. Though as I'm quite certain it'll freak out over an incorrect item type (and item type "MAGAZINE" wouldn't have been recognized by that build), it might've been throwing up an error message at the wrong problem instead. XP

**Comment by illi-kun** [comment]
Yes, I guess you're right and incorrect item type can cause some errors.

**Pull request merged**
