### PR TITLE
Give (some) CBM's more insight into their original purpose

### PR DESCRIPTION
**Pull request by tenmillimaster**
#### Summary
None

#### Purpose of change

It'd be cool if we helped explain what CBM's were doing in their universes of origin before become tools in the arsenal of zombie killing(and zombie evading) cyborgs.

#### Describe the solution

Fluff some descriptions in CBMs. Unfortunately I'm not *that* creative so while I tried thinking of more this is about as far as I got. But... I tried?

#### Describe alternatives you've considered

Being more imaginative.

#### Testing

Loaded game. No errors.

#### Additional context

None.

### CODE REVIEW

**Comment by Karol1223** [comment]
As much as I love those I am not sure they fit in item descriptions themselves. This feels like something better suited for snippets of some notes/whatever lying around in Exodii locations, or dialogue descriptions

**Comment by tenmillimaster** [comment]
> As much as I love those I am not sure they fit in item descriptions themselves. This feels like something better suited for snippets of some notes/whatever lying around in Exodii locations, or dialogue descriptions

This is about the level of detail I include in gun descriptions...

**Comment by db48x** [comment]
I like them :)

So what unique mod did our Earth invent, and have they discovered it yet?

**Comment by carlarctg** [comment]
How does the average Survivor magically know this stuff?? This is weird. I don't want to come across alien lore in item description text while playing a medieval churl or punk kid.. Sorry. Lore is cool but it does need to work in context as well.

**Comment by fairyarmadillo** [comment]
This is problematic because 1) this stuff is not supposed to make any sense to the survivor, who has never seen these things before, and 2) the exodii have been nomadic dimension-hoppers for at least centuries and possibly millennia, their CBMs are not retrofitted consumer products from their homeworld, they're purpose-built for apocalypse survival.

**Comment by tenmillimaster** [comment]
> CBMs are not retrofitted consumer products from their homeworld, they're purpose-built for apocalypse survival. The throwing assist CBM is not for beqball, it's for throwing ninja stars at zombies, and even the oldest exodii were not alive in a time where this was not the case.

All CBM's should be retrofitted products from their universe of origin. Having personally consulted on the throwing assist CBM during internal discussions, I can tell you with certainty that the throwing assist CBM was made for sports games.

**Pull request merged**
