### PR TITLE
Makeshift magazines overhaul

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

SUMMARY: Content "Makeshift magazines overhaul"
#### Purpose of change

Make makeshift magazine crafting more sensible, make it more straightforward to add new makeshift magazines for guns, and rebalance their stats to be worse than factory-made magazines.
#### Describe the solution
Alter JSON entries for magazine recipes to use newly-added magazine standard requirements.
Add extra makeshift magazines for 9x19mm and .223 firearms, where making one is feasible with the tools noted.

#### Describe alternatives you've considered

Adding makeshift magazines for other calibers as well. Decided not to bloat this PR, though.
#### Testing

Copy-pasted changes to game files, made sure that no errors happen on load.
#### Additional context

None.

### CODE REVIEW

**Comment by kevingranade** [comment]
We seem to have lost track of the top level guidelines for magazines at some point, Survivor-craftable magazines should be the exception rather than the rule, and they should have significant deficits compared to factory magazines in the areas of weight, capacity and reliability.

**Comment by Rail-Runner** [comment]
> they should have significant deficits compared to factory magazines in the areas of weight, capacity and reliability

That's how I've done it here, pretty much. Craftable magazines are limited to 5-round capacity for rifle cartridges or 20-round capacity for pistol cartridges, and also have higher weight and volume than factory-made magazines of similar capacity. They can't be made at all for many guns either; if gun uses angled-feed magazines (which is true for nearly all pistols for instance) or rimmed cartridges, then producing them would be much harder (likely involving machine tools) and I didn't add that right now.

**Comment by emptytriangle** [comment]
It would be great if makeshift mags had a significant chance of failure to feed and jamming the gun until an unload/reload.

**Comment by Night-Pryanik** [comment]
@Rail-Runner could you please resolve conflicts?

**Comment by Night-Pryanik** [comment]
Closing as inactive.

**Pull request closed without merging**
