### PR TITLE
Convert deconstruction recipes to uncraft

### PR DESCRIPTION
**Pull request by mugling**
Converts all the `CSC_UNCRAFT` recipes to `uncraft`. Required before work can continue on #18286.

Can be verified as follows:

```
#!/bin/sh

uncraft="
  data/json/recipes/recipe_deconstruction.json
  data/mods/Arcana/recipe_deconstruction.json
  data/mods/EW_Pack/ew_bullet_pulling.json
"

for file in "$uncraft"; do
    sed -i '/"category"/d' $file
    sed -i '/"subcategory"/d' $file
    sed -i '/"reversible"/d' $file
    sed -i '/"autolearn"/d' $file
    sed -i '/"id_suffix"/d' $file
    sed -i 's/"recipe"/"uncraft"/' $file
done

./tools/cleanup.sh recipe data/json/recipes/recipe_deconstruction.json
```

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It's giant. So giant that github UI doesn't display the changes to the biggest changed file.
Giant PRs are against The Rules. While it is unlikely to cause any trouble, automatic PRs like this were rejected before so I don't want to go against the rules.

If one other dev agrees (or at least "agrees if someone else agrees"), then I also agree. Then we'll have the active dev majority.
Otherwise the mod parts are fine for as long as `--check-mods` passes, but `recipe_deconstruction.json
` will need breaking.

**Comment by mugling** [comment]
> It's giant. So giant that github UI doesn't display the changes to the biggest changed file.

The UI isn't especially helpful for changes like this. It's more useful to look at the commands run and rely upon unit tests. Reviewing the entire projects JSON data by hand would be painful - smaller chunks don't necessarily make this any easier.

> While it is unlikely to cause any trouble, automatic PRs like this were rejected before so I don't want to go against the rules.

That's understandable but what was rejected and what were the reasons so we can determine the relevance here? One difference here being that there are extensive safeguards - the linter itself has unit tests, the JSON reading is much stricter and `--check-mods` is now much more robust.

> If one other dev agrees (or at least "agrees if someone else agrees"), then I also agree. Then we'll have the active dev majority.

Sounds fair. So I guess it's a decision between whose happy with automated changes, who wants to review them by hand and any alternative suggestions. The changes I have in mind are running the linter one file per PR. Any thoughts @Rivet-the-Zombie and @BevapDin?

**Comment by Rivet-the-Zombie** [comment]
So long as everything is properly tested, I see no problem with this PR.

**Comment by mugling** [comment]
> If one other dev agrees (or at least "agrees if someone else agrees"), then I also agree. Then we'll have the active dev majority.

> So long as everything is properly tested, I see no problem with this PR.

My intention is to proceed per-file. Although this idea has majority amongst active developers I'm always happy to be proven wrong by a superior technical argument

**Pull request merged**
