### PR TITLE
Add missing flags to RM13 combat armor

### PR DESCRIPTION
**Pull request by Salty-Panda**
#### Summary

SUMMARY: Bugfixes "Add missing flags to RM13 combat armor"

#### Purpose of change

When enabled the armor logs:
image
It has 40 environmental protection.

It lacks flags: "PARTIAL_DEAF", "GAS_PROOF", "GNV_EFFECT".
~~Loud sound dampening - described in activation message, logic demands from top-tier tech combat armor to have it.~~
Gas protection - full body and head coverage, 40 environmental protection.
~~Night-vision - "Vision enhancement system" in log and again, top-tier tech combat armor.~~

#### Describe the solution

~~Added those three flags~~
Add GAS_PROOF

#### Describe alternatives you've considered

I considered using `relic_data` to add Perception boost, but I don't see using `relic_data` for this purpose in any technological equipment despite it being an approximation of various supportive systems that modern tech could contain (STR boost from some servomotors, PER from aim-support etc.)

#### Testing

Worn in the game.

### CODE REVIEW

**Comment by Cyprex** [comment]
>various supportive systems that modern tech could contain (STR boost from some servomotors, PER from aim-support etc.)
I've seen power armor have less weight/encumbrance to account for servomotors carrying the armor rather than you. That said, I'm guessing this would also affect weight as an item?

**Comment by SirPendrak** [comment]
> Night-vision - "Vision enhancement system" in log and again, top-tier tech combat armor. 

Doesnt RM13 armor already have its own, hardcoded version of night vision? With greater range and without green overlay

**Comment by Mrzjadacz** [comment]
> its own, hardcoded version of night vision

Yes, my bad

**Comment by Rivet-the-Zombie** [comment]
Acoustic dampening isn't supposed to make you partially deaf - it prevents you from being deafened by loud noises, which it already does.

**Comment by Mrzjadacz** [comment]
I will check the code because it might be that entire armor is already has those functions hardcoded

**Comment by Mrzjadacz** [comment]
Code check if you wear this armor for the purposes of night vision and deaf resist.
In the end, PR only adds GAS_PROOF

**Comment by SirPendrak** [comment]
Isnt GASS_PROOF redundant if item has enviromental protection high enough? xd

**Comment by Mrzjadacz** [comment]
> Isnt GASS_PROOF redundant if item has enviromental protection high enough? xd

A few scattered checks.
You only need env_prot on certain parts to resist acid splatters,
for some gases you need 100 coverage and GAS_PROOF,
for some other you only need 100 coverage and env_prot on mouth/eyes etc.

**Pull request merged**
