### PR TITLE
Update military surplus stores

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Content "Updates military surplus palette"

#### Purpose of change
Military surplus stores were pretty empty and they could spawn some weird stuff.

#### Describe the solution
Update the mil_surplus palette with new loot tables. Rearrange military surplus stores.

#### Testing
Maps are as expected in game.

#### Additional context
We might want to dial back the amount of items this is spawning until we simulate NPC scavenging. Proper itemgroups might be desirable too.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
any pics?

**Comment by forspamnstuff** [comment]
Recently found power armor in mil surplus. Is it desirable? It is in mil_armor group.

**Comment by I-am-Erk** [comment]
That group is one of the ones that was removed because it was generating weird stuff like that

**Comment by I-am-Erk** [comment]
Hmm, we could probably do better on the mapping but that can wait for a different PR.

**Comment by ymber** [comment]
Yeah the maps need reworking and it needs to use standardized palettes. This was a quick partial fix. The third map still doesn't even use a palette.

**Pull request merged**
