### PR TITLE
[MoM] Remove extended channeling recipe after learning, add Thought-Form Construction practice recipe

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Remove extended channeling recipe after learning, add Thought-Form Construction practice recipe"

#### Purpose of change

Alerted that you can keep practicing Extended Channeling even after you already know how to Extended Channel, which is odd.

#### Describe the solution

Add a recurring EoC that checks you have the Extended or Standard Channeling trait and, if you do, remove the recipe to learn it. Replace that trick with a Thought-Form Construction practice recipe, learnable from a Project PHAVIAN training manual.

#### Testing

EoC works, manual shows up in loot lists, using the manual teaches the recipe, using the recipe trains Thought-Form Construction.

### CODE REVIEW

**Comment by GuardianDll** [comment]
Is it necessary to be a recurring eoc, instead of just "when give trait, remove the recipe also"? My understanding of autolearned recipes is that it's given when you reach the skill level it is learned, and not given when you reach levels above. I should test it

**Comment by Standing-Storm** [comment]
That's part of why I put in the deactivate_condition, so it's not running in the background forever (also, there's no example of a `gains_mutation` EoC that specifies a trait)

**Comment by GuardianDll** [comment]
What i mean is that imo adding u_lose_recipe here would be enough, though i didn't test it
https://github.com/CleverRaven/Cataclysm-DDA/blob/d2b51fdc645cf1a49bab6c06c06533737c7fd605/data/mods/MindOverMatter/recipes/research.json#L203

**Comment by Standing-Storm** [comment]
Hmm. I haven't tested it either, I just figured that since the recipe called the EoC, removing it while the EoC was running would crash the game.

**Pull request merged**
