### PR TITLE
Changed include order

### PR DESCRIPTION
**Pull request by MrSnowman**
I couldn't compile on mingw since the include order was changed. See #20848
SUMMARY: None

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Thanks a lot. MinGW was one of the compiler that wasn't tested yet.

P.S.: You need to add summary line to your PR message, e.g. ```SUMMARY: None```.

**Comment by MrSnowman** [comment]
Did I do that right? Not used to github.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
Yeah, looks good now.

**Pull request merged**
