### PR TITLE
Dragon's breath shotgun shell

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Content "Added dragon's breath shotgun shell"```

#### Purpose of change
Adding the real life dragon's breath shotgun shell.

#### Describe the solution
- Added the ammo and reloaded ammo
- Added recipe
- Added the ammo to item groups
- Added disassembly recipe

### CODE REVIEW

**Comment by KorGgenT** [comment]
it doesn't look like you added the code that destroys your shotgun that you fire the dragon's breath out of.

**Comment by RarkGrames** [comment]
@KorGgenT Well, we don't have any penalties for firing more or less similar rounds from guns not intended for them, like .223 and 5.56 mm rounds. Also, you can use a gun without any maintenance for years.

**Comment by tenmillimaster** [comment]
Tracer ammunition isn't quite the same as dragon's breath ammo. Tracer ammo usually consists of a hollow base projectile into which a flammable metal (magnesium, aluminum,zirconium, etc), an oxidize, usuallydoped with a positive anion to color the flame (strontium, barium), and a retardant of some sort (polyvinyl chloride, for example) placed within this hollow.

In a dragons breath shell, the projectile, oxidizer and retardant are omitted, yielding a much brighter and more rapid reaction.  Essentially, birdshot, but made with magnesium, and burning far more rapidly than a tracer does.

While there probably are CDDA applications for this in game (as this is much more flammable than a tracer), the rounds will have very little damage, less than birdshot, and will not travel very far at all(mostly done burning @100 ft), and will not pattern very well. (Watch these being shot in real life, then compare to birdshot patterning).

In addition their lower pressure mean it'll fail to cycle/ fail to eject out of semi-auto actions.

The hygroscopic nature of magnesium oxide, and also of any of the chloride forming retardants if reloading with harvested tracer incendiary, mean the barrel and chamber will rust very, very quickly and need to be cleaned out. FAr more  so than firing 'corrosive primer' ammunition due to the greater mass of residual hygroscopic salts.


The latter two issues aren't implementable til firearm faults are implemented; the others I'll take a look at when I'm off work later.

**Comment by RarkGrames** [comment]
@tenmillimaster If you have any suggestions about changes I will implement them.

The damage is lower than birdshot, and since the birdshot has the same range as 00 buck, I didn't modify it. I'm not against incompatibility with gas operated reloading mechanisms and weapon damage, but I don't think these can be solved in .json. This should be a thing for niche situations, so you won't be firing dozens of them on a daily basis anyways.

**Comment by tenmillimaster** [comment]
@RarkGrames #7 1/2 birdshot, the max size used for trap and skeet, has a maximum range of  209 yards for reference. https://www.carson.army.mil/assets/docs/dpw/NEPA/2015-final-seafnsi-trap-skeet-range.pdf

Compare to firequest brand dragons breath, which has a max range of 75 yards, and produces 100 foot long plumes of burning magnesium. <https://www.firequest.com/G12-013.html>

I would reduce the range of these; multiply the range by 75/209, or set it to 4.

Still at work, I'll check it out some more In a few hours.

**Comment by RarkGrames** [comment]
> I would reduce the range of these; multiply the range by 75/209, or set it to 4.

I imagine that the in game use of this shell would be to fill a corridor with flames when you try to get away from something. While the 4 range would be technically correct, I would set it to around 7, so it can be used realistically. A 4 squares long flame wouldn't be really useful in terms of gameplay.

**Comment by tenmillimaster** [comment]
> > I would reduce the range of these; multiply the range by 75/209, or set it to 4.
> 
> I imagine that the in game use of this shell would be to fill a corridor with flames when you try to get away from something. While the 4 range would be technically correct, I would set it to 6, so it can be used realistically. A 4 squares long flame wouldn't be really useful in terms of gameplay.
> 
> If I understand you correctly, then the load of the shell is simple magnesium and not incendiary, right? Would it be possible to handload these shells from raw magnesium powder?

That's correct, though raw magnesium powder would have an even lower effective range to to surface area. I don't know if the differences in mesh size is hand-wave able.

**Comment by RarkGrames** [comment]
So I've changed the load to magnesium. I left the range at 6 for both shells, which is the length of a car in game. I think if you would load sugar into a shell, even that would be effective at that range.

**Pull request merged**
