### PR TITLE
Apocalypse themed zombie horse mutations.

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Content "Adds four possible mutations for the zombie horse, based on the four horsemen of the apocalypse."

#### Purpose of change

The horse does not mutate into anything, zombie or otherwise. The zombie horse is quite fast (speed of 215) but weak as a regular zombie, and I believe something like that could use some more dangerous mutations. I decided to give them a special flair instead of just naming them "acidic horse" or "skeletal horse" because I'm a big fan of zombies with unique names.

#### Describe the solution

Four new monsters in zanimal_upgrade.json, themed after the white, red, black and pale horses respectively:

- The pestilent horse, which has acid blood as well as an acid spitting attack
- The sinewy warhorse, which has a brute slam attack, along with regeneration (1/10 of its hp)
- The smoldering stallion, which emits a cloud of smoke around it, blocking line of sight and choking anyone without a gasmask.
- The pale charger, which has a brute attack like the warhorse, though instead of regeneration it has armor plating.

The zombie horse has an equal chance to mutate into either one of the variants, and starts mutating after 42 days.

#### Testing

I figured out how to run these changes on my copy of CDDA, and they do work.

### CODE REVIEW

**Comment by LyleSY** [comment]
Love the flavor. I'd like to see  "attack_cost" lines added for each matching their speed, but otherwise this makes sense. I don't know a lot about regen balance so I'm not sure if that one is balanced but the rest makes sense to me.

**Comment by Daved27hundred** [comment]
> I'd like to see "attack_cost" lines added for each matching their speed

Sounds good. I’ll do it this afternoon.

**Review by LyleSY — APPROVED** [review]
Makes sense, clear improvement, fun choices

**Comment by AcidAntOnAMinefield** [comment]
Out of curiosity, is the "hardtoshoot" flag used just to simulate their nimbleness or something? I thought that tag was exclusively used for smaller/tiny creatures that ... well... hard to shoot at. 
This said, looking forward to seeing these 4 in the wild.

**Comment by Zireael07** [comment]
@AcidAntOnAMinefield in my experience it was mostly used for skeletons

**Comment by AcidAntOnAMinefield** [comment]
Ah yeah those have it too, kinda like the Amigara Horror too. Yeah it does make some sense they'd have it. It's just the description mentioning size threw me off.

**Pull request merged**
