### PR TITLE
Small tiles fix

### PR DESCRIPTION
**Pull request by Mshock777**
Fixed invisible items, reported on forum.

P.S.: Does anyone have a problem with Github for windows trying to track all upstream branches?

### CODE REVIEW

**Comment by Zireael07** [comment]
@Mshock777: I had problems where it would stop recognizing my local changes, eventually I gave up and have been using SourceTree for months instead with no problems.

**Comment by Mshock777** [comment]
@Zireael07 Thanks, will try it :)

**Comment by Rivet-the-Zombie** [comment]
The last time I installed github for windows it started tracking everything upstream. I really wish they'd fix that.

**Comment by DavidKeaton** [comment]
yeah I gave G4W a spin, went right back to `git log -p src/` lol

**Pull request merged**
