### PR TITLE
EoCify STARE monattack

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
🤷 
#### Describe the solution
EoCify STARE, add telepathic defence against it in MoM
things changed:
- removed avatar check when applied hallucinations - it was confirmed they work properly with NPCs now, so i don't see the reason they should be immune
- change bad effects being applied gradually if you have tainted mind effect of intensity 2, 3 and 4 for all three bad effects it has, comparing to previous "only effect intensity 3 or bigger". one in x checks are still presented
- replaced the code hallucination type, where hallucination is generated out of all monsters in the game, to EoC hallucination type, where random creature is picked from around and it's hallu copy is created
- small variation in effect length, like hallucinations are applied for 25-35 minutes now instead of being 30 minutes
#### Testing
image
image
image
image
#### Additional context
~~i think i messed up a bit in EOC_STARE4, because even if character is blind, check still return "true"~~ fixed

### CODE REVIEW

**Comment by Testudo-Cultu** [comment]
I had it set up to be gradual like this at some point in testing, but decided one application before applying a debuff wasn't balanced. This was based on the non-EOC hallucinations, though. Your hallucination system is much more reasonable, so it fits the original intended behavior very well. Thank you for taking the time to update and clean this up using your EoC sorcery.

**Comment by Standing-Storm** [comment]
Hmm...just thought of something I'm not sure there's a good solution for.

MoM has Telepathic Shield, so a replacement EoC in MoM works. But Magiclysm also has the Thought Shield spell, which maybe should also make you resist flaming eye attacks, but you can't extend EoCs so whichever mod is loaded later, only its powers would work.

**Comment by GuardianDll** [comment]
mod can change the spell to rearrange EoC to another one, or we can add another fake step for some mods, or one mod can change `EOC_STARE1`, and another can change `EOC_STARE2`, but none of this are good approaches imo

**Comment by Maleclypse** [comment]
Move both MoM and Magiclysm to check for a shared trait/flag.

**Comment by GuardianDll** [comment]
That will remove nice flavor messages then

**Pull request merged**
