### PR TITLE
Option to spawn starting npc

### PR DESCRIPTION
**Pull request by Night-Pryanik**
- Added `STARTING_NPC` world generation option. It has 3 switches: `Always`, `Never`, and `Scenario-based`;
- `STARTING_NPC` option has a prerequisite of `STATIC_NPC` option;
- `Never` will (obviously) never spawn a starting NPC while other static NPCs such as the ones at the evac center will still spawn;
- `Always` will always spawn starting NPC;
- `Scenario-based` is the default switch. It will show the `No starting NPC` text under the `Scenario Flags` section. This switch will spawn a starting NPC only for scenarios without the `LONE_START` flag. Affected scenarios are:

-- Challenge-Medieval Peasant;
-- Challenge-Lab;
-- Ambush;
-- The Next Summer;
-- Sheltered;
-- Challenge-Abandoned;
-- Experiment;
-- Wilderness;
-- Helicopter Crash;
-- Bottom of a Mine;
-- Out of Town;
-- High Tech, Low Life.

As you can see, this list includes most of the scenarios. Feedback on which scenario should be added or removed from the list are welcome.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Should not be "Scenario-based" be default? It should be very strange to meet NPC in the center of the locked lab.

**Comment by Leland** [comment]
> Should not be "Scenario-based" be default? It should be very strange to meet NPC in the center of the locked lab.

Not if you were there together

Anyway, I'm a fan of `always` being the default. Starting NPCs have a glossary of tips to help new players, and also provide a starting quest that helps provide some kind of direction in the early game. Plus, it maintains the existing behavior and won't disrupt people updating the game.

**Comment by Firestorm01X2** [comment]
>Anyway, I'm a fan of always being the default. Starting NPCs have a glossary of tips to help new players, and also provide a starting quest that helps provide some kind of direction in the early game. Plus, it maintains the existing behavior and won't disrupt people updating the game.

In default scenario, of course.
But "At least we have a shelter" and " go scavenge city" level tips in challenge scenario in the locked lab have literally no point.

**Comment by Leland** [comment]
NPCs can actually read off the hints in https://github.com/CleverRaven/Cataclysm-DDA/blob/8badff72e358bc7d9f889dc635e922880fcf0cf2/data/json/hints.json

Try the "Any tips?" question

**Comment by kevingranade** [comment]
I agree that scenario based should be the default, if you want hand-holding from a starting NPC, you should either override the option or pick a beginner-oriented scenario.

**Comment by JazzGuru** [comment]
This is a brilliant idea!  Can't wait till it makes it in... :)

**Comment by mlangsdorf** [comment]
A future PR could build on this by providing lists of NPC classes for the various scenarios. Having a NPC spawn in a lab start who was also a test subject, or having a fellow naked and afraid NPC for that scenario, would make a lot of sense.

I don't want to hold up this PR for that. It's definitely a future improvement to consider.

**Pull request merged**
