### PR TITLE
Facial hair

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Content "Adds facial hair that can be chosen at chargen."```

#### Purpose of change
This follows the new hairstyles recently added to the game.

#### Describe the solution
It's mostly JSON work along the lines of hair styles and skin tones.

#### Describe alternatives you've considered
Considered locking this "mutation" type for female characters for obvious reasons, but this should be done separately imho.
This might be later enhanced by some extra attributes like long beard protecting your mouth from wind or giving a bit of extra warmth.

#### Additional context
Tileset artists, especially @SomeDeadGuy, might want to take a look at this.

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Oh snap, what did I do wrong that all of this is mixed in?

**Comment by SomeDeadGuy** [comment]
You figiried a way to give beards only to men?
Cause i do not want any bearded women! xD
Ofcourse i can assign empty tile to all female facial hairs, but it still gonna be seen in character description.

**Comment by ralreegorganon** [comment]
> Oh snap, what did I do wrong that all of this is mixed in?

You want to base your branch off of and PR into development instead of master.

**Comment by nexusmrsep** [comment]
Thanks for the advice, closing for now.

**Pull request closed without merging**
