### PR TITLE
Scent Tracking Slimes

### PR DESCRIPTION
**Pull request by jsstchur**
#### Summary
Bugfixes "Removed Slimes ability to track by scent"

#### Purpose of change
Relates to #62681 and making monsters that track by scent slightly more appropriate

#### Describe the solution
Removed species wide ability for Slimes to track by scent, and added it back to Slime sub-species that have the "SMELLS" flag (namely the amoebic mold).

#### Testing
Spawned some slimes in via the debug menu to ensure that scent was not a factor in their pursuit of me, so far so good.

### CODE REVIEW

**Comment by Venera3** [comment]
What's the reasoning behind chemotaxis working for one set of nether nasties but not for the almost-identical other (which is *spawned* by the first)?

They should both be able to smell, in my eyes.

**Comment by Karol1223** [comment]
> What's the reasoning behind chemotaxis working for one set of nether nasties but not for the almost-identical other (which is _spawned_ by the first)?
> 
> They should both be able to smell, in my eyes.

Personally I'd go with neither should be able to smell. Given our smell is more like dog tracking, than even human smell, basic chemotaxis would likely not be enough to warrant the flag.

**Comment by Venera3** [comment]
They don't have much else to track food, and hearing is not reliable enough.

**Comment by I-am-Erk** [comment]
I kind of agree with venera here... to be honest, I think I'd prefer slimes to be deaf, than to be unable to smell. They're more likely to have chemoreceptors and photoreceptors than ears.

I don't have really strong feelings on it though. You could convince me otherwise with a behavioural example for why our smell is dumb on slimes

**Comment by Venera3** [comment]
I agree in principle re deafness, though ingame that would make them only track characters since monster don't smell.

**Pull request closed without merging**
