### PR TITLE
Update monster_attacks.json

### PR DESCRIPTION
**Pull request by arockperson**
Changed messages to be more consistent and accurate. Now, they always mention the body part that is hit, and the messages for no damage hopefully make it clear that they did no damage because of armor.

Also added messages for dodging.

#### Summary
Bugfixes "Monster special attack messages more consistent and clear"

#### Purpose of change
I've been trying to make combat messages more consistent and accurate as mentioned in #49709. Some of the combat messages list the body part that is hit, but others don't. Also I feel that some of the messages for receiving no damage didn't adequately make it clear that you took no damage because of your armor, instead of dodging the attack or the monster missing. I think the messages are much less ambiguous now.

#### Describe the solution

Changed all the messages in monster_attacks.json to mention the body part that is hit, and made the no_dmg_msg more clearly reflect that it's based off your armor. no_dmg_msg for NPCs still doesn't mention body part because the player probably doesn't need to know that. Also added dodge messages for the player and npcs.

#### Describe alternatives you've considered

Could have left it as is, or changed all of the messages to NOT mention body parts to be more consistent (which would be horrible, I feel).

#### Testing

Tried getting clawed, slammed, and impaled (fun) by monsters, and everything seemed in order. Did the same with NPCs.

### CODE REVIEW

**Comment by actual-nh** [comment]
Should slams really be directed at a bodypart?

**Comment by arockperson** [comment]
> 
> 
> Should slams really be directed at a bodypart?

Heh, changing the message made me think the same thing. It feels kind of silly for a kevlar hulk to slam into your foot, and highlighting it in the message makes that silliness more obvious. IMO it's worth changing, especially to make the slam attack feel more unique compared to clawing, but that's a different issue of course.

**Comment by AccountAlias** [comment]
"The hulk slams into your eyes" sounds pretty meme worthy 😄

**Comment by actual-nh** [comment]
Ping: @Venera3 - have you looked at the slam special attack?

**Comment by Venera3** [comment]
I'm going with a new attack for smashing, but at a glance removing eyes/mouth from slams sounds reasonable. Bump damage up to 12-15 if you do that, to compensate missing out on the unprotected targets (and 8 damage for kevlar hulks is just, wow).

**Pull request merged**
