### PR TITLE
Add more makeshift firearms

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add more makeshift firearms that can be crafted.

Added weapons:
1. Makeshift lever shotgun.
2. .30-06 pipe rifle. (Craftable version of Survivor Special 700 gun.)
3. Triple-barrel 40mm launcher.

Also remove unneeded specific plural form for survivor's .223 carbine.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Triple barrel 40mm launcher. Because there's no such thing as too much dakka.

**Comment by AppleConnoiseur** [comment]
Would it be possible to makeshift rig individual shells and grenades in a generic way? Would be quite cool to make use of 40mm ammo early game :P.

**Comment by kevingranade** [comment]
40mm ammo, with a few exceptions (some flares and some of the shot rounds)
uses a complex multi-stage propellant that makes it unsuitable for crafting.
There might be some alternate loads that aren't normally used, but would
make sense for someone to make if they don't have access to proper 40mm
rounds.

**Comment by chaosvolt** [comment]
Right. Makeshift launchers for it might be viable, but handloads would logically be more awkward.

**Comment by Cyrano7** [comment]
.50 cal rifle made out of pipes? Sounds a tad bit dangerous. There already is a homemade .50 cal rifle in the game made out a m2 machine gun barrel but its a one shot per reload gun. They use old heavy machine gun parts to make homemade anti-materiel rifles in places like Iraq, Libya and Syria. Those are the bolt action, one shot type though. Having a 5-round, lever fed, homemade .50 cal rifle seems a bit unbalanced.

**Comment by Rivet-the-Zombie** [comment]
>Having a 5-round, lever fed, homemade .50 cal rifle seems a bit unbalanced.

And *massive*; the material stresses in a .50BMG firearm are so high that you're not going to kludge one together without either a full machine shop or the disassembled remains of an extant .50BMG firearm (as in the existing .50 rifle recipe).

**Comment by Cyrano7** [comment]
I have a suggestion. Maybe break this PR up into individual guns. Its hard to review and crunch the numbers for balance on 5 guns at once. It would make debate easier to. btw I like the Double-barrel sawed-off pipe shotgun and the plural name fix. But since they are bundled up with everything else its gonna take longer to get to them.

**Comment by Cyrano7** [comment]
On a side note here is a youtube channel about a guy who makes homemade guns. And he tries to make a .50 cal rifle https://www.youtube.com/watch?v=sfOC53Oo5yY he fails but some of his other guns are pretty cool.

**Comment by Soadreqm** [comment]
@Cyrano7, that was very impressive and quite educational. What I'm getting from this is that although it might be possible to build a .50cal rifle out of scrap metal, it involves several rather tricky engineering problems. And even if it works perfectly, you definitely risk breaking some bones.

Anyway, the more makeshift guns there are, the more I feel like the crafting system can't adequately represent the process of making them. :stuck_out_tongue: It'd be so much *neater* if instead of specific recipes, you could specify a handful of generic firearm types (pipe rifle, single-shot handgun, revolving-barrel full-auto carbine) with crafting difficulty, material requirements and weapon stats calculated from bullet damage. It'd be a balancing nightmare, but one can dream.

As for these particular weapons, I can't really think of a situation where I'd WANT to fire three grenades at once, except as a point-blank take-them-with-me measure. Can't really argue with more dakka, though.

**Comment by kevingranade** [comment]
On Jan 1, 2016 5:07 PM, "Soadreqm" <notifications@github.com> wrote:
> Anyway, the more makeshift guns there are, the more I feel like the
crafting system can't adequately represent the process of making them.

I'm very strongly leaning toward rejecting any more complicated guns rather
than trying to add a system to handle it better. Crafting guns is a stretch
even with the simple guns, and making novel and complex guns is far over
the line into unrealism.

**Comment by chaosvolt** [comment]
> I'm very strongly leaning toward rejecting any more complicated guns rather than trying to add a system to handle it better. Crafting guns is a stretch even with the simple guns, and making novel and complex guns is far over the line into unrealism.

I can still see this idea having merit with respect to the diverse array of plausible pipe rifles, double pipe rifles, sawn variants etc. Depending on if providing a framework for it saves more code than multiple redundant .json entries, which is possible but may not be plausible.

Though this is ultimately just a suggestion for why the idea behind it might not be useless, unsure whether it's worth attempting.

**Comment by kevingranade** [comment]
Just FYI, this isn't blacklisted or anything, I keep looking at it and going, "I need to check the balance", then decide that I don't have enough time to do it.

**Comment by Cyrano7** [comment]
Im kinda against the triple-barreled grenade launcher. Such a gun would be quite heavy and impractical especially if it was homemade. A double-barreled side-by-side 40mm gun would be more realistic to wield and make. Guns start getting really heavy and the trigger mechanisms start getting complicated after 2 barrels. That's why there isn't a lot of tripe barreled guns around. When using pipes and lacking in finely made parts I don't see that gun being craft-able.

**Comment by Rivet-the-Zombie** [comment]
I think the triple launcher [was inspired](http://metrovideogame.wikia.com/wiki/Medved) by another game, and I'm not against it for something like this so long as it's suitably heavy and massive (maybe a bit bigger/heavier than it is currently?). It doesn't have to have multiple triggers or anything; a lot of old double barrel shotguns use a single trigger, and you only cock the hammers on the barrel(s) you want to fire when you squeeze it.

**Comment by Cyrano7** [comment]
Even if it you had to manually cock all the hammers like a single action it would be hard to make. Muti-stage triggers are complicated too.

**Comment by chaosvolt** [comment]
Since I always assumed that the pipe guns were less "pull the trigger" and more "pull the chamber closed to force the cartridge onto a nail" then I would assume a triple 40mm launch is very simple. Just that it'd be triple-shot only unless you want a less insane design. XP

**Comment by Darkyhard** [comment]
> I think the triple launcher may have been inspired by another game.

It is based on this exactly, actually.

> I'm not against it for something it so long as it's suitably heavy and massive (maybe a bit bigger/heavier than it is currently?)

This thing looks quite light on the picture that is provided in the article. Also, it's already significantly bulkier than single-barrel pipe launcher.

> Just FYI, this isn't blacklisted or anything, I keep looking at it and going, "I need to check the balance", then decide that I don't have enough time to do it.

What about these? #14520, #14601, #14602 

The problem is that I have messed up my master branch while trying to rebase it, so the only option left is to completely delete it and create new fork, but I would like to do this after all my PRs get merged/closed so that their content wouldn't get lost.

**Comment by chaosvolt** [comment]
> What about these? #14520, #14601, #14602 

Small problem. I'm also working on an addition to medieval mod, that right now only needs a PR by @Coolthulhu to be merged, then it'll be ready to use.

**Pull request merged**
