### PR TITLE
Taste Modifier bionic

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Adds new bionic Taste Modifier"```

#### Purpose of change
Added a new bionic that nullifies negative enjoyment value from any comestible with negative `joy`. In fact, it's more of a flavor/roleplay stuff as there ain't many items with negative `joy` value, and the values ain't so big to care about. But why not? Especially if people [liked](https://discourse.cataclysmdda.org/t/what-are-some-bionics-youve-always-wanted-to-see/19101/19) the idea.

#### Describe the solution
Added bionic `Taste Modifier` and bionic item `Taste Modifier CBM`. If active and player has enough bionic energy (equals to `joy` value), it will nullify the value of any comestible with negative `joy`.
Added bionic to the `bionics` item group spawn list.
Added bionic to the starting bionics list for Bionic Soldier, Bionic Prepper, Bionic Sniper, and Bionic Monster professions.

#### Additional context
Inactive bionic:
изображение

Active bionic (note that only negative values of `JOY` aren't shown):
изображение

Proofs:
изображение

### CODE REVIEW

**Comment by Rail-Runner** [comment]
Wouldn't it be better to only get it to nullify negative fun values? It might be tedious to turn in on and off for different foods (if anything, we could assume that character does it automatically).

**Comment by Night-Pryanik** [comment]
> Wouldn't it be better to only get it to nullify negative fun values? It might be tedious to turn in on and off for different foods (if anything, we could assume that character does it automatically).

Ok, done.

**Comment by Night-Pryanik** [comment]
I don't know if this bionic suits any profession. Any suggestions?

**Comment by nexusmrsep** [comment]
Why does it only nullify negative joy? If it works by cutting the sensory neural connection to the tongue it'd be a double edged sword where you would feel nothing, no taste at all, be it good or bad, as long as it's active.

Of course it's easily bypassed by simply turning off before eating good tasty chocolate and turned on when eating awful jug of lard, but it makes much more sense this way then a targeted system.

**Comment by Rail-Runner** [comment]
> Why does it only nullify negative joy? If it works by cutting the sensory neural connection to the tongue it'd be a double edged sword where you would feel nothing, no taste at all, be it good or bad, as long as it's active.
> 
> Of course it's easily bypassed by simply turning off before eating good tasty chocolate and turned on when eating awful jug of lard, but it makes much more sense this way then a targeted system.

Balancing via tedium is never a good thing. Like I said, it may be assumed that character turns it on and off automatically depending on the specific item they're about to consume.

**Comment by nexusmrsep** [comment]
> Balancing via tedium is never a good thing. Like I said, it may be assumed that character turns it on and off automatically depending on the specific item they're about to consume.

Then add energy consumption for every automatic on/off action it would require, and automatic toggle to keep track if it's on/off.

**Comment by Rail-Runner** [comment]
> > Balancing via tedium is never a good thing. Like I said, it may be assumed that character turns it on and off automatically depending on the specific item they're about to consume.
> 
> Then add energy consumption for every automatic on/off action it would require, and automatic toggle to keep track if it's on/off.

Or just remove activation power cost and make it drain power only when it's actually used.

**Comment by Night-Pryanik** [comment]
> Or just remove activation power cost and make it drain power only when it's actually useful and only if set to "on" on bionics list.

Done.

**Comment by Amoebka** [comment]
While I like the idea, I'm a bit perplexed by the lore implications of this thing. Bionics are a new commercial technology, presumably a very expensive one. Yet this bionic is only really useful for people eating garbage foods. Surely anyone too poor to afford decent food wouldn't be able to afford a hi-tech bionic either? Who was this thing even designed for, in-universe?

**Comment by Maddremor** [comment]
Another issue is that taste is only part of disliking comestibles. Texture will remain, as will the character knowledge of them eating rotten food/insects/human flesh/whatever. A simplified solution would be to cap the negative joy that the bionic could negate.

**Comment by Fris0uman** [comment]
Could be for soldier or astronaut that are forced to eat poor tasting food in the field ?

**Comment by Amoebka** [comment]
As for professions, Bionic Monster should definitely have this. It already has bionics that help digest rotting raw meat and such.

And if it is indeed a military tech, then Bionic Sniper as well. That one seems to be centered around surviving alone in the wilds.

**Comment by Night-Pryanik** [comment]
> Another issue is that taste is only part of disliking comestibles. Texture will remain, as will the character knowledge of them eating rotten food/insects/human flesh/whatever. A simplified solution would be to cap the negative joy that the bionic could negate.

I enhanced bionic. Divided it into two parts, one in mouth, and the other in the brain. The mouth part intercepts various data of the comestible (such as taste or texture) from the receptors in mouth and sends it to the brain part. The brain analyzes data, and if it finds it "bad", it modifies it and sends it forth the brain. Cheated brain considers all "bad" comestibles have neutral taste.

**Comment by Night-Pryanik** [comment]
> As for professions, Bionic Monster should definitely have this. It already has bionics that help digest rotting raw meat and such. And if it is indeed a military tech, then Bionic Sniper as well. That one seems to be centered around surviving alone in the wilds.

Added it to Bionic Monster, Bionic Soldier, Bionic Prepper, and Bionic Sniper professions.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/latest-experimental-features/5582/1106

**Pull request merged**
