### PR TITLE
Remove spore-producing monsters from the spawn lists, add them in the fungal locations and some other fungus-related changes

### PR DESCRIPTION
**Pull request by SariusSkelrets**
#### Purpose of change

As of now, fighting the Mycus is so boring that the two favorite methods to deal with it are keeping the fungaloids out of the realty bubble of just use the no fungi mod. I want to change that.

#### Describe the solution

Remove the fungaloids and other spore producing monsters from the spawn lists by remplacing them with fungal tendrils (i changed their death function from FUNGUS to DISINTEGRATE) and adding them in the fungal locations

Allow the spire and the tower to use the FUNGUS_BIG_BLOSSOM attack each 10,000 turns to prevent locking them in an endless fire with a single molotov and adding flavor as the Mycus strikes back to protect the tower and the spire.

Finally, add the FUNGUS attack to the fungal hedgerows around the tower to help it to restart the expansion after someone threw a molotov on it

#### Describe alternatives you've considered

leaving the Mycus broken as it is now

#### Testing

1. Create a world
2. Teleport to spire
3. See the fungal tendrils who can't produce spores far away on the map
4. See fungaloids around the core structure
5. throw a molotov and keep the sporelings in the fire
6. wait until the spire stops the fire
7. visit the the other fungal locations and repeat

### CODE REVIEW

**Comment by or-or** [comment]
Wouldn't this effectively dial down Mycus encounters to almost nil unless you go looking for them? Likewise, wouldn't this make terraformed areas a rarity?

**Comment by SariusSkelrets** [comment]
I didn’t changed the fungal location spawn so they’re still on the map and i plan to add far bigger fungal areas if that PR is merged like one big as the military base from the overrun scenario to introduce them in the late game as you try to clear a massive fungal infestation by yourself.

The three basic fungal will be the smallest ones. The bigger locations will also contain some new fungal monsters to vary the fight. 

The fungaloid spawn on the overmap is the source of the hate for the Mycus as they’re everywhere but you can’t light them all at once so there’s always one who’ll survive and undo your changes, AFAIK making wanting to search them. 

My goal for now is to make the Mycus interesting instead of annoying. When people will want to burn it all for fun, roleplay or a npc quest, i’ll be here to add a lot of things to diversify the fungus like fungal beehives with fungal giant bees trying to stab you and that npc quest to clear a fungal area.

**Comment by nexusmrsep** [comment]
Fungaloid invasion serves a purpose, however annoying may it be to some players. There is nothing even remotely comparable to the looming doom it brings, and the feeling you can't deal with it. It's a "oh shoot, run" enemy we actually need. Not even Triffid queens induce such horror as incoming fungus terraforming invasion. Nerf it and you will bland the game to oblivion. What next? Fluffy unicorns that carry you by hand throughout the apocalypse? One of the unique features of this game is it having enemies you go fight and enemies you go "nope" on sight. Don't take it away please.

**Comment by UmbralReaper** [comment]
Like Nexusmrsrep, I dislike the idea of removing the almost infinite abilities of the mycus - in my mind, that's what the fungus does. However, I fully support making the mycus more interesting, as currently they are rather bland.

**Comment by SariusSkelrets** [comment]
I fully agree that the Mycus should be able to multiply without limits and it’s why i plan to never nerf its spread. The problem with the Mycus is that the «oh shoot, run» doesn’t come from the danger or the fact they multiply faster than you kill them, it comes from the massive lag and the «they can’t spread if they’re not in the bubble» causing people to just stay far away of the fungus and forget it exists until they see a light gray/light blue/yellow T on the overmap and path to stay the farthest as they can of the fungus

What i want to do is making the current fungal locations the smallest ones as if the spread begun hours ago. You cleared the tower? Good, but there’s an one hundred times bigger fungal area nearby with multiple core structures and things like fireproof fungaloids. Do you really want to fight that one?

Another thing i want to do if i find how it could be possible to do is making the fungal locations you find in the game bigger and bigger as the time passes. Start at the default date and you’ll mostly find the smallest ones, start in winter and the fungal areas will be bigger than hub-01 and if you wait or start years after the cataclysm you’ll find a fungal area far bigger that the overrun scenario military base and filled to the brim with fungal monsters you’ve never seen before so you can’t just keep them out of the bubble if you want to stay fungal-free since AFAIK spread simulation outside of the bubble is impossible.

The result would be that you could destroy that spot next from your home alone, you could clear larger ones with help from npcs but clearing the biggest fungal infestations would be humanly impossible. Maybe the blob and the triffids could succeed but an human army will be stopped by the fungal creatures and those who joined the Mycus and killed as their deathmobile is torn apart by fungal abominations.

Also, there’s no fungal ground between the spawned fungaloids and it removes the feel of expansion around the tower and makes no sense for me.

Finally, there’s an alternative or two for the fungaloids removal-of-the-spawns-then-including-in-the-structures: shrinking the spawn area so the fungaloids stand on the same fungal ground instead of wierd little patches or finding how to generate fungal ground to connect all the spawned fungaloids and the tower. The result is the same, making a big terraformed area instead of some spots ten overmap tiles far away but makes the bigger fungal areas even bigger as they need to cover more ground that the base one and i don’t know how to do one of the two options above.

**Comment by nexusmrsep** [comment]
If that's the goal, than I'm all for it. Seeing late game fungaloids barely starting to fungalize the area seems unnatural, and having large areas already fungalized with specialized fungaloids found only within would be awesome.

That's why I also hope @ZhilkinSerge will some day get back to the postprocessing mapgen feature that was once abandoned. Other idea is to use map extras postprocessing ability for that purpose, which is limited but, depending on implementation, might work in some cases.

As for performance - perhaps fungaloids activity could be reduced when that are already on fungal beds. And I've surely missed the full discussion, but @I-am-Erk mentioned to me that  some kind of limiter to fungaloid activity in relation to distance of the main supporting structures would be also in place if someone were to add it. I guess it's far fetched, but it would be be an eye candy to see if fungaloids could under some circumstances make new towers, or in general place new alien organic structures on the fungal beds.

**Comment by or-or** [comment]
Thanks for clarifying.

**Comment by SariusSkelrets** [comment]
Yes, that’s the goal to make the Mycus an endgame menace while not ruining the early game with thousands of fungals facing your evacuation shelther just after you spawned.

The multiplication of the fungaloids based on their proximity with the core structure is a great idea who’ll remove the need of my changes as they wouldn’t spread enough to undo your extermination or not at all without the structure.

One thing we must find is how they will be affected by the distance between them and the tower/whatever. Are they slowing down the spore production? Are the spores less effective when too far of the structure? Are the fungaloids able to survive without a core structure? All of them at once? The choices give the same results: the fungals are bound to the core but each one affect the differently.

An option to create more core structures could be that fungaloids merge together in a group/mass able to be effective/survive farther as the merged fungaloids include new ones into itself (could work as the dissoluted devorer and be based on the mass/group max hp) and after attaining a certain threshold they would take root as a new structure.

One cool addition for the endgame fungal location would be that the super core structure at the center talks to you a la rat king, trying to convince your determinated character who produced thousand of liters of fungicide and killed many mycus humans equipped with firearms and enough environmental protection to ignore the fungicide to join its side. If you destroy the structure, you’ll find a grey jelly described as  «smelling incredibly good» and «you have the feeling that eating this thing will be the best decision of your entire life» who’ll give you the marloss gateway trait and spawn the fruit as the Mycus wants to assimilate the human who want to destroy it so much and was kinda successful at that.

**Comment by I-am-Erk** [comment]
I missed this when it was a fresh discussion, but I don't think this is the right answer to mycus problems. As nexusmrsep set, the issue is more that fungus spreads way too quickly and indiscriminately. It's a relatively simple C++ project to make fungus expansion related to distance from fungal power centers, and I think that's the solution we need to look at. This will change the fungus to a trivial little curiosity encountered in minor zones on the world map, and that's too extreme.

**Comment by SariusSkelrets** [comment]
Yeah it’s what i think too now. Binding the fungus to the core would slow the spread and increase the importance of the cores structures. 
However, i admit that the fungal locations should evolve with time because the Mycus isn’t a little bit bigger even if you start the next summer and if the fungals need the core, just take a random car and crush the tower and the fungus is no longer a threat (or it seams) and adding bigger fungal locations with new monsters and towers add to the depth of the Mycus.
 IIRC, the Mycus is the only faction that wasn’t taken from another movie/game/so its why I would love to see them gaining even more depth and complexity

**Comment by I-am-Erk** [comment]
OK, I'll close this PR then, let me know if you'd like to reopen it and run it in a different way

**Pull request closed without merging**
