### PR TITLE
[Aftershock] fix speedloader for RM99

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Bugfixes "fix speedloader for RM99."

#### Purpose of change
saw the issue posted about on a [reddit thread](https://www.reddit.com/r/cataclysmdda/comments/rcdsnm/speed_loader_not_working/)

#### Describe the solution
Added the speedloader to RM99's pocket data

#### Describe alternatives you've considered
none

#### Testing
1. start new game with aftershock mod
2. spawn in an RM99 and an RMGS5 speedloader 
3. empty the RM99
4. reload the RM99 with the speedloader
5. success

### CODE REVIEW

**Review by John-Candlebury — APPROVED** [review]
Thanks for the fix!

**Comment by I-am-Erk** [comment]
This just needs a quick push to restart the builder that is stuck

**Comment by catdach** [comment]
I'm not quite sure what that means. Assuming that's something I need to do, how would I go about doing that?

**Comment by I-am-Erk** [comment]
You could merge upstream if you know how to do that, or just make a tiny change and then undo it.

**Pull request merged**
