### PR TITLE
Perspiration, evaporation cooling

### PR DESCRIPTION
**Pull request by Robik81**
#### Summary

SUMMARY: Features "Perspiration, Evaporation cooling, heat effect balancing"

#### Purpose of change

Human body is awesome. And one of its awesome features is perspiration - thermoregulation via evaporative cooling. 

I had some problems while cooking near the stove in late spring... well, I had to cook naked to not cook myself as well. Which led me to GitHub issues where I found issue #43451 this PR hopefully at least partially fixes. Issue talks about heat effect in general and ways to balance it, but what struck my eye the most was mention about perspiration.

I started digging in the code and I found that in relevant function that handles character wetness are following lines:
_// TODO: Make evaporation reduce body heat_
and
_// TODO: Make clothing slow down drying_

It was like a glove to be picked up.

#### Describe the solution

- material [breathability](https://en.wikipedia.org/wiki/Breathability) in material.json to relevant clothing materials, range is 0 - 100 (none to full), defaults to none, I did my best to set appropriate values, but comments are welcome
- new [perspiration](https://en.wikipedia.org/wiki/Perspiration) effect used in hot effect, which causes... wetness, it can be potentially used in other effects that cause non-heat perspiration, like some kind of fear effect or illnesses
- evaporation cools you body, wetness does not have to come from sweat, you can also submerge yourself in the pool for a moment, or something
- evaporation rate is reduced by clothing, light summer clothing is quite okay, but running around in leather duster during summer can lead to drenching yourself in your own sweat and nasty morale penalties
- heat effect now causes more thirst (i feel it was negligible before)
- reduced speed penalty of heat slowdown effect to half, it is per body part and just being warm caused quite harsh penalty

notes about implementation
- uses current wetness and does not track sweat as a separate entity, from the cooling effect perspective, it should not make a difference where the liquid came from
- increased range of drench capacity of body parts is to achieve finer granularity of evaporation
- wet-o-meter tool prints info about wetness and heat level of all body parts, just for testing, not added to any item groups
- reduced average drying time from 2 hours to 30 minutes, now that is is later affected by clothing

#### Describe alternatives you've considered

It was possible to just tweak existing heat effect around the edges, but...

#### Testing

I tested that the code is running without any noticeable issues and it appears that it does what was intended. What is yet to come is live play test, hence the WIP tag in the caption.

Useful tool for testing is wet-o-meter. Feel free to spawn one.

#### Additional context

Perspy was not harmed in any way during the testing...
image

### CODE REVIEW

**Comment by CountAlex** [comment]
That's pretty awesome feature to have! Would you consider adding an action of pouring water on player character? Like putting water from a flask or w/e on your clothes if there's no place to dive into to get wet.

**Comment by Robik81** [comment]
> Would you consider adding an action of pouring water on player character? Like putting water from a flask or w/e on your clothes if there's no place to dive into to get wet.

Indeed I am. 

I thought about leaving it to separate PR, but having this feature for my test run might be quite useful.

**Comment by Robik81** [comment]
I implemented the pouring action via unload from container / interaction with other sources of water on map, though I am probably going to PR it as a followup.

To keep things simple for reviewers and the person who can do the merge.

**Comment by NickVolynkin** [comment]
Earlier, being wet used to lower your morale. Now it can be useful, so being wet when it's hot should raise morale, right? As a general rule, if being wet decreases heat from positive values down to zero (or 30), it's fun, otherwise not fun.

**Comment by Robik81** [comment]
Whether you gain or loose morale for being wet depends on clothing you have. Swim and some sports gear give morale bonus.

Just being sweaty is not going to give you a penalty, as sweat should evaporate before lots of it accumulate. Unless you are running in leather or similarly unbreathable gear while sweating.

**Comment by dissociativity** [comment]
would low stamina not cause additional heat and thus perspiration too?
I don't think, unless there's been recent changes, that the game replicates this.

**Comment by Robik81** [comment]
There is new Weariness system #43985 that tracks weariness from activities that have activity level ranging from NO_EXERCISE to EXTRA_EXERCISE. I can definitely see the possibility of modifying it to not only raise weariness, but also body heat. That will in turn cause perspiration once the body part reaches the Warm status.

There is also a discussion about weariness in issue #44326.

**Comment by kevingranade** [comment]
> uses current wetness and does not track sweat as a separate entity, from the cooling effect perspective, it should not make a difference where the liquid came from

It doesn't make a difference where it came from, but it matters where it is when it evaporates.  Only evaporation very close to the skin carries heat away from the body.  Water in clothing is going to evaporate, but not impact body heat much, unless the clothes are so soaked that it acts like a big heat sink.

Overall I'm a bit concerned about the lack of either reference to IRL sources or in-game use cases. This really needs some stuff like, "character wearing so-and-so outfit doing exercise foo is comfortable" for validation.

**Comment by Robik81** [comment]
> Only evaporation very close to the skin carries heat away from the body. Water in clothing is going to evaporate, but not impact body heat much, unless the clothes are so soaked that it acts like a big heat sink.

True, though I believe that the game tracks only wetness that actually got to your skin, not wetness on the gear itself, that did not penetrate. Given that wetness causes morale penalty.

> Overall I'm a bit concerned about the lack of either reference to IRL sources or in-game use cases.

Body using perspiration as a way to regulate its temperature is not in a dispute I believe? Nor is the evaporative cooling? In-game use case is that the player has currently good options about dealing with cold, not so much with heat. It seems to me (individual player experience, though if we go by the referenced issue I am not alone) that it is pretty easy to get warm in mild temperatures. It could be solved by tweaking the numbers instead of introducing new system, but given the existence of TODO comments in the code, I thought that something akin to what I implemented was planned to be added at some date.

Other use is, that it fit well in tandem with suggestion about activities raising your body heat, if that was implemented at a later date.

> This really needs some stuff like, "character wearing so-and-so outfit doing exercise foo is comfortable" for validation.

Hmm, wouldn't such stuff be related more to a PR that would tweak what clothing gives what morale bonus during activity x? This PR is not changing what clothing is giving bonus / penalty when character is wet. These are kept as they are, sorry if I implied differently.

**Comment by dissociativity** [comment]
Player is in summer, heat sucks for movement speed and extra thirst, player perspires.
Player is wearing nasty leather gear and is drenched in sweat, not terribly comfortable nor breathable

Player instead wears light nomad gear for summer, is far les wet, is able to perspire and cool down, therefore not getting heat penalties nearly as much without having to strip down to essentially naked and take full damage.

case made.

**Comment by Robik81** [comment]
I can see that I did a pretty bad job explaining things in the **Purpose of change** section, though @dissociativity got it right. I am not good at explaining my thoughts, sorry about that. Let me try to amend it.

The purpose of change is to simulate the fact, that human body is capable to handle excessive heat on its own, to a degree, and with associated cost of increased thirst, via perspiration through the evaporative cooling. The evaporative cooling is hindered by wearing clothing made from material with low breathability, thus incentivizing the player to choose more fitting clothing for his current situation.

Now that I read it after myself, I am not sure if I did better job than before... well, I tried.

**Comment by anothersimulacrum** [comment]
Suggestion: replace the integers for breathability with string values, that the loading turns into integers. Raw integers are messy, provide too much control, and don't really mean anything to humans. Having a few enumerated states would be better.

**Comment by Night-Pryanik** [comment]
@Robik81 is this being worked on?

**Comment by Robik81** [comment]
@Night-Pryanik I didn't have time to test it properly, though I do plan to return to it this month.

**Comment by Night-Pryanik** [comment]
Ok, could you please convert it to draft and remove the WIP tag then?

**Comment by Shodan14** [comment]
Any chance that the scent system could eventually link in what that? e.g. more sweat-stronger scent etc.

**Comment by dustan1** [comment]
One thing I think could be added but isn't exactly "Perspiration, evaporation cooling" would be cooling/heating from respiration. The insides of our lungs are basically hot and sweaty 100% of the time, and we lose a small but significant amount of heat and water from breathing under regular conditions. This loss would scale with temperature and humidity like perspiration.

**Comment by I-am-Erk** [comment]
I didn't realize there was a WIP pr for this, I had just started writing up an implementation.

I would really like to see this get done. @Robik81 are you still around? if you'd like, we could try to get this in as one of the last big parts of 0.G, calling it part of the armour revamp. If you're not around, I may see if we can get someone to adopt this and not let it languish.

**Comment by Robik81** [comment]
@I-am-Erk I am currently busy with work and only god knows when I will be able to return to finish it. Feel free to take it over completely, in part or as an inspiration for your own implementation. 

That goes for everyone who is willing and able to do it, of course.

Though I don't have time to play CDDA currently, I would be really happy if something akin this is implemented when I will have time to play again!

**Comment by I-am-Erk** [comment]
Thanks for the quick reply. I'll look and see, maybe this can be quickly made functional and merged and we can sort out the fallout from there.

**Comment by I-am-Erk** [comment]
Was going to take this over directly but on second thought if I do, I'd prefer it to be another PR. I have moved it to the appropriate projects so it doesn't get missed and I will close this PR.

**Pull request closed without merging**
