### PR TITLE
Added passenger train car

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Features "Added passenger train car"```

#### Purpose of change

#21792 became kinda bloated with all the changes, so I decided to split it up to several smaller chunks. This one adds passenger train car vehicle. Vehicle won't be spawned automatically and will be used later to be spawned on railroads.

#### Additional context

image

image

image

### CODE REVIEW

**Comment by park66665** [comment]
Hello, I'm just curious, but is that passenger train car on the picture derailed? Rail isn't supposed to be used that way.

**Comment by ZhilkinSerg** [comment]
It was debug spawned. Proper aligning of railroad vehicles to railways is a whole new follow-up project.

**Comment by Shodan14** [comment]
Looks good, but what's with all the floor trunks?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Looks good, but what's with all the floor trunks?

That's for the luggage.

**Pull request merged**
