### PR TITLE
Lean

### PR DESCRIPTION
**Pull request by Broken-Admin**
* Sidenote: I added Sprite not Seven-Up, I used 7-up as a placeholder for Sprite until I had added Sprite

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I don't feel like we really need three new item types for a single type of new candy. If it is somehow necessary, then it needs to use the `copy-from` function for those items' definitions.

**Comment by BorkBorkGoesTheCode** [comment]
7-up is redundant. lemon-lime soda is in-game.

**Comment by Cyrano7** [comment]
Having three specific flavors of jolly ranchers seems excessive. Maybe having one generic flavor, basically a mixed bag would be better I think.

**Comment by AMurkin** [comment]
In the distant future, there could be a game (mode) using a variety of subjects (rip Lua). But now, really, there is no sense.

**Comment by Night-Pryanik** [comment]
What is this stuff? Candy with drugs? Drinkable? Do we really need it?

**Comment by kettleswordfang** [comment]
**Sprite** and **Jolly Rancher** are also registered trademarks. i think that's an issue.

**Comment by Broken-Admin** [comment]
We have a few items in-game that aren't exactly needed `Ex. Dildo` It adds morale but doesn't have to be used. It can be completely ignored if it's unwanted and the Jolly ranchers can be eaten by themselves,

**Comment by Broken-Admin** [comment]
Cyrano7, what do you mean by a mixed bag?

**Comment by kettleswordfang** [comment]
now you just gotta remove `sprite` from the item groups + replace sprite with `lemonlime` in the recipe.

the components should also be on one line --
```    "components": [ [ [ "jr_grape", 1 ], [ "jr_apple", 1 ], [ "jr_watermelon", 1 ] ], [ [ "codeine", 2 ] ], [ [ "sprite", 1 ] ] ]```

check out http://dev.narc.ro/cataclysm/format.html re: formatting

**Comment by Broken-Admin** [comment]
As hard as I tried I ended up getting tired and forgetting to follow the previous formatting of recipes, sorry about that.

**Comment by ZhilkinSerg** [comment]
I believe you will have to lean back on those sprite and fanta things.

**Comment by Broken-Admin** [comment]
Stop, I'm fine with using lemon lime...

**Comment by Zireael07** [comment]
"I wanted orrange, and it gave me lemon lime!"

**Comment by ZhilkinSerg** [comment]
> "I wanted orrange, and it gave me lemon lime!"

That was terror, squad.

**Comment by Broken-Admin** [comment]
👌

**Comment by Broken-Admin** [comment]
I'd love to ask, why?

**Comment by Zireael07** [comment]
Probably closed due to inactivity.

**Pull request closed without merging**
