### PR TITLE
Remove Murrsuits, Adjust HWP EXODIC Conversion, Add Filk

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Content "Removes fursuits from sex stores, 12.3 HWP needs special magazine, filk"

#### Purpose of change

It felt really weird having fursuits in sex shops, as while sexual fursuits do exist (murrsuits), they're not only less common than fursuits, but since fursuits are pretty much always custom made, having some ready to go in a shop is unheard of. Also since the 60 round Exodii PA md 68 is now a pan mag, it shouldn't fit into the HWP. Filk is also a music genre that I know at least one other person knows of. 

#### Describe the solution
Removes fursuits from sex shops, removes exodii magazine from HWP. Adds filk

#### Describe alternatives you've considered
Adding in an even rarer version of fursuits, murrsuits, that have 1% less coverage

#### Testing
image
image
image
ss_merch_3 is where the fursuits were, and magazine dont fit no more. 

#### Additional context
Should fursuits be more common in tailor basements, and should fursuits be a high level tailoring craft?
Also filk is pretty much fictional folk music, here are some examples 
https://www.youtube.com/watch?v=-mO7vkdkJhg
https://www.youtube.com/watch?v=ud6LiVJkwyA
https://www.youtube.com/watch?v=nAk5ane_9AQ

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Fursuits probably shouldn't be common anywhere as they're vanishingly rare irl. They should definitely be craftable though.

**Comment by Paprika-H** [comment]
> Fursuits probably shouldn't be common anywhere as they're vanishingly rare irl. They should definitely be craftable though.

Probably, but I'm unsure of how to properly adjust it, IIRC the fursuits are all already weighted with 1

**Comment by fairyarmadillo** [comment]
It's probably fine to leave it as-is, unless someone wants to go through and make all common stuff many times more likely. That's a whole project though.

**Comment by Maleclypse** [comment]
Hmm wonders if I should add post apocalyptic folk music. That would include songs like “I made a promise to the moon”

**Comment by Paprika-H** [comment]
> Hmm wonders if I should add post apocalyptic folk music. That would include songs like “I made a promise to the moon”

Is this new music or an existing genre? If its new I don't see how it'd get downloaded into MP3 players or in stereo systems

**Comment by fairyarmadillo** [comment]
The new timeline says the actual apocalypse has only really been going on for like a month, I'm not sure why that would exist beyond like Draco Dune writing a song in the last day or two.

**Comment by Maleclypse** [comment]
I see I am introducing you all to an actual current genre.  https://www.youtube.com/watch?v=Vk6W80zsFSs

**Comment by Paprika-H** [comment]
> I see I am introducing you all to an actual current genre. https://www.youtube.com/watch?v=Vk6W80zsFSs

Ngl I thought you were making a reference to https://www.youtube.com/watch?v=DCEewyIE_0c

**Comment by kasanryukin** [comment]
Fursuits don't really require high sewing skills.  90% of the hard work actually goes into the construction of the head.  If anything, there should be an electronics and a fabrication requirement added.  Most medium to high end fursuit heads have integrated cooling systems because those things are very hot to wear for long periods of time.

While among the furry community, fursuits are pretty common with probably about 3/5s of all furries having at the very least a partial suit (usually feet, hands/arms, and a head), the distribution of them in game should be astonishingly rare.

However, the greater New England area does have some of the largest concentrations of furries, along with the largest convention attracting thousands of attendees.


Don't ask me why I know all this, I'm already trying to forget I know it in the first place.

**Comment by Paprika-H** [comment]
> Fursuits don't really require high sewing skills. 90% of the hard work actually goes into the construction of the head. If anything, there should be an electronics and a fabrication requirement added. Most medium to high end fursuit heads have integrated cooling systems because those things are very hot to wear for long periods of time.
> 
> While among the furry community, fursuits are pretty common with probably about 3/5s of all furries having at the very least a partial suit (usually feet, hands/arms, and a head), the distribution of them in game should be astonishingly rare.
> 
> However, the greater New England area does have some of the largest concentrations of furries, along with the largest convention attracting thousands of attendees.
> 
> Don't ask me why I know all this, I'm already trying to forget I know it in the first place.
> 
> Edit: adding them to hotel/motel loot lists wouldn't be a terrible idea.

Once I have the energy I could turn the fursuits all to variants and then put them in motels/hotels. Biggest issue though is that furry conventions dont last very long, so it'd be kind of weird having a somewhat regular spawn of fursuits when its out of season (pun intended)

**Comment by fairyarmadillo** [comment]
I was thinking it might be worthwhile to go through the item groups and slap an extra zero on anything that is relatively common. Then we could stick oddball items in people's closets without making them ubiquitous.

That is like a whole ass project though.

Furry con stuff might be better done as its own map special. You'd copy a normal hotel and adjust the decorations, zed spawns, and itemgroups accordingly. That way most hotels would be normal and occasionally you'd find one where a convention had been going down.

Other variants could include anime cons, trade shows, or other potentially interesting events.

**Comment by Paprika-H** [comment]
> I was thinking it might be worthwhile to go through the item groups and slap an extra zero on anything that is relatively common. Then we could stick oddball items in people's closets without making them ubiquitous.
> 
> That is like a whole ass project though.
> 
> Furry con stuff might be better done as its own map special. You'd copy a normal hotel and adjust the decorations, zed spawns, and itemgroups accordingly. That way most hotels would be normal and occasionally you'd find one where a convention had been going down.
> 
> Other variants could include anime cons, trade shows, or other potentially interesting events.

Imagine the seasonal thing where christmas related stuff spawns on christmas and using it for shit like fur cons

**Comment by kasanryukin** [comment]
Does August have a seasonal special? That's when the con is if I remember
right.

**Comment by KittyTac** [comment]
> Fursuits don't really require high sewing skills. 90% of the hard work actually goes into the construction of the head. If anything, there should be an electronics and a fabrication requirement added. Most medium to high end fursuit heads have integrated cooling systems because those things are very hot to wear for long periods of time.
> 
> While among the furry community, fursuits are pretty common with probably about 3/5s of all furries having at the very least a partial suit (usually feet, hands/arms, and a head), the distribution of them in game should be astonishingly rare.
> 
> However, the greater New England area does have some of the largest concentrations of furries, along with the largest convention attracting thousands of attendees.
> 
> Don't ask me why I know all this, I'm already trying to forget I know it in the first place.
> 
> Edit: adding them to hotel/motel loot lists wouldn't be a terrible idea.

I have many furry friends.

Definitely not 3/5s have a fursuit. It's less than 1/10 probably. Maybe it depends on demographic.

**Pull request merged**
