### PR TITLE
Ir shooting

### PR DESCRIPTION
**Pull request by kevingranade**
Fix a bug that was making IR vision very inconsistent, and allow targeting monsters visible via IR with ranged weapons.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woo!

**Comment by BevapDin** [comment]
The zombie that is only visible via infrared appears as zombie (not as unknown creature, visible via infrared) in the monster compass and in list of monsters around. Beside being displayed as red question mark, it's like the character can see the creature normally.

**Comment by illi-kun** [comment]
Visibility of zombies in IR means they radiate the heat, and I'm wondering why?

**Comment by Rivet-the-Zombie** [comment]
I guess the black slime that animates them is an endothermic entity?

**Comment by kevingranade** [comment]
More like, "ir vision is 'cool' and it'd be a waste if you couldn't see
zombies with it" ;)
Otoh, it shouldn't generally allow unlimited vision through walls, should
be attenuating somehow.

**Comment by kevingranade** [comment]
I see the problem, thought I'd checked who was calling get_visible_creatures(), evidently I didn't or I missed some.
Here's both a more targeted and more general fix :)

**Pull request merged**
