### PR TITLE
Groups have precedence for loot mapgen [WIP]

### PR DESCRIPTION
**Pull request by mugling**
Follows #19380

Currently we have 10 different syntaxes for specifying item placement via JSON which map to 3 disparate code paths. Two of those code paths have very unintutitive rules controlling the number of items that will be placed. We should aim for a single code path and more restricted (and better documented) syntax.

Specifying items by `itype_id` in JSON mapgen should be discouraged. It prevents true blacklisting and is also problematic for mod authors that may wish to override those spawns.

This PR adjusts `place_loot`, which is being used for all new mapgen code, to try an `item_group` first and only if not found to attempt placement by `itype_id`. In this way mod authors can transparently override item placement by defining a group with the same id.

### CODE REVIEW

**Comment by acidia** [comment]
Hey, I have no problem with changing how we are writing item spawns in JSONs but how do you want the following to be written in the new format.
`"items": {"@": { "item": "bed", "chance": 60 }}`
Counting out squares to define locations is incredibly tedious and I didn't see an example for place_loot in this format.

Is there an alternative way you would like single items to be placed if not by itype_id?  I'm assuming creating a group with a single item would be discouraged.

Even though it won't land for a while, I'm still looking at spending many hours working on item spawns shortly.
#19257

**Comment by Coolthulhu** [comment]
How about allowing loot placing function to define a symbol instead of `x` and `y`? Though the implementation of that could be weird.

**Comment by mugling** [comment]
> How about allowing loot placing function to define a symbol instead of x and y? Though the implementation of that could be weird.

Doesn't this work already?
```
loot: {
    "P": { "item": "foo" ... },
    "Q": { "item": "quux" ... },
}
```

Because if not adding support for that should be trivial and could help mapgen authors a lot

**Comment by BorkBorkGoesTheCode** [comment]
It works (thanks for telling me pisskop) but it isn't well-documented in mapgen.md. It needs some way to control spawn chance.

**Comment by mugling** [comment]
@BorkBorkGoesTheCode elaborate?

**Comment by BorkBorkGoesTheCode** [comment]
At the time, I'd forgotten that spawn chance worked with the "spawn on character system".


Idea: could the system spawn a item on every designated tile if a successful roll occurs? For example, could the game generate a continuous wall on every "/" tile without rolling for every "/" tile?

**Comment by Reclusive-reptile** [comment]
I don't think letter designation allows for magazine or ammo arguments either.

**Comment by kevingranade** [comment]
> Specifying items by itype_id in JSON mapgen should be discouraged.

This is incorrect, it is totally reasonable for building layouts to specify
specific items.  It is not reasonable to allow mods to remove core items
but to support them using core mapgen.  Basically that mapgen entity has a
dependency on the mod the item is defined in.

The only sane thing we can do in case an explicitly specified item is
blacklisted is not spawn anything, but that's fine.

**Comment by mugling** [comment]
`discouraged != deprecated`. A lot of the mods (generic guns, extended guns etc) are heavily dependent upon item groups, eg. `guns_pistol_common`. A syntax that allows specifying specific `itype_id` whilst still allowing mods to provide alternatives doesn't remove support for either option.

**Pull request closed without merging**
