### PR TITLE
Mg controlled burst

### PR DESCRIPTION
**Pull request by ArcanErasmus**
#### Summary
```SUMMARY: Balance "Adds controlled burst modes to machine guns"```

#### Purpose of change
Having only a full-auto option for MGs is both crippling to their utility and unrealistic. In the name of ammo-saving, players need a way to not just zip tie the trigger down when firing full-auto-only guns.

#### Describe the solution
This PR adds a "burst" mode to all full-auto-only guns, representing a controlled pull of the trigger. This lines up with how real soldiers are trained to use these weapons, and how you would likely *want* to use them in-game.

Luty-pattern guns (as well as the STEN) were given longer bursts to represent the unrefined trigger pull these guns would inevitably have, making fine control difficult.

In addition, I went through and changed the JSON definitions of guns which used the "burst" tag to instead use the "modes" tag, with strictly defined semi and auto modes. This is just a code cleanup, no functionality change.

#### Describe alternatives you've considered
Making the cheapo guns' bursts even longer.

Putting the JSON cleanup in a separate PR.
Not doing the JSON cleanup at all.
Standardizing the JSON in the other direction, to use the "burst" tag.

#### Testing
Tested a sample of the guns changed. The JSON edits worked fine, the new short bursts worked fine, both on Luty and other guns.

### CODE REVIEW

**Comment by ymber** [comment]
See discussion in #31947.

**Comment by ArcanErasmus** [comment]
That is a great discussion thread, thanks! It sounds like the changes I want to make would be obsolete eventually, but such a feature isn't exactly ready to push. So, this seems like it would still be an acceptable stopgap measure to help curtail wild ammo spraying, until the new system is ready.

**Comment by kevingranade** [comment]
I'd rather just replace the "full auto fire" option with the "burst" option for the time being than have a useless option hanging around (in other words, just cut burst size to something reasonable).  Even if you want to mag dump, "burst", "burst", "burst" with no aiming in between gets you to roughly the same place.

**Comment by ArcanErasmus** [comment]
In that case, what do you think about cutting burst sizes down to "reasonable" (3-5, based on their auto fire rate) numbers across the board? For example, the ACR has semi and 11-round auto, and I could change that to semi and 4-round burst.

**Comment by mrkybe** [comment]
It would be nice if burst control was something scaled with your character's skill level with that kind of firearm.

Someone who's never touched a gun trying to burst fire an UZI in a stressful situation should a harder time than someone with a lot of SMG skill.  Likewise though, someone with a lot of rifle-skill should be able to somewhat consistently pull off bursts of 2 shots.

**Comment by ArcanErasmus** [comment]
Alright so for now I removed the full auto, but I also bumped up the burst size by 1 for all 6 guns affected. My logic was that it's still more awkward to fire controlled bursts intended for on-target hits with MGs, and if you really wanted controlled shots you would bipod or vehicle mount them like they were designed for. As for the Luty weapons, I figure it's a way of highlighting that they are homemade and still fairly sketchy, and as such, the trigger pull is gonna suck.

@mrkybe as per ymber's comment, see #31947. That's something I have neither the codebase familiarity nor design time to handle right now. This is basically a stopgap measure.

**Comment by ArcanErasmus** [comment]
I'm still open to dropping them down to 3 round burst if you think it makes more sense though.

**Comment by mrkybe** [comment]
I'd personally prefer a 3rnd burst.  But I'm not anyone to tell you what to
do lol.  If any of the main devs care to weigh in here, go with that.

**Comment by kevingranade** [comment]
Yes absolutely, cut everything down to a quarter second worth of fire or so.

**Comment by ArcanErasmus** [comment]
I was holding on to these commits for a little bit. Basically, I cut down automatic fire to about one third. On the logic that a weapon with a 3-round burst mode is going to put out at least somewhat more when on "auto", I changed burst sizes based on their original full-auto burst (or occasionally from googling fire rates):
- Less than 10 -> 3
- 10-14 -> 4
- 15-19 -> 5
- 20+ -> 6

I felt that this would strike a middle ground between total realism and game balance. For instance, almost all assault rifles end up with a 4-round "auto" mode, while SMGs usually see 5, or sometimes 6 round bursts. I didn't want to go higher than 6, because further rounds are increasingly wasteful, but I wanted to represent how fast-firing weapons *are* more wasteful. A 4-round burst is probably the upper limit to practicality at medium ranges, with anything higher requiring a very specialized build.

Some research was also done by watching random videos of people shooting guns, and looking at how many shots they seemed to put out with short pulls of full auto weapons.

I didn't touch any of the really weird weapons, like blob stuff, monster weapons, or undecipherable mod gear. I think this is also incomplete, so definitely let me take another look at the weapons before calling anything good.

**Comment by Outta-my-way-burrocrat** [comment]
Please list the original fire rates in GAME_BALANCE.md so others won't have to re-research the wheel.

**Comment by cainiaowu** [comment]
This change may also help the sudden turret death issue, if I read the code correctly, turret is using same mg weapon, so reducing the burst will somewhat nerf the turrets.

**Pull request merged**
