### PR TITLE
Fix missing nullptr check causing null deference in some builds

### LINKED ISSUE #10817: SIGSEGV in release build caused by rattlesnake
- use release build (has to be built with clang++, not gcc)
- spawn a rattlesnake
- wait a few turns, sometimes player-movement triggers it, too

Unfortunately this only happens in optimized builds, -O0 "fixes" the issue.

```
(gdb) run
Starting program: /home/alex/build/cataclysm-git/cataclysm-tiles 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff4dc2700 (LWP 8099)]
[New Thread 0x7fffe8b3d700 (LWP 8100)]
[Thread 0x7fffe8b3d700 (LWP 8100) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff73f87af in __dynamic_cast () from /usr/lib/libstdc++.so.6
(gdb) bt
#0  0x00007ffff73f87af in __dynamic_cast () from /usr/lib/libstdc++.so.6
#1  0x000055555561ea04 in monster::attitude_to (this=0x55555b0dee00, other=...) at src/monster.cpp:461
#2  0x000055555561e8ca in monster::attack_target (this=0x55555b0dee00) at src/monster.cpp:444
#3  0x00005555556f5a36 in mattack::rattle (this=<optimized out>, z=0x55555b0dee00, index=0) at src/monattack.cpp:161
#4  0x0000555555640208 in monster::move (this=0x55555b0dee00) at src/monmove.cpp:267
#5  0x0000555555655b6b in game::monmove (this=0x555559184880) at src/game.cpp:6525
#6  0x00005555556500f1 in game::do_turn (this=0x555559184880) at src/game.cpp:1484
#7  0x000055555582a82b in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:296
(gdb)
```

git [bisect](https://gist.github.com/namarrgon/9bf0f0b11581ab7eec7b) points at five commits of which none will build due to various issues:

3ed386291fdc1cbbc096f2eb34546cf11ad6dbc2 Fix bad fix
41d6ed5fbd382667ba339d35b43777a703a146bc Fixing errors at manual merge
41da7a0535d42fd0a5017fc2c26ea4b0db85b509 Remove unused parameter to silence warning
6befa0db18eecbf18554af9642158ebce5ae21a2 Merge branch 'master' into playerless-monattacks
5b254c4f283ce65b45e81c789990705830cba318 Allow some of the special abilities to target non-players

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7636758-sigsegv-in-release-build-caused-by-rattlesnake?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Should fix #10817

I forgot a nullptr check in monster::attack_target.
On some builds this didn't cause anything, because creature reference apparently got passed as (Creature*)nullptr. Code that uses attack_target tests for nullptr, so it worked.
Other builds probably tried to deference the pointer causing a crash.

### CODE REVIEW

**Comment by KA101** [comment]
npc::look_for_player called, but we can see u!

(Received when I spawned a rattlesnake into the evac shelter: it didn't rattle at all, despite the NPC immediately moving in and meleeing, but eventually disappeared and I got that debug message whenever within one tile.)

Sorry, Coolthulhu.

**Comment by Coolthulhu** [comment]
Damn, I really hope I won't need to set up clang on my own just to test those strange build-dependent bugs. Windows doesn't like setting up stuff.

Not-rattling rattlesnakes is another (minor) bug - they check for hostility, but stay neutral to player.

**Comment by Coolthulhu** [comment]
Oh, I found why does the "see u" spam happen - the rattlesnake can stumble "under" the NPC. This is not a new bug, but I can try to fix it here.

**Comment by KA101** [comment]
No worries.  I found a crash bug that's been rarely popping up since yesterday, couldn't reproduce it with a debugger attached.  Got it tonight.  Will file it as a separate issue.

**Comment by Coolthulhu** [comment]
Rattlesnakes back to rattling only at the player. Making them rattle at other stuff would probably require far more code than it's worth.

**Pull request merged**
