### PR TITLE
Thermal Electric set rebalance (#55572)

### LINKED ISSUE #55572: Balaclava & Thermal electronic balaclava stats
### Is your feature request related to a problem? Please describe.

The normal balaclava has a warmth value of 30, 3 encumbrance and and 95% coverage,

While the thermal electronic balaclava has a warmth value of 10, 100% coverage and 0 encumbrance. 

Of course the thermal electronic balaclava has 60 warmth when it is turned on. 

I also looked at the cut-resistant balaclava which has the same coverage and warmth as the normal balaclava.

### Solution you would like.

I think we want the thermal electronic balaclava to have the same stats as a normal balaclava while it is turned off. 

### Describe alternatives you have considered.

I tried looking for an existing PR that changes this, but couldn't find one. This is my first time submitting something, so maybe I am doing something wrong. 

I also considered going over all of the clothing items first to see if their values makes sense (which I am sort of doing for a guide), but figured that it is probably easier to implement some of these changes on an item-to-item basis.

### Additional context

balaclava in debug

thermal electric balaclava in debug

### PR DESCRIPTION
**Pull request by Croisis**
#### Summary
Balance "Rebalance Thermal Electric set stats"

#### Purpose of change
Resolves #55572
* Balanced all thermal electric set parts
* Balanced non-electric items used in TE recipes

#### Describe the solution
Streamlined the warm underwear items to 30 warmth, 0.2mm thickness, 100% coverage and 2 encumbrance (VARSIZE, so fits 1).
All TE set items, balaclava, union suit, glove liners, socks and wool socks tweaked to match this baseline.
TE socks and TE gloves now require 2 pairs of socks and glove liners respectively to double the thickness and warmth.
Light gloves are not usable in the TE gloves recipe anymore (they are a normal layer item, not skintight).
TE set items keep the 60 warmth when turned on.

#### Describe alternatives you've considered
Having the TE outfit with different stats for each covered part to match the original components but this seemed unreasonable.

#### Testing
1. Spawn affected items
2. Check their stats

#### Additional context
Switched the flags for the XL, XS and ON versions of the modified items to "extend": { "flags": [ "XXX" ] } format instead of complete relisting for good measure.

### CODE REVIEW

**Comment by Croisis** [comment]
If I read the log correctly, one of the tests in ranged_balance_test.cpp fails because it assumes that the balaclava has encumbrance of 5 but I've intentionally changed it to 2.
Is it OK for me to just change the test's expected result as well or what is the proper course of action in this case please?
Sorry for asking a probably stupid question but I'm just starting and I'd rather be safe than sorry.

**Comment by BrettDong** [comment]
> Is it OK for me to just change the test's expected result as well or what is the proper course of action in this case please?

Yes, updated expected value in the test.

**Comment by Night-Pryanik** [comment]
Could you please resolve conflicts?

**Comment by I-am-Erk** [comment]
Closing as abandoned. Can be reopened if author returns.

**Pull request closed without merging**
