### PR TITLE
Reveal wires on simple wooden walls

### PR DESCRIPTION
**Pull request by Lalomb0000**
#### Summary
Bugfixes "Added the ability to reveal wires on simple wooden walls"

#### Purpose of change
reveal wires function was missing on simple wood walls, and since log walls had them i thought the change was justified

#### Describe the solution
to add the flag

#### Describe alternatives you've considered
to remove the flag from log walls

#### Testing
tested

### CODE REVIEW

**Comment by akrieger** [comment]
I consider it more a bug that log wall has it. None of the damaged variants of either wood wall have it either.

**Comment by Maleclypse** [comment]
When did it get added to log walls? It was specifically intended to not be on log walls and some others I thought.

**Comment by Aeiouuu01234** [comment]
so what is the consensus?

**Comment by akrieger** [comment]
@Maleclypse #53983

**Comment by Maleclypse** [comment]
> @Maleclypse #53983

#60671 I have no one to blame but myself.

**Pull request closed without merging**
