### PR TITLE
Update RetroDays Tileset

### LINKED ISSUE #23075: Crash/Seg Fault using retrodays tilesets on linux 64bit
Game version:
0.C-26487-gfca10df

Operating system:
Linux 64bit - Ubuntu Mate 
4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Tiles or curses:
Tiles

Mods active:
Default Set

### Expected behavior
Play the game with "retrodays10" tileset or "retrodays20" tileset

### Actual behavior
Game crashes to desktop.
Console Output:
Segmentation Fault (Core Dumped)

### Steps to reproduce the behavior
-Start game in tiles mode with default/stock config (I used a fresh install right from the site)
-Select "retrodays10" tileset or "retrodays20" tileset
-Enjoy game

### Other Information
I have fixed this issue by installing an older version of the tilesets
This issue has been happening for me since at least 0.C-7151

### PR DESCRIPTION
**Pull request by matdombrock**
I added the new tileset 'retrodaysJar' (https://discourse.cataclysmdda.org/t/retrodays-tileset-update-2018/14791) by Jar which is the newest and most up-to-date version of the retrodays set and should continue to be maintianed. 

This was inspired by #23075. But does not actually alter or fix the original retrodays tilesets. 

It seems that the old retrodays sets are no longer being maintained and or more or less obsolete. Removing them was outside of the scope of this PR. 

Update:
The scope of this PR has changed somewhat and it now fixes #23075 by updating the original tileset.

### CODE REVIEW

**Comment by Leland** [comment]
If there's a newer version (and with signoff from the original artist in that thread), we'd probably want to replace the Retroday rather than creating another tileset, no?

**Comment by matdombrock** [comment]
I briefly discussed the matter of replacing the original tilesets with the discord dev channel and it seemed best to leave the original sets in place. However it does seem that they are now obsolete. Maybe it would be best to remove them. 

If that's the case I we can close this PR and I'll submit a new one later tonight with the removed sets.

**Comment by Leland** [comment]
Do you mind posting that discussion here if it's not too far back? Interested in the rationale for keeping the older version around.

**Comment by matdombrock** [comment]
> 
> MA☥LK🜍⛧🜍 - Today at 12:03 PM
> So I'm working on a Pull Request that will add the newset version of the retrodays tileset 'retrodaysJar'. 
> 
> But I'm really not 100% sure on procedure and I actually want to be helpful here. 
> 
> So I have forked the repo, created a new branch in my local copy and commited the changes. 
> 
> Should I merge my branch back to master and then do a pull request or just do a pull request without merging my branch first?

> kevin the mattress - Today at 12:03 PM
> you can just PR
> unless there's a conflict in the files you touched it won't matter

> MA☥LK🜍⛧🜍 - Today at 12:04 PM
> So just without merging my new branch?

> kevin the mattress - Today at 12:04 PM
> I assume you forked in the last few days or so, and retrodays hasn't been touched in a while, so yes

> MA☥LK🜍⛧🜍 - Today at 12:04 PM
> Forked about 20 mins ago haha

> kevin the mattress - Today at 12:05 PM
> yea, definitely no need to merge

> MA☥LK🜍⛧🜍 - Today at 12:05 PM
> This change doesnt actually touch the existing retrodays sets, it adds a new one

> kevin the mattress - Today at 12:05 PM
> oh.... why?
> I mean the old one causes that crash, so it's pretty useless

> MA☥LK🜍⛧🜍 - Today at 12:05 PM
> There is a new author, https://discourse.cataclysmdda.org/t/retrodays-tileset-update-2018/14791
> 
> It is not the same tileset technically
> Cataclysm: Dark Days Ahead
> RetroDays Tileset (Update 2018)
> RetroDays Tileset (Update 2018)   ==========================  CHANGELOG   12.01.2018 - First attempt. 21.01.2018 - Now all missing tiles are filled.  24.01.2018 - Fixed railroad tiles.  ==========================  FEATURES   Added several missed images compared to original Edited few images for more immersion If you love RetroDays theme but something annoys you, you can ask me to fix it.  ==========================  HOW TO INSTALL   Download file https://drive.google.com/file/d/1tcHMVExDLHgdqnEA...
> 

> ZhilkinSerg - Today at 12:06 PM
> He just filled in all the missing tiles.

> MA☥LK🜍⛧🜍 - Today at 12:06 PM
> Do you think this new one should just replace the old versions then?(edited)

> kevin the mattress - Today at 12:06 PM
> I'd definitely prefer to overwrite the original

> ZhilkinSerg - Today at 12:07 PM
> Probably just put editor name somewhere.

> MA☥LK🜍⛧🜍 - Today at 12:07 PM
> @kevin the mattress thats what I was thinking. Might as well not remove the originals right now. Its outside of the scope of my PR anyways

**Comment by matdombrock** [comment]
On rereading this log, it seems that Kevin WAS in fact in favor of removing the old sets. I need to work on my reading comprehension. 

I will submit a new PR tonight if that is what we want to do.

**Comment by Leland** [comment]
Yup, both approaches work insofar as getting this great content mainlined but overwriting the existing one will keep things simple  👍

**Comment by matdombrock** [comment]
Alright, I can do that. However, my reason for thinking they should stay for now is that if I just remove the two older tilesets, players currently using them who upgrade the game will load up with a missing tileset since their config will be requesting a tileset that no longer exists. This new version is  named 'retrodaysJar' as oppsed to 'retrodays10' or 'retrodays20'. 

I could rename the tileset so that this issue doesn't happen, but I can't rename it to cover both of them because that would be redundant. 

IIRC loading the game with a missing tileset doesn't cause an error but it also doesn't notify the player as to what happened. 

What do you think about this? Is alright to just drop those old tilesets entirely? There isn't really a clean way to actually overwrite them as far as I'm aware.

**Comment by Leland** [comment]
> if I just remove the two older tilesets, players currently using them who upgrade the game will load up with a missing tileset since their config will be requesting a tileset that no longer exists.

Agreed, wouldn't recommend this approach.

> I could rename the tileset so that this issue doesn't happen, but I can't rename it to cover both of them because that would be redundant (it would require 2 copies of the same tileset)

Can you clarify this a little more? Right now retrodays20 is just a pixel-doubled version of retrodays10 (see #14902). Shouldn't require 2 copies, unless I'm missing something.

**Comment by matdombrock** [comment]
Sorry that was a bit confusing. I didn't fully understand the relationship between these tilesets. 

It seems this new set is just a replacement for 'retrodays20'. 

So I can overwrite 'retrodays20' but that will leave 'retrodays10' unchanged (and still buggy). 

I'm not familiar with actually modifying tilesets so I don't know how to turn this into a replacement for 'retrodays10'. 

Is 'retrodays10' still needed? If so, is someone else willing to turn this new tileset into a replacement for 'retrodays10' or explain to me how I can do that myself? If not should it be removed?

**Comment by Leland** [comment]
I believe if you do the following everything should work as expected:

1. Put this PR's `tiles.png` into the current retrodays10 folder, replacing the existing one
2. Put this PR's `tile_config.json` into the current retrodays20 folder, replacing the existing one
3. Copy this PR's `tile_config.json` into the current retrodays10 folder, replacing the existing one. **And** remove every instance of `"pixelscale": 2` from the file.

**Pull request merged**
