### PR TITLE
Convert ammotype to string_id

### PR DESCRIPTION
**Pull request by BevapDin**

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It broke tests hard.

Other than that looks good, even if conflict-y (will most likely break all big PRs on the list).

**Comment by Coolthulhu** [comment]
Warning: the `NULL_ID`s here could cause the crash - the same one as in `iuse_actor`. It will need testing on multiple compilers.

**Comment by BevapDin** [comment]
> Warning: the  NULL_ID s here could cause the crash - the same one as in  iuse_actor . It will need testing on multiple compilers.

Shouldn't be a problem. The only `itype´ instance created early is the null type in "item.cpp" and that uses the default constructor with does not instantiate any of the item slot classes.

But I'm aware of that problem.

**Comment by mugling** [comment]
PR is solid but why not implicit construction of string_id<foo> from `std::string`?

**Comment by Coolthulhu** [comment]
> PR is solid but why not implicit construction of string_id from std::string?

Implicit conversion is mildly convenient, but highly dangerous.
It causes weird bugs such as vector constructor being invoked with static pointers rather than strings. At the same time most of the cases where it looks useful boil down to mild convenience.

An example that actually caused problems in the code looked like:
```
static const std::vector<std::string> some_vector = {{
    "string a", "string b"
}};
```

The constructor of the above vector converted the strings into `char *`, then to `int`s or something like that. The end result was a hard to find bug that wouldn't happen if the strings were an opaque type with no implicit constructor.

**Comment by BevapDin** [comment]
> why not implicit construction of string_id from  std::string ?

Explicit construction ensures the program has chosen that type on purpose. A string is not an id, it can be used to create any type of id, so it needs explicit mentioning of the type.

For example `if( foo.ammo_type() == "battery" )` - that "battery" may refer to the item type (and the condition should actually check `foo.ammo_current()`) or it could refer to the ammo type, what is it?

----

Unrelated note: I remove the "pointer_fake_ammo" as it is not used anywhere.

**Comment by mugling** [comment]
Fair enough, makes sense

**Pull request merged**
