### PR TITLE
Implement discrete power storage bionics

### PR DESCRIPTION
**Pull request by Coolthulhu**
Lack of limits on power storage bionics is a blocker for bionic slot system.

SUMMARY: Features "Implement discrete power storage bionics."

Here I implement:
* Encapsulation of bionics. The bionic vector is a private `Character` field. A direct reference to a bionic can be acquired, but the vector itself should only ever be changed by dedicated functions.
* Ability to install duplicate bionics. Currently only handles power storage (hardcoded by id), rest can't be duplicated. Duplicate bionics all share the same invlet, because they are identical in every respect except position in vector.
* Discrete power storage bionics. That is, power storage is now something you get out of actually having bionics, not something you gain after you install them but not connected to them.
* Save migration that gives characters with power storage value the proper bionics. It is lossy because I don't want to solve the backpack problem here, so it rounds bionic count up. Won't grant more than 100 free power, so it's not a big deal.

### CODE REVIEW

**Comment by Noctifer-de-Mortem** [comment]
How will this affect profession definitions? Will the `bio_power_storage` and `bio_power_storage_mkII` become obsolete and need to be dropped?

**Comment by Coolthulhu** [comment]
No, professions stay the same.
They specify explicit bionics and use `add_bionic` to install them, meaning they don't need any adjustment.

**Comment by illi-kun** [comment]
Any important reasons why this wasn't implemented?

@Coolthulhu could you resolve merge conflicts of this pr to make merging it to the mainline easier?

**Comment by Coolthulhu** [comment]
@illi-kun It was supposed to be a post-0.D thing, since it would be a pretty major, possibly unbalancing and problematic (gameplay-wise) change.
I could resolve the conflicts this weekend if we want it now, but I'd need a confirmation first.

**Comment by illi-kun** [comment]
@Coolthulhu okay, thanks for info, it makes sense.

**Comment by ZhilkinSerg** [comment]
Marking as Stalled. Feel free to reopen it.

**Comment by illi-kun** [comment]
I'd prefer to keep this open.

**Comment by ZhilkinSerg** [comment]
> I'd prefer to keep this open.

Sorry, I've missed that this PR is in Bionic Slots project.

**Comment by vlad1492** [comment]
Discrete power storage bionics - how about bionics have their own basic power supply, but you can occupy slots to get extra power storage.  it would be a considerable sacrifice to give up a slot, so the value of the power storage cbm might need to get boosted.

**Comment by ZhilkinSerg** [comment]
Needs massive conflict resolution.

**Pull request closed without merging**
