### PR TITLE
Bound food health between -1 and 0

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Balance "Bound food health between -1 and 0"

#### Purpose of change

Part of  #37446

#### Describe the solution

- Every positive health is now 0
- Negative health were moved to -1 for heavily processed food and 0 for the rest
- Med and mutagens are untouched
- Some weird foods like putrid hearts are still untouched
- replace some negative health by food poisoning or regular poison

#### Testing

Load game without errors

#### Additional context

Not sure what to do abotu raw potatoes and a few other stuff described as "midly poisonous" but that have no poison effect, just a negative health impact. I'm not usre we have an effect to represent midly poisonous

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Anything mildly poisonous should either be given an effect if it's significant, or left alone if not. Health stat doesn't really model that.

Thanks for doing this! Are you also able to slow down how quickly we update the health stat or is that for another pr

**Comment by Fris0uman** [comment]
This is a pure json change that is already pretty long. I think any alteration to c++ should go into a different PR

**Comment by omni-Var** [comment]
So, for newer players and those still learning -- this is amazing and is probably the right direction ulimately. 

For every veteran that understood the system and used it (and it still took weeks to crank up that health stat, unless you moved Hell for it) this is a big slap in the face. I'm not sure what could be done, other than reintroduce the idea of (fun) active player agency roles in this. 

Simply put: I had a lot more fun farming up tea materials (and seeing the world, exploring for it) than I do making sure I go through quite the (boring) routine every day (sleeping / fitness adherence.) Perhaps, we _do_ need a slight bit of gamification here -- the slightest idea of a player being able to boost their health stat in fun and interesting ways. If you try to tell me the new system is "fun and interesting" you have problems.

**Comment by I-am-Erk** [comment]
We're mostly trying to phase the existing vague and hidden "health" stat into the background, you should be getting a similar fun to that from other systems.

We could certainly use some buffs related to eating fresh food you grew yourself. Health just isn't the greatest spot for it.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/no-positive-health-foods/28249/3

**Pull request merged**
