### PR TITLE
Papaya!

### PR DESCRIPTION
**Pull request by kevingranade**
SUMMARY: None

### CODE REVIEW

**Comment by Inglonias** [comment]
wait what why?

**Comment by Naive8A** [comment]
Papaya!

**Comment by I-am-Erk** [comment]
I'm glad that particular piece of player feedback made it in.

**Comment by TechyBen** [comment]
> I'm glad that particular piece of player feedback made it in.

Meta gaming. Why program something in, when you can life update from the coders themselves. Wait... who needs CDDA to be a PC game, we could tabletop it... might increase the workload of the developers a bit though. ;)

**Pull request merged**
