### PR TITLE
Global getters

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Continuing to address sources of build slowdown as revealed by #41237 
Specifically, over-inclusion of game.h due to g->m, g->u, etc.

#### Describe the solution
Add getters for the various commonly accessed entities and use them.

#### Testing
Fairly straightforward refactor.

#### Additional Information
This depends on #41340 because they would conflict otherwise and I'm lazy.

### CODE REVIEW

**Comment by jbytheway** [comment]
I'm guessing you've only changed the uses of `g->u` etc. that were relevant to the files you wanted changed.

It wouldn't be hard to write a clang-tidy check to automate this refactoring across all uses.  Let me know if that would be useful.

**Comment by kevingranade** [comment]
g->m can definitely be automated, do you think you can automate changing g->u to either get_avatar() or get_player_character()?

I think it's worth doing either way, I just wanted to do a little test run first. I also think it's simple enough to just do a mass find replace, but I'm sure the clang tidy route will be pretty simple too.

A side note, we won't need enforcement since once everything is migrated over m and u and the other affected members will be set to private and the various getters can be made friends of game.

**Comment by jbytheway** [comment]
Yeah, thinking about it, if we don't need ongoing enforcement then it's probably easier to do mass find & replace.  I *could* write something to choose between `get_avatar` and `get_player_character` correctly, but it would be tricky.  Probably easier to find-and-replace with `get_player_character` and then fix the compiler errors.  So, I've convinced myself not to bother.

**Comment by kevingranade** [comment]
Works for me I need some low brain activity busy work to do while I'm
juggling a couple of kids anyway.

**Comment by jbytheway** [comment]
Once you're done with these `g->events()` might be a good target for similar treatment.

**Pull request merged**
