### PR TITLE
Adjust limb encumbrance calculations

### LINKED ISSUE #52109: Torso modifiers for encumbrance shows wrong rolls
### Describe the bug

Modifiers for torso encumbrance shows incorrect rolls on "player info" screen. Only affect on what is worn on the feet.

Снимок экрана (66)

### Steps To Reproduce

1. Equip few bags with stuff
2. Remove encumbrance from feet
3. Behold no modiier rolls on torso encumbrance

### Expected behavior

Why can't you just be normal?

### Screenshots

_No response_

### Versions and configuration

OS: Windows 10
Game version: 2f54703 [64-bit]
Graphics Version: Tiles
Game Language: English/Russian
Mods loaded: None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Bugfixes "Tweak limb encumbrance calculations"

#### Purpose of change

Some limb scores' effect was communicated poorly to the player, especially torso encumbrance which stopped having an effect on melee rolls but still displayed the melee roll modifier in its @ menu entry. 
Fixes #52109, #50915 and #52418

#### Describe the solution

- Added `footing_score`, moved `balance_score`'s effect on movement costs over to it (normal feet have 0.5 each)
- Adjusted the movement cost modifier calculations to take `movement_speed_score` and `footing_score` in a 2:1 proportion into account (was 1:1)
- Added `balance_score` to the torso and arms (0.7 / 0.15 /0.15 respectively) to restore torso encumbrance's effect on melee
- Adjusted melee stamina cost calculations to take arm encumbrance (`lifting_score`) into account instead of only limb HP
- Added `encumbrance_threshold`, a limb field to define at which level of encumbrance do the limb's scores start to decrease and added it to feet, legs, arms, torso and head - with the goal of "casual" wear not having any encumbering effect
- Added `encumbrance_limit`, defining the level of encumbrance where the limb stops contributing its scores *completely* - this is necessary because the normal encumbrance scaling never really reaches 0. Default 100, eyes have 60 turning welding goggles into improptu blindfolds without using the blind flag
- Adjusted the encumbrance displays and messages to be (hopefully) a bit more useful

#### Describe alternatives you've considered

Break it up a bit more, but they're related. 
Audit the encumbrance values of all pieces of gear - there is a lot of weirdness, and I have mutant bits to enlimben. I tried to eyeball a level of `encumbrance_threshold`s where your everyday wear wouldn't have an effect, but there's probably an outlier or three somewhere.
Use `encumbrance_threshold` as a "grace" area, and apply the full scaling apart from it, but that felt a bit too jumpy for my tastes - delaying scaling feels smoother.

#### Testing

The @ menu values change as expected.
`encumbrance_threshold` limits (or raises, for negative values) the effect of gear.
`encumbrance_limit` triggers, has the expected effect.
Torso encumbrance makes you miss, arm encumbrance makes swings more tiring, walk speed is mostly determined by leg encumbrance, with feet playing a smaller role.

#### Additional context

@KorGgenT 

The threshold values for encumbrance are 5 for feet (meaning boots have a minimal effect), arms, legs and torso and 10 for head. I'm open to suggestions on that front, but they feel like the right ballpark.

### CODE REVIEW

**Comment by dseguin** [comment]
Looks like we had similar ideas: #53069
I'll wait until this gets merged to migrate the new score.

**Comment by Terrorforge** [comment]
> I tried to eyeball a level of encumbrance_thresholds where your everyday wear wouldn't have an effect, but there's probably an outlier or three somewhere.

The obvious thing to mention here is that these values leave the heavy survivor suit almost completely unaffected by encumbrance - but I don't expect the fact that the heavy survivor suit is completely busted comes as a shock to anyone.

**Comment by Venera3** [comment]
Yeah, armor encumbrance is all over the place - or rather, armor is universally low-encumbrance, with clothing being annoyingly heavy - *jeans* have a fitted encumbrance of 5-9 depending on their fullness (and four 1L pockets, while we're at it), with fitted plate armor clocking in at *14*. I briefly considered tweaking a bit here and there, but this type of stuff needs a thorough audit by one person who has a clear idea of what they want to reach instead of n+1 people "while I'm here"ing it.

**Comment by Terrorforge** [comment]
Basically every aspect of armor needs a comprehensive audit. Coverage is weird too, layering probably needs a seeing-to, pockets don't make sense, i.e. one of the many weird aspects of survivor suits is that you can somehow stuff 8L of crap into a garment that ostensibly fits underneath a suit of gothic plate. I have a lot of thoughts on that stuff, bur unfortunately I don't have the bandwidth to be the One Person who knuckles down and actually does it.

But I was under the impression that someone was leading the charge to euthanize at least the heavy survivor suit and replace it with something modular. Maybe that was more of an "Eventually(tm)" thing?

**Comment by Inglonias** [comment]
The fact that torso encumbrance didn't affect melee rolls was nice, though I understand that it's a bug that should be fixed. I will still be sad to see it go.

**Comment by Venera3** [comment]
Bumped down the thresholds a bit. "I'm too encumbered by normal clothes, this is bullshit" is a better incentive to start working on something than "neat, I can wear this with no downsides", after all.

**Pull request merged**
