### PR TITLE
[RDY] Changing vehicle jack stats across the board

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Currently we have this issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/17231

Jack stats for lifting vehicles are very strange. For example scissor jack that can be found in most vehicles can't lift them. It is time to change that. And possible solve the issue.

This PR changes that. And not only that:
Changes:
- makeshift jack now jacks 1500 kg (was 500 kg). Now it can lift bikes and  light vehicles and even SUVs but not some of light trucks. It is useful now;
- scissor jack now jacks 2000 kg (was 1000 kg). Now it can actually lift light vehicles, SUV and icecream van;
- bottle jack now jacks 7000 kg (was 3000 kg). Now it can lift  all vehicles excluding crazy deathmobiles;
- telescopic crane now can jack 3500 kg (was 1500 kg). Now it can lift luxary RV and firetruck;
- boom crane now can jack 20 000 kg (was 6000 kg). Now it can lift anything. It is most advanced lifting tool in game after all.

So now we have this:
- makeshift jack : suitable borderline for civillian vehicles, bikes and below;
- scissor jack: suitable for icecream truck, SUV's, light civillian vehicles,  and below. +0.5tons in comparison of makeshift jack that gives room for upgrades;
- telescopic crane: suitable for  heavy civillian vehicles(luxary RV, firetruck) and below;
- bottle jack: suitable for all heavy vehicles but not for crazy deathmobiles;
- boom crane: suitable for  rolling fortresses of doom and below.

Advantages of presented model:
- Covers all vehicles;
- All jacks and cranes now useful for some category of vehicles;
- If you find jack in vehicle cargo then you can use that jack on that vehicle.

### CODE REVIEW

**Comment by jaked122** [comment]
@Firestorm01X2 I like this.

**Comment by Firestorm01X2** [comment]
Ok. I think that from editing point it is ready. We only need additonal sanity checks from other users and approval from developer. Also note, that I user info from https://github.com/CleverRaven/Cataclysm-DDA/issues/17231

Mugling already searchning amazon. So he found that medium lifting weight value for scissor jack is 1500 kg and bottle jack is 5000 kg.

**Comment by Firestorm01X2** [comment]
I am still thinking about increasing lift weight for boom crane. It is most advanced lifting tool after tool.

**Comment by Firestorm01X2** [comment]
Possible I will buff bottle jack. So WIP for now.

**Comment by BorkBorkGoesTheCode** [comment]
Could this type of vehicle be added? https://en.wikipedia.org/wiki/Armoured_recovery_vehicle

**Comment by Firestorm01X2** [comment]
Increased jack quality to 0.5 tons for bottle jack and telescopic crane.
Now it is ready.

**Comment by Firestorm01X2** [comment]
>Could this type of vehicle be added? https://en.wikipedia.org/wiki/Armoured_recovery_vehicle

**Comment by Firestorm01X2** [comment]
Surprisingly armored  flatbed truck, spawned with deug weights slightly more that APC. It is very special flatbed truck for sure.

**Comment by Firestorm01X2** [comment]
telescopic crane jack weight inceased to 0.5t. Not it jacks 3.5 tons, It was too birderline for firetruck

**Comment by Firestorm01X2** [comment]
Last +0.5 tons surprsingly didn't change much in terms or equired jack levels. 
For now everything suits declared logic fine.

**Comment by Firestorm01X2** [comment]
Semi truck weight more than APC. That is strange. Let's rearange something

**Comment by Firestorm01X2** [comment]
I had to set 6 tonts to bottle jack. Semi truck weights more than APC and may containt that bottle jack.

**Comment by Firestorm01X2** [comment]
Ready.

**Comment by Firestorm01X2** [comment]
Take not on:
1) Jacks obviously do not lift all weight of vehicle.
2) Weight of vehicles in cata sometimes very strange.

Current values should be a lot more playable.

**Comment by Firestorm01X2** [comment]
Bottle jack weight was incresed bacause of semi truck.
Boom crane weight was increased actually to uncap it - boom crane mostly for craze vehicles.

**Comment by BorkBorkGoesTheCode** [comment]
Main battle tanks these days weigh about 50-60 tonnes.

It's amazing how survivors are making Landkreuser Rattes without land shipyards.

**Comment by Rivet-the-Zombie** [comment]
>It's amazing how survivors are making Landkreuser Rattes without land shipyards.

Really, it's no bigger than a Maus.

**Comment by Firestorm01X2** [comment]
Is maximum jack level requirement capped with 12?

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/request-to-developers/22170/1

**Pull request merged**
