### PR TITLE
[XEDRA_EVOVLED] add class and energy source to firmament driver 

### LINKED ISSUE #65009: Xedra Evolved - Firmament Driver spell missing class and energy source
### Describe the bug

You can check it in game if you want, but it's easier to just look right in the json. In inventor_spells.json, the entry for Firmament Driver is missing the lines:

"spell_class": "INVENTOR",
 "energy_source": "MANA"

If you learn the spell in-game, you'll see that it's listed as classless, and despite the artifact correctly showing the current and final cost, you can actually cast it for free since there's nothing to tell the game what resource that cost should be paid in.

I might just fix it myself later, since it's an easy one, but I might not. TBH, I kinda just want to play the game.

### Attach save file

N/A

### Steps to reproduce

1. Cheat in a String Theory for Dummies artifact and activate it.
2.  Notice that it incorrectly says that the Firmament Driver spell is "Classless", but that it does correctly list the casting cost.
3. Learn the spell and open the spell menu
4. Notice that it still says classless, but also the casting cost is no longer present.

### Expected behavior

I expect that the spell class should be "Inventor", since that's where the spell is found in the json files. I also expect that the casting cost should be paid in mana, or possibly biotic energy or stamina, but most likely the intended resource is mana.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 1ab1bed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Gigachadicus - Prime Human Overhaul [Gigachadicus],
    No Bionic Slots [no_cbm_slots],
    Resource Crops [resource_crops],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Pneumatic fun [pneumo_fun]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Add missing class and energy source to firmament driver "
Fixes #65009
I also added them to the damage variant, and gave it a mana cost

#### Testing
loaded up the game and its correctly using the class & mana

### CODE REVIEW

**Comment by Devengel** [comment]
Ok wow i'm messy. What i did so far was add damage type, casting time, energy source and class. and nerfed firmament driver by increasing casting time and energy cost.

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
Thanks for fixing this!

**Comment by Devengel** [comment]
i spent 10 minutes trying to figure out why it doesn't show the spell damage, then i used the spell on me, and it turns out it DOES damage, its just hidden for some reason. the code is identical to other damage spells.
image
Also WOW at max level this thing is insane
image

**Comment by Devengel** [comment]
i'm not sure why the damage is so high, The max damage is 11, max level is 20, with a damage increment of 0.5

I'll try to do some balancing.

**Comment by Devengel** [comment]
ah i see, the "extra_effects" code adds the damage from firmament driver damage to the firmament driver spell. i'm not sure if they're supposed to be different. since the description suggests it adds the damage after the push. if i am reading this correctly.

Can i get some insight? @Maleclypse

**Review by GuardianDll — CHANGES_REQUESTED** [review]
First: please, do not make it. I'm on my way to make a huge revamp with a lot of new stuff and mechanic for inventor, and i don't really want to mess up with resolving conflicts again
Second: me who forgot to add `spell_class` and  `energy_source` to spell is in shame, but anything else is not needed here - `damage_type` is `pure` by default (and for `firmament_driver` spell it doesn't even counted, because it's effect is `directed_push`, not `attack`), and second spell is used only as secondary effect, and do not use any of the fields you add

**Pull request closed without merging**
