### PR TITLE
Adds recipes for bike and motorbike alternators.

### PR DESCRIPTION
**Pull request by Tamiore**
#### Summary

`SUMMARY: Content "Adds recipes for bike and motorbike alternators."`

#### Purpose of change

Makes sense in general. If you can craft a motor, why not an alternator? 

#### Describe the solution

Add recipes for alternators. Based on micro and small motor.

#### Describe alternatives you've considered

Doing nothing. 
Adding recipes to craft motors *into* alternators. 

#### Testing

Works fine locally.

### CODE REVIEW

**Comment by Rail-Runner** [comment]
I think you can't really make an alternator as good as a factory-made one that easily.

Not saying you can't make one at all, but a makeshift alternator would have to be much less efficient.

**Comment by Tamiore** [comment]
>I think you can't really make an alternator as good as a factory-made one that easily.

Technically true, but pretty much no other craftable part for vehicles makes this distinction. Specifically, handmade motor are as good as factory made ones. And an alternator is waaaay easier to make than a motor.

Plus, it's not auto-learned. 
And limited for bike and motorbike alternators.

**Comment by kevingranade** [comment]
> Technically true, but pretty much no other craftable part for vehicles makes this distinction.

Only because we have not gotten around to it. Please make a makeshift alternator if you want it to be craftable.

**Comment by Tamiore** [comment]
>Please make a makeshift alternator if you want it to be craftable.

Ok, will do.

However, just to clarify: what's the expected difference between makeshift and normal alternator?
Just lower efficiency, and somewhat larger/heavier?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Please make a makeshift alternator if you want it to be craftable.
> 
> Ok, will do.
> 
> However, just to clarify: what's the expected difference between makeshift and normal alternator?
> Just lower efficiency, and somewhat larger/heavier?

I guess it should be somewhat bulkier.

**Pull request merged**
