### PR TITLE
One napkin per MRE, instead of 8

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
none

#### Purpose of change
It's really cluttered to have 8 napkins in every MRE package. They are not of much use, are annoying to get rid of and may affect performance.

#### Describe the solution
One napkin per MRE is probably sufficient.

#### Testing
Passes basic build and test.

### CODE REVIEW

**Comment by Karol1223** [comment]
> They are not of much use, are annoying to get rid of and may affect performance.

This is not really a concern, save for the last part which is just not true. They USED to affect performance, because they used to track temperature - after my changes they do not.

Annoying to get rid of? You can just burn them. I could understand these if you were talking about something that can't burn but come on, they're painfully easy to get rid of.

**Comment by SurFlurer** [comment]
> If I remember correctly how the code for spawning sealed container works, this might break that as well.

They are not spawned inside a sealed container.

> They USED to affect performance

There are many cases where a sheer amount of items solely can cause performance degradation.

> Annoying to get rid of? You can just burn them.

They are spawned inside nested containers in MRE packages. Collecting them takes a lot of keypresses and/or much time in game.

**Comment by Karol1223** [comment]
> If performance really is the issue

This is a very big "if". I am not aware of any *confirmed* performance regressions by items that aren't active in some form. Napkins shouldn't be.

**Comment by SurFlurer** [comment]
> I am not aware of any confirmed performance regressions by items that aren't active in some form.

I had fixed multiple performance regressions caused by items that aren't active in some form in the past, in case you are not aware of. Walk towards the MRE storage shelves in mil_base and press 'e' to examine one MRE bag. You'll notice the lag. That's from building the crafting inventory.

**Comment by SurFlurer** [comment]
> they function the same way as tinder for firestarting, removing 7 of them takes away multiple uses of them as firestarters.

Firestarting items aren't something rare to find, especially when talking about MRE that usually won't appear alone.

**Comment by kevingranade** [comment]
All this other discussion aside, the question is how many towelettes/napkins does a standard MRE have? 8 seems high.

**Comment by sgteclair** [comment]
> All this other discussion aside, the question is how many towelettes/napkins does a standard MRE have? 8 seems high.

Just opened up a pack and counted, it's about 22-24 incredibly thin sheets packed together.

**Comment by esotericist** [comment]
according to the [defense logistics agency](https://www.dla.mil/Troop-Support/Subsistence/Operational-rations/MRE/) those accessory packets should contain both moist towlettes (sometimes listed as 'hand wipes' sometimes 'hand and body wipes') and toilet paper, not dry napkins. the moist towlettes _appear_ to be a single sealed packet, claiming to be non-alcohol for its treatment.

for the toilet paper, no quantity or other specifications are visible in the pdfs i was able to scour.

no mention of 'napkins', but i'm guessing we probably ended up with napkins as an attempt to best-fit because the distinction between a napkin and toilet paper at that level of material quality/quantity is... hazy.

i did find [an unpacking video](https://youtu.be/SfdM7vbTpok?t=317) that showed the person attempting to partially unfold that pack...
image

shows a tightly packed wad, but she doesn't unfold it all the way. what i see combined with the upstream listing of 'toilet paper' would be compatible with @sgteclair 's assertion of 20+ thin sheets.

accurately representing the precise amount of toilet paper in an mre seems to be well into diminishing returns territory, but i do think we should have *some* representation. if someone for some reason decides to load a bunch of MREs into their vehicle as their primary source of tinder, they clearly should be able to get away with it. i'm not going to argue heavily on how many uses they should use, or the best way to represent that in our system, though. i'll let content people figure that out.

back to the initial topic: if there's a performance concern from these items, it needs instrumentation so we can try to address it, independent of what actually happens with the json. removing/reducing items SOLELY because of performance concerns or annoyance isn't how we do things, though.

**Comment by SurFlurer** [comment]
Fine, I'm closing this :)

**Pull request closed without merging**
