### PR TITLE
Deprecate fictional martial arts.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: Content "Deprecate fictional martial arts"```

#### Purpose of change
Deprecates fictional 5 venoms martial arts by moving them to an isolated file and disabling the mutation that provides access to them.

### CODE REVIEW

**Comment by Photoloss** [comment]
Are the Five Animals Kung Fu styles "real" in having tangible distinct effects in life-or-death combat? [This wikipedia list](https://en.wikipedia.org/wiki/Five_Animals#List_of_animal_styles) suggests there may be non-fictional equivalent animal styles to most of the Deadly Venoms but does not cite any sources. Based on the better referenced [Xinyiquan forms](https://en.wikipedia.org/wiki/Five_Animals#The_12_Animals_of_Xinyiquan) on that page it might be easy to rebrand "Toad Venom" as "Bear Form" for example if historical mythology is permitted.

Since martial arts are JSON-only maybe it would be better to move all fictional or purely sporting/meditational ones to a mod keeping only those employed by actual security/combat forces? (and maybe biojutsu because while fictional it has the same justification in context)

**Comment by kevingranade** [comment]
> if historical mythology is permitted.

There are way too many examples of unquestionably extant martial arts to spend time on apocryphal examples.

> purely sporting/meditational

Removing Boxing, Karate and Taekwondo is a hard sell, I dont think you're going to get any support for that. We don't have any purely meditational arts.

> to a mod

Go ahead, be sure to handle migration properly.

**Comment by Photoloss** [comment]
> Go ahead, be sure to handle migration properly.

Could you link to the appropriate guideline please? To my (limited) understanding the mutation and an "empty" MA definition need to exist for backwards compatibility (in your "obsolete" file) but everything else can essentially be cut-pasted into a mod. Would it be preferable to keep the now-current "obsolete" copy in its entirety so those who do not add the mod are not left with a non-functioning dummy, or should the then-duplicate code be removed as quickly as possible?

> At least several of them are seriously practiced martial arts, if you have doubts about some of them please bring them up.

I don't know anywhere near enough about authentic Chinese practitioners or potential historical precursors. Besides hoping for input from others my main point of reference is the distinction between [Kendo](https://en.wikipedia.org/wiki/Kendo) which is considered a martial art in the modern sense with professional tournament bouts but essentially boils down to "stick tag" similar to olympic fencing, and [Kenjutsu](https://en.wikipedia.org/wiki/Kenjutsu) as the combat-viable art.

Especially Dragon's ability to somehow conjure blunt trauma from intelligence, against zombies and mutated arthropods no less, leads me to believe that while the arts themselves do exist their actual implementation might be based more on mythology or popular culture. This would presumably be addressed in the rebalance PR linked above so if you and the other admins have no pressing concerns regarding the animal styles they can stay.

**Comment by kevingranade** [comment]
> Kendo

That's an odd thing to worry about, since it's not in the game.

> leads me to believe

In other words, you're guessing.  If you care to follow up on this, how about you:
1. Find out how it works instead of speculating.
2. Do some light research on the styles involved.
3. Make specific suggestions about what you think needs improvement.

**Comment by jokermatt999** [comment]
As I recall, KA101 wasn't all that happy with these anyway, and wanted to do a more thorough implementation w/ martial arts masters. But they've been gone a few years now, sadly. Nice contributor; they helped me out a lot with my first PRs.

**Comment by Photoloss** [comment]
> That's an odd thing to worry about, since it's not in the game.

I meant that as an analogy where both arts are quite similar. Olympic fencing vs. HEMA is another one which essentially **is** in the game: the "fencing" MA [explicitly references the sport](https://github.com/kevingranade/Cataclysm-DDA/blob/master/data/json/martialarts.json#L488) but its actual implementation makes far more sense as a combination of historical rapier and military sabre systems. 

> Make specific suggestions about what you think needs improvement.

I listed one already: how does Dragon Kung Fu derive blunt damage from intelligence? Including its effectiveness against animals, zombies and mutant beasts and without any study of their anatomy. Some of the other damage stats don't *always* make sense either: perception or dexterity might allow you to capitalise on enemy mistakes or strike a weak point but won't really do anything to harm blob monsters (plus since enemies don't have coverage issues the current resilience of skeletons implies their armour has no sufficiently weak spots, if you can strike with a hand or foot you can put a bullet through it)

**Pull request merged**
