### PR TITLE
 Consume tool charges incrementally during crafting 

### LINKED ISSUE #7126: Crafting checks for nearby fire at the start and at the end
I start a fire. This is enough to start and finish crafting, even if the fire goes off halfway through. So I can cook normally.

However, if I have an integrated toolset, I will lose some power at the end if the fire is no longer there. If I have no power left, I will still be able to finish crafting normally without it. If there is any other substitutes for a fire in a recipe, they will also be used. With a prompt if you have multiple options.

I propose to remove the end-check for fire to prevent unnecessary power/charges loss. Removing starting check instead is a bad option currently, I'd say, since this creates strong possibility of not being able to finish crafting when you already spent your time doing it.

If fire was more predictable (had countable duration), this could be used to determine if it will last enough for your crafting purposes, so that recipes can be made to require more or less fire and not just the fact that the fire exists at this particular moment. Don't know how to go about the weather, though.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1559916-crafting-checks-for-nearby-fire-at-the-start-and-at-the-end?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #24230: Some recipes require more than the maximum amount of charges from soldering iron
Game version: 0.C-28870-g2ccd3b8

Some recipes, like [charcoal kiln](http://cdda-trunk.chezzo.com/char_kiln/craft) or [electric forge](http://cdda-trunk.chezzo.com/forge/craft) require more than 200 charges if made by soldering iron. The issue is that soldering iron can only hold 200 charges. That can be changed by using e.g. extra battery mod, so it's not *impossible* to craft such recipes using soldering iron, just fairly hard. Is this intentional?

Especially consider that in the real world, it would be possible to put new set of batteries into a tool in the middle of crafting, so how many charges it can hold probably shouldn't make a big difference.

Maybe when crafting, tools should be able to use nearby charges after charges in the tool are exhausted?

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
SUMMARY: Bugfixes "Consume tool charges incrementally during crafting."

#### Purpose of change
Fixes #7126
Fixes #24230
Progress towards #29210 (getting very close to drastic craft time extension being feasible)

#### Describe the solution
Tool charges are now consumed before every 5% crafting progress,
with the remainder consumed at the start of the craft.

#### Describe alternatives you've considered
Rewriting a large portion of this code to make things cleaner.  The way this is currently implemented feels more than a little hacky, but should work without issues.

#### Additional context
This may fix other old issues that I'm not aware of.  If you know of any please add a comment so we can close them with this PR as well.

### CODE REVIEW

**Comment by ifreund** [comment]
Conflicts resolved

**Comment by jbytheway** [comment]
I've seen a test failure that looks related to this
```

cata_test: src/ui.cpp:112: void uilist::init(): Assertion `!test_mode' failed.
Stack trace at fatal error:

        /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/libasan.so.4(+0x55630) [0x7f7cdf359630]
        tests/cata_test(_Z21debug_write_backtraceRSo+0x34b) [0x560f3866f496]
        tests/cata_test(_ZN12CataListener14assertionEndedERKN5Catch14AssertionStatsE+0x74) [0x560f37f49572]
        tests/cata_test(_ZN5Catch17ListeningReporter14assertionEndedERKNS_14AssertionStatsE+0x2c7) [0x560f37e94adf]
        tests/cata_test(_ZN5Catch10RunContext14assertionEndedERKNS_15AssertionResultE+0x179) [0x560f37f07e23]
        tests/cata_test(_ZN5Catch10RunContext25handleFatalErrorConditionENS_9StringRefE+0x4b7) [0x560f37f08957]
        tests/cata_test(+0x101b8a4) [0x560f37ea18a4]
        tests/cata_test(_ZN5Catch21FatalConditionHandler12handleSignalEi+0x77) [0x560f37ea1a09]
        /lib64/libc.so.6(+0x35fc0) [0x7f7cde219fc0]
        /lib64/libc.so.6(gsignal+0x110) [0x7f7cde219f00]
        /lib64/libc.so.6(abort+0x1c7) [0x7f7cde21ba57]
        /lib64/libc.so.6(+0x2d85a) [0x7f7cde21185a]
        /lib64/libc.so.6(+0x2d8e2) [0x7f7cde2118e2]
        tests/cata_test(_ZN6uilist4initEv+0x28b) [0x560f3b1a70f5]
        tests/cata_test(_ZN6uilistC1Ev+0x99e) [0x560f3b1a8ece]
        tests/cata_test(_ZN6player21select_item_componentERKSt6vectorI9item_compSaIS1_EEiR9inventorybRKSt8functionIFbRK4itemEEb+0x1c09) [0x560f38558309]
        tests/cata_test(_ZN13craft_command7executeERK8tripoint+0x1e10) [0x560f3ba7d696]
        tests/cata_test(_ZN6player23make_craft_with_commandERK9string_idI6recipeEibRK8tripoint+0xd68) [0x560f38516f58]
        tests/cata_test(_ZN6player10make_craftERK9string_idI6recipeEiRK8tripoint+0x11) [0x560f38516fd9]
        tests/cata_test(+0x8f9f5a) [0x560f3777ff5a]

        Attempting to repeat stack trace using debug symbols...
        ??
        ??:0
        debug_write_backtrace(std::ostream&)
        .../src/debug.cpp:620
        CataListener::assertionEnded(Catch::AssertionStats const&)
        .../tests/test_main.cpp:244
        __gnu_cxx::__normal_iterator<std::unique_ptr<Catch::IStreamingReporter, std::default_delete<Catch::IStreamingReporter> >*, std::vector<std::unique_ptr<Catch::IStreamingReporter, std::default_delete<Catch::IStreamingReporter> >, std::allocator<std::unique_ptr<Catch::IStreamingReporter, std::default_delete<Catch::IStreamingReporter> > > > >::operator++()
        /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include/g++-v7.3.1/bits/stl_iterator.h:805
        Catch::ListeningReporter::assertionEnded(Catch::AssertionStats const&)
        .../tests/catch/catch.hpp:16101
        Catch::RunContext::assertionEnded(Catch::AssertionResult const&)
        .../tests/catch/catch.hpp:12099
        Catch::RunContext::handleFatalErrorCondition(Catch::StringRef)
        .../tests/catch/catch.hpp:12224
        (anonymous namespace)::reportFatal(char const*)
        .../tests/catch/catch.hpp:10302
        Catch::FatalConditionHandler::handleSignal(int)
        .../tests/catch/catch.hpp:10397
        killpg
        ??:?
        gsignal
        ??:?
        abort
        ??:?
        uselocale
        ??:?
        __assert_fail
        ??:?
        uilist::init()
        .../src/ui.cpp:113
        uilist::uilist()
        .../src/ui.cpp:33
        player::select_item_component(std::vector<item_comp, std::allocator<item_comp> > const&, int, inventory&, bool, std::function<bool (item const&)> const&, bool)
        .../src/crafting.cpp:1373
        craft_command::execute(tripoint const&)
        .../src/craft_command.cpp:149
        player::make_craft_with_command(string_id<recipe> const&, int, bool, tripoint const&)
        .../src/crafting.cpp:564
        player::make_craft(string_id<recipe> const&, int, tripoint const&)
        .../src/crafting.cpp:547
        actually_test_craft(string_id<recipe> const&, std::vector<item, std::allocator<item> > const&, int)
        .../tests/crafting_test.cpp:314

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v2.9.1 host application.
Run with -? for options

Randomness seeded to: 1561885818

-------------------------------------------------------------------------------
charge_handling
  carver
-------------------------------------------------------------------------------
crafting_test.cpp:330
...............................................................................

crafting_test.cpp:311: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

0.000 s: charge_handling
```

Something is causing a UI popup which isn't permitted in the tests because there's no one to respond to it.

**Comment by ifreund** [comment]
Certainly seems like it must be related, but I haven't been able to reproduce the failure locally.  Does it happen every time for you or is it intermittent?

**Comment by jbytheway** [comment]
Only seen it once so far (out of maybe three test runs).

**Pull request merged**
