### PR TITLE
bullet pulling as quality

### PR DESCRIPTION
**Pull request by kettleswordfang**
+ added bullet pulling tool quality ("PULL")
+ added new new quality flag to existing tool ("PULLER", kinetic bullet puller)
+ altered all ammo uncraft recipes to use "qualities" flag in place of "tools" flag

### CODE REVIEW

**Comment by AMurkin** [comment]
Great, but no new line at the end of `data/json/tool_qualities.json` and TAB in the `data/json/items/tools.json`.

**Comment by Night-Pryanik** [comment]
Is there any examples of different bullet pulling qualities IRL?

**Comment by kevingranade** [comment]
There are probably different levels of tools, but I don't think we have a
need for them at the moment.

**Comment by kettleswordfang** [comment]
DAMN, i can't believe i missed that.
both formatting issues now resolved.

**Pull request merged**
