### PR TITLE
Repair and balance adjustment of recipes

### LINKED ISSUE #51174: Yeast culture transforms container
### Describe the bug

sealed yeast culture requires 1 glass jar to craft, opening the product after the incubation time expires will yield a glass flask of yeast, not a glass jar of yeast

### Steps To Reproduce

1. craft a sealed yeast culture
2. wait for it to ferment
3. (a)ctivate the product
4.  glass flask of yeast appears

### Expected behavior

step 4 should be "glass jar of yeast appear"

### Screenshots

_No response_

### Versions and configuration

Windows 10 tiles version 7495101 

### Additional context

_No response_

### LINKED ISSUE #51440: Fermenting sauerkraut has different weight, volume, and length than a sealed jar
### Describe the bug

Fermenting sauerkraut has different weight, volume, and length than a sealed jar of the sauerkraut 

### Steps To Reproduce

Seal a jar, and see it lose half its weight, but extend in length and volume. Be amazed that a glass jar can grow so much.

### Expected behavior

I expect that the dimensions at least would remain consistent. I could see weight being dependent upon the food used to make the sauerkraut, but the dimensions? No.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kwl01skz**
#### Summary
Balance "Repair and balance adjustment of recipes"

#### Purpose of change
Check the existing recipes and adjust the omissions and unreasonable contents.

- fixed #51440
- fixed #51174 ( Only deleted containers that shouldn't appear because it was an obvious mistake. If someone want to implement the idea of supporting diffrent containers, we need more C++ code. )
- Corrected egg recipes.
- Corrected toast recipes.
- Corrected cooked/raw meat in components list.
- Corrected vegetable.
- Corrected container.
- Corrected explosive because the container has changed.
- Corrected sugars.
- Added missing recipes mentioned #52166  

#### Describe the solution

I have removed something like bologna and smoked_meat from meat nofish components list.
In the existing recipe:
They are cooked meat, smoked or pickled, but they are added to the components list of raw meat.
So they may be poured into the sausage and smoked again.

I added a rehydrated egg recipe, which can replace scattered eggs in cooking, but can not replace complete eggs.
In this way, you can delete some duplicate recipes, which only change the eggs to egg_powder + water.

I fixed the recipes related to toast so that they can use more kinds of bread and eggs.
In addition, like toast with jam, toast should be used instead of untreated bread.

I added the components list of cracklins. Cracklins includes animal meat, human meat, Demihuman meat and other possibilities, but in the current version, we can only use animal meat.

I corrected almost all the vegetables that can be smoked to make their volume and weight more reasonable.

The volume of some containers has been modified, which is related to the material of this container.
I corrected the volume of many explosives so that they would not be smaller than their materials.
I adjusted my diet to prohibit the use of pottery in "gas bombs that can recycle empty cans" to prevent pottery from turning into metal.

I corrected sugar and honey to make them appear in proportion in the recipe.

The necessary adjustments are listed in the table in the response area.

##### ~~Still in progress:~~

No one discussed it with me, so I did it according to my own ideas.

~~The volume of some vegetables needs to be modified. They are unreasonable.  But I don't know the granularity of these foods in the game, and I don't know where to find references.~~

~~I don't quite understand this components list. This no fish components list actually includes fish liver and fish scrap,  Rehydrated meat is a kind of cooked meat. They are put in a components list of raw meat. Similarly, canned chicken and canned lunchmeat.  I think it is reasonable for us to cook it as raw meat.   Should they be removed from the components list?~~

https://github.com/CleverRaven/Cataclysm-DDA/blob/178348022b69b7c7f9eef8dce645512b9b1d86c4/data/json/requirements/cooking_components.json#L309-L321

#### Testing
Enter the game, 
check recipes,
make food, 
they meet expectations

#### Additional context

  | volume（L） | weight(Kg)
-- | -- | --
Cabbage | 0.14 | 0.25
Lettuce | 0.25 | 0.04
wild vegetable | 0.25 | 0.12
cucumber | 0.75 | 0.33
dehydrated vegetable | 0.12 | 0.06

When we air dry most of the moisture in the vegetables:
The volume and weight of wild vegetables were reduced by 1 / 2,
Cucumber is reduced by 4 / 5,
The weight of cabbage has been reduced by 3 / 4, but its volume has not decreased accordingly.
It is puzzling that lettuce has gained weight.

### CODE REVIEW

**Comment by kwl01skz** [comment]
My network is really frustrating. I tried to submit it as a draft, but failed.
Do I need to resubmit?

**Comment by kwl01skz** [comment]
My network is really frustrating. I tried to submit it as a draft, but failed.
Do I need to resubmit?

**Comment by RenechCDDA** [comment]
> My network is really frustrating. I tried to submit it as a draft, but failed.
> Do I need to resubmit?

It looks like it's draft over here, so you should be fine! It's also possible to toggle draft on/off without opening a new PR, so you should be 100% good to go regardless.

**Comment by kwl01skz** [comment]
The volume of ordinary glass cans should be 0.68L, and this number should also be used for fermented foods in jar. Those two 0.5L need to be modified again.
The weight of rehydrated eggs should be adjusted.

**Comment by kwl01skz** [comment]
Removed the optional glass bottle from the recipe for acid bomb.
Removed the optional glass flask from the recipe for sealed yeast.
Because they can cause unpredictable product volume.

**Comment by kwl01skz** [comment]
Our JSON content is difficult to understand

Calories are neither calories per 100g nor the actual calories of this food. I don't know what it is. Fortunately, it has a proportion so that I can calculate it. I get these data from different websites. Please let me know if there are any errors. myfitnesspal.com
boohee.com

Volume is the total volume of all props stacked

Weight is the weight of each item

Many editors do not understand this, resulting in the abnormally small volume of carrots and the abnormally large volume of celery.







  | volume（mL） | weight(g) | charges stack | V/W | calories 100g | calories | content in JSON
-- | -- | -- | -- | -- | -- | -- | --
dehydrated vegetable | 125 | 60 | 1 | 2.08 | - | - | -
dry_veggy | 250 | 119 | 1 | 2.10 | - | - | -
plant_sac | 250 | 278 | 1 | 0.90 | - | - | -
veggy | 250 | 119 | 1 | 2.10 | - | - | -
broccoli | 180 | 96 | 1 | 1.88 | 27 | 26 | 33
Cabbage | 1250 | 82 | 8 | 1.91 | 23 | 19 | 24
spinach | 2250 | 139 | 9 | 1.80 | 24 | 33 | 43
carrot | 770 | 72 | 6 | 1.78 | 32 | 23 | 30
celery | 190 | 107 | 1 | 1.78 | 13 | 14 | 18
cucumber | 320 | 185 | 1 | 1.73 | 16 | 30 | 38
Lettuce | 850 | 90 | 5 | 1.89 | 12 | 11 | 14
onion | 250 | 150 | 1 | 1.67 | 39 | 59 | 75
potato | 375 | 210 | 1 | 1.79 | 81 | 170 | 219
pumpkin | 3000 | 123 | 12 | 2.03 | 21 | 26 | 33
horseradish_greens | 140 | 70 | 1 | 2.00 |   | 0 | 0
raw_dandelion | 430 | 68 | 4 | 1.58 | 45 | 31 | 39
burdock | 470 | 72 | 4 | 1.63 | 72 | 52 | 67
rhubarb | 250 | 129 | 1 | 1.94 | 21 | 27 | 35
sugar_beet | 1000 | 143 | 4 | 1.75 | 43 | 61 | 79
tomato | 375 | 231 | 1 | 1.62 | 15 | 35 | 45
zucchini | 395 | 210 | 1 | 1.88 | 19 | 40 | 51
bell_pepper | 250 | 113 | 1 | 2.21 | 31 | 35 | 45

**Comment by kwl01skz** [comment]
Let the volume of some containers be slightly larger than it can hold, rather than equal.
The volume of some containers has been modified, which is related to the material of this container.


  | proportion | capacity | volume
-- | -- | -- | --
Plastic | 0.05 | 1.5 | 1.575
Glass | 0.27 | 3 | 3.81
ceramics | 0.18 | 0.25 | 0.295
Metal | 0.05 | 0.5 | 0.525

**Comment by kwl01skz** [comment]
The recipes related to sugar and honey have been modified, and now they appear in proportion in the recipes.


honeycomb 1

honey_glassed 2
molasses 2

honey_bottled 6
honeydew 6

syrup 8

beet_syrup 10

sugar 20 
artificial_sweetener 20

**Comment by kwl01skz** [comment]
Is there anything wrong with ice cream?  I did not change the calories of ice cream, sugar, milk.

**Comment by kwl01skz** [comment]
I modified the formula of peanut butter, which indirectly affected the nutritional composition of ice cream, resulting in the failure of hard coding test, so I need to update it.

**Pull request merged**
