### PR TITLE
Offal recipes for new offal types

### PR DESCRIPTION
**Pull request by KorGgenT**
`SUMMARY: Content "add new offal recipes in the game using the new offal types`"

#### Summary

adds a few recipes for each piece of offal, including "cooked" variant [done]
Also, adds offal as ingredients to existing offal recipes [done]
Adjust fat to be more correct calorie-wise [done]
#### Purpose of change

I recently had a pull request merged #26811 that added new offal types, and the ability to add them to the harvest code. This is another step toward making these offal types a reality.
I have done a bit of research on various recipes, and toned / am working on toning down the ingredients so survivors can cook meals for one reasonably.

### CODE REVIEW

**Comment by Mecares** [comment]
Hi you might want to use "looks like" for those new items.

**Comment by ZhilkinSerg** [comment]
You are missing category in summary line.

**Comment by ZhilkinSerg** [comment]
New json files should be linted (you can use [web-linter](http://dev.narc.ro/cataclysm/format.html) for that).

For example:

image

image

**Comment by AskaHope** [comment]
ADD ZOMBIE BRAINS, PLEASE!!!

**Comment by KorGgenT** [comment]
> ADD ZOMBIE BRAINS, PLEASE!!!

what would the purpose of them be? a tainted version of offal didn't exist in the first place, so i imagined they sort of turned into unusable slop.
a purpose would be pretty important to me

**Comment by KorGgenT** [comment]
All right, I am happy with the content of this PR where it sits now. I would still welcome comments.

**Comment by kwl01skz** [comment]
> > ADD ZOMBIE BRAINS, PLEASE!!!
> 
> what would the purpose of them be? a tainted version of offal didn't exist in the first place, so i imagined they sort of turned into unusable slop.
> a purpose would be pretty important to me

When we lose some games, 
> The zombies ate your brains!
Just now,
> You ate the zombis‘ brains!
Maybe this will make us win.

**Comment by gc2020x4** [comment]
@kevingranade @KorGgenT 
Kevin Grenade must leave the project forever.

**Pull request merged**
