### PR TITLE
V-menu while peeking.

### PR DESCRIPTION
**Pull request by OzoneH3**
Feature request: #5820

### CODE REVIEW

**Comment by DanmakuDan** [comment]
The peek menu appears to reset to the player/peek origin's location after exiting the V menu, but will snap back to the current peek coordinates after you move the cursor again. Also, is it supposed to be possible to switch between V menu/peek infinitely? 

Also, the horizontal bar in the middle of the V menu doesn't get redrawn when leaving the embedded peek mode ("grass; Movement cost 100" remains until a redraw), but that might have been there before this update.

**Comment by KA101** [comment]
Yeah, the UI isn't perfect but Ozone (or anyone else) can tweak that later.  It's currently escapable with a few uses of Esc so not a dealbreaker IMO.

**Comment by OzoneH3** [comment]
@DanmakuDan What do you mean by swapping infinitely? I don't see a key int the v keybindings to go to the peek menu from the v.

**Comment by OzoneH3** [comment]
Nevermind, it's in monsters tab not items, derp.

**Pull request merged**
