### PR TITLE
Enable "self-assigned" missions (no quest giver) and fix "goto" missions

### PR DESCRIPTION
**Pull request by codemime**
Tested with #19688.

This is a bit more generic solution than #19690 (no specific missions were mentioned), and fixes the real cause of the issue: terrains should be compared using their types, rather than ids.

Small enhancement: added messages on mission completion/failure.

### CODE REVIEW

**Comment by patternoia** [comment]
Your Fix-Fu is better than mine.

**Comment by patternoia** [comment]
I'll check it now

**Comment by patternoia** [comment]
This only finishes the Reach Refugee Center mission and not the others (FEMA, Farm, Sarcophagus).

**Comment by codemime** [comment]
Thanks for testing. I guess I know the reason.

**Comment by codemime** [comment]
Fixed.

**Comment by patternoia** [comment]
Still doesn't do. I think it is in `void mission::process()`.

**Comment by patternoia** [comment]
I have non-negative npc_id for Sarcophagus mission. (2, since it was given by an npc and not self-assigned). This makes the check on target terrain arrival never happen.

**Comment by patternoia** [comment]
So it really works only for self assigned missions

**Comment by codemime** [comment]
Now I know why it still doesn't work for you: you probably forgot to take the quest givers with you.
In order to complete those missions you should lead them to the destinations (level -2 in case of the sarcophagus) and talk to them there.

**Comment by patternoia** [comment]
Is this true for all goto missions?

**Comment by patternoia** [comment]
I cant recall one needs to escort someone to farm or fema

**Comment by codemime** [comment]
> Is this true for all goto missions?

Yes, except one (I mean your new mission).

> I cant recall one needs to escort someone to farm or fema

Read the dialogs.

**Comment by patternoia** [comment]
Then maybe split and generalize them to `goto` and `escort to`?

**Comment by codemime** [comment]
I thought about it too, but not in this PR. I'd prefer it to be lightweight: essentially, only fixes and tiny refactorings.

**Comment by patternoia** [comment]
Okay, seems to work when chatting with escorted npc.

**Pull request merged**
