### PR TITLE
Autopickup can be configured to use a max quantity

### LINKED ISSUE #54879: Auto pickup max quantity
### Is your feature request related to a problem? Please describe.

I don't like that I have to manually sort through content after auto picking it up and removing excess items.

### Solution you would like.

Auto pickup should have a configuration value for each item entry that determines the maximum count an item in inventory is allowed to have before auto pickup stops working for that item. The feature should become suspended for that item until the item count drops below the max quantity value specified by entry configuration value.

For example let's say the player wants to go scavenging and is interested in finding and looting 5 units of water. He starts his journey with 2 units of water so with this feature implemented he would create a new auto pickup entry for water and configure it to only allow up to 7 units of water. During his scavenging trip he would pick up (either manually or via auto pickup) additional 5 units of water after which the auto pickup entry for water would no longer work until there is less then 7 units of water present in his inventory. He would return to his base, unload the water and either disable or remove the entry from auto pickup manager.

### Describe alternatives you have considered.

I have considered manually sifting through auto picked content to remove excess item count but I quickly concluded that having this automated in a configurable way is a much better idea.

### Additional context

_No additional context available._

### PR DESCRIPTION
**Pull request by juliavetter**
#### Summary
Features "Autopickup can be configured to use a max quantity"

#### Purpose of change

Fixes #54879. It seems like this feature has been desired for a long time, looking at the linked forum thread in the issue. 

#### Describe the solution

In the autopickup interface, there is an additional column "max", where the player can specify the maximum amount of an item they would like to have in their inventory. Setting the "max" field to 0 will result in this feature being disabled for that specific rule.

Underlying logic:
For each item that is processed by the autopickup manager:
- If the item fulfills an enabled rule that has a max of 0, it is picked up.
- For each rule, such that this item fulfills that rule, such that the number of items in the character's inventory that fulfill that rule does _not_ exceed the max for that rule, only so many items, including items measured by charges (e.g. charcoal) will be picked up until the max has been reached or there are no items remaining on the ground.
- Otherwise the item is not picked up. 

Todo list:
- [x] Support legacy `auto_pickup.json` files
- [ ] Actually make the feature work
- [ ] Write tests

#### Describe alternatives you've considered

None

#### Testing

TODO

#### Additional context

Screenshot_2022-01-29_02-00-29

### CODE REVIEW

**Comment by kurtisvetter** [comment]
Thanks to @KorGgenT for helping out on the discord. @matshou if your PR #54408 is just about ready to be merged, I'll wait for that before I continue on this. 

This works now in a very few specific cases, due to the autopickup functionality first marking the items for pickup, then picking them up (without updating the player inventory in between). So it only works when 1: the player has greater than or equal to the max specified items for a rule already in their inventory, no items fulfilling that rule will be picked up. 2: when the player moves over a _single_ item that is measured by charges, only the amount of charges up until the max for that rule will be picked up.

**Comment by matshou** [comment]
The mentioned PR is waiting to be merged.

**Comment by Maleclypse** [comment]
> Thanks to @KorGgenT for helping out on the discord. @matshou if your PR #54408 is just about ready to be merged, I'll wait for that before I continue on this.
> 
> This works now in a very few specific cases, due to the autopickup functionality first marking the items for pickup, then picking them up (without updating the player inventory in between). So it only works when 1: the player has greater than or equal to the max specified items for a rule already in their inventory, no items fulfilling that rule will be picked up. 2: when the player moves over a _single_ item that is measured by charges, only the amount of charges up until the max for that rule will be picked up.

The PR mentioned above has been merged.

**Comment by I-am-Erk** [comment]
We definitely still want this feature. I am closing this as @kurtisvetter doesn't seem to be around right now, but feel free to ask me to reopen if you want to complete it. I have also bookmarked in our project list of "PRs to not lose".

**Pull request closed without merging**
