### PR TITLE
Add spell flag to suppress AoE explosion visuals

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary

None

#### Purpose of change

By default, all AoE spells draw an explosion effect, which can be pretty jarring for critter attacks using spells without being necessarily explody.

#### Describe the solution

Added a new spell flag `NO_VISUAL`, suppressing the drawing of the AoE. The target(s) still get painted with an explosion sprite, but I find that to be nice for readability. Added the flag to the summon spell of the frog mother, centipede matriarch and the dermatik incubators.

#### Describe alternatives you've considered

Do something properly fancy with explosions being drawn with JSON-defined field sprites, but that's way beyond my abilities.
Add the flag to the pupating zombies, but since they actually die of a single cast it seems violent enough to warrant an explosion.

#### Testing

Got exploded at by a frog mother summoning her young, applied the changes, only the frog mother blinked briefly.

#### Additional context

If desired I can also go over the Magiclysm spells and add the flag to where it makes sense, but I don't personally play with it so I don't know if there are any problematic ones.

### CODE REVIEW

**Comment by actual-nh** [comment]
I personally find `NO_VISUAL` a bit vague - no visual of what? Possibly `NO_VISUAL_AOE`? `NOT_EXPLOSION`?

**Comment by Night-Pryanik** [comment]
Maybe `INVISIBLE` flag, like in #44739?

**Comment by Venera3** [comment]
`NO_VISUAL_AOE` works better, I'll update later today.
`INVISIBLE` sounds like proper magic stuff, if that makes sense, and I like flag names that are intuitive enough to understand even without reading the docs. `NO_EXPLOSION` has the same problem, implying it changes something about the spell's behavior.

**Comment by KorGgenT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/44739#issuecomment-705974660

and an addendum: this would be a band-aid fix that masks a better fix

**Comment by actual-nh** [comment]
> [#44739 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/44739#issuecomment-705974660)
> 
> and an addendum: this would be a band-aid fix that masks a better fix

I am guessing a better fix would be enabling each spell to specify tiles used for it? There would still need to be a default (which could be altered by this flag) and/or a script adding this information to each spell (which could look for this flag to help indicate what to put in).

**Comment by Venera3** [comment]
> Is this obsoleted by #47277?

Not completely. That one hooks up spells to tilesets, but there should be a way for fallback/looks-like tiles to be defined in the spell definition itself - so that you don't have to wait for tilesets to "catch up" (but still leave them to be able to do a custom tile, should they want to).

**Comment by Night-Pryanik** [comment]
Ok, then maybe resolve conflicts?

**Comment by Venera3** [comment]
Deconflicted, tested again to be sure it still works. I'd like a nicer solution, where the flag only activates if the explosion would use the default explosion sprite (in case a tileset artist comes up with a suitable tile for a spell with the flag) - but that goes on the large pile of nice things I'm not competent enough for.

**Comment by jbytheway** [comment]
> I am guessing a better fix would be enabling each spell to specify tiles used for it? There would still need to be a default (which could be altered by this flag) and/or a script adding this information to each spell (which could look for this flag to help indicate what to put in).

Although there would have to be some default, we should also have `looks_like` support so the default would probably rarely be relevant, even for newly added spells with no tiles yet, so long as some other spell can reasonably be listed as its `looks_like`.

**Comment by KorGgenT** [comment]
After a lot of consideration, i think i am going to close this pr for now. I don't feel like this approach is exactly the thing we want, though it might be pretty close. That being said, this would paper over these issues which is not ideal. Since tilesets can draw the spell explosion now, that is part of the solution, while another part of the solution is adding looks_like to spells (which should be fairly easy)

**Pull request closed without merging**
