### PR TITLE
Kill off ammo vending machines

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
"Ammo vending machines"

#### Describe the solution
Remove.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
It seems this just removes the ability to get (some of the?) ammo from gun stores, without spawning replacement ammo elsewhere?

I'm fine with the removal of the machines, but the ammo ought to be spawned by other means.

If it's considered too much work to locate all the places where these machines were placed and distribute ammo in them, I'd rather use a cheap replacement of providing some, preferably locked, furniture with ammo in it in the palette.

**Comment by harakka** [comment]
Afaik this is happening as part of investigating where and how much ammo currently spawns and fixing it to match reality. The goal isn't to preserve the current numbers.

**Comment by PatrikLundell** [comment]
If that's a thought out move, then that's fine. It looked like an extension of the vending machine transformation to me, though, which is why I voiced my concern.

**Comment by kevingranade** [comment]
A cursory glance at the item group shows that it's only spawning ammo that spans in extremely large quantities elsewhere, so there's certainly no risk of this change making anything unavailable.

If you're talking about absolute quantities of ammo spawned,  as harakka says that's currently in a state of total nonsense and this is part of an effort to fix it.

This actually predates the recent look at vending machine stuff and i just had it sitting on a local branch for months.

**Comment by Rasengetsu** [comment]
As mentioned by Patrik, this actually did remove all ammo from the gunstore variant that used ammo vending machines since all the spawns ammo spawns of this variant were tied to the vending machines.
I would recommend adding safes that follow the same spawn rules as the other unlooted gunstore variants as it makes no sense to have an unlooted gunstore with many guns and a large amount of magazines but no bullets for them. Anyone who would loot the ammo would also take the magazines.

**Comment by Fris0uman** [comment]
You should open an issue about if it's not done already. Closed PR are not the correct place to track bugs

**Pull request merged**
