### PR TITLE
Human Skull

### PR DESCRIPTION
**Pull request by faefux**
#### Summary
Content "Human Skulls"

#### Purpose of change

xrogaan on IRC suggested having a human skull item as it is skulls and skull imagery are a common cultural image that turn up everywhere.  Aside this it would be great for animals to drop skulls and other things too in my opinion.  I was also going to add the femur as they are the largest bones in the body and would make a good bashing item in a pinch but I thought i'd float the skulls first along with the larger idea RE bones.
#### Describe the solution

Added a new `skull_human` item,

#### Describe alternatives you've considered

Doing a PR of just 'Skulls' and adding a skull bone for all the animals (broadly speaking, so for example: `skull_bird` rather than `skull_raven` and such in some places.) and for tainted skulls.  I did not do this because I thought it would be better to float the idea first in case of rejection.

#### Testing

Spawned an NPC. Killed them ded. Butchered.  One Skull.

#### Additional context

image

### CODE REVIEW

**Comment by Shodan14** [comment]
Can't wait to decorate my armor with cat skulls.

**Comment by PatrikLundell** [comment]
Skulls probably won't have an effect on the harvest of bones, but if femurs are introduced they should deduct from the generic bones harvest and should also be usable as either a source for production of generic bones, or as a replacement for bones in recipes.
You may want to consider whether skulls should be possible to convert into generic bones, though, in which case it should affect the generic bones amount harvested.

**Comment by leemuar** [comment]
You monster! (pull request on this when?)

> 
> 
> Can't wait to decorate my armor with cat skulls.

**Comment by faefux** [comment]
> Skulls probably won't have an effect on the harvest of bones, but if femurs are introduced they should deduct from the generic bones harvest and should also be usable as either a source for production of generic bones, or as a replacement for bones in recipes. You may want to consider whether skulls should be possible to convert into generic bones, though, in which case it should affect the generic bones amount harvested.

@PatrikLundell Yea, that's the thing i've come up with some far. I'm not sure how many of the generic bones item i'd have to take out, I think you are right that if we go through recipes using bone some might be only realistic with a femur as it is imagine the bone that allows for the most utility.  
I had an idea maybe of with the rest of the bones we could split them into `bones` and `small bones` items. Bones will by for most recipes we currently have and small bones will be for other things like broths and glues. I'd appreciate your feed back on this idea and any other input you have RE bones. 
Kind Regards. :)

**Pull request merged**
