### PR TITLE
Cold blood reduce water requirement, higher end strength mutations block higher end dexterity mutations

### PR DESCRIPTION
**Pull request by dissociativity**
```SUMMARY: Balance "Rebalance Cold blooded and strength increasing mutations'"```

#### Purpose of change
Strength is currently very powerful, strength mutations and trees based on them allow the player to become far more powerful than any other stat boosts would give them.

Some negative mutations such as cold blooded deserve more nuance as well.

#### Describe the solution
I've added some thirst reduction to the cold blood related mutations.
I've also made it so higher end strength increase mutations cancel out higher end dexterity mutations.

#### Describe alternatives you've considered
Totally re-balance stats, make any strength increase beyond say +1 at chargen to cost 2 points as it is currently the most powerful stat.

Make dex and strenth work in a ratio, if the player has too low dex vs str, there is a penalty with the ability for the player to coordinate with their large, buff body, at least more-so than currently.

Alternatively increase negatives for dex, perception and intelligence below 8.

#### Additional context
I'd just like to flesh out mutations a bit more, have realistic negatives with some positive mutations and realistic positives with negative ones, I plan to do more of these styles of things.

### CODE REVIEW

**Comment by KITbutler** [comment]
What is your reasoning for encumbering the hands specifically on "Extremely Strong"? The existing data do not mention any deformity and it isn't even considered "ugly". Also a lot of tasks affected by hand encumbrance only require a lesser degree of precision which should not be impaired by "slightly larger" hands, for example swinging a longsword or forging said sword.

Considering what strength is mostly used for, namely lifting things, carrying them and wielding weapons, it would make more sense to encumber the arms from the added muscle mass. This also has a simple basis in the square-cube-law. Theoretically the legs should be affected as well but with the current encumbrance penalties this does not make as much sense in practice.

And more out of curiosity, what is your scientific reasoning for the reduced water consumption? If it's related to a lack of sweating that might be interesting to note in the trait descriptions.

**Comment by Kelenius** [comment]
You want to add a penalty to these mutations for no reason other that they're good? I'm not following this line of logic. They're mutations. They're balanced by needing to find/craft mutagen and randomness. On top of that, `STR_UP_4` is a post-threshold mutation.

**Comment by dissociativity** [comment]
Fair criticisms, and yes, it's the lack of sweating, that and a slower metabolism in general would no doubt go through less water, just as it goes through less calories to burn.

I'm trying to balance strength mutations vs mutation builds that do not get them, for example there is no real reason to not go for say lupine since strength and minmaxing that in general is so dis-proportionally overpowered in almost all aspects of the game.

**Comment by dissociativity** [comment]
My logic behind the encumbrance, is that this strength mutation is not like fit human's workout where ones hands would largely stay the same due to the improvement in strength being attributed to forearm muscles and not those in the palm, and certainly not tendons, it makes both the muscles AND tendons of the hands larger, increasing the overall size of even the digits, impacting fine motor skills.

**Comment by dissociativity** [comment]
Kevin has suggested I instead make these more powerful strength traits cancel dexterity enhancing ones, that seems like a fair compromise instead of my solution, so I'll go for that

**Comment by KITbutler** [comment]
> My logic behind the encumbrance, is that this strength mutation is not like fit human's workout where ones hands would largely stay the same due to the improvement in strength being attributed to forearm muscles and not those in the palm, and certainly not tendons, it makes both the muscles AND tendons of the hands larger, increasing the overall size of even the digits, impacting fine motor skills.

On what scale though? If hand encumbrance mainly hindered operating computer consoles, guns and watchmaker-level fine crafting I would agree wholeheartedly, but as of right now you would be slower to swing a pipe at a zombie as well. Shifting it to the arms you at least have a logical justification as to *why* swinging a pipe is slower.

> again, I see the mutations as an indiscriminate expansion of the body, not equivalent to the player working out.

The lack of "visibility", "ugliness" and explicit mention to this effect in the previous description suggests this is merely your personal opinion. We already have the "huge" series to represent what you describe.

> mutations aren't supposed to be a largely positive thing the player wants to go for without drawbacks, and there are solid trees that simply outweigh all others in benefits unless one has a more obscure playstyle, and all of them involve a decent amount of strength.

There already is a **massive** host of **entirely negative** mutations to accomplish that goal, and even a baseline bias towards getting those. Unless you're save-scumming the hell out of every dose of mutagen you **will** get screwed over. 

I don't see why you singled out Lupine or the strong beasts in general as they actually have quite a few downsides with the howling, encumbrance+gear restrictions from other mutations and a few peripheral losses which hamper most non-combat activities (loss of INT, speech skill, food QoL) plus a fairly large chance you won't be able to wear power armour.

> This and balance-wise it makes sense given it stacks with other strength enhancing mutations.

The other strength-enhancing ones are not many, mostly post-threshold and/or come with substantial downsides themselves already. Given a reasonable ability to pick and choose on an endgame character I would not go for any of those unless specifically playing a melee-focused challenge (or a greatbow archer).

> Kevin has suggested I instead make these more powerful strength traits cancel dexterity enhancing ones, that seems like a fair compromise instead of my solution, so I'll go for that

This seems reasonable overall except I'm not sure how DEX mutations are supposed to operate in the first place. If it's "fast-twitch" vs. "slow-twitch" muscle enhancements that'd make a *lot* of sense actually, but now DEX mutations feel too weak since they also lock you out of the STR bonus.

Speaking of which, if the "cancels" entries are not symmetric does that mean chugging your wolf mutagen first and the cat juice later still lets you grab both traits granted sufficient luck?

**Comment by dissociativity** [comment]
No, this should mean you can only get so strong before strength cancels out higher end dexterity now.
I removed the encumbrance effect as a more balanced compromise.

**Comment by KITbutler** [comment]
> No, this should mean you can only get so strong before strength cancels out higher end dexterity now.

I assumed that's what you're *trying* to do, but what does *the code* do if you already have "Extremely Strong" and try to mutate towards "Extremely Dextrous"? Is it smart enough to read out the "cancels" entries on your *existing* mutations? The existing "obvious opposites" examples suggest this at least *used to be* an issue as both sides explicitly exclude their opposite.

**Comment by dissociativity** [comment]
Jenkins Rebuild

**Comment by kevingranade** [comment]
After testing, you *can* work around the strength/dexterity conflict by acquiring the strength mutations first and later acquiring the dexterity ones.  It needs to be a mutual exclusion to be meaningful.

**Comment by dissociativity** [comment]
Just close this one, I accidentally deleted this branch when the development/master split was reversed
I'll possibly to a revised version at some point with these suggestions in mind

**Pull request closed without merging**
