### PR TITLE
Make the game angry if ``luminance`` is defined as the default value

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
For ages I've seen ``luminance: 0`` across files and it didn't do SHIT. It's a wasted field, that I always was confused why we didn't have the game yell about. No more.

#### Describe the solution
Make the game throw an error if ``luminance: 0`` is defined. Remove instances of ``luminance: 0`` (and double-copying luminance) across the ``data`` folder.

#### Testing
Compiled and ran the tests - it cried

#### Additional context
The C++ part done entirely by @GuardianDll because when I tried to do this myself yesterday I failed miserably

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> For ages I've seen luminance: 0 across files and it didn't do SHIT. It's a wasted field, that I always was confused why we didn't have the game yell about. No more.

This isn't a problem. IMO it's fine to remove the default-assigned field for this field that's not really going to have it's default value change, but I don't think the game should complain about the default assigned value.

Consider the following use case:

I add a bunch of nether monsters, 4 of which have luminance, and a fifth which doesn't. Instead of leaving the luminance out for the fifth, I explicitly set it to zero - making it clear it is not an accidental omission.

This is now not allowed, yet it costs nothing to have these fields.

**Comment by Maleclypse** [comment]
Conflicts.

**Comment by Maleclypse** [comment]
I guess my question is what's our testing do for other things set to zero?   I know some things use setting a field to zero in order to change monsters that use copy-from but don't need that specific stat.

**Comment by anothersimulacrum** [comment]
It's not about setting to zero, it's about assigning the default value.

On the topic of copy-from, another thing this disallows is explicitly setting a field so that it is not changed accidentally when the monster the monster defining it is copied-from changes.

These aren't pressing issues for this specific field, and I don't think should hold up this PR made by a person who has to interact with a lot more monster JSON than I do, but I'm not a fan of the of getting warnings about explicitly setting default values.

**Comment by Karol1223** [comment]
> I guess my question is what's our testing do for other things set to zero? I know some things use setting a field to zero in order to change monsters that use copy-from but don't need that specific stat.

It's not specifically about being set to 0, but being set as the same as the default or inherited value. We do the exact same thing with weight, volume and vision ranges, to name just a few.

> These aren't pressing issues for this specific field, and I don't think should hold up this PR made by a person who has to interact with a lot more monster JSON than I do, but I'm not a fan of the of getting warnings about explicitly setting default values.

Monsters are plagued by cargo culting to hell and back. There's dozens of definitions with either code that does absolutely nothing, or code that was copied from somewhere else and still DOES things that shouldn't be happening for that particular definition. Empty fields are not the end of the world, but they do make monster JSON look far more menacing and difficult to navigate than it needs to be.

**Pull request merged**
