### PR TITLE
Add longest side information to unprocessed nuts

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

None

#### Purpose of change

Unprocessed nuts previously had no size information. I'm trying to add it, both for consistency with processed nuts, and to better work with `min_item_length` pockets.

#### Describe the solution

- Added `longest_side` info to the JSON.
- Also added material (nut).

#### Describe alternatives you've considered

Carrying less stuff, rather than insisting my survivor fill the last of their pockets with hickory nuts, bits of string, and other small items.

#### Testing

Started vanilla game with default options. Went to the debug menu to examine and spawn nuts. Verified nuts had size information.

#### Additional context

This PR previously wasn't working as intended, but adding material seemed to fix that.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I'm not sure what you're trying to achieve. Some of these lengths make no sense at all, such as the last one that tries to somehow squeeze a quarter of a liter into something that has no more than 5 mm length in any dimension (maybe you're trying to describe the size of an individual walnut [although that size looks more like the short side of a shelled peanut], rather than a handful of an unspecified number of nuts?).

The absence of a longest side causes the game to consider the item to be spherical and derive the longest side from that, which I think is a decent approximation for a pile of nuts.

As to why this change doesn't show up, I have no idea beyond the possibility that the wrong file was edited (or not saved before testing the changes) or the wrong items were examined.

**Comment by pjf** [comment]
Sorry, it was late at night when I submitted this, and I could have explained better.

Right now, the "spherical handful of nuts" can be happily stored in a string bag, even though they should fall out. What's more, the *shelled* version of all the nuts have `longest_side` information, and it feels like we should be consistent.

The 5mm for a walnut was a typo, it was supposed to be `50mm`, and I'll fix that now. The other sizes should be realistic for the unshelled nuts; I've cited sources in the commit info where available (although to be fair a few I just eyeballed).

**Comment by PatrikLundell** [comment]
I don't see a reason for unshelled nuts to have a longest side either unless they're stored in a rigid container (in which case it's the container that should have inflexible dimensions). Shelled or unshelled, a handful of nuts is just a pile of smaller items, the pile of which should be rather pliable.

The actual issue seems to be that a pile of small items shouldn't be contained in a container with holes that are large enough for the small component items to fall out of. I believe pockets can have requirements for minimum dimensions to deal with nets and the like, but I'm not aware of anything that's capable of dealing with collections of small items that aren't liquid or powder.
It would be possible to convert nuts into individual items, but then you'd run into the issues that causes, such as 1 s spent on pick up or dropping of each individual nut (and, of course, adjustment of all recipes using nuts).

**Comment by pjf** [comment]
> I believe pockets can have requirements for minimum dimensions to deal with nets and the like, but I'm not aware of anything that's capable of dealing with collections of small items that aren't liquid or powder.

A sample pocket I was looking at was the water-bottle pocket on the daypack, which is presumably a mesh-style pocket:

```json
      {
        "//": "waterbottle pocket",
        "pocket_type": "CONTAINER",
        "holster": true,
        "max_contains_volume": "510 ml",
        "max_contains_weight": "1 kg",
        "max_item_length": "12 cm",
        "min_item_length": "7 cm",
        "moves": 80,
        "description": "Small pocket for a waterbottle",
        "ripoff": 2
      },
```

I've personally stuffed unprocessed chestnuts into such containers iRL; the chestnuts are large and spikey, and don't fall out, whereas smaller nuts (eg: acorns) would.

> but I'm not aware of anything that's capable of dealing with collections of small items that aren't liquid or powder.

Right now we can insert pills into bottles, and then place the bottles in pockets. I don't see any reason why one couldn't do the same with nuts.

> It would be possible to convert nuts into individual items, but then you'd run into the issues that causes, such as 1 s spent on pick up or dropping of each individual nut (and, of course, adjustment of all recipes using nuts).

Oh no! I definitely don't want to do that. I just want the shelled and unshelled nuts to be consistent, and to work with the magnificent pocketry systems we already have. :)

**Comment by pjf** [comment]
Update:

I've added material information to the nuts in question, and they now seem to be working as intended!

I've rebased onto current `mater`, updated the top information for this PR with the updated details, and marked this as ready-to-go!

**Comment by pjf** [comment]
Updated test suite to exclude nuts from the minimal diameter check.

**Comment by kevingranade** [comment]
Thanks for bringing up the issue, but I think this is the wrong way to fix it.
For one thing, nuts should be precisely the kind of thing that we don't need length data for. For another, having an impossibly short length relative to volume is just asking for trouble.

**Comment by pjf** [comment]
@kevingranade : Roger that! It was good practice for me to touch the C++ test suite and discover the joy of clang-tidy. :)

- Without modelling individual nuts, do we have a way of indicating "this is a collection of small things"? If not, should I write an issue summarising?
- Should I remove the existing length info on processed nuts?

**Comment by I-am-Erk** [comment]
What we might want is some sort of information to indicate that an "item" is actually a bunch of small granules or a powder, so we can have it behave accordingly. I would suggest that it might fit in `"phase"` even though it's a bit of a stretch of the term itself, and we could have "powder" and "granules" or similar as options. There are other places this would help, like most of the time we should be treating powders like we treat liquid (you can't recover them after dropping without a container, eg).

**Comment by pjf** [comment]
@I-am-Erk : Thank you! I've opened an issue to track the discussion and potential outcomes.

Closing this PR in favour of #53718.

**Pull request closed without merging**
