### PR TITLE
Delete one-off conversion tools that are no longer necessary

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary 
SUMMARY: Infrastructure "Delete one-off conversion tools that are no longer necessary"

#### Purpose of change
For some reason I do not understand a couple of one-off conversion tools were checked into the repo. As far as I can tell these two tools were only useful once: during a json conversion. Why are they still here cluttering up the tools/json_tools/ directory? Is there any use for them after the conversion is done?

#### Describe the solution
Delete these tools.

#### Describe alternatives you've considered
Keep them and let them waste time of every new person looking for json tooling.

#### Testing
none

#### Additional context
none

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Are they useful for legacy third-party mods?

**Comment by hexagonrecursion** [comment]
I don't know. Maybe.

**Comment by KorGgenT** [comment]
we should definitely leave the pocket tool in at the very least until 0.F, as that tool was used in this very experimental, and as it's a migration tool it can be useful.

**Comment by wapcaplet** [comment]
Maybe there is value to including a line or two of documentation in these scripts, explaining their purpose. I have also wondered why they were in the repository.

**Comment by mrkybe** [comment]
I found these a helpful reference for when I did a one-off conversion.  I know technically they'll always be in the git history, but as a practical matter, maybe putting them in a "OneOffs" folder would be useful as a reference for future contributors?

**Comment by ZhilkinSerg** [comment]
Let's not delete them, but some comments are welcome.

**Pull request closed without merging**
