### PR TITLE
Revert "Broken Cyborg awards 6 points instead of 2, in light of new bionic changes"

### PR DESCRIPTION
**Pull request by kevingranade**
Reverts CleverRaven/Cataclysm-DDA#24582

A little quick there.  The profession is no less *survivable* than it was before, just more resource intensive.

### CODE REVIEW

**Comment by Xhuis** [comment]
I still am very much of the opinion that the difficulty has been increased enough to justify an increase in points. As I mentioned in the PR, it requires eighteen anesthesia kits to uninstall all the bionics - a massively high amount, and with the amount of drawbacks you suffer constantly until you uninstall at least a good chunk of them, the 2 points is simply disproportionately weak. Really Bad Day gives eight for something I would argue is less severe, for Pete's sake.

Maybe 6 is too much, but I think 4 or at least 3 would make it more reasonable.

**Comment by Mecares** [comment]
That will sound to Kevin like a really bad day gives too much points, which actually might be the case. An overall point rebalance of professions and scenarios following some kind of rules instead of subjective opinions would be nice.

**Comment by kevingranade** [comment]
> the difficulty has been increased

How has it been increased?  This:
> it requires eighteen anesthesia kits to uninstall all the bionics

Is a *Resource Sink*, not added difficulty.  Short term survivability is exactly where it was before.  If the status quo was you sitting down and uninstalling the worst bionics right at game start, it was already "free points" to take the profession.

Also, CBM uninstallation is currently in a state of flux, we don't need to be going around doing a final polish on balance until that settles down, see: #/24508 #24572 #24571 #24567

**Comment by Xhuis** [comment]
By virtue of the large amount of drawbacks staying for a much longer time, I would say that it is more difficult. Having so many downsides that can't feasibly be removed until midgame is highly damaging and greatly decreases your chances of survival.

Broken Cyborg was balanced around uninstallation of its faulty bionics being possible with a knife and a first aid kit. As such, I feel that having to find so many rare materials in order to remove the bionics is disproportional to the points it gives you.

**Comment by DracoGriffin** [comment]
I believe a small increase could be warranted, as seeing crafting your own anesthesia will still require time to develop (acquiring resources [length of time depending on rarity and RNG]) and feasibility of NPC's removing CBM still reliant on their capability (either taking the risk with a crappy "surgeon" or lucking out/finding a NPC with the appropriate skills) --- all the awhile coping with the side effects of faulty CBMs.

**Pull request merged**
