### PR TITLE
Make "just for fun" books that you haven't read yet a lighter red

### PR DESCRIPTION
**Pull request by Musteval**
#### Summary
Interface "Display unread 'Just For Fun' books in a lighter color than unread educational books"

#### Purpose of change
When I'm looting houses (and especially bookstores), I tend to want skill-training books very badly, and "just for fun" books not at all. But in the UI they're hard to distinguish - they're both red if you haven't read them yet, and you need to go into the item description to see whether they're just for fun or not. Heuristics like "anything with chapters is just for fun" don't work, because of books like A Taste of India that are entertaining, have chapters, and also contain skills and recipes.

This PR makes the just-for-fun books light red, so you don't have to remember every individual book's name. There's an argument that this is unrealistic - the fact that you don't know a book's contents until you've skimmed it is a feature that was intentionally added. But:
- Even if my character doesn't know what's in the book, I do. It's frustrating when the game doesn't acknowledge that.
- From a realism perspective, you can already see if a book is "just for fun" before you've skimmed it - this change just means that you get that information without needing to dig into the item description

#### Describe the solution
Modified color_in_inventory to return light red for books with no skills or martial arts. The logic here was taken from item::book_info https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L3105. Based on the description of color_in_inventory this should be a purely cosmetic change in any case.

#### Describe alternatives you've considered
The light red is pretty close to the normal red - might be better to use a different color with more contrast.

#### Testing
bookstore
reading

### CODE REVIEW

**Comment by Light-Wave** [comment]
Oh yes please. This would make life so much easier.
On a side note, it might be worth looking into if this causes problems for colorblind people.

**Comment by actual-nh** [comment]
> What about having skill books use capitals, and 'just for fun' books, not?

One would still need a way to distinguish them for languages not using capital letters. Possibly whatever is used in web browsers for `<EM>`?

**Comment by MarlossCDDA** [comment]
This shouldn't make things any worse for colorblind players than the status quo, but I agree it'd be better if we had a way to distinguish them that would work for them as well. Maybe if we choose colors that are sufficiently far apart in brightness they'd be distinguishable?

**Comment by GuardianDll** [comment]
i just checked some sites that make images "how colorblind person see this", and mostly it work same as normal color changing, but i still think change the color is better idea - its pretty hard to see the difference even for non-colorblind person
image

>One would still need a way to distinguish them for languages not using capital letters.

I agree with that

**Comment by Light-Wave** [comment]
> i just checked some sites that make images "how colorblind person see this"

Make sure to also check that it's not too similar to green, blue, or yellow. Preferably with different colorblind filters.

**Comment by MarlossCDDA** [comment]
How about red and inverse-red? It's much more distinctive, but maybe a little too much:

red
get

**Comment by MarlossCDDA** [comment]
Sure does make you want to read those books so the color will go away, though, right?

**Comment by Light-Wave** [comment]
> Sure does make you want to read those books so the color will go away, though, right?

Either read them, or apply bandages to stop the bleeding.

**Comment by GuardianDll** [comment]
Yep, both of them is pretty good and intuitive - easy to understand which one you need to pick up, and which one is trash

**Comment by MarlossCDDA** [comment]
I guess uh react :+1: to vote for the original light red, :-1: for the bold inverted red, 😄 for pink, and 🎉 for magenta

**Comment by ektoplazm** [comment]
Pink (or a color which is pretty close to it) is already used for skill books when the player does not meet their skill requirements.

**Comment by GuardianDll** [comment]
Thats why i said about orange (c_red_yellow) or beige (c_brown_white) - both of them didnt used in books

**Comment by MarlossCDDA** [comment]
@GuardianDll unfortunately c_red_yellow isn't "orange' it's "red foreground, yellow background":

red yellow

And c_brown_white is uh not great contrastwise:

beige


@ektoplazm Oh, you're right - books that you're not skilled enough to read yet display as grey on the "read book" menu but pink on the inventory screen. Compare Out of the Holler and into the Home on the "read" popup above, with on the inventory screen below. So I guess pink's a bad choice.

grey

**Comment by Zireael07** [comment]
Incidentally, IMHO red fore yellow back is better than inverted red presented earlier.

**Comment by Aphegis** [comment]
Am i the only one who thinks that 2 colors like the pictures makes the inventory really ugly and disorganized? If you guys like it, i can live with it... please share your opinions if you prefer single color or the way in the pictures.

2 colors 2
2 colors

**Comment by actual-nh** [comment]
Oh - one thing. There are a couple of books that, IIRC, come in two versions - with something special and without - namely the standpipe maintenance log and the AAA guide. These should never (in either version) show up as "just for fun", even if they lack recipes.

**Comment by MarlossCDDA** [comment]
@actual-nh Both the AAA onse already have skills, so that's not an issue today. The decoy standpipe one doesn't have a skill, but you can already distinguish them because the decoy has "just for fun" in its item description and the chemistry one doesn't. So perhaps it'd be better to make the decoy standpipe one train some skill to 1.

**Comment by MarlossCDDA** [comment]
I think mechanics would make sense, but that's a kinda big balance change I think - right now I'm not aware of a good way to go from mechanics 0 to 1 except "find a book that teaches mechanics 1" and those are currently pretty rare. But maybe that's not a bad thing, I do think it should be easier to go from mechanics 0 to 1 (or someone should tell me the trick that I haven't figured out).

**Comment by actual-nh** [comment]
> I think mechanics would make sense, but that's a kinda big balance change I think - right now I'm not aware of a good way to go from mechanics 0 to 1 except "find a book that teaches mechanics 1" and those are currently pretty rare. But maybe that's not a bad thing, I do think it should be easier to go from mechanics 0 to 1 (or someone should tell me the trick that I haven't figured out).

Three possibilities:

- It may well not be a bad thing... perhaps a high int requirement? You can get around it with time, but that's also rereading a book with a decidedly negative morale modifier (which could also be increased)!
- I doubt it's currently doable in JSON, but getting a clue as to the layout of the facility in question makes perfect sense.
- Add the pipe cleaner recipe - but with int and mechanics skill 1 requirements (latter may be built-in); you're taking what somebody wrote in as a way to clean the pipes, and decreasing the size. (It's in recipe_other.json, BTW.)

**Comment by MarlossCDDA** [comment]
3686086f96 does the pipe cleaner thing - confirmed decoy and real one are both the same color.

standpipe

**Comment by Night-Pryanik** [comment]
How about **bold** for skill books? Or maybe _italics_?

**Comment by actual-nh** [comment]
> How about **bold** for skill books? Or maybe _italics_?

Bold is a distinct possibility. I find italics without bold tend to be harder to read.

**Comment by actual-nh** [comment]
#48462 (see my comment & below) may be of interest re making sure things actually are "just for fun".

**Comment by actual-nh** [comment]
I have been (reluctantly) forced to conclude that this probably should be under 0.F Feature Freeze; if anyone has an argument otherwise, I'd be quite happy.

**Pull request merged**
