### PR TITLE
Charges / item consumption for non-comestible healing; first aid items from comestible to generic

### PR DESCRIPTION
**Pull request by cake-pie**
#### Summary
Infrastructure "Charges / item consumption for non-comestible healing"

#### Purpose of change
(Split from #63428)

While investigating #63345 I found that the "heal" use action only has code for consumption of comestibles, and doesn't handle anything else properly (nothing is deducted).

#### Describe the solution
If a tool has `charges_per_use`, deduct that much when it is used for healing. -- See #63428 for a demo/test item.

If an item has `SINGLE_USE`, delete the item when done with healing.
Leverage this new functionality to change first aid items that use the "heal" use action from comestibles to generic items. Adjust item stats, spawns/drops, recipes proportionately; put items on charge migration blacklist.

Driveby: two recipes with fake activity level changed to `LIGHT_EXERCISE`

#### Alternatives considered
Continue to have comestibles that are `NO_INGEST` and `EDIBLE_FROZEN`.
Continue to be prone to bugs due to using comestibles for things that aren't actually food. (e.g. #38698)

#### Testing
Debug damage self, debug spawn the first aid items, use them and note that they are correctly used up.
Compare vs prior version to check item stats and affected recipes.
Check professions that start with any of the changed items -- ensure that those that used to have `charges` in the item definition still spawning with correct number of items (now set with `count`)
Scrutinize JSON spawn/drop changes.

### CODE REVIEW

**Comment by mqrause** [comment]
Considering these items don't seem to be using any tool mechanics, `generic` might be a better choice of type. Good stuff, though. Should be merged before #60885.

**Comment by andrei8l** [comment]
UX-wise this is pretty awkward as some healing items (ex: bandage) are now in the `a`ctivate menu while others (ex: antiseptic) are in the `E`at menu. IMO you should change `comestible_inventory_preset` and related bits to preserve the old UX. That doesn't have to be in this PR though.

**Comment by cake-pie** [comment]
> don't seem to be using any tool mechanics, `generic` might be a better choice

Hmm, you have a point; I guess I was a bit fixated on tools due to the context behind this (#63345, #63428)

---

> UX-wise this is pretty awkward as some healing items (ex: bandage) are now in the `a`ctivate menu while others (ex: antiseptic) are in the `E`at menu. IMO you should change `comestible_inventory_preset` and related bits to preserve the old UX.

The items changed were already in the `a`ctivate menu to begin with even before this PR, and remain accessible there. This has not changed. Other healing items like antiseptic, also do show up as "apply to wound" in the `a`ctivate menu. This is the logical way to access them.

The reason behind healing items (that are not actually food, or even edible) showing up in the `E`at menu is because of (ab)using comestible type for things that are not food. Seriously, we do not eat bad-aids, bandages, or medical gauze to treat a wound. Rather than trying to "preserve" such illogical UX, I think that we should instead be looking into how other non-food medical items can be taken out of comestibles as well.

**Comment by andrei8l** [comment]
There is a dedicated `Cosume Medication` hotkey unbound by default.

What's logical is not very relevant for UI as people just expect their UX habits to keep working.

Finally, the `a`ctivate menu shows far more than just medication AND doesn't auto-return. So if you want to patch yourself up after a fight, you now need to repeat 6 times 1.`a`ctivate 2. `/`filter bandage 3. apply

**Comment by andrei8l** [comment]
I've noticed that this makes alcohol wipes spawn as one per box. Example from `drugs_heal_simple`

Screenshot from 2023-02-16 18-01-05

**Comment by cake-pie** [comment]
Ah, it needs the first aid kit treatment. Same for cotton balls. Thanks for catching this.

**Pull request merged**
