### PR TITLE
Prune nanofab_recipes

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Polish up nanofab recipes"

#### Purpose of change
We have a few nanofab recipes for items that either don't make sense to be nanofabbed, or aren't earth native. 
G80 railgun stuff: Spawns in voidweaver pools, aren't earth-native, therefore shouldn't be in here.
Alloy plate: What super alloy is is a bit vague, but a single solid sheet of one material seems like a waste of an intricate machine, akin to using a 3d printer to print out square sheet of plastic. 
Plasma gun: Voidweaver pools, see above. 
Can sealer: A joke 
UPS: It appears to be a pretty basic electrical device, no reason to use an expensive machine and expensive materials to produce it. 
Atomic coffeepot: This is a civilian commercial product, akin to using a nanofab to produce an iphone.

#### Describe the solution
Removes recipes. 

#### Describe alternatives you've considered
Remove the laser stuff, as that also feels a bit too high-tech

#### Testing
These are the recipes that were spawned in before the changes, after the changes applied. Everything still works fine. 
image
Here's the results of the new itemgroup
image

#### Additional context
Paging @John-Candlebury for input. I know this is kinda your baby, so I want to know if there's anything more you want removed, or anything you want to remain, or anything you want added. This PR will remain in draft until I get your input.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
I'll need to re arrange the entirety of the list with (or after) #76582.  Not a bad change for now tho.

**Comment by tenehea** [comment]
!?!??!?!

Nanofab is for fun, exotic end-game items

**Comment by KHeket** [comment]
> Nanofab is for fun, exotic end-game items

Relax. Fun is forbidden by kevin
Dont waste your nerves and energy to change their mind, its useless

**Comment by John-Candlebury** [comment]
Its salvaged alien technology, it'll get a new list that reflects this. I

**Comment by RenechCDDA** [comment]
@KHeket Read the [code of conduct](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/CODE_OF_CONDUCT.md) before posting again. In particular, you must refrain from making inflammatory remarks or assuming bad faith.

**Pull request merged**
