### PR TITLE
Added `CARGO` flag and size to vehicle aisles

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Rationale for selected size - 200 liter barrels should fit in single tile of heavy duty truck.

### CODE REVIEW

**Comment by kevingranade** [comment]
The cannonical use for a vehicle aisle is the walkway of a passenger bus, not a cargo vehicle.
Minimum width for an american schoolbus is 12"... that sounds kind of insane, but the more typical value seems to be about 18"
https://www.bestbussales.com/buses-by-mfr/glaval/concorde/index.html
That definitely makes the 200l barrel not work, it's over 22.5" in diameter.
If the truck needs to have better cargo-carrying capacity for it's aisle, it needs a different vehicle part.

Additionally, having the aisle be "full" should represent the aile still being usable to move through, so I would suggest a much, much smaller cargo capacity, something like 50l (200 in "volume units")

**Comment by ZhilkinSerg** [comment]
> If the truck needs to have better cargo-carrying capacity for it's aisle, it needs a different vehicle part.

You are probably right.

**Comment by Broken-Admin** [comment]
This is at what point in development?

**Comment by ZhilkinSerg** [comment]
> This is at what point in development?

I assume it is ready to be merged.

Truck with aisles instead of cargo spaces is ridiculous, so I've replaced some of the aisles with cargo spaces.

**Pull request merged**
