### PR TITLE
CITY_UNIQUE flag

### LINKED ISSUE #72904: [Self assigned] "CITY_UNIQUE" flag
### Is your feature request related to a problem? Please describe.

UNIQUE currently makes it so only 1 of that special can appear per overmap (not to be confused with GLOBALLY_UNIQUE). Currently no city specials use this flag but with #72815 adding the ability to limit special spawns in cities based on city size it would make sense to increase their weights so their relative occurrences doesn't drop, however currently that would lead to multiple of the same type appearing in a single city which doesn't make sense for some of them.

### Solution you would like.

For cities it would make more sense for this to limit specials to 1 per city.

### Describe alternatives you have considered.

Using a separate flag for this functionality but UNIQUE is currently unutilised by city specials.
Waiting on someone to figure out limiting special placement based on already placed specials so you can prevent same function buildings spawning near each other where sensible even when there are multiple similar specials (as well as more realistic placement in general)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
Fixes #72904

#### Describe the solution
UNIQUE is now called OVERMAP_UNIQUE to avoid confusion
Adds CITY_UNIQUE flag that limits a city building to once per city
GLOBALLY_UNIQUE is checked before counting towards retries for city building placement

Will add uses of the flag
Will attempt to enforce CITY_UNIQUE, OVERMAP_UNIQUE and GLOBALLY_UNIQUE mutual exclusivity
Will add an error if CITY_UNIQUE is used with a non city building special unless I change my mind and make it work with them too

#### Describe alternatives you've considered
Allowing max occurrences per city instead
Removing the existing flags and making it a field instead to make their mutual exclusivity more obvious

#### Testing
Compiles and loads
Tested that 50000 weight cathedrals were only spawning once per city at max city size world setting

### CODE REVIEW

**Comment by RanikOrtega** [comment]
Great addition. Some clarification. What locations would be unique per city? 

Versus something like "Max occurances per city size 4 city size" where one hospital could spawn in a size 4 city, 2 could spawn per size 8 city and 3 per size 12 city etc etc

**Comment by PatrikLundell** [comment]
Essentially the same comment as @RanikOrtega: If you can have more than one of something in a city but the number still being limited, the permitted number of instances ought to scale with the city size.

I guess something like a city council would be limited to (at most) one instance, but on the other hand it might be implemented by the same city administration facility that may be spread over the city's various districts so you can't actually distinguish it from those.

**Comment by RanikOrtega** [comment]
> Essentially the same comment as @RanikOrtega: If you can have more than one of something in a city but the number still being limited, the permitted number of instances ought to scale with the city size.
> 
> I guess something like a city council would be limited to (at most) one instance, but on the other hand it might be implemented by the same city administration facility that may be spread over the city's various districts so you can't actually distinguish it from those.

Having thought it over. City_Unique and new city Size restrictions would work with things like Town Halls vs City Hall or Sheriffs Department vs Police HQ. But other items are not exactly city Unique but somewhere in the "there should be X many per city size" category. But that is a different ask. 

Now that we have city Size restrictions, and Procyonae is getting City Unique working. Instances per city Size would be the next step I guess.

**Comment by Procyonae** [comment]
I don't have any problems growing it to something like "X occurances per Y city size" or similar in future but with how small the largest cities possible rn are I'm not sure that level of granularity would achieve much
My main motivation for this is allowing city_sizes to limit large buildings to large cities but without making them really rare by giving them this along with higher weights so they try to spawn more frequently in big enough cities but can only place once so big cities aren't just made of all the big buildings. The initial uses I just made are very tentative like my city_sizes initial uses, once we've got some kind of high-density/low-density distinctions and versions of things that should be common but only exist for one rn etc I'll be more willing to go ham and start really trying to make different city sizes feel distinct.

**Pull request merged**
