### PR TITLE
Automated linting of MONSTER

### PR DESCRIPTION
**Pull request by mugling**
Automated changes following manual review in #18427 as per discussion in #18330

### CODE REVIEW

**Comment by illi-kun** [comment]
```
Linting data/json/monsters.json: ERROR: Format error at line 1138
<     "starting_ammo": { "556": 1000, "40mm_frag": 100 },'
>     "starting_ammo": { "40mm_frag": 100, "556": 1000 },'
```

**Comment by mugling** [comment]
How we split this file (by faction, species, etc) needs to be discussed so will be undertaken in a separate PR. Suggestions anyone?

**Comment by mugling** [comment]
@illi-kun can reproduce, suspect I know why as well

**Comment by mugling** [comment]
The problem is that the contents of `starting_ammo` both match the same `context` and therefore have the same `rank`. We need to tie-break, probably via alphanumeric sorting of keys.

Looks like `make lint` should involve a self-check via `make lint-check` to detect situations like this

**Comment by illi-kun** [comment]
> Looks like ```make lint``` should involve a self-check via ```make lint-check``` to detect situations like this

Seems to be a good self-check.

**Comment by mugling** [comment]
I think the terminology would `commutative`

**Comment by mugling** [comment]
@illi-kun ready to test again

**Comment by mugling** [comment]
Will do Makefile adjustments in further PR

**Comment by illi-kun** [comment]
OK, updated version works fine for me, I'll run ```make clean``` just in case and merge this PR right after that.

**Comment by mugling** [comment]
Good stuff (strictly speaking you only need to nuke `obj/lint.cache`). Where would be a good place to write summary documentation describing how to run the linter (as opposed to how to extend it)

**Comment by illi-kun** [comment]
> strictly speaking you only need to nuke ```obj/lint.cache```

Thanks for the note, I'll use it (and save a lot of time!).


> Where would be a good place to write summary documentation describing how to run the linter

```CONTRIBUTING.md```, I guess (or just a link to GH wiki with description of this stuff in the mentioned .md file is enough).

**Pull request merged**
