### PR TITLE
Mutant Firefly Lamps and associated things

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Content "Mutant Firefly Lamps"

#### Purpose of change
To add a Mutant Firefly lamp.

#### Describe the solution
We have mutant fireflies.  This adds mutant firefly lamps and a mega fern. I need to figure out if Mega Ferns should appear near Triffids or in swamps?  Once that's decided I can add a recipe for it.  Adds a tie in for someone to create a bug scientist who came up with the idea for these.  

#### Describe alternatives you've considered
None

#### Testing
TBD

### CODE REVIEW

**Comment by Maleclypse** [comment]
@Venera3 and @Mom-Bun thoughts on whether the mega ferns came from ancient history or with the Triffids?

**Comment by Venera3** [comment]
The leech plants are referred to as ferns consistently, so I vote for funky nether flora. Using them would also give you one reason to engage with root runners and co. and has some story potential for our scientist to have gotten away from them (but managing to get some samples).

**Comment by Mom-Bun** [comment]
> @Venera3 and @Mom-Bun thoughts on whether the mega ferns came from ancient history or with the Triffids?

Sorry late, but I am totally up for mega ferns being associated with triffids, especially if from what I understand what Venera is suggesting its some weird nether flora

I'd really like Triffids to have some more alien-esque plants for em instead of regular plants that just exist right now!

**Comment by Venera3** [comment]
No, I meant using leech plants - though *them* being an alternative triffid morph also crossed my mind.

**Comment by Maleclypse** [comment]
I'll try and finish this out this weekend.

**Pull request merged**
