### PR TITLE
Convert class Messages to namespace[RDY]

### PR DESCRIPTION
**Pull request by Dyrewulfe**
#### Summary
SUMMARY: Infrastructure "Increase code clarity of Messages and remove unneeded indirection"

#### Purpose of Change
This change makes the code of Messages match it's application, and removes the unneeded indirection involved in using a pointer-to-implementation. Removing the implementation pointer resulted in a class that was only serving as a namespace, so I changed to it to be so.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Needs a proper SUMMARY line for the new changelog parser/creator tool.

**Comment by Dyrewulfe** [comment]
@mlangsdorf Did I get that right? (My apologies, that must be a relatively new thing, and I PR'd right before I went to sleep.)

**Comment by kevingranade** [comment]
Turns out you were misled by the quoting in the template, which now that I think of it is perfectly natural.
This is what you want, we need to revisit the template and try to make it less confusing.
SUMMARY: Infrastructure "Increase code clarity of Messages and remove unneeded indirection"

**Comment by Dyrewulfe** [comment]
Alright, sans the markdown triple grave, and done. And yep, they aren't converted in the template, so it very much does look like it's suggesting to use them.

**Pull request merged**
