### PR TITLE
Fix ammo belts not scaling volume/weight with current amount of ammo

### LINKED ISSUE #57981: Ammo belt's weight and volume is broken
### Describe the bug

The volume of ammo belts is fixated on 200 ml no matter how much round it has
His weight is scalable, but it adds flat +1 kg to weight of stuff inside it

### Steps to reproduce

Spawn 2 any ammo belt (for example, `5.56x45mm ammo belt`)
Unload one of them
find the belt has different stats than both .223 linkage and 5.56 NATO M855 ammo

### Expected behavior

Having correct weight and volume for belts

### Screenshots

500 ammo in belt vs 500 ammo and 500 linkage
image

1 ammo in belt vs 1 ammo and 1 linkage
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 714cafd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Fixing the weight require to delete the [weight flag in belt's abstract](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/classes/magazine.json#L8) and supress the 0 weight error with ZERO_WEIGHT flag
fixing the volume is require to delete the volume (or left only 1 to supress error), and delete all `"rigid": true` fields from his child
Not sure about how realistic this fixes, but i see no another way

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Bugfixes "Fix ammo belts not scaling volume/weight with current amount of ammo"

#### Purpose of change
Fixes #57981

#### Describe the solution
Changed both `weight` and `volume` of the base magazine belt to 0. Changed all child belts to `"rigid": false` so that the volume changes depending on how many bullets are in it.

#### Describe alternatives you've considered
Logically, the volume and weight of the belt _should_ be the sum of the bullets and linkages, but I couldn't figure out a good way to actually do that. To my surprise the game actually seems to do that on its own, at least for **weight** (but not for volume). I have no idea where in the code this is being done, but I'll take it a  win I guess 🤷; I still don't know how to make it work for volume.
500: 
image

250:
image

1:
image

#### Testing

edit: error 1 no longer occurs as of #58191
<details><summary>error 1 details</summary>

Went into the game and spawned some ammo belts. Everything (mostly) seems to work fine except for an **unrelated** error that pops up when you try to make an ammo belt by activating belt linkage items on the ground.
image

</details>

edit: error 2 no longer occurs as of #58625
<details><summary>error 2 details</summary>

Ok, hold on, I just ran into another error while writing this. to reproduce:
1. Wear a subject suit (my test character spawns in one)
2. spawn in and wear a high-volume rucksack
3. pickup 250 `5.56 NATO M855` and 250 `.223 ammo belt linkages`
4. (A)ctivate the belt linkages, creating an ammo belt with 250 charges
5. try to move
6. error:
image

Can be repeated as many times as you want by (U)nloading the belt and repeating steps 4 and 5.

It appears that the game puts the finished ammo belt in the subject suit pockets rather than the rucksack.
image
I'm not sure exactly how relevant this is to this PR; it could have something to do with me changing the volume of the base item, but the root of the problem seems to be in the logic of where items go when they are created from the `ammobelt` use_action maybe? Regardless, it's beyond me.

</details>

#### Additional context
The ammo belt class was originally given its weight an volume in #42509

Thanks a ton to mqrause for making #58191 and #58625 you're a legend. 😎

### CODE REVIEW

**Comment by mqrause** [comment]
> I'm not sure exactly how relevant this is to this PR; it could have something to do with me changing the volume of the base item, but the root of the problem seems to be in the logic of where items go when they are created from the `ammobelt` use_action maybe?

When you create a belt from linkage, it first gets put into your inventory empty and then starts a reload action. I only took a glance at the code, but the reload action should normally handle the belt getting too big/heavy, so no idea what goes wrong there.

**Comment by GuardianDll** [comment]
IIRC i got this error even without the belt changes, so i think its not related to your pr
Would be great if someone will test it on vanilla version tho

**Comment by catdach** [comment]
> IIRC i got this error even without the belt changes, so I think its not related to your pr Would be great if someone will test it on vanilla version tho

(I assume this is regarding the second error) I'm not sure. I assume this wouldn't happen without my changes to the volume of belts; if it was always at max volume like before, then the belt probably would never be placed in the smaller pocket to begin with. 

As mqrause said, the reload action code should probably be dealing with this. So I don't the problem itself is _because_ of this PR, but I'm not sure how it would possibly be replicated _without_ this PR.

**Comment by GuardianDll** [comment]
Oh wait, thats another error
image
so i dont really know what to do with it or how to fix it

**Comment by mqrause** [comment]
Did you check if it works (mostly) properly with #58191 merged?

**Comment by catdach** [comment]
> Did you check if it works (mostly) properly with #58191 merged?

yeah, error 2 still happens, but error 1 doesn't.

**Comment by mqrause** [comment]
Does this work properly now?

**Comment by catdach** [comment]
Thank-you so much, **error 2 is now fixed.** 🎉

Just one tiny thing, the game will now **incorrectly** say that the destination will be the subject suit: 
image
When the _actual_ destination is the high-volume rucksack (as it should be):
image

**Comment by mqrause** [comment]
I think that is simply the current location of the item you want to reload. It's the destination of the ammo, not the destination of the belt?
The empty belt gets spawned before reloading with ammo. And because the empty belt is small and the pocket system prefers the smallest possible pocket, it gets put into the subject suit first before being moved during reload because of the size increase.

**Comment by catdach** [comment]
understood, I guess this PR is finally ready to go then.

**Comment by mqrause** [comment]
You need to fix `cheap_ammo_pouch_belt223` and maybe other related ammo containers that were added in #58016 to fit the new belt volume/weight.

**Comment by Fris0uman** [comment]
The item density test seems to actually be failing due to the change in the ammo belts

**Comment by mqrause** [comment]
If I understand this right, the failing test is actually saying that the belts are _not_ broken anymore. Above the check there's a comment saying `// Failing? Just remove the relevant items from the known_bad list above` and it fails only if the item density is _not_ above the max allowed.

**Comment by catdach** [comment]
It still seems to be failing these tests. Am I doing this right?

**Comment by mqrause** [comment]
Yeah, the failures aren't your fault.

**Pull request merged**
