### PR TITLE
Hydration pack size fixes

### LINKED ISSUE #73508: Hydration Pack Volume Incorrect
### Describe the bug

Recently the hydration pack's volume changed from .01 L empty to 3.00 L empty, and expands to 6.00L when full. This prevents it from being placed within pockets specifically designed for it when full, such as the "pouch sized for a hydration pack." on the MOLLE assault pack. The Hydration Pack may not be the only item affected by whatever has changed, but it is the item that I noticed this on.

image
image
image

### Attach save file

N/A

### Steps to reproduce

1. Create new world with only Dark Days Ahead content pack
2. Spawn in Hydration pack
3. Observe volume when filled an unfilled

### Expected behavior

The hydration pack previously had a volume of .01 L empty and would expand to include the volume of the contained liquid up to its maximum.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3155 (23H2)
- Game Version: 00d3e82 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

_No response_

### LINKED ISSUE #73535: Hydration pack change 5/5/2024
### Describe the bug

The recent change to hydration packs from a hard container to a soft container have them no longer able to fit inside of hydration pack pockets in various backpacks when filled. Base size remains 3.01L when empty, but when filled with its capacity of 3L, size expands to 6L and the hydration pack no longer fits inside the hydration pack pocket. This causes the hydration pack to either migrate pockets to allow it to remain carried, or to fall to the ground if there is insufficient space on the character. 

### Attach save file

N/A

### Steps to reproduce

Put a hydration pack in a backpack with a hydration pack pocket.
move to a source of liquid and refill the hydration pack. 
hydration pack should move locations to the main pocket of the backpack or fall on the ground

### Expected behavior

hydration pack in a hydration pack pocket would remain in the pocket empty or filled. 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: eefe407 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TheAthenaCabin0**
#### Summary
"None"

#### Purpose of change
When hydration pack was changes from a rigid to a non-rigid container, its volume when empty was not changed accordingly, nor were the pockets in bags that contained it. Fixes #73508 , Fixes #73535 

#### Describe the solution
Changes size of hydration pack and associated container pockets built for hydration pack in json.

#### Describe alternatives you've considered
Reverting hydration pack to being rigid (not realistic), or changing its empty volume to 0.001 L (also not realistic, see Hyperseeker's notes on #73535 and #73508 for both alternatives). 

#### Testing
None

#### Additional context
Also edited a pocket in Xedra Evolved, as the issue would have persisted there as well.

### CODE REVIEW

**Comment by Hyperseeker** [comment]
It looks like you may have committed unrelated Magiclysm NPC dialogue changes with this PR.

**Comment by TheAthenaCabin0** [comment]
> It looks like you may have committed unrelated Magiclysm NPC dialogue changes with this PR.

Yes, it uh seems that I did. Should I close this PR and basically resubmit with those accidental commits gone?

**Comment by Hyperseeker** [comment]
> Should I close this PR and basically resubmit with those accidental commits gone?

That seems to be the pattern, from what PRs I've seen resubmitted.

**Comment by NetSysFire** [comment]
You can also just erase those commits and force push.

**Pull request closed without merging**
