### PR TITLE
Device to measure artifact resonance (lab loot)

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Content "XEDRA device to measure artifact resonance(loot only)"

#### Purpose of change
Someone pointed out to me that Artifacts.MD says we should be able to measure resonance of artifacts.
"The resonance factor of an artifact should be measurable, even if the other properties of the artifact are not, although at time of writing there is no way to do so."

#### Describe the solution
So, I made it possible to measure.

Added an item that has a new use_action "MEASURE_RESONANCE" (can be modded for cost, applied elsewhere, etc, but the function itself is hardcoded) and spawns only in places where you'd expect to find them - with a dead XEDRA kill team (rarely) or alongside lab artifact storage(uncommonly). It also consumes a staggering 5000 battery charges per use and cannot be plugged in, meaning that plutonium cells are the only fuel that works. It also does not give an exact readout, the resulting resonance value is fudged up to 15% higher or lower. You can re-scan an object to get a better idea of the true resonance value, but that costs even more precious plutonium cells...

#### Describe alternatives you've considered
I was thinking about making it a furniture which couldn't be moved (and still ate plutonium cells) but once I came up with a description for the item I liked it.

#### Testing
Game loads

Need to check: Can this be modded to take non-plutonium cells? (It probably shouldn't be possible)

#### Additional context
CC @anoobindisguise 

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/29673a99-fb4e-4eef-a89a-dac2e8df7c4d

### CODE REVIEW

**Comment by Rokharn** [comment]
Will this item spawn with batteries with random charge level like other tools? If so, that will mean a lot of free rare batteries.

**Comment by anoobindisguise** [comment]
I'm not sure if it should print exactly resonance and maybe have some documentation (using an esoteric measurement system like "1000 [lastnames]" in the naming style of Newton, Curie, etc) or maybe res/2000 as a percentage or something. Flat saying "you have 1500" may not have enough context but idk I'd have to look at it more. Thanks for doing this btw.

**Comment by RenechCDDA** [comment]
> I'm not sure if it should print exactly resonance

Randomized by +-15%.

>using an esoteric measurement system like "1000 [lastnames]" 

Yeah I went with "units" but I am open to suggestions. I explicitly didn't want to say "resonance **factor**" as that implies it is a multiplicative value.

**Comment by Rokharn** [comment]
> I am open to suggestions

Maybe something like: resonance more or less stable (numbers, maybe color like radiation badge too), resonance little unstable, unstable, deadly unstable. 
Where instability hints at "tiers" of effects.

**Comment by RenechCDDA** [comment]
> Will this item spawn with batteries with random charge level like other tools? If so, that will mean a lot of free rare batteries.

Hey late reply here but I just wanted to let you know these DO NOT spawn with a battery already inside them.

**Pull request merged**
