### PR TITLE
Mainline Dinos

### LINKED ISSUE #25294: Mod Inclusion Project: DinoMod
Use the following issue as a space to discuss the inclusion of:

Mod Ident: DinoMod
Name: DinoMod

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

Based on existing lore and [kevin's approval here](https://github.com/CleverRaven/Cataclysm-DDA/issues/25294#issuecomment-417912485), I think induction can work in a narrow/limited fashion.

- [ ] - Add (various or limited) dinosaur species as variants in special locations (e.g., lab specials, or other similar locations)

See discussion for other ideas.

### PR DESCRIPTION
**Pull request by LyleSY**
```SUMMARY: Content "Adds dinosaurs from DinoMod as a resource for the main game, minus egg laying."```

```Resolves #25294 - adds reweighted dinos without experimental egg laying and dino doo```  

```Considered adding eggs, hatchlings, and dino doo, but want those to be widely tested in the mod before bringing them in as a resource, considered including Titanis and Dimorphodon, but they aren't dinos so don't meet the intent of this project```

### CODE REVIEW

**Comment by I-am-Erk** [comment]
How do dinosaurs fit into the lore of the game?

**Comment by LyleSY** [comment]
They came across in the portals. I have some notes on this in the mod I should move over to main

**Comment by KorGgenT** [comment]
you'll need to run this through the web linter http://dev.narc.ro/cataclysm/format.html
and also add harvest entries for all your monsters

**Comment by ZhilkinSerg** [comment]
Marking as Stalled to clean up PR queue. Please ping me to get it reopened when you feel you can continue working on it.

**Pull request closed without merging**
