### PR TITLE
Vehicle sprites to show accumulated blood spatter

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Features "vehicle sprites to show accumulated blood spatter"

#### Purpose of change

The already fleshed out blood spatter system was only used in ASCII mode and vehicle inspection mode.  Why should tileset players miss out on all the excitement of spraying viscera onto your car?

This change introduces four new multitile metadata entries to tileset json files to allow vehicle sprites to render blood state.

#### Describe the solution

The tile drawing function asked the vehicle system for details on each part so it knows what to pass to the sprite drawing function.  This function used to collect only two states - Is the part open or broken?  I expanded this function to also collect information on how much blood is on the part.  It passes this information onto the sub-tile metadata so the tile drawing function can read whether or not the part has the multitile string, there are 4 new strings now for this.

    center
    corner
    edge
    t_connection
    end_piece
    unconnected
    open
    broken
    blooded_open -> for vehicle doors that get bloodied
    blooded_broken -> for vehicle parts that get broken and bloodied
    lightblood -> for any vehicle parts that get bloodied a little
    heavyblood -> for any vehicle parts that get bloodied a lot

The last 4 ids are only used for vehicle parts.  Since the subtitle id for the first 8 are unmodified, all existing multitile data should function as normally.

I created a tileset branch of UltiCa to test the blood sprite functionality, and will include a link at the bottom - it will be pushed to the main tileset repository in the event of this pr being merged.

https://imgur.com/a/zWHwC3Q
Video of bloodspatter in action.  Highly recommend watching to see how it works in action.

image

Extra sprites that I created :

blood tileset

In this initial tileset the blood is used as an overlay much like cracks and dents are.  More committed tileset creators can create more detailed blood parts if they want to.

#### Testing

I did a lot of hit-and-run testing in vehicles, and while the rest of the game looks normal...  This edits multitile functionality of tile sprites so I do need to do more testing to confirm all other multitile usage remains intact. ( Such as doors, building wall connections, and so on)

#### Additional context

Tilesets WILL have to all be updated as this will break any vehicle tiles that have blood and multitile json data using the current system.  They will display unbroken, if they are actually broken and bloodied. I have made a UltiCa revision that updates windshields, quarterpanels, panels and doors that will show blood parts.  The only other thing that is necessary for UltiCa tileset to be completed is for all other vehicle parts to add a blooded_broken multitile state.

The two changes all tileset creators would have to do at a minimum is ;

            Add a new multitile for all "open" vehicle sprites to also declare "blooded_open" with same value as "open"
            Add a new multitile for all "broken" vehicle sprites to also declare "blooded_broken" with same value as "broken"

Any blood sprite inclusion is optional for tilesets.  Only the above changes would be required for tilesets to function as normally without blood sprites.

This is the PR for the Ultica tileset that contains the blood sprites necessary for this pr to work ;

     https://github.com/I-am-Erk/CDDA-Tilesets/pull/630 

Any tileset system that uses the Ultica vehicle tileset style and naming as a base should have little difficulty copying the blood and jsons over to convert their tile system to get a working blood sprite set.

### CODE REVIEW

**Comment by esotericist** [comment]
this is entirely the wrong approach for this.

blood spatter needs to be handled with layered decals, not pointlessly multiplying the needed tile assets for every single vehicle part.

we also intended to move broken stuff to decals at some point, because the current approach is problematic and requires too many duplicate tiles. compounding an existing problematic implementation is not the answer.

**Comment by I-am-Erk** [comment]
Hope you're able to return to this at some point. This is definitely something we want, but the tileset implementation right now is deeply flawed and we definitely can't extend it with the current flaws. This might just have to wait until it gets fixed overall, unfortunately.

**Comment by vetall812** [comment]
> move broken stuff to decals

I'm disagree here with you. Broken stuff can be drawn as crumbled panel or a hole in the fabric wall or absent glass in the door. All this will require completely new sprite with additional transparency to show objects behind them.
So I think that current "broken" mechanics fits better then decals.

Decals will be ideal addition to the walls or furniture, but they have to be opaque as real decals )

**Comment by vetall812** [comment]
Blood or advertisement, or some army signs can be decals of course, but please don't "fix" broken mechanics. )

**Pull request closed without merging**
