### PR TITLE
[MoM] Add calorie cost for psionics

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Add calorie cost for psionics"

#### Purpose of change

One reason I originally wanted to use weariness for psionics is because I wanted psionics to be _work_. I'm happy with the way Drain works now and won't change it over even if weariness becomes available, but psionics being work means they should take more energy.

#### Describe the solution

Add a calorie cost to psionics. For using a power, the formula is (Difficulty * 5) * [random number between 0.3 and 1.7), and the cost for using a contemplation recipe is 5x that. This should not be enough to make using any particular power a difficult decision but puts more resource pressure on the player over time.

(Or would if food weren't basically infinite and free, but this PR is assuming that at some point that won't be true) 

#### Testing

Loaded game up, used some powers and debug-checked needs before and after, did some contemplation practice and debug-checked needs before and after. Stored kcal were reduced.

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
With this, could psionic powers be used as a new and improved weight loss program? I guess XXXXL characters have a new way to drop the weight and gain immense power at the same time.

**Comment by Standing-Storm** [comment]
Theoretically yes, though the amount of Drain they'd accumulate by trying to do so would probably make it more attractive to just get on the treadmill.

**Comment by Terrorforge** [comment]
This would lead to a psion's cardio trending higher than non-psions, which is in theory a buff since their powers are stamina-based and food is, as mentioned, not usually a problem.

However, given the size of the calorie consumption, I don't think it'll be ap roblem. I will be keeping an eye on it, though.

**Comment by Standing-Storm** [comment]
> This would lead to a psion's cardio trending higher than non-psions, which is in theory a buff since their powers are stamina-based and food is, as mentioned, not usually a problem.

I actually wonder if that's the case--the mechanism is by using an EoC to directly removed stored calories from the player, and I'm not sure if that counts as burning them for cardio purposes or not. Though if it does, as you say, it's pretty low so it shouldn't make a significant difference.

**Pull request merged**
