### PR TITLE
Adjust headlamp to match flashlight

### LINKED ISSUE #77394: The headlamp is severely under-powered compared to a real-life equivalent.
### Describe the bug

I tested it in game, and it runs out of batteries after a little over 23 minutes which makes it borderline unusable. It also accepts ultra-light batteries (2/2) which runs out immediately after you turn it on. 

The cheapest headlamp sold by US largest outdoor retailer (Recreational Equipment Incorporated) is advertised as having 6 hours burn-time at its highest setting.

high: 6 hours / 300 lumen (55 meters)
medium: 12 hours / 150 lumen (35 meters)
low: 140 hours / 6 lumen (8 meters)

Reference:

"Black Diamond Astro 300 Headlamp" costs $19.95 compared to $40 for the pre-apocalypse price of the in-game headlamp. It weighs 75 grams compared to in-game 520 grams. 

https://www.rei.com/product/202772/black-diamond-astro-300-headlamp

### Attach save file

N/A

### Steps to reproduce

Spawn a headlight and a light battery, load it and turn it on. Do the same with a very light battery.

### Expected behavior

I expect it to work for a couple of hours at the very least. 

Proposed solution: Make it take medium batteries (56/56).

According to [this site](https://integral-led.com/en/content/what-are-lumens) LEDs produce 80-152 lumen per watt, so a 300 lumen LED headlamp it should have a power consumption between 2-3.5 W. Does the json flag `LIGHT_300` stand for 300 lumen? 

If we say it's 3W and a medium battery is 56 kJ it should run for 3W / 56 kJ = 18666.66 seconds ~ 5.185 hours, which is close enough to the 6 hours expected.

We shouldn't need to specify power draw for LED sources, we can calculate it from lumen emitted and adjust it with json flags specifying conversion efficiency. 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.7428 (1607)
- Game Version: d515611 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary
Balance "Adjust headlamp to match flashlight"

#### Purpose of change

As we can make a headlamp using a flashlight and patches/strings/tape and you can disassemble a headlamp to get a flashlight, we should expect the headlamp to function exactly as a flashlight strapped to your head. 

Furthermore, the headlamp is borderline unusable and severely under-powered compared to a real life equivalent and only functions for 23 minutes with a light battery (or 1 second with a ultra-light battery). Fixes #77394. 

I believe the current discrepancy between the current flashlight and headlamp is because the listed specs for the reference flashlight is either a) straight up lying or b) use some different and incompatible metric for its brightness and/or burn time. 

Reference in-game flashlight: https://www.amazon.com/dp/B0CFLGMKQM?th=1
Reference headlamp: https://www.rei.com/product/202772/black-diamond-astro-300-headlamp

They both take 3xAAA batteries (corresponding to a medium battery), but the advertised performance is 1000 lm for 10 hours for the flashlight and 300 lm for 4-6 hours the headlamp.

> 1996, white LEDs' luminous efficacy has increased from 5 lm/W to today's commercial white LED of 150 lm/W, the highest luminous efficacy of all white light sources. The theoretical limit for white LEDs is about 260-300 lm/W.

https://phys.org/news/2010-08-white-super-high-luminous-efficacy.html

At the maximum theoretical efficiency of 300 lm/W, to shine at a brightness of 1000 lumen for 10 hours would take 120 kJ of energy, and the medium battery is only 56 kJ.

The in-game power draw is 1560 mW and a 150 lm/W luminous efficacy it would produce 234 lumen for the duration of 56 kJ / 1560 mW = 10 hours, which seems very close to the 300 lumen for 6 hours from the reference headlamp's spec.

Running a 56 kJ battery 6 hours at an efficiency of 150 lumen / W would produce [389 lumen](https://www.wolframalpha.com/input?i=56+kJ+%2F+6+hours+*+150+lumen+%2F+W+in+lumen). 

I think they are close enough that we can consider a flashlight strapped to your head and a headlamp functionally the same item. 

#### Describe the solution

Json edits to headlamp to match flashlight.

#### Describe alternatives you've considered

Make the recipes into a makeshift headlamp and create new a new item for a commercial headlamp. But as they would be so similar I don't think adding another item would achieve that much.

### CODE REVIEW

**Comment by ampersand55** [comment]
As I changed the headlight to use a medium battery like the flashlight instead of light battery, tests fail when a helper function tries to load headlamp with a light battery. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/a61a138db755925c5e7006d30fba162e03467903/tests/map_helpers.cpp#L207-L215

**Comment by ampersand55** [comment]
This should now be ready for merging. 

I limited the scope of this to just adjusting the headlamp, I made it accept a light battery specifically to pass the tests. 

Headlamp should really have the same battery slot as flashlight. A version with battery and the tests fixed should be previous commit at HEAD https://github.com/CleverRaven/Cataclysm-DDA/pull/77461/commits/b0324d13be43c4754887255ae9316dc43f1fbe2a

**Comment by Termineitor244** [comment]
Did you not adjust the heavy-duty headlamp too? It uses light batteries too.

**Comment by ampersand55** [comment]
My idea for the heavy headlamp includes some changes to the heavy flashlight too (which is part of the recipe of the heavy headlamp). I have that branch mostly ready and I'll make a separate PR if this one gets merged/accepted. 

The heavy-duty headlamp is made from a heavy flashlight, which has an internal 48 kJ battery that can't be changed. It's based on this item:

https://www.amazon.com/dp/B00Y8AHZYC

Which is kind of silly to strap to your head as it weighs 720 g and has a volume of 4267 ml.

**Comment by kevingranade** [comment]
Remove battery light from the headlamp, fix the test.

**Comment by ampersand55** [comment]
I can't figure out why the tests fail. I need help with fixing the tests.

**Comment by Night-Pryanik** [comment]
There's `Urban Explorer` profession which has `wearable_light` with corresponding `light_battery_cell` which the game tries to put inside.

**Comment by ampersand55** [comment]
The failed test is unrelated to this PR.

**Pull request merged**
