### PR TITLE
Fixed Remington ACR .223 description

### PR DESCRIPTION
**Pull request by ProjectileWaterfowl**
#### Summary

Bugfixes "Previous description was a copy of that of the MK 18 CQBR, which is definitely not right. Copied the description from the .300 blackout variant minus the .300 blackout part."

#### Purpose of change

The description was wrong. The change fixes this.

#### Describe the solution

Changed the description.

#### Describe alternatives you've considered

Leaving the description incorrect.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Old description:
`This carbine was developed for military use in the early 21st century.  It is damaging and accurate, though its rate of fire is a bit slower than competing .223 carbines.`

**Comment by ProjectileWaterfowl** [comment]
I almost entirely have no idea what I'm doing, so I wasn't expecting the later commits I made to my fork to do shit with the PR.

**Comment by Night-Pryanik** [comment]
If you don't know how to clean commit history, I suggest you to close this PR and open a new one, with only the right changes.

**Comment by ProjectileWaterfowl** [comment]
Will do.

**Pull request closed without merging**
