### PR TITLE
[CR] Workaround to Automatic Turrets don't shoot at things from inside vehicle without LOS

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Workaround/bugfix to Automatic Turrets don't shoot at things from inside vehicle without LOS

Additionally icreased turret autofire detection range from 12 to 16 tiles similar to milspec turret (Leadworks LLC's T-4A1 Sentry). It is just small bonus to bugfix and if mil spec turret can shoot there with its ai then why our turret can't?

After that autoturrets will work on everything including fresh spawned APCs. Curtains and frames no longer will prevent your turrets ai from autofire.

#### Summary

SUMMARY: Bugfix "Automatic Turrets don't shoot at things from inside vehicle without LOS"

#### Purpose of change

https://github.com/CleverRaven/Cataclysm-DDA/issues/19730

#### Describe the solution

Solution itself is pretty simple - if turrent can't find the target than let's check if it able to fire from various  postions on vehicle boundaries and if now able- shot from there (safety for avoding shooting player included). This way LOS problems for vehicle autoturrets will be bypassed. 
Max range for this shots is reduced on distance from actual turret position.

Yes it basically hack but it will produce expected results. Later proper 3D FOV calculation for turrets on roof  can be done but probably after finishing z-levels and 3d fov.

#### Describe alternatives you've considered

Alternative solution is proper 3D check. But there is problem - 3D FOV and z-levels still considered unstable and using it for autoturrets only despite of user world settings sounds problematic and may produce unexpected results.

Also there is can be FOV hack that bypassing frames and curtains. But it it much harder and probably not worth it since with that you will be messing with FOV calculation itself.

#### Additional context

After that autoturrets will work on everything including fresh spawned APCs. Curtains and frames no longer will prevent your turrets from autofire.

Solution somewhat messing with target prioritization. Target priritizaion still working but it's effect may be restricted to one direction. 
But it is enables only (mostly) then turret can't see target at all. So it is better to get your turret shooting at something than getting turret that completely ignoring all targets because of LOS problem.

### CODE REVIEW

**Comment by kevingranade** [comment]
You can calculate what tile is on the edge of the vehicle and on a line between the turret and the target, no need to sample.
```
std::vector<tripoint> path_to_target = line_to( turret_pos, target_pos );
while( !( const optional_vpart_position vp = g->m.veh_at( path_to_target.back() ) ) ||
       vp->vehicle() != this->vehicle() ) {
    path_to_target.pop_back();
}
```
Once this loop exits, ``path_to_target.back()`` is the closest point on the vehicle to the target on the line from the turret and the target.  It's guaranteed to terminate as long as the turret itself is on the current vehicle.

**Comment by Firestorm01X2** [comment]
>You can calculate what tile is on the edge of the vehicle and on a line between the turret and the target, no need to sample.

There is problem - turret can't detect if there is target at all- it doesn't see it becasuse af blocked LOS. So I don't know there is target all. Or if any present.

Look at:
`Creature *auto_target = cpu.auto_find_hostile_target( range, boo_hoo, area );`
This thing simply can't see target becuse of cpu LOS is blocked. That is why I need sampling to at least detect it.

**Comment by Firestorm01X2** [comment]
LOS problem still will be there. In auto_find_hostile_target. How should ilI avoid the fact that frames blocking LOS from the turret position?

**Comment by Firestorm01X2** [comment]
Wait now I've got it. There is check visibility for target. So I can hack it by ckecking sees from veh boundary tile.

**Comment by Firestorm01X2** [comment]
I think it is better to start over.

**Pull request closed without merging**
