### PR TITLE
Electric engines won't fail to start

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Bugfixes "Electric engines won't fail to start"```

#### Purpose of change
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/32439

### CODE REVIEW

**Comment by ProfoundDarkness** [comment]
I've posted on my fork (referenced above) an alternate solution to issue #32439 which I find far more acceptable than what this does.  If my alternative is more acceptable then I can go ahead and PR it.  I have a feeling an additional PR addressing the same issue might add to much noise to the PRs though if I should have actually submitted a PR I'd love to hear about it.

Quite frankly from an IRL perspective and a game perspective this particular PR doesn't sit well for me.  From an IRL perspective electronics CAN work when damaged but when they fail they tend to fail spectacularly.  The alternate approach encapsulates both this spectacular failure and the discussion in #32439 which is paraphrased as an electric motor either starts or it's already completely broken.  It also maintains risk in trying to use something that is banged up.

Also I've been goofing around with the concept of adding critical failures to engines for a little bit and this is kind of a critical failure light applied only to electric engines.  An example critical failure is if anyone has ever tried to troubleshoot a dead short.  Maybe deciding to bypass things like safety of a fuse for a little bit of metal... maybe resulting in an electrical fire in the car shortly after turning the key...  (Not describing things I've done, more second hand distilled stories plus things I've witnessed.)

**Comment by l29ah** [comment]
Looks interesting. Your sound notification should reflect the spectacular failure of the engine though. And in fact i'd prefer it not to destroy itself by chance when you start it, but have a damage threshold.
Also, it seems like an electric engine consumes a lot of power when it is stopped, this should be taken care of too someday.

**Comment by ProfoundDarkness** [comment]
Yeah... I didn't get any sound notifications in the event log (not even in code from before the change) or I'd have played with that some more first.

As for the extra power drain... that's something I wanted to look into, specifically for electric motor (critical) failure, with a side of high chance for starting a fire.

**Comment by ZhilkinSerg** [comment]
Bugfix -> Bugfixes

**Pull request merged**
