### PR TITLE
Recharge sulfur powder and make it not a comestible

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
bugfixes "sulfur is treated like a chem rather than a comestible"

#### Purpose of change
Sulfur powder was caught by the automated changeover of charge removal from comestibles. This is probably in error because it was not applied to most of the other chem items, but sulfur was a comestible specifically because you could rub it on your skin to cure a fungal infection. It probably should not work that way.

#### Describe the solution
This makes it an ammo and not a comestible. This causes an error as existing sulfurs become sulfur (active) which errors on load, I don't know how to fix this. Future sulfurs will not have the issue though. Sulfur should not be tracking temperature and doing all the other things a comestible does, it's needless overhead on the game. It also obviously removes its status as a high grade fungicide with no health penalty.

#### Describe alternatives you've considered
I get that we're trying to move away from charges but sulfur frequently spawns in the thousands (and breaking up a single chunk of sulphur makes 1500+ individual sulfurs) so it is a particularly egregious case that can probably be left for de charging after we fix some more of the underlying issues with charges that affect comestibles.

#### Testing
Works in game but has the abovementioned errors.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Are those errors skippable or crash?

**Comment by mqrause** [comment]
> This causes an error as existing sulfurs become sulfur (active) which errors on load, I don't know how to fix this. Future sulfurs will not have the issue though.

You probably just need to add it to `obsoletion/blacklist_temperature_removal.json`.

Also considering sulfur is one of the cases from #67324, is it possible to rebalance the charge amount and size in a sensible way to avoid the same issue once ammo gets their charges removed?

**Comment by anoobindisguise** [comment]
> > This causes an error as existing sulfurs become sulfur (active) which errors on load, I don't know how to fix this. Future sulfurs will not have the issue though.
> 
> You probably just need to add it to `obsoletion/blacklist_temperature_removal.json`.
> 
> Also considering sulfur is one of the cases from #67324, is it possible to rebalance the charge amount and size in a sensible way to avoid the same issue once ammo gets their charges removed?

Chemicals are measured as 1/100th mol per charge so unless that paradigm changes probably not.

**Comment by mqrause** [comment]
> Chemicals are measured as 1/100th mol per charge so unless that paradigm changes probably not.

Huh, I didn't know that. But that'll probably mean a lot of the chemicals will break when ammo charges get removed, so we need to figure something out for that at some point.

**Comment by PatrikLundell** [comment]
There is probably a need for a system for powders and liquids that tracks how large one lot of it is, regardless of whether you call it charges or anything else (and powders should probably require containers or be spilled. Spills should probably be partially recoverable into containers at some point).

**Pull request merged**
