### PR TITLE
fix npc background conversation

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
Bugfixes "More background stories: actually access them"

#### Purpose of change
I believe content from #53894 and alike was inaccessible. So I am trying to fix that.

#### Describe the solution
Move it all to one file to not overlap `id`: `TALK_FRIEND_CONVERSATION`

#### Describe alternatives you've considered
Don't define new `BG_OTHER_SURVIVORS_STORY`, just use the old `BG_SURVIVAL_STORY`

#### Testing
[copy-from-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13262113/copy-from-trimmed.tar.gz)

1. Load save (before and after this change).
2. Talk to nearby NPC. `C t`
3. Ask them about their history. `e a a`

Warning: don't save, as when NPC tells the confused story, they become confused and will not talk about chef stuff in new version (unless confused is removed in debug menu via mutating)

After: Chef story
image

Before: Confused story, which is a catchall, when something doesn't work
image

NOT TESTED:
Can NPC with the background spawn?

#### Additional context
If somebody tested it more it would be nice.

### CODE REVIEW

**Comment by Brambor** [comment]
I finally realized I moved content from mod to basegame. It wouldn't activate without the mod, but still it is undesired...

**Comment by Brambor** [comment]
I now removed the Aftershock changes.

Is Aftershock supposed to replace the `TALK_FRIEND_CONVERSATION` with its own instead of extending it?

**Comment by Brambor** [comment]
Required tests passed, not restarting to not waste GitHub CPU.

**Comment by Maleclypse** [comment]
> I now removed the Aftershock changes.
> 
> Is Aftershock supposed to replace the `TALK_FRIEND_CONVERSATION` with its own instead of extending it?

Long term yes.

**Pull request merged**
