### PR TITLE
Robots are immune to cold, not "cold blooded" creatures

### LINKED ISSUE #38525: Magiclysm - Cold damage type spells will not damage creatures lacking WARM flag.
Cold damage spells such as ice spike, will not do damage to any monster without the 'WARM' flag, this includes things like rattlesnakes, giant roaches, and eyebots. Spell damage will 'reflect' off the monster's hide regardless of damage amount.

# Expected behavior

Cold spells should be intense cold and damage anything and everything.

# Screenshots

# Versions and configuration

# Additional context

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Robots are immune to cold"```

#### Purpose of change
Fixes #38525 

#### Describe the solution
Add COLDPROOF flag
Replace check for WARM flag with check for COLDPROOF flag
Give COLDPROOF flag to robots and turrets

#### Testing
image
Cast against a police bot and do no damage

### CODE REVIEW

**Comment by foulman** [comment]
I agree that it might be better off JSONized in some way, as this still leaves an issue where, if we are saying electronic creatures don't take damage from cold spells, they are still able to take damage from cold melee and ranged attacks using { "damage_type": "cold", "amount": 50 } for example, which was tested until the WARM flag was found as the culprit. 
Perhaps they should have cold armor of a certain value? I'm not even sure that's possible rn.
Either way, good work and quick response!

**Comment by KorGgenT** [comment]
yeah it seems kinda weird to make a blanket statement like "all robots are immune to cold" though it does make sense. probably a better way of doing it is making a new monster flag that grants cold immunity and just applying those to appropriate monsters

**Comment by Funguss** [comment]
https://gesrepair.com/how-cold-weather-affects-electronics/

Some key points:

"if it gets too cold, certain components can suffer sudden failure. For instance, LCD screens contain fluid and at extreme temperatures can freeze. (...) any electronics that rely on movement such as motors, disk drives, servo valves etc., can suffer failure from the cold. As the temperature drops, metal contracts making moving parts run under higher load stress which can cause the part to fail."

https://motioncontrolsrobotics.com/how-cold-can-my-robot-go/

"FANUC manual, you will see that an LR Mate robot, the smallest in FANUC’s industry leading stable of robots,  is rated for use in temperatures from 0 to 45 degrees C, or 32 F to 113 F."

https://www.robotics.org/content-detail.cfm/Industrial-Robotics-Industry-Insights/Robots-to-Extremes/content_id/7701

"After searching the market, Albertsons chose the KUKA KR QUANTEC PA Arctic robot. The five-axis robot performs palletizing tasks quickly and precisely even in ice cold temperatures as low as -30°C. Thanks to the Arctic design, it needs no protective suit."

So, to handle below freezing temperatures requires engineering or other protective methods, generally speaking. The biggest issue seems to be that fluids are liable to freezing and lithium batteries will suffer plating, fail to charge and become fragile. Given that, and that other sensitive or heavy load parts may break due to a snap chill, it seems reasonable that robots would only be immune if they were specifically designed to withstand that kind of attack.

I'm wondering if the immunity was originally meant for nether creatures like the flaming eye and it was based on an off the cuff assumption as to what the flag meant?

I'd take from this

**Comment by KorGgenT** [comment]
i think we may be able to come back to it and have resistance numbers for cold and other damage types like how we have for fire and acid.

**Pull request merged**
