### PR TITLE
Lua mods ported to C++: Speedydex, stats through kills

### PR DESCRIPTION
**Pull request by DoctorGoat**
Any testing would be appreciated. 

Balance is currently somewhat questionable as the player is allowed to set whatever they want. Stats through kills is allowing the player to add stats with a new keybinding, eliminating the need for an anti-oops menu,

### CODE REVIEW

**Comment by BevapDin** [comment]
Please don't style random parts of the source, that have nothing to do with your changes.

Currently this PR shows as having touched about 1,800 lines, that are far too many.

**Comment by DoctorGoat** [comment]
yeah, I just ran astyle on the files that I had worked on. I'll refactor later tonight more carefully.

**Comment by DoctorGoat** [comment]
ffs i'll reopen it when i rework it

**Comment by Clyybber** [comment]
Seems to be good now.

**Comment by DoctorGoat** [comment]
Kevin let me know on Discord last night that mods can actually toggle options on/off, so I'm going to be rewriting to use that functionality.

**Pull request closed without merging**
