### PR TITLE
Prevent necropolis from spawning

### LINKED ISSUE #44336: No items spawning in upper floor of the Vault
# Describe the bug

The Vault has items on the lower floor but none at all on the upper floor. 

# Steps To Reproduce

1. Debug reveal map.
2. Find a necropolis.
3. Teleport to the first floor of the vault, observe that there is no items whatsoever.
4. Teleport to the lower floor, observe that items spawn normally. 

# Expected behavior

There should be items on the top floor of the vault just like it is on the lower floor.
It makes no sense for the first floor to be completely devoid of items while the bottom floor has a normal item spawn rate.

# Versions and configuration

 - OS:  Windows 10
 - Game Version: 0.E-6131-gdba2207, experimental build 11023
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Content "Disable the necropolis"

#### Purpose of change
Closes #44336 and #52523 by invalidating them

#### Describe the solution
Set the occurrences for the necropolis to zero.

#### Describe alternatives you've considered
Not being a smartass about this and actually taking a stab at fixing the thing, but... it's big and I don't wanna.

#### Testing
N/A

#### Additional context
This feels like a bit of a smartass solution to the issues mentioned above. Sort of "throwing the baby out with the bathwater", I suppose. But to be blunt, the necropolis as it stands is huge and unwieldy. Mapgen technology has advanced quite a bit since this special was built. We have things like nested mapgen now. This special is aching for an overhaul, but until someone steps up to the plate, the structure we have is outdated, broken, and feels somewhat out of place considering lore developments.

### CODE REVIEW

**Comment by Inglonias** [comment]
I want to be clear that I don't dislike the concept of the necropolis. I just don't think that in its current form, it should exist in an un-modded game.

**Comment by anothersimulacrum** [comment]
I don't think this is the right solution, it prevents accessing the second half of the old gaurd quest line. Not that that is particularly great, but it could be made at least a little cleaner. If we're going to lemove this, we should just commit to it and delete it, and redirect the content that it has related to it.

**Comment by PatrikLundell** [comment]
I believe there's a connection to #57030 here.

**Review by I-am-Erk — CHANGES_REQUESTED** [review]
Yeah, this can't be done in these steps... The missions need to be disabled first, then the spawning. And all these things should be moved to a mod so people can still explore the necropolis.

**Comment by Inglonias** [comment]
Based on the feedback I'm seeing, this is probably a bad solution to this issue, so I'll close this for now. If I get bored, I'll work on the changes that erk mentioned, but as I type this, I'm feeling a little lazy for that.

**Pull request closed without merging**
