### PR TITLE
Update dinosuar butcher yields [Dino Mod]

### PR DESCRIPTION
**Pull request by Reclusive-reptile**
Dinosuars are no longer immune to the American diet of corn syrup and potato chips. Now all dinos larger than small in size yield fat when butchered.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Dinomod may be obsoleted.

**Comment by Reclusive-reptile** [comment]
That makes me sad.

**Comment by codemime** [comment]
> That makes me sad.

That doesn't mean it will be removed, though. That means it will not be maintained by the main devs, and someone else has to keep it loadable an up-to-date.

**Comment by DangerNoodle** [comment]
> That doesn't mean it will be removed, though. That means it will not be maintained by the main devs, and someone else has to keep it loadable an up-to-date.

Is that not what the pull request is intended to do?

**Comment by codemime** [comment]
> Is that not what the pull request is intended to do?

Yes, it is. It would be great if you could maintain the mod on a regular basis. As the core game evolves, mods need to be updated accordingly to be working properly. That's where maintenance the most appreciated.

**Comment by DangerNoodle** [comment]
That ideally should also be mitigated by way of the person changing a feature to double-check mods.

**Comment by codemime** [comment]
> That ideally should also be mitigated by way of the person changing a feature to double-check mods.

We do (or, at least, we try to) check mods before applying changes (using `--check-mods` key), but now it concerns only not-obsoleted mods.

**Comment by DangerNoodle** [comment]
Then ideally the current mods should not be obsoleted, as doing so makes error-checking less effective.

**Comment by mugling** [comment]
> That ideally should also be mitigated by way of the person changing a feature to double-check mods.

This brings us directly back to the 3 people maintaining 48 mods problem that I outlined in #19124. No amount of opinion posts are going to change the simple truth that we don't have the resources to continue in this manner.

**Comment by DangerNoodle** [comment]
That sounds like a problem that has more severe consequences than just mod maintenance.

**Comment by mugling** [comment]
Yes, the project is in danger of stalling and this has also be noted by other developers (#19124, #19197). Nods to @codemime lurking above - you presumably guessed correctly that you were the third.

**Comment by DangerNoodle** [comment]
And my apologies, as I do not know if I will be able to contribute regularly.

**Comment by mugling** [comment]
Small contributions are always welcome - those aren't the problem. We need to change some of our working practices to account for the fact that we have relatively few active developers.

**Comment by DangerNoodle** [comment]
Understood. And I do not know what policies or methods are best to attract more contributors capable of and willing to hep with maintenance.

**Comment by codemime** [comment]
@mugling Thank you for this.

**Comment by mugling** [comment]
We need to make progress on a new stable release before the end of the year. @codemime you may want to check your email

**Pull request merged**
