### PR TITLE
backport #75444

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Backport #75444

### CODE REVIEW

**Comment by kevingranade** [comment]
This is entirely too much change for me to call it trivially safe,  and the bug it adresses isn't isn't a game-breaking one, so I'm not inclined to backport.

Leaving open because other people that work with this kind of dialogue/eoc stuff more than me might go "no this is all totally safe".

**Comment by GuardianDll** [comment]
i can say "no this is all totally safe" but i am the one who made both prs, so it's kinda wrong
but what i should say is that this PR do not uses any syntax that was added post diverge

**Comment by Maleclypse** [comment]
If I pull this PR locally and compile it will I be testing
The appropriate version?  I assume so but want to confirm.

**Comment by GuardianDll** [comment]
yes, you don't even need to compile
tho don't know where you can find any of this npcs to test, also you would need to make character have negative balance if you want to reproduce the #75433

**Comment by Maleclypse** [comment]
Tested and works.

**Pull request merged**
