### PR TITLE
Fix Reciprocating Saw

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Changes qualities of reciprocating saw"

#### Purpose of change

The reciprocating saw was previously metal sawing and wood sawing 2, but was changed to a quality of "1" for "realism" purposes. ~~Sawing with these is much faster than with handtools,~~ Sawing with these are on par with wood/metal saws, and so it should be such in game. It also allows it to be able to cut metal bars, saw off stocks and barrels. It's not the same level of sawing as a multitool.

#### Describe the solution

Makes the qualities higher.

#### Describe alternatives you've considered

None

#### Testing

Tested locally, works fine

### CODE REVIEW

**Comment by Zireael07** [comment]
Quality has nothing to do with how fast we craft, though.

(Adding some speed factors has been long discussed but never materialized yet)

**Comment by Paprika-H** [comment]
> Quality has nothing to do with how fast we craft, though.
> 
> (Adding some speed factors has been long discussed but never materialized yet)

Yes, but the saws can still be used to cut metal (window bars, etc) and vehicle work, while before, it could not.

**Comment by harperers** [comment]
I'm almost certain that the low qualities on this tool is intentional.

**Comment by Paprika-H** [comment]
> I'm almost certain that the low qualities on this tool is intentional. And as was said earlier, tool quality shouldn't have anything to do with crafting times.

It was intentional, but it's a pretty crappy excuse, being "realism", despite a reciprocating saw being at least on par with a wood/hacksaw. #57239. And yes, I know, it was bad wording. But with a higher tool quality it's able to cut metal and be used in vehicle work.

**Comment by Zireael07** [comment]
@Paprika-H: Tbh I see no reasoning in that PR. I agree with the other changes (removing use actions) that PR made but a change to tool quality is imho undeeded

**Comment by Fris0uman** [comment]
So what thing the saw can't cut in game that it can cut irl?

**Comment by Paprika-H** [comment]
> So what thing the saw can't cut in game that it can cut irl?

Metal bars, removing vehicle parts, gun stocks, gun barrels, tree trunks into planks. With a level 1 sawing, you're very much limited to a few crafts, while IRL you could 100% use a reciprocating saw to cut metal apart.

**Pull request merged**
