### PR TITLE
Add Giant Novelty Backpack item.

### PR DESCRIPTION
**Pull request by Gabe-Lincoln**
I just thought it would be funny to have a giant novelty backpack with huge storage and encumbrance.

It'll appear in some places where a normal backpack would appear 1% of the time.

Edit: Yes, I know that it's not actually appearing anywhere in game right now. I'm just a github noob. I have a version of the item_groups file that makes it appear, but it's not in this PR and I can't figure out how to add it.

### CODE REVIEW

**Comment by cainiaowu** [comment]
Joke items should be in mods, that is what I have been told.

**Comment by ZhilkinSerg** [comment]
Yeah, better put it to Crazy Cataclysm.

**Comment by sfsworms** [comment]
Do you have a real-world exemple? This is very huge, bigger than a duffel bag even.

**Comment by ZhilkinSerg** [comment]
It as a joke item, but it really exists:

https://www.google.com/search?ie=UTF-8&q=Giant Novelty Backpack

**Comment by kevingranade** [comment]
Bump encumbrance up to 100, if this is supposed to be the version that reaches to the ground, add leg encumbrance.

**Pull request merged**
