### PR TITLE
Overhaul mod support (part 1)

### PR DESCRIPTION
**Pull request by mugling**
The mod loading code is very ugly. This PR starts work on cleanup and is a prerequisite for completing #18861 (that PR will allow total conversion mods).

### Validation

The mod loading code does a very bad job of validating the input from `modinfo.json` and indeed it is possible to segfault or stall the game using bad input. I'm still looking into the cause but given the excessive use of pointers undefined behavior is a candidate

Also a lot of the mods packaged with the game have invalid fields within their `modinfo.json`, for example `mod_type` instead of `mod-type`. The obvious solution is to require linting of `modinfo.json`. This requirement is **not** extended to other mod content.

### Code cleanup

Lots of refactoring, especially in `mod_manager::load_modfile` and `mod_ui::get_information`. The next PR in this series will start to convert pointers to references.

### Obsolete mods

Completes the previously unfinished support for marking mods as `obsolete` so that they are still usable for old savegames but new worlds cannot be created using them. The `no_faults` mod is provided as an example (the mod itself is now superfluous as it was originally implemented before the mending UI was written).

### Default mods

The codebase already had the ability to mark some mods as default. This PR adds @Coolthulhu's `no_npc_food` mod to that list as practically everyone will want it. We could/should make much more use of this functionality when developing new features in the future.

### Replacement mods

Previously you could deprecate a mod and remove it from a savegame. This has been extended to allow replacement with an alternative. In this PR the `no_energy_weapons` and `no_powered_armor` are replaced with `no_scifi`.

### Maintainers

You can now add maintainers to a mod in addition to authors. Names are updated to the form used on github. I've been very conservative in adding maintainers so if anyone wants to step forward that would be welcome.

### Future work

* Mod versioning
* Registering known conflicts between mods
* Total conversion mods (replace all game items)

Most of the line count is JSON linting, the important changes are all C++. There is a **lot** of scope for improving the mod loading code so please only comments about bugs as opposed to stylistic improvements in adjacent legacy code.

#19037 (and probably 18922) should take precedence and this PR will be rebased after it.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
I have already implemented "authors" [ "DeadLeaves" ] in my DeadLeaves Fictional Weapons overhaul PR. Could you remove it from this PR?

**Comment by mugling** [comment]
> I have already implemented "authors" [ "DeadLeaves" ] in my DeadLeaves Fictional Weapons overhaul PR. Could you remove it from this PR?

I'm not sure if I understand your reasoning there?

**Comment by BorkBorkGoesTheCode** [comment]
I already changed the author line to "authors": [ "DeadLeaves" ] in #18922

**Comment by mugling** [comment]
@BorkBorkGoesTheCode I don't think you understand version control completely - it doesn't matter that the change is in both files.

**Comment by Coolthulhu** [comment]
Something is not right. I'm not sure if it's this PR, but it looks to be the most likely.

When I start the game, it doesn't redraw the screen until I do something, like press "escape" 3 times.
This sounds really weird and like it was caused by the recent main menu rework, but it worked fine back then.
The only good explanation I can come up with is that some change to mod system verifies the mods (or just core?) at start, causing a debugmsg, which can't be displayed because display isn't initialized yet.
There is that mon_null warning and it could be it.

**Comment by mugling** [comment]
Yes, I've seen that before but I'm not sure about the cause. Adding new JSON data appears to trigger it (probably #18922). The stack trace is useless.

I'm going to go with some tactical `printf`

**Comment by mugling** [comment]
Found it - it's to do with whether `modinfo.json` is an array or an object. It shouldn't matter but it does. You can sometimes trigger it before this PR.

I'm going to continue reworking mod code. Can you do a repeat merge test so I can both verify it's not platform dependent and once it's merged continue with further refactoring of the mod code?

**Comment by Coolthulhu** [comment]
I'm still getting that weird wait at start thing.
Though it may not be caused here.
I can't attach a debugger now because I built release (debug takes ages here). Is there a way to build release without stripping function names?

**Comment by mugling** [comment]
The debugger wasn't helpful in any case. Can you add some `printf`. Specifically in `mod_manager::load_mod_info` and `mod_manager::load_modfile`

**Comment by Coolthulhu** [comment]
OK, got it:
It is caused by invalid files in mod directory.
It happens somewhere in `game` constructor.
Can be triggered by intentionally tampering with `modinfo.json`.

Would be good if it didn't clear the screen, so that this message could actually be read.

**Comment by mugling** [comment]
Makes sense. Any idea where in `game::game`?

**Comment by Coolthulhu** [comment]
It's `read_from_file` in `cata_utility.cpp`. It uses `popup` function, which doesn't work well in that context. Replacing it with `debugmsg` makes it work.

**Comment by mugling** [comment]
Ok I'll push that now. Incidentally what message are you getting?

**Comment by Coolthulhu** [comment]
The message was caused by git leaving `.orig` files after merge (for some reason the game tried to read those).

**Comment by mugling** [comment]
Can you open an issue tagged 'mods' assigned to me about that

**Comment by mugling** [comment]
Fixed in 8ce776f

**Pull request merged**
