### PR TITLE
Reverse the nerfing of survivor machete

### PR DESCRIPTION
**Pull request by jkoudys**
Its cutting damage was reduced all the way down to 18, which is ironically even _lower_ than the standard machete's 20. I know that it has some more techniques, but it's silly for a weapon which is specifically "customized and rebalanced to improve its performance as a weapon" to actually do _less_ damage than before, and even have a higher moves per attack.

It wasn't even overpowered to begin with, given the high fab 6 melee 5 requirement to make one. I'm frequently at broadswords/katanas long before this becomes available.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It was also clearly outclassing all comparable weapons despite being just a rebalanced machete with a bunch of tape on it. That's why it got nerfed so hard.

Even at its current stats it has better damage output than a warhammer. After your buff, it would be comparable to diamond machete and better than any of: broadsword, katana, rapier and diamond zweihander.

If you want to bump its damage, also delete the "RAPID" technique, so that it doesn't go back to being better than dedicated forged melee weapons that take a forge and a book to produce.

**Comment by chaosvolt** [comment]
Hmm. It is a bit odd that it has less damage than the standard machete, admittedly. It would make sense if it was a tad ad-hoc like the makeshift machete.

I'm not sure how best to rebalance it though. I'm assuming that the best logic would be to make its damage-per-turn slightly above that of the standard machete, but not by enough to push it up to "weapon of war" levels.

**Comment by chaosvolt** [comment]
Um. Wait. Small issue here. Turns out that base damage-per-move is lower for the survivor machete, because for some reason it has 5 volume to the normal machete's 4. So step 3: fix the volume. :V

**Comment by Rivet-the-Zombie** [comment]
It definitely shouldn't be gaining volume like that.

**Comment by chaosvolt** [comment]
Aye. Additionally, the item could potentially do with a little more lightening, enough to make the DPT different closer to half a point, or even a whole point.

**Comment by jkoudys** [comment]
That sounds like a good approach to balancing it. I picture it as similar
to the combat chainsaw -- optimized for combat, so it should be noticeably
slimmed down, not bulked up
.

**Comment by vache** [comment]
I have a question.  What exactly is a survivor machete?  Can someone explain how taking this https://productimages.knife-depot.com/1c/392167.jpg and using a hammer, hacksaw, soldering iron and duct tape somehow make it a much better weapon?

**Comment by chaosvolt** [comment]
I can only assume it's mostly removing sections to lighten it and change the point of balance.

But with a blade that's meant to serve its purpose by being point-heavy, this is a bad thing if you want a good chopper. I assume the survivor is basically trying to make it an ersatz falchion, and presumably shifting the point of balance farther towards the hilt.

So while it might be plausible for it to have more cutting damage, be lighter, and maybe even gain a point of to-hit, it needs to have less bash damage than the regular machete, and absolutely shouldn't have rapid attack. As it is, survivor machete is already way better than regular machete. The guy running this PR likely didn't account for how rapid attack affects the weapon's effective damage per turn.

**Pull request closed without merging**
