### PR TITLE
[Magiclysm] Miscellaneous Magiclysm Expansions Merger (MMEM)

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary

SUMMARY: Mods "Merge the content of Miscellaneous Magiclysm Expansions to that of Magiclysm itself."

#### Purpose of change

Due to circumstance and collaborative work upon a differing modification, I propose a content merger of Miscellaneous Magiclysm Expansions and Magiclysm itself.

#### Additional context

The content of the merger includes:
44 new spells.
5 sub-"schools" of existing classes, concentrating particular elements of that which they branch from.
   Lore-wise, mages of particular classes would devote themselves to certain aspects of a school. Eventually, their spellcasting 
   disciplines would become unique enough, they conflict with their opposing sub-school; Pyromancers and Frostmongers, for 
   example.
A new location, the Wizard Shack.
Various new spellcasting implements, such as wands, staves, and a sword. 
The ability to engrave spells onto runes of the same class, allowing for single use casting of a spell; at half of its maximum power.
Two new monsters.
Two mutation lines, the Orc and Vampire.
Eight new NPC's.
Many recipes, from carving staves to potions galore!
A new plant; the Mana Mushroom. When grown, it can be ground into a solid form of magic.
Eight new starting professions.
Two new vehicle parts.

### CODE REVIEW

**Comment by BrettDong** [comment]
You are merging mod content to root folder. I guess they should be placed inside `data/mods/`.

**Comment by KorGgenT** [comment]
not only that, but 8k lines of change is way too many for me to review in one pr. please split it up into smaller chunks or i just can't review it.

**Review by KorGgenT — CHANGES_REQUESTED** [review]
i forgot to request changes with the above comment. 

it's even faster for me to review things if they'r ~500 lines or less.

**Comment by BrettDong** [comment]
I recommend you to commit changes offline on your local machine.

**Pull request closed without merging**
