### PR TITLE
Even more religious books

### PR DESCRIPTION
**Pull request by The-Anjelo-Guy**
#### Summary
Content "Grammar fixes and even more religious books."

#### Purpose of change

Only for fluff purposes.

### CODE REVIEW

**Comment by Rimplestilt** [comment]
"id": "holybook_bible4" change from spiritual.json missing the E in Bible?

**Comment by The-Anjelo-Guy** [comment]
> "id": "holybook_bible4" change from spiritual.json missing the E in Bible?

Oh right! I didn't saw this mistake there, I probably touched the erase button at my keyboard by accident (I work from a phone). Thank you for letting me know it, I appreciate it.

**Comment by ANickelN** [comment]
While I like having more variety in literature (evil mansion with lots of books is a cool aesthetic), are these weighted properly so that they are rare, or only show up in appropriate locations (temples/shrines of specific religions)?

I feel like it might be strange going into the average house and finding the texts of religions with little to almost no presence in Massachusetts. 

When I checked on Pew Research it seems that non-Christian faiths in Massachusetts made up less than 10% of people surveyed.  Among those non-Christian religions, "Other World Religions" made up less than 1% of those surveyed.
https://www.pewresearch.org/religion/religious-landscape-study/state/massachusetts/

Lowering the rarity to more realistic values also serves to give the "collecting" player something to collect, rather than finding a collection of the world's theology within the first library or two.

**Comment by The-Anjelo-Guy** [comment]
> While I like having more variety in literature (evil mansion with lots of books is a cool aesthetic), are these weighted properly so that they are rare, or only show up in appropriate locations (temples/shrines of specific religions)?
> 
> I feel like it might be strange going into the average house and finding the texts of religions with little to almost no presence in Massachusetts.
> 
> When I checked on Pew Research it seems that non-Christian faiths in Massachusetts made up less than 10% of people surveyed. Among those non-Christian religions, "Other World Religions" made up less than 1% of those surveyed. https://www.pewresearch.org/religion/religious-landscape-study/state/massachusetts/
> 
> Lowering the rarity to more realistic values also serves to give the "collecting" player something to collect, rather than finding a collection of the world's theology within the first library or two.

You are completely right. I'll be working properly at the spawn rates of those religious books for them to spawn at the most realistical way possible. Christian books will be more likely to spawn in relation to the other books, but I'll be performing some research on the field. Thank you so much for the notification, advice and information.

**Pull request merged**
