### PR TITLE
Organize NPC Code

### PR DESCRIPTION
**Pull request by RustyPotato**
This is just a small thing, but it changes the types of some of the code dealing with NPCs and it also changes some of the formatting (thanks to astyle, with cataclysm settings). 

2nd pull request, open for all comments/suggestions.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm making some tiny tweaks and PRing them as #22195 since clang doesn't like the 'd' suffix.
Otherwise looks good.

I was starting to type up a lecture on too-long Pull Requests, but after appending ?w=1 to the file url, its less than 500 lines, so I just crunched through it.

**Comment by RustyPotato** [comment]
Ahh, thank you. I was also going to fix the 'd' suffix (I just needed a few minutes). What does appending ?w=1 do? And why are large PR's done through astyle bad? I understand hand written code, but formatting?

**Comment by kevingranade** [comment]
Regardless of how the changes are made, they still need manual review.  Basically there's no way I'm going to review 3,000+ lines of changes all at once in order to fix styling.  But that's where the ?w=1 comes in, it tells github to not display changes to lines that only added or removed whitespace, so it shrunk the effective size of the diff.

**Comment by kevingranade** [comment]
> Edit: And moving forwards, how can I test such edge cases that clang has locally before I PR them?

Install clang and do the build, though to be honest it's rare enough that I don't do multiple builds, I just let travis and gorgon handle it.

**Pull request merged**
