### PR TITLE
Add disposable filters for gas masks.

### PR DESCRIPTION
**Pull request by Vasyan2006**
Add new filter types:
- Small. Crafted from charcoal and paper. Used in filter mask,
- Medium. Crafted from charcoal and paper. Used in gas masks, PBA and survivor masks,
- Heavy. Recipe equal to rebreather cartridge. Used in hazmat and ANBC suits.

All masks provide no enviroment protection by default and must be activated before use, so they will consume filter.
Each filter lasts for 10k turns (5k turns fo hazmat), about 16 ingame hours (8 for hazmat).
This change will remove "put-on-and-forget" flag from gas masks and they will require more attention, but without excess grinding.

Linting has changed all lines, should I keep it this way or just add new stuff with old formatting?

### CODE REVIEW

**Comment by tyrael93** [comment]
good change

**Comment by John-Candlebury** [comment]
Why not activate/disable  them automatically when needed, or making them consume charges only when being used to filter fields?

Less keypress from the player is good, one of the most common complains about the game is the obtuse ui based in lots of keybindings

**Comment by Night-Pryanik** [comment]
Those linting changes are unrelated, making the PR huge and therefore hard to review. I recommend you drop this PR and open a new one with only addition of disposable filters.

**Comment by Vasyan2006** [comment]
Reopen #23580 without linting, please close this PR.

**Pull request closed without merging**
