### PR TITLE
Fix itemgroups charges (issue #43149)

### PR DESCRIPTION
**Pull request by akirashirosawa**
#### Summary
SUMMARY: None
#### Purpose of change
Fix  issue #43149: 5.1 `can't contain charges` aka `tried to set ammo for spray_can which does not have ammo or a magazine`
#### Describe the solution
```
ERROR: item spray_can itemgroup (recycle_aluminum) can't contain charges (3)
ERROR: item permanent_marker itemgroup (SUS_junk_drawer) can't contain charges (50)
ERROR: item permanent_marker itemgroup (SUS_junk_drawer_handy) can't contain charges (50)
ERROR: item permanent_marker itemgroup (SUS_junk_drawer_artsy) can't contain charges (70)
ERROR: item candle itemgroup (SUS_junk_drawer) can't contain charges (10)
ERROR: item candle itemgroup (SUS_junk_drawer_tidy) can't contain charges (70)
```
Added ammo: `spray_can` -> `aerosol_paint`, `permanent_marker` -> `permanent_ink `, `candle` -> `candle_wax`.
Note: Ammo has full names as `item`, but short as `ammunition_type` to make items look better with them:

```
ERROR: item jumper_cable_heavy itemgroup (recycle_steel) can't contain charges (10)
ERROR: item jumper_cable itemgroup (recycle_steel) can't contain charges (2)
```
Just removed the charges from the `itemgroup`s as they don't make sense. In the future, may add charges as `some semi-abstract "cable spool"`, but this is not necessary for this PR. In any case, it makes no sense to fill up the charges for the `jumper_cable` or `jumper_cable_heavy` in the `itemgroup`s.
```
ERROR: item tanbark itemgroup (teashop_bulk_teas) can't contain charges (2)
ERROR: item spurge itemgroup (teashop_bulk_teas) can't contain charges (2)
ERROR: item lotus itemgroup (teashop_bulk_teas) can't contain charges (2)
ERROR: item chamomile itemgroup (teashop_bulk_teas) can't contain charges (2)
```
Added an auxiliary itemgroup `teashop_bulk_teas_no_stackable`, after that, put one or two of these items at once in one container using `contents-group`. Perhaps there is an easier way, but I have not found it (If not making items stackable).
#### Describe alternatives you've considered
1. May rewrite C++ code to handle items with the "BURNOUT" flag like with "USE_UPS", and do not add ammo for candle. Because the addition of visible ammo makes "BURNOUT" flag useless. But then it makes sense to do this for items with the "CABLE_SPOOL" flag, but it was decided not to do this:
>After some discussion, I am leaning towards making jumper cables a container of some semi-abstract "cable spool" item (similar to our "battery" item). I think that would require the least code changes, because that's how most charges-based items have been migrated, so that path should be relatively smooth. @jbytheway, @KorGgenT
2. Make `tanbark`, `spurge`, `lotus`, `chamomile` `"stackable": true`, but I am not well versed in the matter to understand the implications of such a decision.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Candle changes break some test:

```
-------------------------------------------------------------------------------

tool info

  candle with feedback on burnout

-------------------------------------------------------------------------------

iteminfo_test.cpp:2075

...............................................................................

iteminfo_test.cpp:2079: FAILED:

  REQUIRE( candle.ammo_remaining() > 0 )

with expansion:

  0 > 0
```

**Comment by akirashirosawa** [comment]
@ZhilkinSerg 
> Candle changes break some test:

Now need to `ammo_set` before testing. Fixed it. Although in fact, as I said above, the addition of visible ammo makes "BURNOUT" flag (and burnout info) pretty useless.

Is it possible somehow to compile and run just one test_case? Now I'm doing `make ... check` ->` Ctrl + C` -> `tests/cata_test "tool info"`. It's a little awkward. `make ... check "tool info"` not works. Searching inside the Makefile didn't help.

**Comment by akirashirosawa** [comment]
For some reason, `make astyle` didn't remove the extra space. I deleted it manually.

**Comment by jbytheway** [comment]
> Is it possible somehow to compile and run just one test_case? Now I'm doing `make ... check` ->` Ctrl + C` -> `tests/cata_test "tool info"`. It's a little awkward. `make ... check "tool info"` not works. Searching inside the Makefile didn't help.

Not via the Makefile, but you can run individual tests in a similar way without having to interrupt it.  Just use e.g.
```
make TILES=1 -j9 && ./tests/cata_test "tool info"
```
(That's Unix shell syntax; something similar should be possible on other platforms)

**Comment by akirashirosawa** [comment]
@jbytheway 
> ```
> make TILES=1 -j9 && ./tests/cata_test "tool info"
> ```
But this doesn't compile tests. I run `make ... check` to compile tests it too, because I change the code of the tests. Can this be done without `make ... check`?

**Comment by jbytheway** [comment]
It should compile the tests.  Are you sure it's not for you?

**Comment by akirashirosawa** [comment]
> It should compile the tests. Are you sure it's not for you?

No, maybe because i am using `RELEASE=1`?
```
make app NATIVE=osx OSX_MIN=10.15 RELEASE=1 TILES=1 CLANG=1 USE_HOME_DIR=1 SOUND=1 LANGUAGES="ru"
```

**Comment by jbytheway** [comment]
`RELEASE` shouldn't matter.  The only thing I can find that turns it off in the `Makefile` is setting `RUNTESTS=0`.

What happens if you `make ... tests`?

**Comment by akirashirosawa** [comment]
> `RELEASE` shouldn't matter. The only thing I can find that turns it off in the `Makefile` is setting `RUNTESTS=0`.
> 
> What happens if you `make ... tests`?
```
/Library/Developer/CommandLineTools/usr/bin/make -C tests
make[1]: Nothing to be done for `tests'.
```

**Comment by akirashirosawa** [comment]
In general solution:
```
make ... tests && ./tests/cata_test "tool info"
```
Thanks again. Much more convenient now :)

**Pull request merged**
