### PR TITLE
Implement multimag

### PR DESCRIPTION
**Pull request by BalthazarArgall**
#### Summary
Infrastructure "Implement multiple magazine use and reloading"

#### Purpose of change
Currently, items like tools and guns can only draw ammo from a single magazine while in use. This is a **huge** issue for obvious reasons.

#### Describe the solution
Make multimag a thing. Process:

1. Items that can consume ammo should consume ammo per magazine.

- [ ] Ammo related fields need to be at the pocket level
- [ ] Ammo consumption needs to be predicted per magazine
- [ ] Ammo consumption needs to be done per magazine

2. Reloading

- TBD, I'm not even sure how reloading should behave yet

3. UI handling multimag (may even come before reloading)

- TBD

#### Describe alternatives you've considered
Wait for someone to do it eventually.

#### Additional context

- I have no idea what I'm doing
- I like to create an item for testing purposes, yes this makes gitbot raise the wrong flags
- Checks means that it """works""", not that it's polished in any way

### CODE REVIEW

**Comment by Hyperseeker** [comment]
It sounds like the main goal is to implement e.g. laser sights and flashlights that would require power when attached to a gun. Would this enable actual multiple magazines per gun, like some of the multi-tube shotguns we have?

**Comment by BalthazarArgall** [comment]
> It sounds like the main goal is to implement e.g. laser sights and flashlights that would require power when attached to a gun. Would this enable actual multiple magazines per gun, like some of the multi-tube shotguns we have?

I think we can already give an item multiple magazine pockets but to answer the question, yes, we will need and have multiple functional magazine pockets to enable multimag.

**Comment by fairyarmadillo** [comment]
The Kel-tec KSG has dual magazines currently implemented, and toggles between them via fire modes. I assume this is accomplished by giving them a built-in underbarrel shotgun or something, but the fact that they track distinct magazines could mean they're helpful to look at.

**Comment by fairyarmadillo** [comment]
NC

**Comment by ymber** [comment]
This was the last big project I never finished back when I was a cata dev. First of all, you're never going to do it in one PR. Even splitting it up you're probably going to step on other changes but it's worth it for infrastructure code like this.

One of the big complicating factors here is that you don't only need to handle magazines. Look at how batteries and electric charge storage are implemented now. Back in the ancient past it was a magazine and a watt hour of electricity was an actual item stored in a battery item using the magazine code. Stuff like that has been on the way out for years, pressurized gas containers will probably be handled differently to mags soon too if they're not already. To handle things like coilguns and pneumatics you need to handle batteries and such as well as magazines. Step 1 for this project should be implementing a general firing requirements handler that can deal with more things than ammo items in magazines.

Generalizing loading magazines, batteries, other magazine ish items into the item that uses them also needs doing. When I was doing this we only barely just had the pocket code implemented. Now you should implement it as mag wells and battery sockets and all that being pockets on an item. One of the problems that comes up all over the code base is the creeping scope of the magazine code. Back before we even had magazine items every item that contained something had its own special case code to handle it. Once magazines were implemented everything became a magazine. One problem turned to another. Sorting that out is important to do before you get deep into multimag. If you don't sort that out first down the line you'll find that half the vehicle code needs changing because fuel consumption is handled by the weapon magazine code and making things take multiple magazines gets exponentially more complicated because half of the magazines aren't actually magazines so you can't make it all behave consistently. There's stuff like that all over, the scope of it has crept so far that a bunch of things just use special cases in the mag code when they should have had general consumable source handlers written for them that handle things that aren't mags.

The step 1 you've got in your plan is actually more like step 6. This is a big long term project and it's important to do all the infrastructure work behind the scenes before the player facing stuff will be feasible. I worked on this with @KorGgenT back in the day, he wrote a huge amount of the current item handling code, he's the one to ask about how stuff works.

**Pull request closed without merging**
