### PR TITLE
[Xedra Evolved] Add some Salamander mutations

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "Add some Salamander mutations"

#### Purpose of change

I had ideas for some Salamander mutations too

#### Describe the solution

Add some Salamander mutations (more to come?)

**SPELL-GRANTING MUTATIONS**
- Enkindle: Set a nearby square on fire.
- Blazing Blow: Do fire damage and knock a target back a short distance 
- Fiery Charge: Charge forward and cause an explosion at your arrival point.
- Breath of the Firedragon: A cone-based fire attack. (_Requires Blazing Blow_)
- Calling the Children of the Inferno: Summon other fire fae to aid.
- Burning Away Your Impurities: Target themselves or an ally to cure a large number of status conditions (dermatik, poison, diseases, etc) but cause damage to each limb. (_Requires Heat Fuels the Flames_)
- Fanning the Inner Spark: Increase speed for self or ally.  (_Requires Heat Quickens the Blood and Outracing the Prairie Fire_)
- Stoking the Inner Furnace: Emit hot air.  (_Requires Enkindle and The Bonfire Blazes Until the Revelers Have Gone_)

**PASSIVE MUTATIONS**
- The Inner Fire Cannot Be Quenched: The Salamander no longer needs to drink. (_Requires Burning Coals Skin_)
- Salamander Eyes: Same as the other Paraclesian eye mutations, provides glare protection. Also allows the Salamander to always know the temperature. Leads to:
- Heatsight: Allows the Salamander to see into the infrared. Changes to:
- Reading the Heartfires: As above, but also grants the Salamander +10 to Persuade or Lie checks due to more easily being able to read their target's emotions (by seeing the heat of their blood flow). 
- Salamander Ears: The Salamander's ears are longer and pointed, like tongues of flame.  This has no in-game effect.
- The Campfire Stands Watch: The Salamander needs 25% less sleep but must eat 33% more food. Changes to:
- The Bonfire Blazes Until the Revelers Have Gone: The Salamander needs 50% less sleep but must eat 66% more food.
- Heat Quickens the Blood: The Salamander acts faster in hot weather, but is more sluggish in cold weather (_Requires The Inner Fire Cannot Be Quenched_). Changes to:
- Heat Fuels the Flames: In addition to temperature-based speed, the Salamander heals much faster in heat. (It's unfortunately not possible to get ambient temperature, so this is based on standing in warm air fields or fire or the weather [not local temperature, weather temperature] being 80 F or hotter)
- Strength of the Crackling Fire: +1 Strength. Changes to:
- Strength of the Blazing Bonfire: +3 Strength.
- Sparking Thoughts: +2 Intelligence.
- Fiery Speed: +2 Dexterity. Changes to:
- Blazing Speed: +5 Dexterity. (_Requires Fiery Charge and Heat Quickens the Blood_ )
- Outracing the Prairie Fire: The Salamander moves and attacks 10% faster (_Requires Blazing Speed_ )
- Within the Firelight: As a distant fire reveals that which is nearby, the Salamander can see what surrounds their kin.  Gain moncams on Salamander summons. (_Requires Heatsight_)

**ACTIVE MUTATIONS**
- Effortlessly-Rising Smoke: Like smoke rising to the sky, the Salamander cannot be kept down. This mutation may be activated to immediately clear the Stunned, Dazed, or Downed effects. ( _Requires Outracing the Prairie Fire_)

**POST-THRESHOLD MUTATIONS**
- Inured to Flame: Become completely immune to heat or flames, but take additional damage from cold. (_Requires Flame Skin_)
- Burning Ascension: Teaches a spell that allows the Salamander to launch themselves into the air with an explosion and float on smoke for a short period of time before falling safely back to earth.  (_Requires Inured to Flame_)
- On Wings of Flame: The Salamander may manifest a pair of fiery wings at will. The aetherial nature of the wings does not allow them to carry the Salamander aloft, but they may be used to break a fall or buffet enemies in combat. They also glow very brightly. (_Requires Inured to Flame and Outracing the Prairie Fire_)
- In Flames, Reborn Like the Phoenix: A passive effect, once every two weeks if the Salamander dies while standing in a fire they have a 100% chance to be immediately healed and stripped of all debilitating conditions. It can also happen during this two-week cooldown, but only at 1/7 chance.   (_Requires Inured to Flame_)
- The Watchfire Burns Throughout the Night: The Salamander no longer needs to sleep at all.  However, they must eat twice as much food as a human.  It is possible to deactivate this if the Salamander wishes to sleep for some reason, in which case they only need half as much sleep as a human. (_Requires The Bonfire Blazes Until the Revelers Have Gone_)

#### Testing

Everything works

#### Additional context

I like the idea of every Paraclesian having their own individual PREVENT_DEATH EoC as an extra reinforcement that they are _not_ humans and not subject to human frailties.

Also, writing for this has the same problem as Pyrokinesis where I need to come up with 50 ways to say "fire."

### CODE REVIEW

**Comment by Standing-Storm** [comment]
30 powers and a thousand lines is a good place to stop.

**Comment by ashGlaw** [comment]
Love the flavor! These are all great

**Comment by Maleclypse** [comment]
This is great!

**Comment by Standing-Storm** [comment]
I'm glad I met my initial goal, which was get through the whole tree without ever making "You cast fireball"

Also, probably another PR coming with more ideas (vanish in a burst of smoke, stop bleeding through cauterization [which works thanks to magic], summoning a "fire whip" weapon to wield, a recipe to transform water into strong alcohol, a post-threshold decrease in spell-casting times building on the theme of speed, immunity to radiation, some other stuff I'm forgetting)

**Pull request merged**
