### PR TITLE
compose.py: make default output easier to read

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
Make compose.py's output more easy to read. Before the output was just a really long line of json, sometimes causing funny stuff to happen such as your text editor not even recognize it as json, or just slowing the software you used to open it waaay down.
long_line_long
kinda_shot

#### Describe the solution
Indent output.

#### Testing
See pictures.

### CODE REVIEW

**Comment by int-ua** [comment]
No indent is intended to reduce file size in releases. You can always use `python -m json.tool` to format it after `compose.py`.

**Comment by int-ua** [comment]
Alternatively, make it an opt-in feature with a new argparse argument.

**Comment by casswedson** [comment]
Configs file from here <https://github.com/I-am-Erk/CDDA-Tilesets/releases/tag/2021-08-01> are all formatted, probably using cdda's formatter, in-repo tileset config files are also formatted using cdda's formatter, so the other instances of default output config files are those generated by some CI workflow or in someone's computer, if for some reason someone opens one of those files they benefit from it being somewhat readable.

**Comment by int-ua** [comment]
> Configs file from here https://github.com/I-am-Erk/CDDA-Tilesets/releases/tag/2021-08-01 are all formatted, probably using cdda's formatter, in-repo tileset config files are also formatted using cdda's formatter, so the other instances of default output config files are those generated by some CI workflow or in someone's computer, if for some reason someone opens one of those files they benefit from it being somewhat readable.

These files are not meant to be edited manually. They are both generated and read much more often by code and not by humans. The reason behind formatting them for in-repo tilesets is that git works better when there are multiple lines in a file. If you need to open it more often than not means that you are already debugging one of the automated ends, either the `compose.py` or the game code.

Much more people will benefit from them taking less space including me as I often run it locally and I don't remember when was the last time I needed to open the file.

If you are not sure you can make it opt-in I'll do it, ok?

**Comment by int-ua** [comment]
anyway, it's easy, I'm already doing it

**Comment by int-ua** [comment]
Using the option more than doubles the file size. I really wouldn't like writing all these spaces every time.

**Comment by casswedson** [comment]
Getting someone with more python experience than myself to evaluate a problem and consecutively make some changes is a pleasant outcome indeed.

**Pull request closed without merging**
