### PR TITLE
Products of filthy crafting are filthy.

### LINKED ISSUE #20356: Filthy ingredients combine to form clean cloths
Now that there is a new feature that has filthy clothes dissemble into filthy rags/patches/etc, it would seem to make sense that creating cloths from those ingredients would create filthy clothing, but it doesn't

### LINKED ISSUE #20357: Filthy leather jacket can be crafted to a clean vest with 5 clean leather patches

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #20356 
Fixes #20357 
Just some consistency, filthiness shouldn't be lost simply by crafting.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
How is this handled from a UI sense?

A mix of clean and filthy clothing corrupting the output with no player warning with be bad implementation, for example. Having this potentially occur with rotten food is already an existing UI concern, and as far as I can determine is one blocker to rotten ingredients having any effect on non-perishable food.

A prompt before initiating crafting if the output would be filthy would be useful, but only if the system is reliably able avoiding filthy ingredient entirely unless there are no alternatives in crafting radius.

Added tedium of having to wash rags or other salvage items relative to raw zombie drops or complete might additionally be a complicating factor. Cutting up filthy clothes would increase the amount of player input demanded (and possibly multiply soap usage), while crafting them into filthy items will decrease the amount of input demanded, and either increase or decrease amount of soap required depending on the percentage of filthy materials used in crafting the item.

The last concern, increasing the amount of soap consumed if filthy and clean components are combined, will have potential for causing player annoyance, and will cause inconsistencies.

**Comment by kevingranade** [comment]
That is a problem, and the crafting code has no way to "prefer" some items
over others at the moment, so that route is out as well.

The only solution I see is forbidding use of filthy clothing in crafting,
the same solution we use for rotten ingredients.

**Comment by Coolthulhu** [comment]
> the same solution we use for rotten ingredients

We don't do that yet. It was proposed in the simplest form, but rejected, because many crafts can use rotten items just fine and because 2 mutations make eating rotten food perfectly fine.

**Comment by DangerNoodle** [comment]
> The only solution I see is forbidding use of filthy clothing in crafting, the same solution we use for rotten ingredients.

Incorrect last I checked. I would thus assume that current handling is more in line with the methods I fear will be most problematic from the perspective of players. The "avoid filthy reagants unless forced to, possibly prompt player if output will be filthy" would be the best solution in terms of making it the least annoying for players.

**Comment by kevingranade** [comment]
OK, I was remembering a proposal instead of the implementation, my mistake.
>  "avoid filthy reagants unless forced to, possibly prompt player if output will be filthy" would be the best solution in terms of making it the least annoying for players.

As I said
> the crafting code has no way to "prefer" some items over others at the moment, so that route is out as well.

**Comment by DangerNoodle** [comment]
> the crafting code has no way to "prefer" some items over others at the moment, so that route is out as well.

Understood. Some implementation of that would be desirable in the future, but possibly low-priority.

**Comment by tinukedaya** [comment]
Well... With this the game recognize if filthy material is used right? It has to in order for the result to be filthy, So why not give a prompt to the player asking if he wants to continue? At least there will be no surprise when I see the result.

**Comment by kevingranade** [comment]
I have an implementation in mind that would make this kind of thing much
easier to handle, but I don't want to delay 0.D to do it.

Briefly, the first step of crafting would be assembling the components into
a "bundle" that can be referenced throughout the crafting process,
including tracking progress toward completion of the craft.

**Comment by Coolthulhu** [comment]
> Briefly, the first step of crafting would be assembling the components into a "bundle" that can be referenced throughout the crafting process

First step?
I see at least 3 points for starting:
* At menu stage, also helping with display (say, if you only have rotten food, menu would display rotten result)
* During the item selection, with individual items being binned into categories to allow picking correct components
* After item selection, only to help with resuming work

I tried to implement something like this twice already, but realized that option 1 and 2 would be very clunky without item IDs and option 3 would not solve much, just wrap the items for resuming and NPCs working on crafting projects.

**Comment by Night-Pryanik** [comment]
Should be closed if #20859 was merged?

**Comment by kevingranade** [comment]
yep, oversight.

**Pull request closed without merging**
