### PR TITLE
Make mansion basements modular, and add hidden bionic basement room for HTLL scenario

### PR DESCRIPTION
**Pull request by MT-Arnoldussen**
#### Summary
SUMMARY: Content "Make mansion basements modular, and add hidden bionic basement room for HTLL scenario"

#### Why
* Mansions are currently all prebuilt, but the basements tiles are almost all made in such a way that mansions could easily pull from a pool of basement tiles to create a random basement for each mansion.
* There is only a single starting location for the High Tech Low Life Start, after I removed all the ones not related to bionics.
* Without mods there is no way to start in a Mansion.

#### What
* This makes mansion basements modular, meaning they are randomly generated from existing basement tiles. This enables people to add new basement tiles and have them show up in Mansions.
* Ground and first floors are very interdependent, so those have been left alone.
* Most existing basement tiles have been changed to have walls and connections make sense regardless of configuration.
* Adds a library basement room with 3 variations: normal, hidden bionic room, and hidden cannibal room.
* The hidden bionic room is a possible starting location for the High Tech Low Life scenario.
* To make that work, I had to add a fifth mansion type overmap special which is a copy of an existing one, except one of its 9 basement tiles is always the bionic basement. There might be a better way of doing this.

#### Additional context
One issue with the modularity is walls extending into rock, because the tiles responsible for the walls do not know how large the neighboring tiles will be. This will not be visible in the vast majority of games though:

capture

In addition to that, there can now be duplicate tiles in mansion basements. This is mostly because there are very few of them to begin with: before this there were only 18 possible basement tiles. hopefully more of them will be created.

I believe around one in ten mansions should now have a (semi-hidden) autodoc.

### CODE REVIEW

**Comment by kevingranade** [comment]
Hrm, the wall thing is one of the problems with json-based mapgen, it would be pretty simple to polish those away in the code.

Just FYI, one thing that can happen is when you have a junction like:
```
RRW
RRW
WWW
RRW
RRW
```
The 'W" at the junction can end up being drawn as a 'T' instead of being flat, so there is sometimes an artifact visible from this approach.

I don't consider that serious enough to block this addition though.

**Comment by Night-Pryanik** [comment]
jenkins rebuild

**Comment by MT-Arnoldussen** [comment]
well that merge conflict went nowhere.

will open a new PR with these changes later, since i have some minor things i wanted to change anyway

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/modular-mansion-basements-and-hidden-bionic-labs-closed-merge-request/22967/1

**Pull request closed without merging**
