### PR TITLE
Increase search ranges for important locations

### PR DESCRIPTION
**Pull request by MoocowTG**
#### Summary
Bugfixes "Increase search range for important locations and quest hubs"

#### Purpose of change

Several times I've had the game fail to find hub 01 when getting the quest from Smokes at the refugee center, leading me to believe my world was broken. This should help alleviate that along with the other locations from the teamster. 

#### Describe the solution

Simply increase the range of the search. It may cause the game to hang for longer when looking for map locations but that's far preferable to not finding anything and being stuck with a dead mission with no way to feasibly find the hub.

#### Describe alternatives you've considered

In addition to this, an extra message popup warning the player that the game may hang for a few seconds would be good, but I don't have the time to dig into something like this.

#### Testing

Tested in my world - prior to this change the hub was not found. After this change, it was found, 523 tiles away - just 23 more than the limit.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@akrieger is there any way to reduce the hang time when searching at these distances?

**Comment by PatrikLundell** [comment]
What about an alternative to searching for "unique" locations that are now set to actually be unique, namely to record their locations in a unique location list (of whatever flavor is deemed suitable technically, be it vector or map or actual list) when they are created. After all, there is a need to record that they have been created to block further creation, so it would make sense to record the location as well. This assumes that these locations are generated on world gen rather than as a result of searching for them, though.

This is presumed to be out of scope for this PR, though.

**Comment by akrieger** [comment]
I'm wholly unfamiliar with how searching for specials works but I'm sure there is 'a' way, it just might not be 'easy'.

**Comment by akrieger** [comment]
It would help if you uploaded your save for repro'ing with btw.

**Comment by MoocowTG** [comment]
> It would help if you uploaded your save for repro'ing with btw.

Had to double archive it to fit cuz github doesn't accept 7zip for some reason.

Teleport a few tiles west to get to refugee center and get the fema data quest, it'll fail. Increasing the search range beyond 500 tiles will make it work.

[Deadhorse.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14316207/Deadhorse.zip)

**Comment by akrieger** [comment]
All the time is going into mapgen itself, not searching the map. Won't help the delay here if the map literally hasn't genned.

image

**Pull request merged**
