### PR TITLE
Delete unnecessary om placements from refugee centre

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change

Scrolling is pain

#### Describe the solution

Doubles down on #66123 and removes all special_air because it doesn't do anything and deletes all special_earth, special_rock and special_deep_rock that aren't in reality bubble of the building
image
!s are the special terrain

#### Describe alternatives you've considered

Removing all the underground special terrain in exchange for labs being able to spawn under it

#### Testing

Checked I got all the right oms by changing the special terrain symbol as shown above

#### Additional context

(The additions are just organising the order a lil)

### CODE REVIEW

**Comment by I-am-Erk** [comment]
These are present for expansion of the building into the deeper layers, and to prevent labs from going there. You can remove a bit of the air, but it's fairly pointless to remove the earth part

**Comment by Zireael07** [comment]
@I-am-Erk Worth a comment in the code so that the next contributor doesn't try the same sort of "clean-up" again

**Comment by I-am-Erk** [comment]
Or worth me doing some mapping at last

**Comment by Procyonae** [comment]
> These are present for expansion of the building into the deeper layers, and to prevent labs from going there. You can remove a bit of the air, but it's fairly pointless to remove the earth part

"Present for expansion" is a nonsense reason, only new maps would gen with the basement when it gets added anyway
I left the ground part within reality bubble range in specifically so labs can't spawn down there
I disagree that removing 1145 pointless om placements is in itself pointless

**Comment by I-am-Erk** [comment]
Oh... I see. Someone "simplified" and changed these all to have a generic name.

These were originally given specific map names so that update mapgen could be run to spawn new structures within the area. That hasn't happened yet obviously, but that's the intent. They make no sense with the generic names, I agree... I would prefer they be reverted to having specific names so we have that option without rebuilding the world, but I don't intend to get around to using them any time immediately either so I'm not going to argue at length about it. If you really want you can delete it and I'll replace them when I get the bunker added in.

**Pull request merged**
