### PR TITLE
Fix curry/chili powder substitutions

### PR DESCRIPTION
**Pull request by lazho**
#### Summary

SUMMARY: Content "Fix recipe substitutions for chili and curry powder"

#### Purpose of change

Related to #34068, mentioned in point 2 and 3 of proposed solution.

#### Describe the solution

Removed instances in food recipes where red sauce appears next to curry/chili powder and chili pepper.

Added chili powder as substitute for curry powder in every recipe curry powder is used.

#### Describe alternatives you've considered

N/A? 

#### Additional context
Before (recipe is curry with meat)
beforecurry
After
curryafter

### CODE REVIEW

**Comment by lazho** [comment]
btw this PR is JSON only... currently tagged as C++

**Comment by lazho** [comment]
That's strange. For this recipe, the only change was adding 20 chili powder as alternative to 20 curry powder. Neither should have any caloric content.

**Comment by ZhilkinSerg** [comment]
I am not 100% sure, but I think you need to use `NUTRIENT_OVERRIDE` item flag here.

**Comment by kevingranade** [comment]
That's a very odd outcome, I agree this should not have done anything to the nutrition test.
I can only guess that the change is that before it was three different recipe variants and after it's six recipe variants, and this shrunk the confidence interval for the test, causing it to fail.

**Comment by kevingranade** [comment]
I notice sausage and bratwurst have pretty different calories, 474 vs 297.  This was probably right on the border of failing previously.  The smallest change likely to make the test happy is to bump the bratwurst requirement to three portions.

**Comment by kevingranade** [comment]
Ok I checked and that didn't do it, but i works if you cut all the quantities of the currywurst in half.

**Pull request merged**
