### PR TITLE
(Researching) Better and faster RNG & hash function

### PR DESCRIPTION
**Pull request by ghost**
Implements #5249.

Short summary:

In this PR, I made the following changes:
- Use FNV-1a hashing algorithm instead of DJB2
- Use `xorshift1024*` RNG
### Use FNV-1a hashing algorithm instead of DJB2

Ian Boyd compared several hashing algorithms on Stack Exchange [1], with three different key sets:
- `Lowercase`: a list of 216,553 English words
- `Random UUID`: same amount of random GUIDs
- `Numbers`: the number from 1 to 216,533

```
Hash           Lowercase      Random UUID  Numbers
=============  =============  ===========  ==============
Murmur            145 ns      259 ns          92 ns
                    6 collis    5 collis       0 collis
FNV-1a            152 ns      504 ns          86 ns
                    4 collis    4 collis       0 collis
FNV-1             184 ns      730 ns          92 ns
                    1 collis    5 collis       0 collis
DBJ2a             158 ns      443 ns          91 ns
                    5 collis    6 collis       0 collis
DJB2              156 ns      437 ns          93 ns
                    7 collis    6 collis       0 collis
SDBM              148 ns      484 ns          90 ns
                    4 collis    6 collis       0 collis
SuperFastHash     164 ns      344 ns         118 ns
                   85 collis    4 collis   18742 collis
```

From the comparison we can see that FNV-1a algorithm [2] has advantage both on higher performance and less collisions.
### Use `xorshift1024*` RNG

C standard has provided the random generating function `rand()`, but that function has some problems. 
1. It produces integers within range [0, RAND_MAX]. On MSVC, the value of `RAND_MAX` is 65535, which isn't perfectly wide.
2. It has short period and poor quality, fails systemically in many statistical tests.
3. On some platforms, the implementation of `rand()` is fairly slow, eg. Windows MSVC. See my benchmark below.

In #5249, @Abalieno used mersenne twister RNG. But according to a benchmark in one of Sebastiano Vigna's paper [4], the performance of mersenne twister isn't quite fast. It requires a loop of 624 iterations after each 624 calls. Also, mersenne twister algorithm systemically fails on some statistical tests [6]. I suggest `xorshift1024*` RNG algorithm proposed by Vigna [4]. It has excellent performance and passes most of the statistical tests.

Vigna made a benchmark on an Intel Core i7-4770 CPU 3.40GHz: [4] [5]

| Generator | Mean time (ns) |
| --- | --- |
| xorshift1024* | 1.36 |
| MT19937 | 2.84 |
| SFMT19937 (SIMD) | 1.80 |

Also, I made a benchmark on my Intel Core i5-5250U CPU with frequency 2.55GHz when Turbo Boost activated.

| Generator | Mean time (ns) |
| --- | --- |
| xorshift1024* | 4.03 |
| rand() MSVC | 21.94 |

Using the new RNG, we can get better random numbers faster.
### References

[1] [http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed](http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed)

[2] [http://www.isthe.com/chongo/tech/comp/fnv/](http://www.isthe.com/chongo/tech/comp/fnv/)

[3] [https://en.wikipedia.org/wiki/Xorshift](https://en.wikipedia.org/wiki/Xorshift)

[4] [http://vigna.di.unimi.it/ftp/papers/xorshift.pdf](http://vigna.di.unimi.it/ftp/papers/xorshift.pdf)

[5] [https://arxiv.org/pdf/1404.0390v3.pdf](https://arxiv.org/pdf/1404.0390v3.pdf)

[6] [http://www.pcg-random.org/other-rngs.html](http://www.pcg-random.org/other-rngs.html)

### CODE REVIEW

**Comment by DLaboratory** [comment]
Note:
1. I eliminated all calls to `rand()` and changed them to `xorshift_rng_***()`. Now `srand()` and `rand()` are no longer used in the entire project.
2. The implementation of FNV1a hash algorithm and `xorshift128+` RNG algorithm I wrote are optimized for 64-bit machines, so you can see the type of those functions are `unsigned long long`. I anded them with `0x7FFFFFFF` somewhere because the rest of the code only accept 32-bit signed values. I don't have plenty of time IRL these days. This dirty hack may be cleaned up in the future.

**Comment by kevingranade** [comment]
Where is the performance testing showing that it makes a difference that I asked for in #5249?
If it doesn't have a significant performance benefit, I'm not going to even consider moving away from the standard rand to a hand-coded solution.

**Comment by DLaboratory** [comment]
> Where is the performance testing showing that it makes a difference that I asked for in #5249?

In the description of this pull request. I looped 10^8 times for each RNG, measured the time elapsed, then calculated average time for each call. Intel Core i5-5250U Turbo Boost frequency 2.55 GHz.

| Generator | Mean time (ns) |
|---|---|
| xorshift128+ | 1.81 |
| rand() | 21.94 |

`xorshift128+` is faster than `rand()`, and has better quality.

**Comment by DLaboratory** [comment]
Sorry, misread.

> performance testing showing that it makes a difference

The original motivation of introducing `xorshift128+` RNG algorithm is to get better random numbers. `rand()` are awful. Then, I noticed that it runs faster than `rand()` too. And just when I was writing the description of this pull request, I casually searched on the issue tracker, and found #5249 .

`rand()` might not be the performance bottleneck at all. This PR is not for a performance optimization at first.

**Comment by DLaboratory** [comment]
There are both benefit of speed and output quality when I was studying `xorshift` RNG algorithms family, so I thought of, ``Why not bring it to CDDA?'' Then there is this pull request.

**Comment by mugling** [comment]
> xorshift128+ is faster than rand(), and has better quality.

The latter may be true but is there any evidence that `rand()` isn't random enough for our purposes?

**Comment by DLaboratory** [comment]
> is there any evidence that rand() isn't random enough for our purposes?

It's hard to say of what degree of randomness is enough for gaming purpose. There is no quantitative standard to judge a generator whether it's quality is enough for gaming.

**Comment by kevingranade** [comment]
Good point mugling.  A demonstrable problem caused by insufficient randomness, even a somewhat contrived one in a unit test type situation would also be sufficient, but outside of concrete evidence that *this* change improves the game in some measurable way, this is all cost and no benefit.

**Comment by Coolthulhu** [comment]
If there is some `rand()` heavy section of the code that gets invoked often, maybe it could be used in a test to show the differences in speed.

Could be monsters' reaction to noise. It can be called quite often and invokes a bunch of random rolls.

**Comment by Coolthulhu** [comment]
If you still can't find a good test case for it, you could try fields. Each field entry invokes 2 `rng`s per turn.
A good test would be to:
* Spawn an empty map
* Cover it all in blood
* Start a timer
* Wait a set number of turns (1000 or so)
* End the timer

This could be easily automatized and probably invokes the most rng-per-second out of all code in the game that can be expensive to compute.

**Comment by DLaboratory** [comment]
`Could you please get #17455 merged, so I'll have a more convenient environment to test.

**Comment by DLaboratory** [comment]
CPU: Intel Core i5-5250U underclocked at 1.00 GHz
OS: Windows 10 x64

| generator | time for 600 turns IRL | average time per turn |
|---|---|---|
| `rand()` | 6.758s | 11.263ms |
| `xorshift1024*` | 6.551s | 10.9183ms |

The profiler suggests `map::process_fields` only consumed a very small period of time (24ms inclusive) compared to the whole process (6 seconds), so the difference are not significant.

profiler

**Comment by mugling** [comment]
Closed due to lack of compelling performance data. Can be reopened if appropriate data is provided.

**Pull request closed without merging**
