### PR TITLE
Military armor balance

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary
```SUMMARY: Balance "Rebalances some armors to fit armor balance document"```

#### Purpose of change
 ```#36759```
Makes a couple of currently unexpectedly weak armors more inline with the armor balance document: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance

#### Describe the solution
Increased material thickness on the MBR vest variants that are loaded with plates, and the swat armor, AEP armor, and ANBC armor. Reduced encumbrance on some of the MBR variants.
They now have the following simple values:

MBR (ceramic plates) 	= 1.11
MBR (superalloy) 		= 0.95
MBR (hard plates) 		= 0.89
MBR (steel plating)   	= 0.86
AEP suit 				= 0.8
MBR (kevlar plates) 	= 0.77
Swat armor 			= 0.7
ANBC suit 			= 0.47

#### Describe alternatives you've considered
Waiting for armor to be more fully reworked or only buffing the armors slightly so they can at least compare favorably to leather armor. They should now be great armor but without the coverage that survivor suits or plate armor can provide.

#### Testing
Spawned all the new armors to make sure the stats were correct, wore them, and spawned some zombies to hit me to see if there was weird interactions.

#### Additional context
Screenshot of the new values ingame:
image

PS:
Edited the kevlar mbr(kevlar plates) up to encumbrance 12 to differentiate it more from the empty mbr vest. updated it's simple value above

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Shouldn't the MBR vest get replaced with a plate carrier instead? The new ballistic vest item, and its variants, should replace all the MBR items. Unless MBR is going to now be a survivor made thing- a regular Kevlar vest with plate pockets and mag pouches sewn on.

Also, the superalloy needs to come way down in terms of armor- titanium inserts are only offered for stab resistance, not their ballistic protection (as they don't really offer any) and there wouldn't be any super-engineered alloys for the purpose- that's what ceramic plates are.



There are 8000 grams of steel plate in the MBR steel plate item. This is distributed over a surface area of 2 6"x8" plates and 2 10"x12" plates (average ballistic plate sizes. This results in a plate weight of 2.8#/ft^2, a plate thickness of about  .069". That's very pathetic, and is a an RHA equivalent of  .0552".

5.56 will punch through and damage mild steel quite well, using non-armor piercing projectiles, 12mm thick RHA plate, or 15mm thick mild steel plate. <https://ndiastorage.blob.core.usgovcloudapi.net/ndia/2010/armament/WednesdayLandmarkBPerArvidsson.pdf>
You would need .59" thick steel plate to stop 5.56, whereas .375" Hardened steel plate is sufficient.

I'm unable currently to find any documentation for performance by 9mm on mild steel ( or any other test medium), so a youtube clip will have to suffice for now. <https://www.youtube.com/watch?v=WYBbMg3phZI>

.069" would put the steel plate MBR between a regular one and a superalloy one. (both I would argue are less effective than what is essentially two kevlar vests (IIIA kevlar inserts combined with a IIIA vest).

**Comment by Brian-Otten** [comment]
I'm not sure what exactly the plan or timeline was for ballistic vest and variants to replace the MBR and it's variants and what way, so i figured i would include them in a balance pass for now. If the plate carrier system is expanded on to replace them that would be totally fine. But for now the MBR vest is a very common item you will find in every playthrough so i thought their armor values were weird.

As for the superalloy and steel vest values, especially when it comes to bullet resistance, i feel like tackling those issues would take a more thorough rework of the entire armor system. They are already the same resistance, or lower, as wearing a kevlar vest + a cuirass. or even a chainmail vest + a cuirass.

So while it might be time for a full rework of the entire armor system, it's not here yet and probably won't be for a while. until then i don't see a problem with making the armor values conform to reality as far as possible while fitting in the current system.

**Comment by tenmillimaster** [comment]
The best course of action for you here based on your assessment, then, is to remove their spawns. The survivor can still insert these materials if they wish, but the won't be found together anymore, because they wouldn't be found together.

**Comment by Brian-Otten** [comment]
Except the ballistic vest is not set to appear everywhere you would expect mbr vests yet, and is still awaiting a balance pass. 
Removing them from the game would be premature. 
I'm not quite sure where you find the superalloy and metal inserted variants as of right now, Sounds like a good issue/separate PR to see if they are spawning in sensible places.
What i want to avoid is the player skipping military body armor and instead going for leather armor + platemail to soak bullets. or just the ubiquitous survivor armor being far better than military gear.

**Comment by tenmillimaster** [comment]
Were you to remove them, and their itemgroups were called, Empty, Kevlar plate, or ceramic would spawn in their place. 

I don't see the problem with that.

**Comment by Brian-Otten** [comment]
Sounds like a good call for a separate PR.  I've tried to keep this one from becoming to bloated, and it's already a bit full.

**Comment by esotericist** [comment]
> I've tried to keep this one from becoming to bloated, and it's already a bit full.

As a point of order, as a +10 -10 PR, I cannot fathom by what measure this one could be considered "bloated" or "full". If you mean the commit history, that can (and should) be addressed through rebasing.

It's also important to consider the actual objective in the changes you're making. If your goal is to have what the player has access to for ballistic protection to be sensible, addressing spawn locations at the same time is not inappropriate.

**Comment by Brian-Otten** [comment]
Stylistic differences then i suppose. The change suggested is now a PR and the maintainers can see them as a package deal if they think they should go together.

**Comment by Brian-Otten** [comment]
Ran a little benchmark to show off where the balance is about at right now. changed this version of the mbr(ceramic plates) to 100% coverage of all bodyparts. spawned in some gun enemies to test.
MP5 turret: if the turret hits the ceramic plate armor it gets stopped with no damage dealt
m249 turret: Turrets hits me for 13-23 damage. i seem to die in 2 bursts of its gun
image

**Comment by Brian-Otten** [comment]
Bonus round versus the m240 crow
image

**Comment by SirPendrak** [comment]
Maybe increase MBR with kevlar plates encumbrance to 10? This version is now much, much better than empty just-soft-kevlar MBR that sits at 7enc. 
SWAT armor is now somewhat comparable to heavy survivor armor, yet still a bit weaker. 
AEP suit is strong competition for acid resistant survivor suits, less storage and warmer but much more resistant. 
ANBC suit looks like something very strong now, only downsides being a little too warm, no storage and bad fire protection. But it will grant immunity to 80% of zombies, or 100% of starting and early evolution zombie types.

**Comment by Brian-Otten** [comment]
Good call, seems like a good adjustment adjustment on the mbr(kevlar vest) will update that in a second. I'll launch up the game with the ANBC suit and give it a quick playtest, i suspect the encumbrance will end up with the player getting swarmed and worn down due to stamina issues, thus best used in combination with a gun playstyle.

**Comment by Brian-Otten** [comment]
ANBC suit test:
Spawned in a survivor with all stats at 14, skills at 4, with the quarterstaff and brawling stance. walked into a mall and started fighting, tried somewhat to stay alive without fully running away. zombies swarmed me and drained me of stamina. They had trouble getting through the armor but pretty much ended up locking me in place.
image
35 kills before they finished my character. was a mix of pretty much only normal and fat zombies.

**Comment by SirPendrak** [comment]
Did you wear any gas mask? Or were they able to punch trough because of increased strenght when being a large group?

**Comment by Brian-Otten** [comment]
I didn't wear a gas mask for this one but they punched through working as a group and broke my limbs before finishing me off.

**Comment by Amoebka** [comment]
What about the helmets?

**Comment by Brian-Otten** [comment]
Had a quick look at the army helmet. it's at 95% coverage with only 15 cut protection. Most military helmets are meant more for shrapnel and as a bump lid, so i found it hard to find extensive ballistic data, but i could find this:
https://www.youtube.com/watch?v=KzgiZpCIj1c&feature=emb_logo
6:30 to 7:30 is the more relevant bit. adjusting it so it can mostly stop .38 and takes reduced damage from .357 seems about right. It can't currently do that and is pretty much fully outclassed by the survivor helmets which is a bit sad, so i will go see how to adjust it a little.

**Comment by tenmillimaster** [comment]
The ECH, ACH, PASGT and ATE helmets all have publicly available specifications.

**Comment by Brian-Otten** [comment]
That sounds useful.  i wasn't able to trivially find those reports, but i'd love for those to be used in tackling a rework of army helmets. Let me know if you want to tackle that or want to collaborate on getting those into a PR somehow.

**Comment by Brian-Otten** [comment]
Removed the storage from the AEP suit when i realized neither the kevlar vest nor the cleansuit it is made from have storage, nor do any other hazmat style suits.

**Comment by Brian-Otten** [comment]
Anyone have further ideas for what needs to change here? I've gone over these again once or twice and think this should put them in a place where some survivors, but not most, would use them.

**Comment by Brian-Otten** [comment]
Cleared up merge conflicts and looked this over, should be good to merge in the 0.E experimentals.

**Pull request merged**
