### PR TITLE
Remove unused monsters

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: None

#### Purpose of change

Two monsters haven't been spawning anywhere for a long time, just remove unused data.

#### Describe the solution

Remove the unused entries.

#### Testing
Search every reference of the monster id 
Only find monster definition and sprites reference

Load game
No errors

#### Additional context

They have been absent for more than one version so it should not cause any load problems

### CODE REVIEW

**Comment by joshuaipwork** [comment]
Could these monsters be added somewhere rather than removed?

**Comment by Gourmand-is-OP** [comment]
These monsters already and currently exist within the magiclysm mod. The flesh angel also is involved in one of the main questlines in it. I strongly advise not removing these enemies, since I believe it will cause errors for a significant part of the playerbase.

**Comment by anothersimulacrum** [comment]
What? These don't appear anywhere in Magiclysm.

**Comment by Gourmand-is-OP** [comment]
Ah my bad. They do not appear in magiclysm,  they are part of arcana. Which is still a very common mod, although I don't remember if it's mainlined.

**Comment by anothersimulacrum** [comment]
It is not.

**Comment by SirPendrak** [comment]
If strange temples ever get reworked into a proper temples, theese could fit in there.

**Comment by Positronic-Girl** [comment]
Yeah this is fair; I've always found it weird that these monsters were in game when they made 0 sense lore-wise

**Comment by Hatfish** [comment]
Don't they still appear in the church of starry wisdom special, or was that quest and location removed?

**Comment by anothersimulacrum** [comment]
That sounds like something from a third party mod, it does not exist in anything in this repository.

**Pull request merged**
