### PR TITLE
Fix inappropriate color name spelling (grey -> gray)

### PR DESCRIPTION
**Pull request by illi-kun**
Game doesn't know what is "grey", so I've changed all instances of "grey" to more appropriate version of spelling.

Debug messages about that don't appear due to broken logic in color functions which is changed in another PR.

### CODE REVIEW

**Comment by SeanMirrsen** [comment]
I am confuse. How is game not know what is grey when it use grey everywhere?
(bad english on purpose :P)

I mean, really. Grey and gray are used interchangeably pretty much everywhere. I haven't seen either being called "inappropriate", except by whoever is sure that their way of spelling is superior.

**Comment by illi-kun** [comment]
Game knows English language even worse than I, so it recognize only 'gray'.

**Comment by chaosvolt** [comment]
So wait, did this PR fix things by way of breaking different things? The text here seems to imply going the sane route and letting either spelling be interpreted correctly, but discussion elsewhere implies that it instead changed the acceptable spelling entirely.

...and now I've forgotten which spelling is the 'murrican standard. :V

**Comment by Darkyhard** [comment]
Well, it didn't broke a thing, actually, but it caused a merge conflict.

**Comment by chaosvolt** [comment]
Ah, I see. That explains it. ;w;

**Comment by illi-kun** [comment]
Well, merge conflicts happens, especially with inconveniently big PRs.

**Comment by chaosvolt** [comment]
It was inevitable.

**Comment by SeanMirrsen** [comment]
It is terrifying,

**Pull request merged**
