### PR TITLE
Add PROFICIENCY_LIST.md for easier browsing of proficiencies

### PR DESCRIPTION
**Pull request by ERRORCODE509**
#### Summary
Infrastructure "Add PROFICIENCY_LIST.md"

#### Purpose of change
Currently there is no list of proficiencies, making it hard for anyone wanting to make a recipe use them to add them as a requirement, as well as making it difficult to include them in character creation.

#### Describe the solution
Adds PROFICIENCY_LIST.md so that contributors and modders can more easily find proficiencies, as well as their respective descriptions and IDs.

#### Describe alternatives you've considered
Typing every possible combination of characters that fit in 17.56Gb of plain-text, then writing them on paper and faxing the whole list to anyone who requests it.

#### Testing
Reading the file.

#### Additional context
Adding this file as requested by @actual-nh. Please note that this is the first PR I've ever done, and I likely did something wrong.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
This does not render properly.
https://github.com/ERRORCODE509/Cataclysm-DDA/blob/master/doc/PROFICIENCY_LIST.md

**Comment by casswedson** [comment]
https://github.com/ERRORCODE509/Cataclysm-DDA/pull/1 should fix that.

**Comment by BrettDong** [comment]
You also need to properly fill in the summary line:

---

#### Summary
Infrastructure "One line summary"

**Comment by actual-nh** [comment]
I will be assisting with the formatting after I wake up a bit more.

**Comment by ERRORCODE509** [comment]
Sorry for making a bunch of extra work for all of you. I'll assist in any way I can.

**Comment by Nabo92** [comment]
That's pretty cool! Would it be possible (in another PR) to access this info in game through a UI?

**Comment by ERRORCODE509** [comment]
Maybe if someone coded it in. I certainly can't, though.

**Comment by ZhilkinSerg** [comment]
> 
> 
> That's pretty cool! Would it be possible (in another PR) to access this info in game through a UI?

Proficiency descriptions are already available in @-menu.

**Comment by ERRORCODE509** [comment]
I think he meant the entire table, not just the descriptions. Maybe I'm wrong, though.

**Pull request merged**
