### PR TITLE
retain omt path when canceling auto move/drive

### LINKED ISSUE #71506: Canceling auto-move shouldn't clear your destination
### Is your feature request related to a problem? Please describe.

I use auto move to get around a lot. Often I'm looking out for something interesting along the path, and I press '.' to cancel the auto-move so I can stop and investigate. Unfortunately this clears the destination, so when I'm ready to move on I need to re-select the destination in order to continue. Especially if the destination is far away, this can be quite tedious.

### Solution you would like.

Canceling auto-move should stop the character but retain the destination, so that opening up the map and pressing 'g' will continue travel.

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nornagon**
#### Summary
Interface "Destination is no longer cleared when canceling automove/autodrive"

#### Purpose of change

Fixes #71506

#### Describe the solution

This leaves the `omt_path` in place when canceling automove and autodrive, instead of clearing it.

#### Describe alternatives you've considered

N/A

#### Testing

Tested manually by automoving/autodriving and canceling with <kbd>.</kbd>. Observed that the destination and path are still visible on the map screen after cancelling. Observed that <kbd>g</kbd> continues the automove/autodrive.

### CODE REVIEW

**Comment by RenechCDDA** [comment]
As I understand, `omt_path` contains an actual path of points to get to your destination. What happens if you interrupt autodrive, move to a completely different OMT, and try to resume?

**Comment by nornagon** [comment]
ach, I had thought it would repath when you went to navigate to the destination again, but it turns out it sends you to the beginning of the old path first. Moving to draft.

**Comment by nornagon** [comment]
Fixed. It turns out this was an already existing bug, which you can reproduce on current experimental:

1. Open the map and <kbd>W</kbd> path to somewhere, but don't automove yet
2. Move your character somewhere far away from current position
3. Open the map and <kbd>g</kbd>o to destination

character appears to move to beginning of the path first and thence to the destination. which is ... a bit weird

**Comment by Maleclypse** [comment]
PR Validator is still queued.  Hopefully it will run soon.

**Comment by nornagon** [comment]
@Maleclypse seems to be good now, not sure why it didn't run before.

**Pull request merged**
