### PR TITLE
Convert "vitamin_shop" item group to over-the-counter drug item group

### PR DESCRIPTION
**Pull request by Testudo-Cultu**
#### Summary

Content "Improve logic of vitamin_shop item group, allow pharmacies to contain cough syrup and antihistamines"

#### Purpose of change

The current vitamin_shop item group is used in a few locations for spawning basic drugs, but is part of the mall item group file. vitamin_shop currently acts as an item group for most over-the-counter drugs, yet its name implies it is only for supplements. vitamin_shop also contains what seems to be prescription sleeping pills, which is strange and should probably not be there. Lastly, vitamin_shop does not contain antihistamines despite containing over-the-counter painkillers, which is unusual considering how common antihistamines are. Cough syrup is found in pharmacies, but only in the sink or behind a locked door despite being internally labeled as over-the-counter drugs.

Currently, s_pharm cannot contain antihistamines, and s_pharm_1 can only contain antihistamines because softdrugs are set to spawn in the sink.

#### Describe the solution

Rename vitamin_shop to otc_drugs, because in its current state, it is more accurate to say it contains this type of item. Move the item group out of the mall's item group file and into drugs.json. Add antihistamines and cough syrup to it, remove what look like prescription sleeping pills, and adjust spawns so the item group is a bit more rounded.

#### Describe alternatives you've considered

I could have or maybe even should have not renamed the item group, but I felt I might as well do it because "vitamin_shop" is not a good name for this item group (in my opinion). I considered making a new item group entirely, but decided not to because it would have been nearly identical. s_pharm containing two rows of vitamin_shop shelves also lead me to believe that vitamin_shop was being used as an over-the-counter drug item group anyway.

#### Testing

Tested and it works exactly as intended. However, this will unsurprisingly cause issues with mods that rely on the vitamin_store item group. Secronom is one such mod. Thankfully, this will not cause crashes, but it will cause their locations to not contain as much medical stuff until the mapgen JSONs are updated.

#### Additional context

I am nearly certain someone will (rightfully) tell me I did something wrong.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Vitamin shop is based on stores like GNC and should still exist in malls, selling vitamins, herbal supplements, and protein powder. Malls typically do not have pharmacies or drugstores inside of them.

**Comment by Testudo-Cultu** [comment]
> Vitamin shop is based on stores like GNC and should still exist in malls, selling vitamins, herbal supplements, and protein powder. Malls typically do not have pharmacies or drugstores inside of them.

You are by no means wrong, but in this case, not only did vitamin_shop already contain pretty much all of these meds, the mall actually has the drugs_pharmacy item group spawning right next to the vitamin_shop items. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/b459ff571f4d86b0d3cec4e5f4d3bd6ca57a916f/data/json/mapgen/mall/mall_ground.json#L1460C1-L1460C77

This is one of multiple things that makes this PR a bit nebulous. I do think this was meant to be a store like GNC, like you said, but I don't know why a store like GNC would also have prescription narcotics. I could alter this PR to make the mall not spawn this item group at all, which is something I considered, but I don't know what the intention here was to begin with.

**Comment by fairyarmadillo** [comment]
Why not just take the improper items out of vitamin_shop? That's a lot less work and keeps the GNCs intact as intended.

If it's being misused elsewhere, you can just swap it for a pharmacy itemgroup in those places, no?

**Comment by Testudo-Cultu** [comment]
> Why not just take the improper items out of vitamin_shop? That's a lot less work and keeps the GNCs intact as intended.
> 
> If it's being misused elsewhere, you can just swap it for a pharmacy itemgroup in those places, no?

Well, the issue is that the pharmacy item groups contain prescription drugs and narcotics, which means they wouldn't work for pharmacy shelves, but you're right, honestly. I probably just over-complicated things by trying to be so conservative with my changes. I should separate the otc_drugs item group into a new item group and make the vitamin_shop item group contain the things it logically should. I should also remove the drugs_pharmacy item group from the mall completely, because as hard as I was trying to preserve someone's "vision," there's really just no reason at all a mall would have narcotics lying around.

**Comment by Testudo-Cultu** [comment]
> Why not just take the improper items out of vitamin_shop? That's a lot less work and keeps the GNCs intact as intended.
> 
> If it's being misused elsewhere, you can just swap it for a pharmacy itemgroup in those places, no?

Apparently there are actually areas in the US that have pharmacies in their malls as a common thing. It's strange to me, since I've never seen it myself, but there are/were genuinely people that confusingly decided they wanted to go into a mall every time they needed a refill on their meds. I do think a GNC makes more sense, but for now I'll let the pharmacy stay. Because I've learned quite a bit about how mapping works, I might revisit this and add a GNC to the mall.

Worth noting as well that this seems to be designed as a pharmacy, despite the creator making the custom vitamin_shop item group for it. There is a metal door protecting glass cabinets in the back of the room, much like you would expect for a pharmacy. No idea why they went this direction though.

**Comment by fairyarmadillo** [comment]
> > Why not just take the improper items out of vitamin_shop? That's a lot less work and keeps the GNCs intact as intended.
> > If it's being misused elsewhere, you can just swap it for a pharmacy itemgroup in those places, no?
> 
> Apparently there are actually areas in the US that have/had pharmacies in their malls as a common thing. It's strange to me, since I've never seen it myself, but there are/were genuinely people that confusingly decided they wanted to go into a mall every time they needed a refill on their meds. I do think a GNC makes more sense, but for now I'll let the pharmacy stay. Because I've learned quite a bit about how mapping works, I might revisit this and add a GNC to the mall.
> 
> Worth noting as well that this seems to be designed as a pharmacy, despite the creator making the custom vitamin_shop item group for it. There is a metal door protecting glass cabinets in the back of the room, much like you would expect for a pharmacy. No idea why they went this direction though.

I'm certain I have seen vitamin shops in CDDA malls that didn't have hard drugs in the back room. The mall I'm currently playing in has both one of those and a pharmacy. You may be confused because of this.

In any event, no prescription drugs should be out on shelves, and cough syrup should be on the shelf. When CDDA was first being made, it was common for cough syrup with codeine in it to be stored behind the counter, but now most pharmacies do not stock that particulat item IRL, and in any event it doesn't exist in our game.

**Comment by fairyarmadillo** [comment]
It sounds like the itemgroups need a full audit then. Any spot-fix you try is going to remove working content or makena hole somewhere else.

There's no good reason to remove the GNC style stores when we can just whip up a new itemgroup or go over the old ones with a fine toothed comb.

**Comment by Testudo-Cultu** [comment]
> It sounds like the itemgroups need a full audit then. Any spot-fix you try is going to remove working content or make a hole somewhere else, or both.
> 
> There's no good reason to remove the GNC style stores when we can just whip up a new itemgroup or go over the old ones with a fine toothed comb. Malls have too little variety as it is.

This is not a "spot-fix," nor does it remove working content or make a hole somewhere. The only real effect that players would notice is that they can find antihistamines and non-prescription cough syrup in pharmacies. What devs would notice is that the code infrastructure is very slightly improved because this somewhat commonly used drug item group is now part of drugs.json rather than the mall item groups file.

I can fix malls having the softdrugs item group very easily, but I don't want to add that to this PR because it's already a mess because of how I did it. It is a huge mess because, as I said, the scope of this PR was initially just to make pharmacies spawn antihistamines, but I decided to go further without using a proper pipeline. To clarify, this PR being a "mess" does not affect its functionality.

I am not removing any GNC-style stores, because upon closer inspection, it has become clear that they don't exist yet. I also never said I was going to or implied that I was doing that. I will instead try to add them, because it would make much more sense than the current random store that isn't even a pharmacy that sells antibiotics, oxygen tanks, sleeping pills, radiation pills and candy on the second floor of the mall. But, as I said, the currently existing mall pharmacy will remain unless someone else removes it.

**Comment by Testudo-Cultu** [comment]
Closed this for now because I made it with my master branch, which was stupid.

**Pull request closed without merging**
