### PR TITLE
[CR] Make comestibles give better nutrition when you are starving

### PR DESCRIPTION
**Pull request by tivec**
This PR comes from a report made by IRC user "aeoo". I you fast for 7 days, you do not need 7 days of food to get back up to satiated.

This patch makes it so that whenever you become famished or above, you start getting a bonus to the nutrition value. This bonus increases the closer to death by starvation you reach.

### CODE REVIEW

**Comment by Snaaty** [comment]
Hm, couldn't this lead to the awkward situation in which you'd rather wait a little until your hunger is worse in order to get more nutrition that eat that food you just found right now?

**Comment by tivec** [comment]
The values are up for tweaking, of course. They can be turned up toward the end, and tuned down in the beginning. I suppose showing the true nutrition value on the item instead of the modified one might be a good plan though.

**Comment by drbig** [comment]
@Snaaty Valid concern. My opinion is no, it won't make much sense to wait till you're starving to get more out of the food you have.

I assume here hunger penalties kicking in much sooner than any nutrient multipliers, so unless you're really short on food waiting is not a good idea. If you're short on food this still makes sense - you conserve the food by being famished most of the time (and with penalties) and the multipliers help you not die.

**Comment by Snaaty** [comment]
Okay, you're probably right, drbig.

Still, knowing about this
/* thresholds:
+ ** 100 : 1x
+ ** 300 : 2x
+ ** 1400 : 4x
+ ** 2800 : 6x
+ ** 6000 : 10x
+ */

Is making it possible for players to minmax their food consumption, as far as I can see, and the factors by which the nutrition is multiplied are pretty high. 

However, more important than preventing potential abuse of the system is imho, that this feature is properly documented somewhere. There are already more than enough mechanics/connections in the game that are not immediately obvious to the player.

**Comment by tivec** [comment]
That comment with the threshold can be removed, of course, but what does it matter, really? Anyone who has access to the code can figure out the thresholds. This goes for everything, really.

When it comes to minmaxing food consumption, staying at famished just for the food bonus needs to reconsider the negative effects as well.

I'd gladly document this mechanic somewhere, just not sure where.

**Comment by drbig** [comment]
Min-maxing is a non-issue, it's up to the player to choose how he/she wishes to play the game.

I don't see any need for documenting mechanics - there is the wiki for people that like to write/read instead of playing the game and figuring it out on their own (and again that's a particular player's choice). And code comments are code comments, should stay if they clarify the intent of the implementation (which I think they do in this case).

And the point here was that it was quite ridiculous that you had to eat 7 days worth of food to recover from 7 days of fasting. Given that hunger gives penalties and most food is perishable, I'd say this can at least be well balanced (if it isn't already with current thresholds/multipliers). It also adds gameplay depth as now it makes sense to ration your food if you're short on it.

**Comment by Snaaty** [comment]
Yeah, I am not really against this PR, and my initial qualms are gone. 

One problem I see though is, that a player who decides to have a look at the code (with comments or without) can see that waiting until he's over the threshold of hungry/very hungry/starving gives him more nutrition out of his food while a player who doesn't look at the code has no way of seeing that. He might know intuitively that rationing your food is good, but he doesn't know about the thresholds

**Comment by Zireael07** [comment]
@ Snaaty, I don't think a player being able to figure some stuff from the code is a problem here. The same situation applies to a load of things in Cata - and never stopped anyone.

**Comment by kevingranade** [comment]
Torn on this one, looks like I need to read up on rationing theory...

**Comment by drbig** [comment]
@kevingranade What I'm seeing here: assume you have a fixed amount of food available; you have a choice: a) go X days fully-satiated, or b) go Y days eating only when famished; with this patch in you can get a lot bigger Y than X (given your food can stay fresh that long), but at the cost of hunger penalties.

And there's still the original issue.

**Comment by DavidKeaton** [comment]
why not increase the hunger penalties? when one is hungry, that's all one thinks about.

**Comment by drbig** [comment]
@DavidKeaton That and/or tweak the thresholds/multipliers here. Indeed.

**Comment by KA101** [comment]
I'd say hunger should be a serious difficulty at Famished or worse.  Hungry and Very Hungry are there to let the player know, IMO, and I typically eat to that spec.

As for the OP, last I heard starvation tends to cause permanent metabolism changes, so getting a multiplier might have a chance to grant Light Eater... and -1 ST for lost muscle mass, etc.

**Comment by aierce** [comment]
Nice idea KA101 but maybe implement it as "malnutrition" disease instead of mutation, which can be cured after long period of health eating

**Comment by Zireael07** [comment]
+1 for Light Eater and -1 Str chance on starvation.

**Comment by Marrim** [comment]
Sure, eating only while famished will let you last longer. But considering the massive speed penalties from hunger, you won't necessarily get more stuff done in that increased time span.

**Comment by ejseto** [comment]
>Hm, couldn't this lead to the awkward situation in which you'd rather wait a little until your hunger is worse in order to get more nutrition that eat that food you just found right now?

It sounds gamey but people do this in real life. If you were in a survival scenario, you wouldn't just eat everything until you weren't hungry anymore, you'd ration it out to last longer.

>He might know intuitively that rationing your food is good, but he doesn't know about the thresholds

How about messages upon eating to indicate how effective it was?

"You've never tasted anything this good before! Hunger truly is the best sauce!"

It could also take traits into account:

"You'd normally never consider eating meat/veggies/fruit/junk food/etc. but beggars can't be choosers."

"You can't believe how good that meat/veggies/fruit/junk food/etc. was. What have you been missing out on all your life?

Maybe even have a small chance of canceling an aversion trait. Also, excessive hunger should probably lessen or even ignore morale bonuses as you scarf it down rather than savor it.

**Comment by Zireael07** [comment]
@ejseto : Good points.

**Comment by Coolthulhu** [comment]
It would be cool if you buffed the hunger penalties to compensate. Made them activate earlier and hit harder.
Also, maybe lower body temperature? Current effect of hunger on body temperature is low until the character is getting spammed by the "you're starving" messages. By making it more flat it would both explain the quick recovery and would make the effect more noticeable.

I don't like the idea of permanent character changes. Most of the effects of starvation should be reversible, due to the character "training" pretty much all day (running around with a heavy backpack, swinging a katana etc.). Basal metabolic rate can't go THAT much lower when you spend all your day working your ass off.
Like half of the difference in metabolism due to starvation that persists after it is due to combined effect of lowered body mass and reduced fidgeting.

**Comment by graysage1** [comment]
Looks like I've created a duplicate issue without being aware of this one, but my duplicate also mentions sleep as having a similar problem to hunger, if less extreme.

My input for hunger is as follows:

Firstly, how hunger affects individual depends on the individual and on training.  People who fast regularly fare much better than those who've never had to fast before who suddenly fast.  I remember when I fasted for the first time, I was overwhelmed on the second day.  One just the second day I could think of nothing but food and I was incapable of any kind of critical thinking.  However, I've fasted a few more times since then, and each time it got significantly easier.

One the second try I did 4 days, and on the third try I did a week.  Both of those went way, way smoother than my first attempt.  In both cases I could think rationally, and in both cases I was able to perform tasks like going to the store, walking with the dog and so on.  In other words, I wasn't disabled and I could think clearly.  So for me it seems like even minimal training resulted in a huge difference in how the hunger was affecting me.

So I suggest that hunger and hunger-based condition should be two separate things.  Hunger is roughly how full your stomach is, plus about 30 mins to 1 hour of digestion time.  And hunger-based condition is the influence of the event on your mental state.  So for a lot of people hunger may be a stressful event, but for spiritual and/or training-oriented people it may be an uplifting event.  In other words, the stomach contents and the blood sugar level are just one side of the story.

Also, it's often recommended to deliberately eat very little the first meal after a prolonged fast, because there is a danger of a stomach upset otherwise.  After a week long fast I had a light breakfast in the morning followed by a normal meal after a few hours.  I'm thinking those people who fast significantly longer, like 20 or 40 days, they may follow a more specialized regimen to break the fast, I don't know.

**Comment by tivec** [comment]
I don't think we want to expand the game into a nutrition simulator though. That would require labels on all items to show nutrition levels ;) But you do have some good points here @graysage1 - people definitely should eat less the first meal after fasting. However, that's not going to work out in a game like Cataclysm where the portion sizes are fixed like they are now. This is intended to hit some form of middle ground between realistic and unrealistic. And also, of course, it is a work in progress that will need balancing. 

@Coolthulhu: Buffing the negative effects of starvation is definitely something that can be done. Becoming more cold as you become more hungry makes sense too. I'll see what I can done with that.

**Comment by drbig** [comment]
I would like to one-up @ejseto ideas - especially the messages.

**Comment by facepalm** [comment]
There's also the health mechanic one could lean on: starvation is not very healthy.  It may be possible to carefully ration food, but that could still sap your health stat, which you could (partially?) counteract with a steady supply of vitamins and healthy choices about what foods you do eat.  

IIRC, there are IRL individuals who squeak by on ~500 calories and a ton of multivitamins a day, basing their diets on those restricted-intake mouse-longevity studies.  A steady state at 4x nutrition multiplier with minor hunger penalties, a healthy diet and 1/day vitamin use seems about right to me.

**Comment by Snaaty** [comment]
Normally a good idea, but imo the health stat is already vague and overused enough, so adding another component that is only loosely connected to the rest doesn't improve things.

**Pull request merged**
