### PR TITLE
Artisans: Provide buffer area around turrets

### LINKED ISSUE #65024: Gunsmith turrets shoots at all moving vehicles
### Describe the bug

Gunsmith's turrets will shoot at all moving vehicles. 

image

### Attach save file

N/A

### Steps to reproduce

1. New game
2. Reveal overmap
3. Teleport to gunsmith's home
4. Spawn in a vehicle
5. Drive close to the turrets
6. Get shredded into red mist

### Expected behavior

Gunsmith's turrets ignore vehicles?

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 3fe23d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ehughsbaird**
#### Summary
Bugfixes "Make it harder for the Artisans to accidentally shoot player vehicles"

#### Purpose of change
The artisans aren't aiming to kill random people (or shoot up their cars), they're aiming to trade. As such, it would make sense for there to be a warning before cars get in range of their turrets.
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/65024

#### Describe the solution
A little signposted roadblock is added on the road approaching their property, and a buffer area around to property is created to prevent roads from generating in range of their turrets.

Several placements of artisans on the overmap, showing no roads within 2 tiles of the property, other than the access road.
View of the new roadblock blocking the access road to the property. Road barricades block the entire road, with two signs sitting in front of them.
Text on the signs at the roadblock: "WARNING: Turrets will shoot at vehicles!"
Larger view of the new generation, with the roadblock. There is quite some distance between the roadblock and the entrance to the property.

#### Describe alternatives you've considered
There seems to be some discussion over simply making these turrets not target the vehicles. This solution fixed my issue and seems reasonable to me.

#### Testing
Find generation of the artisans. See that you cannot drive close enough to be shot by their turrets without hitting the roadblock warning of the turrets.

### CODE REVIEW

**Comment by Nebnis** [comment]
Maybe add like a row of signs so people actually pay attention? cause otherwise nobody on auto move gonna care ;3

**Comment by ehughsbaird** [comment]
There's a line of road barricades, that should cause autodrive problems and prompt investigation.

**Comment by fairyarmadillo** [comment]
This is a bandaid, not a real fix. The turrets should not shoot at cars and we shouldn't be putting information that suggests that these two technical experts have no idea how to control their creations.

**Comment by Tread4** [comment]
#65882 just got merged and is the preferred solution. However, maybe with a bit of fine tuning, this PR can be changed into "add flavour to the game" one.

Removing the roadblock but keeping the signs (with adjusted text) can be some way of not wasting this PRs workload while adding something to the game. The sign text can be smth along the lines "Traders welcome; hostiles beware of automated defence system"

Just brainstorming to avoid scrapping Ehughsbaird work altogether.

**Comment by ehughsbaird** [comment]
There is no need. The problem is fixed, I am happy with that.

**Pull request closed without merging**
