### PR TITLE
add movement mode coloration to panels, standardize mode letter fetching

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Interface "add movement mode coloration to panels, standardize mode letter fetching"

#### Purpose of change
It can be easy to lose track of which movement mode you're in. While there is overlay support in tilesets, not everyone is using a tileset with the movement mode support (or even using a tileset at all).

There is an attempt to show a movement mode letter (`W`, `R`, `C`) next to the most recent movement cost, but it's still relatively easy to lose track of walk, versus run, versus crouch.

A previous PR attempted this, but stalled out some time ago ( #31958 )

#### Describe the solution
Add colorization to the move cost/move mode indicator in the panels based on current movement mode.

I went with red for run and blue for crouch to go with "warm" and "cool" colorization, to help distinguish between "faster than walk" and "slower than walk". This should remain reasonably extensible if additional movement mode gradients get added.

For walk, I kept grey or white (depending on layout).

The movement cost also being colored is intentional; the actual movement cost and the movement mode are somewhat linked, and the more that gets colored the easier it is to notice the actual state. Only having a single character colored isn't a significant improvement over just changing the letter, in my opinion.

While I was doing this, I also standardized fetching the character used for the movement mode; they weren't all fetched the same (and one of the sidebars did not even use localized strings).

#### Describe alternatives you've considered
I still think there's room for some kind of overlay element that shows critical player status data (not only walk/run but also status effects that may require immediate attention), but I still haven't worked out how best to approach such a thing.

#### Additional context
image
image
image
image
image
image

### CODE REVIEW

**Comment by AMurkin** [comment]
You need to declare the functions at the beginning of the panels.cpp:
```cpp
nc_color move_mode_color( avatar &u );
std::string move_mode_string( avatar &u );
```

What if we use inverted mode for some important indicators?
```diff
     if( u.movement_mode_is( PMM_RUN ) ) {
-        return c_red;
+        return i_red;
     } else if( u.movement_mode_is( PMM_CROUCH ) ) {
-        return c_light_blue;
+        return i_light_blue;
     } else {
         return c_light_gray;
     }
```

R
C

**Comment by esotericist** [comment]
Speaking for myself, I find that kind of inversion fairly difficult to read. :( I get what you're after, but for me at least, it's rather unpleasant. 

can you clarify what you mean about needing to declare the functions at the beginning? A lot of things in the codebase have local helper functions that don't have separate declarations, so it didn't seem to be a common pattern.

**Comment by AMurkin** [comment]
Might be wrong, but that's how I fixed the errors from the Travis log:
```
1159src/panels.cpp:1003:10: error: no previous declaration for ‘nc_color move_mode_color(avatar&)’ [-Werror=missing-declarations]
1160 nc_color move_mode_color( avatar &u )
1161          ^~~~~~~~~~~~~~~
1162src/panels.cpp:1014:13: error: no previous declaration for ‘std::__cxx11::string move_mode_string(avatar&)’ [-Werror=missing-declarations]
1163 std::string move_mode_string( avatar &u )
1164             ^~~~~~~~~~~~~~~~
```

**Comment by esotericist** [comment]
> Might be wrong, but that's how I fixed the errors from the Travis log:
> 

Oh, is that a clang_tidy thing?

I'll look into it after I finish up another task.

**Comment by esotericist** [comment]
Oh, looking at the tests, it looks like something gcc doesn't like that clang is ambivalent about. weird..

**Comment by jbytheway** [comment]
The "no previous declaration" warning (treated as error) is unhelpfully worded.  The right solution here is not to add declarations, but to mark them static.

The reason the warning exists is to enforce that for every function, *either* it's a public function (in which case it will have a previous declaration in a header) *or* it's a local helper function (in which case it should be static).  Unfortunately, the warning message doesn't mention the option of marking it static.

**Comment by esotericist** [comment]
> The "no previous declaration" warning (treated as error) is unhelpfully worded. The right solution here is not to add declarations, but to mark them static.
> 
> The reason the warning exists is to enforce that for every function, _either_ it's a public function (in which case it will have a previous declaration in a header) _or_ it's a local helper function (in which case it should be static). Unfortunately, the warning message doesn't mention the option of marking it static.

GCC giving misleading and unhelpful message? Shock, gasp.

Thanks for the explanation. I can act on this.

**Comment by AMurkin** [comment]
Ah. Sorry for the confusion.

**Comment by esotericist** [comment]
Jenkins rebuild

**Pull request merged**
