### PR TITLE
Fix weariness not saving or loading

### LINKED ISSUE #44299: Wearyness gameplay quirks
# Describe the bug

Wearyness shows 2 separate debuffs, wearyness messages appear while character is sleeping

# Steps To Reproduce

1) Get weary
2) Start sleeping
3) During sleep you get wearyness messages
4) On wakeup you have 2 weary-ness debuffs in @

Save attached if it helps

# Expected behavior

One wearyness debuff, no messages during sleep

# Screenshots

image
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6108-g9a07fb7dcd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    _CustomTweaks [_CustomTweaks]
]

# Additional context

[Nectar.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5252598/Nectar.zip)

### LINKED ISSUE #44604: [Bug] [C++] [Character breaking] I think I found why Weariness sometimes doesn't clear correctly but I need help fixing it
# Describe the bug
Sometimes weariness doesn't reduce while sleeping

# Steps To Reproduce
In the saved game note the weariness level
Sleep
Note that the log doesn't indicate any change in weariness
After waking up check weariness level

# Expected behavior
Sleeping should reduce weariness

# Screenshots
Before sleep
image

After sleep (note the log)
image

# Versions and configuration

- OS: Microsoft Windows 10 Pro
    - OS Version: 10.0 1909
- Game Version: 0.E-6466-g387e60f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context
The weariness cleared correctly the first time (after playing the day, then returning home and sleeping)
I saved before sleeping, then had an issue later on and reloaded
After reloading (right before sleeping) weariness wouldn't clear anymore.
Possibly related to some value not properly saved and reloaded?

Save game:
[Mont Clare.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5322666/Mont.Clare.zip)

### PR DESCRIPTION
**Pull request by Xpyder**
#### Summary

SUMMARY: Bugfixes "Fixes weariness not saving or loading"

#### Purpose of change
Fix weariness not saving or loading

Fixes #44604
Fixes #44299

#### Describe the solution

When weariness was added, it seems it wasn't added to Store or Load.
This results in inconsistent results.  Work all day and sleep? weariness clears.  Save before you sleep and have to reload? now you get 2 weariness debuffs, the largest of which doesn't clear until you reach at least that level and sleep in a single session.

#### Describe alternatives you've considered

N/A

#### Testing

Was successfully compiled and tested by Trioct

### CODE REVIEW

**Comment by Xpyder** [comment]
Also I edited through the Github on the Web so sorry if the linting or spacing is bad

**Comment by Xpyder** [comment]
Also note this doesn't include any explicit fixes for saves already in a bugged state.
There is an implicit fix though, if they work up to their existing level of exhaustion then it should fix on its own

**Comment by Trioct** [comment]
Surprised you figured this out with no compiler.
I made a pr on your pr, not sure how that works but it should fix the errors I think probably hopefully.

**Comment by Xpyder** [comment]
I was thinking about this overnight while I was sleeping and I anticipated this might happen.

My guess is that character.weary needs a ::serialize and ::deserialize since it doesn't have a declared type and it's not a simple construct.  Not sure if it will need a full declaration with typing for its subcomponents or not though.

@Trioct  I'll look for your PR and link it here for easy trailing from the issue tickets

**Comment by Xpyder** [comment]
the travis-ci error is as follows (might be unrelated to this merge)

```
MOD> -------------------------------------------------------------------------------
MOD> npc-movement
MOD>   Player in vehicle & NPCs escaping dangerous terrain
MOD> -------------------------------------------------------------------------------
MOD> ../tests/npc_test.cpp:412
MOD> ...............................................................................
MOD> 
MOD> ../tests/npc_test.cpp:256: FAILED:
MOD>   REQUIRE( guy != nullptr )
MOD> with expansion:
MOD>   nullptr != nullptr
MOD> with messages:
MOD>   Should not crash from infinite recursion
MOD>   NPC on acid should not acquire unstable footing status
```

**Comment by Trioct** [comment]
Seems unrelated, and it's just a test error, looks like it still compiles and works fine. I tested on my machine before I suggested changes, too.

**Comment by Xpyder** [comment]
Ok, I haven't seen enough of the new ones to know how important the automatic tests are

**Comment by Xpyder** [comment]
the clang-tidy error is a few (service unavailable).  I'm guessing that's the linter so I double checked the spacing and it looks to be equivalent to the rest of the file but if anything needs changing just let me know

**Comment by Xpyder** [comment]
Since the errors appear to be transient, should I re-submit it or just wait?

**Comment by Trioct** [comment]
I'd just leave it. It's not rare to get random errors on your pr when compiling a project this big. Someone will probably bother us if there's something they don't like. Should just be a waiting game for now.

**Comment by anothersimulacrum** [comment]
Oh wow, can't believe I forgot this. Thank you for the fix.

**Pull request merged**
