### PR TITLE
Let go of controls if controls are lost

### LINKED ISSUE #20795: Destroying vehicle controls while driving makes it impossible to do anything
Savefile: [Dacula.zip](https://ufile.io/857251)

This situation is quite rare but not impossible.

Steps: increase speed once and keep turning to the left until vehicle controls break down. If they don't - just quit without saving and try again. After breaking the controls the only way to get off the bike would be via debug menu, otherwise the game keeps complaining about not having controls.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20795.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Why did you remove the `return`?

**Comment by Night-Pryanik** [comment]
>Why did you remove the return?

I thought it worked like this: if check is true, then show the message, do nothing more and exit from cycle.
Now it doing some action (letting go of controls) if check is true, so `return` is no longer needed. Am I mistaken?

**Comment by AMurkin** [comment]
Exit from what cycle?

**Comment by Coolthulhu** [comment]
The rest of the function covers turning, so by not returning you allow one turn of turning.

**Comment by Night-Pryanik** [comment]
> Exit from what cycle?

My bad, I meant exit from checking.

**Pull request merged**
