### PR TITLE
Remove Fuji

### PR DESCRIPTION
**Pull request by NotFuji**
#### Summary
Mods "Remove Fuji"

Fine, keep your mods, leave me out of it.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Is it even possible w/o violating Attribution term of our license?

**Comment by NotFuji** [comment]
> Is it even possible w/o violating Attribution term of our license?

https://law.stackexchange.com/questions/52316/removal-of-content-under-creative-commons

**Comment by Night-Pryanik** [comment]
@NotFuji could you please explain why are you removing your mods?

**Comment by NotFuji** [comment]
> @NotFuji could you please explain why are you removing your mods?

I do not condone the opinions and actions of prominent members of the development team and community.

**Comment by andrei8l** [comment]
The CDDA community is very large and I'm sure there are many players who enjoy your work. Is your spat with some dev worth more than that?

On the other hand, if they're killing baby seals maybe you should let everyone know...

**Comment by NotFuji** [comment]
> The CDDA community is very large and I'm sure there are many players who enjoy your work. Is your spat with some dev worth more than that?

Yes.  Call me petty, but someone needs to stand up.  I'm not going to pretend like anyone actually cares dearly enough about me or my content to have any tangible effect, but doing what I can is better than doing nothing.

**Comment by Termineitor244** [comment]
> 
> Yes. Call me petty, but someone needs to stand up. I'm not going to pretend like anyone actually cares dearly enough about me or my content to have any tangible effect, but doing what I can is better than doing nothing.

I liked the fuji additions that has been merged to the main game, if you want to leave the project then its up to you but whatever the reason... Thank you for your contributions!

**Comment by kevingranade** [comment]
As ZhilkinSerg points out, we are not *allowed* to remove attribution, and naming the mod and the files after yourself is a form of attribution.
Mods in DDA are most definitely not "Collections" from the point of view of the CC license, unless specifically noted, everything in the repository is considered a derivative of previous versions of the game.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Is it even possible w/o violating Attribution term of our license?
> 
> https://law.stackexchange.com/questions/52316/removal-of-content-under-creative-commons

We are not creating a "Collection" though - your "Work" must be attributed.

**Comment by NotFuji** [comment]
This is a fucking joke.  Fuck all of you.

**Comment by kevingranade** [comment]
Chill out, you cited a source that said,
```
You can't

Under clause 7(b) of the CC-SA-BY 3.0 the licence is irrevocable providing that the licensee complies with its terms.
However, ...

It appears that your work is part of a Collection (as defined and under clause 4(a), the licensee has this obligation:
```
Which is what we responded to, don't blame us for you citing a source that contradicts your request.

Now that you've actually said something pertinent, I can revisit this.

**Comment by Zireael07** [comment]
Hm, I would argue that mods shipped with the base game constitute a "collection" (they are clearly delineated as something different than the base game itself)...

**Comment by kevingranade** [comment]
Obsoleted by #52736

**Pull request closed without merging**
