### PR TITLE
Added Glasses Shop

### PR DESCRIPTION
**Pull request by Someoneman**
Adds a new location in towns, glasses shop. May contain glasses of various types, contact lenses, eyedrops, saline solutions, screwdriver sets, and pliers. Also has a locked back room that might contain vision-related bionics.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
You need to run the glasses store mapgen through http://dev.narc.ro/cataclysm/format.html

**Comment by Mecares** [comment]
Possible additional loot in my humble opinion: 
High Quality Lenses, Magnifying glasses, Binoculars, scopes, painkillers for the cbms,  broken eyebots, maybe also night vision goggles and cameras, or welding goggles

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by thethunderhawk** [comment]
If one were looking for more practicality for this building, they could include an eye exam room in the back that might include antibiotics (for eye infections) and perhaps something with glare protection 2 (for when they administer that chemical that dialates your pupils and makes your eyes super sensitive to light).

Alternatively, a pair of those eclipse glasses with glare protection 2 might be a good thing to include.

**Comment by Theundyingcode** [comment]
> for when they administer that chemical that dilates your pupils and makes your eyes super sensitive to light).

It's been 4-5 years but last time I got an eye exam with said chems, they gave me "sun glasses" that were basically a strip of dark film with a noise slot cut out and rounded edges.  The thing naturally wanted to roll up which was enough to make it cling to your face.

**Comment by thethunderhawk** [comment]
>...enough to make it cling to your face 

Sounds comfy! Probably not worth glare protection 2 though. Those eclipse glasses could still be a nice piece of niche loot though.
Also IIRC safety goggles are part of the chemistry set recipe, if they were a real common spawn here that could be another reason for an early player to consider making a stop through the glasses shop.
Also, skill magazines and snacks could be in the front room waiting area, if this is a place where eye exams happen.

**Comment by Night-Pryanik** [comment]
> skill magazines

I'd say there should be entertainment, fun-only magazines.

**Comment by ZhilkinSerg** [comment]
Marking as `Stalled`, but feel free to reopen when you feel you can finish this PR.

**Pull request closed without merging**
