### PR TITLE
Make more zombies wear wedding rings

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Content "Make more zombies wear wedding rings"

#### Purpose of change

Wedding rings are very rare in zombie loot compared to how many people you see wearing them in real life.

#### Describe the solution

Add wedding rings to `default_zombie_clothes`. The percentage is somewhat of a guesstimate--while the stats of percentage of adults who are married are available (~50% in America), there's no easy information for "percentage of married adults who do not wear their ring," so I went with 2/3rds of that 50% wear their ring, leading to a 33% drop rate. 

#### Testing

Killed some zombies, found wedding rings.

### CODE REVIEW

**Comment by NetSysFire** [comment]
I would not be surprised if the spawn rate was cut back when we did not have subtypes for loot and zombie children were spawning with wedding dresses and rings and other inappropriate stuff.

I looked into the code and I am unsure whether or not that change applies to zombie children, as they are copied from the zombie base template which uses that loot group. Please make sure these do not spawn on them.

**Comment by Standing-Storm** [comment]
Zombie children do copy from zombie base, but they [override the death drops](https://github.com/CleverRaven/Cataclysm-DDA/blob/f71f48dc8ed6e02ff7416d211992fe1dd9426594/data/json/monsters/zed_children.json#L22) with their own special loot group.

Results of the most common drops in the zombie child clothes loot group: 

Untitled2

No wedding rings.

(some oddities, though--union suits?)

**Comment by PatrikLundell** [comment]
I haven't been playing actively for a while, but wedding rings were encountered all over the place, including weird cases where multiple wedding rings were worn. Serial marriage trophies (is that a thing?)? Polygamy? ...

**Comment by Night-Pryanik** [comment]
This shouldn't break anything, so let's merge this.

**Comment by Standing-Storm** [comment]
> I haven't been playing actively for a while, but wedding rings were encountered all over the place, including weird cases where multiple wedding rings were worn. Serial marriage trophies (is that a thing?)? Polygamy? ...

Wedding rings are a possible drop, but it looks like from generic zombie clothes it's a 15% chance to pull from `accesories_personal_unisex`, in which wedding rings have `"prob": 1`

`accessory_ring` might be what you're thinking of, since it has `{ "item": "ring_wedding", "prob": 50, "count": [ 1, 2 ] }` right at the top, but...apparently it's not referenced anywhere? Doing a search for it only pulls up the group definition and an Aftershock copy-from to add titanium rings, nothing else.

**Comment by PatrikLundell** [comment]
I don't know where it came from, only that I've seen it.

**Pull request merged**
