### PR TITLE
Expanded plate mail pt 2

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "More plate armor"

#### Purpose of change
Crafting an entire suit of plate armor is a long process, splitting it into pieces makes life easier and allows for more customization of armor.

#### Describe the solution
Adds separate torso, arm, and leg sections. Each arm and leg piece is a single limb that can be swapped.

#### Describe alternatives you've considered
None

#### Testing
WIP

#### Additional context
@Paprika-H is working on separated padded armor pieces which should work well with this.

### CODE REVIEW

**Comment by Alex-Folts** [comment]
I think XL variants should cost less compared to normal. It weight more, but we selling it not for scrap, so price defined by applicability, there should be less demand for mutant size armor so price should be lower.

**Comment by bombasticSlacks** [comment]
You don't have to worry about it if you don't want to but in a lot of cases the the current armors are set up so chest pieces include hips and shoulder. Examples are the Heavy Ballistic Vest, Cuirass, Thasalonian, Lorica

So if your arm and leg guards include the hips and shoulders you wont be able to mix and match with the old stuff.

**Comment by Drew4484** [comment]
> I think XL variants should cost less compared to normal. It weight more, but we selling it not for scrap, so price defined by applicability, there should be less demand for mutant size armor so price should be lower.

Honestly I haven't balanced any of the costs for these pieces, once I have recipes (and a valid cost list) and vendor/NPC crafts as an option I'll go back and cost things out.

**Comment by Drew4484** [comment]
> You don't have to worry about it if you don't want to but in a lot of cases the the current armors are set up so chest pieces include hips and shoulder. Examples are the Heavy Ballistic Vest, Cuirass, Thasalonian, Lorica
> 
> So if your arm and leg guards include the hips and shoulders you wont be able to mix and match with the old stuff. 
> 
> Also I really like your setup with 95% coverage for most the protection and 100% coverage for a small base thickness. Very good idea.

Yeah I'm not sure how to bridge that gap, maybe I need to add extra parts needed for the full suit. The layering was Kevin's solution, I'm quite happy with it!

**Comment by bombasticSlacks** [comment]
you could do a find replace for each of:
```
"covers": [ "arm_l", "arm_r" ],
```
to 
```
"covers": [ "arm_l", "arm_r" ], "specifically_covers": [ "arm_lower_r", "arm_lower_l", "arm_elbow_r", "arm_elbow_l", "arm_upper_r", "arm_upper_l" ]
```
and
```
"covers": [ "leg_l", "leg_r" ],
```
to
```
"covers": [ "leg_l", "leg_r" ], "specifically_covers": [ "leg_lower_r", "leg_lower_l", "leg_knee_r", "leg_knee_l", "leg_upper_r", "leg_upper_l" ]
```
but for torso you would probably need to split it into 3 armor entries like for example lightplate is:
```
      { "encumbrance": 20, "coverage": 95, "covers": [ "torso" ] },
      {
        "encumbrance": 4,
        "coverage": 95,
        "covers": [ "arm_l", "arm_r" ],
        "specifically_covers": [ "arm_shoulder_l", "arm_shoulder_r" ]
      },
      {
        "encumbrance": 4,
        "coverage": 95,
        "covers": [ "leg_l", "leg_r" ],
        "specifically_covers": [ "leg_hip_l", "leg_hip_r" ]
      }
```
you would also need to spread the arm and leg encumbrance out onto the torso pieces so that 20% of the current arm and leg encumbrance is instead there. Otherwise you would need additional shoulder and hip guards. **again don't feel obligated it would be a lot of JSON to change just thought I would let you know**

**Comment by Faalagorn** [comment]
I found it too when translating, it seems that all the names could use the fixes for these names

**Comment by Faalagorn** [comment]
> Spell checker encountered unrecognized words in the in-game text added in this pull request. See below for details.
> Click to expand
> 
>     * A **chestplate**, 4 mm thick.  Made with high carbon steel offering excellent protection.
> 
>     * A **chestplate**, 4 mm thick.  Made with tougher medium steel, this offers solid protection.
> 
>     * A **chestplate**, 4 mm thick.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * A **chestplate**, 4 mm thick.  The mild steel has been case hardened, offering superior protection.
> 
>     * A **chestplate**, 4 mm thick.  This one has been made with mild steel.
> 
>     * A heavy **armguard**, 2.25 mm at the thickest.  Made with high carbon steel offering excellent protection.
> 
>     * A heavy **armguard**, 2.25 mm at the thickest.  Made with tougher medium steel, this offers solid protection.
> 
>     * A heavy **armguard**, 2.25 mm at the thickest.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * A heavy **armguard**, 2.25 mm at the thickest.  The mild steel has been case hardened, offering superior protection.
> 
>     * A heavy **armguard**, 2.25 mm at the thickest.  This one has been made with mild steel.
> 
>     * A heavy **chestplate**, 6 mm thick.  Made with high carbon steel offering excellent protection.
> 
>     * A heavy **chestplate**, 6 mm thick.  Made with tougher medium steel, this offers solid protection.
> 
>     * A heavy **chestplate**, 6 mm thick.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * A heavy **chestplate**, 6 mm thick.  The mild steel has been case hardened, offering superior protection.
> 
>     * A heavy **chestplate**, 6 mm thick.  This one has been made with mild steel.
> 
>     * A light **armguard**, 1.25 mm at the thickest.  Made with high carbon steel offering excellent protection.
> 
>     * A light **armguard**, 1.25 mm at the thickest.  Made with tougher medium steel, this offers solid protection.
> 
>     * A light **armguard**, 1.25 mm at the thickest.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * A light **armguard**, 1.25 mm at the thickest.  The mild steel has been case hardened, offering superior protection.
> 
>     * A light **armguard**, 1.25 mm at the thickest.  This one has been made with mild steel.
> 
>     * A light **chestplate**, 2 mm thick.  Made with high carbon steel offering excellent protection.
> 
>     * A light **chestplate**, 2 mm thick.  Made with tougher medium steel, this offers solid protection.
> 
>     * A light **chestplate**, 2 mm thick.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * A light **chestplate**, 2 mm thick.  The mild steel has been case hardened, offering superior protection.
> 
>     * A light **chestplate**, 2 mm thick.  This one has been made with mild steel.
> 
>     * An **armguard**, 1.75 mm at the thickest.  Made with high carbon steel offering excellent protection.
> 
>     * An **armguard**, 1.75 mm at the thickest.  Made with tougher medium steel, this offers solid protection.
> 
>     * An **armguard**, 1.75 mm at the thickest.  The medium steel has been quenched and tempered, offering top of the line protection.
> 
>     * An **armguard**, 1.75 mm at the thickest.  The mild steel has been case hardened, offering superior protection.
> 
>     * An **armguard**, 1.75 mm at the thickest.  This one has been made with mild steel.
> 
>     * XL case hardened 1.25 mm **armguard**
> 
>     * XL case hardened 1.25 mm **armguards**
> 
>     * XL case hardened 1.75 mm **armguard**
> 
>     * XL case hardened 1.75 mm **armguards**
> 
>     * XL case hardened 2 mm **chestplate**
> 
>     * XL case hardened 2 mm **chestplates**
> 
>     * XL case hardened 2.25 mm **armguard**
> 
>     * XL case hardened 2.25 mm **armguards**
> 
>     * XL case hardened 4 mm **chestplate**
> 
>     * XL case hardened 4 mm **chestplates**
> 
>     * XL case hardened 6 mm **chestplate**
> 
>     * XL case hardened 6 mm **chestplates**
> 
>     * XL high steel 1.25 mm **armguard**
> 
>     * XL high steel 1.25 mm **armguards**
> 
>     * XL high steel 1.75 mm **armguard**
> 
>     * XL high steel 1.75 mm **armguards**
> 
>     * XL high steel 2 mm **chestplate**
> 
>     * XL high steel 2 mm **chestplates**
> 
>     * XL high steel 2.25 mm **armguard**
> 
>     * XL high steel 2.25 mm **armguards**
> 
>     * XL high steel 4 mm **chestplate**
> 
>     * XL high steel 4 mm **chestplates**
> 
>     * XL high steel 6 mm **chestplate**
> 
>     * XL high steel 6 mm **chestplates**
> 
>     * XL medium steel 1.25 mm **armguard**
> 
>     * XL medium steel 1.25 mm **armguards**
> 
>     * XL medium steel 1.75 mm **armguard**
> 
>     * XL medium steel 1.75 mm **armguards**
> 
>     * XL medium steel 2 mm **chestplate**
> 
>     * XL medium steel 2 mm **chestplates**
> 
>     * XL medium steel 2.25 mm **armguard**
> 
>     * XL medium steel 2.25 mm **armguards**
> 
>     * XL medium steel 4 mm **chestplate**
> 
>     * XL medium steel 4 mm **chestplates**
> 
>     * XL medium steel 6 mm **chestplate**
> 
>     * XL medium steel 6 mm **chestplates**
> 
>     * XL mild steel 1.25 mm **armguard**
> 
>     * XL mild steel 1.25 mm **armguards**
> 
>     * XL mild steel 1.75 mm **armguard**
> 
>     * XL mild steel 1.75 mm **armguards**
> 
>     * XL mild steel 2 mm **chestplate**
> 
>     * XL mild steel 2 mm **chestplates**
> 
>     * XL mild steel 2.25 mm **armguard**
> 
>     * XL mild steel 2.25 mm **armguards**
> 
>     * XL mild steel 4 mm **chestplate**
> 
>     * XL mild steel 4 mm **chestplates**
> 
>     * XL mild steel 6 mm **chestplate**
> 
>     * XL mild steel 6 mm **chestplates**
> 
>     * XL tempered 1.25 mm **armguard**
> 
>     * XL tempered 1.25 mm **armguards**
> 
>     * XL tempered 1.75 mm **armguard**
> 
>     * XL tempered 1.75 mm **armguards**
> 
>     * XL tempered 2 mm **chestplate**
> 
>     * XL tempered 2 mm **chestplates**
> 
>     * XL tempered 2.25 mm **armguard**
> 
>     * XL tempered 2.25 mm **armguards**
> 
>     * XL tempered 4 mm **chestplate**
> 
>     * XL tempered 4 mm **chestplates**
> 
>     * XL tempered 6 mm **chestplate**
> 
>     * XL tempered 6 mm **chestplates**
> 
>     * case hardened 1.25 mm **armguard**
> 
>     * case hardened 1.25 mm **armguards**
> 
>     * case hardened 1.75 mm **armguard**
> 
>     * case hardened 1.75 mm **armguards**
> 
>     * case hardened 2 mm **chestplate**
> 
>     * case hardened 2 mm **chestplates**
> 
>     * case hardened 2.25 mm **armguard**
> 
>     * case hardened 2.25 mm **armguards**
> 
>     * case hardened 4 mm **chestplate**
> 
>     * case hardened 4 mm **chestplates**
> 
>     * case hardened 6 mm **chestplate**
> 
>     * case hardened 6 mm **chestplates**
> 
>     * high steel 1.25 mm **armguard**
> 
>     * high steel 1.25 mm **armguards**
> 
>     * high steel 1.75 mm **armguard**
> 
>     * high steel 1.75 mm **armguards**
> 
>     * high steel 2 mm **chestplate**
> 
>     * high steel 2 mm **chestplates**
> 
>     * high steel 2.25 mm **armguard**
> 
>     * high steel 2.25 mm **armguards**
> 
>     * high steel 4 mm **chestplate**
> 
>     * high steel 4 mm **chestplates**
> 
>     * high steel 6 mm **chestplate**
> 
>     * high steel 6 mm **chestplates**
> 
>     * medium steel 1.25 mm **armguard**
> 
>     * medium steel 1.25 mm **armguards**
> 
>     * medium steel 1.75 mm **armguard**
> 
>     * medium steel 1.75 mm **armguards**
> 
>     * medium steel 2 mm **chestplate**
> 
>     * medium steel 2 mm **chestplates**
> 
>     * medium steel 2.25 mm **armguard**
> 
>     * medium steel 2.25 mm **armguards**
> 
>     * medium steel 4 mm **chestplate**
> 
>     * medium steel 4 mm **chestplates**
> 
>     * medium steel 6 mm **chestplate**
> 
>     * medium steel 6 mm **chestplates**
> 
>     * mild steel 1.25 mm **armguard**
> 
>     * mild steel 1.25 mm **armguards**
> 
>     * mild steel 1.75 mm **armguard**
> 
>     * mild steel 1.75 mm **armguards**
> 
>     * mild steel 2 mm **chestplate**
> 
>     * mild steel 2 mm **chestplates**
> 
>     * mild steel 2.25 mm **armguard**
> 
>     * mild steel 2.25 mm **armguards**
> 
>     * mild steel 4 mm **chestplate**
> 
>     * mild steel 4 mm **chestplates**
> 
>     * mild steel 6 mm **chestplate**
> 
>     * mild steel 6 mm **chestplates**
> 
>     * tempered 1.25 mm **armguard**
> 
>     * tempered 1.25 mm **armguards**
> 
>     * tempered 1.75 mm **armguard**
> 
>     * tempered 1.75 mm **armguards**
> 
>     * tempered 2 mm **chestplate**
> 
>     * tempered 2 mm **chestplates**
> 
>     * tempered 2.25 mm **armguard**
> 
>     * tempered 2.25 mm **armguards**
> 
>     * tempered 4 mm **chestplate**
> 
>     * tempered 4 mm **chestplates**
> 
>     * tempered 6 mm **chestplate**
> 
>     * tempered 6 mm **chestplates**
> 
> 
> This alert is automatically generated. You can simply disregard if this is inaccurate, or (optionally) you can also add the new words to `tools/spell_checker/dictionary.txt` so they will not trigger an alert next time.

I found it too when translating, it seems that all the names could use the fixes for these names

**Comment by Faalagorn** [comment]
They all also miss the "pair of" by the way :)

**Comment by Faalagorn** [comment]
Oh and finally, I think in English there's no space between the number and `mm` string, so it should be `1.25mm` for example.

**Comment by Drew4484** [comment]
> They all also miss the "pair of" by the way :)

These aren't pairs, each piece covers one limb.

**Comment by Drew4484** [comment]
> Oh and finally, I think in English there's no space between the number and `mm` string, so it should be `1.25mm` for example.

The space matched the code style, but can be removed from the title and description for clarity.

**Comment by Faalagorn** [comment]
> > They all also miss the "pair of" by the way :)
> 
> These aren't pairs, each piece covers one limb.

Oh, that makes more sense then

**Pull request merged**
