### PR TITLE
Urban Development Test City

### PR DESCRIPTION
**Pull request by acidia**
This ISN'T the fifth step to implementing the urban development concept #21488.  This is the test build that I'm currently doing bug testing on.  It contains buildings up to 75 (-NPCs).  There are two mods now, Urban Development will add all 75 buildings to your game with min occurrences set to 0 so they won't interfere with other specials.  Prototype City is a single static city that spawns all of the buildings in one place (no where else) and represents the style of city I'm shooting for eventually. 

The other half of the buildings 
<a href="https://imgur.com/GiCxyko"></a>
<a href="https://imgur.com/QXcggzU"></a>
<a href="https://imgur.com/HcZVrSx"></a>
<a href="https://imgur.com/WEapePC"></a>
<a href="https://imgur.com/ZMdk6nh"></a>
<a href="https://imgur.com/3sqT8Zu"></a>
<a href="https://imgur.com/1zbmN3n"></a>
This is what the static city looks like on the over map at the moment.
<a href="https://imgur.com/CyDP2i1"></a>
Descriptions for the buildings are in the forum thread.

Now working on updating all of the subways to reflect the wonderful improvements by ZhilkinSerg and the minor errors mentioned on the forum.

Forum Thread: https://discourse.cataclysmdda.org/t/spoilers-urban-development/14068

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Awesome!

**Comment by budg3** [comment]
In Urban_Development:
0:16:34.828 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgreen).  Please update mod that uses that.
0:16:34.875 WARNING : Deprecated foreground color suffix was used: (lt) in (i_ltgray).  Please update mod that uses that.

**Comment by acidia** [comment]
Added the z-2 subways and fixed color, tracking that the subway tunnels are defaulting to sewers for some reason.

**Comment by BorkBorkGoesTheCode** [comment]
@acidia try running the mapgen through the weblinter. If that doesn't work, try inspecting the file with a hexeditor and remove any UTF code.

**Comment by acidia** [comment]
I think it is the same line ending problems that I ran into with the other parts.  Everything was ok when I could drag all of the files onto the browser to upload them but when I attempt to edit an existing file the browser converts all EOL characters from LF to CR LF which breaks the linting.

**Comment by Wishbringer** [comment]
I use the free software SourceTree and git bash.

**Comment by Night-Pryanik** [comment]
jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Do you need this to be merged?

**Comment by acidia** [comment]
Nope, this is just my giant tracker for all the parts that need to be updated and for anyone to test them out.  I cut off ten buildings at a time and put them in little PRs.  I typically work on jsons when I don't have much free time because they are easier to pick up and put down.  So, based on my work schedule I'll probably be working on this in 1.5 - 2 weeks, as soon as the faction base is neat and tidy.

**Pull request closed without merging**
