### PR TITLE
Don't enforce trait points limit in freeform

### LINKED ISSUE #22667: The freeform pool option doesn't work.
Game version: 0.C-25560-g6b3f88d9ba

Operating system: Fedora 27 amd64

Tiles or curses: curses

Mods active: none

### Expected behavior
The freeform pool option should allow for an unlimited amount of available traits, stats, and skills.

### Actual behavior
It's still limited.

### Steps to reproduce the behavior 
Try to create a custom character with the freeform option, and attempt to add more than 12 traits.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Also don't show current/max trait points on TRAITS tab in freeform.

Closes #22667.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Several comments:

Price points are still displyed:

image

image

image

Max trait points are still enforced:

image

**Comment by Night-Pryanik** [comment]
> Price points are still displyed:

I left them on purpose. I thought someone might find this information useful even in freeform mode.

**Comment by ZhilkinSerg** [comment]
Sorry, I've branched invalid PR. Will check again now.

**Comment by ZhilkinSerg** [comment]
Looks good.

On the side note - only first 9 traits are displayed in Description tab:

image

**Pull request merged**
