### PR TITLE
Play minesweeper on your gamewatch now!

### PR DESCRIPTION
**Pull request by OzoneH3**

### CODE REVIEW

**Comment by Zireael07** [comment]
Oooh!

**Comment by IOSYN** [comment]
This looks great. Think you could assign different colours to the number vals?

**Comment by OzoneH3** [comment]
Now with color coding. Image updated.

**Comment by chaosvolt** [comment]
Ooh, interesting. What next, snake? o3o

**Comment by OzoneH3** [comment]
Theres already a snake game!? :P

**Comment by chaosvolt** [comment]
...doh, I didn't even realize that. I was actually suggesting it as a joke, because snake in an obstinately turn-based medium would be far easier. :V

**Comment by vache** [comment]
A border around the game area would be nice.

**Comment by Lain-** [comment]
This is really cool. Now I shall patiently wait the day when you can play a mini-Cataclysm game inside Cataclysm :)

**Comment by chaosvolt** [comment]
How deep will the rabbithole go? o3o

**Comment by kevingranade** [comment]
All it would take to enable "Cataception:recursively darker days ahead"
would be to do some hackery around saving and loading the game, basically
when you activate the game console, it'd save your game, set a flag on the
main game object, and exit to the main menu, as long as that flag is set it
suppress display of regular save games and only create and display 'nested'
saves.  When exiting with that flag set, it will instead load the previous
save.

Now when I say flag, I actually mean a stack of save game names.

Simple, right?

**Comment by chaosvolt** [comment]
Oh that would be gloriously insane.

And just think, if some real-world global cataclysm ever occurred, you can bet that someone, somewhere, would be being Cataclysm on a gameboy in Cataclysm, adding another layer to the onion.

**Comment by Lain-** [comment]
I was thinking about some trimmed-down Cataclysm, basically a very simple game with only a few zombies and items with non-infinity map, full-blown Cataclysm would still be nice of course.

**Comment by chaosvolt** [comment]
Hmm. Or maybe a more retro roguelike like ye olde original Rogue. Though I guess Robotfindskitten sorta counts.

**Comment by Rivet-the-Zombie** [comment]
If we're going to go so far as to include Roguelikes within the game system, I'm with @chaosvolt; my vote would have be for the original **Rogue**.

**Comment by vache** [comment]
I vote for overworld zero from the system shock 2 gamepig

**Comment by kevingranade** [comment]
The thing is, full cataclysm would be much easier than anything else, all
the others require shipping a whole additional game in the executable.
Rogue is likely small enough though.

**Comment by John-Candlebury** [comment]
What about the much neglected defense mode? 

That one would  probably be a bit easier, since i don't think it allows saves.

**Comment by chaosvolt** [comment]
Huehuehue. Tempting as all this lunacy is, it was kind of a joke suggestion. >.>

**Comment by JornVernee** [comment]
I think you forgot to add the .cpp to the codeblocks project? I keep getting build errors.

**Pull request merged**
