### PR TITLE
Fix for array size 0

### PR DESCRIPTION
**Pull request by AlecWhite**
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/21208. 

Did some testing and it works, but is not a definitive solution, but at least it allows for VC to compile again.

### CODE REVIEW

**Comment by Qrox** [comment]
Is @FluffyRedSheep working on a fix anyway? If not, some of us might have to help fix the issues in the original PR.

**Comment by AlecWhite** [comment]
He said in IRC that he is going to fix it, but I was impatience so I PR this.

**Comment by FluffyRedSheep** [comment]
I was indeed planning to tackle this, and a bunch of other problems outlined in the original pull request- I was quite recently overwhelmed by a few other matters, however. Apologies.

**Comment by kevingranade** [comment]
Superseeded by #21234

**Pull request closed without merging**
