### PR TITLE
Added 3L jar canning recipes.

### PR DESCRIPTION
**Pull request by ghost**
Added 3L glass jar canning recipes for all previous canning recipes as well as a recipe for canning red sauce for that fully preserved pizza.

### CODE REVIEW

**Comment by Pakislav2** [comment]
First time doing this. Weren't the changed lines supposed to be in red?

**Comment by kevingranade** [comment]
The canning recipes are intended to require a vacuum sealer AND a heat source, you've changed them to require a vacuum sealer OR a heat source.
Also the styling is off, see doc/JSON_STYLE.md for guidelines.

**Comment by Pakislav2** [comment]
The styling is copied from original canning recipes. I only changed values.

I removed the vacuum sealer requirement because; 

1.) IRL you only need a pot to can jars, my mom does that every year.

2.) The game is ambiguous in regards to what the sealer is. IRL there are ones that only package in plastic bags, ones a bit more universal, and specialized ones that provide their own heat source. I chose to think it's the latter to remove the conflict with the fact you only need a pot.

That being said maybe I should add a pot as a requirement?

Or do you insist to bring back the vacuum sealer?

**Comment by kevingranade** [comment]
You did not remove the sealer requirement, you made the sealer requirement and the heating requirement alternatives of each other, so it's definitely wrong.  (no this is not a sealer that cooks and seals the contents, if it were it would say that) It's also extremely bad form to make changes like this with no comment.

Copying data is no excuse not to correct the formatting, please do so.

There is no requirement in these recipes to have a sufficiently large pot to do waterbath canning canning, e.g. http://www.freshpreserving.com/waterbath-canning.html

If you want to make it that kind of recipe, you need to adjust the recipe to match how that kind of recipe works, not just make arbitrary adjustments.  i.e. it needs a pot that is at least 2x the volume of the jar to be sealed, and require water to be used as part of the recipe.  This complexity is part of the reason that this much simpler recipe was used.

**Comment by Pakislav2** [comment]
Should I add vacuum sealers as a requirement to all the basic canning recipes I didn't touch, which only use heatsource as a tool in current build while I'm at it? Only V8, kompot and soups seem to use them, which reminds me why I touched the tools at all.

**Comment by Marrim** [comment]
Is there anything in particular blocking this PR?

**Comment by kevingranade** [comment]
> Is there anything in particular blocking this PR?

The extraneous adjustments to how canning recipes work are a hard blocker, in fact I'm going to just chose this.
If someone wants to open a PR that *just* adds 3L canning recipes, go ahead.

**Pull request closed without merging**
