### PR TITLE
Make hair styles conform to using variants for colors

### LINKED ISSUE #69944: Standing mirror changes eye color randomly
### Describe the bug

The standing mirror is supposed to allow you to change your skin and eye color, and skin color works correctly. However, eye color does not--rather than showing a menu of possible eye colors, it shows only your _current_ eye color. Selecting that color gives you a random new eye color. 

### Attach save file

Trivially reproducible

### Steps to reproduce

1) Spawn in a standing mirror
2) Deploy the standing mirror
3) Activate the standing mirror
4) Attempt to change your eye color

### Expected behavior

Changing eye color works the same as changing skin color. 

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 924079e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by furran**
#### Summary
Bugfixes "Make hair styles conform to using variants for colors"

#### Purpose of change

The purpose of this change is to make all hairstyles conform to using variants for color

#### Describe the solution
- Made all hairstyles use variants for coloring
- Made the necessary migration as to avoid throwing errors at the player and making them bald in the process
- Edited the jsons that used the old hairstyles to use the new hairstyle ids and variants
- Edited the tile_config files for every tileset to use the new hairstyle ids and variants

#### Describe alternatives you've considered
Considered doing the opposite and undoing variant for hairstyles and eye_color, but that felt like going backwards.

#### Testing
Save file from 0.G: [Debug-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13574897/Debug-trimmed.tar.gz)

Made a few tests:

1. Created a new character and selected one of the hairstyles that now conform to the variants color style ('fro black) and checked in game through @ and the sprite (tileset used: GiantDays).

2. Created a character in the stable 0.G version with the black 'fro hairstyle and exported the save to this build. Loaded the save, observed if there were any error messages related to the changes ( there were some unrelated) and checked if my character still had the same hairstyle. Tested the same thing with the hairstyle short_no_fringe black variant.

#### Additional context
Some observations:
- Some tilesets have sprites for some hairstyles while others don't. Keep that in mind if testing that.
- mutation migrations don't seem to support "from_variant", so if the player character is using a re-identified hairstyle that had variants the migration will default the player hair color to black.

### CODE REVIEW

**Comment by furran** [comment]
> I suggest some way of indication of menu items which will prompt for a variant. Something like this:
> 
> ```diff
> diff --git a/src/mutation.cpp b/src/mutation.cpp
> index 19451fc063..cafb3fb023 100644
> --- a/src/mutation.cpp
> +++ b/src/mutation.cpp
> @@ -2363,13 +2363,9 @@ void Character::customize_appearance( customize_appearance_choice choice )
>                  current_trait = trait;
>                  char_has_trait = true;
>              }
> -
> -            const std::string &entry_name = mutation_name( trait );
> -
> -            amenu.addentry(
> -                i, true, MENU_AUTOASSIGN,
> -                char_has_trait ? entry_name + " *" : entry_name
> -            );
> +            amenu.addentry( i, true, MENU_AUTOASSIGN,
> +                            ( trait->variants.empty() ? mutation_name( trait ) : string_format( _( "Variant of %s… " ),
> +                                    trait->name() ) ) + ( char_has_trait ? " *" : "" ) );
>          }
>      };
> ```
I don't know, I feel like it feels cleaner and clearer without it. But I probably should follow your example and use trait->name if it has variants.
| A | B |
| -------| -------|
| image | image |

**Review by ehughsbaird — COMMENTED** [review]
I don't think tilesets are updated here, they're updated at https://github.com/I-am-Erk/CDDA-Tilesets

It would probably better if changing the hair to use variants and the fix to the customization were in separate PRs - they're not really related, and one of them is really big.

**Comment by furran** [comment]
> I don't think tilesets are updated here, they're updated at https://github.com/I-am-Erk/CDDA-Tilesets

I thought changes to the tileset sprites/images are made at https://github.com/I-am-Erk/CDDA-Tilesets but changes to things like tile_config.json are made here?  I might be wrong though

> It would probably better if changing the hair to use variants and the fix to the customization were in separate PRs - they're not really related, and one of them is really big.

You are right. I'm moving the customization fix to it's own PR

**Comment by ehughsbaird** [comment]
> > I don't think tilesets are updated here, they're updated at https://github.com/I-am-Erk/CDDA-Tilesets
> 
> I thought changes to the tileset sprites/images are made at https://github.com/I-am-Erk/CDDA-Tilesets but changes to things like tile_config.json are made here? I might be wrong though

The tile configs seem to be completely overwritten in https://github.com/CleverRaven/Cataclysm-DDA/pull/69886

**Comment by furran** [comment]
@ehughsbaird ouch. I think you are right. Gonna open an issue in that repo informing them of these changes to hair id.

**Pull request merged**
