### PR TITLE
Update Road Warrior profession

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Update Road Warrior profession.
Road Warrior is obvious refernce to Mad Max. Hovewer Mad Max character uses sawed-off shotgun not full sized. And he is not using back holster.

#### Summary

1) Replaced double barelled shotgun with sawed-off double baralled shotgun
2) Replaced back hoslter with XL holster that straps against leg.

SUMMARY: Features "Update Road Warrior proffession."

#### Purpose of change

screenshot 2018-12-22 002

1) Replaced double barelled shotgun with sawed-off double baralled shotgun
2) Replaced back hoslter with XL holster that straps against leg

https://madmax.fandom.com/wiki/Sawn-off_Shotgun
screenshot 2018-12-22 003

#### Describe alternatives you've considered

None

#### Additional context

None

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

**Comment by Firestorm01X2** [comment]
Now I am really don't know what is unformatted.

**Comment by AMurkin** [comment]
You shouldn't guess. Use http://dev.narc.ro/cataclysm/format.html.
One-line entries:
`"entries": [ { "item": "shotgun_d", "ammo-item": "reloaded_shot_00", "contents-item": [ "barrel_small" ] } ]`

**Comment by Firestorm01X2** [comment]
@Night-Pryanik 
You are right.
First thing I've tried:
```
{ "item": "shotgun_d", "ammo-item": "reloaded_shot_00", "container-item": "XL_holster", "contents-item": [ "barrel_small" ] },
"contents-item": [ "barrel_small" ]
```
But it puts barrel small in the hoslter. So I went for workoarund with item_group.

**Comment by Night-Pryanik** [comment]
The author stated that it is simply impossible to do. But it is possible despite being tricky. That's why I closed the issue.

**Pull request merged**
