### PR TITLE
Restore sum of errors based dispersion.

### PR DESCRIPTION
**Pull request by kevingranade**
Basically I was looking into addressing #20414 and discovered the existence of #17962, #18020 and #19019, which took dispersion management in a direction I had explicitly stated was unwelcome in #17712 and #17656, but were merged while I was away on paternity leave.

Effectively this is a revert of some parts of those PRs, re-instituting the previous sum-of-errors calculation method for dispersion.

Since an *actual* revert would be extremely messy at this point, this takes the code in a slightly different direction by accumulating sources of dispersion error into an explicit object, and then "rolling" for actual dispersion at the critical point in the code.  The dispersion source object can also be created and queried for maximum and average, which is used to give feedback to player or NPCs about their chances of hitting.  Additionally the code is generally a bit better factored out, further reducing the entanglement of shooting code and creature/player/npc code.

Major changes in functionality:
* Removes precise feedback about expected accuracy.
  * The previous approach had accumulated a large amount of code to very precisely calculate effective accuracy of a player/gun/projectile combination.  This removes that code because it's pointless.
    * Unit testing is pointless because the code to determine the chance to hit is indipendent of the actual calculation used to determine a hit, so the unit tests were only testing instrumentation code.
    * Feedback to the player or NPC was vague *by design*, the player isn't performing complex statistical analysis while in combat, and the estimate also excludes things like dodging and other random variation that the player is unaware of, it's meaningless to give that level of feedback.
* Removes a bunch of code from the "dump" module.
  * I've only ever seen mugling (now absent) use this data, and IMO the use of said data was frequently flawed, leading to over-simplification of systems in order to make them easier to understand and/or analyse, with no commesurate creation of mechanisms to insure that meaningful game balance was maintained.
  * As above, this data was removed because the code generating it was removed, and is therefor no longer part of the game.
* Removes the strange accuracy-based limit on weapon range.  If we're going to have a hard max range for projectiles other than reality bubble limitation, it should be based on momentum, not accuracy.  The system could lead to some odd scenarios like a very inaccurate grenade launcher being unable to fire a grenade very far, since it "wasn't accurate enough", even though the grenade might be effective to a very wide area.  The natural limit for effective range is accuracy, which we expose to the player (at least insofar as we tell them when a hit is wildly unlikely).

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Doesn't that reverting mean that we returning to citation three player can't reliable hit anything beyond 6 tiles?

**Comment by Zilenan91** [comment]
I agree with @Firestorm01X2 with how much better guns are now, you can actually hit things with them and as a player I feel like they're in a very good place in terms of how they work.

Before, you needed godlike aiming skills to hit things past 10 tiles but now you can do it with even decent skills. Currently the only dumb thing about it is that max range seems to be dependent on the ammo you're using but that's about the only problem it has from a gameplay end.

**Comment by kevingranade** [comment]
The backend was overhauled, and balance of a lot of guns was adjusted.  I
undid part of the backend overhaul, but didn't touch the dispersion
numbers.  As a result the player-visible change to accuracy should be
minimal to nonexistent.

More generally, if people want accuracy to remain unchanged, I need some
assertions about what the correct level of accuracy is so I can codify it
in some unit tests.

**Comment by DangerNoodle** [comment]
I would be extremely cautious of reducing weapon accuracy. It has already been taken too far once.

**Pull request merged**
