### PR TITLE
Remove the move

### LINKED ISSUE #18363: Compilation error
On OSX (`10.11.6`), 

with the code updated to 5a5f641,

with this command:
```sh
$ make clean
$ make app -j4 NATIVE=osx OSX_MIN=10.11 TILES=1 SOUND=1 LOCALIZE=0 RELEASE=1 CLANG=1 MACPORTS=1 USE_HOME_DIR=1
```

I get:

```
...
src/game_inventory.cpp:138:12: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move( inv_s.execute() );
           ^
src/game_inventory.cpp:138:12: note: remove std::move call here
    return std::move( inv_s.execute() );
           ^~~~~~~~~~~                ~
1 error generated.
make: *** [obj/tiles/game_inventory.o] Error 1
make: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by codemime**
Fixes #18363.

### CODE REVIEW

**Comment by codemime** [comment]
@Coolthulhu Could you merge this during the current session to fix OSX builds?

**Comment by Coolthulhu** [comment]
I can't verify it works, though. I can merge it now without testing, but I'd rather wait for someone to confirm it doesn't break things and actually fixes the issue.

**Comment by codemime** [comment]
I don't mind. It compiles fine on my computer (Linux g++) both with and without the `move`. Removing it mustn't break anything, though.

**Comment by mugling** [comment]
I agree it's unlikely to break anything. In any case though Jenkins is currently broken so it wouldn't gain much merging it untested

**Comment by illi-kun** [comment]
Okay, let's merge this and request the feedback from OSX users.

**Pull request merged**
