### PR TITLE
Added noise to laser weapons

### PR DESCRIPTION
**Pull request by Regularitee**
as per discussion https://github.com/CleverRaven/Cataclysm-DDA/issues/19827

To start with, I made the default noise levels about 1/3rd of the UPS energy drain (or if not using UPS energy, copy the noise level of a UPS energy weapon that does similar damage).

### CODE REVIEW

**Comment by Regularitee** [comment]
Anyone know what caused the error here? I'm not seeing it right now.

**Comment by BevapDin** [comment]
See http://ci.narc.ro/job/Cataclysm-Jently/67372//consoleText

The bot complains that the JSON is not "correct" - apparently there is now a very specific ordering of the JSON elements required. mugling knows that stuff. You can run `make lint` to fix this.

**Comment by BorkBorkGoesTheCode** [comment]
Ran these changes through http://dev.narc.ro/cataclysm/format.html. The loudness field is supposed to be placed after the burst field and before ups.

**Comment by BorkBorkGoesTheCode** [comment]
The error message points to the unwanted format in question; The canonical block lists the accepted json ordering.

**Comment by Regularitee** [comment]
There. Should have fixed the issue, unless I missed one.

**Pull request merged**
