### PR TITLE
Fix a typo 150000->15000 in POSTAPOC_PRICE_GUIDE.md

### PR DESCRIPTION
**Pull request by WingedZed**
#### Summary
None

#### Purpose of change
While working on #57749, I encountered an issue within the guide document on price_postapoc, as it suggests different max prices for items, with the first instance saying that no item should be worth more than 150.00$, and the second one having the limit of 1500.00$

#### Describe the solution
Fixes the typo and makes the maximum price 150.00$ in both sentences

#### Testing
None

### CODE REVIEW

**Comment by Inglonias** [comment]
not sure you fixed the typo in the correct direction. Did you ask someone if the value should be $150 or $1500? I took a quick look through the gun prices just now, and it looks like the max value should be $150.

**Comment by WingedZed** [comment]
> not sure you fixed the typo in the correct direction. Did you ask someone if the value should be $150 or $1500? I took a quick look through the gun prices just now, and it looks like the max value should be $150.

I've seen a lot of medicines having prices over 200$, for example, broad-spectrum antibiotics cost 600$. However, an invisibility cloak only costs 250$ and heavy power armor is 400$. 
All of those prices are from the files, and I understand that prices for meds aren't for each individual pill. However, the typo said that the reason for 1500$ or 150$ being the limit is because the person in cataclysm would never be willing/able to pay more, and prices for a couple of meds tend to lean towards the 1500$ being the limit.

Still, I'll try to join the development discord and ask around

**Comment by bombasticSlacks** [comment]
I am almost positive it is supposed to be 150$.

**Comment by Maleclypse** [comment]
I prefer the number being $1500 as it gives more fuzzy room for things to be wrong but still manageable.  At $150 you're still pretty limited in what things can reasonably be worth as a range. The single rock standard we have in the game is that Meat Jerky is worth a single Merch and therefore 2.50 dollars.     If  a pistol is worth $20 then eight pieces of jerky are the equivalent to a pistol. Maybe that makes sense.   But then what's a cow worth?  Is a cow worth $150?  If I can buy a cow and eat it's milk for three weeks then decide I want to move on from farming, butcher it and smoke the meat and now I have 2k meat jerky? Or if you kill and smoke a moose you can buy out the entire refugee center trading post.

**Pull request merged**
