### PR TITLE
Fix copy-from issues

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary
None

### CODE REVIEW

**Comment by actual-nh** [comment]
Oh, dear. Why didn't that work right?

**Comment by ZhilkinSerg** [comment]
More fields had to be deleted.

**Comment by actual-nh** [comment]
I'd wanted to do more, but github wouldn't let me do so with a suggestion. So category and bashing should not be present if something's copied from; will remember.

**Comment by ZhilkinSerg** [comment]
Any fields that have values that aren't different from original object should not be included.

**Pull request merged**
