### PR TITLE
parameterized field base camp version 2

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Main purpose:
- Make use of the ability to use palette parameters in mapgen/recipes to reduce the size of the JSON for field base camp version 2.

Side purposes:
- Remove bed/cooking construction of the first building as prerequisite for further construction.
- Add the option of making makeshift beds (made easy by the palette parameters).

#### Describe the solution

Massaging the construction recipes into palette parameter based ones.

#### Describe alternatives you've considered

Leave the new functionality implemented for this purpose unused.

#### Testing

The main testing was performed while testing the functionality (#58180), but a quick sanity check constructing the whole base camp with "random" materials for different parts was done before producing this PR.

- Verify that all construction materials actually can be used (but possibly not for every individual segment, although that probably was done before the PR went into the deep freezer last year).
- Verify that all 3 first building cooking facilities can be constructed.
- Verify that all 3 bed options can be constructed. Every option for every position has not been tested, though, but rather all permutations for the first room and "random" ones for the rest of them.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
An unrelated comment: After finding that the binding of the JSON uglifier (json_formatter.exe) was missing from Visual Studio as the result of an upgrade that resulted in reinstall a while ago, I manually applied the uglifier to all of the files modified and pushed the result (which is what's in this PR). I then located [https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md](url) and followed its instruction for restoring the "Lint All JSON" tool and then applied the uglifier. The result was that a bunch of starting with .github/vcpkg_ports/sdl2/vcpkg.json was modified. Is this intended? What happens when I inevitably push those changes after having made JSON changes in a future PR?

**Comment by jbytheway** [comment]
I think having those files linted is an unlucky coincidence of the current situation.  The powershell script lints any file that's different in your branch and either `master`, `origin/master`, or `upstream/master`.  Recently there was a PR to change some of the vcpkg stuff, so those files were different in one of those branches when they wouldn't normally be.  If you update `master` on your fork and rebase your branch then it shouldn't happen any more.

Still, I agree that behaviour isn't ideal.  If you know how to wrangle powershell then I'm sure a PR to improve the situation would be welcome :).

**Comment by PatrikLundell** [comment]
Thanks for the answers.

I'll definitely update my master before making any new branches (that is, or should be, standard practice). In fact, I believe my branch was produced immediately after updating master (and I remember I did update it), so any external changes would have happened during a fairly short time measured in hours.

However, even if these normally stable files are changed, why aren't they're subjected to the formatting rules applied to everything else? If they were, no requirements to change the files would occur, and the only side effect might be additional time for the processing of these files (which is rather substantial anyway, so it's fired off and then it's time to do something else in the mean time).

I am, unfortunately, not good at using any kind of shell scripting. Looking at the script I can get a gist of approximately what it's doing, but that's about it.

**Comment by PatrikLundell** [comment]
I very much doubt the field tests failed due to my addition of a word in a string (the tests succeeded before that commit)...

**Pull request merged**
