### PR TITLE
Fix for Bell Peppers never rotting

### LINKED ISSUE #54735: Bell peppers never rot
### Describe the bug

Well, the bell peppers don't rot like other vegetables.

### Steps to reproduce

1. Spawn a bell pepper
2. Examine it

### Expected behavior

I expect it to rot like all other vegetables.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Original Drug Names [OG_Drugs]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by skruncher**
#### Summary
Bugfixes "Makes it so Bell Peppers actually spoil"

#### Purpose of change

 Fixes #54735 

#### Describe the solution

 Adds a line of JSON making Bell Peppers spoil in two days

#### Describe alternatives you've considered

 Only one solution

#### Testing

 Spawned in the Bell Pepper and examined it after fix

### CODE REVIEW

**Comment by J-Fields** [comment]
Do you have a source for 2 days? Feels a bit short to me, and a cursory google gives answers like 3-7 days or 4-5 days.

**Comment by jackster483** [comment]
I was just going off of some of the similar items in the JSON. If 3 days makes more sense, I can cancel PR and change it.

**Comment by J-Fields** [comment]
I'm not sure what the right value is, but I think it should be justifiable with something concrete.

> I can cancel PR and change it

By the way, you can just push another commit to the same branch (or `git commit --amend` and `git push --force`) to update the PR, no need to cancel

**Comment by jackster483** [comment]
Thanks for letting me know about that feature, I updated the value to 3 days and 18 hours. After some research it makes the most sense.

**Review by NetSysFire — APPROVED** [review]

**Pull request merged**
