### PR TITLE
Autonomous Surgical Scalpels CBM Butchering Nerf

### PR DESCRIPTION
**Pull request by ISuckM8**
#### Summary

Balance "Nerfs the butchering capabilities of the scalpel CBM from 50 to 14"

#### Purpose of change

Even for a robot-controlled tool, a scalpel shouldn't be better than a butchering kit. That makes ZERO sense even for a CBM.

#### Describe the solution

Changed its butchering from 50 to 14.

#### Describe alternatives you've considered

Not adding this.

#### Testing

Spawned, debugged my way to install the CBM, checked its butchering capabilities, 14, just as God intended.

### CODE REVIEW

**Comment by actual-nh** [comment]
Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.

**Comment by ISuckM8** [comment]
> Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.

What's that?

**Comment by FayFlightee** [comment]
> > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> 
> What's that?

When you were checking its butchering quality, was it the tool with the BEST butchering quality you have available in your inventory?

**Comment by ISuckM8** [comment]
> > > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> > 
> > 
> > What's that?
> 
> When you were checking its butchering quality, was it the tool with the BEST butchering quality you have available in your inventory?

yeah, 50 is the highest value, with the butchering kit a bit behind it. check the HHG

**Comment by FayFlightee** [comment]
> > > > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> > > 
> > > 
> > > What's that?
> > 
> > 
> > When you were checking its butchering quality, was it the tool with the BEST butchering quality you have available in your inventory?
> 
> yeah, 50 is the highest value, with the butchering kit a bit behind it. check the HHG

I mean in your PR testing.

**Comment by ISuckM8** [comment]
> > > > > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> > > > 
> > > > 
> > > > What's that?
> > > 
> > > 
> > > When you were checking its butchering quality, was it the tool with the BEST butchering quality you have available in your inventory?
> > 
> > 
> > yeah, 50 is the highest value, with the butchering kit a bit behind it. check the HHG
> 
> I mean in your PR testing.

Nah, a hunting knife is better.

**Comment by actual-nh** [comment]
> > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> 
> What's that?

OK, just checked - CUT_FINE.

**Comment by actual-nh** [comment]
> > > > > > Do check on the requirements for dissection vs butchering and make sure it's still best for that, BTW.
> > > > > 
> > > > > 
> > > > > What's that?
> > > > 
> > > > 
> > > > When you were checking its butchering quality, was it the tool with the BEST butchering quality you have available in your inventory?
> > > 
> > > 
> > > yeah, 50 is the highest value, with the butchering kit a bit behind it. check the HHG
> > 
> > 
> > I mean in your PR testing.
> 
> Nah, a hunting knife is better.

I suspect that was because the bionic wasn't active.

**Pull request merged**
