### PR TITLE
Allow running EOCs as result of a recipe

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Been requested on discord a bunch of times.
Json power

#### Describe the solution
Allow running EOCS on completion of a recipe.

#### Testing
Used this json
```
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "name":"tester",
    "id":"test",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_MEAT",
    "skill_used": "cooking",
    "time": "1 m",
    "autolearn": true,
    "batch_time_factors": [ 67, 5 ],
    "qualities": [ { "id": "COOK", "level": 1 } ],
    "proficiencies": [ { "proficiency": "prof_food_prep" } ],
    "result_eocs": [ {"id": "TEST", "effect": { "u_message": "You feel Test" } } ]
  },
```

### CODE REVIEW

**Comment by mqrause** [comment]
Just wondering, what's the reason to make recipes that aren't practice and don't have a result? Is the intention to make items through the EOCs?

**Comment by Ramza13** [comment]
> Just wondering, what's the reason to make recipes that aren't practice and don't have a result? Is the intention to make items through the EOCs?

Thats the main one yea, for things like artifacts.

**Comment by mqrause** [comment]
Something to keep in mind is that as it is you can't learn recipes that produce no result. Might not be an issue for the intentions of this PR, but should probably get documented to avoid confusion if you wanna keep it like that.

**Comment by Ramza13** [comment]
> Something to keep in mind is that as it is you can't learn recipes that produce no result. Might not be an issue for the intentions of this PR, but should probably get documented to avoid confusion if you wanna keep it like that.

I'm not sure I follow.  Practice recipes can be learned from books and there is a dialog command to learn recipes.  What scenario are you referring to?

**Comment by mqrause** [comment]
I'm referring to this block: https://github.com/CleverRaven/Cataclysm-DDA/blob/47cf98ca587b8b1ad4a6767c8b26ee98084ffe72/src/crafting.cpp#L1266-L1286

You have a chance to learn the recipe when you finish the craft. Currently that only happens when you have an item resulting from the craft.

**Comment by Ramza13** [comment]
> I'm referring to this block:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/47cf98ca587b8b1ad4a6767c8b26ee98084ffe72/src/crafting.cpp#L1266-L1286
> 
> You have a chance to learn the recipe when you finish the craft. Currently that only happens when you have an item resulting from the craft.

Thanks, updated it to fix that.

**Pull request merged**
