### PR TITLE
add static defaults to spell_type

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Infrastructure "add static members to spell_type to use as defaults"```

#### Purpose of change
With #44059 implemented, I wanted to try to break up the requirements for #43171 up a bit. this is one of two prs to implement defaults for the spell_type class.

#### Describe the solution
add `static const` members to spell_type and then use those as parameters in optional() as the default values.

#### Testing
opened the game and scrolled through the spell list to see nothing crazy happened.

### CODE REVIEW

**Comment by KorGgenT** [comment]
@jbytheway i'm wondering if you can help me with this clang-tidy check failure. it's telling me to change the default from skill_default to skill_spellcraft. which makes sense for most of our use cases, but this one i definitely want to be skill_default

**Comment by ZhilkinSerg** [comment]
Maybe something like?

```
const skill_id spell_type::skill_spellcraft( "spellcraft" );
const skill_id spell_type::skill_default( skill_spellcraft );
```

**Comment by jbytheway** [comment]
ZhilkinSerg's suggestion should work, or this might:
```
const skill_id spell_type::skill_default = skill_id( "spellcraft" );
```
or you could add a `NOLINT` suppression.

But in general I should make that check not apply to static data members like this one.

**Comment by jbytheway** [comment]
I've fixed the check in #44104.  Once that's merged, you shouldn't need to use any of these workarounds.

**Pull request merged**
