### PR TITLE
Few grenadier changes [READY]

### PR DESCRIPTION
**Pull request by i2amroy**
1) Made grenadiers drop active bombs instead of just exploding on death.
2) Made explosions bash items.
3) Very slightly increased the fudge factor in the hack detonation range check.

And for anyone thinking about further nerfs, consider this. I just 3-on-1'd 3 elite grenadiers with nothing but a crowbar, 2 pairs of sunglesses, and 3 melee skill. 2 of the 3 I managed to get to blow themselves up. The third one I hurt through his own explosions and then finished off with the crowbar. The key is to never actually bother attacking the hacks while you are at low skill, just run in circles around the grenadiers while the hacks explode behind you. You'll be blind a fair chunk of the time, but it's totally doable. Whenever you aren't blind, check for where the grenadiers are and try to place yourself so that you end up near them. When you see one, hit it once or twice and then book it away (continuing in whatever direction you were traveling past them). If you are lucky then the hacks following you will detonate on their masters. If you aren't lucky you can repeat the strategy until they are dead. Don't ever try to actually hit the hacks since it causes you to slow down (and thus the other hacks catch you), just run away from them at an angle so they detonate behind you. It is also important to note that after I had killed 2 of the elites, when I started to run low on stamina, I backed off and took a short breather to regain my stamina before coming back to finish off the last one. I have no doubt that the strategy could be easily performed on as many as 4-6 elites at once, assuming you weren't super unlucky, you made sure to take a look at the terrain before hand, and you made sure to back out for a breather whenever your stamina ran low.

Higher melee skill players (~7 was where I could pull this off reliably, though it varied depending on the +hit of the weapon and how lucky I got) have the alternative strategy of taking down the hacks, but you have about 2 shots to get one successful hit in (which will kill pretty much any of the hacks). It's dangerous, but if you have the skill you can just charge at the elite grenadier like a madman, cutting down the hacks that get in your road before finishing off the grenadier himself.

In addition in a few similar balance checks with grenadiers in combination with other zombies, I fairly commonly got the grenadiers (or elite grenadiers) to blow up the other zombies for me through good positioning, at which point I was either able to close with the grenadier to finish them off through the strategy above, or they ran out of ammo and I was able to just kill them like a normal zombie.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The lack of explosion on death is probably the most important change here.

How about null the ammo on grenadier on death? Since they don't drop 'hacks, they should not reuse them once they get up. Especially important since their abilities don't depend on speed.
Same should be done to scientist, but that's a separate issue.

**Comment by i2amroy** [comment]
>How about null the ammo on grenadier on death? Since they don't drop 'hacks, they should not reuse them once they get up. Especially important since their abilities don't depend on speed.

I looked into that, but my options at this point consist of "null *everything's* ammo on death" or "don't null anyone's ammo". We don't save any creature data across the creature->corpse->creature boundary as far as I can tell, so I decided against it. If you'd prefer me to null out every revived creature's ammo that's totally doable, I just didn't want to make an assumption that could potentially screw over future developments (or add another hardcoded creature id-dependent check in).

**Comment by Coolthulhu** [comment]
Up until very recently, the only things that had ammo were bots that either exploded or fried or death.

A separate mondeath function would be fine.
Or even change the regular die function. When someone decides to write a monster that rezes with ammo, it should be easy to create a new mondeath that doesn't clear the ammo map.

**Comment by i2amroy** [comment]
The mondeath isn't the problem, it's the fact that when we do the monster->corpse conversion we are literally throwing away every piece of information about that individual monster. When said corpse is "revived", it's actually just a brand new monster of that type with the stats scaled.

That said I think I might be able to take advantage of the system we use for z-slaves to add a "no ammo" corpse variant. Give me just a moment.

**Comment by Coolthulhu** [comment]
You could also stuff the corpse with some goodies for player to recover (or zed to use if it rezes). Currently they don't drop much, while being rather tough. Making them more like shockers could help make them more likable.

**Comment by i2amroy** [comment]
Funnily enough a side effect of having explosions actually damage things means you need to grab what you want and get out (or grab the exploding things and throw them away) or the explosion pretty much wipes out their drops.

That said they do drop some of the best storage equipment in the game, so if you are fast you can grab that and get out.

Funnily enough in my tests they ended up acting a lot like spitters; zombies that weren't very useful to kill and were rather annoying, but that helped you out by wiping out all the other zombies nearby.

**Comment by i2amroy** [comment]
Running into a few crash bugs in my current testing, probably due to some stupid thing I forgot to do. Will look into them tomorrow instead of now at 3 am in the morning. Don't merge this yet.

**Comment by i2amroy** [comment]
Grenadiers now revive without ammo, slightly raised the hack drop chances and made dropped hacks no longer spawn damaged (though the death explosion will still often wipe them out if you don't deal with it somehow).

**Comment by i2amroy** [comment]
Kevin was having some problems fighting this, so I made this short video of me fighting an elite with nothing but the crowbar, sunglasses, and 3 melee skill.
https://www.youtube.com/watch?v=tGNaRx5w4EY

In this particular one I ended up getting just a tiny bit greedy at the end and didn't start running soon enough to escape the last hack. The combination of the earlier tear gas coughing, me having absolutely no armor in the slightest, and rolling basically the maximum amount of damage the last C-4 hack explosion could do all combined to do enough torso damage to just barely kill me, but be assured that both of the previous runs ended in me successfully killing the elite grenadier (the video quality of this cheapo quick-download screencap program was just so low on them they were totally garbled :-/ ).

It's a bit difficult to tell, but during the periods where I'm blind I'm moving towards the general last location where I saw the elite grenadier, excluding the times when I saw a dangerous hack (during which I moved in a circle around the grenadier that led me away from the hack) and the point where I ran away to catch my breath.

Also note that I played "return to sender" with a tear-gas hack, accidentally limiting my ability to kill the grenadier. If that had of been a normal explosive hack it probably would have done some serious damage, but as it was it just got in the road, meaning what I should have done at that point was backed off and waited for the tear gas to dissipate rather than just standing there letting him throw more hacks at me. I also slightly overstayed my welcome by not keeping an eye on my stamina; if I had of left for a breather earlier I most likely would have not gotten caught in the tear gas and as such would have survived the last explosion.

**Comment by kevingranade** [comment]
Basically I was being too big a wuss and running away from the bombs instead of charging through them.  Also if you're right on top of the grenadier you can use it to hide from one grenade hack and have a very good chance of getting the grenade to blast the grenadier.

**Pull request merged**
