### PR TITLE
changed the descriptions of crow and raven so they more accurately describe their relative sizes.

### PR DESCRIPTION
**Pull request by MammaJamma88**
#### Summary
Features  "Improved description of crow and raven"

#### Purpose of change
Previously the implication of the crow description is that it is bigger than a raven. 

#### Describe the solution
I changed the descriptions of both the raven and crow delineating the main differences in appearance and sound.

#### Describe alternatives you've considered
Letting people think that crows are larger than ravens.

#### Testing
None.

### CODE REVIEW

**Comment by NoddingCrow** [comment]
This PR has been recommended to me for no particular reason :p

Possible two typos in Raven description, you've written "this glossy black bird **had** a heavy **bead**" - I suspect you mean *has*, present tense, and *beak* respectively. 

Otherwise I like your descriptions, nice work!

**Comment by GuardianDll** [comment]
For your information, `summary` is used by the script that harvest the changelog; for it to work and now errorring, it should be either in format
```
type "description"
```
Or in format
```
None
```
So what you need to do is replace `Improved description of crow and raven` with `Features "Improved description of crow and raven"`

Also if you want to follow suggestion of Nodding Crow and edit the text again, you can do it using link https://github.dev/MammaJamma88/Cataclysm-DDA/tree/description_edits

**Comment by MammaJamma88** [comment]
> This PR has been recommended to me for no particular reason :p
> 
> Possible two typos in Raven description, you've written "this glossy black bird **had** a heavy **bead**" - I suspect you mean _has_, present tense, and _beak_ respectively.
> 
> Otherwise I like your descriptions, nice work!

Correct, now how do I fix it?

**Comment by GuardianDll** [comment]
Use link above, it will open the editor again, and you'll do the same as you did first time

**Comment by MammaJamma88** [comment]
> Use link above, it will open the editor again, and you'll do the same as you did first time

I believe I did it, thanks for being so helpful and patient

**Pull request merged**
