### PR TITLE
NPCs respect dangerous fields during pathfinding

### LINKED ISSUE #50206: [0.F stable] Companion pathfinding confused by sludge trails
### Describe the bug

Moving zig-zag to avoid a somewhat decayed sludge caused the companion to cease to follow the PC until the PC moved to a position where the sludge didn't confuse the companion.

### Steps To Reproduce

1. Have a companion follow the PC at two steps no matter what. don't investigate sounds (don't know what's relevant, but that's what was used).
2. Find a sludge trail of the type "*.***", where * is sludge and . is a sludge free tile.
2. Moved straight down towards the sludge trail from the north towards the center tile in the string above.
3. Side step the sludge into the free space via a diagonal movement and then back to the center downward line with another diagonal movement.
4. Watch in confusion as the companion moves to the tile above the center sludge trail tile (where the PC was two steps ago), then back north, back south, back north... until the PC move around the mess to give the companion a sludge free path to follow.

### Expected behavior

The companion should follow the PC in the footsteps if shortcuts are blocked off by sludge (like when the PC dodges normal bad terrain, such as boulders).

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

By the time I decided to write a bug report the trail had already dissipated, so I can't provide a save, unfortunately.

The sludge trail was generated by the new pupating zombie.

The default setting of having diagonal movement cost more than orthogonal ones hasn't been touched, so two diagonal movements should be more expensive than a straight (sludge free) line.

I've had other cases of sludge confusion where the companion walks off in a different direction when the PC navigates through the sludge mess until the PC moves around to give the companion a path it can understand.

### PR DESCRIPTION
**Pull request by satheon49**
#### Summary
Bugfixes "Fixes NPCs getting stuck next to dangerous fields"

#### Purpose of change

Fixes #50206

The pathfinding algorithm did not take dangerous active field effects into account when creating a path which resulted in a straight  path for the NPC to follow. However when actually trying to follow that path the NPC would step away from the field effect to avoid it which resulted in the generation of a new straight path making the NPC just wobble around in place.

#### Describe the solution

As part of the fix field effects are considered as "traps" as far as pathfinding is concerned meaning any creature with PATH_AVOID_DANGER_2 will path around them.

#### Describe alternatives you've considered

Not connecting dangerous fields to traps and introducing its own variable. However every situation where you would want to avoid one you would also want to avoid the other too. And in the end traps and dangerous fields though technically different are very much the same from a gameplay perspective.

#### Testing

1. Spawn a labyrinth of thick sludge
2. Spawn npc and have him/her try to follow the player through it
3. Spawn zombie runner (PATH_AVOID_DANGER_1) and feral human (PATH_AVOID_DANGER_2)
4. Zombie runner will step into sludge, feral human will not

### CODE REVIEW

**Comment by satheon49** [comment]
I don't know why the astyle check is failing. I did run `make astyle` and  running`make astyle-check` on my local branch does not return any regressions.

**Comment by Venera3** [comment]
Minor nitpick: The `PATH_AVOID_X` flags are handled by `monmove.cpp`, the proper pathfinding is used by monsters with the adequate `path_settings` array. Thank you for this, omitting fields from supposedly smarter mobs was a bit weird. 

Does this differentiate between dangerous/benign/dangerous-but-immune fields? I recall a check to that effect in the main monmove function,.but it might not be applicable to NPCs.

**Comment by satheon49** [comment]
i don't think so. The pathfinding caches the type of each map location in a certain radius. The PF_FIELD flag (which is used in this PR) only checks for field_entry::is_dangerous() during the caching process.

But as far as I can tell even though this flag was already present it was never used until now so it might be possible to change its logic without effecting anything else.

**Comment by actual-nh** [comment]
NPCs or monsters?

**Comment by satheon49** [comment]
I was wrong about the PATH_AVOID_X stuff. As Venera3 mentioned pathfinding is only influenced by path settings. The PATH_AVOID_X only comes into play if any creature tries to follow a path and encounters a location that was on the path it tried to follow but is now considered dangerous which causes the creature to move to another place and recalculate its path to where it wants to go. 

This currently results in creatures indecisively moving between two squares whenever its pathfinding is less restrictive than its PATH_AVOID_X because it will recalculate the same path through dangerous terrain then in the next step try to avoid it. The PR does not fix that in general either, it does however lets the pathfinder consider dangerous fields when creating a path. 

In a perfect world the pathfinding would use the same criteria for danger detection as monmove which would a) obsolete most of the avoid_xyz path settings and b) be probably too slow considering that the path finding algorithm has to compute this for a lot of squares.

**Comment by actual-nh** [comment]
You may find @eltank's comments in #50343 of interest.

**Comment by actual-nh** [comment]
> In a perfect world the pathfinding would use the same criteria for danger detection as monmove which would a) obsolete most of the avoid_xyz path settings and b) be probably too slow considering that the path finding algorithm has to compute this for a lot of squares.

Only if it did so non-lazily. In other words, first run A* with the current lower complexity of filtering. Then take the results as the heuristic for another iteration of A*, adding to the path cost for anything monmove would object to (although not absolutely ruling such out if at all possible). Iterate until stable. A* with a sufficiently good heuristic is quite fast, and unless a danger had not been spotted, this would be a perfect heuristic. (If a danger had been spotted, then the heuristic would be optimistic - which is required for it to work completely reliably for A*.)

**Comment by satheon49** [comment]
I find it interesting. That PR would fix the indecisiveness of NPCs too however this PR would still be relevant because otherwise "smart" creatures like NPCs would boldy step through fire, sludge or every other field effect.

**Comment by satheon49** [comment]
So I playtested #50343 for a bit and it did not fix NPC shuffling around next to dangerous fields which in hindsight makes sense since you said that NPCs do not use PATH_AVOID_X flags.

Anyway I thought a bit more about this and the original approach really was not that great (for example it would have caused black dragons to be afraid of stepping into its own aura field. Instead of the pathfinder avoiding fields for every creature that avoids traps the PR will just add fields NPC would consider dangerous to get_path_avoid() which is the same logic used by npcmove::move() for avoiding dangerous fields.

I restricted the radius to check for dangerous fields to 5 squares which should make the NPC smart enough to follow the player without having to much impact on performance (especially compared to the door check for NPCs in npc::get_path_avoid())

**Comment by actual-nh** [comment]
> @actual-nh So I playtested #50343 for a bit and it did not fix NPC shuffling around next to dangerous fields which in hindsight makes sense since you said that NPCs do not use PATH_AVOID_X flags.

Quite. A lot of stuff is different between the two types of creatures: characters (including NPCs and the avatar) and monsters; indeed, the files are divided between them!

> Anyway I thought a bit more about this and the original approach really was not that great (for example it would have caused black dragons to be afraid of stepping into its own aura field. Instead of the pathfinder avoiding fields for every creature that avoids traps the PR will just add fields NPC would consider dangerous to npc::get_path_avoid() which is the same logic used by npcmove::move() for avoiding dangerous fields.

Sounds reasonable.

> I restricted the radius to check for dangerous fields to 5 squares which should make the NPC smart enough to follow the player without having to much impact on performance (especially compared to the door check for NPCs in npc::get_path_avoid())

Too many NPCs in an area tend to cause some lag, so any performance boosts - e.g., caching information - would likely be helpful.

**Comment by satheon49** [comment]
I have not benchmarked NPCs, but IF pathfinding takes up a significant amount of processing time then it is because the door_check for NPCs in get_path_avoid checks 3721 tiles for doors if NPCs have the rule `avoid_doors`. Might be worth spawning 10 NPCs and see if forbidding doors for all of them degrades performance.

**Comment by Pseudogeist** [comment]
Nice. How many years has this been a thing? I was actually thinking about finding a quick fix for it myself and about pathfinding in general. I'd really like to see this go through, I might playtest it a bit if it doesn't. Looking at the checks it seems they failed due to Aftershock JSONs similar to #50593. Can you take another look @actual-nh ?

**Comment by actual-nh** [comment]
I can try to take a look, probably later this week. (New semester of teaching started today!)

**Pull request merged**
