### PR TITLE
Json spaces round 2

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs a rebase

**Comment by Coolthulhu** [comment]
It got kinda weird after the rebase. For some reason it lists a lot of unrelated changes.

**Comment by BorkBorkGoesTheCode** [comment]
I had a rebase problem too. What happened?

**Comment by Cyrano7** [comment]
Good question. I'm not really sure. I was doing it on my windows machine and github desktop was acting weird after.

**Pull request merged**
