### PR TITLE
Add bronze variants to many recipes. 

### PR DESCRIPTION
**Pull request by juur**
#### Summary
Content "Add bronze variants to ingredients for many recipes"

#### Purpose of change
I enjoy mods such as Innawood, but the base game lacks some of the basic bronze items/construction paths. This patch is the first (if it's accepted and worth doing!) to try and introduce parity for bronze age construction and crafting, alongside the (default) "steel age".

#### Describe the solution
For each key item, e.g. "nail", i've introduced a bronze variant (recipe for those will follow in future), as an alternative ingredient.

#### Describe alternatives you've considered
None

#### Testing
I've tested it in the base game. I need to do more testing with some of the bundled mods to see if it causes 'downstream' problems.

### CODE REVIEW

**Comment by Karol1223** [comment]
1. Summoning @Drew4484 to look over this. Sorry to throw you under the rails of another metalworking PR
2. Uh. Did you add crafting recipes *for* the new items? I couldn't find them.
3. You're missing some spots bronze tongs should be added in requirements at

**Comment by juur** [comment]
> 1. Summoning @Drew4484 to look over this. Sorry to throw you under the rails of another metalworking PR but I am not sure a bronze file is viable?
> 2. Uh. Did you add crafting recipes _for_ the new items? I couldn't find them.

Not yet, that might need a bit more research (and I wasn't sure how open to such a change CDDA was)

> 3. You're missing some spots bronze tongs should be added in requirements at

Will check - I left bronze nails out of vehicles (i'm unsure if that would structurally make sense, I believe bronze is stronger [or can be] than iron, but less than steel)

**Comment by Drew4484** [comment]
> 1. Summoning @Drew4484 to look over this. Sorry to throw you under the rails of another metalworking PR but I am not sure a bronze file is viable?
> 2. Uh. Did you add crafting recipes *for* the new items? I couldn't find them.
> 3. You're missing some spots bronze tongs should be added in requirements at
> 
> Overall I was hoping we'd wait with bronze tools until we can implement tools wearing out as they're used... But I can't stop you if it does make sense, and I'd like Drew to confirm whether it does.

Bronze files are viable, subject to greater wear than iron/steel, and not really suitable for working on harder metals like carbon steel but will probably work well enough. IIRC our in-game bronze isn't a specific alloy so there is some variance between a copper/tin alloy and one with aluminum, but without adding a dozen alloys I'd let this proceed.

**Comment by Drew4484** [comment]
> > 1. Summoning @Drew4484 to look over this. Sorry to throw you under the rails of another metalworking PR but I am not sure a bronze file is viable?
> > 2. Uh. Did you add crafting recipes _for_ the new items? I couldn't find them.
> 
> Not yet, that might need a bit more research (and I wasn't sure how open to such a change CDDA was)
> 
> > 3. You're missing some spots bronze tongs should be added in requirements at
> 
> Will check - I left bronze nails out of vehicles (i'm unsure if that would structurally make sense, I believe bronze is stronger [or can be] than iron, but less than steel)
> 
> 

A nice resource is MakeItFrom.com, you need to know a bit about what you're looking at but it does a good job of showing side-by-side comparisons. In general, brone/copper alloy is approximate to steel but heavier and more likely to deform than fracture (bend vs. break). Bronze nails are fine for things like a wooden wagon or cart.

**Pull request merged**
