### PR TITLE
Flooded Basements Part:1

### PR DESCRIPTION
**Pull request by RanikOrtega**
#### Summary
Content "New flooded basement variants"

#### Purpose of change
Some basements, mechanical or lower elevation areas should have areas that are flooded with water due to structural damage or neglect.

#### Describe the solution
Created a new flood water terrain for indoors use and created some variants of basements that are "filled" with water. The variants are weighted to occur about 1/5th of the time. With unflooded weight of 200 and flooded of 50. 

#### Describe alternatives you've considered
Not making the variants

#### Testing
Added variants to map generation and tested them. Pruned nested chunks to only those that played nicely with the water terrain rather than have to re-do all nested chunks. 

#### Additional context
flood1
flood2
flood3

Tileset does not entirely support current flooded areas. Doors also still act as normal variants for now.

### CODE REVIEW

**Comment by KnifeFightBears** [comment]
I have been in many basements before and significantly less than 20% of basements I have been in have been flooded or prone to floods

**Comment by RanikOrtega** [comment]
> That spawn rate seems really high
> 
> If 1 in 5 houses with basements were prone to flooding, nobody would build basements. This is a problem with the house when it happens. I understand a lot of houses in the north have sumps, but you get a sump because your house was poorly built or built in the wrong place, it's not the default way of life for basement owners

1/5 is too high yes but I was thinking of adjusting to 1/20.   Bear in mind that this is post rioting, zombies and collapse of 95% of the infrastructure so somebody may have left the faucet on 😄

**Comment by KnifeFightBears** [comment]
> > That spawn rate seems really high
> > If 1 in 5 houses with basements were prone to flooding, nobody would build basements.
> 
> 1/5 is too high yes but I was thinking of adjusting to 1/20. Bear in mind that this is post rioting, zombies, house damage and collapse of 95% of the infrastructure so somebody may have left the faucet on 😄

1/20 seems way more reasonable and is about what I'd expect IRL personally

**Comment by fairyarmadillo** [comment]
1/100 will still feel high due to how many houses the player explores. Basements don't just instantly flood the second they're left unattended.

**Comment by PatrikLundell** [comment]
With a rate of 1/100 you may come across one or two, which I think is reasonable and providing some variation. I agree the rate is probably too high from a realism perspective, though.

**Comment by fairyarmadillo** [comment]
> At some point. Realism will have to be suspended to give way to more interesting or varied terrain. 

I'm not sure that tracks. Flooding every fifth basement makes things less varied and interesting, not more. Players will see it and go, "oh, this again."

> 1/100 and the feature may as well not even exist let alone 1/1000.

I don't think that tracks either. The player is often going to explore dozens of houses in a relatively short timespan, and may easily see hundreds in a single run.

**Comment by RanikOrtega** [comment]
I think the both of you are completely misunderstanding something. Currently it's 1/5th of 5 houses. Not ALL houses. So in reality we are talking about 5 houses out of 70+ house options having a 1/5th chance to have flooded basements. It's exceedingly rare right now with 1/5th settings as it is. I had to crank those 5 houses up to 100x the spawn rate of other houses to even get the flooded basements to spawn naturally.

**Comment by fairyarmadillo** [comment]
> I think the both of you are completely misunderstanding something. Currently it's 1/5th of 5 houses. Not ALL houses. So in reality we are talking about 5 houses out of 70+ house options having a 1/5th chance to have flooded basements. It's exceedingly rare right now with 1/5th settings as it is. I had to crank those 5 houses up to 100x the spawn rate of other houses to even get the flooded basements to spawn naturally.

Well don't I feel silly. Sorry for the confusion. 😅

**Comment by RanikOrtega** [comment]
> > I think the both of you are completely misunderstanding something. Currently it's 1/5th of 5 houses. Not ALL houses. So in reality we are talking about 5 houses out of 70+ house options having a 1/5th chance to have flooded basements. It's exceedingly rare right now with 1/5th settings as it is. I had to crank those 5 houses up to 100x the spawn rate of other houses to even get the flooded basements to spawn naturally.
> 
> Well don't I feel silly. Sorry for the confusion. 😅

No problem at all. I just kept thinking "Man If I tune it down to 1/100 then it's NEVER going to actually spawn" lol. Once I had more houses I'll tune down the existing ones to 1/30 then 1/40 etc etc. But right now 1/20 is very low considering it's only 5 houses out of 70 haha

**Comment by Inglonias** [comment]
(5 / 70) * (1 / 5) = about 1.4% of houses. Just an FYI.

**Comment by RanikOrtega** [comment]
> (5 / 70) * (1 / 5) = about 1.4% of houses. Just an FYI.

Before it was merged I pushed it down to 1/20 so now it's 

(5 / 70) * (1 / 20) = 0.35% of houses. Once I had 10 to 20 more houses i'll push that down to 1/40

**Pull request merged**
