### PR TITLE
Game report: add precise version and name for systems.

### PR DESCRIPTION
**Pull request by neitsa**
#### Summary

```SUMMARY: Features "Add game report precise system versions."```

#### Purpose of change

* Follow-up of PR #30313 about game reports.

- [X] Add Windows precise version (e.g. `Windows 10 1809`).
- [X] Add Linux system name and version (e.g `Ubuntu 18.04`).
- [X] Add MacOs version.
- [X] Add BSD version.
- [X] Android version.

#### Describe the solution

* **Windows**: Use the registry and (if it fails) the native RtlGetVersion API.
    - All other version-related APIs "lie" about the underlying system if the application is not [Manifested](https://docs.microsoft.com/en-us/windows/desktop/sbscs/manifests). e.g. An application running on Windows 10 without a manifest may report Windows 8.1 or Windows 7...
    - This behavior is documented in [`verifyversioninfoa`](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-verifyversioninfoa#remarks) for example.

* **Linux**: rely on [LSB](https://en.wikipedia.org/wiki/Linux_Standard_Base) and shell-out to call `lsb_release -a`. This is the more "global" solution which encompasses most of the distributions without having to resort on a giant switch and try /error depending on the underlying system.

* **MacOs**: Use `sw_vers` through the shell as suggested by ifreund.

* **BSD**: Use `uname -a` which gives more information than on linux.

* **Android**: Use `__system_property_get` as suggested here on [SO](https://stackoverflow.com/a/19777977/507028). This doesn't require JNI!

#### Describe alternatives you've considered

* N/A.

#### Additional context

Sample output examples (tested):

* Windows: `Windows 10.0 1809`; `Windows 7.0`
* Linux: `Distributor ID: Ubuntu; Description: Ubuntu 18.10; Release: 18.10; Codename: cosmic;`
* MacOS: `Name: Mac OS X;  Version: 10.14.5;  Build: 18F132; ` (thanks to ifreund!)

Expected output examples (untested):

* Android: `Manufacturer: samsung; Model: SAMSUNG-SM-G930A; Release: 6.0.1; Incremental: G930AUCS4APK1`
    - Example for a Samsung Galaxy S7: 
        - `SAMSUNG-SM-G930A` is the internal name for the Samsung Galaxy S7.
        - `6.0.1` is the Android version.
        - `G930AUCS4APK1` is the samsung official build number for this Android.
* BSD: `FreeBSD 11.2-RELEASE-p4 amd64`

### CODE REVIEW

**Comment by ifreund** [comment]
I believe `sw_vers -productVersion` is what you'd want for macOS
See: https://ss64.com/osx/sw_vers.html

**Comment by neitsa** [comment]
Oh, that's really neat, thank you very much @ifreund!

**Comment by neitsa** [comment]
Thank you very much @ifreund for testing the output! Tahnks to you I just saw that there was a typo in the output... 

```
"    - OS Version: " << os_version << "\"n" << // misplaced "
```

I'm pushing a fix.

**Comment by ifreund** [comment]
Jenkins rebuild

**Pull request merged**
