### PR TITLE
Sewing machines

### PR DESCRIPTION
**Pull request by UmbralReaper**
#### Summary
Content "Adds a sewing machine and an overlocker"

#### Purpose of change
With the tailoring overhaul currently in progess in #54256, as well as appliances being introduced in #51286, I figured this was the best time to add sewing machines to cause the least amount of churn.

works towards #53647

#### Describe the solution

- [x] Implement two new items `sewing_machine` and `overlocker`. 
- [ ] Implement deconstruct recipes for `sewing_machine` and `overlocker`
- [ ] Allow `sewing_machine`  and `overlocker` to have the `SEW` quality when consuming power.
- [ ] Spawn `sewing_machine` and `overlocker` in houses and craft stores.
- [ ] Add sewing machines to recipes. @a-chancey Any chance you could help with this?

#### Describe alternatives you've considered

Adding a recipe for a manual sewing machine. Adding sewing needles.

#### Testing

Both items spawned and installed correctly.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I don't know if there's a demand for manual sewing machines for players who play in worlds without access to power (although they might have trouble making the parts for it)?

**Comment by a-chancey** [comment]
We had some discussions about this on discord and the general consensus is that both manual (pedal and flywheel) and powered sewing machines that run at different speeds are desired. Unfortunately, the only way the player will benefit is by adding alternative recipes to *everything* that could use either machine. 

I don't think I'm going to make alternative recipes just yet for everything, as that's a LOT to cover, and I have already blown past the scope of my original planned work. 

Based on the discussions, we need someone who's far better at CPP than I to work on #42556, as the plan is for routines to have time designated per step, so a powered sewing machine doesn't make the entire project faster, just the actual sewing portion. Essentially it would be like having a sorted list of entries similar to requirements, but each entry would define the time and resources needed for that step. From what I understand, it would also require reworking the tool/ingredient search algorithm and some UI work to allow the player to select which tools to use, likely defaulting to the fastest. 

For now, giving them the SEW 2 quality should allow them to be used in the place of a needle in every recipe we have. They shouldn't be a substitute for a sewing or tailors kit, because those items have cutting and other specialty tools.

**Comment by UmbralReaper** [comment]
I'm not sure how to give the sewing machine the sewing quality only when it has power. Does `charged_qualities` work with appliances?

**Comment by UmbralReaper** [comment]
I'm going to close this due to lack of interest. I don't think it's worth adding sewing machines to the game until they can be used to improve the crafting speed of recipes.

**Pull request closed without merging**
