### PR TITLE
Added easy deconstruction of furniture appliances

### LINKED ISSUE #58710: All appliances should be removable via simple deconstruction
### Is your feature request related to a problem? Please describe.

Bug or feature request?

So far I've encountered two appliances "in the wild" that are described as being possible to disconnect and move, but can't be removed in a reasonable manner, namely the hydraulic press and the water purifier. Using the "full" deconstruction on either of these results in a pile of parts, which is reasonable for that command, but not what you want when you want to actually just move it.

I just found out that there is a convoluted way to actually get a hydraulic press found in e.g. a garage as an item, and that is to first "plug it in" when examining it, and then disconnect it (again when examining it).

### Solution you would like.

All appliance furniture should be removable either via simple deconstruction, or, even better, a general "disconnect appliance furniture" command that's applicable to appliances that are placed as furniture by map generation.

### Describe alternatives you have considered.

_No response_

### Additional context

I assume the two cases I've found somehow didn't get the appropriate JSON descriptions for disconnection when they were supported as appliances. I consider it unlikely those two are the only ones that have some aspects of their appliancification missed, so appliance reviews might be useful (even better if there's a checklist for what's needed for all appliances, e.g. in the form of an example listing all the locations of example JSON parts, plus one or more optional sections for mapgen furniture support and other special cases, if any).

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Allow furniture that have appliance counterparts to be easily constructed into them, rather than a weird work around dance using connection/disconnection examination actions.
Fix #58710

#### Describe the solution

Added easy deconstruction of the furniture variants into the items and moved the deconstruction of the furniture into parts into new deconstructions for the items.
The furniture updated was:
- arcade machine
- hydraulic press
- air compressor (which already had a deconstruction recipe for the item), but no easy furniture deconstruction
- autoclave

It can be noted that the deconstruction conversion was done by taking the maximum number of components as the number specified when there was a range in the furniture deconstruction description. The assumption is that damage and skill would potentially reduce the number of items recovered from there, but I'm open to change that to the median or lowest value instead. Since I didn't see any ranges in the existing deconstruction recipes I looked at I assumed ranges were not supported, but I haven't actually tested to see if that's the case.

Note that water purifier isn't in the list as it has been taken care of by someone else in between the experimental the PR was based on and master contents as of this writing.

#### Describe alternatives you've considered

It would make sense to allow both deconstruction and easy deconstruction of furniture where the former takes the furniture apart into components and the latter disconnects the item. However, that would require a change from using a flag to have two distinct deconstruction sections, either with different names or with an indicator to determine whether the construction is easy or not.

Make the f_water_heater -> household_water_heater an appliance as well. However, that was considered out of the scope of this PR, but is something that probably should be done, as it doesn't make much sense that a heater placed back as furniture would be able to heat water.

#### Testing

Debug spawned the furniture under investigation (the ones that seemed they shouldn't work properly based in the JSON), verified that it couldn't be deconstructed into the item, modified the JSON for the furniture and added a deconstruction recipe for the item, restarted the game, debug spawned the furniture again, deconstructed it into the item and then deconstructed the item.
Done for each if the changed furnitures.

#### Additional context
A large number of appliances exist only as appliances or vehicle parts (e.g. the minifridge), but not as furniture, and so are not of interest in this investigation. The oddball is the kiln, as there exist a number of furniture kiln variants that deconstruct into their building materials, but which also exists as an item. This item can be placed as a vehicle part or appliance, and, I believe, used to be possible to be used to construct a furniture kiln as well. I haven't investigate this case further, however, as I think deconstruction into parts is the correct action in the normal case.

There is also a number of furniture variants that might be considered for appliance support in the future:
- f_air_conditioner (of obvious use during the summer heat, but tricky to implement (two parts, one inside and one outside?))
- f_air_filter. Would it have any use?
- f_dryer. Would require the introduction of wet clothing that needs to be dried.
- f_glass_fridge. Would be a variant.
- f_home_furnace. Since it presumably is actually burning stuff rather than using electricity, the reason to hook it up as an appliance would be to automatically turn it on/off to try to achieve a steady temperature using a thermostat.
- f_bellows. Probably useless as an appliance, but could be disconnected and moved, but bellows currently don't actually do anything.
- f_drophammer. Could be supported for more recipes than a few companion basecamp ones. Could presumably benefit from being powered.
- f_shredder. Probably useless
- f_server. Ditto, unless you somehow had use for a more powerful computer.
- f_satellite. Probably useless.

### CODE REVIEW

**Comment by dseguin** [comment]
FYI, it looks like some of these conflict with #58423

**Comment by PatrikLundell** [comment]
Thanks. Yes, the hydraulic press and the air compressor are modified by both. I don't know if I should assume that PR will be accepted and thus remove those from this PR or wait and see if it gets accepted first and change this PR then.

The code failure shouldn't be applicable to a JSON only PR, and the test failure on deconstruction seems to be on a test object (TEST knotted ball of string) rather than any of the deconstructions ported.

**Comment by descan** [comment]
Air conditioner should probably be two parts - a head, and the heat exchanger. How they should connect is another question - through wiring? Direct touching connection? (would be a bit odd for non-window unit ACs) And the outside part should radiate heat, allowing an impromptu heat-pump. (If you want to get complicated, you could have a fab/mechanics check for modifying an AC into a heat-pump with controls on the other side/both sides, or make certain ACs allow reversal of the heat exchanger as in some modern heat-pumps, allowing the AC head to function as both the AC and a heater depending on setting?)

Air filter could have a use, if you (for whatever reason) want to set up your base in a toxic environment (fungus, toxic waste). Not sure if there's much actual player use-case for that though, unless it's very easy to set up - that would allow someone to build an impromptu nest in a toxic area that they're trying to clear out, to allow resting if they get tired without having to run all the way out of the area. But that would be a *very* specific niche and may not be possible if the air filter is too large for reasonably having it on someone or near them.

The shredder is probably useless on its own, but it would be neat if you could turn it into a makeshift powered trap, although how much damage exposed and running shredding wheels would actually do is not something I have much experience with (... thankfully.)

Server might be useful if/when player research becomes a thing - then some really high-tier research/experimentation could require a functioning server or similarly powerful computer. But I have no idea if that's even a thing planned to ever happen, and I can't think of any other reason a player would or should need a server to do something.

Satellites would be neat if they were a super high-tier computer/fab/mech/whatever construction that allowed you to tap into the remaining orbiting GPS satellites and uncover the map (or parts of it, at least). It would probably require a lot more behind the scenes stuff to a) make it work, and b) make it worth doing by the time you can actually do it. First thing I thought of was like a super-charged survivor telescope/binoculars, but whether that would actually be worth doing by that point is a complete unknown to me - by that point, if your playstyle is dependent on exploring, you've probably explored enough to get all the resources and sites (labs, EXODII, etc) you need.

**Comment by PatrikLundell** [comment]
I wouldn't say reversible air con is "modern": it's at least 30 years old, but yes, one end should have a cold field and the other a heat field, but the tricky part is, as you say, how to connect them.

Air filter: Deployable in mi-go structures? Breaking into the prisons is a lot of work and takes time, so gas masks are a bit of a problem. Still very niche and someone would have to implement that field (which may or may not be trivial or hard).

Servers: Well, apart from research decent computers can also be used for the very useful activity of playing C:DDA with limited slowdown...

Satellites: There may be a working GPS satellite network, if the cataclysm didn't destroy them. However, if those still work a regular GPS receiver would pick up the signal and give you your position, which isn't particularly useful on its own. The thing you'd need for navigation would be to get hold of the maps used in conjunction with the GPS (which, stupidly, is called "GPS" nowadays), which you'd probably get off of any GPS devices you find (I don't use them, but I would assume the "local" map downloaded would cover all of New England at least). However, such maps would obviously be made before the cataclysm, and thus wouldn't display anything that's happened since (bandit forts, craters, mi-go/ant/fungus/...), and so would provide you info similar to what you get from the various local maps you find scattered about.
To get actual maps you'd have to be able to control either military spy satellites (very hard), or civilian satellites of various kinds (you'd probably still need to get the encryption from some facility, such as NOAA or commercial mapping satellites. As you say, it's questionable whether that would provide you with much of a benefit. I guess images coupled with image processing might allow you to detect vehicles which would allow you to locate factions, but that would likely only be useful if you're trying to locate a some hidden facilities by tracking the traffic to and from it.

**Comment by descan** [comment]
Ah, yeah, my information is a little out of date regarding the development of commercial ACs, especially in New England - my bad! In terms of connecting them, I'd take a page from refrigerators and from extension cords - have the two appliances placed like, say, a battery and a solar panel, and then activate a rubber hose and attach them. Realistically, a simple rubber hose (the kind you get from disassembling a garden hose as well - same item) would not be good enough to transfer the evaporant between the head and the radiator. But if it's good enough to function in a refrigerator, then it'd be good enough to serve here. (I'm assuming that's the purpose of the rubber hose you get from a refrigerator, to connect the evaporator and condenser coils. I haven't taken one apart in real life to know whether there's another use for the hose I'm forgetting.)

Mi-go prisons are definitely an example of such a place where a hold-out camp with the air filtered would be useful, although gas-mask cartridges aren't super hard nor super large. I'm not sure how many cartridges you would need to finish off a prison, and if the weight/volume of all of those would be more or less than an air filter and charged battery (and whether the charge on that battery would be enough to make the filter last long enough, too).

Also true, although CDDA is probably (... probably...) not being actively developed any more by that point.

Smartphone and desktop GPS maps, when you download (IF you can) a local map, are usually only the size of the city you're in. They'd cover maybe 40-60 km^2, not much more than that. Covering the entirety of New England is probably not something you could do easily. To get a decent map of the "entire" (hard word to use with a procedurally generating infinite world) map would probably require hacking in to whatever functioning military spy satellites still exist, yeah, and the "realistic" information you could glean from even a spy satellite would be... minimal, I assume. Roads, definitely. Trails, maybe. The *existence* of a building, yes, but what that building *is*? Doubtful. 

On that note: I don't think CDDA currently supports map knowledge that granular - you either know exactly what a building is (although not the state of it) or you have no idea the building is there at all. You can't know that there's *something* there without knowing exactly that it's a gun store, sex shop, moonshine still, triffid tower, etc. 

To get usable satellites (for map knowledge, at least) would take a LOT of work to make them realistic. To get them working realistically, AND worth doing enough for players to bother with (thereby deciding whether it's a priority to do or not, compared to other things) is... Probably even harder. There might be other benefits of satellite dishes for players, but considering they're mostly for communication and/or large-scale information gathering, neither of which players really need beyond the map data, I think it's unlikely.

**Comment by PatrikLundell** [comment]
I've never been to New England, but reversible air cons were common in Oz when I was there. A rubber hose sounds like a clever way of connecting the parts, although I think there's a need for some code to do what jumper cables do currently (but might be used to actually get water to water using appliances).

The issue with gas masks and mi-go prisons isn't really cartridges, but that gas masks restricts breathing, and breaking through walls is tiring. Wearing a gas mask while mining results in LOTS of long breaks.

Servers: C:DDA would probably still be developed by basement dwellers (it's certainly safer than bashing zombies... at least until they run out of coke), but distribution is a bit of an issue. Sneakernet would work, but that requires that you know like minded people nearby who are still alive (and it also means leaving the safety of the basement).

Spy satellites are presumably capable of resolve number plates (but not the numbers on them), but given that they're in low earth orbits you can't have continuous surveillance, but have to image areas when satellites pass over them. Also, I would assume these high resolution images come at the expense of coverage, so you'd have to know exactly where you want to look. Still, the images wouldn't tell you the function of anything you see, as you say.

**Comment by Qrox** [comment]
We could simply allow merging two ends of an air conditioner into a three-tile "appliance", with a "tubing" middle tile that occupies the same tile as a wall, so we could re-use the vehicle-cooler-muffler code. Given that appliance is implemented on top of the vehicle code I think it's relatively easy to implement.

**Comment by PatrikLundell** [comment]
If a three tile appliance solution works, I'd probably want to restrict the placement of the "tubing" part to open terrain, doors, windows, and "normal" walls. The last bit would include all man made walls except mi-go (alien) resin, but exclude things like natural rock walls.

**Comment by Tread4** [comment]
FYI, my PR #58423, which was previously mentioned here and adjusted the Hydraulic Press and Air Compressor got merged recently. I hope that status update clears up the "clash" situation with this PR.

**Comment by PatrikLundell** [comment]
Thanks for the notification. I'll update this PR to take that into consideration.
It looks like there are conflicts to resolve, so I don't have to change this into draft in the mean time.

**Pull request merged**
