### PR TITLE
make laundry baskets craftable & fixes #27478

### LINKED ISSUE #27478: Disassembling basket of plastic yields too much material.
image

### PR DESCRIPTION
**Pull request by mount2010**
#### Summary

SUMMARY: Content "Make laundry baskets craftable and fix disassembly counts"
#### Purpose of change

Laundry baskets were being treated as a solid block of plastic to harvest chunks of plastic out of, yielding 100 chunks of plastic.
#### Describe the solution

This makes an uncraft for laundry baskets and makes them craftable. This sets the disassembly to 20 plastic chunks.
#### Describe alternatives you've considered

N/A

### CODE REVIEW

**Comment by AMurkin** [comment]
Move it in the OP:
Fixes #27478

**Comment by Zireael07** [comment]
Uncraft yes, but I don't think those should be craftable (most plastic items aren't except very simple shapes)

**Comment by mount2010** [comment]
I'm not sure, I initially made it that way because I thought it was how to specify a uncraft recipe. Thpse on the Discord encouraged me to keep it.

**Comment by mount2010** [comment]
I've fixed the summary line, how would I make the CIs rebuild?

**Comment by KITbutler** [comment]
> I've fixed the summary line, how would I make the CIs rebuild?

People tend to post "Jenkins rebuild" without quotes. Not sure which, if any, privileges you require for it to work though.

**Comment by AMurkin** [comment]
Summary is fine but Jenkins failed with `Formatted data/json/recipes/recipe_deconstruction.json`
You should format your JSON changes with http://dev.narc.ro/cataclysm/format.html

**Comment by mount2010** [comment]
oops, got a duplicate in

**Comment by kevingranade** [comment]
Merged into 0.D and master

**Pull request closed without merging**
