### PR TITLE
Add Chinese main menu ASCII art

### PR DESCRIPTION
**Pull request by ghost**
````````````
                  **                  **                  **                    
                  **                  **             *************              
                  **             **************     **   * **                   
             *************       *    *      **        ***  * *                 
             **   **             * *  **  *  *       *** *  * ***               
                  * *            * ** ** **  *      *  ******** **              
                 ** **             ** **                *    **                 
                 **  ***             ** **               ** **                  
               ***    ****          ***  ***              ****            .-.   
           ******      *****      ****    *****       *****  ******   _  |   `  
            ***         ****   *****       *****   *****       *****   ',|    \ 
     ***                 *                  ***           _..    **  -.,,'-., / 
    *   *  /-\                                       ,,,,/   |           |    \ 
     *** =========='      ----               ----        `  _/`'.,       \ _--  
     ||'''/ |                                        `````'-    /```''-    | |  
     ,\.    |                                                '.-_`,,,,,,,,,\.\--
    /  |    ^          ___,,,,,,,,,,...-------''''''``````````                  
*------'''''*``````````                                                         
````````````

### CODE REVIEW

**Comment by DLaboratory** [comment]
@cainiaowu

**Comment by illi-kun** [comment]
Nice!

**Comment by cainiaowu** [comment]
灵魂画师

**Comment by DLaboratory** [comment]
可惜标题主界面必须是18行，80个字符的宽度，写下“大灾变”之后，就容不下“劫后余生”的副标题了，只得画一些奇怪的ASCII Art去填充空白。

**Comment by Night-Pryanik** [comment]
Though we all can use Google Translate, would you mind to write in English?

**Comment by DLaboratory** [comment]
> Though we all can use Google Translate, would you mind to write in English?

I just replied the comment by cainiaowu.

> 灵魂画师
> --cainiaowu

He joked at my painting. :laughing: 

>可惜标题主界面必须是18行，80个字符的宽度，写下“大灾变”之后，就容不下“劫后余生”的副标题了，只得画一些奇怪的ASCII Art去填充空白。
> --DLaboratory

I tried to fill the 18x80 sized canvas with title _Cataclysm_ (大灾变) and subtitle _Dark Days Ahead_ (劫后余生), but Chinese characters are so complicated that I couldn't put their ASCII form together in only 18x80, so I put main title _Cataclysm_ (大灾变) on the top, and painted something beneath.

**Comment by kevingranade** [comment]
Awesome, thanks!

**Comment by Rivet-the-Zombie** [comment]
It's very cute!

**Pull request merged**
