### PR TITLE
Appveyor disable tests

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary
Build "Disable tests on Appveyor (+ other changes)"

#### Purpose of change

MAGA (Make AppVeyor Green Again)

#### Describe the solution

Disable building and running tests on Appveyor. Also make some other changes to disallow hitting 60 minutes timeout.

#### Describe alternatives you've considered

https://help.appveyor.com/discussions/problems/28977-increasing-timeout-on-a-project

#### Testing

Appveyor build succeeds.

#### Additional context

Current PR should not be merged!

Currently it is only useful for manual run to update Appveyor cache with fresh vcpkg dependencies.

### CODE REVIEW

**Comment by actual-nh** [comment]
I see quite a few "Could not locate cached archive:" in appveyor results so far in #47709, BTW.

**Comment by ZhilkinSerg** [comment]
https://help.appveyor.com/discussions/problems/28977-increasing-timeout-on-a-project

**Comment by ZhilkinSerg** [comment]
> 
> 
> I see quite a few "Could not locate cached archive:" in appveyor results so far in #47709, BTW.

Yes, but it still seems builds after current PR was built and cache was stored seems to take less time. Comparing https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/37917330 and https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/37917582 actual build started 6 minutes earlier after cache was updated.

**Comment by actual-nh** [comment]
@kevingranade:
> Current PR should not be merged!
Currently it is only useful for manual run to update Appveyor cache with fresh vcpkg dependencies.

**Comment by ZhilkinSerg** [comment]
Merging this is not a big deal - the only downside is removal of tests project from MSVC solution, but I returned it back in https://github.com/CleverRaven/Cataclysm-DDA/commit/e9dcefbec710c2d2864f3b850866fc2ac95e51ea.

Without running tests (while still building them), we can now fit into 60 minute timeout even for builds with old `.appveyor.yaml` (by with new cache). Builds for new PRs should run even better - see https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/37923720

**Pull request merged**
