### PR TITLE
Make rubber boots and gloves and motorcycle gear compliant with PPE standards

### PR DESCRIPTION
**Pull request by zachary-kaelan**
#### Summary

Balance "Make rubber boots and motorcycle gear sturdy"

#### Purpose of change

As PPE (personal protective equipment), rubber boots and gloves and motorcycle gear have certain safety standard ratings, yet they were not `STURDY`.

The rubber gloves in the game are 13 USD pre-apoc and are not `STURDY`. Take a look at [this pair](https://www.amazon.com/LANON-Chemical-Resistant-Non-slip-Reusable/dp/B07ZRM6SZN) of 13 USD rubber gloves on Amazon. 

> They passed the highest level 4 (at least 8000 cycles) of abrasion resistance test, level 1 (1.2 times) of blade resistance test, level 2 (25 force) of tear resistance test and level 1 (20 force) of puncture resistance test.

Why do they do this? To meet official safety standards, because rubber gloves that can easily get holes and tears with one slip of the arm are considered *unusable* for handling caustic materials.

> CERTIFICATIONS - LANON industrial gloves for hand protection are certificated by CE 0075 CAT III, with Standards EN 388:2016, EN 420, EN ISO374-5:2016, EN ISO374-1:2016/Type A, and meet CA Prop.65 regulations for phthalates. It also passed the FDA regulation test.

Rubber boots are held to similar standards.

&nbsp;

Believe it or not, motorcycle gear is [also considered PPE](https://www.motorcyclegear.com/info_pages/faq_armor_ratings_explained.html) and has its own set of safety standards. They test if it can be ground into abrasive textures at high speeds without falling apart.

#### Describe the solution

I made all of them `STURDY`, and also made steel-toed boots and sneakers `STURDY` because they're used by workers. I also upped the environmental protection of the boots and gloves to 15, because that plays a big part in resisting acid, and in fact a 15 or higher is required on the feet for you to not get burned in pools of acid. I also changed the materials and crafting recipe for the motorcycle boots because being made of cotton makes no sense and definitely isn't compliant.

I also made hiking shoes `STURDY` because they're made for walking hundreds of miles on rugged terrain.

#### Describe alternatives you've considered

Removing those OSHA abominations from the game entirely.

#### Testing

None required.

#### Additional context

None.

### CODE REVIEW

**Comment by Kantonine** [comment]
Regarding motorcycle boots, do you have any other changes for them? I don't feel that its communicated well what type of boots these are, which are really encumbering, despite being just cotton and kevlar (at the same overall thickness of the combat boots no less) which i feel is  hold-over from the combat boots being just as encumbering. Should the addition of plastic padding/thermoplastic resin/plastic etc etc. be made, so that the encumbrance is accurate?

**Comment by zachary-kaelan** [comment]
> I don't feel that its communicated well what type of boots these are

I didn't even loot at the stats and materials. You're right, those make zero sense. I'll make them not horrible.

> also, shouldn't the steeltoe boots and sneakers also have `STURDY`? they're PPE all the same

I forgot to mention that I also made those `STURDY`.

**Comment by fairyarmadillo** [comment]
Just a heads up, there is a bug with how acid protection is calculated that may be throwing you off as you work on these items. IIRC the game modifies the material base value using enviro protection, and applies that per layer without regard to thickness. The result is that two 1mm layers of rubber are twice as protective as one 2mm layer.

**Comment by Kantonine** [comment]
Looking over the change to the motorcycle boots, they look great, but if these are the types used by motocross riders, then wouldn't it be better for it to be something like:
s-l1200

Or was there something else that you based them off of? If so, i might try my hand at making something like these as a seperate item in any case

**Comment by zachary-kaelan** [comment]
I based them on a rough combination of police motorcycle boots, combat boots, and what was already there. Those definitely aren't it, you are 100% free to make those as a separate item.

**Review by kevingranade — CHANGES_REQUESTED** [review]
You're being a bit too free with labeling things sturdy here.  Your rationale seems to boil down to "is it intended to be protective at all", but the use case in the game is predominantly getting attacked by various kinds of monsters,  which I'm quite sure none of these things are rated for.

The ones I'm really concerned with are rubber gloves, steel toed sneakers, and motorcycle armor.
For the gloves,  you picked *an* exemplar,  but that's a pretty heavy duty glove from what I can see, the majority of gloves you're going to come across aren't that tough.  If there's only one item representing a category,  it should be the most common member of that category,  which is almost never count to be the toughest version.
Steel toed sneakers are literally just regular sneakers with an insert, there's nothing particularly tough about them.
Motorcycle armor is a bit of both issues,  it should represent common Motorcycle armor,  not the toughest stuff around,  and also it's not designed to resist being pulled apart,  it's designed to skate across asphalt.

Feel free to add a rarer and tougher variant of some of these,  but the common ones should remain relatively fragile.

**Comment by zachary-kaelan** [comment]
Those are all good points.

> Feel free to add a rarer and tougher variant of some of these, but the common ones should remain relatively fragile.

It would indeed make more sense for the boots and gloves found with hazmat suits or an NBC suit to be differentiated from the boots and gloves found with janitor and plumbing equipment. I'll look into it and later make a fresh PR.

**Pull request closed without merging**
