### PR TITLE
Reword suicide prompt

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Interface "Reword suicide prompt"

#### Purpose of change

Reword suicide prompt to something softer

#### Testing

image

image

### CODE REVIEW

**Comment by Fris0uman** [comment]
Next screen is the death screen, so it gets clarified really quick.

**Comment by bombasticSlacks** [comment]
I've always hated the commit suicide prompt 👍

**Comment by John-Candlebury** [comment]
> Next screen is the death screen, so it gets clarified really quick.

Oh yeah thats right. Forget about it haha

**Comment by Qrox** [comment]
You might also want to change the keybinding text in `data/raw/keybindings.json` and the memorial log text in `memorial_logger.cpp`.

**Pull request merged**
