### PR TITLE
Normalize factory 22 ammo

### PR DESCRIPTION
**Pull request by mugling**
Balance point being plentiful and easy to store, with `stack_size 100` and `weight 3`.

When did handloaded `22` ammo sneak in? Is this **realistically** possible? Are players actually handloading ratshot?

If there's no objection I'd like to move the handloaded variants to `obsolete.json` and remove the recipes as `22` being plentiful but not reloadable was one of the differentiating features for that ammo type?

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
The handloaded .22 ammo uses unspent cartridges - though it is possible to reuse spent ones in the real world.
The .22 ratshot is pretty useless though.

**Comment by mugling** [comment]
Ah I see. So given that you need unspent `22` ammo and `22_fmj` is the best type everything other than `reloaded_22_fmj` is redundant?

**Comment by Rivet-the-Zombie** [comment]
The handloaded .22LR and .22LR FMJ variants are both decent. The CB and ratshot ones are so weak that most folks will probably never actually waste unspent brass on them.

**Comment by mugling** [comment]
Ok, I've normalized the .22LR and .22FMJ handloaded variants

**Pull request merged**
