### PR TITLE
Office Skyscrapers

### PR DESCRIPTION
**Pull request by Stadler76**
#### Summary
Content "Office Skyscrapers"

#### Purpose of change
Adds office skyscrapers to the game.

#### Describe the solution
This is the first crude version of the office skyscraper. It's currently just a copy of the large office tower and adds three more floors to it. The whole thing is stc as of now. e. g. I want to add a big boss' office to the roof and raise the tower by one extra level later. It's just that I had to start somewhere, right? And it's the first part of something big, which I'll reveal once the skyscaper has matured enough to go out of draft stage.

#### Describe alternatives you've considered
None

#### Testing
Map loads without errors and I could climb up to to the roof and zeds spawn on every level as intended.

#### Additional context
Overmap screenshot of a city with a large office tower and an office skyscrape First version of apartment home on z-level 1
Upper half of the skyscraper apartements done Skyscraper apartments on z-level 1 done
First version of the basic layout of the first level (Shops to be added later) Reduced to 5 shops and made the bathrooms smaller
Laundromat finished Electronics store and salon done
Small canteen Grocer done, redid the items at the electronic store and more zed spawns
Pet store done

### CODE REVIEW

**Comment by Stadler76** [comment]
Just added a quick and dirty version of the aparment homes on z-level 1.
It's currently a modified version from an apartment tower map from `data/json/mapgen/apartment_con_new.json`. Instead of compressing the six apartments to fit I've decided, that it's easier to make them bigger. I've focused on making the elevators and the staircases match the rest of the skyscraper for now. Hence the missing walls and the empty spaces in the apartments. See the screenshot of the current version.

I'm considering to replace the offices on z-level 2 with apartments, too. Makes more sense to me, to have more, than 4 apartments on the skyscraper.

Next will be either a random shop or a mini shopping-mall on z-level 0 and the big boss' office on the roof.

Talking about the roof:
My idea is that the upper half is occupied by a big office with all things a big boss needs, like a small kitchen, a smaller office for his (or her) secretary. *Maybe* a small conference table where the boss can shout at his ~minions~ employees.
The lower half will have a helipad on it instead of the help sign and in rare cases a broken heli on it. Most of the time the bosses made it to the heli in time to escape the tower (and most likely got killed by zeds elsewhere).

**Comment by Stadler76** [comment]
Started working on the mini-mall on z-level 0. Currently just empty rooms to be filled with shops. Windows on the outside are to be repositioned. So don't be bothered about the wacky window layout. Currently there are 6 empty rooms to be filled with shops.

Planned shops are:
- Laundromat
- Salon
- Grocery
- Electronics store

Any suggestions about the other two shops?

PS: I might change the layout so we have one shop less. The three upper rooms might be a bit small.

**Comment by Drew4484** [comment]
> 

Smoke shops, pet store, bank branch, tattoo parlor, skate/bike shop

**Comment by Stadler76** [comment]
3 of 5 shops are finished. What's left is the pet supply store (pet store minus the pets) on the top left and the grocer in the middle left room.

**Comment by I-am-Erk** [comment]
From the look of things someone could probably get this polished and added with minimal effort.

**Pull request closed without merging**
