### PR TITLE
improved dialog companion mission UI

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

- Improve the UI of the (primarily) Tacoma companion missions.
- Fix the caravan missions to return all members.
- 

#### Describe the solution

Some UI string changes, keep track of whether companions are ready to be returned and indicate that in the UI.
Move the random time factor for companions joining a caravan to the caravan level rather than the individual level, resulting in the check for the companions having the same timers actually working.

#### Describe alternatives you've considered

Leave if for someone else, but I said I'd do it...

#### Testing

Using a bunch of conveniently retained saves to verify that the changes actually worked as intended, with the greying out of an entry if no companions are available for return and priority marking (yellow) if any of them is available. Checked that the caravan change had two companions sent off on a caravan together return together when one of them was returned.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
"[](https://github.com/CleverRaven/Cataclysm-DDA/runs/5358034319?check_suite_focus=true)General build matrix / GCC 11, Ubuntu cross-compile to MinGW-Win64, Tiles, Sound (pull_request) Failing after 13m — GCC 11, Ubuntu cross-compile to MinGW-Win64, Tiles, Sound" test failure has nothing to do with the PR changes:

(~[slow] ~[.],starting_items)=> cata_test.exe is a Catch v2.13.7 host application.
(~[slow] ~[.],starting_items)=> Run with -? for options
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> Randomness seeded to: 1646052801
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> monster_throwing_sanity_test
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/monster_attack_test.cpp:176
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/monster_attack_test.cpp:230: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( damage_dealt.test_threshold( epsilon_threshold{ expected_damage, 2.5 } ) )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   false

**Comment by PatrikLundell** [comment]
"LGTM analysis: C/C++": "Failed" by tripping over its own feet by timing out.

**Comment by NetSysFire** [comment]
>"LGTM analysis: C/C++": "Failed" by tripping over its own feet by timing out.

As usual. It always times out for some reason, so it can not really be used to judge PRs at this time except when it reports new or fixed alerts.

**Comment by kevingranade** [comment]
I'm pretty much completely overwhelmed by the PR review workload right now.  I'm keeping up as best as I can (and sidelining the things I want to work on), but my time is limited at the moment.

**Pull request merged**
