### PR TITLE
Add an AR-10, HK417 A2, and M110A1

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
```SUMMARY: Content "Add an AR-10, HK417 A2, and M110A1"```

#### Purpose of change
Adds some more options for .308 rifles. Right now the only battle rifle that commonly spawns that takes standard size detachable magazines is the SCAR-H. All the new kevlar zombie types are making large caliber rifles look more attractive.

#### Describe the solution
Adds an HK417 A2, an M110A1, and an AR-10. These cover lots of different use cases between them.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Maybe change the name of the longer hk417 variant to the military version? M110A1. Then you could use that to further justify the included attachements.

Also the MSRP on the 417's is a bit higher, no? I'm seeing about $3200. I think this would make the 417 less common than the AR10's and FN scar's that have been around longer.

**Comment by Greevv** [comment]
Just gonna say I completely disagree with adding the G28.

**Comment by ymber** [comment]
I went with G28 E3 even though the ones actually in use with the US military are derivatives of the G28 because it's a reasonable close enough abstraction well within the standard of realism catas military item spawns adhere to. Given that a zombie soldier could have been anyone with a rifle and plate carrier my lore excuse is that it's expensive imported gear for a PMC operating in the region around the time of the cataclysm.

**Comment by kevingranade** [comment]
Your lore doesn't really make sense when that soldier appears alongside a bunch of other soldiers that are wielding all US-issue weapons.

Having said that, the current loadout is not consistent in the first place, it has all kinds of random shit in it :shrug:

**Comment by Greevv** [comment]
Wouldn't it ultimately be better to fix that though and find a better way
to get those guns into the game rather than exacerbating the problem?

**Comment by Greevv** [comment]
I would absolutely be willing to piece something together.

**Comment by ymber** [comment]
If there's the will to start fixing military item spawns in general I can rework these into stuff that 2019-2020 era US military would actually have.

My idea for getting it vaguely consistent is to decide at the time the map segment (outposts, helicopter crashes etc ) is generated what branch or company or whatever owned it then have it generate monsters all from that group with appropriate drops and descriptions. This would require modifying the mapgen code and adding either a load of different monster types or basic procedural monsters. Not sure how workable that would be but it's somewhere to start and it would probably be useful infrastructure for a load of other map features.

**Comment by DemAvalon** [comment]
Why not just have it spawn only in gun basements, safes and gun stores?, then you can just say its someones hot import.

**Comment by tenmillimaster** [comment]
@demavalon Because then it would be a HK MR762A1, which is closer to the m110 and hk417 anyways.
And HK isn't gonna go through the hassle of marketing a competitor to their own MR762A1, just for a steel upper receiver.

**Comment by tenmillimaster** [comment]
The 13" barrel will need a higher damage penalty, about -7.

Nominal m80/147gr fmj .308 in game travels at 2852 fps. (Assuming its in-game damage reduction is due to bullet design). 

<https://rifleshooter.com/2016/02/308-winchester-7-62x51mm-nato-short-barrel-length-and-velocity-a-six-inch-308-bolt-gun/>

A 147gr Winchester fmj load out of a 13" barrel produces 2515 FPS, about 2800 joules, or ~53 damage in fame., so a -7 damage penalty from the 'standard barrel length'.

**Comment by ymber** [comment]
I was thinking 13" was really short for a .308 barrel when I was doing it but word of GAME_BALANCE.md is -4 damage.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md#ammo-stats

**Comment by tenmillimaster** [comment]
Ah. I see- my assumption about projectile design and damage was incorrect. Refactoring the math yields a -6 damage penality. ((Sqrt 3304J)-(sqrt 2628J)). Using the -1 for every 3" guideline isn't very realistic for extreme differences in barrel length, see the 223 backup revolver for sources; velocity vs barrel length isn't s linear relationship.

**Comment by ymber** [comment]
Yeah the ballistic models still have room for refinement but that's for another PR.

**Pull request merged**
