### PR TITLE
Delete whitespaces in comestibles folder

### PR DESCRIPTION
**Pull request by Cyrano7**
From issue https://github.com/CleverRaven/Cataclysm-DDA/issues/16394 
Would this be meaningful to do across all files?
This PR only has space changes. https://github.com/CleverRaven/Cataclysm-DDA/pull/16395/files?w=1

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Sorry that I misunderstood what you meant about the ends of files.

Nuking useless whitespace is good but nuking newlines (line breaks) at the end of files isn't; they're supposedly necessary for some (not sure which) compilers to function properly.

**Comment by Cyrano7** [comment]
@Rivet-the-Zombie Are you sure? Because if that were true it would be the opposite situation, they're are a lot of files missing trailing line breaks, and they have been that way for a while.

**Comment by Rivet-the-Zombie** [comment]
Could be that it's no longer an issue.

**Comment by narc0tiq** [comment]
It's never been a real issue, it's just that Unix command line applications tend to expect files to end with newlines, and the **really** stupid ones will automatically cut the last character out of the file when reading it into, say, a shell variable.

I have yet to run into a situation where this is an issue, aside from Git itself crying about "No newline at end of file", though I do personally prefer to have a single newline at the end of all files.

**Comment by mugling** [comment]
A well put explanation @narc0tiq

**Comment by Cyrano7** [comment]
I've revised it now, adding a trialing line to mutagens.

**Comment by Cyrano7** [comment]
I might hold off on deleting more white spaces from .jsons  and instead try to catch them while migrating.

**Pull request merged**
