### PR TITLE
Changing movement mode to walking after waking up

### LINKED ISSUE #50644: Player stays prone after waking up from sleep
### Describe the bug

The player automatically lies down, going prone, when sleeping. When the player wakes up from sleep they are still prone; it doesn't matter if the wake up naturally or are interrupted. I believe the intention is to have the player automatically stand up after sleeping.

### Steps To Reproduce

For interrupted sleep:
1. Make an evacuee character
2. Sleep
3. Wakeup due to tossing and turning and you are still prone

For natural wakeup:
1. Make an evacuee character
2. Spawn blindfold, ear plugs, fur sleeping bag, and 3 poppy cough syrup
3. Place the sleeping bag on the ground
4. Drink a bunch of poppy cough syrup (like 12 doses)
5. Put in ear plugs and blindfold
6. Sleep and wake up naturally
7. There is no indicator the character stood up and if you walk you will see the ~500 move speed 

### Expected behavior

I assume standing up after sleep is the expected behavior.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d213995 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by StStep**
#### Summary
None

#### Purpose of change
Waking up after sleeping leaves the player prone, this PR changes their movement mode to walking after waking up. Fixes #50644 

#### Describe the solution

So I've added the change to movement mode if you cancel the sleep activity voluntarily due to the tossing and turning prompt.

I also added a start walking if prone to the character wake up function, but this has some issues below.

* It currently says "You start Walking" and then "You Wake Up" I think this because the remove laying_down effect gets printed after the wake_up function is called, while the  movement mode change happens in wake_up., see attached screenshot
    * If there was a way to standup as part of removing the effect that would be best, I'm not sure how to do that
    * If we did that we should also put going prone as part of starting the effect
 

#### Describe alternatives you've considered

Using an effect to handling going into the walk movement mode, but I'm not sure if that's possible.

#### Testing

For failing to sleep during the sleep activity:

1. Make an evacuee character
 2. Sleep
 3. Select the prompt when it appears to stop trying to sleep
 4. The character starts walking

For calling wake_up (actually having the sleep effect)

1. Make an evacuee character
2. Spawn blindfold, ear plugs, fur sleeping bag, and 3 poppy cough syrup
3. Place the sleeping bag on the ground
4. Drink a bunch of poppy cough syrup (like 12 doses)
5. Put in ear plugs and blindfold
6. Sleep and wake up naturally
7. The character starts walking

### CODE REVIEW

**Comment by StStep** [comment]
So the poppy flower puts the player to sleep but doesn't ever make them prone.

**Comment by StStep** [comment]
Since the try-sleep activity is setting the avatar prone, I don't think NPCs ever go prone to sleep.

If people are okay with the odd printing (Start Walking and then Waking Up) then I think this is ready

**Comment by Night-Pryanik** [comment]
Seems like you define `canceled` method, but never actually use it?

**Comment by StStep** [comment]
The cancel method is called as part of the user pressing ". or 5" to stop activities. It covers the case where the user has selected to ignore further warnings that they can't fall asleep, and then interrupt the try sleep activity.

**Pull request merged**
