### PR TITLE
[XE] Mad Inventor sandwich recipe

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Content "New mad genius recipe for a healing sandwich"

#### Purpose of change

I fucking love the Mad Inventor. It's such a unique concept. This is the first of possibly many recipes I will be adding. I noticed a distinct lack

#### Describe the solution

Adds a new recipe unlocked by intermediate research for the "cosmic dagwood," a food item which gives a short regeneration effect on consumption. It takes seven hours to make, uses some unorthodox ingredients, and spoils in ~~ten hours~~ a day which I see as a good enough balance for it. It's meant to be something you make preemptively before embarking on a looting spree somewhere for an emergency.

#### Describe alternatives you've considered

I could give it different effects.

#### Testing

The recipe works, the spell works as intended

### CODE REVIEW

**Comment by Daved27hundred** [comment]
A bug(?) is stopping this from progressing any further. I'm gonna have to report it and hope it gets fixed.

**Comment by martinrhan** [comment]
If you really like mad genius then you should stop adding useless recipes like this because it will just pollute the pool for random rolling of recipe.

**Comment by IdleSol** [comment]
Alternative. Instead of a spell, use a vitamin that has a healing effect.

**Comment by Daved27hundred** [comment]
The bug has been fixed, this is gonna be finalized soon, just need to iron out some more things.

**Comment by GuardianDll** [comment]
15 seconds, and gonna heal total of 150 hp (so around 25 hp per limb)

**Pull request merged**
