### PR TITLE
[CR] Set player position to the updated submap shift before checking for seen overmap tiles.

### PR DESCRIPTION
**Pull request by DanmakuDan**
For #14309.

`game::update_map` is calling `update_overmap_seen` before the player's position has been corrected for local submap shifting, causing the wrong overmap location to be checked for visibility. This applies the map shift relocation to the player before `update_overmap_seen` is called. I went ahead and removed some of the unnecessary `setpos` references done where `update_map(x,y)` was called.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This seems to break flinging. All hulk smashes end where they start or just a single tile away.

**Comment by DanmakuDan** [comment]
It should be fixed now, `update_map` needed to set the position of the player even if the map didn't move. Also, is `is_u` necessary if the if statement already checked that `player p` is being referenced, or is there a case where the `player*` object doesn't reference the player?

**Comment by Coolthulhu** [comment]
> Also, is is_u necessary if the if statement already checked that player p is being referenced, or is there a case where the player* object doesn't reference the player?

Can be a NPC

**Comment by DanmakuDan** [comment]
In that case, what happens when a NPC gets flung out of the viewable area (x/y < 0 or > MAPSIZE*SEEX/Y)?

**Comment by Coolthulhu** [comment]
From the looks of `map::move_cost`, tiles outside bounds should be unpassable and thus un-flingable-into.

**Pull request merged**
