### PR TITLE
Longer bolts

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
Bugfixes "Make bolts longer"

#### Purpose of change
Arrows already have the right lengh. Bolts do not. They were still sitting at 3 cm. 

#### Describe the solution
Since there are different bolt lenghts from usually 16 inches to 22 inches for normal crossbows, I used the smallest ones, for player friendlyness, which is around 40 cm.

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
Which sources did you use for these bolt lengths?

**Comment by Lamandus** [comment]
> 
> 
> Which sources did you use for these bolt lengths?

A german Hunting-Forum and own knowledge.

**Comment by actual-nh** [comment]
BTW, "zoll"?

**Comment by LaVeyanFiend** [comment]
> > Which sources did you use for these bolt lengths?
> 
> A german Hunting-Forum and own knowledge.
> 
> There are 6 zoll ones for pistol crossbows tho. But they are no good use for normal crossbows. (That would be 15 cm).
> 
> Edit:
> Since you gave me that confused smiley without further context.
> https://www.co2air.de/thema/93810-jaguar-175lbs-ideale-l%C3%A4nge-der-bolzen/
> for example. I can provide more.

Was gonna say we can't check your sources if you don't give em, good mindreading! 😄

**Comment by Lamandus** [comment]
> 
> 
> BTW, "zoll"?

oh god, used the german term.
Inch.

**Comment by actual-nh** [comment]
BTW, your opinion on [this discussion](https://github.com/CleverRaven/Cataclysm-DDA/discussions/47458)?

**Comment by Lamandus** [comment]
> 
> 
> BTW, your opinion on [this discussion](https://github.com/CleverRaven/Cataclysm-DDA/discussions/47458)?

considerable. But one step at a time. The discussion is more "balancing" this is "bugfixing" rather.
I mean if we go full "realistic" pistol-crossbows should have their own ammonition. But that is something for after the F.

**Pull request merged**
