### PR TITLE
Mapgen enhancement part 2

### PR DESCRIPTION
**Pull request by BevapDin**
This is the second mapgen enhancement. It fixes some small bugs and adds:
- placing traps, specific monsters (not from a group) via json mapgen,
- randomly chosen terrain/furniture/traps aka "grass or dirt",
- a test mapgen for testing and showing the syntax.

The test mapgen is a normal overmap terrain and a json mapgen entry for it. It will not appear in the normal game and can reached through the debug system (because there is no entry for the test terrain to spawn).

Please refer to the changes in doc/MAPGEN.md for the documentation of the changes / additions to the mapgen system. It should all be documented there. Comment if something is missing or not clearly enough documented.

I also replaced the `place_toilets` and `place_gaspumps` entries in the existing mapgen json files with equivalent `toilets` / `gaspumps` entries. Those use the terrain mapping to determine their location instead of the explicit coordinates. This makes moving those things around way easier.

Any further mapgen stuff that is wished for? Now is the time (-:

---

I planned another (hopefully last) addition to allow this:

``` JSON
"place": [
    {
        "area": { "shape": "rect", "x": [10, 20], "y": [10, 14] },
        "fields": { ... },
        "terrain": "t_dirt",
    }
]
```

The `area` entry describes the area where to do things (different shapes would be possible), the other entries would work like the usual special entries. Basically it allows to place different things randomly but together. Currently it's not possible to place a row of display racks randomly and fill them with loot. One can place the racks randomly through the "set" thing:

``` JSON
"set": { "line": "furniture", "x": 1, "y": [1,10], "x2": 10, "y2": [1,10], "id": "f_rack" }
```

But the item groups to fill those with content have to be set separately through the "place_items" entries and won't match the location of the racks.

With the proposed addition it would look like this:

``` JSON
"place": [
    {
        "area": { "shape": "line", "x1": 1, "y1": [10, 14], "x2": 10 },
        "furniture": "f_rack",
        "items": { "item": "museum_armor", "chance": 10 }
    }
]
```

This would allow easily implementing many different shapes.

### CODE REVIEW

**Comment by KrazyTheFox** [comment]
This is fantastic! That test entry is extremely helpful.

**Comment by acidia** [comment]
Ah, I see you already found the 'place_npc' vs 'place_npcs' bug that was preventing some static NPCs :)

How difficult would it be to make function that would fill existing furniture, something like:
"fill": [
    {
        "area": { "shape": "rect", "x1": 1, "y1": [1, 22], "x2": [1, 22] }, //So effectively everything
        "furniture": "f_desk",
        "furniture": "f_locker", //fill either furniture type
        "items": { "item": "school", "chance": 40 }, //fill with potentially both
        "items": { "item": "snacks", "chance": 10 }
    }
]
This would save me a huge amount of time when building large structures where I typically count off the squares for the first line of desks for the item field and copy/paste it over and over for each additional row.  This way, I could effectively copy and paste that one function and fill all of the desks in a matter of seconds.

**Comment by BevapDin** [comment]
> Ah, I see you already found the 'place_npc' vs 'place_npcs' bug that was preventing some static NPCs :)

Yes, this is another thing the test mapgen is supposed to detect.

----

> How difficult would it be to make a function that would fill existing furniture

This is what I meant with the suggestion. You call it "fill", I called it "place", but that is merely a word, "fill" might be better actually.

It would have to be like this (json does not allow multiple entries with the same name, those need to be a single entry containing an array):
```JSON
"fill": [
 {
 "area": { "shape": "rect", "x1": 1, "y1": [1, 22], "x2": [1, 22] },
 "furniture": [ "f_desk", "f_locker" ],
 "items": [ { "item": "school", "chance": 40 }, { "item": "snacks", "chance": 10 } ]
 }
]
```

This is actually relatively easy to implement, I'll only have to add the code for the different shapes that need to be supported. The other part (*what* should be placed) already exist and can be linked. That means all stuff that you can place via "place_*" or via a mapping into the ASCII map will also be available for this fill thing.

However the shape is a bit ambiguous: is y1/x2 supposed to random value between 1 and 22? Or does it mean all values from 1 to 22? For this I propose to either name the shape differently (e.g. "random-rect" when the coordinates are chosen randomly, "rect" when they are fixed) or using a width / height setting instead of x2/y2. The width/height itself could be random but that would be unambiguous.

```JSON
// Total area 22x22 squares:
"area": { "shape": "rect", "x": 1, "y": 1, "h": 22, "w": 22 },
// Total area 22xrandom squares:
"area": { "shape": "rect", "x": 1, "y": 1, "h": 22, "w": [1, 22] },
```

And the shape could even be a simple map on its own:
```JSON
"area": { "shape": "map", "x": 1, "y": 1, "rows": [
    "#  #  #",
    "#  #  #" ] },
```
The furniture and so on would be placed only at the '#', leaving the free areas unchanged.

**Comment by KA101** [comment]
Out of time error on my part, no reflection on these PRs.  My apologies.

**Comment by KA101** [comment]
I'd wish for underground sewers to connect to sewage treatments, subways to run between at least two stations, etc. But right now I'll test what we've got.  This has sat around way too long.

**Comment by sparr** [comment]
mapgen test doesn't seem to test placing item groups, particularly recently defined ones.

**Comment by BevapDin** [comment]
Can you be tiny bit more specific, please? What did you do? What happened? What did you expect to happen?

**Comment by sparr** [comment]
Sorry, I'm not saying it's doing something wrong. I'm saying it doesn't test having an item group defined in the file and then used. I suggest adding that test.

**Comment by BevapDin** [comment]
That doesn't need to be tested (at least not here with the mapgen), every json stuff is loaded from every json file. It doesn't matter where item groups are defined and there is no reason to test whether the game loads the item group from that specific file.

The loading procedure is to go through all files and load all json objects they contain. One can put a whole mod (items, monsters, recipes, vehicle parts, vehicles, mutations etc.) into one file.

Therefor if the game would act like you suggest, it would also have to test for monsters, items etc. being *defined* in the mapgen file (which is easily possible), but that is *not*  a special feature of the mapgen code. In fact, you can write mapgen entries into the item files or into data/json/monsters.json, or write monster entries into the mutation files, doesn't matter at all.

**Comment by KA101** [comment]
>In fact, you can write mapgen entries into the item files or into data/json/monsters.json, or write monster entries into the mutation files,

Hmm, good to know.

>doesn't matter at all.

Yes, it does: Chaos-based anti-organization makes our job more difficult, so folks putting mapgen in places it's not expected are unlikely to get their PRs merged.  ;-)

**Pull request merged**
