### PR TITLE
In the crafting GUI, show which books provide this recipe

### PR DESCRIPTION
**Pull request by nornagon**
cataclysm__dark_days_ahead_-_0_c-22800-gca9433d9d8

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This sounds useful, but also potentially very, very slow.
I'd say it must be properly cached before it gets in. You'll have to map all the recipes to books in the crafting GUI functions, then display them. The `player::get_books_for_recipe` has to go - it is unacceptable to look up the crafting inventory for every recipe.

I see it working like this:
* When opening the crafting menu, create a `std::map` of recipes to list of books - this can be `std::map<const recipe *, std::list<const item *>>` or `std::map<recipe_id, std::list<item_id>>` 
* Fill it out once, during opening, even for recipes that aren't displayed
* When showing a recipe, you'd only need to look up if the book is in the cache instead of going through all books in the inventory again

Alternatively:
* When opening the crafting menu, store a list of pointers to all books
* When showing a recipe, pass only this list of pointers instead of whole inventory

Either way, going through all items in crafting inventory more than once per tab switch is unacceptable and has caused giant slowdowns in the past.

**Comment by nornagon** [comment]
Great, thanks for the feedback! I took this approach because it was the simplest thing that could possibly work and I wasn't sure if it would be fast enough. I'll rework it to only compute once per menu-open.

Would it make sense to rework `get_available_recipes` to also store _where_ the recipe came from in the `recipe_subset`? Or best to just do a second iteration through the crafting inventory?

To inform my future intuition, what's the approx. order of magnitude of the # of items in a crafting inv that the game aims to support smoothly?

**Comment by Coolthulhu** [comment]
> Would it make sense to rework get_available_recipes to also store where the recipe came from in the recipe_subset?

I'm not sure if `recipe_subset` doesn't have any other roles, where that data might be unavailable. All instances of `recipe_subset` should have the same kind of data, there should be no "`recipe_subset` created with function `x` will have this data, but one created from `y` will not".
But if it is only used for things where this data is available, feel free to go for it.

Though do check if `recipe_subset` isn't stored anywhere. Pointers to items can be invalidated after any player action that changes the game world, including actions that may not invalidate crafting inventory.
You could try storing `item_location`s instead, if you wanted to protect self against invalidated pointers or wanted to include where the book is (say, "this recipe is from that Mechanical Mastery, on the cart to your west").

> To inform my future intuition, what's the approx. order of magnitude of the # of items in a crafting inv that the game aims to support smoothly?

"As much as possible", but I'd say that 10k is the highest expected in a normal game.
It only really means "no quadratic (average) complexities allowed".
We did have quadratic complexities in crafting menu at one point and it wasn't totally insufferable, but it was really bad.
If you handle each item(/item type/recipe) in something near logarithmic time, it's most likely well within the limits.

**Comment by codemime** [comment]
Each recipe stores `booksets`. It generally _knows_ in which books it's contained. Therefore you don't need to iterate over the whole crafting inventory, only check for those books.

**Comment by Coolthulhu** [comment]
> However, that probably won't be much faster since requires linear search anyways. We'd probably need a quicker way of checking whether an item is in the inventory or not.

They're binned by ID on creation of crafting inventory. `inventory::charges_of/amount_of` should only be linear with number of items sharing the ID, not the size of the whole inventory.

**Comment by nornagon** [comment]
I'm looking at `get_binned_items` in inventory, which looks like it's lazily created by a linear search?

**Comment by nornagon** [comment]
Ah, I see `charges_of` uses `get_binned_items`. `booksets` is currently private on recipe, would it be OK to make it public?

**Comment by nornagon** [comment]
Updated to use `amount_of`, which should be linear in the number of books of the relevant types for the recipe available in the crafting inventory, rather than linear in the size of the whole inventory. (Though the construction of the binned items still needs to happen at some point, which is a linear scan. I'm not sure if that's already happening as part of the crafting GUI processing, or if this is a new usage of that lazily-computed value.)

**Pull request merged**
