### PR TITLE
update 3 houses, add roofs

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
```SUMMARY: Content "add roofs and update 3 houses"```

#### Purpose of change
continue house project
includes the prepper type houses.
#### Testing
spawned in world.

#### Additional context
house_prepper (shares house_04 roof)
house_prepper
house_prepper after

house_prepper2: forgot the before pic, but most are familiar with the trap house.  
I've updated the traps some, and added more traps and loot.

house_prepper 2 after
house_prepper 2 roof

house_fortified:
house_fortified before
house_fortified after
house_fortified roof

### CODE REVIEW

**Comment by Inglonias** [comment]
How many more of these are there left to go?

**Comment by curstwist** [comment]
18 to go

**Comment by Inglonias** [comment]
Wow. Keep up the good work.

**Comment by LaVeyanFiend** [comment]
From house_prepper:

image
Are they supposed to be blocking themselves in behind the rack & gunsafe?

**Comment by Brian-Otten** [comment]
The prepper house is a real beauty, You're doing a ton here to make cata feel more alive.

**Comment by curstwist** [comment]
> 
> 
> From house_prepper:

> Are they supposed to be blocking themselves in behind the rack & gunsafe?

completely intentional.

**Comment by I-am-Erk** [comment]
House_fortified has two open doors. maybe move a table to block the front door?

**Pull request merged**
