### PR TITLE
Create a crafting recipe for solder

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

```SUMMARY: Content "Adds a crafting recipe for solder"```

#### Describe the solution
* Added rosin and recipe
* Added lead/tin based solder recipe

#### Additional context
fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/26601

### CODE REVIEW

**Comment by tenmillimaster** [comment]
<https://hackaday.com/2012/09/19/diy-flux-comes-straight-from-the-tree/>. Unless you're interested in keeping the turpentine, an alcohol extraction would suffice (though you could distill the solution to recover your alcohol)

**Comment by l29ah** [comment]
You're welcome to include more rosin recipes in the following pull requests i suppose ;)
Also there are other kinds of soldering flux available, i've just picked the easiest one.

**Comment by eilaattwood** [comment]
Sad I'm late and this PR was already merged... 50% tin solder is actually rarely used, especially in the making of electronics. 61% tin solder is most widely used, because it's eutectic and has lower melting point (so it overheats precision electronics less).

**Comment by l29ah** [comment]
Yeah, it melts at 183°C versus 222°C for the 50% one, good point, but doesn't matter as much i think.

**Comment by eilaattwood** [comment]
> Yeah, it melts at 183°C versus 222°C for the 50% one, good point, but doesn't matter as much i think.

That fact that 61% tin solder is eutectic is actually matter quite much. Well, 50% is still usable, but noticeably harder to use when soldering manually.

Eutectic means that melting means that solidifying and melting points of the alloys are almost the same.
So when using non-eutectic solder when it begins to coll and solidify it is not an instant process. When temperature of the solder is between melting and solidifying temperature is actually mix of microscopic solid crystals and liquid around them. If you accidentally move parts in that moment you will completely mess up the soldering and it will not hold. And with eutectic solder there is no that semi-liquid state, so soldering is much easier.

**Pull request merged**
