### PR TITLE
Added pineaple to veggy pizza recipe.

### PR DESCRIPTION
**Pull request by Broken27**
#### Summary
None

#### Purpose of change

Some people have really terrible taste, and the game should have recipes for them.

#### Describe the solution

Just a couple of new json lines in the vegetable pizza recipe

#### Describe alternatives you've considered

None

#### Testing

Loaded the game, made a pizza using pinneaple, dropped it in the sea.

#### Additional context

This is all ERRORCODE509 [fault](https://www.reddit.com/r/cataclysmdda/comments/orunou/pineapple_pizza_released/).

### CODE REVIEW

**Comment by definitelynotklip** [comment]
how do i close someone else's pr

**Comment by I-am-Erk** [comment]
I will never understand the strength of opinions people have about pineapple on pizza.

I put mango on a pizza the other week

**Comment by Broken27** [comment]
Damn that was a fast merge

**Comment by I-am-Erk** [comment]
Target of opportunity

**Comment by ERRORCODE509** [comment]
Looks like I'll have to override this recipe.

**Comment by scorpion451** [comment]
Finally, game-breaking bug addressed, pizza can be made properly now.

**Pull request merged**
