### PR TITLE
JSON optimization: remove default cutting value, part 2

### PR DESCRIPTION
**Pull request by illi-kun**

### CODE REVIEW

**Comment by Malkeus** [comment]
The game crashes at world load in 0.C - 8503(this is the only pr in that version), works fine in 0.C -8501 (directly previous to this PR). Something, something, seeking a missing comma.

**Comment by illi-kun** [comment]
Thanks, I will check that (I probably told about similar PR landed previously).

**Comment by Malkeus** [comment]
whoops, I meant to comment in the commit that landed, didn't notice this was part 2

**Comment by illi-kun** [comment]
Can you share your save file?

**Pull request merged**
