### PR TITLE
Fix flight_helmet materials

### PR DESCRIPTION
**Pull request by TannHaals**
#### Summary
None

#### Purpose of change
Military flight helmet's stats don't match its turned on version. 
flight_helmet_compare

#### Describe the solution
Changed flight_helmet's material from "nomex" to "kevlar_rigid", "plastic", which also fixes the length issue. 

#### Testing
Checked in-game to see that the values match.

#### Additional context
Should the flight helmet have the VARSIZE flag? Seems a bit odd considering many other helmets don't.

### CODE REVIEW

**Comment by Photoloss** [comment]
> Also migrated the entries from tool_armor.json to armor\helmets.json as that makes more sense IMHO.

There needs to be some universal guideline for this, sadly I don't know whether we already have one. "tool_armor" is for wearable items which can be (a)ctivated. Notably the only visored helmet in that file is the motorcycle helmet, all the others e.g. the sallet and the riot helmet are somewhere else, mostly in tool_armor.

**Comment by TannHaals** [comment]
> There needs to be some universal guideline for this
Personally I felt it made more sense leaving tools that happen to be wearable (earplugs, whistle etc.) in "tool_armor", while moving activated wearables with minor tool usage into their respective jsons. Would make it easier to find and standardize values across a certain category of clothing.

That said, if anyone delineates any guidelines for this I'd be more than willing to defer to those.

**Comment by Photoloss** [comment]
> moving activated wearables with minor tool usage into their respective jsons. Would make it easier to find and standardize values across a certain category of clothing.

That should go into a separate PR then, and do it *properly* for all item categories currently squished together in tool_armor. Right now you are adding a second exception to the otherwise fairly consistent rule, even most scarves are in tool_armor and not the dedicated "scarfs.json".

Mind you I personally do think grouping by body part, layer or the like to be much more useful than some internal template type but this is definitely not my decision to make, and there might be some reason (e.g. testing) for things to be this way.

**Comment by TannHaals** [comment]
> That should go into a separate PR then, and do it properly for all item categories currently squished together in tool_armor. Right now you are adding a second exception to the otherwise fairly consistent rule, even most scarves are in tool_armor and not the dedicated "scarfs.json".

That's a fair point. I'll migrate those entries back for now then.

**Pull request merged**
