### PR TITLE
Advanced door and window mechanics

### LINKED ISSUE #54166: Silently open/close doors and windows
### Is your feature request related to a problem? Please describe.

Many times when I am scavenging and I approach a door or a window I know is unlocked I always think to myself:

> What if a monster close-by hears me opening this door/window and foils my plans?

Because closing doors is so loud it is possible for monsters in adjacent buildings hearing it.

### Solution you would like.

I would like to propose adding an ability to open and close doors and windows silently.

This could be implemented in the following ways:

- Opening doors while crouching makes 3 (6) noise and costs 300 (100) moves.
- Closing doors while crouching makes 5 (10) noise and costs 270 (90) moves.

Opening and closing windows would follow the same implementation.
This would allow players to sneak around buildings more easily by trading move points for stealth.

### Describe alternatives you have considered.

Displaying a menu when opening/closing doors and windows that let's players choose whether to open/close normally or silently.
The problem with this approach is that it would add additional key presses that would be redundant in most situations as most times you want to open or close the doors normally.

### Additional context

See [feature branch](https://github.com/matshou/Cataclysm-DDA/tree/feat/54166) for implementation details.

### PR DESCRIPTION
**Pull request by matshou**
#### Summary
Features "Introduced advanced door and window mechanics"

#### Purpose of change

Doors and windows are very versatile objects that should provide more interactions beside just opening and closing. Introducing features that allow us to control and take advantage of doors and windows would allow the player to use said doors and windows to their full potential.

For example allowing doors and windows to be opened silently would make scavenging in cities a lot easier. Doors normally produce 6 noise when opened and 10 noise when closed which is too much noise when attempting to sneak. Adding the ability to _dash_ through doors (quickly opening them while running) would allow for easier escapes from indoor settings.

Resolves #54166

#### Describe the solution

- [x] Doors, windows and curtains are opened silently while crouching, producing less noise at the cost of movement points.
- [x] Doors can be _dashed_ through when running, moving while opening at the cost of producing more noise.
- [x] Interaction speed with heavy doors and windows is affected by the following:
    - [x] Each point above 8 (up to 12) strength decreases open/close movement cost overhead above 100 by 25%. For example if a heavy door costed 200 moves to open and the character had 10 strength then the final movement cost would be 150.
    - [x] Each point below 8 strength increases open/close movement cost overhead above 100 by 25%. For example if a heavy door costed 150 moves to open and the character had 6 strength then the final movement cost would be 175.
- [x] Interaction noise is affected by the following:
    - [x] Each point below 8 dexterity increases open/close noise by 25%.
- [x] Each of the following conditions disables interaction:
    - [x] Character is in prone movement position.
    - [x] Character is carrying items in both hands.
    - [x] Character has both arms broken.

#### Describe alternatives you've considered

_No alternatives considered._

#### Testing

Unit tested with 152 assertions in 7 tests cases.
See `tests/gates_test.cpp` test file.

#### Additional context

_No additional context available._

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I understand the intention, but is it even possible IRL to open windows while being crouched? I mean, one simply wouldn't have reach to do this.

**Comment by PatrikLundell** [comment]
I don't think strong people open normal doors faster than weak people. Heavy church or vault doors, yes, possibly, but normal doors? No. Kids can easily open doors at the "normal" speed as it require very little effort.

**Comment by matshou** [comment]
> I don't think strong people open normal doors faster than weak people. Heavy church or vault doors, yes, possibly, but normal doors? No. Kids can easily open doors at the "normal" speed as it require very little effort.

We can do it only for specific doors. 
Do you have any door types in mind that should be affected by strength?

**Comment by PatrikLundell** [comment]
No, I don't know enough about different door types to single out heavy ones. I don't even know if the game features heavy doors at all. It really comes down to inertia, i.e. how much mass you'll have to push (and pull, to stop them from slamming into the door stop).

**Comment by matshou** [comment]
> No, I don't know enough about different door types to single out heavy ones. I don't even know if the game features heavy doors at all. It really comes down to inertia, i.e. how much mass you'll have to push (and pull, to stop them from slamming into the door stop).

This is the list of all doors in the game:
https://nornagon.github.io/cdda-guide/#/search/door

The heaviest doors would be open and closed metal door to which we can apply the strength based modifier.

**Comment by PatrikLundell** [comment]
It doesn't look like to me that the metal door has enough mass to be hard to handle.

**Comment by matshou** [comment]
> It doesn't look like to me that the metal door has enough mass to be hard to handle.

We can pretend it does for the sake of gameplay.

**Comment by Maleclypse** [comment]
I noticed all your boxes are marked complete, is this ready to leave draft?

**Comment by matshou** [comment]
> I noticed all your boxes are marked complete, is this ready to leave draft?

Yes sir, I was just waiting for the build pipeline to finish it's thing.

**Comment by Maleclypse** [comment]
> > I noticed all your boxes are marked complete, is this ready to leave draft?
> 
> Yes sir, I was just waiting for the build pipeline to finish it's thing.

Cool deal.  I've done that and then left something in draft for a week until I looked to see if there was a reason it wasn't getting merged.  Lol.

**Comment by Night-Pryanik** [comment]
Could you please resolve conflicts?

**Pull request closed without merging**
