### PR TITLE
Increased shop stock

### PR DESCRIPTION
**Pull request by crazykiddeath**
#### Summary

```SUMMARY:  "To increase the general stock in shops and commercial district to be more inline with what such places would be stocked with."```

#### Purpose of change

To increase the general stock in shops and commercial district to be more inline with what such places would be stocked with.

#### Describe the solution
Went through the JSON files for shops, restaurants etc and increased common loot amounts and drop chances.

#### Describe alternatives you've considered

Reducing rare loot, leaving it as is.

[mapgen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3746910/mapgen.zip)

### CODE REVIEW

**Comment by ymber** [comment]
You've got all kinds of stuff in here that isn't meant to be. Keep your changes separate and use feature branches.

**Comment by crazykiddeath** [comment]
> 
> 
> You've got all kinds of stuff in here that isn't meant to be. Keep your changes separate and use feature branches.

Sorry, try to figure it out right now

**Comment by Kodiologist** [comment]
I always assumed that there's less stuff than you'd see in a real store because by the time the player gets to a store, it's already been mostly looted by other people.

**Comment by anothersimulacrum** [comment]
PR doesn't mention it, but I believe it's attempting to address #34432.

**Comment by I-am-Erk** [comment]
I strongly agree with this PR in spirit, but you've got a heck of a mess going on here. Stop deleting and replacing files, create a new branch from master, put only your changes on it, and PR that.

**Comment by crazykiddeath** [comment]
> 
> 
> I strongly agree with this PR in spirit, but you've got a heck of a mess going on here. Stop deleting and replacing files, create a new branch from master, put only your changes on it, and PR that.

Is there some way to remove this pull request so I can do this properly?

**Comment by anothersimulacrum** [comment]
> Is there some way to remove this pull request so I can do this properly?
You can close it.

**Pull request closed without merging**
