### PR TITLE
Proficiencies for food recipes 1

### PR DESCRIPTION
**Pull request by SamGondra**
#### Summary
Content "Proficiencies for food recipes part 1"

#### Purpose of change
Adds proficiencies to the first few recipe files as far as I could tell they should apply based on https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/PROFICIENCY_LIST.md

#### Describe alternatives you've considered
Not doing the tedious copy paste work, but my Brain has been annoyed with the state of things for too long...

#### Additional context
Will likely try to work on the rest of the (Food-) recipes over the next few days, but wanted to test the waters if my interpretation is okay before I frustrate myself.

### CODE REVIEW

**Comment by SamGondra** [comment]
Is this (till now) okay how I assigned the proficiencies?
Then I will start running through more of the files in the next few days.

**Comment by I-am-Erk** [comment]
It should be. The only delay here for me is that I've been too busy to review properly. Hoping to have some time in the next week or so

**Comment by SamGondra** [comment]
okay, will try to restart going through recipes next week, it is too warm to try to this weekend.
If you want I can keep this as is, and open a second PR for new files.

**Comment by SamGondra** [comment]
Sorry it got to warm to spend much time at the PC - not sure when I can get back to finishing.

**Comment by I-am-Erk** [comment]
Sorry for the delay! I confess I utterly forgot

This looks good for the most part. I think you've used the food prep proficiency a bit more widely than I intended, but I don't have a strong opinion on that. Let's merge and see where it takes us.

**Pull request merged**
