### PR TITLE
Soylent green

### PR DESCRIPTION
**Pull request by Cyrano7**
Removes dry_hflesh from protein powder recipe and adds new hflesh material protein powder, shake, and drink.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Going with the movie version, eh?

**Comment by Cyrano7** [comment]
"refined protein made of people!"

**Comment by Cyrano7** [comment]
oh wait the quote is *Soylent Green is made out of people* I need to change it now.

**Comment by chaosvolt** [comment]
Huehuehue. Of course, another option is to find a funny alliterative name for human protein powder. People Powder would be rather silly. Pedro Powder? Um...need more names starting with a P.

**Comment by Malkeus** [comment]
Patrick, peter, paul, pinhead, plato, patroclus, ponce, plebe, perry, pan,
pam, polly, philip, penny, Pinocchio, peasant, I'm dry.

**Comment by Malkeus** [comment]
I like peasant. Peasant Powder has a nice ring to it.

**Comment by chaosvolt** [comment]
Peasant, pleb, or maybe Peter...nah, Peter Powder sounds like a name for some kinda aphrodisiac.

**Comment by Malkeus** [comment]
Lol, it's a blend of viagra, cialis and rhino horn.

**Comment by chaosvolt** [comment]
With just a pinch of cocaine for good measure.

**Comment by Malkeus** [comment]
Cocaine is an anti peter powder. It reduces blood flow to your extremities.
My friend told me..

**Comment by chaosvolt** [comment]
Right. Your friend. o3o

Anyway. Powdered Peasant or Peasant Powder sounds funniest.

**Comment by Malkeus** [comment]
I like powdered

**Comment by Malkeus** [comment]
Will vegetarians still be able to eat this without penalty, like they can
eat protein powder?

**Comment by chaosvolt** [comment]
> Will vegetarians still be able to eat this without penalty, like they can eat protein powder?

That smells like a bug, unless you can make normal protein powder using non-meat sources, in which case we might want to split that off into a vegetarian recipe.

**Comment by Malkeus** [comment]
Kevin describes it as being processed so far from its meat origins as to be
unidentifiable as meat for vegetarians. I'd consider this a feature. A
Microsoft style feature, at least.

**Comment by chaosvolt** [comment]
Hmm. Guess that works. But if the entire point of making human protein powder is the idea that you couldn't stop thinking of it as cannibalism... :V

**Comment by chaosvolt** [comment]
Que? D:

**Comment by Cyrano7** [comment]
Was scrolling on mobile and pushed close :(

**Comment by Malkeus** [comment]
That's why I was asking. Does it drop somewhere or is the only way to get
it by making it? That could be the discerning factor, you can't forget
because you chopped up Billy, dried and powdered his pieces, giggling to
yourself all the while...

**Comment by Cyrano7** [comment]
they are not in any groups so the only way to get them is to make them. I'm pretty sure it's like that for all human foods.

**Comment by chaosvolt** [comment]
If I recall, human pizza has supposedly showed up in pizza parlors, and human foods of some sort might show up in police evidence lockers, but that's about that.

**Comment by Malkeus** [comment]
I guess it works then. With protein powder you can pretend it's just that
same processed bean curd they sell to weight lifters. Soylent green has too
many memories associated with it for you to ever forget where it came
from...most meat doesn't talk to you before you kill it, it's hard to get
that out of your head.
This is all just rationalization to discourage someone from nerfing protein
powder x/

they are not in any groups so the only way to get them is to make them. I'm
pretty sure it's like that for all human foods.

—
Reply to this email directly or view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/pull/14658#issuecomment-167878378>
.

**Comment by Rivet-the-Zombie** [comment]
>Kevin describes it as being processed so far from its meat origins as to be unidentifiable as meat for vegetarians. I'd consider this a feature. A Microsoft style feature, at least.

[You mean my post?](http://smf.cataclysmdda.com/index.php?topic=11858.msg261849#msg261849)

To the best of my knowledge, Mr. Granade hasn't weighed in on the matter.

**Comment by kevingranade** [comment]
I can kind of buy the "separation from its origins" argument, but it's a
bit of a stretch.

**Comment by Malkeus** [comment]
It's been a long long long week. My apologies.

**Comment by Rivet-the-Zombie** [comment]
No need to apologize; I was just confused as to what you were referring to.

**Comment by Chezzo** [comment]
Every single protein powder recipe I can find on the nets is vegetarian.

There are some STORE made all beef protein drinks for Paleo weirdos, but they are a whole lot more treated than chopped beef jerky.

Y'all are drinking meat shakes.

**Comment by chaosvolt** [comment]
Jerky Juice, it's got what survivors crave!

**Pull request merged**
