### PR TITLE
[FINISHED!] [MOD] Craftable Weapons & Gunpowder

### PR DESCRIPTION
**Pull request by Zaweri**
Adds a mod to add the old gunpowder recipe back due to popular demand. Also adds _A LOT_ of craftable guns.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Nice. If I may make a suggestion, one could also bump the recipe for blackpowder down to being autolearned, based on the idea of its access being balanced relative to smokeless powder. So basically if smokeless powder is uncraftable, then have blackpowder craftable via book, but if smokeless powder if craftable via book then make blackpowder autolearned.

**Comment by kevingranade** [comment]
It is not remotely reasonable for modern gunpowder to be craftable, see
previous discussion elsewhere.

**Comment by chaosvolt** [comment]
As a mod content, maybe acceptable. As mainline, absolutely not and this is understandable.

If anything this could be the general go-to mod for nifty gunsmithing ideas that are too much of a breach in realism to allow for mainline. We'd need to massively expand on what all "veto'd for mainline" stuff should go here.

**Comment by drbig** [comment]
I concur with this being OK for a mod. It even comes with fair warning.

**Comment by kevingranade** [comment]
My bad, I missed that it was a mod from the summary since I'm on my phone.
I'd much prefer that multiple things get bundled into the mod (eventually,
this isn't a request for the PR), otherwise the mod selection menu gets
terribly cluttered.
Name suggestion, 'fast and loose gun mod'. :)

**Comment by chaosvolt** [comment]
Understandable, it doesn't say in the title that it's a mod.

And ja, more ideas for stuff to bundle in it. I dunno, Sten maybe? Once again drawing from my experience with content that shouldn't be craftable in mainline?

**Comment by drbig** [comment]
> I'd much prefer that multiple things get bundled into the mod (eventually,
this isn't a request for the PR)

This one is pretty specific. As far as bundling goes: sure as long as it make sense, only caveat I have is that mixing JSON-only mods with Lua-requiring mods might be not so great.

**Comment by karlnp** [comment]
This would be a good candidate for other requested-but-suicidal gunsmithing ideas, like loading modern rounds with black powder, repriming rounds, etc.

**Comment by chaosvolt** [comment]
> This would be a good candidate for other requested-but-suicidal gunsmithing ideas, like loading modern rounds with black powder, repriming rounds, etc.

Ja.

**Comment by Zaweri** [comment]
There we go, testing worked as intended and everything worked /flawlessly/. Damn I'm good.

**Comment by chaosvolt** [comment]
> pipe SMG: 9mm

So instead of a Sten, which is easily made with basic metalworking knowledge and tool in reality, you add a generic version.

**Comment by Zaweri** [comment]
Chaosvolt, I am adding stuff that existed in the game before, and variations of it. I don't want to make new stuff. I just want the old guns back.

**Comment by chaosvolt** [comment]
...we had pipe SMGs in the past? How long ago was this?

**Comment by Zaweri** [comment]
*Old man voice* Back in my day, Pipe SMG's existed... They were in 0.5, when I started playing... Don't know where they went.

**Comment by chaosvolt** [comment]
They must've went the way of sanity and logic, because whoever added them half-assed it big time, if you're using the original recipes. Seeing as they seem to just use pipe rifle recipes with some minor edits...

If this is basically just re-implementing content removed due to breaches of realism, then I suppose it's understandable.

**Comment by kevingranade** [comment]
Just to be clear, mod authorship doesn't mean "owning" the code, if @chaosvolt wants to make some of the recipes more reasonable, that should be fine, yes?

**Comment by chaosvolt** [comment]
If one does implement a more realistic recipe for a handcrafted SMG...hmm. Where'd I leave that example recipe I was going to propose way back when...

Would've been closer to the "practical scrap metal arms" recipe than the recipe I first proposed even farther back when I added the Sten. I'm assuming I scrapped it once it was clarified that the survivor .223 and .308 rifles are only described as semi-auto due to the game derping.

**Pull request merged**
