### PR TITLE
Removes old tiles.png, adds expanded one

### PR DESCRIPTION
**Pull request by Regularitee**
In reference to MShock32 tileset.

### CODE REVIEW

**Comment by Regularitee** [comment]
Can someone help me figure out what the technobabble in the failed check log is trying to say? As far as I know, the change should delete an old .png file, and add a newer, larger one. The new one works with the game and has been in use for literally months by players, so isn't incompatible.

The only thing I can think of is that either the file was too large to upload (maybe incomplete/corrupted?), or the automated falsely flagged it as incompatible.

**Comment by Zireael07** [comment]
Technobabble says Jently timed out, @narc0tiq can you kick it back into gear?

**Comment by narc0tiq** [comment]
Done, it'll be rechecked soon. Jently also retests every time there's a new commit to master or to the PR itself. Technobabble actually says github took longer than 10 minutes to deliver the goods, which is rather sad.

**Comment by DangerNoodle** [comment]
I still would prefer the 24 version to be updated as well. The view zoom option does not actually suffice. At default zoom in the 32 version you do not get much of a view beyond your immediate area, but zooming out even one step loses a lot of detail. The default zoom level with the 24x24 version is at the ideal ratio of detail to vision range in my opinion, at least when the window is set to approximate 800x600 resolution.

**Comment by Regularitee** [comment]
If you really want it maintained, why not do it yourself, rather than trying to make others do it?

The reason I didn't touch the MShock24 version is because the tileset sprite numbers don't match up for whatever reason (I would have assumed they would have identical tiles, just in different sizes, but apparently it's not the case -- at least not in the copies I have). So to maintain Mshock24 I'd have to repeat the entire process of figuring out which sprites correspond to what number, rather than just simply copy and pasting everything.

Plus, this was a collaborative work with someone on the forum. So even if I wanted to do all that work a second time in a row, I'd have to somehow make the other guys do it  as well. And he's busy creating more additions for MShock32, so probably won't want drop his current work.

**Comment by DangerNoodle** [comment]
Alternatively, I have a better idea. I am looking into the zoom function in the source code, and might be able to implement a pull request to either add a less severe zoom multiplier/divisor before what is the current first step.

I have not been able to do much work as of late due to real life distractions, and I acknowledge that overhauling a tile set is a massive undertaking. My apologies for this.

**Comment by kevingranade** [comment]
this seems to have no contents, what's up?

**Comment by DangerNoodle** [comment]
Uncertain, and @CataJenkins is claiming a 404 error on attempting to examine the commit failure details.

**Comment by narc0tiq** [comment]
It looks like the diff is correct -- the file added in the second commit is identical to the one removed in the first commit. Not at all sure why Jently isn't trying to build the PR, but with no code changes, it's not really relevant anyway.

**Comment by kevingranade** [comment]
Nothing to merge, open a new PR if you have a change to merge.

**Pull request closed without merging**
