### PR TITLE
Add pthread back for sound support

### PR DESCRIPTION
**Pull request by remyroy**
This is a redo of #13984. I guess it was lost in some merge.

### CODE REVIEW

**Comment by narc0tiq** [comment]
Um, shouldn't `pkg-config --libs SDL2_mixer` include `-lpthread` when needed? It does for native builds on the Jenkins machine:

```
[narc@odin ~]% pkg-config --libs SDL2_mixer                                     
-lSDL2_mixer -lSDL2 -lpthread
[narc@odin ~]% mxe/usr/i686-w64-mingw32.static/bin/pkg-config --libs SDL2_mixer 
-lSDL2_mixer -lmingw32 -lSDL2main -lSDL2  -mwindows -lvorbisfile
```

Note the oddity of _not_ having `-lpthread` on the `i686-w64-mingw32` target, which still [builds perfectly fine](http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Tiles,Platform=Windows/). Of course, it also builds well with this PR in place (just tested both wintiles builds), so we could just do it anyway.

**Comment by remyroy** [comment]
> Um, shouldn't pkg-config --libs SDL2_mixer include -lpthread when needed?

It might but pthread is not a dependency inherent to SDL2_mixer. It is a dependency of our sound support. See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/sounds.cpp#L23

**Comment by narc0tiq** [comment]
Arr, comprendo, thank you.

**Comment by karlnp** [comment]
iirc pthread wasn't available in MSYS2 pacman at the time, but that was months ago.

**Comment by remyroy** [comment]
@karlnp This PR does not break MSYS2 as mentioned and tested in #13984.

**Comment by karlnp** [comment]
I was answering a question that didn't actually get asked. My bad.

**Pull request merged**
