### PR TITLE
Science ID cards as possible drop for zombies scientist

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary

`SUMMARY: Balance "Adds a Science ID card as possible loot for zombie scientists"`

#### Purpose of change

The Zombie scientist drop list doesn´t includes a Science ID card, even when the corpses of scientists in the map_extra_science does, and even the drop list of vault_wanderer (Shared among the Irradiated wanderers and the Charred nightmare) includes an ID card.

#### Describe the solution

I added id_science as a possible drop, with the same chance as in the Irradiated wanderers case and the zombie soldiers (With their military ID).

#### Describe alternatives you've considered

Leave the zombie scientists without a science ID card because they burned them all before turning into zombies (?)

#### Testing

Spawn several zombie scientists, kill them, see if some of them drop a science ID card, they do.

#### Additional context

This is my first PR, so I thought that changing something simple will be a great way to start. I read the code, found that these zombies doesn´t drop those IDs, so I decided to start with this

### CODE REVIEW

**Comment by Mister-Cultist** [comment]
makes sense, but does it mess with the balance of the lab start since most of the time you'd have to get to the lab end to escape?

**Comment by Zireael07** [comment]
It doesn't change lab starts in any way, it doesn't remove any of the existing sources of science cards. If anything, it makes lab starts easier since in addition to all other sources, you can now get a card from a scientist.

**Comment by Mister-Cultist** [comment]
That's what I mean, it makes the lab start a fair bit easier

**Comment by Termineitor244** [comment]
Well, as far as I know, the Lab start have always been "easy", at least for a "Challenge" that gives you 8 points...
And maybe it´s just me, but it seems pretty counterintuitive that the zombie scientist monster doesn´t has any possibility of dropping a science ID card, but the bodies of scientists smashed around a field, have a, well… I think **50 percent** of spawning an ID card per body…
I thought much about this change, whether to make it or not, but I think that the Lab start shouldn´t be about searching and obtaining an ID card at the bottom of that lab, specially if you are around a lot of previous scientist that, well, some of them should have their IDs with them… But rather have different difficulties that make more sense that “RNG Jesus decided to give me the technical books to make something to break the walls and escape” or “RNG Jesus allowed me to find an ID card at the bottom and I can now escape” it seems weird… Wrong if you ask me, a common "Entrance and Exit" ID shouldn´t just be laying around only at the bottom of a lab, surrounded by horrible and powerful monsters as bodyguards…
That´s what I think about the Lab start, but my main purpose to make this change was actually because of the people outside a Lab, the only ways to obtaining an ID card, without actually entering a lab, at the moment of the merge, were to find the Vault city and killing wanderers, or to find the Science special field (A lot of scientist bodies and maybe some horror creatures), but if you found a group of actual scientist zombies, it wouldn´t be possible to obtain it from them, it´s weird…
I decided to give them the **same possibility** to drop an ID card as the Wanderers and the Zombie soldiers, but I can reduce it if it breaks too much with the gameplay (I don´t know if that will even be accepted? Because of the realism vs gameplay thing), but I don´t think that the scientists shouldn´t have the possibility to drop one…

In related topics: I want to see how the game plays now and how common are now the IDs, and reduce the chance of the IDs in the Science special and maybe do something about the wanderers… Someone knows why they have that chance to drop an ID card? Were they all scientists?

**Pull request merged**
