### PR TITLE
WIP Byproduct for construction dig pit 

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
SUMMARY: Bugfixes "Dig pit Construction for NPCs leaves no materials"

#### Purpose of change
Recent faction camp improvements have included the ability to have NPCs perform construction tasks. Currently if you add zones to dig a pit and then command an NPC to complete construction activities they will dig the pits but there will be no material byproducts unlike when the ditch is ordered from the faction camp bulletin.

#### Describe the solution
Adds byproduct items to the dig pit construction activity.

#### Describe alternatives you've considered
I'm not positive that this bugfix is needed since "Dig Pit" is only visible to player's using the CRIT mod. However, I do think players should be able to request NPC's to dig pits.

#### Testing
Loaded world without CRIT mod, no "Dig Pit". Loaded world with CRIT mod.  Dig Pit available.  However, no byproducts created from construction of pit. 

#### Additional context
Seeking advice before any additional testing or json editing.  I'm not sure I understand why byproducts aren't being created but also should the player be able to request NPC's dig pits?

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
WIP in summary line?

**Comment by Maleclypse** [comment]
I put WIP because while I’m getting no errors on it, the fix isn’t working. Also I was hoping someone could speak to whether ‘dig pit’ should be a construction option for NPC followers at all?

**Comment by davidpwbrown** [comment]
you need to enclose the summary line in your PR text with ` ` like the example. so `"Dig pit Construction for NPCs leaves no materials"` 

I believe this isnt working because there actually isnt any C++ support for constructions creating byproducts at all.

you would have to look at the crafting code, how it loads the byproducts into the loaded craft recipe, load the same information into the construction recipe.
Then handle the creation of the byproducts when the construction is finished.

**Comment by Maleclypse** [comment]
> you need to enclose the summary line in your PR text with ` ` like the example. so `"Dig pit Construction for NPCs leaves no materials"`
> 
> I believe this isnt working because there actually isnt any C++ support for constructions creating byproducts at all.
> 
> you would have to look at the crafting code, how it loads the byproducts into the loaded craft recipe, load the same information into the construction recipe.
> Then handle the creation of the byproducts when the construction is finished.

Perfect.  Sorry I missed this reply last week.  I had assumed that the basecamp recipe trench used the construction code to create the trenches that create building materials.  I'll go ahead and close this then.

**Pull request closed without merging**
