### PR TITLE
[RDY] Linter rules update - 2

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# New rules (*with examples*):

- `body_part`;
- `effect_type`;
- `mutation`;
- `mutation_category`;
- `overlay_order`;
- `skill`.

# Updated rules (minor changes):

- `use_action`;
- `item`;
- `COMESTIBLE`;
- `GENERIC`;
- `harvest`;
- `scenario`.

The request is big (7.5k+ rows), but most of it are `json` from `/tools/format/examples/`.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs update to current master

**Comment by ZhilkinSerg** [comment]
Should be good now.

**Comment by Coolthulhu** [comment]
Do the examples need to be this huge? Are they like, copies of the files in question?

**Comment by ZhilkinSerg** [comment]
> Do the examples need to be this huge? Are they like, copies of the files in question?

I believe examples should include all (or most) of the json nodes which are supported by the linter. I can generate examples and replace them later in separate pull request after all of the linter rules are in.

**Pull request merged**
