### PR TITLE
Fix fake cbm items

### LINKED ISSUE #49793: Recipe Dictionary CTD
# Describe the bug

When trying to open the interact menu (default keybind '%'), game crashes

# Steps To Reproduce

1. Load provided save
2. Press %

# Expected behavior

Context menu for various inventory item interactions

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ef8144d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

 DEBUG    : invalid recipe id ""

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 65
 VERSION  : ef8144d

[My savefile](https://www.dropbox.com/s/jqjpkdmv6srv7ns/Olex.7z?dl=0)

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Bugfixes "Fix crash related to missing fake_item on CBMs"

#### Purpose of change
Fixes #49793.

The function that populates the pseudo_item list for crafting/activities is missing a check to make sure the fake_item id for each bionic is not empty. This causes a crash when trying to show the activities menu when one of the offending CBMs is installed.

#### Describe the solution
Added a check to make sure the id is valid before adding an item_id to the pseudo items list. This fixes the crash when CBMs without fake_items are installed.

After further analysis it seems that there is logic in place to make sure the fake_items are valid when set, so there is no need to use cata::optional. Just in case I added extra checks on load to warn when any bionics that are flagged as weapons/guns are missing its fake_item. Also added checks when activating gun or weapon CBMs to prevent crashes when the warnings are ignored for some reason.

#### Describe alternatives you've considered
Not adding warnings to the gun/weapon code.

Also considered removing the gun/weapon flags on bionic_data::check_bionic_consistency() so CBMs that aren't consistent don't register as weapons/guns and any further issues are avoided. This probably is the best approach as it deals with any possible crashes or inconsistent behavior (trying to activating a bionic that does nothing and throws a debug message) but since I can't see any correcting code in that function I decided against it. It seems to be purely checking, not fixing, so I added the guards in the relevant functions instead.

If that approach is preferred I can change it here or open a new PR.

#### Testing
Game doesn't crash when using the attached save in #49793
image

Game warns when a gun/weapon CBM is missing its fake_item:
```
 DEBUG    : Bionic bio_laser specified as gun or weapon bionic is missing its fake_item id

 FUNCTION : check_bionic_consistency
 FILE     : D:\Dev\Cataclysm-DDA\src\bionics.cpp
 LINE     : 432
 VERSION  : 0.F-600-g18c26a090b-dirty

```

When trying to use the inconsistent CBM:
 ```
DEBUG    : tried to activate gun bionic "bio_laser" with invalid fake_item ""

 FUNCTION : activate_bionic
 FILE     : D:\Dev\Cataclysm-DDA\src\bionics.cpp
 LINE     : 649
 VERSION  : 0.F-600-g18c26a090b-dirty

```

### CODE REVIEW

**Comment by GoLoT** [comment]
I just realized that this won't prevent crashes if a gun/weapon CBM defines an invalid fake_item. It's probably a good idea to start adding some correcting code to check_bionic_consistency() as right now if warnings are ignored on load it will lead to crashes under certain circumstances.

**Comment by anothersimulacrum** [comment]
In general, we should avoid crashes where we can.

**Comment by GoLoT** [comment]
So... I can either change is_empty() checks to is_valid() when activating the CBMs or simply set the fake_item to an empty ID in check_bionic_consistency(). The latter seems cleaner as there is no reason to keep a reference to an invalid item around.

I'll make the change, if there is a preferred alternative solution let me know.

**Comment by anothersimulacrum** [comment]
I think it would be a good change to make the fake item a `cata::optional` as you mentioned in the issue, then set it to `cata::nullopt` (and give a debugmsg) in `check_bionic_consistency()`.

**Comment by GoLoT** [comment]
I started doing that but it added a lot of complexity because there are multiple functions that would have to check that there is an optional value and then check the validity of that value. As it is, `itype_id (string_id<itype>)` is effectively acting as an optional as it has functions to check for emptiness, validity and null. The code already uses this to make sure item ids aren't empty in most places, leaving it out in `Character::get_pseudo_items()` was an oversight.

Now there is the issue that `bionic_data::get_all()` returns a const vector and its iterator returns const references. It isn't possible to change the bio.fake_item while iterating so any solutions would be very hacky.

**Comment by GoLoT** [comment]
I did some more testing and it turns out I missed a branch where it still crashed. Right now this should fix the crash from #49793 and prevent crashes when weapons aren't assigned a valid fake_item id.

I'll leave this PR as it is unless there is something that isn't working properly. Regarding the refactor to use cata::optional or fixing CBM inconsistencies in `bionic_data::check_bionic_consistency()`, we can open an issue to discuss the best approach and long-term solution.

**Comment by anothersimulacrum** [comment]
I am not particularly fond of using sentinels over optionals, but I won't make more noise in that direction if that is not the route you have chosen to take.

**Comment by GoLoT** [comment]
It's fine by me to make the change to use optional, I think it's a cleaner solution, but when I started making the changes it turns out there are multiple places that already implement logic using is_empty and is_valid. Replacing those instances is prone to create new issues and the change should be done properly.

I just want to push this out quickly as a fix for the crash so we have a working solution, the refactor can be done in a new PR with just the goal of refactoring. I think it should also include a way to "disable" some features of a CBM (i.e. remove the gun/weapon flags if the installed bionic isn't consistent with the requirements to be used as a weapon) if requirements aren't met to avoid crashes in the future.

**Pull request merged**
