### PR TITLE
Artifact procgen - artifacts that spawn use the new relic data

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Features "Artifact procgen - artifacts that spawn use the new relic data"```

#### Purpose of change
This is a very important/large part of the artifact rewrite project. It is the first PR that will directly affect players that play vanilla.

What it does is creates a new json object that lets you define the artifact attributes, and spawns in an artifact with a random selection of these attributes.

#### Describe the solution
Create a new json dataset that gives procgen rules for the various pieces of information (i refer to these as "attributes") that make an artifact "an artifact".

Currently, the only places that spawn these procgen artifacts are the places that spawned artifacts before, and those places have the following rules:
- 5 attributes max
- -2000 total power level among attributes max
- 1000 total power level

I'll go into more detail in the documentation as to what all that means

#### Testing
Used the debug option, which spawns an "alien_reality" type artifact (found near portals) and saw that it has some attributes. Currently there seems to be a bug where wielded artifacts double their attributes.

#### Additional context
Before we delete the old artifact code we need some kind of migration to use new stuff. There are a few things that need to be done still related to this - artifact charges, active artifact effects, and balancing the procgen data (which is entirely json)

### CODE REVIEW

**Comment by Axema** [comment]
Do you plan to fix this [issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/38409) too?

**Comment by I-am-Erk** [comment]
@Axema please keep posts on topic

**Comment by Axema** [comment]
@I-am-Erk I can't reopen an issue about this. And apologies for my mistake.

**Comment by EvgenijM86** [comment]
Are artifacts even in the game right now? I have yet to see even one spawn in like last 2 months. In previous versions you would usually find them in open fields, surrounded by debris.

**Comment by KorGgenT** [comment]
Honestly i'm not sure the "standard" ones are, the ones that spawn in a rocky meteorite crash. I didn't see any references to it in the code whatsoever, but the other places you can get artifacts do exist. It's out of scope for this PR, but i plan on figuring some extra places to inject artifacts once the migration is in progress

**Pull request merged**
