### PR TITLE
Fix NC_JUNK_SHOPKEEP item list.

### PR DESCRIPTION
**Pull request by TealcOneill**
#### Summary
None

#### Purpose of change
Many items in the misc items list of this file were needlessly added 2 to 4 times even. This was very confusing when I was working with it, so this should help prevent future contributors from becoming confused.

#### Describe the solution
 I kept the highest probability and highest charge version of each item and deleted the rest.

#### Describe alternatives you've considered
Leaving it as is.

#### Testing
Used the debug menu to test the item group several times before and after my change and made sure the averages on a small sample of items stayed relatively the same.

### CODE REVIEW

**Comment by actual-nh** [comment]
Title - spelling of "SHOPKEEP".

**Review by Maleclypse — APPROVED** [review]

**Comment by I-am-Erk** [comment]
Who is using this itemgroup? It is frankly pretty terrible. Why is it a distribution?

**Comment by TealcOneill** [comment]
> 
> 
> Who is using this itemgroup? It is frankly pretty terrible. Why is it a distribution?
https://github.com/CleverRaven/Cataclysm-DDA/blob/db4d92a5230edaef1af6fe1ceaf5d5845359e8b1/data/json/npcs/classes.json
The NC_JUNK_SHOPKEEP from this file is the only one I see. I have no clue on the how's and why's of it, I just noticed it was weird because I was adding my new item in anywhere you could find the one I based it on.

**Comment by I-am-Erk** [comment]
I'm not sure it's being used anywhere at this point.

**Comment by I-am-Erk** [comment]
Ah found it. This is the junk shopkeep at the Tacoma Ranch. I'm willing to wager their inventory is absolutely crap... this itemgroup should be a collection, not a distribution. As it stands they only spawn with a single item to sell from this list.

**Comment by actual-nh** [comment]
> Ah found it. This is the junk shopkeep at the Tacoma Ranch. I'm willing to wager their inventory is absolutely crap... this itemgroup should be a collection, not a distribution. As it stands they only spawn with a single item to sell from this list.

I have previously suggested that there should be a way to specify, when using an itemgroup, which one it should be (having been caught by this myself, the other way around).

**Comment by ZhilkinSerg** [comment]
Are we merging this before proper group change?

**Pull request merged**
