### PR TITLE
[RDY] Changed welding goggles recepie  skill requirement  after discussion with players

### PR DESCRIPTION
**Pull request by Firestorm01X2**
After discussion enough players pointed that mechanics skill requirement for welding goggles recipe should be changed from mechanics 3 to fabrication 3.

Here is poll on the official forum:
http://smf.cataclysmdda.com/index.php?topic=13404.0

Here is discussion:
https://github.com/CleverRaven/Cataclysm-DDA/issues/18641

Best explanation given is:

> Using tailoring for what is not, fundamentally, a piece of clothing, is wrong, that much I agree with.
> However tying Mechanics into making welding goggles, is just as wrong - there is nothing even remotely mechanical about them. You can't just tie welding goggles to a crude welder by required skill.
> 
> In that sense, fabrication is definitely the way to go for crafting the goggles. Now for autolearn, yes, you could make a case for the mechanics skill. Even then, though, I see fabrication being just as likely a candidate.
> 
> And once you've arrived at the skill you're targeting, you need to look at what items are craftable at what level within that skill. The mechanics level needed to craft the crude welder has no relation to the complexity of the goggles. Swimming goggles, the sort that require a bit more effort to stay watertight, require Fabrication 4, in a recipe with a similar premise (convert a different kind of goggles). With that in mind, Fabrication 3 seems fair.
> 
> So I'll cast that as my vote, then. Fabrication 3. It makes sense in general, and you do learn the recipe from a book on Fabrication.

Reasons to change:
- Mechanics do not directly related to crafting welding googles. Recepie itself mostly looks like tinkering not mechanics. So fabrication is way to go.
- We have example of swimming goggles recipe that uses same template for skill requirement

### CODE REVIEW

**Comment by pisskop** [comment]
I can approve of this.  Less concentration of skills for the sake of streamlining the game

**Comment by John-Candlebury** [comment]
Fabrication 3 is probably rather high for doing what amounts to spray painting a pair of goggles. Think it'll make more sense to reduce it to fabrication 2 or even better 1. 

It's not like grinding for fabrication 3 was particularly hard anyways. It simply consumes a lot of player time. Ideally we would keep it mechanics 3 and entirely remove the need for grinding fabrication.

**Comment by SeanMirrsen** [comment]
>Fabrication 3 is probably rather high for doing what amounts to spray painting a pair of goggles. Think it'll make more sense to reduce it to fabrication 2 or even better 1.
>
>It's not like grinding for fabrication 3 was particularly hard anyways. It simply consumes a lot of player time. Ideally we would keep it mechanics 3 and entirely remove the need for grinding fabrication.

It *was* Tailoring 4. It was changed to Mechanics 3 recently. But if it made little sense to use Tailoring, it makes just as little sense to use Mechanics. Especially when the recipe is learned from a book on Fabrication.

And it needs to be Fabrication 3 because a similar recipe, to create swimming goggles, is Fabrication 4. You are not, presumably, just coating existing goggles with paint - and even then you'd need a fine control over how much paint you use and how thin a layer you put down, so as not to get goggles that are uselessly opaque or insufficiently protective.

**Comment by Firestorm01X2** [comment]
Actually you can this recepie from mechanics 3 book if I am not mistaken. My vote was mechanics 3 and fabrication 1.

**Comment by John-Candlebury** [comment]
> It was Tailoring 4. It was changed to Mechanics 3 recently. But if it made little sense to use Tailoring, it makes just as little sense to use Mechanics. Especially when the recipe is learned from a book on Fabrication.

Indeed it was tailoring 4, but the change was approved for several reasons, one of which was exactly: "not having to grind two skills to use mechanics to its full capacity."
I fail to see how this is significant

>And it needs to be Fabrication 3 because a similar recipe, to create swimming goggles, is Fabrication 4. You are not, presumably, just coating existing goggles with paint - and even then you'd need a fine control over how much paint you use and how thin a layer you put down, so as not to get goggles that are uselessly opaque or insufficiently protective.

The game play caused by recipes is more important than "logical" consistency between them.  Making a fabrication grind necessary build welding googles just because swimming goggles require 4 fabrication seems like a bad reason. Especially so because it forces a player to powerlevel a skill they might conceivably have no other use for.

Plus welding knowledge is also tied to the mechanics skill, so its not senseless to assume that some level of welding knowledge is necessary to know how much paint is sufficient protection.

**Comment by Firestorm01X2** [comment]
Almost my thoughts. Mechanics 2 and fabrication 1 maybe ideal. Crude welder also should something insted mechanics by that logic.

**Comment by Firestorm01X2** [comment]
Sean's point logical too. But I prefer less grinding to acess full welding kit.

**Comment by SeanMirrsen** [comment]
>The game play caused by recipes is more important than "logical" consistency between them. Making a fabrication grind necessary build welding googles just because swimming goggles require 4 fabrication seems like a bad reason. Especially so because it forces a player to powerlevel a skill they might conceivably have no other use for.

That's wrong. There is a tradeoff to be had between gameplay and realism, but a survival/scavenging game is not the place to streamline such things. The entire point of a survival situation is the game forcing you to do things as best as you can, and the different skills are there to create those situations where you don't always have exactly what you need to progress.

I am entirely against streamlining what is supposed to be, in principle, a quasi-realistic survival game, into lanes cut out by the needs of raw gameplay. If it were up to me, you would not be able to make any items without at least some levels in Fabrication, because that's what the damn skill is for. Tailoring is to make things that have to fit your body comfortably, Mechanics is to make things with moving and interacting parts, Electronics is to make wiring and circuits, and Fabrication is the "general" skill for making things. Welding goggles don't need to be worn constantly, they have no parts or electronics, therefore they are straight-up Fabrication, and that's that.

**Comment by pisskop** [comment]
reqqing fab to make a fabrication is not a bad thing.

its not mechanics to make a weldermask.  nor is it required you craft one.  theyre prettu common.  labs are almost guaranteed to have multiple copies.  zombies drop them.  public works regularlu spawn them.

its not the crafting systems job to hand people convenient recipes, its there to provide an alternative if you dont play in cities.  but then again, where did you get a welder without electronics skill?

**Comment by Firestorm01X2** [comment]
> where did you get a welder without electronics skill?
Exaclty

It all not as in real life

So we have here realism vs gameplay. 
* From point of IRL fabrication is way to go
* From gamepelay wise it is kinda not logical that you need separate skils to craft full welding kit. The point is that welding google not usable without welder or welder not usable without glasses. It is part of one logical thing.

I said already that ductaping was heavily nerfed. So you basically can't repair cars without welder at all.

**Comment by mugling** [comment]
> If there was ductaping at least for some things like fixing leaking fuel tank.

That should be opened as an issue

> From gamepelay wise it is kinda not logical that you need separate skils to craft full welding kit for mechanics duty. The point is that welding google not usable without welder or welder not usable without glasses. It is part of one logical thing - car repairing.

Well gameplay is more important than realism by far.

**Comment by Firestorm01X2** [comment]
Perhaps compromise solution should be set then:
* We should use template of night vision googles- many levels in specialized skill and mior in reqired skill
* We still should use fabrication.

For that I recommend Mechanics 2 and fabrication 1. Or mechanics 2 and fabrication 2. In this way wannabe mechanic get access for repair tools much faster. We still has mehcanins requirment, extra tools reqirment and other, that prevenst full repair on mechanins 2.

**Comment by mugling** [comment]
MECH 2 and FAB 2 would be reasnoable

**Comment by Firestorm01X2** [comment]
Taking this as compromise solution,

**Comment by mugling** [comment]
Gentle bump - I updated my post, my bad

**Comment by Firestorm01X2** [comment]
Done. Changed. to MEC 2 FAB 1

**Comment by mugling** [comment]
It's impossible to keep everyone happy here. If the welding goggles are FAB3 that makes vehicle repairs even more difficult in the early game and that's a big problem.

**Comment by Firestorm01X2** [comment]
Formatting fixed.

**Comment by SeanMirrsen** [comment]
>It's impossible to keep everyone happy here. If the welding goggles are FAB3 that makes vehicle repairs even more difficult in the early game and that's a big problem.

How is it a problem? How is not having even more easy ways to have a working vehicle (aka mobile safe haven) before you have the barest necessary skills to survive even remotely a problem? Am I the only one finding the actual survival and scavenging parts of the game interesting?

**Comment by mugling** [comment]
Like I said there are those complaining exactly the opposite - that vehicle repairs are becoming too difficult. I'm leaning towards giving those people preference as vehicle repairs actually have become more difficult.

You already need to scavenge a spray can to make the goggles. Adding a skill block is questionable from a gameplay POV.

**Comment by SeanMirrsen** [comment]
Again, any level of just fabrication is better than any requirement variant with any level of mechanics.

And really, level 3 is not a "block" by any means. Level 3 fabrication is pretty easily acquired. Apparently the ones complaining just like to have a working vehicle within the first two days, which in my mind is not a pace you should aim for with the game.

**Comment by Firestorm01X2** [comment]
>Like I said there are those complaining exactly the opposite - that vehicle repairs are becoming too difficult. I'm leaning towards giving those people preference as vehicle repairs actually have become more difficult.

Actually here  only I refers indirectly about  diffcult repair. Maybe someone else think difefernt. 

But after removing repair with ductape, adding jacks, increasing repair time it becoming obvious (I think).

**Comment by mugling** [comment]
> Apparently the ones complaining just like to have a working vehicle within the first two days, which in my mind is not a pace you should aim for with the game.

Whilst I would agree I'd like to add depth to the gameplay as opposed to arbitrary limitations. As I said it's difficult to keep everyone happy and your proposed change disproportionately affects those users whilst providing those with your view with much less gain.

**Comment by Firestorm01X2** [comment]
>And on top of that, you still insist on the bloody Mechanics skill. Just Fab 1 is better than Fab 1 Mec 2. Because at least it makes a whiff of sense.

What wrong if mechanic know how to work his tools and can using tinkering improvise his tool? And yes no one abandon fabrication now. Recepie will use it.

**Comment by SeanMirrsen** [comment]
>Whilst I would agree I'd like to add depth to the gameplay as opposed to arbitrary limitations. As I said it's difficult to keep everyone happy and your proposed change disproportionately affects those users whilst providing those with your view with much less gain.

If you want to add depth to gameplay, allow welding sans goggles, at a penalty. Blindcraftng is a thing, no? You are trying to plug holes in the system that don't exist. It makes internal sense to have welding goggles' construction based off a slightly elevated (3 is not even mid-level) skill level, and the problem you're describing would be much better solved by other means.

**Comment by mugling** [comment]
It's impossible to keep both those groups happy. `FAB 3` is more harmful to one viewpoint than `MECH 3` or even better `MECH 2 FAB 1`

**Comment by SeanMirrsen** [comment]
>It's impossible to keep both those groups happy. FAB 3 is more harmful to one viewpoint than MECH 3 or even better MECH 2 FAB 1

Again, why not just `FAB 1` then? Any level of `MECH` hurts the other viewpoint.

**Comment by pisskop** [comment]
ftr my vote is fab2.

easy to achieve and enough to encourage taking a point in fab if its really that important.

and shoulder straps are fab1, so you have an easy gateway

**Comment by mugling** [comment]
`FAB 1`? It's literally just spraying the contents of a can onto some safety glasses

**Comment by SeanMirrsen** [comment]
>FAB 1? It's literally just spraying the contents of a can onto some safety glasses

Maybe remove the duct tape from the recipe then as well? I recall that there was duct tape in that recipe.

**Comment by Firestorm01X2** [comment]
>FAB 1? It's literally just spraying the contents of a can onto some safety glasses

Actualy it is harder than that:
http://www.doityourself.com/stry/how-to-build-your-own-welding-goggles

**Comment by Firestorm01X2** [comment]
Actualy we may go for 2 different recepies
1) MEC 2 + FAB 2
2) FAB 3
But I bet that in this case  only first will be used most of the time.

**Comment by pisskop** [comment]
:|

thats like saying a worker in a factory producing guns needs gun1 to make a piece.

the items use need not have any bearing on its reqs. knowing how to use the item in this case is a matter of course.

players cant reliably grind welder googles due to limited resources nor will they be making one until it is needed.  crafting weldergoogles for any other purpose, including to use as armor, is pointless and detrimental due to its high encumbrance and the superiority of safety googles

**Comment by mugling** [comment]
Grinding is never an argument for anything.

Adding an arbitrary block on vehicle repairs is bad gameplay

**Comment by pisskop** [comment]
its not a block.

fab1 and 2 are hands down the easiest skills to gain.  the recipe is not mechanical in nature and crafting it inofitself should not grantmechanical insight.

fab, otoh, is exactly what this is.  painting in cdda is fab

**Comment by John-Candlebury** [comment]
Mechanics 3 is much more difficult to attain than fabrication 3.
Mechanics requires either  finding a book. or an inefficient grind with lockpicks until level 1 and then finding both a wrench and a hacksaw.  These three options require the player to risk a usually deep city raid.

Fabrication 3 on the other hand requires just smashing the evac shelter and a lot of player keypresses. Y

Once a player has the suficient skill and the items necessary to weld a car, obtaining fabrication 3 is just a matter of pressing repeat craft for ten minutes. This adds no extra difficult to making a car, it just demands more player time.

And since spray painting goggles is not a hard thing to do by itself I think its unnecessary to add the grind.

**Comment by SeanMirrsen** [comment]
>And since spray painting goggles is not a hard thing to do by itself I think its unnecessary to add the grind.

Again, it's not "just" spraypainting goggles. And even if you see it as such, there is no need for the mechanics skill in the process. Even on top of everything else, making the welding gear is already gated behind Mechanics for the crude welder, which I approve of since it's more of a "mechanics and large-scale electrics" that goes into maintaining a car. 

However welding goggles are not used exclusively for car maintenance, and a character not skilled in mechanics should not be expected to learn mechanics just for the sake of welding goggles. It is, as you said, unnecessary to add the grind.

And I will preemptively counter-argument the "you will learn Mechanics anyway for other purposes" with the same thing said for Fabrication - you will be making metal sheets, frames, metal tanks, and rather a lot of other things that are functionally Fabrication when constructing your own vehicle. You literally can't be making a vehicle without getting to `FAB 2` just from the steel frames. And good luck making wheels.

**Comment by John-Candlebury** [comment]
>However welding goggles are not used exclusively for car maintenance, and a character not skilled in mechanics should not be expected to learn mechanics just for the sake of welding goggles. It is, as you said, unnecessary to add the grind.

Then you can propose a recipe that only needs fabrication.

>And I will preemptively counter-argument the "you will learn Mechanics anyway for other purposes" with the same thing said for Fabrication - you will be making metal sheets, frames, metal tanks, and rather a lot of other things that are functionally Fabrication when constructing your own vehicle. You literally can't be making a vehicle without getting to FAB 2 just from the steel frames. And good luck making wheels.

This is not really true, I've been playing the game for three years, and not once have I had the need to craft frames or other car piece, besides the rv kitchen unit, which uses mechanics.  After all, you can scavenge everything for much less effort.

**Comment by SeanMirrsen** [comment]
>Then you can propose a recipe that only needs fabrication.

I did propose to make the recipe purely Fabrication. That's what this PR was about in the first place. The current recipe has nothing that would require Mechanics in any way already.

>This is not really true, I've been playing the game for three years, and not once have I had the need to craft frames or other car piece, besides the rv kitchen unit, which uses mechanics. After all, you can scavenge everything for much less effort. 

Again, different playstyles. When I go for making vehicles from scratch I start with wooden ones because materials and tools are more easily available. And that requires fabrication. If hacksaws become a finite tool later on, since they do erode with use IRL, this will be even more prominent.

Also cargo carriers require fabrication. I'm sure pretty much any components that aren't interactive in nature require fabrication.

And to be honest... if car construction were implemented properly, fabrication would be the second primary skill for it. Installing windows, welding together frames and panels, setting up cargo space, is all straightforward construction tasks. Not mechanics or electrics. You'd still need mechanics for everything else - wheels, doors, engines, drivetrain, electrics, controls, craftstation stuff. But there's no mechanics skill necessary in welding a spike to the car's bumper or making a roof that doesn't let rain through.

**Comment by mugling** [comment]
All this said, requiring fabrication actively harms a proportion of the playerbase. There isn't an upside to justify that

**Comment by SeanMirrsen** [comment]
>All this said, requiring fabrication actively harms a proportion of the playerbase. There isn't an upside to justify that

So does requiring Mechanics. And it's less "actively harms" and more "mildly inconveniences", seeing as how the two skills are both required in car construction.

**Comment by pisskop** [comment]
Indeed.

Screwdrivers dont require 2 electronics.
Sword-crafting doesnt require 4 cutting
Hammers dont require bashing skill.
Digging sticks dont need construction.

If anything, the arguement here is to add mechanics as a secondary in addition to the rightful req of fabrication to _fabricate_ a welder google.

**Comment by Firestorm01X2** [comment]
So FAB 2 + MEC 1 then?
Current values for this PR is MEC 2 + FAB 1

**Comment by Firestorm01X2** [comment]
Ok Here is 3 variants:
1) MEC 2 + FAB 1 <<<currently on PR
2) FAB 2
3) FAB 2 + MEC 1

Now we just need developer to finally select one of them. 2 or 3 Mostly suits everyone.

**Comment by SeanMirrsen** [comment]
Aand it was merged with the Mechanics 2 requirement... for crying out loud. -_-

Waiting for take three...

**Comment by pisskop** [comment]
2fab 2mech is fine.

dont sweat small things

**Comment by SeanMirrsen** [comment]
It's the principle of the thing.

This item should not have a Mechanics requirement. And making it should definitely not train Mechanics skill. The whole argument that it is meant to go with a Mechanics-based tool falls apart if you consider that the item by itself is useless without that tool - you can't use the goggles without the welder, or the welder without the goggles. The *pair* of items required for welding, is already gated behind the Mechanics skill for the welder, there is no need to tack Mechanics on to a completely non-mechanical piece of gear.

Like I said before. You (meaning... primarily mugling, I suppose?) don't want a meaningful Fabrication level requirement? Screw it. *Fine.* `FAB 1` will hurt nobody. But leave Mechanics out of it. *Tailoring* was better than Mechanics - it at least made sense because goggles are an item you *wear*. Combining Fabrication and Mechanics is literally the worst of all worlds.

**Comment by mugling** [comment]
> It's the principle of the thing.

I'm only interested in pragmatism and progress. OP had an open PR that was an improvement to the project so it was merged. Try and keep principles out of matters that are not of paramount importance.

**Comment by SeanMirrsen** [comment]
OP **had** an open PR that was an improvement to the project.

Then you came in and changed that.

**Comment by mugling** [comment]
The change in #18635 was reasonable and this PR provides a further compromise. You're arguments are overly verbose and are consuming too much time considering the low significance.
 
> dont sweat small things

See above, it's good advice

**Comment by SeanMirrsen** [comment]
>The change in #18635 was reasonable and this PR provides a further compromise.

No it was not, and no it does not.
This PR came about exactly because the change in #18635 was poorly thought through, and this PR itself had been sabotaged, for lack of a better description.

I see neither pragmatism nor progress in the change you merged. You yourself said that adding Fabrication requirement hurts the Mechanics-using portion of people who were complaining that they can't get to making cars quickly enough. At the same time this PR was driven in part by the change to Mechanics hurting people who *don't* go for the cars immediately and focus on crafting instead (but still mostly because, seriously, you're using Mechanics to spray paint over goggles).

The change you merged does not resolve the original issue, and further hurts a (already allegedly suffering) part of the playerbase. How is any part of this a benefit?

**Comment by illi-kun** [comment]
@SeanMirrsen I support you here.

I said ```FAB 3``` initially because of MECH requirement is auto-completed condition since you need it anyway for your wielding activity. If ```FAB 3``` is too difficult to obtain, ```FAB 2``` should be quite good. The ```MECH``` requirement adds nothing useful here and looks really weird.

**Comment by mugling** [comment]
> There is a point where I refuse to not sweat the small things. They accumulate and drive me away from the game because at some point I just cannot look past them when I play.

We can't go from trivial to nuclear over small issues. I merged the original PR because it was a reasonable suggestion. That lead to a wall-of-text.

> FAB 2 should be quite good. The MECH requirement adds nothing useful here and looks really weird.

The vehicle installation requirements are in flux at the moment so it's difficult to balance anything around that. I'm wary of making working on vehicles harder until we have that issue more resolved - recent vehicle repair PR's have helped but it still definitely needs more thought.

There probably isn't a perfect answer for now and that in itself is ok

**Comment by Coolthulhu** [comment]
Fabrication below 4 isn't really a requirement, those are all trivial.
At the point you need to weld anything, fabrication 3 and 0 are equivalent.

**Comment by mugling** [comment]
Tangentially, fabrication does have poor distribution of recipes with most of the useful ones clustered in the first few levels

**Pull request merged**
