### PR TITLE
Add var_norm field to widgets for normal value

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Features "Add var_norm field to widgets for normal value"
 

#### Purpose of change

Some `widget_var` variables have a concept of a normal or baseline value, below which it might be colored red, and above which it might be colored green - the basic STR/DEX/INT/PER stats for example. But we only have `var_min` and `var_max`, with no way to specify a widget variable's "normal" value.

#### Describe the solution

- [x] Add documentation first
- [x] Add a `var_norm` widget field, to set it to an explicit value
- [x] Add a `widget._var_norm` member variable to the widget class, where it's stored
- [x] Add a `widget::get_var_norm( avatar )` function that returns a default `_var_norm` value for the given avatar (for example, from their base STR)
- [x] Add a `widget::set_default_var_range()` function that populates min, norm, and max from defaults (or JSON overrides)
- [x] Simplify existing functions to use member variables instead of arguments
- [ ] Change the stats widgets to be red below norm, green above norm, and white at norm
- [ ] Test cases

#### Describe alternatives you've considered

WIP

#### Additional context

~~Needs work, just getting the first draft up~~

Superseded by #54754

### CODE REVIEW

**Comment by PatrikLundell** [comment]
It's probably simple for stats (simple logic, but not necessarily trivial implementation): Expected value = normal, higher = above, lower = below, but it gets more complicated when "normal" is a range, such as for weight.

**Comment by wapcaplet** [comment]
I am taking the plunge and working toward *removing* the "var_max" (and what few "var_min" there are) from JSON widgets, and making these fields (as well as the new var_norm range) hard-coded only. After thinking about it, I don't see a compelling reason for these to be customizable in JSON - most of the time, the widget class can infer a reasonable min, max, and normal range; much of the time, they are in fact variable, and should be updated as the avatar's stats change - indeed allowing these to be overridden with a fixed JSON value could lead to all kinds of weirdness and unnecessary complexity.

So now it will be up to the widget class to set these fields internally upon each call to `layout()`.

**Comment by wapcaplet** [comment]
I'm still stabbing at this periodically, and am beginning to make it bleed now...

**Comment by wapcaplet** [comment]
This has veered pretty far from its original purpose, to a total overhaul of the widget min/max variable system. I will most likely close this and start a new, cleaner PR with freshly rebased/squashed commits.

**Pull request closed without merging**
