### PR TITLE
Adds the H&K Mp5sd

### PR DESCRIPTION
**Pull request by hyper2snyper**
#### Summary
Adds the H&K mp5sd, a silenced smg with integrated suppressor.

#### Additional context
https://www.heckler-koch.com/en/products/military/submachine-guns/mp5/mp5sd/overview.html

### CODE REVIEW

**Comment by hyper2snyper** [comment]
wait, how do i delete this?

**Comment by Pupsi-Mupsi** [comment]
Just click on **close pull request** down below.
grafik

**Comment by Pupsi-Mupsi** [comment]
You're welcome!

**Comment by hyper2snyper** [comment]
Thanks

**Pull request closed without merging**
