### PR TITLE
Craftable Minifreezer and Minifridge and Washing machine

### LINKED ISSUE #26489: Add recipes for Vehicle Minifridge, Minifreezer and Washing Machine
**Is your feature request related to a problem? Please describe.**  
It's possible to make all sorts of vehicle parts welding rigs, forges, UPS recharging stations, FoodCo's, kitchen units ect.  However no such recipes seem to exist for the Minifridge, Minifreezer and Washing Machine.  Both the Minifreezer and Washing Machine seem to be rather rare which makes it difficult to get them.

**Describe the solution you'd like**  
I would like to see recipes added for the Minifridge, Minifreezer and Washing machine so they can be built from spare parts.

**Describe alternatives you've considered**  
Adding these vehicle parts to RV's and other such vehicles to increase their commonality could make them easier to acquire.

**Additional context**  
From what I understand adding a few recipes should only require some simple JSON editing.  I've played around doing xml editing for Rimworld so I wouldn't be against trying to do this myself and making a pull request.  However I'm not knowledgeable enough to suggest crafting requirements and I have yet to ever use Github in such a capacity.

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Content "adds items and recipes for minifreezer/minifridge/washing machine and component parts."```
#### Purpose of change

Fixes #26489 
#### Describe the solution

Adds recipes for Minifreezer and Minifridge,
also adds new items and recipes for them: compressor coil and evaporator coil
adds recipe for washing machine
#### Additional context

Below are some references I used:
https://www.doityourself.com/stry/troubleshooting-a-chest-freezer-that-runs-continuously
https://yourairexperts.com/article/what-are-evaporator-and-condenser-coils-and-how-do-they-help-cool-your-home
https://www.air-conditioning-and-refrigeration.com/Refrigerator-components.html

borrowed recipe of washing machine from @FulcrumA

### CODE REVIEW

**Comment by FrozenSnowFox** [comment]
Just for reference there's another PR that was intending to do the same thing [#26702](https://github.com/CleverRaven/Cataclysm-DDA/pull/26702).  Although it looks like you've researched the topic more thoroughly.

**Comment by KorGgenT** [comment]
> Just for reference there's another PR that was intending to do the same thing [#26702](https://github.com/CleverRaven/Cataclysm-DDA/pull/26702) but handling things differently.

woops. i thought i glanced over all the open PRs, but I guess i missed this.

**Comment by FrozenSnowFox** [comment]
You might want to check over it though because I think yours might handle it better.  It seems you researched the subject and added specific parts while the other PR adds a generic coolant tank.  The work is already done so whichever of the two handles it better should be the one added.

**Comment by KorGgenT** [comment]
I suppose that is true. I did not want to step on any toes, and i also did not include the washing machine recipe here.

**Comment by Vasyan2006** [comment]
Are you sure it is possible to craft condensers and evaporators without industrial machinery? You propose just another generic "craft everything from scrap iron if you have a welder and a hammer" recepies. 
In addition, builded from scratch minifreezer will not work if you dont have above average understanding in forbidden dark arts of thermodynamics. It is not purely mechanical system and it not possible to learn how to tinker it just by watching its operations.  

There are a LOT of coolers and freezers in working condition in every town. Easiest way to use them in a vehicle is to buy DC to AC power inverter. Ask at your local electronics store. 
I think most logical and easiest way to find a cooler or wash machine is to use existed one, so this furniture must be somehow transformed into vehicle parts. Maybe add two different house fridges: one is XXL size and is too big, another one is rather small and can be installed on every motorbike.

**Comment by KorGgenT** [comment]
As far as "an above average understanding of _" is concerned, I believe that is at least heavily implied in the skill requirements and books necessary. You don't *just* watch its operations from a book recipe in this game, it implies that it gives you the whole host of calculations to actually craft it.

These recipes are my response to the large problem of RNG just giving you a bad run of luck. Going 3-4 weeks IRL time without seeing a single Ice Cream Truck, that being your only current option.

**Comment by FulcrumA** [comment]
@KorGgenT 
>I suppose that is true. I did not want to step on any toes, and i also did not include the washing machine recipe here.

What the hell, you disrespect me and my work by adding this when I worked already on minifridge. You think Acidia was angry when someone butt into his work? Well, I will grab a hatchet and...

Nah, kidding. Your take on it is interesting, though I recall refrigerant being kinda important for Kevin, thus addition of the hermetic tank on my part without simplifying it to just ammonia, so some reviewer will have to comment there. Either way, don't worry, if said reviewers will prefer your take on this thing, you have my blessing and reassurances of no offence on my part, especially given that my PR is still for some reason in a limbo with no one telling me to either change anything further or pushing it through. If we'd go with your work I'd appreciate it if you'd do the washing machine as well though so I can safely close my PR.

**Comment by KorGgenT** [comment]
added washing machine from #26702 @FulcrumA

**Comment by Night-Pryanik** [comment]
Rename your PR and update the OP to reflect the changes.

Considering crafting washing machine: doesn't its drum required to be perfectly round so the washing machine can spin and don't destroy yourself whilst washing? Is it possible for the survivor alone to create such a thing?

**Comment by KorGgenT** [comment]
[according to the wikipedia,](https://en.wikipedia.org/wiki/Washing_machine#Washing_by_machine) the rotary washing machine was patented in 1858.  This by itself tells me a lot about a how a near-future survivor can create the drum of such a machine. I have not been able to find the answer to your question of if it needs to be perfectly round in order to work though.

**Comment by I-am-Erk** [comment]
There's certainly no shortage of fridges around to be disassembled for coolant. That sounds cool.

Oh gawd. Sorry, I didn't intend that pun.

**Comment by kevingranade** [comment]
I'm going to go ahead and merge, but, shouldn't the recipe have insulation?  Like a ton of it.

**Comment by FulcrumA** [comment]
@kevingranade 
In my take on it I've included some of the parts of fridge furniture as well as make new parts required by the recipe drop from the furniture. Would that additional metal and whatnot cover insulation should @KorGgenT consider similar changes here?

**Comment by KorGgenT** [comment]
The reason I added the plastic chunks is that i was thinking about a "plastic" insulation. Usually it's polyurethane, but we don't really have anything very close to that other than "plastic chunk"

**Comment by gc2020x4** [comment]
@kevingranade @KorGgenT 
Kevin Grenade must leave the project forever.

**Pull request merged**
