### PR TITLE
[CR] Conservative Apartment Tower JSONification (with save file conversion)

### PR DESCRIPTION
**Pull request by vickio**
In an effort to learn how mapgen works, I've begun chipping away at `map::draw_map` by converting the conservative apartment tower to JSON. This will make it easier to create some variations of the building and also easier to add z-levels. For now, I kept everything the same except monster spawning (described below).

Some questions:

**1.** It seems like there are a lot of ways to do the same thing in JSON when it comes to item and monster placement. Does what I've done here look ok? Any style or naming advice?

**2.** I tried to balance monster spawning to be more like normal houses but with `"repeat": 2` since each quadrant holds two apartment units. My reading of the original code is that it spawned 1-8 normal zombies in each quadrant regardless of the world's difficulty settings and of the building's proximity to city center? Mine uses this JSON instead for each tile:

```
"place_monsters": [
    { "monster": "GROUP_ZOMBIE", "x": [ 4, 23 ], "y": [ 2, 23 ], "repeat": [1, 2] }
]
```

In my testing, this lead to more varied play, usually spawning fewer, but more powerful zombies than the original. I could use some input on the balance though.

**3.** Will this change break saves by removing the old generation code which used `overmap_terrain.json` ids that couldn't be seamlessly migrated to JSON?

**4.** Would it be helpful if I convert more of the simple buildings in `map::draw_map` to JSON? Or is this unnecessary work?

### CODE REVIEW

**Comment by BevapDin** [comment]
> Will this change break saves by removing the old generation code which used  overmap_terrain.json  ids that couldn't be seamlessly migrated to JSON?

Yes, this will break saves. The Rule is to never change the id of anything after it has been added to the game. The saves contain that id and loading them will break when the game can not find the object that the id refers to.

(One could add a translation to the loading code that translates old ids to new ids, but this is more work.)

> Would it be helpful if I convert more of the simple buildings in  map::draw_map  to JSON? Or is this unnecessary work?

Yes. There should be as few as possible hard coded mapgens. Ideally, all mapgens would be done via JSON. JSON is much easier to edit and does not require (re-)compiling the game.

----

Oh, I see your problem now: the current mapgen in C++ uses the surrounding terrain to determine what to generate. To make this suitable for JSON, you (or somebody) will have to add some translation to the loading of the overmap terrains (src/savegame.cpp and src/savegame_legacy.cpp).

**Comment by vickio** [comment]
Here's my attempt at the save file translations for the changed overmap terrain ids. I created `overmap::convert_terrain` to handle it. Not sure if this is the best approach, but I have tested loading both legacy and modern save files, and the terrain id conversion is working properly.

**Comment by vickio** [comment]
I started looking at what it will take to convert more hard coded buildings to JSON and found that many of them use the same id pattern as these apartments and will require new overmap terrain ids with custom save file translation code. I just pushed a change that makes the conversion code more structured so it should be easier to add more conversions down the line. Tested with both legacy and modern save files at various rotations. If this gets merged I'm prepared to begin converting many more of them.

**Comment by BevapDin** [comment]
Looks fine, works fine, a few style (= subjective) issues:
- The parameter to `convert_terrain` should be a const reference (it's not changed by the function).
- The map in `obsolete_terrain` should be static (it is currently re-created on each function call).
- The range based for loops should use (const) references into the container, if possible (here it is): `for( const auto &conv : near )`

**Comment by vickio** [comment]
Thanks! I'll improve the style with the next PR I submit that uses those functions.

**Pull request merged**
