### PR TITLE
Hatchet blocking and storage

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Features "Added blocking to hatchet and compatibility with firefighter belt"```

#### Purpose of change
Made the hatchet big enough to be stored in a firefighter belt and added medium blocking ability to it. It was 0,5 liter in volume (which is too small anyway).
All kinds of improvised weapons have the medium blocking ability (plank, pipe, broom, etc.), so adding it to the hatchet is a reasonable thing.

#### Describe the solution
- Changing the hatchet volume to 1 liter so it fits into the firefighter belt.
- Adding the wblock_1 technique to it.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Featured - > Feature

**Comment by RarkGrames** [comment]
> 
> 
> Featured - > Feature

Changed it.

**Comment by Night-Pryanik** [comment]
Feature - > Features

**Comment by ZhilkinSerg** [comment]
> 
> 
> Feature - > Features

Damn, sorry :D

**Comment by RarkGrames** [comment]
> 
> 
> Feature - > Features

Changed it.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Pull request merged**
