### PR TITLE
[CR]Add Chili Pepper, Seed, and Chili Powder Recipe

### PR DESCRIPTION
**Pull request by ituluwituluwzev**
I attempt to make chili powder craftable, by adding plantable chili pepper and a chili powder recipe. If this PR works, I would then add the new vegetable and seed to spawn list. I am still learning using Github, and appreciate any comment and review.

I hope that this would make several food recipes like chili con carne more useful. Chili pepper can be cultivated in cold climate (cf. paprika, kimchi), if climate is why it is not yet in game.

### CODE REVIEW

**Comment by BrettDong** [comment]
Plural names of comestibles are unnecessary. They'll all be displayed as something like `chili pepper (50)` in game.

**Comment by ituluwituluwzev** [comment]
Thanke! Should I remove those lines?

**Comment by Cyrano7** [comment]
Don't chili peppers need to be dried out before being ground into powder?

**Comment by ituluwituluwzev** [comment]
Realistically it does. I will add dried chili pepper and recipe when I get to my computer.

**Comment by Rivet-the-Zombie** [comment]
Can we use the raw peppers in a few recipes, possibly the same ones that already use the powdered form, plus anywhere else they would fit?

**Comment by ituluwituluwzev** [comment]
I make chili powder recipe require source of heat(cf. cornmeal recipe), and add chili pepper to chili con cae and con cabron recipes.

**Comment by BrettDong** [comment]
Sorry for the late reply. You can just remove the line
```JSON
"name_plural" : "chili peppers",
```

**Comment by ituluwituluwzev** [comment]
Thanks! I removed that line.

**Comment by ituluwituluwzev** [comment]
I make chili pepper able to spawn where onion is able to.

**Comment by Rivet-the-Zombie** [comment]
What about seeds? Do they spawn anywhere?

**Comment by Cyrano7** [comment]
@ituluwituluwzev maybe spawn some seeds at the garden store?

**Comment by ituluwituluwzev** [comment]
I make chili pepper seed spawn where other seeds do.

**Comment by Treah** [comment]
Should make the chili powder recipe require a quern just like the flour one does. This would give that tool another use :)

**Pull request merged**
