### PR TITLE
Various item price changes

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
Balance "Price changes for various items as per the documentation"

#### Purpose of change
A bunch of our items (a lot) are either severely overpriced (almost always) or severely underpriced (basically an issue exclusive to food and medicine). This PR aims to push the economy into a slightly better state

#### Describe the solution
- Lug wrench: 20$ -> 3$ - item is useful but very common
- Distaff and spindle: 1$ -> 0.15$ - item is useful but craftable from any random piece of wood so extremely easy to obtain
- Wooden shed stick: 0.5$ -> 0.15$ - item is useful but craftable from any random piece of wood so extremely easy to obtain
- Pair of knitting needles: 1$ -> 0.15$ - item is useful but craftable from any random piece of wood so extremely easy to obtain
- Paint chipper: 1$ -> 0.15$ - item is theoretically useful in some niche situations; rarer to come by but extremely easy (likely too easy, honestly) to craft yourself
- "Nail Your Law Firm Interview": 80$ -> 2.5$ - this is not something you'll be creating post Cataclysm so it's effectively a limited resource and it can be situationally useful (or, well, I suppose recreation for some people?) so it should still have decent value just not THAT much value
- Flatjaw tongs: 0.1$ -> 3$ - this is a relatively hard to come by (though craftable) item that is now an absolute necessity to start metalworking so it should be relatively expensive - if anything it's still too cheap
- Hotcut: 0.25$ -> 2.5$ - an important crafting tool, not too easy to come by
- Drift: 0.4$ -> 2.5$ - an important crafting tool, not too easy to come by 
- Stylish corrective glasses: 50$ -> 7.5$ - stylish does not warrant a 10x price increase
- Stylish corrective sunglasses: 50$ -> 7.5$ - stylish does not warrant a 10x price increase
- Transition corrective glasses: 50$ -> 7.5$ - useful, not really craftable, certainly overpriced at 50$ (may be worth more, but I based it off corrective sunglasses which cost 5$)
- Stylish transition corrective glasses: 50$ -> 8$ - stylish does not warrant a 10x price increase
- Rubber chunk: 0.75$ -> 0.02$ (~0.5$/kg - still 2x over the suggested maximum for raw resources in the pricing doc)
- Scrap aluminum: 0.1$ -> 0.02$ (~0.4$/kg - also still over the suggested maximum for raw resources in the pricing doc)

### CODE REVIEW

**Comment by Zireael07** [comment]
Is the lug wrench a post-Cata survivor item or a pre-Cata industrial item (the name is totally Greek to me :P )

**Comment by Karol1223** [comment]
> Is the lug wrench a post-Cata survivor item or a pre-Cata industrial item (the name is totally Greek to me :P )

It's a pre-Cata tool used for... okay, I'm not a mechanic, but ingame it's used for changing wheels. I am 99% sure that that's what it's used for irl as well.

It spawns in basically every other car. It's craftable but you need a blacksmithing setup. With these in mind, it's an item that is certainly useful but not life-or-death levels of useful, and extremely easy to come by. With the assumption from the pricing doc that most people don't go out and loot towns, the lug wrench would still have decent value but 20$ was overkill.

**Comment by Zireael07** [comment]
The thing is, pre-Cata tools are worth more than post-Cata just by virtue of being pre-Cataclysm industrial stuff. This one should stay as is, maybe with a tiny reduction to 12-15$ imho

**Comment by Karol1223** [comment]
> The thing is, pre-Cata tools are worth more than post-Cata just by virtue of being pre-Cataclysm industrial stuff. This one should stay as is, maybe with a tiny reduction to 12-15$ imho

Nah. Read the pricing doc. Besides, our pre-Cata tools are all over the place as is. You have flatjaw tongs costing 0.1$, pliers (which are in the doc as an example) 2.5$ and lug wrenches costing 20$. A lug wrench is really *less* useful than pliers or flatjaws, since it has a more limited usage.

**Pull request merged**
