### PR TITLE
Remove storage space from belts and helmet netting.

### PR DESCRIPTION
**Pull request by kevingranade**
These two don't really make sense, the helmet netting is going to buy you a tiny fraction of a point of storage (oh, a cigarette pack or so), and as for the belt, if we allow that we might as well bump up the storage of most other clothing as well, because you can stick stuff all over the place if you really want to.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
So now they serve no purpose whatsoever?

I can dig that they shouldn't really be providing extra storage space, but this makes belts and helmet netting as useless as those ridiculous cat ears. Would it be better to just remove them from the game entirely?

**Comment by Night-Pryanik** [comment]
How about make them behave like: holsters - for guns; sheaths and scabbards - for blades; boots - for knives, quivers - for arrows, and so on?
Create a list of items that one can put in helmet netting (like aforementioned cigarette pack) and belts (like, ummm, a flask?).

**Comment by kevingranade** [comment]
> Would it be better to just remove them from the game entirely?

No, and for the same reason as the cat ears, because some people are going to want to dress appropriately* whether it's tactically optimal or not.  The vast majority of the clothing items in the game are sub-optimal, and if this were the kind of game that eschews "clutter", we would have never added well over half of the items in the game.  Put another way, items don't need a competitive place on the power curve in order to exist, they can just exist.

As for holstering and such, if someone wants to add a system where certain items can be clipped to certain articles of clothing with a nice ui and a nice implementation, they can feel free, but I'm not interested.

*For whatever their idea of appropriate is :)

**Comment by chaosvolt** [comment]
Doh. I'd already said I was volunteering to that in my assorted armor PR quite some time before you initiated the PR.

Nice to find that Coolthulhu and I are only just now realizing this while they're in the middle of merging. ._.

**Comment by kevingranade** [comment]
That would be because you kept a large PR open for a long time, this is why
we say to keep your PRs small and targeted.  Any PR with a title including
'assorted' is just asking for conflicts.  There's not much overhead for a
bunch of small PRs unless they conflict with each other, there *is* a lot
of overhead for large PRs.

**Comment by chaosvolt** [comment]
True, probably should've restricted it to its original focus. Opting to use that PR to add a whistle function and spend a full day or two unfucking it likely derailed it further as well. @_@

**Pull request merged**
