### PR TITLE
Clean up arrow recipes

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Change arrow making process to skip recipe that creates an unfletched arrow. Now these recipes create an arrow that is ready for being fired from a bow.
2. Reduce amount of superglue and bone glue used in arrow recipes, to make it actually worth using  it as an arrow component.
3. Make most arrow recipes non-reversible.
4. Remove "NO_RECOVER" flag from components in most recipes, as they aren't reversible anyway.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good changes.
Those glue costs could be lowered to 1 in all cases, though. Old costs were insane, but 20 thread is still much less than 1 glue.

**Comment by chaosvolt** [comment]
Ah, nice. I'd always favored the standard wooden arrows for being a tad simpler to make.

Though wooden crossbow bolts remain my favorite for now. XP

**Comment by Coolthulhu** [comment]
By the way, wouldn't it be possible to also "inline" fletching like that? Having only the final recipes for arrows would make them significantly less annoying to craft, maybe with the exception of fire-hardened ones.

**Comment by chaosvolt** [comment]
Hmm? Inline fletching? Might be feasible.

**Comment by Darkyhard** [comment]
Done. You need to craft only once to get usable arrows now.

**Pull request merged**
