### PR TITLE
Next Lua interface enhancement

### PR DESCRIPTION
**Pull request by BevapDin**
#### Export of enumerations.

The values can be specified as string `"bp_leg_r"`. Alternatively they can be exported through a global table (`body_part.bp_leg_r`) - this feature can be disabled easily (just remove the call to `LuaEnum<body_part>::export_global`). It may even depend on an option or a preprocessor directive. The only difference is that accessing a non-existing value in the global table will immediately raise an error. It's currently only done for the `body_part` enum.

``` Lua
local the_bp = "bp_leg_R" -- note the misspelling
-- Thousands lines later:
player:add_effect("hot", 10, the_bp) -- Now this raises an error: "bp_leg_R" is invalid

-- Compared to the global table:
local the_bp = body_part.bp_leg_R -- raises the error here: "bp_leg_R" is invalid
```

---
#### Wrapper generator supports overloaded functions.

The generated C++ wrapper functions check and dispatch the call to the overloaded function. Note that this has some ambiguity because Lua has a different type system. The C++ types `char`, `short` and `int` are different, but Lua only returns a number, which may be any those, so the wrapper functions can not decide which overload to choose.

The format of the function definitions in lua/class_definitions.lua needed to be changed for this feature. Previously it was:

``` Lua
functions = {
    i_clear = { args = { "tripoint" } , rval = nil },
    i_clear = { args = { "point" }, rval = nil },
}
```

This would result in a table containing only the second entry (with the `point` as parameter), the first entry would simply be overridden. The new syntax is to put the function name as separate entry into the function data table and make the `functions` table an array:

``` Lua
functions = {
    { name = "i_clear", args = { "tripoint" } , rval = nil },
    { name = "i_clear", args = { "point" }, rval = nil },
}
```

It keeps both overloads in the table, the bindings generator later generates the proper code to decide which overload to call upon runtime.

This overloading allows to use default parameters. The function `void f(int = 0)` is simply added to the list twice, once with the parameter and once without it:

``` Lua
functions = {
    { name = "f", args = { "int" } , rval = nil },
    { name = "f", args = { }, rval = nil },
}
```

From the caller side, it looks that way anyway. You can see this with the declaration of the `Creature::add_effect` function. The multiple declarations are a bit redundant, so this might be changed later.

---
#### Export of the game instance `g`

This allowed to remove some global functions that wrapped calls to it.

``` Lua
-- Old, does not work anymore:
game.revive_corpse( ... )
-- New, and in color, just like you'd write in C++:
g:revive_corpse( ... )
```

It's two characters shorter, mimics the C++ side, but it might look strange to people used to Lua (?)

---

Some more functions have been exported to Lua, mostly field, `phase_id` or `body_part` related.

Btw. the 3D overload of `map::place_items` is declared but is apparently nowhere defined.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I just realized I don't know how to properly test this one.
It doesn't seem to break any of the existing compatibility, but someone with more skills at lua should probably take a look at it.

**Comment by kevingranade** [comment]
I don't have a problem with the addition per se, I want to give LUA a fair shake, but the current situation is that we now have another thousand lines of very arcane code that is for the most part not being used, which means it is liable to break the next time anything it refers to is changed, and we won't even know it happened since no one is using it.
In other words, is there a plan here, or are you just trying to make the LUA interface "better"?

**Comment by BevapDin** [comment]
> I don't have a problem with the addition per se, I want to give LUA a fair shake, but the current situation is that we now have another thousand lines of very arcane code that is for the most part not being used, which means it is liable to break the next time anything it refers to is changed, and we won't even know it happened since no one is using it.

Changing the C++ source has always the chance to break the Lua interfaces, there is not much one can do here (I think). The best I can offer is to create some standard interface with a set of defined functions that are (per definition) stable and have to be supported "forever". All code changes need to respect that interface and may need to provide compatibility wrappers if the change the C++ functions.

> In other words, is there a plan here, or are you just trying to make the LUA interface "better"?

The plan is to give Lua a meaningful and useful set of function to operate on.

This is the hen and egg problem you mentioned in the other PR. Nobody will use Lua to do anything if they can not access the game data.

> is that we now have another thousand lines of very arcane code that is for the most part not being used,

By arcane code, do you mean the Lua wrapper generator / the C++ wrapper code in catalua or the Lua code somewhere or the class_definitions.lua?

Btw. having a static list of exported functions in lua/class_definitions.lua makes sure the interface is not directly broken. Whenever somebody changed the signature of the functions, catalua.cpp won't compile and the developer has to manually fix this by either changing the Lua interface or providing a suitable wrapper.

**Comment by kevingranade** [comment]
Ok, 'trying to break the chicken/egg impasse' is a good reason.
I agree it's overall an improvement, wasn't criticising the code itself,
and having interface breakage be visible outside LUA=1 is a huge
improvement.

**Comment by DavidKeaton** [comment]
Been loving the Lua changes. Been considering messing with it for a mod.

**Comment by CIB** [comment]
:+1:

**Pull request merged**
