### PR TITLE
Add a new early-game weapon - the makeshift shotgun

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

SUMMARY: Content "Add a new early-game weapon - the makeshift shotgun"

#### Purpose of change

Since simple pipe guns were obsoleted, there has been a sore lack of early-game craftable shotguns. This remedies the change with a fairly realistic craftable pipe shotgun.

#### Describe the solution

This simple shotgun composed of two pipes and metal scraps can tide the player over until they gain something more powerful. It has no sights whatsoever and lacks a support stock, so dispersion is extreme compared to other options.

#### Describe alternatives you've considered

I could have updated the old pipe shotgun recipes to be much more realistic, but these weapons would likely require welding tools and wood saws, which the player will not be able to access at the start of the game.

I could have easily updated the "2-shot special" .38 pistol  using the same method. It's unreasonable to make a firearm out of metal scrap, a pipe and a 1/4 of a duct tape roll.

In future, I would make this weapon have a quick reload time if possible. Flip barrel and slam.

#### Testing

Wish for weapon.
Wish for ammo.
Fire away!

#### Additional context

This weapon would need to work for Generic Guns, and be still craftable there. (I'm a big fan of that mod). I don't know how to do it, however.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Make sure generic guns is updated for this addition.

**Comment by Xenomorph-III** [comment]
Got it! 

So I'll go into the mods folder then.

And I saw your comment about rebsing to master. Right now I'm using web github. Was trying to find a rebase button.

**Comment by Xenomorph-III** [comment]
The addition to Generic Guns are done.

**Comment by Xenomorph-III** [comment]
Is there any way to fix the C/C++ CI build thing?

**Comment by Xenomorph-III** [comment]
I think the double spaces issue has been resolved now.

**Comment by Xenomorph-III** [comment]
Last thing - what's the purpose of the shotshell in the improvised firearm crafting recipes?

**Pull request merged**
