### PR TITLE
[MoM] Update Anabolic Rejuvenation and Accelerated Resuscitation with EoCified healing

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Update Anabolic Rejuvenation and Accelerated Resuscitation with EoCified healing"

#### Purpose of change

Mirror of #77657, converts the healing of both powers over to EoC, which lets it run faster and prevent you from bleeding to death in addition to healing you. 

#### Describe the solution

Copy over the EoC. Set the MoM version to be affected by Nether Attunement, intelligence, and power level, as normal.

#### Testing
Caused bleeding and injury and turned on anabolic rejuvenation. It worked.

### CODE REVIEW

**Comment by Hyperseeker** [comment]
You may have forgotten to set category and description for the PR.

**Comment by Standing-Storm** [comment]
Also looks like the formatting didn't run on save. I might have to break up that 6-deep run_eocs chain

**Comment by Hyperseeker** [comment]
Have you considered iterating over an array of strings, each a body part ID? This might shorten your EOC significantly if it's possible.

**Comment by Standing-Storm** [comment]
I don't believe it's possible to iterate over an array with EoCs, unfortunately.

**Comment by Standing-Storm** [comment]
Oh, there's a special carveout for bodyparts? That explains it.

**Pull request merged**
