### PR TITLE
Remove strawberry and blueberry jams - take three

### LINKED ISSUE #20396: Remove strawberry and blueberry jam items, use generic fruit jam (take 2)
This is a copy of issue #20344, which has been auto-closed by PR #20385 and can't be reopened.

PR #20385 has performed the obsoletion incorrectly - see reverting PR #20395.

-----

`data/json/recipes/recipe_food.json` has `jam_(straw|blue)berries` listed as ingredients for "jam sandwitch", but there is no crafting recipe for them.

`grep -Er "jam_(straw|blue)berries" data` shows these specific items are still present in mapgen, item groups, etc..

Generic jam was added in commit 505ebf4708c1a55eb115ec48e442cd75ba9b3dea (part of PR #3521). The PR is huge (+1,039 −54).

Specific jam recipes were removed in bde1d9fa6885819c399b1219bcb6c755fb87a13f (part of PR  #11507). The items themselves were not removed then since that would have "broken" save games (see discussion in PR).

Obsoletion was not imlemented AFAIK at the time of that PR. It is now, so it should be possible to stop spawning specific jams for new savegames.

"Splitting" recipes might require a different approach - don't remember ATM.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20396.

I think this time it's done right - removed jams from every place it was spawned or existed in recipes and replaced them with generic fruit jam through the migration.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by AMurkin** [comment]
Multiple extra commas at the end of arrays in json files.

**Comment by Broken-Admin** [comment]
Why are we removing these items exactly?

**Comment by Night-Pryanik** [comment]
We can create strawberry and blueberry jams through the generic jam recipe, so separate jam recipes are redundant.

**Comment by AMurkin** [comment]
Sadly them not stacked.
image
```json
{
  "typeid": "jar_3l_glass_sealed",
  "bday": 6811763,
  "invlet": 97,
  "contents": [ { "typeid": "jam_fruit", "charges": 2, "bday": 6811763, "active": true, "last_rot_check": 7658771 } ]
},
{
  "typeid": "jar_3l_glass_sealed",
  "bday": 5335823,
  "invlet": 108,
  "contents": [ { "typeid": "jam_fruit", "charges": 2, "bday": 5335823, "active": true, "last_rot_check": 7658771 } ]
},
{
  "typeid": "jar_3l_glass_sealed",
  "invlet": 109,
  "contents": [ { "typeid": "jam_fruit", "charges": 2, "active": true, "last_rot_check": 7658771 } ]
},
{
  "typeid": "jar_3l_glass_sealed",
  "bday": 5087385,
  "invlet": 115,
  "contents": [ { "typeid": "jam_fruit", "charges": 2, "bday": 5087385, "active": true, "last_rot_check": 7658771 } ]
},
{
  "typeid": "jar_3l_glass_sealed",
  "bday": 4920436,
  "invlet": 117,
  "contents": [ { "typeid": "jam_fruit", "charges": 2, "bday": 4920436, "active": true, "last_rot_check": 7658771 } ]
}
```

**Comment by Broken-Admin** [comment]
They don't stack due to different `bday` entries I assume.

**Pull request merged**
