### PR TITLE
[Innawood] Makes cannon craftable

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Mods "[Innawood] Makes cannon craftable"

#### Purpose of change

Having a massive artillery piece to lay siege onto your enemies with is cool.

#### Describe the solution

Adds a recipe for the cannon. It requires a staggering amount of metal, and several days of work. Otherwise requires skills similar to those needed to craft a flintlock rifle.

#### Describe alternatives you've considered

Maybe it could require more fuel to make.
It could require different skills and proficiencies.
Perhaps it should require new kinds of blacksmithing furniture.
Perhaps the cannon should require less metal.

#### Testing

Checked that the recipe showed up in game and looked correct.

#### Additional context
For when something absolutely positively _has_ to die.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Well, you can make cannons out of (mostly) leather... This has been used historically as a single shot weapon.

**Comment by Light-Wave** [comment]
> Well, you can make cannons out of (mostly) leather... This has been used historically as a single shot weapon.

Interesting. This specific weapon is however a 3-inch ordnance rifle. Specifically the barrel of one.
https://en.wikipedia.org/wiki/3-inch_ordnance_rifle

**Comment by Light-Wave** [comment]
Error seems to be related to detach_vehicle  and should be unrelated to this change.

**Comment by Wishbringer** [comment]
Shouldn't this be base game content?

**Comment by Alex-Folts** [comment]
Craft time should be 5-10 days.

Alternative recipe could be cast it out of bronze, it is lot faster(like 12 hours or so) but require 400-500kg of bronze.

**Comment by Light-Wave** [comment]
> Craft time should be 5-10 days.
> 
> Alternative recipe could be cast it out of bronze, it is lot faster(like 12 hours or so) but require 400-500kg of bronze.

Without proficiencies, the crafting time is 1 week 2 days. And with the weary mechanics, it will likely take even longer to craft. I think that is good enough.

> Shouldn't this PR be base game content? Would love to be able to build a cannon and shoot grapeshot at hordes of zombies. But there is no reason why that shouldn't be base game IMO.

Main reason is that it takes so long to craft, so I thought it might not fit well with the vision of the base game, where you typically don't spend a week crafting one thing. Especially if you can relatively easily loot something better. I was also unsure if I got the balance and the realism of the recipe good enough to be in the base game.

**Comment by Proxima-b** [comment]
Innawood lacks ememies to shoot at, other than mi-go and wasps

**Comment by Light-Wave** [comment]
> Innawood lacks ememies to shoot at, other than mi-go and wasps

I was inspired to make this addition after spending like 200 rounds of riffle ammunition on a group of fungal towers.

**Pull request merged**
