### PR TITLE
food.json - duplicates removed

### PR DESCRIPTION
**Pull request by LilShiningMan**
```SUMMARY: Infrastructure "removed duplicate item group entries in food.json"```

#### Summary

I noticed there were a few item group entries in food.json that were duplicates. They've now been removed.

#### Testing
delinted json, booted up game and it works just fine.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
You could probably tell us where "original" item group are located so we could compare by ourselves.

**Comment by ZhilkinSerg** [comment]
Probably in the same file.

**Comment by LilShiningMan** [comment]
> 
> 
> Probably in the same file.

yes, further up in the same file

**Comment by ZhilkinSerg** [comment]
There is a small difference in one of item groups:

removed - stayed

image

**Pull request merged**
