### PR TITLE
[WIP] Restriction on driving and playing musical instruments simultaneously

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Forbid controlling vehicle and playing two-handed musical instruments (hard-coded for now). Harmonica is ok because it has a holder.

### CODE REVIEW

**Comment by illi-kun** [comment]
Hardcoding IDs is a bad practice. You can introduce a new flag for this purpose.

**Comment by codemime** [comment]
Agreed about hardcoded IDs, but Introducing a new flag isn't a good proposal either. We should keep the number of flags limited and introduce new ones only if they pay for themselves.

Please, consider usage of `"effect_playing_instrument"` to check if player plays an instrument and `islot_armor::covers` to see which parts the armor-tool (boo) possibly encumbers. `"Harmonica with a holder"` encumbers head, and `"whistle"` doesn't encumber anything (but should encumber mouth [hint]) so they both wouldn't prevent player from driving.

**Comment by Night-Pryanik** [comment]
Well, trying to use `"effect_playing_instrument"` was my first intention. 
I added `const efftype_id effect_playing_instrument( "effect_playing_instrument" );` at the top of `game.cpp`. But testing it in code like
`if( u.has_effect("effect_playing_instrument") {
               add_msg( m_info, _( "You can't operate a vehicle while playing musical instrument." ) ); 
}`
did nothing. I don't know where is the error, so I switched to `"u.has_active.item"`.

**Comment by codemime** [comment]
I reckon the reason is 1 tick duration of the effect. Then you can try yet another approach which still doesn't involve hardcoded item ids (the code was not tested):

```c++
bool Character::is_using_item( const std::string &iuse_name ) const
{
    return has_item_with( [ &iuse_name ]( const item & it ) {
        return it.active && it.type->can_use( iuse_name );
    } );
}
...
if( p->is_using_item( "musical_instrument" ) ) {
    // do your stuff
}

```
It's not ideal since an item can have more than one `iuse` function, but I suppose it would work here. To avoid the misleading name you can also use the lambda locally.

**Comment by Night-Pryanik** [comment]
@codemime thanks a lot for your efforts, but I'm afraid I must close this PR because this is too complex for me. I just don't know what all these `const`, single ampersands and lambda are.
And even if I leave hardcoded Ids, my PR is bugged, and it'll require improvements in code for playing musical instruments to fix it.

**Pull request closed without merging**
