### PR TITLE
Crops will overgrow/die if not harvested in time

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Balance "Unattended crops that are ready to harvest will die if not harvested before their next growth period"

#### Purpose of change
My runs often go multiple years. One of the things that has always bothered me is that farms have bountiful fields full of food  which never, ever goes bad. Similarly, I've left crops behind before when moving base, only to come back years later to a mysterious perfectly square patch of crops in pristine condition. It sticks around forever just waiting to be harvested by the player. This trivializes the entire food portion of the game and means players never engage with it in any meaningful way.

#### Describe the solution
Well now they just don't wait for you. Those plants just keep on growing and growing and growing... Or in the case of planters, they just die.

#### Describe alternatives you've considered
if I'm feeling really spicy I might add winter killing crops (though that means having to JSONize which crops survive winter! Effort!)

#### Testing
Here's what the giant mutable farms look like by Autumn 61, 180 days after game start and with months of neglect: 
image
None of these are harvestable anymore.

And here's me clearing (and replanting) an overgrown field using the zone manager:

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/0e8e43ab-42e1-4204-b5ef-02bd3156098d

#### Additional context
Crop tending eventually, along with the automation to support it. But not today.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Winter killing plants, self seeding of some plants, plants replaced by weeds as time goes by (many domesticated plants aren't particularly competitive, and Americans seem to favor poison as the means to deal with any threats to yields, and there's nobody left to do the spraying). Also, more animals eating the crops.

If you want to be mean, you could introduce GMO soy beans and corn (at least) whose seeds are intentionally rendered non viable (and if you're really nasty the player can't tell if they're GMO or not).

**Comment by Nebnis** [comment]
Perfect, now we just need to eliminate the insane amount of fruiting trees in the wilds and maybe late game characters will have to work a lil harder for food.

**Comment by Vane79** [comment]
What if the player wasn't able to find certain seeds/planted crops before the first winter? Is he screwed then?

**Comment by RenechCDDA** [comment]
> What if the player wasn't able to find certain seeds/planted crops before the first winter? Is he screwed then?

Seeds generated as items will still remain viable indefinitely. Even if all agricultural crop seeds were made unavailable to the player they would still be able to grow wild plants gained from forage, or trade for existing seed stocks from the few communities still around.

**Comment by RenechCDDA** [comment]
> Also, keep in mind mods changing the way the game's played. I.E. innawood, sky island.

None of them are particularly relevant here, this is just how crops work. If sky islands wants crops to be magic for some reason it's a simple json override, the same way I did it.

**Comment by adamkad1** [comment]
> What if the player wasn't able to find certain seeds/planted crops before the first winter? Is he screwed then?
> 
> Also, keep in mind mods changing the way the game's played. I.E. innawood, sky island.

Just harvest and preserve properly I guess?

**Pull request merged**
