### PR TITLE
[CR] Add steeltoed shoes

### PR DESCRIPTION
**Pull request by TealcOneill**
#### Summary
Content "Adds a new footwear option."

#### Purpose of change
These are the kind of shoes I and most of my family use and I like them a lot. I also did this to help get me used to the content creation requirements for CDDA.

#### Describe the solution
I've added a new footwear option and made it an generatable alongside steeltoed boots where appropriate with a 30% lower spawn chance. I set up one of the two NPCs that have pre-set clothing options to have steeltoed sneakers instead of boots. I also set up a disassembly recipe for the shoe. Incidentally almost no shoes have a "longest_side" variable and thus end up 5" long, I set my shoe to 10" because that's about right for me.

#### Describe alternatives you've considered
Not adding this item.

#### Testing
I spawned 5 of the steeltoed shoes and made sure all had the correct stats and disassembled into the correct materials. I also used the debug tester to spawn each group that I added it to once or twice and then checked the average amongst all of those tests and got very close to the expected 30% less than steeltoed boots. Finally, I went and found Fatima in the refuge center and made sure she had steeltoed shoes.

#### Additional context
I use almost exactly these shoes as my daily wear so I originally just bumped the encumbrance to 5 from 4 because there's a barely noticeable difference between these and regular sneakers. However, this puts them about twice as good as steeltoed boots according to the armor balance page despite their lower protection value. I'm hoping someone more experienced can tell me what they think is an appropriate encumbrance value.
Steeltoed boots show up twice under the NC_JUNK_SHOPKEEP group so I only put steeltoed shoes below 1 of them. I'm unsure whether there's a reason it's on the list twice.
Steeltoed boots are referenced in "tile_config_template.json" but I'm not entirely sure what that is so I didn't want to try and mimic it without an affirmative.
I fixed steeltoed boots being conductive.(I don't know if this even matters for shoes but they are specifically made non-conductive IRL so it made sense to me.)
I also fixed the 'toecaps' item to use the correct organization in it's description.
IMG_20210901_183735 1
Steeltoe_sneakers1
Updated with pictures of my shoes, mainly to avoid grabbing anything off the internet to post here.

### CODE REVIEW

**Comment by actual-nh** [comment]
Could you include a picture in the PR (partially for anyone wanting to make a sprite)? (And do they make these without laces? I have a personal interest, being a klutz... Thanks!)

**Comment by Winterous** [comment]
I assume that shoes lacking a length is either a simple oversight, or considering that most shoes are foldable to some degree.

**Comment by chrispikula** [comment]
> 
> 
> Could you include a picture in the PR (partially for anyone wanting to make a sprite)? (And do they make these without laces? I have a personal interest, being a klutz... Thanks!)

Steel Toed Rubber Boots exist, so I'd have to assume that regular unlaced variants would exist as well.
~~Also, eyes emoji as it looks like shoes.~~

**Comment by TealcOneill** [comment]
> 
> 
> Could you include a picture in the PR (partially for anyone wanting to make a sprite)? (And do they make these without laces? I have a personal interest, being a klutz... Thanks!)

https://www.safetyshoestoday.com/us/construction/lacing-system/laceless-safety-shoes, here's a list I found online!

**Comment by TealcOneill** [comment]
I'm still looking for feedback on the encumbrance, the steeltoe_boots showing up under NC_JUNK_SHOPKEEP twice, and the "tile_config_template.json" thing.

**Comment by TealcOneill** [comment]
I rechecked the armor balance formula and realized I made a mistake so the shoe is not so much better than the boots as I thought. I fixed the shopkeep thing in another pr and I'm just going to leave the tile_config_template alone.

**Pull request merged**
