### PR TITLE
Add indoor portal storm warnings and voices

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
Content "Add indoor portal storm warnings and voices"

#### Purpose of change
Make portal storm warnings harder to miss and add atmosphere for them even if you aren't being harmed.

#### Describe the solution
Add indoor warning messages.  Also add voices that trigger while you are indoors to attempt(often clumsily) to convince you to come outside.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Won't that result in you being prevented from sleeping by those voices for the duration of the mess?

**Comment by Fris0uman** [comment]
Does this mean that soundpack can have an inside and outside sound for portal storms?

**Comment by Ramza13** [comment]
> 
> 
> Won't that result in you being prevented from sleeping by those voices for the duration of the mess?

Good catch, added a check to prevent that.

> 
> 
> Does this mean that soundpack can have an inside and outside sound for portal storms?

Right now there aren't any sound effects other than generic background portal storm sounds hooked up.  I'm not opposed to doing so, just don't know enough about formats and creator desire to add any.  Its pretty easy via json to add sound effects to the portal storm events if there is desire.

**Comment by FoolsGold45** [comment]
Lore-wise, what faction/entity is broadcasting these voices?

**Comment by Ramza13** [comment]
> 
> 
> Lore-wise, what faction/entity is broadcasting these voices?

My feeling is that its one of any number of different nether entities. And not the same one each time.

**Pull request merged**
