### PR TITLE
Add JSON mapgen for computer class, jsonize evac shelter

### PR DESCRIPTION
**Pull request by Coolthulhu**
Includes #21336

Added a json binding for mapgen for the `computer` class.
Documentation on wiki: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Mapgen:-computers

I couldn't find a good example, so I also jsonized shelter mapgen
This also changes the drops minimally. They aren't hardcoded now so spawn rates matter. You can also sometimes get a spare gas mask.

EDIT: Updated

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Will it be merged anytime soon?

**Comment by DangerNoodle** [comment]
Is there anything currently preventing this from being merged?

**Comment by ZhilkinSerg** [comment]
> Is there anything currently preventing this from being merged?

Conflicting `mapgen.cpp`

**Comment by codemime** [comment]
Looks good to go, but needs conflict resolution. I will test-merge this as soon as it's done.

**Pull request merged**
