### PR TITLE
Backported 0.E fixes

### PR DESCRIPTION
**Pull request by int-ua**
#### Summary

SUMMARY: Bugfixes "Backported some fixes to 0.E"

#### Describe the solution

Original PRs are mentioned in ~~both~~ commit messages.

#### Testing

Hirmuolio commits tested and look good, Qrox changes not tested by me.

### CODE REVIEW

**Comment by Qrox** [comment]
While you're at it can you also backport #39405 and #40025 to 0.E?

**Comment by int-ua** [comment]
Ok, I'll try to.

**Comment by int-ua** [comment]
@Qrox Done. How does it look? No testing yet, obviously.

**Comment by int-ua** [comment]
Tested Hirmuolio commits, they look good. @Qrox can you confirm yours will work on 0.E?

**Comment by Qrox** [comment]
Sure, I'll test when I have time.

**Pull request merged**
