### PR TITLE
Remove unnecessary overmap parameters from Arcana mod

### PR DESCRIPTION
**Pull request by illi-kun**
The same changes in core overmap file are done in #14522.

### CODE REVIEW

**Comment by Malkeus** [comment]
It's Arcana day!

**Comment by illi-kun** [comment]
Yeah, I was surprised by seeing your PR :-) Fortunately, our PRs change different files and not in conflict with each other.

**Comment by chaosvolt** [comment]
Ah, nice. I likely left some things in due to redundancy, or likely copying existing overmaps.

**Comment by Malkeus** [comment]
I will admit to being slightly concerned when I saw yours as well ;)

**Pull request merged**
