### PR TITLE
Forbid alchemy

### PR DESCRIPTION
**Pull request by mugling**
You can't make `lead` from `steel` no matter how hard you might try

### CODE REVIEW

**Comment by Darkyhard** [comment]
This recipe was used before to create material for making bullets. Wasn't it intended to make bullets from scrap?

**Comment by mugling** [comment]
We already have separate recipes for crafting ammo from non-ideal components. If we're going to accept `steel` as a bullet material that might also be acceptable but certainly not transmuting steel into lead.

**Comment by Mecares** [comment]
Yes the significant lower density of steel would make the bullets less effective.
I would suggest adding some items that could be disassembled to get lead. 
Like Diving weights (possible as a Belt) or Weightlifting weights (Pipe and Weights) and of course weights used for fishing in sporting-goods-stores.
Curtains often have chains of lead as a weight.
Some washing machines have lead weights in the bottom of make them move less.

**Comment by mugling** [comment]
@Mecares yes at present the only source is vehicle batteries and this is limiting. Washing machines tend to be concrete however - lead is expensive,

**Comment by mightyagrippa** [comment]
Speaking of expensive remember that silver and gold work in reloading recipes. The science is plausible (especially for silver), armored cars give you a decent supply, and the flavor is great; in the cataclysm bullets are worth their literal weight in gold.

**Comment by bumpkindda** [comment]
I don't think anyone's reloading will ever bottleneck at the lead before the casings and gunpowder now that gunpowder is uncraftable. This recipe might have been useful once but it's pointless now from a gameplay perspective.

**Comment by Rivet-the-Zombie** [comment]
>Wasn't it intended to make bullets from scrap?

That was the point, back before we had good sources of lead like car batteries.

>Yes the significant lower density of steel would make the bullets less effective.

We could keep scrap slugs for a cheap form of AP ammo, but yeah, they'd be less effective otherwise.

**Comment by SeanMirrsen** [comment]
Steel is less dense, but harder - a larger steel bullet of equal mass to the lead one would hit just as hard *and* have better armor-piercing. If it's the same size, it will have higher muzzle velocity, so both better AP *and* damage up close, though dropping significantly with range.  
I think it's worth making a distinction. Making cast iron or steel bullets out of melted scrap, or milling them out of steel chunks if you find or MacGyver a lathe. Even if they do hit less hard than lead ones (guns don't tend to take different cartridge dimensions well, so you'll be limited in size), the tradeoff of damage for AP could very well be useful.

**Comment by Coolthulhu** [comment]
Steel bullets are not used because not every barrel can take those. Lead and gold are much softer than steel and a barrel intended for lead may be heavily damaged when used with steel bullets.

**Pull request merged**
