### PR TITLE
Changes roasted acorn description

### PR DESCRIPTION
**Pull request by ghost**
Updates the description for roasted acorns.

#### Summary
Bugfixes "Roasted acorns description"

#### Purpose of change
Updates the description to more clearly show the multi-step process involved. 

#### Describe alternatives you've considered
I may be entirely wrong about this. I've never eaten acorns of any sort.

#### Testing
Checked in game. New description is displayed.

### CODE REVIEW

**Review by Maleclypse — DISMISSED** [review]

**Comment by flybye3o6** [comment]
most irl recipes iv seen require you to boil or leach acorns to remove the tannins, iv not seen a single recipe that allows you to cook acorns before doing that, if you know of any methods that allow you to cook acorns without the lengthy process of removing the tannins id like to know 
i did some research on this when i was working on #62052

**Comment by RenechCDDA** [comment]
#55928, which *replaced normal acorns with cooked acorns* details the logic behind using cooked acorns. Apparently they are inedible without that preparation. Acorns in particular have come up as a topic several times and I believe #55928 is correct on all counts.

The description was not changed, so if anything the description if erroneous.

**Comment by intergalacticdata** [comment]
Nope, I've done zero research at all. I just couldn't understand why the roasted recipe said 'a handful of nuts from a tree' and the cooked acorns recipe describes turning it into paste etc. As this is intentional, I suggest updating the description for roasted acorns instead so that it is more clear.

**Comment by flybye3o6** [comment]
you could change this PR into doing that, or i can take a look at it myself

**Comment by intergalacticdata** [comment]
> 

If you have a suggested wording, I'll just throw that in this and revert the ingredient change, or you can just handle it if you prefer. No difference to me.

**Comment by flybye3o6** [comment]
well they kinda look like larger darker peanuts when roasted with a wood looking texture
"A handful of roasted nuts from an oak tree. A smoked earthy flavored treat after all the work that went into remove the bitterness."
im not good with descriptions
btw eating acorns without removing the tannins can cause inflammation in your digestive tract

**Comment by intergalacticdata** [comment]
For reference, this is the text from cooked acorns "A serving of acorns that have been hulled, chopped, and boiled in water before being thoroughly toasted until dry. Filling and nutritious."

The "from a tree" part seems confusing to me as it kind of implies directly from the tree, whereas these are shelled and chopped.

How about:
"A handful of shelled and roasted acorns. A smoked, earthy flavored treat. There's hardly any bitterness left."

**Pull request closed without merging**
