### PR TITLE
Adds recipes to get thread more quickly from string and rope by using a cutting tool

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
 ```SUMMARY: Content "You can now quickly craft thread directly from string or rope by using a cutting tool."```

#### Purpose of change
Someone brought up a good point that getting thread from strings took a long time, because the 5-minute recipe assumes that you're unraveling it manually. If you had a cutting tool, you could just cut the string into pieces, which is *much* faster than doing it by hand.

#### Describe the solution
You can now craft thread directly from small strings, long strings, short ropes, and long ropes, corresponding to the amount they would yield normally while taking substantially less time. The recipe requires a cutting tool, and yields:
* 50 thread in 30 seconds from a small string.
* 300 thread in 30 seconds from a long string.
* 1800 thread in 5 minutes from a short rope.
* 9000 thread in 10 minutes from a long rope.
* *Note:* Rope recipes take longer because it's a lot more effort to cut through a rope than it is to cut through some string.

#### Describe alternatives you've considered
Adding a recipe to cut strings into smaller strings. Because strings aren't counted by charges, and there doesn't seem to be any replacement tag for `charges` when something isn't counted by charges, I went with this route instead.

### CODE REVIEW

**Comment by Mecares** [comment]
It is not only long to short we are talking about, it is also thick into thin which cannot be done via cutting. Also cutting should result in less thread than carefully unravelling, I'm not sure your numbers represent that and I do not know if many short pieces of thread are even suitable for all the purposes of thread in the game.

**Comment by Ilysen** [comment]
I can remove the ones for rope, but I think the string ones make sense. All disassembling is is breaking down a 36-inch piece of string into six 6-inch pieces of string, which a knife can do very easily.

**Comment by kevingranade** [comment]
Unless I'm missing something, this is nonsense, you do NOT want 6" lengths of thread, you're going to lose the time you saved unraveling the string many times over once you try to do something with the thread.

Please stop posting PRs based on, "someone brought up a good point in chat", you need to exercise some quality control and provide some sourcing for your ideas.

**Comment by Ilysen** [comment]
My sources here come directly from the game itself. Small strings are defined as `A 6-inch long piece of cotton string`, and long strings are defined as `a 3-foot long piece of cotton string. Disassemble it to cut it into smaller pieces.` The description quite ***directly*** states that it involves cutting it into smaller pieces, as do the descriptions, but the time spent disassembling them doesn't represent that.

**Comment by Ilysen** [comment]
@kevingranade My sources here come directly from the game itself. Small strings are defined as `A 6-inch long piece of cotton string`, and long strings are defined as `a 3-foot long piece of cotton string. Disassemble it to cut it into smaller pieces.` The description quite ***directly*** states that it involves cutting it into smaller pieces, as do the descriptions, but the time spent disassembling them doesn't represent that.

**Comment by kevingranade** [comment]
Are you confusing thread and string? Long string disassembles into short string, not thread.
The recipes you added are disassembling long string into thread, which as people on discord pointed out, imply unwinding instead of cutting.

**Pull request closed without merging**
