### PR TITLE
Added two new variants of the basement of the military bunker

### PR DESCRIPTION
**Pull request by Night-Pryanik**
I feel that standard bunker basement is boring and making little sense as all the items are just lying on the ground, there is no furniture etc.
So I added two new variants. I think they are more realistic and interesting. The variants slightly differ from each other.

Standard variant of the basement still has the highest spawn chance, the new variants should spawn more rarely.

default

The new variant has an antechamber with a military card reader. To the left there is a shift room behind the reinforced glass, with a locked door. To the right there are toilets and a shower room.
Also there are relax room, canteen with a kitchen, barracks, locked (by another military card reader) armory, locked (by another military card reader) infirmary with autodoc, anesthesia and a chance to spawn military bionics.
The last room is a locked command room. The difference between the variants is lying in this room (it's not that important, though).

### CODE REVIEW

**Comment by Leland** [comment]
How common are these? Those are some seriously advanced basements

**Comment by Xhuis** [comment]
@Leland I think this post is changing the military bunkers, not basements. It's likely just phrased weirdly, I think.

**Comment by Night-Pryanik** [comment]
These are the military bunker's basements, not ordinary basements one can found under some city houses. The standard bunker basement has 1000 weight, my first variant has 500, and my second variant has 250. This way they should be rather rare, though I'm not fully sure on this, as I don't fully understand the meaning of `weight` field in jsons.

**Comment by nexusmrsep** [comment]
If this is the bunker i think about (guarded by turrets on ground level inside the facility itself) then hooray and praises to you. While a raid on lab's multiple armories gives you so much gear that you may need to revisit few times, this place - to the contrary - looked like every weapon and every bullet were handad out to soldiers during Cataclysm leaving bare walls behind. Effort needed to get in was a waste of time. Good job!

**Pull request merged**
