### PR TITLE
Remove test whiskey and test glass bottle

### PR DESCRIPTION
**Pull request by Cyrano7**
That don't really serve any purpose anymore. They never should have spawned naturally in game so it won't be save breaking to completely delete them.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
There are several test items in the game files that are similar, could they all be removed without breaking anything?

**Comment by Cyrano7** [comment]
Well not all of them should necessarily be removed. I just picked these two because they are pretty much copies of regular items. The test glass bottle is was never updated to what the regular glass bottle is now even so its just a older version of it.

**Comment by Coolthulhu** [comment]
> There are several test items in the game files that are similar, could they all be removed without breaking anything?

Only items that may exist in non-debug worlds need to be obsoleted before removal. Item that is removed will not cause entire saves to become unloadable, it will only result in creation of useless placeholder items and some debugmsgs.

**Comment by mugling** [comment]
After #16694 you can now follow @BevapDin's suggestion and migrate either to the closest equivalent item and/or a special `obsolete` item with an appropriate `description`. The advantage over the old system of `obsolete.json` is that if you still have any other referencing definitions in the JSON the game will complain upon load.

**Pull request merged**
