### PR TITLE
Jsonize hazardous waste sarcophagus

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Jsonize hazardous waste sarcophagus."```

#### Purpose of change
Jsonize hazardous waste sarcophagus.

#### Describe the solution
- Draw json-variant based on hardcoded variant. Put some enhancements in layout and mapgen here and there (added air conditioners, servers, shredders, and other suitable terrains and furniture; tweaked monster, vehicle, and items spawn).
- Removed `draw_sarcophagus` function from `mapgen.cpp` and `map.h`.
- Put hardcoded variant overmap terrains into `obsolete_terrains.json`.
- Made it possible to read fourth security reminder (Security Reminder [1058]) - it existed very long in game files, but due to technical limitations of our UI, it was impossible to place it in computer UI. Read it in underground level of HWS.
- Put reminders to remove remains of hardcoded variant from everywhere they still exist after 0.E. or proper migration.

#### Describe alternatives you've considered
None.

#### Testing
Loaded game with old hardcoded variant already spawned in the world. Spawned new json-variant. No errors.

#### Additional context
None.

### CODE REVIEW

**Comment by Amoebka** [comment]
Have you fixed the elevator access yet? The code for it always spawns on the LOWER level, so the only way to break in is to dig.
It's also notable for being the only console in the game you can't hack. This should probably change?

**Comment by anothersimulacrum** [comment]
You get the code from an NPC quest.

**Comment by ralreegorganon** [comment]
You need to update the entries in the missions that reference this location since the overmap terrain ids are changing, and then test the missions after the change.

The location is assigned as a mission target [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/missiondef.json#L11) and the semantics of that will change because there were multiple locations with the old name but you'll have to pick one to target now.

The location is used as a destination [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/missiondef.json#L14) and that also changes the semantics because the location needs to be visited in order to complete the mission, and previously any of the basement locations would match it, but now you'll have to pick one of them.

**Comment by Night-Pryanik** [comment]
@ralreegorganon done, thanks for reminding.

**Comment by Night-Pryanik** [comment]
> It's also notable for being the only console in the game you can't hack. This should probably change?

It's a quest/balance issue, I don't plan to change anything on this matter in this PR.

**Pull request merged**
