### PR TITLE
Quick fix for Vorpal technique description.

### LINKED ISSUE #24134: Vorpal strike vs NPC targets random body part when 'beheading'
Keep forgetting to report this one.  Any build, any OS, any setup, any mods.
### Expected behavior
Vorpal strike beheading an NPC targets their head.
### Actual behavior
Vorpal strike vs an NPC targets a random body part while saying it beheads them.
### Steps to reproduce the behavior
Change VORPAL in data/json/techniques.json to have high weight since it is insanely rare otherwise, debug high melee/cut skill and a vorpal weapon, attack npcs and watch as you behead the same person multiple times before they die (removing a limb each time you miss head/torso)

### PR DESCRIPTION
**Pull request by nexusmrsep**
Resolves #24134
Vorpal techniqe suggested that its always aimed at the head.
Technique works fine, so only the description had to be changed.

### CODE REVIEW

**Comment by woutershep** [comment]
Given how vorpal comes from a poem about beheading jabberwocks with snicker-snack noises i think this patch isn't the right way to go as it looses that reference. https://en.wikipedia.org/wiki/Vorpal_sword

**Comment by nexusmrsep** [comment]
> Given how vorpal comes from a poem about beheading jabberwocks with snicker-snack noises i think this patch isn't the right way to go as it looses that reference.

Then what is the right path in your opinion?

**Comment by Kelenius** [comment]
>Then what is the right path in your opinion? Mind you, no in game mechanics checks or forces vorpal strikes to go for the head only.

Then it should go for the head.

**Comment by nexusmrsep** [comment]
Always thought vorpal blades were super-sharp-stopped-by-nothing ultra-critical weapons, and not cut-yer-head-clean-off weapons. A man learns all his life it seems.

The structure of the code performs techniqe effects long before the hit is even dealt, and limb chosen, by modyfing calculated damage and doing other-then-damage effects, that are "pushed along", then "forgets" what technique it was. Saying that other way around - when hit is actualy dealt and limb is chosen, this part of the code does not know and care about what technique was used, becouse it is fed all damage modifiers along the way, so also from the techniqe performed far behind (code-wise).

Making is so that a limb selection in hit functions would know that `VORPAL` technique was used long before, to 'lock' the head as target bodypart, is too much effort (at least for me for a ultra-rare techniqe with 1/250 chance of success) and in my knowledge would require too much code-hacks.

Anyway, since the approach of this PR is sub-optimal in your opinion, and I'm not attempting solution above, as conclusion I'm closing this PR.

**Comment by kevingranade** [comment]
I'd prefer it still say snicker-snack for the reference, but lopping off a random limb is perfectly fine.

**Comment by nexusmrsep** [comment]
Message updated.

**Pull request merged**
