### PR TITLE
Added brass and lead to many cartridges, pt. 1

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Added brass and lead to .22

### CODE REVIEW

**Comment by keyspace** [comment]
To clarify: this changes a `material` of `22_lr` (and all inheriting ammo types) from current `steel`.

**Comment by keyspace** [comment]
Should probably be bundled with PR #20142?

**Comment by BorkBorkGoesTheCode** [comment]
>Should probably be bundled with PR #20142?

I don't know if this PR will be rendered obsolete by a system which causes bullets to inherit the materials they were made of; for example: bullets having "brass", "gold" if made from gold, etc.. If nobody has such a system ready for PR, I'll combine them.

**Comment by Coolthulhu** [comment]
Powder is for things that explode or at least burn well.
Would primers get ruined in (weak) fire?

**Comment by BorkBorkGoesTheCode** [comment]
I haven't exposed a primer to fire in recent memory, so I don't know. Powder was added because the unfired .22 case has an integral primer and the COOKOFF flag.

**Pull request merged**
