### PR TITLE
Make the ``monsters`` GitHub label actually get applied - Attempt 2

### LINKED ISSUE #72746: ``monsters`` GitHub label doesn't get applied when monsters are being touched directly
### Describe the bug

As in the title - the label doesn't get automatically assigned when monster JSON is being touched. It does get applied occasionally for other things, though, such as editing monster factions.

### Attach save file

N/A

### Steps to reproduce

1. Look at any PR that touches only monster JSON files
2. No label
3. Cry

### Expected behavior

Touching monster JSON directly should apply the ``monsters`` label to the PR

### Screenshots

_No response_

### Versions and configuration

N/A

### Additional context

My attempts at solving this in #71933 brought no results

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
None

#### Purpose of change
#71933 still didn't fix this

Hopefully fixes #72746

### CODE REVIEW

**Comment by Maleclypse** [comment]
@casswedson you mind checking this out in case it doesn't work?

**Comment by casswedson** [comment]
I'd appreciate it if Karol could point out specific cases since I haven't been keeping up with things lately

**Comment by Karol1223** [comment]
> I'd appreciate it if Karol could point out specific cases since I haven't been keeping up with things lately

https://github.com/CleverRaven/Cataclysm-DDA/issues/72746#issuecomment-2028653731 had examples of PRs that should have gotten the monsters label but even after my prior changes did not. I do not believe there have been any PRs touching monsters since this change here got merged, though.

**Comment by Karol1223** [comment]
With #74873 properly labeled I can now confirm this worked. ~~First~~ Second try

**Pull request merged**
