### PR TITLE
Add phrase widget, a more dynamic alternative to text widgets

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Features "Add phrase widget, a more dynamic alternative to text widgets"

#### Purpose of change

Since the very beginning of my thinking about widgets, I've wanted a JSONized way to associate numeric values with colorized text strings, since that has long been one of the more annoyingly inflexible parts of the old hard-coded collection of panel display functions.

Now these annoyingly inflexible color-text hard-codings are largely assembled in one place in `src/display.cpp`, and associated with what I think of as interim or legacy `*_text` widget variables, which at least gives you a JSONized way to place and label them, but not much else in the way of customization.

Finally I think the widget system may be ready for my original vision of a "phrase" widget, associating a (typically numeric) internal value or range with a JSON-defined text and color. This is the objective of this PR.

Building the widget dreamboat #53957 

#### Describe the solution

I have not even begun to code.

I'm taking an approach that worked well for me on the initial creation of widgets, **documentation first**. So I'm starting out by writing the docs as if it were already working the way I want.

Edit `doc/SIDEBAR_MOD.md`:
- Promote the "Variable widgets" section one level
- Add "Text widget" section with "pain_text" example
- Add "Phrase widget" section with more JSONized wish-example

Example of how one might define a phrase widget:

```json
"id": "pain_description",
"type": "widget",
"var": "pain",
"//": "Uses get_perceived_pain(), 0-60+",
"style": "phrase",
"phrases": [
    { "value": 0, "text": "No pain", "color": "c_light_gray" },
    { "value": 10, "text": "Mild pain", "color": "c_yellow" },
    { "value": 20, "text": "Moderate pain", "color": "c_yellow" },
    { "value": 30, "text": "Distracting pain", "color": "c_yellow" },
    { "value": 40, "text": "Unmanageable pain", "color": "c_light_red" },
    { "value": 50, "text": "Intense pain", "color": "c_light_red" },
    { "value": 60, "text": "Severe pain", "color": "c_red" }
]
```

#### Additional context

WIP

### CODE REVIEW

**Comment by dseguin** [comment]
This is a great idea! I'm totally stealing this for #54531.

**Comment by wapcaplet** [comment]
There are several `display::*_text_color` functions directly amenable to numeric mapping like this. `health_text_color`, `pain_text_color`, and `thirst_text_color` are the most obvious ones that might work with this, since they're just a series of integer breakpoints where the text and/or color may change.

The `weight_text_color` uses a nicely abstracted `character_weight_category` namespace with constexpr numbers, so these should also be easy to convert.

The (body) `temp_text_color` function just uses some magic-number `BODYTEMP_*` constants, so those would be easy to convert as well, though a version using celsius and/or fahrenheit would be more readable in JSON.

Although `thirst_text_color` is based on a simple integer, `hunger_text_color` uses a collection of `effect_hunger_*` flags. These might be a little harder to convert, since the effects are set in `Character::update_stomach` every so often, based on a number of complicated factors - not so simple as `if hunger > 99 then "HONGRY"`.

But all things in good time, I suppose. This seems like a feature worth pursuing; although it won't really save much code, it may add a lot of flexibility.

**Comment by dseguin** [comment]
I went ahead and implemented this for the bodypart status widgets (well, partially - see https://github.com/CleverRaven/Cataclysm-DDA/pull/54531/commits/7a05a51458b6487760b2677166a5f50547eaa34d).

I'm using a phrase as a template for data-driven text, symbol and colour definitions:
```json
{
  "id": "bodypart_status_indicator_template",
  "type": "widget",
  "style": "phrase",
  "phrases": [
    { "id": "bitten", "text": "bitten", "sym": "B", "color": "yellow" },
    { "id": "infected", "text": "infected", "sym": "I", "color": "pink" },
    { "id": "broken", "text": "broken", "sym": "%", "color": "magenta" },
    { "id": "splinted", "text": "splinted", "sym": "=", "color": "light_gray" },
    { "id": "bandaged", "text": "bandaged", "sym": "+", "color": "white" },
    { "id": "disinfected", "text": "disinfected", "sym": "$", "color": "light_green" },
    { "id": "bleeding", "text": "bleeding", "value": 0, "sym": "b", "color": "light_red" },
    { "id": "bleeding", "text": "bleeding", "value": 11, "sym": "b", "color": "red" },
    { "id": "bleeding", "text": "bleeding", "value": 21, "sym": "b", "color": "red_red" }
  ]
}
```

...which gets `copy-from`'d to the bp_status widgets, and is used in the `display` functions to define how the status is displayed:

bp_status_normal

And after changing the text and symbol definitions to silly values:

bp_status_silly

Not sure if this is a use-case that you had in mind, but it works great!

**Comment by wapcaplet** [comment]
This concept is implemented quite nicely in #54693 as "clauses", so this PR is basically obsolete.

**Pull request closed without merging**
