### PR TITLE
[CR] Separating ABSTRACT, SOFTWARE, TANGIBLE from GENERIC as new types

### PR DESCRIPTION
**Pull request by int-ua**
#### Summary

SUMMARY: Infrastructure "Separating abstract, software and tangible from GENERIC JSON type"

#### Purpose of change

1. Improving readability
2. Ability to filter items by type more easily at least in Python scripts
3. Decreased likelihood that GENERIC will become a broad type of no meaning as it happened with software and abstracts.
4. Ability to make dimensions and weight mandatory.

#### Describe the solution

Adding three new types: `ABSTRACT`, `SOFTWARE` and `TANGIBLE`, the last one being a new generic for tangible items. Look into the first commit for the main part, the second one is just renaming `GENERIC` into `TANGIBLE` excluding only a few cases.

#### Describe alternatives you've considered

1. Not creating `TANGIBLE`, decided to go with it to decrease likelihood of `GENERIC` being (presumably) misused in the future.
2. Additionally renaming `GENERIC` to something like `UNSET` or `UNDEFINED`.

#### Testing

TODO

#### Additional context
See #42958 to understand what problem I'm trying to solve.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I am not sure about `ABSTRACT` - many types can have abstract when using `abstract` instead of `id`.

**Comment by int-ua** [comment]
I'm ok with leaving `abstract` items `GENERIC` if `GENERIC` will be renamed to `TANGIBLE` where appropriate.

**Comment by int-ua** [comment]
Was not approved, see Discord discussion, `#development` channel.

**Comment by KorGgenT** [comment]
https://discordapp.com/channels/598523535169945603/598535827169083403/744539312674308138

**Comment by ZhilkinSerg** [comment]
> 
> 
> I'm ok with leaving `abstract` items `GENERIC` if `GENERIC` will be renamed to `TANGIBLE` where appropriate. Although I'm not sure what the benefit is for using a separate field instead of `id` with `ABSTRACT` type.

There are abstract objects other than abstract item types (e.g. overmap terrains).

**Pull request closed without merging**
