### PR TITLE
Make Wallets spawn and put stuff in them

### LINKED ISSUE #44614: The wallets from #42108 do not spawn anywhere
# Describe the bug
The wallets introduced in #42108 where not made to spawn when the items were added.

# Steps To Reproduce

1. Make a new (or not) character. 
2. Teleport to the middle of a horde and debug kill them all.
3. Search the bodies, nobody carries a wallet.

Alternatively:

2. Teleport to the middle of a city.
3. Search every house, there are no wallets.

Or:

1. Read the code introduced in #42108.
2. Found no code relevant to spawn the wallets naturally in the world.

# Expected behavior

To see at least the not craftable wallets spawn in the world.

# Screenshots

The wallets:
wallets 1
The zombies without wallets:
wallets 2

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6459-ge49eaa0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

_Likewise, I thought I would try to add common wallets to male zombies with the same frequency that purses show up on female ones._
_- @Scrivener07_  

I saw this problem since that PR was merged, but since the author was aware of the problem, I thought I could wait for a second PR with the spawn groups... But maybe everyone forgot?
I too would like to see the wallets in the same frequency that purses.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: Content "Make Wallets spawn and put stuff in them"

#### Purpose of change

Fixes #44614 

#### Describe the solution

Add more variety of dollar bills
Make various wallet item groups
Add those groups to other groups 

#### Testing
Use the debug function to test item groups > no errors
Go through towns and kill zombies > no loose cash cards, and there wallets in their pockets
Kill zombies in lab > lots of various wallets ( probably because they used to have a lot of cash cards )

During my short test I didn't manage to find wallets in houses though, but It make some sense to find more wallet on people than laying around in empty houses

#### Additional context
I've replaced cash cards with wallets, this might have affect proportion of cash card spawn
I've also replaced most id cards with id cards in wallets

We could probably use more random stuff to put in wallets and more variety of wallets. But I think this is good enough in this state.

### CODE REVIEW

**Comment by Termineitor244** [comment]
I love it! Thank you!!! 
THIS is what I was hoping for with the original wallet PR, I like that you event went so far as to create some actual dollar bills, and the fact that is less probable to find cash cards in duck tape (poor) wallets, and even the few that you find will have way less money in them (In general) that the ones in normal wallets, but you will find more coins! And the same with the stylish (expensive) wallet! Perfect!
Oh, and the addition of the discount cards...
I'm overly excited about this PR, even if it is "just some wallets".

**Comment by Xenomorph-III** [comment]
Can we deposit paper bills in ATMs?

**Comment by faefux** [comment]
> Can we deposit paper bills in ATMs?

You should make a separate PR for that but it seems like a bad idea because ATM logic is already sketchy at best.

**Comment by Termineitor244** [comment]
Looks good! But this PR makes me wonder... Would it be fine to add wallets to the starting items of most professions? Like with the cellphones, it makes sense...

**Comment by Scrivener07** [comment]
I never got back to the original PR "soon" like I said. I only started playing again this week, congratulations on Ellison! I love the new pockets system but at the time I was still wrapping my head around using them in normal game play, and then modding with them too. I overwhelmed myself. Thanks everyone for bringing this across the finish line, and then some.

**Pull request merged**
