### PR TITLE
Remove completely unrealistic energy weapon recipes

### PR DESCRIPTION
**Pull request by Rail-Runner**
Make NX17 charge rifle and laser finger CBM uncraftable.

I doubt that even cutting-edge real-life manufacturing equipment will allow to make something like this, let alone a simple soldering iron and screwdriver. Also balances NX17 a bit: it's quite powerful and doesn't use much resources, so this change makes it harder to obtain, at least.

### CODE REVIEW

**Comment by Malkeus** [comment]
If you're making things uncraftable because they can't be made with a
screwdriver and a soldering iron, I submit that all cbm's should be
uncraftable. As I understand it, a CBM is essentially a sophisticated, self
contained surgical suite designed with everything needed to install a
specific bionic into your BODY. Each of them is a miracle of post modern
military tech that probably took billions of dollars and thousands of
people to design, and cost millions to create with all the infrastructure
of a huge corporation behind them. And another thing, afaik none of them
include something as simple as antibiotics in their crafting recipe to
prevent infection. And no survivor bathes, ever. So a self crafted cbm
should be the equivalent of sticking every filthy thing you encounter in
the cataclysm into a dirty hole in your body, which you carved with a
filthy knife, and then sewing the hole shut with a dirty needle and thread.
At least with the ones you find you can pretend like it was hermetically
sealed before you opened it. My thoughts are this: all of them or none of
them. No cherry picking.

**Comment by Shadefang** [comment]
As it is isn't it already rather hard to obtain?  Given you either need to find research notes on it in a lab, or learn the recipe from deconstructing them, which unless I'm reading the json wrong requires 9 electronics.

**Comment by Malkeus** [comment]
All the high tier electronics recipes are unrealistic by any stretch of the imagination. Every cbm recipe should include a first aid kit or other form of sterilization, blades to do the cutting for most of them, anesthetic or painkillers, articulation to do the cutting, a computer controller and a program to run it all. And some kind of magnification tool so you can see what you're doing.

**Comment by Shadefang** [comment]
I agree on the CBMs, my previous post was specifically talking about the NX17

**Comment by Malkeus** [comment]
Everything except the sterilization issues applies to the nx17 as well. There are lots of recipes that are too simplistic for their final product. I'm just trying to get the point across that singling out and removing recipes because 'laser' isn't the proper way to address the issue. Either leave it alone or address all the recipes that are 'unrealistic'. It will have to wait til after christmas, but I will attempt to improve the recipes if someone doesn't beat me too it.

**Comment by Darkyhard** [comment]
> If you're making things uncraftable because they can't be made with a screwdriver and a soldering iron, I submit that all cbm's should be uncraftable.

The problem with Laser Finger CBM specifically is not just what you said, but also the fact that laser (especially the one that would fit in a finger and would be usable for actual comat) couldn't be crafted with hand tools even if you could craft other CBMs.

As for other CBMs, their recipes have "burnt out bionic" as a component, which would make it somewhat sensible if this item includes a bionic implanting system (CBMs somehow install themselves, as far as I know: it's not a manual surgery) and some kind of interface between nerves and circuits.

Actually, I think that all of this barely makes any sense, and so I'd vote for removing CBM recipes.

> Everything except the sterilization issues applies to the nx17 as well.

The only thing that prevents you from crafting a laser by hand is that you need precisely matching parts to focus the beam, and place them equally precisely. If you place a lens a few nanometres to the either side, your laser won't work, and nobody could control their arms precisely enough to actually move them a few nanometres to the either side, no less and no more.

**Comment by kevingranade** [comment]
Just because other things are also unrealistic is no reason to hold up this
pr. We can have a follow-up pr or issue to discuss those issues.

**Comment by Cyrano7** [comment]
Ya I can see making the NX-17 uncraftable. Would be hard to just throw that together. On a side note it would be cool to have a homemade UPS charge rifle. Something not as powerful and more temperamental but still good.

**Comment by Core0verload** [comment]
>If you place a lens a few nanometres to the either side, your laser won't work at all, and nobody could control their arms precisely enough to actually move them a few nanometres to the either side, no less and no more.

And that's why humans use precision tools. A simple set of gears from N20 motor reduces 10cm of linear motion to less than 1mm. Stack ten of those gear boxes and you will get your nanometers.

Test String Please Ignore: Даркихард, это ты, космическое мудило из сс13? Если так, съеби к хуям, мне и там тебя хватило.

**Comment by Darkyhard** [comment]
> Даркихард, это ты, космическое мудило из сс13? Если так, съеби к хуям, мне и там тебя хватило.

Как будто такого уебана, как ты, кто-то просил сюда приходить. Если что-то заебало здесь - пиздуй обратно.

**Comment by Core0verload** [comment]
О, и правда ты. Ну надо ж, блять, какая нахуй встреча! Либо Интернет слишком маленький, либо ты слишком большой мудак.

**Comment by illi-kun** [comment]
@Darkyhard @Core0verload 
Gentlemen, you're not only ones who know Russian language and it's not fun at all to see your bullshit here. Watch your language and solve your issues in another place please.

**Comment by Darkyhard** [comment]
> О, и правда ты. Ну надо ж, блять, какая нахуй встреча! Либо Интернет слишком маленький, либо ты мудак слишком большой.

Мудак здесь как раз не я, а ты. Ибо доебываться до человека со своими "съеби к хуям" будет только долбоеб вроде тебя, потому что я тебе вообще не сказал ни слова. Так что иди отсюда нахуй, промудохуеблядское троепиздище, и не возвращайся, тебя не звали. Хотя нет, иди лучше не нахуй, а на форум, и пиши в ЛС, я как раз хотел тебя нахуй послать еще несколько раз за твою выебистость. А это не то место, где ты можешь свое говно изливать, так что иди либо куда я сказал, либо нахуй: одно из двух.

> Gentlemen, you're not only ones who know Russian language and it's not fun at all to see your bullshit here. Watch your language and solve your issues in another place please.

I've told him to go to "another place" already. If he isn't too dumb to keep writing here, we'll solve our issues there. Sorry for all this mess, but I absolutely can't tolerate him and his stupidness.

**Comment by scorpion451** [comment]
I'm always surprised at how many people seem to think electronics are eldritch objects which normal humans cannot replicate. You can build a small-scale version this sort of thing in your garage using the (laser diode)[https://en.wikipedia.org/wiki/Laser_diode] from an old write-enabled cd or dvd player. 
Nanometer-precision isn't necessary with any secondary lenses if you use a diode laser, because it's just boosting an existing coherent beam. The only reason that there aren't soldiers running around with laser rifles today is that we don't yet have a UPS-style power system to run them off of. All the rest of the technology has been there since physics majors cobbled the prototypes together out of c-clamps and duck tape in the 1980's... and then ran them off a refrigerator sized capacitor.

**Comment by kevingranade** [comment]
Just because the game has the power supply needed for a working laser rifle
doesn't mean constructing one becomes trivial. For one thing the referenced
bench lasers would require years of dedicated engineering to turn them into
a weaponized product, also the survivor is not at a level in all the
required disciplines to do so, even if they did have the time and resources
to do so.

To mirror your statement, I'm always surprised at how ready people are to
gloss over the thousands to millions of engineering hours necessary to turn
a working concept into a usable device.

**Comment by Darkyhard** [comment]
> I'm always surprised at how many people seem to think electronics are eldritch objects which normal humans cannot replicate. You can build a small-scale version this sort of thing in your garage using the laser diode from an old write-enabled cd or dvd player. There's a whole cottage industry of people who've combined that with some servos to make their own laser etching machines.

Yes, actually, you could assemble a thing that works similar to combat laser. The problem is that you won't get it powerful enough to make it actually worth using in combat. You can make a laser pointer for a gun or, at most, use resulting item as a firestarter, but in combat it could only harm your enemy if you point it at their eyes. MAYBE it could lightly burn their skin, but even a projectile launched from a slingshot would cause more damage while requiring much less time, skills and materials to make.

As for "compact storage" problem, I think that lasers themselves in the game are designed to be extremely efficient or something. If they weren't, they would use plutonium cells or a ridiculous amount of batteries.

It means that a makeshift combat laser, if it is possible at all to make, will be a vehicle-mounted thing that eats somewhere near 600 batteries for each shot while being as powerful as an A7 laser rifle.

> survivor is not at a level in all the required disciplines to do so, even if they did have the time and resources to do so.

Why can't they learn them, then? It doesn't look like a serious problem for a game.

**Comment by Skidborg** [comment]
How about add a component only found in labs or advanced laser weapons like a "precision lens assembly" that is required to build homemade laser weapons?

I'm not a fan of another weapon being banished to the low-chance loot lottery.

**Comment by Night-Pryanik** [comment]
>As for realism... your realize this is a game where zombies can throw bolts of lightning, right?

This is *science* fiction, after all. We don't see it IRL, but it isn't something that can't exist at all in our universe.

**Comment by kevingranade** [comment]
Science fiction is exactly what it is, "introduce a small number of
mechanics not known to modern science, and extrapolate how these would
affect a situation where everything else behaves as expected".
The zombies and laser guns are superscience entities you can only interact
with in limited ways, only modern technology can be interacted with fully,
and that is limited by what is feasible for a lone survivor.

**Comment by Soadreqm** [comment]
I don't think laser weapons in general are too unreasonable. This was a society where both lasers and portable power supplies were relatively common. It's just a matter of finding a big enough beam source, connecting it to a big enough power source, and maybe rigging together some kind of cooling system so your laser doesn't melt. Not necessarily easy, but not impossible either.

Fitting one inside your finger, though, is right out. There's precision engineering, and then there's molecular fucking construction. Even the pre-cataclysm laser sources you might be able to scavenge aren't going to be designed for concealing inside the human body, except the ones specifically made for bionics.

**Pull request merged**
