### PR TITLE
Steel working [CR]

### PR DESCRIPTION
**Pull request by mugling**
Steel is, and should remain, a readily available resource but in our current implementation it is too easily workable and has a number of inconsistencies.
#### Steel is too light

`weight` and not `volume` should be the limiting factor as to how much a player can carry. You can readily fit several ingots in a backpack but it would be to heavy to lift. This PR adjusts the density of steel in a similar manner as #17183 did for lead.

Solid ingots should have a higher density than assorted fragments of scrap but they should have the same magnitude. `scrap` should be relatively low `weight` to provide for sufficient granularity without needing to rescale all the JSON definitions:

| item | weight (g) | stack_size | old density | new density* |
| --- | --- | --- | --- | --- |
| scrap | 50 | 10 | 0.45g/cm³ | 2.0g/cm³ |
| chunk | 250 | 4 | 0.68g/cm³ | 4.0g/cm³ |
| lump | 1000 | 2 | 2.7g/cm³ | 8.0g/cm³ |

`*` Density of mild steel is 7.6g/cm³
#### Steel working tools are inconsistent

We currently have a lot of inconsistencies both as to the abilities of various tools and the number of of relative `charges`. In particular welders are for joining preformed parts and are not usable for either forging or (excluding the `oxy_torch`) cutting steel.

| item | welding | soldering | cutting | forging* |
| --- | --- | --- | --- | --- |
| welder | 100 |  |  |  |
| makeshift welder | 150 |  |  |  |
| actetylene torch | 20 |  | 10 | 20 |
| electric forge |  |  |  | 20 |
| charcoal forge |  |  |  | 20 |
| soldering iron |  | 10 |  |  |
| bionic toolset | 100 | 10 | 20 |  |

`*` Cost to forge a signle `steel_chunk`
#### Scrap metal is far too useful

It should be plentiful but where a recipe calls for `steel_lump` or `sheet_metal` then `scrap` should only be a valid alternative where the recipe already calls for a `forge`. We need to make more use of `wire` or `sheet` instead of an arbitrary quantity of `scrap`:

| item | components | small tools* | large tools | frames |
| --- | --- | --- | --- | --- |
| scrap | ✓ |  |  |  |
| chunk |  | ✓ |  |  |
| lump |  | ✓ | ✓ | ✓ |
| sheet |  | ✓ | ✓ |  |
| wire | ✓ | ✓ | ✓ |  |

`*` hand tools weighing less than 0.5kg
#### Mass is not always conserved

For items that are largely composed of steel their crafting requirements should match their `weight`. In particular this should be enforced for frames and other large steel constructions.

Using the values at the start of this PR gives us a granularity of 50g and combined with the above table should allow us to achieve some consistency

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> It should be plentiful but where a recipe calls for steel_lump or sheet_metal then scrap should only be a valid alternative where the recipe already calls for a forge. We need to make more use of wire or sheet instead of an arbitrary quantity of scrap:

Having to craft scrap into chunks/lumps/sheets first would be just plain tedious as long as the recipe requires a welder/torch/forge.

> stack_size

Do test out if it works. It may require altering `count_by_charges`.

**Comment by Rivet-the-Zombie** [comment]
>In particular welders are for joining preformed parts and are not usable for either forging or (excluding the oxy_torch) cutting steel.

You can totally use an oxyacetylene torch as a heat source when working on small forge projects, though you're right about electric-powered welders being no good for such tasks (it might be possible to fake it with TIG on a small task, but that's about it).

**Comment by mugling** [comment]
> Having to craft scrap into chunks/lumps/sheets first would be just plain tedious as long as the recipe requires a welder/torch/forge.

Sheet's shouldn't be craftable at all with the equipment available to the average survivor (92eb480) but they're not exactly in short supply from wrecks.

I'd like to rework crafting so that we can have arbritrary combinations of tools and components, for example `scrap + forge` or `steel_lump` however in the interim a simple solution is for recipes that don't strictly require a forge to add a `suffix: forged` recipe that allows the use of `scrap`

**Comment by mugling** [comment]
> You can totally use an oxyacetylene torch as a heat source when working on small forge projects, though you're right about electric-powered welders being no good for such tasks (it might be possible to fake it with TIG on a small task, but that's not worth worrying about here).

I've no significant experience with oxy. Do you want to propose a value for `charges` for the above table?

**Comment by mugling** [comment]
> Do test out if it works. It may require altering count_by_charges.

Yes, it works correctly. Smashing a vehicle even yields the proportionally correct amount of scrap. The only significant adjustments are where recipes specify both `scrap`, `steel_chunk` and `steel_lump` as the relative proportions have changed.

**Comment by Coolthulhu** [comment]
> Yes, it works correctly. Smashing a vehicle even yields the proportionally correct amount of scrap.

Does it stack as `stack_size` directly implies?

**Comment by mugling** [comment]
> Does it stack as stack_size directly implies?

Yes, you get `scrap metal (3)`

**Comment by Rivet-the-Zombie** [comment]
>I've no significant experience with oxy. Do you want to propose a value for charges for the above table?

It would need at least as much as you'd require to weld a similarly-sized piece of steel, likely more.

**Pull request merged**
