### PR TITLE
Several skin mutations now allow for installation of Alloy Plating CBM

### LINKED ISSUE #63229: Pale Skin prevents installation of alloy plating CBMs
### Describe the bug

It seems that the mutation 'Pale Skin' prevents the installation of certain CBMs, including alloy plating. I haven't been able to test too many different combinations as in my current world Rubik only has arm alloy plating for sale at the moment, but it does not let me install it unless I debug away pale skin. The message it gives is 'not compatible with patient's body'.

Funnily enough, full on Albino seems to work fine!

### Steps to reproduce

1. Make a player with Pale Skin
2. Go to Rubik and try to install an Arm Alloy Plating CBM

### Expected behavior

I expect that the paleness of my character's skin shouldn't impact the ability to put metal plates under it!

### Screenshots

With Pale Skin...

image
image

Without...

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: c033542 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Bugfixes "Several skin mutations now allow for installation of Alloy Plating CBM"

#### Purpose of change
Pale skin forbidding installation of the Alloy Plating was done in #47117. The reason was:
>Skin mutations don't work when you remove your skin for superalloy

But as far as I can tell from Alloy Plating description, you're not replacing your skin with superalloy, you're weaving it into muscles, i.e. under the skin. The very skin is left untouched.
https://github.com/CleverRaven/Cataclysm-DDA/blob/ec0b7961f41ee3926afc9ae45a8e5a1d047f4487/data/json/bionics.json#L60

The conceptual change (from completely replacing your skin to subdermal mesh) was done in #51578. Thus several skin mutations, which are mostly "cosmetic" ones, shouldn't forbid installation of subdermal mesh under the skin.

* Closes #63229.

#### Describe the solution
Removed the following mutations as blockers for installation of Alloy Plating CBMs:
- `Thick skin` and `Thin skin`. These are only slight changes to skin thickness, and shouldn't interfere with the mesh;
- `Pale` and `Spots`. These are just a cosmetic effect.
- `Solar sensitivity`. Total lack of pigment in the skin shouldn't interfere with the mesh under it.
- `Smooth skin`, `Rashy skin`, and `Peeling skin`. These are mostly cosmetic effects.

#### Describe alternatives you've considered
Not alternative, but addendum to the list. There are many other mutations that in theory shouldn't interfere with the subdermal mesh, such as `Furry` or `Chloromorphosis`. The first one is "on the skin"-type of mutation, the second one is a "intradermal"-type, both of which shouldn't interfere with subdermal bionic. But I decided not to touch these fine matters in this PR and go for the low-hanging fruit.

#### Testing
Got Pale mutation. Debug-spawned autodoc. Debug-spawned Arms Alloy Plating CBM. Activated the autodoc, noticed that my Pale mutation doesn't forbid me from installing the CBM anymore.

#### Additional context
None.

### CODE REVIEW

**Comment by Maddremor** [comment]
Consider changing the description instead since we do want a metal exterior at some stage anyway, and the word "plate" implies larger rigid sections of armor.

**Comment by Night-Pryanik** [comment]
I don't understand, what do you mean by "instead"? Revert my changes and refluff CBM to be a some sort of metal coating over the skin?

**Comment by Maleclypse** [comment]
> I don't understand, what do you mean by "instead"? Revert my changes and refluff CBM to be a some sort of metal coating over the skin?

I think Madds is saying we want heavy cyborgs to have Alloy plating instead of skin in the future but that would be a different item.  So in this case we should rename this cbm to something more clear that it's under skin.  Like Subcutaneous Vital protection. 

Cause like you are saying someone with this should still mostly pass as human and it not be extremely visible to the naked eye versus a fully chromed cyberwarrior.

**Comment by PatrikLundell** [comment]
I agree the current name of the CBM is misleading. I'd propose something like Subcutaneous Protective Mesh CBM.

And yes, fur, scales, etc. ought to be compatible with a mesh.

I also agree there ought to eventually be an actual plating as well, but that's a different addition (and both should be possible to have at the same time). The next step (probably quite a long time away) would be mechanical replacement body parts which would replace these kinds of integrated CBMs, as all the biological parts of that body part would be replaced (unless the part is the head, since the brain would still be retained).

**Comment by Night-Pryanik** [comment]
Ok, changed names of CBMs as items and as bionics.

**Pull request merged**
