### PR TITLE
Potentially fix broken build - DO NOT MERGE

### PR DESCRIPTION
**Pull request by prharvey**
#### Summary
None

#### Purpose of change

Build is broken due to a segfault on exit when running tests.

#### Describe the solution

This might be the culprit, but I cannot reproduce the issue on my local machine, so I hacked something together to run through the build matrix to check if this is actually the issue.

DO NOT MERGE YET

### CODE REVIEW

**Comment by GuardianDll** [comment]
fyi for draft PRs only part of the tests are run

**Comment by prharvey** [comment]
> fyi for draft PRs only part of the tests are run

Yeah I know, I just don't want the tests to get blocked by a linter issue or something so I'm waiting for the cheap tests to run first.

**Comment by akrieger** [comment]
You could always edit the workflow file so the asan build is the only thing that runs.

**Comment by andrei8l** [comment]
This is only relevant for monsters right? Would it not be better to move `remove_creature_from_reachability()` to `monster::on_unload()` instead of the creature destructor?

**Comment by prharvey** [comment]
> This is only relevant for monsters right? Would it not be better to move `remove_creature_from_reachability()` to `monster::on_unload()` instead of the creature destructor?

I believe NPCs are also stuck in shared_ptr. I'm not advocating for this to be the correct fix (although something close to this might be), I just wanted to do the easiest thing to check if it actually changed anything.

**Comment by prharvey** [comment]
Superseded by #69368

**Pull request closed without merging**
