### PR TITLE
Draw fields based on intensity

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Infrastructure "Drawn fields now use field intensity"

#### Purpose of change
Currently when fields are drawn they don't account for field intensity. This means that though we have multiple levels of gore, for example, none of the specific colors and icons for ascii will be displayed (instead defaulting to the intensity 0 json settings) and different sprites can't be used for different levels. 

#### Describe the solution
Added a new getter function for fields that gets the displayed fields current intensity value.
This is called to get intensity when drawing a field and the intensity value is passed into the draw_from_id_string() function.
 This value is used when querying if there is a tile in the tileset of that name.

With that said now a tileset can specify sprites for intensity of a field by giving them ID: [basefield_ID]_int[intensity_level] (eg: fd_blood_int1).
Intensity 0 is still just ID: [basefield_ID] as not to break anything with current tilesets and if no specific intensity tile exists it will try to get the tile for intensity 0.

Also the new system still works with multitile.

#### Describe alternatives you've considered
The logic for getting intensity could be moved into draw_from_id_string() but it would be a bunch of additional situational logic that would bloat it. 

There are a bunch of ways naming could work for this. I'm happy to change mine if a maintainer envisions this working differently. 

#### Testing
I threw together some custom Ultica sheets to give myself some filler tiles for different levels of blood to make sure it renders correctly. Also did some testing to make sure failing to find an intensity tile wouldn't keep the system from rendering the tile in question. 

#### Additional context
here is a puddle of blood using a not finished blood intensity sprite
image

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
alright I missed the astyle bit in the contributing guide so I'm going to style my code and I think I need to add severity options for override fields.

**Comment by Aivean** [comment]
I'm of two minds regarding this change. I can see where it can be useful, but at the same time it introduces some technical debt:
* adds another parameter to the `cata_tiles::draw_from_id_string` method that already has 9 (!) parameters
* adds another expensive hash map lookup in `draw_from_id_string` (I believe most of the fields won't have the intensity-specific version and will fall back to the default sprite, so two lookups instead of one)

I don't think that items above could or should be addressed in this PR. This is just something to have in mind.

However, one thing could make future improvements easier:  add some unique prefix to the "intensity_level" suffix: 

* instead of  `[basefield_ID]_[intensity_level]` (eg: `fd_blood_1`)
* use something like   `[basefield_ID]_int[intensity_level]` (eg: `fd_blood_int1`)

The reason behind this is that in the future, to negate the performance hit from multiple tile ids lookups with fallbacks, we'll have to pre-parse sprite ids, and doing that will be easier if some unique prefix is present.

**Comment by bombasticSlacks** [comment]
sure that's an easy enough addition.

**Comment by actual-nh** [comment]
Regarding the hash map lookup: What is the reason for the expense? Would it be less expensive to do a precheck (set membership) for whether something is a key in the hash, if failed lookups are common?

**Comment by Aivean** [comment]
> Regarding the hash map lookup: What is the reason for the expense? Would it be less expensive to do a precheck (possible set membership) for whether something _may_ be a key in the hash, if failed lookups are common?

The problem is: 
1. string key construction 
2. lookup in the hash map by string key

Hash map lookup by string key reads a random chunk of memory (hash table bucket) and compares string(s) stored there against the key. With the current implementation, if there are many field types present on the map with random intensity, these lookups will potentially result in many CPU cache misses.

For example, take a look at #44917, where eliminating one lookup increased FPS by ≈15%. 

However, I must admit, with how fields are used currently (usually they don't cover a significant portion of the map), this may not be a real problem. Although, this could become one when something like `fd_snow` is added: #46559.

**Comment by actual-nh** [comment]
> > Regarding the hash map lookup: What is the reason for the expense? Would it be less expensive to do a precheck (possible set membership) for whether something _may_ be a key in the hash, if failed lookups are common?
> 
> The problem is:
> 
> 1. string key construction
> 2. lookup in the hash map by string key
> 
> Hash map lookup by string key reads a random chunk of memory (hash table bucket) and compares string(s) stored there against the key. With the current implementation, if there are many field types present on the map with random intensity, these lookups will potentially result in many CPU cache misses.
> 
> For example, take a look at #44917, where eliminating one lookup increased FPS by ≈15%.
> 
> However, I must admit, with how fields are used currently (usually they don't cover a significant portion of the map), this may not be a real problem. Although, this could become one when something like `fd_snow` is added: #46559.

Possibly ids could be split - probably by `_` - and looked up hierarchically? This might be best done after an initial quick lookup for whether it's possible the full thing is in the system (there's a hashing technique - I can't remember the name - that turns on bits in a (small) array to tell whether it's possible something is present as a key; hash collisions result in some false positives, but never false negatives).

**Comment by Aivean** [comment]
Maybe we could move this discussion to a separate issue/discussion? It becomes less related to this PR.

> This might be best done after an initial quick lookup for whether it's possible the full thing is in the system (there's a hashing technique - I can't remember the name - that turns on bits in a (small) array to tell whether it's possible something is present as a key; hash collisions result in some false positives, but never false negatives).

That's called a bloom filter and I'm not sure it will be a good fit for this problem.

> Possibly ids could be split - probably by `_` - and looked up hierarchically? 

Yes, I think that something along these lines could be a solution. 

Basically, when loading the tileset, all ids could be split into parts: some of them are prefixes and suffixes (like 'vp_', '_int1', '_season_summer'...) , and others are ids of entities (`t_tree`, 'f_table'...). Then these parts are interned (converted to `int`, potentially using `string_id`). 

The actual structure to store tiles would have two layers of hierarchy:  `unordered_map<key1,  map<key2, value>>`.  

* `key1`  is `vector<interned_parts>`, but it only consists of the subset of parsed parts without common prefixes and suffixes.
* `key2` is also `vector<interned_parts>`, but it consists only of parts that are prefixes and suffixes
* `key1` and `key2` are disjoint sets that together form the original tile key


Alternatively, inner `map<key2, value>>` could be replaced by a `flat_map` variant.

The idea is that for tile lookup only single lookup in `unordered_map` happens. After that all subsequent fallback lookups are performed on a "hot" localized memory.

**Comment by actual-nh** [comment]
> Maybe we could move this discussion to a separate issue/discussion? It becomes less related to this PR.
> 
Sure. Where? Discussions or issue?

**Comment by ZhilkinSerg** [comment]
Let's move it to post-0.F

**Comment by Night-Pryanik** [comment]
@bombasticSlacks could you please resolve conflicts?

**Comment by bombasticSlacks** [comment]
I'll have time early this week to update. Currently my dev environment is out of commission

**Comment by bombasticSlacks** [comment]
Trying to just eyeball fixing the conflicts I still need to test the system and make sure everything still works

**Comment by actual-nh** [comment]
I note in field.cpp's add_field:
```
it->second.set_field_intensity( prev_intensity + new_intensity );
```
Plus? Not max? OTOH, the age is only updated if the old field is about to be removed?

**Comment by bombasticSlacks** [comment]
alright I've ran the code locally with some mockup blood tiles for intensity and it is working
image

I'm not sure why it is failing on Ubuntu with Clang 12

**Comment by actual-nh** [comment]
The failure is happening with tests on at least one other (completely unrelated and JSON-only) PR, #49899, so it isn't related.

**Comment by Night-Pryanik** [comment]
@bombasticSlacks could you please resolve conflicts?

**Comment by bombasticSlacks** [comment]
@Night-Pryanik It's tested and working now. The failing check seems to be happening to all recent C++ pulls.

**Pull request merged**
