### PR TITLE
Implements integral_volume for gun mods.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**

### CODE REVIEW

**Comment by mugling** [comment]
Somewhat related it might be worth adding a sanity check that `integral_volume <= volume`

**Comment by mugling** [comment]
More of a tangent, if I implement `stock_length` would you be able to add some suitable values @Rivet-the-Zombie so we don't start to get odd results from potential interactions between `magazine_well`, `integral_volume` and `barrel_length`?

**Comment by Rivet-the-Zombie** [comment]
With a sawed off stock option and everything? Yeah, I'd be happy to.

**Comment by mugling** [comment]
Yup, wood saw or hacksaw? Possibly chosen based upon material?

**Comment by Rivet-the-Zombie** [comment]
Honestly I'd just go with the hacksaw. Even wooden stocks have often got a length of bolt that runs through them that you'd need it for anyway.

**Pull request merged**
