### PR TITLE
Updated JSON_FLAGS.md

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Updated and sorted alphabetically ammo types and armor.

### CODE REVIEW

**Comment by DavidKeaton** [comment]
often overlooked, very helpful!

**Comment by BevapDin** [comment]
The list of ammo types should probably be removed, it's now entirely defined in json, see data/json/items/ammo_types.json - why keep two identical lists around?

**Comment by KA101** [comment]
It can be, but for folks looking to become familiar with the code, reference files are handy.  A line about "these are mainline ammo types that the game handles, or you can whip up your own via editing ammo_types.json" might improve this, and I can add one in the merge if Night-Pyranik doesn't beat me to it.

(Just make sure you post if you do, so we don't both alter the file and screw up poor Git!)

**Comment by BevapDin** [comment]
The list in the documentation gives some ammo types different names than the json files does, this can be irritating when users search for the "66mm HEAT" ammo, but the game only displays "High Explosive Anti Tank warhead":

ammo_type_id - "Name in doc" - "Name in json"
66mm - "66mm HEAT" - "High Explosive Anti Tank warhead"
120mm - "120mm HEAT" - "High Explosive Anti Tank warhead"
223 - ".223 Remington" - ".223"
etc.

Those should be synchronized either in the documentation or the json.

**Comment by KA101** [comment]
Synch would be good but can wait for another PR.

**Comment by Night-Pryanik** [comment]
@KA101 I don't mind.

**Pull request merged**
