### PR TITLE
Remove Military Professions mod

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove Military Professions mod"

#### Purpose of change

The military professions mod has been obsoleted for about 3 years now, has no maintainers, and also has a bunch of redundant professions such as sniper, breacher, automatic rifleman. The unique ones it does have are just those professions, but better. This does not add much of a curated experience, and as such does not qualify to be an inrepo mod. 

#### Describe the solution

Removes it. 

#### Describe alternatives you've considered

Haven't.

#### Testing
Ain't there no more!
image

### CODE REVIEW

**Comment by DSeyka** [comment]
Will the game load for people using this profession on their current character?

**Comment by Karol1223** [comment]
> Ain't there no more!

...was it there before? This thing has been obsolete for ages, has it not?

**Comment by Holli-Git** [comment]
> > Ain't there no more!
> 
> ...was it there before? This thing has been obsolete for ages, has it not? It's not been able to be added to a savefile at least since 0.F

I wasn't sure what to put there tbh

**Comment by Holli-Git** [comment]
> Will the game load for people using this profession on their current character?

Possibly? It'll throw an error for a mod not being there, but the mods been obsolete for 3 years, I'm unsure why someone would still be using the mod for that long after it's obsolete

**Comment by sonphantrung** [comment]
> Will the game load for people using this profession on their current character?

One thing: This mod has been mainlined long ago at #60135

**Pull request merged**
