### PR TITLE
Big Gun ammo audit for longest_side

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

``SUMMARY: Bugfixes "Fix wrong lengths for large ammo"``

#### Purpose of change

Helps #37374.

#### Describe the solution

Add longest_side according to length of the cartridge according to sources in Additional Context.

#### Describe alternatives you've considered

None.

#### Testing

Loading ingame, looking at ammo the field was applied to as well as those that copy from it.

#### Additional context

66mm HEAT: https://en.wikipedia.org/wiki/M72_LAW#Rocket

M74 Rocket: http://www.designation-systems.net/dusrm/app4/m74rocket.html

RPG-7: https://www.gunandsurplus.com/Inert-Ordnance-Rounds/Bulgarian-PG7-HEAT-Rocket-For-RPG-7-Launcher-INERT-Complete

BGM-71F: http://www.military-today.com/missiles/tow.htm

40x46mm(added a base volume for this from M433's length since they didn't have one): http://www.inetres.com/gp/military/infantry/grenade/40mm_ammo.html

40x53mm: https://www.gd-otscanada.com/product/40mm-x-53-ammunition/

### CODE REVIEW

**Comment by kevingranade** [comment]
What is specifying this accomplishing?

**Comment by LaVeyanFiend** [comment]
All bullets show as 6.2 cm long, due to the default length formula using the 250ml volume from a stack of whatever is specified.

**Comment by kevingranade** [comment]
So the launcher ammo makes sense, but that doesn't answer the question for the small arms ammo.  I'm not really interested in having extra fields added to a large number of items that has no practical outcome.

If there is one and I'm missing it, let me know, but I'm not seeing anything.

**Comment by LaVeyanFiend** [comment]
Undoing the fields for small arms then.

**Pull request merged**
