### PR TITLE
Revert "Process of adding Whaley's Locations (1 of 9)"

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Reverts CleverRaven/Cataclysm-DDA#24866

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
So should I just start fresh with a new PR?

**Comment by Qrox** [comment]
I think we should tackle this carefully. From some reading of the git document, reverting merges will cause all weird things to happen. I think a PR reverting the revert commit in #24866 should be done first, and then we take care of whatever mess caused by the last merge in #24866 mentioned by @cosmiccoincidence .

**Comment by ZhilkinSerg** [comment]
We just revert whole PR with bad commit(s) as it shouldn't be merged in its current state. New PR with good changes shoild be created later.

It is possible to fix without revert with PR reverting only bad changes, but I cannot manage this right now.

**Comment by cosmiccoincidence** [comment]
Sorry about that, in the next day or two I will ~~fuck up~~ _make_ another PR.

**Comment by cainiaowu** [comment]
Well, your local git branch should have a full git history for each commit you make, you can checkout the branch with the change and try to rebase on current master. Source tree is highly recommended to understand the relation graph.

```
 -----split-----------------------\-------MASTER
           \----(your old change)--\(merge_from_master)-(fucked up revert)-(you were here)
```
see this for more info.
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by cosmiccoincidence** [comment]
I'm really new to github in general, hence why I'm using github desktop.
After reading a bit in your link, I understand the logistics of rebasing and understand it's easier (less work) to rebase that to re-do my branch by hand, but it seems to be a bit over my head still. I can do this by hand with looking at my commit history and creating temporary files from these commits and re-adding them to a new branch. It will take me 20 or so minutes but honestly it's simpler (for me) to understand.
Also I downloaded Sourcetree and made an account on bitbucket.org, but when launching the Sourcetree app I'm asked for my username and "Root URL". I'm not sure what it means by "Root URL".
Thanks for the help, @cainiaowu.

**Comment by cainiaowu** [comment]
The root URL is where your remote repo is located, for you should be https://github.com/cosmiccoincidence

Also you dont need the bitbucket account at all, you can edit your host setting to github so it will use your github account to login into remote repo.

**Comment by cosmiccoincidence** [comment]
Ok, thats what I thought (and tried), but I seem to be getting an error with it.

untitled

**Comment by cainiaowu** [comment]
Emm, can you try an old version like 2.0? It seems that they have changed a lot of things

**Comment by cosmiccoincidence** [comment]
I'm not sure, I downloaded the latest version the first time... also when googling sourcetree 2.0 every link ends up taking me to the latest download page again.

And not being able to even login to this is quite discouraging...

**Comment by Zireael07** [comment]
https://confluence.atlassian.com/get-started-with-sourcetree/install-sourcetree-847359094.html

https://community.atlassian.com/t5/Bitbucket-questions/What-is-the-Root-URL-for-SourceTree-App/qaq-p/785896

The second link should be more helpful. Basically you've gone down the wrong option (you should be asked for Atlassian credentials not Bitbucket Server)

**Pull request merged**
