### PR TITLE
Removes obsolete mods.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
Can we just get rid of these now?

They've not been necessary for quite a while.

### CODE REVIEW

**Comment by kevingranade** [comment]
The obsolete flag in them prevents the game from throwing warnings when a savegame referencing the mod is loaded.
What I'd like to do is make an obsolete_mods.json somewhere that just has a list of the mod names that has the same effect, just a little more compact.

**Comment by Rivet-the-Zombie** [comment]
Is it really that important that we support savegames from 0.8 or so?

**Comment by kevingranade** [comment]
Lemme poke at them, in the bad case the reference to the mod sticks around in the saves, so any saves that started in 0.8 will be affected.  In the good case the code discards the obsolete references once the same is loaded, in which case this'll be fine.

**Comment by KA101** [comment]
Any updates?

**Comment by kevingranade** [comment]
Just loaded an old save that had the medieval mod activated, we don't seem to clear the obsolete mods from the list, so if someone was using one of these mods at any point it's still there in their file.
What I'd like to do is compress these guys into a small blacklist in a single file so it's not cluttering things up, and add a piece of logic to remove obsolete mods from saves when they're loaded, then plan on clearing the old mods from the obsolete list next release.

**Comment by KA101** [comment]
Thanks.

**Pull request merged**
