### PR TITLE
Add a simple draw benchmark in the debug menu.

### PR DESCRIPTION
**Pull request by DanmakuDan**
This is a small benchmark idea for ~~SDL~~ builds that has utility in comparing performance after possible changes to the rendering process. It will try to call the main draw() call continuously for 5 seconds and report the average fps observed. Generally, the fps will be dependent on how many tiles onscreen are being rendered.

fps_example0

fps_example

### CODE REVIEW

**Comment by mugling** [comment]
Could we instead have an fps display in the sidebar for debug builds? This might help developers better spot when a PR has caused a slowdown?

**Comment by mugling** [comment]
BTW working on game performance is very much appreciated

**Comment by Coolthulhu** [comment]
Would it be possible to generalize it not to depend on SDL?
It would be useful for testing general drawing too. Plus, it takes debug menu entry anyway.
It would probably be sufficient to just use a more general method of taking ticks.

**Comment by DanmakuDan** [comment]
> Could we instead have an fps display in the sidebar for debug builds?

SDL FPS is hardcoded to 40 max (1000 ms / 25 ms interval variable), there should be a FPS option added so that a FPS display is useful for faster computers.

> Would it be possible to generalize it not to depend on SDL?

This PR was updated to remove the SDL calls.

**Pull request merged**
