### PR TITLE
Make meditating an activity

### PR DESCRIPTION
**Pull request by sethsimon**
It takes 2000 moves (2 minutes), and a lot can happen in that amount of time.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
We have a lot of activities now. It would be a good idea to move away from the enum approach, because it's inflexible and clunky.

**Comment by mugling** [comment]
JSONify?

**Comment by codemime** [comment]
Polymorphic classes would provide the flexibility we need. I believe @Coolthulhu meant them.

**Comment by Coolthulhu** [comment]
Even just a `iuse` like system, with json structures addressing hardcoded functions by name.

Look at the size of this PR - most of it is just definitions. Having a json system for it would mean changing 2 code files and 1 json instead of 5 code files.

**Comment by sethsimon** [comment]
I agree, and I like Coolthulhu's  idea of an iuse-like system. The only major differences between all the activities are their `do_turn` and `*_finish` functions, and conditions for resuming the activity- those could be handled by `player_activity_actors`, for lack of a better name. The other differences, such as whether you're rooted during the activity, whether it's based on time or speed, if it's suspendable, etc. would be natural to specify in JSON.

**Pull request merged**
