### PR TITLE
Vehicles shouldn't collide with hallucinations

### LINKED ISSUE #19970: You can crash into hallucinations with a vehicle.
Been trying to back up my APC, before i managed to get it to move, a hallucination of a racoon appeared behind it. The APC wouldn't gain any speed untill the hallucination dissapeared due to ramming into it.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes  #19970.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
They shouldn't phase through them either.

**Comment by Night-Pryanik** [comment]
> They shouldn't phase through them either.

Why? I find this behavior appropriate. 
How do you see it?

**Comment by Coolthulhu** [comment]
Instakill every hallucination collided with.

**Comment by Night-Pryanik** [comment]
>Instakill every hallucination collided with.

While I'm not against your proposal, I'd like to hear other opinions.

**Comment by kevingranade** [comment]
That's how we handle hallucinations in general, once you interact with it,
it proves it's not real, so we just remove it.

**Comment by Coolthulhu** [comment]
The most "sensible" option would be to have collisions be pushed back as real critters, but without actually affecting the vehicle. Save the vehicle values that would change, simulate the collision on saved values, then save changed values if it's not a hallucination or discard them if they are. You'd still need to handle bike ramming into hallucinated hulk, by instakilling hallucinations that the vehicle can't push away.
But that would be an overkill - hallucinations are too easy to figure out and specialcasing them in vehicle code would be more work than it is worth.

If you want the phasing to stay, you shouldn't specialcase it, but rather remove the `true` second argument in `g->critter_at` above.

**Comment by Coolthulhu** [comment]
The current version of this PR is totally broken.

**Comment by Night-Pryanik** [comment]
Why?

**Comment by Coolthulhu** [comment]
Ram a tree and see what happens.

**Comment by AMurkin** [comment]
That was `if( critter != nullptr )`?

**Comment by Night-Pryanik** [comment]
What "that"?

**Comment by AMurkin** [comment]
The reason why this PR is totally broken, i guess.

**Comment by Coolthulhu** [comment]
You've got the order of checks inverted and additionally aren't handling cases that aren't critters. This is why it breaks.

**Pull request closed without merging**
