### PR TITLE
Add some reputation-related events

### PR DESCRIPTION
**Pull request by MNG-cataclysm**
#### Summary
Content "Begin adding some reputation-related events"

#### Purpose of change
#63815 and #63919 added some ways to use and alter faction standing in EOCs. This PR begins to add some world consequences based on the player's standing with existing factions.

#### Describe the solution
If you become sufficiently disliked by a faction beyond outright hostility, they will begin to make efforts to try and kill you. The Hell's Raiders will send thugs after you, in increasing numbers depending on how far out of favor you are. The Old Guard will consider you a high-priority target and send a kill team of two, heavily armed and skilled fighters. The Exodii and Hub 01 will attempt to kill you using a bomb, which can wreck player bases and even destroy vehicles. These will only occur every 1-2 weeks, and NPC fighters will not arrive in portal storms or in certain areas, such as faction bases. 

#### Describe alternatives you've considered
Not adding this, lowering the firepower of these events, or increasing the time between them.

#### Testing
I decreased my standing with these factions significantly and waited a while. Everything works as intended.

#### Additional context
All of these events require significant effort on part of the player to decrease standing that much. If needed, the requirements could be increased.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
Wait isn't Hub01 always an archenemy for weird technical reasons? Won't they just insta bomb you immediately?

**Comment by andrei8l** [comment]
How are they tracking you?

**Comment by MNG-cataclysm** [comment]
> Wait isn't Hub01 always an archenemy for weird technical reasons? Won't they just insta bomb you immediately?

Yes, they would. I've set the EOC condition for them to a new low, which exceeds that they have set as a default, so you won't instantly die.

**Comment by MNG-cataclysm** [comment]
> How are they tracking you?

Drones, bounty hunters, private eyes, mainly traditional investigation methods.

**Comment by andrei8l** [comment]
>  mainly traditional investigation methods.

They show a picture of you to the zombies and ask which way you headed last?

**Comment by actually-the-artificer** [comment]
shouldn't these stop at some point? Like if you wipe all their best dudes they just give up?

**Comment by MNG-cataclysm** [comment]
> shouldn't these stop at some point? Like if you wipe all their best dudes they just give up?

It seems to me that killing their best members would only empower the faction in question to continue sending assassins after you, and possibly redouble their efforts to kill you, as you would exemplify your danger to them. The attacks would only stop through peace negotiations; they could bargain with you after some number of assassins fail to kill you, or by you reaching out first.

**Comment by actually-the-artificer** [comment]
Ah; I was talking about the fact that they should at some point run out of people to throw at you. Especially for the smaller factions.

**Comment by Naadn** [comment]
I think factions should have stop loss point once they send a few bubbly and all of them didn't come back. As long as player don't mess them again they will stop bothering you.

**Pull request merged**
