### PR TITLE
helipad.json: Use barbed wire fence

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Balance "Replace chain link fence with barbed wire fence"

#### Purpose of change

This is a secured military building. It should use barbed wire fence instead of a regular chainlink fence.

#### Describe the solution

Just replaces a single entry in the palette.

#### Describe alternatives you've considered

I don't know really. I considered to just leave it be because it has turrets, why would it also need barbed wire but this is the military and there is the Cataclysm going on. Defence in depth is a thing after all.

#### Testing

Applied the change locally. Travelled until I found a helipad. All chainlink fence has been correctly replaced by its barbed wire equivalent.

#### Additional context

n/a

### CODE REVIEW

**Comment by Maleclypse** [comment]
Wouldn’t you have the barbed wire outside of the chainring fence for two layers of defense.

**Comment by NetSysFire** [comment]
So I just looked at the fence types with other tilesets and it looks like a barbed wire fence is just barbed wire between posts, not just an upgraded chainlink fence with barbed wire on top. imho this should be a separate object but it might be non-trivial to implement since it blocks climbing in some cases and is much higher than these small fence posts.

So yes, putting barbed wire on the ground in front of a chainlink fence with barbed wire on top makes more sense if this gets implemented.

**Comment by Shodan14** [comment]
Might be good to have a stronger [razor wire](https://en.wikipedia.org/wiki/Barbed_tape) fence for official stuff to differentiate it from the flimsy farmyard stuff.

**Comment by NetSysFire** [comment]
I agree, but this is out of scope for this PR. There have been some discussions in the IRC and forums about this and it really does make sense to add this for many buildings.

**Pull request merged**
