### PR TITLE
Add a proper way to produce planks and beams with stone tools

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Add a proper way to produce planks and beams with stone tools"```
#### Purpose of change

As Kevin mentioned in #32765, the proper way of woodworking with stone tools would be to make a wooden beam from logs and then work from that (to make a dugout canoe or similar), or to work a whole log into one plank-shaped wood piece if you really want planks. This PR implements that, also resolving one of the bottlenecks in wilderness-only plays, though one would still need nails to make use of recipes which need necessarily planks and not sticks.

Wooden beam recipe has been changed to allow stone axe and to also require a wood sawing tool (an adze would do) to smooth it at least a bit by more accurately removing branch stumps. The beam itself is still useless at the moment if you don't have metal tools to work with it, but I guess at least being able to make it is an imporvement.

I also noticed that some woodworking recipes don't show up in subcategories at all; so I added subcategory entries to them and fixed that.
#### Describe the solution

JSON editing.
#### Describe alternatives you've considered

None.
#### Additional context

None.

### CODE REVIEW

**Comment by esotericist** [comment]
The current in-game `beam` and `plank` items are meant to represent a modern manufactured material. While you absolutely can process a log into a finished beam *of some type* using an adze, getting a modern beam (implying a high degree of straight and squared) is not going to happen without absurd amounts of effort. And getting a modern plank isn't going to happen *period* without better tooling.

The right thing to be doing here is adding less modern/rougher versions of these materials, and also uses for them.

**Comment by Rail-Runner** [comment]
> The right thing to be doing here is adding less modern/rougher versions of these materials, and also uses for them.

Is there any point in having separate versions of those while "modern" material shapes don't have any unique uses to them? I thought about it for a while and couldn't think of any; if it's made of wood, you could always make some kind of less pretty, but just as functional version of it, using simple tools. As soon as someone will be adding recipes which would necessarily need such high precision, "modern" versions of beams/planks could be added in; until then it can kinda represent both.

Real disadvantage of using inferior tools would be higher amount of material wasted and/or more time/skill needed, I think. For instance, using stone adze to make planks gets you only one plank per log and takes a long time. Using steel axe or steel hand saw would improve efficiency and speed by a lot, though it requires user to be skilled to get good efficiency. If we had actual sawmill, it'd be much quicker to process logs than if using hand tools, and it may require less skill to achieve full efficiency as using it is pretty straightforward, but I don't see actual material quality or maximum achievable efficiency improving noticeably over steel hand tools.

**Comment by esotericist** [comment]
Using an adze to make plank-like objects, even if not modern, is absolutely incoherent. You need a different tool to make a plank-like object, period. It's a *finishing tool* for surface removal and smoothing, not an actual *saw*. It having "wood sawing" is not really correct, but we haven't gotten around to adding a more accurate quality (I've tentatively suggested something like "log finishing", but i haven't been in a position to pursue it). 

Accordingly, I'm going to remain adamant that what you can use an adze to make would not be suitable for the things that expect a modern beam or plank. Alternate versions of things that go in a similar category and get used in basically the same places are a common thing in the game; look at all the things we do for cordage, for instance.

The important thing here is just because two things can be used for the same purpose does not mean they are necessarily *the same* thing, and if a tool or material *cannot* be used to produce a given thing, we shouldn't do that.

For stone tooling, we should be focusing on splitting logs, not "sawing" them.

**Comment by Rail-Runner** [comment]
>Accordingly, I'm going to remain adamant that what you can use an adze to make would not be suitable for the things that expect a modern beam or plank.

What could those things be, as an example, where you can't "finish up" the possibly rough wood piece with a superior tool either (which you'd probably need for making it anyway as dimensions generally aren't standardized, especially if you just got your "modern" planks from smashing apart a table)? Finishing up would be represented by having the recipe require that tool.

If there are no such recipes yet, it really seems much easier to just rename current plank to a generic "piece of wood" or something, then introduce actual "modern" planks if it's ever needed. There's way too many ways to obtain them that wouldn't get you actual high-quality planks to go about changing them all.

**Comment by kevingranade** [comment]
The main thing that comes to mind is putting flat sections on a log to enable stacking for something like a log cabin.
It also needs to be a seperate tool anyway as the stone adze is going to be like 100x  slower than a modern saw or axe at this job.
I completely agree with eso that there is no good reason to shoehorn a stone adze into a recipe for a finished beam or plank.

**Comment by Rail-Runner** [comment]
> The main thing that comes to mind is putting flat sections on a log to enable stacking for something like a log cabin.
> It also needs to be a seperate tool anyway as the stone adze is going to be like 100x slower than a modern saw or axe at this job.
> I completely agree with eso that there is no good reason to shoehorn a stone adze into a recipe for a finished beam or plank.

Well, what would you suggest as a way to start making items that currently necessarily need planks in wilderness, then? Either via adding some alternative to planks in those recipes that is wilderness-craftable, or adding some way to make planks. What you said before was:

> If you feel like adding the ability to harvest a single plank or beam from a log with a stone adze, feel free.

So, well, I did exactly that, now it's apparently not the right thing. I'm still willing to implement the *right* way whatever it'd be, though.

**Comment by kevingranade** [comment]
There are two major changes here and they're different.
One you lowered the axe and saw quality level for producing a wooden beam, that change is *wrong* because it elevates the adze and other tools to the same level as a much higher quality tool with basically no rationale.  There's a reason the quality levels are where they are.
Two you added a plank recipe using the adze, that's not wrong in the same way, but spending 6 hours removing 90% of the wood from a tree to make a finished plank out of it is a deeply nonsensical thing to do (also I'm not totally sure that's a reasonable timeframe, woodworking with stone tools is unbelievably slow).  Does this actually support some goal you have or are you just randomly adding crafting recipes?

> Well, what would you suggest as a way to start making items that currently necessarily need planks in wilderness, then?

What you need to be doing here is looking at the kinds of things people with these tools actually build and use, and enable that kind of crafting instead of shoehorning primitive tools into voids left by the absence of modern tools.

**Comment by esotericist** [comment]
> What you need to be doing here is looking at the kinds of things people with these tools actually build and use, and enable that kind of crafting instead of shoehorning primitive tools into voids left by the absence of modern tools.

this is why i brought up splitting. splitting the wood is what you would do with tools of this type, never "sawing". takes impossibly long, if you can even successfully manage it at all.

it's possible to repeatedly split a log to get board-like objects. not directly comparable to modern planks, but serving a similar purpose. of course, it's a skill dependent task, and you aren't guaranteed usable results even if you're good (because trees aren't known for being overly cooperative).

hilariously, the old "use axe to make planks" logic is actually not *too* far off here, except it'd be producing these rough boards, not planks. (and an axe should of course never be used for producing modern "four square" planks.)

**Comment by Rail-Runner** [comment]
I think I'll figure out some alternative approach to it later then.

**Pull request closed without merging**
