### PR TITLE
Hoarder penalty adjustments

### PR DESCRIPTION
**Pull request by Skrassh**
#### Summary
Balance "Adjusted how the hoarder morale penalty is calculated with a focus on small pockets and holsters"

#### Purpose of change
Addresses some of #51392 

#### Describe the solution
Instead of taking the full possible volume of a holster for morale penalty instead use a flat penalty for whether it is full or not. Proposed penalty being -1;

For small pockets, those below or equal to 1000ml, we instead give a 25% allowance on their weight, only requiring them to be 75% full for their to be no penalty.

#### Describe alternatives you've considered
I'm looking for feedback on both the small pocket tolerance and the flat penalty for empty holsters.
This also isn't a full fix for drop leg pouch, those may require an adjustment on the total weight allowed in a single pouch. Currently you max out on weight before you max out on volume, this creates an awkward situation for the hoarder trait. So there is a discussion to be had on if a container that is maxed on out weight should still count against you for hoarder purposes.

#### Testing
For holsters simply make a new character with the hoarder trait and wear a scabbard or anything with the holster tag.

For small pocket adjustments equip a pair of light survivor pants, the penalty for them being empty should be -27 instead of -36

### CODE REVIEW

**Comment by Termineitor244** [comment]
I would be in favor of the trait not giving morale penalties if you are full in your allowed weight but not your allowed volume (Even if you want, you literally cant put more stuff in there).

But more than anything, I would prefer a redesign of the hoarder trait, similar to the pyromaniac one, where you would get a morale bonus for being at full capacity, and the penalties only apply when you have some considerable free space in your pockets.

THAT SAID... Its out of scope of this PR hahaha.

**Comment by Maleclypse** [comment]
> I would be in favor of the trait not giving morale penalties if you are full in your allowed weight but not your allowed volume (Even if you want, you literally cant put more stuff in there).
> 
> But more than anything, I would prefer a redesign of the hoarder trait, similar to the pyromaniac one, where you would get a morale bonus for being at full capacity, and the penalties only apply when you have some considerable free space in your pockets.
> 
> THAT SAID... Its out of scope of this PR hahaha.

In support of a general rewrite, here are some generalized statements about hoarding tendencies.  https://www.mayoclinic.org/diseases-conditions/hoarding-disorder/symptoms-causes/syc-20356056

**Comment by Skrassh** [comment]
I would agree on a complete rework of hoarder to be in order. Something more in the line of morale penalties for dropping items or something of the sort and a bonus for having over a certain amount of volume/weight in things.

**Comment by kevingranade** [comment]
In case you haven't noticed, the code style check is failing and needs to be fixed. Either run make astyle locally or click through the "astyle" check and expand the "Display Corrections" section to see what needs adjusting.

**Pull request merged**
