### PR TITLE
[CR] [RDY?] Blazemod Blob Tank Generification

### PR DESCRIPTION
**Pull request by ussdefiant60**
Right, after a small bit of fumbling with Git, i've got a PR for part 2 of the things i discussed in #19217 , the tanks in particular. Capsules are set to 10 L, Pods 20, and Cocoons 25 L, and have been renamed to match the naming style of vanilla tanks. The location: under variants on the tanks have been eliminated entirely, leaving 3 entries out of 30 that were previously in the file and cluttering up the in game list (Though those 3 entries could be restored easily enough if necessary).

A couple issues i see as needing discussion before this gets committed proper:

1) Despite Capsules and Pods being identicle in size to vannila 10 and 20 L tanks in their vehicle part entries, ingame they were only able to hold 7.5 and 15 L, due to the component items being set to capacities of that value. I opted to increase the capacity of the components since it seemed fairly obvious that @Blaze-whatdoyoumeanitsalreadytaken intended for them to be identicle to vanilla tanks when actually installed in a vehicle. this does leave me wondering if "size" entries on vehicle mounted tanks actually does anything, though.

2) Migration: I'm not at all certain how to make this save compatible. the migration json i currently see seems to apply to player inventory items, but i have no idea if it'll work with installed vehicle parts or not.

3)There's a couple of entries for small gas/diesel tanks over in blaze_override.json. The only reason i'm not deleting those in favour of the vanilla 2L tank is that those entries are marked as FOLDABLE, while the vanilla tank is not. Not sure what to do with them.

### CODE REVIEW

**Comment by keyspace** [comment]
Tested the PR locally.

Seems to remove the `under` variants - is this intentional?.. OTOH default tanks don't have this special option.

I've never used these parts, so perhaps I misunderstand where they're to be installed. :/

**Comment by keyspace** [comment]
Ah, the discussion for this is https://github.com/CleverRaven/Cataclysm-DDA/issues/19217

**Comment by ussdefiant60** [comment]
i'd say this is ready except for the whole migration thing. Can anyone advise me on how to handle it?

**Comment by Rivet-the-Zombie** [comment]
Better to merge it now and apply further changes in a future PR.

**Comment by keyspace** [comment]
@ussdefiant60, not sure if it's possible to migrate parts already mounted on a vehicle.

For unmounted parts, I'd say extract the `id`s of items removed, then add `blazemod/migration.json` or the like with contents similar to `data/json/items/migration.json`.

Perhaps "later" indeed?..

**Comment by ussdefiant60** [comment]
theres' no unmounted parts removed, just adjusted so that the capacities of the mounted parts work out. all 30 of the mounted parts were based off of 3 unmounted parts.

**Comment by ussdefiant60** [comment]
with Blaze having made a new update to his mod on the forums that did away with all the excess tanks, there seems to be little point in putting this PR into mainline. Therefore, i'm closing this one.

**Pull request closed without merging**
