### PR TITLE
Adds numpad Enter to confirm item selection.

### PR DESCRIPTION
**Pull request by ghost**
changed file src/pickup.cpp
Signed-off-by: KnightKiller den@stud.fh-dortmund.de

### CODE REVIEW

**Comment by KA101** [comment]
No numpad on this laptop; gonna ask someone with one to test that.  :-/

**Comment by Griffinhart** [comment]
Win7 On-SCreen Keyboard has optional numpad; should signal the same way as a hardware numpad.

**Comment by KA101** [comment]
WinXP.  Thanks, Rivet.

**Comment by Knight-Killer** [comment]
I'm not sure it will affect windows builds, because I guess SDL maps Keypad Enter to "\n", so it should already work in an SDL Build. but on linux with ncurses it doesn't recognize Keypad Enter as \n.

from sdltiles.cpp:
        case SDLK_KP_ENTER:
        case SDLK_RETURN:
        case SDLK_RETURN2:
            return '\n';

**Comment by Rivet-the-Zombie** [comment]
Works fine on Win/Curses.

**Pull request merged**
