### PR TITLE
[WIP] Radiation is not magic, irradiated food doesn't last forever

### PR DESCRIPTION
**Pull request by ehughsbaird**
#### Summary
Balance "Food irradiation slows food decay to a quarter, instead of making it last forever"

#### Purpose of change
Irradiating food does not make it last forever.

#### Describe the solution
First commit: Irradiating food applies the `IRRADIATED` flag, quartering it's spoilage rate.

Second commit: Replace existing irradiated food items with the normal versions of the item with the `IRRADIATED` flag.

#### Describe alternatives you've considered
Different number.

#### Testing
WIP

Don't know how to handle MoM.

#### Additional context
Sorry

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I am going to obsolete the irradiation plant location as there are no food irradiation plants anywhere in New England, and a lone survivor with no experience should not be running a huge facility like that by themself.

See #65907

**Comment by I-am-Erk** [comment]
> I am going to obsolete the irradiation plant location as there are no food irradiation plants anywhere in New England, and a lone survivor with no experience should not be running a huge facility like that by themself.

Please don't. It's fine to remove the irradiating process but there's no reason to remove perfectly good location content. Either refluff it into a packing plant, or make it globally unique.

**Comment by kevingranade** [comment]
```I am going to obsolete the irradiation plant location as there are no food irradiation plants anywhere in New England```
This is kind of unnecessary,  it should probably be a lot more rare,  but we aren't actually aiming for being a complete copy of IRL New England, just a representative example. Things like animals from different biomes or companies that don't made sense in new England like mass desalination plants would be problematic,  but there's no fundamental reason New England *can't* have irridation plants.
Concerning the maintenance issue,  the concept is that it's a passive emitter that does not in fact require highly expert maintenance or a large power supply.
About the effect of irradiation, I agree it shouldn't be absolute and it should require e.g. vacuum sealing to work properly,  but that's not a meaningful blocker to it existing.

**Comment by fairyarmadillo** [comment]
Well that saves me the work I suppose 😆 Carry on OP.

**Comment by PatrikLundell** [comment]
What do you mean, radiation isn't magic? It can provide you with working mutations!

But yes, irradiation isn't a means to completely stop the degradation of food, and it really should be useful only if sealed. However, until sealing is introduced, a reduced degradation rate sounds like a reasonable temporary measure.

**Pull request merged**
