### PR TITLE
Adds birch, maple, and willow trees.

### PR DESCRIPTION
**Pull request by Zaweri**
To add harvestables like birch/maple/willow sap/bark. (Adding these in a separate PR most likely.)

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, glorious. Since one of my projects is yet another tileset update... X3

**Comment by Coolthulhu** [comment]
We need some standardized tree colors. Currently light green '7' is an apple tree. If you want any non-fruit tree to have light green '7', apple tree needs to have its color changed.

We could apply the same rules from bushes - give apple tree a light green background. This should also apply to all other fruit trees - cherry, plum etc.

Just adding new trees won't make them spawn in game, but mapgen changes can be a separate PR.

**Comment by chaosvolt** [comment]
I agree with the idea of standardizing fruit trees around the use of a background.

**Comment by Zaweri** [comment]
@chaosvolt I don't know how to make it turn into that version. I'll get around to all that sometime later; Now I am getting some sleep.

**Comment by chaosvolt** [comment]
Hmm. Get some rest then. I was just gonna say define the terrain entries for the time being, then one can work on implementing them later, or in a separate PR.

**Comment by Zaweri** [comment]
Made the fruit trees into different colors now, @Coolthulhu

**Comment by Coolthulhu** [comment]
I don't like all those backgrounds. We barely "established" a standard that green background for a plant means "fruit plant" (with fruit bush color change) and now we'd be tearing it down with this new one that colors fruit trees by the color of the fruit and the color of leaves.

I personally would prefer it less colorful: fruit color for the foreground, green/ltgreen for background, with one of those meaning harvested and the other unharvested. That would make few trees look identical, but so far fruit drops are nearly identical. Bushes could be adjusted similarly.

If others prefer the fruit/leaf instead of harvestable/harvested, I'll merge it in the current state, otherwise I'm waiting for the change.

**Comment by Zaweri** [comment]
@Coolthulhu It is already like that..  fruit color is the 7, background is green except for cherry.

**Comment by Coolthulhu** [comment]
Not just cherry - apple also is wrong.

**Comment by Zaweri** [comment]
Uhhh... No it is not. Red = apple, cherry is light pink background because the tree's leaves are pink.

**Comment by Coolthulhu** [comment]
All other trees (except cherry and apple) go from `something_ltgreen` to `something_green`.

**Comment by Zaweri** [comment]
Oh, yes, just noticed that after I triple checked, sorry, i have minor dyslexia :/

**Comment by Coolthulhu** [comment]
Now just the cherry tree. I don't see a reason why would it be an exception. IRL all trees have brown trunks, in game it's green.

**Comment by Zaweri** [comment]
Because the background is the color of the leaves. And cherry trees are pink ingame.

**Comment by chaosvolt** [comment]
As mention, you might want to add a "t_tree_birch_harvested" terrain to support harvesting birch bark. Whereas it makes sense harvesting from a blackjack oak turning it permanently into a normal oak tree, it makes less sense for birch to turn into an oak tree.

Making the birch tree regrow is optional. For the sake of consistency with blackjack oak, you could opt for the harvested version to be a defunct, non-special tree with no need to add harvest-related properties.

Then all we'd need is to later on code a variant of the blackjack function that can be applied to the standard birch tree.

**Comment by Coolthulhu** [comment]
> Because the background is the color of the leaves.

Then the standard is not "ltgreen for harvestable, green for harvested", so I'm waiting either for others to confirm it's OK to have a non-standard coloration or for the change so that it is standard.

**Comment by Coolthulhu** [comment]
Oh and by the way, cherry trees are only red/pink IRL when blooming and that's just like, one season?

**Comment by chaosvolt** [comment]
Also pondering how easy it'd be to make the blackjack function modular so that the terrain entry can define what it drops, and what tree it turns into...

**Comment by kevingranade** [comment]
Cherry leaves aren't pink, that's blossoms, and I'm not even sure the cherry trees in New England do that, the ones I'm thinking of are japanese cherry trees.  Those are only in bloom for a week or something IIRC.  I don't think it's a distinction worth having either, especially if we're trending toward having more tree types.

**Comment by Chezzo** [comment]
I think they do, they have the Cherry Blossom festival in D.C.! https://en.wikipedia.org/wiki/National_Cherry_Blossom_Festival

Man, kind of makes me want to go through and do cherry_tree_season_spring and all the other spring fruit trees. At least they wouldn't look pickable.

**Comment by chaosvolt** [comment]
Will be interesting to see this. I'll have to hurry up with my tileset update before these get implemented, given my endless hatred of terrain transparency errors.

I'm assuming that we can puzzle out what the hell to turn harvested birch into once birchbark is actually a thing.

**Comment by Coolthulhu** [comment]
Plums look a little bit too harvested, but otherwise it looks good.

**Comment by chaosvolt** [comment]
Excellent. So who's planning out the next step? Will they be implementing these AND giving them uses in a later PR, or implementing first and then adding their uses in a third PR?

**Comment by Coolthulhu** [comment]
Next step requires C++. iexamine.cpp, iexamine.h, mapdata.h and mapdata.cpp

**Comment by chaosvolt** [comment]
Ah, that's gonna be a hassle to add, I suspect. XP

**Comment by illi-kun** [comment]
> Oh and by the way, cherry trees are only red/pink IRL when blooming and that's just like, one season? Apple trees are white/pink when blooming as well as some other fruit trees.

**Comment by illi-kun** [comment]
> Oh and by the way, cherry trees are only red/pink IRL when blooming and that's just like, one season?

Apple trees are white/pink when blooming as well as some other fruit trees.

**Comment by chaosvolt** [comment]
I'm looking at the code to PR harvesting of birch bark. Will leave the mapgen stuff to others for the time being. Anyone have suggestions for stuff to use birchbark for?

**Comment by Coolthulhu** [comment]
> Will leave the mapgen stuff to others for the time being.

Check out how it's done in #13357
It's just 4 lines total.

**Comment by chaosvolt** [comment]
Hmm. Was looking at the mapgen files, so I guess I could take up the mantle and implement all of the trees. And suggestions for what uses the trees should have?

**Comment by Rivet-the-Zombie** [comment]
>Anyone have suggestions for stuff to use birchbark for?

[Birch bark shoes.](http://www.wildwoodsurvival.com/survival/clothing/birchbarkshoes.html)

**Comment by chaosvolt** [comment]
Ooh. Partially implementing via adding it as a straw alternative, but dedicated birch bark items would be a nice addition. Also an option, quivers.

Would be tempted to add them as More Survival Tools items, but since I'm already adding mainline uses it might be saner to add such things as mainline.

**Comment by illi-kun** [comment]
> Birch bark shoes.

= lapti mentioned in #4938 (they can be produced from bark and not only from bast, see [this] (https://www.google.com/search?q=%D0%91%D0%95%D0%A0%D0%95%D0%A1%D0%A2%D0%AF%D0%9D%D0%AB%D0%95+%D0%9B%D0%90%D0%9F%D0%A2%D0%98&biw=1280&bih=890&tbm=isch&tbo=u&source=univ&sa=X&ved=0CBsQsARqFQoTCKWK_42FvMcCFSbDcgodjuYDuQ# "google: Берестяные лапти")).

Bark can be used for a lot of things: [tents, canoes, hats, boxes...] (https://en.wikipedia.org/wiki/Birch_bark "wikipedia").

**Comment by chaosvolt** [comment]
Ah right. I did implement birchbark shoes, and made the possibly odd choice of adding birchbark as an alternative for straw in the sandals, hat, and basket recipes.

Should I split that off into completely different items instead? And additionally pondering more uses for willow bark.

**Pull request merged**
