### PR TITLE
Partial chitinous helmets

### PR DESCRIPTION
**Pull request by bloodbowel**
#### Summary
Features "Partial chitinous helmets"

#### Purpose of change
I like the idea of the chitinous armor, but the options working with it have been limited. It's lacking in some recipes. One thing I always wanted was the ability to create a chitinous helmet that isn't a "full helmet" that covers the mouth and eyes. Just a regular helmet.

#### Describe the solution
I created a chitinous helmet that leaves more of the front of the face open. This removes the mouth and eye encumbrance but still provides decent protection. Still covers the cheeks and chin. You can also slip a gas mask on while wearing this like a modern military style helmet. Now the original chitinous helmet is called a "full chitinous helmet" and this is just called a "chitinous helmet". Making it takes a little bit less material and time, but is about as difficult.

#### Describe alternatives you've considered
Maybe a chitinous helmet that can open and close. That way you get the best of both worlds. That might be a decent tailoring 8 recipe in addition to this. If some of the coverage isn't right tell me. I basically just took parts of the original helmet off. Also I don't know exactly how much less material this would take. I took 2 pieces of chitin off the base cost. Seemed reasonable to me.

#### Testing
Tested on my computer in debug mode in the tutorial room.

#### Additional context
Screenshot
Screenshot2

### CODE REVIEW

**Comment by CLIDragon** [comment]
I don't think changing the id of the old `chitin_helmet` to `chitin_helmet_full` is a good idea.  Anybody who loads an old save will find that their chitin helmet is now missing protection for the face. I don't think it can be migrated either, as (to the best of my knowledge) the migration system simply replaces ids on save load - it would be impossible to have a partial chitin helmet, as it would be replaced on save load.

Perhaps just give the new helmet the id `chitin_helmet_partial`. It should be ok to change the names.

**Comment by Maleclypse** [comment]
> I don't think changing the id of the old `chitin_helmet` to `chitin_helmet_full` is a good idea. Anybody who loads an old save will find that their chitin helmet is now missing protection for the face. I don't think it can be migrated either, as (to the best of my knowledge) the migration system simply replaces ids on save load - it would be impossible to have a partial chitin helmet, as it would be replaced on save load.
> 
> Perhaps just give the new helmet the id `chitin_helmet_partial`. It should be ok to change the names.

This is the correct way to handle this due to the limits of migration mentioned above.

**Comment by bloodbowel** [comment]
I didn't know you could even play old saves. I'll fix it.

**Comment by bloodbowel** [comment]
I restored the original chitinous helmet which I called the "full chitinous helmet" back to being the standard chitinous helmet. Then I renamed the helmet I added with this pull request to be the "light chitinous helmet" instead.

So now you would have the regular helmet and this new light version. All the IDs should be correct.

**Pull request merged**
