### PR TITLE
Restores gummy vitamins.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
These are a real thing and they're great; they should not have been
removed in the first place.

### CODE REVIEW

**Comment by mugling** [comment]
How to differentiate them from regular vitamins? The `fun 2` isn't of much consequence.

**Comment by Coolthulhu** [comment]
They were removed in #16256

As far as I recall, the reasoning was that dropping some of the vitamin value enables micromanagement (the bad kind of micromangement - number fiddling).

If you're sure we want them in, I'd see them like this:
* Vitamin value same as "real" vitamins
* Increased fun
* Lower stack size because more padding

This wouldn't make them different, but would give them a disadvantage without enabling the micro.

**Comment by pisskop** [comment]
Well, gummies vita-mans are supposed to

  -come in a more palatable form (more fun than a stick of chalk that dissolves into a slightly filmly paste in water)
  -be more readily digestable (though th fact that just lets them put less in them is a thing)
  -Come in fun shapes and sized (flinstones gummys)
  -Are able to be sold form more than chalk gummies.

Itd be neat if they contained differing amounts of dietary nutrients, but they end up being essentially the same thing.  In a game where several very similar guns are included I cant see why not

**Comment by mugling** [comment]
> Vitamin value same as "real" vitamins

It might be worth checking but I think the `use_action` is inherited as part of `copy-from`

> Itd be neat if they contained differing amounts of dietary nutrients

See @Coolthulhu's above explanation and also the discussion in #16256

Given the vitamins system currently has some outstanding problems with balance adding more non-essential parts seems at present counterproductive.

Vitamins should be an option of last resort or useful as a crafting item (for fortified foodstuffs). In either case almost any amount of `fun` is irrelevant.

If the argument is to add variety then I'd actually propose a system of alternate names (via a mod). This could keep everyone happy?

**Comment by kevingranade** [comment]
Holy crap guys, how many times do I have to repeat this? The mere existence
of an item IRL is sufficient reason for its inclusion. If you want to
differentiate items further, great, but stop removing items just because
they aren't "different enough".
If you want a version with everything streamlined like every other game,
make a mod.

**Comment by SeanMirrsen** [comment]
@kevingranade I can't thumbs up that post enough.

**Pull request merged**
