### PR TITLE
food recipes: add large_stomach to haggis ingredients

### PR DESCRIPTION
**Pull request by mlangsdorf**
For those times when you've got one last piece of offal and one large
stomach and want to usefully combine them.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Do you want me throw that in? This really meant to be "I have scraps, why can't I combine them?"
But assuming I can figure out how id_suffix works, I could do a double batch.

**Comment by nexusmrsep** [comment]
Why not if you can? It's a large stomach after all. Thanks in advance.

**Comment by mlangsdorf** [comment]
I can't get the portions to work for some reason:
```
+  {
+    "type" : "recipe",
+    "result": "haggis",
+    "id_suffix": "large",
+    "category": "CC_FOOD",
+    "subcategory": "CSC_FOOD_MEAT",
+    "skill_used": "cooking",
+    "difficulty": 3,
+    "skills_required": [ "tailor", 1 ],
+    "time": 45000,
+    "book_learn": [ [ "survival_book", 6 ], [ "scots_cookbook", 3 ] ],
+    "result_amount": 8,
+    "batch_time_factors": [ 50, 4 ],
+    "using": [ [ "sewing_standard", 2 ] ],
+    "qualities": [ { "id": "BOIL", "level": 1 }, { "id": "COOK", "level": 3 }, { "id": "CUT", "level": 1 } ],
+    "tools": [ [ [ "surface_heat", 10, "LIST" ] ] ],
+    "components": [
+      [ [ "water", 2 ], [ "water_clean", 2 ] ],
+      [ [ "stomach", 2 ], [ "stomach_large", 1 ] ],
+      [ [ "offal", 2 ] ],
+      [ [ "oatmeal", 2 ], [ "buckwheat", 2 ] ],
+      [ [ "fat", 2 ], [ "tallow", 2 ], [ "lard", 2 ] ]
+    ]
+  },
```

**Comment by mlangsdorf** [comment]
because
```
-   "result_amount": 8,
+   "result_mult": 2,
```
if I wanted it to work.

Which I do. Amended commit force pushed.

**Pull request merged**
