### PR TITLE
Adds chemistry skill

### PR DESCRIPTION
**Pull request by facepalm**
While poking through the recipes for all the miscellaneous chemicals one can find in a lab, I realized that we probably have enough raw material to split off a separate chemistry skill, especially if we pull over a few existing crafts which are more chemistry-themed.  Hell, we already have a crafting tab for it.  So I played with it a bit, and it seems reasonable.  It took a bit of difficulty tweaking, but even without books it's entirely possible to skill up to mutagen-production levels via crafting alone.

This switches a large number of crafts to using chemistry, but I'm sure anyone familiar with the chemistry tab will recognize that most of them just aren't very good.  Either they're impractical to make, or too specialized, or just not really anything you'd ever use.  I wanted, as a minimum basis for inclusion, at least one product at each crafting level which is generally useful, or at least easyish to craft for grinding past.  Here's what I'd recommend for a "grind to mutagen" pathway:

Chemistry 0: Clean water (states of matter change, and cooking will hardly miss it given cooked meat)
Chemistry 1: Salt (I'm assuming the salt water->salt recipe uses supersaturated solutions, which should be > 0)
Chemistry 2: Battery (it's a chemical process, and I'm always past fab 2 when I start crafting them anyway)
Chemistry 3: Heat pack (lame level.  Needs some love)
Chemistry 4: Protein powder.  Also aspirin, gunpowder and conc. acid.  Something could be lowered a bit
Chemistry 5: Blob globs (also lame)
Chemistry 6: Ammonia or Bleach. Lots of other good options here.
Chemistry 7: Oxidizer (7 is probably too high, but needs a good replacement before lowering it further)
Chemistry 8: Mutagen

**Future Work**
This PR is intended to pull out the skill and establish a framework for dropping improvements onto.  There are a number of further additions I'd like to make:
- A few current found-only chemicals have good precursors to enable their synthesis.  Formaldehyde can be crafted from alcohol (technically methanol, but it's close enough for game purposes) and silver, serves as a disinfectant in its own right, and can be combined with ammonia to form hexamine.
- Electrolysis equipment as an easier-to-craft tool for a few recipes which depend on it, and as a late-game tool for more advanced crafting (purification via gel electrophoresis).  It could also make iron oxide for thermite.
- Mutagen overhaul.  Making prototype mutagenic treatments from ammonia, bleach and a high school chemistry set?  Surely we can do better.

... but all of those (mutagen especially) should probably be packaged in their own PRs.  For now I'd be content tossing in a skeleton of a system to be fleshed out in the future.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Doesn't look anywhere near ready enough. At this point it looks like a skill you ignore until you want to start grinding for mutagen or at the very least gunpowder.

Most of the recipes require the chemistry set, which isn't easy to craft. Makes it like mid-level fabrication, where you have a big hurdle (forge and anvil) it's not worth trying to get over until endgame.

I'd say first start with the setup - changing as many recipes as you can to use weaker chemical tools like pots and stills, making stills more available, allowing more improvised precursors like bone dust or wood ash etc.
Then the low levels should be fleshed out first. Alcohol distillation, sterilization of cloth for bandages using some cheaper method, I don't know what more but it needs more.
Make the new chemistry books cooking at first too, just give them those new recipes. Make them not-autolearn at first.

Then when cooking has enough low-level chemistry stuff, they could all be moved into the new skill (as a separate PR) without making it bare.

**Comment by Zireael07** [comment]
The idea is lovely, but I agree with @Coolthulhu about fleshing it out first. However, I don't think cooking should get low-level chemistry stuff. Just add the new recipes to this PR. 

And seconding the pots and stills comment.

**Comment by facepalm** [comment]
>At this point it looks like a skill you ignore until you want to start grinding for mutagen or at the very least gunpowder.

That's going to be an inherent part of the skill no matter how fleshed out it is.  It's not a survival skill.  People have always got on just fine without a jot of knowledge about how the world actually works, relying on folk wisdom and "what works" currently packaged as cooking, survival, etc.  They didn't know _why_ smoking meat made it last longer, it just did, and they didn't have the luxury of caring beyond that.  Chemistry is a "modern tech" skill, like computers or electronics, which you can also easily ignore unless you have something specific in mind to grind towards.

As it is now, water, salt and batteries are all indispensable commodities that can bring any player to level 3, equivalent to a high school education, albeit at a very dangerous high school.  It'd be _nice_ to have more options at these levels, but no one needs them for skill.  At level 3, I don't see it as a terrible thing to require the player to search out a textbook* for the chemistry set recipe, which is actually pretty easy to craft once it's available.  That might make it endgame content, but that's more a problem with the endgame never requiring the player to leave their starting town.

You make a good point about bandages, though.  And the still - I can't say I've ever used one.  It has the same recipe-locked problem, but in books that contain nothing to actually make with it.

In fact, am I reading this right? http://cdda-trunk.estilofusion.com/still/recipes/CC_FOOD  Are stills used in the **production** of wort?  The thing that you normally make in a pot, ferment, and _then_ put in the still?  I'm not a home brewer, much less a home moonshiner, but that seems a little backwards to me.

>EDIT: Thorazine + darts = tranquilizer darts (http://smf.cataclysmdda.com/index.php?topic=10046.0)
Would zombies even respond to thorazine?  It operates on the central nervous system, while the Blob just needs mass, and intact muscle tissue to jerk around like a puppet.

Moose, though...


*And now I realize I forgot to add the new chemistry books to any item_groups, so they'll never spawn.  Will fix tonight.

**Comment by Coolthulhu** [comment]
> That's going to be an inherent part of the skill no matter how fleshed out it is.

No, a properly fleshed out chemistry skill would be useful at low levels too. And not just useful for leveling itself.
A skill that you ignore for 90% of the game and then grind up by 8 levels in the remaining 10% is certainly not well designed.

> That might make it endgame content, but that's more a problem with the endgame never requiring the player to leave their starting town.

Depends on RNG and town size. But a skill should not be an "endgame skill", only have some endgame content in it.
Otherwise you end up with fabrication: skill you grind up to 3, completely forget after that, then rediscover only to read an advanced book and craft a cool weapon (that's purely for show, because nothing can hurt you by then).
Though cooking is already quite bad at it, with the hole around levels 4-6.

Start off by creating a proper base for splitting off the skill rather than by splitting cooking into skill that has no early game content and a skill that has only early game content.

**Comment by facepalm** [comment]
>Otherwise you end up with fabrication:

Wait, so _fabrication_ isn't good enough?  You can't say it isn't fleshed out - it's so damned fleshed out it's got rolls of fat hanging off it and landing on other skill's heads.

You seem to be asking for a huge amount of game content, much more than any current skills possess.  I think we already have the minimum needed for the skill to stand on its own.  More content will only help, but it's enough to start with as it is.

>skill you grind up to 3, completely forget after that, then rediscover only to read an advanced book and craft a cool weapon (that's purely for show, because nothing can hurt you by then).

And what's wrong with that?  It seems sensible to me: a survivor attains basic competency in a wide variety of skills, and forcuses on one or two at a time to complete some advanced project they have in mind.  I don't think the goal should be to have everyone sleepwalk to 10 in every skill at once.

**Comment by Coolthulhu** [comment]
> Wait, so fabrication isn't good enough? You can't say it isn't fleshed out - it's so damned fleshed out it's got rolls of fat hanging off it and landing on other skill's heads.

It isn't really. It has a lot of "content", but nothing to craft. Most of the recipes are either filler, not craftable until it's way too late or very low level stuff.

> You seem to be asking for a huge amount of game content, much more than any current skills possess.

No, I'm asking for content that actually has a good reason to get crafted. Things like pointy sticks, fire drills, lightstrips, first aid kits, wearable flashlights, needles, homewreckers, welders, hoodies, jerky, broth...

Look at your own list in the first post. Batteries, mutagen and some drugs you'll use twice in the whole game? Rest is ingredients for those.

>  I think we already have the minimum needed for the skill to stand on its own

How about make it enough that it's good for the skill to stand on its own? Just going for the minimum here would make sense if you expected that it will motivate everyone to start adding new recipes to "restore the balance".
But looking at the latest development, it doesn't look like anything like this is going to happen. After the recent skill gain nerf, construction is still a 3 level skill, driving is still impossibly tedious to skill without books except even more so now, swimming didn't change and fabrication is still not worth grinding above lvl 2-3.

> It seems sensible to me: a survivor attains basic competency in a wide variety of skills, and forcuses on one or two at a time to complete some advanced project they have in mind.

You mean "survivor gains the useful parts of the skills, notices the big RNG wall that prevents them from getting the rest, goes around punching zeds, becomes immortal, finally finds a book and crafts a now-useless katana for show".

> I don't think the goal should be to have everyone sleepwalk to 10 in every skill at once.

And I don't think the solution should be having skills too tedious and useless to level.

Now that I think about it, the change could make sense if all the skill requirements were halved. Survivor with lvl 4 in a crafting skill is about the right power level for mutagen to be useful.
Level 7-8 with a new skill that was useless up to this point? Not worth half the effort. Wouldn't even be worth the effort with the way faster old leveling system.

**Comment by facepalm** [comment]
>Most of the recipes are either filler, not craftable until it's way too late or very low level stuff.
>notices the big RNG wall that prevents them from getting the rest
>finally finds a book and crafts a now-useless katana for show".

I think your problem is less with this skill, and more with the skill system in general, specifically how many items are recipe-locked starting from around the midgame.  I understand this is intentional, as an artifact of the simulation.  Skills at level 3 represent a high-school education, or thereabouts.  Beyond that, any given individual is unlikely to spontaneously think up very many useful applications, as opposed to reading about them in a book.  Combine that with the fact that long overland trips are surprisingly dangerous in Cata (you're very, very likely to run into at least one zombear, zomoose, mi-go, etc), and we have the situation that it's optimally effective to squat in your cleared-out starting town until you can shrug off anything and everything, _then_ go a'lootin'.

> Things like pointy sticks, fire drills, lightstrips, first aid kits, wearable flashlights, needles, homewreckers, welders, hoodies, jerky, broth...

I can honestly say I never craft half of these on a regular basis.  Those that I do, I generally only need one of.  Rest is grind for those singletons.

>Batteries, mutagen and some drugs you'll use twice in the whole game? Rest is ingredients for those.

Yeah, that's chemistry in a nutshell.  90% of the effort and knowledge goes into making ingredients for the ingredients for the end products.  Ideally for multiple potential end products at once, to be selected when the need arises.

>And I don't think the solution should be having skills too tedious and useless to level.

...yeah, I don't think you're actually talking to me, here.  I'm just a proxy for some other argument with some third party.  I've said, multiple times, that my own requirement was that the skill needed at least one item that was useful or not too tedious to produce for each level.  Literally the exact opposite of what you're asserting.  We ought to be agreeing with each other.

**Comment by Coolthulhu** [comment]
> ...yeah, I don't think you're actually talking to me, here.

I'm fine with disagreements and "banter", but this is just plain hypocrisy after you said this:
> I don't think the goal should be to have everyone sleepwalk to 10 in every skill at once.

Plus, how is your solution different from what I described? How does splitting one skill into two you have to level separately actually going to help with the problem of endgame grinders being good at everything other than by bogging them down with tedium? And don't say skillbooks - those are actually separate.

Regardless:
> I think your problem is less with this skill, and more with the skill system in general, specifically how many items are recipe-locked starting from around the midgame.

Fabrication is significantly worse than say, mechanics. With fabrication, you not only need the book, but also tons of crafting tools, either from different books or from lots of drops. Mechanics grants you the pneumatic weapons (autolearn), which are better than all weapons from fabrication (because by that time you've got enough melee to punch hulks and so don't need katanas) and it can be learned by doing the stuff you'd do already.
Even electronics has the decency to be just pure bookcraft rather than requiring tons of rare tools.
Chemistry right now wouldn't as bad at it as fabrication, but it would be worse than electronics (all tools and materials are common) or tailoring (same, except even more so. Also autolearn everything).

> and we have the situation that it's optimally effective to squat in your cleared-out starting town until you can shrug off anything and everything, then go a'lootin'.

It's more like it's too easy to get indestructible compared to getting good at crafting. Just punching zeds brings you to level where you punch hulks. With city size 4 you can easily become a master warrior before leaving the first town. Master blacksmith? Not so much. Often not even any blacksmith (no tools).
There are giant RNG walls barring access to all good crafts, meaning (barring huge, huge luck) that it's easier to learn to punch hulks to death than to craft a good knife. Plus, level 4 melee is a respectable hulk slayer, while level 4 crafting is a novice.



What's wrong with preparing BEFORE the change rather than fixing everything after?
I spent a month developing the z-levels totally disabled not to wreck the game with bugs (some still happened). The only way to get them was to recompile the game with z-levels option. All preparations with no visible effect, but with an obvious goal in sight.
Here you're doing the opposite: no preparation, no promise that it will ever get sensible, just an idea. I can't even think of a good reason for it other than an opinion that they should be separate skills (which is a reason, but not actually a good one). And the only obvious and certain thing I see here is that getting mutagen will be more tedious and pushed even further into post-endgame.

**Comment by facepalm** [comment]
>Plus, how is your solution different from what I described? How does splitting one skill into two you have to level separately actually going to help with the problem of endgame grinders being good at everything other than by bogging them down with tedium? And don't say skillbooks - those are actually separate.

Why do you assume that's the problem I'm trying to address?  That's the point I was making with the "sleepwalking to 10" comment.

The problem I'm trying to address is that chemistry _isn't_ cooking.  They're just two kind-of-related skills bunged together for convenience sake and will eventually need to be separated, which I think you'll agree with.  Where we differ is when to unbung them, when does it have enough meat to be pulled out into separate skill.  I think it does, even if it doesn't come with a perfectly smooth progression curve for optimized play.

>Fabrication is significantly worse than say, mechanics. With fabrication, you not only need the book, but also tons of crafting tools, either from different books or from lots of drops. Mechanics grants you the pneumatic weapons (autolearn), which are better than all weapons from fabrication (because by that time you've got enough melee to punch hulks and so don't need katanas) and it can be learned by doing the stuff you'd do already.

Funny, I'd say mechanics is significantly worse than fabrication for the exact same reason.  There's too much _magic_ involved with mechanics.  You don't have to move around the car, that's automatic.  You just _know_ how to install and repair any part you qualify for, and you don't need anything but welder juice to repair them from one step from broken.  Once you get a welding rig, even that is essentially free.  Then you autolearn recipes for one of the best rifles and the best crossbow, which use trash for ammo and have long reload times as their only drawbacks.

>It's more like it's too easy to get indestructible compared to getting good at crafting. Just punching zeds brings you to level where you punch hulks. With city size 4 you can easily become a master warrior before leaving the first town. Master blacksmith? Not so much. Often not even any blacksmith (no tools).
There are giant RNG walls barring access to all good crafts, meaning (barring huge, huge luck) that it's easier to learn to punch hulks to death than to craft a good knife. Plus, level 4 melee is a respectable hulk slayer, while level 4 crafting is a novice.

Shouldn't punching a hulk to death be an endgame thing?  It sounds like an endgame thing.  I don't think 4 is really an endgame skill level.  It seems to me like we need to make that harder, rather than make everything else easier.

>I spent a month developing the z-levels totally disabled not to wreck the game with bugs (some still happened). The only way to get them was to recompile the game with z-levels option. All preparations with no visible effect, but with an obvious goal in sight.

I'm pulling this out of order to point out that these situations aren't really comparable.  You're changing one of the most basic elements of the game, which affects every coordinate, every motion.  I'm changing the word "cooking" to "chemistry," for a subset of things that currently say "cooking."

>What's wrong with preparing BEFORE the change rather than fixing everything after?
...
Here you're doing the opposite: no preparation, no promise that it will ever get sensible, just an idea. I can't even think of a good reason for it other than an opinion that they should be separate skills (which is a reason, but not actually a good one). And the only obvious and certain thing I see here is that getting mutagen will be more tedious and pushed even further into post-endgame.

Well, I did implement it, and played around with it, and it already _does_ seem sensible.  So I'm making a request to pull the implementation and get feedback.  And your feedback, frankly, is lacking.  You say it needs fleshing out, and that it needs more useful skills, and that's fine.  I think "at least one good option" is a good goal to meet, but I can see someone wanting more.  

But then you say _fabrication_ is the same way, the same fabrication that governs half the crafts in the game, and I have a hard time following you beyond that.  It doesn't seem like you have a realistic endpoint in mind, but are expecting the skill to burst forth whole from the forehead of cooking, like a nerdy Athena.  I really have no idea what you have in mind when you think of how much new content is enough, or what you mean by "useful."  When you elaborate, it tends to go off into complaints about recipe-locking, or how easy melee is, or what a pain tools are, not about what the skill needs to earn your approval.

I can tell you though, if you think mutagen crafting is already tedious, you haven't seen anything.  I'm a cell biologist by trade, so I know how to do it _right_.  There's gonna be centrifuges, and incubators, and blackjack and hookers.  It boils down to a much longer and more involved process, at the end of which you get an absolute metric crapton of mutagen.  But that's way beyond the scope of this PR.

**Comment by KA101** [comment]
>lots of argument over whether this is useful

Thing is, this has come up before and we shot it down because splitting chemistry rendered the remaining cooking skill worthless.  I'm not seeing that addressed here.  Closing unless you can convince me not to, you've got 24 hours.

**Comment by facepalm** [comment]
>Thing is, this has come up before and we shot it down because splitting chemistry rendered the remaining cooking skill worthless. I'm not seeing that addressed here. Closing unless you can convince me not to, you've got 24 hours.

I don't see it as worthless.  It's still better than computers, which frankly could be merged into electronics without anyone caring.  Cooking has the same value as always: preserving food for later, and morale bonuses.  The latter is kind of worthless, only because morale needs a significant overhaul, but the need to preserve food is good enough to get cooking to 3 or 4 by itself.  Beyond that, there _are_ advanced cooking applications irl, but what role is there for a Cordon Bleu-trained chef in the postapocalyptic wastes?

**Comment by KA101** [comment]
>cooking to 3 or 4 by itself

There's the problem: high-end cooking would be stripped out, making the skill worthless.

>what role is there for a Cordon Bleu-trained chef in the postapocalyptic wastes?

One of the themes I never got the chance to properly develop in That RP Thread: areas that are still more or less pre-apoc can be bloody impressive for folks and confer significant social advantage on those able to maintain them.  A faction that can offer you chicken Marsala* (fresh) (hot) (let alone veal Oscar* (fresh) (hot) ) is probably gonna seem a little more impressive than the folks who just have a spitroasted chunk of meat (fresh) (hot).

*Chicken in a Marsala wine sauce with mushrooms
*Veal topped with crabmeat, asparagus, and hollandaise sauce

**Comment by facepalm** [comment]
>There's the problem: high-end cooking would be stripped out, making the skill worthless.

As I was saying to Coolthulhu, I don't think a skill is worthless if nearly every survivor brings it to basic competency and leaves it there.  _Swimming_ is worthless: no one touches it.  Like, ever.  Trapping is nearly so, as is Computers.  Throwing ain't great either.  Cooking would remain pretty vital, actually, it just doesn't offer a reason for players to specialize in it.  Either morale (and the contribution of food to it) would need to be made much more important, or NPCs could be made to desire fancy or homestyle foods.  Kind of a little taste of normalcy, you know?

In fact, if I were going to make high-end cooking more important in the game, I'd go through the NPCs.  We have a few quest lines, but a some cooking ones wouldn't be out of character.  Especially if an NPC spawns with some high skill, they were probably using that skill to great effect before the fall, and nowadays would like nothing more than to continue living in the manner to which they were accustomed.

Then there's the refugee centers.  Maybe they have an NPC cook spawn some times that wants ingredients and help making high-end recipes to serve their charges "_real_ food."  Or imagine the trade merchant saying the following:

"But what we really need is smoked meat, bandages, and... cock... coke a vine?  The hell is this?  This one of your jokes again, Pierre?"
"But what we really need is flour.  And, uh... well, I just want to say I've got a blue-blood back here making me say this... Lobster Thermidor.  You find a lobster, or a thermidor, bring it over, he'll make it worth your while."
"But what we really need is booze.  This situation sucks for everyone, and as long as the wine's flowing, we're not staring down a riot.  We can't pay you more for it, but if you end up needing something we can help you out with, say no more."

**Comment by KA101** [comment]
Still not convinced.  DDA policy: don't break existing an claim it'll be made Better sometime later.  Later can be a very long time.

**Comment by facepalm** [comment]
I wouldn't have made the PR if I didn't think it was Better with it.  I think chemistry can stand on its own, and cooking is just fine without serving as a ladder to grind to it.

**Comment by Zireael07** [comment]
Instead of shooting down the whole idea, how about brainstorming some high-level cooking (as opposed to cooking-cum-chemistry) recipes?

@facepalm: KA101 doesn't want cooking to be bare at high levels. No one is saying the chemistry part can't stand on its own, just that the cooking is not stripped too much by your PR.

**Comment by KiwiTrinsic** [comment]
> Instead of shooting down the whole idea, how about brainstorming some high-level cooking (as opposed to cooking-cum-chemistry) recipes?

In addition, with the chemistry recipes removed, the remaining cooking recipes could be rebalanced and some of them pushed up to higher levels.

**Comment by Coolthulhu** [comment]
> Instead of shooting down the whole idea

No one here is shooting down the whole idea, only the idea of doing it right now without a good base for it and without a good, non-personal reason for doing it.
This is a big gameplay change for anyone who wants to use the chemistry stuff.
> the remaining cooking recipes could

"Could" isn't enough here. It could possibly be if the recipes were all rebalanced here in this PR or (better yet) before this PR.
> I wouldn't have made the PR if I didn't think it was Better with it.

And as you can see not everyone agrees with your opinion. Opinion, because all the reasons you've brought up so far were personal "I think that's better" and "I'd prefer it that way". What's better for you is not better for everyone and the change you want to do here would affect everyone (who touches chemistry, that is).
How about make this a mod instead? Then later you could bring it up with possible support from players who tested it.

**Comment by Zireael07** [comment]
I'd love to test such a mod :)

**Comment by facepalm** [comment]
@Zireael07 
>KA101 doesn't want cooking to be bare at high levels. No one is saying the chemistry part can't stand on its own, just that the cooking is not stripped too much by your PR.

KA101 asserted that I'm breaking existing functionality, with the promise that it could be fixed in the future.  I disagree.  I think this is fixing something now.  

Chemistry and cooking are two skills that are only somewhat related, but are being kept together for purely functional reasons.  In other words, it's a messy hack.  If this were code, it'd be one of those ancient legacy functions that does multiple jobs, that everyone agrees ought to be split into subfunctions eventually but no one's done it so far because, and this really appears to be the case, otherwise one of the subfunctions wouldn't be called as often.  It isn't considered "breaking" anything to refactor them into two separate, more minimal functions.  Quite the opposite: it's good programming practice to have each function do one clear, specific thing.  It's the same thing here: having cooking doing cooking and chemistry doing chemistry _should_ be considered a net gain all on its own.

Provided, that is, the functionality of the new stuff isn't impaired, which is why I stressed again that chemistry can stand on its own, in terms of general usefulness and ease of grind.  It's a bit minimal, I'll grant you, but even Coolthulhu'd agree it wouldn't be the worst skill if it were added as-is.

On the flip side is KA101's complaint that it breaks cooking functionality, referring to cooking's "function" of being a pathway to grind to mutagen.  This, I flat-out disagree with.  It is not a _good thing_ for grinding to be the only reason for an item to be crafted, and removing the need for that grind should not necessitate the addition of something else to grind to in its stead.  It may be the case that mutagen is the only reason anyone currently makes aspic, pemmican, etc, and that removing mutagen means no one would level cooking past 3, but that does not mean doing so breaks cooking.  If anything it makes it better, by increasing the ratio of dishes people make because they actually _want_ them.  Fancy that.

@Coolthulhu 
>And as you can see not everyone agrees with your opinion. Opinion, because all the reasons you've brought up so far were personal "I think that's better" and "I'd prefer it that way". What's better for you is not better for everyone and the change you want to do here would affect everyone (who touches chemistry, that is).
Well I'd welcome feedback from the everyone that it would affect, if you can provide something more constructive than wanting it to be "more useful," or "less tedious," or other things that are entirely your personal opinion.

**Comment by Coolthulhu** [comment]
> Chemistry and cooking are two skills that are only somewhat related, but are being kept together for purely functional reasons. In other words, it's a messy hack.

No, it's more like having a function that handles the entire range of arguments fed into it. Instead of having `sin_for_x_more_than_3` and `sin_for_x_up_to_4` there's just one `sin`. Mainline cooking handles both high and low levels, your cooking handles 0-4 and your chemistry handles 4-10.

> Well I'd welcome feedback from the everyone that it would affect, if you can provide something more constructive than wanting it to be "more useful," or "less tedious,"

My first reply was like that. Allow more improvised tools and more improvised ingredients. Add more recipes, especially at low levels. Before (or with) this PR, not as a promise for the future.
Here the burden of proof is on you - you have to explain what will it add rather than just explaining how it won't remove too much. And if all you have is an opinion to back yourself up, expect opinions to be enough to counter that.

**Comment by facepalm** [comment]
>My first reply was like that. Allow more improvised tools and more improvised ingredients. Add more recipes, especially at low levels. Before (or with) this PR, not as a promise for the future.

Yeah... but then you started qualifying "more" with "useful," and said that even Fabrication wouldn't make your cut because despite its mountain of recipes not enough were "useful," and pointed toward Mechanics as an ideal because it hands you everything on a platter made of late-game guns.

**Comment by Coolthulhu** [comment]
Mountains of recipes being a mountain of required tools, which make most of the recipes useless.
> pointed toward Mechanics as an ideal

Not an ideal. It is still way worse than just punching the hulks to death. It is just way better than fabrication, because it actually has a late-game use and it levels as you play rather than with a separate grinding routine.
Your chemistry is like fabrication: something for over-leveled ultra-competent god of a survivor to waste time on.

**Comment by facepalm** [comment]
> it levels as you play rather than with a separate grinding routine.

You can blame the hard cap for that.  When playtesting the softcapped skill overhaul PR, "levels as you play" _exactly_ described the experience for crafting skills.  With the hard cap as it is, most crafting levels only come with deliberate grind, whether that's distaves and spindles for fabrication, panties for sewing, or batteries for chemistry.

But that's another discussion entirely.

**Comment by Coolthulhu** [comment]
Even if you're totally 100% right, you have to address what we have here right now.
My suggestion to move it to a mod wasn't "lol this sucks", but an actual suggestion on how you could save this idea. You could then add an option for soft cap as a separate PR (an option like skill rust). You could get people to play your way, add new recipes and arguments etc.

As it stands, I'd say the PR is not ready and you need to work on it if you want it in. And not work by arguing how my feedback isn't good enough, not even by arguing how it is ready, but by figuring out what it needs and adding it first.

You are trying to mainline a major crafting change. This requires major arguments.

**Comment by facepalm** [comment]
This is a Pull Request, not a Pull Demand.  I made it because I think the proposed changes already add sufficient value to justify their inclusion.  If the general consensus (or more precisely, the specific consensus of the powers that be) say otherwise, that's not going to irreparably damage my poor widdle feewings.  

My concern then is to identify what exactly is lacking in the PR, or if it's just a bad idea entirely.  In this case it's already been very informative.  I expected the weakest part of the PR to be the paucity of leveling options, which you and I have been arguing about, but instead the principal objection seems to be the lack of dishes with "avec" in the name, and reasons to make such.  Go figure.

**Comment by Coolthulhu** [comment]
> but instead the principal objection seems to be the lack of dishes with "avec" in the name

I don't think I get the joke you're making here. The argument is more like: one skill is bare early, one later. And this is a good argument, even if it's strawmanned easily.

**Comment by Zireael07** [comment]
@Coolthulhu: He's referring to the fact that @KA101 wants high-level cooking dishes before the split can happen.

**Comment by facepalm** [comment]
@Zireael07 
>@Coolthulhu: He's referring to the fact that @KA101 wants high-level cooking dishes before the split can happen.

Yes.  I've often heard that mid level cooking is just there to get to mutagen.  Ironic that it's the other way around.

@Coolthulhu 
>The argument is more like: one skill is bare early, one later. And this is a good argument, even if it's strawmanned easily.

It may be a good argument, but it's poor feedback.  There's no information there.  Okay, you think it's bare.  What is "bare?"  How much, and of what, needs to be added to make it not "bare," exactly?  All you've said this whole thread is "I don't think it's ready yet," with no hint of what "ready" entails in your mind.

Although I disagree that it merits keeping the skills merged, at least KA101's feedback held something constructive: an in-game need for high-end cooking recipes.  I can process that.  I can imagine what additions might fill that requirement.  I can estimate the effort needed to implement those additions.  I can decide whether or not it's worth my time to make that effort.

But "bare?" "More?" "Ready?" "Work on it?" Tells me nothing.

**Comment by Coolthulhu** [comment]
> at least KA101's feedback held something constructive

And mine didn't, despite me explicitly mentioning few things that can fix some of the issues? Despite explicitly mentioning how RNG wall is a major problem here?
More uses of improvised tools like pots and stills, wood ash as an ingredient (to make lye), bandage sterilization, alcohol distillation.
Not only those are very concrete examples and in the first post at that, they also show a direction: add recipes that can actually be used before the endgame when you're sitting at piles of gold, pondering what to do with your wealth.

And "bare" etc. is painfully obvious when you look at your own list in the first post. It is a list mostly of "how to grind the skill" rather than "what to create".
Grab an "Anarchist Cookbook" or "Improvised Munitions Handbook" if you want some ideas.

Plus, it's your job to make it look good rather than mine to show how to make it good. If you can't think of what should be done here, reject the criticism and the suggestions (without even explaining how are they lacking), then all suggestions are going to tell you nothing.

**Comment by facepalm** [comment]
>More uses of improvised tools like pots and stills, wood ash as an ingredient (to make lye), bandage sterilization, alcohol distillation.

And I acknowledged that those would be useful additions, thank you.  But KA101 came along and threatened to can the whole thing for a different reason entirely, so I haven't bothered adding them or anything else new until that gets resolved.

>Not only those are very concrete examples and in the first post at that, they also show a direction

A direction, yes, but not an endpoint.  When I pressed you to get an idea of how much of the direction was needed, I got answers containing approximately half the game.

>And "bare" etc. is painfully obvious when you look at your own list in the first post. It is a list mostly of "how to grind the skill" rather than "what to create".

I admit, I assumed anyone reading the list would also have read the paragraph before it explaining what it was.  My fault, I guess.  It is __explicitly__ a list of how to grind the skill.  That is how I introduced it, as the "grind to mutagen" pathway.  Aside from level 0, there are numerous other options one can create at each level, but not all of them are grind-friendly, and I wanted to make sure the player always had at least one good non-book option, and that anyone reading the PR would know that.

For example, I suggested ammonia or bleach at level 6 because that's what I'd personally use to grind past that level, but here's the full list of level 6 crafts:

 * Adrenaline Injector
 * Ammonia
 * Antiparasitic
 * Bleach
 * Diazepam
 * Gasoline
 * Heroin
 * Incendiary
 * Iodine tablets
 * LSD
 * Salt (from bleach)
 * Soap
 * Water purification tablets

**Comment by Coolthulhu** [comment]
> I admit, I assumed anyone reading the list would also have read the paragraph before it explaining what it was. My fault, I guess.

Lol'd at the passive aggressiveness.
>  It is explicitly a list of how to grind the skill.

And then you proceed to explicitly list almost all the good stuff except for the level 6. And yes, I not only read the entirety of your post, but also the diff.
It does look a tiny bit better with a full list, but outside of that one big level and stuff you listed, it's basically limited to flavored mutagen and ingredients. Some rare exceptions like meth. Rest is on the list in your OP.

You could start by moving parts of the lvl 6 down. I bet some of them are high school level chemistry.
It would probably be a good idea to make a thread on forum and get all the chemists interested.

**Comment by Zireael07** [comment]
@facepalm: Add to this PR the things you consider useful additions. If the PR isn't expanded, @KA101 will have even more reasons to say it won't be merged.

**Comment by facepalm** [comment]
Meh.  I've already got something on my plate which I could care less about but needs to be done to get KA101 to merge a PR.  I've made the arguments I think are relevant.  If it gets closed, it gets closed.

**Comment by KA101** [comment]
I'm not seeing a solution to the problem of worthless high-level cooking.  Closing, with leave to reopen should this work out the problem with making cooking worthless at high levels.

**Pull request closed without merging**
