### PR TITLE
Move gunsmith/blacksmith turret out of the direct path of the player

### PR DESCRIPTION
**Pull request by MoocowTG**
#### Summary
Balance "Move the isolated_road turret 3 tiles to the west"

#### Purpose of change

Prevent the player accidentally attacking the turret and losing their 20 hour character. Yes I'm mad.

#### Describe the solution

Move the turret out of the way.

#### Describe alternatives you've considered

Removing it altogether, but it's off to the side nicely here.

#### Testing

Spawned the location in world and made sure it's were I want it to be.

### CODE REVIEW

**Comment by casswedson** [comment]
so you want to move the turret that sits in between the 2 houses here; but a location does not need to make sense in a player-friendly / safety way, using the rationale "its inconvenient position ended up killing my character" is not valid, turn safe mode on, it will prevent you from attacking neutral monsters, generally pay attention at what you are doing
Screenshot from 2023-10-06 21-14-57

**Comment by MoocowTG** [comment]
Never would it have crossed my mind someone would argue against such a simple QoL change. Navigable terrain is a core principle of level design regardless of the type of game. Is there some reason you're trying to keep things inconvenient?

**Comment by oosyrag** [comment]
I'd move it 3 or 4 tiles southeast, then it would make still make sense and be more out of the way

**Comment by KHeket** [comment]
Maybe, what is better - place it to the roof at this place, where I mark? Because it will make the way safe for player, and also it reasonable to place turret to place, where the zombies cant get it, and the turret can attack potential enemies at the roofs?
image

**Pull request merged**
