### PR TITLE
Overmap path fixes

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Overmap pathing: allow subway, disallow rock"

#### Purpose of change

This is a follow-up to #50637. I was too focused on overland navigation and didn't consider underground.

#### Describe the solution

Don't allow pathing through solid rock / earth.
Allow vehicles to drive in the subway tunnels.

#### Describe alternatives you've considered

Special case burrowing mutants to allow pathing through rock? Seems like too much hassle, and burrowing is hard work so you probably want to avoid it anyway.

#### Testing

https://user-images.githubusercontent.com/8000047/129117211-63418e57-f575-4170-8a36-68ba0d6fd31f.mp4

#### Additional context

Seeing a lot more monsters in the subway tunnels than I ever remember seeing.

### CODE REVIEW

**Comment by actual-nh** [comment]
Re subway critters: See #48772.

**Comment by eltank** [comment]
Found an unrelated bug while testing this: #50696

**Comment by Venera3** [comment]
Do you think you can hook it up to handle rail vehicles? Turning's pretty wonky at the moment, and some assistance in gauging speeds/distance would be helpful.

**Comment by eltank** [comment]
> Do you think you can hook it up to handle rail vehicles? Turning's pretty wonky at the moment, and some assistance in gauging speeds/distance would be helpful.

I've added your feature request to the list (#49455). A prerequisite for autodriving rail vehicles is keeping track of where the wheels are. I'm planning on doing that anyway, mostly because I hate driving over any "loot piles" that I made. But there's an additional complication for rail vehicles, which is that when the track bends they temporarily go off-track with some of their wheels. Predicting how they're going to take a turn seems rather difficult at the moment. So... it's going to take a while.

**Pull request merged**
