### PR TITLE
Accessibility: Textual Vehicle Direction Indicator

### LINKED ISSUE #20951: Accessibility: Textual Vehicle Direction Indicator
Per discussion in [this Reddit thread](https://www.reddit.com/r/cataclysmdda/comments/686yf0/accessible_vehicles/), some kind of text-based indicator of which direction a vehicle is facing would improve accessibility a lot. Something like "Facing: 200 degrees," somewhere on the sidebar might help. Perhaps it could be a toggle option, much like the way gun targeting percentages are displayed.

### PR DESCRIPTION
**Pull request by OzoneH3**
Fixes #20951

* Vehicle direction indivator in degree ° (0 to 359) where 0° is north.

* Narrow sidebar

* Wide sidebar

### CODE REVIEW

**Comment by Mecares** [comment]
Maybe make it rough direction and degrees instead of only degrees?
Like N 355° or S 178° or even SW 225

**Comment by Theundyingcode** [comment]
Consumer vehicle compasses don't give you degrees thy just give N, NW, NE, W, E, SW, SE and S.  Though it would probably be better to show the 16 divisions (NNE etc.)

**Comment by Zireael07** [comment]
@Theundyingcode: Thing is, the request was made by a blind player who otherwise has no idea to tell the direction of the vehicle. So just N/NW/NNW are unlikely to be helpful.

**Comment by AMurkin** [comment]
Jenkins rebuild

**Pull request merged**
