### PR TITLE
Created executive zombie and its upgrade the sleazy executive zombie. [WIP]

### PR DESCRIPTION
**Pull request by Soyweiser**
#### Summary
SUMMARY: Content "New zombie type, the executive zombie, who drops clean (but damaged) clothes."

#### Purpose of change
Added a new zombie (main reason for doing so, creating a zombie without the FILTHY flag), the 'executive zombie', who drops clean clothing, and bashes people with its suitcase. Transforms into a 'sleazy executive zombie' over time (drops dirty clothing and had some minor stat upgrades), as various fluids leaked from its eyes/mouth over the zombies clothing.

The zombie can also drop cocaine and other items that are supposed to hint at the cause of death of this zombie being suicide. (one by drinking something that used to be in an empty canister (my idea was that this variant somehow got hold of a goo canister and thought consuming the blob was a good idea)).

Also has a chance to drop a lot of cash, which seemed to fit the evil ceo type I'm going for with the zombie here. (That is also why it only has cocaine as a drug drop, which is the 80's stock broker guy drug of choice in popular culture).

#### Additional context
Why is it still WIP? Because I have not added it to any spawn lists yet. I need to figure out suitable places and not make the zombie too common. Any ideas on where it should spawn?

Is the name 'sleazy executive zombie' too much? OrenAudeles suggested sleazy/slimy on discord, and I thought it seemed like a nice name.

### CODE REVIEW

**Comment by Theundyingcode** [comment]
Comment for the sole purpose of highlighting thread.  As maintainer of the mundane zombies mod, I wish to keep track of new zombie additions.

**Comment by JacobKessler** [comment]
It seems only natural that they would spawn in offices

**Comment by Soyweiser** [comment]
Tbh, I have no idea what kind of buildings spawn in the base game any more, I play with the various more building mods all the time, so I will have to do some digging to figure that out.

**Comment by kanedb** [comment]
It could spawn in mansion too

**Comment by SomeDeadGuy** [comment]
Why would executives not spoil their clothes right away, like any other zombie?
Like, they are regular people who sweat, defecate, and stuff. Their clothes would be dirty like any other zombie. I am not buying it at all in the game context.

**Pull request closed without merging**
