### PR TITLE
Change Cut Cotton to Patchwork, add Patchwork to Rags

### PR DESCRIPTION
**Pull request by Xpyder**
#### Summary
Balance "Change Cut Cotton to Patchwork, add Patchwork to Rags"

#### Purpose of change
We're moving away from Rags towards Patchwork Sheets and Cotton Sheets.

#### Describe the solution
This makes it so cutting up cotton stuff gives patchwork sheets, and you can repurpose them as rags if you need to use them in an older recipe

Reupurposing is instant because you don't actually need to change them, you just change how you use them (like to stop bleeding)

#### Describe alternatives you've considered
doing nothing, or aborting the conversion to patchwork sheets

#### Testing
tested cutting up filthy clothes -> filthy cotton patches -> filthy rags
tested disassembling bed sheets -> patchwork cotton sheet -> cotton patches -> rags
tested cutting bed sheets -> cotton patches
verified all weights are close and lower with material loss depending on route

#### Additional context
This is an interim step but one I consider important

For a separate PR:
The volume/weight for bed sheets is WAY off.  I balanced these based on weight (as that's a more reliable measure of mass) and density as given by the previous author.

But a 5L cotton sheet drops to 0.8 L when disassembled which indicates to me both that the sheet volume is too high (makes sense as it's an old item) and that the weight needs to be checked.

### CODE REVIEW

**Comment by Xpyder** [comment]
Fixes 49694

**Comment by Maleclypse** [comment]
Change this `Category: Balance` to `Balance: "Change Cut Cotton to Patchwork, add Patchwork to Rags"`

**Comment by Xpyder** [comment]
> Change this `Category: Balance` to `Balance: "Change Cut Cotton to Patchwork, add Patchwork to Rags"` under summary and that'll fix your PR test failure.

ty!

**Comment by Xpyder** [comment]
I need to do some more testing

**Comment by Xpyder** [comment]
There's a bug when trying to cut up filthy stuff, the patchwork (filthy) doesn't spawn.  I'm reviewing the handler.cpp and harvest.json files now but if anyone knows where that is and can point me I'd be much obliged

**Comment by Xpyder** [comment]
My current guess is either
 - that the check to create/set them as filthy assumes ammo can't be filthy, and since these are listed as ammo_type: Components it's bugging out
 - or the game doesn't know how to present the filthy item

I'm having trouble tracing that check though.  I got it to here but I'm having trouble getting beyond
src\item.cpp
bool item::is_filthy() const
\/
bool item::has_flag( const flag_id &f ) const
\/
bool item::has_own_flag( const flag_id &f ) const

**Comment by Xpyder** [comment]
after studying the way sheet_cotton_patchwork was implemented I think that was meant to be for a possible cloth bolt.

I'm adding a cotton_patch intermediate item to replace rags with until I can get clarity on whether we want to use actual clothing bolts/sheets and if so to allow interoperability during the transition

**Comment by Xpyder** [comment]
the drop qty is off when you disassemble a sheet -> disassemble the patches
cutting sheet is correct (by weight)
cutting patches is correct (by weight)
disassemble patches must be incorrect

**Comment by Xpyder** [comment]
forgot to lint

**Comment by Xpyder** [comment]
I think this is ready to go whenever we want it.  The main thing it would allow is more recipes to start using Patchwork Cotton sheets / parts instead of rags

**Comment by OneThousandResets** [comment]
Sorry but I am a bit lost. I speak as a long time player. I am mindful that I am seeing work in progress. 

¿I am seeing here a renaming and volume rebalancing of rags and cotton sheets as cotton sheet (industrial quality), patchwork cotton sheet (makeshift), patchwork cotton clothing parts (rags?), and rags as leftover item from previous commits?
That's what I am understanding. Besides the fact that this commit nuked tailoring due to incompatibility with the recipes ( no problem, we are in experimental), the names are confusing.

Let me present my thoughts:
It makes sense to have a "crude textile" (rags) and a refined, processed one (cotton sheets) although that is a distinction that could already be discussed as unnecessary. The idea of "Fiber" -> "Cloth" -> "Clothing" seems deep enough to me.

The proposal of:
"Fiber" -> "crude cloth" -> ("usable cloth" OR "industrial quality cloth") -> "Clothing"
or, In concrete terms:
"thread" -> "patchwork cotton clothing parts" -> ("patchwork cotton sheet" -> "cotton sheet") -> "Clothing"

Seems an unnecessary intermediate. 
I have similar thoughts regarding the variety in types of buttons and zippers. Unnecessary in practice and helps pollute the crafting and inventory management.

In any case, my frustration is indeed sprout from the surprise of having my tidy crafting process becoming suddenly confusing. If someone could point me to the latest commit before those changes I would be grateful.

Godspeed.

**Comment by Xpyder** [comment]
The goal is to move away from using rags as a component, to using cotton sheets/patchwork cotton sheets.
Currently those two are implemented as ammo which is causing weird issues like "cutting up filthy hoodie doesn't drop filthy parts"
the addition of the patchwork cotton parts was just to get the pr working, it's based on rags but with some changes to make it fit into the patchwork path.

Originally I thought about just replacing rags, but then the IDs wouldn't match and I don't know how to get the game to automatically port over existing items.

Eventually your "tidy crafting process" should uniformly be "cut up cotton clothing -> cotton clothing parts -> cotton patchwork sheets -> your item" not "cut up cotton clothing -> rags -> everything" (at least so far as I can tell that's the intention of the "tailoring rework pr" which I don't have handy atm)

**Comment by Xpyder** [comment]
also just to be clear: I the idea to switch to patchwork/cotton sheets is not mine.  It's been around for a while.

All this pr does is make it EASIER to get the parts needed to make them.

**Comment by OneThousandResets** [comment]
Appreciate it!

Keep up this great game.

**Pull request merged**
