### PR TITLE
1860s part 2

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This should have been the second commit in the Colt 1860 PR, but somehow I forgot to add it. 
I should (and will) get more sleep.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
This seems like an odd change. It can be assumed that most older firearms would be made of mild steel, excepting older cannons commonly made of cast iron (which is war harder and more brittle than wrought iron) or bronze.

Unless the iron material is supposed to be extremely low-quality steel instead of wrought iron (which would be a naming failure), I am not sure if this makes sense.

This is even stranger if the versions in the game are assumed to include modern reproductions (Uberti, for example) in addition to genuine antiques.

**Comment by BorkBorkGoesTheCode** [comment]
>This seems like an odd change. It can be assumed that most older firearms would be made of mild steel, excepting older cannons commonly made of cast iron (which is war harder and more brittle than wrought iron) or bronze.

Is mild steel represented by budget steel in-game?

**Comment by DangerNoodle** [comment]
I assumed budget steel literally only existed to nerf medieval weapons via item-group dilution.

**Comment by mugling** [comment]
> I assumed budget steel literally only existed to nerf medieval weapons via item-group dilution.

Yes, this

**Comment by DangerNoodle** [comment]
So right now I am unsure about this change. And yet you have already changed the material for another old presumably-steel revolver? How did that get merged unquestioned, especially when it is mostly just a flavor detail in this situation?

**Comment by BorkBorkGoesTheCode** [comment]
> So right now I am unsure about this change. And yet you have already changed the material for another old presumably-steel revolver? How did that get merged unquestioned, especially when it is mostly just a flavor detail in this situation?

???

**Comment by DangerNoodle** [comment]
This is part 2, correct?

**Comment by BorkBorkGoesTheCode** [comment]
> This should have been the second commit in the Colt 1860 PR, but somehow I forgot to add it. 
 I should (and will) get more sleep.

https://github.com/CleverRaven/Cataclysm-DDA/pull/18524

Please review the code changes in both PRs. And read the descriptions of both PRs.

**Comment by DangerNoodle** [comment]
I see. The other changes in that pull request, it is just the material change than seems a bit peculiar.

**Comment by BorkBorkGoesTheCode** [comment]
I am going to flesh out budget_steel in a separate PR.

**Comment by DangerNoodle** [comment]
Should it be renamed mild steel in that case? If we intend to use it for less bizarre specialized purposes.

**Comment by mugling** [comment]
> Should it be renamed mild steel in that case?

Yes

**Pull request closed without merging**
