### PR TITLE
Remove include of vehicle.h from mapdata.h

### PR DESCRIPTION
**Pull request by BevapDin**
Turns out, vehicle.h is still include (for no real reason at all) by mapdata.h

Really, it is meant to _remove_ something. The additions are just because the other cpp files did not include the header they should have included in the first place. Some don't even need vehicle.h, only line.h

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good catch there with that vehicle.h - half (or more) of the files that had it included probably didn't need it.

I think that item.h could be removed from map.h in similar way.
map.h has 2 functions that return item (`water_from` and `swater_from`) and it has `map_stack` struct which has a `std::list<item>*` member.
The `water_from` part could probably be handled by returning a `unique_ptr` instead of the item itself. I don't know if `std::list<item>*` would be allowed with item being forward declared, but it looks like it would.

**Comment by BevapDin** [comment]
> map.h has 2 functions that return item

That is fine, the declaration does not need to know the inner parts of the class. I just found a nice overview at http://stackoverflow.com/questions/553682/when-can-i-use-a-forward-declaration

Whether `std::list<item>` needs the class is more difficult to say. AFAIK, implementations of the stdlib are free to require the full object.

There are some inline functions (`update_lum_add`) in mapdata.h that still need to know the complete item.

However, one thing can be done: move the submap class into a separate header, included by mapbuffer.cpp, map.cpp and editmap.cpp. This would also allow to make most submap functions inline.

**Comment by Coolthulhu** [comment]
> Whether `std::list<item>` needs the class is more difficult to say.

And what about `std::list<item>*`? Can template instances be forward declared?

**Comment by BevapDin** [comment]
> And what about  std::list<item>* ? Can template instances be forward declared?

Yes (I'm relatively sure). If absolutely required, one can always add a pseudo wrapper that can definitely be forwarded:
```C++
class std_list_item : public std::list<item> { };
```

But you don't want to go that way. Besides, `std::list<item>::iterator` is used in the `map_stack` class, but maybe that can be moved in a separate header that only contains the `map_stack` class.

in my opinion changing actual code (e.g. changing function parameters) only to avoid including a header is just not worth it. It creates more code that can fail and makes it difficult to understand. 

Many cpp files that include map.h required knowledge of the item class anyway.

**Pull request merged**
