### PR TITLE
Mainline roof-mounted external tank (200L) + add roof-mounted external tank (100L)

### LINKED ISSUE #38968: Steel drum (100L) is not mountable to vehicles
I'm searching for a bigger tank for my car and was happy i found some 100L steel drums at a military helipad, but as it turns out you can only roof mount 200L drums to your vehicle

My wish: Make 100L drums mountable

Alternatively convert the 100L drums into 200L

Thanks for your work!

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Content "Aftershock Mod - Add roof-mounted tank (100L)"`

#### Purpose of change

This fixes #38968. Sorry, it took me so long to get what you were talking about ;-)

<br />
Hope you like it.
<br /><br />

#### Screenshot(s)

grafik

grafik

### CODE REVIEW

**Comment by Maddremor** [comment]
What's sci-fi about roof mounted tanks? Why put it into Aftershock?

**Comment by Pupsi-Mupsi** [comment]
Don't ask me. Here is a picture of my car:

grafik

Just kidding ;-)

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> What's sci-fi about roof mounted tanks? Why put it into Aftershock?

BTW- The 200l version was already part of aftershock. I merely added the 100l roof mounted tank.

**Comment by John-Candlebury** [comment]
You should shift this to vanilla. I dont think either this one or the 200lt tank should be aftershock content.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> You should shift this to vanilla. I dont think either this one or the 200lt tank should be aftershock content.

Well, I could help with that, but I don't know how to mograte these things without breaking any savegames. Can you point me in the right direction?

**Comment by anothersimulacrum** [comment]
No need to worry about that when moving things to vanilla. Everyone has vanilla loaded, so it just works seamlessly.

The issue is the other way, because not everyone has whatever mod something has been migrated to loaded, and then they get errors without migration.

**Comment by Pupsi-Mupsi** [comment]
Like this?

Well, I was being cautious. Thought I would have to change ids ("id": "afs_roof_external_tank") or at least remove the prefix "afs".

**Pull request merged**
