### PR TITLE
Update Visual Studio builds and Appveyor

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: None

#### Purpose of change

We had too many different Visual Studio project files and build options that provided different discrete sets of functionality (e.g. unit testing only available in one set of project files, dependencies from vcpkg in another set of project files) which led to confusion about which to use when and a subpar developer experience.

Additionally, because our Appveyor builds were using vcpkg for dependencies but our vcpkg based project files weren't set up to build and run unit tests, we were never actually running our unit test suite in an actual Windows environment.

#### Describe the solution

I've consolidated all of the different options down into a single one that uses vcpkg for dependencies and builds a statically linked Cataclysm executable and unit test executable, so development and unit testing can all be done within a single solution. That same solution is used within Appveyor, which now runs the unit tests.

I also updated the documentation around compiling with Visual Studio to reflect the changes and be a bit more hand-holding (e.g. specifying the user has to select the startup project, change the working directory, and so on), as well as calling out how to run the unit tests.

In doing this, I found one unit test that failed because of a Windows issue and added a workaround in b792877.

#### Describe alternatives you've considered

I thought about keeping the dynamically linked and statically linked variants but I don't see a strong case for it versus the clarity of having a single way to support and maintain for building the project in Visual Studio.

#### Testing

Confirmed the project builds, the game launches, the unit tests run and all pass.

Confirmed on my Appveyor instance that it builds and the tests pass. This shouldn't be merged until it passes on the CleverRaven instance though--Appveyor has some settings that are not defined in the .appveyor.yml file and are just in the web interface, so we need to be sure it works here.

#### Additional context

*random screenshot from the test explorer showing tests grouped by category*
image

### CODE REVIEW

**Comment by Pupsi-Mupsi** [comment]
Thanks a lot!!!

Would you mind adding .\ to 

`vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext`

 doc/COMPILING/COMPILING-VS-VCPKG.md

**Comment by ralreegorganon** [comment]
> Would you mind adding .\ to

Sure. I see that they were not consistent, so that makes them consistent now.

**Comment by Pupsi-Mupsi** [comment]
Followed all the steps and could not get VS2019 to compile cdda.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md

Error after "4. Install (or upgrade) neccessary packages with following command line:"
`.\vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext`

grafik

**Comment by CodeBandit** [comment]
image
There's an issue getting mpg123 installed as described above

**Pull request merged**
