### PR TITLE
Correctly namespace more math functions.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
As outlined in #39388 these non-standard invocations of math functions are problematic.

#### Describe the solution
Stick em in the std namespace.

#### Testing
Needs to build, and I expect lgtm to agree it cleared up a bunch of alerts.

#### Additional context
I realized something else, implementations are *allowed* to put e.g. pow() in the global namespace in <cmath>, but they are also allowed not to, which would fail our build on such a system.

### CODE REVIEW

**Comment by kevingranade** [comment]
Weird roadbump, GCC standard library does not export sqrtf() into the std namespace.
https://stackoverflow.com/questions/43183252/cmake-sqrtf-is-not-a-member-of-std

**Comment by jbytheway** [comment]
> Weird roadbump, GCC standard library does not export sqrtf() into the std namespace.
> https://stackoverflow.com/questions/43183252/cmake-sqrtf-is-not-a-member-of-std

Yeah, I remember running into this issue when I looked into some related warnings.  I didn't come up with a good answer.

**Comment by kevingranade** [comment]
AFAICT the answer is either just don't use it or export it into std ourselves.
I really don't like the latter because it essentially means we have to carry around our own cmath wrapper and use it everywhere.

**Comment by jbytheway** [comment]
Agreed.  I think just don't use it.  It will lead to more `-Wdouble-promotion` errors errors if we ever turn on that particular warning, but that's life.

**Comment by kevingranade** [comment]
Turns out same story with powf() >_<

**Pull request merged**
