### PR TITLE
Added OM_MOVE and u_near_om_location EOC effects

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Added OM_MOVE and u_near_om_location EOC effects"

#### Purpose of change
for #55002 wanted to make it so that their stocks refresh not when you talk to them but when you are nearby since on talking feels a little janky when their wares are on shelves.  If you were to look at the shelves and see something you wanted, talk to the shopkeeper, then it be removed as it was sold *sometime that week* that would feel **real bad**. 

#### Describe the solution
Adds a new EOC type that are triggered when you swap OMTs. This is to be a little less taxing than just running an aggressive recurring EOC with conditionals. 

Add new conditional u_near_om_location and npc_near_om_location for testing if you aren't in the OMT but near it. This is so you can make sure you are near an OMT and can do whatever effects need to happen without being point blank. So for example you wont see the shopkeeper shelves swap around in front of your eyes since you'll still be a distance away.

Added some docs

#### Testing
I'm using this EOC to test:
```json
{
    "type": "effect_on_condition",
    "id": "test",
"eoc_type": "OM_MOVE",
    "condition": { "u_near_om_location": "isolated_house_farm_gunsmith" },
    "effect": [ { "u_message": "AMBIENT_LAB_SUBWAY", "snippet": true, "sound": true } ]
  }
```

### CODE REVIEW

**Comment by Venera3** [comment]
Does it check adjacent OMs only, or can it do arbitrary ranges? Would you also update the relevant docs (`NPC.md` for the condition and `Effect_on_condition.md` for the new EOC type).

**Comment by Ramza13** [comment]
This looks great!  I would request you add an npc version to the om_near just because in some cases its possible the player character will be the npc(confusing I know).

**Comment by bombasticSlacks** [comment]
Alright I'll move to draft and add the npc version, a range and documentation.

**Comment by Ramza13** [comment]
I'll probably update it myself as a minor part of something else, but for future reference anytime we are adding an int or time duration parameter to a dialog function we want to use an int_or_var or a duration_or_var instead.  This automatically allows using variables in place of the value.

**Pull request merged**
