### PR TITLE
[WIP] Building spawn tweaks for 0.D

### PR DESCRIPTION
**Pull request by acidia**
Don't spoil anything in this PR, let it be a surprise for people in 0.D!

I heard that work had begun to get a 0.D release out in the relative future so I figured I'd make something to help gather attention when it released.  I'm hoping to get it together by the end of the year but that is very unpredictable.  

At 22x11+ the z-0 footprint of the national guard camp is nearly three times as large as anything else.  Last time I was around such large structures weren't possible but in a couple dozen worlds I've only seen one have an intersection issue.
This is the basic layout of the base on z-0.

http://imgur.com/a/xYiNb
z:0
^ (dark green) - shoppette
^ (light blue) - gym
^ (light green) - barracks or post commander's house
^ (dark blue) - fuel point
A (light green) - asp
A (red) - arms rooms
A (yellow/red) - advanced warfare center
B (dark green) - battalion operations facility (BN)
C (dark green) - company operations facility (COF)
D (dark green) - dining facility
G (gray) - gate
H (red) - aid station
H (yellow) - helipad
H (yellow inverted) - heliport
L (yellow) - launch station
O (gray) - parking lot
O (green) - motor pool
O (white) - wreck bay
R (green) - small arms range
z:-1
0 (light gray) cavern/construction zones
B (green) battalion HQ basement
L (blue) labs from top to bottom, left to right: weapons lab, genetics lab, rocketry lab, and microbiology/virology lab
M (green inverted) military complex
O (dark gray) house basement
R (red) reactor
"-" (green) sewer

My current preference is to have the base be manned by robots that are similar to the Star Wars battle droids.  Relatively fragile anthropomorphic robots that are stock armed with 7.62 assault or battle rifles.  Their combat ability would derive from their numbers, a “go prone” ability to boost dodge that would trigger when a fellow robot was destroyed and the player was still X tiles away, and the ability to fire flares when under attack in the dark.  Slow speed and audible voice commands would allow new players to escape an accidental encounter on the outskirts of the base.  

So, run around the two levels of the base and give me feedback on any errors you see or what you'd like the base to evolve into.  If it spawns in your world it is easy to find by searching “guard” on the world map.  The four additions are all jsons so drop them in your existing game to see it with a tileset.

Don't spoil anything in this PR, let it be a surprise for people in 0.D!

### CODE REVIEW

**Comment by John-Candlebury** [comment]
Of all the ideas the combat robots seem the best.

Great work as always!

**Comment by pisskop** [comment]
Inverted G looks a little straining.  Love it though, way past the standards and something I could only aspire to

**Comment by vache** [comment]
ZOMG I've been waiting for your return.  I have a handful of ideas to fling at your direction.

I'm in favor of robot enemies.  They're pretty underutilized, especially in the low to medium-threat category, and they provide some much needed ranged threat.  I agree with pisskop too, maybe use line drawing for the walls?  Also, you're not necessarily constrained to a rectangular layout, you can make the walls follow the layout of the base closely and remove the rest and it should still work.

**Comment by Coolthulhu** [comment]
Now that's a load of text.
Is most of it copy+paste? I mean, in a good sense: if most of the definitions are totally identical, it will be easy to parse it with search+replace if we update mapgen to handle big blocks of similar definitions.
Having consistent, identical "palettes" would make parsing the definitions - and reading them afterwards - much easier. For example, if in every definition "1" meant a column or something like that, "." meant grass/dirt/shrub/tree, "c" meant crate (with 1/3 chance of being open).

**Comment by acidia** [comment]
I still use my old python script that got updated by wormingdead under utilities/building-utility/deconstruct.py.  I make a giant ascii map and update the palette and it'll cut up the map into a json.  If I could just define a palette for all of them to use it would cut the final json to 1/2-1/3 of its current size but wouldn't really save me any time.  If we do set a standard palette then we might want to allow overrides because I typically go back and manually add the tiles that only occur in one or two chunks.

Ya, I don't particularly like the white "G" on a green background either... I just can't think of anything that works better.  Should be something that sticks out so that it is evident that all of the buildings are part of a single group.  Black "G" look any better?  I really like the idea of using a colored road/path to denote the wall.  Do we have the double line character in all of the variants that single lines have?

I've already drawn up a little 7x2 extension off the top for a set of landing pads so it'll start loosing the boxy appearance.  I'll probably add one more extension and might cut a corner or two off but I want to leave plenty of room as a woods/buffer zone so players can escape if they decide they aren't up to the challenge.

**Comment by vache** [comment]
I don't think we can do the double line drawing (though I'd love to be wrong on this one), but you can probably get a similar effect with a single line inverted color, like a black line on a brown background.

Do you have anything in mind for specific missions or goals for the player, perhaps something involving the old guard?  

Also, I sent you a message on the forums about some ideas

**Comment by ZhilkinSerg** [comment]
Looks terrific even with no loot or vehicles included.

**Comment by acidia** [comment]
Changed the overmap color scheme and added the lower level.  Check the main post for an updated map.  I decided to keep most buildings on the lower level as generic "military complex" tiles since they don't fall into nice little squares like z0 and it makes the base more of a labyrinth to navigate.  The building style is very different from necropolis in that small passages and back doors are the main means of moving about instead of the large vehicle tunnels.

I'll be going through and cutting out the unused solid rock map tiles when things are finalized.

As far as missions go, I'm uncertain if it is going to be possible to keep the base on the default overmap.  I might need to make a "not on 1st overmap" to prevent it from playing too large a role in the world.  By putting it in the 2nd or 3rd overmap it encourages exploration and creates a nice end of game location to journey to.  After it has been incorporated into the game I'm going to go back and see about making it alter the world around it (burning down forests/towns in a given radius, spawning outposts, having respawning troops with very low numbers but very long range).  By taking it off the original over map I can create a much larger war zone without accidentally hurting new characters.

**Comment by vache** [comment]
I really like the idea of having it spawn on not the first overmap, especially if we could get some sort of general system that supports that set up, like creating some sort of queue for specials and populating it based on what quests are available, or only spawning certain locations after the player has lived long enough or traveled far enough.

**Comment by acidia** [comment]
Prototyping the enemies, looks like we'll be starting with something like:
W11B10 - "Wraitheon (11B) Infantry 10 Level.  Part of Wraitheon's series of one-to-one auxiliaries designed to seamlessly integrate with more traditional forces." 7.62 weapon with alt thermobaric grenade or 2

W11B20 (240) - "Wraitheon (11B) Infantry 20 Level manning a 240."  Essentially a turret till it runs out of ammo

W11B20B4 - "Wraitheon (11B) Infantry 20 Level (B4) Sniper."  Possibly 50cal weapon, rare and alone

W11B30 - "Wraitheon (11B) Infantry 30 Level." 7.62 weapon with alt law, slightly better stats, one per squad

W11H10 - "Wraitheon (11H) Anti-Tank Infantry 10 Level."  Don't have much use for anti-tank in a zombified world but the flash launcher/carl gustaf is fairly fitting.  Rare.  Isn't an active MOS at the moment but it makes sense to recreate it with robots and power armor running around.

W12B10 - "Wraitheon (12B) Combat Engineer 10 Level."  Flamethrower with a small chance of a c4 drop.

W12H10 - "Wraitheon (12H) Construction Engineer 10 Level." 7.62 with possible tool drops, common but away from combat

W18B20 - "Wraitheon (18B) Special Forces Weapon Sergeant 20 Level." Top Secret

W18Z30 - "Wraitheon (18Z) Special Forces Senior Sergeant 30 Level." Boss

W74D10 - "Wraitheon (74D) CBRN Specialist 10 Level." Completely useless, will contaminate player in melee combat, drops radiation detectors

Considering:
W13F10 - "Wraitheon (13F) Fire Support 10 Level." 

The biggest problem at the moment is balancing firepower... even unpowered basic power armor can walk right up to a .50cal turret and let it empty its entire magazine at 0 range.  Making enemies near-peers renders most player's weapons useless against them.  Using newfangled energy weapons doesn't work lore wise.  That's why the fire support guy might need to be included, if "player wearing magic invulnerability suit" -> "call in rocket artillery or fascam".

**Comment by BorkBorkGoesTheCode** [comment]
.50 BMG is weak right now, due to balance nerfs to its damage and pierce. Its damage is only 9 more than .308 cartridges, it cannot use its extreme range due to hardcoded aim limits, and its pierce is weak.

**Pull request closed without merging**
