### PR TITLE
[Partially merged] Augmentation Associate and Augmentative Tech Review rebalance

### PR DESCRIPTION
**Pull request by ghost**
```SUMMARY: Balance "Tweaked Augmentation Associate cost, and made Augmentative Tech Review ."```  

#### Purpose of change
With the removal of bionics recipes, the magazine Augmentative Tech Review is now largely useless, as all it does is train electronics from 4 to 5. It also makes Augmentation Associate weaker, as they have no book to get recipes from or train from.

With manual bionics enabled, Autodoc Specialist has no purpose, so it's a large waste of points to take the profession.

### 1. Autodoc Specialist increases success chance for both manual installation and Autodoc installation of bionics.

Nothing much to say here; this makes the profession worth taking regardless of the method you choose.

### 2. Reduced Augmentation Associate cost to 4 and removed the Augmentative Tech Review book from it.

Without a usable book, Augmentation Associate starts with something that does very little, so it's been removed from them. Since they also no longer have ready access to crafting them, I reduced their point cost.

### 3. Augmentative Tech Review now trains electronics from 2 to 5, instead of 4 to 5.

This makes it a usable book that's actually good to find.

### CODE REVIEW

**Comment by kevingranade** [comment]
> Bright Nights is also a good place for bionics and mininuke recipes

If you want to start up your own mod  you can have total freedom with what you put in it, but you're turning BN into a dumping ground for rejected content and it needs to stop.

**Comment by Xhuis** [comment]
I don't agree with that. From what I've gathered from speaking with the people considered in charge of the mod it's based around a less-simulationist and more science-fiction version of the game. Nuclear reactors are advanced and common enough to exist as civilian power plants commonly.

If anything, I think that Bright Nights has received highly little content until I started adding to it, and has previously been used for things deemed too "science fiction' for the base game, like the Solar Panels CBM.

I do not think I'm the only one with this opinion.
image

**Comment by Xhuis** [comment]
BN is a core content pack, and I was under the assumption that it deserved expansion for its own purposes just as much as DDA. It'd be like asking a single person to clear every change on baseline; while you *are* the owner of the repository (and I certainly don't mean to discount that!), it's crazy to ask you or any other one person to closely inspect and clear every PR. As a core content pack, woudpnt

**Comment by kevingranade** [comment]
I dont follow your argument, let me restate my position.
If OKing additions to BN falls to me, I'm rejecting craftable CBMs and mininuke as an addition, as they dont fit in BN to the best of my knowledge.

If you want to either make a new mod or take ownership of BN, you're free to do whatever you want with it.

**Comment by Night-Pryanik** [comment]
> Augmentative Tech Review now trains electronics from 0 to 4, instead of 4 to 5.

I'd say full noob in electronics can't learn much from reading about such an advanced stuff like bionics augmentations. 2 to 5 or 2 to 6 probably be better?

**Comment by Xhuis** [comment]
I'm going to have to do some thinking on all this, as I'm going to be leaving for a 3/4-day camping trip in a few hours. I'm unsure whether or not I'd like to take ownership of BN, as I think that's something that Coolthulu is entitled to. I suppose I'd be fine with being added to the "maintainer" list for the mod, but not without approval from them.

**Comment by Xhuis** [comment]
I was worn down enough by my trip that I don't have much drive to argue about this, so I'll remove the recipes from this PR and centralize it to only modifying the stats.

**Comment by kevingranade** [comment]
I'm not seeing a compelling reason to buff the augmentation book, especially since it's a drop-only item now, so I reverted that part, and squashed the rest.

**Comment by Xhuis** [comment]
Aight.

**Pull request closed without merging**
