### PR TITLE
Bright Nights: Makes antibiotics more effective, and adds Verum Remedium, an extremely rare panacea that cures earthly wounds (also astyles item_factory.cpp)

### PR DESCRIPTION
**Pull request by ghost**
Bright Nights tends to err more towards faster healing, in both mending limbs and bandaging wounds. As such, in light of the changes of how antibiotics now function, I made this PR.
* Atreyupan effectiveness is equal to that of strong antibiotics in normal DDA
* Regular antibiotics reverse normal infection progression, and tremendously increase natural recovery chance of bites and infections (+400)

I also added a new item called Verum Remedium to Bright Nights. This pill, found very, very rarely in labs (only spawns in `chem_lab` item group, with a weight of 1), was under development before the Cataclysm, utilizing blob matter, nanobots, and purifier. Over a one-minute period of time, a dose will remove infections, heal all limbs by 100 hit points, and reduce pain by 100. In addition, for the ten turns that it affects you, you gain +20 to speed, and +2 to all stats.

Code-wise:
* Added the `STRONG_ANTIBIOTIC` and `PANACEA` use actions.
* Added the `strong_antibiotic` and `panacea` effects. `strong_antibiotic` adds +400 to bite and infection recovery chances, and reverses their durations. `panacea` guarantees recovery from them, as well as healing each limb by 10 hit points and reducing pain by 10 each turn, as well as boosting speed by 20 and all stats by 2 while active.
* Astyled my changes in `item_factory.cpp` with my astyle batch file once I finished working on it, and unintentionally astyled the entire file. So that's a thing now.

If Verum Remedium would be an interesting addition to the base game, I'd be happy to move it into it, but something that powerful seems difficult to justify in a simulationist approach, even with enhanced technology like in DDA's United States. However, in a more science fiction approach, like that of Bright Nights, it's perfect.

### CODE REVIEW

**Comment by John-Candlebury** [comment]
I like them both! It gets my 👍 

If you want some feedback maybe you can think of a more high-tech name for verum remedium?
That said, if you like the current name, there's no real need to change it.


--

By the way Brightnights is supposed to be somewhere vaguely eastern-european (of course you cant really notice that right now). Not necessary to take it into account for this, but maybe it can give you ideas in the future.

**Comment by Mecares** [comment]
That sounds ridiciously overpowered.

**Comment by sfsworms** [comment]
It's okay if it's balanced with rarity. It'd be the one saving throw.

**Comment by John-Candlebury** [comment]
Yeah its basically an amulet of livesaving

**Comment by Night-Pryanik** [comment]
For the future - please do all the astyling in a separate commit.

**Comment by Xhuis** [comment]
The astyle changes occurred because the file hadn't been properly astyled in a long time, and when I made my changes and ran astyle, it did so. It'd be easy enough for me to revert it if you wanted that.

**Comment by Night-Pryanik** [comment]
As I said, if you're going to astyle large chunk of code and especially if astyling isn't the main feature of your PR, please make that astyling in a separate commit.

**Comment by Night-Pryanik** [comment]
Third time: in your future PRs (if any) please make major astyle (if any) in a separate commit.

**Comment by Xhuis** [comment]
I know. I'm understanding your point, but you're not clarifying what you mean.
* [This is a commit.](https://github.com/CleverRaven/Cataclysm-DDA/pull/24640/commits/f653d069db7750fe45b737a0eda5fb6771f6ef76) It is a code change in a pull request, and a pull request can have several commits, but each pull request builds its code using the commit.
* [This is a pull request.](https://github.com/CleverRaven/Cataclysm-DDA/pull/24640) It is a separate code change listed separately on the tracker.

Does that clarify things?

**Comment by Xhuis** [comment]
There.

**Comment by ZhilkinSerg** [comment]
If you astyled whole file you need to remove it from `astyle_blacklist`.

**Comment by Xhuis** [comment]
I didn't know that file even existed, my mistake.

**Pull request merged**
