### PR TITLE
Double spaces after punctuation

### PR DESCRIPTION
**Pull request by Cyrano7**

### CODE REVIEW

**Comment by codemime** [comment]
> Double spaces after punctuation

@mugling Is it possible to add a rule to your linter to check this in other json files?

**Comment by mugling** [comment]
@codemime yes, entirely so. Are there any possibilities of false positives though?

**Comment by codemime** [comment]
> Are there any possibilities of false positives though?

I'd try to add something like:
- not less than two spaces between `.` `;` `!` `?`  (or the last mark in a row) and the next (if any) letter

and find out. An example of three spaces in a row is already here: 
```c++
"desc": ["Strength - 3;   Dexterity - 3"
```

**Comment by mugling** [comment]
PCRE: `s/([.;!?]) [^ ]/$1  /g`

**Comment by codemime** [comment]
@mugling There are false positives in case of abbreviations: `"Skorpion Vz. 82"`.
Maybe `([.;!?]) [A-Z]`?

**Comment by mugling** [comment]
Sure but we should only apply it to `description`?

**Comment by codemime** [comment]
But abbreviations may exist there too.
However, my version gives false positives on names (as in `J. R. Bob`). I don't know yet how to overcome this. Trickier example: `Mr. Johns`.

**Pull request merged**
