### PR TITLE
Enable effect_on_conditions to affect npcs

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Up until now recurring effect_on_conditions haven't run on npcs.  So for example all the faulty bionics I unhardcoded haven't been affecting npcs.  Same for weather though all that affects at the moment is npcs not getting wet from snow.  Add global variable support to aid with using this for #50685.

#### Describe the solution
Moved the effect_on_conditions and inactive_effect_queues into character.  NPC's now have there own queues and own inactive eocs.   
Add two new parameters to effect_on_conditions runs_on_npcs and global.  
If runs_on_npcs is true the eoc will be run on the player's queue and the npc's queues.  This will work with bionics/traits but not weather.  This is intended for eocs tied to bionics/traits.
If global is true the eoc will be run in the players queue and their inactive queue.  When it is run it will run on the player and all npcs.  This is intended for weather style effects hitting everyone in the area.

Added global switch to variable usage.  This allows using the player characters variables even when running on an npc.  This is needed for my portal work #50685 to enable having a central location for truth as to the storm's strength while still running the eocs on npcs.

#### Describe alternatives you've considered
It feels a little clunky to me in terms of easy understanding but it works.  The distinction exists for performance reasons. 

#### Testing
Used this json and debug commands
```
  {
    "type": "effect_on_condition",
    "id": "mutation_test",
    "run_for_npcs": true,
    "recurrence_min": "5 seconds",
    "recurrence_max": "7 seconds",
    "condition": { "u_has_trait": "PROF_HUB01_ANCILLIARY" },
    "deactivate_condition": { "not": { "u_has_trait": "PROF_HUB01_ANCILLIARY" } },
    "effect": [ { "u_mod_radiation": 10 } ]
  },
  {
    "type": "effect_on_condition",
    "id": "weather_test",
    "global": true,
    "recurrence_min": 6,
    "recurrence_max": 6,
    "condition": { "and": [ { "is_weather": "snowstorm" }, "u_is_outside" ] },
    "deactivate_condition": { "not": { "is_weather": "snowstorm" } },
    "effect": [ { "u_mod_radiation": 10 } ]
  },
  {
    "type": "effect_on_condition",
    "id": "test3",
    "//": "Increases the portal storms strength.",
    "recurrence_min": 1,
    "recurrence_max": 1,
    "effect": [
      { "u_adjust_var": "ps_str", "type": "weather", "context": "ps", "adjustment": 1 }
    ]
  },
  {
    "type": "effect_on_condition",
    "id": "test4",
    "global": true,
    "recurrence_min": 6,
    "recurrence_max": 6,
    "condition": { 
      "compare_int": [ { "u_val": "var", "var_name": "ps_str", "type": "weather", "context": "ps", "global":true }, { "const": 3 } ],
      "op": ">="
    },
    "effect": [ { "u_mod_radiation": 10 } ]
  }
```

### CODE REVIEW

**Comment by PatrikLundell** [comment]
How does this affect prototype cyborgs? If you find one in a lab and return weeks later, will they have died due to their harmful bionics? And, likewise, in the rare cases where you actually manage to disable a prototype cyborg and manage to rip out the control chip but don't manage to convince them to join you (or chose not to try), will they die from those bionics in a fairly limited amount of time?

**Comment by Ramza13** [comment]
> How does this affect prototype cyborgs? If you find one in a lab and return weeks later, will they have died due to their harmful bionics? And, likewise, in the rare cases where you actually manage to disable a prototype cyborg and manage to rip out the control chip but don't manage to convince them to join you (or chose not to try), will they die from those bionics in a fairly limited amount of time?

So prototype cyborgs are technicily monsters so this won't affect them. As to saving them this shouldn't change anything versus the current stable version as that was before I unhardcoded the bionics.  As in stable the bionics will only affect them as long as they are in the reality bubble(near the player).

**Comment by actual-nh** [comment]
Could something be added so NPC (goal?) location could be changed? I know @I-am-Erk has been wanting that for a while.

**Comment by Ramza13** [comment]
> 
> 
> Could something be added so NPC (goal?) location could be changed? I know @I-am-Erk has been wanting that for a while.

So I think that is part of #50310.  The hard part there isn't changing the goal per se, it's the what do you set it to part.  You'd need to add some sort of waypoint to the map like that PR talks about and I don't really know mapgen stuff that well so I haven't done anything with that.  Still yea it would be nice and it's on my giant list of things to maybe do some day.

**Pull request merged**
