### PR TITLE
Bountydummy

### LINKED ISSUE #6893: Item names sailing off into the sunset, never to be seen again. [$5]
Names on items keep getting longer and longer and longer, at first it wasn't a problem, but playing on a widescreen monitor I went to check the charge on an "reinforced thermo electric balava" that fit. It reads "reinforced thermal electric balaclava (fits) (r" which wouldn't be so much a problem if it weren't for the fact that I don't have the vaguest idea what the charge is.

Can I suggest we use the item screen and have it display item condition, battery, and other information there rather than try to cram all of it into the name? Or at least mirror it there so it's visible when the names are a mile long?

<bountysource-plugin>
---
There is a **[$5 open bounty](https://www.bountysource.com/issues/1548674-item-names-sailing-off-into-the-sunset-never-to-be-seen-again-5?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by OzoneH3**
Bountydummy Fixes #6893, Original #11209

Will stick the 5$ to another issue once it's through.

Created a Bountysource account thats connected
to this one, is there anything else to do?

### CODE REVIEW

**Comment by narc0tiq** [comment]
Probably want to include the text "Fixes #6893" in the OP to cause it to auto-close when this is merged. No idea how it works otherwise, though.

**Comment by DavidKeaton** [comment]
best commit 2015

**Comment by narc0tiq** [comment]
Only if you don't count `git commit --allow-empty`.

**Comment by DavidKeaton** [comment]
runner up commit 2015

**Comment by narc0tiq** [comment]
:+1:

**Comment by kevingranade** [comment]
Nice, tidy up the place while you're at it :)

**Comment by kevingranade** [comment]
Wrong button, derp.

**Pull request merged**
