### PR TITLE
Fix double blacklisting

### PR DESCRIPTION
**Pull request by mugling**
As discussed in #18705 the JSON mod loading currently has some insanity:

> We have:
> 1. Content in the main game that is first loaded (eg. jacqueshammer)
> 2. Then unloaded via default_blacklist.json
> 3. Except when for a mod (crazy_cataclysm) where it is un-unloaded via an ITEM_WHITELIST
> 
> Or even better:
> 1. We load mon_zombie_jackson in the core game
> 2. Then unloaded him via default_blacklist.json
> 3. Except when for a mod (crazy_cataclysm) where it is un-unloaded via an MONSTER_WHITELIST
> 
> It's worse still though - mon_zombie_jackson has specific clothes than only he drops (eg. jeans_red) which someone forgot to blacklist in core even though they can never spawn without him.

This PR tackles the first example of un-unloading/double blacklisting via removal of `ITEM_WHITELIST`. A legacy migration is provided for `0.C` saves (this functionality didn't exist when the Crazy Cataclysm mod was written).

A followup PR is going to provide true whitelists which exclude everything **not** on the list. This should allow for total-conversion mods.

### CODE REVIEW

**Comment by Zireael07** [comment]
I'm not sure that removing item whitelisting functionality is the way to go. The functionality needs to stay, but needs to be more sane obviously.

**Comment by mugling** [comment]
> I'm not sure that removing item whitelisting functionality is the way to go. The functionality needs to stay, but needs to be more sane obviously.

* What do you think it currently does?
* How would you like it to work?

**Comment by Zireael07** [comment]
Whitelists allow you to load stuff which would be blacklisted otherwise.

I would check if an item is on a whitelist BEFORE it is unloaded via a blacklist. Therefore avoiding unloading and then un-unloading.

**Comment by mugling** [comment]
You didn't answer why we need this functionality in the first place. Why do we need to blacklist and then whitelist something? What possible purpose does that serve?

**Comment by Zireael07** [comment]
> You didn't answer why we need this functionality in the first place.

We have some monsters that are blacklisted by default (used to be done by No Joke Monsters).

Say I want to have one of the monsters in my game, but not the others. I make a small mod, say, 'Z dancer and thriller' and whitelist the two monsters.

Without whitelisting, I could either have none or all joke monsters in.

> Why do we need to blacklist something and then un-blacklist it later?
I already said whitelists should be checked BEFORE blacklisting. So no un-blacklisting. If it's on a whitelist, treat it as though it wasn't blacklisted. No un-blacklisting needed.

**Comment by mugling** [comment]
> We have some monsters that are blacklisted by default (used to be done by No Joke Monsters).

Not affected at all by this PR

> Say I want to have one of the monsters in my game, but not the others. I make a small mod, say, 'Z dancer and thriller' and whitelist the two monsters.

You don't need to do this at all when we get rid of default blacklists (another insane idea). You just copy the definitions you want into your mod and you're ready to go.

**Comment by Coolthulhu** [comment]
> Without whitelisting, I could either have none or all joke monsters in.

Not at all, it's as trivial to "regular blacklist" the joke monsters as it is to whitelist some selected ones.
If you want only some joke monsters, you still have to manually modify mods.

Are whitelists actually used by some mods?

**Comment by mugling** [comment]
> Are whitelists actually used by some mods?

No `ITEM_WHITELIST` is used only by Crazy Cataclysm. I haven't checked for `MONSTER_WHITELIST` but I suspect also no. I'm going to deal with monsters in a separate PR though.

The next PR will support true whitelists (exclude everything that's not on the list) - that is new functionality and would allow for total conversion mods which I think a lot of mod authors would find a very interesting possibility.

**Comment by Chezzo** [comment]
I am all for a real whitelist for total conversion mods. I thought that's what it was when Kevin did it, but have since learned otherwise.

**Pull request merged**
