### PR TITLE
Makes AEP and ANBC suit harder to craft.

### PR DESCRIPTION
**Pull request by Brian-Otten**
#### Summary
```SUMMARY: Balance "Makes AEP and ANBC slightly harder to craft'"```

#### Purpose of change
AEP and ANBC suit took very low levels of tailoring to make (1 and 2). ANBC suit takes too little kevlar too make.

#### Describe the solution
The tailoring level required is now 1 lower than the fabrication required. ANBC suit now takes suitable amounts of kevlar to make.

#### Describe alternatives you've considered
Leaving the recipes as is.

#### Testing
Launched up the game and crafted the recipes.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
Going to post up an issue for a slightly bigger project. Currently these suits spawn as a pre-cataclysm loot. With how important "not getting exposed to foreign agents" was during the cataclysm we might want a more expanded set of clean/CBRN/hazmat suits  used before the fall, and put them in drop tables. ANBC might end up making more sense as craftable only survivor ANBC if that happens.

**Comment by kevingranade** [comment]
json styling tool wants you to inline that table and remove the trailing newline
```
--- a/data/json/recipes/armor/suit.json
+++ b/data/json/recipes/armor/suit.json
@@ -29,11 +29,7 @@
     "book_learn": [ [ "tailor_portfolio", 7 ], [ "textbook_fireman", 7 ] ],
     "qualities": [ { "id": "CUT", "level": 1 } ],
     "tools": [ [ [ "welder", 112 ], [ "welder_crude", 168 ], [ "soldering_iron", 168 ], [ "toolset", 168 ] ] ],
-    "components": [
-      [ [ "hazmat_suit", 1 ] ],
-      [ [ "duct_tape", 800 ] ],
-      [ [ "swat_armor", 1 ], [ "kevlar_plate", 48 ] ]
-    ]
+    "components": [ [ [ "hazmat_suit", 1 ] ], [ [ "duct_tape", 800 ] ], [ [ "swat_armor", 1 ], [ "kevlar_plate", 48 ] ] ]
   },
   {
     "result": "armor_blarmor",
@@ -896,4 +892,3 @@
     "components": [ [ [ "lycra_patch", 34 ] ] ]
   }
 ]
-
```

**Comment by I-am-Erk** [comment]
You might consider adding some `plastic_sheet` to the requirements to help seal it up after adding the new material.

**Comment by Brian-Otten** [comment]
Thanks for the help there kevin, was wracking my brain trying to fix that, will have another go now.
I like the addition of plastic sheet, will go ahead and add those to both recipes.

I think them being craftable should be okay for the high skill level survivors, because in the end it's a (armored) airtight plastic suit, without the gas mask. I don't think that seems impossible for a survivor with fabrication 8 and tailoring 7, especially comparing to some of the other crafting the player gets up to.

And yes if The ANBC suit becomes a craft only item we can fluff up the flavour text / materials, and make it into the survivor ANBC suit. That should probably wait for a rework of the pre-cataclysm NBC gear and the removal of the ANBC from the spawn tables.

**Comment by AMurkin** [comment]
@Brian-Otten you can see the corrections in the JSON style check  https://github.com/CleverRaven/Cataclysm-DDA/runs/383799333

**Pull request merged**
