### PR TITLE
Make mending a light activity (used to be no activity at all)

### LINKED ISSUE #48961: Firearm cleaning should be an activity
# Describe the bug

When you clean (mend) a firearm, activity level is depicted as "none".

# Steps To Reproduce

1. Make a player with a gun, black gunpowder ammo for faster fouling. Firearm repair kit, rags, oil, gasoline, and ammonia are necessary for cleaning and lubrication.
2. Shoot a few times.
3. (M)end your gun (clean and lube).
4. Note that activity level is depicted as "none".

# Expected behavior

Cleaning a firearm should be a light activity, like tailoring. I've noted that almost every move in the game is an activity, so it probably should be too.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by leemuar**
#### Summary
Balance "Mending now counts as light activity. Used to be no activity"

#### Purpose of change

Fixes #48961
@SuddenEyePuncture pointed out that mending does not count as activity. But it probably should be. Cleaning guns and working on removing flaws on different things should count as activity

#### Describe the solution

Made all mending actions a light activity through JSON. Every mending is a light activity now

#### Describe alternatives you've considered

Leave it as it is

#### Testing

- Spawn a gun and black powder ammo
- Shoot the gun until it malfunctions
- Spawn repair items and attempt to (m)end the gun
- Make sure it is counts as light activity now

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Making mending configurable by JSON is a good idea but I think it probably should be NO_ACTIVITY currently. Most mending in game not something that would reasonably tire you out much

**Comment by SuddenEyePuncture** [comment]
> Making mending configurable by JSON is a good idea but I think it probably should be NO_ACTIVITY currently. Most mending in game not something that would reasonably tire you out much

If so, why tailoring is a light activity and not "none"? I think cleaning guns and packing CBMs all day should be a little harder than reading in a bed.

**Comment by I-am-Erk** [comment]
> If so, why tailoring is a light activity and not "none"? I think cleaning guns and packing CBMs all day should be a little harder than reading in a bed.

As I said in the PR where I moved most tailoring down to 'light' or 'none', it's debatable if it's even light activity. Really, all these things should be somewhere in between the two. However, mending cloth and things still isn't as much effort as moving around sections of cloth, dismantling clothing and reassembling it, etc.

**Comment by leemuar** [comment]
Here were my thought when I was making this change:

- I've talked to some home tailors, and they said while tailoring is not VERY exhausting it is still a physical activity: you move cloth around, every stitch requires some "tension" to tight it up etc. You move your hands a lot during tailoring, it requires some physical energy
- guns are heavy and repairing and cleaning them require some physical energy
- vehicle repair is marked as "moderate excercise". Repairing things is an activity indeed
- all crafting is marked as moderate activity
- fishing is marked as light activity. My experience shows fishing is mostly waiting with a very rare physical activity. It's mostly like a meditation
- I've found no way to mark only gun mending as a light activity, only all mending

It would be cool if we could mark some items group separately: gun mendind as a moderate activity, tailoring heavy winter coat as moderate activity and tailoring T-shirt as a light activity. But currently there is no way to do that afaik.

I think it is OK to make all mending a light activity. In future I wish to mark other items to have a "heavier" activity types

**Comment by anothersimulacrum** [comment]
> all crafting is marked as moderate activity

Crafting is actually variable, as defined in the recipe - the activity definition lies.

**Comment by leemuar** [comment]
Maybe we should also add something in between NO_ACTIVITY and LIGHT_ACTIVITY? Something like VERY_LIGHT_ACTIVITY?

**Comment by Qrox** [comment]
Perhaps just specify the calories per hour needed, instead of / in addition to the current discrete activity levels?

**Comment by leemuar** [comment]
Another way to fix the original issue with gun mending might be adding activity level support to gun faults **(/data/json/items/gun/faults_gun.json)**
Every fault might be marked with some coefficient of activity

**Comment by Kelenius** [comment]
Not all mending is guns. CBMs and engines can also be mended.

**Comment by leemuar** [comment]
> 
> 
> Not all mending is guns. CBMs and engines can also be mended.

Yes! Mending engines is kinda more energy intensive. CBMs repair are probably the same as guns in terms of energy loss

**Comment by leemuar** [comment]
@kevingranade could you please tell why it was closed unmerged? Does it requires more discussion or what?

**Pull request closed without merging**
