### PR TITLE
[CR] Recoil ->

### PR DESCRIPTION
**Pull request by KA101**
Currently this changes the big red "Recoil" that's confusing everyone to "Shaky" and updates the color scheme toward a better version.  Calibration is a bit off though and I'm willing to just axe the thing if that's preferable.

Update: now pulls the Recoil from the UI and leaves it intact for the aim screen.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Seeing 'shaky' on the screen seems like the game is trying to tell me that I'm feeling ill or something. Could we just do without when we're not currently aiming/experiencing recoil?

**Comment by kevingranade** [comment]
I'm thinking just cut it, the main interaction with recoil is in the aim
menu now, outside if that it's just a distraction.

**Comment by KA101** [comment]
Yeah, that was my concern.  Will be axed shortly.

**Comment by KA101** [comment]
Color scheme renumbering is still there, but it only shows up (in grey) when on the aiming screen.

**Pull request merged**
