### PR TITLE
Add burst mode to the m249

### PR DESCRIPTION
**Pull request by theotherblyatman**
Add burst mode to m249 for better managing both wielded and mounted.

### CODE REVIEW

**Comment by mugling** [comment]
Both unrealistic and more importantly bad gameplay. The `m249` has it's niche and that most definitely isn't as a replacement for the other `223` weapons

**Comment by BorkBorkGoesTheCode** [comment]
The game needs a way to simulate short bursts. This doesn't do it well.

**Comment by mugling** [comment]
> The game needs a way to simulate short bursts.

Yes, but very low priority compared to all of our current outstanding issues

> This doesn't do it well.

Agreed

**Comment by Cyrano7** [comment]
@theotherblyatman I'm glad I'm seeing your first post and your not to far along yet. But that's maybe not the best choice in username.
@mugling @illi-kun @kevingranade @Rivet-the-Zombie Not that I want to be the PC police but do we have any rules about people contributing with vulgar or offensive usernames. Its seems very unprofessional. In the future I don't want people to have to see such things when checking for updates or the pulse or graphs.

**Comment by Rivet-the-Zombie** [comment]
>do we have any rules about people contributing with vulgar or offensive usernames

I don't think it's come up before.

**Comment by BorkBorkGoesTheCode** [comment]
Why is the lintbot giving an error in this case?

**Comment by mugling** [comment]
> do we have any rules about people contributing with vulgar or offensive usernames
> 
> I don't think it's come up before.

No, and I don't see the reason to expend time discussing whether a username is offensive given the OP could just change it.

**Pull request closed without merging**
