### PR TITLE
Pry open metal doors with a halligan bar

### PR DESCRIPTION
**Pull request by ISuckM8**
#### Summary

Balance "You can now pry open metal doors with a halligan bar."

#### Purpose of change

Makes the halligan bar more useful and makes metal doors pry-able, two birds one stone.

#### Describe the solution

Simply put; Any tool with prying 4 (Halligan bar as the only example) will be able to open metal doors (The gun store ones)

#### Describe alternatives you've considered

None that I could think of.

#### Testing

I'll test this as soon as the newest build comes out.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
This should take longer than 1 second

**Comment by ISuckM8** [comment]
> This should take longer than 1 second

Regular prying uses a complicated formula that depends on the tool prying quality, difficulty, and the player's current strength, changing duration won't do anything unless you use "prying_nails: true" (That's what I've been told at least)

**Comment by I-am-Erk** [comment]
In general, I don't think this should go in unless we can have it require a "forced entry" proficiency. Opening a metal door with a Halligan bar is not at all trivial.

**Comment by ISuckM8** [comment]
> In general, I don't think this should go in unless we can have it require a "forced entry" proficiency. Opening a metal door with a Halligan bar is not at all trivial. This also has a balance impact on huge chunks of the game and will require us to have a whole separate set of metal doors that aren't forcible.

We already have 2-3 versions of the metal doors, one is used commonly around the world and the other is used inside labs (The third version may or may not exist). This PR only allows the halligan bar to open the common metal door version. And a halligan bar is capable of opening metal doors, just takes more time.

**Comment by curstwist** [comment]
This should be targeting `t_door_metal_pickable`  the closed one is simply closed and not locked.  I'm ok with this as long as it takes a decent chunk of time.  

It'll mostly impact the prison, gun stores, electronic stores, some houses, mall, and a few other locations but not high end loot sources like the labs or the military sites.

**Comment by ISuckM8** [comment]
> This should be targeting `t_door_metal_pickable` the closed one is simply closed and not locked. I'm ok with this as long as it takes a decent chunk of time.
> 
> It'll mostly impact the prison, gun stores, electronic stores, some houses, mall, and a few other locations but not high end loot sources like the labs or the military sites.

That's where I screwed up, my bad here

> This should be targeting `t_door_metal_pickable` the closed one is simply closed and not locked. I'm ok with this as long as it takes a decent chunk of time.
> 
> It'll mostly impact the prison, gun stores, electronic stores, some houses, mall, and a few other locations but not high end loot sources like the labs or the military sites.

Fixed.

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
