### PR TITLE
Debug mutation to easily remove deaf effect

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
SUMMARY: Content "Debug mutation to easily remove deafness"

#### Purpose of change
It's common for players to get deaf for a very long duration when using a mininuke or other very loud explosives, this debug mutation can be activated to remove this deaf effect without needing to edit the save file.

#### Describe the solution
Add mutation that makes the player immune to the deaf effect, needs to be activated if the player already has the deaf effect. 

#### Describe alternatives you've considered
Use ear plugs before playing with loud noises.

#### Testing
- [x] No deafness from a mini-nuke blast
- [x] When activated removed deafness if the player had it.
- [x] Did not affect the poor hearing and deaf mutations

#### Additional context
Has no effect with the deaf mutation.

### CODE REVIEW

**Comment by Zireael07** [comment]
Instead of debug mutation, why not provide tympanoplasty or some equivalent at a hospital? I remember it was being discussed at some point...

**Comment by Night-Pryanik** [comment]
While in not against this debug mutation as a workaround, I think it would be much more useful to add a debug option to remove any effect from a list of effects player currently has.

**Comment by Saicchi** [comment]
> Instead of debug mutation, why not provide tympanoplasty or some equivalent at a hospital? I remember it was being discussed at some point...

Using this debug mutation would be much faster than finding and teleporting to a map using debug commands.

> While in not against this debug mutation as a workaround, I think it would be much more useful to add a debug option to remove any effect from a list of effects player currently has.

That could be done in the future, with this mutation serving as a way to grant deaf immunity without the need to wear earplugs.

**Comment by kevingranade** [comment]
No player-facing features for the debug menu are valid.

The use case as stated is not a bug, permanent deafness from excessive noise is totally fine.

**Pull request closed without merging**
