### PR TITLE
Add punch gun

### PR DESCRIPTION
**Pull request by l29ah**
#### Summary

SUMMARY: Content "Add punch gun"

#### Purpose of change
Sometimes i not just want to punch you in ur face. Check http://fallout.wikia.com/wiki/Punch_gun for inspiration.

### CODE REVIEW

**Comment by l29ah** [comment]
The stats are adjusted to be balanced against the vanilla cdda and the gun doesn't have anything inherently fictional about its function. Anyway, would Bright Nights be an appropriate place for it?

**Comment by Reclusive-reptile** [comment]
[https://en.wikipedia.org/wiki/Sedgley_OSS_.38](url) Was a real thing once. I'm not sure it was ever actually used though.

**Comment by kevingranade** [comment]
I don't think it fits in BrightNights, that's more cyberpunk than steampunk.

I also ran across a forum post about a [Fallout Mod](https://discourse.cataclysmdda.org/t/fallout-new-england/17509?u=kevin.granade).

**Comment by tinukedaya** [comment]
It's actually a real thing... 
https://www.youtube.com/watch?v=1hkmc0o8uVk

**Comment by l29ah** [comment]
I'm kinda disappointed in the fact that a lot of the realistic survival content gets pushed around (mostly third-party) mods, mixed with unbalanced and outright insane stuff, while in mainstream cdda one can shoot walking bones with plasma cannons and put a truckload of different fictional CBMs in one's body w/o any problems whatsoever. Is there an up to date kind of a design document that i can grok?

**Pull request closed without merging**
