### PR TITLE
Recipe tests & rebalances

### LINKED ISSUE #27556: Canned veggy is only useable in 3 recipes.
I thought canned veggy should be usable in more recipes, currently you can only use it in dudeluxe sandwich, deluxe sandwich and vegetable sandwich. I'd say make it at least on par with pickled veggy. As for balancing i'd say they are close enough ? Canning pots and can sealers are pretty rare i'd say.

### LINKED ISSUE #27740: Odd food properties
I have seen a few odd food properties with the recent updates:
-crafting woods soup yields 1 portion with 304 Calories, while cooked meat, a possible component, gives 399 Calories. A lot of components are like this as well. Although boiling food reduces the calories in the food, I just thought it should be checked.
-cooking oil is in portions of 240, but the weight of each portion doesn't seem to have changed. For example, a gallon jug of cooking oil weighs about 60 or so lbs.
-dried rice gives 217 Calories per portion while fried rice is 174 calories. Again, I might be wrong since some of the rice might lose Calories due to cooking, but I think it should be looked at.
-dried rice gives 217 Calories per portion and is used in making sushi rice, which yields 4 portions that each give 200 Calories. The other ingredients are water, vinegar, and [salt(5) or seasoned salt(5) or soy sauce(1) or sugar(1)], which I don't think provide a lot more calories.
-Rice also seems to be a bit too small. Setting plastic rice bags to hold 3 units of dried rice seems like a conscious choice to make portions of rice feel larger, but the rice itself is .09L per portion right now. Sushi rice is .07L in comparison even though it is made in groups of 4 with 1 unit of dried rice.
-vegetable pie gives 8 portions with 486 Calories each, while meat pie gives 8 portions with 399 Calories each. In-game, meat has a lot more calories than vegetables, and a large bonus of vitamin B12 which is somehow lost in making the meat pie.
-Pemmican seems to give a small amount of calories in comparison to the things it is made out of including fat based components like tallow and lard.

-One more thing that is unrelated is the volumes of syringes. An empty syringe is .05L, while a syringe of adrenaline is .01L.

Reproduction:
1. Open a world and debug recipes, then use the crafting menu and item list to look at recipes and items.

**Versions and configuration:**
 - OS: [Windows 10]
 - Game Version [0.C-36905-g81e9990]
 - Graphics version [Tiles]
 - Tested in an unmodded world.

I probably haven't gotten all of the strange things, though the people working on this game are probably weeding them out themselves. However, I do hope this provides a bit of useful information in case the devs miss anything.

### LINKED ISSUE #27852: Mess with Food recipies from flour
1.  Chockolate pancake  2188 kcal from 1 flour
     chockolate waffle 3177 kcal from 1 flour

2.  meat pie requires 30 flour now??? wow, it's a lot. 
     humble pie still requires 2 flour 

3.  fried dandelion has 17???? nutrition, only 17? why not to make 0.17? 
     onion ring has 634 kcal. Great, compared to dandelions. 

4.  total mess with soup recipes. Only 1 flour needed, but we can use macaroni (5 flour)

### LINKED ISSUE #27855: Soup portions after nutrition update
Base Soups recipes now produce only 1 portion.  Why? I suppose it's mistake. 
Before nutrition update, it was 4 portion per 1 base soup recipe.

### LINKED ISSUE #27911: Food item loses nutrition after cooked.
**Describe the bug**  
One of the food items has no calorie and vitamin value after cooked.
bug report 1
bug report 2

**To Reproduce**  
1. Try to make vegetable aspic.
2. Check result.

**Expected behavior**  
Display the correct values.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.C-37094-g5da8e39 (tiles)
 - **Mods loaded:**  "dda",  "no_npc_food",  "filthy_morale",  "ew_pack",  "makeshift",  "Medieval_Stuff",
  "More_Survival_Tools",  "modular_turrets",  "Salvaged_Robots",  "alt_map_key",  "Mining_Mod",
  "mutant_npcs",  "npc_traits",  "more_locations",  "FujiStruct",  "boats",  "deoxymod",  "blazemod",
  "Tanks",  "DP_REMIX_INDICATORS",  "StatsThroughSkills",  "PK_REBALANCE",  "growable-pots"

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Balance "New tests and recipe rebalance"```
#### Purpose of change

Fixes #27911
Fixes #27855
Fixes #27852
Fixes #27740
Fixes #27556

Fixes the rest of the recipes that I missed when trying to make them more reasonable int he first pass.
Added a new test to make sure recipes are within certain limits.

#### Describe the solution

I have written a test that will iterate through all recipes that make comestibles, and get statistics on their permutations. I have asserted that the test will fail if the average of these calorie values is not within 1) 2 standard deviations of the value of the result defined in the json or 2) 20% of the value of the result defined in the json, whichever is a wider margin.
I have made sure to adjust the recipes that failed these assertions to succeed. These assertions are basically a way to keep the balance of recipes in check. If we decide we need to change the margins, we can do so.
#### Describe alternatives you've considered

Check every recipe by hand whenever a new recipe and/or food item is PRed

### CODE REVIEW

**Comment by KITbutler** [comment]
I believe you are missing the "canned" and "jarred" recipes for the soups, and possibly equivalents for other foods.

**Comment by KorGgenT** [comment]
>I believe you are missing the "canned" and "jarred" recipes for the soups, and possibly equivalents for other foods.

yeah looks like i'm not correctly detecting the calorie values for these.

**Comment by moxian** [comment]
I'm sorry to be so insistent on this, but regarding your last commit - no, you can't use vegetable broth (which is called `broth` in game) in aspic. You can use bone broth (and, by extension, human broth), just not plain vegetable one. There's no gelatin in it - it just won't work that way..

**Comment by KorGgenT** [comment]
fair enough. i'll leave the alternates for someone else to cook up. heh.

**Pull request closed without merging**
