### PR TITLE
Nerf dress uniform protection

### PR DESCRIPTION
**Pull request by casswedson**
#### Summary
None

#### Purpose of change
I don't see why this item should have 6 points of protection across
the board, it's just some cloth.
Nerf it to levels similar to other common cloth clothing

#### Testing
Before and after
waves-nerfbat
nerf-bat-was-here

### CODE REVIEW

**Comment by mkrutov** [comment]
why encumbrance increase as well?

**Comment by Terrorforge** [comment]
> why encumbrance increase as well?

It didn't. The first example is fitted, but the second is (poor fit)

**Comment by Zireael07** [comment]
AFAIK (my grandfather was an officer) dress uniform cloth is usually pretty thick and sturdy (think jeans, not t-shirt)

**Comment by kevingranade** [comment]
Somewhere in between I think, 6 is super thick but 0.1 is the low end of tshirts, this thing is a jacket, probably around 0.5?

**Review by Maleclypse — APPROVED** [review]
Good catch

**Pull request merged**
