### PR TITLE
Motorcycle armor

### PR DESCRIPTION
**Pull request by reprobate-bastard**
#### Summary
Balance "Motorcycle armor overhaul"

#### Purpose of change

Motorcycle armor is something that has needed a rework for quite some time due to it's encumbrance, warmth, and lack of armor sublocations.

#### Describe the solution

Volume, encumbrance, and warmth have been balanced, as well as an 'inside pocket' for added realism. Additionally, it's code for armor has been completely overhauled to include completely different materials, new coverage, and in-depth armor sublocations with varying material coverage and thicknesses.

Besides this, I've changed the volume to be 2 L instead of 1 L for realism, added the flag "OUTER" for realism as well as balance, and lastly added a "to_hit" of -3 because motorcycle armor frankly has no god damned business being more viable as a weapon than a standard hammer.

#### Describe alternatives you've considered

Frankly, I'm not knowledgeable enough about CDDA or it's coding to list alternatives. Constructive criticism is always welcome.

#### Testing
Encumbrance, coverage, and resistances all seem to be much more balanced. Additionally, with the inclusion of detailed armor sublocations, enemies can penetrate some parts of the armor, the lycra, with ease but have trouble getting through others, like the plastic.

#### Additional context

Didn't realize I was supposed to delete the comments with "< !--" and "-->". Hopefully that isn't what keeps this PR from getting merged.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@Aerin-of-the-Toast for some reason I was thinking you might have opinions here.

**Comment by anoobindisguise** [comment]
Should this be normal layer, so that it fits comfortably under a touring suit? Or do people not wear those together?

**Comment by PatrikLundell** [comment]
You're not "supposed" to delete the comments: they can be left as is. However, you can't place your actual content inside of them. In the past, trying to delete the comments and only succeeding partially frequently hid the actual content, to the consternation of the PR writer.
Note that if you've deleted the comments without screwing up there's no reason to restore them.

**Comment by catdach** [comment]
> Should this be normal layer, so that it fits comfortably under a touring suit? Or do people not wear those together?
Most protective armors like this are being pushed to the outer layer in accordance with #52514; But I guess if it is commonly and easily worn underneath the touring suit, then maybe an argument _could_ be made that they should go on different layers.

**Comment by Termineitor244** [comment]
It was time the motorcycle armor received some love!

That said, changing the materials to plastic and lycra eliminates one of the main sources of kevlar for survivors (unless they want to disassemble the more valuable and rare kevlar plates), do this kind of clothing does not incorporate kevlar in real life?

Also, you could unify the armor definitions for the arms with the same coverage, just putting all the sulocations in the same definition (I would normally "suggest" the change with github but I'm not on my computer).

Some photos of the before and after of the armor in game would be nice too.

**Comment by kevingranade** [comment]
This is stalled for merge because I don't have anything to go on, there's no justification or sourcing for pretty much any of the changes here.

**Comment by Night-Pryanik** [comment]
Closing as this PR was superseded by #58907.

**Pull request closed without merging**
