### PR TITLE
Deprecate magazine mods (part 1)

### PR DESCRIPTION
**Pull request by mugling**
To resolve some of the outstanding issues (#15185, #15088,  #15122) with reloading  I want to refactor some of the functions from `game.cpp` into `player.cpp` along with refactoring many of the methods in `item`.

A limiting factor here is a twisty maze of `@todo` and conditionals concerning `spare_mag`, which along with the magazine mod slot in general, is marked for deprecation (#14949):

> For now I don't see a reason to keep the magazine slot around

This PR extends `item::magazine_convert` to remove `spare_mag`, `clip` and `clip2` mods from all items and return any excess ammo. It also drops `spare_mag_size` (which was unused anyway) and `clip_size` which becomes obsolete.

One additional major net gain is that after this PR any code concerning ammo outside of `item::ammo_*` function making direct use of the `charges` member can be considered a bug.

EDIT: Rebase to include some instances of `spare_mag` missed in #15108

### CODE REVIEW

**Comment by DeadLeaves** [comment]
IMO, extended magazine mod should still be a thing, considering integrated magazines.

**Comment by mugling** [comment]
> IMO, extended magazine gunmod should still be a thing, considering integrated magazines.

> For now I don't see a reason to keep the magazine slot around

It's not that I'm against the idea it's just that now we have detachable magazines it adds too little to gameplay to be worth the associated maintenance cost.

> a twisty maze of @todo and conditionals

Although I've done some extensive refactoring the reloading and especially `charges` code is still horrible. `charges` means just about anything dependent upon context and as a public member of `item` is accessed from just about everywhere. In the rarer cases where accessor functions are used there often poorly (or not) documented.

A good example would be code comment removed in 00a35aa:

`Clip size. Note that on some gunmods it means relative (in percent) of the guns main magazine`

Every single use of `clip_size` now has to be aware of that exceptional case, which is fertile ground for bugs.

Tone is always difficult to get right and this reply isn't intended as a snark. Hopefully it provides some more insight in to why I want to take this approach.

**Comment by Coolthulhu** [comment]
I don't have a good save to test this on and it looks like it needs a proper save test.

Nitpick: the description of rifle conversions still mentions decreased capacity.

**Comment by mugling** [comment]
> I don't have a good save to test this on and it looks like it needs a proper save test.

To be honest the evil magic was done in #15081. This PR just handles removing the mods from guns with integral magazines and is much simpler to test:

* In a current version of `master`
* Spawn a gun that currently uses integral magazines (`deagle_44`)
* Spawn a spare magazine (`spare_mag`)
* Spawn a double magazine (`clip2`)
* Attach both mods to the gun and fill completely with ammo
* Save
* Compile this PR
* Open

Your gun should no longer have any mods and the excess ammo should be in your inventory

**Pull request merged**
