### PR TITLE
Add updated spacebar sidebar files

### PR DESCRIPTION
**Pull request by GrandpuhTy**
#### Summary
Interface "New upgrades to spacebar sidebar."

image
1. Adds an overmap element to the sidebar.
2. Extends the wielded weapon field for more readability, mostly for ammo count.

#### Purpose of change

A couple of minor QoL tweaks to the spacebar sidebar. As much as I liked the original version it was lacking an overmap and had a UI limitation of the wielded weapon for firearms, namely the name/attachment/ammo count were being cutoff.

#### Describe the solution

I created a new spacebar_overmap.json file with overmap widgets and tweaked existing widgets in spacebar_environment_block to accommodate the new overmap widget. I also re-arranged the ordering of the martial arts widgets in spacebar_waepon_ma_block to allow for the extended weapon text to be displayed.

#### Describe alternatives you've considered

Not doing what I did?
Create a new folder to retain current edition of spacebar?

#### Testing

Fresh install on newest experimental. Copied files over. New world new character(henceforth NWNC "Nu-Nic"). Switched to spacebar sidebar. Smile.

### CODE REVIEW

**Comment by GuardianDll** [comment]
Note: to make our files style consistent we use [this linter](https://dev.narc.ro/cataclysm/format.html). It is a mandatory thing for this project, so please lint your files

**Comment by GrandpuhTy** [comment]
> Note: to make our files style consistent we use [this linter](https://dev.narc.ro/cataclysm/format.html). It is a mandatory thing for this project, so please lint your files

Linted the files. I think I did it right.

**Comment by GrandpuhTy** [comment]
Okay false alarm. Just some oddity with copy-pasting over files. Tried deleting the folder and copying a new folder in and no wonkiness.

**Comment by GrandpuhTy** [comment]
Bump?

**Comment by anothersimulacrum** [comment]
You might want to rebase to get the tests up to date. Either that or close and re-open the PR.

**Comment by GrandpuhTy** [comment]
> You might want to rebase to get the tests up to date. Either that or close and re-open the PR.

That work?

**Comment by anothersimulacrum** [comment]
Looks good.

**Pull request merged**
