### PR TITLE
More generic compares and arithmetic for the dialogue system

### LINKED ISSUE #50102: More generic compares and arithmetics for the dialogue system
# Is your feature request related to a problem? Please describe.
In the NPC dialogue system, there currently it doesn't seem to be possible to compare a variable to another, or multiply a variable with another. Same for values such as current bionic power, mana, pain, HP, dexterity, etc. Now that effect_on_condition has been added, having more powerful dialogue logic becomes much more useful. 

# Describe the solution you'd like
A function usable by the dialogue system similar to u_compare_var or npc_compare_var, except on both sides of the comparison it can take either a variable, or a numeric value such as
- Current Hit points
- Max Hit points
- Percentage of Hit points (A value between 0 and 100 where 0 means you have 0 hit points remaining, and 100 means you are at full health)
- Current, max, and percentage of bionic power and mana
- Numbers of a certain type of items in your inventory
- strength, dexterity, intelligence, and perception, perhaps both current and base.
- Level in a skill
- Pain level
- Days since cataclysm
- Random number
- Total earned experience
- Stored calories and water
- Water, calories and fullness of your stomach
- Current map X, Y, and Z coordinate
- Current X and Y coordinates inside the current chunk
- Any other numbers one might want to compare or alter

Furthermore, I would like a generic arithmetic function that takes two integer values such as those above, a given operator (Such as `*`, `/`, `+`, `-`, `%`), and an output which could be any of the values mentioned above. The function would take the two values, apply the operator, and save the result in the specified variable.

# Describe alternatives you've considered
- Check for each possible configuration separately, for example instead of doing `A = B * C`, do `if(B== 1 && C == 1) A = 1; elseif(B== 1 && C == 2) A = 2; ...` This solution is technically possible for variables with finite scope, but insane, impractical, slow and ugly.
- Keep the json mostly the same and instead hardcode c++ code every time you want to do something the .json can't handle. A lot of old functionality works this way, and it works all right for mainline mods. It may or may not be faster, but is more difficult for moders to deal with. Personally, I think there is virtue in avoiding hardcoding functionality this way.
- Optionally, add support for a function that takes only two values and an operator such as `=`, `+=`, `*=`, and so on. That could be more elegant, even though everything it can do should be achievable with the previously discussed function that takes three values.

# Additional context
I was looking into implementing a soul siphon effect that gives the player mana every time they slay an enemy, with the amount of mana awarded would depend on how difficult the enemy was. My idea implementation was something like that below, but I started running into limits with the dialogue system, and I was hoping to avoid having to hard code this in C++.
(Apologies for potentially bad code, I'm fairly new to json. But I hope the general idea comes across.)

```
{
    "type": "effect_on_condition",
    "id": "soul_siphon",
    "recurrence_min": 1,
    "recurrence_max": 1,
    "condition": {
      "and": [
        { "u_has_trait_flag": "SOULSIPHON" },
        {
          "compare": [
            { "u_var": "experience_digested", "type": "counter", "context": "soul_siphon" },
            { "value": "u_experience" }
          ],
          "op": "<"
        }
      ]
    },
    "deactivate_condition": { "not": { "u_has_trait_flag": "SOULSIPHON" } },
    "effect": [
      { "arithmetics": [
        { "value": "u_experience" },
        { "u_var": "experience_digested", "type": "counter", "context": "soul_siphon" },
        { "u_var": "experience_to_digest", "type": "counter", "context": "soul_siphon" }
        ],
      "op": "-"
      },
      { "arithmetics": [
        { "u_var": "experience_to_digest", "type": "counter", "context": "soul_siphon" }
        { "const": 4 },
        { "u_var": "gained_mana", "type": "counter", "context": "soul_siphon" },
        ],
      "op": "*"
      },
      { "arithmetics": [
        { "u_var": "gained_mana", "type": "counter", "context": "soul_siphon" },
        { "u_var": "mana" },
        { "u_var": "mana" }
        ],
      "op": "+"
      },
      { "arithmetics": [
        { "u_var": "mana" },
        { "u_var": "mana_max" },
        { "u_var": "mana" },
        ],
      "op": "min"
      },
      { "arithmetics": [
        { "value": "u_experience" },
        { "const": 0 },
        { "u_var": "experience_digested", "type": "counter", "context": "soul_siphon" }
        ],
      "op": "+"
      }
    ]
  }
```

### PR DESCRIPTION
**Pull request by Light-Wave**
#### Summary
Infrastructure "Compare and do arithmetic on any two integers through the dialogue system"

#### Purpose of change

Fixes #50102
In the NPC dialogue system, it currently doesn't seem to be possible to compare a variable to another, or multiply a variable with another. Same for values such as current bionic power, mana, pain, HP, dexterity, etc. Now that effect_on_condition has been added, having more powerful dialogue logic becomes much more useful.
This pull request aims to make it possible to take any two numeric values and compare them or do arithmetic on them through the dialogue system. This would also be available for effect_on_condition ( added in #48042 ) to use. 

#### Describe the solution

Example json code:
```
{
  "text": "Five > two.",
  "topic": "TALK_DONE",
  "condition": {
    "compare_int": [
      { "const": 5 },
      { "const": 2 }
    ],
    "op": ">"
  }
}
```

WIP
Code (C++)
- [x] compare_int
  - [x] support operators
    - [x] == and = (both handled the same)
    - [x] !=
    - [x] <=
    - [x] >=
    - [x] <
    - [x] >
  - [x] fetch different values
    - [x] consts
    - [x] strength
    - [x] dexterity
    - [x] intelligence
    - [x] perception
    - [x] custom variables
    - [x] special support for time variables?
      - [x] Time variable was created
      - [x] Time since start of game
      - [x] Const of type time
      - [x] Time since variable was created
    - [x] Number of allies
    - [x] Amount of money the player has
    - [x] Owed ammount.
    - [x] Days since cataclysm
    - [x] Level of a skill
    - [x] random number between 0 and a given value
    - [x] Current temperature
    - [x] Current wind power
    - [x] Current humidity
    - [x] Pressure
    - [x] X, Y and X of the player / npc
    - [x] Pain level (current/max/percentage of max?)
    - [x] Bionic power (current/max/percentage of max?)
    - [x] Morale
    - [x] Focus
    - [x] Mana (current/max/percentage of max?)
    - [x] Number of certain items in player inventory
    - [x] Total earned experience
    - [x] Calories and water in your body (outside the stomach) (current/max/percentage of max?)
- [x] arithmetic
  - [x] operators
    - [x] *
    - [x] /
    - [x] +
    - [x] -
    - [x] %
    - [x] bitwise operators? Or is that overkill?
    - [x] =
    - [x] *=
    - [x] /=
    - [x] +=
    - [x] -=
    - [x] %=
    - [x] ++
    - [x] --
  - [x] fetch different values
  - [x] write different values
- [x] Fix style errors

Test code (C++)
- [x] compare_int
  - [x] support operators
  - [x] fetch different values
- [x] arithmetic
  - [x] operators
  - [x] fetch different values
  - [x] write different values
- [x] Fix style errors

Test code (json)
- [x] compare_int
  - [x] support operators
  - [x] fetch different values
- [x] arithmetic
  - [x] operators
  - [x] fetch different values
  - [x] write different values
- [x] Fix style errors

Documentation
- [x] compare_int
  - [x] support operators
  - [x] fetch different values
    - [x] Document how time variables works now.
- [x] arithmetic
  - [x] operators
  - [x] fetch different values
  - [x] write different values

#### Describe alternatives you've considered

Hardcode advanced mathematics into C++ instead of letting json handle it

Replace old functionality that deals with numbers with this new function, removing old code. This would be more elegant, but would mean all currently existing dialogue would need to be updated to the new system, both in mainline and third party mods. The alternative is having duplicated functionality, which is not great either. I do not intend to remove the old functionality that this pull request duplicates. But if someone else want to tackle that, feel free to.

#### Testing

It is my intention to make sure all added functionality has testcases. The only exception is the random number generator that will be tested manually. 

#### Additional context

Possible future work:
    - [ ] Number of items with certain flag in inventory
    - [ ] Overmap Coordiantes
    - [ ] Calories and water in your stomach (current/max/percentage of max?)
    - [ ] Other useful numbers? Feel free to leave comments below if you have suggestions/requests
    - [ ] Check that npc talkers can use power_max, mana_cur, mana_max, get_amount, get_stored_kcal
    - [ ] Check that npc, item, and monster values works as well.
    - [ ] Check if windpower and windspeed are the same things or should be handled separately.

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @Ramza13?

**Comment by Ramza13** [comment]
This looks awesome and I am looking forward to using it.  And slightly less to ripping out the content I added that this is superior to.

**Comment by kwl01skz** [comment]
These conversations don't need translation, do they? I want to delete them from string waiting for translation.

**Comment by Light-Wave** [comment]
> These conversations don't need translation, do they? I want to delete them from string waiting for translation.

There are English error messages and documentation, and printouts during testing, but no English text the player would be able to see during normal play. So I don't think anything here needs a translation, no.

**Pull request merged**
