### PR TITLE
[WIP][CR] Atmospheric and Environmental Modifications to Cities

### PR DESCRIPTION
**Pull request by vache**
Applies special zone post processing to generated maps, allowing for things like looted, overgrown, and fungus covered cities.

How it works:
Cities have a zone type added to them, and overmaps have a method to determine if a location lies within a city.  During mapgen, the location checks its city, finds the city zone type, and applies special post processing to it.

Screenshots:
Overgrown with Triffids: http://i.imgur.com/sAEm6lv.png
Overgrown with Fungus: http://i.imgur.com/vr6DQ6x.png
Looted library: http://i.imgur.com/i9VwHY8.png
Looted gun store: http://i.imgur.com/ar2GZbJ.png

Zones so far:
Fungal: the fungus has spread inside and outside of all locations in the area.
Overgrown: triffids have spread nature back into the city, outside areas now full of trees, shrubs, and underbrush.  Some of the road has been broken through.  Inside areas are mostly unaffected, since the plants want the sunlight.
Looted: one in 5 chance of a location being looted, with all items > a certain value (right now $200) and a random amount of the rest being looted, terrain and furniture being bashed up, and blood stains being tossed around.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This PR will probably not become mergeable. Closing.

**Comment by Zireael07** [comment]
The idea, however, was very well received, should anyone want to revisit it.

**Comment by Rivet-the-Zombie** [comment]
Yes, particularly the damaged/looted overlays; it would be capital if somebody wants to resurrect them.

**Comment by vache** [comment]
I am going to keep this branch alive.  I don't think it will be too difficult to bring back in with the changes that have occurred since I first posted the PR, and I would really like to finish it, but as of right now I just don't really have the time I need to dedicate to any of my PRs.

**Comment by Rivet-the-Zombie** [comment]
If you fix up the damaged/looted overlay for terrain and get it operational, I'd definitely fast-track it for merge testing. The other overlays are good too, but the damaged/looted one is such a great idea that I'd like to see it as a freestanding PR so we can get it into the game quickly.

**Comment by ZhilkinSerg** [comment]
Resurrected (although non-functional yet) branch is here - https://github.com/ZhilkinSerg/Cataclysm-DDA/compare/overmap-zones-basic.

**Pull request closed without merging**
