### PR TITLE
Add more metal constructions

### PR DESCRIPTION
**Pull request by Rail-Runner**
Add metal floor, metal walls and metal doors with peepholes, all of which can be constructed.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. o.o

**Comment by Coolthulhu** [comment]
The walls look like '#' in console build. This makes them look like marloss shrubs rather than walls.
Judging by `"connects_to" : "wall"`, I assume they're supposed to look like walls.
Adding `"AUTO_WALL_SYMBOL"` to tags and setting `"symbol": "LINE_OXOX"` would make them look much more wall-like.

Also, currently there is no way to deconstruct those, not even with a torch.

**Comment by Darkyhard** [comment]
> The walls look like '#' in console build. This makes them look like marloss shrubs rather than walls.
Judging by "connects_to" : "wall", I assume they're supposed to look like walls.
Adding "AUTO_WALL_SYMBOL" to tags and setting "symbol": "LINE_OXOX" would make them look much more wall-like.

This is true for all other walls that are constructed by player. As it would be odd to have just one type of walls being drawn like this, should I change all of them in this PR or a separate one?

> Also, currently there is no way to deconstruct those, not even with a torch.

How do you add a way to deconstruct it with a torch?

**Comment by Coolthulhu** [comment]
> This is true for all other walls that are constructed by player.

This makes sense for really bulky walls like log ones, partly for brick ones (because # kinda looks like brick wall), but metal walls are made from steel plating and thus thin.
Also, it makes it hard to tell apart walls from furniture.

I don't think this is an intentional convention, just that older walls weren't updated.
If picket fences can look like walls, player-built walls should look like walls too.

**Comment by Coolthulhu** [comment]
> How do you add a way to deconstruct it with a torch?

Currently hardcoded in iuse.cpp and activity_handlers.cpp. It's not necessary, but it would be useful to have some way to destroy the wall.

**Comment by Darkyhard** [comment]
> This makes sense for really bulky walls like log ones, partly for brick ones (because # kinda looks like brick wall), but metal walls are made from steel plating and thus thin.
Also, it makes it hard to tell apart walls from furniture.

> I don't think this is an intentional convention, just that older walls weren't updated.
If picket fences can look like walls, player-built walls should look like walls too.

So, I'll probably change metal walls to look like lines, not "#". I won't change half-built metal walls as this will help to see the difference between finished and unfinished wall.

> Currently hardcoded in iuse.cpp and activity_handlers.cpp. It's not necessary, but it would be useful to have some way to destroy the wall.

I'll try changing it.
By the way, wouldn't it cause weird stuff like floating roof if you build a house and then deconstruct all the walls this way?

**Comment by Coolthulhu** [comment]
> By the way, wouldn't it cause weird stuff like floating roof if you build a house and then deconstruct all the walls this way?

Hmm, yeah.
It may be better to leave it not-torchable then.
Many walls have the same problem, we'll need some good solution for not being able to uncraft those.

**Comment by Darkyhard** [comment]
Done.

**Pull request merged**
