### PR TITLE
Upgraded dress

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The female senior citizen cannot hold their equipment in inventory otherwise.

### CODE REVIEW

**Comment by pisskop** [comment]
make it a fanny pack

**Comment by Rivet-the-Zombie** [comment]
Seems more likely to have a purse.

**Comment by BorkBorkGoesTheCode** [comment]
I didn't want to switch the storage asymmetry too much, and I wanted to use a lesser-used storage item.

**Comment by Rivet-the-Zombie** [comment]
Does any profession even have a purse?

**Comment by BorkBorkGoesTheCode** [comment]
Hmm, GitHub 500 server error

**Comment by Cyrano7** [comment]
The fanny pack has the same amount of storage as the leather pouch. The leather pouch has "A bag stitched together from leather scraps." in the description so it would be a odd thing to be carrying pre-cataclysm.

**Comment by Coolthulhu** [comment]
Yeah, that leather pouch is supposed to be makeshift.

**Comment by illi-kun** [comment]
@BorkBorkGoesTheCode will you update your PR according to the recent comments from Cyrano7 and
 Coolthulhu?

**Comment by BorkBorkGoesTheCode** [comment]
I was just thinking; why wouldn't a dress have a cell phone pocket? Instead of any kind of strap-on storage item, I have given the dress storage 2.

**Comment by illi-kun** [comment]
500 ml pockets is definitely not a "minimal storage capacity". Fanny pack is a much better way to fix the initial issue, IMO.

**Comment by BorkBorkGoesTheCode** [comment]
@illi-kun , I apologize for not updating this PR.

**Comment by illi-kun** [comment]
@BorkBorkGoesTheCode no problem. Feel free to provide a proper fix discussed above if you agree with it or create an issue report elsewise. Thanks!

**Pull request closed without merging**
