### PR TITLE
Astyle bionics.cpp, part6

### PR DESCRIPTION
**Pull request by illi-kun**

### CODE REVIEW

**Comment by codemime** [comment]
I have a rather silly question, but I'm gonna ask it anyway: why do you astyle files partly, not as a whole?

**Comment by kevingranade** [comment]
Because then the pr would be too big to review.

**Comment by codemime** [comment]
Then yet another one: why would anyone review an astyled file with one's eyes? The same file can be astyled locally and then compared. They should match or be very close to each other.

**Comment by kevingranade** [comment]
Because astyle has bugs (go look at their bug tracker), also these need to
be made piecewise anyway to avoid invalidating huge numbers of pending PRs.

**Comment by codemime** [comment]
> Because astyle has bugs (go look at their bug tracker)

Yeah, I've seen, but it's very unlikely to introduce a bug (anything more serious, than a bracket at a wrong line) and still get a compilable build.

> also these need to be made piecewise anyway to avoid invalidating huge numbers of pending PRs.

I thought about it too, but still there's a possible solution: merge all pending PRs (locally, of course) and then either:
- see which files are not affected and astyle them at once
- try to merge the astyled file and see if it fails

Also, partial astyling doesn't solve the mentioned problem.

**Comment by kevingranade** [comment]
> Yeah, I've seen, but it's very unlikely to
>  introduce a bug (anything more serious, than
> a bracket at a wrong line) and still get a
> compilable build.

Result: we merge who knows how many style errors, also plain awkward things
astyle leaves in.  I fix up style manually on these fairly frequently. I
don't share your confidence that the 50,000+ line full project astyle would
not cause any bugs, additionally, I guarantee the subsequent conflicts
would introduce bugs.

> I thought about it too, but still there's a
> possible solution: merge all pending PRs
> (locally, of course)

Incomplete PRs live on other people's computers, not mine :p

> Also, partial astyling doesn't solve the
> mentioned problem.

It spreads out the workload so it isn't overwhelming.

**Comment by codemime** [comment]
@illi-kun Please, suspend further astyling of `bionics.cpp` till #16144 lands (merge conflict).

**Comment by codemime** [comment]
@kevingranade That's exactly what I was talking about: routine checking, that your astyling won't break someones PR is a good practice anyways. Partial astyling doesn't prevent any issues.

> Incomplete PRs live on other people's computers, not mine :p

If you mean security problems related to unviewed code, I was talking about merging only, not running the executable. It should be pretty harmless. Also, I wonder if Jenkins can do that (checking for conflicts) using an appropriate script.

**Comment by illi-kun** [comment]
@codemime these are preparations for further changes in this file, and I've started it more than week ago (because this process is not so fast).

I can agree that's not so important and referenced PRs are probably more prior so I'll take a break.

**Comment by kevingranade** [comment]
> Partial astyling doesn't prevent any issues.

Again, it makes said overhead maneageable. This discussion is going in
circles, the basic issue is I'm not going to merge a huge unreviewed PR.
>>
>> Incomplete PRs live on other people's computers, not mine :p
>
> If you mean security problems related to
> unviewed code, I was talking about merging
> only, not running the executable.

I mean I don't have access to the majority of pending code changes, as they
aren't even pushed to github.

**Comment by codemime** [comment]
> the basic issue is I'm not going to merge a huge unreviewed PR

@kevingranade I'm not proposing it, of course. I really wanted to learn the reasons of the accepted astyling approach and I respect it.

> I mean I don't have access to the majority of pending code changes, as they aren't even pushed to github.

Ah, ha, got it now. Anyways, merging at least pushed PRs locally seems to be a useful way to avoid some of the conflicts and I'm gonna use it for myself. All I need is to write a script. Thank you for the comprehensive answer.

**Comment by codemime** [comment]
@illi-kun Thanks.

**Pull request merged**
