### PR TITLE
Reinforced security camera power fix

### PR DESCRIPTION
**Pull request by DPavonis**
#### Summary
Bugfixes "Reinforced security cameras now no longer draw 10 kW"

#### Purpose of change

I'm reasonably sure any kind of security cameras shouldn't be drawing 10 **kilo**watts. Call me crazy.

#### Describe the solution

Changed reinforced security camera's epower from `-10` to `-10 W`

#### Describe alternatives you've considered

~~Figure out why supergluing stiff metal wire to a security camera causes it to draw one thousand times more power~~

#### Testing

Changed `"epower": -10,` to `"epower": "-10 W",` then loaded up game. Reinforced security cameras now drawing 10 W as expected. Game did not crash, explode, kick-start a resonance cascade or summon catboy satan.

### CODE REVIEW

**Comment by KheaHyena** [comment]
Out of curiosity...
Since this affects the power drain of the **Reinforced Security Camera**, does it take into account the regular **Security Camera** too?

**Comment by flybye3o6** [comment]
regular Security Camera is already set to 10w
image

**Comment by DPavonis** [comment]
> Out of curiosity... Since this affects the power drain of the **Reinforced Security Camera**, does it take into account the regular **Security Camera** too?

Yeah, it was only the reinforced security camera that had the issue, I could see poor phrasing on my part implying otherwise.

**Comment by KheaHyena** [comment]
> regular Security Camera is already set to 10w image

Yeah, I didn't catch the updated _Hitchhiker_, so I was just confused with all the **-10** and **-10 W** (still am honestly, since some of the code here references in a few places "**kW**").

Thanks for clearing my doubt though!

**Pull request merged**
