### PR TITLE
dedicated unload loot button

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
Should be a way to strip corpses and unload stuff without otherwise sorting

#### Describe the solution
Added a new method similar to sort but with the actual moving removed. just tries to unload nearby unload zones.

Moved over to the activity actor system, made some functions that were just used in the old activities available in a namspace for use across the systems.

#### Testing
Load up game, make an unload zone, kill some zeds, try unloading

#### Additional context
image

### CODE REVIEW

**Comment by mqrause** [comment]
You should implement the activity with the activity actor system. See #40013.

**Comment by snipercup** [comment]
Why go trough zones for this? Shouldn't this be just a player action? Do you want NPC's to use this function as well and that's why you're using zones? I get there's a player action for unloading a container, but that puts it into your inventory as opposed to your solution where it is dropped onto the ground. I feel like it should be more similar to unload container as a player action.

**Comment by mqrause** [comment]
> in the future I would like to generalize this and further similar activities to that system and split them into chunks (so code isn't replicated), however for now it seems like a lot of work and risks regression when we should be in freeze. This is just a quick assist for the new nested zombie items making the workflow of unloading a bit snappier potentially.

You can make it a quick assist with an activity actor and save the refactoring for later. There's no real need to add to legacy code here.

**Comment by bombasticSlacks** [comment]
> Why go trough zones for this

So you can do it en-masse. If you have a huge unload zone you can unload everything in there. It also gets nested containers.

> but that puts it into your inventory as opposed to your solution where it is dropped onto the ground
Onto the ground exists as well but is unbound by default "Unload container" in the bindings menu. It's very useful.

**Comment by bombasticSlacks** [comment]
> You can make it a quick assist with an activity actor and save the refactoring for later. There's no real need to add to legacy code here.

I apologize but I don't understand what this means.

**Comment by molkero** [comment]
`src/activity_actor.cpp:6266:14: error: variable 'unload_always' set but not used [-Werror,-Wunused-but-set-variable]
bool unload_always = false;`

**Pull request merged**
