### PR TITLE
[Magiclysm] Finetuning black dragon mutation

### PR DESCRIPTION
**Pull request by Stadler76**
#### Summary
Mods "[Magiclysm] Finetuning black dragon mutation"

#### Purpose of change
Fixed Dragon Clawed Feet being unobtainable and hardcoded `TOE_CLAWS` into Reptilian Legs along with some finetunings to both. 'Draconic Magic' now `changes_to` 'Draconic Spellcasting' instead of being two separate mutations.

#### Describe the solution
Due to a stray `"valid": false,` Dragon Clawed Feet were unobtainable and due to a mismatch in `"types"` they didn't replace `TOE_CLAWS`. Additionally I decided to hardcode `TOE_CLAWS` into 'Reptilian Legs', but without the random attack and the limitations to wear any footwear.

Renamed two more mutations:
- Stubby Reptile Tail → Stubby Dragon Tail
- Scaled Reptile Tail → Short Dragon Tail

Old: Stubby Reptile Tail → Scaled Reptile Tail → Dragon Tail
New:  Stubby Dragon Tail → Short Dragon Tail → Dragon Tail

'Draconic Magic' now `changes_to` 'Draconic Spellcasting' instead of being two separate mutations. I've made sure, that Draconic Spellcasting is a combination of both mutations.

I've removed `LIZARD` category from Reptilian Legs (old: Clawed Feet) aka `TOE_CLAWS` because Magiclysm lizards should match Vanilla lizards, not surpass them.

Black Dragon mutation worked fine before the change to the mutation-system, but as of now more and more issues surface every time I change something that changes dragons as a byproduct.

#### Testing
Did some tests with both lizards and dragons in Vanilla and Magiclysm. I've even tested mutating into a dragon by adjusting the vitamin values for black dragon mutagen and mutagen under Set needs in the Debug menu.

### CODE REVIEW

**Comment by RelMayers** [comment]
I do not see a reason to have a base game mutation line be having same traits as it has in mod.

**Comment by Stadler76** [comment]
I wanted to hardcode `TOE_CLAWS` because `"copy_from": "RAP_TALONS",` caused some unwanted issues with `DRAGON_FEET`.
I've merged `WEBBED_FEET` into them so there's no change in points and mutagen cost for vanilla lizards and the claws are short and quite dull, so no extra DPS for lizards. So basically vanilla lizards are the same as without this PR.

IIRC @KorGgenT added `TOE_CLAWS` as a mid-TF to transition to `DRAGON_FEET` later. Not to make Magiclysm lizards stronger, than vanilla lizards.

**Comment by RelMayers** [comment]
I would really prefer no changes to base line mutations based on magicalysm experience.

**Comment by Stadler76** [comment]
> I would really prefer no changes to base line mutations based on magicalysm experience.

Like I said: Lizard gameplay hasn't even changed the slightest in vanilla. If you're a fully mutated lizard with `WEBBED_FEET` you don't even need to use the extra 100 mutagen to get your `WEBBED_FEET` to be changed to `TOE_CLAWS`

Just compare `TOE_CLAWS` to `WEBBED_FEET`:
```json
  {
    "type": "mutation",
    "id": "TOE_CLAWS",
    "name": { "str": "Reptilian Legs" },
    "points": 1,
    "description": "Your legs and feet have become reptile-like and your toenails have grown into short claws.  Your toes have grown noticeably longer and webbing has grown between them.  Fortunately they don't impede your movement.",
    "types": [ "LEGS", "FEET" ],
    "flags": [ "WEBBED_FEET" ],
    "wet_protection": [ { "part": "foot_l", "good": 6 }, { "part": "foot_r", "good": 6 } ],
    "cancels": [ "WEBBED_FEET" ],
    "category": [ "LIZARD" ]
  },
  {
    "type": "mutation",
    "id": "WEBBED_FEET",
    "name": { "str": "Webbed Feet" },
    "points": 1,
    "description": "Your feet are heavily webbed, allowing you to swim faster if you aren't wearing footwear.",
    "prereqs": [ "WEBBED" ],
    "category": [ "FISH", "SLIME", "BATRACHIAN" ],
    "flags": [ "WEBBED_FEET" ],
    "wet_protection": [ { "part": "foot_l", "good": 6 }, { "part": "foot_r", "good": 6 } ]
  },
```

**Comment by fairyarmadillo** [comment]
Lizards don't have webbed feet IRL. What's the justification for this?

**Comment by Stadler76** [comment]
> Lizards don't have webbed feet IRL. What's the justification for this?

I agree with you. Originally they were added in #59458, when I split Webbed Hands into Webbed Hands and Webbed Feet.
Originally Webbed Hands aka `WEBBED` was an outright -2 points bad mutation. After the split I've changed the points of webbed hands to -3 as they now contibute less to swimming speed.
In short: Removing `WEBBED_FEET` from lizards would leave them with an even worse `WEBBED` mutation so logic would say no webbings at all in other words: Remove both. But removing an outright bad mutation would kinda require adding an alternative to rebalance them.

See also #59292 where I decided to leave `WEBBED` for lizards altough the aren't meant to be geckos.

**Comment by fairyarmadillo** [comment]
> > Lizards don't have webbed feet IRL. What's the justification for this?
> 
> I agree with you. Originally they were added in #59458, when I split Webbed Hands into Webbed Hands and Webbed Feet. Originally Webbed Hands aka `WEBBED` was an outright -2 points bad mutation. After the split I've changed the points of webbed hands to -3 as they now contibute less to swimming speed. In short: Removing `WEBBED_FEET` from lizards would leave them with an even worse `WEBBED` mutation so logic would say no webbings at all in other words: Remove both. But removing an outright bad mutation would kinda require adding an alternative to rebalance them.
> 
> See also #59292 where I decided to leave `WEBBED` for lizards altough the aren't meant to be geckos.

IMO you should ditch the lizard legs mutation entirely. They don't have webbed feet and "game balance" isn't usually considered a valid justification for this kind of decision making in Cataclysm.

If you're dead set on replacing them with something, perhaps a climbing bonus could work, as chameleons and geckos are very good at climbing and many other lizards are decent at it, but I believe that would require either adding a hardcoded effect to the climb function or jsonizing a variable bonus that gear, bionics, proficiencies, mutations etc. could affect. I think that's too much work though.

**Comment by Stadler76** [comment]
> > > Lizards don't have webbed feet IRL. What's the justification for this?
> > 
> > 
> > I agree with you. Originally they were added in #59458, when I split Webbed Hands into Webbed Hands and Webbed Feet. Originally Webbed Hands aka `WEBBED` was an outright -2 points bad mutation. After the split I've changed the points of webbed hands to -3 as they now contibute less to swimming speed. In short: Removing `WEBBED_FEET` from lizards would leave them with an even worse `WEBBED` mutation so logic would say no webbings at all in other words: Remove both. But removing an outright bad mutation would kinda require adding an alternative to rebalance them.
> > See also #59292 where I decided to leave `WEBBED` for lizards altough the aren't meant to be geckos.
> 
> IMO you should ditch the lizard legs mutation entirely. They don't have webbed feet and "game balance" isn't usually considered a valid justification for this kind of decision making in Cataclysm. Mutation lines are not really balanced at all anyway.

Well, then I would remove both `WEBBED` and `WEBBED_FEET` from lizards and make `TOE_CLAWS` aka Reptilian Legs for dragons only, since I don't see much point for lizards or any other vanilla mutation to differ between mods.

> If you're dead set on replacing them with something, perhaps a climbing bonus could work, as chameleons and geckos are very good at climbing and many other lizards are decent at it, but I believe that would require either adding a hardcoded effect to the climb function or jsonizing a variable bonus that gear, bionics, proficiencies, mutations etc. could affect. I think that's too much work though.

Would be an alternative, yeah. I was also considering to make claws functional as a minor bonus to kicking with martial arts if not wearing footwear, but that would require more work.

Originally this was named 'Finetuning black dragon mutation (with intended sideeffects)'. I could change this to be a black dragon only PR and undo the changes to lizards (And make `TOE_CLAWS` aka 'Reptilian Legs' dragons only), but that would leave lizards with the `WEBBED_FEET`-mutation.

**Comment by fairyarmadillo** [comment]
You replied while I was in the middle of editing my post, so I'll just reiterate: Lizard sucks pretty badly to play. Getting rid of a single  -2 or -3 point mutation isn't going to make it overpowered, and "game balance" is not a justification for insisting that lizards have webbed feet/hands. They don't have either IRL, and should have neither in Cataclysm.

**Comment by Stadler76** [comment]
> You replied while I was in the middle of editing my post, so I'll just reiterate: Lizard sucks pretty badly to play. Getting rid of a single -2 or -3 point mutation isn't going to make it overpowered, and "game balance" is not a justification for insisting that lizards have webbed feet/hands. They don't have either IRL, and should have neither in Cataclysm.

I agree with you, but revisiting lizard mutation would better fit into a separate suggestion/PR.

**Comment by fairyarmadillo** [comment]
> > You replied while I was in the middle of editing my post, so I'll just reiterate: Lizard sucks pretty badly to play. Getting rid of a single -2 or -3 point mutation isn't going to make it overpowered, and "game balance" is not a justification for insisting that lizards have webbed feet/hands. They don't have either IRL, and should have neither in Cataclysm.
> 
> I agree with you, but revisiting lizard mutation would better fit into a separate suggestion/PR.
> 
> [Edit:] I'll consider undoing the changes to lizards and making TOE_CLAWS dragons only. But I need to discuss that a bit. So give me time ^^

You seem to be saying you agree with me and then just talking past me. There is no reason to backport anything to mainline and say that someone else should come remove it in another PR. You're just making work for people.

**Comment by Stadler76** [comment]
> You seem to be saying you agree with me and then just talking past me. There is no reason to backport anything from Magiclysm to the main game and say that someone else should come remove it in another PR. You're just making work for people.

I'm willing to do that myself. But not in this PR. Anyway: I'll convert this to a draft real quick and make a commit to show my intention.

**Comment by RelMayers** [comment]
> > You replied while I was in the middle of editing my post, so I'll just reiterate: Lizard sucks pretty badly to play. Getting rid of a single -2 or -3 point mutation isn't going to make it overpowered, and "game balance" is not a justification for insisting that lizards have webbed feet/hands. They don't have either IRL, and should have neither in Cataclysm.
> 
> I agree with you, but revisiting lizard mutation would better fit into a separate suggestion/PR.
> 
> [Edit:] I'll consider undoing the changes to lizards and making TOE_CLAWS dragons only. But I need to discuss that a bit. So give me time ^^

Don't back port magicalysm mutations, they work fine in their place which isn't same as mainline. Just because there is addition to mutations in magicalysm doesn't mean it would make any sense in mainline

**Comment by Stadler76** [comment]
@fairyarmadillo: There. Now it's black dragon only and doesn't touch vanilla anymore.

**Comment by chrispikula** [comment]
> Lizards don't have webbed feet IRL. What's the justification for this?

Turtles, Alligators and Crocodiles would disagree.

**Comment by fairyarmadillo** [comment]
> > Lizards don't have webbed feet IRL. What's the justification for this?
> 
> Turtles, Alligators and Crocodiles would disagree.

None of those are lizards.

**Comment by Zireael07** [comment]
@fairyarmadillo: Not from a scientific POV, but most layman depictions of a "lizard" will look like a croc/alligator...

Offtop: I seem to remember a Turtle tree being proposed once upon a time, it might be a solution?

**Comment by fairyarmadillo** [comment]
Lizard mutagen isn't a layman's depiction of a lizard, it's a drug from a highly advanced laboratory that turns people into lizards.

A separate turtle mutation line would be great. So would a crocodilian.

**Comment by Stadler76** [comment]
> Lizard mutagen isn't a layman's depiction of a lizard, it's a drug from a highly advanced laboratory that turns people into lizards.
> 
> A separate turtle mutation line would be great. So would a crocodilian.

This is the current version of `TOE_CLAWS` in Magiclysm:
```json
  {
    "type": "mutation",
    "id": "TOE_CLAWS",
    "name": { "str": "Reptilian Legs" },
    "points": 0,
    "description": "Your legs and feet have become reptile-like and your toenails have grown into short claws.  Fortunately they don't impede your movement.",
    "types": [ "LEGS", "FEET" ],
    "cancels": [ "WEBBED_FEET" ],
    "category": [ "DRAGON_BLACK" ],
    "changes_to": [ "DRAGON_FEET" ]
  },
```
I could backport this to mainline lizards and at the same time remove Webbed Hands and Webbed Feet from lizard category.
This is as an option to have variants for other reptilian subtrees, like turtle and crocodile, later. And to make lizards more accurate ofc.

@fairyarmadillo: If you want this, make a suggestion issue and point me to it. Baking that into an actual PR should be pretty straightforward and a good oppotunity to test [`"abstract"`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#copy-from-and-abstract) mutations.

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
