### PR TITLE
Fix crash from reachability zones checking dead NPCs.

### LINKED ISSUE #70649: Crash when trying to kill or after killing a hostile military deserter near his outpost in the city. ​
### Describe the bug

This is the first time I encountered such a strange error. Each time, after killing any of these deserters, the game would crash during the next turn. It didn’t matter who killed them and how, the game still crashed after that.

### Attach save file

[Новая-Aнглия.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833482/-A.zip)

### Steps to reproduce

1. I aim my ranged weapon at the deserter.
2. I fire a shot and kill him.
3. I'm trying to wait for a new move

### Expected behavior

The turn after killing the deserter NPC must be completed successfully.

### Screenshots

Screenshot_2024-01-04-23-00-59-330_com cleverraven cataclysmdda experimental
Screenshot_2024-01-04-23-00-55-422_com cleverraven cataclysmdda experimental

### Versions and configuration

- OC: [Android 8]
- Game version: [1ec6b8c (64-bit)]
- Tileset: [Ultica]
- Language: [System (Russian)]
- Loaded mods mods: [dda], [translate_dialogue], [package_bionic_professions], [personal_portal_storm], [alt_map_key], [minimod_no_rust], [stamina_pool_buff]

### Additional context

[crash.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833529/crash.log.zip)
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833536/debug.log.zip)
[Новая-Aнглия.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833541/-A.zip)

### PR DESCRIPTION
**Pull request by prharvey**
#### Summary
Bugfixes "Fix crash from reachability zones checking dead NPCs."

#### Purpose of change

Fix #70649

#### Describe the solution

NPCs weren't being cleaned out of the zone map. In general this code path is scattered all over `game.cpp` since `game` is a friend class, and trying to manage it manually would be too fragile. Instead, the pointers are swapped to `shared_ptr`s and are removed during iteration if the creature is no longer in the tracker.

#### Testing

Can't reproduce issue after change. Killed a bunch of npcs/monsters and shifted zones and it appears to work.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Is this your clang error or someone else's?  If someone else's I... just realized I wouldn't know how to fix that.  Sorry was gonna say I'd try to fix it.
```
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/map.cpp:9725:10: error: Avoid auto in declaration of 'loc'. [cata-almost-never-auto,-warnings-as-errors]
    for( auto &loc : tr_proximity ) {
         ^~~~~~
         tripoint &
```

**Comment by RenechCDDA** [comment]
> Is this your clang error or someone else's? If someone else's I... just realized I wouldn't know how to fix that. Sorry was gonna say I'd try to fix it.

looks like it was introduced by one of the dormant zombies PR. Just needs the `loc` variable to be explicitly typed. Should not hold up merging this once it's good to go.

**Comment by prharvey** [comment]
> Is this your clang error or someone else's? If someone else's I... just realized I wouldn't know how to fix that. Sorry was gonna say I'd try to fix it.
> 
> ```
> Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/map.cpp:9725:10: error: Avoid auto in declaration of 'loc'. [cata-almost-never-auto,-warnings-as-errors]
>     for( auto &loc : tr_proximity ) {
>          ^~~~~~
>          tripoint &
> ```

As noted that is due to an unrelated PR and there is a fix out for it already. That said, could you please restart one of the cancelled ASAN checks? I would at least like one of those to run before I can say this is ready.

**Comment by Maleclypse** [comment]
They are queued but sometimes those queues hang.  If they haven't run by tomorrow morning please close and reopen and see if that fixes.

**Comment by prharvey** [comment]
> They are queued but sometimes those queues hang. If they haven't run by tomorrow morning please close and reopen and see if that fixes.

Unfortunately it's a problem with the flaky overmap test. The builds are run one after another, and if any of the tests fail they all stop. I can keep closing/opening until it gets to the ASan build, but I was hoping you had the power to just run that specific check instead of all of them all over again.

**Comment by inogenous** [comment]
Nice find! This fix might also address #70595 .

**Comment by Maleclypse** [comment]
> > They are queued but sometimes those queues hang. If they haven't run by tomorrow morning please close and reopen and see if that fixes.
> 
> Unfortunately it's a problem with the flaky overmap test. The builds are run one after another, and if any of the tests fail they all stop. I can keep closing/opening until it gets to the ASan build, but I was hoping you had the power to just run that specific check instead of all of them all over again.

You are wrong. At the time I was commenting your tests were queued with no failures stopping the queue. When tests are queued but the build hasn’t failed no one has the ability to reset the queued test. Once a queue has completed either through a queue ending failure or completion I have the ability to rerun specific tests. There were no queue ending overmap failures then. I checked. They may have come shortly after but I guarantee you that I looked through your test suite before I opened my mouth.

**Comment by Maleclypse** [comment]
I should mention it’s also possible that between when you requested it and I came and commented that someone else could have restarted your tests. That would explain you and I having seen different things.

**Comment by Maleclypse** [comment]
I’m rerunning your failed tests to see if we can get this to green.

**Comment by prharvey** [comment]
> I should mention it’s also possible that between when you requested it and I came and commented that someone else could have restarted your tests. That would explain you and I having seen different things.

To be clear, when I requested it no checks were queued. One of the builds had failed and cancelled everything.

**Comment by Maleclypse** [comment]
> > I should mention it’s also possible that between when you requested it and I came and commented that someone else could have restarted your tests. That would explain you and I having seen different things.
> 
> To be clear, when I requested it no checks were queued. One of the builds had failed and cancelled every build after (including the ASan one I was interested in).
> 
> Looks like someone else restarted it: https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/7428655094/attempts/2?pr=70687

Well it’s good to know neither of us is crazy :)

**Pull request merged**
