### PR TITLE
UltiCa Update 17 June 2020

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Content "Update UltiCa Demo"

#### Purpose of change
UltiCa hasn't been updated since March!

#### Describe the solution
Updates UltiCa.

This version has many enormous changes - it's been three months!
We've had some major stylistic changes to how monsters and NPCs are displayed, from shadows to a new "soft" outline to make them pop better. Of course many new items, monsters, and terrains have been added and expanded.

Gah I am so damn proud of how this set looks.
image

I mean, honestly. Look at this stuff! Look at that shower!
image

soft outlines have helped to make monsters 'pop'
image
image

Jeez louise.
Anyway, once we have cars this is gonna be some real srs business.
image

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Awesome! Getting better and better.

I've noticed that character does not have the soft outline (shadow), so he stands out in a crowd of zombies as an odd one. Perhaps a small shadow at the feet would be in place?

Also what is visually striking in the wilderness is that there are no seamless transitions between grasses (see first and second picture), so there are unnatural dirt borders between them. Something to consider in further development.

**Comment by I-am-Erk** [comment]
The dirt borders require some changes to the renderer.

**Comment by barsoosayque** [comment]
> I've noticed that character does not have the soft outline (shadow), <...>

Ow, it's actually a bug. Player character should have the same shadow as the normal zeds. And small shadows looks like normal shadows (like that one under the kid in the last screenshot), which is also a bug, as there are small shadows for small creatures.

Shoulda fix that in the next version !

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/ultica-tileset-update-thread/19033/92

**Pull request merged**
