### PR TITLE
Add item enchanting to magicalysm mod

### LINKED ISSUE #63243: Magicalism Add ability to enchant weapons
### Is your feature request related to a problem? Please describe.

no

### Solution you would like.

adding new item called Enchanter's Toolkit that spawns in wizard tower
adding a new book for enchantment recipes
adding ability to craft enchanted items with it example:
Lucerne hammer+1 
Required: tool: Enchanter's Toolkit
Time:2 hours
Required: Materials: Lucerne hammer and 20 mana dust/4 lotus flowers/ 9 funnelcap chunk
Result:Lucerne hammer+1 

Lucerne hammer+2
Required: tool: Enchanter's Toolkit
Time: 3 hours
Required: Materials: Lucerne hammer+1 and+ 25 mana dust/5 lotus flowers/ 12 funnelcap chunk
Result:Lucerne hammer+2

### Describe alternatives you have considered.

no

### Additional context

just an idea we can discuss adding it or about crafting recipes

### PR DESCRIPTION
**Pull request by alp7292**
#### Summary
Adds item enchanting to magicalysm mod
#### Purpose of change
closes #63243
adds a way to enchant items
#### Describe the solution
adds a new profeciency for enchanting
adds a new book that has a chance to spawn in magic shop that gives recipe for enchanting
adds a new category for enchanting recipes
adds enchanting recipes

#### Describe alternatives you've considered
 a different method of enchanting

#### Testing
created character and checked magic shop for book. found one and with mana dust, copper bracelet and crowbar i enchanted crowbar. gained profeciency

#### Additional context
we can adjust recipes with request and adjust the spawn chance of book as its very rare
every tier increases damage by %10 and decreases weight by %10 so i find it suitable for same requirement for both +1 and +2
to hit bonus doesnt seem to work or i understand it wrong.

### CODE REVIEW

**Comment by GuardianDll** [comment]
For the reference, you need to use https://dev.narc.ro/cataclysm/format.html when you do your PR, to prevent this bot spam

**Comment by alp7292** [comment]
> For the reference, you need to use https://dev.narc.ro/cataclysm/format.html when you do your PR, to prevent this bot spam

should i delete this and make a new one

**Comment by GuardianDll** [comment]
No, the tool actually do exactly what bot tries to reach - make your code be in style with another code in the repo
the tool can just fix the whole file, when bot need to do stuff one by one
what you can do is open your files, copy them into the tool, press "lint" and send them again - git allow you to overwrite the changes you did already

**Comment by GuardianDll** [comment]
No need to reopen your PR actually, just lint your files and send them as you did before

**Comment by GuardianDll** [comment]
ok it seems it is actually easier to reopen it, yeah

**Pull request closed without merging**
