### PR TITLE
Refactory inventory classes

### PR DESCRIPTION
**Pull request by mugling**
Whilst trying to extend the holstering code I noticed the classes in `inventory_ui.h` are effectively undocumented and use some very non-standard constructs. In particular there is a lot of spurious/obfuscating usages of `std::shared_ptr`.

This PR provides an initial refactor of those classes:
- Dead code and unused typedefs are removed
- Check valid filter function is passed (avoiding potential `std::bad_function_call` exception)
- Avoid returning references to objects of indeterminate lifetime
- Drop all uses of `std::shared_ptr` and `std::unique_ptr`
- Drop non-encapsulating accessors from `inventory_entry` which become a struct

In part 2 I'm going to have a go and adding some documentation

### CODE REVIEW

**Comment by Coolthulhu** [comment]
There's a very high chance that this change would bring huge conflicts with @codemime 's new menu code.

While the menu code wasn't updated for a while and is too huge to be merged right now, a big part of it is good to go. Bringing huge conflicts could make it impossible to keep it updated.

**Comment by mugling** [comment]
> There's a very high chance that this change would bring huge conflicts with @codemime 's new menu code.

Yes, but that's precisely the reason why 2000+ line PR's are not permitted.

> Bringing huge conflicts could make it impossible to keep it updated.

It's unreasonable to expect all other development work to stop so as to maintain compatibility. Conflicts have always been the responsibility of the branch author and that doesn't change just because they have made that task nearly insurmountable.

> a big part of it is good to go

It has a lot of outstanding review comments, many of which are answered as `WONTFIX`. Additionally it looks abandoned and when I recently asked about making my changes received no reply.

Additionally that authors last viewpoint was:
> I could point you out lots of such precedents and with much higher number of lines
> I don't see a reasonable way of significantly reducing its size
> I would also appreciate some more feedback from the other developers

The first isn't true (and requested citation was not provided), the second affirms that the branch is dead in the water and the latter was followed by definitive replies that the branch could not be merged.

The only way forward is to resume the original plan of reasonably sized PR's. This one fixes three unpleasant problems, the first is the `shared_ptr` issue, the second that `execute` returns a reference to an object with poorly defined lifetime (potential segfault) and the third that an empty `std::function` is accepted (termination via exception).

If @codemime want's to resume refactoring via smaller PR's then they can take precedence but the presence of the rejected PR provides no reason to block this one and there last statements were that they do not wish to pursue such an approach.

**Comment by mugling** [comment]
Rebased against master

**Comment by Coolthulhu** [comment]
I didn't see @codemime comment on the whole issue or update #17765
I'm gonna give him one more chance to comment before we introduce a lot of conflicts. Skipping it in this merge run, will test in the next one.

Also, the merge isn't complete.

**Comment by mugling** [comment]
@Coolthulhu sounds reasonable. The idea behind #17765 if @codemime wants to refactor it into a series of smaller PR's.

**Comment by mugling** [comment]
@Coolthulhu sounds reasonable. The idea behind #17765 is solid if @codemime wants to refactor it into a series of smaller PR's.

**Comment by codemime** [comment]
Sorry for the long absence: I was travelling last two weeks. I'm about to continue my work on #17765: reduce it to a reasonable size (as much as it's possible) and make changes after the last reviews.
@Coolthulhu Thank you for this.

**Comment by mugling** [comment]
One possible approach is to start with a refactor int the first (including addressing the above issues), then add the ancilliary functions (liquid handling etc) and then one of your custom screens in the third PR.

**Comment by codemime** [comment]
I think I'm going to drop custom presets completely (leaving only the base `inventory_selector_preset` class) and turn the PR into a pure refactoring (as [suggested](https://github.com/CleverRaven/Cataclysm-DDA/pull/17765#issuecomment-235063069)). Some of the above issues has already been addressed, some others will be addressed soon, but I'm against turning `inventory_entry` back into a transparent `struct`.

**Comment by mugling** [comment]
Rebased and ready to merge

**Pull request closed without merging**
