### PR TITLE
Mod for bionic claws and monomolecular blade to pickup items.

### PR DESCRIPTION
**Pull request by Lorith**
For those of us annoyed with the activate, kill a few zombies, deactivate, loot, activate cycle.

### CODE REVIEW

**Comment by chaosvolt** [comment]
I've proposed this change for the bionic claws, it was vetoed as it's implied they're more for combat than utility.

Personally, I agree with the monomolecular blade being too combat-centric enough that it might hinder the use of your hands (think integrated duel-wielded katars or even patas), but the bionic claws might not warrant this. They're either like Wolverine claws (which might logically give hand encumbrance, but wouldn't outright prevent using your hands) or more like oversized retractable claws.

If it's the latter, it makes less than no sense that the mutation equivalents, which have no evolutionary imperative to conform to the demands of human physiology, to be MORE user-friendly than something designed by humans for humans.

**Comment by kevingranade** [comment]
It makes perfect sense, the biological claws are adapted from a feature
that must be general purpose, while the bionic claws are specifically
designed for combat.  Also no wolverine claws, they're nonsensical.

**Comment by chaosvolt** [comment]
Hmm. Thing is that creatures with big nasty claws are generally not that prone to having opposable thumbs or other things conducive to manual dexterity, bird talons being a notable exception.

Though I guess they're more like integrated tiger claws, if the blade is an integrated katar?

**Comment by Coolthulhu** [comment]
Picking up doesn't take much manual dexterity. You could grab most of the stuff with wrists alone in an emergency.

Maybe change the "no pickup" to just penalty at pickup?

**Comment by Lorith** [comment]
That is part of why I made this as a mod, if you want the game as it is, nothing changes.  If it is annoying and you want to pick things up, then you can enable the mod, which then lets you pick things up.

**Comment by chaosvolt** [comment]
Like I said, it at least makes sense for bionic claws, if not the blade.

Glad to see @Coolthulhu weigh in on this.

**Comment by Rivet-the-Zombie** [comment]
I agree; we should add a new flag that slows you down when grabbing stuff off the ground and change the NO_PICKUP flag on the claws (and optionally the blade) to use it instead.

**Comment by chaosvolt** [comment]
Now if the same option could be applied to certain mutation claws...being able to give mutations item properties would actually being very handy, as we could use them to give sharp enough claws a low, possibly negative (like with sharp rocks) butchering quality.

**Comment by Marrim** [comment]
I thought the no_pickup was a balancing factor that made you spend bionic energy, otherwise you could just keep them extended all the time for no energy cost.

An option to auto-retract them when trying to pickup something would be nice, though.

**Comment by DeNarr** [comment]
Is there any reason to assume the cyber enhancements are using both arms anyways? The game doesn't really do dual wielding, so you could assume the weapon is only on the primary hand, and that you have the off hand to pick things up or use things.

Also, if you want, you can wield a 50 gallon drum in your hands, and still be able to pick things up without having to drop the drum (assuming you still have space in inventory) and then pick it back up afterwards.

**Comment by chaosvolt** [comment]
Another good point that makes this balancing factor look ridiculous in context, yeah.

Then again, it would be reasonable to assume that you ARE dropping the barrel long enough to grab items, and that the action is abstracted away. Something you can't do with a bionic weapon.

**Comment by kevingranade** [comment]
Obsoleted by #14118, thanks for bringing it to my attention (again).

**Comment by chaosvolt** [comment]
Yay. o3o

**Pull request closed without merging**
