### PR TITLE
Make gold ring fancy

### PR DESCRIPTION
**Pull request by jacobchess13**
#### Summary
Bugfixes "Make gold ring fancy"

**Purpose of change**

Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/57460
The gold ring was not fancy. In my experience, a real gold ring generally seems fancy, especially when it is a "flashy gold ring".
So, the gold ring needs to have the "fancy" flag added.

**Describe the solution**

Add the fancy flag to the gold ring json.

**Describe alternatives you've considered**

Give the gold ring the SUPER_FANCY flag.
Change the gold ring's description to something like "A plain, boring gold ring" to justify it not having the fancy flag.

**Testing**

Copied the change into my local up-to-date game, change worked without any bugs.

**Additional context**

This is my first PR or code contribution ever so please excuse any mistakes I made.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Not a problem here currently, but as a rule don't make pull request from your master branch, always make pull request from a branch specific to the change you want to add

**Comment by jacobchess13** [comment]
Thank you!

**Comment by jacobchess13** [comment]
Is my formatting OK or do I need to change it somehow?

**Comment by jacobchess13** [comment]
Thank you for your help everyone!

**Comment by jacobchess13** [comment]
this is @hicc on discord

**Pull request merged**
