### PR TITLE
Prevent player from closing vehicle doors when standing on them (partial fix)

### LINKED ISSUE #13388: Can close vehicle doors while standing on them
Win 7 x64 w/tiles, build 0.C-3590.  As per the title.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26102625-can-close-vehicle-doors-while-standing-on-them?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by drbig**
Addresses #13388.

Getting particular part global position seems to be a rather involved business, so unless there are some weird special cases this should work (or at least be better than nothing).

### CODE REVIEW

**Comment by narc0tiq** [comment]
I seem to recall `vehicle_part`s had a `int dx[2], dy[2]`, the 0th of which
represent the part's current reality-bubble-relative position (the 1th
being the "next turn" position, or something like that). This is a better
solution than searching for the vpart, though.

**Comment by drbig** [comment]
I've looked into that - `mount` gives an offset which would then need to be offset given the vehicle origin point (no idea if I'd need to care for rotation myself) = "more involved business". Doesn't seem worth the trouble unless edge-cases...

**Comment by Coolthulhu** [comment]
> Getting particular part global position seems to be a rather involved business

It's `veh->global_pos3() + veh->parts[p].precalc[0]`. This gives the position in the same coordinates as player's position.

1 tile vehicle doors will always be where they are closed/opened, but multitile ones aren't handled here. Due to the way `vehicle::open_or_close` is handled, it may be non-trivial to test for them.

**Comment by drbig** [comment]
@Coolthulhu So... stick with the naive check here? Or use the coords as you've provided (thanks!)? I don't feel like poking around the multi-tile case (working on #13393)...

**Comment by Coolthulhu** [comment]
> So... stick with the naive check here? Or use the coords as you've provided

Both should refer to the same tile, so leaving them as-is should be fine.

> I don't feel like poking around the multi-tile case

Then it doesn't fully close the issue, even though it fixes the most common case.

**Comment by narc0tiq** [comment]
Yes, now I remember, it was `px` and `py`, and they were later formed into the `precalc` array of (tri)points.

**Comment by BevapDin** [comment]
Well, it's a start. You probably need to find all the parts that would be closed via `vehicle::close` and check them manually for creatures (hint: `game::critter_at`).

**Pull request merged**
