### PR TITLE
Mutations can have a colour

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Infrastructure "Mutations can have a colour"

#### Purpose of change

Allow one mutation to exist in different colours, that way we could consolidate all hair colour mutations into one per hair style.
And it would also allow other mutations like fur to have colored variants

Also in a later PR we could add the option to use items to colour your hair or your fur

#### Describe the solution

```json
  {
    "type": "mutation",
    "id": "LUPINE_EARS",
    "name": { "str": "Lupine Ears" },
    "points": 1,
    "visibility": 4,
    "ugliness": 1,
    "description": "Your hearing has evolved further and is now on par with that of wolves.  You can hear things significantly farther away.",
    "types": [ "EARS" ],
    "colours": [ [ "pink", 1 ], [ "grey", 5 ], [ "brown", 3 ] ],
    "category": [ "LUPINE" ],
    "hearing_modifier": 1.75
  }
```

Get the mutation > if mutation has colours pick one > add it in trait_data
Add "_[colour]" at the end of the overlay id

**To do list:**
- [x] Implementation to display colour variant of overlays
- [ ] Ability to chose hair/eye colour at char gen 
- [ ] Deal with mutations obsoleted by this change
- [ ] Add content and put some colours on existing mutations
- [ ] Documentation

#### Testing

image

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Are these colours just free entry? Or do they have to be the in game colour palette? The latter won't work well since hair is often given different colour names like "blond", and we may want different things like fur patterns "tabby"

**Comment by Fris0uman** [comment]
Currently it's just a string so It's completly free

**Comment by SunshineDistillery** [comment]
Color with a 'U' is going to trip people up.

**Comment by Fris0uman** [comment]
Is it okay to have a popup like this in character creation? 
image

Or should  it be presented another way?

**Comment by Fris0uman** [comment]
Current implementation kills the trait_groups that make NPCs and random PC have coherent looks. Not sure howe to move that into this color system

**Comment by Fris0uman** [comment]
Can't figure out how to not break the trait group system. Feel free to pick it up if you have a solution.

**Pull request closed without merging**
