### PR TITLE
add rubber

### PR DESCRIPTION
**Pull request by Jerimee**
#### Summary
```SUMMARY: Content "add rubber as a material"```

#### Purpose of change

This adds a synthetic rubber material (named simply "rubber") to materials.json.

In my mind this is very much needed, there are a number of items which are explicitly made of rubber without any material designation to reflect rubber's unique properties

#### Describe the solution

**I modified iuse_actor.h:** I changed the class salvage_actor so that material_whitelist included rubber.

added rubber to materials.json

Add the rubber material to a number of items, including:
- rubber hose
- rubber gloves
- rubber boots
- rubber dog rainsuit
- rubber slug
- pair of turnout boots
- pair of combat boots
- lowtops
- swim_fins
- wetsuit_gloves
- glass flask (rubber bung)
- test tube (rubber bung)
- toilet plunger
- spatula
- drive belt
- rubber sole

This adds rubber and chunk_rubber to main game, so this pr **DELETES** data\mods\CRT_EXPANSION\crt_materials.json

I added a handful of uncraft recipes.  

#### Describe alternatives you've considered

Synthetic rubber is surprisingly different from natural rubber, but I expect natural rubber is now rather rare in New England, so I've made no provision for natural rubber.  This material is called "rubber" not "synth rubber."  I mean this rubber definition to be the most prevalent type of rubber and thus it is just "rubber."

If I understand correctly, the rubber in "rubber gloves" and "rubber hose" and "rubber tires" are very different kinds of rubber.  But just as "wood" and "gemstone" don't distinguish between different types, rubber is simply generic.

The gas produced by rubber burning is highly toxic. "Rubber smoke" should be different than fire smoke, but I've not attempted to model this (ie make it happen in game).

**elec_resist** - I do not know how rubber compares to ceramic and glass as an insulator. I've set the elec_resist of rubber to ~~9~~ 11, because ceramic is 10. I've also increased the elec_resist of glass to 4; it probably should be even higher. _CRIT mod had it at 20._

Bash resist is 5, perhaps it should be much higher.

I moved some entities within the file to partially alphabetize by ident; perhaps partial alphabetical order is worse than no order.

I removed leather from sneakers and replaced it with rubber.

#### Testing

I loaded the game several times with various versions of this PR without incident.

A good test to do would be to burn a rubber hose and see what happens. I tried to give stats that would reflect rubber items long burning with much smoke but little fuel.

When I did this test outdoors the rubber did burn a longish time, but produced no smoke that I could notice. When I did it indoors it produced smoke.  A pile of rubber hose will burn up entirely, but a pile of chunks of rubber seems to burn only two at a time before fire goes out.  Which is curious, but not necessarily wrong. 

#### Additional context

I moved a couple of unrelated entries in a partial attempt to alphabetize the materials.json file.

I modified my stats for rubber in the direction of those given by the CRIT mod.  As instructed, I removed rubber from that mod, as rubber will now be in the main game.

I had to guess (extrapolate based on other entities) with regard to burn data and chip resist. I wasn't able to find any doc on burn data, and chip resist remains ambiguous.

Just for fun I added another bottleopener flavor message.

I've added rubber as a material for 16+ items.  Once this PR is approved, I look forward to adding rubber to tires and other obviously rubber items.  I suspect I will also make a rubber band item and add it (in various quantities) to junk drawers.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Please add this material to at least one item. Otherwise it's dead weight with no purpose.

**Comment by ZhilkinSerg** [comment]
Note that rubber exist in CRIT mod.

**Comment by CodeBandit** [comment]
I support the existence of rubber as an item. But considering that it looks like the main gist of your post is that rubber is missing from most things that are rubber-made, this should also contain the changes needed to make those rubber containing items contain that rubber. Otherwise, as Night-Pryanik mentioned, it's dead weight with no purpose. As a counter to this, plastic is just the general term used for all synthetic polymers at the moment.

**Comment by Jerimee** [comment]
> Note that rubber exist in CRIT mod.

Hmmm, how do we handle that? Should I respect the namespace (ie not use the "rubber" ident already used by this mod)?

```json
​[
  {
    ​"​type​"​: ​"​material​"​,
    ​"​ident​"​: ​"​rubber​"​,
    ​"​name​"​: ​"​Rubber​"​,
    ​"​density​"​: ​12​,
    ​"​soft​"​: ​false​,
    ​"​bash_resist​"​: ​5​,
    ​"​cut_resist​"​: ​1​,
    ​"​acid_resist​"​: ​8​,
    ​"​fire_resist​"​: ​1​,
    ​"​elec_resist​"​: ​20​,
    ​"​chip_resist​"​: ​9​,
    ​"​repaired_with​"​: ​"​plastic_chunk​"​,
    ​"​salvaged_into​"​: ​"​chunk_rubber​"​,
    ​"​dmg_adj​"​: [ ​"​ripped​"​, ​"​torn​"​, ​"​shredded​"​, ​"​tattered​"​ ],
    ​"​bash_dmg_verb​"​: ​"​ripped​"​,
    ​"​cut_dmg_verb​"​: ​"​cut​"​,
    ​"​burn_data​"​: [ { ​"​fuel​"​: ​1​, ​"​smoke​"​: ​3​, ​"​burn​"​: ​1​ }, { ​"​fuel​"​: ​1​, ​"​smoke​"​: ​3​, ​"​burn​"​: ​2​ }, { ​"​fuel​"​: ​1​, ​"​smoke​"​: ​3​, ​"​burn​"​: ​3​ } ]
  },
  {
    ​"​type​"​: ​"​AMMO​"​,
    ​"​id​"​: ​"​chunk_rubber​"​,
    ​"​category​"​: ​"​spare_parts​"​,
    ​"​price​"​: ​75​,
    ​"​name​"​: { ​"​str​"​: ​"​chunk of rubber​"​, ​"​str_pl​"​: ​"​chunks of rubber​"​ },
    ​"​symbol​"​: ​"​*​"​,
    ​"​color​"​: ​"​dark_gray​"​,
    ​"​description​"​: ​"​A chunk of useful rubber, can be molded easily.​"​,
    ​"​material​"​: ​"​rubber​"​,
    ​"​volume​"​: ​"​250 ml​"​,
    ​"​weight​"​: ​"​38 g​"​,
    ​"​ammo_type​"​: ​"​components​"​,
    ​"​flags​"​: [ ​"​NO_SALVAGE​"​ ]
  }
]
```

**Comment by Night-Pryanik** [comment]
Use your variant and remove duplicate from the mod.

**Comment by ZhilkinSerg** [comment]
Yes, just mainline rubber and remove it from the mod.

**Comment by Jerimee** [comment]
@Night-Pryanik you sure you want me to add it to items?  A trivial thing to add it to a handful of items, but I purposefully did not do that, as I wanted this PR to be as simple as possible.  

Assuming yes, I will add it to the following:

- rubber hose
- rubber gloves
- rubber boots
- rubber dog rainsuit

@ZhilkinSerg sounds good, and that means I will need to add ​chunk_rubber too.

@Soupster89 fyi

**Comment by Jerimee** [comment]
Travis is mad because:

> All tests passed (2529506 assertions in 388 test cases)
> Ended test at Wed Apr 22 23:12:00 2020
> The test took 135.319 seconds
> Treating result as failure due to error logged during initialization.
> Randomness seeded to: 1587596966

CI is mad because:

> All tests passed (2529064 assertions in 388 test cases)
> 
> Ended test at Wed Apr 22 22:59:07 2020
> The test took 91.319 seconds
> 
> Treating result as failure due to error logged during initialization.
> Randomness seeded to: 1587596242
> Makefile:39: recipe for target 'check' failed
> make[1]: Leaving directory '/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/tests'
> 22:57:28.109 WARNING : opendir [./save/Tom/mods] failed with "No such file or directory".make[1]: *** [check] Error 1
> Makefile:1120: recipe for target 'check' failed
> make: *** [check] Error 2
> ##[error]Process completed with exit code 2.

I'm thinking that this is unrelated to my PR.

**Comment by anothersimulacrum** [comment]
It's your thing to fix:
https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/jobs/678372467#L4544-L4610
(error logged during initialization means an error that occurs when the data is loaded - these can be errors shown only when the game is built for tests, which is what is happening in this case).

**Comment by Jerimee** [comment]
#$%#$&*@ - what does "errors shown only when the game is built for tests" mean? Thanks in advance for help.

**Comment by anothersimulacrum** [comment]
For performance reasons, we don't track what members of each JSON object are loaded when the game is not built for tests. When it is, we do.

What these errors are saying is that the game isn't loading any data from these fields.
That mean they're either in the wrong place, or have a typo.

**Comment by Night-Pryanik** [comment]
@Jerimee yes, please add rubber as a material to all items in your list.

**Comment by Jerimee** [comment]
I got this error:

` DEBUG    : Error: data/mods//dda/../../json/items/generic/bathroom_house.json: line 48:14: Duplicate snippet id

    "snippet_category": [
      {
        "id":
             ^
              "tbrush1",
        "text": "A plastic brush with soft bristles for cleaning your teeth.  It has a cheap, blocky handle and is likely meant to be disposable."
      },


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 820
`

note that it says mods in the directory - I'm a bit confused - going to go try to find that file...

**Comment by Jerimee** [comment]
So now I've loaded the game without errors... The items made of rubber material don't seem to do anything odd.  I'm at a loss as to what to investigate now... Thanks for trying to explain it to me.

Since the material existed in the CRIT mod, and essentially all I've done is copy it over to main, it seems like there shoudn't be very much that can go wrong.  I'll check again for typos.

**Comment by YakumoChen** [comment]
shouldn't most shoes in general also be using rubber? What about car tires?

**Comment by Jerimee** [comment]
Yup, I will add some of those, but I intend to do a whole followup sweep _after_ this PR gets approved.

**Pull request merged**
