### PR TITLE
Rewrites: 300 Weatherby

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by John-Candlebury** [comment]
I much prefer the older description, even if the one you propose here is more matter-of-fact.

**Comment by Rivet-the-Zombie** [comment]
The original sentence was from the Wikipedia article, while the revised version is not. Plus it's a cool bit of trivia about the gun.

**Comment by BorkBorkGoesTheCode** [comment]
>The original sentence was from the Wikipedia article, while the revised version is not. Plus it's a cool bit of trivia about the gun.

This is why. I have no objection to quoting sections from Wikipedia, as long as the quotes are attributed.

**Comment by BorkBorkGoesTheCode** [comment]
I might have found the original author on Wikipedia: DeusImperator added the lines on 13 June 2011 07:27.

**Comment by BorkBorkGoesTheCode** [comment]
There are a few copy-paste sites on the net with the original wording. I'm going to check shootingpress.com

**Comment by mugling** [comment]
I'm not sure if this type of PR is especially productive as there isn't any objective way of deciding what is better

**Comment by BorkBorkGoesTheCode** [comment]
Finding the original author is a priority.

**Comment by mugling** [comment]
> Finding the original author is a priority.

Why? Asides your taking content from lots of other sites and I don't see any attribution at all

**Comment by BorkBorkGoesTheCode** [comment]
>Why? Asides your taking content from lots of other sites and I don't see any attribution at all

Which?

**Comment by mugling** [comment]
Your other PR's that change the `description`

**Comment by BorkBorkGoesTheCode** [comment]
>Your other PR's that change the  description 

Which ones?

**Comment by mugling** [comment]
> Your other PR's that change the description
> 
> Which ones?

Why don't you look through some of your previous PR's?

**Comment by BorkBorkGoesTheCode** [comment]
>Why don't you look through some of your previous PR's?

I have, and I cannot find what you are talking about. Which PR are you talking about?

**Comment by mugling** [comment]
For example #18550 

> The description was partly mirrored by an article on military.com

**Comment by BorkBorkGoesTheCode** [comment]
>The description was partly mirrored by an article on military.com

The previous description (that was replaced by that PR) was present on military.com; that, and the weird punctuation, is why I rewrote the description in the first place.

**Comment by mugling** [comment]
I see

**Comment by BorkBorkGoesTheCode** [comment]
Could someone please properly cite the author?

**Comment by BorkBorkGoesTheCode** [comment]
@John-Candlebury @mugling  what descriptive tone were you looking for?

**Comment by Rivet-the-Zombie** [comment]
This description is good and this discussion is going nowhere.

**Pull request merged**
