### PR TITLE
Revert "Attempts to fix nether monster generation"

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

Reverts CleverRaven/Cataclysm-DDA#64421

Not fixed after all,  so now the plan is to revert both and get back to working.

### CODE REVIEW

**Comment by irwiss** [comment]
Is it on purpose that this reverts just the one unsuccessful fix attempt commit?
The original PR changed 15 files https://github.com/CleverRaven/Cataclysm-DDA/pull/63611

**Comment by kevingranade** [comment]
Yea I need to do this one first and then the other one since I'm doing it in my phone.

**Comment by LovamKicsiGazsii** [comment]
That's a bummer, didn't expect the tentacles to error from beyond the grave. :/
So the overall plan is to prevent the mutable from spawning or removing it entirely?

**Comment by GuardianDll** [comment]
Right now we remove it entirely, because both the game and our autotests are bricked because of it

**Pull request merged**
