### PR TITLE
Aftershock Exosuit Pocket Flags

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Fixes to exosuit inherits flags"

#### Purpose of change
When a PSU is loaded into an exosuit, the suit inherits the "CANT_WEAR" flag, which means if the player removes the suit and tries to wear it again, they can't unless they unload it first.

#### Describe the solution
WIP

#### Describe alternatives you've considered
None,

#### Testing
WIP

#### Additional context
None.

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
do you still want me to do a fix for this or are you happy with the json solution?

**Comment by Drew4484** [comment]
> do you still want me to do a fix for this or are you happy with the json solution?

This was just a change to the plating pockets, since they don't need to take anything from the plating flags. The issue with the modules still happens.

**Comment by bombasticSlacks** [comment]
#58806

**Comment by Drew4484** [comment]
#58806 solves this in a better way, closing.

**Pull request closed without merging**
