### PR TITLE
Convert mods to use new 40mm ammo types.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
#35865 failed to update bundled mods, probably under the assumption that they would be handled by migration entries.

#### Describe the solution
Manually migrate affected entries in various mods.

#### Testing
The various mods load with no errors.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
#36147 Also does this.

**Comment by I-am-Erk** [comment]
The only solution is to put the PRs in an arena and let them battle to the death

**Comment by esotericist** [comment]
given that #36147 got merged, is this PR now obsolete?

**Comment by kevingranade** [comment]
Yes, #36147 was a more complete fix.

**Pull request closed without merging**
