### PR TITLE
Group training seminars

### LINKED ISSUE #51532: Teach NPCs skills
# Is your feature request related to a problem? Please describe.
The NPCs have an option to teach you things, why can't you teach them once a day too?

# Describe the solution you'd like
NPCs can learn when you read to them, learn from a book themselves, or they watch you enough. Why can't you also just teach them so they jump up in skill like they can teach you?

# Describe alternatives you've considered
It would be nice to be able to teach them until they reach the next level, just like reading to them, instead of a bulk once-a-day session like they teach you.

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
Fixes #51532

#### Describe the solution
A new '`C`' menu option was added to initiate a training seminar. The player selects a skill to teach, then selects which of their followers they want to participate in the seminar.
- A skill can only be selected if the player's practical level is >0.
- A follower can only be selected if their theoretical skill is less than the player's selected skill's level

c_menu
skill_menu
npc_menu
result

Also, dialogue options were added to the NPC talk screen for asking the NPC to host a training seminar, as well as for one-on-one training from the player.

talk_menu4
result

The `start_training()` function was refactored into `start_training_gen()`, which accepts one teacher `Character` and an arbitrary vector of student `Character`s. This allows one character to train any number of other characters. A new activity `ACT_TRAIN_TEACHER` was added as well to force the teacher to spend the required time teaching the session.

TODO:
- [x] Create generic routine to handle training an array of `Character`s
- [x] Add conversation logic for initiating a group training seminar (`npctalk.cpp`)
- [x] Add conversation dialog tree for new training options (various json)
- [x] Do not allow student `ACT_TRAIN` activities to complete without the teacher's `ACT_TRAIN_TEACHER` activity
- [x] Adjust training time to reflect reality (roughly 1 hour or more)
- [x] ~Add ability to teach proficiencies, martial arts, and spells~ This would make the menus more cluttered. For now, just add the infrastructure to process these kinds of training.
- [x] Thorough testing

#### Testing
Player teaching seminar:
1. Spawn and recruit a group of NPCs
2. Start a training seminar through the `C` menu
3. Depending on the player's and the NPCs' skill levels, the seminar should take upwards of 1 hour

NPC teaching seminar:
1. Talk to an NPC friend
2. Ask the NPC to host a training seminar
3. Select a number of participating students (including/excluding you)

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @eltank?

**Comment by PatrikLundell** [comment]
If you're going to have one NPC train another you'd have to make sure the one you're not talking to when setting the situation up "knows" about it and so won't continue with a current activity (can either be to break the activity off or not be available for the task while active) and won't be available for a new one (and won't follow the PC around while engaged in a training session).

**Comment by eltank** [comment]
I personally think that this "near-instantaneous training" is not realistic and should either be removed from the game or replaced with a "training seminar" that takes at least 1h and can have multiple participants. 
The current "training" is also practically useless at higher levels (say, above 4) due to how little skill xp it gives vs how much is needed to level up.

My solution to teaching NPCs skills is #51628 (letting them work on practice recipes).

**Comment by dseguin** [comment]
I agree that it's not completely realistic. Do you think it would be reasonable to have both crafting practice as well as group training? As in, you could instruct NPCs to craft items or participate in a training seminar?

**Comment by eltank** [comment]
> I agree that it's not completely realistic. Do you think it would be reasonable to have both crafting practice as well as group training? As in, you could instruct NPCs to craft items or participate in a training seminar?

Both of those options sound realistic to me. But if practice via crafting addresses the problem more efficiently it might not be worth the effort of coding seminars. OTOH if it turns out to be easy to code, then why not.

**Comment by dseguin** [comment]
Good point. I'll refocus this PR on group training like you described.

**Comment by dseguin** [comment]
Ping: @eltank
If possible, could you tell me what you think of the updated solution? (Screenshots in PR description)

**Comment by PatrikLundell** [comment]
I believe training sessions ought to take time rather than being instantaneous with spamming blocked by a "memory" of having trained someone. If seminars (or, for that matter one on one training) takes time there's no need for a timeout timer.
If instantaneous training remains (due to implementation difficulties), the timeout would probably have to remain until that's been sorted out.

The snipped of changed code seems to imply there's a check for if the player has been asked to train ("player_character"), but it really should be a check for the teacher having been asked to train, regardless of whether the teacher is the (current) player character or not.

**Comment by dseguin** [comment]
I'm sorry, I don't really understand. Are you saying that training is currently instantaneous? That shouldn't be the case. I'm using the same mechanism as receiving training from an NPC, so it's handled through an activity. It takes roughly 50-100 turns depending on the skill requirements. (see `talk_function::start_training_gen()`)

Yeah, currently the `asked_to_train` effect is applied to the player when the player teaches a seminar. The effect should be applied in the dialog tree depending on who is doing the teaching. I think if additional dialog is added to allow NPCs to teach seminars, a new case in `game::chat()` would be added to assign the effect to the NPC.

**Comment by PatrikLundell** [comment]
Training currently is very quick, although it might not be instantaneous. 50-100 seconds is extremely fast, whereas I'd expect a "real" training session to be somewhere around 45-60 minutes, based on how long individual lessons tend to be currently.

I thought there was a reason for the specification of the player character, but I don't think it hurts to check. Also, if it's reasonably easy to implement, having the function just take a character would make it possible to reuse it later on when/if the UI issues have been sorted out.

**Comment by dseguin** [comment]
Yes I agree, eltank mentioned earlier that he wanted training activities to take >1h. I've added it to the TODO checklist above.

> Also, if it's reasonably easy to implement, having the function just take a character would make it possible to reuse it later on

That's how I implemented it:
https://github.com/dseguin/Cataclysm-DDA/blob/2f019d742aa5f474f294499c614fefc1c75ff74f/src/npctalk_funcs.cpp#L1012-L1013

**Pull request merged**
