### PR TITLE
Move filthy clothing morale penalty to a mod

### LINKED ISSUE #17254: Filthiness affects everyone, but isn't well designed enough for mainline
Filthiness is a relatively intrusive mechanic without much actual impact.
When it was tied to a trait, it was a voluntary thing. Now everyone has to deal with it.

It isn't difficulty to deal with it because:
* The penalty doesn't stay with you once you remove the filthy clothing
* When you really need to use the filthy items, the filthiness doesn't really matter
* Even with the trait, you eventually can use all items, you only need some soap and water source, which are only hard to find early on
* Zombie items almost universally require repairs before use, meaning only some rare drops (flame-resistant underwear) really require cleaning
* It isn't passed around when crafting

At the same time it can't be said not to be intrusive:
* The morale penalty will stay with you during crafting, unless you manually remove (and then put back on) the filthy clothing
* You can't wait it out, like it is the case with wetness penalty
* Removal requires semi-rare components (soap) and access to water. Ironically the best water access in a city will be the sewer - you'll be cleaning filthy clothing with sewer water
* It is bugged at times due to unstable morale system which doesn't recalculate stats often enough

The biggest problem is that it doesn't properly split two exclusive sections of the game: action and downtime
During downtime, protection doesn't matter much. You don't start crafting in the middle of Hulktown. Warmth also matters surprisingly little - you can just wrap yourself in a blanket. Morale does matter, though.
During action, morale doesn't matter much. Focus will drop really fast during combat and even 50 points of morale won't make a big difference here. What does matter is protection, storage and (to lesser extent) warmth.

End result is that advantages during combat and scavenging are balanced with tedium during crafting and resting. Balancing with tedium is pretty much the closest thing to "objectively bad" there is.

At the very least there should be a mod disabling morale penalty for filthiness. Though honestly I don't see a good justification for filthiness penalty in its current state to be enabled by default. It would be better off disabled for those who don't explicitly pick a mod that enables it or the "squeamish" trait.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Resolves #17254

Squeamish is still in mainline.

Clothing dropped by zombies is still filthy, it's just that non-squeamish characters don't care.

### CODE REVIEW

**Comment by kevingranade** [comment]
Very opposed, discussion should stay in #17254 though.

**Comment by Rivet-the-Zombie** [comment]
Same here; I really like the idea behind the FILTHY system, I just think the numbers could use some adjustment.

**Comment by John-Candlebury** [comment]
I would really appreciate a mod to disable this tag from the main game, however.

**Comment by Coolthulhu** [comment]
Will be obsoleted by #17591

**Pull request closed without merging**
