### PR TITLE
Unhardcode bio_taste_blocker

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Unhardcode bio_taste_blocker

#### Describe the solution
Added a new flag one to nullify bad tastes.

#### Describe alternatives you've considered
Adding complicated logic to maintain ability for taste based power usage.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> Removed power cost from bio_taste_blocker as it made little sense and was quite minor any way.

I find it having perfect sense. More disgusting food requires more energy to block the taste. If you think power cost is too minor, we could increase it, maybe even 100 times, not remove it altogether.

Also, it seems that `NO_GOOD_TASTE` flag isn't used by any bionic? If so, it's better to remove the check for essentially non-existent flag.

**Comment by actual-nh** [comment]
> > Removed power cost from bio_taste_blocker as it made little sense and was quite minor any way.
> 
> I find it having perfect sense. More disgusting food requires more energy to block the taste. If you think power cost is too minor, we could increase it, maybe even 100 times, not remove it altogether.

If it's suppressing the sensory nerve potentials (from tongue and, realistically, nose) then it should take the same amount - a very small amount. (And given that it's only on while eating/drinking, it would not be turned on for very long in any event - not like the leukocyte booster or similar.)

**Comment by Ramza13** [comment]
I ssume that since its interacting with nerves the amount of power would be so low that like the bio watch, bio_recycler, bio_claws/bio_toolset extend/retract it requires virtually no energy and the system can do it for free.

**Comment by actual-nh** [comment]
> I ssume that since its interacting with nerves the amount of power would be so low that like the bio watch, bio_recycler, bio_claws/bio_toolset extend/retract it requires virtually no energy and the system can do it for free.

Actually, most of those would take _more_ bionic power, reasonably speaking...

**Comment by Night-Pryanik** [comment]
It's not suppressing nerve signals. To block negative enjoyment value, it conducts a comprehensive analysis of incoming comestible, including its taste, smell, texture etc. Then it's substitutes actual data of comestible with fake data that it creates on the fly to cheat the brain. That's why it's called "taste _modifier_ bionic" despite its id of "taste blocker". It's all written in PR's description https://github.com/CleverRaven/Cataclysm-DDA/pull/28772#issuecomment-474735789
This work should cost power.

**Comment by Ramza13** [comment]
> Also, it seems that `NO_GOOD_TASTE` flag isn't used by any bionic? If so, it's better to remove the check for essentially non-existent flag.

That's correct I just added it for possible future use.  I was in the area and it was an easy add to be used for future negative mutations or faulty bionics.  I'm doing a lot of this unhardcoding work with the aim of a future larger effort to changeup current bionics and add a lot more so things like this are intended to be helpful then.

Fair enough on the cost issue I wasn't thinking about it correctly and can add a cost to it.

**Comment by Night-Pryanik** [comment]
I understand your intentions, but we have a policy not to add a code that does nothing now and will _probably_ do something in the future. You can always add a check for this flag later, when it will be used by something.

**Comment by Night-Pryanik** [comment]
Please return back power cost as it was before - based on the negative value of enjoyment.

**Comment by actual-nh** [comment]
> Please return back power cost as it was before - based on the negative value of enjoyment.

Why would the amount of processing increase with how negative it was? Indeed, detecting that something was very negative would likely take less processing than picking up a subtle difference resulting in just a -1.

**Comment by strburst** [comment]
Going with the nerve receptor idea, perhaps we could change the description to something like the following.

Example 1:

> Your taste receptors and their associated cranial nerves are altered to block any tastes that you would interpret as unpleasant.  The active bionic will nullify the taste of all comestibles with negative enjoyment value.

Example 2:

> Signals from all the cranial nerves associated with taste are intercepted, and any that might be interpreted as unpleasant are simply discarded.  The active bionic will nullify the taste of all comestibles with negative enjoyment value.

Without any mention of complicated taste analyzers/etc. it makes sense to me that the power cost would be negligible.

**Comment by Night-Pryanik** [comment]
> Why would the amount of processing increase with how negative it was?

Because bionic has to modify incoming data. Counterfeiting the taste of lard to be acceptable should be a bit harder than the taste of ammonia.

**Comment by Night-Pryanik** [comment]
> any tastes that you would interpret as unpleasant.

>Without any mention of complicated taste analyzers/etc.

How exactly the bionic should _know_ which taste you consider as unpleasant if there's no analyzers?

**Comment by actual-nh** [comment]
> > any tastes that you would interpret as unpleasant.
> 
> > Without any mention of complicated taste analyzers/etc.
> 
> How exactly the bionic should _know_ which taste you consider as unpleasant if there's no analyzers?

Pick it up from the brain, and suppress the region (probably of the insula) responsible for perceiving the taste/smell/texture as unpleasant.

**Comment by Night-Pryanik** [comment]
I grow tired of this pointless discussion. I designed this bionic to draw power based on negative enjoyment value, and I'm against changes you're making. If you want bionic that _blocks_ taste instead of modifying it, make a new one rather than changing an old one.

**Comment by actual-nh** [comment]
> I grow tired of this pointless discussion. I designed this bionic to draw power based on negative enjoyment value, and I'm against changes you're making. If you want bionic that _blocks_ taste instead of modifying it, make a new one rather than changing an old one.

OK. I think the id of the bionic may be confusing.

**Pull request closed without merging**
