### PR TITLE
[WIP] Standardized chemical powders for 1 unit = 1 gram

### PR DESCRIPTION
**Pull request by RDru**
#### Summary
```SUMMARY: Balance "Standardized chemical powders for 1 unit = 1 gram"```

#### Purpose of change
It's hard to do new or balance existing recipes if you don't know how much an unit is.

#### Describe the solution
1 unit of powder is 1 gram.
Density taken from wikipedia. Added it as a comment.
A "chunk" is 250ml volume item. Same as "metal chunk". Balanced crafting powders from chunks accordingly. Much bigger chunks felt too OP - like you find 1 and you are kinda set up for the rest of the game.
Most powders are in small bottles now - most solid state chemicals are sold like that.

#### Describe alternatives you've considered
1. Changing recipes to allow units of volume or weight in them. But that will lead to some problems, like what to do with left overs. It's also much bigger work.
2. We could have base "items". Like "1 gram of copper" and then we inherit that to make a copper wire, etc.

#### Testing
Checked weight, volume and crafting in game.

#### Additional context
If this is approved I will probably continue on balancing existing recipes to match weight/volume.

### CODE REVIEW

**Comment by tenmillimaster** [comment]
Have you considered rebasing them to be 1 mol? That'd make future recipes much easier to deal with.

**Comment by RDru** [comment]
> 
> 
> Have you considered rebasing them to be 1 mol? That'd make future recipes much easier to deal with.

No. I'm not a chemist. Had to check how to calculate that.
Won't this be too much? Like 1 mol of manganese dioxide is 87g. What if we need less than that?

**Comment by tenmillimaster** [comment]
No, the practical thing would be to pick some quantity of mols practical for the substance, e.g. 0.87 g, 1.74g, etc.

**Comment by RDru** [comment]
We either use 1 gram or 1/100 mol for unit. 
The question is do we want mol everywhere?
If we just mix 2 powders do we need moles?
For explosives we probably prefer grams.

**Comment by Tadders1488** [comment]
Don't use mol to mol.  That's beyond what most ppl are even aware of for chemistry related issues.  Grams to them will be fine.  Although, and option for mol to mol would be tits mcgee.

**Comment by cainiaowu** [comment]
using mol will simplify recipe for sure, at least that is why mol was created in the first  place.

**Comment by RDru** [comment]
Closing this one. I will make a new one with moles and other bugs.

**Pull request closed without merging**
