### PR TITLE
Add miniature railway location

### PR DESCRIPTION
**Pull request by snipercup**
#### Summary
```SUMMARY: Content "Add miniature railway location"```

#### Purpose of change
Put small railroad track in a location
more veriety in locations

#### Describe the solution
It's a miniature railway park, like the ones you can find in England. I copied the steel_mill and adjusted the contents to make it into this. It has vending machines, roofs, items and monsters but no vehicles yet.

#### Describe alternatives you've considered
Not adding it, changing the size

#### Testing
image

image

#### Additional context
N/A

### CODE REVIEW

**Comment by John-Candlebury** [comment]
If those are normal spawns it looks a little bit too dense.  Would probably be ideal with about a third of the zombies

**Comment by snipercup** [comment]
There are less zombies now:
image

**Comment by PaulBlay** [comment]
Wait, is this in or not in? I'm confused. 

If it's in, how about adding a miniature train or two (steal them from Luna Park).

**Comment by Night-Pryanik** [comment]
It's in the game for more than a year.

**Pull request merged**
