### PR TITLE
added dairy tag to several foods

### LINKED ISSUE #24097: Add missing 'Dairy' tag to several foods
Game version:
0.C-28499-g744491a

`Cheeseburger, chump cheeseburger, hamburger helper, hobo helper, clam chowder` all are prepared with milk or cheese, but are missing the `dairy` tag.

Then there is the fringe cases of `pancake, fruit pancake, chocolate pancake, waffle, fruit waffle, chocolate waffle, brioche` where the recipe calls for either milk, powdered milk, condensed milk or coconut milk.. making 1 option out of 4 non-dairy. Considering how rare coconut milk is, it might be a good idea to add the `dairy` tag to these anyway.

Of course the best option would be to have the tag be created depending on what you use in a given recipe, as there's plenty of them where you may substitute sugar with milk or vice versa. But this would be a lot of work and I just wanted to highlight some easily fixable mistakes.

### PR DESCRIPTION
**Pull request by robdit**
#### Summary
SUMMARY: Bugfixes "Adds dairy tag to several food items."

#### Purpose of change
Fixes #24097 - Added dairy tag to a bunch of food items that used dairy.

#### Describe the solution
Added dairy tag to the material section of items that were missing it in the JSON.

#### Describe alternatives you've considered
Milk tag might be suitable enough in most cases since all dairy products contain milk.

#### Additional context
New recipes might be need to address recipes that can use coconut milk as an alternative to dairy milk.

### CODE REVIEW

**Comment by Theundyingcode** [comment]
I feel that needed to list milk and dairy is redundant.  Milk should imply dairy but good job fixing this anyways.

**Comment by rdittrich97** [comment]
I was thinking the same thing but since the issue was still open I assumed it still needed to be worked on.

**Comment by AMurkin** [comment]
Two misformatted lines. Fix is in #26539.

**Comment by AMurkin** [comment]
Hmm. Looks like this was done wrong.
`Dairy` is a name for the `milk` material:
```
  {
    "type": "material",
    "ident": "milk",
    "name": "Dairy",
```

Now game does this many times at load:
```
 DEBUG    : invalid material id "dairy"
 
 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = material_type]
 FILE     : src/generic_factory.h
 LINE     : 358
```

**Comment by AMurkin** [comment]
I made #26540 to fix it.

**Pull request merged**
