### PR TITLE
Adjust format of coverage values

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
In #52060, coverage was split into several values. The UI portion was a bit of an afterthought, and based on some comments on the discord, the coverage values are kind of confusing. It's about time I addressed that.

BombasticSlacks also brought up in the comments that protection values can also be specific to a body part, so it would be handy to display this info as well.

#### Describe the solution
Reformat coverage and protection values to more clearly indicate which limbs are affected (expand to see images):

<details>
<summary><i>Jumpsuit</i></summary>

jumpsuit
</details>

<details>
<summary><i>Gas mask</i></summary>

gasmask
</details>

<details>
<summary><i>M4 with shoulder strap</i></summary>

m4
</details>

It's a bit less compact, but overall I think it's much more readable. I also changed the (fits / poor fit) row label to `"Size/Fit"`, since that's its only purpose.

#### Describe alternatives you've considered
Initially I just changed coverage values to be more descriptive. I ended up reformatting quite a bit more than I thought...

#### Testing
See screenshots above. Also see the resulting strings in `src/iteminfo_test.cpp` to get an idea of how it's been changed.

I also checked that using Item Compare highlights the proper values:
item_cmp

#### Additional context
Sorry about the confusion!

### CODE REVIEW

**Comment by bombasticSlacks** [comment]
I really like this! Don't feel obligated to include this suggestion (if you don't I'm gonna extend this a bit) but protection is at this point also per limb so though it's a lot of additional info it might be worth it to split it as:

Leg Encumbrance
Leg Coverage:
...
Leg Protection:
...

**Comment by dseguin** [comment]
Good point, I forgot about that! I'll split the values for each limb into its own section as well, so it reads better.

**Comment by dseguin** [comment]
I changed the `"Encumbrance:"` row to `"Size/Fit:"`, since it looks like all it shows is the size and fit of the clothing. I also broke out the encumbrance and protection values into their own limbs. It's quite long, so let me know if it's too much:

jumpsuit_after

**Comment by Zireael07** [comment]
This ends up looking a bit iffy for clothing that has repeated values for all limbs (e.g. wool cloak)

**Comment by dseguin** [comment]
> This ends up looking a bit iffy for clothing that has repeated values for all limbs (e.g. wool cloak)

I think you're right, but I'm not quite sure how to handle it. On one hand, the protection values can vary by bodypart, so the player should have that info. But on the other hand, the info is quite long...

I'll have to figure out some sort of compromise.

**Comment by bombasticSlacks** [comment]
so it would be a little involved and require re-organizing but if islot_armor sub_data vector is size 1 it means every bodypart shares data. So a naive test would be to check for that and that each specified limb in that entry has every sublocation involved and then compress them to a single entry with a header like "all": 


This test could get more elegant organizing parts together but I don't think much value or clarity would be given by more than the simple version.

**Pull request merged**
