### PR TITLE
Prototype fix for Perishable zone sorting issue

### PR DESCRIPTION
**Pull request by Xpyder**
#### Summary

SUMMARY: Bugfixes "Prototype fix for Perishable zone sorting issue"

#### Purpose of change

when setting zones for sorting perishable and nonperishable food/drink, foods in paper wrappers and plastic bags go into the nonperishable zone and perishable drinks are being sorted as nonperishable foods

This is a step towards trying to fix this, but I need help finishing it.

#44245

#### Describe the solution

Adds a function that searches containers for perishable items and returns a bool
Modifies item::goes_bad() to defer to this function if item->is_container()

#### Describe alternatives you've considered

There are a few alternate approaches such as searching directly from goes_bad(), but this seemed like the most logical and least disruptive to the existing code base

#### Testing

No testing yet

#### Additional context

note: THIS CODE WILL NOT WORK AS IS 
I need help finishing it by someone who has a compiler

current problems:
There's some definitions in the function header I don't understand that need to be filled out
I'm not sure what the echo in `item_contents.h` should be
I probably forgot a type declaration or two
I don't know the linting style for this project so spacing should be double checked
I don't have a compiler so I can't test
And I'm flying kind of blind so I'm not sure I declared the temporary function correctly. I forget what they're called, but it's the `[] (parameter){instructions}` part

### CODE REVIEW

**Comment by Xpyder** [comment]
@Trioct Can you take a look at this and see if fixing the prototype might be easy?

**Comment by Trioct** [comment]
I think for now you could just keep it simple because I think:tm: that something can only end up in the food/drink category if it itself is a food or drink or there is exactly one item in the container that is.
```cpp
const item_category &item::get_category_of_contents() const
{
    if( type->category_force == item_category_container && contents.num_item_stacks() == 1 ) {
        return contents.only_item().get_category_of_contents();
    } else {
        return this->get_category_shallow();
    }
}
```
Something as simple as
```diff
diff --git a/src/clzones.cpp b/src/clzones.cpp
index 26f52503ae..c35b944e4b 100644
--- a/src/clzones.cpp
+++ b/src/clzones.cpp
@@ -841,8 +841,16 @@ zone_type_id zone_manager::get_near_zone_type_for_item( const item &it,
     }
 
     if( cat.get_id() == item_category_food ) {
-        // skip food without comestible, like MREs
-        if( const item *it_food = it.get_food() ) {
+        const item *it_food;
+        // containers are only in the food category if they have 1 item in them
+        if( it.is_container() ) {
+            it_food = it.contents.only_item().get_food();
+        } else {
+            // skip food without comestible, like MREs
+            it_food = it.get_food();
+        }
+
+        if( it_food ) {
             if( it_food->get_comestible()->comesttype == "DRINK" ) {
                 if( it_food->goes_bad() && has_near( zone_type_id( "LOOT_PDRINK" ), where, range ) ) {
                     return zone_type_id( "LOOT_PDRINK" );
@@ -850,7 +858,6 @@ zone_type_id zone_manager::get_near_zone_type_for_item( const item &it,
                     return zone_type_id( "LOOT_DRINK" );
                 }
             }
-
             if( it_food->goes_bad() && has_near( zone_type_id( "LOOT_PFOOD" ), where, range ) ) {
                 return zone_type_id( "LOOT_PFOOD" );
             }
```
would probably be fine. Maybe toss in a check and debugmsg to double triple make sure it.contents.num_item_stacks() == 1. But I'm no guru here, I just write mediocre code.

**Comment by mlangsdorf** [comment]
As a rule for this project, people coding in C++ need to have a C++ compiler in order to manage a code-compile-test-debug cycle.  I'm not saying that your PR is going to get rejected, because if you make this work it will work, but it's up to you to make this work.

There are a number of free C++ compilers out there, and `doc/COMPILING` discusses how to compile the game on most of the major ones.  If nothing else, it's not that hard to set up a Linux VM on most modern hardware, and compiling under Linux is the easiest compiling.

`make astyle` from a command line, on a properly configured system, will correctly style your C++ code.

**Comment by Trioct** [comment]
Yeah, sorry, I probably should've pointed you to getting a compiler rather than throwing a diff at you for this one. There's quite a few possible solutions for this pr which requires testing, unlike the first pr I helped you with, which was a straight forward fix. You'll also get to work a lot faster since you'll get to see the compiler errors on demand.
There's also still the [discord server](https://discord.gg/jFEc7Yp) where you can ask for help on whatever you're working on, including getting a development environment set up, if you want to take that route.
Either way, I'll still try to help you with this pr.

**Comment by Xpyder** [comment]
Totally understandable, and I don't mind if someone points me to one.  I'm moderately competent with Rust so I don't have an aversion to them, I just don't really use c++

And I appreciate your help Tri.  No obligations, just if you have time your last help was... helpful ^-^

I was hoping my code was close enough to be adapted in about 5 minutes of work but I take it that's not the case this time

**Comment by Maleclypse** [comment]
@Xpyder in the contributions guide that ships with the game there are sections on multiple compiler types and instructions on how to set them up.

**Comment by Xpyder** [comment]
@Maleclypse ty, I'll try to take a look once I cycle back into the game again

Since I've been absent for a while I'll close this PR so it's not lingering.  If someone else wants to replicate and finish it before I get around to it then feel free

**Comment by Xpyder** [comment]
@Maleclypse btw, I reviewed CONTRIBUTING.md but I don't see the compiler section you mentioned (though I might have missed it) is that the right document?

**Comment by RenechCDDA** [comment]
I believe they meant `COMPILING.MD`.

Try viewing it here, on repo: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md

**Pull request closed without merging**
