### PR TITLE
Remove CBM recipes

### PR DESCRIPTION
**Pull request by kevingranade**
These should never have been added in the first place, CBMs have always been intended to be find-only.

#### Summary
SUMMARY: Content "Removed CBM crafting."

#### Purpose of change
This is a simple content removal, these crafting recipes should not exist.

#### Describe alternatives you've considered
Blacklisting the recipes is an option, but that is more work in order to preserve content I don't believe should be in the game.
Making the difficulty of crafting CMBs commensurate with what they should be is a losing proposition, they uniformly require custom miniaturized electronics and sophisticated bio-mechanical components, not to mention the cleanroom conditions this kind of thing is normally constructed in.

#### Testing
I still need to verify that a simple removal will do the right thing and not cause load errors, it may require blacklisting elsewhere.

### CODE REVIEW

**Comment by CoroNaut** [comment]
Weird.

**Comment by Night-Pryanik** [comment]
Should also remove CBM crafting subcategory?

**Comment by Mecares** [comment]
Maybe the recipes could be moved to the bright nights mod instead of removing them entirely, it would fit into the mod quite well.

**Comment by ZhilkinSerg** [comment]
There is no recipe blacklist. If player knows recipe which was deleted from game - there will be error during game load (which can be ignored), saving game and reloading it again will not show error any more.

**Comment by crowder** [comment]
It seems like the player ought to be able to somehow make Power Storage Mk II (given a higher Electronics requirement, perhaps?), at least?

**Comment by tyrael93** [comment]
What the hell

**Comment by Timonkeyn** [comment]
chaosvolt told me to go reee at you. reee

**Comment by Regilith** [comment]
Should CBM drops/spawns be upped to compensate? You have to rely completely on RNG after this change.

**Comment by kevingranade** [comment]
If they're craft only, yes some might become unobtainable, we'd look into either obsoleting or spawning them later.

> Should CBM drops/spawns be upped to compensate? 

Not reflexively, if you think theyre too rare, make an issue outlining how common they are and how common they should be.

> They were main components for the recipes, so they would be a kind of trash items now.

You should also be able to harvest electonics from them.  Even if they're trash, theres nothing wrong with trash.

**Pull request merged**
