### PR TITLE
Remove unnecessary g->m in map.cpp

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: None```

#### Purpose of change

Just a style correction

### CODE REVIEW

**Comment by jbytheway** [comment]
Are you absolutely sure these are unnecessary?  There are `map` objects other than `g->m` and their interaction with `g->m` is very subtle and prone to difficult-to-diagnose bugs.

**Comment by Fris0uman** [comment]
I've only removed `g->m`  used to call a function that is already within map.cpp. I'm pretty sure they were unnecessary.

**Comment by jbytheway** [comment]
Just because they're in `map.cpp` doesn't mean they only run on that specific `map` instance.

**Comment by Fris0uman** [comment]
Well ok, then I must admit that I don't know. It should not be to difficult to revert if you're worried it will break things

**Comment by ZhilkinSerg** [comment]
Yeah, let's revert it for now.

**Comment by jbytheway** [comment]
I hope I didn't come across too harshly here.  We do appreciate code cleanup!  I'm just a bit paranoid about `map` caching because of past bug-hunting trauma :).

**Comment by Fris0uman** [comment]
Sure no problem ^^

**Pull request merged**
