### PR TITLE
Some of the hard-coded talk topics can now be described in NPC's json.

### PR DESCRIPTION
**Pull request by ti360gh**
#### Summary
 Features "Some of the hard-coded talk topics can now be described in NPC's json."

#### Purpose of change
 Some of the talk-topics of NPCs are currently the same for all NPCs in the game.
 To better characterize NPCs, the following talk topics now can be described in json.

- TALK_FRIEND / TALK_RADIO / TALK_LEADER / TALK_STOLE_ITEM / TALK_WAKE_UP / TALK_FRIEND_GURAD
- TALK_MUG / TALK_STRANGER_AGGRESSIVE / TALK_STRANGER_SCARED / TALK_STRANGER_WARY / TALK_STRANGER_FRIENDLY / TALK_STRANGER_NEUTRAL

 This will make NPCs more unique and will help to create a kind of NPC-driven story mods or NPC heroes.

follower#1
image
follower#2
image

#### Describe the solution
 - The above hard-coded topics are now can read from npc's json.
 - The custome topic is handling with npc.chatbin.<same_name_of_topic> in game.
 - Hard-corded topic replaced to chatbin.<same_name_of_topic>.
 - save/load that topic names.

The following topics seems system messages, so I don't touch it.

 - TALK_REBOOT / TALK_SEDATED 
 
The mission dialog also a "common", but this can be avoided by creating a dialog chain. 

#### Describe alternatives you've considered
 Nothing.
 I wanted to replace the hard-coded values with JSON.

#### Testing
- Setup
I created the scenario with 2 NPC instances.
One of NPC have all customized topics in json.
The other one have nothing above fields in json.

- Testing
 All topic was displayed by in-game debugging or save editing.
  - TALK_FRIEND
  Talk to follower.
  Assign NPCs as camp worker/re-join to follower and talk.
  - TALK_FRIEND_GUARD
    Assign NPCs as camp worker and talk.
  - TALK_WAKE_UP
  Set the sleep effect in the In-game debug menu and talk to the NPCs that is sleeping.
  - TALK_RADIO
  Assign NPCs as camp worker with 2-way radios. leave camp and talk them using "#" menu.
  - TALK_LEADER / TALK_STOLEN_ITEM
  Set NPC `attitude` with 5/18 in json, start a game and ~~save/exit~~ talk them.
  - TALK_MUG / TALK_STRANGER_ stuff.
  Set NPC `chat` with `TALK_NONE` in json, start a game and save/exit.  Editing save data with NPCs op_of_u and personality to match above condition, then start the game and talk.
  Attack the follower, save it, and make sure that the "first_topic" value in the save data is chatbin.talk_stranger_neutral".

#### Additional context
Todo: Make same changes to talk-tag's snippet in next PR.

### CODE REVIEW

**Comment by WeisserRitter** [comment]
How would one go about specifying that this is a character-specific talk topic, rather than just being an override of the original talk?  Because I wrote a personal NPC mod that overrides said topic but comes with obvious issues in that you need one event chain to hold all the conditions for flavor lines for all NPCs, breaking compatibility.

**Comment by ti360gh** [comment]
> How would one go about specifying that this is a character-specific talk topic, rather than just being an override of the original talk? Because I wrote a personal NPC mod that overrides said topic but comes with obvious issues in that you need one event chain to hold all the conditions for flavor lines for all NPCs, breaking compatibility.

I didn't think that point.
Would you explain more detail about the breaking compatibility?
If we need to keep the conditions for all NPCs, we can use `u_add_var` with `speaker_effect`.

This PR does not change any existing NPCs, so I don't think it will affect the compatibility.

**Comment by WeisserRitter** [comment]
> > How would one go about specifying that this is a character-specific talk topic, rather than just being an override of the original talk? Because I wrote a personal NPC mod that overrides said topic but comes with obvious issues in that you need one event chain to hold all the conditions for flavor lines for all NPCs, breaking compatibility.
> 
> I didn't think that point.
> Would you explain more detail about the breaking compatibility?
> If we need to keep the conditions for all NPCs, we can use `u_add_var` with `speaker_effect`.
> 
> This PR does not change any existing NPCs, so I don't think it will affect the compatibility.

Currently you can override the talk topics you mentioned in a mod through json, but by doing so you have to modify the conditions in which the conversation plays out.

Example:
`[
	{
	"id": [ "TALK_FRIEND", "TALK_GIVE_ITEM", "TALK_USE_ITEM", "TALK_RADIO" ],
    "type": "talk_topic",
	"dynamic_line": {
		"npc_has_trait" : "NPC1",
		"yes" : "Yes, what do you want?",
		"no": { "npc_has_trait" : "NPC2",
		        "yes" : "Hallo?",
		        "no": { "has_reason": { "use_reason": true }, "no": "What is it, friend?" } 
			}
		}
	}
]`

This is bad because there's no compatibility, this isn't open to extension but rather a strict override that ensures any previous conditional checks for the dynamic line of greeting you are changed.

I assume that your solution provides a way to avoid doing this by having the talk_topic override be specific to an NPC class, but how would you go about writing the json for it?

**Comment by ti360gh** [comment]
@WeisserRitter 
Yeah, we can override the talk topic but as you said, that is not so good.
And we can't replace the whole responses, we can only add responses or display only one response with "swith". (afaik)

If this PR has been merged, we can define like:
```json
{
  "type": "npc",
  "id": "examplicious",
  "class": "NC_EXAMPLE",
  "attitude": 0,
  "mission": 7,
  "chat": "TALK_EXAMPLE",
  "talk_friend": "TALK_FRIEND_NPC1",
  "talk_radio": "TALK_RADIO_NPC1",
  "faction": "no_faction"
},
{
  "id": [ "TALK_FRIEND_NPC1",  "TALK_RADIO_NPC1" ],
  "type": "talk_topic",
  "dynamic_line": {
    "is_by_radio": "NPC1 radio message",
    "no": {
      "has_reason": { "use_reason": true },
      "no": "NPC1 friend message"
    }
  },
  "responses": [
    { "text": "Specific response for NPC1", "topic": "TALK_TOPIC_EXAMPLE" }
  ]
}
```
Since the "experimental" NPC instance has two specific talk topic names `talk_friend` and `talk_radio` defined, it will override the default `TALK_FRIEND` and `TALK_RADIO`.
For other topics like `TALK_WAKE_UP` and `TALK_STOLE_ITEM`, the default topics are used.

The same goes for other NPCs, if there is no specific topic definition in json, the default topics will be used.

I wrote it in [NPCs.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/8e3ca4ecf8f135c3ed2ae67f5e195a08c324be02/doc/NPCs.md).

**Comment by WeisserRitter** [comment]
That's an effective solution! Though it does somewhat feel like putting on a band-aid, since you have to specify the exact name of the talk topic you want to override in the JSON.

**Comment by ti360gh** [comment]
> That's an effective solution! Though it does somewhat feel like putting on a band-aid, since you have to specify the exact name of the talk topic you want to override in the JSON.

Thanks! I know why you feel that way, but I don't think it matters because all json parameter names must be exact correctly.

**Comment by I-am-Erk** [comment]
I was trying hard to figure out how to do this, and found out that you did it almost exactly two years ago, in exactly the way I was about to ask it be implemented. Thanks for this, sorry it took me so long to put it to good use.

**Pull request merged**
