### PR TITLE
Add logic & mods to optionally change proficiency penalty behavior

### PR DESCRIPTION
**Pull request by DoctorVanGogh**
# Summary

SUMMARY: Balance "Add mods to remove missing crafting proficiency time penalty stacking or completely disable penalties."

# Purpose of change

I think the "new" proficiency time penalties are too harsh. Instead of _just_ screaming at ~windmills~ @I-am-Erk, this change adds the infrastructure to allow player choice in the behavior for crafting penalties.
Specifically it offers 2 mods similar to the "no npc food" mod:
* One completely disables the time penalties for missing proficiencies.
* The other changes the stacking multiplier of multiple penalties to a simple addition of the penalties.

# Describe the solution

Added some minor code to recipes to check for a "new" external option `PROFICIENCY_PENALTY`. Added two simple mods which set that option to different values.
Depending on the option, the crafting system either "pretends" the player knows all proficiencies as far as crafting times are concerned, or it changes the penalty aggregation logic from multiplicative to additive. Added some special handling to UI to make mere addition of penalties more clear ( `4x` becomes `+300%`).
Also fixed a minor unnecessary code duplication along the way.

# Describe alternatives you've considered

Thinking *really* hard at @I-am-Erk to just nerf the existing penalties. Surprisingly I seem to be having very limited success with that. So this PR adds some options for players.

# Testing

Created a world, added all recipes to character, game them some skills.
Checked recipe list.

Edited mod variants into world, checked recipes. Looked good.

# Additional context
## Screenshots
(all from the same character, same world)
### Default:
image
### "No Stacking" variant:
image
### "No Penalties" variant:
image

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
Revert mods are not acceptable for the repo. You have only stated that it is harsh, not that proficiencies don't work.
## What is necessary for a mod to be included in the repository?
Furthermore, there are additional criteria:
*  *  Mods which do not qualify as curated experiences: Grab bag mods with no defined purpose (i.e. adding a bunch of random guns), **_"settings" mods that just turn off a possibly undesired but working feature (acid ants)_**.

~doc/IN_REPO_MODS.md

**Comment by kevingranade** [comment]
Not interested, you haven't made a case for these being excessive, and I'm getting less and less interested over time in supporting arbitrary configuration of game features

**Comment by I-am-Erk** [comment]
I was under the impression that we were having a discussion, one in which I had in fact entertained alternatives and run them through spreadsheets and things. This was an unimpressive passive-agressive response. I am much less likely to give you any credence in the future.

**Comment by DoctorVanGogh** [comment]
Well Kevin, I hear you loud and clear. 

I especially want to thank you for your _good faith_ in slamming the door on this PR after not even 30 minutes. 
I would have gladly made a case why an *option* to sidestep or alter the system seems warranted to me - even though this might duplicate some points argued elsewhere - but your _lack of interest_ is quite explicit. 
As for me adding the mods themselves _here_ - not the mere necessary code changes - I simply went with the `no_npc_food` mod as a template. Thank you for your _kindness_ in pointing out my overreach.

So I will just leave it at some impressions I had about this project:

This game offers options. You can play with zombies, or without. You can have zombie evolution or not. You can have seasons or not. You can have npc needs or not. You can ride into battle on a horse wearing Japanese armor or with a laser turret equipped death mobile. All from the core distribution. 
Fricken hell - someone added refrigerated tanks so they can have milk tankers so they can have a working dairy farm in game.

To me that suggested an _encouragement_ of configurability. Well... it seems this has become more of a burden than a design principle.

**Comment by I-am-Erk** [comment]
You seem shocked that your PR, with sentences like 
> Instead of just screaming at ~~windmills~~ @I-am-Erk
or
> Thinking really hard at @I-am-Erk to just nerf the existing penalties. Surprisingly I seem to be having very limited success with that.
is not being read in good faith. Can you think of any reason we might not take a PR like this in good faith?

Seriously man, I spent a reasonable amount of my presently very limited free time yesterday sketching out a few different ideas, and in fact nearly made some changes until I found a fatal flaw. I did that because I was *listening to you*. You came back with this and are now whining because you're not getting special treatment with that kind of behaviour.

**Comment by anothersimulacrum** [comment]
> You can ride into battle on a horse wearing Japanese armor or with a laser turret equipped death mobile. All from the core distribution.
> Fricken hell - someone added refrigerated tanks so they can have milk tankers so they can have a working dairy farm in game.

These have nothing to do with enabling or disabling core features, and are things you could reasonably do in the setting.

**Comment by Night-Pryanik** [comment]
@DoctorVanGogh if you still interested in this work, redo it in a slightly different matter. 
First, create an external option in game_balance.json with default set to current behavior. 
Second, remove mods from your changes. Those who want to use mods, have to create one by themselves, based on your changes.
And third, try to avoid using emotionally-colored sentences in PRs.

**Comment by mikt4743thesecond** [comment]
Hey, could you send the files for the mods here, so those interested could have them?

**Comment by anothersimulacrum** [comment]
The patch is available by add `.patch` to the end of the URL. [Here it is for this one](https://patch-diff.githubusercontent.com/raw/CleverRaven/Cataclysm-DDA/pull/44302.patch).

**Pull request closed without merging**
