### PR TITLE
Allow looking up/down without changing abs_sub.z

### LINKED ISSUE #6818: 3-dimensional Z-level support, Core Part 1: extend map class to 3D [$330]
Master Ticket #6822

This will be a "bounty issue" for the development of z-line track development.

This has following requirements:
*Expand the "map" object to encompass alternate z-levels*

CiB's estimate of required task components:
- Implement a "SEEZ", that tells us how far up and down the player can look at most(and by extension, how many of the up/down slices should be loaded into map)
- Extend map to store SEEZ times more submaps
- transparency_cache etc. can stay the same for now - visibility calculations will ONLY happen on current z-level
- implement special submap type that is homogeneously one terrain(e.g. only air, or only rock)
- rewrite anything that changes the player's z-level to do map::shift with the new z-level instead
- optional: don't shift the map on every z-level, shift it only on every N z-levels
- expand creature to have zpos()
- expand the creature tracker/mon_at to be fully 3d
- expand the stored traps to be fully 3d
- expand map::i_at, ter_at, furn_at, get_ter, tr_at, etc etc to be fully 3d

<bountysource-plugin>
---
There is a **[$330 open bounty](https://www.bountysource.com/issues/1537787-3-dimensional-z-level-support-core-part-1-extend-map-class-to-3d-330?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Allows viewing z-levels other than the current one without even temporarily changing the abs_sub.z (the "global" z-level). This is achieved by starting the game in a z-level world, starting debug mode, looking ('x') and using up/down stairs command.

Also rewrote the outside cache building function to address submaps rather than invoking `has_flag` on every single point of the map.

Every point of #6818 is fulfilled now. The `map` class is now 3D. Not all usages of it are 3D, but issue is about the map. Not all caches are perfect (lightmap isn't recalculated properly), but this is explicitly not a part of the issue.

Unless there is something I interpreted differently from the intent:
Closes #6818

### CODE REVIEW

**Comment by Zireael07** [comment]
Woot! You're brilliant, @Coolthulhu!

**Comment by BevapDin** [comment]
There seems to be a bug (unrelated to this PR, but related to z-levels) when vertical moving:

When z-levels are enabled (`m.has_zlevels()` is true), the *main* map is vertically shifted during the vertical movement (in `game::vertical_move`). The function later handles monsters, moving those that can reach your character into the monstairs list or despawn them otherwise. However, this uses the *shifted* map, that means the `can_reach` code looks at the terrain of the *new* z-level, not at the z-level the monster is originally on.

This can easily seen by this: jump to fields, make a down stair (at z=0), make an up stair below it (at z=-1), jump to that up stair. Add a floor field nearby (still z=-1), but make it completely surrounded by rock, place a zombie there. That zombie can not move anywhere, so it should not be able to reach the stairs, right? However, if you move up, the zombie awaits you.

```
Z=-1
### 
#.#
###
#<#
###
```
(player character at the stairs, zombie at the floor field, # is solid rock, z=0 is all free field and grass and a single down stairs above the up stair)

**Comment by BevapDin** [comment]
Another thing, this is related: when the monsters despawn via `game::despawn_monster`, via `game::shift_monsters(0,0,movez)`, the go into the overmap, this uses the *current* z-level (g->get_levz()), which is already shifted. This means the monster is despawned into the z-level that the character has just moved onto. As a result, the monster is immediately re-spawned.

**Comment by BevapDin** [comment]
You probably want to call `build_seen_cache` with the z-level that is currently viewed at https://github.com/CleverRaven/Cataclysm-DDA/pull/12072/files#diff-ab005ad9757130721ffb66a09833090aR6459

**Comment by Coolthulhu** [comment]
Changed seen cache to be built on current z-level.

It has minor errors due to lightmap being built only on the abs_sub.z z-level, but fixing that is out of the scope of this PR (and first part of the z-level issue).

**Comment by BevapDin** [comment]
Some minor issues:

- When choosing the target for short range teleport, one can now choose a different z-level, but the character is only teleported on the current z-level. This is a bit confusing. I expect this to happen with other code that uses the return value of `game::look_around`.

- When switching viewed z-level while driving, the game shows a debug message that `game::draw_veh_dir_indicator` can't find the vehicle (because it's on a different z-level, probably needs to call the 3D-version of `veh_at`).

- During creation of the lightmap (`generate_lightmap`), there is one call to `map::get_vehicles` without parameters, it returns all the vehicles (on any z-level) and applies their light. Having a vehicle with active lights illuminates the below ground just fine.

- When there is a sound marker somewhere, it is not drawn directly after changing the z-levels, but later when moving horizontally (also sound markers are not 3D at all).

- Minor flickering, probably caused by calling `refresh_all`, which calls `draw`, which calls `draw_ter` (on the players z-level, not the one I view currently), followed by `draw_ter( lp, true );` which draw the terrain at the correct (currently viewed) z-level.

- cata_tiles does not draw the cursor if the cursor is centered on the player character (ignoring the view offset as well!), this ignores z-levels (does not draw the cursor when it's directly below/above the character).

Once the z-level stuff is complete, the cache updates will be gone and I expect the code blocks for vertical movement of the cursor and for horizontal movement of the cursor to be merged into one and that would get rid of the flickering and draw the footsteps and most of the other issues.

Beside those minor issues (which don't actually matter much because it's a debug feature, requiring debug mode), this looks good, doesn't crash and is quite useful.

**Pull request merged**
