### PR TITLE
Density cleanup + minor stuff

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Maintenance?
#### Describe the solution
Fixed the density of a bunch of items
Added `drug_filler` material for the purpose of different pills, to avoid adding dozens of materials that would do nothing, effectively; Maybe we should make material variants?
Added more `test_material` to test items 
Removed `testcomest`, whatever it was, since it doesn't exist anywhere in the game
Obsoleted and migrated two artifact auras in favor of effects that do the same
Obsoleted and migrated `recipe_mil_augs` since it doesn't fit current lore
Changed description of recipe_augs a bit, bring and old description for aftershock mod

#### Additional context
Oh hey, maybe i should migrate `recipe_mil_augs` to the aftershock also? @John-Candlebury

### CODE REVIEW

**Comment by Karol1223** [comment]
Why is homeopathic pill material sugar? And why did you remove the hydrocarbons material?

**Comment by GuardianDll** [comment]
> Why is homeopathic pill material sugar?

What do you think they are made of?

> Why is homeopathic pill material sugar? And why did you remove the hydrocarbons material?

Oops

**Comment by NetSysFire** [comment]
> Why is homeopathic pill material sugar?

To cite https://en.wikipedia.org/wiki/Homeopathy#Preparation:

> Homeopathic pills are made from an inert substance (often sugars, typically lactose), upon which a drop of liquid homeopathic preparation is placed and allowed to evaporate.

From personal experience I know that homeopathic pills, called globuli in germany, are mostly sugar.

**Comment by Karol1223** [comment]
For the record, the question about homeopathic pills wasn't because I have any idea what they are - it was pointing it out in case there was a copy-paste error along the way. Tbh I'd add a json comment explaining that there, because it can be pretty confusing to come across.

**Comment by John-Candlebury** [comment]
>Oh hey, maybe i should migrate recipe_mil_augs to the aftershock also? @John-Candlebury

No not really, moving that one to aftershock requires actually putting thought on what should be craftable and when.

**Comment by ehughsbaird** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/70211 will enable having the material in the test data mod

**Pull request merged**
