### PR TITLE
Rationalise ammo.json [RDY]

### PR DESCRIPTION
**Pull request by mugling**
~~Marked [WIP] as will need rebasing once #15072 is merged~~

This PR is an incidental refactor split out from larger work to extract ammo data for use when updating the wiki.

It normalizes `ammo.json` as follows:
- `damage`, `recoil`, `range` and `dispersion` now have zero as an unspecified default
- Lots of ammo had a variety of `to_hit` values even when it shouldn't
- Almost all ammo (except rebar etc) shouldn't specify `bashing`
- Why was soap damaging?
- Change gun ammo to have `volume 1` having set an appropriate stack size

@illi-kun - apologies, I'm not trying to step on your toes.

### CODE REVIEW

**Comment by illi-kun** [comment]
That's totally fine, no need to apologize for such great things you're doing.

**Comment by Rivet-the-Zombie** [comment]
Mind the throwing weapons.

**Comment by mugling** [comment]
Good point. I don't think I've affected any so far though?

**Comment by Rivet-the-Zombie** [comment]
Haven't had the time to check yet.

**Comment by mugling** [comment]
Good to go

**Pull request merged**
