### PR TITLE
Rework on_death effect for slimes

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Bugfixes "Rework on_death effect for slimes"

#### Purpose of change
As pointed out in #53565 the fix provided didn't work in all scenarios.

Slimes had a fixed on_death effect and bigger slimes were always splitting into two smaller ones with full mass. The combined mass of the newly spawned slimes was (in most cases) higher than the mass of the donating (dead) slime. This extra mass in turn helped the slimes grow into bigger versions and split into new smaller slimes. This loop made them replicate indefinitely unless you focused on killing the smaller ones (which don't spawn new slimes on death).

This problem was observed and documented by @Balthasar-eu in a test where a skitterbot kept killing slimes over and over creating new ones in the process, until the whole area was filled by slimes.

#### Describe the solution
The generic approach with summon spells isn't good enough for the splitting mechanic so I created a new spell for the slime on_death effect specifically.

This new effect tries to create new slimes (of random sizes and reduced mass) up to the total mass of the dead slime, avoiding the main issue. If there is no room to place new slimes around, the remaining mass is transferred to a nearby slime as if it was absorbed. I added a failsafe to this new mechanic so that some of the mass is lost on transfer. This should prevent infinite loops where dead slimes keep transferring all their mass to other slimes and/or creating medium+ sized slimes that feed each other without a chance to kill the smaller ones to finally get rid of them.

The new effect is limited to a size 1 radius which prevents slimes from being created on the other side of walls. The radius can be increased to 2 if a check for passability/reachability between the source and target tile is added, but I went with the radius 1 approach. It's an easy change though if anyone wants to implement it at some point.

I also added a new behavior so very small slimes have a chance to fully merge with a nearby slime. Otherwise at some point most slimes became too small to donate mass or split.

#### Describe alternatives you've considered
None.

#### Testing

SlimeVsSkitterbot

SlimeVsSkitterbot2

SlimeVsSkitterbot3

### CODE REVIEW

**Comment by KorGgenT** [comment]
what happens when a non slime casts this spell effect? npc? avatar?

**Comment by GoLoT** [comment]
It should work the same. Basically it uses the base speed of the creature to determine the total mass to spawn (which is how slimes track mass), then it checks if it's a brain slime to double the mass. This is because brain slimes have low base speed so they need a boost.

The rest is code adapted from the formblob attack that spawns slimes up to the total mass calculated previously.

I haven't done any tests but I'll quickly set one up and let you know.

**Comment by GoLoT** [comment]
Retested after the changes: Same results as shown in the gifs.

**Comment by KorGgenT** [comment]
i guess i failed to get across my meaning in my previous comment?
in the spell effect, you've got all sentinel values, and are not utilizing the spell data at all. additionally, you are checking versus a specific monster id; so the effect can only ever be used for a single thing. just briefly glancing over it, you can add aoe() in the spot where you place the monster, and i'm sure there's a few more options to add versatility.

for spell effects, versatility is king. the goal is to give the people writing json a tool they can use in at least more than one situation, and perhaps find new ways to combine the numbers to make something interesting and new.

**Comment by GoLoT** [comment]
Oh, I see.

This is a very specific use-case that doesn't generalize well. The AoE has to be restricted to avoid spawning monsters through walls. If you meant the visual effect, I can add the `spell_effect_area()` call for the explosion effect, but the effective area will still be restricted to 3x3 to prevent issues.  The monster IDs have to stay hardcoded to choose between the 3 slime types randomly. There isn't much room for customization.

This is one of those cases where the effect should probably stay hardcoded for the most part and not reused.

**Comment by Photoloss** [comment]
Using speed as a proxy for mass is really janky but at the very least this could be re-used for something like a fudge blob in MySweetCataclysm or an "ectoplasm slime" which *can* spawn through walls in magic mods so adding proper JSON customisation does have some benefit. No idea how hard it is to add the corresponding monster type and species properties though.

**Comment by GoLoT** [comment]
The hardcoded upgrade path for blobs means that monster IDs have to be hardcoded. If it's used for other monsters it'd have to be hardcoded for those monsters also. The way around it would be to add support for multiple monster IDs to summon (which goes out of the scope of this PR), sorting them by base speed and choosing in descending order, which I really CBA to do right now. Or simplifying the effect to always summon 2 monsters of the same kind (allowing a single custom monster_id to be specified) with half the available mass each, which is also a valid approach and more similar to the original one, but I don't like slimes always splitting in 2. I think splitting into multiple blobs of different sizes looks better.

For `spell_effect_area()` (explosions, projectile support and so on): it needs a whitelist of monster_ids to target anything other than the ground. In this case the list can be empty so it targets open tiles only, but then the hack to transfer the remaining mass to nearby slimes (if there is no room to spawn new ones) stops working. Which means the spell needs a list of monster_ids that it can transfer this mass to (basically all the slime monsters defined on each spell), or a way to define monster species as a target (out of the scope of the PR). The speed being used to track mass is hardcoded for slimes only (AFAIK) so if someone ever needs to use this spell effect for a different kind of monster they would have to hardcode it too and do more code changes than just this, so it really doesn't make sense to waste time on this.

Again, this is an effect tailored for a specific monster and all this work just to make it slightly more JSON-friendly, for a use-case that might never happen and will still more than likely require code edits with more hardcoded stuff, is not really adding much. If someone decides to implement new slime types and this doesn't work for their use-case they can always tailor it to their needs or use the basic summon effect. If they want split mechanics for other kind of monsters they can use the basic summon spell like with the half-worm.

I'll leave this as a draft for now and if anyone wants to implement one of the suggested approaches I can close this PR in favor of that one.

**Comment by KorGgenT** [comment]
you had convinced me; feel free to finish up this PR.

**Comment by GoLoT** [comment]
I don't see harm in adding radius support and it's a quick change, so I added it. Same for the duration of the spawned slimes.

**Comment by Psithief** [comment]
The slimes have speeds {50, 70, 90}

A slime with "mass"(speed) 70 will split into two small slimes of mass 35, but a small slime with mass 35 will always spawn another slime with mass 35 when it dies, because a small slime will always be spawned if the dying slime has a mass of 25 or more.

Is there something I'm missing that prevents this?

**Comment by Psithief** [comment]
Nevermind, small slimes don't split!

**Pull request merged**
