### PR TITLE
Plant product adjustment

### PR DESCRIPTION
**Pull request by NotFuji**
#### Summary
```SUMMARY: Content "Adjusts plant material yields"```

#### Purpose of change
For the number of withered plants and straw piles required for various recipes yields from plants are unusably and unrealistically low.

#### Describe the solution
Yields adjusted:
 - Trees: Added 1 - 200 withered plants
 - Tree trunk: Added 1 - 100 withered plants
 - Shrubs: Changed from 1 - 2 to 1 - 50 withered plants
 - Underbrush: Changed from 1 - 2 to 1 - 10 withered plants
 - Fruit bushes: Changed from 1 - 2 to 1 - (10 - 50 depending on species)

Increased yield chance from 50% to 80% for all

Added straw pile byproducts to cut grass
Replaced scythe and sickle requirement for cutting grass with CUT 1

Lowered withered plant volume from 250ml to 10ml, same as small string

#### Additional context
Data based on: 
[https://digitalcommons.library.umaine.edu/cgi/viewcontent.cgi?article=1019&context=aes_miscreports](https://digitalcommons.library.umaine.edu/cgi/viewcontent.cgi?article=1019&context=aes_miscreports)

### CODE REVIEW

**Comment by kevingranade** [comment]
Where are the tree yields coming from?
Please be more specific about how you converted from your source to yield amounts of various plants.

**Comment by NotFuji** [comment]
I took the branch weight of a couple trees same as the bushes, saw the number was stupidly massive, and did some assumption magic (branches too big, branches too damaged) and gameplay considerations (does the player really *need or want* 5000 material from a tree, and settled on ~200 per tree

It's the same for all trees, since cutting them down, data on what kind of tree it was gets lost

Birch for example: ~250kg of branches, makes 12500 material.  That's a bad number so lets assume 10% of that is usable, too big, too broken, etc, 1250.  Assume a 4th of that is destroyed by the tree falling or whatever, ~300.  That number seems manageable for gameplay, so add some to get outlier variation, ~400.  Trees drop 4 trunks, so 1-100 per trunk.

**Comment by mlangsdorf** [comment]
This will certainly make no-city, innawoods cold starts a lot easier.

**Comment by kevingranade** [comment]
Ok so in short, you're saying branches = withered plants.
They aren't the same thing.
I think you want to make rope or twine from branches (woody plant material).  If so thats a totally different process than splitting and braiding soft plant fiber (what we're calling withered plants).

I still need your rationale that supports the yields for bushes and underbrush.

**Comment by NotFuji** [comment]
While I'd agree at face value, the way the game uses withered plants is in line with being small supple branches, regardless of what they were supposed to be originally.  Also, you might be forgetting that tree branches *do* contain soft plant fibers.

Actual natural cordage like you're imagining is already relegated to "plant fiber" which can be made into industrial quality strings and ropes (which is realistic, well made natural cordage is virtually identical to store bought twine), rather than the "makeshift ropes" that withered plants are used for.

I got the shrub and underbrush yields the exact same way as above, except using the smallest diameter trees.  Shrubs, after all, are just small trees. (mostly, there are non-tree species shrubs too).  Underbrush uses the absolute smallest diameter tree as a base.

**Comment by kevingranade** [comment]
What part of *withered* is not clear?  This item represents dried and partially-rotted plant stalks or leaves that are suitable for stripping into loose plant fibre.  Freshly harvested tree branches bear no resemblance to that.

As your justification for the bush yields is also tenuous to nonexistent, I'm just going to close this.

**Comment by NotFuji** [comment]
Except dried stalks and leaves are completely unsuitable for making rope.  Not bad for making rope, it just doesn't work.

I can rename the item if you want.  Being leaves and such is not reflected by its implementation in the game whatsoever.

And why are the bush yields tenuous?  I explained exactly how I got it, it's based on a chart of real data, *and even undercuts it significantly*.

**Comment by I-am-Erk** [comment]
Actually Kevin, while I agree that there are issues with this pr, I gotta say you're way off on the last bit. Rotted leaves are not used for cordage. Green wood and cambion is. 

http://www.primitiveways.com/cordage_in_North_America.html

I don't think bumping withered plant yields up to hundreds is a good first step to fixing rope making, but it's going to need to happen at some point. In real life plant cordage is abundant.

**Pull request closed without merging**
