### PR TITLE
Add toxic waste map extra

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
Content "Add toxic waste map extra"

#### Purpose of change

Adds a toxic waste map extra. This is supposed to be a relatively minor challenge for the player and is mostly there for ambience since most of the world is currently lush forest and yet an apocalypse is happening. This should also provide some minor lore, since slime globs have a chance of being spawned, indicating that scientists might have deposed of this biologically-hazardous material irresponsibly, making the situation even worse. The only places with nuclear reactors are, as far as I know, military buildings (the missile silo?) and labs, contributing more implicit lore regarding the occurance of plutonium slurry. It should indicate that the government and the scientists were not very well prepared and not aware of what has going on, showing it was haphazardly run since their waste was disposed that way.

#### Describe the solution

Just adds a new map extra. It uses the `toxic_waste` group, which is also used in "proper" toxic waste dumps.

#### Describe alternatives you've considered

This can in theory be merged as is but should not since it is still WIP and therefore a bit bland.

**Things I need help with**:
- Having a chance of adding a field. I want to add a chance of a deep pit with a toxic gas vent (`fd_vent`) being spawned on top, but apparently you can not make fields randomly appear? As in a say 40% chance in a `mapping` block.
- Randomly adding radiation. It seems toxic waste dumps (the normal ones) randomly have radiation or not and I can not find a way to reproduce that behavior without hardcoding it in C++.

**Stuff I am still considering** (a ? means I am not too sure yet):
- Adding some low-level relevant monsters:
  - Sewer rats
  - Slimes
  - Hazmat zombies?
  - Adding dead mutant corpses inside of the barrel or a body bag
  - Adding tainted flesh, bones and alien fungus chunks to the garbage pile
- Adding a version with goo pits and guaranteed slime?
- Adding a fenced in variation of this map extra?

#### Testing

Applied the changes locally without any errors. Also see below.

#### Additional context

Manually spawned a bunch of the map extra next to each other:

image

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I've thought about the problem of having a percentage chance of spawning a collection of things (terrain + furniture + items, and probably also a field), which is problematic as percentages are applied separately to each type of things. However, I think it would be possible to create such collections as single tile "chunks", which I think can be placed with a percentage chance.

**Comment by Night-Pryanik** [comment]
> Having a chance of adding a field. I want to add a chance of a deep pit with a toxic gas vent (fd_vent) being spawned on top, but apparently you can not make fields randomly appear? As in a say 40% chance in a mapping block.

AFAIK there's no way to directly set a chance for spawning a field, so you could use nested chunks for that.
First you add a small nested chunk which only spawning a field. For example, this chunk spawns a field of toxic gas vent

```
{
    "type": "mapgen",
    "method": "json",
    "nested_mapgen_id": "toxic_gas_vent",
    "object": { "mapgensize": [ 1, 1 ], "place_fields": [ { "field": "fd_vent", "x": 0, "y": 0, "intensity": 1, "age": 10 } ] }
}
```

Then you set a chance for this particular chunk to spawn. For example, tiles with `a` symbol will have a 40% chance to spawn a field of toxic gas vent.
```
"nested": { "a": { "chunks": [ [ "toxic_gas_vent", 40 ], [ "null", 60 ] ] } }
```

> Randomly adding radiation. It seems toxic waste dumps (the normal ones) randomly have radiation or not and I can not find a way to reproduce that behavior without hardcoding it in C++.

I'm not sure what you meant here. You meant some toxic waste dumps (as locations, in whole) have radiation, and some have not? Or did you meant that some tiles in toxic waste dumps (one particular location) have radiation, and some have not?

**Comment by NetSysFire** [comment]
>Then you set a chance for this particular chunk to spawn. For example, tiles with a symbol will have a 40% chance to spawn a field of toxic gas vent.

Great! Thanks for the solution. I shall experiment with this.

>I'm not sure what you meant here. You meant some toxic waste dumps (as locations, in whole) have radiation, and some have not? Or did you meant that some tiles in toxic waste dumps (one particular location) have radiation, and some have not?

I meant that toxic waste dumps as whole either have radiation or not. In earlier versions, in 0.E for example but I can not reproduce this behavior in experimental, not every toxic waste dump was radioactive.
Would be nice to only make the dump radioactive when plutonium slurry was spawned.

**Comment by PatrikLundell** [comment]
A very crude way to do that would be to have two versions of it where the radioactive one uses the same blueprints as the "normal" one and then adds random spawns of plutonium slurry on top of that, plus making it radioactive (but I don't know how to do that).
An alternative would be to have the radioactive version use everything but the loot table, which would be different, and so would reside in a chunk (or set of chunks) that wouldn't be reused. That would ensure you wouldn't get multiple barrels on the same time if you were unlucky, unless the two loot blueprints were designed not to overlap.

**Comment by NetSysFire** [comment]
Looking at the other stuff, you have `place_corpses`, but it appears you can not place corpses into containers such as body bags according to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md

**Comment by PatrikLundell** [comment]
Have you looked at the weirdo logic used for harvestable plants (e.g. farm fields of corn)? There a weird generic "container" is used to hold the produce. Could a similar approach work here?

**Comment by NetSysFire** [comment]
I have not. I will take a look at this. Thanks for the tip. Meanwhile, it appears the gas vent spawn is working properly, but the toxic gas spawn is not (note the absence of the actual toxic gas, manually placing the field via the debug map editor has the same effect).

image


The only other place a toxic gas vent is spawned is in the mines (and in labs) and it is spawned via C++.

https://github.com/CleverRaven/Cataclysm-DDA/blob/94dfb9464708f3cb03ed8681562c2f4f7e946455/src/mapgen.cpp#L5940-L5950

This does not look like it is spawning the toxic gas fields, too so I wonder how the actual toxic gas is produced here.

**Comment by NetSysFire** [comment]
Alright. I think I figured out the toxic gas vent situation. When I spawn the map extra via the debug, it will not start emitting gas. But if I teleport somewhere and back to the map extra again, it suddenly starts working. This may be a bug, but should not occur in normal gameplay where you do not teleport around.

This PR is almost ready to be merged. I need to decide on what to do with radiation and the corpses.

**Comment by NetSysFire** [comment]
I've looked into the matter with spawning corpses inside containers and unfortunately this is not possible. You can have "pseudo-corpses" which are in a couple of itemgroups but `place_corpses` placing genuine corpses into a container will not work. You can also not determine there freshness unfortunately.

**Comment by NetSysFire** [comment]
I did not have the time and motivation to work on this in the past couple of months but now I have both again.

Meanwhile I did some research on hazardous and toxic waste and therefore added a lot of spilled chemicals and even a fence which appears randomly. The latter is a pretty elegant solution in my opinion and I will probably also move the radioactive stuff into that, so if the fence appears it is radioactive. I am still open to changing that and in fact I am thinking of just placing the fence anyways because why not?

The spilled chemicals are currently cosmetic only since you can not re-use them. I am also thinking of placing small amounts into the barrels but still need to decide what chemicals to use for that.

I would love to use an itemgroup for `liquids` but I am unsure if it would even work. It would certainly be more elegant though.

**Comment by NetSysFire** [comment]
Closing because I ventured outside of the original scope and it got a bit messy in here. It is less work to create a new PR than to clean up here for anyone looking to merge this later. I'll open a new one shortly, dont worry. My work is almost done, too.

**Pull request closed without merging**
