### PR TITLE
Sealed jams

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
SUMMARY: Content "Canned Jam Recipe"

#### Purpose of change
Creating preserved jams for winter consumption.

#### Describe the solution
I've added a recipe that uses the canning process.  However, I'm lost on how to create an item that recognizes the jam as sealed.  I looked at canned meats and fruits items and saw no flag or other way that marks them as being sealed and immune to rot effects until after they've been opened.  

#### Describe alternatives you've considered
None

#### Testing
Tested and no errors and works as expected.

### CODE REVIEW

**Comment by ishtatann** [comment]
I believe the sealing is done by the container you use.
The jar_3l_glass_sealed is in data\json\items\containers.json and has "preserves": true on it.
Have you tried using the recipe?

**Comment by Maleclypse** [comment]
> I believe the sealing is done by the container you use.
> The jar_3l_glass_sealed is in data\json\items\containers.json and has "preserves": true on it.
> Have you tried using the recipe?

So I made a change and removed the `sealed_` from the recipe but now it's replaced all fruit jam recipes instead of working as a possible alternative fruit jam recipe.  So I'm wondering if there is some way for me to show that this is an alternative recipe or am I going to have to add back in the `sealed_` in result and create a specific item?

**Comment by Maleclypse** [comment]
Discovered recipe suffixes.  I think I have this resolved.  Waiting on tests to clear then removing WIP.

**Comment by Maleclypse** [comment]
Can someone who understands Travis let me know if that failure is my fault somehow?  It looks like the average calories for the jarred jams are coming in below the lower bound?  But I don't see how I have any control of that?

**Comment by I-am-Erk** [comment]
My first pr was bread so I guess it makes sense for my first merge to be jam.

**Pull request merged**
