### PR TITLE
Resized .223 and 5x50 ammunition

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Reduced the stack_size of 5x50 and .223 casings and ammo. See commit descriptions.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Why change the stack sizes?

**Comment by BorkBorkGoesTheCode** [comment]
The 5x50 gives the impression that it's nearer the size of the 5.56 than the .22 CB, and the .223/5.56 stack sizes don't match the volume quote for 1 cup of casings (about 46.91710255190997 per cup). I need to enlarge them further to account for the bullet protruding from the casings.

**Comment by Rivet-the-Zombie** [comment]
Can we keep the serving sizes the same while changing their overall volume instead? Boxes of 47 cartridges seem weird.

**Comment by BorkBorkGoesTheCode** [comment]
@Rivet-the-Zombie I didn't change the number of cartridges spawned: 5.56/223 cartridges still spawn in piles of 30, 5x50 still spawns in piles of 100. The prices have decreased though. I'm going to fix them.

**Pull request merged**
