### PR TITLE
More loot in vehicles

### LINKED ISSUE #5595: Spawning items in vehicles is MASSIVELY underused
While looking at vehicles.cpp, I just noticed something;  despite having a system to spawn items in vehicles, 99% of the vehicles spawn with nothing.  Nada.  Zip.
I guess it's just something that got overlooked (the vehicle item code is pretty new), I think we should make an effort to add a few spawns to all the vehicles.  We don't want military trucks and swat vans to be loot piñatas, but they should at least have a chance to have SOME stuff lying in them.  Same with an umbrella occasionally in the back seat of a car, a spare tire or jack in the trunk, etc.  All those little things that get left lying around and make a car a CAR, and not just some mobile metal box.

Does anyone want to work on this?  Or have any good ideas for items to include?  I may even take a crack at it myself if nobody is interested.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1548825-spawning-items-in-vehicles-is-massively-underused?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by illi-kun**
It finally closes #5595.

The followings items were added:
- Military id in military vehicles;
- Some military stuff in Military Cargo Truck;
- Fancy snacks in sports cars and luxury RV;
- Trash in shopping carts;
- Joints in motorcycle.

Minor side correction: name of superbike was capitalized (and now it matches style of other names).

If further expansion is required please create new specific issue(s) for that.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Interesting. Would it be recommended that I implement similar changes in tank mod?

If I do so, I might also do the "shift camera from driver to commander" thing I'd been putting off. If I could recall any other things that have been suggested...

**Comment by Rivet-the-Zombie** [comment]
Very cool!

**Comment by illi-kun** [comment]
@chaosvolt, yes, I think such changes are applicable to all military vehicles, so fill free to implement the same cahnges for vehicles from your mod.

@Rivet-the-Zombie, thanks!

**Comment by chaosvolt** [comment]
Ah, will start up a PR for it in the event this is merged then. ^^

**Pull request merged**
