### PR TITLE
Modifies the aggression of several types of wildlife, and edits their descriptions for grammar and consistency

### PR DESCRIPTION
**Pull request by ghost**
```SUMMARY: Balance "Many animals such as coyotes and dogs are now less aggressive across the board."```

#### Purpose of change
The aggression of many types of wildlife in-game are currently not consistent with their aggression in real life. Coyotes will attack you for so much as straying near them, when in real life they're timid and likely to flee if you shout at them. Moose will mess you up even while you're shouting at them. Domestic dogs, which retain their trust of humans for a long time, will also attack if they're in a bad mood.

Because these behaviors are inconsistent with real life, I decided to change them by adjust fear, placate, and aggression triggers for coyotes, moose, and dogs. Moose will stop faster if you call their bluff, coyotes will flee from loud noises, and dogs are less likely to attack you, and more likely to flee if you fight back.

Research sources:
* Feral dogs retaining human trust - [1](https://www.theguardian.com/lifeandstyle/2018/feb/05/dogs-chernobyl-abandoned-pets-stray-exclusion-zone), [2](https://www.smithsonianmag.com/smart-news/chernobyl-puppies-are-bound-united-states-180969086/)
* Coyote timidness - [1](https://en.wikipedia.org/wiki/Coyote), [2](http://www.humanesociety.org/animals/coyotes/tips/coyotes_people.html)
* Moose bluff charges - [1](https://www.youtube.com/watch?v=YZEbBZ2IrXE), [2](https://www.nps.gov/noat/planyourvisit/moose-safety.htm)
* My girlfriend, who has camped the Midwest throughout her life and has extensive experience dealing with coyotes

#### Describe the solution
* Removed `PLAYER_CLOSE` from coyote anger triggers (both types), and added a `SOUND` fear trigger, meaning they will flee from loud noises.
* Lowered aggression values for most dog breeds.
  * Chihuahuas retain their aggression because ~~chihuahuas are bastards~~ are naturally very aggressive even towards their owners ~~and delight in the suffering of innocents~~.
  * Rottweilers retain their aggression because they're territorial and vicious.
  * German shepherds retain most aggression because they're stalwart, brave, and intelligent, and won't back down easily when threatened.
* Changed the descriptions of most dog breeds for fluff and grammar.
* Added `HURT` to fear triggers for smaller dog breeds such as daschunds and more docile ones such as the boxer mastiff.
* Removed `PLAYER_CLOSE` from moose anger triggers, but increased their default aggression, removed their placate triggers, and added `HURT` to anger triggers.
* Added the `MATING_SEASON` anger trigger and added it to the moose.
  * Moose now have `baby_flags` equal to `AUTUMN` to support this.
* Added the `PLAYER_NEAR_BABY` anger trigger and added it to the black bear.
* Renamed "bear" to "black bear", and removed `PLAYER_CLOSE` from its anger triggers.

#### Describe alternatives you've considered
An argument could be made for increasing difficulty by having wildlife be constantly aggressive, but I feel that niche is filled already by many animals such as giant insects, bears, and cougars (which avoid humans in reality, but is less likely to respond to intimidation like coyotes.)

Additionally, it seems that realism is generally valued over difficulty from what I've observed in this code base, and coyotes suddenly losing all fear of humans makes little sense realistically - especially because now they don't feel pain, and are liable to get back up after they die.

### CODE REVIEW

**Comment by Marrim** [comment]
Huh. I've always been taught that feral dogs are more dangerous than wolves because they know humans and don't fear them. They may not attack you easily, but if they do attack, you can't scare them away by bluff.

**Comment by Xhuis** [comment]
I think there's a difference between feral dogs and domestic dogs who are suddenly forced out into the wild due to outside circumstance. A pet suddenly left ownerless seems like it'd logically be *eager* to interact with other humans that aren't trying to kill it, and animals seem to instinctually know about the blob, given how they attack zombies.

**Comment by Mecares** [comment]
Maybe you could have a look at far too frightful animals as well, especially birds seem to flee as soon as i  come into vision range, which makes it combined with their high speed almost impossible to hunt them.

**Comment by MT-Arnoldussen** [comment]
I like these changes for the most part.

I agree that distinguishing between coyote breeds seems farfetched.

Also, will this mean Moose are never a threat as long as you shout at them?

**Comment by Xhuis** [comment]
Coyote name changes reverted, awoo.

**Comment by kevingranade** [comment]
My only real concern with lowering overall aggression and increasing fear
(but I'm mostly thinking of the moose here) is that I don't think we have a
way to model, "full of bluff unless provoked", because we have no way of
separating a fear trigger like shouting from an anger trigger like taking
damage.  In other words, if you hurt a moose, no amount of shouting should
do a thing to stop it, but nothing about the current system prevents
shouting from stopping an attacker in their tracks, even repeatedly.

That having been said, your description says you adjusted moose behavior,
but I'm not seeing any changes.

**Comment by Xhuis** [comment]
I might look into some C++ to add a new flag called `BLUFFS` that makes them stop attacking if they become hostile from being near you and you shout, but that doesn't affect it if you've already fought back. That said, I'm not sure how to check for player damage specifically. Maybe an effect that's applied when the player hits it, and it only stops if that isn't there?

**Comment by MT-Arnoldussen** [comment]
Might just check for HP. A moose that got into a fight with wolves might not be too friendly with the player afterward.

**Comment by kevingranade** [comment]
Alternately, I'd prefer a system where Moose are docile unless provoked, and attack relentlessly once angered, which we can do by simply giving them no fear triggers, removing a lot of the default aggression, and giving them "HURT" as an anger trigger.

Basically, if we have to lose either the bluffing or the aggression once provoked, it's the bluffing that should go away.

**Comment by DracoGriffin** [comment]
Since we're brainstorming, it'd also be great if there was a "BABY_NEARBY" flag, to represent overprotective animals --- moose and bears are great examples of this.

[Bear Behavior](http://www.bearsmart.com/about-bears/behaviour/)
>A black bear’s first line of defence is retreat, but grizzlies, especially sows with cubs, can be very aggressive towards other bears and people they perceive as threats.

[Staying Safe Around Bears](https://www.nps.gov/subjects/bears/safety.htm)
>Be especially cautious if you see a female with cubs; never place yourself between a mother and her cub, and never attempt to approach them. The chances of an attack escalate greatly if she perceives you as a danger to her cubs.

[Aggressive Moose](http://www.adfg.alaska.gov/index.cfm?adfg=livewith.aggressivemoose)
>Moose are not normally aggressive; however, they can be very aggressive, especially in winter when they are hungry and tired of walking in deep snow; or when they are harassed by people, dogs, and traffic.

>During the fall mating season in late September and October, termed the rut, bull moose may be aggressive toward humans. In late spring and summer, cow moose with young calves are very protective and will attack humans who come too close. If you see a calf and not a cow, be very careful, because you may have walked between them which is a very dangerous place to be.

**Comment by cosmiccoincidence** [comment]
> A black bear’s first line of defence is retreat, but grizzlies, especially sows with cubs, can be very aggressive towards other bears and people they perceive as threats.

The only bear that would be in new england would be a black bear, so maybe that should be specified in game?  And although black bears are less aggressive than grizzlies, they can charge you, bluff charge you, out run you, climb at tree to get to you, will be extra defensive with cubs, will be attracted to food both on a person or kept in a semi open area (dumpsters, etc),  and I believe you can possibly avoid a fatal mauling by not having any smelly food on you and playing dead...

**Comment by Treah** [comment]
I very much agree with the changes here to coyotes. I live in Arizona which is infested with them and I have never NEVER feared them whatsoever. I have even been near a pack of them as they were walking though the city. So even human adapted ones flee from humans.

**Pull request merged**
