### PR TITLE
Make haggis more costly

### PR DESCRIPTION
**Pull request by AMurkin**
Because this is 4 portions with 72 nutrition.

### CODE REVIEW

**Comment by 1skandar** [comment]
Incorrect. 4 portions, yes but only 48 nutrition each. As such, your changes are overkill. 

4 raw offal can be turned into 4 cooked offal at 28 nutrition each and the 2 stomachs turned into boiled stomachs of 15 nutrition each. Add the oatmeal which, when cooked, is 48 nutrition and the tallow at 18 and now haggis is worth less nutrition than the components that went into it. 

I'd say you need to take a look at other recipes and see how haggis stacks up and then come back and rethink your changes.

**Comment by AMurkin** [comment]
Yeah, 60 for meat soup and 72 for haggis with CBM.
Base: 40 for meat soup and 48 for haggis.

 dish | meat soup = 4* 40 = 160 | haggis = 4* 48 = 192
---|---|---
now | 2* 28 (meat) + 30 (spaghetti) + 40 (broth) = 126 | 28 (offal) + 15 (stomach) + 48 (oatmeal) + 6 (tallow) = 97
suggested | -//- | 4* 28 (offal) + 15 (stomach) + 2* 48 (oatmeal) + 6 (tallow) = 229

_+ Enjoyability bonus!_
Oatmeal ruined everything. With 1 oatmeal - 229 - 48 = 181.

**Comment by FulcrumA** [comment]
Take into account also how much harder is to be even able to make one and the other (availability of recipe and cooking points required).

**Comment by JacobKessler** [comment]
So you want to take haggis, a food primarily used after food is no longer a driving factor and which requires significant skill to craft, and make it significantly worse nutrition-gain-wise than the significantly easier to craft (both in terms of skill and ingredient availability) soup?

Haggis mostly seems like an advanced use for the endless quantities of offal and stomachs that you get from wolves randomly attacking you once you can confidently kill and butcher them. At the very least, compare it with a cooking-3 food like meat pizza, and arguably higher (the scots cookbook isn't common), which gets you into the same class as pemmican and other end-game foods.

**Comment by AMurkin** [comment]
IMO pizza op too. But that's promise massive overhaul. Closing per feedback.

**Pull request closed without merging**
