### PR TITLE
Make Plate armor, Chainmail armor and gambeson less encumbering

### PR DESCRIPTION
**Pull request by GOFLUMPYOURSELFPORCAY**
#### Summary
```SUMMARY: Balance "Makes Plate armor, Chainmail armor and gambeson less encumbering"```

#### Purpose of change
The in game plate and chainmail armor has 20 encumbrance each, if they are fitted, then they have 10 encumbrance. The in game gambeson has 15 encumbrance, if it's fitted, it has 7. 
In the battlefield, knights at least wore the gambeson under their armor, if not with the chainmail.
If we think that a knight wore the gambeson, chainmail, and the plate armor on top of eachother, than 10+10+7+3 encumbrance is too much.
https://www.tandfonline.com/doi/abs/10.1080/01615440.2015.1112753
https://www.cnet.com/news/this-is-how-easy-it-is-to-move-in-full-metal-plate-armor/
https://www.metmuseum.org/toah/hd/aams/hd_aams.htm (4'th question) 

#### Describe the solution
Decrease the encumbrance on gambeson, chainmail and plate armor.
(not fitted plate armor: 14, fitted plate armor: 9/ not fitted chainmail armor: 14, fitted chainmail armor: 7, not fitted gambeson: 10, fitted gambeson 5).

#### Describe alternatives you've considered
I can't think of one.

#### Testing
Created a world with the default character, then wore chainmail armor and plate armor, ran, was tired before a minute.

#### Additional context
There is an educational video of a fireman, soldier and knight running, made by Military Museum of Castle of Morges in switzerland. [Here it is.](https://www.youtube.com/watch?v=pAzI1UvlQqw)

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
I am kindly asking you to rename your Github profile.

**Comment by mlangsdorf** [comment]
Knights did not wear full mail under their plate harness.  There were mail voiders attached to the gambeson to cover the joints, but that was the limit of it.

17 encumbrance for plate harness and gambeson is fine, and even 27 encumbrance wouldn't be unreasonable.

**Comment by anothersimulacrum** [comment]
The gambeson is integrated into the chainmail, for a total of 20 encumbrance, not 30. As such, I don't think this PR should be merged, because the encumbrance if worn properly is actually less than the suggested encumbrance here.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
anothersimulacrum, then can you explain why when disassembled, it only gives curiass, steel leg and arm guards? why doesn't it give the mail coif?

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
> Knights did not wear full mail under their plate harness. There were mail voiders attached to the gambeson to cover the joints, but that was the limit of it.
> 
> 17 encumbrance for plate harness and gambeson is fine, and even 27 encumbrance wouldn't be unreasonable.

 https://www.youtube.com/watch?v=zGl_UXc9HIE
DESCRIPTION OF THE VIDEO: 
A video shoving how to dress in and wear armor (harness) from late 14th century. The harness is a detailed reconstruction based on the effigy of the Black Prince (1330-1376) in the Canterbury Cathedral, other relevant effigies, paintings in 14th century manuscripts and late 14th century armour displayed in The Royal Armories in Leeds.

**Comment by anothersimulacrum** [comment]
It's integrated into the chainmail, not the plate armor.

image

image

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
oh, thank you then.

**Comment by anothersimulacrum** [comment]
It does. On their own, the chainmail armor pieces are 10 bash, 10 cut. When in the suit, combined with the gambeson, they are 15 bash, 15 cut.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
thank you everyone.

**Pull request closed without merging**
