### PR TITLE
Swamp spawnrate rebalance

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary

SUMMARY: Balance "Adjust swamp spawn rates"

#### Purpose of change

Swamps are currently practically devoid of life, owing to the very low spawn rate of their mongroup. This PR aims to bring some more life in them, in preparation for some future insect reworks.

#### Describe the solution

Spawning as it stands: on mapgen each overmap terrain has a number of chances (depending on the terrain) to roll a d1000 on its prescribed monstergroup table, in which the applicable monsters (those not excluded by e.g. time-of-day conditions) get a given number of entries. 
However, the number of these entries varies greatly between the different OMTs in all respects: on a Day 1 noon roll you have

- 850/1000 chance to spawn something in a river (with a high population + mostly in packs, I suspect a relic from before the fishing rebalance),
- 550/1000 chance to spawn something on a field or forest, and
- 85/1000  chance to have something spawn in a swamp (and if you exclude lemmings, 35/1000).

After gameplay scaling (also determined in the monster groups, peaking at day 33), that abysmal rate comes up to... a whopping 496/1000, leading to summer swamps being one of the chillest places to be. 

Add to that that spawning only* happens on mapgen, and a good chunk of critters are hidden behind spawn conditionals (ie. to see that *beautiful* Ultica tile for a sludge crawler you have to explore an unexplored swamp at night..). Those two factors make swamps boring, and that made me sad, so I:

- Removed spawn conditions on every critter
- Turned the base spawn rate of all critters up, to a combined spawn chance of 400/1000 day 1
- Raised the population and spawn probabilities to [2,6] and 50% respectiveley
- Adjusted the cost_multipliers so that "prey" species and predators are counted differently

TODO:

- [x] Adjust scaling to be universal and not end at the beginning of Summer1

#### Describe alternatives you've considered

Using a different default monster for the mongroup (currently mon_null), but that would have been inconsistent with the other mongroups and would have been problematic to scale.

Using a higher day1 probability (I started with 600), but since swamps already have a generous population slot that made it too busy.
<strike>Play around more with the population and prob numbers, but I wanted to change one variable at a time.</strike>

#### Testing

To test I generated worlds, revealed the overmap and jumped around into swamp clusters (3+tiles, if possible always the middle tile), and took notes of the critters.
Before changes (85/1000): 55(!) jumps, 42xnothing, 11xlemmings (yay.), 1x wasp and 1x dragonfly:
before
This, but 53 times.
Briefly tested 600/1000, aborted because it was too busy even for me.
400/1000, 25 jumps: 2xnothing (both times near a river), usually 2-3 critters/packs in sight, with the occasional busier cluster:
after400
Same map, same swamp, 400/1000 chance. Not the busiest scene in the test, but on the higher end.

#### Additional context

Combined, these changes mean that the half of all swamp OMTs get a chance to spawn, each with 2-6 rolls on the mongroup table (predators are counted as 2 rolls), each of which has a 40% chance to spawn something. That means the swamps feel consistently lively with occasional clusters of higher/lower activity.

With a 400/1000 probability a Day1 character has little chance in a swamp scrap, however if you choose your entry point correctly you can sneak through no problem (longest stretch before being annoyed by a dragonfly was 20 OMTs). This makes swamps more interesting than "annoying wet forests".

Mutated insects are a source of (mutant) meat and chitin, both relatively valuable. In my dragonfly PR (#44779 ) I added a custom harvest list for flying critters with barely any of both, and since the most common swamp insects all belong to that list that helps keep the balance relatively intact IMHO. In the future I'll try to bring arthropods up to par, so that swamps can be the scary posatpocalyptic hellscapes they deserve to be and to further discourage unprepared hunting trips.

Marking it as a draft till the dragonfly rework merges so I can combine both without problems, but please discuss until then too.
Edited with the mapgen changes.

Also look at this poor, neglected wonder:
Sludge

### CODE REVIEW

**Comment by Zireael07** [comment]
Changes look good, except spawn conditions were a good thing to make some critters not commonplace and difficult to find... I liked that challenge ;)

**Comment by Venera3** [comment]
I'm still fiddling with overall rarity of the monsters, for the same reason (experimental mutants are down, for example).

The thing is, I can tell that someone gave the conditions a lot of thought (and lines), but they don't really work with Cata's one-and-done spawning. It would work in a game where monster spawning would happen continously/on loading the terrain, but as it stands you need to jump through a lot of hoops for something interesting to happen.
They also lead to some weeeird stuff, like that 10-strong pack of bats just chillin' by the roadside day and night from that one time I drove home after dark on a new route.

**Comment by Venera3** [comment]
All right, first iteration of scaling is in (remember, this is just for newly spawned terrains). 
I unified the scaling steps into 1 week-2weeks-1month-2month-3months, with things reaching maximum fun just in time for August on a normal start. In that time the composition of mobs shifts to the more dangerous species, the lemmings are extinct by the end of june and dermatiks start spawning relatively regularly. Since toad mothers evolve from toads that's also around the time they show up. All in all not *that* dangerous for now, but a bit different than the present situation.
On the whole the spawn probability goes up to around 540, so the population difference is not that jarring. Since almost all the critters use evolution instead of age_grow (something I plan on changing) you can't really see the non-mega variants after a while, but I futureproofed the scaling in that direction too ( from Summer on the giant versions).
I also changed all freqs into cumulative probability (ie. X chance from 0-168h, Y chance from 168h-336h instead of X, +Y from 168 +Z from 336 etc), so if someone down the line wants to fiddle with the numbers they'll have a way easier time than I did.

**Comment by LyleSY** [comment]
Thanks for looking at this, swamps have been forgotten and lifeless. In general simplifying these lists makes a lot of sense and I strongly support increasing spawns so it's not totally empty all the time. I am not a monster spawn expert, but I've been trying hard to understand them so I'd like to know your thought process here. Why manually spawn larger mutants and also have them evolve/grow? Why not just pick one method? Why is grow better than evolve in your mind? I chose evolve because I wanted a gradual shift instead of a sudden universal change but you may see something I didn't.

**Comment by Venera3** [comment]
I have basically two problems with evolution as it is currently implemented: gameplay-wise, since it happens to freshly spawned (and hatched!) critters and we generally have too short evolve timers it quickly makes the mid-lategame very samey if you don't have alternate upgrade paths, wheras with age_grow you have the potential of a more mixed picture (if you also add reproduction in the mix); and lorewise I think it fits the zombies, which are being actively molded by an external intelligence to evolve as fast as they do, but it makes less sense for the semi-natural critters. Wild speciation within years, sure, but not 2 months to be unrecognizable.
The added "giant" spawns only serve to save me some headache down the line, when I rejig the arthropods one-by-one to use age_grow. 
I'm just about to type up my little manifesto for those changes for a discussion, but if you check out the dragonfly rework you'll get the gist of what I'm aiming for.

**Comment by Venera3** [comment]
Okay, after some adjustments it should be good to go. Added some extra scaling to dermatiks to bring the max. spawn freq to a nice and round 552.

**Comment by Xpyder** [comment]
iirc once upon a time swamps were full of hostile insect life.  Not sure when this changed but nice to see some life back in them.

**Pull request merged**
