### PR TITLE
A chance at second life

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Features "Enabled swapping to follower on death"

#### Purpose of change
the real easy part of #53523

#### Describe the solution
Added a few lines of code prompting you to swap characters if you die.

It works but is not extensively tested (but I think that's the point of adding it)

#### Describe alternatives you've considered
Continue listening to people say "this should now be easy to add" without adding it

Do it the EOC way but I feel like there might end up being special handling specifically on death like dropping a memorial sheet with all your stats/how you died. Swapping journal name etc.

#### Testing
Make a character,
Make a friend,
Die and get prompted

#### Additional context
image

image

image

### CODE REVIEW

**Comment by mkrutov** [comment]
Quick question about this, how does this integrate with journal system?

**Comment by bombasticSlacks** [comment]
image

It persists but is still labeled as the diary of your first Character

**Comment by Ramza13** [comment]
So I would very much prefer we did it the EOC way rather than just hardcode it.  For one it gives us a good test for on death EOCs which I eventually(after 0.G) plan to replace epilogues with.  Secondly it makes it much easier to change the feature, to for example make a scenario or trait where you can only switch once or something.  I've tested the on death EOC and it seemed to work as well as your solution.

**Comment by bombasticSlacks** [comment]
If you want to PR your EOC from the PR where you tested it originally I'll close this. Either way it's an easy addition I just added this because nobody has yet.

**Comment by Ramza13** [comment]
> If you want to PR your EOC from the PR where you tested it originally I'll close this. Either way it's an easy addition I just added this because nobody has yet.
> 
> EDIT: I realize my above comment may come off as catty. I just don't want to author your code. This didn't take any time or much work so I'm happy to go with the EOC option I just don't wanna copy and paste your JSON.

No worries, #53606 should handle this as an EOC.  Thanks for getting me to finally do this.

**Comment by bombasticSlacks** [comment]
Closing as the EOC option is up

**Pull request closed without merging**
