### PR TITLE
Ammunition weight fixes

### PR DESCRIPTION
**Pull request by CatWithFourEyes**
#### Summary

Balance "Bringing the weight of cartridges to real numbers"

#### Purpose of change

Many cartridges in the game have a weight equal to the weight of the bullet without the casing and powder load, or even less weight. This PR should fix that.

#### Describe the solution

Replace old numbers with new ones, based on catriges weight data, or calculated weight from "bullet weight + average powder load + average casing weight".

Increase weight limits for cardboard ammo boxes, to resolve conflicts with ammo density

#### Describe alternatives you've considered

Don't touch it.
 
#### Testing

Load game with changed numbers to see changed ammunition weight

#### Additional context

Sources of information
https://www.thefirearmblog.com/blog/2016/04/09/how-much-does-your-ammunition-weigh/
https://www.armorally.com/brass-counts-by-weight/

For .450 Bushmaster:
https://defiantmunitions.com/450-bushmaster-250gr-tcx-mad-pig-total-copper-x-panding-solid-copper-defensive-ammunition/  - weight of the box calculated based on .223 ammo in same package and deducted

For .50 Beowulf: 
https://www.ar15.com/forums/General/Who-makes-50-Beowulf-brass-for-Alexander-Arms-Can-t-be-Starline-11-grain-difference-/5-2315385/ - added weight of the bullet and avg. powder load.

For 12Ga weight:
https://armoryfarm.com/venom-12-ga-9-pellets-1-case-300-rounds/
Also personal knowlege that 12ga is ~45-50g
Beanbag 12ga - deducting pellets weight and adding 40g according to https://en.wikipedia.org/wiki/Bean_bag_round

For .410: 
https://www.mutinymachine.com/product/remington-410-bore-ultimate-defense-000-buckshot-5-pellets-3-1125-fps-black-ball-special-15-shells-box/

### CODE REVIEW

**Comment by Maleclypse** [comment]
Lotta container itemgroups are broken by this.  Tests showed several ammo boxes failing

**Comment by CatWithFourEyes** [comment]
> Lotta container itemgroups are broken by this. Tests showed several ammo boxes failing

Seen this, thinking about possible solutions. First one, coming to mind is increasing "small ammo box" weight capacity (currently it's 2kg), since it's supporting only ~5g/cm^3 when full, and ammo can be more dense.
Second one - rechecking volume and weight, but can't find mistakes here.

**Comment by Maleclypse** [comment]
Good news 
```
item_material_density_blacklist_is_pruned
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:766
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_00 had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   3.0f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   410shot_000 had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_slug had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_flechette had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_bird had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_he had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   3.0f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_410shot_000 had its density fixed, remove it from the list in data/
(~[slow] ~[.],starting_items)=>   mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_dragon had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.5[90](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5274343521/jobs/9538849440?pr=66160#step:16:91)[91](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5274343521/jobs/9538849440?pr=66160#step:16:92)f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_beanbag had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   shot_scrap had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_scrap had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_shot_00 had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_shot_bird had its density fixed, remove it from the list in data/
(~[slow] ~[.],starting_items)=>   mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_shot_dragon had its density fixed, remove it from the list in data/
(~[slow] ~[.],starting_items)=>   mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_shot_flechette had its density fixed, remove it from the list in
(~[slow] ~[.],starting_items)=>   data/mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.[136](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5274343521/jobs/9538849440?pr=66160#step:16:137)36f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   reloaded_shot_slug had its density fixed, remove it from the list in data/
(~[slow] ~[.],starting_items)=>   mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_00 had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_bird had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_dragon had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_flechette had its density fixed, remove it from the list in data/
(~[slow] ~[.],starting_items)=>   mods/TEST_DATA/known_bad_density.json
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/item_test.cpp:781: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( item_density( target ) > max_density )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   2.13636f > 5.5355f
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   bp_shot_slug had its density fixed, remove it from the list in data/mods/
(~[slow] ~[.],starting_items)=>   TEST_DATA/known_bad_density.json
``` You fixed the density on a number of items so now you need to remove those items from the `known_bad_density.json` in the TEST_DATA  folder.

**Comment by CatWithFourEyes** [comment]
> Good news

Doesn't look good. Or it is?

**Comment by randomtyper** [comment]
> > Good news
> 
> Doesn't look good. Or it is?

It is good. That means that the items now have density that makes sense. Just remove the items with these IDs from the file data/mods/TEST_DATA/known_bad_density.json.

**Comment by CatWithFourEyes** [comment]
> > > Good news
> > 
> > 
> > Doesn't look good. Or it is?
> 
> It is good. That means that the items now have density that makes sense. Just remove the items with these IDs from the file data/mods/TEST_DATA/known_bad_density.json.

Done

**Pull request merged**
