### PR TITLE
[CR] [WIP] Ice content

### PR DESCRIPTION
**Pull request by Shoes01**
This PR contains new content geared towards cold weather. I worked on it a few months ago but lost steam; for now I am at it again. 

Cygwin does not allow me to launch the game yet (outstanding locale bug or something), so I can't playtest right this moment. Last time I played with this content, it seemed okay. 

I had to copy paste by hand most of the code because of the numerous refactorings, so if I seem to have left something out, let me know!

Changes and additions
- A new function calculates radiant temperature, allowing monsters to have an "aura" of hot or cold. Also affects how fire factors into body temperature.
- Monster speed is affected by temperature. Species influence how affected monsters are.
- New tiles added : frost, mist, ice, snow. Ice increases movement cost, has a chance of causing the player to slip. Lowers dodge and melee skills. Ice mist cools the player.
- Gases spread less randomly: gases cannot move to tiles of greater density; this causes them to spread out as evenly as possible, occupying more space.
- New weapons and effects : ice grenade, ice Molotov, ice rocket launcher, some freeze rays. Ice <weapons> have "ice" explosions that leave behind frost and ice. Freeze <weapons> have a chance of encasing the target in a block of ice. 
- New zombies and effects : a normal ice zombie that has a chilling strike which reduces body temperature, and then a spitter equivalent zombie, but ice instead.

### CODE REVIEW

**Comment by Shoes01** [comment]
I am closing this because I don't think any of this will plausibly make it into the game ;p Ice weapons? However, a lot of the under the hood changes I made have been added independently in other PRs. The branch will remain on my repo if ever you want NPCs to have weapons that comically freezes the player.

**Comment by KA101** [comment]
>A new function calculates radiant temperature, allowing monsters to have an "aura" of hot or cold. Also affects how fire factors into body temperature.

>Monster speed is affected by temperature. Species influence how affected monsters are.

>New tiles added : frost, mist, ice, snow. Ice increases movement cost, has a chance of causing the player to slip. Lowers dodge and melee skills. Ice mist cools the player.

None of these are in to my knowledge, and we're poorer for that lack.  Freeze ray might somehow be feasible if ice lab finales are pegged to a portal from a frozen Nether dimension or something.

Shoes, I'm gonna ask you to reconsider.

**Comment by Snaaty** [comment]
Yeah, I also very much support this PR!

**Comment by Shoes01** [comment]
Oh my! Well in that case, I will reconsider. It's exam week at school, so I should have some down time to tinker a bit :3

**Comment by Shoes01** [comment]
I am going to PR a bit of stuff when I get home today. I am looking at making monster speed dependent on weather conditions, however that whole section of the code base has changed. Where would be an appropriate place to drop in some of this code? I don't want to interject bloat in what seems to be a pretty streamlined creature.cpp.

**Comment by DavidKeaton** [comment]
I'm all for this!!!

**Comment by DavidKeaton** [comment]
also perhaps the slowness in weather could make use of i2amroy's effects system?

**Comment by Shoes01** [comment]
What are these effects and were do I find an example of them? I'll take advantage of them if I can!

**Comment by DavidKeaton** [comment]
effects.{h,cpp} and doc/json/effects.md I think :-)

**Comment by Shoes01** [comment]
Cool, I'll look into that.

**Comment by DavidKeaton** [comment]
p great stuff, my medical stuffs will be using it

**Comment by Shoes01** [comment]
@DavidKeaton, in the even that you know more than me I will ask you a question about the effects.json. Take a look at what I have written up : http://pastebin.com/NyVWrxHx

You can see I am not sure how to add a chance to miss physical attacks. I also want boots to have a better grip on ice, but I don't think I can do that with the json alone. Any suggestions?

**Comment by Coolthulhu** [comment]
This PR will probably not become mergeable. Closing.

**Comment by Zireael07** [comment]
However, the idea would be very welcome should anyone revisit it.

**Pull request closed without merging**
