### PR TITLE
Adds ashen brawler (smoker zombie evolution)

### PR DESCRIPTION
**Pull request by aoae23**
#### Summary

SUMMARY: Content "Adds ashen brawlers - a smoker zombie evolution"

#### Purpose of change

Smoker zombies needed an evolution. I suggested smoker brutes facetiously, but Korg said to go for it. He also said to give them grappling attacks (like the zombie wrestler) in order to create an effect of the zombie holding you down in smoke while you suffocate. It sounded like a fun idea that would be easy to sneak in before the content freeze.

#### Describe the solution

Adds ashen brawlers, which are, gameplay wise, a cross between zombie wrestlers and smoker zombies. They emit smoke and are very fast, and have fearsome melee attacks that they use to keep you debilitated in their smoke. 

#### Describe alternatives you've considered

Not unleashing these in the game

#### Testing

Have not tested yet, but it is a fairly straightforward change. Just make sure that smokers evolve into them and that they don't crash the game I guess

#### Additional context

Gameplay wise, they have a pretty terrible field of vision, have less HP than zombie wrestlers, and very low bash armour. But at the same time they are good at evading bullets, and can deal devastating amounts of damage if you cannot kill them quickly. I would approach them only with good face protection like a gas mask and a strong bashing weapon if melee. Or just use a car.

### CODE REVIEW

**Comment by SirPendrak** [comment]
Looks good, almost every basic zes should have one or more evolced versions. 
What about adding "looks-like" so it looks like smoker zombie untill graphic packs catch up?

**Comment by Maleclypse** [comment]
https://dev.narc.ro/cataclysm/format.html for linting.

**Comment by anothersimulacrum** [comment]
I don't think we should have looks-like for monsters, it just adds confusion.

**Comment by SirPendrak** [comment]
Aren't the acid soldiers already "looking like" standard zombie soldiers?

**Comment by anothersimulacrum** [comment]
If they are, I'd argue they should not be.

**Comment by John-Candlebury** [comment]
This monster seems very overstated to me. 

High speed means you can only unrun it with a fresh characacter, while the smoke means you can barely shoot it from afar. With `ranged_pull` it can theoretical grab you even through the smoke even while unseen (as the special doesnt check vision), so it can potentially insta melee you if you open a wrong door inside a building. Once its in melee range, it deals an average of 10 damage per attack, and the high health means its likely to hit you at least 3 times.  Not to mention the smoke debuff,; and the other advanced zombies that are likely to be close, which will mob you once the brawler grabs you.

This would likely be the most dangerous enemy in the game, and in my opinion, the range of combat immunities it has makes it cross the line  from `dificult` into `unfair` .

I think you should at least, make it slower, or push its appearance even way back

**Comment by aoae23** [comment]
Thanks for your concerns. I am considering bringing its speed in line with standard smoker zombies if that makes them more balanced. I definitely want to preserve the mechanic that lets them pull you through smoke though.

**Comment by Amoebka** [comment]
> you can barely shoot it from afar

I think having zombies that intentionally punish ranged playstyles is a good thing, though. There currently aren't many.
The wrong door argument is somewhat strange - you can already open a door and see a zombie hulk (or anything else scary) right next to you.

**Comment by LyleSY** [comment]
This is great, the smoker should have evolutions and these changes are complementary with the concept. It might make more sense to insert an intermediate form, a smoker brute or a smoker wrestler without the stat bumps. It doesn't have to be identical to the vanilla evolution line and maybe shouldn't be.

**Pull request merged**
