### PR TITLE
Change food recipes in minor ways to improve utelization of ingredients

### PR DESCRIPTION
**Pull request by ashGlaw**
#### Summary
```SUMMARY: Content "Recipe Realism"```

#### Purpose of change
As things are added to the game it's useful to go through the recipes and make sure that newer ingredients are as well implemented as they could be in the current recipes

#### Describe the solution
I've gone through the recipes, cooking tools, and cooking requirements and increased access to butter across many recipes where it made sense. I added boiled fiddleheads and roasted salsify to veggy_any, so they could be usable in many more recipes.

#### Describe alternatives you've considered
I've been thinking of ways to expand and improve upon the cooking system. These small edits are minor but working with them has prepared me for more ambitious goals. Perhaps a baking system with ovens that work a lot like smoking racks. It'd take redoing many of the recipes, but it's an alternative I've considered

#### Testing
I've tested each change. Every recipe works with the new ingredients.

#### Additional context
I find myself wondering if sauteed fiddleheads would be a decent addition to veggy_any, or if the inherited fat calories be inappropriate?

### CODE REVIEW

**Comment by KorGgenT** [comment]
notes for mergers: if travis fails make sure the recipe permutation test isn't the reason.

**Comment by KorGgenT** [comment]
it looks like you've done something to the tileset config.

**Comment by ashGlaw** [comment]
Lots of additions. Everything seems good to me. I've tested every recipe I've changed.

**Comment by ashGlaw** [comment]
> 
> 
> it looks like you've done something to the tileset config.

I'm not sure how things keep changing that I'm not editing. I'm not even sure what files those are in. Is it still an issue? I may have taken care of it

**Comment by KorGgenT** [comment]
image
yeah it's still an issue

**Comment by ashGlaw** [comment]
Thanks for looking. I have no idea at all how that got changed. I have never opened the folder that's in, let alone the file. Bizarre

**Comment by AMurkin** [comment]
Commited in the be9bbc4. Probably changed by json linter.

**Comment by ashGlaw** [comment]
I hope I took care of the differences in the tile_config file

**Comment by I-am-Erk** [comment]
`fiddlehead_boiled` is producing a calorie error in travis. I think this is because you removed broth from the possible ingredients, which would slightly reduce the average calorie count for the dish. You can probably resolve this by changing the `calories` attribute of the `fiddlehead_boiled` item by about 10 kcal. I think. Those tests are really finicky.

**Comment by ashGlaw** [comment]
Thanks for explaining that to me. I had no idea what it was talking about. On it!

**Comment by I-am-Erk** [comment]
Tweaked it further trying to beat this dang thing.

**Comment by ashGlaw** [comment]
Is there anything left that needs done here?

**Comment by I-am-Erk** [comment]
I was just waiting for the CI tests to pass. It looks like they passed on the last version - if the CI tests are all good and there's no conflict I don't recommend updating your branch with upstream, as it just resets the CI tests.

**Comment by ashGlaw** [comment]
Thanks for the tip, and the merge. Much obliged

**Pull request merged**
