### PR TITLE
Significantly increased damage threshold of metal bar doors

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Balance "Significantly increased damage threshold of metal bar doors."

#### Purpose of change
Currently bar doors are ridiculously flimsy. An average 8-strength person could easily break them with a wooden baseball bat or wooden quarterstaff. In fact, your character needs only 4 strength and a quarterstaff to break them. This is more strange as ordinary metal bars have solid 60 bash damage threshold which makes them nearly indestructible. Even if we take metal hinges into account, bar doors still shouldn't be such flimsy.

#### Describe the solution
Increased bash damage threshold of locked and closed metal bar doors from 30 to 45. Open bar doors are increased from 20 (even more ridiculously low value!) to 40.

#### Describe alternatives you've considered
Equate metal bar doors to metal bars and make them equally sturdy.

#### Testing
None, obvious change.

#### Additional context
I doubt anyone should be able to break sturdy metal bars like these with any wooden weapon
C90K5F

### CODE REVIEW

**Comment by Broken27** [comment]
Making bars immune to wooden weapons is all well and good, but with the new values they are immune to a homewrecker too. (Well, unless you also have 16 str).

This combined with the imposibility to make lockpicks make the prison scenario outright impossible.

I suggest an slighty lesser value of 40 instead of 45, so homewreckers still work.

**Comment by anothersimulacrum** [comment]
Prisons can spawn with the necessary tools to create lockpicks, so it would not be impossible.

**Comment by Broken27** [comment]
> Prisons can spawn with the necessary tools to create lockpicks, so it would not be impossible.

Not really. Not for Island Prison, anyway.

To make lockpicks, you need either Metal sawing 2 (A hacksaw or equivalent) to make them from scrap metal, or a Plier/bolt/multitool cutter to turn barbed wire into normal wire.

I did an island prison run recently and it was simply impossible to get normal wire (Aside of spending two hours dissasembling a bra for one piece of wire, and even that doesn't help because it's filthy).

The only way to access the inner prison is bashing the bars away.

**Comment by actual-nh** [comment]
A tool with PRY should be able to do some damage, actually.

**Comment by anothersimulacrum** [comment]
Ah, I was commenting on the normal prison.

**Comment by Night-Pryanik** [comment]
> with the new values they are immune to a homewrecker too. (Well, unless you also have 16 str).

Homewrecker has 35 bashing damage, so you need only 10 strength to break it down. 10 strength is just a strong person, slightly above the average. I feel it's justified. Also I feel that homewrecker shouldn't be able to break metal bar doors. It's just several pieces of metal lumps tied to the stick. Sooner its handle would break rather than metal bars.

>To make lockpicks, you need either Metal sawing 2 (A hacksaw or equivalent) to make them from scrap metal, or a Plier/bolt/multitool cutter to turn barbed wire into normal wire.
I did an island prison run recently and it was simply impossible to get normal wire (Aside of spending two hours dissasembling a bra for one piece of wire, and even that doesn't help because it's filthy).

I've added fixed and guaranteed spawn of pliers to Island prison type B, so making lockpicks is possible. We don't have guaranteed spawn of tools required to craft lockpicks to Island prison type A, and we could add such guaranteed spawn to it too, and it's way better than making metal bar door arbitrarily flimsier than it should be. 

On a side note, Island prison is a challenge, and as it was said numerous times, challenge-type scenarios are not guaranteed to be "winnable" at all. So if in current run rng didn't spawn you a tool for crafting lockpicks, well... bad luck, there are plenty of other ways to escape the island.

**Comment by Theawesomeboophis** [comment]
This makes sense for both balance and realism, I always wondered why bashing a pointy stick against steel bars broke them.

**Comment by Shodan14** [comment]
I guess it's significantly easier to dismantle/pull of its hinges, but otherwise seems a bit odd.

**Pull request merged**
