### PR TITLE
Adjust Newspaper Chronology

### PR DESCRIPTION
**Pull request by halosammy**
#### Summary

Bugfixes "Corrected placement of a snippet"

#### Purpose of change

Blob Singularities only started showing up on April 15th. Because of this, the snippet mentioning "Hastur" belongs in the newest news category.

#### Describe the solution

Rearrange snippet placement.

#### Describe alternatives you've considered

N/A

#### Testing

N/A

#### Additional context

N/A

### CODE REVIEW

**Comment by Karol1223** [comment]
Good god don't change the IDs without a reason please

**Comment by halosammy** [comment]
> Good god don't change the IDs without a reason please

I’m not sure what you mean. I did provide a reason. The newspaper I moved was in the wrong category.

**Comment by Karol1223** [comment]
> I’m not sure what you mean. I did provide a reason.

You provided a reason for changing snippet category. That makes sense.

Changing the ids of unrelated snippets FOLLOWING the id number of the one you moved does not make sense. Please do not change IDs unless there's some really good reason to do so. Making sure the numbers line up right isn't a good reason.

**Comment by halosammy** [comment]
> > I’m not sure what you mean. I did provide a reason.
> 
> You provided a reason for changing snippet category. That makes sense.
> 
> Changing the ids of unrelated snippets FOLLOWING the id number of the one you moved does not make sense. Please do not change IDs unless there's some really good reason to do so. Making sure the numbers line up right isn't a good reason.

Oh, that’s what you mean. That’s easy enough to fix.

**Comment by KeremBabaG** [comment]
Afaik changing the ids messes with the translations as well. Would you consider writing a new snippet for week_old_news_9 and leaving the rest as it is?

**Comment by Karol1223** [comment]
It does mess with the translations, but so do all string edits. Just rewriting the snippet instead of moving it would put the exact same amount of strain on translators.

**Pull request merged**
