### PR TITLE
Audit To-Hit for Bludgeons

### PR DESCRIPTION
**Pull request by ANickelN**
Short length maces with reasonable weight were given neutral balance, as they are similar to the claw hammer which is noted in the game_balance.md to have a balance value of +0 (Neutral)

#### Summary
Balance "Adjust To-Hit Value of Bludgeons"

#### Purpose of change

Noticed some inconsistency within the to-hit values of some weapons, this change is intended to keep them consistent with the game_balance.md document.

#### Describe the solution

Go through the bludgeons file and compare the present values with the examples in game_balance.md.

#### Describe alternatives you've considered

Simply leaving things as they are.

#### Testing

Game loads properly, weapons have appropriate to-hit values.

### CODE REVIEW

**Comment by ANickelN** [comment]
Failure seems unrelated.

**Review by bombasticSlacks — APPROVED** [review]
looks good to me, gonna get at least one more set of eyes on it

**Comment by x-qq** [comment]
War hammer should not be -1. Unlike most of the things it is an actual weapon made for the purposes of swinging, with quite good balance (1.34 kg with a 120 cm long handle will be comfortable enough to wield both one handed and two handed).

PS: it's also defined as surface = point, which is incorrect, as it will do good damage with both front side (hammer) and back side (armor-piercing spike).

**Comment by ANickelN** [comment]
> 

Adjusted surface of warhammer to "line", as you still need to align either the hammer head or the pick end for a proper blow.  Changed balance of the weapon to "good".

**Comment by ANickelN** [comment]
Unrelated Failure

**Pull request merged**
