### PR TITLE
change vehicle volume display from legacy units to liters issue #18634

### PR DESCRIPTION
**Pull request by PlasmaChroma**

### CODE REVIEW

**Comment by illi-kun** [comment]
I guess it can conflict with #18468.

**Comment by PlasmaChroma** [comment]
Oh wow, yeah, it's certainly in direct conflict.

I didn't see that an older request had imagined completely re-hauling units.

**Comment by PlasmaChroma** [comment]
As a result of c35e34ef8af6c984e512b344fd8c5b7a3f9fd7ab superseding this, I am closing this PR.

**Comment by illi-kun** [comment]
I guess that was fixed by the mentioned PR.

**Pull request closed without merging**
