### PR TITLE
Mark some specific furnitures/terrains examine as always allowed in faction territory

### LINKED ISSUE #77239: "Stealing" checks are too aggressive
### Describe the bug

You can no longer read signs at the exodii base.

You can no longer move creates and lockers at refugee center. This prevents completing the first merchant quest to kill zombies (Clear Back Bay).

### Attach save file

N/A

### Steps to reproduce

1. Try grabbing crates at the refugee center
2. This makes everyone hostile

1. Try activating signs at the exodii base to read them.
2. This triggers a warning too

### Expected behavior

Reading signs should be allowed.

Moving some crates and lockers at the refugee center should be allowed.

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: 2357a3c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Bugfixes "Mark some specific furnitures/terrains examine as always allowed in faction territory"

#### Purpose of change
* Closes #77239

#### Describe the solution
Add a flag `FREE_TO_EXAMINE` to the common furniture/terrain that should always be examinable.

If that flag is present, the locals will never care about you examining it.

Added to the following furniture/terrain:
Translocator (magiclysm)
Exodii sign at their main base and all other `f_sign` by extension
Exodii sign at their barns (not faction territory atm, but just in case)

#### Describe alternatives you've considered
Tying it to the examine actor/function

Uh it turns out that a flag was incredibly simple, so the flag was chosen instead.

#### Testing
Spawned a sign at a faction territory

Examined glass display case, got warned

Examined sign, no warning

#### Additional context
https://github.com/CleverRaven/Cataclysm-DDA/issues/77239#issuecomment-2451984463 is a problem with the design. There's no way in and the prisoners SHOULD be upset about you forcing your way in (they're barricaded to keep the zombies out). I don't know what to do there 🤷 

This PR was way easier than I thought.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Regarding prisoners problem: probably they should be upset, but not THAT upset. Removing the barricade should lower their opinion towards player, but not to the point of attacking on sight after getting in.
The other possible solution is to remove the barricaded doors from the prisoners' zone of ownership, so they don't mind removing the barricade at all.

**Comment by RenechCDDA** [comment]
> Regarding prisoners problem: probably they should be upset, but not THAT upset. Removing the barricade should lower their opinion towards player, but not to the point of attacking on sight after getting in. The other possible solution is to remove the barricaded doors from the prisoners' zone of ownership, so they don't mind removing the barricade at all.

For better or worse, there are only two levels of granularity in 'ownership zones'.

* #77428
image

We could offset their relationship status to absorb the first offense, but that would be prone to breakage if the values change in the future. It would also not work well if the player failed at lockpicking, since each attempt would accrue additional relationship losses.

**Comment by RenechCDDA** [comment]
Oh this is embarrassing. I went to go find who added this mapgen to ask their intention, but that's you!

I feel like the prisoners being a bit smug (at owning the place) *and* peeved (from the fact you broke in) is appropriate for the prison setting.

We could limit their ownership to one OMT, set them to **initially** allow you to touch anything (allowing you to break in/lockpick your way in), and then have an EOC that fires when you actual enter their OMT which flips it to not allowed. It seems a little jank, but it does emulate your unexpected, unwanted entry into their safe area. 

Could also add a new line/topic to the first conversation you have with their boss, mentioning that they're surprised/peeved at how you got in.

**Comment by kevingranade** [comment]
Need a rebase to pick up the cross-mod conflict fix.

**Comment by RenechCDDA** [comment]
> Yeah, that would be VERY cool.

We have all the infrastructure in place to already make this, probably just going to have to wait until after christmas. Busy busy :)

**Comment by RenechCDDA** [comment]
Hm, okay. I said we had the infrastructure for that, but I may have been overly optimistic. It seems like the the cafeteria is not confined within a neat little single OMT. I had rashly assumed it was. Here's the OMT borders as shown ingame.

image

 Flipping them to limited_area_claim is still a good idea, but that lets to some weirdness where only part of the cafeteria is considered theirs. Still way better than the entire prison, but not perfect.

**Pull request merged**
