### PR TITLE
Grammar/Spelling

### PR DESCRIPTION
**Pull request by klorpa**
#### Summary
SUMMARY: Bugfixes "Fixes various punctuation and spelling errors."

### CODE REVIEW

**Comment by I-am-Erk** [comment]
You appear to have deleted all your changes with that last update.

**Comment by anothersimulacrum** [comment]
You should never edit `.po` files, any string edits should be in `data/` or `src/`

**Comment by Qrox** [comment]
You should see `lang/po/_NO_MANUAL_EDITING` for why you shouldn't edit the .po files.

**Comment by I-am-Erk** [comment]
I don't think an automated check would fix things since they're already in the PR stage by then

**Comment by Qrox** [comment]
But the author would see the warning and revert the changes before we have to tell them to do so. (Well at least if they are paying attention to the check status)

**Comment by ZhilkinSerg** [comment]
> 
> 
> But the author would see the warning and revert the changes before we have to tell them to do so. (Well at least if they are paying attention to the check status)

Wouldn't it affect expected i18n PRs from @BrettDong? Or we would need to add some kind of  whitelist for PR author to the check?

**Comment by Soupster89** [comment]
Hello, I looked over what you fixed on the CRIT mod and I thank you. However, I now have conflicts that I am not sure how to resolve. Can I receive assistance?

**Comment by Qrox** [comment]
@ZhilkinSerg If a PR is an authentic i18n update we can just ignore the warning and merge it.

**Pull request merged**
