### PR TITLE
Hwp stock

### PR DESCRIPTION
**Pull request by Dan1ss1mo**
#### Summary
Balance "modular folding stock for HWP"

#### Purpose of change
Swap hwp integrated adjustable stock for modular folding stock

#### Describe alternatives you've considered
Not do it if there is some specific reason for hub to favour adjustable stock. May also leave name as it is for now to dodge string freeze. (realized it wouldn't work as i have to also add folded stock variant)

#### Testing
WIP

#### Additional context
I feel like hub would prefer to integrate best possible attachment into they're signature weapon

### CODE REVIEW

**Comment by Maleclypse** [comment]
Hub01 specifically is stated to suffer from "not designed here" syndrome.  So this particular PR has been mentioned as a no go previously iirc.

**Comment by Dan1ss1mo** [comment]
> Hub01 specifically is stated to suffer from "not designed here" syndrome. So this particular PR has been mentioned as a no go previously iirc.

But why can't they design they're own folding stock instead of adjustable one? As you can see it's still treated as unique gun mod. It's just copy base stats from different mod now

**Comment by Maleclypse** [comment]
> > Hub01 specifically is stated to suffer from "not designed here" syndrome. So this particular PR has been mentioned as a no go previously iirc.
> 
> But why can't they design they're own folding stock instead of adjustable one? As you can see it's still treated as unique gun mod. It's just copy base stats from different mod now

Because of actual game balance. You've already said this is a better stock than what it currently has.  It's supposed to be a gun with a whole lot of tradeoffs and not the best in anything.

**Comment by Dan1ss1mo** [comment]
> > > Hub01 specifically is stated to suffer from "not designed here" syndrome. So this particular PR has been mentioned as a no go previously iirc.
> > 
> > 
> > But why can't they design they're own folding stock instead of adjustable one? As you can see it's still treated as unique gun mod. It's just copy base stats from different mod now
> 
> Because of actual game balance. You've already said this is a better stock than what it currently has. It's supposed to be a gun with a whole lot of tradeoffs and not the best in anything.

I see, make sense. Guess i miss understood the intended balance for this gun

**Pull request closed without merging**
