### PR TITLE
Wall wiring tweaks

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Features "Ability to hide/unhide revealed wall wiring by examining it"

#### Purpose of change
Wall wiring having a sprite is convenient for setting it up but is mainly annoying after that
Exterior walls of most pre existing buildings should have WIRED_WALL for verisimilitude

#### Describe the solution
Adds an option to the appliance menu (that only shows up when appropriate) to disable/reenable the sprite showing for that tile
Allows revealing wall wiring in concrete/brick walls that are part of the newish widely used parametrized_walls_palette

#### Describe alternatives you've considered
I can't get hiding the symbol to work for non tiles display, it doesn't seem setup to be able to understand not drawing a null layer that it was expecting so I've just disabled the option if you're not using tiles
Making toggling the option apply to the whole connected network could be cool but seemed substantially more awkward to implement

#### Testing
Checked the option only showed up when appropriate and it removed the sprite leaving the underlying sprite instead (wall)

### CODE REVIEW

**Comment by RenechCDDA** [comment]
This JUST hides them? They still can connect to other appliances, or be connected to, and they're just hidden in the usual world display?

So say someone hides an entire wall (line of wall tiles), forgets about it, then later tries to set up two separate appliance grids on opposite ends of the wall. It just keeps connecting, and there's no way to figure out how aside from *assuming or knowing they can be hidden* and doing the operation in reverse? With wires that you can't see.

**Comment by Procyonae** [comment]
> assuming or knowing they can be hidden

If they hid them once they already inherently know this? You can find them by `e`xamining or `x` looking around tho it's not that difficult to relocate them if you have forgotten

I'll probably try to figure out changing the whole connected networks wires in one toggle at some point but I don't really see why this isn't an improvement as is

**Comment by RenechCDDA** [comment]
I just feel like it's going to be like the open/collapse all containers button in the inventory menu. Shift+E is NOT an easy keybind to hit by accident, but despite that... we had tons of people who managed to hit it and could NOT figure out how to undo it. Even though there was a clear indication (red arrow) indicating that its status was different in some way. Even though the keybinds menu is prominently mentioned in many of our UI windows (including that one).

I am sure a lot of people play the game without ever using the e'x'amine further tiles function, although I can't imagine doing that personally.

**Comment by RenechCDDA** [comment]
Yeah that would be better, IMO.

Regardless we'll have a while before next stable to see if it's a problem, so it's not like I'm *really* opposed.

**Pull request merged**
