### PR TITLE
Ensure atomic coffee is brewed hot

### PR DESCRIPTION
**Pull request by pehamm**
#### Summary
Bugfixes "Ensure Atomic Coffee is hot after brewing"

#### Purpose of change

During discussion in #48936 it came up that only food crafted using a hotplate is supposed to be heated. This notably excludes atomic coffee, which can only be crafted using the atomic coffee maker. This PR fixes this, ensuring we can enjoy our atomic coffee hot.

#### Describe the solution

The code in recipe.cpp has a function to check whether a food recipe should come out hot. It does this by looking whether the tool list includes a hotplate as it is used for both boiling as well as heating. This PR adds a check so all recipes using either a hotplate or the atomic coffee maker get heated.

#### Describe alternatives you've considered

None

#### Testing

Got myself water, coffee powder, and an atomic coffee maker. Made normal coffee and atomic coffee. Without this fix, normal coffee comes out hot while atomic coffee has room temperature. With the added check, both recipes result in hot drinks.

### CODE REVIEW

**Comment by actual-nh** [comment]
Is the multi_cooker still working properly (the flag for it is "MULTICOOKER", not "HOTPLATE")?

**Comment by pehamm** [comment]
As far as I can see, this section of the code has only ever checked for hotplates. Are there recipes that can use the multicooker but not the plate?

**Comment by actual-nh** [comment]
> As far as I can see, this section of the code has only ever checked for hotplates. Are there recipes that can use the multicooker but not the plate?

Looks like all the food ones use the surface_heat or water_boiling_heat requirement, but I'm not sure if that works properly in this case since the atomic coffeepot is already listed under water_boiling_heat, admittedly with a -1 after it for some reason (as does "fire").

**Comment by Salty-Panda** [comment]
> admittedly with a -1 after it for some reason

It marks it won't be consumed as for crafting purposes it's infinite charges

**Comment by Saicchi** [comment]
Instead of adding another hardcoded itype, wouldn't it be better to check if the item has a flag instead that makes it return true?

**Comment by ZhilkinSerg** [comment]
^^

**Comment by actual-nh** [comment]
> > admittedly with a -1 after it for some reason
> 
> It marks it won't be consumed as for crafting purposes it's infinite charges

Oh, right, that confusing thing.

**Comment by pehamm** [comment]
> Instead of adding another hardcoded itype, wouldn't it be better to check if the item has a flag instead that makes it return true?

We cannot do this on the items as some of them have hot and cold recipes. You can make hot coffee with something that can boil water, coffee beans and water, or you can make cold coffee out of clean water and instant coffee mix.

We could add it to recipes, but it feels weirdly redundant to me as we can infer hotness from the tool list in each case except this specific one. Would like to hear other's opinions on that.

**Comment by Saicchi** [comment]
I meant give the hotplate and atomic coffemachine a flag, like "HEATFOOD" for example.

**Comment by pehamm** [comment]
I will take another look whether we can already infer hotness from JSON flags on the tool. If not, I will look into adding them, although I will most likely not get to this until the weekend.

**Pull request merged**
