### PR TITLE
Translate 10 strings to German (beverages)

### PR DESCRIPTION
**Pull request by Wuzzy2**
#### Summary
```SUMMARY: I18N "Translate 10 strings to German (beverages)"``` 

(this probably shouldn't be in the final changelog)

#### Purpose of change
What it says on the tin.

#### Describe the solution
As announced in <https://github.com/CleverRaven/Cataclysm-DDA/issues/27843>, I send you my first German translations for the upcoming 0.D release.

This is meant as a “warm-up”, so there are only 10 strings. Intentionally low-volume to test the waters.

If this PR gets accepted, I plan to send you daily PRs with about 100 translated strings each, until all of German is translated.

If this PR is rejected, please tell me a better way to send you translations as long it doesn't involve Transifex.

#### Describe alternatives you've considered
None.

#### Additional context
None.

### CODE REVIEW

**Comment by cainiaowu** [comment]
Someone need to update the transifex or this will get overwrite by the next translation update.

What I can think of is that someone in the German translation team to download a .po file with GE translation and send it to you, when you finished the work via local tool (poedit etc.) and uploaded back there.

**Comment by ZhilkinSerg** [comment]
>If this PR is rejected, please tell me a better way to send you translations as long it doesn't involve Transifex.

As outlined [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md), translations are done via Transifex. What is the reason behind not doing it proper way?

**Comment by Wuzzy2** [comment]
@ZhilkinSerg: See #27843.

@kevingranade: Please give feedback on whether this PR is OK.

**Comment by ZhilkinSerg** [comment]
That doesn't mean you should not use Transifex.

**Comment by nexusmrsep** [comment]
You should absolutely use Transifex at all times, with a miniscule exception of few places that can't be translated that way. It's a great service that keeps your data even after some drastic changes so you can come back to previous translations and work on them. Not to mention the periodic synch up. I cannot fathom even starting translating those 29000+ strings via other method then a professional tool and doing it manually is a major pain. From personal experience of a translator.

**Comment by Wuzzy2** [comment]
If it turns out using the proprietary Transifex website in my browser is mandatory and without alternatives, there will be no further German translations from me for 0.D. You can close this issue in that case. But I have my doubts that this is actually the case.

You can talk to me in IRC (my name is “Wuzzy”).

In the worst case scenario, I am willing to accept Launchpad as an “emergency” solution for 0.D, as suggested by kevingranade earlier. But I have no idea if it would actually work out for you.

**Comment by Wuzzy2** [comment]
Just to be clear: My refusal to use the Transifex website in my browser is non-negotiable (until it becomes usable without running any proprietary code).

Dumb question: Would it be possible to use the Transifex command-line client (`tx`) (https://github.com/transifex/transifex-client) to work on translations, as a translator? It looks like it's free software, so that might be an option.

I have experimented with `tx` a while, but I just can't figure out how it works. I can't pull files or anything. I'm stuck. Maybe someone with more experience with that tool could help me out here, please?

**Comment by ZhilkinSerg** [comment]
It would've been a little better for understanding if you've linked directly to your comment explaining why you do not use Transifex and not just a `0.D release` issue. Now that I've read the whole thread and found your explanation comment there I understand your choice not to use Transifex. Anyway my point is that we just need to make sure somebody will upload your translations to Transifex too (as we keep translations there).

**Comment by kevingranade** [comment]
Sorry for the confusion everyone, yes we'll need to sort out a workflow for this, which is why I haven't merged it.

**Comment by ZhilkinSerg** [comment]
So, I've tried [Transifex CLI](https://github.com/transifex/transifex-client/) on Windows and it works.

Should be basically the same on Linux, though I've used [precompiled binary](https://github.com/transifex/transifex-client/releases/download/0.13.6/tx.py36.x64.exe) and I am not sure if it fits you as you would need to register on Transifex.

# Rough instruction:

0. Clone Cataclysm repository (e.g. `C:\Projects\Cataclysm-DDA`).

1. Register and login on [Transifex](https://www.transifex.com/) (required to get API token). Can be done with Github account.

2. Generate Transifex API token [here](https://www.transifex.com/user/settings/api/) (if you have non yet).

3. Get `tx` client as outlined [here](https://github.com/transifex/transifex-client/#installation).

4. Go to Cataclysm repository (e.g. `C:\Projects\Cataclysm-DDA`) and run `tx init`.

```
 _____                    _  __
|_   _| __ __ _ _ __  ___(_)/ _| _____  __
  | || '__/ _` | '_ \/ __| | |_ / _ \ \/ /
  | || | | (_| | | | \__ \ |  _|  __/>  <
  |_||_|  \__,_|_| |_|___/_|_|  \___/_/\_\


Welcome to the Transifex Client! Please follow the instructions to
initialize your project.

tx INFO: Creating .tx folder...
tx INFO: Creating config file...
tx INFO: Running tx config command for you...
tx INFO: No credentials file was found at C:\Users\%USERNAME%\.transifexrc.
tx INFO: Created C:\Users\%USERNAME%\.transifexrc
[?] Enter your api token: 1/%YOUR_API_TOKEN%
Verifying token...
tx INFO: Updating C:\Users\%USERNAME%\.transifexrc file...
```

5. Enter path to local source file:

```
[?] Enter the path to your local source file: C:\Projects\Cataclysm-DDA\lang\po\cataclysm-dda.pot
```

6. Enter path to translation files:

```
[?] Enter a path expression: C:\Projects\Cataclysm-DDA\lang\po\<lang>.po
```

7. Select `PO File` format:

```
  1. PO File - .po, .pot

[?] Select the file format type [1]: 1
```

8. Select `Cataclysm-DDA translators` organization:

```
  1. Cataclysm-DDA translators

[?] Select the organization to use [1]: 1
```

9. Select `Cataclysm-DDA` project:

```
We found these projects in your organization.
  1. Cataclysm-DDA
  2. Create new project (show instructions)...

[?] Select the project to use [1-2]: 1
```

10. You will receive following output:

```
tx INFO: Updating source for resource cataclysm-dda.cataclysm-dda-pot ( en -> lang\po\cataclysm-dda.pot ).
tx INFO: Setting source file for resource cataclysm-dda.cataclysm-dda-pot ( en -> lang\po\cataclysm-dda.pot ).
tx INFO: Updating file expression for resource cataclysm-dda.cataclysm-dda-pot ( C:\Projects\Cataclysm-DDA\lang\po\<lang>.po ).

Here’s the content of the .tx/config file that was created:

    [cataclysm-dda.cataclysm-dda-pot]
    source_file = lang/po/cataclysm-dda.pot
    file_filter = lang/po/<lang>.po
    source_lang = en
    type = PO

You could also have generated the same configuration by running a single command like:

    tx config mapping -r cataclysm-dda.cataclysm-dda-pot -f lang/po/cataclysm-dda.pot -s en -t PO 'lang/po/<lang>.po'
```

11. Edit `C:\Projects\Cataclysm-DDA\.tx\config` file from

```
[main]
host = https://www.transifex.com

[cataclysm-dda.cataclysm-dda-pot]
file_filter = lang/po/<lang>.po
minimum_perc = 0
source_file = lang/po/cataclysm-dda.pot
source_lang = en
type = PO

```

to

```
[main]
host = https://www.transifex.com

[cataclysm-dda.master-cataclysm-dda]
file_filter = lang/po/<lang>.po
minimum_perc = 0
source_file = lang/po/cataclysm-dda.pot
source_lang = en
type = PO
```

12. Alternatively to steps 5-11 run following command:

```
tx config mapping -r cataclysm-dda.master-cataclysm-dda -f lang/po/cataclysm-dda.pot -s en -t PO 'lang/po/<lang>.po'
```

13. Run `tx pull` and see successful output:

```
tx INFO: New translations found for the following languages:ar, nl, sr, it_IT, nb, el, is, uk_UA, pt_BR, da, tr
tx INFO: Pulling translations for resource cataclysm-dda.master-cataclysm-dda (source: lang\po\cataclysm-dda.pot)
tx INFO:  -> zh_TW: lang\po\zh_TW.po
tx INFO:  -> ko: lang\po\ko.po
tx INFO:  -> hu: lang\po\hu.po
tx INFO:  -> ru: lang\po\ru.po
tx INFO:  -> zh_CN: lang\po\zh_CN.po
tx INFO: Skipping 'fr' translation (file: lang\po\fr.po).
tx INFO:  -> ja: lang\po\ja.po
tx INFO:  -> pl: lang\po\pl.po
tx INFO: Skipping 'es_AR' translation (file: lang\po\es_AR.po).
tx INFO: Skipping 'de' translation (file: lang\po\de.po).
tx INFO: Skipping 'es_ES' translation (file: lang\po\es_ES.po).
tx INFO: Pulling new translations for resource cataclysm-dda.master-cataclysm-dda (source: lang\po\cataclysm-dda.pot)
tx WARNING:  -> ar: lang\po\ar.po
tx WARNING:  -> nl: lang\po\nl.po
tx WARNING:  -> sr: lang\po\sr.po
tx WARNING:  -> it_IT: lang\po\it_IT.po
tx WARNING:  -> nb: lang\po\nb.po
tx WARNING:  -> el: lang\po\el.po
tx WARNING:  -> is: lang\po\is.po
tx WARNING:  -> uk_UA: lang\po\uk_UA.po
tx WARNING:  -> pt_BR: lang\po\pt_BR.po
tx WARNING:  -> da: lang\po\da.po
tx WARNING:  -> tr: lang\po\tr.po
tx INFO: Done.
```

Translations are updated locally:

image

I am not sure about `tx push` - you will probably need some additional access right in organization/project on Transifex site.

**Comment by Wuzzy2** [comment]
Thanks a lot for your write-up, but sadly, step 2 is a show-stopper as the website breaks down at this point. It does not display the API token. Apparently I cannot proceed without executing proprietary JavaScript code. Is there a different way to query my API token?

**Comment by ZhilkinSerg** [comment]
None, that I am aware of - https://docs.transifex.com/api/introduction#authentication tells the only way to go to settings.

Though it also tells:

```
Transifex requires all requests to the API to be authenticated through HTTP Basic Auth. The credentials to access the API are the same as the username and password you use to log into Transifex.
```

So you can probably try using your Transifex credentials, but if you are using non-Transifex credentials - you are out-of-luck again:

```
If you signed up for Transifex using social login, i.e. GitHub, Google, or LinkedIn, then your Transifex account won’t have a password associated with it by default. You can generate or change your password through your [account settings page](https://www.transifex.com/user/settings/password/).
```

**Comment by cainiaowu** [comment]
Well, you can pass the translated. po to other people in the GE translation team to upload it for you. 

Upload will override any modified strings so you need to work upon the current .po file.

**Comment by Wuzzy2** [comment]
@cainiaowu: Can you give me the contact data of those people, please?

**Comment by cainiaowu** [comment]
Well, I have no idea. But judging from the Transifex/Github recent activity, you may need to find https://www.transifex.com/user/profile/pupsi/ .

**Comment by BrettDong** [comment]
You may send your .po file to me and I can merge them with Transifex version on my machine

**Comment by Wuzzy2** [comment]
@BrettDong: Thanks, I sent you an e-mail.

**Comment by Wuzzy2** [comment]
After searching around in the Transifex API docs for hours, I finally managed to figure out how to download and upload PO files without executing any proprietary code! Yay!

The workflow requires you to have a Transifex account with username and password, be a member of the `cataclysm-dda-translators` organization on Transifex. And you need the command-line utility `curl`.

From now on, my workflow for any translation session will be:
- Download PO file
- Translate strings in PO file
- Upload PO file immediately when my session is complete

This workflow has been tested and verified with 4 mini translations.

Download PO file from the command-line (you must replace the parts enclosed in the lower-than and greater-than signs):

```
curl -i -L --user <USERNAME>:<PASSWORD> -X GET https://www.transifex.com/api/2/project/<PROJECT>/resource/<RESOURCE>/translation/<LANGUAGE_CODE>?file=po -o <DOWNLOAD_FILENAME>
```

Note: The file have a HTTP header, which you need to remove manually first.

Upload PO file from the command-line:
```
curl -i -L --user <USERNAME>:<PASSWORD> -F file=@<PATH_TO_YOUR_PO_FILE> -X PUT https://www.transifex.com/api/2/project/cataclysm-dda/resource/master-cataclysm-dda/transl    ation/<LANGUAGE_CODE>/
```

If the upload succeeded, the server will tell you in a JSON file some stats about the updated strings.

I will close this issue soon when I run in no further problems.

**Comment by Wuzzy2** [comment]
Slightly OT.
@BrettDong: Lol. Apparently in German, someone translated all dollar signs into Euro signs (€). xD
I will fix this in my next translation session. Please notify whoever is responsible for the euro signs that C:DDA plays in New England, so it really must be the dollar sign.

**Comment by kevingranade** [comment]
I am amazed.  Also I'm very happy you can contribute again in a way that requires no compromises.

**Comment by Wuzzy2** [comment]
Yes, it's a bit clunky for me to do, but it works. I can myself lucky I'm a programmer myself so I know how to get around this huge API. It would be highly impractical for any non-technical people.
It's still a compromise, somewhat, because I lost access to the glossary and the commenting system for which I am sure there is also some sort of API but it would be highly impractical to do all that stuff with `curl`. It's not a big loss, however.

I want to stress this is NOT a long-term solution. But this is exactly what I needed for now.

Anyway, the 10 strings have been successfully pushed to Transifex now and I'm now in full translation mode. Closing.

**Pull request closed without merging**
