### PR TITLE
[WIP][On Hold] Add spicy flag and spice intolerance trait

### PR DESCRIPTION
**Pull request by Cyrano7**
Added spicy flag and spice intolerance trait. Works a lot like the other intolerance traits. I might add some slight pain to it also. Right now its set to a starting trait but I might take it and throw it into some mutation trees as most animals can't eat spicy things. There is not a ton of spicy stuff right now but i'll be adding a few more spicy recipes/food soon so I thought Id finish this first. 
My Issue as a reference https://github.com/CleverRaven/Cataclysm-DDA/issues/14530

### CODE REVIEW

**Comment by Zireael07** [comment]
Great!

**Comment by Coolthulhu** [comment]
At the moment the trait is pretty much a free point. It shouldn't be a starting trait until it means something.

**Comment by Core0verload** [comment]
Do we really need more intolerance traits?

**Comment by hitbutton** [comment]
You haven't addressed the point I raised in the issue. There is no way for a player to easily determine whether or not a food is spicy. Since you are doing this with a flag, You should make that flag add a line to the item description of spicy food which explicitly states the food is spicy.

**Comment by AppleConnoiseur** [comment]
Hehe, maybe have Spice Tolerance as positive flag.
Can eat food like canned chili, meat preserved with strong spices (Could be easier than jerky to make) and even eat peppers raw without a negative morale modifier and chance of upset stomach.
Could even lead to spice addiction if you eat enough spicy food.

To make this trait more useful\needed i guess there can be houses which mainly have spicy food to be looted. (Young adults live there) Even have restaurants that got Indian and Asian food with a variety spicy food.
If city generation becomes sophisticated enough there can be districts where a area is "China Town" and the like.

Also more cooking books can be added with more recipes :D. "Curries 101" "Stories of a Thailand street vendor" "Dragon Cooking"

**Comment by Cyrano7** [comment]
@Coolthulhu yes It would be a free point at this point. I was more thinking about adding It to just the mutant trees or just keeping it in the code for now. It would then be easy to just flag new spicy food as there added. I was thinking of adding some pain to it as a little something extra for the staving spicy intolerant as the people I know who have this irl get pretty messed up if they have anything spicy.

@Core0verload yes the more ways you can mess up your genetics and get sick the better. That's just my opinion though.

@hitbutton Yes I was planing I line under where the perishable foods thing comes up. Ran out of time last night though. And then forgot to write it up top. We could always let people use their common sense to though.

@AppleConnoiseur That's an idea. But it would kinda be like adding a gluten tolerant trait. I LOVE spicy food and it makes me happy but my dad has stomach ulcers and spicy food really messes things up for him. Those things aren't quite opposites.

**Comment by Cyrano7** [comment]
@AppleConnoiseur Id like to add that we need "Stories of a Thailand street vendor" in the game though.

**Comment by hitbutton** [comment]
> We could always let people use their common sense to though.

"Common sense" here would mean a mixture of cultural knowledge and second-guessing the JSON writers.

For example:
Is a chili dog spicy? I couldn't even tell you what a chili dog looked like without using google.
Is the game item "curry" spicy? There are many different kinds of curry which range from not spicy at all (korma/mughlai) to extremely spicy (phal/madras)

**Comment by Cyrano7** [comment]
@hitbutton that's a good point.

**Comment by Zireael07** [comment]
What mutation trees might get the spicy intolerance?

**Comment by Cyrano7** [comment]
The only thought i've put in to it was that animals like cats and dogs and some others are sensitive to strong smells and spicy or acidic foods. Id change the description if I went that route though. I might leave this WIP for a bit and add some more spicy foods.

**Pull request closed without merging**
