### PR TITLE
All the Realism: Drinks Edition, The Alcohol Chapter

### PR DESCRIPTION
**Pull request by roaringjohn**
#### Summary 
SUMMARY: Content "Add more alcoholic drinks that make realistic sense"

#### Purpose of change

Add more alcohol which has been missing from CDDA.

#### Describe the solution

Add more alcohol.

#### Describe alternatives you've considered

Don't add more alcohol.

#### Additional context

The numbers may need to be changed.

### CODE REVIEW

**Comment by AMurkin** [comment]
[Lint](http://dev.narc.ro/cataclysm/format.html) your changes.

**Comment by roaringjohn** [comment]
I already made sure they were linted before I made the PR.

**Comment by Night-Pryanik** [comment]
Could you please also update the `alcohol` and `alcohol_bottled_canned` item groups located in `item_groups.json`? And maybe other appropriate item groups in this file?

**Comment by roaringjohn** [comment]
New fork due to commit mishaps in my fork's master

**Pull request closed without merging**
