### PR TITLE
Added deodorant and ability to modify your scent strength

### PR DESCRIPTION
**Pull request by FuelType-Memes**
#### Summary

SUMMARY: Content "Adds deodorant and modifies current method of scent masking"

#### Purpose of change

#36160 added the ability to mask your scent by switching your scent_id. I reused this and modified the scent masking calculation to be percentage-based

#### Describe the solution

Added effect intensity to masked_scent and modified the equation to be percentage-based. Now if you want to decrease your scent by 20% you need to set intensity to 20

#### Describe alternatives you've considered

Rewriting code to include the ability to boost scent. I came to the conclusion that because current implementation specifically implies masking scent it should only support decreasing or masking your odor completely. I believe there is room for a much more complex system for scent modification, that is out of scope of this PR

#### Testing

Compiled, spawned the item and activated it. 
Used the debug menu to show the scent map
Waiting for a couple of minutes leads to a decrease in scent intensity. Modified masking intensity to 90%, scent radius dropped dramatically

#### Additional context

I hope this leads to addition of perfumes and other scented items, maybe I'll add some in the future

### CODE REVIEW

**Comment by Fris0uman** [comment]
You need to edit the documentation to reflect your changes to mask_intensity, in JSON_INFO.md

**Comment by kevingranade** [comment]
This has come up a number of times before, and as far as I have been able to determine, ordinary deodorants and perfumes do not have this effect.  i,e, the new scent is present, but that doesn't change the fact that the old scent is present as well, and if an animal is scent-aware enough to track you by scent in the first place, they're scent-aware enough to ignore the new scent as necessary.  This would be fine for a mod, but I want to be clear that it's not ok for mainline.

**Comment by FuelType-Memes** [comment]
> 
> 
> This has come up a number of times before, and as far as I have been able to determine, ordinary deodorants and perfumes do not have this effect. i,e, the new scent is present, but that doesn't change the fact that the old scent is present as well, and if an animal is scent-aware enough to track you by scent in the first place, they're scent-aware enough to ignore the new scent as necessary. This would be fine for a mod, but I want to be clear that it's not ok for mainline.

I'm sorry but that means that the current implementation of "fetid_goop" is wrong as it completely changes your scent, while this PR imitates how deodorants kill bacteria and reduces your sweating

[Human perspiration of all types is largely odorless until its organic components are fermented by bacteria that thrive in hot, humid environments. The human underarm is among the most consistently warm areas on the surface of the human body, and sweat glands readily provide moisture containing a fraction of organic matter, which when excreted, has a vital cooling effect. When adult armpits are washed with alkaline pH soap, the skin loses its protective acid mantle (pH 4.5–6), raising the skin pH and disrupting the skin barrier](https://en.wikipedia.org/wiki/Deodorant#Overview)

**Comment by Zireael07** [comment]
Yeah, if this is mod-content, then the goop is even more so.

**Review by kevingranade — CHANGES_REQUESTED** [review]
To be clear, this is not ok as long as it's applying a scent masking effect to mundane items like deodorant.

**Comment by FuelType-Memes** [comment]
I think I don't understand both your request and your comment about "deodorant" being mundane

If you're against the whole idea of any scent modification, then this PR should be closed and "fetid_goop" should be removed
If you're against scent "masking" then this PR doesn't introduce items that switch your scent. You still keep default "sc_human" you just smell 10% less because deodorant keeps PC from sweating and kills off bacteria

**Comment by Fris0uman** [comment]
For the mundane part it's that fetid goop is some alien substance found in dangerous place and has some downsides. Deodorant on the other hand is a real item that must adhere to its real life properties. I don't know if reducing scent intensity is credible or not though, it doesn't sound crazy to me.

**Pull request closed without merging**
