### PR TITLE
Few food recipe fixes and balances

### PR DESCRIPTION
**Pull request by atealein**
#### Summary
Bugfixes "Few recipe fixes and a new quick veggy salad recipe"

#### Purpose of change
I have gathered few different issues in this PR. Not sure this is very common but I'll put a list so it is more clear. Few are bug fixes (one food item was appearing instead as drinks in the consume menu), few are balances and addition to new alternative ingredients, there is a new alternative veggy_salad recipe that uses food processor and has much faster preparation time. Lastly, there is an id change for all the different nuts which id before was _unshelled when the description and use was actually as _shelled. This change has been added to the migration as well.

#### Describe the solution

1. New vegetable salad recipe that uses a tool (food processor) and thus can prepare salad much faster and with great batch saving time.
2. ~~Beet syrup preparation recipe can now take advantage of some batch saving time since it is basically cooking and concentrating sugar beet juice and this doesn't have to happen consecutively one beet after another.~~ this has been reversed. See explanation in comments.
3. All flour recipes can now use alternative ingredient chestnut_roasted to prepare flour; also the quantity of acorns needed to prepare flour have been upgraded from 2 to 10 because otherwise we are somehow making 0.20 kg flour from 0.04 kg acorns.
4. Leverpastej is no longer appearing as DRINK but as FOOD in the consume item menu.
5. All nuts with suffix _unshelled are now instead _shelled. This is due to both their description and use listing them as having shell already removed. These changes required changes in number of files that list the nuts as potential items, deconstruction recipes, etc. The id change is added to the migration.json too.  

#### Describe alternatives you've considered
I considered leaving the misleading item_ids as is, since this is the way they were submitted originally. It was recommended that it might prevent confusion in later stages if it is fixed now. 

#### Testing
Copied the changed json files to an existing game and checked ingame if the recipes are available.

### CODE REVIEW

**Comment by RelMayers** [comment]
Beet Syrup should not have batch saving time

**Comment by atealein** [comment]
> Beet Syrup should not have batch saving time

Why? The preparation of the extra portions take some extra time, but if you are boiling 10 liters of water it doesn't take 10 times the time of boiling 1 liter of water as long as your heat source can provide more energy?

**Comment by Maleclypse** [comment]
If this fixes existing issues please write “Fixes #xyz” somewhere in the summary. For each issue it will close.

**Comment by atealein** [comment]
I've reversed the sugar beet recipe batch save time to none and going to write a quick argument why. My original argument was that once the water boils, the beets cook for a time and that time will depend on the beets and won't change if there are more cooking or less at the same time. This argument would generally work well for making for example batches of soups and so on recipes where you "cook until ready". However, in the case for the syrup, you actually don't boil it until the beets are ready, you boil it until the water boils out.

**Pull request merged**
