### PR TITLE
Fixes office building's stairs

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
Stairs missing from roof, don't line up downstairs

#### Describe the solution
Adds a couple of roof nests while I were at it

#### Describe alternatives you've considered
Adding another floor seeing as it's called a tower

#### Testing
Spawned one in and checked it lined up

### CODE REVIEW

**Comment by Maleclypse** [comment]
Ooh are the xedra government offices having the same issue?

**Comment by Procyonae** [comment]
> Ooh are the xedra government offices having the same issue?

I'll check tomorrow, if this could get merged asap that would be cool bc I'm somehow stuck on this branch and can't escape >~<

**Comment by Procyonae** [comment]
I'm not sure which you mean but I spawned all the specials that have "office" in their name and they all seemed fine

**Comment by Maleclypse** [comment]
> > Ooh are the xedra government offices having the same issue?
> 
> I'll check tomorrow, if this could get merged asap that would be cool bc I'm somehow stuck on this branch and can't escape >~<

Just saw this now.  For faster service always ping me in discord.

**Pull request merged**
