### PR TITLE
Make the delayed player spawn a toggled option

### PR DESCRIPTION
**Pull request by ianestrachan**
#### Summary
```SUMMARY: Features "Allow starting at a non-default date without advancing rot and monster scaling"```

#### Purpose of change
Addresses #28000, sorta.

Currently the option to change the starting season warns the player that starting at a date other than the default will advance the state of the world by delaying the player spawn; monsters will evolve and perishable items will rot. This means that to play the game and not make things harder on yourself, you have to start in spring, which means dealing with freezing cold weather. Since this is the default option it makes an unnecessarily difficult experience, particularly for new players, who have to deal with food and drink freezing solid in addition to the potential dangers of frostbite.

This PR replaces the "Initial Season" option with "Initial Day", and makes it so that food and monster spawns begin at the same time the game begins. So even if you start the game in Fall 1, food is fresh (relative to Fall 1) and monsters have not scaled up. It's as if the cataclysm happened at the end of July instead of the end of December.

#### Describe the solution
In the specific cases where `calendar::time_of_cataclysm` is used as a zero-date for determining elapsed time for food spoilage and monster scaling, calendar::start is used instead, which is the in-game start time.

#### Describe alternatives you've considered
I could have fudged the values of calendar::time_of_cataclysm and calendar::start directly, but this might have far-reaching consequences that would be difficult to predict, and might also mess with mods. Patching the specific cases of food rot and monster scaling was much easier and less likely to have unforeseen side-effects.

#### Additional context
I have tested this locally with the flag on and with it off, by creating new worlds starting in Fall or Winter, and immediately using debug commands to teleport into grocery stores to check the food spoilage state. With the flag set to `true` many foods are spoiled; with it set to `false` everything is as fresh as can be. (Teleporting into cities also lets me check monster scaling, which is a lot less precise to tell at a glance, but does seem to be affected)

~This likely breaks the intended balance of scenarios that start the player later in the year or in the next year delayed spawn is disabled and those scenarios are used, but I feel that that is a self-induced problem since the flag defaults to true.~ Scenarios are unaffected as they hard-override the starting time and elapsed time since the start of the cataclysm.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
The goal is actually to make "date of the cataclysm" and "game start date" two independent variables you can set in options. I don't suppose you could expand this to work that way?

**Comment by ianestrachan** [comment]
Theoretically, yes; it would just mean changing the values of `calendar::time_of_cataclysm` and `calendar::start` which are both just points in time (defaulting to 0 and 8 hours in respectively). I'm just not sure offhand how far-reaching the consequences of fiddling with those to values would be, though calendar::start is currently adjusted by the starting month and time options.

It would also need some sanity checks to make sure you don't set the start date before the cataclysm date. Which, effectively, means you're just choosing the amount of time that has elapsed since the cataclysm. So perhaps instead of this on/off flag, the actual configured value on the world creation screen is how much time (days? months?) has elapsed since the cataclysm. This would allow you to start years later, which you currently can't do except in that one scenario that starts you in the next summer.

**Comment by kevingranade** [comment]
The two options can be "start of cataclysm", either as an offset into the year (0-365 days?) or by choosing a month or season and "time since cataclysm", which should only be set by scenario, because otherwise it makes things wildly inconsistent.

**Comment by ianestrachan** [comment]
Sounds good to me, though year lengths are configurable so hardcoding the limit to 0-365 probably isn't a good idea. A simple sanity check and/or sane default should suffice.

Going to put a WIP tag on the title (I can't seem to mark as WIP a PR that wasn't created as one, please correct me if I am wrong) in the meantime.

Also I think backwards compatibility comes for free because I believe that both `time_of_cataclysm` and `start` get saved/loaded with the save files.

**Comment by ianestrachan** [comment]
As it turns out, modifying `calendar::time_of_cataclysm` is impossible (and should likely remain so) because it's a `const time_point` unlike `calendar::start` which is a `calendar` and can thus be modified.

New plan: Scenarios will override the starting time configured in the world setting as they do currently in master (since they refer to explicit times like "the next summer").
If no scenario overrides the start, then the configured day+time is used, and all food is spawned in fresh at the start of the game.

I have replaced the "Initial season" option with "Initial day", allowing for finer control over the start time.

**Comment by ianestrachan** [comment]
This PR is almost done, but I'm currently stuck on a very strange bug - if a player has it set so that their spawn is delayed relative to the beginning of the cataclysm, and they start the game with perishable items, those items appear fresh but rot as soon as a turn passes.

As far as I can tell from the debugger, even if I set the item's birthday when it gets added to the character's inventory in newcharacter.cpp#player::create, by the time the rot check rolls around the item's birthday has been set back to 0 by something. Yet even with a breakpoint in the set_birthday function, I cannot find what it setting it back to 0. It doesn't seem to be the no-arg item constructor, and bday is private and the few references to it don't seem to be being called either (I put a breakpoint on all of the ones Code::Blocks found).

Anyone with more experience have some idea of what might be going on here?

**Comment by ianestrachan** [comment]
I have confirmed that the bug mentioned above is in fact a bug in the current master and was not introduced by my code. I have opened #29037 to capture that bug, and other than that I believe this PR is ready to be merged. I have tested it in the following manner:

* Created a new world with the time of cataclysm advanced two months, and made a new character in it. The date is Fall 1. I debug-teleported into a grocery store, gave myself maxed-out Survival, and looked around; everything was as fresh as could be. I wished for the ingredients to a meat sandwich and made it to confirm that crafting still worked as intended.
* Wiped the world, created another one where the player's spawn is delayed two months but the cataclysm date is still day 0. Debug-teleported to a grocery store again and observed that perishable food had rotten. I wished for meat sandwich ingredients again and made one to confirm that crafted food works as intended.

Along the way I discovered a rather minor and obscure bug that wished-for food would have a birthday of 0, and thus be rotten if you were far enough into the game. Since people generally don't play the game for months and then start using debug cheat commands, it's easy to see why this went under the radar.

**Pull request merged**
