### PR TITLE
Routine i18n updates on 20 August 2022

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Additional context
`Translation file changes are intended`

### CODE REVIEW

**Comment by BrettDong** [comment]
I have no idea why `msgfmt` outputs in a different MO format version starting from this week and only for `uk_UA.po`.

**Comment by BrettDong** [comment]
The GNU gettext documentation (https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html) only mentions MO format revision `Major=0x0, Minor=0x0`. MO format revision `Major=0x1, Minor=0x1` is not documented and I don't know if it is safe to parse the `uk_UA.mo` in the different format revision with our current code.

**Comment by EIIKaO** [comment]
Different of version number is seems to be caused by a typo (I don't know the mechanism).

Replace text `msgstr "невідома клавіша %Id"` in uk_UA.po:429575  to `msgstr ""` or delete the wor `%Id` then revision was recovered.

**Comment by BrettDong** [comment]
Corrected `%ld` on Transifex and force-pushing on GitHub side.

**Review by BrettDong — APPROVED** [review]
The MO format version problem is resolved. Basic build test is passing again.

**Pull request merged**
