### PR TITLE
Implement Daily health vs Lifestyle system

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Balance "Implement Daily health vs Lifestyle system"

#### Purpose of change

Implement Daily health vs Lifestyle system
Part of #37446

#### Describe the solution
- Rename `healthy_mod` to `daily_health`
- Rename `healthy` to `lifestyle`
- Add `health_tally` variable
- Every 24h add  either `EFFECTIVE_HEALTH_MOD` or `daily_health` to `health_tally`
- Every 24h add `health_tally / 7` to `lifestyle`, effectively your mean `daily_health` on a rolling 7 days
- `lifestyle` controls healing and getting sick just as before

- Radiation effect on health only happens once into suffer
- Enchantment effect on `daily_health` is moved to suffer

#### Testing

Not sure how to test it properly

#### Additional context
In this implementation `lifestyle` does not decay, it will keep going up toward 200 as long as you have a postivie `health_tally`

### CODE REVIEW

**Comment by Zireael07** [comment]
Some questions (without me looking at code): what increases lifestyle and what decreases it? How do things like body weight/exercise factor in?

**Comment by Fris0uman** [comment]
This just changes the rate of change but doesn't add any new health interaction. So thing that affect health affect daily_health and once a day your mean daily_health over the past 7 days gets added to your lifestyle.

**Comment by Amoebka** [comment]
Now that food is limited to [-1;0] and none of those methods of getting health up from the linked issue are implemented, wouldn't helath just keep dropping forever, because nothing offsets the occasional -1s from candy? This would leave experimental in a somewhat unplayable state until the follow up prs are merged.

**Comment by Zireael07** [comment]
@Amoebka Many other features were merged without being totally complete (pockets, for instance!) and were then expanded/fixed in follow up PRs. This is, actually, a case of something that seems nearly impossible to balance without people actually playing with the change, so...

**Comment by I-am-Erk** [comment]
So reviewing my old math, I think that `health_tally` needs to decrease by the amount that `lifestyle` is adjusted by: this effectively "removes the oldest day" from the 7 day tally and lets it continue moving forward for the next day, so that `health_tally` doesn't infinitely compound.

@Amoebka in the near term, health from food should be handled more by vitamins than by a health score. So, if you eat a decent amount of vitamins in a day, you get a small health bonus, and if you eat a lot of junk food, you get a small penalty.

Once we have a few of the proposed health modifiers in place we can remove the thing where `daily_health` trends towards zero, I believe, and it will instead trend towards a neutral-ish number based on your activities.

**Comment by fungamer2-2** [comment]
You also want to ensure that `health_tally` is also saved and loaded with the game so that it doesn't get reset to 0 every time a save a loaded

**Pull request merged**
