### PR TITLE
[READY] Astyle campaign 1

### PR DESCRIPTION
**Pull request by kevingranade**
Updated stye settings as discussed in #13873 and re-astyled with a later version of astyle that understands c++11 syntax.

### CODE REVIEW

**Comment by BevapDin** [comment]
Should there be a fixed style for placing the `const`?

```C++
const std::string &get();
// vs.
std::string const &get();

const auto foo = some_map.find(...);
// vs.
auto const foo = some_map.find(...);
```

----

About the comments for things like `SEEY`: they should be put *before* the object they comment and into a single multiline-comment. That way they can be detected by doxygen.

Even without considering doxygen, this look very strange:
```C++
// SEEX is how far the player can see in the X direction (at
#define SEEX 12 // least, without scrolling).  All map segments will need to be
// at least this wide. The map therefore needs to be 3x as wide.
```
The comment "flows" all around the object it's commenting on.

But this can not be handled by astyle and needs some manual interaction.

**Comment by Coolthulhu** [comment]
> Should there be a fixed style for placing the const?

Yes please
I'm fine with either option (though I'd prefer type being the last)
Also, static vs const

**Comment by BevapDin** [comment]
CONTRIBUTING.md contains similar astyle commands, they should probably be changed as well, or replaced with a link to doc/CODE_STYLE.md

> Also, static vs const

You mean `static` before the type or between type and identifier? That could be codified as well.

**Comment by Coolthulhu** [comment]
> You mean static before the type or between type and identifier?

This, but also `static` and `const` in one line (most statics are `const`, I think).

**Comment by Coolthulhu** [comment]
Not sure how to solve this conflict - was this function removed?

**Comment by kevingranade** [comment]
Astyle doesn't have a way to correct or detect ordering of type modifiers (const, static, etc).
AFAICT this is all the options: http://astyle.sourceforge.net/astyle.html

I'd prefer const to come before the typename, e.g. ```const int varname;```, the other way around is something c++ did and I frankly don't see the point of allowing it in either order.

I'd be perfectly happy saying "no comments after other statements", it's never necessary.

As for conflicts, if they crop up it's by far easier to just redo the astyling.

**Comment by kevingranade** [comment]
Bump for "please don't make me do this merge again".

**Comment by Rivet-the-Zombie** [comment]
I've got this, @kevingranade.

**Pull request merged**
