### PR TITLE
Hairdresser bugfix

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary
```SUMMARY: Bugfixes "Vanessa Toby's infinite loop possibility is fixed"```

#### Purpose of change
https://github.com/CleverRaven/Cataclysm-DDA/issues/31075 highlighted that Vanessa has a conversation option with no back/done breaks.

#### Describe the solution
I added talk_none and talk_done to her options in that topic.

#### Describe alternatives you've considered
I considered adding the entire table of contents to that topic but I think it's a bit messy looking

### CODE REVIEW

**Comment by jbytheway** [comment]
Is this the sort of flaw in conversation logic that could be detected programmatically?  Should we add something in the data loading logic that sanity-checks conversations to catch such issues?

**Comment by I-am-Erk** [comment]
I would think it would be doable with a test that goes through conversation options and makes sure there are no responses that:
- lead to talk_topic IDs that haven't been written (super easy and I don't think it exists
- Produces an infinite loop (harder, because it could be a multi stage loop)

**Comment by jbytheway** [comment]
You might also want a check for unreachable topics.

**Comment by I-am-Erk** [comment]
Yeah, that's not unreasonable. I can see infrastructural reasons to add unreachable topics (to be integrated later eg. when a mission is finalized) but it's something that can be worked around and it would identify legit errors.

**Comment by jbytheway** [comment]
Should I create an issue?

**Comment by I-am-Erk** [comment]
If you like. I could try too but I won't get to it probably until tomororw

**Pull request merged**
