### PR TITLE
Avoid divide by zero in vehicle::print_fuel_indicator

### LINKED ISSUE #64407: SIGFPE crash in `vehicle::print_fuel_indicator`
### Describe the bug

Attempting to `e`xamine a vehicle results in a SIGFPE ("Arithmetical error") and a crash to desktop.

### Attach save file

[NoHope-2023-03-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11016717/NoHope-2023-03-trimmed.tar.gz)

### Steps to reproduce

1. <s>Open the attached save</s>
2. <s>`e`xamine the adjacent vehicle</s>

Theory is a weird wreck that doesn't survive a load/save cycle, so:

1. Create a new NoHope game
2. Find and `e`xamine a couple of wrecks.

### Expected behavior

Examining a vehicle does not crash the game.

### Screenshots

_No response_

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-726-gc1e8d78dbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Hope [no_hope]
]
```

Version is b738ae2c6315ed81f56f84d8a7b5479d9f7f1de9 (`cdda-experimental-2023-03-20-0422`) with local patches applied, none of which impact vehicles.

### Additional context

Crash log:

```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/pjf/.cataclysm-dda/config/crash.log
VERSION: 0.G-726-gc1e8d78dbb
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x24) [0x1505a83]
    ./cataclysm-tiles() [0x14e6730]
    ./cataclysm-tiles() [0x14e641e]
    /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7fbd418860c0]
    ./cataclysm-tiles(vehicle::print_fuel_indicator(catacurses::window const&, point const&, string_id<itype> const&, std::map<string_id<itype>, units::quantity<long, units::energy_in_millijoule_tag>, std::less<
string_id<itype> >, std::allocator<std::pair<string_id<itype> const, units::quantity<long, units::energy_in_millijoule_tag> > > >, bool, bool)+0x267) [0x22265f7]
    ./cataclysm-tiles(vehicle::print_fuel_indicators(catacurses::window const&, point const&, int, bool, bool, bool, bool)+0x106) [0x2226102]
    ./cataclysm-tiles(veh_interact::display_stats() const+0x1611) [0x21b422f]
    ./cataclysm-tiles() [0x21bde6b]
    ./cataclysm-tiles(ui_adaptor::redraw_invalidated()+0x1c2) [0x2190a8e]
    ./cataclysm-tiles(veh_interact::do_main_loop()+0xe3) [0x219d9bf]
    ./cataclysm-tiles(veh_interact::run(vehicle&, point const&)+0x20) [0x219d8a8]
    ./cataclysm-tiles(game::exam_vehicle(vehicle&, point const&)+0x61) [0x16a0317]
    ./cataclysm-tiles(veh_menu::query()+0x3e9) [0x21e1ba7]
    ./cataclysm-tiles(vehicle::interact_with(tripoint const&, bool)+0xba) [0x2251e34]
    ./cataclysm-tiles(game::examine(tripoint const&, bool)+0x30c) [0x16a5a4e]
    ./cataclysm-tiles(game::examine(bool)+0x21d) [0x16a54bb]
    ./cataclysm-tiles(game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x3a20) [0x172ce34]
    ./cataclysm-tiles(game::handle_action()+0x2fb) [0x173cf7d]
    ./cataclysm-tiles(do_turn()+0x889) [0x158defd]
    ./cataclysm-tiles(main+0x1206) [0x1a2d2aa]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    crash.cpp:?
    ??
    ??:0
    vehicle::print_fuel_indicator(catacurses::window const&, point const&, string_id<itype> const&, std::map<string_id<itype>, units::quantity<long, units::energy_in_millijoule_tag>, std::less<string_id<itype> >, std::allocator<std::pair<string_id<itype> const, units::quantity<long, units::energy_in_millijoule_tag> > > >, bool, bool)
    ??:?
    vehicle::print_fuel_indicators(catacurses::window const&, point const&, int, bool, bool, bool, bool)
    ??:?
    veh_interact::display_stats() const
    ??:?
    std::_Function_handler<void (ui_adaptor&), veh_interact::create_or_get_ui_adaptor()::$_8>::_M_invoke(std::_Any_data const&, ui_adaptor&)
    veh_interact.cpp:?
    ui_adaptor::redraw_invalidated()
    ??:?
    veh_interact::do_main_loop()
    ??:?
    veh_interact::run(vehicle&, point const&)
    ??:?
    game::exam_vehicle(vehicle&, point const&)
    ??:?
    veh_menu::query()
    ??:?
    vehicle::interact_with(tripoint const&, bool)
    ??:?
    game::examine(tripoint const&, bool)
    ??:?
    game::examine(bool)
    ??:?
    game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
    ??:?
    game::handle_action()
    ??:?
    do_turn()
    ??:?
    main
    ??:?
```

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

None

#### Purpose of change

Stop crash to desktop on examining some vehicles.

Fixes #64407.

#### Describe the solution

Checked if the fuel `cap` for a given fuel was zero, and avoided showing/calculating time-to-full/empty calculations if it is.

#### Describe alternatives you've considered

None.

#### Testing

Loaded save in #64407 without patch applied. Game crashes on vehicle examination.

Loaded save in #64407 with patch applied. Vehicle can be examined fine.

#### Additional context

None.

### CODE REVIEW

**Comment by irwiss** [comment]
I can't reproduce the crash using the save from linked PR on commit b738ae2c6315ed81f56f84d8a7b5479d9f7f1de9
I think the actual repro case happened on a weirdly generated wreck and failed to survive a save/load cycle
Likely it's caused by something I changed in https://github.com/CleverRaven/Cataclysm-DDA/pull/64097 though

I think it might be worth it to do the `cap == 0` case handling earlier; since with verbose == true and debug_mode == false the division by 0 will happen on line 437

**Comment by pjf** [comment]
@irwiss : Well heck, I've now tried it with the save as well and can't reproduce it either. A weird wreck that didn't survive a save/load cycle makes perfect sense, especially since weird wrecks have been the bane of my existence.

Adding more comments in #64407.

**Comment by irwiss** [comment]
I mean regardless of reproduction it's probably a good idea to block division by zero, but your solution misses the case you described in the issue:
When examining vehicle the function is called with verbose=true, and unless you're in debug mode you'll divide at line 437 before you get to the check you added

**Comment by pjf** [comment]
> When examining vehicle the function is called with verbose=true, and unless you're in debug mode you'll divide at line 437 before you get to the check you added

Oh gosh, you're absolutely right. PR updated.

**Pull request merged**
