### PR TITLE
Density balance pass - fuel, mutagen, batteries, electric motors, jewelry, tool_armor items

### PR DESCRIPTION
**Pull request by batekulve**
Balance fuel, mutagen, vehicle batteries, electric motors, jewelry, and a few tool_armor items.

#### Summary
Balance "Density balance pass for fuel, mutagen, vehicle batteries, electric motors, jewelry, and a few tool_armor items."

#### Purpose of change
Fixing some objects' density being either impossibly high, or in some cases unreasonably low. Contributes toward fixing #54811.

#### Describe the solution
If an object's density was higher than its materials suggests, then lower it to the correct density. If an object's density was significantly lower than its material suggests and below 1.0 g/cm3, then raise it, but not all the way to the cap.
Lead-acid battery density set to 2.1 g/cm3.
Lithium-ion battery density set to 4.0 g/cm3.

#### Describe alternatives you've considered
In real life, lithium-ion batteries are less dense than lead-acid batteries. However, Li+ storage batteries in Cataclysm can hold _way_ more charge than real life Li+ vehicle batteries. I think having storage batteries be about twice as heavy as lead-acid car batteries is a good balance between realism and game balance. This is still lighter then they were before.

I could have left watch volume the way it was, but I think 250 ml (the volume of a plastic water bottle) was way too high for even a large watch. Online stats for Rolex watches put the weight at somewhere between 83 to 225 g.

#### Testing
Copied item JSON to latest experimental game directory. Weights and volumes in the item spawning menu were correct.

#### Additional context
Enhanced electric motors are made of superalloy. Are the more advanced Super electric motors supposed to be made out of superalloy as well?

### CODE REVIEW

**Comment by Maleclypse** [comment]
Do you know to rebase you’re PR to resolve the conflict or would you prefer I try to manually resolve it?

**Comment by Inglonias** [comment]
Is this PR sufficient to resolve all those density failures we're seeing by itself, or will there need to be more of those?

**Comment by Maleclypse** [comment]
> Is this PR sufficient to resolve all those density failures we're seeing by itself, or will there need to be more of those?

Based on the line count this is approximately 1/10th of the total density changes needed.

**Comment by batekulve** [comment]
That's a worryingly long list. I hope I did that right.

**Comment by dseguin** [comment]
It looks like something's gone wrong with your commit history, maybe try rebasing your last commit against `CleverRaven/master` to fix it

**Comment by batekulve** [comment]
That seemed to resolve conflicts and correct the File Changed tab. In the future, how can I avoid this? By rebasing from `upstream/master` before committing my changes to the branch?

**Comment by BrettDong** [comment]
Commit history is still messed up. You probably committed on the wrong branch, or your base branch diverted from upstream.

**Comment by batekulve** [comment]
Okay, I'm torching this branch and starting over.

**Pull request closed without merging**
