### PR TITLE
Add disassembly recipes for Exodii material blocks, attempt 2

### PR DESCRIPTION
**Pull request by AtomicFox556**
#### Summary
Content "Add disassembly recipes for Exodii material blocks"

#### Purpose of change
Make those huge blocks of material actually useful.

#### Describe the solution
Each large block is disassembled into smaller blocks, and those are then disassembled into actual usable material by weight. Angle grinder is needed to disassemble metal blocks, and circular saw or reciprocating saw are needed to disassemble plastic block.
Increased weight limit for "crafting spot" workbench, so that items that are as heavy as those blocks could be disassembled.

#### Describe alternatives you've considered
Disassembling material blocks into usable material straight away, but it'd take too much time to do so and would cause a delay after disassembly is done, as all the newly-created items are being spawned.

#### Testing
Disassembled material blocks in-game to make sure that disassembly still works fine with huge weights and huge amounts of stackable items produced.

#### Additional context
Unfucked duplicate of #57552 that is making use of stuff added in #56598.

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
I think you're underestimating several aspects of this problem. A typical cutoff disc (115mm diameter) has a cutting depth around 5cm, so that's going to be the side length for your cubes (i.e. 0.125L), unless you introduce a heavy angle grinder with a disc twice that size, netting you 10cm / 1L cubes.
That implies the total cut area is something like 900^2 sq cm (area of a cut through the cube, i.e. face area) * 900/5 (number of cuts per axis) * 3 (number of axes). That comes out to a whopping 437 million cubic cm. I don't know how many cutoff discs that's going to eat, but it's a LOT.  That also implies a pretty ridiculous amount of time spent disassembling it and absurd power consumption.

The 10cm cut from a heavy angle grinder reduces that by a factor of about 8, which isn't enough to fix anything.

What you want for this is a very, very large bandsaw or a very, very large cutting disc.

**Comment by AtomicFox556** [comment]
> I think you're underestimating several aspects of this problem. A typical cutoff disc (115mm diameter) has a cutting depth around 5cm, so that's going to be the side length for your cubes (i.e. 0.125L), unless you introduce a heavy angle grinder with a disc twice that size, netting you 10cm / 1L cubes. That implies the total cut area is something like 900^2 sq cm (area of a cut through the cube, i.e. face area) * 900/5 (number of cuts per axis) * 3 (number of axes). That comes out to a whopping 437 million cubic cm. I don't know how many cutoff discs that's going to eat, but it's a LOT. That also implies a pretty ridiculous amount of time spent disassembling it and absurd power consumption.
> 
> The 10cm cut from a heavy angle grinder reduces that by a factor of about 8, which isn't enough to fix anything.
> 
> What you want for this is a very, very large bandsaw or a very, very large cutting disc.

In such a scenario you'd most likely not want to cut up the whole cube, at least all at once, except I don't know what's the best way to make that possible. I can only think of adding partially cut up cubes as separate items, from which you'd cut off smaller chunks, possibly in 10% increments or so.

Also this makes me think about how would Exodii go about with transporting and disassembling those metal blocks. While there are mobile cranes capable of lifting 9 tons (the weight of a lead block) and there are industrial bandsaws that could cut up a block this large, wouldn't it be easier to make smaller blocks of material to start with? You could stack them into a larger one for pretty much the same material density anyway.

**Comment by AtomicFox556** [comment]
I think I'll just make a PR later to make those blocks have a more manageable size. That's just not a convenient method of material storage for anyone involved.

**Comment by Drew4484** [comment]
Is there still a plan to make the 5/10 L ingots have deconstruct recipes?

**Comment by AtomicFox556** [comment]
I plan to do it at some point, along with changing huge Exodii material blocks to be stacks of smaller ones, as they proved to be too inconvenient to transport, use, and most likely manufacture in the first place, for no real advantage to anyone. I'd be fine with someone else taking over it, though.

**Pull request closed without merging**
