### PR TITLE
Add: check json files by Travis

### PR DESCRIPTION
**Pull request by serv-inc**
#### Summary
SUMMARY: Build "Add check to Travis CI to check JSON files"

#### Purpose of change
Avoid broken JSON from ever becoming part of master. Avoid cases like https://github.com/CleverRaven/Cataclysm-DDA/pull/27045. Trigger bug: edit JSON, make it invalid, compile game, game crashes.

#### Describe the solution
 Fix: Travis should/could complain. If this is not working, feel free to adjust, or tell me about it.

### CODE REVIEW

**Comment by kevingranade** [comment]
This needs to be a check run from an existing stage, not a new stage.

**Comment by serv-inc** [comment]
> This needs to be a check run from an existing stage, not a new stage.

awesome. Is there anything else to do here?

**Comment by kevingranade** [comment]
Not my intent, but my test PR #27096 was merged with my adjustments, so your change made it in in a different PR.

**Comment by serv-inc** [comment]
Main thing is that it is used. You might want to update to the latest commit https://github.com/CleverRaven/Cataclysm-DDA/pull/27090/commits/38851b0fa1fd46b5b362e684b94707d7303ba447.

**Pull request closed without merging**
