### PR TITLE
Jsonify toxic dump

### PR DESCRIPTION
**Pull request by chaisawlajatang**
#### Summary

```SUMMARY: Content "Jsonify toxic waste dump'"```

#### Purpose of change

Toxic dump was hardcoded, boring and nonrotatable.

#### Describe the solution

I jsonified it, made it less boring and rotatable. It's still radioactive and sometimes still contains military ID card.

Resolved the conflict of the previous PR.

#### Describe alternatives you've considered

Leave everything as is.

#### Additional context

toxic

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
You decided to leave the military ID card as is?

Also, some trail or a road to the doors would be good.

**Comment by chaisawlajatang** [comment]
ID card has a 10% chance to spawn. I guess the dump is used by the military too, and ID card makes some reason to visit the dump.

There was no road originally, I thought it's by design, like a semi-secret object hidden from everyone's eyes.

**Comment by ZhilkinSerg** [comment]
You need to remove some more code:

https://github.com/CleverRaven/Cataclysm-DDA/blob/78daca53d4e563f00fbb2d6724239187a8e5e23f/src/map.h#L1456

https://github.com/CleverRaven/Cataclysm-DDA/blob/78daca53d4e563f00fbb2d6724239187a8e5e23f/src/overmap.cpp#L791

**Comment by curstwist** [comment]
drat i missed it.  Did you add a roof & paint that building?

**Comment by chaisawlajatang** [comment]
Nope, will add a roof later.

**Pull request merged**
