### PR TITLE
Remove Rivtech LMG/battle rifle

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove Rivtech LMG/battle rifle"

#### Purpose of change

Both of these guns are a byproduct of early times in CDDA's development, and do not fit into the modern game, or make sense.

The LMG: 
1. 500/250 round magazines. These are dumb, and don't make any sense. It's in the realm of impossible to have a drum magazine that big that's not just on a belt. Why not give it a belt, though? I could, but it should still be removed for these following reasons.
2. A caseless LMG. One of caseless ammo's biggest downside is the fact it doesn't have material to dump heat into, so guns overheat fast. For the G11, this was solved as the gun is not expected to have huge amount of rounds dumped out of it in a short time, and has a fairly smaller case. The LMG has none of those. It's role is to provide constant fire, and would not doubt cause unwanted cookoff inside the gun. And the caliber is also much hotter than the G11s, compounding the overheating issue.

The Battle Rifle:
Battle rifles are a specific thing, using calibers more powerful than intermediate calibers, useful for longer ranges, barrier penetration, and suffering in full-auto due to the power of the round. There's already a rivtech assault rifle in the exact same caliber, and so by definition, it's not a battle rifle. Could've removed the assault rifle instead, but eh I felt the battle rifle has less going for it.

Now, this applies to both, but also all rivtech guns. The US military would not just adopt a brand new line of guns out of nowhere, in calibers and magazines that are proprietary. Especially something as "cutting edge" as rivtech. 

#### Describe the solution

Removes them.

#### Describe alternatives you've considered
I didn't.

#### Testing
image
image
Before and after the changes. Trust me, these are different sceenshots.

#### Additional context

Putting these in some weird niche location or chalking them up to some alternate earth placing them in via portal is a poor rationale. There's much more interesting and unique concepts to come up with a future gun than "what if g11 but everything"

### CODE REVIEW

**Comment by sonphantrung** [comment]
@Rivet-the-Zombie What's your take on this one?

**Comment by Vgoloshivskiy** [comment]
Maybe instead of removing gun completly you can add overheat as on laser weapons 500 rounds is way too much no doubt about that considering that almost all locations that spawn ammo for this thing spawn 40-80 rounds

**Comment by Holli-Git** [comment]
> Maybe instead of removing gun completly you can add overheat as on laser weapons 500 rounds is way too much no doubt about that considering that almost all locations that spawn ammo for this thing spawn 40-80 rounds

Why would anyone buy, adopt, or create an LMG that doesn't function as an LMG?

**Comment by Vgoloshivskiy** [comment]
> > Maybe instead of removing gun completly you can add overheat as on laser weapons 500 rounds is way too much no doubt about that considering that almost all locations that spawn ammo for this thing spawn 40-80 rounds
> 
> Why would anyone buy, adopt, or create an LMG that doesn't function as an LMG?

It may be failed experimental weapon sent in small numbers for on site testing,
Blob psychosis.

**Comment by Holli-Git** [comment]
> It may be failed experimental weapon sent in small numbers for on site testing and kept as ammo supplies were running low (in Trans Logistics there is barelly any ammo at all if you forget about turrets with bad IFF), Blob psychosis.

No. If it was a rejected experimental weapon it'd either a) be essentially non-functional because it's a failed experiment or b) essentially non-functional as it'd get a few too many internal cook-offs and blow up. I think a failed experiment would also have a lot more ammo with it, as since the gun failed you can't use the rest of the ammo. You also can't justify stuff with "blob psychosis", especially with stuff as long and thought-out as weapons testing.

Also, majority of weapons testing would take place in Aberdeen, which is not in New England. There's just too many variables that need to be heavily skewed in favour of this LMG to justify it existing in the state its in and in the place its in.

**Comment by Vgoloshivskiy** [comment]
> > It may be failed experimental weapon sent in small numbers for on site testing and kept as ammo supplies were running low (in Trans Logistics there is barelly any ammo at all if you forget about turrets with bad IFF), Blob psychosis.
> 
> No. If it was a rejected experimental weapon it'd either a) be essentially non-functional because it's a failed experiment or b) essentially non-functional as it'd get a few too many internal cook-offs and blow up. I think a failed experiment would also have a lot more ammo with it, as since the gun failed you can't use the rest of the ammo. You also can't justify stuff with "blob psychosis", especially with stuff as long and thought-out as weapons testing.
> 
> Also, majority of weapons testing would take place in Aberdeen, which is not in New England. There's just too many variables that need to be heavily skewed in favour of this LMG to justify it existing in the state its in and in the place its in.

Can't argue with that, know very little about guns to know about weapon testing locations.

**Comment by ehetena** [comment]
Literally all you do is remove things that other people have created

**Comment by Zireael07** [comment]
@ehetena Not true, they also did some rebalancing and also re-added mistakenly removed flavors

**Comment by fairyarmadillo** [comment]
It's sad to see these go, but it's hard to argue with the reasoning.

**Comment by Holli-Git** [comment]
> Didn't the US military do this IRL already? See [XM7](https://en.wikipedia.org/wiki/XM7_rifle) and [XM250](https://en.wikipedia.org/wiki/XM250).

The NGSWP was a thing before the weapons were made, and rivtech firearms are pre-existing guns that were adopted into service. Those two guns also adapt to new military doctrine, while rivtech firearms seem to fill no niche or fulfill a change in doctrine. The XM7 uses SR-25 magazines which are already in service. The NGSWP are two guns, not a whole line of them like the Rivtech ones are. Also, XM7 and XM250 are meant to replace existing weapons, rivtech guns are brand new additions.

**Pull request merged**
