### PR TITLE
More vehicles found inside house garages

### PR DESCRIPTION
**Pull request by ISuckM8**
#### Summary

Balance "Increases vehicle spawnrate inside house garages"

#### Purpose of change

Car condition was nerfed and it just makes sense because of the small number of cars outside of houses.

#### Describe the solution

Just increases chances for garages to have vehicles.

#### Describe alternatives you've considered

Increase amount of vehicles found on the street.

#### Testing

Works just fine

### CODE REVIEW

**Comment by wapcaplet** [comment]
Such a greatly increased (5x) chance of the vehicle being in the garage implies a higher chance of the (feral or zombified) owners still being at home. Can you increase the "place_monsters" chance by a similar factor for these garages? That would at least make it sometimes more challenging to steal the vehicle.

**Comment by ISuckM8** [comment]
> Such a greatly increased (from 15% to 75%) chance of the vehicle being in the garage implies a higher chance of the (feral or zombified) owners still being at home. Can you increase the "place_monsters" chance by a similar factor for these garages? That would at least make it sometimes more challenging to steal the vehicle.

80% of houses have zombies though?

**Comment by wapcaplet** [comment]
> 80% of ALL houses have zombies though?

That is fine, but beside the point. I am suggesting that these houses should have *more* zombies than the average house, because the vehicle is so much more likely to be at home.

**Comment by ISuckM8** [comment]
> > 80% of ALL houses have zombies though?
> 
> That is fine, but beside the point. I am suggesting that these houses should have _more_ zombies than the average house, because the vehicle is so much more likely to be at home. It would be a simple increase to the "place_monsters" chance, from 2 to (say) 10.

Done

**Comment by kevingranade** [comment]
We don't actually have numbers of cars vs number of houses to make this kind of tweak, and the reactionary purpose of correcting toward an arbitrary previous balance point WRT vehicle availability is not valid.

If you want to tweak the number of cars, especially drastically like this, it needs to be based on how many cars should exist in the game area based essentially on demographics, and from a balance/scenario point of view, most cars should be on the road and damaged.

**Pull request closed without merging**
