### PR TITLE
cap pain gain from hauling heavy furniture

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Balance "Cap pain gain from hauling heavy furniture"

#### Purpose of change
Previously grabing a heavy piece of furniture (like a gun safe) and holding down the movement key was a quick way to accumulate pain rapidly and with no limit. (in less than 10 seconds)

Now it will stop (and deny further hauling attempts) once the player reaches distressing pain

#### Describe the solution

Added a check for the pain lvl the character is in and stop hauling attempts if they would require the help of the rng roll that can cause pain. (player str below the required str)

#### Describe alternatives you've considered

I could just add a cap that prevents further pain from hauling attempts but that feels a bit gamey and illogical.

#### Testing

- Create str 8 char
- Debug spawn in a gun safe (map editor) and grab it
- Hold down movement key for a bit, until you reach distressing pain and the grabbed furniture gets released and a msg is added to the msg log.

### CODE REVIEW

**Comment by Xaleth** [comment]
Could there be a prompt to continue hauling?

**Comment by Jamuro-g** [comment]
> Could there be a prompt to continue hauling?

In theory yes, but it the player would end up getting prompted everytime they try to move the furniture ... and for every tile they move it.

**Comment by actual-nh** [comment]
Should this really happen for characters with `Cenobite` (no strength/dexterity reductions from pain)? I can also see arguments for `Pain Junkie` and even `Masochist` to be "exempt".

**Comment by Jamuro-g** [comment]
> Should this really happen for characters with `Cenobite` (no strength/dexterity reductions from pain)? I can also see arguments for `Pain Junkie` and even `Masochist` to be "exempt".

That is a good point. The updated version now excempts cenobite and allows players with masochist/pain junkie to go one pain threshhold further. (unmanagable pain instead of distressing)

**Pull request merged**
