### PR TITLE
Jenkins Compilation Fix

### PR DESCRIPTION
**Pull request by DavidKeaton**
Missing include in `mapgenformat.cpp`.
Needs `<algorithm>` if using `remove_if()`.

-Davek

### CODE REVIEW

**Comment by narc0tiq** [comment]
Am I missing something? <http://ci.narc.ro/job/Cataclysm-Matrix/> says everything's currently fine, and has been for the last 29 builds. Or is there another Jenkins you're referring to?

**Comment by DavidKeaton** [comment]
http://ci.narc.ro/job/Cataclysm-Jently/30260//consoleText
(see PR #12566 Details)

**Comment by narc0tiq** [comment]
That's... really weird. Why doesn't the mainline build complain? #12566 doesn't seem to be touching mapgenformat.cpp or any of its friends.

**Comment by DavidKeaton** [comment]
*shrugs*

**Comment by narc0tiq** [comment]
Oh, nevermind, I see it: <https://github.com/CleverRaven/Cataclysm-DDA/pull/12566/files#diff-66217ab5c054d1ce40c5940ec02eb541L6>

In mainline, `mapgenformat.cpp` includes `mapdata.h`, which includes `enums.h`, which includes `<algorithm>`. You removed that last (on the linked line).

**Comment by narc0tiq** [comment]
Just to be clear, I agree that `enums.h` shouldn't be including `<algorithm>` if it's not using it, and it shouldn't be using it. I was just determining the failure path for your PR #12566.

**Comment by DavidKeaton** [comment]
Oh oh you're right. I must've removed that when I got rid of my old functions. Added it to mapgenformat in my PR, closing.

**Comment by DavidKeaton** [comment]
Thanks @narc0tiq for the quick detective work there. :-)

**Comment by narc0tiq** [comment]
Well, since it was only showing up on the one PR, it had to be something that PR did, right?

**Comment by DavidKeaton** [comment]
True, but you know me... I tend to forget things sometimes. :-P

**Pull request closed without merging**
