### PR TITLE
make onomatopeias translatable

### PR DESCRIPTION
**Pull request by illi-kun**
because current state isn't good:
untitled

### CODE REVIEW

**Comment by jaked122** [comment]
You may also want to check the vehicle::alarm too. Same sort of thing.

**Comment by illi-kun** [comment]
My initial commit contains changes for two functions, and ```vehicle::alarm``` is one of them. Can you confirm you're talking about already fixed thing or I miss something?

**Comment by Rivet-the-Zombie** [comment]
Can you show us some example onomatopeia in Russian? Not required in any way, I'd just like to see what they look like.

**Comment by illi-kun** [comment]
Some of them sound the same and just write in Cyrillic alphabet, like "hummm!" = "хммм", "vroom!" = "вруум", but things like train's "Choo choo" spells like "Ty-ту" (and sounds more like "Too-too").

**Comment by Rivet-the-Zombie** [comment]
Very cool! Thanks, @illi-kun!

**Comment by illi-kun** [comment]
np, I glad you liked it :-)

**Pull request merged**
