### PR TITLE
reduce car loot

### PR DESCRIPTION
**Pull request by voiddeal**
#### Summary
Balance "reduce car lootables"

#### Purpose of change
even though this PR #66267 reduced the car loot a bit but still it's way too much and sometimes it feels like a dream.
I created a world and looted **_3_** random semi-wrecked cars and this was the result:

- 17"wheel x1
- bottle jack x2
- funnel x2
- jumper cable x1
- large plastic sheet x1
- lug wrench x2
- plastic jerry can x2
- rubber hose x2
- small fire extinguisher x3
- first aid kit box x1
- survival kit box x2
- doc tape x50
- adjustable wrench x1
- boxcutter knife x1
- heavy duty flash light x1
- screwdriver set x1
- small adjustable wrench x1
- tongue-and-groove pliers x1
- hand pump x1
- locking pliers 2
- socket screwdriver set x1
- socket wrench set  x1
 
I know 3 cars is not a solid determiner for the possible outcome but nonetheless this is a OP loot in my opinion.

#### Describe the solution
I reduced the possible loot from cars by approximately 10%-40%

#### Testing
you wont feel like a lottery winner after looting a few cars

#### Additional context
I just tried to tune down the values a bit to avoid a big sudden change but still not the right values.
but in general anything lower than the current rates are better.

### CODE REVIEW

**Comment by kilozombie** [comment]
I have never in my life driven, or even been _in_ a car with first aid. That isn't to say that's smart, but it's got to be way way less common than portrayed in the game. Just my thoughts.

**Comment by andrei8l** [comment]
> I have never in my life driven, or even been _in_ a car with first aid. 

The first aid kit is typically hidden in the trunk or under the front seats and not something a passenger would see. Same for the spare wheel and fire extinguisher.

Normally I'd say this needs a better justification than "loot = bad", but the previous one was merged without it so idk 🤷

**Comment by Zireael07** [comment]
@andrei8l In my corner of EU at least, first aid kit is required to be somewhere in the car just like extinguisher

**Comment by bombasticSlacks** [comment]
> Normally I'd say this needs a better justification than "loot = bad", but the previous one was merged without it so idk 🤷

If the person making the second PR is the same person who made the first, I consider it more of an addendum than a separate contribution and don't provide as much scrutiny.

As for this PR I don't really have much interest in merging a "vibes" PR so soon after the initial change, if you have some numbers for what people carry then it could be implemented 😄

**Comment by fairyarmadillo** [comment]
Every car I've ever owned has had a full toolbox in the trunk. I would not leave home without it, and if I lived somewhere cold I'd pack blankets and stuff too. I consider myself to be way more prepared than most people, though.

> @andrei8l In my corner of EU at least, first aid kit is required to be somewhere in the car just like extinguisher
> 
> Depending on how big it is people will put it in glove compartment or in the trunk

There's no such requirement in the US and I've never met anyone who kept first aid supplies in their car. I'm sure some people do, but it's not a super common thing.

**Comment by harmez7** [comment]
> If the person making the second PR is the same person who made the first

No im not the person who made the first one.
i've made this PR only duo to the fact that the loot in cars can be very excessive, for the sake of a balanced and meanwhile a challenging experience.
im not living in USA to know what ppl carry in their cars but as a hardcore gamer with over 20yrs of gaming experience in hundreds of games and as someone who've put over 200hrs into this game in the past 2 weeks I'd say the current rates for loot spawn in cars are extreme (and some other places too) especially because all of them are essential stuff for survival.
there is a higher chance for finding a good wrench in a car than in a light industry.
what you want?
meds? loot a car,
awesome tools? loot a car,
cool survival stuff? loot a car,
some random stuff to make you excited? loot a car,
and if you didn't find them in the first car, you most certainty will in the 2nd or at most in the 3rd!.
it's not right to only focus on realism when we create a realistic game, simply because we can never hit that spot (100% realism mechanic-wise) and its not how it needs to be.
Balance is what matters and it's what that makes a challenging game enjoyable and challenge is what a realistic-wannabe post-apocalyptic game requires and with poor balance, challenge loses its color.
the one who has a good understanding of "Balance", can make awesome hardcore gaming experiences.

> > Normally I'd say this needs a better justification than "loot = bad", but the previous one was merged without it so idk 🤷
> 
> If the person making the second PR is the same person who made the first, I consider it more of an addendum than a separate contribution and don't provide as much scrutiny.
> 
> As for this PR I don't really have much interest in merging a "vibes" PR so soon after the initial change, if you have some numbers for what people carry then it could be implemented 😄

**Comment by harmez7** [comment]
> if the person making the second PR is the same person who made the first
No im not the person who made the first one.
i've made this PR only duo to the fact that the loot in cars can be very excessive, for the sake of a balanced and meanwhile a challenging experience.
im not living in USA to know what ppl carry in their cars but as a hardcore gamer with over 20yrs of gaming experience in hundreds of games and as someone who've put over 200hrs into this game in the past 2 weeks I'd say the current rates for loot spawn in cars are extreme (and some other places too) especially because all of them are essential stuff for survival.
there is a higher chance for finding a good wrench in a car than in a light industry.
what you want?
meds? loot a car,
awesome tools? loot a car,
cool survival stuff? loot a car,
some random stuff to make you excited? loot a car,
and if you didn't find them in the first car, you most certainty will in the 2nd or at most in the 3rd!.
it's not right to only focus on realism when we create a realistic game, simply because we can never hit that spot (100% realism mechanic-wise) and its not how it needs to be.
Balance is what matters and it's what that makes a challenging game enjoyable and challenge is what a realistic-wannabe post-apocalyptic game requires and with poor balance, challenge loses its color.
the one who has a good understanding of "Balance", can make awesome hardcore gaming experiences.

**Comment by Aerin-of-the-Toast** [comment]
This shows a misunderstanding of CDDA's design philosophy around "balance." The philosophy has always been "real life has its own balance." Nerfing loot just for some vague notion of balance isn't what we want at all, and impossible to truly quantify. Cars ingame should have everything they would irl.
Especially keep in mind there's going to be people fleeing in their car with supplies who get killed before they can get very far or whatever.

**Comment by harmez7** [comment]
> there's going to be people fleeing in their car with supplies

that is still possible.
if you'd have played this game recently you'd hve known that the current possible loot in cars are very extreme and excesses the real life situations. ive done some researches for these changes so these are not only MY preference

**Comment by harmez7** [comment]
> The philosophy has always been "real life has its own balance."

goodluck creating real life balance. this is a game, no game have ever wanted or tried to be 100% realistic in history because it's impossible and attempt to doing it can cause major balance issues because there is ALOTLOT to worry about.
a game is a driven experience, no matter how open it has been made.
that's why implemented balance is important. making sure the players tastes what we want them to taste and those who are good at doing this, can touch the stars.

**Comment by harmez7** [comment]
this is the biggest flaw of one of my favorite game ever-this game : level design and balance.
im not good at coding so I will just pry XD

**Comment by kilozombie** [comment]
I am definitely hung up on the first aid kit thing. It is admittedly not easy to find high-level medical gear in the earlygame, but that's why bandages (and natural healing) exist. You're meant to really scrape by without stacks of medical gauze and painkillers and antiseptic, I think. Though this is coming from someone who primarily plays melee, and someone who also primarily savescums.

Even when bugging out of my house IRL, I'd be doing it in a hurry focusing on my family and food and possessions. I absolutely don't doubt that some families would bring first aid supplies, thinking smart on their feet and seeing the world actually going to shit, but some folks might think it's similar to a weather warning--or at least something they'll be able to escape. First aid might be lower on the priority list than you'd hope.

W/r/t realism, I think it would make a ton of sense if cars had more electronics more often, and _especially_ for-fun books. If you think you're going to be on the road a while and need to appease a kid, they'll bring them along anyhow. And families with kids can attest that cars will be loaded with books in-between all the seats.

All just circumstantial though, it might help to actually do some more thorough research. You don't want cars to be loot pinatas but they could easily be more consistent looting pools for household goods.

**Comment by kevingranade** [comment]
As outlined by others, the rationale here is incredibly weak and the goal of enforcing scarcity because you think the game needs it instead of because the scenario calls for it is not one we follow.

**Comment by harmez7** [comment]
the issue is obvious enough.
you're doing this because I complained about the game. np

**Comment by esotericist** [comment]
adherence to a policy that has been in visibly in place for years is not singling you out. if you want to take a bit, come to a better understanding of how we go about things here, and try again in the future (with a better rationale), that would be welcome. for the time being, we're done here.

**Pull request closed without merging**
