### PR TITLE
Changed 'Report bugs' message to github from kevins email.

### PR DESCRIPTION
**Pull request by Soyweiser**
Implements suggestion made here #18162 (Just close this one if it is a bad idea). (I shortened the sentence a bit. Due to min screen size).

### CODE REVIEW

**Comment by Soyweiser** [comment]
In player.cpp 'rem_morale( MORALE_FOOD_COLD );  was missing. No idea if that was intentional. It does something similar to rem_morale( MORALE_FOOD_HOT ); Should I add it?

**Comment by mugling** [comment]
Not sure how @kevingranade would feel about that but I'll add that mention so that he can weigh in

**Comment by Soyweiser** [comment]
I also don't know. But he is pretty busy atm from what I heard. (Congrats kevin!)

**Comment by mugling** [comment]
> Congrats kevin

Yes, likewise

**Pull request merged**
