### PR TITLE
Add installable gunmods to provide slots for other gunmods

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Add installable gunmods to provide slots for other gunmods"```
#### Purpose of change

Provides an inbetween variant between being able to easily attach a gunmod to a gun if a slot is available (doesn't make sense for many old guns) and not being able to do so at all, even with possible modification, that variant being "gunmod is installable with some permanent gun modification".
List of gunmod slot changes (mostly additions; a few were removed as they didn't make sense):

Launchers:

M79: underbarrel mount, rail mount, grip mount, stock mount, sling
Flamethrower: sights mount, underbarrel mount, rail mount, stock mount
Spraycan flamethrower: rail mount, REMOVE grip
tube 40mm launcher: underbarrel mount, rail mount, grip mount, stock mount, sling
M320 stand alone launcher: sling
Milkor MGL: underbarrel mount, rail mount, grip mount, stock mount, sling
triple-barrel 40mm launcher: underbarrel mount, rail mount, grip mount, stock mount, sling
mininuke launcher: sights mount, underbarrel mount, rail mount, grip mount
M202 FLASH: underbarrel mount, rail mount
RPG-7: underbarrel mount, rail mount
crude rocket launcher: sights mount, underbarrel mount, rail mount, grip mount
simple flamethrower: sights mount, underbarrel mount, rail mount, stock mount
CLASS: base launcher: sling

Pistols:

12 gauge pistol: underbarrel mount, rail mount
homemade hand cannon: underbarrel mount, rail mount
flintlock pistol: sights mount, underbarrel mount, rail mount, grip mount, stock mount
Taurus Raging Bull: underbarrel mount, stock mount
FN 1910 .380: sights mount, underbarrel mount, rail mount, stock mount
Ruger LCP: sights mount, underbarrel mount, rail mount, stock mount
Kel-Tec P32: sights mount, underbarrel mount, rail mount, stock mount
S&W 500: underbarrel mount, stock mount 
Jennings J-22: sights mount, underbarrel mount, rail mount, stock mount
Nail gun: sights mount, underbarrel mount, rail mount, grip mount, stock mount
Flaregun: sights mount, underbarrel mount, rail mount
Colt M1860 Army: rail mount, underbarrel mount
Colt M1861 Navy: rail mount, underbarrel mount
Mini speargun: rail mount, underbarrel mount
Kel-Tec P3AT: sights mount, underbarrel mount, rail mount, stock mount
Kel-Tec PF-9: sights mount, underbarrel mount, rail mount, stock mount
2 Shot Special: rail mount, stock mount
handmade six-shooter: rail mount
Mossberg Brownie: sights mount, underbarrel mount, rail mount, stock mount
COP .38: sights mount, underbarrel mount, rail mount, stock mount
CLASS: backup pistol: muzzle, brass catcher, sights mount, underbarrel mount, rail mount, stock mount
CLASS: revolver: rail mount, underbarrel mount
CLASS: base launcher: sling

Rifles:

pneumatic bolt driver: underbarrel mount, rail mount
Crossbow: underbarrel mount, rail mount, sights mount
Pneumatic assault rifle: underbarrel mount, rail mount
Pneumatic speargun: underbarrel mount, rail mount
Flintlock rifle: sights mount, rail mount, grip mount, stock mount
Handheld laser cannon: sights mount, underbarrel mount, rail mount, grip mount, stock mount
Speargun: underbarrel mount, rail mount
Double speargun: underbarrel mount, rail mount
Flintlock carbine: sights mount, underbarrel mount, rail mount, grip mount, stock mount
Coilgun: underbarrel mount, rail mount
Nail rifle: underbarrel mount, rail mount
Handmade double-barrel flintlock: sights mount, underbarrel mount, rail mount, grip mount, stock mount
Henry Big Boy .44: underbarrel mount, rail mount
Big Horn Model 89: underbarrel mount, rail mount
BB gun: underbarrel mount, rail mount, grip mount
Ruger Mini-14: underbarrel mount, rail mount, grip mount, stock mount
pipe rifle: .44 Magnum: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: .45: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: .22: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: .38 Special: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: .40: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: 9x19mm: sights mount, underbarrel mount, rail mount, grip mount
M1903 Springfield: underbarrel mount, rail mount, grip mount, stock mount
Special 700:  underbarrel mount, rail mount, stock mount 
M24: underbarrel mount, rail mount, grip mount
Ferromagnetic rail rifle: underbarrel mount, rail mount 
Combination gun: rail mount
M1A: underbarrel mount, rail mount, grip mount, stock mount
pipe rifle: .30-06: sights mount, underbarrel mount, rail mount, grip mount
pipe rifle: .223: sights mount, underbarrel mount, rail mount, grip mount
.50 caliber rifle: underbarrel mount, rail mount
Handmade carbine: sights mount, rail mount, grip mount
pipe rifle: .308: underbarrel mount, rail mount, grip mount

Shotguns: 

Pipe shotgun: sights mount, underbarrel mount, rail mount, grip mount, muzzle
Double-barrel pipe shotgun: sights mount, underbarrel mount, rail mount, grip mount
Handmade lever shotgun: sights mount, underbarrel mount, rail mount, grip mount, muzzle
Blunderbuss: sights mount, underbarrel mount, rail mount, grip mount,
Manual autoshotgun: underbarrel mount, rail mount 
Shotgun revolver: sights mount, underbarrel mount, rail mount, grip mount
Single barrel shotgun: underbarrel mount, rail mount, grip mount
Pipe combination gun: sights mount, underbarrel mount, rail mount, grip mount
Double barrel shotgun: underbarrel mount, rail mount, grip mount, REMOVE muzzle

SMGs:

PPSh-41: rail mount
Paintball gun: sights mount, underbarrel mount, rail mount, grip mount, stock mount
STEN: sights mount, underbarrel mount, rail mount, grip mount
Briefcase SMG: rail mount
#### Describe the solution

Adds five different gunmods (one for each slot: sights, rail, underbarrel, grip, stock) and adds gunmod slots to most guns, on which they could be installed. Also adds recipes for those new gunmods.
#### Describe alternatives you've considered

Implement some sort of additional parameter on a gunmod slot to make it require tools to use the slot, but this seems a bit too complex.
Add just one gunmod instead, to "unlock" all of those slots, but some slots wouldn't make sense for some guns.
#### Additional context

Video references for something similar being done to guns:
https://www.youtube.com/watch?v=PoEpNHjUvtg
https://www.youtube.com/watch?v=qgCsE1glfG0

### CODE REVIEW

**Comment by tenmillimaster** [comment]
> Jennings J-22: sights mount, underbarrel mount, rail mount, stock mount

Mon dieu, I don't think the world is ready for this monstrosity, even post cataclysm.


Some of these combos I'm not so sure about- there's a lot of difference between adding a bipod stud/rail section and having the appropriate furniture or real estate to install an m203 or a masterkey. In other cases there are questions I have about there being enough material to support such a mod- like a sight rail (I'm *guessing* it'd be a on-the-side style one rather than direct on the slide) on tiny little backup pistols to hold a full on high-magnification optic.


Fuji had mentioned that there was extant code for sawing down gun barrels via a gunsmithing kit- I kinda of think that would be a better implementation, necessitating the kit to actually installing the mounts so this level of 'mount abstraction' is justifiable.

**Comment by JonahDes** [comment]
image

I'm having a hard time imagining this with an underbarrel slot for a grenade launcher.

**Comment by tenmillimaster** [comment]
> I'm having a hard time imagining this with an underbarrel slot for a grenade launcher.

mod targets would still apply, many of the larger underbarrel mods don't apply to the small pistols.

That said, I feel like a lot of these necessitate volume increases, where others don't. A pistol sight rail *might* significantly increase the volume of the gun (mini red dot sight mill, drill and tap on pistols vs those large sight rails  like these <https://images-na.ssl-images-amazon.com/images/I/51GWyyn8DlL._SX569_.jpg> that are kind of the only viable thing for pocket pistols), whereas a small section of pic rail on something like a flintlock is negligible.

**Comment by Rail-Runner** [comment]
> That said, I feel like a lot of these necessitate volume increases, where others don't.

Installed gunmods currently do add some volume if installed (I've set it to 8 ml per each, noticable for pocket pistols but negligible for larger guns). May increase it if it isn't enough.

**Comment by eilaattwood** [comment]
I always imagined pneumatic bolt driver and pneumatic rifle to look like 'Helsing' pneumatic speargun and 'Tihar' air rifle from Metro 2033. So installing underbarrel mods is quite impossible for me, especially on the bolt driver. 
Helsing
Tihar

**Comment by anothersimulacrum** [comment]
> I always imagined pneumatic bolt driver and pneumatic rifle to look like 'Helsing' pneumatic speargun and 'Tihar' air rifle from Metro 2033

They are inspired by that - if you look at the id for the bolt driver, it's `helsing`.

**Comment by Rail-Runner** [comment]
> I always imagined pneumatic bolt driver and pneumatic rifle to look like 'Helsing' pneumatic speargun and 'Tihar' air rifle from Metro 2033. So installing underbarrel mods is quite impossible for me, especially on the bolt driver.

Seems like it'd work just fine if the air pump lever was not directly under the barrel, but instead a bit to the side. I think this can be taken into account while crafting the weapon, if desired.

**Comment by SirPendrak** [comment]
While we are at this, could you remove stock slot from RM11B scout rifle? Its described as bullpup, and it is indeed very small for a sniper rifle with silencer and scope. Adding folding stock to this makes it crazy small. 
And on second thought.... If we remove stock slot from this, will it be possible to give it back by using theese new tools? And to other bullpups? 
And what about leadworks guns?

**Comment by tenmillimaster** [comment]
@railrunner 8mL seems ok for some, but not for sight rails on a lot of recoil operated pistols, which are quite bulky, or for any rifle platform that needs a side rail type attachment for optics.  (Ak's, mosins, garands ). 

I'm also certain that sighting rails will have significant volume on other launcher style or  other heavy weapons. The RPG 7 and M202 themselves are examples of such 'protusion' style sighting arrangements. The M134 is another example, though volume on mounted guns is kind of a 'least concern'.

I think dropping a lot of the mounting points on the small guns (sights, rail, brass catcher), or using mod targets to specify by class is the best solution. Have a rail for pistols, and another rail for everything else.


Also why the change of type of the Mossberg brownie? It's pocket pistol sized.

**Comment by Greevv** [comment]
I like the goal here, but I'm with Tonk. Possibly make those pistols require a "bracket" or sight rail mod before they can mount sights?

**Comment by Rail-Runner** [comment]
> While we are at this, could you remove stock slot from RM11B scout rifle?

Done, no stock gunmod slot for it now.

> And on second thought.... If we remove stock slot from this, will it be possible to give it back by using theese new tools? And to other bullpups?

Can't think of a reasonable way to do this. Well, actually something like a recoil pad might be doable, it just needs to have BULLPUP flag or something, and stock mods that are compatible need to have BULLPUP_COMPATIBLE flag or something. Maybe I'll work on this later. 

> And what about leadworks guns?

Made them moddable via permanent modification too. Couldn't think of a reason why it wouldn't work.

> Possibly make those pistols require a "bracket" or sight rail mod before they can mount sights?

Done. Pistols and launchers now need alternative gunmods that are larger.

> Also why the change of parent of the Mossberg brownie? It's pocket pistol sized.

Seems like it had a muzzle slot before (which it shouldn't have because it's multi-barrel), so I removed it. After this change nothing was actually inherited from pocket pistol entry as well, so I changed it to more general one too.


Also, slingshots and brace slingshots can now be modified to mount ergonomic grips and underbarrel laser sights.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by kevingranade** [comment]
Need to re-audit this for some of the particular combinations, was this
still allowing rail mounts on essentially derringers?

**Pull request merged**
