### PR TITLE
Added multiple camp construction workers

### LINKED ISSUE #53656: For faction bases make it so you can send more people on construction mission to drastically cut time
### Is your feature request related to a problem? Please describe.

The time requirement for building things are so immense compared to the general game speed that often, before I manage to actually get to a point where I can enjoy the benefits of the base I am long done and bored with the save. It litterally take years to expand the base. Which is realistic if you are one person doing it but just having two people would more than halve the time it takes cause when you are alone, a lot of tasks are exponentially more difficult, but with one to support you can do tasks far more efficiently. I say that as a son of carpenter that have build and pulled down multiple houses. Alone just lifting a beam up takes a while as you have to go back and forth and use a lot of tricks, but with a partner you can skip a lot of extra work. 

### Solution you would like.

Make you able to add more people to every construction people. Adding more people should decrease it at least linearly if not more up until a certain point. I.e. 10 days should be 5 days for 2 people, 3.33 for 3 people, 2.5 for 4 people and so on. 

### Describe alternatives you have considered.

- Powered/higher quality tools decreasing time compared to unpowered tools

- A powered forklift arm drastically reducing build time to simulate the use of machinery in building 

These solutions might also be wise to implement along with the number of people reduction. Its reasonable that a well functioning base with lots of people, powered tools and large machinery would able to construct things extremely quickly.

**EDIT:** Per Photoloss insightfull comment I made expanded on what could be a better solution:

I like what you said about reworking it into blueprints, then it would give the player the opportunity to affect the speed with all the methods available to them in game instead of some abstraction. In fact, going alone those lines maybe it should work closer to how zones work, so the faction camp menu allow you can set up any arbitrary zone and simply checks if the required items, walls, furniture and so is within those zones allowing the player to access the recipes and productions of basecamp.

And then detach blueprint design into a separate selection, where players can select blueprints to apply but are not necessary or linked to the function of the base per se and more about how you could design building. These blueprints ideally would be importable and exportable so users can share base designs and work out particular design for bases in various in game buildings.

So to sum up, for base functions it should basically just work like zones and just check whatever required is within that zone or zones, like how base storage already works. And then actual construction should work trough a importable and exportable blueprints. That way the players can design the bases however they want, or use pre designed designs but the functioning of the base stays more or less the same (making a labyrinth probable would impact the game some). 

### Additional context

https://www.youtube.com/watch?v=AsTB0HnM6WM

A bunch of Amish constructing a entire barn in a day using their hands and primitive tools.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

Features "Added multiple workers to camp construction"

#### Purpose of change

Allow players to assign multiple workers to camp construction missions.
Fix #53656

#### Describe the solution

When a camp construction job is started, ask for additional companions after the first one until out of companions or the player escapes out of the selection list. The time taken is divided by the number of companions assigned and only then converted to "work days".

When the work is done, all companions assigned to the construction is returned without any selection process (just like "normal" jobs don't ask for who to return when there's only one candidate).

When emergency recalling a companion and there there is at least one companion left working on a construction mission, sum up the remaining time and dividing it over the remaining companions (so they will have longer before they're done). The last one removed will drop the job completely as previously.

#### Describe alternatives you've considered

- Allow companions to be added to ongoing missions. Decided against it because it's messy with the "work day" conversion and it requires some new UI element to order it. To much work and complexity for something that ought to be of marginal utility.
- Add one complete set of tools for each companions. This is NOT done currently: the code just checks that tools are available, but doesn't actually allocate them and return them. There is internal functionality for storing the tools in the companion mission data, but it's not used, at least not for construction. As issues with logic to collect and return tools is expected, the current approach of looking the other way is used, even if this means 100 companions could dig a trench with a single shovel.
- Rejected any notion of trying to figure out how useful additional companions would be based on what's constructed, as that would be a rather complex issue.
- Some other formula for how additional companions set on the task would scale. Some tasks would be faster with multiple workers (digging a trench), while others would benefit little or not at all (digging a well/a tower), while others would benefit greatly from 4 hands rather than two. Linear scaling seems to be good enough for a reasonable fit, especially since most camp construction blueprints are large enough that several companions could work on their own set of tiles in parallel.
- Ignore it while waiting for camp construction to be morphed into construction zones. However, it seems there's quite a lot of waiting before that functionality has sufficient maturity and support to be used for camp blueprints. We can wait for that with this functionality in place.
- Assign some arbitrary max number of companions that can be assigned to each construction mission. Decided the natural limit imposed by the number of companions available is probably better. If someone amasses 100 companions and gets a construction task done in minutes, more power to them (and a minor consolation prize when trying to manage a horde).
- Changing the companion return logic so multiple companions can be announced at once.

#### Testing

Assigning one and two companions to camp and expansion upgrade tasks and verifying that things behave as expected when finalizing and emergency recall companions.

#### Additional context

Expansion task selection. No change in functionality, but note the time (2 days, 6 hours):
Screenshot (210)

Selection of a companion. Again, no change from the current functionality:
Screenshot (211)

Selection of the other companion. The prompt text is different (and there's no abortion message when not selecting a additional companion):
Screenshot (212)

The two companions are working on the construction: Note that there are two of them, and the time listed is half that of the original (single companion) time (but could be different due to work days conversions):
Screenshot (213)

The same job one day later:
Screenshot (214)

The same job after having emergency recalled one of the companions, with double the time remaining:
Screenshot (215)

A different time line where nobody was emergency recalled, and two days have passed from the start:
Screenshot (216)

Result when recalling the two companions from their completed task:
Screenshot (217)

And after dismissing the previous popup the second companion is also announced:
Screenshot (218)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
There's probably something wrong with a support tool, as I received an Email referencing "Pull Request Labeler: No jobs were run" with the following (although no failures were indicated in the list of checks yet):

Invalid workflow file: .github/workflows/labeler.yml#L12
The workflow is not valid. .github/workflows/labeler.yml (Line: 12, Col: 9): Unexpected value 'sync-labels'

**Comment by Maleclypse** [comment]
There is a bugfix the labeler in play.

**Comment by PatrikLundell** [comment]
"[Clang 12, Ubuntu, Tiles, ASan](https://github.com/CleverRaven/Cataclysm-DDA/runs/5431719084?check_suite_focus=true#logs)": failed due to some broken monster attack test:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Mods-(~[slow] ~[.],starting_items)=> cata_test is a Catch v2.13.7 host application.
Mods-(~[slow] ~[.],starting_items)=> Run with -? for options
Mods-(~[slow] ~[.],starting_items)=> 
Mods-(~[slow] ~[.],starting_items)=> Randomness seeded to: 1646472042
Mods-(~[slow] ~[.],starting_items)=> 
Mods-(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
Mods-(~[slow] ~[.],starting_items)=> monster_throwing_sanity_test
Mods-(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
Mods-(~[slow] ~[.],starting_items)=> ../tests/monster_attack_test.cpp:176
Mods-(~[slow] ~[.],starting_items)=> ...............................................................................
Mods-(~[slow] ~[.],starting_items)=> 
Mods-(~[slow] ~[.],starting_items)=> ../tests/monster_attack_test.cpp:230: FAILED:
Mods-(~[slow] ~[.],starting_items)=>   CHECK( damage_dealt.test_threshold( epsilon_threshold{ expected_damage, 2.5 } ) )
Mods-(~[slow] ~[.],starting_items)=> with expansion:
Error: Mods-(~[slow] ~[.],starting_items)=>   false

**Comment by PatrikLundell** [comment]
Another win for the house in the test casino:

"LGTM analysis: C/C++" timed out as usual.

**Pull request merged**
