### PR TITLE
fire additions

### PR DESCRIPTION
**Pull request by Jo-Neto**
compile with the few lines of code I changed on fire, spawn a survivor with 8 status (str, dex, int, per), leather armor, level 2-3 combat skills (dodge, melee, bash, pierce, cut)

the most OP ones might be a bit too much for the above survivor, but they can be set to spawn at lategame or more spawn-weight, and the robots to spawn on the appropriate place.

there's two problems:

1- in my version of the game, which is 6 months old, there were more changes related to
how much the survivor clothes burn, and I couldn't find the code on the current version of the game, if needed I can provide my current version of the game for testing, so maybe the survivor will burn for too long until all the clothes are destroyed, and the mod will be extremely imbalanced.

2 - I may be biased because I like to struggle

In vanilla running on small fires would break your leg, some times just a simple 1 HEAT damage on your torso would also, kill you, because your shirt will burn for several turns on most materials. In the version that I play, fire monsters are not a death sentence, they most of the times leaves a leather cloth in the "burnt" state, most of the times they need the survivor to make 2 or 3 mistakes before losing that clothing to fire. (unless they walk on 2 tiles of fire, or sometimes 1 tile of large fire, or something like that)

Also, fire hurts, yes, if you run on large fire you are most likely to get pretty hurt, 2 tiles of large fire is almost always death, 2 tile of small fire means pain and hurt feet. if you you walk instead of running, it's even worse.

This opens up some gameplay possibilities, the player worrying if their base may catch fire attracting the wrong monster(especially with hordes on), that they may need to have a backup fire cloth depending on what they are doing, as well as carrying the throwable-fire-foam and grappling hook, and stocking up fire extinguishers

### CODE REVIEW

**Comment by NetSysFire** [comment]
This is a giant change which will be hard to review. There is also inconsistent use of whitespace and terminal punctuation.

You may want to read https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#all-prs-should-have-a-summary-section-with-one-line so the PR validator gives you a pass.

**Comment by Jo-Neto** [comment]
I just posted this here for testing purposes, this PR is by no means ready to be merged to the basegame, if I get positive feedback, I may be willing to put some love to it

**Comment by NetSysFire** [comment]
Then please convert your PR to a draft PR

**Comment by Night-Pryanik** [comment]
Please follow the PR template and rewrite the PR's description. I struggle to understand what's your PR is all about. Is this a new mod? Is this a change to vanilla? There should be a clear and concise description of what and why you've done.

**Comment by fairyarmadillo** [comment]
I think you should remove all of the extra enemies, update this to the current experimental, and make it into a proper contribution rather than a mod. We do need saner fire effects, but there's too much going on here to really give meaningful feedback.

**Comment by Theawesomeboophis** [comment]
This is an almost exact port of World On Fire, a third party mod, with udp support intact.

https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/tree/master/Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/World_On_Fire

**Comment by fairyarmadillo** [comment]
> This is an almost exact port of World On Fire, a third party mod, with udp support intact.
> 
> https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/tree/master/Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/World_On_Fire

lmao

**Comment by Jo-Neto** [comment]
Its a balanced version of this mod, 70% of it has been changed

**Comment by sonphantrung** [comment]
You should strip anything monster, tiles, anything but fire effects

**Comment by anothersimulacrum** [comment]
I am not sure we can accept this without proper attribution to original authors.

**Pull request closed without merging**
