### PR TITLE
tilesets and looks_like: add some looks_like to cover ChestHole gaps

### PR DESCRIPTION
**Pull request by mlangsdorf**
This isn't everything that Chesthole is missing, but it covers several
that don't have tiles currently.

### CODE REVIEW

**Comment by Faalagorn** [comment]
How does it compares with things in #23716 ? Assuming that will get merged eventually aren't some items covered there already and we're just duplicating work especially as I think this PR basically just waits for a reply from @Chezzo because of (WIP) status (though I have to admit, I didn't try merging this PR locally to see how it works)?

**Comment by mlangsdorf** [comment]
This PR uses looks_like to tell the tileset loader to load other tiles if it can't find a tile. See  #24747
#23716 would add the proper tiles and the looks_like entries would be ignored.

There's no conflict, I'm not adding any tiles, there's no wasted work. All this is doing is saying "if you don't have a tile for mon_deer_fawn, you should see if you have a tile for mon_deer" and use that.

For instance, mxotto32+ is up to date, and would ignore the looks_like field.

**Comment by Faalagorn** [comment]
For the moment I forgot about other tile sets, as they will clearly benefit from those changes, including those that are yet to come due to the fact of ChestHole being de facto standard for the showcases :P.

Disregard what I said then, as even with ChestHole having 100% coverage at day0 (which by itself is unlikely) this will be always useful nevertheless and thank you for the work!

**Comment by ZhilkinSerg** [comment]
It actually fixes any tilesets.

image

**Pull request merged**
