### PR TITLE
JSONizing CBM slot feature

### PR DESCRIPTION
**Pull request by Firestorm01X2**
JSONnizing CBM slot feature

Feaure was hidden with debug mutation. Now it is can be enabled or disabled via EXTERNAl OPTION "CBM_SLOTS_ENABLED". So it can be enabled via mod.

https://github.com/CleverRaven/Cataclysm-DDA/pull/15937

Feature is still functional but may not be fully balanced. That is why it is disabled by default. But now it can be enabled via JSOn editing. So It can be enabled via mod

**Feature is disabled by default. So it is just infrastructure change.**

#### Summary

SUMMARY: Content "JSONnizing CBM slot feature"

#### Purpose of change

https://github.com/CleverRaven/Cataclysm-DDA/projects/6

JSONnizing CBM slot feature

#### Describe the solution

Feaure was hidden with debug mutation. Now it is can be enabled or disabled via EXTERNAl OPTION "CBM_SLOTS_ENABLED". So it can be enabled via mod.

Debug mutation to enable slot system was removed. It is not needed anymore.

#### Additional context

None.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
#15937 is for reference.

**Comment by Firestorm01X2** [comment]
@Night-Pryanik 
Can I soften CBM installation skill requrments here? It is additonal restriction for player. CBM sofware it bit TODO and player should be tmepted to constatly install and reinstall CBMs now.

**Comment by Night-Pryanik** [comment]
>Can I soften CBM installation skill requrments here?

No. It should be done in a separate PR.

Furthermore, please do tell why do you think there is a need for softer requirements. With usual "expected vs. actual" comparison, numbers, calculations etc. The "additional restriction" is not a valid reason for easier installation.

**Comment by Firestorm01X2** [comment]
>Furthermore, please do tell why do you think there is a need for softer requirements.

To balance new restriction. Guranteed way to install CBMS are big TODO for now.

With slot system player should constantly tweak himself to fit current needs. It will be hard until raising skills.

**Comment by Firestorm01X2** [comment]
>No. It should be done in a separate PR.

Then it is ready.

**Comment by Night-Pryanik** [comment]
> To balance new restriction.

In this case CBM slots restriction should raise skill requirements instead. Imagine - now we have limited space in our body, and every new CBM should be installed in a way that shouldn't interfere with the previously installed CBMs. Each new CBM require more and more skill to successful installation.

**Comment by Firestorm01X2** [comment]
>In this case CBM slots restriction should raise skill requirements instead. 

It may just force player to install only few CBMS instead of filling slots.

**Comment by Night-Pryanik** [comment]
> It may just force player to install only few CBMS instead of filling slots.

And why should they necessarily fill slots in the first place?

> Something has to compensate requirement to constantly jiggle CBMs.

Bionics are already OP, big advantages without any drawbacks. Difficulties and complications of bionics (un)installation are already compensated by their own coolness.

**Comment by Firestorm01X2** [comment]
>And why should they necessarily fill slots in the first place?

To as adapted and strong as player can be.

**Comment by Firestorm01X2** [comment]
>Every wish has its own price. In this case its increased requirements on skills and difficulty of the (un)installation process.

Slots is restiction iself. I recommend to tweak certain CBM. For example ta make really powerfull CBM fill almost all free space in player body. So player more reason to uninstall it. It is much simplier solution.

**Comment by Firestorm01X2** [comment]
> What has changed to make it "time for this"? 

Delaying of 0.D. Feature was disabled in the furts place because people thouht that 0.D was adound corner. It was almost 2 years ago.
Also this feature much less articial in comparsion to other restrictions.

**Comment by Firestorm01X2** [comment]
Ah, yes. Also this: https://github.com/CleverRaven/Cataclysm-DDA/projects/6

**Comment by I-am-Erk** [comment]
The feature was delayed to 0.D because it was only halfway implemented. It is still only halfway implemented, and this is a particularly odd time to cite 'delayed release of 0.D' as a reason, since progress to the next version is moving pretty steadily right now.

Do you intend to complete the other elements of bionic slots, like balancing bionic slot availability and slot occupation, or making faulty bionics a part of the bionic piece itself rather than a separate bionic? Per the project, those should be done *before* the slots are mainlined. If you want to go through that stuff, then it's not a half-done feature and could certainly be re-enabled. Be aware though that you'll probably face significant discussion and debate around the balance element, because it's a complex feature.

**Comment by Firestorm01X2** [comment]
@I-am-Erk 
>Do you intend to complete the other elements of bionic slots, like balancing bionic slot availability and slot occupation, or making faulty bionics a part of the bionic piece itself rather than a separate bionic? 

You, know. You right. I think I am not going to do that.

Instead les't reporpuse this PR. Now it wil lbe just JSON switch to enable CBM slots. And it will be disabled by default.

**Comment by I-am-Erk** [comment]
Making it a json switch is pretty reasonable, having it concealed in debug is a bizarre solution.

**Comment by Firestorm01X2** [comment]
>Making it a json switch is pretty reasonable, having it concealed in debug is a bizarre solution.

I think it was done before EXTERAN OPTIONS were implemented. Likely that is the only reason.

**Comment by nexusmrsep** [comment]
> The feature was delayed to 0.D because it was only halfway implemented. It is still only halfway implemented, and this is a particularly odd time to cite 'delayed release of 0.D' as a reason, since progress to the next version is moving pretty steadily right now.

If the other half is described and agreed upon, just point @Firestorm01X2 towards it. Postponing by saying "someone will pick it up after 0.D" sounds like saying "lets not think about it unless we see some pegazi flying in the sky". 0.D is a mythical being, you cannot guarantee seeing it in a month, or a year, and also since when is anything postponed on this ever-rolling train of a development system, when there is someone willing to do the work, and the work itself is agreed on? I believe only @Coolthulhu absence is the reason why it is stuck. It predates autodoc and anesthesia and was meant as a first major limiting factor. It finally addresses the scarcity of human body. (hmm.... threshold for CBMs... no longer human... robocop.... hmmm). So I say - unless there are any significant objections toward the slot concept itself - instead postponing it, its as good time to do it as any other.

**Comment by Firestorm01X2** [comment]
I have to point the fact that feaure shows slots and limits installation. 

I don't know what is half implemented there but feature looks functional.

**Comment by Firestorm01X2** [comment]
If only problem is balancing then slots are ready. 

Broken CBM occupuing part actually make sense. You have to remove it. Just like it is now. Other things can be done later.

**Pull request merged**
