### PR TITLE
Synchronize charcoal smoker need for charcoal with adequate recipes

### PR DESCRIPTION
**Pull request by nexusmrsep**
#### Summary
```SUMMARY: Balance "Synchronized charcoal smoker need for charcoal with adequate recipes."```

#### Purpose of change
As @mlangsdorf noticed, charcoal smoker's need for charcoal was not synchronized with recipes. Smoked food recipes were left untouched and their requirement for charcoal were lower. Smoker was set at 100 charges per one kilogram of food, while smoking meat (etc.) in recipes was set to 25 charges per kilogram (15 charges per 3 meat at 200 g per chunk equals 25 charges per 1000 g). Minimum is still set to 100 charges regardless of inserted food, since it has to have fuel to stay lit for 6 hours strait.

#### Describe the solution
Quick one value change in the code.

#### Describe alternatives you've considered
Removing the recipes, but that's not an option realy, since that still serve a purpose.

#### Additional context
N/A

### CODE REVIEW

**Comment by mlangsdorf** [comment]
I still think that:
long char_charges = 100 * to_liter( food_volume ) < 100 ? 100 : 25 * to_liter( food_volume );
is more clear as:
long char_charges = std::max( 100, 25 * to_liter( food_volume ) );

other than that, looks good.

**Comment by nexusmrsep** [comment]
@mlangsdorf I went for your suggestion.

**Comment by kevingranade** [comment]
Even simpler change now that there was an intervening refactor.

**Comment by KurzedMetal** [comment]
Charcoal smoker was already a bit too low in capacity and kinda annoying use due to having to recharge too foten. With this "nerf" it will make it super annoying to use.

I think this charcoal smoker is based on a 2L metal tank, which is rather small. It would be nice if a bigger charcoal smoker, is added or the existing one is "ugpraded" into a ~10L metal tank (built from either sheet metal or a 20L metal tank from a large fire extinguishers + leftover of metal instead of a 2L metal tank).

Example:
This is a 2L version: [https://www.amazon.com/Weber-7447-Compact-Rapidfire-Chimney/dp/B009IH0ICG](https://www.amazon.com/Weber-7447-Compact-Rapidfire-Chimney/dp/B009IH0ICG)
This is a ~8.5L version: [Cuisinart COS-118 Vertical 18" Charcoal Smoker, Black ](https://www.amazon.com/Cuisinart-COS-118-Vertical-Charcoal-Smoker/dp/B01GFLYWF6)
This is a 9.5L version: [Char-Broil Bullet Charcoal Smoker, 20" ](https://www.amazon.com/Char-Broil-Bullet-Charcoal-Smoker-20/dp/B074Y9LXG7)

**Comment by nexusmrsep** [comment]
> With this "nerf" it will make it super annoying to use.

What nerf? This PR changes it's requirements for charcoal and not the
volume capacity for food that still is 20 liter, isn't it?

czw., 20 wrz 2018, 14:26 użytkownik KurzedMetal <notifications@github.com>
napisał:

**Comment by kevingranade** [comment]
Please test the code in the game before complaining, this has the opposite effect of what you think it does.

**Pull request merged**
