### PR TITLE
Fungal spread forever

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
Features "Fungal spread overhaul"

#### Purpose of change
Handling of fungal areas has been problematic for roughly forever due to the requirement that spread only occurs when near the player is nearby, triggered by monster specials, therefore necessitating that the spread occurs FAST.  As a result, spread scales based on how much time the player spends nearby. This sets up a perverse incentive to simply stay away from fungal areas at all times since dealing with them is self-defeating unless you have overwhelming resources.

#### Describe the solution
This completely overhauls how fungal spread occurs, instead treating the entire area as a single massive organism. This necessitates adding some new infrastructure for such a coherent area  at the overmap level so that it can be updated even when the player is not present.  Compensating for the constant spread, it can now occur very slowly and still make meaningful progress.

The growth model is constant rate addition of area, which means that as the area continues to grow, the rate of increase of the *radius* drops off sharply.
The first week of growth is illustrative, assuming one tile per 10 minutes.
Day one, 144 tiles, 6.7 tiles of radius.
Day two, 288 tiles, 9.5 tiles of radius.
Day three, 432 tiles, 11.7 tiles radius.
Day four, 576 tiles, 13.5 tiles radius.
Day five, 720 tiles, 15.1 tiles radius.
Day six, 864 tiles, 16.5 tiles radius.
Day seven, 1008 tiles, 17.9 tiles radius.
Day 30, 4320 tiles, 37 tiles radius.
Day 365, 52,560 tiles, 129.3 tile radius.

The way this growth is realized is somewhat indirect, there is a counter that literally tallies up a count that is "time since cataclysm" divided by some number, something in the ballpark of 10 minutes per tick (configurable in json).  This area is then used to determine the area of effect as a radius, which is then used to determine whether a given tile has been altered.
In order to not simply have a boring perfectly circular area, I've added a feathering function that hashes the absolute coordinates of individual tiles to determine how far the growth needs to advance before that tile is altered.  If you're familiar with the concept this is essentially a noise function.

Independent of the growth rate, a rather complex part of the system is dealing with damage.
Modified tiles are treated as a resource, both absorbing damage and being expended in order to attack the player (this is not implemented yet).  In the fully realized system this is where all fungal "creatures" will come from, a number of tiles will go into some kind of dormant state, and a fungal creature will be produced.  The larger the creature the larger the number of tiles would be expended to make it happen.
When tiles have been altered but then reversed, either by damage or being spent to create attacks or attackers, growth is halted and resources are instead redirected toward "healing" these lost tiles, and normal growth is not resumed until all such tiles are replaced.
Internally this is tracked by the number of tiles "lost" within a given OMT being tracked, and then when new growth events occur, the tiles are randomly distributed to the affected OMTs. The next time that OMT is loaded, the distributed tiles are applied, again to random eligible tiles within the OMT.  Alternately, once the number of "healed" tiles equals the number of "destroyed" tiles within an OMT entry, the two numbers "cancel out", and since there is no "tiles lost" entry for the OMT, they are automatically repopulated the next time they are loaded.

I found that fire works entirely too well against a contiguous fungal bed.  For now I've made them non-flammable, but I want to instead make them *less flammable*. You should be able to torch an area quite rapidly with a flamethrower, but that might require adjustments to the flamethrower.

#### Testing
This have been a number of issues that have cropped up during development that we need to continue to look out for.
This code has occasionally caused noticeable slowdown, but I believe that the overhead is negligible in its current incarnation.  Catching up as the reality bubble loads affected areas is very fast, and the overhead of occasional growth ticks is completely negligible.  I do need to test what happens when a very large zone is mostly destroyed and then starts healing, as each growth tick will trigger an iteration over the whole set of OMTs within the zone, but as this number of OMTs always remains small it should remain negligible.

#### Remaining issues:
- [x] I want to rename stuff, everything is called "nodes" and I'm not happy with that, but I don't have alternatives I'm happy with either.
- [ ] Need to update flamethrowers and chemical sprayers and chemical grenades to hit larger areas and/or be more reasonable to rapid fire.
- [ ] Need the fungal bed terrain to be flammable enough to be burned by flamethrowers and molotovs, just not something that will spread on its own.
- [ ] I want to add a minimal kind of enemy spawning feature. Probabably just spawning and then reabsorbing the existing spore entities and various fungaloids.
- [ ] I need to look into improving the detection of damage.  Right now it periodically scans the loaded map, and scans map chunks as they are unloaded in order to tally up missing fungal tiles, but it's probably more performant and future-proof to add a hook to the terrain definition that calls a function when the terrain is destroyed.
- [ ] Only the fungal tower has this feature defined for it, the other fungal zones need it as well.
- [ ] Overhaul the core terrain special for the fungal zones, probably something more like just a scattering of tower/flower enemies and minimal other entities.
- [ ] Completely remove the fungal creature ability to fiungalize terrain along with the mods that adjust it.

#### Deferred Features
- [ ] Later I want to have a multi-tiered thing where the inner part of the zone develops denser, tougher, and more aggressive fungal features, up to and including a maze of fungal walls that are very difficult to breach.
- [ ] I want to add a variety of special attacks the fungal mass can make, such as spawning tendrils, emitting different kids of spores or poison gasses, etc.
- [ ] At some point we might want these zones to be able to produce a mega-spore that can go establish new fungal zones.
- [ ] The code currently assumes these zones will never overlap, I'll test what happens when they do, but I'm not too concerned with having it function better than "not completely failing".

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I don't like this at all. As far as I can tell this means the mycus will eventually take over everything and kick out the blob. It also means that the player is doomed as fungal areas will gradually restrict movement when free corridors are cut off, until the growths approach you from all directions. Fleeing is not an option as it's as bad everywhere else (well, you might find an island somewhere on which you can twiddle your thumbs for the rest of your life). The current mycus is very bad, but this is even worse, and I don't see there being any chance to fight it at all. Sure, you might be able to harm a few tiles a little, but then you have to sleep and it's recovered with interest when you wake up. Can you even "kill" a single tile in 10 minutes so you'd keep up with regrowth even when actively fighting it (and this is ignoring the fact that you'd need to spend a lot of time crafting the "ammo" needed to fight it, and scavenge for the components needed for crafting)?

**Comment by Shibimon** [comment]
> At this point that kind of thing needs an implementation, not a vague suggestion. If you have a specific and detailed idea of how it would work sketch it out and I can consider it for a later version.
That sounds great, but i dont have proper knowledge of how the mycus worked before and even less of how will work now with the new changes.
Will need to ask lots of questions that i think might be out of the scope of this PR like how the game could handle the location of the spawn of the new structures of spread that you mention in these changes, maybe a big chance of new structures spawning inside forests, and a low chance of spawning outside, or if could have some factor based on fungalized creatures that affects the speed of growth. I think that rain affecting growth could be the easiest to implement but since i have no idea it could be really hard to do.
It is an idea that needs proper analysis and hopefully i could help in the future since im starting to learn how to code.

**Comment by PatrikLundell** [comment]
Killing fungaloids is less useful than stamping out fire that's spreading over containment lines in real life, because fire will eventually use up all the fuel within the line and die out, while the mycus will keep generating more resources over time to replace what's lost, which means that at some killing rate you're stopping the spread for as long as you keep at it, but as soon as you stop it will start spreading again. Also, you can't just kill off the ones that you happen to stumble upon, but rather have to hunt them down.

Now, if the mycus needed fungaloids to expand, to e.g. prepare the soil for the mycelium or something like that you'd be able to stop the expansion in your direction with a limited effort, even though the mycus could continue to spread in other directions. That would require an additional layer of logic, though.

**Comment by kevingranade** [comment]
> How will killing the core structure (tower/spire/giant flower) affect the zone?

Good point, I don't have the details hammered out, but yes at a minimum it will consume a great deal of resources to restore, and halt growth until it does.
Once there are more attack options, eliminating any larger structures will limit the fungal mass' ability to attack.
Killing the central structure won't necessarily eliminate the entire mass, but it will get you most of the way there.

> Even if it doesn't reverse the effects but rather makes the tile into dead and dry fungus would be good.
>  is there anything the player can do to fight it?

You can actually take it down with attrition after this, I am planning on making fire a viable option, just not trivial.
You probably won't want to try to burn the whole thing down, but it should work to clear a path.

**Comment by Nebnis** [comment]
Also +1 to killing towers limits/stop the fungal growth entirely. It gives the players a meaningful objective and you could add stronger dangers near the central path to challenge the player.

Another thing i would like to see changed is the fungal infection, because right now it is too deadly and risky to even begin thinking about fighting them, and the means to protect yourself are limited as well or hard to find, making players always turn tails to fight the mycus. The infection could be limited to either deadlier creatures near the central tower or by making it less deadly or easily treated like zombie deep bites.

**Comment by PatrikLundell** [comment]
Long enough, yes, unless the blob develops zombies that can deal with the mycus, which it probably would. However, according to the lore, the blob should also have developed zombies that will wipe out whatever normal life there is by that time. Those zombies don't exist currently, but I don't think dying of old age does either, and that should happen sooner than complete coverage would.

**Comment by MarceloLaser** [comment]
> How does this thing interact with infinite world? With a long enough game, if the distribution of fungal blooms is uniform, the part of the map that the player couldn't even have interacted yet with is going to be fully covered with fungus.

I second this point. While games longer than a couple seasons are fairly uncommon in the community (at least the more vocal parts of the community), the potential for enclosing the player should not be ignored. Given enough fungal OMTs within a radius of even 100-150 OMTs from the player's base, the player could become completely enclosed by the mycus within 3-4 game years. That may seem like such a long time that basically no one would ever need to face the issue at all, but at the same time, this whole feature is essentially targeting long-term players, so they're probably the ones who need to be considered the most. The people who play for only 1-2 seasons before restarting are likely to continue to ignore fungus: it just won't spread fast enough to be an issue for them, they'll prefer to just go look for a lab in another direction.

The notion of some sort of attrition between mycus and blob seems like a good way to deal with this, or maybe even attrition between factions in a general way. Assign certain OMTs an "owner faction" with their own spread values, which could work the same way as the fungus does as per this feature, and then calculate ownership of given OMTs based on proximity and faction spread power. Obviously some factions are either not interested in or not capable of spreading (like the refugee center), but they should have a fighting chance to not be wiped out if the player doesn't find them quickly enough. This makes it so the mycus is an interesting and real challenge to late-game players, without making it ultimately so powerful that very late-game players become averse to it. It could also make for an interesting alternative to zombie hordes: if the blob owns a "circle" of OMTs, it can spawn zombies outside of its usual towns and bases, meaning if a player does not deal with the problem in a final way, eventually the zombies will make it to their base, creating a real need for base defenses that hasn't really existed until now. Though I can't really think of what a "final solution" to a blob-controlled OMT would be; just killing every zombie in town doesn't really sound final enough to me.

**Comment by I-am-Erk** [comment]
As it stands I do not think that @kevingranade is going to get time to finish this in time for stable, because he's an extremely limited resource. I am going to defer it with a heavy heart unless ordered to do otherwise.

**Pull request closed without merging**
