### PR TITLE
Add sees_player_hitbutton mod

### PR DESCRIPTION
**Pull request by kristleifur**
#### Summary
```SUMMARY: Content "Add sees-player mod for HitButton_iso"```

#### Describe the solution
Adds a little exclamation mark highlight to entities that have spotted you. Red for hostile, yellow for neutral, green for friendly, pink for Other. (Whatever that is?)

#### Additional context
Screenshot 2019-06-06 at 00 39 38

### CODE REVIEW

**Comment by AMurkin** [comment]
tinypng.com have compressed sees_player_hitbutton_green.png from 1.2 KB to 114 B.

**Comment by AnthonBerg** [comment]
I see there's something wrong with my summary line and seemingly with some JSON formatting! Will fix.

**Comment by Leland** [comment]
> tinypng.com have compressed sees_player_hitbutton_green.png from 1.2 KB to 114 B.

TinyPNG is a no-configuration lossy compression service, FYI. Those default settings work quite well for web images but I saw visible degradation when I was compressing files on #21685. Lossless is the way to go IMO, or _very_ light touch lossy compression

**Comment by anothersimulacrum** [comment]
I know halfahermit uses or has used pngcrush when they have done RetroDays tile updates (see #28928), so maybe you could look into that?

**Pull request merged**
