### PR TITLE
added "SHEATH_KNIFE" and "SHEATH_SWORD" to appropriate bayonets

### PR DESCRIPTION
**Pull request by kd8qdz**
"SHEATH_KNIFE" for all bayonets except Sword bayonet that got
"SHEATH_SWORD"

### CODE REVIEW

**Comment by mugling** [comment]
Have you checked this doesn't result in you being able to holster a small gun with bayonet in a scabbard or other such?

**Comment by kd8qdz** [comment]
Just checked.  doesn't give you the option when the weapon is not in bayonet mode.  When it is, its considered too large to sheath.

**Comment by mugling** [comment]
That's a future bug waiting to happen. I bet you can get a sawn down rifle with folding stock and a sword bayonet to fit in a scabbard...

**Comment by kd8qdz** [comment]
so.. we need to add a check to the holstering mechanics to make sure the item isn't attached to another item.

**Comment by mugling** [comment]
The issue is that item flags are inherited from any contained items. Changing that behavior is going to break a **lot** of stuff that we might not anticipate which doesn't seem like enough of a reason to allow sheathing of a bayonet?

**Comment by kd8qdz** [comment]
a bayonets have been stored in sheaths since there were bayonets, which is why we should try to allow it.   I wasn't suggesting we break the flag inheritance, but add a conditional check on the sheathing/scabbording functions to make sure that even though its got the appropriate flag, it doesn't have that flag though inheritance, or some other method to keep gun from following the bayonet into the scabbard.

**Comment by mugling** [comment]
You're not wrong but this is a corner case. I'd rather avoid accumulating such kludges unless there's a significant payoff. For example when we implement nested containers such a bug is likely to recurr in a subtly different manner

**Comment by mugling** [comment]
Requires large scale infrastructure changes to handle corner-cases

**Pull request closed without merging**
