### PR TITLE
Draw stop lines on intersections

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Content "Draw stop lines on intersections."

#### Purpose of change
Continuation on making our cities slightly more realistic.

#### Describe the solution
Added yellow-dot stop lines on four-way and tee-shaped intersections, only if there are also traffic lights on these intersections (since we don't have STOP signs yet).

#### Describe alternatives you've considered
None.

#### Testing
Teleported around cities' and rural area's intersections and checked if everything is ok.

#### Additional context
Four-way intersection
изображение

Tee-shaped intersection
изображение

### CODE REVIEW

**Comment by Hirmuolio** [comment]
A bit silly idea: Could the driving side be defined in the `regional_map_settings.json`.

**Comment by Night-Pryanik** [comment]
> A bit silly idea: Could the driving side be defined in the regional_map_settings.json and then change the stop line side based on that?

I guess that's possible, but I think that's an idea for some other PR.

**Comment by 8street** [comment]
@Night-Pryanik At a crossroads after the stop line there should be pedestrian crossings. So you should leave some room for them. For example
[](https://st4.depositphotos.com/4157421/24233/v/600/depositphotos_242337848-stock-video-aerial-view-intersection-road-junction.jpg)

**Comment by Night-Pryanik** [comment]
Ok, moved stop lines a bit in preparation for adding a pedestrian crossing.

**Pull request merged**
