### PR TITLE
Fix cash card stacking and display

### LINKED ISSUE #31716: Cash cards not formatted properly when examined on ground
# Describe the bug
image
Cash cards in the examine screen aren't formatted properly.

# Steps To Reproduce
1. Get a cash card.
2. Drop it.
3. Examine the tile so you can pick up the cash card.

# Expected behavior
image

# Screenshots
See above

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4799-g044439e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context
N/A

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Fix cash card stacking and display"

#### Purpose of change
Fixes #31716.

After the recent change (#30874) to allow multiple ammo types, cash cards needed different code to identify them as such.  This check was happening in many places, some of which were updated, but not all.

#### Describe the solution
Add a new function `item::is_money()` to make factor out this logic and use it in all the places.

Also tweak how the advanced inventory handles stacks from a character inventory.  Previously it wasn't rendering mixed-value stacks properly.

This fixes various issues related to cash cards like them not stacking any more or strange messages when you pick them up.

#### Describe alternatives you've considered
We might want to make stacking of vari-charges items an generic item flag, rather than money-specific.

#### Additional context
Here's the before-and-after messages in a single screenshot:
cata-cash-card-messages
And here are two differently-valued cash cards stacking in an inventory:
cata-cash-card-stacking

### CODE REVIEW

**Comment by EvgenijM86** [comment]
I have encountered the same bug for "chunks of chitin" item.

**Comment by jbytheway** [comment]
> I have encountered the same bug for "chunks of chitin" item.

There are various different aspects to this bug.  Can you clarify what you mean?  Perhaps a screenshot?

**Comment by EvgenijM86** [comment]
> > I have encountered the same bug for "chunks of chitin" item.
> 
> There are various different aspects to this bug. Can you clarify what you mean? Perhaps a screenshot?

I have posted screenshot above. Is it not visible? Here is direct link - https://user-images.githubusercontent.com/430076/59964949-7ebf6a80-9510-11e9-936a-41f847a9ed70.png

I would assume that "chunks of chitin" should stack together, just like sinew and other non-perishable items. Or maybe I am wrong and they have some sort of durability stat that is different for each chunk of chitin - then this is not a bug in this case.

**Comment by jbytheway** [comment]
It shows now; don't know why it didn't before.  This must be caused by some kind of hidden stat; not sure which one.  But the fact that you can't see what it is makes it a bug, IMO.  But it's almost certainly unrelated to this cash card issue, so out of scope for this PR.

**Comment by alanbrady** [comment]
> This must be caused by some kind of hidden stat

I believe if the items are not *exactly* alike they will not stack.  So different rot/birthday/temperature, almost anything will make an item not stack with each other.  This *why*  cash cards need the exception because they're saying it's ok we don't have the same ammo amount we can stack anyway and we'll handle it ourselves by storing a list of ammo amounts such that whenever you pull a cash card off the stack it pops an internally saved value off to make the "new" cash card.

**Comment by alanbrady** [comment]
Further context for anyone unaware, stacking coalesces multiple items down into one item in such a way that we don't need to track each individual item and just say "I have x number of items exactly like this" so that unstacking them is trivial.  Stacking causes them to lose any individual properties, so if they're not exactly alike we do not stack.

**Comment by Inglonias** [comment]
YAAAAAAAAAY

**Pull request merged**
