### PR TITLE
Add alternative magazines

### PR DESCRIPTION
**Pull request by mugling**
Migrates remaining `9mm` and `22` weapons and then adds alternative magazines for `bore` conversions.
- Only conversions possible according to `acceptable_ammo` and `mod_targets` are defined.
- Consideration is given to the shape and orientation of a magazine. This does help to provide some further distinction between the otherwise similar `46` and `57`.
- Leadworks guns can only be converted to use other leadworks magazines
- `9mm` and `22` rifles are now convertable to `46` and `57` as this adds some more interesting options. For example a ruger 10/22 with rifle scope, compact suppressor and extended magazine could make for an interesting weapon when converted to `46` - if of course you could actually find the right and install all the required parts
- Conversions of shotguns is deprecated as it's not especially sensible and we already have slugs. A future PR could consider reworking the rifled barrel?
- Conversion from `3006` is deprecated as there aren't many (any?) reasonable options.
- Conversion from `9x18mm` could be added but I'm not convinced these guns would see much use in any case?

Relatedly but as a separate PR I'm considering implementing a before/after screen for trialing various combinations of gunmods.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> 9mm and 22 are now convertable to 46 and 57

Just curious - is this possible IRL? 9mm is almost twice the diameter of 4.6mm. It will require too big changes to internals to convert, no?

**Comment by mugling** [comment]
@Night-Pryanik I've edited the preamble to reflect the fact that I only added `rifle` to the list of `mod_targets` - such conversions were previously possible for `pistol` and `smg`

**Comment by Coolthulhu** [comment]
Generic Guns mods complains about calico mag.

**Comment by mugling** [comment]
Fixed in 3a4cbb2

**Comment by Coolthulhu** [comment]
Problems (more or less related):
* There is no way to tell what kind of magazine will be required after conversion
* Some possible combinations are useless. For example, Steyr AUG + .22 results in damage comparable to sling
* "Your x does not appear to be modded" when all mods are integrated

**Comment by mugling** [comment]
> There is no way to tell what kind of magazine will be required after conversion

Yes, this is the main motivation for wanting a before/after comparison

> "Your x does not appear to be modded" when all mods are integrated

Can you explain further?

**Comment by Coolthulhu** [comment]
An item modded with unremovable bore mod is modded, but activating it (to remove mods) says it isn't, because all mods are integrated. When the integrated mods thing was added, all integrated mods were added on spawn and so weapons with only integrated mods were indeed unmodded.

**Comment by mugling** [comment]
I see. Can you open that as an issue as I'm going to tackle some more of the gunmod code again soon and that' should be a relatively simple fix

**Pull request merged**
