### PR TITLE
Sun path based daylight

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary

Features "Sun angle based light"

#### Purpose of change

Sunrise and sunset are currently based on hardcoded times and linear interpolations in between. The result somehow feel "wrong". 

The new system is based on position of Sun.

#### Describe the solution

Old system:
* Dawn and sunset last 1h.
* Dawn starts at 05:00 - 07:00 depending on time of year.
* Sunset starts at 17:00-21:00 depending on time of year
* Day light varies from 75 to 125 depending on time of year. Brightest on summer day 1 and darkest on winter day 1, linear interpolation in between.

New system:
Day phases:
* Daylight is based on the angle of the sun.
* Sunrise and susnset are at 0°.
* Day is from 0° to 0°.
* Twilight (dawn and dusk) is from -18° to 1°.
* Night is from -12° to -12°.
* The phases overlap by few degrees. This is not a problem.

Day light:
* 75 at 0°, rises linearly to 125 at 20°.
* 0 at -18°, rises linearly to 75 at 0°.
* 0 at below -18°.

The duration of twilight during dawn and evening now depends on the time of year. In general they last much longer and the sunlight starts to dim before the sun fully goes below horizont.
The twilight lasts about 2 hours from.

Solar panels are a bit nerfed for summer but a bit buff for winter. In old system they got full day sunlight immediately after dawn ended. Now the sunlight varies over the duration of day.
The correct fix for this would be to not clamp max daylight light to 20° and instead allow it to rise to even higher peak at 90°. But I am not sure if having very bright sunlight causes problems for vision systems.

I am not completely sure about the light levels used here. They are pretty arbitrary and I don't know how they interact with the vision system.

There is also a new sextant tool. It can be used to see the altitude and declination of Sun.

#### Describe alternatives you've considered

Handle sunlight as lux.
Would allow more realistic vision. Doing this would require gutting the current vision system. Also since light beyond "full vision" doesn't do anything at all there is not much need for this.

Handle sunlight as W/m^2.
Would allow better solar panel handling. Would probably require some light solar panel rebalance. Would also make sulight warmth possible.

#### Testing

It works.

#### Additional context

https://en.wikipedia.org/wiki/Sun_path

Opens future for directional light. such as shadows and glare for one direction only.

Seasons could be based on the sun position. They are currently all of equal length which is not very good system.

### CODE REVIEW

**Comment by Salty-Panda** [comment]
The various implications you mentioned sound amazing

**Comment by jbytheway** [comment]
FYI, I have a local branch where I've also implemented 'real' Sun positioning, I was just waiting for the release to PR it.  My plan was to use it to implement directional shadows.

**Comment by jbytheway** [comment]
I published my version at  #48090.  You can see our calculations are very similar, although I think you're not taking into account the 'mean anomaly'.  I only implemented the calculation and unit tests; I hadn't got as far as actually changing any game logic.  My plan was to alter sunrise and sunset timing as you've done and leave it at that; the first PR should probably be as minimal as possible.

We've taken rather different approaches to the unit tests.  I have two types of tests:
* Ones that check for properties, rather than specific values (e.g. Sun being highest around noon).
* Ones that plot an ASCII-art image of the movement, to be a sanity-check.

I imagine we should be able to figure out a way to combine the best of the two implementations.

**Comment by Hirmuolio** [comment]
This is done in #48090

**Pull request closed without merging**
