### PR TITLE
Fridges no longer spawn loose, container-less eggs

### LINKED ISSUE #58536: Some eggs spawn outside of egg cartons
### Describe the bug

Refrigerators in houses can have egg cartons with some eggs in them, but they also contain standalone eggs.

### Steps to reproduce

1. Go to a fridge. (You can start in a house by selecting an In Town scenario like Missed, then going to the last screen on character creation and pressing `/`.)
2. Look at what's in the fridge (such as with `g`) and see what the eggs look like.

### Expected behavior

Eggs should be in egg cartons, because that's why egg cartons were added to the game (source: #47020), and it seems odd to have half of them rolling around on their own inside fridges.

### Screenshots

CDDA escaped eggs

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: d422ab7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Sometimes the total number of eggs is more than 12, so it's possible there are also twice as many eggs than there should be—one set in a carton, one set out. Of course, there's no reason a fridge couldn't have more than 12 eggs or 1 carton.

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
Content "Fridges no longer spawn eggs without cartons"

#### Purpose of change

I've only recently noticed that this is actually happening, and it's very silly indeed. I certainly haven't met anyone in real life that leaves loose eggs lying around in their fridge, at least. The change was implemented in #47080 but it wasn't mentioned in the comments or the OP, so I can only assume it was an oversight.

Resolves #58536

#### Describe the solution

Removed the extraneous egg spawn line that could spawn up to an extra dozen eggs without a container. Now, eggs will always be in cartons. This has the side effect of reducing the overall number of egg spawns, but I have a hunch that fixing loose eggs on the bottom of the fridge won't affect balance too badly :P

#### Describe alternatives you've considered

Keeping the extra eggs, just putting them in a carton. One thing that comes to mind is having the potential for a carton with one or two eggs to show up on a lower spawn rate, to represent that the fridge owner had gotten another carton before running out of the first one, but I'm not sure how many people in real life do that kind of thing or not so I opted on the safe side of making sure that eggs would always show up in cartons.

#### Testing

Jumped to some houses on my new world that were generated before the change. Eggs generated both in cartons as well as loosely inside of fridges. Then, I generated some new terrain and checked the fridges there. Extra eggs no longer appeared.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
#58536?

**Comment by Ilysen** [comment]
Will add mention of it to the OP - thanks

**Comment by Rabidweasel** [comment]
I always assumed that fridges in the US typically had one of those [plastic egg holders](https://www.4fridgemaster.co.uk/fridge-door-shelf-egg-tray/product.pl?pid=3239578) fitted into the door. They're pretty common in the UK even though most people I know don't use them and don't refrigerate eggs.

**Comment by Zireael07** [comment]
My fridge has it too, I still think it counts as a container in CDDA terms

**Comment by Ilysen** [comment]
I've heard that thrown around a few times, but for a few reasons I don't think it's what was trying to be represented here - in addition to spawning in 85% of fridges (and no fridge I've ever used has such a holder, at least here in the US), it also spawned *in addition* to eggs in cartons, which would negate the point of the holder to begin with. I figure that if it was meant to be an egg holder, it would be mutually exclusive with the cartons, instead of potentially spawning a full dozen eggs in a carton and a full dozen loose eggs as well. That, coupled with the fact that if it *was* an egg holder we could easily use a purpose-made pocket, is what makes me think it's not what was intended here, especially since there was no mention of such a thing in the PR that originally implemented the loose eggs

**Comment by Zireael07** [comment]
I wasn't saying that the holder explained loose eggs. I was saying that in CDDA terms, those eggs should still have a container of some sort themselves ;) But I phrased that badly

**Pull request merged**
