### PR TITLE
Lab end loot rebalance.

### PR DESCRIPTION
**Pull request by Soyweiser**
Makes lab end loot less likely to explode (by the bots being killed, and exploding). Which was pretty annoying, as that mean it was very difficult to get quantum solar panels. (they always got destroyed).

Added reinforced glass walls around the loot. Moved the dissectors. Added reinforced glass door terrain.

New setup one: http://prntscr.com/c0w4d4 (occurs 9 out of 10 times when the weapons end is chosen). This is the one in 10 end: http://prntscr.com/c0wcp5.

Also changed the repeated one in 3 chances to a simple dice roll up front. Yes, this changes the distribution a bit, didn't think that would be that much of a problem.

### CODE REVIEW

**Comment by mightyagrippa** [comment]
You can easily stay close to the initial distribution. It was 67%/22%/7% with a 4% chance of bum loot. Instead of going with your current 3/3/4 split just do 7/2/1 or 6/3/1. I do like moving away from the iterated roll model, this one is much easier to tweak.

**Comment by Soyweiser** [comment]
There, changed the values. Back to the old % values.

**Comment by Coolthulhu** [comment]
The science ID also needs to be moved inside the glass room.

**Comment by Soyweiser** [comment]
For some reason, I mind the ID being destroyed less, and it seems odd for there to be an ID there anyway. That is why I didn't move it inside as well.

**Pull request merged**
