### PR TITLE
Handcuffs markedly increase item handling costs

### PR DESCRIPTION
**Pull request by mugling**
Not a solution for #14882 but certainly inspired by it

### CODE REVIEW

**Comment by Coolthulhu** [comment]
What kind of impairment does it represent?
Problem with reaching into pockets or manipulating held items?
In case of the former, it should probably be a flat penalty - reaching into pockets is only a part of the action.
In case of the latter, it can be a multiplier, but later on may need correcting if cuffs become an armor (cuffs being a weapon is kinda weird). Wielding a 2-by-4 wouldn't be impaired much by cuffs, for example.

I'd go lower with the penalty, at least at first. If item manipulation costs later extend to some action that everyone does a lot, then getting cuffed may result in people dying to unexplained mechanics.

There should be some sort of a distinction between locked and unlocked cuffs.

This penalty could be a re-implementation of the removed inability to pickup with bionic weapons. Both (locked) cuffs and bionic weapons have NO_UNWIELD, though probably adding a different flag would be better.

On an semi-unrelated note, MAX_ and MIN_HANDLING_COST and VOLUME_MOVE_COST should be moved to player.cpp - they are only used there, no need to have them visible to almost all of the files in the game.
Having centralized constants makes sense when multiple files need it and there is no common header that should have this data or when the constant should stay constant between game versions. In other cases it only makes it harder to modify without having to recompile the whole game.

**Comment by mugling** [comment]
> On an semi-unrelated note, MAX_ and MIN_HANDLING_COST and VOLUME_MOVE_COST should be moved to player.cpp

`VOLUME_MOVE_COST` is required by `holster_actor` as well as in `player.cpp`. Keeping the other two related constants in the same file provides more context?

**Comment by Coolthulhu** [comment]
> VOLUME_MOVE_COST is required by holster_actor as well as in player.cpp.

Both of those include `player.h`.
While `player.h` is a relatively bad header to modify (it triggers recompilation of most of the game files), `game_constants.h` is strictly worse - `player.h` includes it.

On an unrelated note, the item damage constants should also be moved to `item.h` or `itype.h` and max item constants to `map.h`. Anything that damages items includes `item.h`, anything that accesses items on map includes `map.h`.

**Comment by mugling** [comment]
> Both of those include player.h.

The usage is in `iuse_actor.h` not `iuse_actor.cpp` which unless I'm mistaken doesn't appear to include `player.h`?

> On an unrelated note, the item damage constants should also be moved to item.h

Required in `material.h`?

**Comment by Coolthulhu** [comment]
> The usage is in iuse_actor.h not iuse_actor.cpp

Could be moved to the load function, with default value being 0.
Not sure what advantages (if any) are there to declaring default constructor arguments in the .h file, except possible inlining for faster execution (which obviously doesn't matter here).
Or even better: require it to always be declared. It is a pretty essential value that doesn't really need defaults. And it wouldn't be much work - it is declared in most cases anyway.

> Required in material.h?

This one would be harder.
I guess in this case it really is one of those constants that don't vary across game versions - changing that one value would require a lot of changes. Mostly because a great deal of code doesn't use the constant and instead has its inlined value...

**Comment by BevapDin** [comment]
>> On an unrelated note, the item damage constants should also be moved to item.h

> Required in  material.h ?

Or: have a separate amount of damage adjectives, completely separated from the scale of the item damage itself. Using it would only require to convert those two scales. It has the nice advantages that item damage can get its own (finer) scale.

In fact, this should be handled by the material class alone, the item class should call `material::get_damage_adjective( float health )` or similar - `health` ranges from `>1` for reinforced to 1 (normal) to 0 (destroyed).

**Pull request merged**
