### PR TITLE
Fix #29043 - Fix off-by-one iteration and prevent indexing an empty vector in gas spreading code.

### LINKED ISSUE #29043: Crash.
**Describe the bug**  
Had multiple crashes while looting a city

**To Reproduce**  
I have no idea was walking/looting when last crash happened.

**Expected behavior**  
Just crashes the game.

**Screenshots**  
crash

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: 0.D-1042-ge3964f4
 - Graphics version: Tiles
 - Mods loaded: 
Disable npc needs,Filthy clothing,
(DP_RP)Remix Indicator,
Vehicle Addition pack,Tanks and Other Vehicles, Folding parts Pack,
Urban Development,More Locations,Fuji's More Buildings,
Mutant NPCs,Alternate Map key,
More Survival Tools, Medieval and Historic Content, Extended Realistic Guns,
No Fungal Monsters

**Additional context**  
Crash Log File:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-1042-ge3964f4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x555FB5[cataclysm-tiles.exe+0x155FB5]
    @0x556B62[cataclysm-tiles.exe+0x156B62]
    SMPEG_error+0x4B034@0xE280A0[cataclysm-tiles.exe+0xA280A0]
    _C_specific_handler+0x98@0x7FFAB31E8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFAB47F468F[ntdll.dll+0xA468F]
    RtlWalkFrameChain+0x14BF@0x7FFAB4754BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFAB47F33FE[ntdll.dll+0xA33FE]
    @0x60ACB3[cataclysm-tiles.exe+0x20ACB3]
    @0x60BB78[cataclysm-tiles.exe+0x20BB78]
    @0x611300[cataclysm-tiles.exe+0x211300]
    @0x618127[cataclysm-tiles.exe+0x218127]
    @0x682F4E[cataclysm-tiles.exe+0x282F4E]
    IMG_LoadWEBP_RW+0x4D91C9@0x13F30D9[cataclysm-tiles.exe+0xFF30D9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFAB1B581F4[KERNEL32.DLL+0x181F4]
    RtlUserThreadStart+0x21@0x7FFAB47BA251[ntdll.dll+0x6A251]

Edit:
Uploaded a [save zip.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3012796/save.zip.zip)

### PR DESCRIPTION
**Pull request by neitsa**
#### Summary

```SUMMARY: Bugfixes "Fix #29043'"```

#### Purpose of change

Fixes #29043 - Fix off-by-one iteration and prevent indexing an empty vector in gas spreading code.

#### Describe the solution

* Fix all end conditions of similar loop iterations in the `field.cpp` file.
* Guard against indexing of a possible empty vector.

(Sorry for the wall of text)

There's a very subtle bug in the gas spreading lamba in the [map::process_fields_in_submap](https://github.com/CleverRaven/Cataclysm-DDA/blob/14a0cbfa209f76f262c70c63ba816b41ca1f7ec8/src/field.cpp#L585) function, [exactly here](https://github.com/CleverRaven/Cataclysm-DDA/blob/14a0cbfa209f76f262c70c63ba816b41ca1f7ec8/src/field.cpp#L718). Various conditions make the bug hard to chase, so I was lucky to be able to trigger it only on the second try.

I wrote a quite [detailed explanation](https://github.com/CleverRaven/Cataclysm-DDA/issues/29043#issuecomment-477252509) in the issue, but it can be summarized like this:

Given this code:

* Init: 
    - `neighs.size()` is 8.
    - `neighbour_vec`  is empty.
    -  `end_it` is 7.
```
    end_it = static_cast<size_t>( rng( 0, neighs.size() - 1 ) );
    for( size_t i = ( end_it + 1 ) % neighs.size() ;
         // Start at end_it + 1, then wrap around until i == end_it
         i != end_it;
         i = ( i + 1 ) % neighs.size() ) {
        const auto &neigh = neighs[i];
        if( ( neigh.x != remove_tile.x && neigh.y != remove_tile.y ) ||
            ( neigh.x != remove_tile2.x && neigh.y != remove_tile2.y ) ||
            ( neigh.x != remove_tile3.x && neigh.y != remove_tile3.y ) ) {
            neighbour_vec.push_back( neigh );
        }
    }
    spread_to( neighbour_vec[ rng( 0, neighbour_vec.size() - 1 ) ] ); // Crash here
```
It seems that in all my tests there's always at least a single tile that matches the big `if` so the vector (`neighbour_vec`) should be pushed to and never be empty.

Now if we carefully look at the `for` loop and the end expression condition we have: `i != end_it`.

As the cpp reference says (about the loop end condition):

> an expression which is contextually convertible to bool. This expression is evaluated before each iteration, and if it yields false, the loop is exited.

Let's go over a few of the iterations with an `end_it` set 7:

* iteration 0: i = 0  ( i =  (7 + 1) % 8 = 0 )
    - i != end_it: True
    - execute_loop
    - i = 1
    
* iteration 1: i = 1
    - i != end_it: True
    - execute_loop
    - i = 2

* [snip]

* iteration 6: i = 6
    - i != end_it: True
    - execute_loop
    - i = 7    
    
* iteration 7: i = 7
    - i != end_it: False
    - **exit loop**

As we can see the 8th loop iteration (`i = 7` which is perfectly valid), is not executed due to an off-by-one mistake. 

In my case (during the crash repro), the only valid tile was the tile at index 7 (the last one). Thus, it was not pushed to the vector and the vector was empty during its indexing, which resulted in a crash.

#### Describe alternatives you've considered

N/A.

#### Additional context

Similar loop constructs were also fixed, not just the crashing one.

### CODE REVIEW

**Comment by kevingranade** [comment]
I threw a teargas grenade, and a few ticks later got a crash with this backtrace:
```
        debug_write_backtrace(std::ostream&)
        .../src/debug.cpp:593
        std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
        /usr/include/c++/7/sstream:638
        log_crash
        .../src/crash.cpp:258
        crash_terminate_handler()
        .../src/crash.cpp:321
        ??
        ??:0
        ??
        ??:0
        ??
        ??:0
        ??
        ??:0
        __gnu_cxx::new_allocator<maptile>::allocate(unsigned long, void const*)
        /usr/include/c++/7/ext/new_allocator.h:111
        std::allocator_traits<std::allocator<maptile> >::allocate(std::allocator<maptile>&, unsigned long)
        /usr/include/c++/7/bits/alloc_traits.h:436
        std::_Vector_base<maptile, std::allocator<maptile> >::_M_allocate(unsigned long)
        /usr/include/c++/7/bits/stl_vector.h:172
        void std::vector<maptile, std::allocator<maptile> >::_M_realloc_insert<maptile const&>(__gnu_cxx::__normal_iterator<maptile*, std::vector<maptile, std::allocator<maptile> > >, maptile const&)
        /usr/include/c++/7/bits/vector.tcc:406
        map::process_fields_in_submap(submap*, int, int, int)::{lambda(field_entry&, tripoint const&, field_id, int, time_duration const&)#2}::operator()(field_entry&, tripoint const&, field_id, int, time_duration const&) const
        .../src/field.cpp:715
        map::process_fields_in_submap(submap*, int, int, int)
        .../src/field.cpp:1367
        map::process_fields()
        .../src/field.cpp:524
        game::do_turn()
        .../src/game.cpp:1461
        main
        .../src/main.cpp:682
        __libc_start_main
        ??:?
        _start
        ??:?
```

**Comment by kevingranade** [comment]
In
https://github.com/CleverRaven/Cataclysm-DDA/pull/29093/files#diff-4ad10df75ab302c4b9ae78f758a32003L707-L717
If end_it == neighs.size(), the loop is rendered non-terminating.
This is probably happening elsewhere too.

**Comment by neitsa** [comment]
Damn 😢 

Can't believe I introduced the same bug class than the one I was fixing... I should have obviously tested this one, this will teach me a lesson. 

I'm going to "fix the fix" today.

Thanks @kevingranade for your review!

**Comment by neitsa** [comment]
Resorted to use a loop counter variable as `i != end_it + 1` would be always true, so it was not possible to use this solution. Tested the patch with a debugger. Did some iterations of various loops and it seemed correct.

**Pull request merged**
