### PR TITLE
Add more magazine spawns

### PR DESCRIPTION
**Pull request by mugling**
Currently magazine spawns are too rare and there is a high chance of merge conflicts as we add new ones.

This PR starts work by defining the groupings and relative rarity of magazines in `itemgroups/magazines.json` and then using those to define spawns for buildings and monster drops. Currently this PR provides thematically correct spawns for the gun stores, military surplus and zombie cops/police armories.

@Rivet-the-Zombie I'm not sure what the thematic fit for your Rivtech magazines is so if you let me know I can slot them in or alternatively you might want to add your own niche.

Nods to previous suggestion from @kevingranade in that `itemgroups/magazines.json` lists magazines alphabetically to limit merge conflicts.

EDIT: Also spawns obscure magazines in the pawnshop.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Put them in with other guns and in military areas, like the places where they spawned originally.

**Comment by mugling** [comment]
I've added the majority to `mags_milspec` with the RM360 mags going into `mags_smg_*`. The former is used as part of `mil_hw` and the latter show up reasonably frequently in gun stores.

**Comment by Rivet-the-Zombie** [comment]
I'd originally put the 8x40 HMG in ````mil_hw```` as well.

**Comment by Rivet-the-Zombie** [comment]
A few of the Rivtech guns - namely the RM103A, RM99, RM228, and RM120C - are considered high-end civilian items, so the RMGP10 and RMGP25 magazines for the RM103A should be rare spawns in civilian areas as well (none of the other civilian ones use magazines).

**Comment by mugling** [comment]
I've put those in`mags_other_rare` which will spawn in gunshops (and when I get round to it in a separate PR in survivor basements).

**Comment by mugling** [comment]
No further changes planned

**Comment by Rivet-the-Zombie** [comment]
The ````8x40_500_mag```` doesn't seem to actually spawn anywhere.

**Comment by chaosvolt** [comment]
Hmm, interesting.

**Comment by chaosvolt** [comment]
Also, if I may...been working on some stuff, intending to alter Icecoon's Weapons Pack to have magazines. separate from this, I also have AKM magazines:

````
    {
        "type" : "MAGAZINE",
        "id" : "akmmag",
        "price" : 1500,
        "name" : "AKM magazine",
        "symbol" : "#",
        "color" : "ltgray",
        "description" : "A standard magazine made for the AK-74M rifle, made of stamped sheet metal.  Holds 30 rounds",
        "material" : "steel",
        "volume" : 2,
        "weight" : 430,
        "to_hit" : -2,
        "ammo_type" : "762",
        "capacity" : 30,
        "reliability" : 9,
        "reload_time" : 100,
        "flags": [ "MAG_COMPACT" ],
        "alternatives" : [
            [ "223", [ "stanag30", "stanag10", "survivor223mag" ] ]
        ]
    },
    {
        "type" : "MAGAZINE",
        "id" : "rpk47mag",
        "price" : 8500,
        "name" : "AKM extended magazine",
        "symbol" : "#",
        "color" : "ltgray",
        "description" : "A 40-round, 7.62x39mm magazine compatible with the AKM rifle, initially designed for the RPK.",
        "material" : "steel",
        "volume" : 3,
        "weight" : 570,
        "ammo_type" : "762",
        "capacity" : 40,
        "reliability" : 8,
        "reload_time" : 130,
        "flags": [ "MAG_BULKY" ],
        "alternatives" : [
            [ "223", [ "stanag30", "stanag10", "survivor223mag" ] ]
        ]
    },
````

And in addition, the weapons:

````
  {
    "id": "ak47",
    "type": "GUN",
    "symbol": "(",
    "color": "brown",
    "name": "AKM",
    "name_plural": "AKM",
    "description": "One of the most recognizable assault rifles ever made, the AKM is renowned for its durability even under the worst conditions.",
    "price": 290000, "//" : "AKs likewise aren't commercially traded in the US.",
    "material": ["steel", "wood"],
    "flags": ["MODE_BURST", "NEVER_JAMS"],
    "skill": "rifle",
    "ammo": "762",
    "weight": 4300,
    "volume": 9,
    "bashing": 12,
    "cutting": 0,
    "to_hit": -1,
    "dispersion": 45,
    "sight_dispersion": 60,
    "aim_speed" : 6,
    "recoil": 60,
    "durability": 9,
    "burst": 8,
    "reload": 475,
    "loudness": 150,
    "barrel_length" : 1,
    "magazines" : [ "akmmag", "rpk47mag" ],
    "valid_mod_locations": [[ "accessories", 4 ],[ "barrel", 1 ],[ "bore", 1 ],[ "conversion", 1 ],[ "grip", 1 ],[ "mechanism", 4 ],[ "muzzle", 1 ],[ "rail", 1 ],[ "sights", 1 ],[ "stock", 1 ],[ "underbarrel", 1 ]]
  },
  {
    "id": "arx160",
    "type": "GUN",
    "symbol": "(",
    "color": "blue",
    "name": "Beretta ARX-160",
    "name_plural": "Beretta ARX-160",
    "description": "The Beretta ARX-160 was a Phase II contender in the United States Army Individual Carbine competition to replace the M4 carbine.  It failed to replace it, but it is widely used by military all around the world.  This version is chambered for 7.62x39mm.",
    "price": 450000,
    "material": "steel",
    "flags": "MODE_BURST",
    "skill": "rifle",
    "ammo": "762",
    "weight": 3000,
    "volume": 13,
    "bashing": 11,
    "cutting": 0,
    "to_hit": 2,
    "ranged_damage": 2,
    "dispersion": 30,
    "sight_dispersion": 60,
    "aim_speed" : 6,
    "recoil": 60,
    "durability": 9,
    "burst": 3,
    "reload": 400,
    "loudness" : 150,
    "barrel_length" : 1,
    "magazines" : [ "akmmag", "rpk47mag" ],
    "valid_mod_locations": [[ "accessories", 4 ],[ "barrel", 1 ],[ "bore", 1 ],[ "conversion", 1 ],[ "grip", 1 ],[ "mechanism", 4 ],[ "muzzle", 1 ],[ "rail", 1 ],[ "sights", 1 ],[ "stock", 1 ],[ "underbarrel", 1 ]]
  },
````

**Comment by Rivet-the-Zombie** [comment]
This is still missing at least one item spawn, namely `8x40_500_mag`, which no longer appears to have any spawn locations.

**Pull request merged**
