### PR TITLE
[RFC] Adds graywater to washing for recycling into clean water

### PR DESCRIPTION
**Pull request by VictoriaActual**
#### Summary
Features "Adds graywater byproduct when washing clothes by hand. Can be recycled into clean water."

#### Purpose of change

When you wash clothes your water shouldn't just disappear into the void, so this adds graywater (or greywater) as a byproduct when washing that can be filtered back into clean water. This is currently submitted as a draft until I can update the washing machine to utilize it as well.

#### Describe the solution

Instead of washing items and just getting the 'you cleaned your clothes' message, you'll also get all of your units of water back as graywater. It currently isn't used in much, but can be filtered back into clean water with a water purifier of some variety. 

#### Describe alternatives you've considered

Not doing this, but this way I can reuse more of the water I drag to my base. c:
Plus this might be useful to folks playing the desert mod or innawoods and wanting to reduce their water use.

#### Testing

Tested the build by washing several clothing items and storing the excess graywater in a nearby tank. I also confirmed my changes didn't bork the washing machine appliance and I was able to filter all the nasty crap out with a charcoal water purifier and get clean water.

#### Additional context

I submitted this as a draft to get some feedback on what all else I should touch in this update, since I'd like to have the washing machine mirror this behavior. My current thoughts on implementing the graywater recycling would include having a washing machine with a collection tank but I haven't had the heart today to jump into vehicle code next. Graywater is also used to help fertilize and water plants, so creating a mild fertilizer out of it is another goal, but I don't want players crafting proper fertilizer out of it and then using it in explosives recipes. I'd also love some input into the current graywater filtering I added as part of me thinks that filtering it should only result in unclean water, but adds an extra crafting step for no real reason other than "I wouldn't drink that". As the draft stands currently it could be used, but I'd very much appreciate some feedback on the feature and any wishlists while I'm at this point. :3

### CODE REVIEW

**Comment by Qrox** [comment]
Can you really purify dissolved soap with charcoal though? If not, a separate recipe to filter and purify gray water will be more realistic. Also, apart from the purification recipe you changed, you can also activate purification pills, interact with purifier items/appliances/vehicle parts, and boil water on a fire to purify water in the game, so whether those methods apply to gray water should also be considered.

> Graywater is also used to help fertilize and water plants, so creating a mild fertilizer out of it is another goal

If we model what exactly is on filthy clothing that should make sense, but currently the game does not, and I doubt zombie goop can be used to fertilize plants.

**Comment by fairyarmadillo** [comment]
> Can you really purify dissolved soap with charcoal though? If not, a separate recipe to filter and purify gray water will be more realistic. Also, apart from the purification recipe you changed, you can also activate purification pills, interact with purifier items/appliances/vehicle parts, and boil water on a fire to purify water in the game, so whether those methods apply to gray water should also be considered.
> 
> > Graywater is also used to help fertilize and water plants, so creating a mild fertilizer out of it is another goal
> 
> If we model what exactly is on filthy clothing that should make sense, but currently the game does not, and I doubt zombie goop can be used to fertilize plants.

Filthy specifically means putrescence and gore, a lot of which would be fat liquified in the process of decay. This is a famously revolting substance and probably wouldn't come out of water easily. _Definitely_ not from boiling or tablets. I'd buy that a sufficiently complex mechanical filter would do it, but I don't know much about how those work. Our electronic water filters are more than just charcoal, aren't they?

**Comment by harakka** [comment]
> Our electronic water filters are more than just charcoal, aren't they?

They are just straight up magic and should be replaced with something specific.

**Comment by PatrikLundell** [comment]
The easy way to get unlimited amounts of water to a base is to build a water well (as they don't model the reality of limited water availability and limited water flow).

You now have to manually haul it into the washing machine (and dish washer, and autoclave, to mention other water using equipment), though (at least in base camps: it used to magically teleport from the pump to the equipment, and I haven't used this kind of equipment in vehicles since that change, so I can't tell if you have to do the same there, or if it's still drawn from vehicle tanks).

**Comment by BarndoBoi** [comment]
Oof, it's been a wild week with the new year coming in.
But as for graywater as a fertilizer its less about any of the gore or fats and down to the chemicals in the soap that make good plant food. One of the major issues that can come up is if your soap contains boron or excessive salt as it can degrade the soil or change its Ph. The result is that most graywater can be used to water plants, but the presence of blackwater/sewage in it requires that produce be thoroughly washed (which you should be doing anyways!). However that isn't modelled in DDA so I think most of those problems could be sidestepped for now.

As for purifying graywater it's usually done with a mechanical filter and isn't possible with boiling or purification tablets. The water filters currently in game don't make any distinction as to how they work, so I opted to assume they use a layered filter and possibly even reverse osmosis, but as harakka mentioned they're pretty much magic right now.
I'm spending part of the day today going back and quieting the warnings and little boo-boos I still had left in it and then seeing about making a variant of the vehicle mounted washing machine that includes a graywater storage tank.
I'm basing some of this off of information off of a gravity powered irrigation system utilizing graywater linked here (irrigation systems are way beyond the scope of this PR and sound like a nightmare): https://greywateraction.org/laundry-landscape/
and also information from: https://greywateraction.org/greywater-reuse/

**Comment by Maleclypse** [comment]
Are you intending for this to still be in draft?

**Comment by BarndoBoi** [comment]
> Are you intending for this to still be in draft?

Just for a few more days (at max) or until I get this weak fertilizer recipe added. I suppose it could technically be added in now and there'd be no downside but I'd love for the graywater to have at least one recipe it could be used in before it makes it debut. I'm gonna attempt to add in some recipes this afternoon and then move this out of draft. 👍

**Comment by fairyarmadillo** [comment]
> Just for a few more days (at max) or until I get this weak fertilizer recipe added. I suppose it could technically be added in now and there'd be no downside but I'd love for the graywater to have at least one recipe it could be used in before it makes it debut. I'm gonna attempt to add in some recipes this afternoon and then move this out of draft. 👍

Gray water should not be a fertilizer, as in this case it contains zombie gore which is heavily tainted by blob stuff. I don't think concentrating that material, which is toxic enough to kill the player, in the soil they're growing crops with is a good idea.

**Pull request closed without merging**
