### PR TITLE
Activity extraction

### PR DESCRIPTION
**Pull request by kevingranade**
Since #10846 seems to have gone cold, I went ahead and finished out my and BevapDin's suggestions.
Like the previous PR, there are no functionality changes, this just pulls some code out into its own module.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm a bit surprised, I would have thought this would conflict badly with #10982, but github seems ok with it.

**Comment by KA101** [comment]
On a recheck, your initial thought appears accurate.

**Comment by kevingranade** [comment]
Ok yea I'll rebase and ping the PR when it's ready again.

**Comment by kevingranade** [comment]
All rebased, what a slog.

**Comment by DavidKeaton** [comment]
Sorry bud. :-(

**Pull request merged**
