### PR TITLE
Sock Mitts crafting fix

### PR DESCRIPTION
**Pull request by cvbosch**
This is a bug fix for the issue concerning the crafting of sock mitts under the "good first issue" tab.  I tested in game and users can create sock mitts from different kinds of socks.  The altered file is data/json/recipes/armor/hands.json.

### CODE REVIEW

**Comment by Zireael07** [comment]
You should give the issue number - otherwise people don't have a clue what you're talking about.

**Comment by PatrikLundell** [comment]
Apart from Zireal07's point, you also have to follow the template or it will be rejected automatically. The Summary section is parsed, and so has to follow the description exactly (one of the listed keywords followed by a string describing what the PR does, on None without any string for something that isn't important enough to make it into the change log).

**Comment by Maleclypse** [comment]
You'll want to rebase on top of a current master as well.  You are currently deleting a bunch of recipes that were probably added after you downloaded DDA.

**Comment by ZhilkinSerg** [comment]
Please rebase on top of current master and reopen PR.

**Pull request closed without merging**
