### PR TITLE
Begin reorganizing terrain.json

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
 ```SUMMARY: Infrastructure "Start breaking up terrain.json"```

#### Purpose of change
terrain.json is getting unwieldy to navigate and find lesser used terrains, break up the file into categories in a new data/json/terrain folder.

#### Describe the solution
This makes the folder and moves the first category, walls.

#### Describe alternatives you've considered
let it keep growing

### CODE REVIEW

**Comment by kevingranade** [comment]
This is throwing all kinds of errors for some reason, offhand I suspect we might have an ordering dependency that this is violating.

**Comment by Rivet-the-Zombie** [comment]
Good initiative, @curstwist! This is the sort of project that streamlines everything that touches those .jsons.

**Comment by ZhilkinSerg** [comment]
Errors happen because other terrains are connected to walls, so walls should be loaded prior to these terrains. Using only json, we can do this right now:

image

In the long run we need to utilize deferred json loading for terrains and finalize function to process wall connections only after all terrains were loaded. There is infrastructure for that - just need some C++ code.

**Comment by curstwist** [comment]
I'll get back to this shortly.

**Comment by curstwist** [comment]
closing to PR a less conflicted version.

**Pull request closed without merging**
