### PR TITLE
Brainworms ID fix

### PR DESCRIPTION
**Pull request by drbig**
Part of work on #13070.

This just touches the ID and fixes one additional thing (unless someone has some objections).

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Blood filter doesn't affect the brainworm(s) because it's filtering all your blood as it passes through a series of machines and the worm(s) never leaves your brain. Acid blood should still be killing it though, as it doesn't matter if it doesn't leave your head, it still gets bathed in acid blood.

And originally it was singular, as in one big worm gnawing on your grey matter, but plural is fine too.

**Comment by drbig** [comment]
@Rivet-the-Zombie shouldn't acid blood then kill both brain and blood worms?

**Comment by drbig** [comment]
Acid blood = no blood nor brain worms. Hurray for low pH!

**Comment by Rivet-the-Zombie** [comment]
>shouldn't acid blood then kill both brain and blood worms?

Yeah.

**Comment by DavidKeaton** [comment]
The delicate pH in the blood is what makes it such a nice bacteria target (not to mention it has interstate access to anywhere!), however tipping that scale in either direction should kill almost any intruder. Of course that means we would also fry our internals, but being a mutant with acid blood is a different story. :-)

**Comment by drbig** [comment]
@DavidKeaton And that was pretty much exactly where the chemistry discussion has started on IRC ;)

**Comment by DavidKeaton** [comment]
Ah! :-)

**Comment by Coolthulhu** [comment]
What about old saves with brainworms? There should be a check that adds the "new worms" if the old one are in the save. Unless save load already drops inexistent effects.

By the way, dropping inexistent effects on save load could be a good feature in itself, if we don't have it. And I don't think we do, as `effect::deserialize` seems to assume `"eff_type"` always refers to an existing effect.

**Comment by drbig** [comment]
@Coolthulhu Have a look at #13083. The question I have there is which guards to keep. I've added there code that checks on load and adding, which in my testing with fixed IDs ended up cleaning the save.

**Comment by kevingranade** [comment]
How about we keep the version of the identifier that won't break the game, e.g. the one that the save/load code uses?

**Comment by kevingranade** [comment]
whoops, or not? :/

**Comment by narc0tiq** [comment]
Well, "brainworms" seems to be the one that gets given to characters and
saved, so keeping that one makes sense.

**Comment by BevapDin** [comment]
> How about we keep the version of the identifier that won't break the game, e.g. the one that the save/load code uses?

That's the what has been done, but the effect ID appears several times in the saves. The effect map is `map<string, map<body_part, effect>>`, the string is the effect id and the `effect` object also contains the effect (as pointer to the `effect_type` type). The string is stored fine (as "brainworms", what is the correct one, the one that is used all over the place now), but the `effect` contains "" as effect_id, that's what causes problems.

```JSON
{
    "effects": {
        "brainworms": {
            "12": {
                "effect_id": "",
                "intensity": 1,
                "duration": 1
            }
        }
    }
}
```
This is caused by the original call to `Creature::add_effect`. It adds the "brainworms" entry in the outer map and an `effect` object in the inner map (12 btw. is `num_bp`). Creating the `effect` object used the `operator[]` of map of effect types. That created a default constructed `effect_type` with an empty ID.

Actually, now that I think about it, this could be fixed with additional checks and taking the effect id from the map key, but I'm not sure it's worth the code complexity.

**Comment by kevingranade** [comment]
Ok, I see, misunderstood.

**Pull request merged**
