### PR TITLE
Make the construction palette more varied

### PR DESCRIPTION
**Pull request by Milopetilo**
#### Summary
Infrastructure "Change the construction palette to be more varied"

#### Purpose of change
While doing #71555 I stumbled upon the construction palette added in #67168. I used it for regionalizing `house_02` but while doing `house_03` I felt that the construction palette could do with some more variation and show which phase of construction the house was in pre-cataclysm.

#### Describe the solution
I'm planning on adding the following "levels" of construction of areas:
- [x] Outside concrete areas: nothing, dug out, poured 
- [x] Pavement: dirt, dug out?, put down
- [x] Sidewalk: dirt, put down
- [x] Fences: nothing, posts, finished
- [x] Interior walls: half-built, built, painted
- [X] Kitchen/bathroom: only flooring, plumbing (sink, shower, toilet)/electricity (oven, fridge?), installed
- [x] Fireplace/wood stove: floor, chimney, installed
- [X] Windows: (nothing?), frames, installed
- [X] Cabinets: not installed, installed
- [X] Doors: none, frames, installed, locked
- [x] Garage doors: none, installed
- [ ] ~~Multi-story houses: scaffolds, ladders, stairs~~ Going to be handled in future PR

Also adding palette terrain and furniture for:
- [X] Crates with supplies in, bulk supplies

The construction palette `construction_general_palette` now chooses a phase, weighed against how long houses usually are in them in real life. See [my comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/71578#issuecomment-1931847352) on this PR for more details about the phases.
I've also implemented specific kinds of items spawning on different tiles, only in the bathroom for now but I want to try and make different rooms have different spawns, probably in a future PR. The different phases all have different chances to spawn different furniture, especially the bulk supplies.
Also going to change `house_01` & `house_02` to utilize this correctly, in order to not break things after this gets merged.

#### Describe alternatives you've considered
Don't do this and either make multiple variants for different levels of construction or don't make them a thing and just keep them as-is.

#### Testing
All the variants seem to spawn correctly, bashed furniture and flooring is the correct kind, also looked around cities for spawns, they generate correctly.

#### Additional context
~~Maybe also add roof as a possible variable? Unsure when in construction they're added.~~ A basic roof seem to be added around phase 0-1 and actual roofing installed around phase 2, I'm going to see how feasible implementing this is and if it is, making a different PR.
Some screenshots of `house_02` in different phases:
Phase 0:
Screenshot from 2024-02-07 15-57-04
Phase 1:
Screenshot from 2024-02-07 15-58-42
Phase 2:
Screenshot from 2024-02-07 16-00-03
Phase 3:
Screenshot from 2024-02-07 16-02-17

### CODE REVIEW

**Comment by Procyonae** [comment]
It is possible to do a roofless half walled version with parameters but it's probably a bit overkill, excited to see the end result ^_^

**Comment by PatrikLundell** [comment]
Are sidewalks really the builder's responsibility in the US? Where I live it's the responsibility of the party owning the road (and the sidewalk is thus a part of that property). Thus, it seems the sidewalk ought always be present (unless you can somehow create a logic for "new areas" where the sidewalk is missing/in a partial state for a whole neighborhood). You may have to dig up small sections of the sidewalk to be able to connect water, sewage and electricity, and it would presumably fall on the home owner to repair those damages afterwards, but I don't think it would be worthwhile to represent that.

Having logic for what to spawn depending on the RNG of "previous" steps seems tricky. The work around I'm aware of is to bundle things into chunks to get a whole lot placed together based on a single RNG, but that doesn't create a chain.

Usually things are build in a somewhat similar order, so most of the time you don't have some parts just started and some finished (there are cases where delivery delays things, of course). Thus, I would probably settle for stages.

I don't think there's anything wrong with having (semi) fixed loot spots. After all, the best placement of building materials at a construction site is going to be similar for similar sites. If you want to have variation but not too much randomness in terms of the amount spawned you could probably make a few different spawn patterns and select one of those, rather than randomly (and individually) select different spawn point chunks.

Missing roofs is going to be a bit tricky due to how "terrain" is defined, where the "terrain" defines the ceiling as well, which (by sometimes broken) magic causes the roof to appear, although that magic seems to be bypassed for map gen constructions (as opposed to player/camp construction). However, for map gen I assume it would require having the Z+1 level depend on the RNG choices made for the Z level, something that might not be supported.

**Comment by Procyonae** [comment]
> Are sidewalks really the builder's responsibility in the US? Where I live it's the responsibility of the party owning the road (and the sidewalk is thus a part of that property).

Most of the sidewalk is on the road tile provided by the SIDEWALK flag and is untouched by this

> Having logic for what to spawn depending on the RNG of "previous" steps seems tricky. The work around I'm aware of is to bundle things into chunks to get a whole lot placed together based on a single RNG, but that doesn't create a chain.

I think it's doable with making a parameter that picks a stage palette to add alongside the base but it's a bit messy for sure

> Missing roofs is going to be a bit tricky due to how "terrain" is defined.

Yeah I'd dodge messing with missing roofs in this PR and take a shot at it separately if you want to.

> However, for map gen I assume it would require having the Z+1 level depend on the RNG choices made for the Z level, something that might not be supported.

It is supported and for multilevel buildings wouldn't be that bad as long as you don't mind all the floors being in the same state of completion (you could make it different but that gets very messy again), the domestic_general_and_variant_palette used in more generic houses already works like this. Roofs are a more annoying bc you'd be using the shared roof map as the non in construction versions using the roof palette so would either want to conditionally overwrite that palette or overwrite the map with a conditional nest, or to make in construction variants use their own om_terrain ids so they can have their own roof maps. #71219 is a simple example of how to change multiple levels based on the same parameter.

**Comment by Milopetilo** [comment]
> Are sidewalks really the builder's responsibility in the US? Where I live it's the responsibility of the party owning the road (and the sidewalk is thus a part of that property). Thus, it seems the sidewalk ought always be present (unless you can somehow create a logic for "new areas" where the sidewalk is missing/in a partial state for a whole neighborhood). You may have to dig up small sections of the sidewalk to be able to connect water, sewage and electricity, and it would presumably fall on the home owner to repair those damages afterwards, but I don't think it would be worthwhile to represent that.

It seems I got a bit confused about what I found online about this. It seems that it's the owner's responsibility to clean and keep the sidewalk in front of their property free of obstructions, but not to actually put it down. I do still like the idea of it not always being there, since  some houses use it as a walkway to the front door/garden, but that might also be the houses using the wrong terrain.
> Having logic for what to spawn depending on the RNG of "previous" steps seems tricky. The work around I'm aware of is to bundle things into chunks to get a whole lot placed together based on a single RNG, but that doesn't create a chain.

The main issue I ran into doing this was that `switch: case` does not like it when you don't give it a string, so I can't make it use params inside the cases. I'm trying to see if I can get someone more knowledgeable to help me on this.
> Usually things are build in a somewhat similar order, so most of the time you don't have some parts just started and some finished (there are cases where delivery delays things, of course). Thus, I would probably settle for stages.

Looking into this, I did find ~3 phases which seem to be relevant here (after foundations/exterior walls):
1: The general framing of things and finishing the exterior wall up. I'd put in window frames, door frames, downspouts for constructions in this phase.
2: MEP (Mechanical, Electrical, Plumbing). In real life this is when most pipes, vents and cables get put in, I might represent this by putting in appliances (toilets, boilers, ...) and making the interior walls finished, but unpainted.
3: Finishing touches. Putting up drywall, painting walls, cabinets, doors, things like that are done in this phase. I think representing this by making walls painted, putting in cabinets, doors, windows, and tiling of bathrooms would be good.
I'm unsure whether or not to add a phase 0 where it's just outer walls and interior wall frames since that might seem a bit weird.
> I don't think there's anything wrong with having (semi) fixed loot spots. After all, the best placement of building materials at a construction site is going to be similar for similar sites. If you want to have variation but not too much randomness in terms of the amount spawned you could probably make a few different spawn patterns and select one of those, rather than randomly (and individually) select different spawn point chunks.

The methods I'm using right now, which I'm quite satisfied with, is using nested mapgen to spawn "random" items/corpses, e.g. to represent a worker that ran away in a panic leaving their tools behind, and specific spots for crates and bulk supplies.
> Missing roofs is going to be a bit tricky due to how "terrain" is defined, where the "terrain" defines the ceiling as well, which (by sometimes broken) magic causes the roof to appear, although that magic seems to be bypassed for map gen constructions (as opposed to player/camp construction). However, for map gen I assume it would require having the Z+1 level depend on the RNG choices made for the Z level, something that might not be supported.

Yeah, I mostly expected to be unable to, especially because (even if it did work) I don't think I could use the same roof terrain for finished houses as ones in construction.

**Comment by Milopetilo** [comment]
> > Having logic for what to spawn depending on the RNG of "previous" steps seems tricky. The work around I'm aware of is to bundle things into chunks to get a whole lot placed together based on a single RNG, but that doesn't create a chain.
>
> I think it's doable with making a parameter that picks a stage palette to add alongside the base but it's a bit messy for sure
Wow, this will actually help me a lot, thanks :).

**Comment by Milopetilo** [comment]
Alright, I've made the palette choose a variant palette to show the different phases of construction. Gonna update the PR message as well to reflect this.

**Comment by PatrikLundell** [comment]
- I don't think it's a great idea to use blank to actually represent anything, as it's typically used to indicate "no change", and frequently isn't defined at all. I would probably use "." instead. Note: opinion, not order by anyone with any kind of authority.
- I believe it's possible to use multiple palettes concurrently, in which case you can factor out things that are constant (such as the stuff currently indicated by blank, but there may be others) into a static or background palette and then have this palette complement the variant one. That would save on defining the same thing multiple times (and modify it in all places when updating it), at the cost of more text when actually using palettes.

**Comment by Milopetilo** [comment]
> * I don't think it's a great idea to use blank to actually represent anything, as it's typically used to indicate "no change", and frequently isn't defined at all. I would probably use "." instead. Note: opinion, not order by anyone with any kind of authority.

Do you think using something like `,` would be better? I'm just using it to more randomly spawn things and since most of the time (from what I've seen), it is just the filler and is pretty often defined as `t_floor`.
> * I believe it's possible to use multiple palettes concurrently, in which case you can factor out things that are constant (such as the stuff currently indicated by blank, but there may be others) into a static or background palette and then have this palette complement the variant one. That would save on defining the same thing multiple times (and modify it in all places when updating it), at the cost of more text when actually using palettes.

That's actually a really good idea, thanks :)

**Comment by PatrikLundell** [comment]
Both '.' and ',' tend to serve filler purposes, so I think either of them would work.

**Comment by Procyonae** [comment]
Unless I'm misunderstanding something there's no need for the unique names given to your parameters when there can be only one at a time, like `construction1_exterior_wall_type` and `construction2_exterior_wall_type` can both just be `exterior_wall_type` because they're already in their own palettes if you wanted to make it them a bit more readable.

For phase 2+3 you've used t_pavement instead of t_sidewalk for the `p` path in front of the door which is the terrain used for road and it doesn't appear to be that way currently so I'm presuming that's a mistake.

Looks good otherwise from a skim though ^-^

**Comment by Milopetilo** [comment]
> Unless I'm misunderstanding something there's no need for the unique names given to your parameters when there can be only one at a time, like `construction1_exterior_wall_type` and `construction2_exterior_wall_type` can both just be `exterior_wall_type` because they're already in their own palettes if you wanted to make them a bit more readable.

Unless I did something wrong (which is very possible), cataclysm complained at me when I had multiple parameters with the same name, but different default distributions. If you want I could post the error here or in discord.
> For phase 2+3 you've used t_pavement instead of t_sidewalk for the `p` path in front of the door which is the terrain used for road and it doesn't appear to be that way currently so I'm presuming that's a mistake.

Good catch, I had originally used `p` as sidewalk, but then changed it to be more in line with the general house palette where it's `-` and must've forgotten to change it, thanks c:

**Comment by Procyonae** [comment]
> Unless I did something wrong (which is very possible), cataclysm complained at me when I had multiple parameters with the same name, but different default distributions. If you want I could post the error here or in discord.

Weird, it's not a big deal though I wouldn't worry

**Pull request merged**
