### PR TITLE
Remove all references to cauterizing wounds

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Bugfixes "Remove all references to cauterizing wounds"

#### Purpose of change

Cauterize having a beneficial effect has been broken for some time - in coordinance with reality. This merely completes removal of the feature as players are currently being misinformed and hurting themselves for no useful purpose.

#### Describe the solution

Remove all cauterize functions from existing items and all references to it in-game. The sole exception is note_180, in survivor_notes. This appears to be flavor and harms nothing by staying.

#### Describe alternatives you've considered

Allowing players to continue burning themselves. As the capability was only added in order to cauterize wounds, it doesn't seem worth supporting an obsolete feature just to keep self-harm.

#### Testing

Game compiles and launches. Tailoring kits, soldering irons, hotplates and knives were checked to insure they no longer allow cauterization.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Should this close #58823?

**Comment by RenechCDDA** [comment]
>Cauterize having a beneficial effect has been removed for some time. 

It's been broken* for some time. Important difference.

**Comment by intergalacticdata** [comment]
> 

I misunderstood the second+ hand report I received then. I'll adjust.

**Comment by oosyrag** [comment]
While I don't doubt it's (lack of) efficacy, I also wouldn't doubt people would try it in a pinch due to common misconception. Why not let people burn themselves if they want to?

**Comment by Kamayana** [comment]
> While I don't doubt it's (lack of) efficacy, I also wouldn't doubt people would try it in a pinch due to common misconception. Why not let people burn themselves if they want to?
> 
> Note that suicide is also a thing, that happens to be bound by default when there are definitely more useful things that could be graced with a default bind in my opinion, but I digress.

The thing is, the UI implies that it would work - it shows "minor bleeding -> 100% recovery" which is just a lie. If it said "minor bleeding -> Maybe this will work?" or something, with it becoming even more obviously worthless if you have enough survival skill, it'd be more debatable but that feels like going to too much effort just to do a bit of Mythbusters for players.

**Comment by intergalacticdata** [comment]
These functions were intended for cauterization and merely had self harm shimmed in.

I think it would make more sense to create a new, more universal self harm activity that is clearly intended as such if we want to support any of these use cases.

**Comment by MNG-cataclysm** [comment]
What if we left cauterization in, but gated it behind a medical proficiency? Without it, you have a very high chance of injuring yourself with little to no productive results. With it, you can reasonably close and disinfect wounds with the process, maybe with a little less pain by avoiding healthy tissue.

**Comment by intergalacticdata** [comment]
> 

Would probably need a rewrite as cauterization was already broken for several years.

**Comment by harakka** [comment]
> With it, you can reasonably close and disinfect wounds with the process

No, Cauterization _increases_ infection risk. Just let it go into the night, a lot of people from medical backgrounds have already chimed in on this in other discussions.

**Comment by harakka** [comment]
```
#### Summary
Bugfixes "Remove all references to cauterizing wounds"
```
should help you get past the PR validator.

**Comment by Fris0uman** [comment]
Documentation seems to still reference "cauterize" in JSON_INFO line 2495 and line 3888 and in JSON_FLAGS line 1381

**Comment by dseguin** [comment]
Have you checked that existing saves that autosave during the cauterizing activity will continue to work?

**Comment by intergalacticdata** [comment]
> Have you checked that existing saves that autosave during the cauterizing activity will continue to work?

Just checked it. Save loaded.

**Comment by intergalacticdata** [comment]
> Have you checked that existing saves that autosave during the cauterizing activity will continue to work?

Just checked it. Save loaded.

**Pull request merged**
