### PR TITLE
Remove secret science/military stuff from bank/industry/mall vaults

### PR DESCRIPTION
**Pull request by harakka**
#### Summary
Content "Remove secret science and military stuff from bank/industry/mall vaults"

#### Purpose of change
Currently bank and light industry vaults have a chance to spawn a bunch of stuff related to secret science/military things that people doing secret science/military stuff would have zero reason to keep in some random bank safety deposit or light industry backroom safe. This removes those.

#### Describe the solution
Remove Rivtech design binder, classified chemical reference, robot schematics, and nanofab templates from bank vaults.

As extra bonus, also remove survivor notes, since there's zero reason why people's post-apocalyptic scribblings would be deposited in a bank vault.

### CODE REVIEW

**Comment by SirPendrak** [comment]
HUB01 bar encounter merc NPC can sell nanofab templates. He mentions getting them from bank runs. From where does he gets them now?

**Comment by Kamejeir** [comment]
> HUB01 bar encounter merc NPC can sell nanofab templates. He mentions getting them from bank runs. From where does he gets them now?

here, harakka: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/robofac/robofac_ancilla_npcs/BAR_ENCOUNTER_MERCENARIES/BEM_template_seller.json

**Comment by SirPendrak** [comment]
Wouldnt it be better to change word "bank" to "lab", instead of removing more features?

**Comment by harakka** [comment]
> Wouldnt it be better to change word "bank" to "lab"
Done

**Comment by RenechCDDA** [comment]
> Wouldnt it be better to change word "bank" to "lab", instead of removing more features?

A random piece of dialogue is not a "feature" in any way, and removing things that don't fit is important.

**Pull request merged**
