### PR TITLE
Routine i18n updates on 18 Apr 2020

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
```SUMMARY: I18N "Routine i18n updates on 18 Apr 2020"```

### CODE REVIEW

**Comment by CountAlex** [comment]
Almost completed current RU translation, missed this PR a bit.

**Comment by kevingranade** [comment]
Was this aimed at master or 0.E? If any languages have made meaningful progress I'm interested in including them in a bugfix point release.

**Comment by CountAlex** [comment]
> 
> 
> Was this aimed at master or 0.E? If any languages have made meaningful progress I'm interested in including them in a bugfix point release.

I am still not sure what state of Russian version is present at stable version. By some reason every single translation for any name that was transformed into str/str_pl form was lost by Transifex for 0.E translation file. Other than that RU translation is complete to my knowledge.

**Comment by cainiaowu** [comment]
you can upload the ru.po to tansifex 0.e branch, transifex is clever enough to match same string, then you can filter by translation updated date to double check the result.

**Comment by BrettDong** [comment]
> Was this aimed at master or 0.E? If any languages have made meaningful progress I'm interested in including them in a bugfix point release.

This PR is for master branch

**Pull request merged**
