### PR TITLE
Add option to limit lifetime of sidebar messages

### LINKED ISSUE #15864: [Suggestion] Accessibility option: Log-less sidebar mode.
Following the discussion [here](http://smf.cataclysmdda.com/index.php?topic=12309.0), I'll be making a list of reasonably small changes and additions to the game that would make the game more playable for players who are forced to use screen-reader software to "see" the game screen due to disabilities of vision. All of this obviously applies only to "console" builds of the game.

* "Log-less mode" option - make the message log in the sidebar blank out on every update, so that only new messages are visible. This makes screen-reader software able to actually detect the new messages, instead of reading through the entire list as the messages scroll. The full log would still be available in the dedicated message log window.

~~* "Navigate to viewed tile" hotkey - reuse the code currently used for mouse-controlled movement, to navigate the character to the currently focused tile when using the `x` look command, or `V` item list. The feature could be occasionally useful to all players as well.~~
~~* Accessible readouts - In combination with the log-less mode, there will be enough empty space on the screen to display some information that can't be easily, well... seen at a glance... in the circumstances. Things like the current sight radius in tiles, the heading of the currently driven vehicle, the direction and distance to nearest hostile monster, etc.~~

edit: Struck out the move-to-viewed-tile suggestion as already implemented (if undocumented), split accessible readouts into a separate issue for tracking.

### PR DESCRIPTION
**Pull request by lucianposton**
Partially addresses #15864

### CODE REVIEW

**Comment by SeanMirrsen** [comment]
Almost, but not quite. To fix #15864 it needs to fully blank the message log every redraw, to avoid caching causing trouble for screen readers, at least for the specific case when the ttl is 1. It's a pretty great take on the feature otherwise, I didn't think that a non-binary solution could also be useful.

**Comment by lucianposton** [comment]
@SeanMirrsen What caching are you referring to? I'm not all that familair with ncurses nor screen readers, so I'm not follow you.

By "full blank the message log every redraw" so you mean the window should be erased and refreshed prior to redrawing the logs?

**Comment by SeanMirrsen** [comment]
Yes. Currently there is an optimization system wherein characters that are not changed between redraws are preserved to speed up redraw, though I'm not sure if it applies to curses. 

Screen readers are designed to read symbols on the screen that change, so any such caching will confuse them. Even aside from that, just getting the same message several times in a row would end up being confusing - ideally the whole message window would be blanked before drawing a fresh set of messages in.

**Comment by lucianposton** [comment]
I just tried it with the yasr screen reader, and as far as I could tell as a complete novice screen readerer, it behaved as expected. It only reads the new text (the text that's changed e.g. the message(s) from the last turn), so the same message isn't repeated when you set the ttl to 1.

I'll see if I can test the optimization situation you describe.

**Comment by lucianposton** [comment]
@SeanMirrsen I see what you mean about the optimization. If you receive a message "You see a bat" on the first turn, and then you receive "You see a shirt" on the next turn, that second message will only be read as "shirt" since that's the difference between the messages.

I'll leave this PR as it is, save any other issues, and address the redraw optimization problem in separate PR.

**Pull request merged**
