### PR TITLE
[coldness intensifies]

### PR DESCRIPTION
**Pull request by kevingranade**
Pushing on behalf of voskhod on the forums.
Seems pretty reasonable at a quick glance, makes warding off cold a priority.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The `hurt` effect interrupts sleeping and trying to sleep.
Freezing to death while trying to sleep is a common theme IRL and sleeping while cold is a common thing in early DDA survivor's life.
Suppressing the interrupts somehow (a new variable in the effect json?) would be useful, otherwise the hurting may become far more annoying than realistic.

Does it stack? Do you get -7 intelligence just for being cold? Also, does having cold feet cause intelligence loss?

**Comment by tyrael93** [comment]
Icelab start is even more challenging now, I like it! Plus it's good overall.

**Comment by Voskhod-DDA** [comment]
The intelligence and dexterity debuffs can be set to 0.5 instead of 1 so that intelligence and dex loss only occuring during "Freezing!" which would be late-stage hypothermia.

**Comment by KiwiTrinsic** [comment]
> The intelligence and dexterity debuffs can be set to 0.5 instead of 1 so that intelligence and dex loss > only occurring during "Freezing!" which would be late-stage hypothermia.

That is fine for Intelligence, but I don't think one would have to wait that long before the cold starts affecting Dex.

**Comment by kevingranade** [comment]
More general idea for damage waking one up, perhaps painkiller effects should raise the threshold for damaging waking you?  So if you take painkillers before sleep they won't wake you up.
Secondary, have cold supply a painkiller effect.

**Comment by Voskhod-DDA** [comment]
I was thinking of that too, yes, extreme cold has a habit of numbing your skin to pain, including the pain of being too cold in the first place.

**Comment by kevingranade** [comment]
I'm still in favor of this, but very short on time at the moment, if someone wants to apply some of the above changes and PR separately, I promise my feelings won't be hurt :)

**Comment by kevingranade** [comment]
Added a mild painkiller effect, and adjusted apply_damage to skip the call to on_hurt (which would wake you up) if pkill is higher than the damage.  Note if a monster or some other extrnal damage affects you (via deal_damage instead of apply_damage), you'll still get woken up as usual, even with high painkiller levels.
I also dropped the stat loss, especially since dex and int are already getting hit in player::hardcoded_effects(), along with the messages that are intended to make sure the player knows that it's happening.

**Comment by Voskhod-DDA** [comment]
Would it be also be possible for the player sporadically falling unconscious during "Freezing" and above? Either that or rapid fatigue gain like that of methamphetamine. The major threat here should be falling asleep and never waking up, as usually happens in the final stages of hypothermia.

Or would that be a little too painful? Freezing temperatures are very rare though, so...

**Comment by kevingranade** [comment]
Temperatures that take you below "cold" to "freezing" are quite rare, and
generally something the player has to seek out, so I have no problem making
it harsh.
Fatigue increase from extreme cold would combat the effect I've been seeing
where you can't sleep because it's too cold.

**Comment by Voskhod-DDA** [comment]
For fatigue, maybe 

            "fatigue_chance": [20],
            "fatigue_min": [1],

can be added?

**Comment by kevingranade** [comment]
Is there a problem with the PR?  Short of other feedback it's good to go.

**Pull request merged**
