### PR TITLE
(colors) style cleanup

### PR DESCRIPTION
**Pull request by bkentel**

### CODE REVIEW

**Comment by DavidKeaton** [comment]
Love tab alignment, nice.

**Comment by narc0tiq** [comment]
Funny you should say that -- I tend to have the opposite reaction: my feeling is that aligned code imposes extra work on editors for something that's rarely (if ever) useful. Trivial example: adding a new line with a longer first column requires you to realign the whole thing.

That said, these are practically unchanging, so it's _probably_ okay to do it in this case.

**Comment by kevingranade** [comment]
Agree with Narc, this is IMO a style regression rather than an improvement.

**Comment by bkentel** [comment]
*So many men, so many minds.*
Opinion on these sort of things noted.

**Pull request closed without merging**
