### PR TITLE
Automated linting of remaining mapgen

### PR DESCRIPTION
**Pull request by mugling**
Automated cleanup of mapgen code à la #18330

A limited number of incorrect fields were fixed in 9c90c09 and one unread field was dropped in 77f7aa0. This PR now gives us 100% linting coverage for `core` mapgen.

### CODE REVIEW

**Comment by codemime** [comment]
I hope there's not going to be more massive impacts on mapgen. I'm working on it right now.

**Comment by mugling** [comment]
> I hope there's not going to be more massive impacts on mapgen. I'm working on it right now.

#19381 intends to change the `place_loot` syntax slightly. What are you working on?

**Comment by codemime** [comment]
> #19381 intends to change the place_loot syntax slightly

That's fine.

> What are you working on?

I've replaced sequences of symbols for rotatable terrain `[a, b, c, d]` with single symbols. Now I've got to redo that part. Luckily, it's a regexp change, but I'd prefer to make sure that I won't need to redo more than that.

**Comment by mugling** [comment]
> but I'd prefer to make sure that I won't need to redo more than that.

Let me know when you're done and I'll avoid any changes that might affect that for now

**Comment by codemime** [comment]
Thank you. I'm going to work on it for today and, probably, the day after. Then I'll push the branch.

**Pull request merged**
