### PR TITLE
Change single Talmud to multiple volumes of English Talmud Yerushalmi

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Content "replace single-volume Talmud with the 51 volumes of the English Talmud Yerushalmi using variants"

#### Purpose of change

When my character scanned in the entire Talmud into his e-reader in five minutes, I did a double-take and went to check the characteristics in the data. To my surprise, the Talmud was listed as being 1L and 460g, which is hilariously wrong by multiple orders of magnitude. It's smaller than the Tanakh, and while the JPS Tanakh on my bookshelf is pretty hefty, if I had a complete edition of the Talmud it would take up the entire bookshelf.

Assuming this is supposed to be the complete text of the Talmud in English (I can't imagine most survivors can read Mishnaic Hebrew and/or Aramaic), the [Artscroll listing for the English edition of the Yerushalmi](https://www.artscroll.com/Books/yshas.html) lists it as 51 volumes on 9" by 12" pages, weighing 330 pounds. 

#### Describe the solution

Using variants, add all 51 volumes as distinct items.  At the moment I have not added any new loot lists or the Talmud as a collection, since there's realistically nowhere in the game that it would be found--since the Talmud is traditionally studied in pairs or groups, and since a full set costs thousands of dollars, even very observant Jews will rarely have one in their home and the game currently doesn't contain a dedicated yeshiva or synagogue location.

#### Describe alternatives you've considered

Changing the original item title to "An Extremely Brief Introduction to the Talmud" or something similar to reflect the in-game weight and volume. 

#### Testing

Entered game, spawned a bunch of Talmud books, variants appeared as expected.
image

### CODE REVIEW

**Comment by flybye3o6** [comment]
you could use `"snippet_category"` to make volumes of the books and change `"str_pl": "copies of the Talmud"` to `"str_pl": "Volumes of the Talmud"`
image
image
image
image

then you can look at loot spawns and have a chance for the whole set to spawn in places like homes and churches 
it wont fix the scan book problem or change any already spawned books

**Comment by Standing-Storm** [comment]
> you could use `"snippet_category"` to make volumes of the books and change `"str_pl": "copies of the Talmud"` to `"str_pl": "Volumes of the Talmud"`

Oh, that would be a better way of doing it! Plus then people could have the option to try to collect the entire 51-volume set for their rabbi character (or whatever).

**Comment by flybye3o6** [comment]
i figured making sets are more appealing because i to also like to collect full sets of things, i was looking at doing something like this for magazines and other book series
you can even customize the description for each book in the set can give it a small blurb/synopsis, its also less item bloat and wont cause any issues like with a single item being to large

**Comment by Standing-Storm** [comment]
> you can even customize the description for each book in the set can give it a small blurb/synopsis, its also less item bloat and wont cause any issues like with a single item being to large

I could probably go through and have each book be a single tractate or part of a tractate, with a brief description of what it's about. Like 

> Volume 15 of 51, Tractate Ketubot Part 1: One of the central texts of Rabbinic Judaism, the Talmud expounds on the Hebrew Bible with the teachings and opinions of thousands of rabbis. This is the first part of Tractate Ketubot, containing laws related to marriage and relationships between men and women.

I'll have to delve up my memories of doing Daf Yomi and go through them all and figure out how the books are divided, but it shouldn't be too hard.

> I have to say, seeing that the "fixed" book's size was almost 150 kilograms threw me for a loop lmao. Bit too silly though, the aforementioned "X out of 51" volumes or "brief introduction to the Talmud" ideas make a lot more sense than people having a book the size of a commercial refrigerator on their bookshelves.

Yeah, if I had known that was possible I would have started with that. But, we all have things that just shatter our sense of verisimilitude and scanning in the Talmud in five minutes did that to me. :p

**Comment by Standing-Storm** [comment]
Alright, everything is in and spawns as appropriate. This should be good to go (finally)

**Pull request merged**
