### PR TITLE
Convert character name to base64 in memorial and achievement

### LINKED ISSUE #71453: Can't save the game when character name has special characters in it
### Describe the bug

The game fails so save when you have characters in your name that windows doesn't allow in filenames. This only started happening after the new achievement saving system. Pretty sure this is related to #71327 trying to save a file with your player characters name as part of the filename.

### Attach save file

N/A

### Steps to reproduce

1.Start a new game and include characters windows doesn't allow in filenames ( / \ : ? * " < > |  ) in your player's name
2.Try to quicksave the game

### Expected behavior

The game should be able to save

### Screenshots

CDDAsavefailure

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: f2cdb18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtxyd**
#### Summary
Bugfixes "Fail to save when player name have / \ : ? * " < > | "

#### Purpose of change

fix [Can't save the game when character name has special characters in it #71453](https://github.com/CleverRaven/Cataclysm-DDA/issues/71453)

#### Describe the solution

Convert name to base64 encode. @[ehughsbaird](https://github.com/ehughsbaird) tell this simple solution, my previous solution #71464 is ? bloat?(wait for more test).
When we give up current character when the name has special chars, or save the game, memorial json file and recently added achievements json file can't generate correctly.  So there need a filter.

#### Describe alternatives you've considered

for better gameplay, we may be restrict to name. But sometimes it can be flexible.

#### Testing

[aaaa-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14151483/aaaa-trimmed.tar.gz)
image
1. create a new character with name aaa"
2. create a new character with name aaa\ 
3. create a new character with name aaa:
4. create a new character with name aaa? 
5. create a new character with name aaa*
6. create a new character with name aaa"
7. create a new character with name aaa<
8. create a new character with name aaa>
9. create a new character with name aaa| 
10. then enter the game shift+Q give up the character see if save successfully, this action can test both memorial and achievement.

#### Additional context

If there's anything wrong, pls let me know. And if someone can send me a simplified astyle converting cmd.....

### CODE REVIEW

**Comment by rtxyd** [comment]
wait, I didn't test if Chinese characters can be record correctly. I'll have a test

**Comment by rtxyd** [comment]
So, if the name is Chinese, the file name will be unreadable in this case.
Snipaste_2024-02-04_00-32-02
I wonder if my solution can be combined in this PR

**Comment by baileytom** [comment]
so the names of the files don't actually matter that much, as long as the json inside is correct it will read them all

**Comment by rtxyd** [comment]
> so the names of the files don't actually matter that much, as long as the json inside is correct it will read them all
> 
> edit: unless you're saying it is unable to get the json because of the filenames, in which case yeah it wouldn't work
> 
> edit: and also i think memorial does do some sorting based on filename so nevermind

For record, if I want to search for a certain past character to get the data or other specific things like read that json structure, I don't want to find my character file in bunch of base64 chars, maybe it's fine for English-based players, but if i18n still one of the main theme, I think this can be solved with code work. 
I am learning the structure of coding, and I want to play CDDA more deeply. So I will try to solve issues I encountered, and if there's anything wrong, I'd like someone to correct me, so so I can do it better.

**Comment by rtxyd** [comment]
now back to the other solution, to make the character name correctly record.

**Comment by ZhilkinSerg** [comment]
Base64 is a proper solution

**Pull request closed without merging**
