### PR TITLE
Adds a new fungal monster: Whispering fungi

### PR DESCRIPTION
**Pull request by zdlpoppa**
#### Summary
Content "Adds a new stationary fungal variant."

#### Purpose of change
I began making this change due to my general interest in additions to the mycus, and was inspired by the whistling fungus in home safety hotline. This stationary fungus is meant to act like a lure, to pull in hostile entities, or curious players. It's meant to be a (personal) introduction to more unique fungal monsters, that attempt to assimilate targets in a different fashion.

#### Describe the solution
This stationary fungus constantly produces sound and spores, possibly making it a good candidate for infecting other monsters. Although I made it quite rare (primarily because I'm uncomfortable with monster groups), it should be a notable addition to the cast, and it serves it's own unique role, as a sort of fungal wind chime.

#### Describe alternatives you've considered
I considered adding the marloss evangelists, however I didn't want to approach that in the same PR, since that is it's own can of worms. This specimen is primarily meant for general physical conversion instead of mental, but it still carries it's own little quirks with it.

#### Testing
Added it ingame, booted it up, and got no errors (after a few fixes), although I wasn't able to test monster groups well.

#### Additional context
Any feedback, like always, would be greatly appreciated. This has been a concept cooking in my mind for a little bit, so it's idea may not be completely compact. Also, "you cannot kill me in a way that matters"

### CODE REVIEW

**Comment by Nebnis** [comment]
This is a very creative monster! It might be worth to make as tough as fungaloid or fungaloid shambler because it is so fragile the sound it makes might make anything kill them before the player ever gets to see it

**Comment by zdlpoppa** [comment]
> This is a very creative monster! It might be worth to make as tough as fungaloid or fungaloid shambler because it is so fragile the sound it makes might make anything kill them before the player ever gets to see it

After a bit of consideration, I do think raising it's hp by 10 would be reasonable, while still making it a bit more fragile then the rest of the fungaloids.

**Comment by PGR-14** [comment]
A suggestion (just a real small idea I had), since fungi don't have windpipes, maybe it could be a fungal version of a screecher (NOT a screecher being assimilated by the mycus, but an animal or person being taken over & constantly screaming.)

**Comment by zdlpoppa** [comment]
> A suggestion (just a real small idea I had), since fungi don't have windpipes, maybe it could be a fungal version of a screecher (NOT a screecher being assimilated by the mycus, but an animal or person being taken over & constantly screaming.)

While this was a possible direction this monster could've gone down, I found the idea of a screeching fungus sort of plain. Screaming monsters, while fine, aren't the general path I want to go down, especially with the mycus. If anything, I'd rather prefer to explore different sounds/emotions

**Comment by PGR-14** [comment]
> > A suggestion (just a real small idea I had), since fungi don't have windpipes, maybe it could be a fungal version of a screecher (NOT a screecher being assimilated by the mycus, but an animal or person being taken over & constantly screaming.)
> 
> While this was a possible direction this monster could've gone down, I found the idea of a screeching fungus sort of plain. Screaming monsters, while fine, aren't the general path I want to go down, especially with the mycus. If anything, I'd rather prefer to explore different sounds/emotions

Fair enough, the Mycus & Blob are kind of essential to reachother right now, & this should help separate them.

**Pull request merged**
