### PR TITLE
Toggle proficiency learning

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
Interface "Allow toggling learning of proficiencies"

#### Purpose of change
Allow toggling proficiencies learning just like skills, that way experience won't be split between multiple proficiencies if learning multiple.

#### Describe the solution
Add a few functions to check if skill can be trained.

#### Describe alternatives you've considered
Changing color from red to dark blue, just like skills. The bright red seems a bit hard to look at.

#### Testing
Can toggle skill and when toggled on the proficiency can't be learned.

#### Additional context
Red means can't learn, hopefully it won't be a problem to players who can't distinguish colors well, since the other colors used are grey and white.

I wanted to use an overload for `fetch_learning`, but I found no way to turn `pimp<pimpl<proficiency_set> _proficiencies` into a const, `const_cast` simply refused to work, so I had to create another const method `fetch_learning_const`.

### CODE REVIEW

**Comment by actual-nh** [comment]
It is likely things are moving in the other direction, namely eliminating the (completely unrealistic) option to turn a skill's learning off.

**Comment by Saicchi** [comment]
Oh... Then I hope driving focus drain gets reduced.

**Comment by actual-nh** [comment]
> Oh... Then I hope driving focus drain gets reduced.

Understand; ping: @I-am-Erk?

**Comment by Rabidweasel** [comment]
> 
> 
> It is likely things are moving in the other direction, namely eliminating the (completely unrealistic) option to turn a skill's learning off.

In case anyone else was wondering about this see #51078

**Comment by I-am-Erk** [comment]
Actually, what we really need is a cap on how much focus you can spend per turn, so your learning rate on things drops if you have to learn several things at a time, but your focus doesn't deplete so much and we don't have to do really illogical micromanagement.

**Comment by kevingranade** [comment]
This is definitely going in the wrong direction, we need to fix focus so it's not so vulnerable to short-term exhaustion like it is.

**Pull request closed without merging**
