### PR TITLE
Add tool listing candidate items for repricing

### PR DESCRIPTION
**Pull request by sulyi**
#### Summary
~~Infrastructure "A tool listing items potentially needed to be repriced"~~

#### Purpose of change

Help a simple task make easier.

#### Describe the solution

It's a python script using `utils.import_data`.

#### Describe alternatives you've considered

Checking if item is places in any vending machine.

### CODE REVIEW

**Comment by Zireael07** [comment]
Why close? This sounds useful...

**Comment by sulyi** [comment]
It's just an over polishment of: 8f92704fc9d34fe1d2ad1f487a46e49bf3829153

**Comment by sulyi** [comment]
I might look into 'migration', see #56112.

**Comment by sulyi** [comment]
Miss formatted summary of request expresses intention not to be merged.

**Pull request closed without merging**
