### PR TITLE
Street facing churches

### PR DESCRIPTION
**Pull request by RandDenner**
Reverse facing of churches so their entrance faces the street.

#### Summary
Bugfixes "Fix churches so the entrance is street facing"

#### Purpose of change
For some reason, the maps for churches had their entrance on the bottom of the map file instead of the top. This causes the game to always draw their entrances on the opposite side they should, given the map layout. This fixes that.

#### Describe the solution
I simply reversed top and bottom. It's technically a mirror image of the original, but it doesn't matter.

#### Describe alternatives you've considered
Swapping the left and right sides as well, so it's a true 180° rotation, but it's a lot more work for no significant difference.

#### Testing
Examined naturally spawned churches, then deliberately spawned a bunch. All face away from the intended direction of rotation. North faces south, east faces west, and so on.

#### Additional context
All were oriented to face the street in the overmap files, but all face away:
image

### CODE REVIEW

**Comment by RandDenner** [comment]
I just noticed that all the natural ground is generating as dirt instead of grass. I'm fixing that before committing.

**Comment by RandDenner** [comment]
And there's a problem with the roofs now.
I'm going to have to finish tomorrow.

**Comment by RandDenner** [comment]
Okay, this is weird. It's failing the JSON validation, but I can't figure out why. It passes the linter and the only changes were in the map grids, which were only rearranged line by line and obviously passed previously.

**Comment by RandDenner** [comment]
Testing by putting a copy of the original back in to see if THAT passes the JSON validation...

**Comment by RandDenner** [comment]
Not even the original passes JSON validation for the style check, despite it working perfectly and the linter passing it with zero alterations.

It's the checker that's got the bug, not my file.

**Comment by RandDenner** [comment]
Still have to fix the groundcover.

**Comment by RandDenner** [comment]
Okay, so despite the check failures, all the churches generate with the correct facing and all the staircases line up perfectly.
image
But there's still an issue with the roof on one of them. The garden isn't generating correctly, and I think it's a coordinate issue.
Have to examine the file and see what the issue is.

**Comment by actual-nh** [comment]
That sounds like spaces getting transformed into tabs invisibly - including in what you pasted back in. Are you using the web interface or git/equivalent on your machine? The former is, from my own experience, prone to JSON formatting bugs.

**Comment by RandDenner** [comment]
I'm just using a browser. I'll check for tabs and non-space blanks with N++.

**Comment by RandDenner** [comment]
Hmmm... not even uploading the file directly fixes the check issue.
To hell with it. This file works perfectly. I tested it locally, multiple times.
Something is wrong with the checker, not this file.

**Comment by RandDenner** [comment]
Note to all: it was an end of line (EOL) character problem.
The file was using Windows' CR LF format, instead of Unix LF only.
Thanks actual-nh!

**Comment by RandDenner** [comment]
Waiting for #51243 to restart checks as that killed the GCC Ubultu cross compile check

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
