### PR TITLE
Add extinct megafauna creatures - as a new Megafauna mod

### PR DESCRIPTION
**Pull request by merrygin**
#### Summary
Mods "Add Megafauna Mod"

#### Purpose of change
Playing the innawoods mod a lot recently, also watching youtuber Rycon Roleplays' let's play of it, I was whishing there was more setting-appropriate fauna. First thing that came to mind was extinct megafauna which was abound in New England before and until around the time the first humans arrived - animals like sabre-toothed cats, mastodons and mammoths, giant bears (as well as giant beavers and sloths) and many more. 
Speaking only about innawoods, there is a very restricted set of modern day wilderness creatures, that 1) mostly don't reflect the pre-civilization fauna of North America (it's very odd to encounter droves of chihuahuas and dachshunds when you pretend to be a cave man ;D ) and 2) the wilderness creatures of the base game are not super variable - of course they don't need to be, necessarily, because of the zeds and other monsters - so they get a bit stale after a while, imho. As a side effect (thats not too important to me, but probably relevant for many), some of these species can be considerably challenging enemies due to their size and strength, adding combat challenge in zed-free playthroughs.

#### Describe the solution
Add extinct megafauna from roughly the area that is modern day New England and roughly the time the first humans arrived there to keep it realistic to an extent, so no terrorbirds from South America, for example (*roughly* 30.000-8.000 BCE). Try to replace animals that were not part of the ecosystem at the beginning of the holocene (like the wild boar) with equivalents (like peccary species). 
List of 16 new species added:

- [x] woolly mammoth
- [x] mastodon
- [x] dire wolf
- [x] sabre-toothed cat
- [x] american cave lion
- [x] giant short-faced bear
- [x] short-headed peccary
- [x] long-nosed peccary
- [x] wood-ox
- [x] shrub-ox
- [x] Scott's horse
- [x] Camelops
- [x] giant beaver
- [x] large claw sloth
- [x] stag moose
- [x] ancient bison

I will start developing this as a separate content mod as discussed below.

#### Describe alternatives you've considered
It might be an idea to develop this similar to the DinoMod, so looking more into how to square it with the base game (failed gene experiments, extinct animal zoos, etc.), adding locations and the like. For now I wanted to focus on my interest in an even more immersive innawoods(-like) experience.
Also, you could get more whacky with what animals to add, like the aforementioned Terrorbirds, Dodos, and stuff like that. Might be fun for the future but, again, not immediately important to what I'd like to do.

#### Testing
I tested the existing animals now, made a number of tweaks to make the behavior more interesting. Especially for fighting behavior in different circumstances as well as spawning it just needs playtesting in real saves, which I did a little bit, but of course more will be better.  

#### Additional context
Here is some background on some awesome [prehistoric megafauna](https://en.wikipedia.org/wiki/Pleistocene_megafauna#North_America) examples:
https://en.wikipedia.org/wiki/Arctodus
https://en.wikipedia.org/wiki/Cervalces_scotti
https://en.wikipedia.org/wiki/Megalonyx
https://en.wikipedia.org/wiki/Woolly_mammoth

### CODE REVIEW

**Comment by Maleclypse** [comment]
@LyleSY tagging you in case dinomod wanted this content?

**Comment by LyleSY** [comment]
Might grab some of this for a special or something. Thanks for doing this, wooly mammoth and saber tooth tiger are the two most requested monsters for DinoMod outside the design scope. Dimetrodon probably number three

**Comment by LyleSY** [comment]
I know a lovely Titanis in Aftershock you might like

**Comment by LyleSY** [comment]
It might help to pick a time period to shape your thinking. DinoMod is Mesozoic, gives some shape to what goes in and out. It seems like you're focusing on Paleogene right now https://en.wikipedia.org/wiki/Paleogene#Flora_and_fauna

**Comment by Xaritscin** [comment]
A Cenozoic mod is something i was thinking the other day. totally support this, if you're doing the same route as Dinomod i think New England in the pleistocene must have had quite the variety of megafaunae. even if it was close to the giang ice sheets. you could include the following to make it more chunkier (not 100% on plausibility tho)

-Wild Horses and Asses
-Ground Sloths
-Dire Wolves or other extinct canids
-Camelids (North America was choke full of them before humans arrived)
-Auks (cause why not?)
-Machairodontines (AKA "Saber Toothed Cats")

i think for the climate of the region in the vanilla game this should be good enough. Dinomod already stretches things a lot by letting dinosaurs roam the state even with current holocene temperatures.

**Comment by merrygin** [comment]
Thanks for the input everyone! 
Yeah, I figuered it might be best to start this as a separate project, expecially since I am currently planning to replace some of the existing wildlife to match. Can absolutely assume a portal storm lore behind this, no problem. Also definitely will include shearable and milkable animals.
For the timeframe, I did think about concentrating on late pleistocene/early holocene (30.000-8000 BCE or something, possibly a bit earlier if necessary), so roughly the time of the big quaternary megfaunal extinctions in NA. The general idea being that it should be animals modern humans have encountered. I also agree its ok stretching the geographical ranges a bit, since records might be relatively spotty and especially if a genus has been around in NA for a long time it makes sense (like horses or camelids). I don't want to stretch it too too much though (at least for now). I'd prefer a reeelatively "realistic" feeling fauna for the region. So if the species only has been found in New Mexiko and southern Texas or something, I'd probably think twice about that one. Not sure about species that lived in presumably similar climates but only in western US yet. Seems a bit like splitting hairs not to include those if they are cool, especially since having something like camels around will already not feel incredibly realistic to most, i reckon. So yeah, I'll keep thinking about it and appreciate your thoughts about it.

I'll keep a ToDo list of possible species to add in the Readme, so if someone has more ideas what species I should check out, just write it here and I'll add it.

**Comment by LyleSY** [comment]
You might consider the NOBREED flag for the young to avoid reproduction explosions. Nice, the new Glooscap NPC talks about those giant beavers. Yeah, a lot of the fossil record you're talking about went out to the ocean a long time ago (erosion is bad), so I personally take a continental view with DinoMod to try and make up for all the missing stuff but it's up to you

**Comment by merrygin** [comment]
Oh, good call with the NO_BREED, thanks. I am currently adding juveniles for all creatures, I am not sure if that might be a problem in that regard in and of itself?
Yes, right, I was reading the giant beaver's wiki article and saw that name, thinking, hang on, isn't that the same guy added to the game?! Its wild to think how relatively recently some of these creatures were around.
Yeah, I am still not sure about the geographical scope. More creative licence might be more useful and fun in the end than marginally more realism concerning a very unfamiliar environment for players today that even science is unsure of. Although the records *are* a bit better for pleistocene fauna than for dinos, just because of the time frames involved. I think for now I'll do it case by case and but try not to be too nitpicky.

**Comment by merrygin** [comment]
The first basic set of animals is now added, I am able to start up a new game without errors. Next up is testing and tweaking the creature's behaviour/stats. 
One preliminary test with the mammoth was weird. It disappeared when killed. It's probably too massive (6tons) for the grass tiles!? I see that you, @LyleSY capped your dinos at 1000kg, I guess for the same reason, right?

**Comment by Light-Wave** [comment]
>capped your dinos at 1000L/1000kg, 

Ground tiles does not seem to be able to support more than 1000L, and trying to drop an item with more volume than that seems to make the item fall out of reality right now. So yeah, don't have items with more mass than 1000. Not sure if the same applies to weight.

**Comment by LyleSY** [comment]
Yes, weight too if you want harvesting to work. #44508 is this

**Review by LyleSY — APPROVED** [review]

**Comment by evankimori** [comment]
Here's a question: any possibility of adding taming to the larger ones (Mastodon for eg) so that we can have a tame one to provide Shearing access?

**Pull request merged**
