### PR TITLE
Remove rock from makeshift shaving kit recipe

### PR DESCRIPTION
**Pull request by Cyrano7**
No rock short of obsidian is sharp enough to shave with.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Other options include seashells, flint, copper, or bronze. Or could add glass shards, those could possibly be knapped to a fine enough edge, though I am uncertain.

**Comment by mugling** [comment]
Removal doesn't necessarily require replacement

**Comment by DangerNoodle** [comment]
Merely presenting ideas, in the event that wilderness-made shaving kits are deemed desirable. As it stands, it is a minor morale item with no practical benefits, so there is no real need for it to be easily improvised.

Replacing it with a sensible makeshift alternative is okay, but not essential.

**Comment by mugling** [comment]
Well wilderness should be a challenge - not a parallel tree of alternative recipes

**Comment by DangerNoodle** [comment]
True. And shaving is rather low on the player priority list in the first place.

**Pull request merged**
