### PR TITLE
Adds several wire crafting recipes using wire draw machine

### PR DESCRIPTION
**Pull request by Marcos6226**
#### Summary
Content "Adds several wire recipes, now using the wire draw machine"

#### Purpose of change
Closes https://github.com/CleverRaven/Cataclysm-DDA/issues/60525

It's weird that we have a wire drawing machine but cannot use it to draw steel wires. 
This PR adds several steel wire recipes that use this machine to facilitate the amount of labor necessary to draw wires.

#### Describe the solution
I have added the recipes based on the copper wire one, but with the addition of necessary proficiencies and crafting materials, as well as tools, in the case of the tempered steel wire.

#### Describe alternatives you've considered
I'm not entirely sure if the time and charges required are perfectly balanced, but if you have any suggestions, I'm all ears.

#### Testing
I have created a new character and opened the crafting menu to check if the crafting recipes are correct, and they are working as intended, as shown in the screenshots below. 

#### Additional context
Captura de Tela (23)
Captura de Tela (24)
Captura de Tela (25)
Captura de Tela (26)
Captura de Tela (27)

### CODE REVIEW

**Comment by ANickelN** [comment]
image
Those items are nested properly as of the latest version, not sure why they are throwing an error for you.  Would recommend updating, starting a new world and seeing if it still throws those errors.

**Comment by Marcos6226** [comment]
> Those items are nested properly as of the latest version, not sure why they are throwing an error for you. Would recommend updating, starting a new world and seeing if it still throws those errors.

Thanks, I'll update to latest and test if it will throw any erros.

**Comment by Marcos6226** [comment]
It worked! Thanks ANickelN. ❤️

<sub> As a side note I feel a bit ashamed for not updating my game and causing this trouble...</sub>

**Comment by ANickelN** [comment]
It is no trouble, this is a good addition.  I'll make a nest for it when it gets merged.

**Comment by Fris0uman** [comment]
Should those recipes really require a forge and an anvil since they use the drawing machine already? Very quick look at wikipedia suggest that wire drawing is done at room temperature. https://en.wikipedia.org/wiki/Wire_drawing

**Comment by Marcos6226** [comment]
> Should those recipes really require a forge and an anvil since they use the drawing machine already? Very quick look at wikipedia suggest that wire drawing is done at room temperature. https://en.wikipedia.org/wiki/Wire_drawing

The forge, hammer, and anvil are present because, as in the normal recipe, raw materials are used to make crude wires, but the wire draw machine is used to make refined wires. Normally, you'd have to manually file them to the desired thickness. By using the wire draw machine to do this refining work, we reduce the amount of labor required, as it is now a light activity, as well as the time required to complete it.

**Comment by ANickelN** [comment]
Just got around to nesting the new wire recipes in with the older ones.  They will be properly nested when #60708 gets merged.

**Comment by Marcos6226** [comment]
> Just got around to nesting the new wire recipes in with the older ones. They will be properly nested when #60708 gets merged.

Thank you very much. =)

**Pull request merged**
