### PR TITLE
Upgrade mall walls and glass

### PR DESCRIPTION
**Pull request by curstwist**
#### Summary
```SUMMARY: Balance "upgraded walls and glass windows/doors"```

#### Purpose of change
To make mall survival more dynamic.
EDIT: added more glass wall/door types.

#### Describe the solution
I've swapped the basic walls for brick.  This is largely aesthetic, but keeps accidental wall bashing from happening as often.

Added reinforced glass & doors to control zombie movement some and also offers a more maze like navigation option for players.  This makes the mall feel much more dynamic. It also helps keep zombie threats on the 2nd floor.

Edit: based on feedback, added ballistic glass doors/windows (and added to military bunkers for a sample) and laminated glass doors/windows for the mall.  I can address other locations in future PR's.  I give brick walls a slight bash bonus since it was significantly lower then other strong walls.  There's no existing documentation for min/max strength for bashing terrain, so that could be a good future review project.

#### Describe alternatives you've considered
Even more zombie spawns but I think I should get some feedback first.

#### Additional context
image
image
image

### CODE REVIEW

**Comment by crazykiddeath** [comment]
The brick walls look very stylish but I have to question the reinforced glass a bit, is that a thing in malls? (We're talking the glass walls that can stand off most bullets right?)

**Comment by ampersand55** [comment]
> The brick walls look very stylish but I have to question the reinforced glass a bit, is that a thing in malls? (We're talking the glass walls that can stand off most bullets right?)

The description for reinforced glass says it's reinforced by metal wires:

> A thicker pane of glass with thin metal wires embedded throughout, strengthening the structural properties.  Still weaker than other types of walls, and not made to support a roof either.

From the description it seems like reinforced glass is meant to be wire mesh glass. But that is actually weaker than unwired glass due to the incursions of the wire into the structure of the glass.

> Wire mesh glass (also known as Georgian Wired Glass) has a grid or mesh of thin metal wire embedded within the glass. Wired glass, as it is typically described, does not perform the function most individuals associate with it. The presence of the wire mesh appears to be a strengthening component, as it is metallic, and conjures up the idea of rebar in reinforced concrete or other such examples. Despite this belief, wired glass is actually weaker than unwired glass due to the incursions of the wire into the structure of the glass. Wired glass often may cause heightened injury in comparison to unwired glass, as the wire amplifies the irregularity of any fractures. This has led to a decline in its use institutionally, particularly in schools

* https://en.wikipedia.org/wiki/Safety_glass#Wire_mesh_glass

I believe the description should be changed to be ballistic/bulletproof glass, or at least glass that has been tempered and laminated.

> Bulletproof glass is used in windows of buildings that require such security, such as jewelry stores and embassies, and of military and private vehicles. 

* https://en.wikipedia.org/wiki/Bulletproof_glass

Glass aside, I really like the brick wall changes. It seems like every time I'm in a mall it gets demolished by hulks and brutes.

**Comment by curstwist** [comment]
I agree with @ampersand55, it's probably best to add some new glass walls/doors.  A set for military installations and another for commercial use.  

That might be best suited for a new PR so I can change the military glass too.  For now, I'd like to use these since the 2nd story of the mall is fairly broken without some zombie control.  I'll work on some new sets next.

**Comment by Petethegoat** [comment]
Nice work! Please check ballistic glass description: aminated -> laminated

**Comment by curstwist** [comment]
Got new doors/windows added, sorry for the slightly messy PR.  See edits in PR for more information.

**Comment by thor-kiessling** [comment]
image

Hey there, some balance feedback. I'm on 9508 and these guys don't even try to bash the laminated glass, and you can shoot right through it. Observe my shooting gallery, I am completely safe here. I don't believe complete safety+no problem shooting was the intention.

**Comment by anothersimulacrum** [comment]
Being able to shoot through glass is a bug, so that is very much not expected.

**Pull request merged**
