### PR TITLE
Say item (1 of 2) instead of (2 of 1) for crafting requirements

### PR DESCRIPTION
**Pull request by perryprog**
#### Summary
None

#### Purpose of change

To clarify how the crafting requirements say how many of an item you have versus how many of the item is required in crafting something.

Aside: I feel like I'm almost incorrect in making this change based on how long it's been present, but I'm also fairly confident this isn't a regionalism in how things like "1 of 2 glass flasks" is stated.

#### Describe the solution

- Text that would have said "duct tape (10 of 5)" now says "duct tape (5 of 10)", based on "you have 5 out of 10 duct tape". 
- Text that would have said "2 glass flasks of 1" now says "1 glass flask of 2".
  - This could also be "1 of 2 glass flasks", but I chose the version with the least amount of change. I think I prefer "1 of 2 glass flasks", but I'd like to hear what others think as well.

#### Describe alternatives you've considered

- See note on "1 glass flask of 2"

#### Testing

I looked at items with both charge-requirements and item count requirements, and they displayed as expected in the `&` crafting UI.

### CODE REVIEW

**Comment by wapcaplet** [comment]
I think this could lead to a lot of confusion. The current format of these requirements is `#needed of #available`, and you are swapping the meaning of these numbers, without giving the user a clue about what has changed.

For instance to make tea, you need 1 tea bag, and 1 clean water. Before your change, it appears like this:

image

After your change, the number available is shown first, as you have intended:

image

But because I am so used to the current format of `#needed of #available`, this at first looks to me like the tea needs 10 tea bags and 6 clean waters.

I am not clear what purpose this change is intended to serve. What is the benefit of showing these numbers in a different order, instead of the order they are in now?

**Comment by Zireael07** [comment]
Can we make the text "n: x of a: y" and explain n and a ("needed" and "available") where keybindings are given? This way it would be clearer, whichever order we go with...

**Comment by GoLoT** [comment]
If the numbers are swapped then the "Components required" should be changed to "Components available". Semantically "Components required" fits the current way of displaying requirements. This might not be enough to clear the initial confusion though.

Having "n:" and "a:" will clutter the menu and make it less readable IMO, I think I'd rather have the numbers swapped and get used to it.

**Comment by PatrikLundell** [comment]
The "current" format is confusing when encountering CDDA, with the new one more suitable for newcomers. However, neither is particularly clear as to which number is which and what they actually mean.
Thus, I'd suggest providing a hint in the form of "Components required (available / required)": and change the entry format into "black tea bag ( 10 / 1)". The word "of" makes sense in the original ordering (need 1 of my 10 items), but not much with the changed order.
I'm not set on using exactly "/". Whatever is deemed making the most sense while still "wasting" as little space as possible should be fine (":" is a possible alternative, for instance.

**Comment by perryprog** [comment]
> I think this could lead to a lot of confusion. The current format of these requirements is `#needed of #available`, and you are swapping the meaning of these numbers, without giving the user a clue about what has changed.

You're right, a visual change is clearly needed here. I'm thinking of it in terms of expanding it like so: "Duct tape is a component required in crafting this. You have 5 duct tape of the required 10 duct tape."

>I am not clear what purpose this change is intended to serve. What is the benefit of showing these numbers in a different order, instead of the order they are in now?

My general line of thought is that "of" is meant strictly as in "n parts of a whole": to me, it's always been unclear what the whole was. It wasn't until I heard @PatrikLundell's "need X of my Y" that I understood how that ordering actually made sense :). I ultimately think that #required of #available is confusing, both to new players, and apparently mildly experienced players (me), hence this PR.

-----

> If the numbers are swapped then the "Components required" should be changed to "Components available". Semantically "Components required" fits the current way of displaying requirements. This might not be enough to clear the initial confusion though.

Hm, yeah—this is a good point. It's pretty hard to communicate what my version of the change means in this case.

-----

> I'd suggest providing a hint in the form of "Components required (available / required)": and change the entry format into "black tea bag ( 10 / 1)". The word "of" makes sense in the original ordering (need 1 of my 10 items), but not much with the changed order.

I do like this, especially considering "of" can clearly be interpreted in even direction (much to my surprise!). 

Using (avail/req) does make sense, and would likely lead to a lot less confusion than my current change, especially with the extra hint in the "Components required" text. If I recall correctly, there is some other areas that use `item_comp::to_string` outside of the context of the crafting menu, so that extra detail would be lost in those cases.

I think I'm more in support of this version than the one my PR has, although I'm uncertain what to do about count-based required (e.g., "1 glass flask (available) of 2"). I would lean towards the same ordering of (avail/req), but that runs into the problem that we're stating it's "Components required: 1 glass flask (available) of 2 (required)".

(Dear goodness I really didn't expect this change to be so confusing. Apologizes for the seriously lengthy response; hopefully I didn't mix any ordering up in my comments.)

**Comment by Zireael07** [comment]
> (e.g., "1 glass flask (available) of 2")

This would work fine too, as it implies that the 2 is required (and is less wordy than spelling out available/required always)

**Comment by wapcaplet** [comment]
> The "current" format is confusing when encountering CDDA, with the new one more suitable for newcomers. However, neither is particularly clear as to which number is which and what they actually mean.

> My general line of thought is that "of" is meant strictly as in "n parts of a whole": to me, it's always been unclear what the whole was.

Now I see what you mean about the ambiguity of "of" in this context, especially when it's just `(x of y)` next to an ingredient. I agree, there is room for improvement here.

Here's another idea, again for tea:

```
Components required:
> 1 black tea bag (10 available) or 1 black tea leaf (3 available)
> 1 clean water (6 availble) or 1 water (34 available)
```

The benefit I see with this format is that it puts the ingredient quantity needed *first*, like a recipe you might see in a cookbook, and gives a clear separation between that and the number you have available (which is secondary information). This makes it easier to skim the ingredients quickly - I need 1 of this and 2 of that, etc.

One big drawback is the length of the word "available" - large recipes with lots of alternatives will be very cluttered with repetitions of this word, hindering readability. Perhaps  `(have 10)` or `(have 6)` would work better:

```
Components required:
> 1 black tea bag (have 10) or 1 black tea leaf (have 3)
> 1 clean water (have 6) or 1 water (have 34)
```

or it could be shortened back to the original "of", which I think would now have a clearer contextual meaning, though not as good as "have":

```
Components required:
> 1 black tea bag (of 10) or 1 black tea leaf (of 3)
> 1 clean water (of 6) or 1 water (of 34)
```

Either way, this ordering would feel familiar to current players, while being an improvement in clarity over what we have now. Putting the needed quantity in front makes it quite clear what that number means, I think. Thoughts?

**Comment by Zireael07** [comment]
"have" is better (less ambiguous) than "of" and only takes 2 more letters :)

**Comment by perryprog** [comment]
Sounds good to me. I'll adjust item count requirements to use "have".

For charge count requirements, is something like "duct tape (have #available of #required)" also clear?

**Comment by perryprog** [comment]
Hm, I admittedly don't _love_ the look of the item-count version of this, but I do think it's an improvement.
screenshot of item count charge requirements

Force-pushed to avoid a misleading commit message, but this should be ready for another look. Apologizes for the delay in updating the PR.

**Comment by wapcaplet** [comment]
> For charge count requirements, is something like "duct tape (have #available of #required)" also clear?

It has always bothered me that "count by charges" items are displayed differently in so many UIs, since it is really just an implementation detail whether an item is counted by charges. As a player, I don't care if my rags are counted like `5 rags` or `rag (5)`. In the context of a recipe, the "count by charges" detail matters even less.

I think it would be better to show all recipe components in a consistent format, and I still think that format is what I proposed earlier: quantity needed first, then the name of the ingredient. Secondarily, and parenthesized, should follow how many you have available (if any).

```
Components required:
> 500 avgas fuel OR 500 denatured alcohol OR 500 ethanol OR 500 ether OR 500 gasoline OR 500 methanol
> 1 rag
> 1 glass bottle OR 2 clay canisters OR 2 glass flasks (have 1)
```

As it may look cluttered with `(have N)` clauses:

```
Components required:
> 500 avgas fuel (have 130) OR 500 denatured alcohol OR 500 ethanol (have 934) OR 500 ether (have 10) OR 500 gasoline (have 15990) OR 500 methanol
> 1 rag (have 27)
> 1 glass bottle (have 14) OR 2 clay canisters OR 2 glass flasks (have 1)
```

The main thing I feel strongly about here is putting the needed quantity first and foremost, and not moving its position around in the ingredient list.

**Comment by perryprog** [comment]
Since it's been a bit and no-one seems to have any disagreement with @wapcaplet's suggestion, I've gone ahead and done exactly that—I think that's by far my favorite solution here, and also gets around that weird implementation leak on count-by-charge items. Here's what it currently looks like with my last commit:
image
image
image

**Comment by perryprog** [comment]
@BrettDong, would you mind confirming that these changes are okay from the i18n side of things? (Sorry for putting you on the spot, I just figure you might happen to know. :) )

**Pull request merged**
