### PR TITLE
Move place zombie mom to mission JSON

### PR DESCRIPTION
**Pull request by cathalpern**
#### Summary
None

#### Purpose of change
In the interest of achieving #3951, this removes the place_zombie_method (and its add_spawn call) and uses the mission templates to place a zombie as the target of the Kill Zombie Mom quest

#### Describe the solution
Use the now built in JSON-ification of generating mission based objects and monsters instead of the hard coded C++ implementation

#### Describe alternatives you've considered
Update the hard coded add_spawns in place_zombie_mom to use place_spawns - but that seemed silly

#### Testing
Assigned start NPC the Kill Zombie Mom quest, went to house, killed zombie mom, verified that NPC was indeed grateful

### CODE REVIEW

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by Night-Pryanik** [comment]
The only difference is that right now through json we can't give this zombie a random female name. Might need to add this functionality some time in the future.

**Comment by cathalpern** [comment]
> The only difference is that right now through json we can't give this zombie a random female name. Might need to add this functionality some time in the future.

I guess I could hard code one for now, to at least make it easier to tell what zombie you're supposed to be targeting?

**Comment by Night-Pryanik** [comment]
Yeah, as a temporary solution this will suffice.

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by Night-Pryanik** [comment]
@cathalpern could you please resolve conflicts?

**Comment by bombasticSlacks** [comment]
need to appease clang and remove the unused var

**Pull request closed without merging**
