### PR TITLE
New Bow Attachments

### PR DESCRIPTION
**Pull request by darktoes**
**Intention:**
This PR is to add some new mods for bows, diversifying them a bit, and hopefully working with my other two PRs to make archery a stronger option ingame and a bit closer to reality. Also, to add crafting recipes for the new items so players actually have access to them. I may also PR changes to spawn groups so they can be scavenged later on.

**Features**
Adds 2 new bow sights, giving three options of varying speed and accuracy.
Added a handling bonus to the stabilizer mod, and slightly reduced it's dispersion. Moved it to the stabilizer mod slot.
Added a stabilizer system to give a bigger, better, stabilizer.
Added a bow dampening kit, to reduce the firing noise of bows, as well as slight accuracy and handling bonuses.
Gave bows with mod slots two new slots, stabilizer and dampener, so the new mods can be installed.

### CODE REVIEW

**Comment by cainiaowu** [comment]
you can use the web linter.

**Comment by darktoes** [comment]
Which one would that be? I know of two but I'm not sure which one to use.

**Comment by Night-Pryanik** [comment]
http://dev.narc.ro/cataclysm/format.html
This one.

**Comment by darktoes** [comment]
Now that all 4 checks are passed I can't think of a single reason anyone could not want these added.

**Pull request merged**
