### PR TITLE
increase healthy timescale

### PR DESCRIPTION
**Pull request by Saelfen**
#### Summary
Balance "Increase healthy timescale"

#### Purpose of change
Healthiness had such a short timescale that it rendered the whole comestibles healthiness mechanic nearly obsolete. Starting from -100 healthiness, after just 24 hours, the value drops to -10. In addition to that, it stayed at -10 after an additional 24 hours as a result of a rounding bug, so it would evidently be back to ~0 just after 24 hours.

This would also, hopefully, push players in the direction of choosing what they eat more carefully. No more eating only the snacks dropped by zombies as you loot, or imbibing gallons of cooking oil. At least, this time, at the risk of significant health penalties.

#### Describe the solution
Increase the time scale for `healthy mod`.
1) Decrease check frequency from once every 30 minutes to once every hour. This also affected `get_sick()` so `checks_per_year` was also updated.
2) change mod_healthy reduction magnitude per check from 95% of original value to 99%, increasing time scale by ~5x

If the player ends up getting themselves extremely unhealthy, they can always offset by eating healthily. 

#### Describe alternatives you've considered
5x timescale instead, but it felt like it still moved too quickly to the point a junk food diet wouldn't have much of an effect.

#### Testing
Below are `healthy_mod` values after several 24 hour time progressions. tl;dr, it's approximately 10x slower timescale, which is anecdotally closer to reality.
Day 0: -100
Day 1: -77
Day 2: -60
Day 3: -48
Day 4: -38
Day 5: -32
Day 6: -25
Day 7: -19
Day 8: -15
Day 9: -12
Day 10: -8

### CODE REVIEW

**Comment by Venera3** [comment]
Health is a horribly unrealistic gamey system as is, making it more important without adressing anything about that is a hard sell.

**Comment by actual-nh** [comment]
> Health is a horribly unrealistic gamey system as is, making it more important without adressing anything about that is a hard sell.

Good point; @anothersimulacrum, thank you for correcting my tagging.

**Comment by AccountAlias** [comment]
@Venera3 Could I be pointed in the right direction/documentation for how health should go? It seems I'm ignorant to the other problems `health` as a stat has. From there, the PR can just be about the rounding bug and I can potentially address the issues in a different PR

**Comment by Broken27** [comment]
> imbibing gallons of cooking oil

Cooking oil is actually healthy 0, so actually not super relevant here.

**Comment by AccountAlias** [comment]
@Broken27 Cooking oil has -2 healthy as of #49758

**Comment by actual-nh** [comment]
> @Venera3 Could I be pointed in the right direction/documentation for how health should go? It seems I'm ignorant to the other problems `health` as a stat has. From there, the PR can just be about the rounding bug and I can potentially address the issues in a different PR

#37446 is a start; there has been other discussion, to put it mildly.

**Comment by Venera3** [comment]
Health is trying to be a realistic abstraction and a gameplay factor at the same time, and it fails at both:

Gameplay-wise it's supposed to promote varied diets by assigning tangible rewards/penalties to some arbitrary value of food "healthiness" (we'll circle back to this below), but the way it's set up is both very gameable and prone to semi-random negative feedback loops (the flu makes you throw up, making you hungry which drops your health which makes you contract the cold...). In effect all it does is makes players deforest New England for pine needle tea while otherwise stuffing their face on whatever they were eating anyway. In addition, calorie-dense food almost universally has a negative health value, but the fact you *need* those calories these days makes you juggle two incompatible systems.

That takes us to realism, nutrition and its health effects just. Don't. Work. Like. That. The stereotypical "unhealthy" (fast-metabolized sugars, high animal fat content) foods are unhealthy over a period of decades, *in the context of our cushy sedentary lifestyle*. The player character is essentially a hunter-gatherer walking miles with a 50+kg cardboard loot box in their hands, regularly burning 8k+ kcal a day while crafting/fighting/clambering on rooftops - their risk of both Type 2 diabetes and heart disease will be pretty low, not that it will save them in the long run. Even if we ignore the exercise the game's time span doesn't accommodate developing such chronic conditions. The effects/penalties of health are squarely in the land of pseudorealism as well: ~~for the last time this year,~~ eating an apple a day does not protect you from a respiratory infection, neither does it speed up your healing rate. Aside from some special populations, dietary interventions beyond "cover daily caloric/macronutrient needs" has pretty consistently showed no significant effect on in-hospital trauma/systemic infection survival and morbidity.

Sorry, that got quite ranty there, but it's one of my little bugbears. I see the idea behind the system as a way to force players out of their comfort zone, but trying to wrap it up as a realistic abstraction of *somatic* health will fall very short. I could see a replacement as a part of a long-term morale rework: mounting desperation that the rest of your probably-short life will be spent trying to keep down mutant meatballs, elation at finding an unmolested toast-em, that sort of thing.

**Comment by AccountAlias** [comment]
I really appreciate the insight on why healthy as it is, is not so great. I will be closing the PR and following it up with just the rounding bug fix

**Pull request closed without merging**
