### PR TITLE
Removed myself from codeowners and maintainers of No Hope mod

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
None

### CODE REVIEW

**Comment by NetSysFire** [comment]
Please sleep one night over it. I know this (https://github.com/CleverRaven/Cataclysm-DDA/pull/58380#issuecomment-1484721818 and https://github.com/CleverRaven/Cataclysm-DDA/pull/62760#issuecomment-1484722322) is probably stemming from some discord drama which I have not seen, but rest assured that your contributions are still appreciated and I would be sad to see you leave.

**Comment by Nebnis** [comment]
SysFire is absolutely right, some of the leadership can be incredibly difficulty but the community definitely appreciates every single work you do, and that alone is worth the effort.

**Comment by Raikiri** [comment]
I hope it's not getting merged

**Comment by Termineitor244** [comment]
For those unaware:

https://www.reddit.com/r/cataclysmdda/comments/123w2oh/the_end/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

 #64586 (Closed PR that led to this whole debacle).

Thank you for your contributions NP, sad to see you go.

**Comment by NetSysFire** [comment]
As much as I hate to potentially bring up drama, I do partially understand NP's reason and a similar thing happened in e.g #54439. Closing PRs with "Nope" or similarly nondescriptive and unhelpful comments (including nothing) has got to stop, especially when the reactions to the PR are overwhelmingly positive.

**Comment by RenechCDDA** [comment]
The bloating of the options menu (whether you agree with it or not) was particularly exacerbated in this case though, and NP was previously aware of this being an issue (https://github.com/CleverRaven/Cataclysm-DDA/pull/62583#issuecomment-1340639983). I can't find it on GH, maybe it was on discord, but I distinctly remember Kevin firmly telling him: *No, do not make it an option*. It takes up an entire scrollable settings page to display the categories, so I personally can see why this is a problem... and this is kevin's position which has been widely known.

Attempting to PR that was never going to end well, although it could have been handled with more tact.

**Comment by Night-Pryanik** [comment]
> I can't find it on GH, maybe it was on discord, but I distinctly remember Kevin firmly telling him: No, do not make it an option.

No, it wasn't on GH and no, it wasn't on Discord, neither anywhere else. We never discussed this particular feature with Kevin and thus he never explicitly stated his opinion on it and form it should be implemented in.

**Pull request merged**
