### PR TITLE
Lets player construct earth ramp (low and high).

### PR DESCRIPTION
**Pull request by dan-netizen**
#### Summary
Content "Construct earth ramps"

#### Purpose of change
If one can construct concrete ramps with 5 units of concrete and 5 units of water (x2), one should be able to construct an earthen one with dirt, rocks and planks/sticks for reinforcement.

#### Describe the solution
Cloned all the aspects of concrete ramp building and made changes where appropriate.

#### Describe alternatives you've considered
Not adding this.

#### Testing
Spawned components, built earth ramp next to building, climbed on said building using ramp.

#### Additional context
Maybe fine tune the components.

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
@dan-netizen I've made a pull request to your branch which lints construction.json, merging that should fix the current errors.

**Comment by dan-netizen** [comment]
> @dan-netizen I've made a pull request to your branch which lints construction.json, merging that should fix the current errors.

Thanks, I went to bed after the pull request.
I bookmarked the formatter for future use.
Cheers!

**Comment by ashGlaw** [comment]
This is a great idea. Big improvement to the construction menu

**Comment by dan-netizen** [comment]
The Windows build check fail, from what I saw in the details, was because of this error:
`01:51:21.638 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1501 [put_in] tried to put an item (talking_doll) count (1) in a container (purse) that cannot contain it: pocket unacceptable because not enough space`
My json code in the commit has nothing to do with any of these items.
What should I do?

**Comment by MNG-cataclysm** [comment]
> The Windows build check fail, from what I saw in the details, was because of this error: `01:51:21.638 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1501 [put_in] tried to put an item (talking_doll) count (1) in a container (purse) that cannot contain it: pocket unacceptable because not enough space` My json code in the commit has nothing to do with any of these items. What should I do?

I'd try making an extremely small change in the code to restart the tests. Alternatively, you could ask one of the developers to restart that test.

**Comment by MNG-cataclysm** [comment]
@Maleclypse Could you restart the Windows build test, please?

**Review by MNG-cataclysm — APPROVED** [review]

**Comment by LyleSY** [comment]
Idea makes sense and I think you're going about it in a good way. Not sure I buy that a ramp can be shoveled together as quickly as the concrete can be poured and smoothed. I would think it would take twice as long and work half as well. Otherwise I think this looks good. I think you're building wooding frames, pounding them in place with sticks and your nice hammer, and then filling that in with earth which I think you're also pounding flat with your shovel?

**Review by LyleSY — COMMENTED** [review]
I don't think this is a deal breaker, but I think that doubling the time to get this done is more realistic since you're not using all the wonderful modern equipment that would be used today. We don't have a quality system but if we did I'd suggest that this should be twice as breakable as the concrete version

**Comment by dan-netizen** [comment]
> I don't think this is a deal breaker, but I think that doubling the time to get this done is more realistic since you're not using all the wonderful modern equipment that would be used today. We don't have a quality system but if we did I'd suggest that this should be twice as breakable as the concrete version

Thanks for the review, yeah it makes sense for the work to take longer.
I was thinking about the office complex that is being built 2 blocks from my place, and I saw the excavators and whatnot carry stuff from -2 basement level to +1 or more, on literally a mound of dug out earth that was growing daily.
Ofc, a lone man with a shovel and a hammer won't be able to compare to modern tools and equipment.
Regading the quality of the construction, I also agree, however it's meant for occasional use by a lonely survivor, not a metropolis highway,  so maybe when it will be possible, make a deathmobile-pass-until-break-counter, but a cart or bike shouldn't be a problem.

That being said, the time is now double, and more suggestions are welcomed.

**Review by LyleSY — APPROVED** [review]
Solid

**Pull request merged**
