### PR TITLE
Re-enable Internal Furnace CBM spawn in Aftershock mod

### PR DESCRIPTION
**Pull request by Rail-Runner**
#### Summary

```SUMMARY: Content "Re-enable Internal Furnace CBM spawn in Aftershock mod"```
#### Purpose of change

Prevent Internal Furnace CBM from being completely removed, instead moving it to Aftershock mod. For now, I only moved CBM item spawns, so as to avoid breaking existing saves. CBM item entry and bionic entry could be moved later at some point, once enough time passes.
#### Describe the solution

JSON editing.
#### Describe alternatives you've considered

Moving it to Bright Nights mod instead.
#### Additional context

None.

### CODE REVIEW

**Comment by Ilysen** [comment]
Thank you! I f you want to put it in Bright Nights, too, the two mods aren't compatible in the first place, so it wouldn't cause any awful harm in doing so.

**Comment by Rail-Runner** [comment]
> Thank you! I f you want to put it in Bright Nights, too, the two mods aren't compatible in the first place, so it wouldn't cause any awful harm in doing so.

I think it might be a good idea to make them compatible at some point. Just gonna check what conflicts.

**Comment by anothersimulacrum** [comment]
They both define the solar panels CBM, which makes them incompatible
If you want to make them compatible, I'd recommend just removing that from Bright Nights because the maintainer is not active anymore.

**Comment by Night-Pryanik** [comment]
I propose even merging these two mods into one because as far as I'm concerned they have similar "the more sci-fi, the more fun" theme.

**Comment by Ilysen** [comment]
Right now, Bright Nights' motif (as far as I can tell) is "much more futuristic Cataclysm", with stuff like civilian nuclear reactors; Aftershock's is "more of the same game, but things that aren't necessarily sensible.", with stuff like strange bionics and unique professions that are fun but unrealistic. I like having them separate as-is, but making them compatible would also be a great thing to do.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/tips-tricks-and-newb-questions-reborn/16870/737

**Pull request merged**
