### PR TITLE
New enchantment value: `AVOID_FRIENDRY_FIRE`

### PR DESCRIPTION
**Pull request by lispcoc**
#### Summary
None

#### Purpose of change
This game manages the line of fire on a tile-by-tile basis, making it easy for friendly fire to occur.
I think that adding CBM and mutations that avoid friendly fire can motivate players to take on challenges.

#### Describe the solution
Add new enchantment value: `AVOID_FRIENDRY_FIRE`. Setting it to 0.5 gives half a chance to avoid friendly fire, and setting it to 1.0 allows the character to attack enemies beyond their allies without causing friendly fire.

#### Describe alternatives you've considered
I think it would be better to introduce actual use cases along with the features, but I wasn't sure which section (or MOD) would be appropriate to introduce them.

#### Testing
I made the following items and equipped them to characters, and confirmed that friendly fire would not occur even if allies were in the line of fire.

```json
  {
    "type": "TOOL_ARMOR",
    "id": "test_ring_avoid_friendly_fire",
    "weight": "4 g",
    "volume": "1 ml",
    "price": 5000,
    "material": [ "copper" ],
    "symbol": "[",
    "color": "light_red",
    "sided": true,
    "warmth": 0,
    "flags": [ "WATER_FRIENDLY", "ALLOWS_NATURAL_ATTACKS", "FANCY", "ONLY_ONE", "SKINTIGHT" ],
    "name": { "str": "ring of avoid friendy fire", "str_pl": "rings of avoid friendy fire" },
    "description": "A copper ring that makes you a little stronger when you wear it.",
    "relic_data": {
      "passive_effects": [ { "has": "WORN", "condition": "ALWAYS", "values": [ { "value": "AVOID_FRIENDRY_FIRE", "add": 1 } ] } ]
    },
    "armor": [ { "coverage": 0, "covers": [ "hand_l", "hand_r" ] } ]
  }
```

### CODE REVIEW

**Comment by MNG-cataclysm** [comment]
This could be used with gun proficiencies to represent high levels of skilled marksmanship regarding precision aiming. Can proficiencies give enchantments, come to think of it?

**Comment by lispcoc** [comment]
I don't think there is any proficiency regarding guns at the moment, but I think you can set the value with Math like other enchantments.
​
"values": [ { "value": "AVOID_FRIENDRY_FIRE", "add": { "math": [ "u_proficiency('prof_marksmanship', 'format': 'percent') / 100" ] } } ] } ]

**Comment by Maleclypse** [comment]
In Xedra Evolved Mad genius could make a gunmod or a specific gun that does so and Eater could have a spell that grants an effect to “curve bullets”. Especially if I could use the value in math so it levels with the character and becomes more likely to avoid friendly fire.

**Comment by Standing-Storm** [comment]
This would be perfect to add to the Clairsentient power Marksman's Eye--firing where the psion knows the enemy will be and there allies will not be.

**Pull request merged**
