### PR TITLE
Display actual dodge skill after encumbrance penalties.

### PR DESCRIPTION
**Pull request by OzoneH3**

### CODE REVIEW

**Comment by DracoGriffin** [comment]
Is the screenshot supposed to be showing 0,8/2 or 0.8/2 ? If it's supposed to be the same, I believe the [convention](https://en.wikipedia.org/wiki/Decimal_separator) is supposed to be periods for CDDA. Although I guess there could be an option for translation / language settings ?

**Comment by Zireael07** [comment]
> Although I guess there could be an option for translation / language settings ?

I believe such an option already exists and it's just a matter of respecting it.

**Comment by OzoneH3** [comment]
Depending on what locale you are on it will be 0.8. For me its 0,8.

**Comment by AMurkin** [comment]
Skill description should describe the values.

**Pull request merged**
