### PR TITLE
Add human skin and stomachs

### PR DESCRIPTION
**Pull request by Rail-Runner**
Allow harvesting raw skin and stomachs from human corpses and use them in recipes.
Also add missing "BONES" flag to homunculus monster and remove unnecessary plural name forms of some items.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, interesting. And nice, you updated the hide-drying recipe on More Survival Tools too. X3

Only peculiarity I can see is that boiled stomachs invert the size logic, thus boiled large stomachs are the norm whereas boiled stomachs are small boiled stomachs.

Granted, that wasn't your doing since the non-human boiled innards do the same thing. While I can see the likely reasoning behind it, it does make for momentary confusion.

**Comment by Darkyhard** [comment]
Well, I decided to not name "normal-sized" human stomachs as small ones, because they are considered normal for a human body, not small. And normal ones are named as large because they are larger than the usual human stomach. For me it does make sense.

**Comment by chaosvolt** [comment]
Right. The same naming is in place for the stomachs of normal creatures.

In meant the boiled stomachs, both human AND non-human. Stomach: small boiled stomach. Large stomach: boiled stomach.

**Comment by Darkyhard** [comment]
Fixed it.

**Comment by chaosvolt** [comment]
Nice. One thing I realized. How many, if any, of the humanlike creatures are big enough to have huge guts to ripe and tear?

**Comment by Rivet-the-Zombie** [comment]
Hulks are huge! That means they have huge guts!

RIP AND TEAR THEIR HUGE GUTS!

**Comment by chaosvolt** [comment]
Clearly this game needs a berserk pack.

**Pull request merged**
