### PR TITLE
minor copy edits

### PR DESCRIPTION
**Pull request by Jerimee**
#### Summary
```SUMMARY: None```

#### Describe the solution
```Copy edits and creation of a handful of new tips. Weight most common swears in swear snippet.```

#### Describe alternatives you've considered
```Submitting copy edits separately from original content.```

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Am I understanding correctly you are duplicating entries to increase their weight?

**Comment by Jerimee** [comment]
Sounds good - should I submit a feature request? (I'm too new to the project and too lousy a programmer to attempt it myself.)

**Comment by Jerimee** [comment]
close PR

**Comment by ZhilkinSerg** [comment]
> 
> 
> Sounds good - should I submit a feature request? (I'm too new to the project and too lousy a programmer to attempt it myself.)

You can try adding necessary code yourself or make a feature request.

**Pull request closed without merging**
