### PR TITLE
Add tin as a material and make some "tin" dining items from it.

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

```SUMMARY: Bugfixes "Tin is now a first-class material, and tin items can be disassembled or smelted into tin scrap."```

#### Purpose of change

Despite scrap "tin" being in game and used in recipes, items described as being made from tin (such as a "tin plate") were instead made from aluminium or other metals.

#### Describe the solution

I've added "tin" as a material, and changed at least one set of items described as being made of tin to use it.

A few things to note:

- I've used stats for pure white tin, even though the items survivors encounter are likely to actually be tin-alloys.
- I wasn't sure which "latent heat" the JSON was referring to. I've used the latent heat of vaporization. The latent heat of fusion is much, much lower.
- I've not changed the material of tin cans, as these are either made of tin-plated steel, or contain no tin at all.
- I've set `burn_products` to produce tin scrap, but I'm not 100% sure of the arguments here. I'd appreciate extra checking.
- I wasn't sure of the units used for density. I've used silver as a reference and kinda fudged it.
- I've noticed that my "tin plate" can be immediately disassembled into tin after making this change. I'm not sure if that's a feature or a bug.
- This is my first time making a material, so feedback and corrections muchly appreciated.
- There are almost certainly other tin items in-game that should be changed. I have not done a thorough search for them all.

#### Describe alternatives you've considered

- Adding the ability to activate "tin" items to scrap them.
- Changing the description of tin items to claim they're not really made from tin.
- Removing tin items altogether.
- Being really pedantic and calling the material "pewter" since most tin items will not actually be pure tin.

### CODE REVIEW

**Comment by pjf** [comment]
And I've realised why my "tin pate" can be disassembled into tin scraps.... It's because materials and items can't have the same name. Standby while I fix things up...

**Comment by nexusmrsep** [comment]
Hope you are aware of https://en.wikipedia.org/wiki/Tin_pest

**Comment by pjf** [comment]
I'm very much aware of grey tin and tin pest (and zinc pest!), but I'm not going to be covering those in this PR. :)

**Comment by pjf** [comment]
Merged already? I guess that means I didn't make any unforseen mistakes. Thank you! :)

**Comment by ampersand55** [comment]
WTH. I was just doing the same thing!

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...ampersand55:material_tin?expand=1

**Comment by jbytheway** [comment]
Given that we have a freezing point but no boiling point in the materials properties I'm fairly sure that the `latent_heat` field is intended to be the latent heat of fusion.

**Comment by ampersand55** [comment]
Yes, I believe I have the correct chemical properties in my PR.

The latent heat of fusion for tin is 59 J/g (equivalent to kJ/kg):

https://www.engineeringtoolbox.com/fusion-heat-metals-d_1266.html

Also the specific heat of liquid tin is 0.24.

https://www.engineeringtoolbox.com/liquid-metal-boiling-points-specific-heat-d_1893.html

**Comment by pjf** [comment]
@ampersand55 : You rock! Have opened a PR with your updates figures and assigned you attribution in git! :)

**Pull request merged**
