### PR TITLE
Drinking Hats Mod

### PR DESCRIPTION
**Pull request by Tsunder**
#### Summary

Summary: Mods "Adds a mod that adds craftable drinking hats to the game."

#### Purpose of change

For fun, and for the lazy quaffables enthusiast engineer.

#### Additional context

This has been on the backburner for a while as a personal mod.
The drinking variants of the equipment should be functionally similar to the base hat.
Most are literally just 2 aluminum cans (or equivalent) taped to a hat, while some are a bit bulkier.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
You need to lint your files in the [web linter](http://dev.narc.ro/cataclysm/format.html).

**Comment by Wokko1** [comment]
Why mod though? Drinking hats are not fictional, and can be found irl.

**Comment by Tsunder** [comment]
could not identify cause for recipies.json to fail in build.

**Comment by Night-Pryanik** [comment]
Please, not another content-mod! Either mainline it, or use [Nexusmods](https://www.nexusmods.com/cataclysmdarkdaysahead/mods/) or other repository at your choise!

**Comment by Tsunder** [comment]
ok.

**Comment by Photoloss** [comment]
> Please, not another content-mod! Either mainline it, or use [Nexusmods](https://www.nexusmods.com/cataclysmdarkdaysahead/mods/) or other repository at your choice!

Could you please explain that stance or point me to an explanation? Several content mods ship with the game and unless my browser is malfunctioning the site you linked to does not actually host any of the external mods I *know* exist (aka PK's, Cata++, Secronom). Is the preference for Nexus a recent change?

**Comment by Night-Pryanik** [comment]
We already have A LOT of content-mods in "official" bundle. A lot more than it should be, in my opinion. What's worst, there is absolutely no reason why are there mods shipped with the game. Mods should be split of the game itself and reside in a separate repository.

> the site you linked to does not actually host any of the external mods I know exist (aka PK's, Cata++, Secronom). Is the preference for Nexus a recent change?

We have no official repository for the mods. It's fully up on the mods' authors where they want to place their mods. Nexus is just a convenient platform for such content.

**Pull request closed without merging**
