### PR TITLE
Provide epower hint for engines and alternators

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary

SUMMARY: None

#### Purpose of change

Continuation of #44001

#### Describe the solution

This patch adds hints for alternators and engines which draw power

Adds ENGINE_EPOWER_DRAIN flag and puts it on combustion engines

#### Describe alternatives you've considered

Could also do without the new flag and just look up whether part
has ENGINE flag and negative epower - but it's just introducing
unexpected magic

#### Testing

Browse alternators and engines in vehicle UI, engines which use up
power (except electric motors) should show a hint on how much
they draw (if they draw), alternators should show their value as well

#### Additional context

There is a minor problem with 1 cylinder engines;
they don't seem to use any epower at all, but 2 of them have
a possible faulty (electric) starter motor and the other one isn't
used in game at all, all vehicles with 2 engines that do get used
also have alternators, afaik most gasoline engines including
small ones for leafblowers have sparkplugs.

I suggest (included in patch) adding a small amount of epower use
for the 1-cylinder engines.

image

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
The lack of epower use is intentional to represent engines that have a pull or kick start and do not require a battery. These engines have a built-in dynamo to create the spark instead of drawing it from a battery, so there is no *net* power draw.

If an engine with no power draw has an electric starter fault, that's a bug.

**Comment by irwiss** [comment]
Set epower back to 0 and removed starter motor faults from the 1cylinder things

Medium steam engine still has 20W power draw, not sure if that's a bug or intended

**Comment by kevingranade** [comment]
> Could also do without the new flag and just look up whether part
has ENGINE flag and negative epower - but it's just introducing
unexpected magic

This is less unexpected magic and more basing the messaging on the reality?
Does it ever make sense to have a negative EPOWER and the ENGINE flag and not have this flag? If not, it's entirely redundant and a potential source of bugs.  If you really like having the flag internally, we could set it when loading the vehicle part instead of specifying the same thing twice in json.

**Comment by irwiss** [comment]
I'm not sure why I convinced myself engine flag and negative epower wasn't
enough but i was so convinced I did a lot of extra useless stuff, whoops :(

Anyway, I've redone the function a bit, also moved 2 flags to json side and
added tests to verify them

**Comment by esotericist** [comment]
why are you doing stuff related to doors and belts in a PR about displaying power requirements?

**Pull request closed without merging**
