### PR TITLE
Resurrecting the nether monster corpse

### PR DESCRIPTION
**Pull request by FarkasKBence**
#### Summary

Content "Improved nether monster corpse"

#### Purpose of change

Second attempt at fixing nether monster generation.
Code from #54155, #63611, and #64421 but with minor tweaks.

#### Describe the solution

* re-added furniture, terrain, maps, effects, field types, monsters, and other content from #63611 and #54155
* merged maps, unified overmap terrain definitions
* fixed uncalled EOC line
* mapgen tweaks from #64421
* improved nether monster generation:
  * merged generation steps and removed unneeded connections
  * added a decapitated variant in case there's not enough room for the head
  * added an initial spawn requirement
  * slightly less unpredictable tentacles

#### Describe alternatives you've considered

Not being a JSON vulture.

#### Testing

Debug-spawned in the world. I also looked at naturally-spawning ones. Let the game
Ran two tests locally.

#### Additional context

Old-style generation to the left, new-style generation to the right.  The result is the the same, but with less steps and connections.
kép

### CODE REVIEW

**Comment by LovamKicsiGazsii** [comment]
Didn't expect that to work. Amazing.

**Comment by fairyarmadillo** [comment]
This PR appears to be causing other PRs to fail tests: https://github.com/CleverRaven/Cataclysm-DDA/pull/65398

The failed Clang 14 test, which was passing before, is now showing a bunch of errors from the nether monster corpse.

**Comment by LovamKicsiGazsii** [comment]
I wonder why tests error only after merging.

All checks have passed for this PR.
Two separate local tests didn't throw any errors.
No errors in-game after 10+ minutes of continuous fast-scrolling through the map.

**Comment by fairyarmadillo** [comment]
@LovamKicsiGazsii I was able to get my PR to pass the same test simply by closing and reopening it, and after some changes it has passed again, so it's possible the test failure was a one-off.

**Comment by bombasticSlacks** [comment]
Yeah no problems on other PRs either.

**Comment by fairyarmadillo** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/65459

This is failing tests again, and the tests show something related to fakespecial_s_gas, which I believe is from this PR. Can anyone make sense of it?

**Pull request merged**
