### PR TITLE
Remove 2D overloads for sounds

### PR DESCRIPTION
**Pull request by Coolthulhu**
EDIT: Includes #12372

Just a cleaup, so that correct z-coords will always be used for sound instead of substituting `g->get_levz()`.

### CODE REVIEW

**Comment by CIB** [comment]
>_> You're not going to stop sending merge conflicts, are you? :P I'd better get my stuff merged soon..

**Comment by Coolthulhu** [comment]
If you want less merge conflicts, don't use 2D functions. 2D functions (especially in `map` class) are being genocided.

**Comment by CIB** [comment]
@Coolthulhu Unfortunately I'm changing the parameters of functions that are 2d and even if I converted them to 3d there'd be merge conflicts. Are you done with sounds::sound?

**Comment by Coolthulhu** [comment]
Done with sounds for now, I just wanted to remove the 2D overloads.

**Pull request merged**
