### PR TITLE
Add Fledgeling Bion to bionic_professions.json

### PR DESCRIPTION
**Pull request by mooshthedouche**
#### Summary

SUMMARY: Content "Added Fledgeling Bion profession to the bionic_professions.json"

#### Purpose of change

I like bionic professions, but I didn't see any that let your character only start with the bare bones, so to speak- allowing them to better customize later game builds once they reach that point. Decided to make this as a first PR and github project in general since it seemed relatively simple.

#### Describe the solution

Added the Fledgeling Bion profession, which starts with a Mk II power supply and a battery system, but NOT any other bionics. 

#### Describe alternatives you've considered

Though theoretically, one could remove bionics they didn't like later on, I didn't really see a point in spending extra points at character creation for a bionic I would remove either way. 

#### Testing

I've gone over the json several times to make sure it looks decent formatting wise, but since I'm new to this whole thing in general there may be some errors that I missed. I've also tested the profession in-game, and it seems to work well.

#### Additional context

First PR ;-;

EDIT: clarified they started with a battery system, oops

### CODE REVIEW

**Comment by DrPariah** [comment]
Nice! I'd recommend that they start with one extra bionic, a method to charge their power supply like the Cable Charger or the Battery System. That way they're set up properly when they start to get other bionics.

**Comment by mooshthedouche** [comment]
> Nice! I'd recommend that they start with one extra bionic, a method to charge their power supply like the Cable Charger or the Battery System. That way they're set up properly when they start to get other bionics.

they do have a battery system! I must not have worded it well in the original summary.

**Comment by DrPariah** [comment]
> > Nice! I'd recommend that they start with one extra bionic, a method to charge their power supply like the Cable Charger or the Battery System. That way they're set up properly when they start to get other bionics.
> 
> they do have a battery system! I must not have worded it well in the original summary.

*rereads* Ah, ok, that's my fault. Reading is FUNdamental, and reading while barely awake doubly so.

**Comment by kevingranade** [comment]
Starting characters with bionics installed are going to be moving out of mainline at some point relatively soon, so I'm not seeing a great case for expanding them still more in the interim.

**Pull request closed without merging**
