### PR TITLE
Fix the Dark Sight spell

### PR DESCRIPTION
**Pull request by CSHague**
Both difficulty and max level of the Dark Sight spell were originally set to zero. This made it impossible to raise the level of Dark Sight. Justifying the value chosen for difficulty by the clairvoyance spell, which gives you instantaneous 1 turn vision on all tiles in the aoe based on level. Clairvoyance has difficulty 4. Whereas Dark Sight gives encumbrance-free light amp vision for the same amount of time as a magical light spell. Compared to the Magical Lamp spell which generates regular light at difficulty 2, for the same amount of time. Comparing the distance you gain in vision from light amp, difficulty 6 seems justified. 

Added some mana cost to the dark sight spell to make it equal to magical light. 

#### Summary
SUMMARY: Balance "Fix the Dark Sight spell"

#### Purpose of change
Noticed while mucking around that Dark Sight had zero difficulty compared to a spell that was more expensive that merely gave you a magical night light for the same period of time. Moving on, it was made clear that the dark sight spell had an unlisted max level value which defaults to zero making it impossible to level .

#### Describe the solution
Change the difficulty  to a value greater than zero. Set max level to 20. Add 100 mana to mana cost.  

#### Describe alternatives you've considered
Difficulty 4 or 5 would be fine too but 6 seemed more appropriate given that the tech solution is cheaper but encumbers you while the magical version has no encumbrance at all.

#### Testing

Spell trains properly now. Takes longer to learn but not too long.

#### Additional context
Durations still feel a little short but that's still in-question.

### CODE REVIEW

**Comment by KorGgenT** [comment]
you appear to also be changing the duration increment for dark sight and magical lamp. i also happened to notice that dark sight doesn't appear to have a max level defined for it.

**Comment by CSHague** [comment]
Did I leave that in there? I thought I reverted that change. That was supposed to be a separate branch. The durations didn't match max level by ratio like the other spells did. It says max duration is ten times the starting duration but at level 20, max, you can only get about half that.

**Comment by CSHague** [comment]
Okay, I reverted that. This does bring up a question: The min duration and max duration on these spells don't match the rate at which the spell levels. I can't be certain what the original intent was other than basing it on the idea that they wanted the spells to be proportional and the durations on the light/sight spells were an oversight. I can't just assume this and change it without any feedback. 

You'd need to change the level increment to 45,000 (my original number was off by a factor of 10) to match the max duration (1,000,000) listed in several spells. This doesn't seem right either. Perhaps the maximum level on the lamp and magical light spells should be removed or set higher? That way the player could potentially strive for that 10000 second magical light but it would take a really long time.

**Comment by KorGgenT** [comment]
I would say that the scope of this PR is trying to fix obvious problems with Dark Sight. So the other issue i see is that it has a max level of 0, meaning the increments don't do anything at all, regardless of the original intent.

**Pull request merged**
