### PR TITLE
Switch to VecTerminus font

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Interface "Switch to VecTerminus font"

#### Purpose of change
Due to some technical issues with FreeType font format and FreeType library, the Terminus TTF font shipped in game cannot be rendered correctly (#50149).

#### Describe the solution
[VecTerminus OpenType font](https://github.com/tisimst/vecterminus) can be rendered correctly with new FreeType library, is also licensed under SIL Open Font License, and has similar appearance to Terminus font.

Distribute VecTerminus OTF font instead of Terminus TTF font to avoid the technical problems.

#### Describe alternatives you've considered
N/A

#### Testing
Windows:

image

Mac:

image

### CODE REVIEW

**Comment by dseguin** [comment]
This is how VecTerminus looks on Linux (Ubuntu 20.04):
Screenshot from 2021-10-01 13-20-35

**Comment by BrettDong** [comment]
> This is how VecTerminus looks on Linux (Ubuntu 20.04):
> 
> Screenshot from 2021-10-01 13-20-35
> 
> 
> 
> 

Is it really Terminus? Looks like fallback Unifont.

**Comment by dseguin** [comment]
I'm not sure, that is the out-of-the box look after building 2fe4cabe082b2c8f3eed7b3e801a878a55490306

**Comment by BrettDong** [comment]
> I'm not sure, that is the out-of-the box look after building 2fe4cabe082b2c8f3eed7b3e801a878a55490306

You may need to delete `config/fonts.json` to reset font settings.

**Comment by dseguin** [comment]
You're right, my mistake. Here's the actual font:
Screenshot from 2021-10-01 13-42-49

**Comment by morthein** [comment]
I went ahead and installed the game in a brand new directory and it shows up just fine.

**Pull request merged**
