### PR TITLE
Cloning vats now stop spoiling

### LINKED ISSUE #32568: Lab cloning vats do not preserve contents
# Describe the bug

The cloning vats found in labs do not preserve their contents. Due to that, the mutated body parts inside will rot away before most players enter laboratories. The only exemption to this are cold labs.

# Expected behavior

Post-cataclysm labs still provide power to the vast majority of their systems, like containment, autodocs, centrifuges, nano labs and so on.
IMO it would make sense that cloning vats preserved their contents, as they'd still be powered like the rest of all systems.

# Versions and configuration

 - OS: Win 10 x64
 - Game Version: 0.D-5805-g50eb478
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs, no fungal monsters

### PR DESCRIPTION
**Pull request by Kelenius**
#### Summary

SUMMARY: Features "Cloning vats now stop spoiling"

#### Purpose of change

First, it makes sense. They're sealed shut and sterile, their contents shouldn't spoil after a couple days. Second, it makes mutated body parts inside actually usable for eating or mutagen making - currently by the time you get to the point where you can use them, it's too late. With this change, you'd be able to extract them when you need them.

#### Describe the solution

I created a `NO_SPOIL` tag for the terrain that stops spoiling.

#### Describe alternatives you've considered

I could hardcode the vats instead of making a tag, but that seems like a bad idea.

#### Testing

Placed two spawned chunks of mutated meat, one in the vat, one next to it, and waited a few hours.

#### Additional context

image

Resolves #32568 - I didn't realize there was already an issue about it when creating this

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> I can see it providing extended preservation but not indefinite. If nothing else the environment is probably sterile and you will not have rot until bacteria can work their way in around seals.

Quoting that issue.
It should slow it, not stop it.

**Comment by actual-nh** [comment]
> > I can see it providing extended preservation but not indefinite. If nothing else the environment is probably sterile and you will not have rot until bacteria can work their way in around seals.
> 
> Quoting that issue.
> It should slow it, not stop it.

A half-life makes sense - after X months, there's a 50% chance that the contents would spoil. (Do note that the labs these are in have at least some power to keep things like UV lights working. OTOH, filters would eventually clog.)

**Comment by Kelenius** [comment]
> Quoting that issue.
It should slow it, not stop it.

It would be trivial to change spoil rate from 0 to 0.001 or something like that, but I think that's not the way to go about it. This is still a hermetically sealed sterile container. It's going to stop the spoilage completely, until it breaks down - which isn't specific to cloning vats. Having terrain and furniture slowly rot, break down, and collapse, as in-game time passes would be a cool feature, but it's _wildly_ outside of scope.

**Comment by PatrikLundell** [comment]
I would expect a cloning vat to actually keep whatever is inside it alive as long as the vat is supplied with power and nutrients. Eventually (after many years) old age effects would set in, but I'd expect few characters or even worlds would be played for long enough for that to become an issue (although starting 100 years after the cataclysm would), so it can probably be ignored until someone decides to make a "long time after the cataclysm" update that incorporates building and item decay.

If something that's not alive is kept sterile it will still break down chemically over time, although the decay is a lot slower than when biological agents get a chance to work in it (like food in a freezer). In that case a slowed spoil rate is a reasonable implementation.

**Pull request merged**
