### PR TITLE
Use text snippets for tutorial messages

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Use text snippets for tutorial messages

#### Describe the solution

Rework tutorial messages to use text snippets infrastructure.

#### Testing

Try finishing a tutorial and make sure all text message are correct.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
I guess we need to separate tutorial messages for tiles and curses builds. All these "@ symbol is you" or "brown + next to you" could confuse new players and/or are useless when player is using tileset.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I guess we need to separate tutorial messages for tiles and curses builds. All these "@ symbol is you" or "brown + next to you" could confuse new players and/or are useless when player is using tileset.

Yeah, tutorial definitely needs a rework.

**Comment by codemime** [comment]
This distinction can't be bound solely to builds. Tiles builds feature console glyphs too.

**Comment by ZhilkinSerg** [comment]
> 
> 
> This distinction can't be bound solely to builds. Tiles builds feature console glyphs too.

Yes, texts should be either more generic or we can use different texts depending on state of tiles.

**Comment by Qrox** [comment]
We can draw highlight on the relevant tiles and change the texts to refer to the highlight instead.

**Pull request merged**
