### PR TITLE
More US Bank Notes

### PR DESCRIPTION
**Pull request by JacobKernFord**
#### Summary
Content "Add more US notes"

#### Purpose of change
Adds US dollar notes that were absent from the game, specifically five, fifty, and hundred dollar bills. Also adds them to the drop tables for wallets and relocates the definitions for all of the dollar bills from generic.json to fluff.json in order to keep them consistent with the existing definitions for the US coins.

#### Describe the solution
Adds definitions for more types of dollar bills, adds them to the wallet tables, and moves the existing dollar bill definitions to fluff.json with the coin definitions.

Moved definitions of "money_one", "money_ten", and "money_twenty" from generic.json to fluff.json to be consistent with where the US coins are defined.

Added "money_five", "money_fifty", and "money_hundred" to fluff.json to add the other US dollar notes to the game.

Edited wallet.json to include probabilities for every type of dollar to spawn in every wallet (except the duct tape wallet) including the newly added ones.

#### Describe alternatives you've considered

None, this is just adding stuff to the game.

#### Testing

I've run all files through [the linter](https://dev.narc.ro/cataclysm/format.html) and checked for the correct style.

### CODE REVIEW

**Comment by actual-nh** [comment]
This will (unfortunately) need String Freeze, as far as I can tell.

**Comment by JimboSpicy** [comment]
> 
> 
> > > This will (unfortunately) need String Freeze, as far as I can tell.
> > 
> > 
> > What do you mean by String Freeze?
> 
> It means that there are some strings that will need translation, and stuff going into 0.F can't have new ones, to give the translators time to keep up. The tag '0.F String Freeze' will signal that, first, it shouldn't be considered stale by the bot; and, second, that it should go into 0.F-dev (which will become master after 0.F is out), not into master.

Thank you for the clarification. I thought it was in reference to the failed check.

**Comment by BrettDong** [comment]
There are some errors in https://github.com/CleverRaven/Cataclysm-DDA/pull/48298/checks?check_run_id=2241583058 test, for example,
> item money_five does not fit in container wallet_stylish when spawning item group wallet_stylish_full.  This can be resolved either by changing the container or contents to ensure that they fit, or by specifying an overflow behaviour via "on_overflow" on the item group.

**Comment by Maleclypse** [comment]
Please open a new PR for this targeting the experimental branch.  Was closed as a side effect of deleting the 0.F -dev branch

**Comment by ZhilkinSerg** [comment]
This needs to be rebased on top of current master. Also it was kinda superseeded by #51077, so I'm closing current PR to clean up PR queue. Feel free to open new PR if more changes are necessary for bank notes.

**Pull request closed without merging**
