### PR TITLE
Add choose your own adventure style portal storm dungeon rewards

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Part of #58887
More flavor plus mechanics to flesh out portal storm dungeons.

#### Describe the solution
Add ability for effects to have enchantments.
Add large amount of json for branching dialog.
Instead of just getting a reward when you leave a portal storm dungeon, add a new pseudo dialog style event to decide what happens.  You can make a number of choices which lead to different outcomes.  
Right now there is a decision tree that leads you to either a good or a bad outcome with a random element.  The numbers aren't set but the idea is that different outcomes have different risk versus reward elements.  So outcome A might be 90% chance reward level 1 10% chance punishment level 1 and B might be 30% chance level 3 reward 70% chance level 1 punishment.  
Rewards and punishments are just effects right now but more will be added.  More single use items are planned.  

#### Describe alternatives you've considered
Something less verbose

#### Testing
Run EOC_PORTAL_STORM_DUNGEON_CONVERSATION using debug commands.

#### Additional context
This is still in progress. The basic framework is here, look at TALK_NETHER_CROSSROADS.json to see the idea.  The other new json files are less fleshed out and may or may not ever be fully fleshed out.  Still need to add lots more rewards and punishments as well.

### CODE REVIEW

**Comment by Amoebka** [comment]
So you can finish a challenging dungeon and get a negative effect as your reward because the slot machine said so? This is pretty much just gambling without any skill involved, you just choose how much you bet.

**Comment by Ramza13** [comment]
> 

Not quite, the eventual goal is that this happens several times while you are going through the dungeon and its weighted to the side of positive.  Still that's a good criticism and I do need to make sure this doesn't just screw the player over.

**Comment by anoobindisguise** [comment]
What do the simpler ones do? Like TALK_NETHER_SCHOOL or TALK_NETHER_MIRRORS. Do I physically get taller from looking in the funhouse mirror?

**Comment by Ramza13** [comment]
> What do the simpler ones do? Like TALK_NETHER_SCHOOL or TALK_NETHER_MIRRORS. Do I physically get taller from looking in the funhouse mirror?

Right now nothing, although thats a great idea.  Those are scafolding for ideas I may flesh out later.  I'm sorta going about this in whatever order suits my mood,  I'm about to implement a bunch of the c++ and rewards stuff in this branch right now for example, which makes it easier to work on the ideas here as they get smaller and smaller the more pieces I finish.

**Pull request closed without merging**
