### PR TITLE
Fix incorrect recipes

### PR DESCRIPTION
**Pull request by mugling**
Noticed whilst testing #17431

### CODE REVIEW

**Comment by Coolthulhu** [comment]
What about mods?

**Comment by mugling** [comment]
@Coolthulhu many are not in good shape. feel free to pull #17431 and experiment now that I have the syntax worked out for the parser rules.

**Comment by Coolthulhu** [comment]
But is their shape all "FUBAR, will need 10 PRs to unfuck, 3000 lines of horrible" or "kinda bad, 100 bad lines"?

**Comment by mugling** [comment]
Probably hundreds not thousands. It's difficult to be certain as I'm still extending the parser to support all of the various fields.

**Pull request merged**
