### PR TITLE
Add tree stumps (forest's table)

### PR DESCRIPTION
**Pull request by nexusmrsep**
Reference: #24878

Credits for the idea goes to @EirenexTheDragon 

This PR adds  **tree stumps**.
Tree stumps are a leftover of cutting down tree. They can be cut further, but the yields are not satisfying as from cutting a log. Yet you might still get some usable wood.

What's more important is that it serves as an **equivalent to other flat furniture needed for butchering** like table, counter, washing machine, dryer, pool table, coffin, and leather tarp.

TODO: stumps should appear by themselves in map generator, as trees fall down with age, leaving stumps behind, and active pre-cataclysm forest cultivation could leave some behind.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Please correct me if there is any mis-information, but tree stump objects already appear in the experimental build to substitute entire masses of cut down-trees (spawning multiple tree stumps in the path of where the tree is fell) which are then broken down into log objects etcetera with a axe.

Would you be putting in any more work to improve & expand on this inconsistency in line with your design vision to make a more realistic if not a little more comprehensive?

* Removing a single stumps from the ground with a shovel for instance.

**Comment by Mecares** [comment]
Could you give boulders the ability to be used as flat surface for butchering?

**Comment by sfsworms** [comment]
Boulders aren't really flat though. At this point, it'd be better to consider if the flat surface requirement is really needed (why not simply on the ground?) or maybe allow ground butchery, but gives a bonus to yield if a flat surface is available (less meat getting dirty in the process. )

**Comment by nexusmrsep** [comment]
@boydkr  this might be in fact valid, but until we sort out the feedback for butchery and finally decide the road to go, this is a valid option, and besides, tree stumps were not there, so it'd be nice to have them anyway.

**Pull request merged**
