### PR TITLE
Added LivePeople tileset

### PR DESCRIPTION
**Pull request by rainbowjose**
#### Summary
SUMMARY: Content "Adds LivePeople Tileset."

#### Describe the solution
Just enable tileset as usual, also  you can enable custom indicators through mods. I recommend "hybrid".

#### Purpose of change
For the better game experience.

#### Additional context
Based on this discussion:
#26676

Original author's repo:
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

### CODE REVIEW

**Comment by Rod995** [comment]
You there!
That's a bit too much PR making....

**Comment by rainbowjose** [comment]
> You there!
> That's a bit too much PR making....

I trying to deal with this fucking regexp.

05:30:44 Invalid Summary line, please provide a summary similar to the following:
05:30:44 SUMMARY: Features "Added ability to fly."
05:30:44 Makefile:1081: recipe for target 'validate-pr' failed
05:30:44 make: *** [validate-pr] Error 1
05:30:44 make: *** Waiting for unfinished jobs....
05:30:52 Build step 'Conditional step (single)' marked build as failure

**Comment by Rod995** [comment]
Hmmst.
By the way, you don't have to redo the entire thing each time.
Just edit that comment and then add another one saying

`jenkins rebuild`

At least, for that summary.
For other edits, you should just push more commits.

**Comment by Rod995** [comment]
jenkins rebuild

**Comment by rainbowjose** [comment]
Meh.

`Makefile:1060: recipe for target 'data/mods/LivePeople_Hybrid/mod_tileset.json' failed`

This http://dev.narc.ro/cataclysm/format.html thing cant help.

**Comment by AMurkin** [comment]
Formatted `data/mods/LivePeople_Hybrid/mod_tileset.json`:
```js
[
  {
    "type": "mod_tileset",
    "compatibility": [ "MSX++LIVE_PEOPLE" ],
    "tiles-new": [
      {
        "file": "Hybrid_Items.png",
        "tiles": [
          { "id": "highlight_item", "fg": 0 },
          { "id": "footstep", "fg": 1 },
          { "id": "cursor", "fg": 2 },
          { "id": "animation_hit", "fg": 3 }
        ]
      }
    ]
  }
]

```
No tabs, proper indents, no empty line.

**Comment by AMurkin** [comment]
I propose you to watch this: https://www.youtube.com/watch?v=A-Cll9jEnnM
And related resources.

**Comment by rainbowjose** [comment]
> Formatted `data/mods/LivePeople_Hybrid/mod_tileset.json`:
> 
> ```js
> [
>   {
>     "type": "mod_tileset",
>     "compatibility": [ "MSX++LIVE_PEOPLE" ],
>     "tiles-new": [
>       {
>         "file": "Hybrid_Items.png",
>         "tiles": [
>           { "id": "highlight_item", "fg": 0 },
>           { "id": "footstep", "fg": 1 },
>           { "id": "cursor", "fg": 2 },
>           { "id": "animation_hit", "fg": 3 }
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> No tabs, proper indents, no empty line.

09:06:26 Makefile:1060: recipe for target 'data/mods/LivePeople_Hybrid/mod_tileset.json' failed
09:06:26 make: *** [data/mods/LivePeople_Hybrid/mod_tileset.json] Error 1

Still not working.

**Comment by rainbowjose** [comment]
> Formatted `data/mods/LivePeople_Hybrid/mod_tileset.json`:
> 
> ```js
> [
>   {
>     "type": "mod_tileset",
>     "compatibility": [ "MSX++LIVE_PEOPLE" ],
>     "tiles-new": [
>       {
>         "file": "Hybrid_Items.png",
>         "tiles": [
>           { "id": "highlight_item", "fg": 0 },
>           { "id": "footstep", "fg": 1 },
>           { "id": "cursor", "fg": 2 },
>           { "id": "animation_hit", "fg": 3 }
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> No tabs, proper indents, no empty line.

Still got this error:
Formatted data/mods/LivePeople_Chesthole/mod_tileset.json
make: *** [data/mods/LivePeople_Chesthole/mod_tileset.json] Error 1

**Comment by AMurkin** [comment]
Your current version:
image
You need to fix it locally, create a commit and push (sync) to your origin repository.

**Comment by rainbowjose** [comment]
> Your current version:
> image
> You need to fix it locally, create a commit and push (sync) to your origin repository.

Okay. Thank you.

**Pull request closed without merging**
