### PR TITLE
Rebalance vehicle part durability

### PR DESCRIPTION
**Pull request by KurzedMetal**
#### Summary
SUMMARY: Balance "Rebalance vehicle part durability to have consistency when comparing different parts."

#### Purpose of change
I opened #34880 a while ago, explaining there are some outlier parts that have way too much durability. In this PR I'll try to give most common hull parts a reasonable durability compared to similar parts.

I'm not an expert on the subject, so if you think anything is off, just politely explain why and I'll make tweaks.

Rules I applied to come up with these numbers:
* Normal Steel Frame = 50 resist, 400 durability (as it is in the repo right now)
* Heavy duty frame = 112 resist (current in repo), Frame's durability + 25% = 500 (760 in repo right now, @mlangsdorf suggested on discord that Heavy Duty parts should have around 20% more durability).
* The rest of the parts are given values relative to frames, assuming the follow durability from strongest to weakest: Frames > Boards = Roof = Aisle > Hatch Door > Shutter > Trunk Door > Doors = Sliding Door > Cargo Hatch > Stow Board
* I based that order depending if they had mobile parts, mechanisms, windows, or if they are trading a sturdy design for space for storage (that's why hatch/stowboard are at the end).

#### Describe the solution
I tweaked most common part durability and resistance values to match the relative durability I listed, these are the values I used (some notes I was taking when doing the changes):

```
opaque version: x1.1 durability and a small resistance bonus (due to no window)
heavy duty version: x1.25 durability and about x3 more resistances (as currently in repo)


frame (normal / heavy):
    dur: 400
    res: 52 / 112

board:
    dur: 300
    res: 33 / 90
    reasoning: highest durability and resistances due to having no mobile/mechanic parts and very sturdy design (space is used mostly for durability).

quarterpanels: same as board with x0.8 durability

roof: 
    dur: 300
    res: 33 / 90
    reasoning: highest durability and resistances due to having no mobile/mechanic parts and very sturdy design.

aisle (also "aisle with lights"):
    dur: 300
    res: 33
    reasoning: highest durability and resistances due to having no mobile/mechanic parts and very sturdy design.

opaque hatch door:
    dur: 265
    res: 20 / 40
    reasoning: more durable than doors, no mechanisms, have small window
    
hatch door: 
    dur: 255
    res: 25 / 75
    reasoning: more durable than doors, no mechanisms, have small window

shutter:
    dur: 245
    res: 25 / 75
    cap: 37L
    reasoning: more durable than doors

trunk door:
    dur: 230
    res: 25 / 75
    reasoning: a bit more durable than doors, sturdy design, few mobile parts, no window

door (also sliding door):
    dur: 215
    res: 20 / 60
    reasoning: less durable than boards, sturdy design, few mobile parts, have mechanisms, have window

cargo hatch (no heavy duty version):
    dur: 165
    res: 20
    cap: 37L
    reasoning: less durable than doors, weaker design due to space efficiency, few mobile parts, some mechanisms, have huge window

stow board:
    dur: 150
    res: 25 / 75
    cap: 62L
    reasoning: less durable than doors, very weak design due to space efficiency, few mobile parts, no mechanisms
```

#### Alternatives you have considered
I was tempted to reduce the Heavy Duty resistances (flat damage reduction) too, feels like current values makes them impossible to be  damaged, but since I don't have anything to back that up, I desisted. If anyone have any opinion about this, I'd love to hear it.

I didn't touch platings either, some have ~500-600 durability, but at least they are designed for that, values didn't seem that off. If you think those need some tweaking too, I'd like to know, I have no clue how much resistant those things are supposed to be.

Another thing that came up on discord while talking about this was that some recipes use either frame / hdframe or metal sheet / steel plate but neither fits into them, they need their own (more complex recipes). For example Doors (why an HD Door would be made up of a Heavy Duty Frame?), due to these incosistencies, there are also discrepancies between how strong the part is and how much it weights. But that's out of this PR scope, I may open a bug/feature request for that later.

#### Testing
I haven't done much testing yet, but I'd love to hear some feedback.

### CODE REVIEW

**Comment by nphyx** [comment]
What's your reasoning on hatches being weaker than ordinary doors? I'd figure hatch = a smaller opening and more reinforcement, thus sturdier.

**Comment by KurzedMetal** [comment]
The windows are part of the hatch in this game, and the window is bigger.

**Comment by nphyx** [comment]
Are you thinking "hatch" as in "hatchback"? I'm thinking hatch as found on an armored vehicle, tank or submarine. That might be the disconnect. I'm not sure which of us is right, but the only place I can think of having seen hatches in game is on the back of APCs fwiw. 

Which would be something like this: https://www.globalsecurity.org/military/systems/ground/images/m-113_ar-ramadia_040116-a-2995r-022-hr.jpg

It's smaller, sturdier and more heavily enforced than a normal door. Note the hatch rests against a pretty thick jamb on all four sides which would tend to distribute force to the vehicle's frame when impacted.

I'd go with generally putting opaque entrances above transparent entrances too, like -

Board > Frame > Roof > Opaque Hatch > Opaque Door > Shutter > Aisle > Hatch > Sliding Door > Door > Quarterpanel > Stowboard.

Figure a door/hatch with a window is somewhat equivalent to a quarterpanel, but with a window on the top half, so they're just slightly more durable than the quarterpanel thanks to the structural benefit of the window.

I like the idea in general, always thought it was weird that hatches were tougher than frames or boards.

I wonder if the weights of the part items for heavy frames should go down a bit to reflect the general nerf in durability when added to a vehicle.

**Comment by KurzedMetal** [comment]
That makes sense, thanks for the info, English is my second language so I probably confused those terms, thanks. Yeah it makes sense, that kind of door is way stronger.

OTOH, why does that door have 37L storage?

**Comment by SirPendrak** [comment]
Why x5 heavier heavy frames are only 20% more durable?

**Comment by KurzedMetal** [comment]
The weight is completely screwed on all part just because it's based on the weight of its component, which needs an update too. I already mentioned that in my initial post.

**Comment by KurzedMetal** [comment]
I made some changes:

* Added a new "hatch door" to represent a strong door as nphyx pointed in his link image in contrast of a "cargo hatch" like used in the Hatchback vehicle. I renamed and reworked the description to reflect this. The reason was to have a disambiguation, because I think both current vehicles in JSON and players were confusing them, and that's why we ended up with a vehicle part that had the durability of the door in the screenshot and the cargo space of a Hatchback.
* I changed a lot of recipes to use "copy-from" and used the "proportional" field to make it easier to keep it up to date (for example, all heavy duty are x1.25 of the normal version, so if normal version change, there's no need to update HD ones).
* I made some more changes to values based on what we talk with nphyx, also due to the new items I introduced. I updated the info in the OP reflecting the changes.

**Comment by nphyx** [comment]
I thought the hatchback used "trunk door"? Agree in general the terms are unclear.

I like the cleanup using inheritance. Much nicer to read now.

**Pull request closed without merging**
