### PR TITLE
Handless Firing [WIP] [CR]

### LINKED ISSUE #26836: Modify gun firing to look for worn items as valid guns.
**Is your feature request related to a problem? Please describe.**  
I'd like to be able to fire a weapon without wielding it if it's worn.

**Describe the solution you'd like**  
Maybe a tag or something that could let this be done without breaking the game balance too much.
This could probably open up a few more weapon possibilities, like wrist-worn weaponry, or a gun on a glove.

### PR DESCRIPTION
**Pull request by Rod995**
#### Summary
```SUMMARY: Features "Adds the ability to fire tagged weapon without checking if they're wielded."```

#### Purpose of change

```Fixes #26836 and #26970 - Handless firing of worn weapons with tag and compatibility with slung weapons.```

Related Issues:

* #26836
* #26970

#### Describe the solution
It adds a new tag called `HANDLESS` that skips the check for wielded ranged weapons when firing them.
Also includes a check for slung weapons.

#### Describe alternatives you've considered
I dunno, I'll put more here tomorrow when I'm not sleepy.
Maybe a check to see if you can actually lift the slung weapon would be nice too.
Is the check for a sling redundant if it's already worn?
Find out tomorrow, on *Rod Makes Bugs*...

#### Bugs

- [ ] Thingie automatically chooses first `HANDLESS` weapon during the check, it needs to open a menu to select which one to fire.

#### Additional context

Gif TBD

### CODE REVIEW

**Comment by kevingranade** [comment]
You're missing a critical piece of information here, which is what the rationale for firing an un-wielded weapon is.

**Comment by Rail-Runner** [comment]
Could be sort of a shoulder-mounted machine gun, at least as a mod content. Or possibly in mainline, wrist guns, as long as they're worn.

**Comment by Zireael07** [comment]
Are wrist guns a real thing?

**Comment by Rod995** [comment]
@Rail-Runner A neural-interface was the idea in a mod I was working on, yes.
@Zireael07 There's the Sedgley OSS .38 if you want to look at it. It's not a wrist gun but is instead a gun on a glove.

**Pull request closed without merging**
