### PR TITLE
Ranged mi-go

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Added a new mi-go monster with ranged capabilities."```

#### Purpose of change
Add some challenge to late-game players.

#### Describe the solution
Added a new fake gun with a very high damage. Let's presume it is a some sort of a biological gun that is grown right on the mi-go body through the means of genetic engineering. Mi-go is growing "ammo" (which is an unknown solid organic matter) for this gun right in its body and then fires them at incredible speed. Thus it is able to easily penetrate almost all of the game armor save for power armor. All of the mi-go body was genetically enhanced to be a perfect sniper - for example all of its appendages were re-purposed to be a supporting platform for the gun with a built-in organic sway-compensating mechanism. Its night vision was genetically enhanced too, so at night it will see a little farther than its mi-go brethren. It will fire its weapon from a very long distance and all of its shots are almost guaranteed to hit the target.

Made the monster spawn at most usual mi-go spawn places, just postponed it to mid to late game (at least 30 days after default start date).

In general this monster is supposed to pose a very high threat to most players, and fleeing might be a good tactic when one encounters it.

#### Describe alternatives you've considered
Made it drop its weapon on its death, but I think it should be useless once its operator is dead, and no more ammo is grown.

#### Additional context
Scout has a cooldown of 5, so it's almost guaranteed for a melee player to get shot twice before entering the clinch distance. That might be a too harsh, so I'm ready to increase the cooldown.

### CODE REVIEW

**Comment by Necrosian** [comment]
I already feel the annoyance of emerging from evac shelter to be gunned down by these!

It's great!

**Comment by Night-Pryanik** [comment]
> emerging from evac shelter

Only if you were hiding in evac shelter for a month or so.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by RarkGrames** [comment]
Is it possible to make the gun similar to a corpse so it gets rotten? If you are not planning to implement it as a usable weapon, it might have some "fun" factor of rotting away in your car trunk. :laughing:

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by ampersand55** [comment]
I think mi-gos having CBM weapons would be fitting with them being experts in surgery and neuroscience.

**Comment by Nacarbac** [comment]
The Mi-Go of Lovecraft did have weapons - strange lightning guns and cold-mist projectors. Unrechargeable artifacts might be one way to do it? A firestorm mi-go would be quite an experience...

**Comment by paulenka-aleh** [comment]
How is it suppose to fire projectiles in an incredible speed? I doubt it makes use gunpowder or similar exploding agent. Don't think it could grow a railgun either. So it must be pneumatics. Doubt bullet fired using pneumatics could pierce armor

**Comment by Night-Pryanik** [comment]
It's definitely not a gunpowder and it's definitely not a pneumatics. Propellant is specifically stated as totally unknown to player (and all human science in general too).

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by TechyBen** [comment]
Dynamics vs just making an insta death OP enemy?

Have one with ranged, one with melee spawn. OR one with knifes, one with blunt attacks. Then the player has to balance/swap between the two.

But currently, it's just another chicken walker. At least that has mitigations on how to approach it. This, I don't even know what this is suppose to be. XD

PS, constructively, the bombardier beetle uses 2 chemicals to produce explosives. This creature could have 1 or 2 *literal* rockets, with 2 chemical chambers combining by injecting into a nozzle. Give the "rocket" an eye or two, a small brain, and it's now guided. XD

Make it launch effectively a clone of the manhack. Faster, but not as good tracking (as it would run past some moving targets). It could have whatever effects (no need to be explosive, but could be). Like, perhaps an electrocuting (like an Electric eel) rocket propelled squid. It would grab the player, instead of instadeath them. Once grabbed, electrocute the player, to "capture/kill" it that way.

Still scary. But much more dynamic. I'd suggest making it a 1 shot item, or giving a *long* (like a few hours) reload time, to effectively "regrow" another one on the meego (if you want to go that way). But give the meego some retreat options, or alternative attacks/weapons.

**Comment by Night-Pryanik** [comment]
> insta death OP enemy?

It's far from delivering insta-death. I tested it on freshly spawned Joe Average with simple clothes and no armor whatsoever. Joe was able to withstand a dozen of hits before death. Joe was also actively running from the scout, and as I was always saying, you shouldn't try (and more so be able to) to kill every creature in the game. Fleeing is a viable tactic.
Also this mi-go will spawn only after a substantial amount of time after game start, and by this time one could be able to cope with it - either in melee or by a ranged weapon. Especially if it has fewer hit points and worse armor than an ordinary mi-go.

**Comment by TechyBen** [comment]
> > insta death OP enemy?
> 
> It's far from delivering insta-death.

Ah. That makes sense then. The OP was [to summarize] "too easy late game, should be able to get through all armour", so I assumed getting through all armour was instagib. ("perfect sniper" "all armour including Power armour" "incredible speed") :P

I guess the guaranteed hit bit I mixed up with the rest for guaranteed death. XD
I do still prefer dynamics being added over plain old max out the attack stats.

**Comment by Night-Pryanik** [comment]
>I do still prefer dynamics being added over plain old max out the attack stats.

You are welcome to implement your proposals by yourself in some other variation of mi-go or any other monster.

**Comment by TechyBen** [comment]
> > I do still prefer dynamics being added over plain old max out the attack stats.
> 
> You are welcome to implement your proposals by yourself in some other variation of mi-go or any other monster.

Yep. I'd love to do a proper insect one (have penciled in some json edits for Ants) for that exact reason. But was just trying to add some input. You've done a lot of other dynamic stuff (the bases), so it would have been a let down if it had gone straight to OP attacks for no reason from the enemy type.

But I see you are not, I was overreacting (have seen lots of over the top neft/buffs to game betas in the past). :)

**Comment by Night-Pryanik** [comment]
> You've done a lot of other dynamic stuff (the bases)

I believe you've mistaken me for someone else - I haven't add nothing related to the bases.

**Comment by TechyBen** [comment]
> > You've done a lot of other dynamic stuff (the bases)
> 
> I believe you've mistaken me for someone else - I haven't add nothing related to the bases.

My bad. I know the meegos are getting a rework. Was not sure who was doing it.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
I don't know what's happening with gorgon, I believe it isn't related to the PR itself.

**Pull request merged**
