### PR TITLE
Assorted armor tweaks

### PR DESCRIPTION
**Pull request by chaosvolt**
This came about while working on the Medieval Mod, plus other oddities noticed.
1. Retweaked chainmail to use iron instead of steel, but with the same protection
2. Buffed plate armor some via changing it to use steel instead of iron.
3. Mainlined the changes to metal leg guards. Renamed to greaves (item ID retained to avoid breaking stuff), they now use leather as a liner which nerfs their protection some. Also changed the recipe and added them to a few item groups.
4. Tweaked ornamental plate armor to use steel and leather instead of iron, but with identical protection.
5. Buffed barbutes, plate gauntlets, and plate boots to use steel in place of iron. Should be comparable to standard plate armor.
6. Buffed great helms to use steel and leather instead of iron. Should be comparable to the ornamental plate armor.
7. Buffed the o-yoroi and kabuto to 18/18 protection. Same as chainmail and plated leather armor.

You know I could've SWORN I'd added an override recipe for iron greaves in the mod, adding the referenced leather to the components. Oh well, just means I didn't have to remove that recipe after changing it in mainline.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
IRL plate armor is really tough. In game, there is a major difference in required resources between the two. Plate armor is quite useless as a craft even after the buff.
It should be steel, not iron.

**Comment by chaosvolt** [comment]
Hmm. I wasn't sure whether to buff up light plate even farther, or not.

Ornamental plate armor has a whopping 30/30 which sounds more impressive. Should I buff regular plate armor more, nerf ornamental plate, or do both?

If any of them should be steel, it maybe should be the ornamental version, which I think is still iron. Maybe change THAT to steel and give it lower thickness to make it closer to its original value?

**Comment by Coolthulhu** [comment]
Doesn't ornamental have tons of encumbrance too?
Both should be steel.

In any case, leather armor shouldn't protect as well as plate. Not boiled leather, not plated leather.

**Comment by chaosvolt** [comment]
Hmm. Right, make both steel. I'm guessing buff the plate armor more and revert the nerf to chainmail?

**Comment by Coolthulhu** [comment]
Yeah.

If chain is to be nerfed, it should be something more advanced than just dropping the armor values. It should get some sort of a flag that would make it less bash-resistant without losing cut resistance. It would also benefit from cut and pierce being split...

**Comment by chaosvolt** [comment]
Hmm, right. Will unerf then, doing a quick test to see how the material change affects the plate armor.

What about the samurai armor? Maybe should be buffed a bit, closer to chainmail and plated leather I guess?

**Comment by Coolthulhu** [comment]
If we're going by realism, it should stay iron and worse than superior western steel (not folded millions of times, but made from superior materials).

**Comment by chaosvolt** [comment]
Hmm. Well if we're buffing plate armor, then buffing the o-yoroi to 18/18 leaves it inferior to plate armor.

**Comment by chaosvolt** [comment]
Hmm. Hard to get ornamental plate armor back to being 30/30, I'll see if adding leather to the material solves that...

**Comment by chaosvolt** [comment]
Also, amusing idea. Should we give ornamental plate armor the fancy flag? I sure as hell would feel fancy if it was, say, Maximilian armor. XP

**Comment by kevingranade** [comment]
This might be more than you want to look into, if so that's fine...
I was just thinking the point of balance for plate SHOULD be that it's less than complete coverage, but that's problematic as long as we treat it as a "suit" or "boots" etc.  A way that seems like it would work would be for plate to just be the metal bits, provide very good armor but incomplete coverage, and a full suit would also include padding and probably chain, which would have lower protection but full coverage.

**Comment by Rivet-the-Zombie** [comment]
Yeah, give it the flag; it is 'ornamental' armor, after all.

**Comment by chaosvolt** [comment]
Hmm. Sop, fanciness amnd...how to nerf it, I guess reduce coverage some? Lemme see what it's already at, I might only want to reduce it by 5 at the most. As a "suit" it might have some gaps but not many. I'll see...

**Comment by Coolthulhu** [comment]
Now that light plate is lighter, it should have a bit lower (5-10) encumbrance. Not having 100 coverage is a major downside.

**Comment by chaosvolt** [comment]
Ah right. Also of note, plated leather armor likewise still has the same encumbrance as said light plate.

**Comment by chaosvolt** [comment]
While I'm at it, I noticed while messing about with stuff that the lobster helmet effectively does not exist. No item groups seem to reference it. Should I implement it in this PR?

**Comment by Rivet-the-Zombie** [comment]
Go for it. Non-dev items that never spawn are useless, and it's supposed to spawn anyways.

**Comment by chaosvolt** [comment]
Ah, very well then, will add that. As it's kevlar and plastic, I would assume it should be in the same item groups as tactical helms?

**Comment by chaosvolt** [comment]
Hmm. Still pondering the idea of implementing shields in a later Medieval Mod PR. As mod-only content they would at least hopefully be more acceptable in their rather crude state, but even then...unsure.

**Comment by chaosvolt** [comment]
Meep. And thank you for the merge.

**Comment by kevingranade** [comment]
The first thing that needs to go in on the way to shields is adding an
off-hand to the character class.  It's going to be way too hacky any other
way.

**Comment by chaosvolt** [comment]
Ah. Unfortunate, as that's unlikely to be something I could put together that easily. Though if losing the use of both hands have additional gameplay effects, that would be a good first step.

**Pull request merged**
