### PR TITLE
Make butchery refuse useful

### PR DESCRIPTION
**Pull request by Rocket-F-1024**
#### Summary
None
#### Purpose of change
Since butchery refuse still contains a large amount of biomass (including feces), why not use it to make fertilizer?

#### Describe the solution

Rewrite the recipe for producing liquid fertilizer using feces. Now you need to mix a certain amount of feces or slaughter waste with water and ferment for a period of time to obtain liquid fertilizer.
The recipe for producing fertilizers using chemicals remains unchanged.

#### Describe alternatives you've considered

None

#### Testing

It works.

#### Additional context

Idea and date from
https://tieba.baidu.com/p/8963394812
https://www.researchgate.net/publication/280935072_Conversion_of_rural_abattoir_wastes_to_an_organic_fertilizer_and_its_application_in_the_field_cultivation_of_tomato_in_India
https://baijiahao.baidu.com/s?id=1771594213400202210&wfr=spider&for=pc
http://www.fjc001.com/m/fenwuzhili/wufenzhilijishu/59380615412.html

### CODE REVIEW

**Comment by XygenSS** [comment]
Aren't they intended to be useless / only exist to preserve mass?

Besides, if you were to compost bits of gore, hair, chitin, soil, excreta and bones you'd have to do some hardcore processing or actually compost it overtime with a source of carbon.

**Comment by Rocket-F-1024** [comment]
> Aren't they intended to be useless / only exist to preserve mass?
> 
> Besides, if you were to compost bits of gore, hair, chitin, soil, excreta and bones you'd have to do some hardcore processing or actually compost it overtime with a source of carbon.

Nothing is useless, it's just lack of utilization methods. It's unrealistic to assume that something is useless.
In addition, even the original recipe included feces, chitin, and bones, so either completely redesign the recipe or it is reasonable to use butchery refuse instead of feces (or even replace the bones and chitin in the original recipe).

**Comment by RenechCDDA** [comment]
How have you determined the amount, exactly?

Feces can make fertilizer because it's got lots of nitrogen availability. I am not confident the same can be said for butchery leftovers.

**Comment by XygenSS** [comment]
> Nothing is useless, it's just lack of utilization methods. It's unrealistic to assume that something is useless.

I'd argue that it's unrealistic to assume that everything must have a purpose. Some things \*are* simply useless.

We don't model the trash from individual candy wrappers not because they can't be recycled and turned back into aluminum - they can be, given the right equipment - but because there's absolutely no reason to.

Butchery refuse, given the description, is one of them. You could salvage something of value using great effort but you have no practical need to do so.

**Comment by Rocket-F-1024** [comment]
> How have you determined the amount, exactly?
> 
> Feces can make fertilizer because it's got lots of nitrogen availability. I am not confident the same can be said for butchery leftovers.

According to the description, butchery refuse contains feces, connective tissue (usually containing a large amount of cells and proteins such as collagen, both of which are high in nitrogen), hair and claws (usually composed of keratin, which also contains a large amount of nitrogen), as well as unusable soil. Therefore, from the perspective of composition alone, butchery refuse is very suitable for producing fertilizers, and as far as I know, there are also practices in real life that use butchery refuse to produce fertilizers.
According to the original recipe, 6 feces, or 1.5kg of feces, were required. In order to eliminate the weight impact of unusable substances (such as soil) in the slaughter residue, 2kg of butchery refuse (8 butchery refuse) was needed.

**Comment by Rocket-F-1024** [comment]
> I'd argue that it's unrealistic to assume that everything must have a purpose. Some things *are* simply useless.
> 
> We don't model the trash from individual candy wrappers not because they can't be recycled and turned back into aluminum - they can be, given the right equipment - but because there's absolutely no reason to.
> 
> Butchery refuse, given the description, is one of them. You could salvage something of value using great effort but you have no practical need to do so.

According to an article I found, candy packaging paper can indeed be recycled and reused (including chewing gum packaging paper and chocolate packaging paper)
"Foil wrappers can also be recycled if they incorporate no plastic, like yogurt lids and some gum wrappers. If a wrapper stays crumbled when you squeeze it in your hand, it’s foil; if it unfolds, it’s plastic, and should be thrown away. If it’s a really small wrapper – like the foil on a Hershey’s kiss – crumple several together to make a larger clump that won’t clog up a sorting machine. " - https://www.ecowatch.com/recycling-tips-facts.html

**Comment by Hyperseeker** [comment]
I think the issue here is not with candy wrappers and plastic/foil/etc.: I think the issue is with whether @Rocket-F-1024, as the creator of the PR, can provide one of two things:

1. A well-reasoned explanation for why this is viable, including edge cases and potential consequences
2. A real-world example of things that can be reasonably classified as "butchery refuse" being used in composting in a way that doesn't require extra processing

Personally, I like the existing explanation already. Unless it contradicts real-world efficacy data, if this were up to me, I'd merge this. "Some things are just useless" is a failure of imagination and/or expertise, especially in a situation where survival may well depend on the player/character using every available resource.

"But you can get a ton of resources already" discounts situations where looting is limited, e.g. low-item-spawn runs, No Hope runs, challenging or remote starts... "But these are optional" – yes, or, in other words, "Some players may choose to play under less-than-ideal circumstances". Again, in these situations, being careful with one's resources is not just wise: it could be the difference between seeing the next sunrise or starting a new run.

**Review by I-am-Erk — CHANGES_REQUESTED** [review]
Hyperseeker basically has the short of it. I'd want some kind of sourcing on this for using off-scraps of hair and keratin and feces and dirt as a fertilizer. I agree it's *conceivable* but I'm not convinced it would work as an adequate source of nitrogen. If you've got something, I'm not opposed to this on principle, but we try to avoid "eh maybe it makes sense" kind of changes, they tend to cause grief down the road.

It's okay if some things in the game aren't useful.

**Comment by Qrox** [comment]
If butchery refuse contains feces, then it should be able to substitute the feces in the existing recipe, regardless of whether it also contains hair, connective issue, or soil in it. We may need some data on how much feces butchery refuse normally contains but I don't think the practibility of using butchery refuse to make fertilizer can be disputed, as long as it actually contains feces.

**Comment by I-am-Erk** [comment]
Yep, giving an idea how much poop there should be in the goop would be adequate, or giving an idea of how effective all that blood and biomass would be.

**Comment by Rocket-F-1024** [comment]
> Hyperseeker basically has the short of it. I'd want some kind of sourcing on this for using off-scraps of hair and keratin and feces and dirt as a fertilizer. I agree it's _conceivable_ but I'm not convinced it would work as an adequate source of nitrogen. If you've got something, I'm not opposed to this on principle, but we try to avoid "eh maybe it makes sense" kind of changes, they tend to cause grief down the road.
> 
> It's okay if some things in the game aren't useful.

I searched and found that in real life, there is a fertilizer brand called Thallo that uses butchery refuse to produce fertilizers.
In addition, although nitrogen is an important fertilizer, phosphorus and potassium are equally important, as well as other trace elements.

**Comment by RenechCDDA** [comment]
While butchery refuse might contain the stomach contents, it certainly does not contain *any appreciable amount* of actual feces. Even assuming that the contents are 100% feces (really not true until they've moved to the colon equivalent), the overall weight content is pretty low. https://pubmed.ncbi.nlm.nih.gov/8605579/

**Comment by I-am-Erk** [comment]
So, the thallo thing is a good find, but at a brief glance I'm not sure it says what you want. It gives the impression there's a fair bit of post processing going on to make viable fertilizer out of abbatoir waste, it's not just a matter of mixing it up in dirt.

If you find something to the contrary then I take it back, but that very much makes it sound like this is something that requires tech and processing to work

**Comment by Rocket-F-1024** [comment]
This paper actually proves that the slaughtering residue in the game may contain a large amount of feces. Nowadays, the amount of slaughtering residue produced in the game is too small (in most cases, only one portion, which is 0.25kg). However, this article describes that the average wet weight of gastric residue in pigs after slaughter is even 0.87kg. The reason why the dry weight is so low is because pig feces contain a lot of water.

**Comment by Rocket-F-1024** [comment]
> While butchery refuse might contain the stomach contents, it certainly does not contain _any appreciable amount_ of actual feces. Even assuming that the contents are 100% feces (really not true until they've moved to the colon equivalent), the overall weight content is pretty low. https://pubmed.ncbi.nlm.nih.gov/8605579/

This paper actually proves that the slaughtering residue in the game may contain a large amount of feces. Nowadays, the amount of slaughtering residue produced in the game is too small (in most cases, only one portion, which is 0.25kg). However, this article describes that the average wet weight of gastric residue in pigs after slaughter is even 0.87kg. The reason why the dry weight is so low is because pig feces contain a lot of water.

**Comment by Rocket-F-1024** [comment]
> So, the thallo thing is a good find, but at a brief glance I'm not sure it says what you want. It gives the impression there's a fair bit of post processing going on to make viable fertilizer out of abbatoir waste, it's not just a matter of mixing it up in dirt.
> 
> If you find something to the contrary then I take it back, but that very much makes it sound like this is something that requires tech and processing to work

This is an article that uses a simple method (although it may be more complex than the existing formulas in the game, strictly speaking, the current practice of directly heating feces to produce fertilizer is also unrealistic) to produce fertilizer from slaughterhouse waste.
https://www.researchgate.net/publication/280935072_Conversion_of_rural_abattoir_wastes_to_an_organic_fertilizer_and_its_application_in_the_field_cultivation_of_tomato_in_India
And articles on the potential of using simple operations to produce fertilizers using solid waste (even using liquid waste alone can produce fertilizers)
https://www.sciencedirect.com/science/article/pii/S0306261909004796

**Comment by I-am-Erk** [comment]
All right, I'm cautiously interested in the option to make bbrdm fertilizer from blood and butchery refuse processed and dried as in the first paper, if you can adequately explain how a character gets this knowledge and can make a recipe that reflects the post processing required.

**Comment by MNG-cataclysm** [comment]
If the running issue here is the ability to use butchering refuse for normal composting methods without processing or not, then why not just add a recipe for fertilizer from butchering refuse that includes the additional processing steps that may/may not be required?

**Comment by Rocket-F-1024** [comment]
> All right, I'm cautiously interested in the option to make bbrdm fertilizer from blood and butchery refuse processed and dried as in the first paper, if you can adequately explain how a character gets this knowledge and can make a recipe that reflects the post processing required.
> 
> Also apparently I've been vegetarian long enough that these articles are kinda squicky to me now, which is odd since my job regularly involves cutting chunks off people.

Since the recipe for the production of fertilizer from manure is self-evident, it should be logical to extrapolate the use of butchery refuse, which contains a large amount of biomass (and feces), for the production of fertilizer

**Comment by I-am-Erk** [comment]
> Since the recipe for the production of fertilizer from manure is self-evident, it should be logical to extrapolate the use of butchery refuse, which contains a large amount of biomass (and feces), for the production of fertilizer

The paper you cited has them spreading out a particular mix of blood and abbatoir waste and drying it in the sun for several days, and this is a process that they've come to experimentally. I'm a half decent gardener and I don't think that would have occurred to me.

**Review by kevingranade — CHANGES_REQUESTED** [review]
The change in the PR doesn't match your most recent reccommendation for what the process would look like.

If you want to follow the process from the India paper you're looking at seperating "rumen digesta" as a butchery outcome and adding a recipe matching the paper to turn that and blood into a dry fertilizer.

"Turn all the leftover chunks into fertilizer" is not justified by "some of the leftover parts can be turned into fertilizer"

**Comment by Rocket-F-1024** [comment]
> > Since the recipe for the production of fertilizer from manure is self-evident, it should be logical to extrapolate the use of butchery refuse, which contains a large amount of biomass (and feces), for the production of fertilizer
> 
> The paper you cited has them spreading out a particular mix of blood and abbatoir waste and drying it in the sun for several days, and this is a process that they've come to experimentally. I'm a half decent gardener and I don't think that would have occurred to me.

Maybe it's because we're in a different region, but in the rural areas of my country it's very common to make homemade fertilizers from all kinds of wastes (e.g., manure, slaughter waste, leftovers, etc.).

**Comment by ADekema** [comment]
You could use butchery refuse in a bioreactor to make biogas as you can feed the reactor anything that rots. There also seem to be methodes of turning butchery refuse into fertilizer either by composting it in certain ways or having it rot in a barrel for a few months. You should probably look into those methods.

As for adding any butchery product that can be directly used in fertilizer I would say that blood would be the best candidate. It is easy to get from the bleeding action on any corpse and it is a high nitrogen product already used as a product.

**Comment by yuganxia** [comment]
May be you need add a furniture like root cellar and function like charcole kiln.
You need dig a deep hole on grass and put large wooden sheet on top of it.
You can put butchery refuse, burned ash, manure or rusted food in it, then seal it for a whole season, till it turn to bio-fertilizer.
(When open it might release poison smoke or something.)

This kind of cellar is common in Chinese village (But we don't use butchery refuse to do that, i think it might work as well.)
[Chinese doc about fish refuse fertilizer](http://www.fjc001.com/m/fenwuzhili/wufenzhilijishu/59380615412.html)

**Comment by Rocket-F-1024** [comment]
> May be you need add a furniture like root cellar and function like charcole kiln. You need dig a deep hole on grass and put large wooden sheet on top of it. You can put butchery refuse, burned ash, manure or rusted food in it, then seal it for a whole season, till it turn to bio-fertilizer. (When open it might release poison smoke or something.)
> 
> This kind of cellar is common in Chinese village (But we don't use butchery refuse to do that, i think it might work as well.) [Chinese doc about fish refuse fertilizer](http://www.fjc001.com/m/fenwuzhili/wufenzhilijishu/59380615412.html)
> 
> The main idea is, make this process much more harder, because it **is** hard, in real life.

I actually come from the rural area of China, and even though none of my family members are farmers, it's a very common practice to use slaughter residues to compost fertilizer in our area, which is why I brought up this one PR.
Technically speaking, current liquid fertilizer formulations also have serious problems; you can't convert manure into fertilizer with just 20 minutes of heating and dilution.
Regarding using furniture for fermentation though, that's a bit beyond me, it seems to require changes to the C++ side of the code, and I haven't learned C++ systematically.
But I thought of an alternative, using 'use_action', which would only require changes to JSON to make this work, though I'd prefer someone to JSONize the fermentation process.

**Comment by yuganxia** [comment]
> > On this point I have already explained in the previous that I have intentionally increased the weight of the slaughter waste required in the recipe, since it is true that there are parts of the slaughter waste that cannot be made into fertilizer.
> 
> I read your statement and I don't agree with it. The entire point of butchery refuse is to NOT treat it as a catch-all like this and just have "inconvenient" parts evaporate or be incorporated into some other product.
> 
> Also, you've presented evidence for doing one thing (sterilization and desiccation of specifically blood and rumen digesta to yield a powdered fertilizer), and implemented a completely different thing (fermentation of misc bio-waste into a liquid fertilizer).
> 
> If I have to guess your rationale is that since there is a process to turn some butchery refuse into fertilizer, then it can work and the details don't matter, that is incorrect, if you demonstrate that a process is feasible, then just do that process.

So do you think my cellar solution above is more promising? It exist in real life, it has relatively real process, it can explain where the mass gone (become biogas or absorbed by the soil).

**Comment by I-am-Erk** [comment]
I think your idea of burying it and leaving it for a while in a special cellar is probably the closest to a reasonable idea for it yeah. The problem is that it contains all kinds of undifferentiated junk, lots of which needs a long time to break down.

I'm really not convinced the core PR here is going to be viable right now, but some of the stuff we're discussing could be. I'm not sure "butchery refuse" as an in game concept is at all clear enough for it to be just "made useful"

**Comment by Qrox** [comment]
I'd say the current PR is already much more realistic than the previous state. First, it makes it so that a fermentation process is required, as opposed to simply dropping poop into soil, which is likely going to burn the plants, not fertilize them. Secondly, while it's true butchery refuse may contain some hard-to-decompose elements, as long as they are non-toxic, they can simply be treated as an inactive part similar to soil. The only problem I see is that toxic butchery refuse from zombies may need to be distinguished from normal butchery refuse as suggested by @fairyarmadillo.

More improvements other than that can be made in later PRs, but the current problem is whether we want a more realistic simulation or none at all.

**Comment by kevingranade** [comment]
> So do you think my cellar solution above is more promising?

Source

**Comment by Maddremor** [comment]
This is essentially the same argument that was made about plant scraps at one point. People argued that the parts that dropped from plants that weren't sticks, logs, or edible could be used for stuff like cordage, but the issue was that just allowing the scraps to be used in that manner would imply that leaves were also used.

Here we have a similar situation where a practical use is suggested for something _included_ in what we currently call butchery refuse, but if such a thing we're to be added it would no longer be butchery refuse as we use the term. You could have it work in a recipe, but then you would also have to add a byproduct for the unusable stuff, and kicking the can down the road with "butchery refuse refuse" is just silly.

**Comment by yuganxia** [comment]
> > So do you think my cellar solution above is more promising?
> 
> Source

https://www.sciencedirect.com/topics/engineering/biogas-digester
It can produce biogas and fertilizer, no need of electricity.

**Comment by yuganxia** [comment]
> > So do you think my cellar solution above is more promising?
> 
> Source

Anaerobic Digestion
In this process a [biogas](https://www.sciencedirect.com/topics/chemical-engineering/biogas) digester is prepared (closed container) in which the segregation and feeding of the organic fraction takes place. In this digester, the biodegradation of segregated waste takes place under anaerobic conditions and in the presence of methanogenic bacteria, and as a result produces a methane-rich biogas. This generated biogas can be further used for cooking and for electricity generation, which can be processed through gas engines. The fully stabilized sludge that remains after [anaerobic digestion](https://www.sciencedirect.com/topics/chemical-engineering/anaerobic-digestion) can be further used as a soil conditioner. Depending on the composition of the input waste it can even be sold as compost.

**Comment by wwkk222208** [comment]
Yes, the fermentation process is essential. When unfermented feces are directly used as fertilizer, it will produce a large amount of heat due to fermentation, thereby harming the crops.  Like the approach in the present game that the feces are directly used as fertilizer after being heated is not workable.

**Comment by kevingranade** [comment]
https://ecommons.cornell.edu/server/api/core/bitstreams/8775aea4-e582-41e9-9e5c-a5bc19ab5dbc/content

2-6 months and outlines construction of an open air compost pile.

**Comment by kevingranade** [comment]
The large pile outlined in my post isn't the only option, but my understanding is you do need a somewhat larger pile for things like meat because you want it to reach a higher core temperature for a protracted time period.

You really can't brush aside disease risks since this fertilizer would be used to fertilize food crops which is exactly when this risk is highest.

I think we're roughly on the same page though,  intensive composting can take butchery waste as an input so that is a valid way to take this.
That does come with some additional requirements such as a mix of butchery refuse and plant matter being required.

**Comment by I-am-Erk** [comment]
That kind of leads us to wanting a compost heap item, which I'd love but is going really sideways.

**Comment by fairyarmadillo** [comment]
If you put meat in a compost heap, it will stink to high heaven and attract a lot of scavengers. You'll also introduce pathogens into your compost which can survive the composting process and be transfered to any food grown in the stuff.

**Pull request closed without merging**
