### PR TITLE
Log Stools

### PR DESCRIPTION
**Pull request by WhaleyWhaley**
#### Summary
```SUMMARY: Content "Adds new construction option for 'log stool'"```

#### Purpose of change
Just a way to make a place to sit while out in the woods.

#### Describe the solution
One log can be constructed into a log stool with survival skill 1, and a tool with cutting 1. 

#### Testing
Got the required materials and skills and constructed the log stool.

### CODE REVIEW

**Comment by curstwist** [comment]
may want to slightly increase the build time since you mention cleaning up the edges.

**Comment by Night-Pryanik** [comment]
Maybe just add `CAN_SIT` flag to tree trunk and tree stump terrains instead of adding a new furniture?

**Comment by FuelType-Memes** [comment]
> 
> 
> Maybe just add `CAN_SIT` flag to tree trunk and tree stump terrains instead of adding a new furniture?

Why not both?

**Comment by Night-Pryanik** [comment]
> Why not both?

Just less amount of work.

**Pull request merged**
