### PR TITLE
Spacebar tweaks

### PR DESCRIPTION
**Pull request by dikiy4eburator**
#### Summary
Interface "some tweaks to the spacebar"

#### Purpose of change
make the look a bit more consistend and add missing char stat

#### Testing
testet on local build

#### Additional context
Since the "bodybart status legend" widget only has six states, i think it's better to replace it with two lines of text.
This makes the whole block more stable and I can make better use of the unused rows that were reserved for the widget.
I would also like to take the opportunity to add the missing "bionic power" indicator

### CODE REVIEW

**Comment by mlange-42** [comment]
> I would also like to take the opportunity to add the missing "bionic power" indicator

More bionic power widgets come with #59498. Would that cover it?

**Comment by dikiy4eburator** [comment]
no i will have to add them separatly when it get merged,
the indicator i added is the clasic one.

**Comment by ANickelN** [comment]
While you're tweaking, I noticed while using this sidebar that the compass doesn't work entirely, as in it doesn't have the direction indicator turn red when an enemy from that direction sees the player, this is very useful for pulling small amounts of enemies away from groups and would be well loved if it was added.

**Comment by dikiy4eburator** [comment]
> While you're tweaking, I noticed while using this sidebar that the compass doesn't work entirely, as in it doesn't have the direction indicator turn red when an enemy from that direction sees the player, this is very useful for pulling small amounts of enemies away from groups and would be well loved if it was added.

sorry but the compass works fine,
because there a two kinds of compass layouts one is with danger indicator, and the other one with out.
i used in the one with out.

**Comment by ANickelN** [comment]
I didn't realize that was an intentional choice, my apologies.  I'll see if I can figure out the system and replace it with the one with the danger indicator.  Thanks!

**Comment by dikiy4eburator** [comment]
> I didn't realize that was an intentional choice, my apologies. I'll see if I can figure out the system and replace it with the one with the danger indicator. Thanks!

you dont need, i just uploadet the change, it does not change a lot, so its ok. :)

**Pull request merged**
