### PR TITLE
[CR] Fix crash when removing armor

### PR DESCRIPTION
**Pull request by jzambo**

### CODE REVIEW

**Comment by jzambo** [comment]
I'd like to fix this bug but I'm not sure how to update an element index that has just been invalidated. 

Offending line:

leftListIndex = std::min( (unsigned long) leftListIndex , tmp_worn.size() - 2);

**Comment by kevingranade** [comment]
What is the behavior after your change?
From reading the code it looks looks the old problem was it accessing out of bounds if you removed the last listed armor, and the new problem is out of bounds access if you remove the only listed armor.
It looks like if you remove the last element of tmp_worn, the index will be set to -1, so you just need to insure that it is never set to < 0.
I'd suggest
```
int new_tmp_worn_size = std::min( 0, tmp_worn.size() - 2 );
leftListIndex = std::min( leftListIndex , new_tmp_worn_size );
```

**Comment by jzambo** [comment]
I believe it will never crash because std::min is done on unsigned arithmetic thanks to size_type from size() call. The compiler used by CI rejects this approach though.

New behavior possibly introduces a minor issue where worn item "cursor" is reset instead of being decremented if necessary to stay in bounds. To fix this, I need to move the cursor which is trivial if you know how to satisfy the compiler.

The problem I have is with "converting" between incompatible C++ types available here: iterators, size_type and int. I would appreciate guidance regarding arithmetic on indexes into STL vectors here. 

My guess is that leftListIndex should be of type size_type but I haven't tried that.

**Comment by kevingranade** [comment]
> I believe it will never crash because std::min is done on unsigned arithmetic thanks to size_type from size() call.

That's not a good assumption to make, casting a negative number to unsigned and evaluating the result is a *bad idea*.
Is there a reason you think my suggestion won't work?

The specific error gorgon is reporting is that unsigned long and unsigned int don't match, just cast leftlistindex to unsigned int, or cast the size_t to not.
But I'd still recommend my code above, your code is not clamping properly.

**Comment by jzambo** [comment]
The problem stems from design that requires us to decrement size_type by two which may be negative if conversion to signed arithmetic is preferred. In this case, we need to ensure both bounds  using std::max and std::min.

How about this:

int new_index_upper_bound = std::max( 0, ( ( int ) tmp_worn.size() ) - 2 );
leftListIndex = std::min( leftListIndex, new_index_upper_bound );

This works fine as far as I can tell. I also saw no problems regarding resetting cursor which I mentioned.

**Comment by jzambo** [comment]
This PR seems to be stuck with

`diff: /var/lib/jenkins/cataclysm-reference-repo/Makefile: No such file or directory`

How can I reproduce this? Or is it just temporary build inftrastructure issue?

**Comment by AlecWhite** [comment]
It seems to be happening to all PRs.

**Pull request merged**
