### PR TITLE
Use %zu for printf-style formatting of size_t values.

### PR DESCRIPTION
**Pull request by mutability**
This is a semi-automated replacement of %d/%i formats with %zu
when the parameter is of type size_t. It was driven by parsing the
warnings generated by PRINTF_CHECKS.

Also fixes one case where a size_t was passed as a width specifier
(this has to be an int)

Adds a testcase that tests that %zu and positional args work OK.

This requires C++11 / C99 printf support. The current CI environment
does not provide this for Windows builds, so this needs to be
merged _after_ the CI environment has been upgraded.

(previously: #19339)

### CODE REVIEW

**Comment by BrettDong** [comment]
Merge conflicts need to be resolved.

**Comment by mutability** [comment]
No point looking at the conflicts until the CI environment is ready.

**Comment by BrettDong** [comment]
Oh yeah, just a habitual reminder though meaningless for this PR.

**Comment by mutability** [comment]
> The current CI environment does not provide this for Windows builds, so this needs to be merged after the CI environment has been upgraded.

No, really, I did mean that.
Do you want me to create a _third_ copy of this PR?

**Comment by kevingranade** [comment]
I'll be able to un-revert it once the CI environment is updated. No need
for a new pr.

**Comment by mutability** [comment]
Any news on un-reverting this?

**Comment by narc0tiq** [comment]
That's rather dependent on me getting http://gorgon.narc.ro:8080/ to become the new build environment.

I didn't believe it was terribly urgent, so I've given it time to show problems (which it definitely has, on multiple occasions -- mostly to do with eating all the disk space available). I still need to give it the OSX build environment, and to get it supplying build artifacts, then it can replace ci.narc.ro.

**Comment by mutability** [comment]
It's not urgent, I just want to make sure the un-revert doesn't get lost since there is no open issue or PR tracking this.

**Comment by narc0tiq** [comment]
I am keeping the email thread in my inbox, both to remind me to work on it,
and to reply when it's ready.

**Comment by narc0tiq** [comment]
As of now, gorgon is the new primary build environment (still publishing to the same output, but now with complete platform/graphics coverage). Therefore:

```
[narc@gorgon ~]% /home/narc/mxe/usr/bin/i686-w64-mingw32.static-g++ --version
i686-w64-mingw32.static-g++ (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

We can now resurrect this and get the printf warnings fixed.

**Pull request merged**
