### PR TITLE
[WIP] Make fish fillets more calorie-dense (this time for real)

### LINKED ISSUE #36302: Calorie adjustment: Fish portions
1 Fillet of Fish (0.15kg) is listed ingame as having 90 calories. I thought this was weirdly low, as these are pretty big chunks of meat. If it's got feet or fins, it has fat, and that means calories.

You can catch salmon, and I figured this wouldn't be a bad 'standard' fish to check the games baseline from. I also checked whitefish, an obviously leaner fish.

A quick Google search identified Atlantic Salmon (0.10kg) as having ~210Cal (315 Calories for 0.15kg), making the CDDA fillets about 200 calories short. For comparison, 100g of whitefish has ~170 calories (261Cal for 0.15kg)

I recommend making an adjustment to Fillet of Fish to be within 250-310 calories. The new nutrition system should propagate the calorie counts to derivative recipes if I understand it properly. I could see an arguement as low as 200 calories to take into account a population of 'lean' fish, but the yield of 'scraps of meat' when butchering fish, and their lower overall yields, are sufficient to account for this discrepancy as this is how small game is handled as compared to larger animals.

### PR DESCRIPTION
**Pull request by cozardi**
Summary
SUMMARY: Balance "Up the calories in fish fillet"

Purpose of change
Resolves #36302 - fish values were based on cod, a pretty lean fish, whereas now they're based on whitefish

Describe the solution
Changed fish fillet calories from 90 to 260 kcal, according to the explanation in #36302. Also changed the comment saying what the caloric values are based on.

Describe alternatives you've considered
Not changing it.

Testing
Butchered fish, their meat now has the correct caloric value, so do fish-based recipes

Additional context
Only implemented what was brought up in the issue, maybe upping the calories on fish can throw off balance, but I don't think it's that significant.

### CODE REVIEW

**Comment by CountAlex** [comment]
It seems you need to tweak resulting food items (e.g. fried fish, lutefisk, fish soup etc.) calories expectation value tweaked to meet new amount of calories provided by fish. I believe most of those are located at `data\json\items\comestibles\meat_dishes.json` 
I suggest going through the list of those failed C/C++ build test first.

**Comment by KorGgenT** [comment]
cod's the most common fish in new england. what's the reasoning behind changing it to whitefish?

**Comment by Rivet-the-Zombie** [comment]
Cod is a whitefish.

**Comment by Zourin2** [comment]
What happened to this PR?

**Comment by KorGgenT** [comment]
@Zourin2 the author closed it for an unspecified reason

**Pull request closed without merging**
