### PR TITLE
Feed NPCs using their stomachs when they eat from faction camps

### LINKED ISSUE #47663: NPCs remain permanantly hungry when eating out of faction camp stores
# Describe the bug
NPCs remain perpetually hungry when being fed through faction camp stores.  Their stored calories are correctly being updated so they don't actually starve, but their hunger meter remains maxed out, which causes them to complain of hunger and refuse to train you.

# Steps To Reproduce

1. Recruit an NPC
2. Build a faction camp
3. Stock the camp larder with at least 50 kcal of food
4. Edit the NPC's needs so that they have 300 hunger and have 52200 stored kcal (50 kcal below the number at which they start eating from the camp larder)
5. Wait a few moments and check the NPC needs screen.  Observe that NPC's hunger remains 300 calories, though their stored kcal is back up to 52250

# Expected behavior
Feeding NPCs through faction camps fills their stomachs properly so they don't complain of hunger or refuse to train you

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9792-g0731d85177 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Second half of #47596 

The relevant code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0731d8517713c9357b25ac7c6f55eb137432f04e/src/npcmove.cpp#L3818-L3826

While testing this again on the latest version, I've noticed something interesting -- sometimes the hunger does seem to get updated and sometimes it does not.  It seems like larger calorie deficits more reliably cause their hunger to go down, while a deficit of only 50 kcal usually causes hunger to remain at maximum.  I'm not sure why.

### PR DESCRIPTION
**Pull request by RadHazard**
#### Summary
Bugfixes "NPCs now eat from faction camps using their stomachs, eliminating phantom hunger pangs"

#### Purpose of change
Fixes #47663
Prior to this, NPCs simply teleported calories directly into their fat stores, which bypassed the entire stomach system.  This was causing various oddities in behavior when they ate from faction camps compared to eating regular food.

#### Describe the solution
I simply created a fake food_summary item, filled it with the calories they would have otherwise teleported, and stuffed it into their bellies.  The volume of the fake food is enough to fill them up without making them vomit, which is good enough for now but can certainly be improved if faction camps do more detailed food tracking in the future.

There were a few other minor changes as well:
- NPCs only eat from camp stores when hungry, to stop them from vacuuming up all your food if they're underweight
- NPCs eat a maximum of 2500 kcals in a sitting, again to stop the food vacuum
- NPCs try to eat 100 more kcals than their kcal limit, to avoid them eating tiny amounts of food every 5 minutes.

#### Describe alternatives you've considered
I considered giving the fake food a fixed volume or volume dependent on calories, but it was hard to balance in a way to keep NPCs from eating too much and vomiting.

I considered giving the fake food vitamins, but vitamin deficiencies do nothing right now and if that changes in the future faction camps should be updated to track vitamins anyway.

I also considered more detailed tracking of vitamins and/or food volumes in the camp store, but that would be a much bigger sweeping change that would be better suited for after 0.F.

#### Testing
Scenarios I tested, using the debug tools introduced in #47716

1. NPC with an empty stomach and 52200 stored calories -> They ate 150 calories which ended up in their stomach, making them full
2. NPC with a stomach with 150 calories and 52200 stored calories -> They did not attempt to eat anything
3. NPC with an empty stomach and 52200 stored calories, but only 100 were available -> They ate only 100 calories and emptied the larder
4. NPC with an empty stomach, 52200 stored calories, and the larder was empty -> They complained about an empty larder
5. NPC with an empty stomach and only 42250 stored calories -> They ate 2500 camp calories, and didn't attempt to eat any more until they digested enough to feel hungry an hour later

Incidentally, these would make good unit tests but I'm entirely unsure how to create a working faction camp in a unit test, so I wasn't able to implement them :(

#### Additional context
While messing around with this code, I observed that the hunger variable is now completely controlled by `update_stomach()`.  Thus, any calls to `set_hunger()` or `mod_hunger()` outside of that method do absolutely nothing long term and almost certainly need to be changed.

See #47391 for examples of other places that still use `mod_hunger()`

### CODE REVIEW

**Comment by Maleclypse** [comment]
Is there a maximum number of calories they'll eat in a day? Won't their stomach empty out of 2500 kcals in thirty minutes or so?

**Comment by RadHazard** [comment]
> Is there a maximum number of calories they'll eat in a day? Won't their stomach empty out of 2500 kcals in thirty minutes or so?

No, but I don't think that's necessarily a problem.  If instead of eating from the camp store they had a giant pile of smoked meat, they'd eat about as much in a day anyway if they were really that hungry.  Mostly the limit is there to stop absurd outcomes like them vacuuming up 20k calories in one sitting.

**Comment by linonetwo** [comment]
This seems gets regression in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-06-22-0605

NPC in the camp still getting hungry.

**Comment by linonetwo** [comment]
@RadHazard could you take a look at this? Camp fooding is not workong anymore.

**Pull request merged**
