### PR TITLE
Gender-specific clothing on corpses, part two

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Gender-specific clothing on corpses."```

#### Purpose of change
Men in tuxedos, women in dresses. 
Continuation of #34032, now for loot dropped by zombies.

#### Describe the solution
Made a lot of checks for various conditions to eradicate situations where male zombie dropped female underwear or wedding veil, or other silly combinations of clothing.

#### Describe alternatives you've considered
None.

#### Testing
Spawned ~50 zombies, debug-killed them, checked for their dropped clothing.

#### Additional context
None.

### CODE REVIEW

**Comment by Funguss** [comment]
Does this fix the zombie children in wedding dresses bug by any chance?

**Comment by Night-Pryanik** [comment]
> Does this fix the zombie children in wedding dresses bug by any chance?

Not yet. Zombie children drop items from `default_zombie_clothes` loot table, which contain wedding dress and other maybe-inappropriate clothing. 
I will try to fix this later today.

**Comment by Funguss** [comment]
Well, that's the only thing I've noticed recently at least. No more drugs, vibrators, cigarettes... Never seen them in bondage gear thankfully but I'm guessing it's a matter of time. To be fair, cigarettes and drugs should probably be a semi rare drop, at least if it were set here in England. Dunno about New England, but I'd guess it's just a matter of degree.

Nice one for this, and thanks for all of your effort so far! :+1:

**Comment by Night-Pryanik** [comment]
I didn't change zombie children non-clothing loot tables, so (in)famous children's crack is still with us.

**Comment by Funguss** [comment]
Oh wow... Yeah I was thinking more cannabis and alcohol. I forgot about crack, that's just depressing.

**Pull request merged**
