### PR TITLE
Add looks_like to a number of books

### LINKED ISSUE #45926: A lot of books lack a looks_like
# Describe the bug

At least most books in the game don't have a `looks_like` and it requires a lot of work to get a tileset looking decent. I'm preparing a new Ultica tileset release and have other things to do, unfortunately, please help with these books.

### PR DESCRIPTION
**Pull request by xerenogan**
#### Summary

SUMMARY: Infrastructure "Add looks_like to a number of books"

#### Purpose of change

Fixes #45926

There are a number of books that look very similar to others, and were not using the existing tile art.
As a result most of the books were appearing in the ultica tileset as question marks.

#### Describe the solution

Checked which books were not showing the correct tile in-game, and then went through each books json and added the appropriate looks_like option.

#### Describe alternatives you've considered

None.

#### Testing

Spawned every single book, each on it's own separate tile. Loaded the changed json and made sure every book displayed correctly. Checked debug.log after running to ensure no additional errors.

#### Additional context
books_looks-like_start
books_looks-like_done

### CODE REVIEW

**Comment by int-ua** [comment]
Thank you! What are the 5 unknown ones?

**Comment by xerenogan** [comment]
Those are schematics. I'm not sure why those are showing unknown.

**Comment by int-ua** [comment]
tripod, tank drone, dispatch, military dispatch and chicken walker

**Comment by xerenogan** [comment]
There we go. Fixed.

**Comment by int-ua** [comment]
2020-12-11-114147_1920x1080_scrot

**Pull request merged**
