### PR TITLE
Exoskeleton update

### LINKED ISSUE #60613: Material energy consumption and efficiency
### Is your feature request related to a problem? Please describe.

We have a few non-CBM non-vehicle power generators now, primarily used on the various exoskeletons/exosuits. For the ones that consume fuel, the fuel is consumed as a single charge to generate power, rather than using the appropriate material energy. Additionally, there is currently no way to modify the efficiency of that consumption. 

### Solution you would like.

Two additional fields, something along the lines of
"consume-as-fuel": "true"
"fuel-efficiency": "40"

### Describe alternatives you have considered.

Continuing to burn lamp oil and ammonia at the same rate.

### Additional context

List of known items this would help with:
power_armor_generator
ice_utility_exoskeleton_on
exo_back_gasoline
exo_back_fuelcell

### LINKED ISSUE #61140: Cable charger improvements
### Is your feature request related to a problem? Please describe.

I'd like to utilize the cable charger effect for the various powered exoskeletons/frames/suits etc., however the actual current functionality is only available to the CBM. 

### Solution you would like.

Add a flag or iuse allowing for more cable charging options.

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Drew4484**
#### Summary
Content "Additional updates to exoskeletons"

#### Purpose of change
Bring exoskeletons in line with detailed armor coverage (weakpoints at joints/eyes, ablative plating) as well as some additional QOL features. 
Replaces existing combat exoskeletons with Mark 1, 2, and 3 frames. Frames will have swappable armor plating so when the issued composite plates break the player can replace them with forged steel or makeshift scraps if they're desperate. Removes separate helmet item, all frames will have integrated climate control and toggleable NVG/IR vision, clock, weather, glare protection, hearing protection, radio.

Weight capacity is designed for combat load (23.18 kg) consisting of:
|Weight|Count|Item
|---: |---: |---: |
|6.9 kg|1|M3E1 Recoilless Rifle
|16.5 kg|5|84x246mm HEDP rocket
|16 kg|5|84x246mm HE rocket
|3.5 kg|1|M27 assault rifle
|2.4 kg|10|STANAG 60-round magazine
|12 kg|600|7.62x51mm M80
|0.4 kg|6|Fragmentation grenade
|2.88 kg|2|IFAK

Plus the weight of the stock composite plating, 36.85 kg.
|Weight|Volume|Count|Item
|---: |---: |---: |---: |
|2.75 kg|4 L|1|Composite Helmet
|17.5 kg|25.5 L|1|Composite Torso
|4.15 kg|4.5 L|2|Composite Arm
|4.15 kg|5.5 L|2|Composite Leg
|3.9 kg|4 L|1|Steel/Makeshift Helmet
|24 kg|25.5 L|1|Steel/Makeshift Torso
|6 kg|4.5 L|2|Steel/Makeshift Arm
|6 kg|4.5 L|2|Steel/Makeshift Leg

| Model | Efficiency | Capacity | Power Supply | Enc/Active | Dry Weight | Notes
|---: |---: |---: |---: |---: |---: |---: 
| Mark 1 |  80% | 150 kg | Fixed Diesel |  80/15 | 90 kg | +5 str, +5 enc to hands
| Mark 2 | 100% |  135 kg | Modular |  60/10 | 75 kg | +5 str
| Mark 3 | 120% |  120 kg | Modular |  40/0 | 60 kg | +5 str, advanced HUD blocks vision while suit is offline
| ICE Utility | 100% | 215 kg | Fixed Diesel | 20/20 | 110 kg | +10 str
| Battery Utility | 100% | 190 kg | Battery | 20/20 |  90 kg | +10 str

#### Describe the solution

Frames:
- [ ] Mark 1: Overbuilt drive system makes it awkward to move in.
- [ ] Mark 2: Production model, baseline performance.
- [ ] Mark 3: Prototype, feels like you're wearing nothing at all.

Armor: 
- [ ] Layer coverage to leave minor vulnerabilities at joints
- [ ] Make non-craftable ablative composite plates for armor protection
- [ ] Add replacement steel plates with recipe
- [ ] Add makeshift plates with recipe

Power:
- [ ] Internal power storage for all marks
- [ ] Swappable power source (ICE, fuel cell, battery) for mark 2 and 3
- [ ] Cable charge option (would resolve #61140)
- [x] Improve power consumption model to burn fuel for energy rather than consume X units per tick (resolved by #66348, thanks to bombasticSlacks!)
- [x] Update fuel consumption/power requirements (suit should draw more power and consume more fuel)
- [ ] Integrate changes from #58844
- [ ] Possibly use @anoobindisguise's work to make some heavy weapons not require mounting for firing, this would be limited to specific weapons like the gatling shotgun, not things like hip firing an M2.

#### Describe alternatives you've considered

Deleting power armor from the core game entirely as it's years beyond practical production.

#### Testing
WIP

#### Additional context
Suggestions are welcome!

### CODE REVIEW

**Comment by Raikiri** [comment]
It's very exiting, I really hope you guys will have enough motivation to pull this one.

Particularly excited about multiple tiers of frames and long-term maintenance by maintaining ablative armor plates. I love the idea of having armor as a persistent maintenance and upgrade project rather than being an endpoint of a playthrough.

Even though it would be amazing to have its own UI, I think it should be possible to implement a functioning power armor system based on the already implemented stuff the same how how hub 01 modular armor works.

What's the plan on how it's going to interact with other equipment such as clothing and storage? I wish the power armor did not just straight up invalidate whatever gear you have accumulated, but instead acted as an outer/strapped suit, similar to how currently implemented industrial exoskeletons work.

Since @Drew4484 and @andrei8l seems liek the only people actively participating in this project, I feel like maybe either adding a bounty on it or supporting you guys on patreon if you have that.

**Comment by halosammy** [comment]
I especially love that you switched exoskeletons to outer layer items. It gives a lot more flexibility with clothing options.

**Comment by Raikiri** [comment]
Watching this issue since the begging, excited about every update.

**Comment by Raikiri** [comment]
Very sad 😞

**Comment by Kwenchin** [comment]
I think I can finish this but I don't know how to "pick up" an unfinished PR from someone else.

**Comment by Zireael07** [comment]
@Kwenchin create a fork of DDA, check it out to a folder, then check out https://github.com/Drew4484/Cataclysm-DDA/tree/Exoskeleton-Update to a folder, copy files from that folder over and you should have the state as of this PR's closing

**Comment by harakka** [comment]
> copy files from that folder over and you should have the state as of this PR's closing

Not ideal, this loses authorship of the original work.

**Comment by Zireael07** [comment]
I know there's ways to have a commit have multiple authors, but I'm not sure how to do it outside of Github Desktop, which is... far from a good git client

**Comment by Kwenchin** [comment]
I submitted a PR aiming to finish this update, check it out at #68758.

**Pull request closed without merging**
