### PR TITLE
RetroDays19-01-15

### PR DESCRIPTION
**Pull request by Antistar**
Updated tileset for all new tiles in experimental as of around 19-01-15.

See the thread here for more info:

http://smf.cataclysmdda.com/index.php?topic=5482.msg212011#msg212011

### CODE REVIEW

**Comment by KA101** [comment]
Couldn't compile because some clever person (not you) used stoi, which isn't supported in mingw.

>_<

**Comment by Antistar** [comment]
I, uh... am afraid I don't understand what that means.

**Comment by KA101** [comment]
I couldn't properly build a master branch, much less this, so last night was pretty much cancelled.

**Comment by DavidKeaton** [comment]
Antistar, retrodays is dope as hell. Thanksfor the update!!!

**Pull request merged**
