### PR TITLE
changes splints to be fitted

### PR DESCRIPTION
**Pull request by Tsunder**
an wearable of medical healing-ness should be fitted! 

also adjusts encumberance to keep effective encumberance the same

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
I don't see why not.

**Comment by Coolthulhu** [comment]
There is only one spawn for splints and it is incredibly rare, rarer than power armor.
All other splints are crafted and thus fitted.

**Comment by Mecares** [comment]
Maybe we should add them to Ambulances, Hospitals and Doctors Offices item spawn lists

**Comment by pisskop** [comment]
id agrue that we should make the player refit it themselves somehow, but thats an awful lot of work for some small rp

**Comment by Coolthulhu** [comment]
By the way, "fitting" implies it can't be adjusted with straps to fit and needs to be tailor-made (or destructively tailored by replacing parts of it) for specific sizes.

**Comment by kevingranade** [comment]
More specifically means it's an item that appears in multiple sizes, and
it's the right size for your character.  If it's one-size-fits-all, which
splints are, it doesn't apply.

**Pull request closed without merging**
