### PR TITLE
Weapon Categories: Medieval Swordsmanship

### PR DESCRIPTION
**Pull request by catdach**
#### Summary
Balance "Add weapon categories for Medieval Swordsmanship"

#### Purpose of change
Partially implements #51867.

#### Describe the solution
Put Estoc into LONG_SWORDS category

Added the following weapon categories
- CONSTRUCTED_SWORDS
  Swords made by _someone_ who doesn't know what they're doing, without proper tools. (you! 😄) i.e. 2-by-sword, nord, crude sword, and metal sword.
- MEDIEVAL_SWORDS
  Every sword that was in Medieval Swordsmanship previously that isn't in constructed swords.

made but did not include in this martial art
- JAPANESE_SWORDS
  Katana, Wakizashi, and Nodachi

Something to note is that by expanding the LONG_SWORDS category, other martial arts that make use of the category, such as Ninjutsu, will now include the Estoc.

#### Describe alternatives you've considered
None

#### Testing
Start a new game. Unlock med swordsmanship with the debug menu and spawn in a sword. Start killing zombies.

#### Additional context
It could be argued that the Estoc is mainly fencing sword and not longsword due it not having only a [sharp point, no cutting edge](https://en.wikipedia.org/wiki/Estoc) and being a sort of ancestor to the rapier, but it fits the size requirements and was already in the medieval swordsmanship style so I assume it could be used in similar fashion to other longswords despite the lack of an edge.

### CODE REVIEW

**Comment by Photoloss** [comment]
> I assume it could be used in similar fashion to other longswords despite the lack of an edge.

That may be true for certain techniques, especially halfswording and murder strokes used between fully armoured combatants in the later periods, but definitely not for something like Iaido, general katana cuts or the Montante flourishes.

**Comment by Photoloss** [comment]
> While I do agree, these specific techniques aren't relevant to the current Medieval Swordsmanship artstyle nor any other artstyles in the base game that I'm aware of. So it doesn't seem particularly relevant to this PR.
> 
> It would be nice to have categories to differentiate between things like eastern weapons and western weapons, or even double edged and single edged swords. That might happen later, (there is some discussion of it here #53297) for now we don't have that level of distinction.

I replied because of this: "Something else to note is that by expanding the LONG_SWORDS category, other martial arts that make use of the category, such as Ninjutsu, will now include the Zweihander and Estoc." - Ninjutsu isn't a real martial art to my knowledge but I would definitely expect Niten to eventually use that category in good faith if it doesn't do so already.

**Comment by Termineitor244** [comment]
I asked about categories for this martial art (As well as the Japenese Swordmanship) on the discord some time ago, and the answer I got from @Hymore246 was to create a new category ("MEDIEVAL_SWORDS", "JAPENESE_SWORDS" for example) because these martial arts are supposed to only use the weapons of their themes for which they are trained (Medieval Swords and Japenese/Oriental Swords).
This are the exact words from Hymore246:

> It is a bit tricky but I think option 2 would be best. We might run into an issue where the weapon categories become too broad and bloated and suddenly styles can use weapons that didn't exist or were far away from where they style was made. You could argue that you could do Medieval Swordsmanship with a katana but that isn't really a weapon they train to use. Only way that works is if the modern versions of the style trains with that weapon but I don't think that is the case.

The options I proposed were these:

> 1._ To just enable them to use all kind of swords of similar size to the ones they already use, using the categories implemented with Ninjutsu (Short, medium and long swords).
2._ To implement 3 new categories: "Medieval swords", "Japanese swords" and something like "Self made swords" and giving them to the styles as appropriate, basically not changing what weapons they can use.

The first option is what is being implemented in this PR, and the second option is what was given green light.

Apart from that... I think the zweihänder is big enough that it can not fit into "Long Swords" anymore, the estoc I think is fine.

**Comment by Photoloss** [comment]
Eh, culture should not matter. What matters is the actual shape and damage mechanics of the weapons. One-handed katana techniques will work with a cavalry sabre, a jian will work for most arming sword/longsword techniques (depending on whether it's built for one-handed or two-handed use), but a katana will definitely not work for false edge cuts you can perform with an arming sword nor for rapier thrusts.

Which is why I am hesitant about the estoc. It's from the matching culture and time period (kinda) but it does not function like a typical sword. I'd rather put it into a "THRUSTING_SWORDS" category but as a two-handed weapon it probably wouldn't work very well with (even historical) Fencing so that category would not serve any purpose.

**Comment by catdach** [comment]
So...I...uh...*sigh* I should have known things wouldn't be this easy. My goal with this PR was to use the current categories for now, with the intent change them to more rigorous and exclusive categories later. If I should make some more rigorous categories now then I will, but there are some problems.

> 2._ To implement 3 new categories: "Medieval swords", "Japanese swords" and something like "Self made swords" and giving them to the styles as appropriate, basically not changing what weapons they can use.

I can do that but then there is the problem of all the edge cases like the Scimitar and the Dao. should I leave them out or make them each their own category like "middle eastern swords" and "Chinese swords"? 

Are all the "Fencing swords" also "Medieval swords"? surely not. So what about the estoc? is it both? if the estoc is in medieval swords then why not the rapier? Heck, why isn't the rapier in medieval swordsmanship? What qualities of the estoc put it in medieval swordsmanship that the rapier doesn't have? historical time period? size?

> I think the zweihänder is big enough that it can not fit into "Long Swords" anymore, the estoc I think is fine.

Ok so, should I make a "Great Sword" category? I'm hesitant to make a category for a single weapon.
I could just not give it a category, but that seems like it defeats the purpose of having all these weapon categories.

> The first option is what is being implemented in this PR, and the second option is what was given green light.

Oh, I wasn't aware of that, I'll do my best to implement option 2 then.



> Which is why I am hesitant about the estoc. It's from the matching culture and time period (kinda) but it does not function like a typical sword. I'd rather put it into a "THRUSTING_SWORDS" category but as a two-handed weapon it probably wouldn't work very well with (even historical) Fencing so that category would not serve any purpose.

I want every weapon that's in the artstyle to have a category reflective of _why_ it is in the artstyle, and I'm not going to put a "thrusting_swords" category in this artstyle. Well, I'm not going to remove the estoc from this art style, that's a nonstarter. the differences between it and other twohanded swords are already reflected by things like damage type, and the differences in technique are not reflected in the implementation of this martial art style enough to differentiate it from other longswords.

**Comment by Terrorforge** [comment]
> Heck, why isn't the rapier in medieval swordsmanship?

I could make a coherent argument about how the rapier is fundamentally different from the other swords in that style, but the real answer is that these categories are fundamentally aesthetic. Niten Ichi-Ryu doesn't exclusively use Japanese swords because they have some irreplaceable physical property that would otherwise make the style useless, it exclusively uses Japanese swords because it's "the samurai style".

I agree that, realistically, you could probably use a longsword instead of a katana, but that starts to muddy up the identity of the styles.

Then again, making a bunch of categories like EUROPEAN_SWORDS and JAPANESE_SWORDS kind of defeats the purpose of even having weapon categories in the first place, doesn't it? And it's especially weird to do when we already have a load of martial arts that _do_ treat weapons as interchangeable. If we're okay saying that a kukri is as good as a tanto for ninjutsu purposes, why are we not okay saying that a scimitar and a sabre are similar enough to work in the same style?

**Comment by Termineitor244** [comment]
> I can do that but then there is the problem of all the edge cases like the Scimitar and the Dao. should I leave them out or make them each their own category like "middle eastern swords" and "Chinese swords"?

They already belong to "MEDIUM_SWORDS", and for now I don't see a need to add more categories to them unless they could be reasonable used by another martial art (And the rest of the medium length swords not).

> Are all the "Fencing swords" also "Medieval swords"? surely not. So what about the estoc? is it both? if the estoc is in medieval swords then why not the rapier? Heck, why isn't the rapier in medieval swordsmanship? What qualities of the estoc put it in medieval swordsmanship that the rapier doesn't have? historical time period? size?

Difficult question, and one of the reasons why I left this martial art alone until now, I recommend you only create the categories and include the weapons that the style is using right now, leave any additions (apart from variants of the weapons already in the style) for another PR, so the discussion can focus in one thing at a time.

> Ok so, should I make a "Great Sword" category? I'm hesitant to make a category for a single weapon.

I don't think so, unless you plan to add more giga swords like this one, I would just leave it outside of the main categories and just add it to a specialized category ("MEDIEVAL_SWORDS").

> I could just not give it a category, but that seems like it defeats the purpose of having all these weapon categories.

Some weapons are just too different from the rest already in the game, the tricky part is finding enough similarities to connect them with other weapons for use in a style, there is nothing bad about a weapon without category, the bullwhip doesnt has any categories, because there are not any styles that would use it and there is not enough similarity in its use/form with other weapons for it to be added to one, and there is nothing bad with it.

> If we're okay saying that a kukri is as good as a tanto for ninjutsu purposes, why are we not okay saying that a scimitar and a sabre are similar enough to work in the same style?

It depends on the style I would say, the techniques can require different forms in a weapon, fencing requires one specific use for its weapons for example, one could argue the same with the japanese swords given the weird techniques it uses.

I personally prefer to use the swords categories already implemented for this styles, but I can understand the argument in favor of thematic categories.

A third option in this dilemma could be to allow all kind of swords for the styles, but with restrictions for non japanese/medieval european swords, so you can only use the buffs/certain general techniques unless you are using a thematic weapon for the style.

Or to create a different, weaker kind of buffs/techs that work with the general swords so you can use with the style but with less efficiency.

> So...I...uh..._sigh_ I should have known things wouldn't be this easy.

Yeah, sorry, that's one of the things that keeps me from completing this project, the unarmed martial arts are another beast that needs some thought and testing too (for the changes I want to make to them)... I really need to finish those.

**Comment by catdach** [comment]
At some point, all categorization becomes arbitrary and subjective, so it's never going to be perfect. As people on the internet like to say "everything is either a soup or a salad" and salads are really just vegetable soup. Still, at some level they should be useful so...yeah I'll stick to what the situation calls for I suppose.

> Yeah, sorry, that's one of the things that keeps me from completing this project, the unarmed martial arts are another beast that needs some thought and testing too (for the changes I want to make to them)... I really need to finish those.

Godspeed comrade

**Comment by Terrorforge** [comment]
> It depends on the style I would say, the techniques can require different forms in a weapon, fencing requires one specific use for its weapons for example, one could argue the same with the japanese swords given the weird techniques it uses.

Sure, but there is a bit of (mostly intentional) fuzziness. Medieval swordsmanship isn't any particular style, it's a vague catchall for various central European sword arts from across a 500-year period, which is why people have felt comfortable adding things like the zweihander and cavalry sabre. If we want to define what's appropriate based on the actual physical properties of the weapons, we're gonna have the define what those properties actually are.

But if we so go for the more general approach, I'd be inclined to be a bit lenient. E.g. medieval longsword arts do include false edge cuts, so you could argue medieval swordsmanship should only allow double-edged swords. But they're not exactly a central feature, so it would hardly be an insurmountable obstacle to use the techniques with a single edged blade.

I guess another option is that you can use the core weapons as it currently works, and you can use slightly off substitutions like longsword <-> katana, but only if you put in some extra effort to adapt your techniques. Like you need a weapon proficiency, or... oh! The easiest solution to that would probably just be that if you use an "off" weapon, your Melee skill counts as one or two points lower for purposes of unlocking techniques.

**Pull request merged**
