### PR TITLE
Fixes mall_cop profession's items

### LINKED ISSUE #33364: Mall Security profession starts with flashlight, incompatible battery
# Describe the bug

The `mall_cop` profession comes with a `flashlight` and a `medium_battery_cell`, but the `flashlight` is compatible with 

```
    "magazines": [
      [
        "battery",
        [
          "light_battery_cell",
          "light_plus_battery_cell",
          "light_minus_battery_cell",
          "light_atomic_battery_cell",
          "light_minus_atomic_battery_cell",
          "light_minus_disposable_cell",
          "light_disposable_cell"
        ]
      ]
    ],
```

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.04; Release: 19.04; Codename: disco; 
- Game Version: 0.D-6692-gcf4ce7d691-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by RedShakespeare**
#### Summary

SUMMARY:Bugfixes "Fixes mall_cop profession's items"
#### Purpose of change

Fixes #33364-Mall Security guy starts with a useless flashlight 
#### Describe the solution

Replace the useless medium battery cell with a light+ one.

#### Describe alternatives you've considered

Other battery cells which fit the flashlight will do.(or we can replace the flashlight with a heavy-size one.)

### CODE REVIEW

**Comment by pierredavidbelanger** [comment]
But the `tazer` will now be useless.

**Comment by RedShakespeare** [comment]
> But the `tazer` will now be useless.

Oh yes...I totally forgot about that.
Will it be imbalance if two different battery cells are carried?

**Comment by pierredavidbelanger** [comment]
In my original issue (#33364) was misleading because I was also forgetting the tazer, I just realized what the medium battery was for while testing my own fix (#33366)

**Comment by RedShakespeare** [comment]
> In my original issue (#33364) was misleading because I was also forgetting the tazer, I just realized what the medium battery was for while testing my own fix (#33366)

Saw that just now.lol

**Pull request closed without merging**
