### PR TITLE
fix tangent calculation in projectile attacks

### LINKED ISSUE #16925: Ranged and throwing dispersion use a very poor approximation of tangent
Windows 10
Tiles
Version 0.C-14379-ga3bc3ca

Approximating tangent by multiplying angle by 0.745 is a very poor approximation. Multiplying by 1.0 would be a better approximation, which is very commonly used for small angles. As the angle gets larger the actual tangent will get higher and higher above the angle, so my vote is to use the actual tangent. On a miss, the same function calls `cos`, `sin`, and `atan2`, so it makes little sense to use an approximation for performance reasons.

in Creature::projectile_attack in ranged.cpp:
```
    // shot_dispersion is in MOA - 1/60 of a degree
    constexpr double moa = M_PI / 180 / 60;
    // We're approximating the tangent. Multiplying angle*range by ~0.745 does that (kinda).
    constexpr double to_tangent = 0.745;

    double range = rl_dist( source, target_arg );
    double missed_by = shot_dispersion * moa * to_tangent * range;
```

very closely related, the code for throwing seems to be applying this approximation twice, since the result gets sent to `projectile_attack`.

In player::throw_item in ranged.cpp:

```
    // Rescaling to use the same units as projectile_attack
    const double shot_dispersion = deviation * (.01 / 0.00021666666666666666);
```
```
    auto dealt_attack = projectile_attack( proj, target, shot_dispersion );
```

0.745 ⋅ π ∕ 180 ∕ 60 ≈ 0.0002167117, so my best guess is that this used to be a questionable approximation for the tangent of an angle in MOA that somebody rounded to 0.0002167 and then somebody else assumed that 0.0002167 was supposed to be 0.0021 ̅6. To explain the .01, I've got nothing. This should be changed to just a conversion from quarter degrees to MOA by multiplying by 15.
```
    constexpr double quarter_degrees_to_moa = 15;
    const double shot_dispersion = deviation * quarter_degrees_to_moa;
```

### PR DESCRIPTION
**Pull request by ghost**
fixes #16925

### CODE REVIEW

**Comment by Coolthulhu** [comment]
What about misses at 90 degree, 180 degree etc. dispersion? The argument for `tan` should probably be an absolute value and capped an epsilon below `pi / 2`.

The shots will get significantly harder to pull off. Ranged combat is rather weak, it needs some sort of a multiplier to avoid making it useless.
At the very least, the `missed_by == 1` (the total miss threshold) has to be roughly the same as it was before. Multiplying by 0.75 should keep the balance we have now, even if it doesn't perfectly reflect the documentation, comments and variable names.

**Comment by Crispy6** [comment]
The point about capping it is excellent. Once the shot has missed, elsewhere in the code the miss is already capped to 30 degrees.

I can multiply all of the headshot, critical, good hit, hit, grazing hit, etc. thresholds by 0.745 to keep the previous balance. I refuse to change the missed_by limit of 1 because that refers to 1 tile, meaning that it hits a different tile if and only if the missed_by is greater than 1.

**Comment by Coolthulhu** [comment]
> I can multiply all of the headshot, critical, good hit, hit, grazing hit, etc. thresholds by 0.745 to keep the previous balance.

Won't work for grazing hits, because it would require grazing hits at ~1.3 `missed_by`, which is more than a total miss.

> I refuse to change the missed_by limit of 1 because that refers to 1 tile, meaning that it hits a different tile if and only if the missed_by is greater than 1.

I mean multiplying `missed_by` by a constant. `missed_by >= 1` can stay, but `missed_by = ran(dispersion*moa)*range` will need a constant multiplier.

**Comment by Crispy6** [comment]
I calculated grazing hits going from < 0.8 to < 1.07, which I had planned to just cut off at 1.0, but let me think about it for a few minutes.

I'd still rather fix accuracy somewhere else if it's too low, and I'm happy to do whatever work is needed.

**Comment by Coolthulhu** [comment]
The `projectile_attack` is used by:
* Throwing - this can get a buff
* Monster ranged attacks - the area ones really need a buff since they got hit hard by the new miss calculations
* Gun accuracy formula - this one should get roughly just the 0.75 multiplier on dispersion
* Shrapnel - this one can get a nerf, as it hits really hard

It should be enough to use a different multiplier on the `shot_dispersion` parameter.

**Comment by Crispy6** [comment]
How about I just leave the 0.745 exactly where it is, as well as leave the other strange unit conversion on the throwing and just change player::get_weapon_dispersion to use tangent of the dispersion capped to 30 degrees (1800 dispersion, which is more than I've ever seen anyway)?

That would meet the stated goal of fixing the tangent approximation without any huge balance changes, and touch incredibly few lines of code.

**Comment by Crispy6** [comment]
Try that. It uses tangent and breaks out the rest of the calculation error into two constants, one in `Creature::projectile_attack` and the other in `player::throw_item`.

Maybe if ranged is ever rebalanced those constants can go away.

**Comment by kevingranade** [comment]
What's the in-game benefit here? The way trajectories work is only a pantomime of how it really works, but I'm not sure this ends up meaningfully better.

**Comment by Crispy6** [comment]
@kevingranade 
One way uses correct math and the other is a hack and full of undocumented literals? Is that not enough?

One of the other collaborators gave a thumbs-up to the issue report.

**Comment by kevingranade** [comment]
So... no? If you were eliminating the scaling hacks it would be one thing,
but as far as I can tell all this does is replace one approximation of the
tangent function with another approximation of the tangent function with no
claimed or discernable game impact.
In other words, how do I test that this PR does what it's trying to do? If
that desired outcome is "nothing", why merge it?

**Comment by Crispy6** [comment]
Well, it replaces it with the actual tangent, not another approximation.

I wanted to rip the incorrect numbers out, but I took flak about the resulting balance changes, so basically I can't win. Sorry to waste your time.

**Pull request closed without merging**
