### PR TITLE
Clarifies the purpose and function of the megaveh mod

### PR DESCRIPTION
**Pull request by Regularitee**
Changed name (but not ID) and description of the megaveh mod, since old ones gave absolutely no indication of what the mod actually did.

### CODE REVIEW

**Comment by keyspace** [comment]
Add

> Closes #19902.

before it's too late!

**Comment by Asmageddon** [comment]
Wait... are you trying to tell me that the current fuel efficiency values are intentional? The ones where a 3 ton vehicle will use 15L of gasoline going between two cities, and electricity is 100% unviable for powering even (motor)bikes?

**Comment by keyspace** [comment]
@Asmageddon no, not intentional. See #19348, and issues/PRs referenced there.

**Comment by Asmageddon** [comment]
Thank god. Because I'm still outraged. It takes a full season for regular solar car to charge up to full, half the distance between cities to run out of juice, dunno about diesel, but gasoline consumption is 100% unsustainable even for a 700kg vehicle. And also, I don't think that minireactors work, though I'm not really sure.

**Pull request merged**
