### PR TITLE
Extended animal speech

### PR DESCRIPTION
**Pull request by Kenan2000**
#### Summary

SUMMARY: Content "Extended animal speech"

#### Purpose of change

In order to use and extend even more the code defined in `speech.json` for dogs, cats and horses

#### Describe the solution

Adds more speech variants for dogs, zombie dogs, cats, horses and zombie horses as well as adding proper sound emission by the animals via `PARROT` special attacks

#### Describe alternatives you've considered

Do nothing and keep the animals absolutely silent as they currently are

#### Testing

The animals are now actually emitting the `speech.json` sounds properly compared to their silent state before, it seems like I have not really messed up the original code in any way - only expanded what was already created

#### Additional context

This may be interesting for the developers and the contributors to maybe add even more sound variants for other animals - I found this quite important because I am adding sounds for the animals in my soundpack, but without mainlined speech for vanilla animals this is impossible, because the sound emission relies on the `speech` trigger, so no speech=no sounds, this is why I decided to make a PR 😃

### CODE REVIEW

**Review by kevingranade — CHANGES_REQUESTED** [review]
I'm not clear what the goal is here, you want a hook so your soundpack can trigger audible animal sounds? When? At random? When the monster is in danger? How often?

Once every 7 turns seems extremely common, especially since it costs the monster 100 moves when it triggers. This might be reasonable for dogs, but it's definitely not reasonably for the wide array of monsters you're applying it to here. To be clear, when this is applied to monsters that are a significant threat, you are nerfing those monsters by enabling this feature for them.

The current implementation also scans *all other monsters on the map* looking for danger, if most monsters have this flag, we can run into some noticeable performance problems.

You're setting all monster speech at the same volume, there's some very obvious differentiation that needs to be added there between these monsters.

**Comment by Kenan2000** [comment]
> I'm not clear what the goal is here, you want a hook so your soundpack can trigger audible animal sounds? When? At random? When the monster is in danger? How often?
> 
> Once every 7 turns seems extremely common, especially since it costs the monster 100 moves when it triggers. This might be reasonable for dogs, but it's definitely not reasonably for the wide array of monsters you're applying it to here. To be clear, when this is applied to monsters that are a significant threat, you are nerfing those monsters by enabling this feature for them.
> 
> The current implementation also scans _all other monsters on the map_ looking for danger, if most monsters have this flag, we can run into some noticeable performance problems.
> 
> You're setting all monster speech at the same volume, there's some very obvious differentiation that needs to be added there between these monsters.

Done, removed the "PARROT_AT_DANGER" and replaced it with "PARROT" due to the possible performance problems with the former and increased the cooldown significantly - once per 25 turns for dogs and horses and 20 turns for cats and kittens lest it should be annoying, changed and balanced volumes

The soundpack triggers sounds in any case as soon as it detects monster speech, yes - it will trigger real audible animal sounds, I believe that with the current updated cooldown of 20 and 25 the sounds won't be too annoying or repetitive and make enough sense

I'll be waiting if more changes are required, I wanted to add even more speech and sounds for other animals but I believe that foundation for now is enough - all dogs (and their zombie variants), all cats, and all horses (and their zombie variants as well)

**Comment by Fris0uman** [comment]
> Done, removed the "PARROT_AT_DANGER" and replaced it with "PARROT" due to the possible performance problems with the former and increased the cooldown significantly - once per 25 turns for dogs and horses and 20 turns for cats and kittens lest it should be annoying, changed and balanced volumes

But aren't you just re-implementing the issues fixed by #32831 but in an even worse version?

**Comment by Kenan2000** [comment]
> > Done, removed the "PARROT_AT_DANGER" and replaced it with "PARROT" due to the possible performance problems with the former and increased the cooldown significantly - once per 25 turns for dogs and horses and 20 turns for cats and kittens lest it should be annoying, changed and balanced volumes
> 
> But aren't you just re-implementing the issues fixed by #32831 but in an even worse version?

I am not really sure at this point what I should do - Kevin says that `PARROT_AT_DANGER` causes performance issues - so instead I've decided to swap it with `PARROT` and make the cooldown quite long, it can be made even longer to make animals just emit sounds once in a while - either this or keep animals silent as they were...

**Comment by kevingranade** [comment]
At this point I'm leaning toward keeping them silent, most animals don't wander around making noises for no reason, and even when they do, it's usually something you'd ignore (i,e, songbirds).
We can look into a system for animals making sounds when appropriate, but PARROT is not that system.

**Pull request closed without merging**
