### PR TITLE
Eliminate Self-Aware trait and replace it with sidebar widgets

### LINKED ISSUE #53473: Turning off the 'Self Aware' mutation does not turn off the ability to see exact Pain numbers
### Describe the bug

If the Self-Aware trait is taken during character creation, turning it off takes away the ability to see health on limbs, but not the exact number of pain. The vague terms for pain thresholds (Distracting, Minimal, Intense, Severe, etc.) aren't used as they would for normal characters, instead it's shown as the exact number.

### Steps to reproduce

1. Make a character with the Self Aware trait
2. Turn 'Self Aware' off in the 'View/Activate Mutations' section
3. Get hurt by any monster

### Expected behavior

When Self-Aware is not turned on, the exact pain number should be replaced with the vague terms as is for characters that weren't created with the Self-Aware trait.

### Screenshots

_No response_

### Versions and configuration

build type: windows-tiles-x64
build number: 2021-12-15-1210
commit sha: 373cf4e8d511e8773f6fbc52fa07c55d8ee2010a
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/373cf4e8d511e8773f6fbc52fa07c55d8ee2010a

(I've looked for any guides that told me exactly where the report the game makes in the debug menu goes, but the 'debug' note file I found clearly wasn't it as it was too long, so I went with the game version for this report)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Bugfixes "Eliminate Self-Aware trait and replace it with sidebar widgets"

#### Purpose of change

The Self-Aware trait is kind of goofy, and of minimal utility. If taken at character creation time, it comes with an "Activate" function that simply displays the current hidden health stat. The only other thing it does is display raw hit point and pain numbers in the sidebar, and bandaging window.

Resolves #53473 

#### Describe the solution

- Remove the `SELFAWARE` mutation from all code and data
- Remove all references to `SELFAWARE` from trait groups and scenarios in mods.
- Replace one `SELFAWARE` instance with `OPTIMISTIC`, for the "Meditation" hobby.
- Replace the trait with another one in an old regression test for #42853 (the Self-Aware trait itself was not actually relevant here).

Replace with widgets:
- Add `hitpoint_nums_top_layout` and `hitpoint_nums_bottom_layout` to sidebar JSON
- Implement new `widget_var` variables `health` and `health_text` in widget class
- Add `health_num` and `health_text`, which players may add to their sidebars by editing `sidebar.json`

There is already a `pain_num` widget that can display numeric pain values, which was the concern with the original issue #53473 

#### Describe alternatives you've considered

Inventing new ways to make the trait make sense and be more useful. Discarded the idea after consulting with Kevin and other developers; future development direction will make this trait not worth the effort of maintaining.

Previously considered moving it to a `DEBUG_SELFAWARE` mutation

#### Testing

~~Debug mutate the new `DEBUG_SELFAWARE` trait and see that it does what `SELFAWARE` has always done.~~ No longer applicable

Save a game with a character having `SELFAWARE`, then load it after this patch - error message is displayed as expected, saying the unknown trait will be ignored. The error does not reoccur after saving and loading again.

#### Additional context

Screenshot of custom sidebar with `hitpoint_nums_top_layout` and `hitpoint_nums_bottom_layout` added just below the regular HP bars:

image

Cropped shots of the `health_num` and `health_text` widgets with different health values:

image

Existing `pain_num` and `pain_desc` added to custom sidebar:

image

image

### CODE REVIEW

**Comment by mkrutov** [comment]
Is there any ingame non-debug non-nurse way to see your exact HP on your limbs?

Asking because super-low-HP characters benefit from this trait a lot, since when difference between '|||' and '|||||' is 3 points bars don't provide any useful information at all.

**Comment by nexusmrsep** [comment]
Does this imply that health stat can now be made visible for ex. in @ menu in a textified approximation form: very bad, bad, average, good, very good?

**Comment by Terrorforge** [comment]
> Asking because super-low-HP characters benefit from this trait a lot, since when difference between '|||' and '|||||' is 3 points bars don't provide any useful information at all.

Super-high-HP characters, too. Maybe it's just my weird little brain, but I really struggle to comprehend what ||\ means on a character with 171 hit points.

But I guess if it's staying as a debug trait, you can always just turn it on.

**Comment by mkrutov** [comment]
>maybe make small CBM with his effect is a good idea?
Yes, that would be awesome.

**Comment by wapcaplet** [comment]
I've added numeric versions of the graphical bodypart HP widgets for the custom moddable sidebar. I was planning to do this anyway in a future PR, but now is a good time to add them.

The HP numbers are not enabled by default, but you will be able to easily add them (or replace the graphs with numbers) by simply editing your `data/json/ui/sidebar.json` and adding `hitpoint_nums_top_layout` and `hitpoint_nums_bottom_layout` to the `root_layout_wide` widget:

```json
  {
    "id": "root_layout_wide",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "widgets": [
      "hitpoint_graphs_top_layout",
      "hitpoint_graphs_bottom_layout",
      "hitpoint_nums_top_layout",
      "hitpoint_nums_bottom_layout",
      "sound_fatigue_focus_layout",
      "stamina_speed_move_layout",
      "stats_layout"
    ]
  },
```

This is how it renders in the "Custom" section of the wide sidebars:

image

After #51438 is completed and merged, this will be something you can add/remove/toggle/rearrange like any other sidebar section. Encumbrance, warmth, and wetness numbers are coming soon too - no "Self-Awareness" required.

**Comment by Zireael07** [comment]
In that case, I don't think the move to a debug trait is necessary, just straightforward obsoletion.

**Comment by wapcaplet** [comment]
> Does this imply that health stat can now be made visible for ex. in @ menu in a textified approximation form: very bad, bad, average, good, very good?

No, hidden health value is not displayed directly anywhere else I'm aware of; there is only the hint when you wake up from sleep, from the `health_msgs.json` snippets, based on rough thresholds (+/- 10, 50, 100). I never got around to making a widget for hidden health, but it would not be too difficult to do.

**Review by Maleclypse — COMMENTED** [review]
Thanks for fixing mods while you were here.  Those looked good.  Not approving since there is more to this PR than the mod stuff I reviewed and I don't feel qualified to check those parts :)

**Pull request merged**
