### PR TITLE
Addition of heavy duty doors

### PR DESCRIPTION
**Pull request by Broken-Admin**
+ Addition of a heavy duty version of regular door
+ Addition of a heavy duty version of opaque door

### CODE REVIEW

**Comment by Broken-Admin** [comment]
I think I did it properly this time.

**Comment by BorkBorkGoesTheCode** [comment]
Are you using the GitHub web interface to do this, or the command line?

**Comment by Broken-Admin** [comment]
Command line, it's why I'm having a few errors here and there.

**Comment by Broken-Admin** [comment]
I'm slowly learning more and more, I'll get better as time progresses.

**Comment by rm-code** [comment]
You should try a rebase on top of master to get rid of all the unnecessary commits.

**Comment by rm-code** [comment]
You can simply push --force afterwards to update this PR.

**Comment by Broken-Admin** [comment]
B-but that's rape.

**Comment by rm-code** [comment]
No it's not. It's actually the exact reason why the `rebase` command exists ;)

Having a clean history has lots of benefits when it comes to bisecting and other nice git functionality. Github even allows maintainers to rebase PRs instead of merging.

Anyway, it's a suggestion.

**Comment by kevingranade** [comment]
@Broken-Admin not funny, please refrain from making rape "jokes" in this repository.

**Comment by Broken-Admin** [comment]
Sorry KG.

**Comment by Broken-Admin** [comment]
@rm-code Thanks by the way! I was just being a idiot.

**Comment by Broken-Admin** [comment]
I'm sorry I wasn't at during that point, I'm sorry for any offense I have cause. Looking back that was extremely out of line. Sorry is truely not enough, yet it is all I can say.

**Comment by Broken-Admin** [comment]
I had completely forgotten I had this PR, where are we at on it?

**Comment by ZhilkinSerg** [comment]
Marking as Stalled. Feel free to reopen it.

**Comment by mlangsdorf** [comment]
Is there a way to mark this as no longer stalled, but fixed by  #24065? It's confusing to have it stalled when similar changes have been merged.

**Comment by Night-Pryanik** [comment]
I just removed the Stalled tag.

**Pull request closed without merging**
