### PR TITLE
[Extra Mutated Scenarios ] Adds new mutation trees to mod starts 

### PR DESCRIPTION
**Pull request by Hellcommander**
#### Summary
Mods "[Extra Mutated Scenarios] Update to include new mutation lines"

Purpose of change
To update the mod to include the newer mutations and resolves issues like allowing players to give a mutant that doesn't have the right threshold a mutation that requires something they don't have.

Describe the solution
Manually updated it to allow people to be to choose newer mutations, prevent getting a threshold mutation that you are not at the threshold for, prevent being able to select a mutation that is flagged as invalid (it was part of a condition mutation that triggered it based on mood) and prevent issues like selecting a mutation  but being given a different mutation instead though this still happens (things would likely have to change in the code to fix this)

Describe alternatives you've considered
Testing
I've used it for multiple characters with no issues

Additional context
Didn't know how to implement the wildcard thing for chimera so threshold mutations are still limited to chimera on character gen

### CODE REVIEW

**Comment by Procyonae** [comment]
You're not meant to just delete the template and start over the changelog bot won't recognise your first line which should be something like
````
#### Summary
Mods "[Extra Mutated Scenarios] Update to include new mutation lines"
```

**Comment by Hellcommander** [comment]
thanks

**Comment by Hellcommander** [comment]
sorry missed it was using it to compare if there was changes updated branch with it removed

**Review by GuardianDll — APPROVED** [review]
looks good for me

**Pull request merged**
