### PR TITLE
Adding Glock 21 (.45), magazines and spawning

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Content "Adds Glock 21, chambering .45 ACP Ammo to the Glock family."

#### Purpose of change
Since we got the 17, 18, 19, 20 and 22, it would make sense to add the 21 as well. It uses .45 ACP ammo and usually uses a 13 round magazine. Values for lengh etc, were taken from the German Wikipedia.

#### Describe the solution
Hehe Glock 21 goes brrrrrr

#### Describe alternatives you've considered
there are no alternatives for a guy with a gun.

#### Testing
pow pow.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
You will need to add generic guns migrations for these.

**Comment by Lamandus** [comment]
> 
> 
> You will need to add generic guns migrations for these.

oh dang, I forgot. Working on it.

**Comment by LaVeyanFiend** [comment]
Don't forget to add these new magazines to the Vector SMG's accepted magazines.

**Comment by Lamandus** [comment]
> 
> 
> Don't forget to add these new magazines to the [Vector SMG](https://kriss-usa.com/item/vector-smg/)'s accepted magazines.

even if it is a different caliber? Our glock is .45. The Vector is 9x19.

I am not that into guns to understand the relation.

**Comment by LaVeyanFiend** [comment]
There are two versions.
image

**Comment by Lamandus** [comment]
oh right, I just saw it. Adding it

**Pull request merged**
