### PR TITLE
Better ter/furn copy-from support

### LINKED ISSUE #54702: Inheritance bug
### Is your feature request related to a problem? Please describe.

i have a terrain, which has `TRANSPARENT` flag, but few another terrains, that `copy-from` the original one has lack of this flag

### Solution you would like.

to inherit terrain flags from original node

### Describe alternatives you have considered.

write about this inheritance thing on the github wiki

### Additional context

the original terrain
```json
{
    "type": "terrain",
    "id": "t_deck_coating_no_roof",
    "name": "deck coating",
    "description": "Thick metal covering of a hull, covered with a military grade epoxy mix.",
    "symbol": ".",
    "looks_like": "t_pavement",
    "color": "dark_gray",
    "connects_to": "METALFLOOR",
    "move_cost": 2,
    "flags": [ "FLAT", "ROAD", "TRANSPARENT" ],
    "bash": {
      "sound": "thump",
      "ter_set": "t_null",
      "str_min": 500,
      "str_max": 1000,
      "str_min_supported": 200,
      "items": [
        { "item": "steel_lump", "count": [ 1, 4 ] },
        { "item": "steel_chunk", "count": [ 3, 12 ] },
        { "item": "scrap", "count": [ 9, 36 ] }
      ]
    }
  },
  ```
  
example of copy-from terrain
```json
{
    "type": "terrain",
    "id": "t_deck_coating_no_roof_r",
    "name": "red deck coating",
    "description": "Thick metal covering of a hull, covered with a military grade epoxy mix, and painted in red color.",
    "copy-from": "t_deck_coating_no_roof",
    "looks_like": " ",
    "move_cost": 2,
    "symbol": ".",
    "color": "red"
  },
```

expectation
image
reality
image

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Infrastructure "Better ter/furn copy from support, remove legacy alias code"

#### Purpose of change
copy-from good
Fixes #54702

#### Describe the solution

More copy-from support:
  `"symbol"` supports copy-from
  `TRANSPARENT` flag inherits correctly
  `"flags"` support extend/delete
  `"connect_groups"`, `"connects_to"` and `"rotates_to"` support copy-from

Removes remaining redundant aliases and alias code
Removes `LINE_OXOX` and `LINE_XOXO` handling replacing it with better generic unicode character handling. Currently changes symbols to what they were already using but when I add abstracts I'll probably make most walls # instead. (The symbol only affects unconnected instances of the terrain/furniture)
Removes legacy `connects_to`/`rotates_to` flag support enabled by #73415
Merges some duplicate code in `ter_t::load` and `furn_t::load` into `map_data_common_t::load`

Will attempt to ensure you can overwrite `"bash"`'s, `"deconstruct"`'s and `"pry"`'s `"ter_set"`/`"result"` without redefining the other values for stuff like doors where that's the main difference while allowing ie `"bash": {  }` to correctly default all the fields inherited.
May add tests to check stuff like the above works.
~~Will likely update inheritance docs~~ Nvm I forgot how atrocious our existing inheritance docs were for a moment

Was originally going to add abstract terrains/furniture to cut alot of json bloat but I'll do that in future PRs bc it was getting too big to review

~~May remove legacy connects_to/rotates_to flag support if applying the necessary JSON changes in this PR isn't too much otherwise I'll leave it till after the follow-up PRs adding copy-from to alot of existing ter/furn~~
~~Will add abstract versions of basic terrain (probably just walls/windows/doors/floors/roofs for now)~~
~~Moves painted walls to their own file bc they were taking up half the file~~
~~Corrects several discrepancies between similar terrains~~

#### Describe alternatives you've considered
Deduplicating parts of `ter_t::check` and `furn_t::check` into `map_data_common_t::check` but `map_data_common_t` doesn't have the respective ids so the debug messages would be less useful.
I found an extern list of traps I missed while doing #72766 and #72834 which I'll remove in a separate PR

#### Additional context

I'd still like to make paint metadata instead of needing to have individual terrains/furniture but the save/load side of things isn't easy

NTS: Check using copy-from with an id of the wrong type (ter with furn or vice versa) throws an error. (While this could theoretically be supported I don't think it would be a good idea)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
What do you mean by paint meta data? My interest stems from the issue of "terrain" completely overwriting information about the actual terrain, and thus making it impossible to restore the actual terrain when the "terrain" is removed (you have to hard code some best guess).
By the way, if you find some way to associate paint info to terrain, I assume the logic would also apply to carpets?

**Comment by Procyonae** [comment]
Basically I have a local branch that makes it so piant can be applied to any terrain with a PAINTABLE flag (and consequently removed by a chipper still) without changing the id of the terrain itself. For mapgen I think I'm looking at doing it as a `"colour": { "!": [ "blue" ] }` type thing but autogenerated ids might make sense too (so t_not_painted_blue). I just haven't looked into how to add a new field to track it in savefiles yet and am mildly scared of breaking everyone's saves.
I also needed 
It's been a minute since I looked at it but I imagine making it handle furniture too wouldn't be that bad it'd just need to prompt you in the case of both a PAINTABLE terrain and furniture on one tile.
Idk how carpets should be handled tho.

**Comment by I-am-Erk** [comment]
Can we also inherit colour? I see no reason to have to repeat it every time.

**Comment by Procyonae** [comment]
> Can we also inherit colour? I see no reason to have to repeat it every time.

Yes?

**Comment by Procyonae** [comment]
Ok going through all our ter/furn in this PR is probably a bit stoopid I think I'll dial this back to just C++ and do abstract/copy-from stuff in seperate follow-up PRs

**Comment by Procyonae** [comment]
Ok the changes to bash and deconstruct are getting a bit much I think I'm going to scale back the PR a lil by reverting them and then just finalising what I have and then I'll attack them separately later

**Comment by Night-Pryanik** [comment]
Closing as stale. If you wish to continue working on this, ping me to reopen.

**Pull request closed without merging**
