### PR TITLE
Changed in recipes

### PR DESCRIPTION
**Pull request by kekwlboy12469**
#### Summary
 Bugfixes"changes the issue regarding recipes of battery mistake"
#### Purpose of change

#78641
Mistakes in battery recipes
#### Describe the solution
well i corrected the issue now well i have copied battery recipes from vanila to innawood in new file and i also edited vanila recipes cutting it down to only car battery only 
#### Additional context
corrected the file data\json\recipes\electronics\toolmod.json
created a new file  data\mods\innawood\recipes\battery recipes.json

### CODE REVIEW

**Comment by Karol1223** [comment]
Please lint your changes instead of just closing the bot's suggestions.

**Comment by RenechCDDA** [comment]
Linting is *mandatory* for your work to be merged, it cannot be merged without.

You can review the [json style doc](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md) for a variety of ways to do that. The bot here also automatically opens suggestions to apply linting. Pressing "resolve conversation" does not apply them, you must actually apply them.

**Comment by IdleSol** [comment]
What is the reason for removing these recipes from the game:
- battery_ups (UPS conversion mod)
- battery_bionic (bionic power conversion mod)
- magazine_battery_mod (battery compartment mod)
- magazine_battery_light_mod (light battery mod)
- magazine_battery_medium_mod (medium battery mod)
- magazine_battery_heavy_mod (tool battery mod)

The thread was only talking about batteries, not modifications for instruments. Is this a mistake or am I just not aware of it? Perhaps there was some discussion?

**Comment by kekwlboy12469** [comment]
> What is the reason for removing these recipes from the game:
> 
> * battery_ups (UPS conversion mod)
> * battery_bionic (bionic power conversion mod)
> * magazine_battery_mod (battery compartment mod)
> * magazine_battery_light_mod (light battery mod)
> * magazine_battery_medium_mod (medium battery mod)
> * magazine_battery_heavy_mod (tool battery mod)
> 
> The thread was only talking about batteries, not modifications for instruments. Is this a mistake or am I just not aware of it? Perhaps there was some discussion?
yup u only mentioned about it under issue section

**Comment by IdleSol** [comment]
>UPD. And my personal opinion. If you remove battery recipes, then remove all recipes, including tool batteries. (Recipes for car batteries, should be left in).

I must have mistranslated or misspoken. I was talking about removing the battery recipes. In addition to the recipes for light and medium, I was referring to recipes for heavy batteries, which are now called tool batteries.
- heavy_battery_cell
- heavy_plus_battery_cell

But I wasn't talking about modifications that allow the tool to be powered by other types of batteries.

Especially do not remove the modification that allows you to power instruments from bionics or UPS. Such issues should be better brought up for discussion.

P.S. Just in case. I am not the developer of the game.

**Comment by kekwlboy12469** [comment]
ahh got it i will work on that then

**Pull request closed without merging**
