### PR TITLE
Ice cream shop roof

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
```SUMMARY: Content "Ice cream shops now have a roof."```

#### Purpose of change
I wanted to help with the ongoing roof project.

#### Describe the solution
Ice cream shops now have a (small) roof. There's nothing of note that appears up there beyond the normal roof stuff.

#### Describe alternatives you've considered
Adding a much larger roof, with struts to support it, so the eating area out front would be enclosed from the elements. The ice cream shop is very weirdly proportioned compared to other buildings, and not much can fit up there.

#### Additional context
ahc creem shawp
image

### CODE REVIEW

**Comment by LovamKicsiGazsii** [comment]
You should put a roof over these brick walls. 
what

**Comment by Ilysen** [comment]
I wasn't quite sure how to handle that; a 2x1 protrusion would look really odd. Should it be a 2x2 square? Just the protrusion anyway?

**Comment by LovamKicsiGazsii** [comment]
> I wasn't quite sure how to handle that; a 2x1 protrusion would look really odd. 

That's still better than falling inside a brick wall.

**Comment by Ilysen** [comment]
I found that solar units made sense, and look pretty nice, so I've updated the jutting portion to have them.

**Comment by curstwist** [comment]
> 
> 
> I found that solar units made sense, and look pretty nice, so I've updated the jutting portion to have them.

yeah that looks good. : )

**Comment by Ilysen** [comment]
Oh right@
@curstwist You're the person in charge of the roof project, so is there any work you want to do personally? I've been considering helping out a bit but I don't want to intrude.

**Comment by curstwist** [comment]
> 
> 
> Oh right@
> @curstwist You're the person in charge of the roof project, so is there any work you want to do personally? I've been considering helping out a bit but I don't want to intrude.

just the craft shops, since I did the original floors too.  I have some ideas.  If you want to do more, that's great.  We could split them by category or something so we don't do the same ones, or message me somewhere with ones you're planning on doing.

**Comment by Night-Pryanik** [comment]
The infrastructure on the roof has to be serviced somehow, but there is no way to get to the roof, except for using the downspout. I suggest adding stairs or ladder.

**Comment by ZhilkinSerg** [comment]
There is no way to get to the roof.

**Comment by Ilysen** [comment]
I'll put in a ladder. I should mention that the vast majority of roofs don't really seem to have an obvious access point, either.

**Comment by kevingranade** [comment]
I don't know what the decision process should be offhand, but I don't think every roof needs built in acess.

**Pull request merged**
