### PR TITLE
Train relevant skills when installing/removing vehiclep parts

### LINKED ISSUE #18413: Part installation and removal should train more than just mechanics
It should instead train `install_requirements` and `remove_requirements`

See #18378

### PR DESCRIPTION
**Pull request by mugling**
Fixes #18413

### CODE REVIEW

**Comment by mugling** [comment]
@Rivet-the-Zombie also preferably this if you have the time as I have a dependent branch to push

**Comment by Rivet-the-Zombie** [comment]
Something here isn't working properly. I'm not seeing any skill percentage improvements at all when I install and remove vehicle components. Also the 'skills required' header isn't displaying properly: in place of the skill(s) it reads `%2$s %3$i`.

**Comment by mugling** [comment]
> Something here isn't working properly. I'm not seeing any skill percentage improvements at all when I install and remove vehicle components.

Odd, I thought I checked that - let me take a look. What are you trying to install?

Also the 'skills required' header isn't displaying properly: in place of the skill(s) it reads %2$s %3$i.

Separate bug reported earlier by @Coolthulhu. What OS?

**Comment by mugling** [comment]
Works for me. By any chance do you have a level 10 debug character trying to remove a level 2 part because the grants you almost no xp. Spawn a basic vehicle, debug mechanics to 2 and start removing parts from it and you should level up

**Comment by Rivet-the-Zombie** [comment]
>Odd, I thought I checked that - let me take a look. What are you trying to install?

Steel frame, light wooden frame.

>What OS?

Windows 7.

>By any chance do you have a level 10 debug character trying to remove a level 2 part

No, I had level three in all skills.

**Comment by mugling** [comment]
Can you check removal works. I'll run a test locally for installation

**Comment by mugling** [comment]
That might be why - steel frames are both `mechanics 1` to remove and install so if you are level 3 you only get a tiny xp bonus (often less than 1%). Try setting your skill to 1 and you should see there is a much bigger improvement.

Install/remove balance we could tackle in a separate PR as not all are balanced

**Comment by Rivet-the-Zombie** [comment]
>Try setting your skill to 1 and you should see there is a much bigger improvement.

That was indeed the case.

**Comment by mugling** [comment]
We need to go through vehicle install/remove requirements and restore some sanity. Less duct taping of engine blocks

**Pull request merged**
