### PR TITLE
comestibles.json: invalid material type, s/veggie/veggy/

### PR DESCRIPTION
**Pull request by jomat**

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Remove material types fixes, and it's good.

**Comment by Soyweiser** [comment]
So, is it veggie or veggy? As in, in English. (My spellings-checker says it is veggie).

**Comment by Leland** [comment]
American here, have literally only ever seen it spelled "veggie"

**Comment by illi-kun** [comment]
Closing due to inactivity: material changes should be removed since they're done in another pr mentioned above. No need to block trivial spelling fix by this pr.

**Pull request closed without merging**
