### PR TITLE
Rewrite throwing

### LINKED ISSUE #20414: Throwing is too good
Throwing got all the buffs that aiming got, but without any requirements to aim.
It also uses the old XP formula, back then when guns were incredibly inaccurate even when aimed. That old formula scales with accuracy. Result is that you can gain throwing 7 before your melee reaches 3 or so.

The only thing preventing throwing from being the ultimate hulk killer is the UI issues of having to re-select the item over and over.
Which is pretty much the worst possible situation when it comes to balancing - balancing with tedium (unintentional, but still).

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #20414 

Throwing was too strong because it wasn't updated for the new dispersion calculations. It resulted in trivial headshots by nearly-untrained characters and huge XP gains for easy, repeatable actions.

Changes:
* Items get a separate stat block for thrown damage. Items that don't have it only keep bashing damage
* Thrown items may randomly (depends on skill) deal melee damage, if it's higher than their thrown damage
* Dispersion increased, random effects dropped (dispersion is related to variance, so it shouldn't be rolled)
* Dispersion is partially increased by target's dodge. I need better numbers here so that it always makes sense
* Volume effects on dispersion rewritten to include the milliliter volume stat
* Dodgy critters prevent proper aiming, increasing dispersion when aiming at them
* Point-blank and 1 distance throws penalized heavily depending on target's dodge. Still, for many targets, point-blank and 1 distance throws may be the best

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Throwing data may be required in mod content as well. @pisskop, @Noctifer-de-Mortem, and @chaosvolt will also need to be notified to update their mods.

**Comment by Coolthulhu** [comment]
Updated

**Comment by DangerNoodle** [comment]
When this is merged, it might be viable to increase the ranged damage of the atlatl to be comparable to the listed throwing damage, since ranged weapons that use the throwing skill already have issues making them inferior to throwing by hand, though this pull request narrows this gap in effectiveness. I already had planned to make some updates after noticing some recipe redundancies in More Survival Tools.

Related, should thrown ammuniton maybe have an adequately high "preserve on impact" percentage when fired, since throwing them by hand will have a 100 percent chance of the ammunition remaining intact?

**Comment by kevingranade** [comment]
Everything looks great except for:
> Thrown items may randomly (depends on skill) deal melee damage, if it's higher than their thrown damage

If something is capable of dealing higher damage with skill when thrown, model that and give it a difficulty to unlock the higher thrown damage, but a chance of upgrading thrown damage to (sometimes extremely high) melee damage just based on, "this player is really good at throwing" doesn't make any sense.

**Comment by Coolthulhu** [comment]
In majority of cases, it does.
For most weapons, the throw penalties will prevent them from hitting well. For example, thrown chainsaw will just glance of things, dealing a tiny fraction of melee damage.

Exceptions are slicing weapons. Should I special-case those?

**Pull request merged**
