### PR TITLE
add misc_repairkit to toolbox deconstuct components

### PR DESCRIPTION
**Pull request by ghost**
It takes a basic repair kit to make a toolbox but you don't get one when you disassemble a toolbox. This fixes that.

### CODE REVIEW

**Comment by BevapDin** [comment]
Do we actually need a separate disassemble recipe? It can be used to convert a stone knife into a pocket knife: make the toolbox with the former, disassemble it into the later. It would probably better to make the original recipe reversible and remove the disassemble recipe.

**Comment by mauledbybears** [comment]
That works either. Cleaner than having a disassembly recipe.

**Comment by Coolthulhu** [comment]
Due to how toolbox recipe is ordered, the returned knife is a switchblade, which is more of a weapon than a tool.
Should be reordered so that it returns pocket knife, like it did before.

**Comment by BevapDin** [comment]
This fixes another bug: the disassemble recipe would give back a hammer, but the assemble recipe did not require a hammer.

**Pull request merged**
