### PR TITLE
Add uses for trash bags

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Content "Add uses for trash bags"

#### Purpose of change

Adds a few uses for the garbage bag, which was previously a junk item. These bags are commonly cited by hunters and bushcraft types as a useful tool. Also changed the bag from gray to black, as most of these bags are black IRL.

#### Describe the solution

The bags can now be deconstructed to create plastic sheets or crafted into makeshift ponchos. The makeshift poncho keeps your head and torso dry.

I made the poncho require Cutting 1 as you're trying to cut the smallest holes possible to keep water out, but deconstruction doesn't need a tool as you can easily rip these things with your hands or teeth.

#### Describe alternatives you've considered

55 gallon bags (contractor's bags) could be added for even more utility, such as crafting shelters or more complex clothing.

#### Testing

Spawned a survivor, found a bag, deconstructed it. Found another bag, crafted it into a makeshift poncho, put it on.

#### Additional context

None

### CODE REVIEW

**Comment by actually-a-cat** [comment]
A plastic sheet is 20x the volume and 30x the weight of a garbage bag, so it seems to be a very different kind of plastic, and a 1:1 conversion might be a bit of a stretch.

If I may suggest an alternative use for garbage bags, they could be a substitute for plastic bags in recipes. Those are a more similar material, and annoying to get in quantity.

**Comment by fairyarmadillo** [comment]
That sounds to me more like plastic sheets have a nonsensically high volume and weight that needs fixing. Who has a single plastic sheet in their garage that weighs a whole kilogram?

The plastic sheet as it exists in CDDA is used as a waterproof tarp big enough to cover a single ground tile. That's what people use hefty bags for, and that's also consistent with all the crafting recipes that currently use plastic sheets.

**Comment by Inglonias** [comment]
The most sensible thing here would be to clarify plastic sheets. When I think of "plastic sheets" like the ones in the game, I think of something like [office floor mats](https://www.staples.com/Staples-Flat-Pile-Carpet-Chair-Mat-36-x-48-Lip/product_447139) or something similar - A hard plastic thing, in other words.

What I'm trying to say is that I think of them as fundamentally different materials, and they should behave as such.

**Comment by fairyarmadillo** [comment]
They are definitely not hard plastic floor mats, as they are used mostly as waterproof lining for bags.

**Comment by fairyarmadillo** [comment]
I_Am_Erk introduced plastic sheets in this PR [#30823](https://github.com/CleverRaven/Cataclysm-DDA/pull/30823) and there he specifically refers to rolls of 6ml plastic.

I think that fits with what we have [here](https://www.homedepot.com/p/HDX-20-ft-x-100-ft-Clear-6-mil-Plastic-Sheeting-CFHD0620C/204711640) and is fairly represented by a garbage bag. The only remaining discrepancy is the amount of material.

I don't think the item that is currently implemented accurately represents an entire roll of this stuff, which should be enough to make many tents/waterproofed bags/groundsheets/etc and not just one. I've altered the existing item so that it more accurately represents a single sheet of this kind of plastic. If someone wants to go through the itemgroups and properly add rolls of the stuff (a bag with 9 of these sheets inside would work) that would be appropriate, but it's beyond the scope of this PR.

**Comment by fairyarmadillo** [comment]
I went ahead and added small boxes of plastic sheets to a couple of relevant itemgroups so survivors can find single sheets that have been used, or entire rolls on store shelves. This should hopefully clarify any remaining confusion around the original item.

**Pull request merged**
