### PR TITLE
[WIP] Road infrastructure mapgen

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- un-hardcoded `s_lot` and `s_gas` mapgen;
- updated city size and city distance parameters for gas stations;
- added and utilized mapgen palette for road infrastructure;
- minor changes to road stops layout;
- added a couple of city building generic buildings.

# Todo:

- [ ] - add vehicles, monsters and loot in `s_lot`;
- [x] - jsonize `s_gas` layout;
- [ ] - add vehicles, monsters and loot in `s_gas`;
- [ ] - use palette for rural gas station;

# Screenshots:

__Gas Station__

image

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
Where's the gas station?

**Comment by ZhilkinSerg** [comment]
> Where's the gas station?

On my laptop in my kitchen - it was not commited yet :)

**Comment by BorkBorkGoesTheCode** [comment]
@ZhilkinSerg Do you have free time for developing this
?

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg Do you have free time for developing this?

I'm a little bit busy with my baby kid, also software installation to new PC also adds up. And I wanna wait for more updates to Mapgen Explorer. Feel free to pick this PR up if you want to.

**Comment by BorkBorkGoesTheCode** [comment]
Ok. How're you doing? Getting any sleep?

**Comment by ZhilkinSerg** [comment]
More than I expected, less than I wanted too :P.

**Comment by ZhilkinSerg** [comment]
> The door marked by arrow leads to the wall?

That is some poor city planning - those nasty neighbors blocked fire exit by their house. :)

**Comment by Night-Pryanik** [comment]
@ZhilkinSerg how about to PR only jsonification of gas station and parking lot, since you've already done this?

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg how about to PR only jsonification of gas station and parking lot, since you've already done this?

Loot and monster spawns are missing in those jsons. You can pick it up when I've stopped if you want to.

**Pull request closed without merging**
