### PR TITLE
Adds a recipe for making .380 ACP cases from .223 brass.

### PR DESCRIPTION
**Pull request by Greevv**
#### Summary
SUMMARY: Content "Adds recipe for making .380 ACP brass from .223 brass."

#### Purpose of change
Makes .380 brass easier to get in quantity.

#### Context
Here are the relevant cartridge dimensions from SAAMI. As you can see, the rims are nearly identical, close enough that it will function.
image
image

### CODE REVIEW

**Comment by dommon** [comment]
im sorry, what? we have 9x19mm luger (parablellum), 9x18m makarov and 9x17mm .380acp cases and youre making a recipe from **5.56 (.223)** cases?

nb, .380 is already upward compatible, makarov should be too (so you can shoot luger, makarov, .380acp from luger chambered gun, makarov and .380acp from makarov gun), and respective ammo recipes updated to take any longer cases as they can be easily shaved whilst loading

**Comment by Greevv** [comment]
Uh, I don't even really know where to start here. 9mm Makarov uses a larger
diameter bullet than Luger or .380, so it won't even chamber in a 9x19
pistol, let alone function. The rim and case dimensions of .223 are
coincidentally just right to be trimmed into a .380 case. You can't make a
.380 case from either 9x19 or 9x18. 9x19 won't work unless you turn the
case on a lathe and reshape the rim, and 9x18 won't work because as I said,
larger bullet. Length and nominal diameter are not the only things that
matter when it comes to compatibility. You can't trim a .45 LC into a .45
ACP because the case rims are totally different. You can't even trim a .45
ACP into a .45 GAP. In order to get that kind of compatibility it either
has to be done intentionally, or the stars have to align just right, as is
the case with .223 and .380. Don't try and correct someone when you don't
know what you're talking about.

**Comment by dommon** [comment]
sure matey, yet .380acp can be fired from luger - IN GAME, you need to come to some sense in the realism vs game mechanics, in this case fe account for 9x19 being tremendously common resource in game, 9x18 and 9x17 being largely irrelevant and .223 being quite valuable

**Comment by Greevv** [comment]
Well matey, you can fire a .380 out of a 9mm Luger IRL. It just won't
function 90% of the time in semi automatics and will split the case more
often than not in revolvers. I don't disagree with the sentiment that it's
a little unrealistic, but the guy who added it made it that way to keep the
cartridge relevant past the first 20 mins of gameplay. That one compromise
does not justify further bending of the gun system. If you want more
compatibility maybe you should use the generic guns mod.

**Comment by Rail-Runner** [comment]
Did you check if the recipe actually produces one casing rather than the whole stack? I think it needs to specify amount of casings created somewhere to not create whole stack.

**Comment by tenmillimaster** [comment]
@dommon, this isn't a gameplay thing, just a way to get 380 brass if that's what you want. If you don't like it in game, just don't make it then.

9mm mak itself is outside the scope of this PR, but Greev is right. it was intentionally designed to be too large (.365in) to fire out of a .355 barrel (9mm).

Realistically speaking, this addition is a good way to downcycle your spent 5.56 brass when the shoulder/neck is too damaged to reload again. 

Things fall apart, and it's best to get as much use out of them as you can, while you can.

Where were you when I made .460 brass craftable from 308 brass?

**Comment by Greevv** [comment]
> Did you check if the recipe actually produces one casing rather than the whole stack? I think it needs to specify amount of casings created somewhere to not create whole stack.

Not gonna lie, I literally just copied and pasted the .460 recipe and changed the items.

**Comment by Greevv** [comment]
Tested and working.
image

**Comment by esotericist** [comment]
Since Travis is no longer clear what even is a file, I can confirm that
*  this is correctly styled as per our standards
*  it loads correctly in game (as per Greevv's screenshot above)
*  it actually seems consonant with the quick research I've done

I dunno whether @Greevv or @tenmillimaster came up with the idea of using the cordless drill as an ersatz lathe for this, but it's clever.

**Pull request merged**
