### PR TITLE
[Magiclysm] Technomancer pain ignore spell

### PR DESCRIPTION
**Pull request by rty275**
#### Summary
Mods "Technomancer pain ignoring spell"

#### Purpose of change
Pain's effects on stats got jsonized, time to make a spell about it.

#### Describe the solution
This is a very niche spell, something that is only really good for breaking out of a death spiral, but very useful for that purpose, as it'll reduce your pain penalties to nearly zero at max level (can't go to zero, stat reductions have to be -1 at least from my understanding) but it only lasts a very brief amount of time. That said, if you're in any amount of severe pain, you'll recoup the move cost of casting it by not having your speed reduced for the duration of the spell, so long as its sufficiently leveled. 

#### Describe alternatives you've considered
Not making it?

#### Testing
Spell learned correctly, cast correctly, effect scaled with level correctly and was removed correctly at time limit, and scroll spawned in itemgroup correctly. Can't think of anything else?

#### Additional context
I'm a little curious about why pain stat reduction is always at least a 1, but it still fits the spell to make it imperfect even at max level.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Can it also cost bionic power? That way it mimics you having some machine inside you at least a power storage cbm.

**Comment by rty275** [comment]
It can, sure. I worry that just makes it a strictly worse Sensory Dulling CBM in that case though. Also I'm realizing I don't understand the lore on any spells costing bionic power at all, if bionics are coming exclusively from the exodii now.

**Comment by rty275** [comment]
Converting to draft so it doesn't get merged while we're talking about it.

**Comment by Maleclypse** [comment]
> It can, sure. I worry that just makes it a strictly worse Sensory Dulling CBM in that case though. Also I'm realizing I don't understand the lore on any spells costing bionic power at all, if bionics are coming exclusively from the exodii now.

Bionics don’t come from the Exodii exclusively in Magiclysm lore. Technomancers invented them. Just no one has run with that lore tidbit and done anything to add them back.  If you don’t have a sensory dulling cbm you don’t have any other option than this now would you?

**Comment by rty275** [comment]
Huh, I didn't realize Technomancers made them, that's a cool bit of lore. Maybe I should make an attempt at spreading them back around, though that sounds like a big undertaking. In any case, that's an idea for a different PR, I'll change this to bionic power then. Probably lower the cost too, because of the short duration

**Comment by rty275** [comment]
Right, I think that test failure seems unrelated? Not my area of expertise though, so if there's something I need to fix then let me knwo.

**Pull request merged**
