### PR TITLE
Add kitchen units as appliances

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

Content "Kitchen units can now be placed as appliances"

#### Purpose of change

The RV kitchen unit could be fitted to a vehicle, but not placed as an appliance, despite it making sense to do so.

#### Describe the solution

JSON edits.

#### Describe alternatives you've considered

None.

#### Testing

Placed a kitchen unit in my current game. Have been using it for cooking ever since.

#### Additional context

This is my first time adding an appliance, so please let me know if I've made any oopsies or not followed any conventions.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
I don't think these should be appliances, they're just worse ovens. We could perhaps have a hotplate appliance, but I don't think this should be an appliance.

**Comment by I-am-Erk** [comment]
I agree, I think the solution here is mainly to make a hotplate or electric stovetop appliance, and once we have water running through an appliance grid, a sink would be good too, but separate. Since we don't have water afaik, the kitchen unit doesn't really work as advertised when placed.

**Comment by pjf** [comment]
I'm not at all attached to this PR, my survivor just managed to scavenge a kitchen unit and I wanted to plug it in.

I'm happy to edit the description to note the sink doesn't work, or to just close this and have the kitchen unit appliance on my local branch.

**Comment by I-am-Erk** [comment]
I'd suggest closing this PR and making a hotplate appliance, one route to make a hotplate appliance could be to just put some countertop over the sink and use an RV kitchen set.

**Comment by pjf** [comment]
Aye aye! Closing this in favour of a hotplate appliance.

**Pull request closed without merging**
