### PR TITLE
Fixed up pipe combo gun recipe

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
Increased the number of pipes to 2, added fine hammering tool quality, and nerfed toolkit power usage.

### CODE REVIEW

**Comment by kevingranade** [comment]
Why two pipes?  Its a pipe rifle welded to an existing shotgun.

**Comment by BorkBorkGoesTheCode** [comment]
I had intended to turn the pipe combo gun into a Vierling configuration.

**Comment by kevingranade** [comment]
If you change it to vierlang you need to change the recipe then, if you change it now the recipe won't match the item.

**Comment by Coolthulhu** [comment]
Needs to lose that extra pipe or gain it in the result.

**Pull request merged**
