### PR TITLE
Add Molting for Exoskeletons

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Features "Add molting for exoskeleton mutations"

#### Purpose of change

Real-life arthropods periodically have to molt their exoskeletons, usually a few times a year. This is a process that begins to slow them down, during which time they typically seek shelter. Once the molt begins, they are helpless for a short time, then have severely compromised armor until their new chitin can sclerotize and harden via exposure to air or water.

Simulating this process for arthropod mutants adds to the body horror aspect, opens the door to new gameplay considerations, and is just a neat way to flex EOCs.

#### Describe the solution

Using the EOC system, mutants with CHITIN2 or CHITIN3 will begin molting about every 5 weeks. They're given a small debuff for roughly 24 hours which advises them that the molt is coming, then a much worse debuff for an hour or two as their exoskeleton begins to lock up completely, with clear and direct warnings to seek shelter. After that, they are immobilized for 5 minutes (CHITIN2) or 15 minutes (CHITIN3) and get some body horror-y messaging about emerging from their own skin.

Once the above process has completed, they lose their CHITIN2, and CHITIN3 mutations and are given molted versions of the same, which have greatly diminished protection values on the associated integrated items, but a bit less encumbrance as well (halved for CHITIN2, 2/3rds for CHITIN3, rounding up). They receive a few chunks of chitin to represent their old exoskeleton. After a day or so, the new exoskeleton hardens and they are back to normal.

In real arthropods, this post-molt period often leaves them in a near-helpless state as their muscles require a rigid exoskeleton to move, however Cataclysm arthropods and arthropod mutants are using endoskeletons composed of bone or endochitin, so we probably don't need to go that far.

There's also a CHITIN_MOLTED, which is only there to prevent molting mutants from magically losing their chitin in the unlikely event that they drink mutagen mid-molt and it tries to give them CHITIN2 or CHITIN3.

Additionally, a preexisting bug was discovered during this PR. CHITIN_FUR2, CHITIN_FUR3, and CF_HAIR were conflicting with the chitin mutations, meaning they would cancel your armor entirely to give you hair. This PR introduces a fix to this issue by giving the chitin_fur mutations their own type, BODY_ARMOR_MOD. This type can be used for mutations which don't actually provide armor, but rather modify mutations which do. 

With these changes, the CHITIN_FUR mutations can properly cancel each other as the mutant becomes hairier, and are not lost when upgrading chitin tiers via mutation.

#### Describe alternatives you've considered

I'm not attached to any of the numbers I've listed here, they're just what looked good to me in testing. The integrated CHITIN2 and CHITIN3 armors are half thickness and made of leather_arthropod instead of chitin and sclerotin, respectively, as that seemed logical to me, but they could be weaker if needed. If you've ever eaten a soft-shelled crab, you probably understand how weak a molted (and cooked, to be fair) crustacean really is.

The debuffs on molting are meant to be minor, molting_imminent is meant to be fairly devastating. I pinned the molt cycles at roughly five weeks because we run into the portal storm problem if they're too common, where they stop being cool and start just being an interruption to gameplay. The fifteen minute molt for CHITIN3 is based on a NOAA article about the Bering sea Tanner crab. https://www.fisheries.noaa.gov/alaska/science-data/alaska-shellfish-growth-research

CHITIN2 is faster to get out of because it's thinner, softer, and doesn't cover quite as much of the body.

#### Testing

I scaled all the molting timers down to be doable within a single day, then I successfully completed several molts with both CHITIN2 and CHITIN2+CHITIN3. I made sure that CHITIN1 wasn't molting on its own - it's soft like skin, so I imagine it can molt off in small fragments like human skin does.

I also gave CHITIN2 and CHITIN3 to an NPC and observed them successfully completing multiple molt cycles.

I rescaled the molting timers to their current weeks-long cycles and used debug to advance time until a molt began, then watched it resolve in the expected timeframe.

I also tried drinking mutagen while molting to ensure that the mutagen wouldn't improperly replace a freshly molted exoskeleton with a new one, or double them up, or anything like that. The freshly molted versions of the exoskeleton mutations are not purifiable, and behaved as expected - you can't use mutagen or purifier to replace or remove your exoskeleton while they're still hardening, but afterwards they go back to normal.

#### Additional context

If this PR is merged, it could easily form the basis for similar systems for other mutants. Mammals could shed and grow winter coats, and lizards could shed their skins.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
You could use the debug function to change time to test that your "normal" cycle kicked in when intended (but would obviously miss out on detecting any issues of premature molting during the time skipped).

This is just a reminder that this functionality exist, not a request for any particular testing.

**Comment by fairyarmadillo** [comment]
> You could use the debug function to change time to test that your "normal" cycle kicked in when intended (but would obviously miss out on detecting any issues of premature molting during the time skipped).
> 
> This is just a reminder that this functionality exist, not a request for any particular testing.

Thanks! I'll test that now.

image

Using this method, I was able to skip forward 24 days and then just manually wait. After 35 days total, I finally started molting, which is within the expected timeframe, but it looks like I went through the first pre-molt stage instantly rather than taking a day or two. This wasn't happening that I saw in earlier testing.

```
  {
    "type": "effect_on_condition",
    "id": "chitin2_molt_timer2",
    "recurrence": [ "1 day", "2 days" ],
    "condition": {
      "and": [
        { "u_has_effect": "molting" },
        { "not": { "u_has_effect": "molting_imminent" } },
        { "not": { "u_has_trait": "CHITIN3" } }
      ]
    },
    "effect": [ { "u_add_effect": "molting_imminent", "intensity": 1, "duration": "PERMANENT" }, { "u_lose_effect": "molting" } ]
  },
```
Do I have something wrong here? This EOC should add molting_imminent at the end of a randomly rolled 24 to 48 hours, right?

**Comment by crypticcollaborator** [comment]
Just want to chime in and say this is very thematic and I like the premise a lot.

**Comment by fairyarmadillo** [comment]
Alright, I've got the preexisting bug with chitin fur ironed out. It behaves properly now. Testing shows the molt cycles are all happening as they should and the integrated armor isn't breaking weight tests anymore, so it looks like it's all good to go.

**Comment by fairyarmadillo** [comment]
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> All valid mutations can be purified
(~[slow] ~[.],starting_items)=>       Given: mutation of ID CHITIN_FUR is valid and removable
(~[slow] ~[.],starting_items)=>        Then: a dummy mutation should cancel it or have the same type
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------

**Comment by sadenar** [comment]
Maybe post molting an insectoid/arachnid mutant could get a slight bonus to move speed? Because yes while the new exoskeleton is softer, wouldn't it be significantly easier and lighter to move with? I very much like the concept of the PR, but I just wanted to chime in with that slight suggestion.

**Comment by fairyarmadillo** [comment]
I could reduce the encumbrance on the integrated items in the post-molt period, which would speed the character up a bit.

https://www.youtube.com/watch?v=ysRwW7uUmco

**Comment by fairyarmadillo** [comment]
Redoing this PR to include all the new crab stuff.

**Pull request closed without merging**
