### PR TITLE
Animal Breeding Rate Adjusted to Season Length & Dog breeding delay increased to more accurate numbers

### PR DESCRIPTION
**Pull request by TimPollard**
#### Summary
```SUMMARY: Bugfixes "Slows dog reproduction to realistic levels and makes reproduction rate adjust based on season length"```

#### Purpose of change
Helps with, but doesn't completely fix, the various issues related to puppy overpopulation, such as: #25289, #25302, and #24852. (Especially with long season lengths.)

#### Describe the solution
Uses calendar::season_ratio() to adjust baby_timer. baby_timer is now number of days on a 91 day season (364 days) to match up with the grow times for plants.

All animals have had their baby_timer multiplied by 6.5 so that it will produce the same results on 14 day seasons as it used to, but slower reproduction on longer seasons.

The exception is dogs which have had their baby_timer increased as follows:

The baby_timer had been set for dogs to be equivalent of just over 2/3 of a season, which is the correct pregnancy period (~62 days in the real world), but didn't take into account the fact that dogs can only get pregnant when in heat, which only happens a couple of times a year typically.

Searching on the internet suggests and average of seven months between heats, with smaller dogs having heats more regularly, and larger dogs less regularly.

Values have been adjusted to 272 days for most breeds to represent  seven months plus 62 days, while smaller breeds have been set to 240 days, and larger breeds to 300 or 320.

#### Describe alternatives you've considered
baby_timer could have been left adjusted to 14 day seasons, which simplifies the code very slightly, but results in absurdities like 36 litters of puppies every year on 91 day seasons.

It seems more sensible to have it adjust based on season length.

#### Additional context
These links provide some real world values for dog reproduction:

http://animalpetdoctor.homestead.com/reproduction.html

https://www.vetwest.com.au/pet-library/reproduction-in-dogs-season-heat-oestrus-pregnancy-tests

### CODE REVIEW

**Comment by kevingranade** [comment]
Nothing should be scaling with season length.

**Comment by Robik81** [comment]
> Nothing should be scaling with season length.

Do I interpret it correctly that season is base time unit. Everything should be defined as `x per season`?

If an animal has litter 0.5 per season, it means it has litter 1x in 28 days in default season length and 1x 180 days in 90 days season length. And it is not scaling because it is constant against the season unit?

**Comment by kevingranade** [comment]
> Would I be correct in assuming that it would be best to adjust them for 14 day seasons?

Adjust for real world season lengths.

> Do I interpret it correctly that season is base time unit. Everything should be defined as x per season?

No, I mean durations should take the same number of days as they do in the real world and completely ignore the season length option.

**Comment by Robik81** [comment]
> No, I mean durations should take the same number of days as they do in the real world and completely ignore the season length option.

Not sure if it is such a good idea... for example, spring wheat takes 4 real months from planting to harvest, lets say 120 real days. If would take over 8 seasons / 2 game years on default settings from planting to harvest.

**Comment by paulenka-aleh** [comment]
Does it make sense to have seasons of 14 days long at all especially by default?

**Comment by kevingranade** [comment]
> Does it make sense to have seasons of 14 days long at all especially by default?

Nope

**Comment by DracoGriffin** [comment]
@kevingranade With the new seasons of 91 days, I think season scaling could be a suitable mechanism now for those that choose to play on different season lengths (like those that might cling to 14 days or otherwise). At least instead of the weirdness of (for example) plants dying in winter (based on reverted #24291 which might eventually return) / lasting for years or suggestions of "play on default 91 days", there is some acquiescence of normality supplied with the season scaling. It wouldn't affect anything on default (as most things are already based on 90/91 day seasons), and reduce potential issues/complaints in the future. Then at least any "weirdness" that might occur with shortened/variant season lengths can be met with "designed with 90/91 day seasons, so play default or accept the quirks".

Secondly, I think this PR should probably be split up between the season scaling mechanism and animal reproduction days (those could be ported over to #25423) especially with both PRs having very similar changes to dog reproduction values.

**Comment by DracoGriffin** [comment]
All of the other (other than dog) animal reproduction values probably should be ported and merged, otherwise they are still based off of the 14-day season length.

**Pull request closed without merging**
