### PR TITLE
Fix ghee triggering lactose intolerant allergies

### LINKED ISSUE #46321: Ghee should not set off lactose intolerance
Simple really, game even says it's "free from milk solids..."

It should not be flagged as "milk" after the process is complete.

That while the Wikipedia article for "Clarified Butter" is not a primary source, it says the following:

"....It has negligible amounts of lactose and casein and is, therefore, acceptable to most who have a lactose intolerance or milk allergy...."

As a moderately lactose intolerant person, butter is of little consequence, and ghee is of no objection whatsoever. Thus: Alternatively, perhaps make it suffer a greatly reduced lactose penalty?

### PR DESCRIPTION
**Pull request by Aerin-of-the-Toast**
#### Summary
Bugfixes "Prevent ghee from triggering lactose intolerant allergy"

#### Purpose of change

Fixes #46321 

#### Describe the solution

Added a line in the JSON entry for ghee to set its material to "oil", instead of borrowing "milk" from butter.

#### Describe alternatives you've considered

Making a new material entirely.

#### Testing

Made a character with lactose intolerant and spawned in ghee, no longer gets a warning about an allergy. Also, manually crafted ghee from butter using the standard recipe just to make sure it still worked and it does, no warning about an allergy.

### CODE REVIEW

**Comment by actual-nh** [comment]
Umm... none? That is problematic. You'll need to find an appropriate food material (if it's pure fats, then same as, well, other pure fats), as well as indenting it the same as the other lines (see the [JSON linter](https://dev.narc.ro/cataclysm/format.html) for one way to fix the indentation problem).

**Comment by jumjummju** [comment]
> Umm... none? That is problematic. You'll need to find an appropriate food material (if it's pure fats, then same as, well, other pure fats), as well as indenting it the same as the other lines (see the [JSON linter](https://dev.narc.ro/cataclysm/format.html) for one way to fix the indentation problem).

Hm, I thought I did the linting thing, I must've screwed something up, my bad. Also I only gave it no material off the suggestion of others in the discord, I'm not sure what material it actually would qualify as.

**Comment by actual-nh** [comment]
> > Umm... none? That is problematic. You'll need to find an appropriate food material (if it's pure fats, then same as, well, other pure fats), as well as indenting it the same as the other lines (see the [JSON linter](https://dev.narc.ro/cataclysm/format.html) for one way to fix the indentation problem).
> 
> Hm, I thought I did the linting thing, I must've screwed something up, my bad. Also I only gave it no material off the suggestion of others in the discord, I'm not sure what material it actually would qualify as.

Well, you could actually use literally "none" (not just nothing in between the brackets, but `[ "none" ],`), or - what I would suggest - "oil".

**Comment by jumjummju** [comment]
Alright, I switched the material to "oil" instead of nothing and I think I got the linting right this time. Also, I tested it with the new changes and everything seemed to work right.

**Pull request merged**
