### PR TITLE
Wearable binoculars

### PR DESCRIPTION
**Pull request by Cyrano7**
Adds a set of binoculars with a strap that can be worn on the torso. Basically strap goes around your neck like irl but in game binoculars are equipped to the torso.
Can be crafted much like the headlamp.
When broken down it gives you a set of binoculars (normal binoculars)
Added to same group as binoculars.

### CODE REVIEW

**Comment by Cyrano7** [comment]
I have a quick question. If you are wearing an item does it still count for has_amount or do I need or put a seperate (or is_wearing) there too in the player.cpp  file?

**Comment by Coolthulhu** [comment]
> I have a quick question. If you are wearing an item does it still count for has_amount or do I need or put a seperate (or is_wearing) there too in the player.cpp file?

It doesn't.
But don't add a separate item id check, make it a flag instead and change the old checks for ids into this flag too.

**Comment by mugling** [comment]
> Adds a set of binoculars with a strap that can be worn on the torso

The problem here is that the layering penalty would discourage use. The head torch PR didn't have this problem as it doesn't compete with anything and in any case we don't (but somehow should) penalise head encumbrance.

> Basically strap goes around your neck like irl but in game binoculars are equipped to the torso.

Agreed, the binoculars should be wearable. It's a shame when you find them in the first days loot but have no space to carry them - a situation in which you might accept a temporary increase in torso encumbrance.

> Can be crafted much like the headlamp

The head torch (and it's predecessor the wearable flashlight) were both craftable as the source item was also used in other existing recipes (eg. headlamps) and more have been since added.

I can't see your recipe getting much use as by the time your in a position use it you would be better crafting some storage clothing. Have you considered merely updating the existing binoculars to be wearable along with the changes suggested by @Coolthulhu?

**Comment by Rivet-the-Zombie** [comment]
>Have you considered merely updating the existing binoculars to be wearable along with the changes suggested by @Coolthulhu?

I'd like to second this.

**Comment by Cyrano7** [comment]
@Coolthulhu @mugling @Rivet-the-Zombie Those are some good suggestions actually. Adding a flag for scope type items would clean things up a bit. Should the pistol scope be added to this flag group? Moving the binoculars to the tool_armor file and making them all wearable maybe is a better idea. Thanks for the feedback everybody.

**Comment by Cyrano7** [comment]
Updated here: https://github.com/CleverRaven/Cataclysm-DDA/pull/14428

**Pull request closed without merging**
