### PR TITLE
Adjust the volume, weight and material of motor

### PR DESCRIPTION
**Pull request by kwl01skz**
#### Summary
```SUMMARY: Balance "Adjust the volume, weight and material of motor"```  

#### Purpose of change
Adjust the volume, weight and material of motor
before
Power： small > tiny > micro
Volume： tiny > small = micro 
Weight： tiny = 11 x micro
material： tiny ≈ micro
after 
small > tiny >= micro

#### Describe the solution
Ensure that the volume, weight and material of the motor are related to the power.

#### Describe alternatives you've considered
Modify a few formulations to make tiny motor useful.
Delete motor_tiny -- why do we add it?

#### Additional context
 I don't know how to make an item smaller than 0.25L.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
We added the tiny motor because it was useful to have a 2 HP motor, as well as the 10 HP small motor and 0.25 HP micro motor.

**Comment by Fris0uman** [comment]
While you're at it maybe you could adjust the weight and volume to be closer to real life values.

Here's the values I wanted to use originally,  it was before mlangsdorf rework and it broke the game but maybe now it would be ok to use them.

> `enhanced electric motor` is a like a Tesla engine : 780 HP, 175 kg and 250L [Tesla Model S Drive Unit](http://www.evwest.com/catalog/product_info.php?products_id=476)
> 
> `large lectric motor` is like one from a racing car : 420 HP, 90kg and 16L [AM Racing AMR Dual Stack 250-90 AC Motor](http://www.evwest.com/catalog/product_info.php?products_id=300)
> 
> `electric motor`  standard  electric car : 125HP, 68kg and 20L [Curtis 1238e-7621 HPEVS Dual AC-34](http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=170) (I don't know if it's really "standard" or not)
> 
> `small electric motor` motrobike : 15HP , 17kg and 5L [BLDC / PMSM brushless motor HPM-10KW](https://www.miromax.lt/en/m-6/c-39/c-45-brushless_bldc_motor_with_permanent_magnet/product-507-bldc__pmsm_brushless_motor_hpm-10kw_-_nominal_power10kw13kw__134ag174ag___650cm3#to_products)
> 
> `tiny motor` electric bike : 0.7HP , 5.8kg and 0.5L [Front 500w Heavy-Duty Direct-Drive Motor](https://www.ebikekit.com/collections/wheels/products/front-500w-heavy-duty-direct-drive-motor)

**Comment by Fris0uman** [comment]
Looking back at the [discussion](https://github.com/CleverRaven/Cataclysm-DDA/pull/24329) accompanying  those numbers I found this from sfsworms : 

> They seems about right. Maybe I just think you're overestimating the size od the tesla motor since it has that "bulge" on the side. Assuming the bulge is one third of the total size, I get 108 L.
>I also get something a bit bigger, around 30L, for the racing car.

So 108L for Tesla motor and 30L for racing car. 
As for the micro_motor I don't know but since it's only a crafting item and not vehicle part I guess it can stay as it is now.

**Comment by KorGgenT** [comment]
to answer your additional context, to make an item 100 ml would be ```"volume": "100 ml"```

**Comment by kwl01skz** [comment]
I need to adjust the recipe so that some small devices use tiny motors instead of small motors.

**Comment by kwl01skz** [comment]
> The Tesla motor is 400 kW or 530 HP, not 780 HP. It has about 4x the volume of the racing motor and I'm not sure which of the volumes you suggest for those parts is wrong but one of them is.
 
I found a motor for Tesla on a Chinese website. It used two motors and got about 570kw or 765HP.
In the game, the super engine uses the superalloy, so I think we can give it some extra benefits.

**Comment by mlangsdorf** [comment]
The Tesla motor from the EVWest catalog that Fris0uman linked to is explicitly 400 kW.  If you have some other site, you'll need to provide a link.

**Comment by kwl01skz** [comment]
1. The solution provided by Fris0uman.
2. Reduce change.
3. Make sure the micromotor is smaller than a small motor.

#### large electric motor
1. Increasing the volume, increasing the weight, and doubling the power are even more powerful.
[16L、90kg、420hp](http://www.evwest.com/catalog/product_info.php?products_id=300)
2. Increase volume
[20L、68kg、210hp](http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=297)
3. No change
3.75L、60kg、200hp

#### electric motor
1. Provided by Fris0uman, but its size is larger than "large", which I think is a bit strange.
[20L、68kg、125hp](http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=170)
2.  Compromise the solution. Increase volume and weight
[10L、22.7kg、59hp](http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=338)
3.  No change
1.5L、9.07kg、50hp

#### small electric motor
1. Increase volume, weight and power.
[7L、17kg、15hp](https://www.miromax.lt/en/m-6/c-39/c-45-brushless_bldc_motor_with_permanent_magnet/product-507-bldc__pmsm_brushless_motor_hpm-10kw_-_nominal_power10kw13kw__134ag174ag___650cm3#to_products)
2. Another model of the same brand adds volume and weight. The power has not changed.
[5L、7.45kg、10hp](https://www.miromax.lt/en/m-6/c-39/c-45-brushless_bldc_motor_with_permanent_magnet/product-500-bldc__pmsm_brushless_motor_hpm-5000b_-_nominal_power_5kw86kw__67hp115hp__400_cm3#to_products )
3. Just adjusted to be bigger than Tiny, there is no realistic reference. The advantage is that we don't have to modify the recipe for the handheld chainsaw.
 0.75L、1.25kg、10hp

#### tiny electric motor
1. Increase weight and reduce power.
[0.50L、5.8kg、0.7hp](https://www.ebikekit.com/collections/wheels/products/front-500w-heavy-duty-direct-drive-motor)
2. The volume is reduced and the power is reduced. This is a smaller, lighter skateboard motor . 480w~1152w.
[0.25L、0.67kg、0.65hp](https://item.jd.com/32385612512.html)
3. No change


### micro electric motor
There is no need to consider power, but the weight of the component is much larger than the finished product, so we should modify its recipe and possibly modify the volume.

**Comment by mlangsdorf** [comment]
So these are the numbers I get/prefer

Motor Size | Power (kW) | Volume (L) | Mass (kg) | Reference
-- | -- | -- | -- | --
Micro Electric Motor | 0.1 | 0.25 | 0.4 | No refe
Tiny Electric Motor | 0.75 | 0.5 | 5.8 | https://www.ebikekit.com/collections/wheels/products/front-500w-heavy-duty-direct-drive-motor
Small Electric Motor | 7.3 | 5 | 7.5 | https://www.miromax.lt/en/m-6/c-39/c-45-brushless_bldc_motor_with_permanent_magnet/product-500-bldc__pmsm_brushless_motor_hpm-5000b_-_nominal_power_5kw86kw__67hp115hp__400_cm3#to_products
Electric Motor | 37.3 | 9.7 | 27.2 | http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=339
"Obsolete" Large Electric Motor | 93.25 | 20.2 | 68 | http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=170
Large Electric Motor | 149.2 | 17.4 | 68 | http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=297
Enhanced Electric Motor | 313.3 | 26.5 | 81.6 | http://www.evwest.com/catalog/product_info.php?products_id=300
Super Electric Motor | 400 | 111 | 133.8 | http://www.evwest.com/catalog/product_info.php?products_id=476

The solar car replaces its current 2 electric motors with a single obsolete large electric motor, and the bubble car replaces its 3 electric motors with a single large electric motor.  The atomic sports car replaces both of its enhanced electric motors with super electric motors.

Since we're changing the mass and HP of some test vehicles, the vehicle_efficiency and vehicle_drag tests will need to be updated.

**Pull request merged**
