### PR TITLE
beans and rice fix

### PR DESCRIPTION
**Pull request by johnrdconnolly**
#### Summary

SUMMARY: Bugfixes "Fix deluxe veggie beans & rice causing engorged"

#### Purpose of change

With a volume of 0.75L deluxe vegetarian beans & rice causes engorged from a single serving.

#### Describe the solution

Lower volume from 0.75L to 0.50L

#### Describe alternatives you've considered

None

#### Testing

Spawn in and eat some deluxe vegetarian beans & rice. Used to cause engorged, doesn't cause engorged after change.

See images in additional context

#### Additional context
Before fix
engorge pre
engorge post

After fix
fix pre
fix post

### CODE REVIEW

**Comment by I-am-Erk** [comment]
The problem here is less that the volume is high and more that the weight is low. The more calories per gram a food has the more filling it is. 1 cup of cooked rice weighs 250g and 1 cup of cooked beans is 60 or more, so at 3 cups the original recipe should weigh at least 310g, and that's not counting whatever the remaining 250mL was made up if

**Comment by johnrdconnolly** [comment]
> The problem here is less that the volume is high and more that the weight is low. The more calories per gram a food has the more filling it is. 1 cup of cooked rice weighs 250g and 1 cup of cooked beans is 60 or more, so at 3 cups the original recipe should weigh at least 310g, and that's not counting whatever the remaining 250mL was made up of

soooo you are saying a weight of 400g would be more reasonable? I just tested and it solves the problem just fine too.

Also, in game a single portion of cooked rice weighs in at only 62g. And cooked beans at 270g. i'm guessing you just mixed those up..?

**Comment by I-am-Erk** [comment]
I looked at the irl weight of 250ml cooked rice and cooled beans. Don't assume those values are correct in game... The calories of a serving seem to be pretty good but weight and volume are all over the place.

**Comment by I-am-Erk** [comment]
I looked at the irl weight of 250ml cooked rice and cooled beans. Don't assume those values are correct in game... The calories of a serving seem to be pretty good but weight and volume are all over the place.

**Comment by johnrdconnolly** [comment]
hmmm... i eat rice and beans irl almost every day, and i have a scale. I should just start weighing and measuring my food when I eat and update game values where I can...

**Comment by johnrdconnolly** [comment]
I will weigh a cup of cooked rice and a cup of cooked beans, and then another cup of veggies, and update the value accordingly tomorrow.

As for other food weights, I just may start weighing out my food and update more values.

**Comment by I-am-Erk** [comment]
That's a great idea! The only trick to that is making sure the weight *and calories* are correct, and it's still tricky making sure they correspond to the size of portion the recipe makes. However it would be a huge amount better than what we've got! If you do something like that I strongly recommend adding comments saying you did it so we know your data are real world. Eg:

`"//": "Weight based on real world measurement of 1 cup of beans and rice",`

**Comment by johnrdconnolly** [comment]
I have updated the values based on portions of 250ml for all the rice and bean containing recipes based on real world measurements for calories and weight. Also added comments stating the details.

**Comment by bloodraven983** [comment]
great job!

**Comment by ZhilkinSerg** [comment]
That breaks recipe permutation tests - need to change result calories, ingredient calories or ingredients counts.

**Comment by johnrdconnolly** [comment]
> That breaks recipe permutation tests - need to change result calories, ingredient calories or ingredients counts.

So, those changed values were based on real world measurements/estimates. Should these values really be altered to fit the test, or should the test possibly be reworked to accept the values since the are real world values? Can I get more details on how these broke said tests?

I ask because I plan to reevaluate recipes in the future for accuracy, and this could have the same effect in the future.

**Comment by anothersimulacrum** [comment]
Test should be altered. See #41870

**Pull request merged**
