### PR TITLE
Adds bio blade CBM to Trader_Avoid [Not Tested]

### PR DESCRIPTION
**Pull request by Dozed12**
*Untested, I simply did what was suggested.
#8171

### CODE REVIEW

**Comment by KA101** [comment]
It's a start, and futzing about with inventory can wait for post-0.C.

**Comment by Marrim** [comment]
What is the purpose of adding the CBM to Trader_Avoid?
Only the actual blade (bio_blade_weapon) should be excluded, no?

**Comment by Rivet-the-Zombie** [comment]
>What is the purpose of adding the CBM to Trader_Avoid?
Only the actual blade (bio_blade_weapon) should be excluded, no?

Correct. What's up with this one?

**Comment by KA101** [comment]
OK, I'll revert it.  Trying to keep things moving, missed that the weapon was already in and frankly I'm not sure how I'd appreciably test that NPCs weren't carrying something given the amount of stuff we have for them to carry.

**Pull request merged**
