### PR TITLE
Buffed 7.62x25hot and 7.62x25mm Type P

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
I have increased the Pierce rating by 5.

### CODE REVIEW

**Comment by illi-kun** [comment]
Why? I'm not saying it's incorrect/bad but it would be better to see your arguments.

**Comment by BorkBorkGoesTheCode** [comment]
The Wikipedia and several sites said the 7.62x25 could penetrate NIJ level II A vests. The 7.62x25mm hot load is supposed to represent the most powerful loading I have found. I buffed the Type P to balance the weight nerf I applied.

**Comment by mugling** [comment]
> I buffed the Type P to balance the weight nerf I applied.

It already has the benefit of being much quieter so I'm not sure this is balanced. Is there any evidence for this having siginifcant `pierce` IRL?

**Comment by DLaboratory** [comment]
According to a Chinese textbook, Type 54 Pistol (imitation of Soviet TT-33 pistol) is able to pierce into steel plate 3mm deep, into brick wall 6cm deep, into wood plate 10cm deep and into soil 35mm deep.

**Comment by kevingranade** [comment]
> According to a Chinese textbook...

Compared to what? Do we have similar numbers for comparable rounds?

**Comment by DLaboratory** [comment]
I just offered the data that how deep 7.62x25mm can pierce into with different kind of materials

**Comment by kevingranade** [comment]
Sorry, misread the context.  If we get some more of those we might be able
to do something with them.
There might be " wound channel depth" numbers somewhat available.

**Comment by BorkBorkGoesTheCode** [comment]
Would ballistic gelatin penetration data be useful?

**Comment by kevingranade** [comment]
Yes, very.

**Comment by BorkBorkGoesTheCode** [comment]
brassfetcher.com claims to have ballistic gelatin and bulletproof vest data, but I cannot vouch for the safety of the site or the accuracy of the data.

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade have you checked out the site?

**Comment by kevingranade** [comment]
I'm not sure what you want me to do, the next time I'm looking at this,
I'll be sure to take a look at the site, but I don't know when that will
be. If they have ballistic test results of any kind I think it will be
useful.

A side issue, issue comments aren't a good way to coordinate, for one thing
it's broadcasting every comment to people who are subscribed via email,
this kind of thing is much better handled via irc or forums, both of which
we use.

**Comment by BorkBorkGoesTheCode** [comment]
Okay. brassfetcher says 85gr. FMJ 7.62x25mm can penetrate 13.4 inches into 10% ballistic gel after piercing a NIJ level II vest, and 37.1 inches into unarmored 10% ballistic gel. The range to target was 10 feet. The barrel length was 4.6 inches.

**Pull request closed without merging**
