### PR TITLE
Fix flake8 F821 errors

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: None

#### Purpose of change
Python static analysis.

#### Describe the solution
This checks for use of undefined variables.

Enable flake8 check F821 and work around the cases it reports.

The only warnings for this check were false-positives, but it seems like a good check to have.

#### Describe alternatives you've considered
Suppressing the uses of `defines` rather than tricking flake8 into thinking it was defined.

#### Testing
Running `flake8`.

Would be nice to check that `dmgbuild` still works, but that looks like it requires running on OSX, which I'm not in a position to do.

#### Additional context

### CODE REVIEW

**Comment by jbytheway** [comment]
Hmm..  Apparently LGTM is unhappy with my workaround.  Will reconsider.

**Comment by kevingranade** [comment]
LGTM has been reporting erroneous unreachable code errors in python code since we've been using it, I've been considering supressing it.

**Comment by jbytheway** [comment]
Trying a different crazy workaround; we'll see what LGTM thinks of this one.

**Comment by jbytheway** [comment]
Seems happy.

**Pull request merged**
