### PR TITLE
Add butcher

### PR DESCRIPTION
**Pull request by nornagon**
Also from [my mod](https://github.com/nornagon/cdda-more-city-locations).

### CODE REVIEW

**Comment by cainiaowu** [comment]
name unclear, will confuse translator.

**Comment by Coolthulhu** [comment]
You could add some extra offal and blood fields.

**Comment by lucianposton** [comment]
The en-us name is "Butcher Shop".

**Comment by nornagon** [comment]
Added blood and gib fields, and renamed to 'butcher shop' to hopefully be clearer. (The en-AU name for such a place is just 'butcher', so thanks for the clarification!)

I wasn't sure what the difference was between a 'field' of blood and the liquid blood, but other mapgens appear to use `fd_blood`, so I copied those. This also appears to be the first mapgen use of `fd_gibs_flesh`, let me know if that's not what you meant when you said 'offal'.

**Comment by Coolthulhu** [comment]
Offal is an item type. When you butcher a corpse of an animal, you get chunks and offal.

**Comment by nornagon** [comment]
oh, right, d'oh :P I read "(offal and blood) fields" instead of "(offal) and (blood fields)". Anyway, done. Should I remove the gibs? They kind of look like they belong.

**Pull request merged**
