### PR TITLE
Add IGNORE_SOUND, NO_BASH and RETURN_TO_START_POS traits for NPC's

### PR DESCRIPTION
**Pull request by mythosmod**
#### Summary

Bugfixes "Create IGNORE_SOUND, NO_BASH and RETURN_TO_START_POS trait and add to faction NPC's"

#### Purpose of change

Alternative fix for #56990 (superseding #62408 as I think this is a better solution) - makes NPC's with the IGNORE_SOUND not investigate sounds, NO_BASH not bash to path to anything and RETURN_TO_START_POS return to the position they initially spawned in when the current task has completed but does not affect any other behavior.

#### Describe the solution

- Add IGNORE_SOUND mutation in JSON
- Add IGNORE_SOUND trait into npcmove.cpp
- Under npc::move(), if the NPC has the IGNORE_SOUND trait switch to move back to position and clear sounds from queue instead of investigating sounds
- Add NO_BASH mutation in JSON
- Add INO_BASH trait into npc.cpp
- Under &npc::get_pathfinding_settings, if the NPC has the NO_BASH trait set path_settings->bash_strength to 0 when returning
- Add RETURN_TO_START_POS mutation in JSON
- Add RETURN_TO_START_POS trait into npcmove.cpp
- Under npc::regen_ai_cache(), if the NPC has the RETURN_TO_START_POS trait set ai_cache.guard_pos which will set to inital position where the NPC spawns, NPC will then return to this position after fighting  
- Add traits to Smokes, the refugee doctor, the broker, Rubik, the Artisans (Jay and Cody) and the merchant caravan guards

#### Describe alternatives you've considered

Alternative solution in #62408 - however this one does not stop the NPC from fighting, fleeing etc. so I think this is a better solution

#### Testing

Complied and built to Cataclysm-lib-vcpkg-static
Created standard world and loaded default scenario
Added refugee center location from PC
Teleported to refugee center
Yelled around the corner, Smokes reacted but did not move to investigate like the guards
Attacked Smokes - fought back as expected

Spawned zombie in lobby, Smokes did not smash glass to path to it
Removed door, spawned zombie again, Smokes started to path to fight it and then smash the corpse, then returned to initial position afterwards

Spawned zombie outside open door, Smokes pathed to fight it and then returned to inital position

#### Additional context

Yelling out of sight

IGNORESOUNDS1

Guards investigate, Smokes does not

IGNORESOUNDS2

Smokes still attacks if attacked

IGNORESOUNDS3

Zombie spawned in lobby

IGNORESOUNDS4

Guards kill, Smokes does not smash glass to get to as he did previously

IGNORESOUNDS5

Remove door, spawn zombie

IGNORESOUNDS6

Smokes kills Zombie

IGNORESOUNDS7

Smokes returns to initial spot

IGNORESOUNDS8

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Will he smash the glass out if a zombie walks into the main room?

**Comment by Night-Pryanik** [comment]
Nitpick, but trait names with underscores are more comfortable to read.

**Comment by mythosmod** [comment]
> Nitpick, but trait names with underscores are more comfortable to read.

Fixed, thank you - will bear that in mind for future

More testing done on individual traits

Remove IGNORE_SOUNDS, keep NO_BASH and RETURN_TO_START_POS

Yell round corner

nb-returntostart1

Guards investigate, Smokes does not as not able to path

nb-returntostart2

Change closed door to open door, Smokes now comes to investigate after yelling

nb-returntostart3

And then returns to his start position

nb-returntostart4

Remove NO_BASH, just leave RETURN_TO START_POS

nb-returntostart5

Change door back to locked one and yell, Smokes smashes glass and comes to investigate

nb-returntostart6

Then returns to his start position

nb-returntostart7

**Comment by I-am-Erk** [comment]
Well. That solves a lot of problems.
We should add no_bash and return_to_start pos to pretty much all static NPCs, especially those that can't be hired as followers (I assume it will mess with those that can follow). That could be done in this PR or we could do a follow up per faction.

**Comment by I-am-Erk** [comment]
Merged this because I think it's better we try these out on the NPCs that have them, and we should start adding them to more quest giving NPCs right away.

**Pull request merged**
