### PR TITLE
[Ready] [CR] Rework SDL window updates to clear oversized framebuffers when regular windows are rendered. (Large GIFs)

### PR DESCRIPTION
**Pull request by DanmakuDan**
A less intrusive attempt at #17042.

In `cursesport.cpp` (SDL Tiles implementation of ncurses), a method was made available to pass the window object to `sdltiles.cpp`, so it can clear the framebuffer to match what the `werase` call would do in the special cases where a window is supporting a font other than the main terminal font.

The `Font::draw_window` method has an extra call added to erase the custom font framebuffer depending on a proportion of the window passed in. This handles the issue seen with ghosting by multiplying the base font size to figure out what region the base font covers the map/overmap fonts. The downside is that the previously active window (overmap or terrain) isn't known at the time of drawing a terminal window, so the custom font framebuffer is cleared using both map_font and overmap_font proportions.

Todo:
- [x] add const
- [x] remove framebuffer references from other places
- [x] pictures

Before:
map_bad
menu_bad
vehicle_bad

After:
map2
menu
vehicle

### CODE REVIEW

**Comment by Soadreqm** [comment]
I feel like congratulations are in order.

**Comment by 6580001** [comment]
Congratulations!

**Comment by Fallingferret** [comment]
#ASCIILivesMatter

**Comment by illi-kun** [comment]
This PR brakes Windows-Curses builds (see Jenkins builds).

**Pull request merged**
