### PR TITLE
adds a recipe for calcium_tablet 

### PR DESCRIPTION
**Pull request by lcy03406**
I'm playing with "novitamins" off and find keeping my calcium up is especially difficult. But I'm living on an ant hill. I think a home made calcium tablet would be reasonable.

### CODE REVIEW

**Comment by Treah** [comment]
why is there vinegar in the recipe?

**Comment by kevingranade** [comment]
More generally, is there really a process to extract usable dietary calcium from bone meal or insect carapaces by boiling them in vinegar?

**Comment by ituluwituluwzev** [comment]
How to make CaCO3 from shell: Grind the shell to powder; Bake the powder until it turns into CaO; Add water, and it turns into Ca(OH)2; Blow some CO2 into the solution, and the CaCO3 deposits.

**Comment by lcy03406** [comment]
thank you @ituluwituluwzev 

I didn't think that much in reality. My thought was: Firstly we can't just add water into chitin meals and get the pills, that would be too easy. So some sort of acid 'looks' good. But when I looks into the recipe of acid, it says it's destilled from salt water aka acid rains. It sounds awful and also too easy. So I choose vinegar. Having a steady supply of vinegar means one have sattled and actively farming fruits, and I think calcium tablets worth the effort.

For "Bake the powder until it turns into CaO" I think the time and fuel should be increased. But we don't have a good way to simulate "Blow some CO2 into the solution", maybe add some charcoal?

**Comment by kevingranade** [comment]
You've already got glassware in there (chemistry quality), can someone who knows chemistry stuff suggest a CO2 source?

**Comment by lcy03406** [comment]
Plan A: Burn charcoal to produce CO2 and pipe it into the solution using the heat of burning charcoal.

Plan B: Just pour some vinegar in and hope for calcium acetate instead.

**Comment by ituluwituluwzev** [comment]
Our resourceful survivor can blow air through a glass pipe when they has to...

The problem is that bone and chitin don't contain CaCO3. Limestone is CaCO3, but the impurity is not safe for eating and difficult to get rid of. Shell is good, but it is rare in the game at the moment.

**Comment by kevingranade** [comment]
I think I misread earlier, the shell you mentioned earlier was not chitin,
it's snail shell? Crab?

It sounds like this is a reasonable approach if you replace bone meal and
chitin with shell, if we even have it in the game.

As for the original issue (keeping calcium levels high), it's a lot more
reasonable to add food-based mineral sources than to try to process raw
materials into supplements.

Take a look at something like
https://greatist.com/health/18-surprising-dairy-free-sources-calcium for
ideas.

**Comment by lcy03406** [comment]
> As for the original issue (keeping calcium levels high), it's a lot more
reasonable to add food-based mineral sources

So the problem becomes "can we give different vegetables different sets of nutrition and keep tracking of them and maybe transform them according different cooking processes". I've noticed rhubarb has more calcium than other veggy but I don't know how it is implemented.

**Comment by ituluwituluwzev** [comment]
Shell of snail, mussel, clam, & other mollusks.

**Pull request merged**
