### PR TITLE
use number instead of string for style_brawling autolearn

### PR DESCRIPTION
**Pull request by nornagon**
#### Summary
None

#### Purpose of change

Normalizes the JSON data. Every other martial art uses numbers here :)

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]

**Comment by ZhilkinSerg** [comment]
What about code? It expects string:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cd6044d4052335b769dfb8555e1cb8c9a85bbc1c/src/martialarts.cpp#L262-L268

**Comment by Pynter** [comment]
This does indeed break the game when creating a new character, at least for me.

` DEBUG    : Error: Json error: data/json/martialarts.json:121:31: expected string but got '1'

hen unarmed or with any weapon to a certain extent.  It's not stylish or sporting, but it gets the job done.",
    "initiate": [ "You grit your teeth and prepare for a good fight.", "%s gets ready to brawl." ],
    "autolearn": [ [ "melee", 1
                              ^
                                ] ],
    "arm_block": 1,
    "static_buffs": [


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 857
 VERSION  : a558c81
`

**Comment by nornagon** [comment]
> What about code? It expects string:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/cd6044d4052335b769dfb8555e1cb8c9a85bbc1c/src/martialarts.cpp#L262-L268

Ack, right you are. I was thinking of the recipe code, which uses a number there.

It seems like this _ought_ to be a number, to match the recipes (and because the `stoi` is extraneous). I'll prep a new PR that updates the code + the JSON together.

**Comment by nornagon** [comment]
ah, looks like it was already done in b5ce160423c.

**Pull request merged**
