### PR TITLE
Necropolis, The Sunken City Pt 3

### PR DESCRIPTION
**Pull request by acidia**
Now the brave can venture further into the vault.  The difficulty doesn't really spike but an increase is noticeable.  The second level of the vault proper contains mainly housing areas with a few mechanical/utility rooms thrown in.  Quest and NPC work will be a while out.  

Third level is nothing but sketches at the moment but looks like it will focus on storage and utility spaces.  Fourth will be the reactor level.  

EDIT:  Special thanks to BevapDin, the new mapgen functions saved a huge amount of time.  Compare the item entry on line 5094 to the older version on line 505.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
It gets better! Very nice work, @acidia!

**Comment by Zireael07** [comment]
Woot!

**Comment by KA101** [comment]
>Makes me want to suicide the current char just to see all the newness!

Just explore another overmap or two and you'll probably find one.  :-/

**Comment by KA101** [comment]
Missed that fix.  This gets mergetested next run, if nobody beats me to it.

**Pull request merged**
