### PR TITLE
Rebalance base_colors-dark.json

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Interface "rebalanced lighting levels for colors"

#### Purpose of change
For better readability all colors slightly changed.
Highlighting color (previously blue, changed to black)

#### Describe the solution
All colors divided by luminosity (lightness) levels.
0 - highlighting color (actually it's black here)
25 - background color (gray)
50 - all dark colors
75 - all light colors
100 - white color

#### Describe alternatives you've considered
probably highlighting color should be blue, but it lowers its contrast to everything else.

#### Testing
image
image
image
image

### CODE REVIEW

**Comment by vetall812** [comment]
sorry, realized that lighting levels are uneven...

**Comment by vetall812** [comment]
@bombasticSlacks , I know that you use dark theme - could you please test this one and give me some feedback.

**Comment by bombasticSlacks** [comment]
It looks good to me. 

However when I load it up in game I still have a blue background 
image

**Comment by vetall812** [comment]
> It looks good to me. 
> 
> However when I load it up in game I still have a blue background 
> image
> 

To reload scheme you have to change it to something else, restart the game, change to dark theme again. And restart again of course.

Also, as this is the draft, you have to manually download scheme update. (but i think that you know this better than me)

**Comment by vetall812** [comment]
> However when I load it up in game I still have a blue background ![image](https://user-
I'm sorry. NOW it can be tested. Thank you for your patience and understanding.

**Comment by bombasticSlacks** [comment]
> I'm sorry. NOW it can be tested. Thank you for your patience and understanding.

I figured you would figure it out 😉

**Pull request merged**
