### PR TITLE
ChestHole Tilesets Update: Adds back anti-mat turrets and zharks and a few more

### LINKED ISSUE #23296: ChestHole tile for spotted landmine too subtle
Game version: cataclysmdda-0.C-7227

Operating system: windows 7

Tiles or curses: tiles

Mods active: Default ones

### Expected behavior
I walk into a mine and get blown up

### Actual behavior
Game asks me if I want to step onto the mine (that is unrevealed to me)

### Steps to reproduce the behavior
Load the game from attachment try stepping north.
[Merrillville - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1845214/Merrillville.-.Copy.zip)

### PR DESCRIPTION
**Pull request by Chezzo**
Have flu... So sick... must change invisizombies...

closes #23296

### CODE REVIEW

**Comment by ZenZen2** [comment]
The vehicle camera is floating above the ground when broken.
```
        {
          "id": "vp_omnicam",
          "fg": 2735,
          "bg": 678,
    "multitile": true,
          "additional_tiles": [
            {
              "id": "broken",
              "fg": 3119
            }
          ]
        },
```
I think a fast way to fix that is adding ``` "bg": 678 ``` to the broken state.

**Comment by ZenZen2** [comment]
Just a minor thing: ``` f_coffin_o ``` rotation need to be turned off.

**Comment by ZenZen2** [comment]
``` omnicamera ``` can not get into a broken state, need to place that ``` "bg": 678 ``` to the vehicle part ``` vp_omnicam ```

**Comment by illi-kun** [comment]
@Chezzo Take care!
@ZenZen2 Please put unimplemented requests to a separate issue. Thanks!

**Pull request merged**
