### PR TITLE
Move some mutation modifiers to jsons.

### PR DESCRIPTION
**Pull request by Vasyan2006**
#### Summary
 ```SUMMARY: Infrastructure "Move some mutation modifiers to jsons."```

#### Purpose of change
Move some mutation modifiers to jsons.

#### Describe the solution
Add new jsonified modifiers for mutations, remove hardcoded modifiers.
Add 2 new templates to calculate net modifier from different mutations. One will add modifiers additively (used for dodge), another will multiply them multiplicatively (used for carry weight).
Some modified mutations have additional hardcoded effects (bad back not only decrease carry weight, but also apply pain if overburdened), this effects will not be changed and will work as before.

#### Additional context
List of new json modifiers:

```
str_modifier // change strength without changing HP 
dodge_modifier
speed_modifier
movecost_modifier
movecost_flatground_modifier
movecost_obstacle_modifier
attackcost_modifier
max_stamina_modifier
weight_capacity_modifier
hearing_modifier
noise_modifier
```

### CODE REVIEW

**Comment by Brian-Otten** [comment]
Seems like any constant mutations should be showing their effect in the mutations list description, not in the temporary buff list. That seems like it would be a good change. Since the passive buff list can be changing turn to turn you want to keep it relatively terse.

**Comment by Vasyan2006** [comment]
There are some gameplay differences between changing base stats and adding modifier. "Very strong" mutation will increase base strength and all related attributes like HP. Using strength modifiers in mutations will increase strength and carrying capacity, but HP will be the same.
The only UI difference is green stat digits, as if using bionics or temporary buffs.

**Comment by Brian-Otten** [comment]
IMO it would be suitable as a base stat increase, since it's "part of who you are now", it avoids some confusion over the source of stat buffs, and keeps the temporary buff list from being overcrowded. 
But it would be good to get a second opinion on this from some people.

**Comment by Vasyan2006** [comment]
>and keeps the temporary buff list from being overcrowded.

Nothing will be added to the effects list. You can get "arm tentacles" mutation right now and see how +1dex bonus is applied. It will be the same after this update.

**Comment by Vasyan2006** [comment]
Checked the entire code and base values for dex, int and per are not used anywhere, only resulting values with effects are important. So these modifiers are removed and corresponding mutations now add normal passive bonuses.
Strength modifier ``str_modifier`` will stay separated from ``"passive_mods" : { "str_mod" : 2 }``, because it allows to change character strength without changing HP.

**Pull request merged**
