### PR TITLE
Add welding consumables

### PR DESCRIPTION
**Pull request by Alex-Folts**
#### Summary
Content "Adds new consumable items which used during welding operations(craft, install or repair vehicle parts)"

#### Purpose of change
Welding always seemed a bit off, only welder charges consumed which is essentially free in mid-late game, also it is not inline with other tools like soldering iron where additionally to charges we need also solder.

#### Describe the solution
Added 6 new consumable items for welding:

- welding rods for steel and aluminium
- welding wire for steel and aluminium
- brazing rods for steel and aluminium

All new items are craftable and were added to item groups for spawn near welder/acetylene torch.

Added this consumables to "welding_standard" requirement, also added 3 addition welding requirements for future split of welding into welding steel, welding aluminium, repair steel with welder, repair aluminium with welder.

#### Describe alternatives you've considered
Implement possibility for tools to use more than one set of charges, so we can have battery charges for welder and at the same time one of the consumable items, welding gas, etc.

#### Testing
Crafted new items, spawn them with debug menu, tried installing and repair vehicle - make sure items consumed. Teleport character to different locations(e.g. garage) and check that items spawns properly.

#### Additional context
This is one of steps toward revamping of welding process, in the future we'll need to split usage of welding into separate welder requirements: for steel and aluminium, and use proper consumables(this already partially implemented here), audit welding usage for installing vehicle parts(some of them should use different mounting method), rebalance usage of welding charges and consumables.
Brazing rods is more for acetylene torch, while welding wire for MIG/MAG welder, but at the moment it is not possible to have separate set of components based on used tool, so all 3 types of consumables were added everywhere where any of welding tools used.

The wording in items description contain mistakes, would be nice if someone check them and suggest corrections.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
At long last

**Comment by Alex-Folts** [comment]
I see "tests/vehicle_interact_test.cpp" repair test fails because it cant repair without new items, seems need to update test.

Also some errors in "faction_base_modular_firestation1_workbench" and a like, i'm right understand that need to add new items to  "blueprint_needs" section?

Error about hazmat suit is not mine.

**Comment by Maleclypse** [comment]
> I see "tests/vehicle_interact_test.cpp" repair test fails because it cant repair without new items, seems need to update test.
> 
> Also some errors in "faction_base_modular_firestation1_workbench" and a like, i'm right understand that need to add new items to "blueprint_needs" section?
> 
> Error about hazmat suit is not mine.

You are correct.

**Comment by PatrikLundell** [comment]
Regarding the workbench, there are two ways to fix that:
1. Update the recipe to match the changed needs.
2. Update the recipe to use the newer method of letting the recipe figure out the requirements itself based on what it constructs. I believe this means the "skill_used" and "blueprint_needs" sections would be removed. This is the method I would recommend.
 
Regardless of which approach is used, I believe it will have to be tested, unfortunately (i.e. build a base camp in a fire station up to the level required for that recipe to be used). Bonus points for modernizing all the recipes, but that's more or less a PR on its own.

**Comment by Alex-Folts** [comment]
> Edit: I went ahead and updated the fire station base camp as #53448, and that update includes alternative 2 above. This has the disadvantage that this PR will have to wait for that PR to be merged before it works (assuming, of course, the issue has been identified correctly).

This is good, but the thing is there whole list of similar recipes, so i think i still need to fix them, i just didnt know how, seems like removing "blueprint_needs" section is the way to go.

the list it:
```
faction_base_modular_firestation1_workbench
faction_base_modular_shelter_craftspot
faction_base_modular_shelter_1_craftspot
faction_base_modular_workshop_room2_common_northeast
faction_base_modular_workshop_room6_log_north
faction_base_modular_workshop_room6_metal_north
faction_base_modular_workshop_room6_migo_resin_north
faction_base_modular_workshop_room6_rock_north
faction_base_modular_workshop_room6_wad_north
faction_base_modular_workshop_room6_wood_north
```

I'll update test "tests/vehicle_interact_test.cpp" first.

**Comment by PatrikLundell** [comment]
Ah, I didn't realize it was just an example.
- The modular shelter craft spots should work with that adjustment. It's curious that modular shelter 2 isn't in the list, though, as I thought all three of them did the same things to slightly different shelter layouts.
- The workshop room 6 recipe should also work with that change. Placement of tools can be considered to take no significant time on top of the construction work, so that should be fine.
- The same goes for workshop room 2.

Still, unfortunately, the changes ought to be tested, although I personally would be fine with just testing one of the room 6 material variants, relying on the JSON checks to pick up any syntactic mistakes in the other versions.

**Comment by Alex-Folts** [comment]
I've decide to fix only those 9 problemstic recipes in this PR since they directly related to this PR. I removed only "blueprint_needs" sections.

Rest recipes will need to be fixed in separate PR.

**Comment by PatrikLundell** [comment]
As far as I can see those changes are reasonable.

**Pull request merged**
