### PR TITLE
Makes selected sorting method of visible item_list persistent

### PR DESCRIPTION
**Pull request by tvm1**
What it says.
#12296 mentioned this.

### CODE REVIEW

**Comment by BevapDin** [comment]
Something's strange: enter "list items" view, select sorting by category, press TAB to switch to monster list (works nicely so far). Press TAB again to switch back to items list. It's now sorted by distance, but has category headers:
```
CLOTHING
sweater [2] 1 NW
hat         1 NW
DRUGS
cigarette   1 NW
CLOTHING
sweater     2 E
hat         2 E
```

Is that intended?

**Comment by tvm1** [comment]
You are right, I didn't notice this during my test.

/me sets [WIP]

**Comment by tvm1** [comment]
Fixed, tested & ready to go!

**Comment by DavidKeaton** [comment]
nice addition duder!

**Comment by tvm1** [comment]
@DavidKeaton Thanks!

**Comment by Coolthulhu** [comment]
Found a bug. Not with this PR, but related: high/low priority sorting doesn't work.

**Pull request merged**
