### PR TITLE
Adds Cinnamon

### PR DESCRIPTION
**Pull request by Cyrano7**
After some debating its clear that having a ton of spices in the game wouldn't serve much purpose so instead of adding a few spices it would be better to add just one generic spice like cinnamon. Adds cinnamon for use in a upcoming eggnog recipe. I'm sure it could be added to a few recipes or some new recipes. Spawns in coffee shops, kitchens, kitchen tables and grocery stores but its more rare then other things like salt and pepper.

### CODE REVIEW

**Comment by AppleConnoiseur** [comment]
Maybe... Maybe add a recipe for cream stewed macaronis as well! Also you can apparently get high on nutmeg but in high enough concentration it is toxic.

**Comment by Cyrano7** [comment]
Ya we were talking about that earlier. Maybe need to revisit that later haha.

**Comment by sparr** [comment]
if we want to make nutmeg hallucinogenic or toxic, we'll need a way to make it take more than one dose. I believe currently all of the drug actions take effect after taking a single dose.

**Comment by Cyrano7** [comment]
@sparr hmm this is true. That's fine I don't think we really need ppl tripping off nutmeg in this game. Maybe some more spices though.

**Comment by sparr** [comment]
Also, spices might be a little *too* detailed. We don't need 20 more zero-volume items (available for looting in any city) clogging up our inventory / bases just to be able to complete recipes.

**Comment by Cyrano7** [comment]
@sparr This is true. Maybe just cinnamon. That would do it for eggnog and plenty of other things.

**Comment by railmonkey** [comment]
In fairness, I was actually going to be settling for wild herbs for the recipes that brought on this PR, but I'm personally all for more clutter. Then again, I'm pretty strongly roleplay-oriented. Would help a lot if we could actually put solid items into containers instead of being stuck with liquids in watertight containers, though.

**Comment by Cyrano7** [comment]
@railmonkey I think i'm going to close this actually and add cinnamon instead. Wild herbs is a good idea though.

**Comment by Cyrano7** [comment]
Its not updating the files so give me a second to try and fix it.

**Comment by Cyrano7** [comment]
Someone already has a new recipe ChJees wrote on free node "Chaï tea could be made with tea leaves, black pepper, cinnamon, sugar, water OR clean water & milk OR condensed milk "

**Comment by kevingranade** [comment]
> Also, spices might be a little too detailed. We don't need 20 more
zero-volume items (available for looting in any city) clogging up our
inventory / bases just to be able to complete recipes.

No such thing, we're eventually going to have nesting containers to manage
this kind of thing, so I'd prefer to not discourage people from adding more
detail.

**Comment by chaosvolt** [comment]
And rather belatedly, I would note that it should be possible to use the "scaling" drug effects for intoxication that only comes into play after accumulating enough doses of an item.

But I've never really played around with it, as my most complex drug-effect coding so far has been making red potions not kill the user via stacking painkiller effects. >.>

**Comment by Cyrano7** [comment]
@chaosvolt I had a thought actually. They have compound reactions and thresholds to drugs already like with alcohol. All we really need to do is have nutmeg have no effect until you reach a certain threshold. It would be kinda fun to add that. But it definitely is at the bottom of my list for things to do haha.

**Comment by nanovad** [comment]
In reference to the fact that drugs take effect after one dose - you could make a "concentrated nutmeg drug" or the like that requires 4 nutmeg to craft. Looks like the nutmeg got nerfed though.

**Comment by Rivet-the-Zombie** [comment]
This would work nicely as an alternative ingredient in seasoned salt, in place of sugar.

**Comment by Cyrano7** [comment]
@Rivet-the-Zombie I'll have to keep that in mind. I have a little list of recipes to add or update already haha.

**Comment by Cyrano7** [comment]
check failed? error: cannot lock ref 'refs/remotes/origin/pr/14338/head': 'refs/remotes/origin/pr/14338' exists; cannot create 'refs/remotes/origin/pr/14338/head'

**Pull request merged**
