### PR TITLE
Convert some tailor kits to sewing kits

### PR DESCRIPTION
**Pull request by mark7**
#### Summary
SUMMARY: Balance "Convert some tailor kits to sewing kits"

#### Purpose of change
As it stands, the tailor kit and the sewing kit show up at fairly-equal frequency, despite the fact that the tailor kit is a "better" sewing kit.  This means that the tailor kit isn't a particularly-interesting find; I'm about as likely to just run into a tailor kit as I am a sewing kit.

#### Describe the solution
To help keep the tailor kit an interesting find, cause it to show up at a 1:4 ratio to the sewing kit in most item groups, rather than a 2:3.  The overall frequency of sewing/tailor kits relative to other items is unchanged, to avoid modifying overall balance of tailoring items relative to other items (that is, it's still as easy as before the patch to find an item to repair clothing, but not to modify it).

### CODE REVIEW

**Comment by ymber** [comment]
I think a better way to go about it is making tailors kit spawns more specific. Very uncommon for most people to have but you're pretty likely to find one in some of the clothing store variations.

**Comment by mark7** [comment]
Yeah, I thought about it, because it creates an incentive to look for specialized stores, but when I went digging through the json, there wasn't really a great set of stores to which this would apply.  That is, there isn't a drycleaners or tailor/seamstress shop, which are the places that I'd normally expect to see tailoring work done.  I agree that creating maps for stores of that sort would be cool, but I'm also lazy...

Pottery_Sewing_shops.json is sort of a crafts store and has the sewing_group, and I left the ratio unchanged there (maybe it should be increased there?), but it's not very common.  With only the lone store map, ramping the frequency up would make it repetitive; if the go-to route for "tailor kit" is "find a specialized store", then there should probably be more than one map.

I guess one could argue that a clothing store might have tailor kits, but normally what I'd think of as a typical clothing store in the US doesn't do tailoring work -- they're just selling rows of factory-manufactured clothes.  I guess there are some, like Men's Warehouse, say, but normally when I go somewhere that sells clothes, they're just selling racks of factory-made clothing.

**Comment by RarkGrames** [comment]
Megastores, home improvement stores, thrift stores, malls could have tailor's kits.

**Comment by mark7** [comment]
Yeah, I suppose that's fair, especially since malls and megastores today are something that I tend to avoid due to there not beinng much reason to go there.  All right, sounds good; I'll cut the frequency in homes significantly and stock some of the existing stores.  Amended commit to follow.

**Comment by ymber** [comment]
One of the clothing store maps has a tailoring room in the back too.

**Comment by mark7** [comment]
Okay, so:

* Further cut odds of finding a tailor kit in the existing categories that I'd changed it.
* Mall's leather shop had a repair category; tilted odds towards a tailor kit there.  
* Mall tux shop already had a tailor kit.  Left alone.
* It looks like megastores are only in an example mod today.  Left them alone.
* Unfortunately, tools_tailor is presently used by clothing stores -- which can indeed have a tailoring section, good catch @ymber -- and most other "commercial" entities, but also by homes.  Created tools_commercial_tailor, weighted towards items that one might find a professional using (i.e. not "hobby" knitting, but using a tailoring kit).  Switched clothing stores to use the tools_commercial_tailor instead, and biased it towards tailor kits.

**Comment by mark7** [comment]
Oh, dammit, left a rebase in.  One sec.

**Comment by mark7** [comment]
Will reopen a new pull request based on HEAD.

**Pull request closed without merging**
