### PR TITLE
Fix loading of npcs in savegames

### LINKED ISSUE #33937: Save does not load properly on latest version. Error "Failed to read from "[file]": line 31:8235: Expected number"
# Describe the bug

Save does not load properly on the newest version.

Errors:
```
 DEBUG    : Failed to read from "./save/kakkonen/o.0.-1": line 31:8235: Expected number

shot_00","owner":"wasteland_scavengers","relic_data":null},"last_target_pos":null,"faction_warnings":[],"ammo_location":{"type":"null"},"camps":[],"name":"Mikaela Kouko, Survivor","marked_for_death":false,"dead":false,"patience":0,"myclass":"
                                                                                                                                                                                                                                                ^
                                                                                                                                                                                                                                                 NC_COWBOY","personality":{"aggression":-7,"bravery":13,"collector":2,"altruism":-4},"submap_coords":[333,-156],"last_player_seen_pos":null,"goalx":166,"goaly":-78,"goalz":0,"guardx":3971,"guardy":-1858,"guardz":0,"current_activity_id":"ACT_
 
 FUNCTION : bool read_from_file(const string&, const std::function<void(std::basic_istream<char>&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 433


 DEBUG    : Failed to read from "./save/kakkonen/o.0.0": line 31:6746: Expected number

,"bday":0,"last_rot_check":0,"last_temp_check":0,"relic_data":null},"last_target_pos":null,"faction_warnings":[],"ammo_location":{"type":"null"},"camps":[],"name":"Milko Vienonen","marked_for_death":false,"dead":false,"patience":0,"myclass":"
                                                                                                                                                                                                                                                ^
                                                                                                                                                                                                                                                 NC_DOCTOR","personality":{"aggression":8,"bravery":2,"collector":6,"altruism":0},"submap_coords":[214,152],"last_player_seen_pos":null,"goalx":-2147483648,"goaly":-2147483648,"goalz":-2147483648,"guardx":-2147483648,"guardy":-2147483648,"gu
 
 FUNCTION : bool read_from_file(const string&, const std::function<void(std::basic_istream<char>&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 433



 DEBUG    : Failed to read from "./save/kakkonen/o.-1.-1": line 31:7621: Expected number

ull}],"owner":"hells_raiders","relic_data":null}],"last_target_pos":null,"faction_warnings":[],"ammo_location":{"type":"null"},"camps":[],"name":"Ismo 'Cheesehead' Leussu, Bandit","marked_for_death":false,"dead":false,"patience":0,"myclass":"
                                                                                                                                                                                                                                                ^
                                                                                                                                                                                                                                                 NC_SCAVENGER","personality":{"aggression":5,"bravery":9,"collector":4,"altruism":9},"submap_coords":[-51,-160],"last_player_seen_pos":null,"goalx":-2147483648,"goaly":-2147483648,"goalz":-2147483648,"guardx":-2147483648,"guardy":-2147483648
 
 FUNCTION : bool read_from_file(const string&, const std::function<void(std::basic_istream<char>&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 433
```

Game Version: 0.D-7417-gc9dc288 [64-bit] loads the save fine but version 0.D-7457-gaaf90dc [64-bit] throws errors.

If the errors are ignored the save will load. But the explored map is lost (the world is still there as it was before but it doesn't show up as explored on the map). Also all NPC followers are gone.

# Steps To Reproduce

Grab this save: https://drive.google.com/file/d/1g3GRx8LyZA-zJgTRun_Q-S5hktSw-dzN/view?usp=sharing
(optional: Grab these mods to avoid errors about missing mods https://github.com/Hirmuolio/CDDA-mods)
Try to load it on few days old experimental. It works.
Try to load on latest experimental. It doesn't load properly.

# Expected behavior
Save loads properly.

# Screenshots


# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7457-gaaf90dc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    Mundane Zombies [Mundane_Zombies],
    Vertakoski [vertakoski],
    Caliber in weapon name [caliber_in_name],
    No Ants [No_Anthills],
    No Bees [No_Bees],
    No nether creatures [no_nether],
    Safe Autodoc [safeautodoc]
]



# Additional context

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Bugfixes "Fix loading of npcs in savegames"```

#### Purpose of change

Fixes #33937

### CODE REVIEW

**Comment by throttlekitty** [comment]
I was asked to provide my savegame for testing.

https://drive.google.com/open?id=10WeLj8bEUJ9fIUU6zEPmuDMOuz8Jc0zH

**Comment by davidpwbrown** [comment]
Tested and apparently fixes the loading issue for my save.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I was asked to provide my savegame for testing.
> 
> https://drive.google.com/open?id=10WeLj8bEUJ9fIUU6zEPmuDMOuz8Jc0zH

Seems to be loading okay with current fix.

**Comment by ZhilkinSerg** [comment]
I will self-merge to fix this emergency savegame issue.

**Comment by jbytheway** [comment]
Thanks for fixing.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/build-9612-broke-all-my-mods/21302/22

**Pull request merged**
